DayzKode: P:/scripts/3_game/DayZ/systems/inventory/debug.c File Reference
debug.c File Reference
Functions
void actionDebugPrint (string s)
void inventoryDebugPrint (string s)
void syncDebugPrint (string s)
Function Documentation
actionDebugPrint()
void actionDebugPrint (string s)
Definition at line 10 of file debug.c.
{
#ifdef INV_DEBUG
    PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
    Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References Print(), and PrintToRPT().
Referenced by PlayEmote().
inventoryDebugPrint()
void inventoryDebugPrint (string s)
Definition at line 19 of file debug.c.
{
#ifdef INV_DEBUG
    PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
    //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by DropEntity(), DropEntityInBounds(), DropEntityWithTransform(), EEInit(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), LocalDestroyEntity(), ReplaceItemWithNew(), TakeEntityAsAttachment(), TakeEntityAsAttachmentEx(), TakeEntityAsTargetAttachment(), TakeEntityAsTargetAttachmentEx(), TakeEntityToCargo(), TakeEntityToCargoEx(), TakeEntityToInventory(), TakeEntityToTargetCargo(), TakeEntityToTargetCargoEx(), and TakeEntityToTargetInventory().
syncDebugPrint()
void syncDebugPrint (string s)
Definition at line 1 of file debug.c.
{
#ifdef INV_DEBUG
    PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
    //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by HandEventBase::CheckRequestSrc(), EntityAI::DropEntityImpl(), EntityAI::ForceSwapEntitiesImpl(), EntityAI::LocalDestroyEntityInHands(), ManBase::NeedInventoryJunctureFromServer(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), ManBase::OnQuickBarSingleUse(), OnServerInventoryCommand(), OnServerInventoryCommandStatic(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), EntityAI::PredictiveMoveItemFromHandsToInventory(), ProccessInputData(), EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), EntityAI::ReplaceItemWithNewImpl(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), EntityAI::SwapEntitiesImpl(), EntityAI::TakeEntityAsAttachmentExImpl(), EntityAI::TakeEntityAsAttachmentImpl(), ManBase::TakeEntityAsAttachmentImpl(), EntityAI::TakeEntityToCargoImpl(), ManBase::TakeEntityToCargoImpl(), EntityAI::TakeEntityToHandsImpl(), ManBase::TakeEntityToHandsImpl(), EntityAI::TakeEntityToInventoryImpl(), ManBase::TakeEntityToInventoryImpl(), EntityAI::TakeEntityToTargetAttachmentExImpl(), ManBase::TakeEntityToTargetAttachmentImpl(), EntityAI::TakeEntityToTargetCargoExImpl(), EntityAI::TakeEntityToTargetCargoImpl(), ManBase::TakeEntityToTargetCargoImpl(), EntityAI::TakeEntityToTargetInventoryImpl(), ManBase::TakeEntityToTargetInventoryImpl(), TakeToDst(), EntityAI::TakeToDstImpl(), ManBase::TakeToDstImpl(), TryAcquireInventoryJunctureFromServer(), and TryAcquireTwoInventoryJuncturesFromServer().