DayzKode: P:/scripts/3_game/DayZ/systems/inventory/inventory.c File Reference
inventory.c File Reference
Enumerations
enum InventoryCheckContext
enum InventoryCommandType {
MOVE , SYNC_MOVE , HAND_EVENT , SWAP ,
FORCESWAP , DESTROY , REPLACE , USER_RESERVATION_CANCEL
}
enum InventoryJunctureType { TAKE , SWAP }
enum InventoryMode { PREDICTIVE , LOCAL , JUNCTURE , SERVER }
Functions
proto native bool CanAddSwappedEntity (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
static proto native bool CanForceSwapEntities (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
static bool CanForceSwapEntitiesEx (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst)
static proto native bool CanSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
static bool CanSwapEntitiesEx (notnull EntityAI item1, notnull EntityAI item2)
bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
bool DropEntityInBounds (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector halfExtents, float angle, float cosAngle, float sinAngle)
bool DropEntityWithTransform (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector transform[4])
proto native bool FindFirstFreeLocationForNewEntity (string item_type, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFirstFreeLocationForNewEntity.
proto native bool FindFreeLocationFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFreeLocationFor.
proto native bool FindFreeLocationForEx (notnull EntityAI item, FindInventoryLocationType flags, notnull InventoryLocation exclude, out notnull InventoryLocation loc)
FindFreeLocationForEx.
proto native int FindFreeLocationsFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull array< ref InventoryLocation > locs)
proto native void FlipCargo ()
bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
bool GetCurrentAttachmentSlotInfo (out int slot_id, out string slot_name)
Returns true if the item is currently attached and outputs attachment slot id and name.
proto native bool GetCurrentInventoryLocation (out notnull InventoryLocation loc)
proto native bool GetFlipCargo ()
static int GetInventoryCheckContext ()
bool IsAttachment ()
Returns true if this Inventory owner is an attachment of something.
bool IsCargoInHiearchy ()
Returns true if item of his hiearchy parents are in cargo.
bool IsInCargo ()
Returns true if this Inventory owner is in cargo of something.
bool LocalDestroyEntity (notnull EntityAI item)
static proto native bool LocationAddEntity (notnull InventoryLocation inv_loc)
static proto native bool LocationCanAddEntity (notnull InventoryLocation inv_loc)
static bool LocationCanAddEntityEx (notnull InventoryLocation inv_loc)
static proto native bool LocationCanMoveEntity (notnull InventoryLocation src, notnull InventoryLocation dst)
static bool LocationCanMoveEntitySyncCheck (notnull InventoryLocation src, notnull InventoryLocation dst)
static proto native bool LocationCanRemoveEntity (notnull InventoryLocation inv_loc)
static proto native EntityAI LocationCreateEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
static proto native EntityAI LocationCreateLocalEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation)
static proto native EntityAI LocationGetEntity (notnull InventoryLocation inv_loc)
static proto native bool LocationMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
static proto native bool LocationRemoveEntity (notnull InventoryLocation inv_loc)
static proto native bool LocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
static proto native bool LocationSyncMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc)
static proto native bool LocationTestAddEntity (notnull InventoryLocation inv_loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
static bool MakeDstForSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static bool MakeSrcAndDstForForceSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, notnull InventoryLocation dst2)
helper function for ForceSwap
static bool MakeSrcAndDstForSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2)
helper function for swap
static void OnServerInventoryCommandStatic (ParamsReadContext ctx)
static proto native void PrepareDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix=false)
bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
proto native void ResetFlipCargo ()
static proto native bool ServerHandEvent (notnull Man player, notnull EntityAI item, ParamsWriteContext ctx)
static proto native bool ServerLocationMoveEntity (notnull EntityAI item, ParamsWriteContext ctx)
static proto native bool ServerLocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, ParamsWriteContext ctx)
static proto native bool ServerLocationSyncMoveEntity (Man player, notnull EntityAI item, ParamsWriteContext ctx)
proto native void SetFlipCargo (bool flip)
static void SetGroundPosByOwner (EntityAI owner, notnull EntityAI item, out InventoryLocation ground)
static void SetGroundPosByOwnerBounds (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector halfExtents, float angle, float cosAngle, float sinAngle)
static void SetGroundPosByTransform (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector transform[4])
bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
bool TakeEntityAsAttachment (InventoryMode mode, notnull EntityAI item)
bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
bool TakeEntityAsTargetAttachment (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
bool TakeEntityAsTargetAttachmentEx (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
put item as attachment of target
bool TakeEntityToCargo (InventoryMode mode, notnull EntityAI item)
bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
bool TakeEntityToTargetCargo (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
Put item into into cargo of another entity.
bool TakeEntityToTargetCargoEx (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
Put item into into cargo on specific cargo location of another entity.
bool TakeEntityToTargetInventory (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
helper that finds location first, then moves the entity into it
bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
proto native bool CanAddEntityInCargo (notnull EntityAI e, bool flip)
proto native bool CanAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip)
proto native bool CanAddEntityInCargoExLoc (InventoryLocation loc)
proto native bool CanRemoveEntityInCargo (notnull EntityAI e)
proto native bool CanRemoveEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native int CountInventory ()
almost identical to EnumerateInventory except it does not return items
proto native EntityAI CreateEntityInCargo (string typeName)
Create Entity of specified type in cargo of entity.
proto native EntityAI CreateEntityInCargoEx (string typeName, int idx, int row, int col, bool flip)
Create Entity of specified type in cargo of entity at coordinates (row, col)
proto native bool EnumerateInventory (InventoryTraversalType tt, out array< EntityAI > items)
proto native CargoBase GetCargo ()
cargo
proto native CargoBase GetCargoFromIndex (int index)
proto native EntityAI GetInventoryOwner ()
Engine native functions.
proto native bool HasEntityInCargo (notnull EntityAI e)
proto native bool HasEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
proto native bool HasEntityInInventory (notnull EntityAI item)
proto native bool TestAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native bool TestAddEntityInCargoExLoc (notnull InventoryLocation loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
proto native int AttachmentCount ()
Returns count of attachments attached to this item.
proto native bool CanAddAttachment (notnull EntityAI e)
proto native bool CanAddAttachmentEx (notnull EntityAI e, int slot)
proto native bool CanRemoveAttachment (EntityAI attachment)
proto native bool CanRemoveAttachmentEx (EntityAI attachment, int slot)
proto native EntityAI CreateAttachment (string typeName)
proto native EntityAI CreateAttachmentEx (string typeName, int slotId)
proto native EntityAI FindAttachment (int slot)
Returns attached entity in slot (you can use InventorySlots.GetSlotIdFromString(name) to get slot id)
proto native EntityAI FindAttachmentByName (string slotName)
Returns attached entity in slot (you can use EntityAI.GetActionComponentName to get slot id)
proto native EntityAI FindPlaceholderForSlot (int slot)
Returns placeholder entity for slot (naked arms, legs etc)
proto native EntityAI GetAttachmentFromIndex (int index)
proto native int GetAttachmentSlotId (int index)
proto native int GetAttachmentSlotsCount ()
proto native int GetSlotId (int index)
proto native int GetSlotIdCount ()
proto native bool HasAttachment (notnull EntityAI e)
proto native bool HasAttachmentEx (notnull EntityAI e, int slot)
proto native bool HasInventorySlot (int slotId)
proto native bool IsPlaceholderEntity (notnull Object e)
proto native bool CanLockInventoryWithKey (notnull EntityAI key)
locks
proto native bool CanUnlockInventoryWithKey (notnull EntityAI key)
proto native int GetScriptLockCount ()
proto native bool GetSlotLock (int slot)
proto native bool HasKeys ()
proto native bool IsInventoryLocked ()
proto native bool IsInventoryLockedForLockType (int lockType)
proto native bool IsInventoryUnlocked ()
proto native void LockInventory (int lockType)
proto native void LockInventoryWithKey (notnull EntityAI key)
proto native bool SetSlotLock (int slot, bool locked)
proto native void UnlockInventory (int lockType)
proto native void UnlockInventoryWithKey (notnull EntityAI key)
bool AddEntityToInventory (notnull EntityAI item)
bool CanAddEntityInto (notnull EntityAI item, FindInventoryLocationType flags=FindInventoryLocationType.ANY)
bool CanAddEntityIntoHands (notnull EntityAI item)
Test if entity can be put into hands.
bool CanAddEntityIntoInventory (notnull EntityAI item)
Test if entity can be put to the inventory (Cargo, ProxyCargo, Attachment)
bool CanAddEntityToInventory (notnull EntityAI item, int flag=FindInventoryLocationType.ANY)
bool CanRemoveEntity ()
Returns if entity can be removed from its current location.
EntityAI CreateInInventory (string type)
void EEDelete (EntityAI parent)
void EEInit ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void OnAfterStoreLoad ()
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
bool OnInputUserDataProcess (ParamsReadContext ctx)
synchronization
bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
void OnServerInventoryCommand (ParamsReadContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
db load hooks
void OnStoreSave (ParamsWriteContext ctx)
db store hook
Variables
DEFAULT
m_inventory_check_context = InventoryCheckContext.DEFAULT
SYNC_CHECK
static proto native bool AddInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
bool AddInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
const int c_InventoryReservationTimeoutMS = 5000
reservations
const int c_InventoryReservationTimeoutShortMS = 3000
static proto native bool ClearInventoryReservation (EntityAI item, InventoryLocation dst)
bool ClearInventoryReservationEx (EntityAI item, InventoryLocation dst)
static proto native bool ExtendInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms)
bool ExtendInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
static proto native bool GetInventoryReservationCount (EntityAI item, InventoryLocation dst)
static proto native bool HasInventoryReservation (EntityAI item, InventoryLocation dst)
const float c_MaxItemDistanceRadius = 2.5
anti-cheats
static proto native bool CheckDropRequest (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckManipulatedObjectsDistances (notnull EntityAI e0, notnull EntityAI e1, float radius)
static proto native bool CheckMoveToDstRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
static proto native bool CheckRequestSrc (notnull Man requestingPlayer, notnull InventoryLocation src, float radius)
static proto native bool CheckSwapItemsRequest (notnull Man requestingPlayer, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
static proto native bool CheckTakeItemRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
Enumeration Type Documentation
InventoryCheckContext
enum InventoryCheckContext
Definition at line 27 of file inventory.c.
{
    DEFAULT,
    SYNC_CHECK,
}
InventoryCommandType
enum InventoryCommandType
Enumerator
MOVE
generic move, may involve animations
SYNC_MOVE
synchronous move. action is finished immeadiately, no animations involved
HAND_EVENT
event for hands
SWAP
swap two entities (simple swap of compatible objects)
swapping from ground
FORCESWAP
Forced swap two entities. First goes to second's place, second goes "somewhere else".
DESTROY
destroy of entity right in inventory
REPLACE
replace of entity in inventory (@NOTE: hands goes through HAND_EVENT)
USER_RESERVATION_CANCEL
Clear user reserved inventory space.
Definition at line 2 of file inventory.c.
{
    MOVE,
    SYNC_MOVE,
    HAND_EVENT,
    SWAP,
    FORCESWAP,
    DESTROY,
    REPLACE,
    USER_RESERVATION_CANCEL
};
InventoryJunctureType
enum InventoryJunctureType
Enumerator
TAKE
taking from ground
SWAP
swap two entities (simple swap of compatible objects)
swapping from ground
Definition at line 13 of file inventory.c.
{
    TAKE,
    SWAP,
    //LOAD,         ///< load mag from ground
};
InventoryMode
enum InventoryMode
Enumerator
PREDICTIVE
'Predictive' means that the operation uses Client-Side Prediction, i.e. the action runs the same code on both, client AND server
LOCAL
'Local' operation executes from where it is run
JUNCTURE
'Juncture' operation is used whenever there is possibility of race condition, i.e. two players picking same item from ground
SERVER
'Server' mode operation is required if and only if the operation runs only on server (creates and/or destroys objects)
Definition at line 19 of file inventory.c.
{
    PREDICTIVE,
    LOCAL,
    JUNCTURE,
    SERVER,
};
Function Documentation
AddEntityToInventory()
bool AddEntityToInventory (notnull EntityAI item)
Definition at line 825 of file inventory.c.
    {
        InventoryLocation il = new InventoryLocation;
        bool result = FindFreeLocationFor(item, FindInventoryLocationType.ANY, il);
        if (result)
            return LocationAddEntity(il);
        return result;
    }
References FindFreeLocationFor(), and LocationAddEntity().
AddInventoryReservation()
static proto native bool AddInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms) static
Referenced by AddInventoryReservationEx().
AddInventoryReservationEx()
bool AddInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
Definition at line 635 of file inventory.c.
    {
        if (GetGame().IsMultiplayer() && GetGame().IsServer() )
            return true;
        bool ret_val = AddInventoryReservation(item, dst, timeout_ms);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryReservationLogEnable() )
        {
            DayZPlayer player = GetGame().GetPlayer();
            if( player )
            {
                if(item)
                    Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "AddInventoryReservation", player.ToString() );
                else
                    Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "AddInventoryReservation", player.ToString() );
            }
        }
        #endif
        return ret_val;
    }
References AddInventoryReservation(), InventoryLocation::DumpToStringNullSafe(), GetGame(), CGame::GetPlayer(), Debug::InventoryMoveLog(), LogManager::IsInventoryReservationLogEnable(), and string::ToString().
Referenced by ProccessInputData().
AttachmentCount()
AttachmentCount ()
Returns count of attachments attached to this item.
Referenced by ItemBase::CanBePacked(), ItemBase::CanBeTaken(), RecipeBase::CanDo(), ItemBase::CanFoldBaseBuildingObject(), UIScriptedMenu::CheckForLightsAndNVG(), ItemBase::GetGasCanister(), HasLastAttachment(), IsEmpty(), ThrowAllItemsInInventory(), PropertyModifiers::UpdateModifiers(), and UpdateProxySelections().
CanAddAttachment()
proto native bool CanAddAttachment (notnull EntityAI e)
Referenced by EntityAI::PredictiveTakeOrSwapAttachment().
CanAddAttachmentEx()
proto native bool CanAddAttachmentEx (notnull EntityAI e, int slot)
CanAddEntityInCargo()
proto native bool CanAddEntityInCargo (notnull EntityAI e, bool flip)
CanAddEntityInCargoEx()
proto native bool CanAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip)
CanAddEntityInCargoExLoc()
proto native bool CanAddEntityInCargoExLoc (InventoryLocation loc)
CanAddEntityInto()
bool CanAddEntityInto (notnull EntityAI item, FindInventoryLocationType flags = FindInventoryLocationType.ANY)
Definition at line 858 of file inventory.c.
    {
        InventoryLocation loc = new InventoryLocation;
        return FindFreeLocationFor(item, flags, loc)  &&  !item.IsHologram();
    }
References FindFreeLocationFor().
Referenced by CanAddEntityIntoHands(), and CanAddEntityIntoInventory().
CanAddEntityIntoHands()
bool CanAddEntityIntoHands (notnull EntityAI item)
Test if entity can be put into hands.
Definition at line 875 of file inventory.c.
    {
        return CanAddEntityInto(item, FindInventoryLocationType.HANDS);
    }
References CanAddEntityInto().
Referenced by HandsArea::DraggingOverHandsPanel(), HandsArea::OnHandsPanelDropReceived(), and ManBase::OnQuickBarSingleUse().
CanAddEntityIntoInventory()
bool CanAddEntityIntoInventory (notnull EntityAI item)
Test if entity can be put to the inventory (Cargo, ProxyCargo, Attachment)
Definition at line 867 of file inventory.c.
    {
        return CanAddEntityInto(item, FindInventoryLocationType.ANY_CARGO | FindInventoryLocationType.ATTACHMENT);
    }
References CanAddEntityInto().
CanAddEntityToInventory()
bool CanAddEntityToInventory (notnull EntityAI item, int flag = FindInventoryLocationType.ANY)
Definition at line 805 of file inventory.c.
    {
        InventoryLocation il = new InventoryLocation;
        bool result = FindFreeLocationFor(item, flag, il);
        return result;
    }
References FindFreeLocationFor().
CanAddSwappedEntity()
proto native bool CanAddSwappedEntity (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
CanForceSwapEntities()
static proto native bool CanForceSwapEntities (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst) static
Referenced by CanForceSwapEntitiesEx().
CanForceSwapEntitiesEx()
static bool CanForceSwapEntitiesEx (notnull EntityAI item1, InventoryLocation item1_dst, notnull EntityAI item2, out InventoryLocation item2_dst) static
Definition at line 587 of file inventory.c.
    {
        if(!CanForceSwapEntities(item1, item1_dst, item2, item2_dst) )
            return false;
        int slot;
        InventoryLocation il = new InventoryLocation;
        if( item1_dst == null)
        {
            item2.GetInventory().GetCurrentInventoryLocation(il);
            slot = il.GetSlot();
        }
        else
        {
            slot = item1_dst.GetSlot();
        }
        if( item1.GetQuantity() > item1.GetTargetQuantityMax(slot) )
            return false;
        if( item2_dst == null)
        {
            item1.GetInventory().GetCurrentInventoryLocation(il);
            slot = il.GetSlot();
        }
        else
        {
            slot = item2_dst.GetSlot();
        }
        if(!item1.CanSwapEntities(item2, item2_dst, item1_dst) || !item2.CanSwapEntities(item1, item1_dst, item2_dst))
        {
            return false;
        }
        if( item2.GetQuantity() > item2.GetTargetQuantityMax(slot) )
            return false;
        return true;
    }
References CanForceSwapEntities(), and InventoryLocation::GetSlot().
Referenced by HandleForceSwapEntities().
CanLockInventoryWithKey()
proto native bool CanLockInventoryWithKey (notnull EntityAI key)
locks
CanRemoveAttachment()
proto native bool CanRemoveAttachment (EntityAI attachment)
CanRemoveAttachmentEx()
proto native bool CanRemoveAttachmentEx (EntityAI attachment, int slot)
CanRemoveEntity()
bool CanRemoveEntity ()
Returns if entity can be removed from its current location.
Definition at line 837 of file inventory.c.
    {
        InventoryLocation il = new InventoryLocation;
        if (GetCurrentInventoryLocation(il))
            return LocationCanRemoveEntity(il);
        return false;
    }
References GetCurrentInventoryLocation(), and LocationCanRemoveEntity().
CanRemoveEntityInCargo()
proto native bool CanRemoveEntityInCargo (notnull EntityAI e)
CanRemoveEntityInCargoEx()
proto native bool CanRemoveEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
CanSwapEntities()
static proto native bool CanSwapEntities (notnull EntityAI item1, notnull EntityAI item2) static
Referenced by CanSwapEntitiesEx().
CanSwapEntitiesEx()
static bool CanSwapEntitiesEx (notnull EntityAI item1, notnull EntityAI item2) static
Definition at line 550 of file inventory.c.
    {
        int slot;
        InventoryLocation il1 = new InventoryLocation;
        InventoryLocation il2 = new InventoryLocation;
        item2.GetInventory().GetCurrentInventoryLocation(il2);
        slot = il2.GetSlot();
        if( item1.GetQuantity() > item1.GetTargetQuantityMax(slot) )
            return false;
        item1.GetInventory().GetCurrentInventoryLocation(il1);
        slot = il1.GetSlot();
        if( item2.GetQuantity() > item2.GetTargetQuantityMax(slot) )
            return false;
        if(!item1.CanSwapEntities(item2, il2, il1) || !item2.CanSwapEntities(item1, il1, il2))
        {
            return false;
        }
        return CanSwapEntities(item1,item2);
    }
References CanSwapEntities(), and InventoryLocation::GetSlot().
Referenced by HandleSwapEntities(), EntityAI::PredictiveTakeOrSwapAttachment(), HumanInventory::SwappingToPreviousLocation(), and EntityAI::TakeEntityToHandsImpl().
CanUnlockInventoryWithKey()
proto native bool CanUnlockInventoryWithKey (notnull EntityAI key)
CheckDropRequest()
static proto native bool CheckDropRequest (notnull Man requestingPlayer, notnull InventoryLocation src, float radius) static
Referenced by PlayerCheckDropRequest().
CheckManipulatedObjectsDistances()
static proto native bool CheckManipulatedObjectsDistances (notnull EntityAI e0, notnull EntityAI e1, float radius) static
CheckMoveToDstRequest()
static proto native bool CheckMoveToDstRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius) static
Referenced by PlayerCheckRequestDst().
CheckRequestSrc()
static proto native bool CheckRequestSrc (notnull Man requestingPlayer, notnull InventoryLocation src, float radius) static
CheckSwapItemsRequest()
static proto native bool CheckSwapItemsRequest (notnull Man requestingPlayer, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius) static
Referenced by PlayerCheckSwapItemsRequest().
CheckTakeItemRequest()
static proto native bool CheckTakeItemRequest (notnull Man requestingPlayer, notnull InventoryLocation src, notnull InventoryLocation dst, float radius) static
ClearInventoryReservation()
static proto native bool ClearInventoryReservation (EntityAI item, InventoryLocation dst) static
ClearInventoryReservationEx()
bool ClearInventoryReservationEx (EntityAI item, InventoryLocation dst)
Definition at line 679 of file inventory.c.
    {
        if (GetGame().IsMultiplayer() && GetGame().IsServer() )
            return true;
        bool ret_val = ClearInventoryReservation(item,dst);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryReservationLogEnable() )
        {
            DayZPlayer player = GetGame().GetPlayer();
            if( player )
            {
                if(item)
                    Debug.InventoryMoveLog("Reservation cleared result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "ClearInventoryReservation", player.ToString() );
                else
                    Debug.InventoryMoveLog("Reservation cleared result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "ClearInventoryReservation", player.ToString() );
            }
        }
        #endif
        return ret_val;
    }
References ClearInventoryReservation(), InventoryLocation::DumpToStringNullSafe(), GetGame(), CGame::GetPlayer(), Debug::InventoryMoveLog(), LogManager::IsInventoryReservationLogEnable(), and string::ToString().
Referenced by ActionRemoveSeed::OnExecute(), ActionTakeItemToHands::OnExecute(), ActionRepositionPluggedItem::OnExecuteClient(), ActionTakeHybridAttachment::OnExecuteClient(), OnExecuteClient(), ActionAttachOnSelection::OnExecuteClient(), ActionAttachPowerSourceToPanel::OnExecuteClient(), ActionAttachToConstruction::OnExecuteClient(), ActionAttachWithSwitch::OnExecuteClient(), ActionFoldEntityToSlot::OnExecuteClient(), ActionOpen::OnExecuteClient(), ActionUnfoldEntity::OnExecuteClient(), ActionTakeHybridAttachmentToHands::OnExecuteImpl(), ActionRepositionPluggedItem::OnExecuteServer(), ActionTakeHybridAttachment::OnExecuteServer(), ActionTakeItem::OnExecuteServer(), OnExecuteServer(), ActionAttachToConstruction::OnExecuteServer(), ActionAttachWithSwitch::OnExecuteServer(), ActionFoldEntityToSlot::OnExecuteServer(), ActionOpen::OnExecuteServer(), ActionUnfoldEntity::OnExecuteServer(), OnFinishProgressClient(), OnFinishProgressServer(), ProccessInputData(), ActionDetachFromTarget::Process(), SetupAction(), ActionDropItemSimple::Start(), FirearmActionAttachMagazine::Start(), and FirearmActionAttachMagazineQuick::Start().
CountInventory()
CountInventory ()
almost identical to EnumerateInventory except it does not return items
Returns
number of items
Referenced by ItemBase::OnItemLocationChanged().
CreateAttachment()
proto native EntityAI CreateAttachment (string typeName)
Referenced by ItemBase::AssembleKit().
CreateAttachmentEx()
proto native EntityAI CreateAttachmentEx (string typeName, int slotId)
Referenced by ItemBase::CreatePlant().
CreateEntityInCargo()
proto native EntityAI CreateEntityInCargo (string typeName)
Create Entity of specified type in cargo of entity.
CreateEntityInCargoEx()
proto native EntityAI CreateEntityInCargoEx (string typeName, int idx, int row, int col, bool flip)
Create Entity of specified type in cargo of entity at coordinates (row, col)
Parameters
typeName type to create
row the row of cargo to be created at
col the column of cargo to be created at
CreateInInventory()
EntityAI CreateInInventory (string type)
Definition at line 780 of file inventory.c.
    {
        InventoryLocation loc = new InventoryLocation;
        if (FindFirstFreeLocationForNewEntity(type, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT, loc))
        {
            switch (loc.GetType())
            {
                case InventoryLocationType.ATTACHMENT: return loc.GetParent().GetInventory().CreateAttachmentEx(type, loc.GetSlot()); break;
                case InventoryLocationType.CARGO: return loc.GetParent().GetInventory().CreateEntityInCargoEx(type, loc.GetIdx(), loc.GetRow(), loc.GetCol(), loc.GetFlip()); break;
                default: Error("CreateInInventory: unknown location for item"); break;
            }
        }
        return null;
    }
References Error(), FindFirstFreeLocationForNewEntity(), InventoryLocation::GetCol(), InventoryLocation::GetFlip(), InventoryLocation::GetIdx(), InventoryLocation::GetParent(), InventoryLocation::GetRow(), InventoryLocation::GetSlot(), and InventoryLocation::GetType().
Referenced by BaseBuildingBase::OnDebugSpawn(), Headtorch_Black::OnDebugSpawn(), Headtorch_Grey::OnDebugSpawn(), OnDebugSpawn(), ItemBase::OnDebugSpawn(), GPSReceiver::OnDebugSpawn(), and Barrel_ColorBase::ProduceFertilizer().
DropEntity()
bool DropEntity (InventoryMode mode, EntityAI owner, notnull EntityAI item)
Definition at line 1140 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            SetGroundPosByOwner(owner, item, dst);
            return TakeToDst(mode, src, dst);
        }
        Error("DropEntity - No inventory location");
        return false;
    }
References Error(), inventoryDebugPrint(), SetGroundPosByOwner(), and TakeToDst().
DropEntityInBounds()
bool DropEntityInBounds (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector halfExtents, float angle, float cosAngle, float sinAngle)
Definition at line 1197 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            SetGroundPosByOwnerBounds(owner, item, dst, halfExtents, angle, cosAngle, sinAngle);
            return TakeToDst(mode, src, dst);
        }
        Error("DropEntityInBounds - No inventory location");
        return false;
    }
References Error(), inventoryDebugPrint(), SetGroundPosByOwnerBounds(), and TakeToDst().
DropEntityWithTransform()
bool DropEntityWithTransform (InventoryMode mode, EntityAI owner, notnull EntityAI item, vector transform[4])
Definition at line 1162 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Drop(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            SetGroundPosByTransform(owner, item, dst, transform);
            return TakeToDst(mode, src, dst);
        }
        Error("DropEntity - No inventory location");
        return false;
    }
References Error(), inventoryDebugPrint(), SetGroundPosByTransform(), and TakeToDst().
EEDelete()
void EEDelete (EntityAI parent)
Definition at line 766 of file inventory.c.
    {
        EntityAI item = GetInventoryOwner();
        Man player = item.GetHierarchyRootPlayer();
        if (player)
            player.GetInventory().ClearInventoryReservationEx(item, null);
    }
References GetInventoryOwner().
EEInit()
void EEInit ()
Definition at line 749 of file inventory.c.
    {
        InventoryLocation src = new InventoryLocation;
        if (GetCurrentInventoryLocation(src))
        {
            if (src.GetType() == InventoryLocationType.HANDS)
            {
                Man man = Man.Cast(src.GetParent());
                if (man)
                {
                    inventoryDebugPrint("Inventory::EEInit - Man=" + man + " item=" + this);
                    man.GetHumanInventory().OnEntityInHandsCreated(src);
                }
            }
        }
    }
References GetCurrentInventoryLocation(), InventoryLocation::GetParent(), InventoryLocation::GetType(), and inventoryDebugPrint().
EnumerateInventory()
proto native bool EnumerateInventory (InventoryTraversalType tt, out array< EntityAI > items)
ExtendInventoryReservation()
static proto native bool ExtendInventoryReservation (EntityAI item, InventoryLocation dst, int timeout_ms) static
Referenced by ExtendInventoryReservationEx().
ExtendInventoryReservationEx()
bool ExtendInventoryReservationEx (EntityAI item, InventoryLocation dst, int timeout_ms)
Definition at line 657 of file inventory.c.
    {
        if (GetGame().IsMultiplayer() && GetGame().IsServer() )
            return true;
        bool ret_val = ExtendInventoryReservation(item,dst,timeout_ms);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryReservationLogEnable() )
        {
            DayZPlayer player = GetGame().GetPlayer();
            if( player )
            {
                if(item)
                    Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / " + item.ToString() + " / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "ExtendInventoryReservation", player.ToString() );
                else
                    Debug.InventoryMoveLog("Reservation result: " + ret_val + " - STS = " + player.GetSimulationTimeStamp() + " / null / " + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "ExtendInventoryReservation", player.ToString() );
            }
        }
        #endif
        return ret_val;
    }
References InventoryLocation::DumpToStringNullSafe(), ExtendInventoryReservation(), GetGame(), CGame::GetPlayer(), Debug::InventoryMoveLog(), LogManager::IsInventoryReservationLogEnable(), and string::ToString().
FindAttachment()
proto native EntityAI FindAttachment (int slot)
Returns attached entity in slot (you can use InventorySlots.GetSlotIdFromString(name) to get slot id)
Referenced by ManBase::CanEatAndDrink(), KitBase::CanReceiveAttachment(), FlammableBase::CanReceiveAttachment(), ManBase::CheckForBurlap(), ManBase::CheckForGag(), ManBase::CheckHairClippingOnCharacterLoad(), Barrel_ColorBase::DetermineAction(), Plastic_Explosive::OnVariablesSynchronized(), ManBase::OnVoiceEvent(), ManBase::OnVoiceEventPlayback(), ItemBase::RefreshAttachements(), and ManBase::UpdateCorpseStateVisual().
FindAttachmentByName()
proto native EntityAI FindAttachmentByName (string slotName)
Returns attached entity in slot (you can use EntityAI.GetActionComponentName to get slot id)
FindFirstFreeLocationForNewEntity()
proto native bool FindFirstFreeLocationForNewEntity (string item_type, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFirstFreeLocationForNewEntity.
Parameters
[in] item_type item type that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
Referenced by ManBase::CreateCopyOfItemInInventory(), ManBase::CreateInInventory(), and CreateInInventory().
FindFreeLocationFor()
proto native bool FindFreeLocationFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull InventoryLocation loc)
FindFreeLocationFor.
Parameters
[in] item item that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
Referenced by AddEntityToInventory(), CanAddEntityInto(), CanAddEntityToInventory(), ManBase::PredictiveTakeEntityToInventory(), ZombieContainer::Select(), HumanInventory::TakeEntityToInventory(), and TakeEntityToInventory().
FindFreeLocationForEx()
proto native bool FindFreeLocationForEx (notnull EntityAI item, FindInventoryLocationType flags, notnull InventoryLocation exclude, out notnull InventoryLocation loc)
FindFreeLocationForEx.
Parameters
[in] item item that would be placed in inventory
[out] loc the InventoryLocation the item can be placed to
Returns
true if found any, false otherwise
FindFreeLocationsFor()
proto native int FindFreeLocationsFor (notnull EntityAI item, FindInventoryLocationType flags, out notnull array< ref InventoryLocation > locs)
FindPlaceholderForSlot()
proto native EntityAI FindPlaceholderForSlot (int slot)
Returns placeholder entity for slot (naked arms, legs etc)
Referenced by ManBase::OnPlayerLoaded().
FlipCargo()
proto native void FlipCargo ()
ForceSwapEntities()
bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
Definition at line 1127 of file inventory.c.
    {
        return false;
    }
GetAttachmentFromIndex()
proto native EntityAI GetAttachmentFromIndex (int index)
Referenced by InventoryItem::DamageItemAttachments(), GetFuelCount(), GetKindlingCount(), and UpdateProxySelections().
GetAttachmentSlotId()
proto native int GetAttachmentSlotId (int index)
GetAttachmentSlotsCount()
GetAttachmentSlotsCount ()
Returns
number of slots for attachments
Referenced by Switchable_Base::CanPutAsAttachment(), and InventoryItem::GetProtectionLevel().
GetCargo()
proto native CargoBase GetCargo ()
cargo
Referenced by ItemBase::CanBePacked(), InventoryItem::DamageItemInCargo(), InventoryItem::EEHitBy(), InventoryItem::GetNumberOfItems(), ItemBase::GetStashedItem(), IsCargoEmpty(), IsEmpty(), VehicleBattery::OnInventoryEnter(), and ThrowAllItemsInInventory().
GetCargoFromIndex()
proto native CargoBase GetCargoFromIndex (int index)
GetCurrentAttachmentSlotInfo()
bool GetCurrentAttachmentSlotInfo (out int slot_id, out string slot_name)
Returns true if the item is currently attached and outputs attachment slot id and name.
Definition at line 386 of file inventory.c.
    {
        slot_id = -1;
        slot_name = "";
        InventoryLocation lcn = new InventoryLocation;
        GetCurrentInventoryLocation(lcn);
        if ( lcn.GetType() == InventoryLocationType.ATTACHMENT)
        {
            slot_id = lcn.GetSlot();
            slot_name = InventorySlots.GetSlotName(slot_id);
            return true;
        }
        return false;
    }
References GetCurrentInventoryLocation(), InventoryLocation::GetSlot(), InventorySlots::GetSlotName(), and InventoryLocation::GetType().
Referenced by InventoryItem::CanBeCombined().
GetCurrentInventoryLocation()
proto native bool GetCurrentInventoryLocation (out notnull InventoryLocation loc)
Referenced by CarWheel_Ruined::CanPutAsAttachment(), CanRemoveEntity(), EEInit(), GetCurrentAttachmentSlotInfo(), IsAttachment(), IsCargoInHiearchy(), IsInCargo(), and Weapon::IsRemoteWeapon().
GetFlipCargo()
proto native bool GetFlipCargo ()
GetInventoryCheckContext()
static int GetInventoryCheckContext () static
Definition at line 317 of file inventory.c.
    {
        return m_inventory_check_context;
    }
References m_inventory_check_context.
GetInventoryOwner()
GetInventoryOwner ()
Engine native functions.
Returns
entity associated with this inventory
Referenced by DeferredWeaponFailed(), EEDelete(), GetDayZPlayerOwner(), HumanInventory::GetManOwner(), HandEvent(), HumanInventory::LocalDestroyEntity(), PostWeaponEvent(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), HumanInventory::TakeEntityAsAttachmentEx(), TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), and TakeEntityToCargoEx().
GetInventoryReservationCount()
static proto native bool GetInventoryReservationCount (EntityAI item, InventoryLocation dst) static
GetScriptLockCount()
proto native int GetScriptLockCount ()
GetSlotId()
proto native int GetSlotId (int index)
GetSlotIdCount()
GetSlotIdCount ()
Returns
number of slots this item can belong to
Referenced by ManBase::HideHairSelections(), and EntityAI::PredictiveTakeOrSwapAttachment().
GetSlotLock()
proto native bool GetSlotLock (int slot)
Referenced by InventoryItem::CanBeCombined(), and LockOvenAttachments().
HasAttachment()
proto native bool HasAttachment (notnull EntityAI e)
HasAttachmentEx()
proto native bool HasAttachmentEx (notnull EntityAI e, int slot)
HasEntityInCargo()
proto native bool HasEntityInCargo (notnull EntityAI e)
HasEntityInCargoEx()
proto native bool HasEntityInCargoEx (notnull EntityAI e, int idx, int row, int col)
HasEntityInInventory()
proto native bool HasEntityInInventory (notnull EntityAI item)
HasInventoryReservation()
static proto native bool HasInventoryReservation (EntityAI item, InventoryLocation dst) static
Referenced by InventoryItem::CanBeCombined(), ManBase::CanDropEntity(), HandsContainer::CanEquip(), VicinitySlotsContainer::DoubleClick(), HandsContainer::EquipItem(), ManBase::OnQuickBarSingleUse(), InventoryItem::OnRightClick(), and HandsContainer::TransferItem().
HasInventorySlot()
proto native bool HasInventorySlot (int slotId)
HasKeys()
proto native bool HasKeys ()
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 738 of file inventory.c.
{ }
IsAttachment()
bool IsAttachment ()
Returns true if this Inventory owner is an attachment of something.
Definition at line 352 of file inventory.c.
    {
        InventoryLocation lcn = new InventoryLocation;
        GetCurrentInventoryLocation(lcn);
        if ( lcn.GetType() == InventoryLocationType.ATTACHMENT)
        {
            return true;
        }
        return false;
    }
References GetCurrentInventoryLocation(), and InventoryLocation::GetType().
Referenced by CanAssignToQuickbar(), ItemBase::CanAssignToQuickbar(), RecipeBase::CanDo(), Barrel_ColorBase::CanPutIntoHands(), FireplaceBase::CanPutIntoHands(), and PlateCarrierPouches::CanReceiveItemIntoCargo().
IsCargoInHiearchy()
bool IsCargoInHiearchy ()
Returns true if item of his hiearchy parents are in cargo.
Definition at line 365 of file inventory.c.
    {
        InventoryLocation lcn = new InventoryLocation;
        GetCurrentInventoryLocation(lcn);
        EntityAI parent = lcn.GetParent();
        while (parent) //while with limit
        {
            if (lcn.GetType() == InventoryLocationType.CARGO || lcn.GetType() == InventoryLocationType.PROXYCARGO)
            {
                return true;
            }
            parent.GetInventory().GetCurrentInventoryLocation(lcn);
            parent = lcn.GetParent();
        }
        return false;
    }
References GetCurrentInventoryLocation(), InventoryLocation::GetParent(), and InventoryLocation::GetType().
IsInCargo()
bool IsInCargo ()
Returns true if this Inventory owner is in cargo of something.
Definition at line 339 of file inventory.c.
    {
        InventoryLocation lcn = new InventoryLocation;
        GetCurrentInventoryLocation(lcn);
        if ( lcn.GetType() == InventoryLocationType.CARGO)
        {
            return true;
        }
        return false;
    }
References GetCurrentInventoryLocation(), and InventoryLocation::GetType().
IsInventoryLocked()
proto native bool IsInventoryLocked ()
Referenced by ManBase::OnQuickBarContinuousUseStart(), and ManBase::OnQuickBarSingleUse().
IsInventoryLockedForLockType()
proto native bool IsInventoryLockedForLockType (int lockType)
IsInventoryUnlocked()
proto native bool IsInventoryUnlocked ()
Referenced by MissionBase::ShowInventory().
IsPlaceholderEntity()
proto native bool IsPlaceholderEntity (notnull Object e)
LocalDestroyEntity()
bool LocalDestroyEntity (notnull EntityAI item)
Definition at line 1215 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::LocalDestroyEntity inv item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            if (src.GetType() == InventoryLocationType.HANDS)
                Error("[inv] Source location == HANDS, player has to handle this");
            GetGame().ObjectDelete(src.GetItem());
            return true;
        }
        Error("LocalDestroyEntity: No inventory location");
        return false;
    }
References Error(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetType(), inventoryDebugPrint(), and CGame::ObjectDelete().
LocationAddEntity()
static proto native bool LocationAddEntity (notnull InventoryLocation inv_loc) static
Referenced by AddEntityToInventory().
LocationCanAddEntity()
static proto native bool LocationCanAddEntity (notnull InventoryLocation inv_loc) static
Referenced by LocationCanAddEntityEx(), and VicinitySlotsContainer::TransferItem().
LocationCanAddEntityEx()
static bool LocationCanAddEntityEx (notnull InventoryLocation inv_loc) static
Definition at line 292 of file inventory.c.
    {
        return LocationCanAddEntity (inv_loc);
    }
References LocationCanAddEntity().
LocationCanMoveEntity()
static proto native bool LocationCanMoveEntity (notnull InventoryLocation src, notnull InventoryLocation dst) static
Referenced by HandleTakeToDst(), LocationCanMoveEntitySyncCheck(), and EntityAI::PredictiveMoveItemFromHandsToInventory().
LocationCanMoveEntitySyncCheck()
static bool LocationCanMoveEntitySyncCheck (notnull InventoryLocation src, notnull InventoryLocation dst) static
Definition at line 322 of file inventory.c.
    {
        m_inventory_check_context = InventoryCheckContext.SYNC_CHECK;
        bool result = LocationCanMoveEntity(src, dst);
        m_inventory_check_context = InventoryCheckContext.DEFAULT;
        return result;
    }
References LocationCanMoveEntity(), and m_inventory_check_context.
LocationCanRemoveEntity()
static proto native bool LocationCanRemoveEntity (notnull InventoryLocation inv_loc) static
Referenced by CanRemoveEntity().
LocationCreateEntity()
static proto native EntityAI LocationCreateEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation) static
LocationCreateLocalEntity()
static proto native EntityAI LocationCreateLocalEntity (notnull InventoryLocation inv_loc, string type, int iSetupFlags, int iRotation) static
Referenced by ManBase::CreateCopyOfItemInInventory().
LocationGetEntity()
static proto native EntityAI LocationGetEntity (notnull InventoryLocation inv_loc) static
LocationMoveEntity()
static proto native bool LocationMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc) static
LocationRemoveEntity()
static proto native bool LocationRemoveEntity (notnull InventoryLocation inv_loc) static
LocationSwap()
static proto native bool LocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2) static
Referenced by ForceSwapEntities(), HandleForceSwapEntities(), HandleSwapEntities(), OnServerInventoryCommandStatic(), ProccessInputData(), and SwapEntities().
LocationSyncMoveEntity()
static proto native bool LocationSyncMoveEntity (notnull InventoryLocation src_loc, notnull InventoryLocation dst_loc) static
Referenced by HandleTakeToDst(), OnServerInventoryCommandStatic(), ProccessInputData(), and TakeToDst().
LocationTestAddEntity()
static proto native bool LocationTestAddEntity (notnull InventoryLocation inv_loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check) static
LockInventory()
proto native void LockInventory (int lockType)
LockInventoryWithKey()
proto native void LockInventoryWithKey (notnull EntityAI key)
MakeDstForSwap()
static bool MakeDstForSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2) static
helper function for swap
Definition at line 1071 of file inventory.c.
    {
        if (dst1 == null)
            dst1 = new InventoryLocation;
        dst1.Copy(src1);
        dst1.CopyLocationFrom(src2, false);
        dst1.SetFlip(src1.GetItem().GetInventory().GetFlipCargo()); // update flip flag from inventory item
        if (dst2 == null)
            dst2 = new InventoryLocation;
        dst2.Copy(src2);
        dst2.CopyLocationFrom(src1, false);
        dst2.SetFlip(src2.GetItem().GetInventory().GetFlipCargo()); // update flip flag from inventory item
        return true;
    }
References InventoryLocation::Copy(), InventoryLocation::CopyLocationFrom(), and InventoryLocation::SetFlip().
Referenced by MakeSrcAndDstForSwap().
MakeSrcAndDstForForceSwap()
static bool MakeSrcAndDstForForceSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, notnull InventoryLocation dst2) static
helper function for ForceSwap
Definition at line 1100 of file inventory.c.
    {
        if (src1 == null)
            src1 = new InventoryLocation;
        if (src2 == null)
            src2 = new InventoryLocation;
        if (item1.GetInventory().GetCurrentInventoryLocation(src1) && item2.GetInventory().GetCurrentInventoryLocation(src2))
        {
            // src1 -> dst_of(src2)
            if (dst1 == null)
                dst1 = new InventoryLocation;
            dst1.Copy(src1);
            dst1.CopyLocationFrom(src2, false);
            dst1.SetFlip(dst1.GetItem().GetInventory().GetFlipCargo());
            // src2 -> dst2 from user
            return true;
        }
        return false;
    }
References InventoryLocation::Copy(), InventoryLocation::CopyLocationFrom(), and InventoryLocation::SetFlip().
MakeSrcAndDstForSwap()
static bool MakeSrcAndDstForSwap (notnull EntityAI item1, notnull EntityAI item2, out InventoryLocation src1, out InventoryLocation src2, out InventoryLocation dst1, out InventoryLocation dst2) static
helper function for swap
Definition at line 1088 of file inventory.c.
    {
        if (src1 == null)
            src1 = new InventoryLocation;
        if (src2 == null)
            src2 = new InventoryLocation;
        if (item1.GetInventory().GetCurrentInventoryLocation(src1) && item2.GetInventory().GetCurrentInventoryLocation(src2))
            return MakeDstForSwap(src1, src2, dst1, dst2);
        return false;
    }
References MakeDstForSwap().
OnAfterStoreLoad()
OnAfterStoreLoad ()
engine reaction to load from database originates in: engine - Person::BinLoad script - PlayerBase.OnAfterStoreLoad
Definition at line 745 of file inventory.c.
{ }
OnInputUserDataProcess()
bool OnInputUserDataProcess (ParamsReadContext ctx)
synchronization
Definition at line 881 of file inventory.c.
{ }
Referenced by ManBase::OnInputUserDataProcess(), and OnInputUserDataReceived().
OnInventoryJunctureFromServer()
bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
Definition at line 882 of file inventory.c.
{ }
OnInventoryJunctureRepairFromServer()
bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
Definition at line 883 of file inventory.c.
{ }
OnServerInventoryCommand()
void OnServerInventoryCommand (ParamsReadContext ctx)
Definition at line 884 of file inventory.c.
{ }
OnServerInventoryCommandStatic()
static void OnServerInventoryCommandStatic (ParamsReadContext ctx) static
Definition at line 401 of file inventory.c.
    {
        int tmp = -1;
        ctx.Read(tmp);
        int type = -1;
        if (!ctx.Read(type))
            return;
        switch (type)
        {
            case InventoryCommandType.SYNC_MOVE:
            {
                InventoryLocation src = new InventoryLocation;
                InventoryLocation dst = new InventoryLocation;
                src.ReadFromContext(ctx);
                dst.ReadFromContext(ctx);
                syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                if (!src.GetItem() || !dst.GetItem())
                {
                    LogError("[syncinv] ServerInventoryCommand (cmd=SYNC_MOVE) dropped, item not in bubble");
                    break; // not in bubble
                }
                LocationSyncMoveEntity(src, dst);
                break;
            }
            case InventoryCommandType.HAND_EVENT:
            {
                HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
                syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand cmd=" + typename.EnumToString(InventoryCommandType, type) + " event=" + e.DumpToString());
                if (!e.GetSrcEntity())
                {
                    Error("[syncinv] ServerInventoryCommand (cmd=HAND_EVENT) dropped, item not in bubble");
                    break; // not in bubble
                }
                e.m_Player.GetHumanInventory().ProcessHandEvent(e);
                break;
            }
            case InventoryCommandType.FORCESWAP:
            case InventoryCommandType.SWAP:
            {
                InventoryLocation src1 = new InventoryLocation;
                InventoryLocation src2 = new InventoryLocation;
                InventoryLocation dst1 = new InventoryLocation;
                InventoryLocation dst2 = new InventoryLocation;
                src1.ReadFromContext(ctx);
                src2.ReadFromContext(ctx);
                dst1.ReadFromContext(ctx);
                dst2.ReadFromContext(ctx);
                if (src1.IsValid() && src2.IsValid() && dst1.IsValid() && dst2.IsValid())
                {
                    syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms ServerInventoryCommand Swap src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
                    LocationSwap(src1, src2, dst1, dst2);
                }
                else
                    Error("ServerInventoryCommand - cannot swap, invalid location input: src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
                break;
            }
        }
    }
References HandEventBase::DumpToString(), InventoryLocation::DumpToStringNullSafe(), Error(), GetGame(), InventoryLocation::GetItem(), GetTime(), InventoryLocation::IsValid(), LocationSwap(), LocationSyncMoveEntity(), LogError(), Serializer::Read(), InventoryLocation::ReadFromContext(), and syncDebugPrint().
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version)
db load hooks
Definition at line 741 of file inventory.c.
    {
        return true;
    }
Referenced by Weapon::CopyWeaponStateFrom(), ItemBase::OnStoreLoad(), and ManBase::OnStoreLoad().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx)
db store hook
Definition at line 747 of file inventory.c.
{ }
PrepareDropEntityPos()
static proto native void PrepareDropEntityPos (EntityAI owner, notnull EntityAI item, out vector mat[4], bool useValuesInMatrix = false) static
ReplaceItemWithNew()
bool ReplaceItemWithNew (InventoryMode mode, ReplaceItemWithNewLambdaBase lambda)
Definition at line 1232 of file inventory.c.
    {
        InventoryLocation src = new InventoryLocation;
        if (lambda.m_OldItem.GetInventory().GetCurrentInventoryLocation(src))
        {
            inventoryDebugPrint("[inv] I::ReplaceItemWithNew executing lambda=" + lambda + "on old_item=" + lambda.m_OldItem);
            if (src.GetType() == InventoryLocationType.HANDS && src.GetParent().IsAlive())
                Error("[inv] I::ReplaceItemWithNew Source location == HANDS, alive player has to handle this");
            lambda.Execute();
            return true;
        }
        Error("[inv] I::ReplaceItemWithNew - no inventory location");
        return false;
    }
References Error(), ReplaceItemWithNewLambdaBase::Execute(), InventoryLocation::GetParent(), InventoryLocation::GetType(), inventoryDebugPrint(), and ReplaceItemWithNewLambdaBase::m_OldItem.
ResetFlipCargo()
proto native void ResetFlipCargo ()
ServerHandEvent()
static proto native bool ServerHandEvent (notnull Man player, notnull EntityAI item, ParamsWriteContext ctx) static
ServerLocationMoveEntity()
static proto native bool ServerLocationMoveEntity (notnull EntityAI item, ParamsWriteContext ctx) static
ServerLocationSwap()
static proto native bool ServerLocationSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, ParamsWriteContext ctx) static
ServerLocationSyncMoveEntity()
static proto native bool ServerLocationSyncMoveEntity (Man player, notnull EntityAI item, ParamsWriteContext ctx) static
SetFlipCargo()
proto native void SetFlipCargo (bool flip)
SetGroundPosByOwner()
static void SetGroundPosByOwner (EntityAI owner, notnull EntityAI item, out InventoryLocation ground) static
Definition at line 1132 of file inventory.c.
    {
        vector m4[4];
        Math3D.MatrixIdentity4(m4);
        GameInventory.PrepareDropEntityPos(owner, item, m4, false);
        ground.SetGround(item, m4);
    }
References Math3D::MatrixIdentity4().
Referenced by DropEntity().
SetGroundPosByOwnerBounds()
static void SetGroundPosByOwnerBounds (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector halfExtents, float angle, float cosAngle, float sinAngle) static
Definition at line 1178 of file inventory.c.
    {
        vector m4[4];
        owner.GetTransform(m4);
        vector randomPos = Vector(Math.RandomFloat(-halfExtents[0], halfExtents[0]), 0, Math.RandomFloat(-halfExtents[2], halfExtents[2]));
        randomPos = vector.RotateAroundZero(randomPos, vector.Up, cosAngle, sinAngle);
        float dist = randomPos[0] * m4[1][0] + randomPos[1] * m4[1][1] + randomPos[2] * m4[1][2];
        m4[3][0] = m4[3][0] + randomPos[0];
        m4[3][1] = m4[3][1] - dist + halfExtents[1];
        m4[3][2] = m4[3][2] + randomPos[2];
        item.PlaceOnSurfaceRotated(m4, Vector(m4[3][0], m4[3][1], m4[3][2]));
        ground.SetGround(item, m4);
    }
References Math::RandomFloat(), vector::RotateAroundZero(), vector::Up, and Vector().
Referenced by DropEntityInBounds().
SetGroundPosByTransform()
static void SetGroundPosByTransform (EntityAI owner, notnull EntityAI item, out InventoryLocation ground, vector transform[4]) static
Definition at line 1156 of file inventory.c.
    {
        GameInventory.PrepareDropEntityPos(owner, item, transform, true);
        ground.SetGround(item, transform);
    }
Referenced by DropEntityWithTransform().
SetSlotLock()
proto native bool SetSlotLock (int slot, bool locked)
SwapEntities()
bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
Definition at line 1122 of file inventory.c.
    {
        return false;
    }
TakeEntityAsAttachment()
bool TakeEntityAsAttachment (InventoryMode mode, notnull EntityAI item)
Definition at line 1058 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2Att(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        return TakeEntityToInventory(mode, FindInventoryLocationType.ATTACHMENT, item);
    }
References inventoryDebugPrint(), and TakeEntityToInventory().
TakeEntityAsAttachmentEx()
bool TakeEntityAsAttachmentEx (InventoryMode mode, notnull EntityAI item, int slot)
Definition at line 1026 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " slot=" + slot);
        return TakeEntityAsTargetAttachmentEx(mode, GetInventoryOwner(), item, slot);
    }
References GetInventoryOwner(), inventoryDebugPrint(), and TakeEntityAsTargetAttachmentEx().
TakeEntityAsTargetAttachment()
bool TakeEntityAsTargetAttachment (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
Definition at line 1064 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        return TakeEntityToTargetInventory(mode, target, FindInventoryLocationType.ATTACHMENT, item);
    }
References inventoryDebugPrint(), and TakeEntityToTargetInventory().
TakeEntityAsTargetAttachmentEx()
bool TakeEntityAsTargetAttachmentEx (InventoryMode mode, notnull EntityAI target, notnull EntityAI item, int slot)
put item as attachment of target
Definition at line 1033 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2TargetAttEx(" + typename.EnumToString(InventoryMode, mode) + ") as ATT of target=" + target + " item=" + item + " slot=" + slot);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            EntityAI att = target.GetInventory().FindAttachment(slot);
            if(att)
            {
                att.CombineItemsClient(item, true );
                return true;
            }
            else
            {
                InventoryLocation dst = new InventoryLocation;
                dst.SetAttachment(target, item, slot);
                return TakeToDst(mode, src, dst);
            }
        }
        Error("[inv] I::Take2AttEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Error - src has no inventory location");
        return false;
    }
References Error(), inventoryDebugPrint(), InventoryLocation::SetAttachment(), and TakeToDst().
Referenced by TakeEntityAsAttachmentEx().
TakeEntityToCargo()
bool TakeEntityToCargo (InventoryMode mode, notnull EntityAI item)
Definition at line 977 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        return TakeEntityToInventory(mode, FindInventoryLocationType.CARGO, item);
    }
References inventoryDebugPrint(), and TakeEntityToInventory().
TakeEntityToCargoEx()
bool TakeEntityToCargoEx (InventoryMode mode, notnull EntityAI item, int idx, int row, int col)
Definition at line 995 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " row=" + row + " col=" + col);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            dst.SetCargo(GetInventoryOwner(), item, idx, row, col, item.GetInventory().GetFlipCargo());
            return TakeToDst(mode, src, dst);
        }
        Error("[inv] I::Take2Cgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " row=" + row + " col=" + col + " Error - src has no inventory location");
        return false;
    }
References Error(), GetInventoryOwner(), inventoryDebugPrint(), InventoryLocation::SetCargo(), and TakeToDst().
TakeEntityToInventory()
bool TakeEntityToInventory (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
Definition at line 907 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            if (FindFreeLocationFor(item, flags, dst))
                return TakeToDst(mode, src, dst);
            inventoryDebugPrint("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Warning - no room for item");
            return false;
        }
        Error("[inv] I::Take2Inv(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + " Error - src has no inventory location");
        return false;
    }
References Error(), FindFreeLocationFor(), inventoryDebugPrint(), and TakeToDst().
Referenced by TakeEntityAsAttachment(), and TakeEntityToCargo().
TakeEntityToTargetCargo()
bool TakeEntityToTargetCargo (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
Put item into into cargo of another entity.
Definition at line 984 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2TargetCgo(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + target);
        return TakeEntityToTargetInventory(mode, target, FindInventoryLocationType.CARGO, item);
    }
References inventoryDebugPrint(), and TakeEntityToTargetInventory().
TakeEntityToTargetCargoEx()
bool TakeEntityToTargetCargoEx (InventoryMode mode, notnull CargoBase cargo, notnull EntityAI item, int row, int col)
Put item into into cargo on specific cargo location of another entity.
Definition at line 1011 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2TargetCgoEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + cargo.GetCargoOwner() + " row=" + row + " col=" + col);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            dst.SetCargoAuto(cargo, item, row, col, item.GetInventory().GetFlipCargo());
            return TakeToDst(mode, src, dst);
        }
        Error("[inv] I::Take2TargetCgoEx(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item + "to cargo of target=" + cargo.GetCargoOwner() + " row=" + row + " col=" + col);
        return false;
    }
References Error(), inventoryDebugPrint(), InventoryLocation::SetCargoAuto(), and TakeToDst().
TakeEntityToTargetInventory()
bool TakeEntityToTargetInventory (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
helper that finds location first, then moves the entity into it
Definition at line 926 of file inventory.c.
    {
        inventoryDebugPrint("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") item=" + item);
        InventoryLocation src = new InventoryLocation;
        if (item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation;
            if (target.GetInventory().FindFreeLocationFor(item, flags, dst))
                return TakeToDst(mode, src, dst);
            inventoryDebugPrint("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") target=" + target + " item=" + item + " Warning - no room for item in target");
            return false;
        }
        Error("[inv] I::Take2Target(" + typename.EnumToString(InventoryMode, mode) + ") target=" + target + " item=" + item + " Error - src has no inventory location");
        return false;
    }
References Error(), inventoryDebugPrint(), and TakeToDst().
Referenced by TakeEntityAsTargetAttachment(), and TakeEntityToTargetCargo().
TakeToDst()
bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
Definition at line 951 of file inventory.c.
    {
        bool ret;
        switch (mode)
        {
            case InventoryMode.SERVER:
                ret = LocationSyncMoveEntity(src, dst);
                if (ret && dst.IsValid())
                    InventoryInputUserData.SendServerMove(null, InventoryCommandType.SYNC_MOVE, src, dst);
                return ret;
            case InventoryMode.LOCAL:
                ret = LocationSyncMoveEntity(src, dst);
                //InventoryInputUserData.SendInputUserDataMove(InventoryCommandType.SYNC_MOVE, src, dst);
                //Print(ret);
                return ret;
            default:
                return false;
        }
        return false;
    }
References LocationSyncMoveEntity(), and InventoryInputUserData::SendServerMove().
Referenced by DropEntity(), DropEntityInBounds(), DropEntityWithTransform(), EntityAI::PredictiveMoveItemFromHandsToInventory(), TakeEntityAsTargetAttachmentEx(), TakeEntityToCargoEx(), TakeEntityToInventory(), TakeEntityToTargetCargoEx(), and TakeEntityToTargetInventory().
TestAddEntityInCargoEx()
proto native bool TestAddEntityInCargoEx (notnull EntityAI e, int idx, int row, int col, bool flip, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
TestAddEntityInCargoExLoc()
proto native bool TestAddEntityInCargoExLoc (notnull InventoryLocation loc, bool do_resevation_check, bool do_item_check, bool do_lock_check, bool do_occupancy_test, bool do_script_check, bool do_script_load_check)
UnlockInventory()
proto native void UnlockInventory (int lockType)
UnlockInventoryWithKey()
proto native void UnlockInventoryWithKey (notnull EntityAI key)
Variable Documentation
c_InventoryReservationTimeoutMS
const int c_InventoryReservationTimeoutMS = 5000
reservations
Definition at line 632 of file inventory.c.
c_InventoryReservationTimeoutShortMS
const int c_InventoryReservationTimeoutShortMS = 3000
Definition at line 633 of file inventory.c.
c_MaxItemDistanceRadius
const float c_MaxItemDistanceRadius = 2.5
anti-cheats
Definition at line 722 of file inventory.c.
DEFAULT
@ DEFAULT
Definition at line 29 of file inventory.c.
m_inventory_check_context
m_inventory_check_context = InventoryCheckContext.DEFAULT
Referenced by GetInventoryCheckContext(), and LocationCanMoveEntitySyncCheck().
SYNC_CHECK
SYNC_CHECK
Definition at line 30 of file inventory.c.