DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actiondisarmexplosivewithremotedetonator.c File Reference
actiondisarmexplosivewithremotedetonator.c File Reference
Classes
class ActionDisarmExplosiveWithRemoteDetonatorCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionDisarmExplosiveWithRemoteDetonatorCB ActionDisarmExplosiveCB ActionDisarmExplosiveWithRemoteDetonator ()
override bool CanBeSetFromInventory ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 31 of file actiondisarmexplosivewithremotedetonator.c.
    {
        if (!target)
        {
            return false;
        }
        ExplosivesBase explosive = ExplosivesBase.Cast(target.GetObject());
        if (!explosive)
        {
            return false;
        }
        if (explosive.IsRuined() || !explosive.GetArmed() || !explosive.CanBeDisarmed())
        {
            return false;
        }
        if (explosive.GetAttachmentByType(KitchenTimer) || explosive.GetAttachmentByType(AlarmClock_ColorBase))
        {
            return false;
        }
        RemoteDetonatorTrigger rdt = RemoteDetonatorTrigger.Cast(item);
        if (rdt && rdt.IsConnected())
        {
            if (explosive != rdt.GetControlledDevice())
            {
                return false;
            }
            ExplosivesBase controlledDevice = ExplosivesBase.Cast(rdt.GetControlledDevice());
            if (controlledDevice && !controlledDevice.IsRuined() && controlledDevice.GetArmed())
            {
                return true;
            }
        }
        return false;
    }
References ExplosivesBase(), RemoteDetonatorTrigger::GetControlledDevice(), and RemoteDetonatorTrigger::IsConnected().
ActionDisarmExplosiveWithRemoteDetonator()
ActionDisarmExplosiveWithRemoteDetonatorCB ActionDisarmExplosiveCB ActionDisarmExplosiveWithRemoteDetonator ()
Definition at line 1 of file actiondisarmexplosivewithremotedetonator.c.
    {
        m_CallbackClass = ActionDisarmExplosiveWithRemoteDetonatorCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody      = true;
        m_Text          = "#disarm";
    }
Referenced by ActionConstructor::RegisterActions(), and RemoteDetonatorTrigger::SetActions().
CanBeSetFromInventory()
override bool CanBeSetFromInventory ()
Definition at line 26 of file actiondisarmexplosivewithremotedetonator.c.
    {
        return true;
    }
CreateActionComponent()
override void ActionDisarmExplosiveWithRemoteDetonator::CreateActionComponent ()
Definition at line 12 of file actiondisarmexplosivewithremotedetonator.c.
    {
        m_CallbackClass = ActionDisarmExplosiveWithRemoteDetonatorCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 20 of file actiondisarmexplosivewithremotedetonator.c.
    {
        m_ConditionItem     = new CCINonRuined();
        m_ConditionTarget   = new CCTNonRuined();
    }
References m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
claymore has integrated detonator
refresh IK, item changed
Definition at line 73 of file actiondisarmexplosivewithremotedetonator.c.
    {
        ExplosivesBase target;
        Class.CastTo(target, action_data.m_Target.GetObject());
        ItemBase detonator;
        Class.CastTo(detonator, action_data.m_MainItem);
        target.Disarm();
        target.SetTakeable(true);
        if (target.IsInherited(ClaymoreMine))
        {
            detonator.Delete();
            return;
        }
        ReplaceItemWithNewLambdaBase lambda = new ReplaceItemWithNewLambdaBase(detonator, "RemoteDetonator");
        MiscGameplayFunctions.TurnItemIntoItemEx(action_data.m_Player, lambda);
        action_data.m_Player.GetItemAccessor().OnItemInHandsChanged();;
    }
References Class::CastTo(), ExplosivesBase(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.