DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/singleuse/actionunfoldmap.c File Reference
actionunfoldmap.c File Reference
Classes
class ActionUnfoldMapCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionUnfoldMapCB ActionBaseCB ActionUnfoldMap ()
void ActionUnfoldMapCB ()
bool CancelCondition (bool pEnable)
override void CreateConditionComponents ()
override int GetActionCategory ()
override bool HasTarget ()
override void Interrupt (ActionData action_data)
override bool IsInstant ()
override void OnAnimationEvent (int pEventID)
override void OnEndRequest (ActionData action_data)
override void OnFinish (bool pCanceled)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnStateChange (int pOldState, int pCurrentState)
void OpenMap (ActionData action_data)
void PerformMapChange ()
override void SetActionData (ActionData action_data)
bool StateCheck ()
void ~ActionUnfoldMapCB ()
Variables
bool m_CancelCondition
int m_FinalMovementState
bool m_HasReceivedEvent
int m_InitMovementState
bool m_MapFolding
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 189 of file actionunfoldmap.c.
    {
        if (player.m_hac || player.IsMapOpen())
        {
            return false;
        }
        return true;
    }
ActionUnfoldMap()
ActionUnfoldMapCB ActionBaseCB ActionUnfoldMap ()
Definition at line 1 of file actionunfoldmap.c.
    {
        m_Text = "#unfold_map";
    }
Referenced by MissionBase::IsMapUnfoldActionRunning(), ActionUnfoldMapCB::OnFinish(), ActionConstructor::RegisterActions(), and ItemMap::SetActions().
ActionUnfoldMapCB()
void ActionUnfoldMap::ActionUnfoldMapCB ()
Definition at line 175 of file actionunfoldmap.c.
    {
        m_ConditionItem     = new CCINonRuined();
CancelCondition()
bool ActionUnfoldMap::CancelCondition (bool pEnable)
Definition at line 210 of file actionunfoldmap.c.
    {
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 178 of file actionunfoldmap.c.
    {
        m_ConditionItem     = new CCINonRuined();
        m_ConditionTarget   = new CCTNone();
    }
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int GetActionCategory ()
Definition at line 198 of file actionunfoldmap.c.
    {
        return AC_SINGLE_USE;
    }
References AC_SINGLE_USE.
HasTarget()
override bool HasTarget ()
Definition at line 184 of file actionunfoldmap.c.
    {
        return false;
    }
Interrupt()
override void Interrupt (ActionData action_data)
Definition at line 221 of file actionunfoldmap.c.
    {
        if ( action_data.m_Player.m_hac )
        {
            action_data.m_Player.m_hac.m_MapFolding = true;
            action_data.m_Player.m_hac.PerformMapChange();
        }
        super.Interrupt(action_data);
        if ( action_data.m_Callback )
        {
            action_data.m_Callback.Cancel();
        }
        else
        {
            End( action_data );
        }
        action_data.m_State = UA_INTERRUPT;
    }
References ActionData::m_Player.
IsInstant()
override bool IsInstant ()
Definition at line 173 of file actionunfoldmap.c.
    {
        return false;
    }
OnAnimationEvent()
override void ActionUnfoldMap::OnAnimationEvent (int pEventID)
Definition at line 226 of file actionunfoldmap.c.
        {
            action_data.m_Callback.Cancel();
        }
        else
        {
            End( action_data );
        }
        action_data.m_State = UA_INTERRUPT;
    }
    void OpenMap( ActionData action_data )
    {
        if (!action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE))
        {
            action_data.m_Player.m_hac = ActionUnfoldMapCB.Cast(action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_VIEWMAP,ActionUnfoldMapCB));
        }
OnEndRequest()
override void OnEndRequest (ActionData action_data)
Definition at line 215 of file actionunfoldmap.c.
    {
        action_data.m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
        action_data.m_State = UA_FINISHED;
    }
References ActionData::m_Callback, ActionData::m_State, and UA_FINISHED.
OnFinish()
override void ActionUnfoldMap::OnFinish (bool pCanceled)
Definition at line 250 of file actionunfoldmap.c.
        {
            action_data.m_Player.m_hac = ActionUnfoldMapCB.Cast(action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_VIEWMAP,ActionUnfoldMapCB,GetStanceMask(action_data.m_Player)));
        }
        // sets player for associated callback to use
        if (action_data.m_Player.m_hac)
        {
            action_data.m_Player.m_hac.SetActionData(action_data);
            action_data.m_Callback = action_data.m_Player.m_hac;
        }
    }
}
References GetStanceMask(), and ActionData::m_Player.
OnStartClient()
override void OnStartClient (ActionData action_data)
Definition at line 203 of file actionunfoldmap.c.
    {
        OpenMap(action_data);
    }
OnStartServer()
override void OnStartServer (ActionData action_data)
Definition at line 208 of file actionunfoldmap.c.
    {
        OpenMap(action_data);
        ItemMap chernomap = ItemMap.Cast(action_data.m_MainItem);
        chernomap.SyncMapMarkers();
    }
OnStateChange()
override void ActionUnfoldMap::OnStateChange (int pOldState, int pCurrentState)
Definition at line 215 of file actionunfoldmap.c.
    {
        action_data.m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
        action_data.m_State = UA_FINISHED;
    }
    override void Interrupt(ActionData action_data)
    {
        if ( action_data.m_Player.m_hac )
        {
OpenMap()
void OpenMap (ActionData action_data)
Definition at line 243 of file actionunfoldmap.c.
    {
        if (!action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE))
        {
            action_data.m_Player.m_hac = ActionUnfoldMapCB.Cast(action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_VIEWMAP,ActionUnfoldMapCB));
        }
        else
        {
            action_data.m_Player.m_hac = ActionUnfoldMapCB.Cast(action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_VIEWMAP,ActionUnfoldMapCB,GetStanceMask(action_data.m_Player)));
        }
        // sets player for associated callback to use
        if (action_data.m_Player.m_hac)
        {
            action_data.m_Player.m_hac.SetActionData(action_data);
            action_data.m_Callback = action_data.m_Player.m_hac;
        }
    }
References ActionData::m_Player.
Referenced by SetActionData().
PerformMapChange()
void ActionUnfoldMap::PerformMapChange ()
Definition at line 282 of file actionunfoldmap.c.
SetActionData()
override void ActionUnfoldMap::SetActionData (ActionData action_data)
Definition at line 204 of file actionunfoldmap.c.
    {
        OpenMap(action_data);
    }
    override void OnStartServer( ActionData action_data )
References OpenMap().
StateCheck()
bool ActionUnfoldMap::StateCheck ()
Definition at line 326 of file actionunfoldmap.c.
~ActionUnfoldMapCB()
void ActionUnfoldMap::~ActionUnfoldMapCB ()
Definition at line 182 of file actionunfoldmap.c.
    {
        return false;
    }
    override bool ActionCondition(PlayerBase player, ActionTarget target, ItemBase item)
    {
        if (player.m_hac || player.IsMapOpen())
        {
            return false;
        }
        return true;
    }
    override int GetActionCategory()
    {
        return AC_SINGLE_USE;
    }
Variable Documentation
m_CancelCondition
bool m_CancelCondition
Definition at line 171 of file actionunfoldmap.c.
m_FinalMovementState
int m_FinalMovementState
Definition at line 173 of file actionunfoldmap.c.
m_HasReceivedEvent
bool m_HasReceivedEvent
Definition at line 170 of file actionunfoldmap.c.
m_InitMovementState
int m_InitMovementState
Definition at line 172 of file actionunfoldmap.c.
m_MapFolding
bool m_MapFolding
Definition at line 169 of file actionunfoldmap.c.