DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actiondisarmmine.c File Reference
actiondisarmmine.c File Reference
Classes
class ActionDisarmMineCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionDisarmMineCB ActionContinuousBaseCB ActionDisarmMine ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override void OnAnimationEvent (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 27 of file actiondisarmmine.c.
    {
        if (!target)
        {
            return false;
        }
        LandMineTrap targetMine;
        if (Class.CastTo(targetMine, target.GetObject()) && item && IsInReach(player, target, UAMaxDistances.DEFAULT))
        {
            return targetMine.IsActive() && targetMine.CanBeDisarmed();
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, IsInReach(), and LandMineTrap().
ActionDisarmMine()
ActionDisarmMineCB ActionContinuousBaseCB ActionDisarmMine ()
Definition at line 1 of file actiondisarmmine.c.
    {
        m_CallbackClass = ActionDisarmMineCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody      = true;
        m_Text          = "#disarm";
    }
Referenced by ActionConstructor::RegisterActions(), ToolBase::SetActions(), and Lockpick::SetActions().
CreateActionComponent()
override void ActionDisarmMine::CreateActionComponent ()
Definition at line 12 of file actiondisarmmine.c.
    {
        m_CallbackClass = ActionDisarmMineCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file actiondisarmmine.c.
    {
        m_ConditionItem     = new CCINonRuined;
        m_ConditionTarget   = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
OnAnimationEvent()
override void OnAnimationEvent (ActionData action_data)
Definition at line 53 of file actiondisarmmine.c.
    {
        if (!GetGame().IsMultiplayer() || GetGame().IsServer())
        {
            LandMineTrap targetMine = LandMineTrap.Cast(action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>(true);
            GetGame().RPCSingleParam(targetMine, SoundTypeMine.DISARMING, play, true);
        }
    }
References GetGame(), LandMineTrap(), ActionData::m_Target, and CGame::RPCSingleParam().
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data)
Definition at line 63 of file actiondisarmmine.c.
    {
        if (!GetGame().IsMultiplayer() || GetGame().IsServer())
        {
            LandMineTrap targetMine = LandMineTrap.Cast(action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>(false);
            GetGame().RPCSingleParam(targetMine, SoundTypeMine.DISARMING, play, true);
        }
    }
References GetGame(), LandMineTrap(), ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 73 of file actiondisarmmine.c.
    {
        LandMineTrap targetMine;
        Class.CastTo(targetMine, action_data.m_Target.GetObject());
        ToolBase tool;
        Class.CastTo(tool, action_data.m_MainItem);
        if (Math.RandomIntInclusive(0, 100) < tool.GetDisarmRate())
        {
            targetMine.Disarm();
        }
        else
        {
            targetMine.OnSteppedOn(action_data.m_Player);
        }
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 2);
    }
References Class::CastTo(), LandMineTrap(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and Math::RandomIntInclusive().
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data)
Definition at line 43 of file actiondisarmmine.c.
    {
        if (!GetGame().IsMultiplayer() || GetGame().IsServer())
        {
            LandMineTrap targetMine = LandMineTrap.Cast(action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>(true);
            GetGame().RPCSingleParam(targetMine, SoundTypeMine.DISARMING, play, true);
        }
    }
References GetGame(), LandMineTrap(), ActionData::m_Target, and CGame::RPCSingleParam().