DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/interact/actiontakefireplacefrombarrel.c File Reference
actiontakefireplacefrombarrel.c File Reference
Classes
class ActionTakeFireplaceFromBarrel
Functions
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
override protected void CreateNetworkObjectInfo (EntityAI new_item)
override protected void DeleteOldEntity ()
override protected void RemoveOldItemFromLocation ()
void TakeFireplaceFromBarrelLambda (EntityAI old_item, string new_item_type, PlayerBase player)
override protected void UndoRemoveOldItemFromLocation ()
Variables
ActionTakeFireplaceFromBarrel m_Player
Function Documentation
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Definition at line 69 of file actiontakefireplacefrombarrel.c.
    {
        super.CopyOldPropertiesToNew( old_item, new_item );
        MiscGameplayFunctions.TransferInventory(old_item, new_item, m_Player);
    }
References m_Player.
CreateNetworkObjectInfo()
override protected void CreateNetworkObjectInfo (EntityAI new_item)
Definition at line 81 of file actiontakefireplacefrombarrel.c.
    {
        super.CreateNetworkObjectInfo(new_item);
        GetGame().RemoteObjectTreeCreate(m_OldItem); // re-create network for old item
    }
References GetGame(), and CGame::RemoteObjectTreeCreate().
DeleteOldEntity()
override protected void DeleteOldEntity ()
Definition at line 76 of file actiontakefireplacefrombarrel.c.
    {
        // intentional no-operation
    }
RemoveOldItemFromLocation()
override protected void RemoveOldItemFromLocation ()
Definition at line 59 of file actiontakefireplacefrombarrel.c.
    {
        // intentional no-operation
        m_RemoveFromLocationPassed = true; // but indicate the operation to be success
    }
TakeFireplaceFromBarrelLambda()
void TakeFireplaceFromBarrelLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 54 of file actiontakefireplacefrombarrel.c.
    {
        m_Player = player;
    }
References m_Player.
Referenced by ActionTakeFireplaceFromBarrel::OnExecuteServer().
UndoRemoveOldItemFromLocation()
override protected void UndoRemoveOldItemFromLocation ()
Definition at line 64 of file actiontakefireplacefrombarrel.c.
    {
        // undo nothing
    }
Variable Documentation
m_Player
ActionTakeFireplaceFromBarrel m_Player