DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/interact/actiondetach.c File Reference
actiondetach.c File Reference
Classes
class DetachActionData
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDetach ()
override void CreateAndSetupActionCallback (ActionData action_data)
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool HasProneException ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Variables
DetachActionData m_ItemName = ""
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 38 of file actiondetach.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        EntityAI tgt_parent = EntityAI.Cast( target.GetParent() );
        EntityAI tgt_entity = EntityAI.Cast( target.GetObject() );
        if ( !tgt_item || !tgt_entity || !tgt_parent )
            return false;
        if ( !tgt_parent || !tgt_item.IsItemBase() || !tgt_item.IsTakeable() || tgt_item.IsBeingPlaced() )
            return false;
        if ( player.GetCommand_Vehicle() )
            return false;
        if ( player.GetInventory().CanAddEntityIntoHands(tgt_entity) ) //&& !player.GetInventory().CanAddEntityIntoInventory(tgt_entity) )
        {
            if ( tgt_entity.GetHierarchyRootPlayer() != player )
            {
                if ( tgt_entity.CanDetachAttachment( tgt_parent ) && tgt_parent.CanReleaseAttachment( tgt_entity ) )
                    return true;
            }
        }
        return false;
    }
References ItemBase::IsTakeable().
ActionDetach()
void ActionDetach ()
Definition at line 10 of file actiondetach.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS;
        m_Text = "#take_to_hands";
    }
References m_Text.
Referenced by ActionConstructor::RegisterActions(), InventoryItemSuper::SetActions(), CarDoor::SetActions(), ItemBase::SetActions(), SetActions(), Inventory_Base::SetActions(), Roadflare::SetActions(), TripodBase::SetActions(), and VehicleBattery::SetActions().
CreateAndSetupActionCallback()
override void CreateAndSetupActionCallback (ActionData action_data)
Definition at line 87 of file actiondetach.c.
    {
        EntityAI target = EntityAI.Cast(action_data.m_Target.GetObject());
        ActionBaseCB callback;
        if (!target)
            return;
        if (target.IsHeavyBehaviour())
        {
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            if( action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT) )
            {
                Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS,GetCallbackClassTypename()));
            }
            else
            {
                Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_PRONE));
            }
        }
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 17 of file actiondetach.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursorNoRuinCheck();
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 28 of file actiondetach.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool HasProgress ()
Definition at line 33 of file actiondetach.c.
    {
        return false;
    }
HasProneException()
override bool HasProneException ()
Definition at line 23 of file actiondetach.c.
    {
        return true;
    }
OnExecuteClient()
override void OnExecuteClient (ActionData action_data)
Definition at line 78 of file actiondetach.c.
    {
        ActionManagerClient am = ActionManagerClient.Cast(action_data.m_Player.GetActionManager());
        am.UnlockInventory(action_data);
        EntityAI ntarget = EntityAI.Cast(action_data.m_Target.GetObject());
        action_data.m_Player.PredictiveTakeEntityToHands(ntarget);
    }
References ActionData::m_Player, ActionData::m_Target, and ActionManagerClient::UnlockInventory().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 65 of file actiondetach.c.
    {
        if ( GetGame().IsMultiplayer() )
            return;
        ActionManagerClient am = ActionManagerClient.Cast(action_data.m_Player.GetActionManager());
        am.UnlockInventory(action_data);
        EntityAI ntarget = EntityAI.Cast(action_data.m_Target.GetObject());
        action_data.m_Player.PredictiveTakeEntityToHands(ntarget);
    }
References GetGame(), ActionData::m_Player, ActionData::m_Target, and ActionManagerClient::UnlockInventory().
Variable Documentation
m_ItemName
DetachActionData m_ItemName = ""
Referenced by GetItemName(), PluginRecipesManagerBase::MatchItems(), and RadialQuickbarItem().