DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/singleuse/actionturnontransmitter.c File Reference
actionturnontransmitter.c File Reference
Classes
class ActionTurnOnTransmitterCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionTurnOnTransmitterCB ActionSingleUseBaseCB ActionTurnOnTransmitter ()
override void CreateActionComponent ()
override void OnExecuteServer (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 19 of file actionturnontransmitter.c.
    {
        if (item.IsTransmitter())
        {
            return item.HasEnergyManager() && !item.GetCompEM().IsWorking();
        }
        return false;
    }
ActionTurnOnTransmitter()
ActionTurnOnTransmitterCB ActionSingleUseBaseCB ActionTurnOnTransmitter ()
Definition at line 1 of file actionturnontransmitter.c.
    {
        m_CallbackClass     = ActionTurnOnTransmitterCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_ITEM_ON;
        m_Text              = "#turn_on";
    }
Referenced by ActionConstructor::RegisterActions(), ItemMegaphone::SetActions(), ItemRadio::SetActions(), and ItemTransmitter::SetActions().
CreateActionComponent()
override void ActionTurnOnTransmitter::CreateActionComponent ()
Definition at line 12 of file actionturnontransmitter.c.
    {
        m_CallbackClass     = ActionTurnOnTransmitterCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_ITEM_ON;
References m_Text.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 29 of file actionturnontransmitter.c.
    {
        action_data.m_MainItem.GetCompEM().SwitchOn();
    }
References ActionData::m_MainItem.