DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionattachexplosivestrigger.c File Reference
actionattachexplosivestrigger.c File Reference
Classes
class ActionAttachExplosivesTriggerCB
Functions
ActionAttachExplosivesTriggerCB ActionContinuousBaseCB ActionAttachExplosivesTrigger ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
protected void AttachItem (ActionData action_data)
override bool CanBeSetFromInventory ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
protected void CreateRemoteDetonatorReceiverAsAttachment (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionAttachExplosivesTrigger()
ActionAttachExplosivesTriggerCB ActionContinuousBaseCB ActionAttachExplosivesTrigger ()
Definition at line 1 of file actionattachexplosivestrigger.c.
    {
        m_CallbackClass     = ActionAttachExplosivesTriggerCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
        m_FullBody          = true;
        m_SpecialtyWeight   = UASoftSkillsWeight.PRECISE_LOW;
        m_Text              = "#STR_ArmExplosive";
    }
Referenced by OnVariablesSynchronized(), ActionConstructor::RegisterActions(), RemoteDetonatorReceiver(), RemoteDetonatorTrigger::SetActions(), and SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 36 of file actionattachexplosivestrigger.c.
    {
        if (target.GetParent())
        {
            return false;
        }
        if (ClaymoreMine.Cast(target.GetObject()))
        {
            return false;
        }
        ExplosivesBase explosive = ExplosivesBase.Cast(target.GetObject());
        if (explosive)
        {
            ClockBase timedTrigger;
            if (ClockBase.CastTo(timedTrigger, item))
            {
                return timedTrigger.IsAlarmOn() && explosive.IsTimerDetonable() && explosive.CanBeArmed();
            }
            return explosive.CanBeArmed();
        }
        return false;
    }
References ClockBase(), and ExplosivesBase().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data)
Definition at line 26 of file actionattachexplosivestrigger.c.
    {
        return true;
    }
AttachItem()
protected void AttachItem (ActionData action_data)
Definition at line 143 of file actionattachexplosivestrigger.c.
    {
        EntityAI target_EAI;
        if (action_data.m_Target.IsProxy())
        {
            target_EAI = EntityAI.Cast(action_data.m_Target.GetParent());
        }
        else
        {
            target_EAI = EntityAI.Cast(action_data.m_Target.GetObject());
        }
        if (target_EAI && action_data.m_MainItem)
        {
            int slot_id = InventorySlots.GetSlotIdFromString(action_data.m_MainItem.GetExplosiveTriggerSlotName());
            bool test = action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_EAI, action_data.m_MainItem, slot_id);
        }
    }
References InventorySlots::GetSlotIdFromString(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnFinishProgressClient(), and OnFinishProgressServer().
CanBeSetFromInventory()
override bool CanBeSetFromInventory ()
Definition at line 31 of file actionattachexplosivestrigger.c.
    {
        return true;
    }
CreateActionComponent()
override void ActionAttachExplosivesTrigger::CreateActionComponent ()
Definition at line 12 of file actionattachexplosivestrigger.c.
    {
        m_CallbackClass     = ActionAttachExplosivesTriggerCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
        m_FullBody          = true;
References m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 20 of file actionattachexplosivestrigger.c.
    {
        m_ConditionTarget   = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem     = new CCINonRuined();
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
CreateRemoteDetonatorReceiverAsAttachment()
protected void CreateRemoteDetonatorReceiverAsAttachment (ActionData action_data)
Definition at line 120 of file actionattachexplosivestrigger.c.
    {
        ExplosivesBase explosive;
        if (action_data.m_Target.IsProxy())
        {
            explosive = ExplosivesBase.Cast(action_data.m_Target.GetParent());
        }
        else
        {
            explosive = ExplosivesBase.Cast(action_data.m_Target.GetObject());
        }
        if (explosive && action_data.m_MainItem)
        {
            ItemBase receiver = ItemBase.Cast(explosive.GetInventory().CreateAttachment("RemoteDetonatorReceiver"));
            if (receiver)
            {
                receiver.LockToParent();
                RemoteDetonatorTrigger.SpawnInPlayerHands(action_data.m_Player);
            }
        }
    }
References ExplosivesBase(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and RemoteDetonatorTrigger::SpawnInPlayerHands().
Referenced by OnFinishProgressServer().
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 104 of file actionattachexplosivestrigger.c.
    {
        ExplosivesBase explosive = ExplosivesBase.Cast(action_data.m_Target.GetObject());
        RemoteDetonatorTrigger trigger = RemoteDetonatorTrigger.Cast(action_data.m_Player.GetItemInHands());
        if (trigger)
        {
            if (explosive)
            {
                explosive.PairRemote(trigger);
                trigger.SetControlledDevice(explosive);
                explosive.Arm();
            }
        }
    }
References ExplosivesBase(), ActionData::m_Player, ActionData::m_Target, RemoteDetonatorTrigger::PairRemote(), and RemoteDetonatorTrigger::SetControlledDevice().
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data)
Definition at line 87 of file actionattachexplosivestrigger.c.
    {
        ClearInventoryReservationEx(action_data);
        ExplosivesBase explosive = ExplosivesBase.Cast(action_data.m_Target.GetObject());
        if (explosive)
        {
            explosive.UnlockTriggerSlots();
            explosive.SetTakeable(false); //Ensures the item is not picked by client before arming
        }
        if (!action_data.m_MainItem.IsInherited(RemoteDetonator))
        {
            AttachItem(action_data);
        }
    }
References AttachItem(), ClearInventoryReservationEx(), ExplosivesBase(), ActionData::m_MainItem, and ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 64 of file actionattachexplosivestrigger.c.
    {
        ClearInventoryReservationEx(action_data);
        ExplosivesBase explosive = ExplosivesBase.Cast(action_data.m_Target.GetObject());
        if (explosive)
        {
            explosive.UnlockTriggerSlots();
            explosive.SetTakeable(false);  //Ensures the item is not picked by server or remotes before arming
        }
        if (action_data.m_MainItem.IsInherited(RemoteDetonator))
        {
            CreateRemoteDetonatorReceiverAsAttachment(action_data);
            return;
        }
        else
        {
            AttachItem(action_data);
        }
    }
References AttachItem(), ClearInventoryReservationEx(), CreateRemoteDetonatorReceiverAsAttachment(), ExplosivesBase(), ActionData::m_MainItem, and ActionData::m_Target.