DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/interact/actiondetachfromtarget.c File Reference
actiondetachfromtarget.c File Reference
Classes
class ActionDetachFromTarget
class ActionDetachFromTarget_SpecificSlot_WoodenPlanks
class ActionDetachFromTarget_SpecificSlotsCategory
class ActionDetachFromTarget_SpecificSlotsCategory_Barrel
Functions
ActionDetachFromTarget_SpecificSlot_WoodenPlanks ActionDetachFromTarget_SpecificSlot ActionDetachFromTarget_SpecificSlot_MetalSheets ()
ActionDetachFromTarget_SpecificSlotsCategory ActionDetachFromTarget ActionDetachFromTarget_SpecificSlot_WoodenLogs ()
void ActionDetachFromTarget_SpecificSlot_WoodenPlanks ()
void ActionDetachFromTarget_SpecificSlotsCategory_Barrel ()
ActionDetachFromTarget_SpecificSlotsCategory_Barrel ActionDetachFromTarget_SpecificSlotsCategory ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate ()
override int FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item)
Variables
string m_slotsToDetach
ActionDetachFromTarget m_slotToDetach
Function Documentation
ActionDetachFromTarget_SpecificSlot_MetalSheets()
ActionDetachFromTarget_SpecificSlot_WoodenPlanks ActionDetachFromTarget_SpecificSlot ActionDetachFromTarget_SpecificSlot_MetalSheets ()
Definition at line 138 of file actiondetachfromtarget.c.
    {
        m_slotToDetach = "truck_01_metalsheets";
    }
References InventorySlots::GetSlotIdFromString(), and m_slotToDetach.
Referenced by ActionConstructor::RegisterActions(), and CarScript::SetActions().
ActionDetachFromTarget_SpecificSlot_WoodenLogs()
ActionDetachFromTarget_SpecificSlotsCategory ActionDetachFromTarget ActionDetachFromTarget_SpecificSlot_WoodenLogs ()
Definition at line 138 of file actiondetachfromtarget.c.
    {
        m_slotToDetach = "truck_01_woodenlogs";
    }
Referenced by ActionConstructor::RegisterActions(), and CarScript::SetActions().
ActionDetachFromTarget_SpecificSlot_WoodenPlanks()
void ActionDetachFromTarget_SpecificSlot_MetalSheets::ActionDetachFromTarget_SpecificSlot_WoodenPlanks ()
Definition at line 224 of file actiondetachfromtarget.c.
    {
        m_slotToDetach = "truck_01_metalsheets";
    }
}
References m_slotToDetach.
ActionDetachFromTarget_SpecificSlotsCategory_Barrel()
void ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate::ActionDetachFromTarget_SpecificSlotsCategory_Barrel ()
Definition at line 240 of file actiondetachfromtarget.c.
    {
        m_slotsToDetach = "truck_01_woodencrate";
    }
}
References m_slotsToDetach.
ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate()
ActionDetachFromTarget_SpecificSlotsCategory_Barrel ActionDetachFromTarget_SpecificSlotsCategory ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate ()
Definition at line 138 of file actiondetachfromtarget.c.
    {
        m_slotsToDetach = "truck_01_woodencrate";
    }
Referenced by ActionConstructor::RegisterActions(), and CarScript::SetActions().
FindSlotIdToDetach()
override int FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 138 of file actiondetachfromtarget.c.
    {
        EntityAI target_entity = EntityAI.Cast(target.GetObject());
        if ( player && target_entity )
        {
            array<string> selections = new array<string>();
            target_entity.GetActionComponentNameList( target.GetComponentIndex(),selections );
            if ( target_entity && target_entity.GetInventory() && target_entity.GetInventory().AttachmentCount() > 0 )
            {
                for(int i = 0; i < selections.Count(); i++ )
                {
                    if( selections[i] == m_slotToDetach )
                    {
                        int target_slot_id = InventorySlots.GetSlotIdFromString( selections[i] );
                        EntityAI att = target_entity.GetInventory().FindAttachment(target_slot_id);
                        if ( att && player.GetInventory().CanAddEntityIntoHands(att) )
{
                            if ( att.CanDetachAttachment( target_entity ) && target_entity.CanReleaseAttachment( att ) )
                                return target_slot_id;
                        }
                    }
                }
            }
        }
        return InventorySlots.INVALID;
    }
Variable Documentation
m_slotsToDetach
string m_slotsToDetach
Definition at line 208 of file actiondetachfromtarget.c.
Referenced by ActionDetachFromTarget_SpecificSlotsCategory_Barrel().
m_slotToDetach
ActionDetachFromTarget m_slotToDetach
Referenced by ActionDetachFromTarget_SpecificSlot_MetalSheets(), ActionDetachFromTarget_SpecificSlot_WoodenPlanks::ActionDetachFromTarget_SpecificSlot_WoodenPlanks(), and ActionDetachFromTarget_SpecificSlot_WoodenPlanks().