DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/interact/actionpacktent.c File Reference
actionpacktent.c File Reference
Classes
class ActionPackTentCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
ActionPackTentCB ActionContinuousBaseCB ActionPackTent ()
override void CreateActionComponent ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasAlternativeInterrupt ()
override bool HasProgress ()
override bool IsUsingProxies ()
override void OnEnd (ActionData action_data)
override void OnExecute (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void Start (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 73 of file actionpacktent.c.
    {
        Object targetObject = target.GetObject();
        Object targetParent = target.GetParent();
        TentBase inventory_tent = TentBase.Cast(targetObject);
        if (inventory_tent && inventory_tent.GetHierarchyRootPlayer())
        {
            return false; //tent is somewhere in player's inventory
        }
        if ( player && targetObject && targetParent )
        {
            TentBase tent = TentBase.Cast( targetParent );
            if ( tent.CanBePacked() )
            {
                array<string> selections = new array<string>;
                targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections);
                for ( int s = 0; s < selections.Count(); s++ )
                {
                    if ( selections[s] == "pack" )
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data)
Definition at line 47 of file actionpacktent.c.
    {
        Object targetParent = action_data.m_Target.GetParent();
        TentBase tent = TentBase.Cast( targetParent );
        return tent.CanBePacked();
    }
References ActionData::m_Target.
ActionPackTent()
ActionPackTentCB ActionContinuousBaseCB ActionPackTent ()
Definition at line 1 of file actionpacktent.c.
    {
        m_CallbackClass     = ActionPackTentCB;
        m_SpecialtyWeight   = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID        = 0;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#pack_tent";
    }
Referenced by ActionConstructor::RegisterActions(), ItemBase::SetActions(), and TentBase::SetActions().
CreateActionComponent()
override void ActionPackTent::CreateActionComponent ()
Definition at line 12 of file actionpacktent.c.
    {
        m_CallbackClass     = ActionPackTentCB;
        m_SpecialtyWeight   = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID        = 0;
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
CreateActionData()
override ActionData CreateActionData ()
Definition at line 54 of file actionpacktent.c.
    {
        PlaceObjectActionData action_data = new PlaceObjectActionData;
        return action_data;
    }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file actionpacktent.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursorParent(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 27 of file actionpacktent.c.
    {
        return ContinuousInteractActionInput;
    }
HasAlternativeInterrupt()
override bool HasAlternativeInterrupt ()
Definition at line 42 of file actionpacktent.c.
    {
        return true;
    }
HasProgress()
override bool HasProgress ()
Definition at line 37 of file actionpacktent.c.
    {
        return true;
    }
IsUsingProxies()
override bool IsUsingProxies ()
Definition at line 32 of file actionpacktent.c.
    {
        return true;
    }
OnEnd()
override void OnEnd (ActionData action_data)
Definition at line 118 of file actionpacktent.c.
    {
        Object targetParent = action_data.m_Target.GetParent();
        TentBase tent = TentBase.Cast( targetParent );
        tent.SetIsBeingPacked(false);
        if ( action_data.m_Player ) action_data.m_Player.TryHideItemInHands(false);
    }
References ActionData::m_Player, and ActionData::m_Target.
OnExecute()
override void OnExecute (ActionData action_data)
Definition at line 111 of file actionpacktent.c.
    {
        Object targetParent = action_data.m_Target.GetParent();
        TentBase tent = TentBase.Cast( targetParent );
        tent.SetIsBeingPacked(true);
    }
References ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 126 of file actionpacktent.c.
    {
        //vector offset = Vector(1, 0, 0);
        Object targetParent = action_data.m_Target.GetParent();
        TentBase tent = TentBase.Cast( targetParent );
        if (tent.CanBePacked())
        {
            tent.Pack( true );
            tent.SetPosition( action_data.m_Player.GetPosition() /*+ offset*/ ); //Add offset to allign tent with player
            tent.SetOrientation( action_data.m_Player.GetOrientation() );
            tent.PlaceOnSurface();
        }
    }
References ActionData::m_Player, and ActionData::m_Target.
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL)
Definition at line 60 of file actionpacktent.c.
    {
        if ( super.SetupAction(player, target, item, action_data, extra_data ))
        {
            PlaceObjectActionData poActionData;
            poActionData = PlaceObjectActionData.Cast(action_data);
            poActionData.m_AlreadyPlaced = false;
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD; //Call the animation
            return true;
        }
        return false;
    }
References PlaceObjectActionData::m_AlreadyPlaced.
Start()
override void Start (ActionData action_data)
Definition at line 104 of file actionpacktent.c.
    {
        super.Start(action_data);
        if ( action_data.m_Player ) action_data.m_Player.TryHideItemInHands(true);
    }
References ActionData::m_Player.