DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/singleuse/actionattach.c File Reference
actionattach.c File Reference
Classes
class AttachActionData
Functions
AttachActionData ActionData ActionAttach ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeSetFromInventory ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Variables
int m_AttSlot
Function Documentation
ActionAttach()
AttachActionData ActionData ActionAttach ()
Definition at line 1 of file actionattach.c.
    {
        m_Text = "#attach";
    }
Referenced by ActionConstructor::RegisterActions(), ItemBase::SetActions(), SetActions(), Inventory_Base::SetActions(), Roadflare::SetActions(), and TripodBase::SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 61 of file actionattach.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if ( target_entity && item )
        {
            if ( target_entity.GetInventory() && target_entity.GetInventory().CanAddAttachment( item ) )
            {
                return true;
            }
        }
        return false;
    }
CanBeSetFromInventory()
override bool CanBeSetFromInventory ()
Definition at line 121 of file actionattach.c.
    {
        return false;
    }
CreateActionData()
override ActionData CreateActionData ()
Definition at line 22 of file actionattach.c.
    {
        AttachActionData action_data = new AttachActionData;
        return action_data;
    }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 14 of file actionattach.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.DEFAULT );
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_ATTACHITEM;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, m_ConditionTarget, and m_StanceMask.
OnExecuteClient()
override void OnExecuteClient (ActionData action_data)
Definition at line 99 of file actionattach.c.
    {
        ClearInventoryReservationEx(action_data);
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        EntityAI target_EAI;
        if ( action_data.m_Target.IsProxy() )
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetParent() ); // cast to ItemBase
        }
        else
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetObject() ); // cast to ItemBase
        }
        if (target_EAI && action_data_a.m_MainItem)
        {
            action_data_a.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_EAI, action_data_a.m_MainItem, action_data_a.m_AttSlot);
        }
    }
References ClearInventoryReservationEx(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 75 of file actionattach.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        ClearInventoryReservationEx(action_data);
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        EntityAI target_EAI;
        if ( action_data.m_Target.IsProxy() )
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetParent() ); // cast to ItemBase
        }
        else
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetObject() ); // cast to ItemBase
        }
        if (target_EAI && action_data_a.m_MainItem)
        {
            action_data_a.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_EAI, action_data_a.m_MainItem,action_data_a.m_AttSlot);
        }
    }
References ClearInventoryReservationEx(), GetGame(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL)
Definition at line 28 of file actionattach.c.
    {
        ref InventoryLocation il = new InventoryLocation;
        if (!GetGame().IsDedicatedServer())
        {
            EntityAI target_entity;
            if ( target.IsProxy() )
            {
                target_entity = EntityAI.Cast( target.GetParent() );
            }
            else
            {
                target_entity = EntityAI.Cast( target.GetObject() );
            }
            if (!target_entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ATTACHMENT, il ))
                return false;
        }
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            if (!GetGame().IsDedicatedServer())
            {
                AttachActionData action_data_a = AttachActionData.Cast(action_data);
                action_data_a.m_AttSlot = il.GetSlot();
            }
            return true;
        }
        return false;
    }
References GetGame(), and AttachActionData::m_AttSlot.
Variable Documentation
m_AttSlot
int m_AttSlot
Definition at line 10 of file actionattach.c.