DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actiondisarmexplosive.c File Reference
actiondisarmexplosive.c File Reference
Classes
class ActionDisarmExplosiveCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionDisarmExplosiveCB ActionContinuousBaseCB ActionDisarmExplosive ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 27 of file actiondisarmexplosive.c.
    {
        if (!target)
        {
            return false;
        }
        ExplosivesBase explosive;
        if (Class.CastTo(explosive, target.GetObject()) && item)
        {
            return explosive.GetArmed() && explosive.CanBeDisarmed();
        }
        return false;
    }
References Class::CastTo(), and ExplosivesBase().
ActionDisarmExplosive()
ActionDisarmExplosiveCB ActionContinuousBaseCB ActionDisarmExplosive ()
Definition at line 1 of file actiondisarmexplosive.c.
    {
        m_CallbackClass = ActionDisarmExplosiveCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody      = true;
        m_Text          = "#disarm";
    }
Referenced by ActionConstructor::RegisterActions(), ToolBase::SetActions(), and Lockpick::SetActions().
CreateActionComponent()
override void ActionDisarmExplosive::CreateActionComponent ()
Definition at line 12 of file actiondisarmexplosive.c.
    {
        m_CallbackClass = ActionDisarmExplosiveCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file actiondisarmexplosive.c.
    {
        m_ConditionItem     = new CCINonRuined();
        m_ConditionTarget   = new CCTCursor();
    }
References m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 43 of file actiondisarmexplosive.c.
    {
        ExplosivesBase explosive;
        Class.CastTo(explosive, action_data.m_Target.GetObject());
        ToolBase tool;
        Class.CastTo(tool, action_data.m_MainItem);
        if (Math.RandomIntInclusive(0, 100) < tool.GetDisarmRate())
        {
            explosive.Disarm(true);
        }
        else
        {
            explosive.SetHealth("", "", 0.0);
        }
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, UADamageApplied.DEFUSE_TOOLS);
    }
References Class::CastTo(), UADamageApplied::DEFUSE_TOOLS, ExplosivesBase(), ActionData::m_MainItem, ActionData::m_Target, and Math::RandomIntInclusive().