DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/interact/actiongetouttransport.c File Reference
actiongetouttransport.c File Reference
Classes
class GetOutTransportActionData
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionGetOutTransport ()
void ApplyJumpOutDmg (ActionData action_data)
override bool CanBeUsedInRestrain ()
override bool CanBeUsedInVehicle ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void End (ActionData action_data)
override int GetActionCategory ()
override GetInputType ()
override bool HasProgress ()
override void OnEnd (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
override void Start (ActionData action_data)
void Unhide (PlayerBase player)
Variables
const int HIGH_SPEED_VALUE = 30
const int LOW_SPEED_VALUE = 20
GetOutTransportActionData m_DmgFactor = 60
int m_ShockFactor = 15
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 51 of file actiongetouttransport.c.
    {
        Transport trans = null;
        int crew_index = -1;
        HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            trans = vehCommand.GetTransport();
            if ( trans )
            {
                crew_index = trans.CrewMemberIndex( player );
/*According today testing (12.06.2020) this hack is no longer needed
                //Hack for NIVA - disabling jumpng out from the back seats
                Car car;
                if ( Class.CastTo(car, trans) )
                {
                    if ( car.GetSpeedometer() > 8 && crew_index >= 2 && trans.GetType() == "OffroadHatchback" )
                        return false;
                }
*/
                if ( crew_index >= 0 && trans.CrewCanGetThrough( crew_index ) && trans.IsAreaAtDoorFree( crew_index ) )
                    return true;
            }
        }
        return false;
    }
References HumanCommandVehicle::GetTransport(), and Transport::IsAreaAtDoorFree().
ActionGetOutTransport()
void ActionGetOutTransport ()
Definition at line 22 of file actiongetouttransport.c.
    {
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
        m_Text = "#leave_vehicle";
    }
References m_StanceMask, and m_Text.
Referenced by ActionConstructor::RegisterActions(), and ManBase::SetActions().
ApplyJumpOutDmg()
void ApplyJumpOutDmg (ActionData action_data)
Definition at line 245 of file actiongetouttransport.c.
    {
        GetOutTransportActionData got_action_data = GetOutTransportActionData.Cast(action_data);
        PlayerBase player = got_action_data.m_Player;
        //Get all currently equipped clothing
        // ---------------------------------------------
        ClothingBase trousers =     ClothingBase.Cast(player.GetItemOnSlot("LEGS"));
        ClothingBase bag =          ClothingBase.Cast(player.GetItemOnSlot("BACK"));
        ClothingBase vest =         ClothingBase.Cast(player.GetItemOnSlot("VEST"));
        ClothingBase headGear =     ClothingBase.Cast(player.GetItemOnSlot("HeadGear"));
        ClothingBase mask =         ClothingBase.Cast(player.GetItemOnSlot("Mask"));
        ClothingBase shirt =        ClothingBase.Cast(player.GetItemOnSlot("BODY"));
        ClothingBase shoes =        ClothingBase.Cast(player.GetItemOnSlot("FEET"));
        ClothingBase gloves =       ClothingBase.Cast(player.GetItemOnSlot("GLOVES"));
        //Array used to find all relevant information about currently equipped clothes
        array<ClothingBase> equippedClothes = new array<ClothingBase>;
        equippedClothes.Insert(trousers);
        equippedClothes.Insert(bag);
        equippedClothes.Insert(vest);
        equippedClothes.Insert(headGear);
        equippedClothes.Insert(mask);
        equippedClothes.Insert(shirt);
        equippedClothes.Insert(shoes);
        equippedClothes.Insert(gloves);
        // -----------------------------------------------
        //Lower shock taken if player uses a helmet
        headGear = ClothingBase.Cast(player.GetItemOnHead());
        HelmetBase helmet;
        if (Class.CastTo(helmet, headGear))
            got_action_data.m_ShockTaken *= 0.5;
        // -----------------------------------------------
        int randNum; //value used for probability evaluation
        randNum = Math.RandomInt(0, 100);
        if (got_action_data.m_CarSpeed < LOW_SPEED_VALUE)
        {
            if (randNum < 20)
                player.GiveShock(-got_action_data.m_ShockTaken); //To inflict shock, a negative value must be passed
            randNum = Math.RandomIntInclusive(0, PlayerBase.m_BleedingSourcesLow.Count() - 1);
            player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection(PlayerBase.m_BleedingSourcesLow[randNum]);
        }
        else if (got_action_data.m_CarSpeed >= LOW_SPEED_VALUE && got_action_data.m_CarSpeed < HIGH_SPEED_VALUE)
        {
            if (randNum < 50)
                player.GiveShock(-got_action_data.m_ShockTaken);
            randNum = Math.RandomInt(0, PlayerBase.m_BleedingSourcesUp.Count() - 1);
            player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection(PlayerBase.m_BleedingSourcesUp[randNum]);
        }
        else if (got_action_data.m_CarSpeed >= HIGH_SPEED_VALUE)
        {
            headGear = ClothingBase.Cast(player.GetItemOnHead());
            if (!Class.CastTo(helmet, headGear))
                player.m_BleedingManagerServer.AttemptAddBleedingSourceBySelection("Head");
            if (randNum < 75)
                player.GiveShock(-got_action_data.m_ShockTaken);
        }
        int nbClothes = 0;
        //Damage all currently equipped clothes
        for (int i = 0; i < equippedClothes.Count(); i++)
        {
            //If no item is equipped on slot, slot is ignored
            if (equippedClothes[i] == null)
                continue;
            equippedClothes[i].DecreaseHealth(got_action_data.m_DmgTaken, false);
            nbClothes++;
        }
    }
References Class::CastTo(), HIGH_SPEED_VALUE, LOW_SPEED_VALUE, GetOutTransportActionData::m_CarSpeed, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, GetOutTransportActionData::m_ShockTaken, Math::RandomInt(), and Math::RandomIntInclusive().
Referenced by OnEndServer().
CanBeUsedInRestrain()
override bool CanBeUsedInRestrain ()
Definition at line 167 of file actiongetouttransport.c.
    {
        return true;
    }
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle ()
Definition at line 172 of file actiongetouttransport.c.
    {
        return true;
    }
CreateActionData()
override ActionData CreateActionData ()
Definition at line 28 of file actiongetouttransport.c.
    {
        ActionData action_data = new GetOutTransportActionData;
        return action_data;
    }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 35 of file actiongetouttransport.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
End()
override void End (ActionData action_data)
Definition at line 140 of file actiongetouttransport.c.
    {
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(Unhide,action_data.m_Player);
        super.End( action_data );
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), ActionData::m_Player, and Unhide().
GetActionCategory()
override int GetActionCategory ()
Definition at line 177 of file actiongetouttransport.c.
    {
        return AC_INTERACT;
    }
References AC_INTERACT.
GetInputType()
override GetInputType ()
Definition at line 41 of file actiongetouttransport.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool HasProgress ()
Definition at line 46 of file actiongetouttransport.c.
    {
        return false;
    }
OnEnd()
override void OnEnd (ActionData action_data)
Definition at line 182 of file actiongetouttransport.c.
    {
        if ( action_data.m_Player.GetInventory() )
                action_data.m_Player.GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
    }
References ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 188 of file actiongetouttransport.c.
    {
        GetOutTransportActionData got_action_data = GetOutTransportActionData.Cast(action_data);
        vector endLocation = action_data.m_Player.GetPosition() + "0 0.5 0"; // Offset it a little to not hit small objects on the ground
        RaycastRVParams rayParams = new RaycastRVParams( got_action_data.m_StartLocation, endLocation, got_action_data.m_Car, 0.3 );
        rayParams.flags = 0;
        rayParams.sorted = true;
        array<ref RaycastRVResult> results = new array<ref RaycastRVResult>;
        if (DayZPhysics.RaycastRVProxy(rayParams, results))
        {
            Object o = null;
            vector contactPos;
            for (int i = 0; i < results.Count(); ++i)
            {
                if ( got_action_data.m_Car && results[i].obj && !got_action_data.m_Car.IsIgnoredObject(results[i].obj) )
                {
                    o = results[i].obj;
                    contactPos = results[i].pos;
                    break;
                }
            }
            if (o)
            {
                vector offset = got_action_data.m_StartLocation - contactPos;
                offset.Normalize();
                got_action_data.m_Player.SetPosition(contactPos + offset);
            }
        }
        if (got_action_data.m_WasJumpingOut)
        {
            got_action_data.m_Player.OnJumpOutVehicleFinish(got_action_data.m_CarSpeed);
            PlayerBase player = got_action_data.m_Player;
            ApplyJumpOutDmg(action_data);
            vector posMS = player.WorldToModel(player.GetPosition());
            player.DamageAllLegs(got_action_data.m_DmgTaken); //Additionnal leg specific damage dealing
            player.ProcessDirectDamage(DT_CUSTOM, player, "", "FallDamage", posMS, got_action_data.m_DmgTaken);
        }
        if ( got_action_data.m_Car )
        {
            CarScript car;
            if ( Class.CastTo(car, got_action_data.m_Car) )
            {
                car.ForceUpdateLightsEnd();
            }
        }
    }
References ApplyJumpOutDmg(), Class::CastTo(), RaycastRVParams::flags, GetOutTransportActionData::m_Car, GetOutTransportActionData::m_CarSpeed, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, GetOutTransportActionData::m_StartLocation, GetOutTransportActionData::m_WasJumpingOut, vector::Normalize(), array::obj, DayZPhysics::RaycastRVProxy(), and RaycastRVParams::sorted.
OnStartServer()
override void OnStartServer (ActionData action_data)
Definition at line 122 of file actiongetouttransport.c.
    {
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            Transport trans = vehCommand.GetTransport();
            if ( trans )
            {
                CarScript car;
                if ( Class.CastTo(car, trans) )
                {
                    car.ForceUpdateLightsStart();
                }
            }
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.
OnUpdate()
override void OnUpdate (ActionData action_data)
Definition at line 151 of file actiongetouttransport.c.
    {
        if (action_data.m_State == UA_START)
        {
            if ( !action_data.m_Player.GetCommand_Vehicle() )
            {
                End(action_data);
            }
            //TODO add some timed check for stuck possibility
            /*else
            {
                End(action_data);
            }*/
        }
    }
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
Start()
override void Start (ActionData action_data)
Definition at line 82 of file actiongetouttransport.c.
    {
        super.Start( action_data );
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            Transport trans = vehCommand.GetTransport();
            if ( trans )
            {
                GetOutTransportActionData got_action_data = GetOutTransportActionData.Cast(action_data);
                Car car;
                if ( Class.CastTo(car, trans) )
                {
                    got_action_data.m_StartLocation = got_action_data.m_Player.GetPosition();
                    got_action_data.m_Car = car;
                    float speed = car.GetSpeedometerAbsolute();
                    got_action_data.m_CarSpeed = speed;
                    got_action_data.m_DmgTaken = (got_action_data.m_CarSpeed * got_action_data.m_CarSpeed) / m_DmgFactor; //When using multiplications, wrong value is returned
                    got_action_data.m_ShockTaken = (got_action_data.m_CarSpeed * got_action_data.m_CarSpeed) / m_ShockFactor;
                    if ( speed <= 8 )
                    {
                        vehCommand.GetOutVehicle();
                    }
                    else
                    {
                        got_action_data.m_WasJumpingOut = true;
                        vehCommand.JumpOutVehicle();
                    }
                    //action_data.m_Player.TryHideItemInHands(false);
                    //action_data.m_Player.GetItemAccessor().OnItemInHandsChanged();
                    GetDayZGame().GetBacklit().OnLeaveCar();
                    if ( action_data.m_Player.GetInventory() )
                        action_data.m_Player.GetInventory().LockInventory(LOCK_FROM_SCRIPT);
                }
            }
        }
    }
References Class::CastTo(), GetDayZGame(), HumanCommandVehicle::GetOutVehicle(), HumanCommandVehicle::GetTransport(), HumanCommandVehicle::JumpOutVehicle(), GetOutTransportActionData::m_Car, GetOutTransportActionData::m_CarSpeed, m_DmgFactor, GetOutTransportActionData::m_DmgTaken, ActionData::m_Player, m_ShockFactor, GetOutTransportActionData::m_ShockTaken, GetOutTransportActionData::m_StartLocation, and GetOutTransportActionData::m_WasJumpingOut.
Unhide()
void Unhide (PlayerBase player)
Definition at line 146 of file actiongetouttransport.c.
    {
        player.TryHideItemInHands(false);
    }
Referenced by End().
Variable Documentation
HIGH_SPEED_VALUE
const int HIGH_SPEED_VALUE = 30
Definition at line 20 of file actiongetouttransport.c.
Referenced by ApplyJumpOutDmg().
LOW_SPEED_VALUE
const int LOW_SPEED_VALUE = 20
Definition at line 19 of file actiongetouttransport.c.
Referenced by ApplyJumpOutDmg().
m_DmgFactor
GetOutTransportActionData m_DmgFactor = 60
Referenced by Start().
m_ShockFactor
int m_ShockFactor = 15
Definition at line 16 of file actiongetouttransport.c.
Referenced by Start().