DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionlightitemonfire.c File Reference
actionlightitemonfire.c File Reference
Classes
class ActionLightItemOnFireCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
ActionLightItemOnFireCB ActionContinuousBaseCB ActionLightItemOnFire ()
override bool CanBePerformedFromQuickbar ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
bool IsItemInCargoOfSomething (ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
void SetIgnitingAnimation (ItemBase target_item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 70 of file actionlightitemonfire.c.
    {
        ItemBase target_item = ItemBase.Cast(target.GetObject());
        if (target_item && item)
        {
            // when igniting item on the ground with igniter in hands
            if (!target_item.IsIgnited() && !IsItemInCargoOfSomething(target_item) && item.CanIgniteItem(target_item) && target_item.CanBeIgnitedBy(item))
            {
                // oven stage of standard fireplace
                if (target_item.IsKindOf("Fireplace"))
                {
                    if (Fireplace.Cast(target_item).IsOven())
                    {
                        return true;
                    }
                    if (Fireplace.CanIgniteEntityAsFireplace(target_item))
                    {
                        return true;
                    }
                    return false;
                }
                return true;
            }
            // when igniting item in hands from something on ground
            else if (!item.IsIgnited() && !IsItemInCargoOfSomething(item) && target_item.CanIgniteItem(item) && item.CanBeIgnitedBy(target_item))
            {
                return true;
            }
        }
        return false;
    }
References ItemBase::CanBeIgnitedBy(), ItemBase::CanIgniteItem(), ItemBase::IsIgnited(), and IsItemInCargoOfSomething().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data)
Definition at line 56 of file actionlightitemonfire.c.
    {
        FireworksBase fireworks = FireworksBase.Cast( action_data.m_Target.GetObject() );
        if (fireworks)
        {
            return true;//something might begin occluding the item after the ignition began, we don't want that to cancel the ignition process, not the prettiest solution, but it works
        }
        else
        {
            return ActionCondition(action_data.m_Player, action_data.m_Target,action_data.m_MainItem);
        }
    }
References AnimatedActionBase::ActionCondition(), FireworksBase(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
ActionLightItemOnFire()
ActionLightItemOnFireCB ActionContinuousBaseCB ActionLightItemOnFire ()
Definition at line 1 of file actionlightitemonfire.c.
    {
        m_CallbackClass = ActionLightItemOnFireCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_STARTFIRE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#ignite";
    }
Referenced by ActionConstructor::RegisterActions(), SetActions(), ItemBase::SetActions(), Roadflare::SetActions(), and FlammableBase::SetActions().
CanBePerformedFromQuickbar()
override bool CanBePerformedFromQuickbar ()
Definition at line 28 of file actionlightitemonfire.c.
    {
        return true;
    }
CreateActionComponent()
override void ActionLightItemOnFire::CreateActionComponent ()
Definition at line 12 of file actionlightitemonfire.c.
    {
        m_CallbackClass = ActionLightItemOnFireCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_STARTFIRE;
        m_FullBody = true;
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 22 of file actionlightitemonfire.c.
    {
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.DEFAULT );
        m_ConditionItem = new CCINonRuined;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsItemInCargoOfSomething()
bool IsItemInCargoOfSomething (ItemBase item)
Definition at line 40 of file actionlightitemonfire.c.
    {
        if ( item.GetInventory() )
        {
            InventoryLocation loc = new InventoryLocation;
            item.GetInventory().GetCurrentInventoryLocation(loc);
            if ( loc.GetIdx() > -1 )
            {
                return true;
            }
        }
        return false;
    }
References InventoryLocation::GetIdx().
Referenced by ActionCondition(), and CreateActionComponent().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 107 of file actionlightitemonfire.c.
    {
        ItemBase target_item = ItemBase.Cast( action_data.m_Target.GetObject() );
        ItemBase item = action_data.m_MainItem;
        bool is_ignition_successful;
        ItemBase ignited_item;              //item that was lit on fire
        ItemBase fire_source_item;          //item that was the source of fire
        if ( item.CanIgniteItem( target_item ) )
        {
            is_ignition_successful = target_item.IsThisIgnitionSuccessful( item );
            ignited_item = target_item;
            fire_source_item = item;
        }
        else if ( item.CanBeIgnitedBy( target_item ) )
        {
            is_ignition_successful = target_item.IsTargetIgnitionSuccessful( item );
            ignited_item = item;
            fire_source_item = target_item;
        }
        if ( is_ignition_successful )
        {
            fire_source_item.OnIgnitedTarget( ignited_item );
            ignited_item.OnIgnitedThis( fire_source_item );
        }
        else
        {
            fire_source_item.OnIgnitedTargetFailed( ignited_item );
            ignited_item.OnIgnitedThisFailed( fire_source_item );
        }
    }
References ItemBase::CanBeIgnitedBy(), ItemBase::CanIgniteItem(), ItemBase::IsThisIgnitionSuccessful(), ActionData::m_MainItem, ActionData::m_Target, ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), and ItemBase::OnIgnitedThis().
SetIgnitingAnimation()
void SetIgnitingAnimation (ItemBase target_item)
Definition at line 158 of file actionlightitemonfire.c.
    {
        if ( target_item.HasFlammableMaterial() )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_STARTFIRE;
        }
        else
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
        }
    }
References ItemBase::HasFlammableMaterial().
Referenced by SetupAction().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL)
Definition at line 142 of file actionlightitemonfire.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data ) )
        {
            ItemBase target_item = ItemBase.Cast( target.GetObject() );
            if ( target_item )
            {
                SetIgnitingAnimation( target_item );
            }
            return true;
        }
        return false;
    }
References SetIgnitingAnimation().