DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionburyashes.c File Reference
actionburyashes.c File Reference
Classes
class ActionBuryAshesCB
Functions
ActionBuryAshesCB ActionContinuousBaseCB ActionBuryAshes ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateActionComponent ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
Function Documentation
ActionBuryAshes()
ActionBuryAshesCB ActionContinuousBaseCB ActionBuryAshes ()
Definition at line 1 of file actionburyashes.c.
    {
        m_CallbackClass     = ActionBuryAshesCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight   = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#bury";
    }
Referenced by ActionConstructor::RegisterActions(), ItemBase::SetActions(), FarmingHoe::SetActions(), and Iceaxe::SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 27 of file actionburyashes.c.
    {
        if (player.IsPlacingLocal())
        {
            return false;
        }
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
        {
            return false;
        }
        Fireplace fireplaceTarget = Fireplace.Cast(target.GetObject());
        if (fireplaceTarget)
        {
            if (fireplaceTarget.HasAshes() && !fireplaceTarget.IsBurning() && fireplaceTarget.IsEmpty())
            {
                int liquidType;
                string surfaceType;
                GetGame().SurfaceUnderObject(fireplaceTarget, surfaceType, liquidType);
                if (GetGame().IsSurfaceDigable(surfaceType))
                {
                    return true;
                }
            }
        }
        return false;
    }
References GetGame(), and CGame::SurfaceUnderObject().
CreateActionComponent()
override void ActionBuryAshes::CreateActionComponent ()
Definition at line 12 of file actionburyashes.c.
    {
        m_CallbackClass     = ActionBuryAshesCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
        m_FullBody          = true;
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 21 of file actionburyashes.c.
    {
        m_ConditionTarget   = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem     = new CCINonRuined();
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 58 of file actionburyashes.c.
    {
        //destroy fireplace with ashes
        GetGame().ObjectDelete(action_data.m_Target.GetObject());
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 4);
        //add soft skill specialty
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty(UASoftSkillsWeight.ROUGH_LOW);
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, CGame::ObjectDelete(), and UASoftSkillsWeight::ROUGH_LOW.