DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionlightitemonfirewithblowtorch.c File Reference
actionlightitemonfirewithblowtorch.c File Reference
Classes
class ActionLightItemOnFireWithBlowtorchCB
Functions
ActionLightItemOnFireWithBlowtorchCB ActionLightItemOnFireCB ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateActionComponent ()
override void OnEndServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
Function Documentation
ActionCondition()
ActionLightItemOnFireWithBlowtorchCB ActionLightItemOnFireCB ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 1 of file actionlightitemonfirewithblowtorch.c.
    {
        Blowtorch bt = Blowtorch.Cast(item);
        if (!bt.HasEnoughEnergyForRepair(UATimeSpent.BASEBUILDING_REPAIR_FAST))
        {
            return false;
        }
        ItemBase target_item = ItemBase.Cast(target.GetObject());
        if (target_item && item)
        {
            // when igniting item on the ground with igniter in hands
            if (!target_item.IsIgnited() && !IsItemInCargoOfSomething(target_item) && target_item.CanBeIgnitedBy(item))
            {
                // oven stage of standard fireplace
                if (target_item.IsKindOf("Fireplace"))
                {
                    if (Fireplace.Cast(target_item).IsOven())
                    {
                        return true;
                    }
                    if (Fireplace.CanIgniteEntityAsFireplace(target_item))
                    {
                        return true;
                    }
                    return false;
                }
                return true;
            }
            // when igniting item in hands from something on ground
            else if (!item.IsIgnited() && !IsItemInCargoOfSomething(item) && target_item.CanIgniteItem(item) && item.CanBeIgnitedBy(target_item))
            {
                return true;
            }
        }
        return false;
    }
CreateActionComponent()
override void ActionCondition::CreateActionComponent ()
Definition at line 12 of file actionlightitemonfirewithblowtorch.c.
    {
        Blowtorch bt = Blowtorch.Cast(item);
        if (!bt.HasEnoughEnergyForRepair(UATimeSpent.BASEBUILDING_REPAIR_FAST))
        {
References UATimeSpent::BASEBUILDING_REPAIR_FAST, ItemBase::CanBeIgnitedBy(), ItemBase::CanIgniteItem(), ItemBase::IsIgnited(), and IsItemInCargoOfSomething().
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 77 of file actionlightitemonfirewithblowtorch.c.
    {
        super.OnEndServer(action_data);
        action_data.m_MainItem.GetCompEM().SwitchOff();
    }
References ActionData::m_MainItem.
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 63 of file actionlightitemonfirewithblowtorch.c.
    {
        super.OnExecuteServer(action_data);
        action_data.m_MainItem.GetCompEM().SwitchOn();
    }
References ActionData::m_MainItem.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 70 of file actionlightitemonfirewithblowtorch.c.
    {
        super.OnFinishProgressServer(action_data);
        action_data.m_MainItem.GetCompEM().SwitchOff();
    }
References ActionData::m_MainItem.
OnUpdate()
override void OnUpdate (ActionData action_data)
Definition at line 53 of file actionlightitemonfirewithblowtorch.c.
    {
        super.OnUpdate(action_data);
        if (action_data.m_State == UA_PROCESSING && !action_data.m_MainItem.GetCompEM().IsWorking())
        {
            Interrupt(action_data);
        }
    }
References Interrupt(), ActionData::m_MainItem, ActionData::m_State, and UA_PROCESSING.