DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/deployactions/actiondeployobject.c File Reference
actiondeployobject.c File Reference
Classes
class PlaceObjectActionReciveData
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
PlaceObjectActionReciveData ActionReciveData ActionDeployObject ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasAlternativeInterrupt ()
override bool IsDeploymentAction ()
override void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation)
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
void SetupAnimation (ItemBase item)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Variables
vector m_Orientation
vector m_Position
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 25 of file actiondeployobject.c.
    {
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        //Client
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( player.IsPlacingLocal() )
            {
                if ( !player.GetHologramLocal().IsColliding() )
                {
                    if ( item.CanBePlaced(player, player.GetHologramLocal().GetProjectionEntity().GetPosition()) )
                    {
                        return true;
                    }
                }
            }
            return false;
        }
        //Server
        return true;
    }
References ItemBase::CanBePlaced(), and GetGame().
ActionConditionContinue()
override bool ActionConditionContinue (ActionData action_data)
Definition at line 50 of file actiondeployobject.c.
    {
        if ( action_data.m_Player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS )
        {
            //Action not allowed if player has broken legs
            return false;
        }
        //Server
        if ( GetGame().IsServer() )
        {
            if (action_data.m_Player.IsPlacingServer())
            {
                if ( GetGame().IsServer() && GetGame().IsMultiplayer() )
                    action_data.m_Player.GetHologramServer().EvaluateCollision(action_data.m_MainItem);
                if ( !action_data.m_Player.GetHologramServer().IsColliding() )
                {
                    if ( action_data.m_MainItem.CanBePlaced(action_data.m_Player, action_data.m_Player.GetHologramServer().GetProjectionEntity().GetPosition()) )
                    {
                        return true;
                    }
                }
                return false;
            }
            return false;
        }
        return true;
    }
References ItemBase::CanBePlaced(), GetGame(), ActionData::m_MainItem, and ActionData::m_Player.
ActionDeployObject()
PlaceObjectActionReciveData ActionReciveData ActionDeployObject ()
Definition at line 1 of file actiondeployobject.c.
    {
        m_CommandUID        = 0;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
    }
Referenced by ActionConstructor::RegisterActions(), ClaymoreMine::SetActions(), ImprovisedExplosive::SetActions(), Plastic_Explosive::SetActions(), SetActions(), Inventory_Base::SetActions(), ItemBase::SetActions(), TentBase::SetActions(), TrapBase::SetActions(), and TrapSpawnBase::SetActions().
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Definition at line 281 of file actiondeployobject.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        PlaceObjectActionReciveData recive_data_po = PlaceObjectActionReciveData.Cast(action_recive_data);
        PlaceObjectActionData action_data_po = PlaceObjectActionData.Cast(action_data);
        action_data_po.m_Position = recive_data_po.m_Position;
        action_data_po.m_Orientation = recive_data_po.m_Orientation;
    }
References PlaceObjectActionData::m_Orientation, PlaceObjectActionReciveData::m_Orientation, PlaceObjectActionData::m_Position, and PlaceObjectActionReciveData::m_Position.
HasAlternativeInterrupt()
override bool HasAlternativeInterrupt ()
Definition at line 15 of file actiondeployobject.c.
    {
        return true;
    }
IsDeploymentAction()
override bool IsDeploymentAction ()
Definition at line 20 of file actiondeployobject.c.
    {
        return true;
    }
MoveEntityToFinalPosition()
override void MoveEntityToFinalPosition (ActionData action_data, vector position, vector orientation)
Definition at line 292 of file actiondeployobject.c.
    {
        if ( action_data.m_MainItem.IsBasebuildingKit() ) return;
        super.MoveEntityToFinalPosition( action_data, position, orientation );
    }
References ItemBase::IsBasebuildingKit(), and ActionData::m_MainItem.
OnEndClient()
override void OnEndClient (ActionData action_data)
Definition at line 170 of file actiondeployobject.c.
    {
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        if ( !poActionData.m_AlreadyPlaced )
        {
            EntityAI entity_for_placing = action_data.m_MainItem;
            action_data.m_Player.PlacingCancelLocal();
        }
    }
References PlaceObjectActionData::m_AlreadyPlaced, ActionData::m_MainItem, and ActionData::m_Player.
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 181 of file actiondeployobject.c.
    {
        if ( !action_data || !action_data.m_MainItem )
            return;
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        if ( !poActionData.m_AlreadyPlaced )
        {
            EntityAI entity_for_placing = action_data.m_MainItem;
            GetGame().ClearJuncture( action_data.m_Player, entity_for_placing );
            action_data.m_MainItem.SetIsBeingPlaced( false );
            if ( GetGame().IsMultiplayer() )
            {
                action_data.m_Player.PlacingCancelServer();
                action_data.m_MainItem.SoundSynchRemoteReset();
            }
            else
            {
                //local singleplayer
                action_data.m_Player.PlacingCancelLocal();
                action_data.m_Player.PlacingCancelServer();
                InventoryLocation source = new InventoryLocation;
                InventoryLocation destination = new InventoryLocation;
                if ( action_data.m_MainItem.GetInventory().GetCurrentInventoryLocation( source ) )
                {
                    destination.SetHands( action_data.m_Player, action_data.m_MainItem );
                    action_data.m_Player.GetDayZPlayerInventory().RedirectToHandEvent(InventoryMode.LOCAL, source, destination);
                }
            }
        }
        else
        {
            //TODO: make OnEND placement event and move there
            action_data.m_MainItem.SetIsDeploySound( false );
            action_data.m_MainItem.SetIsPlaceSound( false );
            action_data.m_MainItem.SoundSynchRemoteReset();
            if ( action_data.m_MainItem.IsBasebuildingKit() )
            {
                action_data.m_MainItem.Delete();
            }
            else
            {
                GetGame().ClearJuncture( action_data.m_Player, action_data.m_MainItem );
            }
        }
    }
References CGame::ClearJuncture(), GetGame(), ItemBase::IsBasebuildingKit(), PlaceObjectActionData::m_AlreadyPlaced, ActionData::m_MainItem, ActionData::m_Player, and InventoryLocation::SetHands().
OnExecuteServer()
override void OnExecuteServer (ActionData action_data)
Definition at line 243 of file actiondeployobject.c.
    {
        action_data.m_MainItem.SoundSynchRemote();
    }
References ActionData::m_MainItem.
OnFinishProgressClient()
override void OnFinishProgressClient (ActionData action_data)
Definition at line 154 of file actiondeployobject.c.
    {
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        if ( !poActionData ) { return; }
        EntityAI entity_for_placing = action_data.m_MainItem;
        vector position = action_data.m_Player.GetLocalProjectionPosition();
        vector orientation = action_data.m_Player.GetLocalProjectionOrientation();
        poActionData.m_AlreadyPlaced = true;
        entity_for_placing.OnPlacementComplete( action_data.m_Player, position, orientation);
    }
References PlaceObjectActionData::m_AlreadyPlaced, ActionData::m_MainItem, and ActionData::m_Player.
OnStartAnimationLoop()
override void OnStartAnimationLoop (ActionData action_data)
Definition at line 234 of file actiondeployobject.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( action_data.m_Player.GetItemInHands() )
                ActiondeployObjectCB.Cast(action_data.m_Callback).DropDuringPlacing();
        }
    }
References GetGame(), ActionData::m_Callback, and ActionData::m_Player.
OnStartClient()
override void OnStartClient (ActionData action_data)
Definition at line 113 of file actiondeployobject.c.
    {
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        if ( !poActionData ) { return; }
        if ( GetGame().IsMultiplayer() )
            action_data.m_Player.PlacingCompleteLocal();
    }
References GetGame(), and ActionData::m_Player.
OnStartServer()
override void OnStartServer (ActionData action_data)
Definition at line 124 of file actiondeployobject.c.
    {
        if ( GetGame().IsMultiplayer() )
        {
            PlaceObjectActionData poActionData;
            poActionData = PlaceObjectActionData.Cast(action_data);
            if ( !poActionData ) { return; }
            EntityAI entity_for_placing = action_data.m_MainItem;
            poActionData.m_Player.SetLocalProjectionPosition( poActionData.m_Position );
            poActionData.m_Player.SetLocalProjectionOrientation( poActionData.m_Orientation );
            if ( action_data.m_MainItem )
            {
                poActionData.m_Player.PlacingStartServer(action_data.m_MainItem);
                GetGame().AddActionJuncture( action_data.m_Player, entity_for_placing, 10000 );
                action_data.m_MainItem.SetIsBeingPlaced( true );
            }
        }
        else
        {
            //local singleplayer
            action_data.m_Player.PlacingStartServer(action_data.m_MainItem);
            action_data.m_Player.GetHologramLocal().SetUpdatePosition( false );
            action_data.m_MainItem.SetIsBeingPlaced( true );
        }
    }
References CGame::AddActionJuncture(), GetGame(), ActionData::m_MainItem, PlaceObjectActionData::m_Orientation, ActionData::m_Player, and PlaceObjectActionData::m_Position.
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
Definition at line 259 of file actiondeployobject.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new PlaceObjectActionReciveData;
        }
        super.ReadFromContext(ctx, action_recive_data );
        PlaceObjectActionReciveData action_data_po = PlaceObjectActionReciveData.Cast(action_recive_data);
        vector entity_position = "0 0 0";
        vector entity_orientation = "0 0 0";
        if (!ctx.Read(entity_position))
            return false;
        if (!ctx.Read(entity_orientation))
            return false;
        action_data_po.m_Position = entity_position;
        action_data_po.m_Orientation = entity_orientation;
        return true;
    }
References PlaceObjectActionReciveData::m_Orientation, PlaceObjectActionReciveData::m_Position, and Serializer::Read().
SetupAction()
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL)
Definition at line 80 of file actiondeployobject.c.
    {
        if ( super.SetupAction(player, target, item, action_data, extra_data ))
        {
            PlaceObjectActionData poActionData;
            poActionData = PlaceObjectActionData.Cast(action_data);
            poActionData.m_AlreadyPlaced = false;
            if (!GetGame().IsDedicatedServer() )
            {
                Hologram hologram = player.GetHologramLocal();
                if (hologram)
                {
                    poActionData.m_Position = player.GetHologramLocal().GetProjectionPosition();
                    poActionData.m_Orientation = player.GetHologramLocal().GetProjectionOrientation();
                    poActionData.m_Player.SetLocalProjectionPosition( poActionData.m_Position );
                    poActionData.m_Player.SetLocalProjectionOrientation( poActionData.m_Orientation );
                }
                else
                {
                    return false;
                }
            }
            if ( !action_data.m_MainItem )
                return false;
            SetupAnimation( action_data.m_MainItem );
            return true;
        }
        return false;
    }
References GetGame(), PlaceObjectActionData::m_AlreadyPlaced, PlaceObjectActionData::m_Orientation, ActionData::m_Player, PlaceObjectActionData::m_Position, and SetupAnimation().
SetupAnimation()
void SetupAnimation (ItemBase item)
Definition at line 299 of file actiondeployobject.c.
    {
        if ( item.IsDeployable() )
        {
            if ( item.IsHeavyBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_HEAVY;
            }
            else if ( item.IsOneHandedBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD;
            }
            else if ( item.IsTwoHandedBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD;
            }
            else
            {
                Print("Error: check " + item + " behaviour");
            }
        }
        else
        {
            if ( item.IsHeavyBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_PLACING_HEAVY;
            }
            else if ( item.IsOneHandedBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_PLACING_1HD;
            }
            else if ( item.IsTwoHandedBehaviour() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_PLACING_2HD;
            }
            else
            {
                Print("Error: check " + item + " behaviour");
            }
        }
    }
References ItemBase::IsDeployable(), and Print().
Referenced by SetupAction().
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Definition at line 248 of file actiondeployobject.c.
    {
        super.WriteToContext(ctx, action_data);
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        ctx.Write( poActionData.m_Position );
        ctx.Write( poActionData.m_Orientation );
    }
References PlaceObjectActionData::m_Orientation, PlaceObjectActionData::m_Position, and Serializer::Write().
Variable Documentation
m_Orientation
vector m_Orientation
Definition at line 11 of file actiondeployobject.c.
m_Position
vector m_Position
Definition at line 10 of file actiondeployobject.c.