DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actiontargets.c File Reference
actiontargets.c File Reference
Classes
class ActionTargets
class ObjectGroup
class VicinityObjects
objects in vicinity - extended with secondary object which is parent of that Object
Functions
class VicinityObjects ActionTarget (Object object, Object parent, int componentIndex, vector cursorHitPos, float utility)
void ClearVicinityObjects ()
int Count ()
void DbgPrintTargetDump ()
string DumpToString ()
int GetComponentIndex ()
vector GetCursorHitPos ()
Object GetObject ()
Object GetObject (int i)
returns VicinityObjects Key
Object GetParent ()
Get parent of the Effect.
Object GetParent (int i)
returns VicinityObjects Element
array< Object > GetRawVicinityObjects ()
return simple array of Objects in Vicinity
float GetUtility ()
array< Object > GetVicinityObjects ()
return simple array of Objects in Vicinity
bool IsProxy ()
void Remove (array< Object > objects)
void Remove (Object object)
void SetCursorHitPos (vector cursor_position)
void StoreVicinityObject (Object object, Object parent=null)
stores VicinityObject to Hashmap - for storing of parent/child relationship
void TransformToVicinityObjects (array< Object > objects)
transform simple array of Objects to VicinityObjects hashmap
void VicinityObjects ()
Variables
class ActionTargets ActionTarget
private int m_ComponentIndex
private vector m_CursorHitPos
private Object m_Object
private Object m_Parent
private float m_Utility
private ref map< Object, Object > m_VicinityObjects
Function Documentation
ActionTarget()
class VicinityObjects ActionTarget (Object object, Object parent, int componentIndex, vector cursorHitPos, float utility)
Definition at line 1 of file actiontargets.c.
    {
        m_Object = object;
        m_Parent = parent;
        m_ComponentIndex = componentIndex;
        m_CursorHitPos = cursorHitPos;
        m_Utility = utility;
    }
ClearVicinityObjects()
void ActionTarget::ClearVicinityObjects ()
Definition at line 156 of file actiontargets.c.
                                          {";
        res = res + "m_Object: " + Object.GetDebugName(m_Object);
        res = res + "; m_Parent: " + Object.GetDebugName(m_Parent);
        res = res + "; m_ComponentIndex: " + m_ComponentIndex.ToString();
Count()
int ActionTarget::Count ()
Definition at line 202 of file actiontargets.c.
    {
DbgPrintTargetDump()
void DbgPrintTargetDump ()
Definition at line 149 of file actiontargets.c.
    {
        Print(DumpToString());
    }
References DumpToString(), and Print().
DumpToString()
string DumpToString ()
Definition at line 154 of file actiontargets.c.
    {
        string res = "ActionTarget dump = {";
        res = res + "m_Object: " + Object.GetDebugName(m_Object);
        res = res + "; m_Parent: " + Object.GetDebugName(m_Parent);
        res = res + "; m_ComponentIndex: " + m_ComponentIndex.ToString();
        res = res + "; m_CursorHitPos: " + m_CursorHitPos.ToString();
        res = res + "; m_Utility: " + m_Utility.ToString();
        res = res + "}";
        return res;
    }
GetComponentIndex()
int GetComponentIndex ()
Definition at line 135 of file actiontargets.c.
        { return m_ComponentIndex; }
References m_ComponentIndex.
GetCursorHitPos()
vector GetCursorHitPos ()
Definition at line 141 of file actiontargets.c.
        { return m_CursorHitPos; }
References m_CursorHitPos.
GetObject() [1/2]
Object GetObject ()
Definition at line 122 of file actiontargets.c.
        { return m_Object; }
References m_Object.
Referenced by Container::CanCombine(), Container::CanCombineAmmo(), Container::CanEquip(), Particle::CreateParticleEffect(), Container::EquipItem(), VicinityObjects::GetRawVicinityObjects(), VicinityObjects::GetVicinityObjects(), Container::IsItemActive(), Container::IsItemWithQuantityActive(), ParticleList::PreloadParticles(), Container::SplitItem(), Container::TransferItem(), and Container::TransferItemToVicinity().
GetObject() [2/2]
Object ActionTarget::GetObject (int i)
returns VicinityObjects Key
Definition at line 191 of file actiontargets.c.
    {
GetParent()
Object ActionTarget::GetParent (int i)
returns VicinityObjects Element
Definition at line 197 of file actiontargets.c.
        {
            rayStart = GetGame().GetCurrentCameraPosition() + GetGame().GetCurrentCameraDirection() * 0.5;
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), and GetGame().
GetRawVicinityObjects()
array< Object > ActionTarget::GetRawVicinityObjects ()
return simple array of Objects in Vicinity
Definition at line 179 of file actiontargets.c.
    {
        return m_VicinityObjects.GetVicinityObjects();
    }
GetUtility()
float GetUtility ()
Definition at line 138 of file actiontargets.c.
        { return m_Utility; }
References m_Utility.
GetVicinityObjects()
array< Object > ActionTarget::GetVicinityObjects ()
return simple array of Objects in Vicinity
filters out non-takeable items (won't be shown in vicinity)
Definition at line 162 of file actiontargets.c.
{
    void ActionTargets(PlayerBase player)
    {
IsProxy()
bool IsProxy ()
Definition at line 128 of file actiontargets.c.
    {
        if (m_Parent)
            return true;
        return false;
    }
References m_Parent.
Remove() [1/2]
void ActionTarget::Remove (array< Object > objects)
Definition at line 212 of file actiontargets.c.
        {
Remove() [2/2]
void ActionTarget::Remove (Object object)
Definition at line 207 of file actiontargets.c.
        {
Referenced by AttachmentCategoriesRow::RefreshSlot(), array< Class T >::RemoveItemUnOrdered(), map< Class TKey, Class TValue >::ReplaceKey(), array< ref CallQueueContext >::Tick(), and CallQueue::Tick().
SetCursorHitPos()
void SetCursorHitPos (vector cursor_position)
Definition at line 144 of file actiontargets.c.
    {
        m_CursorHitPos = cursor_position;
    }
References m_CursorHitPos.
StoreVicinityObject()
void ActionTarget::StoreVicinityObject (Object object, Object parent = null)
stores VicinityObject to Hashmap - for storing of parent/child relationship
completely remove items that are being placed or are holograms
ignores plain objects
init of VicinityObjects - object, parent(if exists)
Definition at line 122 of file actiontargets.c.
        { return m_Object; }
    Object GetParent()
        { return m_Parent; }
    bool IsProxy()
    {
        if (m_Parent)
            return true;
        return false;
    }
    int GetComponentIndex()
        { return m_ComponentIndex; }
    float GetUtility()
        { return m_Utility; }
    vector GetCursorHitPos()
TransformToVicinityObjects()
void ActionTarget::TransformToVicinityObjects (array< Object > objects)
transform simple array of Objects to VicinityObjects hashmap
Definition at line 144 of file actiontargets.c.
    {
        m_CursorHitPos = cursor_position;
    }
    void DbgPrintTargetDump()
    {
        Print(DumpToString());
    }
    string DumpToString()
VicinityObjects()
void ActionTarget::VicinityObjects ()
Definition at line 116 of file actiontargets.c.
        { return m_Object; }
Variable Documentation
ActionTarget
class ActionTargets ActionTarget
Referenced by ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::CanSetActionFromInventory(), ActionManagerClient::FindActionTarget(), ActionManagerClient::FindContextualUserActions(), ActionManagerClient::ForceTarget(), UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), HandleReciveData(), ActionWorldCraft::HandleReciveData(), FirearmActionAttachMagazine::HandleReciveData(), FirearmActionAttachMagazineQuick::HandleReciveData(), OnCenterPanelDropReceived(), BotWaitForChangeInHands::OnEntry(), ActionManagerClient::PerformActionFromInventory(), ActionManagerClient::PerformActionFromQuickbar(), ManBase::PhysicalPredictiveDropItem(), FirearmActionAttachMagazineQuick::Post_SetupAction(), ManBase::PredictiveForceSwapEntities(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToHands(), ReadFromContext(), ManBase::ReloadWeapon(), InventoryActionHandler::SetAction(), ActionManagerClient::SetActionFromInventory(), PluginBase::SetDeveloperItemClient(), CAContinuousDisinfectPlant::Setup(), FirearmActionLoadBulletQuick::SetupAction(), ActionManagerServer::StartDeliveredAction(), ActionManagerServer::Update(), CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), and ToggleNVGActionInput::UpdatePossibleActions().
m_ComponentIndex
private int m_ComponentIndex
Definition at line 168 of file actiontargets.c.
m_CursorHitPos
private vector m_CursorHitPos
Definition at line 169 of file actiontargets.c.
Referenced by GetCursorHitPos(), and SetCursorHitPos().
m_Object
private Object m_Object
Definition at line 166 of file actiontargets.c.
Referenced by GetObject().
m_Parent
private Object m_Parent
Definition at line 167 of file actiontargets.c.
m_Utility
private float m_Utility
Definition at line 170 of file actiontargets.c.
Referenced by GetUtility().
m_VicinityObjects
private ref map<Object, Object> m_VicinityObjects
Definition at line 114 of file actiontargets.c.
Referenced by ActionTargets::ActionTargets(), ActionTargets::FilterObstructedObjects(), ActionTargets::FilterObstructedObjectsEx(), and ActionTargets::GetVicinityObjects().