DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actioninput.c File Reference
actioninput.c File Reference
Classes
class ActionInput
class CarHornShortActionInput
class ContinuousInteractActionInput
class ContinuousWeaponManipulationActionInput
class DefaultActionInput
class DropActionInput
class ExternalControlledActionInput
class InteractActionInput
class InventoryOnlyActionInput
class NoIndicationActionInputBase
class QuickaBarActionInput
class ToggleLightsActionInput
class ToggleNVGActionInput
class WeaponManipulationActionInput
Enumerations
enum ActionInputType {
AIT_CONTINUOUS , AIT_SINGLE , AIT_DOUBLECLICK , AIT_HOLDSINGLE ,
AIT_CLICKCONTINUOUS , AIT_NOINPUTCONTROL , AIT_INVENTORYINPUT
}
Functions
void _GetSelectedActions (Object action_source_object, out array< ActionBase > select_actions_all, out bool has_any_action_target)
override void ActionsSelectReset ()
CarHornShortActionInput ContinuousDefaultActionInput CarHornLongActionInput (PlayerBase player)
void CarHornShortActionInput (PlayerBase player)
void ContinuousDefaultActionInput (PlayerBase player)
override void ForceAction (ActionBase action, ActionTarget target, ItemBase item)
override ActionBase GetAction ()
override ActionBase GetPossibleAction ()
override int GetPossibleActionIndex ()
override array< ActionBase > GetPossibleActions ()
override int GetPossibleActionsCount ()
override bool HasTarget ()
override void SelectNextAction ()
override void SelectPrevAction ()
void StandardActionInput (PlayerBase player)
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
Variables
ToggleLightsActionInput CarHornLongActionInput
enum ActionInputType m_Action
ItemBase m_Item
NoIndicationActionInputBase m_SelectAction
ActionInput m_SelectActions
int m_selectedActionIndex
ref ActionTarget m_Target
ref ActionTarget targetNew
Enumeration Type Documentation
ActionInputType
enum ActionInputType
Enumerator
AIT_CONTINUOUS
AIT_SINGLE
AIT_DOUBLECLICK
AIT_HOLDSINGLE
AIT_CLICKCONTINUOUS
AIT_NOINPUTCONTROL
AIT_INVENTORYINPUT
Definition at line 1 of file actioninput.c.
{
    AIT_CONTINUOUS,             //React to hold input and release after it
    AIT_SINGLE,                 //React to click input - single use actions
    AIT_DOUBLECLICK,            //React to double click input - single use actions
    AIT_HOLDSINGLE,             //React to hold input - single use actions
    AIT_CLICKCONTINUOUS,        //React to click input for start and click for end
    AIT_NOINPUTCONTROL,
    AIT_INVENTORYINPUT,         //Inventory specific actions
}
Function Documentation
_GetSelectedActions()
void _GetSelectedActions (Object action_source_object, out array< ActionBase > select_actions_all, out bool has_any_action_target)
Definition at line 308 of file actioninput.c.
    {
        if ( !action_source_object )
            return;
        array<ActionBase_Basic> possible_actions;
        array<ref ActionBase> variant_actions;
        action_source_object.GetActions(this.Type(), possible_actions);
        ActionBase action;
        if(possible_actions)
        {
            for (int i = 0; i < possible_actions.Count(); i++)
            {
                action = ActionBase.Cast(possible_actions.Get(i));
                if ( action.HasVariants() )
                {
                    action.UpdateVariants( m_MainItem, m_Target.GetObject(), m_Target.GetComponentIndex() );
                    action.GetVariants( variant_actions);
                    for (int j = 0; j < variant_actions.Count(); j++)
                    {
                        action = variant_actions[j];
                        if ( action.Can(m_Player, m_Target, m_MainItem, m_ConditionMask) )
{
                            select_actions_all.Insert(action);
                            if (action.HasTarget())
                                has_any_action_target = true;
                        }
                    }
                }
                else
                {
                    if ( action.Can(m_Player, m_Target, m_MainItem, m_ConditionMask) )
                    {
                        select_actions_all.Insert(action);
                        if (action.HasTarget())
                            has_any_action_target = true;
                    }
                }
            }
        }
    }
References ActionBase(), m_ConditionMask, m_MainItem, m_Player, m_Target, and Type.
Referenced by UpdatePossibleActions().
ActionsSelectReset()
override void ActionsSelectReset ()
Definition at line 489 of file actioninput.c.
    {
        m_SelectActions.Clear();
        m_selectedActionIndex = 0;
    }
References m_SelectActions, and m_selectedActionIndex.
CarHornLongActionInput()
CarHornShortActionInput ContinuousDefaultActionInput CarHornLongActionInput (PlayerBase player)
Definition at line 623 of file actioninput.c.
    {
        SetInput("UACarHorn");
        m_InputType         = ActionInputType.AIT_CONTINUOUS;
        m_Priority          = 101;
        m_DetectFromItem    = false;
        m_DetectFromTarget  = false;
        m_DetectFromPlayer  = false;
    }
References m_SelectAction.
CarHornShortActionInput()
void CarHornLongActionInput::CarHornShortActionInput (PlayerBase player)
Definition at line 738 of file actioninput.c.
                              : DefaultActionInput
ContinuousDefaultActionInput()
void ContinuousDefaultActionInput (PlayerBase player)
Definition at line 606 of file actioninput.c.
    {
        SetInput("UADefaultAction");
        m_InputType = ActionInputType.AIT_CONTINUOUS;
        m_Priority = 20;
        m_DetectFromTarget = false;
        m_DetectFromItem = true;
        m_DetectFromPlayer = true;
        m_SelectAction = null;
    }
References ContinuousDefaultActionInput(), m_Priority, m_SelectAction, and SetInput().
Referenced by ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::CanSetActionFromInventory(), ContinuousDefaultActionInput(), ScriptedWidgetEventHandler::GetActions(), ActionContinuousBase::GetInputType(), FirearmActionLoadMultiBullet::GetInputType(), ActionManagerClient::PerformActionFromQuickbar(), ActionManagerClient::SetActionFromInventory(), ActionManagerClient::SetDefaultInputsOrder(), and ScriptedWidgetEventHandler::SetMultipleContinuousItemAction().
ForceAction()
override void ForceAction (ActionBase action, ActionTarget target, ItemBase item)
Definition at line 301 of file actioninput.c.
    {
        super.ForceAction(action, target, item);
        m_selectedActionIndex = 0;
    }
References m_selectedActionIndex.
GetAction()
override ActionBase GetAction ()
Definition at line 482 of file actioninput.c.
    {
        if (m_SelectActions.Count() > 0)
            return m_SelectActions[m_selectedActionIndex];
        return null;
    }
References m_SelectActions, and m_selectedActionIndex.
Referenced by ActionManagerClient::EjectAction(), ActionManagerClient::GetVariantManager(), ActionManagerClient::InjectAction(), ActionManagerServer::OnInputUserDataProcess(), and ActionManagerClient::OnInstantAction().
GetPossibleAction()
override ActionBase GetPossibleAction ()
Definition at line 618 of file actioninput.c.
    {
        return m_SelectAction;
    }
References m_SelectAction.
GetPossibleActionIndex()
override int GetPossibleActionIndex ()
Definition at line 477 of file actioninput.c.
    {
        return m_selectedActionIndex;
    }
References m_selectedActionIndex.
GetPossibleActions()
override array< ActionBase > GetPossibleActions ()
Definition at line 462 of file actioninput.c.
    {
        return m_SelectActions;
    }
References m_SelectActions.
GetPossibleActionsCount()
override int GetPossibleActionsCount ()
Definition at line 467 of file actioninput.c.
    {
        return m_SelectActions.Count();
    }
References m_SelectActions.
Referenced by ActionManagerClient::SelectFirstActionCategory(), ActionManagerClient::SelectNextActionCategory(), and ActionManagerClient::SelectPrevActionCategory().
HasTarget()
override bool HasTarget ()
Definition at line 472 of file actioninput.c.
    {
        return m_HasTarget;
    }
References ActionInput::m_HasTarget.
SelectNextAction()
override void SelectNextAction ()
Definition at line 495 of file actioninput.c.
    {
        if(m_SelectActions.Count())
        {
            m_selectedActionIndex++;
            if(m_SelectActions.Count() <= m_selectedActionIndex )
            {
                m_selectedActionIndex = 0;
            }
        }
    }
References m_SelectActions, and m_selectedActionIndex.
SelectPrevAction()
override void SelectPrevAction ()
Definition at line 507 of file actioninput.c.
    {
        if(m_SelectActions.Count())
        {
            m_selectedActionIndex--;
            if(0 > m_selectedActionIndex )
            {
                m_selectedActionIndex = m_SelectActions.Count() - 1;
            }
        }
    }
References m_SelectActions, and m_selectedActionIndex.
StandardActionInput()
void StandardActionInput (PlayerBase player)
Definition at line 295 of file actioninput.c.
    {
        m_selectedActionIndex = 0;
        m_SelectActions = new array<ActionBase>;
    }
References m_SelectActions, m_selectedActionIndex, and StandardActionInput().
Referenced by StandardActionInput().
UpdatePossibleActions()
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
Definition at line 352 of file actioninput.c.
    {
        if ( ForceActionCheck(player))
        {
            m_SelectActions.Clear();
            m_SelectActions.Insert(m_ForcedActionData.m_Action);
            return;
        }
        if(m_ForcedTarget)
        {
            target = m_ForcedTarget;
        }
        array<ActionBase> select_actions_all = new array<ActionBase>;
        int i, last_index;
        bool change = false;
        m_HasTarget = false;
        m_MainItem = item;
        m_Target = target;
        m_ConditionMask = action_condition_mask;
        if( m_DetectFromItem )
        {
            _GetSelectedActions( item, select_actions_all, m_HasTarget);
        }
        if( m_DetectFromTarget )
        {
            _GetSelectedActions( target.GetObject(), select_actions_all, m_HasTarget);
            _GetSelectedActions( target.GetParent(), select_actions_all, m_HasTarget);
        }
        if( m_DetectFromPlayer )
        {
            _GetSelectedActions( player, select_actions_all, m_HasTarget);
        }
        if ( select_actions_all.Count() )
        {
            last_index = 0;
            for ( i = 0; i < select_actions_all.Count(); i++ )
            {
                ActionBase action = select_actions_all[i];
                if ( m_HasTarget )
                {
                    if ( action.HasTarget() )
                    {
                        if ( m_SelectActions.Count() > last_index )
{
                            if ( m_SelectActions[last_index] != action )
{
                                change = true;
                                m_SelectActions[last_index] = action;
                            }
                        }
                        else
{
                            change = true;
                            m_SelectActions.Insert(action);
                        }
                        action.OnActionInfoUpdate(player, target, item);
                        last_index++;
                    }
                }
                else
                {
                    if ( m_SelectActions.Count() > last_index )
                    {
                        if ( m_SelectActions[last_index] != action )
{
                            change = true;
                            m_SelectActions[last_index++] = action;
                        }
                    }
                    else
                    {
                        change = true;
                        m_SelectActions.Insert(action);
                    }
                    action.OnActionInfoUpdate(player, target, item);
                    last_index++;
                }
            }
        }
        else
        {
            m_selectedActionIndex = 0;
            m_SelectActions.Clear();
        }
        if (m_SelectActions.Count() > last_index)
        {
            change = true;
            for (i = last_index; i < m_SelectActions.Count(); i++)
            {
                m_SelectActions.Remove(last_index);
            }
        }
        if ( change )
        {
            m_selectedActionIndex = 0;
            m_Player.GetActionManager().SelectFirstActionCategory();
        }
    }
References _GetSelectedActions(), ActionBase(), ActionInput::ForceActionCheck(), m_ConditionMask, ActionInput::m_ForcedTarget, m_MainItem, m_Player, m_SelectActions, m_selectedActionIndex, and m_Target.
Variable Documentation
CarHornLongActionInput
ToggleLightsActionInput CarHornLongActionInput
Referenced by ActionCarHornLong::GetInputType().
m_Action
enum ActionInputType m_Action
Referenced by ScriptedWidgetEventHandler::ContinuousActionProgress(), ScriptedWidgetEventHandler::GetActions(), HandStateBase::HandStartAction(), HandStateBase::OnEntry(), and ScriptedWidgetEventHandler::Update().
m_Item
ItemBase m_Item
Definition at line 16 of file actioninput.c.
Referenced by HandsPreview::CreateNewIcon(), HandsPreview::GetFocusedItem(), GetItem(), RadialQuickbarItem(), BleedingSourcesManagerBase::RemoveBleedingSource(), HandsPreview::RemoveItem(), HandsPreview::Select(), HandsPreview::SelectItem(), and SetItem().
m_SelectAction
NoIndicationActionInputBase m_SelectAction
Referenced by CarHornLongActionInput(), ContinuousDefaultActionInput(), CarHornShortActionInput::GetAction(), ToggleLightsActionInput::GetAction(), ToggleNVGActionInput::GetAction(), GetPossibleAction(), CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), and ToggleNVGActionInput::UpdatePossibleActions().
m_SelectActions
ActionInput m_SelectActions
Referenced by ActionsSelectReset(), GetAction(), GetPossibleActions(), GetPossibleActionsCount(), SelectNextAction(), SelectPrevAction(), StandardActionInput(), and UpdatePossibleActions().
m_selectedActionIndex
int m_selectedActionIndex
Definition at line 293 of file actioninput.c.
Referenced by ActionsSelectReset(), ForceAction(), GetAction(), GetPossibleActionIndex(), SelectNextAction(), SelectPrevAction(), StandardActionInput(), and UpdatePossibleActions().
m_Target
ref ActionTarget m_Target
Definition at line 15 of file actioninput.c.
Referenced by CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), and ToggleNVGActionInput::UpdatePossibleActions().
targetNew
ref ActionTarget targetNew
Definition at line 736 of file actioninput.c.