DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/vehicles/actioncarhorn.c File Reference
actioncarhorn.c File Reference
Classes
class ActionCarHornBase
class ActionCarHornLong
class CarHornActionData
Functions
CarHornActionData ActionData ActionCarHornShort ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedInVehicle ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasProgress ()
override bool HasTarget ()
override void OnEndInput (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStart (ActionData action_data)
sets the m_ActionNeeded flag on both sides
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
special case - manually ends the action on exec event
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool UseMainItem ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Variables
class ActionCarHornBase m_ActionNeedEnd
CarScript m_Car
Function Documentation
ActionCarHornShort()
CarHornActionData ActionData ActionCarHornShort ()
Definition at line 53 of file actioncarhorn.c.
    {
        m_CallbackClass = ActionCarHornShortCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONMOD_TOOTHORN;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_ALL;
    }
Referenced by ActionConstructor::RegisterActions(), and SetActions().
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 111 of file actioncarhorn.c.
    {
        return ActionCarHornBase.ActionCondition(player);
    }
References ActionCarHornBase::ActionCondition().
CanBeUsedInVehicle()
override bool CanBeUsedInVehicle ()
Definition at line 84 of file actioncarhorn.c.
    {
        return true;
    }
CreateActionData()
override ActionData CreateActionData ()
Definition at line 105 of file actioncarhorn.c.
    {
        ActionData action_data = new CarHornActionData();
        return action_data;
    }
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 94 of file actioncarhorn.c.
    {
        m_ConditionItem     = new CCINone();
        m_ConditionTarget   = new CCTNone();
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 100 of file actioncarhorn.c.
    {
        return CarHornShortActionInput;
    }
HandleReciveData()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
Definition at line 197 of file actioncarhorn.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        CarHornActionReceiveData carHornReceivedData    = CarHornActionReceiveData.Cast(action_recive_data);
        CarHornActionData carHornData                   = CarHornActionData.Cast(action_data);
        carHornData.m_ActionNeedEnd                     = carHornReceivedData.m_ActionNeedEnd;
        carHornData.m_Car                               = carHornReceivedData.m_Car;
    }
References CarHornActionData::m_ActionNeedEnd, and CarHornActionData::m_Car.
HasProgress()
override bool HasProgress ()
Definition at line 79 of file actioncarhorn.c.
    {
        return false;
    }
HasTarget()
override bool HasTarget ()
Definition at line 74 of file actioncarhorn.c.
    {
        return false;
    }
OnEndInput()
override void OnEndInput (ActionData action_data)
Definition at line 129 of file actioncarhorn.c.
    {
        super.OnEndInput(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.OFF);
    }
References ActionCarHornBase::SetCarHornState().
OnEndServer()
override void OnEndServer (ActionData action_data)
Definition at line 155 of file actioncarhorn.c.
    {
        super.OnEndServer(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.OFF);
    }
References ActionCarHornBase::SetCarHornState().
OnStart()
override void OnStart (ActionData action_data)
sets the m_ActionNeeded flag on both sides
Definition at line 138 of file actioncarhorn.c.
    {
        super.OnStart(action_data);
        CarHornActionData carHornData   = CarHornActionData.Cast(action_data);
        carHornData.m_ActionNeedEnd     = true;
        carHornData.m_Car               = CarScript.Cast(action_data.m_Player.GetCommand_Vehicle().GetTransport());
    }
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and ActionData::m_Player.
OnStartServer()
override void OnStartServer (ActionData action_data)
Definition at line 147 of file actioncarhorn.c.
    {
        super.OnStartServer(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.SHORT);
    }
References ActionCarHornBase::SetCarHornState().
OnUpdate()
override void OnUpdate (ActionData action_data)
special case - manually ends the action on exec event
Definition at line 117 of file actioncarhorn.c.
    {
        super.OnUpdate(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        if (carHornData.m_WasExecuted && carHornData.m_ActionNeedEnd)
        {
            carHornData.m_Callback.SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            carHornData.m_ActionNeedEnd = false;
        }
    }
References CarHornActionData::m_ActionNeedEnd, ActionData::m_Callback, ActionData::m_WasExecuted, and ActionBaseCB::SetCommand().
ReadFromContext()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
Definition at line 173 of file actioncarhorn.c.
    {
        if (!action_recive_data)
        {
            action_recive_data = new CarHornActionReceiveData();
        }
        super.ReadFromContext(ctx, action_recive_data);
        bool needUpdate;
        if (!ctx.Read(needUpdate))
            return false;
        CarScript carScript;
        if (!ctx.Read(carScript))
            return false;
        CarHornActionReceiveData carHornReceivedData    = CarHornActionReceiveData.Cast(action_recive_data);
        carHornReceivedData.m_ActionNeedEnd             = needUpdate;
        carHornReceivedData.m_Car                       = carScript;
        return true;
    }
References Serializer::Read().
UseMainItem()
override bool UseMainItem ()
Definition at line 89 of file actioncarhorn.c.
    {
        return false;
    }
WriteToContext()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Definition at line 163 of file actioncarhorn.c.
    {
        super.WriteToContext(ctx, action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ctx.Write(carHornData.m_ActionNeedEnd);
        ctx.Write(carHornData.m_Car);
    }
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and Serializer::Write().
Variable Documentation
m_ActionNeedEnd
bool m_ActionNeedEnd
Definition at line 68 of file actioncarhorn.c.
m_Car
CarScript m_Car
Definition at line 53 of file actioncarhorn.c.