DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionturnvalve.c File Reference
actionturnvalve.c File Reference
Classes
class ActionTurnValveCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionTurnValveCB ActionContinuousBaseCB ActionTurnValve ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
override GetInputType ()
override void OnEnd (ActionData action_data)
override void OnStart (ActionData action_data)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 31 of file actionturnvalve.c.
    {
        EntityAI targetEntity;
        if (Class.CastTo(targetEntity, target.GetObject()))
        {
            if (targetEntity.HasTurnableValveBehavior())
            {
                int valveIndex = targetEntity.GetTurnableValveIndex(target.GetComponentIndex());
                if (valveIndex != -1)
                {
                    if (!IsInReach(player, target, UAMaxDistances.DEFAULT))
                    {
                        return false;
                    }
                    return targetEntity.IsValveTurnable(valveIndex);
                }
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, and IsInReach().
ActionTurnValve()
ActionTurnValveCB ActionContinuousBaseCB ActionTurnValve ()
Definition at line 1 of file actionturnvalve.c.
    {
        m_CallbackClass = ActionTurnValveCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_TURN_VALVE;
        m_FullBody      = true;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text          = "#STR_USRACT_TURN";
    }
Referenced by ActionConstructor::RegisterActions().
CreateActionComponent()
override void ActionTurnValve::CreateActionComponent ()
Definition at line 12 of file actionturnvalve.c.
    {
        m_CallbackClass = ActionTurnValveCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_TURN_VALVE;
        m_FullBody      = true;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 25 of file actionturnvalve.c.
    {
        m_ConditionItem     = new CCINone();
        m_ConditionTarget   = new CCTCursor();
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override GetInputType ()
Definition at line 20 of file actionturnvalve.c.
    {
        return ContinuousInteractActionInput;
    }
OnEnd()
override void OnEnd (ActionData action_data)
Definition at line 62 of file actionturnvalve.c.
    {
        action_data.m_Player.TryHideItemInHands(false);
        super.OnEnd(action_data);
    }
References ActionData::m_Player.
OnStart()
override void OnStart (ActionData action_data)
Definition at line 54 of file actionturnvalve.c.
    {
        super.OnStart(action_data);
        action_data.m_Player.TryHideItemInHands(true);
    }
References ActionData::m_Player.