DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actiondisarmexplosivewithremotedetonatorunpaired.c File Reference
actiondisarmexplosivewithremotedetonatorunpaired.c File Reference
Classes
class ActionDisarmExplosiveWithRemoteDetonatorUnpairedCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionDisarmExplosiveWithRemoteDetonatorUnpairedCB ActionDisarmExplosiveCB ActionDisarmExplosiveWithRemoteDetonatorUnpaired ()
override void CreateActionComponent ()
override void CreateConditionComponents ()
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
explosives only
RD trigger
RD kit
Definition at line 26 of file actiondisarmexplosivewithremotedetonatorunpaired.c.
    {
        if (!target)
        {
            return false;
        }
        ExplosivesBase explosive = ExplosivesBase.Cast(target.GetObject());
        if (!explosive)
        {
            return false;
        }
        if (explosive.IsRuined() || !explosive.GetArmed() || !explosive.CanBeDisarmed())
        {
            return false;
        }
        if (explosive.GetAttachmentByType(KitchenTimer) || explosive.GetAttachmentByType(AlarmClock_ColorBase))
        {
            return false;
        }
        RemoteDetonatorReceiver attachedReceiver = RemoteDetonatorReceiver.Cast(explosive.GetAttachmentByType(RemoteDetonatorReceiver));
        if (!explosive.IsInherited(ClaymoreMine) && attachedReceiver && attachedReceiver.IsRuined())
        {
            return false;
        }
        RemoteDetonatorTrigger rdt = RemoteDetonatorTrigger.Cast(item);
        if (rdt && target.GetObject() != rdt.GetControlledDevice())
        {
            return true;
        }
        RemoteDetonator rd = RemoteDetonator.Cast(item);
        if (rd && rd.IsKit())
        {
            return true;
        }
        return false;
    }
References ExplosivesBase(), RemoteDetonatorTrigger::GetControlledDevice(), and RemoteDetonatorReceiver().
ActionDisarmExplosiveWithRemoteDetonatorUnpaired()
ActionDisarmExplosiveWithRemoteDetonatorUnpairedCB ActionDisarmExplosiveCB ActionDisarmExplosiveWithRemoteDetonatorUnpaired ()
Definition at line 1 of file actiondisarmexplosivewithremotedetonatorunpaired.c.
    {
        m_CallbackClass = ActionDisarmExplosiveWithRemoteDetonatorUnpairedCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody      = true;
        m_Text          = "#disarm";
    }
Referenced by OnVariablesSynchronized(), ActionConstructor::RegisterActions(), and RemoteDetonatorReceiver().
CreateActionComponent()
override void ActionDisarmExplosiveWithRemoteDetonatorUnpaired::CreateActionComponent ()
Definition at line 12 of file actiondisarmexplosivewithremotedetonatorunpaired.c.
    {
        m_CallbackClass = ActionDisarmExplosiveWithRemoteDetonatorUnpairedCB;
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH;
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 20 of file actiondisarmexplosivewithremotedetonatorunpaired.c.
    {
        m_ConditionItem     = new CCINonRuined();
        m_ConditionTarget   = new CCTCursor();
    }
References m_ConditionItem, and m_ConditionTarget.