DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/actionsequentialbase.c File Reference
actionsequentialbase.c File Reference
Classes
class SequentialActionData
Functions
SequentialActionData ActionData ActionMultiStageBase ()
override bool CanBePerformedFromInventory ()
override bool CanBeUsedOnBack ()
override bool CanBeUsedRaised ()
override ActionData CreateActionData ()
override int GetActionCategory ()
override GetInputType ()
override float GetProgress (ActionData action_data)
override int GetStanceMask (PlayerBase player)
void MultiStageBaseActionData ()
void OnStageEnd (SequentialActionData action_data)
void OnStageStart (SequentialActionData action_data)
void SetStage (int stage, SequentialActionData action_data)
override void Start (ActionData action_data)
Variables
int m_Stage
Function Documentation
ActionMultiStageBase()
SequentialActionData ActionData ActionMultiStageBase ()
Definition at line 1 of file actionsequentialbase.c.
    {
    }
CanBePerformedFromInventory()
override bool CanBePerformedFromInventory ()
Definition at line 37 of file actionsequentialbase.c.
    {
        return true;
    }
CanBeUsedOnBack()
override bool CanBeUsedOnBack ()
Definition at line 42 of file actionsequentialbase.c.
    {
        return true;
    }
CanBeUsedRaised()
override bool CanBeUsedRaised ()
Definition at line 47 of file actionsequentialbase.c.
    {
        return true;
    }
CreateActionData()
override ActionData CreateActionData ()
Definition at line 16 of file actionsequentialbase.c.
    {
        ActionData action_data = new SequentialActionData;
        return action_data;
    }
GetActionCategory()
override int GetActionCategory ()
Definition at line 27 of file actionsequentialbase.c.
    {
        return AC_SINGLE_USE;
    }
References AC_SINGLE_USE.
GetInputType()
override GetInputType ()
Definition at line 32 of file actionsequentialbase.c.
    {
        return DefaultActionInput;
    }
GetProgress()
override float GetProgress (ActionData action_data)
Definition at line 75 of file actionsequentialbase.c.
    {
        return -1;
    }
GetStanceMask()
override int GetStanceMask (PlayerBase player)
Definition at line 22 of file actionsequentialbase.c.
    {
        return DayZPlayerConstants.STANCEMASK_ALL;
    }
MultiStageBaseActionData()
void ActionMultiStageBase::MultiStageBaseActionData ()
Definition at line 14 of file actionsequentialbase.c.
    {
OnStageEnd()
void OnStageEnd (SequentialActionData action_data)
Definition at line 71 of file actionsequentialbase.c.
    {
    }
Referenced by SetStage().
OnStageStart()
void OnStageStart (SequentialActionData action_data)
Definition at line 67 of file actionsequentialbase.c.
    {
    }
Referenced by SetStage(), and Start().
SetStage()
void SetStage (int stage, SequentialActionData action_data)
Definition at line 60 of file actionsequentialbase.c.
    {
        OnStageEnd(action_data);
        action_data.m_Stage = stage;
        OnStageStart(action_data);
    }
References SequentialActionData::m_Stage, OnStageEnd(), and OnStageStart().
Referenced by FirearmActionDetachMagazine::OnUpdate().
Start()
override void Start (ActionData action_data)
Definition at line 52 of file actionsequentialbase.c.
    {
        super.Start( action_data );
        SequentialActionData ad = SequentialActionData.Cast( action_data );
        OnStageStart( ad );
    }
References OnStageStart().
Variable Documentation
m_Stage
int m_Stage
Definition at line 13 of file actionsequentialbase.c.