DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionrestraintarget.c File Reference
actionrestraintarget.c File Reference
Classes
class ActionRestrainTarget
class ActionRestrainTargetCB
class ChainedDropAndRestrainLambda
class SurrenderData
Deprecated.
Functions
override void OnSuccess (EntityAI entity)
void RestrainTargetPlayerLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Variables
ChainedDropAndRestrainLambda m_TargetPlayer
Function Documentation
OnSuccess()
override void OnSuccess (EntityAI entity)
Definition at line 189 of file actionrestraintarget.c.
    {
        super.OnSuccess(new_item);
        m_TargetPlayer.SetRestrained(true);
        m_TargetPlayer.OnItemInHandsChanged();
    }
References m_TargetPlayer.
RestrainTargetPlayerLambda()
void RestrainTargetPlayerLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 180 of file actionrestraintarget.c.
    {
        m_TargetPlayer = player;
        InventoryLocation targetHnd = new InventoryLocation;
        targetHnd.SetHands(m_TargetPlayer, null);
        OverrideNewLocation(targetHnd);
    }
References m_TargetPlayer, and InventoryLocation::SetHands().
Referenced by ActionRestrainTarget::OnFinishProgressServer(), and ChainedDropAndRestrainLambda::OnSuccess().
Variable Documentation
m_TargetPlayer
ChainedDropAndRestrainLambda m_TargetPlayer
Referenced by OnSuccess(), and RestrainTargetPlayerLambda().