DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionuncoverheadself.c File Reference
actionuncoverheadself.c File Reference
Classes
class ActionUncoverHeadBase
class ActionUncoverHeadSelfCB
Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
ActionUncoverHeadBase ActionContinuousBase ActionUncoverHeadSelf ()
override void CreateConditionComponents ()
override bool HasTarget ()
bool IsWearingBurlap (PlayerBase player)
override void OnFinishProgressServer (ActionData action_data)
void UncoverHead (PlayerBase target, PlayerBase source)
Function Documentation
ActionCondition()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
Definition at line 72 of file actionuncoverheadself.c.
    {
        if ( IsWearingBurlap(player) )
            return true;
        return false;
    }
References IsWearingBurlap().
ActionUncoverHeadSelf()
ActionUncoverHeadBase ActionContinuousBase ActionUncoverHeadSelf ()
Definition at line 1 of file actionuncoverheadself.c.
    {
        m_CallbackClass = ActionUncoverHeadSelfCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_SELF;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#uncover_head";
    }
Referenced by ActionConstructor::RegisterActions(), and ManBase::SetActions().
CreateConditionComponents()
override void CreateConditionComponents ()
Definition at line 61 of file actionuncoverheadself.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool HasTarget ()
Definition at line 67 of file actionuncoverheadself.c.
    {
        return false;
    }
IsWearingBurlap()
bool IsWearingBurlap (PlayerBase player)
Definition at line 87 of file actionuncoverheadself.c.
    {
        EntityAI attachment;
        Class.CastTo(attachment, player.GetInventory().FindAttachment(InventorySlots.HEADGEAR));
        if ( attachment && attachment.IsInherited(BurlapSackCover) )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
Referenced by ActionCondition().
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 80 of file actionuncoverheadself.c.
    {
        UncoverHead(action_data.m_Player, action_data.m_Player);
    }
References ActionData::m_Player, and ActionUncoverHeadBase::UncoverHead().
UncoverHead()
void ActionUncoverHeadSelf::UncoverHead (PlayerBase target, PlayerBase source)
Definition at line 53 of file actionuncoverheadself.c.
    {
        m_CallbackClass = ActionUncoverHeadSelfCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_SELF;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#uncover_head";
    }
    override void CreateConditionComponents()
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
    override bool HasTarget()
    {
        return false;
    }
    override bool ActionCondition( PlayerBase player, ActionTarget target, ItemBase item )
    {
        if ( IsWearingBurlap(player) )
            return true;
        return false;
    }
    override void OnFinishProgressServer( ActionData action_data )
    {
        UncoverHead(action_data.m_Player, action_data.m_Player);
    }
    bool IsWearingBurlap( PlayerBase player )
References m_StanceMask, and m_Text.