DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionfishingnew.c File Reference
actionfishingnew.c File Reference
Classes
class ActionFishingNew
class FishingActionData
Functions
override void CreateActionComponent ()
override void EndActionComponent ()
void HandleFishingResultFailure ()
void HandleFishingResultSuccess ()
override void OnStateChange (int pOldState, int pCurrentState)
Variables
FishingActionData m_ActionDataFishing
ref array< string > m_JunkTypes = {"Wellies_Black","Wellies_Brown","Wellies_Green","Wellies_Grey","Pot"}
Function Documentation
CreateActionComponent()
override void CreateActionComponent ()
Definition at line 32 of file actionfishingnew.c.
    {
        EnableStateChangeCallback();
        m_ActionData.m_ActionComponent = new CAContinuousRepeatFishing(3.0);
    }
References EnableStateChangeCallback().
EndActionComponent()
override void EndActionComponent ()
Definition at line 38 of file actionfishingnew.c.
    {
        m_ActionDataFishing = FishingActionData.Cast(m_ActionData);
        if (!m_ActionDataFishing)
        {
            super.EndActionComponent();
            return;
        }
        if ( m_ActionDataFishing.m_State == UA_FINISHED )
        {
            if ( m_ActionDataFishing.m_FishingResult == 1 )
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            else if ( m_ActionDataFishing.m_FishingResult == 0 )
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
        }
        else if (m_ActionDataFishing.m_State == UA_CANCEL )
        {
            ActionContinuousBase action = ActionContinuousBase.Cast(m_ActionDataFishing.m_Action);
            if(action.HasAlternativeInterrupt())
            {
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
            }
            else
            {
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            }
            m_Canceled = true;
            return;
        }
        else
        {
            if ( m_ActionDataFishing.m_FishingResult == 1 )
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            else if ( m_ActionDataFishing.m_FishingResult == 0 )
                SetCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
        }
        m_ActionDataFishing.m_State = UA_FINISHED;
    }
References ActionContinuousBase::HasAlternativeInterrupt(), ActionData::m_Action, m_ActionDataFishing, m_Canceled, FishingActionData::m_FishingResult, ActionData::m_State, ActionBaseCB::SetCommand(), UA_CANCEL, and UA_FINISHED.
HandleFishingResultFailure()
void HandleFishingResultFailure ()
Definition at line 133 of file actionfishingnew.c.
    {
        if (!GetGame().IsMultiplayer() || GetGame().IsServer())
        {
            if (!m_ActionDataFishing.m_Bait)
                m_ActionDataFishing.InitBait(ItemBase.Cast(m_ActionDataFishing.m_MainItem.FindAttachmentBySlotName("Hook")));
            if (Math.RandomFloatInclusive(0.0,1.0) > m_ActionDataFishing.FISHING_HOOK_LOSS) //loss of worm only
            {
                if (!m_ActionDataFishing.IsBaitEmptyHook())
                {
                    m_ActionDataFishing.m_Bait.AddHealth(-m_ActionDataFishing.FISHING_DAMAGE);
                    MiscGameplayFunctions.TurnItemIntoItem(m_ActionDataFishing.m_Bait,m_ActionDataFishing.m_Bait.ConfigGetString("hookType"),m_ActionDataFishing.m_Player);
                }
            }
            else //loss of the entire hook
            {
                m_ActionDataFishing.m_Bait.Delete();
            }
            m_ActionDataFishing.m_MainItem.AddHealth(-m_ActionDataFishing.FISHING_DAMAGE);
        }
    }
References FishingActionData::FISHING_DAMAGE, FishingActionData::FISHING_HOOK_LOSS, GetGame(), FishingActionData::InitBait(), FishingActionData::IsBaitEmptyHook(), m_ActionDataFishing, FishingActionData::m_Bait, ActionData::m_MainItem, ActionData::m_Player, and Math::RandomFloatInclusive().
Referenced by OnStateChange().
HandleFishingResultSuccess()
void HandleFishingResultSuccess ()
Definition at line 79 of file actionfishingnew.c.
    {
        if (!GetGame().IsMultiplayer() || GetGame().IsServer())
        {
            ItemBase fish;
            if (!m_ActionDataFishing.m_Bait)
                m_ActionDataFishing.InitBait(ItemBase.Cast(m_ActionDataFishing.m_MainItem.FindAttachmentBySlotName("Hook")));
            if (!m_ActionDataFishing.IsBaitEmptyHook())
            {
                m_ActionDataFishing.m_Bait.AddHealth(-m_ActionDataFishing.FISHING_DAMAGE);
                MiscGameplayFunctions.TurnItemIntoItem(m_ActionDataFishing.m_Bait,m_ActionDataFishing.m_Bait.ConfigGetString("hookType"),m_ActionDataFishing.m_Player);
            }
            else
            {
                m_ActionDataFishing.m_Bait.AddHealth(-m_ActionDataFishing.FISHING_DAMAGE);
            }
            float rnd = Math.RandomFloatInclusive(0.0,1.0);
            if (rnd > m_ActionDataFishing.FISHING_GARBAGE_CHANCE)
            {
                if (m_ActionDataFishing.m_IsSurfaceSea)
                    fish = ItemBase.Cast(GetGame().CreateObjectEx("Mackerel",m_ActionDataFishing.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
                else
                    fish = ItemBase.Cast(GetGame().CreateObjectEx("Carp",m_ActionDataFishing.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
            }
            else
            {
                if ( !m_ActionDataFishing.m_IsSurfaceSea )
                {
                    string junk_type = m_JunkTypes.Get(Math.RandomInt(0,m_JunkTypes.Count()));
                    fish = ItemBase.Cast(GetGame().CreateObjectEx(junk_type,m_ActionDataFishing.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
                    fish.SetHealth("","Health",fish.GetMaxHealth("","Health") * 0.1);
                }
            }
            if (fish)
            {
                //Print("---Caught something: " + fish + "---");
                fish.SetWet(0.3);
                if (fish.HasQuantity())
                {
                    float coef = Math.RandomFloatInclusive(0.5, 1.0);
                    float item_quantity = fish.GetQuantityMax() * coef;
                    item_quantity = Math.Round(item_quantity);
                    fish.SetQuantity( item_quantity );
                }
            }
            m_ActionDataFishing.m_MainItem.AddHealth(-m_ActionDataFishing.FISHING_DAMAGE);
        }
    }
References ECE_PLACE_ON_SURFACE, FishingActionData::FISHING_DAMAGE, FishingActionData::FISHING_GARBAGE_CHANCE, GetGame(), FishingActionData::InitBait(), FishingActionData::IsBaitEmptyHook(), m_ActionDataFishing, FishingActionData::m_Bait, FishingActionData::m_IsSurfaceSea, m_JunkTypes, ActionData::m_MainItem, ActionData::m_Player, Math::RandomFloatInclusive(), Math::RandomInt(), and Math::Round().
Referenced by OnStateChange().
OnStateChange()
override void OnStateChange (int pOldState, int pCurrentState)
Definition at line 157 of file actionfishingnew.c.
    {
        if (pCurrentState == STATE_NONE && m_ActionDataFishing)
        {
            if (m_ActionDataFishing.m_FishingResult == 1 && pOldState == STATE_LOOP_END)
            {
                HandleFishingResultSuccess();
            }
            else if (m_ActionDataFishing.m_FishingResult == 0 && pOldState == STATE_LOOP_END2)
            {
                HandleFishingResultFailure();
            }
        }
    }
References HandleFishingResultFailure(), HandleFishingResultSuccess(), m_ActionDataFishing, FishingActionData::m_FishingResult, STATE_LOOP_END, STATE_LOOP_END2, and STATE_NONE.
Variable Documentation
m_ActionDataFishing
FishingActionData m_ActionDataFishing
Referenced by EndActionComponent(), HandleFishingResultFailure(), HandleFishingResultSuccess(), and OnStateChange().
m_JunkTypes
ref array<string> m_JunkTypes = {"Wellies_Black","Wellies_Brown","Wellies_Green","Wellies_Grey","Pot"}
Definition at line 30 of file actionfishingnew.c.
Referenced by HandleFishingResultSuccess().