DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/continuous/actionturnvalveundergroundreservoir.c File Reference
actionturnvalveundergroundreservoir.c File Reference
Classes
class ActionTurnValveUndergroundReservoirCB
Functions
ActionTurnValveUndergroundReservoirCB ActionTurnValveCB ActionTurnValveUndergroundReservoir ()
override void CreateActionComponent ()
override protected void CreateAndSetupActionCallback (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
Function Documentation
ActionTurnValveUndergroundReservoir()
ActionTurnValveUndergroundReservoirCB ActionTurnValveCB ActionTurnValveUndergroundReservoir ()
Definition at line 1 of file actionturnvalveundergroundreservoir.c.
    {
        m_CallbackClass = ActionTurnValveUndergroundReservoirCB;
    }
Referenced by ActionConstructor::RegisterActions(), and SetActions().
CreateActionComponent()
override void ActionTurnValveUndergroundReservoir::CreateActionComponent ()
Definition at line 13 of file actionturnvalveundergroundreservoir.c.
    {
        m_CallbackClass = ActionTurnValveUndergroundReservoirCB;
    }
CreateAndSetupActionCallback()
override protected void CreateAndSetupActionCallback (ActionData action_data)
Definition at line 17 of file actionturnvalveundergroundreservoir.c.
    {
        super.CreateAndSetupActionCallback(action_data);
        Land_Underground_WaterReservoir reservoir = Land_Underground_WaterReservoir.Cast(action_data.m_Target.GetObject());
        if (reservoir)
        {
            if (action_data.m_Callback)
            {
                array<vector> data = reservoir.GetValveAligningPointsWS(reservoir.GetTurnableValveIndex(action_data.m_Target.GetComponentIndex()));
                vector position = data[0];
                vector direction = data[1] - data[0];
                action_data.m_Callback.SetAligning(position, direction.Normalized());
            }
        }
    }
References Land_Underground_WaterReservoir(), ActionData::m_Callback, ActionData::m_Target, and vector::Normalized().
OnEndAnimationLoop()
override void OnEndAnimationLoop (ActionData action_data)
Definition at line 46 of file actionturnvalveundergroundreservoir.c.
    {
        super.OnEndAnimationLoop(action_data);
        Land_Underground_WaterReservoir reservoir = Land_Underground_WaterReservoir.Cast(action_data.m_Target.GetObject());
        if (reservoir)
        {
            reservoir.OnValveManipulationCanceled(reservoir.GetTurnableValveIndex(action_data.m_Target.GetComponentIndex()));
        }
    }
References Land_Underground_WaterReservoir(), and ActionData::m_Target.
OnFinishProgressServer()
override void OnFinishProgressServer (ActionData action_data)
Definition at line 57 of file actionturnvalveundergroundreservoir.c.
    {
        super.OnFinishProgressServer(action_data);
        Land_Underground_WaterReservoir reservoir = Land_Underground_WaterReservoir.Cast(action_data.m_Target.GetObject());
        if (reservoir)
        {
            reservoir.OnValveManipulationEnd(reservoir.GetTurnableValveIndex(action_data.m_Target.GetComponentIndex()));
        }
    }
References Land_Underground_WaterReservoir(), and ActionData::m_Target.
OnStartAnimationLoopServer()
override void OnStartAnimationLoopServer (ActionData action_data)
Definition at line 35 of file actionturnvalveundergroundreservoir.c.
    {
        super.OnStartAnimationLoopServer(action_data);
        Land_Underground_WaterReservoir reservoir = Land_Underground_WaterReservoir.Cast(action_data.m_Target.GetObject());
        if (reservoir)
        {
            reservoir.OnValveManipulationStart(reservoir.GetTurnableValveIndex(action_data.m_Target.GetComponentIndex()));
        }
    }
References Land_Underground_WaterReservoir(), and ActionData::m_Target.