DayzKode: P:/scripts/4_world/DayZ/classes/useractionscomponent/actions/singleuse/actionplaceovenindoor.c File Reference
actionplaceovenindoor.c File Reference
Classes
class ActionPlaceOvenIndoor
Functions
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
void FireplaceToIndoorOvenLambda (EntityAI old_item, string new_item_type, PlayerBase player, vector pos, Object target)
Variables
float m_FireplaceRot
ActionPlaceOvenIndoor m_FirePointIndex
vector m_SmokePosition
Function Documentation
CopyOldPropertiesToNew()
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Definition at line 102 of file actionplaceovenindoor.c.
    {
        super.CopyOldPropertiesToNew( old_item, new_item );
        OvenIndoor fireplace_indoor = OvenIndoor.Cast( new_item );
        if ( fireplace_indoor )
        {
            //set fire point index
            fireplace_indoor.SetFirePointIndex( m_FirePointIndex );
            // rotate fireplace
            vector fprot = vector.Zero;
            fprot[0] = m_FireplaceRot;
            fireplace_indoor.SetOrientation( fprot );
            Print(fireplace_indoor.GetOrientation());
            // smoke pos (chimney)
            fireplace_indoor.SetSmokePointPosition( m_SmokePosition );
            //synchronize
            fireplace_indoor.Synchronize();
        }
    }
References m_FireplaceRot, m_FirePointIndex, m_SmokePosition, Print(), and vector::Zero.
FireplaceToIndoorOvenLambda()
void FireplaceToIndoorOvenLambda (EntityAI old_item, string new_item_type, PlayerBase player, vector pos, Object target)
Definition at line 84 of file actionplaceovenindoor.c.
    {
        InventoryLocation gnd = new InventoryLocation;
        vector mtx[4];
        Math3D.MatrixIdentity4( mtx );
        mtx[3] = pos;
        gnd.SetGround( NULL, mtx );
        OverrideNewLocation( gnd );
        //set fire point index and smoke point position in world
        m_FirePointIndex = player.GetLastFirePointIndex();
        m_FireplaceRot = player.GetLastFirePointRot();
        vector smoke_point_pos = target.GetSelectionPositionMS( OvenIndoor.OVENPOINT_SMOKE_POSITION + m_FirePointIndex.ToString() );
        vector smoke_point_pos_world = target.ModelToWorld( smoke_point_pos );
        m_SmokePosition = smoke_point_pos_world;
    }
References m_FireplaceRot, m_FirePointIndex, m_SmokePosition, Math3D::MatrixIdentity4(), and InventoryLocation::SetGround().
Referenced by ActionPlaceOvenIndoor::OnExecuteServer().
Variable Documentation
m_FireplaceRot
float m_FireplaceRot
Definition at line 81 of file actionplaceovenindoor.c.
m_FirePointIndex
ActionPlaceOvenIndoor m_FirePointIndex
m_SmokePosition
vector m_SmokePosition
Definition at line 82 of file actionplaceovenindoor.c.