DayzKode: P:/scripts/3_game/DayZ/aibehaviour.c File Reference
aibehaviour.c File Reference
Classes
class AIBehaviourHLData
class AIBehaviourHLDataZombie2
class AIBehaviourHLZombie2
Functions
private void AIBehaviourHLData ()
proto native AIBehaviourHLData GetTemplateData ()
void OnAnimationEvent (int nameCrc)
void OnDamage (float damage, EntityAI source)
void OnDamageInflicted ()
void OnInit ()
void OnParseConfig ()
proto native void ParseAlertLevel (string name)
proto native void ParseBehaviourSlot (string name)
proto native float ReadParamValue (string paramName, float defValue)
static proto void RegAIBehaviour (string behname, typename behClass, typename behClassData)
proto native void SetNextBehaviour (int BehaviourCrc)
void Simulate (float timeDelta)
proto native void SwitchToNextBehaviour ()
private void ~AIBehaviourHL ()
private void ~AIBehaviourHLData ()
Variables
AIBehaviourHLZombie2 AIBehaviourHL
Detailed Description
this file is interface to AI Behaviour
Definition in file aibehaviour.c.
Function Documentation
AIBehaviourHLData()
private void AIBehaviourHL::AIBehaviourHLData ()
Definition at line 45 of file aibehaviour.c.
{}
GetTemplateData()
proto native AIBehaviourHLData GetTemplateData ()
Referenced by AIBehaviourHLZombie2::GetData().
OnAnimationEvent()
void OnAnimationEvent (int nameCrc)
Definition at line 64 of file aibehaviour.c.
{}
OnDamage()
void OnDamage (float damage, EntityAI source)
Definition at line 61 of file aibehaviour.c.
{}
OnDamageInflicted()
void OnDamageInflicted ()
Definition at line 63 of file aibehaviour.c.
{}
OnInit()
void OnInit ()
Definition at line 49 of file aibehaviour.c.
{};
Referenced by AnimationTimer::AnimationTimer(), TimerBase::Timer(), and TimerBase::WidgetFadeTimer().
OnParseConfig()
void AIBehaviourHL::OnParseConfig ()
ParseAlertLevel()
proto native void AIBehaviourHL::ParseAlertLevel (string name)
ParseBehaviourSlot()
proto native void AIBehaviourHL::ParseBehaviourSlot (string name)
ReadParamValue()
proto native float AIBehaviourHL::ReadParamValue (string paramName, float defValue)
RegAIBehaviour()
static proto void RegAIBehaviour (string behname, typename behClass , typename behClassData) static
SetNextBehaviour()
proto native void SetNextBehaviour (int BehaviourCrc)
Referenced by AIBehaviourHLZombie2::OnInit().
Simulate()
void Simulate (float timeDelta)
Definition at line 53 of file aibehaviour.c.
    {
        //time = time + timeDelta;
        //Print("A2");
    }
SwitchToNextBehaviour()
proto native void SwitchToNextBehaviour ()
Referenced by AIBehaviourHLZombie2::OnInit().
~AIBehaviourHL()
private void ~AIBehaviourHL ()
Definition at line 45 of file aibehaviour.c.
{}
~AIBehaviourHLData()
private void AIBehaviourHL::~AIBehaviourHLData ()
Definition at line 46 of file aibehaviour.c.
{};
Variable Documentation
AIBehaviourHL
class AIBehaviourHLData AIBehaviourHL
Definition at line 1 of file aibehaviour.c.
{}