DayzKode: P:/scripts/4_world/DayZ/entities/itembase/magazine/ammunitionpiles.c File Reference
ammunitionpiles.c File Reference
Classes
class Ammo_12gaPellets
class Ammo_12gaSlug
class Ammo_22
class Ammo_308Win
class Ammo_308WinTracer
class Ammo_357
class Ammo_380
class Ammo_40mm_Base
class Ammo_40mm_Explosive
class Ammo_40mm_Smoke_Black
class Ammo_40mm_Smoke_ColorBase
class Ammo_40mm_Smoke_Green
class Ammo_40mm_Smoke_White
class Ammo_45ACP
class Ammo_545x39
class Ammo_545x39Tracer
class Ammo_556x45
class Ammo_556x45Tracer
class Ammo_762x39
class Ammo_762x39Tracer
class Ammo_762x54
class Ammo_762x54Tracer
class Ammo_9x19
class Ammo_9x39
class Ammo_ArrowBolt
class Ammo_ArrowBoned
class Ammo_ArrowComposite
class Ammo_ArrowPrimitive
class Ammo_DartSyringe
class Ammo_Flare
class Ammo_GrenadeM4
class Ammo_LAW_HE
class Ammo_RPG7_AP
class Ammo_RPG7_HE
class Ammo_SharpStick
class Ammunition_Base
ammo pile base
Functions
override void EEKilled (Object killer)
Ammo_40mm_Explosive Ammo_40mm_Base OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
override void OnDamageDestroyed (int oldLevel)
override bool ShootsExplosiveAmmo ()
Variables
Ammo_40mm_Smoke_ColorBase Ammo_40mm_Smoke_ColorBase
Function Documentation
EEKilled()
override void OnActivatedByItem::EEKilled (Object killer)
Definition at line 111 of file ammunitionpiles.c.
    {
        super.OnDamageDestroyed(oldLevel);
        #ifndef SERVER
References ClearFlags().
OnActivatedByItem()
Ammo_40mm_Explosive Ammo_40mm_Base OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
Definition at line 1 of file ammunitionpiles.c.
    {
        if (GetGame().IsServer())
        {
            GetGame().CreateObject("ContaminatedArea_Local", item.GetPosition());
        }
    }
OnDamageDestroyed()
override void OnActivatedByItem::OnDamageDestroyed (int oldLevel)
Definition at line 118 of file ammunitionpiles.c.
                               : Ammo_40mm_Base
ShootsExplosiveAmmo()
override bool OnActivatedByItem::ShootsExplosiveAmmo ()
Definition at line 98 of file ammunitionpiles.c.
    {
        if (GetGame().IsServer())
        {
            GetGame().CreateObject("ContaminatedArea_Local", item.GetPosition());
References CGame::CreateObject(), and GetGame().
Variable Documentation
Ammo_40mm_Smoke_ColorBase
Ammo_40mm_Smoke_ColorBase Ammo_40mm_Smoke_ColorBase