DayzKode: P:/scripts/4_world/DayZ/classes/areadamage/areadamagenew/damagecomponents/areadamagecomponent.c File Reference
areadamagecomponent.c File Reference
Classes
class AreaDamageComponentData
Functions
ref array< typename > m_DamageableTypes void AreaDamageComponent (AreaDamageManager parent)
private bool EvaluateDamageInternal (TriggerInsider insider, float damageCoef)
protected AreaDamageComponentData GetAreaDamageComponentData (Object object)
override bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
override void PostDamageActions ()
override void PreDamageActions ()
protected bool ShouldDamage (Object object)
Variables
string m_AmmoName
int m_DamageType
class AreaDamageComponentData m_Parent
Function Documentation
AreaDamageComponent()
ref array< typename > m_DamageableTypes void AreaDamageComponent (AreaDamageManager parent)
Definition at line 16 of file areadamagecomponent.c.
    {
        m_Parent = parent;
        m_DamageType        = DT_CUSTOM;
        m_AmmoName          = "MeleeDamage";
        m_DamageableTypes   = new array<typename>;
        m_DamageableTypes.Insert(DayZPlayer);
    }
References AreaDamageComponent(), m_AmmoName, m_DamageType, and m_Parent.
Referenced by AreaDamageComponent(), AreaDamageManager(), and SetDamageComponentType().
EvaluateDamageInternal()
private bool EvaluateDamageInternal (TriggerInsider insider, float damageCoef)
Definition at line 56 of file areadamagecomponent.c.
    {
        PreDamageActions();
        AreaDamageTriggerInsider dInsider;
        if ( CastTo( dInsider, insider ) )
            dInsider.lastDamaged = g_Game.GetTickTime();
        Object object = insider.GetObject();
        AreaDamageComponentData data = GetAreaDamageComponentData(object);
        object.ProcessDirectDamage(m_DamageType, m_Parent.GetParentObject(), data.Hitzone, m_AmmoName, data.Modelpos, damageCoef);
        PostDamageActions();
        return true;
    }
References g_Game, GetAreaDamageComponentData(), TriggerInsider::GetObject(), AreaDamageComponentData::Hitzone, AreaDamageTriggerInsider::lastDamaged, m_AmmoName, m_DamageType, m_Parent, AreaDamageComponentData::Modelpos, AreaDamageEvents::PostDamageActions(), and AreaDamageEvents::PreDamageActions().
Referenced by OnEvaluateDamage().
GetAreaDamageComponentData()
protected AreaDamageComponentData GetAreaDamageComponentData (Object object)
Definition at line 51 of file areadamagecomponent.c.
    {
        return new AreaDamageComponentData;
    }
Referenced by EvaluateDamageInternal().
OnEvaluateDamage()
override bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
Definition at line 27 of file areadamagecomponent.c.
    {
        // No need to damage if the coef is 0!
        if ( ShouldDamage(insider.GetObject()) && damageCoef > 0 )
            return EvaluateDamageInternal(insider, damageCoef);
        return false;
    }
References EvaluateDamageInternal(), TriggerInsider::GetObject(), and ShouldDamage().
PostDamageActions()
override void PostDamageActions ()
Definition at line 41 of file areadamagecomponent.c.
    {
        m_Parent.PostDamageActions();
    }
References m_Parent.
PreDamageActions()
override void PreDamageActions ()
Definition at line 36 of file areadamagecomponent.c.
    {
        m_Parent.PreDamageActions();
    }
References m_Parent.
ShouldDamage()
protected bool ShouldDamage (Object object)
Definition at line 46 of file areadamagecomponent.c.
    {
        return object && object.IsAlive() && object.IsAnyInherited( m_DamageableTypes );
    }
Referenced by OnEvaluateDamage().
Variable Documentation
m_AmmoName
string m_AmmoName
Definition at line 12 of file areadamagecomponent.c.
Referenced by AreaDamageComponent(), and EvaluateDamageInternal().
m_DamageType
int m_DamageType
Definition at line 11 of file areadamagecomponent.c.
Referenced by AreaDamageComponent(), and EvaluateDamageInternal().
m_Parent
class AreaDamageComponentData m_Parent