DayzKode: P:/scripts/4_world/DayZ/classes/areadamage/areadamagenew/areadamagemanager.c File Reference
areadamagemanager.c File Reference
Classes
class AreaDamageComponentTypes
Functions
void AreaDamageManager (EntityAI parent)
void Destroy ()
destroy damage trigger
void SetDamageComponentType (int type)
void Spawn ()
spawn damage trigger
void ~AreaDamageManager ()
AreaDamageEvents Implementation
Implementation for handling AreaDamageEvents Pass them on to the AreaDamageComponent Calling of the events that are the same in TriggerEvents will come from AreaDamageTriggerBase
override void OnEnterBeginEvent (TriggerInsider insider)
Called when an object enters the trigger.
override void OnEnterClientEvent (TriggerInsider insider)
override void OnEnterEndEvent (TriggerInsider insider)
override void OnEnterServerEvent (TriggerInsider insider)
override bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
Tell the AreaDamageComponent to calculate and apply the damage to the Object.
override void OnLeaveBeginEvent (TriggerInsider insider)
Called when an object leaves the trigger.
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnLeaveEndEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
Called in the update loop.
override void OnStayClientEvent (TriggerInsider insider, float deltaTime)
override void OnStayEndEvent (TriggerInsider insider, float deltaTime)
override void OnStayFinishBeginEvent ()
Called at the end of an update loop.
override void OnStayFinishClientEvent ()
override void OnStayFinishEndEvent ()
override void OnStayFinishServerEvent ()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
override void OnStayStartBeginEvent (int nrOfInsiders)
Called at the beginning of an update loop.
override void OnStayStartClientEvent (int nrOfInsiders)
override void OnStayStartEndEvent (int nrOfInsiders)
override void OnStayStartServerEvent (int nrOfInsiders)
override void OnTriggerCreated ()
override void OnTriggerDestroyed ()
Called when a trigger is destroyed.
override void PostDamageActions ()
Usually called from AreaDamageComponent.
override void PreDamageActions ()
Usually called from AreaDamageComponent.
protected float CalculateDamageScale (TriggerInsider insider, float deltaTime)
Helper for calculating damageCoeff when using OnEvaluateDamageEx.
bool OnEvaluateDamageEx (TriggerInsider insider, float deltaTime)
void AddDamageableType (typename damageableType)
string GetAmmoName ()
array< typename > GetDamageableTypes ()
int GetDamageType ()
void GetExtents (out vector mins, out vector maxs)
vector GetOrientation ()
Retrieve orientation (yaw, pitch, roll) in degrees
EntityAI GetParentObject ()
vector GetPosition ()
Retrieve position.
AreaDamageTriggerBase GetTrigger ()
void GetWorldExtents (out vector mins, out vector maxs)
void RemoveAddDamageableType (typename damageableType)
void SetAmmoName (string ammo_name)
void SetAreaOrientation (vector orientation)
void SetAreaPosition (vector position)
void SetDamageableTypes (array< typename > damageableTypes)
void SetDamageType (int pDamageType)
void SetDeferDuration (float time)
void SetExtents (vector mins, vector maxs)
void SetHitZones (array< string > hitzones)
void SetLoopInterval (float time)
void SetParentObject (EntityAI obj)
void SetRaycastSources (array< string > raycast_sources)
void SetRaycastSourcesVector (array< vector > raycast_sources)
protected void CreateDamageTrigger ()
protected bool CreateDamageTriggerEx ()
protected void DestroyDamageTrigger ()
protected bool DestroyDamageTriggerEx ()
Variables
protected AreaDamageTriggerBase m_AreaDamageTrigger
protected vector m_AreaOrientation
protected vector m_AreaPosition
protected ref AreaDamageComponent m_DamageComponent
protected vector m_ExtentMax
protected vector m_ExtentMin
class AreaDamageComponentTypes m_ParentObject
protected string m_TriggerBaseClass
Function Documentation
AddDamageableType()
void AddDamageableType (typename damageableType)
Definition at line 320 of file areadamagemanager.c.
    {
        if (m_DamageComponent.m_DamageableTypes.Find(damageableType) != -1)
            m_DamageComponent.m_DamageableTypes.Insert(damageableType);
    }
References m_DamageComponent.
AreaDamageManager()
void AreaDamageManager (EntityAI parent)
Definition at line 22 of file areadamagemanager.c.
    {
        m_ParentObject      = parent;
        m_DamageComponent   = new AreaDamageComponent(this);
        m_ExtentMin         = vector.Zero;
        m_ExtentMax         = vector.Zero;
        m_AreaPosition      = parent.GetPosition();
        m_AreaOrientation   = parent.GetOrientation();
        m_TriggerBaseClass  = "AreaDamageTriggerBase";
    }
References AreaDamageComponent(), AreaDamageManager(), m_AreaOrientation, m_AreaPosition, m_DamageComponent, m_ExtentMax, m_ExtentMin, m_ParentObject, m_TriggerBaseClass, and vector::Zero.
Referenced by AreaDamageManager().
CalculateDamageScale()
protected float CalculateDamageScale (TriggerInsider insider, float deltaTime)
Helper for calculating damageCoeff when using OnEvaluateDamageEx.
Definition at line 224 of file areadamagemanager.c.
    {
        return deltaTime;
    }
Referenced by OnEvaluateDamageEx().
CreateDamageTrigger()
protected void CreateDamageTrigger ()
Definition at line 397 of file areadamagemanager.c.
    {
        CreateDamageTriggerEx();
    }
References CreateDamageTriggerEx().
CreateDamageTriggerEx()
protected bool CreateDamageTriggerEx ()
create damage trigger with basic set of params
Definition at line 377 of file areadamagemanager.c.
    {
        int flags;
        if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
            flags = ECE_CREATEPHYSICS;
        else
            flags = ECE_LOCAL;
        if (Class.CastTo(m_AreaDamageTrigger, GetGame().CreateObjectEx( m_TriggerBaseClass, m_AreaPosition, flags )))
        {
            m_AreaDamageTrigger.SetOrientation( m_AreaOrientation );
            m_AreaDamageTrigger.SetExtents( m_ExtentMin, m_ExtentMax );
            m_AreaDamageTrigger.SetAreaDamageManager(this);
            return true;
        }
        return false;
    }
References Class::CastTo(), ECE_CREATEPHYSICS, ECE_LOCAL, GetGame(), m_AreaDamageTrigger, m_AreaOrientation, m_AreaPosition, m_ExtentMax, m_ExtentMin, m_TriggerBaseClass, AreaDamageTriggerBase::SetAreaDamageManager(), and AreaDamageTriggerBase::SetExtents().
Referenced by CreateDamageTrigger(), and Spawn().
DestroyDamageTrigger()
protected void DestroyDamageTrigger ()
Definition at line 418 of file areadamagemanager.c.
    {
        DestroyDamageTriggerEx();
    }
References DestroyDamageTriggerEx().
DestroyDamageTriggerEx()
protected bool DestroyDamageTriggerEx ()
destroys damage trigger
Definition at line 406 of file areadamagemanager.c.
    {
        if ( GetGame() && m_AreaDamageTrigger ) // It's necesarry to check if the game exists. Otherwise a crash occurs while quitting.
        {
            GetGame().ObjectDelete( m_AreaDamageTrigger );
            m_AreaDamageTrigger = null;
            return true;
        }
        return false;
    }
References GetGame(), m_AreaDamageTrigger, and CGame::ObjectDelete().
Referenced by Destroy(), and DestroyDamageTrigger().
GetAmmoName()
string GetAmmoName ()
Definition at line 260 of file areadamagemanager.c.
    {
        return m_DamageComponent.m_AmmoName;
    }
References m_DamageComponent.
GetDamageableTypes()
array< typename > GetDamageableTypes ()
Definition at line 315 of file areadamagemanager.c.
    {
        return m_DamageComponent.m_DamageableTypes;
    }
References m_DamageComponent.
GetDamageType()
int GetDamageType ()
Definition at line 269 of file areadamagemanager.c.
    {
        return m_DamageComponent.m_DamageType;
    }
References m_DamageComponent.
GetExtents()
void GetExtents (out vector mins, out vector maxs)
Definition at line 243 of file areadamagemanager.c.
    {
        mins = m_ExtentMin;
        maxs = m_ExtentMax;
    }
References m_ExtentMax, and m_ExtentMin.
Referenced by GetWorldExtents().
GetOrientation()
vector GetOrientation ()
Retrieve orientation (yaw, pitch, roll) in degrees
Returns
vector of yaw, pitch and roll angles (x = yaw, y = pitch, z = roll)
Definition at line 306 of file areadamagemanager.c.
    {
        return m_AreaOrientation;
    }
References m_AreaOrientation.
Referenced by FireplaceBase::AfterStoreLoad(), TrapSpawnBase::AlignCatch(), ItemBase::CreateAreaDamage(), CreateCollisionTrigger(), CreateTrigger(), TrapBase::CreateTrigger(), ItemBase::DoMeasurement(), DayZSpectator::EOnFrame(), DayZInfected::HandleOrientation(), HandleVisualEffects(), IsColliding(), IsCollidingEx(), LateInit(), FireplaceBase::OnIgnitedThis(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), BaseBuildingBase::PerformRoofCheckForBase(), ManBase::PhysicalPredictiveDropItem(), SetParticleOrientation(), UndergroundTriggerCarrierBase::SpawnTrigger(), and FlammableBase::TryTransformIntoStick().
GetParentObject()
EntityAI GetParentObject ()
Definition at line 278 of file areadamagemanager.c.
    {
        return m_ParentObject;
    }
References m_ParentObject.
GetPosition()
vector GetPosition ()
Retrieve position.
Retrieve position.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The world position of the Effect
Definition at line 292 of file areadamagemanager.c.
    {
        return m_AreaPosition;
    }
References m_AreaPosition.
GetTrigger()
AreaDamageTriggerBase GetTrigger ()
Definition at line 368 of file areadamagemanager.c.
    {
        return m_AreaDamageTrigger;
    }
References m_AreaDamageTrigger.
GetWorldExtents()
void GetWorldExtents (out vector mins, out vector maxs)
Definition at line 248 of file areadamagemanager.c.
    {
        GetExtents(mins, maxs);
        mins + m_AreaPosition;
        maxs + m_AreaPosition;
    }
References GetExtents(), and m_AreaPosition.
OnEnterBeginEvent()
override void OnEnterBeginEvent (TriggerInsider insider)
Called when an object enters the trigger.
Definition at line 103 of file areadamagemanager.c.
    {
        m_DamageComponent.OnEnterBeginEvent(insider);
    }
References m_DamageComponent.
OnEnterClientEvent()
override void OnEnterClientEvent (TriggerInsider insider)
Definition at line 111 of file areadamagemanager.c.
    {
        m_DamageComponent.OnEnterClientEvent(insider);
    }
References m_DamageComponent.
OnEnterEndEvent()
override void OnEnterEndEvent (TriggerInsider insider)
Definition at line 115 of file areadamagemanager.c.
    {
        m_DamageComponent.OnEnterEndEvent(insider);
    }
References m_DamageComponent.
OnEnterServerEvent()
override protected void OnEnterServerEvent (TriggerInsider insider)
Definition at line 107 of file areadamagemanager.c.
    {
        m_DamageComponent.OnEnterServerEvent(insider);
    }
References m_DamageComponent.
OnEvaluateDamage()
override bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
Tell the AreaDamageComponent to calculate and apply the damage to the Object.
Definition at line 193 of file areadamagemanager.c.
    {
        return m_DamageComponent.OnEvaluateDamage(insider, damageCoef);
    }
References m_DamageComponent.
OnEvaluateDamageEx()
bool OnEvaluateDamageEx (TriggerInsider insider, float deltaTime)
Some event extensions
Alternative OnEvaluateDamage, using CalculateDamageScale
Definition at line 218 of file areadamagemanager.c.
    {
        return OnEvaluateDamage( insider, CalculateDamageScale( insider, deltaTime ) );
    }
References CalculateDamageScale(), and AreaDamageEvents::OnEvaluateDamage().
Referenced by AreaDamageLooped::OnEnterServerEvent(), AreaDamageOnce::OnEnterServerEvent(), AreaDamageLooped::OnStayServerEvent(), and OnStayServerEvent().
OnLeaveBeginEvent()
override void OnLeaveBeginEvent (TriggerInsider insider)
Called when an object leaves the trigger.
Definition at line 175 of file areadamagemanager.c.
    {
        m_DamageComponent.OnLeaveBeginEvent(insider);
    }
References m_DamageComponent.
OnLeaveClientEvent()
override void OnLeaveClientEvent (TriggerInsider insider)
Definition at line 183 of file areadamagemanager.c.
    {
        m_DamageComponent.OnLeaveClientEvent(insider);
    }
References m_DamageComponent.
OnLeaveEndEvent()
override void OnLeaveEndEvent (TriggerInsider insider)
Definition at line 187 of file areadamagemanager.c.
    {
        m_DamageComponent.OnLeaveEndEvent(insider);
    }
References m_DamageComponent.
OnLeaveServerEvent()
override void OnLeaveServerEvent (TriggerInsider insider)
Definition at line 179 of file areadamagemanager.c.
    {
        m_DamageComponent.OnLeaveServerEvent(insider);
    }
References m_DamageComponent.
OnStayBeginEvent()
override void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
Called in the update loop.
Definition at line 139 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayBeginEvent(insider, deltaTime);
    }
References m_DamageComponent.
OnStayClientEvent()
override void OnStayClientEvent (TriggerInsider insider, float deltaTime)
Definition at line 147 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayClientEvent(insider, deltaTime);
    }
References m_DamageComponent.
OnStayEndEvent()
override void OnStayEndEvent (TriggerInsider insider, float deltaTime)
Definition at line 151 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayEndEvent(insider, deltaTime);
    }
References m_DamageComponent.
OnStayFinishBeginEvent()
override void OnStayFinishBeginEvent ()
Called at the end of an update loop.
Definition at line 157 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayFinishBeginEvent();
    }
References m_DamageComponent.
OnStayFinishClientEvent()
override void OnStayFinishClientEvent ()
Definition at line 165 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayFinishClientEvent();
    }
References m_DamageComponent.
OnStayFinishEndEvent()
override void OnStayFinishEndEvent ()
Definition at line 169 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayFinishEndEvent();
    }
References m_DamageComponent.
OnStayFinishServerEvent()
override void OnStayFinishServerEvent ()
Definition at line 161 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayFinishServerEvent();
    }
References m_DamageComponent.
OnStayServerEvent()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
Definition at line 143 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayServerEvent(insider, deltaTime);
    }
References m_DamageComponent.
OnStayStartBeginEvent()
override void OnStayStartBeginEvent (int nrOfInsiders)
Called at the beginning of an update loop.
Definition at line 121 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayStartBeginEvent(nrOfInsiders);
    }
References m_DamageComponent.
OnStayStartClientEvent()
override void OnStayStartClientEvent (int nrOfInsiders)
Definition at line 129 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayStartClientEvent(nrOfInsiders);
    }
References m_DamageComponent.
OnStayStartEndEvent()
override void OnStayStartEndEvent (int nrOfInsiders)
Definition at line 133 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayStartEndEvent(nrOfInsiders);
    }
References m_DamageComponent.
OnStayStartServerEvent()
override void OnStayStartServerEvent (int nrOfInsiders)
Definition at line 125 of file areadamagemanager.c.
    {
        m_DamageComponent.OnStayStartServerEvent(nrOfInsiders);
    }
References m_DamageComponent.
OnTriggerCreated()
override void OnTriggerCreated ()
Called when a trigger is created
Definition at line 91 of file areadamagemanager.c.
    {
        m_DamageComponent.OnTriggerCreated();
    }
References m_DamageComponent.
OnTriggerDestroyed()
override void OnTriggerDestroyed ()
Called when a trigger is destroyed.
Definition at line 97 of file areadamagemanager.c.
    {
        m_DamageComponent.OnTriggerDestroyed();
    }
References m_DamageComponent.
PostDamageActions()
override void PostDamageActions ()
Usually called from AreaDamageComponent.
Definition at line 206 of file areadamagemanager.c.
    {
        if ( m_ParentObject )
            m_ParentObject.PostAreaDamageActions();
    }
References m_ParentObject.
Referenced by AreaDamageBase::EvaluateDamage_Common().
PreDamageActions()
override void PreDamageActions ()
Usually called from AreaDamageComponent.
Definition at line 199 of file areadamagemanager.c.
    {
        if ( m_ParentObject )
            m_ParentObject.PreAreaDamageActions();
    }
References m_ParentObject.
RemoveAddDamageableType()
void RemoveAddDamageableType (typename damageableType)
Definition at line 326 of file areadamagemanager.c.
    {
        m_DamageComponent.m_DamageableTypes.RemoveItem(damageableType);
    }
References m_DamageComponent.
SetAmmoName()
void SetAmmoName (string ammo_name)
Definition at line 256 of file areadamagemanager.c.
    {
        m_DamageComponent.m_AmmoName = ammo_name;
    }
References m_DamageComponent.
SetAreaOrientation()
void SetAreaOrientation (vector orientation)
Definition at line 297 of file areadamagemanager.c.
    {
        m_AreaOrientation = orientation;
        if ( m_AreaDamageTrigger )
        {
            m_AreaDamageTrigger.SetOrientation(m_AreaOrientation);
        }
    }
References m_AreaDamageTrigger, and m_AreaOrientation.
SetAreaPosition()
void SetAreaPosition (vector position)
Definition at line 283 of file areadamagemanager.c.
    {
        m_AreaPosition = position;
        if ( m_AreaDamageTrigger )
        {
            m_AreaDamageTrigger.SetPosition(m_AreaPosition);
        }
    }
References m_AreaDamageTrigger, and m_AreaPosition.
SetDamageableTypes()
void SetDamageableTypes (array< typename > damageableTypes)
Definition at line 311 of file areadamagemanager.c.
    {
        m_DamageComponent.m_DamageableTypes = damageableTypes;
    }
References m_DamageComponent.
SetDamageComponentType()
void SetDamageComponentType (int type)
Definition at line 41 of file areadamagemanager.c.
    {
        switch (type)
        {
            case AreaDamageComponentTypes.BASE:
            {
                m_DamageComponent = new AreaDamageComponent(this);
                break;
            }
            case AreaDamageComponentTypes.HITZONE:
            {
                m_DamageComponent = new AreaDamageComponentRandomHitzone(this);
                break;
            }
            case AreaDamageComponentTypes.RAYCASTED:
            {
                m_DamageComponent = new AreaDamageComponentRaycasted(this);
                break;
            }
            default:
            {
                Error(string.Format("[ERROR] :: [AreaDamageManager] :: Unknown DamageComponentType: %1", type));
                break;
            }
        }
    }
References AreaDamageComponent(), AreaDamageComponentTypes::BASE, Error(), AreaDamageComponentTypes::HITZONE, m_DamageComponent, and AreaDamageComponentTypes::RAYCASTED.
SetDamageType()
void SetDamageType (int pDamageType)
Definition at line 265 of file areadamagemanager.c.
    {
        m_DamageComponent.m_DamageType = pDamageType;
    }
References m_DamageComponent.
SetDeferDuration()
void SetDeferDuration (float time)
Definition at line 336 of file areadamagemanager.c.
    {
        Error("SetDeferDuration not implemented - usable in Deferred area damage objects only");
    }
References Error().
SetExtents()
void SetExtents (vector mins, vector maxs)
script configuration
Definition at line 233 of file areadamagemanager.c.
    {
        m_ExtentMin = mins;
        m_ExtentMax = maxs;
        if ( m_AreaDamageTrigger )
        {
            m_AreaDamageTrigger.SetExtents(m_ExtentMin, m_ExtentMax);
        }
    }
References m_AreaDamageTrigger, m_ExtentMax, m_ExtentMin, and AreaDamageTriggerBase::SetExtents().
SetHitZones()
void SetHitZones (array< string > hitzones)
Definition at line 341 of file areadamagemanager.c.
    {
        AreaDamageComponentRandomHitzone adc;
        if ( CastTo( adc, m_DamageComponent ) )
            adc.SetHitZones( hitzones );
        else
            Error("SetHitZones not implemented - override for non raycasted versions of area damage objects only");
    }
References Error(), m_DamageComponent, and AreaDamageComponentRandomHitzone::SetHitZones().
SetLoopInterval()
void SetLoopInterval (float time)
Definition at line 331 of file areadamagemanager.c.
    {
        Error("SetLoopInterval not implemented - usable in Regular(looped) area damage objects only");
    }
References Error().
SetParentObject()
void SetParentObject (EntityAI obj)
Definition at line 274 of file areadamagemanager.c.
    {
        m_ParentObject = obj;
    }
References m_ParentObject.
SetRaycastSources()
void SetRaycastSources (array< string > raycast_sources)
Definition at line 350 of file areadamagemanager.c.
    {
        AreaDamageComponentRaycasted adc;
        if ( CastTo( adc, m_DamageComponent ) )
            adc.SetRaycastSources( raycast_sources );
        else
            Error("SetRaycastSources not implemented - override for raycasted versions of area damage objects only");
    }
References Error(), m_DamageComponent, and AreaDamageComponentRaycasted::SetRaycastSources().
SetRaycastSourcesVector()
void SetRaycastSourcesVector (array< vector > raycast_sources)
Definition at line 359 of file areadamagemanager.c.
    {
        AreaDamageComponentRaycasted adc;
        if ( CastTo( adc, m_DamageComponent ) )
            adc.SetRaycastSourcesVector( raycast_sources );
        else
            Error("SetRaycastSources not implemented - override for raycasted versions of area damage objects only");
    }
References Error(), m_DamageComponent, and AreaDamageComponentRaycasted::SetRaycastSourcesVector().
Spawn()
void Spawn ()
spawn damage trigger
Definition at line 70 of file areadamagemanager.c.
    {
        if ( CreateDamageTriggerEx() )
            OnTriggerCreated();
    }
References CreateDamageTriggerEx(), and AreaDamageEvents::OnTriggerCreated().
Referenced by ActionConstructor::ConstructActions(), EmoteConstructor::ConstructEmotes(), and EvaluateImpactEffect().
~AreaDamageManager()
void ~AreaDamageManager ()
Definition at line 36 of file areadamagemanager.c.
    {
        Destroy();
    }
References Destroy().
Variable Documentation
m_AreaDamageTrigger
protected AreaDamageTriggerBase m_AreaDamageTrigger
Definition at line 11 of file areadamagemanager.c.
Referenced by CreateDamageTriggerEx(), DestroyDamageTriggerEx(), AreaDamageBase::GetRaycastedHitZone(), GetTrigger(), SetAreaOrientation(), SetAreaPosition(), and SetExtents().
m_AreaOrientation
protected vector m_AreaOrientation
Definition at line 18 of file areadamagemanager.c.
Referenced by AreaDamageManager(), CreateDamageTriggerEx(), GetOrientation(), and SetAreaOrientation().
m_AreaPosition
protected vector m_AreaPosition
Definition at line 17 of file areadamagemanager.c.
Referenced by AreaDamageManager(), CreateDamageTriggerEx(), GetPosition(), GetWorldExtents(), and SetAreaPosition().
m_DamageComponent
protected ref AreaDamageComponent m_DamageComponent
Definition at line 13 of file areadamagemanager.c.
Referenced by AddDamageableType(), AreaDamageManager(), GetAmmoName(), GetDamageableTypes(), GetDamageType(), OnEnterBeginEvent(), OnEnterClientEvent(), OnEnterEndEvent(), OnEnterServerEvent(), OnEvaluateDamage(), OnLeaveBeginEvent(), OnLeaveClientEvent(), OnLeaveEndEvent(), OnLeaveServerEvent(), OnStayBeginEvent(), OnStayClientEvent(), OnStayEndEvent(), OnStayFinishBeginEvent(), OnStayFinishClientEvent(), OnStayFinishEndEvent(), OnStayFinishServerEvent(), OnStayServerEvent(), OnStayStartBeginEvent(), OnStayStartClientEvent(), OnStayStartEndEvent(), OnStayStartServerEvent(), OnTriggerCreated(), OnTriggerDestroyed(), RemoveAddDamageableType(), SetAmmoName(), SetDamageableTypes(), SetDamageComponentType(), SetDamageType(), SetHitZones(), SetRaycastSources(), and SetRaycastSourcesVector().
m_ExtentMax
protected vector m_ExtentMax
Definition at line 16 of file areadamagemanager.c.
Referenced by AreaDamageManager(), AreaDamageTriggerBase::AreaDamageTrigger(), CreateDamageTriggerEx(), GetExtents(), SetExtents(), and AreaDamageTriggerBase::SetExtents().
m_ExtentMin
protected vector m_ExtentMin
Definition at line 15 of file areadamagemanager.c.
Referenced by AreaDamageManager(), AreaDamageTriggerBase::AreaDamageTrigger(), CreateDamageTriggerEx(), GetExtents(), SetExtents(), and AreaDamageTriggerBase::SetExtents().
m_ParentObject
class AreaDamageComponentTypes m_ParentObject
m_TriggerBaseClass
protected string m_TriggerBaseClass
Definition at line 20 of file areadamagemanager.c.
Referenced by AreaDamageBase::AreaDamageBase(), AreaDamageManager(), and CreateDamageTriggerEx().