DayzKode: P:/scripts/4_world/DayZ/entities/itembase/basebuildingbase.c File Reference
basebuildingbase.c File Reference
Classes
class ItemBase
Functions
override void AfterStoreLoad ()
void BaseBuildingBase ()
class BaseBuildingBase extends ItemBase bsbDebugPrint (string s)
void bsbDebugSpam (string s)
void CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
bool CanFoldBaseBuildingObject ()
override bool CanObstruct ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanUseConstruction ()
override bool CanUseConstructionBuild ()
void CheckForHybridAttachments (EntityAI item, string slot_name)
protected bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
protected bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
void ConstructionInit ()
void CreateAreaDamage (string slot_name, float rotation_angle=0)
ItemBase CreateConstructionKit ()
void CreateConstructionKitInHands (notnull PlayerBase player)
protected void DebugCustomState ()
void DestroyAreaDamage (string slot_name)
void DestroyConstruction ()
void DestroyConstructionKit (ItemBase construction_kit)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEOnAfterLoad ()
ItemBase FoldBaseBuildingObject ()
void FullyBuild ()
void GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
protected string GetBuildSoundByMaterial (string part_name)
Construction GetConstruction ()
protected string GetConstructionKitType ()
protected ConstructionPart GetConstructionPartById (int id)
override int GetDamageSystemVersionChange ()
protected string GetDismantleSoundByMaterial (string part_name)
override int GetHideIconMask ()
override string GetInvulnerabilityTypeString ()
protected vector GetKitSpawnPosition ()
bool HasAttachmentsBesidesBase ()
bool HasBase ()
bool HasProperDistance (string selection, PlayerBase player)
override bool IgnoreOutOfReachCondition ()
void InitBaseState ()
void InitVisuals ()
protected bool IsAttachmentSlotLocked (EntityAI attachment)
protected bool IsAttachmentSlotLocked (string slot_name)
override bool IsDeployable ()
bool IsFacingCamera (string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsIgnoredByConstruction ()
bool IsOpened ()
bool IsPartBuildInSyncData (int part_id)
override bool IsPlayerInside (PlayerBase player, string selection)
bool MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
override void OnDebugSpawn ()
array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
void OnPartBuiltClient (string part_name, int action_id)
void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
void OnPartDestroyedClient (string part_name, int action_id)
void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void OnPartDismantledClient (string part_name, int action_id)
void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
protected void OnSetSlotLock (int slotId, bool locked, bool was_locked)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
protected void OnSynchronizedClient ()
override void OnVariablesSynchronized ()
bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
protected void RegisterActionForSync (int part_id, int action_id)
void RegisterPartForSync (int part_id)
protected void ResetActionSyncData ()
protected void SetActionFromSyncData ()
override void SetActions ()
void SetBaseState (bool has_base)
void SetPartFromSyncData (ConstructionPart part)
void SetPartsAfterStoreLoad ()
void SetPartsFromSyncData ()
override bool ShowZonesHealth ()
protected void SoundBuildStart (string part_name)
protected void SoundDestroyStart (string part_name)
protected void SoundDismantleStart (string part_name)
void SynchronizeBaseState ()
void UnregisterPartForSync (int part_id)
void UpdateAttachmentPhysics (string slot_name, bool is_locked)
void UpdateAttachmentVisuals (string slot_name, bool is_locked)
protected void UpdateNavmesh ()
void UpdatePhysics ()
void UpdateVisuals ()
Variables
const string ANIMATION_DEPLOYED = "Deployed"
ref Construction m_Construction
float m_ConstructionKitHealth
ref map< string, ref AreaDamageManager > m_DamageTriggers
bool m_HasBase = false
ref array< string > m_HybridAttachments
int m_InteractedPartId
ref array< string > m_Mountables
int m_PerformedActionId
protected EffectSound m_Sound
int m_SyncParts01
int m_SyncParts02
int m_SyncParts03
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet"
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet"
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet"
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet"
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet"
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet"
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet"
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet"
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet"
Function Documentation
AfterStoreLoad()
override void bsbDebugPrint::AfterStoreLoad ()
Definition at line 1650 of file basebuildingbase.c.
BaseBuildingBase()
void bsbDebugPrint::BaseBuildingBase ()
Definition at line 1258 of file basebuildingbase.c.
bsbDebugPrint()
class BaseBuildingBase extends ItemBase bsbDebugPrint (string s)
Definition at line 2 of file basebuildingbase.c.
{
    //Print("" + s); // comment/uncomment to hide/see debug logs
}
Referenced by AddToConstructedParts(), BaseBuildingBase::AfterStoreLoad(), BuildPartServer(), DestroyConnectedParts(), ItemBase::DestroyConstruction(), DestroyMaterialsServer(), DestroyPartServer(), DismantlePartServer(), DropNonUsableMaterialsServer(), HideConstructionPart(), InitBaseState(), ItemBase::InitBaseState(), InitVisuals(), ItemBase::InitVisuals(), LockServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ItemBase::OnSetSlotLock(), BaseBuildingBase::OnStoreLoad(), BaseBuildingBase::OnStoreSave(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), RemoveFromConstructedParts(), ConstructionPart::SetBuiltState(), SetLockOnAttachedMaterials(), ItemBase::SetMountedState(), ItemBase::SetPartFromSyncData(), ConstructionPart::SetRequestBuiltState(), ShowConstructionPart(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), Synchronize(), UnlockServer(), ItemBase::UpdateAttachmentPhysics(), UpdateConstructionParts(), UpdatePhysics(), ItemBase::UpdatePhysics(), and UpdateVisuals().
bsbDebugSpam()
void bsbDebugSpam (string s)
Definition at line 1226 of file basebuildingbase.c.
{
    //Print("" + s); // comment/uncomment to hide/see debug logs
}
Referenced by ItemBase::SetPartFromSyncData().
CalcDamageAreaRotation()
void bsbDebugPrint::CalcDamageAreaRotation (float angle_deg, out vector center, out vector orientation)
Definition at line 2259 of file basebuildingbase.c.
Referenced by ItemBase::CreateAreaDamage().
CanFoldBaseBuildingObject()
bool bsbDebugPrint::CanFoldBaseBuildingObject ()
Definition at line 2192 of file basebuildingbase.c.
CanObstruct()
override bool bsbDebugPrint::CanObstruct ()
Definition at line 1292 of file basebuildingbase.c.
CanPutInCargo()
override bool bsbDebugPrint::CanPutInCargo (EntityAI parent)
Definition at line 2139 of file basebuildingbase.c.
CanPutIntoHands()
override bool bsbDebugPrint::CanPutIntoHands (EntityAI parent)
Definition at line 2150 of file basebuildingbase.c.
CanReceiveAttachment()
override bool bsbDebugPrint::CanReceiveAttachment (EntityAI attachment, int slotId)
Definition at line 2112 of file basebuildingbase.c.
CanRemoveFromCargo()
override bool bsbDebugPrint::CanRemoveFromCargo (EntityAI parent)
Definition at line 2144 of file basebuildingbase.c.
CanUseConstruction()
override bool bsbDebugPrint::CanUseConstruction ()
Definition at line 2041 of file basebuildingbase.c.
CanUseConstructionBuild()
override bool bsbDebugPrint::CanUseConstructionBuild ()
Definition at line 2046 of file basebuildingbase.c.
CheckForHybridAttachments()
void bsbDebugPrint::CheckForHybridAttachments (EntityAI item, string slot_name)
Definition at line 2353 of file basebuildingbase.c.
Referenced by ItemBase::EEItemAttached().
CheckLevelVerticalDistance()
protected bool bsbDebugPrint::CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
Definition at line 2089 of file basebuildingbase.c.
CheckMemoryPointVerticalDistance()
protected bool bsbDebugPrint::CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
Definition at line 2084 of file basebuildingbase.c.
CheckSlotVerticalDistance()
bool bsbDebugPrint::CheckSlotVerticalDistance (int slot_id, PlayerBase player)
Definition at line 2079 of file basebuildingbase.c.
ConstructionInit()
void bsbDebugPrint::ConstructionInit ()
Definition at line 2095 of file basebuildingbase.c.
Referenced by ItemBase::BaseBuildingBase().
CreateAreaDamage()
void bsbDebugPrint::CreateAreaDamage (string slot_name, float rotation_angle = 0)
Definition at line 2210 of file basebuildingbase.c.
CreateConstructionKit()
ItemBase bsbDebugPrint::CreateConstructionKit ()
Definition at line 1560 of file basebuildingbase.c.
Referenced by ItemBase::FoldBaseBuildingObject(), and ItemBase::OnPartBuiltServer().
CreateConstructionKitInHands()
void bsbDebugPrint::CreateConstructionKitInHands (notnull PlayerBase player)
Definition at line 1571 of file basebuildingbase.c.
DebugCustomState()
protected void bsbDebugPrint::DebugCustomState ()
Definition at line 2384 of file basebuildingbase.c.
Referenced by ItemBase::EEInit().
DestroyAreaDamage()
void bsbDebugPrint::DestroyAreaDamage (string slot_name)
Definition at line 2279 of file basebuildingbase.c.
DestroyConstruction()
void bsbDebugPrint::DestroyConstruction ()
Definition at line 1597 of file basebuildingbase.c.
Referenced by ItemBase::FoldBaseBuildingObject(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
DestroyConstructionKit()
void bsbDebugPrint::DestroyConstructionKit (ItemBase construction_kit)
Definition at line 1590 of file basebuildingbase.c.
EEHealthLevelChanged()
override void bsbDebugPrint::EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
Definition at line 1673 of file basebuildingbase.c.
EEInit()
override void bsbDebugPrint::EEInit ()
Definition at line 1717 of file basebuildingbase.c.
EEItemAttached()
override void bsbDebugPrint::EEItemAttached (EntityAI item, string slot_name)
Definition at line 1730 of file basebuildingbase.c.
EEItemDetached()
override void bsbDebugPrint::EEItemDetached (EntityAI item, string slot_name)
Definition at line 1739 of file basebuildingbase.c.
EEOnAfterLoad()
override void bsbDebugPrint::EEOnAfterLoad ()
Definition at line 1707 of file basebuildingbase.c.
FoldBaseBuildingObject()
ItemBase bsbDebugPrint::FoldBaseBuildingObject ()
Definition at line 2202 of file basebuildingbase.c.
FullyBuild()
void bsbDebugPrint::FullyBuild ()
Definition at line 2399 of file basebuildingbase.c.
Referenced by ItemBase::OnDebugSpawn().
GetAttachmentSlots()
void bsbDebugPrint::GetAttachmentSlots (EntityAI entity, out array< string > attachment_slots)
Definition at line 2070 of file basebuildingbase.c.
Referenced by ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
GetBuildSoundByMaterial()
protected string bsbDebugPrint::GetBuildSoundByMaterial (string part_name)
Definition at line 2320 of file basebuildingbase.c.
Referenced by ItemBase::SoundBuildStart().
GetConstruction()
Construction bsbDebugPrint::GetConstruction ()
Definition at line 2105 of file basebuildingbase.c.
Referenced by BaseBuildingBase::AfterStoreLoad(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), BaseBuildingBase::CanReceiveAttachment(), BaseBuildingBase::CheckGateState(), BaseBuildingBase::CheckSlotVerticalDistance(), ItemBase::ConstructionInit(), ItemBase::CreateAreaDamage(), ItemBase::EEHealthLevelChanged(), ItemBase::FullyBuild(), BaseBuildingBase::GateAttachmentConditions(), BaseBuildingBase::GateAttachmentsSanityCheck(), ItemBase::GetBuildSoundByMaterial(), ItemBase::GetConstructionPartById(), ItemBase::GetDismantleSoundByMaterial(), ItemBase::InitBaseState(), ItemBase::InitVisuals(), ItemBase::OnPartBuiltServer(), BaseBuildingBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), BaseBuildingBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), BaseBuildingBase::OnPartDismantledServer(), ItemBase::SetPartFromSyncData(), ItemBase::SetPartsAfterStoreLoad(), ItemBase::SetPartsFromSyncData(), ItemBase::UpdatePhysics(), ItemBase::UpdateVisuals(), and BaseBuildingBase::UpdateVisuals().
GetConstructionKitType()
protected string bsbDebugPrint::GetConstructionKitType ()
Definition at line 1585 of file basebuildingbase.c.
GetConstructionPartById()
protected ConstructionPart bsbDebugPrint::GetConstructionPartById (int id)
Definition at line 1518 of file basebuildingbase.c.
Referenced by ItemBase::SetActionFromSyncData().
GetDamageSystemVersionChange()
override int bsbDebugPrint::GetDamageSystemVersionChange ()
Definition at line 2365 of file basebuildingbase.c.
GetDismantleSoundByMaterial()
protected string bsbDebugPrint::GetDismantleSoundByMaterial (string part_name)
Definition at line 2336 of file basebuildingbase.c.
Referenced by ItemBase::SoundDestroyStart(), and ItemBase::SoundDismantleStart().
GetHideIconMask()
override int bsbDebugPrint::GetHideIconMask ()
Definition at line 1297 of file basebuildingbase.c.
GetInvulnerabilityTypeString()
override string bsbDebugPrint::GetInvulnerabilityTypeString ()
Definition at line 1287 of file basebuildingbase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), ItemBase::BaseBuildingBase(), BuildPartServer(), DeployableContainer_Base(), and ItemBase::TentBase().
GetKitSpawnPosition()
protected vector bsbDebugPrint::GetKitSpawnPosition ()
Definition at line 1580 of file basebuildingbase.c.
HasAttachmentsBesidesBase()
bool bsbDebugPrint::HasAttachmentsBesidesBase ()
Definition at line 2117 of file basebuildingbase.c.
HasBase()
bool bsbDebugPrint::HasBase ()
Definition at line 1539 of file basebuildingbase.c.
Referenced by BaseBuildingBase::CanDisplayAttachmentCategory(), ItemBase::CanFoldBaseBuildingObject(), BaseBuildingBase::CanPutIntoHands(), BaseBuildingBase::CanReceiveAttachment(), ItemBase::HasAttachmentsBesidesBase(), ItemBase::InitVisuals(), ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
HasProperDistance()
bool bsbDebugPrint::HasProperDistance (string selection, PlayerBase player)
Definition at line 2186 of file basebuildingbase.c.
IgnoreOutOfReachCondition()
override bool bsbDebugPrint::IgnoreOutOfReachCondition ()
Definition at line 1757 of file basebuildingbase.c.
InitBaseState()
void bsbDebugPrint::InitBaseState ()
Definition at line 1879 of file basebuildingbase.c.
InitVisuals()
void bsbDebugPrint::InitVisuals ()
Definition at line 1888 of file basebuildingbase.c.
IsAttachmentSlotLocked() [1/2]
protected bool bsbDebugPrint::IsAttachmentSlotLocked (EntityAI attachment)
Definition at line 2051 of file basebuildingbase.c.
Referenced by ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
IsAttachmentSlotLocked() [2/2]
protected bool bsbDebugPrint::IsAttachmentSlotLocked (string slot_name)
Definition at line 2064 of file basebuildingbase.c.
IsDeployable()
override bool bsbDebugPrint::IsDeployable ()
Definition at line 1549 of file basebuildingbase.c.
IsFacingCamera()
bool bsbDebugPrint::IsFacingCamera (string selection)
Definition at line 2174 of file basebuildingbase.c.
IsFacingPlayer()
override bool bsbDebugPrint::IsFacingPlayer (PlayerBase player, string selection)
Definition at line 2157 of file basebuildingbase.c.
IsIgnoredByConstruction()
override bool bsbDebugPrint::IsIgnoredByConstruction ()
Definition at line 2297 of file basebuildingbase.c.
IsOpened()
bool bsbDebugPrint::IsOpened ()
Definition at line 1554 of file basebuildingbase.c.
Referenced by BaseBuildingBase::AfterStoreLoad(), PluginBase::EditorToggle(), PluginBase::EditorUpdate(), and LayoutHolder::Toggle().
IsPartBuildInSyncData()
bool bsbDebugPrint::IsPartBuildInSyncData (int part_id)
Definition at line 1390 of file basebuildingbase.c.
Referenced by ItemBase::SetPartFromSyncData().
IsPlayerInside()
override bool bsbDebugPrint::IsPlayerInside (PlayerBase player, string selection)
Definition at line 2162 of file basebuildingbase.c.
MustBeBuiltFromOutside()
bool bsbDebugPrint::MustBeBuiltFromOutside ()
Some buildings can only be built from outside.
Definition at line 2168 of file basebuildingbase.c.
OnDebugSpawn()
override void bsbDebugPrint::OnDebugSpawn ()
Definition at line 2394 of file basebuildingbase.c.
OnDebugSpawnBuildExcludes()
array< string > bsbDebugPrint::OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 2389 of file basebuildingbase.c.
OnPartBuiltClient()
void bsbDebugPrint::OnPartBuiltClient (string part_name, int action_id)
Definition at line 1796 of file basebuildingbase.c.
Referenced by ItemBase::SetActionFromSyncData().
OnPartBuiltServer()
void bsbDebugPrint::OnPartBuiltServer (notnull Man player, string part_name, int action_id)
Definition at line 1764 of file basebuildingbase.c.
OnPartDestroyedClient()
void bsbDebugPrint::OnPartDestroyedClient (string part_name, int action_id)
Definition at line 1872 of file basebuildingbase.c.
Referenced by ItemBase::SetActionFromSyncData().
OnPartDestroyedServer()
void bsbDebugPrint::OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false)
Definition at line 1841 of file basebuildingbase.c.
OnPartDismantledClient()
void bsbDebugPrint::OnPartDismantledClient (string part_name, int action_id)
Definition at line 1834 of file basebuildingbase.c.
Referenced by ItemBase::SetActionFromSyncData().
OnPartDismantledServer()
void bsbDebugPrint::OnPartDismantledServer (notnull Man player, string part_name, int action_id)
Definition at line 1803 of file basebuildingbase.c.
OnSetSlotLock()
protected void bsbDebugPrint::OnSetSlotLock (int slotId, bool locked, bool was_locked)
Definition at line 1747 of file basebuildingbase.c.
OnStoreLoad()
override bool bsbDebugPrint::OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 1616 of file basebuildingbase.c.
OnStoreSave()
override void bsbDebugPrint::OnStoreSave (ParamsWriteContext ctx)
Definition at line 1604 of file basebuildingbase.c.
OnSynchronizedClient()
protected void bsbDebugPrint::OnSynchronizedClient ()
Definition at line 1319 of file basebuildingbase.c.
Referenced by ItemBase::OnVariablesSynchronized().
OnVariablesSynchronized()
override void bsbDebugPrint::OnVariablesSynchronized ()
Definition at line 1311 of file basebuildingbase.c.
PerformRoofCheckForBase()
bool bsbDebugPrint::PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
Definition at line 2180 of file basebuildingbase.c.
RegisterActionForSync()
protected void bsbDebugPrint::RegisterActionForSync (int part_id, int action_id)
Definition at line 1430 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
RegisterPartForSync()
void bsbDebugPrint::RegisterPartForSync (int part_id)
Definition at line 1332 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltServer().
ResetActionSyncData()
protected void bsbDebugPrint::ResetActionSyncData ()
Definition at line 1436 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
SetActionFromSyncData()
protected void bsbDebugPrint::SetActionFromSyncData ()
Definition at line 1443 of file basebuildingbase.c.
Referenced by ItemBase::OnSynchronizedClient().
SetActions()
override void bsbDebugPrint::SetActions ()
Definition at line 2370 of file basebuildingbase.c.
SetBaseState()
void bsbDebugPrint::SetBaseState (bool has_base)
Definition at line 1544 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltServer(), and ItemBase::SetPartsAfterStoreLoad().
SetPartFromSyncData()
void bsbDebugPrint::SetPartFromSyncData (ConstructionPart part)
Definition at line 1460 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), and ItemBase::SetPartsFromSyncData().
SetPartsAfterStoreLoad()
void bsbDebugPrint::SetPartsAfterStoreLoad ()
Definition at line 1660 of file basebuildingbase.c.
Referenced by ItemBase::AfterStoreLoad(), and ItemBase::EEOnAfterLoad().
SetPartsFromSyncData()
void bsbDebugPrint::SetPartsFromSyncData ()
Definition at line 1502 of file basebuildingbase.c.
Referenced by ItemBase::OnSynchronizedClient(), and ItemBase::SetPartsAfterStoreLoad().
ShowZonesHealth()
override bool bsbDebugPrint::ShowZonesHealth ()
Definition at line 2133 of file basebuildingbase.c.
SoundBuildStart()
protected void bsbDebugPrint::SoundBuildStart (string part_name)
Definition at line 2305 of file basebuildingbase.c.
Referenced by ItemBase::OnPartBuiltClient().
SoundDestroyStart()
protected void bsbDebugPrint::SoundDestroyStart (string part_name)
Definition at line 2315 of file basebuildingbase.c.
Referenced by ItemBase::OnPartDestroyedClient().
SoundDismantleStart()
protected void bsbDebugPrint::SoundDismantleStart (string part_name)
Definition at line 2310 of file basebuildingbase.c.
Referenced by ItemBase::OnPartDismantledClient().
SynchronizeBaseState()
void bsbDebugPrint::SynchronizeBaseState ()
Definition at line 1303 of file basebuildingbase.c.
Referenced by BaseBuildingBase::CloseFence(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), BaseBuildingBase::OpenFence(), and ItemBase::SetPartsAfterStoreLoad().
UnregisterPartForSync()
void bsbDebugPrint::UnregisterPartForSync (int part_id)
Definition at line 1361 of file basebuildingbase.c.
Referenced by ItemBase::OnPartDestroyedServer(), and ItemBase::OnPartDismantledServer().
UpdateAttachmentPhysics()
void bsbDebugPrint::UpdateAttachmentPhysics (string slot_name, bool is_locked)
Definition at line 2005 of file basebuildingbase.c.
Referenced by ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ItemBase::OnSetSlotLock(), and ItemBase::UpdatePhysics().
UpdateAttachmentVisuals()
void bsbDebugPrint::UpdateAttachmentVisuals (string slot_name, bool is_locked)
Definition at line 1928 of file basebuildingbase.c.
Referenced by ItemBase::OnSetSlotLock(), and ItemBase::UpdateVisuals().
UpdateNavmesh()
protected void bsbDebugPrint::UpdateNavmesh ()
Definition at line 2035 of file basebuildingbase.c.
Referenced by BaseBuildingBase::CloseFence(), ItemBase::InitBaseState(), BaseBuildingBase::OpenFence(), ItemBase::SetPartsFromSyncData(), and ItemBase::UpdatePhysics().
UpdatePhysics()
void bsbDebugPrint::UpdatePhysics ()
Definition at line 1973 of file basebuildingbase.c.
UpdateVisuals()
void bsbDebugPrint::UpdateVisuals ()
Definition at line 1904 of file basebuildingbase.c.
Variable Documentation
ANIMATION_DEPLOYED
const string ANIMATION_DEPLOYED = "Deployed"
Definition at line 1223 of file basebuildingbase.c.
Referenced by ItemBase::InitVisuals(), ItemBase::SetPartFromSyncData(), ItemBase::UpdatePhysics(), and ItemBase::UpdateVisuals().
m_Construction
ref Construction m_Construction
Definition at line 1227 of file basebuildingbase.c.
Referenced by ItemBase::ConstructionInit(), and ItemBase::GetConstruction().
m_ConstructionKitHealth
float m_ConstructionKitHealth
Definition at line 1225 of file basebuildingbase.c.
Referenced by ItemBase::CreateConstructionKit(), ItemBase::CreateConstructionKitInHands(), and ItemBase::DestroyConstructionKit().
m_DamageTriggers
ref map<string, ref AreaDamageManager> m_DamageTriggers
Definition at line 1253 of file basebuildingbase.c.
Referenced by ItemBase::BaseBuildingBase(), ItemBase::CreateAreaDamage(), and ItemBase::DestroyAreaDamage().
m_HasBase
bool m_HasBase = false
Definition at line 1229 of file basebuildingbase.c.
Referenced by ItemBase::HasBase(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), and ItemBase::SetBaseState().
m_HybridAttachments
ref array<string> m_HybridAttachments
Definition at line 1254 of file basebuildingbase.c.
Referenced by ItemBase::BaseBuildingBase(), and ItemBase::CheckForHybridAttachments().
m_InteractedPartId
int m_InteractedPartId
Definition at line 1234 of file basebuildingbase.c.
Referenced by ItemBase::RegisterActionForSync(), ItemBase::ResetActionSyncData(), and ItemBase::SetActionFromSyncData().
m_Mountables
ref array<string> m_Mountables
Definition at line 1255 of file basebuildingbase.c.
Referenced by ItemBase::BaseBuildingBase(), and ItemBase::UpdateAttachmentPhysics().
m_PerformedActionId
int m_PerformedActionId
Definition at line 1235 of file basebuildingbase.c.
Referenced by ItemBase::RegisterActionForSync(), ItemBase::ResetActionSyncData(), and ItemBase::SetActionFromSyncData().
m_Sound
protected EffectSound m_Sound
Definition at line 1251 of file basebuildingbase.c.
m_SyncParts01
int m_SyncParts01
Definition at line 1231 of file basebuildingbase.c.
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
m_SyncParts02
int m_SyncParts02
Definition at line 1232 of file basebuildingbase.c.
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
m_SyncParts03
int m_SyncParts03
Definition at line 1233 of file basebuildingbase.c.
Referenced by ItemBase::IsPartBuildInSyncData(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::RegisterPartForSync(), and ItemBase::UnregisterPartForSync().
SOUND_BUILD_METAL
const string SOUND_BUILD_METAL = "putDown_MetalPlank_SoundSet"
Definition at line 1242 of file basebuildingbase.c.
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WIRE
const string SOUND_BUILD_WIRE = "putDown_BarbedWire_SoundSet"
Definition at line 1243 of file basebuildingbase.c.
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_LOG
const string SOUND_BUILD_WOOD_LOG = "putDown_WoodLog_SoundSet"
Definition at line 1239 of file basebuildingbase.c.
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_PLANK
const string SOUND_BUILD_WOOD_PLANK = "putDown_WoodPlank_SoundSet"
Definition at line 1240 of file basebuildingbase.c.
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_BUILD_WOOD_STAIRS
const string SOUND_BUILD_WOOD_STAIRS = "putDown_WoodStairs_SoundSet"
Definition at line 1241 of file basebuildingbase.c.
Referenced by ItemBase::GetBuildSoundByMaterial().
SOUND_DISMANTLE_METAL
const string SOUND_DISMANTLE_METAL = "Crash_MetalPlank_SoundSet"
Definition at line 1248 of file basebuildingbase.c.
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WIRE
const string SOUND_DISMANTLE_WIRE = "putDown_BarbedWire_SoundSet"
Definition at line 1249 of file basebuildingbase.c.
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_LOG
const string SOUND_DISMANTLE_WOOD_LOG = "Crash_WoodPlank_SoundSet"
Definition at line 1245 of file basebuildingbase.c.
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_PLANK
const string SOUND_DISMANTLE_WOOD_PLANK = "Crash_WoodPlank_SoundSet"
Definition at line 1246 of file basebuildingbase.c.
Referenced by ItemBase::GetDismantleSoundByMaterial().
SOUND_DISMANTLE_WOOD_STAIRS
const string SOUND_DISMANTLE_WOOD_STAIRS = "Crash_WoodPlank_SoundSet"
Definition at line 1247 of file basebuildingbase.c.
Referenced by ItemBase::GetDismantleSoundByMaterial().