DayzKode: P:/scripts/4_world/DayZ/systems/bot/bot_hunt.c File Reference
bot_hunt.c File Reference
Classes
class BotEventHuntedTargetInSight
class BotEventHuntedTargetLost
class BotStateBase
represent weapon state base
Functions
Man BotSelectNearestTarget (EntityAI bot)
Function Documentation
BotSelectNearestTarget()
Man BotSelectNearestTarget (EntityAI bot)
Definition at line 195 of file bot_hunt.c.
{
    /*ref array<Man> players = new array<Man>;
    g_Game.GetWorld().GetPlayerList( players );
    bool minimal_distance_ok = true;
    float min_dist = 1234567.0;
    int min_index = -1;
    for ( int i = 0; i < players.Count(); i++ )
    {
        float d = vector.Distance(players.Get(i).GetPosition(), bot.GetPosition());
        if ( d < min_dist )
        {
            min_dist = d;
            min_index = i;
        }
    }
    if (min_index != -1)
        return players.Get(min_index);
    return null;*/
        vector pos = bot.GetPosition();
        //vector dir = player.GetDirection();
    array<Object> objects = new array<Object>;
    array<CargoBase> proxyCargos = new array<CargoBase>;
    GetGame().GetObjectsAtPosition(pos, 100.0, objects, proxyCargos);
    float min_dist = 1234567.0;
    int min_index = -1;
    int c = objects.Count();
    for (int i = 0; i < c; i++)
    {
        Object o = objects[i];
        if (o == bot)
            continue;
        float d = vector.Distance(o.GetPosition(), bot.GetPosition());
        if ( d < min_dist )
        {
            min_dist = d;
            min_index = i;
        }
    }
    if (min_index != -1)
    {
        botDebugPrint("[bot] + " + bot + " BotSelectNearestTarget idx=" + min_index + " dist=" + min_dist + " obj=" + o);
        return Man.Cast( objects.Get(min_index) );
    }
    return null;
}
References botDebugPrint(), vector::Distance(), GetGame(), and CGame::GetObjectsAtPosition().
Referenced by BotStateBase::SelectTarget().