DayzKode: P:/scripts/4_world/DayZ/systems/bot/bot.c File Reference
bot.c File Reference
Classes
class Bot
class BotTrigger
class MyBotTrigger
Functions
void botDebugPrint (string s)
void botDebugSpam (string s)
Function Documentation
botDebugPrint()
void botDebugPrint (string s)
Definition at line 182 of file bot.c.
{
    Print("" + s); // comment/uncomment to hide/see debug logs
}
References Print().
Referenced by BotSelectNearestTarget(), BotGuardBase::GuardCondition(), BotStateBase::OnAbort(), OnEntry(), BotTestSpamUserActions::OnEntry(), BotStateBase::OnEntry(), BotWaitForChangeInHands::OnEntry(), BotTestSpamUserActions_Start::OnExit(), BotStateBase::OnExit(), OnTimeout(), Bot::OnTrigger(), BotStateBase::OnUpdate(), BotTestSwapInternal::OnUpdate(), BotTestSwapInternalC2H::OnUpdate(), OnUpdate(), BotStateBase::SelectTarget(), and Bot::Start().
botDebugSpam()
void botDebugSpam (string s)
Definition at line 187 of file bot.c.
{
    //Print("" + s); // comment/uncomment to hide/see debug logs
}
Referenced by BotStateBase::OnTimeout(), BotStateBase::OnUpdate(), and Bot::ProcessEvent().