DayzKode: P:/scripts/4_world/DayZ/systems/bot/bot_testspamuseractions.c File Reference
bot_testspamuseractions.c File Reference
Classes
class BotTestSpamUserActions
class BotTestSpamUserActions_Start
Functions
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnTimeout ()
override void OnUpdate (float dt)
Variables
BotTestSpamUserActions_Start m_Entity = null
bool m_Run = false
int m_RunStage = 0
ref InventoryLocation m_Src = new InventoryLocation
Function Documentation
OnEntry()
override void OnEntry (BotEventBase e)
Definition at line 33 of file bot_testspamuseractions.c.
    {
        m_Entity = m_Owner.GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("Legs"));
        botDebugPrint("[bot] + " + m_Owner + "BotTestSpamUserActions_GetEntityFromSlot item=" + m_Entity);
        GameInventory.SetGroundPosByOwner(m_Owner, m_Entity, m_Src);
        /*if (!m_Entity.GetInventory().GetCurrentInventoryLocation(m_Src))
        {
            Error("NI!");
        }*/
        if (!GetGame().IsDedicatedServer())
        {
            m_Entity = m_Owner.GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("Legs"));
            m_Owner.PredictiveDropEntity(m_Entity);
        }
        super.OnEntry(e);
    }
References botDebugPrint(), GetGame(), InventorySlots::GetSlotIdFromString(), m_Entity, and m_Src.
OnExit()
override void OnExit (BotEventBase e)
Definition at line 53 of file bot_testspamuseractions.c.
    {
        m_Entity = null;
        super.OnExit(e);
    }
References m_Entity.
OnTimeout()
override void OnTimeout ()
Definition at line 132 of file bot_testspamuseractions.c.
    {
        super.OnTimeout();
        botDebugPrint("[bot] + " + m_Owner + "BotTestSpamUserActions_GetEntityFromSlot item=" + m_Entity);
        if (m_Entity && m_Run == false)
        {
            m_Run = true;
            m_RunStage = 0;
        }
    }
References botDebugPrint(), m_Entity, m_Run, and m_RunStage.
OnUpdate()
override void OnUpdate (float dt)
Definition at line 60 of file bot_testspamuseractions.c.
    {
        super.OnUpdate(dt);
        if (!GetGame().IsDedicatedServer())
        {
            if (m_Run && m_Entity)
            {
                switch (m_RunStage)
                {
                    case 0:
                        botDebugPrint("[bot] + " + m_Owner + " STS = " + m_Owner.GetSimulationTimeStamp() + " Stage=" + m_RunStage + " item=" + m_Entity);
                        ScriptInputUserData ctx = new ScriptInputUserData;
                        HandEventTake e = new HandEventTake(m_Owner, m_Src);
                        InventoryInputUserData.SerializeHandEvent(ctx, e);
                        ctx.Send();
                        break;
                    case 1:
                        botDebugPrint("[bot] + " + m_Owner + " STS = " + m_Owner.GetSimulationTimeStamp() + " Stage=" + m_RunStage + " item=" + m_Entity);
                        ScriptInputUserData ctx1 = new ScriptInputUserData;
                        HandEventTake e1 = new HandEventTake(m_Owner, m_Src);
                        InventoryInputUserData.SerializeHandEvent(ctx1, e1);
                        ctx1.Send();
                        break;
                    case 5:
                        botDebugPrint("[bot] + " + m_Owner + " STS = " + m_Owner.GetSimulationTimeStamp() + " Stage=" + m_RunStage + " item=" + m_Entity);
                        ScriptInputUserData ctx2 = new ScriptInputUserData;
                        InventoryLocation dst = new InventoryLocation;
                        dst.SetAttachment(m_Owner, m_Entity, InventorySlots.GetSlotIdFromString("Legs"));
                        InventoryInputUserData.SerializeMove(ctx2, InventoryCommandType.SYNC_MOVE, m_Src, dst);
                        ctx2.Send();
                        break;
                    case 10:
                        botDebugPrint("[bot] + " + m_Owner + " STS = " + m_Owner.GetSimulationTimeStamp() + " Stage=" + m_RunStage + " item=" + m_Entity);
                        ScriptInputUserData ctx3 = new ScriptInputUserData;
                        InventoryLocation dst2 = new InventoryLocation;
                        dst2.SetAttachment(m_Owner, m_Entity, InventorySlots.GetSlotIdFromString("Legs"));
                        InventoryInputUserData.SerializeMove(ctx3, InventoryCommandType.SYNC_MOVE, m_Src, dst2);
                        ctx3.Send();
                        break;
                    /*
                    case 0:
                        botDebugPrint("[bot] + " + m_Owner + "Stage0 item=" + m_Entity);
                        m_Owner.PredictiveTakeEntityToHands(m_Entity);
                        break;
                    case 1:
                        botDebugPrint("[bot] + " + m_Owner + "Stage1 item=" + m_Entity);
                        m_Owner.PredictiveTakeEntityToHands(m_Entity);
                        break;
                    case 2:
                        botDebugPrint("[bot] + " + m_Owner + "Stage2 item=" + m_Entity);
                        m_Owner.PredictiveTakeEntityAsAttachmentEx(m_Entity, InventorySlots.GetSlotIdFromString("Legs"));
                        break;
                    case 3:
                        botDebugPrint("[bot] + " + m_Owner + "Stage3 item=" + m_Entity);
                        m_Owner.PredictiveTakeEntityAsAttachmentEx(m_Entity, InventorySlots.GetSlotIdFromString("Legs"));
                        break;*/
                }
                ++m_RunStage;
            }
        }
    }
References botDebugPrint(), GetGame(), InventorySlots::GetSlotIdFromString(), m_Entity, m_Run, m_RunStage, m_Src, ScriptInputUserData::Send(), InventoryInputUserData::SerializeHandEvent(), InventoryInputUserData::SerializeMove(), and InventoryLocation::SetAttachment().
Variable Documentation
m_Entity
BotTestSpamUserActions_Start m_Entity = null
m_Run
bool m_Run = false
Definition at line 29 of file bot_testspamuseractions.c.
Referenced by OnTimeout(), and OnUpdate().
m_RunStage
int m_RunStage = 0
Definition at line 30 of file bot_testspamuseractions.c.
Referenced by OnTimeout(), and OnUpdate().
m_Src
ref InventoryLocation m_Src = new InventoryLocation
Definition at line 31 of file bot_testspamuseractions.c.