DayzKode: P:/scripts/4_world/DayZ/entities/itembase/edible_base/bottle_base.c File Reference
bottle_base.c File Reference
Enumerations
enum SoundTypeBottle { POURING = 1 , EMPTYING = 0 }
Functions
void Bottle_Base ()
override void EEDelete (EntityAI parent)
string GetEmptyingEndSoundset ()
string GetEmptyingEndSoundsetHard ()
string GetEmptyingEndSoundsetSoft ()
string GetEmptyingEndSoundsetWater ()
string GetEmptyingLoopSoundset ()
string GetEmptyingLoopSoundsetHard ()
string GetEmptyingLoopSoundsetSoft ()
string GetEmptyingLoopSoundsetWater ()
float GetLiquidEmptyRate ()
Returns base liquid empty rate (absolute)..preferrably use the 'GetLiquidThroughputCoef' instead.
string GetPouringSoundset ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
override void OnVariablesSynchronized ()
void ParticleCookingStart (int particle_id)
void ParticleCookingStop ()
void PlayEmptyingLoopSound ()
void PlayPouringLoopSound ()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RemoveAudioVisuals ()
void RemoveAudioVisualsOnClient ()
override void SetActions ()
void StopEmptyingLoopSound ()
void StopPouringLoopSound ()
override void Synchronize ()
void ~Bottle_Base ()
Variables
protected bool m_CookingIsBurned
protected bool m_CookingIsDone
protected bool m_CookingIsEmpty
protected CookingMethodType m_CookingMethod
ref protected EffectSound m_EmptyingLoopSound
float m_LiquidEmptyRate
enum SoundTypeBottle m_ParticleCooking
protected int m_ParticlePlaying = ParticleList.INVALID
ref protected EffectSound m_PouringLoopSound
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
protected int PARTICLE_BOILING_DONE = ParticleList.COOKING_BOILING_DONE
protected int PARTICLE_BOILING_EMPTY = ParticleList.COOKING_BOILING_EMPTY
protected int PARTICLE_BOILING_START = ParticleList.COOKING_BOILING_START
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
private const float QUANTITY_EMPTIED_PER_SEC_DEFAULT = 200
const string SOUND_BOILING_DONE = "boilingWaterDone"
const string SOUND_BOILING_EMPTY = "boilingWater"
const string SOUND_BOILING_START = "boilingWater"
const string SOUND_DRYING_DONE = "dryDone"
const string SOUND_DRYING_START = "dry"
Enumeration Type Documentation
SoundTypeBottle
enum SoundTypeBottle
Enumerator
POURING
EMPTYING
Definition at line 1 of file bottle_base.c.
{
    POURING         = 1,
    EMPTYING        = 0,
}
Function Documentation
Bottle_Base()
void Bottle_Base ()
Definition at line 51 of file bottle_base.c.
    {
        RegisterNetSyncVariableInt( "m_CookingMethod", CookingMethodType.NONE, CookingMethodType.COUNT );
        RegisterNetSyncVariableBool("m_CookingIsDone");
        RegisterNetSyncVariableBool("m_CookingIsEmpty");
        RegisterNetSyncVariableBool("m_CookingIsBurned");
        m_LiquidEmptyRate = QUANTITY_EMPTIED_PER_SEC_DEFAULT;
    }
References m_LiquidEmptyRate, and QUANTITY_EMPTIED_PER_SEC_DEFAULT.
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 67 of file bottle_base.c.
    {
        super.EEDelete( parent );
        //remove audio visuals
        RemoveAudioVisuals();
    }
References RemoveAudioVisuals().
GetEmptyingEndSoundset()
string GetEmptyingEndSoundset ()
Definition at line 324 of file bottle_base.c.
    {
        vector pos = GetPosition();
        string surface_type = GetGame().GetPlayer().GetSurfaceType();
        string sound_set = "";
        bool diggable = GetGame().IsSurfaceDigable( surface_type );
        if ( !diggable )
        {
            sound_set = GetEmptyingEndSoundsetHard();
        }
        else if ( diggable )
        {
            sound_set = GetEmptyingEndSoundsetSoft();
        }
        else if ( GetGame().SurfaceIsPond( pos[0], pos[2] ) || GetGame().SurfaceIsSea( pos[0], pos[2] ) )
        {
            sound_set = GetEmptyingEndSoundsetWater();
        }
        return sound_set;
    }
References Bottle_Base::GetEmptyingEndSoundsetHard(), Bottle_Base::GetEmptyingEndSoundsetSoft(), Bottle_Base::GetEmptyingEndSoundsetWater(), GetGame(), CGame::GetPlayer(), GetPosition, and CGame::IsSurfaceDigable().
Referenced by StopEmptyingLoopSound().
GetEmptyingEndSoundsetHard()
string GetEmptyingEndSoundsetHard ()
Definition at line 356 of file bottle_base.c.
{};
GetEmptyingEndSoundsetSoft()
string GetEmptyingEndSoundsetSoft ()
Definition at line 358 of file bottle_base.c.
{};
GetEmptyingEndSoundsetWater()
string GetEmptyingEndSoundsetWater ()
Definition at line 360 of file bottle_base.c.
{};
GetEmptyingLoopSoundset()
string GetEmptyingLoopSoundset ()
Definition at line 300 of file bottle_base.c.
    {
        vector pos = GetPosition();
        string surface_type = GetGame().GetPlayer().GetSurfaceType();
        string sound_set = "";
        bool diggable = GetGame().IsSurfaceDigable( surface_type );
        if ( !diggable )
        {
            sound_set = GetEmptyingLoopSoundsetHard();
        }
        else if ( diggable )
        {
            sound_set = GetEmptyingLoopSoundsetSoft();
        }
        else if ( GetGame().SurfaceIsPond( pos[0], pos[2] ) || GetGame().SurfaceIsSea( pos[0], pos[2] ) )
        {
            sound_set = GetEmptyingLoopSoundsetWater();
        }
        return sound_set;
    }
References Bottle_Base::GetEmptyingLoopSoundsetHard(), Bottle_Base::GetEmptyingLoopSoundsetSoft(), Bottle_Base::GetEmptyingLoopSoundsetWater(), GetGame(), CGame::GetPlayer(), GetPosition, and CGame::IsSurfaceDigable().
Referenced by PlayEmptyingLoopSound().
GetEmptyingLoopSoundsetHard()
string GetEmptyingLoopSoundsetHard ()
Definition at line 350 of file bottle_base.c.
{};
GetEmptyingLoopSoundsetSoft()
string GetEmptyingLoopSoundsetSoft ()
Definition at line 352 of file bottle_base.c.
{};
GetEmptyingLoopSoundsetWater()
string GetEmptyingLoopSoundsetWater ()
Definition at line 354 of file bottle_base.c.
{};
GetLiquidEmptyRate()
float GetLiquidEmptyRate ()
Returns base liquid empty rate (absolute)..preferrably use the 'GetLiquidThroughputCoef' instead.
Definition at line 363 of file bottle_base.c.
    {
        return m_LiquidEmptyRate;
    }
References m_LiquidEmptyRate.
GetPouringSoundset()
string GetPouringSoundset ()
Definition at line 348 of file bottle_base.c.
{}
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 90 of file bottle_base.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        Param1<bool> p = new Param1<bool>(false);
        if (!ctx.Read(p))
            return;
        bool play = p.param1;
        switch (rpc_type)
        {
            case SoundTypeBottle.POURING:
                if ( play )
                {
                    PlayPouringLoopSound();
                }
                else
                {
                    StopPouringLoopSound();
                }
            break;
            case SoundTypeBottle.EMPTYING:
                if ( play )
                {
                    PlayEmptyingLoopSound();
                }
                else
                {
                    StopEmptyingLoopSound();
                }
            break;
        }
    }
References PlayEmptyingLoopSound(), PlayPouringLoopSound(), Serializer::Read(), StopEmptyingLoopSound(), and StopPouringLoopSound().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 131 of file bottle_base.c.
    {
        super.OnVariablesSynchronized();
        //refresh audio visuals
        if ( m_CookingMethod != CookingMethodType.NONE )
        {
            RefreshAudioVisuals( m_CookingMethod, m_CookingIsDone, m_CookingIsEmpty, m_CookingIsBurned );
        }
        else
        {
            RemoveAudioVisuals();
        }
    }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, RefreshAudioVisuals(), and RemoveAudioVisuals().
ParticleCookingStart()
void ParticleCookingStart (int particle_id)
Definition at line 240 of file bottle_base.c.
    {
        if ( m_ParticlePlaying != particle_id )
        {
            //stop previous particles
            ParticleCookingStop();
            //create new
            if ( GetGame() && !GetGame().IsDedicatedServer() )
            {
                vector local_pos = MiscGameplayFunctions.GetSteamPosition( GetHierarchyParent() );
                //TODO set steam position to pot (proxy) memory point (new hierarchy needed)
                //m_ParticleCooking = Particle.Create( particle_id, this, local_pos );
                m_ParticleCooking = ParticleManager.GetInstance().PlayInWorld( particle_id, local_pos );
                m_ParticlePlaying = particle_id;
            }
        }
    }
References GetGame(), m_ParticleCooking, m_ParticlePlaying, particle_id, ParticleCookingStop(), and ParticleManager().
Referenced by RefreshAudioVisuals().
ParticleCookingStop()
void ParticleCookingStop ()
Definition at line 259 of file bottle_base.c.
    {
        if ( m_ParticleCooking && GetGame() && !GetGame().IsDedicatedServer() )
        {
            m_ParticleCooking.Stop();
            m_ParticleCooking = null;
            m_ParticlePlaying = ParticleList.INVALID;
        }
    }
References GetGame(), ParticleList::INVALID, m_ParticleCooking, and m_ParticlePlaying.
Referenced by ParticleCookingStart(), and RemoveAudioVisuals().
PlayEmptyingLoopSound()
void PlayEmptyingLoopSound ()
Definition at line 283 of file bottle_base.c.
    {
        if ( !m_EmptyingLoopSound || !m_EmptyingLoopSound.IsSoundPlaying() )
        {
            m_EmptyingLoopSound = SEffectManager.PlaySoundOnObject( GetEmptyingLoopSoundset(), this );
        }
    }
References GetEmptyingLoopSoundset(), EffectSound::IsSoundPlaying(), m_EmptyingLoopSound, and SEffectManager::PlaySoundOnObject().
Referenced by OnRPC().
PlayPouringLoopSound()
void PlayPouringLoopSound ()
Definition at line 269 of file bottle_base.c.
    {
        if ( !m_PouringLoopSound || !m_PouringLoopSound.IsSoundPlaying() )
        {
            m_PouringLoopSound = SEffectManager.PlaySoundOnObject( GetPouringSoundset(), this );
        }
    }
References Bottle_Base::GetPouringSoundset(), EffectSound::IsSoundPlaying(), m_PouringLoopSound, and SEffectManager::PlaySoundOnObject().
Referenced by OnRPC().
RefreshAudioVisuals()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
Definition at line 165 of file bottle_base.c.
    {
        string sound_name;
        int particle_id;
        //if at least one of the food items is burned
        if ( is_burned )
        {
            sound_name      = SOUND_BURNING_DONE;
            particle_id     = PARTICLE_BURNING_DONE;
        }
        //proper cooking methods
        else
        {
            if ( cooking_method == CookingMethodType.BOILING )
            {
                if ( is_empty )                                         //EMPTY
                {
                    sound_name      = SOUND_BOILING_EMPTY;
                    particle_id     = PARTICLE_BOILING_EMPTY;
                }
                else
                {
                    if ( is_done )                                      //DONE
                    {
                        sound_name      = SOUND_BOILING_DONE;
                        particle_id     = PARTICLE_BOILING_DONE;
                    }
                    else                                                //START
                    {
                        sound_name      = SOUND_BOILING_START;
                        particle_id     = PARTICLE_BOILING_START;
                    }
                }
            }
            else if ( cooking_method == CookingMethodType.BAKING )
            {
                if ( is_done )                                          //DONE
                {
                    sound_name      = SOUND_BAKING_DONE;
                    particle_id     = PARTICLE_BAKING_DONE;
                }
                else                                                    //START
                {
                    sound_name      = SOUND_BAKING_START;
                    particle_id     = PARTICLE_BAKING_START;
                }
            }
            else if ( cooking_method == CookingMethodType.DRYING )
            {
                if ( is_done )                                          //DONE
                {
                    sound_name      = SOUND_DRYING_DONE;
                    particle_id     = PARTICLE_DRYING_DONE;
                }
                else                                                    //START
                {
                    sound_name      = SOUND_DRYING_START;
                    particle_id     = PARTICLE_DRYING_START;
                }
            }
        }
        //play effects
        ParticleCookingStart( particle_id );
        SoundCookingStart( sound_name );
    }
References PARTICLE_BAKING_DONE, PARTICLE_BAKING_START, PARTICLE_BOILING_DONE, PARTICLE_BOILING_EMPTY, PARTICLE_BOILING_START, PARTICLE_BURNING_DONE, PARTICLE_DRYING_DONE, PARTICLE_DRYING_START, particle_id, ParticleCookingStart(), SOUND_BAKING_DONE, SOUND_BAKING_START, SOUND_BOILING_DONE, SOUND_BOILING_EMPTY, SOUND_BOILING_START, SOUND_BURNING_DONE, SOUND_DRYING_DONE, SOUND_DRYING_START, and SoundCookingStart().
Referenced by OnVariablesSynchronized().
RefreshAudioVisualsOnClient()
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
Definition at line 154 of file bottle_base.c.
    {
        m_CookingMethod     = cooking_method;
        m_CookingIsDone     = is_done;
        m_CookingIsEmpty    = is_empty;
        m_CookingIsBurned   = is_burned;
        //synchronize
        Synchronize();
    }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, and Synchronize().
RemoveAudioVisuals()
void RemoveAudioVisuals ()
Definition at line 233 of file bottle_base.c.
    {
        ParticleCookingStop();
        SoundCookingStop();
    }
References ParticleCookingStop(), and SoundCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
RemoveAudioVisualsOnClient()
void RemoveAudioVisualsOnClient ()
Definition at line 146 of file bottle_base.c.
    {
        m_CookingMethod     = CookingMethodType.NONE;
        //synchronize
        Synchronize();
    }
References m_CookingMethod, and Synchronize().
SetActions()
override void SetActions ()
Definition at line 368 of file bottle_base.c.
    {
        super.SetActions();
        AddAction(ActionFillFuel);
        AddAction(ActionFillCoolant);
        AddAction(ActionFillGeneratorTank);
        AddAction(ActionExtinguishFireplaceByLiquid);
        AddAction(ActionFillBottleBase);
        AddAction(ActionWaterGardenSlot);
        AddAction(ActionWaterPlant);
        AddAction(ActionForceDrink);
        AddAction(ActionDrainLiquid);
        AddAction(ActionPourLiquid);
        AddAction(ActionWashHandsItem);
        AddAction(ActionDrink);
        AddAction(ActionEmptyBottleBase);
    }
References AddAction().
StopEmptyingLoopSound()
void StopEmptyingLoopSound ()
Definition at line 291 of file bottle_base.c.
    {
        if (m_EmptyingLoopSound)
            m_EmptyingLoopSound.SoundStop();
        EffectSound sound = SEffectManager.PlaySoundOnObject( GetEmptyingEndSoundset(), this );
        sound.SetAutodestroy( true );
    }
References GetEmptyingEndSoundset(), m_EmptyingLoopSound, SEffectManager::PlaySoundOnObject(), EffectSound::SetAutodestroy(), and EffectSound::SoundStop().
Referenced by OnRPC().
StopPouringLoopSound()
void StopPouringLoopSound ()
Definition at line 277 of file bottle_base.c.
    {
        if (m_PouringLoopSound)
            m_PouringLoopSound.SoundStop();
    }
References m_PouringLoopSound, and EffectSound::SoundStop().
Referenced by OnRPC().
Synchronize()
override void Synchronize ()
Definition at line 82 of file bottle_base.c.
    {
        if ( GetGame() && GetGame().IsServer() )
        {
            SetSynchDirty();
        }
    }
References GetGame().
~Bottle_Base()
void ~Bottle_Base ()
Definition at line 61 of file bottle_base.c.
    {
        SEffectManager.DestroyEffect( m_PouringLoopSound );
        SEffectManager.DestroyEffect( m_EmptyingLoopSound );
    }
References SEffectManager::DestroyEffect(), m_EmptyingLoopSound, and m_PouringLoopSound.
Variable Documentation
m_CookingIsBurned
protected bool m_CookingIsBurned
Definition at line 34 of file bottle_base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingIsDone
protected bool m_CookingIsDone
Definition at line 32 of file bottle_base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingIsEmpty
protected bool m_CookingIsEmpty
Definition at line 33 of file bottle_base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), and Inventory_Base::RefreshAudioVisualsOnClient().
m_CookingMethod
protected CookingMethodType m_CookingMethod
Definition at line 31 of file bottle_base.c.
Referenced by OnVariablesSynchronized(), Inventory_Base::OnVariablesSynchronized(), RefreshAudioVisualsOnClient(), Inventory_Base::RefreshAudioVisualsOnClient(), RemoveAudioVisualsOnClient(), and Inventory_Base::RemoveAudioVisualsOnClient().
m_EmptyingLoopSound
ref protected EffectSound m_EmptyingLoopSound
Definition at line 28 of file bottle_base.c.
Referenced by PlayEmptyingLoopSound(), StopEmptyingLoopSound(), and ~Bottle_Base().
m_LiquidEmptyRate
float m_LiquidEmptyRate
Definition at line 48 of file bottle_base.c.
Referenced by Bottle_Base(), and GetLiquidEmptyRate().
m_ParticleCooking
enum SoundTypeBottle m_ParticleCooking
Referenced by ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), and Inventory_Base::ParticleCookingStop().
m_ParticlePlaying
protected int m_ParticlePlaying = ParticleList.INVALID
Definition at line 11 of file bottle_base.c.
Referenced by ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), and Inventory_Base::ParticleCookingStop().
m_PouringLoopSound
ref protected EffectSound m_PouringLoopSound
Definition at line 27 of file bottle_base.c.
Referenced by PlayPouringLoopSound(), StopPouringLoopSound(), and ~Bottle_Base().
PARTICLE_BAKING_DONE
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
Definition at line 19 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BAKING_START
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
Definition at line 18 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_DONE
protected int PARTICLE_BOILING_DONE = ParticleList.COOKING_BOILING_DONE
Definition at line 16 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_EMPTY
protected int PARTICLE_BOILING_EMPTY = ParticleList.COOKING_BOILING_EMPTY
Definition at line 14 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BOILING_START
protected int PARTICLE_BOILING_START = ParticleList.COOKING_BOILING_START
Definition at line 15 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BURNING_DONE
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
Definition at line 24 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_DONE
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
Definition at line 22 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_START
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
Definition at line 21 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
QUANTITY_EMPTIED_PER_SEC_DEFAULT
private const float QUANTITY_EMPTIED_PER_SEC_DEFAULT = 200
Definition at line 49 of file bottle_base.c.
Referenced by Bottle_Base().
SOUND_BOILING_DONE
const string SOUND_BOILING_DONE = "boilingWaterDone"
Definition at line 39 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
SOUND_BOILING_EMPTY
const string SOUND_BOILING_EMPTY = "boilingWater"
Definition at line 37 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
SOUND_BOILING_START
const string SOUND_BOILING_START = "boilingWater"
Definition at line 38 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_DONE
const string SOUND_DRYING_DONE = "dryDone"
Definition at line 44 of file bottle_base.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_START
const string SOUND_DRYING_START = "dry"
Definition at line 43 of file bottle_base.c.
Referenced by RefreshAudioVisuals().