DayzKode: P:/scripts/4_world/DayZ/classes/recipes/cacheobject.c File Reference
cacheobject.c File Reference
Classes
class RecipeCacheData
Functions
bool AddRecipe (int recipe_id, int mask)
void CacheObject ()
void DebugPrint ()
int GetBitCountByRecipeID (int recipe_id)
int GetMaskByRecipeID (int recipe_id)
int GetNumberOfRecipes ()
array< int > GetRecipes ()
bool IsContainRecipe (int recipe_id)
void UpdateMask (int recipe_id, int mask)
Variables
class RecipeCacheData int
ref array< int > m_RecipeIDs
class RecipeCacheData m_Recipes
Function Documentation
AddRecipe()
bool AddRecipe (int recipe_id, int mask)
Definition at line 41 of file cacheobject.c.
    {
        RecipeCacheData data = m_Recipes.Get(recipe_id);
        if(data)
        {
            UpdateMask(recipe_id, mask);
        }
        else
        {
            m_Recipes.Insert(recipe_id, new RecipeCacheData(mask));
            m_RecipeIDs.Insert(recipe_id);
        }
        return true;
    }
References m_RecipeIDs, m_Recipes, and UpdateMask().
CacheObject()
void CacheObject ()
Definition at line 35 of file cacheobject.c.
    {
        m_Recipes = new map<int, ref RecipeCacheData>;
        m_RecipeIDs = new array<int>;
    }
References m_RecipeIDs, and m_Recipes.
Referenced by PluginRecipesManagerBase::GenerateHumanReadableRecipeList(), PluginRecipesManagerBase::GetRecipeIntersection(), PluginRecipesManagerBase::MatchItems(), PluginRecipesManagerBase::PrintCache(), PluginRecipesManagerBase::SortIngredientsInRecipe(), and PluginRecipesManagerBase::WalkRecipes().
DebugPrint()
void DebugPrint ()
Definition at line 97 of file cacheobject.c.
    {
        for(int i = 0; i < m_Recipes.Count();i++)
        {
            Print("recipeID:"+m_Recipes.GetKey(i).ToString());
            Print("mask:"+m_Recipes.GetElement(i).m_Mask.ToString());
            Print("m_BitCount:"+m_Recipes.GetElement(i).m_BitCount.ToString());
        }
    }
References RecipeCacheData::m_BitCount, RecipeCacheData::m_Mask, m_Recipes, and Print().
GetBitCountByRecipeID()
int GetBitCountByRecipeID (int recipe_id)
Definition at line 89 of file cacheobject.c.
    {
        RecipeCacheData cache_data = m_Recipes.Get(recipe_id);
        if(cache_data)
            return cache_data.GetBitCount();
        return 0;
    }
References RecipeCacheData::GetBitCount(), and m_Recipes.
GetMaskByRecipeID()
int GetMaskByRecipeID (int recipe_id)
Definition at line 81 of file cacheobject.c.
    {
        RecipeCacheData cache_data = m_Recipes.Get(recipe_id);
        if(cache_data)
            return cache_data.GetMask();
        return 0;
    }
References RecipeCacheData::GetMask(), and m_Recipes.
GetNumberOfRecipes()
int GetNumberOfRecipes ()
Definition at line 66 of file cacheobject.c.
    {
        return m_Recipes.Count();
    }
References m_Recipes.
GetRecipes()
array< int > GetRecipes ()
Definition at line 71 of file cacheobject.c.
    {
        return m_RecipeIDs;
    }
References m_RecipeIDs.
IsContainRecipe()
bool IsContainRecipe (int recipe_id)
Definition at line 76 of file cacheobject.c.
    {
        return m_Recipes.Contains(recipe_id);
    }
References m_Recipes.
UpdateMask()
void UpdateMask (int recipe_id, int mask)
Definition at line 58 of file cacheobject.c.
    {
        RecipeCacheData data = m_Recipes.Get(recipe_id);
        data.SetMask(data.GetMask() | mask);
    }
References RecipeCacheData::GetMask(), m_Recipes, and RecipeCacheData::SetMask().
Referenced by AddRecipe().
Variable Documentation
int
class RecipeCacheData int
Referenced by CharcoalMdfr::GetDebugTextSimple(), RecipeBase::GetIngredientMaskForItem(), ItemBase::GrowthTimerTick(), ItemBase::Init(), UIScriptedMenu::OnClick(), OnGUI_AnimEvents(), PluginBase::OnRPCMods(), OnStoreSave(), VicinitySlotsContainer::ShowItemsInContainers(), Managed::StartRunningDrops(), UIScriptedMenu::Update(), and VectortoRGBA().
m_RecipeIDs
ref array<int> m_RecipeIDs
Definition at line 33 of file cacheobject.c.
Referenced by AddRecipe(), CacheObject(), and GetRecipes().
m_Recipes
class RecipeCacheData m_Recipes
Referenced by AddRecipe(), CacheObject(), DebugPrint(), GetBitCountByRecipeID(), GetMaskByRecipeID(), GetNumberOfRecipes(), ManBase::Init(), IsContainRecipe(), and UpdateMask().