DayzKode: P:/scripts/4_world/DayZ/entities/vehicles/carscript.c File Reference
carscript.c File Reference
Enumerations
enum CarDoorState { DOORS_MISSING , DOORS_OPEN , DOORS_CLOSED }
Functions
void AddAction (typename actionName)
void BrakeLightsShineOff ()
void BrakeLightsShineOn ()
protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance=1.0)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReleaseAttachment (EntityAI attachment)
protected void CarPartsHealthCheck ()
void CarScript ()
void CheckContactCache ()
Responsible for damaging the car according to contact events from OnContact.
protected void CheckVitalItem (bool isVital, string itemName)
void CleanupEffects ()
void CleanupSound (EffectSound sound)
void CreateCarDestroyedEffect ()
CarLightBase CreateFrontLight ()
CarRearLightBase CreateRearLight ()
void DamageCrew (float dmg)
Responsible for damaging crew in a car crash.
void DashboardShineOff ()
void DashboardShineOn ()
override void EEDelete (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEKilled (Object killer)
override void EEOnCECreate ()
override void EOnPostSimulate (IEntity other, float timeSlice)
void ForceUpdateLightsEnd ()
void ForceUpdateLightsStart ()
protected void GenerateCarHornAINoise (int pState)
override int Get3rdPersonCameraType ()
camera type
vector Get_1_1PointPosWS ()
vector Get_1_2PointPosWS ()
vector Get_2_1PointPosWS ()
vector Get_2_2PointPosWS ()
string GetActionCompNameBrakes ()
string GetActionCompNameCoolant ()
string GetActionCompNameFuel ()
string GetActionCompNameOil ()
float GetActionDistanceBrakes ()
float GetActionDistanceCoolant ()
float GetActionDistanceFuel ()
float GetActionDistanceOil ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
string GetAnimSourceFromSelection (string selection)
vector GetBackPointPosWS ()
ItemBase GetBattery ()
float GetBatteryConsumption ()
float GetBatteryRechargeRate ()
float GetBatteryRuntimeConsumption ()
int GetCarDoorsState (string slotType)
vector GetCoolantPtcPosWS ()
bool GetCrashHeavySound ()
bool GetCrashLightSound ()
int GetCrewIndex (string selection)
override vector GetDefaultHitPosition ()
string GetDoorConditionPointFromSelection (string selection)
string GetDoorInvSlotNameFromSeatPos (int posIdx)
string GetDoorSelectionNameFromSeatPos (int posIdx)
vector GetEnginePointPosWS ()
vector GetEnginePosWS ()
float GetEnviroHeatComfortOverride ()
DEPRECATED
vector GetFrontPointPosWS ()
override float GetLiquidThroughputCoef ()
EntityAI GetRadiator ()
vector GetRefillPointPosWS ()
protected void HandleCarHornSound (ECarHornState pState)
protected void HandleDoorsSound (string animSource, float phase)
void HandleEngineSound (CarEngineSoundState state)
bool HasEngineZoneReceivedHit ()
bool HasRadiator ()
void InitializeActions ()
bool IsHandbrakeActive ()
override bool IsInventoryVisible ()
bool IsMoving ()
bool IsScriptedLightsOn ()
Propper way to get if light is swiched on. Use instead of IsLightsOn().
bool IsVitalCarBattery ()
bool IsVitalEngineBelt ()
bool IsVitalFuelTank ()
bool IsVitalGlowPlug ()
bool IsVitalRadiator ()
bool IsVitalSparkPlug ()
bool IsVitalTruckBattery ()
protected void LeakFluid (CarFluid fluid)
void LeftFrontLightShineOff ()
void LeftFrontLightShineOn ()
override void OnAnimationPhaseStarted (string animSource, float phase)
override void OnAttachmentRuined (EntityAI attachment)
override bool OnBeforeEngineStart ()
bool OnBeforeSwitchLights (bool toOn)
void OnBrakesPressed ()
void OnBrakesReleased ()
override void OnContact (string zoneName, vector localPos, IEntity other, Contact data)
WARNING: Can be called very frequently in one frame, use with caution.
override void OnEngineStart ()
Gets called everytime the engine starts.
override void OnEngineStop ()
Gets called everytime the engine stops.
override void OnFluidChanged (CarFluid fluid, float newValue, float oldValue)
override void OnGearChanged (int newGear, int oldGear)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override void OnUpdate (float dt)
override void OnVariablesSynchronized ()
void PlayCrashHeavySound ()
void PlayCrashLightSound ()
void PlaySound (string soundset, ref EffectSound sound, out bool soundbool)
void PlaySoundEx (string soundset, EffectSound sound, out bool soundbool)
void RemoveAction (typename actionName)
void ReverseLightsShineOff ()
void ReverseLightsShineOn ()
void RightFrontLightShineOff ()
void RightFrontLightShineOn ()
void SetActions ()
void SetCarHornState (int pState)
void SetEngineStarted (bool started)
void SetEngineZoneReceivedHit (bool pState)
void SynchCrashHeavySound (bool play)
void SynchCrashLightSound (bool play)
void TailLightsShineOff ()
void TailLightsShineOn ()
void ToggleHeadlights ()
Switches headlights on/off, including the illumination of the control panel and synchronizes this change to all clients.
CarDoorState TranslateAnimationPhaseToCarDoorState (string animation)
void UpdateHeadlightState ()
void UpdateLights (int new_gear=-1)
void UpdateLightsClient (int newGear=-1)
void UpdateLightsServer (int newGear=-1)
void ~CarScript ()
Variables
private const float BATTERY_UPDATE_DELAY = 100
enum CarDoorState BRAKES_ONLY
static float DROWN_ENGINE_DAMAGE = 350.0
static float DROWN_ENGINE_THRESHOLD = 0.5
enum CarDoorState LEFT
enum CarDoorState LONG
bool m_ActionsInitialize
protected vector m_backPos
protected float m_BatteryConsume = 15
protected float m_BatteryContinuousConsume = 0.25
protected float m_BatteryEnergyStartMin = 5.0
protected float m_BatteryHealth
protected float m_BatteryRecharge = 0.15
private float m_BatteryTimer = 0
protected float m_BrakeAmmount
protected bool m_BrakesArePressed
string m_CarDoorCloseSound = ""
string m_CarDoorOpenSound = ""
string m_CarHornLongSoundName = ""
string m_CarHornShortSoundName = ""
protected ref EffectSound m_CarHornSoundEffect
protected int m_CarHornState
enum CarDoorState m_CarTypeActionsMap = new map<typename, ref TInputActionMap>
ref CarContactCache m_ContactCache
protected float m_CoolantAmmount
protected ref EffVehicleSmoke m_coolantFx
Particles.
protected int m_coolantPtcFx
protected vector m_coolantPtcPos
ref EffectSound m_CrashSoundHeavy
ref EffectSound m_CrashSoundLight
protected float m_dmgContactCoef
static string m_DrownEnginePoint = "drown_engine"
static vector m_DrownEnginePos
protected float m_DrownTime
protected bool m_EngineBeforeStart
protected bool m_EngineDestroyed
protected ref EffVehicleSmoke m_engineFx
protected float m_EngineHealth
protected vector m_enginePos
protected int m_enginePtcFx
protected vector m_enginePtcPos
string m_EngineStartBattery = ""
protected bool m_EngineStartDoOnce
protected bool m_EngineStarted
string m_EngineStartFuel = ""
string m_EngineStartOK = ""
Sounds.
string m_EngineStartPlug = ""
string m_EngineStopFuel = ""
protected bool m_EngineZoneReceivedHit
protected float m_EnviroHeatComfortOverride
protected ref EffVehicleSmoke m_exhaustFx
protected vector m_exhaustPtcDir
protected int m_exhaustPtcFx
protected vector m_exhaustPtcPos
protected bool m_ForceUpdateLights
protected vector m_frontPos
protected float m_FuelAmmount
keeps ammount of each fluid
protected vector m_fuelPos
protected float m_FuelTankHealth
CarLightBase m_Headlight
protected bool m_HeadlightsOn
protected bool m_HeadlightsState
TInputActionMap m_InputActionMap
static string m_LeftHeadlightPoint = "light_left"
static string m_LeftHeadlightTargetPoint = "light_left_dir"
protected ref NoiseParams m_NoisePar
protected NoiseSystem m_NoiseSystem
protected float m_OilAmmount
protected bool m_PlayCrashSoundHeavy
protected bool m_PlayCrashSoundLight
protected float m_PlugHealth
protected EntityAI m_Radiator
protected float m_RadiatorHealth
CarRearLightBase m_RearLight
protected bool m_RearLightType
static string m_ReverseLightPoint = "light_reverse"
static string m_RightHeadlightPoint = "light_right"
static string m_RightHeadlightTargetPoint = "light_right_dir"
protected vector m_side_1_1Pos
protected vector m_side_1_2Pos
protected vector m_side_2_1Pos
protected vector m_side_2_2Pos
protected float m_Time
ref EffectSound m_WindowLarge
ref EffectSound m_WindowSmall
enum CarDoorState NONE
enum CarDoorState OFF = 0
enum CarDoorState REVERSE_ONLY
enum CarDoorState RIGHT
static const int SELECTION_ID_BRAKE_LIGHT_L = 2
static const int SELECTION_ID_BRAKE_LIGHT_R = 3
static const int SELECTION_ID_DASHBOARD_LIGHT = 8
static const int SELECTION_ID_FRONT_LIGHT_L = 0
static const int SELECTION_ID_FRONT_LIGHT_R = 1
static const int SELECTION_ID_REVERSE_LIGHT_L = 4
static const int SELECTION_ID_REVERSE_LIGHT_R = 5
static const int SELECTION_ID_TAIL_LIGHT_L = 6
static const int SELECTION_ID_TAIL_LIGHT_R = 7
enum CarDoorState SHORT = 1
enum CarDoorState START_NO_BATTERY
enum CarDoorState START_NO_FUEL
enum CarDoorState START_NO_SPARKPLUG
enum CarDoorState START_OK
enum CarDoorState STOP_OK
enum CarDoorState typename
Enumeration Type Documentation
CarDoorState
enum CarDoorState
Enumerator
DOORS_MISSING
DOORS_OPEN
DOORS_CLOSED
Definition at line 1 of file carscript.c.
{
    DOORS_MISSING,
    DOORS_OPEN,
    DOORS_CLOSED
}
Function Documentation
AddAction()
void AddAction (typename actionName)
Definition at line 2023 of file carscript.c.
    {
        ActionBase action = ActionManagerBase.GetAction(actionName);
        if (!action)
        {
            Debug.LogError("Action " + actionName + " dosn't exist!");
            return;
        }
        typename ai = action.GetInputType();
        if (!ai)
        {
            m_ActionsInitialize = false;
            return;
        }
        array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
        if (!action_array)
        {
            action_array = new array<ActionBase_Basic>;
            m_InputActionMap.Insert(ai, action_array);
        }
        if ( LogManager.IsActionLogEnable() )
        {
            Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString() , "n/a", "Add action" );
        }
        action_array.Insert(action);
    }
References ActionBase(), Debug::ActionLog(), ActionManagerBase::GetAction(), LogManager::IsActionLogEnable(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
BrakeLightsShineOff()
void BrakeLightsShineOff ()
Definition at line 1600 of file carscript.c.
    {
        string material = ConfigGetString("brakeReflectorMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_L, material);
            SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_R, material);
        }
    }
References ConfigGetString(), SELECTION_ID_BRAKE_LIGHT_L, and SELECTION_ID_BRAKE_LIGHT_R.
Referenced by UpdateLightsServer().
BrakeLightsShineOn()
void BrakeLightsShineOn ()
Definition at line 1589 of file carscript.c.
    {
        string material = ConfigGetString("brakeReflectorMatOn");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_L, material);
            SetObjectMaterial(SELECTION_ID_BRAKE_LIGHT_R, material);
        }
    }
References ConfigGetString(), SELECTION_ID_BRAKE_LIGHT_L, and SELECTION_ID_BRAKE_LIGHT_R.
Referenced by UpdateLightsServer().
CanManipulateSpareWheel()
protected bool CanManipulateSpareWheel (string slotSelectionName)
Definition at line 647 of file carscript.c.
    {
        return false;
    }
CanReachSeatFromDoors()
override bool CanReachSeatFromDoors (string pSeatSelection, vector pFromPos, float pDistance = 1.0)
skip the height for now
Definition at line 1841 of file carscript.c.
    {
        string conPointName = GetDoorConditionPointFromSelection(pSeatSelection);
        if (conPointName.Length() > 0)
        {
            if ( MemoryPointExists(conPointName) )
            {
                vector conPointMS = GetMemoryPointPos(conPointName);
                vector conPointWS = ModelToWorld(conPointMS);
                conPointWS[1] = 0;
                pFromPos[1] = 0;
                if (vector.Distance(pFromPos, conPointWS) <= pDistance)
                {
                    return true;
                }
            }
        }
        return false;
    }
References vector::Distance(), CarScript::GetDoorConditionPointFromSelection(), GetMemoryPointPos(), string::Length(), MemoryPointExists(), and ModelToWorld().
CanReceiveAttachment()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
Definition at line 583 of file carscript.c.
    {
        if (!super.CanReceiveAttachment(attachment, slotId))
            return false;
        InventoryLocation attachmentInventoryLocation = new InventoryLocation();
        attachment.GetInventory().GetCurrentInventoryLocation(attachmentInventoryLocation);
        if (attachmentInventoryLocation.GetParent() == null)
        {
            return true;
        }
        if (attachment && attachment.Type().IsInherited(CarWheel))
        {
            string slotSelectionName;
            InventorySlots.GetSelectionForSlotId(slotId, slotSelectionName);
            switch (slotSelectionName)
            {
            case "wheel_spare_1":
            case "wheel_spare_2":
                return CanManipulateSpareWheel(slotSelectionName);
            break;
            }
        }
        return true;
    }
References CarScript::CanManipulateSpareWheel(), InventoryLocation::GetParent(), and InventorySlots::GetSelectionForSlotId().
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment)
Definition at line 612 of file carscript.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        if (EngineIsOn() && IsMoving())
        {
            return false;
        }
        if (attachment && attachment.Type().IsInherited(CarWheel))
        {
            InventoryLocation attachmentInventoryLocation = new InventoryLocation();
            attachment.GetInventory().GetCurrentInventoryLocation(attachmentInventoryLocation);
            string slotSelectionName;
            InventorySlots.GetSelectionForSlotId(attachmentInventoryLocation.GetSlot(), slotSelectionName);
            switch (slotSelectionName)
            {
            case "wheel_spare_1":
            case "wheel_spare_2":
                return CanManipulateSpareWheel(slotSelectionName);
            break;
            default:
                return false;
            }
        }
        return true;
    }
References CarScript::CanManipulateSpareWheel(), InventorySlots::GetSelectionForSlotId(), InventoryLocation::GetSlot(), and IsMoving().
CarPartsHealthCheck()
protected void CarPartsHealthCheck ()
Definition at line 1715 of file carscript.c.
    {
        if (GetGame().IsServer())
        {
            if (HasRadiator())
            {
                m_RadiatorHealth = GetRadiator().GetHealth01("", "");
            }
            else
            {
                m_RadiatorHealth = 0;
            }
            m_EngineHealth      = GetHealth01("Engine", "");
            m_FuelTankHealth    = GetHealth01("FuelTank", "");
        }
    }
References GetGame(), GetHealth01(), GetRadiator(), HasRadiator(), m_EngineHealth, m_FuelTankHealth, and m_RadiatorHealth.
Referenced by EOnPostSimulate().
CarScript()
void CarScript ()
Definition at line 197 of file carscript.c.
    {
        SetEventMask(/*EntityEvent.CONTACT |*/ EntityEvent.POSTSIMULATE);
        m_ContactCache = new CarContactCache;
        m_Time = 0;
        // sets max health for all components at init
        m_EngineHealth = 1;
        m_FuelTankHealth = 1;
        m_RadiatorHealth = -1;
        m_BatteryHealth = -1;
        m_PlugHealth = -1;
        m_enginePtcFx = -1;
        m_coolantPtcFx = -1;
        m_exhaustPtcFx = -1;
        m_dmgContactCoef = 0;
        m_EnviroHeatComfortOverride = 0;
        m_PlayCrashSoundLight = false;
        m_PlayCrashSoundHeavy = false;
        m_CarHornState = ECarHornState.OFF;
        RegisterNetSyncVariableBool("m_HeadlightsOn");
        RegisterNetSyncVariableBool("m_BrakesArePressed");
        RegisterNetSyncVariableBool("m_ForceUpdateLights");
        RegisterNetSyncVariableBool("m_EngineZoneReceivedHit");
        RegisterNetSyncVariableBoolSignal("m_PlayCrashSoundLight");
        RegisterNetSyncVariableBoolSignal("m_PlayCrashSoundHeavy");
        RegisterNetSyncVariableInt("m_CarHornState", ECarHornState.OFF, ECarHornState.LONG);
        if ( MemoryPointExists("ptcExhaust_end") )
        {
            m_exhaustPtcPos = GetMemoryPointPos("ptcExhaust_end");
            if ( MemoryPointExists("ptcExhaust_start") )
            {
                vector exhaustStart = GetMemoryPointPos("ptcExhaust_start");
                vector tempOri = vector.Direction( exhaustStart, m_exhaustPtcPos);
                m_exhaustPtcDir[0] = -tempOri[2];
                m_exhaustPtcDir[1] = tempOri[1];
                m_exhaustPtcDir[2] = tempOri[0];
                m_exhaustPtcDir = m_exhaustPtcDir.Normalized().VectorToAngles();
            }
        }
        else
        {
            m_exhaustPtcPos = "0 0 0";
            m_exhaustPtcDir = "1 1 1";
        }
        if ( MemoryPointExists("ptcEnginePos") )
            m_enginePtcPos = GetMemoryPointPos("ptcEnginePos");
        else
            m_enginePtcPos = "0 0 0";
        if ( MemoryPointExists("ptcCoolantPos") )
            m_coolantPtcPos = GetMemoryPointPos("ptcCoolantPos");
        else
            m_coolantPtcPos = "0 0 0";
        if ( MemoryPointExists("refill") )
            m_fuelPos = GetMemoryPointPos("refill");
        else
            m_fuelPos = "0 0 0";
        if ( MemoryPointExists("drown_engine") )
            m_DrownEnginePos = GetMemoryPointPos("drown_engine");
        else
            m_DrownEnginePos = "0 0 0";
        if ( MemoryPointExists("dmgZone_engine") )
            m_enginePos = GetMemoryPointPos("dmgZone_engine");
        else
            m_enginePos = "0 0 0";
        if ( MemoryPointExists("dmgZone_front") )
            m_frontPos = GetMemoryPointPos("dmgZone_front");
        else
            m_frontPos = "0 0 0";
        if ( MemoryPointExists("dmgZone_back") )
            m_backPos = GetMemoryPointPos("dmgZone_back");
        else
            m_backPos = "0 0 0";
        if ( MemoryPointExists("dmgZone_fender_1_1") )
            m_side_1_1Pos = GetMemoryPointPos("dmgZone_fender_1_1");
        else
            m_side_1_1Pos = "0 0 0";
        if ( MemoryPointExists("dmgZone_fender_1_2") )
            m_side_1_2Pos = GetMemoryPointPos("dmgZone_fender_1_2");
        else
            m_side_1_2Pos = "0 0 0";
        if ( MemoryPointExists("dmgZone_fender_2_1") )
            m_side_2_1Pos = GetMemoryPointPos("dmgZone_fender_2_1");
        else
            m_side_2_1Pos = "0 0 0";
        if ( MemoryPointExists("dmgZone_fender_2_2") )
            m_side_2_2Pos = GetMemoryPointPos("dmgZone_fender_2_2");
        else
            m_side_2_2Pos = "0 0 0";
    }
References vector::Direction(), GetMemoryPointPos(), m_backPos, m_BatteryHealth, m_CarHornState, m_ContactCache, m_coolantPtcFx, m_coolantPtcPos, m_dmgContactCoef, m_DrownEnginePos, m_EngineHealth, m_enginePos, m_enginePtcFx, m_enginePtcPos, m_EnviroHeatComfortOverride, m_exhaustPtcDir, m_exhaustPtcFx, m_exhaustPtcPos, m_frontPos, m_fuelPos, m_FuelTankHealth, m_PlayCrashSoundHeavy, m_PlayCrashSoundLight, m_PlugHealth, m_RadiatorHealth, m_side_1_1Pos, m_side_1_2Pos, m_side_2_1Pos, m_side_2_2Pos, m_Time, MemoryPointExists(), vector::Normalized(), and vector::VectorToAngles().
CheckContactCache()
void CheckContactCache ()
Responsible for damaging the car according to contact events from OnContact.
Definition at line 912 of file carscript.c.
    {
        int contactZonesCount = m_ContactCache.Count();
        if (contactZonesCount == 0)
            return;
        for (int i = 0; i < contactZonesCount; ++i)
        {
            string zoneName = m_ContactCache.GetKey(i);
            array<ref CarContactData> data = m_ContactCache[zoneName];
            float dmg;
            int contactCount = data.Count();
            for (int j = 0; j < contactCount; ++j)
                dmg = data[j].impulse * m_dmgContactCoef;
            if ( dmg < GameConstants.CARS_CONTACT_DMG_MIN )
                continue;
            int pddfFlags;
            if (dmg < GameConstants.CARS_CONTACT_DMG_THRESHOLD)
            {
                //Print(string.Format("[Vehiles:Damage]:: DMG %1 to the %2 zone is SMALL (threshold: %3), SPEED: %4", dmg, zoneName, GameConstants.CARS_CONTACT_DMG_THRESHOLD, GetSpeedometer() ));
                SynchCrashLightSound(true);
                pddfFlags = ProcessDirectDamageFlags.NO_TRANSFER;
            }
            else
            {
                //Print(string.Format("[Vehiles:Damage]:: DMG %1 to the %2 zone is BIG (threshold: %3), SPEED: %4", dmg, zoneName, GameConstants.CARS_CONTACT_DMG_THRESHOLD, GetSpeedometer() ));
                DamageCrew(dmg);
                SynchCrashHeavySound(true);
                pddfFlags = 0;
            }
            #ifdef DEVELOPER
            m_DebugContactDamageMessage += string.Format("%1: %2\n", zoneName, dmg);
            #endif
            ProcessDirectDamage(DT_CUSTOM, null, zoneName, "EnviroDmg", "0 0 0", dmg, pddfFlags);
        }
        UpdateHeadlightState();
        UpdateLights();
        m_ContactCache.Clear();
    }
References GameConstants::CARS_CONTACT_DMG_MIN, GameConstants::CARS_CONTACT_DMG_THRESHOLD, DamageCrew(), string::Format(), m_ContactCache, m_dmgContactCoef, ProcessDirectDamage(), SynchCrashHeavySound(), SynchCrashLightSound(), UpdateHeadlightState(), and UpdateLights().
Referenced by EOnPostSimulate().
CheckVitalItem()
protected void CheckVitalItem (bool isVital, string itemName)
Definition at line 1679 of file carscript.c.
    {
        if ( !isVital )
            return;
        EntityAI item = FindAttachmentBySlotName(itemName);
        if ( !item )
            EngineStop();
        else if ( item.IsRuined() )
            EngineStop();
    }
Referenced by EOnPostSimulate().
CleanupEffects()
void CleanupEffects ()
Definition at line 397 of file carscript.c.
    {
        SEffectManager.DestroyEffect(m_coolantFx);
        SEffectManager.DestroyEffect(m_exhaustFx);
        SEffectManager.DestroyEffect(m_engineFx);
        if (m_Headlight)
            m_Headlight.Destroy();
        if (m_RearLight)
            m_RearLight.Destroy();
        SEffectManager.DestroyEffect(m_CrashSoundLight);
        SEffectManager.DestroyEffect(m_CrashSoundHeavy);
        SEffectManager.DestroyEffect(m_WindowSmall);
        SEffectManager.DestroyEffect(m_WindowLarge);
        CleanupSound(m_CarHornSoundEffect);
    }
References CleanupSound(), SEffectManager::DestroyEffect(), m_CarHornSoundEffect, m_coolantFx, m_CrashSoundHeavy, m_CrashSoundLight, m_engineFx, m_exhaustFx, m_Headlight, m_RearLight, m_WindowLarge, and m_WindowSmall.
Referenced by EEDelete(), and ~CarScript().
CleanupSound()
void CleanupSound (EffectSound sound)
Definition at line 416 of file carscript.c.
    {
        SEffectManager.DestroyEffect(sound);
    }
References SEffectManager::DestroyEffect().
Referenced by CleanupEffects(), and HandleCarHornSound().
CreateCarDestroyedEffect()
void CreateCarDestroyedEffect ()
Definition at line 439 of file carscript.c.
    {
        if ( !SEffectManager.IsEffectExist( m_enginePtcFx ) && GetGame().GetWaterDepth( GetEnginePosWS() ) <= 0 )
        {
            m_engineFx = new EffEngineSmoke();
            m_engineFx.SetParticleStateHeavy();
            m_enginePtcFx = SEffectManager.PlayOnObject( m_engineFx, this, m_enginePtcPos, Vector(0,0,0));
        }
    }
References GetEnginePosWS(), GetGame(), SEffectManager::IsEffectExist(), m_engineFx, m_enginePtcFx, m_enginePtcPos, SEffectManager::PlayOnObject(), EffVehicleSmoke::SetParticleStateHeavy(), and Vector().
Referenced by EEHealthLevelChanged().
CreateFrontLight()
CarLightBase CreateFrontLight ()
Definition at line 1674 of file carscript.c.
    {
        return CarLightBase.Cast( ScriptedLightBase.CreateLight(OffroadHatchbackFrontLight) ); // just a default value
    }
CreateRearLight()
CarRearLightBase CreateRearLight ()
Definition at line 1668 of file carscript.c.
    {
        return CarRearLightBase.Cast( ScriptedLightBase.CreateLight(OffroadHatchbackFrontLight) ); // just a default value
    }
DamageCrew()
void DamageCrew (float dmg)
Responsible for damaging crew in a car crash.
Definition at line 964 of file carscript.c.
    {
        for ( int c = 0; c < CrewSize(); ++c )
        {
            Human crew = CrewMember( c );
            if ( !crew )
                continue;
            PlayerBase player;
            if ( Class.CastTo(player, crew ) )
            {
                if ( dmg > GameConstants.CARS_CONTACT_DMG_KILLCREW )
                {
                    //Print(string.Format("KILL player: %1", dmg));
                    player.SetHealth(0.0);
                }
                else
                {
                    float shockTemp = Math.InverseLerp(GameConstants.CARS_CONTACT_DMG_THRESHOLD, GameConstants.CARS_CONTACT_DMG_KILLCREW, dmg);
                    float shock = Math.Lerp( 50, 110, shockTemp );
                    float hp = Math.Lerp( 2, 99, shockTemp );
                    //Print(string.Format("[Vehiles:Damage]:: Damage to player: %1", hp));
                    //Print(string.Format("[Vehiles:Damage]:: Shock to player: %1", shock));
                    // These should ideally be ProcessDirectDamage...
                    player.AddHealth("", "Shock", -shock );
                    player.AddHealth("", "Health", -hp );
                }
            }
        }
    }
References GameConstants::CARS_CONTACT_DMG_KILLCREW, GameConstants::CARS_CONTACT_DMG_THRESHOLD, Class::CastTo(), Math::InverseLerp(), and Math::Lerp().
Referenced by CheckContactCache().
DashboardShineOff()
void DashboardShineOff ()
Definition at line 1657 of file carscript.c.
    {
        string material = ConfigGetString("dashboardMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_DASHBOARD_LIGHT, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_DASHBOARD_LIGHT.
Referenced by UpdateLightsServer().
DashboardShineOn()
void DashboardShineOn ()
Definition at line 1647 of file carscript.c.
    {
        string material = ConfigGetString("dashboardMatOn");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_DASHBOARD_LIGHT, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_DASHBOARD_LIGHT.
Referenced by UpdateLightsServer().
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 383 of file carscript.c.
    {
        #ifndef SERVER
        CleanupEffects();
        #endif
    }
References CleanupEffects().
EEHealthLevelChanged()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
Definition at line 2072 of file carscript.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        if (newLevel == GameConstants.STATE_RUINED && oldLevel != newLevel)
        {
            bool dummy;
            switch ( zone )
            {
            case "WindowLR":
            case "WindowRR":
                if (m_Initialized)
                {
                    PlaySoundEx("offroad_hit_window_small_SoundSet", m_WindowSmall, dummy);
                }
            break;
            case "WindowFront":
            case "WindowBack":
            case "WindowFrontLeft":
            case "WindowFrontRight":
                if (m_Initialized)
                {
                    PlaySoundEx("offroad_hit_window_large_SoundSet", m_WindowLarge, dummy);
                }
            break;
            case "Engine":
                #ifndef SERVER
                CreateCarDestroyedEffect();
                #endif
            break;
            }
        }
    }
References CreateCarDestroyedEffect(), m_Initialized, m_WindowLarge, m_WindowSmall, PlaySoundEx(), and GameConstants::STATE_RUINED.
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
Definition at line 373 of file carscript.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        ForceUpdateLightsStart();
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(ForceUpdateLightsEnd, 100, false);
        SetEngineZoneReceivedHit(dmgZone == "Engine");
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), component, ForceUpdateLightsEnd(), ForceUpdateLightsStart(), CGame::GetCallQueue(), GetGame(), and SetEngineZoneReceivedHit().
EEInit()
override void EEInit ()
Definition at line 308 of file carscript.c.
    {
        super.EEInit();
        if (GetGame().IsServer())
        {
            m_NoiseSystem = GetGame().GetNoiseSystem();
            if (m_NoiseSystem && !m_NoisePar)
            {
                m_NoisePar = new NoiseParams();
                m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseCarHorn");
            }
        }
    }
References GetGame(), CGame::GetNoiseSystem(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name)
Definition at line 449 of file carscript.c.
    {
        super.EEItemAttached(item, slot_name);
        switch (slot_name)
        {
        case "Reflector_1_1":
            if (GetGame().IsServer())
            {
                SetHealth("Reflector_1_1", "Health", item.GetHealth());
            }
        break;
        case "Reflector_2_1":
            if (GetGame().IsServer())
            {
                SetHealth("Reflector_2_1", "Health", item.GetHealth());
            }
        break;
        case "CarBattery":
        case "TruckBattery":
            if (GetGame().IsServer())
            {
                m_BatteryHealth = item.GetHealth01();
            }
        break;
        case "SparkPlug":
        case "GlowPlug":
            if (GetGame().IsServer())
            {
                m_PlugHealth = item.GetHealth01();
            }
        break;
        case "CarRadiator":
            if (GetGame().IsServer())
            {
                m_RadiatorHealth = item.GetHealth01();
            }
            m_Radiator = item;
        break;
        }
        if (GetGame().IsServer())
        {
            Synchronize();
        }
        UpdateHeadlightState();
        UpdateLights();
    }
References GetGame(), m_BatteryHealth, m_PlugHealth, m_Radiator, m_RadiatorHealth, SetHealth(), Synchronize(), UpdateHeadlightState(), and UpdateLights().
EEItemDetached()
override void EEItemDetached (EntityAI item, string slot_name)
Definition at line 524 of file carscript.c.
    {
        switch (slot_name)
        {
        case "CarBattery":
        case "TruckBattery":
            m_BatteryHealth = -1;
            if (GetGame().IsServer())
            {
                if (EngineIsOn())
                {
                    EngineStop();
                }
                if (IsScriptedLightsOn())
                {
                    ToggleHeadlights();
                }
            }
        break;
        case "SparkPlug":
        case "GlowPlug":
            m_PlugHealth = -1;
            if (GetGame().IsServer() && EngineIsOn())
            {
                EngineStop();
            }
        break;
        case "CarRadiator":
            m_Radiator = null;
            if (GetGame().IsServer())
            {
                LeakAll(CarFluid.COOLANT);
                if (m_DamageZoneMap.Contains("Radiator"))
                {
                    SetHealth("Radiator", "Health", 0);
                }
            }
        break;
        }
        if (GetGame().IsServer())
        {
            Synchronize();
        }
        UpdateHeadlightState();
        UpdateLights();
    }
References GetGame(), IsScriptedLightsOn(), m_BatteryHealth, m_PlugHealth, m_Radiator, SetHealth(), Synchronize(), ToggleHeadlights(), UpdateHeadlightState(), and UpdateLights().
EEKilled()
override void EEKilled (Object killer)
Definition at line 889 of file carscript.c.
    {
        super.EEKilled(killer);
        m_EngineDestroyed = true;
    }
References m_EngineDestroyed.
EEOnCECreate()
override void EEOnCECreate ()
Definition at line 2108 of file carscript.c.
    {
        float maxVolume = GetFluidCapacity( CarFluid.FUEL );
        float amount = Math.RandomFloat(0.0, maxVolume * 0.35 );
        Fill( CarFluid.FUEL, amount );
    }
References Math::RandomFloat().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice)
actions runned when the engine on
leaking of coolant from radiator when damaged
Definition at line 652 of file carscript.c.
    {
        m_Time += timeSlice;
        if (GetGame().IsServer())
        {
            CheckContactCache();
            #ifdef DEVELOPER
            m_DebugMessageCleanTime += timeSlice;
            if (m_DebugMessageCleanTime >= DEBUG_MESSAGE_CLEAN_TIME_SECONDS)
            {
                m_DebugMessageCleanTime = 0;
                m_DebugContactDamageMessage = "";
            }
            #endif
        }
        if ( m_Time >= GameConstants.CARS_FLUIDS_TICK )
        {
            m_Time = 0;
            CarPartsHealthCheck();
            //First of all check if the car should stop the engine
            if (GetGame().IsServer() && EngineIsOn())
            {
                if ( GetFluidFraction(CarFluid.FUEL) <= 0 || m_EngineHealth <= 0 )
                    EngineStop();
                CheckVitalItem(IsVitalCarBattery(), "CarBattery");
                CheckVitalItem(IsVitalTruckBattery(), "TruckBattery");
                CheckVitalItem(IsVitalSparkPlug(), "SparkPlug");
                CheckVitalItem(IsVitalGlowPlug(), "GlowPlug");
            }
            if (GetGame().IsServer())
            {
                if (IsVitalFuelTank())
                {
                    if (m_FuelTankHealth == GameConstants.DAMAGE_RUINED_VALUE && m_EngineHealth > GameConstants.DAMAGE_RUINED_VALUE)
                    {
                        SetHealth("Engine", "Health", GameConstants.DAMAGE_RUINED_VALUE);
                    }
                }
            }
            if ( EngineIsOn() )
            {
                if ( GetGame().IsServer() )
                {
                    float dmg;
                    if ( EngineGetRPM() >= EngineGetRPMRedline() )
                    {
                        if (EngineGetRPM() > EngineGetRPMMax())
                            AddHealth( "Engine", "Health", -GetMaxHealth("Engine", "") * 0.05 ); //CAR_RPM_DMG
                        dmg = EngineGetRPM() * 0.001 * Math.RandomFloat( 0.02, 1.0 );  //CARS_TICK_DMG_MIN; //CARS_TICK_DMG_MAX
                        ProcessDirectDamage(DamageType.CUSTOM, null, "Engine", "EnviroDmg", vector.Zero, dmg);
                        SetEngineZoneReceivedHit(true);
                    }
                    else
                    {
                        SetEngineZoneReceivedHit(false);
                    }
                    if ( IsVitalRadiator() )
                    {
                        if ( GetFluidFraction(CarFluid.COOLANT) > 0 && m_RadiatorHealth < 0.5 ) //CARS_LEAK_THRESHOLD
                            LeakFluid( CarFluid.COOLANT );
                    }
                    if ( GetFluidFraction(CarFluid.FUEL) > 0 && m_FuelTankHealth < GameConstants.DAMAGE_DAMAGED_VALUE )
                        LeakFluid( CarFluid.FUEL );
                    if ( GetFluidFraction(CarFluid.BRAKE) > 0 && m_EngineHealth < GameConstants.DAMAGE_DAMAGED_VALUE )
                        LeakFluid( CarFluid.BRAKE );
                    if ( GetFluidFraction(CarFluid.OIL) > 0 && m_EngineHealth < GameConstants.DAMAGE_DAMAGED_VALUE )
                        LeakFluid( CarFluid.OIL );
                    if ( m_EngineHealth < 0.25 )
                        LeakFluid( CarFluid.OIL );
                    if ( IsVitalRadiator() )
                    {
                        if ( GetFluidFraction( CarFluid.COOLANT ) < 0.5 && GetFluidFraction( CarFluid.COOLANT ) >= 0 )
{
                            dmg = ( 1 - GetFluidFraction(CarFluid.COOLANT) ) * Math.RandomFloat( 0.02, 10.00 );  //CARS_DMG_TICK_MIN_COOLANT; //CARS_DMG_TICK_MAX_COOLANT
                            AddHealth( "Engine", "Health", -dmg );
                            SetEngineZoneReceivedHit(true);
                        }
                    }
                }
                //FX only on Client and in Single
                if (!GetGame().IsDedicatedServer())
                {
                    if (!SEffectManager.IsEffectExist(m_exhaustPtcFx))
                    {
                        m_exhaustFx = new EffExhaustSmoke();
                        m_exhaustPtcFx = SEffectManager.PlayOnObject( m_exhaustFx, this, m_exhaustPtcPos, m_exhaustPtcDir );
                        m_exhaustFx.SetParticleStateLight();
                    }
                    if (IsVitalRadiator() && GetFluidFraction(CarFluid.COOLANT) < 0.5)
                    {
                        if (!SEffectManager.IsEffectExist(m_coolantPtcFx))
{
                            m_coolantFx = new EffCoolantSteam();
                            m_coolantPtcFx = SEffectManager.PlayOnObject(m_coolantFx, this, m_coolantPtcPos, vector.Zero);
                        }
                        if (m_coolantFx)
{
                            if (GetFluidFraction(CarFluid.COOLANT) > 0)
                                m_coolantFx.SetParticleStateLight();
                            else
                                m_coolantFx.SetParticleStateHeavy();
                        }
                    }
                    else
                    {
                        if (SEffectManager.IsEffectExist(m_coolantPtcFx))
                            SEffectManager.Stop(m_coolantPtcFx);
                    }
                }
            }
            else
            {
                //FX only on Client and in Single
                if ( !GetGame().IsDedicatedServer() )
                {
                    if (SEffectManager.IsEffectExist(m_exhaustPtcFx))
                    {
                        SEffectManager.Stop(m_exhaustPtcFx);
                        m_exhaustPtcFx = -1;
                    }
                    if (SEffectManager.IsEffectExist(m_coolantPtcFx))
                    {
                        SEffectManager.Stop(m_coolantPtcFx);
                        m_coolantPtcFx = -1;
                    }
                }
            }
        }
    }
References AddHealth(), CarPartsHealthCheck(), GameConstants::CARS_FLUIDS_TICK, CheckContactCache(), CheckVitalItem(), GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GetGame(), GetMaxHealth(), SEffectManager::IsEffectExist(), CarScript::IsVitalCarBattery(), IsVitalFuelTank(), CarScript::IsVitalGlowPlug(), CarScript::IsVitalRadiator(), CarScript::IsVitalSparkPlug(), CarScript::IsVitalTruckBattery(), LeakFluid(), m_coolantFx, m_coolantPtcFx, m_coolantPtcPos, m_EngineHealth, m_exhaustFx, m_exhaustPtcDir, m_exhaustPtcFx, m_exhaustPtcPos, m_FuelTankHealth, m_RadiatorHealth, m_Time, SEffectManager::PlayOnObject(), ProcessDirectDamage(), Math::RandomFloat(), SetEngineZoneReceivedHit(), SetHealth(), EffVehicleSmoke::SetParticleStateHeavy(), EffVehicleSmoke::SetParticleStateLight(), SEffectManager::Stop(), and vector::Zero.
ForceUpdateLightsEnd()
void ForceUpdateLightsEnd ()
Definition at line 2126 of file carscript.c.
    {
        if (m_ForceUpdateLights)
        {
            m_ForceUpdateLights = false;
            SetSynchDirty();
        }
    }
References m_ForceUpdateLights.
Referenced by EEHitBy().
ForceUpdateLightsStart()
void ForceUpdateLightsStart ()
Definition at line 2117 of file carscript.c.
    {
        if (!m_ForceUpdateLights)
        {
            m_ForceUpdateLights = true;
            SetSynchDirty();
        }
    }
References m_ForceUpdateLights.
Referenced by EEHitBy().
GenerateCarHornAINoise()
protected void GenerateCarHornAINoise (int pState)
Definition at line 2176 of file carscript.c.
    {
        if (pState != ECarHornState.OFF)
        {
            if (m_NoiseSystem && m_NoisePar)
            {
                float noiseMultiplier = 1.0;
                if (pState == ECarHornState.LONG)
                    noiseMultiplier = 2.0;
                m_NoiseSystem.AddNoiseTarget(GetPosition(), 5, m_NoisePar, noiseMultiplier);
            }
        }
    }
References NoiseSystem::AddNoiseTarget(), GetPosition, m_NoisePar, and m_NoiseSystem.
Referenced by SetCarHornState().
Get3rdPersonCameraType()
override int Get3rdPersonCameraType ()
camera type
Definition at line 1921 of file carscript.c.
    {
        return DayZPlayerCameras.DAYZCAMERA_3RD_VEHICLE;
    }
References DayZPlayerCameras::DAYZCAMERA_3RD_VEHICLE.
Get_1_1PointPosWS()
vector Get_1_1PointPosWS ()
Definition at line 350 of file carscript.c.
    {
        return ModelToWorld( m_side_1_1Pos );
    }
References m_side_1_1Pos, and ModelToWorld().
Get_1_2PointPosWS()
vector Get_1_2PointPosWS ()
Definition at line 354 of file carscript.c.
    {
        return ModelToWorld( m_side_1_2Pos );
    }
References m_side_1_2Pos, and ModelToWorld().
Get_2_1PointPosWS()
vector Get_2_1PointPosWS ()
Definition at line 358 of file carscript.c.
    {
        return ModelToWorld( m_side_2_1Pos );
    }
References m_side_2_1Pos, and ModelToWorld().
Get_2_2PointPosWS()
vector Get_2_2PointPosWS ()
Definition at line 362 of file carscript.c.
    {
        return ModelToWorld( m_side_2_2Pos );
    }
References m_side_2_2Pos, and ModelToWorld().
GetActionCompNameBrakes()
string GetActionCompNameBrakes ()
Definition at line 1980 of file carscript.c.
    {
        return "carradiator";
    }
GetActionCompNameCoolant()
string GetActionCompNameCoolant ()
Definition at line 1949 of file carscript.c.
    {
        return "radiator";
    }
GetActionCompNameFuel()
string GetActionCompNameFuel ()
Definition at line 1959 of file carscript.c.
    {
        return "refill";
    }
GetActionCompNameOil()
string GetActionCompNameOil ()
Definition at line 1969 of file carscript.c.
    {
        //return "refill";
        return "carradiator";
    }
GetActionDistanceBrakes()
float GetActionDistanceBrakes ()
Definition at line 1985 of file carscript.c.
    {
        return 2.0;
    }
GetActionDistanceCoolant()
float GetActionDistanceCoolant ()
Definition at line 1954 of file carscript.c.
    {
        return 2.0;
    }
GetActionDistanceFuel()
float GetActionDistanceFuel ()
Definition at line 1964 of file carscript.c.
    {
        return 1.5;
    }
GetActionDistanceOil()
float GetActionDistanceOil ()
Definition at line 1975 of file carscript.c.
    {
        return 2.0;
    }
GetActions()
override void GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 2002 of file carscript.c.
    {
        if (!m_ActionsInitialize)
        {
            m_ActionsInitialize = true;
            InitializeActions();
        }
        actions = m_InputActionMap.Get(action_input_type);
    }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetAnimSourceFromSelection()
string GetAnimSourceFromSelection (string selection)
Definition at line 1800 of file carscript.c.
    {
        return "";
    }
GetBackPointPosWS()
vector GetBackPointPosWS ()
Definition at line 346 of file carscript.c.
    {
        return ModelToWorld( m_backPos );
    }
References m_backPos, and ModelToWorld().
GetBattery()
ItemBase GetBattery ()
Definition at line 2151 of file carscript.c.
    {
        if (IsVitalCarBattery())
        {
            return ItemBase.Cast(FindAttachmentBySlotName("CarBattery"));
        }
        else if (IsVitalTruckBattery())
        {
            return ItemBase.Cast(FindAttachmentBySlotName("TruckBattery"));
        }
        return null;
    }
References CarScript::IsVitalCarBattery(), and CarScript::IsVitalTruckBattery().
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnUpdate().
GetBatteryConsumption()
float GetBatteryConsumption ()
Definition at line 2136 of file carscript.c.
    {
        return m_BatteryConsume;
    }
References m_BatteryConsume.
Referenced by OnEngineStart().
GetBatteryRechargeRate()
float GetBatteryRechargeRate ()
Definition at line 2146 of file carscript.c.
    {
        return -m_BatteryRecharge;
    }
References m_BatteryRecharge.
Referenced by OnUpdate().
GetBatteryRuntimeConsumption()
float GetBatteryRuntimeConsumption ()
Definition at line 2141 of file carscript.c.
    {
        return m_BatteryContinuousConsume;
    }
References m_BatteryContinuousConsume.
Referenced by OnUpdate().
GetCarDoorsState()
int GetCarDoorsState (string slotType)
Definition at line 1932 of file carscript.c.
    {
        return -1;
    }
Referenced by CarScript::CanDisplayAttachmentCategory(), CarScript::CanDisplayCargo(), CarScript::CanManipulateSpareWheel(), CarScript::CanReleaseAttachment(), CarScript::CrewCanGetThrough(), and CarScript::OnSound().
GetCoolantPtcPosWS()
vector GetCoolantPtcPosWS ()
Definition at line 328 of file carscript.c.
    {
        return ModelToWorld( m_coolantPtcPos );
    }
References m_coolantPtcPos, and ModelToWorld().
GetCrashHeavySound()
bool GetCrashHeavySound ()
Definition at line 1752 of file carscript.c.
    {
        return m_PlayCrashSoundHeavy;
    }
References m_PlayCrashSoundHeavy.
Referenced by OnVariablesSynchronized().
GetCrashLightSound()
bool GetCrashLightSound ()
Definition at line 1733 of file carscript.c.
    {
        return m_PlayCrashSoundLight;
    }
References m_PlayCrashSoundLight.
Referenced by OnVariablesSynchronized().
GetCrewIndex()
int GetCrewIndex (string selection)
Definition at line 1836 of file carscript.c.
    {
        return -1;
    }
GetDefaultHitPosition()
override vector GetDefaultHitPosition ()
Definition at line 2191 of file carscript.c.
    {
        return vector.Zero;
    }
References vector::Zero.
GetDoorConditionPointFromSelection()
string GetDoorConditionPointFromSelection (string selection)
Definition at line 1805 of file carscript.c.
    {
        switch( selection )
        {
            case "seat_driver":
                return "seat_con_1_1";
            break;
            case "seat_codriver":
                return "seat_con_2_1";
            break;
            case "seat_cargo1":
                return "seat_con_1_2";
            break;
            case "seat_cargo2":
                return "seat_con_2_2";
            break;
        }
        return "";
    }
GetDoorInvSlotNameFromSeatPos()
string GetDoorInvSlotNameFromSeatPos (int posIdx)
Definition at line 1831 of file carscript.c.
    {
        return "";
    }
GetDoorSelectionNameFromSeatPos()
string GetDoorSelectionNameFromSeatPos (int posIdx)
Definition at line 1826 of file carscript.c.
    {
        return "";
    }
GetEnginePointPosWS()
vector GetEnginePointPosWS ()
Definition at line 338 of file carscript.c.
    {
        return ModelToWorld( m_enginePos );
    }
References m_enginePos, and ModelToWorld().
GetEnginePosWS()
vector GetEnginePosWS ()
Definition at line 323 of file carscript.c.
    {
        return ModelToWorld( m_DrownEnginePos );
    }
References m_DrownEnginePos, and ModelToWorld().
Referenced by CreateCarDestroyedEffect(), and OnUpdate().
GetEnviroHeatComfortOverride()
float GetEnviroHeatComfortOverride ()
DEPRECATED
GetFrontPointPosWS()
vector GetFrontPointPosWS ()
Definition at line 342 of file carscript.c.
    {
        return ModelToWorld( m_frontPos );
    }
References m_frontPos, and ModelToWorld().
GetLiquidThroughputCoef()
override float GetLiquidThroughputCoef ()
Definition at line 367 of file carscript.c.
    {
        return LIQUID_THROUGHPUT_CAR_DEFAULT;
    }
References LIQUID_THROUGHPUT_CAR_DEFAULT.
GetRadiator()
EntityAI GetRadiator ()
Definition at line 1905 of file carscript.c.
    {
        return m_Radiator;
    }
References m_Radiator.
Referenced by CarPartsHealthCheck().
GetRefillPointPosWS()
vector GetRefillPointPosWS ()
Definition at line 333 of file carscript.c.
    {
        return ModelToWorld( m_fuelPos );
    }
References m_fuelPos, and ModelToWorld().
HandleCarHornSound()
protected void HandleCarHornSound (ECarHornState pState)
Definition at line 1052 of file carscript.c.
    {
        switch (pState)
        {
        case ECarHornState.SHORT:
            PlaySoundSet(m_CarHornSoundEffect, m_CarHornShortSoundName, 0, 0);
        break;
        case ECarHornState.LONG:
            PlaySoundSet(m_CarHornSoundEffect, m_CarHornLongSoundName, 0, 0, true);
        break;
        default:
            CleanupSound(m_CarHornSoundEffect);
        break;
        }
    }
References CleanupSound(), m_CarHornLongSoundName, m_CarHornShortSoundName, m_CarHornSoundEffect, and PlaySoundSet().
Referenced by OnVariablesSynchronized().
HandleDoorsSound()
protected void HandleDoorsSound (string animSource, float phase)
Definition at line 1023 of file carscript.c.
    {
        switch (animSource)
        {
        case "doorsdriver":
        case "doorscodriver":
        case "doorscargo1":
        case "doorscargo2":
        case "doorshood":
        case "doorstrunk":
            EffectSound sound;
            if (phase == 0)
            {
                sound = SEffectManager.PlaySound(m_CarDoorOpenSound, GetPosition());
            }
            else
            {
                sound = SEffectManager.PlaySound(m_CarDoorCloseSound, GetPosition());
            }
            if (sound)
            {
                sound.SetAutodestroy(true);
            }
        break;
        }
    }
References GetPosition, m_CarDoorCloseSound, m_CarDoorOpenSound, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnAnimationPhaseStarted().
HandleEngineSound()
void HandleEngineSound (CarEngineSoundState state)
postpone the engine sound played from c++ on soundcontroller (via OnSound override)
Definition at line 1068 of file carscript.c.
    {
        #ifndef SERVER
        PlayerBase player = null;
        EffectSound sound = null;
        WaveKind waveKind = WaveKind.WAVEEFFECT;
        switch (state)
        {
        case CarEngineSoundState.START_OK:
            // play different sound based on selected camera
            if (Class.CastTo(player, CrewMember(0)))
            {
                if (!player.IsCameraInsideVehicle())
                {
                    waveKind = WaveKind.WAVEEFFECTEX;
                }
                sound = SEffectManager.CreateSound(m_EngineStartOK, ModelToWorld(GetEnginePos()));
                if (sound)
                {
                    sound.SetSoundWaveKind(waveKind);
                    sound.SoundPlay();
                    sound.SetAutodestroy(true);
                }
            }
            GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(SetEngineStarted, 1000, false, true);
        break;
        case CarEngineSoundState.START_NO_FUEL:
            SEffectManager.PlaySound("offroad_engine_failed_start_fuel_SoundSet", ModelToWorld(GetEnginePos()));
        break;
        case CarEngineSoundState.START_NO_BATTERY:
            SEffectManager.PlaySound("offroad_engine_failed_start_battery_SoundSet", ModelToWorld(GetEnginePos()));
        break;
        case CarEngineSoundState.START_NO_SPARKPLUG:
            SEffectManager.PlaySound("offroad_engine_failed_start_sparkplugs_SoundSet", ModelToWorld(GetEnginePos()));
        break;
        case CarEngineSoundState.STOP_OK:
        case CarEngineSoundState.STOP_NO_FUEL:
            // play different sound based on selected camera
            if (Class.CastTo(player, CrewMember(0)))
            {
                if (!player.IsCameraInsideVehicle())
                {
                    waveKind = WaveKind.WAVEEFFECTEX;
                }
                sound = SEffectManager.CreateSound(m_EngineStopFuel, ModelToWorld(GetEnginePos()));
                if (sound)
                {
                    sound.SetSoundWaveKind(waveKind);
                    sound.SoundPlay();
                    sound.SetAutodestroy(true);
                }
            }
            SetEngineStarted(false);
        break;
        }
        #endif
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), Class::CastTo(), SEffectManager::CreateSound(), CGame::GetCallQueue(), GetGame(), m_EngineStartOK, m_EngineStopFuel, ModelToWorld(), SEffectManager::PlaySound(), EffectSound::SetAutodestroy(), SetEngineStarted(), EffectSound::SetSoundWaveKind(), and EffectSound::SoundPlay().
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnEngineStop().
HasEngineZoneReceivedHit()
bool HasEngineZoneReceivedHit ()
Definition at line 2202 of file carscript.c.
    {
        return m_EngineZoneReceivedHit;
    }
References m_EngineZoneReceivedHit.
HasRadiator()
bool HasRadiator ()
Definition at line 1900 of file carscript.c.
    {
        return m_Radiator != null;
    }
References m_Radiator.
Referenced by CarPartsHealthCheck().
InitializeActions()
void InitializeActions ()
Definition at line 1990 of file carscript.c.
    {
        m_InputActionMap = m_CarTypeActionsMap.Get( this.Type() );
        if (!m_InputActionMap)
        {
            TInputActionMap iam = new TInputActionMap;
            m_InputActionMap = iam;
            SetActions();
            m_CarTypeActionsMap.Insert(this.Type(), m_InputActionMap);
        }
    }
References m_CarTypeActionsMap, m_InputActionMap, CarScript::SetActions(), and Type.
IsHandbrakeActive()
bool IsHandbrakeActive ()
Definition at line 1915 of file carscript.c.
    {
        return GetHandbrake() > 0.0;
    }
IsInventoryVisible()
override bool IsInventoryVisible ()
Definition at line 2067 of file carscript.c.
    {
        return ( GetGame().GetPlayer() && ( !GetGame().GetPlayer().GetCommand_Vehicle() || GetGame().GetPlayer().GetCommand_Vehicle().GetTransport() == this ) );
    }
References GetCommand_Vehicle(), GetGame(), and GetPlayer().
IsMoving()
bool IsMoving ()
Definition at line 1910 of file carscript.c.
    {
        return GetSpeedometerAbsolute() > 3.5;
    }
Referenced by CanReleaseAttachment().
IsScriptedLightsOn()
bool IsScriptedLightsOn ()
Propper way to get if light is swiched on. Use instead of IsLightsOn().
Definition at line 1277 of file carscript.c.
    {
        return m_HeadlightsOn;
    }
References m_HeadlightsOn.
Referenced by EEItemDetached(), and OnUpdate().
IsVitalCarBattery()
bool IsVitalCarBattery ()
Definition at line 1865 of file carscript.c.
    {
        return true;
    }
IsVitalEngineBelt()
bool IsVitalEngineBelt ()
Definition at line 1885 of file carscript.c.
    {
        return true;
    }
IsVitalFuelTank()
bool IsVitalFuelTank ()
Definition at line 1895 of file carscript.c.
    {
        return true;
    }
Referenced by EOnPostSimulate().
IsVitalGlowPlug()
bool IsVitalGlowPlug ()
Definition at line 1880 of file carscript.c.
    {
        return true;
    }
IsVitalRadiator()
bool IsVitalRadiator ()
Definition at line 1890 of file carscript.c.
    {
        return true;
    }
IsVitalSparkPlug()
bool IsVitalSparkPlug ()
Definition at line 1875 of file carscript.c.
    {
        return true;
    }
IsVitalTruckBattery()
bool IsVitalTruckBattery ()
Definition at line 1870 of file carscript.c.
    {
        return true;
    }
LeakFluid()
protected void LeakFluid (CarFluid fluid)
Definition at line 1692 of file carscript.c.
    {
        float ammount = 0;
        switch (fluid)
        {
            case CarFluid.COOLANT:
                ammount = (1- m_RadiatorHealth) * Math.RandomFloat(0.02, 0.05);//CARS_LEAK_TICK_MIN; CARS_LEAK_TICK_MAX
                Leak(fluid, ammount);
            break;
            case CarFluid.OIL:
                ammount =  ( 1 - m_EngineHealth ) * Math.RandomFloat(0.02, 1.0);//CARS_LEAK_OIL_MIN; CARS_LEAK_OIL_MAX
                Leak(fluid, ammount);
            break;
            case CarFluid.FUEL:
                ammount = ( 1 - m_FuelTankHealth ) * Math.RandomFloat(0.02, 0.05);//CARS_LEAK_TICK_MIN; CARS_LEAK_TICK_MAX
                Leak(fluid, ammount);
            break;
        }
    }
References m_EngineHealth, m_FuelTankHealth, m_RadiatorHealth, and Math::RandomFloat().
Referenced by EOnPostSimulate().
LeftFrontLightShineOff()
void LeftFrontLightShineOff ()
Definition at line 1547 of file carscript.c.
    {
        string material = ConfigGetString("frontReflectorMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_L, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_FRONT_LIGHT_L.
Referenced by UpdateLightsServer().
LeftFrontLightShineOn()
void LeftFrontLightShineOn ()
Definition at line 1527 of file carscript.c.
    {
        string material = ConfigGetString("frontReflectorMatOn");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_L, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_FRONT_LIGHT_L.
Referenced by UpdateLightsServer().
OnAnimationPhaseStarted()
override void OnAnimationPhaseStarted (string animSource, float phase)
Definition at line 1016 of file carscript.c.
    {
        #ifndef SERVER
        HandleDoorsSound(animSource, phase);
        #endif
    }
References HandleDoorsSound().
OnAttachmentRuined()
override void OnAttachmentRuined (EntityAI attachment)
Definition at line 575 of file carscript.c.
    {
        super.OnAttachmentRuined(attachment);
        UpdateHeadlightState();
        UpdateLights();
    }
References UpdateHeadlightState(), and UpdateLights().
OnBeforeEngineStart()
override bool OnBeforeEngineStart ()
Gets called everytime the game wants to start the engine. This callback is called on server only.
Returns
true if the engine can start, false otherwise.
Definition at line 1173 of file carscript.c.
    {
        EntityAI item = null;
        if (m_EngineStartDoOnce)
        {
            m_EngineStartDoOnce = false;
            return m_EngineBeforeStart;
        }
        if (GetFluidFraction(CarFluid.FUEL) <= 0)
        {
            HandleEngineSound(CarEngineSoundState.START_NO_FUEL);
            return false;
        }
        if (IsVitalCarBattery() || IsVitalTruckBattery())
        {
            item = GetBattery();
            if (!item || (item && (item.IsRuined() || item.GetCompEM().GetEnergy() < m_BatteryEnergyStartMin)))
            {
                m_EngineStartDoOnce = true;
                HandleEngineSound(CarEngineSoundState.START_NO_BATTERY);
                return false;
            }
        }
        if (IsVitalSparkPlug())
        {
            item = FindAttachmentBySlotName("SparkPlug");
            if (!item || (item && item.IsRuined()))
            {
                m_EngineStartDoOnce = true;
                HandleEngineSound(CarEngineSoundState.START_NO_SPARKPLUG);
                return false;
            }
        }
        if (IsVitalGlowPlug())
        {
            item = FindAttachmentBySlotName("GlowPlug");
            if (!item || (item && item.IsRuined()))
            {
                m_EngineStartDoOnce = true;
                HandleEngineSound(CarEngineSoundState.START_NO_SPARKPLUG);
                return false;
            }
        }
        /*
        if (!m_EngineBeforeStart)
        {
            m_EngineBeforeStart = true;
            m_EngineStartDoOnce = true;
            HandleEngineSound(CarEngineSoundState.NONE);
        }
        */
        return true;
    }
References GetBattery(), HandleEngineSound(), CarScript::IsVitalCarBattery(), CarScript::IsVitalGlowPlug(), CarScript::IsVitalSparkPlug(), CarScript::IsVitalTruckBattery(), m_BatteryEnergyStartMin, m_EngineBeforeStart, and m_EngineStartDoOnce.
OnBeforeSwitchLights()
bool OnBeforeSwitchLights (bool toOn)
DEPRECATED Gets called everytime the game wants to switch the lights.
Returns
true when lights can be switched, false otherwise.
Definition at line 1271 of file carscript.c.
    {
        return true;
    }
OnBrakesPressed()
void OnBrakesPressed ()
Definition at line 803 of file carscript.c.
    {
        UpdateLights();
    }
References UpdateLights().
Referenced by OnUpdate().
OnBrakesReleased()
void OnBrakesReleased ()
Definition at line 808 of file carscript.c.
    {
        UpdateLights();
    }
References UpdateLights().
Referenced by OnUpdate().
OnContact()
override void OnContact (string zoneName, vector localPos, IEntity other, Contact data)
WARNING: Can be called very frequently in one frame, use with caution.
Definition at line 896 of file carscript.c.
    {
        if (GetGame().IsServer())
        {
            array<ref CarContactData> ccd;
            if (!m_ContactCache.Find(zoneName, ccd))
            {
                ccd = new array<ref CarContactData>;
                m_ContactCache.Insert(zoneName, ccd);
            }
            ccd.Insert(new CarContactData(localPos, other, data.Impulse));
        }
    }
References GetGame(), Contact::Impulse, and m_ContactCache.
OnEngineStart()
override void OnEngineStart ()
Gets called everytime the engine starts.
Definition at line 1241 of file carscript.c.
    {
        ItemBase battery = GetBattery();
        if (GetGame().IsServer() && battery)
        {
            battery.GetCompEM().ConsumeEnergy(GetBatteryConsumption());
        }
        UpdateLights();
        HandleEngineSound(CarEngineSoundState.START_OK);
        m_EngineBeforeStart = false;
    }
References GetBattery(), GetBatteryConsumption(), GetGame(), HandleEngineSound(), m_EngineBeforeStart, and UpdateLights().
OnEngineStop()
override void OnEngineStop ()
Gets called everytime the engine stops.
Definition at line 1257 of file carscript.c.
    {
        UpdateLights();
        HandleEngineSound(CarEngineSoundState.STOP_OK);
        SetEngineZoneReceivedHit(false);
        m_EngineBeforeStart = false;
    }
References HandleEngineSound(), m_EngineBeforeStart, SetEngineZoneReceivedHit(), and UpdateLights().
OnFluidChanged()
override void OnFluidChanged (CarFluid fluid, float newValue, float oldValue)
Gets called everytime when the specified vehicle's fluid changes its current value eg. when car is consuming fuel.
This callback is called on both server and client.
Definition at line 1145 of file carscript.c.
    {
        switch ( fluid )
        {
        case CarFluid.FUEL:
            m_FuelAmmount = newValue;
            break;
        case CarFluid.OIL:
            m_OilAmmount = newValue;
            break;
        case CarFluid.BRAKE:
            m_BrakeAmmount = newValue;
            break;
        case CarFluid.COOLANT:
            m_CoolantAmmount = newValue;
            break;
        }
    }
References m_BrakeAmmount, m_CoolantAmmount, m_FuelAmmount, and m_OilAmmount.
OnGearChanged()
override void OnGearChanged (int newGear, int oldGear)
Definition at line 1234 of file carscript.c.
    {
        //Debug.Log(string.Format("OnGearChanged newGear=%1,oldGear=%2", newGear, oldGear));
        UpdateLights(newGear);
    }
References UpdateLights().
OnSound()
override float OnSound (CarSoundCtrl ctrl, float oldValue)
Gets called every sound simulation step. In this callback, user can modify behaviour of sound controllers The higher the return value is the more muted sound is.
Definition at line 1001 of file carscript.c.
    {
        switch (ctrl)
        {
        case CarSoundCtrl.ENGINE:
            if (!m_EngineStarted)
            {
                return 0.0;
            }
        break;
        }
        return oldValue;
    }
References m_EngineStarted.
OnUpdate()
override void OnUpdate (float dt)
Definition at line 813 of file carscript.c.
    {
        if ( GetGame().IsServer() )
        {
            ItemBase battery = GetBattery();
            if ( battery )
            {
                if ( EngineIsOn() )
                {
                    m_BatteryTimer += dt;
                    if ( m_BatteryTimer >= BATTERY_UPDATE_DELAY )
                    {
                        battery.GetCompEM().ConsumeEnergy(GetBatteryRechargeRate() * m_BatteryTimer);
                        m_BatteryTimer = 0;
                    }
                }
                else if ( !EngineIsOn() && IsScriptedLightsOn() )
                {
                    m_BatteryTimer += dt;
                    if ( m_BatteryTimer >= BATTERY_UPDATE_DELAY )
                    {
                        battery.GetCompEM().ConsumeEnergy(GetBatteryRuntimeConsumption() * m_BatteryTimer);
                        m_BatteryTimer = 0;
                        if ( battery.GetCompEM().GetEnergy() <= 0 )
{
                            ToggleHeadlights();
                        }
                    }
                }
            }
            if ( GetGame().GetWaterDepth( GetEnginePosWS() ) > 0 )
            {
                m_DrownTime += dt;
                if ( m_DrownTime > DROWN_ENGINE_THRESHOLD )
                {
                    // *dt to get damage per second
                    AddHealth( "Engine", "Health", -DROWN_ENGINE_DAMAGE * dt);
                    SetEngineZoneReceivedHit(true);
                }
            }
            else
            {
                m_DrownTime = 0;
            }
        }
        // For visualisation of brake lights for all players
        float brake_coef = GetBrake();
        if ( brake_coef > 0 )
        {
            if ( !m_BrakesArePressed )
            {
                m_BrakesArePressed = true;
                SetSynchDirty();
                OnBrakesPressed();
            }
        }
        else
        {
            if ( m_BrakesArePressed )
            {
                m_BrakesArePressed = false;
                SetSynchDirty();
                OnBrakesReleased();
            }
        }
        if ( (!GetGame().IsDedicatedServer()) && m_ForceUpdateLights )
        {
            UpdateLights();
            m_ForceUpdateLights = false;
        }
    }
References AddHealth(), BATTERY_UPDATE_DELAY, DROWN_ENGINE_DAMAGE, DROWN_ENGINE_THRESHOLD, GetBattery(), GetBatteryRechargeRate(), GetBatteryRuntimeConsumption(), GetEnginePosWS(), GetGame(), IsScriptedLightsOn(), m_BatteryTimer, m_BrakesArePressed, m_DrownTime, m_ForceUpdateLights, OnBrakesPressed(), OnBrakesReleased(), SetEngineZoneReceivedHit(), ToggleHeadlights(), and UpdateLights().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 421 of file carscript.c.
    {
        super.OnVariablesSynchronized();
        if (GetCrashHeavySound())
        {
            PlayCrashHeavySound();
        }
        else if (GetCrashLightSound())
        {
            PlayCrashLightSound();
        }
        HandleCarHornSound(m_CarHornState);
        UpdateLights();
    }
References GetCrashHeavySound(), GetCrashLightSound(), HandleCarHornSound(), m_CarHornState, PlayCrashHeavySound(), PlayCrashLightSound(), and UpdateLights().
PlayCrashHeavySound()
void PlayCrashHeavySound ()
Definition at line 1766 of file carscript.c.
    {
        PlaySoundEx("offroad_hit_heavy_SoundSet", m_CrashSoundHeavy, m_PlayCrashSoundHeavy);
    }
References m_CrashSoundHeavy, m_PlayCrashSoundHeavy, and PlaySoundEx().
Referenced by OnVariablesSynchronized().
PlayCrashLightSound()
void PlayCrashLightSound ()
Definition at line 1747 of file carscript.c.
    {
        PlaySoundEx("offroad_hit_light_SoundSet", m_CrashSoundLight, m_PlayCrashSoundLight);
    }
References m_CrashSoundLight, m_PlayCrashSoundLight, and PlaySoundEx().
Referenced by OnVariablesSynchronized().
PlaySound()
void PlaySound (string soundset, ref EffectSound sound, out bool soundbool)
Definition at line 1795 of file carscript.c.
    {
        PlaySoundEx(soundset, sound, soundbool);
    }
References PlaySoundEx().
PlaySoundEx()
void PlaySoundEx (string soundset, EffectSound sound, out bool soundbool)
Definition at line 1771 of file carscript.c.
    {
        #ifndef SERVER
        if (!sound)
        {
            sound = SEffectManager.PlaySoundCachedParams(soundset, GetPosition());
            if( sound )
            {
                sound.SetAutodestroy(true);
            }
        }
        else
        {
            if (!sound.IsSoundPlaying())
            {
                sound.SetPosition(GetPosition());
                sound.SoundPlay();
            }
        }
        soundbool = false;
        #endif
    }
References GetPosition, EffectSound::IsSoundPlaying(), SEffectManager::PlaySoundCachedParams(), EffectSound::SetAutodestroy(), and EffectSound::SoundPlay().
Referenced by EEHealthLevelChanged(), PlayCrashHeavySound(), PlayCrashLightSound(), and PlaySound().
RemoveAction()
void RemoveAction (typename actionName)
Definition at line 2054 of file carscript.c.
    {
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        ActionBase action = player.GetActionManager().GetAction(actionName);
        typename ai = action.GetInputType();
        array<ActionBase_Basic> action_array = m_InputActionMap.Get(ai);
        if (action_array)
        {
            action_array.RemoveItem(action);
        }
    }
References ActionBase(), GetGame(), GetPlayer(), and m_InputActionMap.
ReverseLightsShineOff()
void ReverseLightsShineOff ()
Definition at line 1578 of file carscript.c.
    {
        string material = ConfigGetString("ReverseReflectorMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_L, material);
            SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_R, material);
        }
    }
References ConfigGetString(), SELECTION_ID_REVERSE_LIGHT_L, and SELECTION_ID_REVERSE_LIGHT_R.
Referenced by UpdateLightsServer().
ReverseLightsShineOn()
void ReverseLightsShineOn ()
Definition at line 1567 of file carscript.c.
    {
        string material = ConfigGetString("ReverseReflectorMatOn");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_L, material);
            SetObjectMaterial(SELECTION_ID_REVERSE_LIGHT_R, material);
        }
    }
References ConfigGetString(), SELECTION_ID_REVERSE_LIGHT_L, and SELECTION_ID_REVERSE_LIGHT_R.
Referenced by UpdateLightsServer().
RightFrontLightShineOff()
void RightFrontLightShineOff ()
Definition at line 1557 of file carscript.c.
    {
        string material = ConfigGetString("frontReflectorMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_R, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_FRONT_LIGHT_R.
Referenced by UpdateLightsServer().
RightFrontLightShineOn()
void RightFrontLightShineOn ()
Definition at line 1537 of file carscript.c.
    {
        string material = ConfigGetString("frontReflectorMatOn");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_FRONT_LIGHT_R, material);
        }
    }
References ConfigGetString(), and SELECTION_ID_FRONT_LIGHT_R.
Referenced by UpdateLightsServer().
SetActions()
void SetActions ()
Definition at line 2013 of file carscript.c.
    {
        AddAction(ActionOpenCarDoorsOutside);
        AddAction(ActionCloseCarDoorsOutside);
        AddAction(ActionGetInTransport);
        AddAction(ActionSwitchLights);
        AddAction(ActionCarHornShort);
        AddAction(ActionCarHornLong);
    }
References ActionCarHornShort(), and AddAction().
SetCarHornState()
void SetCarHornState (int pState)
Definition at line 2165 of file carscript.c.
    {
        m_CarHornState = pState;
        SetSynchDirty();
        if (GetGame().IsServer())
        {
            GenerateCarHornAINoise(pState);
        }
    }
References GenerateCarHornAINoise(), GetGame(), and m_CarHornState.
SetEngineStarted()
void SetEngineStarted (bool started)
Definition at line 1927 of file carscript.c.
    {
        m_EngineStarted = started;
    }
References m_EngineStarted.
Referenced by HandleEngineSound().
SetEngineZoneReceivedHit()
void SetEngineZoneReceivedHit (bool pState)
Definition at line 2196 of file carscript.c.
    {
        m_EngineZoneReceivedHit = pState;
        SetSynchDirty();
    }
References m_EngineZoneReceivedHit.
Referenced by EEHitBy(), EOnPostSimulate(), OnEngineStop(), and OnUpdate().
SynchCrashHeavySound()
void SynchCrashHeavySound (bool play)
Definition at line 1757 of file carscript.c.
    {
        if (m_PlayCrashSoundHeavy != play)
        {
            m_PlayCrashSoundHeavy = play;
            SetSynchDirty();
        }
    }
References m_PlayCrashSoundHeavy.
Referenced by CheckContactCache().
SynchCrashLightSound()
void SynchCrashLightSound (bool play)
Definition at line 1738 of file carscript.c.
    {
        if (m_PlayCrashSoundLight != play)
        {
            m_PlayCrashSoundLight = play;
            SetSynchDirty();
        }
    }
References m_PlayCrashSoundLight.
Referenced by CheckContactCache().
TailLightsShineOff()
void TailLightsShineOff ()
Definition at line 1636 of file carscript.c.
    {
        string material = ConfigGetString("TailReflectorMatOff");
        if (material != "")
        {
            SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
            SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
        }
    }
References ConfigGetString(), SELECTION_ID_TAIL_LIGHT_L, and SELECTION_ID_TAIL_LIGHT_R.
Referenced by UpdateLightsServer().
TailLightsShineOn()
void TailLightsShineOn ()
Definition at line 1611 of file carscript.c.
    {
        string material = ConfigGetString("TailReflectorMatOn");
        string material_off = ConfigGetString("TailReflectorMatOff");
        if (material != "" && material_off != "")
        {
            if (m_HeadlightsState == CarHeadlightBulbsState.LEFT)
            {
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material_off);
            }
            else if (m_HeadlightsState == CarHeadlightBulbsState.RIGHT)
            {
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material_off);
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
            }
            else if (m_HeadlightsState == CarHeadlightBulbsState.BOTH)
            {
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_L, material);
                SetObjectMaterial(SELECTION_ID_TAIL_LIGHT_R, material);
            }
        }
    }
References ConfigGetString(), m_HeadlightsState, SELECTION_ID_TAIL_LIGHT_L, and SELECTION_ID_TAIL_LIGHT_R.
Referenced by UpdateLightsServer().
ToggleHeadlights()
void ToggleHeadlights ()
Switches headlights on/off, including the illumination of the control panel and synchronizes this change to all clients.
Definition at line 1283 of file carscript.c.
    {
        m_HeadlightsOn = !m_HeadlightsOn;
        SetSynchDirty();
    }
References m_HeadlightsOn.
Referenced by EEItemDetached(), and OnUpdate().
TranslateAnimationPhaseToCarDoorState()
CarDoorState TranslateAnimationPhaseToCarDoorState (string animation)
Definition at line 1937 of file carscript.c.
    {
        if (GetAnimationPhase(animation) > 0.5)
        {
            return CarDoorState.DOORS_OPEN;
        }
        else
        {
            return CarDoorState.DOORS_CLOSED;
        }
    }
Referenced by CarScript::GetCarDoorsState().
UpdateHeadlightState()
void UpdateHeadlightState ()
Definition at line 501 of file carscript.c.
    {
        EntityAI bulb_L = FindAttachmentBySlotName("Reflector_1_1");
        EntityAI bulb_R = FindAttachmentBySlotName("Reflector_2_1");
        if (bulb_L && !bulb_L.IsRuined() && bulb_R && !bulb_R.IsRuined())
        {
            m_HeadlightsState = CarHeadlightBulbsState.BOTH;
        }
        else if (bulb_L && !bulb_L.IsRuined())
        {
            m_HeadlightsState = CarHeadlightBulbsState.LEFT;
        }
        else if (bulb_R && !bulb_R.IsRuined())
        {
            m_HeadlightsState = CarHeadlightBulbsState.RIGHT;
        }
        else if ((!bulb_L || bulb_L.IsRuined()) && (!bulb_R || bulb_R.IsRuined()))
        {
            m_HeadlightsState = CarHeadlightBulbsState.NONE;
        }
    }
References m_HeadlightsState.
Referenced by CheckContactCache(), EEItemAttached(), EEItemDetached(), and OnAttachmentRuined().
UpdateLights()
void UpdateLights (int new_gear = -1)
Definition at line 1289 of file carscript.c.
    {
        #ifndef SERVER
        UpdateLightsClient(new_gear);
        #endif
        UpdateLightsServer(new_gear);
    }
References UpdateLightsClient(), and UpdateLightsServer().
Referenced by CheckContactCache(), EEItemAttached(), EEItemDetached(), OnAttachmentRuined(), OnBrakesPressed(), OnBrakesReleased(), OnEngineStart(), OnEngineStop(), OnGearChanged(), OnUpdate(), and OnVariablesSynchronized().
UpdateLightsClient()
void UpdateLightsClient (int newGear = -1)
Definition at line 1297 of file carscript.c.
    {
        int gear;
        if (newGear == -1)
        {
            gear = GetGear();
        }
        else
        {
            gear = newGear;
        }
        if (m_HeadlightsOn)
        {
            if (!m_Headlight && m_HeadlightsState != CarHeadlightBulbsState.NONE)
            {
                m_Headlight = CreateFrontLight();
            }
            if (m_Headlight)
            {
                switch (m_HeadlightsState)
                {
                case CarHeadlightBulbsState.LEFT:
                    m_Headlight.AttachOnMemoryPoint(this, m_LeftHeadlightPoint, m_LeftHeadlightTargetPoint);
                    m_Headlight.SegregateLight();
                    break;
                case CarHeadlightBulbsState.RIGHT:
                    m_Headlight.AttachOnMemoryPoint(this, m_RightHeadlightPoint, m_RightHeadlightTargetPoint);
                    m_Headlight.SegregateLight();
                    break;
                case CarHeadlightBulbsState.BOTH:
                    vector local_pos_left = GetMemoryPointPos(m_LeftHeadlightPoint);
                    vector local_pos_right = GetMemoryPointPos(m_RightHeadlightPoint);
                    vector local_pos_middle = (local_pos_left + local_pos_right) * 0.5;
                    m_Headlight.AttachOnObject(this, local_pos_middle);
                    m_Headlight.AggregateLight();
                    break;
                default:
                    m_Headlight.FadeOut();
                    m_Headlight = null;
                }
            }
        }
        else
        {
            if (m_Headlight)
            {
                m_Headlight.FadeOut();
                m_Headlight = null;
            }
        }
        // brakes
        if (m_BrakesArePressed)
        {
            switch (gear)
            {
            case CarGear.REVERSE:
            case CarAutomaticGearboxMode.R:
                m_RearLightType = CarRearLightType.BRAKES_AND_REVERSE;
                break;
            default:
                m_RearLightType = CarRearLightType.BRAKES_ONLY;
            }
            //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
        }
        else
        {
            switch (gear)
            {
            case CarGear.REVERSE:
            case CarAutomaticGearboxMode.R:
                m_RearLightType = CarRearLightType.REVERSE_ONLY;
                break;
            default:
                m_RearLightType = CarRearLightType.NONE;
            }
            //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
        }
        if (!m_RearLight && m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
        {
            m_RearLight = CreateRearLight();
            vector local_pos = GetMemoryPointPos(m_ReverseLightPoint);
            m_RearLight.AttachOnObject(this, local_pos, "180 0 0");
        }
        // rear lights
        if (m_RearLight && m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
        {
            switch (m_RearLightType)
            {
            case CarRearLightType.BRAKES_ONLY:
                m_RearLight.SetAsSegregatedBrakeLight();
                break;
            case CarRearLightType.REVERSE_ONLY:
                m_RearLight.SetAsSegregatedReverseLight();
                break;
            case CarRearLightType.BRAKES_AND_REVERSE:
                m_RearLight.AggregateLight();
                m_RearLight.SetFadeOutTime(1);
                break;
            default:
                m_RearLight.FadeOut();
                m_RearLight = null;
            }
        }
        else
        {
            if (m_RearLight)
            {
                m_RearLight.FadeOut();
                m_RearLight = null;
            }
        }
    }
References CarScript::CreateFrontLight(), CarScript::CreateRearLight(), GetMemoryPointPos(), m_BrakesArePressed, m_Headlight, m_HeadlightsOn, m_HeadlightsState, m_LeftHeadlightPoint, m_LeftHeadlightTargetPoint, m_RearLight, m_RearLightType, m_ReverseLightPoint, m_RightHeadlightPoint, and m_RightHeadlightTargetPoint.
Referenced by UpdateLights().
UpdateLightsServer()
void UpdateLightsServer (int newGear = -1)
Definition at line 1417 of file carscript.c.
    {
        int gear;
        if (newGear == -1)
        {
            gear = GetGear();
            if (GearboxGetType() == CarGearboxType.AUTOMATIC)
            {
                gear = GearboxGetMode();
            }
        }
        else
        {
            gear = newGear;
        }
        if (m_HeadlightsOn)
        {
            DashboardShineOn();
            TailLightsShineOn();
            switch (m_HeadlightsState)
            {
            case CarHeadlightBulbsState.LEFT:
                LeftFrontLightShineOn();
                RightFrontLightShineOff();
                break;
            case CarHeadlightBulbsState.RIGHT:
                LeftFrontLightShineOff();
                RightFrontLightShineOn();
                break;
            case CarHeadlightBulbsState.BOTH:
                LeftFrontLightShineOn();
                RightFrontLightShineOn();
                break;
            default:
                LeftFrontLightShineOff();
                RightFrontLightShineOff();
            }
            //Debug.Log(string.Format("m_HeadlightsOn=%1, m_HeadlightsState=%2", m_HeadlightsOn.ToString(), EnumTools.EnumToString(CarHeadlightBulbsState, m_HeadlightsState)));
        }
        else
        {
            TailLightsShineOff();
            DashboardShineOff();
            LeftFrontLightShineOff();
            RightFrontLightShineOff();
        }
        // brakes
        if (m_BrakesArePressed)
        {
            switch (gear)
            {
            case CarGear.REVERSE:
            case CarAutomaticGearboxMode.R:
                m_RearLightType = CarRearLightType.BRAKES_AND_REVERSE;
                break;
            default:
                m_RearLightType = CarRearLightType.BRAKES_ONLY;
            }
            //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
        }
        else
        {
            switch (gear)
            {
            case CarGear.REVERSE:
            case CarAutomaticGearboxMode.R:
                m_RearLightType = CarRearLightType.REVERSE_ONLY;
                break;
            default:
                m_RearLightType = CarRearLightType.NONE;
            }
            //Debug.Log(string.Format("m_BrakesArePressed=%1, m_RearLightType=%2", m_BrakesArePressed.ToString(), EnumTools.EnumToString(CarRearLightType, m_RearLightType)));
        }
        // rear lights
        if (m_RearLightType != CarRearLightType.NONE && m_HeadlightsState != CarHeadlightBulbsState.NONE)
        {
            switch (m_RearLightType)
            {
            case CarRearLightType.BRAKES_ONLY:
                ReverseLightsShineOff();
                BrakeLightsShineOn();
                break;
            case CarRearLightType.REVERSE_ONLY:
                ReverseLightsShineOn();
                BrakeLightsShineOff();
                break;
            case CarRearLightType.BRAKES_AND_REVERSE:
                BrakeLightsShineOn();
                ReverseLightsShineOn();
                break;
            default:
                ReverseLightsShineOff();
            }
        }
        else
        {
            ReverseLightsShineOff();
            BrakeLightsShineOff();
        }
    }
References BrakeLightsShineOff(), BrakeLightsShineOn(), DashboardShineOff(), DashboardShineOn(), LeftFrontLightShineOff(), LeftFrontLightShineOn(), m_BrakesArePressed, m_HeadlightsOn, m_HeadlightsState, m_RearLightType, ReverseLightsShineOff(), ReverseLightsShineOn(), RightFrontLightShineOff(), RightFrontLightShineOn(), TailLightsShineOff(), and TailLightsShineOn().
Referenced by UpdateLights().
~CarScript()
void ~CarScript ()
Definition at line 390 of file carscript.c.
    {
        #ifndef SERVER
        CleanupEffects();
        #endif
    }
References CleanupEffects().
Variable Documentation
BATTERY_UPDATE_DELAY
private const float BATTERY_UPDATE_DELAY = 100
Definition at line 101 of file carscript.c.
Referenced by OnUpdate().
BRAKES_ONLY
enum CarDoorState BRAKES_ONLY
DROWN_ENGINE_DAMAGE
float DROWN_ENGINE_DAMAGE = 350.0 static
Definition at line 72 of file carscript.c.
Referenced by OnUpdate().
DROWN_ENGINE_THRESHOLD
float DROWN_ENGINE_THRESHOLD = 0.5 static
Definition at line 71 of file carscript.c.
Referenced by OnUpdate().
LEFT
enum CarDoorState LEFT
LONG
enum CarDoorState LONG
Initial value:
= 2
}
class CarContactData
{
    vector localPos;
    IEntity other;
    float impulse;
    void CarContactData(vector _localPos, IEntity _other, float _impulse)
    {
        localPos    = _localPos;
        other       = _other;
        impulse     = _impulse;
    }
}
typedef map<string
m_ActionsInitialize
bool m_ActionsInitialize
Definition at line 65 of file carscript.c.
m_backPos
protected vector m_backPos
Definition at line 122 of file carscript.c.
Referenced by CarScript(), and GetBackPointPosWS().
m_BatteryConsume
protected float m_BatteryConsume = 15
Definition at line 97 of file carscript.c.
Referenced by GetBatteryConsumption().
m_BatteryContinuousConsume
protected float m_BatteryContinuousConsume = 0.25
Definition at line 98 of file carscript.c.
Referenced by GetBatteryRuntimeConsumption().
m_BatteryEnergyStartMin
protected float m_BatteryEnergyStartMin = 5.0
Definition at line 102 of file carscript.c.
Referenced by OnBeforeEngineStart().
m_BatteryHealth
protected float m_BatteryHealth
Definition at line 92 of file carscript.c.
Referenced by CarScript(), EEItemAttached(), and EEItemDetached().
m_BatteryRecharge
protected float m_BatteryRecharge = 0.15
Definition at line 99 of file carscript.c.
Referenced by GetBatteryRechargeRate().
m_BatteryTimer
private float m_BatteryTimer = 0
Definition at line 100 of file carscript.c.
Referenced by OnUpdate().
m_BrakeAmmount
protected float m_BrakeAmmount
Definition at line 78 of file carscript.c.
Referenced by OnFluidChanged().
m_BrakesArePressed
protected bool m_BrakesArePressed
Definition at line 154 of file carscript.c.
Referenced by OnUpdate(), UpdateLightsClient(), and UpdateLightsServer().
m_CarDoorCloseSound
string m_CarDoorCloseSound = ""
Definition at line 136 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleDoorsSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarDoorOpenSound
string m_CarDoorOpenSound = ""
Definition at line 135 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleDoorsSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornLongSoundName
string m_CarHornLongSoundName = ""
Definition at line 139 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleCarHornSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornShortSoundName
string m_CarHornShortSoundName = ""
Definition at line 138 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleCarHornSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_CarHornSoundEffect
protected ref EffectSound m_CarHornSoundEffect
Definition at line 145 of file carscript.c.
Referenced by CleanupEffects(), and HandleCarHornSound().
m_CarHornState
protected int m_CarHornState
Definition at line 161 of file carscript.c.
Referenced by CarScript(), OnVariablesSynchronized(), and SetCarHornState().
m_CarTypeActionsMap
enum CarDoorState m_CarTypeActionsMap = new map<typename, ref TInputActionMap>
Referenced by InitializeActions().
m_ContactCache
ref CarContactCache m_ContactCache
Definition at line 67 of file carscript.c.
Referenced by CarScript(), CheckContactCache(), and OnContact().
m_CoolantAmmount
protected float m_CoolantAmmount
Definition at line 76 of file carscript.c.
Referenced by OnFluidChanged().
m_coolantFx
protected ref EffVehicleSmoke m_coolantFx
Particles.
Definition at line 105 of file carscript.c.
Referenced by CleanupEffects(), and EOnPostSimulate().
m_coolantPtcFx
protected int m_coolantPtcFx
Definition at line 110 of file carscript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_coolantPtcPos
protected vector m_coolantPtcPos
Definition at line 116 of file carscript.c.
Referenced by CarScript(), EOnPostSimulate(), and GetCoolantPtcPosWS().
m_CrashSoundHeavy
ref EffectSound m_CrashSoundHeavy
Definition at line 142 of file carscript.c.
Referenced by CleanupEffects(), and PlayCrashHeavySound().
m_CrashSoundLight
ref EffectSound m_CrashSoundLight
Definition at line 141 of file carscript.c.
Referenced by CleanupEffects(), and PlayCrashLightSound().
m_dmgContactCoef
protected float m_dmgContactCoef
Definition at line 81 of file carscript.c.
Referenced by CarScript(), CheckContactCache(), CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), CarScript::Truck_01_Base(), CarScript::Truck_02(), and CarScript::Van_01().
m_DrownEnginePoint
string m_DrownEnginePoint = "drown_engine" static
Definition at line 172 of file carscript.c.
m_DrownEnginePos
vector m_DrownEnginePos static
Definition at line 86 of file carscript.c.
Referenced by CarScript(), and GetEnginePosWS().
m_DrownTime
protected float m_DrownTime
Definition at line 85 of file carscript.c.
Referenced by OnUpdate().
m_EngineBeforeStart
protected bool m_EngineBeforeStart
Definition at line 186 of file carscript.c.
Referenced by OnBeforeEngineStart(), OnEngineStart(), and OnEngineStop().
m_EngineDestroyed
protected bool m_EngineDestroyed
Definition at line 159 of file carscript.c.
Referenced by EEKilled().
m_engineFx
protected ref EffVehicleSmoke m_engineFx
Definition at line 106 of file carscript.c.
Referenced by CleanupEffects(), and CreateCarDestroyedEffect().
m_EngineHealth
protected float m_EngineHealth
Definition at line 89 of file carscript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EOnPostSimulate(), and LeakFluid().
m_enginePos
protected vector m_enginePos
Definition at line 120 of file carscript.c.
Referenced by CarScript(), and GetEnginePointPosWS().
m_enginePtcFx
protected int m_enginePtcFx
Definition at line 109 of file carscript.c.
Referenced by CarScript(), and CreateCarDestroyedEffect().
m_enginePtcPos
protected vector m_enginePtcPos
Definition at line 115 of file carscript.c.
Referenced by CarScript(), CreateCarDestroyedEffect(), CarScript::Truck_01_Base(), and CarScript::Truck_02().
m_EngineStartBattery
string m_EngineStartBattery = ""
Definition at line 130 of file carscript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartDoOnce
protected bool m_EngineStartDoOnce
Definition at line 187 of file carscript.c.
Referenced by OnBeforeEngineStart().
m_EngineStarted
protected bool m_EngineStarted
Definition at line 158 of file carscript.c.
Referenced by OnSound(), and SetEngineStarted().
m_EngineStartFuel
string m_EngineStartFuel = ""
Definition at line 132 of file carscript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartOK
string m_EngineStartOK = ""
Sounds.
Definition at line 129 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleEngineSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStartPlug
string m_EngineStartPlug = ""
Definition at line 131 of file carscript.c.
Referenced by CarScript::CivilianSedan(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineStopFuel
string m_EngineStopFuel = ""
Definition at line 133 of file carscript.c.
Referenced by CarScript::CivilianSedan(), HandleEngineSound(), CarScript::Hatchback_02(), CarScript::Offroad_02(), CarScript::OffroadHatchback(), CarScript::Sedan_02(), and CarScript::Truck_01_Base().
m_EngineZoneReceivedHit
protected bool m_EngineZoneReceivedHit
Definition at line 189 of file carscript.c.
Referenced by HasEngineZoneReceivedHit(), and SetEngineZoneReceivedHit().
m_EnviroHeatComfortOverride
protected float m_EnviroHeatComfortOverride
Definition at line 82 of file carscript.c.
Referenced by CarScript().
m_exhaustFx
protected ref EffVehicleSmoke m_exhaustFx
Definition at line 107 of file carscript.c.
Referenced by CleanupEffects(), and EOnPostSimulate().
m_exhaustPtcDir
protected vector m_exhaustPtcDir
Definition at line 114 of file carscript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_exhaustPtcFx
protected int m_exhaustPtcFx
Definition at line 111 of file carscript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_exhaustPtcPos
protected vector m_exhaustPtcPos
Definition at line 113 of file carscript.c.
Referenced by CarScript(), and EOnPostSimulate().
m_ForceUpdateLights
protected bool m_ForceUpdateLights
Definition at line 157 of file carscript.c.
Referenced by ForceUpdateLightsEnd(), ForceUpdateLightsStart(), and OnUpdate().
m_frontPos
protected vector m_frontPos
Definition at line 121 of file carscript.c.
Referenced by CarScript(), and GetFrontPointPosWS().
m_FuelAmmount
protected float m_FuelAmmount
keeps ammount of each fluid
Definition at line 75 of file carscript.c.
Referenced by OnFluidChanged().
m_fuelPos
protected vector m_fuelPos
Definition at line 118 of file carscript.c.
Referenced by CarScript(), and GetRefillPointPosWS().
m_FuelTankHealth
protected float m_FuelTankHealth
Definition at line 91 of file carscript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EOnPostSimulate(), and LeakFluid().
m_Headlight
CarLightBase m_Headlight
Definition at line 163 of file carscript.c.
Referenced by CleanupEffects(), and UpdateLightsClient().
m_HeadlightsOn
protected bool m_HeadlightsOn
Definition at line 152 of file carscript.c.
Referenced by IsScriptedLightsOn(), ToggleHeadlights(), UpdateLightsClient(), and UpdateLightsServer().
m_HeadlightsState
protected bool m_HeadlightsState
Definition at line 153 of file carscript.c.
Referenced by TailLightsShineOn(), UpdateHeadlightState(), UpdateLightsClient(), and UpdateLightsServer().
m_InputActionMap
TInputActionMap m_InputActionMap
Definition at line 64 of file carscript.c.
m_LeftHeadlightPoint
string m_LeftHeadlightPoint = "light_left" static
Definition at line 168 of file carscript.c.
Referenced by UpdateLightsClient().
m_LeftHeadlightTargetPoint
string m_LeftHeadlightTargetPoint = "light_left_dir" static
Definition at line 170 of file carscript.c.
Referenced by UpdateLightsClient().
m_NoisePar
protected ref NoiseParams m_NoisePar
Definition at line 146 of file carscript.c.
m_NoiseSystem
protected NoiseSystem m_NoiseSystem
Definition at line 147 of file carscript.c.
Referenced by EEInit(), and GenerateCarHornAINoise().
m_OilAmmount
protected float m_OilAmmount
Definition at line 77 of file carscript.c.
Referenced by OnFluidChanged().
m_PlayCrashSoundHeavy
protected bool m_PlayCrashSoundHeavy
Definition at line 150 of file carscript.c.
Referenced by CarScript(), GetCrashHeavySound(), PlayCrashHeavySound(), and SynchCrashHeavySound().
m_PlayCrashSoundLight
protected bool m_PlayCrashSoundLight
Definition at line 149 of file carscript.c.
Referenced by CarScript(), GetCrashLightSound(), PlayCrashLightSound(), and SynchCrashLightSound().
m_PlugHealth
protected float m_PlugHealth
Definition at line 93 of file carscript.c.
Referenced by CarScript(), EEItemAttached(), and EEItemDetached().
m_Radiator
protected EntityAI m_Radiator
Definition at line 95 of file carscript.c.
Referenced by EEItemAttached(), EEItemDetached(), GetRadiator(), and HasRadiator().
m_RadiatorHealth
protected float m_RadiatorHealth
Definition at line 90 of file carscript.c.
Referenced by CarPartsHealthCheck(), CarScript(), EEItemAttached(), EOnPostSimulate(), and LeakFluid().
m_RearLight
CarRearLightBase m_RearLight
Definition at line 164 of file carscript.c.
Referenced by CleanupEffects(), and UpdateLightsClient().
m_RearLightType
protected bool m_RearLightType
Definition at line 155 of file carscript.c.
Referenced by UpdateLightsClient(), and UpdateLightsServer().
m_ReverseLightPoint
string m_ReverseLightPoint = "light_reverse" static
Definition at line 167 of file carscript.c.
Referenced by UpdateLightsClient().
m_RightHeadlightPoint
string m_RightHeadlightPoint = "light_right" static
Definition at line 169 of file carscript.c.
Referenced by UpdateLightsClient().
m_RightHeadlightTargetPoint
string m_RightHeadlightTargetPoint = "light_right_dir" static
Definition at line 171 of file carscript.c.
Referenced by UpdateLightsClient().
m_side_1_1Pos
protected vector m_side_1_1Pos
Definition at line 123 of file carscript.c.
Referenced by CarScript(), and Get_1_1PointPosWS().
m_side_1_2Pos
protected vector m_side_1_2Pos
Definition at line 124 of file carscript.c.
Referenced by CarScript(), and Get_1_2PointPosWS().
m_side_2_1Pos
protected vector m_side_2_1Pos
Definition at line 125 of file carscript.c.
Referenced by CarScript(), and Get_2_1PointPosWS().
m_side_2_2Pos
protected vector m_side_2_2Pos
Definition at line 126 of file carscript.c.
Referenced by CarScript(), and Get_2_2PointPosWS().
m_Time
protected float m_Time
Definition at line 69 of file carscript.c.
m_WindowLarge
ref EffectSound m_WindowLarge
Definition at line 144 of file carscript.c.
Referenced by CleanupEffects(), and EEHealthLevelChanged().
m_WindowSmall
ref EffectSound m_WindowSmall
Definition at line 143 of file carscript.c.
Referenced by CleanupEffects(), and EEHealthLevelChanged().
NONE
enum CarDoorState NONE
OFF
enum CarDoorState OFF = 0
REVERSE_ONLY
enum CarDoorState REVERSE_ONLY
RIGHT
enum CarDoorState RIGHT
SELECTION_ID_BRAKE_LIGHT_L
const int SELECTION_ID_BRAKE_LIGHT_L = 2 static
Definition at line 178 of file carscript.c.
Referenced by BrakeLightsShineOff(), and BrakeLightsShineOn().
SELECTION_ID_BRAKE_LIGHT_R
const int SELECTION_ID_BRAKE_LIGHT_R = 3 static
Definition at line 179 of file carscript.c.
Referenced by BrakeLightsShineOff(), and BrakeLightsShineOn().
SELECTION_ID_DASHBOARD_LIGHT
const int SELECTION_ID_DASHBOARD_LIGHT = 8 static
Definition at line 184 of file carscript.c.
Referenced by DashboardShineOff(), and DashboardShineOn().
SELECTION_ID_FRONT_LIGHT_L
const int SELECTION_ID_FRONT_LIGHT_L = 0 static
Definition at line 176 of file carscript.c.
Referenced by LeftFrontLightShineOff(), and LeftFrontLightShineOn().
SELECTION_ID_FRONT_LIGHT_R
const int SELECTION_ID_FRONT_LIGHT_R = 1 static
Definition at line 177 of file carscript.c.
Referenced by RightFrontLightShineOff(), and RightFrontLightShineOn().
SELECTION_ID_REVERSE_LIGHT_L
const int SELECTION_ID_REVERSE_LIGHT_L = 4 static
Definition at line 180 of file carscript.c.
Referenced by ReverseLightsShineOff(), and ReverseLightsShineOn().
SELECTION_ID_REVERSE_LIGHT_R
const int SELECTION_ID_REVERSE_LIGHT_R = 5 static
Definition at line 181 of file carscript.c.
Referenced by ReverseLightsShineOff(), and ReverseLightsShineOn().
SELECTION_ID_TAIL_LIGHT_L
const int SELECTION_ID_TAIL_LIGHT_L = 6 static
Definition at line 182 of file carscript.c.
Referenced by TailLightsShineOff(), and TailLightsShineOn().
SELECTION_ID_TAIL_LIGHT_R
const int SELECTION_ID_TAIL_LIGHT_R = 7 static
Definition at line 183 of file carscript.c.
Referenced by TailLightsShineOff(), and TailLightsShineOn().
SHORT
enum CarDoorState SHORT = 1
START_NO_BATTERY
enum CarDoorState START_NO_BATTERY
START_NO_FUEL
enum CarDoorState START_NO_FUEL
START_NO_SPARKPLUG
enum CarDoorState START_NO_SPARKPLUG
START_OK
enum CarDoorState START_OK
STOP_OK
enum CarDoorState STOP_OK
typename
enum CarDoorState typename
Initial value:
= 2
}
class CarContactData
{
    vector localPos;
    IEntity other;
    float impulse;
    void CarContactData(vector _localPos, IEntity _other, float _impulse)
    {
        localPos    = _localPos;
        other       = _other;
        impulse     = _impulse;
    }
}
typedef map<string
Base script class for all motorized wheeled vehicles.