DayzKode: HumanCommandLadder Class Reference
HumanCommandLadder Class Reference
Private Member Functions
proto native bool CanExit ()
returns true if on exiting point
proto native void Exit ()
private void HumanCommandLadder ()
private void ~HumanCommandLadder ()
Static Private Member Functions
proto static native bool DebugDrawLadder (Building pBuilding, int pLadderIndex)
debug draws any ladder
proto static native int DebugGetLadderIndex (string pComponentName)
Detailed Description
Definition at line 624 of file human.c.
Constructor & Destructor Documentation
HumanCommandLadder()
private void HumanCommandLadder::HumanCommandLadder () inline private
Definition at line 626 of file human.c.
{}
~HumanCommandLadder()
private void HumanCommandLadder::~HumanCommandLadder () inline private
Definition at line 627 of file human.c.
{}
Member Function Documentation
CanExit()
proto native bool HumanCommandLadder::CanExit () private
returns true if on exiting point
Referenced by ActionExitLadder::ActionCondition().
DebugDrawLadder()
proto static native bool HumanCommandLadder::DebugDrawLadder (Building pBuilding, int pLadderIndex) static private
debug draws any ladder
Referenced by ActionEnterLadder::ActionCondition().
DebugGetLadderIndex()
proto static native int HumanCommandLadder::DebugGetLadderIndex (string pComponentName) static private
Referenced by ActionEnterLadder::ActionCondition(), and ActionEnterLadder::Start().
Exit()
proto native void HumanCommandLadder::Exit () private
Referenced by ActionExitLadder::Start().