DayzKode: CAContinuousFertilizeGardenSlot Class Reference
CAContinuousFertilizeGardenSlot Class Reference
Private Member Functions
void CAContinuousFertilizeGardenSlot (float quantity_used_per_second)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected string m_Selection
protected Slot m_Slot
protected float m_SlotFertilizerNeed
protected float m_SpentQuantityTotal
protected float m_StartQuantity
protected float m_TimeToComplete
Detailed Description
Definition at line 1 of file cacontinuousfertilizegardenslot.c.
Constructor & Destructor Documentation
CAContinuousFertilizeGardenSlot()
void CAContinuousFertilizeGardenSlot::CAContinuousFertilizeGardenSlot (float quantity_used_per_second) inline private
Definition at line 10 of file cacontinuousfertilizegardenslot.c.
    {
        m_QuantityUsedPerSecond = quantity_used_per_second;
        m_TimeToComplete = 0;
    }
References CAContinuousQuantity::m_QuantityUsedPerSecond, and m_TimeToComplete.
Member Function Documentation
Execute()
override int CAContinuousFertilizeGardenSlot::Execute (ActionData action_data) inline private
Definition at line 67 of file cacontinuousfertilizegardenslot.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        if ( m_SpentQuantity >= m_ItemQuantity )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_SpentQuantity <= m_ItemQuantity )
            {
                m_SpentQuantity += m_QuantityUsedPerSecond * action_data.m_Player.GetDeltaT();
                float val = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( m_SpentQuantity, m_Action.GetSpecialtyWeight(), true );
                GardenBase garden_base;
                Class.CastTo(garden_base,  action_data.m_Target.GetObject() );
                //string selection = garden_base.GetActionComponentName(action_data.m_Target.GetComponentIndex());
                m_SpentQuantityTotal += m_SpentQuantity;
                if (GetGame().IsServer())
                {
                    action_data.m_MainItem.AddQuantity( -m_SpentQuantity );
                }
                garden_base.Fertilize( action_data.m_Player, action_data.m_MainItem, val, m_Selection );
                return UA_PROCESSING;
            }
            else
            {
                CalcAndSetQuantity( action_data );
                OnCompletePogress(action_data);
                return UA_FINISHED;
            }
        }
    }
References CalcAndSetQuantity(), Class::CastTo(), GetGame(), CABase::m_Action, CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Selection, CAContinuousQuantity::m_SpentQuantity, m_SpentQuantityTotal, ActionData::m_Target, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousFertilizeGardenSlot::GetProgress () inline private
Definition at line 108 of file cacontinuousfertilizegardenslot.c.
    {
        /*if ( m_TimeToComplete == 0) //Prevent division by 0 case
        {
            return -1;
        }*/
        return -(m_SpentQuantityTotal / m_StartQuantity);
        //return (m_SpentQuantity)/m_ItemQuantity;///(m_TimeToComplete * m_QuantityUsedPerSecond)/m_ItemQuantity;
    }
References m_SpentQuantityTotal, and m_StartQuantity.
Setup()
override void CAContinuousFertilizeGardenSlot::Setup (ActionData action_data) inline private
Definition at line 16 of file cacontinuousfertilizegardenslot.c.
    {
        GardenBase target_GB;
        if ( Class.CastTo(target_GB,  action_data.m_Target.GetObject() ) )
        {
            m_SpentQuantity = 0;
            m_StartQuantity = action_data.m_MainItem.GetQuantity();
            if ( !m_SpentUnits )
            {
                m_SpentUnits = new Param1<float>(0);
            }
            else
            {
                m_SpentUnits.param1 = 0;
            }
            if ( action_data.m_MainItem )
                m_ItemQuantity = action_data.m_MainItem.GetQuantity();
            if ( target_GB )
            {
                /*string selection = target_GB.GetActionComponentName(action_data.m_Target.GetComponentIndex());
                Slot slot = target_GB.GetSlotBySelection( selection );*/
                array<string> selections = new array<string>;
                target_GB.GetActionComponentNameList(action_data.m_Target.GetComponentIndex(), selections);
                for (int s = 0; s < selections.Count(); s++)
                {
                    //string selection = selections[s];
                    m_Selection = selections[s];
                    m_Slot = target_GB.GetSlotBySelection( m_Selection );
                    if (m_Slot)
                        break;
                }
                string item_type = action_data.m_MainItem.GetType();
                float consumed_quantity = GetGame().ConfigGetFloat( "cfgVehicles " + item_type + " Horticulture ConsumedQuantity" );
                float max = m_Slot.GetFertilizerQuantityMax();
                m_SlotFertilizerNeed = max - consumed_quantity;
            }
            m_TimeToComplete = (Math.Min(m_SlotFertilizerNeed,m_ItemQuantity))/m_QuantityUsedPerSecond;
        }
    }
References Class::CastTo(), CGame::ConfigGetFloat(), GetGame(), CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Selection, m_Slot, m_SlotFertilizerNeed, CAContinuousQuantity::m_SpentQuantity, CAContinuousQuantity::m_SpentUnits, m_StartQuantity, ActionData::m_Target, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_Selection
protected string CAContinuousFertilizeGardenSlot::m_Selection private
Definition at line 8 of file cacontinuousfertilizegardenslot.c.
Referenced by Execute(), and Setup().
m_Slot
protected Slot CAContinuousFertilizeGardenSlot::m_Slot private
Definition at line 7 of file cacontinuousfertilizegardenslot.c.
Referenced by Setup().
m_SlotFertilizerNeed
protected float CAContinuousFertilizeGardenSlot::m_SlotFertilizerNeed private
Definition at line 3 of file cacontinuousfertilizegardenslot.c.
Referenced by Setup().
m_SpentQuantityTotal
protected float CAContinuousFertilizeGardenSlot::m_SpentQuantityTotal private
Definition at line 5 of file cacontinuousfertilizegardenslot.c.
Referenced by Execute(), and GetProgress().
m_StartQuantity
protected float CAContinuousFertilizeGardenSlot::m_StartQuantity private
Definition at line 6 of file cacontinuousfertilizegardenslot.c.
Referenced by GetProgress(), and Setup().
m_TimeToComplete
protected float CAContinuousFertilizeGardenSlot::m_TimeToComplete private
Definition at line 4 of file cacontinuousfertilizegardenslot.c.
Referenced by CAContinuousFertilizeGardenSlot(), and Setup().