DayzKode: HandEventBase Class Reference
HandEventBase Class Reference
triggered when animation action finishes
Private Member Functions
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override bool AcquireInventoryJunctureFromServer (notnull Man player)
override bool CanPerformEvent ()
override bool CanPerformEvent ()
override bool CanPerformEvent ()
override bool CanPerformEvent ()
void CheckAndExecuteForceStandUp ()
override bool CheckRequest ()
override bool CheckRequest ()
override bool CheckRequest ()
override bool CheckRequest ()
override bool CheckRequestSrc ()
override bool CheckRequestSrc ()
override bool CheckRequestSrc ()
override bool CheckRequestSrc ()
override void ClearInventoryReservation ()
override string DumpToString ()
override string DumpToString ()
override string DumpToString ()
override InventoryLocation GetDst ()
override InventoryLocation GetDst ()
override InventoryLocation GetDst ()
override InventoryLocation GetDst ()
override InventoryLocation GetDst ()
override EntityAI GetSecondSrcEntity ()
void HandAnimEventChanged (Man p=null, InventoryLocation src=null)
void HandEvengReplaceWithNewBase (Man p=null, InventoryLocation src=null, ReplaceItemWithNewLambdaBase lambda=NULL)
void HandEventCreated (Man p=null, InventoryLocation src=null)
void HandEventDestroy (Man p=null, InventoryLocation src=null)
void HandEventDestroyed (Man p=null, InventoryLocation src=null)
void HandEventDrop (Man p=null, InventoryLocation src=null)
void HandEventHumanCommandActionAborted (Man p=null, InventoryLocation src=null)
void HandEventHumanCommandActionFinished (Man p=null, InventoryLocation src=null)
void HandEventMoveTo (Man p=null, InventoryLocation src=null, InventoryLocation dst=null)
destination for item in hands
void HandEventReplaced (Man p=null, InventoryLocation src=null)
void HandEventSwap (Man p=null, InventoryLocation src=null, InventoryLocation src2=null, InventoryLocation dst=null, InventoryLocation dst2=null)
void HandEventTake (Man p=null, InventoryLocation src=null)
override bool IsServerSideOnly ()
override bool IsServerSideOnly ()
override void ReadFromContext (ParamsReadContext ctx)
override void ReadFromContext (ParamsReadContext ctx)
override void ReadFromContext (ParamsReadContext ctx)
override bool ReserveInventory ()
override void WriteToContext (ParamsWriteContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
Private Attributes
int m_Animation2ID = -1
destination for old item that was in hands
ref InventoryLocation m_Dst
ref InventoryLocation m_Dst2
src of old item in hands
ref ReplaceItemWithNewLambdaBase m_Lambda
ref InventoryLocation m_Src2
destination for new item (i.e. hands)
string m_Type
Detailed Description
triggered when animation action finishes
represents event that triggers transition from state to state
triggered when animation action aborts
Definition at line 161 of file hand_events.c.
Member Function Documentation
AcquireInventoryJunctureFromServer() [1/4]
override bool HandEventBase::AcquireInventoryJunctureFromServer (notnull Man player) inline private
Definition at line 204 of file hand_events.c.
    {
        InventoryLocation src = GetSrc();
        InventoryLocation dst = GetDst();
        if (src && dst)
        {
            return TryAcquireInventoryJunctureFromServer(player, src, dst);
        }
        Error("[hndfsm] HandEventTake. AcquireInventoryJunctureFromServer: no src or dst for ev=" + DumpToString());
        return JunctureRequestResult.ERROR;
    }
References DumpToString(), Error(), GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
Referenced by ProccessInputData().
AcquireInventoryJunctureFromServer() [2/4]
override bool HandEventBase::AcquireInventoryJunctureFromServer (notnull Man player) inline private
Definition at line 267 of file hand_events.c.
    {
        InventoryLocation src = GetSrc();
        InventoryLocation dst = GetDst();
        if (src && dst)
        {
            return TryAcquireInventoryJunctureFromServer(player, src, dst);
        }
        Error("[hndfsm] HandEventMoveTo. AcquireInventoryJunctureFromServer: no src or dst for ev=" + DumpToString());
        return JunctureRequestResult.ERROR;
    }
References DumpToString(), Error(), GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
AcquireInventoryJunctureFromServer() [3/4]
override bool HandEventBase::AcquireInventoryJunctureFromServer (notnull Man player) inline private
Definition at line 333 of file hand_events.c.
    {
        InventoryLocation src = GetSrc();
        InventoryLocation dst = GetDst();
        if (src && dst)
        {
            return TryAcquireInventoryJunctureFromServer(player, src, dst);
        }
        Error("[hndfsm] HandEventDrop. AcquireInventoryJunctureFromServer: no src or dst for ev=" + DumpToString());
        return JunctureRequestResult.ERROR;
    }
References DumpToString(), Error(), HandEventDrop::GetDst(), GetSrc(), and TryAcquireInventoryJunctureFromServer().
AcquireInventoryJunctureFromServer() [4/4]
override bool HandEventBase::AcquireInventoryJunctureFromServer (notnull Man player) inline private
Definition at line 512 of file hand_events.c.
    {
        return TryAcquireTwoInventoryJuncturesFromServer(player, m_Src, m_Src2, m_Dst, m_Dst2);
    }
References m_Src, and TryAcquireTwoInventoryJuncturesFromServer().
CanPerformEvent() [1/4]
override bool HandEventBase::CanPerformEvent () inline private
Definition at line 188 of file hand_events.c.
    {
        if (false == GameInventory.LocationCanMoveEntity(GetSrc(), GetDst()))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("CANNOT perform", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CanPerformEvent", m_Player.ToString() );
            }
            #endif
            //hndDebugPrint("[desync] HandleInputData man=" + Object.GetDebugName(m_Player) + " CANNOT perform ev=" + DumpToString());
            return false;
        }
        return true;
    }
References GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
Referenced by HandEvent(), HandleHandEvent(), and ProccessInputData().
CanPerformEvent() [2/4]
override bool HandEventBase::CanPerformEvent () inline private
Definition at line 252 of file hand_events.c.
    {
        if (false == GameInventory.LocationCanMoveEntity(GetSrc(), GetDst()))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("CANNOT perform", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CanPerformEvent", m_Player.ToString() );
            }
            #endif
            return false;
        }
        return true;
    }
References GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CanPerformEvent() [3/4]
override bool HandEventBase::CanPerformEvent () inline private
Definition at line 318 of file hand_events.c.
    {
        if (false == GameInventory.LocationCanMoveEntity(GetSrc(), GetDst()))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("CANNOT perform", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CanPerformEvent", m_Player.ToString() );
            }
            #endif
            return false;
        }
        return true;
    }
References HandEventDrop::GetDst(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CanPerformEvent() [4/4]
override bool HandEventBase::CanPerformEvent () inline private
Definition at line 498 of file hand_events.c.
    {
        if (GameInventory.CanForceSwapEntitiesEx(GetSrc().GetItem(), m_Dst, m_Src2.GetItem(), m_Dst2))
            return true;
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("CANNOT perform", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CanPerformEvent", m_Player.ToString() );
        }
        #endif
        return false;
    }
References GetEventID(), GetItem(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CheckAndExecuteForceStandUp()
void HandEventBase::CheckAndExecuteForceStandUp () inline private
Definition at line 522 of file hand_events.c.
    {
        DayZPlayer player = DayZPlayer.Cast(m_Player);
        player.ForceStandUpForHeavyItemsSwap( m_Src.GetItem(), m_Src2.GetItem() );
    }
References InventoryLocation::GetItem(), m_Player, and m_Src.
CheckRequest() [1/4]
override bool HandEventBase::CheckRequest () inline private
Definition at line 183 of file hand_events.c.
    {
        return GameInventory.CheckMoveToDstRequest(m_Player, GetSrc(), GetDst(), GameInventory.c_MaxItemDistanceRadius);
    }
References GetDst(), GetSrc(), and m_Player.
Referenced by ProccessInputData().
CheckRequest() [2/4]
override bool HandEventBase::CheckRequest () inline private
Definition at line 247 of file hand_events.c.
    {
        return GameInventory.CheckMoveToDstRequest(m_Player, GetSrc(), GetDst(), GameInventory.c_MaxItemDistanceRadius);
    }
References GetDst(), GetSrc(), and m_Player.
CheckRequest() [3/4]
override bool HandEventBase::CheckRequest () inline private
Definition at line 313 of file hand_events.c.
    {
        return GameInventory.CheckMoveToDstRequest(m_Player, GetSrc(), GetDst(), GameInventory.c_MaxItemDistanceRadius);
    }
References HandEventDrop::GetDst(), GetSrc(), and m_Player.
CheckRequest() [4/4]
override bool HandEventBase::CheckRequest () inline private
Definition at line 472 of file hand_events.c.
    {
        if (!GameInventory.CheckSwapItemsRequest(m_Player, m_Src, m_Src2, m_Dst, m_Dst2, GameInventory.c_MaxItemDistanceRadius))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("CheckSwapItemsRequest - failed", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CheckRequest", m_Player.ToString() );
            }
            #endif
        }
        else if (!m_Player.GetHumanInventory().CanAddSwappedEntity(m_Src, m_Src2, m_Dst, m_Dst2))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("CanAddSwappedEntity - failed", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CheckRequest", m_Player.ToString() );
            }
            #endif
        }
        else
            return true;
        return false;
    }
References GetEventID(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), m_Player, and m_Src.
CheckRequestSrc() [1/4]
override bool HandEventBase::CheckRequestSrc () inline private
Definition at line 172 of file hand_events.c.
    {
        if (false == GameInventory.CheckRequestSrc(m_Player, GetSrc(), GameInventory.c_MaxItemDistanceRadius))
        {
            Debug.InventoryHFSMLog("CANNOT perform", typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CheckRequestSrc", m_Player.ToString() );
            syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(m_Player) + " failed src1 check with cmd=" + typename.EnumToString(HandEventID, GetEventID()) + " src1=" + InventoryLocation.DumpToStringNullSafe(GetSrc()));
            return false; // stale packet
        }
        return true;
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), m_Player, and syncDebugPrint().
Referenced by ProccessInputData().
CheckRequestSrc() [2/4]
override bool HandEventBase::CheckRequestSrc () inline private
Definition at line 237 of file hand_events.c.
    {
        if (false == GameInventory.CheckRequestSrc(m_Player, GetSrc(), GameInventory.c_MaxItemDistanceRadius))
        {
            syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(m_Player) + " failed src1 check with cmd=" + typename.EnumToString(HandEventID, GetEventID()) + " src1=" + InventoryLocation.DumpToStringNullSafe(GetSrc()));
            return false; // stale packet
        }
        return true;
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), m_Player, and syncDebugPrint().
CheckRequestSrc() [3/4]
override bool HandEventBase::CheckRequestSrc () inline private
Definition at line 298 of file hand_events.c.
    {
        if (false == GameInventory.CheckRequestSrc(m_Player, GetSrc(), GameInventory.c_MaxItemDistanceRadius))
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("Check src - failed, src = " + InventoryLocation.DumpToStringNullSafe(GetSrc()), typename.EnumToString(HandEventID, GetEventID()) , "n/a", "CheckRequestSrc", m_Player.ToString() );
            }
            #endif
            return false; // stale packet
        }
        return true;
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
CheckRequestSrc() [4/4]
override bool HandEventBase::CheckRequestSrc () inline private
Definition at line 457 of file hand_events.c.
    {
        if (false == GameInventory.CheckRequestSrc(m_Player, GetSrc(), GameInventory.c_MaxItemDistanceRadius))
        {
            syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(m_Player) + " failed src1 check with cmd=" + typename.EnumToString(HandEventID, GetEventID()) + " src1=" + InventoryLocation.DumpToStringNullSafe(GetSrc()));
            return false; // stale packet
        }
        if (false == GameInventory.CheckRequestSrc(m_Player, m_Src2, GameInventory.c_MaxItemDistanceRadius))
        {
            syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(m_Player) + " failed src2 check with cmd=" + typename.EnumToString(HandEventID, GetEventID()) + " src2=" + InventoryLocation.DumpToStringNullSafe(m_Src2));
            return false; // stale packet
        }
        return true;
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), GetSrc(), m_Player, and syncDebugPrint().
ClearInventoryReservation()
override void HandEventBase::ClearInventoryReservation () inline private
Definition at line 542 of file hand_events.c.
    {
        m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst.GetItem(), m_Dst);
        m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
    }
References m_Player.
Referenced by DeferredHandEvent::ClearInventoryReservation(), and ProccessInputData().
DumpToString() [1/3]
override string HandEventBase::DumpToString () inline private
Definition at line 279 of file hand_events.c.
    {
        string res = "{ HandEventMoveTo id=" + typename.EnumToString(HandEventID, GetEventID()) + " pl=" + Object.GetDebugName(m_Player) + " src=" + InventoryLocation.DumpToStringNullSafe(m_Src)  + " dst=" + InventoryLocation.DumpToStringNullSafe(m_Dst) + " }";
        return res;
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), m_Player, and m_Src.
Referenced by AcquireInventoryJunctureFromServer(), HandGuardBase::GuardCondition(), HandleHandEvent(), OnServerInventoryCommandStatic(), ProccessInputData(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), and SyncHandEventToRemote().
DumpToString() [2/3]
override string HandEventBase::DumpToString () inline private
Definition at line 517 of file hand_events.c.
    {
        return "{ HandEventSwap id=" + typename.EnumToString(HandEventID, GetEventID()) + " pl=" + Object.GetDebugName(m_Player) + " src1=" + InventoryLocation.DumpToStringNullSafe(m_Src) + " src2=" + InventoryLocation.DumpToStringNullSafe(m_Src2) + " dst1=" + InventoryLocation.DumpToStringNullSafe(m_Dst) + " dst2=" + InventoryLocation.DumpToStringNullSafe(m_Dst2) + " }";
    }
References InventoryLocation::DumpToStringNullSafe(), GetEventID(), m_Player, and m_Src.
DumpToString() [3/3]
override string HandEventBase::DumpToString () inline private
Definition at line 631 of file hand_events.c.
    {
        string res = "{ HandEvenReplaceWithNewBase id=" + typename.EnumToString(HandEventID, GetEventID()) + " pl=" + Object.GetDebugName(m_Player) + " src=" + InventoryLocation.DumpToStringNullSafe(GetSrc()) + " lambda=" + m_Lambda + " dst=" + InventoryLocation.DumpToStringNullSafe(GetDst()) + " }";
        return res;
    }
References InventoryLocation::DumpToStringNullSafe(), GetDst(), GetEventID(), GetSrc(), and m_Player.
GetDst() [1/5]
override InventoryLocation HandEventBase::GetDst () inline private
Definition at line 165 of file hand_events.c.
    {
        InventoryLocation dst = new InventoryLocation;
        dst.SetHands(m_Player, GetSrcEntity());
        return dst;
    }
References GetSrcEntity(), m_Player, and InventoryLocation::SetHands().
Referenced by AcquireInventoryJunctureFromServer(), HandActionBase::Action(), CanPerformEvent(), CheckRequest(), ClearInventoryReservation(), HandGuardBase::GuardCondition(), HandleHandEvent(), HandStateEquipped::OnEntry(), HandStateBase::OnEntry(), ProccessInputData(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), ReserveInventory(), and SendServerHandEventViaJuncture().
GetDst() [2/5]
override InventoryLocation HandEventBase::GetDst () inline private
Definition at line 235 of file hand_events.c.
{ return m_Dst; }
References m_Dst.
GetDst() [3/5]
override InventoryLocation HandEventBase::GetDst () inline private
Definition at line 290 of file hand_events.c.
    {
        InventoryLocation dst = new InventoryLocation;
        GameInventory.SetGroundPosByOwner(m_Player, GetSrcEntity(), dst);
        return dst;
    }
References GetSrcEntity(), and m_Player.
GetDst() [4/5]
override InventoryLocation HandEventBase::GetDst () inline private
Definition at line 447 of file hand_events.c.
    {
        return m_Dst;
    }
GetDst() [5/5]
override InventoryLocation HandEventBase::GetDst () inline private
Definition at line 624 of file hand_events.c.
    {
        InventoryLocation dst = new InventoryLocation;
        dst.SetHands(m_Player, GetSrcEntity());
        return dst;
    }
References GetSrcEntity(), m_Player, and InventoryLocation::SetHands().
GetSecondSrcEntity()
override EntityAI HandEventBase::GetSecondSrcEntity () inline private
Definition at line 452 of file hand_events.c.
    {
        return m_Src2.GetItem();
    }
Referenced by ProccessInputData().
HandAnimEventChanged()
void HandEventBase::HandAnimEventChanged (Man p = null, InventoryLocation src = null) inline private
Definition at line 662 of file hand_events.c.
{ m_EventID = HandEventID.ANIMEVENT_CHANGE_HIDE; }
References m_EventID.
Referenced by HandEventFactory().
HandEvengReplaceWithNewBase()
void HandEventBase::HandEvengReplaceWithNewBase (Man p = null, InventoryLocation src = null, ReplaceItemWithNewLambdaBase lambda = NULL) inline private
Definition at line 607 of file hand_events.c.
{ m_EventID = HandEventID.REPLACE; m_Lambda = lambda; }
References m_EventID.
HandEventCreated()
void HandEventBase::HandEventCreated (Man p = null, InventoryLocation src = null) inline private
Definition at line 594 of file hand_events.c.
{ m_EventID = HandEventID.CREATED; }
References m_EventID.
Referenced by HandEventFactory().
HandEventDestroy()
void HandEventBase::HandEventDestroy (Man p = null, InventoryLocation src = null) inline private
Definition at line 587 of file hand_events.c.
{ m_EventID = HandEventID.DESTROY; }
References m_EventID.
Referenced by HandEventFactory().
HandEventDestroyed()
void HandEventBase::HandEventDestroyed (Man p = null, InventoryLocation src = null) inline private
Definition at line 599 of file hand_events.c.
{ m_EventID = HandEventID.DESTROYED; }
References m_EventID.
Referenced by HandEventFactory().
HandEventDrop()
void HandEventBase::HandEventDrop (Man p = null, InventoryLocation src = null) inline private
Definition at line 288 of file hand_events.c.
{ m_EventID = HandEventID.DROP; }
References m_EventID.
HandEventHumanCommandActionAborted()
void HandEventBase::HandEventHumanCommandActionAborted (Man p = null, InventoryLocation src = null) inline private
Definition at line 685 of file hand_events.c.
{ m_EventID = HandEventID.HUMANCOMMAND_ACTION_ABORTED; }
References m_EventID.
Referenced by HandEventFactory().
HandEventHumanCommandActionFinished()
void HandEventBase::HandEventHumanCommandActionFinished (Man p = null, InventoryLocation src = null) inline private
Definition at line 679 of file hand_events.c.
{ m_EventID = HandEventID.HUMANCOMMAND_ACTION_FINISHED; }
References m_EventID.
Referenced by HandEventFactory().
HandEventMoveTo()
void HandEventBase::HandEventMoveTo (Man p = null, InventoryLocation src = null, InventoryLocation dst = null) inline private
destination for item in hands
Definition at line 221 of file hand_events.c.
{ m_EventID = HandEventID.MOVETO; m_Dst = dst; }
References m_EventID.
Referenced by HandEventFactory().
HandEventReplaced()
void HandEventBase::HandEventReplaced (Man p = null, InventoryLocation src = null) inline private
Definition at line 655 of file hand_events.c.
{ m_EventID = HandEventID.REPLACED; }
References m_EventID.
Referenced by HandEventFactory().
HandEventSwap()
void HandEventBase::HandEventSwap (Man p = null, InventoryLocation src = null, InventoryLocation src2 = null, InventoryLocation dst = null, InventoryLocation dst2 = null) inline private
Definition at line 415 of file hand_events.c.
    {
        m_EventID = HandEventID.SWAP;
        m_Dst = dst;
        m_Src2 = src2;
        m_Dst2 = dst2;
    }
References m_EventID.
HandEventTake()
void HandEventBase::HandEventTake (Man p = null, InventoryLocation src = null) inline private
Definition at line 163 of file hand_events.c.
{ m_EventID = HandEventID.TAKE; }
References m_EventID.
Referenced by HandEventFactory().
IsServerSideOnly() [1/2]
override bool HandEventBase::IsServerSideOnly () inline private
Definition at line 589 of file hand_events.c.
{ return true; }
Referenced by HandleHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), and SendServerHandEventViaJuncture().
IsServerSideOnly() [2/2]
override bool HandEventBase::IsServerSideOnly () inline private
Definition at line 622 of file hand_events.c.
{ return true; }
ReadFromContext() [1/3]
override void HandEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 223 of file hand_events.c.
    {
        m_Dst = new InventoryLocation;
        super.ReadFromContext(ctx);
        m_Dst.ReadFromContext(ctx);
    }
References InventoryLocation::ReadFromContext().
Referenced by CreateHandEventFromContext().
ReadFromContext() [2/3]
override void HandEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 423 of file hand_events.c.
    {
        super.ReadFromContext(ctx);
        m_Src2 = new InventoryLocation;
        m_Dst = new InventoryLocation;
        m_Dst2 = new InventoryLocation;
        m_Src2.ReadFromContext(ctx);
        m_Dst.ReadFromContext(ctx);
        m_Dst2.ReadFromContext(ctx);
        ctx.Read(m_Animation2ID);
    }
References Serializer::Read(), and InventoryLocation::ReadFromContext().
ReadFromContext() [3/3]
override void HandEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 609 of file hand_events.c.
    {
        super.ReadFromContext(ctx);
        ctx.Read(m_Type);
        Error("[hndfsm] HandEventDestroyAndReplaceWithNew - Cannot serialize lambda (read)");
    }
References Error(), m_Type, and Serializer::Read().
ReserveInventory()
override bool HandEventBase::ReserveInventory () inline private
Definition at line 528 of file hand_events.c.
    {
        if( !m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst.GetItem(), m_Dst, GameInventory.c_InventoryReservationTimeoutShortMS) )
        {
            return false;
        }
        if( !m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst2.GetItem(), m_Dst2, GameInventory.c_InventoryReservationTimeoutShortMS) )
        {
            m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst.GetItem(), m_Dst);
            return false;
        }
        return true;
    }
References m_Player.
Referenced by HumanInventory::ForceSwapEntities(), and DeferredHandEvent::ReserveInventory().
WriteToContext() [1/3]
override void HandEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 229 of file hand_events.c.
    {
        super.WriteToContext(ctx);
        m_Dst.WriteToContext(ctx);
    }
Referenced by InventoryInputUserData::SerializeHandEvent(), and SyncHandEventToRemote().
WriteToContext() [2/3]
override void HandEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 437 of file hand_events.c.
    {
        super.WriteToContext(ctx);
        m_Src2.WriteToContext(ctx);
        m_Dst.WriteToContext(ctx);
        m_Dst2.WriteToContext(ctx);
        ctx.Write(m_Animation2ID);
    }
References Serializer::Write().
WriteToContext() [3/3]
override void HandEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 615 of file hand_events.c.
    {
        super.WriteToContext(ctx);
        ctx.Write(m_Type);
        Error("[hndfsm] HandEventDestroyAndReplaceWithNew - Cannot serialize lambda (write)");
    }
References Error(), m_Type, and Serializer::Write().
Member Data Documentation
m_Animation2ID
int HandEventBase::m_Animation2ID = -1 private
destination for old item that was in hands
Definition at line 413 of file hand_events.c.
Referenced by HandGuardBase::GuardCondition().
m_Dst
ref InventoryLocation HandEventBase::m_Dst private
Definition at line 219 of file hand_events.c.
Referenced by HandActionBase::Action(), GetDst(), and HandStateBase::OnEntry().
m_Dst2
ref InventoryLocation HandEventBase::m_Dst2 private
src of old item in hands
Definition at line 412 of file hand_events.c.
m_Lambda
ref ReplaceItemWithNewLambdaBase HandEventBase::m_Lambda private
Definition at line 605 of file hand_events.c.
m_Src2
ref InventoryLocation HandEventBase::m_Src2 private
destination for new item (i.e. hands)
Definition at line 411 of file hand_events.c.
m_Type
string HandEventBase::m_Type private
Definition at line 604 of file hand_events.c.