DayzKode: ActionFillObject Class Reference
ActionFillObject Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionFillObject ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
protected const int EMPTY = 0
protected const int FILLED = 1
protected int m_ActionState
Detailed Description
Definition at line 9 of file actionfillobject.c.
Constructor & Destructor Documentation
ActionFillObject()
void ActionFillObject::ActionFillObject () inline private
Definition at line 16 of file actionfillobject.c.
    {
        m_CallbackClass = ActionFillObjectCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIG;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionFillObject::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 46 of file actionfillobject.c.
    {
        if ( player.IsPlacingLocal() )
            return false;
        HescoBox hesco;
        if ( Class.CastTo(hesco,target.GetObject()) )
        {
            if ( hesco.CanBeFilledAtPosition( player.GetPosition() ) )
            {
                if ( hesco.GetState() == HescoBox.UNFOLDED )
                {
                    m_ActionState = EMPTY;
                    return true;
                }
                else if( hesco.GetState() == HescoBox.FILLED)
                {
                    m_ActionState = FILLED;
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo(), EMPTY, FILLED, and m_ActionState.
CreateConditionComponents()
override void ActionFillObject::CreateConditionComponents () inline private
Definition at line 25 of file actionfillobject.c.
    {
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINonRuined;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnActionInfoUpdate()
override void ActionFillObject::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionfillobject.c.
    {
        HescoBox hesco = HescoBox.Cast(target.GetObject());
        if( hesco.GetState() == HescoBox.UNFOLDED )
        {
            m_Text =  "#empty";
        }
        else
        {
            m_Text =  "#fill";
        }
    }
References m_Text.
OnFinishProgressClient()
override void ActionFillObject::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 94 of file actionfillobject.c.
    {
        HescoBox hesco;
        if ( Class.CastTo(hesco,action_data.m_Target.GetObject()) )
        {
            if ( hesco.GetState() == HescoBox.UNFOLDED )
            {
                hesco.Fill();
            }
            else if ( hesco.GetState() == HescoBox.FILLED )
            {
                hesco.Unfold();
            }
        }
    }
References Class::CastTo(), and ActionData::m_Target.
OnFinishProgressServer()
override void ActionFillObject::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 72 of file actionfillobject.c.
    {
        HescoBox hesco;
        if ( Class.CastTo(hesco,action_data.m_Target.GetObject()) )
        {
            const float ITEM_DAMAGE = 0.05;
            action_data.m_MainItem.DecreaseHealth ( "", "", action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus( ITEM_DAMAGE, this.GetSpecialtyWeight() )*100 );
            if ( hesco.GetState() == HescoBox.UNFOLDED )
            {
                hesco.Fill();
            }
            else if ( hesco.GetState() == HescoBox.FILLED )
            {
                hesco.Unfold();
            }
        }
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and ItemBase::Unfold().
Member Data Documentation
EMPTY
protected const int ActionFillObject::EMPTY = 0 private
Definition at line 13 of file actionfillobject.c.
Referenced by ActionCondition().
FILLED
protected const int ActionFillObject::FILLED = 1 private
Definition at line 14 of file actionfillobject.c.
Referenced by ActionCondition().
m_ActionState
protected int ActionFillObject::m_ActionState private
Definition at line 11 of file actionfillobject.c.
Referenced by ActionCondition().