DayzKode: InputUtils Class Reference
InputUtils Class Reference
Static Private Member Functions
static array< string > GetButtonIconPathFromInput (notnull UAInput pInput, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER)
static array< string > GetButtonIconPathFromInput (string pInputName, int pInputDeviceType)
static string GetButtonNameFromInput (string pInputName, int pInputDeviceType)
static map< int, ref TStringArray > GetComboButtonNamesFromInput (string pInputName, int pInputDeviceType)
returns a map of button names, combo or not
static int GetConsolePresetID ()
static void GetImagesetAndIconFromInputAction (notnull UAInput pInput, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName)
static void GetImagesetAndIconFromInputAction (string pInputAction, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName)
static map< int, ref array< int > > GetInputActionSortingMap ()
static string GetRichtextButtonIconFromInputAction (notnull UAInput pInput, string pLocalizedDescription, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER, float pScale=ICON_SCALE_NORMAL, bool pVertical=false)
static string GetRichtextButtonIconFromInputAction (string pInputAction, string pLocalizedDescription, int pInputDeviceType=EUAINPUT_DEVICE_CONTROLLER, float pScale=ICON_SCALE_NORMAL, bool pVertical=false)
static array< int > GetUnsortedInputActions ()
static bool InitInputMetadata ()
static void UpdateConsolePresetID ()
Static Private Attributes
static const float ICON_SCALE_NORMAL = 1.21
static const float ICON_SCALE_TOOLBAR = 1.81
static int m_CurrentPresetIDConsole = -1
static protected ref map< int, ref array< int > > m_InputActionSortingMap
static protected ref array< int > m_UnsortedInputActions
static const string PRESET_NEW = "#STR_UAPRESET_1"
static const string PRESET_OLD = "#STR_UAPRESET_0"
static const int VARIANT_NEW = 1
static const int VARIANT_OLD = 0
Detailed Description
Definition at line 1 of file inpututils.c.
Member Function Documentation
GetButtonIconPathFromInput() [1/2]
static array< string > InputUtils::GetButtonIconPathFromInput (notnull UAInput pInput, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER) inline static private
Definition at line 77 of file inpututils.c.
    {
        array<string> buttonIcons = new array<string>();
        for (int i = 0; i < pInput.AlternativeCount(); i++)
        {
            pInput.SelectAlternative(i);
            bool done = false;
            for (int bk = 0; bk < pInput.BindKeyCount(); bk++)
            {
                if (pInput.CheckBindDevice(0, pInputDeviceType))
                {
                    buttonIcons.Insert(GetUApi().GetButtonIcon(pInput.Binding(bk)));
                    if (bk == pInput.BindKeyCount() - 1)
                    {
                        done = true;
                    }
                }
            }
            if (done)
            {
                buttonIcons.Invert();
                return buttonIcons;
            }
        }
        return buttonIcons;
    }
References GetUApi().
Referenced by GetButtonIconPathFromInput(), and GetImagesetAndIconFromInputAction().
GetButtonIconPathFromInput() [2/2]
static array< string > InputUtils::GetButtonIconPathFromInput (string pInputName, int pInputDeviceType) inline static private
Definition at line 108 of file inpututils.c.
    {
        UAInput inp = GetUApi().GetInputByName(pInputName);
        array<string> buttonIcons = new array<string>();
        buttonIcons = InputUtils.GetButtonIconPathFromInput(inp, pInputDeviceType);
        return buttonIcons;
    }
References GetButtonIconPathFromInput(), UAInputAPI::GetInputByName(), and GetUApi().
GetButtonNameFromInput()
static string InputUtils::GetButtonNameFromInput (string pInputName, int pInputDeviceType) inline static private
Definition at line 17 of file inpututils.c.
    {
        UAInput inp = GetUApi().GetInputByName(pInputName);
        for (int i = 0; i < inp.AlternativeCount(); i++)
        {
            inp.SelectAlternative(i);
            if (inp.CheckBindDevice(0, pInputDeviceType))
            {
                return GetUApi().GetButtonName(inp.GetBindKey(0));
            }
        }
        return "";
    }
References UAInput::AlternativeCount(), UAInput::CheckBindDevice(), UAInput::GetBindKey(), UAInputAPI::GetButtonName(), UAInputAPI::GetInputByName(), GetUApi(), and UAInput::SelectAlternative().
Referenced by ScriptedWidgetEventHandler::SetInteractActionIcon().
GetComboButtonNamesFromInput()
static map< int, ref TStringArray > InputUtils::GetComboButtonNamesFromInput (string pInputName, int pInputDeviceType) inline static private
returns a map of button names, combo or not
Definition at line 33 of file inpututils.c.
    {
        UAInput inp = GetUApi().GetInputByName(pInputName);
        TStringArray buttons;
        map<int,ref TStringArray> output;//<alternativeIDX<button_array>>
        for (int i = 0; i < inp.AlternativeCount(); i++)
        {
            inp.SelectAlternative(i);
            if (inp.BindingCount() > 0 && inp.Binding(0) != 0 && inp.CheckBindDevice(0,pInputDeviceType))
            {
                buttons = new TStringArray;
                if (inp.IsCombo())
                {
                    buttons.Insert(GetUApi().GetButtonName( inp.Binding(0) ));
                    for (int j = 1; j < inp.BindingCount(); j++)
                    {
                        if (inp.Binding(j) != 0 && inp.CheckBindDevice(j,pInputDeviceType))
{
                            buttons.Insert(GetUApi().GetButtonName( inp.Binding(j) ));
                        }
                    }
                    //return buttons;
                }
                else
                {
                    buttons.Insert(GetUApi().GetButtonName(inp.GetBindKey(0)));
                    //return buttons;
                }
                if (buttons.Count() > 0)
                {
                    if (!output)
                    {
                        output = new map<int,ref TStringArray>;
                    }
                    output.Insert(i,buttons);
                }
            }
        }
        return output;
    }
References UAInput::AlternativeCount(), UAInput::Binding(), UAInput::BindingCount(), UAInput::CheckBindDevice(), UAInput::GetBindKey(), UAInputAPI::GetInputByName(), GetUApi(), UAInput::IsCombo(), and UAInput::SelectAlternative().
Referenced by GetBoundButtonText().
GetConsolePresetID()
static int InputUtils::GetConsolePresetID () inline static private
Definition at line 224 of file inpututils.c.
    {
        return m_CurrentPresetIDConsole;
    }
References m_CurrentPresetIDConsole.
Referenced by UIScriptedMenu::UpdateTabContent().
GetImagesetAndIconFromInputAction() [1/2]
static void InputUtils::GetImagesetAndIconFromInputAction (notnull UAInput pInput, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName) inline static private
Asia vs Europe/N.America controller layout
Definition at line 118 of file inpututils.c.
    {
        array<string> buttons = InputUtils.GetButtonIconPathFromInput(pInput, pInputDeviceType);
        if (buttons.Count() == 0 )
        {
            return;
        }
        for (int i = 0; i < buttons.Count(); i++)
        {
            array<string> parts = new array<string>;
            buttons.Get(i).Split(":", parts);
            if (parts.Count() < 2)
            {
                return;
            }
            pImageSet.Insert(parts[1].SubstringInverted(parts[1], parts[1].Length() - 6, parts[1].Length()));
            #ifdef PLATFORM_PS4
            if (GetGame().GetInput().GetEnterButton() == GamepadButton.B)
            {
                if (parts[2] == "cross")
                {
                    parts[2] = "circle";
                }
                if (parts[2] == "circle")
                {
                    parts[2] = "cross";
                }
            }
            #endif
            pIconName.Insert(parts[2]);
        }
    }
References GetButtonIconPathFromInput(), GetGame(), and GetInput().
Referenced by GetImagesetAndIconFromInputAction(), and GetRichtextButtonIconFromInputAction().
GetImagesetAndIconFromInputAction() [2/2]
static void InputUtils::GetImagesetAndIconFromInputAction (string pInputAction, int pInputDeviceType, out array< string > pImageSet, out array< string > pIconName) inline static private
Definition at line 160 of file inpututils.c.
    {
        UAInput inp = GetUApi().GetInputByName(pInputAction);
        InputUtils.GetImagesetAndIconFromInputAction(inp, pInputDeviceType, pImageSet, pIconName);
    }
References GetImagesetAndIconFromInputAction(), UAInputAPI::GetInputByName(), and GetUApi().
GetInputActionSortingMap()
static map< int, ref array< int > > InputUtils::GetInputActionSortingMap () inline static private
Definition at line 229 of file inpututils.c.
    {
        return m_InputActionSortingMap;
    }
References m_InputActionSortingMap.
Referenced by array::AddSubgroup(), array::CreateSubgroups(), and UIScriptedMenu::CreateTabs().
GetRichtextButtonIconFromInputAction() [1/2]
static string InputUtils::GetRichtextButtonIconFromInputAction (notnull UAInput pInput, string pLocalizedDescription, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER, float pScale = ICON_SCALE_NORMAL, bool pVertical = false) inline static private
first element is already taken
Definition at line 167 of file inpututils.c.
    {
        array<string> imageSets = new array<string>();
        array<string> iconNames = new array<string>();
        InputUtils.GetImagesetAndIconFromInputAction(pInput, pInputDeviceType, imageSets, iconNames);
        if (imageSets.Count() == 0)
        {
            return "";
        }
        string result = string.Format("<image set=\"%1\" name=\"%2\" scale=\"%3\" />", imageSets.Get(0), iconNames.Get(0), pScale);
        string divider = " ";
        if (pVertical)
        {
            divider = string.Format("\n%1\n", divider);
        }
        if (imageSets.Count() > 1)
        {
            for (int i = 1; i < imageSets.Count(); i++)
            {
                result = string.Format("%1%2<image set=\"%3\" name=\"%4\" scale=\"%5\" />", result, divider, imageSets.Get(i), iconNames.Get(i), pScale);
            }
        }
        return string.Format("%1 %2", result, pLocalizedDescription);
    }
References string::Format(), and GetImagesetAndIconFromInputAction().
Referenced by ConsoleToolbarTypeToString(), GetRichtextButtonIconFromInputAction(), UIScriptedMenu::Init(), Init(), Inventory(), ScriptedWidgetEventHandler::SetControllerIcon(), UpdateConsoleToolbar(), UIScriptedMenu::UpdateControlsElements(), ScriptedWidgetEventHandler::UpdateControlsElements(), and UIScriptedMenu::UpdateInfoPanelText().
GetRichtextButtonIconFromInputAction() [2/2]
static string InputUtils::GetRichtextButtonIconFromInputAction (string pInputAction, string pLocalizedDescription, int pInputDeviceType = EUAINPUT_DEVICE_CONTROLLER, float pScale = ICON_SCALE_NORMAL, bool pVertical = false) inline static private
Definition at line 198 of file inpututils.c.
    {
        UAInput inp = GetUApi().GetInputByName(pInputAction);
        array<string> imageSets = new array<string>();
        array<string> iconNames = new array<string>();
        InputUtils.GetImagesetAndIconFromInputAction(inp, pInputDeviceType, imageSets, iconNames);
        return InputUtils.GetRichtextButtonIconFromInputAction(inp, pLocalizedDescription, pInputDeviceType, pScale, pVertical);
    }
References GetImagesetAndIconFromInputAction(), UAInputAPI::GetInputByName(), GetRichtextButtonIconFromInputAction(), and GetUApi().
GetUnsortedInputActions()
static array< int > InputUtils::GetUnsortedInputActions () inline static private
Definition at line 234 of file inpututils.c.
    {
        return m_UnsortedInputActions;
    }
References m_UnsortedInputActions.
Referenced by array::AddSubgroup(), array::CreateSubgroups(), and UIScriptedMenu::CreateTabs().
InitInputMetadata()
static bool InputUtils::InitInputMetadata () inline static private
Definition at line 239 of file inpututils.c.
    {
        if (!m_InputActionSortingMap)
        {
            m_InputActionSortingMap = new map<int, ref array<int>>;
            TIntArray sorted_actions = new TIntArray;
            if (!m_UnsortedInputActions)
            {
                m_UnsortedInputActions = new array<int>;
            }
            GetUApi().GetActiveInputs(m_UnsortedInputActions);
            UAInput inp;
            for (int i = 0; i < GetUApi().SortingCount(); i++)
            {
                int input_id;
                array<int> sorting_content = new array<int>;
                for (int j = 0; j < m_UnsortedInputActions.Count(); j++)
                {
                    input_id = m_UnsortedInputActions[j];
                    inp = GetUApi().GetInputByID(input_id);
                    if (inp.HasSorting(i))
                    {
                        sorting_content.Insert(input_id);
                        sorted_actions.Insert(input_id);
                    }
                }
                if (sorting_content.Count() > 0)
                {
                    sorting_content.Sort();
                    m_InputActionSortingMap.Insert(i,sorting_content);
                }
            }
            //remove sorted used inputs
            int count = sorted_actions.Count();
            for (i = 0; i < count; i++)
            {
                m_UnsortedInputActions.RemoveItem(sorted_actions[i]);
            }
            return true;
        }
        return false;
    }
References UAInputAPI::GetActiveInputs(), UAInputAPI::GetInputByID(), GetUApi(), UAInput::HasSorting(), m_InputActionSortingMap, m_UnsortedInputActions, and UAInputAPI::SortingCount().
Referenced by UIScriptedMenu::InitInputSortingMap().
UpdateConsolePresetID()
static void InputUtils::UpdateConsolePresetID () inline static private
Definition at line 209 of file inpututils.c.
    {
        string profile_name;
        GetGame().GetInput().GetProfileName(GetUApi().PresetCurrent(), profile_name);
        if (profile_name == PRESET_OLD)
        {
            m_CurrentPresetIDConsole = VARIANT_OLD;
        }
        else
        {
            m_CurrentPresetIDConsole = VARIANT_NEW;
        }
    }
References GetGame(), CGame::GetInput(), Input::GetProfileName(), GetUApi(), m_CurrentPresetIDConsole, PRESET_OLD, VARIANT_NEW, and VARIANT_OLD.
Referenced by UIScriptedMenu::ComposeData(), and UIScriptedMenu::PerformSwitchPreset().
Member Data Documentation
ICON_SCALE_NORMAL
const float InputUtils::ICON_SCALE_NORMAL = 1.21 static private
Definition at line 14 of file inpututils.c.
ICON_SCALE_TOOLBAR
const float InputUtils::ICON_SCALE_TOOLBAR = 1.81 static private
Definition at line 15 of file inpututils.c.
Referenced by ConsoleToolbarTypeToString(), UIScriptedMenu::Init(), Init(), UpdateConsoleToolbar(), UIScriptedMenu::UpdateControlsElements(), ScriptedWidgetEventHandler::UpdateControlsElements(), and UIScriptedMenu::UpdateInfoPanelText().
m_CurrentPresetIDConsole
int InputUtils::m_CurrentPresetIDConsole = -1 static private
Definition at line 8 of file inpututils.c.
Referenced by GetConsolePresetID(), and UpdateConsolePresetID().
m_InputActionSortingMap
protected ref map<int, ref array<int> > InputUtils::m_InputActionSortingMap static private
Definition at line 11 of file inpututils.c.
Referenced by GetInputActionSortingMap(), and InitInputMetadata().
m_UnsortedInputActions
protected ref array<int> InputUtils::m_UnsortedInputActions static private
Definition at line 12 of file inpututils.c.
Referenced by GetUnsortedInputActions(), and InitInputMetadata().
PRESET_NEW
const string InputUtils::PRESET_NEW = "#STR_UAPRESET_1" static private
Definition at line 5 of file inpututils.c.
Referenced by UIScriptedMenu::UpdateToolbarText().
PRESET_OLD
const string InputUtils::PRESET_OLD = "#STR_UAPRESET_0" static private
Definition at line 4 of file inpututils.c.
Referenced by UpdateConsolePresetID(), and UIScriptedMenu::UpdateToolbarText().
VARIANT_NEW
const int InputUtils::VARIANT_NEW = 1 static private
Definition at line 7 of file inpututils.c.
Referenced by UpdateConsolePresetID().
VARIANT_OLD
const int InputUtils::VARIANT_OLD = 0 static private
Definition at line 6 of file inpututils.c.
Referenced by UpdateConsolePresetID().