DayzKode: EffEngineSmoke Class Reference
EffEngineSmoke Class Reference
Private Member Functions
void EffEngineSmoke ()
override void Event_OnFrameUpdate (float time_delta)
override void SetParticleStateHeavy ()
override void SetParticleStateLight ()
Private Attributes
private float m_Time
Static Private Attributes
static private float m_UpdateInterval = 2
Detailed Description
Definition at line 1 of file enginesmoke.c.
Constructor & Destructor Documentation
EffEngineSmoke()
void EffEngineSmoke::EffEngineSmoke () inline private
Definition at line 6 of file enginesmoke.c.
    {
        SetEnableEventFrame(true);
    }
References SetEnableEventFrame().
Member Function Documentation
Event_OnFrameUpdate()
override void EffEngineSmoke::Event_OnFrameUpdate (float time_delta) inline private
Definition at line 21 of file enginesmoke.c.
    {
        m_Time += time_delta;
        if (m_Time >= m_UpdateInterval)
        {
            m_Time = 0;
            Car parent = Car.Cast( GetAttachmentParent() );
            if (parent)
            {
                Particle p = GetParticle();
                if (p)
                {
                    SetParticleState( p.GetParticleID() );
                    float speed = parent.GetSpeedometerAbsolute();
                    float lifetime_scale;
                    if (speed < 100)
                        lifetime_scale = (100 - speed) / 100;
                    else
                        lifetime_scale = 0.1;
                    float birthrate_scale = 1 + (speed * 0.02 );
                    p.ScaleParticleParamFromOriginal( EmitorParam.LIFETIME, lifetime_scale );
                    p.ScaleParticleParamFromOriginal( EmitorParam.LIFETIME_RND, lifetime_scale );
                    p.ScaleParticleParamFromOriginal( EmitorParam.BIRTH_RATE, birthrate_scale );
                    p.ScaleParticleParamFromOriginal( EmitorParam.BIRTH_RATE_RND, birthrate_scale );
                }
            }
        }
    }
References GetAttachmentParent(), EffectParticle::GetParticle(), Particle::GetParticleID(), m_Time, m_UpdateInterval, Particle::ScaleParticleParamFromOriginal(), and EffVehicleSmoke::SetParticleState().
SetParticleStateHeavy()
override void EffEngineSmoke::SetParticleStateHeavy () inline private
Definition at line 16 of file enginesmoke.c.
    {
        SetParticleState( ParticleList.HATCHBACK_ENGINE_OVERHEATED );
    }
References ParticleList::HATCHBACK_ENGINE_OVERHEATED, and EffVehicleSmoke::SetParticleState().
SetParticleStateLight()
override void EffEngineSmoke::SetParticleStateLight () inline private
Definition at line 11 of file enginesmoke.c.
    {
        SetParticleState( ParticleList.HATCHBACK_ENGINE_OVERHEATING );
    }
References ParticleList::HATCHBACK_ENGINE_OVERHEATING, and EffVehicleSmoke::SetParticleState().
Member Data Documentation
m_Time
private float EffEngineSmoke::m_Time private
Definition at line 3 of file enginesmoke.c.
Referenced by Event_OnFrameUpdate().
m_UpdateInterval
private float EffEngineSmoke::m_UpdateInterval = 2 static private
Definition at line 4 of file enginesmoke.c.
Referenced by Event_OnFrameUpdate().