DayzKode: PumpkinHelmet Class Reference
PumpkinHelmet Class Reference
Private Member Functions
override bool CanPutAsAttachment (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EOnInit (IEntity other, int extra)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnMovedInsideCargo (EntityAI container)
override void OnMovedWithinCargo (EntityAI container)
override void OnRemovedFromCargo (EntityAI container)
void PumpkinHelmet ()
void UpdateGlowState ()
override void UpdateNVGStatus (PlayerBase player, bool attaching=false, bool force_disable=false)
Detailed Description
Definition at line 3 of file pumpkinhelmet.c.
Constructor & Destructor Documentation
PumpkinHelmet()
void PumpkinHelmet::PumpkinHelmet () inline private
Definition at line 5 of file pumpkinhelmet.c.
    {
        SetEventMask(EntityEvent.INIT); // Enable EOnInit event
    }
Member Function Documentation
CanPutAsAttachment()
override bool PumpkinHelmet::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 10 of file pumpkinhelmet.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        Clothing eyewear = Clothing.Cast(parent.FindAttachmentBySlotName("Eyewear"));
        if ( eyewear && eyewear.ConfigGetBool("isStrap") )
        {
            return false;
        }
        Clothing mask = Clothing.Cast(parent.FindAttachmentBySlotName("Mask"));
        if ( mask && (mask.ConfigGetBool("noHelmet") && !HockeyMask.Cast(mask) && !SantasBeard.Cast(mask)) ) //TODO
        {
            return false;
        }
        return true;
    }
EEHealthLevelChanged()
override void PumpkinHelmet::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 56 of file pumpkinhelmet.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        UpdateGlowState();
    }
References UpdateGlowState().
EOnInit()
override void PumpkinHelmet::EOnInit (IEntity other, int extra) inline private
Definition at line 44 of file pumpkinhelmet.c.
    {
        UpdateGlowState();
    }
References UpdateGlowState().
OnItemLocationChanged()
override void PumpkinHelmet::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 49 of file pumpkinhelmet.c.
    {
        super.OnItemLocationChanged( old_owner, new_owner);
        UpdateGlowState();
    }
References UpdateGlowState().
OnMovedInsideCargo()
override void PumpkinHelmet::OnMovedInsideCargo (EntityAI container) inline private
Definition at line 29 of file pumpkinhelmet.c.
    {
        UpdateGlowState();
    }
References UpdateGlowState().
OnMovedWithinCargo()
override void PumpkinHelmet::OnMovedWithinCargo (EntityAI container) inline private
Definition at line 34 of file pumpkinhelmet.c.
    {
        UpdateGlowState();
    }
References UpdateGlowState().
OnRemovedFromCargo()
override void PumpkinHelmet::OnRemovedFromCargo (EntityAI container) inline private
Definition at line 39 of file pumpkinhelmet.c.
    {
        UpdateGlowState();
    }
References UpdateGlowState().
UpdateGlowState()
void PumpkinHelmet::UpdateGlowState () inline private
Definition at line 63 of file pumpkinhelmet.c.
    {
        // Makes sure PumpkinHelmet doesn't glow when it's attached on head, or it's inside cargo.
        bool do_glow = true;
        if ( IsDamageDestroyed() )
        {
            do_glow = false;
        }
        else
        {
            int id = InventorySlots.HEADGEAR;
            InventoryLocation IL = new InventoryLocation();
            GetInventory().GetCurrentInventoryLocation( IL );
            int id_2 = IL.GetSlot();
            int id_cargo = IL.GetIdx();
            if ( id == id_2) // Pumpkin is attached on head
                do_glow = false;
            if ( id_cargo != -1 ) // Pumpkin is in cargo
                do_glow = false;
        }
        SetPilotLight(do_glow);
    }
References InventoryLocation::GetIdx(), InventoryLocation::GetSlot(), and IsDamageDestroyed().
Referenced by EEHealthLevelChanged(), EOnInit(), OnItemLocationChanged(), OnMovedInsideCargo(), OnMovedWithinCargo(), and OnRemovedFromCargo().
UpdateNVGStatus()
override void PumpkinHelmet::UpdateNVGStatus (PlayerBase player, bool attaching = false, bool force_disable = false) inline private
Definition at line 92 of file pumpkinhelmet.c.
    {
        if ( !GetGame().IsDedicatedServer() ) //SP only
        {
            if (force_disable)
            {
                player.RemoveActiveNV(NVTypes.NV_PUMPKIN);
            }
            else
            {
                if ( attaching && (!player.IsNVGWorking() || player.GetNVType() != NVTypes.NV_PUMPKIN) )
                {
                    player.AddActiveNV(NVTypes.NV_PUMPKIN);
                }
                else if ( !attaching && player.IsNVGWorking() )
                {
                    player.RemoveActiveNV(NVTypes.NV_PUMPKIN);
                }
            }
        }
    }
References GetGame().