DayzKode: SceneObject Class Reference
SceneObject Class Reference
Private Member Functions
void AddAttachment (string att_name)
void AddRotation (float add_rot)
bool CanAttachment (EntityAI e)
void EditorLineAdd (SceneObject obj)
void EditorLineRemove (SceneObject obj)
void EditorShapeAdd ()
void EditorShapeDeselect ()
void EditorShapeRemove ()
void EditorShapeSelect ()
void EditorShapeSetColor (int color)
void EditorShapeUpdatePos ()
array< EntityAI > GetAttachments ()
TStringArray GetConfigAttachments ()
float GetHealth ()
string GetInitScript ()
EntityAI GetLinkedObject (int i)
SceneObject GetLinkedSceneObject (int i)
array< SceneObject > GetLinkedSceneObjects ()
int GetLinkedSceneObjectsCount ()
float GetMaxHealth ()
string GetName ()
EntityAI GetObject ()
vector GetPosition ()
string GetPositionAsString ()
float GetRotation ()
vector GetSize ()
string GetTypeName ()
SceneObject Init (string obj_name, vector pos)
bool IsLinkedWithSceneObject (SceneObject scene_object)
bool IsPlayer ()
override bool IsPlayer ()
void LinkEntityAI (EntityAI e)
void LinkSceneObject (SceneObject scene_object, bool draw_line=true)
void PlaceOnSurface ()
void RemoveAttachment (EntityAI e)
void SceneObjectSynch (Param p)
void SetHealth (float value)
void SetInitScript (string init_script)
void SetPosition (vector pos)
void SetPositionAsString (string string_pos)
void SetRotation (float rot)
void UnlinkAll ()
void UnlinkSceneObject (SceneObject scene_object)
void ~SceneObject ()
Private Attributes
protected Shape m_DebugShapeBBox
protected string m_InitScript
protected ref array< SceneObject > m_LinkedSceneObjects
ref array< int > m_LinkedSceneObjectsIndices
protected ref map< SceneObject, Shape > m_LinkedSceneObjectsShapes
protected string m_ObjectName
protected string m_ObjectNameOrigin
protected EntityAI m_ObjectPtr
Static Private Attributes
static const int COLOR_OBJ_BBOX_NORMAL = 0x00000000
static const int COLOR_OBJ_BBOX_SELECT = 0x1f007C00
Detailed Description
Definition at line 1 of file sceneobject.c.
Constructor & Destructor Documentation
~SceneObject()
void SceneObject::~SceneObject () inline private
Definition at line 357 of file sceneobject.c.
    {
        if ( m_ObjectPtr && m_ObjectPtr != GetGame().GetPlayer() )
        {
            GetGame().ObjectDelete( m_ObjectPtr );
            m_ObjectPtr = NULL;
        }
        for ( int i = 0; i < m_LinkedSceneObjects.Count(); i++ )
        {
            EditorLineRemove( m_LinkedSceneObjects.Get(i) );
        }
        EditorShapeRemove();
    }
References EditorLineRemove(), EditorShapeRemove(), GetGame(), GetPlayer(), m_LinkedSceneObjects, m_ObjectPtr, and CGame::ObjectDelete().
Member Function Documentation
AddAttachment()
void SceneObject::AddAttachment (string att_name) inline private
Definition at line 543 of file sceneobject.c.
    {
        GetObject().GetInventory().CreateAttachment(att_name);
    }
References GetObject().
Referenced by PluginBase::SelectedObjectDuplicate().
AddRotation()
void SceneObject::AddRotation (float add_rot) inline private
Definition at line 520 of file sceneobject.c.
    {
        if ( m_ObjectPtr )
        {
            if ( GetGame().IsClient() && GetGame().IsMultiplayer() )
            {
                Param par = new Param3<string, EntityAI, Param>( "AddRotation" , m_ObjectPtr, new Param1<float>( add_rot ) );
                SceneObjectSynch( par );
            }
            else
            {
                vector v = m_ObjectPtr.GetOrientation();
                v[0] = v[0] + add_rot;
                m_ObjectPtr.SetOrientation( v );
                EditorShapeUpdatePos();
            }
        }
    }
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, and SceneObjectSynch().
CanAttachment()
bool SceneObject::CanAttachment (EntityAI e) inline private
Definition at line 551 of file sceneobject.c.
    {
        return GetObject().GetInventory().CanAddAttachment(e);
    }
References GetObject().
EditorLineAdd()
void SceneObject::EditorLineAdd (SceneObject obj) inline private
Definition at line 233 of file sceneobject.c.
    {
        if ( obj.GetObject() != NULL && GetObject() != NULL )
        {
            if ( m_LinkedSceneObjectsShapes.Contains(obj) )
            {
                EditorLineRemove(obj);
            }
            vector pos1 = obj.GetSize();
            pos1[0] = 0; pos1[1] = pos1[1] / 2; pos1[2] = 0;
            pos1 = pos1 + obj.GetObject().GetPosition();
            vector pos2 = GetSize();
            pos2[0] = 0; pos2[1] = pos2[1] / 2; pos2[2] = 0;
            pos2 = pos2 + GetObject().GetPosition();
            m_LinkedSceneObjectsShapes.Insert( obj, Debug.DrawArrow( pos1, pos2 ) );
        }
    }
References Debug::DrawArrow(), EditorLineRemove(), GetObject(), GetSize(), and m_LinkedSceneObjectsShapes.
Referenced by PluginBase::EditorUpdate(), and LinkSceneObject().
EditorLineRemove()
void SceneObject::EditorLineRemove (SceneObject obj) inline private
Definition at line 217 of file sceneobject.c.
    {
        for ( int i = 0; i < m_LinkedSceneObjectsShapes.Count(); i++ )
        {
            if ( m_LinkedSceneObjectsShapes.GetKey(i) == obj )
            {
                m_LinkedSceneObjectsShapes.GetElement(i).Destroy();
                m_LinkedSceneObjectsShapes.Remove( obj );
                break;
            }
        }
    }
References m_LinkedSceneObjectsShapes.
Referenced by EditorLineAdd(), PluginBase::EditorUpdate(), UnlinkSceneObject(), and ~SceneObject().
EditorShapeAdd()
void SceneObject::EditorShapeAdd () inline private
Definition at line 168 of file sceneobject.c.
    {
        if ( m_DebugShapeBBox != NULL )
        {
            return;
        }
        vector min      = "0 0 0";
        vector max      = "0 0 0";
        vector size = GetSize();
        float width     = size[0];
        float height    = size[1];
        float length    = size[2];
        float width_h = width*0.5;
        float lenght_h = length*0.5;
        min[0] = -width_h;
        min[1] = 0;
        min[2] = -lenght_h;
        max[0] = width_h;
        max[1] = height;
        max[2] = lenght_h;
        //Log("EditorShapeAdd -> "+m_ObjectPtr.Ptr().GetType());
        m_DebugShapeBBox = Debug.DrawBox(min, max);
        EditorShapeUpdatePos();
        EditorShapeDeselect();
    }
References Debug::DrawBox(), EditorShapeDeselect(), EditorShapeUpdatePos(), GetSize(), and m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate().
EditorShapeDeselect()
void SceneObject::EditorShapeDeselect () inline private
Definition at line 134 of file sceneobject.c.
    {
        EditorShapeSetColor(COLOR_OBJ_BBOX_NORMAL);
    }
References COLOR_OBJ_BBOX_NORMAL, and EditorShapeSetColor().
Referenced by EditorShapeAdd(), and PluginBase::EditorUpdate().
EditorShapeRemove()
void SceneObject::EditorShapeRemove () inline private
Definition at line 205 of file sceneobject.c.
    {
        if ( m_DebugShapeBBox != NULL )
        {
            m_DebugShapeBBox.Destroy();
            m_DebugShapeBBox = NULL;
        }
    }
References m_DebugShapeBBox.
Referenced by PluginBase::EditorUpdate(), and ~SceneObject().
EditorShapeSelect()
void SceneObject::EditorShapeSelect () inline private
Definition at line 126 of file sceneobject.c.
    {
        EditorShapeSetColor(COLOR_OBJ_BBOX_SELECT);
    }
References COLOR_OBJ_BBOX_SELECT, and EditorShapeSetColor().
Referenced by PluginBase::EditorUpdate().
EditorShapeSetColor()
void SceneObject::EditorShapeSetColor (int color) inline private
Definition at line 115 of file sceneobject.c.
    {
        if ( m_DebugShapeBBox )
        {
            m_DebugShapeBBox.SetColor(color);
        }
    }
References m_DebugShapeBBox.
Referenced by EditorShapeDeselect(), and EditorShapeSelect().
EditorShapeUpdatePos()
void SceneObject::EditorShapeUpdatePos () inline private
Definition at line 98 of file sceneobject.c.
    {
        if ( m_DebugShapeBBox != NULL )
        {
            vector mat[4];
            GetObject().GetTransform(mat);
            if ( m_DebugShapeBBox != NULL )
            {
                m_DebugShapeBBox.SetMatrix(mat);
            }
        }
    }
References GetObject(), and m_DebugShapeBBox.
Referenced by AddRotation(), EditorShapeAdd(), SetPosition(), and SetRotation().
GetAttachments()
array< EntityAI > SceneObject::GetAttachments () inline private
Definition at line 567 of file sceneobject.c.
    {
        array<EntityAI> ret = new array<EntityAI>;
        for ( int i = 0; i < GetObject().GetInventory().AttachmentCount(); ++i )
        {
            ret.Insert(GetObject().GetInventory().GetAttachmentFromIndex(i));
        }
        return ret;
    }
References GetObject().
Referenced by PluginBase::SelectedObjectDuplicate().
GetConfigAttachments()
TStringArray SceneObject::GetConfigAttachments () inline private
Definition at line 582 of file sceneobject.c.
    {
        string          type_name = GetTypeName();
        TStringArray    cfg_attachments = new TStringArray;
        string cfg_path;
        if ( GetGame().ConfigIsExisting(CFG_VEHICLESPATH+" "+type_name) )
        {
            cfg_path = CFG_VEHICLESPATH+" "+type_name+" attachments";
        }
        else if ( GetGame().ConfigIsExisting(CFG_WEAPONSPATH+" "+type_name) )
        {
            cfg_path = CFG_WEAPONSPATH+" "+type_name+" attachments";
        }
        else if ( GetGame().ConfigIsExisting(CFG_MAGAZINESPATH+" "+type_name) )
        {
            cfg_path = CFG_MAGAZINESPATH+" "+type_name+" attachments";
        }
        GetGame().ConfigGetTextArray(cfg_path, cfg_attachments);
        return cfg_attachments;
    }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and GetTypeName().
Referenced by UIScriptedMenu::Refresh().
GetHealth()
float SceneObject::GetHealth () inline private
Definition at line 433 of file sceneobject.c.
    {
        if (m_ObjectPtr) return m_ObjectPtr.GetHealth("", "");
        return 0;
    }
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), and PluginConfigHandler::SaveSceneObjects().
GetInitScript()
string SceneObject::GetInitScript () inline private
Definition at line 82 of file sceneobject.c.
    {
        return m_InitScript;
    }
References m_InitScript.
Referenced by PluginBase::ExecuteInitScripts(), UIPopupScript::OnOpen(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedObject()
EntityAI SceneObject::GetLinkedObject (int i) inline private
Definition at line 349 of file sceneobject.c.
    {
        return GetLinkedSceneObject(i).GetObject();
    }
References GetLinkedSceneObject(), and GetObject().
GetLinkedSceneObject()
SceneObject SceneObject::GetLinkedSceneObject (int i) inline private
Definition at line 341 of file sceneobject.c.
    {
        return m_LinkedSceneObjects.Get(i);
    }
References m_LinkedSceneObjects.
Referenced by GetLinkedObject(), and UnlinkAll().
GetLinkedSceneObjects()
array< SceneObject > SceneObject::GetLinkedSceneObjects () inline private
Definition at line 325 of file sceneobject.c.
    {
        return m_LinkedSceneObjects;
    }
References m_LinkedSceneObjects.
Referenced by PluginBase::EditorUpdate(), and PluginConfigHandler::SaveSceneObjects().
GetLinkedSceneObjectsCount()
int SceneObject::GetLinkedSceneObjectsCount () inline private
Definition at line 333 of file sceneobject.c.
    {
        return m_LinkedSceneObjects.Count();
    }
References m_LinkedSceneObjects.
Referenced by UnlinkAll().
GetMaxHealth()
float SceneObject::GetMaxHealth () inline private
Definition at line 442 of file sceneobject.c.
    {
        if (m_ObjectPtr) return m_ObjectPtr.GetMaxHealth("", "");
        return 0;
    }
References m_ObjectPtr.
GetName()
string SceneObject::GetName () inline private
Definition at line 66 of file sceneobject.c.
    {
        return m_ObjectName;
    }
References m_ObjectName.
GetObject()
EntityAI SceneObject::GetObject () inline private
Definition at line 58 of file sceneobject.c.
    {
        return m_ObjectPtr;
    }
References m_ObjectPtr.
Referenced by AddAttachment(), CanAttachment(), PluginBase::DeleteSceneObject(), EditorLineAdd(), EditorShapeUpdatePos(), PluginBase::ExecuteEnforceScript(), GetAttachments(), GetLinkedObject(), PluginBase::GetSceneObjectByEntity(), GetSize(), PluginConfigHandler::LoadSceneObjects(), PluginConfigHandler::SaveSceneObjects(), PluginBase::SelectedObjectDuplicate(), and PluginBase::SelectedObjectSetDamage().
GetPosition()
vector SceneObject::GetPosition () inline private
Definition at line 424 of file sceneobject.c.
    {
        if (m_ObjectPtr) return m_ObjectPtr.GetPosition();
        return Vector(0,0,0);
    }
References m_ObjectPtr, and Vector().
Referenced by UIScriptedMenu::Refresh(), PluginBase::SelectedObjectDuplicate(), PluginBase::SelectedObjectFocus(), PluginBase::SelectedObjectSetPosX(), PluginBase::SelectedObjectSetPosY(), and PluginBase::SelectedObjectSetPosZ().
GetPositionAsString()
string SceneObject::GetPositionAsString () inline private
Definition at line 470 of file sceneobject.c.
    {
        if (m_ObjectPtr) return m_ObjectPtr.GetPosition().ToString(false);
        return Vector(0,0,0).ToString(false);
    }
References m_ObjectPtr, vector::ToString(), and Vector().
Referenced by PluginConfigHandler::SaveSceneObjects().
GetRotation()
float SceneObject::GetRotation () inline private
Definition at line 487 of file sceneobject.c.
    {
        if (m_ObjectPtr)
        {
            vector v = m_ObjectPtr.GetOrientation();
            return v[0];
        }
        return 0;
    }
References m_ObjectPtr.
Referenced by UIScriptedMenu::Refresh(), PluginConfigHandler::SaveSceneObjects(), and PluginBase::SelectedObjectDuplicate().
GetSize()
vector SceneObject::GetSize () inline private
Definition at line 142 of file sceneobject.c.
    {
        vector size = Vector(1,1,1);
        vector min_max[2];
        if ( GetObject() )
        {
            GetObject().GetCollisionBox(min_max);
            size[0] = min_max[1][0] - min_max[0][0];
            size[2] = min_max[1][2] - min_max[0][2];
            size[1] = min_max[1][1] - min_max[0][1];
            return size;
        }
        else
        {
            Print("Error: SceneObject "+ m_ObjectNameOrigin +" dont has game object.");
        }
        return size;
    }
References GetObject(), m_ObjectNameOrigin, Print(), and Vector().
Referenced by EditorLineAdd(), EditorShapeAdd(), and PluginBase::SelectedObjectFocus().
GetTypeName()
string SceneObject::GetTypeName () inline private
Definition at line 376 of file sceneobject.c.
    {
        return m_ObjectPtr.GetType();
    }
References m_ObjectPtr.
Referenced by GetConfigAttachments(), UIScriptedMenu::GetFiltredSceneObjects(), UIScriptedMenu::Refresh(), PluginConfigHandler::SaveSceneObjects(), PluginLocalProfile::SceneSave(), PluginBase::SelectedObjectDuplicate(), and UIScriptedMenu::UpdateListObjects().
Init()
SceneObject SceneObject::Init (string obj_name, vector pos) inline private
Definition at line 20 of file sceneobject.c.
    {
        if ( obj_name != STRING_EMPTY )
        {
            m_ObjectNameOrigin = obj_name;
            bool is_ai = GetGame().IsKindOf( obj_name, "DZ_LightAI");
            PluginDeveloper module_dev = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
            EntityAI e = module_dev.SpawnEntityOnGroundPos(PluginSceneManager.PLAYER, obj_name, 100, 0.0, pos);
            if ( e != NULL )
            {
                if ( e.IsInherited(ItemBase) )
                {
                    ItemBase item = ItemBase.Cast( e );
                    if( item.HasQuantity() ) item.SetQuantity(item.GetQuantityMax() );
                }
                m_ObjectName = e.GetType();
                LinkEntityAI(e);
            }
            else if ( obj_name != "player" )
            {
                return NULL;
            }
        }
        m_LinkedSceneObjects = new array<SceneObject>;
        m_LinkedSceneObjectsShapes = new map<SceneObject, Shape>;
        m_LinkedSceneObjectsIndices = new array<int>;
        return this;
    }
References GetGame(), GetPlugin(), CGame::IsKindOf(), LinkEntityAI(), m_LinkedSceneObjects, m_LinkedSceneObjectsIndices, m_LinkedSceneObjectsShapes, m_ObjectName, m_ObjectNameOrigin, and STRING_EMPTY.
Referenced by SceneData::AddObject(), and SceneData::CreateSceneObject().
IsLinkedWithSceneObject()
bool SceneObject::IsLinkedWithSceneObject (SceneObject scene_object) inline private
Definition at line 265 of file sceneobject.c.
    {
        int index = m_LinkedSceneObjects.Find(scene_object);
        if ( index >= 0 )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References m_LinkedSceneObjects.
Referenced by PluginBase::AreSceneObjectsLinked(), and LinkSceneObject().
IsPlayer() [1/2]
bool SceneObject::IsPlayer () inline private
Definition at line 74 of file sceneobject.c.
    {
        return false;
    }
Referenced by SceneData::AddObject(), PluginBase::DeleteSelectedObject(), and PluginBase::Event_OnClickMiddle().
IsPlayer() [2/2]
override bool SceneObject::IsPlayer () inline private
Definition at line 6 of file sceneplayer.c.
    {
        return true;
    }
LinkEntityAI()
void SceneObject::LinkEntityAI (EntityAI e) inline private
Definition at line 257 of file sceneobject.c.
    {
        m_ObjectPtr = e;
    }
References m_ObjectPtr.
Referenced by SceneData::AddObject(), and Init().
LinkSceneObject()
void SceneObject::LinkSceneObject (SceneObject scene_object, bool draw_line = true) inline private
Definition at line 281 of file sceneobject.c.
    {
        if ( !IsLinkedWithSceneObject(scene_object) )
        {
            if ( draw_line )
            {
                EditorLineAdd(scene_object);
            }
            m_LinkedSceneObjects.Insert(scene_object);
        }
    }
References EditorLineAdd(), IsLinkedWithSceneObject(), and m_LinkedSceneObjects.
Referenced by PluginBase::LinkSceneObjects(), and PluginBase::RestoreSceneObjectsLinks().
PlaceOnSurface()
void SceneObject::PlaceOnSurface () inline private
Definition at line 384 of file sceneobject.c.
    {
        if (m_ObjectPtr)
        {
            if ( GetGame().IsClient() && GetGame().IsMultiplayer() )
            {
                Param par = new Param3<string, EntityAI, Param>( "PlaceOnSurface" , m_ObjectPtr, NULL );
                SceneObjectSynch( par );
            }
            else
            {
                m_ObjectPtr.PlaceOnSurface();
            }
        }
    }
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
Referenced by SetPosition().
RemoveAttachment()
void SceneObject::RemoveAttachment (EntityAI e) inline private
Definition at line 559 of file sceneobject.c.
    {
        GetGame().ObjectDelete(e);
    }
References GetGame(), and CGame::ObjectDelete().
SceneObjectSynch()
void SceneObject::SceneObjectSynch (Param p) inline private
Definition at line 512 of file sceneobject.c.
    {
        GetGame().RPCSingleParam( GetGame().GetPlayer(), ERPCs.RPC_SYNC_SCENE_OBJECT, p, true, NULL );
    }
References GetGame(), GetPlayer(), and CGame::RPCSingleParam().
Referenced by AddRotation(), PlaceOnSurface(), SetHealth(), and SetPosition().
SetHealth()
void SceneObject::SetHealth (float value) inline private
Definition at line 451 of file sceneobject.c.
    {
        if (m_ObjectPtr)
        {
            if ( GetGame().IsClient() && GetGame().IsMultiplayer() )
            {
                Param par = new Param3<string, EntityAI, Param>( "SetHealth" , m_ObjectPtr, new Param1<float>( value ) );
                SceneObjectSynch( par );
            }
            else
            {
                m_ObjectPtr.SetHealth ( "", "", value );
            }
        }
    }
References GetGame(), m_ObjectPtr, and SceneObjectSynch().
Referenced by PluginConfigHandler::LoadSceneObjects(), and PluginBase::SelectedObjectSetDamage().
SetInitScript()
void SceneObject::SetInitScript (string init_script) inline private
Definition at line 90 of file sceneobject.c.
    {
        m_InitScript = init_script;
    }
References m_InitScript.
Referenced by PluginConfigHandler::LoadSceneObjects(), and UIPopupScript::OnClick().
SetPosition()
void SceneObject::SetPosition (vector pos) inline private
Definition at line 403 of file sceneobject.c.
    {
        if (m_ObjectPtr)
        {
            if ( GetGame().IsClient() && GetGame().IsMultiplayer() )
            {
                Param par = new Param3<string, EntityAI, Param>( "SetPosition" , m_ObjectPtr, new Param1<vector>( pos ) );
                SceneObjectSynch( par );
            }
            else
            {
                m_ObjectPtr.SetPosition(pos);
            }
        }
        PlaceOnSurface();
        EditorShapeUpdatePos();
    }
References EditorShapeUpdatePos(), GetGame(), m_ObjectPtr, PlaceOnSurface(), and SceneObjectSynch().
Referenced by PluginBase::SelectedObjectSetPosX(), PluginBase::SelectedObjectSetPosY(), PluginBase::SelectedObjectSetPosZ(), and SetPositionAsString().
SetPositionAsString()
void SceneObject::SetPositionAsString (string string_pos) inline private
Definition at line 479 of file sceneobject.c.
    {
        SetPosition(string_pos.ToVector());
    }
References SetPosition(), and string::ToVector().
SetRotation()
void SceneObject::SetRotation (float rot) inline private
Definition at line 501 of file sceneobject.c.
    {
        if (m_ObjectPtr)
        {
            vector v = m_ObjectPtr.GetOrientation();
            v[0] = rot;
            m_ObjectPtr.SetOrientation(v);
            EditorShapeUpdatePos();
        }
    }
References EditorShapeUpdatePos(), and m_ObjectPtr.
Referenced by PluginConfigHandler::LoadSceneObjects(), and PluginBase::SelectedObjectDuplicate().
UnlinkAll()
void SceneObject::UnlinkAll () inline private
Definition at line 309 of file sceneobject.c.
    {
        int link_count = GetLinkedSceneObjectsCount();
        if ( link_count > 0 )
        {
            for ( int i = 0; i < link_count; ++i )
            {
                PluginSceneManager.GetInstance().UnlinkSceneObjects(this, GetLinkedSceneObject(0));
            }
        }
    }
References GetLinkedSceneObject(), and GetLinkedSceneObjectsCount().
Referenced by PluginBase::DeleteSceneObject().
UnlinkSceneObject()
void SceneObject::UnlinkSceneObject (SceneObject scene_object) inline private
Definition at line 296 of file sceneobject.c.
    {
        int index = m_LinkedSceneObjects.Find(scene_object);
        if ( index >= 0 && index < m_LinkedSceneObjects.Count() )
        {
            EditorLineRemove(scene_object);
            m_LinkedSceneObjects.Remove(index);
        }
    }
References EditorLineRemove(), and m_LinkedSceneObjects.
Referenced by PluginBase::UnlinkSceneObjects().
Member Data Documentation
COLOR_OBJ_BBOX_NORMAL
const int SceneObject::COLOR_OBJ_BBOX_NORMAL = 0x00000000 static private
Definition at line 3 of file sceneobject.c.
Referenced by EditorShapeDeselect().
COLOR_OBJ_BBOX_SELECT
const int SceneObject::COLOR_OBJ_BBOX_SELECT = 0x1f007C00 static private
Definition at line 4 of file sceneobject.c.
Referenced by EditorShapeSelect().
m_DebugShapeBBox
protected Shape SceneObject::m_DebugShapeBBox private
Definition at line 7 of file sceneobject.c.
Referenced by EditorShapeAdd(), EditorShapeRemove(), EditorShapeSetColor(), and EditorShapeUpdatePos().
m_InitScript
protected string SceneObject::m_InitScript private
Definition at line 8 of file sceneobject.c.
Referenced by GetInitScript(), and SetInitScript().
m_LinkedSceneObjects
protected ref array<SceneObject> SceneObject::m_LinkedSceneObjects private
Definition at line 12 of file sceneobject.c.
Referenced by GetLinkedSceneObject(), GetLinkedSceneObjects(), GetLinkedSceneObjectsCount(), Init(), IsLinkedWithSceneObject(), LinkSceneObject(), UnlinkSceneObject(), and ~SceneObject().
m_LinkedSceneObjectsIndices
ref array<int> SceneObject::m_LinkedSceneObjectsIndices private
Definition at line 15 of file sceneobject.c.
Referenced by Init(), PluginConfigHandler::LoadSceneObjects(), and PluginBase::RestoreSceneObjectsLinks().
m_LinkedSceneObjectsShapes
protected ref map<SceneObject, Shape> SceneObject::m_LinkedSceneObjectsShapes private
Definition at line 13 of file sceneobject.c.
Referenced by EditorLineAdd(), EditorLineRemove(), and Init().
m_ObjectName
protected string SceneObject::m_ObjectName private
Definition at line 9 of file sceneobject.c.
Referenced by GetName(), and Init().
m_ObjectNameOrigin
protected string SceneObject::m_ObjectNameOrigin private
Definition at line 10 of file sceneobject.c.
Referenced by GetSize(), and Init().
m_ObjectPtr
protected EntityAI SceneObject::m_ObjectPtr private
Definition at line 6 of file sceneobject.c.
Referenced by AddRotation(), GetHealth(), GetMaxHealth(), GetObject(), GetPosition(), GetPositionAsString(), GetRotation(), GetTypeName(), LinkEntityAI(), PlaceOnSurface(), SetHealth(), SetPosition(), SetRotation(), and ~SceneObject().