DayzKode: PoweredOptic_Base Class Reference
PoweredOptic_Base Class Reference
Private Member Functions
void DoMeasurement ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override int GetCurrentNVType ()
float GetMeasurementUpdateInterval ()
override bool IsNVG ()
void LoweredCheck ()
void NVGoggles ()
override void OnDebugSpawn ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWorkStop ()
void Rangefinder ()
void RotateGoggles (bool state)
override void SetActions ()
override void SetActions ()
void StartPeriodicMeasurement ()
void StopPeriodicMeasurement ()
void SwitchOnNVGCheck ()
Private Attributes
bool m_IsLowered
protected TextWidget m_RangeText
Clothing m_Strap
protected ref Timer m_Timer
ref Timer m_WorkCheckTimer
Static Private Attributes
static const float RANGEFINDER_MAX_DISTANCE = 913.4856
Detailed Description
Definition at line 1 of file nvgoggles.c.
Member Function Documentation
DoMeasurement()
void PoweredOptic_Base::DoMeasurement () inline private
Definition at line 72 of file rangefinder.c.
    {
        PlayerBase player = GetPlayer();
        if ( player )
        {
            vector      from            = GetGame().GetCurrentCameraPosition();
            vector      to              = from + (GetGame().GetCurrentCameraDirection() * RANGEFINDER_MAX_DISTANCE);
            vector      contact_pos;
            vector      contact_dir;
            int         contactComponent;
            DayZPhysics.RaycastRV( from, to, contact_pos, contact_dir, contactComponent, NULL , NULL, player, false, false, ObjIntersectIFire);
            // Generate result
            float dist = vector.Distance( from, contact_pos );
            dist = Math.Round(dist);
            if (dist < RANGEFINDER_MAX_DISTANCE)
            {
                if( dist < 10 )
                    m_RangeText.SetText( "00" + dist.ToString() );
                else if( dist < 100 )
                    m_RangeText.SetText( "0" + dist.ToString() );
                else
                    m_RangeText.SetText( dist.ToString() );
            }
            else
            {
                m_RangeText.SetText( "- - -" );
            }
        }
    }
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), RANGEFINDER_MAX_DISTANCE, DayZPhysics::RaycastRV(), Math::Round(), and float::ToString().
EEItemAttached()
override void PoweredOptic_Base::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 21 of file nvgoggles.c.
    {
        super.EEItemAttached( item, slot_name );
        if ( GetCompEM().CanWork() && m_IsLowered )
            m_WorkCheckTimer.Run(0.1,this,"SwitchOnNVGCheck",null,true);
            //GetCompEM().SwitchOn();
    }
EEItemDetached()
override void PoweredOptic_Base::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 30 of file nvgoggles.c.
    {
        super.EEItemDetached( item, slot_name );
        GetCompEM().SwitchOff();
    }
GetCurrentNVType()
override int PoweredOptic_Base::GetCurrentNVType () inline private
Definition at line 178 of file nvgoggles.c.
    {
        if (IsWorking())
        {
            //m_CurrentOpticMode
            switch (m_CurrentOpticMode)
            {
                /*case GameConstants.OPTICS_STATE_DAY:
                    return NVTypes.NV_GOGGLES_WHATEVER;
                case GameConstants.OPTICS_STATE_NIGHTVISION:
                    return NVTypes.NV_GOGGLES;*/
                default:
                    return NVTypes.NV_GOGGLES;
            }
            Error("Undefined optic mode of " + this);
            return NVTypes.NONE;
        }
        else
        {
            return NVTypes.NV_GOGGLES_OFF;
        }
    }
References Error().
GetMeasurementUpdateInterval()
float PoweredOptic_Base::GetMeasurementUpdateInterval () inline private
Definition at line 13 of file rangefinder.c.
    {
        return 0.5;
    }
Referenced by StartPeriodicMeasurement().
IsNVG()
override bool PoweredOptic_Base::IsNVG () inline private
Definition at line 202 of file nvgoggles.c.
    {
        return true;
    }
LoweredCheck()
void PoweredOptic_Base::LoweredCheck () inline private
Definition at line 137 of file nvgoggles.c.
    {
        if ( GetAnimationPhase("rotate") != m_IsLowered )
        {
            m_IsLowered = GetAnimationPhase("rotate");
        }
    }
NVGoggles()
void PoweredOptic_Base::NVGoggles () inline private
Definition at line 7 of file nvgoggles.c.
    {
        RotateGoggles(true);
        m_WorkCheckTimer = new Timer;
    }
References RotateGoggles().
OnDebugSpawn()
override void PoweredOptic_Base::OnDebugSpawn () inline private
Definition at line 114 of file rangefinder.c.
    {
        GetInventory().CreateInInventory( "Battery9V" );
    }
OnWasAttached()
override void PoweredOptic_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 37 of file nvgoggles.c.
    {
        super.OnWasAttached(parent, slot_id);
        RotateGoggles(true);
        m_Strap = Clothing.Cast(parent);
        /*if (m_Strap)
            SetPlayer(PlayerBase.Cast(m_Strap.GetHierarchyParent()));*/
    }
References RotateGoggles().
OnWasDetached()
override void PoweredOptic_Base::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 47 of file nvgoggles.c.
    {
        super.OnWasDetached(parent, slot_id);
        RotateGoggles(true);
        PlayerBase player;
        if ( m_Strap == parent && PlayerBase.CastTo(player, parent.GetHierarchyRootPlayer()) )
        {
            if ( parent && Clothing.Cast(parent) )
            {
                Clothing.Cast(parent).UpdateNVGStatus(player,false,true);
            }
        }
        m_Strap = null;
        //SetPlayer(null);
    }
References RotateGoggles().
OnWork()
override void PoweredOptic_Base::OnWork (float consumed_energy) inline private
Definition at line 111 of file nvgoggles.c.
    {
        //adjust on load - ComponentEnergyManager stores the 'working' state independently
        if ( !m_IsLowered )
        {
            RotateGoggles(false);
        }
        PlayerBase player;
        EntityAI headgear;
        EntityAI glasses;
        if ( m_Strap && PlayerBase.CastTo(player, m_Strap.GetHierarchyParent()) )
        {
            headgear = player.FindAttachmentBySlotName("Headgear");
            glasses = player.FindAttachmentBySlotName("Eyewear");
            if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() ) // Client side
            {
                if ( (headgear == m_Strap || glasses == m_Strap) && player.IsControlledPlayer() )
                {
                    player.AddActiveNV(NVTypes.NV_GOGGLES);
                }
            }
        }
    }
References GetGame(), and RotateGoggles().
OnWorkStart() [1/2]
override void PoweredOptic_Base::OnWorkStart () inline private
Definition at line 65 of file nvgoggles.c.
    {
        PlayerBase player;
        EntityAI headgear;
        EntityAI glasses;
        if ( m_Strap && PlayerBase.CastTo(player, m_Strap.GetHierarchyParent()) )
        {
            headgear = player.FindAttachmentBySlotName("Headgear");
            glasses = player.FindAttachmentBySlotName("Eyewear");
            //adjust on load - ComponentEnergyManager stores the 'working' state independently
            if ( !m_IsLowered )
            {
                RotateGoggles(false);
            }
            if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() ) // Client side
            {
                if ( (headgear == m_Strap || glasses == m_Strap) && player.IsControlledPlayer() )
                {
                    player.AddActiveNV(NVTypes.NV_GOGGLES);
                }
            }
        }
    }
References GetGame(), and RotateGoggles().
OnWorkStart() [2/2]
override void PoweredOptic_Base::OnWorkStart () inline private
Definition at line 18 of file rangefinder.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            PlayerBase player_this = PlayerBase.Cast( GetGame().GetPlayer() );
            PlayerBase player_owner = PlayerBase.Cast( GetHierarchyRootPlayer() );
            if ( player_this == player_owner )
            {
                StartPeriodicMeasurement();
            }
        }
    }
References GetGame(), GetPlayer(), and StartPeriodicMeasurement().
OnWorkStop() [1/2]
override void PoweredOptic_Base::OnWorkStop () inline private
Definition at line 91 of file nvgoggles.c.
    {
        PlayerBase player;
        EntityAI headgear;
        EntityAI glasses;
        if ( m_Strap && PlayerBase.CastTo(player, m_Strap.GetHierarchyParent()) )
        {
            headgear = player.FindAttachmentBySlotName("Headgear");
            glasses = player.FindAttachmentBySlotName("Eyewear");
            if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() ) // Client side
            {
                if ( (headgear == m_Strap || glasses == m_Strap) && player.IsControlledPlayer() )
                {
                    player.RemoveActiveNV(NVTypes.NV_GOGGLES);
                }
            }
        }
    }
References GetGame().
OnWorkStop() [2/2]
override void PoweredOptic_Base::OnWorkStop () inline private
Definition at line 32 of file rangefinder.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            PlayerBase player_this = PlayerBase.Cast( GetGame().GetPlayer() );
            PlayerBase player_owner = PlayerBase.Cast( GetHierarchyRootPlayer() );
            if ( player_this == player_owner )
            {
                StopPeriodicMeasurement();
            }
        }
    }
References GetGame(), GetPlayer(), and StopPeriodicMeasurement().
Rangefinder()
void PoweredOptic_Base::Rangefinder () inline private
Definition at line 8 of file rangefinder.c.
    {
    }
RotateGoggles()
void PoweredOptic_Base::RotateGoggles (bool state) inline private
Definition at line 145 of file nvgoggles.c.
    {
        //if ( GetAnimationPhase("rotate") != state ) //useless?
            SetAnimationPhase("rotate",!state);
        m_IsLowered = !state;
        PlayerBase player;
        int slot_id;
        string slot_name;
        if ( m_Strap && m_Strap.GetInventory().GetCurrentAttachmentSlotInfo(slot_id,slot_name) && PlayerBase.CastTo(player, m_Strap.GetHierarchyParent())/*&& slot_id == InventorySlots.EYEWEAR*/ )
        {
            player.SetNVGLowered(m_IsLowered);
        }
        if ( GetCompEM() )
        {
            if ( !state && GetCompEM().CanWork() )
                GetCompEM().SwitchOn();
            else
                GetCompEM().SwitchOff();
        }
    }
Referenced by NVGoggles(), OnWasAttached(), OnWasDetached(), OnWork(), and OnWorkStart().
SetActions() [1/2]
override void PoweredOptic_Base::SetActions () inline private
Definition at line 13 of file nvgoggles.c.
    {
        super.SetActions();
        RemoveAction(ActionViewOptics);
        AddAction(ActionViewBinoculars);
    }
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void PoweredOptic_Base::SetActions () inline private
Definition at line 106 of file rangefinder.c.
    {
        super.SetActions();
        RemoveAction(ActionViewOptics);
        AddAction(ActionViewBinoculars);
    }
References AddAction(), and RemoveAction().
StartPeriodicMeasurement()
void PoweredOptic_Base::StartPeriodicMeasurement () inline private
Definition at line 46 of file rangefinder.c.
    {
        if( !m_Timer )
        {
            m_Timer = new Timer( CALL_CATEGORY_GAMEPLAY );
        }
        m_RangeText = TextWidget.Cast( GetGame().GetWorkspace().CreateWidgets( "gui/layouts/gameplay/rangefinder_hud.layout" ) );
        m_Timer.Run( GetMeasurementUpdateInterval(), this, "DoMeasurement", null, true );
    }
References CALL_CATEGORY_GAMEPLAY, GetGame(), GetMeasurementUpdateInterval(), and m_Timer.
Referenced by OnWorkStart().
StopPeriodicMeasurement()
void PoweredOptic_Base::StopPeriodicMeasurement () inline private
Definition at line 58 of file rangefinder.c.
    {
        if( m_Timer )
        {
            m_Timer.Stop();
        }
        if (m_RangeText)
        {
            delete m_RangeText;
        }
    }
References m_RangeText, and m_Timer.
Referenced by OnWorkStop().
SwitchOnNVGCheck()
void PoweredOptic_Base::SwitchOnNVGCheck () inline private
Definition at line 168 of file nvgoggles.c.
    {
        //Print("SwitchOnNVGCheck");
        GetCompEM().SwitchOn();
        if (GetCompEM().IsSwitchedOn())
        {
            m_WorkCheckTimer.Stop();
        }
    }
Member Data Documentation
m_IsLowered
bool PoweredOptic_Base::m_IsLowered private
Definition at line 3 of file nvgoggles.c.
m_RangeText
protected TextWidget PoweredOptic_Base::m_RangeText private
Definition at line 6 of file rangefinder.c.
Referenced by StopPeriodicMeasurement().
m_Strap
Clothing PoweredOptic_Base::m_Strap private
Definition at line 4 of file nvgoggles.c.
m_Timer
protected ref Timer PoweredOptic_Base::m_Timer private
Definition at line 5 of file rangefinder.c.
m_WorkCheckTimer
ref Timer PoweredOptic_Base::m_WorkCheckTimer private
Definition at line 5 of file nvgoggles.c.
RANGEFINDER_MAX_DISTANCE
const float PoweredOptic_Base::RANGEFINDER_MAX_DISTANCE = 913.4856 static private
Definition at line 3 of file rangefinder.c.
Referenced by DoMeasurement().