DayzKode: LifespanLevel Class Reference
LifespanLevel Class Reference
Private Member Functions
int GetLevel ()
string GetMaterialName ()
string GetTextureName ()
float GetThreshold ()
void LifespanLevel (int level, float threshold, string texture_name, string material_name)
Private Attributes
protected int m_Level
protected string m_MaterialName
protected string m_TextureName
protected float m_Threshold
Detailed Description
Definition at line 1 of file lifespanlevel.c.
Constructor & Destructor Documentation
LifespanLevel()
void LifespanLevel::LifespanLevel (int level, float threshold, string texture_name, string material_name) inline private
Definition at line 9 of file lifespanlevel.c.
    {
        m_Level = level;
        m_Threshold = threshold;
        m_TextureName = texture_name;
        m_MaterialName = material_name;
    }
References m_Level, m_MaterialName, m_TextureName, and m_Threshold.
Member Function Documentation
GetLevel()
int LifespanLevel::GetLevel () inline private
Definition at line 17 of file lifespanlevel.c.
    {
        return m_Level;
    }
References m_Level.
Referenced by SetPlayerLifespanLevel().
GetMaterialName()
string LifespanLevel::GetMaterialName () inline private
Definition at line 32 of file lifespanlevel.c.
    {
        return m_MaterialName;
    }
References m_MaterialName.
Referenced by GetCurrentHeadMaterial(), and SetPlayerLifespanLevel().
GetTextureName()
string LifespanLevel::GetTextureName () inline private
Definition at line 27 of file lifespanlevel.c.
    {
        return m_TextureName;
    }
References m_TextureName.
Referenced by GetCurrentHeadTexture(), and SetPlayerLifespanLevel().
GetThreshold()
float LifespanLevel::GetThreshold () inline private
Definition at line 22 of file lifespanlevel.c.
    {
        return m_Threshold;
    }
References m_Threshold.
Referenced by GetLifespanLevel(), and UpdateLifespanLevel().
Member Data Documentation
m_Level
protected int LifespanLevel::m_Level private
Definition at line 3 of file lifespanlevel.c.
Referenced by GetLevel(), and LifespanLevel().
m_MaterialName
protected string LifespanLevel::m_MaterialName private
Definition at line 6 of file lifespanlevel.c.
Referenced by GetMaterialName(), and LifespanLevel().
m_TextureName
protected string LifespanLevel::m_TextureName private
Definition at line 5 of file lifespanlevel.c.
Referenced by GetTextureName(), and LifespanLevel().
m_Threshold
protected float LifespanLevel::m_Threshold private
Definition at line 4 of file lifespanlevel.c.
Referenced by GetThreshold(), and LifespanLevel().