DayzKode: PainKillersMdfr Class Reference
PainKillersMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int ACTIVATION_DELAY = 15
const int LIFETIME = 240
Detailed Description
Definition at line 1 of file painkillersmdfr.c.
Member Function Documentation
ActivateCondition()
override bool PainKillersMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file painkillersmdfr.c.
    {
        return false;
    }
DeactivateCondition()
override bool PainKillersMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 56 of file painkillersmdfr.c.
    {
        float attached_time = GetAttachedTime();
        if( attached_time >= LIFETIME )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and LIFETIME.
GetDebugText()
override string PainKillersMdfr::GetDebugText () inline private
Definition at line 25 of file painkillersmdfr.c.
    {
        return (LIFETIME - GetAttachedTime()).ToString();
    }
References GetAttachedTime(), LIFETIME, and string::ToString().
Init()
override void PainKillersMdfr::Init () inline private
Definition at line 5 of file painkillersmdfr.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_PAINKILLERS;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 1;
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void PainKillersMdfr::OnActivate (PlayerBase player) inline private
Definition at line 31 of file painkillersmdfr.c.
    {
        if (player.GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
            player.m_ShockHandler.SetMultiplier(0.5);//was 0.75 //Switch the shock multiplier NEED A CONST
        player.IncreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        */
        m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.PAIN_KILLERS_LVL0;
    }
References m_Player.
OnDeactivate()
override void PainKillersMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 43 of file painkillersmdfr.c.
    {
        if (player.GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
            player.m_ShockHandler.SetMultiplier(1); //Reset the shock multiplier when modifier stops
        player.DecreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        */
        m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PAIN_KILLERS_LVL0;
        m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PAIN_KILLERS_LVL1;
    }
References m_Player.
OnReconnect()
override void PainKillersMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 20 of file painkillersmdfr.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void PainKillersMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 70 of file painkillersmdfr.c.
    {
        if(GetAttachedTime() > ACTIVATION_DELAY)
        {
            m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.PAIN_KILLERS_LVL1;
        }
    }
References ACTIVATION_DELAY, GetAttachedTime(), and m_Player.
Member Data Documentation
ACTIVATION_DELAY
const int PainKillersMdfr::ACTIVATION_DELAY = 15 private
Definition at line 4 of file painkillersmdfr.c.
Referenced by OnTick().
LIFETIME
const int PainKillersMdfr::LIFETIME = 240 private
Definition at line 3 of file painkillersmdfr.c.
Referenced by DeactivateCondition(), and GetDebugText().