DayzKode: Transport Class Reference
Transport Class Reference
Base native class for all motorized wheeled vehicles.
Private Member Functions
override Shape DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
proto native float EngineGetRPM ()
Returns engine's rpm value.
proto native float EngineGetRPMMax ()
Returns engine's max rpm before engine blows up.
proto native float EngineGetRPMRedline ()
Returns engine's maximal working rpm without damaging the engine.
proto native bool EngineIsOn ()
Returns true when engine is running, false otherwise.
proto native void EngineStart ()
Starts the engine.
proto native void EngineStop ()
Stops the engine.
proto native void Fill (CarFluid fluid, float amount)
Adds to the specified fluid the specified amount.
proto native void ForceDirection (vector dir)
proto native void ForcePosition (vector pos)
proto native CarAutomaticGearboxMode GearboxGetMode ()
Returns gearbox mode. This is useful when car has automatic gearbox.
proto native CarGearboxType GearboxGetType ()
Returns gearbox type. See CarGearboxType enum for more info.
proto native float GetBrake ()
Returns the current brake value in range <0, 1>.
proto native CarController GetController ()
DEPRECATED, left for backwards compatibility, the methods of this class are now directly accessible on Car itself.
proto native vector GetEnginePos ()
Get actual position of engine (model space)
proto native float GetFluidCapacity (CarFluid fluid)
proto native float GetFluidFraction (CarFluid fluid)
proto native int GetGear ()
Returns index of the current gear.
proto native int GetGearsCount ()
Returns total number of gears.
proto native float GetHandbrake ()
Returns the current handbrake value in range <0, 1>.
override int GetHideIconMask ()
proto native float GetSpeedometer ()
Returns the current speed of the vehicle in km/h.
float GetSpeedometerAbsolute ()
Returns the current speed of the vehicle in km/h. Value is absolute.
proto native float GetSteering ()
Returns the current steering value in range <-1, 1>.
proto native float GetThrust ()
Returns the current thrust value in range <0, 1>.
proto native float GetThrustGentle ()
Returns the current thrust gentle modifier value in range <0, 1>.
proto native float GetThrustTurbo ()
Returns the current thrust turbo modifier value in range <0, 1>.
override bool IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight=0.5, float horizontalExtents=0.5, float playerHeight=1.7)
proto native void Leak (CarFluid fluid, float amount)
Removes from the specified fluid the specified amount.
proto native void LeakAll (CarFluid fluid)
Removes all the specified fluid from vehicle.
bool OnBeforeEngineStart ()
void OnContact (string zoneName, vector localPos, IEntity other, Contact data)
void OnEngineStart ()
Is called every time the engine starts.
void OnEngineStop ()
Is called every time the engine stops.
void OnFluidChanged (CarFluid fluid, float newValue, float oldValue)
void OnGearChanged (int newGear, int oldGear)
void OnInput (float dt)
float OnSound (CarSoundCtrl ctrl, float oldValue)
void OnUpdate (float dt)
proto native void SetBrake (float in, float panic=0)
proto native void SetEnginePos (vector pos)
Override the position of engine (model space)
proto native void SetHandbrake (float in)
proto native void SetSteering (float in, bool analog=false)
proto native void SetThrust (float in, float gentle=0, float turbo=0)
proto native void ShiftDown ()
proto native void ShiftTo (CarGear gear)
proto native void ShiftUp ()
proto native bool WheelIsAnyLocked ()
Returns true if any of the wheels are locked in terms of its movement.
proto native bool WheelIsLocked (int wheelIdx)
Detailed Description
Base native class for all motorized wheeled vehicles.
Base native class for helicopter.
Definition at line 79 of file car.c.
Member Function Documentation
DebugFreeAreaAtDoor()
override Shape Transport::DebugFreeAreaAtDoor (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
Definition at line 127 of file car.c.
    {
        float speed = GetSpeedometerAbsolute();
        vector direction = GetDirection();
        vector crewPos;
        vector crewDir;
        CrewEntryWS( currentSeat, crewPos, crewDir );
        crewPos[1] = crewPos[1] + maxAllowedObjHeight + playerHeight * 0.5;
        float vExtents = horizontalExtents;
        if (speed > 8)
            vExtents *= 6;
        if (speed > 8)
            horizontalExtents = 2;
        array<Object> excluded = new array<Object>;
        array<Object> collided = new array<Object>;
        excluded.Insert(this);
        excluded.Insert(GetGame().GetPlayer());
        GetGame().IsBoxColliding(crewPos, crewDir, Vector(horizontalExtents, playerHeight, vExtents), excluded, collided);
        int color = ARGB(20, 0, 255, 0);
        foreach (Object o : collided)
        {
            vector minmax[2];
            if (o.GetCollisionBox(minmax))
            {
                color = ARGB(20, 255, 0, 0);
            }
        }
        return Debug.DrawCylinder(crewPos, horizontalExtents, playerHeight, color);
    }
References ARGB(), Debug::DrawCylinder(), GetDirection(), GetGame(), GetPlayer(), GetSpeedometerAbsolute(), CGame::IsBoxColliding(), and Vector().
EngineGetRPM()
proto native float Transport::EngineGetRPM () private
Returns engine's rpm value.
EngineGetRPMMax()
proto native float Transport::EngineGetRPMMax () private
Returns engine's max rpm before engine blows up.
EngineGetRPMRedline()
proto native float Transport::EngineGetRPMRedline () private
Returns engine's maximal working rpm without damaging the engine.
EngineIsOn()
proto native bool Transport::EngineIsOn () private
Returns true when engine is running, false otherwise.
EngineStart()
proto native void Transport::EngineStart () private
Starts the engine.
EngineStop()
proto native void Transport::EngineStop () private
Stops the engine.
Fill()
proto native void Transport::Fill (CarFluid fluid, float amount) private
Adds to the specified fluid the specified amount.
ForceDirection()
proto native void Transport::ForceDirection (vector dir) private
ForcePosition()
proto native void Transport::ForcePosition (vector pos) private
GearboxGetMode()
proto native CarAutomaticGearboxMode Transport::GearboxGetMode () private
Returns gearbox mode. This is useful when car has automatic gearbox.
GearboxGetType()
proto native CarGearboxType Transport::GearboxGetType () private
Returns gearbox type. See CarGearboxType enum for more info.
GetBrake()
proto native float Transport::GetBrake () private
Returns the current brake value in range <0, 1>.
GetController()
proto native CarController Transport::GetController () private
DEPRECATED, left for backwards compatibility, the methods of this class are now directly accessible on Car itself.
GetEnginePos()
proto native vector Transport::GetEnginePos () private
Get actual position of engine (model space)
GetFluidCapacity()
proto native float Transport::GetFluidCapacity (CarFluid fluid) private
Returns tank capacity for the specified vehicle's fluid.
Parameters
fluid the specified fluid type
GetFluidFraction()
proto native float Transport::GetFluidFraction (CarFluid fluid) private
Returns fraction value (in range <0, 1>) of the current state of the specified vehicle's fluid.
Parameters
[in] fluid the specified fluid type
GetGear()
proto native int Transport::GetGear () private
Returns index of the current gear.
GetGearsCount()
proto native int Transport::GetGearsCount () private
Returns total number of gears.
GetHandbrake()
proto native float Transport::GetHandbrake () private
Returns the current handbrake value in range <0, 1>.
GetHideIconMask()
override int Transport::GetHideIconMask () inline private
Definition at line 160 of file car.c.
    {
        return EInventoryIconVisibility.HIDE_VICINITY;
    }
GetSpeedometer()
proto native float Transport::GetSpeedometer () private
Returns the current speed of the vehicle in km/h.
Referenced by GetSpeedometerAbsolute().
GetSpeedometerAbsolute()
float Transport::GetSpeedometerAbsolute () inline private
Returns the current speed of the vehicle in km/h. Value is absolute.
Definition at line 88 of file car.c.
    {
        return Math.AbsFloat(GetSpeedometer());
    }
References Math::AbsFloat(), and GetSpeedometer().
Referenced by ActionStopEngine::ActionCondition(), DebugFreeAreaAtDoor(), and IsAreaAtDoorFree().
GetSteering()
proto native float Transport::GetSteering () private
Returns the current steering value in range <-1, 1>.
GetThrust()
proto native float Transport::GetThrust () private
Returns the current thrust value in range <0, 1>.
GetThrustGentle()
proto native float Transport::GetThrustGentle () private
Returns the current thrust gentle modifier value in range <0, 1>.
GetThrustTurbo()
proto native float Transport::GetThrustTurbo () private
Returns the current thrust turbo modifier value in range <0, 1>.
IsAreaAtDoorFree()
override bool Transport::IsAreaAtDoorFree (int currentSeat, float maxAllowedObjHeight = 0.5, float horizontalExtents = 0.5, float playerHeight = 1.7) inline private
Definition at line 93 of file car.c.
    {
        float speed = GetSpeedometerAbsolute();
        vector direction = GetDirection();
        vector crewPos;
        vector crewDir;
        CrewEntryWS( currentSeat, crewPos, crewDir );
        crewPos[1] = crewPos[1] + maxAllowedObjHeight + playerHeight * 0.5;
        float vExtents = horizontalExtents;
        if (speed > 8)
            vExtents *= 6;
        if (speed > 8)
            horizontalExtents = 2;
        array<Object> excluded = new array<Object>;
        array<Object> collided = new array<Object>;
        excluded.Insert(this);
        excluded.Insert(GetGame().GetPlayer());
        GetGame().IsBoxColliding(crewPos, crewDir, Vector(horizontalExtents, playerHeight, vExtents), excluded, collided);
        foreach (Object o : collided)
        {
            EntityAI e = EntityAI.Cast(o);
            if (IsIgnoredObject(o))
                continue;
            vector minmax[2];
            if (o.GetCollisionBox(minmax))
                return false;
        }
        return true;
    }
References GetDirection(), GetGame(), GetPlayer(), GetSpeedometerAbsolute(), CGame::IsBoxColliding(), and Vector().
Referenced by ActionGetInTransport::ActionCondition(), and ActionCondition().
Leak()
proto native void Transport::Leak (CarFluid fluid, float amount) private
Removes from the specified fluid the specified amount.
LeakAll()
proto native void Transport::LeakAll (CarFluid fluid) private
Removes all the specified fluid from vehicle.
OnBeforeEngineStart()
bool Transport::OnBeforeEngineStart () inline private
Is called every time the game wants to start the engine.
Returns
true if the engine can start, false otherwise.
Definition at line 283 of file car.c.
    {
        // engine can start by default
        return true;
    }
OnContact()
void Transport::OnContact (string zoneName, vector localPos, IEntity other, Contact data) inline private
Is called every time when vehicle collides with other object.
Parameters
[in] zoneName configured vehicle's zone that was hit
[in] localPos position where the vehicle was hit in vehicle's space
[in] other object with which the vehicle is colliding
[in] data contact properties
Definition at line 356 of file car.c.
{}
OnEngineStart()
void Transport::OnEngineStart () inline private
Is called every time the engine starts.
Definition at line 290 of file car.c.
{}
OnEngineStop()
void Transport::OnEngineStop () inline private
Is called every time the engine stops.
Definition at line 296 of file car.c.
{}
OnFluidChanged()
void Transport::OnFluidChanged (CarFluid fluid, float newValue, float oldValue) inline private
Is called every time when the specified vehicle's fluid level changes eg. when car is consuming fuel.
Parameters
[in] fluid fluid identifier,
See also
CarFluid
Parameters
[in] newValue new fluid level
[in] oldValue previous fluid level before change
Definition at line 256 of file car.c.
{}
OnGearChanged()
void Transport::OnGearChanged (int newGear, int oldGear) inline private
Is called every time when the simulation changed gear.
Parameters
[in] newGear new gear level
[in] oldGear previous gear level before gear shift
Definition at line 324 of file car.c.
    {
    }
OnInput()
void Transport::OnInput (float dt) inline private
Is called after every input simulation step.
Note that the player character and other systems can always change the internal state. It is highly recommended to store state of custom inputs elsewhere and call Setters here.
Parameters
[in] dt frame time in seconds
Definition at line 380 of file car.c.
{}
OnSound()
float Transport::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Is called every sound simulation step. In this callback, user can modify behaviour of sound controllers.
Parameters
[in] ctrl sound controller identifier,
See also
CarSoundCtrl
Parameters
[in] oldValue already computed value by the game code
Returns
new value of the specified sound controller.
Definition at line 366 of file car.c.
    {
        // just use the computed value by the game code
        return oldValue;
    }
OnUpdate()
void Transport::OnUpdate (float dt) inline private
Is called every game frame.
Parameters
[in] dt frame time in seconds
Definition at line 386 of file car.c.
{}
SetBrake()
proto native void Transport::SetBrake (float in, float panic = 0) private
Sets the brake value.
Parameters
in should be in range <0, 1>
panic should be in range <0, 1>
SetEnginePos()
proto native void Transport::SetEnginePos (vector pos) private
Override the position of engine (model space)
SetHandbrake()
proto native void Transport::SetHandbrake (float in) private
Sets the handbrake value.
Parameters
in should be in range <0, 1>
SetSteering()
proto native void Transport::SetSteering (float in, bool analog = false) private
Sets the steering value.
Parameters
in should be in range <-1, 1>
analog indicates if the input value was taken from analog controller
SetThrust()
proto native void Transport::SetThrust (float in, float gentle = 0, float turbo = 0) private
Sets the thrust value.
Parameters
in should be in range <0, 1>
gentle should be in range <0, 1>, thrust modifier
turbo should be in range <0, 1>, thrust modifier
ShiftDown()
proto native void Transport::ShiftDown () private
ShiftTo()
proto native void Transport::ShiftTo (CarGear gear) private
ShiftUp()
proto native void Transport::ShiftUp () private
WheelIsAnyLocked()
proto native bool Transport::WheelIsAnyLocked () private
Returns true if any of the wheels are locked in terms of its movement.
WheelIsLocked()
proto native bool Transport::WheelIsLocked (int wheelIdx) private
Returns true if given wheel is locked in terms of its movement.
Parameters
[in] wheelIdx index of the wheel, they are counted from left-front to rear-right