DayzKode: AnimSoundLookupTableBank Class Reference
AnimSoundLookupTableBank Class Reference
Private Member Functions
void AnimSoundLookupTableBank ()
SoundLookupTable GetImpactTable (string tableName)
SoundLookupTable GetStepTable (string tableName)
Static Private Member Functions
static AnimSoundLookupTableBank GetInstance ()
Private Attributes
private autoptr map< int, ref SoundLookupTable > m_pTables
Static Private Attributes
static private ref AnimSoundLookupTableBank m_instance
Detailed Description
Definition at line 168 of file dayzanimeventmaps.c.
Constructor & Destructor Documentation
AnimSoundLookupTableBank()
void AnimSoundLookupTableBank::AnimSoundLookupTableBank () inline private
Definition at line 170 of file dayzanimeventmaps.c.
    {
        m_pTables = new map<int, ref SoundLookupTable>();
    }
References m_pTables.
Referenced by GetInstance().
Member Function Documentation
GetImpactTable()
SoundLookupTable AnimSoundLookupTableBank::GetImpactTable (string tableName) inline private
Definition at line 199 of file dayzanimeventmaps.c.
    {
        int tableNameHash = tableName.Hash();
        SoundLookupTable table = m_pTables.Get(tableNameHash);
        if(table == NULL)
        {
            table = new ImpactSoundLookupTable();
            table.LoadTable(tableName);
            m_pTables.Insert(tableNameHash, table);
        }
        return table;
    }
References string::Hash(), ImpactSoundLookupTable(), SoundLookupTable::LoadTable(), and m_pTables.
Referenced by EntityAI::InitImpactSoundData().
GetInstance()
static AnimSoundLookupTableBank AnimSoundLookupTableBank::GetInstance () inline static private
Definition at line 176 of file dayzanimeventmaps.c.
    {
        if(m_instance == NULL)
            m_instance = new AnimSoundLookupTableBank();
        return m_instance;
    }
References AnimSoundLookupTableBank(), and m_instance.
Referenced by EntityAI::InitImpactSoundData().
GetStepTable()
SoundLookupTable AnimSoundLookupTableBank::GetStepTable (string tableName) inline private
Definition at line 185 of file dayzanimeventmaps.c.
    {
        int tableNameHash = tableName.Hash();
        SoundLookupTable table = m_pTables.Get(tableNameHash);
        if(table == NULL)
        {
            table = new StepSoundLookupTable();
            table.LoadTable(tableName);
            m_pTables.Insert(tableNameHash, table);
        }
        return table;
    }
References string::Hash(), SoundLookupTable::LoadTable(), m_pTables, and StepSoundLookupTable().
Member Data Documentation
m_instance
private ref AnimSoundLookupTableBank AnimSoundLookupTableBank::m_instance static private
Definition at line 213 of file dayzanimeventmaps.c.
Referenced by GetInstance().
m_pTables
private autoptr map<int, ref SoundLookupTable> AnimSoundLookupTableBank::m_pTables private
Definition at line 214 of file dayzanimeventmaps.c.
Referenced by AnimSoundLookupTableBank(), GetImpactTable(), and GetStepTable().