DayzKode: UniversalTemperatureSourceDebug Class Reference
UniversalTemperatureSourceDebug Class Reference
Private Member Functions
void ChangeSettings (UniversalTemperatureSourceSettings pSettings)
float GetFullRange ()
float GetMaxRange ()
EntityAI GetParent ()
vector GetPosition ()
float GetTemperature ()
float GetTemperatureMax ()
float GetTemperatureMin ()
float GetTemperatureRaw ()
void Init (EntityAI pParent)
bool IsActive ()
void SetActive (bool pActive)
void SetDefferedActive (bool pActive, float pSeconds)
void UniversalTemperatureSource (EntityAI pParent, UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceLambdaBase pLambda)
void Update (UniversalTemperatureSourceSettings settings, UniversalTemperatureSourceLambdaBase lambda)
void ~UniversalTemperatureSource ()
Private Attributes
protected ref UniversalTemperatureSourceLambdaBase m_Lambda
protected ref UniversalTemperatureSourceResult m_ResultValues
protected UniversalTemperatureSourceSettings m_Settings
protected bool m_Active protected ref UniversalTemperatureSourceTimer m_Timer
Detailed Description
Definition at line 55 of file universaltemperaturesource.c.
Constructor & Destructor Documentation
~UniversalTemperatureSource()
void UniversalTemperatureSourceDebug::~UniversalTemperatureSource () inline private
Definition at line 74 of file universaltemperaturesource.c.
{};
Member Function Documentation
ChangeSettings()
void UniversalTemperatureSourceDebug::ChangeSettings (UniversalTemperatureSourceSettings pSettings) inline private
Definition at line 178 of file universaltemperaturesource.c.
    {
        m_Timer.SetParams(new Param2<UniversalTemperatureSourceSettings, UniversalTemperatureSourceLambdaBase>(m_Settings, m_Lambda));
    }
References m_Timer.
GetFullRange()
float UniversalTemperatureSourceDebug::GetFullRange () inline private
Definition at line 100 of file universaltemperaturesource.c.
    {
        return m_Settings.m_RangeFull;
    }
References UniversalTemperatureSourceSettings::m_RangeFull.
GetMaxRange()
float UniversalTemperatureSourceDebug::GetMaxRange () inline private
Definition at line 105 of file universaltemperaturesource.c.
    {
        return m_Settings.m_RangeMax;
    }
References UniversalTemperatureSourceSettings::m_RangeMax.
GetParent()
EntityAI UniversalTemperatureSourceDebug::GetParent () inline private
Definition at line 140 of file universaltemperaturesource.c.
    {
        return m_Settings.m_Parent;
    }
References UniversalTemperatureSourceSettings::m_Parent.
GetPosition()
vector UniversalTemperatureSourceDebug::GetPosition () inline private
Definition at line 95 of file universaltemperaturesource.c.
    {
        return m_Settings.m_Position;
    }
References UniversalTemperatureSourceSettings::m_Position.
GetTemperature()
float UniversalTemperatureSourceDebug::GetTemperature () inline private
Definition at line 110 of file universaltemperaturesource.c.
    {
        if (m_Settings.m_TemperatureCap != float.MAX)
        {
            return Math.Min(m_Settings.m_TemperatureCap, GetTemperatureRaw());
        }
        return GetTemperatureRaw();
    }
References UniversalTemperatureSourceSettings::m_TemperatureCap, float::MAX, and Math::Min().
GetTemperatureMax()
float UniversalTemperatureSourceDebug::GetTemperatureMax () inline private
Definition at line 135 of file universaltemperaturesource.c.
    {
        return m_Settings.m_TemperatureMax;
    }
References UniversalTemperatureSourceSettings::m_TemperatureMax.
GetTemperatureMin()
float UniversalTemperatureSourceDebug::GetTemperatureMin () inline private
Definition at line 130 of file universaltemperaturesource.c.
    {
        return m_Settings.m_TemperatureMin;
    }
References UniversalTemperatureSourceSettings::m_TemperatureMin.
GetTemperatureRaw()
float UniversalTemperatureSourceDebug::GetTemperatureRaw () inline private
Definition at line 120 of file universaltemperaturesource.c.
    {
        if (m_ResultValues)
        {
            return m_ResultValues.m_Temperature;
        }
        return 0;
    }
Init()
void UniversalTemperatureSourceDebug::Init (EntityAI pParent) inline private
Definition at line 76 of file universaltemperaturesource.c.
    {
        if (pParent)
        {
            pParent.SetUniversalTemperatureSource(this);
            m_Settings.m_Parent     = pParent;
            m_Settings.m_Position   = pParent.GetPosition();
        }
        if (!m_Settings.m_ManualUpdate)
        {
            auto params = new Param2<UniversalTemperatureSourceSettings, UniversalTemperatureSourceLambdaBase>(m_Settings, m_Lambda);
            m_Timer.Run(m_Settings.m_UpdateInterval, this, "Update", params, m_Settings.m_Updateable);
            SetActive(false);
        }
    }
References UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, m_Timer, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, and SetActive().
IsActive()
bool UniversalTemperatureSourceDebug::IsActive () inline private
Definition at line 145 of file universaltemperaturesource.c.
    {
        if (m_Settings.m_ManualUpdate)
        {
            return m_Active;
        }
        return m_Timer && m_Timer.IsRunning();
    }
References UniversalTemperatureSourceSettings::m_ManualUpdate, and m_Timer.
SetActive()
void UniversalTemperatureSourceDebug::SetActive (bool pActive) inline private
Definition at line 155 of file universaltemperaturesource.c.
    {
        if (m_Settings.m_ManualUpdate)
        {
            m_Active = pActive;
            return;
        }
        if (pActive && !m_Timer.IsRunning())
        {
            m_Timer.Continue();
        }
        else
        {
            m_Timer.Stop();
        }
    }
References UniversalTemperatureSourceSettings::m_ManualUpdate, and m_Timer.
SetDefferedActive()
void UniversalTemperatureSourceDebug::SetDefferedActive (bool pActive, float pSeconds) inline private
Definition at line 173 of file universaltemperaturesource.c.
    {
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLaterByName(this, "SetActive", pSeconds * 1000, false, new Param1<bool>(pActive));
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLaterByName(), CGame::GetCallQueue(), and GetGame().
UniversalTemperatureSource()
void UniversalTemperatureSourceDebug::UniversalTemperatureSource (EntityAI pParent, UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceLambdaBase pLambda) inline private
Definition at line 63 of file universaltemperaturesource.c.
    {
        m_Active            = false;
        m_Settings          = pSettings;
        m_Lambda            = pLambda;
        m_ResultValues      = new UniversalTemperatureSourceResult();
        m_Timer             = new UniversalTemperatureSourceTimer();
        Init(pParent);
    }
References Init(), and m_Timer.
Update()
void UniversalTemperatureSourceDebug::Update (UniversalTemperatureSourceSettings settings, UniversalTemperatureSourceLambdaBase lambda) inline private
Definition at line 183 of file universaltemperaturesource.c.
    {
        if (!IsActive())
        {
            return;
        }
        if (lambda)
        {
            settings.m_Position = settings.m_Parent.GetUniversalTemperatureSourcePosition();
            lambda.Execute(settings, m_ResultValues);
        }
    }
References UniversalTemperatureSourceLambdaBase::Execute(), IsActive(), UniversalTemperatureSourceSettings::m_Parent, and UniversalTemperatureSourceSettings::m_Position.
Member Data Documentation
m_Lambda
protected ref UniversalTemperatureSourceLambdaBase UniversalTemperatureSourceDebug::m_Lambda private
Definition at line 61 of file universaltemperaturesource.c.
m_ResultValues
protected ref UniversalTemperatureSourceResult UniversalTemperatureSourceDebug::m_ResultValues private
Definition at line 60 of file universaltemperaturesource.c.
m_Settings
protected UniversalTemperatureSourceSettings UniversalTemperatureSourceDebug::m_Settings private
Definition at line 59 of file universaltemperaturesource.c.
m_Timer
protected bool m_Active protected ref UniversalTemperatureSourceTimer UniversalTemperatureSourceDebug::m_Timer private
Definition at line 58 of file universaltemperaturesource.c.