DayzKode: ScriptInputUserData Class Reference
ScriptInputUserData Class Reference
Private Member Functions
proto native void Reset ()
void ScriptInputUserData ()
proto native void Send ()
void ~ScriptInputUserData ()
Static Private Member Functions
proto static native bool CanStoreInputUserData ()
Detailed Description
Definition at line 120 of file gameplay.c.
Constructor & Destructor Documentation
ScriptInputUserData()
void ScriptInputUserData::ScriptInputUserData () private
~ScriptInputUserData()
void ScriptInputUserData::~ScriptInputUserData () private
Member Function Documentation
CanStoreInputUserData()
proto static native bool ScriptInputUserData::CanStoreInputUserData () static private
Referenced by ActionManagerClient::ActionStart(), ManBase::CloseMapEx(), InventoryItem::CombineItemsClient(), HandleInventoryManipulation(), ManBase::OnQuickBarSingleUse(), InventoryItem::OnRightClick(), EntityAI::PredictiveDropEntity(), EntityAI::PredictiveForceSwapEntities(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::PredictiveSwapEntities(), EntityAI::PredictiveTakeEntityAsAttachment(), EntityAI::PredictiveTakeEntityAsAttachmentEx(), EntityAI::PredictiveTakeEntityToCargo(), EntityAI::PredictiveTakeEntityToHands(), EntityAI::PredictiveTakeEntityToInventory(), EntityAI::PredictiveTakeEntityToTargetAttachment(), EntityAI::PredictiveTakeEntityToTargetAttachmentEx(), EntityAI::PredictiveTakeEntityToTargetCargo(), EntityAI::PredictiveTakeEntityToTargetCargoEx(), EntityAI::PredictiveTakeEntityToTargetInventory(), EntityAI::PredictiveTakeToDst(), ActionManagerClient::RequestInterruptAction(), ManBase::RequestResetADSSync(), SendEmoteRequestSync(), ManBase::SendLiftWeaponSync(), SetEntityShortcut(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), WeaponManager::StartAction(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), HumanInventory::Update(), ActionManagerClient::Update(), and Update().
Reset()
proto native void ScriptInputUserData::Reset () private
Send()
proto native void ScriptInputUserData::Send () private
Referenced by ActionManagerClient::ActionStart(), InventoryItem::CombineItemsClient(), InventoryItem::OnRightClick(), OnUpdate(), ActionManagerClient::RequestInterruptAction(), ManBase::RequestResetADSSync(), SendEmoteRequestSync(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), ManBase::SendLiftWeaponSync(), SetEntityShortcut(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), WeaponManager::Synchronize(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), HumanInventory::Update(), ActionManagerClient::Update(), and Update().