DayzKode: DestructionEffectBase Class Reference
DestructionEffectBase Class Reference
Private Member Functions
private void DealExplosionDamage ()
bool HasExplosionDamage ()
private void Init ()
void OnEntityDestroyedOneTimeClient (EntityAI entity, int oldLevel, string zone)
void OnEntityDestroyedOneTimeServer (EntityAI entity, int oldLevel, string zone)
void OnEntityDestroyedPersistentClient (EntityAI entity, string zone)
void OnEntityDestroyedPersistentServer (EntityAI entity, string zone)
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnHealthLevelChanged (notnull EntityAI entity, int oldLevel, int newLevel, string zone)
private ParticleSource PlayParticle (int particleType, bool attach=false)
private void ReplaceEntityServer ()
void ~DestructionEffectBase ()
Private Attributes
string m_AmmoType
DamageType m_DamageType
EntityAI m_Entity
bool m_EntityIsTakeable
bool m_HasExplosionDamage
bool m_KeepHealthOnReplace
int m_ParticleOneTime
int m_ParticlePersistent
ParticleSource m_POneTime
ParticleSource m_PPersistent
int m_ReplaceDelay
string m_ReplaceWithEntity
EffectSound m_SOneTime
string m_SoundSetOneTime
string m_SoundSetPersistent
EffectSound m_SPersistent
Detailed Description
Definition at line 1 of file destructioneffectbase.c.
Constructor & Destructor Documentation
~DestructionEffectBase()
void DestructionEffectBase::~DestructionEffectBase () inline private
Definition at line 28 of file destructioneffectbase.c.
    {
        if (m_POneTime)
        {
            m_POneTime.Stop();
        }
        if (m_PPersistent)
        {
            m_PPersistent.Stop();
        }
        SEffectManager.DestroyEffect(m_SOneTime);
        SEffectManager.DestroyEffect(m_SPersistent);
    }
References SEffectManager::DestroyEffect(), m_POneTime, m_PPersistent, m_SOneTime, m_SPersistent, and Particle::Stop().
Member Function Documentation
DealExplosionDamage()
private void DestructionEffectBase::DealExplosionDamage () inline private
Definition at line 50 of file destructioneffectbase.c.
    {
        DamageSystem.ExplosionDamage(m_Entity, null, m_AmmoType, m_Entity.GetPosition(), m_DamageType);
    }
References m_AmmoType, m_DamageType, and m_Entity.
Referenced by OnHealthLevelChanged().
HasExplosionDamage()
bool DestructionEffectBase::HasExplosionDamage () inline private
Definition at line 45 of file destructioneffectbase.c.
    {
        return (m_HasExplosionDamage && m_AmmoType);
    }
References m_AmmoType, and m_HasExplosionDamage.
Referenced by OnHealthLevelChanged().
Init()
private void DestructionEffectBase::Init () private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedOneTimeClient()
void DestructionEffectBase::OnEntityDestroyedOneTimeClient (EntityAI entity, int oldLevel, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedOneTimeServer()
void DestructionEffectBase::OnEntityDestroyedOneTimeServer (EntityAI entity, int oldLevel, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedPersistentClient()
void DestructionEffectBase::OnEntityDestroyedPersistentClient (EntityAI entity, string zone) private
Referenced by OnHealthLevelChanged().
OnEntityDestroyedPersistentServer()
void DestructionEffectBase::OnEntityDestroyedPersistentServer (EntityAI entity, string zone) private
Referenced by OnHealthLevelChanged().
OnExplosionEffects()
void DestructionEffectBase::OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) private
OnHealthLevelChanged()
void DestructionEffectBase::OnHealthLevelChanged (notnull EntityAI entity, int oldLevel, int newLevel, string zone) inline private
Definition at line 55 of file destructioneffectbase.c.
    {
        m_Entity = entity;
        Init();
        if (GetGame().IsServer())
        {
            entity.SetTakeable(m_EntityIsTakeable);
            if (oldLevel != -1 || entity.m_Initialized)
            {
                if (m_ReplaceWithEntity)
                {
                    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(ReplaceEntityServer, m_ReplaceDelay, false);
                }
                if (HasExplosionDamage())
                {
                    DealExplosionDamage();
                }
                OnEntityDestroyedOneTimeServer(entity, oldLevel, zone);
            }
            OnEntityDestroyedPersistentServer(entity, zone);
        }
        #ifndef SERVER//client OR single
        {
            if (oldLevel != -1 || entity.m_Initialized)//one time
            {
                m_POneTime = PlayParticle(m_ParticleOneTime);
                if (m_POneTime)
                {
                    m_POneTime.SetOwner(this);
                }
                OnEntityDestroyedOneTimeClient(entity, oldLevel, zone);
                m_Entity.PlaySoundSet(m_SOneTime, m_SoundSetOneTime, 0, 0 );
                m_Entity.PlaySoundSetLoop(m_SPersistent, m_SoundSetPersistent, 0, 0 );
            }
            else//Persistent
            {
                OnEntityDestroyedPersistentClient(entity, zone);
                m_Entity.PlaySoundSetLoop(m_SPersistent, m_SoundSetPersistent, 0, 0 );
            }
            m_PPersistent = PlayParticle(m_ParticlePersistent, true);
            if (m_PPersistent)
            {
                m_PPersistent.SetOwner(this);
            }
        }
        #endif
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), DealExplosionDamage(), CGame::GetCallQueue(), GetGame(), HasExplosionDamage(), Init(), m_Entity, m_EntityIsTakeable, m_ParticleOneTime, m_ParticlePersistent, m_POneTime, m_PPersistent, m_ReplaceDelay, m_ReplaceWithEntity, m_SOneTime, m_SoundSetOneTime, m_SoundSetPersistent, m_SPersistent, OnEntityDestroyedOneTimeClient(), OnEntityDestroyedOneTimeServer(), OnEntityDestroyedPersistentClient(), OnEntityDestroyedPersistentServer(), PlayParticle(), ReplaceEntityServer(), and ParticleSource::SetOwner().
PlayParticle()
private ParticleSource DestructionEffectBase::PlayParticle (int particleType, bool attach = false) inline private
Definition at line 121 of file destructioneffectbase.c.
    {
        if (!m_Entity)
        {
            ErrorEx("Missing entity - something went wrong");
            return null;
        }
        if (particleType)
        {
            ParticleSource p = ParticleManager.GetInstance().PlayInWorld(particleType, m_Entity.GetPosition());
            if (attach && p)
            {
                p.AddAsChild(m_Entity);//Note: it's also possible to directly play on object: Particle.PlayOnObject
            }
            return p;
        }
        return null;
    }
References ParticleSource::AddAsChild(), ErrorEx, m_Entity, and ParticleManager().
Referenced by OnHealthLevelChanged().
ReplaceEntityServer()
private void DestructionEffectBase::ReplaceEntityServer () inline private
Definition at line 110 of file destructioneffectbase.c.
    {
        EntityAI dead_entity = EntityAI.Cast(GetGame().CreateObjectEx(m_ReplaceWithEntity, m_Entity.GetPosition(), ECE_OBJECT_SWAP, RF_ORIGINAL));
        dead_entity.SetOrientation(m_Entity.GetOrientation());
        if (m_KeepHealthOnReplace)
        {
            dead_entity.SetHealth(m_Entity.GetHealth());
        }
        m_Entity.Delete();
    }
References ECE_OBJECT_SWAP, GetGame(), m_Entity, m_KeepHealthOnReplace, m_ReplaceWithEntity, and RF_ORIGINAL.
Referenced by OnHealthLevelChanged().
Member Data Documentation
m_AmmoType
string DestructionEffectBase::m_AmmoType private
Definition at line 25 of file destructioneffectbase.c.
Referenced by DealExplosionDamage(), HasExplosionDamage(), and DestructionEffectGasCanister::Init().
m_DamageType
DamageType DestructionEffectBase::m_DamageType private
Definition at line 24 of file destructioneffectbase.c.
Referenced by DealExplosionDamage(), and DestructionEffectGasCanister::Init().
m_Entity
EntityAI DestructionEffectBase::m_Entity private
Definition at line 3 of file destructioneffectbase.c.
Referenced by DealExplosionDamage(), OnHealthLevelChanged(), PlayParticle(), and ReplaceEntityServer().
m_EntityIsTakeable
bool DestructionEffectBase::m_EntityIsTakeable private
Definition at line 5 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_HasExplosionDamage
bool DestructionEffectBase::m_HasExplosionDamage private
Definition at line 23 of file destructioneffectbase.c.
Referenced by HasExplosionDamage(), and DestructionEffectGasCanister::Init().
m_KeepHealthOnReplace
bool DestructionEffectBase::m_KeepHealthOnReplace private
Definition at line 19 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and ReplaceEntityServer().
m_ParticleOneTime
int DestructionEffectBase::m_ParticleOneTime private
Definition at line 10 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_ParticlePersistent
int DestructionEffectBase::m_ParticlePersistent private
Definition at line 11 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_POneTime
ParticleSource DestructionEffectBase::m_POneTime private
Definition at line 7 of file destructioneffectbase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_PPersistent
ParticleSource DestructionEffectBase::m_PPersistent private
Definition at line 8 of file destructioneffectbase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_ReplaceDelay
int DestructionEffectBase::m_ReplaceDelay private
Definition at line 21 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_ReplaceWithEntity
string DestructionEffectBase::m_ReplaceWithEntity private
Definition at line 20 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), OnHealthLevelChanged(), and ReplaceEntityServer().
m_SOneTime
EffectSound DestructionEffectBase::m_SOneTime private
Definition at line 13 of file destructioneffectbase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().
m_SoundSetOneTime
string DestructionEffectBase::m_SoundSetOneTime private
Definition at line 16 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_SoundSetPersistent
string DestructionEffectBase::m_SoundSetPersistent private
Definition at line 17 of file destructioneffectbase.c.
Referenced by DestructionEffectGasCanister::Init(), and OnHealthLevelChanged().
m_SPersistent
EffectSound DestructionEffectBase::m_SPersistent private
Definition at line 14 of file destructioneffectbase.c.
Referenced by OnHealthLevelChanged(), and ~DestructionEffectBase().