DayzKode: SalineMdfr Class Reference
SalineMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
float CalculateRegenTime ()
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_RegenTime
Detailed Description
Definition at line 1 of file saline.c.
Member Function Documentation
ActivateCondition()
override bool SalineMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file saline.c.
    {
        return false;
    }
CalculateRegenTime()
float SalineMdfr::CalculateRegenTime () inline private
Definition at line 63 of file saline.c.
    {
        float regen_time = PlayerConstants.SALINE_LIQUID_AMOUNT / PlayerConstants.SALINE_BLOOD_REGEN_PER_SEC;
        return regen_time;
    }
References PlayerConstants::SALINE_BLOOD_REGEN_PER_SEC, and PlayerConstants::SALINE_LIQUID_AMOUNT.
Referenced by Init().
DeactivateCondition()
override bool SalineMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 20 of file saline.c.
    {
        float attached_time = GetAttachedTime();
        if ( attached_time > m_RegenTime )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and m_RegenTime.
Init()
override void SalineMdfr::Init () inline private
Definition at line 4 of file saline.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_SALINE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        m_RegenTime = CalculateRegenTime();
        DisableActivateCheck();
    }
References CalculateRegenTime(), DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_RegenTime, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void SalineMdfr::OnActivate (PlayerBase player) inline private
Definition at line 39 of file saline.c.
    {
        player.IncreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnDeactivate()
override void SalineMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 48 of file saline.c.
    {
        player.DecreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnReconnect()
override void SalineMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 34 of file saline.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void SalineMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 57 of file saline.c.
    {
        player.AddHealth("", "Blood", PlayerConstants.SALINE_BLOOD_REGEN_PER_SEC * deltaT);
        player.GetStatWater().Add( PlayerConstants.SALINE_WATER_REGEN_PER_SEC * deltaT );
    }
References PlayerConstants::SALINE_BLOOD_REGEN_PER_SEC, and PlayerConstants::SALINE_WATER_REGEN_PER_SEC.
Member Data Documentation
m_RegenTime
float SalineMdfr::m_RegenTime private
Definition at line 3 of file saline.c.
Referenced by DeactivateCondition(), and Init().