DayzKode: DayZPlayerUtils Class Reference
DayZPlayerUtils Class Reference
Private Member Functions
private void DayZPlayerUtils ()
cannot be instantiated
Static Private Member Functions
static EWaterLevels CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel)
static proto native void ClearComponentCollisions ()
static int ConvertStanceMaskToStanceIdx (int stanceMask)
static proto native bool DebugOverrideAnimationRotation (string pAnimName, vector pRotation)
overrides total animation rotation
static proto native bool DebugOverrideAnimationSpeed (string pAnimName, float pSpeed)
overrides total animation speed
static proto native bool DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation)
overrides total animation translation
static proto native void DrawDebugBox (vector pos, float size, int color)
draws debug box (color=red)
static proto native void DrawDebugText (string text, vector pos, float size)
static proto native void DrawStartFrame ()
clear info - new draw starts
static proto native void EnableDebugDraw (bool pEnable)
enables debug draw in functions
static proto native bool FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags)
inventory DayZPlayer utils
static proto native void GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList)
returns entities in height-extended 2D cone
static Object GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets=NULL)
returns fight target
static proto native vector GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex)
static bool HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName)
static bool HandleDropMagazine (DayZPlayer player, Magazine mag)
static bool HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop=true)
static private void InitCachedEntList ()
static proto native bool InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules)
initializes table of component collisions
static void InitPlayerComponentCollisions (Human player)
static proto native bool IsComponentCollisionInitialized ()
static proto float LinearRangeClamp (float pValueX, float pValueY, float pLimits[])
static proto native void PhysicsGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList)
returns entities overlapping/touching in AABB box -
static proto native bool PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck=false)
static proto native void SceneGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList)
returns entities overlapping/touching in AABB box -
static Magazine SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName)
Static Private Attributes
static private ref array< Object > m_CachedEntList
Detailed Description
Definition at line 4 of file dayzplayerutils.c.
Constructor & Destructor Documentation
DayZPlayerUtils()
private void DayZPlayerUtils::DayZPlayerUtils () inline private
cannot be instantiated
Definition at line 450 of file dayzplayerutils.c.
{};
Member Function Documentation
CheckWaterLevel()
static EWaterLevels DayZPlayerUtils::CheckWaterLevel (DayZPlayer pPlayer, out vector waterLevel) inline static private
if total water depth >= 1.5m && character is 1.5m in water
Definition at line 414 of file dayzplayerutils.c.
    {
        SHumanCommandSwimSettings swimData = pPlayer.GetDayZPlayerType().CommandSwimSettingsW();
        vector  pp = pPlayer.GetPosition();
        waterLevel = HumanCommandSwim.WaterLevelCheck(pPlayer, pp);
        if (waterLevel[1] < swimData.m_fToCrouchLevel)
        {
            return EWaterLevels.LEVEL_LOW;
        }
        else if (waterLevel[1] >= swimData.m_fToCrouchLevel && waterLevel[1] < swimData.m_fToErectLevel)
        {
            return EWaterLevels.LEVEL_CROUCH;
        }
        else// if (waterLevel[1] >= swimData.m_fToErectLevel)
        {
            if (waterLevel[0] >= swimData.m_fWaterLevelIn && waterLevel[1] >= swimData.m_fWaterLevelIn)
            {
                return EWaterLevels.LEVEL_SWIM_START;
            }
            else
            {
                return EWaterLevels.LEVEL_ERECT;
            }
        }
    }
References HumanCommandSwim(), SHumanCommandSwimSettings::m_fToCrouchLevel, SHumanCommandSwimSettings::m_fToErectLevel, and SHumanCommandSwimSettings::m_fWaterLevelIn.
Referenced by DayZPlayerImplementSwimming::CheckSwimmingStart(), and InterruptWaterCheck().
ClearComponentCollisions()
DayZPlayerUtils::ClearComponentCollisions () static private
ConvertStanceMaskToStanceIdx()
static int DayZPlayerUtils::ConvertStanceMaskToStanceIdx (int stanceMask) inline static private
Definition at line 388 of file dayzplayerutils.c.
    {
        switch (stanceMask)
        {
            case stanceMask & DayZPlayerConstants.STANCEMASK_PRONE:
                return DayZPlayerConstants.STANCEIDX_PRONE;
            case stanceMask & DayZPlayerConstants.STANCEMASK_CROUCH:
                return DayZPlayerConstants.STANCEIDX_CROUCH;
            case stanceMask & DayZPlayerConstants.STANCEMASK_ERECT:
                return DayZPlayerConstants.STANCEIDX_ERECT;
            case stanceMask & DayZPlayerConstants.STANCEMASK_RAISEDPRONE:
                return DayZPlayerConstants.STANCEIDX_RAISEDPRONE;
            case stanceMask & DayZPlayerConstants.STANCEMASK_RAISEDCROUCH:
                return DayZPlayerConstants.STANCEIDX_RAISEDCROUCH;
            case stanceMask & DayZPlayerConstants.STANCEMASK_RAISEDERECT:
                return DayZPlayerConstants.STANCEIDX_RAISEDERECT;
        }
        return -1;
    }
Referenced by Can(), and EmoteBase::EmoteFBStanceCheck().
DebugOverrideAnimationRotation()
static proto native bool DayZPlayerUtils::DebugOverrideAnimationRotation (string pAnimName, vector pRotation) static private
overrides total animation rotation
DebugOverrideAnimationSpeed()
static proto native bool DayZPlayerUtils::DebugOverrideAnimationSpeed (string pAnimName, float pSpeed) static private
overrides total animation speed
DebugOverrideAnimationTranslation()
static proto native bool DayZPlayerUtils::DebugOverrideAnimationTranslation (string pAnimName, vector pTranslation) static private
overrides total animation translation
DrawDebugBox()
static proto native void DayZPlayerUtils::DrawDebugBox (vector pos, float size, int color) static private
draws debug box (color=red)
DrawDebugText()
static proto native void DayZPlayerUtils::DrawDebugText (string text, vector pos, float size) static private
DrawStartFrame()
static proto native void DayZPlayerUtils::DrawStartFrame () static private
clear info - new draw starts
EnableDebugDraw()
static proto native void DayZPlayerUtils::EnableDebugDraw (bool pEnable) static private
enables debug draw in functions
FindMagazinesForAmmo()
DayZPlayerUtils::FindMagazinesForAmmo (DayZPlayer player, string ammoTypeName, out array< Magazine > mags) static private
inventory DayZPlayer utils
searches inventory for all magazines that can hold specified ammo type
Parameters
[in] player DayZPlayer
[in] ammoTypeName type name of the cartridge
[out] mags array filled with suitable magazines
Returns
true if found at least one
Referenced by HandleStoreCartridge(), and SelectStoreCartridge().
GetEntitiesInCone()
DayZPlayerUtils::GetEntitiesInCone (vector pos, vector dir, float angle, float dist, float minHeigh, float maxHeight, out array< Object > entList) static private
returns entities in height-extended 2D cone
Parameters
[in] angle angle in degrees
[in] minHeigh cone 3D-extension Y min
[in] maxHeight cone 3D-extension Y max
Note
the detection hits points/faces from ANY non-edit model geometry, including resolution LODs, regardless of animation hiding (scaling). That is why certain animated objects, like flags in folded state, get detected from significant distance away!
Referenced by GetMeleeTarget(), and VicinityItemManager::RefreshVicinityItems().
GetMeleeTarget()
static Object DayZPlayerUtils::GetMeleeTarget (vector pos, vector dir, float angle, float dist, float minHeight, float maxHeight, EntityAI pToIgnore, array< typename > targetableObjects, out array< Object > allTargets = NULL) inline static private
returns fight target
Definition at line 81 of file dayzplayerutils.c.
    {
        // Print("In: GetFightTarget");
        InitCachedEntList();
        GetEntitiesInCone(pos, dir, angle, dist, minHeight, maxHeight, m_CachedEntList);
        Object ret      = NULL;
        Object obj      = NULL;
        float       retVal  = dist * 2;     // max value
        float       tgAngle = Math.Tan(Math.DEG2RAD * angle);
        // DrawStartFrame();
        foreach(auto ent: m_CachedEntList)
        {
            if (ent == pToIgnore)
            {
                continue;
            }
            Class.CastTo(obj, ent);
            if(obj)
            {
                // check for targetable objects
                if( !obj.IsAnyInherited(targetableObjects) )
                    { continue; }
                if( !obj.IsAlive() )
                    { continue; }
            }
            vector entpos = ent.GetPosition();
            vector diff         = entpos - pos;
            float  cDistSq      = diff.LengthSq();
            if (cDistSq > dist*dist)    // out of distance
            {
                //Print("out of distance");
                continue;
            }
            float  frontDist    = diff[0]*dir[0] + diff[2]*dir[2];
            if (frontDist < 0.1)    // behind the pos/dist half plane or further than dist
            {
                //Print("behind the pos/dist half plane or further than dist");
                continue;
            }
            vector project  = pos + dir * frontDist;
            vector posdiff = Vector(project[0] - entpos[0], 0, project[2] - entpos[2]);
            float sideDist = posdiff.LengthSq();
            if (sideDist > tgAngle) // out of cone
            {
                //Print("out of cone");
                continue;
            }
            float  sum      = frontDist + sideDist;
            if (sum < retVal)
            {
                ret     = ent;
                retVal  = sum;
            }
            else
            {
                //Print("sum !< retVal");
            }
            // string txt       = project.ToString() + ": " + sum.ToString();
            // DrawDebugBox(project,0.01,0xffff0000);
            // DrawDebugBox(entpos,0.01,0xffff0000);
            // DrawDebugText(txt, project, 1.0);
            allTargets.Insert(ent);
        }
        return ret;
    }
References Class::CastTo(), Math::DEG2RAD, GetEntitiesInCone(), InitCachedEntList(), vector::LengthSq(), m_CachedEntList, Math::Tan(), and Vector().
Referenced by DayZInfected::ChaseAttackLogic(), and DayZInfected::FightAttackLogic().
GetMemoryPointPositionBoneRelative()
static proto native vector DayZPlayerUtils::GetMemoryPointPositionBoneRelative (DayZPlayer pPlayer, int pBoneIndex, int pPointIndex) static private
HandleDropCartridge()
static bool DayZPlayerUtils::HandleDropCartridge (DayZPlayer player, float damage, string cartTypeName, string magTypeName) inline static private
Definition at line 260 of file dayzplayerutils.c.
    {
        vector pos = player.GetPosition();
        EntityAI eai_gnd = player.SpawnEntityOnGroundPos(magTypeName, pos);
        if (eai_gnd && eai_gnd.IsInherited(Magazine))
        {
            Magazine mag_gnd;
            if (Class.CastTo(mag_gnd, eai_gnd))
            {
                mag_gnd.ServerSetAmmoCount(0);
                if (mag_gnd.ServerStoreCartridge(damage, cartTypeName))
                {
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo().
Referenced by HandleStoreCartridge(), and WeaponChambering_Base::OnAbort().
HandleDropMagazine()
static bool DayZPlayerUtils::HandleDropMagazine (DayZPlayer player, Magazine mag) inline static private
Definition at line 241 of file dayzplayerutils.c.
    {
        vector m4[4];
        Math3D.MatrixIdentity4(m4);
        GameInventory.PrepareDropEntityPos(player, mag, m4);
        InventoryLocation il_mag_next = new InventoryLocation;
        il_mag_next.SetGround(mag, m4);
        InventoryLocation il_mag_curr = new InventoryLocation;
        if (mag.GetInventory().GetCurrentInventoryLocation(il_mag_curr))
        {
            return GameInventory.LocationSyncMoveEntity(il_mag_curr, il_mag_next);
        }
        else
        {
            Error("DayZPlayerUtils::HandleDropMagazine - cannot get current inv location of mag=" + mag);
            return false;
        }
    }
References Error(), Math3D::MatrixIdentity4(), and InventoryLocation::SetGround().
Referenced by WeaponStateBase::OnAbort(), OnAbort(), and WeaponStateBase::OnExit().
HandleStoreCartridge()
static bool DayZPlayerUtils::HandleStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, float damage, string cartTypeName, string magTypeName, bool CanDrop = true) inline static private
Definition at line 279 of file dayzplayerutils.c.
    {
        if (damage < 1.0)
        {
            // find suitable heap / mag
            ref array<Magazine> mags = new array<Magazine>;
            if (DayZPlayerUtils.FindMagazinesForAmmo(player, magTypeName, mags))
            {
                int health_lvl = -1;
                float test_heatlh = 1 - damage;
                int sz = mags.Count();
                for (int i = 0; i < sz; ++i)
                {
                    Magazine mag_i = mags.Get(i);
                     // add small amout for
                    if( health_lvl == -1)
                    {
                        if (mag_i.CanAddCartridges(1) /*&& Math.AbsFloat(1 - mag_i.GetHealthLevelValue(mag_i.GetHealthLevel()) - damage) < 0.01*/)
{
                            int num_health_lvl = mag_i.GetNumberOfHealthLevels();
                            for( int j = 1; j < num_health_lvl; j++)
{
                                if (mag_i.GetHealthLevelValue(j) < test_heatlh )
{
                                    health_lvl = j - 1;
                                    break;
                                }
                            }
                        }
                    }
                    if( mag_i.GetHealthLevel() == health_lvl )
                    {
                        if (mag_i.ServerStoreCartridge(damage, cartTypeName))
                            return true;
                    }
                }
            }
            // create a new one in inventory
            InventoryLocation inv_loc = new InventoryLocation;
            if (player.GetInventory().FindFirstFreeLocationForNewEntity(magTypeName, FindInventoryLocationType.ANY, inv_loc))
            {
                EntityAI eai_inv = GetGame().SpawnEntity(magTypeName, inv_loc, ECE_IN_INVENTORY, RF_DEFAULT);
                if (eai_inv && eai_inv.IsInherited(Magazine))
                {
                    Magazine mag_inv;
                    if (Class.CastTo(mag_inv, eai_inv))
                    {
                        mag_inv.ServerSetAmmoCount(0);
                        mag_inv.SetHealth("", "", (1 - damage) * mag_inv.GetMaxHealth());
                        if (mag_inv.ServerStoreCartridge(damage, cartTypeName))
                            return true;
                    }
                }
            }
            // drop on ground
            if ( CanDrop )
                return HandleDropCartridge(player, damage, cartTypeName, magTypeName);
        }
        return false;
    }
References Class::CastTo(), ECE_IN_INVENTORY, FindMagazinesForAmmo(), GetGame(), HandleDropCartridge(), and RF_DEFAULT.
Referenced by ejectBulletAndStoreInMagazine(), and ActionEmptyMagazine::OnExecuteServer().
InitCachedEntList()
static private void DayZPlayerUtils::InitCachedEntList () inline static private
Definition at line 453 of file dayzplayerutils.c.
    {
        if (m_CachedEntList == NULL)
        {
            m_CachedEntList = new array<Object>;
        }
        m_CachedEntList.Clear();
    }
References m_CachedEntList.
Referenced by GetMeleeTarget().
InitComponentCollisions()
DayZPlayerUtils::InitComponentCollisions (Human player, array< ref ComponentCollisionBox > boxes, array< ref ComponentCollisionCapsule > capsules) static private
initializes table of component collisions
Parameters
[in] player DayZPlayer
[in] boxes array filled with box
See also
ComponentCollisionBox
Parameters
[in] capsules array filled with capsules
See also
ComponentCollisionCapsule
Returns
true if success
Referenced by InitPlayerComponentCollisions().
InitPlayerComponentCollisions()
static void DayZPlayerUtils::InitPlayerComponentCollisions (Human player) inline static private
Definition at line 365 of file dayzplayerutils.c.
    {
        if (IsComponentCollisionInitialized())
            Error("DayZPlayerUtils.InitComponentCollisions: already initialized!");
        array<ref ComponentCollisionBox> b = new array<ref ComponentCollisionBox>;
        b.Insert(new ComponentCollisionBox(0.40, 0.31, 0.31, "Pelvis", "Spine2"));
        b.Insert(new ComponentCollisionBox(0.40, 0.31, 0.31, "Spine3", "Neck"));
        array<ref ComponentCollisionCapsule> c = new array<ref ComponentCollisionCapsule>;
        c.Insert(new ComponentCollisionCapsule(0.11, "Neck1", "Head"));
        c.Insert(new ComponentCollisionCapsule(0.09, "LeftArm", "LeftArmRoll"));
        c.Insert(new ComponentCollisionCapsule(0.08, "LeftForeArm", "LeftHand"));
        c.Insert(new ComponentCollisionCapsule(0.09, "RightArm", "RightArmRoll"));
        c.Insert(new ComponentCollisionCapsule(0.08, "RightForeArm", "RightHand"));
        c.Insert(new ComponentCollisionCapsule(0.11, "LeftUpLeg", "LeftUpLegRoll"));
        c.Insert(new ComponentCollisionCapsule(0.10, "LeftLeg", "LeftFoot"));
        c.Insert(new ComponentCollisionCapsule(0.11, "RightUpLeg", "RightUpLegRoll"));
        c.Insert(new ComponentCollisionCapsule(0.10, "RightLeg", "RightFoot"));
        DayZPlayerUtils.InitComponentCollisions(player, b, c);
    }
References ComponentCollisionBox(), Error(), InitComponentCollisions(), and IsComponentCollisionInitialized().
IsComponentCollisionInitialized()
DayZPlayerUtils::IsComponentCollisionInitialized () static private
Returns
true if already initialized
Referenced by InitPlayerComponentCollisions().
LinearRangeClamp()
static proto float DayZPlayerUtils::LinearRangeClamp (float pValueX, float pValueY, float pLimits[]) static private
pLimits in form Xvalue, Ymin, Ymax, Xvalue1, Ymin1, Ymax1, .... sample 0, 0, 5, 1, 2, 3, 2, 0, 1 for X <= 0 it clamps Y to Rangle (0,5)
for X == 0.5 it clamps Y to Rangle (1,4)
for X == 1 it clamps Y to Rangle (2,3)
for X == 1.5 it clamps Y to Rangle (1,2)
for X >= 2 it clamps Y to Rangle (0,1)
Referenced by DayZPlayerImplementAiming::ProcessAimFilters().
PhysicsGetEntitiesInBox()
static proto native void DayZPlayerUtils::PhysicsGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList) static private
returns entities overlapping/touching in AABB box -
PlayerCanChangeStance()
static proto native bool DayZPlayerUtils::PlayerCanChangeStance (DayZPlayer pPlayer, int pTargetStance, bool forceCheck = false) static private
Referenced by ManBase::BrokenLegForceProne(), Can(), CanJump(), CanPickupHeavyItem(), EmoteBase::EmoteFBStanceCheck(), HandleFightLogic(), and DayZPlayerImplementSwimming::HandleSwimming().
SceneGetEntitiesInBox()
static proto native void DayZPlayerUtils::SceneGetEntitiesInBox (vector min, vector max, out array< EntityAI > entList) static private
returns entities overlapping/touching in AABB box -
SelectStoreCartridge()
static Magazine DayZPlayerUtils::SelectStoreCartridge (DayZPlayer player, Weapon_Base weapon, int muzzleIndex, Magazine exclude_mag, float damage, string magTypeName) inline static private
Definition at line 190 of file dayzplayerutils.c.
    {
        if (damage < 1.0)
        {
            // find suitable heap / mag (but not the excluded one)
            ref array<Magazine> mags = new array<Magazine>;
            if (DayZPlayerUtils.FindMagazinesForAmmo(player, magTypeName, mags))
            {
                int sz = mags.Count();
                for (int i = 0; i < sz; ++i)
                {
                    Magazine mag_i = mags.Get(i);
                    if (mag_i != exclude_mag && mag_i.CanAddCartridges(1))
                    {
                        return mag_i;
                    }
                }
            }
            // create a new one in inventory
            InventoryLocation inv_loc = new InventoryLocation;
            if (player.GetInventory().FindFirstFreeLocationForNewEntity(magTypeName, FindInventoryLocationType.ANY, inv_loc))
            {
                EntityAI eai_inv = GetGame().SpawnEntity(magTypeName, inv_loc, ECE_IN_INVENTORY, RF_DEFAULT);
                if (eai_inv && eai_inv.IsInherited(Magazine))
                {
                    Magazine mag_inv;
                    if (Class.CastTo(mag_inv, eai_inv))
                    {
                        mag_inv.ServerSetAmmoCount(0);
                        return mag_inv;
                    }
                }
            }
        }
        vector pos = player.GetPosition();
        EntityAI eai_gnd = player.SpawnEntityOnGroundPos(magTypeName, pos);
        if (eai_gnd && eai_gnd.IsInherited(Magazine))
        {
            Magazine mag_gnd;
            if (Class.CastTo(mag_gnd, eai_gnd))
            {
                mag_gnd.ServerSetAmmoCount(0);
                return mag_gnd;
            }
        }
        return NULL;
    }
References Class::CastTo(), ECE_IN_INVENTORY, FindMagazinesForAmmo(), GetGame(), and RF_DEFAULT.
Referenced by WeaponStateBase::OnEntry().
Member Data Documentation
m_CachedEntList
private ref array<Object> DayZPlayerUtils::m_CachedEntList static private
Definition at line 446 of file dayzplayerutils.c.
Referenced by GetMeleeTarget(), and InitCachedEntList().