DayzKode: PCOHandlerStats Class Reference
PCOHandlerStats Class Reference
Private Member Functions
PlayerStatsPCO_Base GetPCO (int version=-1)
void PCOHandlerStats ()
void RegisterPCO (PlayerStatsPCO_Base pco)
Private Attributes
int m_HighestVersion
ref map< int, ref PlayerStatsPCO_Base > m_PCOs = new map<int, ref PlayerStatsPCO_Base>
Detailed Description
Definition at line 3 of file playerstatspco.c.
Constructor & Destructor Documentation
PCOHandlerStats()
void PCOHandlerStats::PCOHandlerStats () inline private
Definition at line 8 of file playerstatspco.c.
    {
        RegisterPCO(new PlayerStatsPCO_v100);
        RegisterPCO(new PlayerStatsPCO_v101);
        RegisterPCO(new PlayerStatsPCO_current);
    }
References RegisterPCO().
Member Function Documentation
GetPCO()
PlayerStatsPCO_Base PCOHandlerStats::GetPCO (int version = -1) inline private
Definition at line 27 of file playerstatspco.c.
    {
        //PlayerStatsPCO_Base pco;
        if(version == -1)//no version set - fetch the highest version
        {
            return m_PCOs.Get(m_HighestVersion);
        }
        else if( !m_PCOs.Contains(version))//version set - version not present, fetch the closest lower version
        {
            for(int i = version; i > 100; i--)
            {
                if(m_PCOs.Contains(i))
                {
                    //Print("fetching PCO version:"+ i);
                    return m_PCOs.Get(i);
                }
            }
            return null;
        }
        else//version set - version present, fetch it
        {
            //Print("fetching PCO version:"+ version);
            return m_PCOs.Get(version);
        }
    }
References m_HighestVersion, and m_PCOs.
Referenced by PlayerStats::GetPCO().
RegisterPCO()
void PCOHandlerStats::RegisterPCO (PlayerStatsPCO_Base pco) inline private
Definition at line 15 of file playerstatspco.c.
    {
        int version = pco.GetVersion();
        if( version > m_HighestVersion )
        {
            m_HighestVersion = version;
        }
        m_PCOs.Insert(version, pco);
    }
References PlayerStatsPCO_Base::GetVersion(), m_HighestVersion, and m_PCOs.
Referenced by PCOHandlerStats().
Member Data Documentation
m_HighestVersion
int PCOHandlerStats::m_HighestVersion private
Definition at line 6 of file playerstatspco.c.
Referenced by GetPCO(), and RegisterPCO().
m_PCOs
ref map<int, ref PlayerStatsPCO_Base> PCOHandlerStats::m_PCOs = new map<int, ref PlayerStatsPCO_Base> private
Definition at line 5 of file playerstatspco.c.
Referenced by GetPCO(), and RegisterPCO().