DayzKode: TentBase Class Reference
TentBase Class Reference
Private Member Functions
override void AnimateCamonetByOpeningSelection (string opening_selection)
override void AnimateCamonetToggle (ToggleAnimations toggle)
void CarTent ()
void Deconstruct ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override string GetClutterCutter ()
override string GetClutterCutter ()
override string GetDeploySoundset ()
override string GetDeploySoundset ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetLoopDeploySoundset ()
string GetMaterialPath ()
string GetShelterVariant ()
override string GetSoundClose ()
override string GetSoundClose ()
override string GetSoundClose ()
override string GetSoundCloseWindow ()
override string GetSoundOpen ()
override string GetSoundOpen ()
override string GetSoundOpen ()
override string GetSoundOpenWindow ()
override void HandleCamoNetAttachment (bool hide)
override bool HasClutterCutter ()
override bool HasClutterCutter ()
override bool HasClutterCutter ()
override bool IsDeployable ()
override bool IsPlayerInside (PlayerBase player, string selection)
void MediumTent ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
void PartyTent ()
override void SetActions ()
void ShelterBase ()
void SpawnKit ()
Static Private Attributes
static const string SITE_OBJECT_TYPE = "ShelterSite"
Detailed Description
Definition at line 1 of file cartent.c.
Member Function Documentation
AnimateCamonetByOpeningSelection()
override void TentBase::AnimateCamonetByOpeningSelection (string opening_selection) inline private
Definition at line 143 of file partytent.c.
    {
        string camo = "Camo" + opening_selection.Substring(4,2);
        SetAnimationPhase(camo,1);
    }
References string::Substring().
Referenced by ItemBase::EEHealthLevelChanged().
AnimateCamonetToggle()
override void TentBase::AnimateCamonetToggle (ToggleAnimations toggle) inline private
Definition at line 129 of file partytent.c.
    {
        if (!m_CamoNet)
            return;
        bool is_closed = m_OpeningMask & toggle.GetOpeningBit();
        string camo_off = "Camo" + toggle.GetToggleOff().Substring(4,2);
        string camo_on = "Camo" + toggle.GetToggleOn().Substring(4,2);
        SetAnimationPhase( camo_off, is_closed );
        SetAnimationPhase( camo_on, !is_closed );
    }
References ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), and string::Substring().
Referenced by ItemBase::ToggleAnimation().
CarTent()
void TentBase::CarTent () inline private
Definition at line 3 of file cartent.c.
    {
        m_ToggleAnimations.Insert( new ToggleAnimations("EntranceO", "EntranceC", OPENING_0), 0 );
        m_ShowAnimationsWhenPitched.Insert( "Body" );
        //m_ShowAnimationsWhenPitched.Insert( "EntranceO" );
        m_ShowAnimationsWhenPitched.Insert( "Pack" );
        m_ShowAnimationsWhenPacked.Insert( "Inventory" );
        m_HalfExtents = Vector(1.8, 0.33, 3.4);
    }
References m_HalfExtents, and Vector().
Deconstruct()
void TentBase::Deconstruct () inline private
Definition at line 31 of file shelter.c.
    {
        StaticConstructionMethods.SpawnConstructionMaterialPiles(this,null,GetMaterialPath(),GetShelterVariant());
        SpawnKit();
        Delete();
    }
References Delete(), ShelterBase::GetShelterVariant(), and StaticConstructionMethods::SpawnConstructionMaterialPiles().
EEInit() [1/3]
override void TentBase::EEInit () inline private
Definition at line 16 of file cartent.c.
    {
        super.EEInit();
    }
EEInit() [2/3]
override void TentBase::EEInit () inline private
Definition at line 16 of file mediumtent.c.
    {
        super.EEInit();
    }
EEInit() [3/3]
override void TentBase::EEInit () inline private
Definition at line 24 of file shelter.c.
    {
        super.EEInit();
        Pitch(true,true);
    }
GetClutterCutter() [1/2]
override string TentBase::GetClutterCutter () inline private
Definition at line 41 of file mediumtent.c.
    {
        return "MediumTentClutterCutter";
    }
Referenced by ItemBase::OnStoreLoad().
GetClutterCutter() [2/2]
override string TentBase::GetClutterCutter () inline private
Definition at line 51 of file partytent.c.
    {
        return "LargeTentClutterCutter"; //TODO add custom clutter cutter?
    }
GetDeploySoundset() [1/3]
override string TentBase::GetDeploySoundset () inline private
Definition at line 50 of file cartent.c.
    {
        return "placeCarTent_SoundSet";
    }
GetDeploySoundset() [2/3]
override string TentBase::GetDeploySoundset () inline private
Definition at line 66 of file mediumtent.c.
    {
        return "placeMediumTent_SoundSet";
    }
GetDeploySoundset() [3/3]
override string TentBase::GetDeploySoundset () inline private
Definition at line 76 of file partytent.c.
    {
        return "placeLargeTent_SoundSet";
    }
GetLoopDeploySoundset() [1/3]
override string TentBase::GetLoopDeploySoundset () inline private
Definition at line 55 of file cartent.c.
    {
        return "cartent_deploy_SoundSet";
    }
Referenced by ItemBase::PlayDeployLoopSound().
GetLoopDeploySoundset() [2/3]
override string TentBase::GetLoopDeploySoundset () inline private
Definition at line 71 of file mediumtent.c.
    {
        return "mediumtent_deploy_SoundSet";
    }
GetLoopDeploySoundset() [3/3]
override string TentBase::GetLoopDeploySoundset () inline private
Definition at line 81 of file partytent.c.
    {
        return "largetent_deploy_SoundSet";
    }
GetMaterialPath()
string TentBase::GetMaterialPath () inline private
Definition at line 38 of file shelter.c.
    {
        return "" + CFG_VEHICLESPATH + " " + SITE_OBJECT_TYPE + " Construction site " + GetShelterVariant() + " Materials";
    }
References CFG_VEHICLESPATH, and ShelterBase::GetShelterVariant().
GetShelterVariant()
string TentBase::GetShelterVariant () inline private
Definition at line 43 of file shelter.c.
    {
        return "";
    }
GetSoundClose() [1/3]
override string TentBase::GetSoundClose () inline private
Definition at line 31 of file cartent.c.
    {
        return "CarTent_Door_Close_SoundSet";
    }
Referenced by ItemBase::SoundTentClosePlay().
GetSoundClose() [2/3]
override string TentBase::GetSoundClose () inline private
Definition at line 31 of file mediumtent.c.
    {
        return "MediumTent_Door_Close_SoundSet";
    }
GetSoundClose() [3/3]
override string TentBase::GetSoundClose () inline private
Definition at line 31 of file partytent.c.
    {
        return "LargeTent_Door_Close_SoundSet";
    }
GetSoundCloseWindow()
override string TentBase::GetSoundCloseWindow () inline private
Definition at line 41 of file partytent.c.
    {
        return "LargeTent_Window_Close_SoundSet";
    }
Referenced by ItemBase::SoundTentCloseWindowPlay().
GetSoundOpen() [1/3]
override string TentBase::GetSoundOpen () inline private
Definition at line 26 of file cartent.c.
    {
        return "CarTent_Door_Open_SoundSet";
    }
Referenced by ItemBase::SoundTentOpenPlay().
GetSoundOpen() [2/3]
override string TentBase::GetSoundOpen () inline private
Definition at line 26 of file mediumtent.c.
    {
        return "MediumTent_Door_Open_SoundSet";
    }
GetSoundOpen() [3/3]
override string TentBase::GetSoundOpen () inline private
Definition at line 26 of file partytent.c.
    {
        return "LargeTent_Door_Open_SoundSet";
    }
GetSoundOpenWindow()
override string TentBase::GetSoundOpenWindow () inline private
Definition at line 36 of file partytent.c.
    {
        return "LargeTent_Window_Open_SoundSet";
    }
Referenced by ItemBase::SoundTentOpenWindowPlay().
HandleCamoNetAttachment()
override void TentBase::HandleCamoNetAttachment (bool hide) inline private
Definition at line 86 of file partytent.c.
    {
        bool is_closed;
        bool is_ruined;
        string component;
        string zone;
        string camo_off;
        string camo_on;
        ToggleAnimations toggle;
        for (int i = 0; i < m_ToggleAnimations.Count(); i++)
        {
            toggle = m_ToggleAnimations.GetKey(i);
            camo_off = "Camo" + toggle.GetToggleOff().Substring(4,2);
            camo_on = "Camo" + toggle.GetToggleOn().Substring(4,2);
            if (hide)
            {
                SetAnimationPhase( camo_off, hide );
                SetAnimationPhase( camo_on, hide );
            }
            else
            {
                component = toggle.GetToggleOff(); //either one works
                component.ToLower();
                DamageSystem.GetDamageZoneFromComponentName(this,component,zone);
                is_ruined = GetHealthLevel(zone) == GameConstants.STATE_RUINED;
                is_closed = m_OpeningMask & toggle.GetOpeningBit();
                if (is_closed)
                {
                    SetAnimationPhase( camo_on, is_ruined );
                }
                else
                {
                    SetAnimationPhase( camo_off, is_ruined );
                }
            }
        }
        SetAnimationPhase( "Camo_Roof", hide );
    }
References component, GetHealthLevel(), ToggleAnimations::GetOpeningBit(), ToggleAnimations::GetToggleOff(), ToggleAnimations::GetToggleOn(), GameConstants::STATE_RUINED, and string::Substring().
Referenced by ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), and ItemBase::RefreshAttachements().
HasClutterCutter() [1/3]
override bool TentBase::HasClutterCutter () inline private
Definition at line 36 of file cartent.c.
    {
        return false;
    }
Referenced by ItemBase::OnStoreLoad().
HasClutterCutter() [2/3]
override bool TentBase::HasClutterCutter () inline private
Definition at line 36 of file mediumtent.c.
    {
        return true;
    }
HasClutterCutter() [3/3]
override bool TentBase::HasClutterCutter () inline private
Definition at line 46 of file partytent.c.
    {
        return true;
    }
IsDeployable()
override bool TentBase::IsDeployable () inline private
Definition at line 45 of file cartent.c.
    {
        return true;
    }
IsPlayerInside()
override bool TentBase::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 63 of file shelter.c.
    {
        vector player_pos = player.GetPosition();
        vector shelter_pos = GetPosition();
        vector ref_dir = GetDirection();
        ref_dir[1] = 0;
        ref_dir.Normalize();
        vector x[2];
        vector b1,b2;
        GetCollisionBox(x);
        b1 = x[0];
        b2 = x[1];
        vector dir_to_shelter = shelter_pos - player_pos;
        dir_to_shelter[1] = 0;
        float len = dir_to_shelter.Length();
        dir_to_shelter.Normalize();
        vector ref_dir_angle = ref_dir.VectorToAngles();
        vector dir_to_shelter_angle = dir_to_shelter.VectorToAngles();
        vector test_angles = dir_to_shelter_angle - ref_dir_angle;
        vector test_position = test_angles.AnglesToVector() * len;
        if (test_position[0] < b1[0] || test_position[0] > b2[0] || test_position[2] < 0.2 || test_position[2] > 2.2 )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
MediumTent()
void TentBase::MediumTent () inline private
Definition at line 3 of file mediumtent.c.
    {
        m_ToggleAnimations.Insert( new ToggleAnimations("EntranceO", "EntranceC", OPENING_0), 0 );
        m_ShowAnimationsWhenPitched.Insert( "Body" );
        //m_ShowAnimationsWhenPitched.Insert( "EntranceO" );
        m_ShowAnimationsWhenPitched.Insert( "Pack" );
        m_ShowAnimationsWhenPacked.Insert( "Inventory" );
        m_HalfExtents = Vector(0.8, 0.15, 1.3);
    }
References m_HalfExtents, and Vector().
OnItemLocationChanged() [1/2]
override void TentBase::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 21 of file cartent.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
    }
OnItemLocationChanged() [2/2]
override void TentBase::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 21 of file mediumtent.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
    }
OnPlacementComplete() [1/2]
override void TentBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 50 of file mediumtent.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        PlayerBase pb = PlayerBase.Cast( player );
        if ( GetGame().IsServer() )
        {
            if ( !m_ClutterCutter )
            {
                m_ClutterCutter = GetGame().CreateObjectEx( "MediumTentClutterCutter", pb.GetLocalProjectionPosition(), ECE_PLACE_ON_SURFACE );
                m_ClutterCutter.SetOrientation( pb.GetLocalProjectionOrientation() );
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), and m_ClutterCutter.
OnPlacementComplete() [2/2]
override void TentBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 60 of file partytent.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        PlayerBase pb = PlayerBase.Cast( player );
        if ( GetGame().IsServer() )
        {
            if ( !m_ClutterCutter )
            {
                m_ClutterCutter = GetGame().CreateObjectEx( "LargeTentClutterCutter", pb.GetLocalProjectionPosition(), ECE_PLACE_ON_SURFACE );
                m_ClutterCutter.SetOrientation( pb.GetLocalProjectionOrientation() );
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), and m_ClutterCutter.
PartyTent()
void TentBase::PartyTent () inline private
Definition at line 3 of file partytent.c.
    {
        m_ToggleAnimations.Insert( new ToggleAnimations("Door1o", "Door1c", OPENING_0), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Door2o", "Door2c", OPENING_1), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Door3o", "Door3c", OPENING_2), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Door4o", "Door4c", OPENING_3), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Door5o", "Door5c", OPENING_4), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Door6o", "Door6c", OPENING_5), 0 );
        m_ShowAnimationsWhenPitched.Insert( "Body" );
        m_ShowAnimationsWhenPitched.Insert( "Pack" );
        /*m_ShowAnimationsWhenPitched.Insert( "Door1o" );
        m_ShowAnimationsWhenPitched.Insert( "Door2o" );
        m_ShowAnimationsWhenPitched.Insert( "Door3o" );
        m_ShowAnimationsWhenPitched.Insert( "Door4o" );
        m_ShowAnimationsWhenPitched.Insert( "Door5o" );
        m_ShowAnimationsWhenPitched.Insert( "Door6o" );*/
        m_ShowAnimationsWhenPacked.Insert( "Inventory" );
        m_HalfExtents = Vector(1.3, 0.35, 2.7);
    }
References m_HalfExtents, and Vector().
SetActions()
override void TentBase::SetActions () inline private
Definition at line 12 of file shelter.c.
    {
        super.SetActions();
        RemoveAction(ActionTogglePlaceObject);
        RemoveAction(ActionToggleTentOpen);
        RemoveAction(ActionPackTent);
        RemoveAction(ActionDeployObject);
        AddAction(ActionDeconstructShelter);
    }
References ActionDeployObject(), ActionPackTent(), AddAction(), and RemoveAction().
ShelterBase()
void TentBase::ShelterBase () inline private
Definition at line 4 of file shelter.c.
    {
        m_ShowAnimationsWhenPitched.Insert( "Body" );
        m_ShowAnimationsWhenPacked.Insert( "Body" ); //redundant?
        m_HalfExtents = Vector(0.8, 0.15, 1.3);
    }
References m_HalfExtents, and Vector().
SpawnKit()
void TentBase::SpawnKit () inline private
Definition at line 48 of file shelter.c.
    {
        ItemBase construction_kit = ItemBase.Cast( GetGame().CreateObjectEx( "ShelterKit", GetPosition(), ECE_PLACE_ON_SURFACE ) );
        construction_kit.SetHealth01( "","",GetHealth01() );
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetHealth01(), and GetPosition.
Member Data Documentation
SITE_OBJECT_TYPE
const string TentBase::SITE_OBJECT_TYPE = "ShelterSite" static private
Definition at line 3 of file shelter.c.