DayzKode: ManBase Class Reference
ManBase Class Reference
Private Member Functions
void AddAction (typename actionName)
void AddAction (typename actionName, out TInputActionMap InputActionMap)
void AddActiveNV (int type)
override void AddItemToDelete (EntityAI item)
void AddPlayerLoad (float addedload)
void AddToEnvironmentTemperature (float pTemperature)
DEPRECATED.
void AdjustBandana (EntityAI item, string slot_name)
override void AfterStoreLoad ()
bool AnimCommandCheck (HumanMoveCommandID mask)
void AntibioticsAttack (float value)
void ApplySplint ()
void BreakLegSound ()
void BrokenLegForceProne (bool forceOverride=false)
void BrokenLegWalkShock ()
void CalculateVisibilityForAI ()
bool CanBeRestrained ()
override bool CanBeTargetedByAI (EntityAI ai)
override bool CanChangeStance (int previousStance, int newStance)
override bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
override bool CanConsumeStamina (EStaminaConsumers consumer)
bool CanDeleteItems ()
override bool CanDropEntity (notnull EntityAI item)
bool CanEatAndDrink ()
override bool CanJump ()
bool CanManipulateInventory ()
override bool CanPickupHeavyItem (notnull EntityAI item)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveItemIntoHands (EntityAI item_to_hands)
bool CanRedirectToWeaponManager (notnull EntityAI item, out bool isActionPossible)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseCargo (EntityAI cargo)
override bool CanReleaseFromHands (EntityAI handheld)
override bool CanRoll ()
override bool CanSaveItemInHands (EntityAI item_in_hands)
bool CanShave ()
bool CanSpawnBreathVaporEffect ()
bool CanSprint ()
override bool CanStartConsumingStamina (EStaminaConsumers consumer)
override bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
bool CheckAndExecuteStackSplit (FindInventoryLocationType flags, notnull EntityAI item, notnull EntityAI target)
bool CheckAndExecuteStackSplitToInventoryLocation (InventoryLocation il, notnull EntityAI item)
override void CheckAnimationOverrides ()
void CheckDeath ()
void CheckForBurlap ()
void CheckForGag ()
void CheckHairClippingOnCharacterLoad ()
helper method for re-checking hairhiding on character load
override void CheckLiftWeapon ()
bool CheckMeleeItemDamage (ItemBase item)
void CheckSendSoundEvent ()
void CheckSoundEvent ()
void CheckZeroSoundEvent ()
void ClearInventory ()
protected void ClearLastUAMessage ()
void CloseInventoryMenu ()
void CloseMap ()
DEPRECATED; terminates map animation callback and re-enables controls.
void CloseMapEx (bool cancelled)
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool Consume (ItemBase source, float amount, EConsumeType consume_type)
void ContaminatedParticleAdjustment ()
float ConvertNonlethalDamage (float damage)
ItemBase CreateCopyOfItemInInventory (ItemBase src)
ItemBase CreateCopyOfItemInInventoryOrGround (ItemBase src)
ItemBase CreateCopyOfItemInInventoryOrGroundEx (ItemBase src, bool markItemAsSplitResult=false)
EntityAI CreateInInventory (string item_name, string cargo_type="", bool full_quantity=false)
void DamageAllLegs (float inputDmg)
void DealShock (float dmg)
void DecreaseAntibioticsCount ()
void DecreaseDiseaseCount ()
void DecreaseHealingsCount ()
override void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
void dmgDebugPrint (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
void DropAllItems ()
Drops all clothes/wearables this character is carrying on themselves.
void DropHeavyItem ()
bool DropItem (ItemBase item)
Spawn item on server side.
override void EEDelete (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemIntoHands (EntityAI item)
override void EEItemOutOfHands (EntityAI item)
override void EEKilled (Object killer)
void EndFighting ()
void EndSurrenderRequest (SurrenderData data=null)
ends surrender, originally intended for surrender->restrained transitioning
override void EOnFrame (IEntity other, float timeSlice)
override void EOnPostFrame (IEntity other, int extra)
EntityAI FindCargoByBaseType (string searched_item)
int FindQuickBarEntityIndex (EntityAI entity)
void FixAllInventoryItems ()
void ForceUpdateInjuredState ()
update injured state immediately
void FreezeCheck ()
ActionManagerBase GetActionManager ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
override int GetAgents ()
vector GetAimPosition ()
int GetBleedingBits ()
BleedingSourcesManagerRemote GetBleedingManagerRemote ()
BleedingSourcesManagerServer GetBleedingManagerServer ()
int GetBleedingSourceCount ()
int GetBloodType ()
float GetBordersImmunity ()
int GetBreathVapourLevel ()
eBrokenLegs GetBrokenLegs ()
override vector GetCenter ()
ConstructionActionData GetConstructionActionData ()
CraftingManager GetCraftingManager ()
int GetCraftingRecipeID ()
DayZPlayerCamera GetCurrentPlayerCamera ()
int GetCurrentRecipe ()
DamageDealtEffect GetDamageDealtEffect ()
void GetDebugActions (out TSelectableActionInfoArray outputList)
DebugMonitorValues GetDebugMonitorValues ()
override string GetDefaultHitComponent ()
returns default hit component (fallback)
override vector GetDefaultHitPosition ()
float GetDeltaT ()
EmoteManager GetEmoteManager ()
float GetFeetDamageMoveModifier ()
bool GetFlagTendencyRaise ()
DEPRECATED.
FlashbangEffect GetFlashbangEffect ()
float GetHealthRegenSpeed ()
override string GetHitComponentForAI ()
Melee helpers.
bool GetHitPPEEnabled ()
Hologram GetHologramLocal ()
Hologram GetHologramServer ()
float GetImmunity ()
returns player's immunity strength between 0..1
EStatLevels GetImmunityLevel ()
returns player's immunity level
ItemBase GetItemInHands ()
ItemBase GetItemOnHead ()
Returns item on player's head. For an example, a headtorch.
ItemBase GetItemOnSlot (string slot_type)
Returns item that's on this player's attachment slot. Parameter slot_type should be a string from config parameter 'itemInfo[]' like "Legs", "Headgear" and so on.
vector GetLastFirePoint ()
int GetLastFirePointIndex ()
float GetLastFirePointRot ()
bool GetLastMapInfo (out float scale, out vector pos)
int GetLastShavedSeconds ()
string GetLastUAMessage ()
UA Last Message.
int GetLifeSpanState ()
bool GetLiquidTendencyDrain ()
vector GetLocalProjectionOrientation ()
vector GetLocalProjectionPosition ()
EntityAI GetMagazineToReload (EntityAI weapon)
bool GetMapClosingSyncSent ()
MapNavigationBehaviour GetMapNavigationBehaviour ()
eMixedSoundStates GetMixedSoundStates ()
ModifiersManager GetModifiersManager ()
int GetNoisePresenceInAI ()
Return actual noise presence of player.
NotifiersManager GetNotifiersManager ()
int GetNVType ()
array< int > GetNVTypesArray ()
string GetPlayerClass ()
float GetPlayerLoad ()
PlayerSoundEventHandler GetPlayerSoundEventHandler ()
PlayerSoundManagerServer GetPlayerSoundManagerServer ()
PlayerStats GetPlayerStats ()
EPulseType GetPulseType ()
override int GetQuickBarBonus ()
EntityAI GetQuickBarEntity (int index)
int GetQuickBarSize ()
RandomGeneratorSyncManager GetRandomGeneratorSyncManager ()
int GetShakeLevel ()
ShockDealtEffect GetShockEffect ()
float GetSimplifiedShockNormalized ()
int GetSingleAgentCount (int agent_id)
float GetSingleAgentCountNormalized (int agent_id)
SoftSkillsManager GetSoftSkillsManager ()
StaminaHandler GetStaminaHandler ()
int GetStaminaState ()
PlayerStat< int > GetStatBloodType ()
float GetStatBordersBlood ()
float GetStatBordersEnergy ()
float GetStatBordersHealth ()
float GetStatBordersToxicity ()
float GetStatBordersWater ()
PlayerStat< float > GetStatDiet ()
PlayerStat< float > GetStatEnergy ()
PlayerStat< float > GetStatHeatBuffer ()
PlayerStat< float > GetStatHeatComfort ()
EStatLevels GetStatLevel (float stat_value, float critical, float low, float normal, float high)
EStatLevels GetStatLevelBlood ()
float GetStatLevelBorders (float stat_value, float critical, float low, float normal, float high, float max)
EStatLevels GetStatLevelEnergy ()
EStatLevels GetStatLevelHealth ()
EStatLevels GetStatLevelToxicity ()
EStatLevels GetStatLevelWater ()
PlayerStat< float > GetStatSpecialty ()
PlayerStat< float > GetStatStamina ()
PlayerStat< float > GetStatToxicity ()
PlayerStat< float > GetStatTremor ()
PlayerStat< float > GetStatWater ()
PlayerStat< int > GetStatWet ()
PlayerStomach GetStomach ()
int GetStoreLoadVersion ()
override array< string > GetSuitableFinisherHitComponents ()
returns list of suitable finisher hit components (defined on base entity/entity type)
SymptomManager GetSymptomManager ()
float GetTotalAgentCount ()
TransferValues GetTransferValues ()
UndergroundHandlerClient GetUndergroundHandler ()
VirtualHud GetVirtualHud ()
float GetVisibilityCoef ()
int GetVoiceType ()
override WeaponManager GetWeaponManager ()
void GiveShock (float shock)
void HandleBrokenLegsSync ()
void HandleGlassesEffect ()
bool HandleRemoteItemManipulation (int userDataType, ParamsReadContext ctx)
bool HasBloodTypeVisible ()
bool HasBloodyHands ()
eBloodyHandsTypes HasBloodyHandsEx ()
bool HasDisease ()
bool HasHealings ()
bool HasStaminaRemaining ()
DEPRECATED.
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
override void HideClothing (ItemOptics optic, bool state)
void HideHairSelections (ItemBase item, bool state)
void ImmuneSystemTick (float value, float deltaT)
void IncreaseAntibioticsCount ()
void IncreaseDiseaseCount ()
void IncreaseHealingsCount ()
void Init ()
void InitEditor ()
void InitializeActions ()
override void InsertAgent (int agent, float count=1)
bool IsAntibioticsActive ()
bool IsBleeding ()
bool IsClimbing ()
bool IsClimbingLadder ()
bool IsCurrentCameraAimedAtGround ()
bool IsEmotePlaying ()
bool IsFacingTarget (Object target)
bool IsFalling ()
override bool IsFighting ()
override bool IsHoldingBreath ()
override bool IsIgnoredByConstruction ()
override bool IsInFBEmoteState ()
bool IsInProne ()
bool IsInRasedProne ()
bool IsInVehicle ()
override bool IsInventorySoftLocked ()
override bool IsInventoryVisible ()
bool IsInWater ()
bool IsItemInInventory (EntityAI entity)
bool IsItemsToDelete ()
bool IsJumpInProgress ()
bool IsLeaning ()
override bool IsLiftWeapon ()
bool IsMale ()
bool IsMapCallbackCancelInput ()
bool IsMapCallbackEndInput ()
bool IsMapOpen ()
bool IsNVGLowered ()
bool IsNVGWorking ()
bool IsOverloaded ()
bool IsPersistentFlag (PersistentFlag bit)
bool IsPlacingLocal ()
bool IsPlacingServer ()
override bool IsPlayer ()
bool IsPlayerDisconnected ()
bool IsPlayerLoaded ()
bool IsQBControl ()
bool IsQuickFishing ()
bool IsQuickRestrain ()
override bool IsRefresherSignalingViable ()
override bool IsRestrained ()
bool IsRestrainPrelocked ()
bool IsRestrainStarted ()
bool IsRolling ()
bool IsSprinting ()
bool IsStance (int stance, int stanceMask)
bool IsSurrendered ()
bool IsSwapBetweenHandsAndGroundLargeItem (notnull EntityAI item1, notnull EntityAI item2, out EntityAI item_hands, out EntityAI item_ground)
bool IsSwimming ()
bool IsTargetInActiveRefresherRange (EntityAI target)
override bool IsUnconscious ()
bool IsWearingSplint ()
override void JunctureDeleteItem (EntityAI item)
void KillUndergroundHandler ()
void LockHandsUntilItemHeld ()
void MapNavigationItemInPossession (EntityAI item)
void MapNavigationItemNotInPossession (EntityAI item)
void Message (string text, string style)
void MessageAction (string text)
void MessageFriendly (string text)
void MessageImportant (string text)
void MessageStatus (string text)
void MovingShock (float legHealth, float highShock, float midShock, float lowShock)
override bool NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent)
void OnBleedingBegin ()
void OnBleedingEnd ()
void OnBleedingSourceAdded ()
void OnBleedingSourceRemoved ()
void OnBleedingSourceRemovedEx (ItemBase item)
void OnCameraChanged (DayZPlayerCameraBase new_camera)
override void OnCommandClimbFinish ()
override void OnCommandClimbStart ()
override void OnCommandDeathStart ()
override void OnCommandFallFinish ()
override void OnCommandFallStart ()
void OnCommandHandlerTick (float delta_time, int pCurrentCommandID)
override void OnCommandLadderFinish ()
override void OnCommandLadderStart ()
override void OnCommandMelee2Finish ()
override void OnCommandMelee2Start ()
override void OnCommandMoveStart ()
override void OnCommandSwimFinish ()
override void OnCommandSwimStart ()
override void OnCommandVehicleFinish ()
override void OnCommandVehicleStart ()
void OnConnect ()
void OnDisconnect ()
void OnDrowningEnd ()
void OnDrowningStart ()
override void OnGameplayDataHandlerSync ()
void OnHoldBreathEnd ()
void OnHoldBreathExhausted ()
void OnHoldBreathStart ()
override bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnInventoryMenuClose ()
void OnInventoryMenuOpen ()
override void OnJumpEnd (int pLandType=0)
void OnJumpOutVehicleFinish (float carSpeed)
override void OnJumpStart ()
override void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
override void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
void OnPlayerLoaded ()
void OnPlayerReceiveFlashbangHitEnd ()
void OnPlayerReceiveFlashbangHitStart (bool visual)
override void OnPlayerRecievedHit ()
void OnQuickBarContinuousUseEnd (int slotClicked)
void OnQuickBarContinuousUseStart (int slotClicked)
void OnQuickbarSetEntityRequest (ParamsReadContext ctx)
void OnQuickBarSingleUse (int slotClicked)
void OnReconnect ()
void OnRestrainStart ()
override void OnRollFinish ()
override void OnRollStart (bool isToTheRight)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void OnScheduledTick (float deltaTime)
void OnSelectPlayer ()
void OnSpawnedFromConsole ()
override void OnStanceChange (int previousStance, int newStance)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
bool OnStoreLoadLifespan (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
void OnStoreSaveLifespan (ParamsWriteContext ctx)
override void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
override void OnThrowingModeChange (bool change_to_enabled)
void OnTick ()
void OnUnconsciousStart ()
void OnUnconsciousStop (int pCurrentCommandID)
void OnUnconsciousUpdate (float pDt, int last_command)
override void OnVariablesSynchronized ()
void OnVehicleSeatDriverEnter ()
void OnVehicleSeatDriverLeft ()
void OnVehicleSwitchSeat (int seatIndex)
void OnVoiceEvent (PlayerSoundEventBase voice_event)
void OnVoiceEventPlayback (PlayerSoundEventBase voice_event, AbstractWave callback, float playback_time)
called every cmd handler tick during a playback of PlayerSoundEvent, m_ProcessPlaybackEvent needs to be enabled on the PlayerSoundEvent
override bool PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only=true)
void PlacingCancelLocal ()
void PlacingCancelServer ()
void PlacingCompleteLocal ()
void PlacingCompleteServer ()
void PlacingStartLocal (ItemBase item)
void PlacingStartServer (ItemBase item)
void PlayAttachmentDropSound ()
void PlayerBase ()
override SoundOnVehicle PlaySound (string sound_name, float range, bool create_local=false)
override bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false)
override bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false, int param=0)
override bool PredictiveDropEntity (notnull EntityAI item)
override bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
override bool PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2)
override void PredictiveTakeEntityToHands (EntityAI item)
override bool PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot)
override bool PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item)
override bool PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col)
override bool PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
override bool PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst)
void PreloadDecayTexture ()
void PrintAgents ()
void ProcessADDModifier ()
void ProcessDrowning (float dT)
override void ProcessFeetDamageServer (int pUserInt)
void ProcessHandDamage (float delta_time, HumanMovementState pState)
void ProcessHoldBreath (float dT)
override void ProcessLiftWeapon ()
void QueueAddEffectWidget (array< int > effects)
void QueueAddGlassesEffect (int id)
void QueueRemoveEffectWidget (array< int > effects)
void QueueRemoveGlassesEffect (int id)
void QuickReloadWeapon (EntityAI weapon)
void RadialQuickBarCombine (int slotClicked)
void RadialQuickBarSingleUse (int slotClicked)
bool ReadLiftWeaponRequest (int userDataType, ParamsReadContext ctx)
void RefreshHandAnimationState (int delay=0)
void ReloadWeapon (EntityAI weapon, EntityAI magazine)
void RemoveAction (typename actionName)
void RemoveAction (typename actionName, out TInputActionMap InputActionMap)
void RemoveActiveNV (int type)
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
void RemoveAllItems ()
void RemoveQuickBarEntityShortcut (EntityAI entity)
void RequestHandAnimationStateRefresh ()
void RequestResetADSSync ()
override void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client=false)
override void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client=false, int param=0)
void RequestUnconsciousness (bool enable)
void ResetActionEndInput ()
void ResetActiveNV ()
bool ResetADSPlayerSync (int userDataType, ParamsReadContext ctx)
server only
void ResetConstructionActionData ()
void ResetPlayer (bool set_max)
override void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient=NULL)
void RunFightBlendTimer ()
bool Save ()
void SaveAreaPersistenceFlag (ParamsWriteContext ctx)
AbstractWave SaySoundSet (string name)
void SendLiftWeaponSync (bool state)
Client-side only.
override protected void SendSoundEvent (EPlayerSoundEventID id)
override protected void SendSoundEventEx (EPlayerSoundEventID id, int param=0)
void SetActionEndInput (ActionBase action)
void SetActions ()
void SetActions (out TInputActionMap InputActionMap)
void SetActionsRemoteTarget ()
void SetActionsRemoteTarget (out TInputActionMap InputActionMap)
void SetBleedingBits (int bits)
void SetBloodType (int blood_type)
void SetBloodTypeVisible (bool show)
void SetBloodyHands (bool show)
void SetBloodyHandsEx (eBloodyHandsTypes type)
void SetBloodyHandsPenalty ()
void SetBrokenLegs (int stateId)
void SetCheckMeleeItem (ItemBase item=null)
void SetContaminatedEffect (bool enable, int ppeIdx=-1, int aroundId=ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId=ParticleList.CONTAMINATED_AREA_GAS_TINY, bool partDynaUpdate=false, int newBirthRate=0)
void SetContaminatedEffectEx (bool enable, int ppeIdx=-1, int aroundId=ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId=ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset="", bool partDynaUpdate=false, int newBirthRate=0)
void SetCraftingRecipeID (int recipeID)
override void SetDeathDarknessLevel (float duration, float tick_time)
void SetDecayEffects (int effect=-1)
protected vector SetDefaultHitPosition (string pSelection)
void SetDrowning (bool enable)
void SetEnableQuickBarEntityShortcut (EntityAI entity, bool value)
void SetFirstRecipe ()
void SetFlagTendencyRaise (bool state)
DEPRECATED.
void SetHairLevelToHide (int level, bool state, bool was_debug=false)
Dynamic hair hiding.
void SetHitPPEEnabled (bool enabled)
void SetImmunityBoosted (bool boosted)
override void SetInventorySoftLock (bool status)
void SetInWater (bool pState)
water contact (driven by Environment)
void SetLastFirePoint (vector last_fire_point)
void SetLastFirePointIndex (int last_fire_point_index)
void SetLastFirePointRot (float last_fire_point_rot)
void SetLastMapInfo (float scale, vector pos)
void SetLastShavedSeconds (int last_shaved_seconds)
void SetLastUAMessage (string pMsg)
void SetLegHealth ()
void SetLifeSpanStateVisible (int show_state)
void SetLiftWeapon (int pJunctureID, ParamsReadContext ctx)
void SetLiquidTendencyDrain (bool state)
void SetLoadedQuickBarItemBind (EntityAI entity, int index)
void SetLocalProjectionOrientation (vector local_orientation)
void SetLocalProjectionPosition (vector local_position)
void SetMapClosingSyncSet (bool state)
void SetMapOpen (bool state)
void SetMixedSoundState (eMixedSoundStates state)
void SetModifiers (bool enable)
void SetNewCharName ()
void SetNextRecipe ()
void SetNVGLowered (bool state)
void SetNVGWorking (bool state)
Deprecated.
void SetPersistentFlag (PersistentFlag bit, bool enable)
void SetPlayerDisconnected (bool state)
void SetPlayerLoad (float load)
override void SetProcessUIWarning (bool state)
void SetPulseType (EPulseType pulse_type)
void SetQuickBarEntityShortcut (EntityAI entity, int index, bool force=false)
void SetQuickFishing (bool enable)
void SetQuickRestrain (bool enable)
void SetRestrained (bool is_restrained)
void SetRestrainPrelocked (bool restrain_prelock)
void SetRestrainStarted (bool restrain_started)
void SetShakesForced (int value)
void SetStamina (int value, int range)
void SetStaminaState (eStaminaState state)
void SetToDelete (ParamsReadContext pCtx)
void SetUnderground (EUndergroundPresence presence)
void SetVisibilityCoef (float pVisibility)
void ShavePlayer ()
void ShockRefill (float pDt)
void ShowUnconsciousScreen (bool show)
int SimplifyShock ()
override void SimulateDeath (bool state)
EntityAI SpawnAI (string object_name, vector pos)
void SpawnBreathVaporEffect ()
override void SpawnDamageDealtEffect ()
void SpawnDamageDealtEffect2 (Param param1=null, Param param2=null)
EntityAI SpawnEntityOnGroundOnCursorDir (string object_name, float distance)
override EntityAI SpawnEntityOnGroundPos (string object_name, vector pos)
void SpawnFlashbangEffect (PlayerBase player, bool visual)
void SpawnShockEffect (float intensity_max)
void SpreadAgents ()
void SpreadAgentsEx (float distance=3, float chance=0.25)
chance between [0..1] , distance in meters
void StaminaHUDNotifier (bool show)
override void SwitchItemSelectionTexture (EntityAI item, string slot_name)
void SwitchItemTypeAttach (EntityAI item, string slot)
void SwitchItemTypeDetach (EntityAI item, string slot)
override protected bool TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item)
override protected bool TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item)
override void TakeEntityToHandsImpl (InventoryMode mode, EntityAI item)
override protected bool TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item)
override protected bool TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
override protected bool TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item)
override protected bool TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item)
override protected bool TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
void TestSend ()
void ToggleHeatBufferVisibility (bool show)
void TogglePlacingLocal (ItemBase item=null)
bool TogglePlacingServer (int userDataType, ParamsReadContext ctx)
void TryHideItemInHands (bool hide, bool force=false)
tries to hide item in player's hands, some exceptions for various movement states
void UnsetMixedSoundState (eMixedSoundStates state)
void UpdateBrokenLegs (int stateId)
void UpdateCorpseState ()
void UpdateCorpseStateVisual ()
void UpdateDelete ()
void UpdateHairSelectionVisibility (bool was_debug=false)
void UpdateLighting ()
void UpdateMaskBreathWidget (notnull MaskBase mask, bool is_start=false)
void UpdatePlayerMeasures ()
void UpdateQuickBarEntityVisibility (EntityAI entity)
void UpdateQuickBarExtraSlots ()
void UpdateShoulderProxyVisibility (EntityAI item, string slot_name)
void UpdateTranslatedSelections (SelectionTranslation stt)
override void UpdateWeight (WeightUpdateType updateType=WeightUpdateType.FULL, float weightAdjustment=0)
void ~PlayerBase ()
Private Attributes
const int ACT_STORE_SAVE_VERSION = 4
const string CONTAMINATED_AREA_AMBIENT = "ContaminatedArea_SoundSet"
bool ItemToInventory
ref protected ActionManagerBase m_ActionManager
bool m_ActionQBControl
bool m_ActionsInitialize
protected ref array< int > m_ActiveNVTypes
int m_AddModifier = -1
PluginAdminLog m_AdminLog
ref PlayerAgentPool m_AgentPool
int m_Agents
protected bool m_AllowQuickFishing
protected bool m_AllowQuickRestrain
EffectSound m_AmbientContamination
ref Timer m_AnalyticsTimer
protected int m_AnimCommandStarting
int m_AntibioticsActive
ref array< ref Param2< EntityAI, int > > m_aQuickBarLoad
bool m_AreHandsLocked
int m_BleedingBits
ref BleedingSourcesManagerRemote m_BleedingManagerRemote
ref BleedingSourcesManagerServer m_BleedingManagerServer
int m_BleedingSourceCount
private int m_BloodType
int m_BreathVapour
bool m_BrokenLegsJunctureReceived
ref EffectSound m_BrokenLegSound
int m_BrokenLegState = eBrokenLegs.NO_BROKEN_LEGS
float m_CameraSwayModifier = 0.2
protected bool m_CanDisplayHitEffectPPE
bool m_CanPlayBrokenLegSound
float m_CargoLoad
Head_Default m_CharactersHead
protected ItemBase m_CheckMeleeItem
PlayerBase m_CheckPulseLastTarget
PluginConfigEmotesProfile m_ConfigEmotesProfile
ref ConstructionActionData m_ConstructionActionData
bool m_ContaminatedAreaEffectEnabled
bool m_CorpseProcessing
int m_CorpseState
protected int m_CorpseStateLocal
vector m_CraftingInitialPos
ref CraftingManager m_CraftingManager
DayZPlayerCameraBase m_CurrentCamera
float m_CurrentShock
ref DamageDealtEffect m_DamageDealtEffect
string m_DatabaseID
int m_DbgListSelection = 0
ref array< string > m_DbgOptions = {"jedna", "dva", "tri"}
float m_DbgSliderValue = 0.0
ref Timer m_DeathCheckTimer
ref Param1< float > m_DeathDarkeningParam
int m_DebugMonitorEnabled
ref DebugMonitorValues m_DebugMonitorValues
string m_DecayedTexture
vector m_DefaultHitPosition
vector m_DirectionToCursor
int m_DiseaseCount
protected float m_dT
ref EffectRadial m_EffectRadial
protected PlayerStat< int > m_StatWet protected PlayerStat< int > m_StatBloodType protected PlayerStat< float > m_StatDiet protected PlayerStat< float > m_StatStamina protected PlayerStat< float > m_StatSpecialty protected PlayerStat< float > m_StatHeatBuffer protected GameplayEffectWidgets_base m_EffectWidgets
effect widgets
ref EmoteManager m_EmoteManager
ref HiddenSelectionsData m_EmptyGloves
ref Environment m_Environment
private bool m_FlagRaisingTendency
ref FlashbangEffect m_FlashbangEffect
ref EffectParticle m_FliesEff
int m_FliesIndex
int m_ForceInjuryAnimMask
ActionUnfoldMapCB m_hac
private bool m_HasBloodTypeVisible
private int m_HasBloodyHandsVisible
protected bool m_HasHeatBuffer
ref HeatComfortAnimHandler m_HCAnimHandler
int m_HealingsCount
int m_HealthLevel
bool m_HideHairAnimated
ref Hologram m_HologramLocal
ref Hologram m_HologramServer
Hud m_Hud
bool m_ImmunityBoosted
ref InjuryAnimationHandler m_InjuryHandler
ref TInputActionMap m_InputActionMap
ref TInputActionMap m_InputActionMapAsTarget
ref TInputActionMap m_InputActionMapControled
ref InventoryActionHandler m_InventoryActionHandler
protected bool m_InventorySoftLocked
bool m_IsCraftingReady
bool m_IsDrowning
bool m_IsFighting = false
protected bool m_IsHoldingBreath
protected bool m_IsInWater
bool m_IsRestrained
bool m_IsRestrainPrelocked
bool m_IsRestrainStarted
bool m_IsVehicleSeatDriver
EntityAI m_Item1
EntityAI m_Item2
protected ref array< EntityAI > m_ItemsToDelete
vector m_LastFirePoint
int m_LastFirePointIndex
float m_LastFirePointRot
protected vector m_LastMapPos
protected float m_LastMapScale = -1.0
float m_LastPostFrameTickTime
private int m_LastShavedSeconds
float m_LastShockHitTime
float m_LastTick = -1
protected int m_LifespanLevelLocal
private int m_LifeSpanState
private bool m_LiquidTendencyDrain
int m_LocalBrokenState = eBrokenLegs.NO_BROKEN_LEGS
vector m_LocalProjectionOrientation = "0 0 0 "
vector m_LocalProjectionPosition = "0 0 0 "
protected int m_LocalRefreshAnimStateIdx
bool m_LoweredNVGHeadset
bool m_MapCloseRequestProcessed
protected bool m_MapClosingSyncSent
protected ref MapNavigationBehaviour m_MapNavigationBehaviour
bool m_MapOpen
protected bool m_MeleeDebug
melee stats
int m_MixedSoundStates
ref ModifiersManager m_ModifiersManager
private PluginLifespan m_ModuleLifespan
private PluginPlayerStatus m_ModulePlayerStatus
PluginRecipesManager m_ModuleRecipesManager
ref NotifiersManager m_NotifiersManager
float m_OriginalSlidePoseAngle
int m_PersistentFlags
protected bool m_PlayerDisconnectProcessed
protected bool m_PlayerLoaded
vector m_PlayerOldPos
ref PlayerSoundManagerClient m_PlayerSoundManagerClient
ref PlayerSoundManagerServer m_PlayerSoundManagerServer
ref PlayerStats m_PlayerStats
ref PlayerStomach m_PlayerStomach
protected PluginPresenceNotifier m_PresenceNotifier
protected ref array< int > m_ProcessAddEffectWidgets
protected ref array< int > m_ProcessAddGlassesEffects
protected ref array< int > m_ProcessRemoveEffectWidgets
protected ref array< int > m_ProcessRemoveGlassesEffects
protected bool m_ProcessUIWarning
EPulseType m_PulseType
ref protected QuickBarBase m_QuickBarBase
int m_QuickBarBonus = 0
bool m_QuickBarFT = false
bool m_QuickBarHold
float m_RecipeAnimLength
int m_RecipeID = -1
protected int m_RecipePick
ref array< int > m_Recipes
protected int m_RefreshAnimStateIdx
ref protected RandomGeneratorSyncManager m_RGSManager
ref SoundObjectBuilder m_SaySoundBuilder
string m_SaySoundLastSetName
ref SoundObject m_SaySoundObject
ref SoundParams m_SaySoundParams
protected int m_Shakes
protected int m_ShakesForced
ref ShockDealtEffect m_ShockDealtEffect
ref ShockHandler m_ShockHandler
int m_ShockSimplified
bool m_ShowDbgUI = true
ref SoftSkillsManager m_SoftSkillsManager
int m_SoundEvent
int m_SoundEventParam
bool m_SoundEventSent
ref EffectSound m_SoundFliesEffect
ref StaminaHandler m_StaminaHandler
ref Param3< float, float, bool > m_StaminaParam
int m_StaminaState
ref StanceIndicator m_StanceIndicator
protected PlayerStat< float > m_StatEnergy
protected PlayerStat< float > m_StatHeatComfort
protected PlayerStat< float > m_StatToxicity
protected PlayerStat< float > m_StatTremor
protected PlayerStat< float > m_StatWater
private int m_StoreLoadVersion
ref SymptomManager m_SymptomManager
int m_SyncedModifiers
int m_SyncedModifiersPrev
ref TransferValues m_TrasferValues
protected string m_UALastMessage
user actions last message
protected ref Timer m_UALastMessageTimer
ref Param2< int, int > m_UAParam
ref Param1< string > m_UAParamMessage
ref Param2< float, float > m_UAProgressParam
ref Param1< float > m_UnconParam
float m_UnconRefillModifier = 1
float m_UnconsciousEndTime = 0
float m_UnconsciousTime
float m_UnconsciousVignetteTarget = 2
protected ref UndergroundHandlerClient m_UndergroundHandler
EUndergroundPresence m_UndergroundPresence
ref VirtualHud m_VirtualHud
float m_VisibilityCoef
ref WeaponManager m_WeaponManager
bool m_WorkingNVGHeadset
const int OVERLOAD_LIMIT = 30000
const int SHAKE_LEVEL_MAX = 7
const int SIMPLIFIED_SHOCK_CAP = 63
const string SOUND_BREAK_LEG = "broken_leg_SoundSet"
Static Private Attributes
static bool DEBUG_INVENTORY_ACCESS = false
static ref array< string > m_BleedingSourcesLow
static ref array< string > m_BleedingSourcesUp
static protected Particle m_ContaminatedAroundPlayer
static protected Particle m_ContaminatedAroundPlayerTiny
static ref TStringArray m_QBarItems
static ref array< Man > m_ServerPlayers = new array<Man>
static ref array< Object > SPREAD_AGENTS_OBJECTS = new array<Object>
static ref array< CargoBase > SPREAD_AGENTS_PROXY_CARGOS = new array<CargoBase>
Detailed Description
Definition at line 1 of file playerbase.c.
Constructor & Destructor Documentation
~PlayerBase()
void ManBase::~PlayerBase () inline private
Definition at line 2273 of file playerbase.c.
    {
        if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            ClientData.RemovePlayerBase( this );
            SetContaminatedEffectEx(false);
        }
        SEffectManager.DestroyEffect(m_FliesEff);
//      ErrorEx("DbgFlies | StopSoundSet | exit 2 ",ErrorExSeverity.INFO);
        StopSoundSet(m_SoundFliesEffect);
    }
References SEffectManager::DestroyEffect(), GetGame(), ClientData::RemovePlayerBase(), and StopSoundSet().
Member Function Documentation
AddAction() [1/2]
void ManBase::AddAction (typename actionName) inline private
Definition at line 1325 of file playerbase.c.
    {
        AddAction(actionName, m_InputActionMap);
    }
References AddAction(), and m_InputActionMap.
AddAction() [2/2]
void ManBase::AddAction (typename actionName , out TInputActionMap InputActionMap) inline private
Definition at line 1304 of file playerbase.c.
    {
        ActionBase action = GetActionManager().GetAction(actionName);
        typename ai = action.GetInputType();
        if (!ai)
        {
            m_ActionsInitialize = false;
            return;
        }
        ref array<ActionBase_Basic> action_array = InputActionMap.Get( ai );
        if (!action_array)
        {
            action_array = new array<ActionBase_Basic>;
            InputActionMap.Insert(ai, action_array);
        }
        action_array.Insert(action);
    }
References ActionBase(), GetActionManager(), and m_ActionsInitialize.
AddActiveNV()
void ManBase::AddActiveNV (int type) inline private
Definition at line 8449 of file playerbase.c.
    {
        if ( !m_ActiveNVTypes || (GetGame().IsMultiplayer() && GetGame().IsServer()) )
        {
            #ifdef DEVELOPER
                Error("AddActiveNV | illegal server-side call!");
            #endif
            return;
        }
        if ( m_ActiveNVTypes.Find(type) == -1 ) //TODO - set instead?
            m_ActiveNVTypes.Insert(type);
    }
References Error(), and GetGame().
AddItemToDelete()
override void ManBase::AddItemToDelete (EntityAI item) inline private
Definition at line 7657 of file playerbase.c.
    {
        if (item)
        {
            item.SetPrepareToDelete();
            m_ItemsToDelete.Insert(item);
        }
    }
AddPlayerLoad()
void ManBase::AddPlayerLoad (float addedload) inline private
Definition at line 4554 of file playerbase.c.
    {
        float newload = GetPlayerLoad() + addedload;
        SetPlayerLoad(newload);
        // Do not need -> Log is in SetPlayerLoad
        //PrintString(ToString(this) + "'s load weight is " + ToString(m_CargoLoad) + " g.");
    }
AddToEnvironmentTemperature()
void ManBase::AddToEnvironmentTemperature (float pTemperature) inline private
DEPRECATED.
Definition at line 2256 of file playerbase.c.
{};
AdjustBandana()
void ManBase::AdjustBandana (EntityAI item, string slot_name) inline private
Definition at line 8505 of file playerbase.c.
    {
        if (Bandana_ColorBase.Cast(item))
        {
            if (slot_name == "Headgear")
            {
                item.SetSimpleHiddenSelectionState(0,1);
                item.SetSimpleHiddenSelectionState(1,0);
            }
            else if (slot_name == "Mask")
            {
                item.SetSimpleHiddenSelectionState(0,0);
                item.SetSimpleHiddenSelectionState(1,1);
            }
        }
    }
AfterStoreLoad()
override void ManBase::AfterStoreLoad () inline private
Definition at line 6769 of file playerbase.c.
    {
        GetHumanInventory().OnAfterStoreLoad();
        if (m_EmoteManager)
        {
            m_EmoteManager.AfterStoreLoad();
        }
        UpdateWeight();
        SetPlayerLoad(GetWeight());
    }
References UpdateWeight().
AnimCommandCheck()
bool ManBase::AnimCommandCheck (HumanMoveCommandID mask) inline private
Returns whether the specified movement command(s) are starting the next frame. Use caution when using this for anything player animation-related, some commands may require the movement state to be truly active (wait until next update)
Definition at line 4975 of file playerbase.c.
    {
        return m_AnimCommandStarting & mask;
    }
AntibioticsAttack()
void ManBase::AntibioticsAttack (float value) inline private
Definition at line 7367 of file playerbase.c.
    {
        m_AgentPool.AntibioticsAttack(value);
    }
ApplySplint()
void ManBase::ApplySplint () inline private
Definition at line 1828 of file playerbase.c.
    {
        float add_health_coef = 0.33;
        // The idea is to slightly increase health of broken limb so the player is still limping. Using more splints will help but each time less. 100% recovery can be achieved only through long term healing.
        if (GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
        {
            AddHealth("LeftLeg",    "Health",   ( GetMaxHealth("LeftLeg", "Health")  - GetHealth("LeftLeg", "Health")  ) * add_health_coef  );
            AddHealth("RightLeg",   "Health",   ( GetMaxHealth("RightLeg", "Health") - GetHealth("RightLeg", "Health") ) * add_health_coef  );
            AddHealth("RightFoot",  "Health",   ( GetMaxHealth("RightFoot", "Health") - GetHealth("RightFoot", "Health") ) * add_health_coef    );
            AddHealth("LeftFoot",   "Health",   ( GetMaxHealth("LeftFoot", "Health") - GetHealth("LeftFoot", "Health") ) * add_health_coef  );
        }
    }
References AddHealth(), GetHealth(), and GetMaxHealth().
BreakLegSound()
void ManBase::BreakLegSound () inline private
Definition at line 3322 of file playerbase.c.
    {
        PlaySoundSet(m_BrokenLegSound, SOUND_BREAK_LEG, 0.1, 0.1);
    }
References PlaySoundSet().
BrokenLegForceProne()
void ManBase::BrokenLegForceProne (bool forceOverride = false) inline private
Definition at line 3326 of file playerbase.c.
    {
        if (!IsInWater() && !IsSwimming() && !IsClimbingLadder() && !IsInVehicle() && !IsClimbing() && DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_PRONE))
        {
            if (m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE && m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            {
                EntityAI attachment;
                Class.CastTo(attachment, GetItemOnSlot("Splint_Right"));
                if ( attachment && attachment.GetType() == "Splint_Applied" )
                {
                    attachment.Delete();
                }
                m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_INITIAL_SHOCK);
                m_ShockHandler.CheckValue(true);
                if ( m_ShockHandler.GetCurrentShock() >= 25 ) //Prevent conflict with unconsciousness by not forcing prone when going uncon (25 shock or less left)
                {
                    //calcels user action
                    HumanCommandActionCallback cmd = GetCommand_Action();
                    if(cmd)
                    {
                        cmd.Cancel();
                    }
                    StopHandEvent();
                    //Get command move and verify not null
                    HumanCommandMove hcm = StartCommand_Move();//not sure why this is here
                    hcm = GetCommand_Move();
                    if (hcm)
                    {
                        hcm.ForceStance(DayZPlayerConstants.STANCEIDX_PRONE);
                    }
                }
            }
        }
    }
References PlayerConstants::BROKEN_LEGS_INITIAL_SHOCK, Class::CastTo(), HumanCommandMove::ForceStance(), GetCommand_Action(), GetCommand_Move(), IsInWater(), m_MovementState, DayZPlayerUtils::PlayerCanChangeStance(), StartCommand_Move(), and StopHandEvent().
BrokenLegWalkShock()
void ManBase::BrokenLegWalkShock () inline private
Definition at line 3367 of file playerbase.c.
    {
        //No need to pursue here if player is prone as the following logic is not applied
        if ( m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE && m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_RAISEDPRONE )
        {
            float avgLegHealth = GetHealth("RightLeg","") + GetHealth("LeftLeg","") + GetHealth("RightFoot","") + GetHealth("LeftFoot","");
            avgLegHealth *= 0.25; //divide by 4 to make the average leg health;
            if (IsSwimming())
            {
                //swimming other than forward is not detectable in script other than through velocity check
                vector v;
                PhysicsGetVelocity(v);
                if(v.LengthSq() > 0)
                {
                    m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_SHOCK_SWIM);
                }
            }
            else if (m_MovementState.m_iMovement != 0)
            {
                if ( IsClimbingLadder() )
                {
                    MovingShock(avgLegHealth, PlayerConstants.BROKEN_LEGS_HIGH_SHOCK_WALK, PlayerConstants.BROKEN_LEGS_MID_SHOCK_WALK, PlayerConstants.BROKEN_LEGS_LOW_SHOCK_WALK);
                }
                else if( m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
                {
                    if ( m_MovementState.m_iMovement > 1)//only jog and faster
                    {
                        MovingShock(avgLegHealth, PlayerConstants.BROKEN_LEGS_HIGH_SHOCK_WALK, PlayerConstants.BROKEN_LEGS_MID_SHOCK_WALK, PlayerConstants.BROKEN_LEGS_LOW_SHOCK_WALK);
                    }
                }
                else if( m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
                {
                    //any speed other than idle
                    MovingShock(avgLegHealth, PlayerConstants.BROKEN_LEGS_HIGH_SHOCK_WALK * PlayerConstants.BROKEN_CROUCH_MODIFIER, PlayerConstants.BROKEN_LEGS_MID_SHOCK_WALK * PlayerConstants.BROKEN_CROUCH_MODIFIER, PlayerConstants.BROKEN_LEGS_LOW_SHOCK_WALK * PlayerConstants.BROKEN_CROUCH_MODIFIER);
                }
            }
            else
            {
                //Here apply shock if player is standing or crouched and STANDING STILL
                m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_STAND_SHOCK);
            }
            m_ShockHandler.CheckValue(true);
        }
    }
References PlayerConstants::BROKEN_CROUCH_MODIFIER, PlayerConstants::BROKEN_LEGS_HIGH_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_LOW_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_MID_SHOCK_WALK, PlayerConstants::BROKEN_LEGS_SHOCK_SWIM, PlayerConstants::BROKEN_LEGS_STAND_SHOCK, GetHealth(), vector::LengthSq(), m_MovementState, and PhysicsGetVelocity().
CalculateVisibilityForAI()
void ManBase::CalculateVisibilityForAI () inline private
Definition at line 4637 of file playerbase.c.
    {
        const int VISIBILITY_SLOTS_COUNT = 10;
        int attcount = GetInventory().AttachmentCount();
        float sumVisibility = 0;
        float countVisibility = 0;
        float visibilityMean = 0;
        if (attcount > 0)
        {
            for (int att = 0; att < attcount; att++)
            {
                EntityAI attachment = GetInventory().GetAttachmentFromIndex(att);
                if ( attachment.IsClothing() )
                {
                    ClothingBase clothing;
                    Class.CastTo(clothing, attachment);
                    sumVisibility += clothing.GetItemVisibility();
                    countVisibility++;
                }
            }
            visibilityMean = (sumVisibility + (VISIBILITY_SLOTS_COUNT - countVisibility)) / VISIBILITY_SLOTS_COUNT;
            SetVisibilityCoef(visibilityMean);
        }
        else
        {
            visibilityMean = 1;
            SetVisibilityCoef(visibilityMean);
        }
    }
References Class::CastTo().
CanBeRestrained()
bool ManBase::CanBeRestrained () inline private
Definition at line 1570 of file playerbase.c.
    {
        if( IsInVehicle() || IsRaised() || IsSwimming() || IsClimbing() || IsClimbingLadder() || IsRestrained() || !GetWeaponManager() || GetWeaponManager().IsRunning() || !GetActionManager() || GetActionManager().GetRunningAction() != null || IsMapOpen() )
        {
            return false;
        }
        if( GetThrowing() && GetThrowing().IsThrowingModeEnabled() )
        {
            return false;
        }
        return true;
    }
References GetActionManager(), GetRunningAction(), GetThrowing(), GetWeaponManager(), IsRaised(), IsRestrained(), and IsRunning().
CanBeTargetedByAI()
override bool ManBase::CanBeTargetedByAI (EntityAI ai) inline private
Definition at line 3219 of file playerbase.c.
    {
        #ifdef DEVELOPER
        if (!m_CanBeTargetedDebug)
        {
            return false;
        }
        #endif
        return super.CanBeTargetedByAI( ai ) && !IsUnconscious() && !IsInVehicle();
    }
CanChangeStance()
override bool ManBase::CanChangeStance (int previousStance, int newStance) inline private
Definition at line 3722 of file playerbase.c.
    {
        return !IsRolling() && !GetThrowing().IsThrowingAnimationPlaying();
    }
References GetThrowing(), and DayZPlayerImplementThrowing::IsThrowingAnimationPlaying().
CanClimb()
override bool ManBase::CanClimb (int climbType, SHumanCommandClimbResult climbRes) inline private
Definition at line 4009 of file playerbase.c.
    {
        if (GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
        {
            return false;
        }
        if ( climbType == 1 && !CanConsumeStamina(EStaminaConsumers.VAULT) )
            return false;
        if ( climbType == 2 && ( !CanConsumeStamina(EStaminaConsumers.CLIMB) || GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS ) )
            return false;
        if ( climbType > 0 && m_InjuryHandler && m_InjuryHandler.GetInjuryAnimValue() >= InjuryAnimValues.LVL3)
            return false;
        return super.CanClimb( climbType,climbRes );
    }
References CanConsumeStamina(), and InjuryAnimValues::LVL3.
CanConsumeStamina()
override bool ManBase::CanConsumeStamina (EStaminaConsumers consumer) inline private
Definition at line 3976 of file playerbase.c.
    {
        if(!GetStaminaHandler()) return false;
        bool val = (GetStaminaHandler().HasEnoughStaminaFor(consumer) /*&& !IsOverloaded()*/ && !IsRestrained() && !IsInFBEmoteState());
        if (!val)
            StaminaHUDNotifier( false );
        return val;
    }
References IsInFBEmoteState(), and IsRestrained().
CanDeleteItems()
bool ManBase::CanDeleteItems () inline private
Definition at line 7666 of file playerbase.c.
    {
        return !(IsEmotePlaying() || GetThrowing().IsThrowingAnimationPlaying() || GetDayZPlayerInventory().IsProcessing() || (GetActionManager() && GetActionManager().GetRunningAction()));
    }
References GetActionManager(), GetDayZPlayerInventory(), GetThrowing(), IsEmotePlaying(), and DayZPlayerImplementThrowing::IsThrowingAnimationPlaying().
CanDropEntity()
override bool ManBase::CanDropEntity (notnull EntityAI item) inline private
Definition at line 567 of file playerbase.c.
    {
        if( GetInventory().HasInventoryReservation( item, null ) )
        {
            return false;
        }
        if( IsRestrained() )
        {
            if( GetHumanInventory().GetEntityInHands() == item )
                return false;
        }
        return true;
    }
References HasInventoryReservation(), and IsRestrained().
CanEatAndDrink()
bool ManBase::CanEatAndDrink () inline private
Definition at line 7389 of file playerbase.c.
    {
        ItemBase mask = ItemBase.Cast(GetInventory().FindAttachment(InventorySlots.MASK));
        return (!mask || (mask && mask.AllowFoodConsumption()));
    }
References FindAttachment().
CanJump()
override bool ManBase::CanJump () inline private
disables jump when player is significantly injured
disables jump when player is under object
Definition at line 4028 of file playerbase.c.
    {
        if (GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
        {
            return false;
        }
        if (!CanConsumeStamina(EStaminaConsumers.JUMP))
            return false;
        if ( m_InjuryHandler && m_InjuryHandler.GetInjuryAnimValue() >= InjuryAnimValues.LVL3 )
            return false;
        if (IsInFBEmoteState() || m_EmoteManager.m_MenuEmote)
        {
            return false;
        }
        /*if (IsUnderRoofJumpCheck())
        {
            return false;
        }*/
        return super.CanJump();
    }
References CanConsumeStamina(), IsInFBEmoteState(), and InjuryAnimValues::LVL3.
CanManipulateInventory()
bool ManBase::CanManipulateInventory () inline private
Definition at line 1621 of file playerbase.c.
    {
        if( IsControlledPlayer() )
        {
            return !IsRestrained() && !IsRestrainPrelocked();
        }
        return true;
    }
References IsRestrained().
CanPickupHeavyItem()
override bool ManBase::CanPickupHeavyItem (notnull EntityAI item) inline private
Definition at line 3443 of file playerbase.c.
    {
        if (item.IsHeavyBehaviour() && (GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS || GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS_SPLINT))
            return false;
        return super.CanPickupHeavyItem(item);
    }
CanReceiveItemIntoCargo()
override bool ManBase::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 1640 of file playerbase.c.
    {
        return super.CanReceiveItemIntoCargo(item);
    }
CanReceiveItemIntoHands()
override bool ManBase::CanReceiveItemIntoHands (EntityAI item_to_hands) inline private
Definition at line 1678 of file playerbase.c.
    {
        if ( IsInVehicle() )
            return false;
        if ( !CanPickupHeavyItem(item_to_hands) )
            return false;
        return super.CanReceiveItemIntoHands(item_to_hands);
    }
References CanPickupHeavyItem().
CanRedirectToWeaponManager()
bool ManBase::CanRedirectToWeaponManager (notnull EntityAI item, out bool isActionPossible) inline private
Definition at line 7978 of file playerbase.c.
    {
        isActionPossible = false;
        Magazine mag = Magazine.Cast(item);
        Weapon_Base wpn = Weapon_Base.Cast(item.GetHierarchyParent());
        if (mag && wpn)
        {
            if (GetWeaponManager().CanDetachMagazine(wpn, mag))
            {
                //Print("[inv] PlayerBase.CanRedirectToWeaponManager OK, can detach mag=" + mag + " from wpn=" + wpn);
                isActionPossible = true;
            }
            else
            {
                //Print("[inv] PlayerBase.CanRedirectToWeaponManager cannot detach mag=" + mag + " from wpn=" + wpn);
            }
            return true;
        }
        return false;
    }
References GetWeaponManager().
CanReleaseAttachment()
override bool ManBase::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 1630 of file playerbase.c.
    {
        return super.CanReleaseAttachment(attachment);
    }
CanReleaseCargo()
override bool ManBase::CanReleaseCargo (EntityAI cargo) inline private
Definition at line 1635 of file playerbase.c.
    {
        return super.CanReleaseCargo(cargo);
    }
CanReleaseFromHands()
override bool ManBase::CanReleaseFromHands (EntityAI handheld) inline private
Definition at line 1694 of file playerbase.c.
    {
        return super.CanReleaseFromHands(handheld);
    }
CanRoll()
override bool ManBase::CanRoll () inline private
Definition at line 3741 of file playerbase.c.
    {
        if (!CanConsumeStamina(EStaminaConsumers.ROLL))
            return false;
        if (IsInFBEmoteState() || m_EmoteManager.m_MenuEmote)
        {
            return false;
        }
        return IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDPRONE) && GetCommand_Move() && !GetCommand_Move().IsOnBack();
    }
References CanConsumeStamina(), GetCommand_Move(), IsInFBEmoteState(), HumanCommandMove::IsOnBack(), and IsPlayerInStance().
CanSaveItemInHands()
override bool ManBase::CanSaveItemInHands (EntityAI item_in_hands) inline private
Definition at line 1689 of file playerbase.c.
    {
        return super.CanSaveItemInHands(item_in_hands);
    }
CanShave()
bool ManBase::CanShave () inline private
Definition at line 6366 of file playerbase.c.
    {
        if ( GetLifeSpanState() )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
CanSpawnBreathVaporEffect()
bool ManBase::CanSpawnBreathVaporEffect () inline private
Definition at line 6414 of file playerbase.c.
    {
        if( !ToDelete() && IsAlive() && !IsSwimming() && !m_IsDrowning )
        {
            return true;
        }
        return false;
    }
References IsAlive(), and ToDelete().
CanSprint()
bool ManBase::CanSprint () inline private
Definition at line 4880 of file playerbase.c.
    {
        ItemBase item = GetItemInHands();
        if ( IsRaised() || (item && item.IsHeavyBehaviour()) )
        {
            return false;
        }
        if (GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
        {
            return false;
        }
        return true;
    }
References IsRaised().
CanStartConsumingStamina()
override bool ManBase::CanStartConsumingStamina (EStaminaConsumers consumer) inline private
Definition at line 3988 of file playerbase.c.
    {
        if(!GetStaminaHandler()) return false;
        bool val = (GetStaminaHandler().HasEnoughStaminaToStart(consumer) && !IsRestrained() && !IsInFBEmoteState());
        if (!val)
            StaminaHUDNotifier( false );
        return val;
    }
References IsInFBEmoteState(), and IsRestrained().
CanSwapItemInCargo()
override bool ManBase::CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline private
Definition at line 1645 of file playerbase.c.
    {
        return super.CanSwapItemInCargo(child_entity, new_entity);
    }
CheckAndExecuteStackSplit()
bool ManBase::CheckAndExecuteStackSplit (FindInventoryLocationType flags, notnull EntityAI item, notnull EntityAI target) inline private
Definition at line 8735 of file playerbase.c.
    {
        float stackable = item.GetTargetQuantityMax();
        if ( !(stackable == 0 || stackable >= item.GetQuantity()) )
        {
            InventoryLocation il = new InventoryLocation;
            if ( target && target.GetInventory().FindFreeLocationFor( item, flags, il ) )
            {
                ItemBase itemB;
                if ( CastTo(itemB, item) )
                {
                    itemB.SplitIntoStackMaxToInventoryLocationClient( il );
                    return true;
                }
            }
        }
        return false;
    }
CheckAndExecuteStackSplitToInventoryLocation()
bool ManBase::CheckAndExecuteStackSplitToInventoryLocation (InventoryLocation il, notnull EntityAI item) inline private
Definition at line 8754 of file playerbase.c.
    {
        float stackable = item.GetTargetQuantityMax();
        if ( !(stackable == 0 || stackable >= item.GetQuantity()) )
        {
            ItemBase itemB;
            if ( CastTo(itemB, item) )
            {
                itemB.SplitIntoStackMaxToInventoryLocationClient( il );
                return true;
            }
        }
        return false;
    }
CheckAnimationOverrides()
override void ManBase::CheckAnimationOverrides () inline private
Definition at line 7959 of file playerbase.c.
    {
        //FB gesture slideposeangle override
        if (IsInFBEmoteState() && IsControlledPlayer() && IsPlayerSelected())
        {
            OverrideSlidePoseAngle(Math.PI2);
        }
        else if (!IsInFBEmoteState() && IsControlledPlayer() && IsPlayerSelected())
        {
            OverrideSlidePoseAngle(m_OriginalSlidePoseAngle);
        }
        //+add more, if needed
    }
References IsInFBEmoteState(), IsPlayerSelected(), OverrideSlidePoseAngle(), and Math::PI2.
CheckDeath()
void ManBase::CheckDeath () inline private
Definition at line 6552 of file playerbase.c.
    {
        if (IsPlayerSelected() && !IsAlive())
        {
            SimulateDeath(true);
            m_DeathCheckTimer.Stop();
        }
    }
References IsAlive(), IsPlayerSelected(), and SimulateDeath().
CheckForBurlap()
void ManBase::CheckForBurlap () inline private
Definition at line 5726 of file playerbase.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            BurlapSackCover attachment;
            Class.CastTo(attachment, GetInventory().FindAttachment(InventorySlots.HEADGEAR));
            PPERequester_BurlapSackEffects req;
            if (Class.CastTo(req,PPERequesterBank.GetRequester(PPERequesterBank.REQ_BURLAPSACK)))
            {
                if ( attachment )
                {
                    req.Start();
                }
                else if (req.IsRequesterRunning())
                {
                    PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop();
                }
            }
        }
    }
References Class::CastTo(), FindAttachment(), and GetInstanceType().
CheckForGag()
void ManBase::CheckForGag () inline private
Definition at line 5748 of file playerbase.c.
    {
        Clothing item;
        Class.CastTo(item, GetInventory().FindAttachment(InventorySlots.MASK));
        if ( !item )
        {
            Class.CastTo(item, GetInventory().FindAttachment(InventorySlots.HEADGEAR));
        }
        if ( item && item.IsObstructingVoice() )
        {
            item.MutePlayer(this,true);
        }
        else
        {
            if (( GetGame().IsServer() && GetGame().IsMultiplayer() ) || ( GetGame().GetPlayer() == this ))
            {
                GetGame().SetVoiceEffect(this, VoiceEffectMumbling, false);
                GetGame().SetVoiceEffect(this, VoiceEffectObstruction, false);
            }
        }
    }
References Class::CastTo(), FindAttachment(), GetGame(), GetPlayer(), Clothing::IsObstructingVoice(), and CGame::SetVoiceEffect().
CheckHairClippingOnCharacterLoad()
void ManBase::CheckHairClippingOnCharacterLoad () inline private
helper method for re-checking hairhiding on character load
Definition at line 8401 of file playerbase.c.
    {
        ItemBase headgear = ItemBase.Cast(GetInventory().FindAttachment(InventorySlots.HEADGEAR));
        ItemBase mask = ItemBase.Cast(GetInventory().FindAttachment(InventorySlots.MASK));
        HideHairSelections(headgear,true);
        HideHairSelections(mask,true);
    }
References FindAttachment().
CheckLiftWeapon()
override void ManBase::CheckLiftWeapon () inline private
Definition at line 7814 of file playerbase.c.
    {
        // lift weapon check
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT /*GetGame().IsClient()*/)
        {
            Weapon_Base weap;
            if ( Weapon_Base.CastTo(weap, GetItemInHands()) )
            {
                bool limited = weap.LiftWeaponCheck(this);
                if (limited && !m_LiftWeapon_player)
                    SendLiftWeaponSync(true);
                else if (!limited && m_LiftWeapon_player)
                    SendLiftWeaponSync(false);
            }
            else if (m_LiftWeapon_player)
            {
                SendLiftWeaponSync(false);
            }
        }
    }
References GetInstanceType(), and m_LiftWeapon_player.
CheckMeleeItemDamage()
bool ManBase::CheckMeleeItemDamage (ItemBase item) inline private
Definition at line 4995 of file playerbase.c.
    {
        //on-hit drop of melee weapons
        //bayonets & buttstocks
        if (item && item.GetHierarchyParent() && item.GetHierarchyParent().IsWeapon() && item.IsRuined()/*&& item.FindAttachmentBySlotName()*/)
        {
            PlayAttachmentDropSound();
            return DropItem(item);
        }
        //handheld items themselves
        if (item && item == GetItemInHands() && item.IsRuined())
        {
            return PredictiveDropEntity(item);
        }
        return false;
    }
CheckSendSoundEvent()
void ManBase::CheckSendSoundEvent () inline private
Definition at line 7065 of file playerbase.c.
    {
        if( m_SoundEvent!= 0 && !m_SoundEventSent )
        {
            m_SoundEventSent = true;
        }
    }
CheckSoundEvent()
void ManBase::CheckSoundEvent () inline private
Definition at line 7234 of file playerbase.c.
    {
        if(m_SoundEvent != 0)
        {
            PlaySoundEventEx(m_SoundEvent, false, true,m_SoundEventParam);
            m_SoundEvent = 0;
            m_SoundEventParam = 0;
        }
    }
References PlaySoundEventEx().
CheckZeroSoundEvent()
void ManBase::CheckZeroSoundEvent () inline private
Definition at line 7054 of file playerbase.c.
    {
        if( m_SoundEvent != 0 && m_SoundEventSent )
        {
            m_SoundEvent = 0;
            m_SoundEventParam = 0;
            m_SoundEventSent = false;
            SetSynchDirty();
        }
    }
ClearInventory()
void ManBase::ClearInventory () inline private
/brief Delete all items in inventory
Returns
void
PlayerBase player = GetGame().GetPlayer();
player.ClearInventory();
Definition at line 6304 of file playerbase.c.
    {
        if ( (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer()) && GetInventory() )
        {
            GameInventory inv = PlayerBase.Cast(this).GetInventory();
            ref array<EntityAI> items = new array<EntityAI>;
            inv.EnumerateInventory(InventoryTraversalType.INORDER, items);
            for(int i = 0; i < items.Count(); i++)
            {
                ItemBase item = ItemBase.Cast(items.Get(i));
                if(item && !item.IsPlayer())
                {
                    GetGame().ObjectDelete(item);
                }
            }
            ItemBase item_in_hands = ItemBase.Cast( GetHumanInventory().GetEntityInHands() );
            if ( item_in_hands )
            {
                LocalDestroyEntityInHands();
            }
        }
    }
References GetGame(), GetInstanceType(), and CGame::ObjectDelete().
ClearLastUAMessage()
protected void ManBase::ClearLastUAMessage () inline private
Definition at line 7524 of file playerbase.c.
    {
        if( m_UALastMessageTimer.IsRunning() )
        {
            m_UALastMessageTimer.Stop();
        }
        m_UALastMessage = "";
    }
CloseInventoryMenu()
void ManBase::CloseInventoryMenu () inline private
Definition at line 6279 of file playerbase.c.
    {
        if( !GetGame().IsDedicatedServer() )
        {
#ifndef NO_GUI
            UIScriptedMenu menu = GetGame().GetUIManager().GetMenu();
            if( menu && ( menu.GetID() == MENU_INVENTORY || menu.GetID() == MENU_INSPECT ) )
            {
                GetGame().GetUIManager().CloseAll();
                GetGame().GetMission().RemoveActiveInputExcludes({"inventory"},false);
                GetGame().GetMission().RemoveActiveInputRestriction(EInputRestrictors.INVENTORY);
            }
#endif
        }
    }
References UIManager::CloseAll(), GetGame(), UIManager::GetMenu(), CGame::GetMission(), CGame::GetUIManager(), MENU_INSPECT, MENU_INVENTORY, Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
CloseMap()
void ManBase::CloseMap () inline private
DEPRECATED; terminates map animation callback and re-enables controls.
Definition at line 2883 of file playerbase.c.
    {
        CloseMapEx(false);
    }
CloseMapEx()
void ManBase::CloseMapEx (bool cancelled) inline private
Definition at line 2888 of file playerbase.c.
    {
        if (m_hac && !m_MapClosingSyncSent)
        {
            ScriptInputUserData ctx = new ScriptInputUserData;
            if ( ctx.CanStoreInputUserData() )
            {
                int command_ID = DayZPlayerConstants.CMD_ACTIONINT_END;
                if ( cancelled )
                {
                    command_ID = DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT;
                }
                if ( GetGame().IsMultiplayer() && GetGame().IsClient() )
                {
                    ActionManagerClient mngr_client;
                    CastTo(mngr_client, GetActionManager());
                    if ( cancelled )
                    {
                        mngr_client.RequestInterruptAction();
                    }
                    else
                    {
                        mngr_client.RequestEndAction();
                    }
                    GetGame().GetMission().RemoveActiveInputExcludes({"map"});
                    GetGame().GetMission().RemoveActiveInputRestriction(EInputRestrictors.MAP);
                }
                else if ( !GetGame().IsMultiplayer() )
                {
                    m_hac.InternalCommand(command_ID);
                }
                SetMapClosingSyncSet(true);
            }
        }
        if (!GetGame().IsDedicatedServer())
        {
            if (GetGame().GetUIManager().IsMenuOpen(MENU_MAP))
            {
                GetGame().GetUIManager().FindMenu(MENU_MAP).Close();
                if (m_Hud)
                {
                    m_Hud.ShowHudPlayer(true);
                    m_Hud.ShowQuickbarPlayer(true);
                }
                GetGame().GetMission().RemoveActiveInputExcludes({"map"});
                GetGame().GetMission().RemoveActiveInputRestriction(EInputRestrictors.MAP);
            }
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), UIManager::FindMenu(), GetActionManager(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), m_Hud, MENU_MAP, Mission::RemoveActiveInputExcludes(), Mission::RemoveActiveInputRestriction(), ActionManagerClient::RequestEndAction(), ActionManagerClient::RequestInterruptAction(), Hud::ShowHudPlayer(), and Hud::ShowQuickbarPlayer().
CommandHandler()
override void ManBase::CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
SPRINT: enable/disable - based on stamina; disable also when raised
Definition at line 2629 of file playerbase.c.
    {
        // lower implement
        super.CommandHandler(pDt,pCurrentCommandID,pCurrentCommandFinished);
        //PrintString("pCurrentCommandID="+pCurrentCommandID.ToString());
        //PrintString(GetActionManager().GetRunningAction().ToString());
        m_dT = pDt;
        CheckZeroSoundEvent();
        CheckSendSoundEvent();
        ProcessADDModifier();
        if(m_BrokenLegsJunctureReceived)//was there a change in broken legs state ?
        {
            m_BrokenLegsJunctureReceived = false;
            bool initial = m_BrokenLegState < 0;//negative values indicate initial activation
            if ( GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS )
            {
                DropHeavyItem();
                if (initial)
                {
                    BrokenLegForceProne();
                }
            }
        }
        GetDayZPlayerInventory().HandleInventory(pDt);
        if (m_IsFireWeaponRaised)
        {
            ProcessHoldBreath(pDt);
        }
        ActionManagerBase       mngr = GetActionManager();
        HumanInputController hic = GetInputController();
        if (m_AreHandsLocked && GetHumanInventory().GetEntityInHands())
        {
            m_AreHandsLocked = false;
        }
        // freelook camera memory for weapon raycast
        if (hic.CameraIsFreeLook() && m_DirectionToCursor == vector.Zero)
        {
            m_DirectionToCursor = GetGame().GetCurrentCameraDirection();
        }
        else if (!hic.CameraIsFreeLook() && m_DirectionToCursor != vector.Zero)
        {
            m_DirectionToCursor = vector.Zero;
        }
        if ( m_WeaponManager )
        {
            m_WeaponManager.Update(pDt);
        }
        if ( m_EmoteManager && IsPlayerSelected() )
        {
            m_EmoteManager.Update(pDt);
            //Print("selected! " + IsPlayerSelected());
        }
        if ( m_RGSManager )
        {
             m_RGSManager.Update();
        }
/*      if(m_VehicleManager)
        {
            m_VehicleManager.Update(pDt);
        }*/
        if ( m_StanceIndicator )
        {
            m_StanceIndicator.Update();
        }
        if ( m_StaminaHandler )
        {
            m_StaminaHandler.Update(pDt, pCurrentCommandID);
        }
        if ( m_InjuryHandler )
        {
            m_InjuryHandler.Update(pDt);
        }
        if ( m_HCAnimHandler )
        {
            m_HCAnimHandler.Update(pDt, m_MovementState);
        }
        if ( m_ShockHandler )
        {
            m_ShockHandler.Update(pDt);
        }
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            GetPlayerSoundManagerServer().Update();
            ShockRefill(pDt);
            FreezeCheck();
            if ( m_Environment )
            {
                m_Environment.Update(pDt);
            }
        }
        GetHumanInventory().Update(pDt);
        if (m_IsDrowning)
        {
            ProcessDrowning(pDt);
        }
        UpdateDelete();
        //PrintString(pCurrentCommandID.ToString());
        //PrintString(m_IsUnconscious.ToString());
        //PrintString("currentCommand:" +pCurrentCommandID.ToString());
        HandleDamageHit(pCurrentCommandID);
        if (mngr && hic)
        {
            mngr.Update(pCurrentCommandID);
            //PrintString(m_ShouldBeUnconscious.ToString());
            if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
            {
                if ( !m_UnconsciousDebug )
                {
                    OnUnconsciousUpdate(pDt, m_LastCommandBeforeUnconscious );
                    if ( !m_IsUnconscious )
                    {
                        m_IsUnconscious = true;
                        OnUnconsciousStart();
                    }
                    if ( !m_ShouldBeUnconscious && m_UnconsciousTime > 2 )//m_UnconsciousTime > x   -> protection for a player being broken when attempting to wake him up too early into unconsciousness
                    {
                        HumanCommandUnconscious hcu = GetCommand_Unconscious();
                        if (hcu)
{
                            if (m_LastCommandBeforeUnconscious == DayZPlayerConstants.COMMANDID_VEHICLE)
                                hcu.WakeUp();
                            else
                                hcu.WakeUp(DayZPlayerConstants.STANCEIDX_PRONE);
                        }
                    }
                }
            }
            else
            {
                if (m_ShouldBeUnconscious && pCurrentCommandID != DayZPlayerConstants.COMMANDID_UNCONSCIOUS && pCurrentCommandID != DayZPlayerConstants.COMMANDID_DEATH && pCurrentCommandID != DayZPlayerConstants.COMMANDID_FALL && pCurrentCommandID != DayZPlayerConstants.COMMANDID_MOD_DAMAGE && pCurrentCommandID != DayZPlayerConstants.COMMANDID_DAMAGE)
                {
                    m_LastCommandBeforeUnconscious = pCurrentCommandID;
                    HumanCommandVehicle vehicleCommand = GetCommand_Vehicle();
                    if ( vehicleCommand )
                    {
                        if (vehicleCommand.ShouldBeKnockedOut())
{
                            m_TransportCache = null;
                            vehicleCommand.KnockedOutVehicle();
                            int damageHitAnim = 1;
                            float damageHitDir = 0;
                            StartCommand_Damage(damageHitAnim, m_DamageHitDir);
                            TryHideItemInHands(false,true);
                        }
                        else
{
                            m_TransportCache = vehicleCommand.GetTransport();
                        }
                    }
                    StartCommand_Unconscious(0);
                }
                if ( m_IsUnconscious /*&& pCurrentCommandID != DayZPlayerConstants.COMMANDID_DEATH*/)
                {
                    m_IsUnconscious = false;
                    OnUnconsciousStop(pCurrentCommandID);
                }
            }
            // quickbar use
            int quickBarSlot = hic.IsQuickBarSlot();
            if ( quickBarSlot && IsAlive())
            {
                if (hic.IsQuickBarSingleUse())
                {
                    OnQuickBarSingleUse(quickBarSlot);
                    //Print("PlayerBase.c IsQuickBarSingleUse - slot: " + quickBarSlot.ToString());
                }
                if (hic.IsQuickBarContinuousUseStart() && ((!GetGame().IsDedicatedServer()) && !GetGame().GetUIManager().GetMenu()))
                {
                    OnQuickBarContinuousUseStart(quickBarSlot);
                    //Print("PlayerBase.c IsQuickBarContinuousUseStart - slot: " + quickBarSlot.ToString());
                }
                if (hic.IsQuickBarContinuousUseEnd() && ((!GetGame().IsDedicatedServer())))
                {
                    OnQuickBarContinuousUseEnd(quickBarSlot);
                    //Print("PlayerBase.c IsQuickBarContinuousUseEnd - slot: " + quickBarSlot.ToString());
                }
            }
            /*if ((pCurrentCommandID == DayZPlayerConstants.COMMANDID_ACTION || pCurrentCommandID == DayZPlayerConstants.COMMANDID_MOVE || pCurrentCommandID == DayZPlayerConstants.COMMANDID_LADDER || pCurrentCommandID == DayZPlayerConstants.COMMANDID_SWIM ) )
            {
                mngr.Update(); // checks for suitable action and sets it
            }*/
        }
        if (m_StaminaHandler && hic)
        {
            if ( !CanConsumeStamina(EStaminaConsumers.SPRINT) || !CanSprint() )
            {
                hic.LimitsDisableSprint(true);
            }
            else
            {
                hic.LimitsDisableSprint(false);
            }
        }
        //map closing - feel free to move to different "update" if it does not belong here
        if ( IsMapOpen() )
        {
            if ( !GetGame().IsDedicatedServer() )
            {
                if ( !CfgGameplayHandler.GetUse3DMap() && !GetGame().GetUIManager().IsMenuOpen(MENU_MAP) )
                {
                    CloseMapEx(false);
                }
                else if ( CfgGameplayHandler.GetUse3DMap() )
                {
                    if ( IsMapCallbackCancelInput() )
                    {
                        CloseMapEx(true);
                    }
                    else if ( IsMapCallbackEndInput() )
                    {
                        CloseMapEx(false);
                    }
                }
            }
        }
#ifdef BOT
        if (m_Bot)
            m_Bot.OnUpdate(pDt);
#endif
        if (m_CheckMeleeItem && (!GetGame().IsDedicatedServer()))
        {
            bool result = CheckMeleeItemDamage(m_CheckMeleeItem);
            //if (result)
                SetCheckMeleeItem();
        }
        OnCommandHandlerTick(pDt, pCurrentCommandID);
    }
References HumanInputController::CameraIsFreeLook(), CanConsumeStamina(), GetActionManager(), GetCommand_Unconscious(), GetCommand_Vehicle(), CGame::GetCurrentCameraDirection(), GetDayZPlayerInventory(), GetGame(), GetInputController(), GetInstanceType(), HumanCommandVehicle::GetTransport(), CfgGameplayHandler::GetUse3DMap(), HandleDamageHit(), IsAlive(), IsPlayerSelected(), HumanInputController::IsQuickBarContinuousUseEnd(), HumanInputController::IsQuickBarContinuousUseStart(), HumanInputController::IsQuickBarSingleUse(), HumanInputController::IsQuickBarSlot(), HumanCommandVehicle::KnockedOutVehicle(), HumanInputController::LimitsDisableSprint(), m_DamageHitDir, m_IsFireWeaponRaised, m_IsUnconscious, m_LastCommandBeforeUnconscious, m_MovementState, m_ShouldBeUnconscious, m_StaminaHandler, m_TransportCache, m_UnconsciousDebug, MENU_MAP, HumanCommandVehicle::ShouldBeKnockedOut(), StartCommand_Damage(), StartCommand_Unconscious(), ActionManagerBase::Update(), HumanCommandUnconscious::WakeUp(), and vector::Zero.
Consume()
bool ManBase::Consume (ItemBase source, float amount, EConsumeType consume_type) inline private
Definition at line 6903 of file playerbase.c.
    {
        PluginTransmissionAgents plugin = PluginTransmissionAgents.Cast( GetPlugin(PluginTransmissionAgents) );
        int agents;
        if( consume_type == EConsumeType.ENVIRO_POND || consume_type == EConsumeType.ENVIRO_WELL )
        {
            if ( consume_type == EConsumeType.ENVIRO_POND )
            {
                agents = agents | eAgents.CHOLERA;
                //plugin.TransmitAgents(NULL, this, AGT_WATER_POND, amount);
            }
            m_PlayerStomach.AddToStomach(Liquid.GetLiquidClassname(LIQUID_WATER), amount, 0 , agents );
            return true;
        }
        Edible_Base edible_item = Edible_Base.Cast(source);
        if(!edible_item)
        {
            return false;
        }
        agents = edible_item.GetAgents();
        if( consume_type == EConsumeType.ITEM_SINGLE_TIME || consume_type == EConsumeType.ITEM_CONTINUOUS )
        {
            if(consume_type == EConsumeType.ITEM_SINGLE_TIME)
            {
                plugin.TransmitAgents(edible_item, this, AGT_UACTION_CONSUME, amount);
            }
            /*
            else
            {
                plugin.TransmitAgents(edible_item, this, AGT_UACTION_TO_PLAYER, amount);
            }
            */
            if(edible_item.IsLiquidContainer())
            {
                int liquid_type = edible_item.GetLiquidType();
                string liquidClassName = Liquid.GetLiquidClassname(liquid_type);
                if (liquidClassName.Length() == 0)
                    Error("Error! Trying to add unknown liquid to stomach with item=" + Object.GetDebugName(edible_item) + " consume_type=" + consume_type + " liquid_type=" + liquid_type);
                m_PlayerStomach.AddToStomach(liquidClassName, amount, 0, agents);
            }
            else
            {
                int food_stage_type;
                if( edible_item.GetFoodStage() )
                {
                    food_stage_type = edible_item.GetFoodStage().GetFoodStageType();
                }
                m_PlayerStomach.AddToStomach(source.GetType(), amount, food_stage_type, agents);
            }
            edible_item.Consume(amount, this);
            return true;
        }
        /*
        if( consume_type == EConsumeType.ITEM_CONTINUOUS )
        {
            if(edible_item)
            {
                plugin.TransmitAgents(edible_item, this, AGT_UACTION_TO_PLAYER, amount);
                edible_item.Consume(amount, this);
                //ProcessNutritions(edible_item.GetNutritionalProfile(),amount);
                m_PlayerStomach.AddToStomach(source.GetType(), amount, edible_item.GetNutritionalProfile());
                return true;
            }
        }
        */
        return false;
    }
References AGT_UACTION_CONSUME, Error(), Liquid::GetLiquidClassname(), GetPlugin(), string::Length(), and LIQUID_WATER.
ContaminatedParticleAdjustment()
void ManBase::ContaminatedParticleAdjustment () inline private
Definition at line 8864 of file playerbase.c.
    {
        if ( GetCommand_Move() && m_ContaminatedAroundPlayer && m_ContaminatedAroundPlayerTiny)
        {
            float playerSpeed = GetCommand_Move().GetCurrentMovementSpeed();
            //Print( playerSpeed );
            // 1 - prone, crouch
            // 2 - jog
            // 3 - sprint
            float particleLifetime = 5.25;
            float particleSpeed = 0.25;
            if ( playerSpeed >= 1 )
            {
                particleLifetime = 3.5;
                particleSpeed = 3.25;
            }
            if ( playerSpeed >= 2 )
            {
                particleLifetime = 2.5;
                particleSpeed = 5.25;
            }
            if ( playerSpeed >= 3 )
            {
                particleLifetime = 1.5;
                particleSpeed = 8.25;
            }
            m_ContaminatedAroundPlayer.SetParameter( 0, EmitorParam.LIFETIME, particleLifetime );
            m_ContaminatedAroundPlayer.SetParameter( 1, EmitorParam.LIFETIME, particleLifetime );
            m_ContaminatedAroundPlayer.SetParameter( 2, EmitorParam.LIFETIME, particleLifetime );
            m_ContaminatedAroundPlayer.SetParameter( 3, EmitorParam.LIFETIME, particleLifetime );
            m_ContaminatedAroundPlayerTiny.SetParameter( 0, EmitorParam.VELOCITY, particleSpeed );
            vector transform[4];
            GetTransform(transform);
            m_ContaminatedAroundPlayer.SetTransform(transform);
            m_ContaminatedAroundPlayerTiny.SetTransform(transform);
        }
    }
References GetCommand_Move(), HumanCommandMove::GetCurrentMovementSpeed(), and Particle::SetParameter().
ConvertNonlethalDamage()
float ManBase::ConvertNonlethalDamage (float damage) inline private
Definition at line 906 of file playerbase.c.
    {
        float converted_dmg = damage * GameConstants.PROJECTILE_CONVERSION_PLAYERS;
        return converted_dmg;
    }
References GameConstants::PROJECTILE_CONVERSION_PLAYERS.
CreateCopyOfItemInInventory()
ItemBase ManBase::CreateCopyOfItemInInventory (ItemBase src) inline private
/brief Creates copy of ItemBase in players inventory. If player dont have enough slots for new item, item will be created on the ground under player.
Parameters
item_name string Class name of ItemBase in configs
Returns
ItemBase Created item
ItemBase item = g_Game.GetPlayer().CreateInInventory("Consumable_GardenLime", "cargo_weapon");
Definition at line 6189 of file playerbase.c.
    {
        InventoryLocation loc = new InventoryLocation;
        string t = src.GetType();
        if (GetInventory().FindFirstFreeLocationForNewEntity(t, FindInventoryLocationType.CARGO, loc))
        {
            bool locked = GetGame().HasInventoryJunctureDestination(this, loc);
            if (locked)
            {
                Print("Warning: Split: CreateCopyOfItemInInventory - Cannot create entity at locked inventory at loc=" + InventoryLocation.DumpToStringNullSafe(loc));
                return null;
            }
            ItemBase dst = ItemBase.Cast( GetInventory().LocationCreateLocalEntity(loc, t, ECE_IN_INVENTORY, RF_DEFAULT) );
            if (dst)
            {
                MiscGameplayFunctions.TransferItemProperties(src, dst);
                GetGame().RemoteObjectTreeCreate(dst);
                Print("CreateCopyOfItemInInventory - created " + dst.GetName() + " at loc=" + InventoryLocation.DumpToStringNullSafe(loc));
            }
            return dst;
        }
        return NULL;
    }
References InventoryLocation::DumpToStringNullSafe(), ECE_IN_INVENTORY, FindFirstFreeLocationForNewEntity(), GetGame(), CGame::HasInventoryJunctureDestination(), LocationCreateLocalEntity(), Print(), CGame::RemoteObjectTreeCreate(), and RF_DEFAULT.
CreateCopyOfItemInInventoryOrGround()
ItemBase ManBase::CreateCopyOfItemInInventoryOrGround (ItemBase src) inline private
Definition at line 6215 of file playerbase.c.
    {
        return CreateCopyOfItemInInventoryOrGroundEx(src, false);
    }
CreateCopyOfItemInInventoryOrGroundEx()
ItemBase ManBase::CreateCopyOfItemInInventoryOrGroundEx (ItemBase src, bool markItemAsSplitResult = false) inline private
Definition at line 6220 of file playerbase.c.
    {
        ItemBase dst = CreateCopyOfItemInInventory(src);
        if (!dst)
        {
            dst = ItemBase.Cast(SpawnEntityOnGroundPos(src.GetType(), this.GetPosition()));
            dst.PlaceOnSurface();
            dst.SetResultOfSplit(markItemAsSplitResult);
            MiscGameplayFunctions.TransferItemProperties(src, dst);
        }
        return dst;
    }
CreateInInventory()
EntityAI ManBase::CreateInInventory (string item_name, string cargo_type = "", bool full_quantity = false) inline private
/brief Creates ItemBase in players inventory. If player dont have enough slots for new item, item will be created on the ground under player.
Parameters
item_name string Class name of ItemBase in configs
Returns
ItemBase Created item
ItemBase item = g_Game.GetPlayer().CreateInInventory("Consumable_GardenLime", "cargo_weapon");
Definition at line 6152 of file playerbase.c.
    {
        InventoryLocation inv_loc = new InventoryLocation;
        if (GetInventory().FindFirstFreeLocationForNewEntity(item_name, FindInventoryLocationType.ANY, inv_loc))
        {
            return SpawnItemOnLocation(item_name, inv_loc, full_quantity);
        }
        return NULL;
    }
References FindFirstFreeLocationForNewEntity(), and SpawnItemOnLocation().
DamageAllLegs()
void ManBase::DamageAllLegs (float inputDmg) inline private
Definition at line 8707 of file playerbase.c.
    {
        array<string> legZones = new array<string>;
        legZones.Insert("LeftLeg");
        legZones.Insert("RightLeg");
        legZones.Insert("RightFoot");
        legZones.Insert("LeftFoot");
        for (int i = 0; i < legZones.Count(); i++)
        {
            DecreaseHealth(legZones[i],"",inputDmg);
        }
    }
References DecreaseHealth().
DealShock()
void ManBase::DealShock (float dmg) inline private
Definition at line 3435 of file playerbase.c.
    {
        Param1<float> damage = new Param1<float>(0);
        damage.param1 = dmg;
        GetGame().RPCSingleParam(this, ERPCs.RPC_SHOCK, damage, true, GetIdentity());
    }
References GetGame(), and CGame::RPCSingleParam().
DecreaseAntibioticsCount()
void ManBase::DecreaseAntibioticsCount () inline private
Definition at line 519 of file playerbase.c.
    {
        m_AntibioticsActive--;
        if(m_AntibioticsActive < 0)
        {
            m_AntibioticsActive = 0;
            Error("DecreaseAntibioticsCount called more times than IncreaseAntibioticsCount (should be equal) - check your code, forcing clamp to 0");
        }
    }
References Error().
DecreaseDiseaseCount()
void ManBase::DecreaseDiseaseCount () inline private
Definition at line 655 of file playerbase.c.
    {
        m_DiseaseCount--;
    }
DecreaseHealingsCount()
void ManBase::DecreaseHealingsCount () inline private
Definition at line 665 of file playerbase.c.
    {
        m_HealingsCount--;
    }
DepleteStamina()
override void ManBase::DepleteStamina (EStaminaModifiers modifier, float dT = -1) inline private
Definition at line 3970 of file playerbase.c.
    {
        if( GetStaminaHandler() )
            GetStaminaHandler().DepleteStamina(modifier,dT);
    }
dmgDebugPrint()
void ManBase::dmgDebugPrint (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 8697 of file playerbase.c.
    {
        /*Print("ProjectileDebugging | Damage Health: " + damageResult.GetDamage(dmgZone,"Health") + " | Component: " + component + " | Zone: " + dmgZone + "| Timestamp: " + GetSimulationTimeStamp());
        Print("ProjectileDebugging | speedCoef: " + speedCoef);
        Print("ProjectileDebugging | GetWorldTime(): " + GetWorldTime());
        Print("-----------------------------------------------");*/
    }
DropAllItems()
void ManBase::DropAllItems () inline private
Drops all clothes/wearables this character is carrying on themselves.
Definition at line 6330 of file playerbase.c.
    {
        array<EntityAI> itemsArray = new array<EntityAI>;
        ItemBase item;
        GetInventory().EnumerateInventory(InventoryTraversalType.LEVELORDER, itemsArray);
        int count = itemsArray.Count();
        for (int i = 0; i < itemsArray.Count(); i++)
        {
            Class.CastTo(item, itemsArray.Get(i));
            if (item  &&  !item.IsInherited(SurvivorBase))
            {
                ServerDropEntity(item);
            }
        }
    }
References Class::CastTo().
DropHeavyItem()
void ManBase::DropHeavyItem () inline private
Definition at line 3460 of file playerbase.c.
    {
        ItemBase itemInHands = GetItemInHands();
        if ( itemInHands && itemInHands.IsHeavyBehaviour() )
            DropItem(itemInHands);
    }
DropItem()
bool ManBase::DropItem (ItemBase item) inline private
Spawn item on server side.
Parameters
object_name string Name of item class
spawn_type \int(const) Type of spawning const: SPAWNTYPE_GROUND, SPAWNTYPE_HANDS, SPAWNTYPE_INVENTORY
full_quantity \bool Spawn with full quantity of item
distance \float Distance of spawn position from player (Only if spawn_type = SPAWNTYPE_GROUND)
Returns
ItemBase Spawned item
PlayerBase player = GetGame().GetPlayer();
player.SpawnItem("Fruit_Apple", SPAWNTYPE_GROUND, true, 5);
Definition at line 6086 of file playerbase.c.
    {
        bool can_be_dropped = CanDropEntity( item );
        if( can_be_dropped )
        {
            can_be_dropped = PredictiveDropEntity( item );
        }
        vector  pos_spawn   = GetPosition() + GetDirection();
        pos_spawn[0]        = pos_spawn[0] + Math.RandomFloat(-0.2, 0.2);
        pos_spawn[2]        = pos_spawn[2] + Math.RandomFloat(-0.2, 0.2);
        item.SetPosition(pos_spawn);
        item.PlaceOnSurface();
        return can_be_dropped;
    }
References GetDirection(), GetPosition, and Math::RandomFloat().
EEDelete()
override void ManBase::EEDelete (EntityAI parent) inline private
Definition at line 899 of file playerbase.c.
    {
        SEffectManager.DestroyEffect( m_FliesEff );
//      ErrorEx("DbgFlies | StopSoundSet | exit 1 ",ErrorExSeverity.INFO);
        StopSoundSet(m_SoundFliesEffect);
    }
References SEffectManager::DestroyEffect(), and StopSoundSet().
EEHealthLevelChanged()
override void ManBase::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 5469 of file playerbase.c.
    {
        super.EEHealthLevelChanged(oldLevel, newLevel, zone);
        if ( !GetGame().IsDedicatedServer() )
        {
            if (newLevel == GameConstants.STATE_RUINED)
            {
                ClearLastUAMessage();
            }
            if (m_CorpseState != 0)
            {
                GetGame().GetCallQueue( CALL_CATEGORY_GUI ).CallLater( UpdateCorpseState, 0, false);
            }
        }
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and GameConstants::STATE_RUINED.
EEHitBy()
override void ManBase::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
DT_EXPLOSION & FlashGrenade
Definition at line 815 of file playerbase.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        if( m_AdminLog )
        {
            m_AdminLog.PlayerHitBy( damageResult, damageType, this, source, component, dmgZone, ammo );
        }
        if( damageResult != null && damageResult.GetDamage(dmgZone, "Shock") > 0)
        {
            m_LastShockHitTime = GetGame().GetTime();
            if(!IsUnconscious())
            {
                if(GetGame().ConfigIsExisting("cfgAmmo " + ammo + " unconRefillModifier"))
                {
                    m_UnconRefillModifier = GetGame().ConfigGetInt("cfgAmmo " + ammo + " unconRefillModifier");
                }
                else
                {
                    m_UnconRefillModifier = 1;
                }
            }
        }
        if( damageType == DT_EXPLOSION && ammo == "FlashGrenade_Ammo" )
        {
            GetStaminaHandler().DepleteStamina(EStaminaModifiers.OVERALL_DRAIN);
        }
        //new bleeding computation
        //---------------------------------------
        if( damageResult != null && GetBleedingManagerServer() )
        {
            float dmg = damageResult.GetDamage(dmgZone, "Blood");
            GetBleedingManagerServer().ProcessHit(dmg, source, component, dmgZone, ammo, modelPos);
        }
        //---------------------------------------
        #ifdef DEVELOPER
        if (DiagMenu.GetBool(DiagMenuIDs.DM_MELEE_DEBUG_ENABLE))
            Print("EEHitBy() | " + GetDisplayName() + " hit by " + source.GetDisplayName() + " to " + dmgZone);
        PluginRemotePlayerDebugServer plugin_remote_server = PluginRemotePlayerDebugServer.Cast( GetPlugin(PluginRemotePlayerDebugServer) );
        if(plugin_remote_server)
        {
            plugin_remote_server.OnDamageEvent(this, damageResult);
        }
        #endif
        if( GetGame().IsDebugMonitor() )
            m_DebugMonitorValues.SetLastDamage(source.GetDisplayName());
        if( m_ActionManager )
            m_ActionManager.Interrupt();
        if ( ammo.ToType().IsInherited(Nonlethal_Base) )
        {
            //Print("PlayerBase | EEHitBy | nonlethal hit");
            AddHealth("","Health",-ConvertNonlethalDamage(damageResult.GetDamage(dmgZone,"Shock")));
            if (dmgZone != "Head")
                AddHealth(dmgZone,"Health",-damageResult.GetDamage(dmgZone,"Shock")); //Also deal damage to zone health, no dmg reduction
        }
        if (GetGame().IsServer())
        {
            if ( GetHealth("RightLeg", "Health") <= 1 || GetHealth("LeftLeg", "Health") <= 1 || GetHealth("RightFoot", "Health") <= 1 || GetHealth("LeftFoot", "Health") <= 1 )
            {
                if ( GetModifiersManager().IsModifierActive( eModifiers.MDF_BROKEN_LEGS ) )//effectively resets the modifier
                {
                    GetModifiersManager().DeactivateModifier( eModifiers.MDF_BROKEN_LEGS );
                }
                GetModifiersManager().ActivateModifier( eModifiers.MDF_BROKEN_LEGS );
            }
        }
        //m_ShockHandler.SetShock(damageResult.GetDamage("", "Shock")); //TESTING
        m_ShockHandler.CheckValue(true);
        //analytics
        GetGame().GetAnalyticsServer().OnEntityHit( source, this );
    }
References AddHealth(), component, CGame::ConfigGetInt(), ConfigIsExisting(), CGame::GetAnalyticsServer(), DiagMenu::GetBool(), TotalDamageResult::GetDamage(), GetDisplayName(), GetGame(), GetHealth(), GetPlugin(), CGame::GetTime(), IsModifierActive(), m_AdminLog, AnalyticsManagerServer::OnEntityHit(), Print(), and string::ToType().
EEHitByRemote()
override void ManBase::EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) inline private
Definition at line 933 of file playerbase.c.
    {
        super.EEHitByRemote(damageType, source, component, dmgZone, ammo, modelPos);
        //Print("DayZPlayerImplement : EEHitByRemote");
    }
References component.
EEItemAttached()
override void ManBase::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 974 of file playerbase.c.
    {
        super.EEItemAttached(item, slot_name);
        SwitchItemSelectionTexture(item, slot_name);
        Param1<PlayerBase> p = new Param1<PlayerBase>(this);
        item.SwitchItemSelectionTextureEx(EItemManipulationContext.ATTACHING,p/*new Param1<PlayerBase>(this)*/);
        m_QuickBarBase.updateSlotsCount();
        CalculateVisibilityForAI();
        UpdateShoulderProxyVisibility(item, slot_name);
        HideHairSelections(ItemBase.Cast(item),true);
        GetGame().GetAnalyticsClient().OnItemAttachedAtPlayer(item, slot_name);
        Clothing clothing = Clothing.Cast(item);
        if ( clothing )
        {
            if ( !GetGame().IsDedicatedServer() )
            {
                if ( clothing.GetEffectWidgetTypes() )
                {
                    QueueAddEffectWidget(clothing.GetEffectWidgetTypes());
                }
                if ( clothing.GetGlassesEffectID() > -1 )
                {
                    QueueAddGlassesEffect(clothing.GetGlassesEffectID());
                }
                GetGame().GetCallQueue( CALL_CATEGORY_GUI ).CallLater( UpdateCorpseStateVisual, 200, false);//sometimes it takes a while to load in
                UpdateCorpseStateVisual();//....but if possible, we don't want a delay
            }
            else if ( GetGame().IsServer() )
            {
                if ( clothing.IsGasMask() )
                {
                    GetModifiersManager().ActivateModifier(eModifiers.MDF_MASK);
                }
            }
            clothing.UpdateNVGStatus(this,true);
        }
        AdjustBandana(item,slot_name);
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetAnalyticsClient(), CGame::GetCallQueue(), Clothing::GetEffectWidgetTypes(), GetGame(), Clothing::GetGlassesEffectID(), Clothing::IsGasMask(), and AnalyticsManagerClient::OnItemAttachedAtPlayer().
EEItemDetached()
override void ManBase::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 1019 of file playerbase.c.
    {
        super.EEItemDetached(item, slot_name);
        SwitchItemSelectionTexture(item, slot_name);
        item.SwitchItemSelectionTextureEx(EItemManipulationContext.DETACHING);
        m_QuickBarBase.updateSlotsCount();
        CalculateVisibilityForAI();
        HideHairSelections(ItemBase.Cast(item),false);
        Clothing clothing = Clothing.Cast(item);
        if ( clothing )
        {
            if ( !GetGame().IsDedicatedServer() )
            {
                if ( clothing.GetEffectWidgetTypes() )
                {
                    QueueRemoveEffectWidget(clothing.GetEffectWidgetTypes());
                }
                if ( clothing.GetGlassesEffectID() > -1 )
                {
                    QueueRemoveGlassesEffect(clothing.GetGlassesEffectID());
                }
            }
            if ( GetGame().IsServer() )
            {
                if ( clothing.IsGasMask() )
                {
                    GetModifiersManager().DeactivateModifier(eModifiers.MDF_MASK);
                }
            }
            clothing.UpdateNVGStatus(this);
            GetGame().GetCallQueue( CALL_CATEGORY_GUI ).CallLater( UpdateCorpseStateVisual, 200, false);//sometimes it takes a while to load in
            UpdateCorpseStateVisual();//....but if possible, we don't want a delay
        }
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), Clothing::GetEffectWidgetTypes(), GetGame(), Clothing::GetGlassesEffectID(), and Clothing::IsGasMask().
EEItemIntoHands()
override void ManBase::EEItemIntoHands (EntityAI item) inline private
fixes situation where raise is canceling some manipulation with heavy item(ex. TakeItemToHands), forces normal stance
Definition at line 2577 of file playerbase.c.
    {
        super.EEItemIntoHands( item );
        if ( item )
        {
            Weapon_Base w;
            if ( Class.CastTo(w, item) )
            {
                w.ResetWeaponAnimState();
                HumanCommandMove cm = GetCommand_Move();
                if ( cm )
                {
                    cm.SetMeleeBlock( false );
                    GetMeleeFightLogic().SetBlock( false );
                }
            }
            if ( item.IsHeavyBehaviour() && IsRaised() )
            {
                HumanCommandMove cm2 = GetCommand_Move();
                if ( cm2 )
                {
                    cm2.ForceStance(DayZPlayerConstants.STANCEIDX_ERECT);
                }
            }
        }
        //SetOpticsPreload(true,item);
    }
References Class::CastTo(), HumanCommandMove::ForceStance(), GetCommand_Move(), GetMeleeFightLogic(), IsRaised(), and HumanCommandMove::SetMeleeBlock().
EEItemOutOfHands()
override void ManBase::EEItemOutOfHands (EntityAI item) inline private
Definition at line 2610 of file playerbase.c.
    {
        super.EEItemOutOfHands( item );
        if ( IsPlacingLocal() )
        {
            GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(TogglePlacingLocal);
        }
        if ( !IsAlive() )
            OnItemInHandsChanged();
        //SetOpticsPreload(false,item);
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), GetGame(), IsAlive(), and OnItemInHandsChanged().
EEKilled()
override void ManBase::EEKilled (Object killer) inline private
Definition at line 771 of file playerbase.c.
    {
        //Print(Object.GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " event EEKilled, player has died at STS=" + GetSimulationTimeStamp());
        if ( m_AdminLog )
        {
            m_AdminLog.PlayerKilled( this, killer );
        }
        if (GetBleedingManagerServer())
            delete GetBleedingManagerServer();
        if (GetModifiersManager())
            GetModifiersManager().DeactivateAllModifiers();
        // kill character in database
        if (GetHive())
        {
            GetHive().CharacterKill(this);
        }
        // disable voice communication
        GetGame().EnableVoN(this, false);
        if( !GetGame().IsDedicatedServer() )
            ClientData.RemovePlayerBase( this );
        GetSymptomManager().OnPlayerKilled();
        if ( GetEconomyProfile() && !m_CorpseProcessing && m_CorpseState == 0 && GetGame().GetMission().InsertCorpse(this) )
        {
            m_CorpseProcessing = true;
            //Print("EEKilled - processing corpse");
        }
        if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
        {
            if (GetGame().GetMission())
            {
                GetGame().GetMission().SyncRespawnModeInfo(GetIdentity());
            }
        }
        super.EEKilled( killer );
    }
References Hive::CharacterKill(), CGame::EnableVoN(), GetGame(), GetHive(), CGame::GetMission(), m_AdminLog, ClientData::RemovePlayerBase(), and Mission::SyncRespawnModeInfo().
EndFighting()
void ManBase::EndFighting () inline private
Definition at line 4990 of file playerbase.c.
    {
        m_IsFighting = false;
    }
EndSurrenderRequest()
void ManBase::EndSurrenderRequest (SurrenderData data = null) inline private
ends surrender, originally intended for surrender->restrained transitioning
Definition at line 7939 of file playerbase.c.
    {
        if (m_EmoteManager)
            m_EmoteManager.EndSurrenderRequest(data);
    }
EOnFrame()
override void ManBase::EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 3812 of file playerbase.c.
    {
        //super.EOnFrame(other, timeSlice);
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
#ifndef NO_GUI
            m_Hud.Update( timeSlice );
            m_Hud.ToggleHeatBufferPlusSign( m_HasHeatBuffer );
            if (IsControlledPlayer() && m_EffectWidgets && m_EffectWidgets.IsAnyEffectRunning())
            {
                m_EffectWidgets.Update(timeSlice);
            }
#endif
            if (m_UndergroundHandler)
                m_UndergroundHandler.Tick(timeSlice);
        }
    }
References GetInstanceType(), GameplayEffectWidgets_base::IsAnyEffectRunning(), m_Hud, Hud::ToggleHeatBufferPlusSign(), Hud::Update(), and GameplayEffectWidgets_base::Update().
EOnPostFrame()
override void ManBase::EOnPostFrame (IEntity other, int extra) inline private
Definition at line 3832 of file playerbase.c.
    {
        //super.EOnPostFrame(other, extra);
        float delta_time = (GetGame().GetTime() - m_LastPostFrameTickTime) / 1000;
        m_LastPostFrameTickTime = GetGame().GetTime();
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            if( GetDamageDealtEffect() )
            {
                if (IsAlive())
                    GetDamageDealtEffect().Update(delta_time);
                else
                    delete GetDamageDealtEffect();
            }
            if (m_EffectRadial)
            {
                if(IsAlive())
                {
                    m_EffectRadial.Update(delta_time);
                }
                else
                    m_EffectRadial = null;
            }
            if (GetFlashbangEffect())
            {
                if (IsAlive())
                {
                    GetFlashbangEffect().Update(delta_time);
                }
                else
                {
                    delete GetFlashbangEffect();
                }
            }
            if( GetShockEffect() )
            {
                if (IsAlive())
                    GetShockEffect().Update(delta_time);
                else
                    delete GetShockEffect();
            }
            m_InventoryActionHandler.OnUpdate();
#ifdef DEVELOPER
            if (m_WeaponDebug)
            {
                m_WeaponDebug.OnPostFrameUpdate();
            }
            if ( GetBleedingManagerRemote() )
            {
                GetBleedingManagerRemote().OnUpdate();
            }
            if (m_MeleeCombat)
            {
                if (DiagMenu.GetBool(DiagMenuIDs.DM_MELEE_DEBUG_ENABLE))
                {
                    m_MeleeDebug = true;
                    m_MeleeCombat.Debug(GetItemInHands(), m_MeleeCombat.GetHitType());
                }
                else if (!DiagMenu.GetBool(DiagMenuIDs.DM_MELEE_DEBUG_ENABLE) && m_MeleeDebug)
                {
                    m_MeleeDebug = false;
                    m_MeleeCombat.Debug(GetItemInHands(), m_MeleeCombat.GetHitType());
                }
            }
            if (m_Environment)
            {
                if (DiagMenu.GetBool(DiagMenuIDs.DM_ENVIRONMENT_DEBUG_ENABLE))
                {
                    m_Environment.ShowEnvDebugPlayerInfo(DiagMenu.GetBool(DiagMenuIDs.DM_ENVIRONMENT_DEBUG_ENABLE));
                }
            }
            if (DiagMenu.GetBool(DiagMenuIDs.DM_SOUNDS_ITEM_IMPACT_SOUNDS))
                InventoryItem.DrawImpacts();
            if (GetPluginManager())
            {
                PluginDrawCheckerboard drawCheckerboard = PluginDrawCheckerboard.Cast(GetPluginManager().GetPluginByType(PluginDrawCheckerboard));
                if (drawCheckerboard && !drawCheckerboard.IsActive())
                {
                    drawCheckerboard.ShowWidgets(DiagMenu.GetBool(DiagMenuIDs.DM_DRAW_CHECKERBOARD));
                }
            }
            if (m_PresenceNotifier)
            {
                m_PresenceNotifier.EnableDebug(DiagMenu.GetBool(DiagMenuIDs.DM_PRESENCE_NOTIFIER_DBG));
            }
            if (DiagMenu.GetBool(DiagMenuIDs.DM_SHOW_PLAYER_TOUCHTRIGGER))
            {
                vector minmax[2];
                GetCollisionBox(minmax);
                int color = COLOR_RED_A;
                if (m_IsInsideTrigger)
                    color = COLOR_GREEN_A;
                Shape dbgShape = Debug.DrawBoxEx(minmax[0], minmax[1], color, ShapeFlags.TRANSP|ShapeFlags.NOZWRITE|ShapeFlags.ONCE);
                vector mat[4];
                GetTransform( mat );
                dbgShape.CreateMatrix( mat );
                dbgShape.SetMatrix( mat );
            }
#endif
        }
    }
References COLOR_GREEN_A, COLOR_RED_A, Debug::DrawBoxEx(), DiagMenu::GetBool(), GetCollisionBox(), GetGame(), GetInstanceType(), GetPluginManager(), CGame::GetTime(), IsAlive(), m_MeleeCombat, m_WeaponDebug, WeaponDebug::OnPostFrameUpdate(), and Shape.
FindCargoByBaseType()
EntityAI ManBase::FindCargoByBaseType (string searched_item) inline private
Definition at line 1919 of file playerbase.c.
    {
        EntityAI attachment;
        string item_name;
        int attcount = this.GetInventory().AttachmentCount();
        for (int att = 0; att < attcount; att++)
        {
            attachment = GetInventory().GetAttachmentFromIndex(att);
            if ( attachment.IsItemBase() )
            {
                item_name = attachment.GetType();
                if ( GetGame().IsKindOf(item_name, searched_item) )
                {
                    return attachment;
                }
            }
        }
        return NULL;
    }
References GetGame(), and IsKindOf().
FindQuickBarEntityIndex()
int ManBase::FindQuickBarEntityIndex (EntityAI entity) inline private
Definition at line 1787 of file playerbase.c.
    {
        int index;
        index = m_QuickBarBase.FindEntityIndex(entity);
        if(m_QuickBarBase.GetEntity(index) == NULL )
            return -1;
        return index;
    }
FixAllInventoryItems()
void ManBase::FixAllInventoryItems () inline private
Definition at line 5578 of file playerbase.c.
    {
        GameInventory inv = PlayerBase.Cast(this).GetInventory();
        ref array<EntityAI> items = new array<EntityAI>;
        inv.EnumerateInventory(InventoryTraversalType.INORDER, items);
        for(int i = 0; i < items.Count(); i++)
        {
            EntityAI item = items.Get(i);
            item.SetHealthMax("","");
            //Print("Fixing item: "+item);
        }
    }
ForceUpdateInjuredState()
void ManBase::ForceUpdateInjuredState () inline private
update injured state immediately
Injured stat
Definition at line 7538 of file playerbase.c.
    {
        m_InjuryHandler.CheckValue(true);
    }
FreezeCheck()
void ManBase::FreezeCheck () inline private
Definition at line 3043 of file playerbase.c.
    {
        int level;
        if( m_ShakesForced > 0 )
        {
            level = m_ShakesForced;
        }
        else
        {
            float heat_comfort = GetStatHeatComfort().Get();
            if( heat_comfort <= PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING )
            {
                float value = Math.InverseLerp( PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING, PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL,heat_comfort);
                level = Math.Lerp(1,7,value);
                level = Math.Clamp(value,1,7);
                /*
                value = Math.Clamp(value,0,1);
                level = Math.Round(value * SHAKE_LEVEL_MAX);//translate from normalized value to levels
                */
            }
        }
        if( level != m_Shakes )
        {
            m_Shakes = level;
            SetSynchDirty();
        }
    }
References Math::Clamp(), Math::InverseLerp(), Math::Lerp(), PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_CRITICAL, and PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING.
GetActionManager()
ActionManagerBase ManBase::GetActionManager () inline private
Definition at line 1374 of file playerbase.c.
    {
        return m_ActionManager;
    }
GetActions()
override void ManBase::GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
Definition at line 1273 of file playerbase.c.
    {
        if (!m_ActionsInitialize)
        {
            m_ActionsInitialize = true;
            InitializeActions();
        }
        // Backwards compatibility
        array<ActionBase_Basic> bcActions = m_InputActionMap.Get(action_input_type);
        if (!bcActions)
        {
            if (IsControlledPlayer())
                actions = m_InputActionMapControled.Get(action_input_type);
            else
                actions = m_InputActionMapAsTarget.Get(action_input_type);
        }
        else
        {
            if (!actions)
                actions = new array<ActionBase_Basic>();
            if (IsControlledPlayer())
                actions.InsertAll(m_InputActionMapControled.Get(action_input_type));
            else
                actions.InsertAll(m_InputActionMapAsTarget.Get(action_input_type));
            actions.InsertAll(bcActions);
        }
    }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetAgents()
override int ManBase::GetAgents () inline private
Definition at line 7315 of file playerbase.c.
    {
        return m_AgentPool.GetAgents();
    }
GetAimPosition()
vector ManBase::GetAimPosition () inline private
Definition at line 7373 of file playerbase.c.
    {
        float min_distance = 0.5;       //min distance, default = 5m
        vector from = GetGame().GetCurrentCameraPosition();
        vector to = from + (GetGame().GetCurrentCameraDirection() * min_distance);
        vector contactPos;
        vector contactDir;
        int contactComponent;
        DayZPhysics.RaycastRV( from, to, contactPos, contactDir, contactComponent, NULL, NULL, NULL, false, true );
        return contactPos;
    }
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), and DayZPhysics::RaycastRV().
GetBleedingBits()
int ManBase::GetBleedingBits () inline private
Definition at line 645 of file playerbase.c.
    {
        return m_BleedingBits;
    }
GetBleedingManagerRemote()
BleedingSourcesManagerRemote ManBase::GetBleedingManagerRemote () inline private
Definition at line 2310 of file playerbase.c.
    {
        return m_BleedingManagerRemote;
    }
GetBleedingManagerServer()
BleedingSourcesManagerServer ManBase::GetBleedingManagerServer () inline private
Definition at line 2305 of file playerbase.c.
    {
        return m_BleedingManagerServer;
    }
GetBleedingSourceCount()
int ManBase::GetBleedingSourceCount () inline private
Definition at line 7147 of file playerbase.c.
    {
        if( !GetGame().IsMultiplayer() )
            return m_BleedingSourceCount / 2;
        return m_BleedingSourceCount;
    }
References GetGame().
GetBloodType()
int ManBase::GetBloodType () inline private
Definition at line 6532 of file playerbase.c.
    {
        return m_BloodType;
    }
References m_BloodType.
GetBordersImmunity()
float ManBase::GetBordersImmunity () inline private
Definition at line 4762 of file playerbase.c.
    {
        float immunity = GetImmunity();
        float immmunity_max = 1;
        return GetStatLevelBorders(immunity, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_LOW, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_NORMAL, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_HIGH, immmunity_max);
    }
References PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_HIGH, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_LOW, and PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_NORMAL.
GetBreathVapourLevel()
int ManBase::GetBreathVapourLevel () inline private
Definition at line 587 of file playerbase.c.
    {
        return m_BreathVapour;
    }
GetBrokenLegs()
eBrokenLegs ManBase::GetBrokenLegs () inline private
Definition at line 3252 of file playerbase.c.
    {
        return Math.AbsInt(m_BrokenLegState);//negative value denotes first time activation
    }
References Math::AbsInt().
GetCenter()
override vector ManBase::GetCenter () inline private
Definition at line 8857 of file playerbase.c.
    {
        return GetBonePositionWS( GetBoneIndexByName( "spine3" ) );
    }
References GetBoneIndexByName(), and GetBonePositionWS().
GetConstructionActionData()
ConstructionActionData ManBase::GetConstructionActionData () inline private
Definition at line 1726 of file playerbase.c.
    {
        return m_ConstructionActionData;
    }
GetCraftingManager()
CraftingManager ManBase::GetCraftingManager () inline private
Definition at line 1555 of file playerbase.c.
    {
        return m_CraftingManager;
    }
GetCraftingRecipeID()
int ManBase::GetCraftingRecipeID () inline private
Definition at line 1699 of file playerbase.c.
    {
        if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            return GetCraftingManager().GetRecipeID();
        }
        else
        {
            return m_RecipeID;
        }
    }
References GetInstanceType(), and m_RecipeID.
GetCurrentPlayerCamera()
DayZPlayerCamera ManBase::GetCurrentPlayerCamera () inline private
Definition at line 2292 of file playerbase.c.
    {
        return m_CurrentCamera;
    }
GetCurrentRecipe()
int ManBase::GetCurrentRecipe () inline private
Definition at line 1356 of file playerbase.c.
    {
        return m_RecipePick;
    }
GetDamageDealtEffect()
DamageDealtEffect ManBase::GetDamageDealtEffect () inline private
Definition at line 712 of file playerbase.c.
    {
        return m_DamageDealtEffect;
    }
GetDebugActions()
void ManBase::GetDebugActions (out TSelectableActionInfoArray outputList) inline private
Definition at line 7544 of file playerbase.c.
    {
        PluginTransmissionAgents plugin_trans_agents = PluginTransmissionAgents.Cast( GetPlugin(PluginTransmissionAgents) );
        string name;
        int id;
        map<int,string> agent_list = plugin_trans_agents.GetSimpleAgentList();
        for(int i = 0; i < agent_list.Count(); i++)
        {
            name = agent_list.GetElement(i);
            id = agent_list.GetKey(i);
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION,EActions.DEBUG_AGENTS_RANGE_INJECT_START + id, "Inject " + name));
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION,EActions.DEBUG_AGENTS_RANGE_REMOVE_START + id, "Remove " + name));
        }
    }
References GetPlugin(), name, and SAT_DEBUG_ACTION.
GetDebugMonitorValues()
DebugMonitorValues ManBase::GetDebugMonitorValues () inline private
Definition at line 2333 of file playerbase.c.
    {
        return m_DebugMonitorValues;
    }
GetDefaultHitComponent()
override string ManBase::GetDefaultHitComponent () inline private
returns default hit component (fallback)
Definition at line 951 of file playerbase.c.
    {
        return GetDayZPlayerType().GetDefaultHitComponent();
    }
References GetDayZPlayerType().
GetDefaultHitPosition()
override vector ManBase::GetDefaultHitPosition () inline private
Definition at line 956 of file playerbase.c.
    {
        return m_DefaultHitPosition;
    }
GetDeltaT()
float ManBase::GetDeltaT () inline private
Definition at line 171 of file playerbase.c.
    {
        return m_dT;
    }
GetEmoteManager()
EmoteManager ManBase::GetEmoteManager () inline private
Definition at line 1379 of file playerbase.c.
    {
        return m_EmoteManager;
    }
GetFeetDamageMoveModifier()
float ManBase::GetFeetDamageMoveModifier () inline private
Definition at line 1496 of file playerbase.c.
    {
        float modifier;
        switch(m_MovementState.m_iMovement)
        {
            case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
                modifier = 1;
                break
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
                modifier = 0.5;
                break
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
                modifier = 0;
                break
        }
        return modifier;
    }
References m_MovementState.
GetFlagTendencyRaise()
bool ManBase::GetFlagTendencyRaise () inline private
DEPRECATED.
Definition at line 4519 of file playerbase.c.
    {
        return m_FlagRaisingTendency;
    }
GetFlashbangEffect()
FlashbangEffect ManBase::GetFlashbangEffect () inline private
Definition at line 740 of file playerbase.c.
    {
        return m_FlashbangEffect;
    }
GetHealthRegenSpeed()
float ManBase::GetHealthRegenSpeed () inline private
Definition at line 5863 of file playerbase.c.
    {
        float blood =  GetHealth("GlobalHealth", "Blood");
        float blood_scale_normalized = Math.InverseLerp(PlayerConstants.BLOOD_THRESHOLD_FATAL, GetMaxHealth("", "Blood"), blood);
        blood_scale_normalized = Math.Clamp(blood_scale_normalized,0,1);
        return Math.Lerp(PlayerConstants.HEALTH_REGEN_MIN, PlayerConstants.HEALTH_REGEN_MAX, blood_scale_normalized);
    }
References PlayerConstants::BLOOD_THRESHOLD_FATAL, Math::Clamp(), GetHealth(), GetMaxHealth(), PlayerConstants::HEALTH_REGEN_MAX, PlayerConstants::HEALTH_REGEN_MIN, Math::InverseLerp(), and Math::Lerp().
GetHitComponentForAI()
override string ManBase::GetHitComponentForAI () inline private
Melee helpers.
select & return hit component for attacking AI
Definition at line 945 of file playerbase.c.
    {
        return GetDayZPlayerType().GetHitComponentForAI();
    }
References GetDayZPlayerType().
GetHitPPEEnabled()
bool ManBase::GetHitPPEEnabled () inline private
Definition at line 1130 of file playerbase.c.
    {
        return m_CanDisplayHitEffectPPE;
    }
GetHologramLocal()
Hologram ManBase::GetHologramLocal () inline private
Definition at line 2030 of file playerbase.c.
    {
        return m_HologramLocal;
    }
GetHologramServer()
Hologram ManBase::GetHologramServer () inline private
Definition at line 2025 of file playerbase.c.
    {
        return m_HologramServer;
    }
GetImmunity()
float ManBase::GetImmunity () inline private
returns player's immunity strength between 0..1
Definition at line 4857 of file playerbase.c.
    {
        float immunity;
        if( GetPlayerStats() )
        {
            float max_health = GetMaxHealth("GlobalHealth", "Health") + 0.01;//addition to prevent divisioin by zero in case of some messup
            float max_blood = GetMaxHealth("GlobalHealth", "Blood") + 0.01;//addition to prevent divisioin by zero in case of some messup
            float energy_normalized = GetStatEnergy().Get() / PlayerConstants.SL_ENERGY_MAX;
            float water_normalized = GetStatWater().Get() / PlayerConstants.SL_WATER_MAX;
            float health_normalized = GetHealth("GlobalHealth", "Health") / max_health;
            float blood_normalized = GetHealth("GlobalHealth", "Blood") / max_blood;
            immunity = energy_normalized + water_normalized + health_normalized + blood_normalized;
            immunity = immunity / 4;//avg
            immunity =  Math.Clamp(immunity,0,1);
        }
        return immunity;
    }
References Math::Clamp(), GetHealth(), GetMaxHealth(), PlayerConstants::SL_ENERGY_MAX, and PlayerConstants::SL_WATER_MAX.
GetImmunityLevel()
EStatLevels ManBase::GetImmunityLevel () inline private
returns player's immunity level
Definition at line 4753 of file playerbase.c.
    {
        float immunity = GetImmunity();
        if(m_ImmunityBoosted)
            return EStatLevels.GREAT;
        return GetStatLevel(immunity, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_LOW, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_NORMAL, PlayerConstants.IMMUNITY_THRESHOLD_LEVEL_HIGH);
    }
References PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_CRITICAL, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_HIGH, PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_LOW, and PlayerConstants::IMMUNITY_THRESHOLD_LEVEL_NORMAL.
GetItemInHands()
ItemBase ManBase::GetItemInHands () inline private
Definition at line 5941 of file playerbase.c.
    {
        if (GetHumanInventory())
        {
            return ItemBase.Cast( GetHumanInventory().GetEntityInHands() );
        }
        return null;
    }
GetItemOnHead()
ItemBase ManBase::GetItemOnHead () inline private
Returns item on player's head. For an example, a headtorch.
Definition at line 554 of file playerbase.c.
    {
        return GetItemOnSlot("Headgear");
    }
GetItemOnSlot()
ItemBase ManBase::GetItemOnSlot (string slot_type) inline private
Returns item that's on this player's attachment slot. Parameter slot_type should be a string from config parameter 'itemInfo[]' like "Legs", "Headgear" and so on.
Definition at line 537 of file playerbase.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString( slot_type );
        EntityAI item_EAI = this.GetInventory().FindAttachment( slot_id );
        ItemBase item_IB = ItemBase.Cast(item_EAI);
        if (item_EAI  &&  !item_IB)
        {
            string str = "Warning! GetItemOnSlot() >> found item on slot " + slot_type + " can't be cast to ItemBase! Found item is " + item_EAI.GetType() + " and the player is " + GetType() + "!";
            Error(str);
            return null;
        }
        return item_IB;
    }
References Error(), InventorySlots::GetSlotIdFromString(), and GetType().
GetLastFirePoint()
vector ManBase::GetLastFirePoint () inline private
Definition at line 1742 of file playerbase.c.
    {
        return m_LastFirePoint;
    }
GetLastFirePointIndex()
int ManBase::GetLastFirePointIndex () inline private
Definition at line 1750 of file playerbase.c.
    {
        return m_LastFirePointIndex;
    }
GetLastFirePointRot()
float ManBase::GetLastFirePointRot () inline private
Definition at line 1746 of file playerbase.c.
    {
        return m_LastFirePointRot;
    }
GetLastMapInfo()
bool ManBase::GetLastMapInfo (out float scale, out vector pos) inline private
Definition at line 8643 of file playerbase.c.
    {
        scale = m_LastMapScale;
        pos = m_LastMapPos;
        return m_LastMapScale != -1.0;
    }
GetLastShavedSeconds()
int ManBase::GetLastShavedSeconds () inline private
Definition at line 6484 of file playerbase.c.
    {
        return m_LastShavedSeconds;
    }
GetLastUAMessage()
string ManBase::GetLastUAMessage () inline private
UA Last Message.
Definition at line 7507 of file playerbase.c.
    {
        return m_UALastMessage;
    }
GetLifeSpanState()
int ManBase::GetLifeSpanState () inline private
Definition at line 6479 of file playerbase.c.
    {
        return m_LifeSpanState;
    }
GetLiquidTendencyDrain()
bool ManBase::GetLiquidTendencyDrain () inline private
Definition at line 4506 of file playerbase.c.
    {
        return m_LiquidTendencyDrain;
    }
GetLocalProjectionOrientation()
vector ManBase::GetLocalProjectionOrientation () inline private
Definition at line 2250 of file playerbase.c.
    {
        return m_LocalProjectionOrientation;
    }
GetLocalProjectionPosition()
vector ManBase::GetLocalProjectionPosition () inline private
Definition at line 2245 of file playerbase.c.
    {
        return m_LocalProjectionPosition;
    }
GetMagazineToReload()
EntityAI ManBase::GetMagazineToReload (EntityAI weapon) inline private
Definition at line 4407 of file playerbase.c.
    {
        Weapon_Base weapon_base = Weapon_Base.Cast( weapon );
        WeaponManager weapon_manager = GetWeaponManager();
        EntityAI magazine_to_reload;
        EntityAI ammo_magazine;             //magazine
        int last_ammo_magazine_count;
        int ammo_magazine_count;
        EntityAI ammo_pile;                 //ammo pile
        int last_ammo_pile_count;
        int ammo_pile_count;
        //Get all magazines in (player) inventory
        for ( int att_i = 0; att_i < GetInventory().AttachmentCount(); ++att_i )
        {
            EntityAI attachment = GetInventory().GetAttachmentFromIndex( att_i );
            ref CargoBase attachment_cargo = attachment.GetInventory().GetCargo();
            if ( attachment_cargo )
            {
                for ( int cgo_i = 0; cgo_i < attachment_cargo.GetItemCount(); ++cgo_i )
                {
                    EntityAI cargo_item = attachment_cargo.GetItem( cgo_i );
                    //check for proper magazine
                    if ( cargo_item.IsMagazine() )
                    {
                        Magazine magazine = Magazine.Cast( cargo_item );
                        ammo_pile_count = magazine.GetAmmoCount();
                        //magazines (get magazine with max ammo count)
                        if ( weapon_manager.CanAttachMagazine( weapon_base, magazine ) || weapon_manager.CanSwapMagazine( weapon_base, magazine ) )
{
                            if ( ammo_pile_count > 0 )
{
                                if ( last_ammo_magazine_count == 0 )
{
                                    ammo_magazine = magazine;
                                    last_ammo_magazine_count = ammo_pile_count;
                                }
                                else
{
                                    if ( last_ammo_magazine_count < ammo_pile_count )
{
                                        ammo_magazine = magazine;
                                        last_ammo_magazine_count = ammo_pile_count;
                                    }
                                }
                            }
                        }
                        //bullets (get ammo pile with min ammo count)
                        else if ( weapon_manager.CanLoadBullet( weapon_base, magazine ) )
{
                            if ( ammo_pile_count > 0 )
{
                                if ( last_ammo_pile_count == 0 )
{
                                    ammo_pile = magazine;
                                    last_ammo_pile_count = ammo_pile_count;
                                }
                                else
{
                                    if ( last_ammo_pile_count > ammo_pile_count )
{
                                        ammo_pile = magazine;
                                        last_ammo_pile_count = ammo_pile_count;
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
        //prioritize magazine
        if ( ammo_magazine )
        {
            return ammo_magazine;
        }
        return ammo_pile;
    }
References WeaponManager::CanAttachMagazine(), WeaponManager::CanLoadBullet(), WeaponManager::CanSwapMagazine(), and GetWeaponManager().
GetMapClosingSyncSent()
bool ManBase::GetMapClosingSyncSent () inline private
Definition at line 2958 of file playerbase.c.
    {
        return m_MapClosingSyncSent;
    }
GetMapNavigationBehaviour()
MapNavigationBehaviour ManBase::GetMapNavigationBehaviour () inline private
Definition at line 2987 of file playerbase.c.
    {
        return m_MapNavigationBehaviour;
    }
GetMixedSoundStates()
eMixedSoundStates ManBase::GetMixedSoundStates () inline private
Definition at line 1899 of file playerbase.c.
    {
        return m_MixedSoundStates;
    }
GetModifiersManager()
ModifiersManager ManBase::GetModifiersManager () inline private
Definition at line 7396 of file playerbase.c.
    {
        return m_ModifiersManager;
    }
GetNoisePresenceInAI()
int ManBase::GetNoisePresenceInAI () inline private
Return actual noise presence of player.
Definition at line 6568 of file playerbase.c.
    {
        if (m_PresenceNotifier)
        {
            return m_PresenceNotifier.GetNoisePresence();
        }
        return 0;
    }
GetNotifiersManager()
NotifiersManager ManBase::GetNotifiersManager () inline private
Definition at line 2559 of file playerbase.c.
    {
        return m_NotifiersManager;
    }
GetNVType()
int ManBase::GetNVType () inline private
Definition at line 8420 of file playerbase.c.
    {
        if (!m_ActiveNVTypes || m_ActiveNVTypes.Count() == 0)
        {
            return NVTypes.NONE;
        }
        else
        {
            return m_ActiveNVTypes[m_ActiveNVTypes.Count() - 1];
        }
    }
GetNVTypesArray()
array< int > ManBase::GetNVTypesArray () inline private
Definition at line 8432 of file playerbase.c.
    {
        return m_ActiveNVTypes;
    }
GetPlayerClass()
string ManBase::GetPlayerClass () inline private
Definition at line 6348 of file playerbase.c.
    {
        string type;
        GetGame().ObjectGetType( this, type );
        return type;
    }
References GetGame(), and CGame::ObjectGetType().
GetPlayerLoad()
float ManBase::GetPlayerLoad () inline private
Definition at line 4535 of file playerbase.c.
    {
        return m_CargoLoad;
    }
GetPlayerSoundEventHandler()
PlayerSoundEventHandler ManBase::GetPlayerSoundEventHandler () inline private
Definition at line 7087 of file playerbase.c.
    {
        return m_PlayerSoundEventHandler;
    }
References m_PlayerSoundEventHandler.
GetPlayerSoundManagerServer()
PlayerSoundManagerServer ManBase::GetPlayerSoundManagerServer () inline private
Definition at line 1161 of file playerbase.c.
    {
        return m_PlayerSoundManagerServer;
    }
GetPlayerStats()
PlayerStats ManBase::GetPlayerStats () inline private
Definition at line 1550 of file playerbase.c.
    {
        return m_PlayerStats;
    }
References m_PlayerStats.
GetPulseType()
EPulseType ManBase::GetPulseType () inline private
Definition at line 682 of file playerbase.c.
    {
        return m_PulseType;
    }
GetQuickBarBonus()
override int ManBase::GetQuickBarBonus () inline private
Definition at line 559 of file playerbase.c.
    {
        return m_QuickBarBonus;
    }
References m_QuickBarBonus.
GetQuickBarEntity()
EntityAI ManBase::GetQuickBarEntity (int index) inline private
Definition at line 1804 of file playerbase.c.
    {
        return m_QuickBarBase.GetEntity(index);
    }
GetQuickBarSize()
int ManBase::GetQuickBarSize () inline private
Definition at line 1799 of file playerbase.c.
    {
        return m_QuickBarBase.GetSize();
    }
GetRandomGeneratorSyncManager()
RandomGeneratorSyncManager ManBase::GetRandomGeneratorSyncManager () inline private
Definition at line 1384 of file playerbase.c.
    {
        return m_RGSManager;
    }
GetShakeLevel()
int ManBase::GetShakeLevel () inline private
Definition at line 4681 of file playerbase.c.
    {
        return m_Shakes;
    }
GetShockEffect()
ShockDealtEffect ManBase::GetShockEffect () inline private
Definition at line 756 of file playerbase.c.
    {
        return m_ShockDealtEffect;
    }
GetSimplifiedShockNormalized()
float ManBase::GetSimplifiedShockNormalized () inline private
Definition at line 3209 of file playerbase.c.
    {
        return (m_ShockSimplified / SIMPLIFIED_SHOCK_CAP);
    }
GetSingleAgentCount()
int ManBase::GetSingleAgentCount (int agent_id) inline private
Definition at line 7340 of file playerbase.c.
    {
        return m_AgentPool.GetSingleAgentCount(agent_id);
    }
GetSingleAgentCountNormalized()
float ManBase::GetSingleAgentCountNormalized (int agent_id) inline private
Definition at line 7346 of file playerbase.c.
    {
        int max_count = PluginTransmissionAgents.GetAgentMaxCount(agent_id);
        return m_AgentPool.GetSingleAgentCount(agent_id) / max_count;
    }
GetSoftSkillsManager()
SoftSkillsManager ManBase::GetSoftSkillsManager () inline private
Definition at line 6547 of file playerbase.c.
    {
        return m_SoftSkillsManager;
    }
GetStaminaHandler()
StaminaHandler ManBase::GetStaminaHandler () inline private
Definition at line 1560 of file playerbase.c.
    {
        return m_StaminaHandler;
    }
References m_StaminaHandler.
GetStaminaState()
int ManBase::GetStaminaState () inline private
Definition at line 7261 of file playerbase.c.
    {
        return m_StaminaState;
    }
GetStatBloodType()
PlayerStat< int > ManBase::GetStatBloodType () inline private
Definition at line 7482 of file playerbase.c.
    {
        if( !m_StatBloodType && GetPlayerStats() )
        {
            m_StatBloodType = PlayerStat<int>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.BLOODTYPE));
        }
        return m_StatBloodType;
    }
References GetStatObject().
GetStatBordersBlood()
float ManBase::GetStatBordersBlood () inline private
Definition at line 4784 of file playerbase.c.
    {
        float blood = GetHealth("","Blood");
        float blood_max = GetMaxHealth("","Blood");
        return GetStatLevelBorders(blood, PlayerConstants.SL_BLOOD_CRITICAL, PlayerConstants.SL_BLOOD_LOW, PlayerConstants.SL_BLOOD_NORMAL, PlayerConstants.SL_BLOOD_HIGH, blood_max);
    }
References GetHealth(), GetMaxHealth(), PlayerConstants::SL_BLOOD_CRITICAL, PlayerConstants::SL_BLOOD_HIGH, PlayerConstants::SL_BLOOD_LOW, and PlayerConstants::SL_BLOOD_NORMAL.
GetStatBordersEnergy()
float ManBase::GetStatBordersEnergy () inline private
Definition at line 4791 of file playerbase.c.
    {
        float energy = GetStatEnergy().Get();
        float energy_max = GetStatEnergy().GetMax();
        return GetStatLevelBorders(energy, PlayerConstants.SL_ENERGY_CRITICAL, PlayerConstants.SL_ENERGY_LOW, PlayerConstants.SL_ENERGY_NORMAL, PlayerConstants.SL_ENERGY_HIGH, energy_max);
    }
References PlayerConstants::SL_ENERGY_CRITICAL, PlayerConstants::SL_ENERGY_HIGH, PlayerConstants::SL_ENERGY_LOW, and PlayerConstants::SL_ENERGY_NORMAL.
GetStatBordersHealth()
float ManBase::GetStatBordersHealth () inline private
Definition at line 4770 of file playerbase.c.
    {
        float health = GetHealth("","");
        float health_max = GetMaxHealth("","");
        return GetStatLevelBorders(health, PlayerConstants.SL_HEALTH_CRITICAL, PlayerConstants.SL_HEALTH_LOW, PlayerConstants.SL_HEALTH_NORMAL, PlayerConstants.SL_HEALTH_HIGH, health_max);
    }
References GetHealth(), GetMaxHealth(), PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatBordersToxicity()
float ManBase::GetStatBordersToxicity () inline private
Definition at line 4777 of file playerbase.c.
    {
        float toxicity = GetStatToxicity().Get();
        float toxicity_max = GetStatToxicity().GetMax();
        return GetStatLevelBorders(toxicity, PlayerConstants.SL_HEALTH_CRITICAL, PlayerConstants.SL_HEALTH_LOW, PlayerConstants.SL_HEALTH_NORMAL, PlayerConstants.SL_HEALTH_HIGH, toxicity_max);
    }
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatBordersWater()
float ManBase::GetStatBordersWater () inline private
Definition at line 4798 of file playerbase.c.
    {
        float water = GetStatWater().Get();
        float water_max = GetStatWater().GetMax();
        return GetStatLevelBorders(water, PlayerConstants.SL_WATER_CRITICAL, PlayerConstants.SL_WATER_LOW, PlayerConstants.SL_WATER_NORMAL, PlayerConstants.SL_WATER_HIGH, water_max);
    }
References PlayerConstants::SL_WATER_CRITICAL, PlayerConstants::SL_WATER_HIGH, PlayerConstants::SL_WATER_LOW, and PlayerConstants::SL_WATER_NORMAL.
GetStatDiet()
PlayerStat< float > ManBase::GetStatDiet () inline private
Definition at line 7455 of file playerbase.c.
    {
        if( !m_StatDiet && GetPlayerStats() )
        {
            m_StatDiet = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.DIET));
        }
        return m_StatDiet;
    }
References GetStatObject().
GetStatEnergy()
PlayerStat< float > ManBase::GetStatEnergy () inline private
Definition at line 7419 of file playerbase.c.
    {
        if( !m_StatEnergy && GetPlayerStats() )
        {
            m_StatEnergy = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.ENERGY));
        }
        return m_StatEnergy;
    }
References GetStatObject().
GetStatHeatBuffer()
PlayerStat< float > ManBase::GetStatHeatBuffer () inline private
Definition at line 7491 of file playerbase.c.
    {
        if( !m_StatHeatBuffer && GetPlayerStats() )
        {
            m_StatHeatBuffer = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.HEATBUFFER));
        }
        return m_StatHeatBuffer;
    }
References GetStatObject().
GetStatHeatComfort()
PlayerStat< float > ManBase::GetStatHeatComfort () inline private
Definition at line 7428 of file playerbase.c.
    {
        if( !m_StatHeatComfort && GetPlayerStats() )
        {
            m_StatHeatComfort = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.HEATCOMFORT));
        }
        return m_StatHeatComfort;
    }
References GetStatObject().
GetStatLevel()
EStatLevels ManBase::GetStatLevel (float stat_value, float critical, float low, float normal, float high) inline private
Definition at line 4828 of file playerbase.c.
    {
        if(stat_value <= critical)
        {
            return EStatLevels.CRITICAL;
        }
        if(stat_value <= low)
        {
            return EStatLevels.LOW;
        }
        if(stat_value <= normal)
        {
            return EStatLevels.MEDIUM;
        }
        if(stat_value <= high)
        {
            return EStatLevels.HIGH;
        }
        return EStatLevels.GREAT;
    }
GetStatLevelBlood()
EStatLevels ManBase::GetStatLevelBlood () inline private
Definition at line 4699 of file playerbase.c.
    {
        float blood = GetHealth("","Blood");
        return GetStatLevel(blood, PlayerConstants.SL_BLOOD_CRITICAL, PlayerConstants.SL_BLOOD_LOW, PlayerConstants.SL_BLOOD_NORMAL, PlayerConstants.SL_BLOOD_HIGH);
    }
References GetHealth(), PlayerConstants::SL_BLOOD_CRITICAL, PlayerConstants::SL_BLOOD_HIGH, PlayerConstants::SL_BLOOD_LOW, and PlayerConstants::SL_BLOOD_NORMAL.
GetStatLevelBorders()
float ManBase::GetStatLevelBorders (float stat_value, float critical, float low, float normal, float high, float max) inline private
Definition at line 4807 of file playerbase.c.
    {
        if(stat_value <= critical)
        {
            return Math.InverseLerp(0, critical, stat_value);
        }
        if(stat_value <= low)
        {
            return Math.InverseLerp(critical, low, stat_value);
        }
        if(stat_value <= normal)
        {
            return Math.InverseLerp(low, normal, stat_value);
        }
        if(stat_value <= high)
        {
            return Math.InverseLerp(normal, high, stat_value);
        }
        return Math.InverseLerp(high, max, stat_value);
    }
References Math::InverseLerp().
GetStatLevelEnergy()
EStatLevels ManBase::GetStatLevelEnergy () inline private
Definition at line 4705 of file playerbase.c.
    {
        float energy = GetStatEnergy().Get();
        return GetStatLevel(energy, PlayerConstants.SL_ENERGY_CRITICAL, PlayerConstants.SL_ENERGY_LOW, PlayerConstants.SL_ENERGY_NORMAL, PlayerConstants.SL_ENERGY_HIGH);
    }
References PlayerConstants::SL_ENERGY_CRITICAL, PlayerConstants::SL_ENERGY_HIGH, PlayerConstants::SL_ENERGY_LOW, and PlayerConstants::SL_ENERGY_NORMAL.
GetStatLevelHealth()
EStatLevels ManBase::GetStatLevelHealth () inline private
Definition at line 4687 of file playerbase.c.
    {
        float health = GetHealth("","");
        return GetStatLevel(health, PlayerConstants.SL_HEALTH_CRITICAL, PlayerConstants.SL_HEALTH_LOW, PlayerConstants.SL_HEALTH_NORMAL, PlayerConstants.SL_HEALTH_HIGH);
    }
References GetHealth(), PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatLevelToxicity()
EStatLevels ManBase::GetStatLevelToxicity () inline private
Definition at line 4693 of file playerbase.c.
    {
        float toxicity = GetStatToxicity().Get();
        return GetStatLevel(toxicity, PlayerConstants.SL_HEALTH_CRITICAL, PlayerConstants.SL_HEALTH_LOW, PlayerConstants.SL_HEALTH_NORMAL, PlayerConstants.SL_HEALTH_HIGH);
    }
References PlayerConstants::SL_HEALTH_CRITICAL, PlayerConstants::SL_HEALTH_HIGH, PlayerConstants::SL_HEALTH_LOW, and PlayerConstants::SL_HEALTH_NORMAL.
GetStatLevelWater()
EStatLevels ManBase::GetStatLevelWater () inline private
Definition at line 4711 of file playerbase.c.
    {
        float water = GetStatWater().Get();
        return GetStatLevel(water, PlayerConstants.SL_WATER_CRITICAL, PlayerConstants.SL_WATER_LOW, PlayerConstants.SL_WATER_NORMAL, PlayerConstants.SL_WATER_HIGH);
    }
References PlayerConstants::SL_WATER_CRITICAL, PlayerConstants::SL_WATER_HIGH, PlayerConstants::SL_WATER_LOW, and PlayerConstants::SL_WATER_NORMAL.
GetStatSpecialty()
PlayerStat< float > ManBase::GetStatSpecialty () inline private
Definition at line 7473 of file playerbase.c.
    {
        if( !m_StatSpecialty && GetPlayerStats() )
        {
            m_StatSpecialty = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.SPECIALTY));
        }
        return m_StatSpecialty;
    }
References GetStatObject().
GetStatStamina()
PlayerStat< float > ManBase::GetStatStamina () inline private
Definition at line 7464 of file playerbase.c.
    {
        if( !m_StatStamina && GetPlayerStats() )
        {
            m_StatStamina = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.STAMINA));
        }
        return m_StatStamina;
    }
References GetStatObject().
GetStatToxicity()
PlayerStat< float > ManBase::GetStatToxicity () inline private
Definition at line 7410 of file playerbase.c.
    {
        if( !m_StatToxicity && GetPlayerStats() )
        {
            m_StatToxicity = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.TOXICITY));
        }
        return m_StatToxicity;
    }
References GetStatObject().
GetStatTremor()
PlayerStat< float > ManBase::GetStatTremor () inline private
Definition at line 7437 of file playerbase.c.
    {
        if( !m_StatTremor && GetPlayerStats() )
        {
            m_StatTremor = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.TREMOR));
        }
        return m_StatTremor;
    }
References GetStatObject().
GetStatWater()
PlayerStat< float > ManBase::GetStatWater () inline private
Definition at line 7401 of file playerbase.c.
    {
        if( !m_StatWater && GetPlayerStats())
        {
            m_StatWater = PlayerStat<float>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.WATER));
        }
        return m_StatWater;
    }
References GetStatObject().
GetStatWet()
PlayerStat< int > ManBase::GetStatWet () inline private
Definition at line 7446 of file playerbase.c.
    {
        if( !m_StatWet && GetPlayerStats() )
        {
            m_StatWet = PlayerStat<int>.Cast(GetPlayerStats().GetStatObject(EPlayerStats_current.WET));
        }
        return m_StatWet;
    }
References GetStatObject().
GetStomach()
PlayerStomach ManBase::GetStomach () inline private
Definition at line 2624 of file playerbase.c.
    {
        return m_PlayerStomach;
    }
GetStoreLoadVersion()
int ManBase::GetStoreLoadVersion () inline private
Definition at line 6596 of file playerbase.c.
    {
        return m_StoreLoadVersion;
    }
GetSuitableFinisherHitComponents()
override array< string > ManBase::GetSuitableFinisherHitComponents () inline private
returns list of suitable finisher hit components (defined on base entity/entity type)
Definition at line 962 of file playerbase.c.
    {
        return GetDayZPlayerType().GetSuitableFinisherHitComponents();
    }
References GetDayZPlayerType().
GetSymptomManager()
SymptomManager ManBase::GetSymptomManager () inline private
Definition at line 2315 of file playerbase.c.
    {
        return m_SymptomManager;
    }
GetTotalAgentCount()
float ManBase::GetTotalAgentCount () inline private
Definition at line 7352 of file playerbase.c.
    {
        return m_AgentPool.GetTotalAgentCount();
    }
GetTransferValues()
TransferValues ManBase::GetTransferValues () inline private
Definition at line 2328 of file playerbase.c.
    {
        return m_TrasferValues;
    }
GetUndergroundHandler()
UndergroundHandlerClient ManBase::GetUndergroundHandler () inline private
Definition at line 1167 of file playerbase.c.
    {
        if (!m_UndergroundHandler && IsAlive())
        {
            m_UndergroundHandler = new UndergroundHandlerClient(this);
        }
        return m_UndergroundHandler;
    }
References IsAlive(), and UndergroundHandlerClient().
GetVirtualHud()
VirtualHud ManBase::GetVirtualHud () inline private
Definition at line 2319 of file playerbase.c.
    {
        if ( !m_VirtualHud )
        {
            m_VirtualHud = new VirtualHud(this);
        }
        return m_VirtualHud;
    }
References m_VirtualHud, and VirtualHud().
GetVisibilityCoef()
float ManBase::GetVisibilityCoef () inline private
Definition at line 4675 of file playerbase.c.
    {
        return m_VisibilityCoef;
    }
GetVoiceType()
int ManBase::GetVoiceType () inline private
Definition at line 1149 of file playerbase.c.
    {
        int voice_type = ConfigGetInt("voiceType");
        if (voice_type == 0)
        {
            voice_type = 1;
        }
        return voice_type;
    }
References ConfigGetInt().
GetWeaponManager()
override WeaponManager ManBase::GetWeaponManager () inline private
Definition at line 1565 of file playerbase.c.
    {
        return m_WeaponManager;
    }
GiveShock()
void ManBase::GiveShock (float shock) inline private
Definition at line 3231 of file playerbase.c.
    {
        AddHealth("","Shock",shock);
    }
References AddHealth().
HandleBrokenLegsSync()
void ManBase::HandleBrokenLegsSync () inline private
Definition at line 5553 of file playerbase.c.
    {
        if (m_BrokenLegState != m_LocalBrokenState)
        {
            m_LocalBrokenState = m_BrokenLegState;
            bool initial = (m_BrokenLegState < 0);
            int state = GetBrokenLegs();
            if ( state == eBrokenLegs.BROKEN_LEGS )
            {
                //Print(m_BrokenLegState);
                if (initial)// <0 values indicate initial activation
                {
                    //Print("synced variables - inital activation of broken legs");
                    BreakLegSound();
                }
                else
                {
                    //Print("synced variables - secondary activation of broken legs");
                }
            }
        }
    }
HandleGlassesEffect()
void ManBase::HandleGlassesEffect () inline private
Definition at line 8904 of file playerbase.c.
    {
        if (!IsControlledPlayer())
            return;
        int i;
        if (m_ProcessRemoveGlassesEffects)
        {
            for (i = 0; i < m_ProcessRemoveGlassesEffects.Count(); i++)
            {
                PPERequesterBank.GetRequester(m_ProcessRemoveGlassesEffects[i]).Stop();
            }
            m_ProcessRemoveGlassesEffects.Clear();
        }
        if (m_ProcessAddGlassesEffects)
        {
            for (i = 0; i < m_ProcessAddGlassesEffects.Count(); i++)
            {
                PPERequesterBank.GetRequester(m_ProcessAddGlassesEffects[i]).Start();
            }
            m_ProcessAddGlassesEffects.Clear();
        }
    }
HandleRemoteItemManipulation()
bool ManBase::HandleRemoteItemManipulation (int userDataType, ParamsReadContext ctx) inline private
Definition at line 5871 of file playerbase.c.
    {
        if( userDataType == INPUT_UDT_ITEM_MANIPULATION )
        {
            int type = -1;
            ItemBase item1 = null;
            ItemBase item2 = null;
            bool use_stack_max = false;
            int slot_id = -1;
            if (!ctx.Read(type))
                return false;
            if (type == 4)
            {
                if (!ctx.Read(item1))
                    return false;
                InventoryLocation dst = new InventoryLocation;
                if (dst.ReadFromContext(ctx))
                {
                    //Print(InventoryLocation.DumpToStringNullSafe(dst));
                    bool dummy;
                    if (ctx.Read(dummy))
                        item1.SplitItemToInventoryLocation(dst);
                    else
                        item1.SplitIntoStackMaxToInventoryLocation(dst);
                    return true;
                }
                return false;
            }
            if (!ctx.Read(item1))
                return false;
            if (!ctx.Read(item2))
                return false;
            if (!ctx.Read(use_stack_max))
                return false;
            if (!ctx.Read(slot_id))
                return false;
            if ( type == -1 && item1 && item2 )//combine
            {
                item1.CombineItems( item2, use_stack_max );
            }
            else if ( type == 1 && item1 )
            {
                if ( use_stack_max )
                    item1.SplitIntoStackMax(item2, slot_id, this);
                else
                    item1.SplitItem(this);
            }
            else if ( type == 2 && item1 )
            {
                int row, col;
                if ( !ctx.Read( row ) )
                    return false;
                if ( !ctx.Read( col ) )
                    return false;
                item1.SplitIntoStackMaxCargo( item2, slot_id, row, col );
            }
            else if ( type == 3 && item1 )
            {
                item1.SplitIntoStackMaxHands( this );
            }
            return true;
        }
        return false;
    }
References INPUT_UDT_ITEM_MANIPULATION, Serializer::Read(), and InventoryLocation::ReadFromContext().
HasBloodTypeVisible()
bool ManBase::HasBloodTypeVisible () inline private
Definition at line 6521 of file playerbase.c.
    {
        return m_HasBloodTypeVisible;
    }
HasBloodyHands()
bool ManBase::HasBloodyHands () inline private
Definition at line 6499 of file playerbase.c.
    {
        return m_HasBloodyHandsVisible;
    }
HasBloodyHandsEx()
eBloodyHandsTypes ManBase::HasBloodyHandsEx () inline private
Definition at line 6494 of file playerbase.c.
    {
        return m_HasBloodyHandsVisible;
    }
HasDisease()
bool ManBase::HasDisease () inline private
Definition at line 676 of file playerbase.c.
    {
        return m_DiseaseCount;//0 for no disease, 1+ for disease, gets truncated to 1
    }
HasHealings()
bool ManBase::HasHealings () inline private
Definition at line 671 of file playerbase.c.
    {
        return m_HealingsCount;//0 for no healings, 1+ for healings, gets truncated to 1
    }
HasStaminaRemaining()
bool ManBase::HasStaminaRemaining () inline private
DEPRECATED.
Definition at line 4001 of file playerbase.c.
    {
        if (!GetStaminaHandler())
            return false;
        return GetStaminaHandler().GetStamina() > 0;
    }
HeadingModel()
override bool ManBase::HeadingModel (float pDt, SDayZPlayerHeadingModel pModel) inline private
during fullbody gestures - disables character turning
Definition at line 7722 of file playerbase.c.
    {
        if ( GetEmoteManager().IsControllsLocked() || (GetActionManager() && GetActionManager().GetRunningAction() && GetActionManager().GetRunningAction().IsFullBody(this)) )
        {
            m_fLastHeadingDiff = 0;
            return DayZPlayerImplementHeading.ClampHeading(pDt, pModel, m_fLastHeadingDiff);
        }
        return super.HeadingModel(pDt, pModel);
    }
References DayZPlayerImplementHeading::ClampHeading(), GetActionManager(), GetRunningAction(), IsControllsLocked(), IsFullBody(), and m_fLastHeadingDiff.
HideClothing()
override void ManBase::HideClothing (ItemOptics optic, bool state) inline private
Definition at line 7852 of file playerbase.c.
    {
        super.HideClothing(optic, state);
        array<int> clothingArray = new array<int>;
        Clothing clothes;
        if (state && DayZPlayerCameraOptics.Cast(m_CurrentCamera))
        {
            if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
            {
                clothingArray.Insert(InventorySlots.BACK);
                clothingArray.Insert(InventorySlots.SHOULDER);
                clothingArray.Insert(InventorySlots.MELEE);
                if(optic.GetCurrentStepFOV() < GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS/*0.5*/ )
                {
                    clothingArray.Insert(InventorySlots.BODY);
                    clothingArray.Insert(InventorySlots.VEST);
                }
                SetInvisibleRecursive(true,this,clothingArray);
            }
        }
        //showing should be instant (called directly, not via CallLater)
        else
        {
            if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
            {
                /*for(int i = 0; i < GetInventory().AttachmentCount(); i++)
                {
                    Print("attachment slot ID: " + GetInventory().GetAttachmentSlotId(i));
                    clothingArray.Insert(GetInventory().GetAttachmentSlotId(i));
                }*/
                clothingArray = {InventorySlots.BACK,InventorySlots.BODY,InventorySlots.VEST,InventorySlots.SHOULDER,InventorySlots.MELEE};
                SetInvisibleRecursive(false,this,clothingArray);
            }
        }
    }
References DayZPlayerCameraOptics(), GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, and GetInstanceType().
HideHairSelections()
void ManBase::HideHairSelections (ItemBase item, bool state) inline private
Definition at line 8303 of file playerbase.c.
    {
        if ( !item || !item.GetHeadHidingSelection() || !m_CharactersHead)
            return;
        int slot_id; //item currently attached (or detaching from) here
        string slot_name; //item currently attached (or detaching from) here
        string str
        int idx;
        int i;
        item.GetInventory().GetCurrentAttachmentSlotInfo(slot_id,slot_name);
        if (item.HidesSelectionBySlot())
        {
            for (i = 0; i < item.GetInventory().GetSlotIdCount(); i++)
            {
                if (item.GetInventory().GetSlotId(i) == slot_id)
                {
                    str = item.GetHeadHidingSelection().Get(i);
                    idx = m_CharactersHead.m_HeadHairSelectionArray.Find(str);
                    SetHairLevelToHide(idx,state);
                }
            }
        }
        else
        {
            for (i = 0; i < item.GetHeadHidingSelection().Count(); i++)
            {
                str = item.GetHeadHidingSelection().Get(i);
                idx = m_CharactersHead.m_HeadHairSelectionArray.Find(str);
                SetHairLevelToHide(idx,state);
            }
        }
        UpdateHairSelectionVisibility();
    }
References Count, and GetSlotIdCount().
ImmuneSystemTick()
void ManBase::ImmuneSystemTick (float value, float deltaT) inline private
Definition at line 7362 of file playerbase.c.
    {
        m_AgentPool.ImmuneSystemTick(value, deltaT);
    }
IncreaseAntibioticsCount()
void ManBase::IncreaseAntibioticsCount () inline private
Definition at line 514 of file playerbase.c.
    {
        m_AntibioticsActive++;
    }
IncreaseDiseaseCount()
void ManBase::IncreaseDiseaseCount () inline private
Definition at line 650 of file playerbase.c.
    {
        m_DiseaseCount++;
    }
IncreaseHealingsCount()
void ManBase::IncreaseHealingsCount () inline private
Definition at line 660 of file playerbase.c.
    {
        m_HealingsCount++;
    }
Init()
void ManBase::Init () inline private
sets default hit position and cache it here (mainly for impact particles)
Definition at line 281 of file playerbase.c.
    {
        //Print("PSOVIS: new player");
        //PrintString( "isServer " + GetGame().IsServer().ToString() );
        //PrintString( "isClient " + GetGame().IsClient().ToString() );
        //PrintString( "isMultiplayer " + GetGame().IsMultiplayer().ToString() );
        SetEventMask(EntityEvent.INIT|EntityEvent.POSTFRAME|EntityEvent.FRAME);
        //m_Agents = new array<int>; //transmission agents
        m_StoreLoadVersion = 0;
        m_IsCraftingReady = false;
        m_Recipes = new array<int>;
        m_LastShavedSeconds = 0;
        m_BloodType = 0;
        m_HasBloodTypeVisible = false;
        m_LifeSpanState = 0;
        m_LifespanLevelLocal = -1;
        m_CorpseState = 0;
        m_CorpseStateLocal = 0;
        m_HasBloodyHandsVisible = 0;
        m_PlayerLoaded = false;
        m_PlayerSelected = false;
        m_ProcessUIWarning = false;
        m_FlagRaisingTendency = true;
        m_LiquidTendencyDrain = false;
        m_UAParamMessage = new Param1<string>("");
        m_UnconParam = new Param1<float>(0);
        m_DeathDarkeningParam = new Param1<float>(0);
        m_UAParam = new Param2<int,int>(0,0);
        m_UAProgressParam = new Param2<float,float>(0,0);
        m_QuickBarBase = new QuickBarBase(this);
        m_QuickBarBonus = Math.Max(ConfigGetInt("quickBarBonus"), 0);
        m_CargoLoad = 0;
        m_VisibilityCoef = 1.0;
        m_Hud = GetGame().GetMission().GetHud();
        m_RecipePick = 0;
        m_ActionQBControl = false;
        m_QuickBarHold = false;
        m_HideHairAnimated = true;
        m_WorkingNVGHeadset = false;
        m_LoweredNVGHeadset = false;
        m_AreHandsLocked = false;
        m_ItemsToDelete = new array<EntityAI>;
        m_AnimCommandStarting = HumanMoveCommandID.None;
        m_EmptyGloves = new HiddenSelectionsData(ConfigGetString("emptyGloves"));
        m_CanDisplayHitEffectPPE = true;
        #ifdef DEVELOPER
            m_CanBeTargetedDebug = true;
            //RegisterNetSyncVariableBool("m_CanBeTargetedDebug");
        #endif
        m_AnalyticsTimer = new Timer( CALL_CATEGORY_SYSTEM );
        m_StaminaHandler = new StaminaHandler(this);//current stamina calculation
        m_InjuryHandler = new InjuryAnimationHandler(this);
        m_ShockHandler = new ShockHandler(this); //New shock handler
        m_HCAnimHandler = new HeatComfortAnimHandler(this);
        m_PlayerStats = new PlayerStats(this);//player stats
        if( GetGame().IsServer() )
        {
            m_PlayerStomach = new PlayerStomach(this);
            m_NotifiersManager = new NotifiersManager(this); // player notifiers
            m_AgentPool = new PlayerAgentPool(this); // agent pool manager
            m_BleedingManagerServer = new BleedingSourcesManagerServer(this);
            m_Environment = new Environment(this);//environment effects on player
            m_ModifiersManager = new ModifiersManager(this); // player modifiers
            m_PlayerSoundManagerServer = new PlayerSoundManagerServer(this);
            m_VirtualHud = new VirtualHud(this);
            m_AdminLog              = PluginAdminLog.Cast( GetPlugin(PluginAdminLog) );
        }
        m_SymptomManager = new SymptomManager(this); // state manager
        m_ModuleRecipesManager = PluginRecipesManager.Cast(GetPlugin(PluginRecipesManager));
        m_TrasferValues = new TransferValues(this);
        m_EmoteManager = new EmoteManager(this);
        m_SoftSkillsManager = new SoftSkillsManager(this);//Soft Skills calculation
        m_WeaponManager = new WeaponManager(this);
        m_DebugMonitorValues = new DebugMonitorValues(this);
        m_RGSManager = new RandomGeneratorSyncManager(this);
        if( !GetGame().IsDedicatedServer() )
        {
            m_MeleeDebug = false;
            m_UALastMessage = "";
            m_UALastMessageTimer = new Timer;
            m_InventoryActionHandler = new InventoryActionHandler(this);
            m_BleedingManagerRemote = new BleedingSourcesManagerRemote(this);
            m_PlayerSoundManagerClient = new PlayerSoundManagerClient(this);
            m_StanceIndicator = new StanceIndicator(this);
            m_ActionsInitialize = false;
            ClientData.AddPlayerBase( this );
            m_ProcessAddEffectWidgets = new array<int>;
            m_ProcessRemoveEffectWidgets = new array<int>;
            m_ActiveNVTypes = new array<int>;
            m_ProcessAddGlassesEffects = new array<int>;
            m_ProcessRemoveGlassesEffects = new array<int>;
        }
        m_ActionManager = NULL;
        //m_PlayerLightManager = NULL;
        //m_VehicleManager = new VehicleManager(this,m_ActionManager);
        m_ConfigEmotesProfile = PluginConfigEmotesProfile.Cast( GetPlugin(PluginConfigEmotesProfile) );
        if ( GetDayZGame().IsDebug() )
        {
            PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed = PluginConfigDebugProfileFixed.Cast( GetPlugin(PluginConfigDebugProfileFixed) );
            PluginConfigDebugProfile m_ConfigDebugProfile = PluginConfigDebugProfile.Cast( GetPlugin(PluginConfigDebugProfile) );
            PluginDeveloper m_Developer = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
            PlayerBase player = this;
            if( m_ConfigDebugProfile )
            {
                string default_preset = m_ConfigDebugProfile.GetDefaultPreset();
                if ( player && default_preset != "" )
                {
                    TStringArray preset_array = new TStringArray;
                    m_ConfigDebugProfileFixed.GetPresetItems( default_preset, preset_array );
                    bool is_preset_fixed = true;
                    if ( preset_array.Count() == 0 )
                    {
                        m_ConfigDebugProfile.GetPresetItems( default_preset, preset_array );
                        is_preset_fixed = false;
                    }
                    if ( preset_array.Count() > 0 )
                    {
                        m_Developer.ClearInventory(player);
                        for (int i = 0; i < preset_array.Count(); i++)
{
                            float health = -1;
                            int quantity = -1;
                            if ( is_preset_fixed )
{
                                health = m_ConfigDebugProfileFixed.GetItemHealth( default_preset, i );
                                quantity = m_ConfigDebugProfileFixed.GetItemQuantity( default_preset, i );
                            }
                            else
{
                                health = m_ConfigDebugProfile.GetItemHealth( default_preset, i );
                                quantity = m_ConfigDebugProfile.GetItemQuantity( default_preset, i );
                            }
                            m_Developer.SpawnEntityInInventory(player, preset_array.Get(i), health, quantity );
                        }
                    }
                }
            }
        }
        m_MapNavigationBehaviour            = new MapNavigationBehaviour(this);
        m_ModulePlayerStatus    = PluginPlayerStatus.Cast( GetPlugin(PluginPlayerStatus) );
        m_ModuleLifespan        = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
        m_BleedingSourcesLow = new array<string>;
        m_BleedingSourcesLow.Insert("RightToeBase");
        m_BleedingSourcesLow.Insert("RightFoot");
        m_BleedingSourcesLow.Insert("LeftToeBase");
        m_BleedingSourcesLow.Insert("LeftFoot");
        m_BleedingSourcesLow.Insert("RightUpLegRoll");
        m_BleedingSourcesLow.Insert("RightUpLeg");
        m_BleedingSourcesLow.Insert("RightLegRoll");
        m_BleedingSourcesLow.Insert("RightLeg");
        m_BleedingSourcesLow.Insert("LeftUpLegRoll");
        m_BleedingSourcesLow.Insert("LeftUpLeg");
        m_BleedingSourcesLow.Insert("LeftLegRoll");
        m_BleedingSourcesLow.Insert("LeftLeg");
        m_BleedingSourcesUp = new array<string>;
        m_BleedingSourcesUp.Insert("RightForeArmRoll");
        m_BleedingSourcesUp.Insert("LeftForeArmRoll");
        m_BleedingSourcesUp.Insert("RightForeArm");
        m_BleedingSourcesUp.Insert("RightArmRoll");
        m_BleedingSourcesUp.Insert("RightArm");
        m_BleedingSourcesUp.Insert("RightShoulder");
        m_BleedingSourcesUp.Insert("LeftForeArm");
        m_BleedingSourcesUp.Insert("LeftArmRoll");
        m_BleedingSourcesUp.Insert("LeftArm");
        m_BleedingSourcesUp.Insert("LeftShoulder");
        m_BleedingSourcesUp.Insert("Spine3");
        m_BleedingSourcesUp.Insert("Spine2");
        m_BleedingSourcesUp.Insert("Spine1");
        m_BleedingSourcesUp.Insert("Spine");
        m_BleedingSourcesUp.Insert("Pelvis");
        m_BleedingSourcesUp.Insert("Neck");
        RegisterNetSyncVariableInt("m_LifeSpanState", LifeSpanState.BEARD_NONE, LifeSpanState.COUNT);
        RegisterNetSyncVariableInt("m_BloodType", 0, 128);
        RegisterNetSyncVariableInt("m_ShockSimplified",0, SIMPLIFIED_SHOCK_CAP);
        RegisterNetSyncVariableInt("m_SoundEvent",0, EPlayerSoundEventID.ENUM_COUNT - 1);
        RegisterNetSyncVariableInt("m_SoundEventParam", 0, ((EPlayerSoundEventParam.ENUM_COUNT - 1) * 2) - 1);
        RegisterNetSyncVariableInt("m_StaminaState",0, eStaminaState.COUNT - 1);
        RegisterNetSyncVariableInt("m_BleedingBits");
        RegisterNetSyncVariableInt("m_Shakes", 0, SHAKE_LEVEL_MAX);
        RegisterNetSyncVariableInt("m_BreathVapour", 0, BREATH_VAPOUR_LEVEL_MAX);
        RegisterNetSyncVariableInt("m_HealthLevel", eInjuryHandlerLevels.PRISTINE, eInjuryHandlerLevels.RUINED);
        RegisterNetSyncVariableInt("m_MixedSoundStates", 0, eMixedSoundStates.COUNT - 1);
        RegisterNetSyncVariableInt("m_CorpseState",-PlayerConstants.CORPSE_STATE_DECAYED,PlayerConstants.CORPSE_STATE_DECAYED);//do note the negative min, negative sign denotes a special meaning
        RegisterNetSyncVariableInt("m_RefreshAnimStateIdx",0,3);
        RegisterNetSyncVariableInt("m_BrokenLegState", -eBrokenLegs.BROKEN_LEGS_SPLINT, eBrokenLegs.BROKEN_LEGS_SPLINT);
        RegisterNetSyncVariableInt("m_SyncedModifiers", 0, ((eModifierSyncIDs.LAST_INDEX - 1) * 2) - 1);
        RegisterNetSyncVariableInt("m_HasBloodyHandsVisible", 0, eBloodyHandsTypes.LAST_INDEX - 1);
        RegisterNetSyncVariableBool("m_IsUnconscious");
        RegisterNetSyncVariableBool("m_IsRestrained");
        RegisterNetSyncVariableBool("m_IsInWater");
        RegisterNetSyncVariableBool("m_HasBloodTypeVisible");
        //RegisterNetSyncVariableBool("m_LiquidTendencyDrain");
        RegisterNetSyncVariableBool("m_IsRestrainStarted");
        RegisterNetSyncVariableBool("m_IsRestrainPrelocked");
        //RegisterNetSyncVariableBool("m_CanPlayBrokenLegSound"); //Temporary
        RegisterNetSyncVariableBool("m_HasHeatBuffer");
        RegisterNetSyncVariableFloat("m_CurrentShock"); //Register shock synchronized variable
        m_OriginalSlidePoseAngle = GetSlidePoseAngle();
        m_DefaultHitPosition = SetDefaultHitPosition(GetDayZPlayerType().GetDefaultHitPositionComponent());
        m_DecayedTexture = ConfigGetString("decayedTexture");
        m_FliesIndex = -1;
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(this.OnPlayerLoaded);
    }
References ClientData::AddPlayerBase(), BREATH_VAPOUR_LEVEL_MAX, ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, ConfigGetInt(), ConfigGetString(), PlayerConstants::CORPSE_STATE_DECAYED, EmoteManager(), CGame::GetCallQueue(), GetDayZGame(), GetDayZPlayerType(), GetDefaultHitPositionComponent(), GetGame(), Mission::GetHud(), CGame::GetMission(), GetPlugin(), GetSlidePoseAngle(), InjuryAnimationHandler(), m_ActionsInitialize, m_AdminLog, m_BloodType, m_Hud, m_ModulePlayerStatus, m_PlayerSelected, m_PlayerStats, m_QuickBarBonus, m_Recipes, m_StaminaHandler, m_VirtualHud, MapNavigationBehaviour(), Math::Max(), ModifiersManager(), NotifiersManager(), PlayerSoundManagerClient(), PlayerStomach(), PluginLifespan(), QuickBarBase(), RandomGeneratorSyncManager(), StaminaHandler(), and VirtualHud().
InitEditor()
void ManBase::InitEditor () inline private
Definition at line 1940 of file playerbase.c.
    {
        if ( GetGame().IsDebug() )
        {
            if ( !GetGame().IsMultiplayer()  &&  GetGame().GetPlayer()  &&  GetGame().GetPlayer().GetID() == this.GetID() )
            {
                PluginSceneManager scene_editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
                scene_editor.InitLoad();
            }
        }
    }
References GetGame(), GetID(), GetPlayer(), and GetPlugin().
InitializeActions()
void ManBase::InitializeActions () inline private
Definition at line 1251 of file playerbase.c.
    {
        // Backwards compatibility
        if (IsControlledPlayer())
        {
            m_InputActionMap = new TInputActionMap;
            SetActions();
        }
        else
        {
            m_InputActionMap = new TInputActionMap;
            SetActionsRemoteTarget();
        }
        m_InputActionMapControled = new TInputActionMap;
        SetActions(m_InputActionMapControled);
        m_InputActionMapAsTarget = new TInputActionMap;
        SetActionsRemoteTarget(m_InputActionMapAsTarget);
    }
References m_InputActionMap, and SetActions().
InsertAgent()
override void ManBase::InsertAgent (int agent, float count = 1) inline private
Definition at line 7334 of file playerbase.c.
    {
        m_AgentPool.AddAgent(agent,count);
    }
IsAntibioticsActive()
bool ManBase::IsAntibioticsActive () inline private
Definition at line 529 of file playerbase.c.
    {
        return (m_AntibioticsActive > 0);
    }
IsBleeding()
bool ManBase::IsBleeding () inline private
Definition at line 623 of file playerbase.c.
    {
        return (m_BleedingBits != 0 );
    }
IsClimbing()
bool ManBase::IsClimbing () inline private
Definition at line 4934 of file playerbase.c.
    {
        return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB;
    }
References m_MovementState.
IsClimbingLadder()
bool ManBase::IsClimbingLadder () inline private
Definition at line 4929 of file playerbase.c.
    {
        return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER;
    }
References m_MovementState.
IsCurrentCameraAimedAtGround()
bool ManBase::IsCurrentCameraAimedAtGround () inline private
Definition at line 2297 of file playerbase.c.
    {
        if (!m_CurrentCamera)
            return false;
        return m_CurrentCamera.GetCurrentPitch() < PlayerConstants.CAMERA_THRESHOLD_PITCH;
    }
References PlayerConstants::CAMERA_THRESHOLD_PITCH.
IsEmotePlaying()
bool ManBase::IsEmotePlaying () inline private
Definition at line 4954 of file playerbase.c.
    {
        if (m_EmoteManager)
        {
            return m_EmoteManager.IsEmotePlaying();
        }
        else
        {
            return false;
        }
    }
IsFacingTarget()
bool ManBase::IsFacingTarget (Object target) inline private
Definition at line 4137 of file playerbase.c.
    {
        vector pdir = GetDirection();
        vector ptv = target.GetPosition() - GetPosition();
        pdir.Normalize();
        ptv.Normalize();
        //MessageAction(ToString(pdir)+"  "+ToString(ptv)+"  ");
        if (Math.AbsFloat(pdir[0]-ptv[0]) < 0.5 && Math.AbsFloat(pdir[2]-ptv[2]) < 0.5 )
        {
            return true;
        }
        return false;
    }
References Math::AbsFloat(), GetDirection(), GetPosition, and vector::Normalize().
IsFalling()
bool ManBase::IsFalling () inline private
Definition at line 4939 of file playerbase.c.
    {
        return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_FALL;
    }
References m_MovementState.
IsFighting()
override bool ManBase::IsFighting () inline private
Definition at line 4949 of file playerbase.c.
    {
        return m_IsFighting;
    }
IsHoldingBreath()
override bool ManBase::IsHoldingBreath () inline private
Definition at line 1889 of file playerbase.c.
    {
        return m_IsHoldingBreath;
    }
IsIgnoredByConstruction()
override bool ManBase::IsIgnoredByConstruction () inline private
Definition at line 4966 of file playerbase.c.
    {
        return IsRuined();
    }
References IsRuined().
IsInFBEmoteState()
override bool ManBase::IsInFBEmoteState () inline private
Definition at line 7927 of file playerbase.c.
    {
        if (!IsEmotePlaying())
            return false;
        if ( (m_EmoteManager.m_Callback && m_EmoteManager.m_Callback.m_IsFullbody) || m_EmoteManager.m_IsSurrendered )
        {
            return true;
        }
        return false;
    }
References IsEmotePlaying().
IsInProne()
bool ManBase::IsInProne () inline private
Definition at line 4896 of file playerbase.c.
    {
        return m_MovementState.IsInProne();
    }
References m_MovementState.
IsInRasedProne()
bool ManBase::IsInRasedProne () inline private
Definition at line 4901 of file playerbase.c.
    {
        return m_MovementState.IsInRaisedProne();
    }
References m_MovementState.
IsInVehicle()
bool ManBase::IsInVehicle () inline private
Definition at line 4944 of file playerbase.c.
    {
        return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_VEHICLE || (GetParent() != null && GetParent().IsInherited(Transport));
    }
References GetParent(), and m_MovementState.
IsInventorySoftLocked()
override bool ManBase::IsInventorySoftLocked () inline private
Definition at line 7734 of file playerbase.c.
    {
        return m_InventorySoftLocked;
    }
IsInventoryVisible()
override bool ManBase::IsInventoryVisible () inline private
Definition at line 1616 of file playerbase.c.
    {
        return true;
    }
IsInWater()
bool ManBase::IsInWater () inline private
Definition at line 2267 of file playerbase.c.
    {
        return m_IsInWater;
    }
IsItemInInventory()
bool ManBase::IsItemInInventory (EntityAI entity) inline private
Definition at line 4563 of file playerbase.c.
    {
        return GetInventory().HasEntityInInventory(entity);
    }
IsItemsToDelete()
bool ManBase::IsItemsToDelete () inline private
Definition at line 7645 of file playerbase.c.
    {
        return m_ItemsToDelete.Count() > 0;
    }
IsJumpInProgress()
bool ManBase::IsJumpInProgress () inline private
Definition at line 4057 of file playerbase.c.
    {
        return m_JumpClimb.m_bIsJumpInProgress;
    }
References DayZPlayerImplementJumpClimb::m_bIsJumpInProgress, and m_JumpClimb.
IsLeaning()
bool ManBase::IsLeaning () inline private
Definition at line 4906 of file playerbase.c.
    {
        return m_MovementState.IsLeaning();
    }
References m_MovementState.
IsLiftWeapon()
override bool ManBase::IsLiftWeapon () inline private
Definition at line 7750 of file playerbase.c.
    {
        return m_LiftWeapon_player;
    }
References m_LiftWeapon_player.
IsMale()
bool ManBase::IsMale () inline private
Definition at line 1140 of file playerbase.c.
    {
        if (ConfigGetBool("woman") != 1)
        {
            return true;
        }
        return false;
    }
References ConfigGetBool().
IsMapCallbackCancelInput()
bool ManBase::IsMapCallbackCancelInput () inline private
Definition at line 2963 of file playerbase.c.
    {
        Input input = GetGame().GetInput();
        if ( IsRaised() || (input && (input.LocalPress("UAUIMenu",true) || input.LocalPress("UAGear",true))) )
        {
            return true;
        }
        return false;
    }
References GetGame(), CGame::GetInput(), IsRaised(), and Input::LocalPress().
IsMapCallbackEndInput()
bool ManBase::IsMapCallbackEndInput () inline private
Definition at line 2975 of file playerbase.c.
    {
        Input input = GetGame().GetInput();
        if ( input && input.LocalPress("UADefaultAction",true) )
        {
            return true;
        }
        return false;
    }
References GetGame(), CGame::GetInput(), and Input::LocalPress().
IsMapOpen()
bool ManBase::IsMapOpen () inline private
Definition at line 2948 of file playerbase.c.
    {
        return m_MapOpen;
    }
IsNVGLowered()
bool ManBase::IsNVGLowered () inline private
Definition at line 8415 of file playerbase.c.
    {
        return m_LoweredNVGHeadset;
    }
IsNVGWorking()
bool ManBase::IsNVGWorking () inline private
Definition at line 8410 of file playerbase.c.
    {
        return m_ActiveNVTypes && m_ActiveNVTypes.Count() > 0;
    }
IsOverloaded()
bool ManBase::IsOverloaded () inline private
Definition at line 4540 of file playerbase.c.
    {
        if ( GetPlayerLoad() >= OVERLOAD_LIMIT ) return true;
        return false;
    }
IsPersistentFlag()
bool ManBase::IsPersistentFlag (PersistentFlag bit) inline private
Definition at line 6579 of file playerbase.c.
    {
        return (m_PersistentFlags & bit);
    }
IsPlacingLocal()
bool ManBase::IsPlacingLocal () inline private
Definition at line 2115 of file playerbase.c.
    {
        if ( m_HologramLocal )
        {
            return true;
        }
        return false;
    }
IsPlacingServer()
bool ManBase::IsPlacingServer () inline private
Definition at line 2103 of file playerbase.c.
    {
        if ( m_HologramServer )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
IsPlayer()
override bool ManBase::IsPlayer () inline private
Definition at line 618 of file playerbase.c.
    {
        return true;
    }
IsPlayerDisconnected()
bool ManBase::IsPlayerDisconnected () inline private
Definition at line 2015 of file playerbase.c.
    {
        return m_PlayerDisconnectProcessed;
    }
IsPlayerLoaded()
bool ManBase::IsPlayerLoaded () inline private
Definition at line 7953 of file playerbase.c.
    {
        return m_PlayerLoaded;
    }
IsQBControl()
bool ManBase::IsQBControl () inline private
Definition at line 4330 of file playerbase.c.
    {
        return m_ActionQBControl;
    }
IsQuickFishing()
bool ManBase::IsQuickFishing () inline private
Definition at line 1545 of file playerbase.c.
    {
        return m_AllowQuickFishing;
    }
IsQuickRestrain()
bool ManBase::IsQuickRestrain () inline private
Definition at line 1540 of file playerbase.c.
    {
        return m_AllowQuickRestrain;
    }
IsRefresherSignalingViable()
override bool ManBase::IsRefresherSignalingViable () inline private
Definition at line 1894 of file playerbase.c.
    {
        return false;
    }
IsRestrained()
override bool ManBase::IsRestrained () inline private
Definition at line 1611 of file playerbase.c.
    {
        return m_IsRestrained;
    }
IsRestrainPrelocked()
bool ManBase::IsRestrainPrelocked () inline private
Definition at line 1600 of file playerbase.c.
    {
        return m_IsRestrainPrelocked;
    }
IsRestrainStarted()
bool ManBase::IsRestrainStarted () inline private
Definition at line 1589 of file playerbase.c.
    {
        return m_IsRestrainStarted;
    }
IsRolling()
bool ManBase::IsRolling () inline private
Definition at line 4911 of file playerbase.c.
    {
        return GetCommand_Move() && GetCommand_Move().IsInRoll());
    }
References GetCommand_Move(), and HumanCommandMove::IsInRoll().
IsSprinting()
bool ManBase::IsSprinting () inline private
Definition at line 4875 of file playerbase.c.
    {
        return m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENT_SPRINT);
    }
References m_MovementState.
IsStance()
bool ManBase::IsStance (int stance, int stanceMask) inline private
Definition at line 3675 of file playerbase.c.
    {
        return ((1 << stance) & stanceMask) != 0;
    }
IsSurrendered()
bool ManBase::IsSurrendered () inline private
Definition at line 7945 of file playerbase.c.
    {
        if (m_EmoteManager)
            return m_EmoteManager.m_IsSurrendered;
        return false;
    }
IsSwapBetweenHandsAndGroundLargeItem()
bool ManBase::IsSwapBetweenHandsAndGroundLargeItem (notnull EntityAI item1, notnull EntityAI item2, out EntityAI item_hands, out EntityAI item_ground) inline private
Definition at line 8232 of file playerbase.c.
    {
        InventoryLocation il = new InventoryLocation;
        if (item1.GetInventory().GetCurrentInventoryLocation(il) && il.GetType() == InventoryLocationType.HANDS)
            item_hands = item1;
        if (item2.GetInventory().GetCurrentInventoryLocation(il) && il.GetType() == InventoryLocationType.HANDS)
            item_hands = item2;
        if (item1.GetInventory().GetCurrentInventoryLocation(il) && il.GetType() == InventoryLocationType.GROUND)
            item_ground = item1;
        if (item2.GetInventory().GetCurrentInventoryLocation(il) && il.GetType() == InventoryLocationType.GROUND)
            item_ground = item2;
        return item_hands && item_ground && item_ground.IsHeavyBehaviour();
    }
References InventoryLocation::GetType().
IsSwimming()
bool ManBase::IsSwimming () inline private
Definition at line 4924 of file playerbase.c.
    {
        return m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_SWIM;
    }
References m_MovementState.
IsTargetInActiveRefresherRange()
bool ManBase::IsTargetInActiveRefresherRange (EntityAI target) inline private
Definition at line 4086 of file playerbase.c.
    {
        array<vector> temp = new array<vector>;
        temp = GetGame().GetMission().GetActiveRefresherLocations();
        int count = temp.Count();
        if (count > 0)
        {
            vector pos = target.GetPosition();
            for (int i = 0; i < count; i++)
            {
                if ( vector.Distance(pos,temp.Get(i)) < GameConstants.REFRESHER_RADIUS )
                    return true;
            }
            return false;
        }
        else
        {
            return false;
        }
    }
References vector::Distance(), Mission::GetActiveRefresherLocations(), GetGame(), CGame::GetMission(), and GameConstants::REFRESHER_RADIUS.
IsUnconscious()
override bool ManBase::IsUnconscious () inline private
Definition at line 3214 of file playerbase.c.
    {
        return m_IsUnconscious;
    }
References m_IsUnconscious.
IsWearingSplint()
bool ManBase::IsWearingSplint () inline private
Definition at line 3467 of file playerbase.c.
    {
        EntityAI attachment;
        Class.CastTo(attachment, GetItemOnSlot("Splint_Right"));
        if ( attachment && attachment.GetType() == "Splint_Applied" )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
JunctureDeleteItem()
override void ManBase::JunctureDeleteItem (EntityAI item) inline private
Definition at line 7671 of file playerbase.c.
    {
        DayZPlayerSyncJunctures.SendDeleteItem(this, item);
    }
References DayZPlayerSyncJunctures::SendDeleteItem().
KillUndergroundHandler()
void ManBase::KillUndergroundHandler () inline private
Definition at line 1177 of file playerbase.c.
    {
        m_UndergroundHandler = null;
    }
LockHandsUntilItemHeld()
void ManBase::LockHandsUntilItemHeld () inline private
Definition at line 2075 of file playerbase.c.
    {
        m_AreHandsLocked = true;
    }
MapNavigationItemInPossession()
void ManBase::MapNavigationItemInPossession (EntityAI item) inline private
Definition at line 2992 of file playerbase.c.
    {
        if (GetMapNavigationBehaviour())
        {
            GetMapNavigationBehaviour().OnItemInPlayerPossession(item);
        }
    }
MapNavigationItemNotInPossession()
void ManBase::MapNavigationItemNotInPossession (EntityAI item) inline private
Definition at line 3000 of file playerbase.c.
    {
        if (GetMapNavigationBehaviour())
        {
            GetMapNavigationBehaviour().OnItemNotInPlayerPossession(item);
        }
    }
Message()
void ManBase::Message (string text, string style) inline private
colorStatusChannel colorAction colorFriendly colorImportant
Definition at line 6243 of file playerbase.c.
    {
        if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            GetGame().ChatMP(this, text, style );
        }
        else
        {
            GetGame().Chat( text, style );
        }
    }
References CGame::Chat(), CGame::ChatMP(), GetGame(), and GetInstanceType().
MessageAction()
void ManBase::MessageAction (string text) inline private
Definition at line 6262 of file playerbase.c.
    {
        Message( text, "colorAction" );
    }
MessageFriendly()
void ManBase::MessageFriendly (string text) inline private
Definition at line 6268 of file playerbase.c.
    {
        Message( text, "colorFriendly" );
    }
MessageImportant()
void ManBase::MessageImportant (string text) inline private
Definition at line 6274 of file playerbase.c.
    {
        Message( text, "colorImportant" );
    }
MessageStatus()
void ManBase::MessageStatus (string text) inline private
Definition at line 6256 of file playerbase.c.
    {
        Message( text, "colorStatusChannel" );
    }
MovingShock()
void ManBase::MovingShock (float legHealth, float highShock, float midShock, float lowShock) inline private
Definition at line 3416 of file playerbase.c.
    {
        if (legHealth <= PlayerConstants.BROKEN_LEGS_LOW_HEALTH_THRESHOLD)
        {
            //Inflict "high shock"
            m_ShockHandler.SetShock(highShock);
        }
        else if (legHealth >= PlayerConstants.BROKEN_LEGS_HIGH_HEALTH_THRESHOLD)
        {
            //Inflict "low shock"
            m_ShockHandler.SetShock(lowShock);
        }
        else
        {
            //If neither high nore low, inflict "mid shock"
            m_ShockHandler.SetShock(midShock);
        }
    }
References PlayerConstants::BROKEN_LEGS_HIGH_HEALTH_THRESHOLD, and PlayerConstants::BROKEN_LEGS_LOW_HEALTH_THRESHOLD.
NeedInventoryJunctureFromServer()
override bool ManBase::NeedInventoryJunctureFromServer (notnull EntityAI item, EntityAI currParent, EntityAI newParent) inline private
Definition at line 4568 of file playerbase.c.
    {
        if (GetGame().IsMultiplayer())
        {
            DayZPlayerInstanceType t = GetInstanceType();
            switch (t)
            {
                case DayZPlayerInstanceType.INSTANCETYPE_AI_SINGLEPLAYER:
                    return false;
                case DayZPlayerInstanceType.INSTANCETYPE_CLIENT:
                case DayZPlayerInstanceType.INSTANCETYPE_SERVER:
                case DayZPlayerInstanceType.INSTANCETYPE_AI_SERVER:
                case DayZPlayerInstanceType.INSTANCETYPE_AI_REMOTE:
                case DayZPlayerInstanceType.INSTANCETYPE_REMOTE:
                    return true; // Might help mitigate "megabugged" (desync)
                    syncDebugPrint("[syncinv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " NeedInventoryJunctureFromServer item=" + Object.GetDebugName(item) + " currPar=" + currParent + " newPar=" + newParent);
                    bool i_owned = GetHumanInventory().HasEntityInInventory(item);
                    bool cp_owned = false;
                    if (currParent)
                        cp_owned = GetHumanInventory().HasEntityInInventory(currParent);
                    bool np_owned = false;
                    if (newParent)
                        np_owned = GetHumanInventory().HasEntityInInventory(newParent);
                    bool all_owned = i_owned && cp_owned && (np_owned || (newParent == null));
                    syncDebugPrint("[syncinv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " NeedInventoryJunctureFromServer=" + !all_owned + " i_pwn=" + i_owned + " cp_pwn=" + cp_owned + " np_pwn=" + np_owned);
                    return !all_owned;
                default:
                    Error("[syncinv] unsupported instance type t=" + t);
                    break;
            }
        }
        return false;
    }
References Error(), GetDebugName(), GetGame(), GetInstanceType(), and syncDebugPrint().
OnBleedingBegin()
void ManBase::OnBleedingBegin () inline private
Definition at line 7093 of file playerbase.c.
    {
    }
OnBleedingEnd()
void ManBase::OnBleedingEnd () inline private
Definition at line 7098 of file playerbase.c.
    {
    }
OnBleedingSourceAdded()
void ManBase::OnBleedingSourceAdded () inline private
Definition at line 7103 of file playerbase.c.
    {
        m_BleedingSourceCount++;
        if (IsControlledPlayer())
        {
            if ( !GetGame().IsDedicatedServer() )
            {
                DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_BLEEDING));
                if ( dis_elm )
                {
                    dis_elm.SetValue(GetBleedingSourceCount());
                }
                //Print("----------bleeding_SoundSet----------");
                //SEffectManager.PlaySoundOnObject("bleeding_SoundSet", this); Removed due as it caused a freeze on the Console Submission builds.
            }
        }
    }
References GetElement(), GetGame(), and GetVirtualHud().
OnBleedingSourceRemoved()
void ManBase::OnBleedingSourceRemoved () inline private
Definition at line 7123 of file playerbase.c.
    {
        m_BleedingSourceCount--;
        if(IsControlledPlayer())
        {
            if( !GetGame().IsDedicatedServer() )
            {
                //Print("GetBleedingSourceCount() "+GetBleedingSourceCount());
                DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_BLEEDING));
                if( dis_elm )
                {
                    dis_elm.SetValue(GetBleedingSourceCount());
                }
            }
        }
    }
References GetElement(), GetGame(), and GetVirtualHud().
OnBleedingSourceRemovedEx()
void ManBase::OnBleedingSourceRemovedEx (ItemBase item) inline private
Definition at line 7141 of file playerbase.c.
    {
        OnBleedingSourceRemoved();
    }
OnCameraChanged()
void ManBase::OnCameraChanged (DayZPlayerCameraBase new_camera) inline private
Definition at line 2286 of file playerbase.c.
    {
        m_CameraSwayModifier = new_camera.GetWeaponSwayModifier();
        m_CurrentCamera = new_camera;
    }
OnCommandClimbFinish()
override void ManBase::OnCommandClimbFinish () inline private
Definition at line 3577 of file playerbase.c.
    {
        if ( GetInventory() )
            GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        GetWeaponManager().RefreshAnimationState();
    }
References GetWeaponManager(), and WeaponManager::RefreshAnimationState().
OnCommandClimbStart()
override void ManBase::OnCommandClimbStart () inline private
Definition at line 3563 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandClimb;
        if ( GetInventory() )
            GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        CloseInventoryMenu();
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), and GetWeaponManager().
OnCommandDeathStart()
override void ManBase::OnCommandDeathStart () inline private
Definition at line 3637 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandDeath;
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), and GetWeaponManager().
OnCommandFallFinish()
override void ManBase::OnCommandFallFinish () inline private
Definition at line 3555 of file playerbase.c.
    {
        if ( GetInventory() )
            GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        GetWeaponManager().RefreshAnimationState();
    }
References GetWeaponManager(), and WeaponManager::RefreshAnimationState().
OnCommandFallStart()
override void ManBase::OnCommandFallStart () inline private
Definition at line 3541 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandFall;
        if ( GetInventory() )
            GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        CloseInventoryMenu();
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), and GetWeaponManager().
OnCommandHandlerTick()
void ManBase::OnCommandHandlerTick (float delta_time, int pCurrentCommandID) inline private
Definition at line 2500 of file playerbase.c.
    {
        if( !IsAlive() )
        {
            if ( !m_DeathSyncSent && m_KillerData )
            {
                SyncEvents.SendEntityKilled(this, m_KillerData.m_Killer, m_KillerData.m_MurderWeapon, m_KillerData.m_KillerHiTheBrain);
                //Print("Sending Death Sync, yay! Headshot by killer = " + m_KillerData.m_KillerHiTheBrain);
                //Print("And was he killed by headshot in general? = " + m_KilledByHeadshot);
                m_DeathSyncSent = true;
            }
            return;
        }
        if( m_DebugMonitorValues )
            m_DebugMonitorValues.OnScheduledTick(delta_time);
        if( GetSymptomManager() )
            GetSymptomManager().OnTick(delta_time, pCurrentCommandID, m_MovementState);//needs to stay in command handler tick as it's playing animations
        //if( GetBleedingManagerServer() ) GetBleedingManagerServer().OnTick(delta_time);
        DayZPlayerInstanceType instType = GetInstanceType();
        if( instType == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            if( m_PlayerSoundEventHandler )
                m_PlayerSoundEventHandler.OnTick(delta_time);
            if (m_ProcessRemoveEffectWidgets && m_ProcessRemoveEffectWidgets.Count() > 0)
            {
                m_EffectWidgets.RemoveActiveEffects(m_ProcessRemoveEffectWidgets);
            }
            if (m_ProcessAddEffectWidgets && m_ProcessAddEffectWidgets.Count() > 0)
            {
                m_EffectWidgets.AddActiveEffects(m_ProcessAddEffectWidgets);
            }
            HandleGlassesEffect();
            if (m_ContaminatedAreaEffectEnabled)
                ContaminatedParticleAdjustment();
            #ifdef DEVELOPER
            if( m_WeaponDebug )
            {
                m_WeaponDebug.OnCommandHandlerUpdate();
            }
            #endif
            m_ProcessAddEffectWidgets.Clear(); //clears array for remotes as well
            m_ProcessRemoveEffectWidgets.Clear(); //clears array for remotes as well
        }
        m_AnimCommandStarting = HumanMoveCommandID.None;
    }
References GameplayEffectWidgets_base::AddActiveEffects(), GetInstanceType(), IsAlive(), m_MovementState, m_PlayerSoundEventHandler, m_WeaponDebug, WeaponDebug::OnCommandHandlerUpdate(), GameplayEffectWidgets_base::RemoveActiveEffects(), and SyncEvents::SendEntityKilled().
OnCommandLadderFinish()
override void ManBase::OnCommandLadderFinish () inline private
Definition at line 3533 of file playerbase.c.
    {
        TryHideItemInHands(false, true);
        if ( GetInventory() )
            GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
    }
OnCommandLadderStart()
override void ManBase::OnCommandLadderStart () inline private
Definition at line 3522 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandLadder;
        TryHideItemInHands(true);
        if ( GetInventory() )
            GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        CloseInventoryMenu();
    }
OnCommandMelee2Finish()
override void ManBase::OnCommandMelee2Finish () inline private
Definition at line 3629 of file playerbase.c.
    {
        RunFightBlendTimer();
        GetWeaponManager().RefreshAnimationState();
    }
References GetWeaponManager(), and WeaponManager::RefreshAnimationState().
OnCommandMelee2Start()
override void ManBase::OnCommandMelee2Start () inline private
Definition at line 3619 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandMelee2;
        m_IsFighting = true;
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), and GetWeaponManager().
OnCommandMoveStart()
override void ManBase::OnCommandMoveStart () inline private
Definition at line 3727 of file playerbase.c.
    {
        if ( GetGame().IsServer() )
        {
            //In case player changes stance through a different command, we refresh the anim overrides
            int prone = DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
            if ( !IsPlayerInStance( prone ) )
            {
                m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PRONE_ANIM_OVERRIDE;
                ForceUpdateInjuredState();
            }
        }
    }
References GetGame(), and IsPlayerInStance().
OnCommandSwimFinish()
override void ManBase::OnCommandSwimFinish () inline private
Definition at line 3510 of file playerbase.c.
    {
        TryHideItemInHands(false, true);
        if ( GetInventory() )
            GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        GetDayZGame().GetBacklit().OnSwimmingStop();
        GetWeaponManager().RefreshAnimationState();
    }
References GetDayZGame(), GetWeaponManager(), and WeaponManager::RefreshAnimationState().
OnCommandSwimStart()
override void ManBase::OnCommandSwimStart () inline private
Definition at line 3481 of file playerbase.c.
    {
        ItemBase itemInHands = GetItemInHands();
        if (itemInHands)
        {
            if (itemInHands.IsHeavyBehaviour())
            {
                TryHideItemInHands(false);
                DropHeavyItem();
            }
            else
            {
                TryHideItemInHands(true);
            }
            itemInHands.OnItemInHandsPlayerSwimStart(this);
        }
        m_AnimCommandStarting = HumanMoveCommandID.CommandSwim;
        if ( GetInventory() )
            GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        CloseInventoryMenu();
        GetDayZGame().GetBacklit().OnSwimmingStart();
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), GetDayZGame(), and GetWeaponManager().
OnCommandVehicleFinish()
override void ManBase::OnCommandVehicleFinish () inline private
Definition at line 3608 of file playerbase.c.
    {
        if ( GetInventory() )
            GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        TryHideItemInHands(false, true);
        if ( m_IsVehicleSeatDriver )
            OnVehicleSeatDriverLeft();
    }
OnCommandVehicleStart()
override void ManBase::OnCommandVehicleStart () inline private
Definition at line 3585 of file playerbase.c.
    {
        m_AnimCommandStarting = HumanMoveCommandID.CommandVehicle;
        if ( GetInventory() )
            GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        ItemBase itemInHand = GetItemInHands();
        EntityAI itemOnHead = FindAttachmentBySlotName("Headgear");
        if ( itemInHand && itemInHand.GetCompEM() )
            itemInHand.GetCompEM().SwitchOff();
        TryHideItemInHands(true);
        if ( itemOnHead && itemOnHead.GetCompEM() )
            itemOnHead.GetCompEM().SwitchOff();
        HumanCommandVehicle hcv = GetCommand_Vehicle();
        if ( hcv && hcv.GetVehicleSeat() == DayZPlayerConstants.VEHICLESEAT_DRIVER )
            OnVehicleSeatDriverEnter();
    }
References GetCommand_Vehicle(), and HumanCommandVehicle::GetVehicleSeat().
OnConnect()
void ManBase::OnConnect () inline private
Definition at line 6853 of file playerbase.c.
    {
        Debug.Log("Player connected:"+this.ToString(),"Connect");
        // analytics
        GetGame().GetAnalyticsServer().OnPlayerConnect( this );
        m_PlayerOldPos = GetPosition();
        if ( m_AnalyticsTimer )
            m_AnalyticsTimer.Run( 60, this, "UpdatePlayerMeasures", null, true );
        //construction action data
        ResetConstructionActionData();
    }
References CGame::GetAnalyticsServer(), GetGame(), GetPosition, Debug::Log(), AnalyticsManagerServer::OnPlayerConnect(), and ToString().
OnDisconnect()
void ManBase::OnDisconnect () inline private
Definition at line 6877 of file playerbase.c.
    {
        Debug.Log("Player disconnected:"+this.ToString(),"Connect");
        // analytics
        // force update of the stats
        // if player disconnect too soon, UpdatePlayersStats() is not called
        GetGame().GetAnalyticsServer().OnPlayerDisconnect( this );
        StatsEventDisconnectedData data = new StatsEventDisconnectedData();
        data.m_CharacterId = g_Game.GetDatabaseID();
        data.m_Reason = "Disconnected";
        Analytics.PlayerDisconnected(data);
        if( m_AnalyticsTimer )
            m_AnalyticsTimer.Stop();
        UpdatePlayerMeasures();
        SetPlayerDisconnected(true);
    }
References g_Game, CGame::GetAnalyticsServer(), GetGame(), Debug::Log(), StatsEventDisconnectedData::m_CharacterId, StatsEventDisconnectedData::m_Reason, AnalyticsManagerServer::OnPlayerDisconnect(), Analytics::PlayerDisconnected(), and ToString().
OnDrowningEnd()
void ManBase::OnDrowningEnd () inline private
Definition at line 2153 of file playerbase.c.
    {
        #ifndef SERVER
        if (IsControlledPlayer())
        {
            PPERequester_Drowning req = PPERequester_Drowning.Cast(PPERequesterBank.GetRequester( PPERequesterBank.REQ_DROWNING ));
            req.Stop();
        }
        #endif
    }
OnDrowningStart()
void ManBase::OnDrowningStart () inline private
Definition at line 2142 of file playerbase.c.
    {
        #ifndef SERVER
        if (IsControlledPlayer())
        {
            PPERequester_Drowning req = PPERequester_Drowning.Cast(PPERequesterBank.GetRequester( PPERequesterBank.REQ_DROWNING ));
            req.Start();
        }
        #endif
    }
OnGameplayDataHandlerSync()
override void ManBase::OnGameplayDataHandlerSync () inline private
Definition at line 5367 of file playerbase.c.
    {
        super.OnGameplayDataHandlerSync();
        UpdateLighting();
        //Print("setting respawn to " + CfgGameplayHandler.GetDisableRespawnDialog());
        GetGame().GetMission().SetRespawnModeClient(CfgGameplayHandler.GetDisableRespawnDialog());//TODO: maybe move to mission/game ?
        SetHitPPEEnabled(CfgGameplayHandler.GetHitIndicationPPEEnabled());
    }
References CfgGameplayHandler::GetDisableRespawnDialog(), GetGame(), CfgGameplayHandler::GetHitIndicationPPEEnabled(), CGame::GetMission(), and Mission::SetRespawnModeClient().
OnHoldBreathEnd()
void ManBase::OnHoldBreathEnd () inline private
Definition at line 1883 of file playerbase.c.
    {
        //SendSoundEvent(SoundSetMap.GetSoundSetID("releaseBreath_male_Char_SoundSet"));
        RequestSoundEventEx(EPlayerSoundEventID.RELEASE_BREATH, true, EPlayerSoundEventParam.SKIP_CONTROLLED_PLAYER );
    }
References RequestSoundEventEx().
OnHoldBreathExhausted()
void ManBase::OnHoldBreathExhausted () inline private
Definition at line 1878 of file playerbase.c.
    {
        RequestSoundEventEx(EPlayerSoundEventID.EXHAUSTED_BREATH, true, EPlayerSoundEventParam.SKIP_CONTROLLED_PLAYER );
    }
References RequestSoundEventEx().
OnHoldBreathStart()
void ManBase::OnHoldBreathStart () inline private
Definition at line 1872 of file playerbase.c.
    {
        //SendSoundEvent(SoundSetMap.GetSoundSetID("holdBreath_male_Char_SoundSet"));
        RequestSoundEventEx(EPlayerSoundEventID.HOLD_BREATH, true, EPlayerSoundEventParam.SKIP_CONTROLLED_PLAYER );
    }
References RequestSoundEventEx().
OnInputUserDataProcess()
override bool ManBase::OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
Definition at line 5817 of file playerbase.c.
    {
        if( super.OnInputUserDataProcess(userDataType, ctx) )
            return true;
        if( m_QuickBarBase.OnInputUserDataProcess(userDataType, ctx) )
            return true;
        if( m_WeaponManager.OnInputUserDataProcess(userDataType, ctx) )
            return true;
        if( HandleRemoteItemManipulation(userDataType, ctx) )
            return true;
        if ( userDataType == INPUT_UDT_INVENTORY && GetHumanInventory().OnInputUserDataProcess(ctx) )
            return true;
        if ( TogglePlacingServer( userDataType, ctx ) )
            return true;
        if ( ResetADSPlayerSync( userDataType, ctx ) )
            return true;
        string uid;
        bool mute;
        if( userDataType == INPUT_UDT_USER_MUTE_XBOX )
        {
            if( ctx.Read( uid ) && ctx.Read( mute ) )
            {
                GetGame().MutePlayer( uid, GetIdentity().GetPlainId(), mute );
                // commented because plainID should not be present in logs
                //Print( "Player: " + GetIdentity().GetId() + " set mute for " + uid + " to " + mute );
            }
        }
        if( m_EmoteManager && userDataType == INPUT_UDT_GESTURE )
            return m_EmoteManager.OnInputUserDataProcess(userDataType, ctx);
        if( userDataType == INPUT_UDT_WEAPON_LIFT_EVENT )
            return ReadLiftWeaponRequest(userDataType, ctx);
        if( m_ActionManager )
            return m_ActionManager.OnInputUserDataProcess(userDataType, ctx);
        return false;
    }
References GetGame(), INPUT_UDT_GESTURE, INPUT_UDT_INVENTORY, INPUT_UDT_USER_MUTE_XBOX, INPUT_UDT_WEAPON_LIFT_EVENT, CGame::MutePlayer(), OnInputUserDataProcess(), and Serializer::Read().
OnInventoryMenuClose()
void ManBase::OnInventoryMenuClose () inline private
Definition at line 5597 of file playerbase.c.
    {
    }
OnInventoryMenuOpen()
void ManBase::OnInventoryMenuOpen () inline private
Definition at line 5592 of file playerbase.c.
    {
    }
OnJumpEnd()
override void ManBase::OnJumpEnd (int pLandType = 0) inline private
Definition at line 3655 of file playerbase.c.
    {
        if(m_PresenceNotifier)
        {
            switch(pLandType)
            {
            case HumanCommandFall.LANDTYPE_NONE:
            case HumanCommandFall.LANDTYPE_LIGHT:
                m_PresenceNotifier.ProcessEvent(EPresenceNotifierNoiseEventType.LAND_LIGHT);
                break;
            case HumanCommandFall.LANDTYPE_MEDIUM:
            case HumanCommandFall.LANDTYPE_HEAVY:
                m_PresenceNotifier.ProcessEvent(EPresenceNotifierNoiseEventType.LAND_HEAVY);
                break;
            }
        }
        GetWeaponManager().RefreshAnimationState();
    }
References GetWeaponManager(), HumanCommandFall(), and WeaponManager::RefreshAnimationState().
OnJumpOutVehicleFinish()
void ManBase::OnJumpOutVehicleFinish (float carSpeed) inline private
Definition at line 3766 of file playerbase.c.
    {
        string surfaceType;
        int liquidType;
        GetGame().SurfaceUnderObject(this, surfaceType, liquidType);
    }
References GetGame(), and CGame::SurfaceUnderObject().
OnJumpStart()
override void ManBase::OnJumpStart () inline private
Definition at line 3645 of file playerbase.c.
    {
        m_ActionManager.OnJumpStart();
        AbortWeaponEvent();
        GetWeaponManager().DelayedRefreshAnimationState(10);
        RequestHandAnimationStateRefresh();
        CloseMapEx(true);
    }
References AbortWeaponEvent(), WeaponManager::DelayedRefreshAnimationState(), and GetWeaponManager().
OnLadder()
override void ManBase::OnLadder (float delta_time, HumanMovementState pState) inline private
called every command handler tick when player is on ladder
Definition at line 1394 of file playerbase.c.
    {
        ProcessHandDamage(delta_time, pState);
    }
OnParticleEvent()
override void ManBase::OnParticleEvent (string pEventType, string pUserString, int pUserInt) inline private
Definition at line 6379 of file playerbase.c.
    {
        super.OnParticleEvent(pEventType ,pUserString, pUserInt);
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( pUserInt == 123456 ) // 123456 is ID for vomiting effect. The current implementation is WIP.
            {
                PlayerBase player = PlayerBase.Cast(this);
                int boneIdx = player.GetBoneIndexByName("Head");
                if ( boneIdx != -1 )
                {
                    EffectParticle eff;
                    if (m_SyncedModifiers & eModifierSyncIDs.MODIFIER_SYNC_CONTAMINATION2)
                    {
                        eff = new EffVomitBlood();
                    }
                    else
                    {
                        eff = new EffVomit();
                    }
                    eff.SetDecalOwner( player );
                    eff.SetAutodestroy( true );
                    SEffectManager.PlayInWorld( eff, vector.Zero );
                    Particle p = eff.GetParticle();
                    player.AddChild(p, boneIdx);
                }
            }
        }
    }
References GetGame(), EffectParticle::GetParticle(), SEffectManager::PlayInWorld(), EffectParticle::SetDecalOwner(), and vector::Zero.
OnPlayerLoaded()
void ManBase::OnPlayerLoaded () inline private
Definition at line 1953 of file playerbase.c.
    {
        InitEditor();
        if ( GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            m_ModuleLifespan.SynchLifespanVisual( this, m_LifeSpanState, m_HasBloodyHandsVisible, m_HasBloodTypeVisible, m_BloodType );
        }
        if (IsControlledPlayer())//true only on client for the controlled character
        {
            if (!m_VirtualHud)
                m_VirtualHud = new VirtualHud(this);
            if ( m_Hud )
            {
                m_Hud.UpdateBloodName();
                PPERequesterBank.GetRequester(PPERequester_DeathDarkening).Stop();
                PPERequesterBank.GetRequester(PPERequester_ShockHitReaction).Stop();
                PPERequesterBank.GetRequester(PPERequester_UnconEffects).Stop(); //TODO - stop en mass...check if effects do not terminate (spawning inside of contaminated area)?!
                GetGame().GetUIManager().CloseAll();
                GetGame().GetMission().SetPlayerRespawning(false);
                GetGame().GetMission().OnPlayerRespawned(this);
                m_Hud.ShowHudUI(true);
                m_Hud.ShowQuickbarUI(true);
                #ifdef PLATFORM_CONSOLE
                m_Hud.ShowQuickBar(GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer()); //temporary solution
                #else
                m_Hud.ShowQuickBar(g_Game.GetProfileOption(EDayZProfilesOptions.QUICKBAR));
                #endif
            }
            m_EffectWidgets = GetGame().GetMission().GetEffectWidgets();
        }
        if (!GetGame().IsDedicatedServer())
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(UpdateCorpseStateVisual, 2000, false);//sometimes it takes a while to load in
            m_PlayerSoundEventHandler = new PlayerSoundEventHandler(this);
        }
        int slot_id = InventorySlots.GetSlotIdFromString("Head");
        m_CharactersHead = Head_Default.Cast(GetInventory().FindPlaceholderForSlot( slot_id ));
        CheckHairClippingOnCharacterLoad();
        UpdateHairSelectionVisibility();
        PreloadDecayTexture();
        Weapon_Base wpn = Weapon_Base.Cast(GetItemInHands());
        if (wpn)
            wpn.ValidateAndRepair();
        /*
        PreloadDecayTexture();
        UpdateCorpseStateVisual();
        */
        m_PlayerLoaded = true;
        //Print("PlayerBase | OnPlayerLoaded()");
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), UIManager::CloseAll(), FindPlaceholderForSlot(), g_Game, CGame::GetCallQueue(), Mission::GetEffectWidgets(), GetGame(), GetInput(), CGame::GetMission(), InventorySlots::GetSlotIdFromString(), CGame::GetUIManager(), m_BloodType, m_Hud, m_PlayerSoundEventHandler, m_VirtualHud, Mission::OnPlayerRespawned(), PlayerSoundEventHandler(), Mission::SetPlayerRespawning(), Hud::ShowHudUI(), Hud::ShowQuickBar(), Hud::ShowQuickbarUI(), Hud::UpdateBloodName(), and VirtualHud().
OnPlayerReceiveFlashbangHitEnd()
void ManBase::OnPlayerReceiveFlashbangHitEnd () inline private
Definition at line 931 of file playerbase.c.
{}
OnPlayerReceiveFlashbangHitStart()
void ManBase::OnPlayerReceiveFlashbangHitStart (bool visual) inline private
Definition at line 926 of file playerbase.c.
    {
        SpawnFlashbangEffect(this, visual);
    }
OnPlayerRecievedHit()
override void ManBase::OnPlayerRecievedHit () inline private
Call only on client or single player PlayerBase (as GetGame().GetPlayer())
Definition at line 915 of file playerbase.c.
    {
#ifndef NO_GUI
        SpawnDamageDealtEffect();
        CachedObjectsParams.PARAM2_FLOAT_FLOAT.param1 = 32;
        CachedObjectsParams.PARAM2_FLOAT_FLOAT.param2 = 0.3;
        SpawnDamageDealtEffect2(CachedObjectsParams.PARAM2_FLOAT_FLOAT);
        CloseMapEx(true);
#endif
    }
References CachedObjectsParams::PARAM2_FLOAT_FLOAT, and SpawnDamageDealtEffect().
OnQuickBarContinuousUseEnd()
void ManBase::OnQuickBarContinuousUseEnd (int slotClicked) inline private
Definition at line 4295 of file playerbase.c.
    {
        if ( m_QuickBarHold )
        {
            if (  GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
            {
                ActionManagerClient am = ActionManagerClient.Cast(GetActionManager());
                if (m_ActionQBControl)
                {
                    ActionBase action = am.GetRunningAction();
                    if (action)
                    {
                        if (!action.GetInput().IsActive())
{
                            am.EndActionInput();
                        }
                    }
                }
                if (m_QuickBarFT)
                {
                    am.ClearForceTarget();
                    m_QuickBarFT = false;
                }
            }
        }
        m_QuickBarHold = false;
    }
References ActionBase(), ActionManagerClient::ClearForceTarget(), ActionManagerClient::EndActionInput(), GetActionManager(), GetInstanceType(), and ActionManagerBase::GetRunningAction().
OnQuickBarContinuousUseStart()
void ManBase::OnQuickBarContinuousUseStart (int slotClicked) inline private
Definition at line 4260 of file playerbase.c.
    {
        if ( GetInventory().IsInventoryLocked() )
            return;
        if ( IsSwimming() || IsClimbingLadder() || GetCommand_Melee() || IsClimbing() || IsRestrained() || IsRestrainPrelocked() )
            return;
        ItemBase quickBarItem = ItemBase.Cast(GetQuickBarEntity(slotClicked - 1));
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
        {
            ItemBase itemInHands = ItemBase.Cast(GetHumanInventory().GetEntityInHands());
            if ( itemInHands != quickBarItem )
            {
                ActionManagerClient amc = ActionManagerClient.Cast(GetActionManager());
                if ( amc.CanPerformActionFromQuickbar(itemInHands, quickBarItem) )
                {
                    amc.PerformActionFromQuickbar(itemInHands, quickBarItem);
                }
                else
                {
                    if ( IsRaised() || GetCommand_Melee() )
                        return;
                    amc.ForceTarget(quickBarItem);
                    m_QuickBarFT = true;
                }
            }
        }
        m_QuickBarHold = true;
    }
References ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::ForceTarget(), GetActionManager(), GetCommand_Melee(), GetInstanceType(), IsInventoryLocked(), IsRaised(), IsRestrained(), and ActionManagerClient::PerformActionFromQuickbar().
OnQuickbarSetEntityRequest()
void ManBase::OnQuickbarSetEntityRequest (ParamsReadContext ctx) inline private
Definition at line 1821 of file playerbase.c.
    {
        m_QuickBarBase.OnSetEntityRequest(ctx);
    }
OnQuickBarSingleUse()
void ManBase::OnQuickBarSingleUse (int slotClicked) inline private
Definition at line 4152 of file playerbase.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER )
            return;
        if ( m_AreHandsLocked )
            return; //Player is in the short window of time after interrupting placement of an item and before getting it back in hands
        if ( GetInventory().IsInventoryLocked() || IsEmotePlaying() )
            return;
        if ( GetThrowing().IsThrowingModeEnabled() || GetThrowing().IsThrowingAnimationPlaying() )
            return;
        if ( IsRaised() || GetCommand_Melee() || IsSwimming() || IsClimbingLadder() || IsClimbing() || IsRestrained() || IsRestrainPrelocked() )
            return;
        if ( GetDayZPlayerInventory().IsProcessing() || IsItemsToDelete() )
            return;
        if ( GetActionManager().GetRunningAction() != null )
            return;
        if ( GetWeaponManager() && GetWeaponManager().IsRunning() )
            return;
        if ( !ScriptInputUserData.CanStoreInputUserData() )
            return;
        //TODO MW change locking method
        //if( GetDayZPlayerInventory().HasLockedHands() )
        //  return;
        EntityAI quickBarEntity = GetQuickBarEntity(slotClicked - 1);//GetEntityInQuickBar(slotClicked - 1);
        if ( !quickBarEntity )
            return;
        Magazine mag;
        Weapon_Base wpn;
        if ( Class.CastTo(mag, quickBarEntity) && Class.CastTo(wpn, mag.GetHierarchyParent()) )
            return;
        EntityAI inHandEntity = GetHumanInventory().GetEntityInHands();
        if ( !GetDayZPlayerInventory().IsIdle() )
            return; // player is already performing some animation
        InventoryLocation handInventoryLocation = new InventoryLocation;
        handInventoryLocation.SetHands(this,quickBarEntity);
        if ( this.GetInventory().HasInventoryReservation(quickBarEntity, handInventoryLocation ) )
            return;
        if ( inHandEntity == quickBarEntity )
        {
            if ( GetHumanInventory().CanRemoveEntityInHands() )
            {
                syncDebugPrint("[QB] Stash - PredictiveMoveItemFromHandsToInventory HND=" + Object.GetDebugName(inHandEntity));
                PredictiveMoveItemFromHandsToInventory();
            }
        }
        else
        {
            InventoryLocation invLocQBItem = new InventoryLocation;
            quickBarEntity.GetInventory().GetCurrentInventoryLocation(invLocQBItem);
            if ( GetInventory().HasInventoryReservation(quickBarEntity,invLocQBItem) )
                return;
            if ( inHandEntity )
            {
                InventoryLocation Reserved_Item_il = new InventoryLocation;
                InventoryLocation inHandEntityFSwapDst = new InventoryLocation;
                inHandEntity.GetInventory().GetCurrentInventoryLocation(inHandEntityFSwapDst);
                int index = GetHumanInventory().FindUserReservedLocationIndex(inHandEntity);
                if ( index >= 0 )
                    GetHumanInventory().GetUserReservedLocation( index, Reserved_Item_il);
                if ( Reserved_Item_il )
                    inHandEntityFSwapDst.CopyLocationFrom(Reserved_Item_il, true);
                if ( index < 0 && GameInventory.CanSwapEntitiesEx( quickBarEntity, inHandEntity ) )
                {
                    syncDebugPrint("[QB] PredictiveSwapEntities QB=" + Object.GetDebugName(quickBarEntity) + " HND=" + Object.GetDebugName(inHandEntity));
                    PredictiveSwapEntities( quickBarEntity, inHandEntity );
                }
                else if ( GameInventory.CanForceSwapEntitiesEx( quickBarEntity, null, inHandEntity, inHandEntityFSwapDst ) )
                {
                    syncDebugPrint("[QB] Swap - PredictiveForceSwapEntities HND=" + Object.GetDebugName(inHandEntity) +  " QB=" + Object.GetDebugName(quickBarEntity) + " fswap_dst=" + InventoryLocation.DumpToStringNullSafe(inHandEntityFSwapDst));
                    PredictiveForceSwapEntities( quickBarEntity, inHandEntity, inHandEntityFSwapDst );
                }
            }
            else
            {
                if ( GetInventory().HasInventoryReservation(quickBarEntity,handInventoryLocation) )
                    return;
                if ( GetInventory().CanAddEntityIntoHands(quickBarEntity) )
                {
                    syncDebugPrint("[QB] Stash - PredictiveTakeEntityToHands QB=" + Object.GetDebugName(quickBarEntity));
                    PredictiveTakeEntityToHands( quickBarEntity );
                }
            }
        }
    }
References CanAddEntityIntoHands(), ScriptInputUserData::CanStoreInputUserData(), Class::CastTo(), InventoryLocation::CopyLocationFrom(), InventoryLocation::DumpToStringNullSafe(), GetActionManager(), GetCommand_Melee(), GetDayZPlayerInventory(), GetInstanceType(), GetRunningAction(), GetThrowing(), GetWeaponManager(), HasInventoryReservation(), IsEmotePlaying(), IsIdle(), IsInventoryLocked(), IsProcessing(), IsRaised(), IsRestrained(), IsRunning(), InventoryLocation::SetHands(), and syncDebugPrint().
OnReconnect()
void ManBase::OnReconnect () inline private
Definition at line 6868 of file playerbase.c.
    {
        Debug.Log("Player reconnected:"+this.ToString(),"Reconnect");
        //construction action data
        ResetConstructionActionData();
    }
References Debug::Log(), and ToString().
OnRestrainStart()
void ManBase::OnRestrainStart () inline private
Definition at line 3237 of file playerbase.c.
    {
        CloseInventoryMenu();
        GetGame().GetMission().RemoveActiveInputExcludes({"inventory"},true);
        GetGame().GetMission().RemoveActiveInputRestriction(EInputRestrictors.INVENTORY);
    }
References GetGame(), CGame::GetMission(), Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
OnRollFinish()
override void ManBase::OnRollFinish () inline private
Definition at line 3762 of file playerbase.c.
    {
    }
OnRollStart()
override void ManBase::OnRollStart (bool isToTheRight) inline private
Definition at line 3754 of file playerbase.c.
    {
        DepleteStamina(EStaminaModifiers.ROLL);
        if (GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_ROLL_SHOCK);
    }
References PlayerConstants::BROKEN_LEGS_ROLL_SHOCK, and DepleteStamina().
OnRPC()
override void ManBase::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
uses contants outside of ERPCs !!!!
Definition at line 5024 of file playerbase.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        switch (rpc_type)
        {
            #ifndef SERVER
            case ERPCs.RPC_SYNC_DISPLAY_STATUS:
                if ( GetVirtualHud() )
                {
                    GetVirtualHud().OnRPC(ctx);
                }
            break;
            case ERPCs.RPC_PLAYER_SYMPTOM_ON:
                if ( GetSymptomManager() )
                {
                    GetSymptomManager().OnRPC(ERPCs.RPC_PLAYER_SYMPTOM_ON, ctx);
                }
            break;
            case ERPCs.RPC_PLAYER_SYMPTOM_OFF:
                if ( GetSymptomManager() )
                {
                    GetSymptomManager().OnRPC(ERPCs.RPC_PLAYER_SYMPTOM_OFF, ctx);
                }
            break;
            case ERPCs.RPC_DAMAGE_VALUE_SYNC:
                if ( m_TrasferValues )
                    m_TrasferValues.OnRPC(ctx);
            break;
            case ERPCs.RPC_USER_ACTION_MESSAGE:
                if ( !GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
                {
                    break;
                }
                if ( ctx.Read(m_UAParamMessage) )
                {
                    string actiontext = m_UAParamMessage.param1;
                    MessageAction(actiontext);
                }
            break;
            case ERPCs.RPC_SOFT_SKILLS_SPECIALTY_SYNC:
                ref Param1<float> p_synch = new Param1<float>(0);
                ctx.Read( p_synch );
                float specialty_level = p_synch.param1;
                GetSoftSkillsManager().SetSpecialtyLevel( specialty_level );
            break;
            case ERPCs.RPC_SOFT_SKILLS_STATS_SYNC:
                ref Param5<float, float, float, float, bool> p_debug_synch = new Param5<float, float ,float, float, bool>(0, 0, 0, 0, false);
                ctx.Read( p_debug_synch );
                float general_bonus_before = p_debug_synch.param1;
                float general_bonus_after = p_debug_synch.param2;
                float last_UA_value = p_debug_synch.param3;
                float cooldown_value = p_debug_synch.param4;
                float cooldown_active = p_debug_synch.param5;
                GetSoftSkillsManager().SetGeneralBonusBefore( general_bonus_before );
                GetSoftSkillsManager().SetGeneralBonusAfter( general_bonus_after );
                GetSoftSkillsManager().SetLastUAValue( last_UA_value );
                GetSoftSkillsManager().SetCoolDownValue( cooldown_value );
                GetSoftSkillsManager().SetCoolDown( cooldown_active );
            break;
            case ERPCs.RPC_WARNING_ITEMDROP:
            {
                if ( GetGame().IsClient() && GetGame().GetUIManager() && !GetGame().GetUIManager().FindMenu(MENU_WARNING_ITEMDROP) )
                {
                    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(GetGame().GetUIManager().EnterScriptedMenu,MENU_WARNING_ITEMDROP,null);
                    GetGame().GetMission().AddActiveInputExcludes({"menu"});
                }
                break;
            }
            case ERPCs.RPC_WARNING_TELEPORT:
            {
                if ( GetGame().IsClient() && GetGame().GetUIManager() && !GetGame().GetUIManager().FindMenu(MENU_WARNING_TELEPORT) )
                {
                    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(GetGame().GetUIManager().EnterScriptedMenu,MENU_WARNING_TELEPORT,null);
                    GetGame().GetMission().AddActiveInputExcludes({"menu"});
                }
                break;
            }
            case ERPCs.RPC_INIT_SET_QUICKBAR:
                ref Param1<int> count = new Param1<int>(0);
                if ( ctx.Read( count ) );
                {
                    for ( int i = 0; i < count.param1 ; i++ )
                    {
                        m_QuickBarBase.OnSetEntityRPC(ctx);
                    }
                }
            break;
            case ERPCs.RPC_SYNC_THERMOMETER:
            {
                float value;
                if ( ctx.Read( value ) )
                    m_Hud.SetTemperature( value.ToString() + "#degrees_celsius" );
                break;
            }
            case ERPCs.RPC_CHECK_PULSE:
                ctx.Read(CachedObjectsParams.PARAM1_INT);
                EPulseType pulse;
                if ( (CachedObjectsParams.PARAM1_INT.param1 & ActionCheckPulse.TARGET_IRREGULAR_PULSE_BIT) == 0 )
                {
                    pulse = EPulseType.REGULAR;
                }
                else
                {
                    pulse = EPulseType.IRREGULAR;
                }
                int blood_level = ~ActionCheckPulse.TARGET_IRREGULAR_PULSE_BIT & CachedObjectsParams.PARAM1_INT.param1;
                if (m_CheckPulseLastTarget)
                {
                    m_CheckPulseLastTarget.SetLastUAMessage(ActionCheckPulse.GetPulseMessage(pulse, blood_level));
                }
            break;
            //woodcutting
            case PlantType.TREE_HARD:
                SoundHardTreeFallingPlay();
            break;
            case PlantType.TREE_SOFT:
                SoundSoftTreeFallingPlay();
            break;
            case PlantType.BUSH_HARD:
                SoundHardBushFallingPlay();
            break;
            case PlantType.BUSH_SOFT:
                SoundSoftBushFallingPlay();
            break;
            case ERPCs.RPC_DEBUG_MONITOR_FLT:
                if ( m_DebugMonitorValues )
                {
                    m_DebugMonitorValues.OnRPCFloat(ctx);
                }
            break;
            case ERPCs.RPC_DEBUG_MONITOR_STR:
                if ( m_DebugMonitorValues )
                {
                    m_DebugMonitorValues.OnRPCString(ctx);
                }
            break;
            #endif
            /*
            case ERPCs.RPC_CRAFTING_INVENTORY_INSTANT:
                ref Param3<int, ItemBase, ItemBase> craftParam = new Param3<int, ItemBase, ItemBase>(-1, NULL, NULL);
                if (ctx.Read( craftParam ) )
                {
                    m_ModuleRecipesManager.PerformRecipeServer(craftParam.param1, craftParam.param2, craftParam.param3, this);
                }
            break;
            */
            #ifdef DEVELOPER
            case ERPCs.DEV_CAMERA_TOOLS_CAM_DATA:
            {
                if (!m_CameraToolsMenuClient)
                {
                    m_CameraToolsMenuClient = new CameraToolsMenuClient();
                }
                m_CameraToolsMenuClient.OnRPC(ctx);
                break;
            }
            case ERPCs.DEV_RPC_AGENT_RESET:
            {
                bool val;
                if ( ctx.Read( val ) )
                    m_AgentPool.RemoveAllAgents();
                break;
            }
            case ERPCs.DEV_REQUEST_PLAYER_DEBUG:
                PluginRemotePlayerDebugServer plugin_remote_server = PluginRemotePlayerDebugServer.Cast( GetPlugin(PluginRemotePlayerDebugServer) );
                plugin_remote_server.OnRPC(ctx, this);
            break;
            case ERPCs.DEV_PLAYER_DEBUG_DATA:
                PluginRemotePlayerDebugClient plugin_remote_client = PluginRemotePlayerDebugClient.Cast( GetPlugin(PluginRemotePlayerDebugClient) );
                PluginDeveloper plugin_dev = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
                if( plugin_dev.m_ScriptConsole )
                    plugin_dev.m_ScriptConsole.OnRPCEx(rpc_type, ctx);
                else
                    plugin_remote_client.OnRPC(ctx);
            break;
            case ERPCs.DEV_AGENT_GROW:
            {
                m_AgentPool.RemoteGrowRequestDebug(ctx);
                break;
            }
            case ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG_ON:
                if ( GetSymptomManager() )
                {
                    GetSymptomManager().OnRPCDebug(ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG_ON, ctx);
                }
            break;
            case ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG:
                if ( GetSymptomManager() )
                {
                    GetSymptomManager().OnRPCDebug(ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG, ctx);
                }
            break;
            case ERPCs.RPC_PLAYER_SYMPTOMS_EXIT:
                if ( GetSymptomManager() )
                {
                    GetSymptomManager().OnRPCDebug(ERPCs.RPC_PLAYER_SYMPTOMS_EXIT, ctx);
                }
            break;
            case ERPCs.RPC_ITEM_DIAG_CLOSE:
            {
                PluginItemDiagnostic mid = PluginItemDiagnostic.Cast( GetPlugin(PluginItemDiagnostic) );
                mid.StopWatchRequest(this);
                break;
            }
            case ERPCs.DEV_DIAGMENU_SUBSCRIBE:
            {
                PluginItemDiagnostic.Cast( GetPlugin(PluginItemDiagnostic)).OnRPC(this, rpc_type, ctx);
                break;
            }
            case ERPCs.DEV_RPC_PLAYER_RESET:
            {
                if ( ctx.Read( CachedObjectsParams.PARAM1_BOOL ) )
                {
                    ResetPlayer(CachedObjectsParams.PARAM1_BOOL.param1);
                }
                break;
            }
            case ERPCs.DEV_RPC_INVENTORY_ACCESS:
            {
                if ( ctx.Read( CachedObjectsParams.PARAM1_BOOL ) )
                {
                    DEBUG_INVENTORY_ACCESS = CachedObjectsParams.PARAM1_BOOL.param1;
                }
                break;
            }
            case ERPCs.DEV_RPC_SERVER_SCRIPT:
            {
                //PluginItemDiagnostic plugin = PluginItemDiagnostic.Cast( GetPlugin(PluginItemDiagnostic) );
                //SetDebugDeveloper_item(plugin.GetWatchedItem(this));//!! needs to be inside DEVELOPER ifdef
                if ( ctx.Read(CachedObjectsParams.PARAM1_STRING))
                {
                    _player = this;
                    string code = CachedObjectsParams.PARAM1_STRING.param1;
                    bool success = GetGame().ExecuteEnforceScript("void scConsMain() \n{\n" + code + "\n}\n", "scConsMain");
                    CachedObjectsParams.PARAM1_BOOL.param1 = success;
                    RPCSingleParam(ERPCs.DEV_RPC_SERVER_SCRIPT_RESULT, CachedObjectsParams.PARAM1_BOOL,true, GetIdentity());
                }
                break;
            }
            case ERPCs.DEV_RPC_SERVER_SCRIPT_RESULT:
            {
                PluginDeveloper dev = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
                if( dev.m_ScriptConsole )
                        dev.m_ScriptConsole.OnRPCEx(rpc_type, ctx);
                break;
            }
            case ERPCs.DEV_SET_DEV_ITEM:
            {
                Param1<EntityAI> ent = new Param1<EntityAI>(null);
                if (ctx.Read(ent) && ent.param1)
                {
                    PluginItemDiagnostic mid2 = PluginItemDiagnostic.Cast( GetPlugin(PluginItemDiagnostic) );
                    mid2.RegisterDebugItem( ent.param1, this);
                }
                //SetDebugDeveloper_item(this);
                break;
            }
            case ERPCs.RPC_ITEM_DIAG:
            {
                Param1<EntityAI> p1 = new Param1<EntityAI>(null);
                if (ctx.Read(p1))
                {
                    PluginItemDiagnostic plgn = PluginItemDiagnostic.Cast( GetPlugin( PluginItemDiagnostic ) );
                    plgn.OnRPC( p1.param1, ctx );
                }
                break;
            }
            case ERPCs.DEV_REQUEST_UTS_DEBUG:
                PluginUniversalTemperatureSourceServer plugin_uts_server = PluginUniversalTemperatureSourceServer.Cast(GetPlugin(PluginUniversalTemperatureSourceServer));
                plugin_uts_server.OnRPC(ctx, this);
            break;
            case ERPCs.DEV_UTS_DEBUG_DATA:
                PluginUniversalTemperatureSourceClient plugin_uts_client = PluginUniversalTemperatureSourceClient.Cast(GetPlugin(PluginUniversalTemperatureSourceClient));
                plugin_uts_client.OnRPC(ctx);
            break;
            #endif
        }
        #ifdef DIAG_DEVELOPER
            PluginDeveloper module_rc = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
            if ( module_rc )
                module_rc.OnRPC(this, rpc_type, ctx);
            PluginDeveloperSync module_rcs = PluginDeveloperSync.Cast( GetPlugin(PluginDeveloperSync) );
            if ( module_rcs )
                module_rcs.OnRPC(this, rpc_type, ctx);
        #endif
        #ifdef DEVELOPER
            PluginDiagMenu plugin_diag_menu = PluginDiagMenu.Cast( GetPlugin(PluginDiagMenu) );
            if ( plugin_diag_menu )
                plugin_diag_menu.OnRPC(this, rpc_type, ctx);
        #endif
    }
References _player, Mission::AddActiveInputExcludes(), ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::ExecuteEnforceScript(), CGame::GetCallQueue(), GetGame(), GetInstanceType(), CGame::GetMission(), GetPlugin(), ActionCheckPulse::GetPulseMessage(), GetVirtualHud(), m_Hud, MENU_WARNING_ITEMDROP, MENU_WARNING_TELEPORT, CachedObjectsParams::PARAM1_BOOL, CachedObjectsParams::PARAM1_INT, CachedObjectsParams::PARAM1_STRING, PluginItemDiagnostic(), Serializer::Read(), RPCSingleParam(), Hud::SetTemperature(), ActionCheckPulse::TARGET_IRREGULAR_PULSE_BIT, and float::ToString().
OnScheduledTick()
void ManBase::OnScheduledTick (float deltaTime) inline private
Definition at line 2479 of file playerbase.c.
    {
        if( !IsPlayerSelected() || !IsAlive() ) return;
        if( m_ModifiersManager ) m_ModifiersManager.OnScheduledTick(deltaTime);
        if( m_NotifiersManager ) m_NotifiersManager.OnScheduledTick();
        if( m_TrasferValues ) m_TrasferValues.OnScheduledTick(deltaTime);
        if( m_VirtualHud ) m_VirtualHud.OnScheduledTick();
        if( GetBleedingManagerServer() ) GetBleedingManagerServer().OnTick(deltaTime);
        // Check if electric device needs to be unplugged
        ItemBase heldItem = GetItemInHands();
        if ( heldItem && heldItem.HasEnergyManager() && heldItem.GetCompEM().IsPlugged() )
        {
            // Now we know we are working with an electric device which is plugged into a power source.
            EntityAI placed_entity = heldItem;
            // Unplug the device when the player is too far from the power source.
            placed_entity.GetCompEM().UpdatePlugState();
        }
    }
References IsAlive(), IsPlayerSelected(), and m_VirtualHud.
OnSelectPlayer()
void ManBase::OnSelectPlayer () inline private
add callbacks for ai target system
Definition at line 5603 of file playerbase.c.
    {
        //Print("PlayerBase | OnSelectPlayer()");
        m_QuickBarBase.updateSlotsCount();
        m_PlayerSelected = true;
        m_WeaponManager.SortMagazineAfterLoad();
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            SetAITargetCallbacks(new AITargetCallbacksPlayer(this));
            array<ref Param> params = new array<ref Param>;
            if ( m_aQuickBarLoad )
            {
                int count = m_aQuickBarLoad.Count();
                Param1<int> paramCount = new Param1<int>(count);
                params.Insert(paramCount);
                for (int i = 0; i < count; i++)
                {
                    m_QuickBarBase.OnSetEntityNoSync(m_aQuickBarLoad.Get(i).param1,m_aQuickBarLoad.Get(i).param2);
                    params.Insert(m_aQuickBarLoad.Get(i));
                }
                if (count > 0 && GetGame().IsMultiplayer() )
                {
                    GetGame().RPC(this, ERPCs.RPC_INIT_SET_QUICKBAR, params, true, GetIdentity());
                }
                m_aQuickBarLoad = NULL;
            }
            GetSoftSkillsManager().InitSpecialty( GetStatSpecialty().Get() );
            GetModifiersManager().SetModifiers(true);
            SetSynchDirty();
            if ( GetGame().IsMultiplayer() )
            {
                //Drop item warning
                if ( m_ProcessUIWarning )
                {
                    GetGame().RPCSingleParam(this, ERPCs.RPC_WARNING_ITEMDROP, null, true, GetIdentity());
                    m_ProcessUIWarning = false;
                }
                GetGame().GetMission().SyncRespawnModeInfo(GetIdentity());
            }
        }
        CheckForGag();
        if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            m_ActionManager = new ActionManagerServer(this);
            m_ConstructionActionData = new ConstructionActionData();
        }
        else if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
        {
            m_ActionManager = new ActionManagerClient(this);
            m_CraftingManager = new CraftingManager(this,m_ModuleRecipesManager);
            m_ConstructionActionData = new ConstructionActionData();
        }
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            //m_PlayerLightManager = new PlayerLightManager(this);
            if (GetGame().GetMission())
            {
                GetGame().GetMission().ResetGUI();
                // force update player
                GetDayZGame().GetBacklit().UpdatePlayer(true);
            }
            m_DeathCheckTimer = new Timer();
            m_DeathCheckTimer.Run(0.1, this, "CheckDeath", null, true);
            PPEManagerStatic.GetPPEManager().StopAllEffects(PPERequesterCategory.ALL);
            CheckForBurlap();
            int characterCount = GetGame().GetMenuData().GetCharactersCount() - 1;
            int idx = GetGame().GetMenuData().GetLastPlayedCharacter();
            if ( idx == GameConstants.DEFAULT_CHARACTER_MENU_ID || idx > characterCount )
            {
                GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(SetNewCharName);
            }
            GetGame().GetMission().EnableAllInputs(true);
            m_PresenceNotifier = PluginPresenceNotifier.Cast( GetPlugin( PluginPresenceNotifier ) );
            m_PresenceNotifier.Init(this);
            OnGameplayDataHandlerSync();//only here for legacy reasons
        }
#ifdef BOT
        m_Bot = new Bot(this);
        m_Bot.Start(true, new MyBotTrigger(this));
#endif
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, GameConstants::DEFAULT_CHARACTER_MENU_ID, Mission::EnableAllInputs(), Get(), CGame::GetCallQueue(), MenuData::GetCharactersCount(), GetDayZGame(), GetGame(), GetInstanceType(), MenuData::GetLastPlayedCharacter(), CGame::GetMenuData(), CGame::GetMission(), GetPlugin(), PPEManagerStatic::GetPPEManager(), m_PlayerSelected, PlayerBase::OnGameplayDataHandlerSync(), PluginPresenceNotifier(), Mission::ResetGUI(), CGame::RPC(), CGame::RPCSingleParam(), and Mission::SyncRespawnModeInfo().
OnSpawnedFromConsole()
void ManBase::OnSpawnedFromConsole () inline private
Definition at line 4496 of file playerbase.c.
    {
        if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            GetGame().GetMission().AddDummyPlayerToScheduler( this );
        }
    }
References Mission::AddDummyPlayerToScheduler(), GetGame(), GetInstanceType(), and CGame::GetMission().
OnStanceChange()
override void ManBase::OnStanceChange (int previousStance, int newStance) inline private
Definition at line 3680 of file playerbase.c.
    {
        int prone = DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
        int notProne = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_RAISEDERECT | DayZPlayerConstants.STANCEMASK_RAISEDCROUCH;
        if ( ( IsStance(previousStance, prone) && IsStance(newStance, notProne) ) || ( IsStance(previousStance, notProne) && IsStance(newStance, prone) ) )
        {
            AbortWeaponEvent();
            GetWeaponManager().RefreshAnimationState();
        }
        if ( GetGame().IsServer() )
        {
            /*
            if (newStance == DayZPlayerConstants.STANCEIDX_PRONE)
            {
                //Print("Update anim");
                if (m_BrokenLegState == eBrokenLegs.BROKEN_LEGS)
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS;
                else if (m_BrokenLegState == eBrokenLegs.BROKEN_LEGS_SPLINT)
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS_SPLINT;
                m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.PRONE_ANIM_OVERRIDE;
                ForceUpdateInjuredState();
            }
            else if (previousStance == DayZPlayerConstants.STANCEIDX_PRONE || previousStance == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            {
                m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PRONE_ANIM_OVERRIDE;
                //Print("Update anim 2");
                if (m_BrokenLegState == eBrokenLegs.BROKEN_LEGS)
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.BROKEN_LEGS;
                else if (m_BrokenLegState == eBrokenLegs.BROKEN_LEGS_SPLINT)
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.BROKEN_LEGS_SPLINT;
                ForceUpdateInjuredState();
            }
            */
        }
    }
References AbortWeaponEvent(), GetGame(), GetWeaponManager(), and WeaponManager::RefreshAnimationState().
OnStoreLoad()
override bool ManBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 6641 of file playerbase.c.
    {
        //Print("---- PlayerBase OnStoreLoad START ----, version: "+version);
        m_aQuickBarLoad = new array<ref Param2<EntityAI,int>>;
        // todo :: this should be after base call !!!!
        if( version < 102 )//write removed in v. 102
        {
            if(!ctx.Read( m_StoreLoadVersion ))
                return false;
        }
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        // FSM of hands
        if ( !GetHumanInventory().OnStoreLoad(ctx, version) )
            return false;
        if ( !OnStoreLoadLifespan( ctx, version ) )
            return false;
        if ( GetDayZGame().IsServer() && GetDayZGame().IsMultiplayer() )
        {
            if(!GetPlayerStats().LoadStats(ctx, version)) // load stats
            {
                Print("---- failed to load PlayerStats  ----");
                return false;
            }
            if( version < m_ModifiersManager.GetStorageVersion() )//load modifiers !! WILL CANCEL REST OF STREAM IF UNSUPPORTED VERSION !!
            {
                Print("---- failed to load ModifiersManager, unsupported version   ----");
                return false;
            }
            else
            {
                if(!m_ModifiersManager.OnStoreLoad(ctx, version))
                {
                    Print("---- failed to load ModifiersManager, read fail  ----");
                    return false;
                }
            }
            if( version < m_AgentPool.GetStorageVersion() )//load agents !! WILL CANCEL REST OF STREAM IF UNSUPPORTED VERSION !!
            {
                Print("---- failed to load AgentPool, unsupported version   ----");
                return false;
            }
            else
            {
                if(!m_AgentPool.OnStoreLoad(ctx, version))
                {
                    Print("---- failed to load AgentPool, read fail  ----");
                    return false;
                }
            }
            if( version < GetSymptomManager().GetStorageVersion() )//load symptoms !! WILL CANCEL REST OF STREAM IF UNSUPPORTED VERSION !!
            {
                Print("---- failed to load SymptomManager, unsupported version   ----");
                return false;
            }
            else
            {
                if(!GetSymptomManager().OnStoreLoad(ctx, version))
                {
                    Print("---- failed to load SymptomManager, read fail  ----");
                    return false;
                }
            }
            if( version < GetBleedingManagerServer().GetStorageVersion() )//load bleeding manager !! WILL CANCEL REST OF STREAM IF UNSUPPORTED VERSION !!
            {
                Print("---- failed to load BleedingManagerServer, unsupported version  ----");
                return false;
            }
            else
            {
                if(!GetBleedingManagerServer().OnStoreLoad(ctx, version))
                {
                    Print("---- failed to load BleedingManagerServer, read fail  ----");
                    return false;
                }
            }
            if( version < m_PlayerStomach.GetStorageVersion() )//load PlayerStomach !! WILL CANCEL REST OF STREAM IF UNSUPPORTED VERSION !!
            {
                Print("---- failed to load PlayerStomach, unsupported version  ----");
                return false;
            }
            else
            {
                if(!m_PlayerStomach.OnStoreLoad(ctx, version))
                {
                    Print("---- failed to load PlayerStomach, read fail  ----");
                    return false;
                }
            }
            //Check for broken leg value
            if ( version >= 116 )
            {
                if (!ctx.Read( m_BrokenLegState ))
                {
                    return false;
                }
                if ( version <= 126 )// WHILE >= 116
                {
                    if (!ctx.Read( m_LocalBrokenState ))
                    {
                        return false;
                    }
                }
            }
            //Check for broken leg value
            if ( version >= 125 && (!ctx.Read( m_PersistentFlags )))
            {
                Print("---- failed to load Persistent Flags, read fail  ----");
                return false;
            }
        }
        Print("---- PlayerBase OnStoreLoad SUCCESS ----");
        return true;
    }
References GetDayZGame(), GetStorageVersion(), OnStoreLoad(), Print(), and Serializer::Read().
OnStoreLoadLifespan()
bool ManBase::OnStoreLoadLifespan (ParamsReadContext ctx, int version) inline private
Definition at line 6790 of file playerbase.c.
    {
        int lifespan_state = 0;
        if(!ctx.Read( lifespan_state ))
            return false;
        m_LifeSpanState = lifespan_state;
        int last_shaved = 0;
        if(!ctx.Read( last_shaved ))
            return false;
        m_LastShavedSeconds = last_shaved;
        if (version < 122)
        {
            bool bloody_hands_old;
            if(!ctx.Read(bloody_hands_old))
            return false;
            m_HasBloodyHandsVisible = bloody_hands_old;
        }
        else
        {
            int bloody_hands = 0;
            if(!ctx.Read( bloody_hands ))
                return false;
            m_HasBloodyHandsVisible = bloody_hands;
        }
        bool blood_visible = false;
        if(!ctx.Read( blood_visible ))
            return false;
        m_HasBloodTypeVisible = blood_visible;
        int blood_type = 0;
        if(!ctx.Read( blood_type ))
            return false;
        m_BloodType = blood_type;
        return true;
    }
References m_BloodType, and Serializer::Read().
OnStoreSave()
override void ManBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 6601 of file playerbase.c.
    {
        //Print("OnStoreSave");
        if( GetGame().SaveVersion() < 102 )
        {
            ctx.Write( ACT_STORE_SAVE_VERSION );//to be removed after we push 102+
        }
        super.OnStoreSave( ctx );
        GetHumanInventory().OnStoreSave(ctx); // FSM of hands
        OnStoreSaveLifespan( ctx );
        if ( GetDayZGame().IsServer() && GetDayZGame().IsMultiplayer() )
        {
            GetPlayerStats().SaveStats(ctx);// save stats
            m_ModifiersManager.OnStoreSave(ctx);// save modifiers
            m_AgentPool.OnStoreSave(ctx);//save agents
            GetSymptomManager().OnStoreSave(ctx);//save states
            if (GetBleedingManagerServer())
            {
                GetBleedingManagerServer().OnStoreSave(ctx);//save bleeding sources
            }
            m_PlayerStomach.OnStoreSave(ctx);
            ctx.Write( GetBrokenLegs() );
            //ctx.Write( m_LocalBrokenState );
            SaveAreaPersistenceFlag(ctx);
        }
    }
References GetDayZGame(), GetGame(), and Serializer::Write().
OnStoreSaveLifespan()
void ManBase::OnStoreSaveLifespan (ParamsWriteContext ctx) inline private
Definition at line 6781 of file playerbase.c.
    {
        ctx.Write( m_LifeSpanState );
        ctx.Write( m_LastShavedSeconds );
        ctx.Write( m_HasBloodyHandsVisible );
        ctx.Write( m_HasBloodTypeVisible );
        ctx.Write( m_BloodType );
    }
References m_BloodType, and Serializer::Write().
OnSyncJuncture()
override void ManBase::OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
SyncJunctures
Definition at line 7567 of file playerbase.c.
    {
        super.OnSyncJuncture(pJunctureID, pCtx);
        switch( pJunctureID )
        {
            case DayZPlayerSyncJunctures.SJ_INJURY:
                eInjuryHandlerLevels level;
                bool enable;
                DayZPlayerSyncJunctures.ReadInjuryParams(pCtx, enable, level);
                m_InjuryHandler.SetInjuryCommandParams(enable, level);
                break;
            case DayZPlayerSyncJunctures.SJ_PLAYER_STATES:
                GetSymptomManager().SetAnimation(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_QUICKBAR_SET_SHORTCUT:
                OnQuickbarSetEntityRequest(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_INVENTORY:
                GetInventory().OnInventoryJunctureFromServer(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_INVENTORY_REPAIR:
                GetInventory().OnInventoryJunctureRepairFromServer(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_ACTION_INTERRUPT:
            case DayZPlayerSyncJunctures.SJ_ACTION_ACK_ACCEPT:
            case DayZPlayerSyncJunctures.SJ_ACTION_ACK_REJECT:
                m_ActionManager.OnSyncJuncture(pJunctureID,pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_WEAPON_ACTION_ACK_ACCEPT:
            case DayZPlayerSyncJunctures.SJ_WEAPON_ACTION_ACK_REJECT:
            case DayZPlayerSyncJunctures.SJ_WEAPON_SET_JAMMING_CHANCE:
                m_WeaponManager.OnSyncJuncture(pJunctureID,pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_UNCONSCIOUSNESS:
                DayZPlayerSyncJunctures.ReadPlayerUnconsciousnessParams(pCtx, m_ShouldBeUnconscious);
                break;
            case DayZPlayerSyncJunctures.SJ_PLAYER_ADD_MODIFIER:
                GetSymptomManager().SetAnimation(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_KURU_REQUEST:
                float amount;
                if(DayZPlayerSyncJunctures.ReadKuruRequest(pCtx, amount))
                {
                    if(GetAimingModel() && IsFireWeaponRaised())
                    {
                        GetAimingModel().RequestKuruShake(amount);
                    }
                }
                break;
            case DayZPlayerSyncJunctures.SJ_GESTURE_REQUEST :
                m_EmoteManager.OnSyncJuncture(pJunctureID, pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_WEAPON_LIFT:
                SetLiftWeapon(pJunctureID, pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_ADS_RESET:
                m_ResetADS = true;
                break;
            case DayZPlayerSyncJunctures.SJ_DELETE_ITEM:
                SetToDelete(pCtx);
                break;
            case DayZPlayerSyncJunctures.SJ_BROKEN_LEGS:
                m_BrokenLegsJunctureReceived = true;
                DayZPlayerSyncJunctures.ReadBrokenLegsParamsEx(pCtx, m_BrokenLegState);
            break;
            case DayZPlayerSyncJunctures.SJ_SHOCK :
                DayZPlayerSyncJunctures.ReadShockParams(pCtx, m_CurrentShock);
            break;
            case DayZPlayerSyncJunctures.SJ_STAMINA:
                m_StaminaHandler.OnSyncJuncture(pJunctureID, pCtx);
            break;
            case DayZPlayerSyncJunctures.SJ_STAMINA_MISC:
                m_StaminaHandler.OnSyncJuncture(pJunctureID, pCtx);
            break;
        }
    }
References GetAimingModel(), IsFireWeaponRaised(), m_ResetADS, m_ShouldBeUnconscious, m_StaminaHandler, DayZPlayerSyncJunctures::ReadBrokenLegsParamsEx(), DayZPlayerSyncJunctures::ReadInjuryParams(), DayZPlayerSyncJunctures::ReadKuruRequest(), DayZPlayerSyncJunctures::ReadPlayerUnconsciousnessParams(), DayZPlayerSyncJunctures::ReadShockParams(), DayZPlayerImplementAiming::RequestKuruShake(), DayZPlayerSyncJunctures::SJ_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_ACTION_ACK_REJECT, DayZPlayerSyncJunctures::SJ_ACTION_INTERRUPT, DayZPlayerSyncJunctures::SJ_ADS_RESET, DayZPlayerSyncJunctures::SJ_BROKEN_LEGS, DayZPlayerSyncJunctures::SJ_DELETE_ITEM, DayZPlayerSyncJunctures::SJ_GESTURE_REQUEST, DayZPlayerSyncJunctures::SJ_INJURY, DayZPlayerSyncJunctures::SJ_INVENTORY, DayZPlayerSyncJunctures::SJ_INVENTORY_REPAIR, DayZPlayerSyncJunctures::SJ_KURU_REQUEST, DayZPlayerSyncJunctures::SJ_PLAYER_ADD_MODIFIER, DayZPlayerSyncJunctures::SJ_PLAYER_STATES, DayZPlayerSyncJunctures::SJ_QUICKBAR_SET_SHORTCUT, DayZPlayerSyncJunctures::SJ_SHOCK, DayZPlayerSyncJunctures::SJ_STAMINA, DayZPlayerSyncJunctures::SJ_STAMINA_MISC, DayZPlayerSyncJunctures::SJ_UNCONSCIOUSNESS, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_REJECT, DayZPlayerSyncJunctures::SJ_WEAPON_LIFT, and DayZPlayerSyncJunctures::SJ_WEAPON_SET_JAMMING_CHANCE.
OnThrowingModeChange()
override void ManBase::OnThrowingModeChange (bool change_to_enabled) inline private
Definition at line 3803 of file playerbase.c.
    {
        if (change_to_enabled)
        {
            PlacingCancelLocal();
            PlacingCancelServer();
        }
    }
OnTick()
void ManBase::OnTick () inline private
Definition at line 2564 of file playerbase.c.
    {
        float deltaT = (GetGame().GetTime() - m_LastTick) / 1000;
        if ( m_LastTick < 0 )  deltaT = 0;//first tick protection
        m_LastTick = GetGame().GetTime();
        //PrintString("deltaT: " + deltaT);
        //PrintString("at time: " + m_LastTick);
        OnScheduledTick(deltaT);
    }
References GetGame(), CGame::GetTime(), m_LastTick, and OnScheduledTick().
OnUnconsciousStart()
void ManBase::OnUnconsciousStart () inline private
Definition at line 3071 of file playerbase.c.
    {
        CloseInventoryMenu();
        //if( GetInventory() ) GetInventory().LockInventory(LOCK_FROM_SCRIPT);
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            SetInventorySoftLock(true);
            if(m_LastCommandBeforeUnconscious != DayZPlayerConstants.COMMANDID_VEHICLE)
            {
                EntityAI entity_in_hands = GetHumanInventory().GetEntityInHands();
                if ( entity_in_hands && CanDropEntity(entity_in_hands) && !IsRestrained() )
                {
                    DropItem(ItemBase.Cast(entity_in_hands));
                }
            }
            GetGame().GetSoundScene().SetSoundVolume(0,2);
            m_EffectWidgets.AddSuspendRequest(EffectWidgetSuspends.UNCON);
        }
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            SetSynchDirty();
            // disable voice communication
            GetGame().EnableVoN(this, false);
            if ( m_AdminLog )
            {
                m_AdminLog.UnconStart( this );
            }
            // When we fall uncon we force out of block
            if ( GetMeleeFightLogic() )
            {
                GetMeleeFightLogic().SetBlock( false );
            }
        }
        SetMasterAttenuation("UnconsciousAttenuation");
        //PrintString("OnUnconsciousStart");
    }
References GameplayEffectWidgets_base::AddSuspendRequest(), CGame::EnableVoN(), GetGame(), GetInstanceType(), GetMeleeFightLogic(), CGame::GetSoundScene(), IsRestrained(), m_AdminLog, and m_LastCommandBeforeUnconscious.
OnUnconsciousStop()
void ManBase::OnUnconsciousStop (int pCurrentCommandID) inline private
Definition at line 3115 of file playerbase.c.
    {
        m_UnconRefillModifier =1;
        SetSynchDirty();
        //if( GetInventory() ) GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        m_UnconsciousTime = 0;
        m_UnconsciousVignetteTarget = 2;
        if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            if ( pCurrentCommandID != DayZPlayerConstants.COMMANDID_DEATH )
            {
                GetGame().GetSoundScene().SetSoundVolume(g_Game.m_volume_sound,1);
                PPERequesterBank.GetRequester(PPERequester_UnconEffects).Stop();
                GetGame().GetMission().GetHud().ShowHudUI( true );
                GetGame().GetMission().GetHud().ShowQuickbarUI(true);
                if ( GetGame().GetUIManager().IsDialogVisible() )
                {
                    GetGame().GetUIManager().CloseDialog();
                }
                if ( GetGame().GetUIManager().IsMenuOpen(MENU_RESPAWN_DIALOGUE) )
                {
                    GetGame().GetUIManager().FindMenu(MENU_RESPAWN_DIALOGUE).Close();
                }
            }
            SetInventorySoftLock(false);
            m_EffectWidgets.RemoveSuspendRequest(EffectWidgetSuspends.UNCON);
        }
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            // enable voice communication
            if(IsAlive())
                GetGame().EnableVoN(this, true);
            if ( m_AdminLog )
            {
                m_AdminLog.UnconStop( this );
            }
        }
        SetMasterAttenuation("");
        //PrintString("OnUnconsciousStop");
    }
References UIManager::CloseDialog(), CGame::EnableVoN(), UIManager::FindMenu(), g_Game, GetGame(), Mission::GetHud(), GetInstanceType(), CGame::GetMission(), CGame::GetSoundScene(), CGame::GetUIManager(), IsAlive(), m_AdminLog, MENU_RESPAWN_DIALOGUE, GameplayEffectWidgets_base::RemoveSuspendRequest(), Hud::ShowHudUI(), and Hud::ShowQuickbarUI().
OnUnconsciousUpdate()
void ManBase::OnUnconsciousUpdate (float pDt, int last_command) inline private
Definition at line 3159 of file playerbase.c.
    {
        m_UnconsciousTime += pDt;
        if( GetGame().IsServer() )
        {
            int shock_simplified = SimplifyShock();
            if( m_ShockSimplified != shock_simplified )
            {
                m_ShockSimplified = shock_simplified;
                SetSynchDirty();
            }
            //PrintString(last_command.ToString());
            //PrintString(DayZPlayerConstants.COMMANDID_SWIM.ToString());
            if( m_UnconsciousTime > PlayerConstants.UNCONSCIOUS_IN_WATER_TIME_LIMIT_TO_DEATH && last_command == DayZPlayerConstants.COMMANDID_SWIM )
            {
                SetHealth("","",-100);
            }
        }
        if( !GetGame().IsDedicatedServer() )
        {
            GetGame().GetMission().GetHud().ShowHudUI( false );
            GetGame().GetMission().GetHud().ShowQuickbarUI(false);
            if(GetPulseType() == EPulseType.REGULAR)
            {
                float shock_simple_normalized = GetSimplifiedShockNormalized();
                float sin = Math.Sin(m_UnconsciousTime * 0.3);
                float sin_normalized = (sin + 1) / 2;
                if(sin_normalized < 0.05)
                {
                    m_UnconsciousVignetteTarget = (1 - shock_simple_normalized / 3) * 2/*vignette max*/;
                }
                float vignette = Math.Lerp(2,m_UnconsciousVignetteTarget, sin_normalized);
                //PrintString(m_UnconsciousVignetteTarget.ToString());
                m_UnconParam.param1 = vignette;
                PPERequesterBank.GetRequester(PPERequester_UnconEffects).Start(m_UnconParam);
            }
        }
    }
References GetGame(), Mission::GetHud(), CGame::GetMission(), Math::Lerp(), SetHealth(), Hud::ShowHudUI(), Hud::ShowQuickbarUI(), Math::Sin(), and PlayerConstants::UNCONSCIOUS_IN_WATER_TIME_LIMIT_TO_DEATH.
OnVariablesSynchronized()
override void ManBase::OnVariablesSynchronized () inline private
Remotely Activated Item Behaviour refresh on item is in hands
Definition at line 5487 of file playerbase.c.
    {
        super.OnVariablesSynchronized();
        if ( m_ModuleLifespan )
        {
            m_ModuleLifespan.SynchLifespanVisual( this, m_LifeSpanState, m_HasBloodyHandsVisible, m_HasBloodTypeVisible, m_BloodType );
            if (m_LifespanLevelLocal != m_LifeSpanState) //client solution, lifespan level changed
            {
                m_LifespanLevelLocal = m_LifeSpanState;
                UpdateHairSelectionVisibility();
            }
        }
        CheckSoundEvent();
        if ( GetBleedingManagerRemote() && IsPlayerLoaded() )
        {
            GetBleedingManagerRemote().OnVariablesSynchronized(GetBleedingBits());
        }
        if( m_CorpseStateLocal != m_CorpseState && (IsPlayerLoaded() || IsControlledPlayer()) )
        {
            UpdateCorpseState();
        }
        if(m_RefreshAnimStateIdx != m_LocalRefreshAnimStateIdx)
        {
            RefreshHandAnimationState(396); //mean animation blend time
            m_LocalRefreshAnimStateIdx = m_RefreshAnimStateIdx;
        }
        //-------MODIFIERS START--------
        if (m_SyncedModifiers != m_SyncedModifiersPrev)
        {
            int diff = (m_SyncedModifiers & ~m_SyncedModifiersPrev) | (~m_SyncedModifiers & m_SyncedModifiersPrev);//XOR gets us a mask for modifiers that changed by either deactivating, or activating
            if (eModifierSyncIDs.MODIFIER_SYNC_DROWNING & diff)//has this modifier's status as active/inactive changed ?
            {
                if (eModifierSyncIDs.MODIFIER_SYNC_DROWNING & m_SyncedModifiers)//is this modifier currently active ? if so, it means it's been just activated
                {
                    SetDrowning(true);
                }
                else
                {
                    SetDrowning(false);
                }
            }
            m_SyncedModifiersPrev = m_SyncedModifiers;
        }
        //-------MODIFIERS END--------
        HandleBrokenLegsSync();
        ItemBase itemHands = GetItemInHands();
        if (itemHands)
        {
            RemotelyActivatedItemBehaviour raib = itemHands.GetRemotelyActivatedItemBehaviour();
            if (raib)
            {
                raib.OnVariableSynchronized();
            }
        }
    }
References m_BloodType, and RemotelyActivatedItemBehaviour::OnVariableSynchronized().
OnVehicleSeatDriverEnter()
void ManBase::OnVehicleSeatDriverEnter () inline private
Definition at line 3785 of file playerbase.c.
    {
        //Print("OnVehicleSeatDriverEnter");
        m_IsVehicleSeatDriver = true;
        if( m_Hud )
            m_Hud.ShowVehicleInfo();
    }
References m_Hud, and Hud::ShowVehicleInfo().
OnVehicleSeatDriverLeft()
void ManBase::OnVehicleSeatDriverLeft () inline private
Definition at line 3794 of file playerbase.c.
    {
        //Print("OnVehicleSeatDriverLeft");
        m_IsVehicleSeatDriver = false;
        if( m_Hud )
            m_Hud.HideVehicleInfo();
    }
References Hud::HideVehicleInfo(), and m_Hud.
OnVehicleSwitchSeat()
void ManBase::OnVehicleSwitchSeat (int seatIndex) inline private
Definition at line 3773 of file playerbase.c.
    {
        if ( seatIndex == DayZPlayerConstants.VEHICLESEAT_DRIVER )
        {
            OnVehicleSeatDriverEnter();
        }
        else
        {
            OnVehicleSeatDriverLeft();
        }
    }
OnVoiceEvent()
void ManBase::OnVoiceEvent (PlayerSoundEventBase voice_event) inline private
Definition at line 5787 of file playerbase.c.
    {
        if (m_EffectWidgets)
        {
            MaskBase mask = MaskBase.Cast(GetInventory().FindAttachment(InventorySlots.MASK));
            if (mask)
            {
                UpdateMaskBreathWidget(mask, true);
                //m_EffectWidgets.SetBreathIntensityStamina(GetStaminaHandler().GetStaminaCap(),GetStaminaHandler().GetStamina());
            }
        }
    }
References FindAttachment().
OnVoiceEventPlayback()
void ManBase::OnVoiceEventPlayback (PlayerSoundEventBase voice_event, AbstractWave callback, float playback_time) inline private
called every cmd handler tick during a playback of PlayerSoundEvent, m_ProcessPlaybackEvent needs to be enabled on the PlayerSoundEvent
Definition at line 5802 of file playerbase.c.
    {
        if (m_EffectWidgets)
        {
            MaskBase mask = MaskBase.Cast(GetInventory().FindAttachment(InventorySlots.MASK));
            if (mask)
            {
                if ( m_EffectWidgets.m_MaskWidgetUpdateCount < 2 && callback.GetLength() > 2 && playback_time > 0.5  )
                    UpdateMaskBreathWidget(mask);
            }
        }
    }
References FindAttachment(), and AbstractWave::GetLength().
PhysicalPredictiveDropItem()
override bool ManBase::PhysicalPredictiveDropItem (EntityAI entity, bool heavy_item_only = true) inline private
Definition at line 8651 of file playerbase.c.
    {
        vector dir;
        ItemBase item = ItemBase.Cast(entity);
        if (GetItemInHands() == item) //from hands
        {
            //HOTFIX
            return PredictiveDropEntity(item);
            if (entity.ConfigGetString("physLayer") != "item_large" && heavy_item_only)
            {
                return PredictiveDropEntity(item);
            }
            else
            {
                dir = GetOrientation();
                //item.m_ItemBeingDropped = true;
                return GetHumanInventory().ThrowEntity(item,dir,0);
            }
        }
        else //from anywhere else
        {
            ActionManagerClient mngr_client;
            if (CastTo(mngr_client,m_ActionManager))
            {
                ActionTarget atrg = new ActionTarget(null, null, -1, vector.Zero, -1);
                if ( mngr_client.GetAction(ActionDropItemSimple).Can(this,atrg,item) )
                {
                    //Param1<bool> p1 = new Param1<bool>(false);
                    //p1.param1 = heavy_item_only;
                    mngr_client.PerformActionStart(mngr_client.GetAction(ActionDropItemSimple),atrg,item/*,p1*/);
                    return true;
                }
                return false;
            }
            else
                return true;
        }
    }
References ActionTarget, ActionManagerBase::GetAction(), GetOrientation(), ActionManagerClient::PerformActionStart(), and vector::Zero.
PlacingCancelLocal()
void ManBase::PlacingCancelLocal () inline private
Definition at line 2080 of file playerbase.c.
    {
        EntityAI entity_in_hands = GetHumanInventory().GetEntityInHands();
        if ( entity_in_hands && entity_in_hands.HasEnergyManager() )
        {
            if ( entity_in_hands.GetCompEM().IsPlugged() )
            {
                entity_in_hands.OnPlacementCancelled( this );
            }
        }
        delete m_HologramLocal;
    }
PlacingCancelServer()
void ManBase::PlacingCancelServer () inline private
Definition at line 2054 of file playerbase.c.
    {
        EntityAI entity_in_hands = GetHumanInventory().GetEntityInHands();
        if ( IsPlacingServer() )
        {
            GetHologramServer().GetParentEntity().OnPlacementCancelled( this );
            delete m_HologramServer;
            return;
        }
        else if ( entity_in_hands && entity_in_hands.HasEnergyManager() )
        {
            if ( entity_in_hands.GetCompEM().IsPlugged() )
            {
                entity_in_hands.OnPlacementCancelled( this );
            }
        }
    }
PlacingCompleteLocal()
void ManBase::PlacingCompleteLocal () inline private
Definition at line 2098 of file playerbase.c.
    {
        delete m_HologramLocal;
    }
PlacingCompleteServer()
void ManBase::PlacingCompleteServer () inline private
Definition at line 2093 of file playerbase.c.
    {
        delete m_HologramServer;
    }
PlacingStartLocal()
void ManBase::PlacingStartLocal (ItemBase item) inline private
Definition at line 2045 of file playerbase.c.
    {
        if (GetGame().IsMultiplayer() && GetGame().IsServer())
            return;
        m_HologramLocal = new Hologram( this, GetLocalProjectionPosition(), item );
        GetHologramLocal().GetProjectionEntity().OnPlacementStarted( this );
    }
References GetGame().
PlacingStartServer()
void ManBase::PlacingStartServer (ItemBase item) inline private
Definition at line 2035 of file playerbase.c.
    {
        m_HologramServer = new Hologram( this, GetLocalProjectionPosition(), item );
        GetHologramServer().SetProjectionPosition( GetLocalProjectionPosition() );
        GetHologramServer().SetProjectionOrientation( GetLocalProjectionOrientation() );
        GetHologramServer().GetProjectionEntity().OnPlacementStarted( this );
        GetHologramServer().CheckPowerSource();
        GetHologramServer().RefreshVisual();
    }
PlayAttachmentDropSound()
void ManBase::PlayAttachmentDropSound () inline private
Definition at line 5012 of file playerbase.c.
    {
        //TODO
    }
PlayerBase()
void ManBase::PlayerBase () inline private
Definition at line 276 of file playerbase.c.
    {
        Init();
    }
References Init().
PlaySound()
override SoundOnVehicle ManBase::PlaySound (string sound_name, float range, bool create_local = false) inline private
Definition at line 4530 of file playerbase.c.
    {
        return BetaSound.SaySound(this, sound_name, range, false);
    }
References BetaSound::SaySound().
PlaySoundEvent()
override bool ManBase::PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false) inline private
Definition at line 7073 of file playerbase.c.
    {
        return PlaySoundEventEx(id, from_anim_system, is_from_server);
    }
References PlaySoundEventEx().
PlaySoundEventEx()
override bool ManBase::PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false, int param = 0) inline private
Definition at line 7078 of file playerbase.c.
    {
        if (!m_PlayerSoundEventHandler)
        {
            return false;
        }
        return m_PlayerSoundEventHandler.PlayRequestEx(id, is_from_server, param);
    }
References m_PlayerSoundEventHandler.
PredictiveDropEntity()
override bool ManBase::PredictiveDropEntity (notnull EntityAI item) inline private
Definition at line 8090 of file playerbase.c.
    {
        bool can_detach;
        if (CanRedirectToWeaponManager(item,can_detach))
        {
            if (can_detach)
            {
                vector m4[4];
                Math3D.MatrixIdentity4(m4);
                GameInventory.PrepareDropEntityPos(this, item, m4);
                InventoryLocation il = new InventoryLocation;
                il.SetGround(item, m4);
                return GetWeaponManager().DetachMagazine(il);
            }
            return false;
        }
        return super.PredictiveDropEntity(item);
    }
References WeaponManager::DetachMagazine(), GetWeaponManager(), Math3D::MatrixIdentity4(), and InventoryLocation::SetGround().
PredictiveForceSwapEntities()
override bool ManBase::PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst) inline private
Definition at line 8168 of file playerbase.c.
    {
        ForceStandUpForHeavyItemsSwap(item1, item2);
        InventoryLocation il = new InventoryLocation;
        if ( item1.IsHeavyBehaviour() && item1.GetInventory().GetCurrentInventoryLocation(il) && il.GetType() == InventoryLocationType.GROUND && !m_ActionManager.GetRunningAction() )
        {
            //Print("override bool PredictiveForceSwapEntities (notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)");
            ActionManagerClient mngr_client;
            CastTo(mngr_client,m_ActionManager);
            ActionTarget atrg = new ActionTarget(item1,null,-1,vector.Zero,-1.0);
            if ( mngr_client.GetAction(ActionSwapItemToHands).Can(this,atrg,ItemBase.Cast(item2)) )
            {
                mngr_client.PerformActionStart(mngr_client.GetAction(ActionSwapItemToHands),atrg,ItemBase.Cast(item2));
            }
            return true;
        }
        else
            return super.PredictiveForceSwapEntities( item1, item2, item2_dst );
    }
References ActionTarget, ForceStandUpForHeavyItemsSwap(), ActionManagerBase::GetAction(), InventoryLocation::GetType(), ActionManagerClient::PerformActionStart(), and vector::Zero.
PredictiveSwapEntities()
override bool ManBase::PredictiveSwapEntities (notnull EntityAI item1, notnull EntityAI item2) inline private
Definition at line 8109 of file playerbase.c.
    {
        ForceStandUpForHeavyItemsSwap(item1, item2);
        //Print("PlayerBase | PredictiveSwapEntities");
        Magazine swapmag1 = Magazine.Cast(item1);
        Magazine swapmag2 = Magazine.Cast(item2);
        if (swapmag1 && swapmag2)
        {
            Weapon_Base parentWpn;
            if (Class.CastTo(parentWpn, swapmag1.GetHierarchyParent()))
            {
                if (GetWeaponManager().CanSwapMagazine(parentWpn, swapmag2) )
                {
                    Print("[inv] PlayerBase.PredictiveSwapEntities: swapping mag1=" + swapmag1 + " to parent wpn=" + parentWpn + " of mag1=" + swapmag1);
                    return GetWeaponManager().SwapMagazine(swapmag2);
                }
                else
                {
                    Print("[inv] PlayerBase.PredictiveSwapEntities: can not swap magazines");
                    return false;
                }
            }
            if (Class.CastTo(parentWpn, swapmag2.GetHierarchyParent()))
            {
                if (GetWeaponManager().CanSwapMagazine(parentWpn, swapmag1) )
                {
                    Print("[inv] PlayerBase.PredictiveSwapEntities: swapping mag1=" + swapmag1 + " to parent wpn=" + parentWpn + " of mag2=" + swapmag2);
                    return GetWeaponManager().SwapMagazine(swapmag1);
                }
                else
                {
                    Print("[inv] PlayerBase.PredictiveSwapEntities: can not swap magazines");
                    return false;
                }
            }
        }
        EntityAI item_hands;
        EntityAI item_ground;
        if ( IsSwapBetweenHandsAndGroundLargeItem(item1,item2,item_hands,item_ground) && !m_ActionManager.GetRunningAction() )
        {
            ActionManagerClient mngr_client;
            CastTo(mngr_client,m_ActionManager);
            ActionTarget atrg = new ActionTarget(item_ground,null,-1,vector.Zero,-1.0);
            if ( mngr_client.GetAction(ActionSwapItemToHands).Can(this,atrg,ItemBase.Cast(item_hands)) )
            {
                mngr_client.PerformActionStart(mngr_client.GetAction(ActionSwapItemToHands),atrg,ItemBase.Cast(item_hands));
                return true;
            }
            return super.PredictiveSwapEntities( item1, item2);
        }
        else
            return super.PredictiveSwapEntities( item1, item2);
    }
References ActionTarget, Class::CastTo(), ForceStandUpForHeavyItemsSwap(), ActionManagerBase::GetAction(), GetWeaponManager(), ActionManagerClient::PerformActionStart(), Print(), WeaponManager::SwapMagazine(), and vector::Zero.
PredictiveTakeEntityToHands()
override void ManBase::PredictiveTakeEntityToHands (EntityAI item) inline private
Definition at line 8190 of file playerbase.c.
    {
        if ( item.IsHeavyBehaviour() && !m_ActionManager.GetRunningAction() && !item.GetHierarchyParent() )
        {
            ActionManagerClient mngr_client;
            if (CastTo(mngr_client,m_ActionManager))
            {
                ActionTarget atrg = new ActionTarget(item,null,-1,vector.Zero,-1.0);
                if ( mngr_client.GetAction(ActionTakeItemToHands).Can(this,atrg,null) )
                {
                    mngr_client.PerformActionStart(mngr_client.GetAction(ActionTakeItemToHands),atrg,null);
                }
                /*).Can(this,
                mngr_client.ActionStart(mngr_client.GetAction(ActionTakeItemToHands),mngr_client.FindActionTarget(),null);
                return;*/
            }
        }
        else
            super.PredictiveTakeEntityToHands(item);
    }
References ActionTarget, ActionManagerBase::GetAction(), ActionManagerClient::PerformActionStart(), and vector::Zero.
PredictiveTakeEntityToInventory()
override bool ManBase::PredictiveTakeEntityToInventory (FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 8015 of file playerbase.c.
    {
        bool can_detach;
        if (CanRedirectToWeaponManager(item,can_detach))
        {
            InventoryLocation il = new InventoryLocation();
            if (can_detach && GetInventory().FindFreeLocationFor(item, flags, il))
            {
                return GetWeaponManager().DetachMagazine(il);
            }
            return false;
        }
        return super.PredictiveTakeEntityToInventory(flags, item);
    }
References WeaponManager::DetachMagazine(), FindFreeLocationFor(), and GetWeaponManager().
PredictiveTakeEntityToTargetAttachment()
override bool ManBase::PredictiveTakeEntityToTargetAttachment (notnull EntityAI target, notnull EntityAI item) inline private
Definition at line 8030 of file playerbase.c.
    {
        Weapon_Base parentWpn = Weapon_Base.Cast(target);
        Magazine mag = Magazine.Cast(item);
        if (parentWpn && mag)
        {
            if( GetWeaponManager().CanAttachMagazine(parentWpn, mag) )
                return GetWeaponManager().AttachMagazine(mag);
            return false;
        }
        return super.PredictiveTakeEntityToTargetAttachment(target, item);
    }
References WeaponManager::AttachMagazine(), and GetWeaponManager().
PredictiveTakeEntityToTargetAttachmentEx()
override bool ManBase::PredictiveTakeEntityToTargetAttachmentEx (notnull EntityAI target, notnull EntityAI item, int slot) inline private
Definition at line 8044 of file playerbase.c.
    {
        Weapon_Base parentWpn = Weapon_Base.Cast(target);
        Magazine mag = Magazine.Cast(item);
        if (parentWpn && mag)
        {
            if( target.CanReceiveAttachment(item,slot) && GetWeaponManager().CanAttachMagazine(parentWpn, mag) )
                return GetWeaponManager().AttachMagazine(mag);
            return false;
        }
        return super.PredictiveTakeEntityToTargetAttachmentEx(target, item,slot);
    }
References WeaponManager::AttachMagazine(), and GetWeaponManager().
PredictiveTakeEntityToTargetCargo()
override bool ManBase::PredictiveTakeEntityToTargetCargo (notnull EntityAI target, notnull EntityAI item) inline private
Definition at line 8058 of file playerbase.c.
    {
        bool can_detach;
        if (CanRedirectToWeaponManager(item,can_detach))
        {
            InventoryLocation il = new InventoryLocation();
            if (can_detach && target.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.CARGO, il))
            {
                return GetWeaponManager().DetachMagazine(il);
            }
            return false;
        }
        return super.PredictiveTakeEntityToTargetCargo(target,item);
    }
References WeaponManager::DetachMagazine(), and GetWeaponManager().
PredictiveTakeEntityToTargetCargoEx()
override bool ManBase::PredictiveTakeEntityToTargetCargoEx (notnull CargoBase cargo, notnull EntityAI item, int row, int col) inline private
Definition at line 8073 of file playerbase.c.
    {
        bool can_detach;
        if (CanRedirectToWeaponManager(item, can_detach))
        {
            if (can_detach)
            {
                InventoryLocation dst = new InventoryLocation;
                dst.SetCargoAuto(cargo, item, row, col, item.GetInventory().GetFlipCargo());
                return GetWeaponManager().DetachMagazine(dst);
            }
            return false;
        }
        return super.PredictiveTakeEntityToTargetCargoEx (cargo, item, row, col);
    }
References WeaponManager::DetachMagazine(), GetWeaponManager(), and InventoryLocation::SetCargoAuto().
PredictiveTakeEntityToTargetInventory()
override bool ManBase::PredictiveTakeEntityToTargetInventory (notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 8000 of file playerbase.c.
    {
        bool can_detach;
        if (CanRedirectToWeaponManager(item,can_detach))
        {
            InventoryLocation il = new InventoryLocation();
            if (can_detach && target.GetInventory().FindFreeLocationFor(item, flags, il))
            {
                return GetWeaponManager().DetachMagazine(il);
            }
            return false;
        }
        return super.PredictiveTakeEntityToTargetInventory(target, flags, item);
    }
References WeaponManager::DetachMagazine(), and GetWeaponManager().
PredictiveTakeToDst()
override bool ManBase::PredictiveTakeToDst (notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 8212 of file playerbase.c.
    {
        EntityAI item = src.GetItem();
        if(item)
        {
            bool can_detach;
            if (CanRedirectToWeaponManager(item,can_detach))
            {
                if (can_detach)
                {
                    return GetWeaponManager().DetachMagazine(dst);
                }
                return false;
            }
            return super.PredictiveTakeToDst(src,dst);
        }
        return false;
    }
References WeaponManager::DetachMagazine(), and GetWeaponManager().
PreloadDecayTexture()
void ManBase::PreloadDecayTexture () inline private
Definition at line 8620 of file playerbase.c.
    {
        int idx;
        int slot_id;
        idx = GetHiddenSelectionIndex("decay_preload");
        if (idx > -1)
        {
            SetObjectTexture(idx,m_DecayedTexture);
            //Print("'decay_preload'" + m_DecayedTexture +" loaded on " + GetModelName());
        }
        else
        {
            //Print("No 'decay_preload' selection found on " + this);
        }
    }
PrintAgents()
void ManBase::PrintAgents () inline private
Definition at line 7357 of file playerbase.c.
    {
        m_AgentPool.PrintAgents();
    }
ProcessADDModifier()
void ManBase::ProcessADDModifier () inline private
Definition at line 6424 of file playerbase.c.
    {
        if( m_AddModifier != -1 )
        {
            HumanCommandAdditives ad = GetCommandModifier_Additives();
            if(ad)
                ad.StartModifier(m_AddModifier);
            m_AddModifier = -1;
        }
    }
References GetCommandModifier_Additives(), and HumanCommandAdditives().
ProcessDrowning()
void ManBase::ProcessDrowning (float dT) inline private
Definition at line 1841 of file playerbase.c.
    {
        GetStaminaHandler().DepleteStamina(EStaminaModifiers.DROWN,dT );
        PPERequester_Drowning req = PPERequester_Drowning.Cast(PPERequesterBank.GetRequester( PPERequesterBank.REQ_DROWNING ));
        req.SetStamina01(GetStaminaHandler().GetStaminaNormalized());
    }
References GetStaminaNormalized().
ProcessFeetDamageServer()
override void ManBase::ProcessFeetDamageServer (int pUserInt) inline private
right foot
left foot
Definition at line 1436 of file playerbase.c.
    {
        //InventorySlots.HEADGEAR
        EntityAI shoes = GetInventory().FindAttachment(InventorySlots.FEET);
        string surface; int liquid;
        GetGame().SurfaceUnderObject(this, surface, liquid);
        float modifier_surface = Surface.GetParamFloat(surface, "footDamage");
        if( shoes && shoes.GetHealthLevel() < 4 )
        {
            shoes.AddHealth("","", - 1 * modifier_surface * PlayerConstants.SHOES_MOVEMENT_DAMAGE_PER_STEP * (float)PlayerConstants.CHECK_EVERY_N_STEP);
            /*
            Print("modifier_surface:"+modifier_surface);
            Print(shoes.GetHealth("",""));
            */
            return;
        }
        float rnd = Math.RandomFloat01();
        float modifier_movement = GetFeetDamageMoveModifier();
        /*
        Print(surface);
        Print(Surface.GetParamFloat(surface, "footDamage"));
        */
        float chance = modifier_movement * modifier_surface * PlayerConstants.BAREFOOT_MOVEMENT_BLEED_MODIFIER * (float)PlayerConstants.CHECK_EVERY_N_STEP;
        //Print(chance);
        //Print("chance:" +chance);
        if( rnd < chance )
        {
            if(pUserInt % 2 == 0)
            {
                if(GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightFoot"))
                {
                    //added
                    //Print("right foot bleeding");
                    SendSoundEvent(EPlayerSoundEventID.INJURED_LIGHT);
                }
            }
            else
            {
                if(GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftFoot"))
                {
                    //added
                    //Print("left foot bleeding");
                    SendSoundEvent(EPlayerSoundEventID.INJURED_LIGHT);
                }
            }
        }
    }
References PlayerConstants::BAREFOOT_MOVEMENT_BLEED_MODIFIER, PlayerConstants::CHECK_EVERY_N_STEP, GetGame(), Surface::GetParamFloat(), Math::RandomFloat01(), SendSoundEvent(), PlayerConstants::SHOES_MOVEMENT_DAMAGE_PER_STEP, and CGame::SurfaceUnderObject().
ProcessHandDamage()
void ManBase::ProcessHandDamage (float delta_time, HumanMovementState pState) inline private
Definition at line 1399 of file playerbase.c.
    {
        if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            if(pState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SLIDE)
            {
                //Print("sliding down");
                EntityAI gloves = GetInventory().FindAttachment(InventorySlots.GLOVES);
                if( gloves && gloves.GetHealthLevel() < 4 )
                {
                    gloves.AddHealth("","", PlayerConstants.GLOVES_DAMAGE_SLIDING_LADDER_PER_SEC * delta_time);
                    return;
                }
                if( Math.RandomFloat01() < PlayerConstants.CHANCE_TO_BLEED_SLIDING_LADDER_PER_SEC * delta_time)
                {
                    if(Math.RandomFloat01() < 0.5)
                    {
                        if(GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll"))
{
                            SendSoundEvent(EPlayerSoundEventID.INJURED_LIGHT);
                        }
                    }
                    else
                    {
                        if(GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightForeArmRoll"))
{
                            SendSoundEvent(EPlayerSoundEventID.INJURED_LIGHT);
                        }
                    }
                }
            }
        }
    }
References PlayerConstants::CHANCE_TO_BLEED_SLIDING_LADDER_PER_SEC, GetGame(), GetInstanceType(), PlayerConstants::GLOVES_DAMAGE_SLIDING_LADDER_PER_SEC, HumanMovementState::m_iMovement, Math::RandomFloat01(), and SendSoundEvent().
ProcessHoldBreath()
void ManBase::ProcessHoldBreath (float dT) inline private
Definition at line 1850 of file playerbase.c.
    {
        if ( IsTryingHoldBreath() && CanStartConsumingStamina(EStaminaConsumers.HOLD_BREATH) )
        {
            DepleteStamina(EStaminaModifiers.HOLD_BREATH,dT);
            if( !m_IsHoldingBreath )
            {
                OnHoldBreathStart();
                m_IsHoldingBreath = true;
            }
        }
        else if ( IsTryingHoldBreath() && m_IsHoldingBreath && CanConsumeStamina(EStaminaConsumers.HOLD_BREATH) )
        {
            DepleteStamina(EStaminaModifiers.HOLD_BREATH,dT);
        }
        else
        {
            if ( m_IsHoldingBreath ) OnHoldBreathEnd();
            m_IsHoldingBreath = false;
        }
    }
References CanConsumeStamina(), CanStartConsumingStamina(), DepleteStamina(), and IsTryingHoldBreath().
ProcessLiftWeapon()
override void ManBase::ProcessLiftWeapon () inline private
Definition at line 7836 of file playerbase.c.
    {
        if (m_ProcessLiftWeapon)
        {
            HumanCommandWeapons hcw = GetCommandModifier_Weapons();
            if( hcw )
                hcw.LiftWeapon(m_ProcessLiftWeaponState);
            GetWeaponManager().OnLiftWeapon();
            m_LiftWeapon_player = m_ProcessLiftWeaponState;
            m_ProcessLiftWeapon = false;
            //Debug.Log("SimulationStamp_server: " + this.GetSimulationTimeStamp());
        }
    }
References GetCommandModifier_Weapons(), GetWeaponManager(), HumanCommandWeapons::LiftWeapon(), m_LiftWeapon_player, m_ProcessLiftWeapon, m_ProcessLiftWeaponState, and WeaponManager::OnLiftWeapon().
QueueAddEffectWidget()
void ManBase::QueueAddEffectWidget (array< int > effects) inline private
Definition at line 692 of file playerbase.c.
    {
        m_ProcessAddEffectWidgets.InsertArray(effects);
    }
QueueAddGlassesEffect()
void ManBase::QueueAddGlassesEffect (int id) inline private
Definition at line 702 of file playerbase.c.
    {
        m_ProcessAddGlassesEffects.Insert(id);
    }
QueueRemoveEffectWidget()
void ManBase::QueueRemoveEffectWidget (array< int > effects) inline private
Definition at line 697 of file playerbase.c.
    {
        m_ProcessRemoveEffectWidgets.InsertArray(effects);
    }
QueueRemoveGlassesEffect()
void ManBase::QueueRemoveGlassesEffect (int id) inline private
Definition at line 707 of file playerbase.c.
    {
        m_ProcessRemoveGlassesEffects.Insert(id);
    }
QuickReloadWeapon()
void ManBase::QuickReloadWeapon (EntityAI weapon) inline private
Definition at line 4358 of file playerbase.c.
    {
        EntityAI magazine = GetMagazineToReload( weapon );
        ReloadWeapon( weapon, magazine );
    }
RadialQuickBarCombine()
void ManBase::RadialQuickBarCombine (int slotClicked) inline private
Definition at line 4349 of file playerbase.c.
    {
        EntityAI quickBarEntity = GetQuickBarEntity( slotClicked - 1 );
        EntityAI entity_in_hands = GetHumanInventory().GetEntityInHands();
        ReloadWeapon( entity_in_hands, quickBarEntity );
    }
RadialQuickBarSingleUse()
void ManBase::RadialQuickBarSingleUse (int slotClicked) inline private
Definition at line 4343 of file playerbase.c.
    {
        OnQuickBarSingleUse( slotClicked );
    }
ReadLiftWeaponRequest()
bool ManBase::ReadLiftWeaponRequest (int userDataType, ParamsReadContext ctx) inline private
Definition at line 7756 of file playerbase.c.
    {
        bool state;
        ctx.Read(state);
        ScriptJunctureData pCtx = new ScriptJunctureData;
        pCtx.Write(state);
        SendSyncJuncture(DayZPlayerSyncJunctures.SJ_WEAPON_LIFT, pCtx);
        return true;
    }
References Serializer::Read(), SendSyncJuncture(), DayZPlayerSyncJunctures::SJ_WEAPON_LIFT, and Serializer::Write().
RefreshHandAnimationState()
void ManBase::RefreshHandAnimationState (int delay = 0) inline private
Definition at line 4119 of file playerbase.c.
    {
        if (delay == 0)
        {
            //Print("---Refreshing Hand Anim State---");
            GetItemAccessor().OnItemInHandsChanged(true);
            GetItemAccessor().ResetWeaponInHands();
        }
        else
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(RefreshHandAnimationState,delay,false,0);
        }
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and GetItemAccessor().
ReloadWeapon()
void ManBase::ReloadWeapon (EntityAI weapon, EntityAI magazine) inline private
Definition at line 4365 of file playerbase.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            ActionManagerClient mngr_client;
            CastTo(mngr_client, GetActionManager());
            if (mngr_client && FirearmActionLoadMultiBulletRadial.Cast(mngr_client.GetRunningAction()))
            {
                mngr_client.Interrupt();
            }
            else if ( GetHumanInventory().GetEntityInHands()!= magazine )
            {
                Weapon_Base wpn;
                Magazine mag;
                Class.CastTo( wpn,  weapon );
                Class.CastTo( mag,  magazine );
                if ( GetWeaponManager().CanUnjam(wpn) )
                {
                    GetWeaponManager().Unjam();
                }
                else if ( GetWeaponManager().CanAttachMagazine( wpn, mag ) )
                {
                    GetWeaponManager().AttachMagazine( mag );
                }
                else if ( GetWeaponManager().CanSwapMagazine( wpn, mag ) )
                {
                    GetWeaponManager().SwapMagazine( mag );
                }
                else if ( GetWeaponManager().CanLoadBullet( wpn, mag ) )
                {
                    //GetWeaponManager().LoadMultiBullet( mag );
                    ActionTarget atrg = new ActionTarget(mag, this, -1, vector.Zero, -1.0);
                    if ( mngr_client && !mngr_client.GetRunningAction() && mngr_client.GetAction(FirearmActionLoadMultiBulletRadial).Can(this, atrg, wpn) )
                        mngr_client.PerformActionStart(mngr_client.GetAction(FirearmActionLoadMultiBulletRadial), atrg, wpn);
                }
            }
        }
    }
References ActionTarget, WeaponManager::AttachMagazine(), Class::CastTo(), ActionManagerBase::GetAction(), GetActionManager(), GetInstanceType(), ActionManagerBase::GetRunningAction(), GetWeaponManager(), ActionManagerClient::Interrupt(), ActionManagerClient::PerformActionStart(), WeaponManager::SwapMagazine(), WeaponManager::Unjam(), and vector::Zero.
RemoveAction() [1/2]
void ManBase::RemoveAction (typename actionName) inline private
Definition at line 1351 of file playerbase.c.
    {
        RemoveAction(actionName, m_InputActionMap);
    }
References m_InputActionMap, and RemoveAction().
RemoveAction() [2/2]
void ManBase::RemoveAction (typename actionName , out TInputActionMap InputActionMap) inline private
Definition at line 1330 of file playerbase.c.
    {
        ActionBase action = GetActionManager().GetAction(actionName);
        typename ai = action.GetInputType();
        ref array<ActionBase_Basic> action_array = InputActionMap.Get( ai );
        if (action_array)
        {
            for (int i = 0; i < action_array.Count(); i++)
            {
                if (action == action_array.Get(i))
                {
                    action_array.Remove(i);
                }
            }
            action_array = new array<ActionBase_Basic>;
            InputActionMap.Insert(ai, action_array);
        }
        action_array.Insert(action);
    }
References ActionBase(), and GetActionManager().
RemoveActiveNV()
void ManBase::RemoveActiveNV (int type) inline private
Definition at line 8464 of file playerbase.c.
    {
        if ( !m_ActiveNVTypes || (GetGame().IsMultiplayer() && GetGame().IsServer()) )
        {
            #ifdef DEVELOPER
                Error("RemoveActiveNV | illegal server-side call!");
            #endif
            return;
        }
        if ( m_ActiveNVTypes.Find(type) != -1 ) //TODO - set instead?
            m_ActiveNVTypes.RemoveItem(type);
    }
References Error(), and GetGame().
RemoveAgent()
override void ManBase::RemoveAgent (int agent_id) inline private
Definition at line 7321 of file playerbase.c.
    {
        m_AgentPool.RemoveAgent(agent_id);
    }
RemoveAllAgents()
override void ManBase::RemoveAllAgents () inline private
Definition at line 7327 of file playerbase.c.
    {
        m_AgentPool.RemoveAllAgents();
    }
RemoveAllItems()
void ManBase::RemoveAllItems () inline private
Definition at line 1117 of file playerbase.c.
    {
        array<EntityAI> itemsArray = new array<EntityAI>;
        ItemBase item;
        GetInventory().EnumerateInventory(InventoryTraversalType.PREORDER, itemsArray);
        for (int i = 0; i < itemsArray.Count(); i++)
        {
            Class.CastTo(item, itemsArray.Get(i));
            if (item && !item.IsInherited(SurvivorBase))    GetInventory().LocalDestroyEntity(item);
        }
    }
References Class::CastTo().
RemoveQuickBarEntityShortcut()
void ManBase::RemoveQuickBarEntityShortcut (EntityAI entity) inline private
Definition at line 1772 of file playerbase.c.
    {
        int index = m_QuickBarBase.FindEntityIndex(entity);
        if(index != -1)
            m_QuickBarBase.SetEntityShortcut(entity,-1);
    }
RequestHandAnimationStateRefresh()
void ManBase::RequestHandAnimationStateRefresh () inline private
Definition at line 4108 of file playerbase.c.
    {
        if ( (GetGame().IsMultiplayer() && GetGame().IsServer()) )
        {
            m_RefreshAnimStateIdx++;
            if (m_RefreshAnimStateIdx > 3)
                m_RefreshAnimStateIdx = 0;
            SetSynchDirty();
        }
    }
References GetGame().
RequestResetADSSync()
void ManBase::RequestResetADSSync () inline private
Definition at line 2175 of file playerbase.c.
    {
        if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT && GetGame().IsMultiplayer())
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_RESET_ADS);
                ctx.Send();
            }
        }
        else if (!GetGame().IsMultiplayer())
        {
            m_ResetADS = true;
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetInstanceType(), INPUT_UDT_RESET_ADS, m_ResetADS, ScriptInputUserData::Send(), and Serializer::Write().
RequestSoundEvent()
override void ManBase::RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client = false) inline private
Definition at line 7026 of file playerbase.c.
    {
        RequestSoundEventEx(id, from_server_and_client);
    }
References RequestSoundEventEx().
RequestSoundEventEx()
override void ManBase::RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client = false, int param = 0) inline private
Definition at line 7016 of file playerbase.c.
    {
        if(from_server_and_client && GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
        {
            PlaySoundEventEx(id, false, false, param );
            return;
        }
        SendSoundEventEx(id, param);
    }
References GetInstanceType(), PlaySoundEventEx(), and SendSoundEventEx().
RequestUnconsciousness()
void ManBase::RequestUnconsciousness (bool enable) inline private
Definition at line 7891 of file playerbase.c.
    {
        DayZPlayerSyncJunctures.SendPlayerUnconsciousness(this, enable);
    }
References DayZPlayerSyncJunctures::SendPlayerUnconsciousness().
ResetActionEndInput()
void ManBase::ResetActionEndInput () inline private
Definition at line 4334 of file playerbase.c.
    {
        m_ActionQBControl = false;
    }
ResetActiveNV()
void ManBase::ResetActiveNV () inline private
Definition at line 8479 of file playerbase.c.
    {
        m_ActiveNVTypes.Clear();
    }
ResetADSPlayerSync()
bool ManBase::ResetADSPlayerSync (int userDataType, ParamsReadContext ctx) inline private
server only
Definition at line 2193 of file playerbase.c.
    {
        if ( userDataType == INPUT_UDT_RESET_ADS )
        {
            ScriptJunctureData pCtx = new ScriptJunctureData;
            SendSyncJuncture(DayZPlayerSyncJunctures.SJ_ADS_RESET,pCtx);
            return true;
        }
        return false;
    }
References INPUT_UDT_RESET_ADS, SendSyncJuncture(), and DayZPlayerSyncJunctures::SJ_ADS_RESET.
ResetConstructionActionData()
void ManBase::ResetConstructionActionData () inline private
Definition at line 1731 of file playerbase.c.
    {
        if ( m_ConstructionActionData )
        {
            m_ConstructionActionData.ResetActionIndexes();
        }
    }
ResetPlayer()
void ManBase::ResetPlayer (bool set_max) inline private
Definition at line 7163 of file playerbase.c.
    {
        //clear stomach content
        GetStomach().ClearContents();
        // bleeding sources
        if( m_BleedingManagerServer )
            m_BleedingManagerServer.RemoveAllSources();
        // Modifiers
        bool is_area_exposure, is_mask;
        if( GetModifiersManager() )
        {
            is_mask = GetModifiersManager().IsModifierActive(eModifiers.MDF_MASK);
            is_area_exposure = GetModifiersManager().IsModifierActive(eModifiers.MDF_AREAEXPOSURE);
            GetModifiersManager().DeactivateAllModifiers();
        }
        if(is_area_exposure)
            GetModifiersManager().ActivateModifier(eModifiers.MDF_AREAEXPOSURE);
        if(is_mask)
            GetModifiersManager().ActivateModifier(eModifiers.MDF_MASK);
        // Stats
        if( GetPlayerStats() )
        {
            int blood_type = GetStatBloodType().Get();
            GetPlayerStats().ResetAllStats();
            GetStatBloodType().Set(blood_type);
        }
        // Agents
        if( m_AgentPool )
            m_AgentPool.RemoveAllAgents();
        // Damage System
        DamageZoneMap zones = new DamageZoneMap;
        DamageSystem.GetDamageZoneMap(this,zones);
        SetHealth("", "Health", GetMaxHealth("","Health"));
        SetHealth("", "Shock", GetMaxHealth("","Shock"));
        SetHealth("", "Blood", GetMaxHealth("","Blood"));
        for( int i = 0; i < zones.Count(); i++ )
        {
            string zone = zones.GetKey(i);
            SetHealth(zone, "Health", GetMaxHealth(zone,"Health"));
            SetHealth(zone, "Shock", GetMaxHealth(zone,"Shock"));
            SetHealth(zone, "Blood", GetMaxHealth(zone,"Blood"));
        }
        // uncon
        if(IsUnconscious())
            DayZPlayerSyncJunctures.SendPlayerUnconsciousness(this, false);
        // set max
        if( set_max )
        {
            GetStatWater().Set(GetStatWater().GetMax());
            GetStatEnergy().Set(GetStatEnergy().GetMax());
        }
        // fix up inventory
        FixAllInventoryItems();
        //remove bloody hands
        PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
        module_lifespan.UpdateBloodyHandsVisibilityEx( this, eBloodyHandsTypes.CLEAN );
    }
References GetMax(), GetMaxHealth(), GetPlugin(), PluginLifespan(), DayZPlayerSyncJunctures::SendPlayerUnconsciousness(), and SetHealth().
RPC()
override void ManBase::RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient = NULL) inline private
Definition at line 5018 of file playerbase.c.
    {
        super.RPC(rpc_type, params, guaranteed, recipient);
    }
RunFightBlendTimer()
void ManBase::RunFightBlendTimer () inline private
Definition at line 4980 of file playerbase.c.
    {
        if (!m_FightEndBlendTimer)
            m_FightEndBlendTimer = new Timer();
        if (!m_FightEndBlendTimer.IsRunning())
        {
            m_FightEndBlendTimer.Run(PlayerConstants.MELEE2_MOVEMENT_BLEND_DELAY,this,"EndFighting");
        }
    }
References m_FightEndBlendTimer, and PlayerConstants::MELEE2_MOVEMENT_BLEND_DELAY.
Save()
bool ManBase::Save () inline private
Definition at line 7271 of file playerbase.c.
    {
        // saved player must be alive and not captive
        if (GetPlayerState() == EPlayerStates.ALIVE && !IsRestrained())
        {
            GetHive().CharacterSave(this);
            Debug.Log("Player "+this.ToString()+ " saved as alive");
            return true;
        }
        return false;
    }
References Hive::CharacterSave(), GetHive(), IsRestrained(), Debug::Log(), and ToString().
SaveAreaPersistenceFlag()
void ManBase::SaveAreaPersistenceFlag (ParamsWriteContext ctx) inline private
Definition at line 6633 of file playerbase.c.
    {
        if(GetModifiersManager())
            SetPersistentFlag(PersistentFlag.AREA_PRESENCE, GetModifiersManager().IsModifierActive(eModifiers.MDF_AREAEXPOSURE));//set the flag for player's presence in contaminated area
        ctx.Write( m_PersistentFlags );
    }
References IsModifierActive(), and Serializer::Write().
SaySoundSet()
AbstractWave ManBase::SaySoundSet (string name) inline private
Definition at line 1904 of file playerbase.c.
    {
        if( m_SaySoundLastSetName != name )
        {
            m_SaySoundParams = new SoundParams(name);
            m_SaySoundBuilder = new SoundObjectBuilder(m_SaySoundParams);
            m_SaySoundLastSetName = name;
        }
        m_SaySoundObject = m_SaySoundBuilder.BuildSoundObject();
        m_SaySoundObject.SetPosition(GetPosition());
        return GetGame().GetSoundScene().Play3D(m_SaySoundObject, m_SaySoundBuilder);
    }
References GetGame(), GetPosition, CGame::GetSoundScene(), and name.
SendLiftWeaponSync()
void ManBase::SendLiftWeaponSync (bool state) inline private
Client-side only.
Definition at line 7781 of file playerbase.c.
    {
        HumanCommandWeapons hcw;
        //SP version
        if (!GetGame().IsMultiplayer())
        {
            m_LiftWeapon_player = state;
            hcw = GetCommandModifier_Weapons();
            if( hcw )
                hcw.LiftWeapon(state);
            GetWeaponManager().OnLiftWeapon();
            return;
        }
        ScriptInputUserData ctx = new ScriptInputUserData;
        if (GetGame().IsMultiplayer() && GetGame().IsClient() && !ctx.CanStoreInputUserData())
        {
            //Print("ctx unavailable");
            return;
        }
        else if (GetGame().IsMultiplayer() && GetGame().IsClient() && ctx.CanStoreInputUserData())
        {
            //Print("sending ECB cancel request");
            ctx.Write(INPUT_UDT_WEAPON_LIFT_EVENT);
            ctx.Write(state);
            ctx.Send();
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetCommandModifier_Weapons(), GetGame(), GetWeaponManager(), INPUT_UDT_WEAPON_LIFT_EVENT, HumanCommandWeapons::LiftWeapon(), m_LiftWeapon_player, WeaponManager::OnLiftWeapon(), ScriptInputUserData::Send(), and Serializer::Write().
SendSoundEvent()
override protected void ManBase::SendSoundEvent (EPlayerSoundEventID id) inline private
Definition at line 7031 of file playerbase.c.
    {
        SendSoundEventEx(id);
    }
References SendSoundEventEx().
SendSoundEventEx()
override protected void ManBase::SendSoundEventEx (EPlayerSoundEventID id, int param = 0) inline private
Definition at line 7036 of file playerbase.c.
    {
        if( !GetGame().IsServer() )
        {
            return;
        }
        m_SoundEvent = id;
        m_SoundEventParam = param;
        SetSynchDirty();
        if( !GetGame().IsMultiplayer() )
        {
            CheckSoundEvent();
        }
        //PrintString(GetGame().GetTime().ToString() + " Set SoundEvent, id:" + id.ToString());
    }
References GetGame().
SetActionEndInput()
void ManBase::SetActionEndInput (ActionBase action) inline private
Definition at line 4325 of file playerbase.c.
    {
        m_ActionQBControl = !action.GetInput().IsActive();
    }
SetActions() [1/2]
void ManBase::SetActions () inline private
Definition at line 1233 of file playerbase.c.
    {
    }
SetActions() [2/2]
void ManBase::SetActions (out TInputActionMap InputActionMap) inline private
Definition at line 1184 of file playerbase.c.
    {
        AddAction(ActionOpenDoors, InputActionMap);
        AddAction(ActionCloseDoors, InputActionMap);
        AddAction(ActionEnterLadder, InputActionMap);
        AddAction(ActionExitLadder, InputActionMap);
        //AddAction(ActionWorldCraft);//??
        //AddAction(ActionWorldCraftSwitch);//??
        //-----------CheckIfCanMOveToTarget----------
        AddAction(ActionStartEngine, InputActionMap);
        AddAction(ActionStopEngine, InputActionMap);
        AddAction(ActionSwitchSeats, InputActionMap);
        AddAction(ActionOpenCarDoors,InputActionMap);
        AddAction(ActionCloseCarDoors,InputActionMap);
        //AddAction(ActionTakeMaterialToHandsSwitch);
        AddAction(ActionUncoverHeadSelf, InputActionMap);
        //AddAction(ActionAttach);
        AddAction(ActionDrinkPondContinuous, InputActionMap);
        AddAction(ActionIgniteFireplaceByAir, InputActionMap);
        AddAction(ActionMineBushByHand, InputActionMap);
        AddAction(ActionUngagSelf, InputActionMap);
        AddAction(ActionLockedDoors, InputActionMap);
        AddAction(ActionWashHandsWaterOne, InputActionMap);
        AddAction(ActionGetOutTransport, InputActionMap);
        AddAction(ActionUnrestrainTargetHands, InputActionMap);
        //AddAction(ActionPickupChicken, InputActionMap);
        //AddAction(ActionSwitchLights);
        //AddAction(ActionTakeMaterialToHands);
        /*
        AddAction(AT_VEH_ENGINE_START);// TODO -> target
        AddAction(AT_FOLD_BASEBUILDING_OBJECT);// TODO -> target
        AddAction(AT_DIAL_COMBINATION_LOCK_ON_TARGET);// TODO -> target
        AddAction(AT_UNGAG_SELF);
        AddAction(AT_PICK_BERRY);// TODO -> target
        //actions.Insert(AT_SWAP_ITEM_TO_HANDS);
        AddAction(AT_LOCKED_DOORS);// TODO -> target
        AddAction(AT_GETOUT_TRANSPORT);
        AddAction(AT_VEH_SWITCH_LIGHTS);// TODO -> target??
        AddAction(AT_FENCE_OPEN);// TODO -> target
        AddAction(AT_FENCE_CLOSE);// TODO -> target
        AddAction(AT_TAKE_MATERIAL_TO_HANDS);// TODO -> target*/
    }
References ActionGetOutTransport(), ActionUncoverHeadSelf(), and AddAction().
SetActionsRemoteTarget() [1/2]
void ManBase::SetActionsRemoteTarget () inline private
Definition at line 1247 of file playerbase.c.
    {
    }
SetActionsRemoteTarget() [2/2]
void ManBase::SetActionsRemoteTarget (out TInputActionMap InputActionMap) inline private
Definition at line 1237 of file playerbase.c.
    {
        AddAction(ActionCPR, InputActionMap);
        AddAction(ActionUncoverHeadTarget, InputActionMap);
        AddAction(ActionUngagTarget, InputActionMap);
        AddAction(ActionCheckPulse, InputActionMap);
        AddAction(ActionPullBodyFromTransport, InputActionMap);
        //AddAction(AT_GIVE_ITEM);
    }
References AddAction().
SetBleedingBits()
void ManBase::SetBleedingBits (int bits) inline private
Definition at line 628 of file playerbase.c.
    {
        if( m_BleedingBits != bits )
        {
            if( m_BleedingBits == 0 )
            {
                OnBleedingBegin();
            }
            else if( bits == 0 )
            {
                OnBleedingEnd();
            }
        }
        m_BleedingBits = bits;
        SetSynchDirty();
    }
SetBloodType()
void ManBase::SetBloodType (int blood_type) inline private
Definition at line 6537 of file playerbase.c.
    {
        m_BloodType = blood_type;
        SetSynchDirty();
    }
References m_BloodType.
SetBloodTypeVisible()
void ManBase::SetBloodTypeVisible (bool show) inline private
Definition at line 6526 of file playerbase.c.
    {
        m_HasBloodTypeVisible = show;
        SetSynchDirty();
    }
SetBloodyHands()
void ManBase::SetBloodyHands (bool show) inline private
Definition at line 6504 of file playerbase.c.
    {
        m_HasBloodyHandsVisible = show;
        SetSynchDirty();
    }
SetBloodyHandsEx()
void ManBase::SetBloodyHandsEx (eBloodyHandsTypes type) inline private
Definition at line 6510 of file playerbase.c.
    {
        m_HasBloodyHandsVisible = type;
        SetSynchDirty();
    }
SetBloodyHandsPenalty()
void ManBase::SetBloodyHandsPenalty () inline private
Definition at line 6516 of file playerbase.c.
    {
        InsertAgent( eAgents.SALMONELLA, 1 );
    }
References InsertAgent().
SetBrokenLegs()
void ManBase::SetBrokenLegs (int stateId) inline private
Definition at line 3258 of file playerbase.c.
    {
        m_BrokenLegState = stateId;
        DayZPlayerSyncJunctures.SendBrokenLegsEx(this, stateId);
        eBrokenLegs state = GetBrokenLegs();//m_BrokenLegState can go bellow 0, cannot be used directly
        if ( state == eBrokenLegs.NO_BROKEN_LEGS )
        {
            m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS;
            m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS_SPLINT;
        }
        else if ( state == eBrokenLegs.BROKEN_LEGS )
        {
            SetLegHealth();
        }
        else if (state == eBrokenLegs.BROKEN_LEGS_SPLINT)
        {
            // handle splint here
        }
        SetSynchDirty();
    }
References DayZPlayerSyncJunctures::SendBrokenLegsEx().
SetCheckMeleeItem()
void ManBase::SetCheckMeleeItem (ItemBase item = null) inline private
Definition at line 3008 of file playerbase.c.
    {
        m_CheckMeleeItem = item;
    }
SetContaminatedEffect()
void ManBase::SetContaminatedEffect (bool enable, int ppeIdx = -1, int aroundId = ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId = ParticleList.CONTAMINATED_AREA_GAS_TINY, bool partDynaUpdate = false, int newBirthRate = 0) inline private
Definition at line 5452 of file playerbase.c.
    {
        SetContaminatedEffectEx(enable, ppeIdx, aroundId, tinyId, "", partDynaUpdate, newBirthRate);
    }
SetContaminatedEffectEx()
void ManBase::SetContaminatedEffectEx (bool enable, int ppeIdx = -1, int aroundId = ParticleList.CONTAMINATED_AREA_GAS_AROUND, int tinyId = ParticleList.CONTAMINATED_AREA_GAS_TINY, string soundset = "", bool partDynaUpdate = false, int newBirthRate = 0) inline private
Definition at line 5388 of file playerbase.c.
    {
    if ( enable ) // enable
        {
            // We assume that if this is set to true the PPE is already active
            if ( m_ContaminatedAreaEffectEnabled == enable )
                return;
            if ( aroundId !=0 )
            {
                if (!m_ContaminatedAroundPlayer)
                {
                    m_ContaminatedAroundPlayer = ParticleManager.GetInstance().PlayInWorld( aroundId, GetPosition());
                }
                // First entry in an area with dynamic tweaks to particles
                if ( partDynaUpdate )
                {
                    m_ContaminatedAroundPlayer.SetParameter( 0, EmitorParam.BIRTH_RATE, newBirthRate );
                }
            }
            if ( !m_ContaminatedAroundPlayerTiny && tinyId !=0 )
            {
                m_ContaminatedAroundPlayerTiny = ParticleManager.GetInstance().PlayInWorld( tinyId,  GetPosition() );
            }
            if ( ppeIdx != -1 )
            {
                PPERequesterBase ppeRequester;
                if ( Class.CastTo( ppeRequester, PPERequesterBank.GetRequester( ppeIdx ) ) )
                    ppeRequester.Start();
            }
            // We start playing the ambient sound
            if (!m_AmbientContamination && soundset != "")
                PlaySoundSetLoop( m_AmbientContamination, soundset, 0.1, 0.1 );
            m_ContaminatedAreaEffectEnabled = enable;
        }
        else // disable
        {
            if ( m_ContaminatedAroundPlayer )
            {
                m_ContaminatedAroundPlayer.Stop();
                m_ContaminatedAroundPlayer = null;
            }
            if (m_ContaminatedAroundPlayerTiny)
            {
                m_ContaminatedAroundPlayerTiny.Stop();
                m_ContaminatedAroundPlayerTiny = null;
            }
            if (ppeIdx != -1)
                PPERequesterBank.GetRequester( ppeIdx ).Stop(new Param1<bool>(true)); //fade out
            // We stop the ambient sound
            if ( m_AmbientContamination )
                StopSoundSet( m_AmbientContamination );
            // We make sure to reset the state
            m_ContaminatedAreaEffectEnabled = enable;
        }
    }
References Class::CastTo(), GetPosition, ParticleManager(), PlaySoundSetLoop(), Particle::SetParameter(), PPERequesterBase::Start(), Particle::Stop(), and StopSoundSet().
SetCraftingRecipeID()
void ManBase::SetCraftingRecipeID (int recipeID) inline private
Definition at line 1711 of file playerbase.c.
    {
        if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            GetCraftingManager().SetRecipeID(recipeID);
        }
        else
        {
            m_RecipeID = recipeID;
        }
    }
References GetInstanceType(), and m_RecipeID.
SetDeathDarknessLevel()
override void ManBase::SetDeathDarknessLevel (float duration, float tick_time) inline private
Definition at line 7896 of file playerbase.c.
    {
        //super.SetDeathDarknessLevel(duration, tick_time);
        float actual_tick = tick_time;
        if (GetDamageDealtEffect())
            m_DamageDealtEffect = null;
        if (GetFlashbangEffect())
            m_FlashbangEffect = null;
        float percentage;
        if ( duration > 0 )
            percentage = 1 - ( (duration - m_DeathDarkeningCurrentTime) / duration );
        m_DeathDarkeningCurrentTime += actual_tick;
        if (!GetDamageDealtEffect() && !IsAlive())
        {
            m_DeathDarkeningParam.param1 = percentage;
            PPERequesterBank.GetRequester(PPERequester_DeathDarkening).Start(m_DeathDarkeningParam);
        }
        if ( m_DeathDarkeningCurrentTime >= duration && m_DeathEffectTimer )
        {
            m_DeathEffectTimer.Stop();
            m_DeathDarkeningParam.param1 = 1.0;
            PPERequesterBank.GetRequester(PPERequester_DeathDarkening).Start(m_DeathDarkeningParam);
        }
    }
References IsAlive(), m_DeathDarkeningCurrentTime, and m_DeathEffectTimer.
SetDecayEffects()
void ManBase::SetDecayEffects (int effect = -1) inline private
Definition at line 8568 of file playerbase.c.
    {
        int boneIdx = GetBoneIndexByName("Spine2");
        Particle p;
        switch (effect)
        {
            case PlayerConstants.CORPSE_STATE_MEDIUM :
                //play medium sound/flies particle
                if (!m_FliesEff)
                    m_FliesEff = new EffSwarmingFlies();
                if ( m_FliesEff && !SEffectManager.IsEffectExist(m_FliesIndex) )
                {
                    m_FliesEff.SetDecalOwner( this );
                    m_FliesIndex = SEffectManager.PlayOnObject(m_FliesEff, this, "0 0.25 0");
                    p = m_FliesEff.GetParticle();
                    AddChild(p, boneIdx);
                    if ( !m_SoundFliesEffect )
                    {
                        PlaySoundSetLoop(m_SoundFliesEffect, "Flies_SoundSet", 1.0, 1.0);
//                      ErrorEx("DbgFlies | CORPSE_STATE_MEDIUM | m_SoundFliesEffect created! " + m_SoundFliesEffect,ErrorExSeverity.INFO);
                    }
                }
            break;
            case PlayerConstants.CORPSE_STATE_DECAYED :
                //play serious sound/flies particle
                if ( !m_FliesEff )
                    m_FliesEff = new EffSwarmingFlies();
                if ( m_FliesEff && !SEffectManager.IsEffectExist(m_FliesIndex) )
                {
                    m_FliesEff.SetDecalOwner( this );
                    m_FliesIndex = SEffectManager.PlayOnObject(m_FliesEff, this, "0 0.25 0");
                    p = m_FliesEff.GetParticle();
                    AddChild(p, boneIdx);
                    if ( !m_SoundFliesEffect )
                    {
                        PlaySoundSetLoop(m_SoundFliesEffect, "Flies_SoundSet", 1.0, 1.0);
//                      ErrorEx("DbgFlies | CORPSE_STATE_DECAYED | m_SoundFliesEffect created! " + m_SoundFliesEffect,ErrorExSeverity.INFO);
                    }
                }
            break;
            //remove
            default:
                SEffectManager.DestroyEffect( m_FliesEff );
//              ErrorEx("DbgFlies | StopSoundSet | exit 3 ",ErrorExSeverity.INFO);
                StopSoundSet(m_SoundFliesEffect);
            break;
        }
    }
References AddChild(), PlayerConstants::CORPSE_STATE_DECAYED, PlayerConstants::CORPSE_STATE_MEDIUM, SEffectManager::DestroyEffect(), GetBoneIndexByName(), SEffectManager::IsEffectExist(), SEffectManager::PlayOnObject(), PlaySoundSetLoop(), and StopSoundSet().
SetDefaultHitPosition()
protected vector ManBase::SetDefaultHitPosition (string pSelection) inline private
Definition at line 967 of file playerbase.c.
    {
        return GetSelectionPositionMS(pSelection);
    }
References GetSelectionPositionMS().
SetDrowning()
void ManBase::SetDrowning (bool enable) inline private
Definition at line 2125 of file playerbase.c.
    {
        if (enable != m_IsDrowning)
        {
            if (enable)
            {
                OnDrowningStart();
            }
            else
            {
                OnDrowningEnd();
            }
        }
        m_IsDrowning = enable;
    }
SetEnableQuickBarEntityShortcut()
void ManBase::SetEnableQuickBarEntityShortcut (EntityAI entity, bool value) inline private
Definition at line 1779 of file playerbase.c.
    {
        int index = m_QuickBarBase.FindEntityIndex(entity);
        if(index != -1)
            m_QuickBarBase.SetShotcutEnable(index,value);
    }
SetFirstRecipe()
void ManBase::SetFirstRecipe () inline private
Definition at line 1366 of file playerbase.c.
    {
        m_RecipePick = 0;
    }
SetFlagTendencyRaise()
void ManBase::SetFlagTendencyRaise (bool state) inline private
DEPRECATED.
Definition at line 4525 of file playerbase.c.
    {
        m_FlagRaisingTendency = state;
    }
SetHairLevelToHide()
void ManBase::SetHairLevelToHide (int level, bool state, bool was_debug = false) inline private
Dynamic hair hiding.
Definition at line 8248 of file playerbase.c.
    {
        if (was_debug && GetInstanceType() != DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
            return;
        if (!m_CharactersHead)
        {
            ErrorEx("No valid head detected on character!");
            return;
        }
        if (level == -1) //hide/show ALL
        {
            m_HideHairAnimated = !m_HideHairAnimated;
            for (int i = 0; i < m_CharactersHead.m_HeadHairSelectionArray.Count(); i++)
            {
                //m_CharactersHead.SetSimpleHiddenSelectionState(i,m_HideHairAnimated);
                SelectionTranslation stt = SelectionTranslation.Cast(m_CharactersHead.m_HeadHairHidingStateMap.Get(i));
                stt.SetSelectionState(m_HideHairAnimated);
                m_CharactersHead.m_HeadHairHidingStateMap.Set(i,stt);
#ifdef DEVELOPER
                if ( !GetGame().IsDedicatedServer() )
                {
                    PluginDiagMenu diagmenu = PluginDiagMenu.Cast(GetPlugin(PluginDiagMenu));
                    diagmenu.m_HairHidingStateMap.Set(i,m_HideHairAnimated);
                }
#endif
            }
            return;
        }
        else //hide/show selected level only
        {
            bool switchState;
            if (was_debug)
            {
#ifdef DEVELOPER
                if ( !GetGame().IsDedicatedServer() )
                {
                    PluginDiagMenu diagmenuu = PluginDiagMenu.Cast(GetPlugin(PluginDiagMenu));
                    switchState = !diagmenuu.m_HairHidingStateMap.Get(level);
                    diagmenuu.m_HairHidingStateMap.Set(level, switchState);
                }
#endif
            }
            else
            {
                switchState = !state;
            }
            //m_CharactersHead.SetSimpleHiddenSelectionState(level,switchState);
            stt = SelectionTranslation.Cast(m_CharactersHead.m_HeadHairHidingStateMap.Get(level));
            stt.SetSelectionState(switchState);
            m_CharactersHead.m_HeadHairHidingStateMap.Set(level,stt); //nescessary?
        }
    }
References ErrorEx, GetGame(), GetInstanceType(), GetPlugin(), and SelectionTranslation::SetSelectionState().
SetHitPPEEnabled()
void ManBase::SetHitPPEEnabled (bool enabled) inline private
Definition at line 1135 of file playerbase.c.
    {
        m_CanDisplayHitEffectPPE = enabled;
    }
SetImmunityBoosted()
void ManBase::SetImmunityBoosted (bool boosted) inline private
Definition at line 4849 of file playerbase.c.
    {
        m_ImmunityBoosted = boosted;
    }
SetInventorySoftLock()
override void ManBase::SetInventorySoftLock (bool status) inline private
Definition at line 7739 of file playerbase.c.
    {
         m_InventorySoftLocked = status;
    }
SetInWater()
void ManBase::SetInWater (bool pState) inline private
water contact (driven by Environment)
Definition at line 2261 of file playerbase.c.
    {
        m_IsInWater = pState;
        SetSynchDirty();
    }
SetLastFirePoint()
void ManBase::SetLastFirePoint (vector last_fire_point) inline private
Definition at line 1755 of file playerbase.c.
    {
        m_LastFirePoint = last_fire_point;
    }
SetLastFirePointIndex()
void ManBase::SetLastFirePointIndex (int last_fire_point_index) inline private
Definition at line 1763 of file playerbase.c.
    {
        m_LastFirePointIndex = last_fire_point_index;
    }
SetLastFirePointRot()
void ManBase::SetLastFirePointRot (float last_fire_point_rot) inline private
Definition at line 1759 of file playerbase.c.
    {
        m_LastFirePointRot = last_fire_point_rot;
    }
SetLastMapInfo()
void ManBase::SetLastMapInfo (float scale, vector pos) inline private
Definition at line 8637 of file playerbase.c.
    {
        m_LastMapScale = scale;
        m_LastMapPos = pos;
    }
SetLastShavedSeconds()
void ManBase::SetLastShavedSeconds (int last_shaved_seconds) inline private
Definition at line 6489 of file playerbase.c.
    {
        m_LastShavedSeconds = last_shaved_seconds;
    }
SetLastUAMessage()
void ManBase::SetLastUAMessage (string pMsg) inline private
Definition at line 7512 of file playerbase.c.
    {
        m_UALastMessage = pMsg;
        if( m_UALastMessageTimer.IsRunning() )
        {
            m_UALastMessageTimer.Stop();
        }
        m_UALastMessageTimer.Run(PlayerConstants.LAST_UA_MSG_LIFETIME, this, "ClearLastUAMessage", null);
    }
References PlayerConstants::LAST_UA_MSG_LIFETIME.
SetLegHealth()
void ManBase::SetLegHealth () inline private
Definition at line 3452 of file playerbase.c.
    {
        SetHealth("RightLeg", "", 0);
        SetHealth("RightFoot", "", 0);
        SetHealth("LeftLeg", "", 0);
        SetHealth("LeftFoot", "", 0);
    }
References SetHealth().
SetLifeSpanStateVisible()
void ManBase::SetLifeSpanStateVisible (int show_state) inline private
Definition at line 6463 of file playerbase.c.
    {
        bool state_changed;
        if (show_state != m_LifeSpanState)
            state_changed = true;
        m_LifeSpanState = show_state;
        SetSynchDirty();
        if (state_changed) //server only, client solution in OnVariablesSynchronized()
        {
            //SendLifespanSyncEvent(m_LifeSpanState);
            UpdateHairSelectionVisibility();
        }
    }
SetLiftWeapon()
void ManBase::SetLiftWeapon (int pJunctureID, ParamsReadContext ctx) inline private
Definition at line 7769 of file playerbase.c.
    {
        bool state;
        ctx.Read(state);
        m_ProcessLiftWeaponState = state;
        m_ProcessLiftWeapon = true;
        //Print("SetLiftWeapon | STS: " + GetSimulationTimeStamp());
    }
References m_ProcessLiftWeapon, m_ProcessLiftWeaponState, and Serializer::Read().
SetLiquidTendencyDrain()
void ManBase::SetLiquidTendencyDrain (bool state) inline private
Definition at line 4512 of file playerbase.c.
    {
        m_LiquidTendencyDrain = state;
    }
SetLoadedQuickBarItemBind()
void ManBase::SetLoadedQuickBarItemBind (EntityAI entity, int index) inline private
Definition at line 7744 of file playerbase.c.
    {
        if( m_aQuickBarLoad )
            m_aQuickBarLoad.Insert(new Param2<EntityAI, int>(entity,index));
    }
SetLocalProjectionOrientation()
void ManBase::SetLocalProjectionOrientation (vector local_orientation) inline private
Definition at line 2240 of file playerbase.c.
    {
        m_LocalProjectionOrientation = local_orientation;
    }
SetLocalProjectionPosition()
void ManBase::SetLocalProjectionPosition (vector local_position) inline private
Definition at line 2235 of file playerbase.c.
    {
        m_LocalProjectionPosition = local_position;
    }
SetMapClosingSyncSet()
void ManBase::SetMapClosingSyncSet (bool state) inline private
Definition at line 2953 of file playerbase.c.
    {
        m_MapClosingSyncSent = state;
    }
SetMapOpen()
void ManBase::SetMapOpen (bool state) inline private
Definition at line 2943 of file playerbase.c.
    {
        m_MapOpen = state;
    }
SetMixedSoundState()
void ManBase::SetMixedSoundState (eMixedSoundStates state) inline private
Definition at line 607 of file playerbase.c.
    {
        eMixedSoundStates new_states = m_MixedSoundStates | state;
        if(new_states != m_MixedSoundStates)
        {
            m_MixedSoundStates = new_states;
            SetSynchDirty();
        }
    }
SetModifiers()
void ManBase::SetModifiers (bool enable) inline private
Definition at line 6898 of file playerbase.c.
    {
        GetModifiersManager().SetModifiers(enable);
    }
SetNewCharName()
void ManBase::SetNewCharName () inline private
Definition at line 5717 of file playerbase.c.
    {
        //Print("SetNewCharName");
        g_Game.GetMenuData().SaveCharacter(false,true);
        g_Game.GetMenuData().SetCharacterName(g_Game.GetMenuData().GetLastPlayedCharacter(), g_Game.GetMenuDefaultCharacterData(false).GetCharacterName() );
        //g_Game.GetMenuData().SaveCharacter(false,true);
        g_Game.GetMenuData().SaveCharactersLocal();
    }
References g_Game.
SetNextRecipe()
void ManBase::SetNextRecipe () inline private
Definition at line 1361 of file playerbase.c.
    {
        m_RecipePick++;
    }
SetNVGLowered()
void ManBase::SetNVGLowered (bool state) inline private
Definition at line 8444 of file playerbase.c.
    {
        m_LoweredNVGHeadset = state;
    }
SetNVGWorking()
void ManBase::SetNVGWorking (bool state) inline private
Deprecated.
Definition at line 8438 of file playerbase.c.
    {
        //Deprecated, below is for legacy's sake
        AddActiveNV(NVTypes.NV_GOGGLES);
    }
SetPersistentFlag()
void ManBase::SetPersistentFlag (PersistentFlag bit, bool enable) inline private
Definition at line 6584 of file playerbase.c.
    {
        if(enable)//turn on bit
            m_PersistentFlags = (m_PersistentFlags | bit);
        else//turn off bit
            m_PersistentFlags = ((~bit) & m_PersistentFlags);
    }
SetPlayerDisconnected()
void ManBase::SetPlayerDisconnected (bool state) inline private
Definition at line 2010 of file playerbase.c.
    {
        m_PlayerDisconnectProcessed = state;
    }
SetPlayerLoad()
void ManBase::SetPlayerLoad (float load) inline private
Definition at line 4546 of file playerbase.c.
    {
        m_CargoLoad = load;
        //Print("m_CargoLoad: " + m_CargoLoad);
        //Log(ToString(this) + "'s load weight is " + ftoa(m_CargoLoad) + " g.", LogTemplates.TEMPLATE_PLAYER_WEIGHT);
    }
SetProcessUIWarning()
override void ManBase::SetProcessUIWarning (bool state) inline private
Definition at line 8692 of file playerbase.c.
    {
        m_ProcessUIWarning = state;
    }
SetPulseType()
void ManBase::SetPulseType (EPulseType pulse_type) inline private
Definition at line 687 of file playerbase.c.
    {
        m_PulseType = pulse_type;
    }
SetQuickBarEntityShortcut()
void ManBase::SetQuickBarEntityShortcut (EntityAI entity, int index, bool force = false) inline private
Definition at line 1816 of file playerbase.c.
    {
        m_QuickBarBase.SetEntityShortcut(entity, index, force);
    }
SetQuickFishing()
void ManBase::SetQuickFishing (bool enable) inline private
Definition at line 1535 of file playerbase.c.
    {
        m_AllowQuickFishing = enable;
    }
SetQuickRestrain()
void ManBase::SetQuickRestrain (bool enable) inline private
Definition at line 1530 of file playerbase.c.
    {
        m_AllowQuickRestrain = enable;
    }
SetRestrained()
void ManBase::SetRestrained (bool is_restrained) inline private
Definition at line 1605 of file playerbase.c.
    {
        m_IsRestrained = is_restrained;
        SetSynchDirty();
    }
SetRestrainPrelocked()
void ManBase::SetRestrainPrelocked (bool restrain_prelock) inline private
Definition at line 1594 of file playerbase.c.
    {
        m_IsRestrainPrelocked = restrain_prelock;
        SetSynchDirty();
    }
SetRestrainStarted()
void ManBase::SetRestrainStarted (bool restrain_started) inline private
Definition at line 1583 of file playerbase.c.
    {
        m_IsRestrainStarted = restrain_started;
        SetSynchDirty();
    }
SetShakesForced()
void ManBase::SetShakesForced (int value) inline private
Definition at line 3038 of file playerbase.c.
    {
        m_ShakesForced = value;
    }
SetStamina()
void ManBase::SetStamina (int value, int range) inline private
Definition at line 1514 of file playerbase.c.
    {
        if( m_ModulePlayerStatus )
            m_ModulePlayerStatus.SetStamina( value, range );
    }
References m_ModulePlayerStatus.
SetStaminaState()
void ManBase::SetStaminaState (eStaminaState state) inline private
Definition at line 7251 of file playerbase.c.
    {
        if( state != m_StaminaState )
        {
            m_StaminaState = state;
            //PrintString("m_StaminaState:"+m_StaminaState.ToString());
            SetSynchDirty();
        }
    }
SetToDelete()
void ManBase::SetToDelete (ParamsReadContext pCtx) inline private
Definition at line 7650 of file playerbase.c.
    {
        EntityAI item;
        pCtx.Read(item);
        AddItemToDelete(item);
    }
References Serializer::Read().
SetUnderground()
void ManBase::SetUnderground (EUndergroundPresence presence) inline private
Definition at line 2205 of file playerbase.c.
    {
        m_UndergroundPresence = presence;
    }
SetVisibilityCoef()
void ManBase::SetVisibilityCoef (float pVisibility) inline private
Definition at line 4670 of file playerbase.c.
    {
        m_VisibilityCoef = pVisibility;
    }
ShavePlayer()
void ManBase::ShavePlayer () inline private
Definition at line 6359 of file playerbase.c.
    {
        SetLastShavedSeconds( StatGet("playtime") );
        m_ModuleLifespan.UpdateLifespan( this, true );
    }
ShockRefill()
void ManBase::ShockRefill (float pDt) inline private
Definition at line 3244 of file playerbase.c.
    {
        //functionality moved to ShockMdfr::OnTick
    }
ShowUnconsciousScreen()
void ManBase::ShowUnconsciousScreen (bool show) inline private
Definition at line 7000 of file playerbase.c.
    {
    #ifndef NO_GUI
        if (show)
        {
            GetGame().GetUIManager().ScreenFadeIn(0, "You are Unconscious", FadeColors.BLACK, FadeColors.WHITE);
            PrintString("Fade in");
        }
        else
        {
            GetGame().GetUIManager().ScreenFadeOut(0);
            PrintString("Fade out");
        }
    #endif
    }
References GetGame(), CGame::GetUIManager(), PrintString(), UIManager::ScreenFadeIn(), and UIManager::ScreenFadeOut().
SimplifyShock()
int ManBase::SimplifyShock () inline private
Definition at line 3202 of file playerbase.c.
    {
        int shock = Math.Lerp( 0, SIMPLIFIED_SHOCK_CAP, GetHealth("","Shock") / GetMaxHealth("","Shock") );
        shock = Math.Clamp(shock, 0, SIMPLIFIED_SHOCK_CAP);
        return shock;
    }
References Math::Clamp(), GetHealth(), GetMaxHealth(), and Math::Lerp().
SimulateDeath()
override void ManBase::SimulateDeath (bool state) inline private
Definition at line 5705 of file playerbase.c.
    {
        super.SimulateDeath(state);
        m_UndergroundHandler = null;
        if (m_EffectWidgets)
        {
            m_EffectWidgets.StopAllEffects();
            m_EffectWidgets.ClearSuspendRequests();
        }
    }
References GameplayEffectWidgets_base::ClearSuspendRequests(), and GameplayEffectWidgets_base::StopAllEffects().
SpawnAI()
EntityAI ManBase::SpawnAI (string object_name, vector pos) inline private
Definition at line 5983 of file playerbase.c.
    {
        bool is_ai = GetGame().IsKindOf( object_name, "DZ_LightAI");
        if (is_ai)
        {
            return EntityAI.Cast( GetGame().CreateObjectEx(object_name, pos, ECE_PLACE_ON_SURFACE|ECE_INITAI|ECE_EQUIP_ATTACHMENTS) );
        }
        return NULL;
    }
References ECE_EQUIP_ATTACHMENTS, ECE_INITAI, ECE_PLACE_ON_SURFACE, GetGame(), and CGame::IsKindOf().
SpawnBreathVaporEffect()
void ManBase::SpawnBreathVaporEffect () inline private
Definition at line 6436 of file playerbase.c.
    {
        //Print("SpawnBreathVaporEffect:"+GetGame().GetTime());
        int boneIdx = GetBoneIndexByName("Head");
        if ( boneIdx != -1 )
        {
            Particle p;
            switch (m_BreathVapour)
            {
                case 1:
                    p = ParticleManager.GetInstance().PlayInWorld(ParticleList.BREATH_VAPOUR_LIGHT, "-0.03 0.15 0");
                    break;
                case 2:
                    p = ParticleManager.GetInstance().PlayInWorld(ParticleList.BREATH_VAPOUR_MEDIUM, "-0.03 0.15 0");
                    break;
                case 3:
                    p = ParticleManager.GetInstance().PlayInWorld(ParticleList.BREATH_VAPOUR_HEAVY, "-0.03 0.15 0");
                    break;
                default:
                    break;
            }
            if ( p )
                AddChild(p, boneIdx);
        }
    }
References AddChild(), ParticleList::BREATH_VAPOUR_HEAVY, ParticleList::BREATH_VAPOUR_LIGHT, ParticleList::BREATH_VAPOUR_MEDIUM, GetBoneIndexByName(), and ParticleManager().
SpawnDamageDealtEffect()
override void ManBase::SpawnDamageDealtEffect () inline private
Definition at line 717 of file playerbase.c.
    {
        if (m_DamageDealtEffect)
        {
            delete m_DamageDealtEffect;
        }
        if (m_CanDisplayHitEffectPPE)
        {
            m_DamageDealtEffect = new DamageDealtEffect();
        }
    }
SpawnDamageDealtEffect2()
void ManBase::SpawnDamageDealtEffect2 (Param param1 = null, Param param2 = null) inline private
Definition at line 730 of file playerbase.c.
    {
        if (m_EffectRadial)
        {
            delete m_EffectRadial;
        }
        m_EffectRadial = new EffectRadial(param1,param2);
    }
References EffectRadial().
SpawnEntityOnGroundOnCursorDir()
EntityAI ManBase::SpawnEntityOnGroundOnCursorDir (string object_name, float distance) inline private
Definition at line 5977 of file playerbase.c.
    {
        vector position = GetPosition() + ( GetDirection() * distance );
        return SpawnEntityOnGroundPos(object_name, position);
    }
References GetDirection(), and GetPosition.
SpawnEntityOnGroundPos()
override EntityAI ManBase::SpawnEntityOnGroundPos (string object_name, vector pos) inline private
Definition at line 5954 of file playerbase.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer() )
        {
            bool is_AI = GetGame().IsKindOf( object_name, "DZ_LightAI");
            if (is_AI)
            {
                return SpawnAI(object_name, pos);
            }
            else
            {
                InventoryLocation inv_loc = new InventoryLocation;
                vector mtx[4];
                Math3D.MatrixIdentity4(mtx);
                mtx[3] = pos;
                inv_loc.SetGround(NULL, mtx);
                //return GetGame().SpawnEntity(object_name, inv_loc, ECE_PLACE_ON_SURFACE, RF_DEFAULT);
                return EntityAI.Cast(GetGame().CreateObjectEx(object_name, inv_loc.GetPos(), ECE_PLACE_ON_SURFACE));
            }
        }
        return null;
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetInstanceType(), InventoryLocation::GetPos(), CGame::IsKindOf(), Math3D::MatrixIdentity4(), and InventoryLocation::SetGround().
SpawnFlashbangEffect()
void ManBase::SpawnFlashbangEffect (PlayerBase player, bool visual) inline private
Definition at line 745 of file playerbase.c.
    {
        if (m_FlashbangEffect)
        {
            m_FlashbangEffect.Stop();
            delete m_FlashbangEffect;
        }
        m_FlashbangEffect = new FlashbangEffect(player, visual);
    }
SpawnShockEffect()
void ManBase::SpawnShockEffect (float intensity_max) inline private
Definition at line 761 of file playerbase.c.
    {
        if (m_ShockDealtEffect)
        {
            delete m_ShockDealtEffect;
        }
        m_ShockDealtEffect = new ShockDealtEffect(intensity_max);
    }
SpreadAgents()
void ManBase::SpreadAgents () inline private
Definition at line 7309 of file playerbase.c.
    {
        SpreadAgentsEx(3,1);
    }
SpreadAgentsEx()
void ManBase::SpreadAgentsEx (float distance = 3, float chance = 0.25) inline private
chance between [0..1] , distance in meters
Definition at line 7291 of file playerbase.c.
    {
        if(Math.RandomFloat01() > chance)
            return;
        GetGame().GetPlayers(m_ServerPlayers);
        float dist_check = distance * distance;//make it sq
        PluginTransmissionAgents plugin = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
        foreach(Man target: m_ServerPlayers)
        {
            if (vector.DistanceSq(GetWorldPosition(), target.GetWorldPosition()) < dist_check && target != this)
            {
                plugin.TransmitAgents(this, target, AGT_AIRBOURNE_BIOLOGICAL, 1);
            }
        }
    }
References AGT_AIRBOURNE_BIOLOGICAL, vector::DistanceSq(), GetGame(), CGame::GetPlayers(), GetPlugin(), GetWorldPosition(), and Math::RandomFloat01().
StaminaHUDNotifier()
void ManBase::StaminaHUDNotifier (bool show) inline private
Definition at line 3964 of file playerbase.c.
    {
        if (m_Hud)
            m_Hud.SetStaminaBarVisibility( show );
    }
References m_Hud, and Hud::SetStaminaBarVisibility().
SwitchItemSelectionTexture()
override void ManBase::SwitchItemSelectionTexture (EntityAI item, string slot_name) inline private
Definition at line 1104 of file playerbase.c.
    {
        super.SwitchItemSelectionTexture(item,slot_name);
        //shirt + armband
        EntityAI armband = FindAttachmentBySlotName("Armband");
        if (slot_name == "Body" && armband)
        {
            Param1<PlayerBase> p = new Param1<PlayerBase>(this);
            armband.SwitchItemSelectionTextureEx(EItemManipulationContext.UPDATE,p);
        }
    }
SwitchItemTypeAttach()
void ManBase::SwitchItemTypeAttach (EntityAI item, string slot) inline private
Definition at line 1060 of file playerbase.c.
    {
        //Print("SwitchItemTypeAttach: " + item.GetType());
        if( !GetGame().IsServer() )
            return;
        /*InventoryLocation invloc = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation(invloc);
        //Print(invloc.DumpToString());
        if (item.ConfigIsExisting("ChangeIntoOnAttach") && invloc.GetType() != InventoryLocationType.UNKNOWN)
        {
            string str = item.ChangeIntoOnAttach(slot);
            if (str != "")
            {
                string typestr = item.GetType();
                MiscGameplayFunctions.TurnItemIntoItem(ItemBase.Cast( item ), str, this);
            }
        }*/
    }
References GetGame().
SwitchItemTypeDetach()
void ManBase::SwitchItemTypeDetach (EntityAI item, string slot) inline private
Definition at line 1081 of file playerbase.c.
    {
        //Print("SwitchItemTypeDetach: " + item.GetType());
    }
TakeEntityAsAttachmentImpl()
override protected bool ManBase::TakeEntityAsAttachmentImpl (InventoryMode mode, notnull EntityAI item) inline private
Definition at line 8791 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(FindInventoryLocationType.ATTACHMENT, item, this) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2Att(SPLIT) item=" + GetDebugName(item));
            return true;
        }
        return super.TakeEntityAsAttachmentImpl(mode, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToCargoImpl()
override protected bool ManBase::TakeEntityToCargoImpl (InventoryMode mode, notnull EntityAI item) inline private
Definition at line 8780 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(FindInventoryLocationType.CARGO, item, this) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2Cgo(SPLIT) item=" +GetDebugName(item));
            return true;
        }
        return super.TakeEntityToCargoImpl(mode, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToHandsImpl()
override void ManBase::TakeEntityToHandsImpl (InventoryMode mode, EntityAI item) inline private
Definition at line 8802 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(FindInventoryLocationType.HANDS, item, this) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2Hands(SPLIT) item=" + GetDebugName(item));
            return;
        }
        super.TakeEntityToHandsImpl(mode, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToInventoryImpl()
override protected bool ManBase::TakeEntityToInventoryImpl (InventoryMode mode, FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 8769 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(flags, item, this) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2Inv(SPLIT) item=" + GetDebugName(item));
            return true;
        }
        return super.TakeEntityToInventoryImpl(mode, flags, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToTargetAttachmentImpl()
override protected bool ManBase::TakeEntityToTargetAttachmentImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
Definition at line 8835 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(FindInventoryLocationType.ATTACHMENT, item, target) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2TargetAtt(SPLIT) item=" + GetDebugName(item));
            return true;
        }
        return super.TakeEntityToTargetAttachmentImpl(mode, target, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToTargetCargoImpl()
override protected bool ManBase::TakeEntityToTargetCargoImpl (InventoryMode mode, notnull EntityAI target, notnull EntityAI item) inline private
Definition at line 8824 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(FindInventoryLocationType.CARGO, item, target) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2TargetCgo(SPLIT) item=" + GetDebugName(item));
            return true;
        }
        return super.TakeEntityToTargetCargoImpl(mode, target, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeEntityToTargetInventoryImpl()
override protected bool ManBase::TakeEntityToTargetInventoryImpl (InventoryMode mode, notnull EntityAI target, FindInventoryLocationType flags, notnull EntityAI item) inline private
Definition at line 8813 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplit(flags, item, target) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2TargetInv(SPLIT) item=" + GetDebugName(item));
            return true;
        }
        return super.TakeEntityToTargetInventoryImpl(mode, target, flags, item);
    }
References GetDebugName(), and syncDebugPrint().
TakeToDstImpl()
override protected bool ManBase::TakeToDstImpl (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst) inline private
Definition at line 8846 of file playerbase.c.
    {
        if ( CheckAndExecuteStackSplitToInventoryLocation(dst, dst.GetItem()) )
        {
            syncDebugPrint("[inv] " + GetDebugName(this) + " STS=" + GetSimulationTimeStamp() + " Take2Dst(SPLIT) item=" + GetDebugName(dst.GetItem()));
            return true;
        }
        return super.TakeToDstImpl(mode, src, dst);
    }
References GetDebugName(), and syncDebugPrint().
TestSend()
void ManBase::TestSend () inline private
Definition at line 7244 of file playerbase.c.
    {
        if( GetGame().IsClient() ) return;
        RequestSoundEvent(1234);
        //Math.RandomInt(1,4096)
    }
References GetGame(), and RequestSoundEvent().
ToggleHeatBufferVisibility()
void ManBase::ToggleHeatBufferVisibility (bool show) inline private
Definition at line 7500 of file playerbase.c.
    {
        m_HasHeatBuffer = show;
        SetSynchDirty();
    }
TogglePlacingLocal()
void ManBase::TogglePlacingLocal (ItemBase item = null) inline private
Definition at line 2210 of file playerbase.c.
    {
        if ( IsPlacingLocal() )
        {
            if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT && GetGame().IsMultiplayer() )
            {
                if (ScriptInputUserData.CanStoreInputUserData())
                {
                    ScriptInputUserData ctx = new ScriptInputUserData;
                    ctx.Write(INPUT_UDT_ADVANCED_PLACEMENT);
                    ctx.Send();
                }
            }
            PlacingCancelLocal();
        }
        else if (!item)
        {
            PlacingStartLocal( GetItemInHands() );
        }
        else
        {
            PlacingStartLocal(item);
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetInstanceType(), INPUT_UDT_ADVANCED_PLACEMENT, ScriptInputUserData::Send(), and Serializer::Write().
TogglePlacingServer()
bool ManBase::TogglePlacingServer (int userDataType, ParamsReadContext ctx) inline private
Definition at line 2164 of file playerbase.c.
    {
        if ( userDataType == INPUT_UDT_ADVANCED_PLACEMENT )
        {
            PlacingCancelServer();
            return true;
        }
        return false;
    }
References INPUT_UDT_ADVANCED_PLACEMENT.
TryHideItemInHands()
void ManBase::TryHideItemInHands (bool hide, bool force = false) inline private
tries to hide item in player's hands, some exceptions for various movement states
Definition at line 8722 of file playerbase.c.
    {
        if ( !hide && ((!IsSwimming() && !IsClimbingLadder() && !IsInVehicle() && !AnimCommandCheck(HumanMoveCommandID.CommandSwim | HumanMoveCommandID.CommandLadder | HumanMoveCommandID.CommandVehicle)) || force) )
        {
            GetItemAccessor().HideItemInHands(false);
        }
        else
        {
            GetItemAccessor().HideItemInHands(true);
        }
    }
References GetItemAccessor().
UnsetMixedSoundState()
void ManBase::UnsetMixedSoundState (eMixedSoundStates state) inline private
Definition at line 593 of file playerbase.c.
    {
        int bit_mask_remove = ~state;
        eMixedSoundStates new_states = m_MixedSoundStates & bit_mask_remove;
        if(new_states != m_MixedSoundStates)
        {
            m_MixedSoundStates = new_states;
            SetSynchDirty();
        }
    }
UpdateBrokenLegs()
void ManBase::UpdateBrokenLegs (int stateId) inline private
Definition at line 3282 of file playerbase.c.
    {
        eBrokenLegs state = GetBrokenLegs();
        //Raise broken legs flag and force to prone
        if (state != eBrokenLegs.NO_BROKEN_LEGS)
        {
            if ( state == eBrokenLegs.BROKEN_LEGS_SPLINT )
            {
                if ( m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE )
                {
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PRONE_ANIM_OVERRIDE;
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS;
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.BROKEN_LEGS_SPLINT;
                }
                m_InjuryHandler.CheckValue(false);
            }
            else if ( state == eBrokenLegs.BROKEN_LEGS )
            {
                if ( m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE )
                {
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.PRONE_ANIM_OVERRIDE;
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS_SPLINT;
                    m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.BROKEN_LEGS;
                }
                BrokenLegWalkShock();
                m_InjuryHandler.CheckValue(false);
            }
        }
        else if (state == eBrokenLegs.NO_BROKEN_LEGS)
        {
            m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS;
            m_InjuryHandler.m_ForceInjuryAnimMask = m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.BROKEN_LEGS_SPLINT;
        }
    }
References m_MovementState.
UpdateCorpseState()
void ManBase::UpdateCorpseState () inline private
Definition at line 5458 of file playerbase.c.
    {
        UpdateCorpseStateVisual();
        if(m_CorpseState > 0)
            SetDecayEffects(Math.AbsInt(m_CorpseState));
        else if(m_CorpseState < 0)
            SetDecayEffects();//no params means remove the effects
        m_CorpseStateLocal = m_CorpseState;
    }
References Math::AbsInt().
UpdateCorpseStateVisual()
void ManBase::UpdateCorpseStateVisual () inline private
Definition at line 8523 of file playerbase.c.
    {
        //Print("---Prettying up corpses... | " + GetGame().GetTime() + " | " + this + " | " + GetType() + "---");
        //Print("m_DecayedTexture = " + m_DecayedTexture);
        int state = Math.AbsInt(m_CorpseState);//negative sign denotes a special meaning(state was forced to a live player), but we are only intetested in the positive value here
        if( state == PlayerConstants.CORPSE_STATE_DECAYED )
        {
            EntityAI bodypart;
            ItemBase item;
            string path;
            int idx;
            int slot_id;
            array<string> bodyparts = {"Gloves","Body","Legs","Feet"};
            for (int i = 0; i < bodyparts.Count(); i++)
            {
                slot_id = InventorySlots.GetSlotIdFromString(bodyparts.Get(i));
                bodypart = GetInventory().FindPlaceholderForSlot( slot_id );
                item = ItemBase.Cast(GetInventory().FindAttachment( slot_id ));
                if( bodypart )
                {
                    path = "cfgVehicles " + bodypart.GetType();
                    idx = bodypart.GetHiddenSelectionIndex("personality");
                    if( idx > -1 )
                    {
                        bodypart.SetObjectTexture(idx,m_DecayedTexture);
                    }
                }
                if( item )
                {
                    path = "cfgVehicles " + item.GetType();
                    idx = item.GetHiddenSelectionIndex("personality");
                    if( idx > -1 )
                    {
                        item.SetObjectTexture(idx,m_DecayedTexture);
                    }
                }
            }
            SetFaceTexture(m_DecayedTexture);
        }
    }
References Math::AbsInt(), PlayerConstants::CORPSE_STATE_DECAYED, FindAttachment(), InventorySlots::GetSlotIdFromString(), and path.
UpdateDelete()
void ManBase::UpdateDelete () inline private
Definition at line 7676 of file playerbase.c.
    {
        int count = m_ItemsToDelete.Count();
        if (count > 0)
        {
            if (CanDeleteItems())
            {
                EntityAI itemToDelete;
                if (GetGame().IsClient() && GetGame().IsMultiplayer())
                {
                    InventoryLocation il = new InventoryLocation();
                    for (int i = count - 1; i >= 0 ; i--)
                    {
                        itemToDelete = m_ItemsToDelete.Get(i);
                        if (itemToDelete != null)
{
                            itemToDelete.GetInventory().GetCurrentInventoryLocation(il);
                        }
                        if (itemToDelete == null || (GetItemInHands() == null && il.GetType() == InventoryLocationType.UNKNOWN))
{
                            m_ItemsToDelete.Remove(i);
                        }
                    }
                }
                else
                {
                    for (int j = count - 1; j >= 0 ; j--)
                    {
                        itemToDelete = m_ItemsToDelete.Get(j);
                        if (itemToDelete == null)
{
                            m_ItemsToDelete.Remove(j);
                        }
                        else
{
                            itemToDelete.Delete();
                            m_ItemsToDelete.Remove(j);
                        }
                    }
                }
            }
        }
    }
References GetGame(), and InventoryLocation::GetType().
UpdateHairSelectionVisibility()
void ManBase::UpdateHairSelectionVisibility (bool was_debug = false) inline private
Definition at line 8339 of file playerbase.c.
    {
        if (!m_CharactersHead)
            return;
        bool shown;
        bool exception_hidden = false;
        int i;
        SelectionTranslation stt;
        //hide/show beard
        if ( IsMale() && m_CharactersHead.GetBeardIndex() > -1 && !was_debug )
        {
            SetHairLevelToHide(m_CharactersHead.GetBeardIndex(),GetLifeSpanState() != LifeSpanState.BEARD_EXTRA);
        }
        //show all first
        for (i = 0; i < m_CharactersHead.m_HeadHairHidingStateMap.Count(); i++)
        {
            m_CharactersHead.SetSimpleHiddenSelectionState(i,true);
        }
        //then carve it up
        for (i = 0; i < m_CharactersHead.m_HeadHairHidingStateMap.Count(); i++)
        {
            stt = m_CharactersHead.m_HeadHairHidingStateMap.Get(i);
            shown = stt.GetSelectionState();
            if (!shown)
            {
                if ( /*IsMale() && */!m_CharactersHead.IsHandlingException() )
                {
                    m_CharactersHead.SetSimpleHiddenSelectionState(i,shown);
                    UpdateTranslatedSelections(stt);
                    //Print("hidden idx: " + i);
                }
                else
                {
                    exception_hidden = true;
                }
            }
        }
        //exceptions handled differently; hides hair
        if ( exception_hidden )
        {
            m_CharactersHead.SetSimpleHiddenSelectionState(m_CharactersHead.GetHairIndex(),false);
            if ( IsMale() )
                m_CharactersHead.SetSimpleHiddenSelectionState(m_CharactersHead.GetBeardIndex(),false);
        }
    }
References SelectionTranslation::GetSelectionState().
UpdateLighting()
void ManBase::UpdateLighting () inline private
Definition at line 5377 of file playerbase.c.
    {
        Mission mission = GetGame().GetMission();
        if ( mission )
        {
            WorldLighting wLighting = mission.GetWorldLighting();
            if ( wLighting )
                wLighting.SetGlobalLighting( CfgGameplayHandler.GetLightingConfig());
        }
    }
References GetGame(), CfgGameplayHandler::GetLightingConfig(), CGame::GetMission(), Mission::GetWorldLighting(), mission, and WorldLighting::SetGlobalLighting().
UpdateMaskBreathWidget()
void ManBase::UpdateMaskBreathWidget (notnull MaskBase mask, bool is_start = false) inline private
Definition at line 5771 of file playerbase.c.
    {
        if(is_start)
            m_EffectWidgets.ResetMaskUpdateCount();
        float resistance = 0;
        if ( mask.HasIntegratedFilter() || mask.IsExternalFilterAttached() )
            resistance = 1 - mask.GetFilterQuantity01();
        m_EffectWidgets.OnVoiceEvent(resistance);
        m_EffectWidgets.IncreaseMaskUpdateCount();
    }
References GameplayEffectWidgets_base::OnVoiceEvent().
UpdatePlayerMeasures()
void ManBase::UpdatePlayerMeasures () inline private
Definition at line 6832 of file playerbase.c.
    {
        int hour, minute, second;
        GetHourMinuteSecond( hour, minute, second );
        float distance;
        distance = StatGet("playtime");
        if ( m_AnalyticsTimer )
        {
            StatsEventMeasuresData data = new StatsEventMeasuresData();
            data.m_CharacterId = g_Game.GetDatabaseID();
            data.m_TimeInterval = m_AnalyticsTimer.GetRemaining();
            data.m_DaytimeHour = hour;
            data.m_PositionStart = m_PlayerOldPos;
            data.m_PositionEnd = GetPosition();
            data.m_DistanceOnFoot = distance;
            Analytics.PlayerMeasures(data);
        }
        m_PlayerOldPos = GetPosition();
    }
References g_Game, GetHourMinuteSecond(), GetPosition, StatsEventMeasuresData::m_CharacterId, StatsEventMeasuresData::m_DaytimeHour, StatsEventMeasuresData::m_DistanceOnFoot, StatsEventMeasuresData::m_PositionEnd, StatsEventMeasuresData::m_PositionStart, StatsEventMeasuresData::m_TimeInterval, and Analytics::PlayerMeasures().
UpdateQuickBarEntityVisibility()
void ManBase::UpdateQuickBarEntityVisibility (EntityAI entity) inline private
Definition at line 1809 of file playerbase.c.
    {
        int i = FindQuickBarEntityIndex(entity);
        if( i >= 0 )
            m_QuickBarBase.UpdateShotcutVisibility(i);
    }
UpdateQuickBarExtraSlots()
void ManBase::UpdateQuickBarExtraSlots () inline private
Definition at line 7266 of file playerbase.c.
    {
        m_QuickBarBase.updateSlotsCount();
    }
UpdateShoulderProxyVisibility()
void ManBase::UpdateShoulderProxyVisibility (EntityAI item, string slot_name) inline private
Definition at line 1086 of file playerbase.c.
    {
        string slot = slot_name;
        bool boo;
        boo = item.IsWeapon();
        if ( slot == "Melee" )
        {
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_MELEE_RIFLE,boo);
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_MELEE_MELEE,!boo);
        }
        else if ( slot == "Shoulder" )
        {
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_SHOULDER_RIFLE,boo);
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_SHOULDER_MELEE,!boo);
        }
    }
References SIMPLE_SELECTION_MELEE_MELEE, SIMPLE_SELECTION_MELEE_RIFLE, SIMPLE_SELECTION_SHOULDER_MELEE, and SIMPLE_SELECTION_SHOULDER_RIFLE.
UpdateTranslatedSelections()
void ManBase::UpdateTranslatedSelections (SelectionTranslation stt) inline private
Definition at line 8388 of file playerbase.c.
    {
        int index;
        array<int> translatedSelectinosArray = stt.GetTranslatedSelections();
        for (int i = 0; i < translatedSelectinosArray.Count(); i++)
        {
            index = translatedSelectinosArray.Get(i);
            //if (index > -1)
                m_CharactersHead.SetSimpleHiddenSelectionState(index,false); //safe this way, only hiding/carving from shown parts
        }
    }
References SelectionTranslation::GetTranslatedSelections().
UpdateWeight()
override void ManBase::UpdateWeight (WeightUpdateType updateType = WeightUpdateType.FULL, float weightAdjustment = 0) inline private
Definition at line 4608 of file playerbase.c.
    {
        if (!GetInventory())
        {
            return;
        }
        EntityAI attachment;
        int attCount = this.GetInventory().AttachmentCount();
        int loadTotal = 0;
        for (int att = 0; att < attCount; att++)
        {
            attachment = GetInventory().GetAttachmentFromIndex(att);
            if (attachment)
            {
                loadTotal += attachment.GetWeight();
            }
        }
        ItemBase itemHands = GetItemInHands();
        if (itemHands) // adds weight of item carried in hands
        {
            loadTotal += itemHands.GetWeight();
        }
        m_Weight = loadTotal;
    }
Member Data Documentation
ACT_STORE_SAVE_VERSION
const int ManBase::ACT_STORE_SAVE_VERSION = 4 private
Definition at line 19 of file playerbase.c.
CONTAMINATED_AREA_AMBIENT
const string ManBase::CONTAMINATED_AREA_AMBIENT = "ContaminatedArea_SoundSet" private
Definition at line 153 of file playerbase.c.
DEBUG_INVENTORY_ACCESS
bool ManBase::DEBUG_INVENTORY_ACCESS = false static private
Definition at line 144 of file playerbase.c.
ItemToInventory
bool ManBase::ItemToInventory private
Definition at line 210 of file playerbase.c.
m_ActionManager
ref protected ActionManagerBase ManBase::m_ActionManager private
Definition at line 36 of file playerbase.c.
m_ActionQBControl
bool ManBase::m_ActionQBControl private
Definition at line 201 of file playerbase.c.
m_ActionsInitialize
bool ManBase::m_ActionsInitialize private
Definition at line 74 of file playerbase.c.
m_ActiveNVTypes
protected ref array<int> ManBase::m_ActiveNVTypes private
Definition at line 245 of file playerbase.c.
m_AddModifier
int ManBase::m_AddModifier = -1 private
Definition at line 186 of file playerbase.c.
m_AdminLog
PluginAdminLog ManBase::m_AdminLog private
Definition at line 249 of file playerbase.c.
m_AgentPool
ref PlayerAgentPool ManBase::m_AgentPool private
Definition at line 38 of file playerbase.c.
m_Agents
int ManBase::m_Agents private
Definition at line 39 of file playerbase.c.
m_AllowQuickFishing
protected bool ManBase::m_AllowQuickFishing private
Definition at line 119 of file playerbase.c.
m_AllowQuickRestrain
protected bool ManBase::m_AllowQuickRestrain private
Definition at line 118 of file playerbase.c.
m_AmbientContamination
EffectSound ManBase::m_AmbientContamination private
Definition at line 154 of file playerbase.c.
m_AnalyticsTimer
ref Timer ManBase::m_AnalyticsTimer private
Definition at line 232 of file playerbase.c.
m_AnimCommandStarting
protected int ManBase::m_AnimCommandStarting private
Definition at line 21 of file playerbase.c.
m_AntibioticsActive
int ManBase::m_AntibioticsActive private
Definition at line 149 of file playerbase.c.
m_aQuickBarLoad
ref array<ref Param2<EntityAI,int> > ManBase::m_aQuickBarLoad private
Definition at line 176 of file playerbase.c.
m_AreHandsLocked
bool ManBase::m_AreHandsLocked private
Definition at line 108 of file playerbase.c.
m_BleedingBits
int ManBase::m_BleedingBits private
Definition at line 113 of file playerbase.c.
m_BleedingManagerRemote
ref BleedingSourcesManagerRemote ManBase::m_BleedingManagerRemote private
Definition at line 33 of file playerbase.c.
m_BleedingManagerServer
ref BleedingSourcesManagerServer ManBase::m_BleedingManagerServer private
Definition at line 32 of file playerbase.c.
m_BleedingSourceCount
int ManBase::m_BleedingSourceCount private
Definition at line 128 of file playerbase.c.
m_BleedingSourcesLow
ref array<string> ManBase::m_BleedingSourcesLow static private
Definition at line 145 of file playerbase.c.
m_BleedingSourcesUp
ref array<string> ManBase::m_BleedingSourcesUp static private
Definition at line 146 of file playerbase.c.
m_BloodType
private int ManBase::m_BloodType private
Definition at line 7 of file playerbase.c.
m_BreathVapour
int ManBase::m_BreathVapour private
Definition at line 122 of file playerbase.c.
m_BrokenLegsJunctureReceived
bool ManBase::m_BrokenLegsJunctureReceived private
Definition at line 139 of file playerbase.c.
m_BrokenLegSound
ref EffectSound ManBase::m_BrokenLegSound private
Definition at line 141 of file playerbase.c.
m_BrokenLegState
int ManBase::m_BrokenLegState = eBrokenLegs.NO_BROKEN_LEGS private
Definition at line 137 of file playerbase.c.
m_CameraSwayModifier
float ManBase::m_CameraSwayModifier = 0.2 private
Definition at line 110 of file playerbase.c.
m_CanDisplayHitEffectPPE
protected bool ManBase::m_CanDisplayHitEffectPPE private
Definition at line 157 of file playerbase.c.
m_CanPlayBrokenLegSound
bool ManBase::m_CanPlayBrokenLegSound private
Definition at line 143 of file playerbase.c.
m_CargoLoad
float ManBase::m_CargoLoad private
Definition at line 53 of file playerbase.c.
m_CharactersHead
Head_Default ManBase::m_CharactersHead private
Definition at line 129 of file playerbase.c.
m_CheckMeleeItem
protected ItemBase ManBase::m_CheckMeleeItem private
Definition at line 237 of file playerbase.c.
m_CheckPulseLastTarget
PlayerBase ManBase::m_CheckPulseLastTarget private
Definition at line 131 of file playerbase.c.
m_ConfigEmotesProfile
PluginConfigEmotesProfile ManBase::m_ConfigEmotesProfile private
Definition at line 25 of file playerbase.c.
m_ConstructionActionData
ref ConstructionActionData ManBase::m_ConstructionActionData private
Definition at line 204 of file playerbase.c.
m_ContaminatedAreaEffectEnabled
bool ManBase::m_ContaminatedAreaEffectEnabled private
Definition at line 152 of file playerbase.c.
m_ContaminatedAroundPlayer
protected Particle ManBase::m_ContaminatedAroundPlayer static private
Definition at line 252 of file playerbase.c.
m_ContaminatedAroundPlayerTiny
protected Particle ManBase::m_ContaminatedAroundPlayerTiny static private
Definition at line 253 of file playerbase.c.
m_CorpseProcessing
bool ManBase::m_CorpseProcessing private
Definition at line 95 of file playerbase.c.
m_CorpseState
int ManBase::m_CorpseState private
Definition at line 96 of file playerbase.c.
m_CorpseStateLocal
protected int ManBase::m_CorpseStateLocal private
Definition at line 97 of file playerbase.c.
m_CraftingInitialPos
vector ManBase::m_CraftingInitialPos private
Definition at line 193 of file playerbase.c.
m_CraftingManager
ref CraftingManager ManBase::m_CraftingManager private
Definition at line 78 of file playerbase.c.
m_CurrentCamera
DayZPlayerCameraBase ManBase::m_CurrentCamera private
Definition at line 112 of file playerbase.c.
m_CurrentShock
float ManBase::m_CurrentShock private
Definition at line 103 of file playerbase.c.
m_DamageDealtEffect
ref DamageDealtEffect ManBase::m_DamageDealtEffect private
Definition at line 66 of file playerbase.c.
m_DatabaseID
string ManBase::m_DatabaseID private
Definition at line 231 of file playerbase.c.
m_DbgListSelection
int ManBase::m_DbgListSelection = 0 private
Definition at line 2555 of file playerbase.c.
m_DbgOptions
ref array<string> ManBase::m_DbgOptions = {"jedna", "dva", "tri"} private
Definition at line 2557 of file playerbase.c.
m_DbgSliderValue
float ManBase::m_DbgSliderValue = 0.0 private
Definition at line 2556 of file playerbase.c.
m_DeathCheckTimer
ref Timer ManBase::m_DeathCheckTimer private
Definition at line 94 of file playerbase.c.
m_DeathDarkeningParam
ref Param1<float> ManBase::m_DeathDarkeningParam private
Definition at line 65 of file playerbase.c.
m_DebugMonitorEnabled
int ManBase::m_DebugMonitorEnabled private
Definition at line 215 of file playerbase.c.
m_DebugMonitorValues
ref DebugMonitorValues ManBase::m_DebugMonitorValues private
Definition at line 51 of file playerbase.c.
m_DecayedTexture
string ManBase::m_DecayedTexture private
Definition at line 135 of file playerbase.c.
m_DefaultHitPosition
vector ManBase::m_DefaultHitPosition private
Definition at line 115 of file playerbase.c.
m_DirectionToCursor
vector ManBase::m_DirectionToCursor private
Definition at line 114 of file playerbase.c.
m_DiseaseCount
int ManBase::m_DiseaseCount private
Definition at line 116 of file playerbase.c.
m_dT
protected float ManBase::m_dT private
Definition at line 88 of file playerbase.c.
m_EffectRadial
ref EffectRadial ManBase::m_EffectRadial private
Definition at line 67 of file playerbase.c.
m_EffectWidgets
protected PlayerStat<int> m_StatWet protected PlayerStat<int> m_StatBloodType protected PlayerStat<float> m_StatDiet protected PlayerStat<float> m_StatStamina protected PlayerStat<float> m_StatSpecialty protected PlayerStat<float> m_StatHeatBuffer protected GameplayEffectWidgets_base ManBase::m_EffectWidgets private
effect widgets
Definition at line 268 of file playerbase.c.
m_EmoteManager
ref EmoteManager ManBase::m_EmoteManager private
Definition at line 41 of file playerbase.c.
m_EmptyGloves
ref HiddenSelectionsData ManBase::m_EmptyGloves private
Definition at line 76 of file playerbase.c.
m_Environment
ref Environment ManBase::m_Environment private
Definition at line 40 of file playerbase.c.
m_FlagRaisingTendency
private bool ManBase::m_FlagRaisingTendency private
Definition at line 10 of file playerbase.c.
m_FlashbangEffect
ref FlashbangEffect ManBase::m_FlashbangEffect private
Definition at line 68 of file playerbase.c.
m_FliesEff
ref EffectParticle ManBase::m_FliesEff private
Definition at line 70 of file playerbase.c.
m_FliesIndex
int ManBase::m_FliesIndex private
Definition at line 58 of file playerbase.c.
m_ForceInjuryAnimMask
int ManBase::m_ForceInjuryAnimMask private
Definition at line 132 of file playerbase.c.
m_hac
ActionUnfoldMapCB ManBase::m_hac private
Definition at line 218 of file playerbase.c.
m_HasBloodTypeVisible
private bool ManBase::m_HasBloodTypeVisible private
Definition at line 8 of file playerbase.c.
m_HasBloodyHandsVisible
private int ManBase::m_HasBloodyHandsVisible private
Definition at line 11 of file playerbase.c.
m_HasHeatBuffer
protected bool ManBase::m_HasHeatBuffer private
Definition at line 12 of file playerbase.c.
m_HCAnimHandler
ref HeatComfortAnimHandler ManBase::m_HCAnimHandler private
Definition at line 83 of file playerbase.c.
m_HealingsCount
int ManBase::m_HealingsCount private
Definition at line 117 of file playerbase.c.
m_HealthLevel
int ManBase::m_HealthLevel private
Definition at line 123 of file playerbase.c.
m_HideHairAnimated
bool ManBase::m_HideHairAnimated private
Definition at line 134 of file playerbase.c.
m_HologramLocal
ref Hologram ManBase::m_HologramLocal private
Definition at line 180 of file playerbase.c.
m_HologramServer
ref Hologram ManBase::m_HologramServer private
Definition at line 179 of file playerbase.c.
m_Hud
Hud ManBase::m_Hud private
Definition at line 87 of file playerbase.c.
m_ImmunityBoosted
bool ManBase::m_ImmunityBoosted private
Definition at line 107 of file playerbase.c.
m_InjuryHandler
ref InjuryAnimationHandler ManBase::m_InjuryHandler private
Definition at line 46 of file playerbase.c.
m_InputActionMap
ref TInputActionMap ManBase::m_InputActionMap private
Definition at line 71 of file playerbase.c.
m_InputActionMapAsTarget
ref TInputActionMap ManBase::m_InputActionMapAsTarget private
Definition at line 73 of file playerbase.c.
m_InputActionMapControled
ref TInputActionMap ManBase::m_InputActionMapControled private
Definition at line 72 of file playerbase.c.
m_InventoryActionHandler
ref InventoryActionHandler ManBase::m_InventoryActionHandler private
Definition at line 79 of file playerbase.c.
m_InventorySoftLocked
protected bool ManBase::m_InventorySoftLocked private
Definition at line 227 of file playerbase.c.
m_IsCraftingReady
bool ManBase::m_IsCraftingReady private
Definition at line 191 of file playerbase.c.
m_IsDrowning
bool ManBase::m_IsDrowning private
Definition at line 212 of file playerbase.c.
m_IsFighting
bool ManBase::m_IsFighting = false private
Definition at line 211 of file playerbase.c.
m_IsHoldingBreath
protected bool ManBase::m_IsHoldingBreath private
Definition at line 90 of file playerbase.c.
m_IsInWater
protected bool ManBase::m_IsInWater private
Definition at line 91 of file playerbase.c.
m_IsRestrained
bool ManBase::m_IsRestrained private
Definition at line 104 of file playerbase.c.
m_IsRestrainPrelocked
bool ManBase::m_IsRestrainPrelocked private
Definition at line 106 of file playerbase.c.
m_IsRestrainStarted
bool ManBase::m_IsRestrainStarted private
Definition at line 105 of file playerbase.c.
m_IsVehicleSeatDriver
bool ManBase::m_IsVehicleSeatDriver private
Definition at line 126 of file playerbase.c.
m_Item1
EntityAI ManBase::m_Item1 private
Definition at line 189 of file playerbase.c.
m_Item2
EntityAI ManBase::m_Item2 private
Definition at line 190 of file playerbase.c.
m_ItemsToDelete
protected ref array<EntityAI> ManBase::m_ItemsToDelete private
Definition at line 136 of file playerbase.c.
m_LastFirePoint
vector ManBase::m_LastFirePoint private
Definition at line 206 of file playerbase.c.
m_LastFirePointIndex
int ManBase::m_LastFirePointIndex private
Definition at line 208 of file playerbase.c.
m_LastFirePointRot
float ManBase::m_LastFirePointRot private
Definition at line 207 of file playerbase.c.
m_LastMapPos
protected vector ManBase::m_LastMapPos private
Definition at line 223 of file playerbase.c.
m_LastMapScale
protected float ManBase::m_LastMapScale = -1.0 private
Definition at line 222 of file playerbase.c.
m_LastPostFrameTickTime
float ManBase::m_LastPostFrameTickTime private
Definition at line 92 of file playerbase.c.
m_LastShavedSeconds
private int ManBase::m_LastShavedSeconds private
Definition at line 6 of file playerbase.c.
m_LastShockHitTime
float ManBase::m_LastShockHitTime private
Definition at line 111 of file playerbase.c.
m_LastTick
float ManBase::m_LastTick = -1 private
Definition at line 185 of file playerbase.c.
m_LifespanLevelLocal
protected int ManBase::m_LifespanLevelLocal private
Definition at line 20 of file playerbase.c.
m_LifeSpanState
private int ManBase::m_LifeSpanState private
Definition at line 5 of file playerbase.c.
m_LiquidTendencyDrain
private bool ManBase::m_LiquidTendencyDrain private
Definition at line 9 of file playerbase.c.
m_LocalBrokenState
int ManBase::m_LocalBrokenState = eBrokenLegs.NO_BROKEN_LEGS private
Definition at line 138 of file playerbase.c.
m_LocalProjectionOrientation
vector ManBase::m_LocalProjectionOrientation = "0 0 0 " private
Definition at line 182 of file playerbase.c.
m_LocalProjectionPosition
vector ManBase::m_LocalProjectionPosition = "0 0 0 " private
Definition at line 181 of file playerbase.c.
m_LocalRefreshAnimStateIdx
protected int ManBase::m_LocalRefreshAnimStateIdx private
Definition at line 16 of file playerbase.c.
m_LoweredNVGHeadset
bool ManBase::m_LoweredNVGHeadset private
Definition at line 244 of file playerbase.c.
m_MapCloseRequestProcessed
bool ManBase::m_MapCloseRequestProcessed private
Definition at line 220 of file playerbase.c.
m_MapClosingSyncSent
protected bool ManBase::m_MapClosingSyncSent private
Definition at line 221 of file playerbase.c.
m_MapNavigationBehaviour
protected ref MapNavigationBehaviour ManBase::m_MapNavigationBehaviour private
Definition at line 224 of file playerbase.c.
m_MapOpen
bool ManBase::m_MapOpen private
Definition at line 219 of file playerbase.c.
m_MeleeDebug
protected bool ManBase::m_MeleeDebug private
melee stats
Definition at line 235 of file playerbase.c.
m_MixedSoundStates
int ManBase::m_MixedSoundStates private
Definition at line 124 of file playerbase.c.
m_ModifiersManager
ref ModifiersManager ManBase::m_ModifiersManager private
Definition at line 34 of file playerbase.c.
m_ModuleLifespan
private PluginLifespan ManBase::m_ModuleLifespan private
Definition at line 26 of file playerbase.c.
m_ModulePlayerStatus
private PluginPlayerStatus ManBase::m_ModulePlayerStatus private
Definition at line 24 of file playerbase.c.
m_ModuleRecipesManager
PluginRecipesManager ManBase::m_ModuleRecipesManager private
Definition at line 31 of file playerbase.c.
m_NotifiersManager
ref NotifiersManager ManBase::m_NotifiersManager private
Definition at line 35 of file playerbase.c.
m_OriginalSlidePoseAngle
float ManBase::m_OriginalSlidePoseAngle private
Definition at line 55 of file playerbase.c.
m_PersistentFlags
int ManBase::m_PersistentFlags private
Definition at line 99 of file playerbase.c.
m_PlayerDisconnectProcessed
protected bool ManBase::m_PlayerDisconnectProcessed private
Definition at line 14 of file playerbase.c.
m_PlayerLoaded
protected bool ManBase::m_PlayerLoaded private
Definition at line 13 of file playerbase.c.
m_PlayerOldPos
vector ManBase::m_PlayerOldPos private
Definition at line 6831 of file playerbase.c.
m_PlayerSoundManagerClient
ref PlayerSoundManagerClient ManBase::m_PlayerSoundManagerClient private
Definition at line 82 of file playerbase.c.
m_PlayerSoundManagerServer
ref PlayerSoundManagerServer ManBase::m_PlayerSoundManagerServer private
Definition at line 81 of file playerbase.c.
m_PlayerStats
ref PlayerStats ManBase::m_PlayerStats private
Definition at line 30 of file playerbase.c.
m_PlayerStomach
ref PlayerStomach ManBase::m_PlayerStomach private
Definition at line 250 of file playerbase.c.
m_PresenceNotifier
protected PluginPresenceNotifier ManBase::m_PresenceNotifier private
Definition at line 27 of file playerbase.c.
m_ProcessAddEffectWidgets
protected ref array<int> ManBase::m_ProcessAddEffectWidgets private
Definition at line 269 of file playerbase.c.
m_ProcessAddGlassesEffects
protected ref array<int> ManBase::m_ProcessAddGlassesEffects private
Definition at line 273 of file playerbase.c.
m_ProcessRemoveEffectWidgets
protected ref array<int> ManBase::m_ProcessRemoveEffectWidgets private
Definition at line 270 of file playerbase.c.
m_ProcessRemoveGlassesEffects
protected ref array<int> ManBase::m_ProcessRemoveGlassesEffects private
Definition at line 274 of file playerbase.c.
m_ProcessUIWarning
protected bool ManBase::m_ProcessUIWarning private
Definition at line 15 of file playerbase.c.
m_PulseType
EPulseType ManBase::m_PulseType private
Definition at line 130 of file playerbase.c.
m_QBarItems
ref TStringArray ManBase::m_QBarItems static private
Definition at line 228 of file playerbase.c.
m_QuickBarBase
ref protected QuickBarBase ManBase::m_QuickBarBase private
Definition at line 80 of file playerbase.c.
m_QuickBarBonus
int ManBase::m_QuickBarBonus = 0 private
Definition at line 125 of file playerbase.c.
m_QuickBarFT
bool ManBase::m_QuickBarFT = false private
Definition at line 86 of file playerbase.c.
m_QuickBarHold
bool ManBase::m_QuickBarHold private
Definition at line 85 of file playerbase.c.
m_RecipeAnimLength
float ManBase::m_RecipeAnimLength private
Definition at line 192 of file playerbase.c.
m_RecipeID
int ManBase::m_RecipeID = -1 private
Definition at line 188 of file playerbase.c.
m_RecipePick
protected int ManBase::m_RecipePick private
Definition at line 89 of file playerbase.c.
m_Recipes
ref array<int> ManBase::m_Recipes private
Definition at line 194 of file playerbase.c.
m_RefreshAnimStateIdx
protected int ManBase::m_RefreshAnimStateIdx private
Definition at line 17 of file playerbase.c.
m_RGSManager
ref protected RandomGeneratorSyncManager ManBase::m_RGSManager private
Definition at line 148 of file playerbase.c.
m_SaySoundBuilder
ref SoundObjectBuilder ManBase::m_SaySoundBuilder private
Definition at line 197 of file playerbase.c.
m_SaySoundLastSetName
string ManBase::m_SaySoundLastSetName private
Definition at line 199 of file playerbase.c.
m_SaySoundObject
ref SoundObject ManBase::m_SaySoundObject private
Definition at line 198 of file playerbase.c.
m_SaySoundParams
ref SoundParams ManBase::m_SaySoundParams private
Definition at line 196 of file playerbase.c.
m_ServerPlayers
ref array<Man> ManBase::m_ServerPlayers = new array<Man> static private
Definition at line 156 of file playerbase.c.
m_Shakes
protected int ManBase::m_Shakes private
Definition at line 120 of file playerbase.c.
m_ShakesForced
protected int ManBase::m_ShakesForced private
Definition at line 121 of file playerbase.c.
m_ShockDealtEffect
ref ShockDealtEffect ManBase::m_ShockDealtEffect private
Definition at line 69 of file playerbase.c.
m_ShockHandler
ref ShockHandler ManBase::m_ShockHandler private
Definition at line 47 of file playerbase.c.
m_ShockSimplified
int ManBase::m_ShockSimplified private
Definition at line 102 of file playerbase.c.
m_ShowDbgUI
bool ManBase::m_ShowDbgUI = true private
Definition at line 2554 of file playerbase.c.
m_SoftSkillsManager
ref SoftSkillsManager ManBase::m_SoftSkillsManager private
Definition at line 48 of file playerbase.c.
m_SoundEvent
int ManBase::m_SoundEvent private
Definition at line 56 of file playerbase.c.
m_SoundEventParam
int ManBase::m_SoundEventParam private
Definition at line 57 of file playerbase.c.
m_SoundEventSent
bool ManBase::m_SoundEventSent private
Definition at line 59 of file playerbase.c.
m_SoundFliesEffect
ref EffectSound ManBase::m_SoundFliesEffect private
Definition at line 84 of file playerbase.c.
m_StaminaHandler
ref StaminaHandler ManBase::m_StaminaHandler private
Definition at line 45 of file playerbase.c.
m_StaminaParam
ref Param3<float,float,bool> ManBase::m_StaminaParam private
Definition at line 62 of file playerbase.c.
m_StaminaState
int ManBase::m_StaminaState private
Definition at line 100 of file playerbase.c.
m_StanceIndicator
ref StanceIndicator ManBase::m_StanceIndicator private
Definition at line 49 of file playerbase.c.
m_StatEnergy
protected PlayerStat<float> ManBase::m_StatEnergy private
Definition at line 257 of file playerbase.c.
m_StatHeatComfort
protected PlayerStat<float> ManBase::m_StatHeatComfort private
Definition at line 258 of file playerbase.c.
m_StatToxicity
protected PlayerStat<float> ManBase::m_StatToxicity private
Definition at line 256 of file playerbase.c.
m_StatTremor
protected PlayerStat<float> ManBase::m_StatTremor private
Definition at line 259 of file playerbase.c.
m_StatWater
protected PlayerStat<float> ManBase::m_StatWater private
Definition at line 255 of file playerbase.c.
m_StoreLoadVersion
private int ManBase::m_StoreLoadVersion private
Definition at line 18 of file playerbase.c.
m_SymptomManager
ref SymptomManager ManBase::m_SymptomManager private
Definition at line 43 of file playerbase.c.
m_SyncedModifiers
int ManBase::m_SyncedModifiers private
Definition at line 247 of file playerbase.c.
m_SyncedModifiersPrev
int ManBase::m_SyncedModifiersPrev private
Definition at line 248 of file playerbase.c.
m_TrasferValues
ref TransferValues ManBase::m_TrasferValues private
Definition at line 50 of file playerbase.c.
m_UALastMessage
protected string ManBase::m_UALastMessage private
user actions last message
Definition at line 240 of file playerbase.c.
m_UALastMessageTimer
protected ref Timer ManBase::m_UALastMessageTimer private
Definition at line 241 of file playerbase.c.
m_UAParam
ref Param2<int,int> ManBase::m_UAParam private
Definition at line 61 of file playerbase.c.
m_UAParamMessage
ref Param1<string> ManBase::m_UAParamMessage private
Definition at line 63 of file playerbase.c.
m_UAProgressParam
ref Param2<float,float> ManBase::m_UAProgressParam private
Definition at line 60 of file playerbase.c.
m_UnconParam
ref Param1<float> ManBase::m_UnconParam private
Definition at line 64 of file playerbase.c.
m_UnconRefillModifier
float ManBase::m_UnconRefillModifier = 1 private
Definition at line 147 of file playerbase.c.
m_UnconsciousEndTime
float ManBase::m_UnconsciousEndTime = 0 private
Definition at line 127 of file playerbase.c.
m_UnconsciousTime
float ManBase::m_UnconsciousTime private
Definition at line 101 of file playerbase.c.
m_UnconsciousVignetteTarget
float ManBase::m_UnconsciousVignetteTarget = 2 private
Definition at line 109 of file playerbase.c.
m_UndergroundHandler
protected ref UndergroundHandlerClient ManBase::m_UndergroundHandler private
Definition at line 29 of file playerbase.c.
m_UndergroundPresence
EUndergroundPresence ManBase::m_UndergroundPresence private
Definition at line 22 of file playerbase.c.
m_VirtualHud
ref VirtualHud ManBase::m_VirtualHud private
Definition at line 44 of file playerbase.c.
m_VisibilityCoef
float ManBase::m_VisibilityCoef private
Definition at line 54 of file playerbase.c.
m_WeaponManager
ref WeaponManager ManBase::m_WeaponManager private
Definition at line 77 of file playerbase.c.
m_WorkingNVGHeadset
bool ManBase::m_WorkingNVGHeadset private
Definition at line 243 of file playerbase.c.
OVERLOAD_LIMIT
const int ManBase::OVERLOAD_LIMIT = 30000 private
Definition at line 52 of file playerbase.c.
SHAKE_LEVEL_MAX
const int ManBase::SHAKE_LEVEL_MAX = 7 private
Definition at line 4 of file playerbase.c.
SIMPLIFIED_SHOCK_CAP
const int ManBase::SIMPLIFIED_SHOCK_CAP = 63 private
Definition at line 3 of file playerbase.c.
SOUND_BREAK_LEG
const string ManBase::SOUND_BREAK_LEG = "broken_leg_SoundSet" private
Definition at line 142 of file playerbase.c.
SPREAD_AGENTS_OBJECTS
ref array<Object> ManBase::SPREAD_AGENTS_OBJECTS = new array<Object> static private
Definition at line 7286 of file playerbase.c.
SPREAD_AGENTS_PROXY_CARGOS
ref array<CargoBase> ManBase::SPREAD_AGENTS_PROXY_CARGOS = new array<CargoBase> static private
Definition at line 7287 of file playerbase.c.