DayzKode: ActionWorldLiquidActionSwitch Class Reference
ActionWorldLiquidActionSwitch Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionWorldLiquidActionSwitch ()
override void CreateConditionComponents ()
override bool IsInstant ()
override bool IsLocal ()
override bool RemoveForceTargetAfterUse ()
override void Start (ActionData action_data)
Private Attributes
bool m_switch_to
Detailed Description
Definition at line 2 of file actionworldliquidactionswitch.c.
Constructor & Destructor Documentation
ActionWorldLiquidActionSwitch()
void ActionWorldLiquidActionSwitch::ActionWorldLiquidActionSwitch () inline private
Definition at line 5 of file actionworldliquidactionswitch.c.
    {
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE;
    }
References m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionWorldLiquidActionSwitch::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 24 of file actionworldliquidactionswitch.c.
    {
        ItemBase target_item = ItemBase.Cast(target.GetObject());
        if (Barrel_ColorBase.Cast(target_item) && !target_item.IsOpen())
            return false;
        if ( target_item && item && Liquid.CanFillContainer( item, target_item.GetLiquidType(),true ) && Liquid.CanFillContainer( target_item, item.GetLiquidType(), true ) && !GetGame().IsInventoryOpen() ) //TODO find better condition than IsKindOf
        {
            if ( target_item.GetQuantity() > target_item.GetQuantityMin() && item.GetQuantity() < item.GetQuantityMax() && !player.GetLiquidTendencyDrain() && Liquid.CanFillContainer( item, target_item.GetLiquidType() ) )
            {
                if ( Liquid.CanFillContainer( target_item, item.GetLiquidType() ) )
                {
                    m_switch_to = 0;//"#liquid_drain";
                    return true;
                }
                else
                {
                    player.SetLiquidTendencyDrain(true);
                    return false;
                }
            }
            if ( item.GetQuantity() > item.GetQuantityMin() && target_item.GetQuantity() < target_item.GetQuantityMax() && player.GetLiquidTendencyDrain() && Liquid.CanFillContainer( target_item, item.GetLiquidType() ) )
            {
                if ( Liquid.CanFillContainer( item, target_item.GetLiquidType() ) )
                {
                    m_switch_to = 1;//"#liquid_pour";
                    return true;
                }
                else
                {
                    player.SetLiquidTendencyDrain(false);
                    return false;
                }
            }
        }
        return false;
    }
References Liquid::CanFillContainer(), GetGame(), IsInventoryOpen(), and m_switch_to.
CreateConditionComponents()
override void ActionWorldLiquidActionSwitch::CreateConditionComponents () inline private
Definition at line 10 of file actionworldliquidactionswitch.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsInstant()
override bool ActionWorldLiquidActionSwitch::IsInstant () inline private
Definition at line 77 of file actionworldliquidactionswitch.c.
    {
        return true;
    }
IsLocal()
override bool ActionWorldLiquidActionSwitch::IsLocal () inline private
Definition at line 72 of file actionworldliquidactionswitch.c.
    {
        return true;
    }
RemoveForceTargetAfterUse()
override bool ActionWorldLiquidActionSwitch::RemoveForceTargetAfterUse () inline private
Definition at line 82 of file actionworldliquidactionswitch.c.
    {
        return false;
    }
Start()
override void ActionWorldLiquidActionSwitch::Start (ActionData action_data) inline private
Definition at line 62 of file actionworldliquidactionswitch.c.
    {
        super.Start( action_data );
        bool state;
        state = action_data.m_Player.GetLiquidTendencyDrain();
        action_data.m_Player.SetLiquidTendencyDrain(!state);
        //Print(action_data.m_Player.GetLiquidTendencyDrain());
    }
References ActionData::m_Player.
Member Data Documentation
m_switch_to
bool ActionWorldLiquidActionSwitch::m_switch_to private
Definition at line 4 of file actionworldliquidactionswitch.c.
Referenced by ActionCondition().