DayzKode: ActionPourLiquid Class Reference
ActionPourLiquid Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPourLiquid ()
override void CreateConditionComponents ()
override bool HasProneException ()
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
Detailed Description
Definition at line 11 of file actionpourliquid.c.
Constructor & Destructor Documentation
ActionPourLiquid()
void ActionPourLiquid::ActionPourLiquid () inline private
Definition at line 13 of file actionpourliquid.c.
    {
        m_CallbackClass = ActionPourLiquidCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_Text = "#pour_liquid";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionPourLiquid::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 33 of file actionpourliquid.c.
    {
        ItemBase target_item = ItemBase.Cast(target.GetObject());
        if ( target_item && item )
        {
                return Liquid.CanTransfer(item,target_item);;
        }
        return false;
    }
References Liquid::CanTransfer().
CreateConditionComponents()
override void ActionPourLiquid::CreateConditionComponents () inline private
Definition at line 22 of file actionpourliquid.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionPourLiquid::HasProneException () inline private
Definition at line 28 of file actionpourliquid.c.
    {
        return true;
    }
OnEndAnimationLoop()
override void ActionPourLiquid::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 60 of file actionpourliquid.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            Bottle_Base target_vessel = Bottle_Base.Cast( action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>( false );
            GetGame().RPCSingleParam( target_vessel, SoundTypeBottle.POURING, play, true );
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void ActionPourLiquid::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 44 of file actionpourliquid.c.
    {
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References ActionData::m_Player, and m_SpecialtyWeight.
OnStartAnimationLoop()
override void ActionPourLiquid::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 49 of file actionpourliquid.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            Bottle_Base vessel_in_hands = Bottle_Base.Cast( action_data.m_Target.GetObject() );
            Param1<bool> play = new Param1<bool>( true );
            GetGame().RPCSingleParam( vessel_in_hands, SoundTypeBottle.POURING, play, true );
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().