DayzKode: PPEMatClassParameterCommandData Class Reference
PPEMatClassParameterCommandData Class Reference
Private Member Functions
void AddPriorityInfo (int priority)
Adds 'layers' to be iterated throug.
void DbgPrnt (string text)
Param GetCurrentValues ()
Careful, only actual values, WITHOUT string.
Param GetDefaultValues ()
Careful, formating is such, that param1 is ALWAYS string, containing parameter name, should it be needed. Actual values follow.
override int GetParameterVarType ()
int GetParameterVarType ()
override int GetParameterVarType ()
override int GetParameterVarType ()
override int GetParameterVarType ()
override int GetParameterVarType ()
override int GetParameterVarType ()
override void InitCuttent ()
protected void InitCuttent ()
override void InitCuttent ()
override void InitCuttent ()
override void InitDefaults ()
protected void InitDefaults ()
override void InitDefaults ()
override void InitDefaults ()
void InsertRequestData (PPERequestParamDataBase request_data)
void ModifyResultValues (inout Param result_values)
Modifies values to be used for setter methods later in the manager update. Currently used only on PPEMatClassParameterColor, TODO!!
void PPEMatClassParameterBool (int mat_idx, int parameter_idx, PPEClassBase parent)
void PPEMatClassParameterCommandData (int mat_idx, int parameter_idx, PPEClassBase parent)
void PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent)
void PPEMatClassParameterInt (int mat_idx, int parameter_idx, PPEClassBase parent)
void PrepareLayerInfo (int layer, bool value, int operator)
void PrepareLayerInfo (int layer, float value, int operator)
void PrepareLayerInfo (int layer, int value, int operator)
void RegisterDefaults (Param p)
Adds name and default values from material registration, override on children to properly add for each type.
void RemovePriorityInfo (int priority)
Currently unused; layer info gets cleared every update.
void SetMaterialIndex (int value)
void SetParameterIndex (int value)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT.
protected void SetParameterValueDefault (inout Param p_total)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
override void SetParameterValueDefault (inout Param p_total)
No active requests for the mat. parameter value change, sets the value to DEFAULT.
void SetParent (PPEClassBase parent)
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
override void Update (float timeslice, out Param p_total, out bool setting_defaults, int order)
Private Attributes
const int LAYER_INFO_OPERATOR = 1
const int LAYER_INFO_VALUE = 0
protected PPETemplateDefBool m_Bool
ref array< int > m_CommandLayersArray
protected ref Param m_CurrentValues
protected ref Param m_Defaults
protected ref map< int, ref array< int > > m_Dependencies
protected PPETemplateDefFloat m_Float
protected PPETemplateDefInt m_Int
protected ref map< int, ref array< bool, int > > m_LayerInfo
protected ref map< int, ref array< float, int > > m_LayerInfo
protected ref map< int, ref array< int, int > > m_LayerInfo
protected int m_MaterialIndex
protected int m_ParameterIndex
protected PPEClassBase m_Parent
protected ref ActiveParameterRequestsMap m_RequestMap
protected int m_UpdatedCount
protected bool m_ValueDefault
protected float m_ValueDefault
protected int m_ValueDefault
protected float m_ValueMax
protected float m_ValueMin
Detailed Description
Definition at line 1 of file ppematclassparameterbool.c.
Constructor & Destructor Documentation
PPEMatClassParameterCommandData()
void PPEMatClassParameterCommandData::PPEMatClassParameterCommandData (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
Definition at line 20 of file ppematclassparametercommanddata.c.
    {
        m_MaterialIndex = mat_idx;
        m_ParameterIndex = parameter_idx;
        m_Parent = parent;
        m_CommandLayersArray = new array<int>;
        m_UpdatedCount = 0;
        m_RequestMap = new ActiveParameterRequestsMap;
    }
References m_CommandLayersArray, m_MaterialIndex, m_ParameterIndex, m_Parent, m_RequestMap, and m_UpdatedCount.
Member Function Documentation
AddPriorityInfo()
void PPEMatClassParameterCommandData::AddPriorityInfo (int priority) inline private
Adds 'layers' to be iterated throug.
Definition at line 81 of file ppematclassparametercommanddata.c.
    {
        if ( m_CommandLayersArray.Find(priority) == -1 )
        {
            m_CommandLayersArray.Insert(priority);
            m_CommandLayersArray.Sort();
        }
        else
        {
            //DbgPrnt("PPEDebug | PPEMatClassParameterCommandData - AddPriorityInfo | Already exists, values have been overwritten!");
        }
    }
References m_CommandLayersArray.
Referenced by PrepareLayerInfo().
DbgPrnt()
void PPEMatClassParameterCommandData::DbgPrnt (string text) inline private
Definition at line 127 of file ppematclassparametercommanddata.c.
    {
        //Debug.Log(""+text);
    }
GetCurrentValues()
Param PPEMatClassParameterCommandData::GetCurrentValues () inline private
Careful, only actual values, WITHOUT string.
Definition at line 122 of file ppematclassparametercommanddata.c.
    {
        return m_CurrentValues;
    }
References m_CurrentValues.
Referenced by GetPostProcessCurrentValues(), PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and PPEClassBase::SetFinalParameterValue().
GetDefaultValues()
Param PPEMatClassParameterCommandData::GetDefaultValues () inline private
Careful, formating is such, that param1 is ALWAYS string, containing parameter name, should it be needed. Actual values follow.
Definition at line 116 of file ppematclassparametercommanddata.c.
    {
        return m_Defaults;
    }
References m_Defaults.
Referenced by GetPostProcessDefaultValues().
GetParameterVarType() [1/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 24 of file ppematclassparameterbool.c.
    {
        return PPEConstants.VAR_TYPE_BOOL;
    }
Referenced by PPEClassBase::SetFinalParameterValue().
GetParameterVarType() [2/7]
int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 31 of file ppematclassparametercommanddata.c.
    {
        return -1;
    }
GetParameterVarType() [3/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 29 of file ppematclassparameterfloat.c.
    {
        return PPEConstants.VAR_TYPE_FLOAT;
    }
GetParameterVarType() [4/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 24 of file ppematclassparameterint.c.
    {
        return PPEConstants.VAR_TYPE_INT;
    }
GetParameterVarType() [5/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 3 of file ppematclassparameterresource.c.
    {
        return PPEConstants.VAR_TYPE_RESOURCE;
    }
GetParameterVarType() [6/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 3 of file ppematclassparametertexture.c.
    {
        return PPEConstants.VAR_TYPE_TEXTURE;
    }
GetParameterVarType() [7/7]
override int PPEMatClassParameterCommandData::GetParameterVarType () inline private
Definition at line 3 of file ppematclassparametervector.c.
    {
        return PPEConstants.VAR_TYPE_VECTOR;
    }
InitCuttent() [1/4]
override void PPEMatClassParameterCommandData::InitCuttent () inline private
Definition at line 19 of file ppematclassparameterbool.c.
    {
        m_CurrentValues = new Param1<bool>(m_ValueDefault);
    }
References m_ValueDefault.
Referenced by RegisterDefaults().
InitCuttent() [2/4]
protected void PPEMatClassParameterCommandData::InitCuttent () inline private
Definition at line 109 of file ppematclassparametercommanddata.c.
{};
InitCuttent() [3/4]
override void PPEMatClassParameterCommandData::InitCuttent () inline private
Definition at line 24 of file ppematclassparameterfloat.c.
    {
        m_CurrentValues = new Param1<float>(m_ValueDefault);
    }
References m_ValueDefault.
InitCuttent() [4/4]
override void PPEMatClassParameterCommandData::InitCuttent () inline private
Definition at line 19 of file ppematclassparameterint.c.
    {
        m_CurrentValues = new Param1<int>(m_ValueDefault);
    }
References m_ValueDefault.
InitDefaults() [1/4]
override void PPEMatClassParameterCommandData::InitDefaults () inline private
Definition at line 13 of file ppematclassparameterbool.c.
    {
        Class.CastTo(m_Bool,m_Defaults);
        m_ValueDefault = m_Bool.param2;
    }
References Class::CastTo(), and m_ValueDefault.
Referenced by RegisterDefaults().
InitDefaults() [2/4]
protected void PPEMatClassParameterCommandData::InitDefaults () inline private
Definition at line 107 of file ppematclassparametercommanddata.c.
{};
InitDefaults() [3/4]
override void PPEMatClassParameterCommandData::InitDefaults () inline private
Definition at line 15 of file ppematclassparameterfloat.c.
    {
        Class.CastTo(m_Float,m_Defaults);
        //m_Float = PPETemplateDefFloat.Cast(m_Defaults);
        m_ValueDefault = m_Float.param2;
        m_ValueMin = m_Float.param3;
        m_ValueMax = m_Float.param4;
    }
References Class::CastTo(), m_Float, m_ValueDefault, m_ValueMax, and m_ValueMin.
InitDefaults() [4/4]
override void PPEMatClassParameterCommandData::InitDefaults () inline private
Definition at line 13 of file ppematclassparameterint.c.
    {
        Class.CastTo(m_Int,m_Defaults);
        m_ValueDefault = m_Int.param2;
    }
References Class::CastTo(), and m_ValueDefault.
InsertRequestData()
void PPEMatClassParameterCommandData::InsertRequestData (PPERequestParamDataBase request_data) inline private
Definition at line 51 of file ppematclassparametercommanddata.c.
    {
        m_RequestMap.Set(request_data.GetRequesterIDX(),request_data);//<request_ID, data>
    }
References PPERequestParamDataBase::GetRequesterIDX(), and m_RequestMap.
Referenced by PPEClassBase::InsertParamValueData().
ModifyResultValues()
void PPEMatClassParameterCommandData::ModifyResultValues (inout Param result_values) inline private
Modifies values to be used for setter methods later in the manager update. Currently used only on PPEMatClassParameterColor, TODO!!
Definition at line 76 of file ppematclassparametercommanddata.c.
    {
    }
PPEMatClassParameterBool()
void PPEMatClassParameterCommandData::PPEMatClassParameterBool (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
Definition at line 8 of file ppematclassparameterbool.c.
    {
        m_LayerInfo = new map<int,ref array<bool,int>>;
    }
References m_LayerInfo.
PPEMatClassParameterFloat()
void PPEMatClassParameterCommandData::PPEMatClassParameterFloat (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
Definition at line 10 of file ppematclassparameterfloat.c.
    {
        m_LayerInfo = new map<int,ref array<float,int>>;
    }
References m_LayerInfo.
PPEMatClassParameterInt()
void PPEMatClassParameterCommandData::PPEMatClassParameterInt (int mat_idx, int parameter_idx, PPEClassBase parent) inline private
Definition at line 8 of file ppematclassparameterint.c.
    {
        m_LayerInfo = new map<int,ref array<int,int>>;
    }
References m_LayerInfo.
PrepareLayerInfo() [1/3]
void PPEMatClassParameterCommandData::PrepareLayerInfo (int layer, bool value, int operator) inline private
Definition at line 178 of file ppematclassparameterbool.c.
    {
        m_LayerInfo.Set(layer,{value,operator});
        AddPriorityInfo(layer);
    }
References AddPriorityInfo(), and m_LayerInfo.
Referenced by Update().
PrepareLayerInfo() [2/3]
void PPEMatClassParameterCommandData::PrepareLayerInfo (int layer, float value, int operator) inline private
Definition at line 227 of file ppematclassparameterfloat.c.
    {
        m_LayerInfo.Set(layer,{value,operator});
        AddPriorityInfo(layer);
    }
References AddPriorityInfo(), and m_LayerInfo.
PrepareLayerInfo() [3/3]
void PPEMatClassParameterCommandData::PrepareLayerInfo (int layer, int value, int operator) inline private
Definition at line 178 of file ppematclassparameterint.c.
    {
        m_LayerInfo.Set(layer,{value,operator});
        AddPriorityInfo(layer);
    }
References AddPriorityInfo(), and m_LayerInfo.
RegisterDefaults()
void PPEMatClassParameterCommandData::RegisterDefaults (Param p) inline private
Adds name and default values from material registration, override on children to properly add for each type.
Definition at line 100 of file ppematclassparametercommanddata.c.
    {
        m_Defaults = p;
        InitDefaults();
        InitCuttent();
    }
References InitCuttent(), InitDefaults(), and m_Defaults.
RemovePriorityInfo()
void PPEMatClassParameterCommandData::RemovePriorityInfo (int priority) inline private
Currently unused; layer info gets cleared every update.
Definition at line 95 of file ppematclassparametercommanddata.c.
    {
    }
SetMaterialIndex()
void PPEMatClassParameterCommandData::SetMaterialIndex (int value) inline private
Definition at line 36 of file ppematclassparametercommanddata.c.
    {
        m_MaterialIndex = value;
    }
References m_MaterialIndex.
SetParameterIndex()
void PPEMatClassParameterCommandData::SetParameterIndex (int value) inline private
Definition at line 41 of file ppematclassparametercommanddata.c.
    {
        m_ParameterIndex = value;
    }
References m_ParameterIndex.
SetParameterValueDefault() [1/4]
override void PPEMatClassParameterCommandData::SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT.
Definition at line 185 of file ppematclassparameterbool.c.
    {
        p_total = new Param1<bool>(PPETemplateDefBool.Cast(m_Defaults).param2);
        m_CurrentValues = p_total;
        //DbgPrnt("PPEDebug | PPEMatClassParameterBool - UpdateParameterValues | exit 3 - zero value");
    }
Referenced by Update().
SetParameterValueDefault() [2/4]
protected void PPEMatClassParameterCommandData::SetParameterValueDefault (inout Param p_total) inline private
Definition at line 111 of file ppematclassparametercommanddata.c.
    {
    }
SetParameterValueDefault() [3/4]
override void PPEMatClassParameterCommandData::SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT (zero?)
Definition at line 234 of file ppematclassparameterfloat.c.
    {
        p_total = new Param1<float>(PPETemplateDefFloat.Cast(m_Defaults).param2);
        m_CurrentValues = p_total;
        //DbgPrnt("PPEDebug | PPEMatClassParameterFloat - UpdateParameterValues | exit 3 - zero value");
    }
SetParameterValueDefault() [4/4]
override void PPEMatClassParameterCommandData::SetParameterValueDefault (inout Param p_total) inline private
No active requests for the mat. parameter value change, sets the value to DEFAULT.
Definition at line 185 of file ppematclassparameterint.c.
    {
        p_total = new Param1<int>(PPETemplateDefInt.Cast(m_Defaults).param2);
        m_CurrentValues = p_total;
        //DbgPrnt("PPEDebug | PPEMatClassParameterInt - UpdateParameterValues | exit 3 - zero value");
    }
SetParent()
void PPEMatClassParameterCommandData::SetParent (PPEClassBase parent) inline private
Definition at line 46 of file ppematclassparametercommanddata.c.
    {
        m_Parent = parent;
    }
References m_Parent.
Update() [1/4]
override void PPEMatClassParameterCommandData::Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
Definition at line 29 of file ppematclassparameterbool.c.
    {
        super.Update(timeslice,p_total,setting_defaults,order);
        protected int active_request_count = 0;
        protected PPERequestParamDataBool req_data;
        protected bool setting_value_zero = false;
        protected bool bool_value_temp = false;
        protected bool bool_value_total = m_ValueDefault;
        if (p_total == null)
        {
            p_total = new Param1<bool>(false);
        }
        if (m_RequestMap.Count() > 0)
        {
            m_LayerInfo.Clear();
        }
        else
        {
            //DbgPrnt("m_RequestMap.Count() is zero! Using default values. | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
            SetParameterValueDefault(p_total);
            m_Parent.ParamUpdateRemove(m_ParameterIndex);
            return;
        }
        for ( int i = 0; i < m_RequestMap.Count(); i++ )
        {
            req_data = PPERequestParamDataBool.Cast(m_RequestMap.GetElement(i));
            if (req_data == null)
            {
                Error("PPEMatClassParameterBool | req_data not found! | " + this + " | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
                continue;
            }
            setting_value_zero = req_data.IsSettingDefaultValues();
            if (setting_value_zero && !req_data.GetUpdatingDataValues() && !req_data.IsDataActive())
            {
                //DbgPrnt("Is Default, not updating | idx: " + i + " | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
                continue;
            }
            if (setting_value_zero)
            {
                req_data.m_BoolTarget = false;
                //DbgPrnt("PPEDebug | PPEMatClassParameterBool - UpdateParameterValues | !data.m_DefaultTargetSet | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | req_data.m_BoolTarget: " + req_data.m_BoolTarget);
            }
            else
            {
                active_request_count++;
            }
            //evaluation
            //--------------------------------
            req_data.m_BoolLast = req_data.m_BoolCurrent;
            if (!req_data.GetUpdatingDataValues() && req_data.IsDataActive()) //set to exact value, not updating anymore
            {
                bool_value_temp = req_data.m_BoolCurrent;
                PrepareLayerInfo(req_data.GetPriorityLayer(),bool_value_temp,req_data.GetInteractionMask());
                //DbgPrnt("PPEDebug | PPEMatClassParameterBool - UpdateParameterValues | !req_data.m_UpdatingData | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | not updating, addaing current value into mix: " + bool_value_temp);
                continue;
            }
            bool_value_temp = req_data.m_BoolTarget;
            //DbgPrnt("PPEDebug | PPEMatClassParameterBool - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
            req_data.SetUpdatingDataValues(false);
            if (setting_value_zero)
            {
                req_data.SetDataActive(false);
                //RemovePriorityInfo(req_data.GetPriorityLayer()); //redundant?
            }
            else
            {
                bool_value_temp = req_data.m_BoolTarget;
                PrepareLayerInfo(req_data.GetPriorityLayer(),bool_value_temp,req_data.GetInteractionMask());
            }
            req_data.m_BoolCurrent = bool_value_temp;
        }
        if (active_request_count == 0)
        {
            SetParameterValueDefault(p_total);
        }
        else
        {
            //---------------------------
            //MASK handling and calculation
            bool value;
            int operator;
            bool override_active = false;
            for ( i = 0; i < m_LayerInfo.Count(); i++ )
            {
                if ( override_active )
                    break;
                value = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_VALUE);
                operator = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_OPERATOR);
                switch (operator)
                {
                    case PPOperators.LOWEST:
                        bool_value_total = Math.Min(bool_value_total,value);
                    break;
                    case PPOperators.HIGHEST:
                        bool_value_total = Math.Max(bool_value_total,value);
                    break;
                    case PPOperators.OVERRIDE:
                        bool_value_total = value;
                    break;
                    case PPOperators.SET:
                        bool_value_total = value;
                    break;
                    default:
                        Error("PPEMatClassParameterBool | Invalid operator " + operator + " in mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
                    break;
                }
                if ( operator == PPOperators.OVERRIDE )
                {
                    //DbgPrnt("m_LayerInfo | PPOperators.OVERRIDE at: " + i);
                    override_active = true;
                }
            }
            m_CommandLayersArray.Clear();
            Param1<bool>.Cast(p_total).param1 = bool_value_total;
        }
        //DbgPrnt("PPEDebug | PPEMatClassParameterBool - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | parameter update end, removing from queue");
        m_Parent.ParamUpdateRemove(m_ParameterIndex);
        m_CurrentValues = p_total;
    }
References Error(), m_LayerInfo, m_Parent, m_ValueDefault, Math::Max(), Math::Min(), PPERequestParamDataBool(), PrepareLayerInfo(), and SetParameterValueDefault().
Update() [2/4]
void PPEMatClassParameterCommandData::Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
Definition at line 56 of file ppematclassparametercommanddata.c.
    {
        //insert dependencies to another update round
        if ( m_Dependencies && m_Dependencies.Count() > 0 && order < PPEConstants.DEPENDENCY_ORDER_HIGHEST )
        {
            int key_mat = -1;
            int element_par = -1;
            for (int i = 0; i < m_Dependencies.Count(); i++)
            {
                key_mat = m_Dependencies.GetKey(i);
                for (int j = 0; j < m_Dependencies.GetElement(i).Count(); j++)
                {
                    element_par = m_Dependencies.GetElement(i).Get(j);
                    PPEManagerStatic.GetPPEManager().SetMaterialParamUpdating(key_mat,element_par,order + 1); // TODO - revise, currently only does one more update
                }
            }
        }
    }
References Count, PPEManagerStatic::GetPPEManager(), and m_Dependencies.
Update() [3/4]
override void PPEMatClassParameterCommandData::Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
Definition at line 34 of file ppematclassparameterfloat.c.
    {
        super.Update(timeslice,p_total,setting_defaults,order);
        protected int active_request_count = 0;
        protected PPERequestParamDataFloat req_data;
        protected bool setting_value_zero = false;
        protected float float_value_temp = 0.0;
        protected float float_value_default = 0.0;
        protected float float_value_total = 0.0;
        if (p_total == null)
        {
            p_total = new Param1<float>(0.0);
        }
        if (m_RequestMap.Count() > 0)
        {
            m_LayerInfo.Clear();
        }
        else
        {
            //DbgPrnt("m_RequestMap.Count() is zero! Using default values. | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
            SetParameterValueDefault(p_total);
            m_Parent.ParamUpdateRemove(m_ParameterIndex);
            return;
        }
        for ( int i = 0; i < m_RequestMap.Count(); i++ )
        {
            req_data = PPERequestParamDataFloat.Cast(m_RequestMap.GetElement(i));
            if (req_data == null)
            {
                Error("Debug | PPEMatClassParameterFloat | req_data not found! | " + this + " | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
                continue;
            }
            setting_value_zero = req_data.IsSettingDefaultValues();
            if (setting_value_zero && !req_data.GetUpdatingDataValues() && !req_data.IsDataActive())
            {
                //DbgPrnt("Is Default, not updating | idx: " + i + " | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
                continue;
            }
            if (setting_value_zero)
            {
                req_data.m_FloatTarget = 0;//min;
                //DbgPrnt("PPEDebug | PPEMatClassParameterFloat - UpdateParameterValues | !data.m_DefaultTargetSet | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | req_data.m_FloatTarget: " + req_data.m_FloatTarget);
            }
            else
            {
                active_request_count++;
            }
            //evaluation
            //--------------------------------
            req_data.m_FloatLast = req_data.m_FloatCurrent;
            if (!req_data.GetUpdatingDataValues() && req_data.IsDataActive()) //set to exact value, not updating anymore
            {
                float_value_temp = req_data.m_FloatCurrent;
                PrepareLayerInfo(req_data.GetPriorityLayer(),float_value_temp,req_data.GetInteractionMask());
                //DbgPrnt("PPEDebug | PPEMatClassParameterFloat - UpdateParameterValues | !req_data.m_UpdatingData | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | not updating, addaing current value into mix: " + float_value_temp);
                continue;
            }
            float_value_temp = req_data.m_FloatTarget;
            //DbgPrnt("PPEDebug | PPEMatClassParameterFloat - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
            req_data.SetUpdatingDataValues(false);
            if (setting_value_zero)
            {
                req_data.SetDataActive(false);
                //RemovePriorityInfo(req_data.GetPriorityLayer()); //redundant?
            }
            else
            {
                float_value_temp = req_data.m_FloatTarget;
                PrepareLayerInfo(req_data.GetPriorityLayer(),float_value_temp,req_data.GetInteractionMask());
            }
            req_data.m_FloatCurrent = float_value_temp;
        }
        //---------------------------
        //MASK handling and calculation
        float value;
        int operator;
        bool override_active = false;
        if ( m_ValueMax == 0.0 )
            float_value_total = m_ValueDefault; //?
        else
            float_value_total = m_ValueDefault / m_ValueMax;
        //float_value_total = Math.InverseLerp(m_ValueMin,m_ValueMax,m_ValueDefault);
        float_value_default = float_value_total;
        for ( i = 0; i < m_LayerInfo.Count(); i++ )
        {
            if ( override_active )
                break;
            value = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_VALUE);
            operator = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_OPERATOR);
            switch (operator)
            {
                case PPOperators.LOWEST:
                    float_value_total = Math.Min(float_value_total,value);
                break;
                case PPOperators.HIGHEST:
                    float_value_total = Math.Max(float_value_total,value);
                break;
                case PPOperators.ADD:
                    //float_value_total = float_value_total + value - float_value_default;
                    float_value_total = float_value_total + value;
                break;
                case PPOperators.ADD_RELATIVE:
                    float_value_total = (1 - float_value_total) * value + float_value_total;
                break;
                case PPOperators.SUBSTRACT:
                    //float_value_total = float_value_total - value + float_value_default;
                    float_value_total = float_value_total - value;
                break;
                case PPOperators.SUBSTRACT_RELATIVE:
                    float_value_total = float_value_total - value * float_value_total;
                break;
                case PPOperators.SUBSTRACT_REVERSE:
                    //float_value_total = value - float_value_default - float_value_total;
                    float_value_total = value - float_value_total;
                break;
                case PPOperators.SUBSTRACT_REVERSE_RELATIVE:
                    float_value_total = value * float_value_total - float_value_total;
                break;
                case PPOperators.MULTIPLICATIVE:
                    //float_value_total = Math.Lerp(float_value_default, float_value_total, value);
                    float_value_total = float_value_total * value;
                break;
                case PPOperators.OVERRIDE:
                    float_value_total = value;
                break;
                case PPOperators.SET:
                    float_value_total = value;
                break;
            }
            //DbgPrnt("m_LayerInfo | float_value_total pre-clamp: " + float_value_total + " | i: " + i);
            float_value_total = Math.Clamp(float_value_total,0,1);
            if ( operator == PPOperators.OVERRIDE )
            {
                //DbgPrnt("m_LayerInfo | PPOperators.OVERRIDE at: " + i);
                override_active = true;
            }
            //RemovePriorityInfo(m_CommandLayersArray.Get(i));
        }
        m_CommandLayersArray.Clear();
        //TODO - consider moving this up, if possible
        if (active_request_count == 0)
        {
            SetParameterValueDefault(p_total);
        }
        else
        {
            float res = Math.Lerp(m_ValueMin,m_ValueMax,float_value_total);
            Param1<float>.Cast(p_total).param1 = res; //converts back to absolute values
        }
        //DbgPrnt("PPEDebug | PPEMatClassParameterFloat - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | parameter update end, removing from queue");
        m_Parent.ParamUpdateRemove(m_ParameterIndex);
        m_CurrentValues = p_total;
    }
References Math::Clamp(), Error(), Math::Lerp(), m_LayerInfo, m_Parent, m_ValueDefault, m_ValueDefault, m_ValueMax, m_ValueMax, m_ValueMin, Math::Max(), Math::Min(), PPERequestParamDataFloat(), PrepareLayerInfo(), and SetParameterValueDefault().
Update() [4/4]
override void PPEMatClassParameterCommandData::Update (float timeslice, out Param p_total, out bool setting_defaults, int order) inline private
Definition at line 29 of file ppematclassparameterint.c.
    {
        super.Update(timeslice,p_total,setting_defaults,order);
        protected int active_request_count = 0;
        protected PPERequestParamDataInt req_data;
        protected bool setting_value_zero = false;
        protected bool int_value_temp = false;
        protected bool int_value_total = m_ValueDefault;
        if (p_total == null)
        {
            p_total = new Param1<int>(0);
        }
        if (m_RequestMap.Count() > 0)
        {
            m_LayerInfo.Clear();
        }
        else
        {
            //DbgPrnt("m_RequestMap.Count() is zero! Using default values. | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
            SetParameterValueDefault(p_total);
            m_Parent.ParamUpdateRemove(m_ParameterIndex);
            return;
        }
        for ( int i = 0; i < m_RequestMap.Count(); i++ )
        {
            req_data = PPERequestParamDataInt.Cast(m_RequestMap.GetElement(i));
            if (req_data == null)
            {
                Error("Debug | PPEMatClassParameterInt | req_data not found! | " + this + " | mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
                continue;
            }
            setting_value_zero = req_data.IsSettingDefaultValues();
            if (setting_value_zero && !req_data.GetUpdatingDataValues() && !req_data.IsDataActive())
            {
                //DbgPrnt("Is Default, not updating | idx: " + i + " | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
                continue;
            }
            if (setting_value_zero)
            {
                req_data.m_IntTarget = false;
                //DbgPrnt("PPEDebug | PPEMatClassParameterInt - UpdateParameterValues | !data.m_DefaultTargetSet | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | req_data.m_IntTarget: " + req_data.m_IntTarget);
            }
            else
            {
                active_request_count++;
            }
            //evaluation
            //--------------------------------
            req_data.m_IntLast = req_data.m_IntCurrent;
            if (!req_data.GetUpdatingDataValues() && req_data.IsDataActive()) //set to exact value, not updating anymore
            {
                int_value_temp = req_data.m_IntCurrent;
                PrepareLayerInfo(req_data.GetPriorityLayer(),int_value_temp,req_data.GetInteractionMask());
                //DbgPrnt("PPEDebug | PPEMatClassParameterInt - UpdateParameterValues | !req_data.m_UpdatingData | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | not updating, addaing current value into mix: " + int_value_temp);
                continue;
            }
            int_value_temp = req_data.m_IntTarget;
            //DbgPrnt("PPEDebug | PPEMatClassParameterInt - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX());
            req_data.SetUpdatingDataValues(false);
            if (setting_value_zero)
            {
                req_data.SetDataActive(false);
                //RemovePriorityInfo(req_data.GetPriorityLayer()); //redundant?
            }
            else
            {
                int_value_temp = req_data.m_IntTarget;
                PrepareLayerInfo(req_data.GetPriorityLayer(),int_value_temp,req_data.GetInteractionMask());
            }
            req_data.m_IntCurrent = int_value_temp;
        }
        if (active_request_count == 0)
        {
            SetParameterValueDefault(p_total);
        }
        else
        {
            //---------------------------
            //MASK handling and calculation
            int value;
            int operator;
            bool override_active = false;
            for ( i = 0; i < m_LayerInfo.Count(); i++ )
            {
                if ( override_active )
                    break;
                value = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_VALUE);
                operator = m_LayerInfo.Get(m_CommandLayersArray.Get(i)).Get(LAYER_INFO_OPERATOR);
                switch (operator)
                {
                    case PPOperators.LOWEST:
                        int_value_total = Math.Min(int_value_total,value);
                    break;
                    case PPOperators.HIGHEST:
                        int_value_total = Math.Max(int_value_total,value);
                    break;
                    case PPOperators.OVERRIDE:
                        int_value_total = value;
                    break;
                    case PPOperators.SET:
                        int_value_total = value;
                    break;
                    default:
                        Error("PPEMatClassParameterInt | Invalid operator " + operator + " in mat/par: " + m_MaterialIndex + "/" + m_ParameterIndex);
                    break;
                }
                if ( operator == PPOperators.OVERRIDE )
                {
                    //DbgPrnt("m_LayerInfo | PPOperators.OVERRIDE at: " + i);
                    override_active = true;
                }
            }
            m_CommandLayersArray.Clear();
            Param1<int>.Cast(p_total).param1 = int_value_total;
        }
        //DbgPrnt("PPEDebug | PPEMatClassParameterInt - UpdateParameterValues | mat/par/req: " + m_MaterialIndex + "/" + m_ParameterIndex + "/" + req_data.GetRequesterIDX() + " | parameter update end, removing from queue");
        m_Parent.ParamUpdateRemove(m_ParameterIndex);
        m_CurrentValues = p_total;
    }
References Error(), m_LayerInfo, m_Parent, m_ValueDefault, Math::Max(), Math::Min(), PrepareLayerInfo(), and SetParameterValueDefault().
Member Data Documentation
LAYER_INFO_OPERATOR
const int PPEMatClassParameterCommandData::LAYER_INFO_OPERATOR = 1 private
Definition at line 7 of file ppematclassparametercommanddata.c.
LAYER_INFO_VALUE
const int PPEMatClassParameterCommandData::LAYER_INFO_VALUE = 0 private
Definition at line 6 of file ppematclassparametercommanddata.c.
m_Bool
protected PPETemplateDefBool PPEMatClassParameterCommandData::m_Bool private
Definition at line 5 of file ppematclassparameterbool.c.
m_CommandLayersArray
ref array<int> PPEMatClassParameterCommandData::m_CommandLayersArray private
Definition at line 9 of file ppematclassparametercommanddata.c.
Referenced by AddPriorityInfo(), and PPEMatClassParameterCommandData().
m_CurrentValues
protected ref Param PPEMatClassParameterCommandData::m_CurrentValues private
Definition at line 16 of file ppematclassparametercommanddata.c.
Referenced by GetCurrentValues().
m_Defaults
protected ref Param PPEMatClassParameterCommandData::m_Defaults private
Definition at line 15 of file ppematclassparametercommanddata.c.
Referenced by GetDefaultValues(), and RegisterDefaults().
m_Dependencies
protected ref map<int,ref array<int> > PPEMatClassParameterCommandData::m_Dependencies private
Definition at line 18 of file ppematclassparametercommanddata.c.
Referenced by Update().
m_Float
protected PPETemplateDefFloat PPEMatClassParameterCommandData::m_Float private
Definition at line 5 of file ppematclassparameterfloat.c.
m_Int
protected PPETemplateDefInt PPEMatClassParameterCommandData::m_Int private
Definition at line 5 of file ppematclassparameterint.c.
m_LayerInfo [1/3]
protected ref map<int,ref array<bool,int> > PPEMatClassParameterCommandData::m_LayerInfo private
Definition at line 3 of file ppematclassparameterbool.c.
m_LayerInfo [2/3]
protected ref map<int,ref array<float,int> > PPEMatClassParameterCommandData::m_LayerInfo private
Definition at line 3 of file ppematclassparameterfloat.c.
m_LayerInfo [3/3]
protected ref map<int,ref array<int,int> > PPEMatClassParameterCommandData::m_LayerInfo private
Definition at line 3 of file ppematclassparameterint.c.
m_MaterialIndex
protected int PPEMatClassParameterCommandData::m_MaterialIndex private
Definition at line 11 of file ppematclassparametercommanddata.c.
Referenced by PPEMatClassParameterCommandData(), and SetMaterialIndex().
m_ParameterIndex
protected int PPEMatClassParameterCommandData::m_ParameterIndex private
Definition at line 12 of file ppematclassparametercommanddata.c.
Referenced by PPEMatClassParameterCommandData(), and SetParameterIndex().
m_Parent
protected PPEClassBase PPEMatClassParameterCommandData::m_Parent private
Definition at line 14 of file ppematclassparametercommanddata.c.
Referenced by PPEMatClassParameterCommandData(), and SetParent().
m_RequestMap
protected ref ActiveParameterRequestsMap PPEMatClassParameterCommandData::m_RequestMap private
Definition at line 13 of file ppematclassparametercommanddata.c.
Referenced by InsertRequestData(), and PPEMatClassParameterCommandData().
m_UpdatedCount
protected int PPEMatClassParameterCommandData::m_UpdatedCount private
Definition at line 10 of file ppematclassparametercommanddata.c.
Referenced by PPEMatClassParameterCommandData().
m_ValueDefault [1/3]
protected bool PPEMatClassParameterCommandData::m_ValueDefault private
Definition at line 6 of file ppematclassparameterbool.c.
Referenced by Update().
m_ValueDefault [2/3]
protected float PPEMatClassParameterCommandData::m_ValueDefault private
Definition at line 6 of file ppematclassparameterfloat.c.
m_ValueDefault [3/3]
protected int PPEMatClassParameterCommandData::m_ValueDefault private
Definition at line 6 of file ppematclassparameterint.c.
m_ValueMax
protected float PPEMatClassParameterCommandData::m_ValueMax private
Definition at line 8 of file ppematclassparameterfloat.c.
Referenced by Update().
m_ValueMin
protected float PPEMatClassParameterCommandData::m_ValueMin private
Definition at line 7 of file ppematclassparameterfloat.c.