DayzKode: WeaponParticlesBase Class Reference
WeaponParticlesBase Class Reference
Private Member Functions
bool CheckBoltStateCondition (ItemBase weapon)
bool CheckHealthCondition (int health_label)
vector CheckOrientationOverride (vector local_pos, ItemBase muzzle_owner)
bool CheckOverheatingCondition (float overheating_coef)
int CheckParticleOverride (string ammoType)
bool CheckRainCondition (float rain_coef)
void OnActivate (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void OnDeactivate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void OnParticleCreated (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search, Particle p)
void OnUpdate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void WeaponParticlesBase (ItemBase muzzle_owner, string config_OnFire_entry)
Private Attributes
bool m_IgnoreIfSuppressed
bool m_IlluminateWorld
int m_MuzzleIndex
string m_Name
bool m_OnlyIfBoltIsOpen
string m_OnlyIfBulletIs
string m_OnlyIfWeaponIs
int m_OnlyWithinHealthLabelMax
int m_OnlyWithinHealthLabelMin
float m_OnlyWithinOverheatLimitsMax
float m_OnlyWithinOverheatLimitsMin
float m_OnlyWithinRainLimitsMax
float m_OnlyWithinRainLimitsMin
string m_OverrideDirectionPoint
vector m_OverrideDirectionVector
int m_OverrideParticle
string m_OverridePoint
vector m_PositionOffset
Detailed Description
Definition at line 7 of file weaponparticles.c.
Constructor & Destructor Documentation
WeaponParticlesBase()
void WeaponParticlesBase::WeaponParticlesBase (ItemBase muzzle_owner, string config_OnFire_entry) inline private
Definition at line 33 of file weaponparticles.c.
    {
        m_Name = config_OnFire_entry;
        // ignoreIfSuppressed
        m_IgnoreIfSuppressed = GetGame().ConfigGetFloat(string.Format("%1 ignoreIfSuppressed", m_Name));
        // onlyIfBoltIsOpen
        m_OnlyIfBoltIsOpen = GetGame().ConfigGetFloat(string.Format("%1 onlyIfBoltIsOpen", m_Name));
        // illuminateWorld
        m_IlluminateWorld = GetGame().ConfigGetFloat(string.Format("%1 illuminateWorld", m_Name));
        m_MuzzleIndex = -1;
        if (GetGame().ConfigIsExisting(string.Format("%1 muzzleIndex", m_Name)))
        {
            m_MuzzleIndex = GetGame().ConfigGetInt(string.Format("%1 muzzleIndex", m_Name));
        }
        // onlyIfWeaponIs
        m_OnlyIfWeaponIs = "";
        GetGame().ConfigGetText(string.Format("%1 onlyIfWeaponIs", m_Name), m_OnlyIfWeaponIs);
        // onlyIfBulletIs
        m_OnlyIfBulletIs = "";
        GetGame().ConfigGetText(string.Format("%1 onlyIfBulletIs", m_Name), m_OnlyIfBulletIs);
        // onlyWithinHealthLabel[]
        array<float> health_limit = new array<float>;
        GetGame().ConfigGetFloatArray(string.Format("%1 onlyWithinHealthLabel", m_Name), health_limit);
        if (health_limit.Count() == 2)
        {
            m_OnlyWithinHealthLabelMin = health_limit.Get(0);
            m_OnlyWithinHealthLabelMax = health_limit.Get(1);
        }
        else
        {
            // Disable this filter
            m_OnlyWithinHealthLabelMin = -1;
            m_OnlyWithinHealthLabelMax = 99;
        }
        // onlyWithinOverheatLimits[]
        array<float> overheat_limit = new array<float>;
        GetGame().ConfigGetFloatArray(string.Format("%1 onlyWithinOverheatLimits", m_Name), overheat_limit);
        if (overheat_limit.Count() == 2)
        {
            m_OnlyWithinOverheatLimitsMin = overheat_limit.Get(0);
            m_OnlyWithinOverheatLimitsMax = overheat_limit.Get(1);
        }
        else
        {
            // Disable this filter
            m_OnlyWithinOverheatLimitsMin = -1;
            m_OnlyWithinOverheatLimitsMax = 2;
        }
        // onlyWithinRainLimits[]
        array<float> rain_limit = new array<float>;
        GetGame().ConfigGetFloatArray(string.Format("%1 onlyWithinRainLimits", m_Name), rain_limit);
        if (rain_limit.Count() == 2)
        {
            m_OnlyWithinRainLimitsMin = rain_limit.Get(0);
            m_OnlyWithinRainLimitsMax = rain_limit.Get(1);
        }
        else
        {
            // Disable this filter
            m_OnlyWithinRainLimitsMin = -1;
            m_OnlyWithinRainLimitsMax = 2;
        }
        // overridePoint
        m_OverridePoint = "";
        GetGame().ConfigGetText(string.Format("%1 overridePoint", m_Name), m_OverridePoint);
        if (m_OverridePoint == "")
            m_OverridePoint = "Usti hlavne"; // default memory point name
        // overrideParticle
        string particle_name = "";
        GetGame().ConfigGetText( string.Format("%1 overrideParticle", m_Name), particle_name);
        if (particle_name != "")
        {
            m_OverrideParticle = ParticleList.GetParticleIDByName(particle_name);
        }
        else
        {
            m_OverrideParticle = -1;
            ErrorEx(string.Format("'%1' does not contain a definition for 'overrideparticle'",
                config_OnFire_entry), ErrorExSeverity.INFO);
        }
        // overrideDirectionPoint
        m_OverrideDirectionPoint = "";
        GetGame().ConfigGetText(string.Format("%1 overrideDirectionPoint", m_Name), m_OverrideDirectionPoint);
        if (m_OverrideDirectionPoint == "")
        {
            // overrideDirectionVector
            vector test_ori = GetGame().ConfigGetVector(string.Format("%1 overrideDirectionVector", m_Name));
            if (test_ori != vector.Zero)
            {
                m_OverrideDirectionVector = test_ori;
            }
        }
        // positionOffset[]
        array<float> v = new array<float>;
        GetGame().ConfigGetFloatArray(string.Format("%1 positionOffset", m_Name), v);
        if (v.Count() == 3)
        {
            float v1 = v.Get(0);
            float v2 = v.Get(1);
            float v3 = v.Get(2);
            m_PositionOffset = Vector(v1, v2, v3);
        }
    }
References CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), CGame::ConfigGetInt(), CGame::ConfigGetText(), CGame::ConfigGetVector(), ConfigIsExisting(), ErrorEx, GetGame(), ParticleList::GetParticleIDByName(), m_IgnoreIfSuppressed, m_IlluminateWorld, m_MuzzleIndex, m_Name, m_OnlyIfBoltIsOpen, m_OnlyIfBulletIs, m_OnlyIfWeaponIs, m_OnlyWithinHealthLabelMax, m_OnlyWithinHealthLabelMin, m_OnlyWithinOverheatLimitsMax, m_OnlyWithinOverheatLimitsMin, m_OnlyWithinRainLimitsMax, m_OnlyWithinRainLimitsMin, m_OverrideDirectionPoint, m_OverrideDirectionVector, m_OverrideParticle, m_OverridePoint, m_PositionOffset, Vector(), and vector::Zero.
Member Function Documentation
CheckBoltStateCondition()
bool WeaponParticlesBase::CheckBoltStateCondition (ItemBase weapon) inline private
Definition at line 255 of file weaponparticles.c.
    {
        if ( m_OnlyIfBoltIsOpen )
        {
            Weapon_Base wb = Weapon_Base.Cast( weapon );
            WeaponStateBase current_state =  wb.GetCurrentState();
            return current_state.IsBoltOpen();
        }
        return true;
    }
References WeaponStateBase::IsBoltOpen(), and m_OnlyIfBoltIsOpen.
Referenced by OnActivate().
CheckHealthCondition()
bool WeaponParticlesBase::CheckHealthCondition (int health_label) inline private
Definition at line 268 of file weaponparticles.c.
    {
        return ( (health_label >= m_OnlyWithinHealthLabelMin)  &&  (health_label <= m_OnlyWithinHealthLabelMax) );
    }
References m_OnlyWithinHealthLabelMax, and m_OnlyWithinHealthLabelMin.
Referenced by OnActivate().
CheckOrientationOverride()
vector WeaponParticlesBase::CheckOrientationOverride (vector local_pos, ItemBase muzzle_owner) inline private
Definition at line 327 of file weaponparticles.c.
    {
        vector particle_ori = "0 0 0";
        if (m_OverrideDirectionPoint != "")
        {
            vector target_pos = muzzle_owner.GetSelectionPositionLS(m_OverrideDirectionPoint);
            target_pos = vector.Direction(local_pos, target_pos);
            particle_ori = target_pos.VectorToAngles();
        }
        else
        {
            if (m_OverrideDirectionVector != Vector(0, 0, 0))
            {
                particle_ori = m_OverrideDirectionVector;
            }
            if (muzzle_owner.IsInherited(ItemSuppressor))
            {
                particle_ori = particle_ori + Vector(0,0,270); // This rotation is necesarry due to suppressors being rotated into ground in their p3d files
            }
        }
        return particle_ori;
    }
References vector::Direction(), m_OverrideDirectionPoint, m_OverrideDirectionVector, Vector(), and vector::VectorToAngles().
Referenced by OnActivate().
CheckOverheatingCondition()
bool WeaponParticlesBase::CheckOverheatingCondition (float overheating_coef) inline private
Definition at line 274 of file weaponparticles.c.
    {
        return ( (overheating_coef >= m_OnlyWithinOverheatLimitsMin)  &&  (overheating_coef <= m_OnlyWithinOverheatLimitsMax) );
    }
References m_OnlyWithinOverheatLimitsMax, and m_OnlyWithinOverheatLimitsMin.
Referenced by OnActivate().
CheckParticleOverride()
int WeaponParticlesBase::CheckParticleOverride (string ammoType) inline private
Definition at line 286 of file weaponparticles.c.
    {
        int particle_id = -1;
        string particle_file = "";
        string cfg_path = "CfgAmmo " + ammoType + " muzzleFlashParticle";
        if (GetGame().ConfigGetText( cfg_path, particle_file))
            particle_id = ParticleList.GetParticleIDByName(particle_file);
        // Config is accessed only once because the data is saved into a map for repeated access.
        if ( particle_id > 0 || m_OverrideParticle == -1)
        {
            if (particle_file == "")
            {
                ErrorEx(string.Format("Cannot spawn particle effect because item %1 is missing config parameter muzzleFlashParticle!", ammoType), ErrorExSeverity.INFO);
            }
            else
            {
                particle_id = ParticleList.GetParticleIDByName(particle_file);
                if (particle_id == 0)
                {
                    string devStr;
                    #ifdef DEVELOPER
                    devStr = " Make sure it's registered there and then rebuild Scripts and Graphics PBOs.";
                    #endif
                    ErrorEx(string.Format("Cannot play particle effect with name %1 because no such file is registered in ParticleList.c!%2", particle_file, devStr));
                    m_OverrideParticle = particle_id; // Prevents another appearence of the above error.
                }
            }
        }
        else
        {
            particle_id = m_OverrideParticle;
        }
        return particle_id;
    }
References ErrorEx, GetGame(), ParticleList::GetParticleIDByName(), m_OverrideParticle, and particle_id.
Referenced by OnActivate().
CheckRainCondition()
bool WeaponParticlesBase::CheckRainCondition (float rain_coef) inline private
Definition at line 280 of file weaponparticles.c.
    {
        return ( (rain_coef >= m_OnlyWithinRainLimitsMin)  &&  (rain_coef <= m_OnlyWithinRainLimitsMax) );
    }
References m_OnlyWithinRainLimitsMax, and m_OnlyWithinRainLimitsMin.
Referenced by OnActivate().
OnActivate()
void WeaponParticlesBase::OnActivate (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 165 of file weaponparticles.c.
    {
        if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() )
        {
            // Handle effect's parameters
            if ( PrtTest.m_GunParticlesState ) // Check if particles are enabled by debug
            {
                if ( m_MuzzleIndex == -1 || m_MuzzleIndex == muzzle_index )
                {
                    if ( CheckBoltStateCondition(weapon) ) // onlyIfBoltIsOpen
                    {
                        if ( !suppressor || suppressor.IsRuined() || !(m_IgnoreIfSuppressed) ) // ignoreIfSuppressed
{
                            if ( CheckHealthCondition( muzzle_owner.GetHealthLevel() ) ) // onlyWithinHealthLabel
{
                                if ( CheckOverheatingCondition( muzzle_owner.GetOverheatingCoef() ) ) // onlyWithinOverheatLimits
{
                                    if ( CheckRainCondition( GetGame().GetWeather().GetRain().GetActual() ) ) // onlyWithinRainLimits
{
                                        if ( m_OnlyIfBulletIs == ""  ||  m_OnlyIfBulletIs == ammoType ) // onlyIfBulletIs
{
                                            if ( m_OnlyIfWeaponIs == ""  ||  m_OnlyIfWeaponIs == weapon.GetType() ) // onlyIfWeaponIs
{
                                                // Get particle ID
                                                int particle_id = CheckParticleOverride(ammoType);
                                                if (ParticleList.IsValidId(particle_id))
{
                                                    // Get position of the particle
                                                    vector local_pos = muzzle_owner.GetSelectionPositionLS(m_OverridePoint);
                                                    local_pos += m_PositionOffset;
                                                    // Set orientation of the particle
                                                    vector particle_ori = CheckOrientationOverride(local_pos, muzzle_owner);
                                                    // Create particle
                                                    Particle p = ParticleManager.GetInstance().PlayOnObject( particle_id, muzzle_owner, local_pos, particle_ori );
                                                    OnParticleCreated(weapon, ammoType, muzzle_owner, suppressor, config_to_search, p);
                                                }
                                                else
{
                                                    ErrorEx(string.Format("No valid particle found for: '%1'", m_Name));
                                                }
                                                // Create light
                                                if (m_IlluminateWorld)
{
                                                    vector global_pos = muzzle_owner.ModelToWorld(local_pos + Vector(-0.2, 0, 0));
                                                    int randX = Math.RandomInt( 0,10 );
                                                    if ( randX > 8 )
                                                        ScriptedLightBase.CreateLight( MuzzleFlashLight_2, global_pos );
                                                    else if ( randX > 4 )
                                                        ScriptedLightBase.CreateLight( MuzzleFlashLight_1, global_pos );
                                                    else
                                                    ScriptedLightBase.CreateLight(MuzzleFlashLight, global_pos);
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
References CheckBoltStateCondition(), CheckHealthCondition(), CheckOrientationOverride(), CheckOverheatingCondition(), CheckParticleOverride(), CheckRainCondition(), ErrorEx, GetGame(), ParticleList::IsValidId(), PrtTest::m_GunParticlesState, m_IgnoreIfSuppressed, m_IlluminateWorld, m_MuzzleIndex, m_Name, m_OnlyIfBulletIs, m_OnlyIfWeaponIs, m_OverridePoint, m_PositionOffset, MuzzleFlashLight_1(), OnParticleCreated(), particle_id, ParticleManager(), Math::RandomInt(), and Vector().
OnDeactivate()
void WeaponParticlesBase::OnDeactivate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 238 of file weaponparticles.c.
    {
    }
OnParticleCreated()
void WeaponParticlesBase::OnParticleCreated (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search, Particle p) inline private
Definition at line 233 of file weaponparticles.c.
    {
    }
Referenced by OnActivate().
OnUpdate()
void WeaponParticlesBase::OnUpdate (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 243 of file weaponparticles.c.
    {
    }
Member Data Documentation
m_IgnoreIfSuppressed
bool WeaponParticlesBase::m_IgnoreIfSuppressed private
Definition at line 10 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_IlluminateWorld
bool WeaponParticlesBase::m_IlluminateWorld private
Definition at line 9 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_MuzzleIndex
int WeaponParticlesBase::m_MuzzleIndex private
Definition at line 12 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_Name
string WeaponParticlesBase::m_Name private
Definition at line 27 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyIfBoltIsOpen
bool WeaponParticlesBase::m_OnlyIfBoltIsOpen private
Definition at line 11 of file weaponparticles.c.
Referenced by CheckBoltStateCondition(), and WeaponParticlesBase().
m_OnlyIfBulletIs
string WeaponParticlesBase::m_OnlyIfBulletIs private
Definition at line 21 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyIfWeaponIs
string WeaponParticlesBase::m_OnlyIfWeaponIs private
Definition at line 22 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_OnlyWithinHealthLabelMax
int WeaponParticlesBase::m_OnlyWithinHealthLabelMax private
Definition at line 15 of file weaponparticles.c.
Referenced by CheckHealthCondition(), and WeaponParticlesBase().
m_OnlyWithinHealthLabelMin
int WeaponParticlesBase::m_OnlyWithinHealthLabelMin private
Definition at line 14 of file weaponparticles.c.
Referenced by CheckHealthCondition(), and WeaponParticlesBase().
m_OnlyWithinOverheatLimitsMax
float WeaponParticlesBase::m_OnlyWithinOverheatLimitsMax private
Definition at line 17 of file weaponparticles.c.
Referenced by CheckOverheatingCondition(), and WeaponParticlesBase().
m_OnlyWithinOverheatLimitsMin
float WeaponParticlesBase::m_OnlyWithinOverheatLimitsMin private
Definition at line 16 of file weaponparticles.c.
Referenced by CheckOverheatingCondition(), and WeaponParticlesBase().
m_OnlyWithinRainLimitsMax
float WeaponParticlesBase::m_OnlyWithinRainLimitsMax private
Definition at line 19 of file weaponparticles.c.
Referenced by CheckRainCondition(), and WeaponParticlesBase().
m_OnlyWithinRainLimitsMin
float WeaponParticlesBase::m_OnlyWithinRainLimitsMin private
Definition at line 18 of file weaponparticles.c.
Referenced by CheckRainCondition(), and WeaponParticlesBase().
m_OverrideDirectionPoint
string WeaponParticlesBase::m_OverrideDirectionPoint private
Definition at line 20 of file weaponparticles.c.
Referenced by CheckOrientationOverride(), and WeaponParticlesBase().
m_OverrideDirectionVector
vector WeaponParticlesBase::m_OverrideDirectionVector private
Definition at line 24 of file weaponparticles.c.
Referenced by CheckOrientationOverride(), and WeaponParticlesBase().
m_OverrideParticle
int WeaponParticlesBase::m_OverrideParticle private
Definition at line 13 of file weaponparticles.c.
Referenced by CheckParticleOverride(), and WeaponParticlesBase().
m_OverridePoint
string WeaponParticlesBase::m_OverridePoint private
Definition at line 23 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().
m_PositionOffset
vector WeaponParticlesBase::m_PositionOffset private
Definition at line 25 of file weaponparticles.c.
Referenced by OnActivate(), and WeaponParticlesBase().