DayzKode: BiosUser Class Reference
BiosUser Class Reference
Private Member Functions
proto native BiosClientServices GetClientServices ()
proto native owned string GetName ()
proto native owned string GetUid ()
proto native bool IsOnline ()
Detailed Description
Definition at line 8 of file biosusermanager.c.
Member Function Documentation
GetClientServices()
proto native BiosClientServices BiosUser::GetClientServices () private
Referenced by OnlineServices::GetClientServices().
GetName()
proto native owned string BiosUser::GetName () private
Referenced by DayZIntroScene::GetSelectedUserName(), BiosUserManager::OnGameNameChanged(), UIScriptedMenu::Refresh(), SelectGamepad(), Managed::SetupPlayerName(), and DayZIntroSceneXbox::UpdateSelectedUserName().
GetUid()
proto native owned string BiosUser::GetUid () private
Referenced by ScriptedWidgetEventHandler::IsLocalPlayer(), and UIScriptedMenu::IsLocalPlayer().
IsOnline()
proto native bool BiosUser::IsOnline () private
Referenced by BiosUserManager::OnPartyHost(), and SelectUser().