DayzKode: ActionCheckPulse Class Reference
ActionCheckPulse Class Reference
Private Member Functions
void ActionCheckPulse ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Static Private Member Functions
static string GetPulseMessage (EPulseType pulse_type, int blood_level)
Private Attributes
const int TARGET_IRREGULAR_PULSE_BIT = 1 << 31
Detailed Description
Definition at line 1 of file actioncheckpulse.c.
Constructor & Destructor Documentation
ActionCheckPulse()
void ActionCheckPulse::ActionCheckPulse () inline private
Definition at line 4 of file actioncheckpulse.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#check_pulse_target";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCheckPulse::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 61 of file actioncheckpulse.c.
    {
        PlayerBase ntarget = PlayerBase.Cast(  target.GetObject() );
        if( ntarget && ntarget.IsAlive())
        {
            return true;
        }
        return false;
    }
CreateConditionComponents()
override void ActionCheckPulse::CreateConditionComponents () inline private
Definition at line 11 of file actioncheckpulse.c.
    {
        m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINone;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetPulseMessage()
static string ActionCheckPulse::GetPulseMessage (EPulseType pulse_type, int blood_level) inline static private
Definition at line 17 of file actioncheckpulse.c.
    {
        //builds string table keys:
        //pulse_strong
        //pulse_decent
        //pulse_moderate
        //pulse_weak
        //pulse_faint
        //pulse_strong_irregular
        //pulse_decent_irregular
        //pulse_moderate_irregular
        //pulse_weak_irregular
        //pulse_faint_irregular
        string blood_msg = "strong";
        string pulse_msg = "";
        if(pulse_type == EPulseType.IRREGULAR)
        {
            pulse_msg = "_irregular";
        }
        if( blood_level == EStatLevels.HIGH )
        {
            blood_msg = "decent";
        }
        if( blood_level == EStatLevels.MEDIUM )
        {
            blood_msg = "moderate";
        }
        if( blood_level == EStatLevels.LOW )
        {
            blood_msg = "weak";
        }
        if( blood_level == EStatLevels.CRITICAL )
        {
            blood_msg = "faint";
        }
        //string message = blood_msg + " " + pulse_msg + " pulse";
        string message = "#"+ "pulse_" + blood_msg + pulse_msg;
        return message;
    }
Referenced by ManBase::OnRPC().
OnEndServer()
override void ActionCheckPulse::OnEndServer (ActionData action_data) inline private
Definition at line 97 of file actioncheckpulse.c.
    {
        /*
        PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
        PlayerBase player = action_data.m_Player;
        CachedObjectsParams.PARAM1_INT.param1 = target_player.GetStatLevelBlood();
        GetGame().RPCSingleParam( target_player ,ERPCs.RPC_CHECK_PULSE, CachedObjectsParams.PARAM1_INT, true, target_player.GetIdentity() );
        */
    }
OnExecuteClient()
override void ActionCheckPulse::OnExecuteClient (ActionData action_data) inline private
Definition at line 87 of file actioncheckpulse.c.
    {
        PlayerBase ntarget = PlayerBase.Cast( action_data.m_Target.GetObject() );
        if(ntarget)
        {
            action_data.m_Player.m_CheckPulseLastTarget = ntarget;
        }
    }
References ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void ActionCheckPulse::OnExecuteServer (ActionData action_data) inline private
Definition at line 71 of file actioncheckpulse.c.
    {
        PlayerBase target_player = PlayerBase.Cast(action_data.m_Target.GetObject());
        if (target_player)
        {
            PlayerBase player = action_data.m_Player;
            CachedObjectsParams.PARAM1_INT.param1 = target_player.GetStatLevelBlood();
            bool pulse_type = target_player.GetPulseType();
            if (pulse_type == EPulseType.IRREGULAR)
                CachedObjectsParams.PARAM1_INT.param1 = CachedObjectsParams.PARAM1_INT.param1 | (1 << TARGET_IRREGULAR_PULSE_BIT);
            GetGame().RPCSingleParam( player ,ERPCs.RPC_CHECK_PULSE, CachedObjectsParams.PARAM1_INT, true, player.GetIdentity() );
        }
    }
References GetGame(), ActionData::m_Player, ActionData::m_Target, CachedObjectsParams::PARAM1_INT, CGame::RPCSingleParam(), and TARGET_IRREGULAR_PULSE_BIT.
Member Data Documentation
TARGET_IRREGULAR_PULSE_BIT
const int ActionCheckPulse::TARGET_IRREGULAR_PULSE_BIT = 1 << 31 private
Definition at line 3 of file actioncheckpulse.c.
Referenced by OnExecuteServer(), and ManBase::OnRPC().