DayzKode: GardenBase Class Reference
GardenBase Class Reference
Private Member Functions
override bool CanBePlaced (Man player, vector position)
override void EEDelete (EntityAI parent)
override void EEInit ()
void GardenPlot ()
override int GetGardenSlotsCount ()
override bool IsInventoryVisible ()
override void OnHologramBeingPlaced (Man player)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementStarted (Man player)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
void RefreshSlots ()
Private Attributes
private const int GARDEN_SLOT_COUNT = 9
Object m_ClutterCutter
Detailed Description
Definition at line 1 of file gardenplot.c.
Member Function Documentation
CanBePlaced()
override bool GardenBase::CanBePlaced (Man player, vector position) inline private
Definition at line 112 of file gardenplot.c.
    {
        string surface_type;
        GetGame().SurfaceGetType3D( position[0], position[1], position[2], surface_type );
        return GetGame().IsSurfaceFertile(surface_type);
    }
References GetGame(), CGame::IsSurfaceFertile(), and CGame::SurfaceGetType3D().
EEDelete()
override void GardenBase::EEDelete (EntityAI parent) inline private
Definition at line 30 of file gardenplot.c.
    {
        super.EEDelete(parent);
        if (m_ClutterCutter  &&  GetGame())
        {
            GetGame().ObjectDelete(m_ClutterCutter);
            m_ClutterCutter = NULL;
        }
    }
References GetGame(), m_ClutterCutter, and CGame::ObjectDelete().
EEInit()
override void GardenBase::EEInit () inline private
Definition at line 11 of file gardenplot.c.
    {
        super.EEInit();
    }
GardenPlot()
void GardenBase::GardenPlot () inline private
Definition at line 6 of file gardenplot.c.
    {
        SetBaseFertility(0.5);
    }
GetGardenSlotsCount()
override int GardenBase::GetGardenSlotsCount () inline private
Definition at line 46 of file gardenplot.c.
    {
        return GARDEN_SLOT_COUNT;
    }
References GARDEN_SLOT_COUNT.
Referenced by ItemBase::CheckRainTick(), ItemBase::GardenBase(), ItemBase::GetNearestSlotIDByState(), ItemBase::InitializeSlots(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::SyncSlots(), and ItemBase::UpdateTexturesOnAllSlots().
IsInventoryVisible()
override bool GardenBase::IsInventoryVisible () inline private
Definition at line 41 of file gardenplot.c.
    {
        return true;
    }
OnHologramBeingPlaced()
override void GardenBase::OnHologramBeingPlaced (Man player) inline private
Definition at line 82 of file gardenplot.c.
    {
        RefreshSlots();
    }
References RefreshSlots().
OnPlacementComplete()
override void GardenBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 87 of file gardenplot.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        PlayerBase player_base = PlayerBase.Cast( player );
        //vector pos = player_base.GetLocalProjectionPosition();
        //vector ori = player_base.GetLocalProjectionOrientation();
        if ( GetGame().IsServer() )
        {
            // To properly move the clutter cutter from spawn position, it must be deleted and created again.
            if (m_ClutterCutter)
            {
                GetGame().ObjectDelete(m_ClutterCutter);
                m_ClutterCutter = NULL;
            }
            if (!m_ClutterCutter)
            {
                m_ClutterCutter = GetGame().CreateObjectEx( "ClutterCutter6x6", GetPosition(), ECE_PLACE_ON_SURFACE );
                m_ClutterCutter.SetOrientation( orientation );
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, m_ClutterCutter, and CGame::ObjectDelete().
OnPlacementStarted()
override void GardenBase::OnPlacementStarted (Man player) inline private
Definition at line 77 of file gardenplot.c.
    {
        RefreshSlots();
    }
References RefreshSlots().
OnStoreLoad()
override bool GardenBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 16 of file gardenplot.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        if ( !m_ClutterCutter )
        {
            m_ClutterCutter = GetGame().CreateObjectEx( "ClutterCutter6x6", GetPosition(), ECE_PLACE_ON_SURFACE );
            m_ClutterCutter.SetOrientation( GetOrientation() );
        }
        return true;
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, and m_ClutterCutter.
RefreshSlots()
void GardenBase::RefreshSlots () inline private
Definition at line 51 of file gardenplot.c.
    {
        HideSelection("SeedBase_1");
        HideSelection("SeedBase_2");
        HideSelection("SeedBase_3");
        HideSelection("SeedBase_4");
        HideSelection("SeedBase_5");
        HideSelection("SeedBase_6");
        HideSelection("SeedBase_7");
        HideSelection("SeedBase_8");
        HideSelection("SeedBase_9");
        HideSelection("slotCovered_01");
        HideSelection("slotCovered_02");
        HideSelection("slotCovered_03");
        HideSelection("slotCovered_04");
        HideSelection("slotCovered_05");
        HideSelection("slotCovered_06");
        HideSelection("slotCovered_07");
        HideSelection("slotCovered_08");
        HideSelection("slotCovered_09");
    }
Referenced by OnHologramBeingPlaced(), and OnPlacementStarted().
Member Data Documentation
GARDEN_SLOT_COUNT
private const int GardenBase::GARDEN_SLOT_COUNT = 9 private
Definition at line 4 of file gardenplot.c.
Referenced by GetGardenSlotsCount().
m_ClutterCutter
Object GardenBase::m_ClutterCutter private
Definition at line 3 of file gardenplot.c.