DayzKode: HitDirectionEffectBase Class Reference
HitDirectionEffectBase Class Reference
Private Member Functions
void CalculateArrowPosition (float timeslice=-1.0)
bool DurationCheck ()
override void FinalizePositionCalculation ()
void FinalizePositionCalculation ()
specific handling on individual indicator type
override void FinalizePositionCalculation ()
override void FinalizePositionCalculation ()
override HitDirectionImagesBase GetImageData ()
HitDirectionImagesBase GetImageData ()
override HitDirectionImagesBase GetImageData ()
override HitDirectionImagesBase GetImageData ()
void HitDirectionEffectBase ()
void Init (DayZPlayer player, float hit_direction, float intensity_max)
Called manually after object spawn.
void SetIndicatorPositon (float timeslice=-1.0)
override void SetIndicatorRotation (float timeslice=-1.0)
void SetIndicatorRotation (float timeslice=-1.0)
override void SetIndicatorRotation (float timeslice=-1.0)
override void SetIndicatorRotation (float timeslice=-1.0)
void Update (float timeslice)
void ~HitDirectionEffectBase ()
Static Private Member Functions
static void CheckValues ()
range 0..180, randomized offset of direction to make it less acurate
static GetCurrentType ()
Private Attributes
const float DURATION_COEF_MIN = 0.6
const float INTENSITY_MIN = 0.6
float m_AngleRad
float m_AngleRadPrev
float m_BreakPoint
float m_Duration
float m_HitDirection
Widget m_Image
ref HitDirectionImagesBase m_ImageData
bool m_Initialized
float m_IntensityMax
Widget m_LayoutRoot
DayZPlayer m_Player
float m_PosX
float m_PosXScreenEdge
float m_PosY
float m_PosYScreenEdge
int m_SizeXEnf
int m_SizeYEnf
float m_SmoothVel [1]
float m_TimeActive
Static Private Attributes
static float m_BreakPointBase
static int m_Color
static float m_DistanceAdjust
range 0..1, a point where the fading starts
static float m_DurationMax
static int m_ID
static int m_Mode
static int m_RotationOverride
static float m_Scatter
static bool m_ServerOverrideEnabled
static protected m_Type
Detailed Description
Definition at line 2 of file hitdirectionarrow.c.
Constructor & Destructor Documentation
HitDirectionEffectBase()
void HitDirectionEffectBase::HitDirectionEffectBase () inline private
Definition at line 32 of file hitdirectionbase.c.
    {
        m_Initialized = false;
        m_PosX = 0.0;
        m_PosY = 0.0;
        m_AngleRad = 0.0;
        m_SmoothVel[0] = 0.0;
        m_ImageData = GetImageData();
        m_ImageData.GetCurrentImageData(m_LayoutRoot,m_Image);
    }
References HitDirectionImagesBase::GetCurrentImageData(), GetImageData(), m_AngleRad, m_Image, m_ImageData, m_Initialized, m_LayoutRoot, m_PosX, m_PosY, and m_SmoothVel.
~HitDirectionEffectBase()
void HitDirectionEffectBase::~HitDirectionEffectBase () inline private
Definition at line 75 of file hitdirectionbase.c.
    {
        m_LayoutRoot.Show(false);
        delete m_LayoutRoot;
    }
References m_LayoutRoot.
Member Function Documentation
CalculateArrowPosition()
void HitDirectionEffectBase::CalculateArrowPosition (float timeslice = -1.0) inline private
Definition at line 123 of file hitdirectionbase.c.
    {
        m_HitDirection = Math.NormalizeAngle(m_HitDirection);
        float angle_direction = m_Player.GetOrientation()[0];
        angle_direction = Math.NormalizeAngle(angle_direction);
        float camera_angle = GetGame().GetCurrentCameraDirection().VectorToAngles()[0];
        camera_angle = Math.NormalizeAngle(camera_angle);
        float angle_camera_diff = angle_direction - camera_angle;
        m_AngleRad = m_HitDirection + angle_camera_diff;
        m_AngleRad = Math.NormalizeAngle(m_AngleRad);
        m_AngleRad = m_AngleRad * Math.DEG2RAD;
        m_PosX = 0.0;
        m_PosY = 0.0;
        GetScreenSize(m_SizeXEnf,m_SizeYEnf);
        if ( m_Initialized && timeslice != -1.0 )
        {
            float val = m_AngleRadPrev - m_AngleRad + Math.PI;
            val = Math.ModFloat(val, Math.PI2);
            val -= Math.PI;
            m_AngleRad = m_AngleRadPrev - Math.SmoothCD(0, val, m_SmoothVel, 0.1, 1000, timeslice);
        }
        m_AngleRadPrev = m_AngleRad;
        m_PosXScreenEdge = Math.Clamp(Math.Sin(m_AngleRad)/Math.Sin(Math.PI/4),-1,1) * ( m_SizeXEnf/2 + m_DistanceAdjust * m_SizeXEnf);
        m_PosYScreenEdge = Math.Clamp(-1 * Math.Cos(m_AngleRad)/Math.Cos(Math.PI/4),-1,1) * ( m_SizeYEnf/2 + m_DistanceAdjust * m_SizeYEnf);
        FinalizePositionCalculation();
    }
References Math::Clamp(), Math::Cos(), Math::DEG2RAD, FinalizePositionCalculation(), CGame::GetCurrentCameraDirection(), GetGame(), GetScreenSize(), m_AngleRad, m_AngleRadPrev, m_DistanceAdjust, m_HitDirection, m_Initialized, m_Player, m_PosX, m_PosXScreenEdge, m_PosY, m_PosYScreenEdge, m_SizeXEnf, m_SizeYEnf, m_SmoothVel, Math::ModFloat(), Math::NormalizeAngle(), Math::PI, Math::PI2, Math::Sin(), Math::SmoothCD(), and vector::VectorToAngles().
Referenced by Init(), and Update().
CheckValues()
static void HitDirectionEffectBase::CheckValues () inline static private
range 0..180, randomized offset of direction to make it less acurate
sets override values, or defaults
Definition at line 181 of file hitdirectionbase.c.
    {
        m_ServerOverrideEnabled = CfgGameplayHandler.GetHitIndicationOverrideEnabled();
        if (m_ServerOverrideEnabled)
        {
            m_Mode = CfgGameplayHandler.GetHitIndicationMode();
            m_ID = CfgGameplayHandler.GetHitIndicationTypeID();
            m_Color = CfgGameplayHandler.GetHitIndicationIndicatorColor();
            m_DurationMax = CfgGameplayHandler.GetHitIndicationMaxDuration();
            m_BreakPointBase = CfgGameplayHandler.GetHitIndicationBreakPoint();
            m_Scatter = CfgGameplayHandler.GetHitIndicationScatter();
        }
        else
        {
            m_Mode = HitDirectionModes.STATIC;
            m_ID = HitIndicatorType.SPLASH;
            m_Color = HitDirectionConstants.COLOR_DEFAULT;
            m_DurationMax = HitDirectionConstants.DURATION_BASE;
            m_BreakPointBase = HitDirectionConstants.BREAKPOINT_BASE;
            m_Scatter = HitDirectionConstants.SCATTER;
        }
        m_DistanceAdjust = HitDirectionConstants.DISTANCE_ADJUST;
        m_RotationOverride = HitDirectionConstants.ROTATION_DEFAULT;
    }
References CfgGameplayHandler::GetHitIndicationBreakPoint(), CfgGameplayHandler::GetHitIndicationIndicatorColor(), CfgGameplayHandler::GetHitIndicationMaxDuration(), CfgGameplayHandler::GetHitIndicationMode(), CfgGameplayHandler::GetHitIndicationOverrideEnabled(), CfgGameplayHandler::GetHitIndicationScatter(), CfgGameplayHandler::GetHitIndicationTypeID(), m_BreakPointBase, m_Color, m_DistanceAdjust, m_DurationMax, m_ID, m_Mode, m_RotationOverride, m_Scatter, and m_ServerOverrideEnabled.
Referenced by PlayerBase::UpdateHitDirectionValues().
DurationCheck()
bool HitDirectionEffectBase::DurationCheck () inline private
Definition at line 81 of file hitdirectionbase.c.
    {
        if ( m_TimeActive >= m_Duration )
        {
            return true;
        }
        return false;
    }
References m_Duration, and m_TimeActive.
FinalizePositionCalculation() [1/4]
override void HitDirectionEffectBase::FinalizePositionCalculation () inline private
Definition at line 11 of file hitdirectionarrow.c.
    {
        //blobs move around the edges, the rest on elypsis
        float distance_x = (m_DistanceAdjust * m_SizeXEnf) + (m_SizeXEnf / 2.5);
        float distance_y = (m_DistanceAdjust * m_SizeYEnf) + (m_SizeYEnf / 2.5);
        m_PosX = Math.Sin(m_AngleRad) * distance_x;
        m_PosY = -Math.Cos(m_AngleRad) * distance_y;
    }
References Math::Cos(), m_SizeXEnf, m_SizeYEnf, and Math::Sin().
Referenced by CalculateArrowPosition().
FinalizePositionCalculation() [2/4]
void HitDirectionEffectBase::FinalizePositionCalculation () inline private
specific handling on individual indicator type
Definition at line 158 of file hitdirectionbase.c.
{}
FinalizePositionCalculation() [3/4]
override void HitDirectionEffectBase::FinalizePositionCalculation () inline private
Definition at line 11 of file hitdirectionspike.c.
    {
        //blobs move around the edges, the rest on elypsis
        float distance_x = (m_DistanceAdjust * m_SizeXEnf) + (m_SizeXEnf / 2.5);
        float distance_y = (m_DistanceAdjust * m_SizeYEnf) + (m_SizeYEnf / 2.5);
        m_PosX = Math.Sin(m_AngleRad) * distance_x;
        m_PosY = -Math.Cos(m_AngleRad) * distance_y;
    }
References Math::Cos(), m_SizeXEnf, m_SizeYEnf, and Math::Sin().
FinalizePositionCalculation() [4/4]
override void HitDirectionEffectBase::FinalizePositionCalculation () inline private
Definition at line 11 of file hitdirectionsplash.c.
    {
        //blobs move around the edges, the rest on elypsis
        m_PosX = m_PosXScreenEdge;
        m_PosY = m_PosYScreenEdge;
    }
References m_PosXScreenEdge, and m_PosYScreenEdge.
GetCurrentType()
static HitDirectionEffectBase::GetCurrentType () inline static private
Definition at line 206 of file hitdirectionbase.c.
    {
        switch (m_ID)
        {
            case HitIndicatorType.SPLASH:
                m_Type = HitDirectionEffectSplash;
            break;
            case HitIndicatorType.SPIKE:
                m_Type = HitDirectionEffectSpike;
            break;
            case HitIndicatorType.ARROW:
                m_Type = HitDirectionEffectArrow;
            break;
            default:
                ErrorEx("Unknown HitDirection mode, using HitIndicatorType.SPLASH",ErrorExSeverity.INFO);
                m_Type = HitDirectionEffectSplash;
            break;
        }
        return m_Type;
    }
References ErrorEx, m_ID, and m_Type.
Referenced by Hud::SpawnHitDirEffect().
GetImageData() [1/4]
override HitDirectionImagesBase HitDirectionEffectBase::GetImageData () inline private
Definition at line 4 of file hitdirectionarrow.c.
    {
        typename type = HitDirectionImagesArrow;
        HitDirectionImagesArrow data = HitDirectionImagesArrow.Cast(type.Spawn());
        return data;
    }
Referenced by HitDirectionEffectBase().
GetImageData() [2/4]
HitDirectionImagesBase HitDirectionEffectBase::GetImageData () inline private
Definition at line 73 of file hitdirectionbase.c.
{}
GetImageData() [3/4]
override HitDirectionImagesBase HitDirectionEffectBase::GetImageData () inline private
Definition at line 4 of file hitdirectionspike.c.
    {
        typename type = HitDirectionImagesSpike;
        HitDirectionImagesSpike data = HitDirectionImagesSpike.Cast(type.Spawn());
        return data;
    }
GetImageData() [4/4]
override HitDirectionImagesBase HitDirectionEffectBase::GetImageData () inline private
Definition at line 4 of file hitdirectionsplash.c.
    {
        typename type = HitDirectionImagesSplash;
        HitDirectionImagesSplash data = HitDirectionImagesSplash.Cast(type.Spawn());
        return data;
    }
Init()
void HitDirectionEffectBase::Init (DayZPlayer player, float hit_direction, float intensity_max) inline private
Called manually after object spawn.
Definition at line 45 of file hitdirectionbase.c.
    {
        m_Player = player;
        float duration_coef = Math.Clamp(intensity_max,DURATION_COEF_MIN,1);
        m_IntensityMax = Math.Clamp(intensity_max,INTENSITY_MIN,1);
        m_Duration = m_DurationMax * duration_coef;
        m_BreakPoint = Math.Clamp(m_BreakPointBase * m_Duration,0,m_Duration);
        m_Scatter = Math.Clamp(m_Scatter,0.0,180.0);
        m_HitDirection = hit_direction + (Math.RandomFloatInclusive(0,m_Scatter) * Math.Pow(-1.0,Math.RandomIntInclusive(0,1)));
        Widget w = m_LayoutRoot;
        w = w.GetChildren();
        while (w)
        {
            w.Show(m_Image == w);
            w = w.GetSibling();
        }
        m_Image.SetColor(m_Color);
        m_LayoutRoot.Show(true);
        CalculateArrowPosition();
        SetIndicatorRotation();
        SetIndicatorPositon();
        m_Initialized = true;
    }
References CalculateArrowPosition(), Math::Clamp(), DURATION_COEF_MIN, INTENSITY_MIN, m_BreakPoint, m_BreakPointBase, m_Color, m_Duration, m_DurationMax, m_HitDirection, m_Image, m_Initialized, m_IntensityMax, m_LayoutRoot, m_Player, m_Scatter, Math::Pow(), Math::RandomFloatInclusive(), Math::RandomIntInclusive(), SetIndicatorPositon(), and SetIndicatorRotation().
Referenced by Hud::SpawnHitDirEffect().
SetIndicatorPositon()
void HitDirectionEffectBase::SetIndicatorPositon (float timeslice = -1.0) inline private
Definition at line 161 of file hitdirectionbase.c.
    {
        m_LayoutRoot.SetPos(m_PosX,m_PosY,true);
    }
References m_LayoutRoot, m_PosX, and m_PosY.
Referenced by Init(), and Update().
SetIndicatorRotation() [1/4]
override void HitDirectionEffectBase::SetIndicatorRotation (float timeslice = -1.0) inline private
Definition at line 20 of file hitdirectionarrow.c.
    {
        if (m_RotationOverride == HitDirectionConstants.ROTATION_DEFAULT)
        {
            m_LayoutRoot.SetRotation(0,0,Math.RAD2DEG * m_AngleRad,true);
        }
        else
        {
            m_LayoutRoot.SetRotation(0,0,m_RotationOverride,true);
        }
    }
References Math::RAD2DEG.
Referenced by Init(), and Update().
SetIndicatorRotation() [2/4]
void HitDirectionEffectBase::SetIndicatorRotation (float timeslice = -1.0) inline private
Definition at line 159 of file hitdirectionbase.c.
{}
SetIndicatorRotation() [3/4]
override void HitDirectionEffectBase::SetIndicatorRotation (float timeslice = -1.0) inline private
Definition at line 20 of file hitdirectionspike.c.
    {
        if (m_RotationOverride == HitDirectionConstants.ROTATION_DEFAULT)
        {
            m_LayoutRoot.SetRotation(0,0,Math.RAD2DEG * m_AngleRad,true);
        }
        else
        {
            m_LayoutRoot.SetRotation(0,0,m_RotationOverride,true);
        }
    }
References Math::RAD2DEG.
SetIndicatorRotation() [4/4]
override void HitDirectionEffectBase::SetIndicatorRotation (float timeslice = -1.0) inline private
Definition at line 18 of file hitdirectionsplash.c.
    {
        if ( timeslice == -1.0) //does not rotate on dynamic mode update
        {
            if (m_RotationOverride == HitDirectionConstants.ROTATION_DEFAULT)
            {
                m_LayoutRoot.SetRotation(0,0,Math.RandomIntInclusive(0,359),true);
            }
            else
            {
                m_LayoutRoot.SetRotation(0,0,m_RotationOverride,true);
            }
        }
    }
References Math::RandomIntInclusive().
Update()
void HitDirectionEffectBase::Update (float timeslice) inline private
Definition at line 90 of file hitdirectionbase.c.
    {
        float intensity;
        if ( m_TimeActive <= m_BreakPoint )
        {
            intensity = m_IntensityMax;
        }
        else
        {
            float tmp_value = Math.InverseLerp(m_BreakPoint, m_Duration, m_TimeActive);
            intensity = Math.Lerp(m_IntensityMax,0.0,tmp_value);
        }
        m_TimeActive += timeslice;
        intensity = Math.Clamp(intensity,0,1);
        if ( m_TimeActive >= m_Duration )
        {
            m_LayoutRoot.Show(false);
        }
        else
        {
            m_LayoutRoot.SetAlpha(intensity);
            if ( m_Mode == HitDirectionModes.DYNAMIC )
            {
                CalculateArrowPosition(timeslice);
                SetIndicatorPositon(timeslice);
                SetIndicatorRotation(timeslice);
            }
        }
    }
References CalculateArrowPosition(), Math::Clamp(), Math::InverseLerp(), Math::Lerp(), m_BreakPoint, m_Duration, m_IntensityMax, m_LayoutRoot, m_Mode, m_TimeActive, SetIndicatorPositon(), and SetIndicatorRotation().
Member Data Documentation
DURATION_COEF_MIN
const float HitDirectionEffectBase::DURATION_COEF_MIN = 0.6 private
Definition at line 5 of file hitdirectionbase.c.
Referenced by Init().
INTENSITY_MIN
const float HitDirectionEffectBase::INTENSITY_MIN = 0.6 private
Definition at line 6 of file hitdirectionbase.c.
Referenced by Init().
m_AngleRad
float HitDirectionEffectBase::m_AngleRad private
Definition at line 26 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and HitDirectionEffectBase().
m_AngleRadPrev
float HitDirectionEffectBase::m_AngleRadPrev private
Definition at line 27 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition().
m_BreakPoint
float HitDirectionEffectBase::m_BreakPoint private
Definition at line 10 of file hitdirectionbase.c.
Referenced by Init(), and Update().
m_BreakPointBase
float HitDirectionEffectBase::m_BreakPointBase static private
Definition at line 175 of file hitdirectionbase.c.
Referenced by CheckValues(), and Init().
m_Color
int HitDirectionEffectBase::m_Color static private
Definition at line 172 of file hitdirectionbase.c.
Referenced by CheckValues(), and Init().
m_DistanceAdjust
float HitDirectionEffectBase::m_DistanceAdjust static private
range 0..1, a point where the fading starts
Definition at line 176 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and CheckValues().
m_Duration
float HitDirectionEffectBase::m_Duration private
Definition at line 9 of file hitdirectionbase.c.
Referenced by DurationCheck(), Init(), and Update().
m_DurationMax
float HitDirectionEffectBase::m_DurationMax static private
Definition at line 174 of file hitdirectionbase.c.
Referenced by CheckValues(), and Init().
m_HitDirection
float HitDirectionEffectBase::m_HitDirection private
Definition at line 8 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and Init().
m_ID
int HitDirectionEffectBase::m_ID static private
Definition at line 171 of file hitdirectionbase.c.
Referenced by CheckValues(), and GetCurrentType().
m_Image
Widget HitDirectionEffectBase::m_Image private
Definition at line 15 of file hitdirectionbase.c.
Referenced by HitDirectionEffectBase(), and Init().
m_ImageData
ref HitDirectionImagesBase HitDirectionEffectBase::m_ImageData private
Definition at line 30 of file hitdirectionbase.c.
Referenced by HitDirectionEffectBase().
m_Initialized
bool HitDirectionEffectBase::m_Initialized private
Definition at line 19 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and Init().
m_IntensityMax
float HitDirectionEffectBase::m_IntensityMax private
Definition at line 12 of file hitdirectionbase.c.
Referenced by Init(), and Update().
m_LayoutRoot
Widget HitDirectionEffectBase::m_LayoutRoot private
Definition at line 14 of file hitdirectionbase.c.
Referenced by HitDirectionEffectBase(), Init(), SetIndicatorPositon(), Update(), and ~HitDirectionEffectBase().
m_Mode
int HitDirectionEffectBase::m_Mode static private
Definition at line 170 of file hitdirectionbase.c.
Referenced by CheckValues(), Hud::SpawnHitDirEffect(), and Update().
m_Player
DayZPlayer HitDirectionEffectBase::m_Player private
Definition at line 17 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and Init().
m_PosX
float HitDirectionEffectBase::m_PosX private
Definition at line 22 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and SetIndicatorPositon().
m_PosXScreenEdge
float HitDirectionEffectBase::m_PosXScreenEdge private
Definition at line 24 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_PosY
float HitDirectionEffectBase::m_PosY private
Definition at line 23 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), HitDirectionEffectBase(), and SetIndicatorPositon().
m_PosYScreenEdge
float HitDirectionEffectBase::m_PosYScreenEdge private
Definition at line 25 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_RotationOverride
int HitDirectionEffectBase::m_RotationOverride static private
Definition at line 177 of file hitdirectionbase.c.
Referenced by CheckValues().
m_Scatter
float HitDirectionEffectBase::m_Scatter static private
Definition at line 178 of file hitdirectionbase.c.
Referenced by CheckValues(), and Init().
m_ServerOverrideEnabled
bool HitDirectionEffectBase::m_ServerOverrideEnabled static private
Definition at line 169 of file hitdirectionbase.c.
Referenced by CheckValues().
m_SizeXEnf
int HitDirectionEffectBase::m_SizeXEnf private
Definition at line 20 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_SizeYEnf
int HitDirectionEffectBase::m_SizeYEnf private
Definition at line 21 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and FinalizePositionCalculation().
m_SmoothVel
float HitDirectionEffectBase::m_SmoothVel[1] private
Definition at line 28 of file hitdirectionbase.c.
Referenced by CalculateArrowPosition(), and HitDirectionEffectBase().
m_TimeActive
float HitDirectionEffectBase::m_TimeActive private
Definition at line 11 of file hitdirectionbase.c.
Referenced by DurationCheck(), and Update().
m_Type
protected HitDirectionEffectBase::m_Type static private
Definition at line 173 of file hitdirectionbase.c.
Referenced by GetCurrentType().