DayzKode: SmokeSimulation Class Reference
SmokeSimulation Class Reference
Private Member Functions
void OnFire (Entity flare)
void SmokeSimulation ()
void ~SmokeSimulation ()
Private Attributes
protected Particle m_ParMainSmoke
int particle_id
Detailed Description
Definition at line 1 of file smokesimulation.c.
Constructor & Destructor Documentation
SmokeSimulation()
void SmokeSimulation::SmokeSimulation () inline private
Definition at line 6 of file smokesimulation.c.
    {
        particle_id = ParticleList.GRENADE_M18_PURPLE_LOOP;
    }
References ParticleList::GRENADE_M18_PURPLE_LOOP, and particle_id.
~SmokeSimulation()
void SmokeSimulation::~SmokeSimulation () inline private
Definition at line 17 of file smokesimulation.c.
    {
        if (m_ParMainSmoke)
            m_ParMainSmoke.Stop();
    }
References m_ParMainSmoke, and Particle::Stop().
Member Function Documentation
OnFire()
void SmokeSimulation::OnFire (Entity flare) inline private
Definition at line 11 of file smokesimulation.c.
    {
        m_ParMainSmoke = ParticleManager.GetInstance().PlayOnObject( particle_id, flare);
        m_ParMainSmoke.SetWiggle( 7, 0.3);
    }
References m_ParMainSmoke, particle_id, ParticleManager(), and Particle::SetWiggle().
Member Data Documentation
m_ParMainSmoke
protected Particle SmokeSimulation::m_ParMainSmoke private
Definition at line 3 of file smokesimulation.c.
Referenced by OnFire(), and ~SmokeSimulation().
particle_id
int SmokeSimulation::particle_id private
Definition at line 4 of file smokesimulation.c.
Referenced by OnFire(), SmokeSimulation(), and SmokeSimulation_Green::SmokeSimulation_Green().