DayzKode: Achievements Class Reference
Achievements Class Reference
Private Member Functions
private void Achievements ()
private void ~Achievements ()
Static Private Member Functions
static private void CheckError (EAchievementError error)
static void OnActionDrink ()
static void OnActionEat ()
static void OnActionGutDeer ()
static void OnActionHandcuff ()
static void OnActionIgniteDrill ()
static void OnActionIgniteMatchbox ()
static void OnActionIgniteRoadflare ()
static void OnActionMedsSurvivor ()
static void OnActionShave ()
static void OnCookedSteak ()
static void OnEquippedFullGear ()
static void OnPlayerKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
static proto EAchievementError SendEventAction (EAchievementActionId action_id)
static proto EAchievementError SendEventKill (EAchievementTargetId target_id, EAchievementRankId rank_id, EAchievementRangeId range_id, EAchievementHitId hit_id, float distance)
Detailed Description
Definition at line 51 of file achievementsxbox.c.
Constructor & Destructor Documentation
Achievements()
private void Achievements::Achievements () private
~Achievements()
private void Achievements::~Achievements () private
Member Function Documentation
CheckError()
static private void Achievements::CheckError (EAchievementError error) inline static private
Definition at line 193 of file achievementsxbox.c.
    {
        if ( error != EAchievementError.ERR_OK )
        {
            Print("Achievements: Cannot send achievement event. Error ID: " + error);
        }
    }
References Print().
Referenced by OnActionDrink(), OnActionEat(), OnActionGutDeer(), OnActionHandcuff(), OnActionIgniteDrill(), OnActionIgniteMatchbox(), OnActionIgniteRoadflare(), OnActionMedsSurvivor(), OnActionShave(), OnCookedSteak(), OnEquippedFullGear(), and OnPlayerKilled().
OnActionDrink()
static void Achievements::OnActionDrink () inline static private
Definition at line 70 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_DRINK ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionDrink().
OnActionEat()
static void Achievements::OnActionEat () inline static private
Definition at line 62 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_EAT ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionEat().
OnActionGutDeer()
static void Achievements::OnActionGutDeer () inline static private
Definition at line 126 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_GUT_DEER ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionFinishedGutDeer().
OnActionHandcuff()
static void Achievements::OnActionHandcuff () inline static private
Definition at line 142 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_HANDCUFF_SURVIVOR ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionRestrain().
OnActionIgniteDrill()
static void Achievements::OnActionIgniteDrill () inline static private
Definition at line 110 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_IGNITE_FIRE_HAND_DRILL ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionIgniteMatchbox()
static void Achievements::OnActionIgniteMatchbox () inline static private
Definition at line 94 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_IGNITE_FIRE_MATCHBOX ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionIgniteRoadflare()
static void Achievements::OnActionIgniteRoadflare () inline static private
Definition at line 102 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_IGNITE_FIRE_ROAD_FLARE ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace().
OnActionMedsSurvivor()
static void Achievements::OnActionMedsSurvivor () inline static private
Definition at line 134 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_APPLY_MEDS_ON_SURVIVOR ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionBandageTarget().
OnActionShave()
static void Achievements::OnActionShave () inline static private
Definition at line 118 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_SHAVE ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionFinishedShaveSelf().
OnCookedSteak()
static void Achievements::OnCookedSteak () inline static private
Definition at line 86 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_COOK_STEAK ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnActionCookedSteak().
OnEquippedFullGear()
static void Achievements::OnEquippedFullGear () inline static private
Definition at line 78 of file achievementsxbox.c.
    {
        CheckError( SendEventAction( EAchievementActionId.ACTION_EQUIP_GEAR ) );
    }
References CheckError(), and SendEventAction().
Referenced by AnalyticsManagerClient::OnItemAttachedAtPlayer().
OnPlayerKilled()
static void Achievements::OnPlayerKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline static private
Definition at line 150 of file achievementsxbox.c.
    {
        EAchievementTargetId    target_id       = EAchievementTargetId.TARGET_SURVIVOR;
        EAchievementRankId      target_rank_id  = EAchievementRankId.RANK_SURVIVOR;
        EAchievementRangeId     range_id        = EAchievementRangeId.RANGE_OTHER;
        EAchievementHitId       hit_id          = EAchievementHitId.HIT_OTHER;
        float                   distance        = 0;
        if ( victim.IsZombie() )
        {
            target_id = EAchievementTargetId.TARGET_INFECTED;
            target_rank_id = EAchievementRankId.RANK_INFECTED;
            if ( victim.IsZombieMilitary() )
            {
                target_rank_id = EAchievementRankId.RANK_INFECTED_SOLDIER;
            }
        }
        if ( source )
        {
            if ( source.IsMeleeWeapon() )
            {
                range_id = EAchievementRangeId.RANGE_MELEE;
            }
            else if ( source.IsWeapon() && killer )
            {
                range_id = EAchievementRangeId.RANGE_RANGED;
                distance = vector.Distance( killer.GetPosition(), victim.GetPosition() );
                if ( is_headshot )
                {
                    hit_id = EAchievementHitId.HIT_HEADSHOT;
                }
            }
        }
        CheckError( SendEventKill(target_id, target_rank_id, range_id, hit_id, distance) );
    }
References CheckError(), vector::Distance(), EntityAI::IsMeleeWeapon(), and SendEventKill().
Referenced by AnalyticsManagerClient::Event_OnEntityKilled().
SendEventAction()
static proto EAchievementError Achievements::SendEventAction (EAchievementActionId action_id) static private
Referenced by OnActionDrink(), OnActionEat(), OnActionGutDeer(), OnActionHandcuff(), OnActionIgniteDrill(), OnActionIgniteMatchbox(), OnActionIgniteRoadflare(), OnActionMedsSurvivor(), OnActionShave(), OnCookedSteak(), and OnEquippedFullGear().
SendEventKill()
static proto EAchievementError Achievements::SendEventKill (EAchievementTargetId target_id, EAchievementRankId rank_id, EAchievementRangeId range_id, EAchievementHitId hit_id, float distance) static private
Referenced by OnPlayerKilled().