DayzKode: HitDirectionImagesBase Class Reference
HitDirectionImagesBase Class Reference
Private Member Functions
void GetCurrentImageData (out Widget layout, out Widget image)
Layout should be sufficient for generic manipulation of the hit image.
protected array< string > GetTypeImagePathArray ()
protected array< string > GetTypeLayoutPathArray ()
void HitDirectionImagesBase ()
protected void PerformRegisterImages ()
protected void RandomizeImageIdx ()
protected void RegisterImage (string layout_path, string image_name)
Private Attributes
int m_ImageIndex
Detailed Description
Definition at line 2 of file hitdirectionimagesbase.c.
Constructor & Destructor Documentation
HitDirectionImagesBase()
void HitDirectionImagesBase::HitDirectionImagesBase () inline private
Definition at line 6 of file hitdirectionimagesbase.c.
    {
        if ( (!GetTypeLayoutPathArray() && !GetTypeImagePathArray()) )
        {
            PerformRegisterImages();
        }
        RandomizeImageIdx();
    }
References GetTypeImagePathArray(), GetTypeLayoutPathArray(), PerformRegisterImages(), and RandomizeImageIdx().
Member Function Documentation
GetCurrentImageData()
void HitDirectionImagesBase::GetCurrentImageData (out Widget layout, out Widget image) inline private
Layout should be sufficient for generic manipulation of the hit image.
Definition at line 40 of file hitdirectionimagesbase.c.
    {
        layout = GetGame().GetWorkspace().CreateWidgets(GetTypeLayoutPathArray()[m_ImageIndex]);
        image = layout.FindAnyWidget(GetTypeImagePathArray()[m_ImageIndex]);
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), GetTypeImagePathArray(), GetTypeLayoutPathArray(), CGame::GetWorkspace(), and m_ImageIndex.
Referenced by HitDirectionEffectBase::HitDirectionEffectBase().
GetTypeImagePathArray()
protected array< string > HitDirectionImagesBase::GetTypeImagePathArray () inline private
Definition at line 37 of file hitdirectionimagesbase.c.
{}
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), RandomizeImageIdx(), and RegisterImage().
GetTypeLayoutPathArray()
protected array< string > HitDirectionImagesBase::GetTypeLayoutPathArray () inline private
Definition at line 36 of file hitdirectionimagesbase.c.
{}
Referenced by GetCurrentImageData(), HitDirectionImagesBase(), and RegisterImage().
PerformRegisterImages()
protected void HitDirectionImagesBase::PerformRegisterImages () inline private
Definition at line 16 of file hitdirectionimagesbase.c.
    {
        /*
        RegisterImage("gui/layouts/gameplay/HitDirectionIndication.layout","Single_indicator_Splash_1");
        RegisterImage("gui/layouts/gameplay/HitDirectionIndication.layout","Single_indicator_Splash_2");
        ...
        */
    }
Referenced by HitDirectionImagesBase().
RandomizeImageIdx()
protected void HitDirectionImagesBase::RandomizeImageIdx () inline private
Definition at line 31 of file hitdirectionimagesbase.c.
    {
        m_ImageIndex = Math.RandomIntInclusive(0,GetTypeImagePathArray().Count() - 1);
    }
References Count, GetTypeImagePathArray(), m_ImageIndex, and Math::RandomIntInclusive().
Referenced by HitDirectionImagesBase().
RegisterImage()
protected void HitDirectionImagesBase::RegisterImage (string layout_path, string image_name) inline private
Definition at line 25 of file hitdirectionimagesbase.c.
    {
        GetTypeLayoutPathArray().Insert(layout_path);
        GetTypeImagePathArray().Insert(image_name);
    }
References GetTypeImagePathArray(), and GetTypeLayoutPathArray().
Member Data Documentation
m_ImageIndex
int HitDirectionImagesBase::m_ImageIndex private
Definition at line 4 of file hitdirectionimagesbase.c.
Referenced by GetCurrentImageData(), and RandomizeImageIdx().