DayzKode: DisplayElementBase Class Reference
DisplayElementBase Class Reference
Private Member Functions
void DisplayElementTendency (PlayerBase player)
void ElementStance (PlayerBase player)
void SetLevel (int level)
void SetSeriousnessLevel (DSLevels level)
void SetTendency (int tendency)
override void UpdateHUD ()
override void UpdateHUD ()
override void UpdateHUD ()
Private Attributes
protected int SERIOUSNESS_BIT_MASK = 7
protected int SERIOUSNESS_BIT_OFFSET = 3
protected int TENDENCY_MASK = 7
Detailed Description
Definition at line 1 of file displayelementbadge.c.
Member Function Documentation
DisplayElementTendency()
void DisplayElementBase::DisplayElementTendency (PlayerBase player) inline private
Definition at line 7 of file displayelementtendency.c.
    {
        NUM_OF_BITS = 6;//the overall num of bits this element occupies(can be calculated from masks, better leave it explicit)
    }
ElementStance()
void DisplayElementBase::ElementStance (PlayerBase player) inline private
Definition at line 3 of file elementstance.c.
    {
        NUM_OF_BITS = 2;
        m_Type      =   eDisplayElements.DELM_STANCE;
        m_IsClientOnly = true;
    }
References m_Type.
SetLevel()
void DisplayElementBase::SetLevel (int level) inline private
Definition at line 3 of file displayelementbadge.c.
    {
        SetValue(level);
    }
References SetValue().
SetSeriousnessLevel()
void DisplayElementBase::SetSeriousnessLevel (DSLevels level) inline private
Definition at line 12 of file displayelementtendency.c.
    {
        m_Value = (~(SERIOUSNESS_BIT_MASK << SERIOUSNESS_BIT_OFFSET)) & m_Value;//clear the last value
        m_Value = (level << SERIOUSNESS_BIT_OFFSET)  | m_Value;
    }
References m_Value.
SetTendency()
void DisplayElementBase::SetTendency (int tendency) inline private
Definition at line 37 of file displayelementtendency.c.
    {
        m_Value = (~TENDENCY_MASK) & m_Value;//clear the last value
        m_Value =  tendency | m_Value;//insert the new one
        //PrintString(m_Value.ToString());
    }
References m_Value.
UpdateHUD() [1/3]
override void DisplayElementBase::UpdateHUD () inline private
Definition at line 8 of file displayelementbadge.c.
    {
        super.UpdateHUD();
        m_ModulePlayerStatus.SetBadge(m_Key, m_Value);
    }
References m_Key, m_ModulePlayerStatus, and m_Value.
Referenced by ImmediateUpdate(), and UpdateStatus().
UpdateHUD() [2/3]
override void DisplayElementBase::UpdateHUD () inline private
Definition at line 18 of file displayelementtendency.c.
    {
        super.UpdateHUD();
        int seriousness = m_Value >> SERIOUSNESS_BIT_OFFSET;
        int tendency = TENDENCY_MASK & m_Value;
        //PrintString(tendency.ToString());
        if(tendency > 3)
        {
            tendency = -(tendency - 3);
        }
        /*
        PrintString(this.ToString());
        PrintString("ser:"+ seriousness.ToString());
        PrintString("tnd:"+ tendency.ToString());
        */
        m_ModulePlayerStatus.DisplayTendency(m_Key, tendency, TranslateLevelToStatus(seriousness));
    }
References m_Key, m_ModulePlayerStatus, m_Value, and DisplayElementTendency::TranslateLevelToStatus().
UpdateHUD() [3/3]
override void DisplayElementBase::UpdateHUD () inline private
Definition at line 10 of file elementstance.c.
    {
        super.UpdateHUD();
        m_ModulePlayerStatus.SetStance( m_Value );
    }
References m_ModulePlayerStatus, and m_Value.
Member Data Documentation
SERIOUSNESS_BIT_MASK
protected int DisplayElementBase::SERIOUSNESS_BIT_MASK = 7 private
Definition at line 4 of file displayelementtendency.c.
SERIOUSNESS_BIT_OFFSET
protected int DisplayElementBase::SERIOUSNESS_BIT_OFFSET = 3 private
Definition at line 5 of file displayelementtendency.c.
TENDENCY_MASK
protected int DisplayElementBase::TENDENCY_MASK = 7 private
Definition at line 3 of file displayelementtendency.c.