DayzKode: GameplayEffectsData Class Reference
GameplayEffectsData Class Reference
Manages all bleeding indicators and their updates.
Private Member Functions
void BuildPositioningData ()
void BuildProbabilityData (int severity, float frequency)
int CalculateSeverity (float flow_modifier)
void CleanupBleedingIndicators ()
override bool DataInitialized ()
void GameplayEffectsDataBleeding (array< ref Widget > input, int type, int user_override=-1)
vector GenerateSequenceRandomPosition ()
ImageWidget GetNextDropImage ()
array< float > GetProbabilities (int severity)
override bool HasDefinedHandle ()
override void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
void RegisterBleedingIndicatorInstance (int bit, float flow_modifier)
override void RegisterData (Param p)
void SpawnBleedingIndicator (int source_ID, vector position)
void StopBleedingIndicator (int source_ID, bool instant=false)
override void Update (float timeSlice=0, Param p=null, int handle=-1)
void UpdateBleedingIndicators (float timeSlice)
override void UpdateVisibility (bool state)
Private Attributes
protected Widget m_BloodDropsFrame
protected ref array< int > m_CleanupQueue
protected int m_ImageWidgetCount
protected bool m_Initialized
protected int m_LastDropIdx
protected int m_LastPositionFrameUsed
protected ref array< Widget > m_PositioningFramesArray
protected ref map< int, ref array< float > > m_ProbabilityMap
protected ref map< int, ref BleedingIndicator > m_RegisteredInstances
protected ref array< int > m_RunningIndicators
protected bool m_Visible
Detailed Description
Manages all bleeding indicators and their updates.
Definition at line 3 of file gewidgetsmetadatableeding.c.
Member Function Documentation
BuildPositioningData()
void GameplayEffectsData::BuildPositioningData () inline private
Definition at line 236 of file gewidgetsmetadatableeding.c.
    {
        Widget frameParent = m_LayoutRoot.FindAnyWidget("PoisitioningFrames");
        if (frameParent)
        {
            if (!m_PositioningFramesArray)
            {
                m_PositioningFramesArray = new array<Widget>;
            }
            Widget frame = frameParent.GetChildren();
            while (frame)
            {
                m_PositioningFramesArray.Insert(frame);
                frame = frame.GetSibling();
            }
        }
    }
Referenced by Init().
BuildProbabilityData()
void GameplayEffectsData::BuildProbabilityData (int severity, float frequency) inline private
Definition at line 209 of file gewidgetsmetadatableeding.c.
    {
        if (!m_ProbabilityMap)
        {
            m_ProbabilityMap = new map<int,ref array<float>>;
        }
        array<float> probabilities = new array<float>;
        for (int i = 0; i < BleedingIndicationConstants.SEQUENCE_STEPS; i++)
        {
            probabilities.Insert(Math.Poisson(frequency,i));
        }
        m_ProbabilityMap.Insert(severity,probabilities);
    }
References Math::Poisson(), and BleedingIndicationConstants::SEQUENCE_STEPS.
Referenced by Init().
CalculateSeverity()
int GameplayEffectsData::CalculateSeverity (float flow_modifier) inline private
Definition at line 99 of file gewidgetsmetadatableeding.c.
    {
        switch (flow_modifier)
        {
            case PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW:
                return BleedingIndicationConstants.INDICATOR_SEVERITY_LOW;
            case PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM:
                return BleedingIndicationConstants.INDICATOR_SEVERITY_MEDIUM;
            case PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH:
                return BleedingIndicationConstants.INDICATOR_SEVERITY_HIGH;
        }
        return BleedingIndicationConstants.INDICATOR_SEVERITY_LOW;
    }
References PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_LOW, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, and BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM.
Referenced by RegisterBleedingIndicatorInstance().
CleanupBleedingIndicators()
void GameplayEffectsData::CleanupBleedingIndicators () inline private
Definition at line 145 of file gewidgetsmetadatableeding.c.
    {
        for (int i = 0; i < m_CleanupQueue.Count(); i++)
        {
            m_RunningIndicators.RemoveItem(m_CleanupQueue[i]);
        }
        m_CleanupQueue.Clear();
    }
Referenced by Update().
DataInitialized()
override bool GameplayEffectsData::DataInitialized () inline private
Definition at line 49 of file gewidgetsmetadatableeding.c.
    {
        return m_Initialized;
    }
References m_Initialized.
Referenced by GameplayEffectWidgets_base::UpdateWidgets().
GameplayEffectsDataBleeding()
void GameplayEffectsData::GameplayEffectsDataBleeding (array< ref Widget > input, int type, int user_override = -1) inline private
Definition at line 18 of file gewidgetsmetadatableeding.c.
    {
        m_RegisteredInstances = new map<int,ref BleedingIndicator>;
        m_CleanupQueue = new array<int>;
        m_RunningIndicators = new array<int>;
        m_Initialized = false;
    }
References m_Initialized.
GenerateSequenceRandomPosition()
vector GameplayEffectsData::GenerateSequenceRandomPosition () inline private
Definition at line 255 of file gewidgetsmetadatableeding.c.
    {
        if (m_PositioningFramesArray)
        {
            int arrayCount = m_PositioningFramesArray.Count();
            int index = Math.RandomInt(0,arrayCount);
            if (index == m_LastPositionFrameUsed)
            {
                index++;
                if (index >= arrayCount)
                {
                    index = 0;
                }
            }
            Widget frame = m_PositioningFramesArray[index];
            m_LastPositionFrameUsed = index;
            if (frame)
            {
                int screenX,screenY;
                float x,y,x_size,y_size;
                frame.GetScreenPos(x,y);
                frame.GetScreenSize(x_size,y_size);
                x = Math.RandomFloatInclusive(x,x+x_size);
                y = Math.RandomFloatInclusive(y,y+y_size);
                return Vector(x,y,0);
            }
        }
        return vector.Zero;
    }
References Math::RandomFloatInclusive(), Math::RandomInt(), Vector(), x, y, and vector::Zero.
Referenced by SpawnBleedingIndicator().
GetNextDropImage()
ImageWidget GameplayEffectsData::GetNextDropImage () inline private
Definition at line 115 of file gewidgetsmetadatableeding.c.
    {
        m_LastDropIdx++;
        if (m_LastDropIdx > (m_ImageWidgetCount - 1))
        {
            m_LastDropIdx = 0;
        }
        return ImageWidget.Cast(m_WidgetArray[m_LastDropIdx]);
    }
GetProbabilities()
array< float > GameplayEffectsData::GetProbabilities (int severity) inline private
Definition at line 226 of file gewidgetsmetadatableeding.c.
    {
        array<float> ret = m_ProbabilityMap.Get(severity);
        if (!ret)
        {
            ErrorEx("No defined data for the selected severity!");
        }
        return ret;
    }
References ErrorEx.
HasDefinedHandle()
override bool GameplayEffectsData::HasDefinedHandle () inline private
Definition at line 44 of file gewidgetsmetadatableeding.c.
    {
        return true;
    }
Referenced by GameplayEffectWidgets_base::UpdateVisibility(), and GameplayEffectWidgets_base::UpdateWidgets().
Init()
override void GameplayEffectsData::Init (array< ref Widget > input, int type, Widget layout_root, int user_override = -1) inline private
Definition at line 26 of file gewidgetsmetadatableeding.c.
    {
        super.Init(input, type, layout_root, user_override);
        m_WidgetArray.ShuffleArray(); //shuffles order of the widgets on every init
        m_ImageWidgetCount = m_WidgetArray.Count();
        m_BloodDropsFrame = m_LayoutRoot.FindAnyWidgetById(EffectWidgetsTypes.BLEEDING_LAYER);
        m_Visible = g_Game.GetProfileOption(EDayZProfilesOptions.BLEEDINGINDICATION);
        m_BloodDropsFrame.Show(m_Visible);
        m_LastDropIdx = -1;
        m_LastPositionFrameUsed = -1;
        BuildProbabilityData(BleedingIndicationConstants.INDICATOR_SEVERITY_LOW,BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_LOW);
        BuildProbabilityData(BleedingIndicationConstants.INDICATOR_SEVERITY_MEDIUM,BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_MEDIUM);
        BuildProbabilityData(BleedingIndicationConstants.INDICATOR_SEVERITY_HIGH,BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_HIGH);
        BuildPositioningData();
    }
References BuildPositioningData(), BuildProbabilityData(), g_Game, BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM, m_Visible, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_LOW, and BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_MEDIUM.
Referenced by GameplayEffectWidgets_base::CreateHandledClass().
RegisterBleedingIndicatorInstance()
void GameplayEffectsData::RegisterBleedingIndicatorInstance (int bit, float flow_modifier) inline private
Definition at line 80 of file gewidgetsmetadatableeding.c.
    {
        int severity = CalculateSeverity(flow_modifier);
        BleedingIndicator indicator = new BleedingIndicator(bit,severity,this); //source_ID == bit for the purpose of pairing
        m_RegisteredInstances.Set(bit,indicator);
    }
References CalculateSeverity().
Referenced by RegisterData().
RegisterData()
override void GameplayEffectsData::RegisterData (Param p) inline private
Definition at line 54 of file gewidgetsmetadatableeding.c.
    {
        if (m_Initialized)
        {
            #ifdef DEVELOPER
                ErrorEx("" + this + " is already initialized, further registration not possible!");
            #else
                Debug.Log("ERROR: " + this + " is already initialized, further registration not possible!");
            #endif
            return;
        }
        //<finish registration,bit,flow_modifier>
        Param3<bool,int,float> par;
        if (Class.CastTo(par,p))
        {
            if (par.param1 == true) //finish registration
            {
                m_Initialized = true;
                return;
            }
            RegisterBleedingIndicatorInstance(par.param2,par.param3);
        }
    }
References Class::CastTo(), ErrorEx, Debug::Log(), m_Initialized, and RegisterBleedingIndicatorInstance().
SpawnBleedingIndicator()
void GameplayEffectsData::SpawnBleedingIndicator (int source_ID, vector position) inline private
Definition at line 87 of file gewidgetsmetadatableeding.c.
    {
        if (m_RunningIndicators.Find(source_ID) != -1)
        {
            return;
        }
        BleedingIndicator indicator = m_RegisteredInstances.Get(source_ID);
        //indicator.InitIndicator(position); //would be nice if we could pair the indicator position to the hit position that caused the bleeding, wouldn't it
        indicator.InitIndicator(GenerateSequenceRandomPosition());
        m_RunningIndicators.Insert(source_ID);
    }
References GenerateSequenceRandomPosition().
Referenced by Update().
StopBleedingIndicator()
void GameplayEffectsData::StopBleedingIndicator (int source_ID, bool instant = false) inline private
Definition at line 126 of file gewidgetsmetadatableeding.c.
    {
        m_RegisteredInstances.Get(source_ID).StopIndicator(instant);
    }
Referenced by Update().
Update()
override void GameplayEffectsData::Update (float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 154 of file gewidgetsmetadatableeding.c.
    {
        //starts or ends a bleeding indicator
        if (p)
        {
            //start/stop of the indicator
            //<state,bit,position,immediate>
            Param4<bool,int,vector,bool> par;
            //hide/show of bleeding effect visuals
            //<state>
            Param1<bool> parShow;
            if (Class.CastTo(par,p))
            {
                bool state = par.param1;
                if (state) //add indicator
                {
                    SpawnBleedingIndicator(par.param2,par.param3);
                }
                else //stop indicator
                {
                    StopBleedingIndicator(par.param2,par.param4);
                }
            }
            else if (Class.CastTo(parShow,p) && m_Visible != parShow.param1)
            {
                m_Visible = parShow.param1;
                m_BloodDropsFrame.Show(m_Visible);
            }
        }
        //updates bleeding indicators
        UpdateBleedingIndicators(timeSlice);
        CleanupBleedingIndicators();
        if (m_RunningIndicators.Count() <= 0)
        {
            GetGame().GetMission().GetEffectWidgets().RemoveActiveEffects({EffectWidgetsTypes.BLEEDING_LAYER});
            m_WidgetArray.ShuffleArray();
        }
    }
References Class::CastTo(), CleanupBleedingIndicators(), Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), m_Visible, GameplayEffectWidgets_base::RemoveActiveEffects(), SpawnBleedingIndicator(), StopBleedingIndicator(), and UpdateBleedingIndicators().
Referenced by GameplayEffectWidgets_base::UpdateWidgets().
UpdateBleedingIndicators()
void GameplayEffectsData::UpdateBleedingIndicators (float timeSlice) inline private
Definition at line 131 of file gewidgetsmetadatableeding.c.
    {
        BleedingIndicator bib;
        for (int i = 0; i < m_RunningIndicators.Count(); i++)
        {
            bib = m_RegisteredInstances.Get(m_RunningIndicators[i]);
            bib.Update(timeSlice);
            if ( bib.GetEndNow() )
            {
                m_CleanupQueue.Insert(m_RunningIndicators[i]);
            }
        }
    }
Referenced by Update().
UpdateVisibility()
override void GameplayEffectsData::UpdateVisibility (bool state) inline private
Definition at line 197 of file gewidgetsmetadatableeding.c.
    {
        m_Visible = g_Game.GetProfileOption(EDayZProfilesOptions.BLEEDINGINDICATION); //ugh
        //manage layout visibility
        Widget w = m_BloodDropsFrame;
        while (w && w != m_LayoutRoot && m_Visible == state && w.IsVisibleHierarchy() != state)
        {
            w.Show(state);
            w = w.GetParent();
        }
    }
References g_Game, m_BloodDropsFrame, and m_Visible.
Referenced by GameplayEffectWidgets_base::UpdateVisibility().
Member Data Documentation
m_BloodDropsFrame
protected Widget GameplayEffectsData::m_BloodDropsFrame private
Definition at line 14 of file gewidgetsmetadatableeding.c.
Referenced by UpdateVisibility().
m_CleanupQueue
protected ref array<int> GameplayEffectsData::m_CleanupQueue private
Definition at line 8 of file gewidgetsmetadatableeding.c.
m_ImageWidgetCount
protected int GameplayEffectsData::m_ImageWidgetCount private
Definition at line 11 of file gewidgetsmetadatableeding.c.
m_Initialized
protected bool GameplayEffectsData::m_Initialized private
Definition at line 5 of file gewidgetsmetadatableeding.c.
Referenced by DataInitialized().
m_LastDropIdx
protected int GameplayEffectsData::m_LastDropIdx private
Definition at line 10 of file gewidgetsmetadatableeding.c.
m_LastPositionFrameUsed
protected int GameplayEffectsData::m_LastPositionFrameUsed private
Definition at line 16 of file gewidgetsmetadatableeding.c.
m_PositioningFramesArray
protected ref array<Widget> GameplayEffectsData::m_PositioningFramesArray private
Definition at line 13 of file gewidgetsmetadatableeding.c.
m_ProbabilityMap
protected ref map<int,ref array<float> > GameplayEffectsData::m_ProbabilityMap private
Definition at line 12 of file gewidgetsmetadatableeding.c.
m_RegisteredInstances
protected ref map<int,ref BleedingIndicator> GameplayEffectsData::m_RegisteredInstances private
Definition at line 7 of file gewidgetsmetadatableeding.c.
m_RunningIndicators
protected ref array<int> GameplayEffectsData::m_RunningIndicators private
Definition at line 9 of file gewidgetsmetadatableeding.c.
m_Visible
protected bool GameplayEffectsData::m_Visible private
Definition at line 6 of file gewidgetsmetadatableeding.c.