DayzKode: SyncPlayerList Class Reference
SyncPlayerList Class Reference
Private Member Functions
void CreatePlayerList ()
Static Private Member Functions
static SyncPlayerList Compare (SyncPlayerList a, SyncPlayerList b)
Private Attributes
ref array< ref SyncPlayer > m_PlayerList
Detailed Description
Definition at line 1 of file syncplayerlist.c.
Member Function Documentation
Compare()
static SyncPlayerList SyncPlayerList::Compare (SyncPlayerList a, SyncPlayerList b) inline static private
Definition at line 34 of file syncplayerlist.c.
    {
        SyncPlayerList new_list = new SyncPlayerList;
        new_list.m_PlayerList = new array<ref SyncPlayer>;
        if (!a && b && b.m_PlayerList)
        {
            foreach (SyncPlayer player3 : b.m_PlayerList)
            {
                new_list.m_PlayerList.Insert(player3);
            }
        }
        else if (a && a.m_PlayerList && !b)
        {
            foreach (SyncPlayer player4 : a.m_PlayerList)
            {
                new_list.m_PlayerList.Insert(player4);
            }
        }
        else if (a && a.m_PlayerList && b && b.m_PlayerList)
        {
            array<ref SyncPlayer> array_a = a.m_PlayerList;
            array<ref SyncPlayer> array_b = b.m_PlayerList;
            foreach (SyncPlayer player : array_b)
            {
                bool found = false;
                foreach (SyncPlayer player2 : array_a)
                {
                    if (player.m_UID == player2.m_UID)
                    {
                        found = true;
                        break;
                    }
                }
                if (!found)
                {
                    new_list.m_PlayerList.Insert(player);
                }
            }
        }
        return new_list;
    }
References m_PlayerList.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
CreatePlayerList()
void SyncPlayerList::CreatePlayerList () inline private
Definition at line 5 of file syncplayerlist.c.
    {
        if (GetGame().IsServer())
        {
            m_PlayerList = new array<ref SyncPlayer>;
            array<Man> players = new array<Man>;
            GetGame().GetWorld().GetPlayerList(players);
            for (int i = 0; i < players.Count(); ++i)
            {
                Man player = players[i];
                PlayerIdentity p_identity = player.GetIdentity();
                if (p_identity)
                {
                    SyncPlayer sync_player = new SyncPlayer;
                    sync_player.m_UID = p_identity.GetPlainId();
                    sync_player.m_PlayerName = p_identity.GetName();
                    m_PlayerList.Insert(sync_player);
                }
                else
                {
                    DebugPrint.LogErrorAndTrace("No Identity in Server Player List");
                }
            }
        }
    }
References GetGame(), PlayerIdentityBase::GetName(), PlayerIdentityBase::GetPlainId(), World::GetPlayerList(), CGame::GetWorld(), DebugPrint::LogErrorAndTrace(), m_PlayerList, SyncPlayer::m_PlayerName, and SyncPlayer::m_UID.
Referenced by SyncEvents::SendPlayerList().
Member Data Documentation
m_PlayerList
ref array<ref SyncPlayer> SyncPlayerList::m_PlayerList private
Definition at line 3 of file syncplayerlist.c.
Referenced by Compare(), UIScriptedMenu::CreateFakePlayerList(), CreatePlayerList(), ClientData::GetSimplePlayerList(), OnlineServices::OnFriendsAsync(), ScriptedWidgetEventHandler::Reload(), ClientData::ResetClientData(), and ClientData::SyncEvent_OnRecievedPlayerList().