DayzKode: DayZInfected Class Reference
DayZInfected Class Reference
Private Member Functions
override bool CanBeBackstabbed ()
override bool CanBeSkinned ()
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
bool ChaseAttackLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt)
void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
float ComputeHitDirectionAngle (EntityAI pSource)
float ComputeHitDirectionAngleEx (EntityAI pSource, int invertHitDir=0)
protected void DebugSound (string s)
sound debug messages
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override protected void EOnContact (IEntity other, Contact extra)
override void EOnInit (IEntity other, int extra)
bool EvaluateCrawlTransitionAnimation (EntityAI pSource, string pComponent, string pAmmoType, out int pAnimType)
bool EvaluateDamageHitAnimation (EntityAI pSource, string pComponent, string pAmmoType, out bool pHeavyHit, out int pAnimType, out float pAnimHitDir)
selects animation type and direction based on damage system data
bool EvaluateDeathAnimation (EntityAI pSource, string pComponent, string pAmmoType, out int pAnimType, out float pAnimHitDir)
bool EvaluateDeathAnimationEx (EntityAI pSource, ZombieHitData data, out int pAnimType, out float pAnimHitDir)
bool FightAttackLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt)
bool FightLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt)
int GetAttackPitch (EntityAI target)
override AnimBootsType GetBootsType ()
override vector GetCenter ()
override string GetDefaultHitComponent ()
returns default hit component (fallback)
override vector GetDefaultHitPosition ()
override string GetHitComponentForAI ()
returns hit component for attacking AI
int GetMindStateSynced ()
int GetOrientationSynced ()
returns rounded zombie yaw for sync purposes
override array< string > GetSuitableFinisherHitComponents ()
returns suitable hit components for finisher attacks; DEPRECATED
int GetVaultType (float height)
bool HandleCrawlTransition (int pCurrentCommandID)
bool HandleDamageHit (int pCurrentCommandID)
bool HandleDeath (int pCurrentCommandID)
bool HandleMindStateChange (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt)
void HandleMove (int pCurrentCommandID)
void HandleOrientation (float pDt, int pCurrentCommandID)
protected void HandleSoundEvents ()
bool HandleVault (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt)
void Init ()
override bool IsBeingBackstabbed ()
returns true if backstab is in progress; used for suspending of AI targeting and other useful things besides
bool IsCrawling ()
returns true if crawling; 'DayZInfectedCommandCrawl' is only for the transition, after that it remains 'DayZInfectedCommandMove' (unreliable)
override bool IsDanger ()
override bool IsHealthVisible ()
bool IsMale ()
override bool IsRefresherSignalingViable ()
override bool IsZombie ()
override bool IsZombieMilitary ()
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void OnRecoverFromDeath ()
override void OnSoundVoiceEvent (int event_id, string event_user_string)
override void OnVariablesSynchronized ()
synced variable(s) handler
protected void ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event, out AbstractWave aw)
AbstractWave ProcessVoiceFX (string pSoundSetName)
override void SetBeingBackstabbed (int backstabType)
protected vector SetDefaultHitPosition (string pSelection)
void ZombieBase ()
Private Attributes
int m_ActiveVaultType = -1
DayZInfectedAttackType m_ActualAttackType = NULL
EntityAI m_ActualTarget = NULL
protected ref array< Object > m_AllTargetObjects
float m_AttackCooldownTime = 0
int m_CrawlTransition = -1
float m_DamageHitDirection = 0
bool m_DamageHitHeavy = false
bool m_DamageHitToProcess = false
int m_DamageHitType = 0
int m_DeathType = 0
protected vector m_DefaultHitPosition
protected bool m_FinisherInProgress = false
protected ref InfectedSoundEventHandler m_InfectedSoundEventHandler
protected bool m_IsCrawling
protected bool m_KnuckleLand = false
protected float m_KnuckleOutTimer = 0
protected int m_LastMindState = -1
protected float m_LastMovementSpeed = -1
protected AbstractWave m_LastSoundVoiceAW
protected int m_MindState = -1
protected float m_MovementSpeed = -1
protected int m_OrientationLocal = -1
protected int m_OrientationSynced = -1
protected float m_OrientationTimer
float m_ShockDamage = 0
protected int m_StanceVariation = 0
server / singleplayer properties
protected ref array< typename > m_TargetableObjects
const float ORIENTATION_SYNC_THRESHOLD = 30
const float SHOCK_TO_STUN_MULTIPLIER = 2.82
const float TARGET_CONE_ANGLE_CHASE = 20
const float TARGET_CONE_ANGLE_FIGHT = 30
Detailed Description
Definition at line 1 of file zombiebase.c.
Member Function Documentation
CanBeBackstabbed()
override bool DayZInfected::CanBeBackstabbed () inline private
Definition at line 123 of file zombiebase.c.
    {
        return true;
    }
CanBeSkinned()
override bool DayZInfected::CanBeSkinned () inline private
Definition at line 134 of file zombiebase.c.
    {
        return false;
    }
CanReceiveAttachment()
override bool DayZInfected::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 1045 of file zombiebase.c.
    {
        if ( !IsAlive() )
        {
            return false;
        }
        return super.CanReceiveAttachment(attachment, slotId);
    }
References IsAlive().
ChaseAttackLogic()
bool DayZInfected::ChaseAttackLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt) inline private
do not attack players in vehicle - hotfix
target is outside the targeting cone; skip attack
Definition at line 695 of file zombiebase.c.
    {
        // always update target - it can be destroyed
        m_ActualTarget = pInputController.GetTargetEntity();
        PlayerBase pb = PlayerBase.Cast(m_ActualTarget);
        if ( pb && pb.GetCommand_Vehicle() )
        {
            return false;
        }
        if ( m_ActualTarget == NULL )
            return false;
        vector targetPos = m_ActualTarget.GetPosition();
        if ( !CanAttackToPosition(targetPos) )
            return false;
        float targetDist = vector.Distance(targetPos, this.GetPosition());
        int pitch = GetAttackPitch(m_ActualTarget);
        m_ActualAttackType = GetDayZInfectedType().ChooseAttack(DayZInfectedAttackGroupType.CHASE, targetDist, pitch);
        if ( m_ActualAttackType )
        {
            Object target = DayZPlayerUtils.GetMeleeTarget(this.GetPosition(), this.GetDirection(), TARGET_CONE_ANGLE_CHASE, m_ActualAttackType.m_Distance, -1.0, 2.0, this, m_TargetableObjects, m_AllTargetObjects);
            if (m_ActualTarget != target)
            {
                m_AllTargetObjects.Clear();
                return false;
            }
            StartCommand_Attack(m_ActualTarget, m_ActualAttackType.m_Type, m_ActualAttackType.m_Subtype);
            m_AttackCooldownTime = m_ActualAttackType.m_Cooldown;
            return true;
        }
        return false;
    }
References vector::Distance(), GetDirection(), DayZPlayerUtils::GetMeleeTarget(), GetPosition, DayZInfectedInputController::GetTargetEntity(), m_AllTargetObjects, DayZInfectedAttackType::m_Cooldown, DayZInfectedAttackType::m_Distance, DayZInfectedAttackType::m_Subtype, m_TargetableObjects, and DayZInfectedAttackType::m_Type.
CommandHandler()
void DayZInfected::CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
CommandHandler
for mods
handle death
movement handler (just for sync now)
handle finished commands
default behaviour after finish is to start move
for mods
crawl transition
damage hits
Definition at line 193 of file zombiebase.c.
    {
        if ( ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished) )
        {
            return;
        }
        if ( pCurrentCommandID != DayZInfectedConstants.COMMANDID_DEATH )
        {
            if ( HandleDeath(pCurrentCommandID) )
                return;
        }
        else if (!pCurrentCommandFinished)
        {
            return;
        }
        HandleMove(pCurrentCommandID);
        HandleOrientation(pDt,pCurrentCommandID);
        if (pCurrentCommandFinished)
        {
            DayZInfectedCommandMove moveCommand = StartCommand_Move();
            moveCommand.SetStanceVariation(m_StanceVariation);
            return;
        }
        if ( ModCommandHandlerInside(pDt, pCurrentCommandID, pCurrentCommandFinished) )
        {
            return;
        }
        if ( HandleCrawlTransition(pCurrentCommandID) )
        {
            return;
        }
        if ( HandleDamageHit(pCurrentCommandID) )
        {
            return;
        }
        DayZInfectedInputController inputController = GetInputController();
        if ( inputController )
        {
            if ( HandleVault(pCurrentCommandID, inputController, pDt) )
            {
                return;
            }
            if ( HandleMindStateChange(pCurrentCommandID, inputController, pDt) )
            {
                return;
            }
            if ( FightLogic(pCurrentCommandID, inputController, pDt) )
            {
                return;
            }
        }
        if ( ModCommandHandlerAfter(pDt, pCurrentCommandID, pCurrentCommandFinished) )
        {
            return;
        }
    }
References GetInputController(), HandleDamageHit(), HandleDeath(), ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), and StartCommand_Move().
CommandHandlerDebug()
void DayZInfected::CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
CommandHandlerDebug
Definition at line 297 of file zombiebase.c.
    {
        if ( GetPluginManager() )
        {
            PluginDayZInfectedDebug infectedDebug = PluginDayZInfectedDebug.Cast(GetPluginManager().GetPluginByType(PluginDayZInfectedDebug));
            if ( infectedDebug )
                infectedDebug.CommandHandler(this);
        }
    }
References GetPluginManager().
ComputeHitDirectionAngle()
float DayZInfected::ComputeHitDirectionAngle (EntityAI pSource) inline private
Definition at line 927 of file zombiebase.c.
    {
        vector targetDirection = GetDirection();
        vector toSourceDirection = (pSource.GetPosition() - GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        float dirAngle = Math.Acos(cosFi) * Math.RAD2DEG;
        if ( cross[1] < 0 )
            dirAngle = -dirAngle;
        return dirAngle;
    }
References Math::Acos(), vector::Dot(), GetDirection(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
ComputeHitDirectionAngleEx()
float DayZInfected::ComputeHitDirectionAngleEx (EntityAI pSource, int invertHitDir = 0) inline private
Definition at line 948 of file zombiebase.c.
    {
        vector targetDirection = GetDirection();
        vector toSourceDirection = (pSource.GetPosition() - GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        float dirAngle = Math.Acos(cosFi) * Math.RAD2DEG;
        // We will invert direction of the hit
        if ( invertHitDir > 0 )
            dirAngle -= 180;
        if ( cross[1] < 0 )
            dirAngle = -dirAngle;
        return dirAngle;
    }
References Math::Acos(), vector::Dot(), GetDirection(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
DebugSound()
protected void DayZInfected::DebugSound (string s) inline private
sound debug messages
Definition at line 1020 of file zombiebase.c.
    {
        //Print(s);
    }
EEHitBy()
override void DayZInfected::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Events from damage system
Definition at line 979 of file zombiebase.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        m_TransportHitRegistered = false;
        if ( !IsAlive() )
        {
            dBodySetInteractionLayer(this, PhxInteractionLayers.RAGDOLL);
            ZombieHitData data = new ZombieHitData;
            data.m_Component = component;
            data.m_DamageZone = dmgZone;
            data.m_AmmoType = ammo;
            EvaluateDeathAnimationEx(source, data, m_DeathType, m_DamageHitDirection);
        }
        else
        {
            int crawlTransitionType = -1;
            if ( EvaluateCrawlTransitionAnimation(source, dmgZone, ammo, crawlTransitionType) )
            {
                m_CrawlTransition = crawlTransitionType;
                return;
            }
            if ( EvaluateDamageHitAnimation(source, dmgZone, ammo, m_DamageHitHeavy, m_DamageHitType, m_DamageHitDirection) )
            {
                if ( dmgZone )
                    m_ShockDamage = damageResult.GetDamage( dmgZone, "Shock" );
                m_DamageHitToProcess = true;
                return;
            }
        }
    }
References component, dBodySetInteractionLayer(), EvaluateDamageHitAnimation(), TotalDamageResult::GetDamage(), and IsAlive().
EEHitByRemote()
override void DayZInfected::EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos) inline private
Definition at line 1014 of file zombiebase.c.
    {
        super.EEHitByRemote(damageType, source, component, dmgZone, ammo, modelPos);
    }
References component.
EOnContact()
override protected void DayZInfected::EOnContact (IEntity other, Contact extra) inline private
Phx contact event
Definition at line 1030 of file zombiebase.c.
    {
        if ( !IsAlive() )
            return;
        Transport transport = Transport.Cast(other);
        if ( transport )
        {
            if ( GetGame().IsServer() )
            {
                RegisterTransportHit(transport);
            }
        }
    }
References GetGame(), and IsAlive().
EOnInit()
override void DayZInfected::EOnInit (IEntity other, int extra) inline private
Definition at line 87 of file zombiebase.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            m_StanceVariation = Math.RandomInt(0, 4);
            DayZInfectedCommandMove moveCommand = GetCommand_Move();
            moveCommand.SetStanceVariation(m_StanceVariation);
        }
    }
References GetCommand_Move(), GetGame(), and Math::RandomInt().
EvaluateCrawlTransitionAnimation()
bool DayZInfected::EvaluateCrawlTransitionAnimation (EntityAI pSource, string pComponent, string pAmmoType, out int pAnimType) inline private
Definition at line 835 of file zombiebase.c.
    {
        pAnimType = -1;
        if ( pComponent == "LeftLeg" && GetHealth(pComponent, "Health") == 0 )
            pAnimType = 0;
        else if ( pComponent == "RightLeg" && GetHealth(pComponent, "Health") == 0 )
            pAnimType = 2;
        if ( pAnimType != -1 )
        {
            vector targetDirection = GetDirection();
            vector toSourceDirection = (pSource.GetPosition() - GetPosition());
            targetDirection[1] = 0;
            toSourceDirection[1] = 0;
            targetDirection.Normalize();
            toSourceDirection.Normalize();
            float cosFi = vector.Dot(targetDirection, toSourceDirection);
            if ( cosFi >= 0 ) // front
                pAnimType++;
        }
        return pAnimType != -1;
    }
References vector::Dot(), GetDirection(), GetHealth(), GetPosition, and vector::Normalize().
EvaluateDamageHitAnimation()
bool DayZInfected::EvaluateDamageHitAnimation (EntityAI pSource, string pComponent, string pAmmoType, out bool pHeavyHit, out int pAnimType, out float pAnimHitDir) inline private
selects animation type and direction based on damage system data
heavy hit
anim type
direction
shock GetDamage
Definition at line 900 of file zombiebase.c.
    {
        int invertHitDir = 0; //Used to flip the heavy hit animation direction
        pHeavyHit = ((GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " hitAnimation") > 0) || m_HeavyHitOverride);
        invertHitDir = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " invertHitDir");
        pAnimType = 0; // belly
        if ( !pHeavyHit )
        {
            if ( pComponent == "Torso" ) // body
                pAnimType = 1;
            else if ( pComponent == "Head" ) // head
                pAnimType = 2;
        }
        //pAnimHitDir = ComputeHitDirectionAngle(pSource);
        pAnimHitDir = ComputeHitDirectionAngleEx(pSource, invertHitDir);
        //m_ShockDamage = GetGame().ConfigGetFloat( "CfgAmmo " + pAmmoType + " DamageApplied " + "Shock " + "damage");
        return true;
    }
References CGame::ConfigGetInt(), and GetGame().
EvaluateDeathAnimation()
bool DayZInfected::EvaluateDeathAnimation (EntityAI pSource, string pComponent, string pAmmoType, out int pAnimType, out float pAnimHitDir) inline private
anim type
direction
add some impulse if needed
Definition at line 385 of file zombiebase.c.
    {
        bool doPhxImpulse = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " doPhxImpulse") > 0;
        pAnimType = doPhxImpulse;
        pAnimHitDir = ComputeHitDirectionAngle(pSource);
        if ( doPhxImpulse )
        {
            vector impulse = 80 * m_TransportHitVelocity;
            impulse[1] = 80 * 1.5;
            //Print("Impulse: " + impulse.ToString());
            dBodyApplyImpulse(this, impulse);
        }
        return true;
    }
References CGame::ConfigGetInt(), dBodyApplyImpulse(), and GetGame().
EvaluateDeathAnimationEx()
bool DayZInfected::EvaluateDeathAnimationEx (EntityAI pSource, ZombieHitData data, out int pAnimType, out float pAnimHitDir) inline private
Definition at line 378 of file zombiebase.c.
    {
        bool ret = EvaluateDeathAnimation(pSource,data.m_DamageZone,data.m_AmmoType,pAnimType,pAnimHitDir);
        return ret;
    }
References EvaluateDeathAnimation().
FightAttackLogic()
bool DayZInfected::FightAttackLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt) inline private
do not attack players in vehicle - hotfix
target is outside the targeting cone; skip attack
Definition at line 736 of file zombiebase.c.
    {
        // always update target - it can be destroyed
        m_ActualTarget = pInputController.GetTargetEntity();
        PlayerBase pb = PlayerBase.Cast(m_ActualTarget);
        if ( pb && pb.GetCommand_Vehicle() )
        {
            return false;
        }
        if ( m_AttackCooldownTime > 0 )
        {
            m_AttackCooldownTime -= pDt * GameConstants.AI_ATTACKSPEED;
            return false;
        }
        if ( m_ActualTarget == NULL )
            return false;
        vector targetPos = m_ActualTarget.GetPosition();
        float targetDist = vector.Distance(targetPos, this.GetPosition());
        int pitch = GetAttackPitch(m_ActualTarget);
        if ( !CanAttackToPosition(targetPos) )
            return false;
        m_ActualAttackType = GetDayZInfectedType().ChooseAttack(DayZInfectedAttackGroupType.FIGHT, targetDist, pitch);
        if ( m_ActualAttackType )
        {
            Object target = DayZPlayerUtils.GetMeleeTarget(this.GetPosition(), this.GetDirection(), TARGET_CONE_ANGLE_FIGHT, m_ActualAttackType.m_Distance, -1.0, 2.0, this, m_TargetableObjects, m_AllTargetObjects);
            if (m_ActualTarget != target)
            {
                m_AllTargetObjects.Clear();
                return false;
            }
            StartCommand_Attack(m_ActualTarget, m_ActualAttackType.m_Type, m_ActualAttackType.m_Subtype);
            m_AttackCooldownTime = m_ActualAttackType.m_Cooldown;
            return true;
        }
        return false;
    }
References GameConstants::AI_ATTACKSPEED, vector::Distance(), GetDirection(), DayZPlayerUtils::GetMeleeTarget(), GetPosition, DayZInfectedInputController::GetTargetEntity(), m_AllTargetObjects, DayZInfectedAttackType::m_Cooldown, DayZInfectedAttackType::m_Distance, DayZInfectedAttackType::m_Subtype, m_TargetableObjects, and DayZInfectedAttackType::m_Type.
FightLogic()
bool DayZInfected::FightLogic (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt) inline private
player is in block stance and facing the infected
infected is playing heavy attack - decrease the dmg to light
override hit pos by pos defined in type
infected is playing light attack - do not send damage, play animation instead
override hit pos by pos defined in type
override hit pos by pos defined in type
Definition at line 622 of file zombiebase.c.
    {
        if ( pCurrentCommandID == DayZInfectedConstants.COMMANDID_MOVE )
        {
            // we attack only in chase & fight state
            int mindState = pInputController.GetMindState();
            if ( mindState == DayZInfectedConstants.MINDSTATE_CHASE )
            {
                return ChaseAttackLogic(pCurrentCommandID, pInputController, pDt);
            }
            else if ( mindState == DayZInfectedConstants.MINDSTATE_FIGHT )
            {
                return FightAttackLogic(pCurrentCommandID, pInputController, pDt);
            }
        }
        else if ( pCurrentCommandID == DayZInfectedConstants.COMMANDID_ATTACK )
        {
            DayZInfectedCommandAttack attackCommand = GetCommand_Attack();
            if ( attackCommand && attackCommand.WasHit() )
            {
                if ( m_ActualTarget != NULL )
                {
                    if (m_ActualTarget.GetMeleeTargetType() == EMeleeTargetType.NONALIGNABLE )
                    {
                        return false;
                    }
                    bool playerInBlockStance = false;
                    vector targetPos = m_ActualTarget.GetPosition();
                    vector hitPosWS = targetPos;
                    vector zombiePos = GetPosition();
                    PlayerBase playerTarget = PlayerBase.Cast(m_ActualTarget);
                    if ( playerTarget )
                    {
                        playerInBlockStance = playerTarget.GetMeleeFightLogic() && playerTarget.GetMeleeFightLogic().IsInBlock();
                    }
                    if ( vector.DistanceSq(targetPos, zombiePos) <= m_ActualAttackType.m_Distance * m_ActualAttackType.m_Distance )
                    {
                        if ( playerInBlockStance && (Math.RAD2DEG * Math.AbsFloat(Math3D.AngleFromPosition(targetPos, MiscGameplayFunctions.GetHeadingVector(playerTarget), zombiePos))) <= GameConstants.AI_MAX_BLOCKABLE_ANGLE )
{
                            if ( m_ActualAttackType.m_IsHeavy != 0 )
{
                                hitPosWS = m_ActualTarget.ModelToWorld(m_ActualTarget.GetDefaultHitPosition());
                                DamageSystem.CloseCombatDamageName(this, m_ActualTarget, m_ActualTarget.GetHitComponentForAI(), "MeleeZombie", hitPosWS);
                            }
                            else
{
                                if ( GetGame().IsServer() )
{
                                    hitPosWS = m_ActualTarget.GetDefaultHitPosition();
                                    m_ActualTarget.EEHitBy(null, 0, this, -1, m_ActualTarget.GetDefaultHitComponent(), "Dummy_Light", hitPosWS, 1.0);
                                }
                            }
                        }
                        else
{
                            hitPosWS = m_ActualTarget.ModelToWorld(m_ActualTarget.GetDefaultHitPosition());
                            DamageSystem.CloseCombatDamageName(this, m_ActualTarget, m_ActualTarget.GetHitComponentForAI(), m_ActualAttackType.m_AmmoType, hitPosWS);
                        }
                    }
                }
            }
            return true;
        }
        return false;
    }
References Math::AbsFloat(), GameConstants::AI_MAX_BLOCKABLE_ANGLE, Math3D::AngleFromPosition(), vector::DistanceSq(), GetGame(), EntityAI::GetMeleeTargetType(), DayZInfectedInputController::GetMindState(), GetPosition, DayZInfectedAttackType::m_AmmoType, DayZInfectedAttackType::m_Distance, DayZInfectedAttackType::m_IsHeavy, and Math::RAD2DEG.
GetAttackPitch()
int DayZInfected::GetAttackPitch (EntityAI target) inline private
no default hit pos fallback
Definition at line 783 of file zombiebase.c.
    {
        vector attackRefPos;
        attackRefPos = target.GetDefaultHitPosition();
        if ( attackRefPos != vector.Zero )
        {
            attackRefPos = target.ModelToWorld(attackRefPos);
        }
        else
        {
            attackRefPos = target.GetPosition();
        }
        // Now we have only erect stance, we need to get head position later too
        float headPosY = GetPosition()[1];
        headPosY += 1.8;
        float diff = Math.AbsFloat(attackRefPos[1] - headPosY);
        if ( diff < 0.3 )
            return 0;
        if ( headPosY > attackRefPos[1] )
            return -1;
        else
            return 1;
    }
References Math::AbsFloat(), GetPosition, and vector::Zero.
GetBootsType()
override AnimBootsType DayZInfected::GetBootsType () inline private
Definition at line 129 of file zombiebase.c.
    {
        return AnimBootsType.Boots;
    }
GetCenter()
override vector DayZInfected::GetCenter () inline private
Definition at line 1054 of file zombiebase.c.
    {
        return GetBonePositionWS( GetBoneIndexByName( "spine3" ) );
    }
References GetBoneIndexByName(), and GetBonePositionWS().
GetDefaultHitComponent()
override string DayZInfected::GetDefaultHitComponent () inline private
returns default hit component (fallback)
Definition at line 156 of file zombiebase.c.
    {
        return GetDayZInfectedType().GetDefaultHitComponent();
    }
GetDefaultHitPosition()
override vector DayZInfected::GetDefaultHitPosition () inline private
Definition at line 161 of file zombiebase.c.
    {
        return m_DefaultHitPosition;
    }
GetHitComponentForAI()
override string DayZInfected::GetHitComponentForAI () inline private
returns hit component for attacking AI
Definition at line 150 of file zombiebase.c.
    {
        return GetDayZInfectedType().GetHitComponentForAI();
    }
GetMindStateSynced()
int DayZInfected::GetMindStateSynced () inline private
Definition at line 177 of file zombiebase.c.
    {
        return m_MindState;
    }
GetOrientationSynced()
int DayZInfected::GetOrientationSynced () inline private
returns rounded zombie yaw for sync purposes
Definition at line 183 of file zombiebase.c.
    {
        return m_OrientationSynced;
    }
GetSuitableFinisherHitComponents()
override array< string > DayZInfected::GetSuitableFinisherHitComponents () inline private
returns suitable hit components for finisher attacks; DEPRECATED
Definition at line 172 of file zombiebase.c.
    {
        return GetDayZInfectedType().GetSuitableFinisherHitComponents();
    }
GetVaultType()
int DayZInfected::GetVaultType (float height) inline private
Definition at line 416 of file zombiebase.c.
    {
        if ( height <= 0.6 )
            return 0;
        else if ( height <= 1.1 )
            return 1;
        else if ( height <= 1.6 )
            return 2;
        else
            return 3;
    }
HandleCrawlTransition()
bool DayZInfected::HandleCrawlTransition (int pCurrentCommandID) inline private
Definition at line 820 of file zombiebase.c.
    {
        if ( m_CrawlTransition != -1 )
        {
            StartCommand_Crawl(m_CrawlTransition);
            m_CrawlTransition = -1;
            m_IsCrawling = true;
            SetSynchDirty();
            return true;
        }
        return pCurrentCommandID == DayZInfectedConstants.COMMANDID_CRAWL;
    }
HandleDamageHit()
bool DayZInfected::HandleDamageHit (int pCurrentCommandID) inline private
Definition at line 873 of file zombiebase.c.
    {
        if ( pCurrentCommandID == DayZInfectedConstants.COMMANDID_HIT )
        {
            m_DamageHitToProcess = false;
            m_ShockDamage = 0;
            return true;
        }
        if ( m_DamageHitToProcess )
        {
            int randNum = Math.RandomIntInclusive(0, 100);
            float stunChange = SHOCK_TO_STUN_MULTIPLIER * m_ShockDamage;
            if ( m_DamageHitHeavy || randNum <= stunChange || ( m_MindState == DayZInfectedConstants.MINDSTATE_CALM || m_MindState == DayZInfectedConstants.MINDSTATE_DISTURBED ) )
                StartCommand_Hit(m_DamageHitHeavy, m_DamageHitType, m_DamageHitDirection);
            m_DamageHitToProcess = false;
            m_ShockDamage = 0;
            m_HeavyHitOverride = false;
            return true;
        }
        return false;
    }
References Math::RandomIntInclusive().
HandleDeath()
bool DayZInfected::HandleDeath (int pCurrentCommandID) inline private
Definition at line 364 of file zombiebase.c.
    {
        if ( !IsAlive() || m_FinisherInProgress )
        {
            StartCommand_Death(m_DeathType, m_DamageHitDirection);
            m_MovementSpeed = -1;
            m_MindState = -1;
            SetSynchDirty();
            return true;
        }
        return false;
    }
References IsAlive(), and StartCommand_Death().
HandleMindStateChange()
bool DayZInfected::HandleMindStateChange (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt) inline private
Mind state change
Definition at line 465 of file zombiebase.c.
    {
        DayZInfectedCommandMove moveCommand = GetCommand_Move();
        m_MindState = pInputController.GetMindState();
        if ( m_LastMindState != m_MindState )
        {
            switch ( m_MindState )
            {
            case DayZInfectedConstants.MINDSTATE_CALM:
                if ( moveCommand && !moveCommand.IsTurning() )
                    moveCommand.SetIdleState(0);
                break;
            case DayZInfectedConstants.MINDSTATE_DISTURBED:
                if ( moveCommand && !moveCommand.IsTurning() )
                    moveCommand.SetIdleState(1);
                break;
            case DayZInfectedConstants.MINDSTATE_CHASE:
                if ( moveCommand && !moveCommand.IsTurning() && (m_LastMindState < DayZInfectedConstants.MINDSTATE_CHASE) )
                    moveCommand.SetIdleState(2);
                break;
            }
            m_LastMindState = m_MindState;
            m_AttackCooldownTime = 0.0;
            SetSynchDirty();
        }
        return false;
    }
References GetCommand_Move(), and DayZInfectedInputController::GetMindState().
HandleMove()
void DayZInfected::HandleMove (int pCurrentCommandID) inline private
HandleMove
Definition at line 311 of file zombiebase.c.
    {
        DayZInfectedInputController ic = GetInputController();
        m_MovementSpeed = ic.GetMovementSpeed();
        if (Math.AbsFloat(m_LastMovementSpeed - m_MovementSpeed) >= 0.9 && m_LastMovementSpeed != m_MovementSpeed)
        {
            SetSynchDirty();
        }
        m_LastMovementSpeed = m_MovementSpeed;
    }
References Math::AbsFloat(), GetInputController(), and DayZInfectedInputController::GetMovementSpeed().
HandleOrientation()
void DayZInfected::HandleOrientation (float pDt, int pCurrentCommandID) inline private
HandleOrientation
Definition at line 328 of file zombiebase.c.
    {
        m_OrientationTimer += pDt;
        int yaw = Math.Round(GetOrientation()[0]);
        yaw = Math.NormalizeAngle(yaw);
        //atan2(sin(x-y), cos(x-y))
        float angleSourceRad = m_OrientationSynced * Math.DEG2RAD;
        float angleTargetRad = yaw * Math.DEG2RAD;
        float angleDiffRad = Math.Atan2(Math.Sin(angleTargetRad - angleSourceRad), Math.Cos(angleSourceRad - angleTargetRad));
        angleDiffRad *= Math.RAD2DEG;
        angleDiffRad = Math.Round(angleDiffRad);
        if (m_OrientationTimer >= 2.0 || m_OrientationSynced == -1 || Math.AbsInt(angleDiffRad) > ORIENTATION_SYNC_THRESHOLD)
        {
            m_OrientationTimer = 0.0;
            if (m_OrientationSynced == -1 || Math.AbsInt(angleDiffRad) > 5)
            {
                //Print("DbgSyncOrientation | HandleMove | original: " + m_OrientationSynced + " | target: " + yaw + " | diff: " + angleDiffRad);
                m_OrientationSynced = yaw;
                SetSynchDirty();
            }
        }
    }
References Math::AbsInt(), Math::Atan2(), Math::Cos(), Math::DEG2RAD, GetOrientation(), Math::NormalizeAngle(), Math::RAD2DEG, Math::Round(), and Math::Sin().
HandleSoundEvents()
protected void DayZInfected::HandleSoundEvents () inline private
Sound (client only)
no sound handler - bail out
infected is dead
stop all sounds
Definition at line 502 of file zombiebase.c.
    {
        if ( !m_InfectedSoundEventHandler )
        {
            return;
        }
        if ( !IsAlive() )
        {
            m_InfectedSoundEventHandler.Stop();
            return;
        }
        switch ( m_MindState )
        {
        case DayZInfectedConstants.MINDSTATE_CALM:
            m_InfectedSoundEventHandler.PlayRequest(EInfectedSoundEventID.MINDSTATE_CALM_MOVE);
            break;
        case DayZInfectedConstants.MINDSTATE_ALERTED:
            m_InfectedSoundEventHandler.PlayRequest(EInfectedSoundEventID.MINDSTATE_ALERTED_MOVE);
            break;
        case DayZInfectedConstants.MINDSTATE_DISTURBED:
            m_InfectedSoundEventHandler.PlayRequest(EInfectedSoundEventID.MINDSTATE_DISTURBED_IDLE);
            break
        case DayZInfectedConstants.MINDSTATE_CHASE:
            m_InfectedSoundEventHandler.PlayRequest(EInfectedSoundEventID.MINDSTATE_CHASE_MOVE);
            break;
        default:
            m_InfectedSoundEventHandler.Stop();
            break;
        }
        DebugSound("[Infected @ " + this + "][MindState]" + typename.EnumToString(DayZInfectedConstants, m_MindState));
        DebugSound("[Infected @ " + this + "][SoundEventID]" + typename.EnumToString(EInfectedSoundEventID, m_InfectedSoundEventHandler.GetCurrentStateEventID()));
    }
References IsAlive().
HandleVault()
bool DayZInfected::HandleVault (int pCurrentCommandID, DayZInfectedInputController pInputController, float pDt) inline private
Definition at line 428 of file zombiebase.c.
    {
        if ( pCurrentCommandID == DayZInfectedConstants.COMMANDID_VAULT )
        {
            DayZInfectedCommandVault vaultCmd = GetCommand_Vault();
            if ( vaultCmd && vaultCmd.WasLand() )
            {
                m_KnuckleOutTimer = 0;
                m_KnuckleLand = true;
            }
            if ( m_KnuckleLand )
            {
                m_KnuckleOutTimer += pDt;
                if ( m_KnuckleOutTimer > 2.0 )
                    StartCommand_Vault(-1);
            }
            return true;
        }
        if ( pInputController.IsVault() )
        {
            float vaultHeight = pInputController.GetVaultHeight();
            int vaultType = GetVaultType(vaultHeight);
            m_KnuckleLand = false;
            StartCommand_Vault(vaultType);
            return true;
        }
        return false;
    }
References DayZInfectedInputController::GetVaultHeight(), and DayZInfectedInputController::IsVault().
Init()
void DayZInfected::Init () inline private
sets default hit position and cache it here (mainly for impact particles)
client only
Definition at line 45 of file zombiebase.c.
    {
        SetEventMask(EntityEvent.INIT);
        m_IsCrawling = false;
        RegisterNetSyncVariableInt("m_MindState", -1, 4);
        RegisterNetSyncVariableInt("m_OrientationSynced", 0, 359);
        RegisterNetSyncVariableFloat("m_MovementSpeed", -1, 3);
        RegisterNetSyncVariableBool("m_IsCrawling");
        m_DefaultHitPosition = SetDefaultHitPosition(GetDayZInfectedType().GetDefaultHitPositionComponent());
        if ( !GetGame().IsDedicatedServer() )
        {
            m_LastSoundVoiceAW          = null;
            m_InfectedSoundEventHandler = new InfectedSoundEventHandler(this);
        }
        m_AllTargetObjects      = new array<Object>;
        m_TargetableObjects     = new array<typename>;
        m_TargetableObjects.Insert(PlayerBase);
        m_TargetableObjects.Insert(AnimalBase);
        m_OrientationTimer = 0;
    }
References GetDefaultHitPositionComponent(), GetGame(), InfectedSoundEventHandler(), m_AllTargetObjects, and m_TargetableObjects.
IsBeingBackstabbed()
override bool DayZInfected::IsBeingBackstabbed () inline private
returns true if backstab is in progress; used for suspending of AI targeting and other useful things besides
Definition at line 1060 of file zombiebase.c.
    {
        return m_FinisherInProgress;
    }
IsCrawling()
bool DayZInfected::IsCrawling () inline private
returns true if crawling; 'DayZInfectedCommandCrawl' is only for the transition, after that it remains 'DayZInfectedCommandMove' (unreliable)
Definition at line 1092 of file zombiebase.c.
    {
        return m_IsCrawling;
    }
IsDanger()
override bool DayZInfected::IsDanger () inline private
Definition at line 103 of file zombiebase.c.
    {
        return true;
    }
IsHealthVisible()
override bool DayZInfected::IsHealthVisible () inline private
Definition at line 139 of file zombiebase.c.
    {
        return false;
    }
IsMale()
bool DayZInfected::IsMale () inline private
Definition at line 118 of file zombiebase.c.
    {
        return true;
    }
IsRefresherSignalingViable()
override bool DayZInfected::IsRefresherSignalingViable () inline private
Definition at line 144 of file zombiebase.c.
    {
        return false;
    }
IsZombie()
override bool DayZInfected::IsZombie () inline private
Definition at line 98 of file zombiebase.c.
    {
        return true;
    }
IsZombieMilitary()
override bool DayZInfected::IsZombieMilitary () inline private
Definition at line 108 of file zombiebase.c.
    {
        /*if ( IsKindOf( "ZmbM_SoldierNormal_Base" ) )
        {
            return true;
        }*/
        return false;
    }
ModCommandHandlerAfter()
bool DayZInfected::ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 287 of file zombiebase.c.
    {
        return false;
    }
ModCommandHandlerBefore()
bool DayZInfected::ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
ModOverrides
Definition at line 277 of file zombiebase.c.
    {
        return false;
    }
ModCommandHandlerInside()
bool DayZInfected::ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 282 of file zombiebase.c.
    {
        return false;
    }
OnRecoverFromDeath()
void DayZInfected::OnRecoverFromDeath () inline private
Definition at line 1098 of file zombiebase.c.
    {
        // enable AI simulation again
        GetAIAgent().SetKeepInIdle(false);
        // reset flag
        m_FinisherInProgress = false;
        //Print("DbgZombies | DumbZombie off: " + GetGame().GetTime());
    }
OnSoundVoiceEvent()
override void DayZInfected::OnSoundVoiceEvent (int event_id, string event_user_string) inline private
stop state sound when playing anim SoundVoice
stop playing of old SoundVoice from anim (if any)
play new SoundVoice from anim
Definition at line 565 of file zombiebase.c.
    {
        //super.OnSoundVoiceEvent(event_id, event_user_string);
        AnimSoundVoiceEvent voice_event = GetCreatureAIType().GetSoundVoiceEvent(event_id);
        if (voice_event != null)
        {
            if (m_InfectedSoundEventHandler) // && m_InfectedSoundEventHandler.IsPlaying())
            {
                m_InfectedSoundEventHandler.Stop();
                DebugSound("[Infected @ " + this + "][SoundEvent] InfectedSoundEventHandler - stop all");
            }
            if (m_LastSoundVoiceAW != null)
            {
                DebugSound("[Infected @ " + this + "][AnimVoiceEvent] Stopping LastAW");
                m_LastSoundVoiceAW.Stop();
            }
            ProcessSoundVoiceEvent(voice_event, m_LastSoundVoiceAW);
            HandleSoundEvents();
        }
    }
References AbstractWave::Stop().
OnVariablesSynchronized()
override void DayZInfected::OnVariablesSynchronized () inline private
synced variable(s) handler
Definition at line 75 of file zombiebase.c.
    {
        DebugSound("[Infected @ " + this + "][OnVariablesSynchronized]");
        HandleSoundEvents();
        if ( m_OrientationLocal != m_OrientationSynced )
        {
            m_OrientationLocal = m_OrientationSynced;
        }
    }
ProcessSoundVoiceEvent()
protected void DayZInfected::ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event, out AbstractWave aw) inline private
Definition at line 592 of file zombiebase.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            SoundObjectBuilder objectBuilder = sound_event.GetSoundBuilder();
            if (NULL != objectBuilder)
            {
                objectBuilder.UpdateEnvSoundControllers(GetPosition());
                SoundObject soundObject = objectBuilder.BuildSoundObject();
                AttenuateSoundIfNecessary(soundObject);
                aw = PlaySound(soundObject, objectBuilder);
            }
        }
        if (GetGame().IsServer())
        {
            if (sound_event.m_NoiseParams != NULL)
                GetGame().GetNoiseSystem().AddNoise(this, sound_event.m_NoiseParams);
        }
    }
References NoiseSystem::AddNoise(), AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessVoiceFX()
AbstractWave DayZInfected::ProcessVoiceFX (string pSoundSetName) inline private
Definition at line 541 of file zombiebase.c.
    {
        ref SoundParams         soundParams;
        ref SoundObjectBuilder  soundObjectBuilder;
        ref SoundObject         soundObject;
        if (!GetGame().IsDedicatedServer())
        {
            soundParams = new SoundParams( pSoundSetName );
            if ( !soundParams.IsValid() )
            {
                //SoundError("Invalid sound set.");
                return null;
            }
            soundObjectBuilder = new SoundObjectBuilder( soundParams );
            soundObject = soundObjectBuilder.BuildSoundObject();
            AttenuateSoundIfNecessary(soundObject);
            return PlaySound(soundObject, soundObjectBuilder);
        }
        return null;
    }
References AttenuateSoundIfNecessary(), GetGame(), PlaySound(), and SoundObject().
SetBeingBackstabbed()
override void DayZInfected::SetBeingBackstabbed (int backstabType) inline private
Definition at line 1065 of file zombiebase.c.
    {
        // disable AI simulation
        GetAIAgent().SetKeepInIdle(true);
        // select death animation
        switch( backstabType )
        {
        case EMeleeHitType.FINISHER_LIVERSTAB:
            m_DeathType = DayZInfectedDeathAnims.ANIM_DEATH_BACKSTAB;
            break;
        case EMeleeHitType.FINISHER_NECKSTAB:
            m_DeathType = DayZInfectedDeathAnims.ANIM_DEATH_NECKSTAB;
            break;
        default:
            m_DeathType = DayZInfectedDeathAnims.ANIM_DEATH_DEFAULT;
        }
        // set flag - death command will be executed
        m_FinisherInProgress = true;
        //Print("DbgZombies | DumbZombie on: " + GetGame().GetTime());
    }
SetDefaultHitPosition()
protected vector DayZInfected::SetDefaultHitPosition (string pSelection) inline private
Definition at line 166 of file zombiebase.c.
    {
        return GetSelectionPositionMS(pSelection);
    }
References GetSelectionPositionMS().
ZombieBase()
void DayZInfected::ZombieBase () inline private
Definition at line 40 of file zombiebase.c.
    {
        Init();
    }
References Init().
Member Data Documentation
m_ActiveVaultType
int DayZInfected::m_ActiveVaultType = -1 private
HandleVault
Definition at line 414 of file zombiebase.c.
m_ActualAttackType
DayZInfectedAttackType DayZInfected::m_ActualAttackType = NULL private
Definition at line 620 of file zombiebase.c.
m_ActualTarget
EntityAI DayZInfected::m_ActualTarget = NULL private
Combat
Definition at line 618 of file zombiebase.c.
m_AllTargetObjects
protected ref array<Object> DayZInfected::m_AllTargetObjects private
Definition at line 28 of file zombiebase.c.
m_AttackCooldownTime
float DayZInfected::m_AttackCooldownTime = 0 private
Definition at line 619 of file zombiebase.c.
m_CrawlTransition
int DayZInfected::m_CrawlTransition = -1 private
Crawl transition
Definition at line 818 of file zombiebase.c.
m_DamageHitDirection
float DayZInfected::m_DamageHitDirection = 0 private
HandleDeath
Definition at line 361 of file zombiebase.c.
m_DamageHitHeavy
bool DayZInfected::m_DamageHitHeavy = false private
Definition at line 869 of file zombiebase.c.
m_DamageHitToProcess
bool DayZInfected::m_DamageHitToProcess = false private
Damage hits
Definition at line 867 of file zombiebase.c.
m_DamageHitType
int DayZInfected::m_DamageHitType = 0 private
Definition at line 870 of file zombiebase.c.
m_DeathType
int DayZInfected::m_DeathType = 0 private
Definition at line 362 of file zombiebase.c.
m_DefaultHitPosition
protected vector DayZInfected::m_DefaultHitPosition private
Definition at line 23 of file zombiebase.c.
m_FinisherInProgress
protected bool DayZInfected::m_FinisherInProgress = false private
Definition at line 35 of file zombiebase.c.
m_InfectedSoundEventHandler
protected ref InfectedSoundEventHandler DayZInfected::m_InfectedSoundEventHandler private
Definition at line 26 of file zombiebase.c.
m_IsCrawling
protected bool DayZInfected::m_IsCrawling private
Definition at line 33 of file zombiebase.c.
m_KnuckleLand
protected bool DayZInfected::m_KnuckleLand = false private
Definition at line 14 of file zombiebase.c.
m_KnuckleOutTimer
protected float DayZInfected::m_KnuckleOutTimer = 0 private
Definition at line 15 of file zombiebase.c.
m_LastMindState
protected int DayZInfected::m_LastMindState = -1 private
Definition at line 11 of file zombiebase.c.
m_LastMovementSpeed
protected float DayZInfected::m_LastMovementSpeed = -1 private
Definition at line 12 of file zombiebase.c.
m_LastSoundVoiceAW
protected AbstractWave DayZInfected::m_LastSoundVoiceAW private
Definition at line 25 of file zombiebase.c.
m_MindState
protected int DayZInfected::m_MindState = -1 private
Definition at line 17 of file zombiebase.c.
m_MovementSpeed
protected float DayZInfected::m_MovementSpeed = -1 private
Definition at line 21 of file zombiebase.c.
m_OrientationLocal
protected int DayZInfected::m_OrientationLocal = -1 private
Definition at line 18 of file zombiebase.c.
m_OrientationSynced
protected int DayZInfected::m_OrientationSynced = -1 private
Definition at line 19 of file zombiebase.c.
m_OrientationTimer
protected float DayZInfected::m_OrientationTimer private
Definition at line 20 of file zombiebase.c.
m_ShockDamage
float DayZInfected::m_ShockDamage = 0 private
Definition at line 871 of file zombiebase.c.
m_StanceVariation
protected int DayZInfected::m_StanceVariation = 0 private
server / singleplayer properties
Definition at line 10 of file zombiebase.c.
m_TargetableObjects
protected ref array<typename> DayZInfected::m_TargetableObjects private
Definition at line 29 of file zombiebase.c.
ORIENTATION_SYNC_THRESHOLD
const float DayZInfected::ORIENTATION_SYNC_THRESHOLD = 30 private
Definition at line 5 of file zombiebase.c.
SHOCK_TO_STUN_MULTIPLIER
const float DayZInfected::SHOCK_TO_STUN_MULTIPLIER = 2.82 private
Definition at line 7 of file zombiebase.c.
TARGET_CONE_ANGLE_CHASE
const float DayZInfected::TARGET_CONE_ANGLE_CHASE = 20 private
Definition at line 3 of file zombiebase.c.
TARGET_CONE_ANGLE_FIGHT
const float DayZInfected::TARGET_CONE_ANGLE_FIGHT = 30 private
Definition at line 4 of file zombiebase.c.