DayzKode: HandsArea Class Reference
HandsArea Class Reference
Private Member Functions
void DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver)
override ScrollWidget GetScrollWidget ()
void HandsArea (LayoutHolder parent)
bool IsCombineActive ()
bool IsSwapActive ()
void OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver)
override void OnShow ()
override void Refresh ()
override void SetLayoutName ()
override void SetParentWidget ()
override void UpdateInterval ()
override void UpdateSelectionIcons ()
Private Attributes
protected ref HandsContainer m_HandsContainer
protected ref SizeToChild m_HandsResizer
protected ScrollWidget m_Scroller
protected bool m_ShouldChangeSize = true
Detailed Description
Definition at line 1 of file handsarea.c.
Constructor & Destructor Documentation
HandsArea()
void HandsArea::HandsArea (LayoutHolder parent) inline private
Definition at line 9 of file handsarea.c.
    {
        m_HandsContainer = new HandsContainer( this );
        m_Body.Insert(m_HandsContainer);
        if ( m_ImmedUpdate )
            m_MainWidget.Update();
        m_ParentWidget.GetScript( m_HandsResizer );
        m_Scroller = ScrollWidget.Cast( m_ParentWidget );
        RecomputeOpenedContainers();
    }
References m_HandsContainer, m_HandsResizer, and m_Scroller.
Member Function Documentation
DraggingOverHandsPanel()
void HandsArea::DraggingOverHandsPanel (Widget w, int x, int y, Widget receiver) inline private
Definition at line 105 of file handsarea.c.
    {
        if ( w == NULL )
        {
            return;
        }
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        if( ipw.GetItem() && GetGame().GetPlayer().GetHumanInventory().CanAddEntityIntoHands( ipw.GetItem() ) )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
        }
        else
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
        }
    }
References CanAddEntityIntoHands(), ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), name, ColorManager::RED_COLOR, string::Replace(), and ColorManager::SetColor().
Referenced by DraggingOverHandsPanel().
GetScrollWidget()
override ScrollWidget HandsArea::GetScrollWidget () inline private
Definition at line 42 of file handsarea.c.
    {
        return m_Scroller;
    }
References m_Scroller.
IsCombineActive()
bool HandsArea::IsCombineActive () inline private
Definition at line 32 of file handsarea.c.
    {
        Widget combine_cursor = m_MainWidget.FindAnyWidget("CombineCursor");
        if ( combine_cursor )
            return combine_cursor.IsVisible();
        else
            return false;
    }
IsSwapActive()
bool HandsArea::IsSwapActive () inline private
Definition at line 22 of file handsarea.c.
    {
        Widget swap_cursor = m_MainWidget.FindAnyWidget("SwapCursor");
        if ( swap_cursor )
            return swap_cursor.IsVisible();
        else
            return false;
    }
OnHandsPanelDropReceived()
void HandsArea::OnHandsPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
Definition at line 145 of file handsarea.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw || !ipw.GetItem() || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        if( !ipw.GetItem().GetInventory().CanRemoveEntity() )
            return;
        if( GetGame().GetPlayer().GetHumanInventory().CanAddEntityIntoHands( ipw.GetItem() ) )
        {
            ItemBase item_base = ItemBase.Cast( ipw.GetItem() );
            float stackable = item_base.GetTargetQuantityMax(-1);
            if( stackable == 0 || item_base.GetQuantity() <= stackable )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToHands( item_base );
            }
            else if( stackable != 0 && stackable <= item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxHandsClient( PlayerBase.Cast( GetGame().GetPlayer() ) );
            }
        }
    }
References CanAddEntityIntoHands(), GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), GetPlayer(), name, and string::Replace().
Referenced by OnHandsPanelDropReceived().
OnShow()
override void HandsArea::OnShow () inline private
Definition at line 93 of file handsarea.c.
    {
        super.OnShow();
        m_HandsContainer.OnShow();
    }
References m_HandsContainer, and HandsContainer::OnShow().
Refresh()
override void HandsArea::Refresh () inline private
Definition at line 99 of file handsarea.c.
    {
        UpdateSelectionIcons();
        m_ShouldChangeSize = true;
    }
References m_ShouldChangeSize, and UpdateSelectionIcons().
Referenced by Refresh(), and Reset().
SetLayoutName()
override void HandsArea::SetLayoutName () inline private
Definition at line 83 of file handsarea.c.
    {
        m_LayoutName = WidgetLayoutName.HandsArea;
    }
References WidgetLayoutName::HandsArea.
SetParentWidget()
override void HandsArea::SetParentWidget () inline private
Definition at line 88 of file handsarea.c.
    {
        m_ParentWidget = m_Parent.GetMainWidget().FindAnyWidget( "HandsPanel" );
    }
References m_Parent.
UpdateInterval()
override void HandsArea::UpdateInterval () inline private
Definition at line 54 of file handsarea.c.
    {
        if (!m_Scroller.IsScrollbarVisible())
        {
            m_Scroller.VScrollToPos01(0.0);
        }
        else if (m_Scroller.GetVScrollPos01() > 1.0)
        {
            m_Scroller.VScrollToPos01(1.0);
        }
        m_HandsContainer.UpdateInterval();
        float x, y;
        float x2, y2;
        m_Scroller.GetScreenSize( x, y );
        m_MainWidget.GetScreenSize( x2, y2 );
        if ( y2 != y )
            m_ShouldChangeSize = true;
        bool changed_size;
        if ( m_ShouldChangeSize && m_HandsResizer.ResizeParentToChild( changed_size, InventoryMenu.GetHeight() * 0.5 ) )
            m_Scroller.SetAlpha( 0.3921 );
        else
            m_Scroller.SetAlpha( 0 );
        if ( changed_size )
            m_ShouldChangeSize = false;
    }
References InventoryMenu(), m_HandsContainer, m_HandsResizer, m_Scroller, m_ShouldChangeSize, HandsContainer::UpdateInterval(), x, and y.
Referenced by UpdateInterval().
UpdateSelectionIcons()
override void HandsArea::UpdateSelectionIcons () inline private
Definition at line 47 of file handsarea.c.
    {
        #ifdef PLATFORM_CONSOLE
        ScrollToActiveContainer();
        #endif
    }
Referenced by Refresh().
Member Data Documentation
m_HandsContainer
protected ref HandsContainer HandsArea::m_HandsContainer private
Definition at line 4 of file handsarea.c.
Referenced by HandsArea(), OnShow(), and UpdateInterval().
m_HandsResizer
protected ref SizeToChild HandsArea::m_HandsResizer private
Definition at line 5 of file handsarea.c.
Referenced by HandsArea(), and UpdateInterval().
m_Scroller
protected ScrollWidget HandsArea::m_Scroller private
Definition at line 3 of file handsarea.c.
Referenced by GetScrollWidget(), HandsArea(), and UpdateInterval().
m_ShouldChangeSize
protected bool HandsArea::m_ShouldChangeSize = true private
Definition at line 7 of file handsarea.c.
Referenced by Refresh(), and UpdateInterval().