DayzKode: PlayerPreview Class Reference
PlayerPreview Class Reference
Private Member Functions
bool MouseButtonDown (Widget w, int x, int y, int button)
bool MouseWheel (Widget w, int x, int y, int wheel)
void PlayerPreview (LayoutHolder parent)
void RefreshPlayerPreview ()
override void UpdateInterval ()
void UpdateRotation (int mouse_x, int mouse_y, bool is_dragging)
void UpdateScale ()
Private Attributes
protected vector m_CharacterOrientation
protected ref PlayerPreviewWidget m_CharacterPanelWidget
protected int m_CharacterRotationX
protected int m_CharacterRotationY
protected int m_CharacterScaleDelta
protected bool m_IsHolding
Detailed Description
Definition at line 1 of file playerpreview.c.
Constructor & Destructor Documentation
PlayerPreview()
void PlayerPreview::PlayerPreview (LayoutHolder parent) inline private
Definition at line 11 of file playerpreview.c.
    {
        m_CharacterPanelWidget = PlayerPreviewWidget.Cast( m_Parent.GetMainWidget().FindAnyWidget( "CharacterPanelWidget" ) );
        WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( m_Parent.GetMainWidget().FindAnyWidget( "CharacterPanel" ),  this, "MouseButtonDown" );
        WidgetEventHandler.GetInstance().RegisterOnMouseWheel( m_Parent.GetMainWidget().FindAnyWidget( "CharacterPanel" ),  this, "MouseWheel" );
        m_CharacterScaleDelta = 1;
        m_CharacterPanelWidget.SetPlayer( GetGame().GetPlayer() );
        m_CharacterPanelWidget.SetModelPosition( "0 0 0.605" );
        m_CharacterPanelWidget.SetSize( 1.34, 1.34 );  // default scale
        UpdateScale();
    }
References GetGame(), WidgetEventHandler::GetInstance(), GetPlayer(), m_CharacterPanelWidget, m_CharacterScaleDelta, m_Parent, WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseWheel(), PlayerPreviewWidget::SetModelPosition(), PlayerPreviewWidget::SetPlayer(), and UpdateScale().
Member Function Documentation
MouseButtonDown()
bool PlayerPreview::MouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 69 of file playerpreview.c.
    {
        g_Game.GetMousePos( m_CharacterRotationX, m_CharacterRotationY );
        m_IsHolding = true;
        return true;
    }
References g_Game, m_CharacterRotationX, m_CharacterRotationY, and m_IsHolding.
MouseWheel()
bool PlayerPreview::MouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 76 of file playerpreview.c.
    {
        m_CharacterScaleDelta = wheel;
        UpdateScale();
        return true;
    }
References m_CharacterScaleDelta, and UpdateScale().
RefreshPlayerPreview()
void PlayerPreview::RefreshPlayerPreview () inline private
Definition at line 25 of file playerpreview.c.
    {
        m_CharacterPanelWidget.Refresh();
    }
References m_CharacterPanelWidget, and PlayerPreviewWidget::Refresh().
Referenced by OnShow().
UpdateInterval()
override void PlayerPreview::UpdateInterval () inline private
Definition at line 83 of file playerpreview.c.
    {
        // item in hands update
        m_CharacterPanelWidget.UpdateItemInHands(GetGame().GetPlayer().GetHumanInventory().GetEntityInHands());
        PlayerBase realPlayer = PlayerBase.Cast(GetGame().GetPlayer());
        DayZPlayer dummyPlayer = m_CharacterPanelWidget.GetDummyPlayer();
        if ( realPlayer && dummyPlayer )
        {
            // injury animation update
            HumanCommandAdditives hca = dummyPlayer.GetCommandModifier_Additives();
            //dummyPlayer.UpdateDummyPlayerProxyVisibility(realPlayer.FindAttachmentBySlotName("Shoulder"), realPlayer.FindAttachmentBySlotName("Melee"));
            if ( hca && realPlayer.m_InjuryHandler )
                hca.SetInjured(realPlayer.m_InjuryHandler.GetInjuryAnimValue(), realPlayer.m_InjuryHandler.IsInjuryAnimEnabled());
        }
        if ( m_IsHolding )
        {
            int mouse_x;
            int mouse_y;
            GetMousePos(mouse_x, mouse_y);
            if ( GetMouseState(MouseState.LEFT) & 0x80000000 )
            {
                UpdateRotation( mouse_x, mouse_y, true );
            }
            else
            {
                UpdateRotation( mouse_x, mouse_y, false );
                m_IsHolding = false;
            }
        }
    }
References PlayerPreviewWidget::GetDummyPlayer(), GetGame(), GetMousePos(), GetMouseState(), GetPlayer(), HumanCommandAdditives(), m_CharacterPanelWidget, m_IsHolding, PlayerPreviewWidget::UpdateItemInHands(), and UpdateRotation().
Referenced by UpdateInterval().
UpdateRotation()
void PlayerPreview::UpdateRotation (int mouse_x, int mouse_y, bool is_dragging) inline private
Definition at line 30 of file playerpreview.c.
    {
        if ( m_CharacterPanelWidget )
        {
            vector orientation = m_CharacterOrientation;
            orientation[1] = orientation[1] - ( m_CharacterRotationX - mouse_x );
            m_CharacterPanelWidget.SetModelOrientation( orientation );
            if ( !is_dragging )
            {
                m_CharacterOrientation = orientation;
            }
        }
    }
References m_CharacterOrientation, m_CharacterPanelWidget, m_CharacterRotationX, and PlayerPreviewWidget::SetModelOrientation().
Referenced by UpdateInterval().
UpdateScale()
void PlayerPreview::UpdateScale () inline private
Definition at line 46 of file playerpreview.c.
    {
        if ( m_CharacterPanelWidget )
        {
            float w, h;
            m_CharacterPanelWidget.GetSize( w, h );
            w = w + ( m_CharacterScaleDelta / 25 );
            h = h + ( m_CharacterScaleDelta / 25 );
            if ( w > 0.62 && w < 3 )
            {
                m_CharacterPanelWidget.SetSize( w, h );
            }
            else if ( w < 0.62 )
            {
                m_CharacterPanelWidget.SetSize( 0.62, 0.62 );
            }
            else if ( w > 3 )
            {
                m_CharacterPanelWidget.SetSize( 3, 3 );
            }
        }
    }
References m_CharacterPanelWidget, and m_CharacterScaleDelta.
Referenced by MouseWheel(), and PlayerPreview().
Member Data Documentation
m_CharacterOrientation
protected vector PlayerPreview::m_CharacterOrientation private
Definition at line 8 of file playerpreview.c.
Referenced by UpdateRotation().
m_CharacterPanelWidget
protected ref PlayerPreviewWidget PlayerPreview::m_CharacterPanelWidget private
Definition at line 3 of file playerpreview.c.
Referenced by PlayerPreview(), RefreshPlayerPreview(), UpdateInterval(), UpdateRotation(), and UpdateScale().
m_CharacterRotationX
protected int PlayerPreview::m_CharacterRotationX private
Definition at line 5 of file playerpreview.c.
Referenced by MouseButtonDown(), and UpdateRotation().
m_CharacterRotationY
protected int PlayerPreview::m_CharacterRotationY private
Definition at line 6 of file playerpreview.c.
Referenced by MouseButtonDown().
m_CharacterScaleDelta
protected int PlayerPreview::m_CharacterScaleDelta private
Definition at line 7 of file playerpreview.c.
Referenced by MouseWheel(), PlayerPreview(), and UpdateScale().
m_IsHolding
protected bool PlayerPreview::m_IsHolding private
Definition at line 9 of file playerpreview.c.
Referenced by MouseButtonDown(), and UpdateInterval().