DayzKode: QuantityConversions Class Reference
QuantityConversions Class Reference
Static Private Member Functions
static float GetItemQuantity (InventoryItem item)
static void GetItemQuantity (InventoryItem item, out float q_cur, out float q_min, out float q_max)
static float GetItemQuantityMax (InventoryItem item)
static string GetItemQuantityText (EntityAI item, bool showMax=false)
static int HasItemQuantity (notnull EntityAI item)
Detailed Description
Definition at line 1 of file quantityconversions.c.
Member Function Documentation
GetItemQuantity() [1/2]
static float QuantityConversions::GetItemQuantity (InventoryItem item) inline static private
Definition at line 72 of file quantityconversions.c.
    {
        float quantity = 0;
        if ( item.IsInherited(InventoryItem))
        {
            ItemBase item_base;
            Class.CastTo(item_base, item);
            if (item_base)
            {
                if (item.IsMagazine())
                {
                    Magazine magazine_item;
                    Class.CastTo(magazine_item, item);
                    quantity = magazine_item.GetAmmoCount();
                }
                else
                {
                    quantity = item_base.GetQuantity();
                }
            }
        }
        return quantity;
    }
References Class::CastTo().
Referenced by InventoryGridController::GetItemQuantity(), ScriptedWidgetEventHandler::GetItemQuantity(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().
GetItemQuantity() [2/2]
static void QuantityConversions::GetItemQuantity (InventoryItem item, out float q_cur, out float q_min, out float q_max) inline static private
Definition at line 120 of file quantityconversions.c.
    {
        if ( item.IsInherited( InventoryItem ) )
        {
            ItemBase item_base;
            Class.CastTo(item_base, item);
            if ( item.IsMagazine() )
            {
                Magazine magazine_item;
                Class.CastTo(magazine_item, item);
                q_cur = magazine_item.GetAmmoCount();
                q_min = 0;
                q_max = magazine_item.GetAmmoMax();
            }
            else
            {
                q_cur = item_base.GetQuantity();
                q_min = item_base.GetQuantityMin();
                q_max = item_base.GetQuantityMax();
            }
        }
    }
References Class::CastTo().
GetItemQuantityMax()
static float QuantityConversions::GetItemQuantityMax (InventoryItem item) inline static private
Definition at line 96 of file quantityconversions.c.
    {
        float quantity = 0;
        if (item.IsInherited(InventoryItem))
        {
            ItemBase item_base;
            Class.CastTo(item_base, item);
            if (item_base)
            {
                if (item.IsMagazine())
                {
                    Magazine magazine_item;
                    Class.CastTo(magazine_item, item);
                    quantity = magazine_item.GetAmmoMax();
                }
                else
                {
                    quantity = item_base.GetQuantityMax();
                }
            }
        }
        return quantity;
    }
References Class::CastTo().
Referenced by Icon::SetQuantity(), and SlotsIcon::SetQuantity().
GetItemQuantityText()
static string QuantityConversions::GetItemQuantityText (EntityAI item, bool showMax = false) inline static private
Definition at line 3 of file quantityconversions.c.
    {
        string quantity_text = "";
        if ( item.IsInherited( InventoryItem) )
        {
            ItemBase item_base;
            Class.CastTo(item_base, item);
            float quantity = item_base.GetQuantity();
            int ammo;
            if ( item.IsMagazine() )
            {
                Magazine magazine_item;
                Class.CastTo(magazine_item, item);
                ammo = magazine_item.GetAmmoCount();
                return ammo.ToString();
            }
            else if ( item.IsInherited( ItemBook) )
            {
                return "";
            }
            int stack_max = item.GetQuantityMax();
            //int max = item.ConfigGetInt("varQuantityMax");
            //string unit = item.ConfigGetString("stackedUnit");
            if (stack_max > 0)
            {
                if (stack_max == 1)
                {
                    if (quantity > 1)
                    {
                        if (showMax)
                            quantity_text = string.Format("%1/%2", quantity.ToString(), stack_max.ToString() );
                        //quantity_text = string.Format("%i/%i", quantity, stack_max );
                        else
                            quantity_text = quantity.ToString();
                    }
                    else
                    {
                        quantity_text = "";
                    }
                }
                else
                {
                    if (showMax)
                        quantity_text = string.Format("%1/%2", quantity.ToString(), stack_max.ToString() );
                        //quantity_text = string.Format("%i/%i", quantity, stack_max );
                    else
                        quantity_text = quantity.ToString();
                    // if (unit == "ml")
                    // {
                    //  float liters = round(quantity / 1000.0);
                    //  if ( quantity < 2000 )
                    //  {
                    //      liters =  ( round( (quantity / 100.0) ) ) / 10;
                    //  }
                    //  quantity_text = ftoa(liters) + "l";
                    // }
                    // else
                    // {
                    //  quantity_text = itoa(quantity) + unit;
                    // }
                }
            }
        }
        return quantity_text;
    }
References Class::CastTo(), string::Format(), bool::ToString(), float::ToString(), and string::ToString().
Referenced by InventoryGridController::GetItemQuantityText(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().
HasItemQuantity()
static int QuantityConversions::HasItemQuantity (notnull EntityAI item) inline static private
Definition at line 143 of file quantityconversions.c.
    {
        ItemBase ib;
        if ( Class.CastTo(ib, item) )
        {
            if ( item.IsMagazine() )
                return QUANTITY_COUNT;
            if ( !ib.m_CanShowQuantity )
                return QUANTITY_HIDDEN;
            int max = item.GetQuantityMax();
            if ( max > 0 )
            {
                if ( ib.m_HasQuantityBar )
                {
                    return QUANTITY_PROGRESS;
                }
                else
                {
                    if (max == 1)
                    {
                        return QUANTITY_HIDDEN;
                    }
                    else
                    {
                        return QUANTITY_COUNT;
                    }
                }
            }
        }
        return QUANTITY_HIDDEN;
    }
References Class::CastTo(), QUANTITY_COUNT, QUANTITY_HIDDEN, and QUANTITY_PROGRESS.
Referenced by SlotsIcon::CheckHasQuantity(), Icon::CheckHasQuantityEx(), ScriptedWidgetEventHandler::GetItemQuantity(), InventoryGridController::HasItemQuantity(), Attachments::IsItemActive(), HandsContainer::IsItemActive(), Attachments::IsItemWithQuantityActive(), Container::IsItemWithQuantityActive(), HandsContainer::IsItemWithQuantityActive(), PlayerContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), ZombieContainer::IsItemWithQuantityActive(), Icon::SetQuantity(), SlotsIcon::SetQuantity(), and UIScriptedMenu::UpdateQuickbarItemCard().