DayzKode: KuruShake Class Reference
KuruShake Class Reference
Private Member Functions
void KuruShake (PlayerBase player, float amount)
void Update (float delta_time, out float pos_x, out float pos_y)
Private Attributes
ref array< vector > m_Curve = new array<vector>
PlayerBase m_Player
float m_RelativeTime
float m_RelativeTime2
float m_ShakeStrength
float m_Time
float m_Time2
const float RANDOM_RANGE_DEVIATION = 0.50
const float RANDOM_RANGE_POINT = 1
const float SHAKE_DURATION_PHASE1 = 0.01
const float SHAKE_STRENGTH_MAX = 5
const float SHAKE_STRENGTH_MIN = 1
Detailed Description
Definition at line 1 of file kurushake.c.
Constructor & Destructor Documentation
KuruShake()
void KuruShake::KuruShake (PlayerBase player, float amount) inline private
Definition at line 19 of file kurushake.c.
    {
        vector pos1;
        int seed = Math.Randomize(player.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSGeneric,0,10000));
        Math.RandomFloat(-RANDOM_RANGE_POINT,RANDOM_RANGE_POINT);//throw away
        m_ShakeStrength = Math.Lerp(SHAKE_STRENGTH_MIN, SHAKE_STRENGTH_MAX, amount);
        pos1[0] = Math.RandomFloat(-RANDOM_RANGE_POINT,RANDOM_RANGE_POINT);
        pos1[1] = Math.RandomFloat(-RANDOM_RANGE_POINT,RANDOM_RANGE_POINT);
        pos1.Normalize();
        pos1 = pos1 * m_ShakeStrength;
        vector pos2;
        pos2[0] = pos1[0] + Math.RandomFloat(-RANDOM_RANGE_DEVIATION,RANDOM_RANGE_DEVIATION) + pos1[0];
        pos2[1] = pos1[1] + Math.RandomFloat(-RANDOM_RANGE_DEVIATION,RANDOM_RANGE_DEVIATION) + pos1[1];
        m_Curve.Insert("0 0 0");
        m_Curve.Insert(pos1);
        m_Curve.Insert(pos2);
        /*
        Print("==========================");
        for(int i = 0; i < m_Curve.Count(); i++)
        {
            Print(m_Curve[i]);
        }
        Print("==========================");
        */
    }
References Math::Lerp(), m_Curve, m_ShakeStrength, vector::Normalize(), RANDOM_RANGE_DEVIATION, RANDOM_RANGE_POINT, Math::RandomFloat(), Math::Randomize(), SHAKE_STRENGTH_MAX, and SHAKE_STRENGTH_MIN.
Member Function Documentation
Update()
void KuruShake::Update (float delta_time, out float pos_x, out float pos_y) inline private
Definition at line 48 of file kurushake.c.
    {
        if(m_RelativeTime < 0.99)
        {
            m_Time += delta_time;
            m_RelativeTime = Math.InverseLerp(0, SHAKE_DURATION_PHASE1, m_Time);
            //m_RelativeTime = m_RelativeTime - 0.01;
            m_RelativeTime = Easing.EaseInQuint(m_RelativeTime);
            vector pos = Math3D.Curve(ECurveType.CatmullRom, m_RelativeTime, m_Curve);
            pos_x = pos[0];
            pos_y = pos[1];
        }
        else
        {
            m_Time2 += delta_time * 1;
            m_RelativeTime2 = 1 -  m_Time2;
            m_RelativeTime2 = Easing.EaseInQuint(m_RelativeTime2);
            vector pos2 = Math3D.Curve(ECurveType.CatmullRom, m_RelativeTime2, m_Curve);
            pos_x = pos2[0];
            pos_y = pos2[1];
        }
        if(m_Time2 >= 0.99)
        {
            delete this;
        }
    }
References Math3D::Curve(), Easing::EaseInQuint(), Math::InverseLerp(), m_Curve, m_RelativeTime, m_RelativeTime2, m_Time, m_Time2, and SHAKE_DURATION_PHASE1.
Referenced by DayZPlayerImplementAiming::ProcessAimFilters().
Member Data Documentation
m_Curve
ref array<vector> KuruShake::m_Curve = new array<vector> private
Definition at line 17 of file kurushake.c.
Referenced by KuruShake(), and Update().
m_Player
PlayerBase KuruShake::m_Player private
Definition at line 9 of file kurushake.c.
m_RelativeTime
float KuruShake::m_RelativeTime private
Definition at line 12 of file kurushake.c.
Referenced by Update().
m_RelativeTime2
float KuruShake::m_RelativeTime2 private
Definition at line 13 of file kurushake.c.
Referenced by Update().
m_ShakeStrength
float KuruShake::m_ShakeStrength private
Definition at line 14 of file kurushake.c.
Referenced by KuruShake().
m_Time
float KuruShake::m_Time private
Definition at line 10 of file kurushake.c.
Referenced by Update().
m_Time2
float KuruShake::m_Time2 private
Definition at line 11 of file kurushake.c.
Referenced by Update().
RANDOM_RANGE_DEVIATION
const float KuruShake::RANDOM_RANGE_DEVIATION = 0.50 private
Definition at line 4 of file kurushake.c.
Referenced by KuruShake().
RANDOM_RANGE_POINT
const float KuruShake::RANDOM_RANGE_POINT = 1 private
Definition at line 3 of file kurushake.c.
Referenced by KuruShake().
SHAKE_DURATION_PHASE1
const float KuruShake::SHAKE_DURATION_PHASE1 = 0.01 private
Definition at line 5 of file kurushake.c.
Referenced by Update().
SHAKE_STRENGTH_MAX
const float KuruShake::SHAKE_STRENGTH_MAX = 5 private
Definition at line 7 of file kurushake.c.
Referenced by KuruShake().
SHAKE_STRENGTH_MIN
const float KuruShake::SHAKE_STRENGTH_MIN = 1 private
Definition at line 6 of file kurushake.c.
Referenced by KuruShake().