DayzKode: Weather Class Reference
Weather Class Reference
Private Member Functions
proto native Fog GetFog ()
Returns a fog phenomenon object.
bool GetMissionWeather ()
proto native Overcast GetOvercast ()
Returns an overcast phenomenon object.
proto native Rain GetRain ()
Returns a rain phenomenon object.
proto native float GetTime ()
Returns actual time from start of a server (how many seconds elapsed from server start).
proto native vector GetWind ()
Returns wind vector (direction and speed as length of the vector).
proto void GetWindFunctionParams (out float fnMin, out float fnMax, out float fnSpeed)
Reads function parameters that controls the wind behaviour (change in time).
proto native float GetWindMaximumSpeed ()
Returns maximal wind speed in metre per second.
proto native float GetWindSpeed ()
Returns actual wind speed in metre per second.
void MissionWeather (bool use)
proto native void SetRainThresholds (float tMin, float tMax, float tTime)
Sets overcast threshold values for rain phenomena.
proto native void SetStorm (float density, float threshold, float timeOut)
Sets the thunderstorm properties.
proto native void SetWind (vector wind)
Sets the wind vector (direction and speed as length of the vector).
proto native void SetWindFunctionParams (float fnMin, float fnMax, float fnSpeed)
Sets function parameters that controls the wind behaviour (change in time).
proto native void SetWindMaximumSpeed (float maxSpeed)
Sets the maximal wind speed in metre per second.
proto native void SetWindSpeed (float speed)
Sets the actual wind speed in metre per second.
proto native void SuppressLightningSimulation (bool state)
enables/disables thunderbolt simulation on client (together with sounds)
private void Weather ()
private void ~Weather ()
Private Attributes
protected bool m_missionWeather
Detailed Description
Weather controller
Definition at line 154 of file weather.c.
Constructor & Destructor Documentation
Weather()
private void Weather::Weather () inline private
Definition at line 158 of file weather.c.
    {
        m_missionWeather = false;
    }
References m_missionWeather.
~Weather()
private void Weather::~Weather () inline private
Definition at line 163 of file weather.c.
{}
Member Function Documentation
GetFog()
proto native Fog Weather::GetFog () private
Returns a fog phenomenon object.
Referenced by Environment::CollectAndSetEnvironmentData(), DayZIntroScene::DayZIntroScene(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), UIPopupScript::OnOpen(), UIPopupScript::ResetSliders(), and SceneData::SetInitFog().
GetMissionWeather()
bool Weather::GetMissionWeather () inline private
Definition at line 249 of file weather.c.
    {
        return m_missionWeather;
    }
References m_missionWeather.
Referenced by WeatherPhenomenon::OnBeforeChange().
GetOvercast()
proto native Overcast Weather::GetOvercast () private
Returns an overcast phenomenon object.
Referenced by Environment::CollectAndSetEnvironmentData(), DayZIntroScene::DayZIntroScene(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), UIPopupScript::OnOpen(), UIPopupScript::ResetSliders(), and SceneData::SetInitOvercast().
GetRain()
proto native Rain Weather::GetRain () private
Returns a rain phenomenon object.
Referenced by ItemBase::CheckRainTick(), Environment::CollectAndSetEnvironmentData(), Cooling(), DayZIntroScene::DayZIntroScene(), Heating(), ItemBase::Init(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), UIPopupScript::OnOpen(), RainProcurementManager::RainProcurementCheck(), UIPopupScript::ResetSliders(), and SceneData::SetInitRain().
GetTime()
proto native float Weather::GetTime () private
Returns actual time from start of a server (how many seconds elapsed from server start).
GetWind()
proto native vector Weather::GetWind () private
Returns wind vector (direction and speed as length of the vector).
GetWindFunctionParams()
proto void Weather::GetWindFunctionParams (out float fnMin, out float fnMax, out float fnSpeed) private
Reads function parameters that controls the wind behaviour (change in time).
Parameters
fnMin Function relative minimum (in range <0, 1>).
fnMax Function relative maximum (in range <0, 1>).
fnSpeed Controls speed of change of function value.
GetWindMaximumSpeed()
proto native float Weather::GetWindMaximumSpeed () private
Returns maximal wind speed in metre per second.
Note
By default this value is 10 m/s but it can be overridden in script on mission initialization.
Referenced by Environment::CollectAndSetEnvironmentData(), IsWindy(), UIPopupScript::OnChange(), and UIPopupScript::ResetSliders().
GetWindSpeed()
proto native float Weather::GetWindSpeed () private
Returns actual wind speed in metre per second.
Note
Wind is changing continuously in time, so the returned value may not stand for too long.
Referenced by Environment::CollectAndSetEnvironmentData(), IsWindy(), UIPopupScript::OnOpen(), and UIPopupScript::ResetSliders().
MissionWeather()
void Weather::MissionWeather (bool use) inline private
Definition at line 244 of file weather.c.
    {
        m_missionWeather = use;
    }
References m_missionWeather.
SetRainThresholds()
proto native void Weather::SetRainThresholds (float tMin, float tMax, float tTime) private
Sets overcast threshold values for rain phenomena.
Rain can start only if actual overcast value is in given range of <tMin, tMax>. If it's already raining and actual overcast value gets out of given range then rain will stop in given tTime seconds.
Default values are: tMin = 0.6 tMax = 1 tTime = 30
Parameters
tMin Minimal overcast value (in range <0, 1>).
tMax Maximal overcast value (in range <0, 1>).
tTime Time in seconds when it stops raining.
SetStorm()
proto native void Weather::SetStorm (float density, float threshold, float timeOut) private
Sets the thunderstorm properties.
Parameters
density A value in <0, 1> range where 0 means no thunderstorms at all and 1 means thunderstorm every time it gets cloudy.
threshold The overcast value that must be exceeded so that lightning can appear.
timeOut A minimal time in seconds between lightning during thunderstorm.
Referenced by DayZIntroScene::DayZIntroScene().
SetWind()
proto native void Weather::SetWind (vector wind) private
Sets the wind vector (direction and speed as length of the vector).
SetWindFunctionParams()
proto native void Weather::SetWindFunctionParams (float fnMin, float fnMax, float fnSpeed) private
Sets function parameters that controls the wind behaviour (change in time).
Parameters
fnMin Function relative minimum (in range <0, 1>).
fnMax Function relative maximum (in range <0, 1>).
fnSpeed Controls speed of change of function value.
Referenced by DayZIntroScene::DayZIntroScene().
SetWindMaximumSpeed()
proto native void Weather::SetWindMaximumSpeed (float maxSpeed) private
Sets the maximal wind speed in metre per second.
Referenced by DayZIntroScene::DayZIntroScene().
SetWindSpeed()
proto native void Weather::SetWindSpeed (float speed) private
Sets the actual wind speed in metre per second.
Note
Wind is changing continuously in time, so the returned value may not stand for too long. Minimum speed for wind is 0.1 m/s.
Referenced by DayZIntroScene::DayZIntroScene(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::ResetSliders(), and SceneData::SetInitWindForce().
SuppressLightningSimulation()
proto native void Weather::SuppressLightningSimulation (bool state) private
enables/disables thunderbolt simulation on client (together with sounds)
Referenced by OnUndergroundPresenceUpdate(), and ~UndergroundHandlerClient().
Member Data Documentation
m_missionWeather
protected bool Weather::m_missionWeather private
Definition at line 156 of file weather.c.
Referenced by GetMissionWeather(), MissionWeather(), and Weather().