DayzKode: SyncEvents Class Reference
SyncEvents Class Reference
Static Private Member Functions
static void Event_OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
static void OnSyncEvent (ESyncEvent event_type, SyncData data, Object target)
static void RegisterEvents ()
static void SendEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
static void SendPlayerIgnatedFireplace (Man player, EFireIgniteType ignite_type)
static void SendPlayerList ()
static private void SendSyncEvent (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data=null, bool guaranteed=true, PlayerIdentity player_target=null)
static private void SendSyncEventEx (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data=null, bool guaranteed=true, Man recipient=null)
Detailed Description
Definition at line 1 of file syncevents.c.
Member Function Documentation
Event_OnRPC()
static void SyncEvents::Event_OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx) inline static private
Definition at line 11 of file syncevents.c.
    {
        if ( rpc_type == ERPCs.RPC_SYNC_EVENT && GetGame() && GetGame().IsMultiplayer() && GetGame().IsClient() )
        {
            Param2<ESyncEvent, ref SyncData> event_data = new Param2<ESyncEvent, ref SyncData>( -1, null );
            if ( ctx.Read( event_data ) )
            {
                OnSyncEvent( event_data.param1, event_data.param2, target );
            }
        }
    }
References GetGame(), OnSyncEvent(), and Serializer::Read().
OnSyncEvent()
static void SyncEvents::OnSyncEvent (ESyncEvent event_type, SyncData data, Object target) inline static private
Definition at line 24 of file syncevents.c.
    {
        switch ( event_type )
        {
            case ESyncEvent.PlayerList:
            {
                ClientData.SyncEvent_OnRecievedPlayerList( data.m_ServerPlayerList );
                break;
            }
            case ESyncEvent.EntityKill:
            {
                ClientData.SyncEvent_OnEntityKilled( data.m_EntityKill );
                break;
            }
            case ESyncEvent.PlayerIgnateFireplayce:
            {
                ClientData.SyncEvent_OnPlayerIgnitedFireplace( data.m_SyncInt );
                break;
            }
        }
    }
References SyncData::m_EntityKill, SyncData::m_ServerPlayerList, SyncData::m_SyncInt, ClientData::SyncEvent_OnEntityKilled, ClientData::SyncEvent_OnPlayerIgnitedFireplace, and ClientData::SyncEvent_OnRecievedPlayerList().
Referenced by Event_OnRPC().
RegisterEvents()
static void SyncEvents::RegisterEvents () inline static private
Definition at line 3 of file syncevents.c.
    {
        DayZGame dz_game = DayZGame.Cast( GetGame() );
        dz_game.Event_OnRPC.Insert( Event_OnRPC );
        Print("SyncEvents -> RegisterEvents");
    }
References DayZGame(), Event_OnRPC, GetGame(), and Print().
Referenced by MissionBase::MissionGameplay().
SendEntityKilled()
static void SyncEvents::SendEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline static private
Definition at line 55 of file syncevents.c.
    {
        if ( (victim && victim.IsPlayer()) || (killer && killer.IsPlayer()) )
        {
            SyncData data = new SyncData;
            data.m_EntityKill = new SyncEntityKillInfo;
            data.m_EntityKill.m_EntityVictim    = victim;
            data.m_EntityKill.m_EntityKiller    = killer;
            data.m_EntityKill.m_EntitySource    = source;
            data.m_EntityKill.m_IsHeadShot      = is_headshot;
            Man recipient;
            if ( killer && killer.IsPlayer() && victim.GetID() != killer.GetID() )
            {
                recipient = Man.Cast(killer);
            }
            else if ( victim && victim.IsPlayer() )
            {
                recipient = Man.Cast(victim);
            }
            SendSyncEventEx( ERPCs.RPC_SYNC_EVENT, ESyncEvent.EntityKill, data, true, recipient );
        }
    }
References SyncData::m_EntityKill, SyncEntityKillInfo::m_EntityKiller, SyncEntityKillInfo::m_EntitySource, SyncEntityKillInfo::m_EntityVictim, SyncEntityKillInfo::m_IsHeadShot, and SendSyncEventEx().
Referenced by ManBase::OnCommandHandlerTick().
SendPlayerIgnatedFireplace()
static void SyncEvents::SendPlayerIgnatedFireplace (Man player, EFireIgniteType ignite_type) inline static private
Definition at line 82 of file syncevents.c.
    {
        SyncData data = new SyncData;
        data.m_SyncInt = ignite_type;
        SendSyncEvent( ERPCs.RPC_SYNC_EVENT, ESyncEvent.PlayerIgnateFireplayce, data, true, player.GetIdentity() );
    }
References SyncData::m_SyncInt, and SendSyncEvent().
Referenced by FireplaceBase::OnIgnitedThis().
SendPlayerList()
static void SyncEvents::SendPlayerList () inline static private
Definition at line 46 of file syncevents.c.
    {
        SyncData data = new SyncData;
        data.m_ServerPlayerList = new SyncPlayerList;
        data.m_ServerPlayerList.CreatePlayerList();
        SendSyncEvent( ERPCs.RPC_SYNC_EVENT, ESyncEvent.PlayerList, data, true );
    }
References SyncPlayerList::CreatePlayerList(), SyncData::m_ServerPlayerList, and SendSyncEvent().
Referenced by MissionBase::OnEvent(), and MissionBase::PlayerDisconnected().
SendSyncEvent()
static private void SyncEvents::SendSyncEvent (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data = null, bool guaranteed = true, PlayerIdentity player_target = null) inline static private
Definition at line 90 of file syncevents.c.
    {
        Param2<ESyncEvent, ref SyncData> event_data = new Param2<ESyncEvent, ref SyncData>( sync_event_type, data );
        if ( !player_target )
        {
            GetGame().RPCSingleParam( null, rpc_event_id, event_data, guaranteed );
        }
        else
        {
            GetGame().RPCSingleParam( null, rpc_event_id, event_data, guaranteed, player_target );
        }
    }
References GetGame(), and CGame::RPCSingleParam().
Referenced by SendPlayerIgnatedFireplace(), SendPlayerList(), and SendSyncEventEx().
SendSyncEventEx()
static private void SyncEvents::SendSyncEventEx (ERPCs rpc_event_id, ESyncEvent sync_event_type, SyncData data = null, bool guaranteed = true, Man recipient = null) inline static private
Definition at line 103 of file syncevents.c.
    {
        SendSyncEvent(rpc_event_id, sync_event_type, data, guaranteed, recipient.GetIdentity());
    }
References SendSyncEvent().
Referenced by SendEntityKilled().