DayzKode: SyncedValueModifier Class Reference
SyncedValueModifier Class Reference
Private Member Functions
bool GetActive ()
int GetID ()
bool GetLocked ()
string GetName ()
void SyncedValueModifier (int id, string name, bool active, bool locked)
Private Attributes
bool m_Active
int m_ID
bool m_Locked
string m_Name
Detailed Description
Definition at line 67 of file syncedvalue.c.
Constructor & Destructor Documentation
SyncedValueModifier()
void SyncedValueModifier::SyncedValueModifier (int id, string name, bool active, bool locked) inline private
Definition at line 74 of file syncedvalue.c.
    {
        m_Name = name;
        m_ID = id;
        m_Locked = locked;
        m_Active = active;
    }
References m_Active, m_ID, m_Locked, m_Name, and name.
Member Function Documentation
GetActive()
bool SyncedValueModifier::GetActive () inline private
Definition at line 97 of file syncedvalue.c.
    {
        return m_Active;
    }
References m_Active.
Referenced by SetModifiers().
GetID()
int SyncedValueModifier::GetID () inline private
Definition at line 87 of file syncedvalue.c.
    {
        return m_ID;
    }
References m_ID.
Referenced by SetModifiers().
GetLocked()
bool SyncedValueModifier::GetLocked () inline private
Definition at line 92 of file syncedvalue.c.
    {
        return m_Locked;
    }
References m_Locked.
Referenced by SetModifiers().
GetName()
string SyncedValueModifier::GetName () inline private
Definition at line 82 of file syncedvalue.c.
    {
        return m_Name;
    }
References m_Name.
Referenced by SetModifiers().
Member Data Documentation
m_Active
bool SyncedValueModifier::m_Active private
Definition at line 72 of file syncedvalue.c.
Referenced by GetActive(), and SyncedValueModifier().
m_ID
int SyncedValueModifier::m_ID private
Definition at line 70 of file syncedvalue.c.
Referenced by GetID(), and SyncedValueModifier().
m_Locked
bool SyncedValueModifier::m_Locked private
Definition at line 71 of file syncedvalue.c.
Referenced by GetLocked(), and SyncedValueModifier().
m_Name
string SyncedValueModifier::m_Name private
Definition at line 69 of file syncedvalue.c.
Referenced by GetName(), and SyncedValueModifier().