DayzKode: EpinephrineMdfr Class Reference
EpinephrineMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int LIFETIME = 60
const float STAMINA_DEPLETION_MULTIPLIER = 0
Detailed Description
Definition at line 1 of file epinephrinemdfr.c.
Member Function Documentation
ActivateCondition()
override bool EpinephrineMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file epinephrinemdfr.c.
    {
        return false;
    }
DeactivateCondition()
override bool EpinephrineMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 47 of file epinephrinemdfr.c.
    {
        float attached_time = GetAttachedTime();
        if( attached_time >= LIFETIME )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and LIFETIME.
GetDebugText()
override string EpinephrineMdfr::GetDebugText () inline private
Definition at line 25 of file epinephrinemdfr.c.
    {
        return (LIFETIME - GetAttachedTime()).ToString();
    }
References GetAttachedTime(), LIFETIME, and string::ToString().
Init()
override void EpinephrineMdfr::Init () inline private
Definition at line 5 of file epinephrinemdfr.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_EPINEPHRINE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 1;
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void EpinephrineMdfr::OnActivate (PlayerBase player) inline private
Definition at line 30 of file epinephrinemdfr.c.
    {
        player.IncreaseHealingsCount();
        //if( player.GetNotifiersManager() ) player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        player.GiveShock(100);
        player.GetStaminaHandler().SetStamina(100);
        player.GetStaminaHandler().ActivateDepletionModifier(EStaminaMultiplierTypes.EPINEPHRINE);
    }
OnDeactivate()
override void EpinephrineMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 39 of file epinephrinemdfr.c.
    {
        //if( player.GetNotifiersManager() ) player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        player.DecreaseHealingsCount();
        //player.GetStaminaHandler().SetDepletionMultiplier(1);
        player.GetStaminaHandler().DeactivateDepletionModifier(EStaminaMultiplierTypes.EPINEPHRINE);
    }
OnReconnect()
override void EpinephrineMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 20 of file epinephrinemdfr.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void EpinephrineMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 61 of file epinephrinemdfr.c.
    {
        //player.GetStaminaHandler().SetStamina(100);
    }
Member Data Documentation
LIFETIME
const int EpinephrineMdfr::LIFETIME = 60 private
Definition at line 3 of file epinephrinemdfr.c.
Referenced by DeactivateCondition(), and GetDebugText().
STAMINA_DEPLETION_MULTIPLIER
const float EpinephrineMdfr::STAMINA_DEPLETION_MULTIPLIER = 0 private
Definition at line 4 of file epinephrinemdfr.c.
Referenced by Init().