DayzKode: TripodBase Class Reference
TripodBase Class Reference
Private Member Functions
override bool CanDetachAttachment (EntityAI parent)
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
override bool HasProxyParts ()
override void OnDebugSpawn ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void SetActions ()
Detailed Description
Definition at line 1 of file cookingstand.c.
Member Function Documentation
CanDetachAttachment()
override bool TripodBase::CanDetachAttachment (EntityAI parent) inline private
Definition at line 8 of file tripod.c.
    {
        FireplaceBase fireplace = FireplaceBase.Cast(parent);
        if(fireplace)
        {
            if ( fireplace.GetCookingEquipment() != null )
            {
                return false;
            }
        }
        return true;
    }
CanSwapEntities()
override bool TripodBase::CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination) inline private
Definition at line 21 of file tripod.c.
    {
        if (GetHierarchyParent() && GetHierarchyParent().IsFireplace() && otherItem)
        {
            if (otherItem.IsInherited(Pot) || otherItem.IsInherited(Cauldron))
            {
                return false;
            }
        }
        return true;
    }
References IsFireplace().
HasProxyParts()
override bool TripodBase::HasProxyParts () inline private
Definition at line 3 of file tripod.c.
    {
        return true;
    }
OnDebugSpawn()
override void TripodBase::OnDebugSpawn () inline private
Definition at line 34 of file tripod.c.
    {
        HideAllSelections();
        ShowSelection( "Deployed" );
    }
OnWasAttached()
override void TripodBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 48 of file tripod.c.
    {
        super.OnWasAttached(parent, slot_id);
        if (parent.IsFireplace())
        {
            HideAllSelections();
            ShowSelection( "Deployed" );
        }
    }
OnWasDetached()
override void TripodBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 58 of file tripod.c.
    {
        super.OnWasDetached(parent, slot_id);
        if (parent.IsFireplace())
        {
            HideAllSelections();
            ShowSelection( "Collapsed" );
        }
    }
SetActions()
override void TripodBase::SetActions () inline private
Definition at line 40 of file tripod.c.
    {
        super.SetActions();
        AddAction(ActionAttach);
        AddAction(ActionDetach);
    }
References ActionAttach(), ActionDetach(), and AddAction().