DayzKode: ActionCarDoorsOutside Class Reference
ActionCarDoorsOutside Class Reference
Private Member Functions
void ActionCarDoorsOutside ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
protected int m_CommandUIDPerCrewIdx [4]
protected bool m_IsOpening = true
Detailed Description
Definition at line 1 of file actioncardoorsoutside.c.
Constructor & Destructor Documentation
ActionCarDoorsOutside()
void ActionCarDoorsOutside::ActionCarDoorsOutside () inline private
Definition at line 6 of file actioncardoorsoutside.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    }
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCarDoorsOutside::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
reach check from outside of car
player is outside of vehicle
player is looking at one of the doors, can't open if obstructed
if player is in car and cannot reach doors
is in reach, should open the door
Definition at line 18 of file actioncardoorsoutside.c.
    {
        if (!IsInReach(player, target, UAMaxDistances.DEFAULT))
        {
            return false;
        }
        CarScript car = null;
        if (Class.CastTo(car, target.GetParent()))
        {
            CarDoor carDoor = CarDoor.Cast(target.GetObject());
            if (carDoor)
            {
                array<string> selections = new array<string>();
                string animSource = "";
                carDoor.GetActionComponentNameList(target.GetComponentIndex(), selections);
                for (int i = 0; i < selections.Count(); i++)
                {
                    animSource = car.GetAnimSourceFromSelection(selections[i]);
                    if (animSource != "")
                    {
                        int idx = car.GetSeatIndexFromDoor(animSource);
                        if (idx != -1 && !car.IsAreaAtDoorFree(idx))
{
                            return false;
                        }
                        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
                        float animationPhase = car.GetAnimationPhase(animSource);
                        return (m_IsOpening && animationPhase <= 0.5 ) || ( !m_IsOpening && animationPhase > 0.5);
                    }
                }
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, CarScript::GetAnimSourceFromSelection(), CarScript::GetSeatIndexFromDoor(), IsInReach(), AnimatedActionBase::m_CommandUID, and m_IsOpening.
CreateConditionComponents()
override void ActionCarDoorsOutside::CreateConditionComponents () inline private
Definition at line 12 of file actioncardoorsoutside.c.
    {
        m_ConditionItem     = new CCINone;
        m_ConditionTarget   = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
protected void ActionCarDoorsOutside::FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline private
Definition at line 106 of file actioncardoorsoutside.c.
    {
        m_CommandUIDPerCrewIdx[0] = crewIdx0;
        m_CommandUIDPerCrewIdx[1] = crewIdx1;
        m_CommandUIDPerCrewIdx[2] = crewIdx2;
        m_CommandUIDPerCrewIdx[3] = crewIdx3;
    }
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
protected void ActionCarDoorsOutside::FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline private
Definition at line 114 of file actioncardoorsoutside.c.
    {
        FillCommandUIDPerCrewIdx(evenCrewIdx0, unevenCrewIdx1, evenCrewIdx0, unevenCrewIdx1);
    }
References FillCommandUIDPerCrewIdx().
OnEndServer()
override void ActionCarDoorsOutside::OnEndServer (ActionData action_data) inline private
Definition at line 97 of file actioncardoorsoutside.c.
    {
        CarScript car = CarScript.Cast(action_data.m_Target.GetParent());
        if (car)
        {
            car.ForceUpdateLightsEnd();
        }
    }
References ActionData::m_Target.
OnStartServer()
override void ActionCarDoorsOutside::OnStartServer (ActionData action_data) inline private
Definition at line 64 of file actioncardoorsoutside.c.
    {
        CarScript car = CarScript.Cast(action_data.m_Target.GetParent());
        if (car)
        {
            array<string> selections = new array<string>();
            string animSource = "";
            CarDoor carDoor = CarDoor.Cast(action_data.m_Target.GetObject());
            if (carDoor)
            {
                carDoor.GetActionComponentNameList(action_data.m_Target.GetComponentIndex(), selections);
                for (int i = 0; i < selections.Count(); i++)
                {
                    animSource = car.GetAnimSourceFromSelection(selections[i]);
                    if (animSource != "")
                    {
                        break;
                    }
                }
            }
            float phase = 0.0;
            if (m_IsOpening)
            {
                phase = 1.0;
            }
            car.ForceUpdateLightsStart();
            car.SetAnimationPhase(animSource, phase);
        }
    }
References CarScript::GetAnimSourceFromSelection(), m_IsOpening, and ActionData::m_Target.
Member Data Documentation
m_CommandUIDPerCrewIdx
protected int ActionCarDoorsOutside::m_CommandUIDPerCrewIdx[4] private
Definition at line 3 of file actioncardoorsoutside.c.
Referenced by FillCommandUIDPerCrewIdx().
m_IsOpening
protected bool ActionCarDoorsOutside::m_IsOpening = true private
Definition at line 4 of file actioncardoorsoutside.c.
Referenced by ActionCloseCarDoorsOutside::ActionCloseCarDoorsOutside(), ActionCondition(), ActionOpenCarDoorsOutside::ActionOpenCarDoorsOutside(), and OnStartServer().