DayzKode: GearChangeActionCallback Class Reference
GearChangeActionCallback Class Reference
Private Member Functions
override void OnFinish (bool pCanceled)
void SetVehicleCommand (HumanCommandVehicle hcv)
Private Attributes
HumanCommandVehicle m_hcv
Detailed Description
Definition at line 1 of file dayzplayerimplementvehicle.c.
Member Function Documentation
OnFinish()
override void GearChangeActionCallback::OnFinish (bool pCanceled) inline private
Definition at line 13 of file dayzplayerimplementvehicle.c.
    {
        Human owner = GetHuman();
        if (owner)
        {
            HumanCommandVehicle hcv = owner.GetCommand_Vehicle();
            if (hcv)
            {
                hcv.SetClutchState(false);
            }
        }
    }
References GetHuman(), and HumanCommandVehicle::SetClutchState().
SetVehicleCommand()
void GearChangeActionCallback::SetVehicleCommand (HumanCommandVehicle hcv) inline private
Definition at line 6 of file dayzplayerimplementvehicle.c.
    {
        //m_hcv = hcv;
        hcv.SetClutchState(true);
    }
References HumanCommandVehicle::SetClutchState().
Referenced by CommandHandler().
Member Data Documentation
m_hcv
HumanCommandVehicle GearChangeActionCallback::m_hcv private
Definition at line 4 of file dayzplayerimplementvehicle.c.