DayzKode: TelescopicBaton Class Reference
TelescopicBaton Class Reference
Private Member Functions
override void Close ()
override int GetMeleeHeavyMode ()
override int GetMeleeMode ()
override int GetMeleeSprintMode ()
override bool IsOpen ()
override void OnVariablesSynchronized ()
override void Open ()
override void SetActions ()
void TelescopicBaton ()
protected void UpdateVisualState ()
Private Attributes
protected int m_MeleeHeavyMode
protected int m_MeleeMode
protected int m_MeleeSprintMode
protected ref OpenableBehaviour m_Openable
Detailed Description
Definition at line 1 of file telescopicbaton.c.
Constructor & Destructor Documentation
TelescopicBaton()
void TelescopicBaton::TelescopicBaton () inline private
set default melee modes on init
Definition at line 9 of file telescopicbaton.c.
    {
        m_MeleeMode = 0;
        m_MeleeHeavyMode = 1;
        m_MeleeSprintMode = 2;
        m_Openable = new OpenableBehaviour(false);
        RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
        UpdateVisualState();
    }
References m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, and UpdateVisualState().
Member Function Documentation
Close()
override void TelescopicBaton::Close () inline private
sets different set of melee modes for closed state
Definition at line 36 of file telescopicbaton.c.
    {
        m_Openable.Close();
        SetSynchDirty();
        m_MeleeMode = 0;
        m_MeleeHeavyMode = 1;
        m_MeleeSprintMode = 2;
        UpdateVisualState();
    }
References OpenableBehaviour::Close(), m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, and UpdateVisualState().
GetMeleeHeavyMode()
override int TelescopicBaton::GetMeleeHeavyMode () inline private
Definition at line 71 of file telescopicbaton.c.
    {
        return m_MeleeHeavyMode;
    }
References m_MeleeHeavyMode.
GetMeleeMode()
override int TelescopicBaton::GetMeleeMode () inline private
Definition at line 66 of file telescopicbaton.c.
    {
        return m_MeleeMode;
    }
References m_MeleeMode.
GetMeleeSprintMode()
override int TelescopicBaton::GetMeleeSprintMode () inline private
Definition at line 76 of file telescopicbaton.c.
    {
        return m_MeleeSprintMode;
    }
References m_MeleeSprintMode.
IsOpen()
override bool TelescopicBaton::IsOpen () inline private
Definition at line 49 of file telescopicbaton.c.
    {
        return m_Openable.IsOpened();
    }
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by UpdateVisualState().
OnVariablesSynchronized()
override void TelescopicBaton::OnVariablesSynchronized () inline private
Definition at line 81 of file telescopicbaton.c.
    {
        super.OnVariablesSynchronized();
        UpdateVisualState();
    }
References UpdateVisualState().
Open()
override void TelescopicBaton::Open () inline private
sets different set of melee modes for opened state
Definition at line 23 of file telescopicbaton.c.
    {
        m_Openable.Open();
        SetSynchDirty();
        m_MeleeMode = 3;
        m_MeleeHeavyMode = 4;
        m_MeleeSprintMode = 5;
        UpdateVisualState();
    }
References m_MeleeHeavyMode, m_MeleeMode, m_MeleeSprintMode, m_Openable, OpenableBehaviour::Open(), and UpdateVisualState().
SetActions()
override void TelescopicBaton::SetActions () inline private
Definition at line 88 of file telescopicbaton.c.
    {
        super.SetActions();
        AddAction(ActionOpen);
        AddAction(ActionClose);
    }
References AddAction().
UpdateVisualState()
protected void TelescopicBaton::UpdateVisualState () inline private
Definition at line 54 of file telescopicbaton.c.
    {
        if ( IsOpen() )
        {
            SetAnimationPhase("Doors1", 0.0);
        }
        else
        {
            SetAnimationPhase("Doors1", 1.0);
        }
    }
References IsOpen().
Referenced by Close(), OnVariablesSynchronized(), Open(), and TelescopicBaton().
Member Data Documentation
m_MeleeHeavyMode
protected int TelescopicBaton::m_MeleeHeavyMode private
Definition at line 4 of file telescopicbaton.c.
Referenced by Close(), GetMeleeHeavyMode(), Open(), and TelescopicBaton().
m_MeleeMode
protected int TelescopicBaton::m_MeleeMode private
Definition at line 3 of file telescopicbaton.c.
Referenced by Close(), GetMeleeMode(), Open(), and TelescopicBaton().
m_MeleeSprintMode
protected int TelescopicBaton::m_MeleeSprintMode private
Definition at line 5 of file telescopicbaton.c.
Referenced by Close(), GetMeleeSprintMode(), Open(), and TelescopicBaton().
m_Openable
protected ref OpenableBehaviour TelescopicBaton::m_Openable private
Definition at line 7 of file telescopicbaton.c.
Referenced by Close(), IsOpen(), Open(), and TelescopicBaton().