DayzKode: HealthNotfr Class Reference
HealthNotfr Class Reference
Private Member Functions
override void DisplayBadge ()
override void DisplayTendency (float delta)
override int GetNotifierType ()
override protected float GetObservedValue ()
void HealthNotfr (NotifiersManager manager)
override void HideBadge ()
Private Attributes
private const float DEC_TRESHOLD_HIGH = -1.3
private const float DEC_TRESHOLD_LOW = 0
private const float DEC_TRESHOLD_MED = -0.7
private const float INC_TRESHOLD_HIGH = 1.3
private const float INC_TRESHOLD_LOW = 0
private const float INC_TRESHOLD_MED = 0.7
Detailed Description
Definition at line 1 of file healthnotfr.c.
Constructor & Destructor Documentation
HealthNotfr()
void HealthNotfr::HealthNotfr (NotifiersManager manager) inline private
Definition at line 18 of file healthnotfr.c.
    {
        m_TickInterval = 3000;
        m_TendencyBufferSize = 6;
    }
References NotifierBase::m_TendencyBufferSize, and NotifierBase::m_TickInterval.
Member Function Documentation
DisplayBadge()
override void HealthNotfr::DisplayBadge () inline private
Definition at line 29 of file healthnotfr.c.
    {
    }
DisplayTendency()
override void HealthNotfr::DisplayTendency (float delta) inline private
Definition at line 33 of file healthnotfr.c.
    {
        int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
        //PrintString("tendency:" + tendency);
        //GetVirtualHud().SetStatus(eDisplayElements.DELM_TDCY_HEALTH,tendency);
        //DSLevels level = DetermineLevel( GetObservedValue(), PlayerConstants.THRESHOLD_HEALTH_WARNING, PlayerConstants.THRESHOLD_HEALTH_CRITICAL, PlayerConstants.THRESHOLD_HEALTH_BLINKING, PlayerConstants.THRESHOLD_HEALTH_EXTRA);
        EStatLevels health_level = m_Player.GetStatLevelHealth();
        DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_HEALTH));
        if( dis_elm )
        {
            dis_elm.SetSeriousnessLevel(health_level);
            dis_elm.SetTendency(tendency);
        }
    }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int HealthNotfr::GetNotifierType () inline private
Definition at line 24 of file healthnotfr.c.
    {
        return eNotifiers.NTF_HEALTHY;
    }
GetObservedValue()
override protected float HealthNotfr::GetObservedValue () inline private
Definition at line 57 of file healthnotfr.c.
    {
        float health = m_Player.GetHealth("","Health");
        //PrintString("health:" + health);
        return health;
    }
References NotifierBase::m_Player.
HideBadge()
override void HealthNotfr::HideBadge () inline private
Definition at line 51 of file healthnotfr.c.
    {
    }
Member Data Documentation
DEC_TRESHOLD_HIGH
private const float HealthNotfr::DEC_TRESHOLD_HIGH = -1.3 private
Definition at line 12 of file healthnotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
private const float HealthNotfr::DEC_TRESHOLD_LOW = 0 private
Definition at line 10 of file healthnotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
private const float HealthNotfr::DEC_TRESHOLD_MED = -0.7 private
Definition at line 11 of file healthnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
private const float HealthNotfr::INC_TRESHOLD_HIGH = 1.3 private
Definition at line 15 of file healthnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
private const float HealthNotfr::INC_TRESHOLD_LOW = 0 private
Definition at line 13 of file healthnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
private const float HealthNotfr::INC_TRESHOLD_MED = 0.7 private
Definition at line 14 of file healthnotfr.c.
Referenced by DisplayTendency().