DayzKode: ActionGagTarget Class Reference
ActionGagTarget Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionGagTarget ()
override void CreateConditionComponents ()
bool IsWearingMask (PlayerBase player)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actiongagtarget.c.
Constructor & Destructor Documentation
ActionGagTarget()
void ActionGagTarget::ActionGagTarget () inline private
Definition at line 3 of file actiongagtarget.c.
    {
        m_CallbackClass = ActionCoverHeadTargetCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_TARGET;
        //m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#gag_person";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionGagTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 20 of file actiongagtarget.c.
    {
        if (item.GetQuantity() > 1)
            return false;
        PlayerBase targetPlayer;
        Class.CastTo(targetPlayer, target.GetObject());
        if ( !IsWearingMask(targetPlayer) )
        {
            ItemBase headgear = ItemBase.Cast(targetPlayer.FindAttachmentBySlotName( "Headgear" ));
            if ( headgear )
            {
                bool headgear_restricted;
                headgear_restricted = headgear.ConfigGetBool( "noMask" );
                if (headgear_restricted)
                {
                    return false;
                }
            }
            return true;
        }
        return false;
    }
References Class::CastTo(), and IsWearingMask().
CreateConditionComponents()
override void ActionGagTarget::CreateConditionComponents () inline private
Definition at line 13 of file actiongagtarget.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsWearingMask()
bool ActionGagTarget::IsWearingMask (PlayerBase player) inline private
Definition at line 64 of file actiongagtarget.c.
    {
        if ( player.GetInventory().FindAttachment(InventorySlots.MASK) )
        {
            return true;
        }
        return false;
    }
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionGagTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 45 of file actiongagtarget.c.
    {
        PlayerBase ntarget;
        Class.CastTo(ntarget, action_data.m_Target.GetObject());
        ntarget.GetInventory().CreateInInventory("MouthRag");
        MouthRag m_Gag = MouthRag.Cast(ntarget.GetItemOnSlot("Mask"));
        if (m_Gag)
        {
            m_Gag.SetHealth01("", "", action_data.m_MainItem.GetHealth01("", ""));
            ntarget.CheckForGag();
        }
        action_data.m_MainItem.TransferModifiers(ntarget);
        action_data.m_MainItem.Delete();
        //action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), ActionData::m_MainItem, and ActionData::m_Target.