DayzKode: Particle Class Reference
Particle Class Reference
Legacy way of using particles in the game.
Private Member Functions
Playback
Methods regarding playing/stopping of particle
override void PlayParticle (int particle_id=-1)
Method to tell the particle to start playing.
override bool PlayParticleEx (int particle_id=-1, int flags=0)
Method to tell the particle to start playing.
void Play (int particle_id=-1)
Legacy function for backwards compatibility with 1.01 and below.
override bool StopParticle (int flags=0)
Method to tell the particle to stop playing.
void Stop ()
Legacy function for backwards compatibility with 1.14 and below.
Properties and state
Obtain information or set properties regarding the state of the Particle
void SetSource (int particle_id)
Sets particle id.
int GetParticleID ()
Gets particle id.
Object GetDirectParticleEffect ()
Returns direct particle effect entity which is usually handled by this class 'Particle' if there is one.
Object GetParticleParent ()
Returns the parent of this Particle if there is one.
bool HasActiveParticle ()
Returns if there is any particle active.
int GetParticleCount ()
Returns the total count of active particles in all emitors.
bool IsRepeat ()
Returns whether there is a repeating particle.
float GetMaxLifetime ()
Returns the approx. max lifetime.
Misc Particle specific helpers
Functionality specific for Particle
protected void UpdateState ()
Creates/Destroys ParticleEffect child according to current state.
private void CreateParticleEffect ()
Creates ParticleEffect child, called from UpdateState.
private void DestroyParticleEffect ()
Destroys ParticleEffect child, called from UpdateState.
override void EOnFrame (IEntity other, float timeSlice)
OnFrame update event decrementing the stored approx. lifetime and checking for deletion.
void OnCheckAutoDelete ()
Creates ParticleEffect child, called from UpdateState.
private void OnToDelete ()
Called before deletion from OnCheckAutoDelete.
Misc
Various helpers
void AddAsChild (Object parent, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_to_world=false)
Attaches this particle onto some object. If null value is provided then the particle will be detached from the current parent.
Parameter API
Helpful methods for getting or setting parameters
void SetParticleParam (int parameter_id, float value)
Set the value of a parameter of all emitors in the particle.
void SetParameter (int emitter, int parameter, float value)
Set the value of a parameter of an emitor in the particle.
void GetParameter (int emitter, int parameter, out float value)
Get the value of a parameter of an emitor in the particle.
float GetParameterEx (int emitter, int parameter)
Get the value of a parameter of an emitor in the particle.
void ScaleParticleParamFromOriginal (int parameter_id, float coef)
Scales the given parameter on all emitors relatively to their ORIGINAL value.
void ScaleParticleParam (int parameter_id, float coef)
Scales the given parameter on all emitors relatively to their CURRENT value.
void IncrementParticleParamFromOriginal (int parameter_id, float value)
Increments the value of the given parameter relatively from the ORIGINAL value.
void IncrementParticleParam (int parameter_id, float value)
Increments the value of the given parameter relatively from the CURRENT value.
Static Private Member Functions
Create a particle (static)
You can create a particle either at some position, or create it as a child on some object.
static Particle CreateOnObject (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter and attaches it on the given object.
static Particle Create (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0")
Legacy function for backwards compatibility.
static Particle CreateInWorld (int particle_id, vector global_pos, vector global_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter on the given position.
static Particle Create (int particle_id, vector global_pos, vector global_ori="0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
Static play on creation
You can use the following Play(...) functions to create and activate a particle in 1 line of your script.
static Particle PlayOnObject (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter, attaches it on the given object and activates it.
static Particle Play (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
static Particle PlayInWorld (int particle_id, vector global_pos)
Creates a particle emitter on the given position and activates it.
static Particle Play (int particle_id, vector global_pos)
Legacy function for backwards compatibility with 1.01 and below.
Private Attributes
Generic data
Generic data for the Particle
protected int m_ParticleID
ID from ParticleList if assigned.
protected float m_Lifetime
Approx. remaining lifetime of particle.
protected bool m_IsRepeat
Whether this particle repeats.
private bool m_MarkedForDeletion
Whether this particle is queued for deletion.
Wiggle API
Settings to make the Particle wiggle
bool m_WiggleProcessing
Used for Wiggle API, to signal that wiggle API is currently doing work.
bool m_ForceOrientationRelativeToWorld
Used for Wiggle API, to restore after unparenting.
vector m_DefaultOri
Used for Wiggle API, to restore after unparenting.
vector m_DefaultPos
Used for Wiggle API, to restore after unparenting.
vector m_DefaultWorldOri
Used for Wiggle API, to restore after unparenting.
vector m_DefaultWorldPos
Used for Wiggle API, to restore after unparenting.
float m_MaxOriWiggle
Used for Wiggle API, Wiggle room [-m_MaxOriWiggle, m_MaxOriWiggle].
float m_MaxOriInterval
Used for Wiggle API, Interval for wiggling [0, m_MaxOriInterval[.
ref Timer m_RandomizeOri
Used for Wiggle API, calls the Wiggle functionality.
protected Object m_ParentObject
Parent Object the Particle is child of.
protected Object m_ParticleEffect
The child object which contains the actual particle.
protected int m_PreviousFrame
DEPRECATED.
private vector m_GlobalPosPreviousFrame
DEPRECATED.
static private const int MAX_EMITORS = 30
DEPRECATED
void Particle ()
ctor
protected void ParticleInit ()
Purely here so that it can be emptied in ParticleSource.
bool IsWiggling ()
Checks if particle is currently wiggling.
void SetWiggle (float random_angle, float random_interval)
Makes the particle change direction by random_angle every random_interval seconds.
void StopWiggle ()
Stops randomized wiggle.
void RandomizeOrientation ()
Randomizes a new orientation and applies it.
protected vector RandWiggleVector ()
Helper to get a randomized wiggle vector.
protected float RandWiggleFloat ()
Helper to get a randomized wiggle float value.
Detailed Description
Legacy way of using particles in the game.
Note
They work okay when just needing to play a particle once every once in a while But are extremely wasteful when it comes to playing multiple Particles at the same time
Definition at line 6 of file particle.c.
Constructor & Destructor Documentation
Particle()
void Particle::Particle () inline private
ctor
Definition at line 61 of file particle.c.
    {
        ParticleInit();
    }
References ParticleInit().
Member Function Documentation
AddAsChild()
void Particle::AddAsChild (Object parent, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_rotation_to_world = false) inline private
Attaches this particle onto some object. If null value is provided then the particle will be detached from the current parent.
Note
Due to the members being filled in, AddChild/RemoveChild cannot be used with Particle when using Wiggle
Parameters
parent Object Parent onto which this particle will be attached
local_pos vector Attachment position local to the parent (optional)
local_ori vector Orientation local to the parent (Pitch, Yawn, Roll in degrees) (Optional)
force_rotation_to_world bool Force rotation to be in WS (Optional)
Definition at line 563 of file particle.c.
    {
        if (ToDelete())
            return;
        if (parent)
        {
            // AddAsChild method is sometimes called from a timer.
            // Due to that it is necesarry to use ToDelete() here to check if the parent object is flagged for deletion or not on client,
            // because sometimes this code is executed before the parent's destructor from where this would normally be handled.
            if (!parent.ToDelete())
            {
                SetPosition(local_pos);
                SetOrientation(local_ori);
                m_ParentObject = parent;
                m_DefaultPos = local_pos;
                m_ForceOrientationRelativeToWorld = force_rotation_to_world;
                if (m_ParticleEffect)
                    AddChild(m_ParticleEffect, -1, m_ForceOrientationRelativeToWorld);
                parent.AddChild(this, -1, false);
            }
        }
        else
        {
            if (m_ParentObject && !m_ParentObject.ToDelete())
            {
                m_ParentObject.RemoveChild(this, true);
                m_ParentObject = null;
            }
        }
    }
References AddChild(), m_DefaultPos, m_ForceOrientationRelativeToWorld, m_ParentObject, m_ParticleEffect, SetOrientation(), SetPosition(), and ToDelete().
Referenced by EffectParticle::AddAsChild(), CreateOnObject(), and RandomizeOrientation().
Create() [1/2]
static Particle Particle::Create (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0") inline static private
Legacy function for backwards compatibility.
Definition at line 104 of file particle.c.
    {
        return CreateOnObject( particle_id, parent_obj, local_pos, local_ori);
    }
References CreateOnObject(), and particle_id.
Create() [2/2]
static Particle Particle::Create (int particle_id, vector global_pos, vector global_ori = "0 0 0") inline static private
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 129 of file particle.c.
    {
        return CreateInWorld( particle_id, global_pos, global_ori );
    }
References CreateInWorld(), and particle_id.
CreateInWorld()
static Particle Particle::CreateInWorld (int particle_id, vector global_pos, vector global_ori = "0 0 0", bool force_world_rotation = false) inline static private
Creates a particle emitter on the given position.
Parameters
particle_id int Particle ID registered in ParticleList
global_pos Vector Position where the particel will be created
global_ori vector Orientation (Pitch, Yawn, Roll in degrees) (Optional)
force_world_rotation bool Forces particle's orientation to rotate relative to the world and not with the object (Optional)
Returns
Particle Created particle instance
Definition at line 117 of file particle.c.
    {
        Particle p = Particle.Cast( GetGame().CreateObjectEx("Particle", global_pos, ECE_LOCAL) );
        p.SetSource(particle_id);
        p.SetOrientation(global_ori);
        p.m_ForceOrientationRelativeToWorld = force_world_rotation;
        return p;
    }
References ECE_LOCAL, GetGame(), m_ForceOrientationRelativeToWorld, particle_id, and SetSource().
Referenced by Create(), CreateOnObject(), and PlayInWorld().
CreateOnObject()
static Particle Particle::CreateOnObject (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_world_rotation = false) inline static private
Creates a particle emitter and attaches it on the given object.
Parameters
particle_id int Particle ID registered in ParticleList
parent_obj Object Instance on which this particle will be attached
local_pos vector Attachment position local to the parent (Optional)
local_ori vector Orientation local to the parent (Pitch, Yawn, Roll in degrees) (Optional)
force_world_rotation bool Forces particle's orientation to rotate relative to the world and not with the object (Optional)
Returns
Particle Created particle instance
Definition at line 88 of file particle.c.
    {
        if (!parent_obj)
            Error("ERROR when creating a particle! Parameter parent_obj is NULL!");
        vector global_pos = parent_obj.GetPosition();
        Particle p = CreateInWorld(particle_id, global_pos, Vector(0,0,0), force_world_rotation);
        p.AddAsChild(parent_obj, local_pos, local_ori, force_world_rotation);
        p.m_DefaultOri = local_ori;
        return p;
    }
References AddAsChild(), CreateInWorld(), Error(), m_DefaultOri, particle_id, and Vector().
Referenced by Create(), and PlayOnObject().
CreateParticleEffect()
private void Particle::CreateParticleEffect () inline private
Creates ParticleEffect child, called from UpdateState.
Definition at line 440 of file particle.c.
    {
        if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() )
        {
            string fullPath = ParticleList.GetParticleFullPath(m_ParticleID);
            if (fullPath == "")
            {
                ErrorEx("Could not play Particle as there is no valid particle id assigned.");
                m_IsPlaying = false;
                return;
            }
            if ( m_ParticleEffect == null )
            {
                m_ParticleEffect = GetGame().CreateObjectEx("#particlesourceenf", vector.Zero, ECE_LOCAL); // particle source must be lowercase!
            }
            AddChild(m_ParticleEffect, -1, m_ForceOrientationRelativeToWorld);
            vobject vobj = GetObject( fullPath );
            m_ParticleEffect.SetObject(vobj, "");
            ReleaseObject(vobj);
            m_IsRepeat = IsRepeat();
            m_Lifetime = GetMaxLifetime();
        }
    }
References AddChild(), CGame::CreateObjectEx(), ECE_LOCAL, ErrorEx, GetGame(), GetMaxLifetime(), GetObject(), ParticleList::GetParticleFullPath(), IsRepeat(), m_ForceOrientationRelativeToWorld, m_IsPlaying, m_IsRepeat, m_Lifetime, m_ParticleEffect, m_ParticleID, ReleaseObject(), and vector::Zero.
Referenced by UpdateState().
DestroyParticleEffect()
private void Particle::DestroyParticleEffect () inline private
Destroys ParticleEffect child, called from UpdateState.
Note
Does not destroy it immediately As it simply nulls the lifetime Then it will be cleaned up by EOnFrame eventually
Definition at line 474 of file particle.c.
    {
        if ( m_ParticleEffect && GetGame() )
        {
            SetParameter(-1, EmitorParam.LIFETIME, 0);
            SetParameter(-1, EmitorParam.LIFETIME_RND, 0);
            SetParameter(-1, EmitorParam.REPEAT, 0);
            m_IsRepeat = false;
        }
    }
References GetGame(), m_IsRepeat, m_ParticleEffect, and SetParameter().
Referenced by UpdateState().
EOnFrame()
override void Particle::EOnFrame (IEntity other, float timeSlice) inline private
OnFrame update event decrementing the stored approx. lifetime and checking for deletion.
Definition at line 489 of file particle.c.
    {
        m_Lifetime -= timeSlice;
        OnCheckAutoDelete();
    }
References m_Lifetime, and OnCheckAutoDelete().
GetDirectParticleEffect()
Object Particle::GetDirectParticleEffect () inline private
Returns direct particle effect entity which is usually handled by this class 'Particle' if there is one.
Note
Is a child of this Particle
Returns
Object The Object with the particle component or null
Definition at line 307 of file particle.c.
    {
        return m_ParticleEffect;
    }
References m_ParticleEffect.
Referenced by FlammableBase::UpdateLight().
GetMaxLifetime()
float Particle::GetMaxLifetime () inline private
Returns the approx. max lifetime.
Returns
float The largest lifetime sum among the emitors
Definition at line 380 of file particle.c.
    {
        float lifetime_return = 0;
        if (m_ParticleEffect)
        {
            float lifetime_min = 0;
            float lifetime_random = 0;
            float effect_time = 0;
            float lifetime_sum = 0;
            int emitors = GetParticleEmitorCount(m_ParticleEffect);
            for (int i = 0; i < emitors; ++i)
            {
                GetParticleParm(m_ParticleEffect, i, EmitorParam.LIFETIME, lifetime_min);
                GetParticleParm(m_ParticleEffect, i, EmitorParam.LIFETIME_RND, lifetime_random);
                GetParticleParm(m_ParticleEffect, i, EmitorParam.EFFECT_TIME, effect_time);
                lifetime_sum = lifetime_min + lifetime_random + effect_time;
                if ( lifetime_sum > lifetime_return )
                {
                    lifetime_return = lifetime_sum;
                }
            }
        }
        return lifetime_return;
    }
References GetParticleEmitorCount(), GetParticleParm(), and m_ParticleEffect.
Referenced by CreateParticleEffect(), and OnCheckAutoDelete().
GetParameter()
void Particle::GetParameter (int emitter, int parameter, out float value) inline private
Get the value of a parameter of an emitor in the particle.
Parameters
emitter int The emitor to get the value from
parameter int The parameter to get the value from (enum EmitorParam)
value float The value
Definition at line 639 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        GetParticleParm(m_ParticleEffect, emitter, parameter, value);
    }
References GetParticleParm(), and m_ParticleEffect.
GetParameterEx()
float Particle::GetParameterEx (int emitter, int parameter) inline private
Get the value of a parameter of an emitor in the particle.
Parameters
emitter int The emitor to get the value from
parameter int The parameter to get the value from (enum EmitorParam)
Returns
float The value
Definition at line 653 of file particle.c.
    {
        if (!m_ParticleEffect)
            return 0;
        float value;
        GetParticleParm(m_ParticleEffect, emitter, parameter, value);
        return value;
    }
References GetParticleParm(), and m_ParticleEffect.
GetParticleCount()
int Particle::GetParticleCount () inline private
Returns the total count of active particles in all emitors.
Note
Internally does a sum, HasActiveParticle is better for a quick check
Returns
int Total count of active particles
Definition at line 340 of file particle.c.
    {
        if (m_ParticleEffect)
        {
            return m_ParticleEffect.GetParticleCount(m_ParticleEffect);
        }
        return 0;
    }
References m_ParticleEffect.
Referenced by OnCheckAutoDelete().
GetParticleID()
int Particle::GetParticleID () inline private
Gets particle id.
Note
This is not necessarily the CURRENT particle As one can use SetSource while the Particle is still playing But that will not change the particle before Particle is played again
Returns
int The last set Particle ID registered in ParticleList
Definition at line 297 of file particle.c.
    {
        return m_ParticleID;
    }
References m_ParticleID.
Referenced by EffEngineSmoke::Event_OnFrameUpdate(), EffectParticle::GetCurrentParticleID(), and FlammableBase::UpdateParticle().
GetParticleParent()
Object Particle::GetParticleParent () inline private
Returns the parent of this Particle if there is one.
Returns
Object The registered parent or null
Definition at line 316 of file particle.c.
    {
        return m_ParentObject;
    }
References m_ParentObject.
HasActiveParticle()
bool Particle::HasActiveParticle () inline private
Returns if there is any particle active.
Returns
bool Whether there is any particle active
Definition at line 325 of file particle.c.
    {
        if (m_ParticleEffect)
        {
            return m_ParticleEffect.HasActiveParticle(m_ParticleEffect);
        }
        return false;
    }
References m_ParticleEffect.
IncrementParticleParam()
void Particle::IncrementParticleParam (int parameter_id, float value) inline private
Increments the value of the given parameter relatively from the CURRENT value.
Note
It's a simple sum, so negative value decrements
Parameters
parameter_id int The parameter to adjust (enum EmitorParam)
value float The value to sum
Definition at line 727 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        int emitors = GetParticleEmitorCount(m_ParticleEffect);
        for (int i = 0; i < emitors; ++i)
        {
            float param;
            GetParticleParm(m_ParticleEffect, i, parameter_id, param);
            SetParticleParm(m_ParticleEffect, i, parameter_id, param + value);
        }
    }
References GetParticleEmitorCount(), GetParticleParm(), m_ParticleEffect, and SetParticleParm().
IncrementParticleParamFromOriginal()
void Particle::IncrementParticleParamFromOriginal (int parameter_id, float value) inline private
Increments the value of the given parameter relatively from the ORIGINAL value.
Note
It's a simple sum, so negative value decrements
Parameters
parameter_id int The parameter to adjust (enum EmitorParam)
value float The value to sum
Definition at line 707 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        int emitors = GetParticleEmitorCount(m_ParticleEffect);
        for (int i = 0; i < emitors; ++i)
        {
            float param;
            GetParticleParmOriginal(m_ParticleEffect, i, parameter_id, param);
            SetParticleParm(m_ParticleEffect, i, parameter_id, param + value);
        }
    }
References GetParticleEmitorCount(), GetParticleParmOriginal(), m_ParticleEffect, and SetParticleParm().
IsRepeat()
bool Particle::IsRepeat () inline private
Returns whether there is a repeating particle.
Returns
bool whether there is a repeating particle
Definition at line 354 of file particle.c.
    {
        if (m_ParticleEffect)
        {
            bool repeat = false;
            int emitors = GetParticleEmitorCount(m_ParticleEffect);
            for (int i = 0; i < emitors; ++i)
            {
                GetParticleParm(m_ParticleEffect, i, EmitorParam.REPEAT, repeat);
                if (repeat)
                {
                    return true;
                }
            }
        }
        return false;
    }
References GetParticleEmitorCount(), GetParticleParm(), and m_ParticleEffect.
Referenced by CreateParticleEffect(), and OnCheckAutoDelete().
IsWiggling()
bool Particle::IsWiggling () inline private
Checks if particle is currently wiggling.
Definition at line 753 of file particle.c.
    {
        return m_RandomizeOri && m_RandomizeOri.IsRunning();
    }
References m_RandomizeOri.
Referenced by ParticleSource::OnParticleStop(), ParticleSource::OnParticleUnParented(), ParticleSource::SetWiggle(), and ParticleSource::StopWiggle().
OnCheckAutoDelete()
void Particle::OnCheckAutoDelete () inline private
Creates ParticleEffect child, called from UpdateState.
Definition at line 498 of file particle.c.
    {
        if (m_Lifetime <= 0)
        {
            if (!m_MarkedForDeletion)
            {
                m_IsRepeat = IsRepeat(); // It is possible that the REPEAT flag was changed during lifetime, so it needs to be checked again.
                if ( m_IsRepeat )
                {
                    m_Lifetime = GetMaxLifetime();
                }
                else
                {
                    OnParticleStop();
                    if ( GetParticleCount() == 0 )
                    {
                        m_MarkedForDeletion = true;
                        OnToDelete();
                        OnParticleEnd();
                    }
                }
            }
            else
            {
                if ( m_MarkedForDeletion )
                {
                    if (m_ParticleEffect)
                    {
                        m_ParticleEffect.Delete();
                        m_ParticleEffect = null;
                    }
                    Delete();
                }
            }
        }
    }
References Delete(), GetMaxLifetime(), GetParticleCount(), IsRepeat(), m_IsRepeat, m_Lifetime, m_MarkedForDeletion, m_ParticleEffect, OnParticleEnd(), OnParticleStop(), and OnToDelete().
Referenced by EOnFrame().
OnToDelete()
private void Particle::OnToDelete () inline private
Called before deletion from OnCheckAutoDelete.
Definition at line 541 of file particle.c.
    {
    }
Referenced by OnCheckAutoDelete().
ParticleInit()
protected void Particle::ParticleInit () inline private
Purely here so that it can be emptied in ParticleSource.
Definition at line 67 of file particle.c.
    {
        SetFlags(EntityFlags.VISIBLE, true);
        SetEventMask(EntityEvent.INIT);
        SetEventMask(EntityEvent.FRAME);
    }
References SetFlags().
Referenced by Particle().
Play() [1/3]
static Particle Particle::Play (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0") inline static private
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 163 of file particle.c.
    {
        return PlayOnObject( particle_id, parent_obj, local_pos, local_ori);
    }
References particle_id, and PlayOnObject().
Play() [2/3]
static Particle Particle::Play (int particle_id, vector global_pos) inline static private
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 185 of file particle.c.
    {
        return PlayInWorld( particle_id, global_pos);
    }
References particle_id, and PlayInWorld().
Play() [3/3]
void Particle::Play (int particle_id = -1) inline private
Legacy function for backwards compatibility with 1.01 and below.
Parameters
particle_id int Particle ID registered in ParticleList to start playing
Definition at line 233 of file particle.c.
    {
        PlayParticle(particle_id);
    }
References particle_id, and PlayParticle().
PlayInWorld()
static Particle Particle::PlayInWorld (int particle_id, vector global_pos) inline static private
Creates a particle emitter on the given position and activates it.
Parameters
particle_id int Particle ID registered in ParticleList
global_pos Vector Position where the particel will be created
Returns
Particle Created particle instance
Definition at line 174 of file particle.c.
    {
        Particle p = CreateInWorld(particle_id, global_pos);
        p.PlayParticle();
        return p;
    }
References CreateInWorld(), particle_id, and PlayParticle().
Referenced by EffBulletImpactBase::Event_OnStarted(), and Play().
PlayOnObject()
static Particle Particle::PlayOnObject (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_world_rotation = false) inline static private
Creates a particle emitter, attaches it on the given object and activates it.
Parameters
particle_id int Particle ID registered in ParticleList
parent_obj Object Instance on which this particle will be attached
local_pos vector Attachment position local to the parent (Optional)
local_ori vector Orientation local to the parent (Pitch, Yaw, Roll in degrees) (Optional)
force_world_rotation bool Forces particle's orientation to rotate relative to the world and not with the object (Optional)
Returns
Particle Created particle instance
Definition at line 152 of file particle.c.
    {
        Particle p = CreateOnObject(particle_id, parent_obj, local_pos, local_ori, force_world_rotation);
        p.PlayParticle();
        return p;
    }
References CreateOnObject(), particle_id, and PlayParticle().
Referenced by Play().
PlayParticle()
override void Particle::PlayParticle (int particle_id = -1) inline private
Method to tell the particle to start playing.
Parameters
particle_id int Particle ID registered in ParticleList to start playing
Definition at line 203 of file particle.c.
    {
        PlayParticleEx(particle_id, 0);
    }
References particle_id, and PlayParticleEx().
Referenced by PMTPlayback::CheckStop(), Play(), PlayInWorld(), and PlayOnObject().
PlayParticleEx()
override bool Particle::PlayParticleEx (int particle_id = -1, int flags = 0) inline private
Method to tell the particle to start playing.
Note
The parameter to set the ID will only work when the particle is not already playing
Parameters
particle_id int Particle ID registered in ParticleList to start playing
flags int Flags to pass to the playing (None on this level)
Returns
bool Whether the particle successfully started
Definition at line 215 of file particle.c.
    {
        if ( particle_id > -1 )
        {
            SetSource(particle_id);
        }
        OnParticleStart();
        UpdateState();
        return true;
    }
References OnParticleStart(), particle_id, SetSource(), and UpdateState().
Referenced by PlayParticle().
RandomizeOrientation()
void Particle::RandomizeOrientation () inline private
Randomizes a new orientation and applies it.
Definition at line 801 of file particle.c.
    {
        m_WiggleProcessing = true;
        if (m_ParentObject)
        {
            if ( !m_RandomizeOri.IsRunning() )
            {
                m_RandomizeOri.Run( Math.RandomFloat(0, m_MaxOriInterval) , this, "RandomizeOrientation", NULL, false);
            }
            Object old_parent = m_ParentObject;
            AddAsChild( null );
            AddAsChild( old_parent, m_DefaultPos, m_DefaultOri + RandWiggleVector() );
        }
        m_WiggleProcessing = false;
    }
References AddAsChild(), m_DefaultOri, m_DefaultPos, m_MaxOriInterval, m_ParentObject, m_RandomizeOri, m_WiggleProcessing, Math::RandomFloat(), and RandWiggleVector().
RandWiggleFloat()
protected float Particle::RandWiggleFloat () inline private
Helper to get a randomized wiggle float value.
Definition at line 831 of file particle.c.
    {
        return Math.RandomFloatInclusive(-m_MaxOriWiggle, m_MaxOriWiggle);
    }
References m_MaxOriWiggle, and Math::RandomFloatInclusive().
Referenced by RandWiggleVector().
RandWiggleVector()
protected vector Particle::RandWiggleVector () inline private
Helper to get a randomized wiggle vector.
Definition at line 823 of file particle.c.
    {
        return Vector( RandWiggleFloat(), RandWiggleFloat(), RandWiggleFloat() );
    }
References RandWiggleFloat(), and Vector().
Referenced by RandomizeOrientation(), and ParticleSource::RandomizeOrientation().
ScaleParticleParam()
void Particle::ScaleParticleParam (int parameter_id, float coef) inline private
Scales the given parameter on all emitors relatively to their CURRENT value.
Parameters
parameter_id int The parameter to adjust (enum EmitorParam)
coef float The multiplier to apply
Definition at line 687 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        int emitors = GetParticleEmitorCount(m_ParticleEffect);
        for (int i = 0; i < emitors; ++i)
        {
            float value;
            GetParticleParm(m_ParticleEffect, i, parameter_id, value);
            SetParticleParm(m_ParticleEffect, i, parameter_id, value * coef);
        }
    }
References GetParticleEmitorCount(), GetParticleParm(), m_ParticleEffect, and SetParticleParm().
Referenced by Hit_MeatBones::BloodSplatGround(), EffBulletImpactBase::Event_OnStarted(), EffBulletImpactBase::OnEnterAngledCalculations(), EffBulletImpactBase::OnEnterCalculations(), Hit_MeatBones::OnEnterCalculations(), Hit_Wood::OnEnterCalculations(), EffBulletImpactBase::OnExitCalculations(), Hit_MeatBones::OnExitCalculations(), Hit_Wood::OnExitCalculations(), and EffBulletImpactBase::OnRicochetCalculations().
ScaleParticleParamFromOriginal()
void Particle::ScaleParticleParamFromOriginal (int parameter_id, float coef) inline private
Scales the given parameter on all emitors relatively to their ORIGINAL value.
Parameters
parameter_id int The parameter to adjust (enum EmitorParam)
coef float The multiplier to apply
Definition at line 668 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        int emitors = GetParticleEmitorCount(m_ParticleEffect);
        for (int i = 0; i < emitors; ++i)
        {
            float value;
            GetParticleParmOriginal(m_ParticleEffect, i, parameter_id, value);
            SetParticleParm(m_ParticleEffect, i, parameter_id, value * coef);
        }
    }
References GetParticleEmitorCount(), GetParticleParmOriginal(), m_ParticleEffect, and SetParticleParm().
Referenced by EffEngineSmoke::Event_OnFrameUpdate(), EffExhaustSmoke::SetParticleStateLight(), EffCoolantSteam::UpdateParticle(), BroomBase::UpdateParticle(), and FlammableBase::UpdateParticle().
SetParameter()
void Particle::SetParameter (int emitter, int parameter, float value) inline private
Set the value of a parameter of an emitor in the particle.
Parameters
emitter int The emitter to apply the new value to, -1 for all emitter
parameter int The parameter to apply the new value to (enum EmitorParam)
value float The value to apply
Definition at line 625 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        SetParticleParm(m_ParticleEffect, emitter, parameter, value);
    }
References m_ParticleEffect, and SetParticleParm().
Referenced by ManBase::ContaminatedParticleAdjustment(), CreateParticle(), DestroyParticleEffect(), ParticleNormalSmokeStart(), ParticleSmallSmokeStart(), PlayVFX(), ManBase::SetContaminatedEffectEx(), FlareSimulation::Simulate(), and FlareSimulation::TurnOffDistantLight().
SetParticleParam()
void Particle::SetParticleParam (int parameter_id, float value) inline private
Set the value of a parameter of all emitors in the particle.
Parameters
parameter int The parameter to apply the new value to (enum EmitorParam)
value float The value to apply
Definition at line 611 of file particle.c.
    {
        if (!m_ParticleEffect)
            return;
        SetParticleParm(m_ParticleEffect, -1, parameter_id, value);
    }
References m_ParticleEffect, and SetParticleParm().
Referenced by EntityLightSource::HandleDancingShadows(), and EffCoolantSteam::UpdateParticle().
SetSource()
void Particle::SetSource (int particle_id) inline private
Sets particle id.
Note
Does not work at runtime, particle object needs to be destroyed and then Particle needs to play again
Parameters
particle_id int Particle ID registered in ParticleList to start playing
Definition at line 285 of file particle.c.
    {
        m_ParticleID = particle_id;
    }
References m_ParticleID, and particle_id.
Referenced by CreateInWorld(), PlayParticleEx(), and EffectParticle::SetCurrentParticleID().
SetWiggle()
void Particle::SetWiggle (float random_angle, float random_interval) inline private
Makes the particle change direction by random_angle every random_interval seconds.
Note
This does not actually work on Particle with no parent, it should on ParticleSource
Calling SetWiggle(0,0) will effectively stop all wiggle functionality
Parameters
random_angle float Will be the range [-random_angle, random_angle[ to wiggle between
random_interval float Will be the time range [0, random_interval] to wiggle next time
Definition at line 765 of file particle.c.
    {
        if ( random_angle != 0 || random_interval != 0 )
        {
            m_MaxOriWiggle = random_angle;
            m_MaxOriInterval = random_interval;
            if ( !m_RandomizeOri )
                m_RandomizeOri = new Timer( CALL_CATEGORY_GAMEPLAY );
            if ( !m_RandomizeOri.IsRunning() ) // Makes sure the timer is NOT running already
                m_RandomizeOri.Run( Math.RandomFloat(0, m_MaxOriInterval) , this, "RandomizeOrientation", null, false);
        }
        else
        {
            StopWiggle();
        }
    }
References CALL_CATEGORY_GAMEPLAY, m_MaxOriInterval, m_MaxOriWiggle, m_RandomizeOri, Math::RandomFloat(), and StopWiggle().
Referenced by Roadflare::DestroyParticle(), FlareSimulation::OnActivation(), SmokeSimulation::OnFire(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), PlayVFX(), and Roadflare::UpdateActiveParticles().
Stop()
void Particle::Stop () inline private
Legacy function for backwards compatibility with 1.14 and below.
Definition at line 266 of file particle.c.
    {
        StopParticle();
    }
References StopParticle().
Referenced by DestroyParticle(), Roadflare::DestroyParticle(), DynamicArea_Flare::EEDelete(), House::EEDelete(), BuildingSuper::EEDelete(), Ammo_40mm_Smoke_ColorBase::EEDelete(), ItemBase::EEDelete(), InventoryItem::KillAllOverheatingParticles(), FlareSimulation::OnActivation(), FireworksLauncherClientEvent::OnExplode(), OnInventoryEnter(), FlammableBase::OnWorkStop(), ManBase::SetContaminatedEffectEx(), EffectParticle::Stop(), FlammableBase::StopAllParticles(), InventoryItem::UpdateAllOverheatingParticles(), FlammableBase::UpdateParticle(), DestructionEffectBase::~DestructionEffectBase(), ~EasterEgg(), FlareSimulation::~FlareSimulation(), and SmokeSimulation::~SmokeSimulation().
StopParticle()
override bool Particle::StopParticle (int flags = 0) inline private
Method to tell the particle to stop playing.
Note
No flags available for Particle
Emitors are automatically removed later when its particle count is 0
Parameters
flags int Flags to pass to the stopping (None on this level)
Returns
bool Whether the particle successfully stopped
Definition at line 245 of file particle.c.
    {
        OnParticleStop();
        // Without the following we might get an error when a particle parent is despawned client-side.
        Object parent = Object.Cast( GetParent() );
        if ( parent && !ToDelete())
        {
            vector world_pos = GetPosition();
            parent.RemoveChild(this);
            SetPosition(world_pos);
        }
        UpdateState();
        return true;
    }
References GetParent(), GetPosition, OnParticleStop(), SetPosition(), ToDelete(), and UpdateState().
Referenced by Stop().
StopWiggle()
void Particle::StopWiggle () inline private
Stops randomized wiggle.
Definition at line 787 of file particle.c.
    {
        if ( m_RandomizeOri )
        {
            m_RandomizeOri.Stop();
        }
        m_MaxOriWiggle = 0;
        m_MaxOriInterval = 0;
    }
References m_MaxOriInterval, m_MaxOriWiggle, and m_RandomizeOri.
Referenced by SetWiggle().
UpdateState()
protected void Particle::UpdateState () inline private
Creates/Destroys ParticleEffect child according to current state.
Note
Is called from Play/Stop methods
Definition at line 425 of file particle.c.
    {
        if ( m_IsPlaying == false && m_ParticleEffect)
        {
            DestroyParticleEffect();
        }
        else if ( m_IsPlaying == true && m_ParticleEffect == null )
        {
            CreateParticleEffect();
        }
    }
References CreateParticleEffect(), DestroyParticleEffect(), m_IsPlaying, and m_ParticleEffect.
Referenced by PlayParticleEx(), and StopParticle().
Member Data Documentation
m_DefaultOri
vector Particle::m_DefaultOri private
Used for Wiggle API, to restore after unparenting.
Definition at line 31 of file particle.c.
Referenced by CreateOnObject(), ParticleSource::OnParticleUnParented(), RandomizeOrientation(), ParticleSource::RandomizeOrientation(), ParticleSource::SetWiggle(), and ParticleSource::StopWiggle().
m_DefaultPos
vector Particle::m_DefaultPos private
Used for Wiggle API, to restore after unparenting.
Definition at line 33 of file particle.c.
Referenced by AddAsChild(), ParticleSource::OnParticleUnParented(), RandomizeOrientation(), ParticleSource::RandomizeOrientation(), ParticleSource::SetWiggle(), and ParticleSource::StopWiggle().
m_DefaultWorldOri
vector Particle::m_DefaultWorldOri private
Used for Wiggle API, to restore after unparenting.
Definition at line 35 of file particle.c.
Referenced by ParticleSource::OnParticleUnParented(), and ParticleSource::SetWiggle().
m_DefaultWorldPos
vector Particle::m_DefaultWorldPos private
Used for Wiggle API, to restore after unparenting.
Definition at line 37 of file particle.c.
Referenced by ParticleSource::OnParticleUnParented(), and ParticleSource::SetWiggle().
m_ForceOrientationRelativeToWorld
bool Particle::m_ForceOrientationRelativeToWorld private
Used for Wiggle API, to restore after unparenting.
Definition at line 29 of file particle.c.
Referenced by AddAsChild(), CreateInWorld(), CreateParticleEffect(), ParticleSource::RandomizeOrientation(), ParticleSource::SetWiggle(), and ParticleSource::StopWiggle().
m_GlobalPosPreviousFrame
private vector Particle::m_GlobalPosPreviousFrame private
DEPRECATED.
Definition at line 55 of file particle.c.
m_IsRepeat
protected bool Particle::m_IsRepeat private
Whether this particle repeats.
Definition at line 17 of file particle.c.
Referenced by CreateParticleEffect(), DestroyParticleEffect(), and OnCheckAutoDelete().
m_Lifetime
protected float Particle::m_Lifetime private
Approx. remaining lifetime of particle.
Definition at line 15 of file particle.c.
Referenced by CreateParticleEffect(), EOnFrame(), and OnCheckAutoDelete().
m_MarkedForDeletion
private bool Particle::m_MarkedForDeletion private
Whether this particle is queued for deletion.
Definition at line 19 of file particle.c.
Referenced by OnCheckAutoDelete().
m_MaxOriInterval
float Particle::m_MaxOriInterval private
Used for Wiggle API, Interval for wiggling [0, m_MaxOriInterval[.
Definition at line 42 of file particle.c.
Referenced by ParticleSource::OnParticleUnParented(), RandomizeOrientation(), ParticleSource::RandomizeOrientation(), SetWiggle(), ParticleSource::SetWiggle(), and StopWiggle().
m_MaxOriWiggle
float Particle::m_MaxOriWiggle private
Used for Wiggle API, Wiggle room [-m_MaxOriWiggle, m_MaxOriWiggle].
Definition at line 40 of file particle.c.
Referenced by ParticleSource::OnParticleUnParented(), RandWiggleFloat(), SetWiggle(), ParticleSource::SetWiggle(), and StopWiggle().
m_ParentObject
protected Object Particle::m_ParentObject private
Parent Object the Particle is child of.
Definition at line 48 of file particle.c.
Referenced by AddAsChild(), GetParticleParent(), ParticleSource::OnParticleParented(), ParticleSource::OnParticleUnParented(), and RandomizeOrientation().
m_ParticleEffect
protected Object Particle::m_ParticleEffect private
The child object which contains the actual particle.
Definition at line 50 of file particle.c.
Referenced by AddAsChild(), CreateParticleEffect(), DestroyParticleEffect(), GetDirectParticleEffect(), GetMaxLifetime(), GetParameter(), GetParameterEx(), GetParticleCount(), HasActiveParticle(), IncrementParticleParam(), IncrementParticleParamFromOriginal(), IsRepeat(), OnCheckAutoDelete(), ParticleSource::ParticleSource(), ScaleParticleParam(), ScaleParticleParamFromOriginal(), SetParameter(), SetParticleParam(), and UpdateState().
m_ParticleID
protected int Particle::m_ParticleID private
ID from ParticleList if assigned.
Definition at line 13 of file particle.c.
Referenced by CreateParticleEffect(), GetParticleID(), and SetSource().
m_PreviousFrame
protected int Particle::m_PreviousFrame private
DEPRECATED.
Definition at line 53 of file particle.c.
m_RandomizeOri
ref Timer Particle::m_RandomizeOri private
Used for Wiggle API, calls the Wiggle functionality.
Definition at line 44 of file particle.c.
Referenced by IsWiggling(), ParticleSource::OnParticleStop(), RandomizeOrientation(), ParticleSource::RandomizeOrientation(), SetWiggle(), and StopWiggle().
m_WiggleProcessing
bool Particle::m_WiggleProcessing private
Used for Wiggle API, to signal that wiggle API is currently doing work.
Definition at line 27 of file particle.c.
Referenced by ParticleSource::OnParticleUnParented(), RandomizeOrientation(), and ParticleSource::RandomizeOrientation().
MAX_EMITORS
private const int Particle::MAX_EMITORS = 30 static private
DEPRECATED
Definition at line 57 of file particle.c.