DayzKode: BloodTypes Class Reference
BloodTypes Class Reference
Static Private Member Functions
static int GenerateBloodType ()
static string GetBloodTypeName (int bloodtype, out string type, out bool positive)
static bool MatchBloodCompatibility (int bloodtypetarget, int bloodtype)
Static Private Attributes
static const int NUM_OF_BLOOD_TYPES = 8
Detailed Description
Definition at line 1 of file bloodtype.c.
Member Function Documentation
GenerateBloodType()
static int BloodTypes::GenerateBloodType () inline static private
Definition at line 7 of file bloodtype.c.
    {
        int types[NUM_OF_BLOOD_TYPES]       = {LIQUID_BLOOD_0_P, LIQUID_BLOOD_0_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_B_P, LIQUID_BLOOD_B_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_AB_N};
        int probability[NUM_OF_BLOOD_TYPES]     = {42,10,25,5,9,3,2,2};
        int probability_sum = 0;
        for(int i = 0; i < NUM_OF_BLOOD_TYPES; i++)
        {
            probability_sum += probability[i];
        }
        //TIMERDEPRECATED - randomized blodtype for new character
        int probability_randomized = Math.RandomInt(0,probability_sum);
        int tmp = 0;
        int index;
        for(i = 0; i < NUM_OF_BLOOD_TYPES; i++)
        {
            tmp += probability[i];
            if( tmp > probability_randomized )
            {
                index = i;
                break;
            }
        }
        return types[index];
    }
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, LIQUID_BLOOD_B_P, NUM_OF_BLOOD_TYPES, and Math::RandomInt().
Referenced by PlayerStatsPCO_Base::Init().
GetBloodTypeName()
static string BloodTypes::GetBloodTypeName (int bloodtype, out string type, out bool positive) inline static private
Definition at line 89 of file bloodtype.c.
    {
        string bloodTypeName;
        switch ( bloodtype )
        {
            case LIQUID_BLOOD_0_P:
                bloodTypeName = "0+";
                type = "0";
                positive = true;
            break;
            case LIQUID_BLOOD_0_N:
                bloodTypeName = "0-";
                type = "0";
                positive = false;
            break;
            case LIQUID_BLOOD_A_P:
                bloodTypeName = "A+";
                type = "A";
                positive = true;
            break;
            case LIQUID_BLOOD_A_N:
                bloodTypeName = "A-";
                type = "A";
                positive = false;
            break;
            case LIQUID_BLOOD_B_P:
                bloodTypeName = "B+";
                type = "B";
                positive = true;
            break;
            case LIQUID_BLOOD_B_N:
                bloodTypeName = "B-";
                type = "B";
                positive = false;
            break;
            case LIQUID_BLOOD_AB_P:
                bloodTypeName = "AB+";
                type = "AB";
                positive = true;
            break;
            case LIQUID_BLOOD_AB_N:
                bloodTypeName = "AB-";
                type = "AB";
                positive = false;
            break;
            default:
                bloodTypeName = "";
            break;
        }
        return bloodTypeName;
    }
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, and LIQUID_BLOOD_B_P.
Referenced by RecipeBase::Do(), ActionTestBloodTarget::OnFinishProgressClient(), Hud::UpdateBloodName(), UIScriptedMenu::UpdateItemInfoLiquidType(), and HudDebugWinBase::UpdateValues().
MatchBloodCompatibility()
static bool BloodTypes::MatchBloodCompatibility (int bloodtypetarget, int bloodtype) inline static private
Definition at line 39 of file bloodtype.c.
    {
        bool result = false;
        switch ( bloodtype )
        {
            case LIQUID_BLOOD_0_P:
                if ( bloodtypetarget == LIQUID_BLOOD_0_P || bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_0_N:
                if ( bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_A_P:
                if ( bloodtypetarget == LIQUID_BLOOD_A_P || bloodtypetarget == LIQUID_BLOOD_A_N || bloodtypetarget == LIQUID_BLOOD_0_P || bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_A_N:
                if ( bloodtypetarget == LIQUID_BLOOD_A_N || bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_B_P:
                if ( bloodtypetarget == LIQUID_BLOOD_B_P || bloodtypetarget == LIQUID_BLOOD_B_N || bloodtypetarget == LIQUID_BLOOD_0_P || bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_B_N:
                if ( bloodtypetarget == LIQUID_BLOOD_B_N || bloodtypetarget == LIQUID_BLOOD_0_N ) result = true;
            break;
            case LIQUID_BLOOD_AB_P:
                if ( bloodtypetarget == LIQUID_BLOOD_AB_P || bloodtypetarget == LIQUID_BLOOD_0_N || bloodtypetarget == LIQUID_BLOOD_0_P || bloodtypetarget == LIQUID_BLOOD_A_N || bloodtypetarget == LIQUID_BLOOD_A_P || bloodtypetarget == LIQUID_BLOOD_B_N || bloodtypetarget == LIQUID_BLOOD_B_P || bloodtypetarget == LIQUID_BLOOD_AB_N ) result = true;
            break;
            case LIQUID_BLOOD_AB_N:
                if ( bloodtypetarget == LIQUID_BLOOD_AB_N || bloodtypetarget == LIQUID_BLOOD_0_N || bloodtypetarget == LIQUID_BLOOD_A_N || bloodtypetarget == LIQUID_BLOOD_B_N ) result = true;
            break;
            default:
                Debug.Log("Incorrect blood type");
            break;
        }
        if ( result )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References LIQUID_BLOOD_0_N, LIQUID_BLOOD_0_P, LIQUID_BLOOD_A_N, LIQUID_BLOOD_A_P, LIQUID_BLOOD_AB_N, LIQUID_BLOOD_AB_P, LIQUID_BLOOD_B_N, LIQUID_BLOOD_B_P, and Debug::Log().
Referenced by CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), ActionGiveBloodSelf::OnEndServer(), and ActionGiveBloodTarget::OnEndServer().
Member Data Documentation
NUM_OF_BLOOD_TYPES
const int BloodTypes::NUM_OF_BLOOD_TYPES = 8 static private
Definition at line 3 of file bloodtype.c.
Referenced by GenerateBloodType().