DayzKode: AreaDamageComponentRaycasted Class Reference
AreaDamageComponentRaycasted Class Reference
Newer implementation equivalent of "AreaDamageRegularRaycasted", hitzone selection only.
Private Member Functions
void AreaDamageComponentRaycasted (AreaDamageManager parent)
protected void ClearCache ()
override protected AreaDamageComponentData GetAreaDamageComponentData (Object object)
protected string GetFallbackHitZone (Object victim)
protected string GetRaycastedHitZone (Object victim)
override void OnStayFinishServerEvent ()
override void OnTriggerCreated ()
void SetRaycastLength (float length)
void SetRaycastSources (array< string > raycast_sources)
void SetRaycastSourcesVector (array< vector > raycast_sources)
Private Attributes
ref array< ref RaycastRVResult > m_RaycastCache
int m_RaycastCachedIndex
vector m_RaycastEndOffset
ref array< vector > m_RaycastSources
Detailed Description
Newer implementation equivalent of "AreaDamageRegularRaycasted", hitzone selection only.
Definition at line 2 of file areadamagecomponentraycasted.c.
Constructor & Destructor Documentation
AreaDamageComponentRaycasted()
void AreaDamageComponentRaycasted::AreaDamageComponentRaycasted (AreaDamageManager parent) inline private
Definition at line 11 of file areadamagecomponentraycasted.c.
    {
        m_RaycastSources = new array<vector>;
        m_RaycastEndOffset = "0 0.5 0";
        m_RaycastCache = new array<ref RaycastRVResult>;
        m_RaycastCachedIndex = -1;
    }
References m_RaycastCache, m_RaycastCachedIndex, m_RaycastEndOffset, and m_RaycastSources.
Member Function Documentation
ClearCache()
protected void AreaDamageComponentRaycasted::ClearCache () inline private
Definition at line 64 of file areadamagecomponentraycasted.c.
    {
        m_RaycastCache.Clear();
        m_RaycastCachedIndex = -1;
    }
References m_RaycastCache, and m_RaycastCachedIndex.
Referenced by OnStayFinishServerEvent(), and OnTriggerCreated().
GetAreaDamageComponentData()
override protected AreaDamageComponentData AreaDamageComponentRaycasted::GetAreaDamageComponentData (Object object) inline private
Definition at line 56 of file areadamagecomponentraycasted.c.
    {
        AreaDamageComponentData data = new AreaDamageComponentData;
        data.Hitzone = GetRaycastedHitZone(object);
        return data;
    }
References GetRaycastedHitZone(), and AreaDamageComponentData::Hitzone.
GetFallbackHitZone()
protected string AreaDamageComponentRaycasted::GetFallbackHitZone (Object victim) inline private
Definition at line 121 of file areadamagecomponentraycasted.c.
    {
        Error(string.Format("[WARNING] :: [%1] :: [AreaDamageComponentRaycasted] :: No proper HitZone found for damaging %2, using fallback.",
            m_Parent, Object.GetDebugName(victim)));
        // Fallbacks, currently are implemented assuming that foot/leg damagezones would be desired to damage
        if ( victim.IsInherited(DayZPlayer) || victim.IsInherited(DayZInfected) )
        {
            // Damage random leg since we don't know what part of player's body was caught in the trap.
            if ( Math.RandomIntInclusive(0, 1) == 1 )
                return "RightFoot";
            return "LeftFoot";
        }
        else
        {
            array<string> damageZones = new array<string>;
            victim.GetDamageZones(damageZones);
            int nrOfDmgZones = damageZones.Count();
            if (nrOfDmgZones > 0)
            {
                for (int z = 0; z < nrOfDmgZones; ++z)
                {
                    if ( damageZones[z].Contains("Foot") || damageZones[z].Contains("Leg") )
                        return damageZones[z];
                }
                return damageZones.GetRandomElement();
            }
            else
                return "";
        }
    }
References Error(), m_Parent, and Math::RandomIntInclusive().
Referenced by GetRaycastedHitZone().
GetRaycastedHitZone()
protected string AreaDamageComponentRaycasted::GetRaycastedHitZone (Object victim) inline private
Definition at line 70 of file areadamagecomponentraycasted.c.
    {
        int nrOfCachedResults = m_RaycastSources.Count();
        for ( int c = 0; c < nrOfCachedResults; ++c )
        {
            RaycastRVResult cachedRes = m_RaycastCache[c];
            if ( cachedRes.obj == victim )
                return victim.GetDamageZoneNameByComponentIndex(cachedRes.component);
        }
        int nrOfSources = m_RaycastSources.Count();
        array<ref RaycastRVResult> victims = new array<ref RaycastRVResult>;
        string hitzone = "";
        AreaDamageTriggerBase trigger = m_Parent.GetTrigger();
        RaycastRVParams params = new RaycastRVParams( vector.Zero, vector.Zero, trigger, 0.0 );
        params.type = ObjIntersectIFire;
        params.flags = CollisionFlags.ONLYDYNAMIC;
        for ( int i = m_RaycastCachedIndex + 1; i < nrOfSources; ++i )
        {
            m_RaycastCachedIndex = i;
            params.begPos = trigger.ModelToWorld( m_RaycastSources[i] );
            params.endPos = params.begPos + m_RaycastEndOffset;
            if ( DayZPhysics.RaycastRVProxy(params, victims) )
            {
                for ( int j = 0; j < victims.Count(); ++j )
                {
                    RaycastRVResult res = victims[j];
                    if (res.obj == victim)
                        hitzone = victim.GetDamageZoneNameByComponentIndex(res.component);
                    if (res.obj.IsAnyInherited(m_DamageableTypes))
                        m_RaycastCache.Insert(res);
                }
                if ( !( hitzone == "") )
                    return hitzone;
                victims.Clear();
            }
        }
        return GetFallbackHitZone(victim);
    }
References RaycastRVParams::begPos, RaycastRVResult::component, RaycastRVParams::endPos, RaycastRVParams::flags, GetFallbackHitZone(), m_Parent, m_RaycastCache, m_RaycastCachedIndex, m_RaycastEndOffset, m_RaycastSources, RaycastRVResult::obj, DayZPhysics::RaycastRVProxy(), RaycastRVParams::type, and vector::Zero.
Referenced by GetAreaDamageComponentData().
OnStayFinishServerEvent()
override void AreaDamageComponentRaycasted::OnStayFinishServerEvent () inline private
Definition at line 49 of file areadamagecomponentraycasted.c.
    {
        super.OnStayFinishServerEvent();
        ClearCache();
    }
References ClearCache().
OnTriggerCreated()
override void AreaDamageComponentRaycasted::OnTriggerCreated () inline private
Definition at line 20 of file areadamagecomponentraycasted.c.
    {
        super.OnTriggerCreated();
        ClearCache();
    }
References ClearCache().
SetRaycastLength()
void AreaDamageComponentRaycasted::SetRaycastLength (float length) inline private
Definition at line 44 of file areadamagecomponentraycasted.c.
    {
        m_RaycastEndOffset = Vector(0, length, 0);
    }
References m_RaycastEndOffset, and Vector().
SetRaycastSources()
void AreaDamageComponentRaycasted::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 27 of file areadamagecomponentraycasted.c.
    {
        m_RaycastSources.Clear();
        // convert Array of string to array of Vectors
        int nrOfSources = raycast_sources.Count();
        for ( int v = 0; v < nrOfSources; ++v)
        {
            m_RaycastSources.Insert(raycast_sources[v].ToVector());
        }
    }
References m_RaycastSources.
Referenced by SetRaycastSources().
SetRaycastSourcesVector()
void AreaDamageComponentRaycasted::SetRaycastSourcesVector (array< vector > raycast_sources) inline private
Definition at line 39 of file areadamagecomponentraycasted.c.
    {
        m_RaycastSources = raycast_sources;
    }
References m_RaycastSources.
Referenced by SetRaycastSourcesVector().
Member Data Documentation
m_RaycastCache
ref array<ref RaycastRVResult> AreaDamageComponentRaycasted::m_RaycastCache private
Definition at line 8 of file areadamagecomponentraycasted.c.
Referenced by AreaDamageComponentRaycasted(), ClearCache(), and GetRaycastedHitZone().
m_RaycastCachedIndex
int AreaDamageComponentRaycasted::m_RaycastCachedIndex private
Definition at line 9 of file areadamagecomponentraycasted.c.
Referenced by AreaDamageComponentRaycasted(), ClearCache(), and GetRaycastedHitZone().
m_RaycastEndOffset
vector AreaDamageComponentRaycasted::m_RaycastEndOffset private
Definition at line 6 of file areadamagecomponentraycasted.c.
Referenced by AreaDamageComponentRaycasted(), GetRaycastedHitZone(), and SetRaycastLength().
m_RaycastSources
ref array<vector> AreaDamageComponentRaycasted::m_RaycastSources private
Definition at line 5 of file areadamagecomponentraycasted.c.
Referenced by AreaDamageComponentRaycasted(), GetRaycastedHitZone(), SetRaycastSources(), and SetRaycastSourcesVector().