DayzKode: UndergroundTriggerCarrierBase Class Reference
UndergroundTriggerCarrierBase Class Reference
Private Member Functions
bool CanSpawnTrigger ()
override void OnVariablesSynchronized ()
void RequestDelayedTriggerSpawn ()
void SpawnTrigger ()
void UndergroundTriggerCarrier ()
void ~UndergroundTriggerCarrier ()
Private Attributes
ref JsonUndergroundAreaTriggerData m_Data
UndergroundTrigger m_Trigger
Detailed Description
This entity exists both client andserver side when it enters into player's bubble and gets instantiated client-side, it will locally spawn UndergroundTrigger, which is the actual trigger
Definition at line 3 of file undergroundtrigger.c.
Constructor & Destructor Documentation
~UndergroundTriggerCarrier()
void UndergroundTriggerCarrierBase::~UndergroundTriggerCarrier () inline private
Definition at line 13 of file undergroundtrigger.c.
    {
        if (m_Trigger && !m_Trigger.IsSetForDeletion() && GetGame())
        {
            //RemoveChild(m_Trigger);
            m_Trigger.Delete();
        }
    }
References GetGame().
Member Function Documentation
CanSpawnTrigger()
bool UndergroundTriggerCarrierBase::CanSpawnTrigger () inline private
Definition at line 31 of file undergroundtrigger.c.
    {
        return UndergroundAreaLoader.m_JsonData && m_TriggerIndex != -1;
    }
References UndergroundAreaLoader::m_JsonData.
Referenced by SpawnTrigger().
OnVariablesSynchronized()
override void UndergroundTriggerCarrierBase::OnVariablesSynchronized () inline private
Definition at line 22 of file undergroundtrigger.c.
    {
        super.OnVariablesSynchronized();
        if (!m_Trigger)
        {
            SpawnTrigger();
        }
    }
References SpawnTrigger().
RequestDelayedTriggerSpawn()
void UndergroundTriggerCarrierBase::RequestDelayedTriggerSpawn () inline private
Definition at line 36 of file undergroundtrigger.c.
    {
        //Print("RequestDelayedTriggerSpawn() " + this);
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SpawnTrigger, 100);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
Referenced by SpawnTrigger().
SpawnTrigger()
void UndergroundTriggerCarrierBase::SpawnTrigger () inline private
Definition at line 42 of file undergroundtrigger.c.
    {
        if (!CanSpawnTrigger())
        {
            RequestDelayedTriggerSpawn();
            return;
        }
        if (UndergroundAreaLoader.m_JsonData.Triggers && UndergroundAreaLoader.m_JsonData.Triggers.IsValidIndex(m_TriggerIndex))
        {
            JsonUndergroundAreaTriggerData data = UndergroundAreaLoader.m_JsonData.Triggers[m_TriggerIndex];
            UndergroundTrigger trigger = UndergroundTrigger.Cast(GetGame().CreateObjectEx( "UndergroundTrigger", GetPosition(), ECE_LOCAL ));
            if (trigger)
            {
                #ifdef DEVELOPER
                trigger.m_Local = true;
                #endif
                trigger.SetPosition(vector.Zero);
                if (GetOrientation() != vector.Zero)
                    trigger.SetOrientation(GetOrientation());
                AddChild(trigger,-1);
                trigger.Init(data);
                m_Trigger = trigger;
            }
        }
    }
References AddChild(), CanSpawnTrigger(), ECE_LOCAL, GetGame(), GetOrientation(), GetPosition, UndergroundAreaLoader::m_JsonData, RequestDelayedTriggerSpawn(), JsonUndergroundTriggers::Triggers, and vector::Zero.
Referenced by OnVariablesSynchronized().
UndergroundTriggerCarrier()
void UndergroundTriggerCarrierBase::UndergroundTriggerCarrier () inline private
Definition at line 8 of file undergroundtrigger.c.
    {
        RegisterNetSyncVariableInt("m_TriggerIndex", -1, 255);
    }
Member Data Documentation
m_Data
ref JsonUndergroundAreaTriggerData UndergroundTriggerCarrierBase::m_Data private
Definition at line 5 of file undergroundtrigger.c.
m_Trigger
UndergroundTrigger UndergroundTriggerCarrierBase::m_Trigger private
Definition at line 6 of file undergroundtrigger.c.