DayzKode: SceneData Class Reference
SceneData Class Reference
Private Member Functions
SceneObject AddObject (EntityAI e)
void Clear ()
SceneObject CreateSceneObject (string obj_name, vector pos)
ScenePlayer CreateScenePlayer ()
void DeleteSceneObject (SceneObject scene_object)
int GetInitDay ()
float GetInitFog ()
int GetInitHour ()
int GetInitMinute ()
int GetInitMonth ()
float GetInitOvercast ()
float GetInitRain ()
float GetInitTime ()
float GetInitWindForce ()
int GetInitYear ()
string GetNameMission ()
string GetNameScene ()
SceneObject GetSceneObjectByEntityAI (EntityAI e)
array< ref SceneObject > GetSceneObjects ()
array< ref SceneObject > GetSceneObjectsAll ()
array< ref ScenePlayer > GetScenePlayers ()
void SceneData ()
void SetInitDay (int value)
void SetInitFog (float value)
void SetInitHour (int value)
void SetInitMinute (int value)
void SetInitMonth (int value)
void SetInitOvercast (float value)
void SetInitRain (float value)
void SetInitTime (float time)
void SetInitWindForce (float value)
void SetInitYear (int value)
void SetNameMission (string name)
void SetNameScene (string name)
Private Attributes
protected ref array< ref SceneObject > m_AllObjs
protected int m_DateInitDay
protected int m_DateInitHour
protected int m_DateInitMinute
protected int m_DateInitMonth
protected int m_DateInitYear
protected float m_InitTime
protected string m_NameMission
protected string m_NameScene
protected ref array< ref SceneObject > m_Objects
protected ref array< ref ScenePlayer > m_Players
protected float m_WeaterInitFog
protected float m_WeaterInitOvercast
protected float m_WeaterInitRain
protected float m_WeaterInitWindForce
Detailed Description
Definition at line 1 of file scenedata.c.
Constructor & Destructor Documentation
SceneData()
void SceneData::SceneData () inline private
Definition at line 23 of file scenedata.c.
    {
        m_Objects = new array<ref SceneObject>;
        m_Players = new array<ref ScenePlayer>;
        m_AllObjs = new array<ref SceneObject>;
    }
References m_AllObjs, m_Objects, and m_Players.
Member Function Documentation
AddObject()
SceneObject SceneData::AddObject (EntityAI e) inline private
Definition at line 326 of file scenedata.c.
    {
        SceneObject sc_obj = new SceneObject();
        sc_obj.Init("player", e.GetPosition());
        sc_obj.LinkEntityAI( e );
        if ( sc_obj.IsPlayer() )
        {
            m_Players.Insert( ScenePlayer.Cast( sc_obj ) );
        }
        else
        {
            m_Objects.Insert( sc_obj );
        }
        return sc_obj;
    }
References SceneObject::Init(), SceneObject::IsPlayer(), SceneObject::LinkEntityAI(), m_Objects, and m_Players.
Clear()
void SceneData::Clear () inline private
Definition at line 316 of file scenedata.c.
    {
        m_Objects.Clear();
        m_Players.Clear();
        m_AllObjs.Clear();
    }
References m_AllObjs, m_Objects, and m_Players.
CreateSceneObject()
SceneObject SceneData::CreateSceneObject (string obj_name, vector pos) inline private
Definition at line 285 of file scenedata.c.
    {
        SceneObject sc_obj = new SceneObject();
        sc_obj.Init(obj_name, pos);
        if ( sc_obj != NULL )
        {
            m_Objects.Insert(sc_obj);
            return sc_obj;
        }
        return NULL;
    }
References SceneObject::Init(), and m_Objects.
Referenced by PluginConfigHandler::LoadSceneObjects().
CreateScenePlayer()
ScenePlayer SceneData::CreateScenePlayer () inline private
Definition at line 303 of file scenedata.c.
    {
        ScenePlayer sc_ply = new ScenePlayer();
        sc_ply.Init(STRING_EMPTY, Vector(0,0,0));
        m_Players.Insert(sc_ply);
//PrintString("CreateScenePlayer Add => "+ m_Players.Count().ToString());
        return sc_ply;
    }
References m_Players, STRING_EMPTY, and Vector().
Referenced by PluginConfigHandler::LoadScenePlayer().
DeleteSceneObject()
void SceneData::DeleteSceneObject (SceneObject scene_object) inline private
Definition at line 376 of file scenedata.c.
    {
        int index_p = m_Players.Find( ScenePlayer.Cast( scene_object ) );
        if ( index_p != -1 )
        {
            m_Players.Remove(index_p);
        }
        int index_o = m_Objects.Find(scene_object);
        if ( index_o != -1 )
        {
            m_Objects.Remove(index_o);
        }
    }
References m_Objects, and m_Players.
GetInitDay()
int SceneData::GetInitDay () inline private
Definition at line 157 of file scenedata.c.
    {
        return m_DateInitDay;
    }
References m_DateInitDay.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitFog()
float SceneData::GetInitFog () inline private
Definition at line 242 of file scenedata.c.
    {
        return m_WeaterInitFog;
    }
References m_WeaterInitFog.
Referenced by PluginConfigHandler::SaveSceneWeather(), and PluginLocalProfile::SceneSave().
GetInitHour()
int SceneData::GetInitHour () inline private
Definition at line 174 of file scenedata.c.
    {
        return m_DateInitHour;
    }
References m_DateInitHour.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitMinute()
int SceneData::GetInitMinute () inline private
Definition at line 191 of file scenedata.c.
    {
        return m_DateInitMinute;
    }
References m_DateInitMinute.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitMonth()
int SceneData::GetInitMonth () inline private
Definition at line 140 of file scenedata.c.
    {
        return m_DateInitMonth;
    }
References m_DateInitMonth.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetInitOvercast()
float SceneData::GetInitOvercast () inline private
Definition at line 208 of file scenedata.c.
    {
        return m_WeaterInitOvercast;
    }
References m_WeaterInitOvercast.
Referenced by PluginConfigHandler::SaveSceneWeather().
GetInitRain()
float SceneData::GetInitRain () inline private
Definition at line 225 of file scenedata.c.
    {
        return m_WeaterInitRain;
    }
References m_WeaterInitRain.
Referenced by PluginConfigHandler::SaveSceneWeather(), and PluginLocalProfile::SceneSave().
GetInitTime()
float SceneData::GetInitTime () inline private
Definition at line 106 of file scenedata.c.
    {
        return m_InitTime;
    }
References m_InitTime.
Referenced by PluginConfigHandler::SaveSceneSettings(), and PluginLocalProfile::SceneSave().
GetInitWindForce()
float SceneData::GetInitWindForce () inline private
Definition at line 259 of file scenedata.c.
    {
        return m_WeaterInitWindForce;
    }
References m_WeaterInitWindForce.
Referenced by PluginConfigHandler::SaveSceneWeather().
GetInitYear()
int SceneData::GetInitYear () inline private
Definition at line 123 of file scenedata.c.
    {
        return m_DateInitYear;
    }
References m_DateInitYear.
Referenced by PluginConfigHandler::SaveSceneSettings().
GetNameMission()
string SceneData::GetNameMission () inline private
Definition at line 90 of file scenedata.c.
    {
        return m_NameMission;
    }
References m_NameMission.
Referenced by PluginConfigHandler::SaveSceneSettings(), and PluginLocalProfile::SceneSave().
GetNameScene()
string SceneData::GetNameScene () inline private
Definition at line 74 of file scenedata.c.
    {
        return m_NameScene;
    }
References m_NameScene.
Referenced by PluginConfigHandler::SceneDataSave(), and PluginLocalProfile::SceneSave().
GetSceneObjectByEntityAI()
SceneObject SceneData::GetSceneObjectByEntityAI (EntityAI e) inline private
Definition at line 348 of file scenedata.c.
    {
        for ( int i = 0; i < m_Players.Count(); ++i )
        {
            EntityAI ply = m_Players.Get(i).GetObject();
            if ( ply != NULL && ply == e )
            {
                return m_Players.Get(i);
            }
        }
        for ( int j = 0; j < m_Objects.Count(); ++j )
        {
            EntityAI obj = m_Objects.Get(j).GetObject();
            if ( obj != NULL && obj == e )
            {
                return m_Objects.Get(j);
            }
        }
        return NULL;
    }
References m_Objects, and m_Players.
Referenced by PluginBase::OnRPCSyncSceneObject().
GetSceneObjects()
array< ref SceneObject > SceneData::GetSceneObjects () inline private
Definition at line 33 of file scenedata.c.
    {
        return m_Objects;
    }
References m_Objects.
Referenced by GetSceneObjectsAll(), PluginConfigHandler::SaveSceneObjects(), and PluginLocalProfile::SceneSave().
GetSceneObjectsAll()
array< ref SceneObject > SceneData::GetSceneObjectsAll () inline private
Definition at line 49 of file scenedata.c.
    {
        array<ref ScenePlayer> scene_players = GetScenePlayers();
        array<ref SceneObject> scene_object = GetSceneObjects();
        m_AllObjs.Clear();
        foreach (auto p: scene_players)
        {
            m_AllObjs.Insert(p);
        }
        foreach (auto o: scene_object)
        {
            m_AllObjs.Insert(o);
        }
        return m_AllObjs;
    }
References GetSceneObjects(), GetScenePlayers(), and m_AllObjs.
GetScenePlayers()
array< ref ScenePlayer > SceneData::GetScenePlayers () inline private
Definition at line 41 of file scenedata.c.
    {
        return m_Players;
    }
References m_Players.
Referenced by GetSceneObjectsAll(), and PluginConfigHandler::SaveScenePlayer().
SetInitDay()
void SceneData::SetInitDay (int value) inline private
Definition at line 165 of file scenedata.c.
    {
        m_DateInitDay = value;
        GetGame().GetWorld().SetDate( m_DateInitYear, m_DateInitMonth, m_DateInitDay, m_DateInitHour, m_DateInitMinute );
    }
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitFog()
void SceneData::SetInitFog (float value) inline private
Definition at line 250 of file scenedata.c.
    {
        m_WeaterInitFog = value;
        GetGame().GetWeather().GetFog().Set( value, 0, 1000 );
    }
References Weather::GetFog(), GetGame(), CGame::GetWeather(), m_WeaterInitFog, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitHour()
void SceneData::SetInitHour (int value) inline private
Definition at line 182 of file scenedata.c.
    {
        m_DateInitHour = value;
        GetGame().GetWorld().SetDate( m_DateInitYear, m_DateInitMonth, m_DateInitDay, m_DateInitHour, m_DateInitMinute );
    }
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitMinute()
void SceneData::SetInitMinute (int value) inline private
Definition at line 199 of file scenedata.c.
    {
        m_DateInitMinute = value;
        GetGame().GetWorld().SetDate( m_DateInitYear, m_DateInitMonth, m_DateInitDay, m_DateInitHour, m_DateInitMinute );
    }
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitMonth()
void SceneData::SetInitMonth (int value) inline private
Definition at line 148 of file scenedata.c.
    {
        m_DateInitMonth = value;
        GetGame().GetWorld().SetDate( m_DateInitYear, m_DateInitMonth, m_DateInitDay, m_DateInitHour, m_DateInitMinute );
    }
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitOvercast()
void SceneData::SetInitOvercast (float value) inline private
Definition at line 216 of file scenedata.c.
    {
        m_WeaterInitOvercast = value;
        GetGame().GetWeather().GetOvercast().Set( value, 0, 1000 );
    }
References GetGame(), Weather::GetOvercast(), CGame::GetWeather(), m_WeaterInitOvercast, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitRain()
void SceneData::SetInitRain (float value) inline private
Definition at line 233 of file scenedata.c.
    {
        m_WeaterInitRain = value;
        GetGame().GetWeather().GetRain().Set( value, 0, 1000 );
    }
References GetGame(), Weather::GetRain(), CGame::GetWeather(), m_WeaterInitRain, and WeatherPhenomenon::Set().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitTime()
void SceneData::SetInitTime (float time) inline private
Definition at line 114 of file scenedata.c.
    {
        m_InitTime = time;
    }
References m_InitTime.
Referenced by PluginConfigHandler::LoadSceneSettings().
SetInitWindForce()
void SceneData::SetInitWindForce (float value) inline private
Definition at line 267 of file scenedata.c.
    {
        // The following method SetWindSpeed does not support smaller values than 0.1!
        if (value > 0.1)
        {
            m_WeaterInitWindForce = value;
        }
        else
        {
            m_WeaterInitWindForce = 0.1;
        }
        GetGame().GetWeather().SetWindSpeed( m_WeaterInitWindForce );
    }
References GetGame(), CGame::GetWeather(), m_WeaterInitWindForce, and Weather::SetWindSpeed().
Referenced by PluginConfigHandler::LoadSceneWeather().
SetInitYear()
void SceneData::SetInitYear (int value) inline private
Definition at line 131 of file scenedata.c.
    {
        m_DateInitYear = value;
        GetGame().GetWorld().SetDate( m_DateInitYear, m_DateInitMonth, m_DateInitDay, m_DateInitHour, m_DateInitMinute );
    }
References GetGame(), CGame::GetWorld(), m_DateInitDay, m_DateInitHour, m_DateInitMinute, m_DateInitMonth, m_DateInitYear, and World::SetDate().
Referenced by PluginConfigHandler::LoadSceneSettings().
SetNameMission()
void SceneData::SetNameMission (string name) inline private
Definition at line 98 of file scenedata.c.
    {
        m_NameMission = name;
    }
References m_NameMission, and name.
Referenced by PluginConfigHandler::LoadSceneSettings().
SetNameScene()
void SceneData::SetNameScene (string name) inline private
Definition at line 82 of file scenedata.c.
    {
        m_NameScene = name;
    }
References m_NameScene, and name.
Referenced by PluginConfigHandler::SceneDataLoad().
Member Data Documentation
m_AllObjs
protected ref array<ref SceneObject> SceneData::m_AllObjs private
Definition at line 18 of file scenedata.c.
Referenced by Clear(), GetSceneObjectsAll(), and SceneData().
m_DateInitDay
protected int SceneData::m_DateInitDay private
Definition at line 8 of file scenedata.c.
Referenced by GetInitDay(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitHour
protected int SceneData::m_DateInitHour private
Definition at line 9 of file scenedata.c.
Referenced by GetInitHour(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitMinute
protected int SceneData::m_DateInitMinute private
Definition at line 10 of file scenedata.c.
Referenced by GetInitMinute(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitMonth
protected int SceneData::m_DateInitMonth private
Definition at line 7 of file scenedata.c.
Referenced by GetInitMonth(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_DateInitYear
protected int SceneData::m_DateInitYear private
Definition at line 6 of file scenedata.c.
Referenced by GetInitYear(), SetInitDay(), SetInitHour(), SetInitMinute(), SetInitMonth(), and SetInitYear().
m_InitTime
protected float SceneData::m_InitTime private
Definition at line 5 of file scenedata.c.
Referenced by GetInitTime(), and SetInitTime().
m_NameMission
protected string SceneData::m_NameMission private
Definition at line 4 of file scenedata.c.
Referenced by GetNameMission(), and SetNameMission().
m_NameScene
protected string SceneData::m_NameScene private
Definition at line 3 of file scenedata.c.
Referenced by GetNameScene(), and SetNameScene().
m_Objects
protected ref array<ref SceneObject> SceneData::m_Objects private
Definition at line 16 of file scenedata.c.
Referenced by AddObject(), Clear(), CreateSceneObject(), DeleteSceneObject(), GetSceneObjectByEntityAI(), GetSceneObjects(), and SceneData().
m_Players
protected ref array<ref ScenePlayer> SceneData::m_Players private
Definition at line 17 of file scenedata.c.
Referenced by AddObject(), Clear(), CreateScenePlayer(), DeleteSceneObject(), GetSceneObjectByEntityAI(), GetScenePlayers(), and SceneData().
m_WeaterInitFog
protected float SceneData::m_WeaterInitFog private
Definition at line 13 of file scenedata.c.
Referenced by GetInitFog(), and SetInitFog().
m_WeaterInitOvercast
protected float SceneData::m_WeaterInitOvercast private
Definition at line 11 of file scenedata.c.
Referenced by GetInitOvercast(), and SetInitOvercast().
m_WeaterInitRain
protected float SceneData::m_WeaterInitRain private
Definition at line 12 of file scenedata.c.
Referenced by GetInitRain(), and SetInitRain().
m_WeaterInitWindForce
protected float SceneData::m_WeaterInitWindForce private
Definition at line 14 of file scenedata.c.
Referenced by GetInitWindForce(), and SetInitWindForce().