DayzKode: AIBehaviourHLDataZombie2 Class Reference
AIBehaviourHLDataZombie2 Class Reference
Private Member Functions
private void AIBehaviourHLDataZombie2 ()
override void OnParseConfig ()
private void ~AIBehaviourHLDataZombie2 ()
Private Attributes
float m_fCrawlProbability
float m_fDamageToCrawl
Detailed Description
Definition at line 116 of file aibehaviour.c.
Constructor & Destructor Documentation
AIBehaviourHLDataZombie2()
private void AIBehaviourHLDataZombie2::AIBehaviourHLDataZombie2 () inline private
Definition at line 121 of file aibehaviour.c.
{}
~AIBehaviourHLDataZombie2()
private void AIBehaviourHLDataZombie2::~AIBehaviourHLDataZombie2 () inline private
Definition at line 122 of file aibehaviour.c.
{}
Member Function Documentation
OnParseConfig()
override void AIBehaviourHLDataZombie2::OnParseConfig () inline private
Definition at line 124 of file aibehaviour.c.
    {
        Print("zombie data parse config start");
        ParseBehaviourSlot("Calm");
        ParseBehaviourSlot("Attracted");
        ParseBehaviourSlot("Disturbed");
        ParseBehaviourSlot("Alerted");
        ParseAlertLevel("Calm");
        ParseAlertLevel("Disturbed");
        ParseAlertLevel("Attracted");
        ParseAlertLevel("Alerted");
        m_fDamageToCrawl = ReadParamValue("damageToCrawl",0.01);
        m_fCrawlProbability = ReadParamValue("crawlProbability",0.01);
        Print("zombie data parse config end");
    }
References m_fCrawlProbability, m_fDamageToCrawl, AIBehaviourHLData::ParseAlertLevel(), AIBehaviourHLData::ParseBehaviourSlot(), Print(), and AIBehaviourHLData::ReadParamValue().
Member Data Documentation
m_fCrawlProbability
float AIBehaviourHLDataZombie2::m_fCrawlProbability private
Definition at line 119 of file aibehaviour.c.
Referenced by OnParseConfig().
m_fDamageToCrawl
float AIBehaviourHLDataZombie2::m_fDamageToCrawl private
Definition at line 118 of file aibehaviour.c.
Referenced by OnParseConfig().