DayzKode: DayZInfectedInputController Class Reference
DayZInfectedInputController Class Reference
Private Member Functions
private void DayZInfectedInputController ()
never created by script
proto native int GetAlertLevel ()
proto native vector GetLookAtDirectionWS ()
proto native int GetMindState ()
proto native float GetMovementSpeed ()
proto native EntityAI GetTargetEntity ()
proto native float GetVaultHeight ()
proto native bool IsLookAtEnabled ()
proto native bool IsVault ()
proto native void OverrideMovementSpeed (bool pState, float pValue)
private void ~DayZInfectedInputController ()
never destroyed by script
Detailed Description
Definition at line 1 of file dayzinfectedinputcontroller.c.
Constructor & Destructor Documentation
DayZInfectedInputController()
private void DayZInfectedInputController::DayZInfectedInputController () inline private
never created by script
Definition at line 16 of file dayzinfectedinputcontroller.c.
    {
    }
~DayZInfectedInputController()
private void DayZInfectedInputController::~DayZInfectedInputController () inline private
never destroyed by script
Definition at line 21 of file dayzinfectedinputcontroller.c.
    {
    }
Member Function Documentation
GetAlertLevel()
proto native int DayZInfectedInputController::GetAlertLevel () private
GetLookAtDirectionWS()
proto native vector DayZInfectedInputController::GetLookAtDirectionWS () private
GetMindState()
proto native int DayZInfectedInputController::GetMindState () private
Referenced by DayZInfected::FightLogic(), AITargetCallbacksPlayer::GetVisionPointPositionWS(), and DayZInfected::HandleMindStateChange().
GetMovementSpeed()
proto native float DayZInfectedInputController::GetMovementSpeed () private
Referenced by DayZInfected::HandleMove().
GetTargetEntity()
proto native EntityAI DayZInfectedInputController::GetTargetEntity () private
Referenced by DayZInfected::ChaseAttackLogic(), and DayZInfected::FightAttackLogic().
GetVaultHeight()
proto native float DayZInfectedInputController::GetVaultHeight () private
Referenced by DayZInfected::HandleVault().
IsLookAtEnabled()
proto native bool DayZInfectedInputController::IsLookAtEnabled () private
IsVault()
proto native bool DayZInfectedInputController::IsVault () private
Referenced by DayZInfected::HandleVault().
OverrideMovementSpeed()
proto native void DayZInfectedInputController::OverrideMovementSpeed (bool pState, float pValue) private