DayzKode: ActionSingleUseBase Class Reference
ActionSingleUseBase Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPin ()
void ActionSingleUseBase ()
void ActionUnpin ()
override void CreateConditionComponents ()
override void CreateConditionComponents ()
override int GetActionCategory ()
override GetInputType ()
override bool HasTarget ()
override bool HasTarget ()
override void OnExecute (ActionData action_data)
override void OnExecute (ActionData action_data)
Detailed Description
Definition at line 41 of file actionsingleusebase.c.
Constructor & Destructor Documentation
ActionSingleUseBase()
void ActionSingleUseBase::ActionSingleUseBase () inline private
Definition at line 43 of file actionsingleusebase.c.
    {
        m_CallbackClass = ActionSingleUseBaseCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
    }
References AnimatedActionBase::m_CallbackClass, and AnimatedActionBase::m_CommandUID.
Member Function Documentation
ActionCondition() [1/2]
override bool ActionSingleUseBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file actionpin.c.
    {
        /*
        if ( item.IsInherited(Grenade_Base) )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_PINGRENAGE;
        }
        else
        */
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON;
        }
        Grenade_Base grenade = Grenade_Base.Cast(item);
        if( grenade )
        {
            if( !grenade.IsPinned() && grenade.IsPinnable() )
            {
                return true;
            }
        }
        return false;
    }
References Grenade_Base::IsPinnable(), and Grenade_Base::IsPinned().
ActionCondition() [2/2]
override bool ActionSingleUseBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file actionunpin.c.
    {
        if ( item.IsInherited(Grenade_Base) )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_UNPINGRENAGE;
        }
        else
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON;
        }
        Grenade_Base grenade = Grenade_Base.Cast(item);
        if( grenade )
        {
            if( grenade.IsPinned() )
            {
                return true;
            }
        }
        return false;
    }
References Grenade_Base::IsPinned().
ActionPin()
void ActionSingleUseBase::ActionPin () inline private
Definition at line 3 of file actionpin.c.
    {
        m_Text = "#pin";
    }
References m_Text.
ActionUnpin()
void ActionSingleUseBase::ActionUnpin () inline private
Definition at line 3 of file actionunpin.c.
    {
        m_Text = "#unpin";
    }
References m_Text.
CreateConditionComponents() [1/2]
override void ActionSingleUseBase::CreateConditionComponents () inline private
Definition at line 8 of file actionpin.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
CreateConditionComponents() [2/2]
override void ActionSingleUseBase::CreateConditionComponents () inline private
Definition at line 8 of file actionunpin.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int ActionSingleUseBase::GetActionCategory () inline private
Definition at line 54 of file actionsingleusebase.c.
    {
        return AC_SINGLE_USE;
    }
References AC_SINGLE_USE.
GetInputType()
override ActionSingleUseBase::GetInputType () inline private
Definition at line 49 of file actionsingleusebase.c.
    {
        return DefaultActionInput;
    }
HasTarget() [1/2]
override bool ActionSingleUseBase::HasTarget () inline private
Definition at line 14 of file actionpin.c.
    {
        return false;
    }
HasTarget() [2/2]
override bool ActionSingleUseBase::HasTarget () inline private
Definition at line 14 of file actionunpin.c.
    {
        return false;
    }
OnExecute() [1/2]
override void ActionSingleUseBase::OnExecute (ActionData action_data) inline private
Definition at line 44 of file actionpin.c.
    {
        Grenade_Base grenade = Grenade_Base.Cast(action_data.m_MainItem);
        if( grenade )
        {
            grenade.Pin();
        }
    }
References ActionData::m_MainItem, and Grenade_Base::Pin().
OnExecute() [2/2]
override void ActionSingleUseBase::OnExecute (ActionData action_data) inline private
Definition at line 42 of file actionunpin.c.
    {
        Grenade_Base grenade = Grenade_Base.Cast(action_data.m_MainItem);
        if( grenade )
        {
            grenade.Unpin();
        }
    }
References ActionData::m_MainItem, and Grenade_Base::Unpin().