DayzKode: ActionAttachToConstruction Class Reference
ActionAttachToConstruction Class Reference
Private Member Functions
void ActionAttachToConstruction ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void OnExecuteClient (ActionData action_data)
protected void OnExecuteImpl (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnStartClient (ActionData action_data)
Detailed Description
Definition at line 1 of file actionattachtoconstruction.c.
Constructor & Destructor Documentation
ActionAttachToConstruction()
void ActionAttachToConstruction::ActionAttachToConstruction () inline private
Definition at line 3 of file actionattachtoconstruction.c.
    {
        m_Text = "#attach";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAttachToConstruction::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 20 of file actionattachtoconstruction.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if ( target_entity && target_entity.CanUseConstruction() )
        {
            string selection = target_entity.GetActionComponentName( target.GetComponentIndex() );
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            int slot_id  = construction_action_data.GetAttachmentSlotFromSelection( player, target_entity, item, selection );
            BaseBuildingBase base_building;
            if ( slot_id != -1 )
            {
                base_building = BaseBuildingBase.Cast( target_entity );
                if ( base_building.CheckSlotVerticalDistance( slot_id, player ) && base_building.IsPlayerInside(player,"") )
                {
                    construction_action_data.SetSlotId( slot_id );
                    return true;
                }
            }
            else if ( item.IsKindOf("CombinationLock") )
            {
                base_building = BaseBuildingBase.Cast( target_entity );
                //simpler hack
                /*construction_action_data.SetSlotId( InventorySlots.GetSlotIdFromString("Att_CombinationLock") );
                return true;*/
                InventoryLocation loc = new InventoryLocation;
                bool found = base_building.GetInventory().FindFreeLocationFor(item,FindInventoryLocationType.ATTACHMENT,loc);
                if (found)
                {
                    //Print("slot name: " + InventorySlots.GetSlotName(loc.GetSlot()) );
                    construction_action_data.SetSlotId( loc.GetSlot() );
                    return true;
                }
            }
        }
        return false;
    }
References BaseBuildingBase::CheckSlotVerticalDistance(), ConstructionActionData::GetAttachmentSlotFromSelection(), InventoryLocation::GetSlot(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::SetSlotId().
CreateActionData()
override ActionData ActionAttachToConstruction::CreateActionData () inline private
Definition at line 14 of file actionattachtoconstruction.c.
    {
        AttachActionData action_data = new AttachActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionAttachToConstruction::CreateConditionComponents () inline private
Definition at line 8 of file actionattachtoconstruction.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
OnExecuteClient()
override void ActionAttachToConstruction::OnExecuteClient (ActionData action_data) inline private
Definition at line 106 of file actionattachtoconstruction.c.
    {
        ClearInventoryReservationEx(action_data);
        OnExecuteImpl(action_data);
    }
References ClearInventoryReservationEx(), and OnExecuteImpl().
OnExecuteImpl()
protected void ActionAttachToConstruction::OnExecuteImpl (ActionData action_data) inline private
Definition at line 72 of file actionattachtoconstruction.c.
    {
        EntityAI target_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        ItemBase item = ItemBase.Cast( action_data.m_MainItem );
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        int slot_id = construction_action_data.GetSlotId();
        if ( slot_id != -1 )
        {
            ItemBase attachment = ItemBase.Cast( target_entity.GetInventory().FindAttachment( slot_id ) );
            if ( attachment )
            {
                //combine
                attachment.CombineItemsClient( item );
            }
            else// if( target_entity.GetInventory().CanAddAttachmentEx( item, slot_id ) )
            {
                ItemBase item_base  = ItemBase.Cast( item );
                float stackable = item_base.GetTargetQuantityMax( slot_id );
                if( stackable == 0 || stackable >= item_base.GetQuantity() )
                {
                    action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_entity, item, slot_id);
                }
                else if( stackable != 0 && stackable < item_base.GetQuantity() )
                {
                    item_base.SplitIntoStackMaxClient( target_entity, slot_id );
                }
            }
        }
    }
References ConstructionActionData::GetSlotId(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void ActionAttachToConstruction::OnExecuteServer (ActionData action_data) inline private
Definition at line 112 of file actionattachtoconstruction.c.
    {
        if ( !GetGame().IsMultiplayer() )
        {
            ClearInventoryReservationEx(action_data);
            OnExecuteImpl(action_data); // single player
        }
    }
References ClearInventoryReservationEx(), GetGame(), and OnExecuteImpl().
OnStartClient()
override void ActionAttachToConstruction::OnStartClient (ActionData action_data) inline private
Definition at line 65 of file actionattachtoconstruction.c.
    {
        //set action initiator
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        construction_action_data.SetActionInitiator( action_data.m_Player );
    }
References ActionData::m_Player, and ConstructionActionData::SetActionInitiator().