DayzKode: ActionDisinfectPlant Class Reference
ActionDisinfectPlant Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDisinfectPlant ()
override void CreateConditionComponents ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
PlantBase m_Plant
Detailed Description
Definition at line 9 of file actiondisinfectplant.c.
Constructor & Destructor Documentation
ActionDisinfectPlant()
void ActionDisinfectPlant::ActionDisinfectPlant () inline private
Definition at line 13 of file actiondisinfectplant.c.
    {
        m_CallbackClass = ActionDisinfectPlantCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_SPRAYPLANT;
        //m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody = true;
        m_Text = "#apply";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionDisinfectPlant::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actiondisinfectplant.c.
    {
        GardenBase garden_base;
        if ( Class.CastTo(garden_base, target.GetObject()))
        {
            Slot slot;
            array<string> selections = new array<string>;
            garden_base.GetActionComponentNameList(target.GetComponentIndex(), selections);
            string selection;
            for (int s = 0; s < selections.Count(); s++)
            {
                selection = selections[s];
                slot = garden_base.GetSlotBySelection( selection );
                if (slot)
                    break;
            }
            if ( slot && slot.GetPlant() )
            {
                m_Plant = PlantBase.Cast(slot.GetPlant());
                if ( m_Plant.IsGrowing()  &&  m_Plant.NeedsSpraying() )
                {
                    if ( m_Plant.GetPlantStateIndex() < 1 )
                        return false;
                    if ( item.GetQuantity() > 0 )
                    {
                        return true;
                    }
                }
            }
        }
        return false;
        /*PlantBase plant;
        if ( Class.CastTo(plant,  target.GetObject() ) && !item.IsDamageDestroyed() )
        {
            if ( plant.IsGrowing()  &&  plant.NeedsSpraying() )
            {
                if ( item.GetQuantity() > 0 )
                {
                    return true;
                }
            }
        }
        return false;*/
    }
References Class::CastTo(), and m_Plant.
CreateConditionComponents()
override void ActionDisinfectPlant::CreateConditionComponents () inline private
Definition at line 25 of file actiondisinfectplant.c.
    {
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINotRuinedAndEmpty;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressClient()
override void ActionDisinfectPlant::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 91 of file actiondisinfectplant.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        Param1<float> nacdata = Param1<float>.Cast( action_data.m_ActionComponent.GetACData() );
        if (nacdata)
        {
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References CABase::GetACData(), ActionData::m_ActionComponent, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
OnFinishProgressServer()
override void ActionDisinfectPlant::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 81 of file actiondisinfectplant.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        Param1<float> nacdata = Param1<float>.Cast( action_data.m_ActionComponent.GetACData() );
        if (nacdata)
        {
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References CABase::GetACData(), ActionData::m_ActionComponent, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
Member Data Documentation
m_Plant
PlantBase ActionDisinfectPlant::m_Plant private
Definition at line 11 of file actiondisinfectplant.c.
Referenced by ActionCondition().