DayzKode: ActionOpenFence Class Reference
ActionOpenFence Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionOpenFence ()
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
ref NoiseParams m_NoisePar
const string SELECTION_INTERACT = "gate_interact"
Detailed Description
Definition at line 1 of file actionopenfence.c.
Constructor & Destructor Documentation
ActionOpenFence()
void ActionOpenFence::ActionOpenFence () inline private
Definition at line 6 of file actionopenfence.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#open";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionOpenFence::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file actionopenfence.c.
    {
        Object targetObject = target.GetObject();
        if ( targetObject && targetObject.CanUseConstruction() )
        {
            Fence fence = Fence.Cast( targetObject );
            if ( fence && fence.CanOpenFence() )
            {
                array<string> selections = new array<string>;
                targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections);
                for ( int i = 0; i < selections.Count(); i++ )
                {
                    if ( selections[i] == SELECTION_INTERACT )
                        return true;
                }
            }
        }
        return false;
    }
References SELECTION_INTERACT.
CreateConditionComponents()
override void ActionOpenFence::CreateConditionComponents () inline private
Definition at line 13 of file actionopenfence.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionOpenFence::OnEndServer (ActionData action_data) inline private
Definition at line 48 of file actionopenfence.c.
    {
        m_NoisePar = new NoiseParams();
        m_NoisePar.LoadFromPath("CfgVehicles SurvivorBase NoiseActionDefault");
        NoiseSystem noise = GetGame().GetNoiseSystem();
        if ( noise )
        {
            if ( action_data.m_Player )
                noise.AddNoisePos(action_data.m_Player, action_data.m_Target.GetObject().GetPosition(), m_NoisePar);
        }
    }
References NoiseSystem::AddNoisePos(), GetGame(), CGame::GetNoiseSystem(), m_NoisePar, ActionData::m_Player, ActionData::m_Target, and NoiseParams().
OnStartServer()
override void ActionOpenFence::OnStartServer (ActionData action_data) inline private
Definition at line 42 of file actionopenfence.c.
    {
        Fence fence = Fence.Cast( action_data.m_Target.GetObject() );
        fence.OpenFence();
    }
References ActionData::m_Target.
Member Data Documentation
m_NoisePar
ref NoiseParams ActionOpenFence::m_NoisePar private
Definition at line 3 of file actionopenfence.c.
Referenced by OnEndServer().
SELECTION_INTERACT
const string ActionOpenFence::SELECTION_INTERACT = "gate_interact" private
Definition at line 4 of file actionopenfence.c.
Referenced by ActionCondition().