DayzKode: DisinfectantAlcohol Class Reference
DisinfectantAlcohol Class Reference
Private Member Functions
override float GetDisinfectQuantity (int system=0, Param param1=null)
override void InitItemVariables ()
override void SetActions ()
Detailed Description
Definition at line 1 of file disinfectantalcohol.c.
Member Function Documentation
GetDisinfectQuantity()
override float DisinfectantAlcohol::GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 10 of file disinfectantalcohol.c.
    {
        return (GetQuantityMax() * 0.1);
    }
References GetQuantityMax().
InitItemVariables()
override void DisinfectantAlcohol::InitItemVariables () inline private
Definition at line 4 of file disinfectantalcohol.c.
    {
        super.InitItemVariables();
        can_this_be_combined = true;
    }
References can_this_be_combined.
SetActions()
override void DisinfectantAlcohol::SetActions () inline private
Definition at line 16 of file disinfectantalcohol.c.
    {
        super.SetActions();
        AddAction(ActionDisinfectTarget);
        AddAction(ActionDisinfectSelf);
        AddAction(ActionFillGeneratorTank);
        AddAction(ActionWashHandsItem);
        //AddAction(ActionForceDrinkAlcohol);
        //AddAction(ActionDrinkAlcohol);
    }
References ActionDisinfectSelf(), and AddAction().