DayzKode: CrashSoundSets Class Reference
CrashSoundSets Class Reference
Static Private Member Functions
static string GetSoundSetByHash (int hash)
static void RegisterSoundSet (string sound_set)
Static Private Attributes
static ref map< int, string > m_Mappings = new map<int, string>
Detailed Description
Definition at line 1 of file dayzgame.c.
Member Function Documentation
GetSoundSetByHash()
static string CrashSoundSets::GetSoundSetByHash (int hash) inline static private
Definition at line 10 of file dayzgame.c.
    {
        string sound_set;
        if(m_Mappings)
            m_Mappings.Find(hash,sound_set);
        return sound_set;
    }
References m_Mappings.
Referenced by OnRPC().
RegisterSoundSet()
static void CrashSoundSets::RegisterSoundSet (string sound_set) inline static private
Definition at line 5 of file dayzgame.c.
    {
        m_Mappings.Set(sound_set.Hash(), sound_set);
    }
References string::Hash(), and m_Mappings.
Referenced by House::Init().
Member Data Documentation
m_Mappings
ref map<int, string> CrashSoundSets::m_Mappings = new map<int, string> static private
Definition at line 3 of file dayzgame.c.
Referenced by GetSoundSetByHash(), and RegisterSoundSet().