DayzKode: ContaminationStage3Mdfr Class Reference
ContaminationStage3Mdfr Class Reference
Private Member Functions
override protected bool ActivateCondition (PlayerBase player)
override protected bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override protected void OnActivate (PlayerBase player)
override protected void OnDeactivate (PlayerBase player)
override protected void OnTick (PlayerBase player, float deltaT)
Static Private Attributes
static const int AGENT_THRESHOLD_ACTIVATE = 400
static const int AGENT_THRESHOLD_DEACTIVATE = AGENT_THRESHOLD_ACTIVATE - 1
static const int AGENT_THRESHOLD_FEVER = 250
static const float DAMAGE_PER_SEC = -3
Detailed Description
Definition at line 1 of file contamination3.c.
Member Function Documentation
ActivateCondition()
override protected bool ContaminationStage3Mdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 22 of file contamination3.c.
    {
        return ( player.GetSingleAgentCount(eAgents.CHEMICAL_POISON) >= AGENT_THRESHOLD_ACTIVATE );
    }
References AGENT_THRESHOLD_ACTIVATE.
Referenced by DeactivateCondition().
DeactivateCondition()
override protected bool ContaminationStage3Mdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 39 of file contamination3.c.
    {
        return !ActivateCondition(player);
    }
References ActivateCondition().
GetDebugText()
override string ContaminationStage3Mdfr::GetDebugText () inline private
Definition at line 17 of file contamination3.c.
    {
        return ("Activate threshold: "+AGENT_THRESHOLD_ACTIVATE + "| " +"Deativate threshold: "+AGENT_THRESHOLD_DEACTIVATE);
    }
References AGENT_THRESHOLD_ACTIVATE, and AGENT_THRESHOLD_DEACTIVATE.
Init()
override void ContaminationStage3Mdfr::Init () inline private
Definition at line 8 of file contamination3.c.
    {
        m_ID                    = eModifiers.MDF_CONTAMINATION3;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE_SHORT;
        m_SyncID                = eModifierSyncIDs.MODIFIER_SYNC_CONTAMINATION2;//using the same sync as stage 2 for now
        m_TrackActivatedTime    = true;
    }
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override protected void ContaminationStage3Mdfr::OnActivate (PlayerBase player) inline private
Definition at line 28 of file contamination3.c.
    {
        player.IncreaseDiseaseCount();
        player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_VOMIT);
    }
OnDeactivate()
override protected void ContaminationStage3Mdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 34 of file contamination3.c.
    {
        player.DecreaseDiseaseCount();
    }
OnTick()
override protected void ContaminationStage3Mdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 44 of file contamination3.c.
    {
        if(GetAttachedTime() > 4 && (!player.GetSymptomManager().GetCurrentPrimaryActiveSymptom() || (player.GetSymptomManager().GetCurrentPrimaryActiveSymptom() &&  player.GetSymptomManager().GetCurrentPrimaryActiveSymptom().GetType() != SymptomIDs.SYMPTOM_VOMIT)) )
        {
            player.AddHealth("","Shock", -100);
        }
        if (player.IsUnconscious())
        {
            player.AddHealth("","",DAMAGE_PER_SEC * deltaT);
        }
    }
References DAMAGE_PER_SEC, and GetAttachedTime().
Member Data Documentation
AGENT_THRESHOLD_ACTIVATE
const int ContaminationStage3Mdfr::AGENT_THRESHOLD_ACTIVATE = 400 static private
Definition at line 3 of file contamination3.c.
Referenced by ActivateCondition(), and GetDebugText().
AGENT_THRESHOLD_DEACTIVATE
const int ContaminationStage3Mdfr::AGENT_THRESHOLD_DEACTIVATE = AGENT_THRESHOLD_ACTIVATE - 1 static private
Definition at line 4 of file contamination3.c.
Referenced by GetDebugText().
AGENT_THRESHOLD_FEVER
const int ContaminationStage3Mdfr::AGENT_THRESHOLD_FEVER = 250 static private
Definition at line 5 of file contamination3.c.
DAMAGE_PER_SEC
const float ContaminationStage3Mdfr::DAMAGE_PER_SEC = -3 static private
Definition at line 6 of file contamination3.c.
Referenced by OnTick().