DayzKode: MouseButtonInfo Class Reference
MouseButtonInfo Class Reference
Private Member Functions
int GetButtonID ()
int GetTimeLastPress ()
int GetTimeLastRelease ()
bool IsButtonDown ()
void MouseButtonInfo (int button)
void Press ()
void Release ()
Private Attributes
private int m_ButtonID
private int m_TimeLastPress
private int m_TimeLastRelease
Detailed Description
Definition at line 1 of file mousebuttoninfo.c.
Constructor & Destructor Documentation
MouseButtonInfo()
void MouseButtonInfo::MouseButtonInfo (int button) inline private
Definition at line 7 of file mousebuttoninfo.c.
    {
        m_ButtonID          = button;
        m_TimeLastPress     = -1;
        m_TimeLastRelease   = -1;
    }
References m_ButtonID, m_TimeLastPress, and m_TimeLastRelease.
Member Function Documentation
GetButtonID()
int MouseButtonInfo::GetButtonID () inline private
Definition at line 14 of file mousebuttoninfo.c.
    {
        return m_ButtonID;
    }
References m_ButtonID.
Referenced by PluginBase::GetMouseButtonInfo(), and PluginBase::OnFrame().
GetTimeLastPress()
int MouseButtonInfo::GetTimeLastPress () inline private
Definition at line 19 of file mousebuttoninfo.c.
    {
        return m_TimeLastPress;
    }
References m_TimeLastPress.
Referenced by PluginBase::OnFrame(), and PluginBase::OnMouseButtonRelease().
GetTimeLastRelease()
int MouseButtonInfo::GetTimeLastRelease () inline private
Definition at line 24 of file mousebuttoninfo.c.
    {
        return m_TimeLastRelease;
    }
References m_TimeLastRelease.
Referenced by PluginBase::OnMouseButtonRelease().
IsButtonDown()
bool MouseButtonInfo::IsButtonDown () inline private
Definition at line 39 of file mousebuttoninfo.c.
    {
        if ( m_TimeLastRelease < m_TimeLastPress )
        {
            return true;
        }
        return false;
    }
References m_TimeLastPress, and m_TimeLastRelease.
Referenced by PluginBase::OnFrame().
Press()
void MouseButtonInfo::Press () inline private
Definition at line 29 of file mousebuttoninfo.c.
    {
        m_TimeLastPress = GetGame().GetTime();
    }
References GetGame(), CGame::GetTime(), and m_TimeLastPress.
Referenced by PluginBase::OnMouseButtonPress().
Release()
void MouseButtonInfo::Release () inline private
Definition at line 34 of file mousebuttoninfo.c.
    {
        m_TimeLastRelease = GetGame().GetTime();
    }
References GetGame(), CGame::GetTime(), and m_TimeLastRelease.
Referenced by PluginBase::OnMouseButtonRelease().
Member Data Documentation
m_ButtonID
private int MouseButtonInfo::m_ButtonID private
Definition at line 3 of file mousebuttoninfo.c.
Referenced by GetButtonID(), and MouseButtonInfo().
m_TimeLastPress
private int MouseButtonInfo::m_TimeLastPress private
Definition at line 4 of file mousebuttoninfo.c.
Referenced by GetTimeLastPress(), IsButtonDown(), MouseButtonInfo(), and Press().
m_TimeLastRelease
private int MouseButtonInfo::m_TimeLastRelease private
Definition at line 5 of file mousebuttoninfo.c.
Referenced by GetTimeLastRelease(), IsButtonDown(), MouseButtonInfo(), and Release().