DayzKode: ScrollBarContainer Class Reference
ScrollBarContainer Class Reference
Private Member Functions
float GetContentYPos ()
float GetRootHeight ()
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
override bool OnResize (Widget w, int x, int y)
void OnWidgetScriptInit (Widget w)
void ScrollFixedAmount (bool down, float amount)
void ScrollToBottom ()
void ScrollToPos (float pos)
void ScrollToTop ()
protected void StopScrolling ()
protected void UpdateScroll (int mouse_x, int mouse_y, bool is_dragging)
void UpdateScroller ()
void ~ScrollBarContainer ()
Private Attributes
protected Widget Content
reference bool Invert
protected float m_content_height
protected float m_position
protected Widget m_root
protected float m_root_height
protected bool m_scrolling
protected int m_scrolling_mouse_pos
protected float m_scrolling_start_pos
protected Widget ScrollBar
protected Widget Scroller
const int WHEEL_STEP = 20
Detailed Description
Definition at line 2 of file scrollbarcontainer.c.
Constructor & Destructor Documentation
~ScrollBarContainer()
void ScrollBarContainer::~ScrollBarContainer () inline private
Definition at line 18 of file scrollbarcontainer.c.
    {
        //if(GetGame() != NULL)
        //GetGame().GetDragQueue().RemoveCalls(this);
    }
Member Function Documentation
GetContentYPos()
float ScrollBarContainer::GetContentYPos () inline private
Definition at line 92 of file scrollbarcontainer.c.
    {
        float x, y;
        Content.GetPos(x, y);
        return y;
    }
References Content, x, and y.
GetRootHeight()
float ScrollBarContainer::GetRootHeight () inline private
Definition at line 99 of file scrollbarcontainer.c.
    {
        return m_root_height;
    }
References m_root_height.
OnMouseButtonDown()
override bool ScrollBarContainer::OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 197 of file scrollbarcontainer.c.
    {
        if (button == MouseState.LEFT && w == Scroller && !m_scrolling)
        {
            m_scrolling = true;
            m_scrolling_start_pos = m_position;
            int mouse_x;
            GetMousePos(mouse_x, m_scrolling_mouse_pos);
            GetGame().GetDragQueue().Call(this, "UpdateScroll");
            return true;
        }
        return false;
    }
References CGame::GetDragQueue(), GetGame(), GetMousePos(), m_position, m_scrolling, m_scrolling_mouse_pos, m_scrolling_start_pos, and Scroller.
OnMouseButtonUp()
override bool ScrollBarContainer::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 213 of file scrollbarcontainer.c.
    {
        StopScrolling();
        return false;
    }
References StopScrolling().
OnMouseWheel()
override bool ScrollBarContainer::OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 220 of file scrollbarcontainer.c.
    {
        if (m_scrolling || m_content_height <= m_root_height) return false;
        float step = (1.0 / (m_content_height - m_root_height)) * WHEEL_STEP;
        m_position -= wheel * step;
        if (m_position < 0) m_position = 0;
        if (m_position > 1) m_position = 1;
        UpdateScroller();
        return true;
    }
References m_content_height, m_position, m_root_height, m_scrolling, UpdateScroller(), and WHEEL_STEP.
OnResize()
override bool ScrollBarContainer::OnResize (Widget w, int x, int y) inline private
Definition at line 233 of file scrollbarcontainer.c.
{
        if (w == m_root || w == Content)
        {
            UpdateScroller();
        }
        return false;
    }
References Content, m_root, and UpdateScroller().
OnWidgetScriptInit()
void ScrollBarContainer::OnWidgetScriptInit (Widget w) inline private
Definition at line 146 of file scrollbarcontainer.c.
    {
        m_root = w;
        m_root.SetHandler(this);
        m_root.SetFlags(WidgetFlags.VEXACTPOS);
        m_scrolling = false;
        UpdateScroller();
    }
References m_root, m_scrolling, and UpdateScroller().
ScrollFixedAmount()
void ScrollBarContainer::ScrollFixedAmount (bool down, float amount) inline private
Definition at line 24 of file scrollbarcontainer.c.
    {
        m_root.Update();
        Content.Update();
        float width;
        m_root.GetScreenSize(width, m_root_height);
        Content.GetScreenSize(width, m_content_height);
        float diff = m_root_height / m_content_height;
        float one_percent = diff / 100;
        float percents = amount / m_content_height;
        //float step = (1.0 / (m_content_height - m_root_height)) * WHEEL_STEP;
        float step = (percents/100);
        if(down)
        m_position += 1 * ( percents + 0.05 );
        else
        m_position -= 1 * ( percents + 0.05 );
        if (m_position < 0) m_position = 0;
        if (m_position > 1 - diff) m_position = 1 - diff;
        UpdateScroller();
    }
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToBottom()
void ScrollBarContainer::ScrollToBottom () inline private
Definition at line 69 of file scrollbarcontainer.c.
    {
        m_root.Update();
        Content.Update();
        float width;
        m_root.GetScreenSize(width, m_root_height);
        Content.GetScreenSize(width, m_content_height);
        float diff = m_root_height / m_content_height;
        m_position = 1 - diff;
        UpdateScroller();
    }
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToPos()
void ScrollBarContainer::ScrollToPos (float pos) inline private
Definition at line 48 of file scrollbarcontainer.c.
    {
        m_root.Update();
        Content.Update();
        float width;
        m_root.GetScreenSize(width, m_root_height);
        Content.GetScreenSize(width, m_content_height);
        float diff = m_root_height / m_content_height;
        float percents = pos / m_content_height;
        m_position = percents;
        if (m_position < 0)
            m_position = 0;
        if (m_position > 1 - diff)
            m_position = 1 - diff;
        UpdateScroller();
    }
References Content, m_content_height, m_position, m_root, m_root_height, and UpdateScroller().
ScrollToTop()
void ScrollBarContainer::ScrollToTop () inline private
Definition at line 83 of file scrollbarcontainer.c.
    {
        if( m_position != 0 )
        {
            m_position = 0;
            UpdateScroller();
        }
    }
References m_position, and UpdateScroller().
StopScrolling()
protected void ScrollBarContainer::StopScrolling () inline private
Definition at line 155 of file scrollbarcontainer.c.
    {
        if (m_scrolling)
        {
            GetGame().GetDragQueue().RemoveCalls(this);
            m_scrolling = false;
        }
    }
References CGame::GetDragQueue(), GetGame(), and m_scrolling.
Referenced by OnMouseButtonUp(), and UpdateScroll().
UpdateScroll()
protected void ScrollBarContainer::UpdateScroll (int mouse_x, int mouse_y, bool is_dragging) inline private
Definition at line 164 of file scrollbarcontainer.c.
    {
        m_root.Update();
        Content.Update();
        float width;
        m_root.GetScreenSize(width, m_root_height);
        Content.GetScreenSize(width, m_content_height);
        if (m_scrolling)
        {
            if (is_dragging)
            {
                float diff = (mouse_y - m_scrolling_mouse_pos);
                float scroller_height = (m_root_height / m_content_height) * m_root_height;
                m_position = m_scrolling_start_pos + (diff / (m_root_height - scroller_height));
                if (m_position < 0) m_position = 0;
                if (m_position > 1) m_position = 1;
            }
            else
            {
                m_scrolling = false;
                StopScrolling();
            }
        }
        UpdateScroller();
    }
References Content, m_content_height, m_position, m_root, m_root_height, m_scrolling, m_scrolling_mouse_pos, m_scrolling_start_pos, StopScrolling(), and UpdateScroller().
UpdateScroller()
void ScrollBarContainer::UpdateScroller () inline private
Definition at line 104 of file scrollbarcontainer.c.
    {
        m_root.Update();
        Content.Update();
        float width;
        float height;
        float diff;
        float scroller_height;
        m_root.GetScreenSize(width, m_root_height);
        Content.GetScreenSize(width, m_content_height);
        diff = m_content_height - m_root_height;
        if (diff <= 0)
        {
            Content.SetPos(0,0);
            Scroller.Show(false);
            ScrollBar.Show(false);
            m_position = 0;
            return;
        }
        scroller_height = (m_root_height / m_content_height) * m_root_height;
        ScrollBar.Show(true);
        Scroller.Show(true);
        Scroller.GetSize(width, height);
        Scroller.SetSize(width, scroller_height);
        float pos = ( -m_content_height * m_position );
        if( pos <= -diff )
            pos = -diff;
        Scroller.SetPos(0, -pos);
        if(Invert)
            Content.SetPos(0, -(diff + (-diff * m_position)));
        else
            Content.SetPos(0, pos);
    }
References Content, Invert, m_content_height, m_position, m_root, m_root_height, ScrollBar, and Scroller.
Referenced by OnMouseWheel(), OnResize(), OnWidgetScriptInit(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), ScrollToTop(), and UpdateScroll().
Member Data Documentation
Content
protected Widget ScrollBarContainer::Content private
Definition at line 5 of file scrollbarcontainer.c.
Referenced by GetContentYPos(), OnResize(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
Invert
reference bool ScrollBarContainer::Invert private
Definition at line 4 of file scrollbarcontainer.c.
Referenced by UpdateScroller().
m_content_height
protected float ScrollBarContainer::m_content_height private
Definition at line 12 of file scrollbarcontainer.c.
Referenced by OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_position
protected float ScrollBarContainer::m_position private
Definition at line 13 of file scrollbarcontainer.c.
Referenced by OnMouseButtonDown(), OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), ScrollToTop(), UpdateScroll(), and UpdateScroller().
m_root
protected Widget ScrollBarContainer::m_root private
Definition at line 8 of file scrollbarcontainer.c.
Referenced by OnResize(), OnWidgetScriptInit(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_root_height
protected float ScrollBarContainer::m_root_height private
Definition at line 11 of file scrollbarcontainer.c.
Referenced by GetRootHeight(), OnMouseWheel(), ScrollFixedAmount(), ScrollToBottom(), ScrollToPos(), UpdateScroll(), and UpdateScroller().
m_scrolling
protected bool ScrollBarContainer::m_scrolling private
Definition at line 14 of file scrollbarcontainer.c.
Referenced by OnMouseButtonDown(), OnMouseWheel(), OnWidgetScriptInit(), StopScrolling(), and UpdateScroll().
m_scrolling_mouse_pos
protected int ScrollBarContainer::m_scrolling_mouse_pos private
Definition at line 16 of file scrollbarcontainer.c.
Referenced by OnMouseButtonDown(), and UpdateScroll().
m_scrolling_start_pos
protected float ScrollBarContainer::m_scrolling_start_pos private
Definition at line 15 of file scrollbarcontainer.c.
Referenced by OnMouseButtonDown(), and UpdateScroll().
ScrollBar
protected Widget ScrollBarContainer::ScrollBar private
Definition at line 6 of file scrollbarcontainer.c.
Referenced by UpdateScroller().
Scroller
protected Widget ScrollBarContainer::Scroller private
Definition at line 7 of file scrollbarcontainer.c.
Referenced by OnMouseButtonDown(), and UpdateScroller().
WHEEL_STEP
const int ScrollBarContainer::WHEEL_STEP = 20 private
Definition at line 10 of file scrollbarcontainer.c.
Referenced by OnMouseWheel().