DayzKode: BIOSErrorModule Class Reference
BIOSErrorModule Class Reference
Private Member Functions
void BIOSErrorModule ()
override void FillErrorDataMap ()
override void InitOptionalVariables ()
void InsertBIOSError (int code, string message)
Detailed Description
Definition at line 62 of file bioserrormodule.c.
Constructor & Destructor Documentation
BIOSErrorModule()
void BIOSErrorModule::BIOSErrorModule () inline private
Definition at line 64 of file bioserrormodule.c.
    {
        SetCategory(ErrorCategory.BIOSError);
    }
Member Function Documentation
FillErrorDataMap()
override void BIOSErrorModule::FillErrorDataMap () inline private
Definition at line 76 of file bioserrormodule.c.
    {
        super.FillErrorDataMap();
        InsertErrorProperties(EBiosError.OK); // Not an error, so no message
        InsertBIOSError(EBiosError.CANCEL                               , "#STR_BIOS_OperationCancelled");
        InsertBIOSError(EBiosError.BAD_PARAMETER                        , "#STR_BIOS_BadParameter");
        InsertBIOSError(EBiosError.NOT_FOUND                            , "#STR_BIOS_NotFound");
        InsertBIOSError(EBiosError.NOT_IMPLEMENTED                      , "#STR_BIOS_NotImplemented");
        InsertBIOSError(EBiosError.PURCHASE_REQUIRED                    , "#STR_BIOS_PurchaseRequired");
        InsertBIOSError(EBiosError.NOT_ALLOWED                          , "#STR_BIOS_ActionRestricted");
        InsertBIOSError(EBiosError.BANNED                               , "#STR_auth_publisher_ban");
        InsertBIOSError(EBiosError.LOGICAL                              , "#STR_BIOS_APILogicError");
        InsertBIOSError(EBiosError.WRONG_RESPONSE_DATA                  , "#STR_BIOS_UnexpectedFormat");
        InsertBIOSError(EBiosError.SERVER_HEARTBEAT_SERVER_NOT_FOUND    , "#STR_BIOS_ServerNotRegistered");
        InsertBIOSError(EBiosError.SERVER_REGISTER_ALREADY_EXISTS       , "#STR_BIOS_ServerAlreadyRegistered");
        InsertBIOSError(EBiosError.REQUEST_CREATE_FAIL_XHR              , "#STR_BIOS_FailedToOpenRequest");
        InsertBIOSError(EBiosError.REQUEST_SEND_FAIL                    , "#STR_BIOS_FailedToSendData");
        InsertBIOSError(EBiosError.REQUEST_WAIT_FAIL                    , "#STR_BIOS_FailedToWaitOperationEnd");
        InsertBIOSError(EBiosError.NON_JSON_RESPONSE                    , "#STR_BIOS_UnexpectedFormat");
        InsertBIOSError(EBiosError.UPDATE_REQUIRED                      , "#STR_BIOS_UpdateRequired");
        InsertBIOSError(EBiosError.UPDATE_REQUIRED_AND_DOWNLOADED       , "#STR_BIOS_UpdateRequiredAndDownloaded");
        InsertBIOSError(EBiosError.COMUNICATION_ERROR                   , "#STR_BIOS_CommunicationError");
        InsertBIOSError(EBiosError.UNKNOWN                              , "#server_browser_error_unknown");
        InsertBIOSError(EBiosError.BAD_SCRIPT                           , "#STR_BIOS_LinkageError");
    }
References InsertBIOSError(), and InsertErrorProperties().
InitOptionalVariables()
override void BIOSErrorModule::InitOptionalVariables () inline private
Definition at line 69 of file bioserrormodule.c.
    {
        super.InitOptionalVariables();
        m_Header = "#STR_BIOS_BIOSError";
    }
References m_Header.
InsertBIOSError()
void BIOSErrorModule::InsertBIOSError (int code, string message) inline private
Definition at line 110 of file bioserrormodule.c.
    {
        #ifdef PLATFORM_CONSOLE
        InsertDialogueErrorProperties(code, message);
        #else
        InsertErrorProperties(code, message);
        #endif
    }
References InsertDialogueErrorProperties(), and InsertErrorProperties().
Referenced by FillErrorDataMap().