DayzKode: OptionSelectorBase Class Reference
OptionSelectorBase Class Reference
Private Member Functions
override void ColorDisabledConsole (Widget w)
override void ColorHighlight (Widget w)
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
override void ColorNormal (Widget w)
override void ColorNormalConsole (Widget w)
void ColorOption ()
override void Disable ()
override void Disable ()
override void Disable ()
override void Enable ()
override void Enable ()
override void Enable ()
array< string > GetOptions ()
string GetStringValue ()
string GetValue ()
float GetValue ()
bool IsEnabled ()
override bool IsFocusable (Widget w)
override bool IsFocusable (Widget w)
override bool IsFocusable (Widget w)
bool IsSelectorEnabled ()
Returns false for the selector in 'disabled' states.
bool IsSet ()
float NormalizeInput (float value)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
void OptionSelector (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled)
void OptionSelectorEditbox (Widget parent, string value, ScriptedWidgetEventHandler parent_menu, bool disabled)
void Reset ()
void SetNextOption ()
void SetPrevOption ()
void SetStep (float step)
void SetStringOption (string option, bool fire_event=true)
void SetValue (float value, bool update=true)
void SetValue (string value, bool update=true)
void ~OptionSelector ()
void ~OptionSelectorEditbox ()
void ~OptionSelectorSliderSetup ()
Private Attributes
protected EditBoxWidget m_EditBox
protected float m_MaxValue
protected float m_MinValue
protected Widget m_NextOption
protected ref array< string > m_Options
protected Widget m_PreviousOption
protected TextWidget m_SelectedOption
protected int m_SelectedOptionIndex
protected SliderWidget m_Slider
Detailed Description
Definition at line 1 of file optionselector.c.
Constructor & Destructor Documentation
~OptionSelector()
void OptionSelectorBase::~OptionSelector () inline private
Definition at line 58 of file optionselector.c.
    {
        delete m_Root;
    }
References m_Root.
~OptionSelectorEditbox()
void OptionSelectorBase::~OptionSelectorEditbox () inline private
Definition at line 26 of file optionselectoreditbox.c.
    {
        delete m_Root;
    }
References m_Root.
~OptionSelectorSliderSetup()
void OptionSelectorBase::~OptionSelectorSliderSetup () inline private
Definition at line 7 of file optionselectorslidersetup.c.
    {
        delete m_Root;
    }
References m_Root.
Member Function Documentation
ColorDisabledConsole()
override void OptionSelectorBase::ColorDisabledConsole (Widget w) inline private
Definition at line 266 of file optionselector.c.
    {
        super.ColorDisabledConsole(w);
        if (!w)
            return;
        if (m_SelectedOption)
        {
            m_SelectedOption.SetColor(ARGB(120,255,255,255));
            //m_Root.SetColor(ARGB(120,0,255,0));
        }
    }
References ARGB().
Referenced by ScriptedWidgetEventHandler::Disable().
ColorHighlight() [1/2]
override void OptionSelectorBase::ColorHighlight (Widget w) inline private
Definition at line 145 of file optionselectoreditbox.c.
    {
        if( !w )
            return;
        if ( m_EditBox )
        {
            SetFocus( m_EditBox );
            m_EditBox.SetColor( ARGB(255, 200, 0, 0) );
        }
        super.ColorHighlight( w );
    }
References ARGB(), and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseEnter(), and OnMouseEnter().
ColorHighlight() [2/2]
override void OptionSelectorBase::ColorHighlight (Widget w) inline private
Definition at line 133 of file optionselectorslidersetup.c.
    {
        if( !w )
            return;
        if ( m_Slider )
        {
            SetFocus( m_Slider );
            m_Slider.SetColor( ARGB(255, 200, 0, 0) );
        }
        super.ColorHighlight( w );
    }
References ARGB(), and SetFocus().
ColorNormal() [1/2]
override void OptionSelectorBase::ColorNormal (Widget w) inline private
Definition at line 159 of file optionselectoreditbox.c.
    {
        if( !w )
            return;
        if ( m_EditBox )
        {
            m_EditBox.SetColor( ARGB(140, 255, 255, 255) );
        }
        super.ColorNormal( w );
    }
References ARGB().
Referenced by ScriptedWidgetEventHandler::Enable(), ScriptedWidgetEventHandler::OnMouseLeave(), and OnMouseLeave().
ColorNormal() [2/2]
override void OptionSelectorBase::ColorNormal (Widget w) inline private
Definition at line 147 of file optionselectorslidersetup.c.
    {
        if( !w )
            return;
        if ( m_Slider )
        {
            m_Slider.SetColor( ARGB(140, 255, 255, 255) );
        }
        super.ColorNormal( w );
    }
References ARGB().
ColorNormalConsole()
override void OptionSelectorBase::ColorNormalConsole (Widget w) inline private
Definition at line 252 of file optionselector.c.
    {
        super.ColorNormalConsole(w);
        if (!w)
            return;
        if (m_SelectedOption)
        {
            m_SelectedOption.SetColor(ARGB(255,255,255,255));
            //m_Root.SetColor(ARGB(255,0,0,255));
        }
    }
References ARGB().
Referenced by ScriptedWidgetEventHandler::Enable(), ScriptedWidgetEventHandler::OnFocusLost(), and ScriptedWidgetEventHandler::OnMouseLeave().
ColorOption()
void OptionSelectorBase::ColorOption () inline private
Definition at line 193 of file optionselector.c.
    {
        switch( m_SelectedOptionIndex )
        {
            case 0:
            {
                m_SelectedOption.SetColor( ARGB( 255, 255, 255, 255 ) );
                break;
            }
            case 1:
            {
                m_SelectedOption.SetColor( ARGB( 255, 0, 255, 0 ) );
                break;
            }
            case 2:
            {
                m_SelectedOption.SetColor( ARGB( 255, 255, 0, 0 ) );
                break;
            }
        }
    }
References ARGB().
Disable() [1/3]
override void OptionSelectorBase::Disable () inline private
Definition at line 238 of file optionselector.c.
    {
        super.Disable();
        #ifndef PLATFORM_CONSOLE
            m_NextOption.SetFlags( WidgetFlags.IGNOREPOINTER );
            m_NextOption.Show( false );
            m_PreviousOption.SetFlags( WidgetFlags.IGNOREPOINTER );
            m_PreviousOption.Show( false );
        #else
            m_Parent.SetFlags(WidgetFlags.NOFOCUS);
            //m_Parent.Show(false);
        #endif
    }
References m_Parent.
Disable() [2/3]
override void OptionSelectorBase::Disable () inline private
Definition at line 38 of file optionselectoreditbox.c.
    {
        super.Disable();
        m_EditBox.SetFlags( WidgetFlags.IGNOREPOINTER );
    }
Disable() [3/3]
override void OptionSelectorBase::Disable () inline private
Definition at line 19 of file optionselectorslidersetup.c.
    {
        super.Disable();
        m_Slider.SetFlags( WidgetFlags.IGNOREPOINTER );
    }
Enable() [1/3]
override void OptionSelectorBase::Enable () inline private
Definition at line 224 of file optionselector.c.
    {
        super.Enable();
        #ifndef PLATFORM_CONSOLE
            m_NextOption.ClearFlags( WidgetFlags.IGNOREPOINTER );
            m_NextOption.Show( true );
            m_PreviousOption.ClearFlags( WidgetFlags.IGNOREPOINTER );
            m_PreviousOption.Show( true );
        #else
            m_Parent.ClearFlags(WidgetFlags.NOFOCUS);
            //m_Parent.Show(true);
        #endif
    }
References m_Parent.
Referenced by OptionSelectorEditbox().
Enable() [2/3]
override void OptionSelectorBase::Enable () inline private
Definition at line 31 of file optionselectoreditbox.c.
    {
        super.Enable();
        m_EditBox.ClearFlags( WidgetFlags.IGNOREPOINTER );
    }
Enable() [3/3]
override void OptionSelectorBase::Enable () inline private
Definition at line 12 of file optionselectorslidersetup.c.
    {
        super.Enable();
        m_Slider.ClearFlags( WidgetFlags.IGNOREPOINTER );
    }
GetOptions()
array< string > OptionSelectorBase::GetOptions () inline private
Definition at line 140 of file optionselector.c.
    {
        return m_Options;
    }
GetStringValue()
string OptionSelectorBase::GetStringValue () inline private
Definition at line 174 of file optionselector.c.
    {
        return m_Options.Get( m_SelectedOptionIndex );
    }
References string::Get().
GetValue() [1/2]
string OptionSelectorBase::GetValue () inline private
Definition at line 140 of file optionselectoreditbox.c.
    {
        return m_EditBox.GetText();
    }
Referenced by OnChange(), and SetValue().
GetValue() [2/2]
float OptionSelectorBase::GetValue () inline private
Definition at line 127 of file optionselectorslidersetup.c.
    {
        float ret = ( m_Slider.GetCurrent() * ( m_MaxValue - m_MinValue ) ) + m_MinValue;
        return ret;
    }
References m_MaxValue, and m_MinValue.
IsEnabled()
bool OptionSelectorBase::IsEnabled () inline private
Definition at line 151 of file optionselector.c.
    {
        return m_SelectedOptionIndex == 1;
    }
IsFocusable() [1/3]
override bool OptionSelectorBase::IsFocusable (Widget w) inline private
Definition at line 215 of file optionselector.c.
    {
        if( w )
        {
            return ( w == m_Parent || w == m_NextOption || w == m_PreviousOption );
        }
        return false;
    }
References m_Parent.
Referenced by ScriptedWidgetEventHandler::OnFocus(), ScriptedWidgetEventHandler::OnMouseEnter(), OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), and OnMouseLeave().
IsFocusable() [2/3]
override bool OptionSelectorBase::IsFocusable (Widget w) inline private
Definition at line 103 of file optionselectoreditbox.c.
    {
        if( w )
        {
            return ( w == m_Parent || w == m_EditBox );
        }
        return false;
    }
References m_Parent.
IsFocusable() [3/3]
override bool OptionSelectorBase::IsFocusable (Widget w) inline private
Definition at line 74 of file optionselectorslidersetup.c.
    {
        if( w )
        {
            return ( w == m_Parent || w == m_Slider );
        }
        return false;
    }
References m_Parent.
IsSelectorEnabled()
bool OptionSelectorBase::IsSelectorEnabled () inline private
Returns false for the selector in 'disabled' states.
Definition at line 157 of file optionselector.c.
    {
        return m_Enabled;
    }
IsSet()
bool OptionSelectorBase::IsSet () inline private
Definition at line 146 of file optionselector.c.
    {
        return m_SelectedOptionIndex != 0;
    }
NormalizeInput()
float OptionSelectorBase::NormalizeInput (float value) inline private
Definition at line 109 of file optionselectorslidersetup.c.
    {
        float ret = ( value - m_MinValue) / ( m_MaxValue - m_MinValue );
        return ret;
    }
References m_MaxValue, and m_MinValue.
OnChange() [1/2]
override bool OptionSelectorBase::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 93 of file optionselectoreditbox.c.
    {
        if( w == m_EditBox )
        {
            m_OptionChanged.Invoke( GetValue() );
            return true;
        }
        return false;
    }
References GetValue().
OnChange() [2/2]
override bool OptionSelectorBase::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 64 of file optionselectorslidersetup.c.
    {
        if( w == m_Slider )
        {
            m_OptionChanged.Invoke( GetValue() );
            return true;
        }
        return false;
    }
References GetValue().
OnClick()
override bool OptionSelectorBase::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 81 of file optionselector.c.
    {
        if( button == MouseState.LEFT )
        {
            if( w == m_Parent )
                SetNextOption();
        }
        return true;
    }
References m_Parent, and OptionSelector::SetNextOption().
OnFocus() [1/2]
override bool OptionSelectorBase::OnFocus (Widget w, int x, int y) inline private
Definition at line 112 of file optionselectoreditbox.c.
    {
        if( GetFocus() != m_EditBox )
        {
            SetFocus( m_EditBox );
            m_Parent.Enable( false );
        }
        return super.OnFocus( m_Parent, x, y );
    }
References GetFocus(), m_Parent, SetFocus(), x, and y.
OnFocus() [2/2]
override bool OptionSelectorBase::OnFocus (Widget w, int x, int y) inline private
Definition at line 83 of file optionselectorslidersetup.c.
    {
        #ifdef PLATFORM_CONSOLE
        if( GetFocus() != m_Slider )
        {
            SetFocus( m_Slider );
            m_Parent.Enable( false );
        }
        return super.OnFocus( m_Parent, x, y );
        #else
        return false;
        #endif
    }
References GetFocus(), m_Parent, SetFocus(), x, and y.
OnFocusLost() [1/2]
override bool OptionSelectorBase::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 123 of file optionselectoreditbox.c.
    {
        if( w == m_EditBox )
        {
            m_Parent.Enable( true );
            return super.OnFocusLost( m_Parent, x, y );
        }
        return false;
    }
References m_Parent, x, and y.
OnFocusLost() [2/2]
override bool OptionSelectorBase::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 99 of file optionselectorslidersetup.c.
    {
        if( w == m_Slider )
        {
            m_Parent.Enable( true );
            return super.OnFocusLost( m_Parent, x, y );
        }
        return false;
    }
References m_Parent, x, and y.
OnMouseButtonUp() [1/2]
override bool OptionSelectorBase::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 63 of file optionselector.c.
    {
        if( button == MouseState.LEFT )
        {
            if( w == m_NextOption )
            {
                SetNextOption();
                return true;
            }
            else if ( w == m_PreviousOption )
            {
                SetPrevOption();
                return true;
            }
        }
        return false;
    }
References OptionSelector::SetNextOption(), and OptionSelector::SetPrevOption().
OnMouseButtonUp() [2/2]
override bool OptionSelectorBase::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 56 of file optionselectorslidersetup.c.
    {
        if( button == MouseState.LEFT && w == m_Slider )
        {
        }
        return false;
    }
OnMouseEnter() [1/3]
override bool OptionSelectorBase::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 92 of file optionselector.c.
    {
        return super.OnMouseEnter( w, x, y );
    }
References x, and y.
OnMouseEnter() [2/3]
override bool OptionSelectorBase::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 45 of file optionselectoreditbox.c.
    {
        if( !IsFocusable( w ) )
            return true;
        if( m_ParentClass )
        {
            m_ParentClass.OnFocus( m_Root.GetParent(), -1, m_SelectorType );
            m_ParentClass.OnMouseEnter( m_Root.GetParent().GetParent(), x, y );
        }
        UIScriptedMenu menu = GetGame().GetUIManager().GetMenu();
        if ( menu && menu.IsInherited( CharacterCreationMenu ) )
        {
            menu.OnFocus( m_Root.GetParent(), -1, m_SelectorType );
            menu.OnMouseEnter( m_Root.GetParent().GetParent(), x, y );
        }
        ColorHighlight(w);
        return true;
    }
References ColorHighlight(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), IsFocusable(), m_Root, UIScriptedMenu::OnFocus(), UIScriptedMenu::OnMouseEnter(), x, and y.
OnMouseEnter() [3/3]
override bool OptionSelectorBase::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 26 of file optionselectorslidersetup.c.
    {
        if( m_ParentClass )
        {
            OnFocus( w, x, y );
            m_ParentClass.OnFocus( m_Root.GetParent(), -1, m_SelectorType );
            #ifdef PLATFORM_WINDOWS
            m_ParentClass.OnMouseEnter( m_Root.GetParent().GetParent(), x, y );
            ColorHighlight(w);
            #endif
        }
        return true;
    }
References ColorHighlight(), m_Root, OnFocus(), x, and y.
OnMouseLeave() [1/3]
override bool OptionSelectorBase::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 97 of file optionselector.c.
    {
        return super.OnMouseLeave( w, enterW, x, y );
    }
References x, and y.
OnMouseLeave() [2/3]
override bool OptionSelectorBase::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 69 of file optionselectoreditbox.c.
    {
        if( IsFocusable( enterW ) )
            return true;
        if( m_ParentClass )
        {
            m_ParentClass.OnFocus( null, x, y );
            m_ParentClass.OnMouseLeave( m_Root.GetParent().GetParent(), enterW, x, y );
        }
        UIScriptedMenu menu = GetGame().GetUIManager().GetMenu();
        if ( menu && menu.IsInherited( CharacterCreationMenu ) )
        {
            menu.OnFocus( null, x, y );
            menu.OnMouseLeave( m_Root.GetParent().GetParent(), enterW, x, y );
        }
        ColorNormal( w );
        return true;
    }
References ColorNormal(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), IsFocusable(), m_Root, UIScriptedMenu::OnFocus(), UIScriptedMenu::OnMouseLeave(), x, and y.
OnMouseLeave() [3/3]
override bool OptionSelectorBase::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 41 of file optionselectorslidersetup.c.
    {
        if( m_ParentClass )
        {
            #ifdef PLATFORM_WINDOWS
            m_ParentClass.OnMouseLeave( m_Root.GetParent().GetParent(), enterW, x, y );
            ColorNormal( w );
            #endif
            OnFocusLost( w, x, y );
            SetFocus( null );
        }
        return true;
    }
References ColorNormal(), m_Root, OnFocusLost(), SetFocus(), x, and y.
OptionSelector()
void OptionSelectorBase::OptionSelector (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled) inline private
Definition at line 9 of file optionselector.c.
    {
        m_Options               = { "#server_browser_disabled", "#server_browser_show", "#server_browser_hide" };
        m_ParentClass           = parent_c;
        m_SelectorType          = 2;
        if( current_index < 0 || current_index >= m_Options.Count() )
        {
            m_SelectedOptionIndex = 0;
        }
        else
        {
            m_SelectedOptionIndex = current_index;
        }
        m_Root                      = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/option_selector.layout", parent );
        #ifdef PLATFORM_CONSOLE
            m_Parent                = parent.GetParent().GetParent();
        #else
        #ifdef PLATFORM_WINDOWS
            m_Parent                = parent.GetParent();
        #endif
        #endif
        //m_DisablePanel                = m_Parent.GetParent().FindAnyWidget( m_Parent.GetName() + "_disable" );
        m_SelectedOption            = TextWidget.Cast( m_Root.FindAnyWidget( "option_label" ) );
        m_PreviousOption            = m_Root.FindAnyWidget( "prev_option" );
        m_NextOption                = m_Root.FindAnyWidget( "next_option" );
        #ifdef PLATFORM_CONSOLE
            m_NextOption.Show( false );
            m_PreviousOption.Show( false );
        #endif
        m_Enabled = !disabled;
        if( m_Enabled )
        {
            Enable();
        }
        else
        {
            Disable();
        }
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
        m_Parent.SetHandler( this );
    }
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_Parent, and m_Root.
OptionSelectorEditbox()
void OptionSelectorBase::OptionSelectorEditbox (Widget parent, string value, ScriptedWidgetEventHandler parent_menu, bool disabled) inline private
Definition at line 5 of file optionselectoreditbox.c.
    {
        m_Root                  = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/option_editbox.layout", parent );
        #ifdef PLATFORM_CONSOLE
            m_Parent                = parent.GetParent().GetParent();
        #else
        #ifdef PLATFORM_WINDOWS
            m_Parent                = parent.GetParent();
        #endif
        #endif
        m_SelectorType              = 1;
        m_ParentClass               = parent_menu;
        m_EditBox                   = EditBoxWidget.Cast( m_Root.FindAnyWidget( "option_value" ) );
        SetValue( value );
        Enable();
        m_Parent.SetHandler( this );
    }
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_Parent, m_Root, and SetValue().
Reset()
void OptionSelectorBase::Reset () inline private
Definition at line 102 of file optionselector.c.
    {
        m_SelectedOptionIndex = 0;
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
        //ColorOption();
        m_OptionChanged.Invoke( m_SelectedOptionIndex );
    }
SetNextOption()
void OptionSelectorBase::SetNextOption () inline private
Definition at line 112 of file optionselector.c.
    {
        m_SelectedOptionIndex++;
        if( m_SelectedOptionIndex >= m_Options.Count() )
        {
            m_SelectedOptionIndex = 0;
        }
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
        //ColorOption();
        m_OptionChanged.Invoke( m_SelectedOptionIndex );
    }
SetPrevOption()
void OptionSelectorBase::SetPrevOption () inline private
Definition at line 126 of file optionselector.c.
    {
        m_SelectedOptionIndex--;
        if( m_SelectedOptionIndex < 0 )
        {
            m_SelectedOptionIndex = m_Options.Count() - 1;
        }
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
        //ColorOption();
        m_OptionChanged.Invoke( m_SelectedOptionIndex );
    }
SetStep()
void OptionSelectorBase::SetStep (float step) inline private
Definition at line 115 of file optionselectorslidersetup.c.
    {
        m_Slider.SetStep(step);
    }
SetStringOption()
void OptionSelectorBase::SetStringOption (string option, bool fire_event = true) inline private
Definition at line 179 of file optionselector.c.
    {
        int index = m_Options.Find( option );
        if( index > -1 )
        {
            m_SelectedOptionIndex = index;
            m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
            //ColorOption();
            if( fire_event )
                m_OptionChanged.Invoke( m_SelectedOptionIndex );
        }
    }
SetValue() [1/2]
void OptionSelectorBase::SetValue (float value, bool update = true) inline private
Definition at line 120 of file optionselectorslidersetup.c.
    {
        m_Slider.SetCurrent( NormalizeInput( value ) );
        if( update )
            m_OptionChanged.Invoke( GetValue() );
    }
References GetValue().
SetValue() [2/2]
void OptionSelectorBase::SetValue (string value, bool update = true) inline private
Definition at line 133 of file optionselectoreditbox.c.
    {
        m_EditBox.SetText( value );
        if( update )
            m_OptionChanged.Invoke( GetValue() );
    }
References GetValue().
Referenced by OptionSelectorEditbox().
Member Data Documentation
m_EditBox
protected EditBoxWidget OptionSelectorBase::m_EditBox private
Definition at line 3 of file optionselectoreditbox.c.
m_MaxValue
protected float OptionSelectorBase::m_MaxValue private
Definition at line 5 of file optionselectorslidersetup.c.
m_MinValue
protected float OptionSelectorBase::m_MinValue private
Definition at line 4 of file optionselectorslidersetup.c.
m_NextOption
protected Widget OptionSelectorBase::m_NextOption private
Definition at line 4 of file optionselector.c.
m_Options
protected ref array<string> OptionSelectorBase::m_Options private
Definition at line 7 of file optionselector.c.
m_PreviousOption
protected Widget OptionSelectorBase::m_PreviousOption private
Definition at line 3 of file optionselector.c.
m_SelectedOption
protected TextWidget OptionSelectorBase::m_SelectedOption private
Definition at line 5 of file optionselector.c.
m_SelectedOptionIndex
protected int OptionSelectorBase::m_SelectedOptionIndex private
Definition at line 6 of file optionselector.c.
m_Slider
protected SliderWidget OptionSelectorBase::m_Slider private
Definition at line 3 of file optionselectorslidersetup.c.