DayzKode: ActionRemoveSeed Class Reference
ActionRemoveSeed Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRemoveSeed ()
override void CreateConditionComponents ()
override GetInputType ()
override bool InventoryReservation (ActionData action_data)
override void OnExecute (ActionData action_data)
Private Attributes
SeedBase m_Seed
Detailed Description
Definition at line 1 of file actionremoveseed.c.
Constructor & Destructor Documentation
ActionRemoveSeed()
void ActionRemoveSeed::ActionRemoveSeed () inline private
Definition at line 5 of file actionremoveseed.c.
    {
        m_Text = "#take";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionRemoveSeed::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 21 of file actionremoveseed.c.
    {
        if ( player.GetCommand_Vehicle() )
            return false;
        GardenBase garden_base;
        if ( Class.CastTo( garden_base, target.GetObject() ) )
        {
            Slot slot;
            array<string> selections = new array<string>;
            garden_base.GetActionComponentNameList( target.GetComponentIndex(), selections );
            string selection;
            for (int s = 0; s < selections.Count(); s++)
            {
                selection = selections[s];
                slot = garden_base.GetSlotBySelection( selection );
                if ( slot )
                    break;
            }
            //Can only remove seed if slot is not watered to prevent VME
            if ( slot && slot.GetSeed() )
            {
                if ( slot.GetWateredState() != 0 )
                    return false;
                m_Seed = SeedBase.Cast( slot.GetSeed() );
                if ( m_Seed )
                {
                    if ( player.GetInventory().CanAddEntityIntoInventory( m_Seed ) && m_Seed.GetHierarchyRootPlayer() != player )
                        return true;
                    else
                        return player.GetInventory().CanAddEntityIntoHands( m_Seed );
                }
            }
        }
        return false;
    }
References Class::CastTo(), and m_Seed.
CreateConditionComponents()
override void ActionRemoveSeed::CreateConditionComponents () inline private
Definition at line 15 of file actionremoveseed.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor(UAMaxDistances.SMALL);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
GetInputType()
override ActionRemoveSeed::GetInputType () inline private
Definition at line 10 of file actionremoveseed.c.
    {
        return ContinuousInteractActionInput;
    }
InventoryReservation()
override bool ActionRemoveSeed::InventoryReservation (ActionData action_data) inline private
Definition at line 63 of file actionremoveseed.c.
    {
        bool success = true;
        InventoryLocation il = new InventoryLocation;
        if ( m_Seed )
        {
            action_data.m_Player.GetInventory().FindFreeLocationFor( m_Seed , FindInventoryLocationType.ANY, il );
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( m_Seed, il ) )
            {
                success = false;
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( m_Seed, il, GameInventory.c_InventoryReservationTimeoutMS );
            }
        }
        if ( success )
        {
            if ( il )
                action_data.m_ReservedInventoryLocations.Insert( il );
        }
        return success;
    }
References ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and m_Seed.
OnExecute()
override void ActionRemoveSeed::OnExecute (ActionData action_data) inline private
Definition at line 91 of file actionremoveseed.c.
    {
        if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
            return;
        PlayerBase player = action_data.m_Player;
        float stackable;
        InventoryLocation il;
        //We place in inventory
        if ( !player.GetInventory().CanAddEntityIntoHands( m_Seed ) )
        {
            il = action_data.m_ReservedInventoryLocations.Get( 0 );
            InventoryLocation targetInventoryLocation = new InventoryLocation;
            m_Seed.GetInventory().GetCurrentInventoryLocation( targetInventoryLocation );
            stackable = m_Seed.GetTargetQuantityMax( il.GetSlot() );
            if ( stackable == 0 || stackable >= m_Seed.GetQuantity() )
            {
                player.PredictiveTakeToDst( targetInventoryLocation, il );
            }
            else
            {
                m_Seed.SplitIntoStackMaxToInventoryLocationClient( il );
            }
        }
        else
        {
            //We place in hands
            ClearInventoryReservationEx( action_data );
            stackable = m_Seed.GetTargetQuantityMax( -1 );
            if ( stackable == 0 || stackable >= m_Seed.GetQuantity() )
            {
                action_data.m_Player.PredictiveTakeEntityToHands( m_Seed );
            }
            else
            {
                il = new InventoryLocation;
                il.SetHands( action_data.m_Player, m_Seed );
                m_Seed.SplitIntoStackMaxToInventoryLocationClient( il );
            }
        }
    }
References ClearInventoryReservationEx(), GetGame(), InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, m_Seed, and InventoryLocation::SetHands().
Member Data Documentation
m_Seed
SeedBase ActionRemoveSeed::m_Seed private
Definition at line 3 of file actionremoveseed.c.
Referenced by ActionCondition(), InventoryReservation(), and OnExecute().