DayzKode: DayZPlayerTypeStepSoundLookupTable Class Reference
DayZPlayerTypeStepSoundLookupTable Class Reference
Private Member Functions
void DayZPlayerTypeStepSoundLookupTableImpl ()
SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
Static Private Member Functions
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance ()
Private Attributes
private autoptr map< int, ref StepSoundLookupTable > m_pSoundTableInstances
private autoptr map< int, StepSoundLookupTable > m_pSoundTables
Static Private Attributes
static private ref DayZPlayerTypeStepSoundLookupTableImpl m_instance
Detailed Description
Definition at line 115 of file dayzplayer.c.
Member Function Documentation
DayZPlayerTypeStepSoundLookupTableImpl()
void DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl () inline private
Definition at line 3 of file dayzplayercfgsounds.c.
    {
        m_pSoundTableInstances = new map<int, ref StepSoundLookupTable>;
        m_pSoundTables = new map<int, StepSoundLookupTable>;
        string stepsCfgPath = "CfgVehicles SurvivorBase AnimEvents Steps ";
        int stepsCount = GetGame().ConfigGetChildrenCount(stepsCfgPath);
        for(int i = 0; i < stepsCount; i++)
        {
            string stepName;
            GetGame().ConfigGetChildName(stepsCfgPath, i, stepName);
            string stepPath = stepsCfgPath + stepName + " ";
            int id = GetGame().ConfigGetInt(stepPath + "id");
            string tableName;
            GetGame().ConfigGetText(stepPath + "soundLookupTable", tableName);
            StepSoundLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
            if(table == NULL)
            {
                table = new StepSoundLookupTable();
                table.LoadTable(tableName);
                m_pSoundTableInstances.Insert(tableName.Hash(), table);
            }
            m_pSoundTables.Insert(id, table);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, m_pSoundTables, and StepSoundLookupTable().
Referenced by GetInstance().
GetInstance()
static DayZPlayerTypeStepSoundLookupTableImpl DayZPlayerTypeStepSoundLookupTable::GetInstance () inline static private
Definition at line 89 of file dayzplayercfgsounds.c.
    {
        if(m_instance == NULL)
            m_instance = new DayZPlayerTypeStepSoundLookupTableImpl();
        return m_instance;
    }
References DayZPlayerTypeStepSoundLookupTableImpl(), m_instance, and m_instance.
Referenced by DayZPlayerTypeRegisterSounds().
GetSoundBuilder() [1/2]
SoundObjectBuilder DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
Definition at line 117 of file dayzplayer.c.
    {
        return null;
    }
Referenced by OnStepEvent().
GetSoundBuilder() [2/2]
override SoundObjectBuilder DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots) inline private
Definition at line 32 of file dayzplayercfgsounds.c.
    {
        SoundLookupTable table = m_pSoundTables.Get(eventId);
        if(table == NULL)
            return NULL;
        SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pSurfaceHash);
        if(soundBuilder == NULL)
            return NULL;
        if (pMovement == DayZPlayerConstants.MOVEMENTIDX_WALK)
        {
            soundBuilder.SetVariable("walk", 1);
            soundBuilder.SetVariable("run", 0);
            soundBuilder.SetVariable("sprint", 0);
        }
        else if (pMovement == DayZPlayerConstants.MOVEMENTIDX_RUN)
        {
            soundBuilder.SetVariable("walk", 0);
            soundBuilder.SetVariable("run", 1);
            soundBuilder.SetVariable("sprint", 0);
        }
        else if (pMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
        {
            soundBuilder.SetVariable("walk", 0);
            soundBuilder.SetVariable("run", 0);
            soundBuilder.SetVariable("sprint", 1);
        }
        else
        {
            soundBuilder.SetVariable("walk", 0);
            soundBuilder.SetVariable("run", 0);
            soundBuilder.SetVariable("sprint", 0);
        }
        if (pBoots == AnimBootsType.None)
        {
            soundBuilder.SetVariable("bare", 1);
            soundBuilder.SetVariable("sneakers", 0);
            soundBuilder.SetVariable("boots", 0);
        }
        else if (pBoots == AnimBootsType.Sneakers)
        {
            soundBuilder.SetVariable("bare", 0);
            soundBuilder.SetVariable("sneakers", 1);
            soundBuilder.SetVariable("boots", 0);
        }
        else if (pBoots == AnimBootsType.Boots)
        {
            soundBuilder.SetVariable("bare", 0);
            soundBuilder.SetVariable("sneakers", 0);
            soundBuilder.SetVariable("boots", 1);
        }
        return soundBuilder;
    }
References SoundLookupTable::GetSoundBuilder(), m_pSoundTables, and SoundObjectBuilder::SetVariable().
Member Data Documentation
m_instance
private ref DayZPlayerTypeStepSoundLookupTableImpl DayZPlayerTypeStepSoundLookupTable::m_instance static private
Definition at line 97 of file dayzplayercfgsounds.c.
Referenced by GetInstance().
m_pSoundTableInstances
private autoptr map<int, ref StepSoundLookupTable> DayZPlayerTypeStepSoundLookupTable::m_pSoundTableInstances private
Definition at line 98 of file dayzplayercfgsounds.c.
m_pSoundTables
private autoptr map<int, StepSoundLookupTable> DayZPlayerTypeStepSoundLookupTable::m_pSoundTables private
Definition at line 99 of file dayzplayercfgsounds.c.