DayzKode: DayZAnimalInputController Class Reference
DayZAnimalInputController Class Reference
Private Member Functions
private void DayZAnimalInputController ()
never created by script
proto native bool IsAttack ()
proto native bool IsDead ()
proto native bool IsJump ()
private void ~DayZAnimalInputController ()
never destroyed by script
Detailed Description
Definition at line 293 of file dayzanimal.c.
Constructor & Destructor Documentation
DayZAnimalInputController()
private void DayZAnimalInputController::DayZAnimalInputController () inline private
never created by script
Definition at line 302 of file dayzanimal.c.
    {
    }
~DayZAnimalInputController()
private void DayZAnimalInputController::~DayZAnimalInputController () inline private
never destroyed by script
Definition at line 307 of file dayzanimal.c.
    {
    }
Member Function Documentation
IsAttack()
proto native bool DayZAnimalInputController::IsAttack () private
Referenced by DayZCreatureAI::CommandHandler().
IsDead()
proto native bool DayZAnimalInputController::IsDead () private
Referenced by DayZCreatureAI::HandleDeath().
IsJump()
proto native bool DayZAnimalInputController::IsJump () private
Referenced by DayZCreatureAI::CommandHandler().