DayzKode: ActionSetKitchenTimer Class Reference
ActionSetKitchenTimer Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionSetKitchenTimer ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool HasTarget ()
override void OnEndAnimationLoopServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
Detailed Description
Definition at line 13 of file actionsetkitchentimer.c.
Constructor & Destructor Documentation
ActionSetKitchenTimer()
void ActionSetKitchenTimer::ActionSetKitchenTimer () inline private
Definition at line 15 of file actionsetkitchentimer.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_SET_KITCHENTIMER;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONMOD_SET_KITCHENTIMER;
        m_SpecialtyWeight = 0;
        m_CallbackClass = ActionSetKitchenTimerCB;
        m_Text = "#STR_SetTimer0";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionSetKitchenTimer::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 49 of file actionsetkitchentimer.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionSetKitchenTimer::CreateConditionComponents () inline private
Definition at line 25 of file actionsetkitchentimer.c.
    {
        m_ConditionTarget = new CCTSelf;
        m_ConditionItem = new CCINonRuined;
    }
References m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionSetKitchenTimer::HasProneException () inline private
Definition at line 31 of file actionsetkitchentimer.c.
    {
        return true;
    }
HasTarget()
override bool ActionSetKitchenTimer::HasTarget () inline private
Definition at line 36 of file actionsetkitchentimer.c.
    {
        return false;
    }
OnEndAnimationLoopServer()
override void ActionSetKitchenTimer::OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 61 of file actionsetkitchentimer.c.
    {
    }
OnEndServer()
override void ActionSetKitchenTimer::OnEndServer (ActionData action_data) inline private
Definition at line 54 of file actionsetkitchentimer.c.
    {
        float progress = action_data.m_Callback.GetActionComponentProgress();
        KitchenTimer clock = KitchenTimer.Cast(action_data.m_MainItem);
        clock.SetAlarmTimeServer(progress);
    }
References ActionBaseCB::GetActionComponentProgress(), ActionData::m_Callback, ActionData::m_MainItem, and KitchenTimer::SetAlarmTimeServer().
OnStart()
override void ActionSetKitchenTimer::OnStart (ActionData action_data) inline private
Definition at line 41 of file actionsetkitchentimer.c.
    {
    }
OnStartServer()
override void ActionSetKitchenTimer::OnStartServer (ActionData action_data) inline private
Definition at line 45 of file actionsetkitchentimer.c.
    {
    }
OnUpdate()
override void ActionSetKitchenTimer::OnUpdate (ActionData action_data) inline private
Definition at line 66 of file actionsetkitchentimer.c.
    {
        float progress = action_data.m_Callback.GetActionComponentProgress();
        KitchenTimer clock = KitchenTimer.Cast(action_data.m_MainItem);
        clock.SetAnimationPhaseNow("ClockAlarm", progress);
    }
References ActionBaseCB::GetActionComponentProgress(), ActionData::m_Callback, and ActionData::m_MainItem.