DayzKode: ActionTakeItemToHands Class Reference
ActionTakeItemToHands Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTakeItemToHands ()
override bool CanBeUsedOnBack ()
override bool CanContinue (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool HasProneException ()
override void OnExecute (ActionData action_data)
Detailed Description
Definition at line 1 of file actiontakeitemtohands.c.
Constructor & Destructor Documentation
ActionTakeItemToHands()
void ActionTakeItemToHands::ActionTakeItemToHands () inline private
Definition at line 3 of file actiontakeitemtohands.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS;
        m_Text = "#take_to_hands";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeItemToHands::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actiontakeitemtohands.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        if ( !tgt_item )
            return false;
        EntityAI tgt_parent = EntityAI.Cast(tgt_item.GetHierarchyParent());
        if ( !tgt_item.IsTakeable() || tgt_item.IsBeingPlaced() || ( tgt_item.GetHierarchyParent() && !BaseBuildingBase.Cast(tgt_parent) ) || ((tgt_parent && !tgt_item.CanDetachAttachment(tgt_parent)) || (tgt_parent && !tgt_parent.CanReleaseAttachment(tgt_item))) )
            return false;
        return player.GetInventory().CanAddEntityIntoHands(tgt_item);
    }
References ItemBase::CanDetachAttachment(), and ItemBase::IsTakeable().
CanBeUsedOnBack()
override bool ActionTakeItemToHands::CanBeUsedOnBack () inline private
Definition at line 102 of file actiontakeitemtohands.c.
    {
        return true;
    }
CanContinue()
override bool ActionTakeItemToHands::CanContinue (ActionData action_data) inline private
Definition at line 43 of file actiontakeitemtohands.c.
    {
        return true;
    }
CreateAndSetupActionCallback()
override void ActionTakeItemToHands::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 70 of file actiontakeitemtohands.c.
    {
        //Print("starting - CreateAndSetupActionCallback");
        EntityAI target = EntityAI.Cast(action_data.m_Target.GetObject());
        ActionBaseCB callback;
        if (!target)
            return;
        if (target.IsHeavyBehaviour())
        {
            //Print("heavybehaviour");
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            //Print("else - SHOULD NOT BE HERE");
            if( action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT) )
            {
                Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(m_CommandUID,GetCallbackClassTypename()));
            }
            else
            {
                Class.CastTo(callback, action_data.m_Player.StartCommand_Action(m_CommandUIDProne,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_PRONE));
            }
        }
        //Print(callback);
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
CreateConditionComponents()
override void ActionTakeItemToHands::CreateConditionComponents () inline private
Definition at line 10 of file actiontakeitemtohands.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionTakeItemToHands::GetInputType () inline private
Definition at line 21 of file actiontakeitemtohands.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionTakeItemToHands::HasProgress () inline private
Definition at line 26 of file actiontakeitemtohands.c.
    {
        return false;
    }
HasProneException()
override bool ActionTakeItemToHands::HasProneException () inline private
Definition at line 16 of file actiontakeitemtohands.c.
    {
        return true;
    }
OnExecute()
override void ActionTakeItemToHands::OnExecute (ActionData action_data) inline private
Definition at line 48 of file actiontakeitemtohands.c.
    {
        if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
            return;
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        ClearInventoryReservationEx(action_data);
        float stackable = ntarget.GetTargetQuantityMax(-1);
        if ( stackable == 0 || stackable >= ntarget.GetQuantity() )
        {
            action_data.m_Player.PredictiveTakeEntityToHands( ntarget );
        }
        else
        {
            InventoryLocation il = new InventoryLocation;
            il.SetHands(action_data.m_Player, ntarget);
            ntarget.SplitIntoStackMaxToInventoryLocationClient( il );
        }
    }
References ClearInventoryReservationEx(), GetGame(), ActionData::m_Player, ActionData::m_Target, and InventoryLocation::SetHands().