DayzKode: DayZCreature Class Reference
DayZCreature Class Reference
Private Member Functions
void AddDamageSphere (AnimDamageParams damage_params)
proto native void AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams)
protected void AttenuateSoundIfNecessary (SoundObject soundObject)
string CaptureSound ()
void DayZCreatureAI ()
void DecreaseEffectTriggerCount ()
proto native void DestroyAIAgent ()
override void EEKilled (Object killer)
proto native AIAgent GetAIAgent ()
AnimBootsType GetBootsType ()
proto native DayZCreatureAIType GetCreatureAIType ()
void IncreaseEffectTriggerCount ()
proto native void InitAIAgent (AIGroup group)
bool IsDanger ()
proto native bool IsSoundInsideBuilding ()
void OnDamageEvent (int event_id, string event_user_string)
void OnSoundEvent (int event_id, string event_user_string)
void OnSoundVoiceEvent (int event_id, string event_user_string)
void OnStepEvent (int event_id, string event_user_string)
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
private void ProcessDamageEvent (AnimDamageEvent damage_event)
private void ProcessSoundEvent (AnimSoundEvent sound_event)
private void ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event)
private void ProcessStepEvent (AnimStepEvent step_event)
protected void RegisterAnimEvents ()
string ReleaseSound ()
bool ResistContaminatedEffect ()
Private Attributes
int m_EffectTriggerCount
Detailed Description
Definition at line 56 of file dayzanimal.c.
Member Function Documentation
AddDamageSphere() [1/2]
void DayZCreature::AddDamageSphere (AnimDamageParams damage_params) inline private
Definition at line 95 of file dayzanimal.c.
    {
        AddDamageSphere(damage_params.m_sBoneName, damage_params.m_sAmmoName, damage_params.m_fRadius, damage_params.m_fDuration, damage_params.m_bInvertTeams);
    }
AddDamageSphere() [2/2]
proto native void DayZCreature::AddDamageSphere (string bone_name, string ammo_name, float radius, float duration, bool invertTeams) private
AttenuateSoundIfNecessary()
protected void DayZCreature::AttenuateSoundIfNecessary (SoundObject soundObject) inline private
Definition at line 245 of file dayzanimal.c.
    {
        if (GetGame().GetPlayer() != NULL && (IsSoundInsideBuilding() != GetGame().GetPlayer().IsSoundInsideBuilding() || GetGame().GetPlayer().IsCameraInsideVehicle()))
        {
            soundObject.SetKind(WaveKind.WAVEATTALWAYS);
        }
        else
        {
            soundObject.SetKind(WaveKind.WAVEEFFECTEX);
        }
    }
References GetGame(), and GetPlayer().
CaptureSound()
string DayZCreature::CaptureSound () inline private
Definition at line 272 of file dayzanimal.c.
    {
        return "";
    }
DayZCreatureAI()
void DayZCreature::DayZCreatureAI () inline private
Definition at line 78 of file dayzanimal.c.
    {
        RegisterAnimEvents();
        SetFlags(EntityFlags.TOUCHTRIGGERS, false);
    }
References SetFlags().
DecreaseEffectTriggerCount()
void DayZCreature::DecreaseEffectTriggerCount () inline private
Definition at line 90 of file dayzanimal.c.
    {
        m_EffectTriggerCount--;
    }
DestroyAIAgent()
proto native void DayZCreature::DestroyAIAgent () private
EEKilled()
override void DayZCreature::EEKilled (Object killer) inline private
Definition at line 100 of file dayzanimal.c.
    {
        super.EEKilled(killer);
        CreateComponent(COMP_TYPE_BODY_STAGING); // TO DO: This is never called on clients in multiplayer! That's why skinning doesn't work properly in MP. DAYZ-28269
    }
References COMP_TYPE_BODY_STAGING.
GetAIAgent()
proto native AIAgent DayZCreature::GetAIAgent () private
GetBootsType()
AnimBootsType DayZCreature::GetBootsType () inline private
Definition at line 106 of file dayzanimal.c.
    {
        return AnimBootsType.None;
    }
GetCreatureAIType()
proto native DayZCreatureAIType DayZCreature::GetCreatureAIType () private
IncreaseEffectTriggerCount()
void DayZCreature::IncreaseEffectTriggerCount () inline private
Definition at line 85 of file dayzanimal.c.
    {
        m_EffectTriggerCount++;
    }
InitAIAgent()
proto native void DayZCreature::InitAIAgent (AIGroup group) private
AIAgent initialization. Manual ai initialization for creatures created with CreateObject(... init_ai = false...).
IsDanger()
bool DayZCreature::IsDanger () inline private
Definition at line 267 of file dayzanimal.c.
    {
        return false;
    }
IsSoundInsideBuilding()
proto native bool DayZCreature::IsSoundInsideBuilding () private
OnDamageEvent()
void DayZCreature::OnDamageEvent (int event_id, string event_user_string) inline private
Definition at line 150 of file dayzanimal.c.
    {
        AnimDamageEvent damage_event = GetCreatureAIType().GetDamageEvent(event_id);
        if(damage_event != NULL)
        {
            ProcessDamageEvent(damage_event);
        }
    }
OnSoundEvent()
void DayZCreature::OnSoundEvent (int event_id, string event_user_string) inline private
Definition at line 123 of file dayzanimal.c.
    {
        AnimSoundEvent sound_event = GetCreatureAIType().GetSoundEvent(event_id);
        if(sound_event != NULL)
        {
            ProcessSoundEvent(sound_event);
        }
    }
References ProcessSoundEvent().
OnSoundVoiceEvent()
void DayZCreature::OnSoundVoiceEvent (int event_id, string event_user_string) inline private
Definition at line 132 of file dayzanimal.c.
    {
        AnimSoundVoiceEvent voice_event = GetCreatureAIType().GetSoundVoiceEvent(event_id);
        if(voice_event != NULL)
        {
            ProcessSoundVoiceEvent(voice_event);
        }
    }
OnStepEvent()
void DayZCreature::OnStepEvent (int event_id, string event_user_string) inline private
Definition at line 141 of file dayzanimal.c.
    {
        AnimStepEvent step_event = GetCreatureAIType().GetStepEvent(event_id);
        if(step_event != NULL)
        {
            ProcessStepEvent(step_event);
        }
    }
PlaySound()
AbstractWave DayZCreature::PlaySound (SoundObject so, SoundObjectBuilder sob) inline private
Definition at line 111 of file dayzanimal.c.
    {
        if(so == NULL)
        {
            return NULL;
        }
        so.SetPosition(GetPosition());
        AbstractWave wave = GetGame().GetSoundScene().Play3D(so, sob);
        return wave;
    }
References GetGame(), GetPosition, CGame::GetSoundScene(), and AbstractWave::SetPosition().
ProcessDamageEvent()
private void DayZCreature::ProcessDamageEvent (AnimDamageEvent damage_event) inline private
Definition at line 240 of file dayzanimal.c.
    {
        AddDamageSphere(damage_event.m_DamageParams);
    }
ProcessSoundEvent()
private void DayZCreature::ProcessSoundEvent (AnimSoundEvent sound_event) inline private
Definition at line 185 of file dayzanimal.c.
    {
        if(!GetGame().IsDedicatedServer())
        {
            SoundObjectBuilder objectBuilder = sound_event.GetSoundBuilder();
            if(NULL != objectBuilder)
            {
                objectBuilder.UpdateEnvSoundControllers(GetPosition());
                SoundObject soundObject = objectBuilder.BuildSoundObject();
                PlaySound(soundObject, objectBuilder);
            }
        }
        if(GetGame().IsServer())
        {
            if(sound_event.m_NoiseParams != NULL)
                GetGame().GetNoiseSystem().AddNoise(this, sound_event.m_NoiseParams);
        }
    }
References NoiseSystem::AddNoise(), SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessSoundVoiceEvent()
private void DayZCreature::ProcessSoundVoiceEvent (AnimSoundVoiceEvent sound_event) inline private
Definition at line 205 of file dayzanimal.c.
    {
        if(!GetGame().IsDedicatedServer())
        {
            SoundObjectBuilder objectBuilder = sound_event.GetSoundBuilder();
            if(NULL != objectBuilder)
            {
                objectBuilder.UpdateEnvSoundControllers(GetPosition());
                SoundObject soundObject = objectBuilder.BuildSoundObject();
                AttenuateSoundIfNecessary(soundObject);
                PlaySound(soundObject, objectBuilder);
            }
        }
        if(GetGame().IsServer())
        {
            if(sound_event.m_NoiseParams != NULL)
                GetGame().GetNoiseSystem().AddNoise(this, sound_event.m_NoiseParams);
        }
    }
References NoiseSystem::AddNoise(), AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
ProcessStepEvent()
private void DayZCreature::ProcessStepEvent (AnimStepEvent step_event) inline private
Definition at line 226 of file dayzanimal.c.
    {
        SoundObjectBuilder soundBuilder = step_event.GetSoundBuilder(GetSurfaceType().Hash());
        if(soundBuilder == NULL)
            return;
        soundBuilder.UpdateEnvSoundControllers(GetPosition());
        SoundObject soundObject = soundBuilder.BuildSoundObject();
        AttenuateSoundIfNecessary(soundObject);
        PlaySound(soundObject, soundBuilder);
        //TODO effects
    }
References AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), GetPosition, GetSurfaceType(), PlaySound(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
RegisterAnimEvents()
protected void DayZCreature::RegisterAnimEvents () inline private
Definition at line 159 of file dayzanimal.c.
    {
        if(!RegisterAnimationEvent("Sound", "OnSoundEvent"))
        {
            Print("Error registering anim. event (Sound)");
        }
        if(!RegisterAnimationEvent("SoundVoice", "OnSoundVoiceEvent"))
        {
            Print("Error registering anim. event (SoundVoice)");
        }
        if(!GetGame().IsDedicatedServer())
        {
            if(!RegisterAnimationEvent("Step", "OnStepEvent"))
            {
                Print("Error registering anim. event (Step)");
            }
        }
        if(!RegisterAnimationEvent("Damage", "OnDamageEvent"))
        {
            Print("Error registering anim. event (Damage)");
        }
    }
References GetGame(), Print(), and RegisterAnimationEvent().
ReleaseSound()
string DayZCreature::ReleaseSound () inline private
Definition at line 277 of file dayzanimal.c.
    {
        return "";
    }
ResistContaminatedEffect()
bool DayZCreature::ResistContaminatedEffect () inline private
Definition at line 257 of file dayzanimal.c.
    {
        return false;
    }
Member Data Documentation
m_EffectTriggerCount
int DayZCreature::m_EffectTriggerCount private
Definition at line 75 of file dayzanimal.c.