DayzKode: ActionBuildShelter Class Reference
ActionBuildShelter Class Reference
Private Member Functions
void ActionBuildShelter ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool CanBeUsedLeaning ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
void DestroyActionLoopSound ()
void DetermineConstructionSounds (ActionData action_data)
override GetInputType ()
override string GetText ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasAlternativeInterrupt ()
override bool HasProgress ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEnd (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnStartClient (ActionData action_data)
void PlayActionFinishSound (ActionData action_data)
void PlayActionLoopSound (ActionData action_data)
void PlayActionStartSound (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
void StopActionLoopSound ()
override bool UseMainItem ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
void ~ActionBuildShelter ()
Private Attributes
ref protected EffectSound m_BuildLoopSound
string m_SoundsetBuildFinish
string m_SoundsetBuildLoop
string m_SoundsetBuildStart
Detailed Description
Definition at line 1 of file actionbuildshelter.c.
Constructor & Destructor Documentation
ActionBuildShelter()
void ActionBuildShelter::ActionBuildShelter () inline private
Definition at line 8 of file actionbuildshelter.c.
    {
        m_CallbackClass = ActionBuildPartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#build_shelter_leather";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
~ActionBuildShelter()
void ActionBuildShelter::~ActionBuildShelter () inline private
Definition at line 17 of file actionbuildshelter.c.
    {
        DestroyActionLoopSound();
    }
References DestroyActionLoopSound().
Member Function Documentation
ActionCondition()
override bool ActionBuildShelter::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 108 of file actionbuildshelter.c.
    {
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        if (target.GetObject() && !target.GetObject().CanUseConstructionBuild())
            return false;
        if ( player.IsPlacingLocal() || player.IsPlacingServer() )
            return false;
        if ( (!GetGame().IsDedicatedServer()) )
        {
            if ( MiscGameplayFunctions.ComplexBuildCollideCheckClient(player, target, item, m_VariantID ) )
            {
                return true;
            }
            return false;
        }
        return true;
    }
References GetGame(), and m_VariantID.
ActionConditionContinue()
override bool ActionBuildShelter::ActionConditionContinue (ActionData action_data) inline private
Definition at line 183 of file actionbuildshelter.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        string part_name = BuildPartActionData.Cast(action_data).m_PartType;
        CollisionCheckData check_data = new CollisionCheckData;
        check_data.m_PartName = part_name;
        check_data.m_AdditionalExcludes.Insert(action_data.m_Player);
        return !construction.IsCollidingEx( check_data ) && construction.CanBuildPart( part_name, action_data.m_MainItem, false );
    }
References CollisionCheckData(), Construction(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool ActionBuildShelter::CanBeUsedLeaning () inline private
Definition at line 83 of file actionbuildshelter.c.
    {
        return false;
    }
CreateActionData()
override ActionData ActionBuildShelter::CreateActionData () inline private
Definition at line 146 of file actionbuildshelter.c.
    {
        BuildPartActionData action_data = new BuildPartActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionBuildShelter::CreateConditionComponents () inline private
Definition at line 22 of file actionbuildshelter.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
DestroyActionLoopSound()
void ActionBuildShelter::DestroyActionLoopSound () inline private
Definition at line 312 of file actionbuildshelter.c.
    {
        SEffectManager.DestroyEffect( m_BuildLoopSound );
    }
References SEffectManager::DestroyEffect(), and m_BuildLoopSound.
Referenced by ~ActionBuildShelter().
DetermineConstructionSounds()
void ActionBuildShelter::DetermineConstructionSounds (ActionData action_data) inline private
Definition at line 254 of file actionbuildshelter.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        ConstructionPart constrution_part = construction_action_data.GetBuildPartNoToolAtIndex(m_VariantID);;
        if (constrution_part)
        {
            switch (constrution_part.GetName())
            {
                case "leather":
                    m_SoundsetBuildStart = "Shelter_Leather_Build_Start_SoundSet";
                    m_SoundsetBuildLoop = "Shelter_Leather_Build_Loop_SoundSet";
                    m_SoundsetBuildFinish = "Shelter_Leather_Build_Finish_SoundSet";
                break;
                case "fabric":
                    m_SoundsetBuildStart = "Shelter_Fabric_Build_Start_SoundSet";
                    m_SoundsetBuildLoop = "Shelter_Fabric_Build_Loop_SoundSet";
                    m_SoundsetBuildFinish = "Shelter_Fabric_Build_Finish_SoundSet";
                break;
                case "stick":
                    m_SoundsetBuildStart = "Shelter_Wooden_Stick_Build_Start_SoundSet";
                    m_SoundsetBuildLoop = "Shelter_Wooden_Stick_Build_Loop_SoundSet";
                    m_SoundsetBuildFinish = "Shelter_Wooden_Stick_Build_Finish_SoundSet";
                break;
                default:
                    m_SoundsetBuildStart = "";
                    m_SoundsetBuildLoop = "";
                    m_SoundsetBuildFinish = "";
                break;
            }
        }
    }
References ConstructionActionData::GetBuildPartNoToolAtIndex(), ConstructionPart::GetName(), ActionData::m_Player, m_SoundsetBuildFinish, m_SoundsetBuildLoop, m_SoundsetBuildStart, and m_VariantID.
Referenced by OnStartClient().
GetInputType()
override ActionBuildShelter::GetInputType () inline private
Definition at line 88 of file actionbuildshelter.c.
    {
        return ContinuousInteractActionInput;
    }
GetText()
override string ActionBuildShelter::GetText () inline private
Definition at line 28 of file actionbuildshelter.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player )
        {
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            ConstructionPart constrution_part = construction_action_data.GetBuildPartNoToolAtIndex(m_VariantID);
            if ( constrution_part )
            {
                string ret = "";
                switch (constrution_part.GetName())
                {
                    case "leather":
                        ret = "#build_shelter_leather";
                    break;
                    case "fabric":
                        ret = "#build_shelter_fabric";
                    break;
                    case "stick":
                        ret = "#build_shelter_stick";
                    break;
                }
            }
        }
        return ret;
    }
References ConstructionActionData::GetBuildPartNoToolAtIndex(), GetGame(), ConstructionPart::GetName(), GetPlayer(), and m_VariantID.
HandleReciveData()
override void ActionBuildShelter::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 176 of file actionbuildshelter.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        BuildPartActionData.Cast(action_data).m_PartType = BuildPartActionReciveData.Cast( action_recive_data ).m_PartType;
    }
References BuildPartActionReciveData::m_PartType.
HasAlternativeInterrupt()
override bool ActionBuildShelter::HasAlternativeInterrupt () inline private
Definition at line 103 of file actionbuildshelter.c.
    {
        return false;
    }
HasProgress()
override bool ActionBuildShelter::HasProgress () inline private
Definition at line 98 of file actionbuildshelter.c.
    {
        return true;
    }
OnActionInfoUpdate()
override void ActionBuildShelter::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 59 of file actionbuildshelter.c.
    {
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            ConstructionPart constrution_part = construction_action_data.GetBuildPartNoToolAtIndex(m_VariantID);
            if ( constrution_part )
            {
                switch (constrution_part.GetName())
                {
                    case "leather":
                        m_Text = "#build_shelter_leather";
                    break;
                    case "fabric":
                        m_Text = "#build_shelter_fabric";
                    break;
                    case "stick":
                        m_Text = "#build_shelter_stick";
                    break;
                }
            }
    }
References ConstructionActionData::GetBuildPartNoToolAtIndex(), ConstructionPart::GetName(), m_Text, and m_VariantID.
OnEnd()
override void ActionBuildShelter::OnEnd (ActionData action_data) inline private
Definition at line 217 of file actionbuildshelter.c.
    {
        super.OnEnd(action_data);
        action_data.m_Player.TryHideItemInHands(false);
    }
References ActionData::m_Player.
OnEndClient()
override void ActionBuildShelter::OnEndClient (ActionData action_data) inline private
Definition at line 223 of file actionbuildshelter.c.
    {
        super.OnEndClient(action_data);
        StopActionLoopSound();
        //DestroyActionLoopSound();
    }
References StopActionLoopSound().
OnFinishProgressClient()
override void ActionBuildShelter::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 247 of file actionbuildshelter.c.
    {
        super.OnFinishProgressClient(action_data);
        PlayActionFinishSound(action_data);
    }
References PlayActionFinishSound().
OnFinishProgressServer()
override void ActionBuildShelter::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 231 of file actionbuildshelter.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        string part_name = BuildPartActionData.Cast(action_data).m_PartType;
        if ( !construction.IsColliding( part_name ) && construction.CanBuildPart( part_name, action_data.m_MainItem, false ) )
        {
            //build
            construction.BuildPartServer( action_data.m_Player, part_name, AT_BUILD_PART );
        }
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References AT_BUILD_PART, Construction(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
OnStart()
override void ActionBuildShelter::OnStart (ActionData action_data) inline private
Definition at line 196 of file actionbuildshelter.c.
    {
        super.OnStart(action_data);
        action_data.m_Player.TryHideItemInHands(true);
    }
References ActionData::m_Player.
OnStartAnimationLoopClient()
override void ActionBuildShelter::OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 210 of file actionbuildshelter.c.
    {
        super.OnStartAnimationLoopClient(action_data);
        PlayActionLoopSound(action_data);
    }
References PlayActionLoopSound().
OnStartClient()
override void ActionBuildShelter::OnStartClient (ActionData action_data) inline private
Definition at line 202 of file actionbuildshelter.c.
    {
        super.OnStartClient(action_data);
        DetermineConstructionSounds(action_data);
        PlayActionStartSound(action_data);
    }
References DetermineConstructionSounds(), and PlayActionStartSound().
PlayActionFinishSound()
void ActionBuildShelter::PlayActionFinishSound (ActionData action_data) inline private
Definition at line 317 of file actionbuildshelter.c.
    {
        EffectSound sound = SEffectManager.PlaySound(m_SoundsetBuildFinish, action_data.m_Target.GetObject().GetPosition());
        sound.SetAutodestroy( true );
    }
References m_SoundsetBuildFinish, ActionData::m_Target, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnFinishProgressClient().
PlayActionLoopSound()
void ActionBuildShelter::PlayActionLoopSound (ActionData action_data) inline private
Definition at line 295 of file actionbuildshelter.c.
    {
        if ( !m_BuildLoopSound || !m_BuildLoopSound.IsSoundPlaying() )
        {
            m_BuildLoopSound = SEffectManager.PlaySound( m_SoundsetBuildLoop, action_data.m_Target.GetObject().GetPosition(), 0, 0, true );
        }
    }
References EffectSound::IsSoundPlaying(), m_BuildLoopSound, m_SoundsetBuildLoop, ActionData::m_Target, and SEffectManager::PlaySound().
Referenced by OnStartAnimationLoopClient().
PlayActionStartSound()
void ActionBuildShelter::PlayActionStartSound (ActionData action_data) inline private
Definition at line 289 of file actionbuildshelter.c.
    {
        EffectSound sound = SEffectManager.PlaySound(m_SoundsetBuildStart, action_data.m_Target.GetObject().GetPosition());
        sound.SetAutodestroy( true );
    }
References m_SoundsetBuildStart, ActionData::m_Target, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnStartClient().
ReadFromContext()
override bool ActionBuildShelter::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 159 of file actionbuildshelter.c.
    {
        action_recive_data = new BuildPartActionReciveData;
        super.ReadFromContext(ctx, action_recive_data);
        string part_type;
        if ( ctx.Read(part_type) )
        {
            BuildPartActionReciveData.Cast( action_recive_data ).m_PartType = part_type;
            return true;
        }
        else
        {
            return false;
        }
    }
References BuildPartActionReciveData::m_PartType, and Serializer::Read().
SetupAction()
override bool ActionBuildShelter::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 131 of file actionbuildshelter.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data ) )
        {
            if ( !GetGame().IsDedicatedServer() )
            {
                ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
                BuildPartActionData.Cast(action_data).m_PartType = construction_action_data.GetBuildPartNoToolAtIndex(m_VariantID).GetPartName();
            }
            return true;
        }
        return false;
    }
References ConstructionActionData::GetBuildPartNoToolAtIndex(), GetGame(), ConstructionPart::GetPartName(), and m_VariantID.
StopActionLoopSound()
void ActionBuildShelter::StopActionLoopSound () inline private
Definition at line 303 of file actionbuildshelter.c.
    {
        if (m_BuildLoopSound)
        {
            m_BuildLoopSound.SetSoundFadeOut(0.5);
            m_BuildLoopSound.SoundStop();
        }
    }
References m_BuildLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnEndClient().
UseMainItem()
override bool ActionBuildShelter::UseMainItem () inline private
Definition at line 93 of file actionbuildshelter.c.
    {
        return false;
    }
WriteToContext()
override void ActionBuildShelter::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 152 of file actionbuildshelter.c.
    {
        super.WriteToContext(ctx, action_data);
        ctx.Write(BuildPartActionData.Cast(action_data).m_PartType);
    }
References Serializer::Write().
Member Data Documentation
m_BuildLoopSound
ref protected EffectSound ActionBuildShelter::m_BuildLoopSound private
Definition at line 6 of file actionbuildshelter.c.
Referenced by DestroyActionLoopSound(), PlayActionLoopSound(), and StopActionLoopSound().
m_SoundsetBuildFinish
string ActionBuildShelter::m_SoundsetBuildFinish private
Definition at line 5 of file actionbuildshelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionFinishSound().
m_SoundsetBuildLoop
string ActionBuildShelter::m_SoundsetBuildLoop private
Definition at line 4 of file actionbuildshelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionLoopSound().
m_SoundsetBuildStart
string ActionBuildShelter::m_SoundsetBuildStart private
Definition at line 3 of file actionbuildshelter.c.
Referenced by DetermineConstructionSounds(), and PlayActionStartSound().