DayzKode: MenuDefaultCharacterData Class Reference
MenuDefaultCharacterData Class Reference
Private Member Functions
void ClearAttachmentsMap ()
bool DeserializeCharacterData (ParamsReadContext ctx)
void DumpAttMapContents ()
void EquipDefaultCharacter (Man player)
void GenerateRandomEquip ()
map< int, string > GetAttachmentMap ()
string GetCharacterName ()
string GetCharacterType ()
void Init ()
bool IsRandomCharacterForced ()
void MenuDefaultCharacterData ()
void SerializeCharacterData (ParamsWriteContext ctx)
serializes data into a param array to be used by "StoreLoginData(notnull array<ref Param> params);"
void SetCharacterName (string name)
void SetCharacterType (string character_type)
void SetDefaultAttachment (int slotID, string type)
void SetRandomCharacterForced (bool state)
Private Attributes
ref map< int, string > m_AttachmentsMap
string m_CharacterName
string m_CharacterType
bool m_ForceRandomCharacter
Detailed Description
Definition at line 901 of file gameplay.c.
Constructor & Destructor Documentation
MenuDefaultCharacterData()
void MenuDefaultCharacterData::MenuDefaultCharacterData () inline private
Definition at line 911 of file gameplay.c.
    {
        Init();
    }
References Init().
Member Function Documentation
ClearAttachmentsMap()
void MenuDefaultCharacterData::ClearAttachmentsMap () inline private
Definition at line 925 of file gameplay.c.
    {
        m_AttachmentsMap.Clear();
    }
References m_AttachmentsMap.
Referenced by GenerateRandomEquip().
DeserializeCharacterData()
bool MenuDefaultCharacterData::DeserializeCharacterData (ParamsReadContext ctx) inline private
Definition at line 998 of file gameplay.c.
    {
        if (!ctx.Read(m_CharacterType))
            return false;
        if (!ctx.Read(m_AttachmentsMap))
            return false;
        if (!ctx.Read(m_ForceRandomCharacter))
            return false;
        if (!ctx.Read(m_CharacterName))
            return false;
        //DumpAttMapContents();
        return true;
    }
References m_AttachmentsMap, m_CharacterName, m_CharacterType, m_ForceRandomCharacter, and Serializer::Read().
Referenced by MissionBase::ProcessLoginData().
DumpAttMapContents()
void MenuDefaultCharacterData::DumpAttMapContents () inline private
Definition at line 1049 of file gameplay.c.
    {
        int debugID;
        string debugType;
        Print("-----------");
        Print("m_AttachmentsMap contents:");
        for (int j = 0; j < m_AttachmentsMap.Count(); j++)
        {
            debugID = m_AttachmentsMap.GetKey(j);
            debugType = m_AttachmentsMap.GetElement(j);
            Print("index " + j);
            Print("debugID: " + debugID);
            Print("debugType: " + debugType);
        }
        Print("-----------");
    }
References m_AttachmentsMap, and Print().
EquipDefaultCharacter()
void MenuDefaultCharacterData::EquipDefaultCharacter (Man player) inline private
Definition at line 953 of file gameplay.c.
    {
        if (!player)
        {
            ErrorEx("WARNING - trying to equip non-existent object! | MenuDefaultCharacterData::EquipDefaultCharacter");
            return;
        }
        int slot_ID;
        string attachment_type;
        string current_attachment_type;
        EntityAI current_attachment_object;
        for (int i = 0; i < m_AttachmentsMap.Count(); i++)
        {
            attachment_type = "";
            current_attachment_type = "";
            slot_ID = m_AttachmentsMap.GetKey(i);
            attachment_type = m_AttachmentsMap.GetElement(i); //Get(i)
            current_attachment_object = player.GetInventory().FindAttachment(slot_ID);
            if (current_attachment_object)
            {
                current_attachment_type = current_attachment_object.GetType();
            }
            if (current_attachment_type != attachment_type)
            {
                if (current_attachment_object)
                    g_Game.ObjectDelete(current_attachment_object);
                if (attachment_type != "")
                    player.GetInventory().CreateAttachmentEx(attachment_type,slot_ID);
            }
        }
    }
References ErrorEx, g_Game, and m_AttachmentsMap.
Referenced by UIScriptedMenu::BottomChanged(), Managed::CreateNewCharacter(), UIScriptedMenu::SetCharacter(), UIScriptedMenu::ShoesChanged(), and UIScriptedMenu::TopChanged().
GenerateRandomEquip()
void MenuDefaultCharacterData::GenerateRandomEquip () inline private
Definition at line 935 of file gameplay.c.
    {
        ClearAttachmentsMap();
        int slot_ID;
        string attachment_type;
        for (int i = 0; i < DefaultCharacterCreationMethods.GetAttachmentSlotsArray().Count(); i++)
        {
            slot_ID = DefaultCharacterCreationMethods.GetAttachmentSlotsArray().Get(i);
            if (DefaultCharacterCreationMethods.GetConfigArrayCountFromSlotID(slot_ID) > 0)
            {
                attachment_type = DefaultCharacterCreationMethods.GetConfigAttachmentTypes(slot_ID).GetRandomElement();
                //if (attachment_type != "")
                    SetDefaultAttachment(slot_ID,attachment_type);
            }
        }
    }
References ClearAttachmentsMap(), Count, and SetDefaultAttachment().
Referenced by Managed::CreateNewCharacterByName(), MissionBase::OnClientNewEvent(), and UIScriptedMenu::RandomizeCharacter().
GetAttachmentMap()
map< int, string > MenuDefaultCharacterData::GetAttachmentMap () inline private
Definition at line 1043 of file gameplay.c.
    {
        return m_AttachmentsMap;
    }
References m_AttachmentsMap.
Referenced by MissionBase::EquipCharacter().
GetCharacterName()
string MenuDefaultCharacterData::GetCharacterName () inline private
Definition at line 1018 of file gameplay.c.
    {
        return m_CharacterName;
    }
References m_CharacterName.
Referenced by Managed::GetCharacterName(), and Managed::GetCharacterNameById().
GetCharacterType()
string MenuDefaultCharacterData::GetCharacterType () inline private
Definition at line 1028 of file gameplay.c.
    {
        return m_CharacterType;
    }
References m_CharacterType.
Referenced by Managed::CreateDefaultCharacter(), and MissionBase::OnClientNewEvent().
Init()
void MenuDefaultCharacterData::Init () inline private
Definition at line 916 of file gameplay.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            GetGame().GetMenuData().LoadCharactersLocal();
        }
        m_AttachmentsMap = new map<int,string>;
    }
References GetGame(), CGame::GetMenuData(), MenuData::LoadCharactersLocal(), and m_AttachmentsMap.
Referenced by MenuDefaultCharacterData().
IsRandomCharacterForced()
bool MenuDefaultCharacterData::IsRandomCharacterForced () inline private
Definition at line 1038 of file gameplay.c.
    {
        return m_ForceRandomCharacter;
    }
References m_ForceRandomCharacter.
SerializeCharacterData()
void MenuDefaultCharacterData::SerializeCharacterData (ParamsWriteContext ctx) inline private
serializes data into a param array to be used by "StoreLoginData(notnull array<ref Param> params);"
Definition at line 989 of file gameplay.c.
    {
        ctx.Write(m_CharacterType);
        ctx.Write(m_AttachmentsMap);
        ctx.Write(m_ForceRandomCharacter);
        ctx.Write(m_CharacterName);
        //DumpAttMapContents();
    }
References m_AttachmentsMap, m_CharacterName, m_CharacterType, m_ForceRandomCharacter, and Serializer::Write().
Referenced by MenuData::OnSetDefaultCharacter(), and StoreLoginDataPrepare().
SetCharacterName()
void MenuDefaultCharacterData::SetCharacterName (string name) inline private
Definition at line 1013 of file gameplay.c.
    {
        m_CharacterName = name;
    }
References m_CharacterName, and name.
Referenced by Managed::CreateDefaultCharacter(), Managed::SaveCharName(), and DayZIntroSceneXbox::SaveCharName().
SetCharacterType()
void MenuDefaultCharacterData::SetCharacterType (string character_type) inline private
Definition at line 1023 of file gameplay.c.
    {
        m_CharacterType = character_type;
    }
References m_CharacterType.
Referenced by Managed::CreateNewCharacterByName().
SetDefaultAttachment()
void MenuDefaultCharacterData::SetDefaultAttachment (int slotID, string type) inline private
Definition at line 930 of file gameplay.c.
    {
        m_AttachmentsMap.Set(slotID,type); //using 'Set' instead of 'Insert' for convenience
    }
References m_AttachmentsMap.
Referenced by UIScriptedMenu::BottomChanged(), GenerateRandomEquip(), UIScriptedMenu::ShoesChanged(), and UIScriptedMenu::TopChanged().
SetRandomCharacterForced()
void MenuDefaultCharacterData::SetRandomCharacterForced (bool state) inline private
Definition at line 1033 of file gameplay.c.
    {
        m_ForceRandomCharacter = state;
    }
References m_ForceRandomCharacter.
Referenced by UIScriptedMenu::GameRespawn(), and UIScriptedMenu::GameRetry().
Member Data Documentation
m_AttachmentsMap
ref map<int,string> MenuDefaultCharacterData::m_AttachmentsMap private
Definition at line 908 of file gameplay.c.
Referenced by ClearAttachmentsMap(), DeserializeCharacterData(), DumpAttMapContents(), EquipDefaultCharacter(), GetAttachmentMap(), Init(), SerializeCharacterData(), and SetDefaultAttachment().
m_CharacterName
string MenuDefaultCharacterData::m_CharacterName private
Definition at line 906 of file gameplay.c.
Referenced by DeserializeCharacterData(), GetCharacterName(), SerializeCharacterData(), and SetCharacterName().
m_CharacterType
string MenuDefaultCharacterData::m_CharacterType private
Definition at line 907 of file gameplay.c.
Referenced by DeserializeCharacterData(), GetCharacterType(), SerializeCharacterData(), and SetCharacterType().
m_ForceRandomCharacter
bool MenuDefaultCharacterData::m_ForceRandomCharacter private
Definition at line 909 of file gameplay.c.
Referenced by DeserializeCharacterData(), IsRandomCharacterForced(), SerializeCharacterData(), and SetRandomCharacterForced().