DayzKode: FireworksLauncherClientEvent Class Reference
FireworksLauncherClientEvent Class Reference
Private Member Functions
protected void CalculateExplosionPosition ()
void FireworksLauncherClientEvent (FireworksLauncher item, int index)
protected float GetExplosionDelay ()
protected float GetExplosionDistance ()
protected vector GetExplosionPosition ()
protected string GetExplosionSoundSet ()
protected int GetExplParticleFromSequence ()
protected int GetLightDelay ()
int GetSecondaryExplosionCount ()
protected int GetSecondaryExplosionDelay ()
protected float GetShotDispersionAngle ()
protected vector GetShotPos ()
protected int GetSoundDelay ()
protected void OnExplode ()
override protected void OnFired ()
protected void PlayExplosionSound ()
protected void RequestSecondaryExplosion ()
protected void SetupLight (PointLightBase light)
protected void SpawnLight ()
protected void SpawnSecondaryExplosion ()
void ~FireworksLauncherClientEvent ()
Private Attributes
protected string m_Color
protected ref array< ref FireworksLauncherClientEventBase > m_Events = new ref array<ref FireworksLauncherClientEventBase>
protected ExplosionLight m_ExplosionLight
protected vector m_ExplosionPos
protected EffectSound m_ExplosionSound
protected EffectSound m_FireSound
protected int m_Index
protected FireworksLauncher m_Item
protected ParticleSource m_ParticleAfterBurnEnd
protected ParticleSource m_ParticleExplosion
protected ParticleSource m_ParticleShot
protected int m_RemainingExplosions = GetSecondaryExplosionCount()
protected vector m_ShotDir
protected ref Timer m_Timer = new Timer()
Detailed Description
Definition at line 27 of file fireworkslauncher.c.
Constructor & Destructor Documentation
FireworksLauncherClientEvent()
void FireworksLauncherClientEvent::FireworksLauncherClientEvent (FireworksLauncher item, int index) inline private
Definition at line 87 of file fireworkslauncher.c.
    {
        m_Item = item;
        m_Index = index;
        int colorSequenceLastIndex = m_Item.GetColorSequence().Length() - 1;
        int coloreSequenceIndex = m_Index - 1;//shot index(m_Index) starts at 1
        if (colorSequenceLastIndex >= coloreSequenceIndex)
        {
            m_Color = m_Item.GetColorSequence().Get(coloreSequenceIndex);
        }
        else
        {
            Debug.LogError("Failed to obtain color from color sequence");
            m_Color = "B";
        }
    }
References string::Get(), FireworksLauncher::GetColorSequence(), string::Length(), Debug::LogError(), m_Color, m_Index, and m_Item.
~FireworksLauncherClientEvent()
void FireworksLauncherClientEvent::~FireworksLauncherClientEvent () inline private
Definition at line 106 of file fireworkslauncher.c.
    {
        SEffectManager.DestroyEffect(m_FireSound);
        SEffectManager.DestroyEffect(m_ExplosionSound);
        if (m_ParticleAfterBurnEnd)
        {
            m_ParticleAfterBurnEnd.StopParticle();
        }
    }
References SEffectManager::DestroyEffect(), m_ExplosionSound, m_FireSound, m_ParticleAfterBurnEnd, and ParticleSource::StopParticle().
Member Function Documentation
CalculateExplosionPosition()
protected void FireworksLauncherClientEvent::CalculateExplosionPosition () inline private
Definition at line 154 of file fireworkslauncher.c.
    {
        m_ExplosionPos = GetShotPos() + m_ShotDir * GetExplosionDistance();
    }
References GetExplosionDistance(), GetShotPos(), m_ExplosionPos, and m_ShotDir.
Referenced by GetExplosionPosition().
GetExplosionDelay()
protected float FireworksLauncherClientEvent::GetExplosionDelay () inline private
Definition at line 77 of file fireworkslauncher.c.
    {
        return Math.RandomFloatInclusive(1.5,1.75);
    }
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetExplosionDistance()
protected float FireworksLauncherClientEvent::GetExplosionDistance () inline private
Definition at line 62 of file fireworkslauncher.c.
    {
        return Math.RandomFloatInclusive(35,40);
    }
References Math::RandomFloatInclusive().
Referenced by CalculateExplosionPosition(), GetExplosionPosition(), and OnFired().
GetExplosionPosition()
protected vector FireworksLauncherClientEvent::GetExplosionPosition () inline private
Definition at line 159 of file fireworkslauncher.c.
    {
        if (!m_ExplosionPos)
        {
            CalculateExplosionPosition();
        }
        return m_ExplosionPos;
    }
References CalculateExplosionPosition(), and m_ExplosionPos.
Referenced by OnExplode(), OnExplode(), SpawnLight(), and SpawnSecondaryExplosion().
GetExplosionSoundSet()
protected string FireworksLauncherClientEvent::GetExplosionSoundSet () inline private
Definition at line 72 of file fireworkslauncher.c.
    {
        return "FireworksLauncher_Explosion_SoundSet";
    }
Referenced by PlayExplosionSound().
GetExplParticleFromSequence()
protected int FireworksLauncherClientEvent::GetExplParticleFromSequence () inline private
Definition at line 216 of file fireworkslauncher.c.
    {
        switch (m_Color)
        {
            case "R":
                return ParticleList.FIREWORKS_EXPLOSION_RED;
            case "G":
                return ParticleList.FIREWORKS_EXPLOSION_GREEN;
            case "B":
                return ParticleList.FIREWORKS_EXPLOSION_BLUE;
            case "Y":
                return ParticleList.FIREWORKS_EXPLOSION_YELLOW;
            case "P":
                return ParticleList.FIREWORKS_EXPLOSION_PINK;
            default:
                ErrorEx("Incorrect explosion particle color in the sequence");
        }
        return ParticleList.FIREWORKS_EXPLOSION_RED;
    }
References ErrorEx, ParticleList::FIREWORKS_EXPLOSION_BLUE, ParticleList::FIREWORKS_EXPLOSION_GREEN, ParticleList::FIREWORKS_EXPLOSION_PINK, ParticleList::FIREWORKS_EXPLOSION_RED, ParticleList::FIREWORKS_EXPLOSION_YELLOW, and m_Color.
Referenced by OnExplode(), and OnExplode().
GetLightDelay()
protected int FireworksLauncherClientEvent::GetLightDelay () inline private
Definition at line 57 of file fireworkslauncher.c.
    {
        return 0;
    }
Referenced by OnExplode(), and OnExplode().
GetSecondaryExplosionCount()
int FireworksLauncherClientEvent::GetSecondaryExplosionCount () inline private
Definition at line 168 of file fireworkslauncher.c.
    {
        return 4;
    }
GetSecondaryExplosionDelay()
protected int FireworksLauncherClientEvent::GetSecondaryExplosionDelay () inline private
Definition at line 211 of file fireworkslauncher.c.
    {
        return Math.RandomIntInclusive(100,250);
    }
References Math::RandomIntInclusive().
Referenced by RequestSecondaryExplosion().
GetShotDispersionAngle()
protected float FireworksLauncherClientEvent::GetShotDispersionAngle () inline private
Definition at line 67 of file fireworkslauncher.c.
    {
        return Math.RandomFloatInclusive(-25,25);//this is rotated 360 degrees around the UP vector too
    }
References Math::RandomFloatInclusive().
Referenced by OnFired().
GetShotPos()
protected vector FireworksLauncherClientEvent::GetShotPos () inline private
Definition at line 136 of file fireworkslauncher.c.
    {
        vector memPos;
        string memName = "Shot_" + m_Index;
        if (m_Item.MemoryPointExists(memName))
        {
            memPos = m_Item.GetMemoryPointPos(memName);
            memPos = m_Item.ModelToWorld(memPos);
        }
        else
        {
            memPos = m_Item.GetPosition();//fallback to item's location
            Debug.LogError("Missing shot memory point on Fireworks");
        }
        return memPos;
    }
References Debug::LogError(), m_Index, and m_Item.
Referenced by CalculateExplosionPosition(), GetExplosionPosition(), and OnFired().
GetSoundDelay()
protected int FireworksLauncherClientEvent::GetSoundDelay () inline private
Definition at line 52 of file fireworkslauncher.c.
    {
        return 0;
    }
Referenced by OnExplode(), and OnExplode().
OnExplode()
protected void FireworksLauncherClientEvent::OnExplode () inline private
Definition at line 174 of file fireworkslauncher.c.
    {
        #ifdef DEVELOPER
        if (m_ShotTrajectory)
        {
            m_ShotTrajectory.Destroy();
            m_ShotTrajectory = null;
        }
        #endif
        m_ParticleAfterBurnEnd.Stop();
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( PlayExplosionSound, GetSoundDelay(), false);
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( SpawnLight, GetLightDelay(), false);
        m_ParticleExplosion = ParticleManager.GetInstance().PlayInWorld(GetExplParticleFromSequence(), GetExplosionPosition());
        RequestSecondaryExplosion();
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetExplosionPosition(), GetExplParticleFromSequence(), GetGame(), GetLightDelay(), GetSoundDelay(), m_ParticleAfterBurnEnd, m_ParticleExplosion, ParticleManager(), PlayExplosionSound(), RequestSecondaryExplosion(), SpawnLight(), and Particle::Stop().
OnFired()
override protected void FireworksLauncherClientEvent::OnFired () inline private
Definition at line 116 of file fireworkslauncher.c.
    {
        m_Timer.Run(GetExplosionDelay(), this, "OnExplode", null);
        m_Item.PlaySoundSet( m_FireSound, "FireworksLauncher_Shot_SoundSet", 0, 0 );
        m_ParticleShot = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_SHOT, GetShotPos());
        m_ParticleShot.SetYawPitchRoll(Vector(Math.RandomFloatInclusive(0,360),GetShotDispersionAngle(),0));
        m_ParticleAfterBurnEnd = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_AFTERBURN_END, GetShotPos());
        if (m_ParticleAfterBurnEnd)
            m_ParticleAfterBurnEnd.SetOwner(this);
        m_ShotDir = m_ParticleShot.GetDirectionUp();
        #ifdef DEVELOPER
        vector pts[2];
        pts[0] = GetShotPos();
        pts[1] = GetShotPos() + m_ShotDir * GetExplosionDistance();
        //m_ShotTrajectory = Shape.CreateLines(COLOR_RED, ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE|ShapeFlags.NOZBUFFER, pts, 2);
        #endif
    }
References ParticleList::FIREWORKS_AFTERBURN_END, ParticleList::FIREWORKS_SHOT, GetExplosionDelay(), GetExplosionDistance(), GetShotDispersionAngle(), GetShotPos(), m_FireSound, m_Item, m_ParticleAfterBurnEnd, m_ParticleShot, m_ShotDir, m_Timer, ParticleManager(), Math::RandomFloatInclusive(), ParticleSource::SetOwner(), and Vector().
PlayExplosionSound()
protected void FireworksLauncherClientEvent::PlayExplosionSound () inline private
Definition at line 272 of file fireworkslauncher.c.
    {
        if (m_FireSound)
        {
            m_FireSound.Stop();
        }
        m_Item.PlaySoundSet( m_ExplosionSound, GetExplosionSoundSet(), 0, 0 );
    }
References GetExplosionSoundSet(), m_ExplosionSound, m_FireSound, m_Item, and EffectSound::Stop().
Referenced by OnExplode().
RequestSecondaryExplosion()
protected void FireworksLauncherClientEvent::RequestSecondaryExplosion () inline private
Definition at line 193 of file fireworkslauncher.c.
    {
        if (m_RemainingExplosions> 0)
        {
            m_RemainingExplosions--;
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( SpawnSecondaryExplosion, GetSecondaryExplosionDelay(), false);
        }
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), GetSecondaryExplosionDelay(), m_RemainingExplosions, and SpawnSecondaryExplosion().
Referenced by OnExplode(), and SpawnSecondaryExplosion().
SetupLight()
protected void FireworksLauncherClientEvent::SetupLight (PointLightBase light) inline private
Definition at line 236 of file fireworkslauncher.c.
    {
        switch (m_Color)
        {
            case "R":
                light.SetDiffuseColor(255,51,51);
                light.SetAmbientColor(255,51,51);
                break;
            case "G":
                light.SetDiffuseColor(0,255,128);
                light.SetAmbientColor(0,255,128);
                break;
            case "B":
                light.SetDiffuseColor(51,153,255);
                light.SetAmbientColor(51,153,255);
                break;
            case "Y":
                light.SetDiffuseColor(255,255,51);
                light.SetAmbientColor(255,255,51);
                break;
            case "P":
                light.SetDiffuseColor(255,102,255);
                light.SetAmbientColor(255,102,255);
                break;
            default:
                ErrorEx("Incorrect explosion particle color in the sequence");
        }
    }
References ErrorEx, and m_Color.
Referenced by SpawnLight().
SpawnLight()
protected void FireworksLauncherClientEvent::SpawnLight () inline private
Definition at line 266 of file fireworkslauncher.c.
    {
        m_ExplosionLight = ExplosionLight.Cast( ScriptedLightBase.CreateLight( ExplosionLight, GetExplosionPosition()) );
        SetupLight(m_ExplosionLight);
    }
References GetExplosionPosition(), m_ExplosionLight, and SetupLight().
Referenced by OnExplode().
SpawnSecondaryExplosion()
protected void FireworksLauncherClientEvent::SpawnSecondaryExplosion () inline private
Definition at line 202 of file fireworkslauncher.c.
    {
        FireworksLauncherClientEventSecondary evnt = new FireworksLauncherClientEventSecondary(m_Item,m_Index);
        evnt.Init(GetExplosionPosition());
        evnt.OnExplode();
        m_Events.Insert(evnt);
        RequestSecondaryExplosion();
    }
References GetExplosionPosition(), m_Events, m_Index, m_Item, and RequestSecondaryExplosion().
Referenced by RequestSecondaryExplosion().
Member Data Documentation
m_Color
protected string FireworksLauncherClientEvent::m_Color private
Definition at line 40 of file fireworkslauncher.c.
Referenced by FireworksLauncherClientEvent(), GetExplParticleFromSequence(), and SetupLight().
m_Events
protected ref array<ref FireworksLauncherClientEventBase> FireworksLauncherClientEvent::m_Events = new ref array<ref FireworksLauncherClientEventBase> private
Definition at line 42 of file fireworkslauncher.c.
Referenced by SpawnSecondaryExplosion().
m_ExplosionLight
protected ExplosionLight FireworksLauncherClientEvent::m_ExplosionLight private
Definition at line 38 of file fireworkslauncher.c.
Referenced by SpawnLight().
m_ExplosionPos
protected vector FireworksLauncherClientEvent::m_ExplosionPos private
Definition at line 32 of file fireworkslauncher.c.
Referenced by CalculateExplosionPosition(), and GetExplosionPosition().
m_ExplosionSound
protected EffectSound FireworksLauncherClientEvent::m_ExplosionSound private
Definition at line 34 of file fireworkslauncher.c.
Referenced by PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_FireSound
protected EffectSound FireworksLauncherClientEvent::m_FireSound private
Definition at line 33 of file fireworkslauncher.c.
Referenced by OnFired(), PlayExplosionSound(), and ~FireworksLauncherClientEvent().
m_Index
protected int FireworksLauncherClientEvent::m_Index private
Definition at line 31 of file fireworkslauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), and SpawnSecondaryExplosion().
m_Item
protected FireworksLauncher FireworksLauncherClientEvent::m_Item private
Definition at line 30 of file fireworkslauncher.c.
Referenced by FireworksLauncherClientEvent(), GetShotPos(), OnFired(), PlayExplosionSound(), and SpawnSecondaryExplosion().
m_ParticleAfterBurnEnd
protected ParticleSource FireworksLauncherClientEvent::m_ParticleAfterBurnEnd private
Definition at line 39 of file fireworkslauncher.c.
Referenced by OnExplode(), OnFired(), and ~FireworksLauncherClientEvent().
m_ParticleExplosion
protected ParticleSource FireworksLauncherClientEvent::m_ParticleExplosion private
Definition at line 36 of file fireworkslauncher.c.
Referenced by OnExplode().
m_ParticleShot
protected ParticleSource FireworksLauncherClientEvent::m_ParticleShot private
Definition at line 35 of file fireworkslauncher.c.
Referenced by OnFired().
m_RemainingExplosions
protected int FireworksLauncherClientEvent::m_RemainingExplosions = GetSecondaryExplosionCount() private
Definition at line 41 of file fireworkslauncher.c.
Referenced by RequestSecondaryExplosion().
m_ShotDir
protected vector FireworksLauncherClientEvent::m_ShotDir private
Definition at line 37 of file fireworkslauncher.c.
Referenced by CalculateExplosionPosition(), and OnFired().
m_Timer
protected ref Timer FireworksLauncherClientEvent::m_Timer = new Timer() private
Definition at line 29 of file fireworkslauncher.c.
Referenced by OnFired().