DayzKode: AnimatorTimer Class Reference
AnimatorTimer Class Reference
Tools
Private Member Functions
void Animate (float val, float speed=1.0)
Starts animate value until value reaches target value.
void AnimateLoop (float speed=1.0)
Starts infinite animation loop <-1,1>. Based on sinus transition.
float GetTargetValue ()
Returns target value. While AnimateLoop returns angle of cycle in radians.
float GetValue ()
Returns actual animated value.
bool IsRunning ()
void SetValue (float val)
Sets both value and target value.
void Tick (float timeslice)
Ticks the timer, is called by timer subsystem.
Private Attributes
private bool m_active = false
private bool m_loop = false
private float m_target_value = 0
private float m_time = 0
private float m_value = 0
Detailed Description
Definition at line 735 of file tools.c.
Member Function Documentation
Animate()
void AnimatorTimer::Animate (float val, float speed = 1.0) inline private
Starts animate value until value reaches target value.
Parameters
val float target value
speed float speed of animating, units per second
Definition at line 748 of file tools.c.
    {
        m_target_value = val;
        m_loop = false;
        m_time = speed;
        m_active = true;
    }
References m_active, m_loop, m_target_value, and m_time.
Referenced by MainMenuButtonEffect::OnFocus(), MainMenuButtonEffect::OnFocusLost(), HoverEffect::OnMouseEnter(), and HoverEffect::OnMouseLeave().
AnimateLoop()
void AnimatorTimer::AnimateLoop (float speed = 1.0) inline private
Starts infinite animation loop <-1,1>. Based on sinus transition.
Parameters
speed float speed of animating , cycles per second (1.0 means one 360 degree sinus cycle per second: 0..1..0..-1..0)
Definition at line 760 of file tools.c.
    {
        m_value = 0;
        m_target_value = 0;
        m_loop = true;
        m_time = speed;
        m_active = true;
    }
References m_active, m_loop, m_target_value, m_time, and m_value.
Referenced by Bouncer::OnWidgetScriptInit(), RadialProgressBar::OnWidgetScriptInit(), and Rotator::OnWidgetScriptInit().
GetTargetValue()
float AnimatorTimer::GetTargetValue () inline private
Returns target value. While AnimateLoop returns angle of cycle in radians.
Definition at line 779 of file tools.c.
{
        return m_target_value;
    }
References m_target_value.
Referenced by Rotator::Update(), and RadialProgressBar::UpdateChild().
GetValue()
float AnimatorTimer::GetValue () inline private
Returns actual animated value.
Definition at line 772 of file tools.c.
                     {
        return m_value;
    }
References m_value.
Referenced by Bouncer::Update(), HoverEffect::Update(), and MainMenuButtonEffect::Update().
IsRunning()
bool AnimatorTimer::IsRunning () inline private
Definition at line 791 of file tools.c.
    {
        return m_active;
    }
References m_active.
Referenced by MainMenuButtonEffect::OnFocus(), and HoverEffect::OnMouseEnter().
SetValue()
void AnimatorTimer::SetValue (float val) inline private
Sets both value and target value.
Definition at line 786 of file tools.c.
{
        m_value = val;
        m_target_value = val;
    }
References m_target_value, and m_value.
Tick()
void AnimatorTimer::Tick (float timeslice) inline private
Ticks the timer, is called by timer subsystem.
Definition at line 798 of file tools.c.
    {
        if ( !m_active ) return;
        if (m_loop)
        {
            m_target_value += m_time * Math.PI2 * timeslice;
            while (m_target_value > Math.PI2) m_target_value -= Math.PI2;
            m_value = Math.Sin(m_target_value);
        }
        else
        {
            float diff = Math.AbsFloat(m_target_value - m_value);
            float step = m_time * timeslice;
            if (diff < step)
            {
                m_value = m_target_value;
                m_active = false;
            }
            else
            {
                if (m_target_value > m_value)
                {
                    m_value += step;
                }
                else
                {
                    m_value -= step;
                }
            }
        }
    }
References Math::AbsFloat(), m_active, m_loop, m_target_value, m_time, m_value, Math::PI2, and Math::Sin().
Referenced by MainMenuButtonEffect::Update(), and RadialProgressBar::Update().
Member Data Documentation
m_active
private bool AnimatorTimer::m_active = false private
Definition at line 737 of file tools.c.
Referenced by Animate(), AnimateLoop(), IsRunning(), and Tick().
m_loop
private bool AnimatorTimer::m_loop = false private
Definition at line 738 of file tools.c.
Referenced by Animate(), AnimateLoop(), and Tick().
m_target_value
private float AnimatorTimer::m_target_value = 0 private
Definition at line 739 of file tools.c.
Referenced by Animate(), AnimateLoop(), GetTargetValue(), SetValue(), and Tick().
m_time
private float AnimatorTimer::m_time = 0 private
Definition at line 741 of file tools.c.
Referenced by Animate(), AnimateLoop(), and Tick().
m_value
private float AnimatorTimer::m_value = 0 private
Definition at line 740 of file tools.c.
Referenced by AnimateLoop(), GetValue(), SetValue(), and Tick().