DayzKode: ConstructionPart Class Reference
ConstructionPart Class Reference
Private Member Functions
void ConstructionPart (string name, string part_name, string main_part_name, int id, bool is_built, bool is_base, bool is_gate, array< string > required_parts)
int GetId ()
string GetMainPartName ()
string GetName ()
string GetPartName ()
array< string > GetRequiredParts ()
bool IsBase ()
bool IsBuilt ()
bool IsGate ()
void SetBuiltState (bool is_built)
void SetRequestBuiltState (bool req_built)
Private Attributes
int m_Id
bool m_IsBase
bool m_IsBuilt
bool m_IsGate
string m_MainPartName
string m_Name
string m_PartName
ref array< string > m_RequiredParts
Detailed Description
Definition at line 1 of file constructionpart.c.
Constructor & Destructor Documentation
ConstructionPart()
void ConstructionPart::ConstructionPart (string name, string part_name, string main_part_name, int id, bool is_built, bool is_base, bool is_gate, array< string > required_parts) inline private
Definition at line 12 of file constructionpart.c.
    {
        m_Name = name;
        m_PartName = part_name;
        m_MainPartName = main_part_name;
        m_Id = id;
        m_IsBuilt = is_built;
        m_IsBase = is_base;
        m_IsGate = is_gate;
        m_RequiredParts = required_parts;
    }
References m_Id, m_IsBase, m_IsBuilt, m_IsGate, m_MainPartName, m_Name, m_PartName, m_RequiredParts, and name.
Member Function Documentation
GetId()
int ConstructionPart::GetId () inline private
Definition at line 40 of file constructionpart.c.
    {
        return m_Id;
    }
References m_Id.
Referenced by BaseBuildingBase::CanReceiveAttachment(), ItemBase::GetConstructionPartById(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), and ItemBase::SetPartFromSyncData().
GetMainPartName()
string ConstructionPart::GetMainPartName () inline private
Definition at line 35 of file constructionpart.c.
    {
        return m_MainPartName;
    }
References m_MainPartName.
Referenced by BuildCondition(), BaseBuildingBase::CanReceiveAttachment(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), GetCollisionBoxData(), GetConstructionPartsToBuild(), GetMaterialType(), HasConflictPart(), HasMaterials(), HasRequiredPart(), MaterialIsRuined(), ReceiveMaterialsServer(), ActionRepairPart::RepairCondition(), SetLockOnAttachedMaterials(), and TakeMaterialsServer().
GetName()
string ConstructionPart::GetName () inline private
Definition at line 24 of file constructionpart.c.
    {
        string ret = Widget.TranslateString(m_Name);
        return ret;
    }
References m_Name.
Referenced by ActionBuildShelter::DetermineConstructionSounds(), ActionDismantlePart::GetAdminLogMessage(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionBuildShelter::GetText(), ActionBuildPart::OnActionInfoUpdate(), ActionDismantlePart::OnActionInfoUpdate(), ActionRepairPart::OnActionInfoUpdate(), and ActionBuildShelter::OnActionInfoUpdate().
GetPartName()
string ConstructionPart::GetPartName () inline private
Definition at line 30 of file constructionpart.c.
    {
        return m_PartName;
    }
References m_PartName.
Referenced by AddToConstructedParts(), BaseBuildingBase::CanReceiveAttachment(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ComplexBuildCollideCheckClient(), DropNonUsableMaterialsServer(), GetConstructionPartsToBuild(), GetMaterialType(), InitVisuals(), ActionDestroyPart::OnFinishProgressServer(), ActionDismantlePart::OnFinishProgressServer(), RemoveFromConstructedParts(), ItemBase::SetActionFromSyncData(), ItemBase::SetPartFromSyncData(), ActionBuildPart::SetupAction(), ActionBuildShelter::SetupAction(), UpdatePhysics(), and UpdateVisuals().
GetRequiredParts()
array< string > ConstructionPart::GetRequiredParts () inline private
Definition at line 75 of file constructionpart.c.
    {
        return m_RequiredParts;
    }
References m_RequiredParts.
Referenced by BaseBuildingBase::CheckGateState(), GetValidDepenentPartsArray(), and HasDependentPart().
IsBase()
bool ConstructionPart::IsBase () inline private
Definition at line 65 of file constructionpart.c.
    {
        return m_IsBase;
    }
References m_IsBase.
Referenced by ActionDismantlePart::DismantleCondition(), DropNonUsableMaterialsServer(), GetBaseConstructionPart(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ReceiveMaterialsServer(), and ItemBase::SetPartFromSyncData().
IsBuilt()
bool ConstructionPart::IsBuilt () inline private
Definition at line 45 of file constructionpart.c.
    {
        return m_IsBuilt;
    }
References m_IsBuilt.
Referenced by BaseBuildingBase::AfterStoreLoad(), BaseBuildingBase::CanReceiveAttachment(), BaseBuildingBase::CheckGateState(), BaseBuildingBase::GateAttachmentConditions(), BaseBuildingBase::GateAttachmentsSanityCheck(), GetValidDepenentPartsArray(), HasDependentPart(), InitVisuals(), IsPartConstructed(), ItemBase::SetPartFromSyncData(), ItemBase::SetPartsAfterStoreLoad(), UpdatePhysics(), and UpdateVisuals().
IsGate()
bool ConstructionPart::IsGate () inline private
Definition at line 70 of file constructionpart.c.
    {
        return m_IsGate;
    }
References m_IsGate.
Referenced by ActionDismantlePart::DismantleCondition(), ExceptionCheck(), GetGateConstructionPart(), BaseBuildingBase::OnPartBuiltServer(), BaseBuildingBase::OnPartDestroyedServer(), and BaseBuildingBase::OnPartDismantledServer().
SetBuiltState()
void ConstructionPart::SetBuiltState (bool is_built) inline private
Definition at line 50 of file constructionpart.c.
    {
        bsbDebugPrint("[bsb] SetBuildState=" + is_built + " part=" + m_PartName);
        m_IsBuilt = is_built;
    }
References bsbDebugPrint(), m_IsBuilt, and m_PartName.
Referenced by AddToConstructedParts(), RemoveFromConstructedParts(), and SetRequestBuiltState().
SetRequestBuiltState()
void ConstructionPart::SetRequestBuiltState (bool req_built) inline private
Definition at line 56 of file constructionpart.c.
    {
        bsbDebugPrint("[bsb] SetRequestBuiltState=" + req_built + " part=" + m_PartName);
        if (GetGame().IsMultiplayer())
            SetBuiltState(req_built);
        else
            ; // skip set to true in single player - will be synced later
    }
References bsbDebugPrint(), GetGame(), m_PartName, and SetBuiltState().
Member Data Documentation
m_Id
int ConstructionPart::m_Id private
Definition at line 4 of file constructionpart.c.
Referenced by ConstructionPart(), and GetId().
m_IsBase
bool ConstructionPart::m_IsBase private
Definition at line 8 of file constructionpart.c.
Referenced by ConstructionPart(), and IsBase().
m_IsBuilt
bool ConstructionPart::m_IsBuilt private
Definition at line 7 of file constructionpart.c.
Referenced by ConstructionPart(), IsBuilt(), and SetBuiltState().
m_IsGate
bool ConstructionPart::m_IsGate private
Definition at line 9 of file constructionpart.c.
Referenced by ConstructionPart(), and IsGate().
m_MainPartName
string ConstructionPart::m_MainPartName private
Definition at line 6 of file constructionpart.c.
Referenced by ConstructionPart(), and GetMainPartName().
m_Name
string ConstructionPart::m_Name private
Definition at line 3 of file constructionpart.c.
Referenced by ConstructionPart(), and GetName().
m_PartName
string ConstructionPart::m_PartName private
Definition at line 5 of file constructionpart.c.
Referenced by ConstructionPart(), GetPartName(), SetBuiltState(), ItemBase::SetPartFromSyncData(), and SetRequestBuiltState().
m_RequiredParts
ref array<string> ConstructionPart::m_RequiredParts private
Definition at line 10 of file constructionpart.c.
Referenced by ConstructionPart(), and GetRequiredParts().