DayzKode: ActionEatMeat Class Reference
ActionEatMeat Class Reference
Private Member Functions
void ActionEatMeat ()
override void ApplyModifiers (ActionData action_data)
Detailed Description
Definition at line 9 of file actioneatmeat.c.
Constructor & Destructor Documentation
ActionEatMeat()
void ActionEatMeat::ActionEatMeat () inline private
Definition at line 11 of file actioneatmeat.c.
    {
        m_CallbackClass = ActionEatMeatCB;
    }
References AnimatedActionBase::m_CallbackClass.
Member Function Documentation
ApplyModifiers()
override void ActionEatMeat::ApplyModifiers (ActionData action_data) inline private
Definition at line 16 of file actioneatmeat.c.
    {
        Edible_Base food_item = Edible_Base.Cast( action_data.m_MainItem );
        if ( food_item )
        {
            if ( food_item.IsMeat() && food_item.IsFoodRaw() )
            {
                PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
                if( module_lifespan )
                {
                    module_lifespan.UpdateBloodyHandsVisibility( action_data.m_Player, true );
                }
            }
        }
    }
References GetPlugin(), Edible_Base::IsMeat(), ActionData::m_MainItem, ActionData::m_Player, and PluginLifespan().