DayzKode: PPEffects Class Reference
PPEffects Class Reference
Deprecated; 'PPEManager' used instead.
Static Private Member Functions
static void AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur)
static void DisableBurlapSackBlindness ()
static void EnableBurlapSackBlindness ()
static void FlashbangEffect (float value)
static void HitEffect (float value)
static void Init ()
static void OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset)
static void PerformSetLensEffect (float lens, float chromAbb, float centerX, float centerY)
added for convenience
static int RegisterBlurEffect ()
static int RegisterChromAbbEffect ()
static int RegisterColorEffect ()
static int RegisterVignetteEffect ()
static void ResetAll ()
static void ResetBlurEffects ()
static void ResetChromAbbEffects ()
static void ResetColorEffects ()
static void ResetColorize ()
static void ResetDOFOverride ()
static void ResetLensEffect ()
static void ResetPPMask ()
static void ResetRadialBlur ()
static void ResetVignettes ()
static void SetBloodSaturation (float value)
static void SetBloom (float thres, float steep, float inten)
static void SetBlur (float value)
sets blur effect to an absolute value between 0..1
static void SetBlurDrunk (float value)
Set blur drunk effect to a specified 'value' between 0..1.
static void SetBlurFever (float value)
Set blur drunk effect to a specified 'value' between 0..1.
static void SetBlurFlashbang (float value)
Set blur flashbang hit effect to a specified 'value' between 0..1.
static void SetBlurInventory (float value)
Set blur inventory effect to a specified 'value' between 0..1.
static void SetBlurMenu (float value)
Set menu blur to a specified 'value' between 0..1.
static void SetBlurOptics (float value)
Set optics and ironsights blur to a specified 'value' between 0..1.
static void SetBlurShock (float value)
static void SetBlurValue (int index, float value)
static void SetChromAbb (float value)
static void SetChromAbbOptic (float value)
static void SetChromAbbValue (int index, float value)
static void SetColorizationNV (float r, float g, float b)
static void SetColorValue (int index, float r, float g, float b, float a, float overlay)
static void SetDeathDarkening (float value)
static void SetEVValuePP (float value)
static void SetLensEffect (float lens, float chromAbb, float centerX, float centerY)
static void SetMenuVignette (float value)
static void SetNVParams (float light_mult, float noise_intensity, float sharpness, float grain_size)
static void SetRadialBlur (float powerX, float powerY, float offsetX, float offsetY)
sets blur effect to an absolute value between 0..1
static void SetShockEffectColor (float value)
static void SetShockVignette (float value)
static void SetTunnelVignette (float value)
static void SetUnconsciousnessVignette (float value)
static void SetVignette (float intensity, float R, float G, float B, float A)
static void SetVignetteEffectValue (int index, float intensity, float r, float g, float b, float a)
static void UpdateBlur ()
updates the blur post process effect where the resulting blur is an aggregate of all individual blur effect values
static void UpdateChromAbb ()
updates the chromatic abberation post process effect where the resulting chromabb is an aggregate of all individual chromabb effect values
static void UpdateColor ()
static void UpdateColorize ()
static void UpdateSaturation ()
static void UpdateVignette ()
Static Private Attributes
static const float COLOR_SHOCK = 0.1
static const int COLORIZE_NV = 100
static float m_BloodSaturation
static int m_BlurDrunk
static int m_BlurFever
static int m_BlurFlashbang
static int m_BlurInventory
static int m_BlurMenu
static int m_BlurOptics
static int m_BlurShock
static ref array< float > m_BlurValues
static int m_BurlapBlindness
static int m_ChromAbbOptic
static ref array< float > m_ChromAbbValues
static ref array< float > m_ColorEffect
static ref map< int, ref array< float > > m_ColorizeEffects
static float m_ColorOverlayTotal
static ref map< int, ref array< float > > m_ColorValues
static float m_ColorValueTotal [4] = {0,0,0,0}
static int m_DyingEffect
static Material m_MatColors
static Material m_RadialBlur
static int m_ShockEffect
static ref array< int > m_VignetteEffects
static int m_VignetteMenu
static int m_VignetteShock
static int m_VignetteTunnel
static int m_VignetteUnconscious
static ref map< int, ref array< float > > m_VignetteValues
Detailed Description
Deprecated; 'PPEManager' used instead.
Definition at line 2 of file ppeffects.c.
Member Function Documentation
AddPPMask()
static void PPEffects::AddPPMask (float ndcX, float ndcY, float ndcRadius, float ndcBlur) inline static private
Definition at line 508 of file ppeffects.c.
    {
        GetGame().AddPPMask(ndcX, ndcY, ndcRadius, ndcBlur);
    }
References CGame::AddPPMask(), and GetGame().
DisableBurlapSackBlindness()
static void PPEffects::DisableBurlapSackBlindness () inline static private
Definition at line 577 of file ppeffects.c.
    {
        SetColorValue(m_BurlapBlindness, 0, 0, 0, 0, 0.0);
        UpdateColor();
        g_Game.SetEVValue(0);
    }
References g_Game, m_BurlapBlindness, SetColorValue(), and UpdateColor().
EnableBurlapSackBlindness()
static void PPEffects::EnableBurlapSackBlindness () inline static private
Definition at line 570 of file ppeffects.c.
    {
        SetColorValue(m_BurlapBlindness, 0, 0, 0, 1, 1.0);
        UpdateColor();
        g_Game.SetEVValue(-5);
    }
References g_Game, m_BurlapBlindness, SetColorValue(), and UpdateColor().
FlashbangEffect()
static void PPEffects::FlashbangEffect (float value) inline static private
Definition at line 558 of file ppeffects.c.
    {
        float hitEffectColor[4];
        hitEffectColor[0] = 1;
        hitEffectColor[1] = 1;
        hitEffectColor[2] = 1;
        hitEffectColor[3] = Math.Lerp(Math.Clamp(m_ColorValueTotal[0],0,1), 1, value);
        m_MatColors.SetParam("OverlayColor", hitEffectColor);
        m_MatColors.SetParam("OverlayFactor", 0.75);
    }
References Math::Clamp(), Math::Lerp(), m_ColorValueTotal, m_MatColors, and Material::SetParam().
HitEffect()
static void PPEffects::HitEffect (float value) inline static private
Definition at line 528 of file ppeffects.c.
    {
        float m_HitEffectColor[4];
        m_HitEffectColor[0] = Math.Lerp(Math.Clamp(m_ColorValueTotal[0],0,1), 1, value);
        m_HitEffectColor[1] = 0;
        m_HitEffectColor[2] = 0;
        m_HitEffectColor[3] = Math.Lerp(Math.Clamp(m_ColorValueTotal[0],0,1), 1, value);
        /*
        Print("---------------------------");
        Print("m_ColorValueTotal[0]: " + m_ColorValueTotal[0]);
        Print("value: " + value);
        Print("---------------------------");
        Print("r: " + m_HitEffectColor[0]);
        Print("g: " + m_HitEffectColor[1]);
        Print("b: " + m_HitEffectColor[2]);
        Print("a: " + m_HitEffectColor[3]);
        */
        m_MatColors.SetParam("OverlayColor", m_HitEffectColor);
        m_MatColors.SetParam("OverlayFactor", 0.05);
    }
References Math::Clamp(), Math::Lerp(), m_ColorValueTotal, m_MatColors, and Material::SetParam().
Init()
static void PPEffects::Init () inline static private
Definition at line 52 of file ppeffects.c.
    {
        //Print("---Init PPEffects---");
        if ( m_BlurValues )
        {
            delete m_BlurValues;
        }
        if ( m_ChromAbbValues )
        {
            delete m_ChromAbbValues;
        }
        if ( m_VignetteEffects )
        {
            delete m_VignetteEffects;
        }
        if ( m_VignetteValues )
        {
            delete m_VignetteValues;
        }
        if ( m_ColorEffect )
        {
            delete m_ColorEffect;
        }
        m_MatColors = GetGame().GetWorld().GetMaterial("graphics/materials/postprocess/glow");
        m_RadialBlur = GetGame().GetWorld().GetMaterial("graphics/materials/postprocess/radialblur");
        m_BlurValues = new array<float>;
        m_ChromAbbValues = new array<float>;
        m_VignetteEffects = new array<int>;
        m_VignetteValues = new map<int, ref array<float>>;
        // add new blur effects here
        m_BlurInventory     = RegisterBlurEffect();
        m_BlurDrunk         = RegisterBlurEffect();
        m_BlurFever         = RegisterBlurEffect();
        m_BlurMenu          = RegisterBlurEffect();
        m_BlurOptics        = RegisterBlurEffect();
        m_BlurFlashbang     = RegisterBlurEffect();
        // add chromatic abberation effects here
        m_ChromAbbOptic     = RegisterChromAbbEffect();
        //m_ChromAbbShock   = RegisterChromAbbEffect();
        // add vignette effects here
        m_VignetteUnconscious   = RegisterVignetteEffect();
        m_VignetteShock         = RegisterVignetteEffect();
        m_VignetteTunnel        = RegisterVignetteEffect();
        m_VignetteMenu          = RegisterVignetteEffect();
        m_ColorEffect = new array<float>;
        m_ColorValues = new map<int, ref array<float>>;
        // add new color effects here
        m_BurlapBlindness   = RegisterColorEffect();
        m_DyingEffect       = RegisterColorEffect();
        m_ShockEffect       = RegisterColorEffect();
        // ------------------------NV-related stuff below------------------------
        array<float> colorizeDefault = {0.0, 0.0, 0.0};
        m_ColorizeEffects = new map<int, ref array<float>>;
        // colorize: r, g, b
        // colorize effects registration
        m_ColorizeEffects.Set(PPEffects.COLORIZE_NV, colorizeDefault);
        //SetNVParams(1.0, 0.0, 2.35, 2.75); //default values
        // ------------------------End of NV-related stuff------------------------
    }
References COLORIZE_NV, GetGame(), World::GetMaterial(), CGame::GetWorld(), m_BlurDrunk, m_BlurFever, m_BlurFlashbang, m_BlurInventory, m_BlurMenu, m_BlurOptics, m_BlurValues, m_BurlapBlindness, m_ChromAbbOptic, m_ChromAbbValues, m_ColorEffect, m_ColorizeEffects, m_ColorValues, m_DyingEffect, m_MatColors, m_RadialBlur, m_ShockEffect, m_VignetteEffects, m_VignetteMenu, m_VignetteShock, m_VignetteTunnel, m_VignetteUnconscious, m_VignetteValues, RegisterBlurEffect(), RegisterChromAbbEffect(), RegisterColorEffect(), and RegisterVignetteEffect().
Referenced by DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), and MissionBase::OnInit().
OverrideDOF()
static void PPEffects::OverrideDOF (bool enable, float focusDistance, float focusLength, float focusLengthNear, float blur, float focusDepthOffset) inline static private
Definition at line 503 of file ppeffects.c.
    {
        GetGame().OverrideDOF(enable, focusDistance, focusLength, focusLengthNear, blur, focusDepthOffset);
    }
References GetGame(), and CGame::OverrideDOF().
Referenced by ResetDOFOverride().
PerformSetLensEffect()
static void PPEffects::PerformSetLensEffect (float lens, float chromAbb, float centerX, float centerY) inline static private
added for convenience
Definition at line 419 of file ppeffects.c.
    {
        m_MatColors.SetParam("LensDistort", lens);
        SetChromAbbOptic(chromAbb);
        m_MatColors.SetParam("LensCenterX", centerX);
        m_MatColors.SetParam("LensCenterY", centerY);
    }
References m_MatColors, SetChromAbbOptic(), and Material::SetParam().
Referenced by SetLensEffect().
RegisterBlurEffect()
static int PPEffects::RegisterBlurEffect () inline static private
Definition at line 149 of file ppeffects.c.
    {
        return m_BlurValues.Insert(0);
    }
References m_BlurValues.
Referenced by Init().
RegisterChromAbbEffect()
static int PPEffects::RegisterChromAbbEffect () inline static private
Definition at line 255 of file ppeffects.c.
    {
        return m_ChromAbbValues.Insert(0);
    }
References m_ChromAbbValues.
Referenced by Init().
RegisterColorEffect()
static int PPEffects::RegisterColorEffect () inline static private
Definition at line 370 of file ppeffects.c.
    {
        return m_ColorEffect.Insert(0);
    }
References m_ColorEffect.
Referenced by Init().
RegisterVignetteEffect()
static int PPEffects::RegisterVignetteEffect () inline static private
Definition at line 460 of file ppeffects.c.
    {
        return m_VignetteEffects.Insert(0);
    }
References m_VignetteEffects.
Referenced by Init().
ResetAll()
static void PPEffects::ResetAll () inline static private
Definition at line 744 of file ppeffects.c.
    {
        ResetBlurEffects();
        ResetColorEffects();
        ResetVignettes();
        ResetPPMask();
        ResetDOFOverride();
        ResetLensEffect();
        SetBloodSaturation(1);
        //RemoveUnconsciousnessVignette();
        ResetColorize();
    }
References ResetBlurEffects(), ResetColorEffects(), ResetColorize(), ResetDOFOverride(), ResetLensEffect(), ResetPPMask(), ResetVignettes(), and SetBloodSaturation().
ResetBlurEffects()
static void PPEffects::ResetBlurEffects () inline static private
Definition at line 120 of file ppeffects.c.
    {
        if( m_BlurValues )
        {
            for ( int i = 0; i < m_BlurValues.Count(); ++i )
            {
                m_BlurValues[i] = 0;
            }
            UpdateBlur();
        }
    }
References m_BlurValues, and UpdateBlur().
Referenced by ResetAll().
ResetChromAbbEffects()
static void PPEffects::ResetChromAbbEffects () inline static private
Definition at line 260 of file ppeffects.c.
    {
        if( m_ChromAbbValues )
        {
            for ( int i = 0; i < m_ChromAbbValues.Count(); ++i )
            {
                m_ChromAbbValues[i] = 0;
            }
            UpdateChromAbb();
        }
    }
References m_ChromAbbValues, and UpdateChromAbb().
ResetColorEffects()
static void PPEffects::ResetColorEffects () inline static private
Definition at line 343 of file ppeffects.c.
    {
        if( m_ColorEffect )
        {
            for ( int i = 0; i < m_ColorEffect.Count(); ++i )
            {
                //m_ColorEffect[i] = 0;
                m_ColorValues.Set(i,{0,0,0,0,0});
            }
            UpdateColor();
        }
    }
References m_ColorEffect, m_ColorValues, and UpdateColor().
Referenced by ResetAll().
ResetColorize()
static void PPEffects::ResetColorize () inline static private
Definition at line 706 of file ppeffects.c.
    {
        float color[4];
        color[0] = 1.0;
        color[1] = 1.0;
        color[2] = 1.0;
        color[3] = 0;
        m_MatColors.SetParam("ColorizationColor", color);
    }
References m_MatColors, and Material::SetParam().
Referenced by ResetAll(), and UpdateColorize().
ResetDOFOverride()
static void PPEffects::ResetDOFOverride () inline static private
Definition at line 518 of file ppeffects.c.
    {
        OverrideDOF(false,0,0,0,0,1);
    }
References OverrideDOF().
Referenced by ResetAll().
ResetLensEffect()
static void PPEffects::ResetLensEffect () inline static private
Definition at line 523 of file ppeffects.c.
    {
        SetLensEffect(0,0,0,0);
    }
References SetLensEffect().
Referenced by ResetAll().
ResetPPMask()
static void PPEffects::ResetPPMask () inline static private
Definition at line 513 of file ppeffects.c.
    {
        if( GetGame() ) GetGame().ResetPPMask();
    }
References GetGame(), and CGame::ResetPPMask().
Referenced by ResetAll().
ResetRadialBlur()
static void PPEffects::ResetRadialBlur () inline static private
Definition at line 132 of file ppeffects.c.
    {
        SetRadialBlur(0,0,0,0);
    }
References SetRadialBlur().
ResetVignettes()
static void PPEffects::ResetVignettes () inline static private
Definition at line 489 of file ppeffects.c.
    {
        if( m_VignetteValues )
        {
            for ( int i = 0; i < m_VignetteValues.Count(); ++i )
            {
                array<float> values = {0,0,0,0,0};
                m_VignetteValues.Set(i, values);
            }
            UpdateVignette();
        }
    }
References m_VignetteValues, and UpdateVignette().
Referenced by ResetAll().
SetBloodSaturation()
static void PPEffects::SetBloodSaturation (float value) inline static private
Definition at line 640 of file ppeffects.c.
    {
        m_BloodSaturation = value;
        UpdateSaturation();
    }
References m_BloodSaturation, and UpdateSaturation().
Referenced by ResetAll().
SetBloom()
static void PPEffects::SetBloom (float thres, float steep, float inten) inline static private
Definition at line 737 of file ppeffects.c.
    {
        m_MatColors.SetParam("BloomThreshold", thres);
        m_MatColors.SetParam("BloomSteepness", steep);
        m_MatColors.SetParam("BloomIntensity", inten);
    }
References m_MatColors, and Material::SetParam().
SetBlur()
static void PPEffects::SetBlur (float value) inline static private
sets blur effect to an absolute value between 0..1
Definition at line 168 of file ppeffects.c.
    {
        if (GetGame())
        {
            Material mat_blur = GetGame().GetWorld().GetMaterial("graphics/materials/postprocess/gauss");
            if (mat_blur)
            {
                mat_blur.SetParam("Intensity", value);
            }
        }
    }
References GetGame(), World::GetMaterial(), CGame::GetWorld(), and Material::SetParam().
Referenced by UpdateBlur().
SetBlurDrunk()
static void PPEffects::SetBlurDrunk (float value) inline static private
Set blur drunk effect to a specified 'value' between 0..1.
Definition at line 204 of file ppeffects.c.
    {
        SetBlurValue(m_BlurDrunk, value);
        UpdateBlur();
    }
References m_BlurDrunk, SetBlurValue(), and UpdateBlur().
SetBlurFever()
static void PPEffects::SetBlurFever (float value) inline static private
Set blur drunk effect to a specified 'value' between 0..1.
Definition at line 212 of file ppeffects.c.
    {
        SetBlurValue(m_BlurFever, value);
        UpdateBlur();
    }
References m_BlurFever, SetBlurValue(), and UpdateBlur().
SetBlurFlashbang()
static void PPEffects::SetBlurFlashbang (float value) inline static private
Set blur flashbang hit effect to a specified 'value' between 0..1.
Definition at line 236 of file ppeffects.c.
    {
        SetBlurValue(m_BlurFlashbang, value);
        UpdateBlur();
    }
References m_BlurFlashbang, SetBlurValue(), and UpdateBlur().
SetBlurInventory()
static void PPEffects::SetBlurInventory (float value) inline static private
Set blur inventory effect to a specified 'value' between 0..1.
Definition at line 197 of file ppeffects.c.
    {
        SetBlurValue(m_BlurInventory, value);
        UpdateBlur();
    }
References m_BlurInventory, SetBlurValue(), and UpdateBlur().
SetBlurMenu()
static void PPEffects::SetBlurMenu (float value) inline static private
Set menu blur to a specified 'value' between 0..1.
Definition at line 220 of file ppeffects.c.
    {
        SetBlurValue(m_BlurMenu, value);
        UpdateBlur();
    }
References m_BlurMenu, SetBlurValue(), and UpdateBlur().
SetBlurOptics()
static void PPEffects::SetBlurOptics (float value) inline static private
Set optics and ironsights blur to a specified 'value' between 0..1.
Definition at line 228 of file ppeffects.c.
    {
        SetBlurValue(m_BlurOptics, value);
        UpdateBlur();
    }
References m_BlurOptics, SetBlurValue(), and UpdateBlur().
SetBlurShock()
static void PPEffects::SetBlurShock (float value) inline static private
Definition at line 242 of file ppeffects.c.
    {
        SetBlurValue(m_BlurShock, value);
        UpdateBlur();
    }
References m_BlurShock, SetBlurValue(), and UpdateBlur().
SetBlurValue()
static void PPEffects::SetBlurValue (int index, float value) inline static private
Definition at line 137 of file ppeffects.c.
    {
        if ( m_BlurValues && index < m_BlurValues.Count() )
        {
            m_BlurValues[index] = value;
        }
        else
        {
            Print("Error: PPEffects: m_BlurValues with index: "+ index +" is not registered.");
        }
    }
References m_BlurValues, and Print().
Referenced by SetBlurDrunk(), SetBlurFever(), SetBlurFlashbang(), SetBlurInventory(), SetBlurMenu(), SetBlurOptics(), and SetBlurShock().
SetChromAbb()
static void PPEffects::SetChromAbb (float value) inline static private
Definition at line 284 of file ppeffects.c.
    {
        if (GetGame())
        {
            if (m_MatColors)
            {
                //Print("SetChromAbb: " + value);
                m_MatColors.SetParam("MaxChromAbberation", value);
                //SetVignette(value,0,255,0);
            }
        }
    }
References GetGame(), m_MatColors, and Material::SetParam().
Referenced by UpdateChromAbb().
SetChromAbbOptic()
static void PPEffects::SetChromAbbOptic (float value) inline static private
Definition at line 312 of file ppeffects.c.
    {
        SetChromAbbValue(m_ChromAbbOptic, value);
        UpdateChromAbb();
    }
References m_ChromAbbOptic, SetChromAbbValue(), and UpdateChromAbb().
Referenced by PerformSetLensEffect().
SetChromAbbValue()
static void PPEffects::SetChromAbbValue (int index, float value) inline static private
Definition at line 272 of file ppeffects.c.
    {
        if ( m_ChromAbbValues && index < m_ChromAbbValues.Count() )
        {
            m_ChromAbbValues[index] = value;
        }
        else
        {
            Print("Error: PPEffects: m_ChromAbbValues with index: "+ index +" is not registered.");
        }
    }
References m_ChromAbbValues, and Print().
Referenced by SetChromAbbOptic().
SetColorizationNV()
static void PPEffects::SetColorizationNV (float r, float g, float b) inline static private
Definition at line 659 of file ppeffects.c.
    {
        array<float> colorizeArray = {r, g, b};
        m_ColorizeEffects.Set(PPEffects.COLORIZE_NV, colorizeArray);
        UpdateColorize();
    }
References COLORIZE_NV, m_ColorizeEffects, and UpdateColorize().
SetColorValue()
static void PPEffects::SetColorValue (int index, float r, float g, float b, float a, float overlay) inline static private
Definition at line 356 of file ppeffects.c.
    {
        if ( index < m_ColorEffect.Count() )
        {
            array<float> values = {r,g,b,a,overlay};
            m_ColorValues.Set(index, values);
        }
        else
        {
            Print("Error: PPEffects: m_ColorValues with index: "+ index +" is not registered.");
        }
    }
References m_ColorEffect, m_ColorValues, and Print().
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), SetDeathDarkening(), and SetShockEffectColor().
SetDeathDarkening()
static void PPEffects::SetDeathDarkening (float value) inline static private
Definition at line 584 of file ppeffects.c.
    {
        value = Math.Clamp(value,0,1);
        SetColorValue(m_DyingEffect, 0, 0, 0, 1, value);
        UpdateColor();
        if (value > 0.99)
            SetEVValuePP(-5); //additional "darkness" to avoid lens flare
        else
            SetEVValuePP(0);
    }
References Math::Clamp(), m_DyingEffect, SetColorValue(), SetEVValuePP(), and UpdateColor().
SetEVValuePP()
static void PPEffects::SetEVValuePP (float value) inline static private
Definition at line 717 of file ppeffects.c.
    {
        g_Game.SetEVValue(value);
    }
References g_Game.
Referenced by SetDeathDarkening().
SetLensEffect()
static void PPEffects::SetLensEffect (float lens, float chromAbb, float centerX, float centerY) inline static private
set lens effect
Parameters
lens <-5, 5>, 0 = disable (performance plus), > 0 = outside effect, < 0 inside effect
chromAbb <0, 1>, chromaticity, 1 = max, 0 disable (performance plus)
centerX <-1, 1>, center of effect, 0 = screen center in X
centerY <-1, 1>, center of effect, 0 = screen center in Y
Definition at line 413 of file ppeffects.c.
    {
        PerformSetLensEffect(lens, chromAbb, centerX, centerY);
    }
References PerformSetLensEffect().
Referenced by ResetLensEffect().
SetMenuVignette()
static void PPEffects::SetMenuVignette (float value) inline static private
Definition at line 483 of file ppeffects.c.
    {
        SetVignetteEffectValue(m_VignetteMenu, value, 0,0,0,0); //todo
        UpdateVignette();
    }
References m_VignetteMenu, SetVignetteEffectValue(), and UpdateVignette().
SetNVParams()
static void PPEffects::SetNVParams (float light_mult, float noise_intensity, float sharpness, float grain_size) inline static private
Definition at line 724 of file ppeffects.c.
    {
        Material matHDR = GetGame().GetWorld().GetMaterial("Graphics/Materials/postprocess/filmgrainNV");
/*#ifdef PLATFORM_CONSOLE
//worst-case scenario console fix!
        noise_intensity = 0.0;
#endif*/
        g_Game.NightVissionLightParams(light_mult, noise_intensity);
        matHDR.SetParam("Sharpness", sharpness);
        matHDR.SetParam("GrainSize", grain_size);
    }
References g_Game, GetGame(), World::GetMaterial(), CGame::GetWorld(), and Material::SetParam().
SetRadialBlur()
static void PPEffects::SetRadialBlur (float powerX, float powerY, float offsetX, float offsetY) inline static private
sets blur effect to an absolute value between 0..1
Definition at line 156 of file ppeffects.c.
    {
        if (GetGame())
        {
            m_RadialBlur.SetParam("PowerX", powerX);
            m_RadialBlur.SetParam("PowerY", powerY);
            m_RadialBlur.SetParam("OffsetX", offsetX);
            m_RadialBlur.SetParam("OffsetY", offsetY);
        }
    }
References GetGame(), m_RadialBlur, and Material::SetParam().
Referenced by ResetRadialBlur().
SetShockEffectColor()
static void PPEffects::SetShockEffectColor (float value) inline static private
Definition at line 549 of file ppeffects.c.
    {
        if (value > 0)
            SetColorValue(m_ShockEffect, COLOR_SHOCK, COLOR_SHOCK, COLOR_SHOCK, 1, value);
        else
            SetColorValue(m_ShockEffect, 0, 0, 0, 1, value);
        UpdateColor();
    }
References COLOR_SHOCK, m_ShockEffect, SetColorValue(), and UpdateColor().
SetShockVignette()
static void PPEffects::SetShockVignette (float value) inline static private
Definition at line 471 of file ppeffects.c.
    {
        SetVignetteEffectValue(m_VignetteShock, value, 0,0,0,0); //todo
        UpdateVignette();
    }
References m_VignetteShock, SetVignetteEffectValue(), and UpdateVignette().
SetTunnelVignette()
static void PPEffects::SetTunnelVignette (float value) inline static private
Definition at line 477 of file ppeffects.c.
    {
        SetVignetteEffectValue(m_VignetteTunnel, value, 0,0,0,0); //todo
        UpdateVignette();
    }
References m_VignetteTunnel, SetVignetteEffectValue(), and UpdateVignette().
SetUnconsciousnessVignette()
static void PPEffects::SetUnconsciousnessVignette (float value) inline static private
Definition at line 465 of file ppeffects.c.
    {
        SetVignetteEffectValue(m_VignetteUnconscious, value, 0,0,0,0); //todo
        UpdateVignette();
    }
References m_VignetteUnconscious, SetVignetteEffectValue(), and UpdateVignette().
SetVignette()
static void PPEffects::SetVignette (float intensity, float R, float G, float B, float A) inline static private
set vignette
Parameters
intensity <0, 1>, intensity of effect, 0 = disable
R
G
B
Definition at line 434 of file ppeffects.c.
    {
        float color[4];
        color[0] = R;
        color[1] = G;
        color[2] = B;
        color[3] = A;
        m_MatColors.SetParam("Vignette", intensity);
        m_MatColors.SetParam("VignetteColor", color);
    }
References A, B, m_MatColors, R, and Material::SetParam().
Referenced by UpdateVignette().
SetVignetteEffectValue()
static void PPEffects::SetVignetteEffectValue (int index, float intensity, float r, float g, float b, float a) inline static private
Definition at line 446 of file ppeffects.c.
    {
        if ( index < m_VignetteEffects.Count() )
        {
            array<float> values = {intensity,r,g,b,a};
            m_VignetteValues.Set(index, values);
        }
        else
        {
            Print("Error: PPEffects: m_ColorValues with index: "+ index +" is not registered.");
        }
    }
References m_VignetteEffects, m_VignetteValues, and Print().
Referenced by SetMenuVignette(), SetShockVignette(), SetTunnelVignette(), and SetUnconsciousnessVignette().
UpdateBlur()
static void PPEffects::UpdateBlur () inline static private
updates the blur post process effect where the resulting blur is an aggregate of all individual blur effect values
Definition at line 182 of file ppeffects.c.
    {
        float blur_value_total = 0;
        if( m_BlurValues )
        {
            for ( int i = 0; i < m_BlurValues.Count(); ++i )
            {
                blur_value_total += m_BlurValues[i];
            }
        }
        SetBlur( blur_value_total );
    }
References m_BlurValues, and SetBlur().
Referenced by ResetBlurEffects(), SetBlurDrunk(), SetBlurFever(), SetBlurFlashbang(), SetBlurInventory(), SetBlurMenu(), SetBlurOptics(), and SetBlurShock().
UpdateChromAbb()
static void PPEffects::UpdateChromAbb () inline static private
updates the chromatic abberation post process effect where the resulting chromabb is an aggregate of all individual chromabb effect values
Definition at line 298 of file ppeffects.c.
    {
        float chromabb_value_total = 0;
        if( m_ChromAbbValues )
        {
            for ( int i = 0; i < m_ChromAbbValues.Count(); ++i )
            {
                chromabb_value_total += m_ChromAbbValues[i]; //currently additive!
            }
        }
        SetChromAbb( chromabb_value_total );
    }
References m_ChromAbbValues, and SetChromAbb().
Referenced by ResetChromAbbEffects(), and SetChromAbbOptic().
UpdateColor()
static void PPEffects::UpdateColor () inline static private
Definition at line 375 of file ppeffects.c.
    {
        float color_value_total[4] = {0,0,0,0};
        float color_overlay;
        /*
        m_MatColors.ResetParam("OverlayColor");
        m_MatColors.ResetParam("OverlayFactor");
        */
        if( !GetGame() || !GetGame().GetWorld() )
        {
            return;
        }
        for ( int i = 0; i < m_ColorValues.Count(); ++i )
        {
            int key = m_ColorValues.GetKey(i);
            array<float> value = m_ColorValues.Get(key);
            color_value_total[0]    = color_value_total[0] + value[0];
            color_value_total[1]    = color_value_total[1] + value[1];
            color_value_total[2]    = color_value_total[2] + value[2];
            color_value_total[3]    = color_value_total[3] + value[3];
            color_overlay           += value[4];
        }
        m_ColorValueTotal = color_value_total;
        m_ColorOverlayTotal = color_overlay;
        m_MatColors.SetParam("OverlayColor", color_value_total);
        m_MatColors.SetParam("OverlayFactor", color_overlay);
    }
References GetGame(), m_ColorOverlayTotal, m_ColorValues, m_ColorValueTotal, m_MatColors, and Material::SetParam().
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), ResetColorEffects(), SetDeathDarkening(), and SetShockEffectColor().
UpdateColorize()
static void PPEffects::UpdateColorize () inline static private
Definition at line 666 of file ppeffects.c.
    {
        bool foundActiveEffect = false;
        int lowestKey = 1000000;
        array<float> chosenArray;
        // search for active effect with highest priority (lower value of key better)
        for (int i = 0; i < m_ColorizeEffects.Count(); i++)
        {
            int currentKey = m_ColorizeEffects.GetKey(i);
            array<float> colorizeValues = m_ColorizeEffects.Get(currentKey);
            // check for non-zero active effect
            for (int j = 0; j < colorizeValues.Count(); j++)
            {
                if (colorizeValues[j] != 0.0)
                {
                    if (currentKey < lowestKey)
                    {
                        chosenArray = colorizeValues;
                        lowestKey = currentKey;
                        foundActiveEffect = true;
                        break;
                    }
                }
            }
        }
        if (foundActiveEffect)
        {
            float color[4];
            color[0] = chosenArray[0];
            color[1] = chosenArray[1];
            color[2] = chosenArray[2];
            color[3] = 0;
            m_MatColors.SetParam("ColorizationColor", color);
        }
        else
        {
            // no active event found, reset colorize effect
            ResetColorize();
        }
    }
References m_ColorizeEffects, m_MatColors, ResetColorize(), and Material::SetParam().
Referenced by SetColorizationNV().
UpdateSaturation()
static void PPEffects::UpdateSaturation () inline static private
Definition at line 595 of file ppeffects.c.
    {
        m_MatColors.SetParam("Saturation", m_BloodSaturation/*+add_additional_modifiers_here*/);
    }
References m_BloodSaturation, m_MatColors, and Material::SetParam().
Referenced by SetBloodSaturation().
UpdateVignette()
static void PPEffects::UpdateVignette () inline static private
Definition at line 600 of file ppeffects.c.
    {
        float color[4];
        float intesity;
        float intensity_value_total = 0; //use just the highest?
        if( m_VignetteEffects )
        {
            for ( int i = 0; i < m_VignetteEffects.Count(); ++i )
            {
                if (m_VignetteValues.Get(i))
                {
                    /*color[0] = m_VignetteValues.Get(i)[1]; //red
                    color[1] = m_VignetteValues.Get(i)[2]; //green
                    color[2] = m_VignetteValues.Get(i)[3]; //blue
                    color[3] = m_VignetteValues.Get(i)[4]; //alpha*/
                    color[0] = m_VignetteValues.Get(i).Get(1); //red
                    color[1] = m_VignetteValues.Get(i).Get(2); //green
                    color[2] = m_VignetteValues.Get(i).Get(3); //blue
                    color[3] = m_VignetteValues.Get(i).Get(4); //alpha
                    intesity = m_VignetteValues.Get(i).Get(0);
                    intensity_value_total += intesity;
                }
                else
                {
                    //Print("no m_VignetteValues");
                }
            }
        }
        /*color[0] = m_UnconsciousVignetteColor[0];
        color[1] = m_UnconsciousVignetteColor[1];
        color[2] = m_UnconsciousVignetteColor[2];
        intesity = m_UnconsciousVignetteIntesity;*/
        SetVignette( intensity_value_total, color[0], color[1], color[2], color[3] );
    }
References m_VignetteEffects, m_VignetteValues, and SetVignette().
Referenced by ResetVignettes(), SetMenuVignette(), SetShockVignette(), SetTunnelVignette(), and SetUnconsciousnessVignette().
Member Data Documentation
COLOR_SHOCK
const float PPEffects::COLOR_SHOCK = 0.1 static private
Definition at line 8 of file ppeffects.c.
Referenced by SetShockEffectColor().
COLORIZE_NV
const int PPEffects::COLORIZE_NV = 100 static private
Definition at line 5 of file ppeffects.c.
Referenced by Init(), and SetColorizationNV().
m_BloodSaturation
float PPEffects::m_BloodSaturation static private
Definition at line 33 of file ppeffects.c.
Referenced by SetBloodSaturation(), and UpdateSaturation().
m_BlurDrunk
int PPEffects::m_BlurDrunk static private
Definition at line 14 of file ppeffects.c.
Referenced by Init(), and SetBlurDrunk().
m_BlurFever
int PPEffects::m_BlurFever static private
Definition at line 15 of file ppeffects.c.
Referenced by Init(), and SetBlurFever().
m_BlurFlashbang
int PPEffects::m_BlurFlashbang static private
Definition at line 18 of file ppeffects.c.
Referenced by Init(), and SetBlurFlashbang().
m_BlurInventory
int PPEffects::m_BlurInventory static private
Definition at line 13 of file ppeffects.c.
Referenced by Init(), and SetBlurInventory().
m_BlurMenu
int PPEffects::m_BlurMenu static private
Definition at line 16 of file ppeffects.c.
Referenced by Init(), and SetBlurMenu().
m_BlurOptics
int PPEffects::m_BlurOptics static private
Definition at line 17 of file ppeffects.c.
Referenced by Init(), and SetBlurOptics().
m_BlurShock
int PPEffects::m_BlurShock static private
Definition at line 19 of file ppeffects.c.
Referenced by SetBlurShock().
m_BlurValues
ref array<float> PPEffects::m_BlurValues static private
Definition at line 35 of file ppeffects.c.
Referenced by Init(), RegisterBlurEffect(), ResetBlurEffects(), SetBlurValue(), and UpdateBlur().
m_BurlapBlindness
int PPEffects::m_BurlapBlindness static private
Definition at line 21 of file ppeffects.c.
Referenced by DisableBurlapSackBlindness(), EnableBurlapSackBlindness(), and Init().
m_ChromAbbOptic
int PPEffects::m_ChromAbbOptic static private
Definition at line 25 of file ppeffects.c.
Referenced by Init(), and SetChromAbbOptic().
m_ChromAbbValues
ref array<float> PPEffects::m_ChromAbbValues static private
Definition at line 36 of file ppeffects.c.
Referenced by Init(), RegisterChromAbbEffect(), ResetChromAbbEffects(), SetChromAbbValue(), and UpdateChromAbb().
m_ColorEffect
ref array<float> PPEffects::m_ColorEffect static private
Definition at line 40 of file ppeffects.c.
Referenced by Init(), RegisterColorEffect(), ResetColorEffects(), and SetColorValue().
m_ColorizeEffects
ref map<int, ref array<float> > PPEffects::m_ColorizeEffects static private
Definition at line 41 of file ppeffects.c.
Referenced by Init(), SetColorizationNV(), and UpdateColorize().
m_ColorOverlayTotal
float PPEffects::m_ColorOverlayTotal static private
Definition at line 47 of file ppeffects.c.
Referenced by UpdateColor().
m_ColorValues
ref map<int, ref array<float> > PPEffects::m_ColorValues static private
Definition at line 39 of file ppeffects.c.
Referenced by Init(), ResetColorEffects(), SetColorValue(), and UpdateColor().
m_ColorValueTotal
float PPEffects::m_ColorValueTotal[4] = {0,0,0,0} static private
Definition at line 46 of file ppeffects.c.
Referenced by FlashbangEffect(), HitEffect(), and UpdateColor().
m_DyingEffect
int PPEffects::m_DyingEffect static private
Definition at line 22 of file ppeffects.c.
Referenced by Init(), and SetDeathDarkening().
m_MatColors
Material PPEffects::m_MatColors static private
Definition at line 49 of file ppeffects.c.
Referenced by FlashbangEffect(), HitEffect(), Init(), PerformSetLensEffect(), ResetColorize(), SetBloom(), SetChromAbb(), SetVignette(), UpdateColor(), UpdateColorize(), and UpdateSaturation().
m_RadialBlur
Material PPEffects::m_RadialBlur static private
Definition at line 50 of file ppeffects.c.
Referenced by Init(), and SetRadialBlur().
m_ShockEffect
int PPEffects::m_ShockEffect static private
Definition at line 23 of file ppeffects.c.
Referenced by Init(), and SetShockEffectColor().
m_VignetteEffects
ref array<int> PPEffects::m_VignetteEffects static private
Definition at line 37 of file ppeffects.c.
Referenced by Init(), RegisterVignetteEffect(), SetVignetteEffectValue(), and UpdateVignette().
m_VignetteMenu
int PPEffects::m_VignetteMenu static private
Definition at line 31 of file ppeffects.c.
Referenced by Init(), and SetMenuVignette().
m_VignetteShock
int PPEffects::m_VignetteShock static private
Definition at line 29 of file ppeffects.c.
Referenced by Init(), and SetShockVignette().
m_VignetteTunnel
int PPEffects::m_VignetteTunnel static private
Definition at line 30 of file ppeffects.c.
Referenced by Init(), and SetTunnelVignette().
m_VignetteUnconscious
int PPEffects::m_VignetteUnconscious static private
Definition at line 28 of file ppeffects.c.
Referenced by Init(), and SetUnconsciousnessVignette().
m_VignetteValues
ref map<int, ref array<float> > PPEffects::m_VignetteValues static private
Definition at line 38 of file ppeffects.c.
Referenced by Init(), ResetVignettes(), SetVignetteEffectValue(), and UpdateVignette().