DayzKode: AreaExposureMdfr Class Reference
AreaExposureMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
void ApplyAgentsToBleedingSources (PlayerBase player, float deltaT)
void BleedingSourceCreateCheck (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
float TransmitAgents (PlayerBase player, float count)
Private Attributes
const float AGENT_DOSE_PER_BS_SEC = 0.33
const float AGENTS_PER_SEC = 5
const int EVENT_1_INTERVAL_MAX = 5
const int EVENT_1_INTERVAL_MIN = 3
const int EVENT_2_INTERVAL_MAX = 18
const int EVENT_2_INTERVAL_MIN = 13
protected float m_NextEvent1
protected float m_NextEvent2
protected float m_Time1
protected float m_Time2
Detailed Description
Definition at line 1 of file areaexposure.c.
Member Function Documentation
ActivateCondition()
override bool AreaExposureMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 33 of file areaexposure.c.
    {
        return false;
    }
ApplyAgentsToBleedingSources()
void AreaExposureMdfr::ApplyAgentsToBleedingSources (PlayerBase player, float deltaT) inline private
Definition at line 106 of file areaexposure.c.
    {
        int count = player.GetBleedingSourceCount();
        float agent_dose = count * AGENT_DOSE_PER_BS_SEC * deltaT;
        player.InsertAgent(eAgents.CHEMICAL_POISON, agent_dose);
    }
References AGENT_DOSE_PER_BS_SEC.
Referenced by OnTick().
BleedingSourceCreateCheck()
void AreaExposureMdfr::BleedingSourceCreateCheck (PlayerBase player) inline private
Definition at line 115 of file areaexposure.c.
    {
        int free_bs_locations = 0;//bitmask where each bit set to 1 represents available bleeding source location
        set<int> list = player.GetBleedingManagerServer().GetBleedingSourcesLocations();
        foreach(int location: list)
        {
            float prot_level = PluginTransmissionAgents.GetProtectionLevelEx(DEF_CHEMICAL, location, player, true);
            float dice_throw = Math.RandomFloat01();
            if(dice_throw > prot_level)
            {
                free_bs_locations = player.GetBleedingManagerServer().GetFreeBleedingSourceBitsByInvLocation(location) | free_bs_locations;
            }
        }
        int num_of_free_bs = Math.GetNumberOfSetBits(free_bs_locations);//gets us the number of bits set to 1, where each represents a free bleeding source location
        if ( num_of_free_bs > 0 )
        {
            int random_bs_index = Math.RandomIntInclusive(0, num_of_free_bs - 1 );// - 1 on the max to convert count to index
            int random_bs_bit = Math.Pow(2, Math.GetNthBitSet(free_bs_locations,random_bs_index));
            player.GetBleedingManagerServer().AttemptAddBleedingSourceDirectly(random_bs_bit, eBleedingSourceType.CONTAMINATED);
        }
    }
References DEF_CHEMICAL, Math::GetNthBitSet(), Math::GetNumberOfSetBits(), Math::Pow(), Math::RandomFloat01(), and Math::RandomIntInclusive().
Referenced by OnTick().
DeactivateCondition()
override bool AreaExposureMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 59 of file areaexposure.c.
    {
        return false;
    }
Init()
override void AreaExposureMdfr::Init () inline private
Definition at line 21 of file areaexposure.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_AREAEXPOSURE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE_LONG;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE_SHORT;
        m_SyncID                = eModifierSyncIDs.MODIFIER_SYNC_ZONE_EXPOSURE;
        DisableActivateCheck();
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE_LONG, DisableActivateCheck(), DisableDeactivateCheck(), m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void AreaExposureMdfr::OnActivate (PlayerBase player) inline private
Definition at line 38 of file areaexposure.c.
    {
        JsonDataContaminatedAreas data = EffectAreaLoader.GetData();
        if (data)
        {
            MiscGameplayFunctions.TeleportCheck(player, data.SafePositions);
        }
        //make the player cough immediately
        float transmitted = TransmitAgents(player, 1);
        if(transmitted)
            player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_COUGH);
        m_NextEvent1 = Math.RandomFloatInclusive( EVENT_1_INTERVAL_MIN, EVENT_1_INTERVAL_MAX );
    }
References EVENT_1_INTERVAL_MAX, EVENT_1_INTERVAL_MIN, EffectAreaLoader::GetData(), m_NextEvent1, Math::RandomFloatInclusive(), JsonDataContaminatedAreas::SafePositions, and TransmitAgents().
OnDeactivate()
override void AreaExposureMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 55 of file areaexposure.c.
    {
    }
OnTick()
override void AreaExposureMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 64 of file areaexposure.c.
    {
        #ifdef DEVELOPER
        if(!player.GetCanBeDestroyed())
            return;
        #endif
        float transmitted = TransmitAgents(player, AGENTS_PER_SEC * deltaT);
        m_Time2 += deltaT;
        if (transmitted)
        {
            m_Time1 += deltaT;
            if (m_Time1 >= m_NextEvent1 )
            {
                player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_COUGH);
                if(Math.RandomFloat01() < 0.25)//creates a cough cooldown once in a while
                {
                    m_NextEvent1 = Math.RandomFloatInclusive( EVENT_1_INTERVAL_MIN * 2, EVENT_1_INTERVAL_MAX * 2 );
                }
                else
                {
                    m_NextEvent1 = Math.RandomFloatInclusive( EVENT_1_INTERVAL_MIN, EVENT_1_INTERVAL_MAX );
                }
                m_Time1 = 0;
            }
        }
        if ( m_Time2 >= m_NextEvent2 )
        {
            BleedingSourceCreateCheck(player);
            m_Time2 = 0;
            m_NextEvent2 = Math.RandomFloatInclusive( EVENT_2_INTERVAL_MIN, EVENT_2_INTERVAL_MAX );
        }
        ApplyAgentsToBleedingSources(player, deltaT);
    }
References AGENTS_PER_SEC, ApplyAgentsToBleedingSources(), BleedingSourceCreateCheck(), EVENT_1_INTERVAL_MAX, EVENT_1_INTERVAL_MIN, EVENT_2_INTERVAL_MAX, EVENT_2_INTERVAL_MIN, m_NextEvent1, m_NextEvent2, m_Time1, m_Time2, Math::RandomFloat01(), Math::RandomFloatInclusive(), and TransmitAgents().
TransmitAgents()
float AreaExposureMdfr::TransmitAgents (PlayerBase player, float count) inline private
Definition at line 140 of file areaexposure.c.
    {
        PluginTransmissionAgents plugin = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
        return plugin.TransmitAgentsEx(null, player, AGT_AIRBOURNE_CHEMICAL, count, eAgents.CHEMICAL_POISON);
    }
References AGT_AIRBOURNE_CHEMICAL, and GetPlugin().
Referenced by OnActivate(), and OnTick().
Member Data Documentation
AGENT_DOSE_PER_BS_SEC
const float AreaExposureMdfr::AGENT_DOSE_PER_BS_SEC = 0.33 private
Definition at line 14 of file areaexposure.c.
Referenced by ApplyAgentsToBleedingSources().
AGENTS_PER_SEC
const float AreaExposureMdfr::AGENTS_PER_SEC = 5 private
Definition at line 6 of file areaexposure.c.
Referenced by OnTick().
EVENT_1_INTERVAL_MAX
const int AreaExposureMdfr::EVENT_1_INTERVAL_MAX = 5 private
Definition at line 4 of file areaexposure.c.
Referenced by OnActivate(), and OnTick().
EVENT_1_INTERVAL_MIN
const int AreaExposureMdfr::EVENT_1_INTERVAL_MIN = 3 private
Definition at line 3 of file areaexposure.c.
Referenced by OnActivate(), and OnTick().
EVENT_2_INTERVAL_MAX
const int AreaExposureMdfr::EVENT_2_INTERVAL_MAX = 18 private
Definition at line 11 of file areaexposure.c.
Referenced by OnTick().
EVENT_2_INTERVAL_MIN
const int AreaExposureMdfr::EVENT_2_INTERVAL_MIN = 13 private
Definition at line 10 of file areaexposure.c.
Referenced by OnTick().
m_NextEvent1
protected float AreaExposureMdfr::m_NextEvent1 private
Definition at line 7 of file areaexposure.c.
Referenced by OnActivate(), and OnTick().
m_NextEvent2
protected float AreaExposureMdfr::m_NextEvent2 private
Definition at line 16 of file areaexposure.c.
Referenced by OnTick().
m_Time1
protected float AreaExposureMdfr::m_Time1 private
Definition at line 8 of file areaexposure.c.
Referenced by OnTick().
m_Time2
protected float AreaExposureMdfr::m_Time2 private
Definition at line 17 of file areaexposure.c.
Referenced by OnTick().