DayzKode: StatDebugObject Class Reference
StatDebugObject Class Reference
Private Member Functions
void Debug ()
string GetName ()
eRemoteDebugType GetType ()
string GetValue ()
void SetType (eRemoteDebugType type)
void StatDebugObject (string name, float value, eRemoteDebugType type)
Private Attributes
string m_Name
eRemoteDebugType m_Type
float m_Value
Detailed Description
Definition at line 1 of file statdebugobject.c.
Constructor & Destructor Documentation
StatDebugObject()
void StatDebugObject::StatDebugObject (string name, float value, eRemoteDebugType type) inline private
Definition at line 7 of file statdebugobject.c.
    {
        m_Name = name;
        m_Value = value;
        m_Type = type;
    }
References m_Name, m_Type, m_Value, and name.
Member Function Documentation
Debug()
void StatDebugObject::Debug () inline private
Definition at line 14 of file statdebugobject.c.
    {
        PrintString("stat_type:"+ m_Name + "|stat_value:"+ m_Value.ToString());
    }
References m_Name, m_Value, PrintString(), and float::ToString().
GetName()
string StatDebugObject::GetName () inline private
Definition at line 19 of file statdebugobject.c.
    {
        return m_Name;
    }
References m_Name.
GetType()
eRemoteDebugType StatDebugObject::GetType () inline private
Definition at line 34 of file statdebugobject.c.
    {
        return m_Type;
    }
References m_Type.
Referenced by SerializeNames(), and SerializeValues().
GetValue()
string StatDebugObject::GetValue () inline private
Definition at line 24 of file statdebugobject.c.
    {
        return m_Value.ToString();
    }
References m_Value, and float::ToString().
SetType()
void StatDebugObject::SetType (eRemoteDebugType type) inline private
Definition at line 29 of file statdebugobject.c.
    {
        m_Type = type;
    }
References m_Type.
Member Data Documentation
m_Name
string StatDebugObject::m_Name private
Definition at line 3 of file statdebugobject.c.
Referenced by Debug(), GetName(), and StatDebugObject().
m_Type
eRemoteDebugType StatDebugObject::m_Type private
Definition at line 5 of file statdebugobject.c.
Referenced by GetType(), SetType(), and StatDebugObject().
m_Value
float StatDebugObject::m_Value private
Definition at line 4 of file statdebugobject.c.
Referenced by Debug(), GetValue(), and StatDebugObject().