DayzKode: PlayerBase Class Reference
PlayerBase Class Reference
Private Member Functions
override void OnGameplayDataHandlerSync ()
Static Private Member Functions
static void CreatePersonalLight ()
Creates PL if it doesn't exist already.
static void SwitchPersonalLight (bool state)
Controls the ON/OFF switch of the Personal Light. PL will still shine only if the server allows it.
static void UpdateHitDirectionValues ()
static void UpdatePersonalLight ()
Updates state of PL.
Static Private Attributes
static ScriptedLightBase m_PersonalLight
static bool m_PersonalLightDisabledByDebug = false
static bool m_PersonalLightEnabledOnCurrentServer = false
static bool m_PersonalLightIsSwitchedOn = true
Detailed Description
Definition at line 1 of file playerbaseclient.c.
Member Function Documentation
CreatePersonalLight()
static void PlayerBase::CreatePersonalLight () inline static private
Creates PL if it doesn't exist already.
Definition at line 9 of file playerbaseclient.c.
    {
        if (!m_PersonalLight  &&  ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ))
        {
            m_PersonalLight = ScriptedLightBase.CreateLight(PersonalLight, "0 0 0");
        }
    }
References GetGame().
OnGameplayDataHandlerSync()
override void PlayerBase::OnGameplayDataHandlerSync () inline private
Definition at line 39 of file playerbaseclient.c.
    {
        super.OnGameplayDataHandlerSync();
        m_PersonalLightEnabledOnCurrentServer = !CfgGameplayHandler.GetDisablePersonalLight();
        UpdatePersonalLight();
        UpdateHitDirectionValues();
    }
References CfgGameplayHandler::GetDisablePersonalLight().
Referenced by ManBase::OnSelectPlayer().
SwitchPersonalLight()
static void PlayerBase::SwitchPersonalLight (bool state) inline static private
Controls the ON/OFF switch of the Personal Light. PL will still shine only if the server allows it.
Definition at line 49 of file playerbaseclient.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() )
        {
            m_PersonalLightIsSwitchedOn = state;
            UpdatePersonalLight();
        }
    }
References GetGame().
UpdateHitDirectionValues()
static void PlayerBase::UpdateHitDirectionValues () inline static private
Definition at line 75 of file playerbaseclient.c.
    {
        HitDirectionEffectBase.CheckValues();
    }
References HitDirectionEffectBase::CheckValues().
UpdatePersonalLight()
static void PlayerBase::UpdatePersonalLight () inline static private
Updates state of PL.
Definition at line 59 of file playerbaseclient.c.
    {
        string param;
        CreatePersonalLight();
        if ( ! GetCLIParam("disablePersonalLight", param)  &&  !m_PersonalLightDisabledByDebug  &&  m_PersonalLightIsSwitchedOn ) // Allow PL unless it's disabled by debug or client-side starting parameter
        {
            m_PersonalLight.SetEnabled(m_PersonalLightEnabledOnCurrentServer);
        }
        else
        {
            m_PersonalLight.SetEnabled(false);
        }
    }
References GetCLIParam().
Member Data Documentation
m_PersonalLight
ScriptedLightBase PlayerBase::m_PersonalLight static private
Definition at line 3 of file playerbaseclient.c.
m_PersonalLightDisabledByDebug
bool PlayerBase::m_PersonalLightDisabledByDebug = false static private
Definition at line 5 of file playerbaseclient.c.
m_PersonalLightEnabledOnCurrentServer
bool PlayerBase::m_PersonalLightEnabledOnCurrentServer = false static private
Definition at line 4 of file playerbaseclient.c.
m_PersonalLightIsSwitchedOn
bool PlayerBase::m_PersonalLightIsSwitchedOn = true static private
Definition at line 6 of file playerbaseclient.c.