DayzKode: UAInput Class Reference
UAInput Class Reference
Private Member Functions
proto native void AddAlternative ()
proto native int AlternativeCount ()
proto native int AlternativeIndex ()
proto native bool Backlit_Enabled ()
proto native void Backlit_Override (int eType, int iColor)
proto native void BindCombo (string sButtonName)
proto native void BindComboByHash (int iHash)
proto native int Binding (int iIndex)
proto native int BindingCount ()
proto native int BindKeyCount ()
proto native bool CheckBindDevice (int iIndex, int iDeviceFlags)
proto native void ClearAlternative (int iIndex)
proto native void ClearBinding ()
proto native void ClearDeviceBind (int iDeviceFlags)
proto native int ConflictCount ()
proto native void ForceDisable (bool bEnable)
proto native void ForceEnable (bool bEnable)
proto native int GetBindDevice (int iIndex)
proto native int GetBindKey (int iIndex)
proto native UAIDWrapper GetPersistentWrapper ()
proto native bool HasSorting (int iIndex)
proto native int ID ()
proto native bool IsClickLimit ()
proto native bool IsCombo ()
proto native bool IsDoubleClickLimit ()
proto native bool IsHoldBeginLimit ()
proto native bool IsHoldLimit ()
proto native bool IsLimitConditionActive ()
proto native bool IsLimited ()
proto native bool IsLocked ()
proto native bool IsPressLimit ()
proto native bool IsReleaseLimit ()
proto native bool LocalClick ()
proto native bool LocalDoubleClick ()
proto native bool LocalHold ()
proto native bool LocalHoldBegin ()
proto native bool LocalPress ()
proto native bool LocalRelease ()
proto native float LocalValue ()
proto native void Lock ()
proto native int NameHash ()
proto native void SelectAlternative (int iIndex)
proto native void Supress ()
private void UAInput ()
proto native void Unlock ()
private void ~UAInput ()
Detailed Description
Definition at line 23 of file uainput.c.
Constructor & Destructor Documentation
UAInput()
private void UAInput::UAInput () private
~UAInput()
private void UAInput::~UAInput () private
Member Function Documentation
AddAlternative()
proto native void UAInput::AddAlternative () private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
AlternativeCount()
proto native int UAInput::AlternativeCount () private
Referenced by array::Apply(), ScriptedWidgetEventHandler::Apply(), InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetElementTitle().
AlternativeIndex()
proto native int UAInput::AlternativeIndex () private
Backlit_Enabled()
proto native bool UAInput::Backlit_Enabled () private
Backlit_Override()
proto native void UAInput::Backlit_Override (int eType, int iColor) private
Referenced by Backlit::HintShow().
BindCombo()
proto native void UAInput::BindCombo (string sButtonName) private
BindComboByHash()
proto native void UAInput::BindComboByHash (int iHash) private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
Binding()
proto native int UAInput::Binding (int iIndex) private
Referenced by InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetElementTitle().
BindingCount()
proto native int UAInput::BindingCount () private
Referenced by InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetElementTitle().
BindKeyCount()
proto native int UAInput::BindKeyCount () private
Referenced by ScriptedWidgetEventHandler::SetInteractActionIcon().
CheckBindDevice()
proto native bool UAInput::CheckBindDevice (int iIndex, int iDeviceFlags) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetElementTitle().
ClearAlternative()
proto native void UAInput::ClearAlternative (int iIndex) private
ClearBinding()
proto native void UAInput::ClearBinding () private
ClearDeviceBind()
proto native void UAInput::ClearDeviceBind (int iDeviceFlags) private
Referenced by array::Apply(), and ScriptedWidgetEventHandler::Apply().
ConflictCount()
proto native int UAInput::ConflictCount () private
ForceDisable()
proto native void UAInput::ForceDisable (bool bEnable) private
ForceEnable()
proto native void UAInput::ForceEnable (bool bEnable) private
Referenced by MissionBase::AddActiveInputRestriction(), and MissionBase::RemoveActiveInputRestriction().
GetBindDevice()
proto native int UAInput::GetBindDevice (int iIndex) private
GetBindKey()
proto native int UAInput::GetBindKey (int iIndex) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
GetPersistentWrapper()
proto native UAIDWrapper UAInput::GetPersistentWrapper () private
Referenced by ActionInput::SetInput().
HasSorting()
proto native bool UAInput::HasSorting (int iIndex) private
Referenced by InputUtils::InitInputMetadata().
ID()
proto native int UAInput::ID () private
Referenced by ConstructData().
IsClickLimit()
proto native bool UAInput::IsClickLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsCombo()
proto native bool UAInput::IsCombo () private
Referenced by InputUtils::GetComboButtonNamesFromInput(), and ScriptedWidgetEventHandler::SetElementTitle().
IsDoubleClickLimit()
proto native bool UAInput::IsDoubleClickLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsHoldBeginLimit()
proto native bool UAInput::IsHoldBeginLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsHoldLimit()
proto native bool UAInput::IsHoldLimit () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsLimitConditionActive()
proto native bool UAInput::IsLimitConditionActive () private
IsLimited()
proto native bool UAInput::IsLimited () private
Referenced by GetStringVariant(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsLocked()
proto native bool UAInput::IsLocked () private
IsPressLimit()
proto native bool UAInput::IsPressLimit () private
Referenced by ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
IsReleaseLimit()
proto native bool UAInput::IsReleaseLimit () private
Referenced by ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::SetElementModifier().
LocalClick()
proto native bool UAInput::LocalClick () private
Referenced by ActionInput::Update().
LocalDoubleClick()
proto native bool UAInput::LocalDoubleClick () private
Referenced by ActionInput::Update().
LocalHold()
proto native bool UAInput::LocalHold () private
Referenced by ActionInput::Update().
LocalHoldBegin()
proto native bool UAInput::LocalHoldBegin () private
Referenced by ActionInput::Update().
LocalPress()
proto native bool UAInput::LocalPress () private
Referenced by HandleOptic(), InterruptGestureCheck(), and InventoryMovementButtonTickHandler().
LocalRelease()
proto native bool UAInput::LocalRelease () private
LocalValue()
proto native float UAInput::LocalValue () private
Referenced by InventoryMovementButtonTickHandler().
Lock()
proto native void UAInput::Lock () private
Referenced by OnSprintStart(), and MissionBase::OnUpdate().
NameHash()
proto native int UAInput::NameHash () private
SelectAlternative()
proto native void UAInput::SelectAlternative (int iIndex) private
Referenced by InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
Supress()
proto native void UAInput::Supress () private
Referenced by UIScriptedMenu::OnChange().
Unlock()
proto native void UAInput::Unlock () private
Referenced by OnSprintEnd(), and MissionBase::OnUpdate().