DayzKode: ActionCarHornBase Class Reference
ActionCarHornBase Class Reference
Static Private Member Functions
static bool ActionCondition (PlayerBase player)
static protected bool BatteryIsVital (ItemBase battery)
static protected bool PlayerIsDriver (Transport trans, PlayerBase player)
static void SetCarHornState (CarHornActionData pActionData, int pState)
Detailed Description
Definition at line 1 of file actioncarhorn.c.
Member Function Documentation
ActionCondition()
static bool ActionCarHornBase::ActionCondition (PlayerBase player) inline static private
Definition at line 3 of file actioncarhorn.c.
    {
        HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
        if (vehCommand)
        {
            Transport trans = vehCommand.GetTransport();
            if (trans)
            {
                if (!PlayerIsDriver(trans, player))
                {
                    return false;
                }
                CarScript car;
                if (Class.CastTo(car, trans))
                {
                    return BatteryIsVital(car.GetBattery());
                }
            }
        }
        return false;
    }
References BatteryIsVital(), Class::CastTo(), HumanCommandVehicle::GetTransport(), and PlayerIsDriver().
Referenced by ActionCondition(), and ActionCarHornLong::ActionCondition().
BatteryIsVital()
static protected bool ActionCarHornBase::BatteryIsVital (ItemBase battery) inline static private
Definition at line 44 of file actioncarhorn.c.
    {
        return battery && battery.GetHealthLevel("Health") <= GameConstants.STATE_DAMAGED;
    }
References GameConstants::STATE_DAMAGED.
Referenced by ActionCondition().
PlayerIsDriver()
static protected bool ActionCarHornBase::PlayerIsDriver (Transport trans, PlayerBase player) inline static private
Definition at line 39 of file actioncarhorn.c.
    {
        return trans.GetSeatAnimationType(trans.CrewMemberIndex(player)) == DayZPlayerConstants.VEHICLESEAT_DRIVER;
    }
Referenced by ActionCondition().
SetCarHornState()
static void ActionCarHornBase::SetCarHornState (CarHornActionData pActionData, int pState) inline static private
Definition at line 28 of file actioncarhorn.c.
    {
        if (!pActionData.m_Player)
            return;
        if (!pActionData.m_Car)
            return;
        pActionData.m_Car.SetCarHornState(pState);
    }
References CarHornActionData::m_Car, and ActionData::m_Player.
Referenced by OnEndInput(), ActionCarHornLong::OnEndInput(), OnEndServer(), ActionCarHornLong::OnEndServer(), OnStartServer(), and ActionCarHornLong::OnStartServer().