DayzKode: SelectionTranslation Class Reference
SelectionTranslation Class Reference
Private Member Functions
bool GetSelectionState ()
ref array< int > GetTranslatedSelections ()
void InitTranslatedSelections (int idx)
bool SearchAndTranslate (string path, int idx)
void SelectionTranslation (Head_Default head, int idx)
void SetSelectionState (bool state)
Private Attributes
string m_BasePath
Head_Default m_Head
bool m_SelectionState
ref array< int > m_TranslatedSelections
bool m_TranslationFinished = false
Detailed Description
Definition at line 67 of file head.c.
Constructor & Destructor Documentation
SelectionTranslation()
void SelectionTranslation::SelectionTranslation (Head_Default head, int idx) inline private
Definition at line 76 of file head.c.
    {
        m_Head = head;
        m_BasePath = "cfgVehicles " + m_Head.GetType() + " HairHiding";
        InitTranslatedSelections(idx);
    }
References InitTranslatedSelections(), m_BasePath, and m_Head.
Member Function Documentation
GetSelectionState()
bool SelectionTranslation::GetSelectionState () inline private
Definition at line 148 of file head.c.
    {
        return m_SelectionState;
    }
References m_SelectionState.
Referenced by ManBase::UpdateHairSelectionVisibility().
GetTranslatedSelections()
ref array< int > SelectionTranslation::GetTranslatedSelections () inline private
Definition at line 153 of file head.c.
    {
        return m_TranslatedSelections;
    }
References m_TranslatedSelections.
Referenced by ManBase::UpdateTranslatedSelections().
InitTranslatedSelections()
void SelectionTranslation::InitTranslatedSelections (int idx) inline private
Definition at line 83 of file head.c.
    {
        if ( !m_Head.ConfigIsExisting("HairHiding") )
            return;
        string path;
        int selectionIdx = -1;
        m_TranslatedSelections = new ref array<int>;
        //Hair
        path = m_BasePath + " Group_Hair";
        SearchAndTranslate(path,idx);
        //Beard
        path = m_BasePath + " Group_Beard";
        SearchAndTranslate(path,idx);
        //Hair + Beard
        path = m_BasePath + " Group_HairBeard";
        SearchAndTranslate(path,idx);
        //other
        for (int i = 0; !m_TranslationFinished; i++)
        {
            path = m_BasePath + " Group_" + i;
            if ( g_Game.ConfigIsExisting(path) )
            {
                SearchAndTranslate(path,idx);
            }
            else
            {
                m_TranslationFinished = true;
            }
        }
    }
References g_Game, m_BasePath, m_Head, m_TranslatedSelections, m_TranslationFinished, path, and SearchAndTranslate().
Referenced by SelectionTranslation().
SearchAndTranslate()
bool SelectionTranslation::SearchAndTranslate (string path, int idx) inline private
Definition at line 117 of file head.c.
    {
        if (!g_Game.ConfigIsExisting(path))
            return false;
        array<string> tempArrayStr = new array<string>;
        g_Game.ConfigGetTextArray(path + " memberSelections", tempArrayStr);
        int indexInOriginalArray = -2;
        for (int i = 0; i < tempArrayStr.Count(); i++)
        {
            indexInOriginalArray = m_Head.m_HeadHairSelectionArray.Find(tempArrayStr.Get(i));
            if ( idx == indexInOriginalArray ) //found it
            {
                g_Game.ConfigGetTextArray(path + " simpleSelectionName", tempArrayStr);
                for (i = 0; i < tempArrayStr.Count(); i++)
                {
                    m_TranslatedSelections.Insert(m_Head.m_HeadHairSelectionArray.Find(tempArrayStr.Get(i)));
                }
                m_TranslationFinished = true;
                return true;
            }
        }
        return false;
    }
References g_Game, m_Head, m_TranslatedSelections, m_TranslationFinished, and path.
Referenced by InitTranslatedSelections().
SetSelectionState()
void SelectionTranslation::SetSelectionState (bool state) inline private
Definition at line 143 of file head.c.
    {
        m_SelectionState = state;
    }
References m_SelectionState.
Referenced by Head::InitSelectionTranslation(), and ManBase::SetHairLevelToHide().
Member Data Documentation
m_BasePath
string SelectionTranslation::m_BasePath private
Definition at line 72 of file head.c.
Referenced by InitTranslatedSelections(), and SelectionTranslation().
m_Head
Head_Default SelectionTranslation::m_Head private
Definition at line 74 of file head.c.
Referenced by InitTranslatedSelections(), SearchAndTranslate(), and SelectionTranslation().
m_SelectionState
bool SelectionTranslation::m_SelectionState private
Definition at line 69 of file head.c.
Referenced by GetSelectionState(), and SetSelectionState().
m_TranslatedSelections
ref array<int> SelectionTranslation::m_TranslatedSelections private
Definition at line 73 of file head.c.
Referenced by GetTranslatedSelections(), InitTranslatedSelections(), and SearchAndTranslate().
m_TranslationFinished
bool SelectionTranslation::m_TranslationFinished = false private
Definition at line 71 of file head.c.
Referenced by InitTranslatedSelections(), and SearchAndTranslate().