DayzKode: StaminaSoundHandlerBase Class Reference
StaminaSoundHandlerBase Class Reference
Private Member Functions
void PostponeStamina (float time)
override void Update ()
Private Attributes
ref Timer m_ClientCharacterDistanceCheck = new Timer
ref Timer m_ClientCharacterTick = new Timer
float m_LastTick
float m_PostponeTime = -1
bool m_StaminaUpEndPlayed = true
bool m_UpdateTimerRunning
Detailed Description
Definition at line 178 of file staminasoundhandler.c.
Member Function Documentation
PostponeStamina()
void StaminaSoundHandlerBase::PostponeStamina (float time) inline private
Definition at line 189 of file staminasoundhandler.c.
    {
        m_PostponeTime = GetGame().GetTime() + time;
    }
References GetGame(), and CGame::GetTime().
Update()
override void StaminaSoundHandlerBase::Update () inline private
Definition at line 195 of file staminasoundhandler.c.
    {
        if( GetGame().GetTime() < m_PostponeTime || m_Player.GetPlayerSoundEventHandler().m_CurrentState )
        {
            return;
        }
        //Print(Math.RandomFloat01());
        eStaminaState stamina_state = m_Player.GetStaminaState();
        switch(stamina_state)
        {
            case eStaminaState.ZONE1_DOWN:
                if(m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_DOWN_LIGHT))
                {
                    m_StaminaUpEndPlayed = false;
                }
            break;
            case eStaminaState.ZONE1_UP:
                if(m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_UP_LIGHT))
                {
                    m_StaminaUpEndPlayed = false;
                }
            break;
            case eStaminaState.ZONE2_DOWN:
                if(m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_DOWN_HEAVY))
                {
                    m_StaminaUpEndPlayed = false;
                }
            break;
            case eStaminaState.ZONE2_UP:
                if(m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_UP_HEAVY))
                {
                    m_StaminaUpEndPlayed = false;
                }
            break;
            case eStaminaState.ZONE0_UP:
                if(!m_StaminaUpEndPlayed && m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_UP_END))
                {
                    m_StaminaUpEndPlayed = true;
                }
                else
                {
                    m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_NORMAL_DUMMY);
                }
            break;
            case eStaminaState.ZONE0_DOWN:
                m_Player.PlaySoundEvent(EPlayerSoundEventID.STAMINA_NORMAL_DUMMY);
            break;
        }
    }
References GetGame(), GetTime(), and m_Player.
Member Data Documentation
m_ClientCharacterDistanceCheck
ref Timer StaminaSoundHandlerBase::m_ClientCharacterDistanceCheck = new Timer private
Definition at line 186 of file staminasoundhandler.c.
m_ClientCharacterTick
ref Timer StaminaSoundHandlerBase::m_ClientCharacterTick = new Timer private
Definition at line 185 of file staminasoundhandler.c.
m_LastTick
float StaminaSoundHandlerBase::m_LastTick private
Definition at line 182 of file staminasoundhandler.c.
m_PostponeTime
float StaminaSoundHandlerBase::m_PostponeTime = -1 private
Definition at line 180 of file staminasoundhandler.c.
m_StaminaUpEndPlayed
bool StaminaSoundHandlerBase::m_StaminaUpEndPlayed = true private
Definition at line 184 of file staminasoundhandler.c.
m_UpdateTimerRunning
bool StaminaSoundHandlerBase::m_UpdateTimerRunning private
Definition at line 183 of file staminasoundhandler.c.