DayzKode: ComponentsBank Class Reference
ComponentsBank Class Reference
Private Member Functions
void ComponentsBank (EntityAI entity_parent)
private Component CreateComponent (int comp_type, string extended_class_name="")
bool DeleteComponent (int comp_type)
Component GetComponent (int comp_type, string extended_class_name="")
bool IsComponentAlreadyExist (int comp_type)
Private Attributes
private ref Component m_Components [COMP_TYPE_COUNT]
private EntityAI m_EntityParent
Detailed Description
Definition at line 1 of file componentsbank.c.
Constructor & Destructor Documentation
ComponentsBank()
void ComponentsBank::ComponentsBank (EntityAI entity_parent) inline private
Definition at line 6 of file componentsbank.c.
    {
        m_EntityParent = entity_parent;
    }
References m_EntityParent.
Member Function Documentation
CreateComponent()
private Component ComponentsBank::CreateComponent (int comp_type, string extended_class_name = "") inline private
Definition at line 38 of file componentsbank.c.
    {
        if ( !Component.IsTypeExist(comp_type) )
        {
            Component.LogErrorBadCompType(comp_type, "EntityAI->CreateComponent(int comp_type)");
            return NULL;
        }
        if ( IsComponentAlreadyExist(comp_type) )
        {
            Component.LogWarningAlredyExist(comp_type, "EntityAI->CreateComponent(int comp_type)");
            return m_Components[comp_type];
        }
        string clas_name = extended_class_name;
        if ( clas_name == string.Empty )
        {
            clas_name = Component.GetNameByType(comp_type);
        }
        Component comp = Component.Cast(clas_name.ToType().Spawn());
        comp.SetParentEntityAI(m_EntityParent);
        comp.Event_OnAwake();
        m_Components[comp_type] = comp;
        comp.Event_OnInit();
        return comp;
    }
References Empty, Component::Event_OnAwake(), Component::Event_OnInit(), Component::GetNameByType(), IsComponentAlreadyExist(), Component::IsTypeExist(), Component::LogErrorBadCompType(), Component::LogWarningAlredyExist(), m_Components, m_EntityParent, Component::SetParentEntityAI(), and string::ToType().
Referenced by GetComponent().
DeleteComponent()
bool ComponentsBank::DeleteComponent (int comp_type) inline private
Definition at line 27 of file componentsbank.c.
    {
        if ( IsComponentAlreadyExist(comp_type) )
        {
            m_Components[comp_type] = NULL;
            return true;
        }
        return false;
    }
References IsComponentAlreadyExist(), and m_Components.
GetComponent()
Component ComponentsBank::GetComponent (int comp_type, string extended_class_name = "") inline private
Definition at line 11 of file componentsbank.c.
    {
        if ( !Component.IsTypeExist(comp_type) )
        {
            Component.LogErrorBadCompType(comp_type, "EntityAI.GetComponent(int comp_type)");
            return NULL;
        }
        if ( !IsComponentAlreadyExist(comp_type) )
        {
            CreateComponent(comp_type, extended_class_name);
        }
        return m_Components[comp_type];
    }
References CreateComponent(), IsComponentAlreadyExist(), Component::IsTypeExist(), Component::LogErrorBadCompType(), and m_Components.
IsComponentAlreadyExist()
bool ComponentsBank::IsComponentAlreadyExist (int comp_type) inline private
Definition at line 72 of file componentsbank.c.
    {
        if ( m_Components[comp_type] != NULL )
        {
            return true;
        }
        return false;
    }
References m_Components.
Referenced by CreateComponent(), DeleteComponent(), and GetComponent().
Member Data Documentation
m_Components
private ref Component ComponentsBank::m_Components[COMP_TYPE_COUNT] private
Definition at line 4 of file componentsbank.c.
Referenced by CreateComponent(), DeleteComponent(), GetComponent(), and IsComponentAlreadyExist().
m_EntityParent
private EntityAI ComponentsBank::m_EntityParent private
Definition at line 3 of file componentsbank.c.
Referenced by ComponentsBank(), and CreateComponent().