DayzKode: ToxicityMdfr Class Reference
ToxicityMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
private const float TOXICITY_CLEANUP_PER_SEC = 1
private const float VOMIT_THRESHOLD = 70
Detailed Description
Definition at line 1 of file toxicity.c.
Member Function Documentation
ActivateCondition()
override bool ToxicityMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file toxicity.c.
    {
        return true;
    }
DeactivateCondition()
override bool ToxicityMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 20 of file toxicity.c.
    {
        return false;
    }
Init()
override void ToxicityMdfr::Init () inline private
Definition at line 6 of file toxicity.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_TOXICITY;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void ToxicityMdfr::OnActivate (PlayerBase player) inline private
Definition at line 44 of file toxicity.c.
    {
    }
OnReconnect()
override void ToxicityMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 39 of file toxicity.c.
    {
    }
OnTick()
override void ToxicityMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 25 of file toxicity.c.
    {
        player.GetStatToxicity().Add( -TOXICITY_CLEANUP_PER_SEC * deltaT );
        if( player.GetStatToxicity().Get() > VOMIT_THRESHOLD )
        {
            SymptomBase symptom = player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_VOMIT);
            if( symptom )
            {
                symptom.SetDuration(Math.RandomIntInclusive(4,8));
            }
        }
    }
References Math::RandomIntInclusive(), SymptomBase::SetDuration(), TOXICITY_CLEANUP_PER_SEC, and VOMIT_THRESHOLD.
Member Data Documentation
TOXICITY_CLEANUP_PER_SEC
private const float ToxicityMdfr::TOXICITY_CLEANUP_PER_SEC = 1 private
Definition at line 3 of file toxicity.c.
Referenced by OnTick().
VOMIT_THRESHOLD
private const float ToxicityMdfr::VOMIT_THRESHOLD = 70 private
Definition at line 4 of file toxicity.c.
Referenced by OnTick().