DayzKode: ActionPackGift Class Reference
ActionPackGift Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPackGift ()
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionpackgift.c.
Constructor & Destructor Documentation
ActionPackGift()
void ActionPackGift::ActionPackGift () inline private
Definition at line 11 of file actionpackgift.c.
    {
        m_CallbackClass = ActionPackGiftCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM;
        //m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#STR_Wrap";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionPackGift::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionpackgift.c.
    {
        ItemBase item_to_pack = ItemBase.Cast(target.GetObject());
        if (!item_to_pack)
            return false;
        if ( !item_to_pack.IsTakeable() ) return false;
        if ( item_to_pack.IsBeingPlaced() ) return false;
        if ( BaseBuildingBase.Cast(item_to_pack) ) return false;
        if ( !item_to_pack.CanPutInCargo(null) ) return false;
        EntityAI tgt_parent = EntityAI.Cast( target.GetParent() );
        if ( tgt_parent )
        {
            if ( item_to_pack.GetInventory().IsAttachment() )
            {
                if ( !item_to_pack.CanDetachAttachment(tgt_parent) || !tgt_parent.CanReleaseAttachment(item_to_pack) )
                    return false;
            }
            else
            {
                if ( !item_to_pack.CanRemoveFromCargo(tgt_parent) || !tgt_parent.CanReleaseCargo(item_to_pack) )
                    return false;
            }
        }
        if ( item_to_pack.GetInventory().GetCargo() && item_to_pack.GetInventory().GetCargo().GetItemCount() > 0)
            return false;
        if ( !item_to_pack.IsWeapon() && item_to_pack.GetInventory().AttachmentCount() > 0)
            return false;
        int x,y;
        GetGame().GetInventoryItemSize( item_to_pack, x, y );
        if( x > 5 || y > 5 )
            return false;
        return true;
    }
References ItemBase::CanDetachAttachment(), ItemBase::CanPutInCargo(), ItemBase::CanRemoveFromCargo(), GetGame(), CGame::GetInventoryItemSize(), ItemBase::IsTakeable(), x, and y.
CreateConditionComponents()
override void ActionPackGift::CreateConditionComponents () inline private
Definition at line 21 of file actionpackgift.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionPackGift::HasTarget () inline private
Definition at line 27 of file actionpackgift.c.
    {
        return true;
    }
OnFinishProgressClient()
override void ActionPackGift::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 77 of file actionpackgift.c.
    {
        PlayerBase player = action_data.m_Player;
        ItemBase item_to_pack = ItemBase.Cast(action_data.m_Target.GetObject());
        player.RemoveQuickBarEntityShortcut(item_to_pack);
    }
References ActionData::m_Player, and ActionData::m_Target.
OnFinishProgressServer()
override void ActionPackGift::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 86 of file actionpackgift.c.
    {
        ItemBase item_to_pack = ItemBase.Cast(action_data.m_Target.GetObject());
        ItemBase item = action_data.m_MainItem;
        PlayerBase player = action_data.m_Player;
        string typeName;
        if (item_to_pack)
        {
            int x,y;
            GetGame().GetInventoryItemSize( item_to_pack, x, y );
            int rnd = Math.RandomIntInclusive(1, 4);
            ReplaceWithNewReciveCargoLambda lambda;
            if( x <= 2 && y <= 2 )
            {
                typeName = "GiftBox_Small_" + rnd;
            }
            else if( x <= 3 && y <= 3 )
            {
                typeName = "GiftBox_Medium_" + rnd;
            }
            else if( x <= 5 && y <= 5 )
            {
                typeName = "GiftBox_Large_" + rnd;
            }
            else return;
            if(!GetGame().IsDedicatedServer())
                player.RemoveQuickBarEntityShortcut(item_to_pack);
            lambda = new ReplaceWithNewReciveCargoLambda( item, typeName, player,item_to_pack);
            player.ServerReplaceItemWithNew(lambda);
        }
    }
References GetGame(), CGame::GetInventoryItemSize(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, Math::RandomIntInclusive(), x, and y.