DayzKode: Container Class Reference
Container Class Reference
Private Member Functions
void AddedToCargo (EntityAI item)
void AddedToCargoEx (EntityAI item, bool refresh=true)
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool CanEquip ()
void CargoContainer (LayoutHolder parent, bool is_attachment=false)
override void CheckHeaderDragability ()
void ClosableContainer (LayoutHolder parent, int sort=-1)
override void Close ()
void CloseButtonOnMouseButtonDown ()
override bool Combine ()
override bool EquipItem ()
override LayoutHolder Get (int x)
int GetCargoCapacity ()
int GetCargoIndex ()
EntityAI GetEntity ()
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerHeight (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
override float GetFocusedContainerYScreenPos (bool contents=false)
Icon GetFocusedIcon ()
override EntityAI GetFocusedItem ()
override Header GetHeader ()
Icon GetIcon (EntityAI item)
Icon GetIcon (int index)
float GetIconSize ()
int GetMaxCargoCapacity ()
int GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player)
float GetSpaceSize ()
bool HasItem (EntityAI item)
void InitGridHeight ()
Icon InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y)
Icon InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh=true)
override bool IsDisplayable ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
void MoveContainerDown (Widget cont)
void MoveContainerUp (Widget cont)
void MovedInCargo (EntityAI item)
override void OnShow ()
override void Open ()
override void Refresh ()
override void Refresh ()
void RefreshImpl ()
void ReleaseLock (EntityAI item)
void RemovedFromCargo (EntityAI item)
override bool Select ()
override bool SelectItem ()
override void SetActive (bool active)
void SetAlternateFalseTextHeaderWidget (TextWidget w)
override void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetEntity (EntityAI item, int cargo_index=0, bool immedUpdate=true)
override void SetLastActive ()
override void SetLastFocus ()
override void SetLayoutName ()
override void SetLayoutName ()
void SetLock (EntityAI item)
override void SetNextActive ()
override void SetNextLeftActive ()
override void SetNextRightActive ()
void SetOpenState (bool state)
override void SetPreviousActive (bool force=false)
void ShowFalseCargoHeader (bool show)
override bool SplitItem ()
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void Unfocus ()
override void UnfocusAll ()
void UpdateHeaderText ()
override void UpdateInterval ()
override void UpdateRadialIcon ()
void UpdateRowVisibility (int count)
void UpdateSelection ()
void UpdateSize ()
void ~CargoContainer ()
Private Attributes
protected TextWidget m_AlternateFalseHeaderTextWidget
protected CargoBase m_Cargo
protected Widget m_CargoContainer
protected Widget m_CargoHeader
protected int m_CargoIndex = -1
protected ref ClosableHeader m_ClosableHeader
protected TextWidget m_FalseHeaderTextWidget
protected int m_FocusedItemPosition = -1
protected ref array< ref Icon > m_Icons
protected float m_IconSize
protected bool m_IsAttachment
protected Widget m_ItemsContainer
protected bool m_LockCargo
protected ref SizeToChild m_Resizer1
protected ref SizeToChild m_Resizer2
protected ref Timer m_ResizeTimer
protected ref array< ref CargoContainerRow > m_Rows
protected ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedItemPositions
protected ref map< EntityAI, ref Param3< ref Icon, int, int > > m_ShowedLockPositions
protected float m_SpaceSize
protected const int ROWS_NUMBER_XBOX = 5
Detailed Description
Definition at line 2 of file cargocontainer.c.
Constructor & Destructor Documentation
~CargoContainer()
void Container::~CargoContainer () inline private
Definition at line 50 of file cargocontainer.c.
    {
        if ( m_Entity )
        {
            m_Entity.GetOnItemAddedIntoCargo().Remove( AddedToCargo );
            m_Entity.GetOnItemRemovedFromCargo().Remove( RemovedFromCargo );
            m_Entity.GetOnItemMovedInCargo().Remove( MovedInCargo );
            m_Entity.GetOnSetLock().Remove( SetLock );
            m_Entity.GetOnReleaseLock().Remove( ReleaseLock );
        }
    }
References m_Entity, ScriptedWidgetEventHandler::Remove(), and SetLock().
Member Function Documentation
AddedToCargo()
void Container::AddedToCargo (EntityAI item) inline private
Definition at line 108 of file cargocontainer.c.
    {
        AddedToCargoEx( item );
    }
References AddedToCargoEx().
AddedToCargoEx()
void Container::AddedToCargoEx (EntityAI item, bool refresh = true) inline private
Definition at line 64 of file cargocontainer.c.
    {
        InventoryLocation il = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation( il );
        int x = il.GetCol();
        int y = il.GetRow();
        if ( m_ShowedItemPositions.Contains( item ) )
        {
            Param3<ref Icon, int, int> item_pos = m_ShowedItemPositions.Get( item );
            InitIconEx( item_pos.param1, item, x, y, refresh );
            item_pos.param2 = x;
            item_pos.param3 = y;
        }
        else
        {
            ref Icon icon = new Icon( this, false );
            m_Icons.Insert( icon );
            InitIconEx( icon, item, x, y, refresh );
            m_ShowedItemPositions.Insert( item, new Param3<ref Icon, int, int>( icon, x, y ) );
        }
        if (refresh)
            UpdateHeaderText();
        #ifdef PLATFORM_CONSOLE
        for ( int i = 0; i < m_Cargo.GetItemCount(); i++ )
        {
            EntityAI item2 = m_Cargo.GetItem( i );
            Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get( item2 );
            if ( data )
            {
                data.param1.SetCargoPos( i );
                data.param1.SetPos();
            }
        }
        m_FocusedItemPosition = Math.Min( m_ShowedItemPositions.Count() - 1, m_FocusedItemPosition );
        if (refresh)
            Refresh();
        #endif
    }
References InventoryLocation::GetCol(), CargoBase::GetItem(), CargoBase::GetItemCount(), InventoryLocation::GetRow(), InitIconEx(), Math::Min(), Refresh(), UpdateHeaderText(), x, and y.
Referenced by AddedToCargo(), and SetEntity().
CanCombine()
override bool Container::CanCombine () inline private
Definition at line 781 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            ItemBase entity         = ItemBase.Cast( GetFocusedIcon().GetObject() );
            ItemBase item_in_hands  = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
            return ( ItemManager.GetCombinationFlags( item_in_hands, entity ) != 0 );
        }
        return false;
    }
References ItemManager::GetCombinationFlags(), GetFocusedIcon(), GetGame(), GetObject(), and GetPlayer().
Referenced by UpdateConsoleToolbar(), and UpdateInterval().
CanCombineAmmo()
override bool Container::CanCombineAmmo () inline private
Definition at line 793 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            ActionManagerClient amc = ActionManagerClient.Cast( PlayerBase.Cast( GetGame().GetPlayer() ).GetActionManager() );
            ItemBase entity         = ItemBase.Cast( GetFocusedIcon().GetObject() );
            ItemBase item_in_hands  = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
            return ( amc.CanPerformActionFromInventory( item_in_hands, entity ) || amc.CanSetActionFromInventory( item_in_hands, entity ) );
        }
        return false;
    }
References ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanSetActionFromInventory(), GetActionManager(), GetFocusedIcon(), GetGame(), GetObject(), and GetPlayer().
Referenced by UpdateConsoleToolbar(), and UpdateInterval().
CanEquip()
override bool Container::CanEquip () inline private
Definition at line 767 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            EntityAI entity = EntityAI.Cast( GetFocusedIcon().GetObject() );
            InventoryLocation il = new InventoryLocation;
            if( !entity.IsInherited( Magazine ) )
            {
                return GetGame().GetPlayer().GetInventory().FindFreeLocationFor( entity, FindInventoryLocationType.ATTACHMENT, il );
            }
        }
        return false;
    }
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateConsoleToolbar().
CargoContainer()
void Container::CargoContainer (LayoutHolder parent, bool is_attachment = false) inline private
Definition at line 28 of file cargocontainer.c.
    {
        m_IsAttachment          = is_attachment;
        m_Rows                  = new array<ref CargoContainerRow>;
        m_Icons                 = new array<ref Icon>;
        m_ShowedItemPositions   = new map<EntityAI, ref Param3<ref Icon, int, int>>;
        m_ShowedLockPositions   = new map<EntityAI, ref Param3<ref Icon, int, int>>;
        m_CargoContainer        = m_RootWidget.FindAnyWidget( "grid_background" );
        m_ItemsContainer        = m_RootWidget.FindAnyWidget( "grid_overlay" );
        m_CargoHeader           = m_RootWidget.FindAnyWidget( "grid_container_header_spacer" );
        m_RootWidget.GetScript( m_Resizer1 );
        m_RootWidget.FindAnyWidget( "grid_container" ).GetScript( m_Resizer2 );
        m_CargoHeader.Show( is_attachment );
        m_FalseHeaderTextWidget = TextWidget.Cast(m_CargoHeader.FindAnyWidget( "TextWidget0" ));
        m_MainWidget            = m_CargoContainer;
        m_FocusedItemPosition   = -1;
    }
References m_CargoContainer, and m_RootWidget.
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::AttachmentRemoved(), HandsContainer::DestroyCargo(), HandsContainer::ShowAtt(), and HandsContainer::UnfocusGrid().
CheckHeaderDragability()
override void Container::CheckHeaderDragability () inline private
Definition at line 181 of file closablecontainer.c.
    {
        super.CheckHeaderDragability();
        if (m_ClosableHeader && m_Entity) //TODO: do the entity check here?
        {
            int flag = m_ClosableHeader.GetMainWidget().GetFlags();
            bool old = flag & WidgetFlags.DRAGGABLE;
            bool current = ItemBase.Cast(m_Entity) && m_Entity.IsTakeable();
            //bool changed = false;
            if (old && !current)
            {
                m_ClosableHeader.GetMainWidget().ClearFlags( WidgetFlags.DRAGGABLE );
                Widget drag = GetDragWidget();
                if (drag && drag == m_ClosableHeader.GetMainWidget())
                {
                    CancelWidgetDragging();
                    m_ClosableHeader.OnDropHeader(null);
                }
                //changed = true;
            }
            else if (!old && current)
            {
                m_ClosableHeader.GetMainWidget().SetFlags( WidgetFlags.DRAGGABLE );
                //changed = true;
            }
            /*if (old != current)
            {
                flag &= ~WidgetFlags.DRAGGABLE;
                m_ClosableHeader.GetMainWidget().SetFlags( flag );
            }*/
        }
    }
References CancelWidgetDragging(), GetDragWidget(), ScriptedWidgetEventHandler::GetMainWidget(), and m_Entity.
Referenced by LayoutHolder::UpdateInterval().
ClosableContainer()
void Container::ClosableContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 6 of file closablecontainer.c.
    {
        m_Body              = new array<ref LayoutHolder>;
        m_ClosableHeader    = new ClosableHeader( this, "CloseButtonOnMouseButtonDown" );
        if( sort > -1 )
            m_RootWidget.SetSort( sort + 2 );
        m_MainWidget = m_MainWidget.FindWidget( "body" );
    }
References m_RootWidget.
Close()
override void Container::Close () inline private
Definition at line 79 of file closablecontainer.c.
    {
        ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), false );
        super.Close();
        SetOpenForSlotIcon(false);
        OnHide();
        m_Parent.m_Parent.Refresh(); //TODO: ???
    }
References ItemManager::GetInstance(), m_Entity, m_Parent, OnHide(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), AttachmentCategoriesRow::OnMouseButtonDown(), CollapsibleContainer::Toggle(), and LayoutHolder::Toggle().
CloseButtonOnMouseButtonDown()
void Container::CloseButtonOnMouseButtonDown () inline private
Definition at line 116 of file closablecontainer.c.
    {
        Close();
    }
References ClosableContainer::Close().
Combine()
override bool Container::Combine () inline private
Definition at line 937 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            Icon icon = GetFocusedIcon();
            if( icon )
            {
                EntityAI item_in_hands  = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
                EntityAI prev_item      = EntityAI.Cast( icon.GetObject() );
                if( item_in_hands && prev_item )
                {
                    return icon.CombineItems( item_in_hands, prev_item );
                }
            }
        }
        return false;
    }
References Icon::CombineItems(), GetFocusedIcon(), GetGame(), Icon::GetObject(), and CGame::GetPlayer().
EquipItem()
override bool Container::EquipItem () inline private
Definition at line 843 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            ItemBase entity = ItemBase.Cast( GetFocusedIcon().GetObject() );
            if( entity )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, entity );
                return true;
            }
        }
        return false;
    }
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
Get()
override LayoutHolder Container::Get (int x) inline private
Definition at line 101 of file closablecontainer.c.
    {
        if( m_Body && x < m_Body.Count() && x >= 0 )
            return m_Body.Get( x );
        return null;
    }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
Referenced by ClosableContainer::AttachmentRemoved(), ZombieContainer::GetSlotsIcon(), ZombieContainer::GetWidgetSlot(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), VicinitySlotsContainer::MouseClick(), ClosableContainer::RecomputeContainers(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinitySlotsContainer::~VicinitySlotsContainer().
GetCargoCapacity()
int Container::GetCargoCapacity () inline private
Definition at line 372 of file cargocontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
        #ifndef PLATFORM_WINDOWS
            return CargoList.Cast( m_Cargo ).GetTotalWeight( null );
        #endif
        #endif
        int total_size = 0;
        for ( int i = 0; i < m_Cargo.GetItemCount(); ++i )
        {
            int x, y;
            m_Cargo.GetItemSize( i, x, y );
            total_size += x * y;
        }
        return total_size;
    }
References CargoBase::GetItemCount(), CargoBase::GetItemSize(), x, and y.
Referenced by UpdateHeaderText().
GetCargoIndex()
int Container::GetCargoIndex () inline private
Definition at line 62 of file cargocontainer.c.
{ return m_CargoIndex; }
References m_CargoIndex.
GetEntity()
EntityAI Container::GetEntity () inline private
Definition at line 280 of file cargocontainer.c.
    {
        return m_Entity;
    }
References m_Entity.
GetFocusedContainerHeight() [1/2]
override float Container::GetFocusedContainerHeight (bool contents = false) inline private
Definition at line 427 of file cargocontainer.c.
    {
        float x, y;
        if( contents && GetFocusedIcon() )
            GetFocusedIcon().GetRootWidget().GetScreenSize( x, y );
        else
            GetRootWidget().GetScreenSize( x, y );
        return y;
    }
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), LayoutHolder::ScrollToActiveContainer(), and HandsContainer::ScrollToActiveContainer().
GetFocusedContainerHeight() [2/2]
override float Container::GetFocusedContainerHeight (bool contents = false) inline private
Definition at line 121 of file closablecontainer.c.
    {
        float x, y;
        if( contents && GetFocusedContainer() )
            y = GetFocusedContainer().GetFocusedContainerHeight( contents );
        else if( GetRootWidget() )
            GetRootWidget().GetScreenSize( x, y );
        return y;
    }
References LayoutHolder::GetFocusedContainerHeight(), x, and y.
GetFocusedContainerYPos() [1/2]
override float Container::GetFocusedContainerYPos (bool contents = false) inline private
Definition at line 437 of file cargocontainer.c.
    {
        float x, y;
        if( contents && GetFocusedIcon() )
            GetFocusedIcon().GetRootWidget().GetPos( x, y );
        else
            GetRootWidget().GetPos( x, y );
        return y;
    }
References GetFocusedIcon(), x, and y.
GetFocusedContainerYPos() [2/2]
override float Container::GetFocusedContainerYPos (bool contents = false) inline private
Definition at line 131 of file closablecontainer.c.
    {
        float x, y;
        if( contents && GetFocusedContainer() )
            y = GetFocusedContainer().GetFocusedContainerYPos( contents );
        else if( GetRootWidget() )
            GetRootWidget().GetPos( x, y );
        return y;
    }
References LayoutHolder::GetFocusedContainerYPos(), x, and y.
GetFocusedContainerYScreenPos() [1/2]
override float Container::GetFocusedContainerYScreenPos (bool contents = false) inline private
Definition at line 447 of file cargocontainer.c.
    {
        float x, y;
        if( contents && GetFocusedIcon() )
            GetFocusedIcon().GetRootWidget().GetScreenPos( x, y );
        else
            GetRootWidget().GetScreenPos( x, y );
        return y;
    }
References GetFocusedIcon(), x, and y.
Referenced by LeftArea::GetCurrentContainerBottomY(), RightArea::GetCurrentContainerBottomY(), LeftArea::GetCurrentContainerTopY(), RightArea::GetCurrentContainerTopY(), LayoutHolder::ScrollToActiveContainer(), and HandsContainer::ScrollToActiveContainer().
GetFocusedContainerYScreenPos() [2/2]
override float Container::GetFocusedContainerYScreenPos (bool contents = false) inline private
Definition at line 141 of file closablecontainer.c.
    {
        float x, y;
        if( contents && GetFocusedContainer() )
            y = GetFocusedContainer().GetFocusedContainerYScreenPos( contents );
        else if( GetRootWidget() )
            GetRootWidget().GetScreenPos( x, y );
        return y;
    }
References LayoutHolder::GetFocusedContainerYScreenPos(), x, and y.
GetFocusedIcon()
Icon Container::GetFocusedIcon () inline private
Definition at line 422 of file cargocontainer.c.
    {
        return GetIcon( m_FocusedItemPosition );
    }
References GetIcon().
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), GetFocusedContainerHeight(), GetFocusedContainerYPos(), GetFocusedContainerYScreenPos(), GetFocusedItem(), IsItemActive(), IsItemWithQuantityActive(), SelectItem(), SetLastActive(), SplitItem(), TransferItem(), TransferItemToVicinity(), and Unfocus().
GetFocusedItem()
override EntityAI Container::GetFocusedItem () inline private
Definition at line 708 of file cargocontainer.c.
    {
        Icon icon = GetFocusedIcon();
        if( icon )
        {
            return EntityAI.Cast( icon.GetObject() );
        }
        return null;
    }
References GetFocusedIcon(), and Icon::GetObject().
Referenced by VicinitySlotsContainer::CanCombine(), VicinitySlotsContainer::CanCombineAmmo(), VicinitySlotsContainer::CanEquip(), VicinitySlotsContainer::Combine(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), VicinityContainer::ExpandCollapseContainer(), Attachments::GetFocusedItem(), VicinitySlotsContainer::InspectItem(), VicinitySlotsContainer::IsEmptyItemActive(), ZombieContainer::IsEmptyItemActive(), VicinitySlotsContainer::IsItemActive(), VicinitySlotsContainer::IsItemWithContainerActive(), ZombieContainer::IsItemWithContainerActive(), VicinitySlotsContainer::IsItemWithQuantityActive(), ZombieContainer::IsItemWithQuantityActive(), VicinitySlotsContainer::IsTakeable(), HandsContainer::OnSelectButton(), Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), ZombieContainer::TransferItemToVicinity(), and UpdateInterval().
GetHeader()
override Header Container::GetHeader () inline private
Definition at line 62 of file closablecontainer.c.
    {
        return m_ClosableHeader;
    }
Referenced by LayoutHolder::GetFocusedContainerHeight(), LayoutHolder::GetFocusedContainerYScreenPos(), LayoutHolder::SetActive(), LayoutHolder::SetLastActive(), VicinityContainer::UpdateHeader(), and UpdateHeaderText().
GetIcon() [1/2]
Icon Container::GetIcon (EntityAI item) inline private
Definition at line 399 of file cargocontainer.c.
    {
        if ( item && m_ShowedItemPositions.Contains( item ) )
        {
            Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get( item );
            return data.param1;
        }
        return null;
    }
References LayoutHolder::Get().
GetIcon() [2/2]
Icon Container::GetIcon (int index) inline private
Definition at line 409 of file cargocontainer.c.
    {
        if ( m_Cargo == null )
        {
            Print("Attempted to get icon on cargo container, but cargo was null!");
            return null;
        }
        if ( index >= 0 && m_Cargo.GetItemCount() > index )
            return GetIcon( m_Cargo.GetItem( index ) );
        return null;
    }
References GetIcon(), CargoBase::GetItem(), CargoBase::GetItemCount(), and Print().
GetIconSize()
float Container::GetIconSize () inline private
Definition at line 362 of file cargocontainer.c.
    {
        return m_IconSize;
    }
References m_IconSize.
GetMaxCargoCapacity()
int Container::GetMaxCargoCapacity () inline private
Definition at line 389 of file cargocontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
        #ifndef PLATFORM_WINDOWS
            return CargoList.Cast( m_Cargo ).GetMaxWeight();
        #endif
        #endif
        return m_Cargo.GetWidth() * m_Cargo.GetHeight();
    }
References CargoBase::GetHeight(), and CargoBase::GetWidth().
Referenced by UpdateHeaderText().
GetRecipeCount()
int Container::GetRecipeCount (bool recipe_anywhere, ItemBase entity1, ItemBase entity2, PlayerBase player) inline private
Definition at line 761 of file cargocontainer.c.
    {
        PluginRecipesManager recipes_manager = PluginRecipesManager.Cast( GetPlugin( PluginRecipesManager ) );
        return recipes_manager.GetValidRecipes( entity1, entity2, null, player );
    }
References GetPlugin().
GetSpaceSize()
float Container::GetSpaceSize () inline private
Definition at line 367 of file cargocontainer.c.
    {
        return m_SpaceSize;
    }
References m_SpaceSize.
HasItem()
bool Container::HasItem (EntityAI item) inline private
Definition at line 564 of file cargocontainer.c.
    {
        return m_ShowedItemPositions.Contains( item );
    }
InitGridHeight()
void Container::InitGridHeight () inline private
Definition at line 315 of file cargocontainer.c.
    {
        m_Rows.Clear();
        m_ShowedItemPositions.Clear();
        ref CargoContainerRow row;
        #ifdef PLATFORM_CONSOLE
        int cargo_height =  1;
        #else
        int cargo_height =  m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex).GetHeight();
        #endif
        for ( int j = 0; j < cargo_height; j++ )
        {
            row = new CargoContainerRow( this );
            row.SetNumber( j );
            row.SetEntity( m_Entity );
            #ifdef PLATFORM_WINDOWS
            #ifndef PLATFORM_CONSOLE
            row.SetWidth( m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex).GetWidth(), false );
            #endif
            #endif
            row.GetRootWidget().SetSort( j, false );
            m_Rows.Insert( row );
        }
        float y;
        row.GetRootWidget().FindAnyWidget( "Icon0" ).GetScreenSize( y, m_IconSize );
        #ifdef PLATFORM_WINDOWS
        #ifndef PLATFORM_CONSOLE
            row.GetRootWidget().FindAnyWidget( "Spacer0" ).GetScreenSize( m_SpaceSize, y );
        #endif
        #endif
        m_Resizer2.ResizeParentToChild();
        m_Resizer1.ResizeParentToChild();
    }
References m_Entity, and y.
Referenced by SetEntity().
InitIcon()
Icon Container::InitIcon (Icon icon, EntityAI item, int pos_x, int pos_y) inline private
Definition at line 559 of file cargocontainer.c.
    {
        return InitIconEx( icon, item, pos_x, pos_y );
    }
References InitIconEx().
InitIconEx()
Icon Container::InitIconEx (Icon icon, EntityAI item, int pos_x, int pos_y, bool refresh = true) inline private
Definition at line 532 of file cargocontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
            icon.SetSize( 1, 1 );
            #ifdef PLATFORM_WINDOWS
                pos_y = pos_y * 5 + pos_x;
            #endif
            icon.SetCargoPos( pos_y );
            icon.SetPosY( pos_y );
            icon.SetPosEx( refresh );
        #else
            int size_x, size_y;
            GetGame().GetInventoryItemSize( InventoryItem.Cast( item ), size_x, size_y );
            if ( item.GetInventory().GetFlipCargo() )
                icon.SetSize( size_y, size_x );
            else
                icon.SetSize( size_x, size_y );
            icon.SetPosX( pos_x );
            icon.SetPosY( pos_y );
            icon.SetPosEx( refresh );
        #endif
        icon.InitEx( item, refresh );
        return icon;
    }
References GetGame(), CGame::GetInventoryItemSize(), Icon::InitEx(), Icon::SetCargoPos(), Icon::SetPosEx(), Icon::SetPosX(), Icon::SetPosY(), and Icon::SetSize().
Referenced by AddedToCargoEx(), and InitIcon().
IsDisplayable()
override bool Container::IsDisplayable () inline private
Definition at line 17 of file closablecontainer.c.
    {
        for(int i = 0; i < m_Body.Count(); i++)
        {
            LayoutHolder c = m_Body[i];
            if( c && c.IsDisplayable())
                return true;
        }
        return false;
    }
Referenced by LayoutHolder::RecomputeOpenedContainers(), and VicinitySlotsContainer::ShowItemsInContainers().
IsEmpty()
override bool Container::IsEmpty () inline private
Definition at line 756 of file cargocontainer.c.
    {
        return m_Icons.Count() == 0;
    }
Referenced by AttachmentsWrapper::IsDisplayable(), AttachmentCategoriesContainer::IsDisplayable(), Attachments::IsEmpty(), IsItemWithQuantityActive(), and UpdateConsoleToolbar().
IsItemActive()
override bool Container::IsItemActive () inline private
Definition at line 736 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            ItemBase item = ItemBase.Cast( GetFocusedIcon().GetObject() );
            return ( item != null );
        }
        return false;
    }
References GetFocusedIcon(), and GetObject().
Referenced by UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool Container::IsItemWithQuantityActive () inline private
Definition at line 746 of file cargocontainer.c.
    {
        if( GetFocusedIcon()  )
        {
            ItemBase item = ItemBase.Cast( GetFocusedIcon().GetObject() );
            return ( !IsEmpty() && QuantityConversions.HasItemQuantity( item ) && item.CanBeSplit() );
        }
        return false;
    }
References GetFocusedIcon(), GetObject(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by UpdateConsoleToolbar().
MoveContainerDown()
void Container::MoveContainerDown (Widget cont) inline private
Definition at line 166 of file closablecontainer.c.
    {
        if( m_Entity )
        {
            InventoryLocation loc = new InventoryLocation;
            m_Entity.GetInventory().GetCurrentInventoryLocation( loc );
            if( loc.IsValid() )
            {
                int slot = loc.GetSlot();
                Inventory.MoveAttachmentDown( slot );
                UpdateSelectionIcons();
            }
        }
    }
References InventoryLocation::GetSlot(), Inventory(), InventoryLocation::IsValid(), and m_Entity.
MoveContainerUp()
void Container::MoveContainerUp (Widget cont) inline private
Definition at line 151 of file closablecontainer.c.
    {
        if( m_Entity )
        {
            InventoryLocation loc = new InventoryLocation;
            m_Entity.GetInventory().GetCurrentInventoryLocation( loc );
            if( loc.IsValid() )
            {
                int slot = loc.GetSlot();
                Inventory.MoveAttachmentUp( slot );
                UpdateSelectionIcons();
            }
        }
    }
References InventoryLocation::GetSlot(), Inventory(), InventoryLocation::IsValid(), and m_Entity.
MovedInCargo()
void Container::MovedInCargo (EntityAI item) inline private
Definition at line 142 of file cargocontainer.c.
    {
        InventoryLocation il = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation( il );
        int x = il.GetCol();
        #ifdef PLATFORM_CONSOLE
        int y = il.GetRow() - 1;
        #else
        int y = il.GetRow();
        #endif
        if( m_ShowedItemPositions.Contains( item ) )
        {
            ref Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get( item );
            if( data.param1 )
            {
                if( data.param2 != x || data.param3 != y )
                {
                    data.param2 = x;
                    data.param3 = y;
                    #ifdef PLATFORM_CONSOLE
                        data.param1.SetCargoPos( data.param3 );
                    #endif
                    #ifdef PLATFORM_WINDOWS
                    data.param1.SetPosX( data.param2 );
                    data.param1.SetPosY( data.param3 );
                    #endif
                }
                data.param1.UpdateInterval();
            }
        }
        UpdateSelection();
    }
References InventoryLocation::GetCol(), InventoryLocation::GetRow(), Icon::SetCargoPos(), UpdateSelection(), x, and y.
OnShow()
override void Container::OnShow () inline private
Definition at line 93 of file closablecontainer.c.
    {
        if( IsOpened() )
        {
            super.OnShow();
        }
    }
References ClosableContainer::IsOpened().
Referenced by AttachmentCategoriesContainer::UpdateInterval().
Open()
override void Container::Open () inline private
Definition at line 67 of file closablecontainer.c.
    {
        if( IsDisplayable() )
        {
            super.Open();
            ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), true );
            SetOpenForSlotIcon(true);
            OnShow();
            m_Parent.m_Parent.Refresh();
        }
    }
References ItemManager::GetInstance(), ClosableContainer::IsDisplayable(), m_Entity, m_Parent, OnShow(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesRow::OnMouseButtonDown(), CollapsibleContainer::OnShow(), and LayoutHolder::Toggle().
Refresh() [1/2]
override void Container::Refresh () inline private
Definition at line 504 of file cargocontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
        if ( !m_ResizeTimer )
            m_ResizeTimer = new Timer();
        if ( m_ResizeTimer.IsRunning() )
            m_ResizeTimer.Stop();
        m_ResizeTimer.Run( 0.05, this, "RefreshImpl" );
        #endif
    }
Referenced by AddedToCargoEx(), LayoutHolder::Insert(), LayoutHolder::Remove(), RemovedFromCargo(), and SetEntity().
Refresh() [2/2]
override void Container::Refresh () inline private
Definition at line 108 of file closablecontainer.c.
    {
        if( !m_Closed )
        {
            super.Refresh();
        }
    }
RefreshImpl()
void Container::RefreshImpl () inline private
Definition at line 515 of file cargocontainer.c.
    {
        UpdateRowVisibility( m_ShowedItemPositions.Count() );
        UpdateSelection();
    }
References UpdateRowVisibility(), and UpdateSelection().
ReleaseLock()
void Container::ReleaseLock (EntityAI item) inline private
Definition at line 197 of file cargocontainer.c.
    {
        #ifndef PLATFORM_CONSOLE
        if( m_ShowedLockPositions.Contains( item ) )
        {
            Icon ic = m_ShowedLockPositions.Get( item ).param1;
            m_Icons.RemoveItem( ic );
            m_ShowedLockPositions.Remove( item );
            item.GetOnReleaseLock().Remove( ReleaseLock );
        }
        #endif
    }
References LayoutHolder::Get(), and LayoutHolder::Remove().
RemovedFromCargo()
void Container::RemovedFromCargo (EntityAI item) inline private
Definition at line 113 of file cargocontainer.c.
    {
        Param3<ref Icon, int, int> data = m_ShowedItemPositions.Get( item );
        if( data )
        {
            m_Icons.RemoveItem( data.param1 );
            m_ShowedItemPositions.Remove( item );
        }
        UpdateHeaderText();
        #ifdef PLATFORM_CONSOLE
        for( int i = 0; i < m_Cargo.GetItemCount(); i++ )
        {
            EntityAI item2 = m_Cargo.GetItem( i );
            data = m_ShowedItemPositions.Get( item2 );
            if( data && data.param1 )
            {
                data.param1.SetCargoPos( i );
                data.param1.SetPos();
            }
        }
        m_FocusedItemPosition = Math.Min( m_ShowedItemPositions.Count() - 1, m_FocusedItemPosition );
        Refresh();
        #endif
    }
References CargoBase::GetItem(), CargoBase::GetItemCount(), Math::Min(), Refresh(), and UpdateHeaderText().
Select()
override bool Container::Select () inline private
Definition at line 872 of file cargocontainer.c.
    {
        EntityAI focused_item = GetFocusedItem();
        EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
        DayZPlayer player = GetGame().GetPlayer();
        if( focused_item != selected_item )
        {
            if( selected_item )
            {
                if( selected_item.GetInventory().CanRemoveEntity() && m_Entity )
                {
                    bool can_add = m_Entity.GetInventory().CanAddEntityInCargo( selected_item, selected_item.GetInventory().GetFlipCargo());
                    bool in_cargo = !player.GetInventory().HasEntityInInventory( selected_item ) || !m_Entity.GetInventory().HasEntityInCargo( selected_item );
                    if( can_add && in_cargo )
                    {
                        player.PredictiveTakeEntityToTargetCargo( m_Entity, selected_item );
                        Container selected_cont2 = ItemManager.GetInstance().GetSelectedContainer();
                        if( selected_cont2 )
{
                            selected_cont2.SetActive( false );
                        }
                        SetActive( true );
                        m_FocusedItemPosition = 0;
                        return true;
                    }
                    else
                    {
                        Container selected_cont = ItemManager.GetInstance().GetSelectedContainer();
                        if( selected_cont )
{
                            selected_cont.SetActive( false );
                        }
                        SetActive( true );
                        SetDefaultFocus( true );
                    }
                }
            }
            else if ( focused_item && focused_item.GetInventory().CanRemoveEntity() )
            {
                EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
                if( item_in_hands )
                {
                    if( GameInventory.CanSwapEntitiesEx( item_in_hands, focused_item ) )
                    {
                        player.PredictiveSwapEntities( item_in_hands, focused_item );
                        return true;
                    }
                }
                else
                {
                    if( player.GetHumanInventory().CanAddEntityInHands( focused_item ) )
                    {
                        player.PredictiveTakeEntityToHands( focused_item );
                        return true;
                    }
                }
            }
        }
        return false;
    }
References GetFocusedItem(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), ItemManager::GetSelectedContainer(), ItemManager::GetSelectedItem(), m_Entity, SetActive(), SetActive(), and SetDefaultFocus().
Referenced by HandsContainer::OnSelectButton(), AttachmentCategoriesRow::Select(), and UpdateInterval().
SelectItem()
override bool Container::SelectItem () inline private
Definition at line 857 of file cargocontainer.c.
    {
        Icon focused_item = GetFocusedIcon();
        if( focused_item )
        {
            ItemBase item = ItemBase.Cast(focused_item.GetObject());
            if (item && item.IsTakeable())
            {
                ItemManager.GetInstance().SetSelectedItem( item, this, null, null );
                return true;
            }
        }
        return false;
    }
References GetFocusedIcon(), ItemManager::GetInstance(), Icon::GetObject(), ItemBase::IsTakeable(), and ItemManager::SetSelectedItem().
Referenced by EnableMicromanagement(), and RightArea::SelectItem().
SetActive()
override void Container::SetActive (bool active) inline private
Definition at line 730 of file cargocontainer.c.
    {
        super.SetActive( active );
        UpdateSelection();
    }
References UpdateSelection().
Referenced by MoveFocusByArea(), LayoutHolder::RecomputeOpenedContainers(), ResetFocusedContainers(), Select(), LayoutHolder::SetActive(), AttachmentsGroupContainer::SetNextActive(), LayoutHolder::SetNextActive(), AttachmentsGroupContainer::SetPreviousActive(), and UpdateInterval().
SetAlternateFalseTextHeaderWidget()
void Container::SetAlternateFalseTextHeaderWidget (TextWidget w) inline private
Definition at line 960 of file cargocontainer.c.
    {
        bool update = !m_AlternateFalseHeaderTextWidget;
        m_AlternateFalseHeaderTextWidget = w;
        if (update)
        {
            UpdateHeaderText();
        }
    }
References m_AlternateFalseHeaderTextWidget, and UpdateHeaderText().
SetDefaultFocus()
override void Container::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 587 of file cargocontainer.c.
    {
        super.SetDefaultFocus(while_micromanagment_mode);
        Unfocus();
        m_FocusedItemPosition = 0;
        UpdateSelection();
    }
References Unfocus(), and UpdateSelection().
Referenced by Select(), LayoutHolder::SetActive(), LayoutHolder::SetFirstActive(), and SetLastFocus().
SetEntity()
void Container::SetEntity (EntityAI item, int cargo_index = 0, bool immedUpdate = true) inline private
Definition at line 237 of file cargocontainer.c.
    {
        if ( item )
        {
            m_Entity        = item;
            m_Cargo         = item.GetInventory().GetCargoFromIndex(cargo_index);
            m_CargoIndex    = cargo_index;
            m_Entity.GetOnItemAddedIntoCargo().Insert( AddedToCargo );
            m_Entity.GetOnItemRemovedFromCargo().Insert( RemovedFromCargo );
            m_Entity.GetOnItemMovedInCargo().Insert( MovedInCargo );
            m_Entity.GetOnSetLock().Insert( SetLock );
            m_Entity.GetOnReleaseLock().Insert( ReleaseLock );
            if (immedUpdate)
                UpdateHeaderText();
            InitGridHeight();
            m_MainWidget    = m_ItemsContainer;
            if ( m_Cargo )
            {
                int i;
                int prev_count = m_ShowedItemPositions.Count();
                //START - Add new item Icons
                for ( i = 0; i < m_Cargo.GetItemCount(); i++ )
                {
                    EntityAI cargo_item = m_Cargo.GetItem( i );
                    if ( cargo_item )
                    {
                        AddedToCargoEx( cargo_item, immedUpdate );
                    }
                }
                #ifdef PLATFORM_CONSOLE
                if (immedUpdate)
                    Refresh();
                #endif
            }
        }
    }
References AddedToCargoEx(), CargoBase::GetItem(), CargoBase::GetItemCount(), InitGridHeight(), m_Entity, m_ItemsContainer, Refresh(), SetLock(), and UpdateHeaderText().
SetLastActive()
override void Container::SetLastActive () inline private
Definition at line 719 of file cargocontainer.c.
    {
        super.SetLastActive();
        if( GetFocusedIcon() )
        {
            GetFocusedIcon().SetActive( false );
        }
        m_FocusedItemPosition = ( ( m_Rows.Count() - 1 ) * ROWS_NUMBER_XBOX );
        UpdateSelection();
    }
References GetFocusedIcon(), Icon::SetActive(), and UpdateSelection().
Referenced by Attachments::SetLastActive(), LayoutHolder::SetLastActive(), AttachmentsGroupContainer::SetPreviousActive(), and LayoutHolder::SetPreviousActive().
SetLastFocus()
override void Container::SetLastFocus () inline private
Definition at line 596 of file cargocontainer.c.
    {
        SetDefaultFocus();
    }
References SetDefaultFocus().
Referenced by LayoutHolder::SetLastActive().
SetLayoutName() [1/2]
override void Container::SetLayoutName () inline private
Definition at line 210 of file cargocontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_LayoutName = WidgetLayoutName.CargoContainerXbox;
        #else
            switch( InventoryMenu.GetWidthType() )
            {
                case ScreenWidthType.NARROW:
                {
                    m_LayoutName = WidgetLayoutName.CargoContainerNarrow;
                    break;
                }
                case ScreenWidthType.MEDIUM:
                {
                    m_LayoutName = WidgetLayoutName.CargoContainerMedium;
                    break;
                }
                case ScreenWidthType.WIDE:
                {
                    m_LayoutName = WidgetLayoutName.CargoContainerWide;
                    break;
                }
            }
        #endif
    }
References WidgetLayoutName::CargoContainerMedium, WidgetLayoutName::CargoContainerNarrow, WidgetLayoutName::CargoContainerWide, WidgetLayoutName::CargoContainerXbox, and InventoryMenu().
SetLayoutName() [2/2]
override void Container::SetLayoutName () inline private
Definition at line 88 of file closablecontainer.c.
    {
        m_LayoutName = WidgetLayoutName.ClosableContainer;
    }
References WidgetLayoutName::ClosableContainer.
SetLock()
void Container::SetLock (EntityAI item) inline private
Definition at line 176 of file cargocontainer.c.
    {
        #ifndef PLATFORM_CONSOLE
        if( GetGame().GetPlayer() )
        {
            InventoryLocation il = new InventoryLocation;
            int index = GetGame().GetPlayer().GetHumanInventory().FindUserReservedLocationIndex( item );
            if( index >= 0 )
            {
                GetGame().GetPlayer().GetHumanInventory().GetUserReservedLocation( index, il );
                ref Icon icon = new Icon( this, false );
                m_Icons.Insert( icon );
                icon.InitLock( m_Entity, item, il.GetCol(), il.GetRow(), il.GetFlip() );
                m_ShowedLockPositions.Insert( item, new Param3<ref Icon, int, int>( icon, 1, 1 ) );
                item.GetOnReleaseLock().Insert( ReleaseLock );
            }
        }
        #endif
    }
References InventoryLocation::GetCol(), InventoryLocation::GetFlip(), GetGame(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetRow(), and m_Entity.
SetNextActive()
override void Container::SetNextActive () inline private
Definition at line 622 of file cargocontainer.c.
    {
        Unfocus();
        int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
        int max_row = ( m_Icons.Count() - 1) / ROWS_NUMBER_XBOX;
        if ( max_row > focused_row )
        {
            m_FocusedItemPosition += ROWS_NUMBER_XBOX;
            if ( m_FocusedItemPosition >= m_Icons.Count() )
            {
                m_FocusedItemPosition = m_Icons.Count() - 1;
            }
            UpdateSelection();
        }
        else
        {
            SetActive(false);
        }
    }
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), AttachmentsGroupContainer::SetNextActive(), and LayoutHolder::SetNextActive().
SetNextLeftActive()
override void Container::SetNextLeftActive () inline private
Definition at line 684 of file cargocontainer.c.
    {
        if ( m_Icons.Count() > 0)
        {
            Unfocus();
            int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
            int row_min = focused_row * ROWS_NUMBER_XBOX;
            int row_max = row_min + ROWS_NUMBER_XBOX - 1;
            if ( row_max >= m_Icons.Count() )
            {
                row_max = m_Icons.Count() - 1;
            }
            m_FocusedItemPosition--;
            if( m_FocusedItemPosition < row_min )
            {
                m_FocusedItemPosition = row_max;
            }
            UpdateSelection();
        }
    }
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), and LayoutHolder::SetNextLeftActive().
SetNextRightActive()
override void Container::SetNextRightActive () inline private
Definition at line 660 of file cargocontainer.c.
    {
        if ( m_Icons.Count() > 0)
        {
            Unfocus();
            int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
            int row_min = focused_row * ROWS_NUMBER_XBOX;
            int row_max = row_min + ROWS_NUMBER_XBOX - 1;
            if ( row_max >= m_Icons.Count() )
            {
                row_max = m_Icons.Count() - 1;
            }
            m_FocusedItemPosition++;
            if( m_FocusedItemPosition > row_max )
            {
                m_FocusedItemPosition = row_min;
            }
            UpdateSelection();
        }
    }
References ROWS_NUMBER_XBOX, Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), and LayoutHolder::SetNextRightActive().
SetOpenState()
void Container::SetOpenState (bool state) inline private
Definition at line 48 of file closablecontainer.c.
    {
        ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), state );
        m_Closed = !state;
        if( !m_Closed )
        {
            OnShow();
        }
        else
        {
            OnHide();
        }
    }
References ItemManager::GetInstance(), m_Entity, OnHide(), OnShow(), and ItemManager::SetDefaultOpenState().
SetPreviousActive()
override void Container::SetPreviousActive (bool force = false) inline private
Definition at line 643 of file cargocontainer.c.
    {
        Unfocus();
        int focused_row = m_FocusedItemPosition / ROWS_NUMBER_XBOX;
        if ( focused_row > 0 )
        {
            m_FocusedItemPosition = m_FocusedItemPosition - ROWS_NUMBER_XBOX;
            UpdateSelection();
        }
        else
        {
            SetActive(false);
        }
    }
References ROWS_NUMBER_XBOX, SetActive(), Unfocus(), and UpdateSelection().
Referenced by LayoutHolder::MoveGridCursor(), LayoutHolder::Remove(), AttachmentsGroupContainer::SetPreviousActive(), and LayoutHolder::SetPreviousActive().
ShowFalseCargoHeader()
void Container::ShowFalseCargoHeader (bool show) inline private
Definition at line 955 of file cargocontainer.c.
    {
        m_CargoHeader.Show(show);
    }
SplitItem()
override bool Container::SplitItem () inline private
Definition at line 821 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            ItemBase entity = ItemBase.Cast( GetFocusedIcon().GetObject() );
            if( entity )
            {
                if( entity.HasQuantity() && entity.CanBeSplit() )
                {
                    entity.OnRightClick();
                    Icon icon = m_ShowedItemPositions.Get( entity ).param1;
                    if ( icon )
                    {
                        icon.SetQuantity();
                    }
                }
            }
        }
        return false;
    }
References LayoutHolder::Get(), GetFocusedIcon(), GetObject(), and Icon::SetQuantity().
Referenced by UpdateInterval().
TransferItem()
override bool Container::TransferItem () inline private
Definition at line 807 of file cargocontainer.c.
    {
        if( GetFocusedIcon() )
        {
            EntityAI entity = EntityAI.Cast( GetFocusedIcon().GetObject() );
            if( entity )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, entity );
                return true;
            }
        }
        return false;
    }
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
TransferItemToVicinity()
override bool Container::TransferItemToVicinity () inline private
Definition at line 569 of file cargocontainer.c.
    {
        Man player = GetGame().GetPlayer();
        if( GetFocusedIcon() )
        {
            ItemBase item = ItemBase.Cast( GetFocusedIcon().GetObject() );
            if( item && player.CanDropEntity( item ) )
            {
                if( item.GetTargetQuantityMax() < item.GetQuantity() )
                    item.SplitIntoStackMaxClient( null, -1 );
                else
                    player.PhysicalPredictiveDropItem( item );
                return true;
            }
        }
        return false;
    }
References GetFocusedIcon(), GetGame(), GetObject(), and CGame::GetPlayer().
Referenced by UpdateInterval().
Unfocus()
override void Container::Unfocus () inline private
Definition at line 601 of file cargocontainer.c.
    {
        Icon icon = GetFocusedIcon();
        if ( icon )
        {
            icon.SetActive( false );
        }
    }
References GetFocusedIcon(), and Icon::SetActive().
Referenced by LayoutHolder::SetActive(), SetDefaultFocus(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UnfocusAll()
override void Container::UnfocusAll () inline private
Definition at line 610 of file cargocontainer.c.
    {
        if( m_Icons )
        {
            foreach( Icon icon : m_Icons )
            {
                icon.SetActive( false );
            }
        }
        m_FocusedItemPosition = 0;
    }
Referenced by Attachments::UnfocusAll(), and PlayerContainer::UnfocusPlayerAttachmentsContainer().
UpdateHeaderText()
void Container::UpdateHeaderText () inline private
Definition at line 285 of file cargocontainer.c.
    {
        Widget header;
        string name = m_Entity.GetDisplayName();
        name.ToUpper();
        if ( m_Entity.CanDisplayCargo() && m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex) )
        {
            name = name + " (" + GetCargoCapacity().ToString() + "/" + GetMaxCargoCapacity() + ")";
            if ( m_IsAttachment && m_CargoHeader )
            {
                m_FalseHeaderTextWidget.SetText(name);
                float x, y;
                m_FalseHeaderTextWidget.Update();
                m_FalseHeaderTextWidget.GetScreenSize( x, y );
                m_CargoHeader.FindAnyWidget( "grid_container_header" ).SetSize( 1, y + InventoryMenu.GetHeightMultiplied( 10 ) );
                m_CargoHeader.Update();
                if (m_AlternateFalseHeaderTextWidget)
                {
                    m_AlternateFalseHeaderTextWidget.SetText(name);
                }
                return;
            }
        }
        if ( Container.Cast( GetParent() ) && Container.Cast( GetParent() ).GetHeader() )
            Container.Cast( GetParent() ).GetHeader().SetName(name);
    }
References GetCargoCapacity(), GetHeader(), GetMaxCargoCapacity(), GetParent(), InventoryMenu(), m_Entity, name, Header::SetName(), string::ToUpper(), x, and y.
Referenced by AddedToCargoEx(), RemovedFromCargo(), SetAlternateFalseTextHeaderWidget(), and SetEntity().
UpdateInterval()
override void Container::UpdateInterval () inline private
Definition at line 521 of file cargocontainer.c.
    {
        foreach( Param3<ref Icon, int, int> data : m_ShowedItemPositions )
        {
            if( data.param1 )
            {
                data.param1.UpdateInterval();
            }
        }
    }
Referenced by PlayerContainer::UpdateInterval().
UpdateRadialIcon()
override void Container::UpdateRadialIcon () inline private
Definition at line 28 of file closablecontainer.c.
    {
        if ( m_SlotIcon )
        {
            bool show_radial_icon;
            show_radial_icon = IsOpened();
            show_radial_icon = show_radial_icon && ( ( m_Entity.GetInventory().GetCargo() && m_Entity.CanDisplayCargo()) || m_Entity.GetSlotsCountCorrect() > 0 );
            show_radial_icon = show_radial_icon && !m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT );
            if ( IsDisplayable() )
            {
                m_SlotIcon.GetRadialIconPanel().Show( true );
                SetOpenForSlotIcon(show_radial_icon);
            }
            else
            {
                m_SlotIcon.GetRadialIconPanel().Show( false );
            }
        }
    }
References ClosableContainer::IsDisplayable(), ClosableContainer::IsOpened(), m_Entity, and ScriptedWidgetEventHandler::Show().
Referenced by VicinitySlotsContainer::ShowItemsInContainers(), and Attachments::UpdateInterval().
UpdateRowVisibility()
void Container::UpdateRowVisibility (int count) inline private
Definition at line 472 of file cargocontainer.c.
    {
        int i;
        int rows = Math.Max( 1, Math.Ceil( (count + 1) / ROWS_NUMBER_XBOX ) );
        int diff = rows - m_Rows.Count();
        if( diff < 0 )
        {
            for( i = m_Rows.Count() - 1; i >= rows; i-- )
            {
                m_Rows.Remove( i );
            }
        }
        else if( diff > 0 )
        {
            m_MainWidget    = m_CargoContainer;
            for( i = m_Rows.Count(); i < rows; i++ )
            {
                ref CargoContainerRow row = new CargoContainerRow( this );
                row.SetNumber( i );
                row.SetEntity( m_Entity );
                row.GetRootWidget().SetSort( i );
                m_Rows.Insert( row );
            }
            m_MainWidget    = m_ItemsContainer;
        }
        m_Resizer2.ResizeParentToChild();
        m_Resizer1.ResizeParentToChild();
    }
References Math::Ceil(), m_CargoContainer, m_Entity, m_ItemsContainer, and Math::Max().
Referenced by RefreshImpl().
UpdateSelection()
void Container::UpdateSelection () inline private
Definition at line 457 of file cargocontainer.c.
    {
        if( m_IsActive )
        {
            if( m_FocusedItemPosition >= m_Icons.Count() )
                m_FocusedItemPosition = m_Icons.Count() - 1;
            Icon icon = GetIcon( m_FocusedItemPosition );
            if( icon && !icon.IsActive() )
            {
                icon.SetActive( true );
                Inventory.GetInstance().UpdateConsoleToolbar();
            }
        }
    }
References GetIcon(), Inventory(), m_IsActive, and Icon::SetActive().
Referenced by MovedInCargo(), RefreshImpl(), SetActive(), SetDefaultFocus(), SetLastActive(), SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().
UpdateSize()
void Container::UpdateSize () inline private
Definition at line 357 of file cargocontainer.c.
    {
        m_Resizer1.ResizeParentToChild();
    }
Member Data Documentation
m_AlternateFalseHeaderTextWidget
protected TextWidget Container::m_AlternateFalseHeaderTextWidget private
Definition at line 20 of file cargocontainer.c.
Referenced by SetAlternateFalseTextHeaderWidget().
m_Cargo
protected CargoBase Container::m_Cargo private
Definition at line 6 of file cargocontainer.c.
m_CargoContainer
protected Widget Container::m_CargoContainer private
Definition at line 22 of file cargocontainer.c.
Referenced by CargoContainer(), and UpdateRowVisibility().
m_CargoHeader
protected Widget Container::m_CargoHeader private
Definition at line 21 of file cargocontainer.c.
m_CargoIndex
protected int Container::m_CargoIndex = -1 private
Definition at line 7 of file cargocontainer.c.
Referenced by GetCargoIndex().
m_ClosableHeader
protected ref ClosableHeader Container::m_ClosableHeader private
Definition at line 3 of file closablecontainer.c.
m_FalseHeaderTextWidget
protected TextWidget Container::m_FalseHeaderTextWidget private
Definition at line 19 of file cargocontainer.c.
m_FocusedItemPosition
protected int Container::m_FocusedItemPosition = -1 private
Definition at line 9 of file cargocontainer.c.
m_Icons
protected ref array<ref Icon> Container::m_Icons private
Definition at line 11 of file cargocontainer.c.
m_IconSize
protected float Container::m_IconSize private
Definition at line 15 of file cargocontainer.c.
Referenced by GetIconSize().
m_IsAttachment
protected bool Container::m_IsAttachment private
Definition at line 18 of file cargocontainer.c.
m_ItemsContainer
protected Widget Container::m_ItemsContainer private
Definition at line 23 of file cargocontainer.c.
Referenced by SetEntity(), and UpdateRowVisibility().
m_LockCargo
protected bool Container::m_LockCargo private
Definition at line 4 of file closablecontainer.c.
m_Resizer1
protected ref SizeToChild Container::m_Resizer1 private
Definition at line 24 of file cargocontainer.c.
m_Resizer2
protected ref SizeToChild Container::m_Resizer2 private
Definition at line 25 of file cargocontainer.c.
m_ResizeTimer
protected ref Timer Container::m_ResizeTimer private
Definition at line 26 of file cargocontainer.c.
m_Rows
protected ref array<ref CargoContainerRow> Container::m_Rows private
Definition at line 10 of file cargocontainer.c.
m_ShowedItemPositions
protected ref map<EntityAI, ref Param3<ref Icon, int, int> > Container::m_ShowedItemPositions private
Definition at line 12 of file cargocontainer.c.
m_ShowedLockPositions
protected ref map<EntityAI, ref Param3<ref Icon, int, int> > Container::m_ShowedLockPositions private
Definition at line 13 of file cargocontainer.c.
m_SpaceSize
protected float Container::m_SpaceSize private
Definition at line 16 of file cargocontainer.c.
Referenced by GetSpaceSize().
ROWS_NUMBER_XBOX
protected const int Container::ROWS_NUMBER_XBOX = 5 private
Definition at line 4 of file cargocontainer.c.
Referenced by SetNextActive(), SetNextLeftActive(), SetNextRightActive(), and SetPreviousActive().