DayzKode: PluginDayzPlayerDebug_Ctrl Class Reference
PluginDayzPlayerDebug_Ctrl Class Reference
Private Member Functions
void CommandHandler ()
void CreateModuleWidgets ()
void DestroyModuleWidgets ()
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
void PluginDayzPlayerDebug_Ctrl (Widget pMainWnd)
void ~PluginDayzPlayerDebug_Ctrl ()
Private Attributes
int m_ApplyStanceChange
XComboBoxWidget m_ForceStance
Widget m_MainWnd
EditBoxWidget m_MovDirEB
CheckBoxWidget m_MovOverrideCheckbox
EditBoxWidget m_MovSpeedEB
bool m_OverrideMovementChange = false
Detailed Description
Definition at line 6 of file plugindayzplayerdebug_ctrl.c.
Constructor & Destructor Documentation
PluginDayzPlayerDebug_Ctrl()
void PluginDayzPlayerDebug_Ctrl::PluginDayzPlayerDebug_Ctrl (Widget pMainWnd) inline private
Definition at line 23 of file plugindayzplayerdebug_ctrl.c.
    {
        m_MainWnd           = pMainWnd;
        m_ApplyStanceChange = -2;
        CreateModuleWidgets();
    }
References CreateModuleWidgets(), m_ApplyStanceChange, and m_MainWnd.
~PluginDayzPlayerDebug_Ctrl()
void PluginDayzPlayerDebug_Ctrl::~PluginDayzPlayerDebug_Ctrl () inline private
Definition at line 32 of file plugindayzplayerdebug_ctrl.c.
    {
        DestroyModuleWidgets();
    }
References DestroyModuleWidgets().
Member Function Documentation
CommandHandler()
void PluginDayzPlayerDebug_Ctrl::CommandHandler () inline private
Definition at line 107 of file plugindayzplayerdebug_ctrl.c.
    {
        if (m_ApplyStanceChange != -2)
        {
            DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
            if (!player)
            {
                return;
            }
            HumanCommandMove cm = player.GetCommand_Move();
            if (cm)
            {
                cm.ForceStance(m_ApplyStanceChange);
                m_ApplyStanceChange = -2;
            }
        }
        if (m_OverrideMovementChange)
        {
            m_OverrideMovementChange = false;
            player = DayZPlayer.Cast( GetGame().GetPlayer() );
            if (!player)
                return;
            float speed = m_MovSpeedEB.GetText().ToFloat();
            float dir = m_MovDirEB.GetText().ToFloat();
            player.GetInputController().OverrideMovementSpeed(m_MovOverrideCheckbox.IsChecked(), speed);
            player.GetInputController().OverrideMovementAngle(m_MovOverrideCheckbox.IsChecked(), dir);
        }
    }
References HumanCommandMove::ForceStance(), GetGame(), GetPlayer(), m_ApplyStanceChange, m_MovDirEB, m_MovOverrideCheckbox, m_MovSpeedEB, and m_OverrideMovementChange.
Referenced by CommandHandler().
CreateModuleWidgets()
void PluginDayzPlayerDebug_Ctrl::CreateModuleWidgets () inline private
Definition at line 38 of file plugindayzplayerdebug_ctrl.c.
    {
        m_ForceStance = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("StanceV") );
        m_MovSpeedEB = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("MovSpeedEB") );
        m_MovDirEB = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("MovDirEB") );
        m_MovOverrideCheckbox = CheckBoxWidget.Cast( m_MainWnd.FindAnyWidget("OverrideMovCheckBox") );
    }
References m_ForceStance, m_MainWnd, m_MovDirEB, m_MovOverrideCheckbox, and m_MovSpeedEB.
Referenced by PluginDayzPlayerDebug_Ctrl().
DestroyModuleWidgets()
void PluginDayzPlayerDebug_Ctrl::DestroyModuleWidgets () inline private
Definition at line 46 of file plugindayzplayerdebug_ctrl.c.
    {
    }
Referenced by ~PluginDayzPlayerDebug_Ctrl().
OnChange()
bool PluginDayzPlayerDebug_Ctrl::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 92 of file plugindayzplayerdebug_ctrl.c.
    {
        if( w == m_MovSpeedEB || w == m_MovDirEB )
        {
            Print("Movement override");
            m_OverrideMovementChange = true;
            return true;
        }
        return false;
    }
References m_MovDirEB, m_MovSpeedEB, m_OverrideMovementChange, and Print().
OnClick()
bool PluginDayzPlayerDebug_Ctrl::OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 74 of file plugindayzplayerdebug_ctrl.c.
    {
        if (w == m_ForceStance)
        {
            Print("Stance changed");
            m_ApplyStanceChange = m_ForceStance.GetCurrentItem() - 1;
            return true;
        }
        else if (w == m_MovOverrideCheckbox)
        {
            Print("Movement override");
            m_OverrideMovementChange = true;
        }
        return false;
    }
References m_ApplyStanceChange, m_ForceStance, m_MovOverrideCheckbox, m_OverrideMovementChange, and Print().
Member Data Documentation
m_ApplyStanceChange
int PluginDayzPlayerDebug_Ctrl::m_ApplyStanceChange private
Definition at line 16 of file plugindayzplayerdebug_ctrl.c.
Referenced by CommandHandler(), OnClick(), and PluginDayzPlayerDebug_Ctrl().
m_ForceStance
XComboBoxWidget PluginDayzPlayerDebug_Ctrl::m_ForceStance private
Definition at line 10 of file plugindayzplayerdebug_ctrl.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_MainWnd
Widget PluginDayzPlayerDebug_Ctrl::m_MainWnd private
Definition at line 8 of file plugindayzplayerdebug_ctrl.c.
Referenced by CreateModuleWidgets(), and PluginDayzPlayerDebug_Ctrl().
m_MovDirEB
EditBoxWidget PluginDayzPlayerDebug_Ctrl::m_MovDirEB private
Definition at line 12 of file plugindayzplayerdebug_ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnChange().
m_MovOverrideCheckbox
CheckBoxWidget PluginDayzPlayerDebug_Ctrl::m_MovOverrideCheckbox private
Definition at line 13 of file plugindayzplayerdebug_ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnClick().
m_MovSpeedEB
EditBoxWidget PluginDayzPlayerDebug_Ctrl::m_MovSpeedEB private
Definition at line 11 of file plugindayzplayerdebug_ctrl.c.
Referenced by CommandHandler(), CreateModuleWidgets(), and OnChange().
m_OverrideMovementChange
bool PluginDayzPlayerDebug_Ctrl::m_OverrideMovementChange = false private
Definition at line 17 of file plugindayzplayerdebug_ctrl.c.
Referenced by CommandHandler(), OnChange(), and OnClick().