DayzKode: ToggleAnimations Class Reference
ToggleAnimations Class Reference
Private Member Functions
int GetOpeningBit ()
string GetToggleOff ()
string GetToggleOn ()
void ToggleAnimations (string toggle_off, string toggle_on, int mask, array< string > linked_anims_off=null, array< string > linked_anims_on=null)
Private Attributes
int m_OpeningBit
protected string m_ToggleOff
protected string m_ToggleOn
Detailed Description
Definition at line 1 of file toggleselections.c.
Constructor & Destructor Documentation
ToggleAnimations()
void ToggleAnimations::ToggleAnimations (string toggle_off, string toggle_on, int mask, array< string > linked_anims_off = null, array< string > linked_anims_on = null) inline private
Definition at line 9 of file toggleselections.c.
    {
        m_ToggleOff = toggle_off;
        m_ToggleOn = toggle_on;
        m_OpeningBit = mask;
        //m_ToggleOffLinkedAnimations = linked_anims_off;
        //m_ToggleOnLinkedAnimations = linked_anims_on;
    }
References m_OpeningBit, m_ToggleOff, and m_ToggleOn.
Member Function Documentation
GetOpeningBit()
int ToggleAnimations::GetOpeningBit () inline private
Definition at line 28 of file toggleselections.c.
    {
        return m_OpeningBit;
    }
References m_OpeningBit.
Referenced by TentBase::AnimateCamonetToggle(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
GetToggleOff()
string ToggleAnimations::GetToggleOff () inline private
Definition at line 18 of file toggleselections.c.
    {
        return m_ToggleOff;
    }
References m_ToggleOff.
Referenced by TentBase::AnimateCamonetToggle(), ItemBase::CanToggleAnimations(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
GetToggleOn()
string ToggleAnimations::GetToggleOn () inline private
Definition at line 23 of file toggleselections.c.
    {
        return m_ToggleOn;
    }
References m_ToggleOn.
Referenced by TentBase::AnimateCamonetToggle(), ItemBase::CanToggleAnimations(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), ItemBase::HandleOpeningsVisuals(), and ItemBase::ToggleAnimation().
Member Data Documentation
m_OpeningBit
int ToggleAnimations::m_OpeningBit private
Definition at line 5 of file toggleselections.c.
Referenced by GetOpeningBit(), and ToggleAnimations().
m_ToggleOff
protected string ToggleAnimations::m_ToggleOff private
Definition at line 3 of file toggleselections.c.
Referenced by GetToggleOff(), and ToggleAnimations().
m_ToggleOn
protected string ToggleAnimations::m_ToggleOn private
Definition at line 4 of file toggleselections.c.
Referenced by GetToggleOn(), and ToggleAnimations().