DayzKode: Heatpack Class Reference
Heatpack Class Reference
Private Member Functions
override bool CanHaveTemperature ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
Detailed Description
Definition at line 1 of file heatpack.c.
Member Function Documentation
CanHaveTemperature()
override bool Heatpack::CanHaveTemperature () inline private
Definition at line 3 of file heatpack.c.
    {
        return true;
    }
OnWork()
override void Heatpack::OnWork (float consumed_energy) inline private
Definition at line 16 of file heatpack.c.
    {
        if (GetGame().IsServer())
        {
            SetTemperature(60);
        }
    }
References GetGame(), and SetTemperature().
OnWorkStart()
override void Heatpack::OnWorkStart () inline private
Definition at line 8 of file heatpack.c.
    {
        if (GetGame().IsServer())
        {
            SetTemperature(60);
        }
    }
References GetGame(), and SetTemperature().
OnWorkStop()
override void Heatpack::OnWorkStop () inline private
Definition at line 24 of file heatpack.c.
    {
        if (GetGame().IsServer())
        {
            SetHealth(0);
        }
    }
References GetGame(), and SetHealth().
SetActions()
override void Heatpack::SetActions () inline private
Definition at line 32 of file heatpack.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnHeatpack);
    }
References AddAction().