DayzKode: TestDiseaseMdfr Class Reference
TestDiseaseMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_Interval
ref Param1< float > m_SomeValue
Detailed Description
Definition at line 1 of file testdisease.c.
Member Function Documentation
ActivateCondition()
override bool TestDiseaseMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 19 of file testdisease.c.
    {
        return false;
    }
DeactivateCondition()
override bool TestDiseaseMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 39 of file testdisease.c.
    {
        return false;
    }
Init()
override void TestDiseaseMdfr::Init () inline private
Definition at line 6 of file testdisease.c.
    {
        m_TrackActivatedTime            = false;
        m_ID                            = 9999;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 5;
        m_SomeValue     = new Param1<float>(0);
        MakeParamObjectPersistent(m_SomeValue);
        DisableDeactivateCheck();
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), DisableDeactivateCheck(), m_ID, m_SomeValue, m_TickIntervalActive, m_TickIntervalInactive, m_TrackActivatedTime, and MakeParamObjectPersistent().
OnActivate()
override void TestDiseaseMdfr::OnActivate (PlayerBase player) inline private
Definition at line 24 of file testdisease.c.
    {
        //player.GetBleedingManagerServer().AttemptAddBleedingSource(Math.RandomInt(0, 100));
    }
OnDeactivate()
override void TestDiseaseMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 35 of file testdisease.c.
    {
    }
OnReconnect()
override void TestDiseaseMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 29 of file testdisease.c.
    {
        //OnActivate(player);
        //player.GetSymptomManager().QueueUpSecondaryState( SymptomIDs.SYMPTOM_BLINDNESS );
    }
OnTick()
override void TestDiseaseMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 44 of file testdisease.c.
    {
        player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_LAUGHTER);
    }
Member Data Documentation
m_Interval
float TestDiseaseMdfr::m_Interval private
Definition at line 3 of file testdisease.c.
m_SomeValue
ref Param1<float> TestDiseaseMdfr::m_SomeValue private
Definition at line 4 of file testdisease.c.
Referenced by Init().