DayzKode: WeaponEventBase Class Reference
WeaponEventBase Class Reference
signalize mechanism manipulation
Private Member Functions
string DumpToString ()
WeaponEvents GetAnimEvent ()
returns animation event from anim engine,
override int GetAnimEvent ()
WeaponEventID GetEventID ()
returns id from enum WeaponEventID
int GetPackedType ()
returns eventID in upper 16 bits and AnimEvent in lower 16 bits
void ReadFromContext (ParamsReadContext ctx)
override void ReadFromContext (ParamsReadContext ctx)
override void ReadFromContext (ParamsReadContext ctx)
void WeaponEventAnimation (DayZPlayer p=NULL, Magazine m=NULL)
animation event from Human.WeaponEvents
void WeaponEventAttachMagazine (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventBase (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventContinuousLoadBulletEnd (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventContinuousLoadBulletStart (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventDetachMagazine (DayZPlayer p=NULL, Magazine m=NULL, InventoryLocation il=NULL)
void WeaponEventDryFireTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventHumanCommandActionAborted (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventHumanCommandActionFinished (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventLoad1Bullet (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventMechanism (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventReloadTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventSetNextMuzzleMode (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventSwapMagazine (DayZPlayer p=NULL, Magazine m=NULL, InventoryLocation il=NULL)
void WeaponEventTrigger (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerAutoEnd (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerAutoStart (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventTriggerToJam (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjam (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjammingFailedTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WeaponEventUnjammingTimeout (DayZPlayer p=NULL, Magazine m=NULL)
void WriteToContext (ParamsWriteContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
override void WriteToContext (ParamsWriteContext ctx)
Private Attributes
ref InventoryLocation m_dst
int m_eventID
Magazine m_magazine
DayZPlayer m_player
WeaponEvents m_type
Detailed Description
signalize mechanism manipulation
represents event that triggers transition from state to state
triggered when dry fire timer expires
triggered when reload timer expires
triggered when animation action aborts
triggered when animation action finishes
event when user wants to swap magazine
event when user wants to detach magazine
triggered when unjamming failed timer expires
triggered when unjamming timer expires
event when user wants to attach magazine
event when user wants to unjam weapon
event when user wants to end loading of bullets
event when user wants to load N bullets
event when user wants to load 1 bullet
event when trigger pressed
Parameters
dst inventory location where the magazine will be stored
Definition at line 34 of file events.c.
Constructor & Destructor Documentation
WeaponEventBase()
void WeaponEventBase::WeaponEventBase (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 40 of file events.c.
{ m_eventID = 0; m_player = p; m_magazine = m; }
References m_eventID, m_magazine, and m_player.
Member Function Documentation
DumpToString()
string WeaponEventBase::DumpToString () inline private
Definition at line 62 of file events.c.
    {
        string res = "{ WpnEv id=" + typename.EnumToString(WeaponEventID, GetEventID());
        res = res + " pl=" + Object.GetDebugName(m_player);
        res = res + " mag=" + Object.GetDebugName(m_magazine);
        res = res + " }";
        return res;
    }
References GetEventID(), m_magazine, and m_player.
Referenced by DeferredWeaponFailed(), HandleWeaponEvents(), and PostWeaponEvent().
GetAnimEvent() [1/2]
WeaponEvents WeaponEventBase::GetAnimEvent () inline private
returns animation event from anim engine,
See also
WeaponEvents
Definition at line 44 of file events.c.
{ return -1; }
Referenced by GetPackedType().
GetAnimEvent() [2/2]
override int WeaponEventBase::GetAnimEvent () inline private
Definition at line 219 of file events.c.
{ return m_type; }
GetEventID()
WeaponEventID WeaponEventBase::GetEventID () inline private
returns id from enum WeaponEventID
Definition at line 42 of file events.c.
{ return m_eventID; }
References m_eventID.
Referenced by DumpToString(), OnEventForRemoteWeapon(), Weapon::ProcessWeaponEvent(), and Weapon::SyncEventToRemote().
GetPackedType()
int WeaponEventBase::GetPackedType () inline private
returns eventID in upper 16 bits and AnimEvent in lower 16 bits
Definition at line 46 of file events.c.
    {
        int animEvent = GetAnimEvent() & 0x0000ffff;
        int evShl = m_eventID << 16;
        return evShl | animEvent;
    }
References GetAnimEvent(), and m_eventID.
Referenced by WriteToContext().
ReadFromContext() [1/3]
void WeaponEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 53 of file events.c.
{ }
Referenced by CreateWeaponEventFromContext().
ReadFromContext() [2/3]
override void WeaponEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 152 of file events.c.
    {
        m_dst = new InventoryLocation;
        super.ReadFromContext(ctx);
        m_dst.ReadFromContext(ctx);
    }
References m_dst, and InventoryLocation::ReadFromContext().
ReadFromContext() [3/3]
override void WeaponEventBase::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 171 of file events.c.
    {
        super.ReadFromContext(ctx);
        m_dst = new InventoryLocation;
        m_dst.ReadFromContext(ctx);
    }
References m_dst, and InventoryLocation::ReadFromContext().
WeaponEventAnimation()
void WeaponEventBase::WeaponEventAnimation (DayZPlayer p = NULL, Magazine m = NULL) inline private
animation event from Human.WeaponEvents
Definition at line 218 of file events.c.
{ m_eventID = WeaponEventID.ANIMATION_EVENT; }
WeaponEventAttachMagazine()
void WeaponEventBase::WeaponEventAttachMagazine (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 130 of file events.c.
{ m_eventID = WeaponEventID.ATTACH_MAGAZINE; }
WeaponEventContinuousLoadBulletEnd()
void WeaponEventBase::WeaponEventContinuousLoadBulletEnd (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 118 of file events.c.
{ m_eventID = WeaponEventID.CONTINUOUS_LOADBULLET_END; }
WeaponEventContinuousLoadBulletStart()
void WeaponEventBase::WeaponEventContinuousLoadBulletStart (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 112 of file events.c.
{ m_eventID = WeaponEventID.CONTINUOUS_LOADBULLET_START; }
WeaponEventDetachMagazine()
void WeaponEventBase::WeaponEventDetachMagazine (DayZPlayer p = NULL, Magazine m = NULL, InventoryLocation il = NULL) inline private
Definition at line 150 of file events.c.
{ m_eventID =  WeaponEventID.DETACH_MAGAZINE; m_dst = il; }
References m_dst.
WeaponEventDryFireTimeout()
void WeaponEventBase::WeaponEventDryFireTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 205 of file events.c.
{ m_eventID = WeaponEventID.DRY_FIRE_TIMEOUT; }
WeaponEventHumanCommandActionAborted()
void WeaponEventBase::WeaponEventHumanCommandActionAborted (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 193 of file events.c.
{ m_eventID = WeaponEventID.HUMANCOMMAND_ACTION_ABORTED; }
WeaponEventHumanCommandActionFinished()
void WeaponEventBase::WeaponEventHumanCommandActionFinished (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 187 of file events.c.
{ m_eventID = WeaponEventID.HUMANCOMMAND_ACTION_FINISHED; }
WeaponEventLoad1Bullet()
void WeaponEventBase::WeaponEventLoad1Bullet (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 106 of file events.c.
{ m_eventID = WeaponEventID.LOAD1_BULLET; }
WeaponEventMechanism()
void WeaponEventBase::WeaponEventMechanism (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 76 of file events.c.
{ m_eventID = WeaponEventID.MECHANISM; }
WeaponEventReloadTimeout()
void WeaponEventBase::WeaponEventReloadTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 199 of file events.c.
{ m_eventID = WeaponEventID.RELOAD_TIMEOUT; }
WeaponEventSetNextMuzzleMode()
void WeaponEventBase::WeaponEventSetNextMuzzleMode (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 212 of file events.c.
{ m_eventID = WeaponEventID.SET_NEXT_MUZZLE_MODE; }
WeaponEventSwapMagazine()
void WeaponEventBase::WeaponEventSwapMagazine (DayZPlayer p = NULL, Magazine m = NULL, InventoryLocation il = NULL) inline private
Definition at line 169 of file events.c.
{ m_eventID = WeaponEventID.SWAP_MAGAZINE;m_dst = il; }
References m_dst.
WeaponEventTrigger()
void WeaponEventBase::WeaponEventTrigger (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 82 of file events.c.
{ m_eventID = WeaponEventID.TRIGGER; }
WeaponEventTriggerAutoEnd()
void WeaponEventBase::WeaponEventTriggerAutoEnd (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 100 of file events.c.
{ m_eventID = WeaponEventID.TRIGGER_AUTO_END; }
WeaponEventTriggerAutoStart()
void WeaponEventBase::WeaponEventTriggerAutoStart (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 94 of file events.c.
{ m_eventID = WeaponEventID.TRIGGER_AUTO_START; }
WeaponEventTriggerToJam()
void WeaponEventBase::WeaponEventTriggerToJam (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 88 of file events.c.
{ m_eventID = WeaponEventID.TRIGGER_JAM; }
WeaponEventUnjam()
void WeaponEventBase::WeaponEventUnjam (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 124 of file events.c.
{ m_eventID = WeaponEventID.UNJAM; }
WeaponEventUnjammingFailedTimeout()
void WeaponEventBase::WeaponEventUnjammingFailedTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 136 of file events.c.
{ m_eventID = WeaponEventID.UNJAMMING_FAILED_TIMEOUT; }
WeaponEventUnjammingTimeout()
void WeaponEventBase::WeaponEventUnjammingTimeout (DayZPlayer p = NULL, Magazine m = NULL) inline private
Definition at line 142 of file events.c.
{ m_eventID = WeaponEventID.UNJAMMING_TIMEOUT; }
WriteToContext() [1/3]
void WeaponEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 54 of file events.c.
    {
        int packedType = GetPackedType();
        ctx.Write(packedType);
        ctx.Write(m_player);
        ctx.Write(m_magazine);
    }
References GetPackedType(), m_magazine, m_player, and Serializer::Write().
Referenced by Weapon::SyncEventToRemote().
WriteToContext() [2/3]
override void WeaponEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 158 of file events.c.
    {
        super.WriteToContext(ctx);
        m_dst.WriteToContext(ctx);
    }
References m_dst, and InventoryLocation::WriteToContext().
WriteToContext() [3/3]
override void WeaponEventBase::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 177 of file events.c.
    {
        super.WriteToContext(ctx);
        m_dst.WriteToContext(ctx);
    }
References m_dst, and InventoryLocation::WriteToContext().
Member Data Documentation
m_dst
ref InventoryLocation WeaponEventBase::m_dst private
Definition at line 149 of file events.c.
m_eventID
int WeaponEventBase::m_eventID private
Definition at line 36 of file events.c.
Referenced by GetEventID(), GetPackedType(), and WeaponEventBase().
m_magazine
Magazine WeaponEventBase::m_magazine private
Definition at line 38 of file events.c.
Referenced by DumpToString(), WeaponGuardBase::GuardCondition(), WeaponStateBase::OnEntry(), Weapon::SyncEventToRemote(), WeaponEventBase(), and WriteToContext().
m_player
DayZPlayer WeaponEventBase::m_player private
Definition at line 37 of file events.c.
Referenced by DumpToString(), WeaponGuardBase::GuardCondition(), WeaponStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), OnAbort(), WeaponStateBase::OnEntry(), WeaponStartAction::OnEntry(), WeaponFire::OnEntry(), OnEntry(), WeaponStateBase::OnExit(), Weapon::SyncEventToRemote(), WeaponEventBase(), and WriteToContext().
m_type
WeaponEvents WeaponEventBase::m_type private
Definition at line 217 of file events.c.