DayzKode: ActionMineBase Class Reference
ActionMineBase Class Reference
Private Member Functions
override ActionData CreateActionData ()
string GetYieldName (PlayerBase player, ActionTarget target, ItemBase item)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
Private Attributes
EHarvestType m_HarvestType = EHarvestType.NORMAL
Detailed Description
Definition at line 16 of file actionminetree.c.
Member Function Documentation
CreateActionData()
override ActionData ActionMineBase::CreateActionData () inline private
Definition at line 20 of file actionminetree.c.
    {
        MineActionData data = new MineActionData;
        data.m_HarvestType = m_HarvestType;
        return data;
    }
References MineActionData::m_HarvestType, and m_HarvestType.
GetYieldName()
string ActionMineBase::GetYieldName (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionminetree.c.
    {
        //given the circumstances, the implementation bellow is the path of least resistance
        Object targetObject = target.GetObject();
        WoodBase wood = WoodBase.Cast(targetObject);
        RockBase rock = RockBase.Cast(targetObject);
        string yieldName;
        if (wood || rock)
        {
            map<string,int> output_map = new map<string,int>;
            if (wood)
            {
                wood.GetMaterialAndQuantityMapEx(item, output_map, m_HarvestType);
            }
            else
            {
                rock.GetMaterialAndQuantityMap(item, output_map);
            }
            if (output_map.Count() > 0)
            {
                yieldName = MiscGameplayFunctions.GetItemDisplayName(output_map.GetKey(0));
            }
        }
        return yieldName;
    }
References RockBase::GetMaterialAndQuantityMap(), m_HarvestType, and WoodBase().
Referenced by OnActionInfoUpdate().
OnActionInfoUpdate()
override void ActionMineBase::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 27 of file actionminetree.c.
    {
        m_Text =  "#harvest" + " " + GetYieldName(player, target, item);
    }
References GetYieldName(), and m_Text.
Member Data Documentation
m_HarvestType
EHarvestType ActionMineBase::m_HarvestType = EHarvestType.NORMAL private
Definition at line 18 of file actionminetree.c.
Referenced by CreateActionData(), and GetYieldName().