DayzKode: ParticleList Class Reference
ParticleList Class Reference
Static Private Member Functions
static string GetParticleFullPath (int particle_id)
Returns particle's full path (with .ptc suffix) based on its ID.
static int GetParticleID (string particle_file)
Returns particle's ID based on the path (without .ptc suffix)
static int GetParticleIDByName (string name)
Returns particle's ID based on the filename (without .ptc suffix)
static string GetParticlePath (int particle_id)
Returns particle's full path (without .ptc suffix) based on its ID.
static string GetPathToParticles ()
Returns base path to all particles.
static int GetRegisteredParticlesCount ()
static bool IsValidId (int id)
Purely checks for an invalid number, does NOT mean it is actually registered.
static void PreloadParticles ()
Preloads all particles.
static int RegisterParticle (string file_name)
static int RegisterParticle (string root_path, string file_name)
Registers a particle and returns its ID.
Static Private Attributes
static const int AURORA_SANTA_WRECK = RegisterParticle("smoke_santa_wreck")
static const int BARBED_WIRE_SPARKS = RegisterParticle("electro_shortc2")
static const int BARREL_FIRE_END = RegisterParticle("fire_small_barrel_01_end")
static const int BARREL_FIRE_START = RegisterParticle("fire_small_barrel_01_start")
static const int BARREL_FIRE_STEAM_2END = RegisterParticle("steam_medium_camp_2end")
static const int BARREL_NORMAL_FIRE = RegisterParticle("fire_medium_barrel_01")
static const int BARREL_NORMAL_SMOKE = RegisterParticle("smoke_medium_barrel_01")
static const int BARREL_SMALL_FIRE = RegisterParticle("fire_small_barrel_01")
static const int BARREL_SMALL_SMOKE = RegisterParticle("smoke_small_barrel_01")
static const int BLEEDING_SOURCE = RegisterParticle("blood_bleeding_01")
static const int BLEEDING_SOURCE_LIGHT = RegisterParticle("blood_bleeding_02")
static const int BLOOD_SURFACE_CHUNKS = RegisterParticle("blood_surface_chunks")
static const int BLOOD_SURFACE_DROPS = RegisterParticle("blood_surface_drops")
static const int BONFIRE_FIRE = RegisterParticle("fire_bonfire")
static const int BONFIRE_SMOKE = RegisterParticle("smoke_bonfire")
static const int BREATH_VAPOUR_HEAVY = RegisterParticle("breath_vapour_heavy")
static const int BREATH_VAPOUR_LIGHT = RegisterParticle("breath_vapour_light")
static const int BREATH_VAPOUR_MEDIUM = RegisterParticle("breath_vapour_medium")
static const int BROOM_TORCH_T1 = RegisterParticle("fire_small_broom_torch_01")
static const int BROOM_TORCH_T2 = RegisterParticle("fire_small_broom_torch_02")
static const int BROOM_TORCH_T3 = RegisterParticle("fire_small_broom_torch_03")
static const int CAMP_FIRE_END = RegisterParticle("fire_small_camp_01_end")
static const int CAMP_FIRE_START = RegisterParticle("fire_small_camp_01_start")
static const int CAMP_NO_IGNITE_WIND = RegisterParticle("fire_extinguish_wind")
static const int CAMP_NORMAL_FIRE = RegisterParticle("fire_medium_camp_01")
static const int CAMP_NORMAL_SMOKE = RegisterParticle("smoke_medium_camp_01")
static const int CAMP_SMALL_FIRE = RegisterParticle("fire_small_camp_01")
static const int CAMP_SMALL_SMOKE = RegisterParticle("smoke_small_camp_01")
static const int CAMP_STEAM_2END = RegisterParticle("steam_medium_camp_2end")
static const int CAMP_STEAM_EXTINGUISH_START = RegisterParticle("default_01")
static const int CAMP_STOVE_FIRE = RegisterParticle("fire_small_stove_01")
static const int CAMP_STOVE_FIRE_END = RegisterParticle("fire_small_stove_01_end")
static const int CAMP_STOVE_FIRE_START = RegisterParticle("fire_small_stove_01_start")
static const int CLAYMORE_EXPLOSION = RegisterParticle("explosion_claymore_01")
static const int CONTAMINATED_AREA_GAS_AROUND = RegisterParticle("contaminated_area_gas_around")
static const int CONTAMINATED_AREA_GAS_BIGASS = RegisterParticle("contaminated_area_gas_bigass")
static const int CONTAMINATED_AREA_GAS_GROUND = RegisterParticle("contaminated_area_gas_ground")
static const int CONTAMINATED_AREA_GAS_SHELL = RegisterParticle("contaminated_area_gas_shell")
static const int CONTAMINATED_AREA_GAS_TINY = RegisterParticle("contaminated_area_gas_around_tiny")
static const int COOKING_BAKING_DONE = RegisterParticle("cooking_baking_done")
static const int COOKING_BAKING_START = RegisterParticle("cooking_baking_start")
static const int COOKING_BOILING_DONE = RegisterParticle("cooking_boiling_done")
static const int COOKING_BOILING_EMPTY = RegisterParticle("cooking_boiling_empty")
static const int COOKING_BOILING_START = RegisterParticle("cooking_boiling_start")
static const int COOKING_BURNING_DONE = RegisterParticle("cooking_burning_done")
static const int COOKING_DRYING_DONE = RegisterParticle("cooking_drying_done")
static const int COOKING_DRYING_START = RegisterParticle("cooking_drying_start")
static const int DEBUG_DOT = RegisterParticle("debug_dot")
static const int DIGGING_STASH = RegisterParticle("digging_ground")
static const int EASTER_EGG_ACTIVATE = RegisterParticle("easter_egg_activate")
static const int ENV_SWARMING_FLIES = RegisterParticle("env_fly_swarm_01")
static const int EVAPORATION = RegisterParticle("menu_evaporation")
static const int EXPLOSION_LANDMINE = RegisterParticle("explosion_landmine_01")
static const int EXPLOSION_TEST = RegisterParticle("explosion_placeholder")
static const int FIREWORKS_AFTERBURN_END = RegisterParticle("fireworks_small_03")
static const int FIREWORKS_AFTERBURN_START = RegisterParticle("fireworks_small_02")
static const int FIREWORKS_EXPLOSION_BLUE = RegisterParticle("fireworks_large_01_Blue")
static const int FIREWORKS_EXPLOSION_GREEN = RegisterParticle("fireworks_large_01_Green")
static const int FIREWORKS_EXPLOSION_PINK = RegisterParticle("fireworks_large_01_Pink")
static const int FIREWORKS_EXPLOSION_RED = RegisterParticle("fireworks_large_01_Red")
static const int FIREWORKS_EXPLOSION_YELLOW = RegisterParticle("fireworks_large_01_Yellow")
static const int FIREWORKS_FUSE = RegisterParticle("fireworks_small_04")
static const int FIREWORKS_SHOT = RegisterParticle("fireworks_small_01")
static const int FLAREPROJ_ACTIVATE = RegisterParticle("fire_small_flare_yellow_01")
static const int FLAREPROJ_ACTIVATE_BLUE = RegisterParticle("fire_small_flare_blue_01")
static const int FLAREPROJ_ACTIVATE_GREEN = RegisterParticle("fire_small_flare_green_01")
static const int FLAREPROJ_ACTIVATE_RED = RegisterParticle("fire_small_flare_red_01")
static const int FLAREPROJ_FIRE = RegisterParticle("fire_small_roadflare_red_04")
static const int GRENADE_CHEM_BREAK = RegisterParticle("contaminated_area_gas_grenade")
static const int GRENADE_M18_BLACK_END = RegisterParticle("smoke_M18_black_03")
static const int GRENADE_M18_BLACK_LOOP = RegisterParticle("smoke_M18_black_02")
static const int GRENADE_M18_BLACK_START = RegisterParticle("smoke_M18_black_01")
static const int GRENADE_M18_GREEN_END = RegisterParticle("smoke_M18_green_03")
static const int GRENADE_M18_GREEN_LOOP = RegisterParticle("smoke_M18_green_02")
static const int GRENADE_M18_GREEN_START = RegisterParticle("smoke_M18_green_01")
M18.
static const int GRENADE_M18_PURPLE_END = RegisterParticle("smoke_M18_purple_03")
static const int GRENADE_M18_PURPLE_LOOP = RegisterParticle("smoke_M18_purple_02")
static const int GRENADE_M18_PURPLE_START = RegisterParticle("smoke_M18_purple_01")
static const int GRENADE_M18_RED_END = RegisterParticle("smoke_M18_red_03")
static const int GRENADE_M18_RED_LOOP = RegisterParticle("smoke_M18_red_02")
static const int GRENADE_M18_RED_START = RegisterParticle("smoke_M18_red_01")
static const int GRENADE_M18_WHITE_END = RegisterParticle("smoke_M18_white_03")
static const int GRENADE_M18_WHITE_LOOP = RegisterParticle("smoke_M18_white_02")
static const int GRENADE_M18_WHITE_START = RegisterParticle("smoke_M18_white_01")
static const int GRENADE_M18_YELLOW_END = RegisterParticle("smoke_M18_yellow_03")
static const int GRENADE_M18_YELLOW_LOOP = RegisterParticle("smoke_M18_yellow_02")
static const int GRENADE_M18_YELLOW_START = RegisterParticle("smoke_M18_yellow_01")
static const int GRENADE_M84 = RegisterParticle("explosion_M84_01")
static const int GRENADE_RDG2_BLACK_END = RegisterParticle("smoke_RDG2_black_03")
static const int GRENADE_RDG2_BLACK_LOOP = RegisterParticle("smoke_RDG2_black_02")
static const int GRENADE_RDG2_BLACK_START = RegisterParticle("smoke_RDG2_black_01")
RDG2.
static const int GRENADE_RDG2_WHITE_END = RegisterParticle("smoke_RDG2_white_03")
static const int GRENADE_RDG2_WHITE_LOOP = RegisterParticle("smoke_RDG2_white_02")
static const int GRENADE_RDG2_WHITE_START = RegisterParticle("smoke_RDG2_white_01")
static const int GUN_AK101 = RegisterParticle("weapon_shot_ak101_01")
static const int GUN_AK74 = RegisterParticle("weapon_shot_ak74_01")
static const int GUN_AKM = RegisterParticle("weapon_shot_akm_01")
static const int GUN_AKM_SUPPRESSED = RegisterParticle("weapon_shot_akm_02")
static const int GUN_CZ527 = RegisterParticle("weapon_shot_cz527_01")
static const int GUN_CZ61 = RegisterParticle("weapon_shot_cz61_01")
static const int GUN_CZ75 = RegisterParticle("weapon_shot_cz75_01")
static const int GUN_FNX = RegisterParticle("weapon_shot_fnx_01")
static const int GUN_FNX_SUPPRESSED = RegisterParticle("weapon_shot_fnx_02")
static const int GUN_IZH18 = RegisterParticle("weapon_shot_izh18_01")
static const int GUN_IZH18_SUPPRESSED = RegisterParticle("weapon_shot_izh18_02")
static const int GUN_LONG_WINDED_SMOKE = RegisterParticle("weapon_shot_winded_smoke")
static const int GUN_LONG_WINDED_SMOKE_SMALL = RegisterParticle("weapon_shot_winded_smoke_small")
static const int GUN_M4A1 = RegisterParticle("weapon_shot_m4a1_01")
static const int GUN_MAGNUM = RegisterParticle("weapon_shot_magnum_01")
static const int GUN_MOSIN9130 = RegisterParticle("weapon_shot_mosin9130_01")
static const int GUN_MOSIN_COMPENSATOR = RegisterParticle("weapon_shot_mosin_compensator_01")
static const int GUN_MP133 = RegisterParticle("weapon_shot_mp133_01")
static const int GUN_MP5K = RegisterParticle("weapon_shot_mp5k_01")
static const int GUN_MP5K_2 = RegisterParticle("weapon_shot_mp5k_02_boris")
static const int GUN_MP5K_COMPENSATOR = RegisterParticle("weapon_shot_mp5k_02")
static const int GUN_MP5K_SUPPRESSED = RegisterParticle("weapon_shot_mp5k_02")
static const int GUN_MUZZLE_FLASH_SVD_STAR = RegisterParticle("weapon_shot_Flame_3D_4star")
static const int GUN_PARTICLE_CASING = RegisterParticle("weapon_shot_chamber_smoke")
static const int GUN_PARTICLE_CASING_RAISE = RegisterParticle("weapon_shot_chamber_smoke_raise")
static const int GUN_PARTICLE_TEST = RegisterParticle("weapon_shot_fnx_01")
static const int GUN_PELLETS = RegisterParticle("weapon_shot_pellets")
static const int GUN_SKS = RegisterParticle("weapon_shot_sks_01")
static const int GUN_SOLO_MUZZLE_FLASH = RegisterParticle("weapon_shot_Flame_3D")
static const int GUN_UMP45 = RegisterParticle("weapon_shot_ump45_01")
static const int GUN_VSS = RegisterParticle("weapon_shot_vss_01")
static const int GUN_WINCHESTER70 = RegisterParticle("weapon_shot_winch70_01")
static const int HATCHBACK_COOLANT_OVERHEATED = RegisterParticle("Hatchback_coolant_overheated")
static const int HATCHBACK_COOLANT_OVERHEATING = RegisterParticle("Hatchback_coolant_overheating")
static const int HATCHBACK_ENGINE_OVERHEATED = RegisterParticle("Hatchback_engine_failure")
static const int HATCHBACK_ENGINE_OVERHEATING = RegisterParticle("Hatchback_engine_failing")
static const int HATCHBACK_EXHAUST_SMOKE = RegisterParticle("Hatchback_exhaust")
static const int HOUSE_FIRE_END = RegisterParticle("fire_small_house_01_end")
static const int HOUSE_FIRE_START = RegisterParticle("fire_small_house_01_start")
static const int HOUSE_FIRE_STEAM_2END = RegisterParticle("steam_medium_house_2end")
static const int HOUSE_NORMAL_FIRE = RegisterParticle("fire_medium_house_01")
static const int HOUSE_NORMAL_SMOKE = RegisterParticle("smoke_medium_house_01")
static const int HOUSE_SMALL_FIRE = RegisterParticle("fire_small_house_01")
static const int HOUSE_SMALL_SMOKE = RegisterParticle("smoke_small_house_01")
static const int IMPACT_CONCRETE_ENTER = RegisterParticle("impacts/hit_concrete_ent_01")
static const int IMPACT_CONCRETE_EXIT = RegisterParticle("impacts/hit_concrete_ext_01")
static const int IMPACT_CONCRETE_RICOCHET = RegisterParticle("impacts/hit_concrete_ric_01")
static const int IMPACT_DIRT_ENTER = RegisterParticle("impacts/hit_dirt_ent_01")
static const int IMPACT_DIRT_EXIT = RegisterParticle("impacts/hit_dirt_ext_01")
static const int IMPACT_DIRT_RICOCHET = RegisterParticle("impacts/hit_dirt_ric_01")
static const int IMPACT_DISTANT_DUST = RegisterParticle("impacts/distant_dust")
static const int IMPACT_FOLIAGE_ENTER = RegisterParticle("impacts/hit_foliage_ent_01")
static const int IMPACT_FOLIAGE_EXIT = RegisterParticle("impacts/hit_foliage_ext_01")
static const int IMPACT_FOLIAGE_RICOCHET = RegisterParticle("impacts/hit_foliage_ric_01")
static const int IMPACT_GLASS_ENTER = RegisterParticle("impacts/hit_glass_ent_01")
static const int IMPACT_GLASS_EXIT = RegisterParticle("impacts/hit_glass_ext_01")
static const int IMPACT_GLASS_RICOCHET = RegisterParticle("impacts/hit_glass_ric_01")
static const int IMPACT_GRASS_ENTER = RegisterParticle("impacts/hit_grass_ent_01")
static const int IMPACT_GRASS_RICOCHET = RegisterParticle("impacts/hit_grass_ric_01")
static const int IMPACT_GRAVEL_ENTER = RegisterParticle("impacts/hit_gravel_ent_01")
static const int IMPACT_GRAVEL_EXIT = RegisterParticle("impacts/hit_gravel_ext_01")
static const int IMPACT_GRAVEL_RICOCHET = RegisterParticle("impacts/hit_gravel_ric_01")
static const int IMPACT_MEAT_ENTER = RegisterParticle("impacts/hit_meat_ent_01")
static const int IMPACT_MEAT_EXIT = RegisterParticle("impacts/hit_meat_ext_01")
static const int IMPACT_MEAT_RICOCHET = RegisterParticle("impacts/hit_meat_ric_01")
static const int IMPACT_MEATBONES_ENTER = RegisterParticle("impacts/hit_meatbones_ent_01")
static const int IMPACT_MEATBONES_EXIT = RegisterParticle("impacts/hit_meatbones_ext_01")
static const int IMPACT_MEATBONES_RICOCHET = RegisterParticle("impacts/hit_meatbones_ent_01")
static const int IMPACT_METAL_ENTER = RegisterParticle("impacts/hit_metal_ent_01")
static const int IMPACT_METAL_EXIT = RegisterParticle("impacts/hit_metal_ext_01")
static const int IMPACT_METAL_RICOCHET = RegisterParticle("impacts/hit_metal_ric_01")
static const int IMPACT_PLASTER_ENTER = RegisterParticle("impacts/hit_plaster_ent_01")
static const int IMPACT_PLASTER_EXIT = RegisterParticle("impacts/hit_plaster_ext_01")
static const int IMPACT_PLASTER_RICOCHET = RegisterParticle("impacts/hit_plaster_ric_01")
static const int IMPACT_PLASTIC_ENTER = RegisterParticle("impacts/hit_plastic_ent_01")
static const int IMPACT_PLASTIC_EXIT = RegisterParticle("impacts/hit_plastic_ext_01")
static const int IMPACT_PLASTIC_RICOCHET = RegisterParticle("impacts/hit_plastic_ric_01")
static const int IMPACT_RUBBER_ENTER = RegisterParticle("impacts/hit_rubber_ent_01")
static const int IMPACT_RUBBER_EXIT = RegisterParticle("impacts/hit_rubber_ext_01")
static const int IMPACT_RUBBER_RICOCHET = RegisterParticle("impacts/hit_rubber_ric_01")
static const int IMPACT_SAND_ENTER = RegisterParticle("impacts/hit_sand_ent_01")
static const int IMPACT_SAND_EXIT = RegisterParticle("impacts/hit_sand_ext_01")
static const int IMPACT_SAND_RICOCHET = RegisterParticle("impacts/hit_sand_ric_01")
static const int IMPACT_TEST = RegisterParticle("impacts/bullet_impact_placeholder")
static const int IMPACT_TEST2 = RegisterParticle("_test_orientation_02")
static const int IMPACT_TEST_ENTER_DEBUG = RegisterParticle("impacts/_test_impact_enter_debug")
static const int IMPACT_TEST_EXIT_DEBUG = RegisterParticle("impacts/_test_impact_exit_debug")
static const int IMPACT_TEST_NO_MATERIAL_ERROR = RegisterParticle("_test_no_material")
static const int IMPACT_TEST_RICOCHET = RegisterParticle("impacts/bullet_riochet_placeholder")
static const int IMPACT_TEST_RICOCHET_DEBUG = RegisterParticle("impacts/_test_impact_ricochet_debug")
static const int IMPACT_TEXTILE_ENTER = RegisterParticle("impacts/hit_textile_ent_01")
static const int IMPACT_TEXTILE_EXIT = RegisterParticle("impacts/hit_textile_ext_01")
static const int IMPACT_TEXTILE_RICOCHET = RegisterParticle("impacts/hit_textile_ric_01")
static const int IMPACT_WATER_LARGE_ENTER = RegisterParticle("impacts/hit_water_ent_03")
static const int IMPACT_WATER_MEDIUM_ENTER = RegisterParticle("impacts/hit_water_ent_02")
static const int IMPACT_WATER_SMALL_ENTER = RegisterParticle("impacts/hit_water_ent_01")
static const int IMPACT_WOOD_ENTER = RegisterParticle("impacts/hit_wood_ent_01")
static const int IMPACT_WOOD_EXIT = RegisterParticle("impacts/hit_wood_ext_01")
static const int IMPACT_WOOD_RICOCHET = RegisterParticle("impacts/hit_wood_ric_01")
static const int INVALID = -1
static const int M67 = RegisterParticle("explosion_M67_01")
static int m_lastID = 0
static ref map< string, int > m_ParticleNames
static ref map< int, string > m_ParticlePaths
static const int NONE = 0
static const int OVEN_FIRE_END = RegisterParticle("fire_small_ovenl_01_end")
static const int OVEN_FIRE_START = RegisterParticle("fire_small_oven_01_start")
static const int OVEN_NORMAL_FIRE = RegisterParticle("fire_medium_oven_01")
static const int OVEN_SMALL_FIRE = RegisterParticle("fire_small_oven_01")
static const int PARTICLE_TEST = RegisterParticle("_test_orientation")
static const int PLASTIC_EXPLOSION = RegisterParticle("explosion_plastic_01")
static const int POWER_GENERATOR_SMOKE = RegisterParticle("smoke_small_generator_01")
static const int RGD5 = RegisterParticle("explosion_RGD5_01")
static const int ROADFLARE_BURNING_ENDING = RegisterParticle("fire_small_roadflare_red_02")
static const int ROADFLARE_BURNING_INIT = RegisterParticle("fire_small_roadflare_red_04")
static const int ROADFLARE_BURNING_MAIN = RegisterParticle("fire_small_roadflare_red_01")
static const int ROADFLARE_BURNING_SMOKE = RegisterParticle("fire_small_roadflare_red_03")
static const int SMARKS_CHAMBER = RegisterParticle("weapon_shot_chamber_spark")
static const int SMOKE_GENERIC_WRECK = RegisterParticle("smoke_generic_wreck")
static const int SMOKING_BARREL = RegisterParticle("smoking_barrel")
static const int SMOKING_BARREL_HEAVY = RegisterParticle("smoking_barrel_heavy")
static const int SMOKING_BARREL_SMALL = RegisterParticle("smoking_barrel_small")
static const int SMOKING_BARREL_STEAM = RegisterParticle("smoking_barrel_steam")
static const int SMOKING_BARREL_STEAM_SMALL = RegisterParticle("smoking_barrel_steam_small")
static const int SMOKING_CAR_ENGINE = RegisterParticle("menu_engine_fire")
static const int SMOKING_HELI_WRECK = RegisterParticle("smoke_heli_wreck_01")
static const int SPOOKY_MIST = RegisterParticle("spooky_mist")
static const int TORCH_T1 = RegisterParticle("fire_small_torch_02")
static const int TORCH_T2 = RegisterParticle("fire_small_torch_03")
static const int TORCH_T3 = RegisterParticle("fire_small_torch_01")
static const int VOMIT = RegisterParticle("character_vomit_01")
static const int VOMIT_BLOOD = RegisterParticle("character_vomitBlood_01")
static const int VOMIT_CHUNKS = RegisterParticle("character_vomit_puddle")
static const int WATER_JET = RegisterParticle("water_jet")
static const int WATER_JET_WEAK = RegisterParticle("water_jet_weak")
static const int WATER_SPILLING = RegisterParticle("water_spilling")
Detailed Description
Definition at line 11 of file particlelist.c.
Member Function Documentation
GetParticleFullPath()
static string ParticleList::GetParticleFullPath (int particle_id) inline static private
Returns particle's full path (with .ptc suffix) based on its ID.
Definition at line 384 of file particlelist.c.
    {
        return string.Format("%1.ptc", GetParticlePath(particle_id));
    }
References string::Format(), GetParticlePath(), and particle_id.
Referenced by CreateParticleById(), Particle::CreateParticleEffect(), CreateParticleEx(), ParticleSource::CreateParticleEx(), CreateParticlesById(), CreateParticlesByIdArr(), PlayParticleById(), PlayParticlesById(), ParticleSource::SetParticleByID(), and TestOwnership().
GetParticleID()
static int ParticleList::GetParticleID (string particle_file) inline static private
Returns particle's ID based on the path (without .ptc suffix)
Definition at line 390 of file particlelist.c.
    {
        int id = m_ParticlePaths.GetKeyByValue(particle_file);
        if (!IsValidId(id)) // valid id starts from 1, 0 is invalid
            ErrorEx(string.Format("No particle registered with path: %1", particle_file), ErrorExSeverity.WARNING);
        return id;
    }
References ErrorEx, IsValidId(), and m_ParticlePaths.
Referenced by EffectAreaLoader::CreateZones(), and ParticleSource::GetParticleIDLegacy().
GetParticleIDByName()
static int ParticleList::GetParticleIDByName (string name) inline static private
Returns particle's ID based on the filename (without .ptc suffix)
Definition at line 399 of file particlelist.c.
    {
        int id = 0;
        if (!m_ParticleNames.Find(name, id))
            ErrorEx(string.Format("No particle registered with name: %1", name), ErrorExSeverity.WARNING);
        return id;
    }
References ErrorEx, m_ParticleNames, and name.
Referenced by WeaponParticlesBase::CheckParticleOverride(), AmmoEffects::GetAmmoParticleID(), ParticleSource::GetParticleID(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), and WeaponParticlesBase::WeaponParticlesBase().
GetParticlePath()
static string ParticleList::GetParticlePath (int particle_id) inline static private
Returns particle's full path (without .ptc suffix) based on its ID.
Definition at line 375 of file particlelist.c.
    {
        string path;
        if (!m_ParticlePaths.Find(particle_id, path))
            ErrorEx(string.Format("No particle registered with id: %1", particle_id), ErrorExSeverity.WARNING);
        return path;
    }
References ErrorEx, m_ParticlePaths, particle_id, and path.
Referenced by GetParticleFullPath().
GetPathToParticles()
static string ParticleList::GetPathToParticles () inline static private
Returns base path to all particles.
Definition at line 408 of file particlelist.c.
    {
        return "graphics/particles/";
    }
Referenced by ItemBase::ParticleTest(), and RegisterParticle().
GetRegisteredParticlesCount()
static int ParticleList::GetRegisteredParticlesCount () inline static private
Definition at line 363 of file particlelist.c.
    {
        return m_lastID;
    }
References m_lastID.
IsValidId()
static bool ParticleList::IsValidId (int id) inline static private
Purely checks for an invalid number, does NOT mean it is actually registered.
Definition at line 369 of file particlelist.c.
    {
        return id != NONE && id != INVALID;
    }
References INVALID, and NONE.
Referenced by GetParticleID(), WeaponParticlesBase::OnActivate(), and AmmoEffects::PlayAmmoParticle().
PreloadParticles()
static void ParticleList::PreloadParticles () inline static private
Preloads all particles.
Definition at line 414 of file particlelist.c.
    {
        if ( !GetGame().IsServer() || !GetGame().IsMultiplayer() ) // client side
        {
            int count = m_ParticlePaths.Count();
            for (int i = 0; i < count; ++i)
            {
                vobject vobj = GetObject( string.Format("%1.ptc", m_ParticlePaths[i]) );
                ReleaseObject(vobj);
            }
        }
    }
References GetGame(), GetObject(), m_ParticlePaths, and ReleaseObject().
Referenced by OnInitialize().
RegisterParticle() [1/2]
static int ParticleList::RegisterParticle (string file_name) inline static private
Definition at line 306 of file particlelist.c.
    {
        return RegisterParticle(GetPathToParticles(), file_name);
    }
References GetPathToParticles(), and RegisterParticle().
Referenced by RegisterParticle().
RegisterParticle() [2/2]
static int ParticleList::RegisterParticle (string root_path, string file_name) inline static private
Registers a particle and returns its ID.
Definition at line 312 of file particlelist.c.
    {
        if (!m_ParticlePaths)
            m_ParticlePaths = new map<int, string>;
        if (!m_ParticleNames)
            m_ParticleNames = new map<string, int>;
        string path = string.Format("%1%2", root_path, file_name);
        string fullPath = string.Format("%1.ptc", path);
        if ( !FileExist(fullPath) )
        {
            string devMsgSuffix;
            #ifdef DEVELOPER
            devMsgSuffix = " Then rebuild 'scripts' and 'graphics' PBOs.";
            #endif
            ErrorEx(string.Format("Particle file not found! <%1> Correct path to this particle in script file ParticleList.c!%2",
                fullPath, devMsgSuffix), ErrorExSeverity.WARNING);
        }
        int existingNameId;
        if (m_ParticleNames.Find(file_name, existingNameId))
        {
            int existingPathId;
            if (m_ParticlePaths.GetKeyByValueChecked(path, existingPathId))
            {
                if (existingNameId == existingPathId)
                {
                    return existingNameId; // We have already registered this exact file
                }
                else
                {
                    ErrorEx(string.Format("ParticleNames and ParticlePaths array are containing conflicting data. ID %1 vs ID %2", existingNameId, existingPathId));
                }
            }
            else
            {
                ErrorEx(string.Format("Duplicate particle filename: %1; GetParticleIDByName will only work with the first path if there are two different paths.", file_name), ErrorExSeverity.WARNING);
            }
        }
        else
        {
            m_ParticleNames.Insert(file_name, m_lastID + 1);
        }
        ++m_lastID;
        m_ParticlePaths.Insert(m_lastID, path);
        return m_lastID;
    }
References ErrorEx, FileExist(), string::Format(), m_lastID, m_ParticleNames, m_ParticlePaths, and path.
Member Data Documentation
AURORA_SANTA_WRECK
const int ParticleList::AURORA_SANTA_WRECK = RegisterParticle("smoke_santa_wreck") static private
Definition at line 254 of file particlelist.c.
Referenced by CrashBase::Wreck_SantasSleigh().
BARBED_WIRE_SPARKS
const int ParticleList::BARBED_WIRE_SPARKS = RegisterParticle("electro_shortc2") static private
Definition at line 135 of file particlelist.c.
Referenced by ItemBase::Spark().
BARREL_FIRE_END
const int ParticleList::BARREL_FIRE_END = RegisterParticle("fire_small_barrel_01_end") static private
Definition at line 53 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BARREL_FIRE_START
const int ParticleList::BARREL_FIRE_START = RegisterParticle("fire_small_barrel_01_start") static private
Definition at line 48 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BARREL_FIRE_STEAM_2END
const int ParticleList::BARREL_FIRE_STEAM_2END = RegisterParticle("steam_medium_camp_2end") static private
Definition at line 54 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), and FireplaceBase::OvenIndoor().
BARREL_NORMAL_FIRE
const int ParticleList::BARREL_NORMAL_FIRE = RegisterParticle("fire_medium_barrel_01") static private
Definition at line 51 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BARREL_NORMAL_SMOKE
const int ParticleList::BARREL_NORMAL_SMOKE = RegisterParticle("smoke_medium_barrel_01") static private
Definition at line 52 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BARREL_SMALL_FIRE
const int ParticleList::BARREL_SMALL_FIRE = RegisterParticle("fire_small_barrel_01") static private
Definition at line 49 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BARREL_SMALL_SMOKE
const int ParticleList::BARREL_SMALL_SMOKE = RegisterParticle("smoke_small_barrel_01") static private
Definition at line 50 of file particlelist.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase().
BLEEDING_SOURCE
const int ParticleList::BLEEDING_SOURCE = RegisterParticle("blood_bleeding_01") static private
Definition at line 139 of file particlelist.c.
Referenced by BleedingSourceEffect::BleedingSourceEffect().
BLEEDING_SOURCE_LIGHT
const int ParticleList::BLEEDING_SOURCE_LIGHT = RegisterParticle("blood_bleeding_02") static private
Definition at line 140 of file particlelist.c.
Referenced by BleedingSourceEffect().
BLOOD_SURFACE_CHUNKS
const int ParticleList::BLOOD_SURFACE_CHUNKS = RegisterParticle("blood_surface_chunks") static private
Definition at line 142 of file particlelist.c.
Referenced by Hit_MeatBones::BloodSplatGround().
BLOOD_SURFACE_DROPS
const int ParticleList::BLOOD_SURFACE_DROPS = RegisterParticle("blood_surface_drops") static private
Definition at line 141 of file particlelist.c.
Referenced by BloodSplatter::BloodSplatter().
BONFIRE_FIRE
const int ParticleList::BONFIRE_FIRE = RegisterParticle("fire_bonfire") static private
Definition at line 270 of file particlelist.c.
Referenced by BuildingSuper::EEInit().
BONFIRE_SMOKE
const int ParticleList::BONFIRE_SMOKE = RegisterParticle("smoke_bonfire") static private
Definition at line 271 of file particlelist.c.
Referenced by BuildingSuper::EEInit().
BREATH_VAPOUR_HEAVY
const int ParticleList::BREATH_VAPOUR_HEAVY = RegisterParticle("breath_vapour_heavy") static private
Definition at line 146 of file particlelist.c.
Referenced by EffBreathVapourHeavy::EffBreathVapourHeavy(), and ManBase::SpawnBreathVaporEffect().
BREATH_VAPOUR_LIGHT
const int ParticleList::BREATH_VAPOUR_LIGHT = RegisterParticle("breath_vapour_light") static private
Definition at line 144 of file particlelist.c.
Referenced by EffBreathVapourLight::EffBreathVapourLight(), and ManBase::SpawnBreathVaporEffect().
BREATH_VAPOUR_MEDIUM
const int ParticleList::BREATH_VAPOUR_MEDIUM = RegisterParticle("breath_vapour_medium") static private
Definition at line 145 of file particlelist.c.
Referenced by EffBreathVapourMedium::EffBreathVapourMedium(), and ManBase::SpawnBreathVaporEffect().
BROOM_TORCH_T1
const int ParticleList::BROOM_TORCH_T1 = RegisterParticle("fire_small_broom_torch_01") static private
Definition at line 77 of file particlelist.c.
Referenced by BroomBase::UpdateParticle().
BROOM_TORCH_T2
const int ParticleList::BROOM_TORCH_T2 = RegisterParticle("fire_small_broom_torch_02") static private
Definition at line 78 of file particlelist.c.
BROOM_TORCH_T3
const int ParticleList::BROOM_TORCH_T3 = RegisterParticle("fire_small_broom_torch_03") static private
Definition at line 79 of file particlelist.c.
CAMP_FIRE_END
const int ParticleList::CAMP_FIRE_END = RegisterParticle("fire_small_camp_01_end") static private
Definition at line 32 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_FIRE_START
const int ParticleList::CAMP_FIRE_START = RegisterParticle("fire_small_camp_01_start") static private
Definition at line 27 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_NO_IGNITE_WIND
const int ParticleList::CAMP_NO_IGNITE_WIND = RegisterParticle("fire_extinguish_wind") static private
Definition at line 38 of file particlelist.c.
CAMP_NORMAL_FIRE
const int ParticleList::CAMP_NORMAL_FIRE = RegisterParticle("fire_medium_camp_01") static private
Definition at line 29 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_NORMAL_SMOKE
const int ParticleList::CAMP_NORMAL_SMOKE = RegisterParticle("smoke_medium_camp_01") static private
Definition at line 31 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_SMALL_FIRE
const int ParticleList::CAMP_SMALL_FIRE = RegisterParticle("fire_small_camp_01") static private
Definition at line 28 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_SMALL_SMOKE
const int ParticleList::CAMP_SMALL_SMOKE = RegisterParticle("smoke_small_camp_01") static private
Definition at line 30 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_STEAM_2END
const int ParticleList::CAMP_STEAM_2END = RegisterParticle("steam_medium_camp_2end") static private
Definition at line 33 of file particlelist.c.
Referenced by FireplaceBase::Fireplace().
CAMP_STEAM_EXTINGUISH_START
const int ParticleList::CAMP_STEAM_EXTINGUISH_START = RegisterParticle("default_01") static private
Definition at line 34 of file particlelist.c.
CAMP_STOVE_FIRE
const int ParticleList::CAMP_STOVE_FIRE = RegisterParticle("fire_small_stove_01") static private
Definition at line 35 of file particlelist.c.
CAMP_STOVE_FIRE_END
const int ParticleList::CAMP_STOVE_FIRE_END = RegisterParticle("fire_small_stove_01_end") static private
Definition at line 37 of file particlelist.c.
CAMP_STOVE_FIRE_START
const int ParticleList::CAMP_STOVE_FIRE_START = RegisterParticle("fire_small_stove_01_start") static private
Definition at line 36 of file particlelist.c.
CLAYMORE_EXPLOSION
const int ParticleList::CLAYMORE_EXPLOSION = RegisterParticle("explosion_claymore_01") static private
Definition at line 297 of file particlelist.c.
Referenced by ClaymoreMine::ClaymoreMine().
CONTAMINATED_AREA_GAS_AROUND
const int ParticleList::CONTAMINATED_AREA_GAS_AROUND = RegisterParticle("contaminated_area_gas_around") static private
Definition at line 278 of file particlelist.c.
Referenced by ContaminatedArea_Local::SetupZoneData().
CONTAMINATED_AREA_GAS_BIGASS
const int ParticleList::CONTAMINATED_AREA_GAS_BIGASS = RegisterParticle("contaminated_area_gas_bigass") static private
Definition at line 279 of file particlelist.c.
CONTAMINATED_AREA_GAS_GROUND
const int ParticleList::CONTAMINATED_AREA_GAS_GROUND = RegisterParticle("contaminated_area_gas_ground") static private
Definition at line 280 of file particlelist.c.
CONTAMINATED_AREA_GAS_SHELL
const int ParticleList::CONTAMINATED_AREA_GAS_SHELL = RegisterParticle("contaminated_area_gas_shell") static private
Definition at line 281 of file particlelist.c.
Referenced by OnRPC().
CONTAMINATED_AREA_GAS_TINY
const int ParticleList::CONTAMINATED_AREA_GAS_TINY = RegisterParticle("contaminated_area_gas_around_tiny") static private
Definition at line 277 of file particlelist.c.
COOKING_BAKING_DONE
const int ParticleList::COOKING_BAKING_DONE = RegisterParticle("cooking_baking_done") static private
Definition at line 66 of file particlelist.c.
COOKING_BAKING_START
const int ParticleList::COOKING_BAKING_START = RegisterParticle("cooking_baking_start") static private
Definition at line 65 of file particlelist.c.
COOKING_BOILING_DONE
const int ParticleList::COOKING_BOILING_DONE = RegisterParticle("cooking_boiling_done") static private
Definition at line 64 of file particlelist.c.
COOKING_BOILING_EMPTY
const int ParticleList::COOKING_BOILING_EMPTY = RegisterParticle("cooking_boiling_empty") static private
Definition at line 62 of file particlelist.c.
COOKING_BOILING_START
const int ParticleList::COOKING_BOILING_START = RegisterParticle("cooking_boiling_start") static private
Definition at line 63 of file particlelist.c.
COOKING_BURNING_DONE
const int ParticleList::COOKING_BURNING_DONE = RegisterParticle("cooking_burning_done") static private
Definition at line 69 of file particlelist.c.
COOKING_DRYING_DONE
const int ParticleList::COOKING_DRYING_DONE = RegisterParticle("cooking_drying_done") static private
Definition at line 68 of file particlelist.c.
COOKING_DRYING_START
const int ParticleList::COOKING_DRYING_START = RegisterParticle("cooking_drying_start") static private
Definition at line 67 of file particlelist.c.
DEBUG_DOT
const int ParticleList::DEBUG_DOT = RegisterParticle("debug_dot") static private
Definition at line 23 of file particlelist.c.
Referenced by ItemBase::DoMeasurement(), EntityLightSource::HandleDancingShadows(), and ItemBase::ParticleTest().
DIGGING_STASH
const int ParticleList::DIGGING_STASH = RegisterParticle("digging_ground") static private
Definition at line 95 of file particlelist.c.
Referenced by ActionDigInStash::SpawnParticleShovelRaise(), and SpawnParticleShovelRaise().
EASTER_EGG_ACTIVATE
const int ParticleList::EASTER_EGG_ACTIVATE = RegisterParticle("easter_egg_activate") static private
Definition at line 136 of file particlelist.c.
Referenced by PlayVFX().
ENV_SWARMING_FLIES
const int ParticleList::ENV_SWARMING_FLIES = RegisterParticle("env_fly_swarm_01") static private
Definition at line 267 of file particlelist.c.
Referenced by EffSwarmingFlies::EffSwarmingFlies().
EVAPORATION
const int ParticleList::EVAPORATION = RegisterParticle("menu_evaporation") static private
Definition at line 257 of file particlelist.c.
Referenced by MenuEvaporation::MenuEvaporation().
EXPLOSION_LANDMINE
const int ParticleList::EXPLOSION_LANDMINE = RegisterParticle("explosion_landmine_01") static private
Definition at line 249 of file particlelist.c.
Referenced by ExplosionEffects(), LandmineExplosion::LandmineExplosion(), FuelStation::OnExplosionEffects(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), TestOwnership(), and PMTPlayback::TestStopping().
EXPLOSION_TEST
const int ParticleList::EXPLOSION_TEST = RegisterParticle("explosion_placeholder") static private
Definition at line 250 of file particlelist.c.
FIREWORKS_AFTERBURN_END
const int ParticleList::FIREWORKS_AFTERBURN_END = RegisterParticle("fireworks_small_03") static private
Definition at line 293 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::OnFired().
FIREWORKS_AFTERBURN_START
const int ParticleList::FIREWORKS_AFTERBURN_START = RegisterParticle("fireworks_small_02") static private
Definition at line 292 of file particlelist.c.
FIREWORKS_EXPLOSION_BLUE
const int ParticleList::FIREWORKS_EXPLOSION_BLUE = RegisterParticle("fireworks_large_01_Blue") static private
Definition at line 287 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::GetExplParticleFromSequence().
FIREWORKS_EXPLOSION_GREEN
const int ParticleList::FIREWORKS_EXPLOSION_GREEN = RegisterParticle("fireworks_large_01_Green") static private
Definition at line 286 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::GetExplParticleFromSequence().
FIREWORKS_EXPLOSION_PINK
const int ParticleList::FIREWORKS_EXPLOSION_PINK = RegisterParticle("fireworks_large_01_Pink") static private
Definition at line 289 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::GetExplParticleFromSequence().
FIREWORKS_EXPLOSION_RED
const int ParticleList::FIREWORKS_EXPLOSION_RED = RegisterParticle("fireworks_large_01_Red") static private
Definition at line 285 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::GetExplParticleFromSequence().
FIREWORKS_EXPLOSION_YELLOW
const int ParticleList::FIREWORKS_EXPLOSION_YELLOW = RegisterParticle("fireworks_large_01_Yellow") static private
Definition at line 288 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::GetExplParticleFromSequence().
FIREWORKS_FUSE
const int ParticleList::FIREWORKS_FUSE = RegisterParticle("fireworks_small_04") static private
Definition at line 291 of file particlelist.c.
Referenced by FireworksLauncher::OnFuseIgnitedClient().
FIREWORKS_SHOT
const int ParticleList::FIREWORKS_SHOT = RegisterParticle("fireworks_small_01") static private
Definition at line 284 of file particlelist.c.
Referenced by FireworksLauncherClientEvent::OnFired().
FLAREPROJ_ACTIVATE
const int ParticleList::FLAREPROJ_ACTIVATE = RegisterParticle("fire_small_flare_yellow_01") static private
Definition at line 89 of file particlelist.c.
Referenced by FlareSimulation::FlareSimulation().
FLAREPROJ_ACTIVATE_BLUE
const int ParticleList::FLAREPROJ_ACTIVATE_BLUE = RegisterParticle("fire_small_flare_blue_01") static private
Definition at line 92 of file particlelist.c.
FLAREPROJ_ACTIVATE_GREEN
const int ParticleList::FLAREPROJ_ACTIVATE_GREEN = RegisterParticle("fire_small_flare_green_01") static private
Definition at line 91 of file particlelist.c.
FLAREPROJ_ACTIVATE_RED
const int ParticleList::FLAREPROJ_ACTIVATE_RED = RegisterParticle("fire_small_flare_red_01") static private
Definition at line 90 of file particlelist.c.
Referenced by DynamicArea_Flare::DynamicArea_Flare().
FLAREPROJ_FIRE
const int ParticleList::FLAREPROJ_FIRE = RegisterParticle("fire_small_roadflare_red_04") static private
Definition at line 88 of file particlelist.c.
GRENADE_CHEM_BREAK
const int ParticleList::GRENADE_CHEM_BREAK = RegisterParticle("contaminated_area_gas_grenade") static private
Definition at line 295 of file particlelist.c.
Referenced by Grenade_ChemGas::OnDamageDestroyed().
GRENADE_M18_BLACK_END
const int ParticleList::GRENADE_M18_BLACK_END = RegisterParticle("smoke_M18_black_03") static private
Definition at line 123 of file particlelist.c.
GRENADE_M18_BLACK_LOOP
const int ParticleList::GRENADE_M18_BLACK_LOOP = RegisterParticle("smoke_M18_black_02") static private
Definition at line 122 of file particlelist.c.
GRENADE_M18_BLACK_START
const int ParticleList::GRENADE_M18_BLACK_START = RegisterParticle("smoke_M18_black_01") static private
Definition at line 121 of file particlelist.c.
GRENADE_M18_GREEN_END
const int ParticleList::GRENADE_M18_GREEN_END = RegisterParticle("smoke_M18_green_03") static private
Definition at line 108 of file particlelist.c.
Referenced by OnWorkStop().
GRENADE_M18_GREEN_LOOP
const int ParticleList::GRENADE_M18_GREEN_LOOP = RegisterParticle("smoke_M18_green_02") static private
Definition at line 107 of file particlelist.c.
Referenced by OnWorkStop(), and SmokeSimulation_Green::SmokeSimulation_Green().
GRENADE_M18_GREEN_START
const int ParticleList::GRENADE_M18_GREEN_START = RegisterParticle("smoke_M18_green_01") static private
M18.
Definition at line 106 of file particlelist.c.
Referenced by OnWorkStop().
GRENADE_M18_PURPLE_END
const int ParticleList::GRENADE_M18_PURPLE_END = RegisterParticle("smoke_M18_purple_03") static private
Definition at line 111 of file particlelist.c.
Referenced by M18SmokeGrenade_Yellow().
GRENADE_M18_PURPLE_LOOP
const int ParticleList::GRENADE_M18_PURPLE_LOOP = RegisterParticle("smoke_M18_purple_02") static private
Definition at line 110 of file particlelist.c.
Referenced by M18SmokeGrenade_Yellow(), and SmokeSimulation::SmokeSimulation().
GRENADE_M18_PURPLE_START
const int ParticleList::GRENADE_M18_PURPLE_START = RegisterParticle("smoke_M18_purple_01") static private
Definition at line 109 of file particlelist.c.
Referenced by M18SmokeGrenade_Yellow().
GRENADE_M18_RED_END
const int ParticleList::GRENADE_M18_RED_END = RegisterParticle("smoke_M18_red_03") static private
Definition at line 114 of file particlelist.c.
GRENADE_M18_RED_LOOP
const int ParticleList::GRENADE_M18_RED_LOOP = RegisterParticle("smoke_M18_red_02") static private
Definition at line 113 of file particlelist.c.
Referenced by SmokeSimulation_White().
GRENADE_M18_RED_START
const int ParticleList::GRENADE_M18_RED_START = RegisterParticle("smoke_M18_red_01") static private
Definition at line 112 of file particlelist.c.
GRENADE_M18_WHITE_END
const int ParticleList::GRENADE_M18_WHITE_END = RegisterParticle("smoke_M18_white_03") static private
Definition at line 117 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White().
GRENADE_M18_WHITE_LOOP
const int ParticleList::GRENADE_M18_WHITE_LOOP = RegisterParticle("smoke_M18_white_02") static private
Definition at line 116 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White().
GRENADE_M18_WHITE_START
const int ParticleList::GRENADE_M18_WHITE_START = RegisterParticle("smoke_M18_white_01") static private
Definition at line 115 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_White().
GRENADE_M18_YELLOW_END
const int ParticleList::GRENADE_M18_YELLOW_END = RegisterParticle("smoke_M18_yellow_03") static private
Definition at line 120 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow().
GRENADE_M18_YELLOW_LOOP
const int ParticleList::GRENADE_M18_YELLOW_LOOP = RegisterParticle("smoke_M18_yellow_02") static private
Definition at line 119 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow().
GRENADE_M18_YELLOW_START
const int ParticleList::GRENADE_M18_YELLOW_START = RegisterParticle("smoke_M18_yellow_01") static private
Definition at line 118 of file particlelist.c.
Referenced by M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow().
GRENADE_M84
const int ParticleList::GRENADE_M84 = RegisterParticle("explosion_M84_01") static private
FLASH GRENADE M84
Definition at line 127 of file particlelist.c.
Referenced by Grenade_Base::FlashGrenade().
GRENADE_RDG2_BLACK_END
const int ParticleList::GRENADE_RDG2_BLACK_END = RegisterParticle("smoke_RDG2_black_03") static private
Definition at line 101 of file particlelist.c.
Referenced by RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black().
GRENADE_RDG2_BLACK_LOOP
const int ParticleList::GRENADE_RDG2_BLACK_LOOP = RegisterParticle("smoke_RDG2_black_02") static private
Definition at line 100 of file particlelist.c.
Referenced by RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black().
GRENADE_RDG2_BLACK_START
const int ParticleList::GRENADE_RDG2_BLACK_START = RegisterParticle("smoke_RDG2_black_01") static private
RDG2.
Definition at line 99 of file particlelist.c.
Referenced by RDG2SmokeGrenade_ColorBase::RDG2SmokeGrenade_Black().
GRENADE_RDG2_WHITE_END
const int ParticleList::GRENADE_RDG2_WHITE_END = RegisterParticle("smoke_RDG2_white_03") static private
Definition at line 104 of file particlelist.c.
Referenced by RDG2SmokeGrenade_Black().
GRENADE_RDG2_WHITE_LOOP
const int ParticleList::GRENADE_RDG2_WHITE_LOOP = RegisterParticle("smoke_RDG2_white_02") static private
Definition at line 103 of file particlelist.c.
Referenced by RDG2SmokeGrenade_Black().
GRENADE_RDG2_WHITE_START
const int ParticleList::GRENADE_RDG2_WHITE_START = RegisterParticle("smoke_RDG2_white_01") static private
Definition at line 102 of file particlelist.c.
Referenced by RDG2SmokeGrenade_Black().
GUN_AK101
const int ParticleList::GUN_AK101 = RegisterParticle("weapon_shot_ak101_01") static private
Definition at line 177 of file particlelist.c.
GUN_AK74
const int ParticleList::GUN_AK74 = RegisterParticle("weapon_shot_ak74_01") static private
Definition at line 176 of file particlelist.c.
GUN_AKM
const int ParticleList::GUN_AKM = RegisterParticle("weapon_shot_akm_01") static private
Definition at line 158 of file particlelist.c.
GUN_AKM_SUPPRESSED
const int ParticleList::GUN_AKM_SUPPRESSED = RegisterParticle("weapon_shot_akm_02") static private
Definition at line 159 of file particlelist.c.
GUN_CZ527
const int ParticleList::GUN_CZ527 = RegisterParticle("weapon_shot_cz527_01") static private
Definition at line 172 of file particlelist.c.
GUN_CZ61
const int ParticleList::GUN_CZ61 = RegisterParticle("weapon_shot_cz61_01") static private
Definition at line 181 of file particlelist.c.
GUN_CZ75
const int ParticleList::GUN_CZ75 = RegisterParticle("weapon_shot_cz75_01") static private
Definition at line 157 of file particlelist.c.
GUN_FNX
const int ParticleList::GUN_FNX = RegisterParticle("weapon_shot_fnx_01") static private
Definition at line 152 of file particlelist.c.
GUN_FNX_SUPPRESSED
const int ParticleList::GUN_FNX_SUPPRESSED = RegisterParticle("weapon_shot_fnx_02") static private
Definition at line 153 of file particlelist.c.
GUN_IZH18
const int ParticleList::GUN_IZH18 = RegisterParticle("weapon_shot_izh18_01") static private
Definition at line 160 of file particlelist.c.
GUN_IZH18_SUPPRESSED
const int ParticleList::GUN_IZH18_SUPPRESSED = RegisterParticle("weapon_shot_izh18_02") static private
Definition at line 161 of file particlelist.c.
GUN_LONG_WINDED_SMOKE
const int ParticleList::GUN_LONG_WINDED_SMOKE = RegisterParticle("weapon_shot_winded_smoke") static private
Definition at line 182 of file particlelist.c.
GUN_LONG_WINDED_SMOKE_SMALL
const int ParticleList::GUN_LONG_WINDED_SMOKE_SMALL = RegisterParticle("weapon_shot_winded_smoke_small") static private
Definition at line 183 of file particlelist.c.
GUN_M4A1
const int ParticleList::GUN_M4A1 = RegisterParticle("weapon_shot_m4a1_01") static private
Definition at line 167 of file particlelist.c.
GUN_MAGNUM
const int ParticleList::GUN_MAGNUM = RegisterParticle("weapon_shot_magnum_01") static private
Definition at line 179 of file particlelist.c.
GUN_MOSIN9130
const int ParticleList::GUN_MOSIN9130 = RegisterParticle("weapon_shot_mosin9130_01") static private
Definition at line 170 of file particlelist.c.
GUN_MOSIN_COMPENSATOR
const int ParticleList::GUN_MOSIN_COMPENSATOR = RegisterParticle("weapon_shot_mosin_compensator_01") static private
Definition at line 171 of file particlelist.c.
GUN_MP133
const int ParticleList::GUN_MP133 = RegisterParticle("weapon_shot_mp133_01") static private
Definition at line 168 of file particlelist.c.
GUN_MP5K
const int ParticleList::GUN_MP5K = RegisterParticle("weapon_shot_mp5k_01") static private
Definition at line 162 of file particlelist.c.
GUN_MP5K_2
const int ParticleList::GUN_MP5K_2 = RegisterParticle("weapon_shot_mp5k_02_boris") static private
Definition at line 163 of file particlelist.c.
GUN_MP5K_COMPENSATOR
const int ParticleList::GUN_MP5K_COMPENSATOR = RegisterParticle("weapon_shot_mp5k_02") static private
Definition at line 165 of file particlelist.c.
GUN_MP5K_SUPPRESSED
const int ParticleList::GUN_MP5K_SUPPRESSED = RegisterParticle("weapon_shot_mp5k_02") static private
Definition at line 164 of file particlelist.c.
GUN_MUZZLE_FLASH_SVD_STAR
const int ParticleList::GUN_MUZZLE_FLASH_SVD_STAR = RegisterParticle("weapon_shot_Flame_3D_4star") static private
Definition at line 150 of file particlelist.c.
GUN_PARTICLE_CASING
const int ParticleList::GUN_PARTICLE_CASING = RegisterParticle("weapon_shot_chamber_smoke") static private
Definition at line 155 of file particlelist.c.
GUN_PARTICLE_CASING_RAISE
const int ParticleList::GUN_PARTICLE_CASING_RAISE = RegisterParticle("weapon_shot_chamber_smoke_raise") static private
Definition at line 156 of file particlelist.c.
GUN_PARTICLE_TEST
const int ParticleList::GUN_PARTICLE_TEST = RegisterParticle("weapon_shot_fnx_01") static private
Definition at line 154 of file particlelist.c.
GUN_PELLETS
const int ParticleList::GUN_PELLETS = RegisterParticle("weapon_shot_pellets") static private
Definition at line 169 of file particlelist.c.
GUN_SKS
const int ParticleList::GUN_SKS = RegisterParticle("weapon_shot_sks_01") static private
Definition at line 173 of file particlelist.c.
GUN_SOLO_MUZZLE_FLASH
const int ParticleList::GUN_SOLO_MUZZLE_FLASH = RegisterParticle("weapon_shot_Flame_3D") static private
Definition at line 151 of file particlelist.c.
GUN_UMP45
const int ParticleList::GUN_UMP45 = RegisterParticle("weapon_shot_ump45_01") static private
Definition at line 166 of file particlelist.c.
GUN_VSS
const int ParticleList::GUN_VSS = RegisterParticle("weapon_shot_vss_01") static private
Definition at line 175 of file particlelist.c.
GUN_WINCHESTER70
const int ParticleList::GUN_WINCHESTER70 = RegisterParticle("weapon_shot_winch70_01") static private
Definition at line 174 of file particlelist.c.
HATCHBACK_COOLANT_OVERHEATED
const int ParticleList::HATCHBACK_COOLANT_OVERHEATED = RegisterParticle("Hatchback_coolant_overheated") static private
Definition at line 261 of file particlelist.c.
Referenced by EffVehicleSmoke::SetParticleStateHeavy(), and EffCoolantSteam::SetParticleStateHeavy().
HATCHBACK_COOLANT_OVERHEATING
const int ParticleList::HATCHBACK_COOLANT_OVERHEATING = RegisterParticle("Hatchback_coolant_overheating") static private
Definition at line 260 of file particlelist.c.
Referenced by EffVehicleSmoke::SetParticleStateLight(), and EffCoolantSteam::SetParticleStateLight().
HATCHBACK_ENGINE_OVERHEATED
const int ParticleList::HATCHBACK_ENGINE_OVERHEATED = RegisterParticle("Hatchback_engine_failure") static private
Definition at line 263 of file particlelist.c.
Referenced by EffEngineSmoke::SetParticleStateHeavy().
HATCHBACK_ENGINE_OVERHEATING
const int ParticleList::HATCHBACK_ENGINE_OVERHEATING = RegisterParticle("Hatchback_engine_failing") static private
Definition at line 262 of file particlelist.c.
Referenced by EffEngineSmoke::SetParticleStateLight().
HATCHBACK_EXHAUST_SMOKE
const int ParticleList::HATCHBACK_EXHAUST_SMOKE = RegisterParticle("Hatchback_exhaust") static private
Definition at line 264 of file particlelist.c.
Referenced by EffExhaustSmoke::SetParticleStateLight().
HOUSE_FIRE_END
const int ParticleList::HOUSE_FIRE_END = RegisterParticle("fire_small_house_01_end") static private
Definition at line 45 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor().
HOUSE_FIRE_START
const int ParticleList::HOUSE_FIRE_START = RegisterParticle("fire_small_house_01_start") static private
Definition at line 40 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor().
HOUSE_FIRE_STEAM_2END
const int ParticleList::HOUSE_FIRE_STEAM_2END = RegisterParticle("steam_medium_house_2end") static private
Definition at line 46 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor().
HOUSE_NORMAL_FIRE
const int ParticleList::HOUSE_NORMAL_FIRE = RegisterParticle("fire_medium_house_01") static private
Definition at line 43 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor().
HOUSE_NORMAL_SMOKE
const int ParticleList::HOUSE_NORMAL_SMOKE = RegisterParticle("smoke_medium_house_01") static private
Definition at line 44 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor(), and FireplaceBase::OvenIndoor().
HOUSE_SMALL_FIRE
const int ParticleList::HOUSE_SMALL_FIRE = RegisterParticle("fire_small_house_01") static private
Definition at line 41 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor().
HOUSE_SMALL_SMOKE
const int ParticleList::HOUSE_SMALL_SMOKE = RegisterParticle("smoke_small_house_01") static private
Definition at line 42 of file particlelist.c.
Referenced by FireplaceBase::FireplaceIndoor(), and FireplaceBase::OvenIndoor().
IMPACT_CONCRETE_ENTER
const int ParticleList::IMPACT_CONCRETE_ENTER = RegisterParticle("impacts/hit_concrete_ent_01") static private
Definition at line 203 of file particlelist.c.
Referenced by Hit_Concrete::Hit_Concrete().
IMPACT_CONCRETE_EXIT
const int ParticleList::IMPACT_CONCRETE_EXIT = RegisterParticle("impacts/hit_concrete_ext_01") static private
Definition at line 205 of file particlelist.c.
Referenced by Hit_Concrete::Hit_Concrete().
IMPACT_CONCRETE_RICOCHET
const int ParticleList::IMPACT_CONCRETE_RICOCHET = RegisterParticle("impacts/hit_concrete_ric_01") static private
Definition at line 204 of file particlelist.c.
Referenced by Hit_Concrete::Hit_Concrete().
IMPACT_DIRT_ENTER
const int ParticleList::IMPACT_DIRT_ENTER = RegisterParticle("impacts/hit_dirt_ent_01") static private
Definition at line 211 of file particlelist.c.
Referenced by Hit_Dirt::Hit_Dirt().
IMPACT_DIRT_EXIT
const int ParticleList::IMPACT_DIRT_EXIT = RegisterParticle("impacts/hit_dirt_ext_01") static private
Definition at line 213 of file particlelist.c.
Referenced by Hit_Dirt::Hit_Dirt().
IMPACT_DIRT_RICOCHET
const int ParticleList::IMPACT_DIRT_RICOCHET = RegisterParticle("impacts/hit_dirt_ric_01") static private
Definition at line 212 of file particlelist.c.
Referenced by Hit_Dirt::Hit_Dirt().
IMPACT_DISTANT_DUST
const int ParticleList::IMPACT_DISTANT_DUST = RegisterParticle("impacts/distant_dust") static private
Definition at line 193 of file particlelist.c.
Referenced by EffBulletImpactBase::Event_OnStarted().
IMPACT_FOLIAGE_ENTER
const int ParticleList::IMPACT_FOLIAGE_ENTER = RegisterParticle("impacts/hit_foliage_ent_01") static private
Definition at line 206 of file particlelist.c.
Referenced by Hit_Foliage::Hit_Foliage().
IMPACT_FOLIAGE_EXIT
const int ParticleList::IMPACT_FOLIAGE_EXIT = RegisterParticle("impacts/hit_foliage_ext_01") static private
Definition at line 208 of file particlelist.c.
Referenced by Hit_Foliage::Hit_Foliage().
IMPACT_FOLIAGE_RICOCHET
const int ParticleList::IMPACT_FOLIAGE_RICOCHET = RegisterParticle("impacts/hit_foliage_ric_01") static private
Definition at line 207 of file particlelist.c.
Referenced by Hit_Foliage::Hit_Foliage().
IMPACT_GLASS_ENTER
const int ParticleList::IMPACT_GLASS_ENTER = RegisterParticle("impacts/hit_glass_ent_01") static private
Definition at line 232 of file particlelist.c.
Referenced by Hit_Glass::Hit_Glass(), and Hit_Glass_Thin::Hit_Glass_Thin().
IMPACT_GLASS_EXIT
const int ParticleList::IMPACT_GLASS_EXIT = RegisterParticle("impacts/hit_glass_ext_01") static private
Definition at line 234 of file particlelist.c.
Referenced by Hit_Glass::Hit_Glass(), and Hit_Glass_Thin::Hit_Glass_Thin().
IMPACT_GLASS_RICOCHET
const int ParticleList::IMPACT_GLASS_RICOCHET = RegisterParticle("impacts/hit_glass_ric_01") static private
Definition at line 233 of file particlelist.c.
Referenced by Hit_Glass::Hit_Glass(), and Hit_Glass_Thin::Hit_Glass_Thin().
IMPACT_GRASS_ENTER
const int ParticleList::IMPACT_GRASS_ENTER = RegisterParticle("impacts/hit_grass_ent_01") static private
Definition at line 209 of file particlelist.c.
Referenced by Hit_Grass::Hit_Grass().
IMPACT_GRASS_RICOCHET
const int ParticleList::IMPACT_GRASS_RICOCHET = RegisterParticle("impacts/hit_grass_ric_01") static private
Definition at line 210 of file particlelist.c.
Referenced by Hit_Grass::Hit_Grass().
IMPACT_GRAVEL_ENTER
const int ParticleList::IMPACT_GRAVEL_ENTER = RegisterParticle("impacts/hit_gravel_ent_01") static private
Definition at line 217 of file particlelist.c.
Referenced by Hit_Gravel::Hit_Gravel().
IMPACT_GRAVEL_EXIT
const int ParticleList::IMPACT_GRAVEL_EXIT = RegisterParticle("impacts/hit_gravel_ext_01") static private
Definition at line 219 of file particlelist.c.
Referenced by Hit_Gravel::Hit_Gravel().
IMPACT_GRAVEL_RICOCHET
const int ParticleList::IMPACT_GRAVEL_RICOCHET = RegisterParticle("impacts/hit_gravel_ric_01") static private
Definition at line 218 of file particlelist.c.
Referenced by Hit_Gravel::Hit_Gravel(), and FuelStation::OnExplosionEffects().
IMPACT_MEAT_ENTER
const int ParticleList::IMPACT_MEAT_ENTER = RegisterParticle("impacts/hit_meat_ent_01") static private
Definition at line 226 of file particlelist.c.
IMPACT_MEAT_EXIT
const int ParticleList::IMPACT_MEAT_EXIT = RegisterParticle("impacts/hit_meat_ext_01") static private
Definition at line 228 of file particlelist.c.
IMPACT_MEAT_RICOCHET
const int ParticleList::IMPACT_MEAT_RICOCHET = RegisterParticle("impacts/hit_meat_ric_01") static private
Definition at line 227 of file particlelist.c.
IMPACT_MEATBONES_ENTER
const int ParticleList::IMPACT_MEATBONES_ENTER = RegisterParticle("impacts/hit_meatbones_ent_01") static private
Definition at line 229 of file particlelist.c.
Referenced by Hit_MeatBones::Hit_MeatBones().
IMPACT_MEATBONES_EXIT
const int ParticleList::IMPACT_MEATBONES_EXIT = RegisterParticle("impacts/hit_meatbones_ext_01") static private
Definition at line 231 of file particlelist.c.
Referenced by Hit_MeatBones::Hit_MeatBones().
IMPACT_MEATBONES_RICOCHET
const int ParticleList::IMPACT_MEATBONES_RICOCHET = RegisterParticle("impacts/hit_meatbones_ent_01") static private
Definition at line 230 of file particlelist.c.
Referenced by Hit_MeatBones::Hit_MeatBones().
IMPACT_METAL_ENTER
const int ParticleList::IMPACT_METAL_ENTER = RegisterParticle("impacts/hit_metal_ent_01") static private
Definition at line 223 of file particlelist.c.
Referenced by Hit_Metal::Hit_Metal().
IMPACT_METAL_EXIT
const int ParticleList::IMPACT_METAL_EXIT = RegisterParticle("impacts/hit_metal_ext_01") static private
Definition at line 225 of file particlelist.c.
Referenced by Hit_Metal::Hit_Metal().
IMPACT_METAL_RICOCHET
const int ParticleList::IMPACT_METAL_RICOCHET = RegisterParticle("impacts/hit_metal_ric_01") static private
Definition at line 224 of file particlelist.c.
Referenced by Hit_Metal::Hit_Metal(), and FuelStation::OnExplosionEffects().
IMPACT_PLASTER_ENTER
const int ParticleList::IMPACT_PLASTER_ENTER = RegisterParticle("impacts/hit_plaster_ent_01") static private
Definition at line 220 of file particlelist.c.
Referenced by Hit_Plaster::Hit_Plaster().
IMPACT_PLASTER_EXIT
const int ParticleList::IMPACT_PLASTER_EXIT = RegisterParticle("impacts/hit_plaster_ext_01") static private
Definition at line 222 of file particlelist.c.
Referenced by Hit_Plaster::Hit_Plaster().
IMPACT_PLASTER_RICOCHET
const int ParticleList::IMPACT_PLASTER_RICOCHET = RegisterParticle("impacts/hit_plaster_ric_01") static private
Definition at line 221 of file particlelist.c.
Referenced by Hit_Plaster::Hit_Plaster().
IMPACT_PLASTIC_ENTER
const int ParticleList::IMPACT_PLASTIC_ENTER = RegisterParticle("impacts/hit_plastic_ent_01") static private
Definition at line 244 of file particlelist.c.
Referenced by Hit_Plastic::Hit_Plastic().
IMPACT_PLASTIC_EXIT
const int ParticleList::IMPACT_PLASTIC_EXIT = RegisterParticle("impacts/hit_plastic_ext_01") static private
Definition at line 246 of file particlelist.c.
IMPACT_PLASTIC_RICOCHET
const int ParticleList::IMPACT_PLASTIC_RICOCHET = RegisterParticle("impacts/hit_plastic_ric_01") static private
Definition at line 245 of file particlelist.c.
IMPACT_RUBBER_ENTER
const int ParticleList::IMPACT_RUBBER_ENTER = RegisterParticle("impacts/hit_rubber_ent_01") static private
Definition at line 214 of file particlelist.c.
Referenced by Hit_Rubber::Hit_Rubber().
IMPACT_RUBBER_EXIT
const int ParticleList::IMPACT_RUBBER_EXIT = RegisterParticle("impacts/hit_rubber_ext_01") static private
Definition at line 216 of file particlelist.c.
Referenced by Hit_Rubber::Hit_Rubber().
IMPACT_RUBBER_RICOCHET
const int ParticleList::IMPACT_RUBBER_RICOCHET = RegisterParticle("impacts/hit_rubber_ric_01") static private
Definition at line 215 of file particlelist.c.
Referenced by Hit_Rubber::Hit_Rubber().
IMPACT_SAND_ENTER
const int ParticleList::IMPACT_SAND_ENTER = RegisterParticle("impacts/hit_sand_ent_01") static private
Definition at line 241 of file particlelist.c.
Referenced by Hit_Sand::Hit_Sand().
IMPACT_SAND_EXIT
const int ParticleList::IMPACT_SAND_EXIT = RegisterParticle("impacts/hit_sand_ext_01") static private
Definition at line 243 of file particlelist.c.
IMPACT_SAND_RICOCHET
const int ParticleList::IMPACT_SAND_RICOCHET = RegisterParticle("impacts/hit_sand_ric_01") static private
Definition at line 242 of file particlelist.c.
IMPACT_TEST
const int ParticleList::IMPACT_TEST = RegisterParticle("impacts/bullet_impact_placeholder") static private
Definition at line 192 of file particlelist.c.
Referenced by EffBulletImpactTest::EffBulletImpactTest(), Hit_ErrorNoMaterial::Hit_ErrorNoMaterial(), and Hit_Undefined::Hit_Undefined().
IMPACT_TEST2
const int ParticleList::IMPACT_TEST2 = RegisterParticle("_test_orientation_02") static private
Definition at line 195 of file particlelist.c.
IMPACT_TEST_ENTER_DEBUG
const int ParticleList::IMPACT_TEST_ENTER_DEBUG = RegisterParticle("impacts/_test_impact_enter_debug") static private
Definition at line 196 of file particlelist.c.
IMPACT_TEST_EXIT_DEBUG
const int ParticleList::IMPACT_TEST_EXIT_DEBUG = RegisterParticle("impacts/_test_impact_exit_debug") static private
Definition at line 198 of file particlelist.c.
IMPACT_TEST_NO_MATERIAL_ERROR
const int ParticleList::IMPACT_TEST_NO_MATERIAL_ERROR = RegisterParticle("_test_no_material") static private
Definition at line 199 of file particlelist.c.
Referenced by Hit_ErrorNoMaterial::Hit_ErrorNoMaterial().
IMPACT_TEST_RICOCHET
const int ParticleList::IMPACT_TEST_RICOCHET = RegisterParticle("impacts/bullet_riochet_placeholder") static private
Definition at line 194 of file particlelist.c.
IMPACT_TEST_RICOCHET_DEBUG
const int ParticleList::IMPACT_TEST_RICOCHET_DEBUG = RegisterParticle("impacts/_test_impact_ricochet_debug") static private
Definition at line 197 of file particlelist.c.
IMPACT_TEXTILE_ENTER
const int ParticleList::IMPACT_TEXTILE_ENTER = RegisterParticle("impacts/hit_textile_ent_01") static private
Definition at line 238 of file particlelist.c.
Referenced by Hit_Textile::Hit_Textile().
IMPACT_TEXTILE_EXIT
const int ParticleList::IMPACT_TEXTILE_EXIT = RegisterParticle("impacts/hit_textile_ext_01") static private
Definition at line 240 of file particlelist.c.
Referenced by Hit_Textile::Hit_Textile().
IMPACT_TEXTILE_RICOCHET
const int ParticleList::IMPACT_TEXTILE_RICOCHET = RegisterParticle("impacts/hit_textile_ric_01") static private
Definition at line 239 of file particlelist.c.
IMPACT_WATER_LARGE_ENTER
const int ParticleList::IMPACT_WATER_LARGE_ENTER = RegisterParticle("impacts/hit_water_ent_03") static private
Definition at line 237 of file particlelist.c.
Referenced by Hit_Water::CalculateStoppingForce().
IMPACT_WATER_MEDIUM_ENTER
const int ParticleList::IMPACT_WATER_MEDIUM_ENTER = RegisterParticle("impacts/hit_water_ent_02") static private
Definition at line 236 of file particlelist.c.
Referenced by Hit_Water::CalculateStoppingForce().
IMPACT_WATER_SMALL_ENTER
const int ParticleList::IMPACT_WATER_SMALL_ENTER = RegisterParticle("impacts/hit_water_ent_01") static private
Definition at line 235 of file particlelist.c.
Referenced by Hit_Water::CalculateStoppingForce(), and Hit_Water::Hit_Water().
IMPACT_WOOD_ENTER
const int ParticleList::IMPACT_WOOD_ENTER = RegisterParticle("impacts/hit_wood_ent_01") static private
Definition at line 200 of file particlelist.c.
Referenced by Hit_Wood::Hit_Wood().
IMPACT_WOOD_EXIT
const int ParticleList::IMPACT_WOOD_EXIT = RegisterParticle("impacts/hit_wood_ext_01") static private
Definition at line 202 of file particlelist.c.
Referenced by Hit_Wood::Hit_Wood().
IMPACT_WOOD_RICOCHET
const int ParticleList::IMPACT_WOOD_RICOCHET = RegisterParticle("impacts/hit_wood_ric_01") static private
Definition at line 201 of file particlelist.c.
Referenced by Hit_Wood::Hit_Wood().
INVALID
const int ParticleList::INVALID = -1 static private
Definition at line 20 of file particlelist.c.
Referenced by ExplosivesBase(), EffectParticle::GetCurrentParticleID(), Hit_MeatBones_MeleeFist::Hit_MeatBones_MeleeFist(), IsValidId(), OnExplosionEffects(), ParticleCookingStop(), Inventory_Base::ParticleCookingStop(), and SmokeGrenadeBase().
M67
const int ParticleList::M67 = RegisterParticle("explosion_M67_01") static private
Definition at line 131 of file particlelist.c.
Referenced by Grenade_Base::M67Grenade().
m_lastID
int ParticleList::m_lastID = 0 static private
Definition at line 16 of file particlelist.c.
Referenced by GetRegisteredParticlesCount(), and RegisterParticle().
m_ParticleNames
ref map<string, int> ParticleList::m_ParticleNames static private
Definition at line 14 of file particlelist.c.
Referenced by GetParticleIDByName(), and RegisterParticle().
m_ParticlePaths
ref map<int, string> ParticleList::m_ParticlePaths static private
Definition at line 13 of file particlelist.c.
Referenced by GetParticleID(), GetParticlePath(), PreloadParticles(), and RegisterParticle().
NONE
const int ParticleList::NONE = 0 static private
Definition at line 21 of file particlelist.c.
Referenced by DestructionEffectGasCanister::Init(), and IsValidId().
OVEN_FIRE_END
const int ParticleList::OVEN_FIRE_END = RegisterParticle("fire_small_ovenl_01_end") static private
Definition at line 59 of file particlelist.c.
Referenced by FireplaceBase::OvenIndoor().
OVEN_FIRE_START
const int ParticleList::OVEN_FIRE_START = RegisterParticle("fire_small_oven_01_start") static private
Definition at line 56 of file particlelist.c.
Referenced by FireplaceBase::OvenIndoor().
OVEN_NORMAL_FIRE
const int ParticleList::OVEN_NORMAL_FIRE = RegisterParticle("fire_medium_oven_01") static private
Definition at line 58 of file particlelist.c.
Referenced by FireplaceBase::OvenIndoor().
OVEN_SMALL_FIRE
const int ParticleList::OVEN_SMALL_FIRE = RegisterParticle("fire_small_oven_01") static private
Definition at line 57 of file particlelist.c.
Referenced by FireplaceBase::OvenIndoor().
PARTICLE_TEST
const int ParticleList::PARTICLE_TEST = RegisterParticle("_test_orientation") static private
Definition at line 22 of file particlelist.c.
PLASTIC_EXPLOSION
const int ParticleList::PLASTIC_EXPLOSION = RegisterParticle("explosion_plastic_01") static private
Definition at line 298 of file particlelist.c.
Referenced by Plastic_Explosive::Plastic_Explosive().
POWER_GENERATOR_SMOKE
const int ParticleList::POWER_GENERATOR_SMOKE = RegisterParticle("smoke_small_generator_01") static private
Definition at line 134 of file particlelist.c.
Referenced by EffGeneratorSmoke::EffGeneratorSmoke().
RGD5
const int ParticleList::RGD5 = RegisterParticle("explosion_RGD5_01") static private
Definition at line 130 of file particlelist.c.
Referenced by Grenade_ChemGas::Grenade_ChemGas(), DestructionEffectGasCanister::Init(), and Grenade_Base::RGD5Grenade().
ROADFLARE_BURNING_ENDING
const int ParticleList::ROADFLARE_BURNING_ENDING = RegisterParticle("fire_small_roadflare_red_02") static private
Definition at line 84 of file particlelist.c.
ROADFLARE_BURNING_INIT
const int ParticleList::ROADFLARE_BURNING_INIT = RegisterParticle("fire_small_roadflare_red_04") static private
Definition at line 82 of file particlelist.c.
ROADFLARE_BURNING_MAIN
const int ParticleList::ROADFLARE_BURNING_MAIN = RegisterParticle("fire_small_roadflare_red_01") static private
Definition at line 83 of file particlelist.c.
Referenced by PMTPlayback::TestWiggleStress().
ROADFLARE_BURNING_SMOKE
const int ParticleList::ROADFLARE_BURNING_SMOKE = RegisterParticle("fire_small_roadflare_red_03") static private
Definition at line 85 of file particlelist.c.
SMARKS_CHAMBER
const int ParticleList::SMARKS_CHAMBER = RegisterParticle("weapon_shot_chamber_spark") static private
Definition at line 189 of file particlelist.c.
SMOKE_GENERIC_WRECK
const int ParticleList::SMOKE_GENERIC_WRECK = RegisterParticle("smoke_generic_wreck") static private
Definition at line 255 of file particlelist.c.
Referenced by FuelStation::OnExplosionEffects().
SMOKING_BARREL
const int ParticleList::SMOKING_BARREL = RegisterParticle("smoking_barrel") static private
Definition at line 184 of file particlelist.c.
SMOKING_BARREL_HEAVY
const int ParticleList::SMOKING_BARREL_HEAVY = RegisterParticle("smoking_barrel_heavy") static private
Definition at line 186 of file particlelist.c.
SMOKING_BARREL_SMALL
const int ParticleList::SMOKING_BARREL_SMALL = RegisterParticle("smoking_barrel_small") static private
Definition at line 185 of file particlelist.c.
SMOKING_BARREL_STEAM
const int ParticleList::SMOKING_BARREL_STEAM = RegisterParticle("smoking_barrel_steam") static private
Definition at line 187 of file particlelist.c.
SMOKING_BARREL_STEAM_SMALL
const int ParticleList::SMOKING_BARREL_STEAM_SMALL = RegisterParticle("smoking_barrel_steam_small") static private
Definition at line 188 of file particlelist.c.
SMOKING_CAR_ENGINE
const int ParticleList::SMOKING_CAR_ENGINE = RegisterParticle("menu_engine_fire") static private
Definition at line 256 of file particlelist.c.
Referenced by MenuCarEngineSmoke::MenuCarEngineSmoke().
SMOKING_HELI_WRECK
const int ParticleList::SMOKING_HELI_WRECK = RegisterParticle("smoke_heli_wreck_01") static private
Definition at line 253 of file particlelist.c.
Referenced by CrashBase::Wreck_Mi8_Crashed(), and CrashBase::Wreck_UH1Y().
SPOOKY_MIST
const int ParticleList::SPOOKY_MIST = RegisterParticle("spooky_mist") static private
Definition at line 272 of file particlelist.c.
TORCH_T1
const int ParticleList::TORCH_T1 = RegisterParticle("fire_small_torch_02") static private
Definition at line 73 of file particlelist.c.
Referenced by FlammableBase::UpdateParticle().
TORCH_T2
const int ParticleList::TORCH_T2 = RegisterParticle("fire_small_torch_03") static private
Definition at line 74 of file particlelist.c.
Referenced by FlammableBase::UpdateParticle().
TORCH_T3
const int ParticleList::TORCH_T3 = RegisterParticle("fire_small_torch_01") static private
Definition at line 72 of file particlelist.c.
VOMIT
const int ParticleList::VOMIT = RegisterParticle("character_vomit_01") static private
Definition at line 143 of file particlelist.c.
Referenced by EffVomit::EffVomit().
VOMIT_BLOOD
const int ParticleList::VOMIT_BLOOD = RegisterParticle("character_vomitBlood_01") static private
Definition at line 274 of file particlelist.c.
Referenced by EffVomitBlood::EffVomitBlood().
VOMIT_CHUNKS
const int ParticleList::VOMIT_CHUNKS = RegisterParticle("character_vomit_puddle") static private
Definition at line 147 of file particlelist.c.
WATER_JET
const int ParticleList::WATER_JET = RegisterParticle("water_jet") static private
Definition at line 301 of file particlelist.c.
WATER_JET_WEAK
const int ParticleList::WATER_JET_WEAK = RegisterParticle("water_jet_weak") static private
Definition at line 302 of file particlelist.c.
WATER_SPILLING
const int ParticleList::WATER_SPILLING = RegisterParticle("water_spilling") static private
Definition at line 303 of file particlelist.c.