DayzKode: IconsContainer Class Reference
IconsContainer Class Reference
Private Member Functions
void AddItem (Icon icon)
bool ContainsEntity (EntityAI entity)
Icon GetIcon (int entity_id)
Icon GetIconByIndex (int index)
int GetItemCount ()
void IconsContainer (LayoutHolder parent)
override void Refresh ()
void RemoveItem (Icon icon)
void RemoveItem (int entity)
override void UnfocusAll ()
void UpdateItemsTemperature ()
Private Attributes
protected ref map< int, ref Icon > m_EntitiesMap = new map<int, ref Icon>
Detailed Description
Definition at line 1 of file iconscontainer.c.
Constructor & Destructor Documentation
IconsContainer()
void IconsContainer::IconsContainer (LayoutHolder parent) inline private
Definition at line 5 of file iconscontainer.c.
    {
    }
Member Function Documentation
AddItem()
void IconsContainer::AddItem (Icon icon) inline private
Definition at line 31 of file iconscontainer.c.
    {
        if( !m_EntitiesMap.Contains( icon.GetObject().GetID() ) )
        {
            m_EntitiesMap.Insert( icon.GetObject().GetID(), icon);
        }
    }
References Icon::GetObject(), and m_EntitiesMap.
ContainsEntity()
bool IconsContainer::ContainsEntity (EntityAI entity) inline private
Definition at line 74 of file iconscontainer.c.
    {
        return m_EntitiesMap.Contains( entity.GetID() );
    }
References m_EntitiesMap.
GetIcon()
Icon IconsContainer::GetIcon (int entity_id) inline private
Definition at line 39 of file iconscontainer.c.
    {
        return m_EntitiesMap.Get( entity_id  );
    }
References m_EntitiesMap.
GetIconByIndex()
Icon IconsContainer::GetIconByIndex (int index) inline private
Definition at line 44 of file iconscontainer.c.
    {
        if( index < m_EntitiesMap.Count() && index > -1 )
            return m_EntitiesMap.GetElement( index  );
        return null;
    }
References m_EntitiesMap.
GetItemCount()
int IconsContainer::GetItemCount () inline private
Definition at line 26 of file iconscontainer.c.
    {
        return m_EntitiesMap.Count();
    }
References m_EntitiesMap.
Refresh()
override void IconsContainer::Refresh () inline private
Definition at line 91 of file iconscontainer.c.
    {
        super.Refresh();
        for( int i = 0; i < m_EntitiesMap.Count(); i++ )
        {
            m_EntitiesMap.GetElement(i).Refresh();
        }
    }
References m_EntitiesMap.
RemoveItem() [1/2]
void IconsContainer::RemoveItem (Icon icon) inline private
Definition at line 51 of file iconscontainer.c.
    {
        if( icon )
        {
            Icon icon_copy = icon; // for some reason garbage collector collects icon too soon, so copy has to be made
            if( icon.GetObject() )
                m_EntitiesMap.Remove( icon.GetObject().GetID() );
            else
            {
                int ix = m_EntitiesMap.GetKeyByValue( icon );
                if( m_EntitiesMap.Contains( ix ) )
                    m_EntitiesMap.Remove( ix );
                else
                    delete icon;
            }
        }
    }
References Icon::GetObject(), and m_EntitiesMap.
RemoveItem() [2/2]
void IconsContainer::RemoveItem (int entity) inline private
Definition at line 69 of file iconscontainer.c.
    {
        m_EntitiesMap.Remove( entity );
    }
References m_EntitiesMap.
UnfocusAll()
override void IconsContainer::UnfocusAll () inline private
Definition at line 9 of file iconscontainer.c.
    {
        for ( int i = 0; i < Count(); i++ )
        {
            for ( int j = 0; j < ITEMS_IN_ROW; j++ )
            {
                Get( i ).GetMainWidget().FindAnyWidget( "Cursor" + j ).Show( false );
            }
        }
        for ( i = 0; i < m_EntitiesMap.Count(); ++i )
        {
            m_EntitiesMap.GetElement(i).SetActive(false);
        }
    }
References Count, Get(), ITEMS_IN_ROW, and m_EntitiesMap.
UpdateItemsTemperature()
void IconsContainer::UpdateItemsTemperature () inline private
Definition at line 79 of file iconscontainer.c.
    {
        if( !ItemManager.GetInstance().IsDragging() )
        {
            for( int i = 0; i < m_EntitiesMap.Count(); i++ )
            {
                Icon icon = m_EntitiesMap.GetElement(i);
                icon.SetTemperature();
            }
        }
    }
References ItemManager::GetInstance(), ItemManager::IsDragging(), m_EntitiesMap, and Icon::SetTemperature().
Member Data Documentation
m_EntitiesMap
protected ref map<int, ref Icon> IconsContainer::m_EntitiesMap = new map<int, ref Icon> private
Definition at line 3 of file iconscontainer.c.
Referenced by AddItem(), ContainsEntity(), GetIcon(), GetIconByIndex(), GetItemCount(), Refresh(), RemoveItem(), UnfocusAll(), and UpdateItemsTemperature().