DayzKode: ItemTransmitter Class Reference
ItemTransmitter Class Reference
Private Member Functions
override bool IsTransmitter ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnSwitchOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
void SetNextFrequency (PlayerBase player=NULL)
protected void SoundTurnedOnNoiseStart ()
protected void SoundTurnedOnNoiseStop ()
Private Attributes
protected EffectSound m_SoundLoop
string SOUND_RADIO_TURNED_ON = ""
Detailed Description
Definition at line 2 of file transmitterbase.c.
Member Function Documentation
IsTransmitter()
override bool ItemTransmitter::IsTransmitter () inline private
Definition at line 37 of file transmitterbase.c.
    {
        return true;
    }
OnStoreLoad()
override bool ItemTransmitter::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 18 of file transmitterbase.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Transmitter data ---
        //load and set tuned frequency
        int tuned_frequency_idx;
        if ( !ctx.Read( tuned_frequency_idx ) )
        {
            SetFrequencyByIndex( 0 );       //set default
            return false;
        }
        SetFrequencyByIndex( tuned_frequency_idx );
        //---
        return true;
    }
References Serializer::Read().
OnStoreSave()
override void ItemTransmitter::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 10 of file transmitterbase.c.
    {
        super.OnStoreSave( ctx );
        //store tuned frequency
        ctx.Write( GetTunedFrequencyIndex() );
    }
References Serializer::Write().
OnSwitchOn()
override void ItemTransmitter::OnSwitchOn () inline private
Definition at line 84 of file transmitterbase.c.
    {
        if ( !GetCompEM().CanWork() )
        {
            GetCompEM().SwitchOff();
        }
    }
OnWorkStart()
override void ItemTransmitter::OnWorkStart () inline private
Definition at line 92 of file transmitterbase.c.
    {
        //turn on broadcasting/receiving
        EnableBroadcast ( true );
        EnableReceive ( true );
        SwitchOn ( true );
        //play sound
        SoundTurnedOnNoiseStart();
    }
OnWorkStop()
override void ItemTransmitter::OnWorkStop () inline private
Definition at line 103 of file transmitterbase.c.
    {
        //auto switch off (EM)
        GetCompEM().SwitchOff();
        //turn off broadcasting/receiving
        EnableBroadcast ( false );
        EnableReceive ( false );
        SwitchOn ( false );
        //stop sound
        SoundTurnedOnNoiseStop();
    }
SetActions()
override void ItemTransmitter::SetActions () inline private
Definition at line 131 of file transmitterbase.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnTransmitter);
        AddAction(ActionTurnOffTransmitter);
        AddAction(ActionTuneFrequency);
    }
References ActionTuneFrequency(), ActionTurnOffTransmitter(), ActionTurnOnTransmitter(), and AddAction().
SetNextFrequency()
void ItemTransmitter::SetNextFrequency (PlayerBase player = NULL) inline private
Definition at line 43 of file transmitterbase.c.
    {
        SetNextChannel();
        /*
        if ( player )
        {
            DisplayRadioInfo( GetTunedFrequency().ToString(), player );
        }
        */
    }
SoundTurnedOnNoiseStart()
protected void ItemTransmitter::SoundTurnedOnNoiseStart () inline private
Definition at line 121 of file transmitterbase.c.
    {
        PlaySoundSetLoop( m_SoundLoop, SOUND_RADIO_TURNED_ON, 1.0, 1.0 );
    }
References PlaySoundSetLoop().
SoundTurnedOnNoiseStop()
protected void ItemTransmitter::SoundTurnedOnNoiseStop () inline private
Definition at line 126 of file transmitterbase.c.
    {
        StopSoundSet( m_SoundLoop );
    }
References StopSoundSet().
Member Data Documentation
m_SoundLoop
protected EffectSound ItemTransmitter::m_SoundLoop private
Definition at line 7 of file transmitterbase.c.
SOUND_RADIO_TURNED_ON
string ItemTransmitter::SOUND_RADIO_TURNED_ON = "" private
Definition at line 5 of file transmitterbase.c.