DayzKode: ActionPickupChicken Class Reference
ActionPickupChicken Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPickupChicken ()
override void CreateConditionComponents ()
override GetInputType ()
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actionpickupchicken.c.
Constructor & Destructor Documentation
ActionPickupChicken()
void ActionPickupChicken::ActionPickupChicken () inline private
Definition at line 3 of file actionpickupchicken.c.
    {
        m_Text = "#take";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionPickupChicken::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file actionpickupchicken.c.
    {
        if ( player.GetCommand_Vehicle() )
            return false;
        Animal_GallusGallusDomesticus chicken;
        if ( Class.CastTo( chicken, target.GetObject() ) )
        {
            return !chicken.IsAlive();
        }
        return false;
    }
References Class::CastTo().
CreateConditionComponents()
override void ActionPickupChicken::CreateConditionComponents () inline private
Definition at line 13 of file actionpickupchicken.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionPickupChicken::GetInputType () inline private
Definition at line 8 of file actionpickupchicken.c.
    {
        return ContinuousInteractActionInput;
    }
OnExecuteServer()
override void ActionPickupChicken::OnExecuteServer (ActionData action_data) inline private
Definition at line 32 of file actionpickupchicken.c.
    {
        // We will switch the item
        Animal_GallusGallusDomesticus targetChicken = Animal_GallusGallusDomesticus.Cast( action_data.m_Target.GetObject() );
        if ( targetChicken )
        {
            DeadChicken_ColorBase deadChicken = DeadChicken_ColorBase.Cast( action_data.m_Player.GetHumanInventory().CreateInHands( targetChicken.GetDeadItemName() ) );
            if ( deadChicken == null )
            {
                deadChicken = DeadChicken_ColorBase.Cast( action_data.m_Player.GetHumanInventory().CreateInInventory( targetChicken.GetDeadItemName() ) );
                if ( deadChicken == null )
                    deadChicken = DeadChicken_ColorBase.Cast( GetGame().CreateObjectEx( targetChicken.GetDeadItemName(), targetChicken.GetPosition(), ECE_PLACE_ON_SURFACE, RF_ORIGINAL ) );
            }
            targetChicken.Delete();
        }
    }
References ECE_PLACE_ON_SURFACE, Animal_GallusGallusDomesticus::GetDeadItemName(), GetGame(), ActionData::m_Player, ActionData::m_Target, and RF_ORIGINAL.