DayzKode: PlayerStatsPCO_Base Class Reference
PlayerStatsPCO_Base Class Reference
Private Member Functions
override int GetVersion ()
override int GetVersion ()
override int GetVersion ()
override int GetVersion ()
override void Init ()
override void Init ()
override void Init ()
override void Init ()
void PlayerStatsPCO_v100 ()
Detailed Description
Definition at line 135 of file playerstatspco.c.
Member Function Documentation
GetVersion() [1/4]
override int PlayerStatsPCO_Base::GetVersion () inline private
Definition at line 138 of file playerstatspco.c.
    {
        return 100;
    }
Referenced by PCOHandlerStats::RegisterPCO().
GetVersion() [2/4]
override int PlayerStatsPCO_Base::GetVersion () inline private
Definition at line 189 of file playerstatspco.c.
    {
        return 101;
    }
GetVersion() [3/4]
override int PlayerStatsPCO_Base::GetVersion () inline private
Definition at line 229 of file playerstatspco.c.
    {
        return 106;
    }
GetVersion() [4/4]
override int PlayerStatsPCO_Base::GetVersion () inline private
Definition at line 267 of file playerstatspco.c.
    {
        return 115;
    }
Init() [1/4]
override void PlayerStatsPCO_Base::Init () inline private
Definition at line 143 of file playerstatspco.c.
    {
        RegisterStat(EPlayerStats_v100.HEATCOMFORT,     new PlayerStat<float>   (-1,                    1,                      0,                      "HeatComfort",      EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.TREMOR,          new PlayerStat<float>   (0,                     1,                      0,                      "Tremor",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.WET,             new PlayerStat<int>     (0,                     1,                      0,                      "Wet",              EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.ENERGY,              new PlayerStat<float>   (0,                     20000,                  600,                    "Energy",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.WATER,           new PlayerStat<float>   (0,                     5000,                   500,                    "Water",            EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.STOMACH_SOLID,   new PlayerStat<float>   (0,                     5000,                   0,                      "StomachSolid",         EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.STOMACH_ENERGY,      new PlayerStat<float>   (0,                     40000,                  0,                      "StomachEnergy",    EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.STOMACH_WATER,   new PlayerStat<float>   (0,                     5000,                   0,                      "StomachWater",     EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.DIET,            new PlayerStat<float>   (0,                     5000,                   2500,                   "Diet",             EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.STAMINA,         new PlayerStat<float>   (0,                     GameConstants.STAMINA_MAX,          100,                    "Stamina",          EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.SPECIALTY,       new PlayerStat<float>   (-1,                    1,                      0,                      "Specialty",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v100.BLOODTYPE,       new PlayerStat<int>     (0,                     128,                    BloodTypes.GenerateBloodType(), "BloodType",        EPSstatsFlags.EMPTY) );
    }
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Referenced by ResetAllStats().
Init() [2/4]
override void PlayerStatsPCO_Base::Init () inline private
Definition at line 194 of file playerstatspco.c.
    {
        RegisterStat(EPlayerStats_v101.HEATCOMFORT,     new PlayerStat<float>   (-1,                    1,                      0,                      "HeatComfort",      EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.TREMOR,          new PlayerStat<float>   (0,                     1,                      0,                      "Tremor",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.WET,             new PlayerStat<int>     (0,                     1,                      0,                      "Wet",              EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.ENERGY,              new PlayerStat<float>   (0,                     20000,                  600,                    "Energy",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.WATER,           new PlayerStat<float>   (0,                     5000,                   500,                    "Water",            EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.STOMACH_SOLID,   new PlayerStat<float>   (0,                     5000,                   0,                      "StomachSolid",         EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.STOMACH_ENERGY,      new PlayerStat<float>   (0,                     40000,                  0,                      "StomachEnergy",    EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.STOMACH_WATER,   new PlayerStat<float>   (0,                     5000,                   0,                      "StomachWater",     EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.DIET,            new PlayerStat<float>   (0,                     5000,                   2500,                   "Diet",             EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.STAMINA,         new PlayerStat<float>   (0,                     GameConstants.STAMINA_MAX,          100,                    "Stamina",          EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.SPECIALTY,       new PlayerStat<float>   (-1,                    1,                      0,                      "Specialty",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.BLOODTYPE,       new PlayerStat<int>     (0,                     128,                    BloodTypes.GenerateBloodType(), "BloodType",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v101.TOXICITY,        new PlayerStat<float>   (0,                     100,                    0,                      "Toxicity",         EPSstatsFlags.EMPTY) );
    }
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Init() [3/4]
override void PlayerStatsPCO_Base::Init () inline private
Definition at line 234 of file playerstatspco.c.
    {
        RegisterStat(EPlayerStats_v106.HEATCOMFORT,     new PlayerStat<float>   (-1,    1,                          0,                              "HeatComfort",      EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.TREMOR,          new PlayerStat<float>   (0,     1,                          0,                              "Tremor",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.WET,             new PlayerStat<int>     (0,     1,                          0,                              "Wet",              EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.ENERGY,          new PlayerStat<float>   (0,     20000,                      600,                            "Energy",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.WATER,           new PlayerStat<float>   (0,     5000,                       650,                            "Water",            EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.DIET,            new PlayerStat<float>   (0,     5000,                       2500,                           "Diet",             EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.STAMINA,         new PlayerStat<float>   (0,     GameConstants.STAMINA_MAX,  100,                            "Stamina",          EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.SPECIALTY,       new PlayerStat<float>   (-1,    1,                          0,                              "Specialty",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.BLOODTYPE,       new PlayerStat<int>     (0,     128,                        BloodTypes.GenerateBloodType(), "BloodType",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v106.TOXICITY,        new PlayerStat<float>   (0,     100,                        0,                              "Toxicity",         EPSstatsFlags.EMPTY) );
    }
References BloodTypes::GenerateBloodType(), RegisterStat(), and GameConstants::STAMINA_MAX.
Init() [4/4]
override void PlayerStatsPCO_Base::Init () inline private
Definition at line 272 of file playerstatspco.c.
    {
        RegisterStat(EPlayerStats_v115.HEATCOMFORT,     new PlayerStat<float>   (-1,    1,                              0,                              "HeatComfort",      EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.TREMOR,          new PlayerStat<float>   (0,     1,                              0,                              "Tremor",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.WET,             new PlayerStat<int>     (0,     1,                              0,                              "Wet",              EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.ENERGY,          new PlayerStat<float>   (0,     PlayerConstants.SL_ENERGY_MAX,  600,                            "Energy",           EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.WATER,           new PlayerStat<float>   (0,     PlayerConstants.SL_WATER_MAX,   600,                            "Water",            EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.DIET,            new PlayerStat<float>   (0,     5000,                           2500,                           "Diet",             EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.STAMINA,         new PlayerStat<float>   (0,     CfgGameplayHandler.GetStaminaMax(),     100,                    "Stamina",          EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.SPECIALTY,       new PlayerStat<float>   (-1,    1,                              0,                              "Specialty",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.BLOODTYPE,       new PlayerStat<int>     (0,     128,                            BloodTypes.GenerateBloodType(), "BloodType",        EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.TOXICITY,        new PlayerStat<float>   (0,     100,                            0,                              "Toxicity",         EPSstatsFlags.EMPTY) );
        RegisterStat(EPlayerStats_v115.HEATBUFFER,      new PlayerStat<float>   (-30,   30,                             0,                              "HeatBuffer",       EPSstatsFlags.EMPTY) );
    }
References BloodTypes::GenerateBloodType(), CfgGameplayHandler::GetStaminaMax(), RegisterStat(), PlayerConstants::SL_ENERGY_MAX, and PlayerConstants::SL_WATER_MAX.
PlayerStatsPCO_v100()
void PlayerStatsPCO_Base::PlayerStatsPCO_v100 () inline private
Definition at line 159 of file playerstatspco.c.
    {
    }