DayzKode: ItemOptics Class Reference
ItemOptics Class Reference
Private Member Functions
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
PlayerBase GetPlayer ()
override void HideSelection (string selection_name)
void HuntingOptic ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
bool ParentUsesWinchesterTypeMount ()
void SetPlayer (PlayerBase player)
override void ShowSelection (string selection_name)
Private Attributes
EntityAI m_Parent
protected PlayerBase m_Player
Detailed Description
Definition at line 31 of file m79.c.
Member Function Documentation
CanPutAsAttachment() [1/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 33 of file m79.c.
    {
        return true;
    }
CanPutAsAttachment() [2/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file buisoptic.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( parent.IsKindOf("M4A1_Base") )
        {
            return true;
        }
        return false;
        //return true;
    }
CanPutAsAttachment() [3/3]
override bool ItemOptics::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file m4_carryhandleoptic.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( parent.IsKindOf("M4A1_Base") )
        {
            return true;
        }
        return false;
    }
GetPlayer()
PlayerBase ItemOptics::GetPlayer () inline private
Definition at line 10 of file poweredoptic_base.c.
    {
        return m_Player;
    }
References m_Player.
HideSelection()
override void ItemOptics::HideSelection (string selection_name) inline private
Definition at line 34 of file huntingoptic.c.
    {
        super.HideSelection( selection_name );
        if (selection_name == "hide") //hides pilotview selections in order not to obstruct view
        {
            HideSelection("rings_ris_pilot");
            HideSelection("rings_winchester_pilot");
        }
    }
References HideSelection().
Referenced by ActionViewBinoculars::EnterOptics(), ActionViewOptics::EnterOptics(), HideSelection(), HuntingOptic(), InventoryItemSuper::OnOpticEnter(), KazuarOptic::OnOpticEnter(), StarlightOptic::OnOpticEnter(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
HuntingOptic()
void ItemOptics::HuntingOptic () inline private
Definition at line 5 of file huntingoptic.c.
    {
        HideSelection("rings_ris");
        HideSelection("rings_ris_pilot");
    }
References HideSelection().
OnWasAttached()
override void ItemOptics::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 11 of file huntingoptic.c.
    {
        super.OnWasAttached(parent, slot_id);
        m_Parent = parent;
        if (!ParentUsesWinchesterTypeMount())
        {
            HideSelection("rings_winchester");
            HideSelection("rings_winchester_pilot");
            ShowSelection("rings_ris");
            ShowSelection("rings_ris_pilot");
        }
    }
References HideSelection(), m_Parent, ParentUsesWinchesterTypeMount(), and ShowSelection().
OnWasDetached()
override void ItemOptics::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 24 of file huntingoptic.c.
    {
        super.OnWasDetached(parent, slot_id);
        m_Parent = null;
        HideSelection("rings_ris");
        HideSelection("rings_ris_pilot");
        ShowSelection("rings_winchester");
        ShowSelection("rings_winchester_pilot");
    }
References HideSelection(), m_Parent, and ShowSelection().
ParentUsesWinchesterTypeMount()
bool ItemOptics::ParentUsesWinchesterTypeMount () inline private
Definition at line 66 of file huntingoptic.c.
    {
        if (m_Parent && m_Parent.ConfigIsExisting("winchesterTypeOpticsMount"))
            return m_Parent.ConfigGetBool("winchesterTypeOpticsMount");
        return false;
    }
References m_Parent.
Referenced by OnWasAttached(), and ShowSelection().
SetPlayer()
void ItemOptics::SetPlayer (PlayerBase player) inline private
Definition at line 5 of file poweredoptic_base.c.
    {
        m_Player = player;
    }
References m_Player.
ShowSelection()
override void ItemOptics::ShowSelection (string selection_name) inline private
Definition at line 44 of file huntingoptic.c.
    {
        super.ShowSelection( selection_name );
        if (selection_name == "hide")
        {
            if (!ParentUsesWinchesterTypeMount())
            {
                HideSelection("rings_winchester");
                HideSelection("rings_winchester_pilot");
                ShowSelection("rings_ris");
                ShowSelection("rings_ris_pilot");
            }
            else
            {
                HideSelection("rings_ris");
                HideSelection("rings_ris_pilot");
                ShowSelection("rings_winchester");
                ShowSelection("rings_winchester_pilot");
            }
        }
    }
References HideSelection(), ParentUsesWinchesterTypeMount(), and ShowSelection().
Referenced by ActionViewBinoculars::ExitOptics(), ActionViewOptics::ExitOptics(), InventoryItemSuper::OnOpticExit(), OnWasAttached(), OnWasDetached(), ShowSelection(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
Member Data Documentation
m_Parent
EntityAI ItemOptics::m_Parent private
Definition at line 3 of file huntingoptic.c.
m_Player
protected PlayerBase ItemOptics::m_Player private
Definition at line 3 of file poweredoptic_base.c.