DayzKode: AnimationTimer Class Reference
AnimationTimer Class Reference
Tools
AnimationTimer class. This timer is for animating float value.
usage:
Private Member Functions
void AnimationTimer (int category=CALL_CATEGORY_SYSTEM)
float GetValue ()
Returns actual animated value.
override bool IsRunning ()
void Run (float targetVal, Managed obj, string updateFunc, string finishedFunc, float startingVal=0, bool loop=false, float speed=1.0, Param params=null, int category=CALL_CATEGORY_SYSTEM)
override void Tick (float timeslice)
Ticks the timer, is called by timer subsystem.
void ~AnimationTimer ()
Private Attributes
private bool m_Active
protected string m_FinishedFunction
protected ref Param m_Params
protected Managed m_TargetObject
private float m_TargetValue
private float m_TargetValueOriginal
protected string m_UpdateFunction
private float m_Value
Detailed Description
AnimationTimer class. This timer is for animating float value.
usage:
class MyObject
{
   ref AnimationTimer myAnim;
   void MyObject()
   {
    myAnim = new AnimationTimer();
    myAnim.Run(60, this, "Refresh");
   }
   void Refresh()
   {
    Print(myAnim.GetValue());
   }
};
Definition at line 639 of file tools.c.
Constructor & Destructor Documentation
AnimationTimer()
void AnimationTimer::AnimationTimer (int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 650 of file tools.c.
    {
        OnInit(category);
    }
References OnInit().
~AnimationTimer()
void AnimationTimer::~AnimationTimer () inline private
Definition at line 655 of file tools.c.
    {
        SetRunning(false);
    }
References SetRunning().
Member Function Documentation
GetValue()
float AnimationTimer::GetValue () inline private
Returns actual animated value.
Definition at line 678 of file tools.c.
                     {
        return m_Value;
    }
References m_Value.
Referenced by Land_Underground_EntranceBase::OnUpdateServer(), OnUpdateTimerIn(), and OnUpdateTimerOut().
IsRunning()
override bool AnimationTimer::IsRunning () inline private
Definition at line 682 of file tools.c.
    {
        return m_Active;
    }
References m_Active.
Run()
void AnimationTimer::Run (float targetVal, Managed obj, string updateFunc, string finishedFunc, float startingVal = 0, bool loop = false, float speed = 1.0, Param params = null, int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 660 of file tools.c.
    {
        SetRunning(true);
        m_TargetObject = obj;
        m_UpdateFunction = updateFunc;
        m_FinishedFunction = finishedFunc;
        m_TargetValueOriginal = targetVal;
        m_TargetValue = targetVal;
        m_time = speed;
        m_loop = loop;
        m_Active = true;
        m_Params = params;
        m_Value = startingVal;
    }
References m_Active, m_FinishedFunction, m_loop, m_Params, m_TargetObject, m_TargetValue, m_TargetValueOriginal, m_time, m_UpdateFunction, m_Value, and SetRunning().
Referenced by Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUndergroundPresenceUpdate().
Tick()
override void AnimationTimer::Tick (float timeslice) inline private
Ticks the timer, is called by timer subsystem.
Definition at line 689 of file tools.c.
    {
        if ( !m_Active )
            return;
        float diff = Math.AbsFloat(m_TargetValue - m_Value);
        float step = m_time * timeslice;
        if (diff < step)
        {
            m_Value = m_TargetValue;
            if (!m_loop)
            {
                m_Active = false;
            }
            else
            {
                if (m_TargetValue == m_TargetValueOriginal)
                {
                    m_TargetValue = 0;
                }
                else
                {
                    m_TargetValue = m_TargetValueOriginal;
                }
            }
            GetGame().GameScript.CallFunction(m_TargetObject, m_FinishedFunction, NULL, m_Params);
        }
        else
        {
            if (m_TargetValue > m_Value)
            {
                m_Value += step;
            }
            else
            {
                m_Value -= step;
            }
        }
        GetGame().GameScript.CallFunction(m_TargetObject, m_UpdateFunction, NULL, m_Params);
    }
References Math::AbsFloat(), ScriptModule::CallFunction(), CGame::GameScript, GetGame(), m_Active, m_FinishedFunction, m_loop, m_Params, m_TargetObject, m_TargetValue, m_TargetValueOriginal, m_time, m_UpdateFunction, and m_Value.
Member Data Documentation
m_Active
private bool AnimationTimer::m_Active private
Definition at line 641 of file tools.c.
Referenced by IsRunning(), Run(), and Tick().
m_FinishedFunction
protected string AnimationTimer::m_FinishedFunction private
Definition at line 647 of file tools.c.
Referenced by Run(), and Tick().
m_Params
protected ref Param AnimationTimer::m_Params private
Definition at line 648 of file tools.c.
Referenced by Run(), and Tick().
m_TargetObject
protected Managed AnimationTimer::m_TargetObject private
Definition at line 645 of file tools.c.
Referenced by Run(), and Tick().
m_TargetValue
private float AnimationTimer::m_TargetValue private
Definition at line 642 of file tools.c.
Referenced by Run(), and Tick().
m_TargetValueOriginal
private float AnimationTimer::m_TargetValueOriginal private
Definition at line 643 of file tools.c.
Referenced by Run(), and Tick().
m_UpdateFunction
protected string AnimationTimer::m_UpdateFunction private
Definition at line 646 of file tools.c.
Referenced by Run(), and Tick().
m_Value
private float AnimationTimer::m_Value private
Definition at line 644 of file tools.c.
Referenced by GetValue(), Run(), and Tick().