DayzKode: Header Class Reference
Header Class Reference
Private Member Functions
void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void Header (LayoutHolder parent, string function_name)
void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void SetActive (bool active)
void SetItemPreview (EntityAI entity_ai)
void SetName (string name)
void ShowCollapseButton (bool state)
Private Attributes
protected Widget m_CollapseButton
protected int m_DefaultColor
protected int m_DefaultFontSize
protected Widget m_DownArrowButton
protected EntityAI m_Entity
protected TextWidget m_HeaderText
protected Widget m_UpArrowButton
Detailed Description
Definition at line 1 of file header.c.
Constructor & Destructor Documentation
Header()
void Header::Header (LayoutHolder parent, string function_name) inline private
Definition at line 13 of file header.c.
    {
        m_CollapseButton    = GetMainWidget().FindAnyWidget( "collapse_button" );
        m_UpArrowButton     = GetMainWidget().FindAnyWidget( "opened" );
        m_DownArrowButton   = GetMainWidget().FindAnyWidget( "closed" );
        #ifdef PLATFORM_CONSOLE
            m_CollapseButton.Show( false );
        #else
        WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( m_CollapseButton,  m_Parent, function_name );
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( m_CollapseButton,  m_Parent, "OnDropReceivedFromHeader" );
        #endif
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( GetMainWidget(),  m_Parent, "OnDropReceivedFromHeader" );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( GetMainWidget(),  this, "DraggingOverHeader" );
        m_HeaderText        = TextWidget.Cast( GetMainWidget().FindAnyWidget( "TextWidget0" ) );
        m_DefaultColor      = GetRootWidget().GetColor();
    }
References FindAnyWidget(), WidgetEventHandler::GetInstance(), m_CollapseButton, m_DefaultColor, m_DownArrowButton, m_HeaderText, m_Parent, m_UpArrowButton, WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), and WidgetEventHandler::RegisterOnMouseButtonDown().
Member Function Documentation
DraggingOverHeader()
void Header::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 49 of file header.c.
    {
        if ( w == null )
            return;
        Container parent_container = Container.Cast( m_Parent );
        parent_container.DraggingOverHeader( w, x, y, receiver );
    }
References m_Parent, x, and y.
OnDropReceivedFromHeader()
void Header::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 58 of file header.c.
    {
        Container parent_container = Container.Cast( m_Parent );
        parent_container.OnDropReceivedFromHeader( w, x, y, receiver );
    }
References m_Parent, x, and y.
SetActive()
override void Header::SetActive (bool active) inline private
Definition at line 64 of file header.c.
    {
        super.SetActive( active );
        if ( active )
            GetMainWidget().SetColor( ARGBF( 1, 1, 0, 0 ) );
        else
            GetMainWidget().SetColor( m_DefaultColor );
    }
References ARGBF(), and m_DefaultColor.
Referenced by LayoutHolder::SetActive(), and LayoutHolder::SetLastActive().
SetItemPreview()
void Header::SetItemPreview (EntityAI entity_ai) inline private
Definition at line 39 of file header.c.
    {
        #ifndef PLATFORM_CONSOLE
        m_Entity = entity_ai;
        ItemPreviewWidget item_preview = ItemPreviewWidget.Cast( GetMainWidget().FindAnyWidget( "Render" ) );
        item_preview.SetItem(entity_ai);
        item_preview.SetView( entity_ai.GetViewIndex() );
        #endif
    }
References FindAnyWidget(), m_Entity, ItemPreviewWidget::SetItem(), and ItemPreviewWidget::SetView().
SetName()
void Header::SetName (string name) inline private
Definition at line 33 of file header.c.
    {
        name.ToUpper();
        m_HeaderText.SetText( name );
    }
References m_HeaderText, name, and string::ToUpper().
Referenced by HandsPreview::CreateNewIcon(), AttachmentCategoriesRow::Init(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetHeaderName(), ZombieContainer::SetHeaderName(), Container::UpdateHeaderText(), and VicinityContainer::VicinityContainer().
ShowCollapseButton()
void Header::ShowCollapseButton (bool state) inline private
Definition at line 74 of file header.c.
    {
        m_CollapseButton.Show(state);
    }
References m_CollapseButton.
Referenced by CollapsibleContainer::UpdateCollapseButtons().
Member Data Documentation
m_CollapseButton
protected Widget Header::m_CollapseButton private
Definition at line 8 of file header.c.
Referenced by Header(), ClosableHeader::MouseLeave(), ShowCollapseButton(), and HandsHeader::ShowCollapseButtons().
m_DefaultColor
protected int Header::m_DefaultColor private
Definition at line 3 of file header.c.
Referenced by ClosableHeader::ClosableHeader(), HandsHeader::HandsHeader(), Header(), ClosableHeader::SetActive(), and SetActive().
m_DefaultFontSize
protected int Header::m_DefaultFontSize private
Definition at line 4 of file header.c.
Referenced by ClosableHeader::ClosableHeader(), CollapsibleHeader::CollapsibleHeader(), and HandsHeader::HandsHeader().
m_DownArrowButton
protected Widget Header::m_DownArrowButton private
Definition at line 10 of file header.c.
Referenced by Header(), and CollapsibleHeader::SetArrowButtonOpened().
m_Entity
protected EntityAI Header::m_Entity private
Definition at line 6 of file header.c.
Referenced by ClosableHeader::MouseEnter(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), SetItemPreview(), ClosableHeader::UpdateFlip(), and ClosableHeader::~ClosableHeader().
m_HeaderText
protected TextWidget Header::m_HeaderText private
Definition at line 11 of file header.c.
Referenced by Header(), ClosableHeader::SetName(), and SetName().
m_UpArrowButton
protected Widget Header::m_UpArrowButton private
Definition at line 9 of file header.c.
Referenced by Header(), and CollapsibleHeader::SetArrowButtonOpened().