DayzKode: HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
Private Member Functions
void Abort (FSMEventBase abort_event=NULL)
void AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t)
adds transition into transition table
FSMStateBase FindAbortDestinationState (FSMEventBase e)
i
protected int FindFirstCompletionTransition ()
protected int FindFirstUnguardedTransition (FSMEventBase e)
FSMStateBase FindGuardedTransitionState (FSMStateBase s, FSMEventBase e)
FSMStateBase FindTransitionState (FSMStateBase s, FSMEventBase e)
FSMStateBase GetCurrentState ()
bool GetHierarchyPath (FSMStateBase state, out array< FSMStateBase > path)
returns hierarchic state (path to root) of a state
FSMStateBase GetOwnerState ()
void HFSMBase (FSMStateBase ownerState=NULL)
bool IsRunning ()
returns true if machine is in running state
protected ProcessEventResult LocalTransition (int i, FSMEventBase e)
FSMStateBase ProcessAbortEvent (FSMEventBase e, out ProcessEventResult result)
instructs the hierarchical state machine to process the event e
protected ProcessEventResult ProcessAbortTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
protected ProcessEventResult ProcessCompletionTransitions ()
ProcessEventResult ProcessEvent (FSMEventBase e)
instructs the hierarchical state machine to process the event e
protected ProcessEventResult ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
instructs the state machine to process the event locally - no hierarchy is crossed
void SetInitialState (FSMStateBase initial_state)
void Start (FSMEventBase initial_event=NULL, bool useExistingState=false)
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
void Terminate (FSMEventBase terminal_event=NULL)
terminates the state machine
void Update (float dt)
if machine running, call OnUpdate() on current state
Private Attributes
protected bool m_HasCompletions = false
fsm transition table
protected ref FSMStateBase m_InitialState
state that owns this fsm (or null if root)
protected FSMStateBase m_OwnerState
current fsm state
protected ref FSMStateBase m_State
protected ref array< ref FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > > m_Transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>>
configurable initial state of the machine
Detailed Description
Definition at line 19 of file hfsmbase.c.
Constructor & Destructor Documentation
HFSMBase()
void HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::HFSMBase (FSMStateBase ownerState = NULL) inline private
Definition at line 27 of file hfsmbase.c.
    {
        m_OwnerState = ownerState;
    }
Member Function Documentation
Abort()
void HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort (FSMEventBase abort_event = NULL) inline private
Definition at line 117 of file hfsmbase.c.
    {
        fsmDebugPrint("[hfsm] " + this.ToString() + "::Abort(" + abort_event.ToString() + ")");
        if (IsRunning())
        {
            m_State.OnAbort(abort_event);
            m_State = NULL;
        }
    }
References fsmDebugPrint(), IsRunning(), m_State, ToString(), and string::ToString().
AddTransition()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t) inline private
adds transition into transition table
Definition at line 74 of file hfsmbase.c.
    {
        m_Transitions.Insert(t);
        //fsmDebugSpam("[hfsm] +++ ow=" + this.GetOwnerState() + " this=" + this + " t=" + t + " state=" + t.m_srcState + "-------- event=" + t.m_event + "[G=" + t.m_guard +"]/A=" + t.m_action + " --------|> dst=" + t.m_dstState);
        if (t.m_event == NULL)
        {
            Print("Warning (performance): FSM " + this + " has completion transition for src=" + t.m_srcState + " ---NULL----|> dst=" + t.m_dstState);
            m_HasCompletions = true;
        }
    }
References Print().
FindAbortDestinationState()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState (FSMEventBase e) inline private
i
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
FSM_ABORTED state machine has aborted
Definition at line 175 of file hfsmbase.c.
    {
        if (GetOwnerState())
            fsmDebugPrint("[hfsm] SUB! " + GetOwnerState().Type().ToString() + "::FindAbortDestinationState(" + e.Type().ToString() + ")");
        else
            fsmDebugPrint("[hfsm] root::FindAbortDestinationState(" + e.Type().ToString() + ")");
        // 1) look in submachine first (if any)
        if (m_State.HasFSM())
        {
            HFSMBase<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> a = m_State.GetFSM();
            FSMStateBase abort_dst = a.FindAbortDestinationState(e);
            if (abort_dst)
            {
                return abort_dst;
            }
        }
        // 2) local transitions
        int i = FindFirstUnguardedTransition(e);
        if (i == -1)
        {
            fsmDebugPrint("[hfsm] abort event has no transition: src=" + m_State.ToString() + " e=" + e.Type().ToString());
            return NULL;
        }
        FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
        return t.m_dstState;
    }
References fsmDebugPrint(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
FindFirstCompletionTransition()
protected int HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindFirstCompletionTransition () inline private
Definition at line 439 of file hfsmbase.c.
    {
        if (IsRunning())
        {
            FSMStateBase curr_state = m_State;
            int count = m_Transitions.Count();
            for (int i = 0; i < count; ++i)
            {
                FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
                //fsmDebugPrint("[hfsm] (local) matching state=" + t.m_srcState + "-------- event=" + t.m_event + "[G=" + t.m_guard +"]/A=" + t.m_action + " --------|> dst=" + t.m_dstState);
                if ((t.m_srcState.Type() == curr_state.Type()) && (t.m_event == NULL))
                {
                    bool hasGuard = t.m_guard != NULL;
                    if (!hasGuard || (hasGuard && t.m_guard.GuardCondition(NULL)))      // 1) exec guard (if any)
                    {
                        return i;
                    }
                }
            }
        }
        return -1;
    }
References IsRunning(), and m_State.
FindFirstUnguardedTransition()
protected int HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindFirstUnguardedTransition (FSMEventBase e) inline private
Definition at line 381 of file hfsmbase.c.
    {
        FSMStateBase curr_state = m_State;
        int count = m_Transitions.Count();
        for (int i = 0; i < count; ++i)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
            if ((t.m_srcState == curr_state) && (t.m_event != NULL) && (t.m_event.Type() == e.Type()))
            {
                //fsmDebugSpam("[hfsm] [" + i + "/" + count + "] *** matched! t=" + t + " state=" + t.m_srcState + "-------- event=" + t.m_event + "[G=" + t.m_guard +"]/A=" + t.m_action + " --------|> dst=" + t.m_dstState);
                bool hasGuard = t.m_guard != NULL;
                if (!hasGuard || (hasGuard && t.m_guard.GuardCondition(e)))     // 1) exec guard (if any)
                {
                    return i;
                }
            }
            //else fsmDebugSpam("[hfsm][" + i + "/" + count + "] ... matching  t=" + t + " state=" + t.m_srcState + "-------- event=" + t.m_event + "[G=" + t.m_guard +"]/A=" + t.m_action + " --------|> dst=" + t.m_dstState);
        }
        return -1;
    }
References m_State.
FindGuardedTransitionState()
FSMStateBase HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindGuardedTransitionState (FSMStateBase s, FSMEventBase e) inline private
Definition at line 419 of file hfsmbase.c.
    {
        FSMStateBase curr_state = s;
        int count = m_Transitions.Count();
        for (int i = 0; i < count; ++i)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
            if ((t.m_srcState == curr_state) && (t.m_event != NULL) && (t.m_event.Type() == e.Type()))
            {
                bool hasGuard = t.m_guard != NULL;
                if (!hasGuard || (hasGuard && t.m_guard.GuardCondition(e)))     // 1) exec guard (if any)
                {
                    return t.m_dstState;
                }
            }
        }
        return null;
    }
FindTransitionState()
FSMStateBase HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindTransitionState (FSMStateBase s, FSMEventBase e) inline private
Definition at line 403 of file hfsmbase.c.
    {
        FSMStateBase curr_state = s;
        int count = m_Transitions.Count();
        for (int i = 0; i < count; ++i)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
            if ((t.m_srcState == curr_state) && (t.m_event != NULL) && (t.m_event.Type() == e.Type()))
            {
                return t.m_dstState;
            }
        }
        return null;
    }
GetCurrentState()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetCurrentState () inline private
Returns
returns currently active state within this machine (i.e. not hierarchic state)
Definition at line 35 of file hfsmbase.c.
    {
        return m_State;
    }
References m_State.
GetHierarchyPath()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetHierarchyPath (FSMStateBase state, out array< FSMStateBase > path) inline private
returns hierarchic state (path to root) of a state
Parameters
[in] state state the path is starting
[out] path current hierarchic state
Returns
true if current state returned in path argument, false otherwise
Definition at line 52 of file hfsmbase.c.
    {
        FSMStateBase curr = state;
        while (curr)
        {
          path.Insert(curr);
          curr = curr.GetParentState();
        }
        return path.Count() > 0;
    }
References path.
GetOwnerState()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetOwnerState () inline private
Returns
returns state that is owner of this fsm submachine. returns null if this is a root machine.
Definition at line 42 of file hfsmbase.c.
    {
        return m_OwnerState;
    }
IsRunning()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::IsRunning () inline private
returns true if machine is in running state
Definition at line 104 of file hfsmbase.c.
{ return m_State != NULL; }
References m_State.
LocalTransition()
protected ProcessEventResult HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::LocalTransition (int i, FSMEventBase e) inline private
Definition at line 509 of file hfsmbase.c.
    {
        FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
        ProcessEventResult ret = ProcessLocalTransition(t, e);
        return ret;
    }
ProcessAbortEvent()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent (FSMEventBase e, out ProcessEventResult result) inline private
instructs the hierarchical state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
FSM_ABORTED state machine has aborted
Definition at line 214 of file hfsmbase.c.
    {
        if (GetOwnerState())
            fsmDebugPrint("[hfsm] SUB! " + GetOwnerState().Type().ToString() + "::ProcessAbortEvent(" + e.Type().ToString() + ")");
        else
            fsmDebugPrint("[hfsm] root::ProcessAbortEvent(" + e.Type().ToString() + ")");
        // 1) look in submachine first (if any)
        if (m_State.HasFSM())
        {
            HFSMBase<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> a = m_State.GetFSM();
            ProcessEventResult subfsm_res;
            FSMStateBase abort_dst = a.ProcessAbortEvent(e, subfsm_res);
            switch (subfsm_res)
            {
                case ProcessEventResult.FSM_OK:
                {
                    fsmDebugPrint("[hfsm] event processed by sub machine=" + m_State.ToString());
                    result = subfsm_res;        // 1.1) submachine accepted event
                    return NULL;
                }
                case ProcessEventResult.FSM_ABORTED:
                {
                    fsmDebugPrint("[hfsm] aborted sub machine=" + m_State.ToString());
                    m_State.OnAbort(e); // 1.2) submachine aborted, abort submachine owner (i.e. this)
                    if (GetOwnerState() == abort_dst.GetParentState())
                    {
                        fsmDebugPrint("[hfsm] aborted sub machine=" + m_State.ToString() + " & abort destination reached.");
                        m_State = abort_dst;
                        m_State.OnEntry(e);     // 1.3) submachine aborted, call onEntry on new state (cross-hierarchy transition)
                        result = ProcessEventResult.FSM_OK;
                        return NULL;
                    }
                    else
                    {
                        result = ProcessEventResult.FSM_ABORTED; // 1.4) submachine has aborted, look for destination state in parent
                        return NULL;
                    }
                    break;
                }
                case ProcessEventResult.FSM_TERMINATED:
                {
                    break; // submachine has finished, look for local transitions from exited submachine
                }
                case ProcessEventResult.FSM_NO_TRANSITION:
                {
                    fsmDebugPrint("[hfsm] aborted (but no transition) sub machine=" + m_State.ToString());
                    break; // submachine has no transition, look for transitions in local machine
                }
            }
        }
        // 2) local transitions
        int i = FindFirstUnguardedTransition(e);
        if (i == -1)
        {
            fsmDebugPrint("[hfsm] abort event has no transition: src=" + m_State.ToString() + " e=" + e.Type().ToString());
            result = ProcessEventResult.FSM_NO_TRANSITION;
            return NULL;
        }
        FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
        ProcessEventResult res = ProcessAbortTransition(t, e);
        result = res;
        switch (res)
        {
            case ProcessEventResult.FSM_OK:
            {
                //fsmDebugSpam("[hfsm] abort event processed by machine=" + m_State.ToString());
                return NULL; // machine accepted event
            }
            case ProcessEventResult.FSM_ABORTED:
            {
                fsmDebugPrint("[hfsm] aborted sub machine=" + m_State.ToString() + " will fall-through to dst=" + t.m_dstState);
                return t.m_dstState; // store destination state for parent(s)
            }
            case ProcessEventResult.FSM_TERMINATED:
            {
                fsmDebugPrint("[hfsm] aborted & terminated sub machine=" + m_State.ToString());
                break; // submachine has finished, look for local transitions from exited submachine
            }
            case ProcessEventResult.FSM_NO_TRANSITION:
            {
                break; // submachine has no transition, look for transitions in local machine
            }
        }
        return NULL;
    }
References fsmDebugPrint(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
ProcessAbortTransition()
protected ProcessEventResult HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
Definition at line 135 of file hfsmbase.c.
    {
        fsmDebugPrint("[hfsm] (local abort) state=" + t.m_srcState.ToString() + "-------- ABORT event=" + e.ToString() + "[G=" + t.m_guard.ToString() +"]/A=" + t.m_action.ToString() + " --------|> dst=" + t.m_dstState.ToString());
        m_State.OnAbort(e);         // 1) call onAbort on old state
        if (t.m_action)
            t.m_action.Action(e);   // 2) execute transition action (if any)
        auto tmp = t.m_srcState.GetParentState();
        if (tmp == t.m_dstState.GetParentState())
        {
            m_State = t.m_dstState;     // 3) change state to new (or NULL)
            if (t.m_dstState != NULL)
            {
                m_State.OnEntry(e);     // 4a1) call onEntry on new state (see 4a2) )
                return ProcessEventResult.FSM_OK;
            }
            else
            {
                fsmDebugPrint("[hfsm] abort & terminating fsm: state=" + t.m_srcState.ToString() + " event=" + e.ToString());
                return ProcessEventResult.FSM_TERMINATED; // 4b) or terminate
            }
        }
        else
        {
            m_State = NULL;
            return ProcessEventResult.FSM_ABORTED; // 4c) or signal abort to parent (with appropriate transition)
        }
    }
References fsmDebugPrint(), and m_State.
ProcessCompletionTransitions()
protected ProcessEventResult HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessCompletionTransitions () inline private
Definition at line 516 of file hfsmbase.c.
    {
        int completionIdx = FindFirstCompletionTransition();
        while (completionIdx != -1)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> row = m_Transitions.Get(completionIdx);
            ProcessEventResult res;
            if (row.m_dstState != NULL)
            {
                // this is regular completion transition
                if (row.m_srcState.GetParentState() == row.m_dstState.GetParentState())
                    res = LocalTransition(completionIdx, NULL); // transition is within this state machine
                else
                    Error("cross-hierarchy transition or misconfigured transition detected!");
                    //res = HierarchicTransition(completionIdx, NULL); // transition has to cross hierarchy
            }
            else
            {
                // this is terminating completion transition
                if (row.m_srcState.GetParentState() == GetOwnerState())
                    res = LocalTransition(completionIdx, NULL); // terminating transition is within this state machine
                else
                    Error("cross-hierarchy transition or misconfigured transition detected!");
                    //res = HierarchicTransition(completionIdx, NULL); // source node crosses hierarchy (terminate lies always within this machine)
            }
            completionIdx = FindFirstCompletionTransition();
        }
        return ProcessEventResult.FSM_NO_TRANSITION;
    }
References Error().
ProcessEvent()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent (FSMEventBase e) inline private
instructs the hierarchical state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
FSM_NO_TRANSITION if no unguarded transition found in submachine or local machine
FSM_TERMINATED state machine has terminated
Definition at line 316 of file hfsmbase.c.
    {
        if (GetOwnerState())
            fsmDebugPrint("[hfsm] SUB!::" + GetOwnerState().Type().ToString() + "::ProcessEvent(" + e.Type().ToString() + ")");
        else
            fsmDebugPrint("[hfsm] root::ProcessEvent(" + e.Type().ToString() + " =" + e.DumpToString());
        // 1) completion transitions have priority (if any)
        if (m_HasCompletions)
            ProcessCompletionTransitions();
        // 2) submachine then (if any)
        if (m_State.HasFSM())
        {
            ProcessEventResult subfsm_res = m_State.ProcessEvent(e);
            switch (subfsm_res)
            {
                case ProcessEventResult.FSM_OK:
                {
                    fsmDebugSpam("[hfsm] event processed by sub machine=" + m_State.ToString());
                    return subfsm_res; // submachine accepted event
                }
                case ProcessEventResult.FSM_TERMINATED:
                {
                    break; // submachine has finished, look for local transitions from exited submachine
                }
                case ProcessEventResult.FSM_NO_TRANSITION:
                {
                    break; // submachine has no transition, look for transitions in local machine
                }
            }
        }
        // 3) local transitions
        int i = FindFirstUnguardedTransition(e);
        if (i == -1)
        {
            fsmDebugPrint("[hfsm] event has no transition: src=" + m_State.ToString() + " e=" + e.Type().ToString());
            return ProcessEventResult.FSM_NO_TRANSITION;
        }
        FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> row = m_Transitions.Get(i);
        ProcessEventResult res;
        if (row.m_dstState != NULL)
        {
            // this is regular transition
            if (row.m_srcState.GetParentState() == row.m_dstState.GetParentState())
                res = LocalTransition(i, e); // transition is within this state machine
            else
                Error("cross-hierarchy transition or misconfigured transition detected!");
                //res = HierarchicTransition(i, e); // transition has to cross hierarchy
        }
        else
        {
            // this is terminating transition
            if (row.m_srcState.GetParentState() == GetOwnerState())
                res = LocalTransition(i, e); // terminating transition is within this state machine
            else
                Error("cross-hierarchy transition or misconfigured transition detected!");
                //res = HierarchicTransition(i, e); // source node crosses hierarchy (terminate lies always within this machine)
        }
        return res;
    }
References Error(), fsmDebugPrint(), fsmDebugSpam(), m_State, ToString(), float::ToString(), string::ToString(), and Type.
ProcessLocalTransition()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
instructs the state machine to process the event locally - no hierarchy is crossed
Parameters
[in] t the transition in m_Transitions
[in] e event that will be used to process transition from current state
Returns
FSM_OK or FSM_TERMINATED
Definition at line 471 of file hfsmbase.c.
    {
        fsmDebugPrint("[hfsm] (local) state=" + t.m_srcState.ToString() + "-------- event=" + e.ToString() + "[G=" + t.m_guard.ToString() +"]/A=" + t.m_action.ToString() + " --------|> dst=" + t.m_dstState.ToString());
        m_State.OnExit(e);          // 1) call onExit on old state
        if (t.m_action)
            t.m_action.Action(e);   // 2) execute transition action (if any)
        m_State = t.m_dstState;     // 3) change state to new
        if (t.m_dstState != NULL)
        {
            m_State.OnEntry(e);     // 4a) call onEntry on new state
            if (GetOwnerState())
                GetOwnerState().OnSubMachineChanged(t.m_srcState, t.m_dstState);    // 5a) notify owner state about change in submachine
            if (m_State)
                m_State.OnStateChanged(t.m_srcState, t.m_dstState); // 5b) notify current state about change in machine
            return ProcessEventResult.FSM_OK;
        }
        else
        {
            fsmDebugPrint("[hfsm] terminating fsm: state=" + t.m_srcState.ToString() + " event=" + e.ToString());
            if (GetOwnerState())
                GetOwnerState().OnSubMachineChanged(t.m_srcState, NULL);    // 5) notify owner state about change in submachine
            return ProcessEventResult.FSM_TERMINATED; // 4b) or terminate
        }
    }
References fsmDebugPrint(), and m_State.
SetInitialState()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::SetInitialState (FSMStateBase initial_state) inline private
Parameters
[in] initial_state state the machine will be entered to after Start()
[in] initial_event event that will be used to start the machine
Definition at line 67 of file hfsmbase.c.
    {
        m_InitialState = initial_state;
    }
Start()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start (FSMEventBase initial_event = NULL, bool useExistingState = false) inline private
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
Parameters
[in] e optional event for starting the machind
Definition at line 89 of file hfsmbase.c.
    {
        fsmDebugPrint("[hfsm] " + this.ToString() + "::Start(" + initial_event.ToString() + "), init_state=" + m_InitialState.ToString());
        if (!useExistingState)
            m_State = m_InitialState;
        m_State.OnEntry(initial_event);
        if (m_HasCompletions)
            ProcessCompletionTransitions();
    }
References fsmDebugPrint(), m_State, ToString(), and string::ToString().
Terminate()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate (FSMEventBase terminal_event = NULL) inline private
terminates the state machine
Definition at line 108 of file hfsmbase.c.
    {
        fsmDebugPrint("[hfsm] " + this.ToString() + "::Terminate(" + terminal_event.ToString() + ")");
        if (IsRunning())
        {
            m_State.OnExit(terminal_event);
            m_State = NULL;
        }
    }
References fsmDebugPrint(), IsRunning(), m_State, ToString(), and string::ToString().
Update()
HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Update (float dt) inline private
if machine running, call OnUpdate() on current state
Definition at line 129 of file hfsmbase.c.
    {
        if (IsRunning())
            m_State.OnUpdate(dt);
    }
References IsRunning(), and m_State.
Member Data Documentation
m_HasCompletions
protected bool HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_HasCompletions = false private
fsm transition table
Definition at line 25 of file hfsmbase.c.
m_InitialState
protected ref FSMStateBase HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_InitialState private
state that owns this fsm (or null if root)
Definition at line 23 of file hfsmbase.c.
m_OwnerState
protected FSMStateBase HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_OwnerState private
current fsm state
Definition at line 22 of file hfsmbase.c.
m_State
protected ref FSMStateBase HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_State private
Definition at line 21 of file hfsmbase.c.
m_Transitions
protected ref array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> > HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_Transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>> private
configurable initial state of the machine
Definition at line 24 of file hfsmbase.c.