DayzKode: ServerBrowserTab Class Reference
ServerBrowserTab Class Reference
Private Member Functions
override int AddSorted (GetServersResultRow entry)
override void ApplyFilters ()
override void ApplyFilters ()
override void ApplyFilters ()
void ButtonCancelToRefresh ()
void ButtonRefreshToCancel ()
bool CanRefreshServerList ()
override void ColorDisable (Widget w)
override void ColorDisable (Widget w)
override void ColorHighlight (Widget w)
override void ColorHighlight (Widget w)
override void ColorNormal (Widget w)
override void ColorNormal (Widget w)
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
void DisableFilters ()
override void Focus ()
override void Focus ()
protected ServerBrowserEntry GetServerEntryByIndex (int index)
protected ServerBrowserEntry GetServerEntryByIndex (int index, string server_id)
int GetTimeOfDayEnum (string time_of_day)
override bool IsFocusable (Widget w)
override void Left ()
override void LeftHold ()
override void LeftRelease ()
void LoadEntries (int cur_page_index, GetServersResultRowArray page)
protected void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries)
void LoadingServersStop ()
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
bool OnClickPage (Widget w)
void OnClickPageEnd ()
void OnClickPageFirst ()
void OnClickPageNext ()
void OnClickPagePrev ()
override void OnFilterChanged ()
override void OnFilterChanged ()
override void OnFilterChanged ()
override void OnFilterFocus (Widget w)
override void OnFilterFocusLost (Widget w)
protected void OnInputDeviceChanged (EInputDeviceType pInputDeviceType)
override void OnLoadServerModsAsync (string server_id, array< string > mods)
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response)
override void OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response)
void OnLoadServersAsyncFinished ()
void OnLoadServersAsyncFinished ()
override void OnLoadServersAsyncPC (ref GetServersResult result_list, EBiosError error, string response)
void OnLoadServersAsyncPCFinished ()
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override void PressA ()
override void PressA ()
override void PressSholderLeft ()
override void PressSholderLeft ()
override void PressSholderRight ()
override void PressSholderRight ()
override void PressX ()
override void PressX ()
override void PressY ()
override void PressY ()
override void RefreshList ()
override void RefreshList ()
override void RefreshList ()
override void ResetFilters ()
override void ResetFilters ()
override void ResetFilters ()
override void Right ()
override void RightHold ()
override void RightRelease ()
override void SelectServer (ServerBrowserEntry server)
void SetEnableFilters (bool enable)
void SetEnableFilters (bool enable)
void SetEnableServers (bool enable)
void SetEnableServers (bool enable)
void SetFocusFilters ()
void SetFocusFilters ()
void SetFocusServers ()
void SetFocusServers ()
void SetPageIndex (int page_index)
override void SetSort (ESortType type, ESortOrder order)
void ShowHideConsoleWidgets ()
void ShowHideConsoleWidgets ()
int SortedInsert (GetServersResultRow entry, ESortType sort_type)
int SortedInsertAsc (GetServersResultRow entry, ESortType sort_type)
int SortedInsertDesc (GetServersResultRow entry, ESortType sort_type)
void ToggleSort (ESortType type)
void UpdatePageButtons ()
void UpdatePageButtons ()
void UpdateServerList ()
void UpdateStatusBar ()
void ~ServerBrowserTabPc ()
Private Attributes
protected ref array< ButtonWidget > m_BtnPages
protected ButtonWidget m_BtnPagesFirst
protected ButtonWidget m_BtnPagesLast
protected Widget m_ButtonPageLeftImg
protected Widget m_ButtonPageRightImg
protected Widget m_FilterPanelAccTime
protected Widget m_FilterPanelPing
protected Widget m_FilterSearchIP
protected Widget m_FilterSearchIPBox
private bool m_IsFilterChanged
private bool m_IsFilterFocused
protected int m_PageEndNum
protected int m_PageIndex
protected int m_PagesCount
protected int m_PageStartNum
protected TextWidget m_PnlPagesLoadingText
protected Widget m_PnlPagesPanel
protected int m_PreviousPage
protected ref array< ref ServerBrowserEntry > m_ServerListEntiers
protected ref array< ref ServerBrowserEntry > m_ServerListEntries
protected int m_ServersEstimateCount
protected ref TStringArray m_TempTime = new TStringArray
protected int m_TimeLastServerRefresh
protected int m_TimeLastServerRefreshHoldButton
protected int m_TotalServersCount
private Widget m_WidgetNavFilters
protected bool m_MouseKeyboardControlled private Widget m_WidgetNavFilters
private Widget m_WidgetNavServers
protected const int PAGES_BUTTONS_COUNT = 10
protected const int SERVERS_VISIBLE_COUNT = 24
Detailed Description
Definition at line 1 of file serverbrowsertabconsole.c.
Constructor & Destructor Documentation
~ServerBrowserTabPc()
void ServerBrowserTab::~ServerBrowserTabPc () inline private
Definition at line 129 of file serverbrowsertabpc.c.
    {
    }
Member Function Documentation
AddSorted()
override int ServerBrowserTab::AddSorted (GetServersResultRow entry) inline private
Definition at line 607 of file serverbrowsertabpc.c.
    {
        int index_host = SortedInsert( entry, ESortType.HOST );
        int index_time = SortedInsert( entry, ESortType.TIME );
        int index_popu = SortedInsert( entry, ESortType.POPULATION );
        int index_slot = SortedInsert( entry, ESortType.SLOTS );
        int index_ping = SortedInsert( entry, ESortType.PING );
        int index_favo = SortedInsert( entry, ESortType.FAVORITE );
        int index_pass = SortedInsert( entry, ESortType.PASSWORDED );
        switch ( m_SortType )
        {
            case ESortType.HOST:
                return index_host;
            case ESortType.TIME:
                return index_time;
            case ESortType.POPULATION:
                return index_popu;
            case ESortType.SLOTS:
                return index_slot;
            case ESortType.PING:
                return index_ping;
            case ESortType.FAVORITE:
                return index_favo;
            case ESortType.PASSWORDED:
                return index_pass;
        }
        return 0;
    }
References m_SortType.
ApplyFilters() [1/3]
override void ServerBrowserTab::ApplyFilters () inline private
Definition at line 233 of file serverbrowsertabconsole.c.
    {
        m_IsFilterChanged = false;
        m_CurrentFilterInput = m_Filters.GetFilterOptionsConsoles();
        RefreshList();
    }
References m_CurrentFilterInput, m_Filters, and RefreshList().
ApplyFilters() [2/3]
override void ServerBrowserTab::ApplyFilters () inline private
Definition at line 305 of file serverbrowsertabconsolepages.c.
    {
        if ( m_IsFilterChanged )
        {
            SetCurrentPage(1);
        }
        m_IsFilterChanged = false;
        m_CurrentFilterInput = m_Filters.GetFilterOptionsConsoles();
        RefreshList();
    }
References m_CurrentFilterInput, m_Filters, ServerBrowserTabConsolePages::RefreshList(), and SetCurrentPage().
ApplyFilters() [3/3]
override void ServerBrowserTab::ApplyFilters () inline private
Definition at line 181 of file serverbrowsertabpc.c.
    {
        m_Filters.SaveFilters();
        //m_CurrentFilterInput = m_Filters.GetFilterOptionsPC();
        RefreshList();
        ButtonDisable( m_ApplyFilter );
        ButtonEnable( m_RefreshList );
    }
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Filters, m_RefreshList, and ServerBrowserTabPc::RefreshList().
ButtonCancelToRefresh()
void ServerBrowserTab::ButtonCancelToRefresh () inline private
Definition at line 1115 of file serverbrowsertabpc.c.
    {
        ButtonWidget btn = ButtonWidget.Cast( m_RefreshList );
        btn.SetText( "#STR_server_browser_tab_root_filters_root_filters_content_refresh_list_button0" );
    }
References m_RefreshList.
ButtonRefreshToCancel()
void ServerBrowserTab::ButtonRefreshToCancel () inline private
Definition at line 1109 of file serverbrowsertabpc.c.
    {
        ButtonWidget btn = ButtonWidget.Cast( m_RefreshList );
        btn.SetText( "#menu_cancel" );
    }
References m_RefreshList.
CanRefreshServerList()
bool ServerBrowserTab::CanRefreshServerList () inline private
Definition at line 266 of file serverbrowsertabconsolepages.c.
    {
        return m_LoadingFinished;
    }
References m_LoadingFinished.
ColorDisable() [1/2]
override void ServerBrowserTab::ColorDisable (Widget w) inline private
Definition at line 429 of file serverbrowsertabconsole.c.
    {
        #ifdef PLATFORM_WINDOWS
        SetFocus( null );
        #endif
        ButtonWidget button = ButtonWidget.Cast( w );
        if( button )
        {
            button.SetTextColor( ColorManager.COLOR_DISABLED_TEXT );
        }
    }
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
Referenced by ButtonDisable().
ColorDisable() [2/2]
override void ServerBrowserTab::ColorDisable (Widget w) inline private
Definition at line 667 of file serverbrowsertabconsolepages.c.
    {
        #ifdef PLATFORM_WINDOWS
        SetFocus( null );
        #endif
        ButtonWidget button = ButtonWidget.Cast( w );
        if ( button )
        {
            button.SetTextColor( ColorManager.COLOR_DISABLED_TEXT );
        }
    }
References ColorManager::COLOR_DISABLED_TEXT, and SetFocus().
ColorHighlight() [1/2]
override void ServerBrowserTab::ColorHighlight (Widget w) inline private
Definition at line 367 of file serverbrowsertabconsole.c.
    {
        if ( !w )
        {
            return;
        }
        w.SetColor( ARGB( 255, 200, 0, 0) );
    }
References ARGB().
Referenced by OnFocus(), and OnMouseEnter().
ColorHighlight() [2/2]
override void ServerBrowserTab::ColorHighlight (Widget w) inline private
Definition at line 601 of file serverbrowsertabconsolepages.c.
    {
        if ( !w )
        {
            return;
        }
        w.SetColor( ARGB( 255, 200, 0, 0) );
    }
References ARGB().
ColorNormal() [1/2]
override void ServerBrowserTab::ColorNormal (Widget w) inline private
Definition at line 377 of file serverbrowsertabconsole.c.
    {
        if ( !w)
        {
            return
        }
        if ( (w.GetFlags() & WidgetFlags.IGNOREPOINTER) == WidgetFlags.IGNOREPOINTER )
        {
            return;
        }
        if( w.IsInherited( ButtonWidget ) )
        {
            ButtonWidget button = ButtonWidget.Cast( w );
            button.SetTextColor( ARGB( 255, 255, 255, 255 ) );
        }
        TextWidget text1    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_text" ) );
        TextWidget text2    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_text_1" ) );
        TextWidget text3    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_label" ) );
        ImageWidget image   = ImageWidget.Cast( w.FindAnyWidget( w.GetName() + "_image" ) );
        Widget option   = Widget.Cast( w.FindAnyWidget( w.GetName() + "_option_wrapper" ) );
        if( text1 )
        {
            text1.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if( text2 )
        {
            text2.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if( text3 )
        {
            text3.SetColor( ARGB( 255, 255, 255, 255 ) );
            w.SetAlpha(0);
        }
        if( image )
        {
            image.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if ( option )
        {
            option.SetColor( ARGB( 150, 255, 255, 255 ) );
        }
    }
References ARGB().
Referenced by ButtonEnable(), OnFocusLost(), and OnMouseLeave().
ColorNormal() [2/2]
override void ServerBrowserTab::ColorNormal (Widget w) inline private
Definition at line 611 of file serverbrowsertabconsolepages.c.
    {
        if ( !w )
        {
            return
        }
        if ( (w.GetFlags() & WidgetFlags.IGNOREPOINTER) == WidgetFlags.IGNOREPOINTER )
        {
            return;
        }
        if ( w.IsInherited( ButtonWidget ) )
        {
            ButtonWidget button = ButtonWidget.Cast( w );
            button.SetTextColor( ARGB( 255, 255, 255, 255 ) );
        }
        else if ( !w.IsInherited( EditBoxWidget ) )
        {
            w.SetColor( ARGB( 0, 255, 255, 255 ) );
        }
        TextWidget text1    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_text" ) );
        TextWidget text2    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_text_1" ) );
        TextWidget text3    = TextWidget.Cast(w.FindAnyWidget( w.GetName() + "_label" ) );
        ImageWidget image   = ImageWidget.Cast( w.FindAnyWidget( w.GetName() + "_image" ) );
        Widget option   = Widget.Cast( w.FindAnyWidget( w.GetName() + "_option_wrapper" ) );
        if ( text1 )
        {
            text1.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if ( text2 )
        {
            text2.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if ( text3 )
        {
            text3.SetColor( ARGB( 255, 255, 255, 255 ) );
            w.SetAlpha(0);
        }
        if ( image )
        {
            image.SetColor( ARGB( 255, 255, 255, 255 ) );
        }
        if ( option )
        {
            option.SetColor( ARGB( 150, 255, 255, 255 ) );
        }
    }
References ARGB().
Construct() [1/3]
protected override void ServerBrowserTab::Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 9 of file serverbrowsertabconsole.c.
    {
        m_Root = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/server_browser/xbox/server_browser_tab.layout", parent );
        m_ServerListScroller    = ScrollWidget.Cast( m_Root.FindAnyWidget( "server_list_scroller" ) );
        m_ServerList            = SpacerBaseWidget.Cast( m_ServerListScroller.FindAnyWidget( "server_list_content" ) );
        m_ServerListScroller.VScrollToPos01( 0 );
        m_EntryWidgets          = new map<string, ref ServerBrowserEntry>;
        m_EntriesSorted         = new map<ESortType, ref array<ref GetServersResultRow>>;
        m_EntriesSorted[ESortType.HOST] = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.POPULATION] = new array<ref GetServersResultRow>;
        m_Menu                  = menu;
        m_TabType               = type;
        m_ApplyFilter           = m_Root.FindAnyWidget( "apply_filter_button" );
        m_RefreshList           = m_Root.FindAnyWidget( "refresh_list_button" );
        m_FiltersChanged        = m_Root.FindAnyWidget( "unapplied_filters_notify" );
        m_HostSort              = m_Root.FindAnyWidget( "server_list_content_header_host" );
        m_TimeSort              = m_Root.FindAnyWidget( "server_list_content_header_time" );
        m_PopulationSort        = m_Root.FindAnyWidget( "server_list_content_header_population" );
        m_SlotsSort             = m_Root.FindAnyWidget( "server_list_content_header_slots" );
        m_PingSort              = m_Root.FindAnyWidget( "server_list_content_header_ping" );
        m_LoadingText           = TextWidget.Cast( m_Root.FindAnyWidget( "loading_servers_info" ) );
        m_WidgetNavFilters      = m_Root.FindAnyWidget( "filters_root_nav_wrapper" );
        m_WidgetNavServers      = m_Root.FindAnyWidget( "server_list_root_nav_wrapper" );
        ShowHideConsoleWidgets();
        m_Filters               = new ServerBrowserFilterContainer( m_Root.FindAnyWidget( "filters_content" ), this );
        SetSort( ESortType.HOST, ESortOrder.ASCENDING );
        SetFocusFilters();
        m_Root.SetHandler( this );
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_ApplyFilter, m_EntriesSorted, m_EntryWidgets, m_Filters, m_FiltersChanged, m_HostSort, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_TabType, m_TimeSort, SetFocusFilters(), SetSort(), and ShowHideConsoleWidgets().
Referenced by ServerBrowserTab().
Construct() [2/3]
protected override void ServerBrowserTab::Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 26 of file serverbrowsertabconsolepages.c.
    {
        m_Root = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/server_browser/xbox/server_browser_tab_console_pages.layout", parent );
        m_ServerListScroller    = ScrollWidget.Cast( m_Root.FindAnyWidget( "server_list_scroller" ) );
        m_ServerList            = SpacerBaseWidget.Cast( m_ServerListScroller.FindAnyWidget( "server_list_content" ) );
        m_ServerListScroller.VScrollToPos01( 0 );
        m_ServerListEntiers     = new array<ref ServerBrowserEntry>;
        m_EntryWidgets          = new map<string, ref ServerBrowserEntry>;
        m_EntriesSorted         = new map<ESortType, ref array<ref GetServersResultRow>>;
        m_EntriesSorted[ESortType.HOST] = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.POPULATION] = new array<ref GetServersResultRow>;
        m_Menu                  = menu;
        m_TabType               = type;
        m_ApplyFilter           = m_Root.FindAnyWidget( "apply_filter_button" );
        m_ResetFilters          = m_Root.FindAnyWidget( "reset_filter_button" );
        m_RefreshList           = m_Root.FindAnyWidget( "refresh_list_button" );
        m_FiltersChanged        = m_Root.FindAnyWidget( "unapplied_filters_notify" );
        m_HostSort              = m_Root.FindAnyWidget( "server_list_content_header_host" );
        m_TimeSort              = m_Root.FindAnyWidget( "server_list_content_header_time" );
        m_PopulationSort        = m_Root.FindAnyWidget( "server_list_content_header_population" );
        m_SlotsSort             = m_Root.FindAnyWidget( "server_list_content_header_slots" );
        m_PingSort              = m_Root.FindAnyWidget( "server_list_content_header_ping" );
        m_FilterSearchText      = m_Root.FindAnyWidget( "search_name_button" );
        m_FilterSearchTextBox   = m_Root.FindAnyWidget( "search_name_setting_option" );
        m_LoadingText           = TextWidget.Cast( m_Root.FindAnyWidget( "loading_servers_info" ) );
        m_WidgetNavFilters      = m_Root.FindAnyWidget( "filters_root_nav_wrapper" );
        m_WidgetNavServers      = m_Root.FindAnyWidget( "server_list_root_nav_wrapper" );
        m_BtnPagePrev           = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_prev" ) ) ;
        m_BtnPageNext           = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_next" ) ) ;
        #ifdef PLATFORM_PS4
            m_ButtonPageLeftImg = m_Root.FindAnyWidget( "servers_navigation_page_prev_icon_ps4" );
            m_ButtonPageRightImg = m_Root.FindAnyWidget( "servers_navigation_page_next_icon_ps4" );
            m_Root.FindAnyWidget( "servers_navigation_page_prev_icon_xbox" ).Show( false );
            m_Root.FindAnyWidget( "servers_navigation_page_next_icon_xbox" ).Show( false );
        #else
            m_ButtonPageLeftImg = m_Root.FindAnyWidget( "servers_navigation_page_prev_icon_xbox" );
            m_ButtonPageRightImg = m_Root.FindAnyWidget( "servers_navigation_page_next_icon_xbox" );
            m_Root.FindAnyWidget( "servers_navigation_page_prev_icon_ps4" ).Show( false );
            m_Root.FindAnyWidget( "servers_navigation_page_next_icon_ps4" ).Show( false );
        #endif
        ShowHideConsoleWidgets();
        m_Filters               = new ServerBrowserFilterContainer( m_Root.FindAnyWidget( "filters_content" ), this );
        m_PnlPagesPanel         = m_Root.FindAnyWidget( "servers_navigation_spacer" );
        m_PreviousPage          = 1;
        SetCurrentPage( 1 );
        m_PnlPagesPanel.Show( true );
        m_LoadingFinished       = true;
        m_Filters.OnSortChanged( m_Filters.m_SortingFilter.GetValue() );
        SetFocusFilters();
        UpdatePageButtons();
        m_Root.SetHandler( this );
        m_FilterSearchTextBox.SetHandler( this );
        GetGame().GetMission().GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
        OnInputDeviceChanged(GetGame().GetInput().GetCurrentInputDevice());
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), GetInput(), CGame::GetMission(), Mission::GetOnInputDeviceChanged(), CGame::GetWorkspace(), ScriptInvoker::Insert(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_EntriesSorted, m_EntryWidgets, m_Filters, m_FiltersChanged, m_FilterSearchText, m_FilterSearchTextBox, m_HostSort, m_LoadingFinished, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_ResetFilters, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_TabType, m_TimeSort, OnInputDeviceChanged(), SetCurrentPage(), and ServerBrowserTabConsolePages::SetFocusFilters().
Construct() [3/3]
protected override void ServerBrowserTab::Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 28 of file serverbrowsertabpc.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_Root                  = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/server_browser/xbox/server_browser_tab.layout", parent );
        #else
        #ifdef PLATFORM_WINDOWS
            m_Root                  = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/server_browser/pc/server_browser_tab_pages.layout", parent );
        #endif
        #endif
        m_ServerListScroller    = ScrollWidget.Cast( m_Root.FindAnyWidget( "server_list_scroller" ) );
        m_ServerList            = SpacerBaseWidget.Cast( m_ServerListScroller.FindAnyWidget( "server_list_content" ) );
        m_ServerListScroller.VScrollToPos01( 0 );
        m_ServerListEntries     = new array<ref ServerBrowserEntry>;
        m_EntryWidgets          = new map<string, ref ServerBrowserEntry>;
        m_SortInverted          = new map<ESortType, ESortOrder>;
        m_EntriesSorted         = new map<ESortType, ref array<ref GetServersResultRow>>;
        m_EntryMods             = new map<string, ref array<string>>;
        m_EntriesSorted[ESortType.HOST]         = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.TIME]         = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.POPULATION]   = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.SLOTS]        = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.PING]         = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.FAVORITE]     = new array<ref GetServersResultRow>;
        m_EntriesSorted[ESortType.PASSWORDED]   = new array<ref GetServersResultRow>;
        m_Menu                  = menu;
        m_TabType               = type;
        m_ApplyFilter           = m_Root.FindAnyWidget( "apply_filter_button" );
        m_RefreshList           = m_Root.FindAnyWidget( "refresh_list_button" );
        m_FiltersChanged        = m_Root.FindAnyWidget( "unapplied_filters_notify" );
        m_HostSort              = m_Root.FindAnyWidget( "server_list_content_header_host" );
        m_TimeSort              = m_Root.FindAnyWidget( "server_list_content_header_time" );
        m_PopulationSort        = m_Root.FindAnyWidget( "server_list_content_header_population" );
        m_SlotsSort             = m_Root.FindAnyWidget( "server_list_content_header_slots" );
        m_PingSort              = m_Root.FindAnyWidget( "server_list_content_header_ping" );
        m_FilterSearchText      = m_Root.FindAnyWidget( "search_name_setting" );
        m_FilterSearchTextBox   = m_Root.FindAnyWidget( "search_name_setting_option" );
        m_FilterSearchIP        = m_Root.FindAnyWidget( "search_ip_setting" );
        m_FilterSearchIPBox     = m_Root.FindAnyWidget( "search_ip_setting_option" );
        m_FilterPanelAccTime    = m_Root.FindAnyWidget( "accelerated_time_setting" );
        m_FilterPanelPing       = m_Root.FindAnyWidget( "ping_setting" );
        //m_FilterPanelPing.SetHandler( this );
        m_LoadingText           = TextWidget.Cast( m_Root.FindAnyWidget( "loading_servers_info" ) );
        ButtonDisable( m_ApplyFilter );
        if ( type == TabType.LAN)
        {
            DisableFilters();
        }
        m_Filters = new ServerBrowserFilterContainer( m_Root.FindAnyWidget( "filters_content" ), this );
        m_Root.SetHandler( this );
        SetSort(ESortType.HOST, ESortOrder.ASCENDING);
        m_BtnPages = new array<ButtonWidget>();
        int page_button_num = 1;
        ButtonWidget page_button = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_page"+ page_button_num ) );
        if ( PAGES_BUTTONS_COUNT < 3 || PAGES_BUTTONS_COUNT > 10 )
        {
            Error("ServerBrowserTabPage->PAGES_BUTTONS_COUNT must be in range 3 - 10!");
            return;
        }
        while ( page_button )
        {
            page_button.Show(false);
            if ( page_button_num <= PAGES_BUTTONS_COUNT )
            {
                m_BtnPages.Insert( page_button );
            }
            page_button_num++;
            page_button = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_page"+ page_button_num ) );
        }
        m_ResetFilters          = ButtonWidget.Cast( m_Root.FindAnyWidget( "reset_filter_button" ) ) ;
        m_PnlPagesPanel         = m_Root.FindAnyWidget( "servers_navigation_spacer" );
        m_BtnPagePrev           = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_prev" ) ) ;
        m_BtnPageNext           = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_next" ) ) ;
        m_BtnPagesFirst         = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_page_first" ) ) ;
        m_BtnPagesLast          = ButtonWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_page_last" ) ) ;
        m_PageIndex             = 0;
        m_PnlPagesPanel.Show( true );
        UpdatePageButtons();
    }
References ButtonDisable(), WorkspaceWidget::CreateWidgets(), Error(), GetGame(), CGame::GetWorkspace(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_EntriesSorted, m_EntryMods, m_EntryWidgets, m_Filters, m_FiltersChanged, m_FilterSearchText, m_FilterSearchTextBox, m_HostSort, m_LoadingText, m_Menu, m_PingSort, m_PopulationSort, m_RefreshList, m_ResetFilters, m_Root, m_ServerList, m_ServerListScroller, m_SlotsSort, m_SortInverted, m_TabType, m_TimeSort, and SetSort().
DisableFilters()
void ServerBrowserTab::DisableFilters () inline private
Definition at line 134 of file serverbrowsertabpc.c.
    {
        m_Root.FindAnyWidget( "filters_content" ).Show( false );
        m_Root.FindAnyWidget( "spacer" ).Show( false );
        m_Root.FindAnyWidget( "spacer2" ).Show( false );
        m_Root.FindAnyWidget( "reset_filter_button" ).Show( false );
        m_ApplyFilter.Show( false );
        m_FiltersChanged.Show( false );
    }
References m_ApplyFilter, m_FiltersChanged, and m_Root.
Focus() [1/2]
override void ServerBrowserTab::Focus () inline private
Definition at line 320 of file serverbrowsertabconsole.c.
    {
        if( m_EntryWidgets.Contains( m_CurrentSelectedServer ) )
        {
            m_EntryWidgets.Get( m_CurrentSelectedServer ).Focus();
            ScrollToEntry( m_EntryWidgets.Get( m_CurrentSelectedServer ) );
        }
        SetFocusServers();
    }
References m_CurrentSelectedServer, m_EntryWidgets, ScrollToEntry(), and SetFocusServers().
Referenced by UIScriptedMenu::OnTabSwitch().
Focus() [2/2]
override void ServerBrowserTab::Focus () inline private
Definition at line 452 of file serverbrowsertabconsolepages.c.
    {
        if ( m_EntryWidgets.Contains( m_CurrentSelectedServer ) )
        {
            m_EntryWidgets.Get( m_CurrentSelectedServer ).Focus();
            ScrollToEntry( m_EntryWidgets.Get( m_CurrentSelectedServer ) );
        }
        array<ref GetServersResultRow> entries = m_EntriesSorted[m_SortType];
        if ( entries && entries.Count() > 0 )
            SetFocusServers();
        else
            SetFocusFilters();
    }
References m_CurrentSelectedServer, m_EntriesSorted, m_EntryWidgets, m_SortType, ScrollToEntry(), and ServerBrowserTabConsolePages::SetFocusFilters().
GetServerEntryByIndex() [1/2]
protected ServerBrowserEntry ServerBrowserTab::GetServerEntryByIndex (int index) inline private
Definition at line 235 of file serverbrowsertabconsolepages.c.
    {
        ServerBrowserEntry entry;
        if ( index >= 0 )
        {
            if ( index < m_ServerListEntiers.Count() )
            {
                entry = m_ServerListEntiers[index];
            }
            else
            {
                entry = new ServerBrowserEntry( m_ServerList, index, this );
                m_ServerListEntiers.Insert(entry);
            }
        }
        else
        {
            return null;
        }
        entry.Show( true );
        return entry;
    }
References m_ServerList.
GetServerEntryByIndex() [2/2]
protected ServerBrowserEntry ServerBrowserTab::GetServerEntryByIndex (int index, string server_id) inline private
Definition at line 1051 of file serverbrowsertabpc.c.
    {
        ref ServerBrowserEntry entry;
        if ( index >= 0 )
        {
            if ( index < m_ServerListEntries.Count() )
            {
                entry = m_ServerListEntries[index];
            }
            else
            {
                entry = new ServerBrowserEntry( null, index, this );
                m_ServerList.AddChild( entry.GetRoot(), false );
                m_ServerListEntries.Insert(entry);
            }
        }
        else
        {
            return null;
        }
        // Refresh list
        m_EntryWidgets.Insert( server_id, entry );
        return entry;
    }
References m_EntryWidgets, and m_ServerList.
GetTimeOfDayEnum()
int ServerBrowserTab::GetTimeOfDayEnum (string time_of_day) inline private
Definition at line 573 of file serverbrowsertabpc.c.
    {
        m_TempTime.Clear();
        time_of_day.Split( ":", m_TempTime );
        int minutes = 0;
        if ( m_TempTime.Count() > 0 )
        {
            int h = m_TempTime[0].ToInt();
            if ( h >= 5 )
            {
                h -= 5;
            }
            else
            {
                h += 24;
            }
            minutes = h * 60;
        }
        if ( m_TempTime.Count() > 1 )
        {
            int m = m_TempTime[0].ToInt();
            minutes += m;
        }
        return minutes;
    }
References string::Split().
IsFocusable()
override bool ServerBrowserTab::IsFocusable (Widget w) inline private
Definition at line 1080 of file serverbrowsertabpc.c.
    {
        if ( w )
        {
            if ( super.IsFocusable( w ) )
            {
                return true;
            }
            if ( w == m_ServerListScroller )
            {
                return false;
            }
            if ( w == m_HostSort || w == m_TimeSort || w == m_PopulationSort || w == m_SlotsSort || w == m_PingSort || w == m_FilterSearchIP )
            {
                return true;
            }
            if ( w == m_FilterPanelAccTime || m_FilterPanelPing )
            {
                return true;
            }
            return false;
        }
        return false;
    }
References m_HostSort, m_PingSort, m_PopulationSort, m_ServerListScroller, m_SlotsSort, and m_TimeSort.
Referenced by OnFocus(), OnFocusLost(), OnMouseEnter(), and OnMouseLeave().
Left()
override void ServerBrowserTab::Left () inline private
Definition at line 361 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused )
        {
            int curr_page = GetCurrentPage();
            m_PreviousPage = curr_page;
            if ( curr_page > 1 )
            {
                SetCurrentPage( curr_page - 1 );
                UpdatePageButtons();
            }
        }
    }
References GetCurrentPage(), and SetCurrentPage().
Referenced by UIScriptedMenu::Update().
LeftHold()
override void ServerBrowserTab::LeftHold () inline private
Definition at line 375 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused )
        {
            if ( (GetGame().GetTime() - m_TimeLastServerRefreshHoldButton) > 100 )
            {
                m_TimeLastServerRefreshHoldButton = GetGame().GetTime();
                Left();
            }
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), and Left().
Referenced by UIScriptedMenu::Update().
LeftRelease()
override void ServerBrowserTab::LeftRelease () inline private
Definition at line 387 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused && GetCurrentPage() != m_PreviousPage )
        {
            RefreshList();
        }
    }
References GetCurrentPage(), and ServerBrowserTabConsolePages::RefreshList().
Referenced by UIScriptedMenu::Update().
LoadEntries() [1/2]
void ServerBrowserTab::LoadEntries (int cur_page_index, GetServersResultRowArray page) inline private
Definition at line 122 of file serverbrowsertabconsole.c.
    {
        if( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
        {
            return;
        }
        int index = cur_page_index * SERVER_BROWSER_PAGE_SIZE;
        ref GetServersResultRowArray page_entries = page;
        if( page_entries )
        {
            foreach( GetServersResultRow result : page_entries )
            {
                m_TotalLoadedServers++;
                if( PassFilter( result ) )
                {
                    ref ServerBrowserEntry entry = new ServerBrowserEntry( m_ServerList, index, this );
                    string ipPort = result.GetIpPort();
                    entry.FillInfo( result );
                    entry.SetFavorite( m_Menu.IsFavorited(ipPort));
                    entry.UpdateEntry();
                    m_EntryWidgets.Insert(ipPort, entry);
                    index++;
                    m_EntriesSorted[m_SortType].Insert( result );
                    if ( m_EntryWidgets.Count() > 0 )
                    {
                        SetFocusServers();
                    }
                }
                if( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
                    return;
            }
            m_ServerList.Update();
        }
        /*
        if ( cur_page_index == 1 && m_EntryWidgets.Count() > 0 )
        {
            SetFocusServers();
        }
        else
        {
            m_LoadingText.SetText( "#server_browser_unable_with_filter" );
            SetFocusFilters();
        }
        */
        if( m_EntriesSorted[m_SortType].Count() > 0 )
        {
            /*
            */
        }
        else
        {
            //m_LoadingText.SetText( "#server_browser_unable_with_filter" );
        }
        if ( !m_Menu )
            return;
        if( m_LastLoadedPage == m_TotalPages )
        {
            //m_LoadingText.SetText( "#server_browser_tab_loaded" + " " + m_EntryWidgets.Count() + "/" + m_EntryWidgets.Count() + " " + "#server_browser_servers_desc" );
            m_Menu.SetServersLoadingTab( TabType.NONE );
        }
    }
References Count, m_EntriesSorted, m_EntryWidgets, m_LastLoadedPage, m_Menu, m_ServerList, m_SortType, m_TabType, m_TotalLoadedServers, m_TotalPages, PassFilter(), SERVER_BROWSER_PAGE_SIZE, and SetFocusServers().
Referenced by OnLoadServersAsyncConsole().
LoadEntries() [2/2]
protected void ServerBrowserTab::LoadEntries (int cur_page_index, GetServersResultRowArray page_entries) inline private
Definition at line 180 of file serverbrowsertabconsolepages.c.
    {
        int index = 0;
        ServerBrowserEntry entry;
        m_TotalLoadedServers = m_TotalServersCount;
        if ( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
        {
            return;
        }
        // only load servers if they correspond to current page
        if (cur_page_index != m_CurrentPageNum)
        {
            return;
        }
        if ( m_PagesCount && page_entries )
        {
            foreach ( GetServersResultRow result : page_entries )
            {
                if ( PassFilter( result ) )
                {
                    string ipPort = result.GetIpPort();
                    bool isFavorited = m_Menu.IsFavorited(ipPort);
                    entry = GetServerEntryByIndex( index );
                    entry.FillInfo( result );
                    entry.SetFavorite(isFavorited);
                    entry.SetIsOnline(true);
                    entry.UpdateEntry();
                    if (isFavorited && m_OnlineFavServers.Find(ipPort) == -1)
                    {
                        m_OnlineFavServers.Insert(ipPort);
                    }
                    m_EntryWidgets.Insert(ipPort, entry);
                    m_EntriesSorted[m_SortType].Insert( result );
                    index++;
                }
                if ( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
                {
                    return;
                }
            }
        }
        LoadExtraEntries(index);
        m_ServerList.Update();
        SetFocusServers();
    }
References ServerBrowserTabConsolePages::LoadExtraEntries(), m_CurrentPageNum, m_EntriesSorted, m_EntryWidgets, m_Menu, m_OnlineFavServers, m_ServerList, m_SortType, m_TabType, m_TotalLoadedServers, and ServerBrowserTabConsolePages::PassFilter().
LoadingServersStop()
void ServerBrowserTab::LoadingServersStop () inline private
Definition at line 190 of file serverbrowsertabpc.c.
    {
        OnlineServices.m_ServersAsyncInvoker.Remove( m_Menu.OnLoadServersAsync );
        m_LoadingFinished = true;
        m_Loading = false;
        ButtonCancelToRefresh();
        UpdateServerList();
        UpdateStatusBar();
    }
References m_Loading, m_LoadingFinished, m_Menu, OnlineServices::m_ServersAsyncInvoker, and ScriptInvoker::Remove().
OnClick() [1/2]
override bool ServerBrowserTab::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 558 of file serverbrowsertabconsolepages.c.
    {
        super.OnClick( w, x, y, button );
        if ( button == MouseState.LEFT )
        {
            if ( w == m_ResetFilters )
            {
                ResetFilters();
            }
            else if ( w == m_ApplyFilter )
            {
                ApplyFilters();
                return true;
            }
            else if ( w == m_RefreshList )
            {
                if ( m_Loading && !m_LoadingFinished )
                {
                    PressX();
                }
                else
                {
                    RefreshList();
                }
                return true;
            }
            else if ( w == m_BtnPagePrev )
            {
                Left();
                return true;
            }
            else if ( w == m_BtnPageNext )
            {
                Right();
                return true;
            }
        }
        return false;
    }
References ApplyFilters(), Left(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_Loading, m_LoadingFinished, m_RefreshList, m_ResetFilters, ServerBrowserTabConsolePages::PressX(), ServerBrowserTabConsolePages::RefreshList(), ResetFilters(), Right(), x, and y.
OnClick() [2/2]
override bool ServerBrowserTab::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 263 of file serverbrowsertabpc.c.
    {
        super.OnClick( w, x, y, button );
        if ( button == MouseState.LEFT )
        {
            if ( w == m_ResetFilters )
            {
                ResetFilters();
            }
            else if ( w == m_ApplyFilter )
            {
                ApplyFilters();
                return true;
            }
            else if ( w == m_RefreshList )
            {
                if ( m_Loading && !m_LoadingFinished )
                {
                    LoadingServersStop();
                }
                else
                {
                    RefreshList();
                }
                return true;
            }
            else if ( w == m_BtnPagePrev )
            {
                OnClickPagePrev();
                return true;
            }
            else if ( w == m_BtnPageNext )
            {
                OnClickPageNext();
                return true;
            }
            else if ( w == m_BtnPagesLast )
            {
                OnClickPageEnd();
                return true;
            }
            else if ( w == m_BtnPagesFirst )
            {
                OnClickPageFirst();
                return true;
            }
            else
            {
                bool click = OnClickPage( w );
                if ( click )
                {
                    return true;
                }
                return false;
            }
        }
        return false;
    }
References ApplyFilters(), m_ApplyFilter, m_BtnPageNext, m_BtnPagePrev, m_Loading, m_LoadingFinished, m_RefreshList, m_ResetFilters, ServerBrowserTabPc::RefreshList(), ResetFilters(), x, and y.
OnClickPage()
bool ServerBrowserTab::OnClickPage (Widget w) inline private
Definition at line 450 of file serverbrowsertabpc.c.
    {
        for ( int i = 0; i < m_BtnPages.Count(); ++i )
        {
            if ( m_BtnPages[i] == w )
            {
                SetPageIndex( m_PageStartNum + i - 1 );
                return true;
            }
        }
        return false;
    }
OnClickPageEnd()
void ServerBrowserTab::OnClickPageEnd () inline private
Definition at line 440 of file serverbrowsertabpc.c.
    {
        SetPageIndex( m_PagesCount - 1 );
    }
OnClickPageFirst()
void ServerBrowserTab::OnClickPageFirst () inline private
Definition at line 445 of file serverbrowsertabpc.c.
    {
        SetPageIndex( 0 );
    }
OnClickPageNext()
void ServerBrowserTab::OnClickPageNext () inline private
Definition at line 428 of file serverbrowsertabpc.c.
    {
        if ( m_PageIndex < (m_PagesCount - 1) )
        {
            SetPageIndex( m_PageIndex + 1 );
        }
        else
        {
            SetPageIndex( 0 );
        }
    }
OnClickPagePrev()
void ServerBrowserTab::OnClickPagePrev () inline private
Definition at line 416 of file serverbrowsertabpc.c.
    {
        if ( m_PageIndex > 0 )
        {
            SetPageIndex( m_PageIndex - 1);
        }
        else
        {
            SetPageIndex( m_PagesCount - 1 );
        }
    }
OnFilterChanged() [1/3]
override void ServerBrowserTab::OnFilterChanged () inline private
Definition at line 202 of file serverbrowsertabconsole.c.
    {
        m_IsFilterChanged = true;
    }
Referenced by ScriptedWidgetEventHandler::OnFilterChanged().
OnFilterChanged() [2/3]
override void ServerBrowserTab::OnFilterChanged () inline private
Definition at line 261 of file serverbrowsertabconsolepages.c.
    {
        m_IsFilterChanged = true;
    }
OnFilterChanged() [3/3]
override void ServerBrowserTab::OnFilterChanged () inline private
Definition at line 404 of file serverbrowsertabpc.c.
    {
        //m_FiltersChanged.Show( true );
        ButtonEnable( m_ApplyFilter );
        if ( !m_Loading )
        {
            ButtonDisable( m_RefreshList );
        }
    }
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Loading, and m_RefreshList.
OnFilterFocus()
override void ServerBrowserTab::OnFilterFocus (Widget w) inline private
Definition at line 195 of file serverbrowsertabconsole.c.
    {
        super.OnFilterFocus( w );
        //ColorHighlight( w );
    }
Referenced by ScriptedWidgetEventHandler::OnFocus().
OnFilterFocusLost()
override void ServerBrowserTab::OnFilterFocusLost (Widget w) inline private
Definition at line 240 of file serverbrowsertabconsole.c.
    {
        super.OnFilterFocusLost( w );
    }
OnInputDeviceChanged()
protected void ServerBrowserTab::OnInputDeviceChanged (EInputDeviceType pInputDeviceType) inline private
Definition at line 117 of file serverbrowsertabconsolepages.c.
    {
        switch (pInputDeviceType)
        {
        case EInputDeviceType.CONTROLLER:
            ShowHideConsoleWidgets();
            UpdatePageButtons();
            m_WidgetNavFilters.Show(m_IsFilterFocused);
            m_WidgetNavServers.Show(!m_IsFilterFocused);
            m_MouseKeyboardControlled = false;
        break;
        default:
            if (GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer())
            {
                m_WidgetNavFilters.Show(false);
                m_WidgetNavServers.Show(false);
                m_ButtonPageLeftImg.Show(false);
                m_ButtonPageRightImg.Show(false);
                m_MouseKeyboardControlled = true;
            }
        break;
        }
    }
References GetGame(), and GetInput().
OnLoadServerModsAsync()
override void ServerBrowserTab::OnLoadServerModsAsync (string server_id, array< string > mods) inline private
Definition at line 1041 of file serverbrowsertabpc.c.
    {
        super.OnLoadServerModsAsync( server_id, mods );
        if ( m_EntryWidgets.Contains( server_id ) )
        {
            m_EntryWidgets.Get( server_id ).SetMods( mods );
        }
    }
References m_EntryWidgets.
Referenced by UIScriptedMenu::OnLoadServerModsAsync().
OnLoadServersAsyncConsole() [1/2]
override void ServerBrowserTab::OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 67 of file serverbrowsertabconsole.c.
    {
        //Print("m_NumServers: "+ result_list.m_NumServers +" m_Pages: "+ result_list.m_Pages + " m_Page: "+ result_list.m_Page);
        //string smg = "m_NumServers: "+ result_list.m_NumServers +" m_Pages: "+ result_list.m_Pages + " m_Page: "+ result_list.m_Page +" response: "+ response +" error: "+ error;
        //m_LoadingText.SetText( smg );
        if ( error != EBiosError.OK || !result_list )
        {
            m_LoadingText.SetText( string.Format("Error: %1", ErrorModuleHandler.GetClientMessage(ErrorCategory.BIOSError, error)) );
            return;
        }
        if ( result_list.m_Page == 1 )
        {
            m_TotalPages = result_list.m_Pages;
            m_TotalServers = result_list.m_NumServers;
            if ( m_Menu.GetServersLoadingTab() != m_TabType || !result_list || ( !result_list.m_Results || result_list.m_Results.Count() == 0 ) )
            {
                m_Menu.SetServersLoadingTab( TabType.NONE );
                m_LoadingText.SetText("#server_browser_tab_unable_to_get_server #server_browser_tab_no_servers_with_filter");
                return;
            }
        }
        m_LastLoadedPage = result_list.m_Page;
        if ( m_TotalPages > 0 )
        {
            LoadEntries( result_list.m_Page, result_list.m_Results );
        }
        if ( m_TotalPages > m_LastLoadedPage )
        {
            GetNextPage();
            return;
        }
        if ( result_list.m_Page == result_list.m_Pages )
        {
            OnLoadServersAsyncFinished();
        }
    }
References ErrorModuleHandler::GetClientMessage(), GetNextPage(), LoadEntries(), m_LastLoadedPage, m_LoadingText, m_Menu, GetServersResult::m_NumServers, GetServersResult::m_Page, GetServersResult::m_Pages, GetServersResult::m_Results, m_TabType, m_TotalPages, m_TotalServers, and OnLoadServersAsyncFinished().
Referenced by UIScriptedMenu::OnLoadServersAsync().
OnLoadServersAsyncConsole() [2/2]
override void ServerBrowserTab::OnLoadServersAsyncConsole (GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 142 of file serverbrowsertabconsolepages.c.
    {
        if ( error != EBiosError.OK )
        {
            m_LoadingText.SetText( string.Format("Error: %1", ErrorModuleHandler.GetClientMessage(ErrorCategory.BIOSError, error)) );
            m_Menu.SetServersLoadingTab( TabType.NONE );
            m_LoadingFinished = true;
            SetFocusFilters();
            return;
        }
        m_PagesCount = result_list.m_Pages;
        m_TotalServersCount = result_list.m_NumServers;
        LoadEntries( result_list.m_Page, result_list.m_Results );
        if (m_TotalLoadedServers == 0)
        {
            SetFocusFilters();
        }
        OnLoadServersAsyncFinished();
        UpdatePageButtons();
    }
References ErrorModuleHandler::GetClientMessage(), ServerBrowserTabConsolePages::LoadEntries(), m_LoadingFinished, m_LoadingText, m_Menu, GetServersResult::m_NumServers, GetServersResult::m_Page, GetServersResult::m_Pages, GetServersResult::m_Results, m_TotalLoadedServers, ServerBrowserTabConsolePages::OnLoadServersAsyncFinished(), and ServerBrowserTabConsolePages::SetFocusFilters().
OnLoadServersAsyncFinished() [1/2]
void ServerBrowserTab::OnLoadServersAsyncFinished () inline private
Definition at line 111 of file serverbrowsertabconsole.c.
    {
        string msg = "#servers_found: "+ m_TotalLoadedServers;
        if ( m_TotalLoadedServers == 0 )
        {
            msg = "#server_browser_tab_unable_to_get_server";
        }
        m_LoadingText.SetText( msg );
        m_LoadingFinished = true;
    }
References m_LoadingFinished, m_LoadingText, and m_TotalLoadedServers.
Referenced by OnLoadServersAsyncConsole().
OnLoadServersAsyncFinished() [2/2]
void ServerBrowserTab::OnLoadServersAsyncFinished () inline private
Definition at line 167 of file serverbrowsertabconsolepages.c.
    {
        string msg = "#servers_found: " + m_TotalLoadedServers;
        if ( m_TotalLoadedServers == 0 )
        {
            msg = "#server_browser_tab_unable_to_get_server";
        }
        m_LoadingText.SetText( msg );
        m_LoadingFinished = true;
        m_Menu.SetServersLoadingTab( TabType.NONE );
    }
References m_LoadingFinished, m_LoadingText, m_Menu, and m_TotalLoadedServers.
OnLoadServersAsyncPC()
override void ServerBrowserTab::OnLoadServersAsyncPC (ref GetServersResult result_list, EBiosError error, string response) inline private
Definition at line 203 of file serverbrowsertabpc.c.
    {
        if ( result_list )
        {
            int count = result_list.m_Results.Count();
            if ( count > 0 )
            {
                for ( int i = 0; i < count; i++ )
                {
                    GetServersResultRow result = result_list.m_Results[i];
                    m_TotalServersCount++;
                    result.m_SortName = result.m_Name.ToInt();
                    result.m_SortTime = GetTimeOfDayEnum( result.m_TimeOfDay );
                    if ( PassFilter( result ) )
                    {
                        int sorted_index = AddSorted( result );
                        if ( sorted_index < (m_PageIndex * SERVERS_VISIBLE_COUNT + SERVERS_VISIBLE_COUNT) )
{
                            UpdateServerList();
                            UpdatePageButtons();
                        }
                    }
                    if ( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
                    {
                        return;
                    }
                }
            }
            else
            {
                m_Menu.SetServersLoadingTab( TabType.NONE );
            }
        }
        else
        {
            m_Menu.SetServersLoadingTab( TabType.NONE );
        }
        if ( response == "thelastone" )
        {
            OnLoadServersAsyncPCFinished();
        }
        else
        {
            m_ServersEstimateCount = result_list.m_NumServers;
        }
        UpdateServerList();
        UpdateStatusBar();
    }
References AddSorted(), m_Menu, m_TabType, and PassFilter().
Referenced by UIScriptedMenu::OnLoadServersAsync().
OnLoadServersAsyncPCFinished()
void ServerBrowserTab::OnLoadServersAsyncPCFinished () inline private
Definition at line 258 of file serverbrowsertabpc.c.
    {
        LoadingServersStop();
    }
OnMouseButtonUp()
override bool ServerBrowserTab::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 364 of file serverbrowsertabpc.c.
    {
        //Print("SG OnMouseButtonUp: "+ w.GetName());
        if ( button == MouseState.LEFT )
        {
            if ( w == m_HostSort )
            {
                ToggleSort( ESortType.HOST );
                UpdateServerList();
                return true;
            }
            else if ( w == m_TimeSort )
            {
                ToggleSort( ESortType.TIME );
                UpdateServerList();
                return true;
            }
            else if ( w == m_PopulationSort )
            {
                ToggleSort( ESortType.POPULATION );
                UpdateServerList();
                return true;
            }
            else if ( w == m_SlotsSort )
            {
                ToggleSort( ESortType.SLOTS );
                UpdateServerList();
                return true;
            }
            else if ( w == m_PingSort )
            {
                ToggleSort( ESortType.PING );
                UpdateServerList();
                return true;
            }
        }
        return false;
    }
References m_HostSort, m_PingSort, m_PopulationSort, m_SlotsSort, and m_TimeSort.
OnMouseEnter()
override bool ServerBrowserTab::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 326 of file serverbrowsertabpc.c.
    {
        if ( IsFocusable( w ) )
        {
            ColorHighlight( w );
            if ( w == m_FilterSearchText )
            {
                SetFocus( m_FilterSearchTextBox );
                return true;
            }
            else if ( w == m_FilterSearchIP )
            {
                SetFocus( m_FilterSearchIPBox );
                return true;
            }
            return true;
        }
        return false;
    }
References ColorHighlight(), IsFocusable(), m_FilterSearchText, m_FilterSearchTextBox, and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnMouseLeave()
override bool ServerBrowserTab::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 348 of file serverbrowsertabpc.c.
    {
        if ( IsFocusable( w ) )
        {
            ColorNormal( w );
            if ( w == m_FilterSearchText || w == m_FilterSearchIP )
            {
                SetFocus( null );
            }
            return true;
        }
        return false;
    }
References ColorNormal(), IsFocusable(), m_FilterSearchText, and SetFocus().
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
PressA() [1/2]
override void ServerBrowserTab::PressA () inline private
Definition at line 245 of file serverbrowsertabconsole.c.
    {
    }
Referenced by UIScriptedMenu::Update().
PressA() [2/2]
override void ServerBrowserTab::PressA () inline private
Definition at line 317 of file serverbrowsertabconsolepages.c.
    {
    }
PressSholderLeft() [1/2]
override void ServerBrowserTab::PressSholderLeft () inline private
Definition at line 283 of file serverbrowsertabconsole.c.
    {
        if ( m_IsFilterFocused )
        {
            SetFocusServers();
        }
        else
        {
            SetFocusFilters();
        }
    }
References SetFocusFilters(), and SetFocusServers().
Referenced by UIScriptedMenu::Update().
PressSholderLeft() [2/2]
override void ServerBrowserTab::PressSholderLeft () inline private
Definition at line 429 of file serverbrowsertabconsolepages.c.
    {
        if ( m_IsFilterFocused )
        {
            SetFocusServers();
        }
        else
        {
            SetFocusFilters();
        }
    }
References ServerBrowserTabConsolePages::SetFocusFilters().
PressSholderRight() [1/2]
override void ServerBrowserTab::PressSholderRight () inline private
Definition at line 295 of file serverbrowsertabconsole.c.
    {
        if ( m_IsFilterFocused )
        {
            SetFocusServers();
        }
        else
        {
            SetFocusFilters();
        }
    }
References SetFocusFilters(), and SetFocusServers().
Referenced by UIScriptedMenu::Update().
PressSholderRight() [2/2]
override void ServerBrowserTab::PressSholderRight () inline private
Definition at line 441 of file serverbrowsertabconsolepages.c.
    {
        if ( m_IsFilterFocused )
        {
            SetFocusServers();
        }
        else
        {
            SetFocusFilters();
        }
    }
References ServerBrowserTabConsolePages::SetFocusFilters().
PressX() [1/2]
override void ServerBrowserTab::PressX () inline private
Definition at line 250 of file serverbrowsertabconsole.c.
    {
        RefreshList();
    }
References RefreshList().
Referenced by UIScriptedMenu::Update().
PressX() [2/2]
override void ServerBrowserTab::PressX () inline private
Definition at line 322 of file serverbrowsertabconsolepages.c.
    {
        if ( (GetGame().GetTime() - m_TimeLastServerRefresh) > 1000 )
        {
            m_TimeLastServerRefresh = GetGame().GetTime();
            if ( m_IsFilterChanged)
            {
                SetCurrentPage(1);
            }
            m_OnlineFavServers.Clear();
            RefreshList();
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), m_OnlineFavServers, ServerBrowserTabConsolePages::RefreshList(), and SetCurrentPage().
PressY() [1/2]
override void ServerBrowserTab::PressY () inline private
Definition at line 255 of file serverbrowsertabconsole.c.
    {
        /*
        if( m_Menu.GetServersLoadingTab() != TabType.NONE )
        {
            return;
        }
        */
        switch( m_SelectedPanel )
        {
            case SelectedPanel.BROWSER:
            {
                if( m_SelectedServer )
                {
                    m_Menu.ServerListFocus( true, m_SelectedServer.ToggleFavorite() );
                }
                break;
            }
            case SelectedPanel.FILTERS:
            {
                if( m_Filters )
                    m_Filters.ResetFilters();
                break;
            }
        }
    }
References m_Filters, m_Menu, m_SelectedPanel, and m_SelectedServer.
Referenced by UIScriptedMenu::Update().
PressY() [2/2]
override void ServerBrowserTab::PressY () inline private
Definition at line 338 of file serverbrowsertabconsolepages.c.
    {
        switch ( m_SelectedPanel )
        {
            case SelectedPanel.BROWSER:
            {
                if ( m_SelectedServer )
                {
                    m_Menu.ServerListFocus( true, m_SelectedServer.ToggleFavorite() );
                }
                break;
            }
            case SelectedPanel.FILTERS:
            {
                if ( m_Filters )
                {
                    m_Filters.ResetFilters();
                }
                break;
            }
        }
    }
References m_Filters, m_Menu, m_SelectedPanel, and m_SelectedServer.
RefreshList() [1/3]
override void ServerBrowserTab::RefreshList () inline private
Definition at line 207 of file serverbrowsertabconsole.c.
    {
        for ( int i = 0; i < m_EntriesSorted.Count(); i++ )
        {
            m_EntriesSorted.GetElement(i).Clear();
        }
        m_Filters.SaveFilters();
        super.RefreshList();
        m_ServerListScroller.VScrollToPos01( 0 );
        m_LoadingText.SetText( "#dayz_game_loading" );
        SetFocusFilters();
        //UpdateStatusBar();
    }
References m_EntriesSorted, m_Filters, m_LoadingText, m_ServerListScroller, and SetFocusFilters().
Referenced by ApplyFilters(), UIScriptedMenu::OnTabSwitch(), PressX(), and PressX().
RefreshList() [2/3]
override void ServerBrowserTab::RefreshList () inline private
Definition at line 271 of file serverbrowsertabconsolepages.c.
    {
        for ( int i = 0; i < m_ServerListEntiers.Count(); i++ )
        {
            m_ServerListEntiers[i].Show(false);
        }
        for ( int j = 0; j < m_EntriesSorted.Count(); j++ )
        {
            array<ref GetServersResultRow> result_rows = m_EntriesSorted.GetElement(j);
            if ( result_rows )
            {
                result_rows.Clear();
            }
        }
        m_IsFilterChanged = false;
        m_Filters.SaveFilters();
        super.RefreshList();
        m_ServerListScroller.VScrollToPos01( 0 );
        m_LoadingText.SetText( "#dayz_game_loading" );
    }
References m_EntriesSorted, m_Filters, m_LoadingText, and m_ServerListScroller.
RefreshList() [3/3]
override void ServerBrowserTab::RefreshList () inline private
Definition at line 144 of file serverbrowsertabpc.c.
    {
        for ( int i = 0; i < m_EntriesSorted.Count(); i++ )
        {
            m_EntriesSorted.GetElement(i).Clear();
        }
        OnlineServices.m_ServersAsyncInvoker.Insert( m_Menu.OnLoadServersAsync );
        m_LoadingFinished = false;
        m_Loading = true;
        m_TotalServersCount = 0;
        m_TotalLoadedServers = 0;
        m_ServersEstimateCount = 0;
        m_PageIndex = 0;
        super.RefreshList();
        m_ServerListScroller.VScrollToPos01( 0 );
        ButtonRefreshToCancel();
        UpdateServerList();
        UpdatePageButtons();
        UpdateStatusBar();
    }
References ScriptInvoker::Insert(), m_EntriesSorted, m_Loading, m_LoadingFinished, m_Menu, m_ServerListScroller, OnlineServices::m_ServersAsyncInvoker, and m_TotalLoadedServers.
ResetFilters() [1/3]
override void ServerBrowserTab::ResetFilters () inline private
Definition at line 226 of file serverbrowsertabconsole.c.
    {
        super.ResetFilters();
        m_IsFilterChanged = false;
    }
ResetFilters() [2/3]
override void ServerBrowserTab::ResetFilters () inline private
Definition at line 298 of file serverbrowsertabconsolepages.c.
    {
        super.ResetFilters();
        m_IsFilterChanged = false;
    }
ResetFilters() [3/3]
override void ServerBrowserTab::ResetFilters () inline private
Definition at line 169 of file serverbrowsertabpc.c.
    {
        m_Filters.ResetFilters();
        ButtonEnable( m_ApplyFilter );
        if ( !m_Loading )
        {
            ButtonDisable( m_RefreshList );
        }
    }
References ButtonDisable(), ButtonEnable(), m_ApplyFilter, m_Filters, m_Loading, and m_RefreshList.
Right()
override void ServerBrowserTab::Right () inline private
Definition at line 395 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused )
        {
            int curr_page = GetCurrentPage();
            m_PreviousPage = curr_page;
            if ( curr_page < m_PagesCount )
            {
                SetCurrentPage( curr_page + 1 );
                UpdatePageButtons();
            }
        }
    }
References GetCurrentPage(), and SetCurrentPage().
Referenced by UIScriptedMenu::Update().
RightHold()
override void ServerBrowserTab::RightHold () inline private
Definition at line 409 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused )
        {
            if ( (GetGame().GetTime() - m_TimeLastServerRefreshHoldButton) > 100 )
            {
                m_TimeLastServerRefreshHoldButton = GetGame().GetTime();
                Right();
            }
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), and Right().
Referenced by UIScriptedMenu::Update().
RightRelease()
override void ServerBrowserTab::RightRelease () inline private
Definition at line 421 of file serverbrowsertabconsolepages.c.
    {
        if ( !m_IsFilterFocused && GetCurrentPage() != m_PreviousPage )
        {
            RefreshList();
        }
    }
References GetCurrentPage(), and ServerBrowserTabConsolePages::RefreshList().
Referenced by UIScriptedMenu::Update().
SelectServer()
override void ServerBrowserTab::SelectServer (ServerBrowserEntry server) inline private
Definition at line 638 of file serverbrowsertabpc.c.
    {
        super.SelectServer( server );
        #ifdef PLATFORM_CONSOLE
        ScrollToEntry( server );
        #endif
        m_SelectedServer = server;
        if (!m_Menu)
            return;
        m_Menu.SelectServer( server );
    }
References m_Menu, m_SelectedServer, and ScrollToEntry().
Referenced by ScriptedWidgetEventHandler::Select().
SetEnableFilters() [1/2]
void ServerBrowserTab::SetEnableFilters (bool enable) inline private
Definition at line 350 of file serverbrowsertabconsole.c.
    {
        Widget w_filters = m_Root.FindAnyWidget("filters_content");
        Widget w_content = m_Root.FindAnyWidget("server_list_scroller");
        w_filters.Enable( enable );
        w_content.Enable( !enable );
    }
References m_Root.
Referenced by SetFocusFilters(), and SetFocusServers().
SetEnableFilters() [2/2]
void ServerBrowserTab::SetEnableFilters (bool enable) inline private
Definition at line 514 of file serverbrowsertabconsolepages.c.
    {
        Widget w_filters = m_Root.FindAnyWidget("filters_content");
        Widget w_content = m_Root.FindAnyWidget("server_list_scroller");
        w_content.Enable( !enable );
        if ( enable )
        {
            SetFocus( ButtonWidget.Cast(w_filters.FindWidget("sort_button")) );
        }
    }
References m_Root, and SetFocus().
SetEnableServers() [1/2]
void ServerBrowserTab::SetEnableServers (bool enable) inline private
Definition at line 358 of file serverbrowsertabconsole.c.
    {
        Widget w_filters = m_Root.FindAnyWidget("filters_content");
        Widget w_content = m_Root.FindAnyWidget("server_list_scroller");
        w_filters.Enable( !enable );
        w_content.Enable( enable );
    }
References m_Root.
Referenced by SetFocusFilters(), and SetFocusServers().
SetEnableServers() [2/2]
void ServerBrowserTab::SetEnableServers (bool enable) inline private
Definition at line 526 of file serverbrowsertabconsolepages.c.
    {
        Widget w_filters = m_Root.FindAnyWidget("filters_content");
        Widget w_content = m_Root.FindAnyWidget("server_list_scroller");
        w_content.Enable( enable );
    }
References m_Root.
SetFocusFilters() [1/2]
void ServerBrowserTab::SetFocusFilters () inline private
Definition at line 307 of file serverbrowsertabconsole.c.
    {
        SetEnableFilters( true );
        SetEnableServers( false );
        // if loaded servers is 0, then hide Top navigation menu <Left / Right>
        m_WidgetNavFilters.Show( (m_EntryWidgets.Count() > 0) );
        m_WidgetNavServers.Show( false );
        m_Filters.Focus();
        m_IsFilterFocused = true;
    }
References m_EntryWidgets, m_Filters, SetEnableFilters(), and SetEnableServers().
Referenced by Construct(), PressSholderLeft(), PressSholderRight(), RefreshList(), and SetFocusServers().
SetFocusFilters() [2/2]
void ServerBrowserTab::SetFocusFilters () inline private
Definition at line 468 of file serverbrowsertabconsolepages.c.
    {
        SetEnableFilters(true);
        SetEnableServers(false);
        // if loaded servers is 0, then hide Top navigation menu <Left / Right>
        if (!m_MouseKeyboardControlled)
        {
            m_WidgetNavFilters.Show(true);
            m_WidgetNavServers.Show(false);
        }
        m_Filters.Focus();
        m_IsFilterFocused = true;
        UpdatePageButtons();
    }
References m_Filters.
SetFocusServers() [1/2]
void ServerBrowserTab::SetFocusServers () inline private
Definition at line 330 of file serverbrowsertabconsole.c.
    {
        SetEnableServers( true );
        SetEnableFilters( false );
        m_WidgetNavFilters.Show( false );
        m_WidgetNavServers.Show( true );
        array<ref GetServersResultRow> entries = m_EntriesSorted[m_SortType];
        if( entries.Count() > 0 )
        {
            m_EntryWidgets.Get(entries.Get(0).GetIpPort()).Focus();
            m_IsFilterFocused = false;
        }
        else
        {
            SetFocusFilters();
        }
    }
References m_EntriesSorted, m_EntryWidgets, m_SortType, SetEnableFilters(), SetEnableServers(), and SetFocusFilters().
Referenced by Focus(), LoadEntries(), PressSholderLeft(), and PressSholderRight().
SetFocusServers() [2/2]
void ServerBrowserTab::SetFocusServers () inline private
Definition at line 486 of file serverbrowsertabconsolepages.c.
    {
        SetEnableServers(true);
        SetEnableFilters(false);
        if (!m_MouseKeyboardControlled)
        {
            m_WidgetNavFilters.Show(false);
            m_WidgetNavServers.Show(true);
        }
        array<ref GetServersResultRow> entries = m_EntriesSorted[m_SortType];
        if ( entries && entries.Count() > 0 )
        {
            m_EntryWidgets.Get(entries.Get(0).GetIpPort()).Focus();
        }
        else
        {
            SetFocus( null );
        }
        m_IsFilterFocused = false;
        m_Menu.ShowYButton(true);
        m_Menu.ShowAButton(true);
        UpdatePageButtons();
    }
References m_EntriesSorted, m_EntryWidgets, m_Menu, m_SortType, and SetFocus().
SetPageIndex()
void ServerBrowserTab::SetPageIndex (int page_index) inline private
Definition at line 464 of file serverbrowsertabpc.c.
    {
        m_PageIndex = page_index;
        UpdateServerList();
        UpdatePageButtons();
    }
SetSort()
override void ServerBrowserTab::SetSort (ESortType type, ESortOrder order) inline private
Definition at line 502 of file serverbrowsertabpc.c.
    {
        super.SetSort( type, order);
        #ifdef PLATFORM_WINDOWS
        m_Root.FindAnyWidget( "host_sort" ).Show( false );
        m_Root.FindAnyWidget( "population_sort" ).Show( false );
        m_Root.FindAnyWidget( "slots_sort" ).Show( false );
        m_Root.FindAnyWidget( "time_sort" ).Show( false );
        m_Root.FindAnyWidget( "ping_sort" ).Show( false );
        TextWidget root;
        root = TextWidget.Cast( m_Root.FindAnyWidget( "server_list_content_header_host_label" ) );
        root.SetColor( ARGBF( 1, 1, 1, 1 ) );
        root = TextWidget.Cast( m_Root.FindAnyWidget( "server_list_content_header_population_label" ) );
        root.SetColor( ARGBF( 1, 1, 1, 1 ) );
        root = TextWidget.Cast( m_Root.FindAnyWidget( "server_list_content_header_slots_label" ) );
        root.SetColor( ARGBF( 1, 1, 1, 1 ) );
        root = TextWidget.Cast( m_Root.FindAnyWidget( "server_list_content_header_ping_label" ) );
        root.SetColor( ARGBF( 1, 1, 1, 1 ) );
        root = TextWidget.Cast( m_Root.FindAnyWidget( "server_list_content_header_time_label" ) );
        root.SetColor( ARGBF( 1, 1, 1, 1 ) );
        string r_name;
        string w_name;
        switch ( type )
        {
            case ESortType.HOST:
            {
                r_name = "server_list_content_header_host_label";
                w_name = "host_sort";
                break;
            }
            case ESortType.TIME:
            {
                r_name = "server_list_content_header_time_label";
                w_name = "time_sort";
                break;
            }
            case ESortType.POPULATION:
            {
                r_name = "server_list_content_header_population_label";
                w_name = "population_sort";
                break;
            }
            case ESortType.SLOTS:
            {
                r_name = "server_list_content_header_slots_label";
                w_name = "slots_sort";
                break;
            }
            case ESortType.PING:
            {
                r_name = "server_list_content_header_ping_label";
                w_name = "ping_sort";
                break;
            }
        }
        root = TextWidget.Cast( m_Root.FindAnyWidget( r_name ) );
        root.SetColor( ARGBF( 1, 1, 0, 0 ) );
        m_Root.FindAnyWidget( w_name ).Show( true );
        m_Root.FindAnyWidget( w_name + "_asc" ).Show( !m_SortOrder );
        m_Root.FindAnyWidget( w_name + "_dsc" ).Show( m_SortOrder );
        #endif
    }
References ARGBF(), m_Root, and m_SortOrder.
Referenced by Construct(), and ScriptedWidgetEventHandler::OnSortChanged().
ShowHideConsoleWidgets() [1/2]
void ServerBrowserTab::ShowHideConsoleWidgets () inline private
Definition at line 48 of file serverbrowsertabconsole.c.
    {
#ifdef PLATFORM_PS4
        bool is_xbox = false;
#else
        bool is_xbox = true;
#endif
        m_Root.FindAnyWidget( "filters_root_nav_img_lb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_rb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_lb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_rb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_l1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_r1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_l1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_r1_ps4" ).Show( !is_xbox );
    }
References m_Root.
Referenced by Construct().
ShowHideConsoleWidgets() [2/2]
void ServerBrowserTab::ShowHideConsoleWidgets () inline private
Definition at line 96 of file serverbrowsertabconsolepages.c.
    {
        bool is_xbox = true;
#ifdef PLATFORM_PS4
        is_xbox = false;
#endif
        m_Root.FindAnyWidget( "filters_button_wrapper" ).Show( GetGame().GetInput().IsEnabledMouseAndKeyboard() );
        m_Root.FindAnyWidget( "filters_root_nav_img_lb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_rb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_lb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_rb_xbox" ).Show( is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_l1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "filters_root_nav_img_r1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_l1_ps4" ).Show( !is_xbox );
        m_Root.FindAnyWidget( "server_list_root_nav_img_r1_ps4" ).Show( !is_xbox );
    }
References GetGame(), GetInput(), and m_Root.
SortedInsert()
int ServerBrowserTab::SortedInsert (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 654 of file serverbrowsertabpc.c.
    {
        if ( m_SortInverted[sort_type] )
        {
            return SortedInsertDesc(entry, sort_type);
        }
        return SortedInsertAsc(entry, sort_type);
    }
References m_SortInverted.
SortedInsertAsc()
int ServerBrowserTab::SortedInsertAsc (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 664 of file serverbrowsertabpc.c.
    {
        array<ref GetServersResultRow> list = m_EntriesSorted[sort_type];
        int i;
        int index_min = 0;
        int index_max = list.Count() - 1;
        int target_index = Math.Floor( index_max / 2 );
        if ( index_max == -1 )
        {
            list.Insert( entry );
            return 0;
        }
        if ( sort_type == ESortType.HOST )
        {
            string entry_value_str = entry.GetValueStr(ESortType.HOST);
            while ( true )
            {
                string target_value_str = list[target_index].GetValueStr(ESortType.HOST);
                if ( entry_value_str == target_value_str || ((index_max - index_min) <= 1) )
                {
                    for ( i = index_min; i <= index_max; i++ )
                    {
                        if ( entry_value_str <= list[i].GetValueStr(ESortType.HOST) )
{
                            list.InsertAt( entry, i );
                            return i;
                        }
                    }
                    index_max++;
                    list.InsertAt( entry, index_max );
                    return target_index;
                }
                else if ( entry_value_str < target_value_str )
                {
                    index_max = target_index;
                    target_index = Math.Floor( target_index / 2 );
                }
                else if ( entry_value_str > target_value_str )
                {
                    index_min = target_index;
                    target_index += Math.Floor( (index_max - index_min) / 2 );
                }
            }
        }
        else
        {
            int entry_value_int = entry.GetValueInt( sort_type );
            while ( true )
            {
                int target_value_int = list[target_index].GetValueInt( sort_type );
                if ( entry_value_int == target_value_int || ((index_max - index_min) <= 1) )
                {
                    for ( i = index_min; i <= index_max; i++ )
                    {
                        if ( entry_value_int <= list[i].GetValueInt( sort_type ) )
{
                            list.InsertAt( entry, i );
                            return i;
                        }
                    }
                    index_max++;
                    list.InsertAt( entry, index_max );
                    return target_index;
                }
                else if ( entry_value_int < target_value_int )
                {
                    index_max = target_index;
                    target_index = Math.Floor( target_index / 2 );
                }
                else if ( entry_value_int > target_value_int )
                {
                    index_min = target_index;
                    target_index += Math.Floor( (index_max - index_min) / 2 );
                }
            }
        }
        return target_index;
    }
References Math::Floor(), GetValueInt(), GetValueStr(), and m_EntriesSorted.
SortedInsertDesc()
int ServerBrowserTab::SortedInsertDesc (GetServersResultRow entry, ESortType sort_type) inline private
Definition at line 753 of file serverbrowsertabpc.c.
    {
        array<ref GetServersResultRow> list = m_EntriesSorted[sort_type];
        int i;
        int index_min = 0;
        int index_max = list.Count() - 1;
        int target_index = Math.Floor( index_max / 2 );
        if ( index_max == -1 )
        {
            list.Insert( entry );
            return 0;
        }
        if ( sort_type == ESortType.HOST )
        {
            string entry_value_str = entry.GetValueStr(ESortType.HOST);
            while ( true )
            {
                string target_value_str = list[target_index].GetValueStr(ESortType.HOST);
                if ( entry_value_str == target_value_str || ((index_max - index_min) <= 1) )
                {
                    for ( i = index_min; i <= index_max; i++ )
                    {
                        if ( entry_value_str >= list[i].GetValueStr(ESortType.HOST) )
{
                            list.InsertAt( entry, i );
                            return i;
                        }
                    }
                    index_max++;
                    list.InsertAt( entry, index_max );
                    return target_index;
                }
                else if ( entry_value_str > target_value_str )
                {
                    index_max = target_index;
                    target_index = Math.Floor( target_index / 2 );
                }
                else if ( entry_value_str < target_value_str )
                {
                    index_min = target_index;
                    target_index += Math.Floor( (index_max - index_min) / 2 );
                }
            }
        }
        else
        {
            int entry_value_int = entry.GetValueInt( sort_type );
            while ( true )
            {
                int target_value_int = list[target_index].GetValueInt( sort_type );
                if ( entry_value_int == target_value_int || ((index_max - index_min) <= 1) )
                {
                    for ( i = index_min; i <= index_max; i++ )
                    {
                        if ( entry_value_int >= list[i].GetValueInt( sort_type ) )
{
                            list.InsertAt( entry, i );
                            return i;
                        }
                    }
                    index_max++;
                    list.InsertAt( entry, index_max );
                    return target_index;
                }
                else if ( entry_value_int > target_value_int )
                {
                    index_max = target_index;
                    target_index = Math.Floor( target_index / 2 );
                }
                else if ( entry_value_int < target_value_int )
                {
                    index_min = target_index;
                    target_index += Math.Floor( (index_max - index_min) / 2 );
                }
            }
        }
        return target_index;
    }
References Math::Floor(), GetValueInt(), GetValueStr(), and m_EntriesSorted.
ToggleSort()
void ServerBrowserTab::ToggleSort (ESortType type) inline private
Definition at line 471 of file serverbrowsertabpc.c.
    {
        ESortOrder order = ESortOrder.ASCENDING;
        if ( m_SortType != type )
        {
            if ( m_SortInverted[type] == true )
            {
                m_EntriesSorted[type].Invert();
            }
            m_SortInverted[type] = false;
        }
        else
        {
            if ( m_SortOrder == ESortOrder.ASCENDING )
            {
                m_EntriesSorted[type].Invert();
                m_SortInverted[type] = true;
                order = ESortOrder.DESCENDING;
            }
            else
            {
                m_EntriesSorted[type].Invert();
                m_SortInverted[type] = false;
            }
        }
        SetSort( type, order );
    }
References m_EntriesSorted, m_SortInverted, m_SortOrder, m_SortType, and SetSort().
UpdatePageButtons() [1/2]
void ServerBrowserTab::UpdatePageButtons () inline private
Definition at line 533 of file serverbrowsertabconsolepages.c.
    {
        TextWidget wgt_page_stat = TextWidget.Cast( m_Root.FindAnyWidget( "servers_navigation_page_status" ) );
        wgt_page_stat.SetText( GetCurrentPage().ToString() +" / "+ m_PagesCount.ToString() );
        if ( !m_IsFilterFocused && (m_PagesCount > 1) && !m_MouseKeyboardControlled )
        {
            bool can_left = (GetCurrentPage() > 1);
            m_ButtonPageLeftImg.Show( can_left );
            m_BtnPagePrev.Show( can_left );
            bool can_right = (GetCurrentPage() < m_PagesCount);
            m_ButtonPageRightImg.Show( can_right );
            m_BtnPageNext.Show( can_right );
        }
        else
        {
            m_ButtonPageLeftImg.Show( false );
            m_BtnPagePrev.Show( false );
            m_ButtonPageRightImg.Show( false );
            m_BtnPageNext.Show( false );
        }
    }
References GetCurrentPage(), m_BtnPageNext, m_BtnPagePrev, m_Root, ToString(), and string::ToString().
UpdatePageButtons() [2/2]
void ServerBrowserTab::UpdatePageButtons () inline private
Definition at line 842 of file serverbrowsertabpc.c.
    {
        m_PagesCount = Math.Ceil( m_TotalLoadedServers / SERVERS_VISIBLE_COUNT );
        if ( m_PagesCount > 1 )
        {
            m_PnlPagesPanel.Show( true );
            int i;
            int btn_index_center = Math.Round( PAGES_BUTTONS_COUNT / 2) - 1;
            m_PageStartNum = 1;
            m_PageEndNum = PAGES_BUTTONS_COUNT;
            if ( m_PagesCount <= PAGES_BUTTONS_COUNT )
            {
                m_PageEndNum = m_PagesCount;
                // Pages are less like buttons - changing selected button
                for ( i = 1; i <= m_BtnPages.Count(); ++i )
                {
                    bool is_page_button_enable = ( i <= m_PagesCount );
                    int page_index = (i - 1);
                    m_BtnPages[page_index].Show( is_page_button_enable );
                    m_BtnPages[page_index].SetText( i.ToString() );
                    if ( m_PageIndex == page_index )
                    {
                        m_BtnPages[page_index].SetState( true );
                    }
                    else
                    {
                        m_BtnPages[page_index].SetState( false );
                    }
                }
            }
            else
            {
                // Pages are more like buttons
                if ( m_PageIndex <= btn_index_center )
                {
                    //Left side (start of pages)
                    //m_PageStartNum = 1;
                    //m_PageEndNum = PAGES_BUTTONS_COUNT;
                }
                else
                {
                    m_PageStartNum = m_PageIndex - btn_index_center + 1;
                    m_PageEndNum = m_PageIndex + (PAGES_BUTTONS_COUNT - btn_index_center);
                    if ( m_PageEndNum > m_PagesCount )
                    {
                        // Right side (end of pages)
                        m_PageStartNum -= m_PageEndNum - m_PagesCount;
                        m_PageEndNum -= m_PageEndNum - m_PagesCount;
                    }
                }
                // Button Selection
                int selected_btn_index = m_PageIndex;
                if ( m_PageIndex > btn_index_center )
                {
                    if ( m_PageEndNum == m_PagesCount )
                    {
                        //Right
                         selected_btn_index = PAGES_BUTTONS_COUNT - (m_PagesCount - m_PageIndex);
                    }
                    else
                    {
                        //Center
                        selected_btn_index = btn_index_center;
                    }
                }
                for ( i = 0; i < m_BtnPages.Count(); ++i )
                {
                    m_BtnPages[i].SetText( (m_PageStartNum + i).ToString() );
                    m_BtnPages[i].SetState( ( i == selected_btn_index ) );
                }
            }
            // Button GoTo Prev Page
            if ( m_PageIndex > 0 )
            {
                m_BtnPagePrev.SetText( "<" );
                m_BtnPagePrev.Enable( true );
            }
            else
            {
                m_BtnPagePrev.SetText( "" );
                m_BtnPagePrev.Enable( false );
            }
            // Button GoTo Next Page
            if ( m_PageIndex < (m_PagesCount - 1) )
            {
                m_BtnPageNext.SetText( ">" );
                m_BtnPageNext.Enable( true );
            }
            else
            {
                m_BtnPageNext.SetText( "" );
                m_BtnPageNext.Enable( false );
            }
            // Button GoTo First Page
            if ( m_PageStartNum == 1 )
            {
                m_BtnPagesFirst.SetText( "" );
                m_BtnPagesFirst.Enable( false );
            }
            else
            {
                m_BtnPagesFirst.SetText( "<<" );
                m_BtnPagesFirst.Enable( true );
            }
            // Button GoTo Last Page
            if ( m_PageEndNum == m_PagesCount )
            {
                m_BtnPagesLast.SetText( "" );
                m_BtnPagesLast.Enable( false );
            }
            else
            {
                m_BtnPagesLast.SetText( ">>" );
                m_BtnPagesLast.Enable( true );
            }
        }
        else
        {
            m_PnlPagesPanel.Show(false);
        }
    }
References Math::Ceil(), m_BtnPageNext, m_BtnPagePrev, m_TotalLoadedServers, and Math::Round().
UpdateServerList()
void ServerBrowserTab::UpdateServerList () inline private
Definition at line 978 of file serverbrowsertabpc.c.
    {
        int lastFilledIndexOnPage = 0;
        m_TotalLoadedServers = m_EntriesSorted[m_SortType].Count();
        ServerBrowserEntry entry;
        m_EntryWidgets.Clear();
        for ( int i = 0; i < SERVERS_VISIBLE_COUNT; ++i )
        {
            int serverIndex = i + (SERVERS_VISIBLE_COUNT * m_PageIndex);
            if ( serverIndex < m_EntriesSorted[m_SortType].Count() )
            {
                GetServersResultRow server_info = m_EntriesSorted[m_SortType][serverIndex];
                if ( server_info.m_Favorite )
                {
                    m_OnlineFavServers.Insert(server_info.m_Id);
                }
                entry = GetServerEntryByIndex(i, server_info.m_Id);
                entry.Show( true );
                entry.SetIsOnline( true );
                entry.FillInfo( server_info );
                entry.SetMods( m_EntryMods.Get( server_info.m_Id ) );
                entry.UpdateEntry();
                if ( GetRootMenu() && GetRootMenu().GetServersLoadingTab() != TabType.NONE )
                {
                    entry.SetName("#dayz_game_loading");
                }
                lastFilledIndexOnPage++;
            }
            else
            {
                entry = GetServerEntryByIndex(i, "-1");
                if ( entry )
                {
                    entry.Show( false );
                }
            }
        }
        LoadExtraEntries(lastFilledIndexOnPage);
        m_ServerList.Update();
    }
References Count, GetRootMenu(), ServerBrowserTabPc::LoadExtraEntries(), m_EntriesSorted, m_EntryMods, m_EntryWidgets, m_OnlineFavServers, m_ServerList, m_SortType, and m_TotalLoadedServers.
UpdateStatusBar()
void ServerBrowserTab::UpdateStatusBar () inline private
Definition at line 1028 of file serverbrowsertabpc.c.
    {
        string serversFound = string.Format("#servers_found: %1", m_TotalLoadedServers);
        if ( m_LoadingFinished )
        {
            m_LoadingText.SetText( serversFound );
        }
        else
        {
            m_LoadingText.SetText( string.Format("#dayz_game_loading %1", serversFound) );
        }
    }
References m_LoadingFinished, m_LoadingText, and m_TotalLoadedServers.
Member Data Documentation
m_BtnPages
protected ref array<ButtonWidget> ServerBrowserTab::m_BtnPages private
Definition at line 23 of file serverbrowsertabpc.c.
m_BtnPagesFirst
protected ButtonWidget ServerBrowserTab::m_BtnPagesFirst private
Definition at line 15 of file serverbrowsertabpc.c.
m_BtnPagesLast
protected ButtonWidget ServerBrowserTab::m_BtnPagesLast private
Definition at line 16 of file serverbrowsertabpc.c.
m_ButtonPageLeftImg
protected Widget ServerBrowserTab::m_ButtonPageLeftImg private
Definition at line 10 of file serverbrowsertabconsolepages.c.
m_ButtonPageRightImg
protected Widget ServerBrowserTab::m_ButtonPageRightImg private
Definition at line 11 of file serverbrowsertabconsolepages.c.
m_FilterPanelAccTime
protected Widget ServerBrowserTab::m_FilterPanelAccTime private
Definition at line 21 of file serverbrowsertabpc.c.
m_FilterPanelPing
protected Widget ServerBrowserTab::m_FilterPanelPing private
Definition at line 20 of file serverbrowsertabpc.c.
m_FilterSearchIP
protected Widget ServerBrowserTab::m_FilterSearchIP private
Definition at line 18 of file serverbrowsertabpc.c.
m_FilterSearchIPBox
protected Widget ServerBrowserTab::m_FilterSearchIPBox private
Definition at line 19 of file serverbrowsertabpc.c.
m_IsFilterChanged
private bool ServerBrowserTab::m_IsFilterChanged private
Definition at line 3 of file serverbrowsertabconsole.c.
m_IsFilterFocused
private bool ServerBrowserTab::m_IsFilterFocused private
Definition at line 4 of file serverbrowsertabconsole.c.
m_PageEndNum
protected int ServerBrowserTab::m_PageEndNum private
Definition at line 16 of file serverbrowsertabconsolepages.c.
m_PageIndex
protected int ServerBrowserTab::m_PageIndex private
Definition at line 7 of file serverbrowsertabpc.c.
m_PagesCount
protected int ServerBrowserTab::m_PagesCount private
Definition at line 17 of file serverbrowsertabconsolepages.c.
m_PageStartNum
protected int ServerBrowserTab::m_PageStartNum private
Definition at line 15 of file serverbrowsertabconsolepages.c.
m_PnlPagesLoadingText
protected TextWidget ServerBrowserTab::m_PnlPagesLoadingText private
Definition at line 23 of file serverbrowsertabconsolepages.c.
m_PnlPagesPanel
protected Widget ServerBrowserTab::m_PnlPagesPanel private
Definition at line 22 of file serverbrowsertabconsolepages.c.
m_PreviousPage
protected int ServerBrowserTab::m_PreviousPage private
Definition at line 13 of file serverbrowsertabconsolepages.c.
m_ServerListEntiers
protected ref array<ref ServerBrowserEntry> ServerBrowserTab::m_ServerListEntiers private
Definition at line 24 of file serverbrowsertabconsolepages.c.
m_ServerListEntries
protected ref array<ref ServerBrowserEntry> ServerBrowserTab::m_ServerListEntries private
Definition at line 24 of file serverbrowsertabpc.c.
m_ServersEstimateCount
protected int ServerBrowserTab::m_ServersEstimateCount private
Definition at line 18 of file serverbrowsertabconsolepages.c.
m_TempTime
protected ref TStringArray ServerBrowserTab::m_TempTime = new TStringArray private
Definition at line 26 of file serverbrowsertabpc.c.
m_TimeLastServerRefresh
protected int ServerBrowserTab::m_TimeLastServerRefresh private
Definition at line 19 of file serverbrowsertabconsolepages.c.
m_TimeLastServerRefreshHoldButton
protected int ServerBrowserTab::m_TimeLastServerRefreshHoldButton private
Definition at line 20 of file serverbrowsertabconsolepages.c.
m_TotalServersCount
protected int ServerBrowserTab::m_TotalServersCount private
Definition at line 14 of file serverbrowsertabconsolepages.c.
m_WidgetNavFilters [1/2]
private Widget ServerBrowserTab::m_WidgetNavFilters private
Definition at line 6 of file serverbrowsertabconsole.c.
m_WidgetNavFilters [2/2]
protected bool m_MouseKeyboardControlled private Widget ServerBrowserTab::m_WidgetNavFilters private
Definition at line 7 of file serverbrowsertabconsolepages.c.
m_WidgetNavServers
private Widget ServerBrowserTab::m_WidgetNavServers private
Definition at line 7 of file serverbrowsertabconsole.c.
PAGES_BUTTONS_COUNT
protected const int ServerBrowserTab::PAGES_BUTTONS_COUNT = 10 private
Definition at line 4 of file serverbrowsertabpc.c.
SERVERS_VISIBLE_COUNT
protected const int ServerBrowserTab::SERVERS_VISIBLE_COUNT = 24 private
Definition at line 3 of file serverbrowsertabpc.c.