DayzKode: ConnectionLost Class Reference
ConnectionLost Class Reference
Private Member Functions
void ConnectionLost (DayZGame game)
float GetDuration ()
void Hide ()
void SetDuration (float duration)
void SetText (string text)
void Show ()
Private Attributes
private float m_duration
private TextWidget m_TextWidgetTitle
private ref Widget m_WidgetRoot
Detailed Description
Definition at line 538 of file dayzgame.c.
Constructor & Destructor Documentation
ConnectionLost()
void ConnectionLost::ConnectionLost (DayZGame game) inline private
Definition at line 544 of file dayzgame.c.
    {
        m_WidgetRoot = game.GetWorkspace().CreateWidgets("gui/layouts/day_z_connection_lost.layout");
        m_WidgetRoot.Show(false);
        Class.CastTo(m_TextWidgetTitle, m_WidgetRoot.FindAnyWidget("TextWidget"));
        m_duration = 0.0;
    }
References Class::CastTo(), m_duration, m_TextWidgetTitle, and m_WidgetRoot.
Member Function Documentation
GetDuration()
float ConnectionLost::GetDuration () inline private
Definition at line 580 of file dayzgame.c.
    {
        return m_duration;
    }
References m_duration.
Referenced by OnMPConnectionLostEvent().
Hide()
void ConnectionLost::Hide () inline private
Definition at line 567 of file dayzgame.c.
    {
        if ( m_WidgetRoot.IsVisible() )
        {
            m_WidgetRoot.Show( false );
        }
    }
References m_WidgetRoot.
Referenced by OnMPConnectionLostEvent().
SetDuration()
void ConnectionLost::SetDuration (float duration) inline private
Definition at line 585 of file dayzgame.c.
    {
        m_duration = duration;
    }
References m_duration.
Referenced by OnMPConnectionLostEvent().
SetText()
void ConnectionLost::SetText (string text) inline private
Definition at line 575 of file dayzgame.c.
    {
        m_TextWidgetTitle.SetText(text);
    }
References m_TextWidgetTitle.
Referenced by OnMPConnectionLostEvent().
Show()
void ConnectionLost::Show () inline private
Definition at line 553 of file dayzgame.c.
    {
        if ( !m_WidgetRoot.IsVisible() )
        {
            if ( g_Game.GetUIManager().IsDialogVisible() )
            {
                g_Game.GetUIManager().HideDialog();
            }
            m_WidgetRoot.Show( true );
            m_TextWidgetTitle.SetText( "" );
        }
    }
References g_Game, m_TextWidgetTitle, and m_WidgetRoot.
Referenced by OnMPConnectionLostEvent().
Member Data Documentation
m_duration
private float ConnectionLost::m_duration private
Definition at line 542 of file dayzgame.c.
Referenced by ConnectionLost(), GetDuration(), and SetDuration().
m_TextWidgetTitle
private TextWidget ConnectionLost::m_TextWidgetTitle private
Definition at line 541 of file dayzgame.c.
Referenced by ConnectionLost(), SetText(), and Show().
m_WidgetRoot
private ref Widget ConnectionLost::m_WidgetRoot private
Definition at line 540 of file dayzgame.c.
Referenced by ConnectionLost(), Hide(), and Show().