DayzKode: ActionSwapItemToHands Class Reference
ActionSwapItemToHands Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateAndSetupActionCallback (ActionData action_data)
override bool MainItemAlwaysInHands ()
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void PerformSwap (ActionData action_data)
override void Start (ActionData action_data)
override bool UseMainItem ()
Private Attributes
bool m_Executable
Detailed Description
Definition at line 108 of file actiontakeitemtohands.c.
Member Function Documentation
ActionCondition()
override bool ActionSwapItemToHands::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 112 of file actiontakeitemtohands.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        if ( !tgt_item || !tgt_item.IsTakeable() || tgt_item.IsBeingPlaced() )
            return false;
        return player.GetInventory().CanSwapEntitiesEx(tgt_item,item);
    }
References ItemBase::IsTakeable().
CreateAndSetupActionCallback()
override void ActionSwapItemToHands::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 131 of file actiontakeitemtohands.c.
    {
        EntityAI target = EntityAI.Cast(action_data.m_Target.GetObject());
        ActionBaseCB callback;
        if (!target)
            return;
        if (target.IsHeavyBehaviour())
        {
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            return;
        }
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
MainItemAlwaysInHands()
override bool ActionSwapItemToHands::MainItemAlwaysInHands () inline private
Definition at line 126 of file actiontakeitemtohands.c.
    {
        return true;
    }
OnEndClient()
override void ActionSwapItemToHands::OnEndClient (ActionData action_data) inline private
Definition at line 203 of file actiontakeitemtohands.c.
    {
        if (m_Executable)
        {
            m_Executable = false;
            return;
        }
        PerformSwap(action_data);
    }
References m_Executable, and PerformSwap().
OnEndServer()
override void ActionSwapItemToHands::OnEndServer (ActionData action_data) inline private
Definition at line 189 of file actiontakeitemtohands.c.
    {
        if (m_Executable)
        {
            m_Executable = false;
            return;
        }
        if (GetGame().IsMultiplayer())
            return;
        PerformSwap(action_data);
    }
References GetGame(), m_Executable, and PerformSwap().
OnExecuteClient()
override void ActionSwapItemToHands::OnExecuteClient (ActionData action_data) inline private
Definition at line 181 of file actiontakeitemtohands.c.
    {
        if (!m_Executable)
            return;
        PerformSwap(action_data);
    }
References m_Executable, and PerformSwap().
OnExecuteServer()
override void ActionSwapItemToHands::OnExecuteServer (ActionData action_data) inline private
Definition at line 170 of file actiontakeitemtohands.c.
    {
        if (!m_Executable)
            return;
        if (GetGame().IsMultiplayer())
            return;
        PerformSwap(action_data);
    }
References GetGame(), m_Executable, and PerformSwap().
PerformSwap()
void ActionSwapItemToHands::PerformSwap (ActionData action_data) inline private
Definition at line 214 of file actiontakeitemtohands.c.
    {
        EntityAI ntarget = EntityAI.Cast(action_data.m_Target.GetObject());
        if (action_data.m_Player)
        {
            InventoryMode invMode = InventoryMode.PREDICTIVE;
            if (action_data.m_Player.NeedInventoryJunctureFromServer(ntarget, ntarget.GetHierarchyParent(), action_data.m_Player))
                invMode = InventoryMode.JUNCTURE;
            action_data.m_Player.TakeEntityToHandsImpl(invMode, ntarget);
        }
    }
References ActionData::m_Player, and ActionData::m_Target.
Referenced by OnEndClient(), OnEndServer(), OnExecuteClient(), and OnExecuteServer().
Start()
override void ActionSwapItemToHands::Start (ActionData action_data) inline private
Definition at line 151 of file actiontakeitemtohands.c.
    {
        super.Start( action_data );
        //Print("action_data.m_Target.GetObject() + " + action_data.m_Target.GetObject());
        //Print("action_data.m_MainItem + " + action_data.m_MainItem);
        bool b1 = action_data.m_MainItem.ConfigGetString("physLayer") == "item_large";
        action_data.m_MainItem.m_ThrowItemOnDrop = b1; //hack, should be redundant anyway
        EntityAI object = EntityAI.Cast(action_data.m_Target.GetObject());
        if (!object || !object.IsHeavyBehaviour())
        {
            action_data.m_Player.GetActionManager().Interrupt();
        }
        else
            m_Executable = true;
    }
References IsHeavyBehaviour(), m_Executable, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
UseMainItem()
override bool ActionSwapItemToHands::UseMainItem () inline private
Definition at line 121 of file actiontakeitemtohands.c.
    {
        return true;
    }
Member Data Documentation
m_Executable
bool ActionSwapItemToHands::m_Executable private
Definition at line 110 of file actiontakeitemtohands.c.
Referenced by OnEndClient(), OnEndServer(), OnExecuteClient(), OnExecuteServer(), and Start().