DayzKode: HandsContainer Class Reference
HandsContainer Class Reference
Private Member Functions
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
override bool CanEquip ()
void CollapseButtonOnMouseButtonDown (Widget w)
void DestroyAtt ()
void DestroyCargo ()
void DoubleClick (Widget w, int x, int y, int button)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void DraggingOverHeader2 (Widget w, int x, int y, Widget receiver)
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
void ElectricityIcon ()
override bool EquipItem ()
int GetCombinationFlags (EntityAI entity1, EntityAI entity2)
override Header GetHeader ()
EntityAI GetItemPreviewItem (Widget w)
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
void HandsContainer (LayoutHolder parent)
void HideCargo ()
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
override bool InspectItem ()
override bool IsEmpty ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsLastIndex ()
void MouseClick2 (Widget w, int x, int y, int button)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver)
void OnPerformCombination (int combinationFlags)
override bool OnSelectButton ()
override void OnShow ()
override void Refresh ()
void RefreshHands ()
void RemoveItem ()
void ResetContainer ()
void ScrollToActiveContainer (Container active_container)
override void SetActive (bool active)
void SetFocusToIndex ()
override void SetLastActive ()
override void SetLayoutName ()
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags)
void ShowAtt (EntityAI entity)
void ShowCargo ()
override bool SplitItem ()
void TakeAsAttachment (Widget w, Widget receiver)
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void UnfocusAll ()
override void UnfocusGrid ()
override void UpdateInterval ()
void ~HandsContainer ()
Private Attributes
protected ref map< EntityAI, ref Attachments > m_AttachmentAttachments
protected ref map< EntityAI, AttachmentsWrapper > m_AttachmentAttachmentsContainers
protected ref map< EntityAI, ref CargoContainer > m_AttachmentCargos
protected ref array< int > m_AttachmentSlotsSorted
protected ref Attachments m_Atts
protected ref CargoContainer m_CargoGrid
protected ref HandsHeader m_CollapsibleHeader
protected ref HandsPreview m_HandsPreview
protected bool m_Hidden
protected ScrollWidget m_ScrollWidget
protected int m_StaticAttCount = 0
protected int m_StaticCargoCount = 0
Detailed Description
Definition at line 1 of file handscontainer.c.
Constructor & Destructor Documentation
HandsContainer()
void HandsContainer::HandsContainer (LayoutHolder parent) inline private
Definition at line 20 of file handscontainer.c.
    {
        m_AttachmentCargos                  = new map<EntityAI, ref CargoContainer>;
        m_AttachmentAttachmentsContainers   = new map<EntityAI, AttachmentsWrapper>;
        m_AttachmentAttachments             = new map<EntityAI, ref Attachments>;
        m_CollapsibleHeader = new HandsHeader( this, "CollapseButtonOnMouseButtonDown" );
        GetMainWidget().SetFlags( WidgetFlags.IGNOREPOINTER );
        m_MainWidget = m_MainWidget.FindWidget( "body" );
        GetMainWidget().SetFlags( WidgetFlags.IGNOREPOINTER );
        m_Body = new array<ref LayoutHolder>;
        m_HandsPreview = new HandsPreview( this );
        ItemManager.GetInstance().SetHandsPreview( m_HandsPreview );
        m_Body.Insert( m_HandsPreview );
        ItemBase hands_item = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
        if ( hands_item )
            m_HandsPreview.CreateNewIcon( hands_item );
        m_ScrollWidget                      = ScrollWidget.Cast( m_RootWidget.GetParent().GetParent() );
        RecomputeOpenedContainers();
    }
References HandsPreview::CreateNewIcon(), GetGame(), ItemManager::GetInstance(), GetPlayer(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_CollapsibleHeader, m_HandsPreview, m_RootWidget, m_ScrollWidget, and ItemManager::SetHandsPreview().
~HandsContainer()
void HandsContainer::~HandsContainer () inline private
Definition at line 43 of file handscontainer.c.
    {
        if ( m_Entity )
        {
            m_Entity.GetOnItemAttached().Remove( AttachmentAdded );
            m_Entity.GetOnItemDetached().Remove( AttachmentRemoved );
        }
        m_AttachmentCargos.Clear();
        m_AttachmentAttachmentsContainers.Clear();
        m_AttachmentAttachments.Clear();
    }
References AttachmentAdded(), AttachmentRemoved(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_Entity, and ScriptedWidgetEventHandler::Remove().
Member Function Documentation
AttachmentAdded()
void HandsContainer::AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 1324 of file handscontainer.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString( slot );
        int sort = -1;
        Attachments att_cont = null;
        CargoContainer cont = null;
        if( item.GetInventory().GetAttachmentSlotsCount() > 0  )
        {
            att_cont = new Attachments( this, item );
            sort = (m_AttachmentSlotsSorted.Find( slot_id ) * 2) + SORT_ATTACHMENTS_NEXT_OFFSET;
            att_cont.InitAttachmentGrid( sort );
            m_AttachmentAttachments.Insert( item, att_cont );
            m_AttachmentAttachmentsContainers.Insert( item, att_cont.GetWrapper() );
            att_cont.UpdateInterval();
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        if( item.GetInventory().GetCargo() )
        {
            cont = new CargoContainer( this, true );
            sort = (m_AttachmentSlotsSorted.Find( slot_id ) * 2) + SORT_CARGO_NEXT_OFFSET; //m_AttachmentSlotsSorted.Find( slot_id ) + 50
            cont.GetRootWidget().SetSort( sort );
            cont.SetEntity( item );
            Insert(cont, -1);
            m_AttachmentCargos.Insert( item, cont );
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        if (att_cont)
        {
            att_cont.ShowFalseAttachmentsHeader(true);
            if (cont)
            {
                cont.ShowFalseCargoHeader(false);
                cont.UpdateSize();
                cont.SetAlternateFalseTextHeaderWidget(att_cont.GetFalseHeaderTextWidget());
            }
        }
        else if (cont)
        {
            cont.SetAlternateFalseTextHeaderWidget(null); //just to be safe..
        }
        RecomputeOpenedContainers();
    }
References Container::CargoContainer(), Attachments::GetFalseHeaderTextWidget(), InventorySlots::GetSlotIdFromString(), Attachments::GetWrapper(), Attachments::InitAttachmentGrid(), Insert(), Inventory(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, m_AttachmentSlotsSorted, m_Parent, Attachments::ShowFalseAttachmentsHeader(), and Attachments::UpdateInterval().
Referenced by DestroyAtt(), ShowAtt(), and ~HandsContainer().
AttachmentRemoved()
void HandsContainer::AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 1379 of file handscontainer.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString( slot );
        CargoContainer old_cont = m_AttachmentCargos.Get( item );
        if( old_cont )
        {
            m_Body.RemoveItem( old_cont );
            m_AttachmentCargos.Remove( item );
            delete old_cont;
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        AttachmentsWrapper old_att_cont = m_AttachmentAttachmentsContainers.Get( item );
        if( old_att_cont )
        {
            m_AttachmentAttachmentsContainers.Remove( item );
            m_AttachmentAttachments.Remove( item );
            m_Body.RemoveItem( old_att_cont );
            delete old_att_cont;
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        RecomputeOpenedContainers();
    }
References Container::CargoContainer(), InventorySlots::GetSlotIdFromString(), Inventory(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_AttachmentCargos, and m_Parent.
Referenced by DestroyAtt(), ShowAtt(), and ~HandsContainer().
CanEquip()
override bool HandsContainer::CanEquip () inline private
Definition at line 237 of file handscontainer.c.
    {
        if (m_ActiveIndex == 0)
        {
            EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
            if ( item_in_hands.IsInherited( Magazine ) || GetGame().GetPlayer().GetInventory().HasInventoryReservation(item_in_hands, null)  )
            {
                return false;
            }
            InventoryLocation il = new InventoryLocation;
            bool found = GetGame().GetPlayer().GetInventory().FindFreeLocationFor(item_in_hands,FindInventoryLocationType.ATTACHMENT,il);
            if (found)
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        else if( GetFocusedContainer() )
        {
            return GetFocusedContainer().CanEquip();
        }
        return false;
    }
References GetGame(), CGame::GetPlayer(), GetPlayer(), and HasInventoryReservation().
CollapseButtonOnMouseButtonDown()
void HandsContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 1547 of file handscontainer.c.
    {
        int i;
        if( !m_Hidden )
        {
            for (i = 0; i < m_Body.Count(); i++)
            {
                m_Body.Get( i ).OnHide();
            }
            m_Hidden = true;
        }
        else
        {
            for (i = 0; i < m_Body.Count(); i++)
            {
                m_Body.Get( i ).OnShow();
            }
            m_Hidden = false;
        }
        w.FindAnyWidget("opened").Show(m_Hidden);
        w.FindAnyWidget("closed").Show(!m_Hidden);
        m_Parent.Refresh();
    }
References m_Hidden, and m_Parent.
DestroyAtt()
void HandsContainer::DestroyAtt () inline private
Definition at line 926 of file handscontainer.c.
    {
        if( m_Atts )
        {
            m_Body.RemoveItem( m_Atts.GetWrapper() );
            delete m_Atts;
            if( m_Entity )
            {
                m_Entity.GetOnItemAttached().Remove( AttachmentAdded );
                m_Entity.GetOnItemDetached().Remove( AttachmentRemoved );
            }
        }
        if( m_AttachmentAttachmentsContainers )
        {
            foreach( EntityAI ent, AttachmentsWrapper att : m_AttachmentAttachmentsContainers )
            {
                m_Body.RemoveItem( att );
                m_AttachmentAttachments.Remove( ent );
                delete att;
            }
        }
        m_AttachmentAttachmentsContainers.Clear();
        Refresh();
        m_Parent.Refresh();
        RecomputeOpenedContainers();
    }
References AttachmentAdded(), AttachmentRemoved(), Attachments::GetWrapper(), m_AttachmentAttachments, m_AttachmentAttachmentsContainers, m_Atts, m_Entity, m_Parent, Refresh(), and ScriptedWidgetEventHandler::Remove().
DestroyCargo()
void HandsContainer::DestroyCargo () inline private
Definition at line 991 of file handscontainer.c.
    {
        if( m_CargoGrid )
        {
            m_Body.RemoveItem( m_CargoGrid );
            delete m_CargoGrid;
        }
        if( m_AttachmentCargos )
        {
            foreach( CargoContainer cargo : m_AttachmentCargos )
            {
                m_Body.RemoveItem( cargo );
                delete cargo;
            }
        }
        m_AttachmentCargos.Clear();
        Refresh();
        m_Parent.Refresh();
        RecomputeOpenedContainers();
    }
References Container::CargoContainer(), m_AttachmentCargos, m_CargoGrid, m_Parent, and Refresh().
DoubleClick()
void HandsContainer::DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 1459 of file handscontainer.c.
    {
        if( button == MouseState.LEFT )
        {
            if( w == null )
            {
                return;
            }
            ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
            if( !iw )
            {
              string name = w.GetName();
              name.Replace( "PanelWidget", "Render" );
              iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
            }
            if( !iw )
            {
              iw = ItemPreviewWidget.Cast( w );
            }
            if( !iw.GetItem() )
            {
                return;
            }
            ItemBase item = ItemBase.Cast( iw.GetItem() );
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
            Weapon_Base wpn;
            Magazine mag;
            if( Class.CastTo(wpn, item_in_hands ) )
            {
                return;
            }
            if( !item.GetInventory().CanRemoveEntity() )
                return;
            if( player.GetInventory().HasEntityInInventory( item ) && player.GetHumanInventory().CanAddEntityInHands( item ) )
            {
                player.PredictiveTakeEntityToHands( item );
            }
            else
            {
                if( player.GetInventory().CanAddEntityToInventory( item ) && player.GetHumanInventory().CanRemoveEntityInHands() )
                {
                    player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ANY, item );
                }
                else
                {
                    if( player.GetHumanInventory().CanAddEntityInHands( item ) )
                    {
                        player.PredictiveTakeEntityToHands( item );
                    }
                }
            }
            HideOwnedTooltip();
            name = w.GetName();
            name.Replace( "PanelWidget", "Temperature" );
            w.FindAnyWidget( name ).Show( false );
        }
    }
References Class::CastTo(), GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, and string::Replace().
DraggingOverGrid()
bool HandsContainer::DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline private
Definition at line 1103 of file handscontainer.c.
    {
        EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
        if( w == null )
        {
            return false;
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item || !item_in_hands )
        {
            return false;
        }
        int color;
        int idx = 0;
        int c_x, c_y;
        if( item_in_hands.GetInventory().GetCargo() )
        {
            c_x = item_in_hands.GetInventory().GetCargo().GetHeight();
            c_y = item_in_hands.GetInventory().GetCargo().GetWidth();
        }
        if( c_x > x && c_y > y && item_in_hands.GetInventory().CanAddEntityInCargoEx( item, 0, x, y, item.GetInventory().GetFlipCargo() ) )
        {
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
            color = ColorManager.GREEN_COLOR;
        }
        else
        {
            color = ColorManager.RED_COLOR;
            ItemManager.GetInstance().ShowSourceDropzone( item );
        }
        if( w.FindAnyWidget("Selected") )
        {
            w.FindAnyWidget("Selected").SetColor( color );
        }
        else
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Selected" );
            w.FindAnyWidget( name ).SetColor( color );
        }
        return true;
    }
References ItemManager::GetCenterDropzone(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), name, ColorManager::RED_COLOR, string::Replace(), ItemManager::ShowSourceDropzone(), x, and y.
Referenced by Icon::OnDraggingOverBackground().
DraggingOverHeader()
override void HandsContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 497 of file handscontainer.c.
    {
        if( w == null )
        {
            return;
        }
        EntityAI receiver_item;
        EntityAI slot_owner;
        int slot_id = -1;
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( w_ipw == null )
        {
            w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        }
        if( w_ipw == null )
        {
            return;
        }
        SlotsIcon slots_icon;
        receiver.GetUserData(slots_icon);
        if(slots_icon)
        {
            receiver_item   = slots_icon.GetEntity();
            slot_id         = slots_icon.GetSlotID();
            slot_owner      = slots_icon.GetSlotParent();
        }
        PlayerBase p = PlayerBase.Cast( GetGame().GetPlayer() );
        InventoryItem receiver_entity = InventoryItem.Cast( p.GetHumanInventory().GetEntityInHands() );
        InventoryItem w_entity = InventoryItem.Cast( w_ipw.GetItem() );
        if( !w_entity )
        {
            return;
        }
        if( receiver_entity )
        {
            if( receiver_item )
            {
                ItemBase receiver_itemIB    = ItemBase.Cast( receiver_item );
                ItemBase itemIB             = ItemBase.Cast( receiver_item );
                if( receiver_itemIB && itemIB && receiver_itemIB.CanBeCombined( itemIB ) )
                {
                    ItemManager.GetInstance().HideDropzones();
                    if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                    ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
                }
                else
                {
                    PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
                    Magazine mag = Magazine.Cast(receiver_item);
                    Weapon_Base wpn = Weapon_Base.Cast(receiver_item.GetHierarchyParent());
                    if( wpn && mag )
                    {
                        if( player.GetWeaponManager().CanSwapMagazine( wpn,  Magazine.Cast(w_entity) ) )
{
                            ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                            if( w_entity.GetHierarchyRootPlayer() == player )
{
                                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                            }
                            else
{
                                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                            }
                        }
                        else
{
                            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                            ItemManager.GetInstance().ShowSourceDropzone( w_entity );
                        }
                    }
                    else
                    {
                        if( GameInventory.CanSwapEntitiesEx( receiver_item, w_entity ) )
{
                            ItemManager.GetInstance().HideDropzones();
                            if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
{
                                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                            }
                            else
{
                                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                            }
                            ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                        }
                        else if( receiver_itemIB.GetInventory().CanAddAttachment( w_entity ) )
{
                            ItemManager.GetInstance().HideDropzones();
                            if( receiver_itemIB.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
{
                                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                            }
                            else
{
                                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                            }
                            ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                        }
                    }
                }
            }
            else if( slot_owner && slot_owner.GetInventory().CanAddAttachment( w_entity ) )
            {
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            }
            else if( receiver_entity.GetInventory().CanAddAttachment( w_entity ) )
            {
                ItemManager.GetInstance().HideDropzones();
                if( receiver_entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                {
                    ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                }
                else
                {
                    ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                }
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            }
            else
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( w_entity );
            }
        }
        else
        {
            /*if( m_HandsIcon )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
            }
            else
            {*/
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( w_entity );
            //}
        }
    }
References ItemBase::CanBeCombined(), ColorManager::COMBINE_COLOR, ItemManager::GetCenterDropzone(), SlotsIcon::GetEntity(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Entity, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
Referenced by DraggingOverHeader2().
DraggingOverHeader2()
void HandsContainer::DraggingOverHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 210 of file handscontainer.c.
    {
        DraggingOverHeader(w, x, y, receiver );
    }
References DraggingOverHeader(), x, and y.
DropReceived()
void HandsContainer::DropReceived (Widget w, int x, int y, CargoContainer cargo) inline private
Definition at line 1014 of file handscontainer.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        int idx = 0;
        int c_x, c_y;
        EntityAI target_entity;
        CargoBase target_cargo;
        if( cargo == m_CargoGrid )
        {
            target_entity   = m_Entity;
            target_cargo    = m_Entity.GetInventory().GetCargo();
            #ifdef PLATFORM_CONSOLE
            if( m_CargoGrid.HasItem( item ) )
            {
                return;
            }
            #endif
        }
        else
        {
            target_entity   = m_AttachmentCargos.GetKeyByValue( cargo );
            if( target_entity )
            {
                target_cargo    = target_entity.GetInventory().GetCargo();
                #ifdef PLATFORM_CONSOLE
                if( cargo.HasItem( item ) )
                {
                    return;
                }
                #endif
            }
            else
                return;
        }
        if( target_cargo && target_entity )
        {
            c_x = target_cargo.GetHeight();
            c_y = target_cargo.GetWidth();
        }
        else
            return;
        InventoryLocation dst = new InventoryLocation;
        #ifdef PLATFORM_CONSOLE
        x = 0;
        y = target_cargo.GetItemCount();
        target_entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.CARGO, dst );
        #else
        dst.SetCargoAuto(target_cargo, item, x, y, item.GetInventory().GetFlipCargo());
        #endif
        InventoryLocation src = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation(src);
        if(src.CompareLocationOnly(dst) && src.GetFlip() == dst.GetFlip())
            return;
        #ifdef PLATFORM_CONSOLE
        if(dst.IsValid() && target_entity.GetInventory().LocationCanAddEntity(dst))
        #else
        if( c_x > x && c_y > y && target_entity.GetInventory().LocationCanAddEntity(dst))
        #endif
        {
            SplitItemUtils.TakeOrSplitToInventoryLocation( player, dst );
            Icon icon = cargo.GetIcon( item );
            if( icon )
            {
                if( w && w.FindAnyWidget("Selected") )
                    w.FindAnyWidget("Selected").SetColor( ColorManager.BASE_COLOR );
                icon.Refresh();
                Refresh();
            }
        }
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
    }
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_AttachmentCargos, m_CargoGrid, m_Entity, Icon::Refresh(), Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
ElectricityIcon()
void HandsContainer::ElectricityIcon () inline private
Definition at line 1524 of file handscontainer.c.
    {
        EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
        if( item_in_hands && item_in_hands.GetCompEM() )
        {
            if( GetRootWidget().FindAnyWidget( "electricity" ) )
            {
                bool show_electricity_icon = item_in_hands.GetCompEM().HasElectricityIcon();
                GetRootWidget().FindAnyWidget( "electricity" ).Show( show_electricity_icon );
            }
            if( GetRootWidget().FindAnyWidget( "electricity_can_work" ) )
            {
                bool show_electricity_can_work_icon = item_in_hands.GetCompEM().CanWork() && !item_in_hands.IsRuined();
                GetRootWidget().FindAnyWidget( "electricity_can_work" ).Show( show_electricity_can_work_icon );
            }
        }
        else
        {
            GetRootWidget().FindAnyWidget( "electricity" ).Show( false );
        }
    }
References FindAnyWidget(), GetGame(), and CGame::GetPlayer().
Referenced by UpdateInterval().
EquipItem()
override bool HandsContainer::EquipItem () inline private
Definition at line 284 of file handscontainer.c.
    {
        if (m_ActiveIndex == 0)
        {
            ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
            if ( item_in_hands )
            {
                if ( GetGame().GetPlayer().GetHumanInventory().CanRemoveEntityInHands() && !GetGame().GetPlayer().GetInventory().HasInventoryReservation(item_in_hands, null)  )
                {
                    if ( GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, item_in_hands ) )
                    {
                        m_MainWidget.FindAnyWidget("Selected").Show( false );
                        m_MainWidget.FindAnyWidget("hands_preview_root").SetAlpha( 0.7 );
                        return true;
                    }
                }
            }
        }
        else if( GetFocusedContainer() )
        {
            return GetFocusedContainer().EquipItem();
        }
        return false;
    }
References GetGame(), GetPlayer(), and HasInventoryReservation().
GetCombinationFlags()
int HandsContainer::GetCombinationFlags (EntityAI entity1, EntityAI entity2) inline private
Definition at line 828 of file handscontainer.c.
    {
        int flags = 0;
        PlayerBase m_player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI entity_in_hands = m_player.GetHumanInventory().GetEntityInHands();
        if ( !entity1 || !entity2 ) return flags;
        Magazine swapmag1;
        Magazine swapmag2;
        bool skipSwap = false;
        if( Class.CastTo(swapmag1, entity1) && Class.CastTo(swapmag2, entity2) )
        {
            Weapon_Base parentWpn;
            if( Class.CastTo(parentWpn, swapmag1.GetHierarchyParent())  )
            {
                skipSwap = true;
                if( m_player.GetWeaponManager().CanSwapMagazine(parentWpn,swapmag2) )
                    flags = flags | InventoryCombinationFlags.SWAP;
            }
            if( Class.CastTo(parentWpn, swapmag2.GetHierarchyParent())  )
            {
                skipSwap = true;
                if( m_player.GetWeaponManager().CanSwapMagazine(parentWpn,swapmag1) )
                    flags = flags | InventoryCombinationFlags.SWAP;
            }
        }
        if ( !skipSwap )
        {
            if ( entity1 == m_player.GetHumanInventory().GetEntityInHands() ) flags = flags | InventoryCombinationFlags.TAKE_TO_HANDS;
            else if ( GameInventory.CanSwapEntitiesEx( entity1, entity2 ) )
            {
                if ( !entity1.IsInherited( ZombieBase ) && !entity1.IsInherited( Car ) )
                {
                    flags = flags | InventoryCombinationFlags.SWAP;
                }
            }
        }
        if ( entity1.IsInherited( ItemBase) && entity2.IsInherited( ItemBase ) )
        {
            ItemBase ent1 = ItemBase.Cast( entity1 );
            if ( ent1.CanBeCombined( ItemBase.Cast( entity2 ) ) ) flags = flags | InventoryCombinationFlags.COMBINE_QUANTITY2;
        }
        else if ( entity1.GetInventory().CanAddAttachment( entity2 ) )
        {
            if ( !entity1.IsInherited( ZombieBase ) && !entity1.IsInherited( Car ) && !entity2.IsInherited( ZombieBase ) && !entity2.IsInherited( Car ) )
            {
                flags = flags | InventoryCombinationFlags.ADD_AS_ATTACHMENT;
            }
        }
        if ( entity1.GetInventory().CanAddEntityInCargo( entity2, entity2.GetInventory().GetFlipCargo() ) ) flags = flags | InventoryCombinationFlags.ADD_AS_CARGO;
        if( entity1 == m_player.GetHumanInventory().GetEntityInHands() || entity2 == m_player.GetHumanInventory().GetEntityInHands() )
        {
            ActionManagerClient amc;
            Class.CastTo(amc, m_player.GetActionManager());
            if( entity1 == m_player.GetHumanInventory().GetEntityInHands() )
            {
                if( amc.CanSetActionFromInventory( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.SET_ACTION;
                }
            }
            else
            {
                if( amc.CanSetActionFromInventory( ItemBase.Cast( entity2 ), ItemBase.Cast( entity1 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.SET_ACTION;
                }
            }
        }
        if( GetRecipeCount( true, entity1, entity2 ) > 0 )
        {
            flags = flags | InventoryCombinationFlags.RECIPE_ANYWHERE;
        }
        return flags;
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, ItemBase::CanBeCombined(), ActionManagerClient::CanSetActionFromInventory(), Class::CastTo(), InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), GetPlayer(), GetRecipeCount(), m_player, InventoryCombinationFlags::RECIPE_ANYWHERE, InventoryCombinationFlags::SET_ACTION, InventoryCombinationFlags::SWAP, and InventoryCombinationFlags::TAKE_TO_HANDS.
GetHeader()
override Header HandsContainer::GetHeader () inline private
Definition at line 62 of file handscontainer.c.
    {
        return m_CollapsibleHeader;
    }
References m_CollapsibleHeader.
Referenced by HandsPreview::CreateNewIcon().
GetItemPreviewItem()
EntityAI HandsContainer::GetItemPreviewItem (Widget w) inline private
Definition at line 474 of file handscontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw )
        {
            return null;
        }
        return ipw.GetItem();
    }
References ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by DraggingOverGrid(), DropReceived(), and TakeAsAttachment().
GetRecipeCount()
int HandsContainer::GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 914 of file handscontainer.c.
    {
        PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast( GetPlugin( PluginRecipesManager ) );
        return plugin_recipes_manager.GetValidRecipes( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ), null, PlayerBase.Cast( GetGame().GetPlayer() ) );
    }
References GetGame(), GetPlayer(), and GetPlugin().
Referenced by GetCombinationFlags().
HideCargo()
void HandsContainer::HideCargo () inline private
Definition at line 1573 of file handscontainer.c.
    {
        if( m_CargoGrid )
        {
            m_CargoGrid.OnHide();
            RecomputeOpenedContainers();
        }
    }
References m_CargoGrid.
Referenced by ShowAtt(), and UpdateInterval().
Insert()
override void HandsContainer::Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 182 of file handscontainer.c.
    {
        super.Insert( container, pos, immedUpdate );
    }
Referenced by AttachmentAdded(), and ShowAtt().
InspectItem()
override bool HandsContainer::InspectItem () inline private
Definition at line 422 of file handscontainer.c.
    {
        if(m_ActiveIndex == 0)
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
            if( item_in_hands )
            {
                InspectItem( item_in_hands );
                return true;
            }
        }
        else if( GetFocusedContainer() )
        {
            return GetFocusedContainer().InspectItem();
        }
        return false;
    }
References GetGame(), GetPlayer(), and InspectItem().
Referenced by InspectItem(), and MouseClick2().
IsEmpty()
override bool HandsContainer::IsEmpty () inline private
Definition at line 392 of file handscontainer.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        return player.GetHumanInventory().GetEntityInHands() == null;
    }
References GetGame(), and GetPlayer().
Referenced by IsItemActive(), and IsItemWithQuantityActive().
IsItemActive()
override bool HandsContainer::IsItemActive () inline private
Definition at line 370 of file handscontainer.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        ItemBase item = ItemBase.Cast( player.GetHumanInventory().GetEntityInHands() );
        if( item == null )
        {
            return false;
        }
        return !IsEmpty() && ( !QuantityConversions.HasItemQuantity( item )  || ( QuantityConversions.HasItemQuantity( item ) && !item.CanBeSplit() ) );
    }
References GetGame(), GetPlayer(), QuantityConversions::HasItemQuantity(), and IsEmpty().
IsItemWithQuantityActive()
override bool HandsContainer::IsItemWithQuantityActive () inline private
Definition at line 381 of file handscontainer.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        ItemBase item = ItemBase.Cast( player.GetHumanInventory().GetEntityInHands() );
        if( item == null )
        {
            return false;
        }
        return !IsEmpty() && QuantityConversions.HasItemQuantity( item ) && item.CanBeSplit();
    }
References GetGame(), GetPlayer(), QuantityConversions::HasItemQuantity(), and IsEmpty().
IsLastIndex()
override bool HandsContainer::IsLastIndex () inline private
Definition at line 67 of file handscontainer.c.
    {
        return m_ActiveIndex == m_OpenedContainers.Count() - 1;
    }
MouseClick2()
void HandsContainer::MouseClick2 (Widget w, int x, int y, int button) inline private
Definition at line 187 of file handscontainer.c.
    {
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget item_preview = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( !item_preview )
        {
            return;
        }
        EntityAI item = item_preview.GetItem();
        InventoryItem itemAtPos = InventoryItem.Cast( item );
        if( item )
        {
            if ( button == MouseState.MIDDLE )
            {
                InspectItem( itemAtPos );
            }
        }
    }
References ItemPreviewWidget::GetItem(), InspectItem(), name, and string::Replace().
OnDropReceivedFromHeader()
override void HandsContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 823 of file handscontainer.c.
    {
        TakeAsAttachment( w, receiver );
    }
References TakeAsAttachment().
OnDropReceivedFromHeader2()
void HandsContainer::OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 657 of file handscontainer.c.
    {
        TakeAsAttachment( w, receiver );
    }
References TakeAsAttachment().
OnPerformCombination()
void HandsContainer::OnPerformCombination (int combinationFlags) inline private
Definition at line 662 of file handscontainer.c.
    {
        PlayerBase m_player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( m_am_entity1 == null || m_am_entity2 == null ) return;
        if ( combinationFlags == InventoryCombinationFlags.NONE ) return;
        if ( combinationFlags & InventoryCombinationFlags.LOAD_CHAMBER )
        {
            Magazine mag;
            if ( Class.CastTo(mag,  m_am_entity2 ) )
            {
                m_player.GetWeaponManager().LoadBullet( mag );
                return;
            }
        }
        if ( combinationFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT )
        {
            if( m_Atts )
            {
                m_Body.RemoveItem( m_Atts.GetWrapper() );
                delete m_Atts;
            }
            if( m_am_entity2.GetSlotsCountCorrect() > 0 )
            {
                m_Atts = new Attachments( this, m_am_entity2 );
                m_Atts.InitAttachmentGrid( 1 );
            }
            Refresh();
            m_Parent.Refresh();
            Weapon_Base wpn1;
            Magazine mag1;
            if ( Class.CastTo(wpn1,  m_am_entity1 ) && Class.CastTo(mag1,  m_am_entity2 ) )
            {
                if( m_player.GetWeaponManager().CanAttachMagazine(wpn1, mag1) )
                {
                    m_player.GetWeaponManager().AttachMagazine(mag1);
                    return;
                }
            }
            SplitItemUtils.TakeOrSplitToInventory(m_player, m_am_entity1, m_am_entity2);
            //m_player.PredictiveTakeEntityToTargetAttachment( m_am_entity1, m_am_entity2 );
        }
        if ( combinationFlags & InventoryCombinationFlags.ADD_AS_CARGO )
        {
            m_player.PredictiveTakeEntityToTargetCargo( m_am_entity1, m_am_entity2 );
        }
        if ( combinationFlags & InventoryCombinationFlags.SWAP )
        {
            Magazine swapmag1;
            Magazine swapmag2;
            if (Class.CastTo(swapmag1,  m_am_entity1 ) && Class.CastTo(swapmag2,  m_am_entity2 ) )
            {
                if( m_player.GetWeaponManager().CanSwapMagazine( Weapon_Base.Cast( swapmag1.GetParent() ), Magazine.Cast( swapmag2 ) ) )
                {
                    m_player.GetWeaponManager().SwapMagazine(swapmag2);
                    return;
                }
                if( m_player.GetWeaponManager().CanSwapMagazine(Weapon_Base.Cast( swapmag2.GetParent() ), Magazine.Cast( swapmag1 )) )
                {
                    m_player.GetWeaponManager().SwapMagazine(swapmag1);
                    return;
                }
            }
            if ( !m_player.PredictiveSwapEntities( m_am_entity1, m_am_entity2 ) && m_player.GetHumanInventory().CanAddEntityInHands( m_am_entity1 ) )
            {
                m_player.PredictiveTakeEntityToHands( m_am_entity1 );
            }
        }
        if ( combinationFlags & InventoryCombinationFlags.TAKE_TO_HANDS )
        {
            if ( m_Atts )
            {
                m_Body.RemoveItem( m_Atts.GetWrapper() );
                delete m_Atts;
            }
            if ( m_am_entity2.GetSlotsCountCorrect() > 0 )
            {
                m_Atts = new Attachments( this, m_am_entity2 );
                m_Atts.InitAttachmentGrid( 1 );
            }
            Refresh();
            m_Parent.Refresh();
            if ( m_player.GetHumanInventory().CanAddEntityInHands( m_am_entity2 ) )
            {
                m_player.PredictiveTakeEntityToHands( m_am_entity2 );
            }
        }
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, Class::CastTo(), GetGame(), GetPlayer(), Attachments::GetWrapper(), Attachments::InitAttachmentGrid(), InventoryCombinationFlags::LOAD_CHAMBER, m_Atts, m_Parent, m_player, InventoryCombinationFlags::NONE, Refresh(), InventoryCombinationFlags::SWAP, InventoryCombinationFlags::TAKE_TO_HANDS, and SplitItemUtils::TakeOrSplitToInventory().
OnSelectButton()
override bool HandsContainer::OnSelectButton () inline private
Definition at line 441 of file handscontainer.c.
    {
        if(m_ActiveIndex == 0)
        {
            if( ItemManager.GetInstance().IsMicromanagmentMode() )
            {
                EntityAI selectedItem = ItemManager.GetInstance().GetSelectedItem();
                if( selectedItem == GetFocusedItem() )
                {
                    Inventory.GetInstance().DisableMicromanagement();
                    return true;
                }
                else
                {
                    return Select();
                }
            }
            else
            {
                Inventory.GetInstance().EnableMicromanagement();
                return true;
            }
        }
        else
        {
            if( GetFocusedContainer() )
            {
                return GetFocusedContainer().OnSelectButton();
            }
        }
        return false;
    }
References Container::GetFocusedItem(), ItemManager::GetInstance(), ItemManager::GetSelectedItem(), Inventory(), ItemManager::IsMicromanagmentMode(), and Container::Select().
OnShow()
override void HandsContainer::OnShow () inline private
Definition at line 1449 of file handscontainer.c.
    {
        super.OnShow();
        for ( int i = 0; i < m_Body.Count(); i++ )
        {
            m_Body.Get( i ).OnShow();
        }
    }
Referenced by HandsArea::OnShow().
Refresh()
override void HandsContainer::Refresh () inline private
Definition at line 364 of file handscontainer.c.
    {
        super.Refresh();
        SetActive( m_IsActive );
    }
References m_IsActive, and SetActive().
Referenced by DestroyAtt(), DestroyCargo(), DropReceived(), OnPerformCombination(), RefreshHands(), and ShowAtt().
RefreshHands()
void HandsContainer::RefreshHands () inline private
Definition at line 1314 of file handscontainer.c.
    {
        for (int i = 0; i < m_Body.Count(); i++)
        {
            m_Body.Get( i ).OnShow();
        }
        Refresh();
        m_Parent.Refresh();
    }
References m_Parent, and Refresh().
RemoveItem()
void HandsContainer::RemoveItem () inline private
Definition at line 920 of file handscontainer.c.
    {
        m_Entity = null;
        m_CollapsibleHeader.ShowCollapseButtons( false, true );
    }
References m_CollapsibleHeader, m_Entity, and HandsHeader::ShowCollapseButtons().
ResetContainer()
void HandsContainer::ResetContainer () inline private
Definition at line 56 of file handscontainer.c.
    {
        m_Body.Clear();
        m_Body.Insert( m_HandsPreview );
    }
References m_HandsPreview.
Referenced by ShowAtt().
ScrollToActiveContainer()
void HandsContainer::ScrollToActiveContainer (Container active_container) inline private
Definition at line 160 of file handscontainer.c.
    {
        if( !active_container )
            return;
        float x, y, y_s;
        m_ScrollWidget.GetScreenPos( x, y );
        m_ScrollWidget.GetScreenSize( x, y_s );
        float amount;
        float next_pos  = active_container.GetFocusedContainerYScreenPos( true ) + active_container.GetFocusedContainerHeight( true );
        if( next_pos > ( y + y_s ) )
        {
            amount  = y + active_container.GetFocusedContainerYScreenPos( true );
            m_ScrollWidget.VScrollToPos( m_ScrollWidget.GetVScrollPos() + active_container.GetFocusedContainerHeight( true ) + 2 );
        }
        else if( active_container.GetFocusedContainerYScreenPos( true ) < y )
        {
            amount = active_container.GetFocusedContainerYScreenPos( true ) - y;
            m_ScrollWidget.VScrollToPos( m_ScrollWidget.GetVScrollPos() + amount - 2 );
        }
    }
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), m_ScrollWidget, x, and y.
Referenced by SetFocusToIndex().
SetActive()
override void HandsContainer::SetActive (bool active) inline private
Definition at line 309 of file handscontainer.c.
    {
        super.SetActive(active);
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
        if( item_in_hands )
        {
            if( m_MainWidget.FindAnyWidget( "Selected" ) )
            {
                m_MainWidget.FindAnyWidget( "Selected" ).Show( active );
            }
            if( active )
            {
                float x, y;
                GetMainWidget().GetScreenPos( x, y );
                PrepareOwnedTooltip( item_in_hands, -1, y );
            }
        }
        else
        {
            if( active )
                m_MainWidget.FindAnyWidget( "hands_preview_root" ).SetAlpha( 0.85 );
            else
                m_MainWidget.FindAnyWidget( "hands_preview_root" ).SetAlpha( 0.7 );
        }
    }
References GetGame(), GetPlayer(), x, and y.
SetFocusToIndex()
void HandsContainer::SetFocusToIndex () inline private
Definition at line 72 of file handscontainer.c.
    {
        int index = m_ActiveIndex - 1;
        int attachment_start_index = -1;
        int cargo_start_index = -1;
        int attachment_end_index = -1;
        int cargo_end_index = -1;
        if ( m_Atts || m_AttachmentAttachments.Count() > 0 )
        {
            attachment_start_index = 0;
            if ( m_Atts )
                attachment_end_index++;
            attachment_end_index += m_AttachmentAttachments.Count();
        }
        if ( m_CargoGrid || m_AttachmentCargos.Count() > 0 )
        {
            cargo_start_index = attachment_end_index + 1;
            if ( m_CargoGrid )
                cargo_end_index++;
            cargo_end_index += cargo_start_index + m_AttachmentCargos.Count();
        }
        if ( m_ActiveIndex > m_OpenedContainers.Count() )
        {
            m_ActiveIndex = m_OpenedContainers.Count();
        }
        if ( index == -1 )
        {
            #ifdef PLATFORM_CONSOLE
            if ( m_MainWidget.FindAnyWidget("Selected") )
                m_MainWidget.FindAnyWidget("Selected").Show( true );
            #endif
            m_ScrollWidget.VScrollToPos01( 0 );
        }
        else
        {
            if( index.InRange( 0, attachment_end_index ) )
            {
                if( m_Atts )
                {
                    if( index == 0 )
                    {
                        m_Atts.SetDefaultFocus();
                        SetFocusedContainer( m_Atts.GetWrapper() );
                    }
                    else
                    {
                        m_AttachmentAttachments.GetElement( index - 1 ).SetDefaultFocus();
                        SetFocusedContainer( m_AttachmentAttachments.GetElement( index - 1 ).GetWrapper() );
                    }
                }
                else
                {
                    m_AttachmentAttachments.GetElement( index ).SetDefaultFocus();
                    SetFocusedContainer( m_AttachmentAttachments.GetElement( index ).GetWrapper() );
                }
            }
            else if( index.InRange( cargo_start_index, cargo_end_index ) )
            {
                if( m_CargoGrid )
                {
                    if( index == cargo_start_index )
                    {
                        m_CargoGrid.SetDefaultFocus();
                        SetFocusedContainer( m_CargoGrid );
                    }
                    else
                    {
                        m_AttachmentCargos.GetElement( index - 1 - cargo_start_index ).SetDefaultFocus();
                        SetFocusedContainer( m_AttachmentCargos.GetElement( index - 1 - cargo_start_index ) );
                    }
                }
                else
                {
                    m_AttachmentCargos.GetElement( index - cargo_start_index ).SetDefaultFocus();
                    SetFocusedContainer( m_AttachmentCargos.GetElement( index - cargo_start_index ) );
                }
            }
            if( m_MainWidget.FindAnyWidget("Selected") )
                m_MainWidget.FindAnyWidget("Selected").Show( false );
            ScrollToActiveContainer( GetFocusedContainer() );
        }
    }
References Attachments::GetWrapper(), m_AttachmentAttachments, m_AttachmentCargos, m_Atts, m_CargoGrid, m_ScrollWidget, ScrollToActiveContainer(), and Attachments::SetDefaultFocus().
SetLastActive()
override void HandsContainer::SetLastActive () inline private
Definition at line 338 of file handscontainer.c.
    {
        super.SetLastActive();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
        if( item_in_hands )
        {
            if ( m_ActiveIndex == 0)
            {
                if( m_MainWidget.FindAnyWidget( "Selected" ) )
                {
                    m_MainWidget.FindAnyWidget( "Selected" ).Show( true );
                }
                float x, y;
                GetMainWidget().GetScreenPos( x, y );
                PrepareOwnedTooltip( item_in_hands, x, y );
            }
        }
        else
        {
            m_MainWidget.FindAnyWidget( "hands_preview_root" ).SetAlpha( 0.85 );
        }
    }
References GetGame(), GetPlayer(), x, and y.
SetLayoutName()
override void HandsContainer::SetLayoutName () inline private
Definition at line 1444 of file handscontainer.c.
    {
        m_LayoutName = WidgetLayoutName.ClosableContainer;
    }
References WidgetLayoutName::ClosableContainer.
ShowActionMenuCombine()
void HandsContainer::ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags) inline private
Definition at line 764 of file handscontainer.c.
    {
        if ( entity1 && entity2 ) PrintString( "Showing action menu for " + entity1.GetDisplayName() + " and " + entity2.GetDisplayName() );
        ContextMenu cmenu = GetGame().GetUIManager().GetMenu().GetContextMenu();
        m_am_entity1 = entity1;
        m_am_entity2 = entity2;
        cmenu.Hide();
        cmenu.Clear();
        if( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY2 )
        {
            ItemBase entity = ItemBase.Cast( entity1 );
            entity.CombineItemsClient( ItemBase.Cast( entity2 ) );
            return;
        }
        if ( entity1 == null || entity2 == null ) return;
        if ( combinationFlags == InventoryCombinationFlags.NONE ) return;
        if ( combinationFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT )
        {
            cmenu.Add( "#inv_context_add_as_attachment", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.ADD_AS_ATTACHMENT ) );
        }
        if ( combinationFlags & InventoryCombinationFlags.LOAD_CHAMBER )
        {
            cmenu.Add( "#inv_context_load_chamber", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.LOAD_CHAMBER ) );
        }
        if ( combinationFlags & InventoryCombinationFlags.ADD_AS_CARGO )
        {
            cmenu.Add( "#inv_context_add_as_cargo", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.ADD_AS_CARGO ) );
        }
        if ( combinationFlags & InventoryCombinationFlags.SWAP )
        {
            cmenu.Add( "#inv_context_swap", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.SWAP ) );
        }
        if ( combinationFlags & InventoryCombinationFlags.TAKE_TO_HANDS )
        {
            cmenu.Add( "#inv_context_take_to_hands", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.TAKE_TO_HANDS ) );
        }
        if ( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY )
        {
            cmenu.Add( "#inv_context_combine", this, "OnPerformCombination", new Param1<int>( InventoryCombinationFlags.COMBINE_QUANTITY ) );
        }
        int m_am_pos_x,  m_am_pos_y;
        GetMousePos( m_am_pos_x, m_am_pos_y );
        m_am_pos_x -= 5;
        m_am_pos_y -= 5;
        cmenu.Show( m_am_pos_x, m_am_pos_y );
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), UIManager::GetMenu(), GetMousePos(), CGame::GetUIManager(), InventoryCombinationFlags::LOAD_CHAMBER, InventoryCombinationFlags::NONE, PrintString(), InventoryCombinationFlags::SWAP, and InventoryCombinationFlags::TAKE_TO_HANDS.
ShowAtt()
void HandsContainer::ShowAtt (EntityAI entity) inline private
Definition at line 1256 of file handscontainer.c.
    {
        ResetContainer();
        m_StaticCargoCount = 0;
        m_Entity = entity;
        m_ActiveIndex = 0;
        if( entity.GetSlotsCountCorrect() > 0 )
        {
            m_Atts = new Attachments( this, entity );
            m_Atts.InitAttachmentGrid( 1 );
            m_AttachmentSlotsSorted = m_Atts.GetSlotsSorted();
            m_StaticAttCount = m_Atts.GetAttachmentHeight();
            m_Entity.GetOnItemAttached().Insert( AttachmentAdded );
            m_Entity.GetOnItemDetached().Insert( AttachmentRemoved );
        }
        else
        {
            m_StaticAttCount = 0;
        }
        if( entity.GetInventory().GetCargo() )
        {
            m_CargoGrid = new CargoContainer( this, false );
            m_CargoGrid.SetEntity( entity );
            m_CargoGrid.GetRootWidget().SetSort( 1 );
            Insert( m_CargoGrid );
            m_StaticCargoCount++;
        }
        if (m_AttachmentSlotsSorted)
        {
            foreach( int slot_id : m_AttachmentSlotsSorted )
            {
                EntityAI item = m_Entity.GetInventory().FindAttachment( slot_id );
                if( item )
                    AttachmentAdded( item, InventorySlots.GetSlotName( slot_id ), m_Entity );
            }
        }
        if (m_CargoGrid)
        {
            bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
            if (m_CargoGrid.IsVisible() && hideCargo)
            {
                HideCargo();
            }
            else if (!m_CargoGrid.IsVisible() && !hideCargo)
            {
                ShowCargo();
            }
        }
        m_CollapsibleHeader.ShowCollapseButtons( m_Atts || m_CargoGrid, m_Atts || m_CargoGrid );
        RecomputeOpenedContainers();
        Refresh();
        m_Parent.Refresh();
    }
References AttachmentAdded(), AttachmentRemoved(), Container::CargoContainer(), Attachments::GetAttachmentHeight(), InventorySlots::GetSlotName(), Attachments::GetSlotsSorted(), HideCargo(), Attachments::InitAttachmentGrid(), Insert(), m_AttachmentSlotsSorted, m_Atts, m_CargoGrid, m_CollapsibleHeader, m_Entity, m_Parent, m_StaticAttCount, m_StaticCargoCount, Refresh(), ResetContainer(), ShowCargo(), and HandsHeader::ShowCollapseButtons().
ShowCargo()
void HandsContainer::ShowCargo () inline private
Definition at line 1582 of file handscontainer.c.
    {
        if( m_CargoGrid )
        {
            m_CargoGrid.OnShow();
            RecomputeOpenedContainers();
        }
    }
References m_CargoGrid.
Referenced by ShowAtt(), and UpdateInterval().
SplitItem()
override bool HandsContainer::SplitItem () inline private
Definition at line 264 of file handscontainer.c.
    {
        if (m_ActiveIndex == 0)
        {
            ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
            if ( item_in_hands )
            {
                if ( item_in_hands.CanBeSplit() )
                {
                    item_in_hands.OnRightClick();
                }
            }
        }
        else if( GetFocusedContainer() )
        {
            return GetFocusedContainer().SplitItem();
        }
        return false;
    }
References GetGame(), and GetPlayer().
TakeAsAttachment()
void HandsContainer::TakeAsAttachment (Widget w, Widget receiver) inline private
Definition at line 1152 of file handscontainer.c.
    {
        EntityAI receiver_item;
        EntityAI slot_owner;
        int slot_id = -1;
        SlotsIcon slots_icon;
        receiver.GetUserData(slots_icon);
        if( slots_icon )
        {
            receiver_item   = slots_icon.GetEntity();
            slot_id         = slots_icon.GetSlotID();
            slot_owner      = slots_icon.GetSlotParent();
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        ItemBase item_base  = ItemBase.Cast( item );
        float stack_max = item_base.GetTargetQuantityMax(slot_id);
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( !item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
            return;
        EntityAI target_att_entity = m_Entity;
        Weapon_Base wpn;
        Magazine mag;
        if( Class.CastTo(wpn,  m_Entity ) && Class.CastTo(mag,  item ) )
        {
            if( player.GetWeaponManager().CanAttachMagazine( wpn, mag ) )
            {
                player.GetWeaponManager().AttachMagazine( mag );
            }
            else if(player.GetWeaponManager().CanSwapMagazine( wpn, mag ))
            {
                player.GetWeaponManager().SwapMagazine( mag );
            }
        }
        else if( receiver_item )
        {
            if( receiver_item != item )
            {
                if( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( item ) ) )
                {
                    ( ItemBase.Cast( receiver_item ) ).CombineItemsClient( ItemBase.Cast( item ) );
                }
                else if( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
                {
                    if( !receiver_item.GetInventory().CanRemoveEntity() )
                        return;
                    GetGame().GetPlayer().PredictiveSwapEntities( item, receiver_item );
                }
            }
        }
        else if( slot_owner && slot_owner.GetInventory().CanAddAttachmentEx( item, slot_id ) )
        {
            if( stack_max == 0 || stack_max >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachmentEx(slot_owner, item, slot_id);
            }
            else if( stack_max != 0 && stack_max < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( m_Entity, slot_id );
            }
        }
        else if( slot_owner && slot_owner.GetInventory().CanAddAttachment( item ) )
        {
            if( stack_max == 0 || stack_max >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachment(slot_owner, item);
            }
            else if( stack_max != 0 && stack_max < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( m_Entity, -1 );
            }
        }
        else if( m_Entity.GetInventory().CanAddAttachment( item ) )
        {
            if( stack_max == 0 || stack_max >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachment(m_Entity, item);
            }
            else if( stack_max != 0 && stack_max < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( m_Entity, -1 );
            }
        }
        else if( ( m_Entity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && ( !player.GetInventory().HasEntityInInventory( item ) || !m_Entity.GetInventory().HasEntityInCargo( item )) ) || player.GetHumanInventory().HasEntityInHands( item ) )
        {
            SplitItemUtils.TakeOrSplitToInventory( PlayerBase.Cast( GetGame().GetPlayer() ), m_Entity, item );
        }
        /*else if( !player.GetInventory().HasEntityInInventory( item ) || !m_Entity.GetInventory().HasEntityInCargo( item ) )
        {
            SplitItemUtils.TakeOrSplitToInventory( PlayerBase.Cast( GetGame().GetPlayer() ), m_Entity, item );
        }*/
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
    }
References Class::CastTo(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ItemManager::HideDropzones(), m_Entity, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
Referenced by OnDropReceivedFromHeader(), and OnDropReceivedFromHeader2().
TransferItem()
override bool HandsContainer::TransferItem () inline private
Definition at line 215 of file handscontainer.c.
    {
        if(m_ActiveIndex == 0)
        {
            EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
            if( item_in_hands && GetGame().GetPlayer().GetHumanInventory().CanRemoveEntityInHands() && !GetGame().GetPlayer().GetInventory().HasInventoryReservation(item_in_hands, null)  )
            {
                if( GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, item_in_hands ) )
                {
                    m_MainWidget.FindAnyWidget("Selected").Show( false );
                    m_MainWidget.FindAnyWidget("hands_preview_root").SetAlpha( 0.7 );
                    return true;
                }
            }
        }
        else if( GetFocusedContainer() )
        {
            return GetFocusedContainer().TransferItem();
        }
        return false;
    }
References GetGame(), CGame::GetPlayer(), GetPlayer(), and HasInventoryReservation().
TransferItemToVicinity()
override bool HandsContainer::TransferItemToVicinity () inline private
Definition at line 398 of file handscontainer.c.
    {
        if (m_ActiveIndex == 0)
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            ItemBase item_in_hands = ItemBase.Cast(player.GetHumanInventory().GetEntityInHands());
            if ( item_in_hands && player.CanDropEntity( item_in_hands ) && GetGame().GetPlayer().GetHumanInventory().CanRemoveEntityInHands() && !player.GetInventory().HasInventoryReservation(item_in_hands, null) )
            {
                if ( item_in_hands.GetTargetQuantityMax() < item_in_hands.GetQuantity() )
                    item_in_hands.SplitIntoStackMaxClient( null, -1 );
                else
                    player.PhysicalPredictiveDropItem( item_in_hands );
                m_MainWidget.FindAnyWidget("Selected").Show( false );
                m_MainWidget.FindAnyWidget("hands_preview_root").SetAlpha( 0.7 );
                return true;
            }
        }
        else if ( GetFocusedContainer() )
        {
                return GetFocusedContainer().TransferItemToVicinity();
        }
        return false;
    }
References GetGame(), and GetPlayer().
UnfocusAll()
override void HandsContainer::UnfocusAll () inline private
Definition at line 986 of file handscontainer.c.
    {
        UnfocusGrid();
    }
References UnfocusGrid().
UnfocusGrid()
override void HandsContainer::UnfocusGrid () inline private
Definition at line 956 of file handscontainer.c.
    {
        if( m_Atts )
        {
            m_Atts.UnfocusAll();
        }
        if( m_CargoGrid )
        {
            m_CargoGrid.UnfocusAll();
        }
        if( m_AttachmentCargos )
        {
            foreach( EntityAI e1, CargoContainer cargo : m_AttachmentCargos )
            {
                cargo.UnfocusAll();
            }
        }
        if( m_AttachmentCargos )
        {
            foreach( EntityAI e2, Attachments att : m_AttachmentAttachments )
            {
                att.UnfocusAll();
            }
        }
    }
References Container::CargoContainer(), m_AttachmentAttachments, m_AttachmentCargos, m_Atts, m_CargoGrid, and Attachments::UnfocusAll().
Referenced by UnfocusAll().
UpdateInterval()
override void HandsContainer::UpdateInterval () inline private
Definition at line 1408 of file handscontainer.c.
    {
        super.UpdateInterval();
        if ( m_Entity )
        {
            if (m_CargoGrid)
            {
                bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
                if (m_CargoGrid.IsVisible() && hideCargo)
                {
                    HideCargo();
                }
                else if (!m_CargoGrid.IsVisible() && !hideCargo)
                {
                    ShowCargo();
                }
                m_CargoGrid.UpdateInterval();
            }
            if ( m_Atts )
            {
                m_Atts.UpdateInterval();
            }
            for ( int i = 0; i < m_AttachmentCargos.Count(); i++ )
            {
                m_AttachmentCargos.GetElement( i ).UpdateInterval();
            }
        }
        ElectricityIcon();
        m_CollapsibleHeader.UpdateInterval();
    }
References ElectricityIcon(), HideCargo(), m_AttachmentCargos, m_Atts, m_CargoGrid, m_CollapsibleHeader, m_Entity, ShowCargo(), Attachments::UpdateInterval(), and HandsHeader::UpdateInterval().
Referenced by HandsArea::UpdateInterval().
Member Data Documentation
m_AttachmentAttachments
protected ref map<EntityAI, ref Attachments> HandsContainer::m_AttachmentAttachments private
Definition at line 12 of file handscontainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyAtt(), HandsContainer(), SetFocusToIndex(), UnfocusGrid(), and ~HandsContainer().
m_AttachmentAttachmentsContainers
protected ref map<EntityAI, AttachmentsWrapper> HandsContainer::m_AttachmentAttachmentsContainers private
Definition at line 11 of file handscontainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyAtt(), HandsContainer(), and ~HandsContainer().
m_AttachmentCargos
protected ref map<EntityAI, ref CargoContainer> HandsContainer::m_AttachmentCargos private
Definition at line 10 of file handscontainer.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), DestroyCargo(), DropReceived(), HandsContainer(), SetFocusToIndex(), UnfocusGrid(), UpdateInterval(), and ~HandsContainer().
m_AttachmentSlotsSorted
protected ref array<int> HandsContainer::m_AttachmentSlotsSorted private
Definition at line 13 of file handscontainer.c.
Referenced by AttachmentAdded(), and ShowAtt().
m_Atts
protected ref Attachments HandsContainer::m_Atts private
Definition at line 7 of file handscontainer.c.
Referenced by DestroyAtt(), OnPerformCombination(), SetFocusToIndex(), ShowAtt(), UnfocusGrid(), and UpdateInterval().
m_CargoGrid
protected ref CargoContainer HandsContainer::m_CargoGrid private
Definition at line 8 of file handscontainer.c.
Referenced by DestroyCargo(), DropReceived(), HideCargo(), SetFocusToIndex(), ShowAtt(), ShowCargo(), UnfocusGrid(), and UpdateInterval().
m_CollapsibleHeader
protected ref HandsHeader HandsContainer::m_CollapsibleHeader private
Definition at line 4 of file handscontainer.c.
Referenced by GetHeader(), HandsContainer(), RemoveItem(), ShowAtt(), and UpdateInterval().
m_HandsPreview
protected ref HandsPreview HandsContainer::m_HandsPreview private
Definition at line 5 of file handscontainer.c.
Referenced by HandsContainer(), and ResetContainer().
m_Hidden
protected bool HandsContainer::m_Hidden private
Definition at line 3 of file handscontainer.c.
Referenced by CollapseButtonOnMouseButtonDown().
m_ScrollWidget
protected ScrollWidget HandsContainer::m_ScrollWidget private
Definition at line 18 of file handscontainer.c.
Referenced by HandsContainer(), ScrollToActiveContainer(), and SetFocusToIndex().
m_StaticAttCount
protected int HandsContainer::m_StaticAttCount = 0 private
Definition at line 15 of file handscontainer.c.
Referenced by ShowAtt().
m_StaticCargoCount
protected int HandsContainer::m_StaticCargoCount = 0 private
Definition at line 16 of file handscontainer.c.
Referenced by ShowAtt().