DayzKode: HumanInputController Class Reference
HumanInputController Class Reference
Private Member Functions
proto native bool Camera3rdIsRightShoulder ()
returns true if camera is on right/ false-left shoulder
proto native bool CameraIsFreeLook ()
returns true if freelook is active
proto native bool CameraIsTracking ()
returns if camera is tracking (using IR device)
proto native bool CameraViewChanged ()
1st/3rd person camera view
proto native vector GetAimChange ()
returns per tick aim change (in radians)
proto native float GetHeadingAngle ()
returns main heading angle (in radians) -PI .. PI (this is world Y angle player is actualy pointing the camera)
proto void GetMovement (out float pSpeed, out vector pLocalDirection)
returns pSpeed 0,1..2..3 (idle, walk, run, sprint), local normalized direction vector
proto native vector GetTracking ()
returns absolute tracking change (in radians)
private void HumanInputController ()
never created by script
proto native bool IsAttackButton ()
returns true if 'UAFire' button is pressed (== true for multiple ticks). Synced.
proto native bool IsAttackButtonDown ()
returns true if 'UAFire' button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsContinuousUse ()
Long click 'UADefaultAction' (== true for multiple ticks) + not raised.
proto native bool IsContinuousUseEnd ()
is end of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsContinuousUseStart ()
is start of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsFireModeChange ()
fire mode has changed
proto native int IsGestureSlot ()
proto native bool IsHoldBreath ()
holding breath
proto native bool IsImmediateAction ()
proto native bool IsJumpClimb ()
jump/climb action was pressed
proto native bool IsMeleeEvade ()
returns pressed SHIFT (melee evade)
proto native bool IsMeleeFastAttackModifier ()
returns SHIFT down (melee fast/heavy) attack modifier
proto native int IsMeleeLREvade ()
returns 0,1,2 = none,left,right
proto native bool IsMeleeWeaponAttack ()
return weapon melee attack modifier
proto native bool IsOtherController ()
returns true, if player controls other entity (vehicle for example)
proto native bool IsQuickBarContinuousUse ()
proto native bool IsQuickBarContinuousUseEnd ()
proto native bool IsQuickBarContinuousUseStart ()
proto native bool IsQuickBarSingleUse ()
proto native int IsQuickBarSlot ()
returns 1..10 if some quickbar slot is used, 0 otherwise
proto native bool IsReloadOrMechanismContinuousUse ()
R - reloading / bolting - long press (== true for multiple ticks)
proto native bool IsReloadOrMechanismContinuousUseEnd ()
R - reloading / bolting - long press (== true for multiple ticks)
proto native bool IsReloadOrMechanismContinuousUseStart ()
R - reloading / bolting (== true for 1 tick only)
proto native bool IsReloadOrMechanismSingleUse ()
weapon handling
proto native bool IsSightChange ()
sight has been changed (in/out ironsights)
proto native bool IsSingleUse ()
single 'UADefaultAction' (== true for 1 tick only) + not raised
proto native bool IsThrowingModeChange ()
returns true if change of throwing mode has been requested
proto native bool IsUseButton ()
Deprecated; returns true if Use/Attack button is pressed (== true for multiple ticks). Synced.
proto native bool IsUseButtonDown ()
Deprecated; returns true if Use/Attack button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsUseItemButton ()
returns true if 'UADefaultAction' button is pressed (== true for multiple ticks). Synced.
proto native bool IsUseItemButtonDown ()
returns true if 'UADefaultAction' button has just been pressed (== true for 1 tick only). Synced.
proto native bool IsWalkToggled ()
returns true if Walk set to toggle
proto native bool IsWeaponRaised ()
returns true if weapon is raised
proto native bool IsZeroingDown ()
zeroing down
proto native bool IsZeroingUp ()
zeroing up
proto native bool IsZoom ()
zooming
proto native bool IsZoomIn ()
proto native bool IsZoomOut ()
proto native bool IsZoomToggle ()
zooming toggle
proto native void LimitsDisableSprint (bool pDisable)
this disables sprint
proto native bool LimitsIsSprintDisabled ()
is sprint disabled
proto native void Override3rdIsRightShoulder (bool pOverride, bool pValue)
proto native void OverrideAimChangeX (bool pOverride, float pVal)
proto native void OverrideAimChangeY (bool pOverride, float pVal)
proto native void OverrideMeleeEvade (bool pOverride, bool pValue)
proto native void OverrideMovementAngle (bool pOverride, float pVal)
proto native void OverrideMovementSpeed (bool pOverride, float pVal)
proto native void OverrideRaise (bool pOverride, bool pValue)
proto native void ResetADS ()
resets ADS mode to default
proto native void ResetFreeLookToggle ()
reset freelook toggle
proto native void ResetHoldBreath ()
reset hold breath toggle
proto native void ResetThrowingMode ()
resets Throwing mode
proto native void ResetZoomToggle ()
reset zoom toggle
proto native void SetDisabled (bool pState)
disables input controller
proto native bool WeaponADS ()
returns true if weapon ADS mode
proto native bool WeaponWasRaiseClick ()
returns true if weapon click perfomed recently (before raise specifically)
private void ~HumanInputController ()
never created by script
Detailed Description
Definition at line 14 of file human.c.
Constructor & Destructor Documentation
HumanInputController()
private void HumanInputController::HumanInputController () inline private
never created by script
Definition at line 249 of file human.c.
    {
    }
~HumanInputController()
private void HumanInputController::~HumanInputController () inline private
never created by script
Definition at line 254 of file human.c.
    {
    }
Member Function Documentation
Camera3rdIsRightShoulder()
proto native bool HumanInputController::Camera3rdIsRightShoulder () private
returns true if camera is on right/ false-left shoulder
Referenced by DayZPlayerCameraBase::DayZPlayerCamera3rdPerson(), DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcRaisedMelee(), and DayZPlayerCameraBase::OnUpdate().
CameraIsFreeLook()
proto native bool HumanInputController::CameraIsFreeLook () private
returns true if freelook is active
Referenced by ManBase::CommandHandler(), SelectCrossHair(), UpdateLRAngle(), UpdateLRAngleLookAt(), and UpdateUDAngle().
CameraIsTracking()
proto native bool HumanInputController::CameraIsTracking () private
returns if camera is tracking (using IR device)
Referenced by UpdateLRAngle(), and UpdateUDAngle().
CameraViewChanged()
proto native bool HumanInputController::CameraViewChanged () private
1st/3rd person camera view
Referenced by HandleView().
GetAimChange()
proto native vector HumanInputController::GetAimChange () private
returns per tick aim change (in radians)
Referenced by DayZPlayerCameraBase::OnUpdate(), UpdateLRAngle(), UpdateLRAngleLookAt(), and UpdateUDAngle().
GetHeadingAngle()
proto native float HumanInputController::GetHeadingAngle () private
returns main heading angle (in radians) -PI .. PI (this is world Y angle player is actualy pointing the camera)
Referenced by GetHeadingAngle().
GetMovement()
proto void HumanInputController::GetMovement (out float pSpeed, out vector pLocalDirection) private
returns pSpeed 0,1..2..3 (idle, walk, run, sprint), local normalized direction vector
GetTracking()
proto native vector HumanInputController::GetTracking () private
returns absolute tracking change (in radians)
Referenced by UpdateLRAngle(), and UpdateUDAngle().
IsAttackButton()
proto native bool HumanInputController::IsAttackButton () private
returns true if 'UAFire' button is pressed (== true for multiple ticks). Synced.
Referenced by DayZPlayerImplementThrowing::HandleThrowing(), HandleWeapons(), WeaponStartAction::OnUpdate(), and WeaponStateBase::OnUpdate().
IsAttackButtonDown()
proto native bool HumanInputController::IsAttackButtonDown () private
returns true if 'UAFire' button has just been pressed (== true for 1 tick only). Synced.
Referenced by HandleFightLogic(), and HandleWeapons().
IsContinuousUse()
proto native bool HumanInputController::IsContinuousUse () private
Long click 'UADefaultAction' (== true for multiple ticks) + not raised.
IsContinuousUseEnd()
proto native bool HumanInputController::IsContinuousUseEnd () private
is end of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
IsContinuousUseStart()
proto native bool HumanInputController::IsContinuousUseStart () private
is start of cont. 'UADefaultAction' (== true for 1 tick only) + not raised
Referenced by Update().
IsFireModeChange()
proto native bool HumanInputController::IsFireModeChange () private
fire mode has changed
Referenced by HandleWeapons().
IsGestureSlot()
proto native int HumanInputController::IsGestureSlot () private
returns 1..12 if F1 - F12 us pressed, 0 otherwise Deprecated; slots no longer used, bindable input actions instead
IsHoldBreath()
proto native bool HumanInputController::IsHoldBreath () private
holding breath
Referenced by HandleWeapons().
IsImmediateAction()
proto native bool HumanInputController::IsImmediateAction () private
is immediate action triggered - 1 tick only Middle Button + not raised !
IsJumpClimb()
proto native bool HumanInputController::IsJumpClimb () private
jump/climb action was pressed
Referenced by CommandHandler().
IsMeleeEvade()
proto native bool HumanInputController::IsMeleeEvade () private
returns pressed SHIFT (melee evade)
IsMeleeFastAttackModifier()
proto native bool HumanInputController::IsMeleeFastAttackModifier () private
returns SHIFT down (melee fast/heavy) attack modifier
Referenced by GetAttackTypeFromInputs().
IsMeleeLREvade()
proto native int HumanInputController::IsMeleeLREvade () private
returns 0,1,2 = none,left,right
Referenced by HandleFightLogic().
IsMeleeWeaponAttack()
proto native bool HumanInputController::IsMeleeWeaponAttack () private
return weapon melee attack modifier
Referenced by CommandHandler(), and HandleFightLogic().
IsOtherController()
proto native bool HumanInputController::IsOtherController () private
returns true, if player controls other entity (vehicle for example)
IsQuickBarContinuousUse()
proto native bool HumanInputController::IsQuickBarContinuousUse () private
Long click use (== true for multiple ticks) long quickbar + not raised !
IsQuickBarContinuousUseEnd()
proto native bool HumanInputController::IsQuickBarContinuousUseEnd () private
is end of cont use (== true for 1 tick only) long quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarContinuousUseStart()
proto native bool HumanInputController::IsQuickBarContinuousUseStart () private
is start of cont use (== true for 1 tick only) long quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarSingleUse()
proto native bool HumanInputController::IsQuickBarSingleUse () private
single use (== true for 1 tick only) quickbar + not raised !
Referenced by ManBase::CommandHandler().
IsQuickBarSlot()
proto native int HumanInputController::IsQuickBarSlot () private
returns 1..10 if some quickbar slot is used, 0 otherwise
Referenced by CancelContinuousUse(), and ManBase::CommandHandler().
IsReloadOrMechanismContinuousUse()
proto native bool HumanInputController::IsReloadOrMechanismContinuousUse () private
R - reloading / bolting - long press (== true for multiple ticks)
Referenced by WeaponStartAction::OnUpdate().
IsReloadOrMechanismContinuousUseEnd()
proto native bool HumanInputController::IsReloadOrMechanismContinuousUseEnd () private
R - reloading / bolting - long press (== true for multiple ticks)
IsReloadOrMechanismContinuousUseStart()
proto native bool HumanInputController::IsReloadOrMechanismContinuousUseStart () private
R - reloading / bolting (== true for 1 tick only)
IsReloadOrMechanismSingleUse()
proto native bool HumanInputController::IsReloadOrMechanismSingleUse () private
weapon handling
R - reloading / bolting (== true for 1 tick only)
IsSightChange()
proto native bool HumanInputController::IsSightChange () private
sight has been changed (in/out ironsights)
IsSingleUse()
proto native bool HumanInputController::IsSingleUse () private
single 'UADefaultAction' (== true for 1 tick only) + not raised
Referenced by Update().
IsThrowingModeChange()
proto native bool HumanInputController::IsThrowingModeChange () private
returns true if change of throwing mode has been requested
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
IsUseButton()
proto native bool HumanInputController::IsUseButton () private
Deprecated; returns true if Use/Attack button is pressed (== true for multiple ticks). Synced.
Note
Returns state of both 'UADefaultAction' and 'UAFire' input actions. Those are now separated in the methods below.
IsUseButtonDown()
proto native bool HumanInputController::IsUseButtonDown () private
Deprecated; returns true if Use/Attack button has just been pressed (== true for 1 tick only). Synced.
Note
Returns state of both 'UADefaultAction' and 'UAFire' input actions. Those are now separated in the methods below.
IsUseItemButton()
proto native bool HumanInputController::IsUseItemButton () private
returns true if 'UADefaultAction' button is pressed (== true for multiple ticks). Synced.
IsUseItemButtonDown()
proto native bool HumanInputController::IsUseItemButtonDown () private
returns true if 'UADefaultAction' button has just been pressed (== true for 1 tick only). Synced.
IsWalkToggled()
proto native bool HumanInputController::IsWalkToggled () private
returns true if Walk set to toggle
IsWeaponRaised()
proto native bool HumanInputController::IsWeaponRaised () private
returns true if weapon is raised
Referenced by DayZPlayerImplementThrowing::CanChangeThrowingStance(), DayZPlayerImplementThrowing::CanContinueThrowing(), CanPlayEmote(), HandleADS(), HandleFightLogic(), and Update().
IsZeroingDown()
proto native bool HumanInputController::IsZeroingDown () private
zeroing down
Referenced by HandleWeapons().
IsZeroingUp()
proto native bool HumanInputController::IsZeroingUp () private
zeroing up
Referenced by HandleWeapons().
IsZoom()
proto native bool HumanInputController::IsZoom () private
zooming
IsZoomIn()
proto native bool HumanInputController::IsZoomIn () private
IsZoomOut()
proto native bool HumanInputController::IsZoomOut () private
IsZoomToggle()
proto native bool HumanInputController::IsZoomToggle () private
zooming toggle
Referenced by HandleView().
LimitsDisableSprint()
proto native void HumanInputController::LimitsDisableSprint (bool pDisable) private
this disables sprint
Referenced by ManBase::CommandHandler(), and MissionBase::PlayerControlEnable().
LimitsIsSprintDisabled()
proto native bool HumanInputController::LimitsIsSprintDisabled () private
is sprint disabled
Override3rdIsRightShoulder()
proto native void HumanInputController::Override3rdIsRightShoulder (bool pOverride, bool pValue) private
Referenced by DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcRaisedMelee(), and DayZPlayerCamera3rdPersonErcRaised::~DayZPlayerCamera3rdPersonErcRaisedMelee().
OverrideAimChangeX()
proto native void HumanInputController::OverrideAimChangeX (bool pOverride, float pVal) private
OverrideAimChangeY()
proto native void HumanInputController::OverrideAimChangeY (bool pOverride, float pVal) private
OverrideMeleeEvade()
proto native void HumanInputController::OverrideMeleeEvade (bool pOverride, bool pValue) private
OverrideMovementAngle()
proto native void HumanInputController::OverrideMovementAngle (bool pOverride, float pVal) private
OverrideMovementSpeed()
proto native void HumanInputController::OverrideMovementSpeed (bool pOverride, float pVal) private
OverrideRaise()
proto native void HumanInputController::OverrideRaise (bool pOverride, bool pValue) private
ResetADS()
proto native void HumanInputController::ResetADS () private
resets ADS mode to default
Referenced by HandleADS().
ResetFreeLookToggle()
proto native void HumanInputController::ResetFreeLookToggle () private
reset freelook toggle
Referenced by HandleADS(), and HandleOptic().
ResetHoldBreath()
proto native void HumanInputController::ResetHoldBreath () private
reset hold breath toggle
ResetThrowingMode()
proto native void HumanInputController::ResetThrowingMode () private
resets Throwing mode
ResetZoomToggle()
proto native void HumanInputController::ResetZoomToggle () private
reset zoom toggle
SetDisabled()
proto native void HumanInputController::SetDisabled (bool pState) private
disables input controller
WeaponADS()
proto native bool HumanInputController::WeaponADS () private
returns true if weapon ADS mode
Referenced by HandleADS().
WeaponWasRaiseClick()
proto native bool HumanInputController::WeaponWasRaiseClick () private
returns true if weapon click perfomed recently (before raise specifically)