DayzKode: ActionTriggerRemotely Class Reference
ActionTriggerRemotely Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTriggerRemotely ()
override void CreateConditionComponents ()
override bool HasProgress ()
override bool HasProneException ()
override bool HasTarget ()
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actiontriggerremotely.c.
Constructor & Destructor Documentation
ActionTriggerRemotely()
void ActionTriggerRemotely::ActionTriggerRemotely () inline private
Definition at line 3 of file actiontriggerremotely.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PRESS_TRIGGER;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PRESS_TRIGGER;
        m_Text              = "#STR_Detonate";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTriggerRemotely::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actiontriggerremotely.c.
    {
        RemoteDetonatorTrigger rdt = RemoteDetonatorTrigger.Cast(item);
        if (rdt && rdt.IsConnected())
        {
            ExplosivesBase controlledDevice = ExplosivesBase.Cast(rdt.GetControlledDevice());
            if (controlledDevice && controlledDevice.GetPairDevice() != item)
            {
                rdt.UpdateLED(ERemoteDetonatorLEDState.OFF);
                return false;
            }
            if (controlledDevice && !controlledDevice.IsRuined() && controlledDevice.GetArmed())
            {
                if (vector.DistanceSq(player.GetPosition(), controlledDevice.GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
                {
                    rdt.UpdateLED(ERemoteDetonatorLEDState.LIT);
                    return true;
                }
            }
        }
        rdt.UpdateLED(ERemoteDetonatorLEDState.OFF);
        return false;
    }
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, ExplosivesBase(), RemoteDetonatorTrigger::GetControlledDevice(), RemoteDetonatorTrigger::IsConnected(), and Math::SqrFloat().
CreateConditionComponents()
override void ActionTriggerRemotely::CreateConditionComponents () inline private
Definition at line 10 of file actiontriggerremotely.c.
    {
        m_ConditionTarget   = new CCTNone();
        m_ConditionItem     = new CCINonRuined();
    }
References m_ConditionItem, and m_ConditionTarget.
HasProgress()
override bool ActionTriggerRemotely::HasProgress () inline private
Definition at line 16 of file actiontriggerremotely.c.
    {
        return true;
    }
HasProneException()
override bool ActionTriggerRemotely::HasProneException () inline private
Definition at line 26 of file actiontriggerremotely.c.
    {
        return true;
    }
HasTarget()
override bool ActionTriggerRemotely::HasTarget () inline private
Definition at line 21 of file actiontriggerremotely.c.
    {
        return false;
    }
OnExecuteServer()
override void ActionTriggerRemotely::OnExecuteServer (ActionData action_data) inline private
Definition at line 60 of file actiontriggerremotely.c.
    {
        RemoteDetonatorTrigger rdt = RemoteDetonatorTrigger.Cast(action_data.m_MainItem);
        if (rdt && rdt.IsConnected())
        {
            ItemBase controlledDevice = ItemBase.Cast(rdt.GetControlledDevice());
            if (controlledDevice && !controlledDevice.IsRuined())
            {
                controlledDevice.OnActivatedByItem(action_data.m_MainItem);
                action_data.m_MainItem.SetAnimationPhase("trigger", 1);
                action_data.m_MainItem.SetAnimationPhase("lever", 1);
            }
        }
    }
References RemoteDetonatorTrigger::GetControlledDevice(), RemoteDetonatorTrigger::IsConnected(), and ActionData::m_MainItem.