DayzKode: JsonUndergroundAreaTriggerData Class Reference
JsonUndergroundAreaTriggerData Class Reference
Private Member Functions
vector GetOrientation ()
vector GetPosition ()
vector GetSize ()
Private Attributes
ref array< ref JsonUndergroundAreaBreadcrumb > Breadcrumbs
float EyeAccommodation
float InterpolationSpeed
ref array< float > Orientation
ref array< float > Position
ref array< float > Size
Detailed Description
Definition at line 20 of file undergroundarealoader.c.
Member Function Documentation
GetOrientation()
vector JsonUndergroundAreaTriggerData::GetOrientation () inline private
Definition at line 27 of file undergroundarealoader.c.
    {
        return Vector(Orientation[0],Orientation[1],Orientation[2]);
    }
References Orientation, and Vector().
Referenced by UndergroundAreaLoader::SpawnTriggerCarrier().
GetPosition()
vector JsonUndergroundAreaTriggerData::GetPosition () inline private
Definition at line 22 of file undergroundarealoader.c.
    {
        return Vector(Position[0],Position[1],Position[2]);
    }
References Position, and Vector().
Referenced by UndergroundAreaLoader::SpawnTriggerCarrier().
GetSize()
vector JsonUndergroundAreaTriggerData::GetSize () inline private
Definition at line 31 of file undergroundarealoader.c.
    {
        return Vector(Size[0],Size[1],Size[2]);
    }
References Size, and Vector().
Referenced by Init().
Member Data Documentation
Breadcrumbs
ref array<ref JsonUndergroundAreaBreadcrumb> JsonUndergroundAreaTriggerData::Breadcrumbs private
Definition at line 42 of file undergroundarealoader.c.
Referenced by Init().
EyeAccommodation
float JsonUndergroundAreaTriggerData::EyeAccommodation private
Definition at line 39 of file undergroundarealoader.c.
Referenced by Init().
InterpolationSpeed
float JsonUndergroundAreaTriggerData::InterpolationSpeed private
Definition at line 40 of file undergroundarealoader.c.
Referenced by Init().
Orientation
ref array<float> JsonUndergroundAreaTriggerData::Orientation private
Definition at line 37 of file undergroundarealoader.c.
Referenced by GetOrientation().
Position
ref array<float> JsonUndergroundAreaTriggerData::Position private
Definition at line 36 of file undergroundarealoader.c.
Referenced by GetPosition().
Size
ref array<float> JsonUndergroundAreaTriggerData::Size private
Definition at line 38 of file undergroundarealoader.c.
Referenced by GetSize().