DayzKode: ActionAttachOnSelection Class Reference
ActionAttachOnSelection Class Reference
Private Member Functions
void ActionAttachOnSelection ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override ActionData CreateActionData ()
override void CreateConditionComponents ()
int FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Detailed Description
Definition at line 1 of file actionattachonselection.c.
Constructor & Destructor Documentation
ActionAttachOnSelection()
void ActionAttachOnSelection::ActionAttachOnSelection () inline private
Definition at line 3 of file actionattachonselection.c.
    {
        m_Text = "#attach";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAttachOnSelection::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 97 of file actionattachonselection.c.
    {
        if (GetGame().IsMultiplayer() && GetGame().IsServer() ) return true;
        //if (BaseBuildingBase.Cast(target.GetObject())) return false;
        if (target.GetObject() && target.GetObject().CanUseConstruction()) return false;
        return FindSlotIdToAttachOrCombine(player, target, item) != InventorySlots.INVALID;
    }
References FindSlotIdToAttachOrCombine(), and GetGame().
CreateActionData()
override ActionData ActionAttachOnSelection::CreateActionData () inline private
Definition at line 14 of file actionattachonselection.c.
    {
        AttachActionData action_data = new AttachActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionAttachOnSelection::CreateConditionComponents () inline private
Definition at line 8 of file actionattachonselection.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
FindSlotIdToAttachOrCombine()
int ActionAttachOnSelection::FindSlotIdToAttachOrCombine (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 20 of file actionattachonselection.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if ( target_entity && item )
        {
            if ( !target_entity.GetInventory() ) return InventorySlots.INVALID;
            array<string> selections = new array<string>;
            target_entity.GetActionComponentNameList(target.GetComponentIndex(), selections);
            for (int s = 0; s < selections.Count(); s++)
            {
                //Print(selections[s]);
                int carId = -1;
                if ( !target_entity.TranslateSlotFromSelection(selections[s],carId) )
                    carId = InventorySlots.GetSlotIdFromString( selections[s] );
                if ( carId == -1 )
                    continue;
                int slotsCnt = item.GetInventory().GetSlotIdCount();
                for (int i=0; i < slotsCnt; i++ )
                {
                    int itmSlotId = item.GetInventory().GetSlotId(i);
                    if ( carId == itmSlotId )
                    {
                        ItemBase currentAttachment = ItemBase.Cast(target_entity.GetInventory().FindAttachment( carId ));
                        if (currentAttachment)
{
                            if(currentAttachment.CanBeCombined( item ) )
{
                                return itmSlotId;
                            }
                        }
                        else
{
                            if ( target_entity.GetInventory() && target_entity.GetInventory().CanAddAttachment( item ) )
{
                                return itmSlotId;
                            }
                        }
                    }
                }
            }
        }
        return InventorySlots.INVALID;
    }
References ItemBase::CanBeCombined(), and InventorySlots::GetSlotIdFromString().
Referenced by ActionCondition(), and SetupAction().
OnExecuteClient()
override void ActionAttachOnSelection::OnExecuteClient (ActionData action_data) inline private
Definition at line 120 of file actionattachonselection.c.
    {
        ClearInventoryReservationEx(action_data);
        EntityAI target_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        EntityAI item_entity = action_data.m_MainItem;
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        ItemBase attachment = ItemBase.Cast( target_entity.GetInventory().FindAttachment( action_data_a.m_AttSlot ) );
        if ( attachment )
        {
            attachment.CombineItemsClient( item_entity );
        }
        else
        {
            ItemBase item_base  = ItemBase.Cast( item_entity );
            float stackable = item_base.GetTargetQuantityMax( action_data_a.m_AttSlot );
            if( stackable == 0 || stackable >= item_base.GetQuantity() )
            {
                action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_entity, item_entity, action_data_a.m_AttSlot);
            }
            else if( stackable != 0 && stackable < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( target_entity, action_data_a.m_AttSlot );
            }
        }
    }
References ClearInventoryReservationEx(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void ActionAttachOnSelection::OnExecuteServer (ActionData action_data) inline private
Definition at line 107 of file actionattachonselection.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        EntityAI target_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        EntityAI item_entity = action_data.m_MainItem;
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        action_data.m_Player.PredictiveTakeEntityToTargetAttachmentEx(target_entity, item_entity, action_data_a.m_AttSlot );
    }
References GetGame(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
SetupAction()
override bool ActionAttachOnSelection::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 72 of file actionattachonselection.c.
    {
        int attSlotId = InventorySlots.INVALID;
        if (!GetGame().IsDedicatedServer() )
        {
            attSlotId = FindSlotIdToAttachOrCombine(player, target, item);
        }
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            if (!GetGame().IsDedicatedServer())
            {
                if(attSlotId != InventorySlots.INVALID)
                {
                    AttachActionData action_data_a = AttachActionData.Cast(action_data);
                    action_data_a.m_AttSlot = attSlotId;
                    return true;
                }
                return false;
            }
            return true;
        }
        return false;
    }
References FindSlotIdToAttachOrCombine(), GetGame(), and AttachActionData::m_AttSlot.