DayzKode: House Class Reference
House Class Reference
Private Member Functions
void ChristmasTree ()
override void EEDelete (EntityAI parent)
override void EEDelete (EntityAI parent)
override void EEInit ()
override void EEInit ()
override void EEOnCECreate ()
string GetSoundSet ()
void House ()
void RequestSoundEvent ()
Static Private Member Functions
static bool Init ()
Private Attributes
const string LOOP_SOUND = "ChristmasMusic_SoundSet"
EffectSound m_AmbientSoundLoop
Particle m_ParticleEfx
XmasTreeLight m_TreeLight
Static Private Attributes
static bool m_Init = Init()
Detailed Description
Definition at line 1 of file crashbase.c.
Constructor & Destructor Documentation
House()
void House::House () inline private
Definition at line 3 of file building.c.
    {
    }
Member Function Documentation
ChristmasTree()
void House::ChristmasTree () inline private
Definition at line 7 of file christmastree.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            m_TreeLight = XmasTreeLight.Cast( ScriptedLightBase.CreateLight( XmasTreeLight, "0 0 0" ) );
            m_TreeLight.AttachOnMemoryPoint( this, "action" );
        }
    }
References GetGame().
EEDelete() [1/2]
override void House::EEDelete (EntityAI parent) inline private
Definition at line 44 of file crashbase.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( m_ParticleEfx )
                m_ParticleEfx.Stop();
        }
    }
References GetGame(), and Particle::Stop().
EEDelete() [2/2]
override void House::EEDelete (EntityAI parent) inline private
Definition at line 24 of file christmastree.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( m_TreeLight )
                m_TreeLight.Destroy();
            if ( m_AmbientSoundLoop )
                SEffectManager.DestroyEffect(m_AmbientSoundLoop);
        }
    }
References SEffectManager::DestroyEffect(), and GetGame().
EEInit() [1/2]
override void House::EEInit () inline private
Definition at line 31 of file crashbase.c.
    {
        super.EEInit();
        //Setup for local sound tests
        #ifdef DEVELOPER
        if ( !GetGame().IsMultiplayer() )
        {
            EffectSound eff = SEffectManager.PlaySound( GetSoundSet(), GetPosition(), 0.1, 0.1 );
            eff.SetAutodestroy(true);
        }
        #endif
    }
References GetGame(), GetPosition, CrashBase::GetSoundSet(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
EEInit() [2/2]
override void House::EEInit () inline private
Definition at line 16 of file christmastree.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            PlaySoundSetLoop( m_AmbientSoundLoop, LOOP_SOUND, 0, 0 );
        }
    }
References GetGame(), and PlaySoundSetLoop().
EEOnCECreate()
override void House::EEOnCECreate () inline private
Definition at line 13 of file crashbase.c.
    {
        super.EEOnCECreate();
        RequestSoundEvent();
    }
References RequestSoundEvent().
GetSoundSet()
string House::GetSoundSet () inline private
Definition at line 26 of file crashbase.c.
    {
        return "HeliCrash_Distant_SoundSet";
    }
Init()
static bool House::Init () inline static private
Definition at line 6 of file crashbase.c.
    {
        CrashSoundSets.RegisterSoundSet("HeliCrash_Distant_SoundSet");
        CrashSoundSets.RegisterSoundSet("SledgeCrash_Distant_SoundSet");
        return true;
    }
References CrashSoundSets::RegisterSoundSet().
RequestSoundEvent()
void House::RequestSoundEvent () inline private
Definition at line 19 of file crashbase.c.
    {
        Param3<bool, vector, int> playSound = new Param3<bool, vector, int>(true, GetPosition(), GetSoundSet().Hash());
        GetGame().RPCSingleParam( null, ERPCs.RPC_SOUND_HELICRASH, playSound, true );
    }
References GetGame(), GetPosition, CrashBase::GetSoundSet(), and CGame::RPCSingleParam().
Member Data Documentation
LOOP_SOUND
const string House::LOOP_SOUND = "ChristmasMusic_SoundSet" private
Definition at line 5 of file christmastree.c.
m_AmbientSoundLoop
EffectSound House::m_AmbientSoundLoop private
Definition at line 4 of file christmastree.c.
m_Init
bool House::m_Init = Init() static private
Definition at line 4 of file crashbase.c.
m_ParticleEfx
Particle House::m_ParticleEfx private
Definition at line 3 of file crashbase.c.
m_TreeLight
XmasTreeLight House::m_TreeLight private
Definition at line 3 of file christmastree.c.