DayzKode: VicinityContainer Class Reference
VicinityContainer Class Reference
Private Member Functions
override void CollapseButtonOnMouseButtonDown (Widget w)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void DraggingOverIcon (Widget w, int x, int y, Widget receiver)
override void ExpandCollapseContainer ()
VicinitySlotsContainer GetVicinityIconsContainer ()
bool IsContainerWithCargoActive ()
bool IsItemWithAttachmentsActive ()
bool IsItemWithCategoriesActive ()
bool IsVicinityContainerIconsActive ()
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
void OnDropReceivedFromEmptySpace (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromIcon (Widget w, int x, int y, Widget receiver)
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
void ToggleContainer (Container conta)
void ToggleContainer (Widget w, EntityAI item)
void TraverseShowedItems ()
void UpdateHeader (EntityAI entity, Container cont, PlayerBase player)
Updates header dragability to be consistent with current 'icon' behaviour.
override void UpdateInterval ()
void VicinityContainer (LayoutHolder parent, int sort=-1)
Private Attributes
const float DISTANCE_TO_ENTITIES = 1.0
const float DISTANCE_TO_THE_REST = 0.5
protected bool m_IsProcessing = false
ref map< CargoBase, ref Container > m_ShowedCargos = new ref map<CargoBase, ref Container>
ref array< EntityAI > m_ShowedItemIcons = new array<EntityAI>
ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
ref map< int, ref Container > m_ShowedItemsIDs = new ref map<int, ref Container>
ref VicinitySlotsContainer m_VicinityIconsContainer
Detailed Description
Definition at line 1 of file vicinitycontainer.c.
Constructor & Destructor Documentation
VicinityContainer()
void VicinityContainer::VicinityContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 13 of file vicinitycontainer.c.
    {
        m_VicinityIconsContainer = new VicinitySlotsContainer( this );
        m_Body.Insert( m_VicinityIconsContainer );
        m_VicinityIconsContainer.GetRootWidget().SetColor(166 << 24 | 120 << 16 | 120 << 8 | 120);
        m_MainWidget = m_RootWidget.FindAnyWidget( "body" );
        WidgetEventHandler.GetInstance().RegisterOnChildAdd( m_MainWidget, this, "OnChildAdd" );
        WidgetEventHandler.GetInstance().RegisterOnChildRemove( m_MainWidget, this, "OnChildRemove" );
        RecomputeOpenedContainers();
        m_CollapsibleHeader.SetName("#container_vicinity");
        LoadDefaultState();
    }
References WidgetEventHandler::GetInstance(), CollapsibleContainer::LoadDefaultState(), CollapsibleContainer::m_CollapsibleHeader, m_RootWidget, m_VicinityIconsContainer, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), and Header::SetName().
Member Function Documentation
CollapseButtonOnMouseButtonDown()
override void VicinityContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 649 of file vicinitycontainer.c.
    {
        super.CollapseButtonOnMouseButtonDown(w);
        ItemManager.GetInstance().SetDefaultHeaderOpenState( "VICINITY", !m_Hidden );
    }
References ItemManager::GetInstance(), CollapsibleContainer::m_Hidden, and ItemManager::SetDefaultHeaderOpenState().
DraggingOverHeader()
override void VicinityContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 87 of file vicinitycontainer.c.
    {
        if ( w == null )
        {
            return;
        }
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if ( !ipw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if ( !ipw && ItemPreviewWidget.Cast( w ) )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if ( !ipw || !ipw.GetItem() )
        {
            return;
        }
        if ( ipw.GetItem() && GetGame().GetPlayer().CanDropEntity( ipw.GetItem() ) && ipw.GetItem().GetInventory().CanRemoveEntity() && m_ShowedItemIcons.Find( ipw.GetItem() ) == -1 )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
        }
        else
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            ItemManager.GetInstance().ShowSourceDropzone( ipw.GetItem() );
        }
    }
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_ShowedItemIcons, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
Referenced by LeftArea::DraggingOverHeader().
DraggingOverIcon()
void VicinityContainer::DraggingOverIcon (Widget w, int x, int y, Widget receiver) inline private
Definition at line 125 of file vicinitycontainer.c.
    {
        string name = receiver.GetName();
        name.Replace("PanelWidget", "Render");
        ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget(name) );
        EntityAI receiver_item = receiver_iw.GetItem();
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if ( !ipw )
        {
            name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if ( !ipw && ItemPreviewWidget.Cast( w ) )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if (!ipw)
        {
            return;
        }
        if ( !ItemBase.Cast( receiver_item ) || !ipw.GetItem() )
        {
            return;
        }
        if ( ipw.GetItem().GetInventory().CanRemoveEntity() || m_ShowedItemIcons.Find( ipw.GetItem() ) > -1 )
        {
            if ( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( ipw.GetItem() ) ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                return;
            }
            else if ( GameInventory.CanSwapEntitiesEx( receiver_item, ipw.GetItem() ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                return;
            }
            /*else if( GetGame().GetPlayer().CanDropEntity( ipw.GetItem() ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                return;
            }*/
        }
        ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
        ItemManager.GetInstance().ShowSourceDropzone( ipw.GetItem() );
    }
References ColorManager::COMBINE_COLOR, ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), ItemManager::HideDropzones(), m_ShowedItemIcons, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
ExpandCollapseContainer()
override void VicinityContainer::ExpandCollapseContainer () inline private
Definition at line 614 of file vicinitycontainer.c.
    {
        EntityAI item = GetFocusedItem();
        Container conta;
        if( m_ShowedItems && item )
        {
            conta = m_ShowedItems.Get( item );
            ToggleContainer( conta );
        }
    }
References Container::GetFocusedItem(), m_ShowedItems, and ToggleContainer().
GetVicinityIconsContainer()
VicinitySlotsContainer VicinityContainer::GetVicinityIconsContainer () inline private
Definition at line 32 of file vicinitycontainer.c.
    {
        return m_VicinityIconsContainer;
    }
References m_VicinityIconsContainer.
Referenced by UpdateConsoleToolbar().
IsContainerWithCargoActive()
bool VicinityContainer::IsContainerWithCargoActive () inline private
Definition at line 37 of file vicinitycontainer.c.
    {
        return ( ContainerWithCargo.Cast( GetFocusedContainer() ) != null );
    }
Referenced by UpdateConsoleToolbar().
IsItemWithAttachmentsActive()
bool VicinityContainer::IsItemWithAttachmentsActive () inline private
Definition at line 42 of file vicinitycontainer.c.
    {
        return ( ContainerWithCargoAndAttachments.Cast( GetFocusedContainer() ) != null );
    }
Referenced by UpdateConsoleToolbar().
IsItemWithCategoriesActive()
bool VicinityContainer::IsItemWithCategoriesActive () inline private
Definition at line 47 of file vicinitycontainer.c.
    {
        return ( AttachmentCategoriesContainer.Cast( GetFocusedContainer() ) != null );
    }
IsVicinityContainerIconsActive()
bool VicinityContainer::IsVicinityContainerIconsActive () inline private
Definition at line 27 of file vicinitycontainer.c.
    {
        return m_VicinityIconsContainer.IsActive();
    }
References m_VicinityIconsContainer.
Referenced by UpdateConsoleToolbar().
OnChildAdd()
override bool VicinityContainer::OnChildAdd (Widget w, Widget child) inline private
Definition at line 639 of file vicinitycontainer.c.
    {
        if ( w == GetMainWidget() )
        {
            GetMainWidget().Update();
            m_Parent.OnChildAdd( w, child );
        }
        return true;
    }
References m_Parent.
OnChildRemove()
override bool VicinityContainer::OnChildRemove (Widget w, Widget child) inline private
Definition at line 626 of file vicinitycontainer.c.
    {
        w.Update();
        float x, y;
        w.GetScreenSize( x, y );
        if ( w == GetMainWidget() )
        {
            GetMainWidget().Update();
            m_Parent.OnChildRemove( w, child );
        }
        return true;
    }
References m_Parent, x, and y.
OnDropReceivedFromEmptySpace()
void VicinityContainer::OnDropReceivedFromEmptySpace (Widget w, int x, int y, Widget receiver) inline private
Definition at line 306 of file vicinitycontainer.c.
    {
        OnDropReceivedFromHeader( w, x, y, receiver );
    }
References OnDropReceivedFromHeader(), x, and y.
OnDropReceivedFromHeader()
override void VicinityContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 252 of file vicinitycontainer.c.
    {
        if ( !w )
            return;
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if ( !ipw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if ( !ipw )
        {
            ipw = ItemPreviewWidget.Cast( w );
        }
        if ( !ipw )
            return;
        EntityAI item = ipw.GetItem();
        if ( !ipw.IsInherited( ItemPreviewWidget ) || !item )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( !item.GetInventory().CanRemoveEntity() || m_ShowedItemIcons.Find( item ) > -1 )
            return;
        if ( player.CanDropEntity( item ) )
        {
            ItemBase item_base = ItemBase.Cast( item );
            if ( item_base )
            {
                if ( item_base.GetTargetQuantityMax() < item_base.GetQuantity() )
                    item_base.SplitIntoStackMaxClient( null, -1 );
                else
                    player.PhysicalPredictiveDropItem( item_base );
            }
        }
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
        if ( menu )
        {
            menu.RefreshQuickbar();
        }
    }
References GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), InventoryMenu(), m_ShowedItemIcons, MENU_INVENTORY, name, string::Replace(), and ItemManager::SetIsDragging().
Referenced by OnDropReceivedFromEmptySpace(), and OnLeftPanelDropReceived().
OnDropReceivedFromIcon()
void VicinityContainer::OnDropReceivedFromIcon (Widget w, int x, int y, Widget receiver) inline private
Definition at line 184 of file vicinitycontainer.c.
    {
        string name = receiver.GetName();
        name.Replace("PanelWidget", "Render");
        ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget(name) );
        EntityAI receiver_item = receiver_iw.GetItem();
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if ( !ipw )
        {
            name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if ( !ItemBase.Cast( receiver_item ) || !ipw.GetItem() )
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        bool equal_typed = item.GetType() == receiver_item.GetType();
        if ( !receiver_item.IsInherited( ItemBase ) || item == null )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( !item.GetInventory().CanRemoveEntity() )
            return;
        if ( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( item ) ) )
        {
            ( ItemBase.Cast( receiver_item ) ).CombineItemsClient( ItemBase.Cast( item ) );
        }
        else if( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
        {
            InventoryLocation il1 = new InventoryLocation;
            InventoryLocation il2 = new InventoryLocation;
            receiver_item.GetInventory().GetCurrentInventoryLocation( il1 );
            item.GetInventory().GetCurrentInventoryLocation( il2 );
            if( !receiver_item.GetInventory().CanRemoveEntity() || ( il1.GetType() == InventoryLocationType.GROUND && il2.GetType() == InventoryLocationType.GROUND ) )
                return;
            player.PredictiveSwapEntities( item, receiver_item );
        }
        /*else if( player.CanDropEntity( item ) )
        {
            player.PredictiveDropEntity( item );
        }*/
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        PrepareOwnedTooltip(item);
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
        if ( menu )
        {
            menu.RefreshQuickbar();
        }
    }
References CombineItemsClient(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetType(), ItemManager::HideDropzones(), InventoryMenu(), MENU_INVENTORY, name, string::Replace(), and ItemManager::SetIsDragging().
OnLeftPanelDropReceived()
void VicinityContainer::OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
Definition at line 247 of file vicinitycontainer.c.
    {
        OnDropReceivedFromHeader( w, x, y, receiver );
    }
References OnDropReceivedFromHeader(), x, and y.
Referenced by LeftArea::OnLeftPanelDropReceived().
ToggleContainer() [1/2]
void VicinityContainer::ToggleContainer (Container conta) inline private
Definition at line 609 of file vicinitycontainer.c.
    {
        conta.Toggle();
    }
ToggleContainer() [2/2]
void VicinityContainer::ToggleContainer (Widget w, EntityAI item) inline private
Definition at line 591 of file vicinitycontainer.c.
    {
        SlotsIcon slots_icon;
        Container c;
        w.GetUserData(slots_icon);
        if ( item )
        {
            c = Container.Cast( m_ShowedItems.Get( item ) );
        }
        if (c)
        {
            ToggleContainer(c);
        }
    }
References m_ShowedItems, and ToggleContainer().
Referenced by ExpandCollapseContainer(), and ToggleContainer().
TraverseShowedItems()
void VicinityContainer::TraverseShowedItems () inline private
Definition at line 52 of file vicinitycontainer.c.
    {
        map<string, bool> serialized_types = new map<string, bool>();
        for ( int i = 0; i < m_ShowedItems.Count(); i++ )
        {
            EntityAI entity = m_ShowedItems.GetKey( i );
            Container container = m_ShowedItems.GetElement( i );
            string type = entity.GetType();
            if ( container.IsInherited( ContainerWithCargo ) )
            {
                if ( !serialized_types.Contains( type ) )
                {
                    ContainerWithCargo item_with_cargo = ContainerWithCargo.Cast( container );
                    serialized_types.Insert( type, item_with_cargo.IsOpened() );
                }
            }
        }
        if ( serialized_types.Count() > 0 )
        {
            FileSerializer file = new FileSerializer();
            if ( file.Open( "inventory_state.save", FileMode.APPEND ) )
            {
                file.Write( serialized_types.Count() );
                for ( i = 0; i < serialized_types.Count(); i++ )
                {
                    file.Write( serialized_types.GetKey( i ) );
                    file.Write( serialized_types.GetElement( i ) );
                }
            }
            file.Close();
        }
    }
References FileSerializer::Close(), m_ShowedItems, FileSerializer::Open(), and Serializer::Write().
UpdateHeader()
void VicinityContainer::UpdateHeader (EntityAI entity, Container cont, PlayerBase player) inline private
Updates header dragability to be consistent with current 'icon' behaviour.
Definition at line 656 of file vicinitycontainer.c.
    {
        bool draggable = ItemManager.GetInstance().EvaluateContainerDragabilityDefault(entity);
        if (cont.GetHeader())
        {
            if (GetDragWidget() == cont.GetHeader())
            {
                CancelWidgetDragging();
            }
            ItemManager.GetInstance().SetWidgetDraggable(cont.GetHeader().GetMainWidget(),draggable);
        }
    }
References CancelWidgetDragging(), ItemManager::EvaluateContainerDragabilityDefault(), GetDragWidget(), Container::GetHeader(), ItemManager::GetInstance(), and ItemManager::SetWidgetDraggable().
Referenced by UpdateInterval().
UpdateInterval()
override void VicinityContainer::UpdateInterval () inline private
Definition at line 311 of file vicinitycontainer.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if (!player)
            return;
        super.UpdateInterval();
        EntityAI eai;
        vector pos = player.GetPosition();
        ref array<EntityAI> objects;
        VicinityItemManager.GetInstance().Update( player.GetDeltaT() );
        objects = VicinityItemManager.GetInstance().GetVicinityItems();
        //GetItemsShowableInInventory
        array<EntityAI> showable_items = new array<EntityAI>;
        int m_OldShowedItemIconsCount = m_ShowedItemIcons.Count();
        m_ShowedItemIcons.Clear();
        GameInventory game_inventory = player.GetInventory();
        for ( int i = 0; i < objects.Count(); i++ )
        {
            eai = objects.Get( i );
            if ( eai == null || game_inventory.IsPlaceholderEntity( eai ) )
                continue; // noproxy: ignore body placeholder
            BaseBuildingBase base_building = BaseBuildingBase.Cast(eai);
            if (base_building && !base_building.IsPlayerInside(player,""))
                continue;
            if ( eai.IsInventoryVisible() )
            {
                showable_items.Insert( eai );
                if ( !eai.IsInherited( DayZInfected ) && !eai.IsInherited( PlayerBase ) && !eai.IsInherited( AnimalBase ) && !eai.DisableVicinityIcon() )
                {
                    m_ShowedItemIcons.Insert( eai );
                }
            }
        }
        //MW HOTFIX - old containers must be removed before new one are added (part of initialize are refreshed whole structure - need proper fix to avoid it)
        ref map<EntityAI, ref Container> new_showed_items = new ref map<EntityAI, ref Container>;
        Container con;
        for ( i = 0; i < showable_items.Count(); i++ )
        {
            new_showed_items.Insert(showable_items[i],null);
        }
        bool need_update_focus = false;
        for ( i = 0; i < m_ShowedItems.Count(); i++ )
        {
            EntityAI ent = m_ShowedItems.GetKey( i );
            m_ShowedItems.GetElement( i ).UpdateInterval();
            con = m_ShowedItems.GetElement( i );
            if ( !new_showed_items.Contains( ent ) )
            {
                GetMainWidget().Update();
                if ( con.IsActive() )
                    need_update_focus = true;
                Container.Cast( GetParent() ).Remove( con );
                Remove( con );
            }
            else
            {
                UpdateHeader(ent,con,player); //squeezed here, the map is iterated over enough already..
            }
        }
        //ref map<EntityAI, ref Container> new_showed_items = new ref map<EntityAI, ref Container>;
        new_showed_items.Clear();
        ref map<int, ref Container> showed_items_IDs = new ref map<int, ref Container>;
        for ( i = 0; i < showable_items.Count(); i++ )
        {
            EntityAI entity = showable_items.Get( i );
            if ( entity )
            {
                if ( game_inventory && !m_ShowedItems.Contains( entity ) )
                {
                    string config = "CfgVehicles " + entity.GetType() + " GUIInventoryAttachmentsProps";
                    if ( GetGame().ConfigIsExisting( config ) )
                    {
                        AttachmentCategoriesContainer ac = new AttachmentCategoriesContainer( m_Parent, -1 );
                        ac.SetEntity( entity );
                        new_showed_items.Insert( entity, ac );
                        showed_items_IDs.Insert( entity.GetID(), ac);
                    }
                    else if ( entity.GetSlotsCountCorrect() > 0 && entity.GetInventory().GetCargo() )
                    {
                        if ( entity.IsInherited( DayZInfected ) )
{
                            if ( entity.IsAlive() )
{
                                continue;
                            }
                            ZombieContainer zmb_cnt = new ZombieContainer( m_Parent, -1 );
                            zmb_cnt.SetEntity( entity );
                            new_showed_items.Insert( entity, zmb_cnt );
                            showed_items_IDs.Insert( entity.GetID(), zmb_cnt );
                            Container.Cast( GetParent() ).Insert( zmb_cnt );
                        }
                        else
{
                            ContainerWithCargoAndAttachments iwca = new ContainerWithCargoAndAttachments( this, -1 );
                            iwca.SetEntity( entity, false );
                            new_showed_items.Insert( entity, iwca );
                            showed_items_IDs.Insert( entity.GetID(), iwca );
                        }
                    }
                    else if ( entity.GetInventory().GetCargo() )
                    {
                        ContainerWithCargo iwc = new ContainerWithCargo( this, -1 );
                        iwc.SetEntity( entity, 0, false );
                        new_showed_items.Insert( entity, iwc );
                        showed_items_IDs.Insert( entity.GetID(), iwc );
                        iwc.UpdateInterval();
                    }
                    else if ( entity.GetSlotsCountCorrect() > 0 )
                    {
                        if ( entity.HasEnergyManager() )
{
                            ContainerWithElectricManager iwem = new ContainerWithElectricManager( this, -1 );
                            iwem.SetEntity( entity, false );
                            new_showed_items.Insert( entity, iwem );
                            showed_items_IDs.Insert( entity.GetID(), iwem );
                        }
                        else
{
                            if ( entity.IsInherited( PlayerBase ) )
{
                                if ( !PlayerBase.DEBUG_INVENTORY_ACCESS && entity.IsAlive() && ( !PlayerBase.Cast( entity ).IsUnconscious() && !PlayerBase.Cast( entity ).IsRestrained() ) )
{
                                    continue;
                                }
                                PlayerContainer plyr_cnt = new PlayerContainer( m_Parent, false );
                                plyr_cnt.SetPlayer( PlayerBase.Cast( entity ) );
                                Container.Cast( GetParent() ).Insert( plyr_cnt );
                                ( Container.Cast( m_Parent ) ).Refresh();
                                new_showed_items.Insert( entity, plyr_cnt );
                                showed_items_IDs.Insert( entity.GetID(), plyr_cnt);
                            }
                            else
{
                                ContainerWithCargoAndAttachments iwcas = new ContainerWithCargoAndAttachments( this, -1 );
                                iwcas.SetEntity( entity, false );
                                new_showed_items.Insert( entity, iwcas );
                                showed_items_IDs.Insert( entity.GetID(), iwcas );
                                iwcas.UpdateInterval();
                            }
                        }
                    }
                }
                else
                {
                    //TODO MW: remove old containers on one spot (hotfix)
                    con = m_ShowedItems.Get( entity );
                    if ( con )
                    {
                        if ( entity.IsInherited( PlayerBase ) )
{
                            if ( !PlayerBase.DEBUG_INVENTORY_ACCESS && entity.IsAlive() && ( !PlayerBase.Cast( entity ).IsUnconscious() && !PlayerBase.Cast( entity ).IsRestrained() ) )
{
                                GetMainWidget().Update();
                                if ( con.IsActive() )
                                    need_update_focus = true;
                                Container.Cast( GetParent() ).Remove( con );
                                Remove( con );
                                continue;
                            }
                        }
                        if ( entity.IsInherited( BaseBuildingBase ) )
{
                            if ( !BaseBuildingBase.Cast(entity).IsPlayerInside(player,""))
{
                                GetMainWidget().Update();
                                if ( con.IsActive() )
                                    need_update_focus = true;
                                Container.Cast( GetParent() ).Remove( con );
                                Remove( con );
                                continue;
                            }
                        }
                        new_showed_items.Insert( entity, m_ShowedItems.Get( entity ) );
                        showed_items_IDs.Insert( entity.GetID(), m_ShowedItemsIDs.Get( entity.GetID() ) );
                    }
                }
            }
        }
        ref map<CargoBase, ref Container> new_showed_cargos = new ref map<CargoBase, ref Container>;
        auto cargoes = VicinityItemManager.GetInstance().GetVicinityCargos();
        for ( i = 0; i < cargoes.Count(); i++ )
        {
            CargoBase cgo = cargoes.Get( i );
            if ( cgo )
            {
                if (game_inventory && !m_ShowedCargos.Contains( cgo ) )
                {
                    ContainerWithCargo pxc = new ContainerWithCargo( this, -1 );
                    pxc.SetEntity( cgo.GetCargoOwner(), cgo.GetOwnerCargoIndex(), false );
                    new_showed_cargos.Insert( cgo, pxc );
                    pxc.UpdateInterval();
                }
                else
                {
                    if ( m_ShowedCargos.Get( cgo ) )
                    {
                        new_showed_cargos.Insert( cgo, m_ShowedCargos.Get( cgo ) );
                    }
                }
            }
        }
//          Print(m_ShowedItems.Count());
/*      bool need_update_focus = false;
        for ( i = 0; i < m_ShowedItems.Count(); i++ )
        {
            EntityAI ent = m_ShowedItems.GetKey( i );
            m_ShowedItems.GetElement( i ).UpdateInterval();
            Container con = m_ShowedItems.GetElement( i );
            if ( !new_showed_items.Contains( ent ) )
            {
                GetMainWidget().Update();
                if ( con.IsActive() )
                    need_update_focus = true;
                Container.Cast( GetParent() ).Remove( con );
                Remove( con );
            }
            else
            {
                UpdateHeader(ent,con,player); //squeezed here, the map is iterated over enough already..
            }
        }*/
        for ( int ic = 0; ic < m_ShowedCargos.Count(); ic++ )
        {
            CargoBase cgo2 = m_ShowedCargos.GetKey( ic );
            m_ShowedCargos.GetElement( ic ).UpdateInterval();
            if ( !new_showed_cargos.Contains( cgo2 ) )
            {
                Container con2 = m_ShowedCargos.GetElement( ic );
                if( con2.IsActive() )
                    need_update_focus = true;
                GetMainWidget().Update();
                Container.Cast( GetParent() ).Remove( con2 );
                Remove( con2 );
            }
        }
        m_ShowedItems = new_showed_items;
        m_ShowedItemsIDs = showed_items_IDs;
        m_ShowedCargos = new_showed_cargos;
        //Because WTF (zombie container)
        Container.Cast( GetParent() ).RecomputeOpenedContainers();
        if (need_update_focus)
            SetFirstActive();
        //RecomputeOpenedContainers();
        UpdateCollapseButtons();
        m_VicinityIconsContainer.ShowItemsInContainers( m_ShowedItemIcons );
        if ( m_ShowedItemIcons.Count() != m_OldShowedItemIconsCount )
        {
            Inventory in = Inventory.Cast( GetRoot() );
            if ( in )
                in.UpdateConsoleToolbar();
        }
    }
References ConfigIsExisting(), CargoBase::GetCargoOwner(), GetGame(), VicinityItemManager::GetInstance(), CargoBase::GetOwnerCargoIndex(), GetParent(), GetPlayer(), VicinityItemManager::GetVicinityCargos(), VicinityItemManager::GetVicinityItems(), Inventory(), EntityAI::IsInventoryVisible(), BaseBuildingBase::IsPlayerInside(), m_Parent, m_ShowedCargos, m_ShowedItemIcons, m_ShowedItems, m_ShowedItemsIDs, m_VicinityIconsContainer, CollapsibleContainer::Refresh(), CollapsibleContainer::Remove(), AttachmentCategoriesContainer::SetEntity(), ContainerWithElectricManager::SetEntity(), ZombieContainer::SetEntity(), PlayerContainer::SetPlayer(), VicinitySlotsContainer::ShowItemsInContainers(), VicinityItemManager::Update(), CollapsibleContainer::UpdateCollapseButtons(), and UpdateHeader().
Member Data Documentation
DISTANCE_TO_ENTITIES
const float VicinityContainer::DISTANCE_TO_ENTITIES = 1.0 private
Definition at line 10 of file vicinitycontainer.c.
DISTANCE_TO_THE_REST
const float VicinityContainer::DISTANCE_TO_THE_REST = 0.5 private
Definition at line 11 of file vicinitycontainer.c.
m_IsProcessing
protected bool VicinityContainer::m_IsProcessing = false private
Definition at line 8 of file vicinitycontainer.c.
m_ShowedCargos
ref map<CargoBase, ref Container> VicinityContainer::m_ShowedCargos = new ref map<CargoBase, ref Container> private
Definition at line 7 of file vicinitycontainer.c.
Referenced by UpdateInterval().
m_ShowedItemIcons
ref array<EntityAI> VicinityContainer::m_ShowedItemIcons = new array<EntityAI> private
Definition at line 6 of file vicinitycontainer.c.
Referenced by DraggingOverHeader(), DraggingOverIcon(), OnDropReceivedFromHeader(), and UpdateInterval().
m_ShowedItems
ref map<EntityAI, ref Container> VicinityContainer::m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 4 of file vicinitycontainer.c.
Referenced by ExpandCollapseContainer(), ToggleContainer(), TraverseShowedItems(), and UpdateInterval().
m_ShowedItemsIDs
ref map<int, ref Container> VicinityContainer::m_ShowedItemsIDs = new ref map<int, ref Container> private
Definition at line 5 of file vicinitycontainer.c.
Referenced by UpdateInterval().
m_VicinityIconsContainer
ref VicinitySlotsContainer VicinityContainer::m_VicinityIconsContainer private
Definition at line 3 of file vicinitycontainer.c.
Referenced by GetVicinityIconsContainer(), IsVicinityContainerIconsActive(), UpdateInterval(), and VicinityContainer().