DayzKode: Backlit Class Reference
Backlit Class Reference
Backlit effect class.
Private Member Functions
void HintClear ()
void HintShow (UAInput action)
void KeybindingClear ()
void KeybindingShow (int keyHash)
void LoadingAnim ()
void MainMenu_OnHide ()
void MainMenu_OnShow ()
void OnEnterCar ()
void OnInit (DayZGame game)
void OnLeaveCar ()
void OnSwimmingStart ()
void OnSwimmingStop ()
void RefreshVehicleLayout (int iGear, bool bCEL)
void SetBlood (float fBlood)
void SetHealth (float fHealth)
void UpdatePlayer (bool bForce)
void VisualiseBlood (int iLevel)
void VisualiseHealth (int iLevel)
Private Attributes
bool m_BacklitActive
int m_BloodBefore = -1
int m_BloodNew = 0
bool m_CELBefore = false
int m_GearBefore = 0
int m_HealthBefore = -1
int m_HealthNew = 0
Detailed Description
Backlit effect class.
Definition at line 104 of file backlit.c.
Member Function Documentation
HintClear()
void Backlit::HintClear () inline private
Definition at line 211 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // remove previous backlit
        GetUApi().Backlit_Remove(EUABLAYER_HINTKEY);
    }
References UAInputAPI::Backlit_Remove(), EUABLAYER_HINTKEY, GetUApi(), and m_BacklitActive.
HintShow()
void Backlit::HintShow (UAInput action) inline private
Definition at line 221 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        action.Backlit_Override(EUABLAYER_HINTKEY,0xffafafff);
    }
References UAInput::Backlit_Override(), EUABLAYER_HINTKEY, and m_BacklitActive.
KeybindingClear()
void Backlit::KeybindingClear () inline private
Definition at line 230 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        GetUApi().Backlit_Remove(EUABLAYER_ALL);
    }
References UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
KeybindingShow()
void Backlit::KeybindingShow (int keyHash) inline private
Definition at line 239 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        GetUApi().Backlit_KeyByHash(keyHash,EUABLAYER_VISKEY,EUABACKLIT_FADEOUT_SLOW,0xff0000ff);
    }
References UAInputAPI::Backlit_KeyByHash(), EUABACKLIT_FADEOUT_SLOW, EUABLAYER_VISKEY, GetUApi(), and m_BacklitActive.
LoadingAnim()
void Backlit::LoadingAnim () inline private
Definition at line 121 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // lighten up your desktop
        GetUApi().Backlit_KeyByName("kD",EUABLAYER_LOADING,EUABACKLIT_ON,0xffff0000);
        GetUApi().Backlit_KeyByName("kA",EUABLAYER_LOADING,EUABACKLIT_ON,0xffcf0000);
        GetUApi().Backlit_KeyByName("kY",EUABLAYER_LOADING,EUABACKLIT_ON,0xffaf0000);
        GetUApi().Backlit_KeyByName("kZ",EUABLAYER_LOADING,EUABACKLIT_ON,0xff8f0000);
        GetUApi().Backlit_Animation("Loading/",2,0xffc8c8c8,0xff080808);
        GetUApi().Backlit_ForceUpdate();
    }
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_ForceUpdate(), UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_LOADING, GetUApi(), and m_BacklitActive.
MainMenu_OnHide()
void Backlit::MainMenu_OnHide () inline private
Definition at line 148 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        GetUApi().Backlit_Remove(EUABLAYER_ALL);
        GetUApi().Backlit_Background(0,0xff220000,0xff222222);
    }
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
MainMenu_OnShow()
void Backlit::MainMenu_OnShow () inline private
Definition at line 136 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // lighten up your desktop
        GetUApi().Backlit_Remove(EUABLAYER_ALL);
        GetUApi().Backlit_Animation("MainMenu/",2,0xffff0000,0xff080000);
        GetUApi().Backlit_ForceUpdate();
    }
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_ForceUpdate(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
OnEnterCar()
void Backlit::OnEnterCar () inline private
Definition at line 158 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        GetUApi().Backlit_Remove(EUABLAYER_ALL);
        GetUApi().Backlit_Background(0,0xff211202,0xff110800);
    }
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetUApi(), and m_BacklitActive.
OnInit()
void Backlit::OnInit (DayZGame game) inline private
Definition at line 110 of file backlit.c.
    {
        // enable only on client/ standalone!
        if( game.IsClient() || !game.IsMultiplayer() )
            m_BacklitActive = true;
        if( m_BacklitActive )
            Print("... Backlit Effects Enabled");
    }
References m_BacklitActive, and Print().
Referenced by DayZGame().
OnLeaveCar()
void Backlit::OnLeaveCar () inline private
Definition at line 168 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // force update player
        if( GetGame().GetMission().GetHud() )
        {
            GetUApi().Backlit_Remove(EUABLAYER_ALL);
            GetUApi().Backlit_Background(0,0xff220000,0xff222222);
            UpdatePlayer(true);
        }
    }
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_Remove(), EUABLAYER_ALL, GetGame(), GetUApi(), m_BacklitActive, and UpdatePlayer().
OnSwimmingStart()
void Backlit::OnSwimmingStart () inline private
Definition at line 184 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // reset queue
        GetUApi().Backlit_EmptyQueue();
        // play hit animation
        GetUApi().Backlit_Animation("Water/",0,0xff00ffff,0xffffffff);
    }
References UAInputAPI::Backlit_Animation(), UAInputAPI::Backlit_EmptyQueue(), GetUApi(), and m_BacklitActive.
OnSwimmingStop()
void Backlit::OnSwimmingStop () inline private
Definition at line 196 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        if( GetGame().GetMission().GetHud() )
        {
            // enqueue background
            GetUApi().Backlit_Background(0,0xff220000,0xff222222);
            // force update player
            UpdatePlayer(true);
        }
    }
References UAInputAPI::Backlit_Background(), GetGame(), GetUApi(), m_BacklitActive, and UpdatePlayer().
RefreshVehicleLayout()
void Backlit::RefreshVehicleLayout (int iGear, bool bCEL) inline private
Definition at line 390 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        UAInputAPI ua_api = GetUApi();
        if( m_GearBefore != iGear )
        {
            m_GearBefore = iGear;
            int activeColor = 0xff3fff3f;
            int dimmColor = 0xff0f3f0f;
            if( iGear == CarGear.REVERSE )
                ua_api.Backlit_KeyByName("kR",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("kR",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.NEUTRAL )
                ua_api.Backlit_KeyByName("kN",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("kN",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.FIRST )
                ua_api.Backlit_KeyByName("k1",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("k1",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.SECOND )
                ua_api.Backlit_KeyByName("k2",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("k2",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.THIRD )
                ua_api.Backlit_KeyByName("k3",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("k3",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.FOURTH )
                ua_api.Backlit_KeyByName("k4",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("k4",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
            if( iGear == CarGear.FIFTH )
                ua_api.Backlit_KeyByName("k5",EUABLAYER_CAR,EUABACKLIT_ON,activeColor);
            else
                ua_api.Backlit_KeyByName("k5",EUABLAYER_CAR,EUABACKLIT_ON,dimmColor);
        }
        if( bCEL != m_CELBefore )
        {
            m_CELBefore = bCEL;
            if( bCEL )
                ua_api.Backlit_KeyByName("kC",EUABLAYER_CAR,EUABACKLIT_ON,0xffff0f0f);
            else
                ua_api.Backlit_KeyByName("kC",EUABLAYER_CAR,EUABACKLIT_NONE,0xff000000);
        }
    }
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_NONE, EUABACKLIT_ON, EUABLAYER_CAR, GetUApi(), m_BacklitActive, m_CELBefore, and m_GearBefore.
SetBlood()
void Backlit::SetBlood (float fBlood) inline private
Definition at line 336 of file backlit.c.
    {
        float blood = fBlood * 0.0002; // div 5000
        m_BloodNew = blood*4; // 4 stages
    }
References m_BloodNew.
SetHealth()
void Backlit::SetHealth (float fHealth) inline private
Definition at line 330 of file backlit.c.
    {
        float health = fHealth * 0.01; // div 100
        m_HealthNew = health*4; // 4 stages
    }
References m_HealthNew.
UpdatePlayer()
void Backlit::UpdatePlayer (bool bForce) inline private
Definition at line 342 of file backlit.c.
    {
        if( !m_BacklitActive )
            return; // always return when backlit not present!
        // force update
        if( bForce )
        {
            m_HealthBefore = -1;
            m_BloodBefore = -1;
        }
        // do not update
        if( m_HealthNew == m_HealthBefore && m_BloodNew == m_BloodBefore )
            return;
        // remove previous layers
        GetUApi().Backlit_Remove(EUABLAYER_ALL);
        // set keys to layer CUSTOM
        GetUApi().Backlit_KeyByName("kW",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff0000ff);
        GetUApi().Backlit_KeyByName("kA",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff0000cf);
        GetUApi().Backlit_KeyByName("kS",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff0000af);
        GetUApi().Backlit_KeyByName("kD",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff00008f);
        GetUApi().Backlit_KeyByName("kX",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff3f3f3f);
        GetUApi().Backlit_KeyByName("kC",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff3f3f3f);
        GetUApi().Backlit_KeyByName("kQ",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff7f7f0f);
        GetUApi().Backlit_KeyByName("kE",EUABLAYER_CUSTOM,EUABACKLIT_ON,0xff7f7f0f);
        // health
        VisualiseHealth(m_HealthNew);
        // blood
        VisualiseBlood(m_BloodNew);
        // animation
        GetUApi().Backlit_Background(0,0xff220000,0xff222222);
        // save level
        m_BloodBefore = m_BloodNew;
        m_HealthBefore = m_HealthNew;
    }
References UAInputAPI::Backlit_Background(), UAInputAPI::Backlit_KeyByName(), UAInputAPI::Backlit_Remove(), EUABACKLIT_ON, EUABLAYER_ALL, EUABLAYER_CUSTOM, GetUApi(), m_BacklitActive, m_BloodBefore, m_BloodNew, m_HealthBefore, m_HealthNew, VisualiseBlood(), and VisualiseHealth().
Referenced by OnLeaveCar(), and OnSwimmingStop().
VisualiseBlood()
void Backlit::VisualiseBlood (int iLevel) inline private
Definition at line 286 of file backlit.c.
    {
        UAInputAPI ua_api = GetUApi();
        int aColor = 0xffff1f1f;
        int dColor = 0xff1f0000;
        if( iLevel > 0 )
            ua_api.Backlit_KeyByName("kF5",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF5",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel > 1 )
            ua_api.Backlit_KeyByName("kF6",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF6",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel > 2 )
            ua_api.Backlit_KeyByName("kF7",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF7",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel > 3 )
            ua_api.Backlit_KeyByName("kF8",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF8",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
/*      int lc = 0xff1f0000;
        if( iLevel > 0 )
            lc = 0xff3f0000;
        else if( iLevel > 1 )
            lc = 0xff7f0000;
        else if( iLevel > 2 )
            lc = 0xffaf0000;
        else if( iLevel > 3 )
            lc = iLevel;
        ua_api.Backlit_KeyByName("mBRight",EUABLAYER_HUMAN,EUABACKLIT_ON,lc);*/
    }
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_HUMAN, and GetUApi().
Referenced by UpdatePlayer().
VisualiseHealth()
void Backlit::VisualiseHealth (int iLevel) inline private
Definition at line 248 of file backlit.c.
    {
        UAInputAPI ua_api = GetUApi();
        int aColor = 0xff1fff1f;
        int dColor = 0xff001f00;
        if( iLevel > 0 )
            ua_api.Backlit_KeyByName("kF1",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF1",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel > 1 )
            ua_api.Backlit_KeyByName("kF2",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF2",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel> 2 )
            ua_api.Backlit_KeyByName("kF3",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF3",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
        if( iLevel > 3 )
            ua_api.Backlit_KeyByName("kF4",EUABLAYER_HUMAN,EUABACKLIT_ON,aColor);
        else
            ua_api.Backlit_KeyByName("kF4",EUABLAYER_HUMAN,EUABACKLIT_ON,dColor );
/*      int lc = 0xff001f00;
        if( iLevel > 0 )
            lc = 0xff003f00;
        else if( iLevel > 1 )
            lc = 0xff007f00;
        else if( iLevel > 2 )
            lc = 0xff00af00;
        else if( iLevel > 3 )
            lc = 0xff00ff00;
        ua_api.Backlit_KeyByName("mBMiddle",EUABLAYER_HUMAN,EUABACKLIT_ON,lc);*/
    }
References UAInputAPI::Backlit_KeyByName(), EUABACKLIT_ON, EUABLAYER_HUMAN, and GetUApi().
Referenced by UpdatePlayer().
Member Data Documentation
m_BacklitActive
bool Backlit::m_BacklitActive private
Definition at line 108 of file backlit.c.
Referenced by HintClear(), HintShow(), KeybindingClear(), KeybindingShow(), LoadingAnim(), MainMenu_OnHide(), MainMenu_OnShow(), OnEnterCar(), OnInit(), OnLeaveCar(), OnSwimmingStart(), OnSwimmingStop(), RefreshVehicleLayout(), and UpdatePlayer().
m_BloodBefore
int Backlit::m_BloodBefore = -1 private
Definition at line 325 of file backlit.c.
Referenced by UpdatePlayer().
m_BloodNew
int Backlit::m_BloodNew = 0 private
Definition at line 328 of file backlit.c.
Referenced by SetBlood(), and UpdatePlayer().
m_CELBefore
bool Backlit::m_CELBefore = false private
Definition at line 388 of file backlit.c.
Referenced by RefreshVehicleLayout().
m_GearBefore
int Backlit::m_GearBefore = 0 private
Definition at line 387 of file backlit.c.
Referenced by RefreshVehicleLayout().
m_HealthBefore
int Backlit::m_HealthBefore = -1 private
Definition at line 324 of file backlit.c.
Referenced by UpdatePlayer().
m_HealthNew
int Backlit::m_HealthNew = 0 private
Definition at line 327 of file backlit.c.
Referenced by SetHealth(), and UpdatePlayer().