DayzKode: AttachmentCategoriesContainer Class Reference
AttachmentCategoriesContainer Class Reference
Private Member Functions
void AttachmentCategoriesContainer (LayoutHolder parent, int sort=-1)
override bool CanDisplayAnyCategory ()
override void Close ()
override void CollapseButtonOnMouseButtonDown (Widget w)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void ExpandCollapseContainer ()
int GetAttachmentCategoriesCount (string config_path)
string GetAttachmentCategory (string config_path_attachment_categories, int i)
SlotsIcon GetCargoSlotsIcon ()
string GetIconName (string config_path_attachment_categories, string attachment_category)
SlotsContainer GetSlotsContainer (int icons_row)
int GetViewIndex (string config_path_attachment_categories, string attachment_category)
void InitGhostSlots ()
void InitIconsContainers ()
override bool IsDisplayable ()
bool IsHeaderActive ()
void LoadAttachmentCategoriesIcon (SlotsContainer items_cont, string icon_name, int slot_number)
void MouseClick (Widget w)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void OnHide ()
override void Open ()
void SetEntity (EntityAI entity)
void SetHeaderName ()
void ShowInSlots (string category, bool show)
override void UpdateInterval ()
override void UpdateRadialIcon ()
Private Attributes
protected SlotsIcon m_CargoSlotsIcon
protected ref map< string, int > m_CategorySlotIndex
protected int m_SlotsCount
Detailed Description
Definition at line 1 of file attachmentcategoriescontainer.c.
Constructor & Destructor Documentation
AttachmentCategoriesContainer()
void AttachmentCategoriesContainer::AttachmentCategoriesContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 7 of file attachmentcategoriescontainer.c.
    {
        m_CategorySlotIndex = new map<string, int>;
    }
References m_CategorySlotIndex.
Member Function Documentation
CanDisplayAnyCategory()
override bool AttachmentCategoriesContainer::CanDisplayAnyCategory () inline private
Definition at line 181 of file attachmentcategoriescontainer.c.
    {
        int count = m_Body.Count();
        AttachmentCategoriesRow row;
        for (int i = m_SlotsCount; i < count; i++)
        {
            if (Class.CastTo(row,m_Body[i]) && m_Entity.CanDisplayAttachmentCategory( row.GetCategoryIdentifier() ))
            {
                return true;
            }
        }
        return super.CanDisplayAnyCategory();
    }
References Class::CastTo(), AttachmentCategoriesRow::GetCategoryIdentifier(), m_Entity, and m_SlotsCount.
Referenced by IsDisplayable(), and UpdateRadialIcon().
Close()
override void AttachmentCategoriesContainer::Close () inline private
Definition at line 493 of file attachmentcategoriescontainer.c.
    {
        //ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), false );
        super.Close();
        SlotsIcon icon = null;
        if (m_CargoSlotsIcon && m_CargoSlotsIcon.GetObject())
        {
            icon = m_CargoSlotsIcon;
        }
        else if (m_SlotIcon && m_SlotIcon.GetObject())
        {
            icon = m_SlotIcon;
        }
        /*else
        {
            Print("Dbg | no object in icon here!");
        }
        */
        SetOpenForSlotIcon(false,icon);
        OnHide();
    }
References SlotsIcon::GetObject(), m_CargoSlotsIcon, and OnHide().
CollapseButtonOnMouseButtonDown()
override void AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 447 of file attachmentcategoriescontainer.c.
    {
        if( !m_Hidden )
        {
            for (int i = 1; i < m_Body.Count(); i++)
            {
                m_Body.Get( i ).OnHide();
                Container c = Container.Cast(m_Body.Get(i));
                if (c)
                {
                    c.Close();
                }
            }
            //m_Hidden = true;
            OnHide();
        }
        else
        {
            //m_Hidden = false;
            OnShow();
        }
        m_Closed = m_Hidden;
        SetCollapsibleHeaderArrowState(m_Hidden);
        if (m_CollapsibleHeader)
        {
            m_CollapsibleHeader.SetHeaderVisible(true);
        }
        UpdateCollapseButtons();
        RecomputeOpenedContainers();
    }
References Container::Close(), CollapsibleContainer::m_CollapsibleHeader, CollapsibleContainer::m_Hidden, OnHide(), CollapsibleContainer::OnShow(), CollapsibleContainer::SetCollapsibleHeaderArrowState(), CollapsibleHeader::SetHeaderVisible(), and CollapsibleContainer::UpdateCollapseButtons().
DraggingOverHeader()
override void AttachmentCategoriesContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 416 of file attachmentcategoriescontainer.c.
    {
        if( w == null )
        {
            return;
        }
        ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget("Render") );
        if(!iw)
        {
            string name = w.GetName();
            name.Replace("PanelWidget", "Render");
            iw = ItemPreviewWidget.Cast( w.FindAnyWidget(name) );
        }
        if(!iw)
        {
            iw = ItemPreviewWidget.Cast( w );
        }
        if( !iw || !iw.GetItem() )
        {
            return;
        }
        ItemManager.GetInstance().ShowSourceDropzone( iw.GetItem() );
        ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
    }
References ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
ExpandCollapseContainer()
override void AttachmentCategoriesContainer::ExpandCollapseContainer () inline private
Definition at line 251 of file attachmentcategoriescontainer.c.
    {
        if (m_OpenedContainers.Count() > m_ActiveIndex)
        {
            //c - container where selected icon is part of
            Container c = Container.Cast(m_OpenedContainers.Get( m_ActiveIndex ));
            //cc - container connected to selected icon (this container will be close/open)
            ClosableContainer cc;
            //icon - selected icon
            SlotsIcon icon = c.GetFocusedSlotsIcon();
            if (icon)
            {
                cc = ClosableContainer.Cast(icon.GetContainer());
            }
            if (cc)
            {
                cc.Toggle();
                RecomputeOpenedContainers();
            }
        }
    }
References SlotsIcon::GetContainer().
GetAttachmentCategoriesCount()
int AttachmentCategoriesContainer::GetAttachmentCategoriesCount (string config_path) inline private
Definition at line 147 of file attachmentcategoriescontainer.c.
    {
        return GetGame().ConfigGetChildrenCount( config_path );
    }
References CGame::ConfigGetChildrenCount(), and GetGame().
Referenced by InitGhostSlots(), and InitIconsContainers().
GetAttachmentCategory()
string AttachmentCategoriesContainer::GetAttachmentCategory (string config_path_attachment_categories, int i) inline private
Definition at line 211 of file attachmentcategoriescontainer.c.
    {
        string attachment_category;
        GetGame().ConfigGetChildName(config_path_attachment_categories, i, attachment_category);
        return attachment_category;
    }
References CGame::ConfigGetChildName(), and GetGame().
Referenced by InitGhostSlots().
GetCargoSlotsIcon()
SlotsIcon AttachmentCategoriesContainer::GetCargoSlotsIcon () inline private
Definition at line 158 of file attachmentcategoriescontainer.c.
    {
        return m_CargoSlotsIcon;
    }
References m_CargoSlotsIcon.
GetIconName()
string AttachmentCategoriesContainer::GetIconName (string config_path_attachment_categories, string attachment_category) inline private
Definition at line 218 of file attachmentcategoriescontainer.c.
    {
        string icon_path = config_path_attachment_categories+ " " + attachment_category + " icon";
        string icon_name;
        GetGame().ConfigGetText(icon_path, icon_name);
        return icon_name;
    }
References CGame::ConfigGetText(), and GetGame().
Referenced by InitGhostSlots().
GetSlotsContainer()
SlotsContainer AttachmentCategoriesContainer::GetSlotsContainer (int icons_row) inline private
Definition at line 152 of file attachmentcategoriescontainer.c.
    {
        AttachmentCategoriesSlotsContainer items_cont = AttachmentCategoriesSlotsContainer.Cast(m_Body.Get(icons_row));
        return items_cont.GetSlotsContainer();
    }
References AttachmentCategoriesSlotsContainer::GetSlotsContainer().
Referenced by InitGhostSlots(), and ShowInSlots().
GetViewIndex()
int AttachmentCategoriesContainer::GetViewIndex (string config_path_attachment_categories, string attachment_category) inline private
Definition at line 226 of file attachmentcategoriescontainer.c.
    {
        string preview_path = config_path_attachment_categories+ " " + attachment_category + " view_index";
        return GetGame().ConfigGetInt( preview_path );;
    }
References CGame::ConfigGetInt(), and GetGame().
InitGhostSlots()
void AttachmentCategoriesContainer::InitGhostSlots () inline private
Definition at line 313 of file attachmentcategoriescontainer.c.
    {
        string type = m_Entity.GetType();
        string config_path_attachment_categories = "CfgVehicles " + type + " GUIInventoryAttachmentsProps";
        int attachments_categories_count = GetAttachmentCategoriesCount( config_path_attachment_categories );
        SlotsContainer items_cont;
        SlotsIcon icon;
        string attachment_category;
        string icon_name;
        for (int i = 0; i < attachments_categories_count; i++)
        {
            items_cont = GetSlotsContainer( i / ITEMS_IN_ROW );
            attachment_category = GetAttachmentCategory( config_path_attachment_categories, i );
            icon_name = GetIconName( config_path_attachment_categories, attachment_category );
            if ( items_cont )
            {
                int slot_number = i % ITEMS_IN_ROW;
                m_CategorySlotIndex.Insert( attachment_category, i );
                icon = items_cont.GetSlotIcon( slot_number );
                icon.GetGhostSlot().SetFlags( WidgetFlags.IGNOREPOINTER );
                LoadAttachmentCategoriesIcon( items_cont, icon_name, slot_number );
                string config = config_path_attachment_categories + " " + attachment_category + " name";
                string name;
                GetGame().ConfigGetText(config,name);
                icon.SetSlotDisplayName(name);
                AttachmentCategoriesRow ar;
                ar = new AttachmentCategoriesRow( this, -1 );
                ar.Init(attachments_categories_count, i, attachment_category, config_path_attachment_categories, m_Entity, m_Body.Count() );
                //Insert(ar);
                ar.SetSlotIcon(icon);
                //icon.SetContainer(ar);
                icon.GetRadialIconPanel().Show( true );
                ar.Open();
                icon.SetContainer(ar);
                Insert(ar);
            }
        }
        if ( m_Entity.GetInventory().GetCargo() )
        {
            items_cont = GetSlotsContainer( m_SlotsCount - 1 );
            if ( items_cont )
            {
                icon = items_cont.GetSlotIcon( attachments_categories_count );
                icon.GetGhostSlot().Show( true );
                icon.GetGhostSlot().LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,m_Entity.ConfigGetString("GUIInventoryCargoIcon")) );
                icon.SetSlotDisplayName(m_Entity.ConfigGetString("GUIInventoryCargoName"));
                icon.GetGhostSlot().SetFlags( WidgetFlags.IGNOREPOINTER );
                icon.GetRadialIconPanel().Show( true );
                icon.GetMainWidget().Show( true );
                ContainerWithCargo iwc = new ContainerWithCargo( this, -1 );
                iwc.Get( 0 ).GetRootWidget().ClearFlags( WidgetFlags.DRAGGABLE );
                iwc.SetEntity( m_Entity, 0, false );
                iwc.SetSlotIcon( icon );
                iwc.Open();
                icon.SetContainer(iwc);
                m_CargoSlotsIcon = icon;
            }
        }
        RecomputeOpenedContainers();
    }
References CGame::ConfigGetText(), ScriptedWidgetEventHandler::Count(), GetAttachmentCategoriesCount(), GetAttachmentCategory(), GetGame(), SlotsIcon::GetGhostSlot(), GetIconName(), SlotsIcon::GetRadialIconPanel(), SlotsContainer::GetSlotIcon(), GetSlotsContainer(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, AttachmentCategoriesRow::Init(), CollapsibleContainer::Insert(), ITEMS_IN_ROW, LoadAttachmentCategoriesIcon(), m_CargoSlotsIcon, m_CategorySlotIndex, m_Entity, m_SlotsCount, name, ClosableContainer::Open(), SlotsIcon::SetContainer(), SlotsIcon::SetSlotDisplayName(), and StaticGUIUtils::VerifyIconImageString().
Referenced by SetEntity().
InitIconsContainers()
void AttachmentCategoriesContainer::InitIconsContainers () inline private
Definition at line 281 of file attachmentcategoriescontainer.c.
    {
        m_SlotsCount = 0;
        string type = m_Entity.GetType();
        string config_path_attachment_categories = "CfgVehicles " + type + " GUIInventoryAttachmentsProps";
        int attachments_categories_count = GetAttachmentCategoriesCount( config_path_attachment_categories );
        int categories_count = attachments_categories_count;
        if (m_Entity.GetInventory().GetCargo())
        {
            categories_count++;
        }
        int row_count = categories_count / ITEMS_IN_ROW;
        if (categories_count % ITEMS_IN_ROW != 0)
        {
            row_count++;
        }
        for ( int i = 0; i < row_count; i++ )
        {
            ref AttachmentCategoriesSlotsContainer items_cont = new AttachmentCategoriesSlotsContainer( this, i );
            m_Body.Insert( items_cont );
            m_OpenedContainers.Insert( items_cont );
            //TODO MW find better way
            if (i == ( row_count - 1 ) && categories_count % ITEMS_IN_ROW != 0)
                items_cont.GetSlotsContainer().SetColumnCount( categories_count % ITEMS_IN_ROW );
            else
                items_cont.GetSlotsContainer().SetColumnCount( ITEMS_IN_ROW );
        }
        m_SlotsCount = row_count;
    }
References GetAttachmentCategoriesCount(), ITEMS_IN_ROW, m_Entity, and m_SlotsCount.
Referenced by SetEntity().
IsDisplayable()
override bool AttachmentCategoriesContainer::IsDisplayable () inline private
Definition at line 34 of file attachmentcategoriescontainer.c.
    {
        return !IsEmpty() || CanDisplayAnyCategory();
    }
References CanDisplayAnyCategory(), and Container::IsEmpty().
Referenced by Open().
IsHeaderActive()
bool AttachmentCategoriesContainer::IsHeaderActive () inline private
Definition at line 276 of file attachmentcategoriescontainer.c.
    {
        return m_CollapsibleHeader.IsActive();
    }
References CollapsibleContainer::m_CollapsibleHeader.
Referenced by UpdateConsoleToolbar().
LoadAttachmentCategoriesIcon()
void AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon (SlotsContainer items_cont, string icon_name, int slot_number) inline private
Definition at line 139 of file attachmentcategoriescontainer.c.
    {
        SlotsIcon icon              = items_cont.GetSlotIcon( slot_number );
        ImageWidget image_widget    = icon.GetGhostSlot();
        image_widget.Show( true );
        image_widget.LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,icon_name) ); //icon_name must be in format "set:<setname> image:<imagename>"
    }
References SlotsIcon::GetGhostSlot(), SlotsContainer::GetSlotIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, and StaticGUIUtils::VerifyIconImageString().
Referenced by InitGhostSlots().
MouseClick()
void AttachmentCategoriesContainer::MouseClick (Widget w) inline private
Definition at line 232 of file attachmentcategoriescontainer.c.
    {
        SlotsIcon slots_icon;
        w.GetUserData(slots_icon);
        ClosableContainer c = ClosableContainer.Cast( slots_icon.GetContainer() );
        if( c )
        {
            if( c.IsOpened() )
            {
                c.Close();
            }
            else
            {
                c.Open();
            }
        }
    }
References ClosableContainer::Close(), SlotsIcon::GetContainer(), ClosableContainer::IsOpened(), and ClosableContainer::Open().
OnDropReceivedFromHeader()
override void AttachmentCategoriesContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 391 of file attachmentcategoriescontainer.c.
    {
        ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget("Render") );
        if(!iw)
        {
            string name = w.GetName();
            name.Replace("PanelWidget", "Render");
            iw = ItemPreviewWidget.Cast( w.FindAnyWidget(name) );
        }
        if(!iw)
        {
            iw = ItemPreviewWidget.Cast( w );
        }
        if( !iw.GetItem() )
            return;
        if( m_Entity.GetInventory().CanAddAttachment( iw.GetItem() ) && iw.GetItem().GetInventory().CanRemoveEntity() )
        {
            GetGame().GetPlayer().PredictiveTakeEntityToTargetAttachment( m_Entity, iw.GetItem() );
        }
        else if( m_Entity.GetInventory().CanAddEntityToInventory( iw.GetItem() ) && iw.GetItem().GetInventory().CanRemoveEntity() )
        {
            GetGame().GetPlayer().PredictiveTakeEntityToTargetInventory( m_Entity, FindInventoryLocationType.ANY, iw.GetItem() );
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), m_Entity, name, and string::Replace().
OnHide()
override void AttachmentCategoriesContainer::OnHide () inline private
Definition at line 517 of file attachmentcategoriescontainer.c.
    {
        if (m_CollapsibleHeader)
        {
            bool b1 = !m_SlotIcon && !m_CargoSlotsIcon;
            bool b2 = (!m_SlotIcon || !m_SlotIcon.IsVisible()) && m_CargoSlotsIcon && m_CargoSlotsIcon.IsVisible();
            m_CollapsibleHeader.SetHeaderVisible(b1 || b2);
        }
        super.OnHide();
    }
References SlotsIcon::IsVisible(), m_CargoSlotsIcon, CollapsibleContainer::m_CollapsibleHeader, and CollapsibleHeader::SetHeaderVisible().
Referenced by Close(), and CollapseButtonOnMouseButtonDown().
Open()
override void AttachmentCategoriesContainer::Open () inline private
Definition at line 481 of file attachmentcategoriescontainer.c.
    {
        if( IsDisplayable() )
        {
            super.Open();
            //ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), true );
            SetOpenForSlotIcon(true);
            OnShow();
            //m_Parent.m_Parent.Refresh();
        }
    }
References IsDisplayable(), and CollapsibleContainer::OnShow().
SetEntity()
void AttachmentCategoriesContainer::SetEntity (EntityAI entity) inline private
Definition at line 12 of file attachmentcategoriescontainer.c.
    {
        m_Entity = entity;
        InitIconsContainers();
        m_MainWidget = m_RootWidget.FindAnyWidget( "body" );
        WidgetEventHandler.GetInstance().RegisterOnChildAdd( m_MainWidget, this, "OnChildAdd" );
        WidgetEventHandler.GetInstance().RegisterOnChildRemove( m_MainWidget, this, "OnChildRemove" );
        InitGhostSlots();
        ( Container.Cast( m_Parent ) ).m_Body.Insert( this );
        m_Parent.Refresh();
        SetHeaderName();
        RecomputeOpenedContainers();
    }
References WidgetEventHandler::GetInstance(), InitGhostSlots(), InitIconsContainers(), m_Entity, m_Parent, m_RootWidget, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), and SetHeaderName().
Referenced by VicinityContainer::UpdateInterval().
SetHeaderName()
void AttachmentCategoriesContainer::SetHeaderName () inline private
Definition at line 29 of file attachmentcategoriescontainer.c.
    {
        m_CollapsibleHeader.SetName( m_Entity.GetDisplayName() );
    }
References CollapsibleContainer::m_CollapsibleHeader, m_Entity, and Header::SetName().
Referenced by SetEntity().
ShowInSlots()
void AttachmentCategoriesContainer::ShowInSlots (string category, bool show) inline private
Definition at line 163 of file attachmentcategoriescontainer.c.
    {
        int index                       = m_CategorySlotIndex.Get( category );
        int slot_number                 = index % ITEMS_IN_ROW;
        SlotsContainer items_cont       = GetSlotsContainer( index / ITEMS_IN_ROW );
        if( items_cont )
        {
            Widget icon_widget          = items_cont.GetSlotIcon( slot_number ).GetMainWidget();
            if( icon_widget )
                icon_widget.Show( show );
            icon_widget.GetParent().Update();
            icon_widget.GetParent().GetParent().Update();
            icon_widget.GetParent().GetParent().GetParent().Update();
        }
    }
References SlotsContainer::GetSlotIcon(), GetSlotsContainer(), ITEMS_IN_ROW, and m_CategorySlotIndex.
Referenced by UpdateInterval().
UpdateInterval()
override void AttachmentCategoriesContainer::UpdateInterval () inline private
Definition at line 39 of file attachmentcategoriescontainer.c.
    {
        if( m_Entity )
        {
            if( m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || m_Hidden )
            {
                if( m_Body.Count() > 0 && !m_Hidden )
                    m_CollapsibleHeader.OnHide();
                HideContent();
                GetMainWidget().Show( false );
            }
            else
            {
                if( m_Body.Count() > 0 && !m_Hidden )
                {
                    if( m_Body.Count() > 0 && !m_Hidden )
                        m_CollapsibleHeader.OnShow();
                    int i;
                    for (i = m_SlotsCount; i < m_Body.Count(); i++)
                    {
                        AttachmentCategoriesRow row = AttachmentCategoriesRow.Cast( m_Body[i] );
                        if (row)
{
                            if (m_Entity.CanDisplayAttachmentCategory( row.GetCategoryIdentifier() ))
{
                                if ( row.IsDisplayable() )
{
                                    ShowInSlots( row.GetCategoryIdentifier(), true );
                                    if (!row.IsVisible())
{
                                        row.OnShow();
                                    }
                                }
                                else
{
                                    ShowInSlots( row.GetCategoryIdentifier(), false );
                                    if (row.IsVisible())
{
                                        row.OnHide();
                                    }
                                }
                            }
                            else
{
                                ShowInSlots( row.GetCategoryIdentifier(), false );
                                if (row.IsVisible())
{
                                    row.OnHide();
                                }
                            }
                            row.UpdateInterval();
                        }
                        else
{
                            ContainerWithCargo cargo = ContainerWithCargo.Cast(m_Body[i]);
                            if (cargo)
{
                                if (m_Entity.CanDisplayCargo())
{
                                    m_CargoSlotsIcon.m_MainWidget.Show(true);
                                    if (!cargo.IsVisible())
{
                                        cargo.OnShow();
                                    }
                                }
                                else
{
                                    m_CargoSlotsIcon.m_MainWidget.Show(false);
                                    if (cargo.IsVisible())
{
                                        cargo.OnHide();
                                    }
                                }
                                cargo.UpdateInterval();
                            }
                            RecomputeOpenedContainers();
                        }
                    }
                    for ( i = 0; i < m_SlotsCount; i++)
                    {
                        AttachmentCategoriesSlotsContainer slots = AttachmentCategoriesSlotsContainer.Cast( m_Body[i] );
{
                            if (slots.IsDisplayable())
{
                                slots.OnShow();
                            }
                            else
{
                                slots.OnHide();
                            }
                        }
                    }
                }
                GetMainWidget().Show( true );
            }
        }
    }
References AttachmentCategoriesRow::GetCategoryIdentifier(), AttachmentCategoriesSlotsContainer::IsDisplayable(), ClosableContainer::IsDisplayable(), m_CargoSlotsIcon, CollapsibleContainer::m_CollapsibleHeader, m_Entity, CollapsibleContainer::m_Hidden, m_SlotsCount, Container::OnShow(), ShowInSlots(), SlotsIcon::UpdateInterval(), and AttachmentCategoriesRow::UpdateInterval().
UpdateRadialIcon()
override void AttachmentCategoriesContainer::UpdateRadialIcon () inline private
Definition at line 195 of file attachmentcategoriescontainer.c.
    {
        if ( m_SlotIcon )
        {
            if (m_Entity.CanDisplayCargo() || CanDisplayAnyCategory())
            {
                m_SlotIcon.GetRadialIconPanel().Show( true );
                SetOpenForSlotIcon(!m_Hidden);
            }
            else
            {
                m_SlotIcon.GetRadialIconPanel().Show( false );
            }
        }
    }
References CanDisplayAnyCategory(), m_Entity, and CollapsibleContainer::m_Hidden.
Member Data Documentation
m_CargoSlotsIcon
protected SlotsIcon AttachmentCategoriesContainer::m_CargoSlotsIcon private
Definition at line 5 of file attachmentcategoriescontainer.c.
Referenced by Close(), GetCargoSlotsIcon(), InitGhostSlots(), OnHide(), and UpdateInterval().
m_CategorySlotIndex
protected ref map<string, int> AttachmentCategoriesContainer::m_CategorySlotIndex private
Definition at line 3 of file attachmentcategoriescontainer.c.
Referenced by AttachmentCategoriesContainer(), InitGhostSlots(), and ShowInSlots().
m_SlotsCount
protected int AttachmentCategoriesContainer::m_SlotsCount private
Definition at line 4 of file attachmentcategoriescontainer.c.
Referenced by CanDisplayAnyCategory(), InitGhostSlots(), InitIconsContainers(), and UpdateInterval().