DayzKode: ReplaceWithNewReciveCargoLambda Class Reference
ReplaceWithNewReciveCargoLambda Class Reference
Private Member Functions
override void OnSuccess (EntityAI new_item)
void ReplaceWithNewReciveCargoLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI item_to_cargo)
Private Attributes
protected EntityAI m_ItemToCargo
Detailed Description
Definition at line 128 of file actionpackgift.c.
Constructor & Destructor Documentation
ReplaceWithNewReciveCargoLambda()
void ReplaceWithNewReciveCargoLambda::ReplaceWithNewReciveCargoLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI item_to_cargo) inline private
Definition at line 131 of file actionpackgift.c.
    {
        m_ItemToCargo = item_to_cargo;
    }
References m_ItemToCargo.
Member Function Documentation
OnSuccess()
override void ReplaceWithNewReciveCargoLambda::OnSuccess (EntityAI new_item) inline private
Definition at line 136 of file actionpackgift.c.
    {
        super.OnSuccess(new_item);
        InventoryLocation src = new InventoryLocation;
        m_ItemToCargo.GetInventory().GetCurrentInventoryLocation(src);
        InventoryLocation dst = new InventoryLocation;
        dst.SetCargo(new_item, m_ItemToCargo, 0,0,0,false);
        if ( dst.IsValid() )
        {
            if(GetGame().IsDedicatedServer())
                m_Player.ServerTakeToDst(src,dst);
            else
                m_Player.LocalTakeToDst(src,dst);
        }
    }
References GetGame(), InventoryLocation::IsValid(), m_ItemToCargo, m_Player, and InventoryLocation::SetCargo().
Member Data Documentation
m_ItemToCargo
protected EntityAI ReplaceWithNewReciveCargoLambda::m_ItemToCargo private
Definition at line 130 of file actionpackgift.c.
Referenced by OnSuccess(), and ReplaceWithNewReciveCargoLambda().