DayzKode: ActionWritePaperCB Class Reference
ActionWritePaperCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void EndActionComponent ()
override void OnStateChange (int pOldState, int pCurrentState)
Detailed Description
Definition at line 1 of file actionwritepaper.c.
Member Function Documentation
CreateActionComponent()
override void ActionWritePaperCB::CreateActionComponent () inline private
Definition at line 3 of file actionwritepaper.c.
    {
        EnableStateChangeCallback();
        m_ActionData.m_ActionComponent = new CAContinuousTime(-1.0);
    }
References EnableStateChangeCallback(), ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
EndActionComponent()
override void ActionWritePaperCB::EndActionComponent () inline private
Definition at line 9 of file actionwritepaper.c.
    {
    }
OnStateChange()
override void ActionWritePaperCB::OnStateChange (int pOldState, int pCurrentState) inline private
Definition at line 13 of file actionwritepaper.c.
    {
        if (pCurrentState == STATE_NONE && (!GetGame().IsDedicatedServer()))
        {
            if (GetGame().GetUIManager() && GetGame().GetUIManager().IsMenuOpen(MENU_NOTE))
                GetGame().GetUIManager().FindMenu(MENU_NOTE).Close();
        }
        else if (pCurrentState == STATE_LOOP_LOOP && pOldState != STATE_LOOP_LOOP && (!GetGame().IsMultiplayer() || GetGame().IsServer()))
        {
            ItemBase paper_item;
            if (m_ActionData.m_MainItem.ConfigIsExisting("writingColor"))
            {
                paper_item = ItemBase.Cast(m_ActionData.m_Target.GetObject());
            }
            else
            {
                paper_item = ItemBase.Cast(m_ActionData.m_MainItem);
            }
            Param1<string> text = new Param1<string>(paper_item.GetWrittenNoteData().GetNoteText());
            paper_item.RPCSingleParam(ERPCs.RPC_WRITE_NOTE, text, true,m_ActionData.m_Player.GetIdentity());
        }
    }
References UIManager::FindMenu(), GetGame(), WrittenNoteData::GetNoteText(), CGame::GetUIManager(), ItemBase::GetWrittenNoteData(), ActionBaseCB::m_ActionData, ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, MENU_NOTE, STATE_LOOP_LOOP, and STATE_NONE.