DayzKode: CAContinuousRepeatStartEngine Class Reference
CAContinuousRepeatStartEngine Class Reference
Private Member Functions
void CAContinuousRepeatStartEngine (float time_to_complete_action)
override int Execute (ActionData action_data)
Detailed Description
Definition at line 1 of file cacontinuousrepeatstartengine.c.
Constructor & Destructor Documentation
CAContinuousRepeatStartEngine()
void CAContinuousRepeatStartEngine::CAContinuousRepeatStartEngine (float time_to_complete_action) inline private
Definition at line 3 of file cacontinuousrepeatstartengine.c.
    {
        m_DefaultTimeToComplete = time_to_complete_action;
    }
References CAContinuousRepeat::m_DefaultTimeToComplete.
Member Function Documentation
Execute()
override int CAContinuousRepeatStartEngine::Execute (ActionData action_data) inline private
Definition at line 8 of file cacontinuousrepeatstartengine.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if( vehCommand )
        {
            Transport trans = vehCommand.GetTransport();
            if ( trans )
            {
                Car car;
                if ( Class.CastTo(car, trans) && car.EngineIsOn() )
                {
                    return UA_FINISHED;
                }
            }
        }
        if ( m_TimeElpased < m_TimeToComplete )
        {
            m_TimeElpased += action_data.m_Player.GetDeltaT();
            m_TotalTimeElpased += action_data.m_Player.GetDeltaT();
            return UA_PROCESSING;
        }
        else
        {
            m_SpentUnits.param1 = m_TimeElpased;
            SetACData(m_SpentUnits);
            m_TimeElpased = 0;
            OnCompletePogress(action_data);
            return UA_PROCESSING;
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), ActionData::m_Player, CAContinuousRepeat::m_SpentUnits, CAContinuousRepeat::m_TimeElpased, CAContinuousRepeat::m_TimeToComplete, CAContinuousRepeat::m_TotalTimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.