DayzKode: BitArray Class Reference
BitArray Class Reference
Static Private Member Functions
static bool AddIDToMask (array< int > bit_array, int id)
static array< int > CreateArrayWithID (int id)
static array< int > CreateMaskArray (int size)
Creates an array which will be able to accomodate 'size' number of unique IDs.
static int GetBitCount (array< int > bit_array)
Returns number of bits this array can hold.
static int IDToIndex (int id)
static int IDToMask (int id)
static int IDToNumOfItems (int id)
Returns number of INTs required to hold this ID minus 1(ie for 32, the result is 0, for 33, the result is 1)
static bool IsMaskContainID (array< int > bit_array, int id)
Detailed Description
Definition at line 5 of file bitarray.c.
Member Function Documentation
AddIDToMask()
static bool BitArray::AddIDToMask (array< int > bit_array, int id) inline static private
Definition at line 85 of file bitarray.c.
    {
        if( BitArray.IDToNumOfItems(id) > bit_array.Count() )
        {
            return false;
        }
        else
        {
            int num_of_items    = BitArray.IDToNumOfItems(id);
            int bit             = BitArray.IDToMask(id);
            int new_mask        = bit_array.Get(num_of_items) | bit;
            bit_array.Set(num_of_items, new_mask);
            return true;
        }
    }
References IDToMask(), and IDToNumOfItems().
CreateArrayWithID()
static array< int > BitArray::CreateArrayWithID (int id) inline static private
Definition at line 47 of file bitarray.c.
    {
        int m_NumOfItems    = BitArray.IDToNumOfItems(id);//TODO: check for too big id
        int bit             = BitArray.IDToMask(id);
        array<int> bit_array = new array<int>;
        for(int i = 0;i <= m_NumOfItems;i++)
        {
            bit_array.Insert(0);
        }
        bit_array.Set(m_NumOfItems, bit);
        return bit_array;
    }
References IDToMask(), and IDToNumOfItems().
CreateMaskArray()
static array< int > BitArray::CreateMaskArray (int size) inline static private
Creates an array which will be able to accomodate 'size' number of unique IDs.
Definition at line 21 of file bitarray.c.
    {
        int m_NumOfItems        = BitArray.IDToNumOfItems(size);
        array<int> bit_array    = new array<int>;
        for(int i = 0;i <= m_NumOfItems;i++)
        {
            bit_array.Insert(0);
        }
        return bit_array;
    }
References IDToNumOfItems().
GetBitCount()
static int BitArray::GetBitCount (array< int > bit_array) inline static private
Returns number of bits this array can hold.
Definition at line 34 of file bitarray.c.
    {
        return ( (bit_array.Count() ) * BIT_INT_SIZE );
    }
References BIT_INT_SIZE.
IDToIndex()
static int BitArray::IDToIndex (int id) inline static private
Definition at line 7 of file bitarray.c.
    {
        int m_NumOfItems = BitArray.IDToNumOfItems(id);
        int index   = (id - (m_NumOfItems * BIT_INT_SIZE)) - 1;
        return index;
    }
References BIT_INT_SIZE, and IDToNumOfItems().
Referenced by IDToMask().
IDToMask()
static int BitArray::IDToMask (int id) inline static private
Definition at line 14 of file bitarray.c.
    {
        int index           = BitArray.IDToIndex(id);
        int bit             = 1 << index;
        return bit;
    }
References IDToIndex().
Referenced by AddIDToMask(), CreateArrayWithID(), and IsMaskContainID().
IDToNumOfItems()
static int BitArray::IDToNumOfItems (int id) inline static private
Returns number of INTs required to hold this ID minus 1(ie for 32, the result is 0, for 33, the result is 1)
Definition at line 40 of file bitarray.c.
    {
        int m_NumOfItems = id / BIT_INT_SIZE;
        if( id % BIT_INT_SIZE == 0 ) m_NumOfItems--;
        return m_NumOfItems;
    }
References BIT_INT_SIZE.
Referenced by AddIDToMask(), CreateArrayWithID(), CreateMaskArray(), IDToIndex(), and IsMaskContainID().
IsMaskContainID()
static bool BitArray::IsMaskContainID (array< int > bit_array, int id) inline static private
Definition at line 62 of file bitarray.c.
    {
        if( BitArray.IDToNumOfItems( id ) > bit_array.Count() )
        {
            return false;
        }
        else
        {
            int index_mask      =  BitArray.IDToMask(id);
            int num_of_items    = BitArray.IDToNumOfItems(id);
            int array_mask      = bit_array.Get( num_of_items );
            if ( index_mask & array_mask )
            {
                return true;
            }
            else
            {
                return false;
            }
        }
    }
References IDToMask(), and IDToNumOfItems().