DayzKode: Dispatcher Class Reference
Dispatcher Class Reference
Private Member Functions
Param CallMethod (CallID call_id, Param params)
override Param CallMethod (CallID call_id, Param params)
private void MissionGameplayHideInventory ()
private void SceneEditorCommand (Param params)
private void ScriptConsoleAddPrint (Param1< string > p)
private Param ScriptConsoleGetSelectedItem ()
private void ScriptConsoleHistoryBack ()
private void ScriptConsoleHistoryForward ()
private void SendLogAtClient (Param1< string > p)
Detailed Description
Definition at line 13 of file dispatcher.c.
Member Function Documentation
CallMethod() [1/2]
Param Dispatcher::CallMethod (CallID call_id, Param params) inline private
Definition at line 15 of file dispatcher.c.
{}
Referenced by CallMethod(), and PluginDayzPlayerDebug_Weapons::OnClick().
CallMethod() [2/2]
override Param Dispatcher::CallMethod (CallID call_id, Param params) inline private
Definition at line 75 of file dispatchercaller.c.
    {
        switch(call_id)
        {
        case CALL_ID_SEND_LOG:
            SendLogAtClient(Param1<string>.Cast( params ));
            break;
        case CALL_ID_SCR_CNSL_ADD_PRINT:
            ScriptConsoleAddPrint(Param1<string>.Cast( params ));
            break;
        case CALL_ID_SCR_CNSL_HISTORY_BACK:
            ScriptConsoleHistoryBack();
            break;
        case CALL_ID_SCR_CNSL_HISTORY_NEXT:
            ScriptConsoleHistoryForward();
            break;
        case CALL_ID_SCENE_EDITOR_COMMAND:
            SceneEditorCommand( params );
            break;
        case CALL_ID_HIDE_INVENTORY:
            MissionGameplayHideInventory();
            break;
        case CALL_ID_SCR_CNSL_GETSELECTEDITEM:
            return new Param1<string>(ScriptConsole.GetLastSelectedObject());
        }
        return null;
    }
References CALL_ID_HIDE_INVENTORY, CALL_ID_SCENE_EDITOR_COMMAND, CALL_ID_SCR_CNSL_ADD_PRINT, CALL_ID_SCR_CNSL_GETSELECTEDITEM, CALL_ID_SCR_CNSL_HISTORY_BACK, CALL_ID_SCR_CNSL_HISTORY_NEXT, CALL_ID_SEND_LOG, MissionGameplayHideInventory(), SceneEditorCommand(), ScriptConsoleAddPrint(), ScriptConsoleHistoryBack(), ScriptConsoleHistoryForward(), and SendLogAtClient().
MissionGameplayHideInventory()
private void Dispatcher::MissionGameplayHideInventory () inline private
Definition at line 66 of file dispatchercaller.c.
    {
        MissionGameplay mission = MissionGameplay.Cast( GetGame().GetMission() );
        if ( mission )
        {
            mission.HideInventory();
        }
    }
References GetGame(), Mission::HideInventory(), and mission.
Referenced by CallMethod().
SceneEditorCommand()
private void Dispatcher::SceneEditorCommand (Param params) inline private
Definition at line 56 of file dispatchercaller.c.
    {
        UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
        if ( ui_menu && ui_menu.GetID() == MENU_SCENE_EDITOR )
        {
            SceneEditorMenu editor_menu = SceneEditorMenu.Cast( ui_menu );
            editor_menu.SceneEditorCommand( params );
        }
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), MENU_SCENE_EDITOR, and UIScriptedMenu::SceneEditorCommand().
Referenced by CallMethod().
ScriptConsoleAddPrint()
private void Dispatcher::ScriptConsoleAddPrint (Param1< string > p) inline private
Definition at line 13 of file dispatchercaller.c.
    {
        UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
        if ( ui_menu.GetID() == MENU_SCRIPTCONSOLE )
        {
            ScriptConsole scripted_console = ScriptConsole.Cast( ui_menu );
            scripted_console.Add(p.param1);
        }
    }
References UIScriptedMenu::Add(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
ScriptConsoleGetSelectedItem()
private Param Dispatcher::ScriptConsoleGetSelectedItem () inline private
Definition at line 43 of file dispatchercaller.c.
    {
        UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
        if ( ui_menu.GetID() == MENU_SCRIPTCONSOLE )
        {
            ScriptConsole scripted_console = ScriptConsole.Cast( ui_menu );
            scripted_console.GetCurrentItemName();
        }
        return null;
    }
References UIScriptedMenu::GetCurrentItemName(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
ScriptConsoleHistoryBack()
private void Dispatcher::ScriptConsoleHistoryBack () inline private
Definition at line 23 of file dispatchercaller.c.
    {
        UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
        if ( ui_menu.GetID() == MENU_SCRIPTCONSOLE )
        {
            ScriptConsole scripted_console = ScriptConsole.Cast( ui_menu );
            scripted_console.HistoryBack();
        }
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::HistoryBack(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
ScriptConsoleHistoryForward()
private void Dispatcher::ScriptConsoleHistoryForward () inline private
Definition at line 33 of file dispatchercaller.c.
    {
        UIScriptedMenu ui_menu = GetGame().GetUIManager().GetMenu();
        if ( ui_menu.GetID() == MENU_SCRIPTCONSOLE )
        {
            ScriptConsole scripted_console = ScriptConsole.Cast( ui_menu );
            scripted_console.HistoryForward();
        }
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::HistoryForward(), and MENU_SCRIPTCONSOLE.
Referenced by CallMethod().
SendLogAtClient()
private void Dispatcher::SendLogAtClient (Param1< string > p) inline private
Definition at line 3 of file dispatchercaller.c.
    {
        PluginDeveloper m = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
        if ( m != NULL )
        {
            m.SendServerLogToClient(p.param1);
        }
    }
References GetPlugin().
Referenced by CallMethod().