DayzKode: AreaDamageTriggerBase Class Reference
AreaDamageTriggerBase Class Reference
Private Member Functions
void AreaDamageTrigger ()
override void EOnTouch (IEntity other, int extra)
override void OnEnter (Object obj)
override void OnLeave (Object obj)
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
override void SetAreaDamageManager (AreaDamageManager adType)
void SetAreaDamageType (AreaDamageBase adType)
override void SetExtents (vector mins, vector maxs)
override protected void UpdateInsiders (int timeout)
Private Attributes
protected ref AreaDamageBase m_AreaDamageType
protected vector m_ExtentMax
protected vector m_ExtentMin
protected float m_InnerDistance
protected int m_TriggerUpdateMs
Detailed Description
Definition at line 1 of file areadamagetriggerdirect.c.
Member Function Documentation
AreaDamageTrigger()
void AreaDamageTriggerBase::AreaDamageTrigger () inline private
Definition at line 15 of file areadamagetrigger.c.
    {
        // Backwards compat, revert the flags back to what they used to be
        ClearEventMask(EntityEvent.ENTER | EntityEvent.LEAVE);
        SetEventMask(EntityEvent.TOUCH);
        m_AreaDamageType = null;
        m_ExtentMin = vector.Zero;
        m_ExtentMax = vector.Zero;
        m_InnerDistance = 0;
        m_TriggerUpdateMs = 100;
    }
References m_ExtentMax, m_ExtentMin, and vector::Zero.
EOnTouch()
override void AreaDamageTriggerBase::EOnTouch (IEntity other, int extra) inline private
Definition at line 31 of file areadamagetrigger.c.
    {
        Object obj;
        if (Class.CastTo(obj, other))
            AddInsider(obj);
    }
References AddInsider(), and Class::CastTo().
OnEnter()
override void AreaDamageTriggerBase::OnEnter (Object obj) inline private
Definition at line 62 of file areadamagetrigger.c.
    {
        super.OnEnter( obj );
        if ( GetGame().IsServer() && m_AreaDamageType )
             m_AreaDamageType.OnEnter( obj );
    }
References GetGame().
OnLeave()
override void AreaDamageTriggerBase::OnLeave (Object obj) inline private
Definition at line 70 of file areadamagetrigger.c.
    {
        super.OnLeave( obj );
        if ( GetGame().IsServer() && m_AreaDamageType )
             m_AreaDamageType.OnLeave( obj );
    }
References GetGame().
Referenced by UpdateInsiders().
OnStayServerEvent()
override void AreaDamageTriggerBase::OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 3 of file areadamagetriggerdirect.c.
    {
        super.OnStayServerEvent(insider, deltaTime);
        if (m_AreaDamageManager)
            m_AreaDamageManager.OnEvaluateDamage(insider, deltaTime);
    }
References m_AreaDamageManager.
SetAreaDamageManager()
override void AreaDamageTriggerBase::SetAreaDamageManager (AreaDamageManager adType) inline private
Definition at line 48 of file areadamagetrigger.c.
    {
        super.SetAreaDamageManager( adType );
        m_AreaDamageType = AreaDamageBase.Cast(adType);
    }
Referenced by CreateDamageTriggerEx().
SetAreaDamageType()
void AreaDamageTriggerBase::SetAreaDamageType (AreaDamageBase adType) inline private
Definition at line 55 of file areadamagetrigger.c.
    {
        super.SetAreaDamageManager( adType );
        m_AreaDamageType = adType;
    }
SetExtents()
override void AreaDamageTriggerBase::SetExtents (vector mins, vector maxs) inline private
Definition at line 38 of file areadamagetrigger.c.
    {
        m_ExtentMax = maxs;
        m_ExtentMin = mins;
        m_InnerDistance = (GetRadius(m_ExtentMin, m_ExtentMax) * 0.5) + 0.2;
        super.SetExtents(mins, maxs);
    }
References GetRadius(), m_ExtentMax, and m_ExtentMin.
Referenced by CreateDamageTriggerEx(), and SetExtents().
UpdateInsiders()
override protected void AreaDamageTriggerBase::UpdateInsiders (int timeout) inline private
DEBUG
Definition at line 78 of file areadamagetrigger.c.
    {
        if ( GetGame().IsServer() )
        {
            for (int n = 0; n < m_insiders.Count(); )
            {
                TriggerInsider ins = m_insiders.Get(n);
                if ( ins.GetObject() == null )
                {
                    //object has been deleted. Remove it
                    m_insiders.Remove(n);
                    continue;
                }
                Object insObj = ins.GetObject();
                if ( insObj && ( !insObj.IsAlive() || vector.DistanceSq(insObj.GetPosition(), GetPosition()) > (m_InnerDistance * m_InnerDistance) ) )
                {
                    int timeDiff = g_Game.GetTime() - ins.timeStamp;
                    if (timeDiff > 500)
                    {
                        //object left. Remove it
                        OnLeave(ins.GetObject());
                        m_insiders.Remove(n);
                        continue;
                    }
                    else
                    {
                        //Print("" + this + " :: " + insObj + " :: " + timeDiff);
                    }
                }
                ++n;
            }
            #ifdef DEVELOPER
            DebugSendDmgTrigger();
            #endif
        }
    }
References vector::DistanceSq(), g_Game, GetGame(), TriggerInsider::GetObject(), GetPosition, OnLeave(), and TriggerInsider::timeStamp.
Member Data Documentation
m_AreaDamageType
protected ref AreaDamageBase AreaDamageTriggerBase::m_AreaDamageType private
Definition at line 7 of file areadamagetrigger.c.
m_ExtentMax
protected vector AreaDamageTriggerBase::m_ExtentMax private
Definition at line 10 of file areadamagetrigger.c.
m_ExtentMin
protected vector AreaDamageTriggerBase::m_ExtentMin private
Definition at line 9 of file areadamagetrigger.c.
m_InnerDistance
protected float AreaDamageTriggerBase::m_InnerDistance private
Definition at line 11 of file areadamagetrigger.c.
m_TriggerUpdateMs
protected int AreaDamageTriggerBase::m_TriggerUpdateMs private
Definition at line 13 of file areadamagetrigger.c.