DayzKode: InventoryItemSuper Class Reference
InventoryItemSuper Class Reference
Private Member Functions
bool AllowsDOF ()
returns 'true' for non-magnifying optics
proto native bool AttachMagazine (int muzzleIndex, Magazine mag)
perform attachment of a magazine to weapon
proto native bool CanAttachMagazine (int muzzleIndex, Magazine mag)
query if a magazine can be attached to weapon
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
proto native bool CanChamberFromMag (int muzzleIndex, Magazine mag)
query if a bullet from magazine can be loaded into chamber
override bool CanDetachAttachment (EntityAI parent)
proto native bool CanFire (int muzzleIndex)
query whether the weapon can be fired or not
override bool CanIgniteItem (EntityAI ignite_target=NULL)
proto native bool CanSpeak ()
proto native bool CreateRound (int muzzleIndex)
override bool DescriptionOverride (out string output)
override bool DisplayNameRuinAttach ()
override bool DisplayNameRuinAttach ()
override bool DisplayNameRuinAttach ()
proto native bool DryDryFire (int muzzleIndex)
proto native bool DryFire (int muzzleIndex)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEKilled (Object killer)
override bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
proto native void EffectBulletHide (int muzzleIndex)
reset effect cartridge in weapon
proto native void EffectBulletShow (int muzzleIndex, float dmg, string type)
push effect cartridge to Weapon
proto native bool EjectCasing (int muzzleIndex)
ejects casing from chamber
proto native void EnableBroadcast (bool state)
proto native void EnableReceive (bool state)
proto native bool EnterOptics ()
switches to optics mode if possible
proto native bool EnterOptics ()
proto native bool ExitOptics ()
switches out of optics mode (if possible)
proto native bool ExitOptics ()
proto native bool Fire (int muzzleIndex, vector pos, vector dir, vector speed)
proto native bool FlashlightOff ()
attempt to turn off flashlight
proto native bool FlashlightOn ()
attempt to turn on flashlight
proto native UnderSlugLauncher GetAttachedLauncher ()
proto native ItemOptics GetAttachedOptics ()
proto native ItemSuppressor GetAttachedSuppressor ()
proto native void GetCameraPoint (int muzzleIndex, out vector pos, out vector dir)
proto native void GetCameraPoint (out vector pos, out vector dir)
proto bool GetCartridgeInfo (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
get info about the cartridge in the chamber of a muzzle
proto native owned string GetChamberAmmoTypeName (int muzzleIndex)
proto native owned string GetChamberedCartridgeMagazineTypeName (int muzzleIndex)
query the type of magazine the cartridge can be unloaded to
proto native int GetCurrentMode (int muzzleIndex)
proto native bool GetCurrentModeAutoFire (int muzzleIndex)
proto native int GetCurrentModeBurstSize (int muzzleIndex)
proto native owned string GetCurrentModeName (int muzzleIndex)
proto native int GetCurrentMuzzle ()
int GetCurrentNVType ()
int GetCurrentOpticMode ()
proto native float GetCurrentStepFOV ()
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
proto native float GetCurrentZeroing (int muzzleIndex=0)
returns currently used value of zeroing in config array of weapon or attached optics
proto native int GetInternalMagazineCartridgeCount (int muzzleIndex)
proto bool GetInternalMagazineCartridgeInfo (int muzzleIndex, int cartridgeIndex, out float ammoDamage, out string ammoTypeName)
get info about the cartridge in the internal magazine of a muzzle
proto native int GetInternalMagazineMaxCartridgeCount (int muzzleIndex)
proto native Magazine GetMagazine (int muzzleIndex)
proto native int GetMagazineTypeCount (int muzzleIndex)
bool GetMapStateAnimation ()
array< ref MapMarker > GetMarkerArray ()
proto native owned string GetMaxMagazineTypeName (int muzzleIndex)
override int GetMeleeTargetType ()
override int GetMeleeTargetType ()
proto native int GetMuzzleCount ()
proto native int GetMuzzleModeCount (int muzzleIndex)
float GetNearPlaneValue ()
ref array< float > GetOpticsDOF ()
float GetOpticsPPBlur ()
ref array< float > GetOpticsPPLens ()
ref array< float > GetOpticsPPMask ()
proto native float GetRadius ()
Returns current wheel radius.
proto native owned string GetRandomChamberableAmmoTypeName (int muzzleIndex)
proto native owned string GetRandomMagazineTypeName (int muzzleIndex)
proto native float GetReloadTime (int muzzleIndex)
defines time from one shot to another
proto native int GetSlotFromMuzzleIndex (int muzzleIndex)
conversion muzzleIndex -> slotId
proto native int GetStepFOVCount ()
returns number of configured steps
proto native int GetStepFOVIndex ()
returns index of currently used value in 'discretefov' config array
proto native int GetStepZeroing ()
returns position of currently used value in zeroing config array
proto native int GetStepZeroing (int muzzleIndex=0)
proto native int GetStepZoom ()
returns position of currently used value in zoom config array
proto native int GetTotalCartridgeCount (int muzzleIndex)
proto native int GetTotalMaxCartridgeCount (int muzzleIndex)
proto native float GetTunedFrequency ()
proto native int GetTunedFrequencyIndex ()
proto native float GetWidth ()
Returns wheel width.
proto native float GetZeroingDistanceZoomMax ()
Gets Zeroing distance at opticsZoomMax.
proto native float GetZeroingDistanceZoomMax (int muzzleIndex)
proto native float GetZeroingDistanceZoomMin ()
Gets Zeroing distance at opticsZoomMin.
proto native float GetZeroingDistanceZoomMin (int muzzleIndex)
proto native float GetZoom ()
returns current percentage of zoom
proto native float GetZoomInit ()
gets FOV value, when entering optics
proto native float GetZoomInit (int muzzleIndex)
proto native float GetZoomMax ()
gets FOV maximum
proto native float GetZoomMax (int muzzleIndex)
proto native float GetZoomMin ()
gets FOV minimum
proto native float GetZoomMin (int muzzleIndex)
override bool HasFlammableMaterial ()
proto native bool HasInternalMagazine (int muzzleIndex)
proto native bool HasWeaponIronsightsOverride ()
is weapon in optics mode or not
void Init2DPreloadType ()
void InitCameraOverrideProperties ()
bool InitDOFAvailability ()
optics with more than 1x zoom do not allow DOF changes
void InitMapState ()
void InitOpticMode ()
bool InitOpticsDOFProperties (out array< float > temp_array)
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
void InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float)
initializes values for optics' post-processes
void InitOpticsPPInfo ()
void InitReddotData ()
void InsertMarker (vector pos, string text, int color, int idx)
proto native bool IsActivated ()
proto native bool IsBroadcasting ()
proto native bool IsChamberEjectable (int muzzleIndex)
detects presence of ejectable cartridge in muzzle's chamber
proto native bool IsChamberEmpty (int muzzleIndex)
detects empty chamber
proto native bool IsChamberFiredOut (int muzzleIndex)
detects presence of fired out casing in chamber
proto native bool IsChamberFull (int muzzleIndex)
maximum number of cartridges in chamber
proto native bool IsChamberJammed (int muzzleIndex)
detects presence of damaged cartridge in chamber
proto native bool IsFlashlightOn ()
query state of flashlight
proto native bool IsInOptics ()
is weapon in optics mode or not
proto native bool IsInOptics ()
bool IsInternalMagazineFull (int muzzleIndex)
maximum number of cartridges in internal magazine
bool IsNVOptic ()
proto native bool IsPinned ()
proto native bool IsReceiving ()
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
bool IsTurnedOn ()
proto native bool IsUsingWeaponIronsightsOverride ()
is optics using ironsights override settings or not
override bool IsWeapon ()
bool IsWorking ()
void ItemMap ()
void ItemOptics ()
override bool NameOverride (out string output)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override void OnInventoryEnter (Man player)
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void OnInventoryExit (Man player)
override void OnInventoryExit (Man player)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
void OnOpticEnter ()
void OnOpticExit ()
void OnOpticModeChange ()
optic-specific behaviour to be defined here (override)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
override event bool OnUseFromInventory (Man owner)
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWorkStart ()
override void OnWorkStop ()
proto bool PopCartridgeFromChamber (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
removes cartridge from chamber
proto bool PopCartridgeFromInternalMagazine (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
removes top-most cartridge from internal magazine
proto native bool PushCartridgeToChamber (int muzzleIndex, float ammoDamage, string ammoTypeName)
push cartridge to chamber
proto native bool PushCartridgeToInternalMagazine (int muzzleIndex, float ammoDamage, string ammoTypeName)
push cartridge into internal magazine
proto native void SelectionBulletHide ()
proto native void SelectionBulletShow ()
proto native void SelectionMagazineHide ()
proto native void SelectionMagazineShow ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
proto native void SetCanSpeak (bool onOff)
proto native void SetCurrentMode (int muzzleIndex, int mode)
proto native void SetCurrentMuzzle (int muzzleIndex)
sets index of active muzzle
void SetCurrentOpticMode (int mode)
proto native void SetFrequencyByIndex (int index)
proto native bool SetIgnited ()
sets grenade to state GR_TRIGGERED (if the state transition is possible)
void SetMapStateOpen (bool state, PlayerBase player)
displays open/closed selections; 1 == opened
proto native void SetMuzzleMode (int muzzleIndex, int modeIndex)
proto native void SetNextChannel ()
proto native void SetNextMuzzleMode (int muzzleIndex)
proto native bool SetPinned ()
sets grenade to state GR_PINNED (if the state transition is possible)
proto native void SetPrevChannel ()
proto native bool SetStepFOVIndex (int step)
sets zoom to fov value defined at given in 'discretefov' config array
proto native bool SetStepZeroing (int muzzleIndex, int step)
proto native bool SetStepZeroing (int step)
proto native bool SetStepZoom (int step)
sets zoom to fov value defined at given position in zoom fov config array
proto native bool SetUnpinned ()
sets grenade to state GR_UNPINNED (if the state transition is possible)
proto native bool SetZoom (float percent)
sets current zoom (in %)
void ShowReddot (bool state)
override bool ShowZonesHealth ()
override bool ShowZonesHealth ()
override bool ShowZonesHealth ()
proto native bool StepFOVDown ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native bool StepFOVUp ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepZeroingDown ()
sets zeroing to previous (respective to current) defined value in zeroing config array
proto native bool StepZeroingDown (int muzzleIndex=0)
void StepZeroingDownAllMuzzles ()
proto native bool StepZeroingUp ()
sets zeroing to next defined (respective to current) value in zeroing config array
proto native bool StepZeroingUp (int muzzleIndex=0)
void StepZeroingUpAllMuzzles ()
proto native bool StepZoomIn ()
sets zoom to next defined (respective to current) value in zoom fov config array
proto native bool StepZoomOut ()
sets zoom to previous (respective to current) defined value in zoom fov config array
proto native void Synchronize ()
Force synchronizes the weapon state from Server to Client. Use with caution.
void SyncMapMarkers ()
proto native bool TestAttachMagazine (int muzzleIndex, Magazine mag, bool do_occupancy_test, bool do_script_check)
query if a magazine can be attached to weapon
void UpdateOpticsReddotVisibility ()
void UpdateSelectionVisibility ()
proto native bool UseWeaponIronsightsOverride (bool state)
switches into ironsights override settings
proto native bool ZoomIn ()
moves current zoom by 1% up
proto native bool ZoomOut ()
moves current zoom by 1% down
Private Attributes
string m_2D_preload_type
bool m_allowsDOF
float m_blur_float
int m_CurrentOpticMode
int m_CurrentOpticModeLocal
bool m_data_set
string m_Description
string m_DisplayName
bool m_reddot_displayed bool m_isNVOptic = false
ref array< float > m_lens_array
protected ref array< ref MapMarker > m_MapMarkerArray
ref array< float > m_mask_array
float m_nearplane_override
string m_optic_sight_material
string m_optic_sight_texture
ref array< float > m_OpticsDOFProperties
int m_reddot_index
string m_TextureClosed
string m_TextureLegend
string m_TextureOpened
Detailed Description
Definition at line 3 of file inventoryitem.c.
Member Function Documentation
AllowsDOF()
bool InventoryItemSuper::AllowsDOF () inline private
returns 'true' for non-magnifying optics
Definition at line 427 of file itemoptics.c.
    {
        return m_allowsDOF;
    }
AttachMagazine()
InventoryItemSuper::AttachMagazine (int muzzleIndex, Magazine mag) private
perform attachment of a magazine to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
Returns
true if magazine was attached
CanAttachMagazine()
InventoryItemSuper::CanAttachMagazine (int muzzleIndex, Magazine mag) private
query if a magazine can be attached to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
Returns
true if magazine can be attached
CanBeIgnitedBy()
override bool InventoryItemSuper::CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 16 of file itembook.c.
    {
        if ( GetHierarchyParent() ) return false;
        return true;
    }
CanChamberFromMag()
InventoryItemSuper::CanChamberFromMag (int muzzleIndex, Magazine mag) private
query if a bullet from magazine can be loaded into chamber
Parameters
[in] muzzleIndex
[in] mag magazine to load from
Returns
true if cartidge from mag can be put into chamber
CanDetachAttachment()
override bool InventoryItemSuper::CanDetachAttachment (EntityAI parent) inline private
Definition at line 379 of file inventoryitem.c.
    {
        //parent.FindAtt
        InventoryLocation loc = new InventoryLocation();
        bool isPresent = GetInventory().GetCurrentInventoryLocation( loc );
        if ( !isPresent || loc.GetSlot() == -1 )
            return false;
        string slotName = InventorySlots.GetSlotName( loc.GetSlot() );
        if ( slotName && CarScript.Cast( parent ).GetCarDoorsState( slotName ) == CarDoorState.DOORS_OPEN )
            return true;
        return false;
    }
References CarScript::GetCarDoorsState(), InventoryLocation::GetSlot(), and InventorySlots::GetSlotName().
CanFire()
InventoryItemSuper::CanFire (int muzzleIndex) private
query whether the weapon can be fired or not
Returns
true if fire possible
CanIgniteItem()
override bool InventoryItemSuper::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 23 of file itembook.c.
    {
        return false;
    }
CanSpeak()
proto native bool InventoryItemSuper::CanSpeak () private
CreateRound()
proto native bool InventoryItemSuper::CreateRound (int muzzleIndex) private
DescriptionOverride()
override bool InventoryItemSuper::DescriptionOverride (out string output) inline private
Definition at line 1100 of file inventoryitem.c.
    {
        output = m_Description;
        return true;
    }
References m_Description.
DisplayNameRuinAttach() [1/3]
override bool InventoryItemSuper::DisplayNameRuinAttach () inline private
Definition at line 225 of file inventoryitem.c.
    {
        return true;
    }
DisplayNameRuinAttach() [2/3]
override bool InventoryItemSuper::DisplayNameRuinAttach () inline private
Definition at line 418 of file inventoryitem.c.
    {
        return true;
    }
DisplayNameRuinAttach() [3/3]
override bool InventoryItemSuper::DisplayNameRuinAttach () inline private
Definition at line 650 of file inventoryitem.c.
    {
        return true;
    }
DryDryFire()
proto native bool InventoryItemSuper::DryDryFire (int muzzleIndex) private
DryFire()
proto native bool InventoryItemSuper::DryFire (int muzzleIndex) private
EEHealthLevelChanged() [1/2]
override void InventoryItemSuper::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 235 of file inventoryitem.c.
    {
        super.EEHealthLevelChanged( oldLevel, newLevel, zone );
        if ( newLevel ==  GameConstants.STATE_RUINED )
        {
            string newWheel = "";
            switch ( GetType() )
            {
                case "HatchbackWheel":
                    newWheel = "HatchbackWheel_Ruined";
                break;
                case "CivSedanWheel":
                    newWheel = "CivSedanWheel_Ruined";
                break;
                case "Hatchback_02_Wheel":
                    newWheel = "Hatchback_02_Wheel_Ruined";
                break;
                case "Sedan_02_Wheel":
                    newWheel = "Sedan_02_Wheel_Ruined";
                break;
                case "Truck_01_Wheel":
                    newWheel = "Truck_01_Wheel_Ruined";
                break;
                case "Truck_01_WheelDouble":
                    newWheel = "Truck_01_WheelDouble_Ruined";
                break;
                case "Offroad_02_Wheel":
                    newWheel = "Offroad_02_Wheel_Ruined";
                break;
            }
            if ( newWheel != "" )
            {
                //Unlock to allow creating a new item
                if (IsLockedInSlot())
                {
                    UnlockFromParent();
                }
                ReplaceWheelLambda lambda = new ReplaceWheelLambda(this, newWheel, null);
                lambda.SetTransferParams(true, true, true);
                GetInventory().ReplaceItemWithNew(InventoryMode.SERVER, lambda);
            }
        }
    }
References GetType(), ReplaceWheelLambda(), GameConstants::STATE_RUINED, and UnlockFromParent().
EEHealthLevelChanged() [2/2]
override void InventoryItemSuper::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 402 of file inventoryitem.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        if ( newLevel ==  GameConstants.STATE_RUINED && m_Initialized )
        {
            EffectSound sound_plug;
            switch ( zone )
            {
                case "Window":
                    PlaySoundSet( sound_plug, "offroad_hit_window_small_SoundSet", 0, 0 );
                break;
            }
        }
    }
References m_Initialized, PlaySoundSet(), and GameConstants::STATE_RUINED.
EEKilled()
override void InventoryItemSuper::EEKilled (Object killer) inline private
Definition at line 660 of file inventoryitem.c.
    {
        if ( GetGame().IsServer() )
        {
            Car car;
            EntityAI parent = GetHierarchyParent();
            Class.CastTo( car, parent );
            if ( car )
            {
                float amount = car.GetFluidFraction( CarFluid.COOLANT );
                float newAmount = Math.RandomFloat( amount * 0.2, amount * 0.75 );
                car.Leak( CarFluid.COOLANT, newAmount );
            }
        }
    }
References Class::CastTo(), GetGame(), and Math::RandomFloat().
EEOnDamageCalculated()
override bool InventoryItemSuper::EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 299 of file inventoryitem.c.
    {
        return false;
    }
EffectBulletHide()
InventoryItemSuper::EffectBulletHide (int muzzleIndex) private
reset effect cartridge in weapon
Parameters
[in] muzzleIndex
EffectBulletShow()
InventoryItemSuper::EffectBulletShow (int muzzleIndex, float dmg, string type) private
push effect cartridge to Weapon
Parameters
[in] muzzleIndex
[in] ammoDamage damage of the ammo
[in] ammoTypeName type name of the ammo
EjectCasing()
InventoryItemSuper::EjectCasing (int muzzleIndex) private
ejects casing from chamber
EnableBroadcast()
proto native void InventoryItemSuper::EnableBroadcast (bool state) private
EnableReceive()
proto native void InventoryItemSuper::EnableReceive (bool state) private
EnterOptics() [1/2]
InventoryItemSuper::EnterOptics () private
switches to optics mode if possible
Returns
true if success, false otherwise
EnterOptics() [2/2]
proto native bool InventoryItemSuper::EnterOptics () private
ExitOptics() [1/2]
InventoryItemSuper::ExitOptics () private
switches out of optics mode (if possible)
Returns
true if success, false otherwise
ExitOptics() [2/2]
proto native bool InventoryItemSuper::ExitOptics () private
Fire()
proto native bool InventoryItemSuper::Fire (int muzzleIndex, vector pos, vector dir, vector speed) private
FlashlightOff()
InventoryItemSuper::FlashlightOff () private
attempt to turn off flashlight
Returns
true if on -> off, false otherwise (no flashlight, no power, etc, already off)
FlashlightOn()
InventoryItemSuper::FlashlightOn () private
attempt to turn on flashlight
Returns
true if set on, false otherwise (no flashlight, no power, etc)
GetAttachedLauncher()
InventoryItemSuper::GetAttachedLauncher () private
Returns
returns attached launcher or null
GetAttachedOptics()
InventoryItemSuper::GetAttachedOptics () private
Returns
returns attached optics or null
GetAttachedSuppressor()
InventoryItemSuper::GetAttachedSuppressor () private
Returns
returns attached suppressor or null
GetCameraPoint() [1/2]
proto native void InventoryItemSuper::GetCameraPoint (int muzzleIndex, out vector pos, out vector dir) private
GetCameraPoint() [2/2]
proto native void InventoryItemSuper::GetCameraPoint (out vector pos, out vector dir) private
GetCartridgeInfo()
InventoryItemSuper::GetCartridgeInfo (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
get info about the cartridge in the chamber of a muzzle
Parameters
[in] muzzleIndex
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if info retrieved
GetChamberAmmoTypeName()
InventoryItemSuper::GetChamberAmmoTypeName (int muzzleIndex) private
Parameters
[in]
return returns name of i-th ammo type for chambering
GetChamberedCartridgeMagazineTypeName()
InventoryItemSuper::GetChamberedCartridgeMagazineTypeName (int muzzleIndex) private
query the type of magazine the cartridge can be unloaded to
Parameters
[in] muzzleIndex
Returns
entity type name
GetCurrentMode()
proto native int InventoryItemSuper::GetCurrentMode (int muzzleIndex) private
GetCurrentModeAutoFire()
proto native bool InventoryItemSuper::GetCurrentModeAutoFire (int muzzleIndex) private
GetCurrentModeBurstSize()
proto native int InventoryItemSuper::GetCurrentModeBurstSize (int muzzleIndex) private
GetCurrentModeName()
proto native owned string InventoryItemSuper::GetCurrentModeName (int muzzleIndex) private
GetCurrentMuzzle()
InventoryItemSuper::GetCurrentMuzzle () private
Returns
returns index of current muzzle
GetCurrentNVType()
int InventoryItemSuper::GetCurrentNVType () inline private
Definition at line 437 of file itemoptics.c.
    {
        /*
        //TODO - implement this into NV optics and modify (KazuarOptic example below)
        if (IsWorking())
        {
            switch (m_CurrentOpticMode)
            {
                case GameConstants.OPTICS_STATE_DAY:
                    return NVTypes.NV_OPTICS_KAZUAR_DAY;
                case GameConstants.OPTICS_STATE_NIGHTVISION:
                    return NVTypes.NV_OPTICS_KAZUAR_NIGHT;
            }
        }
        else
        {
            return NVTypes.NV_OPTICS_OFF;
        }
        */
        return NVTypes.NONE;
    }
GetCurrentOpticMode()
int InventoryItemSuper::GetCurrentOpticMode () inline private
Definition at line 466 of file itemoptics.c.
    {
        return m_CurrentOpticMode;
    }
GetCurrentStepFOV()
InventoryItemSuper::GetCurrentStepFOV () private
returns fov value at current index, or 'OpticsInfo.opticsZoomInit' config value (non-zooming optics)
GetCurrentZeroing()
InventoryItemSuper::GetCurrentZeroing (int muzzleIndex = 0) private
returns currently used value of zeroing in config array of weapon or attached optics
Returns
currently used value in zeroing
GetInternalMagazineCartridgeCount()
proto native int InventoryItemSuper::GetInternalMagazineCartridgeCount (int muzzleIndex) private
GetInternalMagazineCartridgeInfo()
InventoryItemSuper::GetInternalMagazineCartridgeInfo (int muzzleIndex, int cartridgeIndex, out float ammoDamage, out string ammoTypeName) private
get info about the cartridge in the internal magazine of a muzzle
Parameters
[in] muzzleIndex
[in] cartridgeIndex has to be 0 <= cartridgeIndex < GetInternalMagazineCartridgeCount()
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if info retrieved
GetInternalMagazineMaxCartridgeCount()
proto native int InventoryItemSuper::GetInternalMagazineMaxCartridgeCount (int muzzleIndex) private
GetMagazine()
InventoryItemSuper::GetMagazine (int muzzleIndex) private
Parameters
[in] muzzleIndex
Returns
attached magazine
GetMagazineTypeCount()
InventoryItemSuper::GetMagazineTypeCount (int muzzleIndex) private
Parameters
[in]
return returns the number of magazines in 'magazines' in config
GetMapStateAnimation()
bool InventoryItemSuper::GetMapStateAnimation () inline private
Definition at line 1030 of file inventoryitem.c.
    {
        if (GetAnimationPhase("map_opened") == 0)
            return true;
        return false;
    }
GetMarkerArray()
array< ref MapMarker > InventoryItemSuper::GetMarkerArray () inline private
Definition at line 1118 of file inventoryitem.c.
    {
        return m_MapMarkerArray;
    }
GetMaxMagazineTypeName()
InventoryItemSuper::GetMaxMagazineTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of the magazine in 'magazines' in config with highest capacity
GetMeleeTargetType() [1/2]
override int InventoryItemSuper::GetMeleeTargetType () inline private
Definition at line 287 of file inventoryitem.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetMeleeTargetType() [2/2]
override int InventoryItemSuper::GetMeleeTargetType () inline private
Definition at line 397 of file inventoryitem.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetMuzzleCount()
InventoryItemSuper::GetMuzzleCount () private
Returns
number of muzzles
GetMuzzleModeCount()
proto native int InventoryItemSuper::GetMuzzleModeCount (int muzzleIndex) private
GetNearPlaneValue()
float InventoryItemSuper::GetNearPlaneValue () inline private
Definition at line 505 of file itemoptics.c.
    {
        return m_nearplane_override;
    }
GetOpticsDOF()
ref array< float > InventoryItemSuper::GetOpticsDOF () inline private
Definition at line 488 of file itemoptics.c.
    {
        return m_OpticsDOFProperties;
    }
GetOpticsPPBlur()
float InventoryItemSuper::GetOpticsPPBlur () inline private
Definition at line 500 of file itemoptics.c.
    {
        return m_blur_float;
    }
GetOpticsPPLens()
ref array< float > InventoryItemSuper::GetOpticsPPLens () inline private
Definition at line 496 of file itemoptics.c.
    {
        return m_lens_array;
    }
GetOpticsPPMask()
ref array< float > InventoryItemSuper::GetOpticsPPMask () inline private
Definition at line 492 of file itemoptics.c.
    {
        return m_mask_array;
    }
GetRadius()
proto native float InventoryItemSuper::GetRadius () private
Returns current wheel radius.
GetRandomChamberableAmmoTypeName()
InventoryItemSuper::GetRandomChamberableAmmoTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of a random ammo registered in 'chamberableFrom' in config
GetRandomMagazineTypeName()
InventoryItemSuper::GetRandomMagazineTypeName (int muzzleIndex) private
Parameters
[in]
return returns the typename of a random magazine in 'magazines' in config
GetReloadTime()
InventoryItemSuper::GetReloadTime (int muzzleIndex) private
defines time from one shot to another
Parameters
[in] muzzleIndex
Returns
reload time in seconds
GetSlotFromMuzzleIndex()
InventoryItemSuper::GetSlotFromMuzzleIndex (int muzzleIndex) private
conversion muzzleIndex -> slotId
Parameters
[in] muzzleIndex muzzle index
Returns
slotId on success, -1 otherwise
GetStepFOVCount()
InventoryItemSuper::GetStepFOVCount () private
returns number of configured steps
GetStepFOVIndex()
InventoryItemSuper::GetStepFOVIndex () private
returns index of currently used value in 'discretefov' config array
Returns
index of currently used value in 'discretefov' config array
GetStepZeroing() [1/2]
InventoryItemSuper::GetStepZeroing () private
returns position of currently used value in zeroing config array
Returns
position of currently used value in zeroing config array
GetStepZeroing() [2/2]
proto native int InventoryItemSuper::GetStepZeroing (int muzzleIndex = 0) private
GetStepZoom()
InventoryItemSuper::GetStepZoom () private
returns position of currently used value in zoom config array
Returns
position of currently used value in zoom config array
GetTotalCartridgeCount()
InventoryItemSuper::GetTotalCartridgeCount (int muzzleIndex) private
Returns
returns number of available cartridges in chamber + internal magazine
GetTotalMaxCartridgeCount()
InventoryItemSuper::GetTotalMaxCartridgeCount (int muzzleIndex) private
Returns
returns number of max cartridges in chamber + internal magazine
GetTunedFrequency()
proto native float InventoryItemSuper::GetTunedFrequency () private
GetTunedFrequencyIndex()
proto native int InventoryItemSuper::GetTunedFrequencyIndex () private
GetWidth()
proto native float InventoryItemSuper::GetWidth () private
Returns wheel width.
GetZeroingDistanceZoomMax() [1/2]
InventoryItemSuper::GetZeroingDistanceZoomMax () private
Gets Zeroing distance at opticsZoomMax.
GetZeroingDistanceZoomMax() [2/2]
proto native float InventoryItemSuper::GetZeroingDistanceZoomMax (int muzzleIndex) private
GetZeroingDistanceZoomMin() [1/2]
InventoryItemSuper::GetZeroingDistanceZoomMin () private
Gets Zeroing distance at opticsZoomMin.
GetZeroingDistanceZoomMin() [2/2]
proto native float InventoryItemSuper::GetZeroingDistanceZoomMin (int muzzleIndex) private
GetZoom()
InventoryItemSuper::GetZoom () private
returns current percentage of zoom
Returns
current percentage of zoom
GetZoomInit() [1/2]
InventoryItemSuper::GetZoomInit () private
gets FOV value, when entering optics
GetZoomInit() [2/2]
proto native float InventoryItemSuper::GetZoomInit (int muzzleIndex) private
GetZoomMax() [1/2]
InventoryItemSuper::GetZoomMax () private
gets FOV maximum
GetZoomMax() [2/2]
proto native float InventoryItemSuper::GetZoomMax (int muzzleIndex) private
GetZoomMin() [1/2]
InventoryItemSuper::GetZoomMin () private
gets FOV minimum
GetZoomMin() [2/2]
proto native float InventoryItemSuper::GetZoomMin (int muzzleIndex) private
HasFlammableMaterial()
override bool InventoryItemSuper::HasFlammableMaterial () inline private
Definition at line 11 of file itembook.c.
    {
        return true;
    }
HasInternalMagazine()
InventoryItemSuper::HasInternalMagazine (int muzzleIndex) private
Note
passing in -1 will check all muzzles
Returns
true if weapon has an internal magazine
HasWeaponIronsightsOverride()
InventoryItemSuper::HasWeaponIronsightsOverride () private
is weapon in optics mode or not
Returns
true if optics has defined override optics info for weapon
Init2DPreloadType()
void InventoryItemSuper::Init2DPreloadType () inline private
Definition at line 510 of file itemoptics.c.
    {
        string path = "cfgVehicles " + GetType() + " OpticsInfo preloadOpticType";
        string type_2d;
        if ( GetGame().ConfigIsExisting(path) )
        {
            GetGame().ConfigGetText(path, type_2d);
            m_2D_preload_type = type_2d;
        }
    }
References CGame::ConfigGetText(), ConfigIsExisting(), GetGame(), GetType(), and path.
InitCameraOverrideProperties()
void InventoryItemSuper::InitCameraOverrideProperties () inline private
Definition at line 397 of file itemoptics.c.
    {
        string path = "cfgVehicles " + GetType() + " OpticsInfo";
        if ( GetGame().ConfigIsExisting(path + " nearPlaneDistanceOverride") )
        {
            m_nearplane_override = Math.Max(GetGame().ConfigGetFloat(path + " nearPlaneDistanceOverride"),DayZPlayerCameraBase.CONST_NEARPLANE_OPTICS_MIN);
        }
        else
        {
            m_nearplane_override = DayZPlayerCameraOptics.CONST_NEARPLANE_OPTICS;
        }
    }
References ConfigGetFloat(), ConfigIsExisting(), DayZPlayerCameraOptics(), GetGame(), GetType(), Math::Max(), and path.
InitDOFAvailability()
bool InventoryItemSuper::InitDOFAvailability () inline private
optics with more than 1x zoom do not allow DOF changes
Definition at line 370 of file itemoptics.c.
    {
        float fov_max;
        string path = "cfgVehicles " + GetType() + " OpticsInfo";
        /*
        Weapon_Base weapon = Weapon_Base.Cast(GetHierarchyParent());
        if (!weapon)
            return false; // no DOF for handheld optics
        */
        fov_max = GetGame().ConfigGetFloat(path + " opticsZoomMax");
        if (fov_max >= GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS)
        {
            return true;
        }
        return false;
    }
References CGame::ConfigGetFloat(), GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, GetGame(), GetType(), and path.
InitMapState()
void InventoryItemSuper::InitMapState () inline private
Definition at line 979 of file inventoryitem.c.
    {
        string path = "CfgWorlds " + GetGame().GetWorldName();
        GetGame().ConfigGetText(path + " mapDisplayNameKey",m_DisplayName);
        GetGame().ConfigGetText(path + " mapDescriptionKey",m_Description);
        GetGame().ConfigGetText(path + " mapTextureClosed",m_TextureClosed);
        GetGame().ConfigGetText(path + " mapTextureOpened",m_TextureOpened);
        GetGame().ConfigGetText(path + " mapTextureLegend",m_TextureLegend);
        SetObjectTexture(0,m_TextureClosed);
        SetObjectTexture(1,m_TextureOpened);
        SetObjectTexture(2,m_TextureLegend);
        //m_MarkerArray = new ref array<vector,int,int,string>;
        m_MapMarkerArray = new ref array<ref MapMarker>;
        if (GetGame().IsMultiplayer() && GetGame().IsServer())
        {
            SyncMapMarkers();
        }
    }
References CGame::ConfigGetText(), GetGame(), CGame::GetWorldName(), m_Description, and path.
InitOpticMode()
void InventoryItemSuper::InitOpticMode () inline private
Definition at line 522 of file itemoptics.c.
    {
        SetCurrentOpticMode(GameConstants.OPTICS_STATE_DAY);
    }
References GameConstants::OPTICS_STATE_DAY.
InitOpticsDOFProperties()
bool InventoryItemSuper::InitOpticsDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for optic's alternate ironsights (ACOG etc.)
Definition at line 411 of file itemoptics.c.
    {
        if (GetGame().ConfigIsExisting("cfgVehicles " + GetType() + " OpticsInfo PPDOFProperties"))
        {
            GetGame().ConfigGetFloatArray("cfgVehicles " + GetType() + " OpticsInfo PPDOFProperties", temp_array);
            return true;
        }
        else if (GetGame().ConfigIsExisting("cfgVehicles " + GetType() + " OpticsInfoWeaponOverride PPDOFProperties"))
        {
            GetGame().ConfigGetFloatArray("cfgVehicles " + GetType() + " OpticsInfoWeaponOverride PPDOFProperties", temp_array);
            return true;
        }
        return false;
    }
References CGame::ConfigGetFloatArray(), ConfigIsExisting(), GetGame(), and GetType().
InitOpticsPP()
void InventoryItemSuper::InitOpticsPP (out array< float > mask_array, out array< float > lens_array, out float blur_float) inline private
initializes values for optics' post-processes
Definition at line 389 of file itemoptics.c.
    {
        string path = "cfgVehicles " + GetType() + " OpticsInfo";
        GetGame().ConfigGetFloatArray(path + " PPMaskProperties", mask_array);
        GetGame().ConfigGetFloatArray(path + " PPLensProperties", lens_array);
        blur_float = GetGame().ConfigGetFloat(path + " PPBlurProperties");
    }
References CGame::ConfigGetFloat(), CGame::ConfigGetFloatArray(), GetGame(), GetType(), and path.
InitOpticsPPInfo()
void InventoryItemSuper::InitOpticsPPInfo () inline private
Definition at line 361 of file itemoptics.c.
    {
        m_allowsDOF = InitDOFAvailability();
        InitOpticsPP(m_mask_array, m_lens_array, m_blur_float);
        m_isNVOptic = ConfigGetBool("NVOptic");
    }
References ConfigGetBool().
InitReddotData()
void InventoryItemSuper::InitReddotData () inline private
Definition at line 303 of file itemoptics.c.
    {
        string path = "cfgVehicles " + GetType() + " OpticsInfo";
        string temp;
        if (GetGame().ConfigIsExisting(path))
        {
            m_reddot_index = GetHiddenSelectionIndex("reddot");
            if (GetGame().ConfigIsExisting(path + " opticSightTexture"))
            {
                GetGame().ConfigGetText(path + " opticSightTexture", temp);
                m_optic_sight_texture = temp;
                temp = "";
            }
            if (GetGame().ConfigIsExisting(path + " opticSightMaterial"))
            {
                GetGame().ConfigGetText(path + " opticSightMaterial", temp);
                m_optic_sight_material = temp;
                temp = "";
            }
        }
        m_data_set = true;
    }
References CGame::ConfigGetText(), ConfigIsExisting(), GetGame(), GetType(), and path.
InsertMarker()
void InventoryItemSuper::InsertMarker (vector pos, string text, int color, int idx) inline private
Definition at line 1112 of file inventoryitem.c.
    {
        ref MapMarker marker = MapMarker(pos,text,color,idx);
        m_MapMarkerArray.Insert(marker);
    }
IsActivated()
InventoryItemSuper::IsActivated () private
Returns
true if grenade is GR_TRIGGERED or GR_EXPLODED
IsBroadcasting()
proto native bool InventoryItemSuper::IsBroadcasting () private
IsChamberEjectable()
InventoryItemSuper::IsChamberEjectable (int muzzleIndex) private
detects presence of ejectable cartridge in muzzle's chamber
Returns
true if eject-able
IsChamberEmpty()
InventoryItemSuper::IsChamberEmpty (int muzzleIndex) private
detects empty chamber
Returns
true if no cartridge in chamber
IsChamberFiredOut()
InventoryItemSuper::IsChamberFiredOut (int muzzleIndex) private
detects presence of fired out casing in chamber
Returns
true if casing in chamber
IsChamberFull()
InventoryItemSuper::IsChamberFull (int muzzleIndex) private
maximum number of cartridges in chamber
Returns
true if full
IsChamberJammed()
InventoryItemSuper::IsChamberJammed (int muzzleIndex) private
detects presence of damaged cartridge in chamber
Returns
true if jammed
IsFlashlightOn()
InventoryItemSuper::IsFlashlightOn () private
query state of flashlight
Returns
true if set on
IsInOptics() [1/2]
InventoryItemSuper::IsInOptics () private
is weapon in optics mode or not
Returns
true if in optics mode, false otherwise
IsInOptics() [2/2]
proto native bool InventoryItemSuper::IsInOptics () private
IsInternalMagazineFull()
InventoryItemSuper::IsInternalMagazineFull (int muzzleIndex) inline private
maximum number of cartridges in internal magazine
Returns
true if full
Definition at line 118 of file weapon.c.
{ return GetInternalMagazineMaxCartridgeCount(muzzleIndex) == GetInternalMagazineCartridgeCount(muzzleIndex); }
IsNVOptic()
bool InventoryItemSuper::IsNVOptic () inline private
Definition at line 432 of file itemoptics.c.
    {
        return m_isNVOptic;
    }
IsPinned()
InventoryItemSuper::IsPinned () private
Returns
true if grenade is pinned
IsReceiving()
proto native bool InventoryItemSuper::IsReceiving () private
IsThisIgnitionSuccessful()
override bool InventoryItemSuper::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 37 of file itembook.c.
    {
        return Fireplace.CanIgniteEntityAsFireplace( this );
    }
IsTurnedOn()
bool InventoryItemSuper::IsTurnedOn () inline private
Definition at line 55 of file inventoryitem.c.
    {
        return true;
    }
Referenced by OnInventoryEnter(), and OnWasAttached().
IsUsingWeaponIronsightsOverride()
InventoryItemSuper::IsUsingWeaponIronsightsOverride () private
is optics using ironsights override settings or not
Returns
true if optics is using ironsights override settings
IsWeapon()
override bool InventoryItemSuper::IsWeapon () inline private
Definition at line 6 of file weapon.c.
{ return true; }
IsWorking()
bool InventoryItemSuper::IsWorking () inline private
Definition at line 209 of file itemoptics.c.
    {
        if (GetCompEM() && GetCompEM().CanWork())
            return true;
        return false;
    }
ItemMap()
void InventoryItemSuper::ItemMap () inline private
Definition at line 974 of file inventoryitem.c.
    {
        InitMapState();
    }
ItemOptics()
void InventoryItemSuper::ItemOptics () inline private
Definition at line 19 of file itemoptics.c.
    {
        m_mask_array = new array<float>;
        m_lens_array = new array<float>;
        m_OpticsDOFProperties = new array<float>;
        InitReddotData();
        InitOpticsPPInfo();
        InitCameraOverrideProperties();
        InitOpticsDOFProperties(m_OpticsDOFProperties);
        Init2DPreloadType();
        InitOpticMode();
        m_CurrentOpticModeLocal = -1;
        RegisterNetSyncVariableInt( "m_CurrentOpticMode", 0, 63 );
    }
NameOverride()
override bool InventoryItemSuper::NameOverride (out string output) inline private
Definition at line 1093 of file inventoryitem.c.
    {
        output = m_DisplayName;
        return true;
    }
OnIgnitedTarget()
override void InventoryItemSuper::OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 28 of file itembook.c.
    {
    }
OnIgnitedThis()
override void InventoryItemSuper::OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 32 of file itembook.c.
    {
        Fireplace.IgniteEntityAsFireplace( this, fire_source );
    }
OnInventoryEnter() [1/2]
override void InventoryItemSuper::OnInventoryEnter (Man player) inline private
Definition at line 60 of file inventoryitem.c.
    {
        super.OnInventoryEnter(player);
        PlayerBase pb = PlayerBase.Cast(player);
        if ( pb && IsTurnedOn() )
        {
            pb.MapNavigationItemInPossession(this);
        }
    }
References IsTurnedOn().
OnInventoryEnter() [2/2]
override void InventoryItemSuper::OnInventoryEnter (Man player) inline private
Definition at line 118 of file inventoryitem.c.
    {
        super.OnInventoryEnter(player);
        if ( IsRuined() )
        {
            return;
        }
        PlayerBase pb = PlayerBase.Cast(player);
        if ( pb )
        {
            pb.MapNavigationItemInPossession(this);
        }
    }
References IsRuined().
OnInventoryExit() [1/3]
override void InventoryItemSuper::OnInventoryExit (Man player) inline private
Definition at line 71 of file inventoryitem.c.
    {
        super.OnInventoryExit(player);
        PlayerBase pb = PlayerBase.Cast(player);
        if ( pb )
        {
            pb.MapNavigationItemNotInPossession(this);
        }
    }
OnInventoryExit() [2/3]
override void InventoryItemSuper::OnInventoryExit (Man player) inline private
Definition at line 134 of file inventoryitem.c.
    {
        super.OnInventoryExit(player);
        if ( IsRuined() )
        {
            return;
        }
        PlayerBase pb = PlayerBase.Cast(player);
        if ( pb )
        {
            pb.MapNavigationItemNotInPossession(this);
        }
    }
References IsRuined().
OnInventoryExit() [3/3]
override void InventoryItemSuper::OnInventoryExit (Man player) inline private
Definition at line 248 of file itemoptics.c.
    {
        super.OnInventoryExit(player);
        PlayerBase playerPB;
        if (PlayerBase.CastTo(playerPB, player))
        {
            playerPB.SetReturnToOptics(false);
        }
        SetTakeable(true);
    }
References SetTakeable().
OnItemLocationChanged()
override void InventoryItemSuper::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 1001 of file inventoryitem.c.
    {
        super.OnItemLocationChanged(old_owner,new_owner);
        SetMapStateOpen(false, PlayerBase.Cast(old_owner));
    }
OnOpticEnter()
void InventoryItemSuper::OnOpticEnter () inline private
Definition at line 473 of file itemoptics.c.
    {
        if ( GetGame() && !GetGame().IsDedicatedServer() )
        {
            HideSelection("hide");
        }
    }
References GetGame(), and ItemOptics::HideSelection().
OnOpticExit()
void InventoryItemSuper::OnOpticExit () inline private
Definition at line 480 of file itemoptics.c.
    {
        if ( GetGame() && !GetGame().IsDedicatedServer() )
        {
            ShowSelection("hide");
        }
    }
References GetGame(), and ItemOptics::ShowSelection().
OnOpticModeChange()
void InventoryItemSuper::OnOpticModeChange () inline private
optic-specific behaviour to be defined here (override)
Definition at line 472 of file itemoptics.c.
{}
OnRPC()
override void InventoryItemSuper::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 1057 of file inventoryitem.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        //array<vector,int,int,string> tmp_array = new array<vector,int,int,string>;
        //Param1<ref array<vector,int,int,string>> param = new Param1<ref array<vector,int,int,string>>(m_MarkerArray);
        Param1<ref array<ref MapMarker>> params = new Param1<ref array<ref MapMarker>>( m_MapMarkerArray );
        if (rpc_type == ERPCs.RPC_SEND_MAP_MARKERS)
        {
            if (ctx.Read(params))
            {
                //Print("Map | OnRPC | m_MapMarkerArray_new count: " + m_MapMarkerArray_new.Count());
            }
        }
    }
References Serializer::Read().
OnStoreLoad() [1/2]
override bool InventoryItemSuper::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 1074 of file inventoryitem.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        if (version >= 108 && !ctx.Read(m_MapMarkerArray))
        {
            return false;
        }
        return true;
    }
References Serializer::Read().
OnStoreLoad() [2/2]
override bool InventoryItemSuper::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 268 of file itemoptics.c.
    {
        if ( !super.OnStoreLoad(ctx,version) )
        {
            return false;
        }
        m_IsStoreLoad = true;
        if ( version >= 126 )
        {
            if ( !ctx.Read(m_CurrentOpticMode) )
            {
                m_IsStoreLoad = false;
                return false;
            }
        }
        OnOpticModeChange();
        SetSynchDirty();
        m_IsStoreLoad = false;
        return true;
    }
References m_IsStoreLoad, and Serializer::Read().
OnStoreSave() [1/2]
override void InventoryItemSuper::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 1086 of file inventoryitem.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_MapMarkerArray);
    }
References Serializer::Write().
OnStoreSave() [2/2]
override void InventoryItemSuper::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 261 of file itemoptics.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_CurrentOpticMode);
    }
References Serializer::Write().
OnUseFromInventory()
override event bool InventoryItemSuper::OnUseFromInventory (Man owner) inline private
Definition at line 3 of file itembook.c.
    {
        return false;
    }
OnVariablesSynchronized()
override void InventoryItemSuper::OnVariablesSynchronized () inline private
Definition at line 292 of file itemoptics.c.
    {
        super.OnVariablesSynchronized();
        if (m_CurrentOpticModeLocal != m_CurrentOpticMode)
        {
            OnOpticModeChange();
            m_CurrentOpticModeLocal = m_CurrentOpticMode;
        }
    }
OnWasAttached() [1/3]
override void InventoryItemSuper::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 82 of file inventoryitem.c.
    {
        super.OnWasAttached(parent, slot_id);
        PlayerBase player = PlayerBase.Cast(parent);
        if ( parent.GetHierarchyRoot() )
        {
            player = PlayerBase.Cast(parent.GetHierarchyRoot());
        }
        if ( player && IsTurnedOn() )
        {
            player.MapNavigationItemInPossession(this);
        }
    }
References IsTurnedOn().
OnWasAttached() [2/3]
override void InventoryItemSuper::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 150 of file inventoryitem.c.
    {
        super.OnWasAttached(parent, slot_id);
        if ( IsRuined() )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast(parent);
        if ( parent.GetHierarchyParent() )
        {
            player = PlayerBase.Cast(parent.GetHierarchyParent());
        }
        if ( player )
        {
            player.MapNavigationItemInPossession(this);
        }
    }
References IsRuined().
OnWasAttached() [3/3]
override void InventoryItemSuper::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 228 of file itemoptics.c.
    {
        super.OnWasAttached(parent, slot_id);
        SetTakeable(false);
    }
References SetTakeable().
OnWasDetached() [1/3]
override void InventoryItemSuper::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 98 of file inventoryitem.c.
    {
        super.OnWasDetached(parent, slot_id);
        PlayerBase player = PlayerBase.Cast(parent);
        if ( parent.GetHierarchyRoot() )
        {
            player = PlayerBase.Cast(parent.GetHierarchyRoot());
        }
        if ( player )
        {
            player.MapNavigationItemNotInPossession(this);
        }
    }
OnWasDetached() [2/3]
override void InventoryItemSuper::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 171 of file inventoryitem.c.
    {
        super.OnWasDetached(parent, slot_id);
        if ( IsRuined() )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast(parent);
        if ( parent.GetHierarchyParent() )
        {
            player = PlayerBase.Cast(parent.GetHierarchyParent());
        }
        if ( player )
        {
            player.MapNavigationItemNotInPossession(this);
        }
    }
References IsRuined().
OnWasDetached() [3/3]
override void InventoryItemSuper::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 235 of file itemoptics.c.
    {
        super.OnWasDetached(parent, slot_id);
        PlayerBase player;
        if (PlayerBase.CastTo(player, GetHierarchyRootPlayer()))
        {
            player.SetReturnToOptics(false);
        }
        SetTakeable(true);
    }
References SetTakeable().
OnWorkStart()
override void InventoryItemSuper::OnWorkStart () inline private
Definition at line 193 of file itemoptics.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            ShowReddot(true);
        }
    }
References GetGame().
OnWorkStop()
override void InventoryItemSuper::OnWorkStop () inline private
Definition at line 201 of file itemoptics.c.
    {
        if (!GetGame().IsDedicatedServer())
        {
            ShowReddot(false);
        }
    }
References GetGame().
PopCartridgeFromChamber()
InventoryItemSuper::PopCartridgeFromChamber (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
removes cartridge from chamber
PopCartridgeFromInternalMagazine()
InventoryItemSuper::PopCartridgeFromInternalMagazine (int muzzleIndex, out float ammoDamage, out string ammoTypeName) private
removes top-most cartridge from internal magazine
PushCartridgeToChamber()
InventoryItemSuper::PushCartridgeToChamber (int muzzleIndex, float ammoDamage, string ammoTypeName) private
push cartridge to chamber
PushCartridgeToInternalMagazine()
InventoryItemSuper::PushCartridgeToInternalMagazine (int muzzleIndex, float ammoDamage, string ammoTypeName) private
push cartridge into internal magazine
SelectionBulletHide()
proto native void InventoryItemSuper::SelectionBulletHide () private
SelectionBulletShow()
proto native void InventoryItemSuper::SelectionBulletShow () private
SelectionMagazineHide()
proto native void InventoryItemSuper::SelectionMagazineHide () private
SelectionMagazineShow()
proto native void InventoryItemSuper::SelectionMagazineShow () private
SetActions() [1/5]
override void InventoryItemSuper::SetActions () inline private
Definition at line 292 of file inventoryitem.c.
    {
        super.SetActions();
        //AddAction(ActionDetach);
        //AddAction(ActionAttachOnSelection);
    }
SetActions() [2/5]
override void InventoryItemSuper::SetActions () inline private
Definition at line 446 of file inventoryitem.c.
    {
        super.SetActions();
        AddAction(ActionAttachOnSelection);
        AddAction(ActionDetach);
    }
References ActionDetach(), and AddAction().
SetActions() [3/5]
override void InventoryItemSuper::SetActions () inline private
Definition at line 680 of file inventoryitem.c.
    {
        super.SetActions();
        AddAction(ActionAttachOnSelection);
        AddAction(ActionDetach);
    }
References ActionDetach(), and AddAction().
SetActions() [4/5]
override void InventoryItemSuper::SetActions () inline private
Definition at line 925 of file inventoryitem.c.
    {
        super.SetActions();
        AddAction(ActionUnpackBox);
    }
References AddAction().
SetActions() [5/5]
override void InventoryItemSuper::SetActions () inline private
Definition at line 529 of file itemoptics.c.
    {
        super.SetActions();
        AddAction(ActionViewOptics);
    }
References AddAction().
SetCanSpeak()
proto native void InventoryItemSuper::SetCanSpeak (bool onOff) private
SetCurrentMode()
proto native void InventoryItemSuper::SetCurrentMode (int muzzleIndex, int mode) private
SetCurrentMuzzle()
InventoryItemSuper::SetCurrentMuzzle (int muzzleIndex) private
sets index of active muzzle
Parameters
[in] muzzleIndex
SetCurrentOpticMode()
void InventoryItemSuper::SetCurrentOpticMode (int mode) inline private
Definition at line 460 of file itemoptics.c.
    {
        m_CurrentOpticMode = mode;
        OnOpticModeChange();
    }
SetFrequencyByIndex()
proto native void InventoryItemSuper::SetFrequencyByIndex (int index) private
SetIgnited()
InventoryItemSuper::SetIgnited () private
sets grenade to state GR_TRIGGERED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetMapStateOpen()
void InventoryItemSuper::SetMapStateOpen (bool state, PlayerBase player) inline private
displays open/closed selections; 1 == opened
Definition at line 1009 of file inventoryitem.c.
    {
        if (player)
        {
            player.SetMapOpen(state);
            if (state)
                player.OnItemInHandsChanged();
        }
        if (state)
        {
            ShowSelection("map_opened");
            HideSelection("map_closed");
        }
        else
        {
            ShowSelection("map_closed");
            HideSelection("map_opened");
        }
    }
SetMuzzleMode()
proto native void InventoryItemSuper::SetMuzzleMode (int muzzleIndex, int modeIndex) private
SetNextChannel()
proto native void InventoryItemSuper::SetNextChannel () private
SetNextMuzzleMode()
proto native void InventoryItemSuper::SetNextMuzzleMode (int muzzleIndex) private
SetPinned()
InventoryItemSuper::SetPinned () private
sets grenade to state GR_PINNED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetPrevChannel()
proto native void InventoryItemSuper::SetPrevChannel () private
SetStepFOVIndex()
InventoryItemSuper::SetStepFOVIndex (int step) private
sets zoom to fov value defined at given in 'discretefov' config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetStepZeroing() [1/2]
proto native bool InventoryItemSuper::SetStepZeroing (int muzzleIndex, int step) private
SetStepZeroing() [2/2]
proto native bool InventoryItemSuper::SetStepZeroing (int step) private
SetStepZoom()
InventoryItemSuper::SetStepZoom (int step) private
sets zoom to fov value defined at given position in zoom fov config array
Parameters
[in] index of configured step, range [0..cfg_max]
Returns
true if zoom set
SetUnpinned()
InventoryItemSuper::SetUnpinned () private
sets grenade to state GR_UNPINNED (if the state transition is possible)
Returns
true if state already set or if state transition performed, false otherwise
SetZoom()
InventoryItemSuper::SetZoom (float percent) private
sets current zoom (in %)
Parameters
[in] percent zoom to set in range [0.0f .. 100.0f]
Returns
true if zoom set
ShowReddot()
void InventoryItemSuper::ShowReddot (bool state) inline private
Definition at line 327 of file itemoptics.c.
    {
        if (GetGame().IsDedicatedServer())
        {
            ErrorEx("should not be called on the server!",ErrorExSeverity.INFO);
            return;
        }
        if (!m_data_set)
        {
            InitReddotData();
        }
        // does not have reddot
        if (m_reddot_index == -1)
        {
            return;
        }
        if (state)
        {
            if (m_optic_sight_texture != "")
                SetObjectTexture(m_reddot_index, m_optic_sight_texture);
            if (m_optic_sight_material != "")
                SetObjectMaterial(m_reddot_index, m_optic_sight_material);
        }
        else
        {
            SetObjectTexture(m_reddot_index, "");
            SetObjectMaterial(m_reddot_index, "");
        }
        m_reddot_displayed = state;
    }
References ErrorEx, and GetGame().
ShowZonesHealth() [1/3]
override bool InventoryItemSuper::ShowZonesHealth () inline private
Definition at line 230 of file inventoryitem.c.
    {
        return true;
    }
ShowZonesHealth() [2/3]
override bool InventoryItemSuper::ShowZonesHealth () inline private
Definition at line 423 of file inventoryitem.c.
    {
        return true;
    }
ShowZonesHealth() [3/3]
override bool InventoryItemSuper::ShowZonesHealth () inline private
Definition at line 655 of file inventoryitem.c.
    {
        return true;
    }
StepFOVDown()
InventoryItemSuper::StepFOVDown () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
StepFOVUp()
InventoryItemSuper::StepFOVUp () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZeroingDown() [1/2]
InventoryItemSuper::StepZeroingDown () private
sets zeroing to previous (respective to current) defined value in zeroing config array
Returns
true if zeroing set
StepZeroingDown() [2/2]
proto native bool InventoryItemSuper::StepZeroingDown (int muzzleIndex = 0) private
StepZeroingDownAllMuzzles()
void InventoryItemSuper::StepZeroingDownAllMuzzles () inline private
Definition at line 442 of file weapon.c.
    {
        for (int i = 0; i < GetMuzzleCount(); i++)
        {
            StepZeroingDown(i);
        }
    }
StepZeroingUp() [1/2]
InventoryItemSuper::StepZeroingUp () private
sets zeroing to next defined (respective to current) value in zeroing config array
Returns
true if zeroing set
StepZeroingUp() [2/2]
proto native bool InventoryItemSuper::StepZeroingUp (int muzzleIndex = 0) private
StepZeroingUpAllMuzzles()
void InventoryItemSuper::StepZeroingUpAllMuzzles () inline private
Definition at line 434 of file weapon.c.
    {
        for (int i = 0; i < GetMuzzleCount(); i++)
        {
            StepZeroingUp(i);
        }
    }
StepZoomIn()
InventoryItemSuper::StepZoomIn () private
sets zoom to next defined (respective to current) value in zoom fov config array
Returns
true if zoom set
StepZoomOut()
InventoryItemSuper::StepZoomOut () private
sets zoom to previous (respective to current) defined value in zoom fov config array
Returns
true if zoom set
Synchronize()
InventoryItemSuper::Synchronize () private
Force synchronizes the weapon state from Server to Client. Use with caution.
SyncMapMarkers()
void InventoryItemSuper::SyncMapMarkers () inline private
Definition at line 1037 of file inventoryitem.c.
    {
        if (m_MapMarkerArray.Count() <= 0)
            return;
        PlayerIdentity pid;
        //Param1<ref array<vector,int,int,string>> params = new Param1<ref array<vector,int,int,string>>( m_MarkerArray );
        Param1<ref array<ref MapMarker>> params = new Param1<ref array<ref MapMarker>>( m_MapMarkerArray );
        if (GetGame().IsServer() && GetHierarchyRootPlayer()) //TODO do we need PlayerIdentity here?
        {
            pid = GetHierarchyRootPlayer().GetIdentity();
            RPCSingleParam(ERPCs.RPC_SEND_MAP_MARKERS,params,true,pid);
        }
        else
        {
            RPCSingleParam(ERPCs.RPC_SEND_MAP_MARKERS,params,true);
        }
    }
References GetGame(), CGame::IsServer(), and RPCSingleParam().
TestAttachMagazine()
InventoryItemSuper::TestAttachMagazine (int muzzleIndex, Magazine mag, bool do_occupancy_test, bool do_script_check) private
query if a magazine can be attached to weapon
Parameters
[in] muzzleIndex
[in] mag magazine to attach
[in] do_occupancy_test if false, skips test for presence of another magazine in weapon
[in] do_script_check if false, skips script conditions
Returns
true if magazine can be attached
UpdateOpticsReddotVisibility()
void InventoryItemSuper::UpdateOpticsReddotVisibility () inline private
Definition at line 216 of file itemoptics.c.
    {
        if (IsWorking() && !m_reddot_displayed)
        {
            ShowReddot(true);
        }
        else if (!IsWorking() && m_reddot_displayed)
        {
            ShowReddot(false);
        }
    }
UpdateSelectionVisibility()
void InventoryItemSuper::UpdateSelectionVisibility () inline private
Definition at line 527 of file itemoptics.c.
{}
UseWeaponIronsightsOverride()
InventoryItemSuper::UseWeaponIronsightsOverride (bool state) private
switches into ironsights override settings
Returns
true if switching was successful
ZoomIn()
InventoryItemSuper::ZoomIn () private
moves current zoom by 1% up
Returns
true if zoom set
ZoomOut()
InventoryItemSuper::ZoomOut () private
moves current zoom by 1% down
Returns
true if zoom set
Member Data Documentation
m_2D_preload_type
string InventoryItemSuper::m_2D_preload_type private
Definition at line 14 of file itemoptics.c.
m_allowsDOF
bool InventoryItemSuper::m_allowsDOF private
Definition at line 4 of file itemoptics.c.
m_blur_float
float InventoryItemSuper::m_blur_float private
Definition at line 10 of file itemoptics.c.
m_CurrentOpticMode
int InventoryItemSuper::m_CurrentOpticMode private
Definition at line 7 of file itemoptics.c.
m_CurrentOpticModeLocal
int InventoryItemSuper::m_CurrentOpticModeLocal private
Definition at line 8 of file itemoptics.c.
m_data_set
bool InventoryItemSuper::m_data_set private
Definition at line 3 of file itemoptics.c.
m_Description
string InventoryItemSuper::m_Description private
Definition at line 972 of file inventoryitem.c.
m_DisplayName
string InventoryItemSuper::m_DisplayName private
Definition at line 971 of file inventoryitem.c.
m_isNVOptic
bool m_reddot_displayed bool InventoryItemSuper::m_isNVOptic = false private
Definition at line 6 of file itemoptics.c.
m_lens_array
ref array<float> InventoryItemSuper::m_lens_array private
Definition at line 16 of file itemoptics.c.
m_MapMarkerArray
protected ref array<ref MapMarker> InventoryItemSuper::m_MapMarkerArray private
Definition at line 966 of file inventoryitem.c.
m_mask_array
ref array<float> InventoryItemSuper::m_mask_array private
Definition at line 15 of file itemoptics.c.
m_nearplane_override
float InventoryItemSuper::m_nearplane_override private
Definition at line 11 of file itemoptics.c.
m_optic_sight_material
string InventoryItemSuper::m_optic_sight_material private
Definition at line 13 of file itemoptics.c.
m_optic_sight_texture
string InventoryItemSuper::m_optic_sight_texture private
Definition at line 12 of file itemoptics.c.
m_OpticsDOFProperties
ref array<float> InventoryItemSuper::m_OpticsDOFProperties private
Definition at line 17 of file itemoptics.c.
m_reddot_index
int InventoryItemSuper::m_reddot_index private
Definition at line 9 of file itemoptics.c.
m_TextureClosed
string InventoryItemSuper::m_TextureClosed private
Definition at line 968 of file inventoryitem.c.
m_TextureLegend
string InventoryItemSuper::m_TextureLegend private
Definition at line 970 of file inventoryitem.c.
m_TextureOpened
string InventoryItemSuper::m_TextureOpened private
Definition at line 969 of file inventoryitem.c.