DayzKode: CallQueueContext Class Reference
CallQueueContext Class Reference
Tools
Private Member Functions
void Call ()
void CallParams (Param params)
void CallQueueContext (Class target, string fn, Param params)
void Invalidate ()
bool IsValid ()
Private Attributes
string m_function
ref Param m_params
Class m_target
bool m_valid
Detailed Description
Definition at line 15 of file tools.c.
Constructor & Destructor Documentation
CallQueueContext()
void CallQueueContext::CallQueueContext (Class target, string fn, Param params) inline private
Definition at line 22 of file tools.c.
    {
        m_target = target;
        m_function = fn;
        m_params = params;
        m_valid = true;
    }
References m_function, m_params, m_target, and m_valid.
Member Function Documentation
Call()
void CallQueueContext::Call () inline private
Definition at line 30 of file tools.c.
    {
        CallParams(m_params);
    }
References CallParams(), and m_params.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonDown(), and array< ref CallQueueContext >::Tick().
CallParams()
void CallQueueContext::CallParams (Param params) inline private
Definition at line 35 of file tools.c.
    {
        if (params)
        {
            GetGame().GameScript.CallFunctionParams(m_target, m_function, NULL, params);
        }
        else
        {
            GetGame().GameScript.CallFunction(m_target, m_function, NULL, 0);
        }
    }
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_function, and m_target.
Referenced by Call(), and CallQueue::Tick().
Invalidate()
void CallQueueContext::Invalidate () inline private
Definition at line 47 of file tools.c.
                      {
        m_valid = false;
    }
References m_valid.
Referenced by array< ref CallQueueContext >::RemoveCalls().
IsValid()
bool CallQueueContext::IsValid () inline private
Definition at line 51 of file tools.c.
                  {
        return m_valid;
    }
References m_valid.
Referenced by array< ref CallQueueContext >::Tick(), and CallQueue::Tick().
Member Data Documentation
m_function
string CallQueueContext::m_function private
Definition at line 18 of file tools.c.
Referenced by CallParams(), and CallQueueContext().
m_params
ref Param CallQueueContext::m_params private
Definition at line 19 of file tools.c.
Referenced by Call(), and CallQueueContext().
m_target
Class CallQueueContext::m_target private
Definition at line 17 of file tools.c.
Referenced by CallParams(), CallQueueContext(), and array< ref CallQueueContext >::RemoveCalls().
m_valid
bool CallQueueContext::m_valid private
Definition at line 20 of file tools.c.
Referenced by CallQueueContext(), Invalidate(), and IsValid().