DayzKode: PPEClassBase Class Reference
PPEClassBase Class Reference
Created once, on manager init. Script-side representation of C++ material class, separate handling.
Private Member Functions
void ApplyValueChanges ()
void ChangeMaterialPathUsed (string path)
protected void CreateDataStructure ()
protected void CreateMaterial ()
void DbgPrnt (string text)
string GetCurrentMaterialPath ()
string GetDefaultMaterialPath ()
override this if you want to use different path by default; '.emat' is appended automatically
Material GetMaterial ()
PPEMatClassParameterCommandData GetParameterCommandData (int parameter_idx)
Some PP effects are handled as hard-coded exceptions, outside of material system. Default == PPEExceptions.NONE (systemic behaviour)
int GetPostProcessEffectID ()
Overriden in all material classes!
protected void Init (string mat_path_override="")
void InsertParamValueData (PPERequestParamDataBase request_data)
Distributes requester data to the material class structure and links them to appropriate parameter.
protected void InsertUpdatedParameter (int mat_id)
void OnUpdate (float timeslice, int order)
generic update method, take care when overriding!
protected void ParamUpdateQueueCleanup (int order)
void ParamUpdateRemove (int parameter_idx)
Queue selected parameter for removal from the update queue.
void PPEClassBase (string mat_path_override="")
protected void RegisterMaterialParameters ()
inserted into associative array by parameter int value, parameter registration order does not matter (still ordered, though)
protected void RegisterParameterColor (int idx, string parameter_name, float r, float g, float b, float a)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterColorEx (int idx, string parameter_name, float r, float g, float b, float a, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterResource (int idx, string parameter_name, string default_path)
protected void RegisterParameterScalarBool (int idx, string parameter_name, bool default_value)
protected void RegisterParameterScalarFloat (int idx, string parameter_name, float default_value, float min, float max)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterScalarFloatEx (int idx, string parameter_name, float default_value, float min, float max, typename type)
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
protected void RegisterParameterScalarInt (int idx, string parameter_name, int default_value, int min, int max)
protected void RegisterParameterTexture (int idx, string parameter_name, string default_path)
protected void RegisterParameterVector (int idx, string parameter_name, array< float > default_values)
void RemoveRequest (int req_idx)
unused, see 'RemoveActiveRequestFromMaterials' for more info
void SetFinalParameterValue (int parameter_idx)
Clamps the values being set to defaults, if there is no request setting non-zero values on the parameter.
void SetParameterUpdating (int order, int parameter_id)
Queue specific parameter of this material to update.
Private Attributes
protected PPEManager m_Manager
protected Material m_Material
protected ref map< int, ref PPEMatClassParameterCommandData > m_MaterialParamMapStructure
protected string m_MaterialPath = ""
protected ref array< int > m_ParameterRemovalQueue
protected ref map< int, ref array< int > > m_ParameterUpdateQueueMap
protected ref array< int > m_UpdatedParameters
Detailed Description
Created once, on manager init. Script-side representation of C++ material class, separate handling.
Definition at line 2 of file ppematclassesbase.c.
Constructor & Destructor Documentation
PPEClassBase()
void PPEClassBase::PPEClassBase (string mat_path_override = "") inline private
Definition at line 14 of file ppematclassesbase.c.
    {
        Init(mat_path_override);
        CreateMaterial();
        CreateDataStructure();
        RegisterMaterialParameters();
    }
References CreateDataStructure(), CreateMaterial(), Init(), and RegisterMaterialParameters().
Member Function Documentation
ApplyValueChanges()
void PPEClassBase::ApplyValueChanges () inline private
Definition at line 269 of file ppematclassesbase.c.
    {
        int parameter_id;
        for (int i = 0; i < m_UpdatedParameters.Count(); i++)
        {
            parameter_id = m_UpdatedParameters.Get(i);
            SetFinalParameterValue(parameter_id);
        }
        m_UpdatedParameters.Clear();
    }
References m_UpdatedParameters, and SetFinalParameterValue().
Referenced by ProcessApplyValueChanges().
ChangeMaterialPathUsed()
void PPEClassBase::ChangeMaterialPathUsed (string path) inline private
Definition at line 326 of file ppematclassesbase.c.
    {
        m_MaterialPath = path;
        m_Material = null;
        CreateMaterial();
    }
References CreateMaterial(), m_Material, m_MaterialPath, and path.
Referenced by ChangePPEMaterial().
CreateDataStructure()
protected void PPEClassBase::CreateDataStructure () inline private
Definition at line 47 of file ppematclassesbase.c.
    {
        m_MaterialParamMapStructure = new map<int,ref PPEMatClassParameterCommandData>;
        //m_ParameterUpdateQueue = new array<int>;
        m_ParameterUpdateQueueMap = new map<int, ref array<int>>;
        m_ParameterRemovalQueue = new array<int>;
        m_UpdatedParameters = new array<int>;
    }
References m_MaterialParamMapStructure, m_ParameterRemovalQueue, m_ParameterUpdateQueueMap, and m_UpdatedParameters.
Referenced by PPEClassBase().
CreateMaterial()
protected void PPEClassBase::CreateMaterial () inline private
Definition at line 35 of file ppematclassesbase.c.
    {
        if (m_MaterialPath != "")
            m_Material = GetGame().GetWorld().GetMaterial(m_MaterialPath);
    }
References GetGame(), World::GetMaterial(), CGame::GetWorld(), m_Material, and m_MaterialPath.
Referenced by ChangeMaterialPathUsed(), and PPEClassBase().
DbgPrnt()
void PPEClassBase::DbgPrnt (string text) inline private
Definition at line 380 of file ppematclassesbase.c.
    {
        //Debug.Log(""+text);
    }
GetCurrentMaterialPath()
string PPEClassBase::GetCurrentMaterialPath () inline private
Definition at line 333 of file ppematclassesbase.c.
    {
        return m_MaterialPath;
    }
References m_MaterialPath.
GetDefaultMaterialPath()
string PPEClassBase::GetDefaultMaterialPath () private
override this if you want to use different path by default; '.emat' is appended automatically
Referenced by Init().
GetMaterial()
Material PPEClassBase::GetMaterial () inline private
Definition at line 41 of file ppematclassesbase.c.
    {
        return m_Material;
    }
References m_Material.
Referenced by ChangePPEMaterial().
GetParameterCommandData()
PPEMatClassParameterCommandData PPEClassBase::GetParameterCommandData (int parameter_idx) inline private
Some PP effects are handled as hard-coded exceptions, outside of material system. Default == PPEExceptions.NONE (systemic behaviour)
Definition at line 350 of file ppematclassesbase.c.
    {
        return m_MaterialParamMapStructure.Get(parameter_idx);
    }
References m_MaterialParamMapStructure.
Referenced by GetPostProcessCurrentValues(), GetPostProcessDefaultValues(), PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and SetFinalParameterValue().
GetPostProcessEffectID()
int PPEClassBase::GetPostProcessEffectID () inline private
Overriden in all material classes!
Definition at line 339 of file ppematclassesbase.c.
    {
        return PostProcessEffectType.None;
    }
Referenced by InsertParamValueData(), OnUpdate(), RegisterParameterColor(), RegisterParameterColorEx(), RegisterParameterResource(), RegisterParameterScalarBool(), RegisterParameterScalarFloat(), RegisterParameterScalarFloatEx(), RegisterParameterScalarInt(), RegisterParameterTexture(), RegisterParameterVector(), and RegisterPPEClass().
Init()
protected void PPEClassBase::Init (string mat_path_override = "") inline private
Definition at line 22 of file ppematclassesbase.c.
    {
        if (mat_path_override != "")
        {
            m_MaterialPath = mat_path_override;
        }
        else
        {
            m_MaterialPath = GetDefaultMaterialPath();
        }
        m_Manager = PPEManagerStatic.GetPPEManager();
    }
References GetDefaultMaterialPath(), PPEManagerStatic::GetPPEManager(), m_Manager, and m_MaterialPath.
InsertParamValueData()
void PPEClassBase::InsertParamValueData (PPERequestParamDataBase request_data) inline private
Distributes requester data to the material class structure and links them to appropriate parameter.
Definition at line 151 of file ppematclassesbase.c.
    {
        PPEMatClassParameterCommandData param_data;
        bool exists = m_MaterialParamMapStructure.Find(request_data.GetParameterID(),param_data);
        if ( !exists )
        {
            Error("PPEClassBase | InsertParamValueData | mat/par/req: " + GetPostProcessEffectID() + "/" + request_data.GetParameterID() + "/" + request_data.GetRequesterIDX() + " not registered in m_MaterialParamMapStructure!");
            return;
        }
        request_data.SetDataActive(true);
        request_data.SetUpdatingDataValues(true); //marks request data as updating
        param_data.InsertRequestData(request_data);//<request_ID, data>
        //DbgPrnt("PPEDebug | InsertParamValueData | mat/par/req: " + GetPostProcessEffectID() + "/" + request_data.GetParameterID() + "/" + request_data.GetRequesterIDX() + " | requester: " + request_data.m_Requester);
    }
References Error(), PPERequestParamDataBase::GetParameterID(), GetPostProcessEffectID(), PPERequestParamDataBase::GetRequesterIDX(), PPEMatClassParameterCommandData::InsertRequestData(), m_MaterialParamMapStructure, PPERequestParamDataBase::SetDataActive(), and PPERequestParamDataBase::SetUpdatingDataValues().
Referenced by SendMaterialValueData().
InsertUpdatedParameter()
protected void PPEClassBase::InsertUpdatedParameter (int mat_id) inline private
Definition at line 281 of file ppematclassesbase.c.
    {
        if ( m_UpdatedParameters.Find(mat_id) == -1 )
            m_UpdatedParameters.Insert(mat_id);
    }
References m_UpdatedParameters.
Referenced by OnUpdate().
OnUpdate()
void PPEClassBase::OnUpdate (float timeslice, int order) inline private
generic update method, take care when overriding!
Definition at line 201 of file ppematclassesbase.c.
    {
        int parameter_idx = -1;
        //DbgPrnt("PPEDebug | PPEClassBase - OnUpdate | mat_id: " + GetPostProcessEffectID());
        if ( m_ParameterUpdateQueueMap.Contains(order) )
        {
            //Print(m_ParameterUpdateQueueMap.Get(order));
            for ( int i = 0; i < m_ParameterUpdateQueueMap.Get(order).Count(); i++ )
            {
                //DbgPrnt("PPEDebug | PPEClassBase - OnUpdate | parameter_idx: " + m_ParameterUpdateQueue.Get(i));
                Param p_values; //TODO - move to material classes?
                bool setting_defaults = false;
                parameter_idx = m_ParameterUpdateQueueMap.Get(order).Get(i);
                m_MaterialParamMapStructure.Get(parameter_idx).Update(timeslice,p_values,setting_defaults,order);
                InsertUpdatedParameter(parameter_idx);
            }
            m_Manager.InsertUpdatedMaterial(GetPostProcessEffectID());
            ParamUpdateQueueCleanup(order);
        }
        /*if ( !m_ParameterUpdateQueueMap.Contains(order) || m_ParameterUpdateQueueMap.Get(order).Count() < 1 )
            m_Manager.RemoveMaterialUpdating(GetPostProcessEffectID(),order); //stops material from updating when no parameters are.*/
    }
References Count, GetPostProcessEffectID(), InsertUpdatedParameter(), m_Manager, m_MaterialParamMapStructure, m_ParameterUpdateQueueMap, and ParamUpdateQueueCleanup().
Referenced by ProcessMaterialUpdates().
ParamUpdateQueueCleanup()
protected void PPEClassBase::ParamUpdateQueueCleanup (int order) inline private
Definition at line 308 of file ppematclassesbase.c.
    {
        //DbgPrnt("PPEDebug | PPEClassBase - ParamUpdateQueueCleanup | mat_id: " + GetPostProcessEffectID() + " | UpdateQueue count: " + m_ParameterUpdateQueue.Count());
        //DbgPrnt("PPEDebug | PPEClassBase - ParamUpdateQueueCleanup | mat_id: " + GetPostProcessEffectID() + " | RemovalQueue count: " + m_ParameterRemovalQueue.Count());
        for ( int i = 0; i < m_ParameterUpdateQueueMap.Get(order).Count(); i++ )
        {
            if ( m_ParameterRemovalQueue.Find(m_ParameterUpdateQueueMap.Get(order).Get(i)) != -1 )
            {
                //DbgPrnt("PPEDebug | PPEClassBase - ParamUpdateQueueCleanup | removing update of: " + m_ParameterUpdateQueue.Get(i));
                //m_ParameterUpdateQueue.RemoveItem(m_ParameterUpdateQueue.Get(i));
            }
        }
        m_ParameterUpdateQueueMap.Get(order).Clear();
    }
References Count, m_ParameterRemovalQueue, and m_ParameterUpdateQueueMap.
Referenced by OnUpdate().
ParamUpdateRemove()
void PPEClassBase::ParamUpdateRemove (int parameter_idx) inline private
Queue selected parameter for removal from the update queue.
Definition at line 288 of file ppematclassesbase.c.
    {
        if ( m_ParameterRemovalQueue.Find(parameter_idx) == -1 )
            m_ParameterRemovalQueue.Insert(parameter_idx);
    }
References m_ParameterRemovalQueue.
RegisterMaterialParameters()
protected void PPEClassBase::RegisterMaterialParameters () private
inserted into associative array by parameter int value, parameter registration order does not matter (still ordered, though)
Referenced by PPEClassBase().
RegisterParameterColor()
protected void PPEClassBase::RegisterParameterColor (int idx, string parameter_name, float r, float g, float b, float a) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 102 of file ppematclassesbase.c.
    {
        PPETemplateDefColor p = new PPETemplateDefColor(parameter_name,r,g,b,a);
        PPEMatClassParameterColor parameter_data = new PPEMatClassParameterColor(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterColorEx()
protected void PPEClassBase::RegisterParameterColorEx (int idx, string parameter_name, float r, float g, float b, float a, typename type) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 111 of file ppematclassesbase.c.
    {
        PPETemplateDefColor p = new PPETemplateDefColor(parameter_name,r,g,b,a);
        PPEMatClassParameterColor parameter_data;
        bool boo = Class.CastTo(parameter_data,type.Spawn());
        //Print("RegisterParameterColorEx: " + boo );
        parameter_data.RegisterDefaults(p);
        parameter_data.SetMaterialIndex(GetPostProcessEffectID());
        parameter_data.SetParameterIndex(idx);
        parameter_data.SetParent(this);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References Class::CastTo(), GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterResource()
protected void PPEClassBase::RegisterParameterResource (int idx, string parameter_name, string default_path) inline private
Definition at line 141 of file ppematclassesbase.c.
    {
        PPETemplateDefResource p = new PPETemplateDefResource(parameter_name,default_path);
        PPEMatClassParameterResource parameter_data = new PPEMatClassParameterResource(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
RegisterParameterScalarBool()
protected void PPEClassBase::RegisterParameterScalarBool (int idx, string parameter_name, bool default_value) inline private
Definition at line 59 of file ppematclassesbase.c.
    {
        PPETemplateDefBool p = new PPETemplateDefBool(parameter_name,default_value);
        PPEMatClassParameterBool parameter_data = new PPEMatClassParameterBool(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEDOF::RegisterMaterialParameters(), PPEDepthOfField::RegisterMaterialParameters(), PPEFilmGrain::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), and PPEHBAO::RegisterMaterialParameters().
RegisterParameterScalarFloat()
protected void PPEClassBase::RegisterParameterScalarFloat (int idx, string parameter_name, float default_value, float min, float max) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 77 of file ppematclassesbase.c.
    {
        PPETemplateDefFloat p = new PPETemplateDefFloat(parameter_name,default_value,min,max);
        PPEMatClassParameterFloat parameter_data = new PPEMatClassParameterFloat(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), m_MaterialParamMapStructure, and PPEMatClassParameterFloat().
Referenced by PPEDOF::RegisterMaterialParameters(), PPEExposureNative::RegisterMaterialParameters(), PPEEyeAccomodationNative::RegisterMaterialParameters(), PPELightIntensityParamsNative::RegisterMaterialParameters(), PPEChromAber::RegisterMaterialParameters(), PPEColors::RegisterMaterialParameters(), PPEDepthOfField::RegisterMaterialParameters(), PPEDynamicBlur::RegisterMaterialParameters(), PPEFilmGrain::RegisterMaterialParameters(), PPEGaussFilter::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), PPEGodRays::RegisterMaterialParameters(), PPEHBAO::RegisterMaterialParameters(), PPERadialBlur::RegisterMaterialParameters(), PPERain::RegisterMaterialParameters(), PPERotBlur::RegisterMaterialParameters(), PPESSAO::RegisterMaterialParameters(), PPEUnderWater::RegisterMaterialParameters(), and PPEWetDistort::RegisterMaterialParameters().
RegisterParameterScalarFloatEx()
protected void PPEClassBase::RegisterParameterScalarFloatEx (int idx, string parameter_name, float default_value, float min, float max, typename type) inline private
WARNING - min/max values are usually taken from Workbench defaults, may not be actual min/max values the renderer can handle! When in doubt, try some higher/lower values...
Definition at line 87 of file ppematclassesbase.c.
    {
        PPETemplateDefFloat p = new PPETemplateDefFloat(parameter_name,default_value,min,max);
        PPEMatClassParameterFloat parameter_data;
        bool boo = Class.CastTo(parameter_data,type.Spawn());
        //Print("RegisterParameterColorEx: " + boo );
        parameter_data.RegisterDefaults(p);
        parameter_data.SetMaterialIndex(GetPostProcessEffectID());
        parameter_data.SetParameterIndex(idx);
        parameter_data.SetParent(this);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References Class::CastTo(), GetPostProcessEffectID(), m_MaterialParamMapStructure, and PPEMatClassParameterFloat().
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RegisterParameterScalarInt()
protected void PPEClassBase::RegisterParameterScalarInt (int idx, string parameter_name, int default_value, int min, int max) inline private
Definition at line 67 of file ppematclassesbase.c.
    {
        PPETemplateDefInt p = new PPETemplateDefInt(parameter_name,default_value,min,max);
        PPEMatClassParameterInt parameter_data = new PPEMatClassParameterInt(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEDepthOfField::RegisterMaterialParameters(), PPEFXAA::RegisterMaterialParameters(), PPEGlow::RegisterMaterialParameters(), PPEHBAO::RegisterMaterialParameters(), PPEMedian::RegisterMaterialParameters(), PPESMAA::RegisterMaterialParameters(), PPESSAO::RegisterMaterialParameters(), and PPEWetDistort::RegisterMaterialParameters().
RegisterParameterTexture()
protected void PPEClassBase::RegisterParameterTexture (int idx, string parameter_name, string default_path) inline private
Definition at line 133 of file ppematclassesbase.c.
    {
        PPETemplateDefTexture p = new PPETemplateDefTexture(parameter_name,default_path);
        PPEMatClassParameterTexture parameter_data = new PPEMatClassParameterTexture(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
RegisterParameterVector()
protected void PPEClassBase::RegisterParameterVector (int idx, string parameter_name, array< float > default_values) inline private
Definition at line 124 of file ppematclassesbase.c.
    {
        PPETemplateDefVector p = new PPETemplateDefVector(parameter_name,default_values);
        PPEMatClassParameterVector parameter_data = new PPEMatClassParameterVector(GetPostProcessEffectID(),idx,this);
        parameter_data.RegisterDefaults(p);
        m_MaterialParamMapStructure.Set(idx, parameter_data);
    }
References GetPostProcessEffectID(), and m_MaterialParamMapStructure.
Referenced by PPEColors::RegisterMaterialParameters(), and PPEGlow::RegisterMaterialParameters().
RemoveRequest()
void PPEClassBase::RemoveRequest (int req_idx) inline private
unused, see 'RemoveActiveRequestFromMaterials' for more info
Definition at line 170 of file ppematclassesbase.c.
    {
        /*for (int i = 0; i < m_ActiveMaterialRequestMap.Count(); i++)
        {
            ActiveParameterRequestsMap dbg = m_ActiveMaterialRequestMap.Get(i);
            //DbgPrnt("PPEDebug | dbg size: " + dbg.Count());
            if ( m_ActiveMaterialRequestMap.Get(i).Contains(req_idx) )
            {
                m_ActiveMaterialRequestMap.Get(i).Remove(req_idx);
                dbg = m_ActiveMaterialRequestMap.Get(i);
                if ( !m_ActiveMaterialRequestMap.Get(i) || m_ActiveMaterialRequestMap.Get(i).Count() < 1 )
                {
                    if (m_ParameterUpdateQueue.IsValidIndex(i))
                    {
                        DbgPrnt("PPEDebug | PPEClassBase - RemoveRequest | Removing: " + i);
                        DbgPrnt("PPEDebug | PPEClassBase - RemoveRequest | exit 4 - last request removal");
                        m_ParameterRemovalQueue.Insert(m_ParameterUpdateQueue.Get(i));
                    }
                    else
                        DbgPrnt("PPEDebug | PPEClassBase - RemoveRequest | Update queue no. " + i + " already removed!");
                }
            }
            //Adds to update one more time
            m_Manager.SetMaterialParamUpdating(GetPostProcessEffectID(),i);
        }*/
    }
Referenced by RemoveActiveRequestFromMaterials().
SetFinalParameterValue()
void PPEClassBase::SetFinalParameterValue (int parameter_idx) inline private
Clamps the values being set to defaults, if there is no request setting non-zero values on the parameter.
Definition at line 228 of file ppematclassesbase.c.
    {
        int var_type = GetParameterCommandData(parameter_idx).GetParameterVarType();
        Param values = GetParameterCommandData(parameter_idx).GetCurrentValues();
        switch (var_type)
        {
            case PPEConstants.VAR_TYPE_BOOL:
                bool value_var_bool = Param1<bool>.Cast(values).param1;
                m_Material.SetParamByIndex(parameter_idx,value_var_bool);
                //Print("DebugValues | PPEConstants.VAR_TYPE_BOOL | bool val: " + value_var_bool);
            break;
            case PPEConstants.VAR_TYPE_INT:
                int value_var_int = Param1<int>.Cast(values).param1;
                m_Material.SetParamByIndex(parameter_idx,value_var_int);
                //Print("DebugValues | PPEConstants.VAR_TYPE_BOOL | bool val: " + value_var_bool);
            break;
            case PPEConstants.VAR_TYPE_FLOAT:
                float value_var_float = Param1<float>.Cast(values).param1;
                m_Material.SetParamByIndex(parameter_idx,value_var_float);
                //Print("DebugValues | PPEConstants.VAR_TYPE_FLOAT | float val: " + value_var_float);
            break;
            case PPEConstants.VAR_TYPE_COLOR:
                float color[4] = {0,0,0,0};
                color[0] = Param4<float,float,float,float>.Cast(values).param1;
                color[1] = Param4<float,float,float,float>.Cast(values).param2;
                color[2] = Param4<float,float,float,float>.Cast(values).param3;
                color[3] = Param4<float,float,float,float>.Cast(values).param4;
                m_Material.SetParamByIndex(parameter_idx,color);
                //Print("DebugValues | PPEConstants.VAR_TYPE_COLOR | color val:: " + color[0] + " " + color[1] + " " + color[2] + " " + color[3]);
            break;
        }
    }
References PPEMatClassParameterCommandData::GetCurrentValues(), GetParameterCommandData(), PPEMatClassParameterCommandData::GetParameterVarType(), m_Material, Param::param1, and Material::SetParamByIndex().
Referenced by ApplyValueChanges().
SetParameterUpdating()
void PPEClassBase::SetParameterUpdating (int order, int parameter_id) inline private
Queue specific parameter of this material to update.
Definition at line 295 of file ppematclassesbase.c.
    {
        if ( !m_ParameterUpdateQueueMap.Contains(order) )
        {
            m_ParameterUpdateQueueMap.Set(order,new array<int>);
        }
        if ( m_ParameterUpdateQueueMap.Get(order).Find(parameter_id) == -1 )
        {
            m_ParameterUpdateQueueMap.Get(order).Insert(parameter_id);
        }
    }
References m_ParameterUpdateQueueMap.
Referenced by SetMaterialParamUpdating().
Member Data Documentation
m_Manager
protected PPEManager PPEClassBase::m_Manager private
Definition at line 4 of file ppematclassesbase.c.
Referenced by Init(), and OnUpdate().
m_Material
protected Material PPEClassBase::m_Material private
Definition at line 6 of file ppematclassesbase.c.
Referenced by ChangeMaterialPathUsed(), CreateMaterial(), GetMaterial(), and SetFinalParameterValue().
m_MaterialParamMapStructure
protected ref map<int,ref PPEMatClassParameterCommandData> PPEClassBase::m_MaterialParamMapStructure private
Definition at line 12 of file ppematclassesbase.c.
Referenced by CreateDataStructure(), GetParameterCommandData(), InsertParamValueData(), OnUpdate(), RegisterParameterColor(), RegisterParameterColorEx(), RegisterParameterResource(), RegisterParameterScalarBool(), RegisterParameterScalarFloat(), RegisterParameterScalarFloatEx(), RegisterParameterScalarInt(), RegisterParameterTexture(), and RegisterParameterVector().
m_MaterialPath
protected string PPEClassBase::m_MaterialPath = "" private
Definition at line 5 of file ppematclassesbase.c.
Referenced by ChangeMaterialPathUsed(), CreateMaterial(), GetCurrentMaterialPath(), and Init().
m_ParameterRemovalQueue
protected ref array<int> PPEClassBase::m_ParameterRemovalQueue private
Definition at line 9 of file ppematclassesbase.c.
Referenced by CreateDataStructure(), ParamUpdateQueueCleanup(), and ParamUpdateRemove().
m_ParameterUpdateQueueMap
protected ref map<int, ref array<int> > PPEClassBase::m_ParameterUpdateQueueMap private
Definition at line 8 of file ppematclassesbase.c.
Referenced by CreateDataStructure(), OnUpdate(), ParamUpdateQueueCleanup(), and SetParameterUpdating().
m_UpdatedParameters
protected ref array<int> PPEClassBase::m_UpdatedParameters private
Definition at line 10 of file ppematclassesbase.c.
Referenced by PPEDOF::ApplyValueChanges(), PPELightIntensityParamsNative::ApplyValueChanges(), ApplyValueChanges(), CreateDataStructure(), and InsertUpdatedParameter().