DayzKode: DeveloperTeleport Class Reference
DeveloperTeleport Class Reference
Static Private Member Functions
static void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
static protected void OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx)
static protected void OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx)
static void SetPlayerDirection (PlayerBase player, vector direction)
static void SetPlayerPosition (PlayerBase player, vector position)
static void TeleportAtCursor ()
static void TeleportAtCursorEx ()
Static Private Attributes
static protected const float TELEPORT_DISTANCE_MAX = 1000
static protected const float TELEPORT_DISTANCE_MAX_EX = 500
Detailed Description
Definition at line 1 of file developerteleport.c.
Member Function Documentation
OnRPC()
static void DeveloperTeleport::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline static private
Definition at line 108 of file developerteleport.c.
    {
        #ifdef DIAG_DEVELOPER
        if ( rpc_type == ERPCs.DEV_RPC_TELEPORT )
        {
            OnRPCSetPlayerPosition(player, ctx);
        }
        else if ( rpc_type == ERPCs.DEV_RPC_SET_PLAYER_DIRECTION )
        {
            OnRPCSetPlayerDirection(player, ctx);
        }
        #endif
    }
References OnRPCSetPlayerDirection(), and OnRPCSetPlayerPosition().
Referenced by PluginBase::OnRPC().
OnRPCSetPlayerDirection()
static protected void DeveloperTeleport::OnRPCSetPlayerDirection (PlayerBase player, ParamsReadContext ctx) inline static private
Definition at line 135 of file developerteleport.c.
    {
        Param3<float, float, float> p = new Param3<float, float, float>(0, 0, 0);
        if (ctx.Read(p))
        {
            vector v = "0 0 0";
            v[0] = p.param1;
            v[1] = p.param2;
            v[2] = p.param3;
            SetPlayerDirection(player, v);
        }
    }
References Serializer::Read(), and SetPlayerDirection().
Referenced by OnRPC().
OnRPCSetPlayerPosition()
static protected void DeveloperTeleport::OnRPCSetPlayerPosition (PlayerBase player, ParamsReadContext ctx) inline static private
Definition at line 122 of file developerteleport.c.
    {
        Param3<float, float, float> p = new Param3<float, float, float>(0, 0, 0);
        if (ctx.Read(p))
        {
            vector v = "0 0 0";
            v[0] = p.param1;
            v[1] = p.param2;
            v[2] = p.param3;
            SetPlayerPosition(player, v);
        }
    }
References Serializer::Read(), and SetPlayerPosition().
Referenced by OnRPC().
SetPlayerDirection()
static void DeveloperTeleport::SetPlayerDirection (PlayerBase player, vector direction) inline static private
Definition at line 82 of file developerteleport.c.
    {
        if ( GetGame().IsServer() )
        {
            HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
            if ( vehCmd )
            {
                Car car = Car.Cast( vehCmd.GetTransport() );
                if ( car )
                {
                    car.ForceDirection( direction );
                    car.Update();
                }
            }
            else
            {
                player.SetDirection( direction );
            }
        }
        else
        {
            Param3<float, float, float> params = new Param3<float, float, float>(direction[0], direction[1], direction[2]);
            player.RPCSingleParam(ERPCs.DEV_RPC_SET_PLAYER_DIRECTION, params, true);
        }
    }
References GetGame(), and HumanCommandVehicle::GetTransport().
Referenced by OnRPCSetPlayerDirection(), and TeleportAtCursorEx().
SetPlayerPosition()
static void DeveloperTeleport::SetPlayerPosition (PlayerBase player, vector position) inline static private
Definition at line 55 of file developerteleport.c.
    {
        if ( GetGame().IsServer() )
        {
            HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
            if ( vehCmd )
            {
                Car car = Car.Cast( vehCmd.GetTransport() );
                if ( car )
                {
                    car.ForcePosition( position );
                    car.Update();
                }
            }
            else
            {
                player.SetPosition( position );
            }
        }
        else
        {
            Param3<float, float, float> params = new Param3<float, float, float>(position[0], position[1], position[2]);
            player.RPCSingleParam(ERPCs.DEV_RPC_TELEPORT, params, true);
        }
    }
References GetGame(), and HumanCommandVehicle::GetTransport().
Referenced by OnRPCSetPlayerPosition(), PluginBase::Teleport(), TeleportAtCursor(), and TeleportAtCursorEx().
TeleportAtCursor()
static void DeveloperTeleport::TeleportAtCursor () inline static private
Definition at line 5 of file developerteleport.c.
    {
        if ( !DeveloperFreeCamera.IsFreeCameraEnabled() )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            vector pos_player = player.GetPosition();
            vector rayStart = GetGame().GetCurrentCameraPosition();
            vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * 1000;
            vector hitPos;
            vector hitNormal;
            int hitComponentIndex;
            DayZPhysics.RaycastRV(rayStart, rayEnd, hitPos, hitNormal, hitComponentIndex, NULL, NULL, player);
            float distance = vector.Distance( pos_player, hitPos );
            if ( distance < TELEPORT_DISTANCE_MAX )
            {
                SetPlayerPosition(PlayerBase.Cast( GetGame().GetPlayer() ), hitPos);
            }
            else
            {
                Debug.LogWarning("Distance for teleportation is too far!");
            }
        }
    }
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), Debug::LogWarning(), DayZPhysics::RaycastRV(), SetPlayerPosition(), and TELEPORT_DISTANCE_MAX.
TeleportAtCursorEx()
static void DeveloperTeleport::TeleportAtCursorEx () inline static private
Definition at line 33 of file developerteleport.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        vector rayStart = GetGame().GetCurrentCameraPosition();
        vector rayEnd = rayStart + GetGame().GetCurrentCameraDirection() * TELEPORT_DISTANCE_MAX_EX;
        vector hitPos;
        vector hitNormal;
        float hitFraction;
        Object hitObj;
        if (DayZPhysics.SphereCastBullet(rayStart, rayEnd, 0.01, PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.ITEM_LARGE|PhxInteractionLayers.BUILDING|PhxInteractionLayers.VEHICLE, player, hitObj, hitPos, hitNormal, hitFraction))
        {
            DeveloperTeleport.SetPlayerPosition( player, hitPos );
            if (DeveloperFreeCamera.IsFreeCameraEnabled())
            {
                DeveloperTeleport.SetPlayerDirection( player, FreeDebugCamera.GetInstance().GetDirection() );
            }
        }
    }
References CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), DeveloperFreeCamera::IsFreeCameraEnabled(), SetPlayerDirection(), SetPlayerPosition(), DayZPhysics::SphereCastBullet(), and TELEPORT_DISTANCE_MAX_EX.
Referenced by DeveloperFreeCamera::DisableFreeCamera(), and PluginBase::TeleportAtCursor().
Member Data Documentation
TELEPORT_DISTANCE_MAX
protected const float DeveloperTeleport::TELEPORT_DISTANCE_MAX = 1000 static private
Definition at line 3 of file developerteleport.c.
Referenced by TeleportAtCursor().
TELEPORT_DISTANCE_MAX_EX
protected const float DeveloperTeleport::TELEPORT_DISTANCE_MAX_EX = 500 static private
Definition at line 32 of file developerteleport.c.
Referenced by TeleportAtCursorEx().