DayzKode: UnconsciousnessMdfr Class Reference
UnconsciousnessMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int UNCONSIOUSS_COOLDOWN_TIME = 60
Detailed Description
Definition at line 1 of file unconsciousness.c.
Member Function Documentation
ActivateCondition()
override bool UnconsciousnessMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 13 of file unconsciousness.c.
    {
        if( player.GetHealth("","Shock") <=  PlayerConstants.UNCONSCIOUS_THRESHOLD )
        {
            return true;
        }
        return false;
    }
References PlayerConstants::UNCONSCIOUS_THRESHOLD.
DeactivateCondition()
override bool UnconsciousnessMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 45 of file unconsciousness.c.
    {
        if( player.GetHealth("","Shock") >= PlayerConstants.CONSCIOUS_THRESHOLD && player.GetPulseType() == EPulseType.REGULAR )
        {
            return true;
        }
        return false;
    }
References PlayerConstants::CONSCIOUS_THRESHOLD.
GetDebugText()
override string UnconsciousnessMdfr::GetDebugText () inline private
Definition at line 33 of file unconsciousness.c.
    {
        string text_pulse = "pulse type:"+m_Player.GetPulseType()+"|";
        string text_shock = (PlayerConstants.CONSCIOUS_THRESHOLD - m_Player.GetHealth("","Shock")).ToString();
        string debug_text = text_pulse + text_shock;
        return debug_text;
    }
References PlayerConstants::CONSCIOUS_THRESHOLD, m_Player, and ToString().
Init()
override void UnconsciousnessMdfr::Init () inline private
Definition at line 5 of file unconsciousness.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_UNCONSCIOUSNESS;
        m_TickIntervalInactive  = 0.5;
        m_TickIntervalActive    = 0.5;
    }
References m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void UnconsciousnessMdfr::OnActivate (PlayerBase player) inline private
Definition at line 22 of file unconsciousness.c.
    {
        DayZPlayerSyncJunctures.SendPlayerUnconsciousness(player, true);
    }
References DayZPlayerSyncJunctures::SendPlayerUnconsciousness().
OnDeactivate()
override void UnconsciousnessMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 27 of file unconsciousness.c.
    {
        player.m_UnconsciousEndTime = GetGame().GetTime();
        DayZPlayerSyncJunctures.SendPlayerUnconsciousness(player, false);
    }
References GetGame(), CGame::GetTime(), and DayZPlayerSyncJunctures::SendPlayerUnconsciousness().
OnReconnect()
override void UnconsciousnessMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 41 of file unconsciousness.c.
    {
    }
OnTick()
override void UnconsciousnessMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 54 of file unconsciousness.c.
    {
    }
Member Data Documentation
UNCONSIOUSS_COOLDOWN_TIME
const int UnconsciousnessMdfr::UNCONSIOUSS_COOLDOWN_TIME = 60 private
Definition at line 3 of file unconsciousness.c.