DayzKode: TriggerEvents Class Reference
TriggerEvents Class Reference
Private Member Functions
OnEnter
Called when an object enters the trigger
protected void Enter (TriggerInsider insider)
protected void OnEnterBeginEvent (TriggerInsider insider)
protected void OnEnterServerEvent (TriggerInsider insider)
protected void OnEnterClientEvent (TriggerInsider insider)
protected void OnEnterEndEvent (TriggerInsider insider)
OnStayStart
Called at the beginning of an update loop
protected void StayStart (int nrOfInsiders)
protected void OnStayStartBeginEvent (int nrOfInsiders)
protected void OnStayStartServerEvent (int nrOfInsiders)
protected void OnStayStartClientEvent (int nrOfInsiders)
protected void OnStayStartEndEvent (int nrOfInsiders)
OnStay
Called in the update loop
protected void Stay (TriggerInsider insider, float deltaTime)
protected void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
protected void OnStayServerEvent (TriggerInsider insider, float deltaTime)
protected void OnStayClientEvent (TriggerInsider insider, float deltaTime)
protected void OnStayEndEvent (TriggerInsider insider, float deltaTime)
OnStayFinish
Called at the end of an update loop
protected void StayFinish ()
protected void OnStayFinishBeginEvent ()
protected void OnStayFinishServerEvent ()
protected void OnStayFinishClientEvent ()
protected void OnStayFinishEndEvent ()
OnLeave
Called when an object leaves the trigger
protected void Leave (TriggerInsider insider)
protected void OnLeaveBeginEvent (TriggerInsider insider)
protected void OnLeaveServerEvent (TriggerInsider insider)
protected void OnLeaveClientEvent (TriggerInsider insider)
protected void OnLeaveEndEvent (TriggerInsider insider)
Detailed Description
Events API for triggers, keep in sync with AreaDamageEvents for consistency NOTE: The deltaTime passed in is the one for the Insider specifically.
Definition at line 3 of file triggerevents.c.
Member Function Documentation
Enter()
protected void TriggerEvents::Enter (TriggerInsider insider) inline private
Definition at line 9 of file triggerevents.c.
    {
        #ifdef TRIGGER_DEBUG_BASIC
        Debug.TriggerLog(GetDebugName(insider.GetObject()), "TriggerEvents", "", "Enter", GetDebugName(this));
        #endif
        OnEnterBeginEvent(insider);
        if ( GetGame().IsServer() )
            OnEnterServerEvent(insider);
        else
            OnEnterClientEvent(insider);
        OnEnterEndEvent(insider);
    }
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnEnterBeginEvent(), OnEnterClientEvent(), OnEnterEndEvent(), OnEnterServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::AddInsider().
Leave()
protected void TriggerEvents::Leave (TriggerInsider insider) inline private
Definition at line 109 of file triggerevents.c.
    {
        #ifdef TRIGGER_DEBUG_BASIC
        Debug.TriggerLog(GetDebugName(insider.GetObject()), "TriggerEvents", "", "Leave", GetDebugName(this));
        #endif
        OnLeaveBeginEvent(insider);
        if ( GetGame() && GetGame().IsServer() )
            OnLeaveServerEvent(insider);
        else
            OnLeaveClientEvent(insider);
        OnLeaveEndEvent(insider);
    }
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnLeaveBeginEvent(), OnLeaveClientEvent(), OnLeaveEndEvent(), OnLeaveServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::RemoveInsider().
OnEnterBeginEvent()
protected void TriggerEvents::OnEnterBeginEvent (TriggerInsider insider) inline private
Definition at line 24 of file triggerevents.c.
{}
Referenced by Enter().
OnEnterClientEvent()
protected void TriggerEvents::OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 26 of file triggerevents.c.
{}
Referenced by Enter().
OnEnterEndEvent()
protected void TriggerEvents::OnEnterEndEvent (TriggerInsider insider) inline private
Definition at line 27 of file triggerevents.c.
{}
Referenced by Enter().
OnEnterServerEvent()
protected void TriggerEvents::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 25 of file triggerevents.c.
{}
Referenced by Enter().
OnLeaveBeginEvent()
protected void TriggerEvents::OnLeaveBeginEvent (TriggerInsider insider) inline private
Definition at line 124 of file triggerevents.c.
{}
Referenced by Leave().
OnLeaveClientEvent()
protected void TriggerEvents::OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 126 of file triggerevents.c.
{}
Referenced by Leave().
OnLeaveEndEvent()
protected void TriggerEvents::OnLeaveEndEvent (TriggerInsider insider) inline private
Definition at line 127 of file triggerevents.c.
{}
Referenced by Leave().
OnLeaveServerEvent()
protected void TriggerEvents::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 125 of file triggerevents.c.
{}
Referenced by Leave().
OnStayBeginEvent()
protected void TriggerEvents::OnStayBeginEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 74 of file triggerevents.c.
{}
Referenced by Stay().
OnStayClientEvent()
protected void TriggerEvents::OnStayClientEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 76 of file triggerevents.c.
{}
Referenced by Stay().
OnStayEndEvent()
protected void TriggerEvents::OnStayEndEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 77 of file triggerevents.c.
{}
Referenced by Stay().
OnStayFinishBeginEvent()
protected void TriggerEvents::OnStayFinishBeginEvent () inline private
Definition at line 99 of file triggerevents.c.
{}
Referenced by StayFinish().
OnStayFinishClientEvent()
protected void TriggerEvents::OnStayFinishClientEvent () inline private
Definition at line 101 of file triggerevents.c.
{}
Referenced by StayFinish().
OnStayFinishEndEvent()
protected void TriggerEvents::OnStayFinishEndEvent () inline private
Definition at line 102 of file triggerevents.c.
{}
Referenced by StayFinish().
OnStayFinishServerEvent()
protected void TriggerEvents::OnStayFinishServerEvent () inline private
Definition at line 100 of file triggerevents.c.
{}
Referenced by StayFinish().
OnStayServerEvent()
protected void TriggerEvents::OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 75 of file triggerevents.c.
{}
Referenced by Stay().
OnStayStartBeginEvent()
protected void TriggerEvents::OnStayStartBeginEvent (int nrOfInsiders) inline private
Definition at line 49 of file triggerevents.c.
{}
Referenced by StayStart().
OnStayStartClientEvent()
protected void TriggerEvents::OnStayStartClientEvent (int nrOfInsiders) inline private
Definition at line 51 of file triggerevents.c.
{}
Referenced by StayStart().
OnStayStartEndEvent()
protected void TriggerEvents::OnStayStartEndEvent (int nrOfInsiders) inline private
Definition at line 52 of file triggerevents.c.
{}
Referenced by StayStart().
OnStayStartServerEvent()
protected void TriggerEvents::OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 50 of file triggerevents.c.
{}
Referenced by StayStart().
Stay()
protected void TriggerEvents::Stay (TriggerInsider insider, float deltaTime) inline private
Definition at line 59 of file triggerevents.c.
    {
        #ifdef TRIGGER_DEBUG_SPAM
        Debug.TriggerLog(GetDebugName(insider.GetObject()), "TriggerEvents", "", "Stay", GetDebugName(this));
        #endif
        OnStayBeginEvent(insider, deltaTime);
        if ( GetGame().IsServer() )
            OnStayServerEvent(insider, deltaTime);
        else
            OnStayClientEvent(insider, deltaTime);
        OnStayEndEvent(insider, deltaTime);
    }
References GetDebugName(), GetGame(), TriggerInsider::GetObject(), OnStayBeginEvent(), OnStayClientEvent(), OnStayEndEvent(), OnStayServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().
StayFinish()
protected void TriggerEvents::StayFinish () inline private
Definition at line 84 of file triggerevents.c.
    {
        #ifdef TRIGGER_DEBUG_SPAM
        Debug.TriggerLog("", "TriggerEvents", "", "StayFinish", GetDebugName(this));
        #endif
        OnStayFinishBeginEvent();
        if ( GetGame().IsServer() )
            OnStayFinishServerEvent();
        else
            OnStayFinishClientEvent();
        OnStayFinishEndEvent();
    }
References GetDebugName(), GetGame(), OnStayFinishBeginEvent(), OnStayFinishClientEvent(), OnStayFinishEndEvent(), OnStayFinishServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().
StayStart()
protected void TriggerEvents::StayStart (int nrOfInsiders) inline private
Definition at line 34 of file triggerevents.c.
    {
        #ifdef TRIGGER_DEBUG_SPAM
        Debug.TriggerLog(nrOfInsiders.ToString(), "TriggerEvents", "", "StayStart", GetDebugName(this));
        #endif
        OnStayStartBeginEvent(nrOfInsiders);
        if ( GetGame().IsServer() )
            OnStayStartServerEvent(nrOfInsiders);
        else
            OnStayStartClientEvent(nrOfInsiders);
        OnStayStartEndEvent(nrOfInsiders);
    }
References GetDebugName(), GetGame(), OnStayStartBeginEvent(), OnStayStartClientEvent(), OnStayStartEndEvent(), OnStayStartServerEvent(), and Debug::TriggerLog().
Referenced by Trigger::UpdateInsiders().