DayzKode: RemotePlayerDamageDebug Class Reference
RemotePlayerDamageDebug Class Reference
Private Member Functions
void AddDamage (float value_global, float value_blood, float value_shock)
void Debug ()
void Get (array< ref DamageData > damage_list)
PlayerBase GetPlayer ()
void GetReversed (array< ref DamageData > damage_list)
void InsertDamageObject (DamageData damage_object)
void RemotePlayerDamageDebug (PlayerBase player)
void Serialize (array< ref RemotePlayerDamageDebug > list)
Private Attributes
bool m_ChangedSinceSerialization
ref array< ref DamageData > m_DamageList = new array<ref DamageData>
PlayerBase m_Player
const int MAX_DAMAGE_RECORDS = 5
Detailed Description
Definition at line 1 of file remoteplayerdamagedebug.c.
Constructor & Destructor Documentation
RemotePlayerDamageDebug()
void RemotePlayerDamageDebug::RemotePlayerDamageDebug (PlayerBase player) inline private
Definition at line 9 of file remoteplayerdamagedebug.c.
    {
        m_Player = player;
    }
References m_Player.
Member Function Documentation
AddDamage()
void RemotePlayerDamageDebug::AddDamage (float value_global, float value_blood, float value_shock) inline private
Definition at line 14 of file remoteplayerdamagedebug.c.
    {
        m_ChangedSinceSerialization = true;
        DamageData damage_data = new DamageData( value_global, value_blood, value_shock );
        m_DamageList.InsertAt(damage_data,0);
        if( m_DamageList.Count() > MAX_DAMAGE_RECORDS )
        {
            m_DamageList.RemoveOrdered(MAX_DAMAGE_RECORDS);
        }
    }
References m_ChangedSinceSerialization, m_DamageList, and MAX_DAMAGE_RECORDS.
Referenced by PluginBase::OnDamageEvent().
Debug()
void RemotePlayerDamageDebug::Debug () inline private
Definition at line 63 of file remoteplayerdamagedebug.c.
    {
        string output;
        for(int i = 0; i < m_DamageList.Count(); i++)
        {
            output = output + m_DamageList.Get(i).ToString() + ", ";
        }
        PrintString("damage values for player " + m_Player.ToString()+":" + output);
    }
References m_DamageList, m_Player, and PrintString().
Referenced by DebugDamage(), and OnRPC().
Get()
void RemotePlayerDamageDebug::Get (array< ref DamageData > damage_list) inline private
Definition at line 37 of file remoteplayerdamagedebug.c.
    {
        for(int i = 0; i < m_DamageList.Count(); i++)
        {
            damage_list.Insert(m_DamageList.Get(i));
        }
    }
References m_DamageList.
GetPlayer()
PlayerBase RemotePlayerDamageDebug::GetPlayer () inline private
Definition at line 31 of file remoteplayerdamagedebug.c.
    {
        return m_Player;
    }
References m_Player.
Referenced by MergeDamage(), and OnRPC().
GetReversed()
void RemotePlayerDamageDebug::GetReversed (array< ref DamageData > damage_list) inline private
Definition at line 45 of file remoteplayerdamagedebug.c.
    {
        int index = m_DamageList.Count() - 1;
        for(; index >= 0; index--)
        {
            damage_list.Insert(m_DamageList.Get(index));
        }
    }
References m_DamageList.
Referenced by MergeDamage(), and UpdateDamageWidget().
InsertDamageObject()
void RemotePlayerDamageDebug::InsertDamageObject (DamageData damage_object) inline private
Definition at line 25 of file remoteplayerdamagedebug.c.
    {
        m_DamageList.Insert(damage_object);
    }
References m_DamageList.
Referenced by MergeDamage().
Serialize()
void RemotePlayerDamageDebug::Serialize (array< ref RemotePlayerDamageDebug > list) inline private
Definition at line 54 of file remoteplayerdamagedebug.c.
    {
        if( m_ChangedSinceSerialization )
        {
            list.Insert(this);
        }
        m_ChangedSinceSerialization = false;
    }
References m_ChangedSinceSerialization.
Member Data Documentation
m_ChangedSinceSerialization
bool RemotePlayerDamageDebug::m_ChangedSinceSerialization private
Definition at line 5 of file remoteplayerdamagedebug.c.
Referenced by AddDamage(), and Serialize().
m_DamageList
ref array<ref DamageData> RemotePlayerDamageDebug::m_DamageList = new array<ref DamageData> private
Definition at line 7 of file remoteplayerdamagedebug.c.
Referenced by AddDamage(), Debug(), Get(), GetReversed(), and InsertDamageObject().
m_Player
PlayerBase RemotePlayerDamageDebug::m_Player private
Definition at line 4 of file remoteplayerdamagedebug.c.
Referenced by Debug(), GetPlayer(), and RemotePlayerDamageDebug().
MAX_DAMAGE_RECORDS
const int RemotePlayerDamageDebug::MAX_DAMAGE_RECORDS = 5 private
Definition at line 3 of file remoteplayerdamagedebug.c.
Referenced by AddDamage().