DayzKode: AutoHeightSpacer Class Reference
AutoHeightSpacer Class Reference
Private Member Functions
override bool OnChildRemove (Widget w, Widget child)
void OnWidgetScriptInit (Widget w)
void Update ()
Private Attributes
reference bool AlignChilds
reference int Gap
protected Widget m_root
reference int MaxHeight
reference int MinHeight
reference float Top
Detailed Description
Definition at line 2 of file autoheightspacer.c.
Member Function Documentation
OnChildRemove()
override bool AutoHeightSpacer::OnChildRemove (Widget w, Widget child) inline private
Definition at line 121 of file autoheightspacer.c.
{
        if (w == m_root)
        {
            Update();
        }
        return false;
    }
References m_root, and Update().
OnWidgetScriptInit()
void AutoHeightSpacer::OnWidgetScriptInit (Widget w) inline private
Definition at line 113 of file autoheightspacer.c.
    {
        m_root = w;
        m_root.SetHandler(this);
        m_root.SetFlags(WidgetFlags.VEXACTPOS);
        Update();
    }
References m_root, and Update().
Update()
void AutoHeightSpacer::Update () inline private
Definition at line 11 of file autoheightspacer.c.
    {
        float x = 0;
        float y = 0;
        float width = 0;
        float height = 0;
        float heightOld = 0;
        float top = Top;
        float rowRight;
        float rowHeight;
        float rowWidth;
        Widget child = m_root.GetChildren();
        //PrintString(m_root.GetName() + ": AutoHeightSpacer::Update()");
        if ( !AlignChilds ) top = -100000;
        if (child != NULL)
        {
        // first row init
        m_root.GetScreenSize(rowWidth, height);
        rowHeight = 0;
        rowRight = rowWidth;
        while (child)
        {
            if (child.IsVisible() == false || child.GetName() == "SelectedContainer" || child.GetName() == "Icon")
            {
                // skip invisible widgets
                child = child.GetSibling();
                continue;
            }
            child.GetScreenSize(width, height);
            if (AlignChilds)
            {
                child.SetFlags(WidgetFlags.EXACTPOS, false);
                // no space left in this row, move to next one
                if (rowRight < width)
                {
                    top += rowHeight;
                    if ( rowHeight > 0 ) top += Gap;
                    rowRight = rowWidth;
                    rowHeight = 0;
                }
                // increase row height if necessary
                if (height > rowHeight) rowHeight = height;
                child.SetPos(rowWidth - rowRight, top, false);
                rowRight -= width + Gap;
            }
            else
            {
                child.GetScreenPos(x, y);
                y += height;
                if (top < y) top = y;
            }
            child = child.GetSibling();
        }
        // add last row height;
        top += rowHeight;
        if (AlignChilds)
        {
            height = top;
        }
        else
        {
            m_root.GetScreenPos(x, y);
            height = top - y;
        }
        }
        m_root.GetSize(width, heightOld);
        if (MaxHeight > 0 && height > MaxHeight)
        {
            height = MaxHeight;
        }
        if (MinHeight > height)
        {
            height = MinHeight;
        }
        if (Math.AbsInt(heightOld - height) > 1)
        {
            m_root.SetSize(width, height);
        }
        else if (AlignChilds)
        {
            m_root.Update();
        }
        return;
    }
References Math::AbsInt(), AlignChilds, Gap, m_root, MaxHeight, MinHeight, Top, x, and y.
Referenced by AddAgent(), AddModifier(), HudDebugWinBase::AddValue(), UIScriptedMenu::LateInit(), OnChildRemove(), NoticeSpacer::OnEvent(), OnWidgetScriptInit(), ScriptedWidgetEventHandler::Show(), and HudDebugWinBase::Update().
Member Data Documentation
AlignChilds
reference bool AutoHeightSpacer::AlignChilds private
Definition at line 4 of file autoheightspacer.c.
Referenced by Update().
Gap
reference int AutoHeightSpacer::Gap private
Definition at line 7 of file autoheightspacer.c.
Referenced by Update().
m_root
protected Widget AutoHeightSpacer::m_root private
Definition at line 9 of file autoheightspacer.c.
Referenced by OnChildRemove(), OnWidgetScriptInit(), and Update().
MaxHeight
reference int AutoHeightSpacer::MaxHeight private
Definition at line 6 of file autoheightspacer.c.
Referenced by Update().
MinHeight
reference int AutoHeightSpacer::MinHeight private
Definition at line 5 of file autoheightspacer.c.
Referenced by Update().
Top
reference float AutoHeightSpacer::Top private
Definition at line 8 of file autoheightspacer.c.
Referenced by Update().