DayzKode: ActionBuildPartSwitch Class Reference
ActionBuildPartSwitch Class Reference
Private Member Functions
void ActionBuildPartSwitch ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedLeaning ()
override void CreateConditionComponents ()
override bool IsInstant ()
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool RemoveForceTargetAfterUse ()
void SetNextIndex (ActionData action_data)
override bool UseAcknowledgment ()
Detailed Description
Definition at line 2 of file actionbuildpartswitch.c.
Constructor & Destructor Documentation
ActionBuildPartSwitch()
void ActionBuildPartSwitch::ActionBuildPartSwitch () inline private
Definition at line 4 of file actionbuildpartswitch.c.
    {
        //m_StanceMask = DayZPlayerConstants.STANCEMASK_NOTRAISED;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_FullBody = true;
        m_Text = "#switch_to_the_next_part";
    }
References m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionBuildPartSwitch::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 38 of file actionbuildpartswitch.c.
    {
        return false;
    }
CanBeUsedLeaning()
override bool ActionBuildPartSwitch::CanBeUsedLeaning () inline private
Definition at line 33 of file actionbuildpartswitch.c.
    {
        return false;
    }
CreateConditionComponents()
override void ActionBuildPartSwitch::CreateConditionComponents () inline private
Definition at line 12 of file actionbuildpartswitch.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.BASEBUILDING);
    }
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
IsInstant()
override bool ActionBuildPartSwitch::IsInstant () inline private
Definition at line 18 of file actionbuildpartswitch.c.
    {
        return true;
    }
OnStartClient()
override void ActionBuildPartSwitch::OnStartClient (ActionData action_data) inline private
Definition at line 44 of file actionbuildpartswitch.c.
    {
        super.OnStartClient( action_data );
        SetNextIndex(action_data);
    }
References SetNextIndex().
OnStartServer()
override void ActionBuildPartSwitch::OnStartServer (ActionData action_data) inline private
Definition at line 51 of file actionbuildpartswitch.c.
    {
        super.OnStartServer( action_data );
        if (!GetGame().IsMultiplayer())
            SetNextIndex(action_data);
    }
References GetGame(), and SetNextIndex().
RemoveForceTargetAfterUse()
override bool ActionBuildPartSwitch::RemoveForceTargetAfterUse () inline private
Definition at line 23 of file actionbuildpartswitch.c.
    {
        return false;
    }
SetNextIndex()
void ActionBuildPartSwitch::SetNextIndex (ActionData action_data) inline private
Definition at line 59 of file actionbuildpartswitch.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        construction_action_data.SetNextIndex();
    }
References ActionData::m_Player, and ConstructionActionData::SetNextIndex().
Referenced by OnStartClient(), and OnStartServer().
UseAcknowledgment()
override bool ActionBuildPartSwitch::UseAcknowledgment () inline private
Definition at line 28 of file actionbuildpartswitch.c.
    {
        return true;
    }