DayzKode: ActionLockAttachment Class Reference
ActionLockAttachment Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionLockAttachment ()
override void CreateConditionComponents ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnEnd (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
Private Attributes
private const string LOCK_VERSION = "#widget_lock"
private string m_Name = LOCK_VERSION
private const string UNLOCK_VERSION = "#widget_unlock"
Detailed Description
Definition at line 20 of file actionlockattachment.c.
Constructor & Destructor Documentation
ActionLockAttachment()
void ActionLockAttachment::ActionLockAttachment () inline private
Definition at line 26 of file actionlockattachment.c.
    {
        m_CallbackClass = ActionLockAttachmentCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_FullBody = true;
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionLockAttachment::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 53 of file actionlockattachment.c.
    {
        if ( !target )
            return false;
        EntityAI parent_EAI = EntityAI.Cast(target.GetParent());
        ItemBase target_IB = ItemBase.Cast(target.GetObject());
        array<int> compLock = item.m_CompatibleLocks;
        int targetType = eLockTypes.NONE;
        if ( target_IB && parent_EAI )
        {
            //CAR DOOR HANDLING
            //I don't really like this, but sometimes specifics have to be handled in generics
            CarDoor targetDoor = CarDoor.Cast(target_IB);
            if ( targetDoor )
            {
                InventoryLocation loc = new InventoryLocation();
                bool isPresent = targetDoor.GetInventory().GetCurrentInventoryLocation( loc );
                if ( !isPresent || loc.GetSlot() == -1 )
                    return false;
                string slotName = InventorySlots.GetSlotName( loc.GetSlot() );
                if ( slotName && CarScript.Cast( parent_EAI ).GetCarDoorsState( slotName ) != CarDoorState.DOORS_OPEN )
                    return false;
            }
            //END OF CAR DOOR SPECIFICS
            if ( target_IB.IsLockedInSlot() )
                m_Name = UNLOCK_VERSION;
            else if ( target_IB.IsAlive() )
                m_Name = LOCK_VERSION;
            else if ( !target_IB.IsLockedInSlot() )
                return false;
            targetType = target_IB.GetLockType();
            for (int i = 0; i < compLock.Count(); i++)
            {
                if ( targetType == compLock[i] && targetType != eLockTypes.NONE)
                {
                    return true;
                }
            }
        }
        return false;
    }
References CarScript::GetCarDoorsState(), InventoryLocation::GetSlot(), InventorySlots::GetSlotName(), LOCK_VERSION, m_Name, and UNLOCK_VERSION.
CreateConditionComponents()
override void ActionLockAttachment::CreateConditionComponents () inline private
Definition at line 47 of file actionlockattachment.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursorNoRuinCheck(UAMaxDistances.SMALL);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
OnActionInfoUpdate()
override void ActionLockAttachment::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 36 of file actionlockattachment.c.
    {
        ItemBase target_IB = ItemBase.Cast(target.GetObject());
        if ( target_IB.IsLockedInSlot() )
            m_Text = UNLOCK_VERSION;
        else if ( target_IB.IsAlive() )
            m_Text = LOCK_VERSION;
        else
            m_Text = "";
    }
References LOCK_VERSION, m_Text, and UNLOCK_VERSION.
OnEnd()
override void ActionLockAttachment::OnEnd (ActionData action_data) inline private
Definition at line 116 of file actionlockattachment.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            ItemBase target_IB = ItemBase.Cast( action_data.m_Target.GetObject() );
            Param2<bool, string> play = new Param2<bool, string>( false, action_data.m_MainItem.GetLockSoundSet() );
            GetGame().RPCSingleParam( target_IB, ERPCs.RPC_SOUND_LOCK_ATTACH, play, true );
        }
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
OnEndAnimationLoop()
override void ActionLockAttachment::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 126 of file actionlockattachment.c.
    {
        super.OnEndAnimationLoop( action_data );
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            ItemBase target_IB = ItemBase.Cast( action_data.m_Target.GetObject() );
            Param2<bool, string> play = new Param2<bool, string>( false, action_data.m_MainItem.GetLockSoundSet() );
            GetGame().RPCSingleParam( target_IB, ERPCs.RPC_SOUND_LOCK_ATTACH, play, true );
        }
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void ActionLockAttachment::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 138 of file actionlockattachment.c.
    {
        ItemBase target_IB = ItemBase.Cast(action_data.m_Target.GetObject());
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 5);
        if (target_IB.IsLockedInSlot())
        {
            target_IB.UnlockFromParent();
            return;
        }
        target_IB.LockToParent();
    }
References ActionData::m_MainItem, and ActionData::m_Target.
OnStartAnimationLoop()
override void ActionLockAttachment::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 104 of file actionlockattachment.c.
    {
        super.OnStartAnimationLoop( action_data );
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            ItemBase target_IB = ItemBase.Cast( action_data.m_Target.GetObject() );
            Param2<bool, string> play = new Param2<bool, string>( true, action_data.m_MainItem.GetLockSoundSet() );
            GetGame().RPCSingleParam( target_IB, ERPCs.RPC_SOUND_LOCK_ATTACH, play, true );
        }
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, and CGame::RPCSingleParam().
Member Data Documentation
LOCK_VERSION
private const string ActionLockAttachment::LOCK_VERSION = "#widget_lock" private
Definition at line 22 of file actionlockattachment.c.
Referenced by ActionCondition(), and OnActionInfoUpdate().
m_Name
private string ActionLockAttachment::m_Name = LOCK_VERSION private
Definition at line 24 of file actionlockattachment.c.
Referenced by ActionCondition().
UNLOCK_VERSION
private const string ActionLockAttachment::UNLOCK_VERSION = "#widget_unlock" private
Definition at line 23 of file actionlockattachment.c.
Referenced by ActionCondition(), and OnActionInfoUpdate().