DayzKode: ActionManagerClient Class Reference
ActionManagerClient Class Reference
Private Member Functions
void ActionManagerClient (PlayerBase player)
protected void ActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data=NULL)
bool CanPerformActionFromInventory (ItemBase mainItem, ItemBase targetItem)
bool CanPerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem)
bool CanSetActionFromInventory (ItemBase mainItem, ItemBase targetItem)
void ClearForceTarget ()
void EjectAction (ActionBase action)
void EjectAction (typename actionType)
void EndActionInput ()
ItemBase FindActionItem ()
override ActionTarget FindActionTarget ()
protected void FindContextualUserActions (int pCurrentCommandID)
void ForceTarget (Object targetObject)
ActionBase GetPossibleAction (typename inputType)
int GetPossibleActionCount (typename inputType)
int GetPossibleActionIndex (typename inputType)
array< ActionBase > GetPossibleActions (typename inputType)
override GetSelectedActionCategory ()
void HandleInputsOnActionEnd ()
void HandleInputsOnActionStart (ActionBase action)
protected bool HasHandInventoryReservation ()
void InjectAction (ActionBase action, ActionTarget target, ItemBase item)
void InjectAction (typename actionType, ActionTarget target, ItemBase item)
void InputsUpdate ()
override void Interrupt ()
protected bool LockInventory (ActionData action_data)
override void OnActionEnd ()
override void OnInstantAction (typename user_action_type, Param data=NULL)
override void OnJumpStart ()
void PerformActionFromInventory (ItemBase mainItem, ItemBase targetItem)
void PerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem)
void PerformActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data=NULL)
void RegisterInputs (PlayerBase player)
void RequestEndAction ()
void RequestInterruptAction ()
client requests action interrupt
void ResetInputsActions ()
void ResetInputsState ()
override void SelectFirstActionCategory ()
override void SelectNextAction ()
override void SelectNextActionCategory ()
override void SelectPrevAction ()
override void SelectPrevActionCategory ()
void SetActionFromInventory (ItemBase mainItem, ItemBase targetItem)
void SetActioninputOrder ()
void SetDefaultInputsOrder ()
void SetInventoryAction (ActionBase action_name, ActionTarget target, ItemBase main_item)
void SetInventoryAction (ActionBase action_name, ItemBase target_item, ItemBase main_item)
void UnlockInventory (ActionData action_data)
void UnsetInventoryAction ()
override void Update (int pCurrentCommandID)
void UpdateActionCategoryPriority ()
Static Private Member Functions
static ActionVariantManager GetVariantManager (typename actionName)
Private Attributes
protected bool m_ActionInputWantEnd_Send
protected bool m_ActionPossible
protected bool m_ActionWantEndRequest_Send
protected ref array< ActionInput > m_DefaultOrderOfActionInputs
private ref ActionTarget m_ForceTarget
protected ref InventoryLocation m_HandInventoryLocationTest
protected ref InventoryActionHandler m_InventoryActionHandler
protected int m_LastAcknowledgmentID
protected ref array< ActionInput > m_OrderedStandartActionInputs
protected ref array< ActionInput > m_OrederedAllActionInput
protected ref ActionData m_PendingActionData
protected ref TTypeNameActionInputMap m_RegistredInputsMap
protected ref array< ref InventoryLocation > m_ReservedInventoryLocations
protected int m_SelectedActionInputToSrollIndex
private ref ActionTargets m_Targets
Detailed Description
Definition at line 4 of file actionmanagerclient.c.
Constructor & Destructor Documentation
ActionManagerClient()
void ActionManagerClient::ActionManagerClient (PlayerBase player) inline private
Definition at line 25 of file actionmanagerclient.c.
    {
        //ActionManagerBase(player);
        m_HandInventoryLocationTest = new InventoryLocation;
        m_HandInventoryLocationTest.SetHands(player,null);
        m_LastAcknowledgmentID = 1;
        m_Targets   = new ActionTargets(player);
        m_ReservedInventoryLocations = new array<ref InventoryLocation>;
        m_InventoryActionHandler = new InventoryActionHandler(player);
        m_ActionWantEndRequest_Send = false;
        m_ActionInputWantEnd_Send = false;
        RegisterInputs(player);
        m_SelectedActionInputToSrollIndex = 0;
    }
References m_ActionInputWantEnd_Send, m_ActionWantEndRequest_Send, m_HandInventoryLocationTest, m_InventoryActionHandler, m_LastAcknowledgmentID, m_ReservedInventoryLocations, m_SelectedActionInputToSrollIndex, m_Targets, RegisterInputs(), and InventoryLocation::SetHands().
Member Function Documentation
ActionStart()
protected void ActionManagerClient::ActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data = NULL) inline private
Definition at line 588 of file actionmanagerclient.c.
    {
        if ( !m_CurrentActionData && action )
        {
            m_ActionWantEndRequest_Send = false;
            m_ActionInputWantEnd_Send = false;
            m_ActionWantEndRequest = false;
            m_ActionInputWantEnd = false;
            if ( action.CanBePerformedFromQuickbar() )
                m_Player.SetActionEndInput(action);
            HandleInputsOnActionStart(action);
            if ( LogManager.IsActionLogEnable() )
            {
                Debug.ActionLog("Item = " + item + ", " + target.DumpToString(), action.ToString() , "n/a", "ActionStart", m_Player.ToString() );
            }
            m_Interrupted = false;
            if ( GetGame().IsMultiplayer() && !action.IsLocal() )
            {
                if (!ScriptInputUserData.CanStoreInputUserData())
                {
                    DPrint("ScriptInputUserData already posted - ActionManagerClient");
                    if ( LogManager.IsActionLogEnable() )
                    {
                        Debug.ActionLog("Cannot start because ScriptInputUserData is already used", action.ToString() , "n/a", "ActionStart", m_Player.ToString() );
                    }
                    return;
                }
            }
            if ( !action.SetupAction(m_Player, target, item, m_CurrentActionData, extra_data ))
            {
                DPrint("Can not inicialize action" + action + " - ActionManagerClient");
                m_CurrentActionData = NULL;
                return;
            }
            if ( LogManager.IsActionLogEnable() )
            {
                Debug.ActionLog("Action data created wait to start", action.ToString() , "n/a", "ActionStart", m_Player.ToString() );
            }
            if ( GetGame().IsMultiplayer() && !action.IsLocal() )
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_STANDARD_ACTION_START);
                ctx.Write(action.GetID());
                action.WriteToContext(ctx, m_CurrentActionData);
                if (action.UseAcknowledgment())
                {
                    m_CurrentActionData.m_State = UA_AM_PENDING;
                    m_PendingActionAcknowledgmentID = ++m_LastAcknowledgmentID;
                    ctx.Write(m_PendingActionAcknowledgmentID);
                }
                ctx.Send();
                if (!action.UseAcknowledgment())
                {
                    action.Start(m_CurrentActionData);
                    if( action.IsInstant() )
                        OnActionEnd();
                }
            }
            else
            {
                action.Start(m_CurrentActionData);
                if( action.IsInstant() )
                    OnActionEnd();
            }
        }
    }
References Debug::ActionLog(), ScriptInputUserData::CanStoreInputUserData(), DPrint(), GetGame(), HandleInputsOnActionStart(), INPUT_UDT_STANDARD_ACTION_START, LogManager::IsActionLogEnable(), ActionManagerBase::m_ActionInputWantEnd, m_ActionInputWantEnd_Send, ActionManagerBase::m_ActionWantEndRequest, m_ActionWantEndRequest_Send, ActionManagerBase::m_CurrentActionData, ActionManagerBase::m_Interrupted, m_LastAcknowledgmentID, ActionManagerBase::m_PendingActionAcknowledgmentID, ActionManagerBase::m_Player, ActionData::m_State, OnActionEnd(), ScriptInputUserData::Send(), UA_AM_PENDING, and Serializer::Write().
Referenced by InputsUpdate(), OnInstantAction(), PerformActionFromInventory(), PerformActionFromQuickbar(), and PerformActionStart().
CanPerformActionFromInventory()
bool ActionManagerClient::CanPerformActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1020 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        target = new ActionTarget(targetItem, null, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            array<ActionBase_Basic> actions;
            ActionBase picked_action;
            int i;
            //First check single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromInventory() )
                    {
                        if( hasTarget == picked_action.HasTarget())
                            return true;
                    }
                }
            }
            //Inventory specific actions
            mainItem.GetActions(InventoryOnlyActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) )
                    {
                        if( hasTarget == picked_action.HasTarget())
                            return true;
                    }
                }
            }
        }
        return false;
    }
References ActionBase(), ActionTarget, ActionManagerBase::m_Player, and vector::Zero.
Referenced by Attachments::CanCombineAmmo(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), and ItemManager::GetCombinationFlags().
CanPerformActionFromQuickbar()
bool ActionManagerClient::CanPerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 890 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        target = new ActionTarget(targetItem, null, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            array<ActionBase_Basic> actions;
            ActionBase picked_action;
            int i;
            mainItem.GetActions(QuickaBarActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) )
                    {
                        if( hasTarget == picked_action.HasTarget())
                            return true;
                    }
                }
            }
            //First check continuous actions
            mainItem.GetActions(ContinuousDefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromQuickbar() )
                    {
                        if( hasTarget == picked_action.HasTarget())
                            return true;
                    }
                }
            }
            //second single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.HasTarget() && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromQuickbar() )
                    {
                        if( hasTarget == picked_action.HasTarget())
                            return true;
                    }
                }
            }
        }
        return false;
    }
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), ActionManagerBase::m_Player, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart().
CanSetActionFromInventory()
bool ActionManagerClient::CanSetActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1118 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        EntityAI parent = null;
        if (targetItem)
        {
            parent = targetItem.GetHierarchyParent();
        }
        target = new ActionTarget(targetItem, parent, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            array<ActionBase_Basic> actions;
            array<ref ActionBase> variant_actions;
            ActionBase picked_action;
            int variants_count,v;
            //First check single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( int i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action.HasVariants() )
                    {
                        picked_action.UpdateVariants( itemInHand, targetItem, -1);
                        picked_action.GetVariants( variant_actions );
                        for ( v = 0; v < variant_actions.Count(); v ++)
{
                            picked_action = variant_actions[v];
                            if ( picked_action && picked_action.CanBeSetFromInventory() && picked_action.Can(m_Player,target, itemInHand) )
{
                                if( hasTarget == picked_action.HasTarget())
                                    return true;
                            }
                        }
                    }
                    else
                    {
                        if ( picked_action && picked_action.CanBeSetFromInventory() && picked_action.Can(m_Player,target, itemInHand) )
{
                            if( hasTarget == picked_action.HasTarget())
                                return true;
                        }
                    }
                }
            }
            //second continuous actions
            mainItem.GetActions(ContinuousDefaultActionInput, actions);
            if (actions)
            {
                for ( int j = 0; j < actions.Count(); j++ )
                {
                    picked_action = ActionBase.Cast(actions[j]);
                    if ( picked_action.HasVariants() )
                    {
                        picked_action.UpdateVariants( itemInHand, targetItem, -1 );
                        picked_action.GetVariants( variant_actions );
                        for ( v = 0; v < variant_actions.Count(); v ++)
{
                            picked_action = variant_actions[v];
                            if ( picked_action && picked_action.HasTarget() && picked_action.CanBeSetFromInventory() && picked_action.Can(m_Player,target, itemInHand) )
{
                                if( hasTarget == picked_action.HasTarget())
                                    return true;
                            }
                        }
                    }
                    else
                    {
                        if ( picked_action && picked_action.HasTarget() && picked_action.CanBeSetFromInventory() && picked_action.Can(m_Player,target, itemInHand) )
{
                            if( hasTarget == picked_action.HasTarget())
                                return true;
                        }
                    }
                }
            }
        }
        return false;
    }
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), ActionManagerBase::m_Player, and vector::Zero.
Referenced by Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), HandsContainer::GetCombinationFlags(), and ItemManager::GetCombinationFlags().
ClearForceTarget()
void ActionManagerClient::ClearForceTarget () inline private
Definition at line 461 of file actionmanagerclient.c.
    {
        m_ForceTarget = NULL;
    }
References m_ForceTarget.
Referenced by InventoryActionHandler::DeactiveAction(), and ManBase::OnQuickBarContinuousUseEnd().
EjectAction() [1/2]
void ActionManagerClient::EjectAction (ActionBase action) inline private
Definition at line 440 of file actionmanagerclient.c.
    {
        ActionInput ai = action.GetInput();
        ai.ClearForcedAction();
    }
References ActionInput::ClearForcedAction().
Referenced by InventoryActionHandler::DeactiveAction(), and EjectAction().
EjectAction() [2/2]
void ActionManagerClient::EjectAction (typename actionType) inline private
Definition at line 446 of file actionmanagerclient.c.
    {
        ActionBase action = GetAction(actionType);
        EjectAction(action);
    }
References ActionBase(), EjectAction(), and GetAction().
EndActionInput()
void ActionManagerClient::EndActionInput () inline private
Definition at line 330 of file actionmanagerclient.c.
    {
        if (!m_ActionInputWantEnd_Send)
        {
            m_ActionInputWantEnd = true;
        }
    }
References ActionManagerBase::m_ActionInputWantEnd, and m_ActionInputWantEnd_Send.
Referenced by InputsUpdate(), and ManBase::OnQuickBarContinuousUseEnd().
FindActionItem()
ItemBase ActionManagerClient::FindActionItem () inline private
Definition at line 502 of file actionmanagerclient.c.
    {
        ItemBase item;
        if ( m_Player && m_Player.GetItemInHands() && m_Player.GetItemInHands().IsItemBase() )
        {
            item = m_Player.GetItemInHands();
        }
        return item;
    }
References ActionManagerBase::m_Player.
Referenced by FindContextualUserActions().
FindActionTarget()
override ActionTarget ActionManagerClient::FindActionTarget () inline private
Definition at line 468 of file actionmanagerclient.c.
    {
        if(m_ForceTarget)
            return m_ForceTarget;
        ActionTarget action_target;
        action_target = NULL;
        int targetsCount = m_Targets.GetTargetsCount();
        if( targetsCount )
        {
            for( int i = 0; i < targetsCount; ++i )
            {
                action_target = m_Targets.GetTarget(i);
                Object targetObject = action_target.GetObject();
                Object targetParent = action_target.GetParent();
                if( targetParent && targetParent.IsEntityAI() )
                {
                    break;
                }
                if( targetObject && (targetObject.IsEntityAI() || targetObject.IsWoodBase() || targetObject.IsRock()) )
                {
                    break;
                }
            }
        }
        else
        {
            action_target = new ActionTarget(null, null, -1, vector.Zero, -1 );
        }
        return action_target;
    }
References ActionTarget, ActionTargets::GetTarget(), ActionTargets::GetTargetsCount(), m_ForceTarget, m_Targets, and vector::Zero.
Referenced by FindContextualUserActions().
FindContextualUserActions()
protected void ActionManagerClient::FindContextualUserActions (int pCurrentCommandID) inline private
Definition at line 520 of file actionmanagerclient.c.
    {
        // TODO: NEEDS OPTIMIZATION (focus on UpdatePossibleActions > CraftingManager::OnUpdate)
        m_ActionsAvaibale = false;
        if ( !m_ActionPossible || HasHandInventoryReservation() || GetGame().IsInventoryOpen())
        {
            ResetInputsActions();
            return;
        }
        if ( !GetRunningAction() )
        {
            ActionBase action;
            ActionTarget    target;
            ItemBase        item;
            // Gathering current inputs
            m_ActionsAvaibale = true;
            item = FindActionItem();
            target = FindActionTarget();
            int actionConditionMask = ActionBase.ComputeConditionMask(m_Player,target,item);
            for (int i = 0; i < m_OrederedAllActionInput.Count();i++)
            {
                ActionInput ain = m_OrederedAllActionInput[i];
                ain.UpdatePossibleActions(m_Player,target,item, actionConditionMask);
            }
            SetActionContext( target,item );
        }
    }
References ActionBase(), ActionTarget, FindActionItem(), FindActionTarget(), GetGame(), ActionManagerBase::GetRunningAction(), HasHandInventoryReservation(), IsInventoryOpen(), m_ActionPossible, ActionManagerBase::m_ActionsAvaibale, m_OrederedAllActionInput, ActionManagerBase::m_Player, ResetInputsActions(), ActionManagerBase::SetActionContext(), and ActionInput::UpdatePossibleActions().
Referenced by Update().
ForceTarget()
void ActionManagerClient::ForceTarget (Object targetObject) inline private
Definition at line 452 of file actionmanagerclient.c.
    {
        Object parent = null;
        EntityAI targetEntity = EntityAI.Cast(targetObject);
        if (targetEntity)
            parent = targetEntity.GetHierarchyParent();
        m_ForceTarget = new ActionTarget(targetObject, parent, -1, vector.Zero, -1);
    }
References ActionTarget, m_ForceTarget, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart(), and InventoryActionHandler::SetAction().
GetPossibleAction()
ActionBase ActionManagerClient::GetPossibleAction (typename inputType) inline private
Definition at line 385 of file actionmanagerclient.c.
    {
        ActionInput action_input = m_RegistredInputsMap.Get(inputType);
        if(action_input)
        {
            return action_input.GetAction();
        }
        return NULL;
    }
References ActionInput::GetAction(), and m_RegistredInputsMap.
GetPossibleActionCount()
int ActionManagerClient::GetPossibleActionCount (typename inputType) inline private
Definition at line 415 of file actionmanagerclient.c.
    {
        ActionInput action_input = m_RegistredInputsMap.Get(inputType);
        if(action_input)
        {
            return action_input.GetPossibleActionsCount();
        }
        return 0;
    }
References ActionInput::GetPossibleActionsCount(), and m_RegistredInputsMap.
GetPossibleActionIndex()
int ActionManagerClient::GetPossibleActionIndex (typename inputType) inline private
Definition at line 405 of file actionmanagerclient.c.
    {
        ActionInput action_input = m_RegistredInputsMap.Get(inputType);
        if(action_input)
        {
            return action_input.GetPossibleActionIndex();
        }
        return -1;
    }
References ActionInput::GetPossibleActionIndex(), and m_RegistredInputsMap.
GetPossibleActions()
array< ActionBase > ActionManagerClient::GetPossibleActions (typename inputType) inline private
Definition at line 395 of file actionmanagerclient.c.
    {
        ActionInput action_input = m_RegistredInputsMap.Get(inputType);
        if(action_input)
        {
            return action_input.GetPossibleActions();
        }
        return NULL;
    }
References ActionInput::GetPossibleActions(), and m_RegistredInputsMap.
GetSelectedActionCategory()
override ActionManagerClient::GetSelectedActionCategory () inline private
Definition at line 781 of file actionmanagerclient.c.
    {
        return m_OrderedStandartActionInputs[m_SelectedActionInputToSrollIndex].Type();
    }
References m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
GetVariantManager()
static ActionVariantManager ActionManagerClient::GetVariantManager (typename actionName) inline static private
Definition at line 311 of file actionmanagerclient.c.
    {
        ActionBase action = GetAction( actionName );
        if ( action )
        {
            return action.GetVariantManager();
        }
        //VME ACTION not exist typo most likely
        return null;
    }
References ActionBase(), and GetAction().
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
HandleInputsOnActionEnd()
void ActionManagerClient::HandleInputsOnActionEnd () inline private
Definition at line 683 of file actionmanagerclient.c.
    {
        ResetInputsState();
    }
References ResetInputsState().
Referenced by OnActionEnd().
HandleInputsOnActionStart()
void ActionManagerClient::HandleInputsOnActionStart (ActionBase action) inline private
Definition at line 667 of file actionmanagerclient.c.
    {
        for (int i = 0; i < m_OrederedAllActionInput.Count();i++)
        {
            ActionInput ain = m_OrederedAllActionInput[i];
            if(action.GetInput() == ain)
            {
                ain.OnActionStart();
            }
            else
            {
                ain.Reset();
            }
        }
    }
References m_OrederedAllActionInput, ActionInput::OnActionStart(), and ActionInput::Reset().
Referenced by ActionStart().
HasHandInventoryReservation()
protected bool ActionManagerClient::HasHandInventoryReservation () inline private
Definition at line 512 of file actionmanagerclient.c.
    {
        m_HandInventoryLocationTest.SetHands(m_Player,m_Player.GetItemInHands());
        if (m_Player.GetHumanInventory().HasInventoryReservation(m_Player.GetItemInHands(),m_HandInventoryLocationTest))
            return true;
        return false;
    }
References m_HandInventoryLocationTest, ActionManagerBase::m_Player, and InventoryLocation::SetHands().
Referenced by FindContextualUserActions().
InjectAction() [1/2]
void ActionManagerClient::InjectAction (ActionBase action, ActionTarget target, ItemBase item) inline private
Definition at line 428 of file actionmanagerclient.c.
    {
        ActionInput ai = action.GetInput();
        ai.ForceAction(action, target, item );
    }
References ActionInput::ForceAction().
Referenced by InjectAction().
InjectAction() [2/2]
void ActionManagerClient::InjectAction (typename actionType , ActionTarget target, ItemBase item) inline private
Definition at line 434 of file actionmanagerclient.c.
    {
        ActionBase action = GetAction(actionType);
        InjectAction(action, target, item);
    }
References ActionBase(), GetAction(), and InjectAction().
InputsUpdate()
void ActionManagerClient::InputsUpdate () inline private
Definition at line 338 of file actionmanagerclient.c.
    {
        ActionInput ain;
        if (m_CurrentActionData)
        {
            if (!m_ActionInputWantEnd)
            {
                ActionInput ai = m_CurrentActionData.m_Action.GetInput();
                ai.Update();
                if (m_Player.IsQBControl())
                {
                    if ( ai.JustActivate() )
                        m_Player.SetActionEndInput(m_CurrentActionData.m_Action);
                }
                else
                {
                    if ( ai.WasEnded() && ( ai.GetInputType() == ActionInputType.AIT_CONTINUOUS || ai.GetInputType() == ActionInputType.AIT_CLICKCONTINUOUS ) )
                    {
                        EndActionInput();
                    }
                }
            }
        }
        else
        {
            if ( m_ActionsAvaibale )
            {
                for (int i = 0; i < m_OrederedAllActionInput.Count();i++)
                {
                    ain = m_OrederedAllActionInput[i];
                    ain.Update();
                    if ( ain.JustActivate() )
                    {
                        ActionBase action = ain.GetAction();
                        if ( action )
{
                            ActionStart(action, ain.GetUsedActionTarget(), ain.GetUsedMainItem());
                            break;
                        }
                    }
                }
            }
        }
    }
References ActionBase(), ActionStart(), EndActionInput(), ActionInput::GetAction(), ActionInput::GetInputType(), ActionInput::GetUsedActionTarget(), ActionInput::GetUsedMainItem(), ActionInput::JustActivate(), ActionData::m_Action, ActionManagerBase::m_ActionInputWantEnd, ActionManagerBase::m_ActionsAvaibale, ActionManagerBase::m_CurrentActionData, m_OrederedAllActionInput, ActionManagerBase::m_Player, ActionInput::Update(), and ActionInput::WasEnded().
Referenced by Update().
Interrupt()
override void ActionManagerClient::Interrupt () inline private
Definition at line 1253 of file actionmanagerclient.c.
    {
        if(m_CurrentActionData)
            m_Interrupted = true;
    }
References ActionManagerBase::m_CurrentActionData, and ActionManagerBase::m_Interrupted.
Referenced by ManBase::ReloadWeapon().
LockInventory()
protected bool ActionManagerClient::LockInventory (ActionData action_data) inline private
Definition at line 554 of file actionmanagerclient.c.
    {
        bool success = false;
        if ( action_data.m_Action.IsInstant() )
        {
            if ( LogManager.IsActionLogEnable() )
            {
                Debug.ActionLog("(-) Inventory lock - Not Used", action_data.m_Action.ToString() , "n/a", "LockInventory", action_data.m_Player.ToString() );
            }
            success = true;
        }
        else
        {
            if ( LogManager.IsActionLogEnable() )
            {
                Debug.ActionLog("(X) Inventory lock", action_data.m_Action.ToString() , "n/a", "LockInventory", action_data.m_Player.ToString() );
            }
            if (action_data.m_Action)
            {
                success = action_data.m_Action.InventoryReservation(action_data);
            }
        }
        return success;
    }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, and ActionData::m_Player.
OnActionEnd()
override void ActionManagerClient::OnActionEnd () inline private
Definition at line 753 of file actionmanagerclient.c.
    {
        if(m_CurrentActionData)
        {
            UnlockInventory(m_CurrentActionData);
            if( m_CurrentActionData.m_Action.RemoveForceTargetAfterUse() )
                m_InventoryActionHandler.DeactiveAction();
            super.OnActionEnd();
            HandleInputsOnActionEnd();
        }
    }
References InventoryActionHandler::DeactiveAction(), HandleInputsOnActionEnd(), ActionData::m_Action, ActionManagerBase::m_CurrentActionData, m_InventoryActionHandler, and UnlockInventory().
Referenced by ActionStart(), OnJumpStart(), and Update().
OnInstantAction()
override void ActionManagerClient::OnInstantAction (typename user_action_type , Param data = NULL) inline private
Definition at line 723 of file actionmanagerclient.c.
    {
        ActionBase action = GetAction(user_action_type);
        if(action)
        {
            ActionStart(action,NULL,NULL, data);
        }
    }
References ActionBase(), ActionStart(), and GetAction().
OnJumpStart()
override void ActionManagerClient::OnJumpStart () inline private
Definition at line 706 of file actionmanagerclient.c.
    {
        if(m_CurrentActionData)
        {
            if( m_CurrentActionData.m_State == UA_AM_PENDING || m_CurrentActionData.m_State == UA_AM_REJECTED || m_CurrentActionData.m_State == UA_AM_ACCEPTED)
            {
                OnActionEnd();
                m_PendingActionAcknowledgmentID = -1;
            }
            else
            {
                m_CurrentActionData.m_Action.Interrupt(m_CurrentActionData);
            }
        }
    }
References ActionData::m_Action, ActionManagerBase::m_CurrentActionData, ActionManagerBase::m_PendingActionAcknowledgmentID, ActionData::m_State, OnActionEnd(), UA_AM_ACCEPTED, UA_AM_PENDING, and UA_AM_REJECTED.
PerformActionFromInventory()
void ActionManagerClient::PerformActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1067 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        target = new ActionTarget(targetItem, null, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            ActionBase picked_action;
            array<ActionBase_Basic> actions;
            int i;
            //First check single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromInventory() )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            ActionStart(picked_action, target, mainItem);
                            return;
                        }
                    }
                }
            }
            //Inventory specific actions
            mainItem.GetActions(InventoryOnlyActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            ActionStart(picked_action, target, mainItem);
                            return;
                        }
                    }
                }
            }
        }
    }
References ActionBase(), ActionStart(), ActionTarget, ActionManagerBase::m_Player, and vector::Zero.
Referenced by Icon::OnPerformCombination().
PerformActionFromQuickbar()
void ActionManagerClient::PerformActionFromQuickbar (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 948 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        ItemBase parent = null;
        if (targetItem)
            parent = ItemBase.Cast(targetItem.GetHierarchyParent());
        target = new ActionTarget(targetItem, parent, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            ActionBase picked_action;
            array<ActionBase_Basic> actions;
            int i;
            mainItem.GetActions(QuickaBarActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.HasTarget() && picked_action.Can(m_Player,target, itemInHand) )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            ActionStart(picked_action, target, mainItem);
                            return;
                        }
                    }
                }
            }
            //First continuous actions
            mainItem.GetActions(ContinuousDefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.HasTarget() && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromQuickbar() )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            ActionStart(picked_action, target, mainItem);
                            return;
                        }
                    }
                }
            }
            //Second check single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBePerformedFromQuickbar() )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            ActionStart(picked_action, target, mainItem);
                            return;
                        }
                    }
                }
            }
        }
    }
References ActionBase(), ActionStart(), ActionTarget, ContinuousDefaultActionInput(), ActionManagerBase::m_Player, and vector::Zero.
Referenced by ManBase::OnQuickBarContinuousUseStart().
PerformActionStart()
void ActionManagerClient::PerformActionStart (ActionBase action, ActionTarget target, ItemBase item, Param extra_data = NULL) inline private
Definition at line 740 of file actionmanagerclient.c.
    {
        if (!GetGame().IsMultiplayer())
        {
            m_PendingActionData = new ActionData;
            if (!action.SetupAction(m_Player,target,item,m_PendingActionData,extra_data))
                m_PendingActionData = null;
        }
        else
            ActionStart(action, target, item, extra_data);
    }
References ActionStart(), GetGame(), m_PendingActionData, and ActionManagerBase::m_Player.
Referenced by UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), OnCenterPanelDropReceived(), ManBase::PhysicalPredictiveDropItem(), ManBase::PredictiveForceSwapEntities(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToHands(), and ManBase::ReloadWeapon().
RegisterInputs()
void ActionManagerClient::RegisterInputs (PlayerBase player) inline private
Definition at line 194 of file actionmanagerclient.c.
    {
        if (!m_RegistredInputsMap)
        {
            m_RegistredInputsMap = new TTypeNameActionInputMap;
            for (int i = 0; i < m_ActionsArray.Count(); i++)
            {
                ActionBase action = m_ActionsArray.Get(i);
                typename input_type_name = action.GetInputType();
                ref ActionInput ai;
                ai = ActionInput.Cast(m_RegistredInputsMap.Get(input_type_name));
                if(!ai)
                {
                    ai = ActionInput.Cast(input_type_name.Spawn());
                    m_RegistredInputsMap.Insert(input_type_name, ai);
                }
                action.SetInput(ai);
            }
            for (int j = 0; j < m_RegistredInputsMap.Count(); j++ )
            {
                m_RegistredInputsMap.GetElement(j).Init(player, this);
            }
            SetActioninputOrder();
        }
    }
References ActionBase(), ActionManagerBase::m_ActionsArray, m_RegistredInputsMap, and SetActioninputOrder().
Referenced by ActionManagerClient().
RequestEndAction()
void ActionManagerClient::RequestEndAction () inline private
Definition at line 322 of file actionmanagerclient.c.
    {
        if ( !m_ActionWantEndRequest_Send )
        {
            m_ActionWantEndRequest = true;
        }
    }
References ActionManagerBase::m_ActionWantEndRequest, and m_ActionWantEndRequest_Send.
Referenced by ManBase::CloseMapEx(), ActionReadPaper::OnUpdate(), and ActionWritePaper::OnUpdate().
RequestInterruptAction()
void ActionManagerClient::RequestInterruptAction () inline private
client requests action interrupt
Definition at line 1260 of file actionmanagerclient.c.
    {
        ScriptInputUserData ctx = new ScriptInputUserData;
        if ( ctx.CanStoreInputUserData() )
        {
            ctx.Write(INPUT_UDT_STANDARD_ACTION_END_REQUEST);
            ctx.Write(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
            ctx.Send();
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), INPUT_UDT_STANDARD_ACTION_END_REQUEST, ScriptInputUserData::Send(), and Serializer::Write().
Referenced by ManBase::CloseMapEx().
ResetInputsActions()
void ActionManagerClient::ResetInputsActions () inline private
Definition at line 697 of file actionmanagerclient.c.
    {
        for (int i = 0; i < m_OrederedAllActionInput.Count();i++)
        {
            ActionInput ain = m_OrederedAllActionInput[i];
            ain.ActionsSelectReset();
        }
    }
References ActionInput::ActionsSelectReset(), and m_OrederedAllActionInput.
Referenced by FindContextualUserActions(), and Update().
ResetInputsState()
void ActionManagerClient::ResetInputsState () inline private
Definition at line 688 of file actionmanagerclient.c.
    {
        for (int i = 0; i < m_OrederedAllActionInput.Count();i++)
        {
            ActionInput ain = m_OrederedAllActionInput[i];
            ain.Reset();
        }
    }
References m_OrederedAllActionInput, and ActionInput::Reset().
Referenced by HandleInputsOnActionEnd().
SelectFirstActionCategory()
override void ActionManagerClient::SelectFirstActionCategory () inline private
Definition at line 809 of file actionmanagerclient.c.
    {
        UpdateActionCategoryPriority();
        m_SelectedActionInputToSrollIndex = 0;
        for ( int index = 0; index < m_OrderedStandartActionInputs.Count(); index++)
        {
            if ( m_OrderedStandartActionInputs[index].GetPossibleActionsCount() > 1)
            {
                m_SelectedActionInputToSrollIndex = index;
                break;
            }
        }
    }
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and UpdateActionCategoryPriority().
SelectNextAction()
override void ActionManagerClient::SelectNextAction () inline private
Definition at line 864 of file actionmanagerclient.c.
    {
        ActionInput ai;
        if( m_SelectedActionInputToSrollIndex < m_OrderedStandartActionInputs.Count() )
        {
            ai = m_OrderedStandartActionInputs[m_SelectedActionInputToSrollIndex];
            if(ai && ai.GetPossibleActionsCount() > 1)
            {
                ai.SelectNextAction();
            }
        }
    }
References ActionInput::GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and ActionInput::SelectNextAction().
SelectNextActionCategory()
override void ActionManagerClient::SelectNextActionCategory () inline private
Definition at line 824 of file actionmanagerclient.c.
    {
        int index;
        for( index = m_SelectedActionInputToSrollIndex + 1; index != m_SelectedActionInputToSrollIndex;; )
        {
            if(++index >= m_OrderedStandartActionInputs.Count() )
            {
                index = 0;
            }
            if( m_OrderedStandartActionInputs[index].GetPossibleActionsCount() > 1)
            {
                m_SelectedActionInputToSrollIndex = index;
                //PossibleGUIUpdate();
                break;
            }
        }
    }
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
SelectPrevAction()
override void ActionManagerClient::SelectPrevAction () inline private
Definition at line 877 of file actionmanagerclient.c.
    {
        ActionInput ai;
        if( m_SelectedActionInputToSrollIndex < m_OrderedStandartActionInputs.Count() )
        {
            ai = m_OrderedStandartActionInputs[m_SelectedActionInputToSrollIndex];
            if(ai && ai.GetPossibleActionsCount() > 1)
            {
                ai.SelectPrevAction();
            }
        }
    }
References ActionInput::GetPossibleActionsCount(), m_OrderedStandartActionInputs, m_SelectedActionInputToSrollIndex, and ActionInput::SelectPrevAction().
SelectPrevActionCategory()
override void ActionManagerClient::SelectPrevActionCategory () inline private
Definition at line 843 of file actionmanagerclient.c.
    {
        int index;
        for( index = m_SelectedActionInputToSrollIndex; index != m_SelectedActionInputToSrollIndex;;)
        {
            if(--index < 0 )
            {
                index = m_OrderedStandartActionInputs.Count() - 1;
            }
            if( m_OrderedStandartActionInputs[index].GetPossibleActionsCount() > 1)
            {
                m_SelectedActionInputToSrollIndex = index;
                //PossibleGUIUpdate();
                break;
            }
        }
    }
References GetPossibleActionsCount(), m_OrderedStandartActionInputs, and m_SelectedActionInputToSrollIndex.
SetActionFromInventory()
void ActionManagerClient::SetActionFromInventory (ItemBase mainItem, ItemBase targetItem) inline private
Definition at line 1204 of file actionmanagerclient.c.
    {
        ItemBase itemInHand = m_Player.GetItemInHands();
        ActionTarget target;
        target = new ActionTarget(targetItem, null, -1, vector.Zero, -1);
        bool hasTarget = targetItem != NULL;
        if( mainItem )
        {
            array<ActionBase_Basic> actions;
            ActionBase picked_action;
            //First check single use actions
            mainItem.GetActions(DefaultActionInput, actions);
            if (actions)
            {
                for ( int i = 0; i < actions.Count(); i++ )
                {
                    picked_action = ActionBase.Cast(actions[i]);
                    if ( picked_action && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBeSetFromInventory() )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            SetInventoryAction( picked_action, target, itemInHand);
                            return;
                        }
                    }
                }
            }
            //second continuous actions
            mainItem.GetActions(ContinuousDefaultActionInput, actions);
            if (actions)
            {
                for ( int j = 0; j < actions.Count(); j++ )
                {
                    picked_action = ActionBase.Cast(actions[j]);
                    if ( picked_action && picked_action.HasTarget() && picked_action.Can(m_Player,target, itemInHand) && picked_action.CanBeSetFromInventory() )
                    {
                        if( hasTarget == picked_action.HasTarget())
{
                            SetInventoryAction( picked_action, target, itemInHand);
                            return;
                        }
                    }
                }
            }
        }
    }
References ActionBase(), ActionTarget, ContinuousDefaultActionInput(), ActionManagerBase::m_Player, SetInventoryAction(), and vector::Zero.
Referenced by Icon::OnPerformCombination().
SetActioninputOrder()
void ActionManagerClient::SetActioninputOrder () inline private
Definition at line 225 of file actionmanagerclient.c.
    {
        int i, j;
        int priority;
        ActionInput input;
        m_OrederedAllActionInput = new array<ActionInput>;
        map<int, ref array<ActionInput>> temp_map_for_sort = new map<int, ref array<ActionInput>>;
        array<int> array_of_priorities_to_sort = new array<int>;
        ref array<ActionInput> same_priority_input_array;
        for (i = 0; i < m_RegistredInputsMap.Count(); i++)
        {
            input = m_RegistredInputsMap.GetElement(i);
            priority = input.GetPriority();
            same_priority_input_array = temp_map_for_sort.Get(priority);
            if ( same_priority_input_array )
            {
                same_priority_input_array.Insert(input);
                continue;
            }
            same_priority_input_array = new array<ActionInput>;
            same_priority_input_array.Insert(input);
            temp_map_for_sort.Insert(priority,same_priority_input_array);
            array_of_priorities_to_sort.Insert(priority);
        }
        array_of_priorities_to_sort.Sort();
        for (i = 0; i < array_of_priorities_to_sort.Count(); i++)
        {
            priority = array_of_priorities_to_sort[i];
            same_priority_input_array = temp_map_for_sort.Get(priority);
            for (j = 0; j < same_priority_input_array.Count(); j++)
            {
                input = same_priority_input_array.Get(j);
                m_OrederedAllActionInput.Insert(input);
            }
        }
        SetDefaultInputsOrder();
    }
References ActionInput::GetPriority(), m_OrederedAllActionInput, m_RegistredInputsMap, and SetDefaultInputsOrder().
Referenced by RegisterInputs().
SetDefaultInputsOrder()
void ActionManagerClient::SetDefaultInputsOrder () inline private
Definition at line 269 of file actionmanagerclient.c.
    {
        int i, j;
        m_DefaultOrderOfActionInputs = new array<ActionInput>;
        m_OrderedStandartActionInputs = new array<ActionInput>;
        ActionInput input = m_RegistredInputsMap.Get(ContinuousDefaultActionInput);
        if (input)
        {
            m_OrderedStandartActionInputs.Insert(input);
        }
        input = m_RegistredInputsMap.Get(DefaultActionInput);
        if (input)
        {
            m_OrderedStandartActionInputs.Insert(input);
        }
        input = m_RegistredInputsMap.Get(ContinuousInteractActionInput);
        if (input)
        {;
            m_OrderedStandartActionInputs.Insert(input);
        }
        input = m_RegistredInputsMap.Get(InteractActionInput);
        if (input)
        {
            m_OrderedStandartActionInputs.Insert(input);
        }
        for (i = 0; i < m_OrederedAllActionInput.Count(); i++)
        {
            for (j = 0; j < m_OrderedStandartActionInputs.Count(); j++)
            {
                if (m_OrederedAllActionInput[i] == m_OrderedStandartActionInputs[j])
                {
                    m_DefaultOrderOfActionInputs.Insert(m_OrederedAllActionInput[i]);
                    break;
                }
            }
        }
    }
References ContinuousDefaultActionInput(), m_DefaultOrderOfActionInputs, m_OrderedStandartActionInputs, m_OrederedAllActionInput, and m_RegistredInputsMap.
Referenced by SetActioninputOrder().
SetInventoryAction() [1/2]
void ActionManagerClient::SetInventoryAction (ActionBase action_name, ActionTarget target, ItemBase main_item) inline private
Definition at line 771 of file actionmanagerclient.c.
    {
        m_InventoryActionHandler.SetAction(action_name, target, main_item);
    }
References m_InventoryActionHandler, and InventoryActionHandler::SetAction().
SetInventoryAction() [2/2]
void ActionManagerClient::SetInventoryAction (ActionBase action_name, ItemBase target_item, ItemBase main_item) inline private
Definition at line 766 of file actionmanagerclient.c.
    {
        m_InventoryActionHandler.SetAction(action_name, target_item, main_item);
    }
References m_InventoryActionHandler, and InventoryActionHandler::SetAction().
Referenced by SetActionFromInventory(), and CraftingManager::SetInventoryCraft().
UnlockInventory()
void ActionManagerClient::UnlockInventory (ActionData action_data) inline private
Definition at line 578 of file actionmanagerclient.c.
    {
        if ( LogManager.IsActionLogEnable() )
        {
            Debug.ActionLog("(O) Inventory unlock", action_data.m_Action.ToString() , "n/a", "UnlockInventory", action_data.m_Player.ToString() );
        }
        if (action_data.m_Action)
            action_data.m_Action.ClearInventoryReservationEx(action_data);
    }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, and ActionData::m_Player.
Referenced by OnActionEnd(), OnExecuteClient(), and OnExecuteServer().
UnsetInventoryAction()
void ActionManagerClient::UnsetInventoryAction () inline private
Definition at line 776 of file actionmanagerclient.c.
    {
        m_InventoryActionHandler.DeactiveAction();
    }
References InventoryActionHandler::DeactiveAction(), and m_InventoryActionHandler.
Update()
override void ActionManagerClient::Update (int pCurrentCommandID) inline private
Definition at line 41 of file actionmanagerclient.c.
    {
        m_InventoryActionHandler.OnUpdate();
        super.Update(pCurrentCommandID);
        m_ActionPossible = ActionPossibilityCheck(pCurrentCommandID);
        if (m_PendingActionData) //SP only
        {
            m_CurrentActionData = m_PendingActionData;
            m_CurrentActionData.m_Action.Start(m_CurrentActionData);
            if ( m_CurrentActionData.m_Action.IsInstant() )
                OnActionEnd();
            m_PendingActionData = null;
        }
        if (m_CurrentActionData)
        {
            if (m_CurrentActionData.m_State != UA_AM_PENDING && m_CurrentActionData.m_State != UA_AM_REJECTED && m_CurrentActionData.m_State != UA_AM_ACCEPTED)
                m_CurrentActionData.m_Action.OnUpdateClient(m_CurrentActionData);
            switch (m_CurrentActionData.m_State)
            {
                case UA_AM_PENDING:
                    break;
                case UA_AM_ACCEPTED:
                    int condition_mask = ActionBase.ComputeConditionMask( m_Player, m_CurrentActionData.m_Target, m_CurrentActionData.m_MainItem );
                    m_CurrentActionData.m_Action.ClearInventoryReservationEx(m_CurrentActionData);
                    //bool can_be_action_done = ((condition_mask & m_CurrentActionData.m_Action.m_ConditionMask) == condition_mask );
                    bool can_be_action_done = m_CurrentActionData.m_Action.Can(m_Player,m_CurrentActionData.m_Target,m_CurrentActionData.m_MainItem);
                    // check pCurrentCommandID before start or reject
                    if ( m_ActionPossible && can_be_action_done && pCurrentCommandID != DayZPlayerConstants.COMMANDID_SWIM )
                    {
                        m_CurrentActionData.m_Action.InventoryReservation(m_CurrentActionData);
                        m_CurrentActionData.m_State = UA_START;
                        m_CurrentActionData.m_Action.Start(m_CurrentActionData);
                        if ( m_CurrentActionData.m_Action.IsInstant() )
                            OnActionEnd();
                    }
                    else
                    {
                        OnActionEnd();
                    }
                    m_PendingActionAcknowledgmentID = -1;
                    break;
                case UA_AM_REJECTED:
                    OnActionEnd();
                    m_PendingActionAcknowledgmentID = -1;
                    //m_Player.GetDayZPlayerInventory().UnlockHands();
                    break;
                default:
                    if ( m_ActionWantEndRequest )
                    {
                        if ( GetGame().IsMultiplayer() && !m_CurrentActionData.m_Action.IsLocal() )
{
                            if ( !m_ActionWantEndRequest_Send && ScriptInputUserData.CanStoreInputUserData() )
{
                                if ( LogManager.IsActionLogEnable() )
{
                                    Debug.ActionLog("Time stamp: " + m_Player.GetSimulationTimeStamp(), m_CurrentActionData.m_Action.ToString() , "n/a", "EndRequest", m_CurrentActionData.m_Player.ToString() );
                                }
                                ScriptInputUserData ctx = new ScriptInputUserData;
                                ctx.Write(INPUT_UDT_STANDARD_ACTION_END_REQUEST);
                                ctx.Send();
                                m_ActionWantEndRequest_Send = true;
                                m_ActionWantEndRequest = false;
                                m_CurrentActionData.m_Action.EndRequest(m_CurrentActionData);
                            }
                        }
                        else
{
                            m_ActionWantEndRequest = false;
                            m_CurrentActionData.m_Action.EndRequest(m_CurrentActionData);
                        }
                    }
                    if ( m_ActionInputWantEnd )
                    {
                        if ( GetGame().IsMultiplayer() && !m_CurrentActionData.m_Action.IsLocal() )
{
                            if ( !m_ActionInputWantEnd_Send && ScriptInputUserData.CanStoreInputUserData() )
{
                                if ( LogManager.IsActionLogEnable() )
{
                                    Debug.ActionLog("Time stamp: " + m_Player.GetSimulationTimeStamp(), m_CurrentActionData.m_Action.ToString() , "n/a", "EndInput", m_CurrentActionData.m_Player.ToString() );
                                }
                                ScriptInputUserData ctxi = new ScriptInputUserData;
                                ctxi.Write(INPUT_UDT_STANDARD_ACTION_INPUT_END);
                                ctxi.Send();
                                m_ActionInputWantEnd_Send = true;
                                m_ActionInputWantEnd = false;
                                m_CurrentActionData.m_Action.EndInput(m_CurrentActionData);
                            }
                        }
                        else
{
                            if (!m_ActionInputWantEnd_Send)
{
                                m_ActionInputWantEnd_Send = true;
                                m_ActionInputWantEnd = false;
                                m_CurrentActionData.m_Action.EndInput(m_CurrentActionData);
                            }
                        }
                    }
                break;
            }
        }
#ifdef DEVELOPER
        if ( DeveloperFreeCamera.IsFreeCameraEnabled() )
        {
            m_ActionPossible = false;
            ResetInputsActions();
        }
        else
        {
#endif
            if (!m_CurrentActionData)
            {
                bool isMenuOpen = false;
#ifndef NO_GUI
                isMenuOpen = GetGame().GetUIManager().IsMenuOpen(MENU_INVENTORY);
#endif
                if ( m_Player.IsRaised() || isMenuOpen )
                {
                    m_Targets.Clear();
                }
                else
                {
                    m_Targets.Update();
                }
                FindContextualUserActions( pCurrentCommandID );
            }
            InputsUpdate();
#ifdef DEVELOPER
        }
#endif
    }
References ActionBase(), Debug::ActionLog(), ActionManagerBase::ActionPossibilityCheck(), ScriptInputUserData::CanStoreInputUserData(), ActionTargets::Clear(), FindContextualUserActions(), GetGame(), CGame::GetUIManager(), INPUT_UDT_STANDARD_ACTION_END_REQUEST, INPUT_UDT_STANDARD_ACTION_INPUT_END, InputsUpdate(), LogManager::IsActionLogEnable(), DeveloperFreeCamera::IsFreeCameraEnabled(), UIManager::IsMenuOpen(), ActionData::m_Action, ActionManagerBase::m_ActionInputWantEnd, m_ActionInputWantEnd_Send, m_ActionPossible, ActionManagerBase::m_ActionWantEndRequest, m_ActionWantEndRequest_Send, ActionManagerBase::m_CurrentActionData, m_InventoryActionHandler, ActionData::m_MainItem, ActionManagerBase::m_PendingActionAcknowledgmentID, m_PendingActionData, ActionData::m_Player, ActionManagerBase::m_Player, ActionData::m_State, ActionData::m_Target, m_Targets, MENU_INVENTORY, OnActionEnd(), InventoryActionHandler::OnUpdate(), ResetInputsActions(), ScriptInputUserData::Send(), UA_AM_ACCEPTED, UA_AM_PENDING, UA_AM_REJECTED, UA_START, ActionTargets::Update(), and Serializer::Write().
UpdateActionCategoryPriority()
void ActionManagerClient::UpdateActionCategoryPriority () inline private
Definition at line 786 of file actionmanagerclient.c.
    {
        int i;
        int last_target_index = 0;
        for ( i = 0; i < m_DefaultOrderOfActionInputs.Count(); i++)
        {
            if ( m_DefaultOrderOfActionInputs[i].HasTarget() )
            {
                m_OrderedStandartActionInputs[last_target_index] = m_DefaultOrderOfActionInputs[i];
                last_target_index++;
            }
        }
        for ( i = 0; i < m_DefaultOrderOfActionInputs.Count(); i++)
        {
            if ( !m_DefaultOrderOfActionInputs[i].HasTarget() )
            {
                m_OrderedStandartActionInputs[last_target_index] = m_DefaultOrderOfActionInputs[i];
                last_target_index++;
            }
        }
    }
References HasTarget(), m_DefaultOrderOfActionInputs, and m_OrderedStandartActionInputs.
Referenced by SelectFirstActionCategory().
Member Data Documentation
m_ActionInputWantEnd_Send
protected bool ActionManagerClient::m_ActionInputWantEnd_Send private
Definition at line 23 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), ActionStart(), EndActionInput(), and Update().
m_ActionPossible
protected bool ActionManagerClient::m_ActionPossible private
Definition at line 9 of file actionmanagerclient.c.
Referenced by FindContextualUserActions(), and Update().
m_ActionWantEndRequest_Send
protected bool ActionManagerClient::m_ActionWantEndRequest_Send private
Definition at line 22 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), ActionStart(), RequestEndAction(), and Update().
m_DefaultOrderOfActionInputs
protected ref array<ActionInput> ActionManagerClient::m_DefaultOrderOfActionInputs private
Definition at line 16 of file actionmanagerclient.c.
Referenced by SetDefaultInputsOrder(), and UpdateActionCategoryPriority().
m_ForceTarget
private ref ActionTarget ActionManagerClient::m_ForceTarget private
Definition at line 1272 of file actionmanagerclient.c.
Referenced by ClearForceTarget(), FindActionTarget(), and ForceTarget().
m_HandInventoryLocationTest
protected ref InventoryLocation ActionManagerClient::m_HandInventoryLocationTest private
Definition at line 12 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), and HasHandInventoryReservation().
m_InventoryActionHandler
protected ref InventoryActionHandler ActionManagerClient::m_InventoryActionHandler private
Definition at line 11 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), OnActionEnd(), SetInventoryAction(), UnsetInventoryAction(), and Update().
m_LastAcknowledgmentID
protected int ActionManagerClient::m_LastAcknowledgmentID private
Definition at line 8 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), and ActionStart().
m_OrderedStandartActionInputs
protected ref array<ActionInput> ActionManagerClient::m_OrderedStandartActionInputs private
Definition at line 15 of file actionmanagerclient.c.
Referenced by GetSelectedActionCategory(), SelectFirstActionCategory(), SelectNextAction(), SelectNextActionCategory(), SelectPrevAction(), SelectPrevActionCategory(), SetDefaultInputsOrder(), and UpdateActionCategoryPriority().
m_OrederedAllActionInput
protected ref array<ActionInput> ActionManagerClient::m_OrederedAllActionInput private
Definition at line 14 of file actionmanagerclient.c.
Referenced by FindContextualUserActions(), HandleInputsOnActionStart(), InputsUpdate(), ResetInputsActions(), ResetInputsState(), SetActioninputOrder(), and SetDefaultInputsOrder().
m_PendingActionData
protected ref ActionData ActionManagerClient::m_PendingActionData private
Definition at line 19 of file actionmanagerclient.c.
Referenced by PerformActionStart(), and Update().
m_RegistredInputsMap
protected ref TTypeNameActionInputMap ActionManagerClient::m_RegistredInputsMap private
Definition at line 13 of file actionmanagerclient.c.
Referenced by GetPossibleAction(), GetPossibleActionCount(), GetPossibleActionIndex(), GetPossibleActions(), RegisterInputs(), SetActioninputOrder(), and SetDefaultInputsOrder().
m_ReservedInventoryLocations
protected ref array<ref InventoryLocation> ActionManagerClient::m_ReservedInventoryLocations private
Definition at line 10 of file actionmanagerclient.c.
Referenced by ActionManagerClient().
m_SelectedActionInputToSrollIndex
protected int ActionManagerClient::m_SelectedActionInputToSrollIndex private
Definition at line 17 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), GetSelectedActionCategory(), SelectFirstActionCategory(), SelectNextAction(), SelectNextActionCategory(), SelectPrevAction(), and SelectPrevActionCategory().
m_Targets
private ref ActionTargets ActionManagerClient::m_Targets private
Definition at line 1273 of file actionmanagerclient.c.
Referenced by ActionManagerClient(), FindActionTarget(), and Update().