DayzKode: HeatComfortAnimHandler Class Reference
HeatComfortAnimHandler Class Reference
Private Member Functions
float GetEventTime (float hc_value, float threshold_low, float threshold_high, float low_min, float high_min, float low_max, float high_max)
void HeatComfortAnimHandler (PlayerBase player)
void Process (float delta_time)
void Update (float delta_time, HumanMovementState hms)
Private Attributes
float m_EventTimeFreeze = -1
float m_EventTimeHot = -1
protected ref HumanMovementState m_MovementState = new HumanMovementState()
PlayerBase m_Player
float m_ProcessTimeAccuFreeze
float m_ProcessTimeAccuHot
float m_TimeSinceLastTick
const float TICK_INTERVAL = 2
const float TIME_INTERVAL_HC_MINUS_HIGH_MAX = 25
const float TIME_INTERVAL_HC_MINUS_HIGH_MIN = 15
const float TIME_INTERVAL_HC_MINUS_LOW_MAX = 12
const float TIME_INTERVAL_HC_MINUS_LOW_MIN = 5
const float TIME_INTERVAL_HC_PLUS_HIGH_MAX = 25
const float TIME_INTERVAL_HC_PLUS_HIGH_MIN = 15
const float TIME_INTERVAL_HC_PLUS_LOW_MAX = 12
const float TIME_INTERVAL_HC_PLUS_LOW_MIN = 5
Detailed Description
Definition at line 1 of file heatcomfortanimhandler.c.
Constructor & Destructor Documentation
HeatComfortAnimHandler()
void HeatComfortAnimHandler::HeatComfortAnimHandler (PlayerBase player) inline private
Definition at line 19 of file heatcomfortanimhandler.c.
    {
        m_Player = player;
    }
References m_Player.
Member Function Documentation
GetEventTime()
float HeatComfortAnimHandler::GetEventTime (float hc_value, float threshold_low, float threshold_high, float low_min, float high_min, float low_max, float high_max) inline private
Definition at line 35 of file heatcomfortanimhandler.c.
    {
        float inv_value = Math.InverseLerp(threshold_low, threshold_high, hc_value);
        float value_min = Math.Lerp(low_min, high_min,inv_value);
        float value_max = Math.Lerp(low_max,high_max,inv_value);
        return Math.RandomFloatInclusive(value_min,value_max);
    }
References Math::InverseLerp(), Math::Lerp(), and Math::RandomFloatInclusive().
Referenced by Process().
Process()
void HeatComfortAnimHandler::Process (float delta_time) inline private
Definition at line 45 of file heatcomfortanimhandler.c.
    {
        if( GetGame().IsServer() )
        {
            float hc = m_Player.GetStatHeatComfort().Get();
            float inv_value;
            float value_min;
            float value_max;
            float offset_time;
            if ( hc <= PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING )
            {
                m_ProcessTimeAccuFreeze++;
                if(m_EventTimeFreeze < 0)//if not set
                {
                    m_EventTimeFreeze = GetEventTime(hc, PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_EMPTY,PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING, TIME_INTERVAL_HC_MINUS_LOW_MIN, TIME_INTERVAL_HC_MINUS_HIGH_MIN, TIME_INTERVAL_HC_MINUS_LOW_MAX, TIME_INTERVAL_HC_MINUS_HIGH_MAX);
                }
                if( m_ProcessTimeAccuFreeze > m_EventTimeFreeze )
                {
                    m_ProcessTimeAccuFreeze = 0;
                    m_EventTimeFreeze = -1;
                    m_Player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_FREEZE);
                    /*
                    Print("-----======== freezing ========-------");
                    Print(inv_value);
                    Print(value_min);
                    Print(value_max);
                    Print(offset_time);
                    Print("-----======== freezing ========-------");
                    */
                }
            }
            else if ( hc >= PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING )
            {
                m_ProcessTimeAccuHot++;
                if(m_EventTimeHot < 0)//if not set
                {
                    m_EventTimeHot = GetEventTime(hc, PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_EMPTY,PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING, TIME_INTERVAL_HC_PLUS_LOW_MIN, TIME_INTERVAL_HC_PLUS_LOW_MIN, TIME_INTERVAL_HC_PLUS_LOW_MAX, TIME_INTERVAL_HC_PLUS_HIGH_MAX);
                }
                if( m_ProcessTimeAccuHot > m_EventTimeHot )
                {
                    m_ProcessTimeAccuHot = 0;
                    m_EventTimeHot = -1;
                    m_Player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_HOT);
                    //Print("-----======== freezing ========-------");
                    //Print(inv_value);
                    //Print(value_min);
                    //Print(value_max);
                    //Print(offset_time);
                    //Print("-----======== freezing ========-------");
                }
            }
        }
    }
References GetEventTime(), GetGame(), m_EventTimeFreeze, m_EventTimeHot, m_Player, m_ProcessTimeAccuFreeze, m_ProcessTimeAccuHot, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_EMPTY, PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_EMPTY, PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_WARNING, TIME_INTERVAL_HC_MINUS_HIGH_MAX, TIME_INTERVAL_HC_MINUS_HIGH_MIN, TIME_INTERVAL_HC_MINUS_LOW_MAX, TIME_INTERVAL_HC_MINUS_LOW_MIN, TIME_INTERVAL_HC_PLUS_HIGH_MAX, TIME_INTERVAL_HC_PLUS_LOW_MAX, and TIME_INTERVAL_HC_PLUS_LOW_MIN.
Referenced by Update().
Update()
void HeatComfortAnimHandler::Update (float delta_time, HumanMovementState hms) inline private
Definition at line 24 of file heatcomfortanimhandler.c.
    {
        m_TimeSinceLastTick += delta_time;
        if( m_TimeSinceLastTick > TICK_INTERVAL )
        {
            Process(m_TimeSinceLastTick);
            m_TimeSinceLastTick = 0;
        }
    }
References m_TimeSinceLastTick, Process(), and TICK_INTERVAL.
Member Data Documentation
m_EventTimeFreeze
float HeatComfortAnimHandler::m_EventTimeFreeze = -1 private
Definition at line 9 of file heatcomfortanimhandler.c.
Referenced by Process().
m_EventTimeHot
float HeatComfortAnimHandler::m_EventTimeHot = -1 private
Definition at line 10 of file heatcomfortanimhandler.c.
Referenced by Process().
m_MovementState
protected ref HumanMovementState HeatComfortAnimHandler::m_MovementState = new HumanMovementState() private
Definition at line 11 of file heatcomfortanimhandler.c.
m_Player
PlayerBase HeatComfortAnimHandler::m_Player private
Definition at line 8 of file heatcomfortanimhandler.c.
Referenced by HeatComfortAnimHandler(), and Process().
m_ProcessTimeAccuFreeze
float HeatComfortAnimHandler::m_ProcessTimeAccuFreeze private
Definition at line 5 of file heatcomfortanimhandler.c.
Referenced by Process().
m_ProcessTimeAccuHot
float HeatComfortAnimHandler::m_ProcessTimeAccuHot private
Definition at line 6 of file heatcomfortanimhandler.c.
Referenced by Process().
m_TimeSinceLastTick
float HeatComfortAnimHandler::m_TimeSinceLastTick private
Definition at line 4 of file heatcomfortanimhandler.c.
Referenced by Update().
TICK_INTERVAL
const float HeatComfortAnimHandler::TICK_INTERVAL = 2 private
Definition at line 3 of file heatcomfortanimhandler.c.
Referenced by Update().
TIME_INTERVAL_HC_MINUS_HIGH_MAX
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_MINUS_HIGH_MAX = 25 private
Definition at line 14 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_MINUS_HIGH_MIN
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_MINUS_HIGH_MIN = 15 private
Definition at line 14 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_MINUS_LOW_MAX
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_MINUS_LOW_MAX = 12 private
Definition at line 13 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_MINUS_LOW_MIN
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_MINUS_LOW_MIN = 5 private
Definition at line 13 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_PLUS_HIGH_MAX
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_PLUS_HIGH_MAX = 25 private
Definition at line 17 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_PLUS_HIGH_MIN
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_PLUS_HIGH_MIN = 15 private
Definition at line 17 of file heatcomfortanimhandler.c.
TIME_INTERVAL_HC_PLUS_LOW_MAX
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_PLUS_LOW_MAX = 12 private
Definition at line 16 of file heatcomfortanimhandler.c.
Referenced by Process().
TIME_INTERVAL_HC_PLUS_LOW_MIN
const float HeatComfortAnimHandler::TIME_INTERVAL_HC_PLUS_LOW_MIN = 5 private
Definition at line 16 of file heatcomfortanimhandler.c.
Referenced by Process().