DayzKode: ActionTakeMaterialToHands Class Reference
ActionTakeMaterialToHands Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTakeMaterialToHands ()
override bool CanContinue (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool HasProneException ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteClient (ActionData action_data)
protected void OnExecuteImpl (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actiontakematerialtohands.c.
Constructor & Destructor Documentation
ActionTakeMaterialToHands()
void ActionTakeMaterialToHands::ActionTakeMaterialToHands () inline private
Definition at line 3 of file actiontakematerialtohands.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS;
        m_Text = "#take";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeMaterialToHands::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 42 of file actiontakematerialtohands.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if ( target_entity && target_entity.CanUseConstruction() )
        {
            BaseBuildingBase base_building = BaseBuildingBase.Cast( target_entity );
            if(!base_building.IsPlayerInside(player,""))
                return false;
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            string main_part_name = target_entity.GetActionComponentName( target.GetComponentIndex() );
            //Print(main_part_name);
            if ( GetGame().IsMultiplayer() || GetGame().IsServer() )
            {
                construction_action_data.RefreshAttachmentsToDetach( target_entity, main_part_name );
            }
            EntityAI attachment = construction_action_data.GetActualAttachmentToDetach();
            if ( attachment && player.GetInventory().CanAddEntityIntoHands( attachment ) && attachment.GetHierarchyRootPlayer() != player )
            {
                return true;
            }
        }
        return false;
    }
References ConstructionActionData::GetActualAttachmentToDetach(), GetGame(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::RefreshAttachmentsToDetach().
CanContinue()
override bool ActionTakeMaterialToHands::CanContinue (ActionData action_data) inline private
Definition at line 70 of file actiontakematerialtohands.c.
    {
        return true;
    }
CreateAndSetupActionCallback()
override void ActionTakeMaterialToHands::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 109 of file actiontakematerialtohands.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        EntityAI target = construction_action_data.GetActualAttachmentToDetach();
        bool heavy_item = false;
        ActionBaseCB callback;
        if ( target && target.ConfigIsExisting("heavyItem") && target.ConfigGetBool("heavyItem") )
        {
            heavy_item = true;
        }
        if( heavy_item )
        {
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            if( action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT) )
            {
                Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS,GetCallbackClassTypename()));
            }
            else
            {
                Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_PRONE));
            }
        }
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), ConstructionActionData::GetActualAttachmentToDetach(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, and ActionBaseCB::SetActionData().
CreateConditionComponents()
override void ActionTakeMaterialToHands::CreateConditionComponents () inline private
Definition at line 10 of file actiontakematerialtohands.c.
    {
        m_ConditionItem = new CCINotPresent;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionTakeMaterialToHands::GetInputType () inline private
Definition at line 32 of file actiontakematerialtohands.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionTakeMaterialToHands::HasProgress () inline private
Definition at line 37 of file actiontakematerialtohands.c.
    {
        return false;
    }
HasProneException()
override bool ActionTakeMaterialToHands::HasProneException () inline private
Definition at line 16 of file actiontakematerialtohands.c.
    {
        return true;
    }
OnActionInfoUpdate()
override void ActionTakeMaterialToHands::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 21 of file actiontakematerialtohands.c.
    {
        ConstructionActionData construction_action_data = player.GetConstructionActionData();
        EntityAI attachment = construction_action_data.GetActualAttachmentToDetach();
        if ( attachment )
        {
            m_Text = "#take " + attachment.GetDisplayName();
        }
    }
References ConstructionActionData::GetActualAttachmentToDetach(), and m_Text.
OnExecuteClient()
override void ActionTakeMaterialToHands::OnExecuteClient (ActionData action_data) inline private
Definition at line 75 of file actiontakematerialtohands.c.
    {
        OnExecuteImpl(action_data);
    }
References OnExecuteImpl().
OnExecuteImpl()
protected void ActionTakeMaterialToHands::OnExecuteImpl (ActionData action_data) inline private
Definition at line 80 of file actiontakematerialtohands.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        ItemBase item_target = ItemBase.Cast( construction_action_data.GetActualAttachmentToDetach() );
        if( item_target )
        {
            float stackable = item_target.GetTargetQuantityMax();
            if( stackable == 0 || stackable >= item_target.GetQuantity() )
            {
                //take to hands
                action_data.m_Player.PredictiveTakeEntityToHands( item_target );
            }
            else if( stackable != 0 && stackable < item_target.GetQuantity() )
            {
                //split and take to hands
                item_target.SplitIntoStackMaxHandsClient( action_data.m_Player );
            }
        }
    }
References ConstructionActionData::GetActualAttachmentToDetach(), and ActionData::m_Player.
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void ActionTakeMaterialToHands::OnExecuteServer (ActionData action_data) inline private
Definition at line 101 of file actiontakematerialtohands.c.
    {
        if (GetGame().IsMultiplayer())
            return; // multiplayer handled on client side via OnExecuteClient
        else
            OnExecuteImpl(action_data); // single player
    }
References GetGame(), and OnExecuteImpl().