DayzKode: ActionTakeItem Class Reference
ActionTakeItem Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionTakeItem ()
override bool CanBeUsedOnBack ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool InventoryReservation (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Private Attributes
string m_ItemName = ""
Detailed Description
Definition at line 6 of file actiontakeitem.c.
Constructor & Destructor Documentation
ActionTakeItem()
void ActionTakeItem::ActionTakeItem () inline private
Definition at line 10 of file actiontakeitem.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_INVENTORY;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_INVENTORY;
        m_Text = "#take";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeItem::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 33 of file actiontakeitem.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        if ( tgt_item && !tgt_item.IsTakeable() ) return false;
        if ( tgt_item && tgt_item.IsBeingPlaced() ) return false;
        EntityAI tgt_parent = EntityAI.Cast( target.GetParent() );
        EntityAI tgt_entity = EntityAI.Cast( target.GetObject() );
        if ( tgt_entity && (!tgt_parent || BaseBuildingBase.Cast(tgt_parent)) )
        {
            if ( tgt_entity && tgt_entity.IsItemBase() && player.GetInventory().CanAddEntityIntoInventory(tgt_entity) && tgt_entity.GetHierarchyRootPlayer() != player )
            {
                if ( tgt_parent && (!tgt_item.CanDetachAttachment(tgt_parent) || !tgt_parent.CanReleaseAttachment(tgt_item)) )
                    return false;
                return true;
            }
        }
        return false;
    }
References ItemBase::CanDetachAttachment(), and ItemBase::IsTakeable().
ActionConditionContinue()
override bool ActionTakeItem::ActionConditionContinue (ActionData action_data) inline private
Definition at line 28 of file actiontakeitem.c.
    {
        return true;
    }
CanBeUsedOnBack()
override bool ActionTakeItem::CanBeUsedOnBack () inline private
Definition at line 55 of file actiontakeitem.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionTakeItem::CreateConditionComponents () inline private
Definition at line 17 of file actiontakeitem.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionTakeItem::HasProneException () inline private
Definition at line 23 of file actiontakeitem.c.
    {
        return true;
    }
InventoryReservation()
override bool ActionTakeItem::InventoryReservation (ActionData action_data) inline private
Definition at line 96 of file actiontakeitem.c.
    {
        bool success = true;
        InventoryLocation il = new InventoryLocation;
        ItemBase targetItem;
        if ( ItemBase.CastTo(targetItem, action_data.m_Target.GetObject()) )
        {
            action_data.m_Player.GetInventory().FindFreeLocationFor( targetItem , FindInventoryLocationType.ANY, il );
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( targetItem, il) )
            {
                success = false;
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( targetItem, il, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if ( success )
        {
            if( il )
                action_data.m_ReservedInventoryLocations.Insert(il);
        }
        return success;
    }
References ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteClient()
override void ActionTakeItem::OnExecuteClient (ActionData action_data) inline private
Definition at line 153 of file actiontakeitem.c.
    {
        //Debug.Log("[Action DEBUG] Start time stamp: " + action_data.m_Player.GetSimulationTimeStamp());
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        InventoryLocation il = action_data.m_ReservedInventoryLocations.Get(0);
        InventoryLocation targetInventoryLocation = new InventoryLocation;
        ntarget.GetInventory().GetCurrentInventoryLocation(targetInventoryLocation);
        //SplitItemUtils.TakeOrSplitToInventoryLocation( action_data.m_Player, il );
        //action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
        float stackable = ntarget.GetTargetQuantityMax(il.GetSlot());
        if( stackable == 0 || stackable >= ntarget.GetQuantity() )
        {
            action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
        }
        else
        {
            ntarget.SplitIntoStackMaxToInventoryLocationClient( il );
        }
    }
References InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteServer()
override void ActionTakeItem::OnExecuteServer (ActionData action_data) inline private
Definition at line 125 of file actiontakeitem.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        //Debug.Log("[Action DEBUG] Start time stamp: " + action_data.m_Player.GetSimulationTimeStamp());
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        InventoryLocation il = action_data.m_ReservedInventoryLocations.Get(0);
        InventoryLocation targetInventoryLocation = new InventoryLocation;
        ntarget.GetInventory().GetCurrentInventoryLocation(targetInventoryLocation);
        //SplitItemUtils.TakeOrSplitToInventoryLocation( action_data.m_Player, il );
        float stackable = ntarget.GetTargetQuantityMax(il.GetSlot());
        if( stackable == 0 || stackable >= ntarget.GetQuantity() )
        {
            action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
        }
        else
        {
            ClearInventoryReservationEx(action_data);
            ntarget.SplitIntoStackMaxToInventoryLocationClient( il );
        }
        //action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
    }
References ClearInventoryReservationEx(), GetGame(), InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
Member Data Documentation
m_ItemName
string ActionTakeItem::m_ItemName = "" private
Definition at line 8 of file actiontakeitem.c.