DayzKode: DrowningMdfr Class Reference
DrowningMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
bool CheckIsDrowning (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
void PlayDrowningSound (int index)
Private Attributes
const int TICK_FREQUENCY = 1
Static Private Attributes
static const float STAMINA_RECOVERY_MULTIPLIER = 0
Detailed Description
Definition at line 1 of file drowning.c.
Member Function Documentation
ActivateCondition()
override bool DrowningMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 31 of file drowning.c.
    {
        return CheckIsDrowning(player);
    }
References CheckIsDrowning().
CheckIsDrowning()
bool DrowningMdfr::CheckIsDrowning (PlayerBase player) inline private
Definition at line 15 of file drowning.c.
    {
        int index = player.GetBoneIndexByName("head");
        vector pos = player.GetBonePositionWS(index);
        float depth = g_Game.GetWaterDepth(pos);
        if (player.IsSwimming())
        {
            return depth > PlayerConstants.DROWNING_SWIMMING_THRESHOLD;
        }
        else if (player.IsUnconscious())
        {
            return depth > PlayerConstants.DROWNING_UNCONSCIOUS_THRESHOLD;
        }
        return depth > PlayerConstants.DROWNING_DEFAULT_THRESHOLD;
    }
References PlayerConstants::DROWNING_DEFAULT_THRESHOLD, PlayerConstants::DROWNING_SWIMMING_THRESHOLD, PlayerConstants::DROWNING_UNCONSCIOUS_THRESHOLD, and g_Game.
Referenced by ActivateCondition(), and DeactivateCondition().
DeactivateCondition()
override bool DrowningMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 36 of file drowning.c.
    {
        return !CheckIsDrowning(player);
    }
References CheckIsDrowning().
Init()
override void DrowningMdfr::Init () inline private
Definition at line 6 of file drowning.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_DROWNING;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = TICK_FREQUENCY;
        m_SyncID                = eModifierSyncIDs.MODIFIER_SYNC_DROWNING;
    }
References DEFAULT_TICK_TIME_INACTIVE, m_ID, m_SyncID, m_TickIntervalActive, m_TickIntervalInactive, m_TrackActivatedTime, and TICK_FREQUENCY.
OnActivate()
override void DrowningMdfr::OnActivate (PlayerBase player) inline private
Definition at line 56 of file drowning.c.
    {
        player.SetDrowning(true);
        player.GetStaminaHandler().ActivateRecoveryModifier(EStaminaMultiplierTypes.DROWNING);
        player.RequestSoundEventEx(EPlayerSoundEventID.DROWNING_BREATH, false, EPlayerSoundEventParam.HIGHEST_PRIORITY);
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( PlayDrowningSound, 3000 ,false, 1);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and PlayDrowningSound().
OnDeactivate()
override void DrowningMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 80 of file drowning.c.
    {
        player.SetDrowning(false);
        player.GetStaminaHandler().DeactivateRecoveryModifier(EStaminaMultiplierTypes.DROWNING);
    }
OnReconnect()
override void DrowningMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 51 of file drowning.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void DrowningMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 41 of file drowning.c.
    {
        if (player.GetStaminaHandler().GetStamina() <= 0)
        {
            player.AddHealth("","",deltaT * -CfgGameplayHandler.GetHealthDepletionSpeed());
            player.AddHealth("","Shock",deltaT * -CfgGameplayHandler.GetShockDepletionSpeed());
            player.RequestSoundEventEx(EPlayerSoundEventID.DROWNING_PAIN, false, EPlayerSoundEventParam.HIGHEST_PRIORITY);
        }
    }
References CfgGameplayHandler::GetHealthDepletionSpeed(), and CfgGameplayHandler::GetShockDepletionSpeed().
PlayDrowningSound()
void DrowningMdfr::PlayDrowningSound (int index) inline private
Definition at line 65 of file drowning.c.
    {
        if (m_Player.m_IsDrowning)//check if we are still drowning after the delay
        {
            if (index == 0)
            {
                m_Player.RequestSoundEventEx(EPlayerSoundEventID.EXHAUSTED_BREATH, false, EPlayerSoundEventParam.HIGHEST_PRIORITY);
            }
            else if (index == 1)
            {
                m_Player.RequestSoundEventEx(EPlayerSoundEventID.DROWNING_BREATH, false, EPlayerSoundEventParam.HIGHEST_PRIORITY);
            }
        }
    }
References m_Player.
Referenced by OnActivate().
Member Data Documentation
STAMINA_RECOVERY_MULTIPLIER
const float DrowningMdfr::STAMINA_RECOVERY_MULTIPLIER = 0 static private
Definition at line 4 of file drowning.c.
Referenced by Init().
TICK_FREQUENCY
const int DrowningMdfr::TICK_FREQUENCY = 1 private
Definition at line 3 of file drowning.c.
Referenced by Init().