DayzKode: HeatComfortMdfr Class Reference
HeatComfortMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override string GetDebugTextSimple ()
override void Init ()
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Detailed Description
Definition at line 1 of file heatcomfortmdfr.c.
Member Function Documentation
ActivateCondition()
override bool HeatComfortMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 12 of file heatcomfortmdfr.c.
    {
        return true;
    }
DeactivateCondition()
override bool HeatComfortMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 17 of file heatcomfortmdfr.c.
    {
        return false;
    }
GetDebugText()
override string HeatComfortMdfr::GetDebugText () inline private
Definition at line 27 of file heatcomfortmdfr.c.
    {
        return m_Player.GetStatHeatComfort().Get().ToString();
    }
References m_Player.
GetDebugTextSimple()
override string HeatComfortMdfr::GetDebugTextSimple () inline private
Definition at line 32 of file heatcomfortmdfr.c.
    {
        return m_Player.GetStatHeatComfort().Get().ToString();
    }
References m_Player.
Init()
override void HeatComfortMdfr::Init () inline private
Definition at line 3 of file heatcomfortmdfr.c.
    {
        m_TrackActivatedTime    = false;
        m_ID                    = eModifiers.MDF_TEMPERATURE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void HeatComfortMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 22 of file heatcomfortmdfr.c.
    {
    }
OnTick()
override void HeatComfortMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 38 of file heatcomfortmdfr.c.
    {
        float heat_comfort = player.GetStatHeatComfort().Get();
        float health_loss;
        float value_normalized;
        if( heat_comfort > PlayerConstants.WATER_LOSS_THRESHOLD_HC_PLUS_LOW )
        {
            value_normalized = Math.Lerp(PlayerConstants.WATER_LOSS_THRESHOLD_HC_PLUS_LOW, PlayerConstants.WATER_LOSS_THRESHOLD_HC_PLUS_HIGH, heat_comfort);
            value_normalized = Math.Clamp(value_normalized, 0, 1);
            float water_loss = deltaT * Math.Lerp(PlayerConstants.WATER_LOSS_HC_PLUS_LOW, PlayerConstants.WATER_LOSS_HC_PLUS_HIGH, value_normalized);
            player.GetStatWater().Add(-water_loss);
            if( heat_comfort > PlayerConstants.WATER_LOSS_THRESHOLD_HC_PLUS_HIGH )
            {
                value_normalized = Math.Lerp(PlayerConstants.WATER_LOSS_THRESHOLD_HC_PLUS_HIGH, 1.0, heat_comfort);
                value_normalized = Math.Clamp(value_normalized, 0, 1);
                health_loss = deltaT * Math.Lerp(PlayerConstants.HEALTH_LOSS_HC_PLUS_LOW, PlayerConstants.HEALTH_LOSS_HC_PLUS_HIGH, value_normalized);
            }
        }
        if( heat_comfort < PlayerConstants.ENERGY_LOSS_THRESHOLD_HC_MINUS_LOW )
        {
            value_normalized = Math.InverseLerp(PlayerConstants.ENERGY_LOSS_THRESHOLD_HC_MINUS_LOW, PlayerConstants.ENERGY_LOSS_THRESHOLD_HC_MINUS_HIGH, heat_comfort);
            value_normalized = Math.Clamp(value_normalized, 0, 1);
            float energy_loss = deltaT * Math.Lerp(PlayerConstants.ENERGY_LOSS_HC_MINUS_LOW, PlayerConstants.ENERGY_LOSS_HC_MINUS_HIGH, value_normalized);
            player.GetStatEnergy().Add(-energy_loss);
            if( heat_comfort < PlayerConstants.ENERGY_LOSS_THRESHOLD_HC_MINUS_HIGH )
            {
                value_normalized = Math.InverseLerp(PlayerConstants.ENERGY_LOSS_THRESHOLD_HC_MINUS_HIGH, -1.0, heat_comfort);
                value_normalized = Math.Clamp(value_normalized, 0, 1);
                health_loss = deltaT * Math.Lerp(PlayerConstants.HEALTH_LOSS_HC_MINUS_LOW, PlayerConstants.HEALTH_LOSS_HC_MINUS_HIGH, value_normalized);
            }
        }
        if( health_loss != 0 )
        {
            player.AddHealth("","",-health_loss);
        }
    }
References Math::Clamp(), PlayerConstants::ENERGY_LOSS_HC_MINUS_HIGH, PlayerConstants::ENERGY_LOSS_HC_MINUS_LOW, PlayerConstants::ENERGY_LOSS_THRESHOLD_HC_MINUS_HIGH, PlayerConstants::ENERGY_LOSS_THRESHOLD_HC_MINUS_LOW, PlayerConstants::HEALTH_LOSS_HC_MINUS_HIGH, PlayerConstants::HEALTH_LOSS_HC_MINUS_LOW, PlayerConstants::HEALTH_LOSS_HC_PLUS_HIGH, PlayerConstants::HEALTH_LOSS_HC_PLUS_LOW, Math::InverseLerp(), Math::Lerp(), PlayerConstants::WATER_LOSS_HC_PLUS_HIGH, PlayerConstants::WATER_LOSS_HC_PLUS_LOW, PlayerConstants::WATER_LOSS_THRESHOLD_HC_PLUS_HIGH, and PlayerConstants::WATER_LOSS_THRESHOLD_HC_PLUS_LOW.