DayzKode: EffectParticle Class Reference
EffectParticle Class Reference
Wrapper class for managing particles through SEffectManager.
Private Member Functions
EffectType
Information about what type of effect the Effect is, without the need for casting
override EffectType GetEffectType ()
Get what type of effect the Effect is.
override bool IsParticle ()
Check whether the Effect is EffectParticle without casting.
Main particle
Set or get the main particle which this Effect will manage
void SetParticle (Particle p)
Sets the main particle which this Effect will manage.
Particle GetParticle ()
Gets the main particle which this Effect is managing.
Playback
Methods to Play/Stop Effect Generally, SEffectManager.Play methods are used instead of Start
override void Start ()
Plays all elements this effect consists of.
override void Stop ()
Stops all elements this effect consists of.
Attach
Helper methods for attaching to prent
void AttachTo (Object obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_to_world=false)
Read Particle.AddAsChild.
void ReAttach ()
Helper method to attach to parent using stored settings.
protected void AddAsChild (Object obj, vector local_pos, vector local_ori, bool force_rotation_to_world)
Helper method to attach to parent.
Events
Various events that can be overriden for custom behaviour
void Event_OnPlayStart ()
Event which just simply exists (DEPRECATED)
void Event_OnPlayStarted ()
Event which just simply exists (DEPRECATED)
Generic API
Setters and getters for generic data and properties
void SetParticleID (int id)
Sets the id of the particle to be used.
int GetParticleID ()
Gets the id of the particle to be used.
void SetCurrentParticleID (int id)
Sets the id of the particle to be used.
int GetCurrentParticleID ()
Gets the current id of the managed Particle.
override void SetCurrentParent (Object parent_obj, bool updateCached=true)
Set current parent of the managed Particle.
override Object GetCurrentParent ()
Get the current parent of the managed Particle.
override void SetCurrentPosition (vector pos, bool updateCached=true)
Set the current world position of the managed Particle.
override vector GetCurrentPosition ()
Get the current world position of the managed Particle.
override void SetCurrentLocalPosition (vector pos, bool updateCached=true)
Set the current local position of the managed Particle.
override vector GetCurrentLocalPosition ()
Get the current local position of the managed Particle.
void SetOrientation (vector ori)
Set orientation of the EffectParticle.
vector GetOrientation ()
Get the orientation of the EffectParticle.
void SetCurrentOrientation (vector ori, bool updateCached=true)
Set the current orientation of the managed Particle.
vector GetCurrentOrientation ()
Get the current orientation of the managed Particle.
void ForceParticleRotationRelativeToWorld (bool state)
Set orientation setting to be used by the effect when the Effect starts.
bool IsParticleRotationRelativeToWorld ()
Get the orientation setting to be used by the effect when the Effect starts.
bool IsParticleCurrentRotationRelativeToWorld ()
Get the current orientation setting to be used by the managed Particle.
Private Attributes
protected Particle m_ParticleObj
The main Particle effect that this Effect wrapper manages.
Generic data
Generic data for the particle
protected int m_ParticleID
The ID in the ParticleList to create Particle from.
protected vector m_Orientation
Orientation set by SetOrientation.
protected bool m_ForceRotationRelativeToWorld
Orientation setting to be used by the effect when the Effect starts.
DEPRECATED
Methods which exist for backwards compatibility and are no longer in use or have never been in use
protected vector m_ParticleOrientation
protected Object m_Object
void EffectParticle ()
ctor
void ~EffectParticle ()
dtor
override void InitEffect ()
init
override string GetDebugName ()
Override when getting debug information.
override void ValidateStart ()
Validation whether an effect truly started playing or if the Effect should stop as none is present.
void CheckLifeSpan ()
Was never called and probably should never be called.
void SetDecalOwner (Object o)
Detailed Description
Wrapper class for managing particles through SEffectManager.
Definition at line 4 of file effectparticle.c.
Constructor & Destructor Documentation
EffectParticle()
void EffectParticle::EffectParticle () inline private
ctor
Definition at line 34 of file effectparticle.c.
    {
    }
~EffectParticle()
void EffectParticle::~EffectParticle () inline private
dtor
Definition at line 42 of file effectparticle.c.
    {
    }
Member Function Documentation
AddAsChild()
protected void EffectParticle::AddAsChild (Object obj, vector local_pos, vector local_ori, bool force_rotation_to_world) inline private
Helper method to attach to parent.
Definition at line 251 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
        {
            p.AddAsChild(obj, local_pos, local_ori, force_rotation_to_world);
        }
    }
References Particle::AddAsChild(), and GetParticle().
Referenced by AttachTo(), and ReAttach().
AttachTo()
void EffectParticle::AttachTo (Object obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_rotation_to_world = false) inline private
Read Particle.AddAsChild.
Definition at line 227 of file effectparticle.c.
    {
        // Update the cached variables...
        SetParent(obj);
        SetLocalPosition(local_pos);
        SetAttachedLocalOri(local_ori);
        ForceParticleRotationRelativeToWorld(force_rotation_to_world);
        // Now attach it
        AddAsChild(obj, local_pos, local_ori, force_rotation_to_world);
    }
References AddAsChild(), ForceParticleRotationRelativeToWorld(), SetAttachedLocalOri(), SetLocalPosition(), and SetParent().
CheckLifeSpan()
void EffectParticle::CheckLifeSpan () inline private
Was never called and probably should never be called.
Warning
Emptied the functionality as it is relatively unsafe...
Definition at line 550 of file effectparticle.c.
    {
        /*
        if ( !m_ParticleObj )
        {
            delete this;
        }
        OnCheckUpdate();
        */
    }
Event_OnPlayStart()
void EffectParticle::Event_OnPlayStart () inline private
Event which just simply exists (DEPRECATED)
Warning
Never called or used
Note
Use Event_OnStarted instead
Definition at line 274 of file effectparticle.c.
    {
    }
Event_OnPlayStarted()
void EffectParticle::Event_OnPlayStarted () inline private
Event which just simply exists (DEPRECATED)
Warning
Never called or used
Note
Use Event_OnStarted instead
Definition at line 284 of file effectparticle.c.
    {
    }
ForceParticleRotationRelativeToWorld()
void EffectParticle::ForceParticleRotationRelativeToWorld (bool state) inline private
Set orientation setting to be used by the effect when the Effect starts.
Warning
Only caches it into a variable to be used by Start, does not live update when called afterwards
Note
There is no way to update this immediately
Parameters
state bool Whether to keep WS orientation when attaching it to parent
Definition at line 503 of file effectparticle.c.
    {
        m_ForceRotationRelativeToWorld = state;
    }
References m_ForceRotationRelativeToWorld.
Referenced by AttachTo(), and SEffectManager::PlayOnObject().
GetCurrentLocalPosition()
override vector EffectParticle::GetCurrentLocalPosition () inline private
Get the current local position of the managed Particle.
Returns
vector The current local position of the managed Particle
Definition at line 431 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
        {
            Object parent = GetParent();
            if (parent)
                return parent.WorldToModel(p.GetPosition());
            else
                return p.GetPosition();
        }
        else
            return super.GetLocalPosition();
    }
References GetParent(), and GetParticle().
GetCurrentOrientation()
vector EffectParticle::GetCurrentOrientation () inline private
Get the current orientation of the managed Particle.
Returns
vector The current orientation of the managed Particle
Definition at line 487 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
            return p.GetOrientation();
        else
            return vector.Zero;
    }
References GetParticle(), and vector::Zero.
GetCurrentParent()
override Object EffectParticle::GetCurrentParent () inline private
Get the current parent of the managed Particle.
Returns
Object The currrent parent of the Particle
Definition at line 367 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
            return Object.Cast(p.GetParent());
        else
            return super.GetParent();
    }
References GetParticle().
GetCurrentParticleID()
int EffectParticle::GetCurrentParticleID () inline private
Gets the current id of the managed Particle.
Returns
int Particle ID registered in ParticleList
Definition at line 338 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
        {
            return p.GetParticleID();
        }
        else
        {
            return ParticleList.INVALID;
        }
    }
References GetParticle(), Particle::GetParticleID(), and ParticleList::INVALID.
GetCurrentPosition()
override vector EffectParticle::GetCurrentPosition () inline private
Get the current world position of the managed Particle.
Returns
vector The current world position of the managed Particle
Definition at line 396 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
            return p.GetPosition();
        else
            return super.GetPosition();
    }
References GetParticle().
GetDebugName()
override string EffectParticle::GetDebugName () inline private
Override when getting debug information.
Definition at line 67 of file effectparticle.c.
    {
        string identifier;
        if (GetParticle())
        {
            identifier = GetParticle().GetDebugNameNative();
        }
        else
        {
            identifier = "NO_PARTICLE";
        }
        return string.Format("%1:%2:%3", super.GetDebugName(), m_ParticleID, identifier);
    }
References string::Format(), GetParticle(), and m_ParticleID.
Referenced by ValidateStart().
GetEffectType()
override EffectType EffectParticle::GetEffectType () inline private
Get what type of effect the Effect is.
Returns
EffectType What type of effect the Effect is
Definition at line 107 of file effectparticle.c.
    {
        return EffectType.PARTICLE;
    }
GetOrientation()
vector EffectParticle::GetOrientation () inline private
Get the orientation of the EffectParticle.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The orientation of EffectParticle
Definition at line 463 of file effectparticle.c.
    {
        return m_Orientation;
    }
References m_Orientation.
Referenced by Start().
GetParticle()
Particle EffectParticle::GetParticle () inline private
Gets the main particle which this Effect is managing.
Returns
Particle Main particle which this Effect is managing
Definition at line 162 of file effectparticle.c.
    {
        return m_ParticleObj;
    }
References m_ParticleObj.
Referenced by AddAsChild(), Hit_MeatBones::BloodSplatGround(), CreateParticle(), DrawDebugShape(), EffEngineSmoke::Event_OnFrameUpdate(), GetCurrentLocalPosition(), GetCurrentOrientation(), GetCurrentParent(), GetCurrentParticleID(), GetCurrentPosition(), GetDebugName(), IsParticleCurrentRotationRelativeToWorld(), IsParticleRotationRelativeToWorld(), ManBase::OnParticleEvent(), SetCurrentLocalPosition(), SetCurrentOrientation(), SetCurrentParticleID(), SetCurrentPosition(), BleedingSourcesManagerBase::SetDiag(), EffExhaustSmoke::SetParticleStateLight(), Stop(), EffCoolantSteam::UpdateParticle(), and ValidateStart().
GetParticleID()
int EffectParticle::GetParticleID () inline private
Gets the id of the particle to be used.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
int Particle ID registered in ParticleList
Definition at line 313 of file effectparticle.c.
    {
        return m_ParticleID;
    }
References m_ParticleID.
InitEffect()
override void EffectParticle::InitEffect () inline private
init
Definition at line 50 of file effectparticle.c.
    {
        super.InitEffect();
        // Would be neat, but since particles are often already playing
        // BEFORE they are even registered as the particle for the Effect
        // Better to just keep that one I guess..
        // Event_OnStarted.Remove(Event_OnEffectStarted);
        // Will be called by the particle events
        Event_OnStopped.Remove(Event_OnEffectEnded);
    }
References Event_OnEffectEnded, Event_OnStopped, and ScriptInvoker::Remove().
IsParticle()
override bool EffectParticle::IsParticle () inline private
Check whether the Effect is EffectParticle without casting.
Returns
bool Whether the Effect is EffectParticle
Definition at line 116 of file effectparticle.c.
    {
        return true;
    }
IsParticleCurrentRotationRelativeToWorld()
bool EffectParticle::IsParticleCurrentRotationRelativeToWorld () inline private
Get the current orientation setting to be used by the managed Particle.
Returns
bool Whether the managed Particle is only updating position from parent
Definition at line 527 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
            return p.IsHierarchyPositionOnly();
        else
            return false;
    }
References GetParticle().
IsParticleRotationRelativeToWorld()
bool EffectParticle::IsParticleRotationRelativeToWorld () inline private
Get the orientation setting to be used by the effect when the Effect starts.
Warning
Only gets the cached variable, for immediate effect use IsParticleCurrentRotationRelativeToWorld
Returns
bool Whether to keep WS orientation when attaching it to parent
Definition at line 513 of file effectparticle.c.
    {
        Particle p = GetParticle();
        if (p)
            return p.IsHierarchyPositionOnly();
        else
            return m_ForceRotationRelativeToWorld;
    }
References GetParticle(), and m_ForceRotationRelativeToWorld.
Referenced by ReAttach(), and Start().
ReAttach()
void EffectParticle::ReAttach () inline private
Helper method to attach to parent using stored settings.
Definition at line 242 of file effectparticle.c.
    {
        // Skip the updating, as we are going to reuse what was set before
        AddAsChild( GetParent(), GetLocalPosition(), GetAttachedLocalOri(), IsParticleRotationRelativeToWorld());
    }
References AddAsChild(), GetAttachedLocalOri(), GetLocalPosition(), GetParent(), and IsParticleRotationRelativeToWorld().
Referenced by SetCurrentLocalPosition(), and SetCurrentParent().
SetCurrentLocalPosition()
override void EffectParticle::SetCurrentLocalPosition (vector pos, bool updateCached = true) inline private
Set the current local position of the managed Particle.
Parameters
pos vector The current local position for the managed Particle
updateCached bool Whether to update the cached variable
Definition at line 411 of file effectparticle.c.
    {
        super.SetCurrentLocalPosition(pos, updateCached);
        Particle p = GetParticle();
        if (p)
        {
            Object parent = GetParent();
            if (parent)
                ReAttach();
            else
                p.SetPosition(pos);
        }
    }
References GetParent(), GetParticle(), and ReAttach().
SetCurrentOrientation()
void EffectParticle::SetCurrentOrientation (vector ori, bool updateCached = true) inline private
Set the current orientation of the managed Particle.
Parameters
ori vector Orientation in degrees (yaw, pitch, roll)
Definition at line 472 of file effectparticle.c.
    {
        if ( updateCached)
            SetOrientation(ori);
        Particle p = GetParticle();
        if (p)
            p.SetOrientation(ori);
    }
References GetParticle(), and SetOrientation().
SetCurrentParent()
override void EffectParticle::SetCurrentParent (Object parent_obj, bool updateCached = true) inline private
Set current parent of the managed Particle.
Parameters
parent_obj Object The parent for the Particle
updateCached bool Whether to update the cached variable
Definition at line 356 of file effectparticle.c.
    {
        super.SetCurrentParent(parent_obj, updateCached);
        ReAttach();
    }
References ReAttach().
SetCurrentParticleID()
void EffectParticle::SetCurrentParticleID (int id) inline private
Sets the id of the particle to be used.
Note
Particle will not update immediately, but ParticleSource will
Parameters
id int Particle ID registered in ParticleList
Definition at line 323 of file effectparticle.c.
    {
        m_ParticleID = id;
        Particle p = GetParticle();
        if (p)
        {
            p.SetSource(id);
        }
    }
References GetParticle(), m_ParticleID, and Particle::SetSource().
SetCurrentPosition()
override void EffectParticle::SetCurrentPosition (vector pos, bool updateCached = true) inline private
Set the current world position of the managed Particle.
Parameters
pos vector The current world position for the Particle
updateCached bool Whether to update the cached variable
Definition at line 382 of file effectparticle.c.
    {
        super.SetCurrentPosition(pos, updateCached);
        Particle p = GetParticle();
        if (p)
            p.SetPosition(pos);
    }
References GetParticle().
SetDecalOwner()
void EffectParticle::SetDecalOwner (Object o) inline private
Definition at line 562 of file effectparticle.c.
    {
        m_Object = o;
    }
References m_Object.
Referenced by ManBase::OnParticleEvent().
SetOrientation()
void EffectParticle::SetOrientation (vector ori) inline private
Set orientation of the EffectParticle.
Warning
Only sets the cached variable, for immediate effect use SetCurrent variant
Parameters
ori vector Orientation in degrees (yaw, pitch, roll)
Definition at line 453 of file effectparticle.c.
    {
        m_Orientation = ori;
    }
References m_Orientation.
Referenced by SetCurrentOrientation().
SetParticle()
void EffectParticle::SetParticle (Particle p) inline private
Sets the main particle which this Effect will manage.
Parameters
p Particle Main particle which this Effect will manage
Definition at line 134 of file effectparticle.c.
    {
        // Unregister the events on the old
        if (m_ParticleObj)
        {
            ParticleEvents ope = m_ParticleObj.GetEvents();
            ope.Event_OnParticleStart.Remove(Event_OnEffectStarted);
            ope.Event_OnParticleStop.Remove(Event_OnEffectEnded);
        }
        // Assign the new main Particle
        m_ParticleObj = p;
        // Register the events on the new
        if (m_ParticleObj)
        {
            ParticleEvents npe = m_ParticleObj.GetEvents();
            npe.Event_OnParticleStart.Insert(Event_OnEffectStarted);
            // We will use Stop instead of End, as old particles were destroyed when they stopped
            // And this system kinda relies on that
            npe.Event_OnParticleStop.Insert(Event_OnEffectEnded);
        }
    }
References Event_OnEffectEnded, Event_OnEffectStarted, ParticleEvents::Event_OnParticleStart, ParticleEvents::Event_OnParticleStop, ScriptInvoker::Insert(), m_ParticleObj, and ScriptInvoker::Remove().
Referenced by EffBulletImpactBase::Event_OnStarted(), Start(), and Stop().
SetParticleID()
void EffectParticle::SetParticleID (int id) inline private
Sets the id of the particle to be used.
Note
Only changes the cached variable, for immediate, use SetCurrentParticleID
Parameters
id int Particle ID registered in ParticleList
Definition at line 303 of file effectparticle.c.
    {
        m_ParticleID = id;
    }
References m_ParticleID.
Referenced by BleedingSourceEffect::BleedingSourceEffect(), BleedingSourceEffect(), BloodSplatter::BloodSplatter(), EffBreathVapourHeavy::EffBreathVapourHeavy(), EffBreathVapourLight::EffBreathVapourLight(), EffBreathVapourMedium::EffBreathVapourMedium(), EffBulletImpactTest::EffBulletImpactTest(), EffGeneratorSmoke::EffGeneratorSmoke(), EffSwarmingFlies::EffSwarmingFlies(), EffVomit::EffVomit(), EffVomitBlood::EffVomitBlood(), LandmineExplosion::LandmineExplosion(), MenuCarEngineSmoke::MenuCarEngineSmoke(), MenuEvaporation::MenuEvaporation(), and EffVehicleSmoke::SetParticleState().
Start()
override void EffectParticle::Start () inline private
Plays all elements this effect consists of.
Note
Is called by SEffectManager.Play methods
Definition at line 181 of file effectparticle.c.
    {
        if (m_ParticleID > 0)
        {
            vector pos = GetPosition();
            vector ori = GetOrientation();
            if (m_ParentObject)
            {
                pos = GetLocalPosition();
                ori = GetAttachedLocalOri();
            }
            SetParticle(ParticleManager.GetInstance().CreateParticle(m_ParticleID, pos, true, GetParent(), ori, IsParticleRotationRelativeToWorld()));
        }
        super.Start();
    }
References GetAttachedLocalOri(), GetLocalPosition(), GetOrientation(), GetParent(), GetPosition, IsParticleRotationRelativeToWorld(), m_ParentObject, m_ParticleID, ParticleManager(), and SetParticle().
Referenced by EffVehicleSmoke::SetParticleState().
Stop()
override void EffectParticle::Stop () inline private
Stops all elements this effect consists of.
Note
Alternatively use SEffectManager.Stop(effect_id)
Definition at line 204 of file effectparticle.c.
    {
        if ( GetParticle() )
        {
            GetParticle().Stop();
            SetParticle(null);
        }
        super.Stop();
    }
References GetParticle(), SetParticle(), and Particle::Stop().
Referenced by EffVehicleSmoke::SetParticleState(), and ValidateStart().
ValidateStart()
override void EffectParticle::ValidateStart () inline private
Validation whether an effect truly started playing or if the Effect should stop as none is present.
Note
Override this when inheriting to create own validation check
Is called from Event_OnStarted invoker after Event_OnStarted has been performed
Definition at line 87 of file effectparticle.c.
    {
        if (!GetParticle())
        {
            ErrorEx(string.Format("No Particle started playing, stopping EffectParticle: %1", GetDebugName()), ErrorExSeverity.WARNING);
            Stop();
        }
    }
References ErrorEx, GetDebugName(), GetParticle(), and Stop().
Member Data Documentation
m_ForceRotationRelativeToWorld
protected bool EffectParticle::m_ForceRotationRelativeToWorld private
Orientation setting to be used by the effect when the Effect starts.
Definition at line 18 of file effectparticle.c.
Referenced by ForceParticleRotationRelativeToWorld(), and IsParticleRotationRelativeToWorld().
m_Object
protected Object EffectParticle::m_Object private
Definition at line 26 of file effectparticle.c.
Referenced by SetDecalOwner().
m_Orientation
protected vector EffectParticle::m_Orientation private
Orientation set by SetOrientation.
Definition at line 16 of file effectparticle.c.
Referenced by GetOrientation(), and SetOrientation().
m_ParticleID
protected int EffectParticle::m_ParticleID private
The ID in the ParticleList to create Particle from.
Definition at line 14 of file effectparticle.c.
Referenced by GetDebugName(), GetParticleID(), SetCurrentParticleID(), SetParticleID(), and Start().
m_ParticleObj
protected Particle EffectParticle::m_ParticleObj private
The main Particle effect that this Effect wrapper manages.
Definition at line 7 of file effectparticle.c.
Referenced by GetParticle(), and SetParticle().
m_ParticleOrientation
protected vector EffectParticle::m_ParticleOrientation private
Definition at line 25 of file effectparticle.c.