DayzKode: ActionDetachFromTarget Class Reference
ActionDetachFromTarget Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDetachFromTarget ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
int FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item)
override Object GetDisplayInteractObject (PlayerBase player, ActionTarget target)
override GetInputType ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Detailed Description
Definition at line 1 of file actiondetachfromtarget.c.
Constructor & Destructor Documentation
ActionDetachFromTarget()
void ActionDetachFromTarget::ActionDetachFromTarget () inline private
Definition at line 10 of file actiondetachfromtarget.c.
    {
        m_Text = "#take_to_hands";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionDetachFromTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 78 of file actiondetachfromtarget.c.
    {
        if ( GetGame().IsMultiplayer() && GetGame().IsServer() ) return true;
        return FindSlotIdToDetach(player, target, item) != InventorySlots.INVALID);
    }
References FindSlotIdToDetach(), and GetGame().
CreateActionData()
override ActionData ActionDetachFromTarget::CreateActionData () inline private
Definition at line 20 of file actiondetachfromtarget.c.
    {
        DetachActionData action_data = new DetachActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionDetachFromTarget::CreateConditionComponents () inline private
Definition at line 4 of file actiondetachfromtarget.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
FindSlotIdToDetach()
int ActionDetachFromTarget::FindSlotIdToDetach (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file actiondetachfromtarget.c.
    {
        EntityAI target_entity = EntityAI.Cast(target.GetObject());
        if ( player && target_entity )
        {
            array<string> selections = new array<string>();
            target_entity.GetActionComponentNameList( target.GetComponentIndex(),selections );
            if ( target_entity && target_entity.GetInventory() && target_entity.GetInventory().AttachmentCount() > 0 )
            {
                for(int i = 0; i < selections.Count(); i++ )
                {
                    int target_slot_id = InventorySlots.GetSlotIdFromString( selections[i] );
                    EntityAI att = target_entity.GetInventory().FindAttachment(target_slot_id);
                    if ( att && player.GetInventory().CanAddEntityIntoHands(att) )
                    {
                        if ( att.CanDetachAttachment( target_entity ) && target_entity.CanReleaseAttachment( att ) )
                            return target_slot_id;
                    }
                }
            }
        }
        return InventorySlots.INVALID;
    }
References InventorySlots::GetSlotIdFromString().
Referenced by ActionCondition(), GetDisplayInteractObject(), and SetupAction().
GetDisplayInteractObject()
override Object ActionDetachFromTarget::GetDisplayInteractObject (PlayerBase player, ActionTarget target) inline private
Definition at line 85 of file actiondetachfromtarget.c.
    {
        int target_slot_id = FindSlotIdToDetach(player, target, null);
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if(target_slot_id != InventorySlots.INVALID)
        {
            return target_entity.GetInventory().FindAttachment(target_slot_id);
        }
        return null;
    }
References FindSlotIdToDetach().
GetInputType()
override ActionDetachFromTarget::GetInputType () inline private
Definition at line 15 of file actiondetachfromtarget.c.
    {
        return ContinuousInteractActionInput;
    }
OnExecuteClient()
override void ActionDetachFromTarget::OnExecuteClient (ActionData action_data) inline private
Definition at line 97 of file actiondetachfromtarget.c.
    {
        Process(action_data);
    }
References Process().
OnExecuteServer()
override void ActionDetachFromTarget::OnExecuteServer (ActionData action_data) inline private
Definition at line 102 of file actiondetachfromtarget.c.
    {
        if(!GetGame().IsMultiplayer())
            Process(action_data);
    }
References GetGame(), and Process().
Process()
void ActionDetachFromTarget::Process (ActionData action_data) inline private
Definition at line 108 of file actiondetachfromtarget.c.
    {
        ClearInventoryReservationEx(action_data);
        DetachActionData action_data_a = DetachActionData.Cast(action_data);
        EntityAI target_entity = EntityAI.Cast( action_data_a.m_Target.GetObject() );
        ItemBase attachment = ItemBase.Cast(target_entity.GetInventory().FindAttachment(action_data_a.m_AttSlot));
        if(attachment)
        {
            float stackable = attachment.GetTargetQuantityMax();
            if( stackable == 0 || stackable >= attachment.GetQuantity() )
            {
                //take to hands
                action_data.m_Player.PredictiveTakeEntityToHands( attachment );
            }
            else if( stackable != 0 && stackable < attachment.GetQuantity() )
            {
                //split and take to hands
                attachment.SplitIntoStackMaxHandsClient( action_data.m_Player );
            }
        }
    }
References ClearInventoryReservationEx(), DetachActionData::m_AttSlot, ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
SetupAction()
override bool ActionDetachFromTarget::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 53 of file actiondetachfromtarget.c.
    {
        int attSlotId = InventorySlots.INVALID;
        if (!GetGame().IsDedicatedServer() )
        {
            attSlotId = FindSlotIdToDetach(player, target, item);
        }
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            if (!GetGame().IsDedicatedServer())
            {
                if(attSlotId != InventorySlots.INVALID)
                {
                    DetachActionData action_data_a = DetachActionData.Cast(action_data);
                    action_data_a.m_AttSlot = attSlotId;
                    return true;
                }
                return false;
            }
            return true;
        }
        return false;
    }
References FindSlotIdToDetach(), GetGame(), and DetachActionData::m_AttSlot.