DayzKode: LogTemplates Class Reference
LogTemplates Class Reference
Static Private Member Functions
static LogTemplate GetTemplate (LogTemplateID template_id)
static void Init ()
static private void RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label)
Static Private Attributes
static private ref map< LogTemplateID, ref LogTemplate > m_LogTemplates
static LogTemplateID TEMPLATE_BROADCAST = 3
static LogTemplateID TEMPLATE_JANOSIK = 1
static LogTemplateID TEMPLATE_PLAYER_WEIGHT = 2
static LogTemplateID TEMPLATE_UNKNOWN = 0
Detailed Description
Definition at line 4 of file logtemplates.c.
Member Function Documentation
GetTemplate()
static LogTemplate LogTemplates::GetTemplate (LogTemplateID template_id) inline static private
Definition at line 49 of file logtemplates.c.
    {
        if ( m_LogTemplates && m_LogTemplates.Contains(template_id) )
        {
            return m_LogTemplates.Get(template_id);
        }
        Debug.Log("Template ID: "+string.ToString(template_id)+" does not exist!", "LogTemplate.h -> GetTemplate()", "System", "Get Log Template", "None");
        return NULL;
    }
References Debug::Log(), m_LogTemplates, and ToString().
Referenced by LogError(), LogInfo(), and LogWarning().
Init()
static void LogTemplates::Init () inline static private
Definition at line 37 of file logtemplates.c.
    {
        //                      | Template Name         | author            | plugin                | label                 ////
        RegisterLogTamplate(    TEMPLATE_UNKNOWN        ,"Unknown"          ,"Unknown"              ,"Unknown"              );//
        RegisterLogTamplate(    TEMPLATE_JANOSIK        ,"Janosik"          ,"GUI"                  ,"None"                 );//
        RegisterLogTamplate(    TEMPLATE_PLAYER_WEIGHT  ,"Unknown"          ,"PlayerBase"           ,"Weight"               );//
        RegisterLogTamplate(    TEMPLATE_BROADCAST      ,"Unknown"          ,"PluginMessageManager" ,"Broadcast"            );//
    }
References RegisterLogTamplate(), TEMPLATE_BROADCAST, TEMPLATE_JANOSIK, TEMPLATE_PLAYER_WEIGHT, and TEMPLATE_UNKNOWN.
Referenced by DayZGame().
RegisterLogTamplate()
static private void LogTemplates::RegisterLogTamplate (LogTemplateID template_id, string author, string plugin, string label) inline static private
Definition at line 8 of file logtemplates.c.
    {
        if ( m_LogTemplates == NULL )
        {
            m_LogTemplates  = new map<LogTemplateID, ref LogTemplate>;
        }
        if ( m_LogTemplates.Contains(template_id) )
        {
            Debug.Log("Template ID: "+string.ToString(template_id)+" is alredy exist!", "LogTemplate.h -> OnInit()", "System", "Template Registration", "None");
        }
        else
        {
            LogTemplate params = new LogTemplate(author, plugin, label);
            m_LogTemplates.Set(template_id, params);
        }
    }
References Debug::Log(), m_LogTemplates, and ToString().
Referenced by Init().
Member Data Documentation
m_LogTemplates
private ref map<LogTemplateID, ref LogTemplate> LogTemplates::m_LogTemplates static private
Definition at line 6 of file logtemplates.c.
Referenced by GetTemplate(), and RegisterLogTamplate().
TEMPLATE_BROADCAST
LogTemplateID LogTemplates::TEMPLATE_BROADCAST = 3 static private
Definition at line 35 of file logtemplates.c.
Referenced by Init().
TEMPLATE_JANOSIK
LogTemplateID LogTemplates::TEMPLATE_JANOSIK = 1 static private
Definition at line 33 of file logtemplates.c.
Referenced by Init().
TEMPLATE_PLAYER_WEIGHT
LogTemplateID LogTemplates::TEMPLATE_PLAYER_WEIGHT = 2 static private
Definition at line 34 of file logtemplates.c.
Referenced by Init().
TEMPLATE_UNKNOWN
LogTemplateID LogTemplates::TEMPLATE_UNKNOWN = 0 static private
Definition at line 32 of file logtemplates.c.
Referenced by Init().