DayzKode: SpookyArea Class Reference
SpookyArea Class Reference
Private Member Functions
override void EEDelete (EntityAI parent)
override void EEInit ()
override void InitZone ()
override void InitZoneClient ()
override void InitZoneServer ()
override void SetupZoneData (EffectAreaParams params)
Detailed Description
Definition at line 2 of file spookyarea.c.
Member Function Documentation
EEDelete()
override void SpookyArea::EEDelete (EntityAI parent) inline private
Definition at line 60 of file spookyarea.c.
    {
        super.EEDelete( parent );
    }
EEInit()
override void SpookyArea::EEInit () inline private
Definition at line 13 of file spookyarea.c.
    {
        // We make sure we have the particle array
        if ( !m_ToxicClouds )
            m_ToxicClouds = new array<Particle>;
        SetSynchDirty();
        #ifdef DEVELOPER
        // Debugs when placing entity by hand using internal tools
        if ( GetGame().IsServer() && !GetGame().IsMultiplayer() )
        {
            Debug.Log("YOU CAN IGNORE THE FOLLOWING DUMP");
            InitZone();
            Debug.Log("YOU CAN USE FOLLOWING DATA PROPERLY");
        }
        #endif
        if ( GetGame().IsClient() && GetGame().IsMultiplayer() )
            InitZone();
        super.EEInit();
    }
References GetGame(), InitZone(), Debug::Log(), and EffectArea::m_ToxicClouds.
InitZone()
override void SpookyArea::InitZone () inline private
Definition at line 38 of file spookyarea.c.
    {
        super.InitZone();
    }
Referenced by EEInit().
InitZoneClient()
override void SpookyArea::InitZoneClient () inline private
Definition at line 52 of file spookyarea.c.
    {
        super.InitZoneClient();
        // We spawn VFX on client
        PlaceParticles( GetWorldPosition(), m_Radius, m_InnerRings, m_InnerSpacing, m_OuterRingToggle, m_OuterSpacing, m_OuterRingOffset, m_ParticleID );
    }
References GetWorldPosition(), EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_OuterRingOffset, EffectArea::m_OuterRingToggle, EffectArea::m_OuterSpacing, EffectArea::m_ParticleID, EffectArea::m_Radius, and EffectArea::PlaceParticles().
InitZoneServer()
override void SpookyArea::InitZoneServer () inline private
Definition at line 43 of file spookyarea.c.
    {
        super.InitZoneServer();
        // We create the trigger on server
        if ( m_TriggerType != "" )
            CreateTrigger( m_Position, m_Radius );
    }
References CreateTrigger(), EffectArea::m_Position, EffectArea::m_Radius, and EffectArea::m_TriggerType.
SetupZoneData()
override void SpookyArea::SetupZoneData (EffectAreaParams params) inline private
Definition at line 8 of file spookyarea.c.
    {
        super.SetupZoneData( params );
    }