DayzKode: PPERequesterBase Class Reference
PPERequesterBase Class Reference
Private Member Functions
protected void ClearRequesterData ()
void DbgPrnt (string text)
map< int, ref map< int, ref PPERequestParamDataBase > > GetActiveRequestStructure ()
int GetCategoryMask ()
mask for mass-handling methods like 'StopAllEffects'
override int GetCategoryMask ()
PPERequestParamDataBase GetRequestData (int mat_id, int param_idx, int type)
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
int GetRequesterIDX ()
Returns requester index.
bool IsRequesterRunning ()
protected void OnStart (Param par=null)
protected void OnStop (Param par=null)
automatically resets all material parameters of this requester to defaults
void OnUpdate (float delta)
void PPERequesterBase (int requester_IDX)
protected PPERequestParamDataBase PrepareData (int mat_id, int param_idx, int type)
protected void QueueValuesSend ()
Sets this requester to update in the manager.
protected float RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative)
converts all values used to relative values (if not relative already)
protected void SendCurrentValueData (PPERequestParamDataBase data)
protected void SetDefaultValuesAll ()
Sets all requested values to default, ignoring them in further calculations.
void SetRequesterIDX (int idx)
automatically assigned by PPERequesterBank
void SetRequesterUpdating (bool state)
Has to be set for the requester to be handled.
protected void SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueBoolDefault (int mat_id, int param_idx)
protected void SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueColorDefault (int mat_id, int param_idx)
protected void SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator=PPOperators.ADD_RELATIVE)
protected void SetTargetValueFloatDefault (int mat_id, int param_idx)
protected void SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator=PPOperators.SET)
protected void SetTargetValueIntDefault (int mat_id, int param_idx)
void Start (Param par=null)
void Stop (Param par=null)
Private Attributes
protected int m_IDX
protected bool m_IsRunning
protected ref map< int, ref map< int, ref PPERequestParamDataBase > > m_RequestDataStructure
protected bool m_Valid = false
protected bool m_ValuesSent
Detailed Description
Definition at line 2 of file pperequestplatformsbase.c.
Constructor & Destructor Documentation
PPERequesterBase()
void PPERequesterBase::PPERequesterBase (int requester_IDX) inline private
Definition at line 12 of file pperequestplatformsbase.c.
    {
        m_Valid = PPERequesterBank.VerifyRequester(this);
        m_IDX = requester_IDX;
        m_ValuesSent = true;
        m_IsRunning = false;
        m_RequestDataStructure = new map<int,ref map<int,ref PPERequestParamDataBase>>;
    }
References m_IDX, m_IsRunning, m_RequestDataStructure, m_Valid, and m_ValuesSent.
Member Function Documentation
ClearRequesterData()
protected void PPERequesterBase::ClearRequesterData () inline private
Definition at line 324 of file pperequestplatformsbase.c.
    {
        m_RequestDataStructure.Clear();
    }
References m_RequestDataStructure.
DbgPrnt()
void PPERequesterBase::DbgPrnt (string text) inline private
Definition at line 424 of file pperequestplatformsbase.c.
    {
        //Debug.Log(""+text);
    }
GetActiveRequestStructure()
map< int, ref map< int, ref PPERequestParamDataBase > > PPERequesterBase::GetActiveRequestStructure () inline private
Definition at line 319 of file pperequestplatformsbase.c.
    {
        return m_RequestDataStructure;
    }
References m_RequestDataStructure.
Referenced by RemoveActiveRequestFromMaterials().
GetCategoryMask() [1/2]
int PPERequesterBase::GetCategoryMask () inline private
mask for mass-handling methods like 'StopAllEffects'
Definition at line 71 of file pperequestplatformsbase.c.
    {
        return PPERequesterCategory.NONE;
    }
GetCategoryMask() [2/2]
override int PPERequesterBase::GetCategoryMask () inline private
Definition at line 444 of file pperequestplatformsbase.c.
    {
        return PPERequesterCategory.MENU_EFFECTS;
    }
GetRequestData()
PPERequestParamDataBase PPERequesterBase::GetRequestData (int mat_id, int param_idx, int type) inline private
returns request data for specific parameter, or creates one if one does not exist in this request yet (singletons)
Definition at line 261 of file pperequestplatformsbase.c.
    {
        PPERequestParamDataBase data;
        if ( m_RequestDataStructure.Get(mat_id) )
        {
            if (m_RequestDataStructure.Get(mat_id).Get(param_idx))
            {
                data = m_RequestDataStructure.Get(mat_id).Get(param_idx);
            }
            else
            {
                data = PrepareData(mat_id,param_idx,type);
                m_RequestDataStructure.Get(mat_id).Set(param_idx,data);
            }
        }
        else
        {
            data = PrepareData(mat_id,param_idx,type);
            map<int,ref PPERequestParamDataBase> temp_map = new map<int,ref PPERequestParamDataBase>;
            temp_map.Set(param_idx,data);
            m_RequestDataStructure.Set(mat_id, temp_map);
        }
        if (!data)
        {
            Error("GetRequestData | no data found in the structure");
        }
        data.m_Requester = this;
        return data;
    }
References Error(), m_RequestDataStructure, PPERequestParamDataBase::m_Requester, and PrepareData().
Referenced by SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), and SetTargetValueIntDefault().
GetRequesterIDX()
int PPERequesterBase::GetRequesterIDX () inline private
Returns requester index.
Definition at line 65 of file pperequestplatformsbase.c.
    {
        return m_IDX;
    }
References m_IDX.
Referenced by EffectArea::GetRequesterIndex(), and RemoveActiveRequestFromMaterials().
IsRequesterRunning()
bool PPERequesterBase::IsRequesterRunning () inline private
Definition at line 53 of file pperequestplatformsbase.c.
    {
        return m_IsRunning;
    }
References m_IsRunning.
OnStart()
protected void PPERequesterBase::OnStart (Param par = null) inline private
Definition at line 354 of file pperequestplatformsbase.c.
    {
        SetRequesterUpdating(true);
    }
References SetRequesterUpdating().
Referenced by Start().
OnStop()
protected void PPERequesterBase::OnStop (Param par = null) inline private
automatically resets all material parameters of this requester to defaults
Definition at line 360 of file pperequestplatformsbase.c.
    {
        //DbgPrnt("PPEDebug | " + this + " | OnStop");
        SetRequesterUpdating(true);
        SetDefaultValuesAll();
    }
References SetDefaultValuesAll(), and SetRequesterUpdating().
Referenced by Stop().
OnUpdate()
void PPERequesterBase::OnUpdate (float delta) inline private
Definition at line 336 of file pperequestplatformsbase.c.
    {
        //DbgPrnt("PPEDebug | PPERequesterBase | OnUpdate");
        if ( !m_ValuesSent )
        {
            for (int i = 0; i < m_RequestDataStructure.Count(); i++)
            {
                for (int j = 0; j < m_RequestDataStructure.GetElement(i).Count(); j++)
                {
                    SendCurrentValueData(m_RequestDataStructure.GetElement(i).GetElement(j)); //map<int,ref map<int,PPERequestParamDataBase>> //<material<param,data>>
                }
            }
            m_ValuesSent = true;
        }
        SetRequesterUpdating(false);
    }
References Count, m_RequestDataStructure, m_ValuesSent, SendCurrentValueData(), and SetRequesterUpdating().
Referenced by ProcessRequesterUpdates().
PrepareData()
protected PPERequestParamDataBase PPERequesterBase::PrepareData (int mat_id, int param_idx, int type) inline private
Definition at line 294 of file pperequestplatformsbase.c.
    {
        PPERequestParamDataBase data;
        switch (type)
        {
            case PPEConstants.VAR_TYPE_BOOL:
                data = new PPERequestParamDataBool(m_IDX, mat_id, param_idx);
            break;
            case PPEConstants.VAR_TYPE_INT:
                data = new PPERequestParamDataInt(m_IDX, mat_id, param_idx);
            break;
            case PPEConstants.VAR_TYPE_FLOAT:
                data = new PPERequestParamDataFloat(m_IDX, mat_id, param_idx);
            break;
            case PPEConstants.VAR_TYPE_COLOR:
                data = new PPERequestParamDataColor(m_IDX, mat_id, param_idx);
            break;
        }
        return data;
    }
References m_IDX, PPERequestParamDataBool(), and PPERequestParamDataFloat().
Referenced by GetRequestData().
QueueValuesSend()
protected void PPERequesterBase::QueueValuesSend () inline private
Sets this requester to update in the manager.
Definition at line 253 of file pperequestplatformsbase.c.
    {
        m_ValuesSent = false;
        //m_IsRunning = true;
        SetRequesterUpdating(true);
    }
References m_ValuesSent, and SetRequesterUpdating().
Referenced by SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), and SetTargetValueIntDefault().
RelativizeValue()
protected float PPERequesterBase::RelativizeValue (float value, int var_type, int mat_id, int param_id, bool relative) inline private
converts all values used to relative values (if not relative already)
Definition at line 368 of file pperequestplatformsbase.c.
    {
        float ret = value;
        if (!relative) //if not already relative...
        {
            switch (var_type)
            {
                case PPEConstants.VAR_TYPE_FLOAT:
                    PPETemplateDefFloat p_float = PPETemplateDefFloat.Cast(PPEManagerStatic.GetPPEManager().GetPostProcessDefaultValues(mat_id,param_id));
                    ret = Math.InverseLerp(p_float.param3, p_float.param4, ret);
                    ret = Math.Clamp(ret,0.0,1.0);
                break;
            }
        }
        //Print("RelativizeValue: " + ret);
        return ret;
    }
References Math::Clamp(), PPEManagerStatic::GetPPEManager(), and Math::InverseLerp().
Referenced by SetTargetValueFloat().
SendCurrentValueData()
protected void PPERequesterBase::SendCurrentValueData (PPERequestParamDataBase data) inline private
Definition at line 329 of file pperequestplatformsbase.c.
    {
        PPEManagerStatic.GetPPEManager().SendMaterialValueData(data);
    }
References PPEManagerStatic::GetPPEManager().
Referenced by OnUpdate().
SetDefaultValuesAll()
protected void PPERequesterBase::SetDefaultValuesAll () inline private
Sets all requested values to default, ignoring them in further calculations.
Definition at line 388 of file pperequestplatformsbase.c.
    {
        //<material<param_id,data>>
        PPERequestParamDataBase req_data;
        for (int i = 0; i < m_RequestDataStructure.Count(); i++)
        {
            for (int j = 0; j < m_RequestDataStructure.GetElement(i).Count(); j++)
            {
                req_data = m_RequestDataStructure.GetElement(i).GetElement(j);
                if (!req_data.IsDataActive())
                    continue;
                switch (req_data.GetVarType())
                {
                    case PPEConstants.VAR_TYPE_BOOL:
                        SetTargetValueBoolDefault(req_data.GetMaterialID(),req_data.GetParameterID());
                    break;
                    case PPEConstants.VAR_TYPE_INT:
                        SetTargetValueIntDefault(req_data.GetMaterialID(),req_data.GetParameterID());
                    break;
                    case PPEConstants.VAR_TYPE_FLOAT:
                        SetTargetValueFloatDefault(req_data.GetMaterialID(),req_data.GetParameterID());
                    break;
                    case PPEConstants.VAR_TYPE_COLOR:
                        SetTargetValueColorDefault(req_data.GetMaterialID(),req_data.GetParameterID());
                    break;
                }
            }
        }
    }
References Count, PPERequestParamDataBase::GetMaterialID(), PPERequestParamDataBase::GetParameterID(), PPERequestParamDataBase::GetVarType(), PPERequestParamDataBase::IsDataActive(), m_RequestDataStructure, SetTargetValueBoolDefault(), SetTargetValueColorDefault(), SetTargetValueFloatDefault(), and SetTargetValueIntDefault().
Referenced by OnStop().
SetRequesterIDX()
void PPERequesterBase::SetRequesterIDX (int idx) inline private
automatically assigned by PPERequesterBank
Definition at line 59 of file pperequestplatformsbase.c.
    {
        m_IDX = idx;
    }
References m_IDX.
Referenced by Managed::RegisterRequester().
SetRequesterUpdating()
void PPERequesterBase::SetRequesterUpdating (bool state) inline private
Has to be set for the requester to be handled.
Definition at line 23 of file pperequestplatformsbase.c.
    {
        if (!m_Valid)
        {
            Debug.Log("" + this + " not valid!");
            return;
        }
        PPEManagerStatic.GetPPEManager().SetRequestUpdating(this,state);
        //TODO - separate into its own function?
        if (state)
            PPEManagerStatic.GetPPEManager().SetRequestActive(this,true);
    }
References PPEManagerStatic::GetPPEManager(), Debug::Log(), and m_Valid.
Referenced by OnStart(), OnStop(), OnUpdate(), and QueueValuesSend().
SetTargetValueBool()
protected void PPERequesterBase::SetTargetValueBool (int mat_id, int param_idx, bool val, int priority_layer, int operator = PPOperators.SET) inline private
Definition at line 78 of file pperequestplatformsbase.c.
    {
        if ( !m_RequestDataStructure )
            return;
        PPERequestParamDataBool data = PPERequestParamDataBool.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_BOOL));
        data.SetPriorityLayer(priority_layer);
        data.SetInteractionMask(operator);
        data.m_BoolTarget = val;
        data.m_BoolLast = data.m_BoolCurrent;
        if (data.m_BoolTarget != data.m_BoolCurrent || data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(false);
            data.SetDataActive(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueBool | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataBool(), and QueueValuesSend().
SetTargetValueBoolDefault()
protected void PPERequesterBase::SetTargetValueBoolDefault (int mat_id, int param_idx) inline private
Definition at line 100 of file pperequestplatformsbase.c.
    {
        //TODO - running check and cleanup rework (elsewhere!)
        if ( !m_RequestDataStructure || !m_RequestDataStructure.Get(mat_id) || !m_RequestDataStructure.Get(mat_id).Get(param_idx))
            return;
        PPERequestParamDataBool data = PPERequestParamDataBool.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_BOOL));
        data.m_BoolLast = data.m_BoolCurrent;
        if (!data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueBoolDefault | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataBool(), and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueColor()
protected void PPERequesterBase::SetTargetValueColor (int mat_id, int param_idx, ref array< float > val, int priority_layer, int operator = PPOperators.ADD_RELATIVE) inline private
Definition at line 197 of file pperequestplatformsbase.c.
    {
        if ( !m_RequestDataStructure )
            return;
        PPERequestParamDataColor data = PPERequestParamDataColor.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_COLOR));
        data.SetPriorityLayer(priority_layer);
        data.SetInteractionMask(operator);
        data.m_ColorFormerTarget = data.m_ColorTarget;
        data.m_ColorTarget.Copy(val);
        data.m_ColorLast = data.m_ColorCurrent;
        data.m_ColorStart = data.m_ColorCurrent;
        //if (data.m_ColorTarget != data.m_ColorCurrent)
        {
            data.SetSettingDefaultValues(false);
            data.SetDataActive(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueColor | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
SetTargetValueColorDefault()
protected void PPERequesterBase::SetTargetValueColorDefault (int mat_id, int param_idx) inline private
Definition at line 221 of file pperequestplatformsbase.c.
    {
        //TODO - running check and cleanup rework (elsewhere!)
        if ( !m_RequestDataStructure || !m_RequestDataStructure.Get(mat_id) || !m_RequestDataStructure.Get(mat_id).Get(param_idx))
            return;
        PPERequestParamDataColor data = PPERequestParamDataColor.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_COLOR));
        data.m_ColorFormerTarget = data.m_ColorTarget;
        data.m_ColorLast = data.m_ColorCurrent;
        data.m_ColorStart = data.m_ColorCurrent;
        if (!data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueColorDefault | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueFloat()
protected void PPERequesterBase::SetTargetValueFloat (int mat_id, int param_idx, bool relative, float val, int priority_layer, int operator = PPOperators.ADD_RELATIVE) inline private
Definition at line 155 of file pperequestplatformsbase.c.
    {
        if ( !m_RequestDataStructure )
            return;
        PPERequestParamDataFloat data = PPERequestParamDataFloat.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_FLOAT));
        data.SetPriorityLayer(priority_layer);
        data.SetInteractionMask(operator);
        data.m_FloatFormerTarget = data.m_FloatTarget;
        data.m_FloatTarget = RelativizeValue(val,PPEConstants.VAR_TYPE_FLOAT,mat_id,param_idx,relative);
        data.m_FloatLast = data.m_FloatCurrent;
        data.m_FloatStart = data.m_FloatCurrent;
        if (data.m_FloatTarget != data.m_FloatCurrent || data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(false);
            data.SetDataActive(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueFloat | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataFloat(), QueueValuesSend(), and RelativizeValue().
SetTargetValueFloatDefault()
protected void PPERequesterBase::SetTargetValueFloatDefault (int mat_id, int param_idx) inline private
Definition at line 178 of file pperequestplatformsbase.c.
    {
        //TODO - running check and cleanup rework (elsewhere!)
        if ( !m_RequestDataStructure || !m_RequestDataStructure.Get(mat_id) || !m_RequestDataStructure.Get(mat_id).Get(param_idx))
            return;
        PPERequestParamDataFloat data = PPERequestParamDataFloat.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_FLOAT));
        data.m_FloatFormerTarget = data.m_FloatTarget;
        data.m_FloatLast = data.m_FloatCurrent;
        data.m_FloatStart = data.m_FloatCurrent;
        if (!data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueFloatDefault | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, PPERequestParamDataFloat(), and QueueValuesSend().
Referenced by SetDefaultValuesAll().
SetTargetValueInt()
protected void PPERequesterBase::SetTargetValueInt (int mat_id, int param_idx, bool relative, int val, int priority_layer, int operator = PPOperators.SET) inline private
Definition at line 117 of file pperequestplatformsbase.c.
    {
        if ( !m_RequestDataStructure )
            return;
        PPERequestParamDataInt data = PPERequestParamDataInt.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_INT));
        data.SetPriorityLayer(priority_layer);
        data.SetInteractionMask(operator);
        data.m_IntTarget = val;
        data.m_IntLast = data.m_IntCurrent;
        if (data.m_IntTarget != data.m_IntCurrent || data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(false);
            data.SetDataActive(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueInt | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
SetTargetValueIntDefault()
protected void PPERequesterBase::SetTargetValueIntDefault (int mat_id, int param_idx) inline private
Definition at line 138 of file pperequestplatformsbase.c.
    {
        //TODO - running check and cleanup rework (elsewhere!)
        if ( !m_RequestDataStructure || !m_RequestDataStructure.Get(mat_id) || !m_RequestDataStructure.Get(mat_id).Get(param_idx))
            return;
        PPERequestParamDataInt data = PPERequestParamDataInt.Cast(GetRequestData(mat_id,param_idx,PPEConstants.VAR_TYPE_INT));
        data.m_IntLast = data.m_IntCurrent;
        if (!data.IsSettingDefaultValues())
        {
            data.SetSettingDefaultValues(true);
            QueueValuesSend();
        }
        //DbgPrnt("PPEDebug | PPERequesterBase - SetTargetValueIntDefault | mat/par/req: " + mat_id + "/" + param_idx + "/" + m_IDX + " | data: " + data);
    }
References GetRequestData(), m_RequestDataStructure, and QueueValuesSend().
Referenced by SetDefaultValuesAll().
Start()
void PPERequesterBase::Start (Param par = null) inline private
Definition at line 38 of file pperequestplatformsbase.c.
    {
        OnStart(par);
        m_IsRunning = true;
    }
References m_IsRunning, and OnStart().
Referenced by ManBase::SetContaminatedEffectEx().
Stop()
void PPERequesterBase::Stop (Param par = null) inline private
Definition at line 44 of file pperequestplatformsbase.c.
    {
        if (!m_RequestDataStructure || m_RequestDataStructure.Count() <= 0)
            return;
        OnStop(par);
        m_IsRunning = false;
    }
References m_IsRunning, m_RequestDataStructure, and OnStop().
Member Data Documentation
m_IDX
protected int PPERequesterBase::m_IDX private
Definition at line 6 of file pperequestplatformsbase.c.
Referenced by GetRequesterIDX(), PPERequesterBase(), PrepareData(), and SetRequesterIDX().
m_IsRunning
protected bool PPERequesterBase::m_IsRunning private
Definition at line 4 of file pperequestplatformsbase.c.
Referenced by IsRequesterRunning(), PPERequesterBase(), Start(), and Stop().
m_RequestDataStructure
protected ref map<int,ref map<int,ref PPERequestParamDataBase> > PPERequesterBase::m_RequestDataStructure private
Definition at line 10 of file pperequestplatformsbase.c.
Referenced by ClearRequesterData(), GetActiveRequestStructure(), GetRequestData(), OnUpdate(), PPERequesterBase(), SetDefaultValuesAll(), SetTargetValueBool(), SetTargetValueBoolDefault(), SetTargetValueColor(), SetTargetValueColorDefault(), SetTargetValueFloat(), SetTargetValueFloatDefault(), SetTargetValueInt(), SetTargetValueIntDefault(), and Stop().
m_Valid
protected bool PPERequesterBase::m_Valid = false private
Definition at line 8 of file pperequestplatformsbase.c.
Referenced by PPERequesterBase(), and SetRequesterUpdating().
m_ValuesSent
protected bool PPERequesterBase::m_ValuesSent private
Definition at line 5 of file pperequestplatformsbase.c.
Referenced by OnUpdate(), PPERequesterBase(), and QueueValuesSend().