DayzKode: MorphineMdfr Class Reference
MorphineMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int LIFETIME = 60
Detailed Description
Definition at line 1 of file morphinemdfr.c.
Member Function Documentation
ActivateCondition()
override bool MorphineMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file morphinemdfr.c.
    {
        return false;
    }
DeactivateCondition()
override bool MorphineMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 51 of file morphinemdfr.c.
    {
        float attached_time = GetAttachedTime();
        if( attached_time >= LIFETIME )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and LIFETIME.
GetDebugText()
override string MorphineMdfr::GetDebugText () inline private
Definition at line 25 of file morphinemdfr.c.
    {
        return (LIFETIME - GetAttachedTime()).ToString();
    }
References GetAttachedTime(), LIFETIME, and string::ToString().
Init()
override void MorphineMdfr::Init () inline private
Definition at line 5 of file morphinemdfr.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_MORPHINE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 1;
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void MorphineMdfr::OnActivate (PlayerBase player) inline private
Definition at line 30 of file morphinemdfr.c.
    {
        if (player.GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
        {
            player.m_ShockHandler.SetMultiplier(0.1); //was 0.5 //Switch the shock multiplier NEED A CONST
        }
        //if( player.GetNotifiersManager() ) player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        player.IncreaseHealingsCount();
        m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask | eInjuryOverrides.MORPHINE;
    }
References m_Player.
OnDeactivate()
override void MorphineMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 41 of file morphinemdfr.c.
    {
        if (player.GetBrokenLegs() != eBrokenLegs.NO_BROKEN_LEGS)
            player.m_ShockHandler.SetMultiplier(1); //Reset the shock multiplier when modifier stops
        //if( player.GetNotifiersManager() ) player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        player.DecreaseHealingsCount();
        m_Player.m_InjuryHandler.m_ForceInjuryAnimMask = m_Player.m_InjuryHandler.m_ForceInjuryAnimMask & ~eInjuryOverrides.MORPHINE;
    }
References m_Player.
OnReconnect()
override void MorphineMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 20 of file morphinemdfr.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void MorphineMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 65 of file morphinemdfr.c.
    {
    }
Member Data Documentation
LIFETIME
const int MorphineMdfr::LIFETIME = 60 private
Definition at line 3 of file morphinemdfr.c.
Referenced by DeactivateCondition(), and GetDebugText().