DayzKode: ActionSewSelf Class Reference
ActionSewSelf Class Reference
Private Member Functions
void ActionSewSelf ()
override void ApplyBandage (ItemBase item, PlayerBase player)
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionsewself.c.
Constructor & Destructor Documentation
ActionSewSelf()
void ActionSewSelf::ActionSewSelf () inline private
Definition at line 11 of file actionsewself.c.
    {
        m_CallbackClass = ActionSewSelfCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_STITCHUPSELF;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_MEDIUM;
        m_Text = "#sew_cuts";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ApplyBandage()
override void ActionSewSelf::ApplyBandage (ItemBase item, PlayerBase player) inline private
Definition at line 47 of file actionsewself.c.
    {
        if (player.GetBleedingManagerServer() )
        {
            player.GetBleedingManagerServer().RemoveMostSignificantBleedingSourceEx(item);
        }
        PluginTransmissionAgents m_mta = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
        m_mta.TransmitAgents(item, player, AGT_ITEM_TO_FLESH);
        if (item.HasQuantity())
        {
            item.AddQuantity(-20,true);
        }
        else
        {
            item.Delete();
        }
    }
References AGT_ITEM_TO_FLESH, and GetPlugin().
Referenced by OnFinishProgressServer().
CreateConditionComponents()
override void ActionSewSelf::CreateConditionComponents () inline private
Definition at line 21 of file actionsewself.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionSewSelf::HasTarget () inline private
Definition at line 27 of file actionsewself.c.
    {
        return false;
    }
OnFinishProgressServer()
override void ActionSewSelf::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 37 of file actionsewself.c.
    {
        PlayerBase target = PlayerBase.Cast(action_data.m_Player);
        if(action_data.m_MainItem && target)
        {
            ApplyBandage( action_data.m_MainItem, target );
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References ApplyBandage(), ActionData::m_MainItem, ActionData::m_Player, and m_SpecialtyWeight.