DayzKode: FirearmActionAttachMagazineQuick Class Reference
FirearmActionAttachMagazineQuick Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override ActionData CreateActionData ()
override void CreateConditionComponents ()
void FirearmActionAttachMagazineQuick ()
override GetInputType ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasProgress ()
override bool HasTarget ()
override bool InventoryReservation (ActionData action_data)
override bool Post_SetupAction (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void Start (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 225 of file firearmactionattachmagazine.c.
Constructor & Destructor Documentation
FirearmActionAttachMagazineQuick()
void FirearmActionAttachMagazineQuick::FirearmActionAttachMagazineQuick () inline private
Definition at line 227 of file firearmactionattachmagazine.c.
    {
    }
Member Function Documentation
ActionCondition()
override bool FirearmActionAttachMagazineQuick::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 231 of file firearmactionattachmagazine.c.
    {
        if (!super.ActionCondition( player, target, item ))
            return false;
        HumanCommandWeapons hcw = player.GetCommandModifier_Weapons();
        if (hcw && hcw.GetRunningAction() == WeaponActions.RELOAD)
            return false;
        MagazineStorage mag = MagazineStorage.Cast(player.GetWeaponManager().GetPreparedMagazine());
        if (!mag)
            return false;
        Weapon weapon = Weapon.Cast(item);
        bool isLoadedMag = false;
        for (int i = 0, count = weapon.GetMuzzleCount(); i < count; ++i)
            isLoadedMag |= ( mag == weapon.GetMagazine( i ) );
        return !isLoadedMag;
    }
References HumanCommandWeapons::GetRunningAction().
CreateActionData()
override ActionData FirearmActionAttachMagazineQuick::CreateActionData () inline private
Definition at line 254 of file firearmactionattachmagazine.c.
    {
        AttachMagazineActionData action_data = new AttachMagazineActionData;
        return action_data;
    }
CreateConditionComponents()
override void FirearmActionAttachMagazineQuick::CreateConditionComponents () inline private
Definition at line 443 of file firearmactionattachmagazine.c.
    {
        m_ConditionItem = new CCINonRuined();
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override FirearmActionAttachMagazineQuick::GetInputType () inline private
Definition at line 438 of file firearmactionattachmagazine.c.
    {
        return ContinuousWeaponManipulationActionInput;
    }
HandleReciveData()
override void FirearmActionAttachMagazineQuick::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 289 of file firearmactionattachmagazine.c.
    {
        AttachMagazineActionReciveData recive_data_am = AttachMagazineActionReciveData.Cast(action_recive_data);
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        action_data.m_MainItem = action_recive_data.m_MainItem;
        if (!action_recive_data.m_Target)
        {
            action_data.m_Target = new ActionTarget(NULL, NULL, -1, vector.Zero, 0);
        }
        else
        {
            action_data.m_Target = action_recive_data.m_Target;
        }
        action_data_am.m_ilOldMagazine = recive_data_am.m_ilOldMagazine;
    }
References ActionTarget, AttachMagazineActionReciveData::m_ilOldMagazine, ActionData::m_MainItem, ActionData::m_Target, and vector::Zero.
HasProgress()
override bool FirearmActionAttachMagazineQuick::HasProgress () inline private
Definition at line 433 of file firearmactionattachmagazine.c.
    {
        return false;
    }
HasTarget()
override bool FirearmActionAttachMagazineQuick::HasTarget () inline private
Definition at line 428 of file firearmactionattachmagazine.c.
    {
        return true;
    }
InventoryReservation()
override bool FirearmActionAttachMagazineQuick::InventoryReservation (ActionData action_data) inline private
Definition at line 330 of file firearmactionattachmagazine.c.
    {
        if( (IsLocal() || !UseAcknowledgment()) && IsInstant() )
            return true;
        bool success = true;
        InventoryLocation oldMagTargetInventoryLocation = NULL;
        InventoryLocation targetInventoryLocation = NULL;
        InventoryLocation handInventoryLocation = NULL;
        PlayerBase player = action_data.m_Player;
        AttachMagazineActionData am_action_data = AttachMagazineActionData.Cast(action_data);
        Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
        int muzzle_index = wpn.GetCurrentMuzzle();
        Magazine new_mag = Magazine.Cast(action_data.m_Target.GetObject());
        if (am_action_data.m_oldMagazine)
        {
            oldMagTargetInventoryLocation = new InventoryLocation;
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( am_action_data.m_oldMagazine, am_action_data.m_ilOldMagazine) )
            {
                success = false;
            }
            else
            {
                player.GetInventory().AddInventoryReservationEx(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine,GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if (success)
        {
            targetInventoryLocation = new InventoryLocation;
            targetInventoryLocation.SetAttachment( wpn, new_mag, InventorySlots.MAGAZINE);
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( new_mag, targetInventoryLocation) )
            {
                success = false;
                if (am_action_data.m_oldMagazine)
                {
                    player.GetInventory().ClearInventoryReservation(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine);
                }
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( new_mag, targetInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if (success)
        {
            handInventoryLocation = new InventoryLocation;
            handInventoryLocation.SetHands(action_data.m_Player, wpn);
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( wpn, handInventoryLocation) )
            {
                if (am_action_data.m_oldMagazine)
                {
                    player.GetInventory().ClearInventoryReservation(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine);
                }
                player.GetInventory().ClearInventoryReservation(new_mag, targetInventoryLocation);
                success = false;
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( wpn, handInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if ( success )
        {
            if (am_action_data.m_ilOldMagazine)
                action_data.m_ReservedInventoryLocations.Insert(am_action_data.m_ilOldMagazine);
            if (targetInventoryLocation)
                action_data.m_ReservedInventoryLocations.Insert(targetInventoryLocation);
            if (handInventoryLocation)
                action_data.m_ReservedInventoryLocations.Insert(handInventoryLocation);
        }
        return success;
    }
References IsInstant(), IsLocal(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_ReservedInventoryLocations, ActionData::m_Target, InventoryLocation::SetAttachment(), InventoryLocation::SetHands(), and UseAcknowledgment().
Referenced by Start().
Post_SetupAction()
override bool FirearmActionAttachMagazineQuick::Post_SetupAction (ActionData action_data) inline private
Definition at line 306 of file firearmactionattachmagazine.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
            int muzzle_index = wpn.GetCurrentMuzzle();
            AttachMagazineActionData am_action_data = AttachMagazineActionData.Cast(action_data);
            am_action_data.m_oldMagazine = wpn.GetMagazine(muzzle_index);
            ActionTarget newTarget = new ActionTarget(action_data.m_Player.GetWeaponManager().GetPreparedMagazine(), null, -1, vector.Zero, -1);
            action_data.m_Target = newTarget;
            InventoryLocation new_il = new InventoryLocation;
            if (!action_data.m_Player.GetWeaponManager().PrepareInventoryLocationForMagazineSwap(wpn, Magazine.Cast(action_data.m_Target.GetObject()), new_il))
            {
                return false;
            }
            am_action_data.m_ilOldMagazine = new_il;
        }
        return true;
    }
References ActionTarget, GetGame(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and vector::Zero.
ReadFromContext()
override bool FirearmActionAttachMagazineQuick::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 270 of file firearmactionattachmagazine.c.
    {
        if (!action_recive_data)
        {
            action_recive_data = new AttachMagazineActionReciveData;
        }
        super.ReadFromContext(ctx, action_recive_data);
        InventoryLocation il = new InventoryLocation;
        if (!il.ReadFromContext(ctx))
            return false;
        AttachMagazineActionReciveData recive_data_am = AttachMagazineActionReciveData.Cast(action_recive_data);
        recive_data_am.m_ilOldMagazine = il;
        return true;
    }
References AttachMagazineActionReciveData::m_ilOldMagazine, and InventoryLocation::ReadFromContext().
Start()
override void FirearmActionAttachMagazineQuick::Start (ActionData action_data) inline private
Definition at line 414 of file firearmactionattachmagazine.c.
    {
        super.Start( action_data );
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
        Magazine mag = Magazine.Cast(action_data.m_Target.GetObject());
        ClearInventoryReservationEx(action_data);
        if ( action_data.m_Player.GetWeaponManager().CanAttachMagazine(wpn,mag,false) )
            action_data.m_Player.GetWeaponManager().AttachMagazine(mag, this);
        else
            action_data.m_Player.GetWeaponManager().SwapMagazineEx(mag, action_data_am.m_ilOldMagazine, this);
         InventoryReservation(action_data);
    }
References ClearInventoryReservationEx(), InventoryReservation(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
WriteToContext()
override void FirearmActionAttachMagazineQuick::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 261 of file firearmactionattachmagazine.c.
    {
        super.WriteToContext(ctx, action_data);
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        action_data_am.m_ilOldMagazine.WriteToContext(ctx);
    }