DayzKode: DayZProfilesOptions Class Reference
DayZProfilesOptions Class Reference
Private Member Functions
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap ()
private DayZGame m_Game void RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def=true)
void ResetOptions ()
void SetProfileOption (EDayZProfilesOptions option, bool value)
Private Attributes
private ref map< EDayZProfilesOptions, ref DayZProfilesOption > m_DayZProfilesOptions
Detailed Description
Definition at line 592 of file dayzgame.c.
Member Function Documentation
GetProfileOption()
bool DayZProfilesOptions::GetProfileOption (EDayZProfilesOptions option) inline private
returns saved profile option
Definition at line 641 of file dayzgame.c.
    {
        if ( m_DayZProfilesOptions && m_DayZProfilesOptions.Contains(option) )
        {
            DayZProfilesOption po = m_DayZProfilesOptions.Get(option);
            return po.param2;
        }
        return true;
    }
References m_DayZProfilesOptions.
Referenced by GetProfileOption().
GetProfileOptionDefault()
bool DayZProfilesOptions::GetProfileOptionDefault (EDayZProfilesOptions option) inline private
returns default value
Definition at line 654 of file dayzgame.c.
    {
        if ( m_DayZProfilesOptions && m_DayZProfilesOptions.Contains(option) )
        {
            DayZProfilesOption po = m_DayZProfilesOptions.Get(option);
            return po.param3;
        }
        ErrorEx("Invalid profile option id! Returning 'true'.",ErrorExSeverity.WARNING);
        return true;
    }
References ErrorEx, and m_DayZProfilesOptions.
Referenced by GetProfileOptionDefault().
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOption > DayZProfilesOptions::GetProfileOptionMap () inline private
returns whole options map
Definition at line 668 of file dayzgame.c.
    {
        if ( m_DayZProfilesOptions )
        {
            return m_DayZProfilesOptions;
        }
        return NULL;
    }
References m_DayZProfilesOptions.
Referenced by GetProfileOptionMap().
RegisterProfileOption()
private DayZGame m_Game void DayZProfilesOptions::RegisterProfileOption (EDayZProfilesOptions option, string profileOptionName, bool def = true) inline private
init of DayZProfilesOption - profileOptionName, value from Profiles files, or use default value
Definition at line 597 of file dayzgame.c.
    {
        if ( !m_DayZProfilesOptions )
        {
            m_DayZProfilesOptions = new map<EDayZProfilesOptions, ref DayZProfilesOption>;
        }
        if ( !m_DayZProfilesOptions.Contains(option) )
        {
            bool profileVal = GetGame().GetProfileValueBool(profileOptionName, def);
            m_DayZProfilesOptions.Set(option, new DayZProfilesOption(profileOptionName, profileVal, def));
            SetProfileOption(option, profileVal);
        }
    }
References GetGame(), m_DayZProfilesOptions, and SetProfileOption().
Referenced by RegisterProfilesOptions().
ResetOptions()
void DayZProfilesOptions::ResetOptions () inline private
Definition at line 614 of file dayzgame.c.
    {
        if ( !m_DayZProfilesOptions )
        {
            m_DayZProfilesOptions = new map<EDayZProfilesOptions, ref DayZProfilesOption>;
        }
        foreach ( EDayZProfilesOptions e_opt, DayZProfilesOption r_opt : m_DayZProfilesOptions )
        {
            bool profileVal = GetGame().GetProfileValueBool(r_opt.param1, r_opt.param3);
            SetProfileOption(e_opt, profileVal);
        }
    }
References GetGame(), m_DayZProfilesOptions, and SetProfileOption().
Referenced by ResetProfileOptions().
SetProfileOption()
void DayZProfilesOptions::SetProfileOption (EDayZProfilesOptions option, bool value) inline private
saves value to mem and to config
Definition at line 627 of file dayzgame.c.
    {
        //Print("SetProfileOption");
        if ( m_DayZProfilesOptions && m_DayZProfilesOptions.Contains(option) )
        {
            DayZProfilesOption po = m_DayZProfilesOptions.Get(option);
            po.param2 = value;
            GetGame().SetProfileValueBool(po.param1, value);
            GetGame().SaveProfile();
        }
    }
References GetGame(), m_DayZProfilesOptions, and CGame::SaveProfile().
Referenced by RegisterProfileOption(), ResetOptions(), and SetProfileOption().
Member Data Documentation
m_DayZProfilesOptions
private ref map<EDayZProfilesOptions, ref DayZProfilesOption> DayZProfilesOptions::m_DayZProfilesOptions private
Definition at line 594 of file dayzgame.c.
Referenced by GetProfileOption(), GetProfileOptionDefault(), GetProfileOptionMap(), RegisterProfileOption(), ResetOptions(), and SetProfileOption().