DayzKode: Container_Base Class Reference
Container_Base Class Reference
Private Member Functions
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override void Close ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
void GiftBox_Base ()
override bool IsContainer ()
override bool IsContainer ()
override bool IsOpen ()
override void OnDebugSpawn ()
override void Open ()
override void SetActions ()
Private Attributes
protected ref OpenableBehaviour m_Openable
Detailed Description
Definition at line 1 of file en5c_bear_colorbase.c.
Member Function Documentation
CanPutInCargo() [1/2]
override bool Container_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 8 of file en5c_bear_colorbase.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        //better use something like super.GetName()
        if ( parent && (parent.IsKindOf("Bear_ColorBase")) )
        {
            return false;
        }
        return true;
    }
CanPutInCargo() [2/2]
override bool Container_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 8 of file en5c_waterproofbag_colorbase.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        if ( parent && (parent.IsKindOf("WaterproofBag_ColorBase")) )
        {
            return false;
        }
        return true;
    }
CanReceiveItemIntoCargo()
override bool Container_Base::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 11 of file giftbox_base.c.
    {
        if( !super.CanReceiveItemIntoCargo(item) ) {return false;}
        if (GameInventory.GetInventoryCheckContext() == InventoryCheckContext.DEFAULT )
        {
            if(!GetGame().IsDedicatedServer())
                return IsOpen();
        }
        return true;
    }
References GetGame(), and IsOpen().
Close()
override void Container_Base::Close () inline private
Definition at line 31 of file giftbox_base.c.
    {
        m_Openable.Close();
        SetSynchDirty();
    }
EEHealthLevelChanged()
override void Container_Base::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 57 of file giftbox_base.c.
    {
        //Print("EEHealthLevelChanged");
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        if ( newLevel == GameConstants.STATE_RUINED && GetGame().IsServer() )
        {
            MiscGameplayFunctions.ThrowAllItemsInInventory(this, 0);
            DeleteSafe();
        }
        //m_DamageSystemStarted = true;
    }
References GetGame(), and GameConstants::STATE_RUINED.
GiftBox_Base()
void Container_Base::GiftBox_Base () inline private
Definition at line 3 of file giftbox_base.c.
    {
        m_Openable = new OpenableBehaviour(false);
        RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
    }
IsContainer() [1/2]
override bool Container_Base::IsContainer () inline private
Definition at line 3 of file en5c_bear_colorbase.c.
    {
        return true;
    }
IsContainer() [2/2]
override bool Container_Base::IsContainer () inline private
Definition at line 3 of file en5c_waterproofbag_colorbase.c.
    {
        return true;
    }
IsOpen()
override bool Container_Base::IsOpen () inline private
Definition at line 37 of file giftbox_base.c.
    {
        return m_Openable.IsOpened();
    }
Referenced by CanReceiveItemIntoCargo().
OnDebugSpawn()
override void Container_Base::OnDebugSpawn () inline private
Definition at line 48 of file giftbox_base.c.
    {
        EntityAI entity;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Chemlight_Green" );
        }
    }
References Class::CastTo().
Open()
override void Container_Base::Open () inline private
Definition at line 25 of file giftbox_base.c.
    {
        m_Openable.Open();
        SetSynchDirty();
    }
SetActions()
override void Container_Base::SetActions () inline private
Definition at line 42 of file giftbox_base.c.
    {
        super.SetActions();
        AddAction(ActionUnpackGift);
    }
References AddAction().
Member Data Documentation
m_Openable
protected ref OpenableBehaviour Container_Base::m_Openable private
Definition at line 9 of file giftbox_base.c.