DayzKode: MapMarker Class Reference
MapMarker Class Reference
Private Member Functions
int GetMarkerColor ()
int GetMarkerIcon ()
vector GetMarkerPos ()
string GetMarkerText ()
void MapMarker (vector pos, string text, int color, int idx)
Private Attributes
protected int m_Color
protected int m_IconIdx
protected vector m_Position
protected string m_Text
Detailed Description
Definition at line 1124 of file inventoryitem.c.
Constructor & Destructor Documentation
MapMarker()
void MapMarker::MapMarker (vector pos, string text, int color, int idx) inline private
Definition at line 1131 of file inventoryitem.c.
    {
        m_Position = pos;
        m_Text = text;
        m_Color = color;
        m_IconIdx = idx;
    }
References m_Color, m_IconIdx, m_Position, and m_Text.
Member Function Documentation
GetMarkerColor()
int MapMarker::GetMarkerColor () inline private
Definition at line 1149 of file inventoryitem.c.
    {
        return m_Color;
    }
References m_Color.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerIcon()
int MapMarker::GetMarkerIcon () inline private
Definition at line 1154 of file inventoryitem.c.
    {
        return m_IconIdx;
    }
References m_IconIdx.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerPos()
vector MapMarker::GetMarkerPos () inline private
Definition at line 1139 of file inventoryitem.c.
    {
        return m_Position;
    }
References m_Position.
Referenced by UIScriptedMenu::LoadMapMarkers().
GetMarkerText()
string MapMarker::GetMarkerText () inline private
Definition at line 1144 of file inventoryitem.c.
    {
        return m_Text;
    }
References m_Text.
Referenced by UIScriptedMenu::LoadMapMarkers().
Member Data Documentation
m_Color
protected int MapMarker::m_Color private
Definition at line 1127 of file inventoryitem.c.
Referenced by GetMarkerColor(), and MapMarker().
m_IconIdx
protected int MapMarker::m_IconIdx private
Definition at line 1128 of file inventoryitem.c.
Referenced by GetMarkerIcon(), and MapMarker().
m_Position
protected vector MapMarker::m_Position private
Definition at line 1126 of file inventoryitem.c.
Referenced by GetMarkerPos(), and MapMarker().
m_Text
protected string MapMarker::m_Text private
Definition at line 1129 of file inventoryitem.c.
Referenced by GetMarkerText(), and MapMarker().