DayzKode: ActionAnimateCarSelection Class Reference
ActionAnimateCarSelection Class Reference
Private Member Functions
void ActionAnimateCarSelection ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
string m_AnimSource = ""
Detailed Description
Definition at line 1 of file actionanimatecarselection.c.
Constructor & Destructor Documentation
ActionAnimateCarSelection()
void ActionAnimateCarSelection::ActionAnimateCarSelection () inline private
Definition at line 5 of file actionanimatecarselection.c.
    {
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_ALL;
        m_Text = "#manipulate";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAnimateCarSelection::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 18 of file actionanimatecarselection.c.
    {
        if (!target)
        {
            return false;
        }
        if (!IsInReach(player, target, UAMaxDistances.DEFAULT))
        {
            return false;
        }
        Object targetObject = target.GetObject();
        Entity targetEnt = Entity.Cast(targetObject);
        array<string> selections = new array<string>();
        targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections);
        CarScript car;
        if (Class.CastTo(car, targetEnt))
        {
            for (int i = 0; i < selections.Count(); i++)
            {
                m_AnimSource = car.GetAnimSourceFromSelection(selections[i]);
                if (m_AnimSource != "")
                {
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, CarScript::GetAnimSourceFromSelection(), IsInReach(), and m_AnimSource.
CreateConditionComponents()
override void ActionAnimateCarSelection::CreateConditionComponents () inline private
Definition at line 12 of file actionanimatecarselection.c.
    {
        m_ConditionItem     = new CCINone;
        m_ConditionTarget   = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionAnimateCarSelection::OnEndServer (ActionData action_data) inline private
Definition at line 75 of file actionanimatecarselection.c.
    {
        CarScript car;
        if (Class.CastTo(car, action_data.m_Target.GetObject()))
        {
            car.ForceUpdateLightsEnd();
        }
    }
References Class::CastTo(), and ActionData::m_Target.
OnStartServer()
override void ActionAnimateCarSelection::OnStartServer (ActionData action_data) inline private
Definition at line 52 of file actionanimatecarselection.c.
    {
        Entity targetEnt;
        if (Class.CastTo(targetEnt, action_data.m_Target.GetObject()))
        {
            if (targetEnt.GetAnimationPhase(m_AnimSource) > 0.5)
            {
                targetEnt.SetAnimationPhase(m_AnimSource, 0.0);
            }
            if (targetEnt.GetAnimationPhase(m_AnimSource) <= 0.5)
            {
                targetEnt.SetAnimationPhase(m_AnimSource, 1.0);
            }
        }
        CarScript car;
        if (Class.CastTo(car, action_data.m_Target.GetObject()))
        {
            car.ForceUpdateLightsStart();
        }
    }
References Class::CastTo(), m_AnimSource, and ActionData::m_Target.
Member Data Documentation
m_AnimSource
string ActionAnimateCarSelection::m_AnimSource = "" private
Definition at line 3 of file actionanimatecarselection.c.
Referenced by ActionCondition(), ActionAnimateSeats::ActionCondition(), and OnStartServer().