DayzKode: ActionDigInStash Class Reference
ActionDigInStash Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDigInStash ()
override void CreateConditionComponents ()
override string GetAdminLogMessage (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
void SpawnParticleShovelRaise (ActionData action_data)
Static Private Attributes
static float m_DigStashSlopeTolerance = 0.6
Detailed Description
Definition at line 9 of file actiondiginstash.c.
Constructor & Destructor Documentation
ActionDigInStash()
void ActionDigInStash::ActionDigInStash () inline private
Definition at line 13 of file actiondiginstash.c.
    {
        m_CallbackClass     = ActionDigInStashCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight   = UASoftSkillsWeight.ROUGH_LOW;
        m_Text              = "#bury";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionDigInStash::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
was initialized from inventory?
Check slope angle
Definition at line 29 of file actiondiginstash.c.
    {
        ItemBase targetIB;
        if (Class.CastTo(targetIB, target.GetObject()) && targetIB.CanBeDigged())
        {
            if (player.IsPlacingLocal())
            {
                return false;
            }
            if (targetIB.IsRuined() || targetIB.GetInventory().IsAttachment())
            {
                return false;
            }
            if (targetIB.GetInventory().IsAttachment())
            {
                return false;
            }
            if (targetIB.IsInherited(UndergroundStash))
            {
                return false;
            }
            EntityAI entityToCheck = targetIB;
            if (targetIB.GetInventory().IsInCargo());
                entityToCheck = player;
            // here we check if a stash is nearby and block digging a new one in close proximity
            array<Object> excludedObjects = new array<Object>;
            excludedObjects.Insert(targetIB);
            array<Object> nearbyObjects = new array<Object>;
            // For now we exclude an area of 2 X 2 X 2 meters
            if (GetGame().IsBoxColliding(entityToCheck.GetPosition(), entityToCheck.GetOrientation(), "2 2 2", excludedObjects, nearbyObjects))
            {
                for (int i = 0; i < nearbyObjects.Count(); i++)
                {
                    if (nearbyObjects[i].IsInherited(UndergroundStash))
                    {
                        return false;
                    }
                }
            }
            // Check surface
            int liquidType;
            string surfaceType;
            GetGame().SurfaceUnderObject(entityToCheck, surfaceType, liquidType);
            if (!GetGame().IsSurfaceDigable(surfaceType))
            {
                return false;
            }
            else
            {
                vector position = entityToCheck.GetPosition();
                array<vector> positions = new array<vector>;
                positions.Insert(position + "0.5 0 0.5");
                positions.Insert(position + "-0.5 0 0.5");
                positions.Insert(position + "0.5 0 -0.5");
                positions.Insert(position + "-0.5 0 -0.5");
                float difference = GetGame().GetHighestSurfaceYDifference(positions);
                return difference < m_DigStashSlopeTolerance;
            }
        }
        return false;
    }
References Class::CastTo(), GetGame(), CGame::GetHighestSurfaceYDifference(), m_DigStashSlopeTolerance, and CGame::SurfaceUnderObject().
CreateConditionComponents()
override void ActionDigInStash::CreateConditionComponents () inline private
Definition at line 23 of file actiondiginstash.c.
    {
        m_ConditionTarget   = new CCTObject(UAMaxDistances.DEFAULT);
        m_ConditionItem     = new CCINonRuined();
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionDigInStash::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 165 of file actiondiginstash.c.
    {
        return string.Format("Player %1 Dug in %2 at position %3", action_data.m_Player, action_data.m_Target.GetObject(), action_data.m_Target.GetObject().GetPosition());
    }
References string::Format(), ActionData::m_Player, and ActionData::m_Target.
OnExecuteClient()
override void ActionDigInStash::OnExecuteClient (ActionData action_data) inline private
Definition at line 104 of file actiondiginstash.c.
    {
        super.OnExecuteClient(action_data);
        SpawnParticleShovelRaise(action_data);
    }
References SpawnParticleShovelRaise().
OnExecuteServer()
override void ActionDigInStash::OnExecuteServer (ActionData action_data) inline private
Definition at line 111 of file actiondiginstash.c.
    {
        super.OnExecuteServer(action_data);
        if (!GetGame().IsMultiplayer())
        {
            SpawnParticleShovelRaise(action_data);
        }
    }
References GetGame(), and SpawnParticleShovelRaise().
OnFinishProgressServer()
override void ActionDigInStash::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 126 of file actiondiginstash.c.
    {
        EntityAI targetEntity = EntityAI.Cast(action_data.m_Target.GetObject());
        if (!targetEntity)
        {
            ErrorEx("Cannot get entity=" + targetEntity);
            return;
        }
        InventoryLocation targetIL = new InventoryLocation();
        if (!targetEntity.GetInventory().GetCurrentInventoryLocation(targetIL))
        {
            ErrorEx("Cannot get inventory location of entity=" + targetEntity);
            return;
        }
        UndergroundStash stash = UndergroundStash.Cast(GetGame().CreateObjectEx("UndergroundStash", targetEntity.GetPosition(), ECE_PLACE_ON_SURFACE));
        if (stash)
        {
            stash.PlaceOnGround();
            if (GameInventory.LocationCanRemoveEntity(targetIL))
            {
                action_data.m_Player.ServerTakeEntityToTargetCargo(stash, targetEntity);
            }
            else
            {
                Debug.Log(string.Format("Cannot remove entity=%1 obj from current location=%2", targetEntity, InventoryLocation.DumpToStringNullSafe(targetIL)));
            }
        }
        else
        {
            ErrorEx("Stash not spawned!");
        }
        //Apply tool damage
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 10);
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
    }
References InventoryLocation::DumpToStringNullSafe(), ECE_PLACE_ON_SURFACE, ErrorEx, GetGame(), Debug::Log(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
SpawnParticleShovelRaise()
void ActionDigInStash::SpawnParticleShovelRaise (ActionData action_data) inline private
Definition at line 121 of file actiondiginstash.c.
    {
        ParticleManager.GetInstance().PlayOnObject(ParticleList.DIGGING_STASH, action_data.m_Player);
    }
References ParticleList::DIGGING_STASH, ActionData::m_Player, and ParticleManager().
Referenced by OnExecuteClient(), and OnExecuteServer().
Member Data Documentation
m_DigStashSlopeTolerance
float ActionDigInStash::m_DigStashSlopeTolerance = 0.6 static private
Definition at line 11 of file actiondiginstash.c.
Referenced by ActionCondition().