DayzKode: DisinfectionMdfr Class Reference
DisinfectionMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override string GetDebugTextSimple ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int LIFETIME = 100
PluginTransmissionAgents m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents))
float m_WoundAgentInvasibility
Detailed Description
Definition at line 1 of file disinfectmdfr.c.
Member Function Documentation
ActivateCondition()
override bool DisinfectionMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 18 of file disinfectmdfr.c.
    {
        return false;
    }
DeactivateCondition()
override bool DisinfectionMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 56 of file disinfectmdfr.c.
    {
        float attached_time = GetAttachedTime();
        if ( attached_time >= LIFETIME )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and LIFETIME.
GetDebugText()
override string DisinfectionMdfr::GetDebugText () inline private
Definition at line 28 of file disinfectmdfr.c.
    {
        return ( LIFETIME - GetAttachedTime() ).ToString();
    }
References GetAttachedTime(), LIFETIME, and string::ToString().
GetDebugTextSimple()
override string DisinfectionMdfr::GetDebugTextSimple () inline private
Definition at line 33 of file disinfectmdfr.c.
    {
        return ( LIFETIME - GetAttachedTime() ).ToString();
    }
References GetAttachedTime(), LIFETIME, and string::ToString().
Init()
override void DisinfectionMdfr::Init () inline private
Definition at line 7 of file disinfectmdfr.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_DISINFECTION;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        //m_WoundAgentInvasibility = m_PluginTransmissionAgents.GetAgentInvasibility(eAgents.WOUND_AGENT);
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void DisinfectionMdfr::OnActivate (PlayerBase player) inline private
Definition at line 39 of file disinfectmdfr.c.
    {
        player.IncreaseHealingsCount();
    }
OnDeactivate()
override void DisinfectionMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 45 of file disinfectmdfr.c.
    {
        player.DecreaseHealingsCount();
        if(player.GetModifiersManager().IsModifierActive(eModifiers.MDF_WOUND_INFECTION1))
        {
            player.m_AgentPool.AddAgent(eAgents.WOUND_AGENT, -10000);
        }
    }
OnReconnect()
override void DisinfectionMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 23 of file disinfectmdfr.c.
    {
        OnActivate( player );
    }
References OnActivate().
OnTick()
override void DisinfectionMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 70 of file disinfectmdfr.c.
    {
        if(player.GetModifiersManager().IsModifierActive(eModifiers.MDF_WOUND_INFECTION2))
        {
            player.m_AgentPool.AddAgent(eAgents.WOUND_AGENT, -m_PluginTransmissionAgents.GetAgentInvasibility(eAgents.WOUND_AGENT) * deltaT);
        }
        else
        {
            player.m_AgentPool.AddAgent(eAgents.WOUND_AGENT, -m_PluginTransmissionAgents.GetAgentInvasibility(eAgents.WOUND_AGENT) * 2 * deltaT);
        }
    }
References m_PluginTransmissionAgents.
Member Data Documentation
LIFETIME
const int DisinfectionMdfr::LIFETIME = 100 private
Definition at line 3 of file disinfectmdfr.c.
Referenced by DeactivateCondition(), GetDebugText(), and GetDebugTextSimple().
m_PluginTransmissionAgents
PluginTransmissionAgents DisinfectionMdfr::m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents)) private
Definition at line 5 of file disinfectmdfr.c.
Referenced by OnTick().
m_WoundAgentInvasibility
float DisinfectionMdfr::m_WoundAgentInvasibility private
Definition at line 6 of file disinfectmdfr.c.