DayzKode: ActionWaterPlant Class Reference
ActionWaterPlant Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionWaterPlant ()
override void CreateConditionComponents ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 11 of file actionwaterplant.c.
Constructor & Destructor Documentation
ActionWaterPlant()
void ActionWaterPlant::ActionWaterPlant () inline private
Definition at line 13 of file actionwaterplant.c.
    {
        m_CallbackClass = ActionWaterPlantCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL;
        m_FullBody = true;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#water_plant";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionWaterPlant::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 28 of file actionwaterplant.c.
    {
        Object targetObject = target.GetObject();
        if ( targetObject != NULL && targetObject.IsInherited(PlantBase) && item != NULL && !item.IsDamageDestroyed() )
        {
            PlantBase plant = PlantBase.Cast( targetObject );
            if ( plant.NeedsWater() && item.GetQuantity() > 0 )
            {
                return true;
            }
        }
        return false;
    }
CreateConditionComponents()
override void ActionWaterPlant::CreateConditionComponents () inline private
Definition at line 22 of file actionwaterplant.c.
    {
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINotRuinedAndEmpty;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressClient()
override void ActionWaterPlant::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 61 of file actionwaterplant.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        if ( targetObject != NULL && targetObject.IsInherited(PlantBase) )
        {
            PlantBase plant = PlantBase.Cast( targetObject );
            Param1<float> nacdata = Param1<float>.Cast( action_data.m_ActionComponent.GetACData() );
            float water = nacdata.param1;
            Slot slot = plant.GetSlot();
            water = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( water, this.GetSpecialtyWeight() );
            slot.GiveWater( water );
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References CABase::GetACData(), GetSpecialtyWeight(), ActionData::m_ActionComponent, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
OnFinishProgressServer()
override void ActionWaterPlant::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 45 of file actionwaterplant.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        if ( targetObject != NULL && targetObject.IsInherited(PlantBase) )
        {
            PlantBase plant = PlantBase.Cast( targetObject );
            Param1<float> nacdata = Param1<float>.Cast( action_data.m_ActionComponent.GetACData() );
            float water = nacdata.param1;
            Slot slot = plant.GetSlot();
            water = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( water, this.GetSpecialtyWeight() );
            slot.GiveWater( water );
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References CABase::GetACData(), GetSpecialtyWeight(), ActionData::m_ActionComponent, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.