DayzKode: DayZPlayerSyncJunctures Class Reference
DayZPlayerSyncJunctures Class Reference
Static Private Member Functions
static bool ReadActionInterruptParams (ParamsReadContext pCtx)
static bool ReadBrokenLegsParams (ParamsReadContext pCtx, out bool canPlaySound, out eBrokenLegs currentState, out eBrokenLegs localState)
static bool ReadBrokenLegsParamsEx (ParamsReadContext pCtx, out int currentState)
static bool ReadDamageHitParams (ParamsReadContext pCtx, out int pType, out float pHitDir, out bool pFullbody)
static bool ReadDamageHitParamsEx (ParamsReadContext pCtx, out SyncHitInfo pData)
static bool ReadDeathParams (ParamsReadContext pCtx, out int pType, out float pHitDir)
static bool ReadInjuryParams (ParamsReadContext pCtx, out bool pEnable, out eInjuryHandlerLevels level)
static bool ReadKuruRequest (ParamsReadContext pCtx, out float amount)
static bool ReadPlayerFBModifier (ParamsReadContext pCtx, out int type)
static bool ReadPlayerSymptomADDParams (ParamsReadContext pCtx, out int type)
static bool ReadPlayerSymptomFBParams (ParamsReadContext pCtx, out DayZPlayerConstants anim_id, out int stance_mask, out float duration)
static bool ReadPlayerUnconsciousnessParams (ParamsReadContext pCtx, out bool enable)
static bool ReadShockParams (ParamsReadContext pCtx, out float shockValue)
static void SendActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept)
static void SendActionInterrupt (DayZPlayer pPlayer)
static void SendBrokenLegs (DayZPlayer pPlayer, bool canPlaySound, eBrokenLegs currentState, eBrokenLegs localState)
static void SendBrokenLegsEx (DayZPlayer pPlayer, int currentState)
static void SendDamageHit (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody)
static void SendDamageHitEx (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody, TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos)
static void SendDeath (DayZPlayer pPlayer, int pType, float pHitDir)
static void SendDeleteItem (DayZPlayer pPlayer, EntityAI item)
static void SendInjury (DayZPlayer pPlayer, bool pEnable, eInjuryHandlerLevels level)
static void SendKuruRequest (DayZPlayer pPlayer, float amount)
static void SendPlayerFBModifier (PlayerBase pPlayer, int type)
static void SendPlayerSymptomADD (DayZPlayer pPlayer, int type, int state_type)
static void SendPlayerSymptomFB (DayZPlayer pPlayer, DayZPlayerConstants anim_id, int state_type, int stance_mask, float duration)
static void SendPlayerUnconsciousness (DayZPlayer pPlayer, bool enable)
static void SendQuickbarSetShortcut (DayZPlayer pPlayer, EntityAI item, int index, bool force=false)
static void SendShock (DayZPlayer pPlayer, float shockValue)
static void SendWeaponActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept)
static void SendWeaponJamChance (DayZPlayer pPlayer, float jamChance)
Static Private Attributes
static const int SJ_ACTION_ACK_ACCEPT = 6
static const int SJ_ACTION_ACK_REJECT = 7
static const int SJ_ACTION_INTERRUPT = 2
static const int SJ_ADS_RESET = 25
static const int SJ_BROKEN_LEGS = 21
static const int SJ_DAMAGE_HIT = 0
static const int SJ_DEATH = 12
static const int SJ_DELETE_ITEM = 20
static const int SJ_GESTURE_REQUEST = 16
static const int SJ_INJURY = 1
static const int SJ_INVENTORY = 5
static const int SJ_INVENTORY_REPAIR = 17
static const int SJ_KURU_REQUEST = 15
static const int SJ_PLAYER_ADD_MODIFIER = 14
static const int SJ_PLAYER_FB_MODIFIER = 13
static const int SJ_PLAYER_STATES = 3
static const int SJ_QUICKBAR_SET_SHORTCUT = 4
static const int SJ_SHOCK = 22
static const int SJ_STAMINA = 23
static const int SJ_STAMINA_MISC = 24
static const int SJ_UNCONSCIOUSNESS = 11
static const int SJ_WEAPON_ACTION_ACK_ACCEPT = 8
static const int SJ_WEAPON_ACTION_ACK_REJECT = 9
static const int SJ_WEAPON_LIFT = 18
static const int SJ_WEAPON_RAISE_COMPLETED = 19
static const int SJ_WEAPON_SET_JAMMING_CHANCE = 10
Detailed Description
Definition at line 4 of file dayzplayersyncjunctures.c.
Member Function Documentation
ReadActionInterruptParams()
static bool DayZPlayerSyncJunctures::ReadActionInterruptParams (ParamsReadContext pCtx) inline static private
Definition at line 244 of file dayzplayersyncjunctures.c.
    {
        return true;
    }
ReadBrokenLegsParams()
static bool DayZPlayerSyncJunctures::ReadBrokenLegsParams (ParamsReadContext pCtx, out bool canPlaySound, out eBrokenLegs currentState, out eBrokenLegs localState) inline static private
Definition at line 353 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(canPlaySound) )
            return false; // error
        if ( !pCtx.Read(currentState) )
            return false; // error
        if ( !pCtx.Read(localState) )
            return false;
        return true;
    }
References Serializer::Read().
ReadBrokenLegsParamsEx()
static bool DayZPlayerSyncJunctures::ReadBrokenLegsParamsEx (ParamsReadContext pCtx, out int currentState) inline static private
Definition at line 373 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(currentState) )
            return false;
        return true;
    }
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadDamageHitParams()
static bool DayZPlayerSyncJunctures::ReadDamageHitParams (ParamsReadContext pCtx, out int pType, out float pHitDir, out bool pFullbody) inline static private
Definition at line 94 of file dayzplayersyncjunctures.c.
    {
        if (!pCtx.Read(pType))
            return false;
        if (!pCtx.Read(pHitDir))
            return false;
        if (!pCtx.Read(pFullbody))
            return false;
        return true;
    }
References Serializer::Read().
ReadDamageHitParamsEx()
static bool DayZPlayerSyncJunctures::ReadDamageHitParamsEx (ParamsReadContext pCtx, out SyncHitInfo pData) inline static private
Definition at line 105 of file dayzplayersyncjunctures.c.
    {
        if (!pCtx.Read(pData))
            return false;
        return true;
    }
References Serializer::Read().
Referenced by OnSyncJuncture().
ReadDeathParams()
static bool DayZPlayerSyncJunctures::ReadDeathParams (ParamsReadContext pCtx, out int pType, out float pHitDir) inline static private
Definition at line 47 of file dayzplayersyncjunctures.c.
    {
        if (!pCtx.Read(pType))
            return false;
        if (!pCtx.Read(pHitDir))
            return false;
        return true;
    }
References Serializer::Read().
Referenced by OnSyncJuncture().
ReadInjuryParams()
static bool DayZPlayerSyncJunctures::ReadInjuryParams (ParamsReadContext pCtx, out bool pEnable, out eInjuryHandlerLevels level) inline static private
Definition at line 126 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(pEnable) )
            return false; // error
        if ( !pCtx.Read(level) )
            return false; // error
        return true;
    }
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadKuruRequest()
static bool DayZPlayerSyncJunctures::ReadKuruRequest (ParamsReadContext pCtx, out float amount) inline static private
Kuru Disease Shake
Definition at line 279 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(amount) )
            return false; // error
        return true;
    }
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadPlayerFBModifier()
static bool DayZPlayerSyncJunctures::ReadPlayerFBModifier (ParamsReadContext pCtx, out int type) inline static private
Definition at line 172 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(type) )
            return false; // error
        return true;
    }
References Serializer::Read().
ReadPlayerSymptomADDParams()
static bool DayZPlayerSyncJunctures::ReadPlayerSymptomADDParams (ParamsReadContext pCtx, out int type) inline static private
Definition at line 194 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(type) )
            return false; // error
        return true;
    }
References Serializer::Read().
ReadPlayerSymptomFBParams()
static bool DayZPlayerSyncJunctures::ReadPlayerSymptomFBParams (ParamsReadContext pCtx, out DayZPlayerConstants anim_id, out int stance_mask, out float duration) inline static private
Definition at line 219 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(anim_id) )
            return false; // error
        if ( !pCtx.Read(stance_mask) )
            return false; // error
        if ( !pCtx.Read(duration) )
            return false; // error
        //if ( !pCtx.Read(pPlayer) )
            //return false; // error
        return true;
    }
References Serializer::Read().
Referenced by SmptAnimMetaBase::Init().
ReadPlayerUnconsciousnessParams()
static bool DayZPlayerSyncJunctures::ReadPlayerUnconsciousnessParams (ParamsReadContext pCtx, out bool enable) inline static private
Definition at line 150 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(enable) )
        {
            return false;
        }
        return true;
    }
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
ReadShockParams()
static bool DayZPlayerSyncJunctures::ReadShockParams (ParamsReadContext pCtx, out float shockValue) inline static private
Definition at line 394 of file dayzplayersyncjunctures.c.
    {
        if ( !pCtx.Read(shockValue) )
            return false; // error
        return true;
    }
References Serializer::Read().
Referenced by ManBase::OnSyncJuncture().
SendActionAcknowledgment()
static void DayZPlayerSyncJunctures::SendActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept) inline static private
Action Acknowledgment
Definition at line 253 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(AckID);
        if (accept)
            pPlayer.SendSyncJuncture(SJ_ACTION_ACK_ACCEPT, ctx);
        else
            pPlayer.SendSyncJuncture(SJ_ACTION_ACK_REJECT, ctx);
    }
References SJ_ACTION_ACK_ACCEPT, SJ_ACTION_ACK_REJECT, and Serializer::Write().
Referenced by ActionManagerServer::OnInputUserDataProcess(), ActionManagerServer::StartDeliveredAction(), and ActionManagerServer::Update().
SendActionInterrupt()
static void DayZPlayerSyncJunctures::SendActionInterrupt (DayZPlayer pPlayer) inline static private
Action interrupt
Definition at line 238 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        pPlayer.SendSyncJuncture(SJ_ACTION_INTERRUPT, ctx);
    }
References SJ_ACTION_INTERRUPT.
Referenced by ActionManagerServer::Interrupt(), ActionBaseCB::Interrupt(), ActionManagerServer::OnInputUserDataProcess(), ActionManagerServer::StartDeliveredAction(), and ActionManagerServer::Update().
SendBrokenLegs()
static void DayZPlayerSyncJunctures::SendBrokenLegs (DayZPlayer pPlayer, bool canPlaySound, eBrokenLegs currentState, eBrokenLegs localState) inline static private
BrokenLegs
Definition at line 343 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(canPlaySound);
        ctx.Write(currentState);
        ctx.Write(localState);
        pPlayer.SendSyncJuncture(SJ_BROKEN_LEGS, ctx);
    }
References SJ_BROKEN_LEGS, and Serializer::Write().
SendBrokenLegsEx()
static void DayZPlayerSyncJunctures::SendBrokenLegsEx (DayZPlayer pPlayer, int currentState) inline static private
Definition at line 365 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(currentState);
        pPlayer.SendSyncJuncture(SJ_BROKEN_LEGS, ctx);
    }
References SJ_BROKEN_LEGS, and Serializer::Write().
Referenced by ManBase::SetBrokenLegs().
SendDamageHit()
static void DayZPlayerSyncJunctures::SendDamageHit (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody) inline static private
DamageHit
Definition at line 62 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(pType);
        ctx.Write(pHitDir);
        ctx.Write(pFullbody);
        pPlayer.SendSyncJuncture(SJ_DAMAGE_HIT, ctx);
    }
References SJ_DAMAGE_HIT, and Serializer::Write().
SendDamageHitEx()
static void DayZPlayerSyncJunctures::SendDamageHitEx (DayZPlayer pPlayer, int pType, float pHitDir, bool pFullbody, TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos) inline static private
Definition at line 72 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        SyncHitInfo data = new SyncHitInfo;
        data.m_AnimType = pType;
        data.m_HitDir = pHitDir;
        data.m_Fullbody = pFullbody;
        data.m_HasSource = pSource != null;
        if ( !pDamageResult )
        {
            data.m_HealthDamage = -1.0;
        }
        else
        {
            data.m_HealthDamage = pDamageResult.GetHighestDamage("Health");
        }
        ctx.Write(data);
        pPlayer.SendSyncJuncture(SJ_DAMAGE_HIT, ctx);
    }
References TotalDamageResult::GetHighestDamage(), Managed::m_AnimType, SJ_DAMAGE_HIT, and Serializer::Write().
Referenced by EEHitBy().
SendDeath()
static void DayZPlayerSyncJunctures::SendDeath (DayZPlayer pPlayer, int pType, float pHitDir) inline static private
Death
Definition at line 38 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(pType);
        ctx.Write(pHitDir);
        pPlayer.SendSyncJuncture(SJ_DEATH, ctx);
    }
References SJ_DEATH, and Serializer::Write().
Referenced by SendDeathJuncture().
SendDeleteItem()
static void DayZPlayerSyncJunctures::SendDeleteItem (DayZPlayer pPlayer, EntityAI item) inline static private
Definition at line 329 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(item);
        pPlayer.SendSyncJuncture(SJ_DELETE_ITEM, ctx);
    }
References SJ_DELETE_ITEM, and Serializer::Write().
Referenced by ManBase::JunctureDeleteItem().
SendInjury()
static void DayZPlayerSyncJunctures::SendInjury (DayZPlayer pPlayer, bool pEnable, eInjuryHandlerLevels level) inline static private
Injury
Definition at line 117 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(pEnable);
        ctx.Write(level);
        pPlayer.SendSyncJuncture(SJ_INJURY, ctx);
    }
References SJ_INJURY, and Serializer::Write().
Referenced by SendValue().
SendKuruRequest()
static void DayZPlayerSyncJunctures::SendKuruRequest (DayZPlayer pPlayer, float amount) inline static private
Definition at line 286 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(amount);
        pPlayer.SendSyncJuncture(SJ_KURU_REQUEST, ctx);
    }
References SJ_KURU_REQUEST, and Serializer::Write().
Referenced by BrainDiseaseMdfr::OnTick().
SendPlayerFBModifier()
static void DayZPlayerSyncJunctures::SendPlayerFBModifier (PlayerBase pPlayer, int type) inline static private
Full body
Definition at line 164 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(type);
        pPlayer.SendSyncJuncture(SJ_PLAYER_FB_MODIFIER, ctx);
    }
References SJ_PLAYER_FB_MODIFIER, and Serializer::Write().
SendPlayerSymptomADD()
static void DayZPlayerSyncJunctures::SendPlayerSymptomADD (DayZPlayer pPlayer, int type, int state_type) inline static private
Additive Symptoms
Definition at line 184 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(state_type);
        ctx.Write(type);
        pPlayer.SendSyncJuncture(SJ_PLAYER_ADD_MODIFIER, ctx);
    }
References SJ_PLAYER_ADD_MODIFIER, and Serializer::Write().
Referenced by SymptomBase::PlayAnimationADD().
SendPlayerSymptomFB()
static void DayZPlayerSyncJunctures::SendPlayerSymptomFB (DayZPlayer pPlayer, DayZPlayerConstants anim_id, int state_type, int stance_mask, float duration) inline static private
Full body Symptoms
Definition at line 207 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(state_type);
        ctx.Write(anim_id);
        ctx.Write(stance_mask);
        ctx.Write(duration);
        //ctx.Write(pPlayer);
        pPlayer.SendSyncJuncture(SJ_PLAYER_STATES, ctx);
    }
References SJ_PLAYER_STATES, and Serializer::Write().
Referenced by SymptomBase::PlayAnimationFB().
SendPlayerUnconsciousness()
static void DayZPlayerSyncJunctures::SendPlayerUnconsciousness (DayZPlayer pPlayer, bool enable) inline static private
Conscious / Unconscious
Definition at line 141 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(enable);
        pPlayer.SendSyncJuncture(SJ_UNCONSCIOUSNESS, ctx);
    }
References SJ_UNCONSCIOUSNESS, and Serializer::Write().
Referenced by UnconsciousnessMdfr::OnActivate(), UnconsciousnessMdfr::OnDeactivate(), ManBase::RequestUnconsciousness(), and ManBase::ResetPlayer().
SendQuickbarSetShortcut()
static void DayZPlayerSyncJunctures::SendQuickbarSetShortcut (DayZPlayer pPlayer, EntityAI item, int index, bool force = false) inline static private
Quickbar
Definition at line 298 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(item);
        ctx.Write(index);
        ctx.Write(force);
        pPlayer.SendSyncJuncture(SJ_QUICKBAR_SET_SHORTCUT, ctx);
    }
References SJ_QUICKBAR_SET_SHORTCUT, and Serializer::Write().
Referenced by SetEntityShortcut().
SendShock()
static void DayZPlayerSyncJunctures::SendShock (DayZPlayer pPlayer, float shockValue) inline static private
Shock
Definition at line 386 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(shockValue);
        pPlayer.SendSyncJuncture(SJ_SHOCK, ctx);
    }
References SJ_SHOCK, and Serializer::Write().
Referenced by ShockHandler::Synchronize().
SendWeaponActionAcknowledgment()
static void DayZPlayerSyncJunctures::SendWeaponActionAcknowledgment (DayZPlayer pPlayer, int AckID, bool accept) inline static private
Definition at line 264 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(AckID);
        if (accept)
            pPlayer.SendSyncJuncture(SJ_WEAPON_ACTION_ACK_ACCEPT, ctx);
        else
            pPlayer.SendSyncJuncture(SJ_WEAPON_ACTION_ACK_REJECT, ctx);
    }
References SJ_WEAPON_ACTION_ACK_ACCEPT, SJ_WEAPON_ACTION_ACK_REJECT, and Serializer::Write().
Referenced by WeaponManager::OnInputUserDataProcess().
SendWeaponJamChance()
static void DayZPlayerSyncJunctures::SendWeaponJamChance (DayZPlayer pPlayer, float jamChance) inline static private
Definition at line 308 of file dayzplayersyncjunctures.c.
    {
        ScriptJunctureData ctx = new ScriptJunctureData;
        ctx.Write(jamChance);
        pPlayer.SendSyncJuncture(SJ_WEAPON_SET_JAMMING_CHANCE, ctx);
    }
References SJ_WEAPON_SET_JAMMING_CHANCE, and Serializer::Write().
Referenced by WeaponManager::Update().
Member Data Documentation
SJ_ACTION_ACK_ACCEPT
const int DayZPlayerSyncJunctures::SJ_ACTION_ACK_ACCEPT = 6 static private
Definition at line 12 of file dayzplayersyncjunctures.c.
Referenced by ActionManagerBase::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionAcknowledgment().
SJ_ACTION_ACK_REJECT
const int DayZPlayerSyncJunctures::SJ_ACTION_ACK_REJECT = 7 static private
Definition at line 13 of file dayzplayersyncjunctures.c.
Referenced by ActionManagerBase::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionAcknowledgment().
SJ_ACTION_INTERRUPT
const int DayZPlayerSyncJunctures::SJ_ACTION_INTERRUPT = 2 static private
Definition at line 8 of file dayzplayersyncjunctures.c.
Referenced by ActionManagerBase::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendActionInterrupt().
SJ_ADS_RESET
const int DayZPlayerSyncJunctures::SJ_ADS_RESET = 25 static private
Definition at line 31 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ManBase::ResetADSPlayerSync().
SJ_BROKEN_LEGS
const int DayZPlayerSyncJunctures::SJ_BROKEN_LEGS = 21 static private
Definition at line 27 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), SendBrokenLegs(), and SendBrokenLegsEx().
SJ_DAMAGE_HIT
const int DayZPlayerSyncJunctures::SJ_DAMAGE_HIT = 0 static private
Definition at line 6 of file dayzplayersyncjunctures.c.
Referenced by OnSyncJuncture(), SendDamageHit(), and SendDamageHitEx().
SJ_DEATH
const int DayZPlayerSyncJunctures::SJ_DEATH = 12 static private
Definition at line 18 of file dayzplayersyncjunctures.c.
Referenced by OnSyncJuncture(), and SendDeath().
SJ_DELETE_ITEM
const int DayZPlayerSyncJunctures::SJ_DELETE_ITEM = 20 static private
Definition at line 26 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendDeleteItem().
SJ_GESTURE_REQUEST
const int DayZPlayerSyncJunctures::SJ_GESTURE_REQUEST = 16 static private
Definition at line 22 of file dayzplayersyncjunctures.c.
Referenced by OnInputUserDataProcess(), ManBase::OnSyncJuncture(), and ServerRequestEmoteCancel().
SJ_INJURY
const int DayZPlayerSyncJunctures::SJ_INJURY = 1 static private
Definition at line 7 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendInjury().
SJ_INVENTORY
const int DayZPlayerSyncJunctures::SJ_INVENTORY = 5 static private
Definition at line 11 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), ProccessInputData(), SendServerHandEventViaJuncture(), and TakeToDst().
SJ_INVENTORY_REPAIR
const int DayZPlayerSyncJunctures::SJ_INVENTORY_REPAIR = 17 static private
Definition at line 23 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ProccessInputData().
SJ_KURU_REQUEST
const int DayZPlayerSyncJunctures::SJ_KURU_REQUEST = 15 static private
Definition at line 21 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendKuruRequest().
SJ_PLAYER_ADD_MODIFIER
const int DayZPlayerSyncJunctures::SJ_PLAYER_ADD_MODIFIER = 14 static private
Definition at line 20 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerSymptomADD().
SJ_PLAYER_FB_MODIFIER
const int DayZPlayerSyncJunctures::SJ_PLAYER_FB_MODIFIER = 13 static private
Definition at line 19 of file dayzplayersyncjunctures.c.
Referenced by SendPlayerFBModifier().
SJ_PLAYER_STATES
const int DayZPlayerSyncJunctures::SJ_PLAYER_STATES = 3 static private
Definition at line 9 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerSymptomFB().
SJ_QUICKBAR_SET_SHORTCUT
const int DayZPlayerSyncJunctures::SJ_QUICKBAR_SET_SHORTCUT = 4 static private
Definition at line 10 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendQuickbarSetShortcut().
SJ_SHOCK
const int DayZPlayerSyncJunctures::SJ_SHOCK = 22 static private
Definition at line 28 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendShock().
SJ_STAMINA
const int DayZPlayerSyncJunctures::SJ_STAMINA = 23 static private
Definition at line 29 of file dayzplayersyncjunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SyncStamina().
SJ_STAMINA_MISC
const int DayZPlayerSyncJunctures::SJ_STAMINA_MISC = 24 static private
Definition at line 30 of file dayzplayersyncjunctures.c.
Referenced by OnSyncJuncture(), ManBase::OnSyncJuncture(), and SyncAdditionalStaminaInfo().
SJ_UNCONSCIOUSNESS
const int DayZPlayerSyncJunctures::SJ_UNCONSCIOUSNESS = 11 static private
Definition at line 17 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and SendPlayerUnconsciousness().
SJ_WEAPON_ACTION_ACK_ACCEPT
const int DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_ACCEPT = 8 static private
Definition at line 14 of file dayzplayersyncjunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponActionAcknowledgment().
SJ_WEAPON_ACTION_ACK_REJECT
const int DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_REJECT = 9 static private
Definition at line 15 of file dayzplayersyncjunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponActionAcknowledgment().
SJ_WEAPON_LIFT
const int DayZPlayerSyncJunctures::SJ_WEAPON_LIFT = 18 static private
Definition at line 24 of file dayzplayersyncjunctures.c.
Referenced by ManBase::OnSyncJuncture(), and ManBase::ReadLiftWeaponRequest().
SJ_WEAPON_RAISE_COMPLETED
const int DayZPlayerSyncJunctures::SJ_WEAPON_RAISE_COMPLETED = 19 static private
Definition at line 25 of file dayzplayersyncjunctures.c.
Referenced by OnSyncJuncture(), and SendCompleteWeaponRaiseJuncture().
SJ_WEAPON_SET_JAMMING_CHANCE
const int DayZPlayerSyncJunctures::SJ_WEAPON_SET_JAMMING_CHANCE = 10 static private
Definition at line 16 of file dayzplayersyncjunctures.c.
Referenced by WeaponManager::OnSyncJuncture(), ManBase::OnSyncJuncture(), and SendWeaponJamChance().