DayzKode: FireworksLauncher Class Reference
FireworksLauncher Class Reference
Private Member Functions
override protected bool CanIgniteItem (EntityAI ignite_target=NULL)
override protected bool CanPutInCargo (EntityAI parent)
override protected bool CanPutIntoHands (EntityAI parent)
void FireworksLauncher ()
protected string GetAmmoType ()
string GetColorSequence ()
protected int GetDamageType ()
override float GetDeployTime ()
how long it takes to deploy this item in seconds
override protected float GetEventDelay ()
protected float GetFuseDelay ()
protected string GetFuseSoundSet ()
override protected float GetMaxAllowedWetness ()
protected int GetMaxShots ()
override bool IsDeployable ()
override protected bool IsIgnited ()
override protected void OnEventServer (int type)
Called periodically but only after the entity gets ignited.
protected void OnFiringStartClient ()
protected void OnFiringStartServer ()
protected void OnFiringStop ()
protected void OnFuseIgnitedClient ()
protected void OnFuseIgnitedServer ()
override protected void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
protected void OnIndexChangedClient ()
override protected void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override protected void OnStateChangedClient (EFireworksState currentState)
override protected void OnStateChangedServer (EFireworksState currentState)
override protected bool OnStoreLoad (ParamsReadContext ctx, int version)
override protected void OnStoreSave (ParamsWriteContext ctx)
override protected void OnVariablesSynchronized ()
protected void RestartEventTimer ()
Starts event timer.
protected void SetupColorSequences ()
protected FireworksLauncherClientEventBase SpawnEvent ()
void ~FireworksLauncher ()
Private Attributes
ref array< string > m_ColorSequence
int m_ColorSequenceIndex
ref array< ref FireworksLauncherClientEventBase > m_Events
EffectSound m_FuseSound
EffectSound m_FuseSoundStart
int m_Index
int m_IndexPrev
ParticleSource m_ParticleAfterBurnEnd
ParticleSource m_ParticleFuse
ref Timer m_TimerFuse
Detailed Description
Definition at line 317 of file fireworkslauncher.c.
Constructor & Destructor Documentation
FireworksLauncher()
void FireworksLauncher::FireworksLauncher () inline private
Definition at line 330 of file fireworkslauncher.c.
    {
        m_ColorSequence = new array<string>();
        SetupColorSequences();
        RegisterNetSyncVariableInt("m_State", 0, EnumTools.GetLastEnumValue(EFireworksState));
        RegisterNetSyncVariableInt("m_Index", 0, GetMaxShots());
        RegisterNetSyncVariableInt("m_RandomSeed", 0, 1023);
        int lastIndex = m_ColorSequence.Count() - 1;
        RegisterNetSyncVariableInt("m_ColorSequenceIndex", 0, lastIndex);
        m_RandomSeed = Math.Randomize(Math.RandomInt(0,1023));
        m_ColorSequenceIndex = Math.RandomIntInclusive(0, lastIndex);
    }
References EnumTools::GetLastEnumValue(), GetMaxShots(), m_ColorSequence, m_ColorSequenceIndex, m_RandomSeed, Math::RandomInt(), Math::RandomIntInclusive(), Math::Randomize(), and SetupColorSequences().
~FireworksLauncher()
void FireworksLauncher::~FireworksLauncher () inline private
Definition at line 344 of file fireworkslauncher.c.
    {
        SEffectManager.DestroyEffect(m_FuseSound);
        SEffectManager.DestroyEffect(m_FuseSoundStart);
    }
References SEffectManager::DestroyEffect(), m_FuseSound, and m_FuseSoundStart.
Member Function Documentation
CanIgniteItem()
override protected bool FireworksLauncher::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 571 of file fireworkslauncher.c.
    {
        return false;
    }
CanPutInCargo()
override protected bool FireworksLauncher::CanPutInCargo (EntityAI parent) inline private
Definition at line 488 of file fireworkslauncher.c.
    {
        return (GetState() == EFireworksState.DEFAULT || (GetState() == EFireworksState.PLACED) || (GetState() == EFireworksState.FINISHED);
    }
References GetState().
CanPutIntoHands()
override protected bool FireworksLauncher::CanPutIntoHands (EntityAI parent) inline private
Definition at line 493 of file fireworkslauncher.c.
    {
        return (GetState() == EFireworksState.DEFAULT || (GetState() == EFireworksState.PLACED) || (GetState() == EFireworksState.FINISHED);
    }
References GetState().
GetAmmoType()
protected string FireworksLauncher::GetAmmoType () inline private
Definition at line 425 of file fireworkslauncher.c.
    {
        return "Fireworks_Ammo";
    }
Referenced by OnEventServer().
GetColorSequence()
string FireworksLauncher::GetColorSequence () inline private
Definition at line 373 of file fireworkslauncher.c.
    {
        if (m_ColorSequence.IsValidIndex(m_ColorSequenceIndex))
        {
            return m_ColorSequence.Get(m_ColorSequenceIndex);
        }
        else
        {
            ErrorEx("Failed to obtain color sequence");
            return "RYPBYYPBRGBYPBRGBRBGBPBRGRGBRBGRYPYR";
        }
    }
References ErrorEx, m_ColorSequence, and m_ColorSequenceIndex.
Referenced by FireworksLauncherClientEvent::FireworksLauncherClientEvent().
GetDamageType()
protected int FireworksLauncher::GetDamageType () inline private
Definition at line 430 of file fireworkslauncher.c.
    {
        return DamageType.EXPLOSION;
    }
Referenced by OnEventServer().
GetDeployTime()
override float FireworksLauncher::GetDeployTime () inline private
how long it takes to deploy this item in seconds
Definition at line 356 of file fireworkslauncher.c.
    {
        return 2;
    }
GetEventDelay()
override protected float FireworksLauncher::GetEventDelay () inline private
Definition at line 405 of file fireworkslauncher.c.
    {
        return Math.RandomFloatInclusive(3,3.35);
    }
References Math::RandomFloatInclusive().
Referenced by RestartEventTimer().
GetFuseDelay()
protected float FireworksLauncher::GetFuseDelay () inline private
Definition at line 420 of file fireworkslauncher.c.
    {
        return 3;
    }
Referenced by OnFuseIgnitedServer().
GetFuseSoundSet()
protected string FireworksLauncher::GetFuseSoundSet () inline private
Definition at line 410 of file fireworkslauncher.c.
    {
        return "FireworksLauncher_Ignition_Loop_SoundSet";
    }
Referenced by OnFuseIgnitedClient().
GetMaxAllowedWetness()
override protected float FireworksLauncher::GetMaxAllowedWetness () inline private
Definition at line 399 of file fireworkslauncher.c.
    {
        return GameConstants.STATE_WET;
    }
References GameConstants::STATE_WET.
GetMaxShots()
protected int FireworksLauncher::GetMaxShots () inline private
Definition at line 415 of file fireworkslauncher.c.
    {
        return 16;
    }
Referenced by FireworksLauncher(), and OnEventServer().
IsDeployable()
override bool FireworksLauncher::IsDeployable () inline private
Definition at line 350 of file fireworkslauncher.c.
    {
        return true;
    }
IsIgnited()
override protected bool FireworksLauncher::IsIgnited () inline private
Definition at line 566 of file fireworkslauncher.c.
    {
        return GetState()==EFireworksState.IGNITED;
    }
References GetState().
OnEventServer()
override protected void FireworksLauncher::OnEventServer (int type) inline private
Called periodically but only after the entity gets ignited.
Definition at line 579 of file fireworkslauncher.c.
    {
        m_Index++;
        DamageSystem.ExplosionDamage(this, NULL, GetAmmoType(), GetPosition(), GetDamageType());
        SetSynchDirty();
        if (m_Index > GetMaxShots())
        {
            m_Index = GetMaxShots();
            m_TimerEvent = null;
            SetState(EFireworksState.FINISHED);
        }
        else
        {
            RestartEventTimer();
        }
    }
References GetAmmoType(), GetDamageType(), GetMaxShots(), GetPosition, m_Index, m_TimerEvent, RestartEventTimer(), and SetState().
Referenced by OnFiringStartServer().
OnFiringStartClient()
protected void FireworksLauncher::OnFiringStartClient () inline private
Definition at line 538 of file fireworkslauncher.c.
    {
        if (m_ParticleFuse)
        {
            m_ParticleFuse.StopParticle(StopParticleFlags.IMMEDIATE);
        }
        if (m_FuseSound)
        {
            m_FuseSound.Stop();
        }
    }
References m_FuseSound, m_ParticleFuse, EffectSound::Stop(), and ParticleSource::StopParticle().
Referenced by OnStateChangedClient().
OnFiringStartServer()
protected void FireworksLauncher::OnFiringStartServer () inline private
Definition at line 533 of file fireworkslauncher.c.
    {
        OnEventServer(0);
    }
References OnEventServer().
Referenced by OnStateChangedServer().
OnFiringStop()
protected void FireworksLauncher::OnFiringStop () inline private
Definition at line 550 of file fireworkslauncher.c.
    {
        SetHealth01("","",0);
    }
References SetHealth01().
OnFuseIgnitedClient()
protected void FireworksLauncher::OnFuseIgnitedClient () inline private
Definition at line 504 of file fireworkslauncher.c.
    {
        m_ParticleFuse = ParticleManager.GetInstance().PlayInWorld(ParticleList.FIREWORKS_FUSE, GetPosition() + "0 0.15 0");
        if (m_ParticleFuse)
            m_ParticleFuse.SetOwner(this);
        PlaySoundSet( m_FuseSoundStart, "FireworksLauncher_Ignition_Start_SoundSet", 0, 0 );
        vector fuseStart;
        vector fuseEnd;
        if (MemoryPointExists("Fuse_Start"))
        {
            fuseStart = GetMemoryPointPos("Fuse_Start");
            fuseStart = ModelToWorld(fuseStart);
        }
        if (MemoryPointExists("Fuse_End"))
        {
            fuseEnd = GetMemoryPointPos("Fuse_End");
            fuseEnd = ModelToWorld(fuseEnd);
        }
        vector fuseDir = fuseEnd - fuseStart;
        vector fuseOrientation[4];
        vector ori = fuseDir.VectorToAngles();
        m_ParticleFuse.SetOrientation(ori);
        m_ParticleFuse.SetPosition(fuseStart);
        PlaySoundSetLoop( m_FuseSound, GetFuseSoundSet(), 0, 0 );
    }
References ParticleList::FIREWORKS_FUSE, GetFuseSoundSet(), GetMemoryPointPos(), GetPosition, m_FuseSound, m_FuseSoundStart, m_ParticleFuse, MemoryPointExists(), ModelToWorld(), ParticleManager(), PlaySoundSet(), PlaySoundSetLoop(), ParticleSource::SetOwner(), and vector::VectorToAngles().
Referenced by OnStateChangedClient().
OnFuseIgnitedServer()
protected void FireworksLauncher::OnFuseIgnitedServer () inline private
Definition at line 498 of file fireworkslauncher.c.
    {
        int state = EFireworksState.FIRING;
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( SetState, GetFuseDelay()*1000, false, state);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetFuseDelay(), GetGame(), and SetState().
Referenced by OnStateChangedServer().
OnIgnitedThis()
override protected void FireworksLauncher::OnIgnitedThis (EntityAI fire_source) inline private
Executed on Server when some item ignited this one.
Definition at line 473 of file fireworkslauncher.c.
    {
        super.OnIgnitedThis(fire_source);
        if (m_Events)
        {
            m_Events.Clear();
        }
        m_Index = 0;
        if (m_TimerEvent)
        {
            m_TimerEvent.Stop();
        }
    }
References m_Events, m_Index, and m_TimerEvent.
OnIndexChangedClient()
protected void FireworksLauncher::OnIndexChangedClient () inline private
Definition at line 597 of file fireworkslauncher.c.
    {
        if (!m_Events)
        {
            m_Events = new array<ref FireworksLauncherClientEventBase>;
        }
        if (m_Index != 0 && m_State == EFireworksState.FIRING)//can only be true when restarting the device during debug calls
        {
            FireworksLauncherClientEventBase fireEvent = SpawnEvent();
            m_Events.Insert(fireEvent);
        }
    }
References m_Events, m_Index, m_State, and SpawnEvent().
Referenced by OnVariablesSynchronized().
OnPlacementComplete()
override protected void FireworksLauncher::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 387 of file fireworkslauncher.c.
    {
        super.OnPlacementComplete(player, position, orientation);
        if (GetGame().IsServer())
        {
            if (GetState() == EFireworksState.DEFAULT)
            {
                SetState(EFireworksState.PLACED);
            }
        }
    }
References GetGame(), GetState(), and SetState().
OnStateChangedClient()
override protected void FireworksLauncher::OnStateChangedClient (EFireworksState currentState) inline private
Definition at line 456 of file fireworkslauncher.c.
    {
        switch (currentState)
        {
            case EFireworksState.IGNITED:
                OnFuseIgnitedClient();
                break
            case EFireworksState.PLACED:
                break
            case EFireworksState.FIRING:
                OnFiringStartClient();
                break
            default: {};
        }
    }
References OnFiringStartClient(), and OnFuseIgnitedClient().
OnStateChangedServer()
override protected void FireworksLauncher::OnStateChangedServer (EFireworksState currentState) inline private
Definition at line 436 of file fireworkslauncher.c.
    {
        switch (currentState)
        {
            case EFireworksState.PLACED:
                break
            case EFireworksState.IGNITED:
                OnFuseIgnitedServer();
                break
            case EFireworksState.FIRING:
                HideSelection("cover");
                OnFiringStartServer();
                break
            case EFireworksState.FINISHED:
                HideSelection("cover");//when loading from storage
                break
            default: {};
        }
    }
References OnFiringStartServer(), and OnFuseIgnitedServer().
OnStoreLoad()
override protected bool FireworksLauncher::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 637 of file fireworkslauncher.c.
    {
        if (!super.OnStoreLoad(ctx, version))
        {
            return false;
        }
        if (version >= 130)
        {
            if (!ctx.Read(m_Index))
            {
                return false;
            }
            if (!ctx.Read(m_State))
            {
                return false;
            }
            SetState(m_State);
        }
        return true;
    }
References m_Index, m_State, Serializer::Read(), and SetState().
OnStoreSave()
override protected void FireworksLauncher::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 629 of file fireworkslauncher.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_Index);
        ctx.Write(m_State);
    }
References m_Index, m_State, and Serializer::Write().
OnVariablesSynchronized()
override protected void FireworksLauncher::OnVariablesSynchronized () inline private
Definition at line 617 of file fireworkslauncher.c.
    {
        super.OnVariablesSynchronized();
        //Print("index: " + m_Index);
        if (m_Index != m_IndexPrev)
        {
            Math.Randomize(m_RandomSeed+m_Index);
            OnIndexChangedClient();
            m_IndexPrev = m_Index;
        }
    }
References m_Index, m_IndexPrev, m_RandomSeed, OnIndexChangedClient(), and Math::Randomize().
RestartEventTimer()
protected void FireworksLauncher::RestartEventTimer () inline private
Starts event timer.
Definition at line 556 of file fireworkslauncher.c.
    {
        if (!m_TimerEvent)
        {
            m_TimerEvent = new Timer();
        }
        m_TimerEvent.Run(GetEventDelay(), this, "OnEventServer", new Param1<int>(0));
    }
References GetEventDelay(), and m_TimerEvent.
Referenced by OnEventServer().
SetupColorSequences()
protected void FireworksLauncher::SetupColorSequences () inline private
Definition at line 361 of file fireworkslauncher.c.
    {
        m_ColorSequence.Insert("RGBYPBRGBRGBYPBRGBRGBYPBRGBPBRGBRGBY");
        m_ColorSequence.Insert("PGPYPBYPYPBYYPBRPYPBYYPBRGBPBRGRGBRB");
        m_ColorSequence.Insert("GRPBRGBRYPBYYPBRPYPBYYPBRGBPBRGRGBRB");
        m_ColorSequence.Insert("YRBGPRYPGRYBGRGRGBRBBYPYPBYRYPGRYGRP");
        m_ColorSequence.Insert("BGRYPYRPBYYPYRBGPRYPGBYPBRGBPBRGBRGB");
        m_ColorSequence.Insert("RYGRPBRGBYPBRRPBRGBBRBBYPYPRGBRGBRPY");
        m_ColorSequence.Insert("GBRGBYRGBYPBRRPBRBYRYPGPYPRGBRGBRPYG");
        m_ColorSequence.Insert("RYPBYYPBRGBYPBRGBRBGBPBRGRGBRBGRYPYR");
    }
References m_ColorSequence.
Referenced by FireworksLauncher().
SpawnEvent()
protected FireworksLauncherClientEventBase FireworksLauncher::SpawnEvent () inline private
Definition at line 610 of file fireworkslauncher.c.
    {
        FireworksLauncherClientEventBase evnt = new FireworksLauncherClientEvent(this,m_Index);
        evnt.OnFired();
        return evnt;
    }
References m_Index.
Referenced by OnIndexChangedClient().
Member Data Documentation
m_ColorSequence
ref array<string> FireworksLauncher::m_ColorSequence private
Definition at line 328 of file fireworkslauncher.c.
Referenced by FireworksLauncher(), GetColorSequence(), and SetupColorSequences().
m_ColorSequenceIndex
int FireworksLauncher::m_ColorSequenceIndex private
Definition at line 321 of file fireworkslauncher.c.
Referenced by FireworksLauncher(), and GetColorSequence().
m_Events
ref array<ref FireworksLauncherClientEventBase> FireworksLauncher::m_Events private
Definition at line 323 of file fireworkslauncher.c.
Referenced by OnIgnitedThis(), and OnIndexChangedClient().
m_FuseSound
EffectSound FireworksLauncher::m_FuseSound private
Definition at line 325 of file fireworkslauncher.c.
Referenced by OnFiringStartClient(), OnFuseIgnitedClient(), and ~FireworksLauncher().
m_FuseSoundStart
EffectSound FireworksLauncher::m_FuseSoundStart private
Definition at line 324 of file fireworkslauncher.c.
Referenced by OnFuseIgnitedClient(), and ~FireworksLauncher().
m_Index
int FireworksLauncher::m_Index private
Definition at line 319 of file fireworkslauncher.c.
Referenced by OnEventServer(), OnIgnitedThis(), OnIndexChangedClient(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), and SpawnEvent().
m_IndexPrev
int FireworksLauncher::m_IndexPrev private
Definition at line 320 of file fireworkslauncher.c.
Referenced by OnVariablesSynchronized().
m_ParticleAfterBurnEnd
ParticleSource FireworksLauncher::m_ParticleAfterBurnEnd private
Definition at line 327 of file fireworkslauncher.c.
m_ParticleFuse
ParticleSource FireworksLauncher::m_ParticleFuse private
Definition at line 326 of file fireworkslauncher.c.
Referenced by OnFiringStartClient(), and OnFuseIgnitedClient().
m_TimerFuse
ref Timer FireworksLauncher::m_TimerFuse private
Definition at line 322 of file fireworkslauncher.c.