DayzKode: InventoryLocation Class Reference
InventoryLocation Class Reference
InventoryLocation.
Private Member Functions
proto native bool CollidesWith (notnull InventoryLocation rhs)
checks if inventory locations collides each with other
proto native bool CompareLocationOnly (notnull InventoryLocation other)
proto native InventoryLocation Copy (notnull InventoryLocation rhs)
copies location data to another location
proto native InventoryLocation CopyLocationFrom (notnull InventoryLocation rhs, bool copyFlip)
copies location to another location without m_item member
string DumpToString ()
proto native int GetCol ()
returns column of cargo if current type is Cargo / ProxyCargo
proto native void GetDir (out float dir[4])
returns direction of item in world if type is Ground
proto native bool GetFlip ()
returns flip status of cargo
proto native int GetIdx ()
returns index of cargo if current type is Cargo / ProxyCargo
proto native EntityAI GetItem ()
returns item of current inventory location
proto native EntityAI GetParent ()
returns parent of current inventory location
proto native vector GetPos ()
returns position of item in world if type is Ground
proto native int GetRow ()
returns row of cargo if current type is Cargo / ProxyCargo
proto native int GetSlot ()
returns slot id if current type is Attachment
proto native int GetType ()
returns type of InventoryLocation
proto native bool IsValid ()
verify current set inventory location
bool ReadFromContext (ParamsReadContext ctx)
proto native void Reset ()
proto native void SetAttachment (notnull EntityAI parent, EntityAI e, int slotId)
sets current inventory location type to Attachment with slot id set to <slotId>
proto native void SetCargo (notnull EntityAI parent, EntityAI e, int idx, int row, int col, bool flip)
sets current inventory location type to Cargo with coordinates (idx, row, col)
proto native void SetCargoAuto (notnull CargoBase cargo, EntityAI e, int row, int col, bool flip)
based on Cargo.IsProxyCargo uses SetProxyCargo or SetCargo respectively
proto native void SetCol (int col)
proto native void SetFlip (bool flip)
proto native void SetGround (EntityAI e, vector mat[4])
sets current inventory location type to Ground with transformation mat
proto native void SetGroundEx (EntityAI e, vector pos, float dir[4])
sets current inventory location type to Ground with transformation mat
proto native void SetHands (notnull EntityAI parent, EntityAI e)
sets current inventory location type to Hands
proto native void SetIndex (int idx)
proto native void SetItem (notnull EntityAI item)
proto native void SetParent (notnull EntityAI parent)
proto native void SetProxyCargo (notnull EntityAI parent, EntityAI e, int idx, int row, int col, bool flip)
sets current inventory location type to ProxyCargo with coordinates (idx, row, col) @NOTE: typical usage is in building-like dummy structures, where furniture with cargo is part of the model, and is not a physical entity (like person or bag).
proto native void SetRow (int row)
proto native void SetSlot (int slotId)
bool WriteToContext (ParamsWriteContext ctx)
Static Private Member Functions
static string DumpToStringNullSafe (InventoryLocation loc)
Detailed Description
InventoryLocation.
Definition at line 27 of file inventorylocation.c.
Member Function Documentation
CollidesWith()
InventoryLocation::CollidesWith (notnull InventoryLocation rhs) private
checks if inventory locations collides each with other
CompareLocationOnly()
proto native bool InventoryLocation::CompareLocationOnly (notnull InventoryLocation other) private
Referenced by ClosableContainer::DropReceived(), HandsContainer::DropReceived(), ActionSawPlanks::OnFinishProgressServer(), and ProccessInputData().
Copy()
InventoryLocation::Copy (notnull InventoryLocation rhs) private
copies location data to another location
@NOTE it copies all data (except enforce internal data)
Referenced by InventoryItem::EEItemLocationChanged(), FirearmActionDetachMagazine::HandleReciveData(), MakeDstForSwap(), MakeSrcAndDstForForceSwap(), HumanInventory::OnEntityInHandsCreated(), HumanInventory::OnEntityInHandsDestroyed(), ActionSawPlanks::OnFinishProgressServer(), SlotToAnimType(), HumanInventory::SwappingToPreviousLocation(), and TransferInventory().
CopyLocationFrom()
InventoryLocation::CopyLocationFrom (notnull InventoryLocation rhs, bool copyFlip) private
copies location to another location without m_item member
@NOTE it does NOT do a copy of m_item member!
Referenced by Icon::DropReceivedFromMain(), MakeDstForSwap(), MakeSrcAndDstForForceSwap(), ManBase::OnQuickBarSingleUse(), and ReplaceItemWithNewLambdaBase::PrepareLocations().
DumpToString()
string InventoryLocation::DumpToString () inline private
Definition at line 225 of file inventorylocation.c.
    {
        string res = "{ type=" + typename.EnumToString(InventoryLocationType, GetType());
        switch (GetType())
        {
            case InventoryLocationType.UNKNOWN:
            {
                break;
            }
            case InventoryLocationType.GROUND:
            {
                res = res + " item=" + Object.GetDebugName(GetItem());
                vector pos = GetPos();
                float dir[4];
                GetDir(dir);
                res = res + " pos=(" + pos[0] + ", " + pos[1] + ", " + pos[2] + ")";
                res = res + " dir=(" + dir[0] + ", " + dir[1] + ", " + dir[2] + ", " + dir[3] + ")";
                break;
            }
            case InventoryLocationType.ATTACHMENT:
            {
                res = res + " item=" + Object.GetDebugName(GetItem());
                res = res + " parent=" + Object.GetDebugName(GetParent());
                res = res + " slot=" + GetSlot();
                break;
            }
            case InventoryLocationType.CARGO:
            {
                res = res + " item=" + Object.GetDebugName(GetItem());
                res = res + " parent=" + Object.GetDebugName(GetParent());
                res = res + " idx=" + GetIdx() + " row=" + GetRow() + " col=" + GetCol() + " f=" + GetFlip();
                break;
            }
            case InventoryLocationType.HANDS:
            {
                res = res + " item=" + Object.GetDebugName(GetItem());
                res = res + " parent=" + Object.GetDebugName(GetParent());
                break;
            }
            case InventoryLocationType.PROXYCARGO:
            {
                res = res + " item=" + Object.GetDebugName(GetItem());
                res = res + " parent=" + Object.GetDebugName(GetParent());
                res = res + " idx=" + GetIdx() + " row=" + GetRow() + " col=" + GetCol() + " f=" + GetFlip();
                break;
            }
            default:
            {
                res = res + "??";
                break;
            }
        }
        res = res + " }";
        return res;
    }
References GetCol(), GetDir(), GetFlip(), GetIdx(), GetItem(), GetParent(), GetPos(), GetRow(), GetSlot(), and GetType().
Referenced by DumpToStringNullSafe(), and CraftingManager::OnUpdate().
DumpToStringNullSafe()
static string InventoryLocation::DumpToStringNullSafe (InventoryLocation loc) inline static private
Definition at line 218 of file inventorylocation.c.
    {
        if (loc)
            return loc.DumpToString();
        return "{ null }";
    }
References DumpToString().
Referenced by CGame::AddInventoryJunctureEx(), AddInventoryReservationEx(), HandEventBase::CheckRequestSrc(), ClearInventoryReservationEx(), ManBase::CreateCopyOfItemInInventory(), DumpToString(), HandEventBase::DumpToString(), ReplaceItemWithNewLambdaBase::Execute(), ExtendInventoryReservationEx(), HumanInventory::ForceSwapEntities(), ForceSwapEntities(), HandGuardBase::GuardCondition(), HandleForceSwapEntities(), HandleSwapEntities(), HandleTakeToDst(), HumanInventory::OnEntityInHandsCreated(), HumanInventory::OnEntityInHandsDestroyed(), WeaponStateBase::OnEntry(), ActionDigInStash::OnFinishProgressServer(), ManBase::OnQuickBarSingleUse(), OnServerInventoryCommandStatic(), ProccessInputData(), ReplaceItemWithNewLambdaBase::RemoveOldItemFromLocation(), SelectAnimationOfForceSwapInHands(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), SendServerHandEventViaJuncture(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), SetupAction(), HumanInventory::SwapEntities(), HumanInventory::TakeToDst(), TakeToDst(), EntityAI::TakeToDstImpl(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), and ReplaceItemWithNewLambdaBase::UndoRemoveOldItemFromLocation().
GetCol()
InventoryLocation::GetCol () private
returns column of cargo if current type is Cargo / ProxyCargo
Returns
index or -1
Referenced by Container::AddedToCargoEx(), CreateInInventory(), DumpToString(), Container::MovedInCargo(), InventoryItem::OnRightClick(), Container::SetLock(), and WriteToContext().
GetDir()
InventoryLocation::GetDir (out float dir[4]) private
returns direction of item in world if type is Ground
Returns
position
Referenced by DropNonUsableMaterialsServer(), DumpToString(), ReplaceItemWithNewLambdaBase::PrepareLocations(), and WriteToContext().
GetFlip()
InventoryLocation::GetFlip () private
returns flip status of cargo
Returns
true/false
Referenced by CreateInInventory(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), DumpToString(), InventoryItem::OnRightClick(), Container::SetLock(), and WriteToContext().
GetIdx()
InventoryLocation::GetIdx () private
returns index of cargo if current type is Cargo / ProxyCargo
Returns
index or -1
Referenced by CreateInInventory(), DumpToString(), IsItemInCargoOfSomething(), InventoryItem::OnRightClick(), PumpkinHelmet::UpdateGlowState(), and WriteToContext().
GetItem()
InventoryLocation::GetItem () private
returns item of current inventory location
Item can be null if and only if this is a query for location of item that is about to be created (new spawn).
Returns
item
Referenced by HandEventSwap::CanPerformEvent(), HandEventBase::CheckAndExecuteForceStandUp(), CheckForRope(), ClearInventoryReservation(), ClearInventoryReservationEx(), HumanInventory::ClearUserReservedLocationAtIndexSynced(), DumpToString(), InventoryItem::EEItemLocationChanged(), GetSrcEntity(), HandGuardBase::GuardCondition(), HandleHandEvent(), HandleSwapEntities(), WeaponManager::InventoryReservation(), LocalDestroyEntity(), WeaponManager::OnInputUserDataProcess(), OnServerInventoryCommandStatic(), WeaponManager::OnWeaponActionEnd(), ProccessInputData(), RefreshReservations(), ReserveInventory(), SendServerHandEventViaJuncture(), SlotToAnimType(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), WeaponManager::StartPendingAction(), HumanInventory::Update(), and WriteToContext().
GetParent()
InventoryLocation::GetParent () private
returns parent of current inventory location
Parent entity can be null if item is on ground.
Returns
parent entity, null otherwise
Referenced by Environment::ApplyDrynessToItem(), Environment::ApplyWetnessToItem(), CanAddAsShortcut(), WeaponManager::CanAttachMagazine(), RecipeBase::CanDo(), CanReceiveAttachment(), CanSwapEntities(), WeaponManager::CanSwapMagazine(), CreateInInventory(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), Icon::DoubleClick(), Icon::DropReceivedFromMain(), DumpToString(), InventoryItem::EEDelete(), EEInit(), InventoryItem::EEItemLocationChanged(), HandGuardBase::GuardCondition(), IsCargoInHiearchy(), Weapon::IsRemoteWeapon(), PlayerContainer::OnDropReceivedFromGhostArea(), InventoryItem::OnRightClick(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HumanInventory::RedirectToHandEvent(), ReplaceItemWithNew(), PlayerContainer::Select(), ZombieContainer::Select(), SendServerHandEventViaJuncture(), SlotToAnimType(), PluginBase::SpawnEntityInInventory(), SplitItemUtils::TakeOrSplitToInventory(), WriteToContext(), and InventoryItem::~ItemBase().
GetPos()
InventoryLocation::GetPos () private
returns position of item in world if type is Ground
Returns
position
Referenced by ReplaceItemWithNewLambdaBase::CreateNewEntity(), DumpToString(), WeaponStateBase::OnAbort(), OnAbort(), WeaponStateBase::OnExit(), ReplaceItemWithNewLambdaBase::PrepareLocations(), ManBase::SpawnEntityOnGroundPos(), and WriteToContext().
GetRow()
InventoryLocation::GetRow () private
returns row of cargo if current type is Cargo / ProxyCargo
Returns
row or -1
Referenced by Container::AddedToCargoEx(), CreateInInventory(), DumpToString(), Container::MovedInCargo(), InventoryItem::OnRightClick(), Container::SetLock(), and WriteToContext().
GetSlot()
InventoryLocation::GetSlot () private
returns slot id if current type is Attachment
@NOTE: slot id is related to order of entries in DZ/data/config.cpp secton CfgSlots
Returns
slot id if attachment, -1 otherwise
Referenced by ActionLockAttachment::ActionCondition(), ActionRepairCarPart::ActionCondition(), ActionAttachToConstruction::ActionCondition(), AttachmentCategoriesRow::CanCombine(), InventoryItemSuper::CanDetachAttachment(), CanForceSwapEntitiesEx(), CanReleaseAttachment(), CanSwapEntitiesEx(), AttachmentCategoriesRow::Combine(), CreateInInventory(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), DestroyMaterialsServer(), ZombieContainer::DoubleClick(), DropNonUsableMaterialsServer(), DumpToString(), InventoryItem::EEDelete(), InventoryItem::EEItemLocationChanged(), GetCurrentAttachmentSlotInfo(), InventoryItem::GetQuantityMax(), ItemBase::GetSlotLockedState(), ItemBase::IsAttachmentSlotLocked(), ItemBase::LockAttachmentSlot(), LockServer(), InventoryItem::LockToParent(), Icon::MouseClick(), Container::MoveContainerDown(), Container::MoveContainerUp(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), BotStateBase::OnEntry(), WeaponStateBase::OnEntry(), ActionRemoveSeed::OnExecute(), ActionTakeHybridAttachment::OnExecuteClient(), ActionTakeItem::OnExecuteClient(), ActionAttachPowerSourceToPanel::OnExecuteImpl(), ActionTakeHybridAttachment::OnExecuteServer(), ActionTakeItem::OnExecuteServer(), OnFinishProgressServer(), BotStateBase::OnUpdate(), HumanInventory::RedirectToHandEvent(), Attachments::Select(), AttachmentCategoriesRow::Select(), SetLockOnAttachedMaterials(), SlotToAnimType(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), PluginBase::SpawnEntityInInventory(), HumanInventory::SwappingToPreviousLocation(), ClosableContainer::TakeAsAttachment(), EntityAI::TakeEntityToTargetAttachmentImpl(), TakeMaterialsServer(), SplitItemUtils::TakeOrSplitToInventory(), PlayerContainer::ToggleContainer(), InventoryItem::UnlockFromParent(), UnlockServer(), ItemBase::UpdateAttachmentSlot(), PumpkinHelmet::UpdateGlowState(), EntityLightSource::UpdateMode(), WriteToContext(), and InventoryItem::~ItemBase().
GetType()
InventoryLocation::GetType () private
returns type of InventoryLocation
See also
InventoryLocationType for known types of inventory locations
Referenced by ActionTurnOffWhileOnGround::ActionCondition(), ActionTurnOnWhileOnGround::ActionCondition(), CarWheel_Ruined::CanPutAsAttachment(), ImprovisedExplosive::CanReceiveAttachment(), Plastic_Explosive::CanReceiveAttachment(), CreateInInventory(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ItemBase::CreateRope(), Icon::DoubleClick(), DraggingOverCenterPanel(), HumanInventory::DropEntity(), Icon::DropReceivedFromMain(), DumpToString(), InventoryItem::EEDelete(), EEInit(), InventoryItem::EEItemLocationChanged(), HumanInventory::ForceSwapEntities(), GetCurrentAttachmentSlotInfo(), ItemBase::GetViewIndex(), HandGuardBase::GuardCondition(), IsAttachment(), IsCargoInHiearchy(), IsInCargo(), Weapon::IsRemoteWeapon(), ManBase::IsSwapBetweenHandsAndGroundLargeItem(), HumanInventory::LocalDestroyEntity(), LocalDestroyEntity(), OnCenterPanelDropReceived(), VicinityContainer::OnDropReceivedFromIcon(), WeaponStateBase::OnEntry(), BotStateBase::OnUpdate(), ManBase::PredictiveForceSwapEntities(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HumanInventory::RedirectToHandEvent(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), ReplaceItemWithNew(), ItemManager::ShowSourceDropzone(), SlotToAnimType(), InventoryItem::SplitItem(), HumanInventory::SwapEntities(), HumanInventory::SwappingToPreviousLocation(), HumanInventory::TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), SplitItemUtils::TakeOrSplitToInventory(), HumanInventory::ThrowEntity(), ManBase::UpdateDelete(), EntityLightSource::UpdateMode(), WriteToContext(), and InventoryItem::~ItemBase().
IsValid()
InventoryLocation::IsValid () private
verify current set inventory location
Returns
true if valid, false otherwise
Referenced by VicinitySlotsContainer::DoubleClick(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), HandGuardBase::GuardCondition(), Container::MoveContainerDown(), Container::MoveContainerUp(), WeaponStateBase::OnAbort(), OnAbort(), OnCenterPanelDropReceived(), PlayerContainer::OnDropReceivedFromGhostArea(), HandStartAction::OnEntry(), WeaponStateBase::OnExit(), WeaponManager::OnInputUserDataProcess(), OnServerInventoryCommandStatic(), ReplaceWithNewReciveCargoLambda::OnSuccess(), ProccessInputData(), SendServerHandEventViaJuncture(), InventoryItem::SplitItem(), and VicinitySlotsContainer::TransferItem().
ReadFromContext()
bool InventoryLocation::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 281 of file inventorylocation.c.
    {
        EntityAI parent;
        EntityAI item;
        int type = 0;
        int idx = -1;
        int row = -1;
        int col = -1;
        bool flp = false;
        if (!ctx.Read(type))
            return false;
        switch (type)
        {
            case InventoryLocationType.UNKNOWN:
            {
                break;
            }
            case InventoryLocationType.GROUND:
            {
                if (!ctx.Read(item))
                    return false;
                vector pos;
                if (!ctx.Read(pos))
                    return false;
                float dir[4];
                if (!ctx.Read(dir))
                    return false;
                if (!item)
                    break; // item is not in bubble
                SetGroundEx(item, pos, dir);
                break;
            }
            case InventoryLocationType.ATTACHMENT:
            {
                if (!ctx.Read(parent))
                    return false;
                if (!ctx.Read(item))
                    return false;
                int slot;
                if (!ctx.Read(slot))
                    return false;
                if (!parent || !item)
                    break; // parent or item is not in bubble
                SetAttachment(parent, item, slot);
                break;
            }
            case InventoryLocationType.CARGO:
            {
                if (!ctx.Read(parent))
                    return false;
                if (!ctx.Read(item))
                    return false;
                if (!ctx.Read(idx))
                    return false;
                if (!ctx.Read(row))
                    return false;
                if (!ctx.Read(col))
                    return false;
                if (!ctx.Read(flp))
                    return false;
                if (!parent || !item)
                    break; // parent or item is not in bubble
                SetCargo(parent, item, idx, row, col, flp);
                break;
            }
            case InventoryLocationType.HANDS:
            {
                if (!ctx.Read(parent))
                    return false;
                if (!ctx.Read(item))
                    return false;
                if (!parent || !item)
                    break; // parent or item is not in bubble
                SetHands(parent, item);
                break;
            }
            case InventoryLocationType.PROXYCARGO:
            {
                if (!ctx.Read(parent))
                    return false;
                if (!ctx.Read(item))
                    return false;
                if (!ctx.Read(idx))
                    return false;
                if (!ctx.Read(row))
                    return false;
                if (!ctx.Read(col))
                    return false;
                if (!ctx.Read(flp))
                    return false;
                if (!parent || !item)
                    break; // parent or item is not in bubble
                SetProxyCargo(parent, item, idx, row, col, flp);
                break;
            }
            default:
            {
                Error("ReadFromContext - really unknown location type, this should not happen, type=" + type);
                return false;
            }
        }
        return true;
    }
References Error(), Serializer::Read(), SetAttachment(), SetCargo(), SetGroundEx(), SetHands(), and SetProxyCargo().
Referenced by ManBase::HandleRemoteItemManipulation(), WeaponManager::OnInputUserDataProcess(), OnServerInventoryCommandStatic(), ProccessInputData(), HandEventBase::ReadFromContext(), HandEventDrop::ReadFromContext(), WeaponEventBase::ReadFromContext(), FirearmActionAttachMagazine::ReadFromContext(), FirearmActionAttachMagazineQuick::ReadFromContext(), FirearmActionDetachMagazine_Old::ReadFromContext(), and FirearmActionDetachMagazine::ReadFromContext().
Reset()
InventoryLocation::Reset () private
Referenced by InventoryItem::EEItemLocationChanged().
SetAttachment()
InventoryLocation::SetAttachment (notnull EntityAI parent, EntityAI e, int slotId) private
sets current inventory location type to Attachment with slot id set to <slotId>
Parameters
[in] parent parent entity the item <e> will be attached to
[in] e entity with this inventory location (null for new spawns)
[in] slotId slot id where the item will be attached
Referenced by CoverHeadOfTargetPlayerLambda::CoverHeadOfTargetPlayerLambda(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), FoldBandanaToSlotLambda::FoldBandanaToSlotLambda(), FirearmActionAttachMagazine::InventoryReservation(), FirearmActionAttachMagazineQuick::InventoryReservation(), WeaponManager::InventoryReservation(), WeaponStateBase::OnEntry(), ActionAttachWithSwitch::OnExecuteClient(), ActionAttachWithSwitch::OnExecuteServer(), WeaponManager::OnInputUserDataProcess(), OnUpdate(), ReadFromContext(), HumanInventory::TakeEntityAsAttachmentEx(), and TakeEntityAsTargetAttachmentEx().
SetCargo()
InventoryLocation::SetCargo (notnull EntityAI parent, EntityAI e, int idx, int row, int col, bool flip) private
sets current inventory location type to Cargo with coordinates (idx, row, col)
Parameters
[in] parent parent entity that will receive item <e> into cargo
[in] e entity with this inventory location (null for new spawns)
[in] idx index of cargo
[in] row row of the cargo
[in] col column of the cargo
Referenced by InventoryItem::OnRightClick(), ReplaceWithNewReciveCargoLambda::OnSuccess(), ReadFromContext(), HumanInventory::TakeEntityToCargoEx(), and TakeEntityToCargoEx().
SetCargoAuto()
InventoryLocation::SetCargoAuto (notnull CargoBase cargo, EntityAI e, int row, int col, bool flip) private
based on Cargo.IsProxyCargo uses SetProxyCargo or SetCargo respectively
Parameters
[in] cargo cargo that will receive item <e> into cargo
[in] e entity with this inventory location (null for new spawns)
[in] row row of the cargo
[in] col column of the cargo
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), Icon::DropReceivedFromMain(), ManBase::PredictiveTakeEntityToTargetCargoEx(), and TakeEntityToTargetCargoEx().
SetCol()
proto native void InventoryLocation::SetCol (int col) private
SetFlip()
proto native void InventoryLocation::SetFlip (bool flip) private
Referenced by Icon::DropReceivedFromMain(), MakeDstForSwap(), and MakeSrcAndDstForForceSwap().
SetGround()
InventoryLocation::SetGround (EntityAI e, vector mat[4]) private
sets current inventory location type to Ground with transformation mat
Parameters
[in] e entity with this inventory location (null for new spawns)
[in] mat transformation matrix
Referenced by ChainedDropAndKillPlayerLambda(), DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), DestroyItemInCorpsesHandsAndCreateNewOnGndLambda::DestroyItemInCorpsesHandsAndCreateNewOnGndLambda(), DropNonUsableMaterialsServer(), FireplaceToIndoorOvenLambda(), FireplaceToIndoorsLambda(), DayZPlayerUtils::HandleDropMagazine(), InventoryItem::OnRightClick(), ManBase::PredictiveDropEntity(), ReplaceItemWithNewLambdaBase::PrepareLocations(), ManBase::SpawnEntityOnGroundPos(), and ActionUncoverHeadBase::UncoverHead().
SetGroundEx()
InventoryLocation::SetGroundEx (EntityAI e, vector pos, float dir[4]) private
sets current inventory location type to Ground with transformation mat
Parameters
[in] e entity with this inventory location (null for new spawns)
[in] pos position vector
[in] dir direction quat
Referenced by ActionRepackTentCB::DropDuringRepacking(), DropNonUsableMaterialsServer(), ActionDeployBase::MoveEntityToFinalPosition(), ActionActivateTrap::OnFinishProgressServer(), ReplaceItemWithNewLambdaBase::PrepareLocations(), ReadFromContext(), and ThrowEntityFromInventory().
SetHands()
InventoryLocation::SetHands (notnull EntityAI parent, EntityAI e) private
sets current inventory location type to Hands
Parameters
[in] parent parent entity the item <e> will be attached to. this'd better be inherited from Person
[in] e entity with this inventory location (null for new spawns)
Referenced by ActionManagerClient::ActionManagerClient(), CommandHandlerDebug(), EmoteManager(), HandEventBase::GetDst(), HandEvent(), ActionManagerClient::HasHandInventoryReservation(), InventoryReservation(), FirearmActionAttachMagazine::InventoryReservation(), FirearmActionAttachMagazineQuick::InventoryReservation(), OnEndServer(), ActionRemoveSeed::OnExecute(), ActionTakeItemToHands::OnExecute(), ManBase::OnQuickBarSingleUse(), WeaponManager::OnWeaponActionEnd(), ReadFromContext(), RepackLambda::RepackLambda(), RestrainTargetPlayerLambda(), SetEmoteLockState(), EntityAI::TakeEntityToHandsImpl(), and UngagSelfLambda::UngagSelfLambda().
SetIndex()
proto native void InventoryLocation::SetIndex (int idx) private
SetItem()
InventoryLocation::SetItem (notnull EntityAI item) private
brief sets current inventory location's item
Referenced by WeaponStateBase::OnEntry().
SetParent()
InventoryLocation::SetParent (notnull EntityAI parent) private
brief sets current inventory location's GetParent
Referenced by TransferInventory().
SetProxyCargo()
InventoryLocation::SetProxyCargo (notnull EntityAI parent, EntityAI e, int idx, int row, int col, bool flip) private
sets current inventory location type to ProxyCargo with coordinates (idx, row, col) @NOTE: typical usage is in building-like dummy structures, where furniture with cargo is part of the model, and is not a physical entity (like person or bag).
Parameters
[in] parent parent entity that will receive item <e> into proxy cargo
[in] e entity with this inventory location (null for new spawns)
[in] idx index of cargo
[in] row row of the cargo
[in] col column of the cargo
Referenced by ReadFromContext().
SetRow()
proto native void InventoryLocation::SetRow (int row) private
SetSlot()
proto native void InventoryLocation::SetSlot (int slotId) private
WriteToContext()
bool InventoryLocation::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 397 of file inventorylocation.c.
    {
        if (!ctx.Write(GetType()))
        {
            Error("InventoryLocation::WriteToContext - cannot write to context! failed to write type");
            return false;
        }
        switch (GetType())
        {
            case InventoryLocationType.UNKNOWN:
            {
                break;
            }
            case InventoryLocationType.GROUND:
            {
                if (!ctx.Write(GetItem()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed GND, arg=item");
                    return false;
                }
                vector pos = GetPos();
                if (!ctx.Write(pos))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed GND, arg=pos");
                    return false;
                }
                float dir[4];
                GetDir(dir);
                if (!ctx.Write(dir))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed GND, arg=dir");
                    return false;
                }
                break;
            }
            case InventoryLocationType.ATTACHMENT:
            {
                if (!ctx.Write(GetParent()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed ATT, arg=parent");
                    return false;
                }
                if (!ctx.Write(GetItem()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed ATT, arg=item");
                    return false;
                }
                if (!ctx.Write(GetSlot()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed ATT, arg=slot");
                    return false;
                }
                break;
            }
            case InventoryLocationType.CARGO:
            {
                if (!ctx.Write(GetParent()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=parent");
                    return false;
                }
                if (!ctx.Write(GetItem()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=item");
                    return false;
                }
                if (!ctx.Write(GetIdx()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=idx");
                    return false;
                }
                if (!ctx.Write(GetRow()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=row");
                    return false;
                }
                if (!ctx.Write(GetCol()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=col");
                    return false;
                }
                if (!ctx.Write(GetFlip()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed CGO, arg=flp");
                    return false;
                }
                break;
            }
            case InventoryLocationType.HANDS:
            {
                if (!ctx.Write(GetParent()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed HND, arg=parent");
                    return false;
                }
                if (!ctx.Write(GetItem()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed HND, arg=item");
                    return false;
                }
                break;
            }
            case InventoryLocationType.PROXYCARGO:
            {
                if (!ctx.Write(GetParent()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=parent");
                    return false;
                }
                if (!ctx.Write(GetItem()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=item");
                    return false;
                }
                if (!ctx.Write(GetIdx()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=idx");
                    return false;
                }
                if (!ctx.Write(GetRow()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=row");
                    return false;
                }
                if (!ctx.Write(GetCol()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=col");
                    return false;
                }
                if (!ctx.Write(GetFlip()))
                {
                    Error("InventoryLocation::WriteToContext - cannot write to context! failed PXY, arg=flp");
                    return false;
                }
                break;
            }
            default:
            {
                Error("WriteToContext - really unknown location type, this should not happen, type=" + GetType());
                return false;
            }
        }
        return true;
    }
References Error(), GetCol(), GetDir(), GetFlip(), GetIdx(), GetItem(), GetParent(), GetPos(), GetRow(), GetSlot(), GetType(), and Serializer::Write().
Referenced by InventoryItem::OnRightClick(), OptionalLocationWriteToContext(), ProccessInputData(), WeaponManager::Synchronize(), and WeaponEventBase::WriteToContext().