DayzKode: array Class Reference
array Class Reference
Result for an object found in CGame.IsBoxCollidingGeometryProxy.
Private Member Functions
void AddElement (int index, Widget parent, Input input)
void AddSubgroup (int sort_index, Widget parent, Input input)
void Apply ()
void CancelEnteringAlternateKeybind ()
void CancelEnteringKeybind ()
void ClearAlternativeKeybind (int key_index)
void ClearKeybind (int key_index)
void CreateSubgroups (Widget parent, Input input)
string GetLayoutName ()
string GetTest ()
string GetTestEx ()
bool IsChanged ()
is anything changed?
bool IsEnteringKeyBind ()
void KeybindingsContainer (int index, Input input, Widget parent, KeybindingsMenu menu)
void OnSelectKBPreset (int index)
void ParticleProperties (vector localPos, int flags, Object parent=null, vector localOri=vector.Zero, Class owner=null)
Constructor (ctor)
void ReloadElements ()
void Reset (bool forced=false)
TFResult Run (float dt)
void StartEnteringAlternateKeybind (int key_index)
void StartEnteringKeybind (int key_index)
void SwitchSubgroup (int index)
void TFCaller (Class instance, string test, TFResult result)
void Update (float timeslice)
void ~ParticleProperties ()
dtor
Data access
Methods to retrieve the data in script
proto Object GetParent ()
proto Class GetOwner ()
proto vector GetLocalPos ()
proto vector GetLocalOri ()
proto int GetPPFlags ()
proto bool IsPlayOnCreation ()
proto bool IsForceWorldRotation ()
proto bool IsKeepParentOnEnd ()
Private Attributes
ref ComponentInfoArray componentInfo
Either the first component found or all of them depending on "fullComponentInfo".
int geomLevel
What geometry was the object found in (will either be primaryType or secondaryType)
int hierLevel
How deep in the proxy hierarchy are we.
protected int m_CurrentSettingAlternateKeyIndex = -1
protected int m_CurrentSettingKeyIndex = -1
private Class m_Instance
protected ref map< int, ref ElementArray > m_KeyWidgetElements
protected KeybindingsMenu m_Menu
private ref TFResult m_Result
protected Widget m_Root
protected ScrollWidget m_Scroll
protected ref array< Widget > m_Subgroups
private string m_Test
protected const int NO_SORTING = -1
Object obj
Object inside of box.
Object parent
Parent of proxy object.
ref ProxyInfoArray proxyInfo
Either the first proxy found or all of them depending on "fullComponentInfo".
Detailed Description
Result for an object found in CGame.IsBoxCollidingGeometryProxy.
Properties while creating a ParticleSource.
Definition at line 27 of file isboxcollidinggeometryproxyclasses.c.
Constructor & Destructor Documentation
~ParticleProperties()
void array::~ParticleProperties () inline private
dtor
Definition at line 83 of file particlesource.c.
    {
    }
Member Function Documentation
AddElement()
void array::AddElement (int index, Widget parent, Input input) inline private
Definition at line 100 of file keybindingscontainer.c.
    {
        //create array if needed
        if (!m_KeyWidgetElements.Get(index))
        {
            ElementArray elements = new ElementArray;
            m_KeyWidgetElements.Insert( index, elements );
        }
        KeybindingElementNew element = new KeybindingElementNew( index, parent, this );
        m_KeyWidgetElements.Get(index).Insert(element);
    }
References ScriptedWidgetEventHandler::KeybindingElementNew().
AddSubgroup()
void array::AddSubgroup (int sort_index, Widget parent, Input input) inline private
Definition at line 55 of file keybindingscontainer.c.
    {
        Widget subgroup             = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/options/keybindings_selectors/keybinding_subgroup.layout", parent );
        Widget subgroup_content     = subgroup.FindAnyWidget( "subgroup_content" );
        TIntArray input_actions;
        if (sort_index != NO_SORTING)
        {
            input_actions = InputUtils.GetInputActionSortingMap().Get(sort_index);
        }
        else
        {
            input_actions = InputUtils.GetUnsortedInputActions();
        }
        for (int i = 0; i < input_actions.Count(); i++)
        {
            AddElement( input_actions[i], subgroup_content, input );
        }
        m_Subgroups.Insert(subgroup);
        subgroup_content.Update();
    }
References ScriptedWidgetEventHandler::AddElement(), WorkspaceWidget::CreateWidgets(), GetGame(), InputUtils::GetInputActionSortingMap(), InputUtils::GetUnsortedInputActions(), and CGame::GetWorkspace().
Apply()
void array::Apply () inline private
Definition at line 182 of file keybindingscontainer.c.
    {
        UAInputAPI ua_api   = GetUApi();
        int input_index = 0;
        foreach (ElementArray elements : m_KeyWidgetElements)
        {
            foreach (int element_index, KeybindingElementNew element : elements)
            {
                if (element_index == 0)
                {
                    UAInput input = ua_api.GetInputByID( m_KeyWidgetElements.GetKey(input_index) );
                    int i;
                    if ( element.IsChanged() )
                    {
                        array<int> new_keys     = element.GetChangedBinds();
                        input.ClearDeviceBind(EUAINPUT_DEVICE_KEYBOARDMOUSE);
                        if ( new_keys.Count() > 0 )
{
                            input.BindComboByHash( new_keys.Get( 0 ) );
                            for( i = 1; i < new_keys.Count(); i++ )
{
                                input.BindComboByHash( new_keys.Get( i ) );
                            }
                        }
                    }
                    if ( element.IsAlternateChanged() )
                    {
                        array<int> new_alt_keys = element.GetChangedAlternateBinds();
                        if ( input.AlternativeCount() == 0 )
{
                            input.AddAlternative();
                        }
                        input.ClearDeviceBind(EUAINPUT_DEVICE_CONTROLLER);
                        if ( new_alt_keys.Count() > 0 )
{
                            input.BindComboByHash( new_alt_keys.Get( 0 ) );
                            for( i = 1; i < new_alt_keys.Count(); i++ )
{
                                input.BindComboByHash( new_alt_keys.Get( i ) );
                            }
                        }
                    }
                }
                element.Reload();
            }
            input_index++;
        }
    }
References UAInput::AddAlternative(), UAInput::AlternativeCount(), UAInput::BindComboByHash(), UAInput::ClearDeviceBind(), UAInputAPI::GetInputByID(), and GetUApi().
CancelEnteringAlternateKeybind()
void array::CancelEnteringAlternateKeybind () inline private
Definition at line 154 of file keybindingscontainer.c.
    {
        if ( m_CurrentSettingAlternateKeyIndex != -1 )
        {
            foreach (KeybindingElementNew element : m_KeyWidgetElements.Get( m_CurrentSettingAlternateKeyIndex ))
            {
                element.CancelEnteringKeybind();
            }
            m_CurrentSettingAlternateKeyIndex = -1;
        }
    }
CancelEnteringKeybind()
void array::CancelEnteringKeybind () inline private
Definition at line 135 of file keybindingscontainer.c.
    {
        if ( m_CurrentSettingKeyIndex != -1 )
        {
            foreach (KeybindingElementNew element : m_KeyWidgetElements.Get( m_CurrentSettingKeyIndex ))
            {
                element.CancelEnteringKeybind();
            }
            m_CurrentSettingKeyIndex = -1;
        }
    }
ClearAlternativeKeybind()
void array::ClearAlternativeKeybind (int key_index) inline private
Definition at line 123 of file keybindingscontainer.c.
    {
        m_Menu.ClearAlternativeKeybind( key_index );
    }
References m_Menu.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonUp().
ClearKeybind()
void array::ClearKeybind (int key_index) inline private
Definition at line 118 of file keybindingscontainer.c.
    {
        m_Menu.ClearKeybind( key_index );
    }
References m_Menu.
Referenced by ScriptedWidgetEventHandler::OnMouseButtonUp().
CreateSubgroups()
void array::CreateSubgroups (Widget parent, Input input) inline private
Definition at line 80 of file keybindingscontainer.c.
    {
        m_Subgroups = new array<Widget>;
        int sort_count = InputUtils.GetInputActionSortingMap().Count();
        for (int i = 0; i < sort_count; i++)
        {
            if (InputUtils.GetInputActionSortingMap().GetElement(i) && InputUtils.GetInputActionSortingMap().GetElement(i).Count() > 0)
            {
                AddSubgroup(InputUtils.GetInputActionSortingMap().GetKey(i),parent,input);
            }
        }
        //any unssorted inputs go here
        if (InputUtils.GetUnsortedInputActions() && InputUtils.GetUnsortedInputActions().Count() > 0)
        {
            AddSubgroup(NO_SORTING,parent,input);
        }
    }
References ScriptedWidgetEventHandler::AddSubgroup(), InputUtils::GetInputActionSortingMap(), and InputUtils::GetUnsortedInputActions().
GetLayoutName()
string array::GetLayoutName () inline private
Definition at line 31 of file keybindingscontainer.c.
    {
        return "gui/layouts/new_ui/options/keybindings_selectors/keybinding_container.layout";
    }
GetLocalOri()
proto vector array::GetLocalOri () private
GetLocalPos()
proto vector array::GetLocalPos () private
GetOwner()
proto Class array::GetOwner () private
GetParent()
proto Object array::GetParent () private
GetPPFlags()
proto int array::GetPPFlags () private
GetTest()
string array::GetTest () inline private
Definition at line 70 of file testframework.c.
    {
        return m_Test;
    }
GetTestEx()
string array::GetTestEx () inline private
Definition at line 75 of file testframework.c.
    {
        return string.Format("%1::%2", m_Instance.ClassName(), m_Test);
    }
References string::Format(), and m_Instance.
IsChanged()
bool array::IsChanged () inline private
is anything changed?
Definition at line 167 of file keybindingscontainer.c.
    {
        foreach (ElementArray elements : m_KeyWidgetElements)
        {
            foreach (KeybindingElementNew element : elements)
            {
                if (element.IsChanged() || element.IsAlternateChanged())
                {
                    return true;
                }
            }
        }
        return false;
    }
IsEnteringKeyBind()
bool array::IsEnteringKeyBind () inline private
Definition at line 113 of file keybindingscontainer.c.
    {
        return ( m_CurrentSettingKeyIndex != -1 || m_CurrentSettingAlternateKeyIndex != -1 );
    }
IsForceWorldRotation()
proto bool array::IsForceWorldRotation () private
IsKeepParentOnEnd()
proto bool array::IsKeepParentOnEnd () private
IsPlayOnCreation()
proto bool array::IsPlayOnCreation () private
KeybindingsContainer()
void array::KeybindingsContainer (int index, Input input, Widget parent, KeybindingsMenu menu) inline private
Definition at line 15 of file keybindingscontainer.c.
    {
        m_KeyWidgetElements = new map<int, ref ElementArray>;
        m_Menu          = menu;
        m_Root  = GetGame().GetWorkspace().CreateWidgets( GetLayoutName(), parent );
        m_Scroll = ScrollWidget.Cast(m_Root.FindAnyWidget("group_scroll"));
        Widget container    = m_Root.FindAnyWidget( "group_scroll" );
        CreateSubgroups(container,input);
        container.Update();
        m_Root.SetHandler( this );
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), ScriptedWidgetEventHandler::GetLayoutName(), CGame::GetWorkspace(), m_Menu, and m_Root.
OnSelectKBPreset()
void array::OnSelectKBPreset (int index) inline private
Definition at line 36 of file keybindingscontainer.c.
    {
        GetUApi().PresetSelect( index );
        ReloadElements();
        GetUApi().Export();
        GetUApi().SaveInputPresetMiscData();
    }
References UAInputAPI::Export(), GetUApi(), UAInputAPI::PresetSelect(), and UAInputAPI::SaveInputPresetMiscData().
ParticleProperties()
void array::ParticleProperties (vector localPos, int flags, Object parent = null, vector localOri = vector.Zero, Class owner = null) inline private
Constructor (ctor)
Parameters
localPos vector Local position of particle, if no parent this is world position
flags int See ParticlePropertiesFlags
parent Object The parent that the ParticleSource will be added to as a child
localOri vector Local orientation of particle, if no parent this is world orientation
owner Class The owning instance for this particle, as long as it exists, this particle will not be reused (unless flagged) Important when for example virtual is enabled since if the particle owner has been deleted, the virtual should not be converted Only fill in owner if necessary, for example when the owner is reusing the same particle after storing it
Definition at line 78 of file particlesource.c.
    {
    }
ReloadElements()
void array::ReloadElements () inline private
Definition at line 44 of file keybindingscontainer.c.
    {
        foreach ( ElementArray elements : m_KeyWidgetElements )
        {
            foreach (KeybindingElementNew element : elements)
            {
                element.Reload();
            }
        }
    }
Reset()
void array::Reset (bool forced = false) inline private
Definition at line 236 of file keybindingscontainer.c.
    {
        foreach ( ElementArray elements : m_KeyWidgetElements )
        {
            foreach (KeybindingElementNew element : elements)
            {
                if ( element.IsChanged() || element.IsAlternateChanged() || forced )
                {
                    element.Reload();
                }
            }
        }
    }
Run()
TFResult array::Run (float dt) inline private
Definition at line 58 of file testframework.c.
    {
        bool callResult = GetGame().GameScript.CallFunction(m_Instance, m_Test, m_Result, dt);
        if (!callResult)
        {
            ErrorEx(string.Format("Failed to call function \'%1\' on \'%2\'", m_Test, m_Instance.GetDebugName()));
            m_Result.Result = TFR.FAIL;
        }
        return m_Result;
    }
References ScriptModule::CallFunction(), ErrorEx, CGame::GameScript, GetGame(), and m_Instance.
Referenced by AreaDamageBase::EvaluateDamage_Loop().
StartEnteringAlternateKeybind()
void array::StartEnteringAlternateKeybind (int key_index) inline private
Definition at line 147 of file keybindingscontainer.c.
    {
        m_CurrentSettingKeyIndex            = -1;
        m_CurrentSettingAlternateKeyIndex   = key_index;
        m_Menu.StartEnteringAlternateKeybind( key_index );
    }
References m_Menu.
StartEnteringKeybind()
void array::StartEnteringKeybind (int key_index) inline private
Definition at line 128 of file keybindingscontainer.c.
    {
        m_CurrentSettingAlternateKeyIndex   = -1;
        m_CurrentSettingKeyIndex            = key_index;
        m_Menu.StartEnteringKeybind( key_index );
    }
References m_Menu.
SwitchSubgroup()
void array::SwitchSubgroup (int index) inline private
Definition at line 295 of file keybindingscontainer.c.
    {
        Widget w;
        for (int i = 0; i < m_Subgroups.Count(); i++)
        {
            w = m_Subgroups[i];
            w.Show(index == i);
        }
        m_Scroll.VScrollToPos01(0);
    }
TFCaller()
void array::TFCaller (Class instance, string test, TFResult result) inline private
Definition at line 51 of file testframework.c.
    {
        m_Instance  = instance;
        m_Test      = test;
        m_Result    = result;
    }
References m_Instance.
Update()
void array::Update (float timeslice) inline private
Definition at line 250 of file keybindingscontainer.c.
    {
        if ( m_CurrentSettingKeyIndex != -1 || m_CurrentSettingAlternateKeyIndex != -1 )
        {
            UAInputAPI ua_api = GetUApi();
            if ( ua_api.DeterminePressedButton() != 0 )
            {
                string name;
                string text;
                ref array<int> new_keybinds = new array<int>;
                // remove previous backlit
                GetDayZGame().GetBacklit().KeybindingClear();
                for( int i = 0; i < ua_api.DeterminedCount(); ++i )
                {
                    int kb_id = ua_api.GetDetermined( i );
                    new_keybinds.Insert( kb_id );
                    // light up specific key
                    GetDayZGame().GetBacklit().KeybindingShow(kb_id);
                }
                if ( m_CurrentSettingKeyIndex != -1 )
                {
                    m_Menu.ConfirmKeybindEntry( new_keybinds );
                    foreach (KeybindingElementNew element : m_KeyWidgetElements.Get( m_CurrentSettingKeyIndex ))
                    {
                        element.Reload( new_keybinds, false );
                    }
                    m_CurrentSettingKeyIndex = -1;
                }
                else if ( m_CurrentSettingAlternateKeyIndex != -1 )
                {
                    m_Menu.ConfirmAlternateKeybindEntry( new_keybinds );
                    foreach (KeybindingElementNew elementAlternate : m_KeyWidgetElements.Get( m_CurrentSettingAlternateKeyIndex ))
                    {
                        elementAlternate.Reload( new_keybinds, true );
                    }
                    m_CurrentSettingAlternateKeyIndex = -1;
                }
            }
        }
    }
References UAInputAPI::DeterminedCount(), UAInputAPI::DeterminePressedButton(), GetDayZGame(), UAInputAPI::GetDetermined(), GetUApi(), m_Menu, and name.
Referenced by SymptomManager::UpdateActiveSymptoms().
Member Data Documentation
componentInfo
ref ComponentInfoArray array::componentInfo private
Either the first component found or all of them depending on "fullComponentInfo".
Definition at line 35 of file isboxcollidinggeometryproxyclasses.c.
geomLevel
int array::geomLevel private
What geometry was the object found in (will either be primaryType or secondaryType)
Definition at line 33 of file isboxcollidinggeometryproxyclasses.c.
hierLevel
int array::hierLevel private
How deep in the proxy hierarchy are we.
Definition at line 32 of file isboxcollidinggeometryproxyclasses.c.
m_CurrentSettingAlternateKeyIndex
protected int array::m_CurrentSettingAlternateKeyIndex = -1 private
Definition at line 11 of file keybindingscontainer.c.
m_CurrentSettingKeyIndex
protected int array::m_CurrentSettingKeyIndex = -1 private
Definition at line 10 of file keybindingscontainer.c.
m_Instance
private Class array::m_Instance private
Definition at line 47 of file testframework.c.
m_KeyWidgetElements
protected ref map<int, ref ElementArray> array::m_KeyWidgetElements private
Definition at line 9 of file keybindingscontainer.c.
m_Menu
protected KeybindingsMenu array::m_Menu private
Definition at line 6 of file keybindingscontainer.c.
m_Result
private ref TFResult array::m_Result private
Definition at line 49 of file testframework.c.
m_Root
protected Widget array::m_Root private
Definition at line 5 of file keybindingscontainer.c.
m_Scroll
protected ScrollWidget array::m_Scroll private
Definition at line 7 of file keybindingscontainer.c.
m_Subgroups
protected ref array<Widget> array::m_Subgroups private
Definition at line 13 of file keybindingscontainer.c.
m_Test
private string array::m_Test private
Definition at line 48 of file testframework.c.
NO_SORTING
protected const int array::NO_SORTING = -1 private
Definition at line 4 of file keybindingscontainer.c.
obj
Object array::obj private
Object inside of box.
Definition at line 29 of file isboxcollidinggeometryproxyclasses.c.
Referenced by OnEndServer(), TrapBase::OnSteppedOn(), and Hud::RefreshPlayerTags().
parent
Object array::parent private
Parent of proxy object.
Definition at line 30 of file isboxcollidinggeometryproxyclasses.c.
proxyInfo
ref ProxyInfoArray array::proxyInfo private
Either the first proxy found or all of them depending on "fullComponentInfo".
Definition at line 36 of file isboxcollidinggeometryproxyclasses.c.