DayzKode: AmmoTypesAPI Class Reference
AmmoTypesAPI Class Reference
Private Member Functions
private void AmmoTypesAPI ()
private void ~AmmoTypesAPI ()
Static Private Member Functions
static proto bool Exists (string ammoType)
Check if ammoType exists (registered in cfgAmmoTypes)
static proto bool GetAmmoType (string magazineType, out string ammoType)
Get the default ammoType of a magazine.
static bool MagazineTypeToAmmoType (string magazineType, out string ammoType)
Helper method.
Detailed Description
Definition at line 1 of file ammotypes.c.
Constructor & Destructor Documentation
AmmoTypesAPI()
private void AmmoTypesAPI::AmmoTypesAPI () inline private
Definition at line 3 of file ammotypes.c.
{}
~AmmoTypesAPI()
private void AmmoTypesAPI::~AmmoTypesAPI () inline private
Definition at line 4 of file ammotypes.c.
{}
Member Function Documentation
Exists()
static proto bool AmmoTypesAPI::Exists (string ammoType) static private
Check if ammoType exists (registered in cfgAmmoTypes)
Referenced by MagazineTypeToAmmoType().
GetAmmoType()
static proto bool AmmoTypesAPI::GetAmmoType (string magazineType, out string ammoType) static private
Get the default ammoType of a magazine.
Referenced by MagazineTypeToAmmoType().
MagazineTypeToAmmoType()
static bool AmmoTypesAPI::MagazineTypeToAmmoType (string magazineType, out string ammoType) inline static private
Helper method.
Definition at line 12 of file ammotypes.c.
    {
        if ( !AmmoTypesAPI.Exists(magazineType) )
        {
            if ( !AmmoTypesAPI.GetAmmoType(magazineType, ammoType) )
            {
                ErrorEx(string.Format("%1 is not a magazineType or ammoType or has no default 'ammo' set up in config.", magazineType));
                return false;
            }
            return true;
        }
        else
        {
            // This is already an ammoType
            ammoType = magazineType;
            return true;
        }
    }
References ErrorEx, Exists(), and GetAmmoType().
Referenced by Weapon::FillChamber(), and Weapon::FillInnerMagazine().