DayzKode: AbstractWave Class Reference
AbstractWave Class Reference
Private Member Functions
void AbstractWave ()
proto float GetCurrPosition ()
Current position in percentage of total length.
AbstractWaveEvents GetEvents ()
proto float GetFrequency ()
proto float GetLength ()
WARNING: Blocking! Waits for header to load.
proto Managed GetUserData ()
proto float GetVolume ()
private void InitEvents ()
proto bool IsHeaderLoaded ()
proto void Loop (bool setLoop)
void OnEnd ()
void OnHeaderLoad ()
void OnLoad ()
void OnPlay ()
void OnStop ()
proto void Play ()
void PlayWithOffset (float offset)
proto void Restart ()
proto void SetFadeInFactor (float volume)
proto void SetFadeOutFactor (float volume)
proto void SetFrequency (float value)
proto void SetPosition (vector position)
proto void SetStartOffset (float offset)
proto void SetUserData (Managed inst)
proto void SetVolume (float value)
proto void SetVolumeRelative (float value)
proto void Skip (float timeSec)
proto void Stop ()
Detailed Description
Definition at line 90 of file sound.c.
Constructor & Destructor Documentation
AbstractWave()
void AbstractWave::AbstractWave () inline private
Definition at line 102 of file sound.c.
{ InitEvents(); }
References InitEvents().
Member Function Documentation
GetCurrPosition()
proto float AbstractWave::GetCurrPosition () private
Current position in percentage of total length.
GetEvents()
AbstractWaveEvents AbstractWave::GetEvents () inline private
Definition at line 135 of file sound.c.
    {
        return AbstractWaveEvents.Cast(GetUserData());
    }
References GetUserData().
Referenced by OnEnd(), OnHeaderLoad(), OnLoad(), OnPlay(), OnStop(), EffectSound::SoundPlayEx(), and EffectSound::ValidateSoundWave().
GetFrequency()
proto float AbstractWave::GetFrequency () private
GetLength()
proto float AbstractWave::GetLength () private
WARNING: Blocking! Waits for header to load.
Referenced by OnTick(), ManBase::OnVoiceEventPlayback(), and EffectSound::ValidateSoundWave().
GetUserData()
proto Managed AbstractWave::GetUserData () private
Referenced by GetEvents(), and Play().
GetVolume()
proto float AbstractWave::GetVolume () private
InitEvents()
private void AbstractWave::InitEvents () inline private
Definition at line 92 of file sound.c.
    {
        AbstractWaveEvents events = new AbstractWaveEvents();
        SetUserData(events);
    }
References SetUserData().
Referenced by AbstractWave().
IsHeaderLoaded()
proto bool AbstractWave::IsHeaderLoaded () private
Referenced by EffectSound::SoundPlayEx().
Loop()
proto void AbstractWave::Loop (bool setLoop) private
Referenced by MissionBase::PlayMusic(), EffectSound::SetSoundLoop(), and SoftStop().
OnEnd()
void AbstractWave::OnEnd () inline private
Definition at line 160 of file sound.c.
    {
        GetEvents().Event_OnSoundWaveEnded.Invoke(this);
    }
References GetEvents().
OnHeaderLoad()
void AbstractWave::OnHeaderLoad () inline private
Definition at line 155 of file sound.c.
    {
        GetEvents().Event_OnSoundWaveHeaderLoaded.Invoke(this);
    }
References GetEvents().
OnLoad()
void AbstractWave::OnLoad () inline private
Definition at line 150 of file sound.c.
    {
        GetEvents().Event_OnSoundWaveLoaded.Invoke(this);
    }
References GetEvents().
OnPlay()
void AbstractWave::OnPlay () inline private
Definition at line 140 of file sound.c.
    {
        GetEvents().Event_OnSoundWaveStarted.Invoke(this);
    }
References GetEvents().
OnStop()
void AbstractWave::OnStop () inline private
Definition at line 145 of file sound.c.
    {
        GetEvents().Event_OnSoundWaveStopped.Invoke(this);
    }
References GetEvents().
Play()
proto void AbstractWave::Play () private
Referenced by MissionBase::PlayMusic(), and PlayWithOffset().
PlayWithOffset()
void AbstractWave::PlayWithOffset (float offset) inline private
Definition at line 110 of file sound.c.
    {
        Play();
        SetStartOffset(offset);
    }
References Play(), and SetStartOffset().
Restart()
proto void AbstractWave::Restart () private
SetFadeInFactor()
proto void AbstractWave::SetFadeInFactor (float volume) private
SetFadeOutFactor()
proto void AbstractWave::SetFadeOutFactor (float volume) private
SetFrequency()
proto void AbstractWave::SetFrequency (float value) private
SetPosition()
proto void AbstractWave::SetPosition (vector position) private
Referenced by OnTick(), DayZCreature::PlaySound(), EntityAI::PlaySound(), and PosUpdate().
SetStartOffset()
proto void AbstractWave::SetStartOffset (float offset) private
Referenced by HandleView(), and PlayWithOffset().
SetUserData()
proto void AbstractWave::SetUserData (Managed inst) private
Referenced by InitEvents().
SetVolume()
proto void AbstractWave::SetVolume (float value) private
SetVolumeRelative()
proto void AbstractWave::SetVolumeRelative (float value) private
Referenced by HandleView(), PlayerSoundEventBase::OnPlay(), EffectSound::SetSoundMaxVolume(), EffectSound::SetSoundVolume(), EffectSound::SoundReset(), and EffectSound::ValidateSoundWave().
Skip()
proto void AbstractWave::Skip (float timeSec) private
Stop()
proto void AbstractWave::Stop () private
Referenced by EffectSound::Event_OnFrameUpdate(), DayZInfected::OnSoundVoiceEvent(), EffectSound::SoundReset(), EffectSound::SoundStop(), Stop(), SoundEventBase::Stop(), MissionBase::StopMusic(), EffectSound::ValidateSoundWave(), ~InfectedSoundEventBase(), and SoundEventBase::~SoundEventBase().