DayzKode: ActionFillBottleBase Class Reference
ActionFillBottleBase Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionFillBottleBase ()
override void CreateConditionComponents ()
int GetLiquidType (PlayerBase player, ActionTarget target, ItemBase item)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
void SetupStance (PlayerBase player)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Private Attributes
private const float WATER_DEPTH = 0.5
Detailed Description
Definition at line 21 of file actionfillbottlebase.c.
Constructor & Destructor Documentation
ActionFillBottleBase()
void ActionFillBottleBase::ActionFillBottleBase () inline private
Definition at line 25 of file actionfillbottlebase.c.
    {
        m_CallbackClass = ActionFillBottleBaseCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEPOND;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_Text = "#fill";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionFillBottleBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 41 of file actionfillbottlebase.c.
    {
        if ( item.IsFullQuantity() )
            return false;
        if ( GetGame().IsServer() && GetGame().IsMultiplayer() )
            return true;
        if ( GetLiquidType( player,target,item ) != -1 && !player.IsPlacingLocal() )
            return true;
        /*if ( item.GetQuantity() < item.GetQuantityMax() )
            return true;
        */
        return false;
    }
References GetGame(), and GetLiquidType().
ActionConditionContinue()
override bool ActionFillBottleBase::ActionConditionContinue (ActionData action_data) inline private
Definition at line 55 of file actionfillbottlebase.c.
    {
        return ( action_data.m_MainItem.GetQuantity() < action_data.m_MainItem.GetQuantityMax() );
    }
References ActionData::m_MainItem.
CreateConditionComponents()
override void ActionFillBottleBase::CreateConditionComponents () inline private
Definition at line 35 of file actionfillbottlebase.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursorNoObject(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetLiquidType()
int ActionFillBottleBase::GetLiquidType (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 126 of file actionfillbottlebase.c.
    {
        vector pos_cursor = target.GetCursorHitPos();
        CCTWaterSurface waterCheck = new CCTWaterSurface(UAMaxDistances.DEFAULT, UAWaterType.FRESH);
        if ( ( waterCheck.Can(player, target) || (target.GetObject() && target.GetObject().IsWell()) ) && Liquid.CanFillContainer(item, LIQUID_WATER ) )
        {
            return LIQUID_WATER;
        }
        else if ( target.GetObject() && target.GetObject().IsFuelStation() && Liquid.CanFillContainer(item, LIQUID_GASOLINE ) )
        {
            return LIQUID_GASOLINE;
        }
        return -1;
    }
References CCTWaterSurface::Can(), Liquid::CanFillContainer(), UAMaxDistances::DEFAULT, UAWaterType::FRESH, LIQUID_GASOLINE, and LIQUID_WATER.
Referenced by ActionFillBottleBaseCB::CreateActionComponent().
ReadFromContext()
override bool ActionFillBottleBase::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 90 of file actionfillbottlebase.c.
    {
        super.ReadFromContext(ctx, action_recive_data);
        if ( HasTarget() )
        {
            vector cursor_position;
            if ( !ctx.Read(cursor_position) )
                return false;
            action_recive_data.m_Target.SetCursorHitPos(cursor_position);
        }
        return true;
    }
References HasTarget(), and Serializer::Read().
SetupAction()
override bool ActionFillBottleBase::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 60 of file actionfillbottlebase.c.
    {
        SetupStance( player );
        if ( super.SetupAction(player, target, item, action_data, extra_data ))
        {
            if ( target.GetObject() )
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEWELL;
            }
            else
            {
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_FILLBOTTLEPOND;
            }
            return true;
        }
        return false;
    }
References AnimatedActionBase::m_CommandUID, and SetupStance().
SetupStance()
void ActionFillBottleBase::SetupStance (PlayerBase player) inline private
Definition at line 143 of file actionfillbottlebase.c.
    {
        //returns in format (totalWaterDepth, characterDepht, 0)
        vector water_info = HumanCommandSwim.WaterLevelCheck( player, player.GetPosition() );
        if ( water_info[1] > WATER_DEPTH )
        {
            m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        }
        else
        {
            m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        }
    }
References HumanCommandSwim(), m_StanceMask, and WATER_DEPTH.
Referenced by SetupAction().
WriteToContext()
override void ActionFillBottleBase::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 80 of file actionfillbottlebase.c.
    {
        super.WriteToContext(ctx, action_data);
        if ( HasTarget() )
        {
            ctx.Write(action_data.m_Target.GetCursorHitPos()); //sends cursor pos for pond recognition
        }
    }
References HasTarget(), ActionData::m_Target, and Serializer::Write().
Member Data Documentation
WATER_DEPTH
private const float ActionFillBottleBase::WATER_DEPTH = 0.5 private
Definition at line 23 of file actionfillbottlebase.c.
Referenced by SetupStance().