DayzKode: PASBroadcaster Class Reference
PASBroadcaster Class Reference
Private Member Functions
override bool DisableVicinityIcon ()
override bool IsStaticTransmitter ()
override void OnSwitchOff ()
override void OnSwitchOn ()
override void OnWorkStart ()
override void OnWorkStop ()
protected void SoundTurnedOnNoiseStart ()
protected void SoundTurnedOnNoiseStop ()
protected void SoundTurnOff ()
protected void SoundTurnOn ()
Private Attributes
protected EffectSound m_Sound
protected EffectSound m_SoundLoop
const string SOUND_PAS_TURN_OFF = "pastransmitter_turnoff_SoundSet"
const string SOUND_PAS_TURN_ON = "pastransmitter_turnon_SoundSet"
const string SOUND_PAS_TURNED_ON = "pastransmitter_staticnoise_SoundSet"
Detailed Description
Definition at line 1 of file land_radio_panelpas.c.
Member Function Documentation
DisableVicinityIcon()
override bool PASBroadcaster::DisableVicinityIcon () inline private
Definition at line 17 of file land_radio_panelpas.c.
    {
        return true;
    }
IsStaticTransmitter()
override bool PASBroadcaster::IsStaticTransmitter () inline private
Definition at line 12 of file land_radio_panelpas.c.
    {
        return true;
    }
OnSwitchOff()
override void PASBroadcaster::OnSwitchOff () inline private
Definition at line 36 of file land_radio_panelpas.c.
    {
        super.OnSwitchOff();
        //sound
        SoundTurnOff();
    }
References SoundTurnOff().
OnSwitchOn()
override void PASBroadcaster::OnSwitchOn () inline private
Definition at line 23 of file land_radio_panelpas.c.
    {
        super.OnSwitchOn();
        if ( !GetCompEM().CanWork() )
        {
            GetCompEM().SwitchOff();
        }
        //sound
        SoundTurnOn();
    }
References SoundTurnOn().
OnWorkStart()
override void PASBroadcaster::OnWorkStart () inline private
Definition at line 44 of file land_radio_panelpas.c.
    {
        super.OnWorkStart();
        //turn off device
        SwitchOn ( true ); // start send/receive voice
        //sound
        SoundTurnedOnNoiseStart();
    }
References SoundTurnedOnNoiseStart().
OnWorkStop()
override void PASBroadcaster::OnWorkStop () inline private
Definition at line 55 of file land_radio_panelpas.c.
    {
        super.OnWorkStop();
        //turn off device
        SwitchOn ( false ); // stop send/receive voice
        //sound
        SoundTurnedOnNoiseStop();
    }
References SoundTurnedOnNoiseStop().
SoundTurnedOnNoiseStart()
protected void PASBroadcaster::SoundTurnedOnNoiseStart () inline private
Definition at line 70 of file land_radio_panelpas.c.
    {
        PlaySoundSetLoop( m_SoundLoop, SOUND_PAS_TURNED_ON, 1.0, 1.0 );
    }
References PlaySoundSetLoop().
Referenced by OnWorkStart().
SoundTurnedOnNoiseStop()
protected void PASBroadcaster::SoundTurnedOnNoiseStop () inline private
Definition at line 75 of file land_radio_panelpas.c.
    {
        StopSoundSet( m_SoundLoop );
    }
References StopSoundSet().
Referenced by OnWorkStop().
SoundTurnOff()
protected void PASBroadcaster::SoundTurnOff () inline private
Definition at line 85 of file land_radio_panelpas.c.
    {
        PlaySoundSet( m_Sound, SOUND_PAS_TURN_OFF, 0, 0 );
    }
References m_Sound, and PlaySoundSet().
Referenced by OnSwitchOff().
SoundTurnOn()
protected void PASBroadcaster::SoundTurnOn () inline private
Definition at line 80 of file land_radio_panelpas.c.
    {
        PlaySoundSet( m_Sound, SOUND_PAS_TURN_ON, 0, 0 );
    }
References m_Sound, and PlaySoundSet().
Referenced by OnSwitchOn().
Member Data Documentation
m_Sound
protected EffectSound PASBroadcaster::m_Sound private
Definition at line 8 of file land_radio_panelpas.c.
m_SoundLoop
protected EffectSound PASBroadcaster::m_SoundLoop private
Definition at line 9 of file land_radio_panelpas.c.
SOUND_PAS_TURN_OFF
const string PASBroadcaster::SOUND_PAS_TURN_OFF = "pastransmitter_turnoff_SoundSet" private
Definition at line 5 of file land_radio_panelpas.c.
SOUND_PAS_TURN_ON
const string PASBroadcaster::SOUND_PAS_TURN_ON = "pastransmitter_turnon_SoundSet" private
Definition at line 4 of file land_radio_panelpas.c.
SOUND_PAS_TURNED_ON
const string PASBroadcaster::SOUND_PAS_TURNED_ON = "pastransmitter_staticnoise_SoundSet" private
Definition at line 6 of file land_radio_panelpas.c.