DayzKode: UAInputAPI Class Reference
UAInputAPI Class Reference
Private Member Functions
proto native void ActivateContext (string sContextName)
proto native void ActivateExclude (string sExcludeName)
proto native void ActivateGroup (string sGroupName)
proto native void ActivateModificator (string sModName)
proto native void Backlit_Animation (string strName, float fLifeTime, int iColor1, int iColor2)
proto native void Backlit_Background (int eType, int iColor1, int iColor2)
proto native void Backlit_EmptyQueue ()
proto native bool Backlit_Enabled ()
proto native void Backlit_ForceUpdate ()
proto native void Backlit_KeyByHash (int uHash, int eLayer, int eType, int iColor)
proto native void Backlit_KeyByName (string strName, int eLayer, int eType, int iColor)
proto native void Backlit_None ()
proto native void Backlit_Remove (int eLayer)
proto native void DeactivateContext ()
proto native void DeactivateModificator (string sModName)
proto native void DeRegisterGroup (string sGroupName)
proto native void DeRegisterInput (string sInputName)
proto native int DeterminedCount ()
proto native int DeterminePressedButton ()
proto native void Export ()
proto native void GetActiveInputs (out TIntArray items)
proto native owned string GetButtonIcon (int iHash)
proto native owned string GetButtonName (int iHash)
proto native int GetDetermined (int iIndex)
proto native UAInput GetInputByID (int iID)
returns list of all bindable (i.e. visible) inputs from the active group ('core' by default)
proto native UAInput GetInputByName (string sInputName)
proto native owned string GetModificatorName (int index)
proto native void ListActiveGroup ()
proto native void ListAvailableButtons ()
proto native void ListCurrentPreset ()
proto native void ListCurrentProfile ()
proto native int ModificatorCount ()
proto native int PresetCount ()
proto native bool PresetCreateNew ()
proto native int PresetCurrent ()
proto native bool PresetDelete (int index)
proto native owned string PresetName (int index)
proto native void PresetSelect (int index)
proto native void RegisterGroup (string sGroupName, string sLoc)
proto native UAInput RegisterInput (string sInputName, string sLoc, string sGroupName)
proto native void Revert ()
proto native void SaveInputPresetMiscData ()
proto native int SortingCount ()
proto native owned string SortingLocalization (int index)
proto native owned string SortingName (int index)
proto native void SupressNextFrame (bool bForce)
private void UAInputAPI ()
proto native void UpdateControls ()
private void ~UAInputAPI ()
Detailed Description
Definition at line 164 of file uainput.c.
Constructor & Destructor Documentation
UAInputAPI()
private void UAInputAPI::UAInputAPI () inline private
Definition at line 166 of file uainput.c.
{}
~UAInputAPI()
private void UAInputAPI::~UAInputAPI () inline private
Definition at line 167 of file uainput.c.
{}
Member Function Documentation
ActivateContext()
proto native void UAInputAPI::ActivateContext (string sContextName) private
ActivateExclude()
proto native void UAInputAPI::ActivateExclude (string sExcludeName) private
Referenced by MissionBase::RefreshExcludes(), and PluginBase::Show().
ActivateGroup()
proto native void UAInputAPI::ActivateGroup (string sGroupName) private
ActivateModificator()
proto native void UAInputAPI::ActivateModificator (string sModName) private
Referenced by CommandHandler().
Backlit_Animation()
proto native void UAInputAPI::Backlit_Animation (string strName, float fLifeTime, int iColor1, int iColor2) private
Referenced by Backlit::LoadingAnim(), Backlit::MainMenu_OnShow(), and Backlit::OnSwimmingStart().
Backlit_Background()
proto native void UAInputAPI::Backlit_Background (int eType, int iColor1, int iColor2) private
Referenced by Backlit::MainMenu_OnHide(), Backlit::OnEnterCar(), Backlit::OnLeaveCar(), Backlit::OnSwimmingStop(), and Backlit::UpdatePlayer().
Backlit_EmptyQueue()
proto native void UAInputAPI::Backlit_EmptyQueue () private
Referenced by Backlit::OnSwimmingStart().
Backlit_Enabled()
proto native bool UAInputAPI::Backlit_Enabled () private
Backlit_ForceUpdate()
proto native void UAInputAPI::Backlit_ForceUpdate () private
Referenced by Backlit::LoadingAnim(), and Backlit::MainMenu_OnShow().
Backlit_KeyByHash()
proto native void UAInputAPI::Backlit_KeyByHash (int uHash, int eLayer, int eType, int iColor) private
Referenced by Backlit::KeybindingShow().
Backlit_KeyByName()
proto native void UAInputAPI::Backlit_KeyByName (string strName, int eLayer, int eType, int iColor) private
Referenced by Backlit::LoadingAnim(), Backlit::RefreshVehicleLayout(), Backlit::UpdatePlayer(), Backlit::VisualiseBlood(), and Backlit::VisualiseHealth().
Backlit_None()
proto native void UAInputAPI::Backlit_None () private
Backlit_Remove()
proto native void UAInputAPI::Backlit_Remove (int eLayer) private
Referenced by Backlit::HintClear(), Backlit::KeybindingClear(), Backlit::MainMenu_OnHide(), Backlit::MainMenu_OnShow(), Backlit::OnEnterCar(), Backlit::OnLeaveCar(), and Backlit::UpdatePlayer().
DeactivateContext()
proto native void UAInputAPI::DeactivateContext () private
DeactivateModificator()
proto native void UAInputAPI::DeactivateModificator (string sModName) private
Referenced by CommandHandler().
DeRegisterGroup()
proto native void UAInputAPI::DeRegisterGroup (string sGroupName) private
DeRegisterInput()
proto native void UAInputAPI::DeRegisterInput (string sInputName) private
DeterminedCount()
proto native int UAInputAPI::DeterminedCount () private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
DeterminePressedButton()
proto native int UAInputAPI::DeterminePressedButton () private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
Export()
proto native void UAInputAPI::Export () private
Referenced by UIScriptedMenu::Apply(), array::OnSelectKBPreset(), UIScriptedMenu::PerformSwitchPreset(), and SwitchPreset().
GetActiveInputs()
proto native void UAInputAPI::GetActiveInputs (out TIntArray items) private
Referenced by ScriptedWidgetEventHandler::AddSubgroup(), InputUtils::InitInputMetadata(), and ScriptedWidgetEventHandler::TutorialKeybinds().
GetButtonIcon()
proto native owned string UAInputAPI::GetButtonIcon (int iHash) private
GetButtonName()
proto native owned string UAInputAPI::GetButtonName (int iHash) private
Referenced by InputUtils::GetButtonNameFromInput(), ScriptedWidgetEventHandler::Reload(), ScriptedWidgetEventHandler::SetElementTitle(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
GetDetermined()
proto native int UAInputAPI::GetDetermined (int iIndex) private
Referenced by array::Update(), and ScriptedWidgetEventHandler::Update().
GetInputByID()
proto native UAInput UAInputAPI::GetInputByID (int iID) private
returns list of all bindable (i.e. visible) inputs from the active group ('core' by default)
Referenced by array::Apply(), ScriptedWidgetEventHandler::Apply(), InputUtils::InitInputMetadata(), ScriptedWidgetEventHandler::Reload(), and ScriptedWidgetEventHandler::TutorialKeybinds().
GetInputByName()
proto native UAInput UAInputAPI::GetInputByName (string sInputName) private
Referenced by MissionBase::AddActiveInputRestriction(), ConstructData(), InputUtils::GetButtonIconPathFromInput(), InputUtils::GetButtonNameFromInput(), InputUtils::GetComboButtonNamesFromInput(), InputUtils::GetImagesetAndIconFromInputAction(), InputUtils::GetRichtextButtonIconFromInputAction(), GetStringVariant(), HandleOptic(), InterruptGestureCheck(), InventoryMovementButtonTickHandler(), UIScriptedMenu::OnChange(), OnSprintEnd(), OnSprintStart(), MissionBase::OnUpdate(), MissionBase::RemoveActiveInputRestriction(), ActionInput::SetInput(), and ScriptedWidgetEventHandler::SetInteractActionIcon().
GetModificatorName()
proto native owned string UAInputAPI::GetModificatorName (int index) private
ListActiveGroup()
proto native void UAInputAPI::ListActiveGroup () private
ListAvailableButtons()
proto native void UAInputAPI::ListAvailableButtons () private
ListCurrentPreset()
proto native void UAInputAPI::ListCurrentPreset () private
ListCurrentProfile()
proto native void UAInputAPI::ListCurrentProfile () private
ModificatorCount()
proto native int UAInputAPI::ModificatorCount () private
PresetCount()
proto native int UAInputAPI::PresetCount () private
Referenced by UIScriptedMenu::PerformSwitchPreset(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetCreateNew()
proto native bool UAInputAPI::PresetCreateNew () private
PresetCurrent()
proto native int UAInputAPI::PresetCurrent () private
Referenced by OnShow(), UIScriptedMenu::PerformSwitchPreset(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetDelete()
proto native bool UAInputAPI::PresetDelete (int index) private
PresetName()
proto native owned string UAInputAPI::PresetName (int index) private
Referenced by OnShow(), SwitchPreset(), and UIScriptedMenu::UpdateToolbarText().
PresetSelect()
proto native void UAInputAPI::PresetSelect (int index) private
Referenced by array::OnSelectKBPreset(), UIScriptedMenu::PerformSwitchPreset(), and SwitchPreset().
RegisterGroup()
proto native void UAInputAPI::RegisterGroup (string sGroupName, string sLoc) private
RegisterInput()
proto native UAInput UAInputAPI::RegisterInput (string sInputName, string sLoc, string sGroupName) private
Revert()
proto native void UAInputAPI::Revert () private
Referenced by UIScriptedMenu::PerformSetToDefaults().
SaveInputPresetMiscData()
proto native void UAInputAPI::SaveInputPresetMiscData () private
Referenced by array::OnSelectKBPreset(), and UIScriptedMenu::PerformSwitchPreset().
SortingCount()
proto native int UAInputAPI::SortingCount () private
Referenced by InputUtils::InitInputMetadata().
SortingLocalization()
proto native owned string UAInputAPI::SortingLocalization (int index) private
Referenced by UIScriptedMenu::CreateTabs().
SortingName()
proto native owned string UAInputAPI::SortingName (int index) private
SupressNextFrame()
proto native void UAInputAPI::SupressNextFrame (bool bForce) private
Referenced by MissionBase::AddActiveInputExcludes(), MissionBase::EnableAllInputs(), and MissionBase::RemoveActiveInputExcludes().
UpdateControls()
proto native void UAInputAPI::UpdateControls () private
Referenced by MissionBase::EnableAllInputs(), PluginBase::Hide(), MissionBase::RefreshExcludes(), and PluginBase::Show().