DayzKode: WeaponChambering_Cartridge Class Reference
WeaponChambering_Cartridge Class Reference
Private Member Functions
override bool IsWaitingForActionFinish ()
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
Detailed Description
Definition at line 160 of file weaponchambering.c.
Member Function Documentation
IsWaitingForActionFinish()
override bool WeaponChambering_Cartridge::IsWaitingForActionFinish () inline private
Definition at line 244 of file weaponchambering.c.
{ return true; }
OnEntry()
override void WeaponChambering_Cartridge::OnEntry (WeaponEventBase e) inline private
Definition at line 245 of file weaponchambering.c.
    {
        super.OnEntry(e);
        for(int i = 0; i < m_weapon.GetMuzzleCount(); i++ )
        {
            if(!m_weapon.IsChamberFull(i))
            {
                m_weapon.ShowBullet(i);
                m_weapon.EffectBulletShow(i, m_damage, m_type);
                return;
            }
        }
    }
References m_weapon.
OnExit() [1/2]
override void WeaponChambering_Cartridge::OnExit (WeaponEventBase e) inline private
Definition at line 162 of file weaponchambering.c.
    {
        float ammoDamage;
        string ammoTypeName;
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsChamberFull(mi))
        {
            m_weapon.PopCartridgeFromChamber(mi, ammoDamage, ammoTypeName);
            if (m_weapon.PushCartridgeToInternalMagazine(mi, ammoDamage, ammoTypeName))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, ok - loaded chamber"); }
            }
            else
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - cannot load chamber chamber!"); }
        }
        super.OnExit(e);
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnExit() [2/2]
override void WeaponChambering_Cartridge::OnExit (WeaponEventBase e) inline private
Definition at line 260 of file weaponchambering.c.
    {
        for(int i = 0; i < m_weapon.GetMuzzleCount(); i++ )
        {
            if(!m_weapon.IsChamberFull(i))
            {
                if (m_weapon.PushCartridgeToChamber(i, m_damage, m_type))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, ok - loaded chamber"); }
                }
                else
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - cannot load chamber chamber!"); }
                m_type = string.Empty;
                return;
            }
        }
        super.OnExit(e);
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().