DayzKode: PaintItem Class Reference
PaintItem Class Reference
Static Private Member Functions
static bool CanPaintItem (ItemBase item_tool, ItemBase item_target)
static void Paint (ItemBase item_tool, ItemBase item_target, string base_name, PlayerBase player, float specialty_weight=0)
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
static void SwitchItems (EntityAI old_item, string new_item, PlayerBase player)
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Detailed Description
Definition at line 1 of file paintitem.c.
Member Function Documentation
CanPaintItem()
static bool PaintItem::CanPaintItem (ItemBase item_tool, ItemBase item_target) inline static private
Definition at line 13 of file paintitem.c.
    {
        string spray_color = item_tool.ConfigGetString("color");
        string item_color = item_target.ConfigGetString("color");
        if( spray_color != item_color )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
Referenced by RecipeBase::CanDo().
Paint()
static void PaintItem::Paint (ItemBase item_tool, ItemBase item_target, string base_name, PlayerBase player, float specialty_weight = 0) inline static private
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
Definition at line 4 of file paintitem.c.
    {
        string spray_color = item_tool.ConfigGetString("color");
        string item_color = item_target.ConfigGetString("color");
        string new_class_name = base_name + "_" + spray_color;
        PaintItem.SwitchItems(item_target, new_class_name, player);
    }
References SwitchItems().
Referenced by RecipeBase::Do().
SwitchItems()
static void PaintItem::SwitchItems (EntityAI old_item, string new_item, PlayerBase player) inline static private
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Definition at line 29 of file paintitem.c.
    {
        MiscGameplayFunctions.TurnItemIntoItemEx(player, new PaintItemLambda(old_item, new_item, player));
    }
Referenced by Paint().