DayzKode: Surface Class Reference
Surface Class Reference
Static Private Member Functions
static float GetParamFloat (string surface_name, string param_name)
Detailed Description
Definition at line 1 of file surface.c.
Member Function Documentation
GetParamFloat()
static float Surface::GetParamFloat (string surface_name, string param_name) inline static private
Definition at line 3 of file surface.c.
    {
        float value = GetGame().ConfigGetFloat( "CfgSurfaces " + surface_name + " " + param_name );
        return value;
    }
References CGame::ConfigGetFloat(), and GetGame().
Referenced by ManBase::ProcessFeetDamageServer().