DayzKode: ActionBandageBase Class Reference
ActionBandageBase Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ApplyBandage (ItemBase item, PlayerBase player)
Detailed Description
Definition at line 1 of file actionbandagebase.c.
Member Function Documentation
ActionCondition()
override bool ActionBandageBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 4 of file actionbandagebase.c.
    {
        if( target)
        {
            PlayerBase target_player = PlayerBase.Cast(target.GetObject());
            if(target_player)
                return target_player.IsBleeding();
        }
        return player.IsBleeding();
    }
ApplyBandage()
void ActionBandageBase::ApplyBandage (ItemBase item, PlayerBase player) inline private
Definition at line 16 of file actionbandagebase.c.
    {
        if (player.GetBleedingManagerServer() )
        {
            player.GetBleedingManagerServer().RemoveMostSignificantBleedingSourceEx(item);
        }
        PluginTransmissionAgents m_mta = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
        m_mta.TransmitAgents(item, player, AGT_ITEM_TO_FLESH);
        if (item.HasQuantity())
        {
            item.AddQuantity(-1,true);
        }
        else
        {
            item.Delete();
        }
    }
References AGT_ITEM_TO_FLESH, and GetPlugin().
Referenced by ActionBandageSelf::OnFinishProgressServer(), and ActionBandageTarget::OnFinishProgressServer().