DayzKode: DayZCreatureAIType Class Reference
DayZCreatureAIType Class Reference
Private Member Functions
private void DayZCreatureAIType ()
AnimDamageEvent GetDamageEvent (int event_id)
proto native owned string GetName ()
AnimSoundEvent GetSoundEvent (int event_id)
AnimSoundVoiceEvent GetSoundVoiceEvent (int event_id)
AnimStepEvent GetStepEvent (int event_id)
void LoadAnimDamageEvents ()
void LoadAnimSoundEvents ()
void LoadAnimSoundVoiceEvents ()
void LoadAnimStepEvents ()
private void LoadParams ()
private void ~DayZCreatureAIType ()
Private Attributes
ref array< ref AnimDamageEvent > m_animDamageEvents
string m_AnimEventsCfgPath
ref array< ref AnimSoundEvent > m_animSoundEvents
ref array< ref AnimSoundVoiceEvent > m_animSoundVoiceEvents
ref array< ref AnimStepEvent > m_animStepEvents
string m_CfgPath
Detailed Description
Definition at line 1 of file dayzanimaltype.c.
Constructor & Destructor Documentation
DayZCreatureAIType()
private void DayZCreatureAIType::DayZCreatureAIType () inline private
Definition at line 11 of file dayzcreatureaitype.c.
    {
        m_CfgPath = "CfgVehicles " + GetName() + " ";
        m_AnimEventsCfgPath = m_CfgPath + "AnimEvents ";
        LoadParams();
    }
References GetName(), LoadParams(), m_AnimEventsCfgPath, and m_CfgPath.
~DayZCreatureAIType()
private void DayZCreatureAIType::~DayZCreatureAIType () inline private
Definition at line 18 of file dayzcreatureaitype.c.
    {
    }
Member Function Documentation
GetDamageEvent()
AnimDamageEvent DayZCreatureAIType::GetDamageEvent (int event_id) inline private
Definition at line 142 of file dayzcreatureaitype.c.
    {
        for (int i = 0; i < m_animDamageEvents.Count(); i++)
        {
            AnimDamageEvent damageEvent = m_animDamageEvents.Get(i);
            if (damageEvent.m_iID == event_id)
            {
                return damageEvent;
            }
        }
        return null;
    }
References m_animDamageEvents.
GetName()
proto native owned string DayZCreatureAIType::GetName () private
Referenced by DayZCreatureAIType(), and RegisterAttacks().
GetSoundEvent()
AnimSoundEvent DayZCreatureAIType::GetSoundEvent (int event_id) inline private
Definition at line 114 of file dayzcreatureaitype.c.
    {
        for (int i = 0; i < m_animSoundEvents.Count(); i++)
        {
            AnimSoundEvent soundEvent = m_animSoundEvents.Get(i);
            if (soundEvent.m_iID == event_id)
            {
                return soundEvent;
            }
        }
        return null;
    }
References m_animSoundEvents.
GetSoundVoiceEvent()
AnimSoundVoiceEvent DayZCreatureAIType::GetSoundVoiceEvent (int event_id) inline private
Definition at line 128 of file dayzcreatureaitype.c.
    {
        for (int i = 0; i < m_animSoundVoiceEvents.Count(); i++)
        {
            AnimSoundVoiceEvent voiceEvent = m_animSoundVoiceEvents.Get(i);
            if (voiceEvent.m_iID == event_id)
            {
                return voiceEvent;
            }
        }
        return null;
    }
References m_animSoundVoiceEvents.
GetStepEvent()
AnimStepEvent DayZCreatureAIType::GetStepEvent (int event_id) inline private
Definition at line 100 of file dayzcreatureaitype.c.
    {
        for (int i = 0; i < m_animStepEvents.Count(); i++)
        {
            AnimStepEvent stepEvent = m_animStepEvents.Get(i);
            if (stepEvent.m_iID == event_id)
            {
                return stepEvent;
            }
        }
        return null;
    }
References m_animStepEvents.
LoadAnimDamageEvents()
void DayZCreatureAIType::LoadAnimDamageEvents () inline private
Definition at line 75 of file dayzcreatureaitype.c.
    {
        m_animDamageEvents = new array<ref AnimDamageEvent>;
        string damagesCfgPath = m_AnimEventsCfgPath + "Damages ";
        int damagesCount = GetGame().ConfigGetChildrenCount(damagesCfgPath);
        for (int i = 0; i < damagesCount; i++)
        {
            string damageName;
            GetGame().ConfigGetChildName(damagesCfgPath, i, damageName);
            string damagePath = damagesCfgPath + damageName + " ";
            AnimDamageEvent damageEvent = new AnimDamageEvent(damagePath);
            m_animDamageEvents.Insert(damageEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_animDamageEvents, and m_AnimEventsCfgPath.
Referenced by LoadParams().
LoadAnimSoundEvents()
void DayZCreatureAIType::LoadAnimSoundEvents () inline private
Definition at line 23 of file dayzcreatureaitype.c.
    {
        m_animSoundEvents = new array<ref AnimSoundEvent>;
        string soundsCfgPath = m_AnimEventsCfgPath + "Sounds ";
        int soundCount = GetGame().ConfigGetChildrenCount(soundsCfgPath);
        for (int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if (soundEvent.IsValid())
                m_animSoundEvents.Insert(soundEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animSoundEvents.
Referenced by LoadParams().
LoadAnimSoundVoiceEvents()
void DayZCreatureAIType::LoadAnimSoundVoiceEvents () inline private
Definition at line 41 of file dayzcreatureaitype.c.
    {
        m_animSoundVoiceEvents = new array<ref AnimSoundVoiceEvent>;
        string soundsCfgPath = m_AnimEventsCfgPath + "SoundVoice ";
        int soundCount = GetGame().ConfigGetChildrenCount(soundsCfgPath);
        for (int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundVoiceEvent soundEvent = new AnimSoundVoiceEvent(soundPath);
            if (soundEvent.IsValid())
                m_animSoundVoiceEvents.Insert(soundEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animSoundVoiceEvents.
Referenced by LoadParams().
LoadAnimStepEvents()
void DayZCreatureAIType::LoadAnimStepEvents () inline private
Definition at line 59 of file dayzcreatureaitype.c.
    {
        m_animStepEvents = new array<ref AnimStepEvent>;
        string stepsCfgPath = m_AnimEventsCfgPath + "Steps ";
        int stepsCount = GetGame().ConfigGetChildrenCount(stepsCfgPath);
        for (int i = 0; i < stepsCount; i++)
        {
            string stepName;
            GetGame().ConfigGetChildName(stepsCfgPath, i, stepName);
            string stepPath = stepsCfgPath + stepName + " ";
            AnimStepEvent stepEvent = new AnimStepEvent(stepPath);
            m_animStepEvents.Insert(stepEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_AnimEventsCfgPath, and m_animStepEvents.
Referenced by LoadParams().
LoadParams()
private void DayZCreatureAIType::LoadParams () inline private
Definition at line 92 of file dayzcreatureaitype.c.
    {
        LoadAnimSoundEvents();
        LoadAnimSoundVoiceEvents();
        LoadAnimStepEvents();
        LoadAnimDamageEvents();
    }
References LoadAnimDamageEvents(), LoadAnimSoundEvents(), LoadAnimSoundVoiceEvents(), and LoadAnimStepEvents().
Referenced by DayZCreatureAIType().
Member Data Documentation
m_animDamageEvents
ref array<ref AnimDamageEvent> DayZCreatureAIType::m_animDamageEvents private
Definition at line 6 of file dayzcreatureaitype.c.
Referenced by GetDamageEvent(), and LoadAnimDamageEvents().
m_AnimEventsCfgPath
string DayZCreatureAIType::m_AnimEventsCfgPath private
Definition at line 9 of file dayzcreatureaitype.c.
Referenced by DayZCreatureAIType(), LoadAnimDamageEvents(), LoadAnimSoundEvents(), LoadAnimSoundVoiceEvents(), and LoadAnimStepEvents().
m_animSoundEvents
ref array<ref AnimSoundEvent> DayZCreatureAIType::m_animSoundEvents private
Definition at line 3 of file dayzcreatureaitype.c.
Referenced by GetSoundEvent(), and LoadAnimSoundEvents().
m_animSoundVoiceEvents
ref array<ref AnimSoundVoiceEvent> DayZCreatureAIType::m_animSoundVoiceEvents private
Definition at line 4 of file dayzcreatureaitype.c.
Referenced by GetSoundVoiceEvent(), and LoadAnimSoundVoiceEvents().
m_animStepEvents
ref array<ref AnimStepEvent> DayZCreatureAIType::m_animStepEvents private
Definition at line 5 of file dayzcreatureaitype.c.
Referenced by GetStepEvent(), and LoadAnimStepEvents().
m_CfgPath
string DayZCreatureAIType::m_CfgPath private
Definition at line 8 of file dayzcreatureaitype.c.
Referenced by DayZCreatureAIType().