DayzKode: NotificationSystem Class Reference
NotificationSystem Class Reference
Private Member Functions
protected NotificationData GetNotificationData (NotificationType type)
void NotificationSystem ()
Static Private Member Functions
static void AddNotification (NotificationType type, float show_time, string detail_text="")
Send notification from default types to local player.
static void AddNotificationExtended (float show_time, string title_text, string detail_text="", string icon="")
Send custom notification from to local player.
static void BindOnAdd (func fn)
static void BindOnRemove (func fn)
static void LoadNotificationData ()
static void SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player from server.
static void SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player from server.
static void SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text="")
Send notification from default types to player identity from server.
static void SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text="", string icon="")
Send custom notification to player identity from server.
static void UnbindOnAdd (func fn)
static void UnbindOnRemove (func fn)
static void Update (float timeslice)
Private Attributes
protected ref map< NotificationType, ref NotificationData > m_DataArray
protected ref array< ref NotificationRuntimeData > m_DeferredArray
protected ref ScriptInvoker m_OnNotificationAdded = new ScriptInvoker
protected ref ScriptInvoker m_OnNotificationRemoved = new ScriptInvoker
protected ref array< ref NotificationRuntimeData > m_TimeArray
Static Private Attributes
static protected const string JSON_FILE_PATH = "Scripts/Data/notifications.json"
static protected ref NotificationSystem m_Instance
static protected const int MAX_NOTIFICATIONS = 5
Detailed Description
Definition at line 56 of file notificationsystem.c.
Constructor & Destructor Documentation
NotificationSystem()
void NotificationSystem::NotificationSystem () inline private
Definition at line 70 of file notificationsystem.c.
    {
        m_Instance = this;
        #ifndef WORKBENCH
        m_TimeArray = new array<ref NotificationRuntimeData>;
        m_DeferredArray = new array<ref NotificationRuntimeData>;
        LoadNotificationData();
        #endif
    }
References LoadNotificationData(), m_DeferredArray, m_Instance, and m_TimeArray.
Member Function Documentation
AddNotification()
static void NotificationSystem::AddNotification (NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to local player.
Parameters
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 156 of file notificationsystem.c.
    {
        if ( m_Instance.m_TimeArray.Count() < MAX_NOTIFICATIONS )
        {
            float time = GetGame().GetTickTime() + show_time;
            NotificationRuntimeData data = new NotificationRuntimeData(time, m_Instance.GetNotificationData( type ), detail_text);
            m_Instance.m_TimeArray.Insert( data );
            m_Instance.m_OnNotificationAdded.Invoke( data );
        }
        else
        {
            NotificationRuntimeData data_def = new NotificationRuntimeData(show_time, m_Instance.GetNotificationData( type ), detail_text);
            m_Instance.m_DeferredArray.Insert( data_def );
        }
    }
References GetGame(), GetNotificationData(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_TimeArray, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by DisconnectSessionScript(), OnlineServices::OnFriendsAsync(), BiosSessionService::OnGetGameplaySession(), BiosSessionService::OnGetSessionError(), BiosUserManager::OnJoin(), OnRPC(), and BiosUserManager::SelectUserEx().
AddNotificationExtended()
static void NotificationSystem::AddNotificationExtended (float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification from to local player.
Parameters
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 180 of file notificationsystem.c.
    {
        if( m_Instance.m_TimeArray.Count() < MAX_NOTIFICATIONS )
        {
            float time = GetGame().GetTickTime() + show_time;
            NotificationData temp_data = new NotificationData( icon, title_text );
            NotificationRuntimeData data = new NotificationRuntimeData(time, temp_data, detail_text);
            m_Instance.m_TimeArray.Insert( data );
            m_Instance.m_OnNotificationAdded.Invoke( data );
        }
        else
        {
            NotificationData temp_data_def = new NotificationData( icon, title_text );
            NotificationRuntimeData data_def = new NotificationRuntimeData(show_time, temp_data_def, detail_text);
            m_Instance.m_DeferredArray.Insert( data_def );
        }
    }
References GetGame(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_TimeArray, MAX_NOTIFICATIONS, and NotificationRuntimeData().
Referenced by OnRPC().
BindOnAdd()
static void NotificationSystem::BindOnAdd (func fn) inline static private
Definition at line 273 of file notificationsystem.c.
    {
        m_Instance.m_OnNotificationAdded.Insert( fn );
    }
References ScriptInvoker::Insert(), m_Instance, and m_OnNotificationAdded.
Referenced by NotificationUI::NotificationUI().
BindOnRemove()
static void NotificationSystem::BindOnRemove (func fn) inline static private
Definition at line 283 of file notificationsystem.c.
    {
        m_Instance.m_OnNotificationRemoved.Insert( fn );
    }
References ScriptInvoker::Insert(), m_Instance, and m_OnNotificationRemoved.
Referenced by NotificationUI::NotificationUI().
GetNotificationData()
protected NotificationData NotificationSystem::GetNotificationData (NotificationType type) inline private
Definition at line 231 of file notificationsystem.c.
    {
        if( m_DataArray.Contains(type) )
        {
            return m_DataArray.Get( type );
        }
        return null;
    }
References m_DataArray.
Referenced by AddNotification().
LoadNotificationData()
static void NotificationSystem::LoadNotificationData () inline static private
Definition at line 241 of file notificationsystem.c.
    {
        map<NotificationType, NotificationData> data_array;
        m_Instance.m_DataArray = new map<NotificationType, ref NotificationData>;
        JsonFileLoader<map<NotificationType, NotificationData>>.JsonLoadFile( JSON_FILE_PATH, data_array );
        m_Instance.m_DataArray.Copy( data_array );
        array<int> types = new array<int>;
        NotificationType type_curr = 0;
        while ( type_curr != NotificationType.NOTIFICATIONS_END )
        {
            types.Insert( type_curr );
            type_curr++;
        }
        for ( int i = 0; i < m_Instance.m_DataArray.Count(); i++ )
        {
            types.RemoveItem( m_Instance.m_DataArray.GetKey( i ) );
        }
        if ( types.Count() > 0 )
        {
            foreach ( NotificationType type2 : types )
            {
                NotificationData data2 = new NotificationData( "please_add_an_icon", "please_add_a_title", "optional_description" );
                m_Instance.m_DataArray.Insert( type2, data2 );
            }
            JsonFileLoader<map<NotificationType, ref NotificationData>>.JsonSaveFile( JSON_FILE_PATH, m_Instance.m_DataArray );
        }
    }
References JSON_FILE_PATH, m_DataArray, and m_Instance.
Referenced by NotificationSystem().
SendNotificationToPlayer()
static void NotificationSystem::SendNotificationToPlayer (Man player, NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to player from server.
Parameters
player the target player to send notification to
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 124 of file notificationsystem.c.
    {
        if ( player )
        {
            SendNotificationToPlayerIdentity( player.GetIdentity(), type, show_time, detail_text );
        }
    }
References SendNotificationToPlayerIdentity().
SendNotificationToPlayerExtended()
static void NotificationSystem::SendNotificationToPlayerExtended (Man player, float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification to player from server.
Parameters
player the target player to send notification to
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 89 of file notificationsystem.c.
    {
        if ( player )
        {
            SendNotificationToPlayerIdentityExtended( player.GetIdentity(), show_time, title_text, detail_text, icon );
        }
    }
References SendNotificationToPlayerIdentityExtended().
SendNotificationToPlayerIdentity()
static void NotificationSystem::SendNotificationToPlayerIdentity (PlayerIdentity player, NotificationType type, float show_time, string detail_text = "") inline static private
Send notification from default types to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
type the type of notification to send - these can be viewed in /Scripts/Data/Notifications.json
show_time amount of time this notification is displayed
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
Definition at line 139 of file notificationsystem.c.
    {
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(type);
        rpc.Write(show_time);
        rpc.Write(detail_text);
        rpc.Send(null, ERPCs.RPC_SEND_NOTIFICATION, true, player);
    }
References ScriptRPC::Send(), and Serializer::Write().
Referenced by SendNotificationToPlayer().
SendNotificationToPlayerIdentityExtended()
static void NotificationSystem::SendNotificationToPlayerIdentityExtended (PlayerIdentity player, float show_time, string title_text, string detail_text = "", string icon = "") inline static private
Send custom notification to player identity from server.
Parameters
player the target player to send notification to - if null, will send to all players
show_time amount of time this notification is displayed
title_text the title text that is displayed in the notification
detail_text additional text that can be added to the notification under the title - will not display additional text if not set
icon the icon that is displayed in the notification - will use default icon if not set
Definition at line 105 of file notificationsystem.c.
    {
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(show_time);
        rpc.Write(title_text);
        rpc.Write(detail_text);
        rpc.Write(icon);
        rpc.Send(null, ERPCs.RPC_SEND_NOTIFICATION_EXTENDED, true, player);
    }
References ScriptRPC::Send(), and Serializer::Write().
Referenced by SendNotificationToPlayerExtended().
UnbindOnAdd()
static void NotificationSystem::UnbindOnAdd (func fn) inline static private
Definition at line 278 of file notificationsystem.c.
    {
        m_Instance.m_OnNotificationAdded.Remove( fn );
    }
References m_Instance, m_OnNotificationAdded, and ScriptInvoker::Remove().
Referenced by NotificationUI::~NotificationUI().
UnbindOnRemove()
static void NotificationSystem::UnbindOnRemove (func fn) inline static private
Definition at line 288 of file notificationsystem.c.
    {
        m_Instance.m_OnNotificationRemoved.Remove( fn );
    }
References m_Instance, m_OnNotificationRemoved, and ScriptInvoker::Remove().
Referenced by NotificationUI::~NotificationUI().
Update()
static void NotificationSystem::Update (float timeslice) inline static private
Definition at line 200 of file notificationsystem.c.
    {
        if( m_Instance )
        {
            array<NotificationRuntimeData> to_remove = new array<NotificationRuntimeData>;
            foreach( NotificationRuntimeData data : m_Instance.m_TimeArray )
            {
                if( data.GetTime() < GetGame().GetTickTime() )
                {
                    to_remove.Insert( data );
                }
            }
            foreach( NotificationRuntimeData data2 : to_remove )
            {
                m_Instance.m_TimeArray.RemoveItem( data2 );
                m_Instance.m_OnNotificationRemoved.Invoke( data2 );
                if( m_Instance.m_DeferredArray.Count() > 0 )
                {
                    NotificationRuntimeData data_def = m_Instance.m_DeferredArray.Get( m_Instance.m_DeferredArray.Count() - 1 );
                    float time = GetGame().GetTickTime() + data_def.GetTime();
                    data_def.SetTime( time );
                    m_Instance.m_TimeArray.Insert( data_def );
                    m_Instance.m_OnNotificationAdded.Invoke( data_def );
                    m_Instance.m_DeferredArray.Remove( m_Instance.m_DeferredArray.Count() - 1 );
                }
            }
        }
    }
References GetGame(), CGame::GetTickTime(), ScriptInvoker::Invoke(), m_DeferredArray, m_Instance, m_OnNotificationAdded, m_OnNotificationRemoved, m_TimeArray, and NotificationRuntimeData().
Referenced by OnUpdate().
Member Data Documentation
JSON_FILE_PATH
protected const string NotificationSystem::JSON_FILE_PATH = "Scripts/Data/notifications.json" static private
Definition at line 58 of file notificationsystem.c.
Referenced by LoadNotificationData().
m_DataArray
protected ref map<NotificationType, ref NotificationData> NotificationSystem::m_DataArray private
Definition at line 65 of file notificationsystem.c.
Referenced by GetNotificationData(), and LoadNotificationData().
m_DeferredArray
protected ref array<ref NotificationRuntimeData> NotificationSystem::m_DeferredArray private
Definition at line 64 of file notificationsystem.c.
Referenced by AddNotification(), AddNotificationExtended(), NotificationSystem(), and Update().
m_Instance
protected ref NotificationSystem NotificationSystem::m_Instance static private
Definition at line 61 of file notificationsystem.c.
Referenced by AddNotification(), AddNotificationExtended(), BindOnAdd(), BindOnRemove(), LoadNotificationData(), NotificationSystem(), UnbindOnAdd(), UnbindOnRemove(), and Update().
m_OnNotificationAdded
protected ref ScriptInvoker NotificationSystem::m_OnNotificationAdded = new ScriptInvoker private
Definition at line 67 of file notificationsystem.c.
Referenced by AddNotification(), AddNotificationExtended(), BindOnAdd(), UnbindOnAdd(), and Update().
m_OnNotificationRemoved
protected ref ScriptInvoker NotificationSystem::m_OnNotificationRemoved = new ScriptInvoker private
Definition at line 68 of file notificationsystem.c.
Referenced by BindOnRemove(), UnbindOnRemove(), and Update().
m_TimeArray
protected ref array<ref NotificationRuntimeData> NotificationSystem::m_TimeArray private
Definition at line 63 of file notificationsystem.c.
Referenced by AddNotification(), AddNotificationExtended(), NotificationSystem(), and Update().
MAX_NOTIFICATIONS
protected const int NotificationSystem::MAX_NOTIFICATIONS = 5 static private
Definition at line 59 of file notificationsystem.c.
Referenced by AddNotification(), and AddNotificationExtended().