DayzKode: PropertyModifiers Class Reference
PropertyModifiers Class Reference
Private Member Functions
float CalculateBarrelLength (ItemBase owner)
float GetBarrelLength ()
Get Barrel Legth in mm.
float m_Weapon void PropertyModifiers (ItemBase owner)
void UpdateModifiers ()
Static Private Member Functions
static vector GetModifierRaw (ItemBase item, string modifier_name, vector value="1 1 1")
Private Attributes
float m_BarrelLength
ItemBase m_OwnerItem
vector m_RecoilModifiers
vector m_SightMisalignment
vector m_SwayModifiers
Detailed Description
Definition at line 1 of file propertymodifiers.c.
Constructor & Destructor Documentation
PropertyModifiers()
float m_Weapon void PropertyModifiers::PropertyModifiers (ItemBase owner) inline private
Definition at line 12 of file propertymodifiers.c.
    {
        //test_timer = new Timer();
        //test_timer.Run(5, this, "Refresh", NULL, true);
        m_OwnerItem = owner;
        UpdateModifiers();
        m_BarrelLength = CalculateBarrelLength(owner);
    }
References CalculateBarrelLength(), m_BarrelLength, m_OwnerItem, and UpdateModifiers().
Member Function Documentation
CalculateBarrelLength()
float PropertyModifiers::CalculateBarrelLength (ItemBase owner) inline private
Definition at line 28 of file propertymodifiers.c.
    {
        vector usti_hlavne_position = owner.GetSelectionPositionLS( "usti hlavne" );//usti hlavne
        vector konec_hlavne_position = owner.GetSelectionPositionLS( "konec hlavne" );//konec hlavne
        usti_hlavne_position = owner.ModelToWorld(usti_hlavne_position);
        konec_hlavne_position = owner.ModelToWorld(konec_hlavne_position);
        return vector.Distance(usti_hlavne_position, konec_hlavne_position);
    }
References vector::Distance().
Referenced by GetBarrelLength(), and PropertyModifiers().
GetBarrelLength()
float PropertyModifiers::GetBarrelLength () inline private
Get Barrel Legth in mm.
Definition at line 22 of file propertymodifiers.c.
    {
        //return m_BarrelLength * 1000:
        return CalculateBarrelLength(m_OwnerItem) * 1000;
    }
References CalculateBarrelLength(), and m_OwnerItem.
GetModifierRaw()
static vector PropertyModifiers::GetModifierRaw (ItemBase item, string modifier_name, vector value = "1 1 1") inline static private
Definition at line 65 of file propertymodifiers.c.
    {
        if( item.ConfigIsExisting(modifier_name) )
        {
            value = item.ConfigGetVector(modifier_name);
        }
        return value;
    }
Referenced by UpdateModifiers().
UpdateModifiers()
void PropertyModifiers::UpdateModifiers () inline private
Definition at line 38 of file propertymodifiers.c.
    {
        m_RecoilModifiers = GetModifierRaw(m_OwnerItem, "recoilModifier");
        m_SwayModifiers = GetModifierRaw(m_OwnerItem, "swayModifier");
        m_SightMisalignment = GetModifierRaw(m_OwnerItem, "sightMisalignmentModifier");
        for (int i = 0; i < m_OwnerItem.GetInventory().AttachmentCount(); i++)
        {
            ItemBase attachment = ItemBase.Cast(m_OwnerItem.GetInventory().GetAttachmentFromIndex(i));
            vector temp_value = PropertyModifiers.GetModifierRaw(attachment, "recoilModifier");
            m_RecoilModifiers[0] = m_RecoilModifiers[0] * temp_value[0];
            m_RecoilModifiers[1] = m_RecoilModifiers[1] * temp_value[1];
            m_RecoilModifiers[2] = m_RecoilModifiers[2] * temp_value[2];
            temp_value = PropertyModifiers.GetModifierRaw(attachment, "swayModifier");
            m_SwayModifiers[0] = m_SwayModifiers[0] * temp_value[0];
            m_SwayModifiers[1] = m_SwayModifiers[1] * temp_value[1];
            m_SwayModifiers[2] = m_SwayModifiers[2] * temp_value[2];
            temp_value = PropertyModifiers.GetModifierRaw(attachment, "sightMisalignmentModifier");
            m_SightMisalignment[0] = m_SightMisalignment[0] * temp_value[0];
            m_SightMisalignment[1] = m_SightMisalignment[1] * temp_value[1];
            m_SightMisalignment[2] = m_SightMisalignment[2] * temp_value[2];
        }
    }
References AttachmentCount(), GetModifierRaw(), m_OwnerItem, m_RecoilModifiers, m_SightMisalignment, and m_SwayModifiers.
Referenced by PropertyModifiers().
Member Data Documentation
m_BarrelLength
float PropertyModifiers::m_BarrelLength private
Definition at line 7 of file propertymodifiers.c.
Referenced by PropertyModifiers().
m_OwnerItem
ItemBase PropertyModifiers::m_OwnerItem private
Definition at line 9 of file propertymodifiers.c.
Referenced by GetBarrelLength(), PropertyModifiers(), and UpdateModifiers().
m_RecoilModifiers
vector PropertyModifiers::m_RecoilModifiers private
Definition at line 3 of file propertymodifiers.c.
Referenced by UpdateModifiers().
m_SightMisalignment
vector PropertyModifiers::m_SightMisalignment private
Definition at line 5 of file propertymodifiers.c.
Referenced by UpdateModifiers().
m_SwayModifiers
vector PropertyModifiers::m_SwayModifiers private
Definition at line 4 of file propertymodifiers.c.
Referenced by UpdateModifiers().