DayzKode: Compass Class Reference
Compass Class Reference
Private Member Functions
override void Close ()
void Compass ()
override bool IsOpen ()
override void OnVariablesSynchronized ()
override void Open ()
override void SetActions ()
protected void UpdateVisualState ()
Private Attributes
protected ref OpenableBehaviour m_Openable
Detailed Description
Definition at line 1 of file compass.c.
Constructor & Destructor Documentation
Compass()
void Compass::Compass () inline private
Definition at line 5 of file compass.c.
    {
        m_Openable = new OpenableBehaviour(false);
        RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
        UpdateVisualState();
    }
References m_Openable, and UpdateVisualState().
Member Function Documentation
Close()
override void Compass::Close () inline private
Definition at line 22 of file compass.c.
    {
        m_Openable.Close();
        SetSynchDirty();
        UpdateVisualState();
    }
References OpenableBehaviour::Close(), m_Openable, and UpdateVisualState().
IsOpen()
override bool Compass::IsOpen () inline private
Definition at line 30 of file compass.c.
    {
        return m_Openable.IsOpened();
    }
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by UpdateVisualState().
OnVariablesSynchronized()
override void Compass::OnVariablesSynchronized () inline private
Definition at line 47 of file compass.c.
    {
        super.OnVariablesSynchronized();
        UpdateVisualState();
    }
References UpdateVisualState().
Open()
override void Compass::Open () inline private
Definition at line 14 of file compass.c.
    {
        m_Openable.Open();
        SetSynchDirty();
        UpdateVisualState();
    }
References m_Openable, OpenableBehaviour::Open(), and UpdateVisualState().
SetActions()
override void Compass::SetActions () inline private
Definition at line 54 of file compass.c.
    {
        super.SetActions();
        AddAction(ActionOpen);
        AddAction(ActionClose);
        AddAction(ActionViewCompass);
    }
References AddAction().
UpdateVisualState()
protected void Compass::UpdateVisualState () inline private
Definition at line 35 of file compass.c.
    {
        if ( IsOpen() )
        {
            SetAnimationPhase("cover", 1.0);
        }
        else
        {
            SetAnimationPhase("cover", 0.0);
        }
    }
References IsOpen().
Referenced by Close(), Compass(), OnVariablesSynchronized(), and Open().
Member Data Documentation
m_Openable
protected ref OpenableBehaviour Compass::m_Openable private
Definition at line 3 of file compass.c.
Referenced by Close(), Compass(), IsOpen(), and Open().