DayzKode: BloodNotfr Class Reference
BloodNotfr Class Reference
Private Member Functions
void BloodNotfr (NotifiersManager manager)
override void DisplayTendency (float delta)
override int GetNotifierType ()
override float GetObservedValue ()
Private Attributes
protected const float DEC_TRESHOLD_HIGH = -22
protected const float DEC_TRESHOLD_LOW = 0
protected const float DEC_TRESHOLD_MED = -12
protected const float INC_TRESHOLD_HIGH = 6
protected const float INC_TRESHOLD_LOW = 0
protected const float INC_TRESHOLD_MED = 3
Detailed Description
Definition at line 1 of file bloodnotfr.c.
Constructor & Destructor Documentation
BloodNotfr()
void BloodNotfr::BloodNotfr (NotifiersManager manager) inline private
Definition at line 10 of file bloodnotfr.c.
    {
    }
Member Function Documentation
DisplayTendency()
override void BloodNotfr::DisplayTendency (float delta) inline private
Definition at line 19 of file bloodnotfr.c.
    {
        int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
        //DSLevels level = DetermineLevel( GetObservedValue(), PlayerConstants.THRESHOLD_BLOOD_WARNING,  PlayerConstants.THRESHOLD_BLOOD_CRITICAL, PlayerConstants.THRESHOLD_BLOOD_BLINKING, PlayerConstants.THRESHOLD_BLOOD_EXTRA );
        DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_BLOOD));
        EStatLevels blood_level = m_Player.GetStatLevelBlood();
        if( dis_elm )
        {
            dis_elm.SetTendency(tendency);
            dis_elm.SetSeriousnessLevel(blood_level);
        }
    }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int BloodNotfr::GetNotifierType () inline private
Definition at line 14 of file bloodnotfr.c.
    {
        return eNotifiers.NTF_BLOOD;
    }
GetObservedValue()
override float BloodNotfr::GetObservedValue () inline private
Definition at line 37 of file bloodnotfr.c.
    {
        float blood = m_Player.GetHealth("GlobalHealth","Blood");
        return blood;
    }
References NotifierBase::m_Player.
Member Data Documentation
DEC_TRESHOLD_HIGH
protected const float BloodNotfr::DEC_TRESHOLD_HIGH = -22 private
Definition at line 5 of file bloodnotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
protected const float BloodNotfr::DEC_TRESHOLD_LOW = 0 private
Definition at line 3 of file bloodnotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
protected const float BloodNotfr::DEC_TRESHOLD_MED = -12 private
Definition at line 4 of file bloodnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
protected const float BloodNotfr::INC_TRESHOLD_HIGH = 6 private
Definition at line 8 of file bloodnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
protected const float BloodNotfr::INC_TRESHOLD_LOW = 0 private
Definition at line 6 of file bloodnotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
protected const float BloodNotfr::INC_TRESHOLD_MED = 3 private
Definition at line 7 of file bloodnotfr.c.
Referenced by DisplayTendency().