DayzKode: ActionShave Class Reference
ActionShave Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionShave ()
override void CreateConditionComponents ()
override bool HasTarget ()
override bool IsShaveSelf ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionshave.c.
Constructor & Destructor Documentation
ActionShave()
void ActionShave::ActionShave () inline private
Definition at line 11 of file actionshave.c.
    {
        m_CallbackClass = ActionShaveCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_SHAVE;
        m_FullBody = false;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#shave_myself";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionShave::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 28 of file actionshave.c.
    {
        if ( player.CanShave() )
        {
            return true;
        }
        return false;
    }
CreateConditionComponents()
override void ActionShave::CreateConditionComponents () inline private
Definition at line 22 of file actionshave.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionShave::HasTarget () inline private
Definition at line 38 of file actionshave.c.
    {
        return false;
    }
IsShaveSelf()
override bool ActionShave::IsShaveSelf () inline private
Definition at line 43 of file actionshave.c.
    {
        return true;
    }
OnFinishProgressClient()
override void ActionShave::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 54 of file actionshave.c.
    {
        super.OnFinishProgressClient( action_data );
        GetGame().GetAnalyticsClient().OnActionFinishedShaveSelf();
    }
References CGame::GetAnalyticsClient(), GetGame(), and AnalyticsManagerClient::OnActionFinishedShaveSelf().
OnFinishProgressServer()
override void ActionShave::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 48 of file actionshave.c.
    {
        action_data.m_Player.ShavePlayer();
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References ActionData::m_Player, and m_SpecialtyWeight.