DayzKode: BleedingCheckMdfr Class Reference
BleedingCheckMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
protected const float BLOOD_DECREMENT_PER_SEC = -10
PluginAdminLog m_AdminLog
Detailed Description
Definition at line 2 of file bleeding.c.
Member Function Documentation
ActivateCondition()
override bool BleedingCheckMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 22 of file bleeding.c.
    {
        float blood = player.GetHealth("","Blood");
        if( blood < PlayerConstants.BLOOD_THRESHOLD_FATAL )
        {
            return true;
        }
        return false;
    }
References PlayerConstants::BLOOD_THRESHOLD_FATAL.
DeactivateCondition()
override bool BleedingCheckMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 49 of file bleeding.c.
    {
        return false;
    }
Init()
override void BleedingCheckMdfr::Init () inline private
Definition at line 7 of file bleeding.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_BLEEDING;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        if( GetGame().IsServer() )
        {
            m_AdminLog              = PluginAdminLog.Cast( GetPlugin(PluginAdminLog) );
        }
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), GetGame(), GetPlugin(), m_AdminLog, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void BleedingCheckMdfr::OnActivate (PlayerBase player) inline private
Definition at line 34 of file bleeding.c.
    {
        player.SetHealth("","",-1000);
        if ( m_AdminLog )
        {
            m_AdminLog.BleedingOut( player );
        }
    }
References m_AdminLog.
OnDeactivate()
override void BleedingCheckMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 44 of file bleeding.c.
    {
    }
OnTick()
override void BleedingCheckMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 54 of file bleeding.c.
    {
    }
Member Data Documentation
BLOOD_DECREMENT_PER_SEC
protected const float BleedingCheckMdfr::BLOOD_DECREMENT_PER_SEC = -10 private
Definition at line 4 of file bleeding.c.
m_AdminLog
PluginAdminLog BleedingCheckMdfr::m_AdminLog private
Definition at line 5 of file bleeding.c.
Referenced by Init(), and OnActivate().