DayzKode: WrittenNoteData Class Reference
WrittenNoteData Class Reference
Private Member Functions
void DepleteWritingImplement (notnull ItemBase pen, string old_text, string new_text)
bool GetNoteInfo (out ItemBase pen, out ItemBase paper)
string GetNoteText ()
void InitNoteInfo (ItemBase pen=null, ItemBase paper=null)
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
void SetNoteText (string text)
void WrittenNoteData (ItemBase parent)
Private Attributes
protected ItemBase m_Paper
protected string m_SimpleText
protected ItemBase m_WritingImplement
Detailed Description
Definition at line 1 of file writtennotedata.c.
Constructor & Destructor Documentation
WrittenNoteData()
void WrittenNoteData::WrittenNoteData (ItemBase parent) inline private
Definition at line 8 of file writtennotedata.c.
    {
    }
Member Function Documentation
DepleteWritingImplement()
void WrittenNoteData::DepleteWritingImplement (notnull ItemBase pen, string old_text, string new_text) inline private
Definition at line 83 of file writtennotedata.c.
    {
        float qty_per_char = 1.0;
        float decrease = Math.Clamp((new_text.Length() - old_text.Length()),0,pen.GetQuantityMax());
        pen.AddQuantity(-(qty_per_char * decrease));
    }
References Math::Clamp(), and string::Length().
Referenced by OnRPC().
GetNoteInfo()
bool WrittenNoteData::GetNoteInfo (out ItemBase pen, out ItemBase paper) inline private
Definition at line 65 of file writtennotedata.c.
    {
        pen = m_WritingImplement;
        paper = m_Paper;
        //handwriting = m_Handwriting;
        return pen && paper;
    }
References m_Paper, and m_WritingImplement.
Referenced by OnRPC().
GetNoteText()
string WrittenNoteData::GetNoteText () inline private
Definition at line 73 of file writtennotedata.c.
    {
        return m_SimpleText;
    }
References m_SimpleText.
Referenced by ActionReadPaperCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
InitNoteInfo()
void WrittenNoteData::InitNoteInfo (ItemBase pen = null, ItemBase paper = null) inline private
Definition at line 58 of file writtennotedata.c.
    {
        m_WritingImplement = pen;
        m_Paper = paper;
        //m_Handwriting = handwriting;
    }
References m_Paper, and m_WritingImplement.
Referenced by ActionWritePaper::OnStartClient(), and ActionWritePaper::OnStartServer().
OnRPC()
void WrittenNoteData::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 13 of file writtennotedata.c.
    {
        Param1<string> param = new Param1<string>("");
        //sent from server, executed on client
        if (rpc_type == ERPCs.RPC_WRITE_NOTE)
        {
            if (ctx.Read(param))
            {
                SetNoteText(param.param1);
            }
            g_Game.GetMission().SetNoteMenu(g_Game.GetUIManager().EnterScriptedMenu(MENU_NOTE, GetGame().GetUIManager().GetMenu())); //NULL means no parent
            ItemBase pen;
            ItemBase paper;
            //int handwriting;
            if (GetNoteInfo(pen,paper))
            {
                g_Game.GetMission().GetNoteMenu().InitNoteWrite(paper,pen,m_SimpleText);
            }
        }
        //sent from client (NoteMenu), executed on server
        if (rpc_type == ERPCs.RPC_WRITE_NOTE_CLIENT)
        {
            if (ctx.Read(param))
            {
                string old_string = m_SimpleText;
                SetNoteText(param.param1);
                DepleteWritingImplement(m_WritingImplement,old_string,m_SimpleText);
            }
        }
        if (rpc_type == ERPCs.RPC_READ_NOTE)
        {
            if (ctx.Read(param))
            {
                SetNoteText(param.param1);
            }
            g_Game.GetMission().SetNoteMenu(g_Game.GetUIManager().EnterScriptedMenu(MENU_NOTE, GetGame().GetUIManager().GetMenu())); //NULL means no parent
            g_Game.GetMission().GetNoteMenu().InitNoteRead(m_SimpleText);
        }
    }
References DepleteWritingImplement(), g_Game, GetGame(), GetNoteInfo(), m_SimpleText, m_WritingImplement, MENU_NOTE, Serializer::Read(), and SetNoteText().
Referenced by InventoryItem::OnRPC().
SetNoteText()
void WrittenNoteData::SetNoteText (string text) inline private
Definition at line 78 of file writtennotedata.c.
    {
        m_SimpleText = MiscGameplayFunctions.SanitizeString(text);
    }
References m_SimpleText.
Referenced by OnRPC().
Member Data Documentation
m_Paper
protected ItemBase WrittenNoteData::m_Paper private
Definition at line 4 of file writtennotedata.c.
Referenced by GetNoteInfo(), and InitNoteInfo().
m_SimpleText
protected string WrittenNoteData::m_SimpleText private
Definition at line 6 of file writtennotedata.c.
Referenced by GetNoteText(), OnRPC(), and SetNoteText().
m_WritingImplement
protected ItemBase WrittenNoteData::m_WritingImplement private
Definition at line 3 of file writtennotedata.c.
Referenced by GetNoteInfo(), InitNoteInfo(), and OnRPC().