DayzKode: Head Class Reference
Head Class Reference
Private Member Functions
int GetBeardIndex ()
int GetHairIndex ()
bool GetHeadHideableSelections (out array< string > selections)
int GetSelectionIndex (string str)
void Head_Default ()
void Init ()
void InitSelectionTranslation ()
bool IsHandlingException ()
Private Attributes
int m_beard_idx
int m_hair_idx
bool m_handling_exception = false
ref map< int, ref SelectionTranslation > m_HeadHairHidingStateMap
ref array< string > m_HeadHairSelectionArray
Detailed Description
Definition at line 1 of file head.c.
Member Function Documentation
GetBeardIndex()
int Head::GetBeardIndex () inline private
Definition at line 46 of file head.c.
    {
        return m_beard_idx;
    }
References m_beard_idx.
GetHairIndex()
int Head::GetHairIndex () inline private
Definition at line 51 of file head.c.
    {
        return m_hair_idx;
    }
References m_hair_idx.
GetHeadHideableSelections()
bool Head::GetHeadHideableSelections (out array< string > selections) inline private
Definition at line 40 of file head.c.
    {
        selections = m_HeadHairSelectionArray;
        return true;
    }
References m_HeadHairSelectionArray.
GetSelectionIndex()
int Head::GetSelectionIndex (string str) inline private
Definition at line 56 of file head.c.
    {
        return m_HeadHairSelectionArray.Find(str);
    }
Head_Default()
void Head::Head_Default () inline private
Definition at line 10 of file head.c.
    {
        Init();
    }
References Init().
Init()
void Head::Init () inline private
Definition at line 15 of file head.c.
    {
        m_HeadHairHidingStateMap = new map<int,ref SelectionTranslation>;
        m_HeadHairSelectionArray = new array<string>;
        ConfigGetTextArray("simpleHiddenSelections",m_HeadHairSelectionArray);
        m_beard_idx = m_HeadHairSelectionArray.Find("beard");
        m_hair_idx = m_HeadHairSelectionArray.Find("hair");
        if (!ConfigIsExisting("HairHiding"))
            m_handling_exception = true;
        InitSelectionTranslation();
    }
References ConfigGetTextArray(), ConfigIsExisting(), and InitSelectionTranslation().
Referenced by Head_Default().
InitSelectionTranslation()
void Head::InitSelectionTranslation () inline private
Definition at line 30 of file head.c.
    {
        for (int i = 0; i < m_HeadHairSelectionArray.Count(); i++)
        {
            SelectionTranslation selTran = new SelectionTranslation(this,i);
            selTran.SetSelectionState(true);
            m_HeadHairHidingStateMap.Insert(i,selTran); //all considered "shown" on init
        }
    }
References SelectionTranslation::SetSelectionState().
Referenced by Init().
IsHandlingException()
bool Head::IsHandlingException () inline private
Definition at line 61 of file head.c.
    {
        return m_handling_exception;
    }
References m_handling_exception.
Member Data Documentation
m_beard_idx
int Head::m_beard_idx private
Definition at line 4 of file head.c.
Referenced by GetBeardIndex().
m_hair_idx
int Head::m_hair_idx private
Definition at line 5 of file head.c.
Referenced by GetHairIndex().
m_handling_exception
bool Head::m_handling_exception = false private
Definition at line 3 of file head.c.
Referenced by IsHandlingException().
m_HeadHairHidingStateMap
ref map<int,ref SelectionTranslation> Head::m_HeadHairHidingStateMap private
Definition at line 7 of file head.c.
m_HeadHairSelectionArray
ref array<string> Head::m_HeadHairSelectionArray private
Definition at line 8 of file head.c.
Referenced by GetHeadHideableSelections().