DayzKode: PluginRecipesManagerBase Class Reference
PluginRecipesManagerBase Class Reference
Private Member Functions
void CallbackGenerateCache ()
protected bool CheckRecipe (int id, ItemBase item1, ItemBase item2, PlayerBase player)
protected void ClearResults ()
protected void CreateAllRecipes ()
void GenerateHumanReadableRecipeList ()
protected void GenerateRecipeCache ()
bool GetIsInstaRecipe (int recipe_id)
protected int GetRecipeIntersection (int num_of_ingredients, ItemBase items[])
fills an array with recipe IDs which 'item_a' and 'item_b' share
float GetRecipeLengthInSecs (int recipe_id)
string GetRecipeName (int recipe_id)
float GetRecipeSpecialty (int recipe_id)
int GetValidRecipes (ItemBase item1, ItemBase item2, array< int > ids, PlayerBase player)
int GetValidRecipesProper (int num_of_items, ItemBase items[], array< int > ids, PlayerBase player)
bool IsEnableDebugCrafting ()
protected void MatchItems (TStringArray full_path)
override void OnInit ()
void PerformRecipeServer (int id, ItemBase item_a, ItemBase item_b, PlayerBase player)
void PluginRecipesManager ()
protected void PrintCache ()
protected void PrintResultMasks (int num)
protected bool RecipeSanityCheck (int num_of_ingredients, InventoryItemBase items[], PlayerBase player)
override protected void RegisterRecipe (RecipeBase recipe)
protected bool ResolveIngredients (int num_of_ingredients, int passes=0)
void SetEnableDebugCrafting (bool enable)
protected int SortIngredients (int num_of_ingredients, ItemBase items_unsorted[], int resolved_recipes[])
protected bool SortIngredientsInRecipe (int id, int num_of_ingredients, ItemBase ingredients_unsorted[], ItemBase ingredients_sorted[])
sorts ingredients correctly as either first or second ingredient based on their masks
override protected void UnregisterRecipe (string clasname)
void WalkRecipes ()
void ~PluginRecipesManager ()
Static Private Member Functions
static int GetMaxNumberOfRecipes ()
static int RecipeIDFromClassname (string classname)
Private Attributes
int item_mask
int m_BaseMask
string m_BaseName
int m_BitsResults [MAX_INGREDIENTS]
ref array< string > m_CachedItems = new array<string>
ref CacheObject m_CoBase
ref CacheObject m_CoItem
bool m_EnableDebugCrafting = false
ItemBase m_ingredient1 [MAX_CONCURENT_RECIPES]
ItemBase m_ingredient2 [MAX_CONCURENT_RECIPES]
ItemBase m_ingredient3 [MAX_CONCURENT_RECIPES]
int m_IngredientBitMask [MAX_INGREDIENTS]
int m_IngredientBitMaskSize [MAX_INGREDIENTS]
ItemBase m_Ingredients [MAX_INGREDIENTS]
string m_ItemName
ref array< int > m_RcpsArray
int m_RecipeID
ref array< ref RecipeBase > m_RecipeList = new array<ref RecipeBase>
ref array< int > m_RecipesMatched = new array<int>
int m_RegRecipeIndex
int m_ResolvedRecipes [MAX_CONCURENT_RECIPES]
ItemBase m_sortedIngredients [MAX_NUMBER_OF_INGREDIENTS]
ref Timer m_TestTimer
const int MAX_CONCURENT_RECIPES = 128
const int MAX_INGREDIENTS = 5
const int MAX_NUMBER_OF_RECIPES = GetMaxNumberOfRecipes()
ref Timer myTimer1
Static Private Attributes
static ref map< string, ref CacheObject > m_RecipeCache = new map<string,ref CacheObject >
static ref map< string, int > m_RecipeNamesList = new map<string, int>
static ref map< typename, bool > m_RecipesInitializedItem = new ref map<typename, bool>
Detailed Description
Definition at line 12 of file pluginrecipesmanager.c.
Constructor & Destructor Documentation
~PluginRecipesManager()
void PluginRecipesManagerBase::~PluginRecipesManager () inline private
Definition at line 61 of file pluginrecipesmanager.c.
    {
    }
Member Function Documentation
CallbackGenerateCache()
void PluginRecipesManagerBase::CallbackGenerateCache () inline private
Definition at line 158 of file pluginrecipesmanager.c.
    {
        Debug.Log("CallbackGenerateCache","recipes");
        GenerateRecipeCache();
        //SaveCacheToFile(PATH_CACHE_FILE);//generate the cache and save it to a file
        //ReadCacheFromFile(PATH_CACHE_FILE);
    }
References GenerateRecipeCache(), and Debug::Log().
CheckRecipe()
protected bool PluginRecipesManagerBase::CheckRecipe (int id, ItemBase item1, ItemBase item2, PlayerBase player) inline private
Definition at line 416 of file pluginrecipesmanager.c.
    {
        RecipeBase p_recipe = m_RecipeList[id];
        return p_recipe.CheckRecipe(item1,item2, player);
    }
References RecipeBase::CheckRecipe().
Referenced by PerformRecipeServer().
ClearResults()
protected void PluginRecipesManagerBase::ClearResults () inline private
Definition at line 460 of file pluginrecipesmanager.c.
    {
        for (int i = 0; i < MAX_INGREDIENTS; i++)
        {
            m_BitsResults[i] = 0;
        }
    }
References MAX_INGREDIENTS.
Referenced by SortIngredientsInRecipe().
CreateAllRecipes()
protected void PluginRecipesManagerBase::CreateAllRecipes () inline private
Definition at line 599 of file pluginrecipesmanager.c.
    {
        RegisterRecipies();
    }
References RegisterRecipies().
Referenced by PluginRecipesManager().
GenerateHumanReadableRecipeList()
void PluginRecipesManagerBase::GenerateHumanReadableRecipeList () inline private
Definition at line 314 of file pluginrecipesmanager.c.
    {
        FileHandle file = OpenFile("$profile:RecipeDump.txt", FileMode.WRITE);
        if ( file == 0 )
        {
            //error message
            PrintString("failed to open file RecipeDump");
            return;
        }
        array<int> recipes = new array<int>;
        for (int i = 0; i < PluginRecipesManager.m_RecipeCache.Count(); i++)
        {
            string key = PluginRecipesManager.m_RecipeCache.GetKey(i);
            CacheObject value = PluginRecipesManager.m_RecipeCache.GetElement(i);
            string line = key;
            recipes.Clear();
            recipes.InsertAll( value.GetRecipes() );
            //PrintString("Item: " + key);
            for (int x = 0; x < recipes.Count(); x++)
            {
                int recipe_id = recipes.Get(x);
                string recipe_name = GetRecipeName(recipe_id);
                line += "," +recipe_name;
            }
            FPrintln(file, line);
        }
        CloseFile(file);
    }
References CacheObject(), CloseFile(), FPrintln(), GetRecipeName(), OpenFile(), PrintString(), and x.
GenerateRecipeCache()
protected void PluginRecipesManagerBase::GenerateRecipeCache () inline private
Definition at line 166 of file pluginrecipesmanager.c.
    {
        GetGame().ProfilerStart("m_RecipeCache");
        //m_CacheBasesMap.Clear();
        m_CachedItems.Clear();
        PluginRecipesManager.m_RecipeCache.Clear();
        TStringArray all_config_paths = new TStringArray;
        all_config_paths.Insert(CFG_VEHICLESPATH);
        all_config_paths.Insert(CFG_WEAPONSPATH);
        all_config_paths.Insert(CFG_MAGAZINESPATH);
        //Debug.Log("Got here 0","caching");
        string config_path;
        string child_name;
        int scope;
        TStringArray full_path = new TStringArray;
        WalkRecipes();
        for (int i = 0; i < all_config_paths.Count(); i++)
        {
            config_path = all_config_paths.Get(i);
            int children_count = GetGame().ConfigGetChildrenCount(config_path);
            for (int x = 0; x < children_count; x++)
            {
                GetGame().ConfigGetChildName(config_path, x, child_name);
                scope = GetGame().ConfigGetInt( config_path + " " + child_name + " scope" );
                if ( scope == 2 )
                {
                    GetGame().ConfigGetFullPath(config_path +" "+ child_name,/*out*/ full_path);
                    MatchItems(full_path);
                }
            }
        }
        GetGame().ProfilerStop("m_RecipeCache");
    }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFullPath(), CGame::ConfigGetInt(), GetGame(), MatchItems(), CGame::ProfilerStart(), CGame::ProfilerStop(), WalkRecipes(), and x.
Referenced by CallbackGenerateCache(), and PluginRecipesManager().
GetIsInstaRecipe()
bool PluginRecipesManagerBase::GetIsInstaRecipe (int recipe_id) inline private
Definition at line 144 of file pluginrecipesmanager.c.
    {
        if ( m_RecipeList[recipe_id] ) return m_RecipeList[recipe_id].IsInstaRecipe();
        else return false;
    }
GetMaxNumberOfRecipes()
static int PluginRecipesManagerBase::GetMaxNumberOfRecipes () inline static private
Definition at line 47 of file pluginrecipesmanager.c.
    {
        return 2048;
    }
GetRecipeIntersection()
protected int PluginRecipesManagerBase::GetRecipeIntersection (int num_of_ingredients, ItemBase items[]) inline private
fills an array with recipe IDs which 'item_a' and 'item_b' share
Definition at line 529 of file pluginrecipesmanager.c.
    {
        int count = 0;
        int smallest = 9999;
        int smallest_index = 0;
        m_RecipesMatched.Clear();
        /*
        m_Ingredients[0] = item_a;
        m_Ingredients[1] = item_b;
        */
        //find the item with smallest number of recipes
        CacheObject co_least_recipes;
        for (int i = 0; i < num_of_ingredients; i++)
        {
            CacheObject cobject = PluginRecipesManager.m_RecipeCache.Get( items[i].GetType() );
            if (!cobject)
            {
                return 0;
            }
            if (cobject.GetNumberOfRecipes() < smallest)
            {
                smallest = cobject.GetNumberOfRecipes();
                smallest_index = i;
                co_least_recipes = cobject;
            }
        }
        //look for matches
        array<int> recipes = co_least_recipes.GetRecipes();
        for (int x = 0; x < recipes.Count(); x++)
        {
            int id = recipes.Get(x);
            for (int z = 0; z < num_of_ingredients; z++)
            {
                if ( z!= smallest_index)
                {
                    CacheObject cobject2 = PluginRecipesManager.m_RecipeCache.Get( items[z].GetType() );
                    if ( cobject2.IsContainRecipe(id) )
                    {
                        m_RecipesMatched.Insert(id);
                        count++;
                    }
                }
            }
        }
        return count;
    }
References CacheObject(), GetType(), and x.
Referenced by GetValidRecipesProper().
GetRecipeLengthInSecs()
float PluginRecipesManagerBase::GetRecipeLengthInSecs (int recipe_id) inline private
Definition at line 132 of file pluginrecipesmanager.c.
    {
        if ( m_RecipeList[recipe_id] ) return m_RecipeList[recipe_id].GetLengthInSecs();
        return 0;
    }
GetRecipeName()
string PluginRecipesManagerBase::GetRecipeName (int recipe_id) inline private
Definition at line 77 of file pluginrecipesmanager.c.
    {
        if ( m_RecipeList[recipe_id] ) return m_RecipeList[recipe_id].GetName();
        return "";
    }
Referenced by GenerateHumanReadableRecipeList().
GetRecipeSpecialty()
float PluginRecipesManagerBase::GetRecipeSpecialty (int recipe_id) inline private
Definition at line 138 of file pluginrecipesmanager.c.
    {
        if ( m_RecipeList[recipe_id] ) return m_RecipeList[recipe_id].GetSpecialty();
        return 0;
    }
GetValidRecipes()
int PluginRecipesManagerBase::GetValidRecipes (ItemBase item1, ItemBase item2, array< int > ids, PlayerBase player) inline private
Definition at line 85 of file pluginrecipesmanager.c.
    {
        if ( item1 == NULL || item2 == NULL )
        {
            if (ids) ids.Clear();
            return 0;
        }
        if ( ( item1.GetInventory().IsAttachment() && item1.GetHierarchyParent().DisassembleOnLastDetach() ) || ( item2.GetInventory().IsAttachment() && item2.GetHierarchyParent().DisassembleOnLastDetach() ) )
        {
            if (ids) ids.Clear();
            return 0;
        }
        m_Ingredients[0] = item1;
        m_Ingredients[1] = item2;
        return GetValidRecipesProper(2,m_Ingredients, ids, player);
    }
References ItemBase::DisassembleOnLastDetach(), and GetValidRecipesProper().
GetValidRecipesProper()
int PluginRecipesManagerBase::GetValidRecipesProper (int num_of_items, ItemBase items[], array< int > ids, PlayerBase player) inline private
Definition at line 104 of file pluginrecipesmanager.c.
    {
        if (ids) ids.Clear();
        GetRecipeIntersection(num_of_items,items);
        int numOfRecipes = SortIngredients(num_of_items,items,m_ResolvedRecipes);
        //will return number of cached recipes for the 2 items being considered,
        //and save their indexes in m_ResolvedRecipes, please note the m_ResolvedRecipes is a static array,
        //and does not clear up with each query, so the number of recipes returned is critical to make sure we don't accidentally
        //mix in some other indexes from previous queries(and obviously loop only as far as we have to)
        //this also saves the ingredients in the correct assignment as ingredient 1/2 into m_ingredient1/m_ingredient2 arrays, these 3 arrays
        //therefore provide you with information per each index with: recipeid,ingredience1,ingredience2
        if ( numOfRecipes == 0 ) return 0;
        int found = 0;
        RecipeBase p_recipe = NULL;
        for (int i = 0; i < numOfRecipes; i++)
        {
            p_recipe = m_RecipeList[m_ResolvedRecipes[i]];
            if ( p_recipe.CheckRecipe(m_ingredient1[i],m_ingredient2[i], player) == true )
            {
                if (ids) ids.Insert( p_recipe.GetID() );
                found++;
            }
        }
        return found;
    }
References RecipeBase::CheckRecipe(), RecipeBase::GetID(), GetRecipeIntersection(), and SortIngredients().
Referenced by GetValidRecipes().
IsEnableDebugCrafting()
bool PluginRecipesManagerBase::IsEnableDebugCrafting () inline private
Definition at line 66 of file pluginrecipesmanager.c.
    {
        return m_EnableDebugCrafting;
    }
References m_EnableDebugCrafting.
MatchItems()
protected void PluginRecipesManagerBase::MatchItems (TStringArray full_path) inline private
Definition at line 249 of file pluginrecipesmanager.c.
    {
        m_ItemName = full_path.Get(0);
        m_CoItem = m_RecipeCache.Get(m_ItemName);
        //Print(m_ItemName);
        if ( !m_CoItem )
        {
            m_CoItem = new CacheObject;
            m_RecipeCache.Insert(m_ItemName,m_CoItem);
        }
        for (int i = 1; i < full_path.Count(); i++)
        {
            m_BaseName = full_path.Get(i);
            m_CoBase = m_RecipeCache.Get(m_BaseName);
            if ( m_CoBase )//resolve new base classes
            {
                m_RcpsArray = m_RecipeCache.Get(m_BaseName).GetRecipes();
                for ( int x = 0; x < m_RcpsArray.Count(); x++ )//base recipes
                {
                    m_RecipeID = m_RcpsArray.Get(x);
                    //item_mask = m_CoItem.GetMaskByRecipeID(m_RecipeID);
                    m_BaseMask = m_CoBase.GetMaskByRecipeID(m_RecipeID);
                    m_CoItem.AddRecipe(m_RecipeID,m_BaseMask);
                }
            }
        }
    }
References CacheObject(), LayoutHolder::Count(), m_ItemName, m_RecipeID, and x.
Referenced by GenerateRecipeCache().
OnInit()
override void PluginRecipesManagerBase::OnInit () inline private
Definition at line 150 of file pluginrecipesmanager.c.
    {
        super.OnInit();
        //ReadCacheFromFile(PATH_CACHE_FILE);//read the cache from a file
        //GenerateHumanReadableRecipeList();
    }
PerformRecipeServer()
void PluginRecipesManagerBase::PerformRecipeServer (int id, ItemBase item_a, ItemBase item_b, PlayerBase player) inline private
Definition at line 282 of file pluginrecipesmanager.c.
    {
        m_Ingredients[0] = item_a;
        m_Ingredients[1] = item_b;
        if ( !item_a || !item_b )
        {
            Error("PerformRecipeServer - one of the items null !!");
            return;
        }
        SortIngredientsInRecipe(id, 2,m_Ingredients, m_sortedIngredients);
        bool is_recipe_valid = CheckRecipe(id,m_sortedIngredients[0],m_sortedIngredients[1],player);
        bool passed_sanity_check = RecipeSanityCheck(2,m_sortedIngredients,player);
        if ( !is_recipe_valid )
        {
            Error("PerformRecipeServer - recipe not valid !!");
            return;
        }
        if ( !passed_sanity_check )
        {
            Error("PerformRecipeServer - recipe failed to pass sanity check !!");
            return;
        }
        RecipeBase ptrRecipe = m_RecipeList[id];
        ptrRecipe.PerformRecipe(m_sortedIngredients[0],m_sortedIngredients[1],player);
        //player.RequestCraftingDisable();
    }
References CheckRecipe(), Error(), RecipeBase::PerformRecipe(), RecipeSanityCheck(), and SortIngredientsInRecipe().
PluginRecipesManager()
void PluginRecipesManagerBase::PluginRecipesManager () inline private
Definition at line 52 of file pluginrecipesmanager.c.
    {
        CreateAllRecipes();
        GenerateRecipeCache();
        myTimer1 = new Timer();
    }
References CreateAllRecipes(), GenerateRecipeCache(), and myTimer1.
PrintCache()
protected void PluginRecipesManagerBase::PrintCache () inline private
Definition at line 422 of file pluginrecipesmanager.c.
    {
        for (int i = 0; i < PluginRecipesManager.m_RecipeCache.Count(); i++)
        {
            string key = PluginRecipesManager.m_RecipeCache.GetKey(i);
            CacheObject co = PluginRecipesManager.m_RecipeCache.GetElement(i);
            PrintString("Item: " + key);
            co.DebugPrint();
            PrintString("----------------");
        }
    }
References CacheObject(), and PrintString().
PrintResultMasks()
protected void PluginRecipesManagerBase::PrintResultMasks (int num) inline private
Definition at line 520 of file pluginrecipesmanager.c.
    {
        for (int i = 0; i < num; i++)
        {
            Debug.Log("results mask("+i.ToString()+") = " +m_BitsResults[i].ToString() );
        }
    }
References Debug::Log().
RecipeIDFromClassname()
static int PluginRecipesManagerBase::RecipeIDFromClassname (string classname) inline static private
Definition at line 409 of file pluginrecipesmanager.c.
    {
        if (m_RecipeNamesList.Contains(classname))
            return m_RecipeNamesList.Get(classname);
        return -1;
    }
Referenced by UnregisterRecipe().
RecipeSanityCheck()
protected bool PluginRecipesManagerBase::RecipeSanityCheck (int num_of_ingredients, InventoryItemBase items[], PlayerBase player) inline private
Definition at line 346 of file pluginrecipesmanager.c.
    {
        int check_results[MAX_INGREDIENTS];
        for (int i = 0; i < num_of_ingredients;i++)
        {
            ItemBase item = items[i];
            Man item_owner_player = item.GetHierarchyRootPlayer();
            vector item_pos = item.GetPosition();
            vector player_pos = player.GetPosition();
            if (item_owner_player == player)
            {
                check_results[i] =  check_results[i] | ERecipeSanityCheck.IS_IN_PLAYER_INVENTORY;
            }
            if ( item_owner_player == NULL || item_owner_player == player || !item_owner_player.IsAlive() )
            {
                check_results[i] = check_results[i] | ERecipeSanityCheck.NOT_OWNED_BY_ANOTHER_LIVE_PLAYER;
            }
            if ( vector.Distance(item_pos, player_pos ) < ACCEPTABLE_DISTANCE )
            {
                check_results[i] = check_results[i] | ERecipeSanityCheck.CLOSE_ENOUGH;
            }
        }
        for (i = 0; i < num_of_ingredients;i++)
        {
            if ( !((check_results[i] & SANITY_CHECK_ACCEPTABLE_RESULT) == SANITY_CHECK_ACCEPTABLE_RESULT))
            {
                return false;
            }
        }
        return true;
    }
References ACCEPTABLE_DISTANCE, vector::Distance(), MAX_INGREDIENTS, and SANITY_CHECK_ACCEPTABLE_RESULT.
Referenced by PerformRecipeServer().
RegisterRecipe()
override protected void PluginRecipesManagerBase::RegisterRecipe (RecipeBase recipe) inline private
Definition at line 382 of file pluginrecipesmanager.c.
    {
        if ( m_RegRecipeIndex >= MAX_NUMBER_OF_RECIPES )
        {
            Error("Exceeded max. number of recipes, max set to: "+MAX_NUMBER_OF_RECIPES.ToString());
        }
        m_RegRecipeIndex = m_RecipeList.Insert(recipe);
        recipe.SetID(m_RegRecipeIndex);
        m_RecipeNamesList.Insert(recipe.ClassName(), m_RegRecipeIndex);
        //Print("RegisterRecipe: " +recipe.ClassName() + ", "+ m_RegRecipeIndex.ToString());
    }
References Error(), and RecipeBase::SetID().
Referenced by RegisterRecipies().
ResolveIngredients()
protected bool PluginRecipesManagerBase::ResolveIngredients (int num_of_ingredients, int passes = 0) inline private
Definition at line 469 of file pluginrecipesmanager.c.
    {
        int rightmost_bit;
        int smallest = 99999;
        int smallest_index = 0;
        for (int i = 0; i < num_of_ingredients; i++)
        {
            int count = m_IngredientBitMaskSize[i];
            if ( count != 0 && count < smallest)
            {
                smallest = m_IngredientBitMaskSize[i];
                smallest_index = i;
            }
        }
        rightmost_bit = m_IngredientBitMask[smallest_index] & (-m_IngredientBitMask[smallest_index]);
        m_BitsResults[smallest_index] = m_BitsResults[smallest_index] | rightmost_bit;
        for (int x = 0; x < num_of_ingredients; x++)
        {
            m_IngredientBitMask[x] = ~rightmost_bit & m_IngredientBitMask[x];
            m_IngredientBitMask[smallest_index] = 0;
            m_IngredientBitMaskSize[smallest_index] = 0;
        }
        // check validity
        int check_sum_vertical = 0;
        for (int z = 0; z < num_of_ingredients; z++)
        {
            check_sum_vertical = check_sum_vertical | m_IngredientBitMask[z];//vertical sum
            check_sum_vertical = check_sum_vertical | m_BitsResults[z];//vertical sum
            if ((m_IngredientBitMask[z] | m_BitsResults[z]) == 0)
            {
                return false;//horizontal check
            }
        }
        if ( check_sum_vertical != (Math.Pow(2, num_of_ingredients) - 1)) return false;//vertical check
        passes++;
        if (passes < num_of_ingredients)
        {
            if ( !ResolveIngredients(num_of_ingredients, passes) ) return false;
        }
        return true;
    }
References Math::Pow(), ResolveIngredients(), and x.
Referenced by ResolveIngredients(), and SortIngredientsInRecipe().
SetEnableDebugCrafting()
void PluginRecipesManagerBase::SetEnableDebugCrafting (bool enable) inline private
Definition at line 71 of file pluginrecipesmanager.c.
    {
        m_EnableDebugCrafting = enable;
    }
SortIngredients()
protected int PluginRecipesManagerBase::SortIngredients (int num_of_ingredients, ItemBase items_unsorted[], int resolved_recipes[]) inline private
Definition at line 579 of file pluginrecipesmanager.c.
    {
        int count = 0;
        for (int i = 0; i < m_RecipesMatched.Count() && i < MAX_CONCURENT_RECIPES; i++)
        {
            int recipe_id = m_RecipesMatched.Get(i);
                if (SortIngredientsInRecipe(recipe_id, num_of_ingredients, items_unsorted, m_sortedIngredients))//...and now we need to determine which item will be which ingredient number
                {
                    resolved_recipes[count] = recipe_id;
                    m_ingredient1[count] = m_sortedIngredients[0];
                    m_ingredient2[count] = m_sortedIngredients[1];
                    //m_ingredient3[count] = m_sortedIngredients[2];
                    count++;
                }
        }
        return count;
    }
References SortIngredientsInRecipe().
Referenced by GetValidRecipesProper().
SortIngredientsInRecipe()
protected bool PluginRecipesManagerBase::SortIngredientsInRecipe (int id, int num_of_ingredients, ItemBase ingredients_unsorted[], ItemBase ingredients_sorted[]) inline private
sorts ingredients correctly as either first or second ingredient based on their masks
Definition at line 435 of file pluginrecipesmanager.c.
    {
        ClearResults();
        for (int i = 0; i < num_of_ingredients; i++)
        {
            CacheObject co_item = PluginRecipesManager.m_RecipeCache.Get( ingredients_unsorted[i].GetType() );
            m_IngredientBitMask[i] = co_item.GetMaskByRecipeID(id);
            m_IngredientBitMaskSize[i] = co_item.GetBitCountByRecipeID(id);
        }
        bool result = ResolveIngredients(num_of_ingredients);
        if (result)
        {
            for (i = 0; i < num_of_ingredients; i++)
            {
                int index = Math.Log2( m_BitsResults[i]);
                ingredients_sorted[index] = ingredients_unsorted[ i ];
            }
        }
        //PrintResultMasks(num_of_ingredients);
        return result;
    }
References CacheObject(), ClearResults(), GetType(), Math::Log2(), and ResolveIngredients().
Referenced by PerformRecipeServer(), and SortIngredients().
UnregisterRecipe()
override protected void PluginRecipesManagerBase::UnregisterRecipe (string clasname) inline private
Definition at line 396 of file pluginrecipesmanager.c.
    {
        int recipe_id = RecipeIDFromClassname(clasname);
        //Print("UnregisterRecipe: " + recipe_id.ToString());
        if (recipe_id != -1)
        {
            m_RecipeNamesList.Remove(clasname);
            //Print(m_RecipeList[recipe_id]);
            m_RecipeList[recipe_id] = null;
            //Print(m_RecipeList[recipe_id]);
        }
    }
References RecipeIDFromClassname().
WalkRecipes()
void PluginRecipesManagerBase::WalkRecipes () inline private
Definition at line 205 of file pluginrecipesmanager.c.
    {
        //Print("------------- WalkRecipes --------------");
        for (int c = 0; c < m_RecipeList.Count(); c++)
        {
            RecipeBase recipe = m_RecipeList.Get(c);
            if (recipe)
            {
                //Print(recipe.ClassName());
                int recipe_id = recipe.GetID();
                for (int i = 0; i < MAX_NUMBER_OF_INGREDIENTS; i++)
                {
                    array<string> list = recipe.m_Ingredients[i];
                    for (int x = 0; x < list.Count(); x++)
                    {
                        string ingredient = list.Get(x);
                        int mask = Math.Pow(2,i);
                        CacheObject co = m_RecipeCache.Get(ingredient);
                        if (!co)
{
                            co = new CacheObject;
                            m_RecipeCache.Insert(ingredient,co);
                        }
                        co.AddRecipe(recipe_id, mask);
                    }
                }
            }
        }
    }
References CacheObject(), RecipeBase::GetID(), RecipeBase::m_Ingredients, MAX_NUMBER_OF_INGREDIENTS, Math::Pow(), and x.
Referenced by GenerateRecipeCache().
Member Data Documentation
item_mask
int PluginRecipesManagerBase::item_mask private
Definition at line 242 of file pluginrecipesmanager.c.
m_BaseMask
int PluginRecipesManagerBase::m_BaseMask private
Definition at line 243 of file pluginrecipesmanager.c.
m_BaseName
string PluginRecipesManagerBase::m_BaseName private
Definition at line 240 of file pluginrecipesmanager.c.
m_BitsResults
int PluginRecipesManagerBase::m_BitsResults[MAX_INGREDIENTS] private
Definition at line 31 of file pluginrecipesmanager.c.
m_CachedItems
ref array<string> PluginRecipesManagerBase::m_CachedItems = new array<string> private
Definition at line 40 of file pluginrecipesmanager.c.
m_CoBase
ref CacheObject PluginRecipesManagerBase::m_CoBase private
Definition at line 246 of file pluginrecipesmanager.c.
m_CoItem
ref CacheObject PluginRecipesManagerBase::m_CoItem private
Definition at line 245 of file pluginrecipesmanager.c.
m_EnableDebugCrafting
bool PluginRecipesManagerBase::m_EnableDebugCrafting = false private
Definition at line 26 of file pluginrecipesmanager.c.
Referenced by IsEnableDebugCrafting().
m_ingredient1
ItemBase PluginRecipesManagerBase::m_ingredient1[MAX_CONCURENT_RECIPES] private
Definition at line 33 of file pluginrecipesmanager.c.
m_ingredient2
ItemBase PluginRecipesManagerBase::m_ingredient2[MAX_CONCURENT_RECIPES] private
Definition at line 34 of file pluginrecipesmanager.c.
m_ingredient3
ItemBase PluginRecipesManagerBase::m_ingredient3[MAX_CONCURENT_RECIPES] private
Definition at line 35 of file pluginrecipesmanager.c.
m_IngredientBitMask
int PluginRecipesManagerBase::m_IngredientBitMask[MAX_INGREDIENTS] private
Definition at line 28 of file pluginrecipesmanager.c.
m_IngredientBitMaskSize
int PluginRecipesManagerBase::m_IngredientBitMaskSize[MAX_INGREDIENTS] private
Definition at line 29 of file pluginrecipesmanager.c.
m_Ingredients
ItemBase PluginRecipesManagerBase::m_Ingredients[MAX_INGREDIENTS] private
Definition at line 27 of file pluginrecipesmanager.c.
m_ItemName
string PluginRecipesManagerBase::m_ItemName private
Definition at line 244 of file pluginrecipesmanager.c.
m_RcpsArray
ref array<int> PluginRecipesManagerBase::m_RcpsArray private
Definition at line 239 of file pluginrecipesmanager.c.
m_RecipeCache
ref map<string,ref CacheObject > PluginRecipesManagerBase::m_RecipeCache = new map<string,ref CacheObject > static private
Definition at line 14 of file pluginrecipesmanager.c.
m_RecipeID
int PluginRecipesManagerBase::m_RecipeID private
Definition at line 241 of file pluginrecipesmanager.c.
m_RecipeList
ref array<ref RecipeBase> PluginRecipesManagerBase::m_RecipeList = new array<ref RecipeBase> private
Definition at line 42 of file pluginrecipesmanager.c.
m_RecipeNamesList
ref map<string, int> PluginRecipesManagerBase::m_RecipeNamesList = new map<string, int> static private
Definition at line 43 of file pluginrecipesmanager.c.
m_RecipesInitializedItem
ref map<typename, bool> PluginRecipesManagerBase::m_RecipesInitializedItem = new ref map<typename, bool> static private
Definition at line 15 of file pluginrecipesmanager.c.
m_RecipesMatched
ref array<int> PluginRecipesManagerBase::m_RecipesMatched = new array<int> private
Definition at line 39 of file pluginrecipesmanager.c.
m_RegRecipeIndex
int PluginRecipesManagerBase::m_RegRecipeIndex private
Definition at line 23 of file pluginrecipesmanager.c.
m_ResolvedRecipes
int PluginRecipesManagerBase::m_ResolvedRecipes[MAX_CONCURENT_RECIPES] private
Definition at line 24 of file pluginrecipesmanager.c.
m_sortedIngredients
ItemBase PluginRecipesManagerBase::m_sortedIngredients[MAX_NUMBER_OF_INGREDIENTS] private
Definition at line 37 of file pluginrecipesmanager.c.
m_TestTimer
ref Timer PluginRecipesManagerBase::m_TestTimer private
Definition at line 18 of file pluginrecipesmanager.c.
MAX_CONCURENT_RECIPES
const int PluginRecipesManagerBase::MAX_CONCURENT_RECIPES = 128 private
Definition at line 20 of file pluginrecipesmanager.c.
MAX_INGREDIENTS
const int PluginRecipesManagerBase::MAX_INGREDIENTS = 5 private
Definition at line 21 of file pluginrecipesmanager.c.
Referenced by ClearResults(), and RecipeSanityCheck().
MAX_NUMBER_OF_RECIPES
const int PluginRecipesManagerBase::MAX_NUMBER_OF_RECIPES = GetMaxNumberOfRecipes() private
Definition at line 19 of file pluginrecipesmanager.c.
myTimer1
ref Timer PluginRecipesManagerBase::myTimer1 private
Definition at line 45 of file pluginrecipesmanager.c.