DayzKode: PPELightIntensityParamsNative Class Reference
PPELightIntensityParamsNative Class Reference
g_Game.NightVissionLightParams, does not directly use materials. Controls light multiplication and filmgrain noise intensity (multiplier)
Private Member Functions
override void ApplyValueChanges ()
override int GetPostProcessEffectID ()
override void RegisterMaterialParameters ()
override void SetFinalParameterValue (int parameter_idx)
Overriden to handle the specific exception.
Static Private Attributes
static const int L_0_NVG = 100
static const int L_0_TOXIC_TINT = 200
static const int L_1_NVG = 100
static const int L_1_TOXIC_TINT = 200
static const int PARAM_LIGHT_MULT = 0
static const int PARAM_NOISE_MULT = 1
Detailed Description
g_Game.NightVissionLightParams, does not directly use materials. Controls light multiplication and filmgrain noise intensity (multiplier)
Definition at line 5 of file ppelightintensityparamsnative.c.
Member Function Documentation
ApplyValueChanges()
override void PPELightIntensityParamsNative::ApplyValueChanges () inline private
Definition at line 27 of file ppelightintensityparamsnative.c.
    {
        if (m_UpdatedParameters.Count() > 0)
        {
            SetFinalParameterValue(-1); //unique handling
        }
        m_UpdatedParameters.Clear();
    }
References PPEClassBase::m_UpdatedParameters, and SetFinalParameterValue().
GetPostProcessEffectID()
override int PPELightIntensityParamsNative::GetPostProcessEffectID () inline private
Definition at line 16 of file ppelightintensityparamsnative.c.
    {
        return PPEExceptions.NVLIGHTPARAMS;
    }
RegisterMaterialParameters()
override void PPELightIntensityParamsNative::RegisterMaterialParameters () inline private
Definition at line 21 of file ppelightintensityparamsnative.c.
    {
        RegisterParameterScalarFloat(PARAM_LIGHT_MULT,"lightIntensityMul",1.0,0.0,50.0); //some reasonable values
        RegisterParameterScalarFloat(PARAM_NOISE_MULT,"noiseIntensity",0.0,0.0,50.0); //some reasonable values
    }
References PARAM_LIGHT_MULT, PARAM_NOISE_MULT, and PPEClassBase::RegisterParameterScalarFloat().
SetFinalParameterValue()
override void PPELightIntensityParamsNative::SetFinalParameterValue (int parameter_idx) inline private
Overriden to handle the specific exception.
Definition at line 38 of file ppelightintensityparamsnative.c.
    {
        array<float> array_values = new array<float>;
        for (int i = 0; i < PARAM_NOISE_MULT + 1; i++)
        {
            Param values = GetParameterCommandData(i).GetCurrentValues();
            float value_var_float = Param1<float>.Cast(values).param1;
            array_values.Insert(value_var_float);
        }
        g_Game.NightVissionLightParams(array_values.Get(PARAM_LIGHT_MULT),array_values.Get(PARAM_NOISE_MULT));
        //DbgPrnt("PPEDebug | SetFinalParameterValue | PPELightIntensityParamsNative | float val: " + value_var_float);
    }
References g_Game, PPEMatClassParameterCommandData::GetCurrentValues(), PPEClassBase::GetParameterCommandData(), Param::param1, PARAM_LIGHT_MULT, and PARAM_NOISE_MULT.
Referenced by ApplyValueChanges().
Member Data Documentation
L_0_NVG
const int PPELightIntensityParamsNative::L_0_NVG = 100 static private
Definition at line 11 of file ppelightintensityparamsnative.c.
Referenced by PPERequester_GameplayBase::SetNVMode().
L_0_TOXIC_TINT
const int PPELightIntensityParamsNative::L_0_TOXIC_TINT = 200 static private
Definition at line 12 of file ppelightintensityparamsnative.c.
L_1_NVG
const int PPELightIntensityParamsNative::L_1_NVG = 100 static private
Definition at line 13 of file ppelightintensityparamsnative.c.
Referenced by PPERequester_GameplayBase::SetNVMode().
L_1_TOXIC_TINT
const int PPELightIntensityParamsNative::L_1_TOXIC_TINT = 200 static private
Definition at line 14 of file ppelightintensityparamsnative.c.
PARAM_LIGHT_MULT
const int PPELightIntensityParamsNative::PARAM_LIGHT_MULT = 0 static private
Definition at line 8 of file ppelightintensityparamsnative.c.
Referenced by RegisterMaterialParameters(), SetFinalParameterValue(), and PPERequester_GameplayBase::SetNVMode().
PARAM_NOISE_MULT
const int PPELightIntensityParamsNative::PARAM_NOISE_MULT = 1 static private
Definition at line 9 of file ppelightintensityparamsnative.c.
Referenced by RegisterMaterialParameters(), SetFinalParameterValue(), and PPERequester_GameplayBase::SetNVMode().