DayzKode: ColorManager Class Reference
ColorManager Class Reference
Private Member Functions
void ColorManager ()
int GetItemColor (ItemBase item)
void SetColor (Widget w, int color)
Static Private Member Functions
static ColorManager GetInstance ()
Static Private Attributes
static int BASE_COLOR = ARGB(10, 255, 255, 255)
static int COLOR_DISABLED_PANEL = ARGB(140, 0, 0, 0)
static int COLOR_DISABLED_TEXT = ARGB(100, 255, 255, 255)
static int COLOR_HIGHLIGHT_PANEL = ARGB(255, 0, 0, 0)
static int COLOR_HIGHLIGHT_TEXT = ARGB(255, 200, 0, 0)
static int COLOR_NORMAL_PANEL = ARGB(140, 0, 0, 0)
static int COLOR_NORMAL_TEXT = ARGB(255, 255, 255, 255)
static int COLOR_SELECTED_PANEL = ARGB(255, 200, 0, 0)
static int COLOR_SELECTED_TEXT = ARGB(255, 255, 255, 255)
static int COMBINE_COLOR = ARGB(150, 255, 165, 0)
static int FSWAP_COLOR = ARGB(150, 35, 106, 150)
static int GREEN_COLOR = ARGB(150, 1, 255, 1)
static int ITEM_BACKGROUND_COLOR = ARGB(50, 255, 255, 255)
private static ref ColorManager m_Instance
static int RED_COLOR = ARGB(150, 255, 1, 1)
static int SWAP_COLOR = ARGB(150, 135, 206, 250)
Detailed Description
Definition at line 1 of file colormanager.c.
Constructor & Destructor Documentation
ColorManager()
void ColorManager::ColorManager () inline private
Definition at line 22 of file colormanager.c.
    {
        m_Instance = this;
    }
References m_Instance.
Member Function Documentation
GetInstance()
static ColorManager ColorManager::GetInstance () inline static private
Definition at line 27 of file colormanager.c.
    {
        return m_Instance;
    }
References m_Instance.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ItemManager::SetIconTemperature(), ItemManager::SetTemperature(), and Icon::ShowActionMenuCombine().
GetItemColor()
int ColorManager::GetItemColor (ItemBase item) inline private
Definition at line 50 of file colormanager.c.
    {
        int color = -1;
        ItemBase dragged_item = ItemBase.Cast( ItemManager.GetInstance().GetDraggedItem() );
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( dragged_item )
            return 0;
        // if item icon is main icon (view, viewgrid )
        if ( item.GetHierarchyParent() && item.GetHierarchyParent() != player )
        {
            color = -1;
        }
        if ( item )
        {
            float temperature = item.GetTemperature();
            if ( temperature )
            {
                color = GetTemperatureColor( temperature );
            }
        }
        return color;
    }
References ItemManager::GetDraggedItem(), GetGame(), ItemManager::GetInstance(), GetPlayer(), and GetTemperatureColor().
Referenced by ItemManager::SetIconTemperature(), and ItemManager::SetTemperature().
SetColor()
void ColorManager::SetColor (Widget w, int color) inline private
Definition at line 32 of file colormanager.c.
    {
        if( w.FindAnyWidget( "Selected" ) )
        {
            w.FindAnyWidget( "Selected" ).SetColor( color );
        }
        else
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Selected" );
            Widget w2 = w.GetParent().FindAnyWidget( name );
            if( w2 )
            {
                w2.SetColor( color );
            }
        }
    }
References name, and string::Replace().
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), and Icon::ShowActionMenuCombine().
Member Data Documentation
BASE_COLOR
int ColorManager::BASE_COLOR = ARGB(10, 255, 255, 255) static private
Definition at line 15 of file colormanager.c.
Referenced by Icon::CreateWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), and ItemManager::SetIconTemperature().
COLOR_DISABLED_PANEL
int ColorManager::COLOR_DISABLED_PANEL = ARGB(140, 0, 0, 0) static private
Definition at line 12 of file colormanager.c.
COLOR_DISABLED_TEXT
int ColorManager::COLOR_DISABLED_TEXT = ARGB(100, 255, 255, 255) static private
Definition at line 11 of file colormanager.c.
Referenced by UIScriptedMenu::ColorDisable(), ColorDisable(), ServerBrowserTab::ColorDisable(), UIScriptedMenu::ColorDisabled(), and UIScriptedMenu::ColorWhite().
COLOR_HIGHLIGHT_PANEL
int ColorManager::COLOR_HIGHLIGHT_PANEL = ARGB(255, 0, 0, 0) static private
Definition at line 8 of file colormanager.c.
COLOR_HIGHLIGHT_TEXT
int ColorManager::COLOR_HIGHLIGHT_TEXT = ARGB(255, 200, 0, 0) static private
Definition at line 7 of file colormanager.c.
COLOR_NORMAL_PANEL
int ColorManager::COLOR_NORMAL_PANEL = ARGB(140, 0, 0, 0) static private
Definition at line 6 of file colormanager.c.
COLOR_NORMAL_TEXT
int ColorManager::COLOR_NORMAL_TEXT = ARGB(255, 255, 255, 255) static private
Definition at line 5 of file colormanager.c.
Referenced by UIScriptedMenu::ColorNormal(), and UIScriptedMenu::ColorWhite().
COLOR_SELECTED_PANEL
int ColorManager::COLOR_SELECTED_PANEL = ARGB(255, 200, 0, 0) static private
Definition at line 10 of file colormanager.c.
COLOR_SELECTED_TEXT
int ColorManager::COLOR_SELECTED_TEXT = ARGB(255, 255, 255, 255) static private
Definition at line 9 of file colormanager.c.
COMBINE_COLOR
int ColorManager::COMBINE_COLOR = ARGB(150, 255, 165, 0) static private
Definition at line 20 of file colormanager.c.
Referenced by Icon::DraggingOver(), PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), and Icon::ShowActionMenuCombine().
FSWAP_COLOR
int ColorManager::FSWAP_COLOR = ARGB(150, 35, 106, 150) static private
Definition at line 19 of file colormanager.c.
Referenced by Icon::DraggingOver(), and Icon::DraggingOverSwap().
GREEN_COLOR
int ColorManager::GREEN_COLOR = ARGB(150, 1, 255, 1) static private
Definition at line 17 of file colormanager.c.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), and VicinityContainer::DraggingOverHeader().
ITEM_BACKGROUND_COLOR
int ColorManager::ITEM_BACKGROUND_COLOR = ARGB(50, 255, 255, 255) static private
Definition at line 14 of file colormanager.c.
m_Instance
private static ref ColorManager ColorManager::m_Instance static private
Definition at line 3 of file colormanager.c.
Referenced by ColorManager(), and GetInstance().
RED_COLOR
int ColorManager::RED_COLOR = ARGB(150, 255, 1, 1) static private
Definition at line 16 of file colormanager.c.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), and Icon::ShowActionMenuCombine().
SWAP_COLOR
int ColorManager::SWAP_COLOR = ARGB(150, 135, 206, 250) static private
Definition at line 18 of file colormanager.c.
Referenced by Icon::DraggingOver(), PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), and Icon::DraggingOverSwap().