DayzKode: HudDebugWinBase Class Reference
HudDebugWinBase Class Reference
Private Member Functions
void AddValue (string classname, int food_stage, int agents, float amount)
void AddValue (string title, string value)
void AddValue (string title, string value, string value2)
void ClearValues ()
void ClearValues ()
void ClearValues ()
void FitWindow ()
void FitWindow ()
void FitWindow ()
void FitWindowByContent (TextListboxWidget wgt)
array< string > GetAgentsArray (int agents)
int GetType ()
override int GetType ()
override int GetType ()
override int GetType ()
override int GetType ()
override int GetType ()
override int GetType ()
void Hide ()
override void Hide ()
override void Hide ()
override void Hide ()
override void Hide ()
void HudDebugWinBase (Widget widget_root)
void HudDebugWinCharDebug (Widget widget_root)
void HudDebugWinCharLevels (Widget widget_root)
void HudDebugWinCharStats (Widget widget_root)
void HudDebugWinCharStomach (Widget widget_root)
void HudDebugWinTemperature (Widget widget_root)
void HudDebugWinVersion (Widget widget_root)
void Init (Widget widget_root)
bool IsVisible ()
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
void ResetStats ()
void RPCChangeStat (string stat, float value)
void SetContentValues ()
void SetRPCSent ()
void SetUpdate (bool state)
override void SetUpdate (bool state)
override void SetUpdate (bool state)
override void SetUpdate (bool state)
override void SetUpdate (bool state)
void SetupValues ()
void SetValueListSize (int x, int y, TextListboxWidget wgt)
void SetValues ()
void Show ()
override void Show ()
override void Show ()
override void Show ()
override void Show ()
void Update ()
override void Update ()
override void Update ()
override void Update ()
override void Update ()
override void Update ()
override void Update ()
void UpdateValues ()
void ~HudDebugWinCharDebug ()
void ~HudDebugWinCharLevels ()
void ~HudDebugWinCharStats ()
void ~HudDebugWinCharStomach ()
void ~HudDebugWinTemperature ()
void ~HudDebugWinVersion ()
Private Attributes
bool m_ChangingSlider
private TextWidget m_ClipboardTextWidget
private TextWidget m_EnviroTextWidget
private PluginDeveloper m_ModuleDeveloper
private TextWidget m_PlayerPosTextWidget
protected PluginDeveloperSync m_PluginDeveloperSync
bool m_Populated
protected bool m_RPCSent
protected bool m_Show
ref map< ref SliderWidget, string > m_SliderWidgets = new map<ref SliderWidget, string>
ref array< ref TextWidget > m_StatValues = new array<ref TextWidget>
ref map< ref EditBoxWidget, string > m_StatValuesInput = new map<ref EditBoxWidget, string>
ref array< ref Widget > m_StatWidgets = new array<ref Widget>
private TextWidget m_VersionTextWidget
TextWidget m_WgtOverall
Widget m_WgtPanel
Widget m_WgtRoot
TextListboxWidget m_WgtValues
Detailed Description
Definition at line 1 of file huddebugwinbase.c.
Constructor & Destructor Documentation
HudDebugWinBase()
void HudDebugWinBase::HudDebugWinBase (Widget widget_root) inline private
Definition at line 10 of file huddebugwinbase.c.
    {
        m_WgtRoot = widget_root;
    }
References m_WgtRoot.
~HudDebugWinCharDebug()
void HudDebugWinBase::~HudDebugWinCharDebug () inline private
Definition at line 20 of file huddebugwinchardebug.c.
    {
    }
~HudDebugWinCharLevels()
void HudDebugWinBase::~HudDebugWinCharLevels () inline private
Definition at line 18 of file huddebugwincharlevels.c.
    {
        SetUpdate( false );
    }
References SetUpdate().
~HudDebugWinCharStats()
void HudDebugWinBase::~HudDebugWinCharStats () inline private
Definition at line 25 of file huddebugwincharstats.c.
    {
        SetUpdate( false );
    }
References SetUpdate().
~HudDebugWinCharStomach()
void HudDebugWinBase::~HudDebugWinCharStomach () inline private
Definition at line 19 of file huddebugwincharstomach.c.
    {
        SetUpdate( false );
    }
References SetUpdate().
~HudDebugWinTemperature()
void HudDebugWinBase::~HudDebugWinTemperature () inline private
Definition at line 20 of file huddebugwintemperature.c.
    {
    }
~HudDebugWinVersion()
void HudDebugWinBase::~HudDebugWinVersion () inline private
Definition at line 22 of file huddebugwinversion.c.
    {
    }
Member Function Documentation
AddValue() [1/3]
void HudDebugWinBase::AddValue (string classname, int food_stage, int agents, float amount) inline private
Definition at line 130 of file huddebugwincharstomach.c.
    {
        int index = m_WgtValues.AddItem( classname, NULL, 0 );
        string stage = typename.EnumToString(FoodStageType, food_stage) + "(" + food_stage.ToString()+")";;
        m_WgtValues.SetItem( index, amount.ToString(), NULL, 1 );
        m_WgtValues.SetItem( index,stage , NULL, 2 );
        array<string> agent_list = GetAgentsArray(agents);
        string agent_line = "("+agents.ToString()+") ";
        for(int i = 0; i < agent_list.Count();i++)
        {
            agent_line +=  "," +agent_list.Get(i);
        }
        m_WgtValues.SetItem( index, agent_line , NULL, 3);
    }
References GetAgentsArray(), and float::ToString().
AddValue() [2/3]
void HudDebugWinBase::AddValue (string title, string value) inline private
Definition at line 176 of file huddebugwincharstats.c.
    {
        Widget widget = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/debug/day_z_hud_debug_stat.layout", m_WgtPanel );
        TextWidget tw = TextWidget.Cast(widget.FindAnyWidget("StatName"));
        tw.SetText(title);
        m_StatWidgets.Insert(widget);
        TextWidget tw_output = TextWidget.Cast(widget.FindAnyWidget("OutputValue"));
        m_StatValues.Insert(tw_output);
        EditBoxWidget ebw_input = EditBoxWidget.Cast(widget.FindAnyWidget("InputValue"));
        m_StatValuesInput.Insert(ebw_input, title );
        SliderWidget sw = SliderWidget.Cast(widget.FindAnyWidget("StatSlider"));
        m_SliderWidgets.Insert(sw,title );
        //int index = m_WgtValues.AddItem( title, NULL, 0 );
        //m_WgtValues.SetItem( index, value, NULL, 1 );
        AutoHeightSpacer WgtModifiersContent_panel_script;
        m_WgtPanel.GetScript( WgtModifiersContent_panel_script );
        WgtModifiersContent_panel_script.Update();
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and AutoHeightSpacer::Update().
AddValue() [3/3]
void HudDebugWinBase::AddValue (string title, string value, string value2) inline private
Definition at line 118 of file huddebugwincharlevels.c.
    {
        int index = m_WgtValues.AddItem( title, NULL, 0 );
        m_WgtValues.SetItem( index, value, NULL, 1 );
        m_WgtValues.SetItem( index, value2, NULL, 2 );
    }
Referenced by SetContentValues(), SetupValues(), and SetValues().
ClearValues() [1/3]
void HudDebugWinBase::ClearValues () inline private
Definition at line 125 of file huddebugwincharlevels.c.
    {
        m_WgtValues.ClearItems();
    }
Referenced by SetContentValues(), and SetValues().
ClearValues() [2/3]
void HudDebugWinBase::ClearValues () inline private
Definition at line 202 of file huddebugwincharstats.c.
    {
        m_StatWidgets.Clear();
        //m_WgtValues.ClearItems();
    }
ClearValues() [3/3]
void HudDebugWinBase::ClearValues () inline private
Definition at line 161 of file huddebugwincharstomach.c.
    {
        m_WgtValues.ClearItems();
    }
FitWindow() [1/3]
void HudDebugWinBase::FitWindow () inline private
Definition at line 130 of file huddebugwincharlevels.c.
    {
        //FitWindowByContent( m_WgtValues );
    }
Referenced by HudDebugWinCharLevels(), SetModifiers(), SetupValues(), and SetValues().
FitWindow() [2/3]
void HudDebugWinBase::FitWindow () inline private
Definition at line 208 of file huddebugwincharstats.c.
    {
        TextListboxWidget wgt = TextListboxWidget.Cast(m_WgtPanel);
        if(wgt)
            FitWindowByContent( wgt );
    }
References FitWindowByContent().
FitWindow() [3/3]
void HudDebugWinBase::FitWindow () inline private
Definition at line 166 of file huddebugwincharstomach.c.
    {
        FitWindowByContent( m_WgtValues );
    }
References FitWindowByContent().
FitWindowByContent()
void HudDebugWinBase::FitWindowByContent (TextListboxWidget wgt) inline private
Definition at line 74 of file huddebugwinbase.c.
    {
        int size_of_value = 17;
        SetValueListSize( 250, size_of_value * wgt.GetNumItems(), wgt );
    }
References SetValueListSize().
Referenced by FitWindow(), and FitWindow().
GetAgentsArray()
array< string > HudDebugWinBase::GetAgentsArray (int agents) inline private
Definition at line 147 of file huddebugwincharstomach.c.
    {
        array<string> list = new array<string>;
        for(int i = 0; i < 32; i++)
        {
            int agent = agents & (1 << i);
            if(agent)
            {
                list.Insert(PluginTransmissionAgents.GetNameByID(agent));
            }
        }
        return list;
    }
Referenced by AddValue().
GetType() [1/7]
int HudDebugWinBase::GetType () inline private
Definition at line 18 of file huddebugwinbase.c.
    {
        return HudDebug.HUD_WIN_UNDEFINED;
    }
References HudDebug().
Referenced by PanelHide(), and PanelShow().
GetType() [2/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 49 of file huddebugwinchardebug.c.
    {
        return HudDebug.HUD_WIN_CHAR_DEBUG;
    }
References HudDebug().
GetType() [3/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 27 of file huddebugwincharlevels.c.
    {
        return HudDebug.HUD_WIN_CHAR_LEVELS;
    }
References HudDebug().
GetType() [4/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 34 of file huddebugwincharstats.c.
    {
        return HudDebug.HUD_WIN_CHAR_STATS;
    }
References HudDebug().
GetType() [5/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 28 of file huddebugwincharstomach.c.
    {
        return HudDebug.HUD_WIN_CHAR_STOMACH;
    }
References HudDebug().
GetType() [6/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 94 of file huddebugwintemperature.c.
    {
        return HudDebug.HUD_WIN_TEMPERATURE;
    }
References HudDebug().
GetType() [7/7]
override int HudDebugWinBase::GetType () inline private
Definition at line 37 of file huddebugwinversion.c.
    {
        return HudDebug.HUD_WIN_VERSION;
    }
References HudDebug().
Hide() [1/5]
void HudDebugWinBase::Hide () inline private
Definition at line 57 of file huddebugwinbase.c.
    {
        m_WgtRoot.Show(false);
        m_Show = false;
    }
References m_Show, and m_WgtRoot.
Referenced by PanelHide().
Hide() [2/5]
override void HudDebugWinBase::Hide () inline private
Definition at line 47 of file huddebugwincharlevels.c.
    {
        super.Hide();
        //Print("Hide()");
        SetUpdate( false );
    }
References SetUpdate().
Hide() [3/5]
override void HudDebugWinBase::Hide () inline private
Definition at line 54 of file huddebugwincharstats.c.
    {
        super.Hide();
        //Print("Hide()");
        SetUpdate( false );
    }
References SetUpdate().
Hide() [4/5]
override void HudDebugWinBase::Hide () inline private
Definition at line 48 of file huddebugwincharstomach.c.
    {
        super.Hide();
        //Print("Hide()");
        SetUpdate( false );
    }
References SetUpdate().
Hide() [5/5]
override void HudDebugWinBase::Hide () inline private
Definition at line 62 of file huddebugwintemperature.c.
    {
        super.Hide();
        SetUpdate( false );
    }
References SetUpdate().
HudDebugWinCharDebug()
void HudDebugWinBase::HudDebugWinCharDebug (Widget widget_root) inline private
Definition at line 11 of file huddebugwinchardebug.c.
    {
        m_PlayerPosTextWidget = TextWidget.Cast( widget_root.FindAnyWidget("txt_PlayerPos") );
        m_ClipboardTextWidget = TextWidget.Cast( widget_root.FindAnyWidget("txt_Clipboard") );
    }
HudDebugWinCharLevels()
void HudDebugWinBase::HudDebugWinCharLevels (Widget widget_root) inline private
Definition at line 8 of file huddebugwincharlevels.c.
    {
        m_WgtValues = TextListboxWidget.Cast( widget_root.FindAnyWidget("txl_CharLevels_Values") );
        FitWindow();
    }
References FitWindow().
HudDebugWinCharStats()
void HudDebugWinBase::HudDebugWinCharStats (Widget widget_root) inline private
Definition at line 15 of file huddebugwincharstats.c.
    {
        m_WgtRoot = widget_root;
        m_WgtPanel = Widget.Cast(m_WgtRoot.FindAnyWidget("Stats") );
        //FitWindow();
    }
References m_WgtRoot.
HudDebugWinCharStomach()
void HudDebugWinBase::HudDebugWinCharStomach (Widget widget_root) inline private
Definition at line 9 of file huddebugwincharstomach.c.
    {
        m_WgtValues = TextListboxWidget.Cast( widget_root.FindAnyWidget("txl_StomachContents") );
        m_WgtOverall = TextWidget.Cast( widget_root.FindAnyWidget("InfoOverall") );
        //FitWindow();
    }
HudDebugWinTemperature()
void HudDebugWinBase::HudDebugWinTemperature (Widget widget_root) inline private
Definition at line 10 of file huddebugwintemperature.c.
    {
        m_EnviroTextWidget = TextWidget.Cast( widget_root.FindAnyWidget("txt_Temp") );
        m_PluginDeveloperSync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
    }
References GetPlugin(), and m_PluginDeveloperSync.
HudDebugWinVersion()
void HudDebugWinBase::HudDebugWinVersion (Widget widget_root) inline private
Definition at line 10 of file huddebugwinversion.c.
    {
        m_VersionTextWidget = TextWidget.Cast( widget_root.FindAnyWidget("txt_Version") );
        string version;
        g_Game.GetVersion(version);
        m_VersionTextWidget.SetText(string.Format("exe: %1 | scripts: %2", version, GetPBOAPI().GetPBOVersion("dta\\scripts.pbo")));
    }
References g_Game, GetPBOAPI(), and GetPBOVersion().
Init()
void HudDebugWinBase::Init (Widget widget_root) private
IsVisible()
bool HudDebugWinBase::IsVisible () inline private
Definition at line 66 of file huddebugwinbase.c.
    {
        return m_WgtRoot.IsVisible();
    }
References m_WgtRoot.
OnChange()
bool HudDebugWinBase::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 225 of file huddebugwincharstats.c.
    {
        if ( m_StatValuesInput.Contains(EditBoxWidget.Cast(w)) && finished )
        {
            EditBoxWidget ebw = EditBoxWidget.Cast(w);
            RPCChangeStat(m_StatValuesInput.Get(EditBoxWidget.Cast(w)), ebw.GetText().ToFloat());
            return true;
        }
        if (m_SliderWidgets.Contains(SliderWidget.Cast(w)))
        {
            m_ChangingSlider = true;
            string stat_name = m_SliderWidgets.Get(SliderWidget.Cast(w));
            SliderWidget sw = SliderWidget.Cast(w);
            PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
            for ( int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++ )
            {
                string label = player.m_PlayerStats.GetPCO().Get().Get( i ).GetLabel();
                if(label == stat_name)
                {
                    float stat_min = player.m_PlayerStats.GetPCO().Get().Get( i ).GetMin();
                    float stat_max = player.m_PlayerStats.GetPCO().Get().Get( i ).GetMax();
                    float current_value_norm = sw.GetCurrent() / 100;
                    float current_value_abs = stat_min + (stat_max - stat_min) * current_value_norm;
                    RPCChangeStat(label, current_value_abs);
                }
            }
            //Print("OnChange " + finished);
            if(finished)
                m_ChangingSlider = false;
        }
        return false;
    }
References Count, Get(), GetGame(), GetPlayer(), and RPCChangeStat().
OnClick()
bool HudDebugWinBase::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 215 of file huddebugwincharstats.c.
    {
        if ( w.GetName() == "ResetStats" )
        {
            ResetStats();
            return true;
        }
        return false;
    }
References ResetStats().
ResetStats()
void HudDebugWinBase::ResetStats () inline private
Definition at line 261 of file huddebugwincharstats.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        ref Param1<bool> params = new Param1<bool>( false );
        if ( player )
        {
            player.RPCSingleParam( ERPCs.DEV_RPC_STATS_RESET, params, true );
        }
    }
References GetGame(), and GetPlayer().
Referenced by OnClick().
RPCChangeStat()
void HudDebugWinBase::RPCChangeStat (string stat, float value) inline private
Definition at line 274 of file huddebugwincharstats.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        ref Param2<string, float> params = new Param2<string, float>( stat, value );
        if ( player )
        {
            player.RPCSingleParam( ERPCs.DEV_RPC_STAT_SET, params, true );
        }
    }
References GetGame(), and GetPlayer().
Referenced by OnChange().
SetContentValues()
void HudDebugWinBase::SetContentValues () inline private
Definition at line 99 of file huddebugwincharstomach.c.
    {
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //clear window
        ClearValues();
        for ( int i = 0; i < developer_sync.m_PlayerStomachSynced.Count() - 1; i++ )
        {
            //new Param4<int,int,int,float>(id, food_stage, agents, amount);
            Param4<int,int,int,float> p4 = Param4<int,int,int,float>.Cast(developer_sync.m_PlayerStomachSynced.Get(i));
            AddValue( PlayerStomach.GetClassnameFromID(p4.param1), p4.param2, p4.param3, p4.param4);
        }
        if( developer_sync.m_PlayerStomachSynced.Count() )
        {
            int last_index = developer_sync.m_PlayerStomachSynced.Count() - 1;
            Param1<float> p1 = Param1<float>.Cast(developer_sync.m_PlayerStomachSynced.Get(last_index));
            m_WgtOverall.SetText("Overall volume:" + p1.param1.ToString());
        }
        else
        {
            m_WgtOverall.SetText("");
        }
        //fit to screen
        //FitWindow();
    }
References AddValue(), ClearValues(), GetPlugin(), and PlayerStomach().
Referenced by Update().
SetRPCSent()
void HudDebugWinBase::SetRPCSent () inline private
Definition at line 39 of file huddebugwinbase.c.
    {
        m_RPCSent = true;
    }
References m_RPCSent.
Referenced by SetUpdate(), and SetUpdate().
SetUpdate() [1/5]
void HudDebugWinBase::SetUpdate (bool state) private
Referenced by Hide(), Hide(), Show(), Show(), Update(), ~HudDebugWinCharAgents(), ~HudDebugWinCharLevels(), ~HudDebugWinCharModifiers(), ~HudDebugWinCharStats(), and ~HudDebugWinCharStomach().
SetUpdate() [2/5]
override void HudDebugWinBase::SetUpdate (bool state) inline private
Definition at line 59 of file huddebugwincharlevels.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<bool> params = new Param1<bool>( state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_LEVELS_UPDATE, params, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( developer_sync )
            {
                developer_sync.EnableUpdate( state, ERPCs.DEV_LEVELS_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [3/5]
override void HudDebugWinBase::SetUpdate (bool state) inline private
Definition at line 66 of file huddebugwincharstats.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<bool> params = new Param1<bool>( state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_STATS_UPDATE, params, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( developer_sync )
            {
                developer_sync.EnableUpdate( state, ERPCs.DEV_STATS_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [4/5]
override void HudDebugWinBase::SetUpdate (bool state) inline private
Definition at line 60 of file huddebugwincharstomach.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<bool> params = new Param1<bool>( state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_STOMACH_UPDATE, params, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( developer_sync )
            {
                developer_sync.EnableUpdate( state, ERPCs.DEV_STOMACH_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), GetPlugin(), and SetRPCSent().
SetUpdate() [5/5]
override void HudDebugWinBase::SetUpdate (bool state) inline private
Definition at line 27 of file huddebugwintemperature.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            CachedObjectsParams.PARAM1_BOOL.param1 = state;
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_TEMP_UPDATE, CachedObjectsParams.PARAM1_BOOL, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( m_PluginDeveloperSync )
            {
                m_PluginDeveloperSync.EnableUpdate( state, ERPCs.DEV_TEMP_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), m_PluginDeveloperSync, CachedObjectsParams::PARAM1_BOOL, and SetRPCSent().
SetupValues()
void HudDebugWinBase::SetupValues () inline private
Definition at line 109 of file huddebugwincharstats.c.
    {
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //clear window
        //ClearValues();
        if ( developer_sync.m_PlayerStatsSynced.Count() > 0 )
        {
            //set
            for ( int i = 0; i < developer_sync.m_PlayerStatsSynced.Count(); i++ )
            {
                AddValue( developer_sync.m_PlayerStatsSynced.Get( i ).GetName(), developer_sync.m_PlayerStatsSynced.Get( i ).GetValue().ToString() );
            }
                    //fit to screen
            FitWindow();
            m_Populated = true;
        }
    }
References AddValue(), FitWindow(), and GetPlugin().
Referenced by Update().
SetValueListSize()
void HudDebugWinBase::SetValueListSize (int x, int y, TextListboxWidget wgt) inline private
Definition at line 83 of file huddebugwinbase.c.
    {
        int offset = 10;
        int size_of_title = 20;
        wgt.SetSize( x, y );
        int root_size_x = x + ( 2 * offset );
        int root_size_y = y + ( 2 * offset ) + size_of_title;
        m_WgtRoot.SetSize( root_size_x, root_size_y );
    }
References m_WgtRoot, x, and y.
Referenced by FitWindowByContent().
SetValues()
void HudDebugWinBase::SetValues () inline private
Definition at line 97 of file huddebugwincharlevels.c.
    {
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //clear window
        ClearValues();
        if ( developer_sync.m_PlayerLevelsSynced.Count() > 0 )
        {
            //set
            for ( int i = 0; i < developer_sync.m_PlayerLevelsSynced.Count(); i++ )
            {
                string bar = MiscGameplayFunctions.ValueToBar(developer_sync.m_PlayerLevelsSynced.Get( i ).GetValue2());
                AddValue( developer_sync.m_PlayerLevelsSynced.Get( i ).GetName(), developer_sync.m_PlayerLevelsSynced.Get( i ).GetValue().ToString() ,bar );
            }
        }
        //fit to screen
        FitWindow();
    }
References AddValue(), ClearValues(), FitWindow(), and GetPlugin().
Referenced by Update().
Show() [1/5]
void HudDebugWinBase::Show () inline private
Definition at line 48 of file huddebugwinbase.c.
    {
        m_WgtRoot.Show(true);
        m_Show = true;
    }
References m_Show, and m_WgtRoot.
Referenced by PanelShow().
Show() [2/5]
override void HudDebugWinBase::Show () inline private
Definition at line 35 of file huddebugwincharlevels.c.
    {
        super.Show();
        //Print("Show()");
        SetUpdate( true );
    }
References SetUpdate().
Show() [3/5]
override void HudDebugWinBase::Show () inline private
Definition at line 42 of file huddebugwincharstats.c.
    {
        super.Show();
        //Print("Show()");
        SetUpdate( true );
    }
References SetUpdate().
Show() [4/5]
override void HudDebugWinBase::Show () inline private
Definition at line 36 of file huddebugwincharstomach.c.
    {
        super.Show();
        //Print("Show()");
        SetUpdate( true );
    }
References SetUpdate().
Show() [5/5]
override void HudDebugWinBase::Show () inline private
Definition at line 55 of file huddebugwintemperature.c.
    {
        super.Show();
        SetUpdate( true );
    }
References SetUpdate().
Update() [1/7]
void HudDebugWinBase::Update () inline private
Definition at line 27 of file huddebugwinbase.c.
    {
        if(m_Show && !m_RPCSent)
        {
            SetUpdate(true);
        }
    }
References m_RPCSent, m_Show, and SetUpdate().
Update() [2/7]
override void HudDebugWinBase::Update () inline private
Definition at line 27 of file huddebugwinchardebug.c.
    {
        super.Update();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player != NULL )
        {
            vector pos = player.GetPosition();
            string pos_str = "Pos: " + pos[0].ToString() + " " + pos[2].ToString();
            m_PlayerPosTextWidget.SetText(pos_str);
        }
        string clipboard;
        GetGame().CopyFromClipboard(clipboard);
        clipboard = clipboard.Substring( 0, Math.Min( clipboard.Length(), 128 ) );  //max 128 chars
        clipboard = "Clipboard: " + clipboard;
        m_ClipboardTextWidget.SetText(clipboard);
    }
References CGame::CopyFromClipboard(), GetGame(), GetPlayer(), string::Length(), Math::Min(), string::Substring(), and vector::ToString().
Update() [3/7]
override void HudDebugWinBase::Update () inline private
Definition at line 87 of file huddebugwincharlevels.c.
    {
        super.Update();
        //Print("Update()");
        //refresh notifiers
        SetValues();
    }
References SetValues().
Update() [4/7]
override void HudDebugWinBase::Update () inline private
Definition at line 94 of file huddebugwincharstats.c.
    {
        super.Update();
        //Print("panel:" + m_WgtPanel);
        //Print("Update()");
        //refresh notifiers
        if(!m_Populated)
            SetupValues();
        UpdateValues();
    }
References SetupValues(), and UpdateValues().
Update() [5/7]
override void HudDebugWinBase::Update () inline private
Definition at line 88 of file huddebugwincharstomach.c.
    {
        super.Update();
        //Print("Update()");
        //refresh notifiers
        SetContentValues();
    }
References SetContentValues().
Update() [6/7]
override void HudDebugWinBase::Update () inline private
Definition at line 73 of file huddebugwintemperature.c.
    {
        super.Update();
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        m_EnviroTextWidget.SetText(developer_sync.m_EnvironmentDebugMessage);
        int sX, sY;
        m_EnviroTextWidget.GetTextSize(sX, sY);
        m_EnviroTextWidget.SetSize(sX, sY);
        AutoHeightSpacer spacer;
        m_WgtRoot.GetScript(spacer);
        if (spacer)
        {
            spacer.Update();
        }
    }
References GetPlugin(), m_WgtRoot, and AutoHeightSpacer::Update().
Update() [7/7]
override void HudDebugWinBase::Update () inline private
Definition at line 29 of file huddebugwinversion.c.
    {
        super.Update();
    }
UpdateValues()
void HudDebugWinBase::UpdateValues () inline private
Definition at line 130 of file huddebugwincharstats.c.
    {
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        if ( developer_sync.m_PlayerStatsSynced.Count() > 0 )
        {
            for ( int i = 0; i < developer_sync.m_PlayerStatsSynced.Count(); i++ )
            {
                string stat_name = developer_sync.m_PlayerStatsSynced.Get( i ).GetName();
                float val_norm = developer_sync.m_PlayerStatsSynced.Get( i ).GetValueNorm();
                float value = developer_sync.m_PlayerStatsSynced.Get( i ).GetValue();
                if( stat_name == "BloodType" )
                {
                    string type, name;
                    bool positive;
                    name = value.ToString();
                    name += "("+BloodTypes.GetBloodTypeName( Math.Round(value), type, positive)+")";
                    m_StatValues.Get(i).SetText(name);
                }
                else
                {
                    m_StatValues.Get(i).SetText(value.ToString());
                }
                if(!m_ChangingSlider)
                    m_SliderWidgets.GetKeyByValue(stat_name).SetCurrent(val_norm * 100);
                /*
                EditBoxWidget w;
                w.
                AddValue( developer_sync.m_PlayerStatsSynced.Get( i ).GetName(), developer_sync.m_PlayerStatsSynced.Get( i ).GetValue().ToString() );
                */
            }
        }
    }
References string::Get(), BloodTypes::GetBloodTypeName(), GetPlugin(), name, Math::Round(), and float::ToString().
Referenced by Update().
Member Data Documentation
m_ChangingSlider
bool HudDebugWinBase::m_ChangingSlider private
Definition at line 10 of file huddebugwincharstats.c.
m_ClipboardTextWidget
private TextWidget HudDebugWinBase::m_ClipboardTextWidget private
Definition at line 6 of file huddebugwinchardebug.c.
m_EnviroTextWidget
private TextWidget HudDebugWinBase::m_EnviroTextWidget private
Definition at line 5 of file huddebugwintemperature.c.
m_ModuleDeveloper
private PluginDeveloper HudDebugWinBase::m_ModuleDeveloper private
Definition at line 3 of file huddebugwinchardebug.c.
m_PlayerPosTextWidget
private TextWidget HudDebugWinBase::m_PlayerPosTextWidget private
Definition at line 5 of file huddebugwinchardebug.c.
m_PluginDeveloperSync
protected PluginDeveloperSync HudDebugWinBase::m_PluginDeveloperSync private
Definition at line 6 of file huddebugwintemperature.c.
m_Populated
bool HudDebugWinBase::m_Populated private
Definition at line 9 of file huddebugwincharstats.c.
m_RPCSent
protected bool HudDebugWinBase::m_RPCSent private
Definition at line 5 of file huddebugwinbase.c.
Referenced by SetRPCSent(), and Update().
m_Show
protected bool HudDebugWinBase::m_Show private
Definition at line 4 of file huddebugwinbase.c.
Referenced by Hide(), Show(), and Update().
m_SliderWidgets
ref map<ref SliderWidget, string> HudDebugWinBase::m_SliderWidgets = new map<ref SliderWidget, string> private
Definition at line 6 of file huddebugwincharstats.c.
m_StatValues
ref array<ref TextWidget> HudDebugWinBase::m_StatValues = new array<ref TextWidget> private
Definition at line 7 of file huddebugwincharstats.c.
m_StatValuesInput
ref map<ref EditBoxWidget, string> HudDebugWinBase::m_StatValuesInput = new map<ref EditBoxWidget, string> private
Definition at line 8 of file huddebugwincharstats.c.
m_StatWidgets
ref array<ref Widget> HudDebugWinBase::m_StatWidgets = new array<ref Widget> private
Definition at line 5 of file huddebugwincharstats.c.
m_VersionTextWidget
private TextWidget HudDebugWinBase::m_VersionTextWidget private
Definition at line 5 of file huddebugwinversion.c.
m_WgtOverall
TextWidget HudDebugWinBase::m_WgtOverall private
Definition at line 4 of file huddebugwincharstomach.c.
m_WgtPanel
Widget HudDebugWinBase::m_WgtPanel private
Definition at line 4 of file huddebugwincharstats.c.
m_WgtRoot
Widget HudDebugWinBase::m_WgtRoot private
Definition at line 3 of file huddebugwinbase.c.
Referenced by Hide(), HudDebugWinBase(), IsVisible(), SetValueListSize(), and Show().
m_WgtValues
TextListboxWidget HudDebugWinBase::m_WgtValues private
Definition at line 3 of file huddebugwincharlevels.c.