DayzKode: Bot Class Reference
Bot Class Reference
Private Member Functions
void Bot (PlayerBase ow)
void DelayedStart (float ms)
protected void OnDelayedStart ()
void OnTimer ()
protected void OnTrigger ()
void OnUpdate (float dt)
bool ProcessEvent (BotEventBase e)
void SetInstanceType (DayZPlayerInstanceType t)
void Start (bool use_trigger, BotTrigger trigger=null)
void Stop ()
void InitFSM ()
Private Attributes
protected const float c_TriggerTimeoutMS = 1000.0
protected const float c_UpdateMS = 16.0
protected ref BotStateBase m_BotTest = null
protected ref BotTrigger m_BotTrigger = null
protected ref BotFSM m_FSM = null
protected DayZPlayerInstanceType m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT
PlayerBase m_Owner = null
protected ref Timer m_Timer = new Timer
protected bool m_Triggered = false
protected bool m_UseTrigger = false
Detailed Description
Definition at line 18 of file bot.c.
Constructor & Destructor Documentation
Bot()
void Bot::Bot (PlayerBase ow) inline private
Definition at line 32 of file bot.c.
    {
        m_Owner = ow;
    }
References m_Owner.
Member Function Documentation
DelayedStart()
void Bot::DelayedStart (float ms) inline private
Definition at line 62 of file bot.c.
    {
        m_Timer.Run(ms / 1000.0, this, "OnDelayedStart", null, false);
    }
References m_Timer.
InitFSM()
void Bot::InitFSM () inline private
transition table
Definition at line 126 of file bot.c.
References m_BotTest, and m_FSM.
Referenced by Start().
OnDelayedStart()
protected void Bot::OnDelayedStart () inline private
Definition at line 67 of file bot.c.
    {
        Start(false, null);
        ProcessEvent(new BotEventStart(m_Owner));
        m_UseTrigger = false;
    }
References m_Owner, m_UseTrigger, ProcessEvent(), and Start().
OnTimer()
void Bot::OnTimer () inline private
Definition at line 119 of file bot.c.
    {
        //m_FSM.GetCurrentState().OnUpdate(c_UpdateMS / 1000.0);
        //OnTrigger(); // to detect trigger stop
    }
OnTrigger()
protected void Bot::OnTrigger () inline private
Definition at line 82 of file bot.c.
    {
        bool triggered = m_BotTrigger.CheckTrigger();
        if (!m_Triggered)
        {
            if (triggered)
            {
                m_Timer.Stop(); // stop trigger timer
                m_Triggered = true;
                ProcessEvent(new BotEventStart(m_Owner));
                m_Timer.Run(c_UpdateMS / 1000.0, this, "OnUpdate", null, true);
                botDebugPrint("[bot] + " + m_Owner + " Started test!");
            }
        }
        else
        {
            if (!triggered)
            {
                m_Timer.Stop(); // stop update timer
                m_Triggered = false;
                ProcessEvent(new BotEventStop(m_Owner));
                m_Timer.Run(c_TriggerTimeoutMS / 1000.0, this, "OnTrigger", null, true);
                botDebugPrint("[bot] + " + m_Owner + " Stopped test!");
            }
        }
    }
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, BotTrigger::CheckTrigger(), m_BotTrigger, m_Owner, m_Timer, m_Triggered, and ProcessEvent().
Referenced by OnUpdate().
OnUpdate()
void Bot::OnUpdate (float dt) inline private
Definition at line 112 of file bot.c.
    {
        m_FSM.GetCurrentState().OnUpdate(dt);
        OnTrigger(); // to detect trigger stop
    }
References m_FSM, and OnTrigger().
ProcessEvent()
bool Bot::ProcessEvent (BotEventBase e) inline private
Definition at line 167 of file bot.c.
    {
        if (m_FSM.ProcessEvent(e) == ProcessEventResult.FSM_OK)
        {
            botDebugSpam("[botfsm] Processed event e=" + e.ToString());
            return true;
        }
        else
        {
            botDebugSpam("[botfsm] FSM refused to process event (no transition): src=" + m_FSM.GetCurrentState().ToString() + " event=" + e.ToString());
            return false;
        }
    }
References botDebugSpam(), and m_FSM.
Referenced by OnDelayedStart(), and OnTrigger().
SetInstanceType()
void Bot::SetInstanceType (DayZPlayerInstanceType t) inline private
Definition at line 37 of file bot.c.
{ m_InstanceType = t; }
References m_InstanceType.
Start()
void Bot::Start (bool use_trigger, BotTrigger trigger = null) inline private
Definition at line 39 of file bot.c.
    {
        m_UseTrigger = use_trigger;
        InitFSM();
        if (m_UseTrigger)
        {
            if (m_UseTrigger && trigger == null)
                Error("use trigger, but trigger null");
            m_Triggered = false;
            m_BotTrigger = trigger;
            botDebugPrint("[bot] + " + m_Owner + " Bot waiting for trigger...");
            m_Timer.Run(c_TriggerTimeoutMS / 1000.0, this, "OnTrigger", null, true);
        }
        else
        {
            botDebugPrint("[bot] + " + m_Owner + " Bot Started.");
            m_Timer.Run(c_UpdateMS / 1000.0, this, "OnTimer", null, true);
        }
    }
References botDebugPrint(), c_TriggerTimeoutMS, c_UpdateMS, Error(), InitFSM(), m_BotTrigger, m_Owner, m_Timer, m_Triggered, and m_UseTrigger.
Stop()
void Bot::Stop () inline private
Definition at line 75 of file bot.c.
    {
        m_Triggered = false;
        m_Timer.Stop();
        m_FSM.Terminate();
    }
References m_FSM, m_Timer, and m_Triggered.
Member Data Documentation
c_TriggerTimeoutMS
protected const float Bot::c_TriggerTimeoutMS = 1000.0 private
Definition at line 22 of file bot.c.
Referenced by OnTrigger(), and Start().
c_UpdateMS
protected const float Bot::c_UpdateMS = 16.0 private
Definition at line 24 of file bot.c.
Referenced by OnTrigger(), and Start().
m_BotTest
protected ref BotStateBase Bot::m_BotTest = null private
Definition at line 30 of file bot.c.
Referenced by InitFSM().
m_BotTrigger
protected ref BotTrigger Bot::m_BotTrigger = null private
Definition at line 29 of file bot.c.
Referenced by OnTrigger(), and Start().
m_FSM
protected ref BotFSM Bot::m_FSM = null private
Definition at line 25 of file bot.c.
Referenced by InitFSM(), OnUpdate(), ProcessEvent(), and Stop().
m_InstanceType
protected DayZPlayerInstanceType Bot::m_InstanceType = DayZPlayerInstanceType.INSTANCETYPE_CLIENT private
Definition at line 28 of file bot.c.
Referenced by SetInstanceType().
m_Owner
PlayerBase Bot::m_Owner = null private
Definition at line 20 of file bot.c.
Referenced by Bot(), BotStateIdle::BotStateIdle(), OnDelayedStart(), OnTrigger(), and Start().
m_Timer
protected ref Timer Bot::m_Timer = new Timer private
Definition at line 21 of file bot.c.
Referenced by DelayedStart(), OnTrigger(), Start(), and Stop().
m_Triggered
protected bool Bot::m_Triggered = false private
Definition at line 27 of file bot.c.
Referenced by OnTrigger(), Start(), and Stop().
m_UseTrigger
protected bool Bot::m_UseTrigger = false private
Definition at line 26 of file bot.c.
Referenced by OnDelayedStart(), and Start().