DayzKode: SoundLookupTable Class Reference
SoundLookupTable Class Reference
Private Member Functions
void AttachmentSoundLookupTable ()
SoundObjectBuilder GetSoundBuilder (int parameterHash)
void ImpactSoundLookupTable ()
void InitTable (string tableCategoryName, string parameterName)
void LoadTable (string soundLookupTableName)
void SoundLookupTable ()
Private Attributes
private string m_parameterName
private ref map< int, ref array< SoundObjectBuilder > > m_soundBuilders
private string m_tableCategoryName
Detailed Description
Definition at line 1 of file dayzanimeventmaps.c.
Constructor & Destructor Documentation
SoundLookupTable()
void SoundLookupTable::SoundLookupTable () inline private
Definition at line 3 of file dayzanimeventmaps.c.
    {
        m_soundBuilders = new map<int, ref array<SoundObjectBuilder>>();
    }
References m_soundBuilders.
Member Function Documentation
AttachmentSoundLookupTable()
void SoundLookupTable::AttachmentSoundLookupTable () inline private
Definition at line 88 of file dayzanimeventmaps.c.
    {
        InitTable("CfgAttachmentSoundTables", "category");
    }
References InitTable().
GetSoundBuilder()
SoundObjectBuilder SoundLookupTable::GetSoundBuilder (int parameterHash) inline private
Definition at line 52 of file dayzanimeventmaps.c.
    {
        array<SoundObjectBuilder> soundObjects = m_soundBuilders.Get(parameterHash);
        if(soundObjects == NULL || soundObjects.Count() == 0)
        {
            return NULL;
        }
        else if (soundObjects.Count() == 1)
        {
            return soundObjects.Get(0);
        }
        else
        {
            int index = Math.RandomInt(0, soundObjects.Count());
            return soundObjects.Get(index);
        }
    }
References m_soundBuilders, and Math::RandomInt().
Referenced by DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), GetSoundBuilder(), and EntityAI::PlayImpactSound().
ImpactSoundLookupTable()
void SoundLookupTable::ImpactSoundLookupTable () inline private
Definition at line 117 of file dayzanimeventmaps.c.
    {
        InitTable("CfgImpactSoundTables", "surface");
    }
References InitTable().
InitTable()
void SoundLookupTable::InitTable (string tableCategoryName, string parameterName) inline private
Definition at line 8 of file dayzanimeventmaps.c.
    {
        m_tableCategoryName = tableCategoryName;
        m_parameterName = parameterName;
    }
References m_parameterName, and m_tableCategoryName.
Referenced by AttachmentSoundLookupTable(), ImpactSoundLookupTable(), PlayerVoiceLookupTable(), and SoundLookupTable().
LoadTable()
void SoundLookupTable::LoadTable (string soundLookupTableName) inline private
Definition at line 14 of file dayzanimeventmaps.c.
    {
        string path = "CfgSoundTables " + m_tableCategoryName + " " + soundLookupTableName;
        //load all classes names
        int soundCount = GetGame().ConfigGetChildrenCount(path);
        for(int i = 0; i < soundCount; i++)
        {
            string soundClassName;
            GetGame().ConfigGetChildName(path, i, soundClassName);
            string soundClassPath = path + " " + soundClassName + " ";
            string parameter;
            GetGame().ConfigGetText(soundClassPath + m_parameterName, parameter);
            array<string> soundSetNames = new array<string>;
            GetGame().ConfigGetTextArray(soundClassPath + "soundSets", soundSetNames);
            //TODO create SoundObject for every entry, save in Game?
            array<SoundObjectBuilder> soundObjectBuilders = new array<SoundObjectBuilder>;
            for(int j = 0; j < soundSetNames.Count(); j++)
            {
                AnimSoundObjectBuilderBank bank = AnimSoundObjectBuilderBank.GetInstance();
                SoundObjectBuilder soundObjectBuilder = bank.GetBuilder(soundSetNames.Get(j));
                if(soundObjectBuilder != NULL)
                    soundObjectBuilders.Insert(soundObjectBuilder);
            }
            if(soundObjectBuilders.Count() > 0)
            {
                //Print("SoundLookupTable::LoadTable: path: " + path + " param:" + parameter + " param#:" + parameter.Hash() + " objBuildersCount: " + soundObjectBuilders.Count());
                m_soundBuilders.Insert(parameter.Hash(), soundObjectBuilders);
            }
        }
    }
References AnimSoundObjectBuilderBank(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), GetGame(), string::Hash(), m_parameterName, m_soundBuilders, m_tableCategoryName, and path.
Referenced by AnimSoundLookupTableBank::GetImpactTable(), and AnimSoundLookupTableBank::GetStepTable().
Member Data Documentation
m_parameterName
private string SoundLookupTable::m_parameterName private
Definition at line 73 of file dayzanimeventmaps.c.
Referenced by InitTable(), and LoadTable().
m_soundBuilders
private ref map<int, ref array<SoundObjectBuilder> > SoundLookupTable::m_soundBuilders private
Definition at line 74 of file dayzanimeventmaps.c.
Referenced by GetSoundBuilder(), LoadTable(), and SoundLookupTable().
m_tableCategoryName
private string SoundLookupTable::m_tableCategoryName private
Definition at line 72 of file dayzanimeventmaps.c.
Referenced by InitTable(), and LoadTable().