DayzKode: UndergroundAreaLoader Class Reference
UndergroundAreaLoader Class Reference
Static Private Member Functions
static JsonUndergroundTriggers GetData ()
static void OnRPC (ParamsReadContext ctx)
static void SpawnAllTriggerCarriers ()
static void SpawnTriggerCarrier (int index, JsonUndergroundAreaTriggerData data)
static void SyncDataSend (PlayerIdentity identity)
Static Private Attributes
static ref JsonUndergroundTriggers m_JsonData
static private string m_Path = "$mission:cfgundergroundtriggers.json"
Detailed Description
Definition at line 47 of file undergroundarealoader.c.
Member Function Documentation
GetData()
static JsonUndergroundTriggers UndergroundAreaLoader::GetData () inline static private
Definition at line 54 of file undergroundarealoader.c.
    {
        if ( !FileExist( m_Path ) )
        {
            // We fallback to check in data and notify user file was not found in mission
            PrintToRPT("[WARNING] :: [UndergroundAreaLoader GetData()] :: file not found in MISSION folder, your path is " + m_Path + " Attempting DATA folder");
            string worldName;
            GetGame().GetWorldName( worldName );
            m_Path = string.Format("DZ/worlds/%1/ce/cfgundergroundtriggers.json", worldName );
            if ( !FileExist( m_Path ) )
            {
                PrintToRPT("[WARNING] :: [UndergroundAreaLoader GetData()] ::file not found in DATA folder, your path is " + m_Path);
                return null; // Nothing could be read, just end here
            }
        }
        JsonUndergroundTriggers data;
        JsonFileLoader<JsonUndergroundTriggers>.JsonLoadFile( m_Path, data );
        return data;
    }
References FileExist(), string::Format(), GetGame(), CGame::GetWorldName(), m_Path, and PrintToRPT().
Referenced by SpawnAllTriggerCarriers().
OnRPC()
static void UndergroundAreaLoader::OnRPC (ParamsReadContext ctx) inline static private
Definition at line 117 of file undergroundarealoader.c.
    {
        Param1<JsonUndergroundTriggers> data = new Param1< JsonUndergroundTriggers>(null);
        if ( ctx.Read(data) )
        {
            m_JsonData = data.param1;
        }
        else
        {
            ErrorEx("UndergroundAreaLoader datasynced - failed to read");
        }
    }
References ErrorEx, m_JsonData, and Serializer::Read().
Referenced by OnRPC().
SpawnAllTriggerCarriers()
static void UndergroundAreaLoader::SpawnAllTriggerCarriers () inline static private
Definition at line 79 of file undergroundarealoader.c.
    {
        if (!m_JsonData)
        {
            m_JsonData = GetData();
        }
        if (!m_JsonData || !m_JsonData.Triggers)
        {
            return;
        }
        foreach (int i, auto data:m_JsonData.Triggers)
        {
            SpawnTriggerCarrier(i, data);
        }
    }
References GetData(), m_JsonData, SpawnTriggerCarrier(), and JsonUndergroundTriggers::Triggers.
Referenced by MissionBase::OnInit().
SpawnTriggerCarrier()
static void UndergroundAreaLoader::SpawnTriggerCarrier (int index, JsonUndergroundAreaTriggerData data) inline static private
Definition at line 97 of file undergroundarealoader.c.
    {
        UndergroundTriggerCarrierBase carrier = UndergroundTriggerCarrierBase.Cast(GetGame().CreateObjectEx( "UndergroundTriggerCarrier", data.GetPosition(), ECE_NONE ));
        //Print("spawning trigger carrier at pos :" +data.GetPosition());
        if (carrier)
        {
            carrier.SetIndex(index);
            carrier.SetOrientation(data.GetOrientation());
        }
    }
References ECE_NONE, GetGame(), JsonUndergroundAreaTriggerData::GetOrientation(), and JsonUndergroundAreaTriggerData::GetPosition().
Referenced by SpawnAllTriggerCarriers().
SyncDataSend()
static void UndergroundAreaLoader::SyncDataSend (PlayerIdentity identity) inline static private
Definition at line 110 of file undergroundarealoader.c.
    {
        GetGame().RPCSingleParam(null, ERPCs.RPC_UNDERGROUND_SYNC, new Param1<JsonUndergroundTriggers>(m_JsonData), true, identity);
    }
References GetGame(), m_JsonData, and CGame::RPCSingleParam().
Referenced by MissionBase::OnEvent().
Member Data Documentation
m_JsonData
ref JsonUndergroundTriggers UndergroundAreaLoader::m_JsonData static private
Definition at line 51 of file undergroundarealoader.c.
Referenced by UndergroundTriggerCarrierBase::CanSpawnTrigger(), OnRPC(), SpawnAllTriggerCarriers(), UndergroundTriggerCarrierBase::SpawnTrigger(), and SyncDataSend().
m_Path
private string UndergroundAreaLoader::m_Path = "$mission:cfgundergroundtriggers.json" static private
Definition at line 49 of file undergroundarealoader.c.
Referenced by GetData().