DayzKode: OnlineServices Class Reference
OnlineServices Class Reference
Static Private Member Functions
static void AutoConnectToEmptyServer ()
static bool CheckUpdate ()
static void ClearCurrentServerInfo ()
static void ClearPendingInviteList (array< string > invitees)
static void EnterGameplaySession ()
static bool ErrorCaught (EBiosError error)
static BiosUser GetBiosUser ()
static void GetCachedFavServerInfo (array< ref CachedServerInfo > favServersInfoCache)
static void GetClientServices ()
static GetServersResultRow GetCurrentServerInfo ()
static void GetCurrentServerInfo (string ip, int port)
static void GetFavoriteServers (TStringArray favServers)
static void GetInviteServerInfo (out string ip, out int port)
static bool GetMultiplayState ()
static map< string, bool > GetMuteList ()
static array< string > GetPendingInviteList ()
static GetServersResultRow GetRandomFreeResult (GetFirstServerWithEmptySlotResult results)
static void GetServerModList (string server_id)
static void GetSession ()
static string GetSessionHandle ()
static void Init ()
static bool IsGameActive (bool sim)
static bool IsGameTrial (bool sim)
static bool IsInitialized ()
static bool IsPlayerMuted (string id)
static void LeaveGameplaySession ()
static void LoadFriends ()
static void LoadMPPrivilege ()
static void LoadPermissions (array< string > player_list)
static void LoadServers (notnull GetServersInput inputValues)
static void LoadVoicePrivilege ()
static bool MutePlayer (string id, bool mute)
static void OnAutoConnectToEmptyServer (GetFirstServerWithEmptySlotResult result_list, EBiosError error)
static void OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error)
static void OnGetServerModList (GetServerModListResult result_list, EBiosError error)
static void OnLoadMPPrivilege (EBiosError err)
static void OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response)
static void OnLoadVoicePrivilege (EBiosError err)
static void OnPermissionsAsync (BiosPrivacyUidResultArray result_list, EBiosError error)
static void OnUserProfileAsync (EBiosError error)
static void PromptUpdate ()
static void SetBiosUser (BiosUser user)
static void SetGameplayActivity ()
static void SetInviteServerInfo (string ip, int port)
static void SetMultiplayState (bool state)
static void SetPendingInviteList (array< string > invitees)
static void SetServerFavorited (string ipAddress, int port, int steamQueryPort, bool is_favorited)
static void SetSessionHandle (string handle)
static void ShowInviteScreen ()
static void ShowUserProfile (string uid)
Static Private Attributes
static int m_AutoConnectTries = 0
static protected ref BiosUser m_BiosUser
static ref BiosClientServices m_ClientServices
static protected ref GetServersResultRow m_CurrentServerInfo
static protected string m_CurrentServerIP
static protected int m_CurrentServerPort
static protected bool m_FirstFriendsLoad = true
static ref ScriptInvoker m_FriendsAsyncInvoker = new ScriptInvoker()
static protected ref map< string, ref BiosFriendInfo > m_FriendsList
static protected string m_InviteServerIP
static protected int m_InviteServerPort
static protected bool m_MultiplayState = false
static protected ref map< string, bool > m_MuteList
static ref ScriptInvoker m_MuteUpdateAsyncInvoker = new ScriptInvoker()
static protected ref array< string > m_PendingInvites
static ref ScriptInvoker m_PermissionsAsyncInvoker = new ScriptInvoker()
static protected ref map< string, ref BiosPrivacyPermissionResultArray > m_PermissionsList
static ref ScriptInvoker m_ServerAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_ServerModLoadAsyncInvoker = new ScriptInvoker()
static ref ScriptInvoker m_ServersAsyncInvoker = new ScriptInvoker()
static ref TrialService m_TrialService
Detailed Description
Definition at line 1 of file onlineservices.c.
Member Function Documentation
AutoConnectToEmptyServer()
static void OnlineServices::AutoConnectToEmptyServer () inline static private
Definition at line 639 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices && m_AutoConnectTries == 0 )
        {
            m_AutoConnectTries = 1;
            GetFirstServerWithEmptySlotInput input = new GetFirstServerWithEmptySlotInput;
            input.SetOfficial( true );
            m_ClientServices.GetLobbyService().GetFirstServerWithEmptySlot( input );
        }
    }
References GetClientServices(), BiosLobbyService::GetFirstServerWithEmptySlot(), BiosClientServices::GetLobbyService(), m_AutoConnectTries, m_ClientServices, and GetFirstServerWithEmptySlotInput::SetOfficial().
Referenced by UIScriptedMenu::AutoConnect().
CheckUpdate()
static bool OnlineServices::CheckUpdate () inline static private
Definition at line 739 of file onlineservices.c.
    {
        GetClientServices();
        if ( m_ClientServices )
        {
            EBiosError error = m_ClientServices.GetPackageService().CheckUpdateAsync();
            if ( !error )
            {
                return true;
            }
        }
        return false;
    }
References BiosPackageService::CheckUpdateAsync(), GetClientServices(), BiosClientServices::GetPackageService(), and m_ClientServices.
Referenced by DayZIntroSceneXbox::CheckXboxClientUpdate().
ClearCurrentServerInfo()
static void OnlineServices::ClearCurrentServerInfo () inline static private
Definition at line 175 of file onlineservices.c.
    {
        m_CurrentServerInfo = null;
        m_CurrentServerIP   = "";
        m_CurrentServerPort = 0;
    }
References m_CurrentServerInfo, m_CurrentServerIP, and m_CurrentServerPort.
Referenced by OnEvent().
ClearPendingInviteList()
static void OnlineServices::ClearPendingInviteList (array< string > invitees) inline static private
Definition at line 633 of file onlineservices.c.
    {
        delete m_PendingInvites;
    }
References m_PendingInvites.
EnterGameplaySession()
static void OnlineServices::EnterGameplaySession () inline static private
Definition at line 546 of file onlineservices.c.
    {
        string addr;
        int port;
        if( GetGame().GetHostAddress( addr, port ) )
        {
            GetClientServices();
            if( m_ClientServices )
            {
                m_ClientServices.GetSessionService().EnterGameplaySessionAsync( addr, port );
                SetMultiplayState(true);
            }
        }
    }
References BiosSessionService::EnterGameplaySessionAsync(), GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), m_ClientServices, and SetMultiplayState().
Referenced by OnEvent().
ErrorCaught()
static bool OnlineServices::ErrorCaught (EBiosError error) inline static private
Definition at line 82 of file onlineservices.c.
    {
        switch ( error )
        {
            case EBiosError.OK:
            {
                return false;
            }
        }
        DebugPrint.LogErrorAndTrace( string.Format("BiosClientServices Error: %1", ErrorModuleHandler.GetClientMessage(ErrorCategory.BIOSError, error)) );
        return true;
    }
References ErrorModuleHandler::GetClientMessage(), and DebugPrint::LogErrorAndTrace().
Referenced by LoadMPPrivilege(), LoadPermissions(), LoadVoicePrivilege(), OnAutoConnectToEmptyServer(), BiosSessionService::OnEnterGameplaySession(), OnFriendsAsync(), OnGetServerModList(), BiosSessionService::OnGetSessionError(), BiosUserManager::OnJoin(), OnLoadMPPrivilege(), OnLoadServersAsync(), OnLoadVoicePrivilege(), OnPermissionsAsync(), BiosPackageService::OnPromptUpdate(), BiosSessionService::OnSetActivity(), BiosSessionService::OnShowInviteToGameplaySession(), BiosPackageService::OnShowStore(), BiosUserManager::OnUserDatabaseId(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), OnUserProfileAsync(), and ShowInviteScreen().
GetBiosUser()
static BiosUser OnlineServices::GetBiosUser () inline static private
Definition at line 519 of file onlineservices.c.
    {
        return m_BiosUser;
    }
References m_BiosUser.
Referenced by DisconnectSessionScript(), BiosSessionService::OnGetSessionError(), and BiosSessionService::TryGetSession().
GetCachedFavServerInfo()
static void OnlineServices::GetCachedFavServerInfo (array< ref CachedServerInfo > favServersInfoCache) inline static private
Definition at line 114 of file onlineservices.c.
    {
        m_ClientServices.GetLobbyService().GetCachedFavoriteServerInfo(favServersInfoCache);
    }
References BiosLobbyService::GetCachedFavoriteServerInfo(), BiosClientServices::GetLobbyService(), and m_ClientServices.
Referenced by ServerBrowserTabPc::RefreshList().
GetClientServices()
static void OnlineServices::GetClientServices () inline static private
Definition at line 57 of file onlineservices.c.
    {
        BiosUserManager user_manager = GetGame().GetUserManager();
        if ( user_manager )
        {
            BiosUser selected_user = user_manager.GetSelectedUser();
            if ( selected_user )
            {
                m_ClientServices = selected_user.GetClientServices();
            }
            #ifdef PLATFORM_WINDOWS
                array<ref BiosUser> user_list = new array<ref BiosUser>;
                user_manager.GetUserList( user_list );
                if ( user_list.Count() > 0 )
                {
                    m_ClientServices = user_list.Get( 0 ).GetClientServices();
                }
            #endif
        }
        else
        {
            Error( "BiosClientServices Error: Usermanager does not exist." );
        }
    }
References Error(), BiosUser::GetClientServices(), GetGame(), BiosUserManager::GetSelectedUser(), BiosUserManager::GetUserList(), CGame::GetUserManager(), and m_ClientServices.
Referenced by AutoConnectToEmptyServer(), CheckUpdate(), EnterGameplaySession(), GetCurrentServerInfo(), GetServerModList(), GetSession(), GetSessionHandle(), Init(), LeaveGameplaySession(), LoadFriends(), LoadMPPrivilege(), LoadPermissions(), LoadServers(), LoadVoicePrivilege(), PromptUpdate(), SetGameplayActivity(), SetPendingInviteList(), SetServerFavorited(), SetSessionHandle(), ShowInviteScreen(), and ShowUserProfile().
GetCurrentServerInfo() [1/2]
static GetServersResultRow OnlineServices::GetCurrentServerInfo () inline static private
Definition at line 167 of file onlineservices.c.
    {
        if (m_CurrentServerInfo)
            return m_CurrentServerInfo;
        else
            return g_Game.GetHostData();
    }
References g_Game, and m_CurrentServerInfo.
GetCurrentServerInfo() [2/2]
static void OnlineServices::GetCurrentServerInfo (string ip, int port) inline static private
Definition at line 139 of file onlineservices.c.
    {
        GetClientServices();
        m_CurrentServerIP = ip;
        m_CurrentServerPort = port;
        GetServersInput inputValues = new GetServersInput;
        inputValues.SetHostIp( ip );
        inputValues.SetHostPort( port );
        inputValues.m_Page = 0;
        inputValues.m_RowsPerPage = 10;
        inputValues.m_Platform = 1;
        #ifdef PLATFORM_XBOX
            inputValues.m_Platform = 2;
        #endif
        #ifdef PLATFORM_PS4
            inputValues.m_Platform = 3;
        #endif
        if ( m_ClientServices )
        {
            m_ClientServices.GetLobbyService().GetServers( inputValues );
        }
    }
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServers(), m_ClientServices, m_CurrentServerIP, m_CurrentServerPort, GetServersInput::m_Page, GetServersInput::m_Platform, GetServersInput::m_RowsPerPage, GetServersInput::SetHostIp(), and GetServersInput::SetHostPort().
Referenced by RefreshCurrentServerInfo(), UIScriptedMenu::SetServerInfo(), and UIScriptedMenu::ToggleFavoriteServer().
GetFavoriteServers()
static void OnlineServices::GetFavoriteServers (TStringArray favServers) inline static private
Definition at line 109 of file onlineservices.c.
    {
        m_ClientServices.GetLobbyService().GetFavoriteServers(favServers);
    }
References BiosLobbyService::GetFavoriteServers(), BiosClientServices::GetLobbyService(), and m_ClientServices.
Referenced by UIScriptedMenu::LoadFavoriteServers().
GetInviteServerInfo()
static void OnlineServices::GetInviteServerInfo (out string ip, out int port) inline static private
Definition at line 188 of file onlineservices.c.
    {
        ip = m_InviteServerIP;
        port = m_InviteServerPort;
    }
References m_InviteServerIP, and m_InviteServerPort.
Referenced by UIScriptedMenu::Update().
GetMultiplayState()
static bool OnlineServices::GetMultiplayState () inline static private
Definition at line 530 of file onlineservices.c.
    {
        return m_MultiplayState;
    }
References m_MultiplayState.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
GetMuteList()
static map< string, bool > OnlineServices::GetMuteList () inline static private
Definition at line 405 of file onlineservices.c.
    {
        return m_MuteList;
    }
References m_MuteList.
Referenced by UIScriptedMenu::Init().
GetPendingInviteList()
static array< string > OnlineServices::GetPendingInviteList () inline static private
Definition at line 612 of file onlineservices.c.
    {
        array<string> already_on_server = ClientData.GetSimplePlayerList();
        if( already_on_server && m_PendingInvites )
        {
            array<string> new_to_server = new array<string>;
            foreach( string invitee : m_PendingInvites )
            {
                if( already_on_server.Find( invitee ) == -1 )
                {
                    new_to_server.Insert( invitee );
                }
            }
            return new_to_server;
        }
        else
        {
            return m_PendingInvites;
        }
    }
References ClientData::GetSimplePlayerList(), and m_PendingInvites.
Referenced by BiosSessionService::OnEnterGameplaySession(), and SetPendingInviteList().
GetRandomFreeResult()
static GetServersResultRow OnlineServices::GetRandomFreeResult (GetFirstServerWithEmptySlotResult results) inline static private
Definition at line 651 of file onlineservices.c.
    {
        GetServersResultRow result;
        array<ref GetServersResultRow> results_free = new array<ref GetServersResultRow>;
        if( results && results.m_Result && results.m_Result.m_Results && results.m_Result.m_Results.Count() > 0 )
        {
            foreach( GetServersResultRow result_temp : results.m_Result.m_Results )
            {
                if( result_temp.m_FreeSlots > 0 )
                {
                    results_free.Insert( result_temp );
                }
            }
        }
        return results_free.GetRandomElement();
    }
References GetFirstServerWithEmptySlotResult::m_Result, and GetServersResult::m_Results.
Referenced by OnAutoConnectToEmptyServer().
GetServerModList()
static void OnlineServices::GetServerModList (string server_id) inline static private
Definition at line 700 of file onlineservices.c.
    {
        GetClientServices();
        if ( m_ClientServices )
        {
            m_ClientServices.GetLobbyService().GetServerModList( server_id );
        }
    }
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServerModList(), and m_ClientServices.
Referenced by ScriptedWidgetEventHandler::SetExpand().
GetSession()
static void OnlineServices::GetSession () inline static private
Definition at line 510 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            m_ClientServices.GetSessionService().TryGetSession( GetSessionHandle() );
        }
    }
References GetClientServices(), GetSessionHandle(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::TryGetSession().
Referenced by BiosUserManager::OnJoin(), and TryConnect().
GetSessionHandle()
static string OnlineServices::GetSessionHandle () inline static private
Definition at line 500 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            return m_ClientServices.GetSessionService().m_CurrentHandle;
        }
        return "";
    }
References GetClientServices(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::m_CurrentHandle.
Referenced by GetSession().
Init()
static void OnlineServices::Init () inline static private
Definition at line 30 of file onlineservices.c.
    {
        #ifdef PLATFORM_CONSOLE
            #ifndef PLATFORM_WINDOWS // if app is not on Windows with -XBOX parameter
            if ( !m_TrialService )
                m_TrialService = new TrialService;
            if ( !m_FriendsList )
                m_FriendsList = new map<string, ref BiosFriendInfo>;
            if ( !m_MuteList )
                m_MuteList = new map<string, bool>;
            if ( !m_PermissionsList )
                m_PermissionsList = new map<string, ref BiosPrivacyPermissionResultArray>;
            m_FriendsList.Clear();
            m_PermissionsList.Clear();
            m_MuteList.Clear();
            #endif
        #endif
        GetClientServices();
    }
References GetClientServices(), m_FriendsList, m_MuteList, m_PermissionsList, and m_TrialService.
Referenced by UIScriptedMenu::Init(), and SelectUser().
IsGameActive()
static bool OnlineServices::IsGameActive (bool sim) inline static private
Definition at line 728 of file onlineservices.c.
    {
        #ifdef PLATFORM_XBOX
        #ifndef PLATFORM_WINDOWS
        if( m_TrialService )
            return m_TrialService.IsGameActive( sim );
        #endif
        #endif
        return false;
    }
References TrialService::IsGameActive(), and m_TrialService.
Referenced by CGame::IsDigitalCopy().
IsGameTrial()
static bool OnlineServices::IsGameTrial (bool sim) inline static private
Definition at line 717 of file onlineservices.c.
    {
        #ifdef PLATFORM_XBOX
        #ifndef PLATFORM_WINDOWS
        if( m_TrialService )
            return m_TrialService.IsGameTrial( sim );
        #endif
        #endif
        return false;
    }
References TrialService::IsGameTrial(), and m_TrialService.
IsInitialized()
static bool OnlineServices::IsInitialized () inline static private
Definition at line 52 of file onlineservices.c.
    {
        return ( m_ClientServices != null );
    }
References m_ClientServices.
IsPlayerMuted()
static bool OnlineServices::IsPlayerMuted (string id) inline static private
Definition at line 366 of file onlineservices.c.
    {
        if( m_MuteList.Contains( id ) )
        {
            return m_MuteList.Get( id );
        }
        else
        {
            BiosPrivacyPermissionResultArray perms = m_PermissionsList.Get( id );
            if( perms )
            {
                for( int i = 0; i < perms.Count(); i++ )
                {
                    BiosPrivacyPermissionResult result = perms.Get( i );
                    if( result.m_Permission == EBiosPrivacyPermission.COMMUNICATE_VOICE )
                    {
                        m_MuteList.Insert( id, !result.m_IsAllowed );
                        return !result.m_IsAllowed;
                    }
                }
            }
        }
        return false;
    }
References BiosPrivacyPermissionResult::m_IsAllowed, m_MuteList, BiosPrivacyPermissionResult::m_Permission, and m_PermissionsList.
Referenced by UIScriptedMenu::Init(), OnPermissionsAsync(), and ScriptedWidgetEventHandler::ReloadLocal().
LeaveGameplaySession()
static void OnlineServices::LeaveGameplaySession () inline static private
Definition at line 561 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            if( m_CurrentServerInfo )
                m_ClientServices.GetSessionService().LeaveGameplaySessionAsync(m_CurrentServerInfo.m_HostIp, m_CurrentServerInfo.m_HostPort);
            else if( m_CurrentServerIP != "" )
                m_ClientServices.GetSessionService().LeaveGameplaySessionAsync(m_CurrentServerIP, m_CurrentServerPort);
            SetMultiplayState(false);
            m_FirstFriendsLoad = true;
            if( m_FriendsList )
                m_FriendsList.Clear();
        }
    }
References GetClientServices(), BiosClientServices::GetSessionService(), BiosSessionService::LeaveGameplaySessionAsync(), m_ClientServices, m_CurrentServerInfo, m_CurrentServerIP, m_CurrentServerPort, m_FirstFriendsLoad, m_FriendsList, and SetMultiplayState().
Referenced by OnEvent().
LoadFriends()
static void OnlineServices::LoadFriends () inline static private
Definition at line 234 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            m_ClientServices.GetSocialService().GetFriendsAsync();
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References GetClientServices(), BiosSocialService::GetFriendsAsync(), BiosClientServices::GetSocialService(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
LoadMPPrivilege()
static void OnlineServices::LoadMPPrivilege () inline static private
Definition at line 430 of file onlineservices.c.
    {
        #ifdef PLATFORM_CONSOLE
            GetClientServices();
            if( m_ClientServices )
            {
                ErrorCaught( m_ClientServices.GetPrivacyService().GetPrivilegeAsync( EBiosPrivacyPrivilege.MULTIPLAYER_GAMEPLAY, true ) );
            }
            else
            {
                DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
            }
        #else
            OnLoadMPPrivilege( EBiosError.OK );
        #endif
    }
References ErrorCaught(), GetClientServices(), BiosClientServices::GetPrivacyService(), BiosPrivacyService::GetPrivilegeAsync(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and OnLoadMPPrivilege().
Referenced by ConnectFromServerBrowser(), ConnectErrorScriptModuleUI::OnModalResult(), and SelectGamepad().
LoadPermissions()
static void OnlineServices::LoadPermissions (array< string > player_list) inline static private
Definition at line 311 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            array<EBiosPrivacyPermission> perms = new array<EBiosPrivacyPermission>;
            perms.Insert( EBiosPrivacyPermission.COMMUNICATE_VOICE );
            ErrorCaught( m_ClientServices.GetPrivacyService().GetPermissionsAsync( player_list, perms ) );
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References ErrorCaught(), GetClientServices(), BiosPrivacyService::GetPermissionsAsync(), BiosClientServices::GetPrivacyService(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by ClientData::SyncEvent_OnRecievedPlayerList().
LoadServers()
static void OnlineServices::LoadServers (notnull GetServersInput inputValues) inline static private
Definition at line 96 of file onlineservices.c.
    {
        GetClientServices();
        if ( m_ClientServices )
        {
            m_ClientServices.GetLobbyService().GetServers( inputValues );
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References GetClientServices(), BiosClientServices::GetLobbyService(), BiosLobbyService::GetServers(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by GetNextPage(), ServerBrowserTabConsolePages::RefreshList(), ServerBrowserTabPc::RefreshList(), and RefreshList().
LoadVoicePrivilege()
static void OnlineServices::LoadVoicePrivilege () inline static private
Definition at line 447 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            ErrorCaught( m_ClientServices.GetPrivacyService().GetPrivilegeAsync( EBiosPrivacyPrivilege.COMMUNICATE_VOICE, true ) );
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References ErrorCaught(), GetClientServices(), BiosClientServices::GetPrivacyService(), BiosPrivacyService::GetPrivilegeAsync(), DebugPrint::LogErrorAndTrace(), and m_ClientServices.
Referenced by OnEvent().
MutePlayer()
static bool OnlineServices::MutePlayer (string id, bool mute) inline static private
Definition at line 391 of file onlineservices.c.
    {
        if( m_MuteList.Contains( id ) )
        {
            m_MuteList.Set( id, mute );
        }
        else
        {
            m_MuteList.Insert( id, mute );
        }
        return true;
    }
References m_MuteList.
Referenced by ScriptedWidgetEventHandler::ToggleMute().
OnAutoConnectToEmptyServer()
static void OnlineServices::OnAutoConnectToEmptyServer (GetFirstServerWithEmptySlotResult result_list, EBiosError error) inline static private
Definition at line 670 of file onlineservices.c.
    {
        if ( !ErrorCaught( error ) )
        {
            GetServersResultRow result = GetRandomFreeResult( result_list );
            if ( result )
            {
                g_Game.ConnectFromServerBrowser( result.m_HostIp, result.m_HostPort );
                m_AutoConnectTries = 0;
                return;
            }
            else
            {
                GetGame().GetUIManager().ShowDialog( "#str_xbox_authentification_fail_title", "#str_xbox_authentification_fail", 232, DBT_OK, DBB_NONE, DMT_INFO, GetGame().GetUIManager().GetMenu() );
            }
        }
        if ( m_AutoConnectTries < 3 )
        {
            m_AutoConnectTries++;
            GetFirstServerWithEmptySlotInput input = new GetFirstServerWithEmptySlotInput;
            input.SetOfficial( true );
            m_ClientServices.GetLobbyService().GetFirstServerWithEmptySlot( input );
        }
        else
        {
            GetGame().GetUIManager().ShowDialog( "#str_xbox_authentification_fail_title", "#xbox_authentification_fail", 232, DBT_OK, DBB_NONE, DMT_INFO, GetGame().GetUIManager().GetMenu() );
        }
    }
References ErrorCaught(), g_Game, BiosLobbyService::GetFirstServerWithEmptySlot(), GetGame(), BiosClientServices::GetLobbyService(), GetRandomFreeResult(), CGame::GetUIManager(), m_AutoConnectTries, m_ClientServices, GetFirstServerWithEmptySlotInput::SetOfficial(), and UIManager::ShowDialog().
Referenced by BiosLobbyService::OnGetFirstServerWithEmptySlot().
OnFriendsAsync()
static void OnlineServices::OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error) inline static private
Definition at line 265 of file onlineservices.c.
    {
        if ( !ErrorCaught( error ) )
        {
            m_FriendsAsyncInvoker.Invoke( friend_list );
            array<string> friends_simple = new array<string>;
            for ( int i = 0; i < friend_list.Count(); ++i )
            {
                string uid = friend_list[i].m_Uid;
                BiosFriendInfo storedBfi = m_FriendsList[uid];
                BiosFriendInfo newBfi = friend_list[i];
                if (storedBfi)
                {
                    if ( !BiosFriendInfo.Compare( storedBfi, newBfi ) )
                    {
                        friends_simple.Insert( newBfi.m_Uid );
                    }
                    m_FriendsList.Set( uid, newBfi );
                }
                else
                {
                    m_FriendsList.Insert( uid, newBfi );
                    friends_simple.Insert( newBfi.m_Uid );
                }
            }
            if ( !m_FirstFriendsLoad )
            {
                if ( ClientData.m_LastNewPlayers && ClientData.m_LastNewPlayers.m_PlayerList.Count() > 0 )
                {
                    foreach ( SyncPlayer player : ClientData.m_LastNewPlayers.m_PlayerList )
                    {
                        if ( m_FriendsList.Contains( player.m_UID ) )
{
                            NotificationSystem.AddNotification( NotificationType.FRIEND_CONNECTED, 6, player.m_PlayerName + " " + "#ps4_invite_has_joined_your_session" );
                        }
                    }
                    ClientData.m_LastNewPlayers.m_PlayerList.Clear();
                }
            }
            m_FirstFriendsLoad = false;
        }
    }
References NotificationSystem::AddNotification(), BiosFriendInfo::Compare(), ErrorCaught(), ScriptInvoker::Invoke(), m_FirstFriendsLoad, m_FriendsAsyncInvoker, m_FriendsList, ClientData::m_LastNewPlayers, SyncPlayerList::m_PlayerList, SyncPlayer::m_PlayerName, SyncPlayer::m_UID, and BiosFriendInfo::m_Uid.
Referenced by BiosSocialService::OnFriendsAsync().
OnGetServerModList()
static void OnlineServices::OnGetServerModList (GetServerModListResult result_list, EBiosError error) inline static private
Definition at line 709 of file onlineservices.c.
    {
        if ( !ErrorCaught( error ) )
        {
            m_ServerModLoadAsyncInvoker.Invoke( result_list );
        }
    }
References ErrorCaught(), ScriptInvoker::Invoke(), and m_ServerModLoadAsyncInvoker.
Referenced by BiosLobbyService::OnServerModList().
OnLoadMPPrivilege()
static void OnlineServices::OnLoadMPPrivilege (EBiosError err) inline static private
Definition at line 460 of file onlineservices.c.
    {
        if( !ErrorCaught( err ) )
        {
            g_Game.TryConnect();
        }
        else
        {
            if( g_Game.GetGameState() != DayZGameState.MAIN_MENU )
            {
                g_Game.MainMenuLaunch();
            }
            else
            {
                g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
                g_Game.GamepadCheck();
            }
        }
    }
References ErrorCaught(), and g_Game.
Referenced by LoadMPPrivilege(), and BiosPrivacyService::OnPrivilege().
OnLoadServersAsync()
static void OnlineServices::OnLoadServersAsync (GetServersResult result_list, EBiosError error, string response) inline static private
Definition at line 194 of file onlineservices.c.
    {
        if ( !ErrorCaught( error ) )
        {
            if ( m_CurrentServerIP != "" && m_CurrentServerPort > 0 )
            {
                foreach ( GetServersResultRow result : result_list.m_Results )
                {
                    if ( result.m_HostIp == m_CurrentServerIP && result.m_HostPort == m_CurrentServerPort )
                    {
                        m_CurrentServerInfo = result;
                        m_CurrentServerIP   = "";
                        m_CurrentServerPort = 0;
                    }
                }
            }
            // todo: remove
            //foreach( GetServersResultRow res : result_list.m_Results )
            //{
            //  Print("OnLoadServersAsync: result id: " + res.m_Id + "modded: " + res.m_Modded);
            //}
            // just for example execute the retrieving of extended info for the first server entry in the list
            //if (result_list.m_Results.Count() > 0)
            //{
                //GetServersResultRow re = result_list.m_Results[0];
                //EBiosError er = m_ClientServices.GetLobbyService().GetServerModList(re.m_Id);
                //Print("OnLoadServersAsync GetServerModList returns:" + er);
            //}
            m_ServersAsyncInvoker.Invoke( result_list, error, response );
        }
        else
        {
            m_ServersAsyncInvoker.Invoke( null, error, "" );
        }
    }
References ErrorCaught(), ScriptInvoker::Invoke(), m_CurrentServerInfo, m_CurrentServerIP, m_CurrentServerPort, GetServersResult::m_Results, and m_ServersAsyncInvoker.
Referenced by BiosLobbyService::OnDoneAsync().
OnLoadVoicePrivilege()
static void OnlineServices::OnLoadVoicePrivilege (EBiosError err) inline static private
Definition at line 480 of file onlineservices.c.
    {
        if( g_Game.GetGameState() == DayZGameState.IN_GAME )
        {
            #ifdef PLATFORM_PS4
            GetGame().GetWorld().DisableReceiveVoN( ErrorCaught( err ) );
            #endif
            GetGame().GetWorld().DisableTransmitVoN( ErrorCaught( err ) );
        }
    }
References World::DisableReceiveVoN(), World::DisableTransmitVoN(), ErrorCaught(), g_Game, GetGame(), and CGame::GetWorld().
Referenced by BiosPrivacyService::OnPrivilege().
OnPermissionsAsync()
static void OnlineServices::OnPermissionsAsync (BiosPrivacyUidResultArray result_list, EBiosError error) inline static private
Definition at line 327 of file onlineservices.c.
    {
        if ( !ErrorCaught( error ) )
        {
            BiosPrivacyUidResultArray new_list = new BiosPrivacyUidResultArray;
            map<string, bool> mute_list = new map<string, bool>;
            for ( int i = 0; i < result_list.Count(); i++ )
            {
                BiosPrivacyUidResult result = result_list.Get( i );
                string uid = result.m_Uid;
                BiosPrivacyPermissionResultArray result_array = m_PermissionsList.Get( uid );
                BiosPrivacyPermissionResultArray result_array2 = result.m_Results;
                if ( result_array && result_array2 )
                {
                    if ( !BiosPrivacyPermissionResult.Compare( result_array.Get( 0 ), result_array2.Get( 0 ) ) )
                    {
                        new_list.Insert( result );
                        m_PermissionsList.Set( uid, result_array2 );
                        mute_list.Insert( uid, IsPlayerMuted( uid ) );
                    }
                }
                else
                {
                    m_PermissionsList.Insert( uid, result_array2 );
                    new_list.Insert( result );
                    mute_list.Insert( uid, IsPlayerMuted( uid ) );
                }
                if ( !m_MuteList.Contains( uid ) )
                {
                    m_MuteList.Insert( uid, !result_array2.Get( 0 ).m_IsAllowed );
                }
            }
            m_PermissionsAsyncInvoker.Invoke( new_list );
            m_MuteUpdateAsyncInvoker.Invoke( mute_list );
        }
    }
References BiosPrivacyPermissionResult::Compare(), ErrorCaught(), ScriptInvoker::Invoke(), IsPlayerMuted(), m_MuteList, m_MuteUpdateAsyncInvoker, m_PermissionsAsyncInvoker, m_PermissionsList, BiosPrivacyUidResult::m_Results, and BiosPrivacyUidResult::m_Uid.
Referenced by BiosPrivacyService::OnPermissions().
OnUserProfileAsync()
static void OnlineServices::OnUserProfileAsync (EBiosError error) inline static private
Definition at line 260 of file onlineservices.c.
    {
        ErrorCaught( error );
    }
References ErrorCaught().
Referenced by BiosSocialService::OnUserProfileAsync().
PromptUpdate()
static void OnlineServices::PromptUpdate () inline static private
Definition at line 755 of file onlineservices.c.
    {
        GetClientServices();
        if ( m_ClientServices )
        {
            m_ClientServices.GetPackageService().PromptUpdateAsync();
        }
    }
References GetClientServices(), BiosClientServices::GetPackageService(), m_ClientServices, and BiosPackageService::PromptUpdateAsync().
Referenced by BiosPackageService::OnCheckUpdate().
SetBiosUser()
static void OnlineServices::SetBiosUser (BiosUser user) inline static private
Definition at line 524 of file onlineservices.c.
    {
        m_BiosUser = user;
    }
References m_BiosUser.
Referenced by BiosUserManager::OnJoin(), and SelectGamepad().
SetGameplayActivity()
static void OnlineServices::SetGameplayActivity () inline static private
Definition at line 579 of file onlineservices.c.
    {
        string addr;
        int port;
        if( GetGame().GetHostAddress( addr, port ) )
        {
            GetClientServices();
            if( m_ClientServices )
            {
                m_ClientServices.GetSessionService().SetGameplayActivityAsync( addr, port );
            }
        }
    }
References GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::SetGameplayActivityAsync().
SetInviteServerInfo()
static void OnlineServices::SetInviteServerInfo (string ip, int port) inline static private
Definition at line 182 of file onlineservices.c.
    {
        m_InviteServerIP = ip;
        m_InviteServerPort = port;
    }
References m_InviteServerIP, and m_InviteServerPort.
Referenced by BiosSessionService::OnGetGameplaySession().
SetMultiplayState()
static void OnlineServices::SetMultiplayState (bool state) inline static private
Definition at line 535 of file onlineservices.c.
    {
        m_MultiplayState = state;
        bool is_multiplay;
        if( ClientData.GetSimplePlayerList() )
            is_multiplay = state && ( ClientData.GetSimplePlayerList().Count() > 1 );
        if( m_ClientServices )
            m_ClientServices.GetSessionService().SetMultiplayState(is_multiplay);
    }
References BiosClientServices::GetSessionService(), ClientData::GetSimplePlayerList(), m_ClientServices, m_MultiplayState, and BiosSessionService::SetMultiplayState().
Referenced by EnterGameplaySession(), LeaveGameplaySession(), OnEvent(), ShowDeadScreen(), and ClientData::SyncEvent_OnRecievedPlayerList().
SetPendingInviteList()
static void OnlineServices::SetPendingInviteList (array< string > invitees) inline static private
Definition at line 593 of file onlineservices.c.
    {
        string addr;
        int port;
        if( GetGame().GetHostAddress( addr, port ) )
        {
            GetClientServices();
            if( m_ClientServices )
            {
                m_PendingInvites = invitees;
                m_ClientServices.GetSessionService().InviteToGameplaySessionAsync( addr, port, GetPendingInviteList() );
            }
        }
        else
        {
            m_PendingInvites = invitees;
        }
    }
References GetClientServices(), GetGame(), GetPendingInviteList(), BiosClientServices::GetSessionService(), BiosSessionService::InviteToGameplaySessionAsync(), m_ClientServices, and m_PendingInvites.
Referenced by BiosUserManager::OnPartyHost().
SetServerFavorited()
static void OnlineServices::SetServerFavorited (string ipAddress, int port, int steamQueryPort, bool is_favorited) inline static private
Definition at line 119 of file onlineservices.c.
    {
        GetClientServices();
        if ( m_ClientServices )
        {
            if ( is_favorited )
            {
                m_ClientServices.GetLobbyService().AddServerFavorite( ipAddress, port, steamQueryPort );
            }
            else
            {
                m_ClientServices.GetLobbyService().RemoveServerFavorite( ipAddress, port, steamQueryPort );
            }
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References BiosLobbyService::AddServerFavorite(), GetClientServices(), BiosClientServices::GetLobbyService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosLobbyService::RemoveServerFavorite().
Referenced by ScriptedWidgetEventHandler::ToggleFavorite(), and UIScriptedMenu::ToggleFavoriteServer().
SetSessionHandle()
static void OnlineServices::SetSessionHandle (string handle) inline static private
Definition at line 491 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            m_ClientServices.GetSessionService().m_CurrentHandle = handle;
        }
    }
References GetClientServices(), BiosClientServices::GetSessionService(), m_ClientServices, and BiosSessionService::m_CurrentHandle.
Referenced by BiosUserManager::OnJoin().
ShowInviteScreen()
static void OnlineServices::ShowInviteScreen () inline static private
Definition at line 410 of file onlineservices.c.
    {
        #ifdef PLATFORM_CONSOLE
            GetClientServices();
            if( m_ClientServices )
            {
                string addr;
                int port;
                if( GetGame().GetHostAddress( addr, port ) )
                {
                    ErrorCaught( m_ClientServices.GetSessionService().ShowInviteToGameplaySessionAsync( addr, port ) );
                }
            }
            else
            {
                DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
            }
        #endif
    }
References ErrorCaught(), GetClientServices(), GetGame(), BiosClientServices::GetSessionService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosSessionService::ShowInviteToGameplaySessionAsync().
Referenced by UIScriptedMenu::OnClick().
ShowUserProfile()
static void OnlineServices::ShowUserProfile (string uid) inline static private
Definition at line 247 of file onlineservices.c.
    {
        GetClientServices();
        if( m_ClientServices )
        {
            m_ClientServices.GetSocialService().ShowUserProfileAsync( uid );
        }
        else
        {
            DebugPrint.LogErrorAndTrace( "BiosClientServices Error: Service reference does not exist." );
        }
    }
References GetClientServices(), BiosClientServices::GetSocialService(), DebugPrint::LogErrorAndTrace(), m_ClientServices, and BiosSocialService::ShowUserProfileAsync().
Referenced by ScriptedWidgetEventHandler::OnDoubleClick(), and UIScriptedMenu::Update().
Member Data Documentation
m_AutoConnectTries
int OnlineServices::m_AutoConnectTries = 0 static private
Definition at line 638 of file onlineservices.c.
Referenced by AutoConnectToEmptyServer(), and OnAutoConnectToEmptyServer().
m_BiosUser
protected ref BiosUser OnlineServices::m_BiosUser static private
Definition at line 28 of file onlineservices.c.
Referenced by GetBiosUser(), and SetBiosUser().
m_ClientServices
ref BiosClientServices OnlineServices::m_ClientServices static private
Definition at line 10 of file onlineservices.c.
Referenced by AutoConnectToEmptyServer(), CheckUpdate(), EnterGameplaySession(), GetCachedFavServerInfo(), GetClientServices(), GetCurrentServerInfo(), GetFavoriteServers(), GetServerModList(), GetSession(), GetSessionHandle(), IsInitialized(), LeaveGameplaySession(), LoadFriends(), LoadMPPrivilege(), LoadPermissions(), LoadServers(), LoadVoicePrivilege(), OnAutoConnectToEmptyServer(), PromptUpdate(), SetGameplayActivity(), SetMultiplayState(), SetPendingInviteList(), SetServerFavorited(), SetSessionHandle(), ShowInviteScreen(), and ShowUserProfile().
m_CurrentServerInfo
protected ref GetServersResultRow OnlineServices::m_CurrentServerInfo static private
Definition at line 17 of file onlineservices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_CurrentServerIP
protected string OnlineServices::m_CurrentServerIP static private
Definition at line 15 of file onlineservices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_CurrentServerPort
protected int OnlineServices::m_CurrentServerPort static private
Definition at line 16 of file onlineservices.c.
Referenced by ClearCurrentServerInfo(), GetCurrentServerInfo(), LeaveGameplaySession(), and OnLoadServersAsync().
m_FirstFriendsLoad
protected bool OnlineServices::m_FirstFriendsLoad = true static private
Definition at line 24 of file onlineservices.c.
Referenced by LeaveGameplaySession(), and OnFriendsAsync().
m_FriendsAsyncInvoker
ref ScriptInvoker OnlineServices::m_FriendsAsyncInvoker = new ScriptInvoker() static private
Definition at line 3 of file onlineservices.c.
Referenced by OnFriendsAsync().
m_FriendsList
protected ref map<string, ref BiosFriendInfo> OnlineServices::m_FriendsList static private
Definition at line 20 of file onlineservices.c.
Referenced by Init(), LeaveGameplaySession(), and OnFriendsAsync().
m_InviteServerIP
protected string OnlineServices::m_InviteServerIP static private
Definition at line 13 of file onlineservices.c.
Referenced by GetInviteServerInfo(), and SetInviteServerInfo().
m_InviteServerPort
protected int OnlineServices::m_InviteServerPort static private
Definition at line 14 of file onlineservices.c.
Referenced by GetInviteServerInfo(), and SetInviteServerInfo().
m_MultiplayState
protected bool OnlineServices::m_MultiplayState = false static private
Definition at line 25 of file onlineservices.c.
Referenced by GetMultiplayState(), and SetMultiplayState().
m_MuteList
protected ref map<string, bool> OnlineServices::m_MuteList static private
Definition at line 21 of file onlineservices.c.
Referenced by GetMuteList(), Init(), IsPlayerMuted(), MutePlayer(), and OnPermissionsAsync().
m_MuteUpdateAsyncInvoker
ref ScriptInvoker OnlineServices::m_MuteUpdateAsyncInvoker = new ScriptInvoker() static private
Definition at line 7 of file onlineservices.c.
Referenced by MissionBase::OnInit(), MissionBase::OnMissionFinish(), and OnPermissionsAsync().
m_PendingInvites
protected ref array<string> OnlineServices::m_PendingInvites static private
Definition at line 26 of file onlineservices.c.
Referenced by ClearPendingInviteList(), GetPendingInviteList(), and SetPendingInviteList().
m_PermissionsAsyncInvoker
ref ScriptInvoker OnlineServices::m_PermissionsAsyncInvoker = new ScriptInvoker() static private
Definition at line 4 of file onlineservices.c.
Referenced by UIScriptedMenu::Init(), OnPermissionsAsync(), and UIScriptedMenu::~InGameMenuXbox().
m_PermissionsList
protected ref map<string, ref BiosPrivacyPermissionResultArray> OnlineServices::m_PermissionsList static private
Definition at line 22 of file onlineservices.c.
Referenced by Init(), IsPlayerMuted(), and OnPermissionsAsync().
m_ServerAsyncInvoker
ref ScriptInvoker OnlineServices::m_ServerAsyncInvoker = new ScriptInvoker() static private
Definition at line 6 of file onlineservices.c.
m_ServerModLoadAsyncInvoker
ref ScriptInvoker OnlineServices::m_ServerModLoadAsyncInvoker = new ScriptInvoker() static private
Definition at line 8 of file onlineservices.c.
Referenced by UIScriptedMenu::Init(), OnGetServerModList(), and UIScriptedMenu::~ServerBrowserMenuNew().
m_ServersAsyncInvoker
ref ScriptInvoker OnlineServices::m_ServersAsyncInvoker = new ScriptInvoker() static private
Definition at line 5 of file onlineservices.c.
Referenced by UIScriptedMenu::Init(), ServerBrowserTab::LoadingServersStop(), OnLoadServersAsync(), ServerBrowserTab::RefreshList(), UIScriptedMenu::SetServersLoadingTab(), and UIScriptedMenu::~ServerBrowserMenuNew().
m_TrialService
ref TrialService OnlineServices::m_TrialService static private
Definition at line 11 of file onlineservices.c.
Referenced by Init(), IsGameActive(), and IsGameTrial().