DayzKode: ITEM_GeneralData Class Reference
ITEM_GeneralData Class Reference
Private Member Functions
void InitServer ()
Private Attributes
bool disableBaseDamage
!! all member variables must correspond with the cfggameplay.json file contents !!!!
bool disableContainerDamage
bool disableRespawnDialog
Detailed Description
Definition at line 28 of file cfggameplaydatajson.c.
Member Function Documentation
InitServer()
void ITEM_GeneralData::InitServer () inline private
Definition at line 30 of file cfggameplaydatajson.c.
    {
        disableBaseDamage = GetGame().ServerConfigGetInt( "disableBaseDamage" );
        disableContainerDamage = GetGame().ServerConfigGetInt( "disableContainerDamage" );
        disableRespawnDialog = GetGame().ServerConfigGetInt("disableRespawnDialog");
    }
References disableBaseDamage, disableContainerDamage, disableRespawnDialog, GetGame(), and CGame::ServerConfigGetInt().
Referenced by CfgGameplayJson::InitServer().
Member Data Documentation
disableBaseDamage
bool ITEM_GeneralData::disableBaseDamage private
!! all member variables must correspond with the cfggameplay.json file contents !!!!
Definition at line 38 of file cfggameplaydatajson.c.
Referenced by CfgGameplayHandler::GetDisableBaseDamage(), and InitServer().
disableContainerDamage
bool ITEM_GeneralData::disableContainerDamage private
Definition at line 39 of file cfggameplaydatajson.c.
Referenced by CfgGameplayHandler::GetDisableContainerDamage(), and InitServer().
disableRespawnDialog
bool ITEM_GeneralData::disableRespawnDialog private
Definition at line 40 of file cfggameplaydatajson.c.
Referenced by CfgGameplayHandler::GetDisableRespawnDialog(), and InitServer().