DayzKode: SymptomManager Class Reference
SymptomManager Class Reference
Private Member Functions
void AutoactivateSymptoms ()
void CleanAvailableSymptoms ()
void CleanDebug1 (string name, int y_offset)
void CleanDebug2 (string name, int y_offset)
void CleanUpPrimaryQueue ()
int ComparePriority (int prio1, int prio2)
int CreateUniqueID ()
void DebugRequestActivateSymptom (int symptom_id)
void DebugRequestExitSymptom (int SYMPTOM_uid)
void DecreaseSymptomCount (int symptom_id)
void DisplayDebug1 (string name, int y_offset, array< ref Param > Symptoms_primary, array< ref Param > Symptoms_secondary)
void DisplayDebug2 (string name, int y_offset, array< ref Param > Symptoms_primary, array< ref Param > Symptoms_secondary)
int FindFirstAvailableSymptomIndex ()
int GetCurrentCommandID ()
SymptomBase GetCurrentPrimaryActiveSymptom ()
PlayerBase GetPlayer ()
int GetStorageVersion ()
SymptomBase GetSymptomByUID (int SYMPTOM_uid)
int GetSymptomCount (int symptom_id)
int GetSymptomMaxCount (int symptom_id)
string GetSymptomName (int symptom_id)
int GetSymptomPriority (int symptom_id)
void IncreaseSymptomCount (int symptom_id)
void Init ()
bool IsSymptomPrimary (int symptom_id)
bool IsUIDUsed (int uid)
void OnAnimationFinished (eAnimFinishType type=eAnimFinishType.SUCCESS)
void OnAnimationStarted ()
void OnInputUserDataReceived (ParamsReadContext ctx)
void OnPlayerKilled ()
void OnRPC (int rpc_type, ParamsReadContext ctx)
void OnRPCDebug (int rpc_type, ParamsReadContext ctx)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnStoreSave (ParamsWriteContext ctx)
void OnSymptomExit (SymptomBase Symptom, int uid)
void OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state)
array< ref Param > PrepareClientDebug (array< ref SymptomBase > Symptoms)
SymptomBase QueueUpPrimarySymptom (int symptom_id, int uid=-1)
void QueueUpSecondarySymptom (int symptom_id, int uid=-1)
SymptomBase QueueUpSecondarySymptomEx (int symptom_id, int uid=-1)
void RegisterSymptom (SymptomBase Symptom)
void RemoveSecondarySymptom (int symptom_id)
Removes a single Symptom.
void RequestSymptomExit (int SYMPTOM_uid)
Exits a specific Symptom with a given UID.
void SendServerDebugToClient ()
void SetAnimation (ParamsReadContext ctx)
void ShowAvailableSymptoms ()
SmptAnimMetaBase SpawnAnimMetaObject (int symptom_id)
SymptomBase SpawnSymptom (int symptom_id, int uid=-1)
void SymptomManager (PlayerBase player)
void UpdateActiveSymptoms (float deltatime)
void ~SymptomManager ()
Private Attributes
int m_ActiveSymptomIndexPrimary = -1
ref map< int, int > m_ActiveSymptomTypes
ref SmptAnimMetaBase m_AnimMeta
ref map< int, ref SymptomBase > m_AvailableSymptoms
int m_CurrentCommandID
PlayerBase m_Player
bool m_ShowDebug = false
bool m_ShowDebug2 = false
ref array< ref SymptomBase > m_SymptomQueuePrimary
ref array< ref SymptomBase > m_SymptomQueueSecondary
ref array< ref Param > m_SymptomQueueServerDbg
ref array< ref Param > m_SymptomQueueServerDbgPrimary
ref array< ref Param > m_SymptomQueueServerDbgSecondary
ref map< int, SymptomBase > m_SymptomsUIDs
ref Timer m_Timer
const int STORAGE_VERSION = 121
Detailed Description
Definition at line 41 of file statemanager.c.
Constructor & Destructor Documentation
SymptomManager()
void SymptomManager::SymptomManager (PlayerBase player) inline private
Definition at line 102 of file statemanager.c.
    {
        m_ActiveSymptomTypes = new map<int, int>;
        m_SymptomsUIDs = new map<int , SymptomBase >;
        m_SymptomQueuePrimary = new array<ref SymptomBase>;
        m_SymptomQueueSecondary = new array<ref SymptomBase>;
        m_SymptomQueueServerDbg = new array<ref Param>;
        m_SymptomQueueServerDbgPrimary = new array<ref Param>;
        m_SymptomQueueServerDbgSecondary = new array<ref Param>;
        m_AvailableSymptoms = new map<int, ref SymptomBase>;
        m_Player = player;
        Init();
        AutoactivateSymptoms();
    }
References AutoactivateSymptoms(), Init(), m_ActiveSymptomTypes, m_AvailableSymptoms, m_Player, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbg, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, and m_SymptomsUIDs.
~SymptomManager()
void SymptomManager::~SymptomManager () inline private
Definition at line 136 of file statemanager.c.
    {
    }
Member Function Documentation
AutoactivateSymptoms()
void SymptomManager::AutoactivateSymptoms () inline private
Definition at line 92 of file statemanager.c.
    {
        if( GetGame().IsClient() )
        {
            return;
        }
        QueueUpSecondarySymptom(SymptomIDs.SYMPTOM_BLOODLOSS);
    }
References GetGame(), and QueueUpSecondarySymptom().
Referenced by SymptomManager().
CleanAvailableSymptoms()
void SymptomManager::CleanAvailableSymptoms () inline private
Definition at line 924 of file statemanager.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("available Symptoms", 300, 50);
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), and DbgUI::EndCleanupScope().
Referenced by OnTick().
CleanDebug1()
void SymptomManager::CleanDebug1 (string name, int y_offset) inline private
Definition at line 932 of file statemanager.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin(name, 50, y_offset);
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), and name.
Referenced by OnTick().
CleanDebug2()
void SymptomManager::CleanDebug2 (string name, int y_offset) inline private
Definition at line 940 of file statemanager.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin(name, 50, y_offset);
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), and name.
Referenced by OnTick().
CleanUpPrimaryQueue()
void SymptomManager::CleanUpPrimaryQueue () inline private
Definition at line 440 of file statemanager.c.
    {
        for(int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
        {
            m_SymptomQueuePrimary.Get(i).RequestDestroy();
        }
    }
References m_SymptomQueuePrimary.
Referenced by OnRPC().
ComparePriority()
int SymptomManager::ComparePriority (int prio1, int prio2) inline private
Definition at line 540 of file statemanager.c.
    {
        if ( prio1 > prio2 )
        {
            return 1;
        }
        else if ( prio2 > prio1 )
        {
            return 2;
        }
        return 0;
    }
Referenced by QueueUpPrimarySymptom().
CreateUniqueID()
int SymptomManager::CreateUniqueID () inline private
Definition at line 174 of file statemanager.c.
    {
        int uid = Math.RandomInt( 1, 2147483647);
        if( !IsUIDUsed(uid) ) return uid;
        else return CreateUniqueID();
    }
References CreateUniqueID(), IsUIDUsed(), and Math::RandomInt().
Referenced by CreateUniqueID(), and SpawnSymptom().
DebugRequestActivateSymptom()
void SymptomManager::DebugRequestActivateSymptom (int symptom_id) inline private
Definition at line 948 of file statemanager.c.
    {
        CachedObjectsParams.PARAM1_INT.param1 = symptom_id;
        if(GetPlayer()) GetGame().RPCSingleParam(GetPlayer(), ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG_ON , CachedObjectsParams.PARAM1_INT, true, GetPlayer().GetIdentity());
    }
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM1_INT, and CGame::RPCSingleParam().
Referenced by ShowAvailableSymptoms().
DebugRequestExitSymptom()
void SymptomManager::DebugRequestExitSymptom (int SYMPTOM_uid) inline private
Definition at line 769 of file statemanager.c.
    {
        Param1<int> p1 = new Param1<int>(SYMPTOM_uid);
        GetGame().RPCSingleParam(GetPlayer(), ERPCs.RPC_PLAYER_SYMPTOMS_EXIT, p1, true, GetPlayer().GetIdentity());
        //return;
        /*
        if( GetGame().IsClient() || ( GetGame().IsClient() && !GetGame().IsMultiplayer() )  )
        {
            Param1<int> p1 = new Param1<int>(SYMPTOM_uid);
            GetGame().RPCSingleParam(GetPlayer(), ERPCs.RPC_PLAYER_SymptomS_EXIT, p1, true, GetPlayer().GetIdentity());
        }
        */
    }
References GetGame(), GetPlayer(), and CGame::RPCSingleParam().
Referenced by DisplayDebug2().
DecreaseSymptomCount()
void SymptomManager::DecreaseSymptomCount (int symptom_id) inline private
Definition at line 404 of file statemanager.c.
    {
        if( m_ActiveSymptomTypes.Contains(symptom_id) )
        {
            if( m_ActiveSymptomTypes.Get(symptom_id) == 1)
                m_ActiveSymptomTypes.Remove(symptom_id);
            else
                m_ActiveSymptomTypes.Set(symptom_id, m_ActiveSymptomTypes.Get(symptom_id) - 1);
        }
    }
References m_ActiveSymptomTypes.
Referenced by OnSymptomExit().
DisplayDebug1()
void SymptomManager::DisplayDebug1 (string name, int y_offset, array< ref Param > Symptoms_primary, array< ref Param > Symptoms_secondary) inline private
Definition at line 804 of file statemanager.c.
    {
        string primary;
        Param3<bool, int, int> p3 = new Param3<bool, int, int>(false,0,0);
        DbgUI.BeginCleanupScope();
        DbgUI.Begin(name, 50, y_offset);
        DbgUI.Text("Primary: ");
        bool is_primary;
        int symptom_id;
        int SYMPTOM_uid;
        string SYMPTOM_name;
        for(int i = 0; i < Symptoms_primary.Count(); i++)
        {
            p3 = Param3<bool, int, int>.Cast(Symptoms_primary.Get(i));
            is_primary = p3.param1;
            symptom_id = p3.param2;
            SYMPTOM_uid = p3.param3;
            SYMPTOM_name = GetSymptomName(symptom_id);
            primary += SYMPTOM_name + " | ";
        }
        DbgUI.Text(primary);
        DbgUI.Text("Secondary: ");
        for(i = 0; i < Symptoms_secondary.Count(); i++)
        {
            p3 = Param3<bool, int, int>.Cast(Symptoms_secondary.Get(i));
            is_primary = p3.param1;
            symptom_id = p3.param2;
            SYMPTOM_uid = p3.param3;
            SYMPTOM_name = GetSymptomName(symptom_id);
            DbgUI.Text(SYMPTOM_name);
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), GetSymptomName(), name, and DbgUI::Text().
Referenced by OnTick().
DisplayDebug2()
void SymptomManager::DisplayDebug2 (string name, int y_offset, array< ref Param > Symptoms_primary, array< ref Param > Symptoms_secondary) inline private
Definition at line 849 of file statemanager.c.
    {
        string primary;
        Param3<bool, int, int> p3 = new Param3<bool, int, int>(false,0,0);
        DbgUI.BeginCleanupScope();
        DbgUI.Begin(name, 50, y_offset);
        DbgUI.Text("Primary: ");
        bool is_primary;
        int symptom_id;
        int SYMPTOM_uid;
        string SYMPTOM_name;
        for(int i = 0; i < Symptoms_primary.Count(); i++)
        {
            p3 = Param3<bool, int, int>.Cast(Symptoms_primary.Get(i));
            is_primary = p3.param1;
            symptom_id = p3.param2;
            SYMPTOM_uid = p3.param3;
            SYMPTOM_name = GetSymptomName(symptom_id);
            if(DbgUI.Button( i.ToString() + " " +SYMPTOM_name, 80))
            {
                PrintString("Symptom: "+ SYMPTOM_uid.ToString());
                DebugRequestExitSymptom(SYMPTOM_uid);
            }
        }
        DbgUI.Text("Secondary: ");
        for(i = 0; i < Symptoms_secondary.Count(); i++)
        {
            p3 = Param3<bool, int, int>.Cast(Symptoms_secondary.Get(i));
            is_primary = p3.param1;
            symptom_id = p3.param2;
            SYMPTOM_uid = p3.param3;
            SYMPTOM_name = GetSymptomName(symptom_id);
            if(DbgUI.Button( i.ToString() + " " +SYMPTOM_name, 80))
            {
                PrintString("Symptom: "+ SYMPTOM_uid.ToString());
                DebugRequestExitSymptom(SYMPTOM_uid);
            }
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DebugRequestExitSymptom(), DbgUI::End(), DbgUI::EndCleanupScope(), GetSymptomName(), name, PrintString(), and DbgUI::Text().
Referenced by OnTick().
FindFirstAvailableSymptomIndex()
int SymptomManager::FindFirstAvailableSymptomIndex () inline private
Definition at line 528 of file statemanager.c.
    {
        for (int i = 0; i < m_SymptomQueuePrimary.Count();i++)
        {
            if ( m_SymptomQueuePrimary.Get(i).CanActivate() )
            {
                return i;
            }
        }
        return -1;
    }
References m_SymptomQueuePrimary.
Referenced by OnTick().
GetCurrentCommandID()
int SymptomManager::GetCurrentCommandID () inline private
Definition at line 218 of file statemanager.c.
    {
        return m_CurrentCommandID;
    }
References m_CurrentCommandID.
GetCurrentPrimaryActiveSymptom()
SymptomBase SymptomManager::GetCurrentPrimaryActiveSymptom () inline private
Definition at line 511 of file statemanager.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( m_ActiveSymptomIndexPrimary >= 0 && m_ActiveSymptomIndexPrimary < m_SymptomQueuePrimary.Count() )
            {
                if ( m_SymptomQueuePrimary.Get(m_ActiveSymptomIndexPrimary) ) return m_SymptomQueuePrimary.Get(m_ActiveSymptomIndexPrimary);
            }
        }
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( m_SymptomQueuePrimary.Count() > 0 )
                return m_SymptomQueuePrimary.Get(0);
        }
        return NULL;
    }
References GetGame(), m_ActiveSymptomIndexPrimary, and m_SymptomQueuePrimary.
Referenced by AnimFinished(), OnAnimationStarted(), and UpdateActiveSymptoms().
GetPlayer()
PlayerBase SymptomManager::GetPlayer () inline private
Definition at line 140 of file statemanager.c.
    {
        return m_Player;
    }
References m_Player.
Referenced by DebugRequestActivateSymptom(), DebugRequestExitSymptom(), and SendServerDebugToClient().
GetStorageVersion()
int SymptomManager::GetStorageVersion () inline private
Definition at line 86 of file statemanager.c.
    {
        return STORAGE_VERSION;
    }
References STORAGE_VERSION.
GetSymptomByUID()
SymptomBase SymptomManager::GetSymptomByUID (int SYMPTOM_uid) inline private
Definition at line 130 of file statemanager.c.
    {
        return m_SymptomsUIDs.Get(SYMPTOM_uid);
    }
References m_SymptomsUIDs.
GetSymptomCount()
int SymptomManager::GetSymptomCount (int symptom_id) inline private
Definition at line 384 of file statemanager.c.
    {
        if( m_ActiveSymptomTypes.Contains(symptom_id) )
            return m_ActiveSymptomTypes.Get(symptom_id);
        else
            return -1;
    }
References m_ActiveSymptomTypes.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomMaxCount()
int SymptomManager::GetSymptomMaxCount (int symptom_id) inline private
Definition at line 378 of file statemanager.c.
    {
        return m_AvailableSymptoms.Get(symptom_id).GetMaxCount();
    }
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
GetSymptomName()
string SymptomManager::GetSymptomName (int symptom_id) inline private
Definition at line 193 of file statemanager.c.
    {
        return m_AvailableSymptoms.Get(symptom_id).GetName();
    }
References m_AvailableSymptoms.
Referenced by DisplayDebug1(), and DisplayDebug2().
GetSymptomPriority()
int SymptomManager::GetSymptomPriority (int symptom_id) inline private
Definition at line 553 of file statemanager.c.
    {
        return m_AvailableSymptoms.Get(symptom_id).GetPriority();
    }
References m_AvailableSymptoms.
Referenced by QueueUpPrimarySymptom().
IncreaseSymptomCount()
void SymptomManager::IncreaseSymptomCount (int symptom_id) inline private
Definition at line 392 of file statemanager.c.
    {
        if( m_ActiveSymptomTypes.Contains(symptom_id) )
        {
            m_ActiveSymptomTypes.Set(symptom_id, m_ActiveSymptomTypes.Get(symptom_id) + 1);
        }
        else
        {
            m_ActiveSymptomTypes.Insert(symptom_id, 1);
        }
    }
References m_ActiveSymptomTypes.
Referenced by SpawnSymptom().
Init()
void SymptomManager::Init () inline private
Definition at line 69 of file statemanager.c.
    {
        RegisterSymptom(new CoughSymptom);
        RegisterSymptom(new VomitSymptom);
        RegisterSymptom(new BlindnessSymptom);
        RegisterSymptom(new SneezeSymptom);
        RegisterSymptom(new FeverBlurSymptom);
        RegisterSymptom(new BloodLoss);
        RegisterSymptom(new LaughterSymptom);
        RegisterSymptom(new FreezeSymptom);
        RegisterSymptom(new HotSymptom);
        RegisterSymptom(new PainLightSymptom);
        RegisterSymptom(new PainHeavySymptom);
        RegisterSymptom(new HandShiversSymptom);
        //RegisterSymptom(new BulletHitSymptom);
    }
References RegisterSymptom().
Referenced by SymptomManager().
IsSymptomPrimary()
bool SymptomManager::IsSymptomPrimary (int symptom_id) inline private
Definition at line 209 of file statemanager.c.
    {
        return m_AvailableSymptoms.Get(symptom_id).IsPrimary();
    }
References m_AvailableSymptoms.
Referenced by OnRPCDebug(), and OnStoreLoad().
IsUIDUsed()
bool SymptomManager::IsUIDUsed (int uid) inline private
Definition at line 181 of file statemanager.c.
    {
        if( m_SymptomsUIDs.Contains(uid) )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References m_SymptomsUIDs.
Referenced by CreateUniqueID().
OnAnimationFinished()
void SymptomManager::OnAnimationFinished (eAnimFinishType type = eAnimFinishType.SUCCESS) inline private
Definition at line 160 of file statemanager.c.
    {
        if( m_AnimMeta )
        {
            m_AnimMeta.AnimFinished(type);
        }
    }
References m_AnimMeta.
Referenced by OnTick(), PlayRequest(), and Update().
OnAnimationStarted()
void SymptomManager::OnAnimationStarted () inline private
Definition at line 168 of file statemanager.c.
    {
        if( GetCurrentPrimaryActiveSymptom() )
            GetCurrentPrimaryActiveSymptom().AnimationStart();
    }
References SymptomBase::AnimationStart(), and GetCurrentPrimaryActiveSymptom().
Referenced by Update().
OnInputUserDataReceived()
void SymptomManager::OnInputUserDataReceived (ParamsReadContext ctx) inline private
Definition at line 214 of file statemanager.c.
    {
    }
OnPlayerKilled()
void SymptomManager::OnPlayerKilled () inline private
Definition at line 117 of file statemanager.c.
    {
        for(int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
        {
            m_SymptomQueuePrimary.Get(i).OnOwnerKilled();
        }
        for(i = 0; i < m_SymptomQueueSecondary.Count(); i++)
        {
            if(m_SymptomQueueSecondary.Get(i)) m_SymptomQueueSecondary.Get(i).OnOwnerKilled();
        }
    }
References m_SymptomQueuePrimary, and m_SymptomQueueSecondary.
OnRPC()
void SymptomManager::OnRPC (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 558 of file statemanager.c.
    {
        ctx.Read(CachedObjectsParams.PARAM2_INT_INT);
        int symptom_id = CachedObjectsParams.PARAM2_INT_INT.param1;
        int uid = CachedObjectsParams.PARAM2_INT_INT.param2;
        bool is_primary = m_AvailableSymptoms.Get(symptom_id).IsPrimary();
        if ( rpc_type == ERPCs.RPC_PLAYER_SYMPTOM_ON )
        {
            if ( is_primary )
            {
                CleanUpPrimaryQueue();
                QueueUpPrimarySymptom(symptom_id,uid);
            }
            else
            {
                QueueUpSecondarySymptom(symptom_id,uid);
            }
        }
        else if ( rpc_type == ERPCs.RPC_PLAYER_SYMPTOM_OFF )
        {
            if ( is_primary )
            {
                CleanUpPrimaryQueue();
            }
            else
            {
                RemoveSecondarySymptom( symptom_id );
            }
        }
    }
References CleanUpPrimaryQueue(), m_AvailableSymptoms, CachedObjectsParams::PARAM2_INT_INT, QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), Serializer::Read(), and RemoveSecondarySymptom().
OnRPCDebug()
void SymptomManager::OnRPCDebug (int rpc_type, ParamsReadContext ctx) inline private
Definition at line 591 of file statemanager.c.
    {
        #ifndef DEVELOPER
        return;
        #endif
        if ( rpc_type == ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG )
        {
            int primary_Symptoms_count;
            int secondary_Symptoms_count;
            int symptom_id;
            if ( ctx.Read(CachedObjectsParams.PARAM1_INT) )
            {
                primary_Symptoms_count = CachedObjectsParams.PARAM1_INT.param1;
            }
            if ( ctx.Read(CachedObjectsParams.PARAM1_INT) )
            {
                secondary_Symptoms_count = CachedObjectsParams.PARAM1_INT.param1;
            }
            m_SymptomQueueServerDbg.Clear();
            m_SymptomQueueServerDbgPrimary.Clear();
            m_SymptomQueueServerDbgSecondary.Clear();
            int overall_count = primary_Symptoms_count + secondary_Symptoms_count;
            for (int i = 0; i < overall_count ; i++)
            {
                Param3<bool, int, int> p3 = new Param3<bool, int, int>(false,0,0);
                ctx.Read(p3);
                bool is_primary = p3.param1;
                if (is_primary)
                {
                    m_SymptomQueueServerDbgPrimary.Insert(p3);//   m_SymptomQueueServerDbg.Insert(p3);
                }
                else
                {
                    m_SymptomQueueServerDbgSecondary.Insert(p3);
                }
                //PrintString("elements m_SymptomQueueServerDbgPrimary:" + m_SymptomQueueServerDbgPrimary.Count());
                //PrintString("elements m_SymptomQueueServerDbgSecondary:" + m_SymptomQueueServerDbgSecondary.Count());
            }
            /*
            for(i = 0; i < secondary_Symptoms_count; i++)
            {
                ctx.Read(CachedObjectsParams.PARAM1_STRING);
                m_SymptomQueueSecondaryServerDbg.Insert(CachedObjectsParams.PARAM1_STRING.param1);
            }*/
        }
        else if ( rpc_type == ERPCs.RPC_PLAYER_SYMPTOMS_EXIT )
        {
            ctx.Read(CachedObjectsParams.PARAM1_INT);
            int SYMPTOM_uid = CachedObjectsParams.PARAM1_INT.param1;
            RequestSymptomExit(SYMPTOM_uid);
        }
        else if ( rpc_type == ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG_ON)
        {
            ctx.Read(CachedObjectsParams.PARAM1_INT);
            int id = CachedObjectsParams.PARAM1_INT.param1;
            if ( IsSymptomPrimary(id) )
            {
                QueueUpPrimarySymptom(id);
            }
            else
            {
                QueueUpSecondarySymptom(id);
            }
        }
    }
References IsSymptomPrimary(), m_SymptomQueueServerDbg, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, CachedObjectsParams::PARAM1_INT, QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), Serializer::Read(), and RequestSymptomExit().
OnStoreLoad()
bool SymptomManager::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 740 of file statemanager.c.
    {
        array<int> m_SaveQueue;
        if(ctx.Read(m_SaveQueue))
        {
            for( int i = 0; i < m_SaveQueue.Count(); i++ )
            {
                int id = m_SaveQueue.Get(i);
                if( IsSymptomPrimary(id) )
                {
                    QueueUpPrimarySymptom( id );
                }
                else
                {
                    QueueUpSecondarySymptom( id );
                }
            }
            return true;
        }
        else
        {
            return false;
        }
    }
References IsSymptomPrimary(), QueueUpPrimarySymptom(), QueueUpSecondarySymptom(), and Serializer::Read().
OnStoreSave()
void SymptomManager::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 717 of file statemanager.c.
    {
        ref array<int>      m_SaveQueue = new array<int>;
        for( int i = 0; i < m_SymptomQueuePrimary.Count(); i++ )
        {
            if( m_SymptomQueuePrimary.Get(i).IsPersistent() )
            {
                m_SaveQueue.Insert( m_SymptomQueuePrimary.Get(i).GetType() );
            }
        }
        for( i = 0; i < m_SymptomQueueSecondary.Count(); i++ )
        {
            if( m_SymptomQueueSecondary.Get(i).IsPersistent() )
            {
                m_SaveQueue.Insert( m_SymptomQueueSecondary.Get(i).GetType() );
            }
        }
        ctx.Write( m_SaveQueue );
    }
References m_SymptomQueuePrimary, m_SymptomQueueSecondary, and Serializer::Write().
OnSymptomExit()
void SymptomManager::OnSymptomExit (SymptomBase Symptom, int uid) inline private
Definition at line 332 of file statemanager.c.
    {
        bool is_primary;
        if( Symptom )
        {
            is_primary = Symptom.IsPrimary();
            DecreaseSymptomCount(Symptom.GetType());
        }
        if( m_SymptomsUIDs.Contains(uid) )
        {
            m_SymptomsUIDs.Remove(uid);
        }
        else
        {
            Debug.LogError("Symptom with this UID does not exist", "PlayerSymptoms");
        }
        if(is_primary)
        {
            for(int i = 0; i < m_SymptomQueuePrimary.Count(); i++)
            {
                if( m_SymptomQueuePrimary.Get(i) == Symptom )
                {
                    m_SymptomQueuePrimary.RemoveOrdered(i);
                    break;
                }
            }
        }
        else
        {
            for(i = 0; i < m_SymptomQueueSecondary.Count(); i++)
            {
                if( m_SymptomQueueSecondary.Get(i) == Symptom )
                {
                    m_SymptomQueueSecondary.RemoveOrdered(i);
                    break;
                }
            }
        }
        m_ActiveSymptomIndexPrimary = -1;
        #ifdef DEVELOPER
        if( GetGame() ) SendServerDebugToClient();
        #endif
    }
References DecreaseSymptomCount(), GetGame(), SymptomBase::GetType(), SymptomBase::IsPrimary(), Debug::LogError(), m_ActiveSymptomIndexPrimary, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomsUIDs, and SendServerDebugToClient().
Referenced by SymptomBase::OnDestructed().
OnTick()
void SymptomManager::OnTick (float deltatime, int pCurrentCommandID, HumanMovementState movement_state) inline private
Definition at line 223 of file statemanager.c.
    {
        m_CurrentCommandID = pCurrentCommandID;
        if(m_ActiveSymptomIndexPrimary == -1)
        {
            m_ActiveSymptomIndexPrimary = FindFirstAvailableSymptomIndex();
        }
        UpdateActiveSymptoms(deltatime);
        if( m_AnimMeta )
        {
            if( m_AnimMeta.IsDestroyReqested() )
            {
                m_AnimMeta = null;
            }
        }
        if( m_AnimMeta )
        {
            //anim requested
            if( !m_AnimMeta.IsPlaying() )
            {
                if( m_AnimMeta.PlayRequest() == EAnimPlayState.FAILED )
                {
                    OnAnimationFinished(eAnimFinishType.FAILURE);
                }
            }
            else
            {
                m_AnimMeta.Update(movement_state);
            }
        }
        #ifdef DEVELOPER
        if( GetGame().IsMultiplayer() && GetGame().IsServer() ) return;//must be here !!!
        if ( DiagMenu.GetBool(DiagMenuIDs.DM_PLAYER_SYMPTOMS_SHOW) )
        {
            //DisplayDebug(true);
            array<ref Param>  primary_debug = PrepareClientDebug(m_SymptomQueuePrimary);
            array<ref Param>  secondary_debug = PrepareClientDebug(m_SymptomQueueSecondary);
            DisplayDebug1("Symptoms Client", 50,primary_debug, secondary_debug);
            DisplayDebug2("Symptoms Server", 300,m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary);
            ShowAvailableSymptoms();
        }
        else
        {
            CleanDebug1("Symptoms Client",50);
            CleanDebug2("Symptoms Server",300);
            CleanAvailableSymptoms();
        }
        #endif
    }
References CleanAvailableSymptoms(), CleanDebug1(), CleanDebug2(), DisplayDebug1(), DisplayDebug2(), FindFirstAvailableSymptomIndex(), DiagMenu::GetBool(), GetGame(), m_ActiveSymptomIndexPrimary, m_AnimMeta, m_CurrentCommandID, m_SymptomQueuePrimary, m_SymptomQueueSecondary, m_SymptomQueueServerDbgPrimary, m_SymptomQueueServerDbgSecondary, OnAnimationFinished(), PrepareClientDebug(), ShowAvailableSymptoms(), and UpdateActiveSymptoms().
PrepareClientDebug()
array< ref Param > SymptomManager::PrepareClientDebug (array< ref SymptomBase > Symptoms) inline private
Definition at line 784 of file statemanager.c.
    {
        array<ref Param> debug_array = new array<ref Param>;
        Param3<bool, int, int> p3;
        for(int i = 0; i < Symptoms.Count(); i++)
        {
            bool is_primary     = Symptoms.Get(i).IsPrimary();
            int symptom_id      = Symptoms.Get(i).GetType();
            int SYMPTOM_uid         = Symptoms.Get(i).GetUID();
            p3 = new Param3<bool,int,int>(is_primary, symptom_id, SYMPTOM_uid );
            debug_array.Insert(p3);
        }
        return debug_array;
    }
Referenced by OnTick().
QueueUpPrimarySymptom()
SymptomBase SymptomManager::QueueUpPrimarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 449 of file statemanager.c.
    {
        SymptomBase Symptom;
        if((GetSymptomCount(symptom_id) >= GetSymptomMaxCount(symptom_id)) && GetSymptomMaxCount(symptom_id) != -1)
            return null;
        for( int i = 0; i < m_SymptomQueuePrimary.Count(); i++ )
        {
            if( m_SymptomQueuePrimary.Get(i).CanBeInterupted() && ComparePriority( GetSymptomPriority(symptom_id), m_SymptomQueuePrimary.Get(i).GetPriority() ) == 1 )
            {
                Symptom = SpawnSymptom( symptom_id, uid );
                m_SymptomQueuePrimary.InsertAt(Symptom,i);
                if( m_SymptomQueuePrimary.Count() > MAX_QUEUE_SIZE )
                {
                    m_SymptomQueuePrimary.Get(MAX_QUEUE_SIZE).RequestDestroy();// no need to remove from the array, that's done via Symptom callback on destruct
                }
                break;
            }
        }
        if( !Symptom && m_SymptomQueuePrimary.Count() < MAX_QUEUE_SIZE)
        {
            Symptom = SpawnSymptom( symptom_id, uid );
            m_SymptomQueuePrimary.Insert(Symptom);
        }
        #ifdef DEVELOPER
        SendServerDebugToClient();
        #endif
        return Symptom;
    }
References ComparePriority(), GetSymptomCount(), GetSymptomMaxCount(), GetSymptomPriority(), m_SymptomQueuePrimary, MAX_QUEUE_SIZE, SendServerDebugToClient(), and SpawnSymptom().
Referenced by OnRPC(), OnRPCDebug(), and OnStoreLoad().
QueueUpSecondarySymptom()
void SymptomManager::QueueUpSecondarySymptom (int symptom_id, int uid = -1) inline private
Definition at line 479 of file statemanager.c.
    {
         QueueUpSecondarySymptomEx(symptom_id, uid);
    }
References QueueUpSecondarySymptomEx().
Referenced by AutoactivateSymptoms(), OnRPC(), OnRPCDebug(), and OnStoreLoad().
QueueUpSecondarySymptomEx()
SymptomBase SymptomManager::QueueUpSecondarySymptomEx (int symptom_id, int uid = -1) inline private
Definition at line 484 of file statemanager.c.
    {
        if((GetSymptomCount(symptom_id) >= GetSymptomMaxCount(symptom_id)) && GetSymptomMaxCount(symptom_id) != -1)
            return null;
        if( m_AvailableSymptoms.Get(symptom_id).IsPrimary() )
            return null;
        SymptomBase Symptom = SpawnSymptom( symptom_id, uid);
        m_SymptomQueueSecondary.Insert(Symptom);
        return Symptom;
    }
References GetSymptomCount(), GetSymptomMaxCount(), m_AvailableSymptoms, m_SymptomQueueSecondary, and SpawnSymptom().
Referenced by QueueUpSecondarySymptom().
RegisterSymptom()
void SymptomManager::RegisterSymptom (SymptomBase Symptom) inline private
Definition at line 145 of file statemanager.c.
    {
        Symptom.Init(this, m_Player,0);
        int id = Symptom.GetType();
        if( m_AvailableSymptoms.Contains(id) )
        {
            Error("SymptomBase Symptom already registered !");
            return;
        }
        m_AvailableSymptoms.Insert(id, Symptom);
        //PrintString("inserting id: "+ToString(id));
    }
References Error(), SymptomBase::GetType(), SymptomBase::Init(), m_AvailableSymptoms, and m_Player.
Referenced by Init().
RemoveSecondarySymptom()
void SymptomManager::RemoveSecondarySymptom (int symptom_id) inline private
Removes a single Symptom.
Definition at line 499 of file statemanager.c.
    {
        for (int i = 0; i < m_SymptomQueueSecondary.Count();i++)
        {
            if ( m_SymptomQueueSecondary.Get(i) && m_SymptomQueueSecondary.Get(i).GetType() == symptom_id )
            {
                m_SymptomQueueSecondary.Get(i).RequestDestroy();
                return;
            }
        }
    }
References m_SymptomQueueSecondary.
Referenced by OnRPC().
RequestSymptomExit()
void SymptomManager::RequestSymptomExit (int SYMPTOM_uid) inline private
Exits a specific Symptom with a given UID.
Definition at line 204 of file statemanager.c.
    {
        if( m_SymptomsUIDs.Get(SYMPTOM_uid) ) m_SymptomsUIDs.Get(SYMPTOM_uid).RequestDestroy();
    }
References m_SymptomsUIDs.
Referenced by OnRPCDebug().
SendServerDebugToClient()
void SymptomManager::SendServerDebugToClient () inline private
Definition at line 670 of file statemanager.c.
    {
        #ifndef DEVELOPER
        if ( !GetPlayer().IsPlayerSelected() ) return;
        #endif
        array<ref Param> debug_list = new array<ref Param>;
        Param1<int> p1 = new Param1<int>(0);
        Param1<int> p2 = new Param1<int>(0);
        p1.param1 = m_SymptomQueuePrimary.Count();
        p2.param1 = m_SymptomQueueSecondary.Count();
        debug_list.Insert(p1);
        debug_list.Insert(p2);
        Param3<bool,int,int> p;
        bool is_primary;
        int symptom_id;
        int SYMPTOM_uid;
        for ( int i = 0; i < m_SymptomQueuePrimary.Count(); i++ )
        {
            is_primary = m_SymptomQueuePrimary.Get(i).IsPrimary();
            symptom_id = m_SymptomQueuePrimary.Get(i).GetType();
            SYMPTOM_uid = m_SymptomQueuePrimary.Get(i).GetUID();
            p = new Param3<bool,int,int>(is_primary, symptom_id, SYMPTOM_uid );
            debug_list.Insert(p);
        }
        for ( i = 0; i < m_SymptomQueueSecondary.Count(); i++ )
        {
            is_primary = m_SymptomQueueSecondary.Get(i).IsPrimary();
            symptom_id = m_SymptomQueueSecondary.Get(i).GetType();
            SYMPTOM_uid = m_SymptomQueueSecondary.Get(i).GetUID();
            p = new Param3<bool,int,int>(is_primary, symptom_id, SYMPTOM_uid );
            debug_list.Insert(p);
        }
        GetGame().RPC(GetPlayer(), ERPCs.RPC_PLAYER_SYMPTOMS_DEBUG, debug_list, true);
    }
References GetGame(), GetPlayer(), IsPlayerSelected(), m_SymptomQueuePrimary, m_SymptomQueueSecondary, and CGame::RPC().
Referenced by SymptomBase::Activate(), OnSymptomExit(), and QueueUpPrimarySymptom().
SetAnimation()
void SymptomManager::SetAnimation (ParamsReadContext ctx) inline private
Definition at line 280 of file statemanager.c.
    {
        if(m_AnimMeta)
        {
            // animation meta already exists
            // pass
        }
        else
        {
            int state_type;
            if(ctx.Read(state_type))
            {
                m_AnimMeta = SpawnAnimMetaObject(state_type);
                if(m_AnimMeta)
                {
                    m_AnimMeta.Init(ctx, this, m_Player);
                }
            }
        }
    }
References SmptAnimMetaBase::Init(), m_AnimMeta, m_Player, Serializer::Read(), and SpawnAnimMetaObject().
ShowAvailableSymptoms()
void SymptomManager::ShowAvailableSymptoms () inline private
Definition at line 902 of file statemanager.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("available Symptoms", 300, 50);
        for(int i = 0; i < m_AvailableSymptoms.Count(); i++)
        {
            SymptomBase Symptom = m_AvailableSymptoms.GetElement(i);
            string SYMPTOM_name = Symptom.GetName();
            int symptom_id = Symptom.GetType();
            if(DbgUI.Button( i.ToString() + " " + SYMPTOM_name, 80))
            {
                DebugRequestActivateSymptom(symptom_id);
            }
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DebugRequestActivateSymptom(), DbgUI::End(), DbgUI::EndCleanupScope(), SymptomBase::GetName(), SymptomBase::GetType(), and m_AvailableSymptoms.
Referenced by OnTick().
SpawnAnimMetaObject()
SmptAnimMetaBase SymptomManager::SpawnAnimMetaObject (int symptom_id) inline private
Definition at line 198 of file statemanager.c.
    {
        return m_AvailableSymptoms.Get(symptom_id).SpawnAnimMetaObject();
    }
References m_AvailableSymptoms.
Referenced by SetAnimation().
SpawnSymptom()
SymptomBase SymptomManager::SpawnSymptom (int symptom_id, int uid = -1) inline private
Definition at line 415 of file statemanager.c.
    {
        if( m_AvailableSymptoms.Get(symptom_id) )
        {
            SymptomBase Symptom = SymptomBase.Cast(m_AvailableSymptoms.Get(symptom_id).ClassName().ToType().Spawn());
            if(uid == -1)
            {
                uid = CreateUniqueID();
            }
            Symptom.Init(this, m_Player,uid);
            if( m_SymptomsUIDs.Contains(uid) )
                Error("Symptoms: Unique ID already exists !");
            m_SymptomsUIDs.Insert(uid, Symptom);
            IncreaseSymptomCount(symptom_id);
            return Symptom;
        }
        if( !Symptom )
        {
            Error("Symptom not registered");
        }
        return NULL;
    }
References CreateUniqueID(), Error(), IncreaseSymptomCount(), SymptomBase::Init(), m_AvailableSymptoms, m_Player, and m_SymptomsUIDs.
Referenced by QueueUpPrimarySymptom(), and QueueUpSecondarySymptomEx().
UpdateActiveSymptoms()
void SymptomManager::UpdateActiveSymptoms (float deltatime) inline private
Definition at line 301 of file statemanager.c.
    {
        //if( GetGame().IsClient() && !m_Player.IsPlayer() ) return;
        //primary
        if( GetCurrentPrimaryActiveSymptom() )
        {
            if( !GetCurrentPrimaryActiveSymptom().IsActivated() )
            {
                if ( GetCurrentPrimaryActiveSymptom().CanActivate() )
                    GetCurrentPrimaryActiveSymptom().Activate();
            }
            if( GetCurrentPrimaryActiveSymptom().IsActivated() )
            {
                GetCurrentPrimaryActiveSymptom().Update(deltatime);
            }
        }
        //secondary
        for(int i = 0; i < m_SymptomQueueSecondary.Count(); i++)
        {
            if( m_SymptomQueueSecondary.Get(i) && !m_SymptomQueueSecondary.Get(i).IsActivated() )
            {
                m_SymptomQueueSecondary.Get(i).Activate();
            }
            else
            {
                if(m_SymptomQueueSecondary.Get(i)) m_SymptomQueueSecondary.Get(i).Update(deltatime);
            }
        }
    }
References SymptomBase::Activate(), GetCurrentPrimaryActiveSymptom(), m_SymptomQueueSecondary, SymptomBase::Update(), and array::Update().
Referenced by OnTick().
Member Data Documentation
m_ActiveSymptomIndexPrimary
int SymptomManager::m_ActiveSymptomIndexPrimary = -1 private
Definition at line 59 of file statemanager.c.
Referenced by GetCurrentPrimaryActiveSymptom(), OnSymptomExit(), and OnTick().
m_ActiveSymptomTypes
ref map<int, int> SymptomManager::m_ActiveSymptomTypes private
Definition at line 45 of file statemanager.c.
Referenced by DecreaseSymptomCount(), GetSymptomCount(), IncreaseSymptomCount(), and SymptomManager().
m_AnimMeta
ref SmptAnimMetaBase SymptomManager::m_AnimMeta private
Definition at line 67 of file statemanager.c.
Referenced by OnAnimationFinished(), OnTick(), and SetAnimation().
m_AvailableSymptoms
ref map<int, ref SymptomBase> SymptomManager::m_AvailableSymptoms private
Definition at line 44 of file statemanager.c.
Referenced by GetSymptomMaxCount(), GetSymptomName(), GetSymptomPriority(), IsSymptomPrimary(), OnRPC(), QueueUpSecondarySymptomEx(), RegisterSymptom(), ShowAvailableSymptoms(), SpawnAnimMetaObject(), SpawnSymptom(), and SymptomManager().
m_CurrentCommandID
int SymptomManager::m_CurrentCommandID private
Definition at line 60 of file statemanager.c.
Referenced by GetCurrentCommandID(), and OnTick().
m_Player
PlayerBase SymptomManager::m_Player private
Definition at line 43 of file statemanager.c.
Referenced by GetPlayer(), RegisterSymptom(), SetAnimation(), SpawnSymptom(), and SymptomManager().
m_ShowDebug
bool SymptomManager::m_ShowDebug = false private
Definition at line 64 of file statemanager.c.
m_ShowDebug2
bool SymptomManager::m_ShowDebug2 = false private
Definition at line 65 of file statemanager.c.
m_SymptomQueuePrimary
ref array<ref SymptomBase> SymptomManager::m_SymptomQueuePrimary private
Definition at line 47 of file statemanager.c.
Referenced by CleanUpPrimaryQueue(), FindFirstAvailableSymptomIndex(), GetCurrentPrimaryActiveSymptom(), OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpPrimarySymptom(), SendServerDebugToClient(), and SymptomManager().
m_SymptomQueueSecondary
ref array<ref SymptomBase> SymptomManager::m_SymptomQueueSecondary private
Definition at line 48 of file statemanager.c.
Referenced by OnPlayerKilled(), OnStoreSave(), OnSymptomExit(), OnTick(), QueueUpSecondarySymptomEx(), RemoveSecondarySymptom(), SendServerDebugToClient(), SymptomManager(), and UpdateActiveSymptoms().
m_SymptomQueueServerDbg
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbg private
Definition at line 53 of file statemanager.c.
Referenced by OnRPCDebug(), and SymptomManager().
m_SymptomQueueServerDbgPrimary
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbgPrimary private
Definition at line 54 of file statemanager.c.
Referenced by OnRPCDebug(), OnTick(), and SymptomManager().
m_SymptomQueueServerDbgSecondary
ref array<ref Param> SymptomManager::m_SymptomQueueServerDbgSecondary private
Definition at line 55 of file statemanager.c.
Referenced by OnRPCDebug(), OnTick(), and SymptomManager().
m_SymptomsUIDs
ref map<int , SymptomBase > SymptomManager::m_SymptomsUIDs private
Definition at line 50 of file statemanager.c.
Referenced by GetSymptomByUID(), IsUIDUsed(), OnSymptomExit(), RequestSymptomExit(), SpawnSymptom(), and SymptomManager().
m_Timer
ref Timer SymptomManager::m_Timer private
Definition at line 57 of file statemanager.c.
STORAGE_VERSION
const int SymptomManager::STORAGE_VERSION = 121 private
Definition at line 62 of file statemanager.c.
Referenced by GetStorageVersion().