DayzKode: BiosSessionService Class Reference
BiosSessionService Class Reference
Private Member Functions
proto native EBiosError ClearActivityAsync ()
not implemented
proto native EBiosError EnterGameplaySessionAsync (string session_address, int session_port)
Enter a gameplay session.
proto native EBiosError GetSessionAsync (string join_handle)
Gets a session from a join handle.
proto native EBiosError InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list)
Send invite to list of users.
proto native EBiosError LeaveGameplaySessionAsync (string session_address, int session_port)
Leave a gameplay session.
void OnClearActivity (EBiosError error)
Callback function.
void OnEnterGameplaySession (string session_address, int session_port, EBiosError error)
Callback function.
void OnGetGameplaySession (string session_address, int session_port)
Callback function.
void OnGetSessionError (EBiosError error)
//! Callback function, not implemented
void OnInviteToGameplaySession (EBiosError error)
Callback function.
void OnLeaveGameplaySession (EBiosError error)
Callback function.
void OnSetActivity (EBiosError error)
Callback function.
void OnShowInviteToGameplaySession (EBiosError error)
Callback function.
proto native EBiosError SetGameplayActivityAsync (string session_address, int session_port)
Sets the activity to a gameplay session.
proto native void SetMultiplayState (bool is_active)
Notifiy about interactive multiplayer state.
proto native EBiosError ShowInviteToGameplaySessionAsync (string session_address, int session_port)
Show system UI to invite friends to current gameplay session.
void TryGetSession (string join_handle="")
Gets a session from a join handle.
Private Attributes
string m_CurrentHandle
protected int m_GetSessionAttempts
Detailed Description
Definition at line 1 of file biossessionservice.c.
Member Function Documentation
ClearActivityAsync()
proto native EBiosError BiosSessionService::ClearActivityAsync () private
not implemented
Clears the current activity
The async result is returned in the OnClearActivity callback. Expected errors:
Returns
EBiosError indicating if the async operation is pending.
EnterGameplaySessionAsync()
proto native EBiosError BiosSessionService::EnterGameplaySessionAsync (string session_address, int session_port) private
Enter a gameplay session.
The async result is returned in the OnEnterGameplaySession callback. Expected errors: LOGICAL - if the user is currently in an active gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::EnterGameplaySession().
GetSessionAsync()
proto native EBiosError BiosSessionService::GetSessionAsync (string join_handle) private
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Referenced by TryGetSession().
InviteToGameplaySessionAsync()
proto native EBiosError BiosSessionService::InviteToGameplaySessionAsync (string session_address, int session_port, array< string > invitee_list) private
Send invite to list of users.
The async result is returned in the OnInviteToGameplaySession callback. The user must be inside the session. That means, OnEnterGameplaySession must be called with no errors.
Parameters
session_address server IP address.
session_port server port.
invitee_list list of users to invite
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession(), and OnlineServices::SetPendingInviteList().
LeaveGameplaySessionAsync()
proto native EBiosError BiosSessionService::LeaveGameplaySessionAsync (string session_address, int session_port) private
Leave a gameplay session.
The async result is returned in the OnLeaveGameplaySession callback. If there is an unexpected error the state is cleared. Expected errors: ERR_NOT_FOUND - when attempting to leave a gameplay session the user is not part of. ERR_LOGICAL - when the user is not in a gameplay session.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::LeaveGameplaySession().
OnClearActivity()
void BiosSessionService::OnClearActivity (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 152 of file biossessionservice.c.
    {
    }
OnEnterGameplaySession()
void BiosSessionService::OnEnterGameplaySession (string session_address, int session_port, EBiosError error) inline private
Callback function.
Parameters
session_address server IP address. Empty if failed.
session_port server port. 0 if failed.
error error indicating success or fail of the async operation.
Definition at line 237 of file biossessionservice.c.
    {
        if ( !OnlineServices.ErrorCaught( error ) )
        {
            SetGameplayActivityAsync( session_address, session_port );
            if ( OnlineServices.GetPendingInviteList() )
                InviteToGameplaySessionAsync( session_address, session_port, OnlineServices.GetPendingInviteList() );
            //OnlineServices.GetCurrentServerInfo(session_address, session_port);
        }
    }
References OnlineServices::ErrorCaught(), OnlineServices::GetPendingInviteList(), InviteToGameplaySessionAsync(), and SetGameplayActivityAsync().
OnGetGameplaySession()
void BiosSessionService::OnGetGameplaySession (string session_address, int session_port) inline private
Callback function.
Parameters
session_address server IP address.
session_port server port.
Definition at line 161 of file biossessionservice.c.
    {
        m_GetSessionAttempts = 0;
        if ( g_Game.GetGameState() == DayZGameState.IN_GAME )
        {
            string addr;
            int port;
            bool found = GetGame().GetHostAddress( addr, port );
            if ( found && !( addr == session_address && port == session_port ) )
            {
                OnlineServices.SetInviteServerInfo( session_address, session_port );
                g_Game.GetUIManager().EnterScriptedMenu( MENU_INVITE_TIMER, null );
            }
            else
            {
                NotificationSystem.AddNotification( NotificationType.INVITE_FAIL_SAME_SERVER, 6, "#ps4_already_in_session" );
            }
        }
        else
        {
            g_Game.ConnectFromJoin( session_address, session_port );
        }
    }
References NotificationSystem::AddNotification(), g_Game, GetGame(), CGame::GetHostAddress(), m_GetSessionAttempts, MENU_INVITE_TIMER, and OnlineServices::SetInviteServerInfo().
OnGetSessionError()
void BiosSessionService::OnGetSessionError (EBiosError error) inline private
//! Callback function, not implemented
Callback function
Parameters
error error indicating fail of the async operation. Cannot be OK.
Definition at line 195 of file biossessionservice.c.
    {
        OnlineServices.ErrorCaught( error );
        m_GetSessionAttempts++;
        #ifdef PLATFORM_XBOX
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( TryGetSession, 100, false, "" );
        #else
            #ifdef PLATFORM_PS4
                GetGame().GetUserManager().SelectUserEx(OnlineServices.GetBiosUser());
                if( g_Game.GetGameState() != DayZGameState.IN_GAME )
                {
                    if( GetGame().GetMission() )
                    {
                        if( g_Game.GetGameState() != DayZGameState.MAIN_MENU )
{
                            GetGame().GetUIManager().CloseAllSubmenus();
                            GetGame().GetMission().AbortMission();
                            if (g_Game.GetGameState() == DayZGameState.JOIN)
                                NotificationSystem.AddNotification(NotificationType.JOIN_FAIL_GET_SESSION, 6);
                            g_Game.SetGameState( DayZGameState.MAIN_MENU );
                            g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
                            g_Game.GamepadCheck();
                            return;
                        }
                    }
                    else
                    {
                        g_Game.MainMenuLaunch();
                    }
                }
                NotificationSystem.AddNotification( NotificationType.JOIN_FAIL_GET_SESSION, 6 );
            #endif
        #endif
    }
References Mission::AbortMission(), NotificationSystem::AddNotification(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), UIManager::CloseAllSubmenus(), OnlineServices::ErrorCaught(), g_Game, OnlineServices::GetBiosUser(), CGame::GetCallQueue(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), CGame::GetUserManager(), m_GetSessionAttempts, BiosUserManager::SelectUserEx(), and TryGetSession().
OnInviteToGameplaySession()
void BiosSessionService::OnInviteToGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 270 of file biossessionservice.c.
    {
    }
OnLeaveGameplaySession()
void BiosSessionService::OnLeaveGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 253 of file biossessionservice.c.
    {
    }
OnSetActivity()
void BiosSessionService::OnSetActivity (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 143 of file biossessionservice.c.
    {
        OnlineServices.ErrorCaught( error );
    }
References OnlineServices::ErrorCaught().
OnShowInviteToGameplaySession()
void BiosSessionService::OnShowInviteToGameplaySession (EBiosError error) inline private
Callback function.
Parameters
error indicating success or fail of the async operation.
Definition at line 261 of file biossessionservice.c.
    {
        OnlineServices.ErrorCaught( error );
    }
References OnlineServices::ErrorCaught().
SetGameplayActivityAsync()
proto native EBiosError BiosSessionService::SetGameplayActivityAsync (string session_address, int session_port) private
Sets the activity to a gameplay session.
The async result is returned in the OnSetActivity callback. Expected errors: ERR_NOT_FOUND - when attempting to set a gameplay session activity the user is not part of.
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnEnterGameplaySession(), and OnlineServices::SetGameplayActivity().
SetMultiplayState()
proto native void BiosSessionService::SetMultiplayState (bool is_active) private
Notifiy about interactive multiplayer state.
Referenced by OnlineServices::SetMultiplayState().
ShowInviteToGameplaySessionAsync()
proto native EBiosError BiosSessionService::ShowInviteToGameplaySessionAsync (string session_address, int session_port) private
Show system UI to invite friends to current gameplay session.
The async result is returned in the OnShowInviteToGameplaySession callback. On Xbox, if session with session_address and session_port does not exist, then xbox show message "We could not send the invite".
Parameters
session_address server IP address.
session_port server port.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::ShowInviteScreen().
TryGetSession()
void BiosSessionService::TryGetSession (string join_handle = "") inline private
Gets a session from a join handle.
The async result is returned in the OnGetGameplaySession, OnGetLobbySession or OnGetSessionError callback, dependinng on the type of session, or error. Expected errors:
Parameters
join_handle the parsed join handle.
Returns
EBiosError indicating if the async operation is pending.
Definition at line 41 of file biossessionservice.c.
    {
        if ( join_handle != "" )
        {
            m_GetSessionAttempts    = 0;
            m_CurrentHandle         = join_handle;
        }
        if ( m_GetSessionAttempts < 10 )
            GetSessionAsync( m_CurrentHandle );
        else
        {
            GetGame().GetUserManager().SelectUserEx(OnlineServices.GetBiosUser());
            if ( g_Game.GetGameState() != DayZGameState.IN_GAME )
            {
                if ( GetGame().GetMission() )
                {
                    GetGame().GetUIManager().CloseAllSubmenus();
                    GetGame().GetMission().AbortMission();
                    g_Game.SetGameState( DayZGameState.MAIN_MENU );
                    g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
                    g_Game.GamepadCheck();
                }
                else
                {
                    g_Game.MainMenuLaunch();
                }
            }
            GetGame().GetUIManager().ShowDialog( "#str_xbox_join_fail_title", "#str_xbox_join_fail", 444, DBT_OK, DBB_NONE, DMT_INFO, GetGame().GetUIManager().GetMenu() );
        }
    }
References Mission::AbortMission(), UIManager::CloseAllSubmenus(), g_Game, OnlineServices::GetBiosUser(), GetGame(), CGame::GetMission(), GetSessionAsync(), CGame::GetUIManager(), CGame::GetUserManager(), m_CurrentHandle, m_GetSessionAttempts, BiosUserManager::SelectUserEx(), and UIManager::ShowDialog().
Referenced by OnlineServices::GetSession(), and OnGetSessionError().
Member Data Documentation
m_CurrentHandle
string BiosSessionService::m_CurrentHandle private
Definition at line 4 of file biossessionservice.c.
Referenced by OnlineServices::GetSessionHandle(), OnlineServices::SetSessionHandle(), and TryGetSession().
m_GetSessionAttempts
protected int BiosSessionService::m_GetSessionAttempts private
Definition at line 3 of file biossessionservice.c.
Referenced by OnGetGameplaySession(), OnGetSessionError(), and TryGetSession().