DayzKode: PlantSuper Class Reference
PlantSuper Class Reference
Specific tree class can be declared as: class TreeHard + _ + p3d filename (without extension)
Private Member Functions
override bool IsBush ()
override bool IsBush ()
override bool IsTree ()
override bool IsTree ()
override void OnTreeCutDown (EntityAI cutting_entity)
override void OnTreeCutDown (EntityAI cutting_entity)
override void OnTreeCutDown (EntityAI cutting_entity)
override void OnTreeCutDown (EntityAI cutting_entity)
Detailed Description
Specific tree class can be declared as: class TreeHard + _ + p3d filename (without extension)
For specific tree declaration see description of TreeHard.
//exapmle for tree DZ\plants2\tree\t_acer2s.p3d
class TreeHard_t_acer2s: TreeHard
{
};
For specific tree declaration see description of TreeHard default values for hard bushes
Definition at line 17 of file plant.c.
Member Function Documentation
IsBush() [1/2]
override bool PlantSuper::IsBush () inline private
Definition at line 164 of file plant.c.
    {
        return true;
    }
IsBush() [2/2]
override bool PlantSuper::IsBush () inline private
Definition at line 225 of file plant.c.
    {
        return true;
    }
IsTree() [1/2]
override bool PlantSuper::IsTree () inline private
Definition at line 27 of file plant.c.
    {
        return true;
    }
IsTree() [2/2]
override bool PlantSuper::IsTree () inline private
Definition at line 95 of file plant.c.
    {
        return true;
    }
OnTreeCutDown() [1/4]
override void PlantSuper::OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 19 of file plant.c.
    {
        //int tree_hard = 14;
        //ToolBase cut_tree_tool = ToolBase.Cast( cutting_tool );
        GetGame().RPCSingleParam( cutting_entity, PlantType.TREE_HARD, NULL, true );
    }
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [2/4]
override void PlantSuper::OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 89 of file plant.c.
    {
        //ToolBase cut_tree_tool = ToolBase.Cast( cutting_tool );
        GetGame().RPCSingleParam( cutting_entity, PlantType.TREE_SOFT, NULL, true );
    }
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [3/4]
override void PlantSuper::OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 158 of file plant.c.
    {
        //ToolBase cut_tree_tool = ToolBase.Cast( cutting_tool );
        GetGame().RPCSingleParam( cutting_entity, PlantType.BUSH_HARD, NULL, true );
    }
References GetGame(), and CGame::RPCSingleParam().
OnTreeCutDown() [4/4]
override void PlantSuper::OnTreeCutDown (EntityAI cutting_entity) inline private
Definition at line 219 of file plant.c.
    {
        //ToolBase cut_tree_tool = ToolBase.Cast( cutting_tool );
        GetGame().RPCSingleParam( cutting_entity, PlantType.BUSH_SOFT, NULL, true );
    }
References GetGame(), and CGame::RPCSingleParam().