DayzKode: SEffectManager Class Reference
SEffectManager Class Reference
Manager class for managing Effect (EffectParticle, EffectSound)
Static Private Member Functions
Generic playback
Methods for playing Effect
Note
Since 1.15, these should work on EffectSound as well
static int PlayInWorld (notnull Effect eff, vector pos)
Play an Effect.
static int PlayOnObject (notnull Effect eff, Object obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_rotation_relative_to_world=false)
Play an Effect.
static void Stop (int effect_id)
Stops the Effect.
Create/Play sound
Methods for playing/creating sound
static EffectSound CreateSound (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false, bool enviroment=false)
Create an EffectSound.
static EffectSound PlaySound (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
static EffectSound PlaySoundParams (notnull SoundParams params, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
static EffectSound PlaySoundCachedParams (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound, using or creating cached SoundParams.
static EffectSound PlaySoundEnviroment (string sound_set, vector position, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound, updating environment variables.
static EffectSound PlaySoundOnObject (string sound_set, Object parent_object, float play_fade_in=0, float stop_fade_out=0, bool loop=false)
Create and play an EffectSound.
Generic API
General methods used for SEffectManager
static void DestroyEffect (Effect effect)
Unregisters, stops and frees the Effect.
static bool IsEffectExist (int effect_id)
Checks whether an Effect ID is registered in SEffectManager.
static Effect GetEffectByID (int effect_id)
Gets the Effect with the given registered Effect ID.
static int EffectRegister (Effect effect)
Registers Effect in SEffectManager.
static void EffectUnregister (int id)
Unregisters Effect in SEffectManager.
static void EffectUnregisterEx (Effect effect)
Unregisters Effect in SEffectManager.
static protected int GetFreeEffectID ()
Helper function for EffectRegister to decide an Effect ID.
Sound helpers
Sound specific helper methods
static bool DestroySound (EffectSound sound_effect)
Legacy, backwards compatibility.
static SoundParams GetCachedSoundParam (string soundset)
Get or create a cached SoundParams object.
Events
Various events that can be overriden for custom behaviour
static void Event_OnSoundWaveEnded (EffectSound effect_sound)
Event called from EffectSound.Event_OnSoundWaveEnded.
static void Event_OnFrameUpdate (float time_delta)
Event called on frame.
Lifetime
Creation and cleanup
static void Init ()
Initialize the containers.
static void Cleanup ()
Cleanup method to properly clean up the static data.
Static Private Attributes
static ref ScriptInvoker Event_OnFrameUpdate
Static invoker for the SEffectManager.Event_OnFrameUpdate called form MissionGameplay.OnUpdate.
static const int INVALID_ID = 0
As the counter starts at 1, Effect ID can never be 0.
static protected ref map< int, ref Effect > m_EffectsMap
Static map of all registered effects <id, Effect>
static protected ref array< int > m_FreeEffectIDs
Static array of IDs that were previously used, but freed up by unregistering.
static protected int m_HighestFreeEffectID = 1
Counter for quickly getting the next ID if FreeEffectIDs array is empty.
static protected bool m_IsCleanup
Bool to check whether Cleanup is happening, which means that the maps should no longer be accessed.
static protected bool m_IsInitialized
Bool to check whether Init was called.
static protected ref map< string, ref SoundParams > m_ParamsMap
Static map of cached sound params, to prevent having to recreate them.
Detailed Description
Manager class for managing Effect (EffectParticle, EffectSound)
Warning
Keeps a ref to any Effect registered (Created/Played), make sure to perform the necessary cleanup
Definition at line 5 of file effectmanager.c.
Member Function Documentation
Cleanup()
static void SEffectManager::Cleanup () inline static private
Cleanup method to properly clean up the static data.
Note
Will be called when MissionBase is destroyed
Definition at line 481 of file effectmanager.c.
    {
        // Nothing to clean
        if (!m_IsInitialized)
            return;
        m_IsCleanup = true;
        // There should not be anything in here on server
        if (GetGame() && GetGame().IsDedicatedServer())
        {
            if (m_ParamsMap.Count() > 0)
                ErrorEx(string.Format("SEffectManager containing SoundParams on server."), ErrorExSeverity.WARNING);
            if (m_EffectsMap.Count() > 0)
                ErrorEx(string.Format("SEffectManager containing Effect on server."), ErrorExSeverity.WARNING);
        }
        // These are intentionally cached, just clear them
        m_ParamsMap.Clear();
        // These might not be intentionally still here, so log how many there are
        #ifdef DEVELOPER
        Print("--- SEffectManager Cleanup dump - Begin ------------------------");
        Print(string.Format("Effect count: %1", m_EffectsMap.Count()));
        #endif
        // Best to call the unregister event before clearing the map
        // In case some ref is still being held elsewhere and will still be kept alive
        foreach (int id, Effect eff : m_EffectsMap)
        {
            eff.Event_OnUnregistered();
            #ifdef SFXM_DUMP
            Print(string.Format( "%1 :: %2 :: %3", eff, typename.EnumToString(EffectType, eff.GetEffectType()), eff.GetDebugName() ));
            #endif
        }
        #ifdef DEVELOPER
        Print("--- SEffectManager Cleanup dump - End --------------------------");
        #endif
        // Now we can clear it
        m_EffectsMap.Clear();
        // Reset the state
        m_HighestFreeEffectID = 1;
        Event_OnFrameUpdate.Clear();
        m_IsCleanup = false;
    }
References ScriptInvoker::Clear(), Effect(), ErrorEx, Event_OnFrameUpdate, GetGame(), m_EffectsMap, m_HighestFreeEffectID, m_IsCleanup, m_IsInitialized, m_ParamsMap, and Print().
Referenced by MissionBaseWorld::MissionBase(), and CGame::~CGame().
CreateSound()
static EffectSound SEffectManager::CreateSound (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false, bool enviroment = false) inline static private
Create an EffectSound.
Warning
Read PlayInWorld warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
enviroment bool Whether to set environment variables (Optional)
Returns
EffectSound The created EffectSound
Definition at line 140 of file effectmanager.c.
    {
        EffectSound effect_sound = new EffectSound();
        effect_sound.SetSoundSet(sound_set);
        effect_sound.SetPosition(position);
        effect_sound.SetSoundFadeIn(play_fade_in);
        effect_sound.SetSoundFadeOut(stop_fade_out);
        effect_sound.SetSoundLoop(loop);
        effect_sound.SetEnviromentVariables(enviroment);
        EffectRegister( effect_sound );
        return effect_sound;
    }
References EffectRegister(), EffectSound::SetEnviromentVariables(), EffectSound::SetSoundFadeIn(), EffectSound::SetSoundFadeOut(), EffectSound::SetSoundLoop(), and EffectSound::SetSoundSet().
Referenced by HandleEngineSound(), FlashbangEffect::PlaySound(), PlaySound(), PlaySoundCachedParams(), PlaySoundEnviroment(), PlaySoundOnObject(), and PlaySoundParams().
DestroyEffect()
static void SEffectManager::DestroyEffect (Effect effect) inline static private
Unregisters, stops and frees the Effect.
Parameters
effect_sound EffectSound The EffectSound to free
Definition at line 267 of file effectmanager.c.
    {
        if (effect)
        {
            // Functionality already happens in dtor of Effect to be safe
            delete effect;
        }
    }
Referenced by CleanupEffects(), CleanupSound(), Destroy(), ActionBuildShelter::DestroyActionLoopSound(), DestroySound(), Roadflare::EEDelete(), ManBase::EEDelete(), House::EEDelete(), OnRingingStartClient(), OnRingingStopClient(), InventoryItem::OnRPC(), OnVariablesSynchronized(), ItemBase::OnWorkStop(), RemoveParticle(), ManBase::SetDecayEffects(), KitchenTimer::TurnOff(), ItemBase::~BarbedWire(), ~Bottle_Base(), ~ClockBase(), DayZIntroSceneXbox::~DayZIntroSceneXbox(), ItemBase::~Defibrillator(), DestructionEffectBase::~DestructionEffectBase(), FireworksLauncher::~FireworksLauncher(), FireworksLauncherClientEvent::~FireworksLauncherClientEvent(), FlashbangEffect::~FlashbangEffect(), Inventory_Base::~HescoBox(), InventoryItem::~ItemBase(), ItemBase::~KitBase(), ~LandMineTrap(), ~LargeTent(), Clothing::~LargeTentBackPack(), ManBase::~PlayerBase(), ItemBase::~PowerGenerator(), UIScriptedMenu::~ScriptConsole(), ItemBase::~Spotlight(), ItemBase::~TentBase(), ~TrapBase(), and ItemBase::~TrapSpawnBase().
DestroySound()
static bool SEffectManager::DestroySound (EffectSound sound_effect) inline static private
Legacy, backwards compatibility.
Parameters
sound_effect EffectSound The EffectSound to free
Returns
bool A bool which is always true
Definition at line 401 of file effectmanager.c.
    {
        DestroyEffect(sound_effect);
        return true;
    }
References DestroyEffect().
Referenced by CleanSoundEffects(), CleanUpOnClosedClient(), and Land_Underground_Stairs_Exit::CleanUpOnClosedClient().
EffectRegister()
static int SEffectManager::EffectRegister (Effect effect) inline static private
Registers Effect in SEffectManager.
Note
Already handled in SEffectManager Create/Play methods
This will make SEffectManager hold a strong ref for the Effect
Parameters
effect Effect The Effect to register
Returns
int The Effect ID
Definition at line 309 of file effectmanager.c.
    {
        if (effect.IsRegistered())
        {
            ErrorEx(string.Format("Attempted to register Effect '%1' which was already registered.", effect.GetDebugName()), ErrorExSeverity.INFO);
            return effect.GetID();
        }
        int id;
        if (!m_IsCleanup)
        {
            id = GetFreeEffectID();
            m_EffectsMap.Insert(id, effect);
            effect.Event_OnRegistered(id);
        }
        else
            ErrorEx("Attempted to register Effect while SEffectManager is cleaning up, request ignored.", ErrorExSeverity.WARNING);
        return id;
    }
References ErrorEx, GetFreeEffectID(), m_EffectsMap, and m_IsCleanup.
Referenced by CreateSound(), PlayInWorld(), and PlayOnObject().
EffectUnregister()
static void SEffectManager::EffectUnregister (int id) inline static private
Unregisters Effect in SEffectManager.
Note
Will automatically occur on stop when the Effect is AutoDestroy
ID can be gotten from the Effect by calling Effect.GetID
Generic Play methods will also return the ID
Parameters
id int The ID of the Effect to unregister
Definition at line 338 of file effectmanager.c.
    {
        if (m_IsCleanup)
            return; // No error needed, since it will have been unregistered anyways after cleanup is finished
        Effect effect;
        if ( m_EffectsMap.Find(id, effect) )
        {
            effect.Event_OnUnregistered();
            m_EffectsMap.Remove(id);
        }
        if ( m_FreeEffectIDs.Find(id) == -1 )
        {
            m_FreeEffectIDs.Insert(id);
        }
    }
References Effect(), m_EffectsMap, m_FreeEffectIDs, and m_IsCleanup.
Referenced by EffectUnregisterEx(), and ~Effect().
EffectUnregisterEx()
static void SEffectManager::EffectUnregisterEx (Effect effect) inline static private
Unregisters Effect in SEffectManager.
Parameters
effect Effect The Effect to unregister
Definition at line 360 of file effectmanager.c.
    {
        EffectUnregister(effect.GetID());
    }
References EffectUnregister().
Event_OnFrameUpdate()
static void SEffectManager::Event_OnFrameUpdate (float time_delta) inline static private
Event called on frame.
Note
Called from MissionGameplay.OnUpdate
Effects register themselves by Effect.SetEnableEventFrame(true)
EffectSound is automatically registered
Parameters
time_delta float Time passed since the previous frame
Definition at line 449 of file effectmanager.c.
    {
        Event_OnFrameUpdate.Invoke(time_delta);
    }
References Event_OnFrameUpdate, and ScriptInvoker::Invoke().
Event_OnSoundWaveEnded()
static void SEffectManager::Event_OnSoundWaveEnded (EffectSound effect_sound) inline static private
Event called from EffectSound.Event_OnSoundWaveEnded.
Note
Every registered sound is registered to call this
Parameters
effect_sound EffectSound The EffectSound calling the event
Definition at line 437 of file effectmanager.c.
    {
    }
Referenced by EffectSound::Event_OnRegistered(), and EffectSound::Event_OnUnregistered().
GetCachedSoundParam()
static SoundParams SEffectManager::GetCachedSoundParam (string soundset) inline static private
Get or create a cached SoundParams object.
Parameters
soundset string The sound set name of the sound
Returns
SoundParams The cached SoundParams for the given soundset
Definition at line 412 of file effectmanager.c.
    {
        SoundParams params;
        if (!m_ParamsMap.Find(soundset, params))
        {
            params = new SoundParams(soundset);
            m_ParamsMap.Insert(soundset, params);
        }
        return params;
    }
References m_ParamsMap.
Referenced by PlaySoundCachedParams().
GetEffectByID()
static Effect SEffectManager::GetEffectByID (int effect_id) inline static private
Gets the Effect with the given registered Effect ID.
Parameters
effect_id int The Effect ID
Returns
Effect The Effect registered to the ID or null
Definition at line 294 of file effectmanager.c.
    {
        if (!m_IsCleanup)
            return m_EffectsMap[effect_id];
        else
            return null;
    }
References m_EffectsMap, and m_IsCleanup.
GetFreeEffectID()
static protected int SEffectManager::GetFreeEffectID () inline static private
Helper function for EffectRegister to decide an Effect ID.
Returns
int A currently unused Effect ID
Definition at line 369 of file effectmanager.c.
    {
        int return_id;
        if (m_FreeEffectIDs.Count() > 0)
        {
            return_id = m_FreeEffectIDs.Get(0);
            m_FreeEffectIDs.Remove(0);
        }
        else
        {
            return_id = m_HighestFreeEffectID;
            ++m_HighestFreeEffectID;
        }
        return return_id;
    }
References m_FreeEffectIDs, and m_HighestFreeEffectID.
Referenced by EffectRegister().
Init()
static void SEffectManager::Init () inline static private
Initialize the containers.
Note
This is done this way, to have these not exist on server
Definition at line 467 of file effectmanager.c.
    {
        m_EffectsMap = new map<int, ref Effect>;
        m_FreeEffectIDs = new array<int>;
        m_ParamsMap = new map<string, ref SoundParams>;
        Event_OnFrameUpdate = new ScriptInvoker();
        m_IsInitialized = true;
    }
References Event_OnFrameUpdate, m_EffectsMap, m_FreeEffectIDs, m_IsInitialized, and m_ParamsMap.
Referenced by CGame::CGame().
IsEffectExist()
static bool SEffectManager::IsEffectExist (int effect_id) inline static private
Checks whether an Effect ID is registered in SEffectManager.
Parameters
effect_id int The Effect ID to check
Returns
bool Whether there is an Effect registered for this ID
Definition at line 281 of file effectmanager.c.
    {
        if (!m_IsCleanup)
            return m_EffectsMap[effect_id] != null;
        else
            return false;
    }
References m_EffectsMap, and m_IsCleanup.
Referenced by CreateCarDestroyedEffect(), EOnPostSimulate(), and ManBase::SetDecayEffects().
PlayInWorld()
static int SEffectManager::PlayInWorld (notnull Effect eff, vector pos) inline static private
Play an Effect.
Warning
As the Effect is automatically registered, it will not be freed automatically (because of the ref) Unless 'SetAutodestroy(true)' is called on the created 'Effect', which will clean it up when the sound stop Alternatively, SEffectManager.DestroyEffect can be called manually, which will also unregister and cleanup
Parameters
eff Effect The Effect to play
pos vector The position to play the Effect
Returns
int The registered ID of the Effect
Definition at line 43 of file effectmanager.c.
    {
        // Stop the effect first, just in case
        eff.Stop();
        int id = EffectRegister(eff);
        eff.SetPosition( pos );
        eff.Start();
        return id;
    }
References EffectRegister().
Referenced by Hit_MeatBones::BloodSplatGround(), CreateParticle(), EvaluateImpactEffect(), ManBase::OnParticleEvent(), AmmoEffects::PlayAmmoEffect(), BleedingSourcesManagerBase::SetDiag(), DayZIntroSceneXbox::SetupParticles(), and Explosion::SpawnEffect().
PlayOnObject()
static int SEffectManager::PlayOnObject (notnull Effect eff, Object obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_rotation_relative_to_world = false) inline static private
Play an Effect.
Warning
Read PlayInWorld warning
Parameters
eff Effect The Effect to play
obj Object The parent of the Effect
local_pos vector The local position to play the Effect in relation to the parent (Optional)
local_ori vector The local orientation to play the Effect in relation to the parent (Optional)
force_rotation_relative_to_world bool Whether to force the orientation to stay in WS (Optional)
Returns
int The registered ID of the Effect
Definition at line 66 of file effectmanager.c.
    {
        // Stop the effect first, just in case
        eff.Stop();
        int id = EffectRegister(eff);
        if (!obj)
        {
            ErrorEx("Parent object is null.", ErrorExSeverity.WARNING);
            eff.SetPosition(local_pos);
        }
        else
        {
            eff.SetPosition(obj.GetPosition());
        }
        eff.SetParent(obj);
        eff.SetLocalPosition(local_pos);
        eff.SetAttachedLocalOri(local_ori);
        if (force_rotation_relative_to_world)
        {
            EffectParticle eff_particle = EffectParticle.Cast(eff);
            if (eff_particle)
            {
                eff_particle.ForceParticleRotationRelativeToWorld(force_rotation_relative_to_world);
            }
        }
        eff.Start();
        return id;
    }
References EffectRegister(), ErrorEx, and EffectParticle::ForceParticleRotationRelativeToWorld().
Referenced by CreateCarDestroyedEffect(), EOnPostSimulate(), ManBase::SetDecayEffects(), and ItemBase::StartLoopSound().
PlaySound()
static EffectSound SEffectManager::PlaySound (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
Definition at line 165 of file effectmanager.c.
    {
        EffectSound effect_sound = CreateSound(sound_set, position, play_fade_in, stop_fade_out, loop, false);
        effect_sound.SoundPlay();
        return effect_sound;
    }
References CreateSound(), and EffectSound::SoundPlay().
Referenced by DelayedMidAirDetonation(), House::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), HandleDoorsSound(), HandleEngineSound(), CarScript::OnAnimationPhaseStarted(), Weapon::OnFireModeChange(), InventoryItem::OnRPC(), OnRPC(), OnSteppedOn(), ActionBuildShelter::PlayActionFinishSound(), ActionBuildShelter::PlayActionLoopSound(), ActionBuildShelter::PlayActionStartSound(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), PlayDeployLoopSound(), InventoryItem::PlayDeploySound(), PlayDisarmingLoopSound(), InventoryItem::PlayPlaceSound(), PlayRepackingLoopSound(), Clothing::PlayRepackingLoopSound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), TrapBase::PlaySoundOpen(), Barrel_ColorBase::SoundBarrelClosePlay(), FireplaceBase::SoundBarrelClosePlay(), Barrel_ColorBase::SoundBarrelOpenPlay(), FireplaceBase::SoundBarrelOpenPlay(), ItemBase::SoundTentClosePlay(), ItemBase::SoundTentCloseWindowPlay(), ItemBase::SoundTentOpenPlay(), ItemBase::SoundTentOpenWindowPlay(), and StartActivate().
PlaySoundCachedParams()
static EffectSound SEffectManager::PlaySoundCachedParams (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound, using or creating cached SoundParams.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
Definition at line 203 of file effectmanager.c.
    {
        SoundParams params = GetCachedSoundParam(sound_set);
        EffectSound effect_sound = CreateSound(params.GetName(), position, play_fade_in, stop_fade_out, loop, false);
        effect_sound.SoundPlayEx(params);
        return effect_sound;
    }
References CreateSound(), GetCachedSoundParam(), SoundParams::GetName(), and EffectSound::SoundPlayEx().
Referenced by PlaySoundEx().
PlaySoundEnviroment()
static EffectSound SEffectManager::PlaySoundEnviroment (string sound_set, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound, updating environment variables.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
Definition at line 224 of file effectmanager.c.
    {
        EffectSound effect_sound = CreateSound(sound_set, position, play_fade_in, stop_fade_out, loop, true);
        effect_sound.SoundPlay();
        return effect_sound;
    }
References CreateSound(), and EffectSound::SoundPlay().
Referenced by UIScriptedMenu::OnClick(), and PlaySoundSetAtMemoryPoint().
PlaySoundOnObject()
static EffectSound SEffectManager::PlaySoundOnObject (string sound_set, Object parent_object, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
sound_set string The sound set name of the sound
parent_object Object The parent Object for the sound to follow
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
Definition at line 243 of file effectmanager.c.
    {
        EffectSound effect_sound = CreateSound(sound_set, parent_object.GetPosition(), play_fade_in, stop_fade_out, loop);
        effect_sound.SetParent( parent_object );
        effect_sound.SetLocalPosition( vector.Zero );
        effect_sound.SoundPlay();
        return effect_sound;
    }
References CreateSound(), EffectSound::SetParent(), EffectSound::SoundPlay(), and vector::Zero.
Referenced by ItemBase::DischargeClient(), ItemBase::OnIsCharged(), ItemBase::OnWorkStart(), PlayEmptyingLoopSound(), PlayPouringLoopSound(), PlaySound(), PlaySoundSet(), and StopEmptyingLoopSound().
PlaySoundParams()
static EffectSound SEffectManager::PlaySoundParams (notnull SoundParams params, vector position, float play_fade_in = 0, float stop_fade_out = 0, bool loop = false) inline static private
Create and play an EffectSound.
Warning
Calls CreateSound, read CreateSound warning
Parameters
params SoundParams Params to create the sound with
position vector The position to play the sound
play_fade_in float The fade in duration of the sound (Optional)
stop_fade_out float The fade out duration of the sound (Optional)
loop bool Whether the sound should loop (Optional)
Returns
EffectSound The created EffectSound
Definition at line 184 of file effectmanager.c.
    {
        EffectSound effect_sound = CreateSound(params.GetName(), position, play_fade_in, stop_fade_out, loop, false);
        effect_sound.SoundPlayEx(params);
        return effect_sound;
    }
References CreateSound(), and EffectSound::SoundPlayEx().
Stop()
static void SEffectManager::Stop (int effect_id) inline static private
Stops the Effect.
Parameters
effect_id int The ID of the Effect to Stop
Definition at line 106 of file effectmanager.c.
    {
        Effect eff = m_EffectsMap.Get(effect_id);
        if (eff)
        {
            eff.Stop();
        }
        else
        {
            ErrorEx(string.Format("Failed to stop Effect with ID %1. The ID is not registered in m_EffectsMap!", effect_id));
        }
    }
References Effect(), ErrorEx, and m_EffectsMap.
Referenced by EOnPostSimulate().
Member Data Documentation
Event_OnFrameUpdate
ref ScriptInvoker SEffectManager::Event_OnFrameUpdate static private
Static invoker for the SEffectManager.Event_OnFrameUpdate called form MissionGameplay.OnUpdate.
Definition at line 24 of file effectmanager.c.
Referenced by Cleanup(), Event_OnFrameUpdate(), Init(), MissionBase::OnUpdate(), and SetEnableEventFrame().
INVALID_ID
const int SEffectManager::INVALID_ID = 0 static private
As the counter starts at 1, Effect ID can never be 0.
Definition at line 14 of file effectmanager.c.
Referenced by Event_OnUnregistered().
m_EffectsMap
protected ref map<int, ref Effect> SEffectManager::m_EffectsMap static private
Static map of all registered effects <id, Effect>
Definition at line 8 of file effectmanager.c.
Referenced by Cleanup(), EffectRegister(), EffectUnregister(), GetEffectByID(), Init(), IsEffectExist(), and Stop().
m_FreeEffectIDs
protected ref array<int> SEffectManager::m_FreeEffectIDs static private
Static array of IDs that were previously used, but freed up by unregistering.
Definition at line 10 of file effectmanager.c.
Referenced by EffectUnregister(), GetFreeEffectID(), and Init().
m_HighestFreeEffectID
protected int SEffectManager::m_HighestFreeEffectID = 1 static private
Counter for quickly getting the next ID if FreeEffectIDs array is empty.
Definition at line 12 of file effectmanager.c.
Referenced by Cleanup(), and GetFreeEffectID().
m_IsCleanup
protected bool SEffectManager::m_IsCleanup static private
Bool to check whether Cleanup is happening, which means that the maps should no longer be accessed.
Definition at line 16 of file effectmanager.c.
Referenced by Cleanup(), EffectRegister(), EffectUnregister(), GetEffectByID(), and IsEffectExist().
m_IsInitialized
protected bool SEffectManager::m_IsInitialized static private
Bool to check whether Init was called.
Definition at line 18 of file effectmanager.c.
Referenced by Cleanup(), and Init().
m_ParamsMap
protected ref map<string, ref SoundParams> SEffectManager::m_ParamsMap static private
Static map of cached sound params, to prevent having to recreate them.
Definition at line 21 of file effectmanager.c.
Referenced by Cleanup(), GetCachedSoundParam(), and Init().