DayzKode: ItemManager Class Reference
ItemManager Class Reference
Private Member Functions
void CalculateTooltipSlotPosition (int x=0, int y=0)
void ClearDefaultHeaderOpenStates ()
void ClearDefaultOpenStates ()
void DeserializeDefaultHeaderOpenStates ()
void DeserializeDefaultOpenStates ()
bool EvaluateContainerDragabilityDefault (EntityAI entity)
Widget GetCenterDropzone ()
bool GetDefaultHeaderOpenState (string type)
bool GetDefaultOpenState (string type)
bool GetDefaultOpenStateHands ()
Icon GetDraggedIcon ()
EntityAI GetDraggedItem ()
HandsPreview GetHandsPreview ()
EntityAI GetHoveredItem ()
Widget GetLeftDropzone ()
Widget GetRightDropzone ()
Container GetSelectedContainer ()
SlotsIcon GetSelectedIcon ()
EntityAI GetSelectedItem ()
Widget GetSelectedWidget ()
void HideDropzones ()
void HideTooltip ()
void HideTooltipSlot ()
bool IsDragging ()
bool IsMicromanagmentMode ()
void ItemManager (Widget root)
void PrepareSlotsTooltip (string name, string desc, int x=0, int y=0)
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
void PrepareTooltip (EntityAI item, int x=0, int y=0)
void SerializeDefaultHeaderOpenStates ()
void SerializeDefaultOpenStates ()
void SetDefaultHeaderOpenState (string type, bool is_opened)
void SetDefaultOpenState (string type, bool is_opened)
void SetDefaultOpenStateHands (bool is_opened)
void SetDraggedIcon (Icon dragged_icon)
void SetDraggedItem (EntityAI dragged_item)
void SetHandsPreview (HandsPreview hansd_preview)
void SetIconTemperature (EntityAI item, Widget item_w)
void SetIsDragging (bool is_dragging)
void SetItemMicromanagmentMode (bool item_micromanagment_mode)
void SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon)
void SetTemperature (EntityAI item, Widget item_w)
void SetTooltipWidget (Widget w)
void SetWidgetDraggable (Widget w, bool draggable)
void ShowSourceDropzone (EntityAI item)
void ShowTooltip ()
void ShowTooltipSlot ()
void UpdateTooltipSlotPosition ()
Static Private Member Functions
static int ColorFromFloat (float fraction)
static int GetCombinationFlags (EntityAI entity1, EntityAI entity2)
static ItemManager GetInstance ()
static int GetItemHealthColor (EntityAI item, string zone="")
static int GetItemHealthColor (int pHealthLevel)
static int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
Private Attributes
protected Widget m_CenterDropzone
protected ref map< string, bool > m_DefautHeaderOpenStates
protected ref map< string, bool > m_DefautOpenStates
protected Icon m_DraggedIcon
protected EntityAI m_DraggedItem
protected int m_HandsDefaultOpenState
protected HandsPreview m_HandsPreview
protected EntityAI m_HoveredItem
protected bool m_IsDragging
protected bool m_ItemMicromanagmentMode
protected ItemPreviewWidget m_ItemPreviewWidget
protected Widget m_LeftDropzone
protected Widget m_RightDropzone
protected Widget m_RootWidget
protected Container m_SelectedContainer
protected SlotsIcon m_SelectedIcon
protected EntityAI m_SelectedItem
protected Widget m_SelectedWidget
protected bool m_SlotInfoShown
protected ref Widget m_TooltipCategoryWidget
protected int m_TooltipPosX
protected int m_TooltipPosY
protected ref Timer m_TooltipSlotTimer
protected ref Widget m_TooltipSlotWidget
protected Widget m_TooltipSourceWidget
protected ref Timer m_ToolTipTimer
protected ref Widget m_TooltipWidget
protected const float TOOLTIP_DELAY = 0.25
Static Private Attributes
private static ref ItemManager m_Instance
Detailed Description
Definition at line 1 of file itemmanager.c.
Constructor & Destructor Documentation
ItemManager()
void ItemManager::ItemManager (Widget root) inline private
Definition at line 43 of file itemmanager.c.
    {
        m_Instance                  = this;
        m_RootWidget                = root;
        m_DefautOpenStates          = new map<string, bool>;
        m_DefautHeaderOpenStates    = new map<string, bool>;
        m_SlotInfoShown             = false;
        #ifdef PLATFORM_CONSOLE
            m_TooltipWidget         = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_xbox.layout", root );
            m_TooltipSlotWidget     = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_slot_xbox.layout", root );
        #else
            m_TooltipWidget         = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip.layout", root );
            m_TooltipSlotWidget     = GetGame().GetWorkspace().CreateWidgets("gui/layouts/inventory_new/day_z_inventory_new_tooltip_slot.layout", root );
        #endif
        m_TooltipWidget.Show( false );
        m_TooltipSlotWidget.Show( false );
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_DefautHeaderOpenStates, m_DefautOpenStates, m_Instance, m_RootWidget, m_SlotInfoShown, m_TooltipSlotWidget, and m_TooltipWidget.
Member Function Documentation
CalculateTooltipSlotPosition()
void ItemManager::CalculateTooltipSlotPosition (int x = 0, int y = 0) inline private
Definition at line 551 of file itemmanager.c.
    {
        int screen_w, screen_h;
        float w, h;
        GetScreenSize(screen_w, screen_h);
        //m_TooltipSlotWidget.GetScreenSize(w,h);
        m_TooltipSlotWidget.GetSize(w,h);
        int slot_normal_w = SlotsIcon.GetNormalWidth();
        int slot_normal_h = SlotsIcon.GetNormalHeight();
        //minimal edge distance adjustments..
        screen_w -= 10;
        screen_h -= 10;
#ifndef PLATFORM_CONSOLE
        x += 5;
        y += slot_normal_h + 5;
#else
        x += 5;
        y += 15;
#endif
        Widget scrollerWidget = m_TooltipSourceWidget.GetParent();
        while (scrollerWidget)
        {
            if (ScrollWidget.Cast(scrollerWidget))
            {
                break;
            }
            else
            {
                scrollerWidget = scrollerWidget.GetParent();
            }
        }
        int rightEdge = x + w;
        if (rightEdge > screen_w)
        {
            x = screen_w - w;
        }
        int bottomEdge = y + h;
        if (scrollerWidget)
        {
            float scrollerX, scrollerY, scrollerSizeX, scrollerSizeY;
            scrollerWidget.GetScreenPos(scrollerX,scrollerY);
            scrollerWidget.GetScreenSize(scrollerSizeX,scrollerSizeY);
            int scroller_bottom = scrollerY + scrollerSizeY;
            if (bottomEdge > scroller_bottom)
            {
                y = scroller_bottom - slot_normal_h;
                bottomEdge = y + h;
            }
        }
        /*else
        {
            ErrorEx("No scroller widget! | m_TooltipSourceWidget: " + m_TooltipSourceWidget);
        }*/
        if (bottomEdge > screen_h) //should mostly never proc now
        {
            y = screen_h - h;
        }
        m_TooltipPosX = x;
        m_TooltipPosY = y;
    }
References SlotsIcon::GetNormalHeight(), SlotsIcon::GetNormalWidth(), GetScreenSize(), m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, m_TooltipSourceWidget, x, and y.
Referenced by UpdateTooltipSlotPosition().
ClearDefaultHeaderOpenStates()
void ItemManager::ClearDefaultHeaderOpenStates () inline private
Definition at line 115 of file itemmanager.c.
    {
        m_DefautHeaderOpenStates.Clear();
    }
References m_DefautHeaderOpenStates.
Referenced by DeserializeDefaultHeaderOpenStates().
ClearDefaultOpenStates()
void ItemManager::ClearDefaultOpenStates () inline private
Definition at line 110 of file itemmanager.c.
    {
        m_DefautOpenStates.Clear();
    }
References m_DefautOpenStates.
Referenced by DeserializeDefaultOpenStates().
ColorFromFloat()
static int ItemManager::ColorFromFloat (float fraction) inline static private
Definition at line 402 of file itemmanager.c.
    {
        if( fraction > 1 || fraction < 0 )
            return 0x00FFFFFF;
        else if( fraction > 0.80 )
            return Colors.COLOR_PRISTINE;
        else if( fraction > 0.6 )
            return Colors.COLOR_WORN;
        else if( fraction > 0.4 )
            return Colors.COLOR_DAMAGED;
        else if( fraction > 0.2 )
            return Colors.COLOR_BADLY_DAMAGED;
        else
            return Colors.COLOR_RUINED;
    }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, and Colors::COLOR_WORN.
DeserializeDefaultHeaderOpenStates()
void ItemManager::DeserializeDefaultHeaderOpenStates () inline private
Definition at line 163 of file itemmanager.c.
    {
        ClearDefaultHeaderOpenStates();
        TStringArray serialized_types = new TStringArray;
        GetGame().GetProfileStringList( "defaultHeaderOpenStates", serialized_types );
        for( int i = 0; i < serialized_types.Count(); i++ )
        {
            TStringArray strs = new TStringArray;
            serialized_types.Get( i ).Split( ",", strs );
            bool is_opened = strs.Get( 1 ).ToInt();
            SetDefaultHeaderOpenState( strs.Get( 0 ), is_opened );
        }
    }
References ClearDefaultHeaderOpenStates(), GetGame(), CGame::GetProfileStringList(), and SetDefaultHeaderOpenState().
Referenced by Deserialize().
DeserializeDefaultOpenStates()
void ItemManager::DeserializeDefaultOpenStates () inline private
Definition at line 196 of file itemmanager.c.
    {
        ClearDefaultOpenStates();
        TStringArray serialized_types = new TStringArray;
        GetGame().GetProfileStringList( "defaultOpenStates", serialized_types );
        for( int i = 0; i < serialized_types.Count(); i++ )
        {
            TStringArray strs = new TStringArray;
            serialized_types.Get( i ).Split( ",", strs );
            bool is_opened = strs.Get( 1 ).ToInt();
            SetDefaultOpenState( strs.Get( 0 ), is_opened );
        }
    }
References ClearDefaultOpenStates(), GetGame(), CGame::GetProfileStringList(), and SetDefaultOpenState().
Referenced by Deserialize().
EvaluateContainerDragabilityDefault()
bool ItemManager::EvaluateContainerDragabilityDefault (EntityAI entity) inline private
Definition at line 630 of file itemmanager.c.
    {
        if ( !ItemBase.Cast( entity ) )
            return false;
        bool draggable;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        draggable = !player.GetInventory().HasInventoryReservation( entity, null ) && !player.IsItemsToDelete();
        draggable = draggable && entity.CanPutIntoHands( GetGame().GetPlayer() );
        draggable = draggable && entity.GetInventory().CanRemoveEntity();
        return draggable;
    }
References GetGame(), and GetPlayer().
Referenced by VicinitySlotsContainer::MouseButtonDown(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
GetCenterDropzone()
Widget ItemManager::GetCenterDropzone () inline private
Definition at line 291 of file itemmanager.c.
    {
        if( !m_CenterDropzone )
            m_CenterDropzone = m_RootWidget.FindAnyWidget( "HandsPanel" ).FindAnyWidget( "DropzoneX" );
        return m_CenterDropzone;
    }
References m_CenterDropzone, and m_RootWidget.
Referenced by HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), Icon::DraggingOverSwap(), HideDropzones(), Icon::ShowActionMenuCombine(), and ShowSourceDropzone().
GetCombinationFlags()
static int ItemManager::GetCombinationFlags (EntityAI entity1, EntityAI entity2) inline static private
Definition at line 670 of file itemmanager.c.
    {
        int flags = 0;
        PlayerBase m_player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( !entity1 || !entity2 )
            return flags;
        if( entity1.IsInherited( ItemBase ) && entity2.IsInherited( ItemBase ) )
        {
            ItemBase ent1 = ItemBase.Cast( entity1 );
            if( ent1.CanBeCombined( ItemBase.Cast( entity2 ) ) ) flags = flags | InventoryCombinationFlags.COMBINE_QUANTITY2;
        }
        Weapon_Base wpn;
        Magazine mag;
        if( Class.CastTo(wpn,  entity1 ) && Class.CastTo(mag,  entity2 ) )
        {
        }
        else if( entity1.GetInventory().CanAddAttachment( entity2 ) )
        {
            if( !entity1.IsInherited( ZombieBase ) && !entity1.IsInherited( Car ) && !entity2.IsInherited( ZombieBase ) && !entity2.IsInherited( Car ) )
            {
                flags = flags | InventoryCombinationFlags.ADD_AS_ATTACHMENT;
            }
        }
        if( entity1.GetInventory().CanAddEntityInCargo( entity2, entity2.GetInventory().GetFlipCargo() ) ) flags = flags | InventoryCombinationFlags.ADD_AS_CARGO;
        if( entity1 == m_player.GetHumanInventory().GetEntityInHands() || entity2 == m_player.GetHumanInventory().GetEntityInHands())
        {
            ActionManagerClient amc;
            Class.CastTo(amc, m_player.GetActionManager());
            if( entity1 == m_player.GetHumanInventory().GetEntityInHands() )
            {
                if( amc.CanPerformActionFromInventory( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.PERFORM_ACTION;
                }
                else if( amc.CanSetActionFromInventory( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.SET_ACTION;
                }
            }
            else
            {
                if( amc.CanPerformActionFromInventory( ItemBase.Cast( entity2 ), ItemBase.Cast( entity1 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.PERFORM_ACTION;
                }
                else if( amc.CanSetActionFromInventory( ItemBase.Cast( entity2 ), ItemBase.Cast( entity1 ) ) )
                {
                    flags = flags | InventoryCombinationFlags.SET_ACTION;
                }
            }
        }
        if( GetRecipeCount( true, entity1, entity2 ) > 0 )
        {
            flags = flags | InventoryCombinationFlags.RECIPE_ANYWHERE;
        }
        return flags;
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, ItemBase::CanBeCombined(), ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanSetActionFromInventory(), Class::CastTo(), InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), GetPlayer(), GetRecipeCount(), m_player, InventoryCombinationFlags::PERFORM_ACTION, InventoryCombinationFlags::RECIPE_ANYWHERE, and InventoryCombinationFlags::SET_ACTION.
Referenced by Attachments::CanCombine(), Container::CanCombine(), PlayerContainer::CanCombine(), VicinitySlotsContainer::CanCombine(), Icon::Combine(), Icon::CombineItems(), and Icon::DraggingOverCombine().
GetDefaultHeaderOpenState()
bool ItemManager::GetDefaultHeaderOpenState (string type) inline private
Definition at line 224 of file itemmanager.c.
    {
        if( m_DefautHeaderOpenStates.Contains( type ) )
        {
            return m_DefautHeaderOpenStates.Get( type );
        }
        else
        {
            return true;
        }
    }
References m_DefautHeaderOpenStates.
Referenced by CollapsibleContainer::LoadDefaultState().
GetDefaultOpenState()
bool ItemManager::GetDefaultOpenState (string type) inline private
Definition at line 212 of file itemmanager.c.
    {
        if( m_DefautOpenStates.Contains( type ) )
        {
            return m_DefautOpenStates.Get( type );
        }
        else
        {
            return true;
        }
    }
References m_DefautOpenStates.
GetDefaultOpenStateHands()
bool ItemManager::GetDefaultOpenStateHands () inline private
Definition at line 138 of file itemmanager.c.
    {
        string value;
        GetGame().GetProfileString( "defaultOpenStateHands", value );
        m_HandsDefaultOpenState = value.ToInt();
        return m_HandsDefaultOpenState;
    }
References GetGame(), CGame::GetProfileString(), m_HandsDefaultOpenState, and string::ToInt().
GetDraggedIcon()
Icon ItemManager::GetDraggedIcon () inline private
Definition at line 318 of file itemmanager.c.
    {
        return m_DraggedIcon;
    }
References m_DraggedIcon.
Referenced by Icon::DropReceivedFromMain(), and Icon::Swap().
GetDraggedItem()
EntityAI ItemManager::GetDraggedItem () inline private
Definition at line 308 of file itemmanager.c.
    {
        return m_DraggedItem;
    }
References m_DraggedItem.
Referenced by ColorManager::GetItemColor(), InventoryGridController::OnItemDropReceived(), AttachmentCategoriesRow::RefreshSlot(), Attachments::UpdateInterval(), ClosableContainer::UpdateInterval(), and UpdateInterval().
GetHandsPreview()
HandsPreview ItemManager::GetHandsPreview () inline private
Definition at line 72 of file itemmanager.c.
    {
        return m_HandsPreview;
    }
References m_HandsPreview.
Referenced by Attachments::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
GetHoveredItem()
EntityAI ItemManager::GetHoveredItem () inline private
Definition at line 298 of file itemmanager.c.
    {
        return m_HoveredItem;
    }
References m_HoveredItem.
Referenced by UpdateInterval().
GetInstance()
static ItemManager ItemManager::GetInstance () inline static private
Definition at line 236 of file itemmanager.c.
    {
        return m_Instance;
    }
References m_Instance.
Referenced by SlotsIcon::Clear(), Container::Close(), ClosableContainer::Close(), VicinityContainer::CollapseButtonOnMouseButtonDown(), Attachments::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), Icon::Combine(), Icon::CreateWhiteBackground(), Deserialize(), Icon::DestroyWhiteBackground(), DisableMicromanagement(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), EnableMicromanagement(), ColorManager::GetItemColor(), HandsContainer::HandsContainer(), ScriptedWidgetEventHandler::HideOwnedSlotsTooltip(), ScriptedWidgetEventHandler::HideOwnedTooltip(), Icon::Icon(), SlotsIcon::Init(), Icon::InitLock(), CollapsibleContainer::LoadDefaultState(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), MoveFocusByArea(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), OnHide(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), HandsContainer::OnSelectButton(), OnShow(), MissionBase::OnUpdate(), Container::Open(), ClosableContainer::Open(), ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip(), ScriptedWidgetEventHandler::PrepareOwnedTooltip(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), Container::SelectItem(), HandsPreview::SelectItem(), SlotsContainer::SelectItem(), Serialize(), Container::SetOpenState(), Icon::SetTemperature(), SlotsIcon::SetTemperature(), Icon::ShowActionMenuCombine(), VicinitySlotsContainer::ShowItemsInContainers(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), PlayerContainer::ToggleWidget(), VicinityContainer::UpdateHeader(), Attachments::UpdateInterval(), HandsPreview::UpdateInterval(), ClosableContainer::UpdateInterval(), UpdateInterval(), IconsContainer::UpdateItemsTemperature(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
GetItemHealthColor() [1/2]
static int ItemManager::GetItemHealthColor (EntityAI item, string zone = "") inline static private
Definition at line 378 of file itemmanager.c.
    {
        if (item)
        {
            switch (item.GetHealthLevel(zone))
            {
            case -1:
            break;
            case GameConstants.STATE_PRISTINE:
                return Colors.COLOR_PRISTINE;
            case GameConstants.STATE_WORN:
                return Colors.COLOR_WORN;
            case GameConstants.STATE_DAMAGED:
                return Colors.COLOR_DAMAGED;
            case GameConstants.STATE_BADLY_DAMAGED:
                return Colors.COLOR_BADLY_DAMAGED;
            case GameConstants.STATE_RUINED:
                return Colors.COLOR_RUINED;
            }
        }
        return 0x00FFFFFF;
    }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
GetItemHealthColor() [2/2]
static int ItemManager::GetItemHealthColor (int pHealthLevel) inline static private
Definition at line 357 of file itemmanager.c.
    {
        switch (pHealthLevel)
        {
        case -1:
        break;
        case GameConstants.STATE_PRISTINE:
            return Colors.COLOR_PRISTINE;
        case GameConstants.STATE_WORN:
            return Colors.COLOR_WORN;
        case GameConstants.STATE_DAMAGED:
            return Colors.COLOR_DAMAGED;
        case GameConstants.STATE_BADLY_DAMAGED:
            return Colors.COLOR_BADLY_DAMAGED;
        case GameConstants.STATE_RUINED:
            return Colors.COLOR_RUINED;
        }
        return 0x00FFFFFF;
    }
References Colors::COLOR_BADLY_DAMAGED, Colors::COLOR_DAMAGED, Colors::COLOR_PRISTINE, Colors::COLOR_RUINED, Colors::COLOR_WORN, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by Hud::RefreshVehicleHud().
GetLeftDropzone()
Widget ItemManager::GetLeftDropzone () inline private
Definition at line 276 of file itemmanager.c.
    {
        if( !m_LeftDropzone )
            m_LeftDropzone  = m_RootWidget.FindAnyWidget( "LeftPanel" ).FindAnyWidget( "DropzoneX" );
        return m_LeftDropzone;
    }
References m_LeftDropzone, and m_RootWidget.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), HideDropzones(), Icon::OnDraggingOverBackground(), SlotsIcon::OnIconDrag(), and ShowSourceDropzone().
GetRecipeCount()
static int ItemManager::GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline static private
Definition at line 734 of file itemmanager.c.
    {
        PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast( GetPlugin( PluginRecipesManager ) );
        return plugin_recipes_manager.GetValidRecipes( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ), NULL, PlayerBase.Cast( GetGame().GetPlayer() ) );
    }
References GetGame(), GetPlayer(), and GetPlugin().
Referenced by GetCombinationFlags().
GetRightDropzone()
Widget ItemManager::GetRightDropzone () inline private
Definition at line 284 of file itemmanager.c.
    {
        if( !m_RightDropzone )
            m_RightDropzone = m_RootWidget.FindAnyWidget( "RightPanel" ).FindAnyWidget( "DropzoneX" );
        return m_RightDropzone;
    }
References m_RightDropzone, and m_RootWidget.
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), HideDropzones(), Icon::OnDraggingOverBackground(), SlotsIcon::OnIconDrag(), and ShowSourceDropzone().
GetSelectedContainer()
Container ItemManager::GetSelectedContainer () inline private
Definition at line 87 of file itemmanager.c.
    {
        return m_SelectedContainer;
    }
References m_SelectedContainer.
Referenced by Container::Select().
GetSelectedIcon()
SlotsIcon ItemManager::GetSelectedIcon () inline private
Definition at line 97 of file itemmanager.c.
    {
        return m_SelectedIcon;
    }
References m_SelectedIcon.
Referenced by Attachments::Select(), VicinitySlotsContainer::Select(), and ZombieContainer::Select().
GetSelectedItem()
EntityAI ItemManager::GetSelectedItem () inline private
Definition at line 82 of file itemmanager.c.
    {
        return m_SelectedItem;
    }
References m_SelectedItem.
Referenced by HandsContainer::OnSelectButton(), MissionBase::OnUpdate(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), and ZombieContainer::Select().
GetSelectedWidget()
Widget ItemManager::GetSelectedWidget () inline private
Definition at line 92 of file itemmanager.c.
    {
        return m_SelectedWidget;
    }
References m_SelectedWidget.
HideDropzones()
void ItemManager::HideDropzones () inline private
Definition at line 241 of file itemmanager.c.
    {
        GetRightDropzone().SetAlpha( 0 );
        GetLeftDropzone().SetAlpha( 0 );
        GetCenterDropzone().SetAlpha( 0 );
    }
References GetCenterDropzone(), GetLeftDropzone(), and GetRightDropzone().
Referenced by Icon::Combine(), Icon::DestroyWhiteBackground(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), InventoryGridController::OnItemDrop(), Icon::ShowActionMenuCombine(), ShowSourceDropzone(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
HideTooltip()
void ItemManager::HideTooltip () inline private
Definition at line 338 of file itemmanager.c.
    {
        m_TooltipWidget.Show( false );
        m_HoveredItem = null;
        delete m_ToolTipTimer;
        HideTooltipSlot();
    }
References HideTooltipSlot(), m_HoveredItem, m_ToolTipTimer, and m_TooltipWidget.
Referenced by ScriptedWidgetEventHandler::HideOwnedTooltip(), OnHide(), PrepareSlotsTooltip(), and PrepareTooltip().
HideTooltipSlot()
void ItemManager::HideTooltipSlot () inline private
Definition at line 347 of file itemmanager.c.
    {
        if ( m_SlotInfoShown )
        {
            m_TooltipSlotWidget.Show( false );
            m_SlotInfoShown = false;
            delete m_TooltipSlotTimer;
        }
    }
References m_SlotInfoShown, m_TooltipSlotTimer, and m_TooltipSlotWidget.
Referenced by ScriptedWidgetEventHandler::HideOwnedSlotsTooltip(), and HideTooltip().
IsDragging()
bool ItemManager::IsDragging () inline private
Definition at line 333 of file itemmanager.c.
    {
        return m_IsDragging;
    }
References m_IsDragging.
Referenced by PrepareTooltip(), VicinitySlotsContainer::ShowItemsInContainers(), PlayerContainer::ToggleWidget(), HandsPreview::UpdateInterval(), and IconsContainer::UpdateItemsTemperature().
IsMicromanagmentMode()
bool ItemManager::IsMicromanagmentMode () inline private
Definition at line 67 of file itemmanager.c.
    {
        return m_ItemMicromanagmentMode;
    }
References m_ItemMicromanagmentMode.
Referenced by DisableMicromanagement(), EnableMicromanagement(), MoveFocusByArea(), HandsContainer::OnSelectButton(), HandsPreview::Select(), and UpdateInterval().
PrepareSlotsTooltip()
void ItemManager::PrepareSlotsTooltip (string name, string desc, int x = 0, int y = 0) inline private
position is currentlycalculated from the owning 'm_TooltipSourceWidget' directly
Definition at line 536 of file itemmanager.c.
    {
        InspectMenuNew.UpdateSlotInfo( m_TooltipSlotWidget, name, desc );
        HideTooltip();
        if (name != "")
        {
            m_SlotInfoShown = true;
            //CalculateTooltipSlotPosition(x,y);
            m_TooltipSlotTimer = new Timer();
            m_TooltipSlotTimer.Run( TOOLTIP_DELAY, this, "ShowTooltipSlot" );
        }
    }
References HideTooltip(), m_SlotInfoShown, m_TooltipSlotTimer, m_TooltipSlotWidget, name, and TOOLTIP_DELAY.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip().
PrepareTooltip()
void ItemManager::PrepareTooltip (EntityAI item, int x = 0, int y = 0) inline private
Definition at line 473 of file itemmanager.c.
    {
        if( IsDragging() || !item )
        {
            return;
        }
        if ( item.IsInherited( InventoryItem ) )
        {
            HideTooltip();
            m_HoveredItem = item;
            InspectMenuNew.UpdateItemInfo( m_TooltipWidget, item );
            int screen_w, screen_h;
            float w, h;
            GetScreenSize(screen_w, screen_h);
            m_TooltipWidget.GetScreenSize(w,h);
            if (x == -1)//set by icon focusing
            {
                x = screen_w/2 - w/2;
                float x1,y1;
                m_RootWidget.FindAnyWidget("InventoryFrameWidget").GetScreenPos(x1,y1); //allign to the same height
                y = y1;
            }
            else if (x == 0 && y == 0 && GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer())
            {
                GetMousePos(x,y);
            }
            //minimal edge distance adjustments..
            screen_w -= 10;
            screen_h -= 10;
            int rightEdge = x + w;
            if (rightEdge > screen_w)
            {
                x = screen_w - w;
            }
            int bottomEdge = y + h;
            if (bottomEdge > screen_h)
            {
                y = screen_h - h;
            }
            m_TooltipWidget.SetPos(x, y);
            m_ToolTipTimer = new Timer();
            m_ToolTipTimer.Run( TOOLTIP_DELAY, this, "ShowTooltip" );
            Widget preview_frame = m_TooltipWidget.FindAnyWidget("ItemFrameWidget");
            if (preview_frame)
            {
                m_ItemPreviewWidget = ItemPreviewWidget.Cast( preview_frame );
                m_ItemPreviewWidget.SetItem(item);
                m_ItemPreviewWidget.SetView( item.GetViewIndex() );
            }
        }
    }
References GetGame(), GetInput(), GetMousePos(), GetScreenSize(), HideTooltip(), IsDragging(), m_HoveredItem, m_ItemPreviewWidget, m_RootWidget, m_ToolTipTimer, m_TooltipWidget, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetView(), TOOLTIP_DELAY, x, and y.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedTooltip().
SerializeDefaultHeaderOpenStates()
void ItemManager::SerializeDefaultHeaderOpenStates () inline private
Definition at line 146 of file itemmanager.c.
    {
        TStringArray serialized_types = new TStringArray;
        for ( int i = 0; i < m_DefautHeaderOpenStates.Count(); i++ )
        {
            int is_opened = m_DefautHeaderOpenStates.GetElement( i ); //from bool to int for easier parsing
            serialized_types.Insert( m_DefautHeaderOpenStates.GetKey( i ) + "," + is_opened );
        }
        if( serialized_types.Count() > 0 )
        {
            GetGame().SetProfileStringList( "defaultHeaderOpenStates", serialized_types );
        }
        GetGame().SaveProfile();
    }
References GetGame(), m_DefautHeaderOpenStates, CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by Serialize().
SerializeDefaultOpenStates()
void ItemManager::SerializeDefaultOpenStates () inline private
Definition at line 179 of file itemmanager.c.
    {
        TStringArray serialized_types = new TStringArray;
        for ( int i = 0; i < m_DefautOpenStates.Count(); i++ )
        {
            int is_opened = m_DefautOpenStates.GetElement( i ); //from bool to int for easier parsing
            serialized_types.Insert( m_DefautOpenStates.GetKey( i ) + "," + is_opened );
        }
        if( serialized_types.Count() > 0 )
        {
            GetGame().SetProfileStringList( "defaultOpenStates", serialized_types );
        }
        GetGame().SaveProfile();
    }
References GetGame(), m_DefautOpenStates, CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by Serialize().
SetDefaultHeaderOpenState()
void ItemManager::SetDefaultHeaderOpenState (string type, bool is_opened) inline private
Definition at line 125 of file itemmanager.c.
    {
        m_DefautHeaderOpenStates.Set( type, is_opened );
    }
References m_DefautHeaderOpenStates.
Referenced by VicinityContainer::CollapseButtonOnMouseButtonDown(), and DeserializeDefaultHeaderOpenStates().
SetDefaultOpenState()
void ItemManager::SetDefaultOpenState (string type, bool is_opened) inline private
Definition at line 120 of file itemmanager.c.
    {
        m_DefautOpenStates.Set( type, is_opened );
    }
References m_DefautOpenStates.
Referenced by Container::Close(), ClosableContainer::Close(), DeserializeDefaultOpenStates(), Container::Open(), ClosableContainer::Open(), and Container::SetOpenState().
SetDefaultOpenStateHands()
void ItemManager::SetDefaultOpenStateHands (bool is_opened) inline private
Definition at line 130 of file itemmanager.c.
    {
        m_HandsDefaultOpenState = is_opened;
        int hands_default_open_state = m_HandsDefaultOpenState; //from bool to int for easier parsing
        GetGame().SetProfileString( "defaultOpenStateHands", hands_default_open_state.ToString() );
        GetGame().SaveProfile();
    }
References GetGame(), m_HandsDefaultOpenState, CGame::SaveProfile(), and CGame::SetProfileString().
SetDraggedIcon()
void ItemManager::SetDraggedIcon (Icon dragged_icon) inline private
Definition at line 313 of file itemmanager.c.
    {
        m_DraggedIcon = dragged_icon;
    }
References m_DraggedIcon.
Referenced by Icon::CreateWhiteBackground(), and SetIsDragging().
SetDraggedItem()
void ItemManager::SetDraggedItem (EntityAI dragged_item) inline private
Definition at line 303 of file itemmanager.c.
    {
        m_DraggedItem = dragged_item;
    }
References m_DraggedItem.
Referenced by Icon::CreateWhiteBackground(), SlotsIcon::OnIconDrag(), and SetIsDragging().
SetHandsPreview()
void ItemManager::SetHandsPreview (HandsPreview hansd_preview) inline private
Definition at line 77 of file itemmanager.c.
    {
        m_HandsPreview = hansd_preview;
    }
References m_HandsPreview.
Referenced by HandsContainer::HandsContainer().
SetIconTemperature()
void ItemManager::SetIconTemperature (EntityAI item, Widget item_w) inline private
Definition at line 449 of file itemmanager.c.
    {
        if ( item_w )
        {
            if ( item && item.IsInherited( ItemBase ) )
            {
                int color = ColorManager.GetInstance().GetItemColor( ItemBase.Cast( item ) );
                if ( color )
                {
                    Widget color_widget = item_w.FindAnyWidget( "Color" );
                    if( color != -1 )
                    {
                        color_widget.SetColor( color );
                    }
                    else
                    {
                        color_widget.SetColor( ColorManager.BASE_COLOR );
                    }
                }
            }
        }
    }
References ColorManager::BASE_COLOR, ColorManager::GetInstance(), and ColorManager::GetItemColor().
Referenced by Icon::SetTemperature(), and SlotsIcon::SetTemperature().
SetIsDragging()
void ItemManager::SetIsDragging (bool is_dragging) inline private
Definition at line 323 of file itemmanager.c.
    {
        m_IsDragging = is_dragging;
        if( !is_dragging )
        {
            SetDraggedItem( null );
            SetDraggedIcon( null );
        }
    }
References m_IsDragging, SetDraggedIcon(), and SetDraggedItem().
Referenced by Icon::Combine(), Icon::CreateWhiteBackground(), Icon::DestroyWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), Icon::DropReceivedFromMain(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), Icon::Swap(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), Icon::~Icon(), and SlotsIcon::~SlotsIcon().
SetItemMicromanagmentMode()
void ItemManager::SetItemMicromanagmentMode (bool item_micromanagment_mode) inline private
Definition at line 62 of file itemmanager.c.
    {
        m_ItemMicromanagmentMode = item_micromanagment_mode;
    }
References m_ItemMicromanagmentMode.
Referenced by DisableMicromanagement(), EnableMicromanagement(), OnHide(), and OnShow().
SetSelectedItem()
void ItemManager::SetSelectedItem (EntityAI selected_item, Container selected_container, Widget selected_widget, SlotsIcon selected_icon) inline private
Definition at line 102 of file itemmanager.c.
    {
        m_SelectedItem      = selected_item;
        m_SelectedContainer = selected_container;
        m_SelectedWidget    = selected_widget;
        m_SelectedIcon      = selected_icon;
    }
References m_SelectedContainer, m_SelectedIcon, m_SelectedItem, and m_SelectedWidget.
Referenced by DisableMicromanagement(), Icon::Icon(), OnHide(), OnShow(), Attachments::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), Container::SelectItem(), HandsPreview::SelectItem(), and SlotsContainer::SelectItem().
SetTemperature()
void ItemManager::SetTemperature (EntityAI item, Widget item_w) inline private
Definition at line 418 of file itemmanager.c.
    {
        if ( item_w )
        {
            if ( true/*show_temperature */ )
            {
                if ( item && item.IsInherited( ItemBase ) )
                {
                    int color = ColorManager.GetInstance().GetItemColor( ItemBase.Cast( item ) ); // !!!!!
                    if ( color )
                    {
                        string name = item_w.GetName();
                        name.Replace("Render", "Temperature");
                        Widget temperature_widget = item_w.GetParent().FindAnyWidget( name );
                        if ( color != -1 )
{
                            temperature_widget.Show( true );
                            temperature_widget.SetColor( color );
                        }
                        else
{
                            temperature_widget.Show( false );
                        }
                        temperature_widget.SetAlpha( 0.3 );
                    }
                }
            }
        }
    }
References ColorManager::GetInstance(), ColorManager::GetItemColor(), name, and string::Replace().
Referenced by VicinitySlotsContainer::ShowItemsInContainers().
SetTooltipWidget()
void ItemManager::SetTooltipWidget (Widget w) inline private
Definition at line 625 of file itemmanager.c.
    {
        m_TooltipSourceWidget = w;
    }
References m_TooltipSourceWidget.
Referenced by ScriptedWidgetEventHandler::PrepareOwnedSlotsTooltip().
SetWidgetDraggable()
void ItemManager::SetWidgetDraggable (Widget w, bool draggable) inline private
Definition at line 644 of file itemmanager.c.
    {
        if (w)
        {
            if ( draggable )
                w.SetFlags( WidgetFlags.DRAGGABLE );
            else
                w.ClearFlags( WidgetFlags.DRAGGABLE );
        }
    }
Referenced by SlotsIcon::Clear(), SlotsIcon::Init(), Icon::InitLock(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
ShowSourceDropzone()
void ItemManager::ShowSourceDropzone (EntityAI item) inline private
Definition at line 248 of file itemmanager.c.
    {
        EntityAI owner = item.GetHierarchyParent();
        if( owner && owner != GetGame().GetPlayer() )
        {
            ShowSourceDropzone( owner );
        }
        else
        {
            InventoryLocation inv_loc_src = new InventoryLocation;
            item.GetInventory().GetCurrentInventoryLocation( inv_loc_src );
            int loc_type = inv_loc_src.GetType();
            HideDropzones();
            if( loc_type == InventoryLocationType.GROUND )
            {
                GetLeftDropzone().SetAlpha( 1 );
            }
            else if( loc_type == InventoryLocationType.HANDS )
            {
                GetCenterDropzone().SetAlpha( 1 );
            }
            else
            {
                GetRightDropzone().SetAlpha( 1 );
            }
        }
    }
References GetCenterDropzone(), GetGame(), GetLeftDropzone(), GetPlayer(), GetRightDropzone(), InventoryLocation::GetType(), HideDropzones(), and ShowSourceDropzone().
Referenced by Icon::DraggingOver(), ClosableContainer::DraggingOver(), DraggingOverCenterPanel(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), Icon::ShowActionMenuCombine(), and ShowSourceDropzone().
ShowTooltip()
void ItemManager::ShowTooltip () inline private
Definition at line 655 of file itemmanager.c.
    {
        if( m_ItemPreviewWidget )
        {
            m_TooltipWidget.Show( true );
        }
    }
References m_ItemPreviewWidget, and m_TooltipWidget.
ShowTooltipSlot()
void ItemManager::ShowTooltipSlot () inline private
Definition at line 663 of file itemmanager.c.
    {
        UpdateTooltipSlotPosition();
        m_TooltipSlotWidget.SetPos(m_TooltipPosX, m_TooltipPosY);
        m_TooltipSlotWidget.Show( true );
    }
References m_TooltipPosX, m_TooltipPosY, m_TooltipSlotWidget, and UpdateTooltipSlotPosition().
UpdateTooltipSlotPosition()
void ItemManager::UpdateTooltipSlotPosition () inline private
Definition at line 618 of file itemmanager.c.
    {
        float x, y;
        m_TooltipSourceWidget.GetScreenPos(x,y);
        CalculateTooltipSlotPosition(x,y);
    }
References CalculateTooltipSlotPosition(), m_TooltipSourceWidget, x, and y.
Referenced by ShowTooltipSlot().
Member Data Documentation
m_CenterDropzone
protected Widget ItemManager::m_CenterDropzone private
Definition at line 30 of file itemmanager.c.
Referenced by GetCenterDropzone().
m_DefautHeaderOpenStates
protected ref map<string, bool> ItemManager::m_DefautHeaderOpenStates private
Definition at line 15 of file itemmanager.c.
Referenced by ClearDefaultHeaderOpenStates(), GetDefaultHeaderOpenState(), ItemManager(), SerializeDefaultHeaderOpenStates(), and SetDefaultHeaderOpenState().
m_DefautOpenStates
protected ref map<string, bool> ItemManager::m_DefautOpenStates private
Definition at line 14 of file itemmanager.c.
Referenced by ClearDefaultOpenStates(), GetDefaultOpenState(), ItemManager(), SerializeDefaultOpenStates(), and SetDefaultOpenState().
m_DraggedIcon
protected Icon ItemManager::m_DraggedIcon private
Definition at line 8 of file itemmanager.c.
Referenced by GetDraggedIcon(), and SetDraggedIcon().
m_DraggedItem
protected EntityAI ItemManager::m_DraggedItem private
Definition at line 7 of file itemmanager.c.
Referenced by GetDraggedItem(), and SetDraggedItem().
m_HandsDefaultOpenState
protected int ItemManager::m_HandsDefaultOpenState private
Definition at line 16 of file itemmanager.c.
Referenced by GetDefaultOpenStateHands(), and SetDefaultOpenStateHands().
m_HandsPreview
protected HandsPreview ItemManager::m_HandsPreview private
Definition at line 25 of file itemmanager.c.
Referenced by GetHandsPreview(), and SetHandsPreview().
m_HoveredItem
protected EntityAI ItemManager::m_HoveredItem private
Definition at line 5 of file itemmanager.c.
Referenced by GetHoveredItem(), HideTooltip(), and PrepareTooltip().
m_Instance
private static ref ItemManager ItemManager::m_Instance static private
Definition at line 3 of file itemmanager.c.
Referenced by GetInstance(), and ItemManager().
m_IsDragging
protected bool ItemManager::m_IsDragging private
Definition at line 4 of file itemmanager.c.
Referenced by IsDragging(), and SetIsDragging().
m_ItemMicromanagmentMode
protected bool ItemManager::m_ItemMicromanagmentMode private
Definition at line 27 of file itemmanager.c.
Referenced by IsMicromanagmentMode(), and SetItemMicromanagmentMode().
m_ItemPreviewWidget
protected ItemPreviewWidget ItemManager::m_ItemPreviewWidget private
Definition at line 12 of file itemmanager.c.
Referenced by PrepareTooltip(), and ShowTooltip().
m_LeftDropzone
protected Widget ItemManager::m_LeftDropzone private
Definition at line 29 of file itemmanager.c.
Referenced by GetLeftDropzone().
m_RightDropzone
protected Widget ItemManager::m_RightDropzone private
Definition at line 31 of file itemmanager.c.
Referenced by GetRightDropzone().
m_RootWidget
protected Widget ItemManager::m_RootWidget private
Definition at line 13 of file itemmanager.c.
Referenced by GetCenterDropzone(), GetLeftDropzone(), GetRightDropzone(), ItemManager(), and PrepareTooltip().
m_SelectedContainer
protected Container ItemManager::m_SelectedContainer private
Definition at line 21 of file itemmanager.c.
Referenced by GetSelectedContainer(), and SetSelectedItem().
m_SelectedIcon
protected SlotsIcon ItemManager::m_SelectedIcon private
Definition at line 23 of file itemmanager.c.
Referenced by GetSelectedIcon(), and SetSelectedItem().
m_SelectedItem
protected EntityAI ItemManager::m_SelectedItem private
Definition at line 20 of file itemmanager.c.
Referenced by GetSelectedItem(), and SetSelectedItem().
m_SelectedWidget
protected Widget ItemManager::m_SelectedWidget private
Definition at line 22 of file itemmanager.c.
Referenced by GetSelectedWidget(), and SetSelectedItem().
m_SlotInfoShown
protected bool ItemManager::m_SlotInfoShown private
Definition at line 6 of file itemmanager.c.
Referenced by HideTooltipSlot(), ItemManager(), and PrepareSlotsTooltip().
m_TooltipCategoryWidget
protected ref Widget ItemManager::m_TooltipCategoryWidget private
Definition at line 11 of file itemmanager.c.
m_TooltipPosX
protected int ItemManager::m_TooltipPosX private
Definition at line 33 of file itemmanager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipPosY
protected int ItemManager::m_TooltipPosY private
Definition at line 34 of file itemmanager.c.
Referenced by CalculateTooltipSlotPosition(), and ShowTooltipSlot().
m_TooltipSlotTimer
protected ref Timer ItemManager::m_TooltipSlotTimer private
Definition at line 18 of file itemmanager.c.
Referenced by HideTooltipSlot(), and PrepareSlotsTooltip().
m_TooltipSlotWidget
protected ref Widget ItemManager::m_TooltipSlotWidget private
Definition at line 10 of file itemmanager.c.
Referenced by CalculateTooltipSlotPosition(), HideTooltipSlot(), ItemManager(), PrepareSlotsTooltip(), and ShowTooltipSlot().
m_TooltipSourceWidget
protected Widget ItemManager::m_TooltipSourceWidget private
Definition at line 35 of file itemmanager.c.
Referenced by CalculateTooltipSlotPosition(), SetTooltipWidget(), and UpdateTooltipSlotPosition().
m_ToolTipTimer
protected ref Timer ItemManager::m_ToolTipTimer private
Definition at line 17 of file itemmanager.c.
Referenced by HideTooltip(), and PrepareTooltip().
m_TooltipWidget
protected ref Widget ItemManager::m_TooltipWidget private
Definition at line 9 of file itemmanager.c.
Referenced by HideTooltip(), ItemManager(), PrepareTooltip(), and ShowTooltip().
TOOLTIP_DELAY
protected const float ItemManager::TOOLTIP_DELAY = 0.25 private
Definition at line 38 of file itemmanager.c.
Referenced by PrepareSlotsTooltip(), and PrepareTooltip().