DayzKode: FireConsumable Class Reference
FireConsumable Class Reference
Private Member Functions
void FireConsumable (ItemBase item, float energy)
float GetEnergy ()
ItemBase GetItem ()
float GetRemainingEnergy ()
void SetRemainingEnergy (float energy)
Private Attributes
float m_Energy
ItemBase m_Item
float m_RemainingEnergy
Detailed Description
Definition at line 1 of file fireconsumable.c.
Constructor & Destructor Documentation
FireConsumable()
void FireConsumable::FireConsumable (ItemBase item, float energy) inline private
Definition at line 7 of file fireconsumable.c.
    {
        m_Item = item;
        m_Energy = energy;
        m_RemainingEnergy = energy;
    }
References m_Energy, m_Item, and m_RemainingEnergy.
Member Function Documentation
GetEnergy()
float FireConsumable::GetEnergy () inline private
Definition at line 21 of file fireconsumable.c.
    {
        return m_Energy;
    }
References m_Energy.
Referenced by CalcAndSetQuantity(), and SetItemToConsume().
GetItem()
ItemBase FireConsumable::GetItem () inline private
Definition at line 15 of file fireconsumable.c.
    {
        return m_Item;
    }
References m_Item.
Referenced by CalcAndSetQuantity(), and RemoveFromFireConsumables().
GetRemainingEnergy()
float FireConsumable::GetRemainingEnergy () inline private
Definition at line 27 of file fireconsumable.c.
    {
        return m_RemainingEnergy;
    }
References m_RemainingEnergy.
Referenced by CalcAndSetQuantity().
SetRemainingEnergy()
void FireConsumable::SetRemainingEnergy (float energy) inline private
Definition at line 32 of file fireconsumable.c.
    {
        m_RemainingEnergy = energy;
    }
References m_RemainingEnergy.
Member Data Documentation
m_Energy
float FireConsumable::m_Energy private
Definition at line 4 of file fireconsumable.c.
Referenced by FireConsumable(), and GetEnergy().
m_Item
ItemBase FireConsumable::m_Item private
Definition at line 3 of file fireconsumable.c.
Referenced by FireConsumable(), and GetItem().
m_RemainingEnergy
float FireConsumable::m_RemainingEnergy private
Definition at line 5 of file fireconsumable.c.
Referenced by FireConsumable(), GetRemainingEnergy(), and SetRemainingEnergy().