DayzKode: PoisoningMdfr Class Reference
PoisoningMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Static Private Attributes
static const int AGENT_THRESHOLD_ACTIVATE = 150
static const int AGENT_THRESHOLD_DEACTIVATE = 0
static const int ENERGY_DRAIN_FROM_VOMIT = 55
static const int VOMIT_OCCURRENCES_PER_HOUR_MAX = 120
static const int VOMIT_OCCURRENCES_PER_HOUR_MIN = 60
static const int WATER_DRAIN_FROM_VOMIT = 70
Detailed Description
Definition at line 1 of file poisoning.c.
Member Function Documentation
ActivateCondition()
override bool PoisoningMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 26 of file poisoning.c.
    {
        if(player.GetSingleAgentCount(eAgents.FOOD_POISON) >= AGENT_THRESHOLD_ACTIVATE)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References AGENT_THRESHOLD_ACTIVATE.
DeactivateCondition()
override bool PoisoningMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 38 of file poisoning.c.
    {
        if(player.GetSingleAgentCount(eAgents.FOOD_POISON) <= AGENT_THRESHOLD_DEACTIVATE)
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References AGENT_THRESHOLD_DEACTIVATE.
GetDebugText()
override string PoisoningMdfr::GetDebugText () inline private
Definition at line 21 of file poisoning.c.
    {
        return ("Activate threshold: "+AGENT_THRESHOLD_ACTIVATE + "| " +"Deativate threshold: "+AGENT_THRESHOLD_DEACTIVATE);
    }
References AGENT_THRESHOLD_ACTIVATE, and AGENT_THRESHOLD_DEACTIVATE.
Init()
override void PoisoningMdfr::Init () inline private
Definition at line 12 of file poisoning.c.
    {
        m_TrackActivatedTime    = true;
        m_IsPersistent          = true;
        m_ID                    = eModifiers.MDF_POISONING;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_IsPersistent, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void PoisoningMdfr::OnActivate (PlayerBase player) inline private
Definition at line 50 of file poisoning.c.
    {
        player.IncreaseDiseaseCount();
    }
OnDeactivate()
override void PoisoningMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 60 of file poisoning.c.
    {
        player.DecreaseDiseaseCount();
    }
OnReconnect()
override void PoisoningMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 55 of file poisoning.c.
    {
        this.OnActivate(player);
    }
References OnActivate().
OnTick()
override void PoisoningMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 65 of file poisoning.c.
    {
        int agent_max = PluginTransmissionAgents.GetAgentMaxCount(eAgents.FOOD_POISON);
        int agent_count = player.m_AgentPool.GetSingleAgentCount(eAgents.FOOD_POISON);
        float stomach_volume = player.m_PlayerStomach.GetStomachVolume();
        float norm_value = Math.InverseLerp(0, agent_max, agent_count );
        float eased_value = Easing.EaseInCirc(norm_value);
        float chance = Math.Lerp(VOMIT_OCCURRENCES_PER_HOUR_MIN, VOMIT_OCCURRENCES_PER_HOUR_MAX, eased_value );
        chance = (chance / 3600) * deltaT;
        if( Math.RandomFloat01() < chance )
        {
            SymptomBase symptom = player.GetSymptomManager().QueueUpPrimarySymptom(SymptomIDs.SYMPTOM_VOMIT);
            if( symptom )
            {
                symptom.SetDuration(5);
                if (m_Player.GetStatWater().Get() > (WATER_DRAIN_FROM_VOMIT))
                    m_Player.GetStatWater().Add(-1 * WATER_DRAIN_FROM_VOMIT);
                if (m_Player.GetStatEnergy().Get() > (ENERGY_DRAIN_FROM_VOMIT))
                    m_Player.GetStatEnergy().Add(-1 * ENERGY_DRAIN_FROM_VOMIT);
            }
        }
    }
References Easing::EaseInCirc(), ENERGY_DRAIN_FROM_VOMIT, Math::InverseLerp(), Math::Lerp(), m_Player, Math::RandomFloat01(), SymptomBase::SetDuration(), VOMIT_OCCURRENCES_PER_HOUR_MAX, VOMIT_OCCURRENCES_PER_HOUR_MIN, and WATER_DRAIN_FROM_VOMIT.
Member Data Documentation
AGENT_THRESHOLD_ACTIVATE
const int PoisoningMdfr::AGENT_THRESHOLD_ACTIVATE = 150 static private
Definition at line 3 of file poisoning.c.
Referenced by ActivateCondition(), and GetDebugText().
AGENT_THRESHOLD_DEACTIVATE
const int PoisoningMdfr::AGENT_THRESHOLD_DEACTIVATE = 0 static private
Definition at line 4 of file poisoning.c.
Referenced by DeactivateCondition(), and GetDebugText().
ENERGY_DRAIN_FROM_VOMIT
const int PoisoningMdfr::ENERGY_DRAIN_FROM_VOMIT = 55 static private
Definition at line 10 of file poisoning.c.
Referenced by OnTick().
VOMIT_OCCURRENCES_PER_HOUR_MAX
const int PoisoningMdfr::VOMIT_OCCURRENCES_PER_HOUR_MAX = 120 static private
Definition at line 7 of file poisoning.c.
Referenced by OnTick().
VOMIT_OCCURRENCES_PER_HOUR_MIN
const int PoisoningMdfr::VOMIT_OCCURRENCES_PER_HOUR_MIN = 60 static private
Definition at line 6 of file poisoning.c.
Referenced by OnTick().
WATER_DRAIN_FROM_VOMIT
const int PoisoningMdfr::WATER_DRAIN_FROM_VOMIT = 70 static private
Definition at line 9 of file poisoning.c.
Referenced by OnTick().