DayzKode: CharcoalMdfr Class Reference
CharcoalMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugTextSimple ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int CHARCOAL_EFFECT_TIME = 100
const int CHARCOAL_LIFETIME = 300
float m_Killrate
Detailed Description
Definition at line 1 of file charcoalmdfr.c.
Member Function Documentation
ActivateCondition()
override bool CharcoalMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 18 of file charcoalmdfr.c.
    {
        return false;
    }
DeactivateCondition()
override bool CharcoalMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 66 of file charcoalmdfr.c.
    {
        float attached_time = GetAttachedTime();
        if ( attached_time >= CHARCOAL_LIFETIME )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References CHARCOAL_LIFETIME, and GetAttachedTime().
GetDebugTextSimple()
override string CharcoalMdfr::GetDebugTextSimple () inline private
Definition at line 49 of file charcoalmdfr.c.
    {
        return ( (int)(CHARCOAL_LIFETIME - GetAttachedTime()) ).ToString() + " | " + (((int)(CHARCOAL_LIFETIME - CHARCOAL_EFFECT_TIME  - GetAttachedTime())) * -1).ToString();
    }
References CHARCOAL_EFFECT_TIME, CHARCOAL_LIFETIME, GetAttachedTime(), int, ToString(), and string::ToString().
Init()
override void CharcoalMdfr::Init () inline private
Definition at line 7 of file charcoalmdfr.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_CHARCOAL;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 3;
        m_Killrate = 2.85;  // # of killed agents per sec
        DisableActivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_Killrate, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void CharcoalMdfr::OnActivate (PlayerBase player) inline private
Definition at line 54 of file charcoalmdfr.c.
    {
        player.IncreaseHealingsCount();
    }
OnDeactivate()
override void CharcoalMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 60 of file charcoalmdfr.c.
    {
        player.DecreaseHealingsCount();
    }
OnReconnect()
override void CharcoalMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 23 of file charcoalmdfr.c.
    {
        OnActivate( player );
    }
References OnActivate().
OnTick()
override void CharcoalMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 80 of file charcoalmdfr.c.
    {
        if ( GetAttachedTime() > ( CHARCOAL_LIFETIME - CHARCOAL_EFFECT_TIME ) )
        {
            player.m_AgentPool.AddAgent(eAgents.SALMONELLA, -m_Killrate * deltaT);
        }
    }
References CHARCOAL_EFFECT_TIME, CHARCOAL_LIFETIME, GetAttachedTime(), and m_Killrate.
Member Data Documentation
CHARCOAL_EFFECT_TIME
const int CharcoalMdfr::CHARCOAL_EFFECT_TIME = 100 private
Definition at line 5 of file charcoalmdfr.c.
Referenced by GetDebugTextSimple(), and OnTick().
CHARCOAL_LIFETIME
const int CharcoalMdfr::CHARCOAL_LIFETIME = 300 private
Definition at line 4 of file charcoalmdfr.c.
Referenced by DeactivateCondition(), GetDebugTextSimple(), and OnTick().
m_Killrate
float CharcoalMdfr::m_Killrate private
Definition at line 3 of file charcoalmdfr.c.
Referenced by Init(), and OnTick().