DayzKode: UnboxLambda Class Reference
UnboxLambda Class Reference
Private Member Functions
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
void UnboxLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count)
Private Attributes
int m_ItemCount
Detailed Description
Definition at line 75 of file actionunpackbox.c.
Constructor & Destructor Documentation
UnboxLambda()
void UnboxLambda::UnboxLambda (EntityAI old_item, string new_item_type, PlayerBase player, int count) inline private
Definition at line 78 of file actionunpackbox.c.
{ m_ItemCount = count; }
References m_ItemCount.
Member Function Documentation
CopyOldPropertiesToNew()
override void UnboxLambda::CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
Definition at line 80 of file actionunpackbox.c.
    {
        super.CopyOldPropertiesToNew(old_item, new_item);
        if ( GetGame().ConfigIsExisting( "CfgMagazines " + m_NewItemType ) )
        {
            Magazine pile;
            Class.CastTo(pile, new_item);
            pile.ServerSetAmmoCount(m_ItemCount);
            Print("UnboxLambda::SetupNewMagazine new_item=" + new_item + " count=" + m_ItemCount);
        }
        else
        {
            ItemBase unboxed;
            Class.CastTo(unboxed, new_item);
            unboxed.SetQuantity(m_ItemCount);
            Print("UnboxLambda::SetupNewItem new_item=" + new_item + " count=" + m_ItemCount);
        }
    }
References Class::CastTo(), ConfigIsExisting(), GetGame(), m_ItemCount, ReplaceItemWithNewLambdaBase::m_NewItemType, and Print().
Member Data Documentation
m_ItemCount
int UnboxLambda::m_ItemCount private
Definition at line 77 of file actionunpackbox.c.
Referenced by CopyOldPropertiesToNew(), and UnboxLambda().