DayzKode: DayZSpectator Class Reference
DayZSpectator Class Reference
Private Member Functions
void DayZSpectator ()
override void EOnFrame (IEntity other, float timeSlice)
Private Attributes
private float m_SendUpdateAcc = 0.0
private float m_SpeedMultiplier = 1.0
Detailed Description
Definition at line 1 of file dayzspectator.c.
Constructor & Destructor Documentation
DayZSpectator()
void DayZSpectator::DayZSpectator () inline private
Definition at line 7 of file dayzspectator.c.
    {
        SetEventMask(EntityEvent.FRAME);
    }
Member Function Documentation
EOnFrame()
override void DayZSpectator::EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 12 of file dayzspectator.c.
    {
        Input input = GetGame().GetInput();
        if( input.LocalPress("UACarShiftGearUp") )
            m_SpeedMultiplier = m_SpeedMultiplier + 2;
        if( input.LocalPress("UACarShiftGearDown") )
            m_SpeedMultiplier = m_SpeedMultiplier - 2;
        float speed = 5.0 * m_SpeedMultiplier;
        if( input.LocalValue("UATurbo") )
            speed *= 2;
        float forward = input.LocalValue("UAMoveForward") - input.LocalValue("UAMoveBack");
        float strafe = input.LocalValue("UATurnRight") - input.LocalValue("UATurnLeft");
        vector direction = GetDirection();
        vector directionAside = vector.Up * direction;
        vector oldPos = GetPosition();
        vector forwardChange = forward * timeSlice * direction * speed;
        vector strafeChange = strafe * timeSlice * directionAside * speed;
        vector newPos = oldPos + forwardChange + strafeChange;
        float yMin = GetGame().SurfaceRoadY(newPos[0], newPos[2]);
        if( newPos[1] < yMin )
            newPos[1] = yMin;
        SetPosition(newPos);
        float yawDiff = input.LocalValue("UAAimLeft") - input.LocalValue("UAAimRight");
        float pitchDiff = input.LocalValue("UAAimDown") - input.LocalValue("UAAimUp");
        vector oldOrient = GetOrientation();
        vector newOrient = oldOrient;
        newOrient[0] = newOrient[0] - Math.RAD2DEG * yawDiff * timeSlice;
        newOrient[1] = newOrient[1] - Math.RAD2DEG * pitchDiff * timeSlice;
        if( newOrient[1] < -89 )
            newOrient[1] = -89;
        if( newOrient[1] > 89 )
            newOrient[1] = 89;
        SetOrientation(newOrient);
        if( m_SendUpdateAcc > 0.5 )
        {
            GetGame().UpdateSpectatorPosition(newPos);
            m_SendUpdateAcc = 0;
        }
        m_SendUpdateAcc = m_SendUpdateAcc + timeSlice;
    }
References GetDirection(), GetGame(), CGame::GetInput(), GetOrientation(), GetPosition, Input::LocalPress(), Input::LocalValue(), m_SendUpdateAcc, m_SpeedMultiplier, Math::RAD2DEG, SetOrientation(), SetPosition(), CGame::SurfaceRoadY(), vector::Up, and CGame::UpdateSpectatorPosition().
Member Data Documentation
m_SendUpdateAcc
private float DayZSpectator::m_SendUpdateAcc = 0.0 private
Definition at line 5 of file dayzspectator.c.
Referenced by EOnFrame().
m_SpeedMultiplier
private float DayZSpectator::m_SpeedMultiplier = 1.0 private
Definition at line 3 of file dayzspectator.c.
Referenced by EOnFrame().