DayzKode: BiosUserManager Class Reference
BiosUserManager Class Reference
Private Member Functions
proto native BiosUser GetSelectedUser ()
Returns the currently selected user.
proto native BiosUser GetTitleInitiator ()
Gets the initiatior of the title.
BiosUser GetUser (string user_id)
proto native EBiosError GetUserDatabaseIdAsync ()
Call async function to get database ID.
proto native EBiosError GetUserList (array< ref BiosUser > user_list)
Gets the currently present list of users.
proto native EBiosError LogOnUserAsync (BiosUser user)
Display a system dependant ui for log-on.
void OnGameNameChanged (BiosUser user)
Callback function.
void OnJoin (EBiosJoinType type, BiosUser joiner, string handle, string joinee, EBiosError error)
Callback function.
void OnLoggedOff (BiosUser user)
Callback function.
void OnLoggedOn (BiosUser user)
Callback function.
void OnPartyHost (BiosUser host, array< string > invitee_list, EBiosError error)
Callback function.
void OnSignedIn (BiosUser user)
Callback function.
void OnSignedOut (BiosUser user)
Callback function.
void OnUserDatabaseId (string dbID, EBiosError error)
Callback function.
void OnUserLoggedOn (EBiosError error)
Callback function.
void OnUserPicked (BiosUser user, EBiosError error)
Callback function.
proto native EBiosError ParseJoinAsync (string join_data)
Parse the join data from from command line parameters.
proto native EBiosError ParsePartyAsync (string party_data)
Parse the party data from from command line parameters.
proto native EBiosError PickUserAsync ()
Display a system dependant account picket.
proto native void SelectUser (BiosUser user)
Informs the engine about the current selected user.
void SelectUserEx (BiosUser user)
Detailed Description
Definition at line 16 of file biosusermanager.c.
Member Function Documentation
GetSelectedUser()
proto native BiosUser BiosUserManager::GetSelectedUser () private
Returns the currently selected user.
Returns
BiosUser the selected user. May be NULL.
Referenced by CreateTitleScreen(), OnlineServices::GetClientServices(), DayZIntroScene::GetSelectedUserName(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::IsLocalPlayer(), UIScriptedMenu::IsLocalPlayer(), OnGameNameChanged(), OnLoggedOn(), OnSignedOut(), UIScriptedMenu::Refresh(), SelectGamepad(), SelectUser(), SelectUserEx(), Managed::SetupPlayerName(), and DayZIntroSceneXbox::UpdateSelectedUserName().
GetTitleInitiator()
proto native BiosUser BiosUserManager::GetTitleInitiator () private
Gets the initiatior of the title.
Returns
BiosUser the initiator. May be NULL.
Referenced by ConnectLaunch(), and MissionLaunch().
GetUser()
BiosUser BiosUserManager::GetUser (string user_id) inline private
Definition at line 383 of file biosusermanager.c.
    {
        array<ref BiosUser> user_list = new array<ref BiosUser>;
        GetUserList( user_list );
        foreach( BiosUser user : user_list )
        {
            if( user.GetUid() == user_id )
            {
                return user;
            }
        }
        return null;
    }
References GetUserList().
GetUserDatabaseIdAsync()
proto native EBiosError BiosUserManager::GetUserDatabaseIdAsync () private
Call async function to get database ID.
Returns
EBiosError indicating if the async operation is pending. If active user is not set, then return NOT_FOUND
Referenced by OnLoginTimeEvent(), and SelectGamepad().
GetUserList()
proto native EBiosError BiosUserManager::GetUserList (array< ref BiosUser > user_list) private
Gets the currently present list of users.
Fills in the array. Expected errors: BAD_PARAMETER - user_list is NULL,
Returns
EBiosError indicating if the operation is done.
Referenced by OnlineServices::GetClientServices(), and GetUser().
LogOnUserAsync()
proto native EBiosError BiosUserManager::LogOnUserAsync (BiosUser user) private
Display a system dependant ui for log-on.
Referenced by OnPartyHost(), and SelectUser().
OnGameNameChanged()
void BiosUserManager::OnGameNameChanged (BiosUser user) inline private
Callback function.
Called when display info of a signed in user changed.
Parameters
user the user affected by the change.
Definition at line 368 of file biosusermanager.c.
    {
        if( user == GetSelectedUser() )
        {
            g_Game.SetPlayerName( user.GetName() );
            #ifdef PLATFORM_CONSOLE
                g_Game.SetPlayerGameName( user.GetName() );
            #endif
            if( GetGame().GetUIManager().GetMenu() )
            {
                GetGame().GetUIManager().GetMenu().Refresh();
            }
        }
    }
References g_Game, GetGame(), UIManager::GetMenu(), BiosUser::GetName(), GetSelectedUser(), CGame::GetUIManager(), and UIScriptedMenu::Refresh().
Referenced by OnUserPicked().
OnJoin()
void BiosUserManager::OnJoin (EBiosJoinType type, BiosUser joiner, string handle, string joinee, EBiosError error) inline private
Callback function.
Called when a join is parsed or when a runtime join is accepted from the system UI.
Parameters
type the type of join. Undefined on error.
joiner the user that is joining. NULL on error.
handle join handle for a session. Empty on error.
joinee uid of the user that is being joined. Empty on error.
error indicating if parsing failed. OK if not a result of ParseJoinAsync.
Definition at line 268 of file biosusermanager.c.
    {
        if ( !OnlineServices.ErrorCaught( error ) )
        {
            OnlineServices.SetBiosUser( joiner );
            SelectUserEx( joiner );
            OnlineServices.SetSessionHandle( handle );
            if ( g_Game.GetGameState() == DayZGameState.IN_GAME )
            {
                g_Game.SetLoadState( DayZLoadState.JOIN_START );
                OnlineServices.GetSession();
            }
            else
            {
                if ( GetGame().GetUIManager() && GetGame().GetInput().IsActiveGamepadSelected() )
                {
                    GetGame().GetUIManager().CloseMenu( MENU_TITLE_SCREEN );
                    GetGame().GetInput().IdentifyGamepad( GamepadButton.BUTTON_NONE );
                }
                g_Game.SetLoadState( DayZLoadState.JOIN_START );
                g_Game.GamepadCheck();
            }
        }
        else
        {
            if ( g_Game.GetGameState() != DayZGameState.IN_GAME )
            {
                if ( GetGame().GetMission() )
                {
                    if ( g_Game.GetGameState() != DayZGameState.MAIN_MENU )
                    {
                        GetGame().GetUIManager().CloseAllSubmenus();
                        GetGame().GetMission().AbortMission();
                        if (g_Game.GetGameState() == DayZGameState.JOIN)
                            NotificationSystem.AddNotification(NotificationType.JOIN_FAIL_GET_SESSION, 6);
                        g_Game.SetGameState( DayZGameState.MAIN_MENU );
                        g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
                        g_Game.GamepadCheck();
                        return;
                    }
                }
                else
                {
                    g_Game.MainMenuLaunch();
                }
            }
            NotificationSystem.AddNotification( NotificationType.JOIN_FAIL_GET_SESSION, 6 );
        }
    }
References Mission::AbortMission(), NotificationSystem::AddNotification(), UIManager::CloseAllSubmenus(), UIManager::CloseMenu(), OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), GetInput(), CGame::GetMission(), OnlineServices::GetSession(), CGame::GetUIManager(), Input::IdentifyGamepad(), MENU_TITLE_SCREEN, SelectUserEx(), OnlineServices::SetBiosUser(), and OnlineServices::SetSessionHandle().
OnLoggedOff()
void BiosUserManager::OnLoggedOff (BiosUser user) inline private
Callback function.
Definition at line 196 of file biosusermanager.c.
    {
        OnSignedOut( user );
    }
References OnSignedOut().
OnLoggedOn()
void BiosUserManager::OnLoggedOn (BiosUser user) inline private
Callback function.
Definition at line 189 of file biosusermanager.c.
    {
        if ( user && GetSelectedUser() == user )
            g_Game.SelectUser(GetGame().GetInput().GetUserGamepad(user));
    }
References g_Game, GetGame(), GetInput(), and GetSelectedUser().
OnPartyHost()
void BiosUserManager::OnPartyHost (BiosUser host, array< string > invitee_list, EBiosError error) inline private
Callback function.
Called when a party is parsed or when a party is hosted from the system UI.
Parameters
host the user that is hosting the party. NULL on error.
invitee_list list of party members.
error indicating if parsing failed. OK if not a result of ParsePartyAsync.
Definition at line 328 of file biosusermanager.c.
    {
        #ifdef PLATFORM_PS4
        if( host && host.IsOnline() )
        #endif
        {
            SelectUserEx(host);
        }
        #ifdef PLATFORM_PS4
        else if( host )
        {
            SelectUserEx( host );
            LogOnUserAsync( host );
        }
        #endif
        if (GetGame().GetUIManager())
        {
            GetGame().GetUIManager().CloseMenu(MENU_TITLE_SCREEN);
        }
        OnlineServices.SetPendingInviteList( invitee_list );
        if(g_Game.GetGameState() != DayZGameState.IN_GAME && g_Game.GetGameState() != DayZGameState.CONNECTING)
        {
            if (!GetGame().GetUIManager().GetMenu() || GetGame().GetUIManager().GetMenu().GetID() != MENU_MAIN)
            {
                GetGame().GetUIManager().EnterScriptedMenu(MENU_MAIN, GetGame().GetUIManager().GetMenu());
            }
            g_Game.SetGameState( DayZGameState.PARTY );
            g_Game.SetLoadState( DayZLoadState.PARTY_START );
            g_Game.GamepadCheck();
        }
    }
References UIManager::CloseMenu(), UIManager::EnterScriptedMenu(), g_Game, GetGame(), GetID(), CGame::GetUIManager(), BiosUser::IsOnline(), LogOnUserAsync(), MENU_MAIN, MENU_TITLE_SCREEN, SelectUserEx(), and OnlineServices::SetPendingInviteList().
OnSignedIn()
void BiosUserManager::OnSignedIn (BiosUser user) inline private
Callback function.
Called when a new user signed in
Parameters
user the user that signed in. Cannot be NULL.
Definition at line 207 of file biosusermanager.c.
    {
    }
OnSignedOut()
void BiosUserManager::OnSignedOut (BiosUser user) inline private
Callback function.
Called when a new user signed out
Parameters
user the user that signed out. Cannot be NULL.
Definition at line 218 of file biosusermanager.c.
    {
        Print("OnSignedOut(): selectedUser: " + GetSelectedUser());
        bool isSelectedUser  = (GetSelectedUser() != null);
        if ( user == GetSelectedUser() )
        {
            SelectUserEx( null );
            if (GetGame().GetUIManager())
            {
                GetGame().GetUIManager().CloseAllSubmenus();
                if ( GetGame().GetUIManager().IsDialogVisible() )
                {
                    GetGame().GetUIManager().CloseDialog();
                }
                g_Game.DeleteGamepadDisconnectMenu();
            }
            if ( GetGame().GetMission() != null )
            {
                Print("OnSignedOut(): AbortMission");
                GetGame().GetMission().AbortMission();
                GetGame().AbortMission();
            }
            GetGame().GetInput().ResetActiveGamepad();
            g_Game.SetGameState( DayZGameState.MAIN_MENU );
            g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
            g_Game.GamepadCheck();
        }
        else if ( !isSelectedUser )
        {
            Print("OnSignedOut(): before TitleScreen");
        }
    }
References Mission::AbortMission(), CGame::AbortMission(), UIManager::CloseAllSubmenus(), UIManager::CloseDialog(), g_Game, GetGame(), CGame::GetInput(), CGame::GetMission(), GetSelectedUser(), CGame::GetUIManager(), Print(), Input::ResetActiveGamepad(), and SelectUserEx().
Referenced by OnLoggedOff().
OnUserDatabaseId()
void BiosUserManager::OnUserDatabaseId (string dbID, EBiosError error) inline private
Callback function.
Parameters
dbID user database ID. If something went wrong, then it is empty string.
error indicating correct state.
Definition at line 125 of file biosusermanager.c.
    {
        if( !OnlineServices.ErrorCaught( error ) )
        {
            g_Game.SetDatabaseID( dbID );
        }
    }
References OnlineServices::ErrorCaught(), and g_Game.
OnUserLoggedOn()
void BiosUserManager::OnUserLoggedOn (EBiosError error) inline private
Callback function.
Parameters
error error indicating success or fail of the async operation.
Definition at line 137 of file biosusermanager.c.
    {
        if( OnlineServices.ErrorCaught( error ) )
        {
            if (GetGame().GetUIManager())
            {
                GetGame().GetUIManager().CloseAllSubmenus();
                if ( GetGame().GetUIManager().IsDialogVisible() )
                {
                    GetGame().GetUIManager().CloseDialog();
                }
                g_Game.DeleteGamepadDisconnectMenu();
            }
            if ( GetGame().GetMission() != null )
            {
                GetGame().GetMission().AbortMission();
            }
            GetGame().GetInput().ResetActiveGamepad();
            g_Game.SetGameState( DayZGameState.MAIN_MENU );
            g_Game.SetLoadState( DayZLoadState.MAIN_MENU_START );
            g_Game.GamepadCheck();
        }
    }
References Mission::AbortMission(), UIManager::CloseAllSubmenus(), UIManager::CloseDialog(), OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), CGame::GetMission(), CGame::GetUIManager(), and Input::ResetActiveGamepad().
OnUserPicked()
void BiosUserManager::OnUserPicked (BiosUser user, EBiosError error) inline private
Callback function.
Parameters
user picked user. NULL on fail.
error error indicating success or fail of the async operation.
Definition at line 171 of file biosusermanager.c.
    {
        if ( !user )
        {
            GetGame().GetInput().ResetActiveGamepad();
            g_Game.GamepadCheck();
        }
        else if ( !OnlineServices.ErrorCaught( error ) )
        {
            SelectUserEx( user );
            if ( GetGame().GetMission() )
                GetGame().GetMission().Reset();
            OnGameNameChanged( user );
            g_Game.SelectUser(GetGame().GetInput().GetUserGamepad(user));
        }
    }
References OnlineServices::ErrorCaught(), g_Game, GetGame(), CGame::GetInput(), GetInput(), CGame::GetMission(), OnGameNameChanged(), Mission::Reset(), Input::ResetActiveGamepad(), and SelectUserEx().
ParseJoinAsync()
proto native EBiosError BiosUserManager::ParseJoinAsync (string join_data) private
Parse the join data from from command line parameters.
The async result is returned in the OnJoin callback. The OnJoin callback is called also during runtime when a join is accepted. Expected errors: BAD_PARAMETER - join_data could not be parsed,
Parameters
join_data the startup join data from command line parameters.
Returns
EBiosError indicating if the async operation is pending.
Referenced by JoinLaunch().
ParsePartyAsync()
proto native EBiosError BiosUserManager::ParsePartyAsync (string party_data) private
Parse the party data from from command line parameters.
The async result is returned in the OnPartyHost callback. The OnPartyHost callback is called also during runtime when a player hosts a game for the party. Expected errors: BAD_PARAMETER - join_data could not be parsed,
Parameters
party_data the startup party data from command line parameters.
Returns
EBiosError indicating if the async operation is pending.
Referenced by PartyLaunch().
PickUserAsync()
proto native EBiosError BiosUserManager::PickUserAsync () private
Display a system dependant account picket.
Xbox: The async result is returned in the OnUserPicked callback.
Returns
EBiosError indicating if the async operation is pending.
Referenced by SelectUser().
SelectUser()
proto native void BiosUserManager::SelectUser (BiosUser user) private
Informs the engine about the current selected user.
Must be called to ensure proper authentication etc.
Parameters
user the user to select.
Referenced by SelectUserEx().
SelectUserEx()
void BiosUserManager::SelectUserEx (BiosUser user) inline private
Definition at line 90 of file biosusermanager.c.
    {
        BiosUser selectedUser = GetSelectedUser();
        if (selectedUser && selectedUser != user && g_Game.GetGameState() != DayZGameState.MAIN_MENU)
        {
            SelectUser(user);
            if ( GetGame().GetMission() )
            {
                GetGame().GetMission().AbortMission();
                if ( g_Game.GetGameState() == DayZGameState.JOIN )
                    NotificationSystem.AddNotification( NotificationType.JOIN_FAIL_GET_SESSION, 6 );
                g_Game.SetGameState( DayZGameState.MAIN_MENU );
                g_Game.SetLoadState( DayZLoadState.MAIN_MENU_CONTROLLER_SELECT );
                g_Game.GamepadCheck();
                g_Game.DeleteGamepadDisconnectMenu();
            }
            else
            {
                g_Game.MainMenuLaunch();
            }
        }
        else
            SelectUser(user);
    }
References Mission::AbortMission(), NotificationSystem::AddNotification(), g_Game, GetGame(), CGame::GetMission(), GetSelectedUser(), and SelectUser().
Referenced by UIScriptedMenu::ChangeAccount(), ConnectLaunch(), DisconnectSessionScript(), MissionLaunch(), BiosSessionService::OnGetSessionError(), OnJoin(), OnPartyHost(), OnSignedOut(), OnUserPicked(), SelectUser(), and BiosSessionService::TryGetSession().