DayzKode: array< ref CallQueueContext > Class Reference
array< ref CallQueueContext > Class Reference
Tools
CallQueue Class provide "lazy" calls - when we don't want to execute function immediately but later during frame update (used mainly in UI)
usage:
Private Member Functions
void Call (Class obj, string fn_name, Param params=NULL)
Creates new call request, add it on queue and execute during frame update (depends on call category)
void CallQueue ()
void RemoveCalls (Class obj)
Removes all queued calls for object (call this function when object is going to be deleted)
void Tick ()
System function, don't call it.
Private Attributes
private bool m_processing
Detailed Description
CallQueue Class provide "lazy" calls - when we don't want to execute function immediately but later during frame update (used mainly in UI)
usage:
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Refresh"); // calls "Refresh" function on "this" with no arguments
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "Show", new Param1<bool>(true)); // calls "Show" function on "this" with one bool argument
GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(this, "SetPos", new Param2<float, float>(0.2, 0.5)); // calls "SetPos" function on "this" with two float arguments
Definition at line 66 of file tools.c.
Member Function Documentation
Call()
void array< ref CallQueueContext >::Call (Class obj, string fn_name, Param params = NULL) inline private
Creates new call request, add it on queue and execute during frame update (depends on call category)
Parameters
obj target object on which function will be executed
fn_name name of function (on object "obj") which will be executed
params function arguments see Param for usage, default NULL (no arguments)
Warning
When object "obj" is deleted prior call execution, don't forget to remove calls for this object with RemoveCalls
Definition at line 108 of file tools.c.
    {
        Insert(new CallQueueContext(obj, fn_name, params));
    }
CallQueue()
void array< ref CallQueueContext >::CallQueue () inline private
Definition at line 70 of file tools.c.
    {
        m_processing = false;
    }
RemoveCalls()
void array< ref CallQueueContext >::RemoveCalls (Class obj) inline private
Removes all queued calls for object (call this function when object is going to be deleted)
Parameters
obj object for which you want remove all "lazy" calls
Definition at line 118 of file tools.c.
    {
        if (Count())
        {
            for (int i = Count() - 1; i >= 0; i--)
            {
                CallQueueContext ctx = Get(i);
                if (ctx.m_target == obj)
                {
                    ctx.Invalidate();
                }
            }
        }
    }
References Count, Get(), CallQueueContext::Invalidate(), and CallQueueContext::m_target.
Tick()
void array< ref CallQueueContext >::Tick () inline private
System function, don't call it.
Definition at line 78 of file tools.c.
    {
        if (m_processing) return;
        m_processing = true;
        while(Count() > 0)
        {
            CallQueueContext ctx = Get(0);
            if (!ctx.IsValid())
            {
                Remove(0);
            }
            else
            {
                Remove(0);
                ctx.Call();
            }
        }
        m_processing = false;
    }
References CallQueueContext::Call(), Count, Get(), CallQueueContext::IsValid(), and Remove().
Member Data Documentation
m_processing
private bool array< ref CallQueueContext >::m_processing private
Definition at line 68 of file tools.c.