DayzKode: Link< Class T > Class Reference
Link< Class T > Class Reference
Private Member Functions
proto private native Object Get ()
proto private native void Init (T init)
bool IsNull ()
void Link (T init)
T Ptr ()
void Release ()
Detailed Description
Definition at line 361 of file proto.c.
Constructor & Destructor Documentation
Link()
void Link< Class T >::Link (T init) inline private
Definition at line 372 of file proto.c.
    {
        Init(init);
    }
References Init(), and init.
Member Function Documentation
Get()
proto private native Object Link< Class T >::Get () private
Init()
proto private native void Link< Class T >::Init (T init) private
IsNull()
bool Link< Class T >::IsNull () inline private
Definition at line 382 of file proto.c.
    {
        if(!Get())
            return true;
        return false;
    }
References Get().
Ptr()
T Link< Class T >::Ptr () inline private
Definition at line 377 of file proto.c.
    {
        return Get();
    }
References Get().
Release()
void Link< Class T >::Release () inline private
Definition at line 366 of file proto.c.
    {
        T obj = Get();
        if(obj)
            obj.Release();
    }
References Get().