DayzKode: CAContinuousWringClothes Class Reference
CAContinuousWringClothes Class Reference
Private Member Functions
void CAContinuousWringClothes (float quantity_used_per_second, float time_to_repeat)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_InitItemQuantity
protected float m_SpentQuantityTotal
Detailed Description
Definition at line 1 of file cacontinuouswringclothes.c.
Constructor & Destructor Documentation
CAContinuousWringClothes()
void CAContinuousWringClothes::CAContinuousWringClothes (float quantity_used_per_second, float time_to_repeat) inline private
Definition at line 6 of file cacontinuouswringclothes.c.
    {
        m_QuantityUsedPerSecond = quantity_used_per_second;
        m_DefaultTimeToRepeat = time_to_repeat;
        m_InitItemQuantity = -1;
    }
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, and CAContinuousQuantityRepeat::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int CAContinuousWringClothes::Execute (ActionData action_data) inline private
Definition at line 24 of file cacontinuouswringclothes.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        float wetness = action_data.m_MainItem.GetWet();
        int trim_wetness = wetness * 100;
        float rounded_wetness = trim_wetness/100;
        if ( rounded_wetness <= 0.25 )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_SpentQuantityTotal < m_InitItemQuantity )
            {
                m_AdjustedQuantityUsedPerSecond = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( m_QuantityUsedPerSecond, m_Action.GetSpecialtyWeight(), true);
                m_SpentQuantity += m_AdjustedQuantityUsedPerSecond * action_data.m_Player.GetDeltaT();
                m_TimeElpased += action_data.m_Player.GetDeltaT();
                if (m_TimeElpased > m_DefaultTimeToRepeat)
                {
                    OnCompletePogress(action_data);
                    m_TimeElpased -= m_DefaultTimeToRepeat;
                }
                if ( GetGame().IsServer() )
                {
                    if ( m_SpentUnits )
                    {
                        m_SpentUnits.param1 = m_SpentQuantity;
                        SetACData(m_SpentUnits);
                    }
                    action_data.m_MainItem.AddWet(-m_SpentQuantity);
                }
                m_SpentQuantityTotal += m_SpentQuantity;
                m_SpentQuantity = 0;
                return UA_PROCESSING;
            }
            else
            {
                OnCompletePogress(action_data);
                return UA_FINISHED;
            }
        }
    }
References GetGame(), CABase::m_Action, CAContinuousQuantityRepeat::m_AdjustedQuantityUsedPerSecond, CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, CAContinuousQuantityRepeat::m_SpentQuantity, m_SpentQuantityTotal, CAContinuousQuantityRepeat::m_SpentUnits, CAContinuousQuantityRepeat::m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousWringClothes::GetProgress () inline private
Definition at line 78 of file cacontinuouswringclothes.c.
    {
        return ((m_TimeElpased - m_DefaultTimeToRepeat) / m_DefaultTimeToRepeat) + 1;
    }
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, and CAContinuousQuantityRepeat::m_TimeElpased.
Setup()
override void CAContinuousWringClothes::Setup (ActionData action_data) inline private
Definition at line 13 of file cacontinuouswringclothes.c.
    {
        super.Setup( action_data );
        if (m_InitItemQuantity < 0)
        {
            m_InitItemQuantity = action_data.m_MainItem.GetWet();
        }
    }
References m_InitItemQuantity, and ActionData::m_MainItem.
Member Data Documentation
m_InitItemQuantity
protected float CAContinuousWringClothes::m_InitItemQuantity private
Definition at line 3 of file cacontinuouswringclothes.c.
Referenced by CAContinuousWringClothes(), Execute(), and Setup().
m_SpentQuantityTotal
protected float CAContinuousWringClothes::m_SpentQuantityTotal private
Definition at line 4 of file cacontinuouswringclothes.c.
Referenced by Execute().