DayzKode: ActionCarHornLong Class Reference
ActionCarHornLong Class Reference
Private Member Functions
void ActionCarHornLong ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedInVehicle ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasProgress ()
override bool HasTarget ()
override void OnEndInput (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStart (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
special case - manually ends the action on exec event
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool UseMainItem ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 208 of file actioncarhorn.c.
Constructor & Destructor Documentation
ActionCarHornLong()
void ActionCarHornLong::ActionCarHornLong () inline private
Definition at line 210 of file actioncarhorn.c.
    {
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONMOD_TOOTHORN;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_ALL;
    }
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCarHornLong::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 253 of file actioncarhorn.c.
    {
        return ActionCarHornBase.ActionCondition(player);
    }
References ActionCarHornBase::ActionCondition().
CanBeUsedInVehicle()
override bool ActionCarHornLong::CanBeUsedInVehicle () inline private
Definition at line 226 of file actioncarhorn.c.
    {
        return true;
    }
CreateActionData()
override ActionData ActionCarHornLong::CreateActionData () inline private
Definition at line 247 of file actioncarhorn.c.
    {
        ActionData action_data = new CarHornActionData();
        return action_data;
    }
CreateConditionComponents()
override void ActionCarHornLong::CreateConditionComponents () inline private
Definition at line 241 of file actioncarhorn.c.
    {
        m_ConditionItem     = new CCINone();
        m_ConditionTarget   = new CCTNone();
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionCarHornLong::GetInputType () inline private
Definition at line 231 of file actioncarhorn.c.
    {
        return CarHornLongActionInput;
    }
References CarHornLongActionInput.
HandleReciveData()
override void ActionCarHornLong::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 339 of file actioncarhorn.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        CarHornActionReceiveData carHornReceivedData    = CarHornActionReceiveData.Cast(action_recive_data);
        CarHornActionData carHornData                   = CarHornActionData.Cast(action_data);
        carHornData.m_ActionNeedEnd                     = carHornReceivedData.m_ActionNeedEnd;
        carHornData.m_Car                               = carHornReceivedData.m_Car;
    }
References CarHornActionData::m_ActionNeedEnd, and CarHornActionData::m_Car.
HasProgress()
override bool ActionCarHornLong::HasProgress () inline private
Definition at line 221 of file actioncarhorn.c.
    {
        return false;
    }
HasTarget()
override bool ActionCarHornLong::HasTarget () inline private
Definition at line 216 of file actioncarhorn.c.
    {
        return false;
    }
OnEndInput()
override void ActionCarHornLong::OnEndInput (ActionData action_data) inline private
Definition at line 271 of file actioncarhorn.c.
    {
        super.OnEndInput(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.OFF);
    }
References ActionCarHornBase::SetCarHornState().
OnEndServer()
override void ActionCarHornLong::OnEndServer (ActionData action_data) inline private
Definition at line 297 of file actioncarhorn.c.
    {
        super.OnEndServer(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.OFF);
    }
References ActionCarHornBase::SetCarHornState().
OnStart()
override void ActionCarHornLong::OnStart (ActionData action_data) inline private
Definition at line 279 of file actioncarhorn.c.
    {
        super.OnStart(action_data);
        CarHornActionData carHornData   = CarHornActionData.Cast(action_data);
        carHornData.m_ActionNeedEnd     = true;
        carHornData.m_Car               = CarScript.Cast(action_data.m_Player.GetCommand_Vehicle().GetTransport());
    }
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and ActionData::m_Player.
OnStartServer()
override void ActionCarHornLong::OnStartServer (ActionData action_data) inline private
Definition at line 288 of file actioncarhorn.c.
    {
        super.OnStartServer(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        carHornData.m_ActionNeedEnd = true;
        ActionCarHornBase.SetCarHornState(carHornData, ECarHornState.LONG);
    }
References CarHornActionData::m_ActionNeedEnd, and ActionCarHornBase::SetCarHornState().
OnUpdate()
override void ActionCarHornLong::OnUpdate (ActionData action_data) inline private
special case - manually ends the action on exec event
Definition at line 259 of file actioncarhorn.c.
    {
        super.OnUpdate(action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        if (carHornData.m_ReciveEndInput && carHornData.m_ActionNeedEnd)
        {
            carHornData.m_Callback.SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            carHornData.m_ActionNeedEnd = false;
        }
    }
References CarHornActionData::m_ActionNeedEnd, ActionData::m_Callback, ActionData::m_ReciveEndInput, and ActionBaseCB::SetCommand().
ReadFromContext()
override bool ActionCarHornLong::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 315 of file actioncarhorn.c.
    {
        if (!action_recive_data)
        {
            action_recive_data = new CarHornActionReceiveData();
        }
        super.ReadFromContext(ctx, action_recive_data);
        bool needUpdate;
        if (!ctx.Read(needUpdate))
            return false;
        CarScript carScript;
        if (!ctx.Read(carScript))
            return false;
        CarHornActionReceiveData carHornReceivedData    = CarHornActionReceiveData.Cast(action_recive_data);
        carHornReceivedData.m_ActionNeedEnd             = needUpdate;
        carHornReceivedData.m_Car                       = carScript;
        return true;
    }
References Serializer::Read().
UseMainItem()
override bool ActionCarHornLong::UseMainItem () inline private
Definition at line 236 of file actioncarhorn.c.
    {
        return false;
    }
WriteToContext()
override void ActionCarHornLong::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 305 of file actioncarhorn.c.
    {
        super.WriteToContext(ctx, action_data);
        CarHornActionData carHornData = CarHornActionData.Cast(action_data);
        ctx.Write(carHornData.m_ActionNeedEnd);
        ctx.Write(carHornData.m_Car);
    }
References CarHornActionData::m_ActionNeedEnd, CarHornActionData::m_Car, and Serializer::Write().