DayzKode: FishingRod_Base_New Class Reference
FishingRod_Base_New Class Reference
Private Member Functions
void AnimateFishingRod (bool state)
void FishingRod_Base_New ()
float GetFishingEffectivityBonus ()
override bool IsOpen ()
override void SetActions ()
Detailed Description
Definition at line 1 of file fishingrod_base.c.
Constructor & Destructor Documentation
FishingRod_Base_New()
void FishingRod_Base_New::FishingRod_Base_New () inline private
Definition at line 3 of file fishingrod_base.c.
    {
    }
Member Function Documentation
AnimateFishingRod()
void FishingRod_Base_New::AnimateFishingRod (bool state) inline private
Definition at line 24 of file fishingrod_base.c.
{}
Referenced by ActionFishingNew::OnEndClient(), ActionFishingNew::OnEndServer(), ActionFishingNew::OnStartClient(), and ActionFishingNew::OnStartServer().
GetFishingEffectivityBonus()
float FishingRod_Base_New::GetFishingEffectivityBonus () inline private
Definition at line 14 of file fishingrod_base.c.
    {
        return 0.0;
    }
Referenced by ActionFishingNew::SetupAction().
IsOpen()
override bool FishingRod_Base_New::IsOpen () inline private
Definition at line 19 of file fishingrod_base.c.
    {
        return false;
    }
SetActions()
override void FishingRod_Base_New::SetActions () inline private
Definition at line 7 of file fishingrod_base.c.
    {
        super.SetActions();
        AddAction(ActionFishingNew);
    }
References AddAction().