DayzKode: CfgParam Class Reference
CfgParam Class Reference
Private Member Functions
void CfgParam (string param_name)
void CfgParamArray (string param_name)
void CfgParamType (string param_name)
void Clear ()
string GetName ()
int GetType ()
override int GetType ()
CfgParam GetValue (int i)
CfgParam GetValueByName (string name, int cfg_type)
array< ref CfgParam > GetValues ()
void InsertValue (CfgParam value)
bool IsArray ()
bool IsParamExist (string name, int cfg_type)
bool IsValueArray ()
bool RenameParam (string name, int cfg_type, string new_name)
void SetName (string param_name)
void SetParams (array< ref CfgParam > value_array)
void ~CfgParamArray ()
Static Private Member Functions
static CfgParam CreateParam (string name, int cfg_type)
Private Attributes
protected string m_ParamName
protected string m_ParamValueString
private ref array< ref CfgParam > m_Values
Detailed Description
Definition at line 8 of file cfgparam.c.
Constructor & Destructor Documentation
CfgParam()
void CfgParam::CfgParam (string param_name) inline private
Definition at line 13 of file cfgparam.c.
    {
        m_ParamName = param_name;
    }
References m_ParamName.
~CfgParamArray()
void CfgParam::~CfgParamArray () inline private
Definition at line 10 of file cfgparamarray.c.
    {
        if ( m_Values != NULL )
        {
            Clear();
        }
    }
References Clear(), and m_Values.
Member Function Documentation
CfgParamArray()
void CfgParam::CfgParamArray (string param_name) inline private
Definition at line 5 of file cfgparamarray.c.
    {
        m_Values = new array<ref CfgParam>;
    }
References m_Values.
Referenced by CreateParam().
CfgParamType()
void CfgParam::CfgParamType (string param_name) inline private
Definition at line 3 of file cfgparamtype.c.
    {
    }
Clear()
void CfgParam::Clear () inline private
Definition at line 18 of file cfgparamarray.c.
    {
        m_Values.Clear();
    }
References m_Values.
Referenced by ~CfgParamArray().
CreateParam()
static CfgParam CfgParam::CreateParam (string name, int cfg_type) inline static private
Definition at line 38 of file cfgparam.c.
    {
        CfgParam param;
        switch (cfg_type)
        {
            case CFG_TYPE_STRING:
            {
                param = new CfgParamString(name);
                break;
            }
            case CFG_TYPE_INT:
            {
                param = new CfgParamInt(name);
                break;
            }
            case CFG_TYPE_FLOAT:
            {
                param = new CfgParamFloat(name);
                break;
            }
            case CFG_TYPE_BOOL:
            {
                param = new CfgParamBool(name);
                break;
            }
            case CFG_TYPE_ARRAY:
            {
                param = new CfgParamArray(name);
                break;
            }
        }
        return param;
    }
References CFG_TYPE_ARRAY, CFG_TYPE_BOOL, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, CfgParamArray(), and name.
Referenced by PluginFileHandler::GetParamByName(), and GetValueByName().
GetName()
string CfgParam::GetName () inline private
Definition at line 23 of file cfgparam.c.
    {
        return m_ParamName;
    }
References m_ParamName.
Referenced by PluginFileHandler::GetParamByName(), GetValueByName(), IsParamExist(), PluginFileHandler::ParamExist(), PluginFileHandler::ParseParam(), PluginFileHandler::RemoveParamByName(), RenameParam(), and PluginFileHandler::RenameParam().
GetType() [1/2]
int CfgParam::GetType () inline private
Definition at line 28 of file cfgparam.c.
    {
        return -1;
    }
Referenced by PluginFileHandler::ParseParam().
GetType() [2/2]
override int CfgParam::GetType () inline private
Definition at line 117 of file cfgparamarray.c.
    {
        return CFG_TYPE_ARRAY;
    }
References CFG_TYPE_ARRAY.
GetValue()
CfgParam CfgParam::GetValue (int i) inline private
Definition at line 28 of file cfgparamarray.c.
    {
        return m_Values.Get(i);
    }
References m_Values.
GetValueByName()
CfgParam CfgParam::GetValueByName (string name, int cfg_type) inline private
Definition at line 84 of file cfgparamarray.c.
    {
        if ( m_Values == NULL )
        {
            m_Values = new array<ref CfgParam>;
        }
        for ( int i = 0; i < m_Values.Count(); ++i )
        {
            CfgParam p = m_Values.Get(i);
            if ( name == p.GetName() )
            {
                return p;
            }
        }
        CfgParam param = CreateParam(name, cfg_type);
        m_Values.Insert(param);
        return param;
    }
References CreateParam(), GetName(), m_Values, and name.
GetValues()
array< ref CfgParam > CfgParam::GetValues () inline private
Definition at line 23 of file cfgparamarray.c.
    {
        return m_Values;
    }
References m_Values.
InsertValue()
void CfgParam::InsertValue (CfgParam value) inline private
Definition at line 33 of file cfgparamarray.c.
    {
        if ( m_Values == NULL )
        {
            m_Values = new array<ref CfgParam>;
        }
        m_Values.Insert(value);
    }
References m_Values.
IsArray()
bool CfgParam::IsArray () inline private
Definition at line 33 of file cfgparam.c.
    {
        return false;
    }
IsParamExist()
bool CfgParam::IsParamExist (string name, int cfg_type) inline private
Definition at line 43 of file cfgparamarray.c.
    {
        if ( m_Values == NULL )
        {
            m_Values = new array<ref CfgParam>;
        }
        for ( int i = 0; i < m_Values.Count(); ++i )
        {
            CfgParam p = m_Values.Get(i);
            if ( name == p.GetName() )
            {
                return true;
            }
        }
        return false;
    }
References GetName(), m_Values, and name.
IsValueArray()
bool CfgParam::IsValueArray () inline private
Definition at line 112 of file cfgparamarray.c.
    {
        return true;
    }
RenameParam()
bool CfgParam::RenameParam (string name, int cfg_type, string new_name) inline private
Definition at line 63 of file cfgparamarray.c.
    {
        if ( m_Values == NULL )
        {
            m_Values = new array<ref CfgParam>;
        }
        for ( int i = 0; i < m_Values.Count(); ++i )
        {
            CfgParam p = m_Values.Get(i);
            if ( name == p.GetName() )
            {
                p.SetName(new_name);
                return true;
            }
        }
        return false;
    }
References GetName(), m_Values, name, and SetName().
SetName()
void CfgParam::SetName (string param_name) inline private
Definition at line 18 of file cfgparam.c.
    {
        m_ParamName = param_name;
    }
References m_ParamName.
Referenced by PluginFileHandler::ParseText(), RenameParam(), and PluginFileHandler::RenameParam().
SetParams()
void CfgParam::SetParams (array< ref CfgParam > value_array) inline private
Definition at line 107 of file cfgparamarray.c.
    {
        m_Values = value_array;
    }
References m_Values.
Member Data Documentation
m_ParamName
protected string CfgParam::m_ParamName private
Definition at line 10 of file cfgparam.c.
Referenced by CfgParam(), GetName(), and SetName().
m_ParamValueString
protected string CfgParam::m_ParamValueString private
Definition at line 11 of file cfgparam.c.
m_Values
private ref array<ref CfgParam> CfgParam::m_Values private
Definition at line 3 of file cfgparamarray.c.
Referenced by GetValues().