DayzKode: HumanItemBehaviorCfg Class Reference
HumanItemBehaviorCfg Class Reference
#include <humanitems.h>
Private Member Functions
void DayzPlayerItemBehaviorCfg ()
void SetEmptyHanded ()
void SetFirearms ()
void SetHeavyItems ()
void SetIK (int pStance, int pMovement, bool pAim, bool pRArm, bool pLArm)
void SetIKAll (bool pAim, bool pRArm, bool pLArm)
void SetIKMelee (int pHitType, bool pAim, bool pRArm, bool pLArm)
void SetIKPoleArms ()
void SetIKStance (int pStance, bool pAim, bool pRArm, bool pLArm)
void SetIKTwoHanded ()
void SetPistols ()
void SetPoleArms ()
void SetRestrained ()
void SetSurrender ()
void SetToolsOneHanded ()
void SetTwoHanded ()
Private Attributes
bool m_bAttackLean
max speed of alignment when evading
bool m_bJumpAllowed
default false
private bool m_bPlaceholder
default true
float m_fMeleeEvadeHeadingFilterSpan
max speed of alignment when moving
float m_fMeleeEvadeHeadingFilterSpeed
delay of alignment when evading
float m_fMoveHeadingFilterSpan
per item camera user data - can be obtained in runtime by DayZPlayer.GetPerItemCameraUD()
float m_fMoveHeadingFilterSpeed
delay of alignment when moving in prone stance
float m_fMoveHeadingProneFilterSpan
delay of alignment when sprintinh
float m_fMoveHeadingSprintFilterSpan
default delay of alignment when moving
int m_IKSettings [24]
int m_IKSettingsMelee [2]
[stance][movement] mask for ik
int m_iPerItemCameraUserData
[inpact type] mask for ik (0 - light/1 - heavy)
int m_iStanceMask
combinations of STANCEMASK_
int m_iType
int m_StanceMovements [6]
int m_StanceRotation [6]
6 stances -> all has movement mask, STANCEIDX_ ... is index
Static Private Attributes
static int IKSETTING_AIMING = 0x1
bit mask of ik settings
static int IKSETTING_LHAND = 0x4
static int IKSETTING_RHAND = 0x2
Detailed Description
Definition at line 5 of file humanitems.h.
Member Function Documentation
DayzPlayerItemBehaviorCfg()
void HumanItemBehaviorCfg::DayzPlayerItemBehaviorCfg () inline private
per item camera user data to be uninitialized
rotational delay to camera direction in move only (filter)
Definition at line 135 of file dayzplayercfgbase.c.
    {
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ALL;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_ERECT]          = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN | DayZPlayerConstants.MOVEMENT_SPRINT;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_CROUCH]         = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_SPRINT;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_PRONE]          = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDERECT]    = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN | DayZPlayerConstants.MOVEMENT_SPRINT;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDCROUCH]   = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDPRONE]    = DayZPlayerConstants.MOVEMENT_IDLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_ERECT]           = DayZPlayerConstants.ROTATION_ENABLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_CROUCH]          = DayZPlayerConstants.ROTATION_ENABLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_PRONE]           = DayZPlayerConstants.ROTATION_ENABLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_RAISEDERECT]     = DayZPlayerConstants.ROTATION_ENABLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_RAISEDCROUCH]    = DayZPlayerConstants.ROTATION_ENABLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_RAISEDPRONE]     = DayZPlayerConstants.ROTATION_ENABLE;
        m_iPerItemCameraUserData        = DayZPlayerCameras.PERITEMUD_INVALID;
        m_fMoveHeadingFilterSpan        = CfgGameplayHandler.GetMovementRotationSpeedJog();
        m_fMoveHeadingSprintFilterSpan  = CfgGameplayHandler.GetMovementRotationSpeedSprint();
        m_fMoveHeadingProneFilterSpan   = 0.7;
        m_fMoveHeadingFilterSpeed       = Math.DEG2RAD * 360;   // 720 deg / sec
        m_fMeleeEvadeHeadingFilterSpan  = 0.07;
        m_fMeleeEvadeHeadingFilterSpeed = Math.DEG2RAD * 1440;  // 720 deg / sec
        m_bAttackLean = false;
        m_bJumpAllowed = true;
    }
References m_iStanceMask, m_StanceMovements, and m_StanceRotation.
SetEmptyHanded()
void HumanItemBehaviorCfg::SetEmptyHanded () inline private
Definition at line 227 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.EMPTYHANDED;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDERECT | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_EMPTYHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN;
        SetIKAll(false, false, false);
        m_bAttackLean = true;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_EMPTYHANDED, and SetIKAll().
SetFirearms()
void HumanItemBehaviorCfg::SetFirearms () inline private
Definition at line 212 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.FIREARMS;
        SetIKStance(DayZPlayerConstants.STANCEIDX_ERECT, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_CROUCH, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_PRONE, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT, true, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDCROUCH, true, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDPRONE, true, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_LIGHT, false, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_HEAVY, false, true, true);
    }
References m_iType, SetIKMelee(), and SetIKStance().
SetHeavyItems()
void HumanItemBehaviorCfg::SetHeavyItems () inline private
Definition at line 303 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.HEAVY;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_ERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_TWOHANDED;
        SetIKAll(false, true, true);
        m_bAttackLean = true;
        m_bJumpAllowed = false;
    }
References m_bAttackLean, m_bJumpAllowed, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKAll().
SetIK()
void HumanItemBehaviorCfg::SetIK (int pStance, int pMovement, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 44 of file humanitems.h.
    {
        int val = 0;
        if (pAim)   val |=  IKSETTING_AIMING;
        if (pRArm)  val |=  IKSETTING_RHAND;
        if (pLArm)  val |=  IKSETTING_LHAND;
        // Print("Setting ik " + pStance.ToString() + "," +   pMovement.ToString() );
        pStance = pStance * 4;
        pStance = pStance + pMovement;
        // Print("Setting ik " + pStance.ToString() + " to value " +   val.ToString() );
        m_IKSettings[pStance] = val;
    }
References IKSETTING_AIMING, IKSETTING_LHAND, and IKSETTING_RHAND.
Referenced by SetPistols().
SetIKAll()
void HumanItemBehaviorCfg::SetIKAll (bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 84 of file humanitems.h.
    {
        int val = 0;
        if (pAim)   val |=  IKSETTING_AIMING;
        if (pRArm)  val |=  IKSETTING_RHAND;
        if (pLArm)  val |=  IKSETTING_LHAND;
        int i;
        for (i = 0; i < 24; i++)
        {
            m_IKSettings[i] = val;
        }
        for (i = 0; i < 2; i++)
        {
            m_IKSettingsMelee[i] = val;
        }
    }
References IKSETTING_AIMING, IKSETTING_LHAND, IKSETTING_RHAND, m_IKSettings, and m_IKSettingsMelee.
Referenced by SetEmptyHanded(), SetHeavyItems(), SetRestrained(), and SetToolsOneHanded().
SetIKMelee()
void HumanItemBehaviorCfg::SetIKMelee (int pHitType, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 74 of file humanitems.h.
    {
        int val = 0;
        if (pAim)   val |=  IKSETTING_AIMING;
        if (pRArm)  val |=  IKSETTING_RHAND;
        if (pLArm)  val |=  IKSETTING_LHAND;
        m_IKSettingsMelee[pHitType] = val;
    }
Referenced by SetFirearms(), SetIKPoleArms(), SetIKTwoHanded(), and SetPistols().
SetIKPoleArms()
void HumanItemBehaviorCfg::SetIKPoleArms () inline private
Definition at line 182 of file dayzplayercfgbase.c.
    {
        SetIKStance(DayZPlayerConstants.STANCEIDX_ERECT, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_CROUCH, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_PRONE, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDCROUCH, false, false, false);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDPRONE, false, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_LIGHT, false, false, false);
        SetIKMelee(DayZPlayerConstants.MELEE_HEAVY, false, false, false);
    }
References SetIKMelee(), and SetIKStance().
Referenced by SetPoleArms().
SetIKStance()
void HumanItemBehaviorCfg::SetIKStance (int pStance, bool pAim, bool pRArm, bool pLArm) inline private
Definition at line 59 of file humanitems.h.
    {
        int val = 0;
        if (pAim)   val |=  IKSETTING_AIMING;
        if (pRArm)  val |=  IKSETTING_RHAND;
        if (pLArm)  val |=  IKSETTING_LHAND;
        int bo = pStance * 4;
        for (int i = 0; i < 4; i++)
        {
            m_IKSettings[bo+i] = val;
        }
    }
References IKSETTING_AIMING, IKSETTING_LHAND, and IKSETTING_RHAND.
Referenced by SetFirearms(), SetIKPoleArms(), SetIKTwoHanded(), and SetPistols().
SetIKTwoHanded()
void HumanItemBehaviorCfg::SetIKTwoHanded () inline private
Definition at line 169 of file dayzplayercfgbase.c.
    {
        SetIKStance(DayZPlayerConstants.STANCEIDX_ERECT, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_CROUCH, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_PRONE, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT, false, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDCROUCH, false, false, false);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDPRONE, false, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_LIGHT, false, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_HEAVY, false, true, true);
    }
References SetIKMelee(), and SetIKStance().
Referenced by SetTwoHanded().
SetPistols()
void HumanItemBehaviorCfg::SetPistols () inline private
Definition at line 195 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.PISTOLS;
        SetIKStance(DayZPlayerConstants.STANCEIDX_ERECT, false, true, false);
        SetIKStance(DayZPlayerConstants.STANCEIDX_CROUCH, false, true, false);
        SetIKStance(DayZPlayerConstants.STANCEIDX_PRONE, false, true, false);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT, true, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDCROUCH, true, true, true);
        SetIKStance(DayZPlayerConstants.STANCEIDX_RAISEDPRONE, true, true, true);
        SetIK(DayZPlayerConstants.STANCEIDX_RAISEDERECT, DayZPlayerConstants.MOVEMENTIDX_SPRINT, false, true, false);
        SetIKMelee(DayZPlayerConstants.MELEE_LIGHT, false, true, true);
        SetIKMelee(DayZPlayerConstants.MELEE_HEAVY, false, true, true);
    }
References m_iType, SetIK(), SetIKMelee(), and SetIKStance().
SetPoleArms()
void HumanItemBehaviorCfg::SetPoleArms () inline private
Definition at line 317 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.POLEARMS;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDERECT | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_TWOHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN;
        SetIKPoleArms();
        m_bAttackLean = true;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKPoleArms().
SetRestrained()
void HumanItemBehaviorCfg::SetRestrained () inline private
Definition at line 269 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.EMPTYHANDED;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_ONEHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_ERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_SPRINT;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_CROUCH] = DayZPlayerConstants.MOVEMENT_IDLE  | DayZPlayerConstants.MOVEMENT_WALK;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_PRONE] = DayZPlayerConstants.MOVEMENT_IDLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_PRONE] = DayZPlayerConstants.ROTATION_DISABLE;
        SetIKAll(false, true, true);
        m_bAttackLean = false;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, m_StanceRotation, DayZPlayerCameras::PERITEMUD_ONEHANDED, and SetIKAll().
SetSurrender()
void HumanItemBehaviorCfg::SetSurrender () inline private
Definition at line 287 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.EMPTYHANDED;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_EMPTYHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_ERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_CROUCH] = DayZPlayerConstants.MOVEMENT_IDLE;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_PRONE] = DayZPlayerConstants.MOVEMENT_IDLE;
        m_StanceRotation[DayZPlayerConstants.STANCEIDX_PRONE] = DayZPlayerConstants.ROTATION_DISABLE;
        m_bAttackLean = false;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, m_StanceRotation, and DayZPlayerCameras::PERITEMUD_EMPTYHANDED.
SetToolsOneHanded()
void HumanItemBehaviorCfg::SetToolsOneHanded () inline private
Definition at line 255 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.ONEHANDED;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDERECT | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_ONEHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN;
        SetIKAll(false, true, false);
        m_bAttackLean = true;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_ONEHANDED, and SetIKAll().
SetTwoHanded()
void HumanItemBehaviorCfg::SetTwoHanded () inline private
Definition at line 241 of file dayzplayercfgbase.c.
    {
        m_iType = ItemBehaviorType.TWOHANDED;
        m_iStanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_RAISEDERECT | DayZPlayerConstants.STANCEMASK_RAISEDPRONE;
        m_iPerItemCameraUserData = DayZPlayerCameras.PERITEMUD_TWOHANDED;
        m_StanceMovements[DayZPlayerConstants.STANCEIDX_RAISEDERECT] = DayZPlayerConstants.MOVEMENT_IDLE | DayZPlayerConstants.MOVEMENT_WALK | DayZPlayerConstants.MOVEMENT_RUN;
        SetIKTwoHanded();
        m_bAttackLean = true;
    }
References m_bAttackLean, m_iPerItemCameraUserData, m_iStanceMask, m_iType, m_StanceMovements, DayZPlayerCameras::PERITEMUD_TWOHANDED, and SetIKTwoHanded().
Member Data Documentation
IKSETTING_AIMING
int HumanItemBehaviorCfg::IKSETTING_AIMING = 0x1 static private
bit mask of ik settings
Definition at line 11 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
IKSETTING_LHAND
int HumanItemBehaviorCfg::IKSETTING_LHAND = 0x4 static private
Definition at line 13 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
IKSETTING_RHAND
int HumanItemBehaviorCfg::IKSETTING_RHAND = 0x2 static private
Definition at line 12 of file humanitems.h.
Referenced by SetIK(), SetIKAll(), and SetIKStance().
m_bAttackLean
bool HumanItemBehaviorCfg::m_bAttackLean private
max speed of alignment when evading
per weapon lean forward
Definition at line 36 of file humanitems.h.
m_bJumpAllowed
bool HumanItemBehaviorCfg::m_bJumpAllowed private
default false
per weapon lean forward
Definition at line 39 of file humanitems.h.
Referenced by CanClimb(), and CanJump().
m_bPlaceholder
private bool HumanItemBehaviorCfg::m_bPlaceholder private
default true
Definition at line 41 of file humanitems.h.
m_fMeleeEvadeHeadingFilterSpan
float HumanItemBehaviorCfg::m_fMeleeEvadeHeadingFilterSpan private
max speed of alignment when moving
evade caps
Definition at line 31 of file humanitems.h.
m_fMeleeEvadeHeadingFilterSpeed
float HumanItemBehaviorCfg::m_fMeleeEvadeHeadingFilterSpeed private
delay of alignment when evading
Definition at line 32 of file humanitems.h.
m_fMoveHeadingFilterSpan
float HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan private
per item camera user data - can be obtained in runtime by DayZPlayer.GetPerItemCameraUD()
movement caps
Definition at line 25 of file humanitems.h.
m_fMoveHeadingFilterSpeed
float HumanItemBehaviorCfg::m_fMoveHeadingFilterSpeed private
delay of alignment when moving in prone stance
Definition at line 28 of file humanitems.h.
m_fMoveHeadingProneFilterSpan
float HumanItemBehaviorCfg::m_fMoveHeadingProneFilterSpan private
delay of alignment when sprintinh
Definition at line 27 of file humanitems.h.
m_fMoveHeadingSprintFilterSpan
float HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan private
default delay of alignment when moving
Definition at line 26 of file humanitems.h.
m_IKSettings
int HumanItemBehaviorCfg::m_IKSettings[24] private
Definition at line 20 of file humanitems.h.
Referenced by SetIKAll(), and SetIKMelee().
m_IKSettingsMelee
int HumanItemBehaviorCfg::m_IKSettingsMelee[2] private
[stance][movement] mask for ik
Definition at line 21 of file humanitems.h.
Referenced by SetIKAll().
m_iPerItemCameraUserData
int HumanItemBehaviorCfg::m_iPerItemCameraUserData private
[inpact type] mask for ik (0 - light/1 - heavy)
Definition at line 22 of file humanitems.h.
m_iStanceMask
int HumanItemBehaviorCfg::m_iStanceMask private
combinations of STANCEMASK_
Definition at line 17 of file humanitems.h.
m_iType
int HumanItemBehaviorCfg::m_iType private
Definition at line 15 of file humanitems.h.
Referenced by DayZPlayerImplementThrowing::CanChangeThrowingStance(), DayZPlayerImplementThrowing::CanContinueThrowing(), and DayZPlayerImplementThrowing::HandleThrowing().
m_StanceMovements
int HumanItemBehaviorCfg::m_StanceMovements[6] private
Definition at line 18 of file humanitems.h.
m_StanceRotation
int HumanItemBehaviorCfg::m_StanceRotation[6] private
6 stances -> all has movement mask, STANCEIDX_ ... is index
Definition at line 19 of file humanitems.h.
Referenced by HeadingModel().