DayzKode: ItemPreviewWidget Class Reference
ItemPreviewWidget Class Reference
Private Member Functions
proto native EntityAI GetItem ()
proto native vector GetModelOrientation ()
proto native vector GetModelPosition ()
proto native int GetView ()
proto native void SetForceFlip (bool value)
proto native void SetForceFlipEnable (bool enable)
proto native void SetItem (EntityAI object)
proto native void SetModelOrientation (vector vOrientation)
proto native void SetModelPosition (vector vPos)
proto native void SetView (int viewIndex)
Detailed Description
Definition at line 272 of file gameplay.c.
Member Function Documentation
GetItem()
proto native EntityAI ItemPreviewWidget::GetItem () private
Referenced by ScriptedWidgetEventHandler::AddItem(), Icon::Combine(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), PlayerContainer::DraggingOver(), DraggingOverCenterPanel(), Icon::DraggingOverCombine(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), PlayerContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), Icon::DropReceivedFromMain(), AttachmentCategoriesSlotsContainer::GetFocusedItem(), HandsContainer::GetItemPreviewItem(), AttachmentCategoriesRow::GetItemPreviewItem(), ClosableContainer::GetItemPreviewItem(), VicinitySlotsContainer::MouseButtonDown(), VicinitySlotsContainer::MouseClick(), HandsContainer::MouseClick2(), OnCenterPanelDropReceived(), ScriptedWidgetEventHandler::OnDrag(), ScriptedWidgetEventHandler::OnDrop(), PlayerContainer::OnDropReceivedFromGhostArea(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), PlayerContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), HandsArea::OnHandsPanelDropReceived(), InventoryGridController::OnItemDraggingOver(), InventoryGridController::OnItemDropReceived(), OnRightPanelDropReceived(), ScriptedWidgetEventHandler::SetItem(), Icon::Swap(), and PlayerContainer::ToggleWidget().
GetModelOrientation()
proto native vector ItemPreviewWidget::GetModelOrientation () private
GetModelPosition()
proto native vector ItemPreviewWidget::GetModelPosition () private
GetView()
proto native int ItemPreviewWidget::GetView () private
SetForceFlip()
proto native void ItemPreviewWidget::SetForceFlip (bool value) private
Referenced by Icon::DestroyWhiteBackground(), Icon::InitEx(), Icon::InitLock(), and SlotsIcon::SlotsIcon().
SetForceFlipEnable()
proto native void ItemPreviewWidget::SetForceFlipEnable (bool enable) private
Referenced by Icon::CreateWhiteBackground(), Icon::DestroyWhiteBackground(), Icon::InitEx(), Icon::InitLock(), SlotsIcon::OnIconDrag(), SlotsIcon::OnIconDrop(), and SlotsIcon::SlotsIcon().
SetItem()
proto native void ItemPreviewWidget::SetItem (EntityAI object) private
Referenced by ScriptedWidgetEventHandler::AddItem(), SlotsIcon::Clear(), ClearWidgets(), DisplayAll(), UIScriptedMenu::OnClick(), ClosableHeader::OnDragHeader(), ClosableHeader::OnDropHeader(), ItemManager::PrepareTooltip(), UIScriptedMenu::SetItem(), ScriptedWidgetEventHandler::SetItem(), SlotsIcon::SetItemPreview(), Header::SetItemPreview(), Icon::SetItemPreviewEx(), UIScriptedMenu::SetPreviewObject(), and UIScriptedMenu::UpdateQuickbarItemCard().
SetModelOrientation()
proto native void ItemPreviewWidget::SetModelOrientation (vector vOrientation) private
Referenced by ScriptedWidgetEventHandler::AddItem(), ScriptedWidgetEventHandler::SetItem(), SlotsIcon::SetItemPreview(), Icon::SetItemPreviewEx(), UIScriptedMenu::UpdateQuickbarItemCard(), and UIScriptedMenu::UpdateRotation().
SetModelPosition()
proto native void ItemPreviewWidget::SetModelPosition (vector vPos) private
Referenced by UIScriptedMenu::SetItem().
SetView()
proto native void ItemPreviewWidget::SetView (int viewIndex) private
0 - default boundingbox_min + boundingbox_max + invView 1 - boundingbox_min2 + boundingbox_max2 + invView2 2 - boundingbox_min3 + boundingbox_max3 + invView3 ...
Referenced by ScriptedWidgetEventHandler::AddItem(), ScriptedWidgetEventHandler::OnDrag(), ClosableHeader::OnDragHeader(), ScriptedWidgetEventHandler::OnDrop(), ItemManager::PrepareTooltip(), UIScriptedMenu::SetItem(), ScriptedWidgetEventHandler::SetItem(), SlotsIcon::SetItemPreview(), Header::SetItemPreview(), Icon::SetItemPreviewEx(), and UIScriptedMenu::UpdateQuickbarItemCard().