DayzKode: CCTWaterSurface Class Reference
CCTWaterSurface Class Reference
Private Member Functions
override bool Can (PlayerBase player, ActionTarget target)
override bool CanContinue (PlayerBase player, ActionTarget target)
void CCTWaterSurface (float maximal_target_distance=UAMaxDistances.DEFAULT, string surfaceType="")
Private Attributes
protected float m_MaximalActionDistanceSq
protected string m_SurfaceType
Detailed Description
Definition at line 1 of file cctwatersurface.c.
Constructor & Destructor Documentation
CCTWaterSurface()
void CCTWaterSurface::CCTWaterSurface (float maximal_target_distance = UAMaxDistances.DEFAULT, string surfaceType = "") inline private
Definition at line 6 of file cctwatersurface.c.
    {
        m_MaximalActionDistanceSq = maximal_target_distance * maximal_target_distance;
        m_SurfaceType = surfaceType;
    }
References m_MaximalActionDistanceSq, and m_SurfaceType.
Member Function Documentation
Can()
override bool CCTWaterSurface::Can (PlayerBase player, ActionTarget target) inline private
Definition at line 12 of file cctwatersurface.c.
    {
        if ( !target || ( target && target.GetObject() ) )
            return false;
        // See if we are looking at something
        vector hit_pos = target.GetCursorHitPos();
        if (hit_pos == vector.Zero)
            return false;
        // See if the surface at the cursor position is water (surfType.Contains("water"))
        // Small Y offset, as it will prioritize water when surfaces are really close together
        string surfType;
        g_Game.SurfaceGetType3D(hit_pos[0], hit_pos[1] + 0.1, hit_pos[2], surfType);
        // See if the player is looking at the sea
        bool isSeaCheck = false;
        if ( m_SurfaceType == UAWaterType.ALL )
            isSeaCheck = ( hit_pos[1] <= ( g_Game.SurfaceGetSeaLevel() + 0.001 ) );
        // Sometimes SurfaceGetType3D ignores the Y, this makes it so the proper distance is calculated
        hit_pos[1] = g_Game.SurfaceY(hit_pos[0],hit_pos[2]);
        // Combine the tests and check the distance
        return ( vector.DistanceSq(hit_pos, player.GetPosition()) <= m_MaximalActionDistanceSq && (isSeaCheck || surfType.Contains(m_SurfaceType)) );
    }
References UAWaterType::ALL, string::Contains(), vector::DistanceSq(), g_Game, m_MaximalActionDistanceSq, m_SurfaceType, and vector::Zero.
Referenced by ActionFillBottleBase::GetLiquidType().
CanContinue()
override bool CCTWaterSurface::CanContinue (PlayerBase player, ActionTarget target) inline private
Definition at line 39 of file cctwatersurface.c.
    {
        return true;
    }
Member Data Documentation
m_MaximalActionDistanceSq
protected float CCTWaterSurface::m_MaximalActionDistanceSq private
Definition at line 3 of file cctwatersurface.c.
Referenced by Can(), and CCTWaterSurface().
m_SurfaceType
protected string CCTWaterSurface::m_SurfaceType private
Definition at line 4 of file cctwatersurface.c.
Referenced by Can(), and CCTWaterSurface().