DayzKode: ActionTakeMaterialToHandsSwitch Class Reference
ActionTakeMaterialToHandsSwitch Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTakeMaterialToHandsSwitch ()
override void CreateConditionComponents ()
override GetInputType ()
override bool IsInstant ()
override bool RemoveForceTargetAfterUse ()
override void Start (ActionData action_data)
override bool UseAcknowledgment ()
Detailed Description
Definition at line 1 of file actiontakematerialtohandsswitch.c.
Constructor & Destructor Documentation
ActionTakeMaterialToHandsSwitch()
void ActionTakeMaterialToHandsSwitch::ActionTakeMaterialToHandsSwitch () inline private
Definition at line 3 of file actiontakematerialtohandsswitch.c.
    {
        m_Text = "#switch_to_next_material";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeMaterialToHandsSwitch::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 34 of file actiontakematerialtohandsswitch.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if ( target_entity && target_entity.CanUseConstruction() )
        {
            BaseBuildingBase base_building = BaseBuildingBase.Cast( target_entity );
            if(!base_building.IsPlayerInside(player,""))
                return false;
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            string main_part_name = target_entity.GetActionComponentName( target.GetComponentIndex() );
            construction_action_data.RefreshAttachmentsToDetach( target_entity, main_part_name );
            if ( construction_action_data.GetAttachmentsToDetachCount() > 1 )
            {
                return true;
            }
        }
        return false;
    }
References ConstructionActionData::GetAttachmentsToDetachCount(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::RefreshAttachmentsToDetach().
CreateConditionComponents()
override void ActionTakeMaterialToHandsSwitch::CreateConditionComponents () inline private
Definition at line 8 of file actiontakematerialtohandsswitch.c.
    {
        m_ConditionItem = new CCINotPresent;
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.BASEBUILDING );
    }
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionTakeMaterialToHandsSwitch::GetInputType () inline private
Definition at line 29 of file actiontakematerialtohandsswitch.c.
    {
        return InteractActionInput;
    }
IsInstant()
override bool ActionTakeMaterialToHandsSwitch::IsInstant () inline private
Definition at line 14 of file actiontakematerialtohandsswitch.c.
    {
        return true;
    }
RemoveForceTargetAfterUse()
override bool ActionTakeMaterialToHandsSwitch::RemoveForceTargetAfterUse () inline private
Definition at line 19 of file actiontakematerialtohandsswitch.c.
    {
        return false;
    }
Start()
override void ActionTakeMaterialToHandsSwitch::Start (ActionData action_data) inline private
Definition at line 57 of file actiontakematerialtohandsswitch.c.
    {
        super.Start( action_data );
        //set next index
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        construction_action_data.SetNextAttachmentIndex();
    }
References ActionData::m_Player, and ConstructionActionData::SetNextAttachmentIndex().
UseAcknowledgment()
override bool ActionTakeMaterialToHandsSwitch::UseAcknowledgment () inline private
Definition at line 24 of file actiontakematerialtohandsswitch.c.
    {
        return true;
    }