DayzKode: ContainerWithElectricManager Class Reference
ContainerWithElectricManager Class Reference
Private Member Functions
void ElectricityIcon ()
override void SetEntity (EntityAI entity, bool immedUpdate=true)
override void UpdateInterval ()
Detailed Description
Definition at line 1 of file containerwithelectricmanager.c.
Member Function Documentation
ElectricityIcon()
void ContainerWithElectricManager::ElectricityIcon () inline private
Definition at line 11 of file containerwithelectricmanager.c.
    {
        if ( GetRootWidget().FindAnyWidget( "electricity" ) )
        {
            bool show_electricity_icon = m_Entity.GetCompEM().HasElectricityIcon();
            GetRootWidget().FindAnyWidget( "electricity" ).Show( show_electricity_icon );
        }
        if ( GetRootWidget().FindAnyWidget( "electricity_can_work" ) )
        {
            bool show_electricity_can_work_icon = m_Entity.GetCompEM().CanWork() && !m_Entity.IsRuined();
            GetRootWidget().FindAnyWidget( "electricity_can_work" ).Show( show_electricity_can_work_icon );
        }
    }
References FindAnyWidget(), m_Entity, and ScriptedWidgetEventHandler::Show().
Referenced by SetEntity(), and UpdateInterval().
SetEntity()
override void ContainerWithElectricManager::SetEntity (EntityAI entity, bool immedUpdate = true) inline private
Definition at line 26 of file containerwithelectricmanager.c.
    {
        super.SetEntity( entity, immedUpdate );
        ElectricityIcon();
    }
References ElectricityIcon().
Referenced by VicinityContainer::UpdateInterval().
UpdateInterval()
override void ContainerWithElectricManager::UpdateInterval () inline private
Definition at line 3 of file containerwithelectricmanager.c.
    {
        super.UpdateInterval();
        if ( m_Entity )
            ElectricityIcon();
    }
References ElectricityIcon(), and m_Entity.