DayzKode: BiosSocialService Class Reference
BiosSocialService Class Reference
BiosSocialService is used to query friend list and other social features for the current user.
Private Member Functions
proto native EBiosError GetFriendsAsync ()
Query for friends list.
void OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error)
Async callback for GetFriendsAsync.
void OnUserProfileAsync (EBiosError error)
Async callback for ShowUserProfileAsync.
proto native EBiosError ShowUserProfileAsync (string uid_target)
Display small system UI profile for the target.
Detailed Description
BiosSocialService is used to query friend list and other social features for the current user.
Todo: report friend changes
Definition at line 23 of file biossocialservice.c.
Member Function Documentation
GetFriendsAsync()
proto native EBiosError BiosSocialService::GetFriendsAsync () private
Query for friends list.
The async result is returned in the OnFriendsAsync callback.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::LoadFriends().
OnFriendsAsync()
void BiosSocialService::OnFriendsAsync (BiosFriendInfoArray friend_list, EBiosError error) inline private
Async callback for GetFriendsAsync.
Parameters
friend_list list of BiosFriendInfo for each friend. NULL if failed.
error error indicating success or fail of the async operation.
Definition at line 58 of file biossocialservice.c.
    {
        OnlineServices.OnFriendsAsync( friend_list, error );
    }
References OnlineServices::OnFriendsAsync().
OnUserProfileAsync()
void BiosSocialService::OnUserProfileAsync (EBiosError error) inline private
Async callback for ShowUserProfileAsync.
Parameters
error error indicating success or fail of the async operation. Xbox: OK - the user displayed the fullscreen profile Xbox: CANCEL - the user closed the small profile.
Definition at line 48 of file biossocialservice.c.
    {
        OnlineServices.OnUserProfileAsync( error );
    }
References OnlineServices::OnUserProfileAsync().
ShowUserProfileAsync()
proto native EBiosError BiosSocialService::ShowUserProfileAsync (string uid_target) private
Display small system UI profile for the target.
Xbox: The async result is returned in the OnPermissionsAsync callback.
Parameters
uid_target target user Uid's for which to display profile.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::ShowUserProfile().