DayzKode: Attachments Class Reference
Attachments Class Reference
Private Member Functions
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
void Attachments (Container parent, EntityAI entity)
bool CanCombine ()
bool CanCombineAmmo ()
bool CanEquip ()
bool Combine ()
bool EquipItem ()
int GetAttachmentHeight ()
TextWidget GetFalseHeaderTextWidget ()
EntityAI GetFocusedItem ()
int GetFocusedSlot ()
SlotsIcon GetFocusedSlotsIcon ()
array< string > GetItemSlots (EntityAI e)
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
array< int > GetSlotsSorted ()
AttachmentsWrapper GetWrapper ()
void InitAttachmentGrid (int att_row_index)
bool InspectItem ()
bool IsActive ()
bool IsEmpty ()
bool IsItemActive ()
bool IsItemWithQuantityActive ()
void OnAttachmentReservationRelease (EntityAI item, int slot_id)
void OnAttachmentReservationSet (EntityAI item, int slot_id)
bool Select ()
bool SelectItem ()
void SelFirstActive ()
void SetActive (bool active)
void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetFalseAttachmentsHeaderText (string text)
void SetLastActive ()
void ShowFalseAttachmentsHeader (bool show)
bool SplitItem ()
bool TransferItem ()
bool TransferItemToVicinity ()
void UnfocusAll ()
void UpdateInterval ()
void ~Attachments ()
Private Attributes
protected ref array< int > m_AttachmentIDOrdered
protected ref AttachmentsWrapper m_AttachmentsContainer
protected ref array< string > m_AttachmentSlotDisplayable
protected ref array< string > m_AttachmentSlotNames
protected ref map< int, SlotsIcon > m_AttachmentSlots
protected EntityAI m_Entity
protected Container m_Parent
protected int m_RowIndex
Detailed Description
Definition at line 3 of file attachments.c.
Constructor & Destructor Documentation
Attachments()
void Attachments::Attachments (Container parent, EntityAI entity) inline private
Definition at line 15 of file attachments.c.
    {
        m_Parent                    = parent;
        m_Entity                    = entity;
        m_AttachmentSlots           = new map<int, SlotsIcon>;
        m_AttachmentIDOrdered       = new array<int>;
        m_AttachmentSlotNames       = GetItemSlots( entity );
        m_AttachmentSlotDisplayable = new array<string>;
        m_Entity.GetOnItemAttached().Insert( AttachmentAdded );
        m_Entity.GetOnItemDetached().Insert( AttachmentRemoved );
        m_Entity.GetOnAttachmentSetLock().Insert( OnAttachmentReservationSet );
        m_Entity.GetOnAttachmentReleaseLock().Insert( OnAttachmentReservationRelease );
    }
References AttachmentAdded(), AttachmentRemoved(), GetItemSlots(), m_AttachmentIDOrdered, m_AttachmentSlotDisplayable, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
~Attachments()
void Attachments::~Attachments () inline private
Definition at line 30 of file attachments.c.
    {
        if( m_Entity )
        {
            m_Entity.GetOnItemAttached().Remove( AttachmentAdded );
            m_Entity.GetOnItemDetached().Remove( AttachmentRemoved );
            m_Entity.GetOnAttachmentSetLock().Remove( OnAttachmentReservationSet );
            m_Entity.GetOnAttachmentReleaseLock().Remove( OnAttachmentReservationRelease );
        }
        delete m_AttachmentsContainer;
    }
References AttachmentAdded(), AttachmentRemoved(), m_AttachmentsContainer, m_Entity, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
Member Function Documentation
AttachmentAdded()
void Attachments::AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 408 of file attachments.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString(slot);
        SlotsIcon icon = m_AttachmentSlots.Get(slot_id);
        if (icon)
        {
            icon.SetSlotID(slot_id);
            icon.SetSlotDisplayName(InventorySlots.GetSlotDisplayName(slot_id));
            if (item)
            {
                icon.Init(item);
            }
        }
    }
References InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), m_AttachmentSlots, SlotsIcon::SetSlotDisplayName(), and SlotsIcon::SetSlotID().
Referenced by Attachments(), InitAttachmentGrid(), and ~Attachments().
AttachmentRemoved()
void Attachments::AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 423 of file attachments.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString(slot);
        SlotsIcon icon = m_AttachmentSlots.Get(slot_id);
        if (icon)
        {
            icon.Clear();
        }
    }
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
CanCombine()
bool Attachments::CanCombine () inline private
Definition at line 197 of file attachments.c.
    {
        ItemBase ent = ItemBase.Cast( GetFocusedItem() );
        ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
        return ( ItemManager.GetCombinationFlags( item_in_hands, ent ) != 0 );
    }
References ItemManager::GetCombinationFlags(), GetFocusedItem(), GetGame(), and GetPlayer().
Referenced by AttachmentsWrapper::CanCombine().
CanCombineAmmo()
bool Attachments::CanCombineAmmo () inline private
Definition at line 205 of file attachments.c.
    {
        PlayerBase m_player = PlayerBase.Cast( GetGame().GetPlayer() );
        ItemBase ent = ItemBase.Cast(  GetFocusedItem() );
        ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
        ActionManagerClient amc;
        Class.CastTo(amc, m_player.GetActionManager());
        return ( amc.CanPerformActionFromInventory( item_in_hands, ent ) );
    }
References ActionManagerClient::CanPerformActionFromInventory(), Class::CastTo(), GetFocusedItem(), GetGame(), GetPlayer(), and m_player.
Referenced by AttachmentsWrapper::CanCombineAmmo().
CanEquip()
bool Attachments::CanEquip () inline private
Definition at line 216 of file attachments.c.
    {
        EntityAI entity = ItemBase.Cast( GetFocusedItem() );
        InventoryLocation il = new InventoryLocation;
        if( !entity || entity.IsInherited( Magazine ) )
        {
            return false;
        }
        return GetGame().GetPlayer().GetInventory().FindFreeLocationFor( entity, FindInventoryLocationType.ATTACHMENT, il );
    }
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::CanEquip().
Combine()
bool Attachments::Combine () inline private
Definition at line 227 of file attachments.c.
    {
        ItemBase ent = ItemBase.Cast( GetFocusedItem() );
        ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
        Icon hands_icon = ItemManager.GetInstance().GetHandsPreview().GetIcon();
        if ( item_in_hands && ent && hands_icon )
        {
            return hands_icon.CombineItems( item_in_hands, ent );
        }
        return false;
    }
References Icon::CombineItems(), GetFocusedItem(), GetGame(), ItemManager::GetHandsPreview(), HandsPreview::GetIcon(), ItemManager::GetInstance(), and GetPlayer().
Referenced by AttachmentsWrapper::Combine().
EquipItem()
bool Attachments::EquipItem () inline private
Definition at line 255 of file attachments.c.
    {
        ItemBase entity = ItemBase.Cast( GetFocusedItem() );
        if( entity && !entity.IsInherited( Magazine ) && !GetFocusedSlotsIcon().IsOutOfReach() )
        {
            GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, entity );
            return true;
        }
        return false;
    }
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::EquipItem().
GetAttachmentHeight()
int Attachments::GetAttachmentHeight () inline private
Definition at line 308 of file attachments.c.
    {
        return m_AttachmentsContainer.Count();
    }
References m_AttachmentsContainer.
Referenced by HandsContainer::ShowAtt().
GetFalseHeaderTextWidget()
TextWidget Attachments::GetFalseHeaderTextWidget () inline private
Definition at line 598 of file attachments.c.
    {
        return m_AttachmentsContainer.GetFalseHeaderTextWidget();
    }
References AttachmentsWrapper::GetFalseHeaderTextWidget(), and m_AttachmentsContainer.
Referenced by HandsContainer::AttachmentAdded().
GetFocusedItem()
EntityAI Attachments::GetFocusedItem () inline private
Definition at line 103 of file attachments.c.
    {
        return m_AttachmentsContainer.GetFocusedItem();
    }
References Container::GetFocusedItem(), and m_AttachmentsContainer.
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), InspectItem(), IsItemActive(), IsItemWithQuantityActive(), Select(), SelectItem(), SplitItem(), TransferItem(), and TransferItemToVicinity().
GetFocusedSlot()
int Attachments::GetFocusedSlot () inline private
Definition at line 108 of file attachments.c.
    {
        SlotsIcon icon = m_AttachmentsContainer.GetFocusedSlotsIcon();
        if (icon)
            return icon.GetSlotID();
        return -1;
    }
References SlotsIcon::GetSlotID(), and m_AttachmentsContainer.
Referenced by AttachmentsWrapper::GetFocusedSlot().
GetFocusedSlotsIcon()
SlotsIcon Attachments::GetFocusedSlotsIcon () inline private
Definition at line 98 of file attachments.c.
    {
        return m_AttachmentsContainer.GetFocusedSlotsIcon();
    }
References m_AttachmentsContainer.
Referenced by EquipItem(), Select(), SelectItem(), SplitItem(), TransferItem(), TransferItemToVicinity(), and UpdateInterval().
GetItemSlots()
array< string > Attachments::GetItemSlots (EntityAI e) inline private
Definition at line 555 of file attachments.c.
    {
        TStringArray searching_in = new TStringArray;
        searching_in.Insert( CFG_VEHICLESPATH );
        searching_in.Insert( CFG_WEAPONSPATH );
        searching_in.Insert( CFG_MAGAZINESPATH );
        array<string> attachments_slots = new array<string>;
        int i = 0;
        for ( int s = 0; s < searching_in.Count(); ++s )
        {
            string cfg_name = searching_in.Get( s );
            string path = cfg_name + " " + e.GetType();
            if ( GetGame().ConfigIsExisting( path ) )
            {
                GetGame().ConfigGetTextArray( path + " attachments", attachments_slots );
                if ( e.IsWeapon() && (!e.ConfigIsExisting("DisplayMagazine") || e.ConfigGetBool("DisplayMagazine")) )
                {
                    attachments_slots.Insert( "magazine" );
                }
                return attachments_slots;
            }
        }
        if ( e.IsWeapon() && (!e.ConfigIsExisting("DisplayMagazine") || e.ConfigGetBool("DisplayMagazine")) )
        {
            attachments_slots.Insert( "magazine" );
        }
        return attachments_slots;
    }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and path.
Referenced by Attachments().
GetRecipeCount()
int Attachments::GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 191 of file attachments.c.
    {
        PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast( GetPlugin( PluginRecipesManager ) );
        return plugin_recipes_manager.GetValidRecipes( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ), null, PlayerBase.Cast( GetGame().GetPlayer() ) );
    }
References GetGame(), GetPlayer(), and GetPlugin().
GetSlotsSorted()
array< int > Attachments::GetSlotsSorted () inline private
Definition at line 403 of file attachments.c.
    {
        return m_AttachmentIDOrdered;
    }
References m_AttachmentIDOrdered.
Referenced by HandsContainer::ShowAtt().
GetWrapper()
AttachmentsWrapper Attachments::GetWrapper () inline private
Definition at line 43 of file attachments.c.
    {
        return m_AttachmentsContainer;
    }
References m_AttachmentsContainer.
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::DestroyAtt(), HandsContainer::OnPerformCombination(), and HandsContainer::SetFocusToIndex().
InitAttachmentGrid()
void Attachments::InitAttachmentGrid (int att_row_index) inline private
Definition at line 450 of file attachments.c.
    {
        SlotsIcon icon;
        int i;
        m_RowIndex = att_row_index;
        int number_of_rows = Math.Ceil( m_AttachmentSlotNames.Count() / ITEMS_IN_ROW );
        string name = m_Entity.GetDisplayName();
        name.ToUpper();
        m_AttachmentsContainer = new AttachmentsWrapper( m_Parent );
        m_AttachmentsContainer.SetParent( this );
        m_AttachmentsContainer.SetFalseAttachmentsHeaderText(name);
        m_AttachmentsContainer.GetRootWidget().SetSort( att_row_index );
        m_Parent.Insert( m_AttachmentsContainer, att_row_index );
        for ( i = 0; i < number_of_rows; i++ )
        {
            SlotsContainer ic = new SlotsContainer( m_AttachmentsContainer, m_Entity );
            m_AttachmentsContainer.Insert( ic );
            if( i == ( number_of_rows - 1 ) && m_AttachmentSlotNames.Count() % ITEMS_IN_ROW != 0 )
            {
                ic.SetColumnCount( m_AttachmentSlotNames.Count() % ITEMS_IN_ROW );
            }
            else
            {
                ic.SetColumnCount( ITEMS_IN_ROW );
            }
            for( int j = 0; j < ITEMS_IN_ROW; j++ )
            {
                icon = ic.GetSlotIcon( j );
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetMainWidget(), m_Parent, "OnDropReceivedFromHeader2" );
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetGhostSlot(), m_Parent, "OnDropReceivedFromHeader2" );
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetPanelWidget(), m_Parent, "OnDropReceivedFromHeader2" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetMainWidget(), m_Parent, "DraggingOverHeader" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetGhostSlot(), m_Parent, "DraggingOverHeader" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetPanelWidget(), m_Parent, "DraggingOverHeader" );
                WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( icon.GetMainWidget(), m_Parent, "MouseClick2" );
                WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( icon.GetGhostSlot(), m_Parent, "MouseClick2" );
                WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( icon.GetPanelWidget(), m_Parent, "MouseClick2" );
            }
        }
        for ( i = 0; i < m_AttachmentSlotNames.Count(); i++ )
        {
            icon = SlotsContainer.Cast( m_AttachmentsContainer.Get( ( i / ITEMS_IN_ROW ) ) ).GetSlotIcon( i % ITEMS_IN_ROW );
            WidgetEventHandler.GetInstance().RegisterOnDoubleClick( icon.GetPanelWidget(), m_Parent, "DoubleClick" );
            string path = "CfgSlots" + " Slot_" + m_AttachmentSlotNames[i];
            //Show different magazine icon for firearms and pistols
            if ( m_AttachmentSlotNames[i] == "magazine" )
            {
                if ( !m_Entity.IsInherited( Pistol_Base ) )
                    path = "CfgSlots" + " Slot_" + "magazine2";
            }
            string icon_name = ""; //icon_name must be in format "set:<setname> image:<imagename>"
            if( GetGame().ConfigGetText( path + " ghostIcon", icon_name ) && icon_name != "" )
                icon.GetGhostSlot().LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,icon_name) );
            int slot_id = InventorySlots.GetSlotIdFromString( m_AttachmentSlotNames[i] );
            m_AttachmentSlots.Insert( slot_id, icon );
            m_AttachmentIDOrdered.Insert(slot_id);
            icon.SetSlotID(slot_id);
            icon.SetSlotDisplayName(InventorySlots.GetSlotDisplayName(slot_id));
            EntityAI item = m_Entity.GetInventory().FindAttachment( slot_id );
            if( item )
                AttachmentAdded( item, m_AttachmentSlotNames[i], m_Entity );
            else
                icon.Clear();
            if (m_Entity.CanDisplayAttachmentSlot(slot_id))
            {
                icon.GetMainWidget().Show( true );
            }
            else
            {
                icon.GetMainWidget().Show( false );
            }
        }
        if( m_AttachmentSlotNames.Count() > 0 )
        {
            int row_index = number_of_rows - 1;
            SlotsContainer row_last = SlotsContainer.Cast( m_AttachmentsContainer.Get( row_index ) );
            if( row_last )
            {
                for( int k = ((m_AttachmentSlotNames.Count() - 1) % ITEMS_IN_ROW) + 1; k < ITEMS_IN_ROW; k++ )
                {
                    row_last.GetSlotIcon( k ).GetMainWidget().Show( false );
                }
                row_last.GetRootWidget().Update();
                row_last.GetRootWidget().GetParent().Update();
            }
        }
        m_AttachmentsContainer.RecomputeOpenedContainers();
    }
References AttachmentAdded(), Math::Ceil(), SlotsIcon::Clear(), Container::Get(), GetGame(), SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), InventorySlots::GetSlotDisplayName(), SlotsContainer::GetSlotIcon(), InventorySlots::GetSlotIdFromString(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ITEMS_IN_ROW, m_AttachmentIDOrdered, m_AttachmentsContainer, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, m_RowIndex, name, path, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), AttachmentsWrapper::SetFalseAttachmentsHeaderText(), AttachmentsWrapper::SetParent(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), string::ToUpper(), and StaticGUIUtils::VerifyIconImageString().
Referenced by HandsContainer::AttachmentAdded(), HandsContainer::OnPerformCombination(), and HandsContainer::ShowAtt().
InspectItem()
bool Attachments::InspectItem () inline private
Definition at line 277 of file attachments.c.
    {
        EntityAI entity = GetFocusedItem();
        if( entity )
        {
            m_Parent.InspectItem( entity );
            return true;
        }
        return false;
    }
References GetFocusedItem(), and m_Parent.
Referenced by AttachmentsWrapper::InspectItem().
IsActive()
bool Attachments::IsActive () inline private
Definition at line 303 of file attachments.c.
    {
        return m_Parent.GetMainWidget().FindAnyWidget("AttachmentsWrapper").GetAlpha() > 0;
    }
References m_Parent.
IsEmpty()
bool Attachments::IsEmpty () inline private
Definition at line 48 of file attachments.c.
    {
        return m_AttachmentsContainer.IsEmpty();
    }
References Container::IsEmpty(), and m_AttachmentsContainer.
Referenced by IsItemActive(), and IsItemWithQuantityActive().
IsItemActive()
bool Attachments::IsItemActive () inline private
Definition at line 53 of file attachments.c.
    {
        ItemBase item = ItemBase.Cast( GetFocusedItem() );
        if( !item )
        {
            return false;
        }
        return !IsEmpty() && ( !QuantityConversions.HasItemQuantity( item )  || ( QuantityConversions.HasItemQuantity( item ) && !item.CanBeSplit() ) );
    }
References GetFocusedItem(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by AttachmentsWrapper::IsItemActive().
IsItemWithQuantityActive()
bool Attachments::IsItemWithQuantityActive () inline private
Definition at line 63 of file attachments.c.
    {
        ItemBase item = ItemBase.Cast( GetFocusedItem() );
        if( !item )
        {
            return false;
        }
        return !IsEmpty() && QuantityConversions.HasItemQuantity( item ) && item.CanBeSplit();
    }
References GetFocusedItem(), QuantityConversions::HasItemQuantity(), and IsEmpty().
Referenced by AttachmentsWrapper::IsItemWithQuantityActive().
OnAttachmentReservationRelease()
void Attachments::OnAttachmentReservationRelease (EntityAI item, int slot_id) inline private
Definition at line 443 of file attachments.c.
    {
        SlotsIcon icon = m_AttachmentSlots.Get( slot_id );
        icon.Clear();
    }
References SlotsIcon::Clear(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
OnAttachmentReservationSet()
void Attachments::OnAttachmentReservationSet (EntityAI item, int slot_id) inline private
Definition at line 433 of file attachments.c.
    {
        SlotsIcon icon = m_AttachmentSlots.Get( slot_id );
        if (item)
        {
            icon.Init( item, true );
        }
    }
References SlotsIcon::Init(), and m_AttachmentSlots.
Referenced by Attachments(), and ~Attachments().
Select()
bool Attachments::Select () inline private
Definition at line 129 of file attachments.c.
    {
        SlotsIcon selected_slot = ItemManager.GetInstance().GetSelectedIcon();
        EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
        SlotsIcon focused_slot = GetFocusedSlotsIcon();
        EntityAI focused_item = GetFocusedItem();
        Man player = GetGame().GetPlayer();
        if( focused_slot.IsReserved() || focused_item != selected_item && !(selected_slot && selected_slot.IsOutOfReach() ) )
        {
            if( selected_item )
            {
                if( selected_item.GetInventory().CanRemoveEntity() )
                {
                    if( m_Entity.GetInventory().CanAddAttachmentEx( selected_item, focused_slot.GetSlotID() ) )
                    {
                        player.PredictiveTakeEntityToTargetAttachmentEx( m_Entity, selected_item, focused_slot.GetSlotID() );
                        ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
                        return true;
                    }
                    else if( m_Entity.GetInventory().CanAddAttachment( selected_item ) )
                    {
                        player.PredictiveTakeEntityToTargetAttachment(m_Entity, selected_item);
                        ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
                        return true;
                    }
                }
            }
            else
            {
                if ( focused_item && !focused_slot.IsOutOfReach() )
                {
                    EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
                    InventoryLocation il = new InventoryLocation;
                    focused_item.GetInventory().GetCurrentInventoryLocation( il );
                    bool reachable = AttachmentsOutOfReach.IsAttachmentReachable( m_Entity, "", il.GetSlot() );
                    if( reachable && focused_item.GetInventory().CanRemoveEntity() )
                    {
                        if( item_in_hands && item_in_hands.GetInventory().CanRemoveEntity() )
{
                            if( GameInventory.CanSwapEntitiesEx( item_in_hands, focused_item ) )
{
                                player.PredictiveSwapEntities( item_in_hands, focused_item );
                                return true;
                            }
                        }
                        else
{
                            if( player.GetHumanInventory().CanAddEntityInHands( focused_item ) )
{
                                player.PredictiveTakeEntityToHands( focused_item );
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), ItemManager::GetSelectedIcon(), ItemManager::GetSelectedItem(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), AttachmentsOutOfReach::IsAttachmentReachable(), SlotsIcon::IsOutOfReach(), SlotsIcon::IsReserved(), m_Entity, and ItemManager::SetSelectedItem().
Referenced by AttachmentsWrapper::Select().
SelectItem()
bool Attachments::SelectItem () inline private
Definition at line 116 of file attachments.c.
    {
        ItemBase item = ItemBase.Cast( GetFocusedItem() );
        SlotsIcon icon = GetFocusedSlotsIcon();
        if (icon && !icon.IsOutOfReach())
        {
            ItemManager.GetInstance().SetSelectedItem( item, null, icon.GetCursorWidget(), icon );
            return true;
        }
        return false;
    }
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), GetFocusedSlotsIcon(), ItemManager::GetInstance(), SlotsIcon::IsOutOfReach(), and ItemManager::SetSelectedItem().
Referenced by AttachmentsWrapper::SelectItem().
SelFirstActive()
void Attachments::SelFirstActive () inline private
Definition at line 93 of file attachments.c.
    {
        m_AttachmentsContainer.SetFirstActive();
    }
References m_AttachmentsContainer.
SetActive()
void Attachments::SetActive (bool active) inline private
Definition at line 88 of file attachments.c.
    {
        m_AttachmentsContainer.SetActive(active);
    }
References m_AttachmentsContainer, and AttachmentsGroupContainer::SetActive().
SetDefaultFocus()
void Attachments::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 78 of file attachments.c.
    {
        m_AttachmentsContainer.SetDefaultFocus(while_micromanagment_mode);
    }
References m_AttachmentsContainer, and AttachmentsGroupContainer::SetDefaultFocus().
Referenced by HandsContainer::SetFocusToIndex(), and UpdateInterval().
SetFalseAttachmentsHeaderText()
void Attachments::SetFalseAttachmentsHeaderText (string text) inline private
Definition at line 593 of file attachments.c.
    {
        m_AttachmentsContainer.SetFalseAttachmentsHeaderText(text);
    }
References m_AttachmentsContainer, and AttachmentsWrapper::SetFalseAttachmentsHeaderText().
SetLastActive()
void Attachments::SetLastActive () inline private
Definition at line 83 of file attachments.c.
    {
        m_AttachmentsContainer.SetLastActive();
    }
References m_AttachmentsContainer, and Container::SetLastActive().
ShowFalseAttachmentsHeader()
void Attachments::ShowFalseAttachmentsHeader (bool show) inline private
Definition at line 588 of file attachments.c.
    {
        m_AttachmentsContainer.ShowFalseAttachmentsHeader(show);
    }
References m_AttachmentsContainer, and AttachmentsWrapper::ShowFalseAttachmentsHeader().
Referenced by HandsContainer::AttachmentAdded().
SplitItem()
bool Attachments::SplitItem () inline private
Definition at line 241 of file attachments.c.
    {
        ItemBase entity = ItemBase.Cast( GetFocusedItem() );
        if( entity && !entity.IsInherited( Magazine ) && !GetFocusedSlotsIcon().IsOutOfReach() )
        {
            if( entity.HasQuantity() )
            {
                entity.OnRightClick();
                return true;
            }
        }
        return false;
    }
References GetFocusedItem(), and GetFocusedSlotsIcon().
Referenced by AttachmentsWrapper::SplitItem().
TransferItem()
bool Attachments::TransferItem () inline private
Definition at line 266 of file attachments.c.
    {
        EntityAI entity = GetFocusedItem();
        if( entity && !GetFocusedSlotsIcon().IsOutOfReach() )
        {
            GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, entity );
            return true;
        }
        return false;
    }
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and CGame::GetPlayer().
Referenced by AttachmentsWrapper::TransferItem().
TransferItemToVicinity()
bool Attachments::TransferItemToVicinity () inline private
Definition at line 288 of file attachments.c.
    {
        ItemBase item = ItemBase.Cast(GetFocusedItem());
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( item && !GetFocusedSlotsIcon().IsOutOfReach() )
        {
            if( item.GetTargetQuantityMax() < item.GetQuantity() )
                item.SplitIntoStackMaxClient( null, -1 );
            else
                player.PhysicalPredictiveDropItem( item );
            return true;
        }
        return false;
    }
References GetFocusedItem(), GetFocusedSlotsIcon(), GetGame(), and GetPlayer().
Referenced by AttachmentsWrapper::TransferItemToVicinity().
UnfocusAll()
void Attachments::UnfocusAll () inline private
Definition at line 73 of file attachments.c.
    {
        m_AttachmentsContainer.UnfocusAll();
    }
References m_AttachmentsContainer, and Container::UnfocusAll().
Referenced by HandsContainer::UnfocusGrid().
UpdateInterval()
void Attachments::UpdateInterval () inline private
Definition at line 313 of file attachments.c.
    {
        SlotsIcon icon;
        int slot_id;
        m_AttachmentSlotDisplayable.Clear();
        int i = 0;
        for (i = m_AttachmentSlotNames.Count() - 1; i >=0; --i)
        {
            slot_id = InventorySlots.GetSlotIdFromString( m_AttachmentSlotNames[i] );
            if (m_Entity.CanDisplayAttachmentSlot(slot_id))
            {
                m_AttachmentSlotDisplayable.Insert(m_AttachmentSlotNames[i]);
            }
            else
            {
                icon = m_AttachmentSlots.Get( slot_id );
                if (icon)
                {
                    icon.GetMainWidget().Show( false );
                    if( GetFocusedSlotsIcon() == icon )
                    {
                        SetDefaultFocus();
                    }
                    // radial icon (collabsable icon handling)
                    icon.UpdateInterval();
                }
            }
        }
        if ( m_AttachmentSlotDisplayable.Count() == 0 )
        {
            if (m_Parent)
            {
                m_Parent.UpdateRadialIcon();
                //m_Parent.Close();
            }
        }
        for (i = 0; i < m_AttachmentSlotDisplayable.Count(); ++i)
        {
            slot_id = InventorySlots.GetSlotIdFromString( m_AttachmentSlotDisplayable[i] );
            icon = m_AttachmentSlots.Get( slot_id );
            EntityAI item = icon.GetEntity();
            icon.GetMainWidget().Show( true );
            icon.UpdateInterval();
            if ( item )
            {
                bool draggable = true;
                if(icon.IsReserved())
                {
                    draggable = false;
                }
                if( m_Entity.GetInventory().GetSlotLock( slot_id ) && ItemManager.GetInstance().GetDraggedItem() != item )
                {
                    icon.GetMountedWidget().Show( true );
                    draggable = false;
                }
                else
                {
                    icon.GetMountedWidget().Show( false );
                }
                PlayerBase p = PlayerBase.Cast( GetGame().GetPlayer() );
                bool in_hands_condition     = m_Entity.GetHierarchyRoot() && item.GetInventory().CanRemoveEntity();
                bool in_vicinity_condition  = !m_Entity.GetHierarchyRoot() && AttachmentsOutOfReach.IsAttachmentReachable( m_Entity, m_AttachmentSlotDisplayable[i] );
                if( in_hands_condition || in_vicinity_condition )
                {
                    icon.GetOutOfReachWidget().Show( false );
                }
                else
                {
                    icon.GetOutOfReachWidget().Show( true );
                    draggable = false;
                }
                if( draggable )
                {
                    icon.GetPanelWidget().SetFlags( WidgetFlags.DRAGGABLE );
                }
                else
                {
                    icon.GetPanelWidget().ClearFlags( WidgetFlags.DRAGGABLE );
                }
            }
        }
        m_AttachmentsContainer.GetRootWidget().Update();
    }
References ItemManager::GetDraggedItem(), SlotsIcon::GetEntity(), GetFocusedSlotsIcon(), GetGame(), ItemManager::GetInstance(), SlotsIcon::GetMountedWidget(), SlotsIcon::GetOutOfReachWidget(), SlotsIcon::GetPanelWidget(), GetPlayer(), InventorySlots::GetSlotIdFromString(), AttachmentsOutOfReach::IsAttachmentReachable(), SlotsIcon::IsReserved(), m_AttachmentsContainer, m_AttachmentSlotDisplayable, m_AttachmentSlotNames, m_AttachmentSlots, m_Entity, m_Parent, SetDefaultFocus(), SlotsIcon::UpdateInterval(), and Container::UpdateRadialIcon().
Referenced by HandsContainer::AttachmentAdded(), AttachmentsWrapper::UpdateInterval(), and HandsContainer::UpdateInterval().
Member Data Documentation
m_AttachmentIDOrdered
protected ref array<int> Attachments::m_AttachmentIDOrdered private
Definition at line 11 of file attachments.c.
Referenced by Attachments(), GetSlotsSorted(), and InitAttachmentGrid().
m_AttachmentsContainer
protected ref AttachmentsWrapper Attachments::m_AttachmentsContainer private
Definition at line 7 of file attachments.c.
Referenced by GetAttachmentHeight(), GetFalseHeaderTextWidget(), GetFocusedItem(), GetFocusedSlot(), GetFocusedSlotsIcon(), GetWrapper(), InitAttachmentGrid(), IsEmpty(), SelFirstActive(), SetActive(), SetDefaultFocus(), SetFalseAttachmentsHeaderText(), SetLastActive(), ShowFalseAttachmentsHeader(), UnfocusAll(), UpdateInterval(), and ~Attachments().
m_AttachmentSlotDisplayable
protected ref array<string> Attachments::m_AttachmentSlotDisplayable private
Definition at line 9 of file attachments.c.
Referenced by Attachments(), and UpdateInterval().
m_AttachmentSlotNames
protected ref array<string> Attachments::m_AttachmentSlotNames private
Definition at line 8 of file attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), and UpdateInterval().
m_AttachmentSlots
protected ref map<int, SlotsIcon> Attachments::m_AttachmentSlots private
Definition at line 10 of file attachments.c.
Referenced by AttachmentAdded(), AttachmentRemoved(), Attachments(), InitAttachmentGrid(), OnAttachmentReservationRelease(), OnAttachmentReservationSet(), and UpdateInterval().
m_Entity
protected EntityAI Attachments::m_Entity private
Definition at line 6 of file attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), Select(), UpdateInterval(), and ~Attachments().
m_Parent
protected Container Attachments::m_Parent private
Definition at line 5 of file attachments.c.
Referenced by Attachments(), InitAttachmentGrid(), InspectItem(), IsActive(), and UpdateInterval().
m_RowIndex
protected int Attachments::m_RowIndex private
Definition at line 13 of file attachments.c.
Referenced by InitAttachmentGrid().