DayzKode: Pear Class Reference
Pear Class Reference
Private Member Functions
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool CanDecay ()
override void EEOnCECreate ()
override bool IsFruit ()
override void SetActions ()
Detailed Description
Definition at line 1 of file pear.c.
Member Function Documentation
CanBeCooked()
override bool Pear::CanBeCooked () inline private
Definition at line 3 of file pear.c.
    {
        return true;
    }
CanBeCookedOnStick()
override bool Pear::CanBeCookedOnStick () inline private
Definition at line 8 of file pear.c.
    {
        return true;
    }
CanDecay()
override bool Pear::CanDecay () inline private
Definition at line 28 of file pear.c.
    {
        return true;
    }
EEOnCECreate()
override void Pear::EEOnCECreate () inline private
Definition at line 33 of file pear.c.
    {
        int rand = Math.RandomInt(0,10);
        if ( rand > 6 )
        {
            ChangeFoodStage( FoodStageType.ROTTEN );
            SetHealth( "", "", GetMaxHealth()*0.1 );
        }
        else if ( rand > 2 )
        {
            ChangeFoodStage( FoodStageType.DRIED );
            SetHealth( "", "", GetMaxHealth()*0.4 );
        }
    }
References ChangeFoodStage(), GetMaxHealth(), Math::RandomInt(), and SetHealth().
IsFruit()
override bool Pear::IsFruit () inline private
Definition at line 13 of file pear.c.
    {
        return true;
    }
SetActions()
override void Pear::SetActions () inline private
Definition at line 18 of file pear.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatFruit);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().