DayzKode: CAContinuousQuantityEdible Class Reference
CAContinuousQuantityEdible Class Reference
Private Member Functions
void CAContinuousQuantityEdible (float quantity_used_per_second, float time_to_repeat)
override void CalcAndSetQuantity (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_InitItemQuantity
protected float m_SpentQuantityTotal
Detailed Description
Definition at line 1 of file cacontinuousquantityedible.c.
Constructor & Destructor Documentation
CAContinuousQuantityEdible()
void CAContinuousQuantityEdible::CAContinuousQuantityEdible (float quantity_used_per_second, float time_to_repeat) inline private
Definition at line 6 of file cacontinuousquantityedible.c.
    {
        m_QuantityUsedPerSecond = quantity_used_per_second;
        m_DefaultTimeToRepeat = time_to_repeat;
        m_InitItemQuantity = -1;
        m_SpentQuantityTotal = 0;
    }
References CAContinuousQuantityRepeat::m_DefaultTimeToRepeat, m_InitItemQuantity, CAContinuousQuantityRepeat::m_QuantityUsedPerSecond, and m_SpentQuantityTotal.
Member Function Documentation
CalcAndSetQuantity()
override void CAContinuousQuantityEdible::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 24 of file cacontinuousquantityedible.c.
    {
        //Print("Munch!");
        if ( m_SpentUnits )
        {
            m_SpentUnits.param1 = m_SpentQuantity;
            SetACData(m_SpentUnits);
            m_SpentQuantityTotal += m_SpentQuantity;
        }
        //m_SpentQuantity = Math.Floor(m_SpentQuantity);
        PlayerBase ntarget = PlayerBase.Cast( action_data.m_Target.GetObject() );
        if ( ntarget )
        {
            if ( GetGame().IsServer() )
            {
                //action_data.m_MainItem.Consume(targetObject, m_SpentQuantity);
                ntarget.Consume(action_data.m_MainItem, m_SpentQuantity, EConsumeType.ITEM_CONTINUOUS);
            }
        }
        else
        {
            if ( GetGame().IsServer() )
            {
                //action_data.m_MainItem.Consume(action_data.m_Player, m_SpentQuantity);
                action_data.m_Player.Consume(action_data.m_MainItem, m_SpentQuantity, EConsumeType.ITEM_CONTINUOUS);
            }
        }
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantityRepeat::m_SpentQuantity, m_SpentQuantityTotal, CAContinuousQuantityRepeat::m_SpentUnits, ActionData::m_Target, and CABase::SetACData().
GetProgress()
override float CAContinuousQuantityEdible::GetProgress () inline private
Definition at line 56 of file cacontinuousquantityedible.c.
    {
        //return super.GetProgress();
        if (m_SpentQuantity > 0)
        {
            return Math.Clamp((1 - (m_InitItemQuantity - m_SpentQuantity - m_SpentQuantityTotal ) / m_InitItemQuantity), 0, 1);
        }
        else
        {
            return Math.Clamp((1 - (m_InitItemQuantity - m_SpentQuantityTotal ) / m_InitItemQuantity), 0, 1);
        }
    }
References Math::Clamp(), m_InitItemQuantity, CAContinuousQuantityRepeat::m_SpentQuantity, and m_SpentQuantityTotal.
Setup()
override void CAContinuousQuantityEdible::Setup (ActionData action_data) inline private
Definition at line 14 of file cacontinuousquantityedible.c.
    {
        super.Setup( action_data );
        if (m_InitItemQuantity < 0)
        {
            m_InitItemQuantity = action_data.m_MainItem.GetQuantity();
        }
    }
References m_InitItemQuantity, and ActionData::m_MainItem.
Member Data Documentation
m_InitItemQuantity
protected float CAContinuousQuantityEdible::m_InitItemQuantity private
Definition at line 3 of file cacontinuousquantityedible.c.
Referenced by CAContinuousQuantityEdible(), GetProgress(), and Setup().
m_SpentQuantityTotal
protected float CAContinuousQuantityEdible::m_SpentQuantityTotal private
Definition at line 4 of file cacontinuousquantityedible.c.
Referenced by CAContinuousQuantityEdible(), CalcAndSetQuantity(), and GetProgress().