DayzKode: WorldData Class Reference
WorldData Class Reference
Keeps information about currently loaded world, like temperature.
Private Member Functions
void BaseTempDebug (int month, int day)
protected float CalcBaseEnvironmentTemperature (float monthday, float daytime)
float GetApproxSunriseTime (float monthday)
float GetApproxSunsetTime (float monthday)
array< vector > GetArtyFiringPos ()
float GetBaseEnvTemperature ()
float GetBaseEnvTemperatureExact (int month, int day, int hour, int minute)
float GetDayTemperature ()
float GetNightTemperature ()
void Init ()
override void Init ()
override void Init ()
void UpdateBaseEnvTemperature (float timeslice)
bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
override bool WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time)
void WorldData ()
Private Attributes
const int BAD_WEATHER = 3
const int BAD_WEATHER_CHANCE = 80
const int CLEAR_WEATHER = 1
const int CLEAR_WEATHER_CHANCE = 30
const int CLOUDY_WEATHER = 2
protected int m_badWeatherChance = BAD_WEATHER_CHANCE
protected int m_chance = 50
protected int m_choosenWeather = 1
protected int m_clearWeatherChance = CLEAR_WEATHER_CHANCE
protected float m_DayTemperature
protected float m_EnvironmentTemperature
protected ref array< vector > m_FiringPos
protected int m_lastWeather = 0
protected float m_MaxTemps [12]
protected float m_MinTemps [12]
protected float m_NightTemperature
protected int m_sameWeatherCnt = 0
protected int m_stepValue = 5
protected float m_Sunrise_Jan
protected float m_Sunrise_Jul
protected float m_Sunset_Jan
protected float m_Sunset_Jul
protected float m_Timer
protected Weather m_Weather
const int OVERCAST_MAX_TIME = 900
const int OVERCAST_MIN_TIME = 600
const float RAIN_THRESHOLD = 0.6
const int RAIN_TIME_MAX = 120
const int RAIN_TIME_MIN = 60
const float STORM_THRESHOLD = 0.9
Static Private Attributes
static protected const ref array< vector > CHERNARUS_ARTY_STRIKE_POS
static protected const ref array< vector > LIVONIA_ARTY_STRIKE_POS
Detailed Description
Keeps information about currently loaded world, like temperature.
Definition at line 2 of file worlddata.c.
Constructor & Destructor Documentation
WorldData()
void WorldData::WorldData () inline private
Definition at line 17 of file worlddata.c.
    {
        Init();
    }
References Init().
Member Function Documentation
BaseTempDebug()
void WorldData::BaseTempDebug (int month, int day) inline private
Definition at line 139 of file worlddata.c.
    {
        Print("--------------------");
        for ( int i = 0; i < 24; i++ )
        {
            for ( int j = 0; j < 6; j++ )
            {
                int minute = ( j * 10 );
                Print(string.Format( "%1:%2      %3", i, minute, GetBaseEnvTemperatureExact( month, day, i, minute ) ) );
            }
        }
    }
References GetBaseEnvTemperatureExact(), and Print().
CalcBaseEnvironmentTemperature()
protected float WorldData::CalcBaseEnvironmentTemperature (float monthday, float daytime) inline private
Definition at line 51 of file worlddata.c.
    {
        float approxSunrise = GetApproxSunriseTime( monthday );
        float approxSunset = GetApproxSunsetTime( monthday );
        float dayLight = approxSunset - approxSunrise;
        float nightTime = 24.0 - dayLight;
        int tempArrayIndex = Math.Floor(monthday) - 1;
        int tempArrayIndexToLerp = tempArrayIndex + 1;
        if ( tempArrayIndexToLerp >= 12 )
            tempArrayIndexToLerp = 0;
        float tempArrayLerp = monthday - Math.Floor(monthday);
        float minTempA = m_MinTemps[tempArrayIndex];
        float minTempB = m_MinTemps[tempArrayIndexToLerp];
        float maxTempA = m_MaxTemps[tempArrayIndex];
        float maxTempB = m_MaxTemps[tempArrayIndexToLerp];
        float eveningMinA = minTempA + ( 0.5 * Math.AbsFloat( minTempA - maxTempA ) );
        float eveningMinB = minTempB + ( 0.5 * Math.AbsFloat( minTempB - maxTempB ) );
        if ( ( daytime >= approxSunrise ) && ( daytime <= approxSunset ) ) {
            if ( daytime <= ( approxSunrise + ( dayLight * 0.75 ) ) )
                return Math.Lerp(
                    Math.Lerp( minTempA, minTempB, tempArrayLerp ),
                    Math.Lerp( maxTempA, maxTempB, tempArrayLerp ),
                    ( ( daytime - approxSunrise ) / ( dayLight * 0.75 ) ) );
            else
                return Math.Lerp(
                    Math.Lerp( maxTempA, maxTempB, tempArrayLerp ),
                    Math.Lerp( eveningMinA, eveningMinB, tempArrayLerp ),
                    ( ( ( daytime - approxSunrise ) - ( dayLight * 0.75 ) ) / ( dayLight - ( dayLight * 0.75 ) ) ) );
        } else {
            if ( ( daytime > approxSunset ) && ( daytime < 24 ) )
                return Math.Lerp(
                    Math.Lerp( eveningMinA, eveningMinB, tempArrayLerp ),
                    Math.Lerp( minTempA, minTempB, tempArrayLerp ),
                    ( ( daytime - approxSunset ) / ( 24 - approxSunset ) ) / 2.0 );
            else
                return Math.Lerp(
                    Math.Lerp( eveningMinA, eveningMinB, tempArrayLerp ),
                    Math.Lerp( minTempA, minTempB, tempArrayLerp ),
                    ( ( ( daytime + ( 24 - approxSunset ) ) / nightTime ) / 2.0 ) + 0.5 );
        }
    }
References Math::AbsFloat(), Math::Floor(), GetApproxSunriseTime(), GetApproxSunsetTime(), Math::Lerp(), m_MaxTemps, and m_MinTemps.
Referenced by GetBaseEnvTemperatureExact(), and UpdateBaseEnvTemperature().
GetApproxSunriseTime()
float WorldData::GetApproxSunriseTime (float monthday) inline private
Definition at line 37 of file worlddata.c.
    {
        if ( monthday <= 8.0 )
            return ( ( m_Sunrise_Jan - m_Sunrise_Jul ) / ( 8 - 1 ) ) * ( 1 - monthday ) + m_Sunrise_Jan;
        else
            return ( ( ( monthday - 8 ) * ( m_Sunrise_Jan - m_Sunrise_Jul ) ) / ( 13 - 8 ) ) + m_Sunrise_Jul;
    }
References m_Sunrise_Jan, and m_Sunrise_Jul.
Referenced by CalcBaseEnvironmentTemperature().
GetApproxSunsetTime()
float WorldData::GetApproxSunsetTime (float monthday) inline private
Definition at line 44 of file worlddata.c.
    {
        if ( monthday <= 8.0 )
            return ( ( m_Sunset_Jan - m_Sunset_Jul ) / (8 - 1) ) * ( 1 - monthday ) + m_Sunset_Jan;
        else
            return ( ( ( monthday - 8 ) * ( m_Sunset_Jan - m_Sunset_Jul ) ) / ( 13 - 8 ) ) + m_Sunset_Jul;
    }
References m_Sunset_Jan, and m_Sunset_Jul.
Referenced by CalcBaseEnvironmentTemperature().
GetArtyFiringPos()
array< vector > WorldData::GetArtyFiringPos () inline private
Definition at line 133 of file worlddata.c.
    {
        return m_FiringPos;
    }
References m_FiringPos.
Referenced by ContaminatedArea_Dynamic::EEOnCECreate().
GetBaseEnvTemperature()
float WorldData::GetBaseEnvTemperature () inline private
Definition at line 106 of file worlddata.c.
    {
        return m_EnvironmentTemperature;
    }
References m_EnvironmentTemperature.
GetBaseEnvTemperatureExact()
float WorldData::GetBaseEnvTemperatureExact (int month, int day, int hour, int minute) inline private
Definition at line 110 of file worlddata.c.
    {
        return CalcBaseEnvironmentTemperature( month + ( day / 32.0 ), hour + ( minute / 60.0 ) );
    }
References CalcBaseEnvironmentTemperature().
Referenced by BaseTempDebug().
GetDayTemperature()
float WorldData::GetDayTemperature () inline private
Definition at line 116 of file worlddata.c.
    {
        return m_DayTemperature;
    }
References m_DayTemperature.
GetNightTemperature()
float WorldData::GetNightTemperature () inline private
Definition at line 121 of file worlddata.c.
    {
        return m_NightTemperature;
    }
References m_NightTemperature.
Init() [1/3]
void WorldData::Init () inline private
Definition at line 22 of file worlddata.c.
    {
        m_DayTemperature = 10;  // legacy, no longer used
        m_NightTemperature = 6; // legacy, no longer used
        m_Weather = g_Game.GetWeather();
        m_EnvironmentTemperature = 12.0;
        m_Timer = 0.0;
        m_Sunrise_Jan = 8.54;
        m_Sunset_Jan = 15.52;
        m_Sunrise_Jul = 3.26;
        m_Sunset_Jul = 20.73;
        m_MaxTemps = {3,5,7,14,19,24,26,25,21,16,10,5};
        m_MinTemps = {-3,-2,0,4,9,14,18,17,12,7,4,0};
    }
References g_Game, m_DayTemperature, m_EnvironmentTemperature, m_MaxTemps, m_MinTemps, m_NightTemperature, m_Sunrise_Jan, m_Sunrise_Jul, m_Sunset_Jan, m_Sunset_Jul, m_Timer, and m_Weather.
Referenced by WorldData().
Init() [2/3]
override void WorldData::Init () inline private
Definition at line 41 of file chernarusplus.c.
    {
        super.Init();
        // new temperature curve settings
        m_Sunrise_Jan = 8.54;
        m_Sunset_Jan = 15.52;
        m_Sunrise_Jul = 3.26;
        m_Sunset_Jul = 20.73;
        int tempIdx;
        m_MinTemps = {-3,-2,0,4,9,14,18,17,12,7,4,0};
        if (CfgGameplayHandler.GetEnvironmentMinTemps() && CfgGameplayHandler.GetEnvironmentMinTemps().Count() == 12)
        {
            for (tempIdx = 0; tempIdx < CfgGameplayHandler.GetEnvironmentMinTemps().Count(); tempIdx++)
            {
                m_MinTemps[tempIdx] = CfgGameplayHandler.GetEnvironmentMinTemps().Get(tempIdx);
            }
        }
        m_MaxTemps = {3,5,7,14,19,24,26,25,21,16,10,5};
        if (CfgGameplayHandler.GetEnvironmentMaxTemps() && CfgGameplayHandler.GetEnvironmentMaxTemps().Count() == 12)
        {
            for (tempIdx = 0; tempIdx < CfgGameplayHandler.GetEnvironmentMaxTemps().Count(); tempIdx++)
            {
                m_MaxTemps[tempIdx] = CfgGameplayHandler.GetEnvironmentMaxTemps().Get(tempIdx);
            }
        }
        m_FiringPos = CHERNARUS_ARTY_STRIKE_POS;
    }
References CHERNARUS_ARTY_STRIKE_POS, Count, CfgGameplayHandler::GetEnvironmentMaxTemps(), and CfgGameplayHandler::GetEnvironmentMinTemps().
Init() [3/3]
override void WorldData::Init () inline private
Definition at line 43 of file enoch.c.
    {
        super.Init();
        // new temperature curve settings
        m_Sunrise_Jan = 8.4;
        m_Sunset_Jan = 15.63;
        m_Sunrise_Jul = 3.65;
        m_Sunset_Jul = 20.35;
        int tempIdx;
        m_MinTemps = {-7,-7.4,-4.1,1.5,7,11.3,13.4,13.1,9.3,5.3,0.8,-3.6};
        if (CfgGameplayHandler.GetEnvironmentMinTemps() && CfgGameplayHandler.GetEnvironmentMinTemps().Count() == 12)
        {
            for (tempIdx = 0; tempIdx < CfgGameplayHandler.GetEnvironmentMinTemps().Count(); tempIdx++)
            {
                m_MinTemps[tempIdx] = CfgGameplayHandler.GetEnvironmentMinTemps().Get(tempIdx);
            }
        }
        m_MaxTemps = {-2.5,-2.1,2.3,9,15.5,19.4,20.9,20.4,16,10.5,4.2,0.1};
        if (CfgGameplayHandler.GetEnvironmentMaxTemps() && CfgGameplayHandler.GetEnvironmentMaxTemps().Count() == 12)
        {
            for (tempIdx = 0; tempIdx < CfgGameplayHandler.GetEnvironmentMaxTemps().Count(); tempIdx++)
            {
                m_MaxTemps[tempIdx] = CfgGameplayHandler.GetEnvironmentMaxTemps().Get(tempIdx);
            }
        }
        m_FiringPos = LIVONIA_ARTY_STRIKE_POS;
    }
References Count, CfgGameplayHandler::GetEnvironmentMaxTemps(), CfgGameplayHandler::GetEnvironmentMinTemps(), and LIVONIA_ARTY_STRIKE_POS.
UpdateBaseEnvTemperature()
void WorldData::UpdateBaseEnvTemperature (float timeslice) inline private
Definition at line 93 of file worlddata.c.
    {
        m_Timer += timeslice;
        if ( m_Timer > 30 )
        {
            int year, month, day, hour, minute;
            GetGame().GetWorld().GetDate( year, month, day, hour, minute );
            m_EnvironmentTemperature = CalcBaseEnvironmentTemperature( month + ( day / 32.0 ), hour + ( minute / 60.0 ) );
            m_Timer = 0;
        }
    }
References CalcBaseEnvironmentTemperature(), World::GetDate(), GetGame(), CGame::GetWorld(), m_EnvironmentTemperature, and m_Timer.
Referenced by MissionBase::OnUpdate().
WeatherOnBeforeChange() [1/3]
bool WorldData::WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
Definition at line 126 of file worlddata.c.
    {
        // default behaviour is same like setting MissionWeather (in Weather) to true
        return false;
    }
Referenced by WeatherPhenomenon::OnBeforeChange().
WeatherOnBeforeChange() [2/3]
override bool WorldData::WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
Definition at line 73 of file chernarusplus.c.
    {
        float phmnValue 0;
        int phmnTime 5;
        int phmnLength 10;
        m_Weather.SetStorm( 1.0, STORM_THRESHOLD, 45 );
        m_Weather.SetRainThresholds( 0.0, 1.0, 60 );
        m_Weather.SetWindMaximumSpeed( 20 );
        m_Weather.SetWindFunctionParams( 0.1, 1.0, 20 );
        switch( type )
        {
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.OVERCAST:
                //went something goes wrong choose some default random weather
                phmnValue = Math.RandomFloatInclusive( 0.2, 0.7 );
                phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                //----
                //calculate next weather
                m_chance = Math.RandomIntInclusive( 0, 100 );
                //--
                if ( m_lastWeather == CLEAR_WEATHER )
                {
                    m_clearWeatherChance -= ( m_stepValue * m_sameWeatherCnt);                  //decrease the chance of the same weather
                }
                if ( m_lastWeather == CLOUDY_WEATHER )
                {
                    m_clearWeatherChance += ( m_stepValue * m_sameWeatherCnt);                  //increase the chance of the better weather
                    //m_badWeatherChance += ( m_stepValue * m_sameWeatherCnt);
                }
                if ( m_lastWeather == BAD_WEATHER )
                {
                    m_clearWeatherChance += m_stepValue;                                        //increase the chance of the better weather slightly
                    m_badWeatherChance += (( m_stepValue * m_sameWeatherCnt ) + m_stepValue  ); //decrease the chance of the same weather rapidly
                }
                //----
                if ( m_chance < m_clearWeatherChance )
                {
                    m_choosenWeather = CLEAR_WEATHER;
                    if ( m_lastWeather == CLEAR_WEATHER )
                        m_sameWeatherCnt ++;
                }
                else if ( m_chance > m_badWeatherChance )
                {
                    m_choosenWeather = BAD_WEATHER;
                    if ( m_lastWeather == BAD_WEATHER )
                        m_sameWeatherCnt ++;
                }
                else
                {
                    m_choosenWeather = CLOUDY_WEATHER;
                    if ( m_lastWeather == CLOUDY_WEATHER )
                        m_sameWeatherCnt ++;
                }
                if ( m_choosenWeather != m_lastWeather )
                    m_sameWeatherCnt = 0;
                m_clearWeatherChance = CLEAR_WEATHER_CHANCE;
                m_badWeatherChance = BAD_WEATHER_CHANCE;
                //----
                //set choosen weather
                if ( m_choosenWeather == CLEAR_WEATHER  )
                {
                    m_lastWeather = CLEAR_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.0, 0.3 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                }
                if ( m_choosenWeather == CLOUDY_WEATHER )
                {
                    m_lastWeather = CLOUDY_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.3, 0.6 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                }
                if ( m_choosenWeather == BAD_WEATHER )
                {
                    m_lastWeather = BAD_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.6, 1.0 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                }
                m_Weather.GetOvercast().Set( phmnValue, phmnTime, phmnLength );
                Debug.Log(string.Format("Chernarus::Weather::Overcast:: (%1) overcast: %2", g_Game.GetDayTime(), actual));
                Debug.Log(string.Format("Chernarus::Weather::Overcast::Rain:: (%1) %2", g_Game.GetDayTime(), m_Weather.GetRain().GetActual()));
                return true;
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.RAIN:
                float actualOvercast = m_Weather.GetOvercast().GetActual();
                m_chance = Math.RandomIntInclusive( 0, 100 );
                phmnValue = 0.2;
                phmnTime = 90;
                phmnLength = 30;
                if ( actualOvercast <= RAIN_THRESHOLD )
                {
                    m_Weather.GetRain().Set( 0.0, RAIN_TIME_MIN, RAIN_TIME_MAX );
                    Debug.Log(string.Format("Chernarus::Weather::Rain::ForceEnd:: (%1) %2 -> 0", g_Game.GetDayTime(), actual));
                    return true;
                }
                if ( actualOvercast > STORM_THRESHOLD )
                {
                    phmnValue = Math.RandomFloatInclusive( 0.8, 1.0 );
                    phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                    phmnLength = 0;
                    m_Weather.GetRain().Set( phmnValue, phmnTime, phmnLength );
                    Debug.Log(string.Format("Chernarus::Weather::Rain::ForceStorm:: (%1) %2 -> %3", g_Game.GetDayTime(), actual, phmnValue));
                    return true;
                }
                //make a differnce in "normal rain"
                if ( actualOvercast < 0.75 )
                {
                    if ( m_chance < 30 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.1, 0.3 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 60 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.2, 0.5 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 80 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.0, 0.2 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else //also have the chance to not have rain at all
                    {
                        phmnValue = 0;
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 120;
                    }
                }
                else
                {
                    if ( m_chance < 25 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.5, 0.7 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 50 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.2, 0.4 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 75 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.4, 0.6 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else //also have the chance to not have rain at all
                    {
                        phmnValue = 0;
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 120;
                    }
                }
                m_Weather.GetRain().Set( phmnValue, phmnTime, phmnLength );
                Debug.Log(string.Format("Chernarus::Weather::Rain:: (%1) %2", g_Game.GetDayTime(), actual));
                return true;
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.FOG:
                float fogMin = 0.0;
                float fogMax = 0.15;
                float fogTime = 1800.0;
                float fogyMorning = Math.RandomFloatInclusive( 0.0, 1.0 );
                if ( fogyMorning > 0.85 )
                {
                    if ( (g_Game.GetDayTime() > 4 && g_Game.GetDayTime() < 7 ) )
                    {
                        fogMin = 0.10;
                        fogMax = 0.35;
                        fogTime = 300;
                    }
                }
                if ( m_Weather.GetOvercast().GetActual() < 0.3 )
                {
                    fogMin = 0.0;
                    fogMax = 0.08;
                    fogTime = 900.0;
                }
                m_Weather.GetFog().Set( Math.RandomFloatInclusive( fogMin, fogMax ), fogTime, 0);
                Debug.Log(string.Format("Chernarus::Weather::Fog:: (%1) %2", g_Game.GetDayTime(), actual));
                return true;
        }
        return false;
    }
References BAD_WEATHER, BAD_WEATHER_CHANCE, CLEAR_WEATHER, CLEAR_WEATHER_CHANCE, CLOUDY_WEATHER, g_Game, Debug::Log(), m_sameWeatherCnt, m_stepValue, Math::RandomFloatInclusive(), Math::RandomInt(), and Math::RandomIntInclusive().
WeatherOnBeforeChange() [3/3]
override bool WorldData::WeatherOnBeforeChange (EWeatherPhenomenon type, float actual, float change, float time) inline private
Definition at line 75 of file enoch.c.
    {
        float phmnValue 0;
        int phmnTime 5;
        int phmnLength 10;
        m_Weather.SetStorm( 1.0, STORM_THRESHOLD, 20 );
        m_Weather.SetRainThresholds( 0.0, 1.0, 60 );
        m_Weather.SetWindMaximumSpeed( 20 );
        m_Weather.SetWindFunctionParams( 0.1, 1.0, 20 );
        switch( type )
        {
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.OVERCAST:
                //went something goes wrong choose some default random weather
                phmnValue = Math.RandomFloatInclusive( 0.1, 0.4 );
                phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                //----
                //calculate next weather
                m_chance = Math.RandomIntInclusive( 0, 100 );
                //--
                if ( m_lastWeather == CLEAR_WEATHER )
                {
                    m_clearWeatherChance -= ( m_stepValue * m_sameWeatherCnt);                  //decrease the chance of the same weather
                }
                if ( m_lastWeather == CLOUDY_WEATHER )
                {
                    m_clearWeatherChance += ( m_stepValue * m_sameWeatherCnt);                  //increase the chance of the better weather
                    m_badWeatherChance -= ( m_stepValue * m_sameWeatherCnt);
                }
                if ( m_lastWeather == BAD_WEATHER )
                {
                    m_clearWeatherChance += m_stepValue;                                        //increase the chance of the better weather slightly
                    m_badWeatherChance += ( m_stepValue * m_sameWeatherCnt );   //decrease the chance of the same weather
                }
                //----
                if ( m_chance < m_clearWeatherChance )
                {
                    m_choosenWeather = CLEAR_WEATHER;
                    if ( m_lastWeather == CLEAR_WEATHER )
                        m_sameWeatherCnt ++;
                }
                else if ( m_chance > m_badWeatherChance )
                {
                    m_choosenWeather = BAD_WEATHER;
                    if ( m_lastWeather == BAD_WEATHER )
                        m_sameWeatherCnt ++;
                }
                else
                {
                    m_choosenWeather = CLOUDY_WEATHER;
                    if ( m_lastWeather == CLOUDY_WEATHER )
                        m_sameWeatherCnt ++;
                }
                if ( m_choosenWeather != m_lastWeather )
                    m_sameWeatherCnt = 0;
                m_clearWeatherChance = CLEAR_WEATHER_CHANCE;
                m_badWeatherChance = BAD_WEATHER_CHANCE;
                //----
                //set choosen weather
                if ( m_choosenWeather == CLEAR_WEATHER  )
                {
                    m_lastWeather = CLEAR_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.0, 0.3 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                }
                if ( m_choosenWeather == CLOUDY_WEATHER )
                {
                    m_lastWeather = CLOUDY_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.3, 0.7 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( 0, OVERCAST_MIN_TIME );
                }
                if ( m_choosenWeather == BAD_WEATHER )
                {
                    m_lastWeather = BAD_WEATHER;
                    phmnValue = Math.RandomFloatInclusive( 0.7, 1.0 );
                    phmnTime = Math.RandomIntInclusive( OVERCAST_MIN_TIME, OVERCAST_MAX_TIME );
                    phmnLength = Math.RandomIntInclusive( 0, OVERCAST_MIN_TIME );
                }
                m_Weather.GetOvercast().Set( phmnValue, phmnTime, phmnLength );
                Debug.Log(string.Format("Enoch::Weather::Overcast:: (%1) overcast: %2", g_Game.GetDayTime(), actual));
                Debug.Log(string.Format("Enoch::Weather::Overcast::Rain:: (%1) %2", g_Game.GetDayTime(), m_Weather.GetRain().GetActual()));
                return true;
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.RAIN:
                float actualOvercast = m_Weather.GetOvercast().GetActual();
                m_chance = Math.RandomIntInclusive( 0, 100 );
                phmnValue = 0.2;
                phmnTime = 90;
                phmnLength = 30;
                if ( actualOvercast <= RAIN_THRESHOLD )
                {
                    m_Weather.GetRain().Set( 0.0, RAIN_TIME_MIN, RAIN_TIME_MAX );
                    Debug.Log(string.Format("Enoch::Weather::Rain::ForceEnd:: (%1) %2 -> 0", g_Game.GetDayTime(), actual));
                    return true;
                }
                if ( actualOvercast > STORM_THRESHOLD )
                {
                    phmnValue = Math.RandomFloatInclusive( 0.8, 1.0 );
                    phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                    phmnLength = 0;
                    m_Weather.GetRain().Set( phmnValue, phmnTime, phmnLength );
                    Debug.Log(string.Format("Enoch::Weather::Rain::ForceStorm:: (%1) %2 -> %3", g_Game.GetDayTime(), actual, phmnValue));
                    return true;
                }
                //make a differnce in "normal rain"
                if ( actualOvercast < 0.75 )
                {
                    if ( m_chance < 30 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.1, 0.3 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 60 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.2, 0.4 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 85 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.0, 0.2 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else //also have the chance to not have rain at all
                    {
                        phmnValue = 0;
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 120;
                    }
                }
                else if ( actualOvercast < STORM_THRESHOLD )
                {
                    if ( m_chance < 15 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.4, 0.6 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 50 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.2, 0.4 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else if ( m_chance < 90 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.6, 0.8 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else //also have the chance to not have rain at all
                    {
                        phmnValue = 0;
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 120;
                    }
                }
                else
                {
                    if ( m_chance < 50 )
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.9, 1.0 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                    else
                    {
                        phmnValue = Math.RandomFloatInclusive( 0.8, 0.9 );
                        phmnTime = Math.RandomInt( RAIN_TIME_MIN, RAIN_TIME_MAX );
                        phmnLength = 0;
                    }
                }
                m_Weather.GetRain().Set( phmnValue, phmnTime, phmnLength );
                Debug.Log(string.Format("Enoch::Weather::Rain:: (%1) %2", g_Game.GetDayTime(), actual));
                return true;
            //-----------------------------------------------------------------------------------------------------------------------------
            case EWeatherPhenomenon.FOG:
                int year, month, day, hour, minute;
                GetGame().GetWorld().GetDate(year, month, day, hour, minute);
                if (( hour >= 1 ) && ( hour <= 5 ))
                {
                    m_Weather.GetFog().Set( 0.1, 1800, 0 );
                } else {
                    m_Weather.GetFog().Set( 0.0, 1800, 0 );
                }
                Debug.Log(string.Format("Enoch::Weather::Fog:: (%1) %2", g_Game.GetDayTime(), actual));
                return true;
        }
        return false;
    }
References BAD_WEATHER, BAD_WEATHER_CHANCE, CLEAR_WEATHER, CLEAR_WEATHER_CHANCE, CLOUDY_WEATHER, g_Game, World::GetDate(), GetGame(), CGame::GetWorld(), Debug::Log(), m_sameWeatherCnt, m_stepValue, Math::RandomFloatInclusive(), Math::RandomInt(), and Math::RandomIntInclusive().
Member Data Documentation
BAD_WEATHER
const int WorldData::BAD_WEATHER = 3 private
Definition at line 15 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
BAD_WEATHER_CHANCE
const int WorldData::BAD_WEATHER_CHANCE = 80 private
Definition at line 18 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
CHERNARUS_ARTY_STRIKE_POS
protected const ref array<vector> WorldData::CHERNARUS_ARTY_STRIKE_POS static private
Initial value:
=
    {
        "-500.00 165.00 5231.69",
        "-500.00 300.00 9934.41",
        "10406.86 192.00 15860.00",
        "4811.75 370.00 15860.00",
        "-500.00 453.00 15860.00"
    }
Definition at line 32 of file chernarusplus.c.
Referenced by Init().
CLEAR_WEATHER
const int WorldData::CLEAR_WEATHER = 1 private
Definition at line 13 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
CLEAR_WEATHER_CHANCE
const int WorldData::CLEAR_WEATHER_CHANCE = 30 private
Definition at line 17 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
CLOUDY_WEATHER
const int WorldData::CLOUDY_WEATHER = 2 private
Definition at line 14 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
LIVONIA_ARTY_STRIKE_POS
protected const ref array<vector> WorldData::LIVONIA_ARTY_STRIKE_POS static private
Initial value:
=
    {
        "7440.00 417.00 -500.00",
        "-500.00 276.00 5473.00",
        "-500.00 265.00 9852.00",
        "4953.00 240.00 13300.00",
        "9620.00 188.00 13300.00",
        "13300.00 204.00 10322.00",
        "13300.00 288.00 6204.00",
        "13300.00 296.00 -500.00"
    }
Definition at line 31 of file enoch.c.
Referenced by Init().
m_badWeatherChance
protected int WorldData::m_badWeatherChance = BAD_WEATHER_CHANCE private
Definition at line 22 of file chernarusplus.c.
m_chance
protected int WorldData::m_chance = 50 private
Definition at line 26 of file chernarusplus.c.
m_choosenWeather
protected int WorldData::m_choosenWeather = 1 private
Definition at line 28 of file chernarusplus.c.
m_clearWeatherChance
protected int WorldData::m_clearWeatherChance = CLEAR_WEATHER_CHANCE private
Definition at line 20 of file chernarusplus.c.
m_DayTemperature
protected float WorldData::m_DayTemperature private
Definition at line 4 of file worlddata.c.
Referenced by GetDayTemperature(), and Init().
m_EnvironmentTemperature
protected float WorldData::m_EnvironmentTemperature private
Definition at line 7 of file worlddata.c.
Referenced by GetBaseEnvTemperature(), Init(), and UpdateBaseEnvTemperature().
m_FiringPos
protected ref array<vector> WorldData::m_FiringPos private
Definition at line 15 of file worlddata.c.
Referenced by GetArtyFiringPos().
m_lastWeather
protected int WorldData::m_lastWeather = 0 private
Definition at line 29 of file chernarusplus.c.
m_MaxTemps
protected float WorldData::m_MaxTemps[12] private
Definition at line 9 of file worlddata.c.
Referenced by CalcBaseEnvironmentTemperature(), and Init().
m_MinTemps
protected float WorldData::m_MinTemps[12] private
Definition at line 10 of file worlddata.c.
Referenced by CalcBaseEnvironmentTemperature(), and Init().
m_NightTemperature
protected float WorldData::m_NightTemperature private
Definition at line 5 of file worlddata.c.
Referenced by GetNightTemperature(), and Init().
m_sameWeatherCnt
protected int WorldData::m_sameWeatherCnt = 0 private
Definition at line 24 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
m_stepValue
protected int WorldData::m_stepValue = 5 private
Definition at line 25 of file chernarusplus.c.
Referenced by WeatherOnBeforeChange().
m_Sunrise_Jan
protected float WorldData::m_Sunrise_Jan private
Definition at line 11 of file worlddata.c.
Referenced by GetApproxSunriseTime(), and Init().
m_Sunrise_Jul
protected float WorldData::m_Sunrise_Jul private
Definition at line 13 of file worlddata.c.
Referenced by GetApproxSunriseTime(), and Init().
m_Sunset_Jan
protected float WorldData::m_Sunset_Jan private
Definition at line 12 of file worlddata.c.
Referenced by GetApproxSunsetTime(), and Init().
m_Sunset_Jul
protected float WorldData::m_Sunset_Jul private
Definition at line 14 of file worlddata.c.
Referenced by GetApproxSunsetTime(), and Init().
m_Timer
protected float WorldData::m_Timer private
Definition at line 8 of file worlddata.c.
Referenced by Init(), and UpdateBaseEnvTemperature().
m_Weather
protected Weather WorldData::m_Weather private
Definition at line 6 of file worlddata.c.
Referenced by Init().
OVERCAST_MAX_TIME
const int WorldData::OVERCAST_MAX_TIME = 900 private
Definition at line 8 of file chernarusplus.c.
OVERCAST_MIN_TIME
const int WorldData::OVERCAST_MIN_TIME = 600 private
Definition at line 7 of file chernarusplus.c.
RAIN_THRESHOLD
const float WorldData::RAIN_THRESHOLD = 0.6 private
Definition at line 4 of file chernarusplus.c.
RAIN_TIME_MAX
const int WorldData::RAIN_TIME_MAX = 120 private
Definition at line 11 of file chernarusplus.c.
RAIN_TIME_MIN
const int WorldData::RAIN_TIME_MIN = 60 private
Definition at line 10 of file chernarusplus.c.
STORM_THRESHOLD
const float WorldData::STORM_THRESHOLD = 0.9 private
Definition at line 5 of file chernarusplus.c.