DayzKode: MapHandler Class Reference
MapHandler Class Reference
Private Member Functions
void MapHandler (Widget w)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnKeyDown (Widget w, int x, int y, int key)
Private Attributes
protected Widget m_Root
Detailed Description
Definition at line 1 of file maphandler.c.
Constructor & Destructor Documentation
MapHandler()
void MapHandler::MapHandler (Widget w) inline private
Definition at line 5 of file maphandler.c.
    {
        m_Root = w;
        m_Root.SetHandler(this);
    }
References m_Root.
Member Function Documentation
OnDoubleClick()
override bool MapHandler::OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 22 of file maphandler.c.
    {
        super.OnDoubleClick(w, x, y, button);
        vector screen_to_map = MapWidget.Cast(w).ScreenToMap(Vector(x,y,0));
        MapMenu m = MapMenu.Cast(g_Game.GetUIManager().FindMenu(MENU_MAP));
        int rand = Math.RandomInt(0,eMapMarkerTypes.MARKERTYPE_MAX);
        //m.AddMarker(screen_to_map,ARGB(255,255,0,0),rand);
        //m.AddUserMark(screen_to_map, "marker", ARGB(255,0,0,255), "\\dz\\gear\\navigation\\data\\map_tree_ca.paa");
        return true;
    }
References g_Game, MENU_MAP, Math::RandomInt(), MapWidget::ScreenToMap(), Vector(), x, and y.
OnKeyDown()
override bool MapHandler::OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 11 of file maphandler.c.
    {
        if (!super.OnKeyDown(w, x, y, key))
            return false;
        vector screen_to_map = MapWidget.Cast(w).ScreenToMap(Vector(x,y,0));
        Print(key);
        Print(screen_to_map);
        return true;
    }
References Print(), MapWidget::ScreenToMap(), Vector(), x, and y.
Member Data Documentation
m_Root
protected Widget MapHandler::m_Root private
Definition at line 3 of file maphandler.c.
Referenced by MapHandler().