DayzKode: Edible_Base Class Reference
Edible_Base Class Reference
Private Member Functions
void BoxCerealCrunchin ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeCookedOnStick ()
override bool CanBeSkinned ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDecay ()
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
bool ConditionAttach (EntityAI parent)
bool ConditionAttach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
bool ConditionDetach (EntityAI parent)
override float GetDisinfectQuantity (int system=0, Param param1=null)
void HumanSteakMeat ()
override void InitItemVariables ()
override bool IsCorpse ()
override bool IsCorpse ()
override bool IsCorpse ()
override bool IsCorpse ()
override bool IsFruit ()
override bool IsFruit ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override bool IsMeat ()
override void OnConsume (float amount, PlayerBase consumer)
override void OnConsume (float amount, PlayerBase consumer)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
Detailed Description
Definition at line 1 of file bearsteakmeat.c.
Member Function Documentation
BoxCerealCrunchin()
void Edible_Base::BoxCerealCrunchin () inline private
Definition at line 3 of file boxcerealcrunchin.c.
    {
    }
CanBeCooked() [1/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file bearsteakmeat.c.
    {
        return true;
    }
Referenced by ProcessItemToCook().
CanBeCooked() [2/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file bitterlings.c.
    {
        return true;
    }
CanBeCooked() [3/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file boarsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [4/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file caninaberry.c.
    {
        return true;
    }
CanBeCooked() [5/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file carp.c.
    {
        return false;
    }
CanBeCooked() [6/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file carpfilletmeat.c.
    {
        return true;
    }
CanBeCooked() [7/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file chicken_colorbase.c.
    {
        return false;
    }
CanBeCooked() [8/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file chickenbreastmeat.c.
    {
        return true;
    }
CanBeCooked() [9/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file cowsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [10/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file deersteakmeat.c.
    {
        return true;
    }
CanBeCooked() [11/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file foxsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [12/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file goatsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [13/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file humansteakmeat.c.
    {
        return true;
    }
CanBeCooked() [14/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file lard.c.
    {
        return true;
    }
CanBeCooked() [15/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file mackerel.c.
    {
        return false;
    }
CanBeCooked() [16/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file mackerelfilletmeat.c.
    {
        return true;
    }
CanBeCooked() [17/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file mouflonsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [18/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file pigsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [19/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file rabbit.c.
    {
        return false;
    }
CanBeCooked() [20/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file rabbitlegmeat.c.
    {
        return true;
    }
CanBeCooked() [21/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file sambucusberry.c.
    {
        return true;
    }
CanBeCooked() [22/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file sardines.c.
    {
        return true;
    }
CanBeCooked() [23/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file sheepsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [24/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 3 of file wolfsteakmeat.c.
    {
        return true;
    }
CanBeCooked() [25/25]
override bool Edible_Base::CanBeCooked () inline private
Definition at line 8 of file worm.c.
    {
        return false;
    }
CanBeCookedOnStick() [1/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file bearsteakmeat.c.
    {
        return true;
    }
Referenced by ActionCookOnStick::ActionCondition(), and CookOnStick().
CanBeCookedOnStick() [2/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file bitterlings.c.
    {
        return true;
    }
CanBeCookedOnStick() [3/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file boarsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [4/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file caninaberry.c.
    {
        return false;
    }
CanBeCookedOnStick() [5/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file carp.c.
    {
        return false;
    }
CanBeCookedOnStick() [6/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file carpfilletmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [7/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file chicken_colorbase.c.
    {
        return false;
    }
CanBeCookedOnStick() [8/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file chickenbreastmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [9/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file cowsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [10/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file deersteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [11/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file foxsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [12/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file goatsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [13/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 13 of file humansteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [14/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file lard.c.
    {
        return true;
    }
CanBeCookedOnStick() [15/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file mackerel.c.
    {
        return false;
    }
CanBeCookedOnStick() [16/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file mackerelfilletmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [17/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file mouflonsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [18/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file pigsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [19/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file rabbit.c.
    {
        return false;
    }
CanBeCookedOnStick() [20/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file rabbitlegmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [21/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file sambucusberry.c.
    {
        return false;
    }
CanBeCookedOnStick() [22/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file sardines.c.
    {
        return true;
    }
CanBeCookedOnStick() [23/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file sheepsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [24/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 8 of file wolfsteakmeat.c.
    {
        return true;
    }
CanBeCookedOnStick() [25/25]
override bool Edible_Base::CanBeCookedOnStick () inline private
Definition at line 3 of file worm.c.
    {
        return false;
    }
CanBeSkinned()
override bool Edible_Base::CanBeSkinned () inline private
Definition at line 23 of file chicken_colorbase.c.
    {
        return true;
    }
CanDecay() [1/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file bearsteakmeat.c.
    {
        return true;
    }
CanDecay() [2/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file bitterlings.c.
    {
        return true;
    }
CanDecay() [3/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file boarsteakmeat.c.
    {
        return true;
    }
CanDecay() [4/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file caninaberry.c.
    {
        return true;
    }
CanDecay() [5/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file carp.c.
    {
        return true;
    }
CanDecay() [6/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file carpfilletmeat.c.
    {
        return true;
    }
CanDecay() [7/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file chicken_colorbase.c.
    {
        return true;
    }
CanDecay() [8/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file chickenbreastmeat.c.
    {
        return true;
    }
CanDecay() [9/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file cowsteakmeat.c.
    {
        return true;
    }
CanDecay() [10/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file deersteakmeat.c.
    {
        return true;
    }
CanDecay() [11/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file foxsteakmeat.c.
    {
        return true;
    }
CanDecay() [12/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file goatsteakmeat.c.
    {
        return true;
    }
CanDecay() [13/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 23 of file humansteakmeat.c.
    {
        return true;
    }
CanDecay() [14/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file lard.c.
    {
        return true;
    }
CanDecay() [15/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file mackerel.c.
    {
        return true;
    }
CanDecay() [16/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file mackerelfilletmeat.c.
    {
        return true;
    }
CanDecay() [17/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file mouflonsteakmeat.c.
    {
        return true;
    }
CanDecay() [18/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file pigsteakmeat.c.
    {
        return true;
    }
CanDecay() [19/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file rabbit.c.
    {
        return true;
    }
CanDecay() [20/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file rabbitlegmeat.c.
    {
        return true;
    }
CanDecay() [21/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file sambucusberry.c.
    {
        return true;
    }
CanDecay() [22/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file sardines.c.
    {
        return true;
    }
CanDecay() [23/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file sheepsteakmeat.c.
    {
        return true;
    }
CanDecay() [24/24]
override bool Edible_Base::CanDecay () inline private
Definition at line 18 of file wolfsteakmeat.c.
    {
        return true;
    }
CanDetachAttachment() [1/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 49 of file disinfectantspray.c.
    {
        bool is_barrel = false;
        bool is_opened_barrel = false;
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        if ( is_opened_barrel || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanDetachAttachment() [2/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file guts.c.
    {
        bool is_barrel = false;
        bool is_opened_barrel = false;
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        if ( is_opened_barrel || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanDetachAttachment() [3/3]
override bool Edible_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file smallguts.c.
    {
        bool is_barrel = false;
        bool is_opened_barrel = false;
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        if ( is_opened_barrel || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [1/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 10 of file disinfectantspray.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        const int SLOTS_ARRAY = 8;
        bool is_barrel = false;
        bool is_opened_barrel = false;
        bool slot_test = true;
        string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Plant", "Nails", "OakBark", "BirchBark", "Lime", "Guts" };
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        // all of the barrel slots are empty
        for ( int i = 0; i < SLOTS_ARRAY ; i++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names[i]) != NULL )
            {
                slot_test = false;
                break;
            }
        }
        if ( ( is_opened_barrel && slot_test ) || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [2/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file guts.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        const int SLOTS_ARRAY = 8;
        bool is_barrel = false;
        bool is_opened_barrel = false;
        bool slot_test = true;
        string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant" };
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        // all of the barrel slots are empty
        for ( int i = 0; i < SLOTS_ARRAY ; i++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names[i]) != NULL )
            {
                slot_test = false;
                break;
            }
        }
        if ( ( is_opened_barrel && slot_test ) || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [3/3]
override bool Edible_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file smallguts.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        const int SLOTS_ARRAY = 8;
        bool is_barrel = false;
        bool is_opened_barrel = false;
        bool slot_test = true;
        string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant" };
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        // all of the barrel slots are empty
        for ( int i = 0; i < SLOTS_ARRAY ; i++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names[i]) != NULL )
            {
                slot_test = false;
                break;
            }
        }
        if ( ( is_opened_barrel && slot_test ) || !is_barrel )
        {
            return true;
        }
        return false;
    }
ConditionAttach() [1/2]
bool Edible_Base::ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file caninaberry.c.
    {
        //if Barrel_ColorBase
        if ( parent.IsInherited( Barrel_ColorBase ) )
        {
            Barrel_ColorBase barrel = Barrel_ColorBase.Cast( parent );
            if ( barrel.IsOpen() && !barrel.FindAttachmentBySlotName( "Nails" ) && !barrel.FindAttachmentBySlotName( "OakBark" ) && !barrel.FindAttachmentBySlotName( "BirchBark" ) && !barrel.FindAttachmentBySlotName( "Lime" ) && !barrel.FindAttachmentBySlotName( "Disinfectant" ) && !barrel.FindAttachmentBySlotName( "Guts" ) )
            {
                return true;
            }
        }
        return false;
    }
References Barrel_ColorBase::IsOpen().
ConditionAttach() [2/2]
bool Edible_Base::ConditionAttach (EntityAI parent) inline private
Definition at line 23 of file sambucusberry.c.
    {
        //if Barrel_ColorBase
        if ( parent.IsInherited( Barrel_ColorBase ) )
        {
            Barrel_ColorBase barrel = Barrel_ColorBase.Cast( parent );
            if ( barrel.IsOpen() && !barrel.FindAttachmentBySlotName( "Nails" ) && !barrel.FindAttachmentBySlotName( "OakBark" ) && !barrel.FindAttachmentBySlotName( "BirchBark" ) && !barrel.FindAttachmentBySlotName( "Lime" ) && !barrel.FindAttachmentBySlotName( "Disinfectant" ) && !barrel.FindAttachmentBySlotName( "Guts" ) )
            {
                return true;
            }
        }
        return false;
    }
References Barrel_ColorBase::IsOpen().
ConditionDetach() [1/2]
bool Edible_Base::ConditionDetach (EntityAI parent) inline private
Definition at line 39 of file caninaberry.c.
    {
        //if Barrel_ColorBase
        if ( parent.IsInherited( Barrel_ColorBase ) )
        {
            Barrel_ColorBase barrel = Barrel_ColorBase.Cast( parent );
            if ( !barrel.IsOpen() )
            {
                return false;
            }
        }
        return true;
    }
References Barrel_ColorBase::IsOpen().
ConditionDetach() [2/2]
bool Edible_Base::ConditionDetach (EntityAI parent) inline private
Definition at line 39 of file sambucusberry.c.
    {
        //if Barrel_ColorBase
        if ( parent.IsInherited( Barrel_ColorBase ) )
        {
            Barrel_ColorBase barrel = Barrel_ColorBase.Cast( parent );
            if ( !barrel.IsOpen() )
            {
                return false;
            }
        }
        return true;
    }
References Barrel_ColorBase::IsOpen().
GetDisinfectQuantity()
override float Edible_Base::GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 74 of file disinfectantspray.c.
    {
        return (GetQuantityMax() * 0.15);
    }
References GetQuantityMax().
HumanSteakMeat()
void Edible_Base::HumanSteakMeat () inline private
Definition at line 3 of file humansteakmeat.c.
    {
        InsertAgent(eAgents.BRAIN, 1);
    }
References InsertAgent().
InitItemVariables()
override void Edible_Base::InitItemVariables () inline private
Definition at line 4 of file disinfectantspray.c.
    {
        super.InitItemVariables();
        can_this_be_combined = true;
    }
References can_this_be_combined.
IsCorpse() [1/4]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file carp.c.
    {
        return true;
    }
Referenced by ItemBase::ProcessDecay().
IsCorpse() [2/4]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file chicken_colorbase.c.
    {
        return true;
    }
IsCorpse() [3/4]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file mackerel.c.
    {
        return true;
    }
IsCorpse() [4/4]
override bool Edible_Base::IsCorpse () inline private
Definition at line 13 of file rabbit.c.
    {
        return true;
    }
IsFruit() [1/2]
override bool Edible_Base::IsFruit () inline private
Definition at line 13 of file caninaberry.c.
    {
        return true;
    }
Referenced by ActionEatFruit::ActionCondition(), and ItemBase::ProcessDecay().
IsFruit() [2/2]
override bool Edible_Base::IsFruit () inline private
Definition at line 13 of file sambucusberry.c.
    {
        return true;
    }
IsMeat() [1/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file bearsteakmeat.c.
    {
        return true;
    }
Referenced by ActionEatMeat::ApplyModifiers(), CAContinuousTimeCooking::Execute(), and ItemBase::ProcessDecay().
IsMeat() [2/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file bitterlings.c.
    {
        return true;
    }
IsMeat() [3/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file boarsteakmeat.c.
    {
        return true;
    }
IsMeat() [4/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file carpfilletmeat.c.
    {
        return true;
    }
IsMeat() [5/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file chickenbreastmeat.c.
    {
        return true;
    }
IsMeat() [6/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file cowsteakmeat.c.
    {
        return true;
    }
IsMeat() [7/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file deersteakmeat.c.
    {
        return true;
    }
IsMeat() [8/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file foxsteakmeat.c.
    {
        return true;
    }
IsMeat() [9/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file goatsteakmeat.c.
    {
        return true;
    }
IsMeat() [10/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 18 of file humansteakmeat.c.
    {
        return true;
    }
IsMeat() [11/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file lard.c.
    {
        return true;
    }
IsMeat() [12/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file mackerelfilletmeat.c.
    {
        return true;
    }
IsMeat() [13/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file mouflonsteakmeat.c.
    {
        return true;
    }
IsMeat() [14/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file pigsteakmeat.c.
    {
        return true;
    }
IsMeat() [15/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file rabbitlegmeat.c.
    {
        return true;
    }
IsMeat() [16/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file sardines.c.
    {
        return true;
    }
IsMeat() [17/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file sheepsteakmeat.c.
    {
        return true;
    }
IsMeat() [18/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file wolfsteakmeat.c.
    {
        return true;
    }
IsMeat() [19/19]
override bool Edible_Base::IsMeat () inline private
Definition at line 13 of file worm.c.
    {
        return true;
    }
OnConsume() [1/2]
override void Edible_Base::OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 13 of file charcoaltablets.c.
    {
        if( !consumer.GetModifiersManager().IsModifierActive(eModifiers.MDF_CHARCOAL ) )
        {
            consumer.GetModifiersManager().ActivateModifier( eModifiers.MDF_CHARCOAL );
        }
    }
Referenced by ItemBase::Consume().
OnConsume() [2/2]
override void Edible_Base::OnConsume (float amount, PlayerBase consumer) inline private
Definition at line 13 of file painkillertablets.c.
    {
        if( consumer.GetModifiersManager().IsModifierActive(eModifiers.MDF_PAINKILLERS ) )//effectively resets the timer
        {
            consumer.GetModifiersManager().DeactivateModifier( eModifiers.MDF_PAINKILLERS, false );
        }
        consumer.GetModifiersManager().ActivateModifier( eModifiers.MDF_PAINKILLERS );
    }
SetActions() [1/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file bearsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [2/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file bitterlings.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
    }
References AddAction().
SetActions() [3/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file boarsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [4/26]
override void Edible_Base::SetActions () inline private
Definition at line 7 of file boxcerealcrunchin.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEat);
    }
References AddAction().
SetActions() [5/26]
override void Edible_Base::SetActions () inline private
Definition at line 55 of file caninaberry.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEat);
    }
References AddAction().
SetActions() [6/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file carpfilletmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [7/26]
override void Edible_Base::SetActions () inline private
Definition at line 3 of file charcoaltablets.c.
    {
        super.SetActions();
        AddAction(ActionForceConsumeSingle);
        AddAction(ActionConsumeSingle);
        //AddAction(ActionForceFeed);
        //AddAction(ActionEatBig);
    }
References AddAction().
SetActions() [8/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file chickenbreastmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
    }
References AddAction().
SetActions() [9/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file cowsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [10/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file deersteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [11/26]
override void Edible_Base::SetActions () inline private
Definition at line 79 of file disinfectantspray.c.
    {
        super.SetActions();
        AddAction(ActionDisinfectTarget);
        AddAction(ActionDisinfectSelf);;
        AddAction(ActionDisinfectPlant);
        AddAction(ActionWashHandsItem);
        //AddAction(ActionForceDrinkDisinfectant);
        //AddAction(ActionDrinkDisinfectant);
    }
References ActionDisinfectSelf(), and AddAction().
SetActions() [12/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file foxsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [13/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file goatsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [14/26]
override void Edible_Base::SetActions () inline private
Definition at line 67 of file guts.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatBig);
    }
References AddAction().
SetActions() [15/26]
override void Edible_Base::SetActions () inline private
Definition at line 28 of file humansteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [16/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file lard.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [17/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file mackerelfilletmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [18/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file mouflonsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [19/26]
override void Edible_Base::SetActions () inline private
Definition at line 3 of file painkillertablets.c.
    {
        super.SetActions();
        AddAction(ActionForceConsumeSingle);
        AddAction(ActionConsumeSingle);
        //AddAction(ActionForceFeed);
        //AddAction(ActionEatBig);
    }
References AddAction().
SetActions() [20/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file pigsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [21/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file rabbitlegmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [22/26]
override void Edible_Base::SetActions () inline private
Definition at line 55 of file sambucusberry.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEat);
    }
References AddAction().
SetActions() [23/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file sardines.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
    }
References AddAction().
SetActions() [24/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file sheepsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().
SetActions() [25/26]
override void Edible_Base::SetActions () inline private
Definition at line 67 of file smallguts.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatBig);
    }
References AddAction().
SetActions() [26/26]
override void Edible_Base::SetActions () inline private
Definition at line 23 of file wolfsteakmeat.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatMeat);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().