DayzKode: RestCallback Class Reference
RestCallback Class Reference
Private Member Functions
void OnError (int errorCode)
Called in case request failed (ERestResultState) - Note! May be called multiple times in case of (RetryCount > 1)
void OnFileCreated (string fileName, int dataSize)
Called when data arrived and/ or file created successfully.
void OnSuccess (string data, int dataSize)
Called when data arrived and/ or response processed successfully.
void OnTimeout ()
Called in case request timed out or handled improperly (no error, no success, no data)
Detailed Description
Definition at line 50 of file restapi.c.
Member Function Documentation
OnError()
void RestCallback::OnError (int errorCode) inline private
Called in case request failed (ERestResultState) - Note! May be called multiple times in case of (RetryCount > 1)
Definition at line 55 of file restapi.c.
    {
        // override this with your implementation
        Print(" !!! OnError() ");
    };
References Print().
OnFileCreated()
void RestCallback::OnFileCreated (string fileName, int dataSize) inline private
Called when data arrived and/ or file created successfully.
Definition at line 84 of file restapi.c.
    {
        // override this with your implementation
        Print(" !!! OnFileCreated() file=" + fileName + " size=" + dataSize );
    };
References Print().
OnSuccess()
void RestCallback::OnSuccess (string data, int dataSize) inline private
Called when data arrived and/ or response processed successfully.
Definition at line 73 of file restapi.c.
    {
        // override this with your implementation
        Print(" !!! OnSuccess() size=" + dataSize );
        if( dataSize > 0 )
            Print(data); // !!! NOTE: Print() will not output string longer than 1024b, check your dataSize !!!
    };
References Print().
OnTimeout()
void RestCallback::OnTimeout () inline private
Called in case request timed out or handled improperly (no error, no success, no data)
Definition at line 64 of file restapi.c.
    {
        // override this with your implementation
        Print(" !!! OnTimeout() ");
    };
References Print().