DayzKode: PluginLocalProfile Class Reference
PluginLocalProfile Class Reference
Private Member Functions
override string GetFileName ()
override string GetFileName ()
string GetPathScenes ()
TStringArray GetSceneList ()
override void OnInit ()
void SceneSave (SceneData scene)
Private Attributes
private const string FILE_ROOT = "$saves:"
private const string FILE_ROOT_SCENES = "Scenes"
private string m_FileSceneName
private const string PARAM_FOG = "InitWeatherFog"
private const string PARAM_MISSION = "Mission"
private const string PARAM_OBJ_COUNT = "SceneObjectsCount"
private const string PARAM_OBJ_NAME = "SceneObject"
private const string PARAM_RAIN = "InitWeatherRain"
private const string PARAM_TIME = "InitTime"
Detailed Description
Definition at line 1 of file pluginadditionalinfo.c.
Member Function Documentation
GetFileName() [1/2]
override string PluginLocalProfile::GetFileName () inline private
Definition at line 3 of file pluginadditionalinfo.c.
    {
        return CFG_FILE_ADDITIONAL_INFO;
    }
References CFG_FILE_ADDITIONAL_INFO.
Referenced by PluginFileHandler::LoadConfigFile().
GetFileName() [2/2]
override string PluginLocalProfile::GetFileName () inline private
Definition at line 42 of file pluginlocalprofilescene.c.
    {
        string file_name = GetPathScenes()+"\\"+m_FileSceneName;
        return file_name;
    }
References GetPathScenes(), and m_FileSceneName.
GetPathScenes()
string PluginLocalProfile::GetPathScenes () inline private
Definition at line 34 of file pluginlocalprofilescene.c.
    {
        return FILE_ROOT+"\\"+FILE_ROOT_SCENES;
    }
References FILE_ROOT_SCENES.
Referenced by GetFileName(), and GetSceneList().
GetSceneList()
TStringArray PluginLocalProfile::GetSceneList () inline private
Definition at line 59 of file pluginlocalprofilescene.c.
    {
        if ( !FileExist( GetPathScenes() ) )
        {
            MakeDirectory( GetPathScenes() );
        }
        string  file_name;
        int     file_attr;
        int     flags;
        TStringArray list = new TStringArray;
        string path_find_pattern = GetPathScenes()+"/*.scene";
        FindFileHandle file_handler = FindFile(path_find_pattern, file_name, file_attr, flags);
        bool found = true;
        while ( found )
        {
            list.Insert(file_name);
            found = FindNextFile(file_handler, file_name, file_attr);
        }
        return list;
    }
References FileExist(), FindFile(), FindNextFile(), GetPathScenes(), and MakeDirectory().
OnInit()
override void PluginLocalProfile::OnInit () inline private
Definition at line 51 of file pluginlocalprofilescene.c.
    {
        super.OnInit();
    }
SceneSave()
void PluginLocalProfile::SceneSave (SceneData scene) inline private
Definition at line 88 of file pluginlocalprofilescene.c.
    {
        m_FileSceneName = scene.GetNameScene()+".scene";
        array<ref SceneObject> objects = scene.GetSceneObjects();
        // Save Mission Name
        SetParameterString(PARAM_MISSION, scene.GetNameMission(), false);
        //Save Init Time
        SetParameterFloat(PARAM_TIME, scene.GetInitTime(), false);
        //Save Init Weather Rain
        SetParameterFloat(PARAM_RAIN, scene.GetInitRain(), false);
        //Save Init Weather Rain
        SetParameterFloat(PARAM_FOG, scene.GetInitFog(), false);
        // Save Count Of missions
        SetParameterInt(PARAM_OBJ_COUNT, objects.Count(), false);
        for ( int i = 0; i < objects.Count(); ++i )
        {
            SceneObject obj = objects.Get(i);
            string param_name = PARAM_OBJ_NAME+"_"+i.ToString();
            Print(param_name);
            SetSubParameterInArray (param_name, 0, "ClassName", obj.GetTypeName(), false);
        }
        SaveConfigToFile();
    }
References SceneData::GetInitFog(), SceneData::GetInitRain(), SceneData::GetInitTime(), SceneData::GetNameMission(), SceneData::GetNameScene(), SceneData::GetSceneObjects(), SceneObject::GetTypeName(), Print(), and string::ToString().
Member Data Documentation
FILE_ROOT
private const string PluginLocalProfile::FILE_ROOT = "$saves:" private
Definition at line 20 of file pluginlocalprofilescene.c.
FILE_ROOT_SCENES
private const string PluginLocalProfile::FILE_ROOT_SCENES = "Scenes" private
Definition at line 21 of file pluginlocalprofilescene.c.
Referenced by GetPathScenes().
m_FileSceneName
private string PluginLocalProfile::m_FileSceneName private
Definition at line 29 of file pluginlocalprofilescene.c.
Referenced by GetFileName().
PARAM_FOG
private const string PluginLocalProfile::PARAM_FOG = "InitWeatherFog" private
Definition at line 25 of file pluginlocalprofilescene.c.
PARAM_MISSION
private const string PluginLocalProfile::PARAM_MISSION = "Mission" private
Definition at line 22 of file pluginlocalprofilescene.c.
PARAM_OBJ_COUNT
private const string PluginLocalProfile::PARAM_OBJ_COUNT = "SceneObjectsCount" private
Definition at line 26 of file pluginlocalprofilescene.c.
PARAM_OBJ_NAME
private const string PluginLocalProfile::PARAM_OBJ_NAME = "SceneObject" private
Definition at line 27 of file pluginlocalprofilescene.c.
PARAM_RAIN
private const string PluginLocalProfile::PARAM_RAIN = "InitWeatherRain" private
Definition at line 24 of file pluginlocalprofilescene.c.
PARAM_TIME
private const string PluginLocalProfile::PARAM_TIME = "InitTime" private
Definition at line 23 of file pluginlocalprofilescene.c.