DayzKode: EnumTools Class Reference
EnumTools Class Reference
Private Member Functions
private void EnumTools ()
private void ~EnumTools ()
Static Private Member Functions
static string EnumToString (typename e, int enumValue)
Return string name of enum value.
static int GetEnumSize (typename e)
Return amount of values in enum.
static int GetEnumValue (typename e, int idx)
Return the nth value in the enum.
static int GetLastEnumValue (typename e)
Return amount of values in enum.
static int StringToEnum (typename e, string enumName)
Return enum value from string name.
Detailed Description
Definition at line 585 of file enconvert.c.
Constructor & Destructor Documentation
EnumTools()
private void EnumTools::EnumTools () private
~EnumTools()
private void EnumTools::~EnumTools () private
Member Function Documentation
EnumToString()
static string EnumTools::EnumToString (typename e , int enumValue) inline static private
Return string name of enum value.
DialogPriority prio = DialogPriority.WARNING;
Print(EnumTools.EnumToString(DialogPriority, prio));
Definition at line 597 of file enconvert.c.
    {
        return typename.EnumToString(e, enumValue);
    }
GetEnumSize()
static int EnumTools::GetEnumSize (typename e) inline static private
Return amount of values in enum.
Print(EnumTools.GetEnumSize(DialogPriority));
Definition at line 619 of file enconvert.c.
    {
        return e.GetVariableCount();
    }
Referenced by UIScriptedMenu::DrawConnectingLines(), ContentDLC::OwnsAllDLC(), Hud::RefreshVehicleHud(), RemoteDetonatorTrigger::RemoteDetonatorTrigger(), and EnProfilerTests::TestSetFlags().
GetEnumValue()
static int EnumTools::GetEnumValue (typename e , int idx) inline static private
Return the nth value in the enum.
Print(EnumTools.GetEnumValue(DialogPriority, 1));
Definition at line 630 of file enconvert.c.
    {
        int value;
        e.GetVariableValue(null, idx, value);
        return value;
    }
Referenced by ContentDLC::OwnsAllDLC(), and EnProfilerTests::TestSetFlags().
GetLastEnumValue()
static int EnumTools::GetLastEnumValue (typename e) inline static private
Return amount of values in enum.
Print(EnumTools.GetLastEnumValue(DialogPriority));
Definition at line 643 of file enconvert.c.
    {
        int lastValue;
        e.GetVariableValue(null, e.GetVariableCount() - 1, lastValue);
        return lastValue;
    }
Referenced by FireworksLauncher::FireworksLauncher(), and Land_Underground_EntranceBase::Land_Underground_EntranceBase().
StringToEnum()
static int EnumTools::StringToEnum (typename e , string enumName) inline static private
Return enum value from string name.
Print(EnumTools.StringToEnum(DialogPriority, "WARNING"));
Definition at line 608 of file enconvert.c.
    {
        return typename.StringToEnum(e, enumName);
    }
Referenced by EnProfilerTests::TestModule().