DayzKode: PlayerContainer Class Reference
PlayerContainer Class Reference
Private Member Functions
void AddSlotsContainer (int row_count)
override bool CanCombine ()
override void CollapseButtonOnMouseButtonDown (Widget w)
override bool Combine ()
void DoubleClick (Widget w, int x, int y, int button)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override bool EquipItem ()
override void ExpandCollapseContainer ()
override EntityAI GetFocusedItem ()
ItemPreviewWidget GetItemPreviewWidget (Widget w)
float GetMainContainerBottomPos ()
float GetMainContainerTopPos ()
int GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2)
SlotsIcon GetSlotsIcon (int row, int column)
bool HasEntityContainerVisible (EntityAI entity)
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
override bool InspectItem ()
bool IsContainerWithCargoActive ()
bool IsEmptyItemActive ()
override bool IsItemActive ()
bool IsItemWithAttachmentsActive ()
bool IsItemWithContainerActive ()
override bool IsItemWithQuantityActive ()
bool IsPlayerEquipmentActive ()
void ItemAttached (EntityAI item, string slot_name)
void ItemDetached (EntityAI item, string slot_name)
void MouseClick (Widget w, int x, int y, int button)
void OnAttachmentReservationRelease (EntityAI item, int slot_id)
void OnAttachmentReservationSet (EntityAI item, int slot_id)
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void PlayerContainer (LayoutHolder parent, int sort=-1)
override void Refresh ()
override bool Select ()
void SetPlayer (PlayerBase player)
override bool SplitItem ()
void SwapItemsInOrder (int slot1, int slot2)
void ToggleContainer (Widget w, EntityAI item)
void ToggleWidget (Widget w)
override bool TransferItem ()
override bool TransferItemToVicinity ()
void UnfocusPlayerAttachmentsContainer ()
override void UpdateInterval ()
override void UpdateRadialIcon ()
void ~PlayerContainer ()
Private Attributes
protected const int HEADER_INDEX_OFFSET = 2
protected ref map< int, SlotsIcon > m_InventorySlots
protected PlayerBase m_Player
protected ref AttachmentsGroupContainer m_PlayerAttachmentsContainer
protected ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
protected ref map< int, ref Container > m_ShowedItemsIDs = new ref map<int, ref Container>
Detailed Description
Definition at line 1 of file playercontainer.c.
Constructor & Destructor Documentation
PlayerContainer()
void PlayerContainer::PlayerContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 34 of file playercontainer.c.
    {
        m_InventorySlots = new ref map<int, SlotsIcon>;
        m_PlayerAttachmentsContainer = new AttachmentsGroupContainer(this);
        m_PlayerAttachmentsContainer.SetHeader(GetHeader());
        m_CollapsibleHeader.SetName( "#container_inventory" );
        SetHeader(null);
        m_Body.Insert( m_PlayerAttachmentsContainer );
        m_MainWidget = m_RootWidget.FindAnyWidget( "body" );
        m_PlayerAttachmentsContainer.GetRootWidget().SetColor(166 << 24 | 80 << 16 | 80 << 8 | 80);
        WidgetEventHandler.GetInstance().RegisterOnChildAdd( m_MainWidget, this, "OnChildAdd" );
        WidgetEventHandler.GetInstance().RegisterOnChildRemove( m_MainWidget, this, "OnChildRemove" );
        //START - InitGhostSlots
        string config_path_ghosts_slots = "CfgVehicles SurvivorBase InventoryEquipment playerSlots";
        ref array<string> player_ghosts_slots = new array<string>;
        GetGame().ConfigGetTextArray( config_path_ghosts_slots, player_ghosts_slots );
        for ( int i = 0; i < player_ghosts_slots.Count(); i++ )
        {
            string slot_name = player_ghosts_slots.Get ( i );
            string path = "CfgSlots" + " " + slot_name;
            if ( GetGame().ConfigIsExisting( path ) )
            {
                string icon_name; //icon_name must be in format "set:<setname> image:<imagename>"
                GetGame().ConfigGetText( path + " ghostIcon", icon_name );
                int slot_number = i;
                int column = slot_number % ITEMS_IN_ROW;
                //START - GetWidgetSlot
                int row = slot_number / ITEMS_IN_ROW;
                if( row >= m_PlayerAttachmentsContainer.Count() )
                {
                    if( row < ( player_ghosts_slots.Count() / ITEMS_IN_ROW ) )
                        AddSlotsContainer( ITEMS_IN_ROW );
                    else
                        AddSlotsContainer( player_ghosts_slots.Count() % ITEMS_IN_ROW );
                }
                SlotsIcon icon = GetSlotsIcon( row, column );
                icon.GetMainWidget().Show( true );
                icon.Clear();
                WidgetEventHandler.GetInstance().RegisterOnDoubleClick( icon.GetPanelWidget(),  this, "DoubleClick" );
                //END - GetWidgetSlot
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetPanelWidget(),  this, "OnDropReceivedFromGhostArea" );
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetGhostSlot(),  this, "OnDropReceivedFromGhostArea" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetGhostSlot(),  this, "DraggingOver" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetPanelWidget(),  this, "DraggingOver" );
                WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( icon.GetPanelWidget(),  this, "MouseClick" );
                icon.GetGhostSlot().LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,icon_name) );
                //END - LoadIconIntoWidgetSlot
                GetGame().ConfigGetText( path + " name", slot_name );
                int slot_id = InventorySlots.GetSlotIdFromString( slot_name );
                icon.SetSlotID(slot_id);
                icon.SetSlotDisplayName(InventorySlots.GetSlotDisplayName(slot_id));
                m_InventorySlots.Set( slot_id, icon );
            }
        }
        m_PlayerAttachmentsContainer.GetMainWidget().Update();
        //END - InitGhostSlots
        RecomputeOpenedContainers();
    }
References AddSlotsContainer(), SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), SlotsIcon::GetGhostSlot(), CollapsibleContainer::GetHeader(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ITEMS_IN_ROW, CollapsibleContainer::m_CollapsibleHeader, m_InventorySlots, m_PlayerAttachmentsContainer, m_RootWidget, path, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), AttachmentsGroupContainer::SetHeader(), CollapsibleContainer::SetHeader(), Header::SetName(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), and StaticGUIUtils::VerifyIconImageString().
~PlayerContainer()
void PlayerContainer::~PlayerContainer () inline private
Definition at line 104 of file playercontainer.c.
    {
        if( m_Player )
        {
            m_Player.GetOnItemAttached().Remove(ItemAttached);
            m_Player.GetOnItemDetached().Remove(ItemDetached);
            m_Player.GetOnAttachmentSetLock().Remove(OnAttachmentReservationSet);
            m_Player.GetOnAttachmentReleaseLock().Remove(OnAttachmentReservationRelease);
        }
    }
References ItemAttached(), ItemDetached(), m_Player, OnAttachmentReservationRelease(), and OnAttachmentReservationSet().
Member Function Documentation
AddSlotsContainer()
void PlayerContainer::AddSlotsContainer (int row_count) inline private
Definition at line 221 of file playercontainer.c.
    {
        ref SlotsContainer s_cont = new SlotsContainer( m_PlayerAttachmentsContainer, m_Player );
        s_cont.SetColumnCount( row_count );
        m_PlayerAttachmentsContainer.Insert( s_cont );
    }
References m_Player, and m_PlayerAttachmentsContainer.
Referenced by PlayerContainer().
CanCombine()
override bool PlayerContainer::CanCombine () inline private
Definition at line 507 of file playercontainer.c.
    {
        ItemBase ent =  ItemBase.Cast( GetFocusedItem() );
        ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
        return ( ItemManager.GetCombinationFlags( item_in_hands, ent ) != 0 );
    }
References ItemManager::GetCombinationFlags(), GetFocusedItem(), GetGame(), and GetPlayer().
Referenced by UpdateConsoleToolbar().
CollapseButtonOnMouseButtonDown()
override void PlayerContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 1082 of file playercontainer.c.
    {
        super.CollapseButtonOnMouseButtonDown(w);
    }
Combine()
override bool PlayerContainer::Combine () inline private
Definition at line 583 of file playercontainer.c.
    {
        if( GetFocusedContainer() && ( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) ) )
        {
            return GetFocusedContainer().Combine();
        }
        else
        {
            EntityAI item = GetFocusedItem();
            ItemBase item_in_hands = ItemBase.Cast( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands() );
            Icon hands_icon = ItemManager.GetInstance().GetHandsPreview().GetIcon();
            if( item_in_hands && item )
            {
                return hands_icon.CombineItems( item_in_hands, item );
            }
        }
        return true;
    }
References Icon::CombineItems(), GetFocusedItem(), GetGame(), ItemManager::GetHandsPreview(), HandsPreview::GetIcon(), ItemManager::GetInstance(), and GetPlayer().
Referenced by RightArea::Combine().
DoubleClick()
void PlayerContainer::DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 370 of file playercontainer.c.
    {
        if( button == MouseState.LEFT )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if( w == null || m_Player.GetInventory().IsInventoryLocked() )
            {
                return;
            }
            ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
            if( !iw )
            {
              string name = w.GetName();
              name.Replace( "PanelWidget", "Render" );
              iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
            }
            if( !iw )
            {
              iw = ItemPreviewWidget.Cast( w );
            }
            ItemBase item = ItemBase.Cast( iw.GetItem() );
            if( !item )
            {
                return;
            }
            SlotsIcon icon;
            iw.GetUserData(icon);
            if(icon && icon.IsReserved())
            {
                return;
            }
            if( !item.GetInventory().CanRemoveEntity() )
                return;
            if ( player.GetInventory().HasEntityInInventory( item ) && player.GetHumanInventory().CanAddEntityInHands( item ) )
            {
                player.PredictiveTakeEntityToHands( item );
            }
            else
            {
                if (player.GetInventory().CanAddEntityToInventory( item ) && item.GetInventory().CanRemoveEntity())
                {
                    if( item.GetTargetQuantityMax() < item.GetQuantity() )
                        item.SplitIntoStackMaxClient( player, -1 );
                    else
                        player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ANY, item );
                }
                else
                {
                    if( item.GetTargetQuantityMax() < item.GetQuantity() )
                        item.SplitIntoStackMaxHandsClient( player );
                    else
                        player.PredictiveTakeEntityToHands( item );
                }
            }
            ToggleWidget( w );
            HideOwnedTooltip();
            InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
            if ( menu )
            {
                menu.RefreshQuickbar();
            }
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryMenu(), SlotsIcon::IsReserved(), m_Player, MENU_INVENTORY, name, string::Replace(), and ToggleWidget().
DraggingOver()
override void PlayerContainer::DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 801 of file playercontainer.c.
    {
        if( w == null )
        {
            return;
        }
        EntityAI receiver_item;
        bool is_reserved = false;
        SlotsIcon slots_icon;
        receiver.GetUserData(slots_icon);
        if(slots_icon)
        {
            receiver_item = slots_icon.GetEntity();
            is_reserved = slots_icon.IsReserved();
        }
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( GetItemPreviewWidget( w ) );
        if( !ipw || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        if( !item )
        {
            return;
        }
        if( receiver_item && !is_reserved )
        {
            if( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                return;
            }
            else if( receiver_item.GetInventory().CanAddAttachment(item) || receiver_item.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && !receiver_item.GetInventory().HasEntityInCargo( item ))
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                return;
            }
            else if( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( item ) ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                return;
            }
        }
        if( item.GetInventory().CanRemoveEntity() )
        {
            if( m_Player.GetInventory().CanAddAttachment( item) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else if( m_Player.GetInventory().CanAddEntityToInventory( item, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT ) && ( !m_Player.GetInventory().HasEntityInInventory( item ) ) || m_Player.GetHumanInventory().HasEntityInHands( item ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else if ( receiver_item && GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
        }
        else
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            //ItemManager.GetInstance().ShowSourceDropzone( item );
        }
    }
References ColorManager::COMBINE_COLOR, SlotsIcon::GetEntity(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Player, ColorManager::RED_COLOR, ColorManager::SetColor(), and ColorManager::SWAP_COLOR.
DraggingOverHeader()
override void PlayerContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 767 of file playercontainer.c.
    {
        if( w == null )
        {
            return;
        }
        ItemPreviewWidget ipw = GetItemPreviewWidget( w );
        if( !ipw || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        if( !item )
        {
            return;
        }
        if( m_Player.GetInventory().CanAddEntityToInventory( item, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT ) && !m_Player.GetInventory().HasEntityInInventory( item ) )
        {
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
        }
        else
        {
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            //ItemManager.GetInstance().ShowSourceDropzone( item );
        }
    }
References ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Player, ColorManager::RED_COLOR, and ColorManager::SetColor().
Referenced by RightArea::DraggingOverHeader().
EquipItem()
override bool PlayerContainer::EquipItem () inline private
Definition at line 525 of file playercontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().EquipItem();
        }
        else
        {
            EntityAI item = GetFocusedItem();
            if( item )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, item );
                return true;
            }
        }
        return false;
    }
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by RightArea::EquipItem().
ExpandCollapseContainer()
override void PlayerContainer::ExpandCollapseContainer () inline private
Definition at line 442 of file playercontainer.c.
    {
        if( m_PlayerAttachmentsContainer.IsActive() )
        {
            ToggleWidget(m_PlayerAttachmentsContainer.GetFocusedSlotsIcon().GetPanelWidget());
        }
    }
References m_PlayerAttachmentsContainer, and ToggleWidget().
Referenced by RightArea::ExpandCollapseContainer().
GetFocusedItem()
override EntityAI PlayerContainer::GetFocusedItem () inline private
Definition at line 578 of file playercontainer.c.
    {
        return GetFocusedContainer().GetFocusedItem();
    }
Referenced by CanCombine(), Combine(), EquipItem(), InspectItem(), IsEmptyItemActive(), IsItemActive(), IsItemWithContainerActive(), IsItemWithQuantityActive(), TransferItem(), and TransferItemToVicinity().
GetItemPreviewWidget()
ItemPreviewWidget PlayerContainer::GetItemPreviewWidget (Widget w) inline private
Definition at line 750 of file playercontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget("Render") );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
          ipw = ItemPreviewWidget.Cast( w );
        }
        return ipw;
    }
References name, and string::Replace().
Referenced by DraggingOver(), DraggingOverHeader(), OnDropReceivedFromGhostArea(), and OnDropReceivedFromHeader().
GetMainContainerBottomPos()
float PlayerContainer::GetMainContainerBottomPos () inline private
Definition at line 300 of file playercontainer.c.
    {
        float x, y;
        float x2, y2;
        GetRootWidget().GetScreenPos( x, y );
        GetRootWidget().GetScreenSize( x2, y2 );
        y += y2;
        return y;
    }
References x, and y.
GetMainContainerTopPos()
float PlayerContainer::GetMainContainerTopPos () inline private
Definition at line 293 of file playercontainer.c.
    {
        float x, y;
        GetRootWidget().GetScreenPos( x, y );
        return y;
    }
References x, and y.
GetRecipeCount()
int PlayerContainer::GetRecipeCount (bool recipe_anywhere, EntityAI entity1, EntityAI entity2) inline private
Definition at line 501 of file playercontainer.c.
    {
        PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast( GetPlugin( PluginRecipesManager ) );
        return plugin_recipes_manager.GetValidRecipes( ItemBase.Cast( entity1 ), ItemBase.Cast( entity2 ), null, PlayerBase.Cast( GetGame().GetPlayer() ) );
    }
References GetGame(), GetPlayer(), and GetPlugin().
GetSlotsIcon()
SlotsIcon PlayerContainer::GetSlotsIcon (int row, int column) inline private
Definition at line 29 of file playercontainer.c.
    {
        return m_PlayerAttachmentsContainer.GetSlotsIcon(row, column);
    }
References AttachmentsGroupContainer::GetSlotsIcon(), and m_PlayerAttachmentsContainer.
Referenced by PlayerContainer(), and SetPlayer().
HasEntityContainerVisible()
bool PlayerContainer::HasEntityContainerVisible (EntityAI entity) inline private
Definition at line 23 of file playercontainer.c.
    {
        ClosableContainer cont = ClosableContainer.Cast( m_ShowedItems.Get( entity ) );
        return ( cont && cont.IsOpened() );
    }
References ClosableContainer::IsOpened(), and m_ShowedItems.
Referenced by RightArea::HasEntityContainerVisible().
Insert()
override void PlayerContainer::Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 310 of file playercontainer.c.
    {
        ClosableContainer c_cont = ClosableContainer.Cast( container );
        if (c_cont && m_Body.Count() > 1)
        {
            ClosableContainer prev  = ClosableContainer.Cast(m_Body.Get( 1 ));
            int index               = 1;
            int curr_sort           = c_cont.GetRootWidget().GetSort();
            while ( prev )
            {
                int prev_sort = prev.GetRootWidget().GetSort();
                if ( prev_sort > curr_sort )
                    break;
                if ( ++index < m_Body.Count() )
                    prev = ClosableContainer.Cast( m_Body.Get( index ) );
                else
                    break;
            }
            m_Body.InsertAt( container, index );
        }
        else
        {
            m_Body.Insert( container );
        }
        if ( immedUpdate )
            RecomputeOpenedContainers();
    }
InspectItem()
override bool PlayerContainer::InspectItem () inline private
Definition at line 482 of file playercontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().InspectItem();
        }
        else
        {
            Man player = GetGame().GetPlayer();
            EntityAI item = GetFocusedItem();
            if( item )
            {
                InspectItem( item );
                return true;
            }
        }
        return false;
    }
References GetFocusedItem(), GetGame(), CGame::GetPlayer(), and InspectItem().
Referenced by RightArea::InspectItem(), InspectItem(), and MouseClick().
IsContainerWithCargoActive()
bool PlayerContainer::IsContainerWithCargoActive () inline private
Definition at line 450 of file playercontainer.c.
    {
        return GetFocusedContainer().IsInherited( ContainerWithCargo );
    }
Referenced by UpdateConsoleToolbar().
IsEmptyItemActive()
bool PlayerContainer::IsEmptyItemActive () inline private
Definition at line 359 of file playercontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent == null;
    }
References GetFocusedItem().
Referenced by UpdateConsoleToolbar().
IsItemActive()
override bool PlayerContainer::IsItemActive () inline private
Definition at line 353 of file playercontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent && !IsItemWithQuantityActive() && !IsItemWithContainerActive();
    }
References GetFocusedItem(), IsItemWithContainerActive(), and IsItemWithQuantityActive().
Referenced by UpdateConsoleToolbar().
IsItemWithAttachmentsActive()
bool PlayerContainer::IsItemWithAttachmentsActive () inline private
Definition at line 455 of file playercontainer.c.
    {
        return GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments );
    }
Referenced by UpdateConsoleToolbar().
IsItemWithContainerActive()
bool PlayerContainer::IsItemWithContainerActive () inline private
Definition at line 341 of file playercontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent && ( ent.GetInventory().GetCargo() || ent.GetSlotsCountCorrect() > 0 );
    }
References GetFocusedItem().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool PlayerContainer::IsItemWithQuantityActive () inline private
Definition at line 347 of file playercontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent && QuantityConversions.HasItemQuantity( ent ) && ent.CanBeSplit();
    }
References GetFocusedItem(), and QuantityConversions::HasItemQuantity().
Referenced by IsItemActive(), and UpdateConsoleToolbar().
IsPlayerEquipmentActive()
bool PlayerContainer::IsPlayerEquipmentActive () inline private
Definition at line 1087 of file playercontainer.c.
    {
        if( GetFocusedContainer() && ( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) ) )
        {
            return false;
        }
        return true;
    }
Referenced by RightArea::IsPlayerEquipmentActive(), and UpdateConsoleToolbar().
ItemAttached()
void PlayerContainer::ItemAttached (EntityAI item, string slot_name) inline private
Definition at line 115 of file playercontainer.c.
    {
        int slot = InventorySlots.GetSlotIdFromString( slot_name );
        SlotsIcon icon = m_InventorySlots.Get( slot );
        if( icon )
        {
            if( icon.IsReserved())
                m_Player.GetOnAttachmentReleaseLock().Invoke(item, slot);
            icon.Init( item );
            if( m_ShowedItems.Contains( item ) == false )
            {
                string name;
                int sort_index = Inventory.GetPlayerAttachmentIndex( slot );
                int current_sort = 9999;
                if( GetFocusedContainer() )
                    current_sort = GetFocusedContainer().GetRootWidget().GetSort();
                if( item.GetSlotsCountCorrect() > 0 )
                {
                    ContainerWithCargoAndAttachments iwca = new ContainerWithCargoAndAttachments( this, sort_index );
                    iwca.SetEntity( item );
                    iwca.SetSlotIcon( icon );
                    WidgetEventHandler.GetInstance().RegisterOnMouseButtonUp( icon.GetPanelWidget(),  this, "ToggleWidget" );
                    if( iwca.IsDisplayable() )
                    {
                        icon.GetRadialIconPanel().Show( true );
                    }
                    m_ShowedItems.Insert( item, iwca );
                    RecomputeOpenedContainers();
                    Refresh();
                }
                else if( item.GetInventory().GetCargo() )
                {
                    ContainerWithCargo iwc = new ContainerWithCargo( this, sort_index );
                    iwc.SetEntity( item );
                    iwc.SetSlotIcon( icon );
                    iwc.UpdateInterval();
                    WidgetEventHandler.GetInstance().RegisterOnMouseButtonUp( icon.GetPanelWidget(),  this, "ToggleWidget" );
                    m_ShowedItems.Insert( item, iwc );
                    RecomputeOpenedContainers();
                    if( iwc.IsDisplayable() )
                        icon.GetRadialIconPanel().Show(true);
                    Refresh();
                }
            }
            ClosableContainer conta = ClosableContainer.Cast( m_ShowedItems.Get( item ) );
            string config = "CfgVehicles " + item.GetType() + " GUIInventoryAttachmentsProps";
            if( conta && conta.IsInherited( ClosableContainer ) )
            {
                bool show_radial_icon = ( item.GetInventory().GetCargo() || item.GetSlotsCountCorrect() > 0 ) && !GetGame().ConfigIsExisting( config );
                Widget rip = icon.GetRadialIconPanel();
                rip.Show( show_radial_icon );
                SetOpenForSlotIcon(conta.IsOpened(),icon);
            }
        }
        UpdateSelectionIcons();
    }
References CGame::ConfigIsExisting(), GetGame(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), Inventory(), ClosableContainer::IsOpened(), SlotsIcon::IsReserved(), m_InventorySlots, m_Player, m_ShowedItems, name, Refresh(), and WidgetEventHandler::RegisterOnMouseButtonUp().
Referenced by SetPlayer(), and ~PlayerContainer().
ItemDetached()
void PlayerContainer::ItemDetached (EntityAI item, string slot_name) inline private
Definition at line 180 of file playercontainer.c.
    {
        int slot = InventorySlots.GetSlotIdFromString( slot_name );
        SlotsIcon icon = m_InventorySlots.Get( slot );
        if( icon )
        {
            Container con = m_ShowedItems.Get( item );
            if( con )
            {
                ( Container.Cast( con.m_Parent ) ).Remove( con );
                RecomputeOpenedContainers();
                GetMainWidget().Update();
                Refresh();
                m_ShowedItems.Remove( item );
            }
            icon.Clear();
            Inventory in = Inventory.Cast( GetRoot() );
            if( in )
                in.UpdateConsoleToolbar();
        }
        UpdateSelectionIcons();
    }
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), Inventory(), m_InventorySlots, m_ShowedItems, Refresh(), and CollapsibleContainer::Remove().
Referenced by SetPlayer(), and ~PlayerContainer().
MouseClick()
void PlayerContainer::MouseClick (Widget w, int x, int y, int button) inline private
Definition at line 228 of file playercontainer.c.
    {
        SlotsIcon slots_icon;
        w.GetUserData(slots_icon);
        EntityAI item;
        bool reserved;
        if(slots_icon)
        {
            item = slots_icon.GetEntity();
            reserved = slots_icon.IsReserved();
        }
        ItemBase itemAtPos = ItemBase.Cast( item );
        if( item )
        {
            if ( button == MouseState.RIGHT )
            {
                #ifdef DEVELOPER
                if( GetDayZGame().IsLeftCtrlDown() )
                    ShowActionMenu( InventoryItem.Cast(item) );
                #endif
                if( reserved )
                {
                    GetGame().GetPlayer().GetHumanInventory().ClearUserReservedLocation( item );
                    m_Player.GetOnAttachmentReleaseLock().Invoke(item, slots_icon.GetSlotID());
                }
            }
            else if ( button == MouseState.MIDDLE )
            {
                if( !reserved )
                {
                    InspectItem( itemAtPos );
                }
            }
            else if ( button == MouseState.LEFT )
            {
                if( !reserved )
                {
                    if ( g_Game.IsLeftCtrlDown() )
                    {
                        if( itemAtPos && itemAtPos.GetInventory().CanRemoveEntity() && m_Player.CanDropEntity(itemAtPos) )
{
                            if( itemAtPos.GetTargetQuantityMax() < itemAtPos.GetQuantity() )
                                itemAtPos.SplitIntoStackMaxClient( null, -1 );
                            else
                                m_Player.PhysicalPredictiveDropItem( itemAtPos );
                        }
                    }
                    else
                    {
                        bool draggable = !m_Player.GetInventory().HasInventoryReservation( item, null ) && !m_Player.GetInventory().IsInventoryLocked() && item.GetInventory().CanRemoveEntity() && !m_Player.IsItemsToDelete();
                        ItemManager.GetInstance().SetWidgetDraggable( w, draggable );
                    }
                }
            }
        }
    }
References g_Game, GetDayZGame(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), SlotsIcon::GetSlotID(), InspectItem(), IsLeftCtrlDown(), SlotsIcon::IsReserved(), m_Player, and ItemManager::SetWidgetDraggable().
OnAttachmentReservationRelease()
void PlayerContainer::OnAttachmentReservationRelease (EntityAI item, int slot_id) inline private
Definition at line 215 of file playercontainer.c.
    {
        SlotsIcon icon = m_InventorySlots.Get( slot_id );
        icon.Clear();
    }
References SlotsIcon::Clear(), and m_InventorySlots.
Referenced by SetPlayer(), and ~PlayerContainer().
OnAttachmentReservationSet()
void PlayerContainer::OnAttachmentReservationSet (EntityAI item, int slot_id) inline private
Definition at line 205 of file playercontainer.c.
    {
        SlotsIcon icon = m_InventorySlots.Get( slot_id );
        if( item )
        {
            icon.Init( item, true );
        }
    }
References SlotsIcon::Init(), and m_InventorySlots.
Referenced by SetPlayer(), and ~PlayerContainer().
OnChildAdd()
override bool PlayerContainer::OnChildAdd (Widget w, Widget child) inline private
Definition at line 1111 of file playercontainer.c.
    {
        Refresh();
        return true;
    }
References Refresh().
OnChildRemove()
override bool PlayerContainer::OnChildRemove (Widget w, Widget child) inline private
Definition at line 1105 of file playercontainer.c.
    {
        Refresh();
        return true;
    }
References Refresh().
OnDropReceivedFromGhostArea()
void PlayerContainer::OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver) inline private
Definition at line 895 of file playercontainer.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        EntityAI receiver_item;
        bool is_reserved = false;
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
        float stack_max;
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( GetItemPreviewWidget( w ) );
        SlotsIcon slots_icon;
        receiver.GetUserData(slots_icon);
        int slot_id = slots_icon.GetSlotID();
        receiver_item = slots_icon.GetEntity();
        is_reserved = slots_icon.IsReserved();
        InventoryLocation il;
        if ( !ipw )
        {
            return;
        }
        ItemBase item = ItemBase.Cast(ipw.GetItem());
        PlayerBase real_player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( !item )
        {
            return;
        }
        if ( receiver_item && !is_reserved )
        {
            if ( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
            {
                GetGame().GetPlayer().PredictiveSwapEntities( item, receiver_item );
                if ( menu )
                {
                    menu.RefreshQuickbar();
                }
                return;
            }
            else if ( receiver_item.GetInventory().CanAddAttachment( item ) )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToTargetAttachment( receiver_item, item );
                if ( menu )
                {
                    menu.RefreshQuickbar();
                }
                return;
            }
            else if ( receiver_item.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && !receiver_item.GetInventory().HasEntityInCargo( item ) )
            {
                SplitItemUtils.TakeOrSplitToInventory(real_player, receiver_item,item);
                if ( menu )
                {
                    menu.RefreshQuickbar();
                }
                return;
            }
            else if ( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( item ) ) )
            {
                ( ItemBase.Cast( receiver_item ) ).CombineItemsClient( ItemBase.Cast( item ) );
                return;
            }
        }
        if ( m_Player.GetInventory().CanAddAttachmentEx( item, slot_id ) )
        {
            if (item.GetQuantity() > item.GetTargetQuantityMax(slot_id))
            {
                item.SplitIntoStackMaxClient( real_player, slot_id );
            }
            else
            {
                real_player.PredictiveTakeEntityToTargetAttachmentEx( m_Player, item, slots_icon.GetSlotID() );
            }
        }
        else if (  m_Player.GetInventory().CanAddAttachment( item ) )
        {
            il = new InventoryLocation;
            m_Player.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ATTACHMENT, il );
            float stackable = item.GetTargetQuantityMax(-1);
            if( il.IsValid() )
            {
                if ( stackable == 0 || stackable >= item.GetQuantity() )
                {
                    real_player.PredictiveTakeEntityToTargetAttachment( il.GetParent(), item );
                }
                else
                {
                    ItemBase.Cast(item).SplitIntoStackMaxToInventoryLocationClient( il );
                }
            }
        }
        else if(  m_Player.GetInventory().CanAddEntityToInventory( item, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT ) && ( !m_Player.GetInventory().HasEntityInInventory( item ) ) || m_Player.GetHumanInventory().HasEntityInHands( item ) )
        {
            SplitItemUtils.TakeOrSplitToInventory(m_Player, m_Player, item);
        }
        if ( menu )
        {
            menu.RefreshQuickbar();
        }
    }
References CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), ItemManager::HideDropzones(), InventoryMenu(), SlotsIcon::IsReserved(), InventoryLocation::IsValid(), m_Player, MENU_INVENTORY, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
OnDropReceivedFromHeader()
override void PlayerContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 726 of file playercontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( GetItemPreviewWidget( w ) );
        if( !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        if( !item )
        {
            return;
        }
        if( !item.GetInventory().CanRemoveEntity() )
            return;
        if( m_Player.GetInventory().CanAddEntityToInventory( item, FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT ) && ( !m_Player.GetInventory().HasEntityInInventory( item ) ) )
        {
            m_Player.PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO | FindInventoryLocationType.ATTACHMENT, item );
        }
    }
References ItemPreviewWidget::GetItem(), GetItemPreviewWidget(), and m_Player.
Refresh()
override void PlayerContainer::Refresh () inline private
Definition at line 1097 of file playercontainer.c.
    {
        super.Refresh();
        m_MainWidget.Update();
        m_RootWidget.Update();
        UpdateSelectionIcons();
    }
References m_RootWidget.
Referenced by ItemAttached(), ItemDetached(), OnChildAdd(), OnChildRemove(), RightArea::Refresh(), ToggleContainer(), and ToggleWidget().
Select()
override bool PlayerContainer::Select () inline private
Definition at line 604 of file playercontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().Select();
        }
        else
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
            SlotsIcon focused_slot = GetFocusedSlotsIcon();
            EntityAI focused_item = focused_slot.GetEntity();
            if( focused_slot.IsReserved() || focused_item != selected_item )
            {
                if( selected_item )
                {
                    if(  selected_item.GetInventory().CanRemoveEntity() )
                    {
                        if( m_Player.GetInventory().CanAddAttachmentEx( selected_item, focused_slot.GetSlotID() ) )
{
                            player.PredictiveTakeEntityToTargetAttachmentEx( m_Player, selected_item, focused_slot.GetSlotID());
                            //m_Player.PredictiveTakeEntityAsAttachmentEx( selected_item, focused_slot.GetSlotID() );
                            ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
                            return true;
                        }
                        else if( m_Player.GetInventory().CanAddAttachment( selected_item ) )
{
                            player.PredictiveTakeEntityToTargetAttachment( m_Player, selected_item );
                            //m_Player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, selected_item );
                            ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
                            return true;
                        }
                    }
                }
                else
                {
                    if( focused_item && focused_item.GetInventory().CanRemoveEntity() )
                    {
                        EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
                        if( item_in_hands && item_in_hands.GetInventory().CanRemoveEntity() )
{
                            if( GameInventory.CanSwapEntitiesEx( item_in_hands, focused_item ) )
{
                                player.PredictiveSwapEntities( item_in_hands, focused_item );
                                return true;
                            }
                            else
{
                                InventoryLocation il_hands_dst = new InventoryLocation;
                                if( player.GetHumanInventory().FindFreeLocationFor( item_in_hands, FindInventoryLocationType.ANY, il_hands_dst ) )
{
                                    InventoryMode invMode = InventoryMode.PREDICTIVE;
                                    if ( player.NeedInventoryJunctureFromServer(item_in_hands, item_in_hands.GetHierarchyParent(), il_hands_dst.GetParent()) || GetGame().GetPlayer().NeedInventoryJunctureFromServer(focused_item, focused_item.GetHierarchyParent(), GetGame().GetPlayer()) )
                                        invMode = InventoryMode.JUNCTURE;
                                    player.GetHumanInventory().ForceSwapEntities( invMode, focused_item, item_in_hands, il_hands_dst );
                                    return true;
                                }
                            }
                        }
                        else
{
                            if( player.GetHumanInventory().CanAddEntityInHands( focused_item ) )
{
                                player.PredictiveTakeEntityToHands( focused_item );
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
References SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), InventoryLocation::GetParent(), GetPlayer(), ItemManager::GetSelectedItem(), SlotsIcon::GetSlotID(), SlotsIcon::IsReserved(), m_Player, and ItemManager::SetSelectedItem().
Referenced by RightArea::Select().
SetPlayer()
void PlayerContainer::SetPlayer (PlayerBase player) inline private
Definition at line 681 of file playercontainer.c.
    {
        if( m_Player )
        {
            m_Player.GetOnItemAttached().Remove(ItemAttached);
            m_Player.GetOnItemDetached().Remove(ItemDetached);
            m_Player.GetOnAttachmentSetLock().Remove(OnAttachmentReservationSet);
            m_Player.GetOnAttachmentReleaseLock().Remove(OnAttachmentReservationRelease);
        }
        m_Player = player;
        if( m_Player )
        {
            m_Player.GetOnItemAttached().Insert(ItemAttached);
            m_Player.GetOnItemDetached().Insert(ItemDetached);
            m_Player.GetOnAttachmentSetLock().Insert(OnAttachmentReservationSet);
            m_Player.GetOnAttachmentReleaseLock().Insert(OnAttachmentReservationRelease);
        }
        //START - InitGhostSlots
        string config_path_ghosts_slots = "CfgVehicles SurvivorBase InventoryEquipment playerSlots";
        ref array<string> player_ghosts_slots = new array<string>;
        GetGame().ConfigGetTextArray( config_path_ghosts_slots, player_ghosts_slots );
        for ( int i = 0; i < player_ghosts_slots.Count(); i++ )
        {
            string slot_name = player_ghosts_slots.Get ( i );
            int column = i % ITEMS_IN_ROW;
            int row = i / ITEMS_IN_ROW;
            SlotsIcon icon = GetSlotsIcon( row, column );
            icon.SetSlotParent(m_Player);
            icon.GetMainWidget().Show( true );
            icon.Clear();
            GetGame().ConfigGetText( "CfgSlots" + " " + slot_name + " name", slot_name );
            EntityAI item = m_Player.GetInventory().FindAttachment( InventorySlots.GetSlotIdFromString( slot_name ) );
            if( item )
            {
                ItemAttached( item, slot_name );
            }
        }
    }
References SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), GetGame(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), ItemAttached(), ItemDetached(), ITEMS_IN_ROW, m_Player, OnAttachmentReservationRelease(), OnAttachmentReservationSet(), and SlotsIcon::SetSlotParent().
Referenced by RightArea::RightArea(), and VicinityContainer::UpdateInterval().
SplitItem()
override bool PlayerContainer::SplitItem () inline private
Definition at line 515 of file playercontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().SplitItem();
        }
        return false;
    }
Referenced by RightArea::SplitItem().
SwapItemsInOrder()
void PlayerContainer::SwapItemsInOrder (int slot1, int slot2) inline private
Definition at line 1005 of file playercontainer.c.
    {
        EntityAI item1  = m_Player.GetInventory().FindAttachment( slot1 );
        EntityAI item2  = m_Player.GetInventory().FindAttachment( slot2 );
        if( item1 && item2 )
        {
            Container cont1 = m_ShowedItems.Get( item1 );
            Container cont2 = m_ShowedItems.Get( item2 );
            if( cont1 && cont2 )
            {
                int sort1       = cont1.GetRootWidget().GetSort();
                int sort2       = cont2.GetRootWidget().GetSort();
                cont1.GetRootWidget().SetSort( sort2 );
                cont2.GetRootWidget().SetSort( sort1 );
                m_Body.SwapItems( m_Body.Find( cont1 ), m_Body.Find( cont2 ) );
            }
        }
        RecomputeOpenedContainers();
    }
References m_Player, and m_ShowedItems.
Referenced by RightArea::SwapItemsInOrder().
ToggleContainer()
void PlayerContainer::ToggleContainer (Widget w, EntityAI item) inline private
Definition at line 1050 of file playercontainer.c.
    {
        InventoryLocation il = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation( il );
        SlotsIcon icon = m_InventorySlots.Get( il.GetSlot() );
        ClosableContainer c = ClosableContainer.Cast( m_ShowedItems.Get( item ) );
        if (c)
        {
            c.Toggle();
            Refresh();
        }
    }
References InventoryLocation::GetSlot(), m_InventorySlots, m_ShowedItems, and Refresh().
Referenced by ToggleWidget().
ToggleWidget()
void PlayerContainer::ToggleWidget (Widget w) inline private
Definition at line 1064 of file playercontainer.c.
    {
        if( ItemManager.GetInstance().IsDragging() )
        {
            return;
        }
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( ipw.GetItem() )
        {
            ToggleContainer( w, ipw.GetItem() );
            RecomputeOpenedContainers();
        }
        Refresh();
    }
References ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::IsDragging(), name, Refresh(), string::Replace(), and ToggleContainer().
Referenced by DoubleClick(), and ExpandCollapseContainer().
TransferItem()
override bool PlayerContainer::TransferItem () inline private
Definition at line 543 of file playercontainer.c.
    {
        LeftArea left_area = LeftArea.Cast( GetParent() );
        EntityAI item;
        if( left_area )
        {
            if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
            {
                return GetFocusedContainer().TransferItem();
            }
            else
            {
                item = GetFocusedItem();
                if( item )
                {
                    GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, item );
                    return true;
                }
            }
        }
        else
        {
            if( !GetFocusedContainer().IsInherited( ContainerWithCargo ) && !GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
            {
                item = GetFocusedItem();
                if( item )
                {
                    GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, item );
                    return true;
                }
            }
        }
        return false;
    }
References GetFocusedItem(), GetGame(), GetParent(), and CGame::GetPlayer().
Referenced by RightArea::TransferItem().
TransferItemToVicinity()
override bool PlayerContainer::TransferItemToVicinity () inline private
Definition at line 460 of file playercontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().TransferItemToVicinity();
        }
        else
        {
            Man player = GetGame().GetPlayer();
            ItemBase item = ItemBase.Cast(GetFocusedItem());
            if( item && player.CanDropEntity( item ) )
            {
                if( item.GetTargetQuantityMax() < item.GetQuantity() )
                    item.SplitIntoStackMaxClient( null, -1 );
                else
                    player.PhysicalPredictiveDropItem( item );
                return true;
            }
        }
        return false;
    }
References GetFocusedItem(), GetGame(), and CGame::GetPlayer().
Referenced by RightArea::TransferItemToVicinity().
UnfocusPlayerAttachmentsContainer()
void PlayerContainer::UnfocusPlayerAttachmentsContainer () inline private
Definition at line 365 of file playercontainer.c.
    {
        m_PlayerAttachmentsContainer.UnfocusAll();
    }
References m_PlayerAttachmentsContainer, and Container::UnfocusAll().
UpdateInterval()
override void PlayerContainer::UpdateInterval () inline private
Definition at line 1028 of file playercontainer.c.
    {
        int i;
        for ( i = 0; i < m_InventorySlots.Count(); i++ )
        {
            SlotsIcon icon = m_InventorySlots.GetElement( i );
            if ( icon )
            {
                icon.UpdateInterval();
            }
        }
        for ( i = 0; i < m_ShowedItems.Count(); i++ )
        {
            Container cont = m_ShowedItems.GetElement( i );
            if ( cont )
            {
                cont.UpdateInterval();
            }
        }
    }
References m_InventorySlots, m_ShowedItems, Container::UpdateInterval(), and SlotsIcon::UpdateInterval().
Referenced by RightArea::UpdateInterval().
UpdateRadialIcon()
override void PlayerContainer::UpdateRadialIcon () inline private
Definition at line 11 of file playercontainer.c.
    {
        if ( m_SlotIcon )
        {
            bool show_radial_icon;
            show_radial_icon = IsHidden();
            Widget rip = m_SlotIcon.GetRadialIconPanel();
            rip.Show( !m_Player.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) && m_Player.CanDisplayCargo());
            SetOpenForSlotIcon(show_radial_icon);
        }
    }
References CollapsibleContainer::IsHidden(), and m_Player.
Member Data Documentation
HEADER_INDEX_OFFSET
protected const int PlayerContainer::HEADER_INDEX_OFFSET = 2 private
Definition at line 9 of file playercontainer.c.
m_InventorySlots
protected ref map<int, SlotsIcon> PlayerContainer::m_InventorySlots private
Definition at line 4 of file playercontainer.c.
Referenced by ItemAttached(), ItemDetached(), OnAttachmentReservationRelease(), OnAttachmentReservationSet(), PlayerContainer(), ToggleContainer(), and UpdateInterval().
m_Player
protected PlayerBase PlayerContainer::m_Player private
Definition at line 7 of file playercontainer.c.
Referenced by AddSlotsContainer(), DoubleClick(), DraggingOver(), DraggingOverHeader(), ItemAttached(), MouseClick(), OnDropReceivedFromGhostArea(), OnDropReceivedFromHeader(), Select(), SetPlayer(), SwapItemsInOrder(), UpdateRadialIcon(), and ~PlayerContainer().
m_PlayerAttachmentsContainer
protected ref AttachmentsGroupContainer PlayerContainer::m_PlayerAttachmentsContainer private
Definition at line 3 of file playercontainer.c.
Referenced by AddSlotsContainer(), ExpandCollapseContainer(), GetSlotsIcon(), PlayerContainer(), and UnfocusPlayerAttachmentsContainer().
m_ShowedItems
protected ref map<EntityAI, ref Container> PlayerContainer::m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 5 of file playercontainer.c.
Referenced by HasEntityContainerVisible(), ItemAttached(), ItemDetached(), SwapItemsInOrder(), ToggleContainer(), and UpdateInterval().
m_ShowedItemsIDs
protected ref map<int, ref Container> PlayerContainer::m_ShowedItemsIDs = new ref map<int, ref Container> private
Definition at line 6 of file playercontainer.c.