DayzKode: Debug Class Reference
Debug Class Reference
Static Private Member Functions
static void ActionLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color)
static void CanvasDrawPoint (float x1, float y1, int color)
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
static void ClearCanvas ()
static private void ClearLogs ()
static void ClearScriptLogs ()
static void DestroyAllShapes ()
static Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, int flags=0)
static Shape DrawBox (vector pos1, vector pos2, int color=0x1fff7f7f)
static Shape DrawBoxEx (vector pos1, vector pos2, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOZWRITE)
static array< Shape > DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color=0xFFFFFFFF, int flags=0)
static Shape DrawCube (vector pos, float size=1, int color=0x1fff7f7f)
static Shape DrawCylinder (vector pos, float radius, float height=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static Shape DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.WIREFRAME)
static Shape DrawLine (vector from, vector to, int color=0xFFFFFFFF, int flags=0)
static Shape DrawLines (vector[] positions, int count, int color=0xFFFFFFFF, int flags=0)
static Shape DrawSphere (vector pos, float size=1, int color=0x1fff7f7f, ShapeFlags flags=ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE)
static void GetBaseConfigClasses (out TStringArray base_classes)
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
static private string GetDate ()
static string GetDebugName (Managed entity)
static private string GetFileName ()
static void GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public=true)
Returns config classes containing search_string in name.
static void Init ()
static void InitCanvas ()
static void InventoryHFSMLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryMoveLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void InventoryReservationLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void Log (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static void LogArrayInt (array< int > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogArrayString (array< string > arr=NULL, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void LogError (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as error message.
static void LogInfo (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message with normal prio.
static private void LogMessage (string level, string plugin, string entity, string author, string label, string message)
static void LogWarning (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
Prints debug message as warning message.
static void MeleeLog (Entity entity, string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT)
static void ParticleLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
static void ReceivedLogMessageFromServer (string message)
static void RemoveShape (out Shape shape)
static private void SaveLog (string log_message)
static void SymptomLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void TFLog (string message=LOG_DEFAULT, TestFramework caller=null, string function="")
static void TriggerLog (string message=LOG_DEFAULT, string plugin=LOG_DEFAULT, string author=LOG_DEFAULT, string label=LOG_DEFAULT, string entity=LOG_DEFAULT)
static void WeightLog (string message=LOG_DEFAULT, Managed caller=null, string function="", Managed entity=null)
Static Private Attributes
static private const string LOG_DEBUG = "Debug"
static private const string LOG_DEBUG_ACTION = "Action"
static private const string LOG_DEBUG_INV_HFSM = "HFSM"
static private const string LOG_DEBUG_INV_MOVE = "Inv Move"
static private const string LOG_DEBUG_INV_RESERVATION = "Inv Rrsv"
static private const string LOG_DEBUG_MELEE = "Melee"
static private const string LOG_DEBUG_PARTICLE = "Particle"
static private const string LOG_DEBUG_SYMPTOM = "Symptom"
static private const string LOG_DEBUG_TF = "TestFramework"
static private const string LOG_DEBUG_TRIGGER = "Trigger"
static private const string LOG_DEBUG_WEIGHT = "Weight"
static private const string LOG_DEFAULT = "n/a"
static private const string LOG_ERROR = "Error"
static private const string LOG_INFO = "Info"
static private const string LOG_WARNING = "Warning"
static CanvasWidget m_CanvasDebug
static Widget m_DebugLayoutCanvas
static private ref array< Shape > m_DebugShapes
static private bool m_EnabledLogs
Detailed Description
Definition at line 13 of file debug.c.
Member Function Documentation
ActionLog()
static void Debug::ActionLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 135 of file debug.c.
    {
        LogMessage(LOG_DEBUG_ACTION, plugin, entity, author, label, message);
    }
References LOG_DEBUG_ACTION, and LogMessage().
Referenced by ActionManagerClient::ActionStart(), EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), AnimatedActionBase::Do(), AnimatedActionBase::End(), ActionInput::Init(), ActionInteractBaseCB::InitActionComponent(), ActionBaseCB::Interrupt(), ActionManagerClient::LockInventory(), ActionManagerBase::OnActionEnd(), AnimatedActionBase::OnAnimationEvent(), ActionInteractBaseCB::OnAnimationEvent(), ActionContinuousBase::OnEndAnimationLoop(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionContinuousBase::OnStartAnimationLoop(), ActionInput::SetInput(), SetupAction(), Start(), ActionManagerServer::StartDeliveredAction(), ActionManagerClient::UnlockInventory(), ActionManagerClient::Update(), and ActionManagerServer::Update().
CanvasDrawLine()
static void Debug::CanvasDrawLine (float x1, float y1, float x2, float y2, float width, int color) inline static private
Definition at line 64 of file debug.c.
    {
        InitCanvas();
        m_CanvasDebug.DrawLine(x1, y1, x2, y2, width, color);
    }
References InitCanvas(), and m_CanvasDebug.
Referenced by CanvasDrawPoint().
CanvasDrawPoint()
static void Debug::CanvasDrawPoint (float x1, float y1, int color) inline static private
Draws a "point" on the screen at x,y coordinates Debug.ClearCanvas(); for(int i = 0; i < 700;i++) { float val = i/700; float y = Easing.EaseInOutExpo(val); Debug.CanvasDrawPoint(i,y*700,ARGBF(0.6, 1, 1, 1)); }.
Definition at line 81 of file debug.c.
    {
        CanvasDrawLine(x1, y1, x1+1, y1, 1, color);
    }
References CanvasDrawLine().
ClearCanvas()
static void Debug::ClearCanvas () inline static private
Definition at line 58 of file debug.c.
    {
        if (m_CanvasDebug)
            m_CanvasDebug.Clear();
    }
References m_CanvasDebug.
ClearLogs()
static private void Debug::ClearLogs () inline static private
Definition at line 502 of file debug.c.
    {
        if ( FileExist( GetFileName() ) )
        {
            FileHandle file_index = OpenFile( GetFileName(), FileMode.WRITE );
            if ( file_index == 0 )
            {
                return;
            }
            FPrintln( file_index, "" );
            CloseFile( file_index );
        }
    }
References CloseFile(), FileExist(), FPrintln(), GetFileName(), and OpenFile().
Referenced by ClearScriptLogs().
ClearScriptLogs()
static void Debug::ClearScriptLogs () inline static private
Definition at line 256 of file debug.c.
    {
        ClearLogs();
    }
References ClearLogs().
DestroyAllShapes()
static void Debug::DestroyAllShapes () inline static private
Definition at line 91 of file debug.c.
    {
        for ( int i = 0; i < m_DebugShapes.Count(); ++i )
        {
            if ( m_DebugShapes.Get(i) )
            {
                m_DebugShapes.Get(i).Destroy();
            }
        }
        m_DebugShapes.Clear();
    }
References m_DebugShapes.
DrawArrow()
static Shape Debug::DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 371 of file debug.c.
    {
        Shape shape = Shape.CreateArrow(from, to, size, color, flags);
        m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by Component::DebugDirectionDraw(), VicinityItemManager::DebugRaycastDraw(), PluginBase::DrawDebugs(), DrawDebugShape(), SceneObject::EditorLineAdd(), and UIScriptedMenu::Update().
DrawBox()
static Shape Debug::DrawBox (vector pos1, vector pos2, int color = 0x1fff7f7f) inline static private
Definition at line 261 of file debug.c.
    {
        return DrawBoxEx(pos1, pos2, color, ShapeFlags.TRANSP|ShapeFlags.NOZWRITE);
    }
References DrawBoxEx().
Referenced by Component::DebugBBoxDraw(), DrawDebugCollisionBox(), and SceneObject::EditorShapeAdd().
DrawBoxEx()
static Shape Debug::DrawBoxEx (vector pos1, vector pos2, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOZWRITE) inline static private
Definition at line 266 of file debug.c.
    {
        Shape shape = Shape.Create(ShapeType.BBOX, color, flags, pos1, pos2);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by DrawBox(), and ManBase::EOnPostFrame().
DrawCone()
static array< Shape > Debug::DrawCone (vector pos, float lenght, float halfAngle, float offsetAngle, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 318 of file debug.c.
    {
        array<Shape> shapes = new array<Shape>;
        vector endL, endR;
        Math3D.ConePoints(pos, lenght, halfAngle, offsetAngle, endL, endR);
        // Left side
        shapes.Insert( Debug.DrawLine(pos, endL, color, flags) );
        // Rigth side
        shapes.Insert( Debug.DrawLine(pos, endR, color, flags) );
        // Top side
        shapes.Insert( Debug.DrawLine(endL, endR, color, flags) );
        // Middle (height) line
        shapes.Insert( Debug.DrawLine(pos, pos + Vector(Math.Cos(offsetAngle), 0, Math.Sin(offsetAngle)).Normalized() * lenght, color, flags) );
        return shapes;
    }
References Math3D::ConePoints(), Math::Cos(), DrawLine(), vector::Normalized(), Math::Sin(), and Vector().
DrawCube()
static Shape Debug::DrawCube (vector pos, float size = 1, int color = 0x1fff7f7f) inline static private
Definition at line 274 of file debug.c.
    {
        vector min = pos;
        vector max = pos;
        float size_h = size * 0.5;
        min[0] = min[0] - size_h;
        min[1] = min[1] - size_h;
        min[2] = min[2] - size_h;
        max[0] = max[0] + size_h;
        max[1] = max[1] + size_h;
        max[2] = max[2] + size_h;
        Shape shape = Shape.Create(ShapeType.DIAMOND, color, ShapeFlags.TRANSP|ShapeFlags.NOZWRITE, min, max);
        m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
DrawCylinder()
static Shape Debug::DrawCylinder (vector pos, float radius, float height = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE) inline static private
Definition at line 310 of file debug.c.
    {
        Shape shape = Shape.CreateCylinder(color, flags, pos, radius, height);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), and PluginBase::DrawDebugs().
DrawFrustum()
static Shape Debug::DrawFrustum (float horizontalAngle, float verticalAngle, float length, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.WIREFRAME) inline static private
Definition at line 302 of file debug.c.
    {
        Shape shape = Shape.CreateFrustum(horizontalAngle, verticalAngle, length, color, flags);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
DrawLine()
static Shape Debug::DrawLine (vector from, vector to, int color = 0xFFFFFFFF, int flags = 0) inline static private
DrawLine \nFlags:
ShapeFlags.NOZBUFFER
ShapeFlags.NOZUPDATE
ShapeFlags.DOUBLESIDE
ShapeFlags.WIREFRAME
ShapeFlags.TRANSP
ShapeFlags.ONCE
ShapeFlags.NOOUTLINE
ShapeFlags.NOCULL
Definition at line 349 of file debug.c.
    {
        vector pts[2]
        pts[0] = from;
        pts[1] = to;
        Shape shape = Shape.CreateLines(color, flags, pts, 2);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        //m_DebugShapes.Debug();
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), VicinityItemManager::DebugConeDraw(), DrawCone(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), and GetMeleeTargetEx().
DrawLines()
static Shape Debug::DrawLines (vector[] positions, int count, int color = 0xFFFFFFFF, int flags = 0) inline static private
Definition at line 362 of file debug.c.
    {
        Shape shape = Shape.CreateLines(color, flags, positions, count);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by WeaponDebug::OnPostFrameUpdate().
DrawSphere()
static Shape Debug::DrawSphere (vector pos, float size = 1, int color = 0x1fff7f7f, ShapeFlags flags = ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE) inline static private
Definition at line 294 of file debug.c.
    {
        Shape shape = Shape.CreateSphere(color, flags, pos, size);
        if (( flags & ShapeFlags.ONCE ) == 0)
            m_DebugShapes.Insert(shape);
        return shape;
    }
References m_DebugShapes, and Shape.
Referenced by CalculateEyeAccoTarget(), VicinityItemManager::DebugActorsSphereDraw(), VicinityItemManager::DebugObjectsSphereDraw(), WeaponDebug::DrawBarrelMemoryPoints(), DrawDebugShape(), WeaponDebug::DrawEyePoint(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), PluginBase::EditorUpdateRuler(), and Hologram::GetProjectionEntityPosition().
GetBaseConfigClasses()
static void Debug::GetBaseConfigClasses (out TStringArray base_classes) inline static private
Returns some of base config classes strings like CfgVehicles, CfgWeapons, etc. for searching purposes.
Parameters
base_classes out TStringArray Array containing some of base config classes
Definition at line 384 of file debug.c.
    {
        base_classes.Clear();
        base_classes.Insert(CFG_VEHICLESPATH);
        base_classes.Insert(CFG_WEAPONSPATH);
        base_classes.Insert(CFG_MAGAZINESPATH);
        base_classes.Insert(CFG_AMMO);
        base_classes.Insert(CFG_WORLDS);
        base_classes.Insert(CFG_SURFACES);
        base_classes.Insert(CFG_SOUND_SETS);
        base_classes.Insert(CFG_SOUND_SHADERS);
        base_classes.Insert(CFG_NONAI_VEHICLES);
    }
References CFG_AMMO, CFG_MAGAZINESPATH, CFG_NONAI_VEHICLES, CFG_SOUND_SETS, CFG_SOUND_SHADERS, CFG_SURFACES, CFG_VEHICLESPATH, CFG_WEAPONSPATH, and CFG_WORLDS.
Referenced by UIPopupScript::ClearHierarchy(), UIPopupScript::FindInHierarchy(), GetFiltredConfigClasses(), and UIScriptedMenu::Init().
GetDate()
static private string Debug::GetDate () inline static private
Definition at line 524 of file debug.c.
    {
        int year;
        int month;
        int day;
        int hour;
        int minute;
        int second;
        GetYearMonthDay(year, month, day);
        GetHourMinuteSecond(hour, minute, second);
        string date = month.ToStringLen(2) + "-" + day.ToStringLen(2) + " " + hour.ToStringLen(2) + ":" + minute.ToStringLen(2) + ":" + second.ToStringLen(2);
        return date;
    }
References GetHourMinuteSecond(), and GetYearMonthDay().
Referenced by LogMessage().
GetDebugName()
static string Debug::GetDebugName (Managed entity) inline static private
Definition at line 37 of file debug.c.
    {
        if (!entity)
            return "";
        Object obj;
        if (CastTo(obj, entity))
            return obj.GetDebugNameNative();
        return entity.GetDebugName();
    }
GetFileName()
static private string Debug::GetFileName () inline static private
Definition at line 519 of file debug.c.
    {
        return CFG_FILE_SCRIPT_LOG_EXT;
    }
References CFG_FILE_SCRIPT_LOG_EXT.
Referenced by ClearLogs().
GetFiltredConfigClasses()
static void Debug::GetFiltredConfigClasses (string search_string, out TStringArray filtered_classes, bool only_public = true) inline static private
Returns config classes containing search_string in name.
Parameters
search_string string String to search in class names
filtered_classes out TStringArray Array containing filtered classes based on search_string
only_public bool Set to true to return only public classes, set to false to return all filtered classes
Definition at line 404 of file debug.c.
    {
        TStringArray searching_in = new TStringArray;
        GetBaseConfigClasses( searching_in );
        filtered_classes.Clear();
        search_string.ToLower();
        for ( int s = 0; s < searching_in.Count(); ++s )
        {
            string config_path = searching_in.Get(s);
            int objects_count = GetGame().ConfigGetChildrenCount(config_path);
            for (int i = 0; i < objects_count; i++)
            {
                string childName;
                GetGame().ConfigGetChildName(config_path, i, childName);
                if ( only_public )
                {
                    int scope = GetGame().ConfigGetInt( config_path + " " + childName + " scope" );
                    if ( scope == 0 )
                    {
                        continue;
                    }
                }
                string nchName = childName;
                nchName.ToLower();
                if ( nchName.Contains(search_string) != -1)
                {
                    filtered_classes.Insert(childName);
                }
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), string::Contains(), GetBaseConfigClasses(), GetGame(), and string::ToLower().
Init()
static void Debug::Init () inline static private
Definition at line 86 of file debug.c.
    {
        m_DebugShapes   = new array<Shape>;
    }
References m_DebugShapes.
Referenced by DayZGame().
InitCanvas()
static void Debug::InitCanvas () inline static private
Definition at line 49 of file debug.c.
    {
        if (!m_DebugLayoutCanvas)
        {
            m_DebugLayoutCanvas = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debugcanvas.layout");
            m_CanvasDebug = CanvasWidget.Cast( m_DebugLayoutCanvas.FindAnyWidget( "CanvasWidget" ) );
        }
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_CanvasDebug, and m_DebugLayoutCanvas.
Referenced by CanvasDrawLine().
InventoryHFSMLog()
static void Debug::InventoryHFSMLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 155 of file debug.c.
    {
        LogMessage(LOG_DEBUG_INV_HFSM, plugin, entity, author, label, message);
    }
References LOG_DEBUG_INV_HFSM, and LogMessage().
Referenced by HandActionBase::Action(), HandEventBase::CanPerformEvent(), HandEventSwap::CanPerformEvent(), HandEventBase::CheckRequest(), HandEventSwap::CheckRequest(), HandEventBase::CheckRequestSrc(), HandGuardBase::GuardCondition(), HandGuardHasItemInEvent::GuardCondition(), HandleHandEvent(), HandleTakeToDst(), HandStateBase::OnAbort(), HandStartAction::OnEntry(), and HumanInventoryWithFSM::ProcessHandEvent().
InventoryMoveLog()
static void Debug::InventoryMoveLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 145 of file debug.c.
    {
        LogMessage(LOG_DEBUG_INV_MOVE, plugin, entity, author, label, message);
    }
References LOG_DEBUG_INV_MOVE, and LogMessage().
Referenced by AddInventoryReservationEx(), ClearInventoryReservationEx(), ExtendInventoryReservationEx(), ForceSwapEntities(), HandleForceSwapEntities(), HandleInputData(), HandleSwapEntities(), HandleTakeToDst(), ProccessInputData(), StoreInputForRemotes(), SwapEntities(), TakeToDst(), and TryAcquireTwoInventoryJuncturesFromServer().
InventoryReservationLog()
static void Debug::InventoryReservationLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 150 of file debug.c.
    {
        LogMessage(LOG_DEBUG_INV_RESERVATION, plugin, entity, author, label, message);
    }
References LOG_DEBUG_INV_RESERVATION, and LogMessage().
Referenced by CGame::AddInventoryJunctureEx(), CGame::ClearJunctureEx(), and TryAcquireTwoInventoryJuncturesFromServer().
Log()
static void Debug::Log (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
Definition at line 130 of file debug.c.
    {
        LogMessage(LOG_DEBUG, plugin, entity, author, label, message);
    }
References LOG_DEBUG, and LogMessage().
Referenced by InventoryItem::AddAction(), RecipeBase::ApplyModificationsResults(), Managed::BleedingIndicator(), PluginRecipesManagerBase::CallbackGenerateCache(), ChangePPEMaterial(), PPEManagerStatic::CreateManagerStatic(), Debug(), RecipeBase::Do(), UIScriptedMenu::DrawItems(), ContaminatedArea_Static::EEInit(), SpookyArea::EEInit(), KeysToUIElements::GetKeyToUIElement(), GetName(), Managed::GetRequester(), Managed::GetRequesterID(), Managed::GetRequesterTypename(), LogTemplates::GetTemplate(), GetValue(), MissionBase::InvokeOnConnect(), MissionBase::InvokeOnDisconnect(), MessageReceiverBase::Log(), PluginBase::Log(), Component::LogThis(), BloodTypes::MatchBloodCompatibility(), ManBase::OnConnect(), ManBase::OnDisconnect(), MissionBase::OnEvent(), ActionDigInStash::OnFinishProgressServer(), Icon::OnPerformRecipe(), ManBase::OnReconnect(), OnSoundEvent(), OnStepEvent(), OpenAndSwitchLambda::OnSuccess(), OnUpdate(), RecipeBase::PerformRecipe(), MissionBase::PlayerControlDisable(), PlayerAgentPool::PrintAgents(), PrintOut(), PluginRecipesManagerBase::PrintResultMasks(), ItemBase::PrintSlots(), GameplayEffectsData::RegisterData(), KeysToUIElements::RegisterKeyToUIElement(), LogTemplates::RegisterLogTamplate(), Managed::RegisterRequester(), ManBase::Save(), PPERequesterBase::SetRequesterUpdating(), SetRequestUpdating(), RecipeBase::SpawnItems(), Managed::VerifyRequester(), and WorldData::WeatherOnBeforeChange().
LogArrayInt()
static void Debug::LogArrayInt (array< int > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 231 of file debug.c.
    {
        if (arr== NULL) return;
        for (int i = 0; i < arr.Count(); i++)
        {
            LogMessage(LOG_DEBUG, plugin, entity, author, label, arr.Get(i).ToString() );
        }
    }
References string::Get(), LOG_DEBUG, LogMessage(), and string::ToString().
LogArrayString()
static void Debug::LogArrayString (array< string > arr = NULL, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 241 of file debug.c.
    {
        if (arr== NULL) return;
        for (int i = 0; i < arr.Count(); i++)
        {
            LogMessage(LOG_DEBUG, plugin, entity, author, label, arr.Get(i) );
        }
    }
References string::Get(), LOG_DEBUG, and LogMessage().
Referenced by PrintOut().
LogError()
static void Debug::LogError (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as error message.
Parameters
msg string Debug message for error print
Returns
void None
Debug.LogError("Hello World, this is error log");
>> [Error]: Hello World, this is error log
Definition at line 226 of file debug.c.
    {
        LogMessage(LOG_ERROR, plugin, entity, author, label, message);
    }
References LOG_ERROR, and LogMessage().
Referenced by EntityAI::AddAction(), AddAction(), InventoryItem::AddAction(), ActionCollectBloodTargetLambda::CopyOldPropertiesToNew(), TanLeatherLambda::CopyOldPropertiesToNew(), ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), DeveloperFreeCamera::DisableFreeCamera(), DeveloperFreeCamera::EnableFreeCamera(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), FireworksLauncherClientEvent::GetShotPos(), LogError(), Component::LogErrorBadCompType(), Component::LogThisError(), Component::LogWarningAlredyExist(), Normalize(), OnStoreLoad(), SymptomManager::OnSymptomExit(), OpenItem::OpenAndSwitch(), PlaySound(), InventoryItem::SetQuantity(), and Tick().
LogInfo()
static void Debug::LogInfo (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
Debug.Log("Hello World");
>> [Log]: Hello World;
Definition at line 196 of file debug.c.
    {
        LogMessage(LOG_INFO, plugin, entity, author, label, message);
    }
References LOG_INFO, and LogMessage().
Referenced by LogInfo().
LogMessage()
static private void Debug::LogMessage (string level, string plugin, string entity, string author, string label, string message) inline static private
Definition at line 448 of file debug.c.
    {
        if (GetGame() == NULL || LogManager.IsLogsEnable() == false )
        {
            return;
        }
        bool is_server_log = ( GetGame().IsServer() && GetGame().IsMultiplayer() );
        // Formation output to external file
        // %date{MM-dd HH:mm:ss} | %Enviroment | %Level | %Module | %Entity | %Author | %Label | %Message
        string date         = GetDate();
        string env          = "Client";
        string msg          = string.Empty;
        if ( is_server_log )
        {
            env = "Server";
        }
        msg = string.Format("%1 | %2 | %3 | %4 | %5 | %6 | %7", date, env, level, plugin, entity, label, message);
        if ( is_server_log )
        {
            SaveLog(msg);
#ifdef DEVELOPER //not sendig log to clients on stable
            Param1<string> msg_p = new Param1<string>(msg);
            CallMethod(CALL_ID_SEND_LOG, msg_p);
#endif
        }
        else
        {
            SaveLog(msg);
        }
    }
References CALL_ID_SEND_LOG, CallMethod(), string::Format(), GetDate(), GetGame(), LogManager::IsLogsEnable(), CGame::IsMultiplayer(), CGame::IsServer(), and SaveLog().
Referenced by ActionLog(), InventoryHFSMLog(), InventoryMoveLog(), InventoryReservationLog(), Log(), LogArrayInt(), LogArrayString(), LogError(), LogInfo(), LogWarning(), MeleeLog(), ParticleLog(), SymptomLog(), TFLog(), and TriggerLog().
LogWarning()
static void Debug::LogWarning (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Prints debug message as warning message.
Parameters
msg string Debug message for warning print
Returns
void None
Debug.LogWarning("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
Definition at line 211 of file debug.c.
    {
        LogMessage(LOG_WARNING, plugin, entity, author, label, message);
    }
References LOG_WARNING, and LogMessage().
Referenced by Component::LogThisWarning(), LogWarning(), and DeveloperTeleport::TeleportAtCursor().
MeleeLog()
static void Debug::MeleeLog (Entity entity, string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT) inline static private
Definition at line 180 of file debug.c.
    {
        string logMessage = string.Format("%1: %2", entity.GetSimulationTimeStamp(), message);
        LogMessage(LOG_DEBUG_MELEE, plugin, GetDebugName(entity), author, label, message);
    }
References GetDebugName(), LOG_DEBUG_MELEE, and LogMessage().
ParticleLog()
static void Debug::ParticleLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
Definition at line 165 of file debug.c.
    {
        LogMessage(LOG_DEBUG_PARTICLE, GetDebugName(caller), GetDebugName(entity), "", function, message);
    }
References GetDebugName(), LOG_DEBUG_PARTICLE, and LogMessage().
Referenced by PMTF::PrintActiveStats(), PMTF::PrintPMStats(), TestInvalidSize(), and TestOwnership().
ReceivedLogMessageFromServer()
static void Debug::ReceivedLogMessageFromServer (string message) inline static private
Definition at line 250 of file debug.c.
    {
        if ( LogManager.IsLogsEnable() )
            SaveLog(message);
    }
References LogManager::IsLogsEnable(), and SaveLog().
Referenced by PluginBase::OnRPCServerLogRecieved().
RemoveShape()
static void Debug::RemoveShape (out Shape shape) inline static private
Definition at line 104 of file debug.c.
    {
        if (!shape) return;
        for ( int i = 0; i < m_DebugShapes.Count(); i++ )
        {
            Shape found_shape = m_DebugShapes.Get(i);
            if ( found_shape  &&  found_shape == shape )
            {
                found_shape.Destroy();
                m_DebugShapes.Remove(i); // Mandatory! Otherwise the Destroy() function causes crash!
                shape = null;
                return;
            }
        }
    }
References m_DebugShapes, and Shape.
Referenced by VicinityItemManager::CleanupDebugShapes(), DrawDebugShape(), WeaponDebug::DrawLineOfFire(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), WeaponDebug::RemoveAllShapes(), and ~BleedingSource().
SaveLog()
static private void Debug::SaveLog (string log_message) inline static private
Definition at line 485 of file debug.c.
    {
        Print("" + log_message);
        //Previous was saved to separate file
        /*FileHandle file_index = OpenFile(GetFileName(), FileMode.APPEND);
        if ( file_index == 0 )
        {
            return;
        }
        FPrintln(file_index, log_message);
        CloseFile(file_index);*/
    }
References Print().
Referenced by LogMessage(), and ReceivedLogMessageFromServer().
SymptomLog()
static void Debug::SymptomLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 140 of file debug.c.
    {
        LogMessage(LOG_DEBUG_SYMPTOM, plugin, entity, author, label, message);
    }
References LOG_DEBUG_SYMPTOM, and LogMessage().
Referenced by SymptomBase::OnGetActivatedClient(), SymptomBase::OnGetActivatedServer(), SymptomBase::OnGetDeactivatedClient(), and SymptomBase::OnGetDeactivatedServer().
TFLog()
static void Debug::TFLog (string message = LOG_DEFAULT, TestFramework caller = null, string function = "") inline static private
Definition at line 170 of file debug.c.
    {
        LogMessage(LOG_DEBUG_TF, GetDebugName(caller), "", "", function, message);
    }
References GetDebugName(), LOG_DEBUG_TF, and LogMessage().
Referenced by TFModule::PrintResult(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
TriggerLog()
static void Debug::TriggerLog (string message = LOG_DEFAULT, string plugin = LOG_DEFAULT, string author = LOG_DEFAULT, string label = LOG_DEFAULT, string entity = LOG_DEFAULT) inline static private
Definition at line 160 of file debug.c.
    {
        LogMessage(LOG_DEBUG_TRIGGER, plugin, entity, author, label, message);
    }
References LOG_DEBUG_TRIGGER, and LogMessage().
Referenced by Trigger::AddInsider(), TriggerEvents::Enter(), TriggerEvents::Leave(), Trigger::RemoveInsider(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), and Trigger::UpdateInsiders().
WeightLog()
static void Debug::WeightLog (string message = LOG_DEFAULT, Managed caller = null, string function = "", Managed entity = null) inline static private
Definition at line 175 of file debug.c.
    {
        //LogMessage(LOG_DEBUG_WEIGHT, GetDebugName(caller), GetDebugName(entity), "", function, message);
    }
Member Data Documentation
LOG_DEBUG
private const string Debug::LOG_DEBUG = "Debug" static private
Definition at line 15 of file debug.c.
Referenced by Log(), LogArrayInt(), and LogArrayString().
LOG_DEBUG_ACTION
private const string Debug::LOG_DEBUG_ACTION = "Action" static private
Definition at line 16 of file debug.c.
Referenced by ActionLog().
LOG_DEBUG_INV_HFSM
private const string Debug::LOG_DEBUG_INV_HFSM = "HFSM" static private
Definition at line 20 of file debug.c.
Referenced by InventoryHFSMLog().
LOG_DEBUG_INV_MOVE
private const string Debug::LOG_DEBUG_INV_MOVE = "Inv Move" static private
Definition at line 18 of file debug.c.
Referenced by InventoryMoveLog().
LOG_DEBUG_INV_RESERVATION
private const string Debug::LOG_DEBUG_INV_RESERVATION = "Inv Rrsv" static private
Definition at line 19 of file debug.c.
Referenced by InventoryReservationLog().
LOG_DEBUG_MELEE
private const string Debug::LOG_DEBUG_MELEE = "Melee" static private
Definition at line 25 of file debug.c.
Referenced by MeleeLog().
LOG_DEBUG_PARTICLE
private const string Debug::LOG_DEBUG_PARTICLE = "Particle" static private
Definition at line 22 of file debug.c.
Referenced by ParticleLog().
LOG_DEBUG_SYMPTOM
private const string Debug::LOG_DEBUG_SYMPTOM = "Symptom" static private
Definition at line 17 of file debug.c.
Referenced by SymptomLog().
LOG_DEBUG_TF
private const string Debug::LOG_DEBUG_TF = "TestFramework" static private
Definition at line 23 of file debug.c.
Referenced by TFLog().
LOG_DEBUG_TRIGGER
private const string Debug::LOG_DEBUG_TRIGGER = "Trigger" static private
Definition at line 21 of file debug.c.
Referenced by TriggerLog().
LOG_DEBUG_WEIGHT
private const string Debug::LOG_DEBUG_WEIGHT = "Weight" static private
Definition at line 24 of file debug.c.
LOG_DEFAULT
private const string Debug::LOG_DEFAULT = "n/a" static private
Definition at line 30 of file debug.c.
LOG_ERROR
private const string Debug::LOG_ERROR = "Error" static private
Definition at line 29 of file debug.c.
Referenced by LogError().
LOG_INFO
private const string Debug::LOG_INFO = "Info" static private
Definition at line 27 of file debug.c.
Referenced by LogInfo().
LOG_WARNING
private const string Debug::LOG_WARNING = "Warning" static private
Definition at line 28 of file debug.c.
Referenced by LogWarning().
m_CanvasDebug
CanvasWidget Debug::m_CanvasDebug static private
Definition at line 35 of file debug.c.
Referenced by CanvasDrawLine(), ClearCanvas(), and InitCanvas().
m_DebugLayoutCanvas
Widget Debug::m_DebugLayoutCanvas static private
Definition at line 34 of file debug.c.
Referenced by InitCanvas().
m_DebugShapes
private ref array<Shape> Debug::m_DebugShapes static private
Definition at line 32 of file debug.c.
Referenced by DestroyAllShapes(), DrawArrow(), DrawBoxEx(), DrawCube(), DrawCylinder(), DrawFrustum(), DrawLine(), DrawLines(), DrawSphere(), Init(), and RemoveShape().
m_EnabledLogs
private bool Debug::m_EnabledLogs static private
Definition at line 446 of file debug.c.