DayzKode: M18SmokeGrenade_ColorBase Class Reference
M18SmokeGrenade_ColorBase Class Reference
Private Member Functions
void M18SmokeGrenade_White ()
void M18SmokeGrenade_Yellow ()
Detailed Description
Definition at line 51 of file m18smokegrenade_colorbase.c.
Member Function Documentation
M18SmokeGrenade_White()
void M18SmokeGrenade_ColorBase::M18SmokeGrenade_White () inline private
Definition at line 73 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_WHITE_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_WHITE_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_WHITE_END);
    }
References ParticleList::GRENADE_M18_WHITE_END, ParticleList::GRENADE_M18_WHITE_LOOP, ParticleList::GRENADE_M18_WHITE_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
M18SmokeGrenade_Yellow()
void M18SmokeGrenade_ColorBase::M18SmokeGrenade_Yellow () inline private
Definition at line 53 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_YELLOW_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_YELLOW_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_YELLOW_END);
    }
References ParticleList::GRENADE_M18_YELLOW_END, ParticleList::GRENADE_M18_YELLOW_LOOP, ParticleList::GRENADE_M18_YELLOW_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().