DayzKode: ActionRepairShelter Class Reference
ActionRepairShelter Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRepairShelter ()
override void CreateConditionComponents ()
override bool IsUsingProxies ()
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 2 of file actionrepairshelter.c.
Constructor & Destructor Documentation
ActionRepairShelter()
void ActionRepairShelter::ActionRepairShelter () inline private
Definition at line 4 of file actionrepairshelter.c.
    {
        m_CallbackClass = ActionRepairTentCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepairShelter::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 25 of file actionrepairshelter.c.
    {
        ShelterBase shelter = ShelterBase.Cast( target.GetObject() );
        if ( !shelter )
            return false;
        if ( player && shelter )
        {
            PluginRepairing module_repairing;
            Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
            if (module_repairing.CanRepair(item,shelter))
            {
                return true;
            }
        }
        return false;
    }
References Class::CastTo(), and GetPlugin().
CreateConditionComponents()
override void ActionRepairShelter::CreateConditionComponents () inline private
Definition at line 14 of file actionrepairshelter.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursor(UAMaxDistances.SMALL);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
IsUsingProxies()
override bool ActionRepairShelter::IsUsingProxies () inline private
Definition at line 20 of file actionrepairshelter.c.
    {
        return false;
    }
OnFinishProgressServer()
override void ActionRepairShelter::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 44 of file actionrepairshelter.c.
    {
        ShelterBase shelter = ShelterBase.Cast( action_data.m_Target.GetObject() );
        if ( shelter )
        {
            PluginRepairing module_repairing;
            Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
            module_repairing.Repair(action_data.m_Player,action_data.m_MainItem,shelter,m_SpecialtyWeight);
        }
    }
References Class::CastTo(), GetPlugin(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.