DayzKode: ActionActivateTrap Class Reference
ActionActivateTrap Class Reference
Private Member Functions
void ActionActivateTrap ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override void OnEnd (ActionData action_data)
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
Detailed Description
Definition at line 16 of file actionactivatetrap.c.
Constructor & Destructor Documentation
ActionActivateTrap()
void ActionActivateTrap::ActionActivateTrap () inline private
Definition at line 18 of file actionactivatetrap.c.
    {
        m_CallbackClass = ActionActivateTrapCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Sound = "craft_universal_0";
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_Text = "#activate";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_Sound, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionActivateTrap::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 45 of file actionactivatetrap.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        if ( tgt_item && tgt_item.IsBeingPlaced() )
            return false;
        Object targetObject = target.GetObject();
        if ( targetObject != NULL )
        {
            if ( targetObject.IsInherited( TrapBase ) )
            {
                TrapBase trap = TrapBase.Cast( targetObject );
                if ( trap.IsActivable() )
                {
                    return true;
                }
            }
            else if ( targetObject.IsInherited( TrapSpawnBase ) )
            {
                TrapSpawnBase spawnTrap = TrapSpawnBase.Cast( targetObject );
                if ( spawnTrap && !spawnTrap.IsActive() )
                    return spawnTrap.IsPlaceableAtPosition( spawnTrap.GetPosition() );
            }
        }
        return false;
    }
References TrapSpawnBase::IsPlaceableAtPosition().
CreateConditionComponents()
override void ActionActivateTrap::CreateConditionComponents () inline private
Definition at line 29 of file actionactivatetrap.c.
    {
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.DEFAULT );
        m_ConditionItem = new CCINotPresent;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionActivateTrap::GetInputType () inline private
Definition at line 35 of file actionactivatetrap.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionActivateTrap::HasProgress () inline private
Definition at line 40 of file actionactivatetrap.c.
    {
        return true;
    }
OnEnd()
override void ActionActivateTrap::OnEnd (ActionData action_data) inline private
Definition at line 90 of file actionactivatetrap.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            TrapBase trap = TrapBase.Cast( action_data.m_Target.GetObject());
            if ( trap )
            {
                Param1<bool> play = new Param1<bool>( false );
                GetGame().RPCSingleParam( trap, SoundTypeTrap.ACTIVATING, play, true );
            }
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnEndAnimationLoop()
override void ActionActivateTrap::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 103 of file actionactivatetrap.c.
    {
        super.OnEndAnimationLoop( action_data );
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            TrapBase trap = TrapBase.Cast( action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>( false );
            GetGame().RPCSingleParam( trap, SoundTypeTrap.ACTIVATING, play, true );
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void ActionActivateTrap::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 115 of file actionactivatetrap.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        if ( targetObject != NULL )
        {
            if ( targetObject.IsInherited( TrapBase ) )
            {
                TrapBase trap = TrapBase.Cast( targetObject );
                trap.StartActivate( action_data.m_Player );
                return;
            }
            else if ( targetObject.IsInherited( TrapSpawnBase ) )
            {
                TrapSpawnBase spawnTrap = TrapSpawnBase.Cast( targetObject );
                Trap_RabbitSnare snareTrap;
                vector orientation = action_data.m_Player.GetOrientation();
                vector position = action_data.m_Player.GetPosition();
                position = position + ( action_data.m_Player.GetDirection() * 0.5 );
                // We want to make sure the snare trap is standing upwards
                if ( CastTo( snareTrap, spawnTrap ) )
                {
                    orientation = action_data.m_Player.GetLocalProjectionOrientation();
                    vector rotation_matrix[3];
                    float direction[4];
                    InventoryLocation source = new InventoryLocation;
                    InventoryLocation destination = new InventoryLocation;
                    Math3D.YawPitchRollMatrix( orientation, rotation_matrix );
                    Math3D.MatrixToQuat( rotation_matrix, direction );
                    if ( spawnTrap.GetInventory().GetCurrentInventoryLocation( source ) )
                    {
                        destination.SetGroundEx( spawnTrap, position, direction );
                        if ( GetGame().IsMultiplayer() )
{
                            action_data.m_Player.ServerTakeToDst(source, destination);
                        }
                    }
                }
                //Debug.Log("Trap pos : " + spawnTrap.GetPosition() );
                //Debug.Log("Player pos : " + action_data.m_Player.GetPosition() );
                spawnTrap.OnPlacementComplete( action_data.m_Player, position, orientation );
                return;
            }
        }
    }
References GetGame(), CGame::IsMultiplayer(), ActionData::m_Player, ActionData::m_Target, Math3D::MatrixToQuat(), TrapSpawnBase::OnPlacementComplete(), InventoryLocation::SetGroundEx(), and Math3D::YawPitchRollMatrix().
OnStartAnimationLoop()
override void ActionActivateTrap::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 75 of file actionactivatetrap.c.
    {
        super.OnStartAnimationLoop( action_data );
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            TrapBase trap = TrapBase.Cast( action_data.m_Target.GetObject() );
            if ( trap )
            {
                Param1<bool> play = new Param1<bool>( true );
                GetGame().RPCSingleParam( trap, SoundTypeTrap.ACTIVATING, play, true );
            }
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().