DayzKode: Clothing Class Reference
Clothing Class Reference
Private Member Functions
override bool AllowFoodConsumption ()
void AttachLightOnHead (EntityAI person)
override bool CanDetachAttachment (EntityAI parent)
bool CanHaveExternalFilter ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
void CheckParent ()
bool ConsumeQuantity (float quantity, PlayerBase consumer_player)
void CreateHeadtorchLight ()
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override array< int > GetEffectWidgetTypes ()
override array< int > GetEffectWidgetTypes ()
EntityAI GetExternalFilter ()
float GetFilterQuantity ()
float GetFilterQuantity01 ()
float GetFilterQuantityMax ()
override int GetGlassesEffectID ()
override int GetGlassesEffectID ()
override int GetGlassesEffectID ()
bool GetIncomingLambdaBool ()
override ItemBase GetLightSourceItem ()
override int GetVoiceEffect ()
bool HasIntegratedFilter ()
bool HasValidFilter ()
has either external or integrated non-empty non-ruined filter ?
void Headtorch_ColorBase ()
override bool IsClothing ()
bool IsExternalFilterAttached ()
override bool IsGasMask ()
override bool IsLightSource ()
override bool IsObstructingVoice ()
void LargeTentBackPack ()
void MouthRag ()
override void OnDebugSpawn ()
void OnLightCreated ()
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player)
void OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity)
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
void PlayRepackingLoopSound ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void SetIncomingLambaBool (bool state)
void StopRepackingLoopSound ()
override void SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par=null)
void ~LargeTentBackPack ()
Private Attributes
bool m_IncomingLambdaChange
HeadtorchLight m_Light
float m_LowFilterEventTime
ref protected EffectSound m_RepackingLoopSound
ref Timer m_Timer
Static Private Attributes
static int GLASS_ID = 5
static string LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat"
static string LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat"
static string LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat"
static string LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat"
static string m_OffHeadLightPoint = "beamStart"
static string m_OffHeadLightTarget = "beamEnd"
static vector m_OnHeadLocalOri = Vector(0,90,0)
static vector m_OnHeadLocalPos = Vector(0.12,0.15,0)
static int REFLECTOR_ID = 4
Detailed Description
Definition at line 1 of file alicebag_colorbase.c.
Constructor & Destructor Documentation
~LargeTentBackPack()
void Clothing::~LargeTentBackPack () inline private
Definition at line 10 of file largetentbackpack.c.
    {
        SEffectManager.DestroyEffect( m_RepackingLoopSound );
    }
References SEffectManager::DestroyEffect(), and m_RepackingLoopSound.
Member Function Documentation
AllowFoodConsumption()
override bool Clothing::AllowFoodConsumption () inline private
Definition at line 20 of file maskbase.c.
    {
        return false;
    }
AttachLightOnHead()
void Clothing::AttachLightOnHead (EntityAI person) inline private
Definition at line 150 of file headtorch_colorbase.c.
    {
        if (person.IsPlayer())
        {
            PlayerBase player = PlayerBase.Cast(person);
            int boneIdx = player.GetBoneIndexByName("Head");
            if( boneIdx != -1 )
            {
                if ( m_Light.GetParent() )
                    m_Light.DetachFromParent();
                m_Light.SetPosition( m_OnHeadLocalPos );
                m_Light.SetOrientation( m_OnHeadLocalOri );
                player.AddChild(m_Light, boneIdx);
            }
        }
        else if (person.IsZombie())
        {
            if ( m_Light.GetParent() )
                m_Light.DetachFromParent();
            m_Light.SetPosition( m_OnHeadLocalPos );
            m_Light.SetOrientation( m_OnHeadLocalOri );
            person.AddChild(m_Light, 17);
        }
    }
References m_Light.
Referenced by CreateHeadtorchLight(), and OnWasAttached().
CanDetachAttachment()
override bool Clothing::CanDetachAttachment (EntityAI parent) inline private
Definition at line 10 of file mouthrag.c.
    {
        return m_IncomingLambdaChange;
    }
References m_IncomingLambdaChange.
CanHaveExternalFilter()
bool Clothing::CanHaveExternalFilter () inline private
Definition at line 123 of file maskbase.c.
    {
        return !HasIntegratedFilter();
    }
CanPutAsAttachment() [1/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file armband_colorbase.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( GetQuantity() <= 1 )
        {
            return true;
        }
        return false;
    }
References GetQuantity().
CanPutAsAttachment() [2/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file crookednose.c.
    {
        if (!super.CanPutAsAttachment(parent)) {return false;}
        Clothing headgear = Clothing.Cast(parent.FindAttachmentBySlotName("Headgear"));
        if ( headgear && headgear.ConfigGetBool("noMask") )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [3/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 30 of file headtorch_colorbase.c.
    {
        if (!super.CanPutAsAttachment(parent)) {return false;}
        Clothing helmet = Clothing.Cast(parent.FindAttachmentBySlotName("Headgear"));
        if ( helmet && helmet.ConfigGetBool("noNVStrap") )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [4/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file hockeymask.c.
    {
        if (!super.CanPutAsAttachment(parent)) {return false;}
        Clothing headgear = Clothing.Cast(parent.FindAttachmentBySlotName("Headgear"));
        if ( headgear && (headgear.ConfigGetBool("noMask") && !PumpkinHelmet.Cast(headgear)) )
        {
            return false;
        }
        Clothing eyewear = Clothing.Cast(parent.FindAttachmentBySlotName("Eyewear"));
        if ( eyewear && SportGlasses_ColorBase.Cast(eyewear) )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [5/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file nvgheadstrap.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        Clothing helmet = Clothing.Cast(parent.FindAttachmentBySlotName( "Headgear" ));
        if ( helmet && helmet.ConfigGetBool("noNVStrap") )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [6/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file santasbeard.c.
    {
        if (!super.CanPutAsAttachment(parent)) {return false;}
        Clothing headgear = Clothing.Cast(parent.FindAttachmentBySlotName("Headgear"));
        if ( headgear && (headgear.ConfigGetBool("noMask") && !PumpkinHelmet.Cast(headgear) && !WeldingMask.Cast(headgear)) )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [7/7]
override bool Clothing::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file sportglasses_colorbase.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        Clothing mask = Clothing.Cast(parent.FindAttachmentBySlotName("Mask"));
        if ( mask && mask.ConfigGetBool("noEyewear") ) //TODO
        {
            return false;
        }
        return true;
    }
CanPutInCargo() [1/2]
override bool Clothing::CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file armband_colorbase.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        if ( GetNumberOfItems() == 0 || !parent || parent.IsMan() )
        {
            return true;
        }
        return false;
    }
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutInCargo() [2/2]
override bool Clothing::CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file leatherbelt_colorbase.c.
    {
        if( !super.CanPutInCargo( parent ) )
        {
            return false;
        }
        return IsEmpty();
    }
References IsEmpty().
CanReceiveAttachment()
override bool Clothing::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 13 of file leatherbelt_colorbase.c.
    {
        if( !super.CanReceiveAttachment( attachment, slotId ) )
        {
            return false;
        }
        return !GetInventory().IsInCargo();
    }
CheckParent()
void Clothing::CheckParent () inline private
Definition at line 44 of file headtorch_colorbase.c.
    {
        EntityAI owner = GetHierarchyParent();
        // Spawn a battery in the headtorch if it's attached on a zombie and switch it on
        if (owner  &&  owner.IsZombie())
        {
            GetInventory().CreateAttachment("Battery9V");
            GetCompEM().SwitchOn();
        }
        if (m_Timer)
            m_Timer.Stop();
        m_Timer = null;
    }
References m_Timer.
ConsumeQuantity()
bool Clothing::ConsumeQuantity (float quantity, PlayerBase consumer_player) inline private
Definition at line 128 of file maskbase.c.
    {
        ItemBase filter = ItemBase.Cast(FindAttachmentBySlotName("GasMaskFilter"));
        ItemBase item_to_consume = null;
        if(HasQuantity() && GetQuantity() > 0)
        {
            item_to_consume = this;//this mask itself has quantity(masks with integrated, non-attached filter)
        }
        else if (filter && !filter.IsDamageDestroyed() && filter.GetQuantity() > 0)
        {
            item_to_consume = filter;
        }
        if (item_to_consume)
        {
            item_to_consume.AddQuantity(-quantity);
            OnQuantityConsumed(item_to_consume, consumer_player, quantity);
            return true;
        }
        return false;
    }
References GetQuantity(), and HasQuantity().
CreateHeadtorchLight()
void Clothing::CreateHeadtorchLight () inline private
Definition at line 107 of file headtorch_colorbase.c.
    {
        if (!m_Light)
            m_Light = HeadtorchLight.Cast(  ScriptedLightBase.CreateLight( HeadtorchLight, "0 0 0")  );
        OnLightCreated();
        EntityAI owner = GetHierarchyParent();
        if (owner)
        {
            if (owner.IsPlayer())
            {
                PlayerBase owner_PB = PlayerBase.Cast(owner);
                ItemBase att_item = owner_PB.GetItemOnSlot("Eyewear");
                if (att_item == this)
                {
                    AttachLightOnHead(owner_PB);
                }
                else
                {
                    m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
                }
            }
            else if (owner.IsZombie())
            {
                int slot_id = InventorySlots.GetSlotIdFromString( "Headgear" );
                EntityAI item_EAI = owner.GetInventory().FindAttachment( slot_id );
                ItemBase item_IB = ItemBase.Cast(item_EAI);
                if (item_IB == this)
                {
                    AttachLightOnHead(owner);
                }
            }
        }
        else
        {
            m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
        }
    }
References AttachLightOnHead(), InventorySlots::GetSlotIdFromString(), m_Light, and OnLightCreated().
Referenced by OnWorkStart().
EEItemAttached() [1/2]
override void Clothing::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 43 of file maskbase.c.
    {
        super.EEItemAttached(item, slot_name);
    }
EEItemAttached() [2/2]
override void Clothing::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 3 of file smershvest.c.
    {
        super.EEItemAttached(item,slot_name);
        if (SmershBag.Cast(item))
        {
            ShowSelection("Buttpack");
        }
    }
EEItemDetached()
override void Clothing::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 13 of file smershvest.c.
    {
        super.EEItemDetached(item,slot_name);
        if (SmershBag.Cast(item))
        {
            HideSelection("Buttpack");
        }
    }
GetEffectWidgetTypes() [1/2]
override array< int > Clothing::GetEffectWidgetTypes () inline private
Definition at line 3 of file eyepatch_improvised.c.
    {
        return {EffectWidgetsTypes.EYEPATCH_OCCLUDER};
    }
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
GetEffectWidgetTypes() [2/2]
override array< int > Clothing::GetEffectWidgetTypes () inline private
Definition at line 15 of file maskbase.c.
    {
        return {EffectWidgetsTypes.MASK_OCCLUDER,EffectWidgetsTypes.MASK_BREATH};
    }
GetExternalFilter()
EntityAI Clothing::GetExternalFilter () inline private
Definition at line 49 of file maskbase.c.
    {
        return FindAttachmentBySlotName("GasMaskFilter");
    }
GetFilterQuantity()
float Clothing::GetFilterQuantity () inline private
Definition at line 76 of file maskbase.c.
    {
        ItemBase filter = ItemBase.Cast(GetExternalFilter());
        if(filter)
            return filter.GetQuantity();
        else
            return GetQuantity();
    }
References GetQuantity().
GetFilterQuantity01()
float Clothing::GetFilterQuantity01 () inline private
Definition at line 85 of file maskbase.c.
    {
        if(!HasValidFilter())
        {
            return 0;
        }
        ItemBase filter = ItemBase.Cast(GetExternalFilter());
        float quantity, quantity_max;
        if(filter)
        {
            quantity = filter.GetQuantity();
            quantity_max = filter.GetQuantityMax();
            return Math.InverseLerp(0, quantity_max, quantity);
        }
        else
        {
            quantity = GetQuantity();
            quantity_max = GetQuantityMax();
            return Math.InverseLerp(0, quantity_max, quantity);
        }
    }
References GetQuantity(), GetQuantityMax(), and Math::InverseLerp().
GetFilterQuantityMax()
float Clothing::GetFilterQuantityMax () inline private
Definition at line 65 of file maskbase.c.
    {
        ItemBase filter = ItemBase.Cast(GetExternalFilter());
        if(filter)//mask can have a filter, and filter is attached
            return filter.GetQuantityMax();
        else if(HasQuantity())//filter was not attached, checking if mask has internal filter
            return GetQuantityMax();
        //mask does not have a filter attached nor does it have internal filter, max quantity can't be obtained
        return 0;
    }
References GetQuantityMax(), and HasQuantity().
GetGlassesEffectID() [1/3]
override int Clothing::GetGlassesEffectID () inline private
Definition at line 3 of file aviatorglasses.c.
    {
        return PPERequesterBank.REQ_GLASSESAVIATOR;
    }
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
GetGlassesEffectID() [2/3]
override int Clothing::GetGlassesEffectID () inline private
Definition at line 3 of file designerglasses.c.
    {
        return PPERequesterBank.REQ_GLASSESDESIGNER;
    }
GetGlassesEffectID() [3/3]
override int Clothing::GetGlassesEffectID () inline private
Definition at line 3 of file tacticalgoggles.c.
    {
        return PPERequesterBank.REQ_GLASSESTACTICAL;
    }
GetIncomingLambdaBool()
bool Clothing::GetIncomingLambdaBool () inline private
Definition at line 30 of file mouthrag.c.
    {
        return m_IncomingLambdaChange;
    }
References m_IncomingLambdaChange.
GetLightSourceItem()
override ItemBase Clothing::GetLightSourceItem () inline private
Definition at line 240 of file headtorch_colorbase.c.
    {
        return this;
    }
Referenced by ToggleLightsActionInput::UpdatePossibleActions().
GetVoiceEffect()
override int Clothing::GetVoiceEffect () inline private
Definition at line 20 of file mouthrag.c.
    {
        return VoiceEffectObstruction;
    }
HasIntegratedFilter()
bool Clothing::HasIntegratedFilter () inline private
Definition at line 118 of file maskbase.c.
    {
        return HasQuantity();
    }
References HasQuantity().
HasValidFilter()
bool Clothing::HasValidFilter () inline private
has either external or integrated non-empty non-ruined filter ?
Definition at line 55 of file maskbase.c.
    {
        ItemBase filter = ItemBase.Cast(GetExternalFilter());
        if(filter && !filter.IsRuined() && filter.GetQuantity() > 0 )
            return true;
        else if(GetQuantity() > 0 && !IsRuined())
            return true;
        return false;
    }
References GetQuantity(), and IsRuined().
Headtorch_ColorBase()
void Clothing::Headtorch_ColorBase () inline private
Definition at line 22 of file headtorch_colorbase.c.
    {
        if (!m_Timer)
            m_Timer = new Timer( CALL_CATEGORY_SYSTEM );
        m_Timer.Run( 1 , this, "CheckParent", NULL, false);
    }
References CALL_CATEGORY_SYSTEM, and m_Timer.
IsClothing()
override bool Clothing::IsClothing () inline private
Definition at line 3 of file leathersack_colorbase.c.
    {
        return true;
    }
IsExternalFilterAttached()
bool Clothing::IsExternalFilterAttached () inline private
Definition at line 109 of file maskbase.c.
    {
        if(ItemBase.Cast(FindAttachmentBySlotName("GasMaskFilter")))
        {
            return true;
        }
        return false;
    }
IsGasMask()
override bool Clothing::IsGasMask () inline private
Definition at line 5 of file maskbase.c.
    {
        return true;
    }
Referenced by ManBase::EEItemAttached(), and ManBase::EEItemDetached().
IsLightSource()
override bool Clothing::IsLightSource () inline private
Definition at line 235 of file headtorch_colorbase.c.
    {
        return true;
    }
IsObstructingVoice()
override bool Clothing::IsObstructingVoice () inline private
Definition at line 15 of file mouthrag.c.
    {
        return true;
    }
Referenced by ManBase::CheckForGag().
LargeTentBackPack()
void Clothing::LargeTentBackPack () inline private
Definition at line 5 of file largetentbackpack.c.
    {
        m_RepackingLoopSound  = new EffectSound;
    }
References m_RepackingLoopSound.
MouthRag()
void Clothing::MouthRag () inline private
Definition at line 5 of file mouthrag.c.
    {
        m_IncomingLambdaChange = false;
    }
OnDebugSpawn()
override void Clothing::OnDebugSpawn () inline private
Definition at line 38 of file maskbase.c.
    {
        GetInventory().CreateInInventory( "GasMask_Filter" );
    }
OnLightCreated()
void Clothing::OnLightCreated () inline private
Definition at line 102 of file headtorch_colorbase.c.
    {
        m_Light.SetColorToWhite();
    }
References m_Light, and PointLightBase::SetColorToWhite().
Referenced by CreateHeadtorchLight().
OnQuantityConsumed() [1/2]
void Clothing::OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player) inline private
Definition at line 151 of file maskbase.c.
    {
    }
OnQuantityConsumed() [2/2]
void Clothing::OnQuantityConsumed (notnull ItemBase filter, PlayerBase consumer_player, float quantity) inline private
Definition at line 156 of file maskbase.c.
    {
        float damage = quantity * filter.GetFilterDamageRatio();
        filter.AddHealth("","", -damage);
    }
OnRPC()
override void Clothing::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 15 of file largetentbackpack.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        Param1<bool> p = new Param1<bool>(false);
        if (!ctx.Read(p))
            return;
        bool play = p.param1;
        switch (rpc_type)
        {
            case SoundTypeTent.REPACK:
                if ( play )
                {
                    PlayRepackingLoopSound();
                }
                else
                {
                    StopRepackingLoopSound();
                }
            break;
        }
    }
References PlayRepackingLoopSound(), Serializer::Read(), and StopRepackingLoopSound().
OnWasAttached()
override void Clothing::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 180 of file headtorch_colorbase.c.
    {
        super.OnWasAttached(parent, slot_id);
        PlayerBase player = PlayerBase.Cast(parent);
        if ( player )
        {
            if ( m_Light )
            {
                AttachLightOnHead( player );
            }
            //player.m_PlayerLightManager.AddLightSource(this);
        }
    }
References AttachLightOnHead(), and m_Light.
OnWasDetached()
override void Clothing::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 196 of file headtorch_colorbase.c.
    {
        super.OnWasDetached(parent, slot_id);
        PlayerBase player = PlayerBase.Cast(parent);
        if ( player )
        {
            if ( m_Light )
            {
                m_Light.DetachFromParent();
                m_Light.AttachOnMemoryPoint(this, m_OffHeadLightPoint, m_OffHeadLightTarget);
            }
            //player.m_PlayerLightManager.RemoveLightSource(this);
        }
    }
References m_Light.
OnWork()
override void Clothing::OnWork (float consumed_energy) inline private
Definition at line 80 of file headtorch_colorbase.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            Battery9V battery = Battery9V.Cast( GetCompEM().GetEnergySource() );
            if (battery  &&  m_Light)
            {
                float efficiency = battery.GetEfficiency0To1();
                if ( efficiency < 1 )
                {
                    m_Light.SetIntensity( efficiency, GetCompEM().GetUpdateInterval() );
                }
                else
                {
                    m_Light.SetIntensity( 1, 0 );
                }
            }
        }
    }
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWorkStart()
override void Clothing::OnWorkStart () inline private
Definition at line 61 of file headtorch_colorbase.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            CreateHeadtorchLight();
        }
        if ( IsInherited( Headtorch_Black ) )
        {
            SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS_RED);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR_RED);
        }
        else
        {
            SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR);
        }
    }
References CreateHeadtorchLight(), and GetGame().
OnWorkStop()
override void Clothing::OnWorkStop () inline private
Definition at line 212 of file headtorch_colorbase.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            if (m_Light)
                m_Light.FadeOut();
            m_Light = NULL;
        }
        SetObjectMaterial(GLASS_ID, LIGHT_OFF_GLASS);
        SetObjectMaterial(REFLECTOR_ID, LIGHT_OFF_REFLECTOR);
    }
References GetGame(), and m_Light.
PlayRepackingLoopSound()
void Clothing::PlayRepackingLoopSound () inline private
Definition at line 43 of file largetentbackpack.c.
    {
        if ( !m_RepackingLoopSound || !m_RepackingLoopSound.IsSoundPlaying() )
        {
            m_RepackingLoopSound = SEffectManager.PlaySound( "largetent_deploy_SoundSet", GetPosition(), 0.5, 0.5 );
        }
    }
References GetPosition, m_RepackingLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC().
SetActions() [1/85]
override void Clothing::SetActions () inline private
Definition at line 23 of file armband_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [2/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file balaclava3holes_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [3/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file balaclavamask_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [4/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file baseballcap_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [5/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file bdujacket.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [6/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file bdupants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [7/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file beaniehat_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [8/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file blouse_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [9/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file bomberjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [10/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file booniehat_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [11/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file breeches_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [12/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file canvaspants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [13/85]
override void Clothing::SetActions () inline private
Definition at line 17 of file canvaspants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [14/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file cargopants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [15/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file chernarussportshirt.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [16/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file denimjacket.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [17/85]
override void Clothing::SetActions () inline private
Definition at line 8 of file eyepatch_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [18/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file facecover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [19/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file feetcover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [20/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file firefighterjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [21/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file firefighterspants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [22/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file flatcap_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [23/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file gorkaejacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [24/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file gorkapants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [25/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file handscover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [26/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file headcover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [27/85]
override void Clothing::SetActions () inline private
Definition at line 226 of file headtorch_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnWhileInHands);
        AddAction(ActionTurnOffWhileInHands);
        AddAction(ActionTurnOnHeadtorch);
        AddAction(ActionTurnOffHeadtorch);
    }
References AddAction().
SetActions() [28/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file hikingjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [29/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file hoodie_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [30/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file hunterpants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [31/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file huntingjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [32/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file jeans_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [33/85]
override void Clothing::SetActions () inline private
Definition at line 18 of file jeans_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [34/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file jumpsuitjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [35/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file jumpsuitpants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [36/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file labcoat.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [37/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file legcover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [38/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file m65jacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [39/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file mansuit_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [40/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file medicalscrubshat_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [41/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file medicalscrubspants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [42/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file medicalscrubsshirt_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [43/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file minidress_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [44/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file nbcjacketbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [45/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file nbcpantsbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [46/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file nursedress_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [47/85]
override void Clothing::SetActions () inline private
Definition at line 17 of file nvgheadstrap.c.
    {
        super.SetActions();
        AddAction(ActionToggleNVG);
    }
References AddAction().
SetActions() [48/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file paramedicjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [49/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file paramedicpants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [50/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file pilotkacap.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [51/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file policejacket.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [52/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file policejacketorel.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [53/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file policepants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [54/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file policepantsorel.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [55/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file prisonercap.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [56/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file prisonuniformjacket.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [57/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file prisonuniformpants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [58/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file quiltedjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [59/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file radarcap_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [60/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file ridersjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [61/85]
override void Clothing::SetActions () inline private
Definition at line 16 of file santasbeard.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [62/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file santashat.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [63/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file shirt_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [64/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file skirt_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [65/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file slackspants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [66/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file surgicalmask.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [67/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file sweater_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [68/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file tacticalshirt_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [69/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file tankerhelmet.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [70/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file telnyashkashirt.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [71/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file torsocover_improvised.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [72/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file tracksuitjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [73/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file tracksuitpants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [74/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file tshirt_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [75/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file ttskojacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [76/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file ttskopants.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [77/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file ushanka_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [78/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file usmcjacket_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [79/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file usmcpants_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [80/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file witchhat.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [81/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file witchhood.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [82/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file womansuit_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [83/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file woolcoat_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [84/85]
override void Clothing::SetActions () inline private
Definition at line 3 of file zmijovkacap_colorbase.c.
    {
        super.SetActions();
        AddAction(ActionWringClothes);
    }
References AddAction().
SetActions() [85/85]
override void Clothing::SetActions () inline private
Definition at line 57 of file largetentbackpack.c.
    {
        super.SetActions();
        //AddAction(ActionRepackTent);
    }
SetIncomingLambaBool()
void Clothing::SetIncomingLambaBool (bool state) inline private
Definition at line 25 of file mouthrag.c.
    {
        m_IncomingLambdaChange = state;
    }
StopRepackingLoopSound()
void Clothing::StopRepackingLoopSound () inline private
Definition at line 51 of file largetentbackpack.c.
    {
        m_RepackingLoopSound.SetSoundFadeOut(0.5);
        m_RepackingLoopSound.SoundStop();
    }
References m_RepackingLoopSound.
Referenced by OnRPC().
SwitchItemSelectionTextureEx()
override void Clothing::SwitchItemSelectionTextureEx (EItemManipulationContext context, Param par = null) inline private
Definition at line 29 of file armband_colorbase.c.
    {
        super.SwitchItemSelectionTextureEx(context, par);
        if (context == EItemManipulationContext.ATTACHING || context == EItemManipulationContext.UPDATE)
        {
            Param1<PlayerBase> data = Param1<PlayerBase>.Cast(par);
            if (!data)
            {
                return;
            }
            PlayerBase player = data.param1;
            int selection_idx = -1;
            string texture;
            array<string> show_selections = new array<string>;
            array<string> hide_selections = new array<string>;
            //has top
            if (player.FindAttachmentBySlotName("Body"))
            {
                show_selections.Insert("camoMale_big_a");
                show_selections.Insert("camoMale_big_b");
                show_selections.Insert("camoFemale_big_a");
                show_selections.Insert("camoFemale_big_b");
                hide_selections.Insert("camoMale_small_a");
                hide_selections.Insert("camoMale_small_b");
                hide_selections.Insert("camoFemale_small_a");
                hide_selections.Insert("camoFemale_small_b");
            }
            //has no top
            else
            {
                hide_selections.Insert("camoMale_big_a");
                hide_selections.Insert("camoMale_big_b");
                hide_selections.Insert("camoFemale_big_a");
                hide_selections.Insert("camoFemale_big_b");
                show_selections.Insert("camoMale_small_a");
                show_selections.Insert("camoMale_small_b");
                show_selections.Insert("camoFemale_small_a");
                show_selections.Insert("camoFemale_small_b");
            }
            int i;
            for (i = 0; i < show_selections.Count(); i++)
            {
                selection_idx = GetHiddenSelectionIndex(show_selections[i]);
                texture = GetHiddenSelectionsData().GetHiddenSelectionsTextures()[selection_idx];
                SetObjectTexture( selection_idx, texture );
            }
            for (i = 0; i < hide_selections.Count(); i++)
            {
                selection_idx = GetHiddenSelectionIndex(hide_selections[i]);
                SetObjectTexture( selection_idx, "" );
            }
        }
    }
Member Data Documentation
GLASS_ID
int Clothing::GLASS_ID = 5 static private
Definition at line 6 of file headtorch_colorbase.c.
LIGHT_OFF_GLASS
string Clothing::LIGHT_OFF_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass.rvmat" static private
Definition at line 8 of file headtorch_colorbase.c.
LIGHT_OFF_REFLECTOR
string Clothing::LIGHT_OFF_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch.rvmat" static private
Definition at line 9 of file headtorch_colorbase.c.
LIGHT_ON_GLASS
string Clothing::LIGHT_ON_GLASS = "dz\\characters\\headgear\\data\\HeadTorchGlass_on.rvmat" static private
Definition at line 10 of file headtorch_colorbase.c.
LIGHT_ON_GLASS_RED
string Clothing::LIGHT_ON_GLASS_RED = "dz\\characters\\headgear\\data\\HeadTorchGlass_on_red.rvmat" static private
Definition at line 11 of file headtorch_colorbase.c.
LIGHT_ON_REFLECTOR
string Clothing::LIGHT_ON_REFLECTOR = "dz\\characters\\headgear\\data\\HeadTorch_ON.rvmat" static private
Definition at line 12 of file headtorch_colorbase.c.
LIGHT_ON_REFLECTOR_RED
string Clothing::LIGHT_ON_REFLECTOR_RED = "dz\\characters\\headgear\\data\\HeadTorch_ON_red.rvmat" static private
Definition at line 13 of file headtorch_colorbase.c.
m_IncomingLambdaChange
bool Clothing::m_IncomingLambdaChange private
Definition at line 3 of file mouthrag.c.
Referenced by CanDetachAttachment(), and GetIncomingLambdaBool().
m_Light
HeadtorchLight Clothing::m_Light private
Definition at line 3 of file headtorch_colorbase.c.
m_LowFilterEventTime
float Clothing::m_LowFilterEventTime private
Definition at line 3 of file maskbase.c.
m_OffHeadLightPoint
string Clothing::m_OffHeadLightPoint = "beamStart" static private
Definition at line 17 of file headtorch_colorbase.c.
m_OffHeadLightTarget
string Clothing::m_OffHeadLightTarget = "beamEnd" static private
Definition at line 18 of file headtorch_colorbase.c.
m_OnHeadLocalOri
vector Clothing::m_OnHeadLocalOri = Vector(0,90,0) static private
Definition at line 16 of file headtorch_colorbase.c.
m_OnHeadLocalPos
vector Clothing::m_OnHeadLocalPos = Vector(0.12,0.15,0) static private
Definition at line 15 of file headtorch_colorbase.c.
m_RepackingLoopSound
ref protected EffectSound Clothing::m_RepackingLoopSound private
Definition at line 3 of file largetentbackpack.c.
m_Timer
ref Timer Clothing::m_Timer private
Definition at line 20 of file headtorch_colorbase.c.
REFLECTOR_ID
int Clothing::REFLECTOR_ID = 4 static private
Definition at line 5 of file headtorch_colorbase.c.