DayzKode: HumanCommandActionCallback Class Reference
HumanCommandActionCallback Class Reference
Private Member Functions
bool CancelCondition ()
bool CancelCondition ()
void Init (float run_time, PlayerBase player)
override bool IsSymptomCallback ()
override void OnAnimationEvent (int pEventID)
override void OnFinish (bool pCanceled)
override void OnFinish (bool pCanceled)
override void OnStateChange (int pOldState, int pCurrentState)
void PluginDayzPlayerActionCallback ()
void ~PluginDayzPlayerActionCallback ()
Private Attributes
float m_fTimeStart
TextWidget m_pAnimEventWidget
PlayerBase m_Player
TextWidget m_pStateWidget
float m_RunTime
float m_StartingTime
Detailed Description
Definition at line 1 of file statecb.c.
Constructor & Destructor Documentation
~PluginDayzPlayerActionCallback()
void HumanCommandActionCallback::~PluginDayzPlayerActionCallback () inline private
Definition at line 71 of file plugindayzplayerdebug.c.
    {
        Print("Action callback deleted");
    }
References Print().
Member Function Documentation
CancelCondition() [1/2]
bool HumanCommandActionCallback::CancelCondition () inline private
Definition at line 30 of file statecb.c.
    {
        if(m_RunTime > 0 && (GetGame().GetTime() > m_StartingTime + m_RunTime))
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetGame(), and GetTime().
CancelCondition() [2/2]
bool HumanCommandActionCallback::CancelCondition () inline private
Definition at line 89 of file plugindayzplayerdebug.c.
    {
        // Print("Action cancel condition");
        return DefaultCancelCondition();
    }
References DefaultCancelCondition().
Init()
void HumanCommandActionCallback::Init (float run_time, PlayerBase player) inline private
Definition at line 17 of file statecb.c.
    {
        EnableCancelCondition(true);
        m_RunTime = run_time * 1000;
        m_StartingTime = GetGame().GetTime();
        m_Player = player;
        if( m_Player && m_Player.GetSymptomManager())
        {
            m_Player.GetSymptomManager().OnAnimationStarted();
        }
    }
References EnableCancelCondition(), GetGame(), CGame::GetTime(), and m_Player.
IsSymptomCallback()
override bool HumanCommandActionCallback::IsSymptomCallback () inline private
Definition at line 42 of file statecb.c.
    {
        return true;
    }
OnAnimationEvent()
override void HumanCommandActionCallback::OnAnimationEvent (int pEventID) inline private
Definition at line 95 of file plugindayzplayerdebug.c.
    {
        // only one event id is registered - 1 so nothing else can be delivered
        string a = "ActionExec event at: ";
        float  tFromSt = GetWorldTime() - m_fTimeStart;
        a += tFromSt.ToString();
        m_pAnimEventWidget.SetText(a);
    }
References GetWorldTime(), m_fTimeStart, and float::ToString().
OnFinish() [1/2]
override void HumanCommandActionCallback::OnFinish (bool pCanceled) inline private
Definition at line 8 of file statecb.c.
    {
        if( m_Player && m_Player.GetSymptomManager())
        {
            m_Player.GetSymptomManager().OnAnimationFinished();
        }
    }
References m_Player.
OnFinish() [2/2]
override void HumanCommandActionCallback::OnFinish (bool pCanceled) inline private
Definition at line 76 of file plugindayzplayerdebug.c.
    {
        if (pCanceled)
        {
            m_pStateWidget.SetText("Result: canceled");
        }
        else
        {
            m_pStateWidget.SetText("Result: ended");
        }
    }
OnStateChange()
override void HumanCommandActionCallback::OnStateChange (int pOldState, int pCurrentState) inline private
Definition at line 105 of file plugindayzplayerdebug.c.
    {
        string oldState = GetStateString(pOldState);
        string newState = GetStateString(pCurrentState);
        m_pStateWidget.SetText(oldState + "->" + newState);
    };
References GetStateString().
PluginDayzPlayerActionCallback()
void HumanCommandActionCallback::PluginDayzPlayerActionCallback () inline private
Definition at line 61 of file plugindayzplayerdebug.c.
    {
        Print("Action callback created");
        EnableCancelCondition(true);
        RegisterAnimationEvent("ActionExec", 1);    // really weird id
        EnableStateChangeCallback();                // enable this to get OnStateChange callbacks
        m_fTimeStart = GetWorldTime();
    }
Member Data Documentation
m_fTimeStart
float HumanCommandActionCallback::m_fTimeStart private
Definition at line 116 of file plugindayzplayerdebug.c.
Referenced by OnAnimationEvent().
m_pAnimEventWidget
TextWidget HumanCommandActionCallback::m_pAnimEventWidget private
Definition at line 118 of file plugindayzplayerdebug.c.
m_Player
PlayerBase HumanCommandActionCallback::m_Player private
Definition at line 6 of file statecb.c.
m_pStateWidget
TextWidget HumanCommandActionCallback::m_pStateWidget private
Definition at line 117 of file plugindayzplayerdebug.c.
m_RunTime
float HumanCommandActionCallback::m_RunTime private
Definition at line 4 of file statecb.c.
m_StartingTime
float HumanCommandActionCallback::m_StartingTime private
Definition at line 5 of file statecb.c.