DayzKode: EmoteBase Class Reference
EmoteBase Class Reference
Private Member Functions
bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
override bool DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody)
void EmoteCampfireSit ()
void EmoteClap ()
void EmoteCome ()
bool EmoteCondition (int stancemask)
override bool EmoteCondition (int stancemask)
override bool EmoteCondition (int stancemask)
void EmoteDabbing ()
bool EmoteFBStanceCheck (int stancemask)
Checks for valid stance mask.
void EmoteGreeting ()
void EmoteHeart ()
void EmoteListening ()
void EmoteLookAtMe ()
void EmoteLyingDown ()
void EmoteMove ()
void EmotePoint ()
void EmoteRPSRock ()
void EmoteRPSScisors ()
void EmoteSalute ()
void EmoteShake ()
void EmoteSitB ()
bool EmoteStartOverride (typename callbacktype, int id, int mask, bool fullbody)
void EmoteSuicide ()
void EmoteThroat ()
void EmoteThumb ()
void EmoteWatching ()
int GetAdditiveCallbackUID ()
int GetFullbodyCallbackUID ()
bool GetHideItemInHands ()
int GetID ()
string GetInputActionName ()
PlayerBase GetOwnerPlayer ()
int GetStanceMaskAdditive ()
int GetStanceMaskFullbody ()
void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
override void OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody)
void SetOwnerPlayer (PlayerBase player)
Private Attributes
protected int m_AdditiveCallbackUID = 0
protected int m_FullbodyCallbackUID = 0
protected bool m_HideItemInHands = false
protected int m_ID = -1
protected string m_InputActionName = ""
protected PlayerBase m_Player
protected int m_StanceMaskAdditive = 0
protected int m_StanceMaskFullbody = 0
protected const float WATER_DEPTH = 0.15
Detailed Description
Definition at line 1 of file emotebase.c.
Member Function Documentation
DetermineOverride() [1/2]
bool EmoteBase::DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline private
Definition at line 34 of file emotebase.c.
    {
        return false;
    }
Referenced by DetermineEmoteData().
DetermineOverride() [2/2]
override bool EmoteBase::DetermineOverride (out int callback_ID, out int stancemask, out bool is_fullbody) inline private
Definition at line 583 of file emoteclasses.c.
    {
        is_fullbody = true;
        callback_ID = -1;
        stancemask = 0;
        string suicideStr;
        ItemBase weapon;
        weapon = m_Player.GetItemInHands();
        if (weapon)
        {
            if (weapon.ConfigIsExisting("suicideAnim"))
            {
                suicideStr = weapon.ConfigGetString("suicideAnim");
            }
            if (weapon.IsKindOf("Pistol_Base"))
            {
                callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_PISTOL;
                stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
                //m_Player.OverrideShootFromCamera(false);
            }
            else if (Weapon_Base.Cast(weapon)) //long firearms
            {
                callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_RIFLE;
                stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
                //m_Player.OverrideShootFromCamera(false);
            }
            else
            {
                switch (suicideStr)
                {
                    case "onehanded":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_1HD;
                        stancemask = DayZPlayerConstants.STANCEMASK_CROUCH;
                    break;
                    case "fireaxe":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_FIREAXE;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "pitchfork":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_PITCHFORK;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "sword":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SWORD;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "spear":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SPEAR;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "woodaxe":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_WOODAXE;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "sickle":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_SICKLE;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                    case "hoe":
                        callback_ID = DayZPlayerConstants.CMD_SUICIDEFB_HOE;
                        stancemask = DayZPlayerConstants.STANCEMASK_ERECT;
                    break;
                }
            }
        }
        if (callback_ID > -1)
        {
            return true;
        }
        return false;
    }
References m_Player.
EmoteCampfireSit()
void EmoteBase::EmoteCampfireSit () inline private
Definition at line 432 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_CAMPFIRE;
        m_InputActionName = "EmoteCampfireSit";
        m_StanceMaskAdditive = 0;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_AdditiveCallbackUID = 0;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_CAMPFIRE;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_CAMPFIRE, and m_ID.
EmoteClap()
void EmoteBase::EmoteClap () inline private
Definition at line 245 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_CLAP;
        m_InputActionName = "EmoteClap";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = 0;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_CLAP;
        m_FullbodyCallbackUID = 0;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_CLAP, and m_ID.
EmoteCome()
void EmoteBase::EmoteCome () inline private
Definition at line 385 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_COME;
        m_InputActionName = "EmoteCome";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_COME;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_COME;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_COME, and m_ID.
EmoteCondition() [1/3]
bool EmoteBase::EmoteCondition (int stancemask) inline private
Definition at line 12 of file emotebase.c.
    {
        return true;
    }
Referenced by CanPlayEmote().
EmoteCondition() [2/3]
override bool EmoteBase::EmoteCondition (int stancemask) inline private
Definition at line 72 of file emoteclasses.c.
    {
        vector water_info = HumanCommandSwim.WaterLevelCheck( m_Player, m_Player.GetPosition() - (m_Player.GetDirection() * 0.9) );
        if ( water_info[0] < WATER_DEPTH ) //is player able to lay down without "drowning"?
            return true;
        return false;
    }
References HumanCommandSwim(), m_Player, and WATER_DEPTH.
EmoteCondition() [3/3]
override bool EmoteBase::EmoteCondition (int stancemask) inline private
Definition at line 663 of file emoteclasses.c.
    {
        Weapon_Base weapon;
        weapon = Weapon_Base.Cast(m_Player.GetItemInHands());
        if (weapon)
            return weapon.ConfigGetBool("isSuicideWeapon");
        return true;
    }
References m_Player.
EmoteDabbing()
void EmoteBase::EmoteDabbing () inline private
Definition at line 217 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_DABBING;
        //m_InputActionName = "EmoteDabbing";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = 0;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_DABBING;
        m_FullbodyCallbackUID = 0;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_DABBING, and m_ID.
EmoteFBStanceCheck()
bool EmoteBase::EmoteFBStanceCheck (int stancemask) inline private
Checks for valid stance mask.
Definition at line 18 of file emotebase.c.
    {
        int stanceIdx = DayZPlayerUtils.ConvertStanceMaskToStanceIdx(stancemask);
        if (!m_Player)
        {
            ErrorEx("No player for 'PlayerCanChangeStance'");
            return false;
        }
        if (stanceIdx != -1 && !DayZPlayerUtils.PlayerCanChangeStance(m_Player, stanceIdx))
            return false;
        return true;
    }
References DayZPlayerUtils::ConvertStanceMaskToStanceIdx(), ErrorEx, m_Player, and DayZPlayerUtils::PlayerCanChangeStance().
Referenced by DetermineEmoteData().
EmoteGreeting()
void EmoteBase::EmoteGreeting () inline private
Definition at line 4 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_GREETING;
        m_InputActionName = "EmoteGreeting";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_GREETING;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_GREETING;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_GREETING, and m_ID.
EmoteHeart()
void EmoteBase::EmoteHeart () inline private
Definition at line 32 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_HEART;
        m_InputActionName = "EmoteHeart";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_HEART;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_HEART;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_HEART, and m_ID.
EmoteListening()
void EmoteBase::EmoteListening () inline private
Definition at line 301 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_LISTENING;
        m_InputActionName = "EmoteListening";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_LISTENING;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LISTENING;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_LISTENING, and m_ID.
EmoteLookAtMe()
void EmoteBase::EmoteLookAtMe () inline private
Definition at line 329 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_LOOKATME;
        m_InputActionName = "EmoteLookAtMe";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_LOOKATME;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LOOKATME;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_LOOKATME, and m_ID.
EmoteLyingDown()
void EmoteBase::EmoteLyingDown () inline private
Definition at line 61 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_LYINGDOWN;
        m_InputActionName = "EmoteLyingDown";
        m_StanceMaskAdditive = 0;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_AdditiveCallbackUID = 0;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_LYINGDOWN;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_LYINGDOWN, and m_ID.
EmoteMove()
void EmoteBase::EmoteMove () inline private
Definition at line 357 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_MOVE;
        m_InputActionName = "EmoteMove";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_MOVE;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_MOVE;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_MOVE, and m_ID.
EmotePoint()
void EmoteBase::EmotePoint () inline private
Definition at line 97 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_POINT;
        m_InputActionName = "EmotePoint";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_POINT;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_POINT;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_POINT, and m_ID.
EmoteRPSRock()
void EmoteBase::EmoteRPSRock () inline private
Definition at line 488 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_RPS_R;
        m_InputActionName = "EmoteRPSRock";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = 0;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_RPS;
        m_FullbodyCallbackUID = 0;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_RPS_R, and m_ID.
EmoteRPSScisors()
void EmoteBase::EmoteRPSScisors () inline private
Definition at line 516 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_RPS_S;
        m_InputActionName = "EmoteRPSScisors";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = 0;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_RPS;
        m_FullbodyCallbackUID = 0;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_RPS_S, and m_ID.
EmoteSalute()
void EmoteBase::EmoteSalute () inline private
Definition at line 189 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_SALUTE;
        m_InputActionName = "EmoteSalute";
        m_StanceMaskAdditive = 0;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_ERECT;
        m_AdditiveCallbackUID = 0;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SALUTE;
        m_HideItemInHands = true;
    }
References EmoteConstants::ID_EMOTE_SALUTE, and m_ID.
EmoteShake()
void EmoteBase::EmoteShake () inline private
Definition at line 544 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_SHAKE;
        m_InputActionName = "EmoteShake";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_SHAKEHEAD;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SHAKEHEAD;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_SHAKE, and m_ID.
EmoteSitB()
void EmoteBase::EmoteSitB () inline private
Definition at line 460 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_SITB;
        m_InputActionName = "EmoteSitB";
        m_StanceMaskAdditive = 0;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_AdditiveCallbackUID = 0;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_SITB;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_SITB, and m_ID.
EmoteStartOverride()
bool EmoteBase::EmoteStartOverride (typename callbacktype , int id, int mask, bool fullbody) inline private
Definition at line 43 of file emotebase.c.
    {
        return false;
    }
Referenced by PlayEmote().
EmoteSuicide()
void EmoteBase::EmoteSuicide () inline private
Definition at line 572 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_SUICIDE;
        m_InputActionName = "EmoteSuicide";
        m_StanceMaskAdditive = 0;
        m_StanceMaskFullbody = 0;
        m_AdditiveCallbackUID = 0;
        m_FullbodyCallbackUID = 0;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_SUICIDE, and m_ID.
EmoteThroat()
void EmoteBase::EmoteThroat () inline private
Definition at line 153 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_THROAT;
        m_InputActionName = "EmoteThroat";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_THROAT;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_THROAT;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_THROAT, and m_ID.
EmoteThumb()
void EmoteBase::EmoteThumb () inline private
Definition at line 125 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_THUMB;
        m_InputActionName = "EmoteThumb";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_THUMB;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_THUMB;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_THUMB, and m_ID.
EmoteWatching()
void EmoteBase::EmoteWatching () inline private
Definition at line 273 of file emoteclasses.c.
    {
        m_ID = EmoteConstants.ID_EMOTE_WATCHING;
        m_InputActionName = "EmoteWatching";
        m_StanceMaskAdditive = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_StanceMaskFullbody = DayZPlayerConstants.STANCEMASK_PRONE;
        m_AdditiveCallbackUID = DayZPlayerConstants.CMD_GESTUREMOD_WATCHING;
        m_FullbodyCallbackUID = DayZPlayerConstants.CMD_GESTUREFB_WATCHING;
        m_HideItemInHands = false;
    }
References EmoteConstants::ID_EMOTE_WATCHING, and m_ID.
GetAdditiveCallbackUID()
int EmoteBase::GetAdditiveCallbackUID () inline private
Definition at line 81 of file emotebase.c.
    {
        return m_AdditiveCallbackUID;
    }
References m_AdditiveCallbackUID.
Referenced by DetermineEmoteData().
GetFullbodyCallbackUID()
int EmoteBase::GetFullbodyCallbackUID () inline private
Definition at line 86 of file emotebase.c.
    {
        return m_FullbodyCallbackUID;
    }
References m_FullbodyCallbackUID.
Referenced by DetermineEmoteData().
GetHideItemInHands()
bool EmoteBase::GetHideItemInHands () inline private
Definition at line 91 of file emotebase.c.
    {
        return m_HideItemInHands;
    }
References m_HideItemInHands.
Referenced by PlayEmote().
GetID()
int EmoteBase::GetID () inline private
Definition at line 61 of file emotebase.c.
    {
        return m_ID;
    }
References m_ID.
GetInputActionName()
string EmoteBase::GetInputActionName () inline private
Definition at line 66 of file emotebase.c.
    {
        return m_InputActionName;
    }
References m_InputActionName.
Referenced by GetBoundButtonText().
GetOwnerPlayer()
PlayerBase EmoteBase::GetOwnerPlayer () inline private
Definition at line 56 of file emotebase.c.
    {
        return m_Player;
    }
References m_Player.
GetStanceMaskAdditive()
int EmoteBase::GetStanceMaskAdditive () inline private
Definition at line 71 of file emotebase.c.
    {
        return m_StanceMaskAdditive;
    }
References m_StanceMaskAdditive.
Referenced by DetermineEmoteData().
GetStanceMaskFullbody()
int EmoteBase::GetStanceMaskFullbody () inline private
Definition at line 76 of file emotebase.c.
    {
        return m_StanceMaskFullbody;
    }
References m_StanceMaskFullbody.
Referenced by DetermineEmoteData().
OnBeforeStandardCallbackCreated() [1/2]
void EmoteBase::OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) inline private
Definition at line 39 of file emotebase.c.
    {
    }
Referenced by PlayEmote().
OnBeforeStandardCallbackCreated() [2/2]
override void EmoteBase::OnBeforeStandardCallbackCreated (int callback_ID, int stancemask, bool is_fullbody) inline private
Definition at line 674 of file emoteclasses.c.
    {
        if (callback_ID > -1)
        {
            if (callback_ID == DayZPlayerConstants.CMD_SUICIDEFB_PISTOL || callback_ID == DayZPlayerConstants.CMD_SUICIDEFB_RIFLE)
                m_Player.OverrideShootFromCamera(false);
        }
        else if (callback_ID < 0)
        {
            m_Player.SetInventorySoftLock(false);
        }
    }
References m_Player.
SetOwnerPlayer()
void EmoteBase::SetOwnerPlayer (PlayerBase player) inline private
Definition at line 48 of file emotebase.c.
    {
        m_Player = player;
    }
References m_Player.
Member Data Documentation
m_AdditiveCallbackUID
protected int EmoteBase::m_AdditiveCallbackUID = 0 private
Definition at line 8 of file emotebase.c.
Referenced by GetAdditiveCallbackUID().
m_FullbodyCallbackUID
protected int EmoteBase::m_FullbodyCallbackUID = 0 private
Definition at line 9 of file emotebase.c.
Referenced by GetFullbodyCallbackUID().
m_HideItemInHands
protected bool EmoteBase::m_HideItemInHands = false private
Definition at line 10 of file emotebase.c.
Referenced by GetHideItemInHands().
m_ID
protected int EmoteBase::m_ID = -1 private
Definition at line 4 of file emotebase.c.
Referenced by GetID().
m_InputActionName
protected string EmoteBase::m_InputActionName = "" private
Definition at line 5 of file emotebase.c.
Referenced by GetInputActionName().
m_Player
protected PlayerBase EmoteBase::m_Player private
Definition at line 3 of file emotebase.c.
Referenced by EmoteFBStanceCheck(), GetOwnerPlayer(), and SetOwnerPlayer().
m_StanceMaskAdditive
protected int EmoteBase::m_StanceMaskAdditive = 0 private
Definition at line 6 of file emotebase.c.
Referenced by GetStanceMaskAdditive().
m_StanceMaskFullbody
protected int EmoteBase::m_StanceMaskFullbody = 0 private
Definition at line 7 of file emotebase.c.
Referenced by GetStanceMaskFullbody().
WATER_DEPTH
protected const float EmoteBase::WATER_DEPTH = 0.15 private
Definition at line 60 of file emoteclasses.c.