DayzKode: PluginManager Class Reference
PluginManager Class Reference
Private Member Functions
PluginBase GetPluginByType (typename plugin_type)
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
void Init ()
void MainOnUpdate (float delta_time)
void PluginManager ()
void PluginsInit ()
protected void RegisterPlugin (string plugin_class_name, bool reg_on_client, bool reg_on_server, bool reg_on_release=true)
Register new PluginBase to PluginManager for storing and handling plugin.
protected void RegisterPluginDebug (string plugin_class_name, bool reg_on_client, bool reg_on_server)
Register new PluginBase to PluginManager for storing and handling plugin.
protected void RegisterPluginDiag (string plugin_class_name, bool reg_on_client, bool reg_on_server)
protected bool UnregisterPlugin (string plugin_class_name)
void ~PluginManager ()
Private Attributes
private ref array< typename > m_PluginRegister
private ref map< typename, ref PluginBase > m_PluginsPtrs
Detailed Description
Definition at line 1 of file pluginmanager.c.
Constructor & Destructor Documentation
PluginManager()
void PluginManager::PluginManager () inline private
Definition at line 9 of file pluginmanager.c.
    {
        m_PluginRegister    = new array<typename>;
        m_PluginsPtrs       = new map<typename, ref PluginBase>;
    }
References m_PluginRegister, and m_PluginsPtrs.
~PluginManager()
void PluginManager::~PluginManager () inline private
Definition at line 18 of file pluginmanager.c.
    {
        int i;
        PluginBase plugin;
        for ( i = 0; i < m_PluginsPtrs.Count(); ++i)
        {
            plugin = m_PluginsPtrs.GetElement(i);
            if ( plugin != NULL )
            {
                plugin.OnDestroy();
                delete plugin;
            }
        }
        GetGame().GetUpdateQueue(CALL_CATEGORY_GAMEPLAY).Remove(this.MainOnUpdate);
    }
References CALL_CATEGORY_GAMEPLAY, GetGame(), CGame::GetUpdateQueue(), m_PluginsPtrs, MainOnUpdate(), PluginBase::OnDestroy(), and ScriptInvoker::Remove().
Member Function Documentation
GetPluginByType()
PluginBase PluginManager::GetPluginByType (typename plugin_type) inline private
Returns registred plugin by class type, better is to use global funtion GetPlugin(typename plugin_type)
Parameters
module_tpye typename class type of plugin
Returns
PluginBase
PluginRepairing plugin = GetPluginManager().GetPluginByType(PluginRepairing);
Definition at line 155 of file pluginmanager.c.
    {
        if ( m_PluginsPtrs.Contains( plugin_type ) )
        {
            return m_PluginsPtrs.Get( plugin_type );
        }
        return null;
    }
References m_PluginsPtrs.
Referenced by GetPlugin(), and PluginsInit().
Init()
void PluginManager::Init () inline private
Definition at line 39 of file pluginmanager.c.
    {
        //----------------------------------------------------------------------
        // Register modules
        //----------------------------------------------------------------------
        //              Module Class Name                               Client  Server
        //----------------------------------------------------------------------
        RegisterPlugin( "PluginHorticulture",                           true,   true );
        RegisterPlugin( "PluginRepairing",                              true,   true );
        RegisterPlugin( "PluginPlayerStatus",                           true,   true );
        RegisterPlugin( "PluginMessageManager",                         true,   true );
        RegisterPlugin( "PluginLifespan",                               true,   true );
        RegisterPlugin( "PluginVariables",                              true,   true );
        RegisterPlugin( "PluginObjectsInteractionManager",              false,  true );
        RegisterPlugin( "PluginRecipesManager",                         true,   true );
        RegisterPlugin( "PluginTransmissionAgents",                     true,   true );
        RegisterPlugin( "PluginAdditionalInfo",                         true,   true ); //TODO clean up after Gamescom
        RegisterPlugin( "PluginConfigEmotesProfile",                    true,   true );
        RegisterPlugin( "PluginPresenceNotifier",                       true,   false );
        RegisterPlugin( "PluginAdminLog",                               false,  true );
        // Developer + Diag
        RegisterPluginDiag( "PluginKeyBinding",                         true,   false );
        RegisterPluginDiag( "PluginDeveloper",                          true,   true );
        // Only In Debug / Internal
        RegisterPluginDebug( "PluginConfigViewer",                      true,   true );
        RegisterPluginDebug( "PluginLocalEnscriptHistory",              true,   true );
        RegisterPluginDebug( "PluginLocalEnscriptHistoryServer",        true,   true );
        RegisterPluginDebug( "PluginDeveloperSync",                     true,   true );
        RegisterPluginDebug( "PluginSceneManager",                      true,   true );
        RegisterPluginDebug( "PluginConfigScene",                       true,   true );
        RegisterPluginDebug( "PluginMissionConfig",                     true,   true );
        RegisterPluginDebug( "PluginConfigEmotesProfile",               true,   true );
        RegisterPluginDebug( "PluginConfigDebugProfile",                true,   true );
        RegisterPluginDebug( "PluginConfigDebugProfileFixed",           true,   true );
        RegisterPluginDebug( "PluginItemDiagnostic",                    true,   true );
        RegisterPluginDebug( "PluginDayzPlayerDebug",                   true,   true );
        RegisterPluginDebug( "PluginDayZInfectedDebug",                 true,   true );
        RegisterPluginDebug( "PluginDiagMenu",                          true,   true );
        RegisterPluginDebug( "PluginDayZCreatureAIDebug",               true,   true );
        RegisterPluginDebug( "PluginDoorRuler",                         true,   false );
        RegisterPluginDebug( "PluginCharPlacement",                     true,   false );
        RegisterPluginDebug( "PluginPermanentCrossHair",                true,   false );
        RegisterPluginDebug( "PluginRemotePlayerDebugClient",           true,   false );
        RegisterPluginDebug( "PluginRemotePlayerDebugServer",           false,  true );
        RegisterPluginDebug( "PluginDrawCheckerboard",                  true,   false );
        //RegisterPluginDebug( "PluginSoundDebug",                      false,  false );
        RegisterPluginDebug( "PluginCameraTools",                       true,   true );
        RegisterPluginDebug( "PluginNutritionDumper",                   true,   false );
        RegisterPluginDebug( "PluginUniversalTemperatureSourceClient",  true,   false );
        RegisterPluginDebug( "PluginUniversalTemperatureSourceServer",  false,  true );
        GetGame().GetUpdateQueue(CALL_CATEGORY_GAMEPLAY).Insert(this.MainOnUpdate);
    }
References CALL_CATEGORY_GAMEPLAY, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), MainOnUpdate(), RegisterPlugin(), RegisterPluginDebug(), and RegisterPluginDiag().
Referenced by PluginManagerInit().
MainOnUpdate()
void PluginManager::MainOnUpdate (float delta_time) inline private
Definition at line 132 of file pluginmanager.c.
    {
        for ( int i = 0; i < m_PluginsPtrs.Count(); ++i)
        {
            PluginBase plugin = m_PluginsPtrs.GetElement(i);
            if ( plugin != NULL )
            {
                plugin.OnUpdate(delta_time);
            }
        }
    }
References m_PluginsPtrs, and PluginBase::OnUpdate().
Referenced by Init(), and ~PluginManager().
PluginsInit()
void PluginManager::PluginsInit () inline private
Definition at line 100 of file pluginmanager.c.
    {
        int i = 0;
        int regCount = m_PluginRegister.Count();
        for ( i = 0; i < regCount; ++i)
        {
            typename plugin_type = m_PluginRegister.Get(i);
            PluginBase module_exist = GetPluginByType( plugin_type );
            if ( module_exist )
            {
                m_PluginsPtrs.Remove( plugin_type );
            }
            PluginBase module_new = PluginBase.Cast(plugin_type.Spawn());
            m_PluginsPtrs.Set(plugin_type, module_new);
        }
        for ( i = 0; i < m_PluginsPtrs.Count(); ++i)
        {
            PluginBase plugin = m_PluginsPtrs.GetElement(i);
            if ( plugin != null )
            {
                plugin.OnInit();
            }
        }
    }
References GetPluginByType(), m_PluginRegister, m_PluginsPtrs, and PluginBase::OnInit().
Referenced by PluginManagerInit().
RegisterPlugin()
protected void PluginManager::RegisterPlugin (string plugin_class_name, bool reg_on_client, bool reg_on_server, bool reg_on_release = true) inline private
Register new PluginBase to PluginManager for storing and handling plugin.
Parameters
module_tpye typename class type of plugin
Returns
void
class PluginRepairing extends PluginBase
{
...
}
RegisterPlugin(PluginRepairing);
Definition at line 181 of file pluginmanager.c.
    {
        if ( !reg_on_client )
        {
            if ( GetGame().IsMultiplayer() && GetGame().IsClient() )
            {
                return;
            }
        }
        if ( !reg_on_server )
        {
            if ( GetGame().IsMultiplayer() )
            {
                if ( GetGame().IsServer() )
                {
                    return;
                }
            }
        }
        if ( !reg_on_release )
        {
            if ( !GetGame().IsDebug() )
            {
                return;
            }
        }
        m_PluginRegister.Insert( plugin_class_name.ToType() );
    }
References GetGame(), m_PluginRegister, and string::ToType().
Referenced by Init(), RegisterPluginDebug(), and RegisterPluginDiag().
RegisterPluginDebug()
protected void PluginManager::RegisterPluginDebug (string plugin_class_name, bool reg_on_client, bool reg_on_server) inline private
Register new PluginBase to PluginManager for storing and handling plugin.
Parameters
module_tpye typename class type of plugin
Returns
void
class PluginRepairing extends PluginBase
{
...
}
RegisterPlugin(PluginRepairing);
Definition at line 229 of file pluginmanager.c.
    {
        RegisterPlugin(plugin_class_name, reg_on_client, reg_on_server, false);
    }
References RegisterPlugin().
Referenced by Init().
RegisterPluginDiag()
protected void PluginManager::RegisterPluginDiag (string plugin_class_name, bool reg_on_client, bool reg_on_server) inline private
Definition at line 236 of file pluginmanager.c.
    {
        #ifdef DIAG_DEVELOPER
        RegisterPlugin(plugin_class_name, reg_on_client, reg_on_server, true);
        #else
        return;
        #endif
    }
References RegisterPlugin().
Referenced by Init().
UnregisterPlugin()
protected bool PluginManager::UnregisterPlugin (string plugin_class_name) inline private
Definition at line 248 of file pluginmanager.c.
    {
        typename plugin_type = plugin_class_name.ToType();
        if ( m_PluginRegister.Find( plugin_type ) != -1 )
        {
            m_PluginRegister.RemoveItem( plugin_type );
            return true;
        }
        return false;
    }
References m_PluginRegister, and string::ToType().
Member Data Documentation
m_PluginRegister
private ref array<typename> PluginManager::m_PluginRegister private
Definition at line 3 of file pluginmanager.c.
Referenced by PluginManager(), PluginsInit(), RegisterPlugin(), and UnregisterPlugin().
m_PluginsPtrs
private ref map<typename, ref PluginBase> PluginManager::m_PluginsPtrs private
Definition at line 4 of file pluginmanager.c.
Referenced by GetPluginByType(), MainOnUpdate(), PluginManager(), PluginsInit(), and ~PluginManager().