DayzKode: ProgressAsync Class Reference
ProgressAsync Class Reference
Static Private Member Functions
static proto native void DestroyAllPendingProgresses ()
static proto native void SetProgressData (Widget inst)
static proto native void SetUserData (Widget inst)
static proto native void StartProgress ()
Detailed Description
Definition at line 1 of file progressasync.c.
Member Function Documentation
DestroyAllPendingProgresses()
static proto native void ProgressAsync::DestroyAllPendingProgresses () static private
Referenced by OnEvent(), and MissionBase::OnMissionStart().
SetProgressData()
static proto native void ProgressAsync::SetProgressData (Widget inst) static private
Referenced by LoadingScreen::EndLoading(), LoadingScreen::Hide(), LoadingScreen::LoadingScreen(), and LoadingScreen::Show().
SetUserData()
static proto native void ProgressAsync::SetUserData (Widget inst) static private
Referenced by LoadingScreen::EndLoading(), LoadingScreen::Hide(), LoadingScreen::LoadingScreen(), and LoadingScreen::Show().
StartProgress()
static proto native void ProgressAsync::StartProgress () static private