DayzKode: BleedingSourceZone Class Reference
BleedingSourceZone Class Reference
Private Member Functions
void BleedingSourceZone (string selection_name, int bit, vector offset, vector orientation, string bone, int max_time, float flow_modifier, string particle_name)
int GetBit ()
string GetBoneName ()
float GetFlowModifier ()
int GetInvLocation ()
int GetMaxTime ()
vector GetOffset ()
vector GetOrientation ()
string GetParticleName ()
string GetSelectionName ()
void SetInvLocation (int inv_slot)
void ~BleedingSourceZone ()
Private Attributes
int m_Bit
string m_Bone
vector m_EmitterOffset
vector m_EmitterOrientation
string m_FireSelectionName
float m_FlowModifier
int m_InventorySlotLocation
int m_MaxTime
string m_ParticleName
Detailed Description
Definition at line 1 of file bleedingsourcezone.c.
Constructor & Destructor Documentation
BleedingSourceZone()
void BleedingSourceZone::BleedingSourceZone (string selection_name, int bit, vector offset, vector orientation, string bone, int max_time, float flow_modifier, string particle_name) inline private
Definition at line 13 of file bleedingsourcezone.c.
    {
        m_FireSelectionName = selection_name;
        m_Bit = bit;
        m_EmitterOffset = offset;
        m_EmitterOrientation = orientation;
        m_Bone = bone;
        m_FlowModifier = flow_modifier;
        m_MaxTime = max_time;
        m_ParticleName = particle_name;
    }
References m_Bit, m_Bone, m_EmitterOffset, m_EmitterOrientation, m_FireSelectionName, m_FlowModifier, m_MaxTime, and m_ParticleName.
~BleedingSourceZone()
void BleedingSourceZone::~BleedingSourceZone () inline private
Definition at line 36 of file bleedingsourcezone.c.
    {
    }
Member Function Documentation
GetBit()
int BleedingSourceZone::GetBit () inline private
Definition at line 56 of file bleedingsourcezone.c.
    {
        return m_Bit;
    }
References m_Bit.
GetBoneName()
string BleedingSourceZone::GetBoneName () inline private
Definition at line 76 of file bleedingsourcezone.c.
    {
        return m_Bone;
    }
References m_Bone.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetFlowModifier()
float BleedingSourceZone::GetFlowModifier () inline private
Definition at line 61 of file bleedingsourcezone.c.
    {
        return m_FlowModifier;
    }
References m_FlowModifier.
Referenced by BleedingSourcesManagerBase::AddBleedingSource(), and BleedingSourcesManagerBase::GetMostSignificantBleedingSource().
GetInvLocation()
int BleedingSourceZone::GetInvLocation () inline private
Definition at line 31 of file bleedingsourcezone.c.
    {
        return m_InventorySlotLocation;
    }
References m_InventorySlotLocation.
Referenced by BleedingSourcesManagerBase::AddBleedingSource(), BleedingSourcesManagerBase::DisplayDebug(), and BleedingSourcesManagerBase::RemoveBleedingSource().
GetMaxTime()
int BleedingSourceZone::GetMaxTime () inline private
Definition at line 46 of file bleedingsourcezone.c.
    {
        return m_MaxTime;
    }
References m_MaxTime.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetOffset()
vector BleedingSourceZone::GetOffset () inline private
Definition at line 71 of file bleedingsourcezone.c.
    {
        return m_EmitterOffset;
    }
References m_EmitterOffset.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetOrientation()
vector BleedingSourceZone::GetOrientation () inline private
Definition at line 66 of file bleedingsourcezone.c.
    {
        return m_EmitterOrientation;
    }
References m_EmitterOrientation.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetParticleName()
string BleedingSourceZone::GetParticleName () inline private
Definition at line 51 of file bleedingsourcezone.c.
    {
        return m_ParticleName;
    }
References m_ParticleName.
Referenced by BleedingSourcesManagerBase::AddBleedingSource().
GetSelectionName()
string BleedingSourceZone::GetSelectionName () inline private
Definition at line 41 of file bleedingsourcezone.c.
    {
        return m_FireSelectionName;
    }
References m_FireSelectionName.
SetInvLocation()
void BleedingSourceZone::SetInvLocation (int inv_slot) inline private
Definition at line 26 of file bleedingsourcezone.c.
    {
        m_InventorySlotLocation = inv_slot;
    }
References m_InventorySlotLocation.
Member Data Documentation
m_Bit
int BleedingSourceZone::m_Bit private
Definition at line 4 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetBit().
m_Bone
string BleedingSourceZone::m_Bone private
Definition at line 7 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetBoneName().
m_EmitterOffset
vector BleedingSourceZone::m_EmitterOffset private
Definition at line 5 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetOffset().
m_EmitterOrientation
vector BleedingSourceZone::m_EmitterOrientation private
Definition at line 6 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetOrientation().
m_FireSelectionName
string BleedingSourceZone::m_FireSelectionName private
Definition at line 3 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetSelectionName().
m_FlowModifier
float BleedingSourceZone::m_FlowModifier private
Definition at line 8 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetFlowModifier().
m_InventorySlotLocation
int BleedingSourceZone::m_InventorySlotLocation private
Definition at line 11 of file bleedingsourcezone.c.
Referenced by GetInvLocation(), and SetInvLocation().
m_MaxTime
int BleedingSourceZone::m_MaxTime private
Definition at line 9 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetMaxTime().
m_ParticleName
string BleedingSourceZone::m_ParticleName private
Definition at line 10 of file bleedingsourcezone.c.
Referenced by BleedingSourceZone(), and GetParticleName().