DayzKode: ActionFishingNew Class Reference
ActionFishingNew Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionFishingNew ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
int EvaluateFishingResult (ActionData action_data)
override bool HasAlternativeInterrupt ()
override bool HasTarget ()
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 173 of file actionfishingnew.c.
Constructor & Destructor Documentation
ActionFishingNew()
void ActionFishingNew::ActionFishingNew () inline private
Definition at line 175 of file actionfishingnew.c.
    {
        m_CallbackClass = ActionFishingNewCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_MEDIUM;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_FISHING;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#start_fishing";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionFishingNew::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 201 of file actionfishingnew.c.
    {
        ItemBase bait;
        FishingRod_Base_New rod = FishingRod_Base_New.Cast(item);
        if (rod)
            bait = ItemBase.Cast(rod.FindAttachmentBySlotName("Hook"));
        if (bait && !bait.IsRuined())
            return true;
        return false;
    }
CreateActionData()
override ActionData ActionFishingNew::CreateActionData () inline private
Definition at line 215 of file actionfishingnew.c.
    {
        FishingActionData action_data = new FishingActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionFishingNew::CreateConditionComponents () inline private
Definition at line 185 of file actionfishingnew.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTWaterSurface(UAMaxDistances.LARGE, UAWaterType.ALL);
    }
References UAWaterType::ALL, UAMaxDistances::LARGE, m_ConditionItem, and m_ConditionTarget.
EvaluateFishingResult()
int ActionFishingNew::EvaluateFishingResult (ActionData action_data) inline private
Definition at line 299 of file actionfishingnew.c.
    {
        if (action_data.m_Player.IsQuickFishing())
            return 1;
        FishingActionData fad = FishingActionData.Cast(action_data);
        float rnd = fad.m_Player.GetRandomGeneratorSyncManager().GetRandom01(RandomGeneratorSyncUsage.RGSGeneric);
        float daytime_modifier = 1;
        float hook_modifier = 1;
        float chance;
        daytime_modifier = GetGame().GetDayTime();
        if ( (daytime_modifier > 18 && daytime_modifier < 22) || (daytime_modifier > 5 && daytime_modifier < 9) )
        {
            daytime_modifier = 1;
        }
        else
        {
            daytime_modifier = 0.5;
        }
        //fishing with an empty hook
        if (fad.IsBaitEmptyHook())
        {
            hook_modifier = 0.05;
        }
        chance = 1 - (((fad.FISHING_SUCCESS * daytime_modifier) + fad.m_RodQualityModifier)) * hook_modifier;
        if (rnd > chance)
        {
            return 1;
        }
        else if (rnd < fad.FISHING_BAIT_LOSS && !fad.IsBaitEmptyHook()) // restricts the loss of an empty hook (low chance is enough)
        {
            return 0;
        }
        return -1;
    }
References FishingActionData::FISHING_BAIT_LOSS, FishingActionData::FISHING_SUCCESS, CGame::GetDayTime(), GetGame(), FishingActionData::IsBaitEmptyHook(), ActionData::m_Player, and FishingActionData::m_RodQualityModifier.
Referenced by OnFinishProgressClient(), and OnFinishProgressServer().
HasAlternativeInterrupt()
override bool ActionFishingNew::HasAlternativeInterrupt () inline private
Definition at line 196 of file actionfishingnew.c.
    {
        return true;
    }
HasTarget()
override bool ActionFishingNew::HasTarget () inline private
Definition at line 191 of file actionfishingnew.c.
    {
        return true;
    }
Referenced by ReadFromContext(), and WriteToContext().
OnEndClient()
override void ActionFishingNew::OnEndClient (ActionData action_data) inline private
Definition at line 264 of file actionfishingnew.c.
    {
        FishingRod_Base_New rod = FishingRod_Base_New.Cast(action_data.m_MainItem);
        rod.AnimateFishingRod(false);
    }
References FishingRod_Base_New::AnimateFishingRod(), and ActionData::m_MainItem.
OnEndServer()
override void ActionFishingNew::OnEndServer (ActionData action_data) inline private
Definition at line 269 of file actionfishingnew.c.
    {
        FishingRod_Base_New rod = FishingRod_Base_New.Cast(action_data.m_MainItem);
        rod.AnimateFishingRod(false);
    }
References FishingRod_Base_New::AnimateFishingRod(), and ActionData::m_MainItem.
OnFinishProgressClient()
override void ActionFishingNew::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 247 of file actionfishingnew.c.
    {
        action_data.m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_ACTION);
        FishingActionData.Cast(action_data).m_FishingResult = EvaluateFishingResult(action_data);
    }
References EvaluateFishingResult(), ActionData::m_Callback, and FishingActionData::m_FishingResult.
OnFinishProgressServer()
override void ActionFishingNew::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 241 of file actionfishingnew.c.
    {
        action_data.m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_ACTION);
        FishingActionData.Cast(action_data).m_FishingResult = EvaluateFishingResult(action_data);
    }
References EvaluateFishingResult(), ActionData::m_Callback, and FishingActionData::m_FishingResult.
OnStartClient()
override void ActionFishingNew::OnStartClient (ActionData action_data) inline private
Definition at line 253 of file actionfishingnew.c.
    {
        FishingRod_Base_New rod = FishingRod_Base_New.Cast(action_data.m_MainItem);
        rod.AnimateFishingRod(true);
    }
References FishingRod_Base_New::AnimateFishingRod(), and ActionData::m_MainItem.
OnStartServer()
override void ActionFishingNew::OnStartServer (ActionData action_data) inline private
Definition at line 258 of file actionfishingnew.c.
    {
        FishingRod_Base_New rod = FishingRod_Base_New.Cast(action_data.m_MainItem);
        rod.AnimateFishingRod(true);
    }
References FishingRod_Base_New::AnimateFishingRod(), and ActionData::m_MainItem.
ReadFromContext()
override bool ActionFishingNew::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 285 of file actionfishingnew.c.
    {
        super.ReadFromContext(ctx, action_recive_data);
        if( HasTarget() )
        {
            vector cursor_position;
            if ( !ctx.Read(cursor_position) )
                return false;
            action_recive_data.m_Target.SetCursorHitPos(cursor_position);
        }
        return true;
    }
References HasTarget(), and Serializer::Read().
SetupAction()
override bool ActionFishingNew::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 221 of file actionfishingnew.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            vector pos_cursor = action_data.m_Target.GetCursorHitPos();
            if (GetGame().SurfaceIsSea(pos_cursor[0],pos_cursor[2]))
            {
                FishingActionData.Cast(action_data).m_IsSurfaceSea = true;
            }
            FishingRod_Base_New rod = FishingRod_Base_New.Cast(action_data.m_MainItem);
            if (rod)
            {
                FishingActionData.Cast(action_data).m_RodQualityModifier = rod.GetFishingEffectivityBonus();
                FishingActionData.Cast(action_data).InitBait(ItemBase.Cast(action_data.m_MainItem.FindAttachmentBySlotName("Hook")));
            }
            return true;
        }
        return false;
    }
References FishingRod_Base_New::GetFishingEffectivityBonus(), GetGame(), FishingActionData::InitBait(), FishingActionData::m_IsSurfaceSea, and FishingActionData::m_RodQualityModifier.
WriteToContext()
override void ActionFishingNew::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 275 of file actionfishingnew.c.
    {
        super.WriteToContext(ctx, action_data);
        if( HasTarget() )
        {
            ctx.Write(action_data.m_Target.GetCursorHitPos());
        }
    }
References HasTarget(), ActionData::m_Target, and Serializer::Write().