DayzKode: DayZPlayerCommandDeathCallback Class Reference
DayZPlayerCommandDeathCallback Class Reference
Private Member Functions
override void OnSimulationEnd ()
Private Attributes
PlayerBase m_pPlayer
Detailed Description
Definition at line 10 of file dayzplayerimplement.c.
Member Function Documentation
OnSimulationEnd()
override void DayZPlayerCommandDeathCallback::OnSimulationEnd () inline private
Definition at line 15 of file dayzplayerimplement.c.
    {
        syncDebugPrint("DZPI::OnSimulationEnd - trying to drop item");
        if (GetGame().IsServer())
        {
            EntityAI itemInHands = m_pPlayer.GetHumanInventory().GetEntityInHands();
            if (itemInHands)
            {
                int boneIndex = m_pPlayer.GetBoneIndexByName("RightHand_Dummy");
                vector m4[4];
                m_pPlayer.GetBoneTransformWS(boneIndex, m4);
                m_pPlayer.GetInventory().DropEntityWithTransform(InventoryMode.SERVER, m_pPlayer, itemInHands, m4);
                if ( GetCEApi() )
                {
                    int deadBodyLifetime = GetCEApi().GetCEGlobalInt( "CleanupLifetimeDeadPlayer" );
                    if ( deadBodyLifetime <= 0 )
                    {
                        deadBodyLifetime = 3600;
                    }
                    itemInHands.SetLifetime( deadBodyLifetime );
                }
            }
        }
        /*if (GetGame().IsServer())
        {
            EntityAI itemInHands = m_pPlayer.GetHumanInventory().GetEntityInHands();
            if (itemInHands)
            {
                if (m_pPlayer.CanDropEntity(itemInHands))
                {
                    string item_name = itemInHands.GetType();
                    m_pPlayer.ServerReplaceItemInHandsWithNewElsewhere(new DestroyItemInCorpsesHandsAndCreateNewOnGndLambda(itemInHands, item_name, m_pPlayer, false));
                }
            }
        }*/
    }
References GetCEApi(), GetGame(), m_pPlayer, and syncDebugPrint().
Member Data Documentation
m_pPlayer
PlayerBase DayZPlayerCommandDeathCallback::m_pPlayer private
Definition at line 57 of file dayzplayerimplement.c.
Referenced by HandleDeath(), and OnSimulationEnd().