DayzKode: KitchenTimer Class Reference
KitchenTimer Class Reference
Private Member Functions
override protected void Disarm ()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
override string GetDebugText ()
override string GetDestroyedSound ()
override string GetExplosiveTriggerSlotName ()
override string GetHitSound ()
int GetMinutesMax ()
override float GetRingingDurationMax ()
override string GetRingingSound ()
string GetRingingStopSound ()
override string GetToggleSound ()
override string GetWorkingSound ()
override void Init ()
override void OnDebugButtonPressServer (int button_index)
override protected void OnRingingStopClient ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
void OnUpdate ()
float SecondsTo01 (int seconds)
override void SetActions ()
override void SetAlarmTimeServer (float time01)
void SetAlarmTimeServerSecs (int inSecs)
int Time01ToSeconds (float time01)
override void TurnOff ()
Private Attributes
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet"
const string HIT_SOUND = "AlarmClock_Hit_SoundSet"
int m_AlarmInSecs
EffectSound m_RingingStopSound
const string RINGING_SOUND = "KitchenTimer_Ring_Loop_SoundSet"
const string WORKING_SOUND = "KitchenTimer_Ticking_Loop_SoundSet"
Static Private Attributes
static ref NoiseParams m_NoisePar
static NoiseSystem m_NoiseSystem
Detailed Description
Definition at line 1 of file kitchentimer.c.
Member Function Documentation
Disarm()
override protected void KitchenTimer::Disarm () inline private
Definition at line 131 of file kitchentimer.c.
    {
        super.Disarm();
        SetAlarmTimeServerSecs(0);
    }
References SetAlarmTimeServerSecs().
GetDebugButtonNames()
override void KitchenTimer::GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline private
Definition at line 219 of file kitchentimer.c.
    {
        button1 = "SetAlarmAhead";
    }
GetDebugText()
override string KitchenTimer::GetDebugText () inline private
Definition at line 232 of file kitchentimer.c.
    {
        string debug_output;
        if( GetGame().IsDedicatedServer())
        {
            debug_output = "alarm in: " + m_AlarmInSecs.ToString() + " secs" + "\n";
            debug_output +=  "current state: " +  typename.EnumToString(EAlarmClockState, m_State) + "\n";
            debug_output +=  "ringing for " + m_RingingDuration.ToString()+ " secs" + "\n";
            debug_output +=  "ringing max " + GetRingingDurationMax().ToString()+ " secs" + "\n";
        }
        else
        {
            debug_output = "this is client";
        }
        return debug_output;
    }
References GetGame(), GetRingingDurationMax(), m_AlarmInSecs, m_RingingDuration, m_State, and float::ToString().
GetDestroyedSound()
override string KitchenTimer::GetDestroyedSound () inline private
Definition at line 57 of file kitchentimer.c.
    {
        return DESTROYED_SOUND;
    }
References DESTROYED_SOUND.
GetExplosiveTriggerSlotName()
override string KitchenTimer::GetExplosiveTriggerSlotName () inline private
Definition at line 37 of file kitchentimer.c.
    {
        return "TriggerKitchenTimer";
    }
GetHitSound()
override string KitchenTimer::GetHitSound () inline private
Definition at line 62 of file kitchentimer.c.
    {
        return HIT_SOUND;
    }
References HIT_SOUND.
GetMinutesMax()
int KitchenTimer::GetMinutesMax () inline private
Definition at line 72 of file kitchentimer.c.
    {
        return 45;
    }
Referenced by SecondsTo01(), and Time01ToSeconds().
GetRingingDurationMax()
override float KitchenTimer::GetRingingDurationMax () inline private
Definition at line 88 of file kitchentimer.c.
    {
        return 60;
    }
Referenced by GetDebugText(), and OnUpdate().
GetRingingSound()
override string KitchenTimer::GetRingingSound () inline private
Definition at line 47 of file kitchentimer.c.
    {
        return RINGING_SOUND;
    }
References RINGING_SOUND.
GetRingingStopSound()
string KitchenTimer::GetRingingStopSound () inline private
Definition at line 52 of file kitchentimer.c.
    {
        return "KitchenTimer_Ring_End_SoundSet";
    }
Referenced by OnRingingStopClient().
GetToggleSound()
override string KitchenTimer::GetToggleSound () inline private
Definition at line 42 of file kitchentimer.c.
    {
        return "";
    };
GetWorkingSound()
override string KitchenTimer::GetWorkingSound () inline private
Definition at line 67 of file kitchentimer.c.
    {
        return WORKING_SOUND;
    }
References WORKING_SOUND.
Init()
override void KitchenTimer::Init () inline private
Definition at line 14 of file kitchentimer.c.
    {
        super.Init();
        if ( GetGame().IsServer() )
        {
            m_NoiseSystem = GetGame().GetNoiseSystem();
            if ( m_NoiseSystem && !m_NoisePar )
            {
                // Create and load noise parameters
                m_NoisePar = new NoiseParams;
                m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseKitchenTimer");
            }
        }
    }
References GetGame(), CGame::GetNoiseSystem(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
OnDebugButtonPressServer()
override void KitchenTimer::OnDebugButtonPressServer (int button_index) inline private
Definition at line 224 of file kitchentimer.c.
    {
        if (button_index == 1)
        {
            SetAlarmTimeServerSecs(10);
        }
    }
References SetAlarmTimeServerSecs().
OnRingingStopClient()
override protected void KitchenTimer::OnRingingStopClient () inline private
Definition at line 137 of file kitchentimer.c.
    {
        if (m_RingingSoundLoop)
            PlaySoundSet( m_RingingStopSound, GetRingingStopSound(), 0, 0);
        super.OnRingingStopClient();
    }
References GetRingingStopSound(), m_RingingSoundLoop, m_RingingStopSound, and PlaySoundSet().
OnStoreLoad()
override bool KitchenTimer::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 145 of file kitchentimer.c.
    {
        if (!super.OnStoreLoad(ctx, version))
            return false;
        if (version < 128)
        {
            return true;
        }
        EAlarmClockState state;
        if ( !ctx.Read( state ) )
        {
            return false;
        }
        int time;
        if (!ctx.Read( time ))
        {
            return false;
        }
        SetState(state);
        if (state == EAlarmClockState.SET)
        {
            SetAlarmTimeServerSecs(time);
        }
        else if (state == EAlarmClockState.RINGING )
        {
            MakeRingingStart();
        }
        return true;
    }
References MakeRingingStart(), Serializer::Read(), SetAlarmTimeServerSecs(), and SetState().
OnStoreSave()
override void KitchenTimer::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 183 of file kitchentimer.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_State);
        ctx.Write(m_AlarmInSecs);
    }
References m_AlarmInSecs, m_State, and Serializer::Write().
OnUpdate()
void KitchenTimer::OnUpdate () inline private
Definition at line 99 of file kitchentimer.c.
    {
        if (m_AlarmInSecs > 0)
        {
            m_AlarmInSecs -= UPDATE_TICK_RATE;
            float time01 = SecondsTo01(m_AlarmInSecs);
            SetAnimationPhaseNow("ClockAlarm", time01);
            if (IsRinging())
            {
                MakeRingingStop();
            }
        }
        else if (!IsRinging())
        {
            MakeRingingStart();
        }
        if (IsRinging())
        {
            m_RingingDuration += UPDATE_TICK_RATE;
            if (m_RingingDuration >= GetRingingDurationMax())
            {
                TurnOff();
            }
            else if ( m_NoiseSystem )
            {
                m_NoiseSystem.AddNoiseTarget( GetPosition(), UPDATE_TICK_RATE, m_NoisePar);
            }
        }
    }
References NoiseSystem::AddNoiseTarget(), GetPosition, GetRingingDurationMax(), IsRinging(), m_AlarmInSecs, m_NoisePar, m_NoiseSystem, m_RingingDuration, MakeRingingStart(), MakeRingingStop(), SecondsTo01(), TurnOff(), and UPDATE_TICK_RATE.
SecondsTo01()
float KitchenTimer::SecondsTo01 (int seconds) inline private
Definition at line 83 of file kitchentimer.c.
    {
        return Math.InverseLerp(0,GetMinutesMax() * 60, seconds);
    }
References GetMinutesMax(), and Math::InverseLerp().
Referenced by OnUpdate(), and SetAlarmTimeServerSecs().
SetActions()
override void KitchenTimer::SetActions () inline private
Definition at line 30 of file kitchentimer.c.
    {
        super.SetActions();
        AddAction(ActionSetKitchenTimer);
        AddAction(ActionResetKitchenTimer);
    }
References ActionResetKitchenTimer(), and AddAction().
SetAlarmTimeServer()
override void KitchenTimer::SetAlarmTimeServer (float time01) inline private
Definition at line 198 of file kitchentimer.c.
    {
        SetAnimationPhaseNow("ClockAlarm", time01);
        m_AlarmInSecs = Time01ToSeconds(time01);
        if (m_AlarmInSecs > 0 )
        {
            TurnOn();
        }
    }
References m_AlarmInSecs, Time01ToSeconds(), and TurnOn().
Referenced by ActionSetKitchenTimer::OnEndServer(), and SetAlarmTimeServerSecs().
SetAlarmTimeServerSecs()
void KitchenTimer::SetAlarmTimeServerSecs (int inSecs) inline private
Definition at line 209 of file kitchentimer.c.
    {
        SetAlarmTimeServer(SecondsTo01(inSecs));
    }
References SecondsTo01(), and SetAlarmTimeServer().
Referenced by Disarm(), OnDebugButtonPressServer(), and OnStoreLoad().
Time01ToSeconds()
int KitchenTimer::Time01ToSeconds (float time01) inline private
Definition at line 77 of file kitchentimer.c.
    {
        return Math.Lerp(0,GetMinutesMax() * 60, time01);
    }
References GetMinutesMax(), and Math::Lerp().
Referenced by SetAlarmTimeServer().
TurnOff()
override void KitchenTimer::TurnOff () inline private
Definition at line 93 of file kitchentimer.c.
    {
        super.TurnOff();
        SEffectManager.DestroyEffect(m_WorkingSound);
    }
References SEffectManager::DestroyEffect(), and m_WorkingSound.
Referenced by OnUpdate().
Member Data Documentation
DESTROYED_SOUND
const string KitchenTimer::DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet" private
Definition at line 4 of file kitchentimer.c.
Referenced by GetDestroyedSound().
HIT_SOUND
const string KitchenTimer::HIT_SOUND = "AlarmClock_Hit_SoundSet" private
Definition at line 5 of file kitchentimer.c.
Referenced by GetHitSound().
m_AlarmInSecs
int KitchenTimer::m_AlarmInSecs private
Definition at line 12 of file kitchentimer.c.
Referenced by GetDebugText(), OnStoreSave(), OnUpdate(), and SetAlarmTimeServer().
m_NoisePar
ref NoiseParams KitchenTimer::m_NoisePar static private
Definition at line 9 of file kitchentimer.c.
Referenced by Init(), and OnUpdate().
m_NoiseSystem
NoiseSystem KitchenTimer::m_NoiseSystem static private
Definition at line 10 of file kitchentimer.c.
Referenced by Init(), and OnUpdate().
m_RingingStopSound
EffectSound KitchenTimer::m_RingingStopSound private
Definition at line 8 of file kitchentimer.c.
Referenced by OnRingingStopClient().
RINGING_SOUND
const string KitchenTimer::RINGING_SOUND = "KitchenTimer_Ring_Loop_SoundSet" private
Definition at line 3 of file kitchentimer.c.
Referenced by GetRingingSound().
WORKING_SOUND
const string KitchenTimer::WORKING_SOUND = "KitchenTimer_Ticking_Loop_SoundSet" private
Definition at line 6 of file kitchentimer.c.
Referenced by GetWorkingSound().