DayzKode: ActionUncoverHeadBase Class Reference
ActionUncoverHeadBase Class Reference
Private Member Functions
void UncoverHead (PlayerBase target, PlayerBase source)
Detailed Description
Definition at line 10 of file actionuncoverheadself.c.
Member Function Documentation
UncoverHead()
void ActionUncoverHeadBase::UncoverHead (PlayerBase target, PlayerBase source) inline private
Definition at line 12 of file actionuncoverheadself.c.
    {
        EntityAI attachment;
        if( !source.GetHumanInventory().GetEntityInHands() )
        {
            ItemBase item = ItemBase.Cast(HumanInventory.Cast(source.GetInventory()).CreateInHands("BurlapSack"));
        }
        else
        {
            EntityAI entity = source.GetInventory().CreateInInventory("BurlapSack");
            if( !entity )//full inventory
            {
                vector m4[4];
                source.GetTransformWS(m4);
                InventoryLocation target_gnd = new InventoryLocation;
                target_gnd.SetGround(null, m4);
                entity = GameInventory.LocationCreateEntity(target_gnd, "BurlapSack",ECE_IN_INVENTORY,RF_DEFAULT);
            }
            ItemBase new_item = ItemBase.Cast(entity);
        }
        Class.CastTo(attachment, target.GetInventory().FindAttachment(InventorySlots.HEADGEAR));
        if ( attachment && attachment.GetType() == "BurlapSackCover" )
        {
            if (new_item)
                MiscGameplayFunctions.TransferItemProperties(attachment,new_item,true,false,true);
            attachment.Delete();
        }
        source.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), HumanInventory::CreateInHands(), ECE_IN_INVENTORY, m_SpecialtyWeight, RF_DEFAULT, and InventoryLocation::SetGround().
Referenced by OnFinishProgressServer(), and ActionUncoverHeadTarget::OnFinishProgressServer().