DayzKode: CAContinuousMineRock Class Reference
CAContinuousMineRock Class Reference
Private Member Functions
void CAContinuousMineRock (float time_between_drops)
override bool GetMiningData (ActionData action_data)
Detailed Description
Definition at line 1 of file cacontinuousminerock.c.
Constructor & Destructor Documentation
CAContinuousMineRock()
void CAContinuousMineRock::CAContinuousMineRock (float time_between_drops) inline private
Definition at line 3 of file cacontinuousminerock.c.
    {
        m_TimeBetweenMaterialDrops = time_between_drops;
    }
References CAContinuousMineWood::m_TimeBetweenMaterialDrops.
Member Function Documentation
GetMiningData()
override bool CAContinuousMineRock::GetMiningData (ActionData action_data) inline private
Definition at line 8 of file cacontinuousminerock.c.
    {
        RockBase ntarget;
        if ( Class.CastTo(ntarget, action_data.m_Target.GetObject()) )
        {
            m_AmountOfDrops = Math.Max(1,ntarget.GetAmountOfDrops(action_data.m_MainItem));
            //m_Material = ntarget.GetMaterial(action_data.m_MainItem);
            //m_AmountOfMaterialPerDrop = Math.Max(1,ntarget.GetAmountOfMaterialPerDrop(action_data.m_MainItem));
            ntarget.GetMaterialAndQuantityMap(action_data.m_MainItem,m_MaterialAndQuantityMap);
            m_DamageToMiningItemEachDrop = ntarget.GetDamageToMiningItemEachDrop(action_data.m_MainItem);
            m_AdjustedDamageToMiningItemEachDrop = action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus( m_DamageToMiningItemEachDrop, m_Action.GetSpecialtyWeight(), true );
            return true;
        }
        return false;
    }
References Class::CastTo(), RockBase::GetAmountOfDrops(), RockBase::GetDamageToMiningItemEachDrop(), RockBase::GetMaterialAndQuantityMap(), CABase::m_Action, CAContinuousMineWood::m_AdjustedDamageToMiningItemEachDrop, CAContinuousMineWood::m_AmountOfDrops, CAContinuousMineWood::m_DamageToMiningItemEachDrop, ActionData::m_MainItem, CAContinuousMineWood::m_MaterialAndQuantityMap, ActionData::m_Player, ActionData::m_Target, and Math::Max().