DayzKode: PlayerPreviewWidget Class Reference
PlayerPreviewWidget Class Reference
Private Member Functions
proto native DayZPlayer GetDummyPlayer ()
proto native vector GetModelOrientation ()
proto native vector GetModelPosition ()
proto native void Refresh ()
proto native void SetModelOrientation (vector vOrientation)
proto native void SetModelPosition (vector vPos)
proto native void SetPlayer (DayZPlayer player)
proto native void UpdateItemInHands (EntityAI object)
Detailed Description
Definition at line 296 of file gameplay.c.
Member Function Documentation
GetDummyPlayer()
proto native DayZPlayer PlayerPreviewWidget::GetDummyPlayer () private
Referenced by PlayerPreview::UpdateInterval().
GetModelOrientation()
proto native vector PlayerPreviewWidget::GetModelOrientation () private
GetModelPosition()
proto native vector PlayerPreviewWidget::GetModelPosition () private
Refresh()
proto native void PlayerPreviewWidget::Refresh () private
Referenced by PlayerPreview::RefreshPlayerPreview().
SetModelOrientation()
proto native void PlayerPreviewWidget::SetModelOrientation (vector vOrientation) private
Referenced by PlayerPreview::UpdateRotation().
SetModelPosition()
proto native void PlayerPreviewWidget::SetModelPosition (vector vPos) private
Referenced by PlayerPreview::PlayerPreview().
SetPlayer()
proto native void PlayerPreviewWidget::SetPlayer (DayZPlayer player) private
Referenced by PlayerPreview::PlayerPreview().
UpdateItemInHands()
proto native void PlayerPreviewWidget::UpdateItemInHands (EntityAI object) private
Referenced by PlayerPreview::UpdateInterval().