DayzKode: WeaponStartAction Class Reference
WeaponStartAction Class Reference
simple class starting animation action specified by m_action and m_actionType
Private Member Functions
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override void OnAbort (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
void WeaponUnjamming_Start (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
Private Attributes
float m_dtAccumulator
float m_jamTime
Detailed Description
simple class starting animation action specified by m_action and m_actionType
Definition at line 2 of file weaponchambering.c.
Member Function Documentation
IsWaitingForActionFinish() [1/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 14 of file weaponchambering.c.
    {
        return true;
    }
IsWaitingForActionFinish() [2/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 611 of file weaponchambering.c.
    {
        return true;
    }
IsWaitingForActionFinish() [3/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 4 of file weaponchamberinglooped.c.
{ return true; }
IsWaitingForActionFinish() [4/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 54 of file weaponcharging.c.
    {
        return true;
    }
IsWaitingForActionFinish() [5/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 16 of file weaponfire.c.
{ return true; }
IsWaitingForActionFinish() [6/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 48 of file weaponfire.c.
{ return true; }
IsWaitingForActionFinish() [7/7]
override bool WeaponStartAction::IsWaitingForActionFinish () inline private
Definition at line 268 of file weaponfire.c.
{ return true; }
OnAbort()
override void WeaponStartAction::OnAbort (WeaponEventBase e) inline private
Definition at line 91 of file weaponfire.c.
    {
        m_weapon.ResetBurstCount();
        super.OnAbort(e);
    }
References m_weapon.
OnEntry() [1/5]
override void WeaponStartAction::OnEntry (WeaponEventBase e) inline private
Definition at line 4 of file weaponchambering.c.
    {
        super.OnEntry(e);
        if (e)
        {
            m_weapon.SelectionBulletHide();
            m_weapon.ForceSyncSelectionState();
        }
    }
References m_weapon.
OnEntry() [2/5]
override void WeaponStartAction::OnEntry (WeaponEventBase e) inline private
Definition at line 6 of file weaponfire.c.
    {
        super.OnEntry(e);
        if (e)
        {
            m_dtAccumulator = 0;
        }
        m_weapon.ResetBurstCount();
    }
References m_dtAccumulator, and m_weapon.
OnEntry() [3/5]
override void WeaponStartAction::OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file weaponfire.c.
    {
        if (e)
        {
            m_dtAccumulator = 0;
            if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponFire bang!"); }
            //m_weapon.Fire();
            int mi = m_weapon.GetCurrentMuzzle();
            if (TryFireWeapon(m_weapon, mi))
            {
                DayZPlayerImplement p;
                if (Class.CastTo(p, e.m_player))
                    p.GetAimingModel().SetRecoil(m_weapon);
                m_weapon.OnFire(mi);
            }
        }
        super.OnEntry(e);
    }
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
OnEntry() [4/5]
override void WeaponStartAction::OnEntry (WeaponEventBase e) inline private
Definition at line 270 of file weaponfire.c.
    {
        if (e)
        {
            m_dtAccumulator = 0;
            if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponFire bang! and jam?"); }
            //m_weapon.Fire();
            int mi = m_weapon.GetCurrentMuzzle();
            if (TryFireWeapon(m_weapon, mi))
            {
                m_weapon.SetJammed(true);
                DayZPlayerImplement p;
                if (Class.CastTo(p, e.m_player))
                    p.GetAimingModel().SetRecoil(m_weapon);
                m_weapon.OnFire(mi);
            }
        }
        m_weapon.ResetBurstCount();
        super.OnEntry(e);
    }
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
OnEntry() [5/5]
override void WeaponStartAction::OnEntry (WeaponEventBase e) inline private
Definition at line 22 of file weaponunjamming.c.
    {
        super.OnEntry(e);
    }
OnExit() [1/4]
override void WeaponStartAction::OnExit (WeaponEventBase e) inline private
Definition at line 35 of file weaponfire.c.
    {
        m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [2/4]
override void WeaponStartAction::OnExit (WeaponEventBase e) inline private
Definition at line 84 of file weaponfire.c.
    {
        if (e)
            m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [3/4]
override void WeaponStartAction::OnExit (WeaponEventBase e) inline private
Definition at line 306 of file weaponfire.c.
    {
        m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [4/4]
override void WeaponStartAction::OnExit (WeaponEventBase e) inline private
Definition at line 64 of file weaponunjamming.c.
    {
        m_dtAccumulator = 0.0;
        m_jamTime = 0.0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnUpdate() [1/4]
override void WeaponStartAction::OnUpdate (float dt) inline private
Definition at line 18 of file weaponfire.c.
    {
        m_dtAccumulator += dt;
        DayZPlayer p;
        Class.CastTo(p, m_weapon.GetHierarchyParent());
        if (p)
        {
            HumanInputController hic = p.GetInputController();
            int muzzleIndex = m_weapon.GetCurrentMuzzle();
            float reloadTime = m_weapon.GetReloadTime(muzzleIndex);
            if ( hic.IsAttackButton() && m_dtAccumulator >= reloadTime)
                if (m_weapon.CanProcessWeaponEvents())
                    m_weapon.ProcessWeaponEvent(new WeaponEventDryFireTimeout(p));
        }
    }
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [2/4]
override void WeaponStartAction::OnUpdate (float dt) inline private
Definition at line 70 of file weaponfire.c.
    {
        m_dtAccumulator += dt;
        DayZPlayer p;
        Class.CastTo(p, m_weapon.GetHierarchyParent());
        int muzzleIndex = m_weapon.GetCurrentMuzzle();
        float reloadTime = m_weapon.GetReloadTime(muzzleIndex);
        if (m_dtAccumulator >= reloadTime)
            if (m_weapon.CanProcessWeaponEvents())
                m_weapon.ProcessWeaponEvent(new WeaponEventReloadTimeout(p));
    }
References Class::CastTo(), m_dtAccumulator, and m_weapon.
OnUpdate() [3/4]
override void WeaponStartAction::OnUpdate (float dt) inline private
Definition at line 292 of file weaponfire.c.
    {
            m_dtAccumulator += dt;
            DayZPlayer p;
            Class.CastTo(p, m_weapon.GetHierarchyParent());
            int muzzleIndex = m_weapon.GetCurrentMuzzle();
            float reloadTime = m_weapon.GetReloadTime(muzzleIndex);
            if (m_dtAccumulator >= reloadTime)
                if (m_weapon.CanProcessWeaponEvents())
                    m_weapon.ProcessWeaponEvent(new WeaponEventReloadTimeout(p));
    }
References Class::CastTo(), m_dtAccumulator, and m_weapon.
OnUpdate() [4/4]
override void WeaponStartAction::OnUpdate (float dt) inline private
Definition at line 27 of file weaponunjamming.c.
    {
        m_dtAccumulator += dt;
        DayZPlayer p;
        Class.CastTo(p, m_weapon.GetHierarchyParent());
        if(p)
        {
            HumanInputController hic = p.GetInputController();
            HumanCommandWeapons hcw = p.GetCommandModifier_Weapons();
            if (m_dtAccumulator >= m_jamTime)
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " Unjammed!"); }
                hcw.StartAction(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END);
                m_weapon.ProcessWeaponEvent(new WeaponEventUnjammingTimeout(p));
                return; // unjammed successfuly
            }
            if (hic.IsReloadOrMechanismContinuousUse())
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " Unjamming..."); }
            }
            #ifndef PLATFORM_CONSOLE
            #ifndef SERVER_FOR_CONSOLE
            else
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " Unjamming failed, weapon still jammed"); }
                hcw.StartAction(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_INTERRUPT);
                m_weapon.ProcessWeaponEvent(new WeaponEventUnjammingFailedTimeout(p));
            }
            #endif
            #endif
        }
    }
References Class::CastTo(), HumanInputController::IsReloadOrMechanismContinuousUse(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, m_weapon, HumanCommandWeapons::StartAction(), and wpnDebugPrint().
WeaponUnjamming_Start()
void WeaponStartAction::WeaponUnjamming_Start (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 16 of file weaponunjamming.c.
    {
        m_dtAccumulator = 0.0;
        m_jamTime = 0.0;
    }
References m_dtAccumulator.
Member Data Documentation
m_dtAccumulator
float WeaponStartAction::m_dtAccumulator private
Definition at line 4 of file weaponfire.c.
m_jamTime
float WeaponStartAction::m_jamTime private
Definition at line 14 of file weaponunjamming.c.