DayzKode: ActionToggleNVMode Class Reference
ActionToggleNVMode Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionToggleNVMode ()
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void SwitchMode (ActionData action_data)
Detailed Description
Definition at line 2 of file actiontogglenvmode.c.
Constructor & Destructor Documentation
ActionToggleNVMode()
void ActionToggleNVMode::ActionToggleNVMode () inline private
Definition at line 4 of file actiontogglenvmode.c.
    {
        //m_CallbackClass = ActionTurnOnTransmitterCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_ITEM_ON;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_ITEM_ON;
        m_Text = "#switch_mode";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionToggleNVMode::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 23 of file actiontogglenvmode.c.
    {
        ItemOptics optics;
        if ( Class.CastTo(optics,item) && optics.IsNVOptic() )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
CreateConditionComponents()
override void ActionToggleNVMode::CreateConditionComponents () inline private
Definition at line 12 of file actiontogglenvmode.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionToggleNVMode::HasTarget () inline private
Definition at line 18 of file actiontogglenvmode.c.
    {
        return false;
    }
OnExecuteClient()
override void ActionToggleNVMode::OnExecuteClient (ActionData action_data) inline private
Definition at line 39 of file actiontogglenvmode.c.
    {
        SwitchMode(action_data);
    }
References SwitchMode().
OnExecuteServer()
override void ActionToggleNVMode::OnExecuteServer (ActionData action_data) inline private
Definition at line 34 of file actiontogglenvmode.c.
    {
        SwitchMode(action_data);
    }
References SwitchMode().
SwitchMode()
void ActionToggleNVMode::SwitchMode (ActionData action_data) inline private
Definition at line 44 of file actiontogglenvmode.c.
    {
        ItemOptics optics = ItemOptics.Cast(action_data.m_MainItem);
        switch (optics.GetCurrentOpticMode())
        {
            case GameConstants.OPTICS_STATE_DAY:
                optics.SetCurrentOpticMode(GameConstants.OPTICS_STATE_NIGHTVISION);
                //TODO: animate
            break;
            case GameConstants.OPTICS_STATE_NIGHTVISION:
                optics.SetCurrentOpticMode(GameConstants.OPTICS_STATE_DAY);
                //TODO: animate
            break;
        }
    }
References ActionData::m_MainItem, GameConstants::OPTICS_STATE_DAY, and GameConstants::OPTICS_STATE_NIGHTVISION.
Referenced by OnExecuteClient(), and OnExecuteServer().