DayzKode: AttachmentsWrapper Class Reference
AttachmentsWrapper Class Reference
Private Member Functions
void AttachmentsWrapper (LayoutHolder parent)
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool CanEquip ()
override bool Combine ()
override bool EquipItem ()
TextWidget GetFalseHeaderTextWidget ()
int GetFocusedSlot ()
override bool InspectItem ()
override bool IsDisplayable ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool Select ()
override bool SelectItem ()
void SetFalseAttachmentsHeaderText (string text)
void SetParent (Attachments atts)
void ShowFalseAttachmentsHeader (bool show)
override bool SplitItem ()
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void UpdateInterval ()
Private Attributes
Attachments m_Attachments
protected Widget m_AttachmentsFalseHeader
protected RichTextWidget m_AttachmentsFalseHeaderText
Detailed Description
Definition at line 1 of file attachmentswrapper.c.
Constructor & Destructor Documentation
AttachmentsWrapper()
void AttachmentsWrapper::AttachmentsWrapper (LayoutHolder parent) inline private
Definition at line 7 of file attachmentswrapper.c.
    {
        m_AttachmentsFalseHeader        = m_RootWidget.FindAnyWidget( "attachmets_wrapper_header_spacer" );
        m_AttachmentsFalseHeaderText    = RichTextWidget.Cast(m_AttachmentsFalseHeader.FindAnyWidget("TextWidget0"));
        m_AttachmentsFalseHeader.Show( false );
    }
References m_AttachmentsFalseHeader, m_AttachmentsFalseHeaderText, and m_RootWidget.
Member Function Documentation
CanCombine()
override bool AttachmentsWrapper::CanCombine () inline private
Definition at line 64 of file attachmentswrapper.c.
    {
        return m_Attachments.CanCombine();
    }
References Attachments::CanCombine(), and m_Attachments.
CanCombineAmmo()
override bool AttachmentsWrapper::CanCombineAmmo () inline private
Definition at line 69 of file attachmentswrapper.c.
    {
        return m_Attachments.CanCombineAmmo();
    }
References Attachments::CanCombineAmmo(), and m_Attachments.
CanEquip()
override bool AttachmentsWrapper::CanEquip () inline private
Definition at line 59 of file attachmentswrapper.c.
    {
        return m_Attachments.CanEquip();
    }
References Attachments::CanEquip(), and m_Attachments.
Combine()
override bool AttachmentsWrapper::Combine () inline private
Definition at line 29 of file attachmentswrapper.c.
    {
        return m_Attachments.Combine();
    }
References Attachments::Combine(), and m_Attachments.
EquipItem()
override bool AttachmentsWrapper::EquipItem () inline private
Definition at line 54 of file attachmentswrapper.c.
    {
        return m_Attachments.EquipItem();
    }
References Attachments::EquipItem(), and m_Attachments.
GetFalseHeaderTextWidget()
TextWidget AttachmentsWrapper::GetFalseHeaderTextWidget () inline private
Definition at line 110 of file attachmentswrapper.c.
    {
        return m_AttachmentsFalseHeaderText;
    }
References m_AttachmentsFalseHeaderText.
Referenced by Attachments::GetFalseHeaderTextWidget().
GetFocusedSlot()
int AttachmentsWrapper::GetFocusedSlot () inline private
Definition at line 95 of file attachmentswrapper.c.
    {
        return m_Attachments.GetFocusedSlot();
    }
References Attachments::GetFocusedSlot(), and m_Attachments.
InspectItem()
override bool AttachmentsWrapper::InspectItem () inline private
Definition at line 44 of file attachmentswrapper.c.
    {
        return m_Attachments.InspectItem();
    }
References Attachments::InspectItem(), and m_Attachments.
IsDisplayable()
override bool AttachmentsWrapper::IsDisplayable () inline private
Definition at line 74 of file attachmentswrapper.c.
    {
        return !IsEmpty();
    }
References Container::IsEmpty().
IsItemActive()
override bool AttachmentsWrapper::IsItemActive () inline private
Definition at line 79 of file attachmentswrapper.c.
    {
        return m_Attachments.IsItemActive();
    }
References Attachments::IsItemActive(), and m_Attachments.
IsItemWithQuantityActive()
override bool AttachmentsWrapper::IsItemWithQuantityActive () inline private
Definition at line 84 of file attachmentswrapper.c.
    {
        return m_Attachments.IsItemWithQuantityActive();
    }
References Attachments::IsItemWithQuantityActive(), and m_Attachments.
Select()
override bool AttachmentsWrapper::Select () inline private
Definition at line 19 of file attachmentswrapper.c.
    {
        return m_Attachments.Select();
    }
References m_Attachments, and Attachments::Select().
SelectItem()
override bool AttachmentsWrapper::SelectItem () inline private
Definition at line 24 of file attachmentswrapper.c.
    {
        return m_Attachments.SelectItem();
    }
References m_Attachments, and Attachments::SelectItem().
SetFalseAttachmentsHeaderText()
void AttachmentsWrapper::SetFalseAttachmentsHeaderText (string text) inline private
Definition at line 105 of file attachmentswrapper.c.
    {
        m_AttachmentsFalseHeaderText.SetText(text);
    }
References m_AttachmentsFalseHeaderText.
Referenced by Attachments::InitAttachmentGrid(), and Attachments::SetFalseAttachmentsHeaderText().
SetParent()
void AttachmentsWrapper::SetParent (Attachments atts) inline private
Definition at line 14 of file attachmentswrapper.c.
    {
        m_Attachments = atts;
    }
References m_Attachments.
Referenced by Attachments::InitAttachmentGrid().
ShowFalseAttachmentsHeader()
void AttachmentsWrapper::ShowFalseAttachmentsHeader (bool show) inline private
Definition at line 100 of file attachmentswrapper.c.
    {
        m_AttachmentsFalseHeader.Show(show);
    }
References m_AttachmentsFalseHeader.
Referenced by Attachments::ShowFalseAttachmentsHeader().
SplitItem()
override bool AttachmentsWrapper::SplitItem () inline private
Definition at line 49 of file attachmentswrapper.c.
    {
        return m_Attachments.SplitItem();
    }
References m_Attachments, and Attachments::SplitItem().
TransferItem()
override bool AttachmentsWrapper::TransferItem () inline private
Definition at line 39 of file attachmentswrapper.c.
    {
        return m_Attachments.TransferItem();
    }
References m_Attachments, and Attachments::TransferItem().
TransferItemToVicinity()
override bool AttachmentsWrapper::TransferItemToVicinity () inline private
Definition at line 34 of file attachmentswrapper.c.
    {
        return m_Attachments.TransferItemToVicinity();
    }
References m_Attachments, and Attachments::TransferItemToVicinity().
UpdateInterval()
override void AttachmentsWrapper::UpdateInterval () inline private
Definition at line 89 of file attachmentswrapper.c.
    {
        super.UpdateInterval();
        m_Attachments.UpdateInterval();
    }
References m_Attachments, and Attachments::UpdateInterval().
Member Data Documentation
m_Attachments
Attachments AttachmentsWrapper::m_Attachments private
Definition at line 3 of file attachmentswrapper.c.
Referenced by CanCombine(), CanCombineAmmo(), CanEquip(), Combine(), EquipItem(), GetFocusedSlot(), InspectItem(), IsItemActive(), IsItemWithQuantityActive(), Select(), SelectItem(), SetParent(), SplitItem(), TransferItem(), TransferItemToVicinity(), and UpdateInterval().
m_AttachmentsFalseHeader
protected Widget AttachmentsWrapper::m_AttachmentsFalseHeader private
Definition at line 4 of file attachmentswrapper.c.
Referenced by AttachmentsWrapper(), and ShowFalseAttachmentsHeader().
m_AttachmentsFalseHeaderText
protected RichTextWidget AttachmentsWrapper::m_AttachmentsFalseHeaderText private
Definition at line 5 of file attachmentswrapper.c.
Referenced by AttachmentsWrapper(), GetFalseHeaderTextWidget(), and SetFalseAttachmentsHeaderText().