DayzKode: MessageReceiverBase Class Reference
MessageReceiverBase Class Reference
Private Member Functions
void AgentBase ()
bool AutoinfectCheck (float deltaT, PlayerBase player)
int BitToDec (int mask, int index, int length)
void Broadcast (int channel)
void BroadcastFloat (int channel, float value)
void BroadcastInt (int channel, int value)
void BroadcastParam (int channel, Param params)
void BroadcastString (int channel, string value)
float CalculateAutoinfectProbability (float userprob)
bool CanAutoinfectPlayer (PlayerBase player)
void DisplayElementBase (PlayerBase player)
int GetAgentType ()
float GetAntibioticsResistanceEx (PlayerBase player)
float GetAntiboticsResistance ()
int GetCompareMask ()
float GetDieOffSpeed ()
float GetDieOffSpeedEx (PlayerBase player)
float GetDigestibility ()
float GetInvasibility ()
float GetInvasibilityEx (PlayerBase player)
int GetMaxCount ()
string GetName ()
int GetNumberOfBits ()
EStatLevels GetPotency ()
EStatLevels GetPotencyEx (PlayerBase player)
float GetTransferabilityAirOut ()
float GetTransferabilityIn ()
float GetTransferabilityOut ()
int GetType ()
int GetValue ()
bool GrowDuringAntibioticsAttack (PlayerBase player)
void Init ()
bool IsClientOnly ()
bool IsValueChanged ()
void Log (string message)
void MessageReceiverBase ()
void OnReceive (int channel)
void OnReceiveFloat (int channel, float value)
void OnReceiveInt (int channel, int value)
void OnReceiveParam (int channel, Param params)
This method is called when an object inheriting from this class subscribes to a channel, and a message along with an object reference is broadcast on that channel, if the object was created just for the purpose of relaying information and is not referenced anywhere else, it should be deleted after processing inside this method.
void OnReceiveString (int channel, string value)
void SetValue (int value, int range=0)
void Subscribe (int channel)
int TranslateLevelToStatus (int level)
void Unsubscribe (int channel)
void UnsubscribeAll ()
void UpdateHUD ()
Private Attributes
float m_AntibioticsResistance = 1
float m_AutoinfectProbability = CalculateAutoinfectProbability(0)
int m_Colors [7]
float m_DieOffSpeed = 1
float m_Digestibility = 0.1
float m_Invasibility
bool m_IsClientOnly = false
int m_Key = 0
string m_Labels [7]
int m_MaxCount = 1
PluginMessageManager m_ModuleMessageManager
PluginPlayerStatus m_ModulePlayerStatus
PlayerBase m_Player
int m_Pos = 1
EStatLevels m_Potency = EStatLevels.MEDIUM
int m_Range = 0
string m_System
float m_TransferabilityAirOut
float m_TransferabilityIn
float m_TransferabilityOut
float m_Type = 0
int m_Type = 0
int m_Value
int m_ValueLast = -99999
int NUM_OF_BITS
Detailed Description
Definition at line 1 of file messagereceiverbase.c.
Constructor & Destructor Documentation
MessageReceiverBase()
void MessageReceiverBase::MessageReceiverBase () inline private
Definition at line 14 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager = PluginMessageManager.Cast(GetPlugin(PluginMessageManager));
    }
References GetPlugin(), and m_ModuleMessageManager.
Member Function Documentation
AgentBase()
void MessageReceiverBase::AgentBase () inline private
Definition at line 16 of file agentbase.c.
    {
        Init();
    }
References AgentBase::Init().
AutoinfectCheck()
bool MessageReceiverBase::AutoinfectCheck (float deltaT, PlayerBase player) inline private
Definition at line 82 of file agentbase.c.
    {
        if ( m_AutoinfectProbability == 0.0 )
            return false;
        float dice_throw = Math.RandomFloat01();
        if ( dice_throw < m_AutoinfectProbability )
        {
            return CanAutoinfectPlayer(player);
        }
        else
        {
            return false;
        }
    }
References AgentBase::CanAutoinfectPlayer(), and Math::RandomFloat01().
BitToDec()
int MessageReceiverBase::BitToDec (int mask, int index, int length) inline private
Definition at line 60 of file displayelementbase.c.
    {
        int value = mask & (GetCompareMask() << index);
        value = value >> index;
        return value;
    }
Broadcast()
void MessageReceiverBase::Broadcast (int channel) inline private
Definition at line 34 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.Broadcast(channel);
    }
References m_ModuleMessageManager.
BroadcastFloat()
void MessageReceiverBase::BroadcastFloat (int channel, float value) inline private
Definition at line 44 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.BroadcastFloat(channel, value);
    }
References m_ModuleMessageManager.
BroadcastInt()
void MessageReceiverBase::BroadcastInt (int channel, int value) inline private
Definition at line 39 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.BroadcastInt(channel, value);
    }
References m_ModuleMessageManager.
BroadcastParam()
void MessageReceiverBase::BroadcastParam (int channel, Param params) inline private
Definition at line 54 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.BroadcastParam(channel, params);
    }
References m_ModuleMessageManager.
BroadcastString()
void MessageReceiverBase::BroadcastString (int channel, string value) inline private
Definition at line 49 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.BroadcastString(channel, value);
    }
References m_ModuleMessageManager.
CalculateAutoinfectProbability()
float MessageReceiverBase::CalculateAutoinfectProbability (float userprob) inline private
Definition at line 77 of file agentbase.c.
    {
        return ( 1 - Math.Pow( 1 - userprob, ( 1 / 1200 ) ) );
    }
References Math::Pow().
CanAutoinfectPlayer()
bool MessageReceiverBase::CanAutoinfectPlayer (PlayerBase player) inline private
Definition at line 99 of file agentbase.c.
    {
        return false;
    }
DisplayElementBase()
void MessageReceiverBase::DisplayElementBase (PlayerBase player) inline private
Definition at line 17 of file displayelementbase.c.
    {
        m_System = "VirtualHud";
        m_ModulePlayerStatus = PluginPlayerStatus.Cast(GetPlugin(PluginPlayerStatus));
        m_Player = player;
        //SetMaxValue();
    }
References GetPlugin(), m_ModulePlayerStatus, m_Player, and m_System.
GetAgentType()
int MessageReceiverBase::GetAgentType () inline private
Definition at line 23 of file agentbase.c.
    {
        return m_Type;
    }
References m_Type.
GetAntibioticsResistanceEx()
float MessageReceiverBase::GetAntibioticsResistanceEx (PlayerBase player) inline private
Definition at line 57 of file agentbase.c.
    {
        return GetAntiboticsResistance();
    }
GetAntiboticsResistance()
float MessageReceiverBase::GetAntiboticsResistance () inline private
Definition at line 53 of file agentbase.c.
    {
        return m_AntibioticsResistance;
    }
GetCompareMask()
int MessageReceiverBase::GetCompareMask () inline private
Definition at line 67 of file displayelementbase.c.
    {
        int mask = Math.Pow(2, GetNumberOfBits() ) - 1;
        return mask;
    }
References Math::Pow().
GetDieOffSpeed()
float MessageReceiverBase::GetDieOffSpeed () inline private
Definition at line 48 of file agentbase.c.
    {
        return m_DieOffSpeed;
    }
GetDieOffSpeedEx()
float MessageReceiverBase::GetDieOffSpeedEx (PlayerBase player) inline private
Definition at line 28 of file agentbase.c.
    {
        return GetDieOffSpeed();
    }
GetDigestibility()
float MessageReceiverBase::GetDigestibility () inline private
Definition at line 72 of file agentbase.c.
    {
        return m_Digestibility;
    }
GetInvasibility()
float MessageReceiverBase::GetInvasibility () inline private
Definition at line 62 of file agentbase.c.
    {
        return m_Invasibility;
    }
GetInvasibilityEx()
float MessageReceiverBase::GetInvasibilityEx (PlayerBase player) inline private
Definition at line 38 of file agentbase.c.
    {
        return GetInvasibility();
    }
GetMaxCount()
int MessageReceiverBase::GetMaxCount () inline private
Definition at line 119 of file agentbase.c.
    {
        return m_MaxCount;
    }
GetName()
string MessageReceiverBase::GetName () inline private
Definition at line 124 of file agentbase.c.
    {
        return ClassName();
    }
GetNumberOfBits()
int MessageReceiverBase::GetNumberOfBits () inline private
Definition at line 41 of file displayelementbase.c.
    {
        return NUM_OF_BITS;
    }
GetPotency()
EStatLevels MessageReceiverBase::GetPotency () inline private
Definition at line 43 of file agentbase.c.
    {
        return m_Potency;
    }
GetPotencyEx()
EStatLevels MessageReceiverBase::GetPotencyEx (PlayerBase player) inline private
Definition at line 33 of file agentbase.c.
    {
        return GetPotency();
    }
GetTransferabilityAirOut()
float MessageReceiverBase::GetTransferabilityAirOut () inline private
Definition at line 114 of file agentbase.c.
    {
        return m_TransferabilityAirOut;
    }
GetTransferabilityIn()
float MessageReceiverBase::GetTransferabilityIn () inline private
Definition at line 104 of file agentbase.c.
    {
        return m_TransferabilityIn;
    }
GetTransferabilityOut()
float MessageReceiverBase::GetTransferabilityOut () inline private
Definition at line 109 of file agentbase.c.
    {
        return m_TransferabilityOut;
    }
GetType()
int MessageReceiverBase::GetType () inline private
Definition at line 73 of file displayelementbase.c.
    {
        return m_Type;
    }
References m_Type.
GetValue()
int MessageReceiverBase::GetValue () inline private
Definition at line 55 of file displayelementbase.c.
    {
        return m_Value;
    }
References m_Value.
GrowDuringAntibioticsAttack()
bool MessageReceiverBase::GrowDuringAntibioticsAttack (PlayerBase player) inline private
Definition at line 67 of file agentbase.c.
    {
        return true;//for legacy balancing reasons, set to true by default
    }
Init()
void MessageReceiverBase::Init () private
IsClientOnly()
bool MessageReceiverBase::IsClientOnly () inline private
Definition at line 26 of file displayelementbase.c.
    {
        return m_IsClientOnly;
    }
IsValueChanged()
bool MessageReceiverBase::IsValueChanged () inline private
Definition at line 31 of file displayelementbase.c.
    {
        return !(m_Value == m_ValueLast);
    }
References m_Value.
Log()
void MessageReceiverBase::Log (string message) inline private
Definition at line 60 of file messagereceiverbase.c.
    {
        Debug.Log(message,m_System);
    }
References Debug::Log(), and m_System.
OnReceive()
void MessageReceiverBase::OnReceive (int channel) inline private
Definition at line 7 of file messagereceiverbase.c.
{}
Referenced by PluginBase::Broadcast().
OnReceiveFloat()
void MessageReceiverBase::OnReceiveFloat (int channel, float value) inline private
Definition at line 9 of file messagereceiverbase.c.
{}
Referenced by PluginBase::BroadcastFloat().
OnReceiveInt()
void MessageReceiverBase::OnReceiveInt (int channel, int value) inline private
Definition at line 8 of file messagereceiverbase.c.
{}
Referenced by PluginBase::BroadcastInt().
OnReceiveParam()
void MessageReceiverBase::OnReceiveParam (int channel, Param params) inline private
This method is called when an object inheriting from this class subscribes to a channel, and a message along with an object reference is broadcast on that channel, if the object was created just for the purpose of relaying information and is not referenced anywhere else, it should be deleted after processing inside this method.
Definition at line 12 of file messagereceiverbase.c.
{}
OnReceiveString()
void MessageReceiverBase::OnReceiveString (int channel, string value) inline private
Definition at line 10 of file messagereceiverbase.c.
{}
SetValue()
void MessageReceiverBase::SetValue (int value, int range = 0) inline private
Definition at line 46 of file displayelementbase.c.
    {
        m_Value = value;
        if (range != 0 )
        {
            m_Range = range;
        }
    }
References m_Value.
Subscribe()
void MessageReceiverBase::Subscribe (int channel) inline private
Definition at line 19 of file messagereceiverbase.c.
    {
        m_ModuleMessageManager.Subscribe(this,channel);
    }
References m_ModuleMessageManager.
TranslateLevelToStatus()
int MessageReceiverBase::TranslateLevelToStatus (int level) inline private
Definition at line 78 of file displayelementbase.c.
    {
        if( level == DSLevels.WARNING )
            return 2;
        if( level == DSLevels.CRITICAL )
            return 3;
        if( level == DSLevels.BLINKING )
            return 4;
        if( level == DSLevels.EXTRA )
            return 5;
        return 1;
    }
Unsubscribe()
void MessageReceiverBase::Unsubscribe (int channel) inline private
Definition at line 24 of file messagereceiverbase.c.
    {
        if( IsPluginManagerExists() ) m_ModuleMessageManager.Unsubscribe(this,channel);
    }
References IsPluginManagerExists(), and m_ModuleMessageManager.
UnsubscribeAll()
void MessageReceiverBase::UnsubscribeAll () inline private
Definition at line 29 of file messagereceiverbase.c.
    {
        if( IsPluginManagerExists() ) m_ModuleMessageManager.UnsubscribeAll(this);
    }
References IsPluginManagerExists(), and m_ModuleMessageManager.
UpdateHUD()
void MessageReceiverBase::UpdateHUD () inline private
Definition at line 36 of file displayelementbase.c.
    {
        m_ValueLast = m_Value;
    }
References m_Value.
Member Data Documentation
m_AntibioticsResistance
float MessageReceiverBase::m_AntibioticsResistance = 1 private
Definition at line 11 of file agentbase.c.
m_AutoinfectProbability
float MessageReceiverBase::m_AutoinfectProbability = CalculateAutoinfectProbability(0) private
Definition at line 9 of file agentbase.c.
m_Colors
int MessageReceiverBase::m_Colors[7] private
Definition at line 8 of file displayelementbase.c.
m_DieOffSpeed
float MessageReceiverBase::m_DieOffSpeed = 1 private
Definition at line 14 of file agentbase.c.
m_Digestibility
float MessageReceiverBase::m_Digestibility = 0.1 private
Definition at line 7 of file agentbase.c.
m_Invasibility
float MessageReceiverBase::m_Invasibility private
Definition at line 4 of file agentbase.c.
m_IsClientOnly
bool MessageReceiverBase::m_IsClientOnly = false private
Definition at line 12 of file displayelementbase.c.
m_Key
int MessageReceiverBase::m_Key = 0 private
Definition at line 5 of file displayelementbase.c.
m_Labels
string MessageReceiverBase::m_Labels[7] private
Definition at line 9 of file displayelementbase.c.
m_MaxCount
int MessageReceiverBase::m_MaxCount = 1 private
Definition at line 8 of file agentbase.c.
m_ModuleMessageManager
PluginMessageManager MessageReceiverBase::m_ModuleMessageManager private
Definition at line 4 of file messagereceiverbase.c.
Referenced by Broadcast(), BroadcastFloat(), BroadcastInt(), BroadcastParam(), BroadcastString(), MessageReceiverBase(), Subscribe(), Unsubscribe(), and UnsubscribeAll().
m_ModulePlayerStatus
PluginPlayerStatus MessageReceiverBase::m_ModulePlayerStatus private
Definition at line 15 of file displayelementbase.c.
m_Player
PlayerBase MessageReceiverBase::m_Player private
Definition at line 13 of file displayelementbase.c.
m_Pos
int MessageReceiverBase::m_Pos = 1 private
Definition at line 10 of file displayelementbase.c.
m_Potency
EStatLevels MessageReceiverBase::m_Potency = EStatLevels.MEDIUM private
Definition at line 13 of file agentbase.c.
m_Range
int MessageReceiverBase::m_Range = 0 private
Definition at line 7 of file displayelementbase.c.
m_System
string MessageReceiverBase::m_System private
Definition at line 5 of file messagereceiverbase.c.
Referenced by Log().
m_TransferabilityAirOut
float MessageReceiverBase::m_TransferabilityAirOut private
Definition at line 10 of file agentbase.c.
m_TransferabilityIn
float MessageReceiverBase::m_TransferabilityIn private
Definition at line 5 of file agentbase.c.
m_TransferabilityOut
float MessageReceiverBase::m_TransferabilityOut private
Definition at line 6 of file agentbase.c.
m_Type [1/2]
float MessageReceiverBase::m_Type = 0 private
Definition at line 3 of file agentbase.c.
m_Type [2/2]
int MessageReceiverBase::m_Type = 0 private
Definition at line 6 of file displayelementbase.c.
m_Value
int MessageReceiverBase::m_Value private
Definition at line 3 of file displayelementbase.c.
m_ValueLast
int MessageReceiverBase::m_ValueLast = -99999 private
Definition at line 4 of file displayelementbase.c.
NUM_OF_BITS
int MessageReceiverBase::NUM_OF_BITS private
Definition at line 11 of file displayelementbase.c.