DayzKode: DebugMonitorValues Class Reference
DebugMonitorValues Class Reference
Private Member Functions
void CheckBlood ()
void CheckHealth ()
void CheckLastDamage ()
void CheckValues ()
void DebugMonitorValues (PlayerBase player)
float GetBlood ()
float GetHealth ()
string GetLastDamage ()
void Init ()
void OnRPCFloat (ParamsReadContext ctx)
void OnRPCString (ParamsReadContext ctx)
void OnScheduledTick (float deltatime)
void ReceiveValue (int value_type, Param param)
void SendValue (int value_type, Param param)
void SetLastDamage (string value)
Private Attributes
const int LAST_DAMAGE_FALL = 1
const int LAST_DAMAGE_HIT = 2
float m_BloodClient
float m_BloodMaxValue
string m_CurrentLastDamage
float m_HealthClient
float m_HealthMaxValue
float m_LastBloodUpdate
string m_LastDamageClient
string m_lastDamageUpdate
float m_LastHealthUpdate
PlayerBase m_Player
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
const float SENSITIVTY_PERCENTAGE = 1
const int TYPE_BLOOD = 2
const int TYPE_BODY_TEMP = 3
const int TYPE_HEALTH = 1
const int TYPE_LAST_DAMAGE = 5
const int TYPE_POSITION = 4
const float VALUE_CHECK_INTERVAL = 1
Detailed Description
Definition at line 1 of file debugmonitorvalues.c.
Constructor & Destructor Documentation
DebugMonitorValues()
void DebugMonitorValues::DebugMonitorValues (PlayerBase player) inline private
Definition at line 31 of file debugmonitorvalues.c.
    {
        m_Player = player;
        Init();
    }
References Init(), and m_Player.
Member Function Documentation
CheckBlood()
void DebugMonitorValues::CheckBlood () inline private
Definition at line 100 of file debugmonitorvalues.c.
    {
        float blood_current = m_Player.GetHealth("","Blood");
        float blood_normalized = blood_current / m_BloodMaxValue;
        float difference_normalized = blood_normalized - m_LastBloodUpdate;
        float diff_abs = Math.AbsFloat(difference_normalized);
        if ( diff_abs > ( SENSITIVTY_PERCENTAGE /100 ) )
        {
            Param1<float> param = new Param1<float>( blood_current );
            SendValue(TYPE_BLOOD, param);
            m_LastBloodUpdate = blood_normalized;
        }
    }
References Math::AbsFloat(), m_BloodMaxValue, m_LastBloodUpdate, m_Player, SendValue(), SENSITIVTY_PERCENTAGE, and TYPE_BLOOD.
Referenced by CheckValues().
CheckHealth()
void DebugMonitorValues::CheckHealth () inline private
Definition at line 84 of file debugmonitorvalues.c.
    {
        float health_current = m_Player.GetHealth("","Health");
        float health_normalized = health_current / m_HealthMaxValue;
        float difference_normalized = health_normalized - m_LastHealthUpdate;
        float diff_abs = Math.AbsFloat(difference_normalized);
        if ( diff_abs > ( SENSITIVTY_PERCENTAGE /100 ) )
        {
            Param1<float> param = new Param1<float>( health_current );
            SendValue(TYPE_HEALTH, param);
            m_LastHealthUpdate = health_normalized;
        }
    }
References Math::AbsFloat(), m_HealthMaxValue, m_LastHealthUpdate, m_Player, SendValue(), SENSITIVTY_PERCENTAGE, and TYPE_HEALTH.
Referenced by CheckValues().
CheckLastDamage()
void DebugMonitorValues::CheckLastDamage () inline private
Definition at line 116 of file debugmonitorvalues.c.
    {
        if (m_CurrentLastDamage != m_lastDamageUpdate)
        {
            Param1<string> param = new Param1<string>(m_CurrentLastDamage);
            SendValue(TYPE_LAST_DAMAGE, param);
            m_lastDamageUpdate = m_CurrentLastDamage;
        }
    }
References m_CurrentLastDamage, m_lastDamageUpdate, SendValue(), and TYPE_LAST_DAMAGE.
Referenced by CheckValues().
CheckValues()
void DebugMonitorValues::CheckValues () inline private
Definition at line 57 of file debugmonitorvalues.c.
    {
        CheckHealth();
        CheckBlood();
        CheckLastDamage();
    }
References CheckBlood(), CheckHealth(), and CheckLastDamage().
Referenced by OnScheduledTick().
GetBlood()
float DebugMonitorValues::GetBlood () inline private
Definition at line 64 of file debugmonitorvalues.c.
    {
        return m_BloodClient;
    }
References m_BloodClient.
Referenced by MissionBase::UpdateDebugMonitor().
GetHealth()
float DebugMonitorValues::GetHealth () inline private
Definition at line 69 of file debugmonitorvalues.c.
    {
        return m_HealthClient;
    }
References m_HealthClient.
Referenced by MissionBase::UpdateDebugMonitor().
GetLastDamage()
string DebugMonitorValues::GetLastDamage () inline private
Definition at line 74 of file debugmonitorvalues.c.
    {
        return m_LastDamageClient;
    }
References m_LastDamageClient.
Referenced by MissionBase::UpdateDebugMonitor().
Init()
void DebugMonitorValues::Init () inline private
Definition at line 37 of file debugmonitorvalues.c.
    {
        m_HealthMaxValue    = m_Player.GetMaxHealth("", "Health");
        m_BloodMaxValue     = m_Player.GetMaxHealth("", "Blood");
    }
References m_BloodMaxValue, m_HealthMaxValue, and m_Player.
Referenced by DebugMonitorValues().
OnRPCFloat()
void DebugMonitorValues::OnRPCFloat (ParamsReadContext ctx) inline private
Definition at line 184 of file debugmonitorvalues.c.
    {
        Param1<float> value = new Param1<float>(0);
        ctx.Read(CachedObjectsParams.PARAM2_INT_FLOAT);
        int value_type  = CachedObjectsParams.PARAM2_INT_FLOAT.param1;
        value.param1    = CachedObjectsParams.PARAM2_INT_FLOAT.param2;
        ReceiveValue(value_type, value);
    }
References CachedObjectsParams::PARAM2_INT_FLOAT, Serializer::Read(), and ReceiveValue().
OnRPCString()
void DebugMonitorValues::OnRPCString (ParamsReadContext ctx) inline private
Definition at line 195 of file debugmonitorvalues.c.
    {
        Param1<string> value = new Param1<string>("");
        ctx.Read(CachedObjectsParams.PARAM2_INT_STRING);
        int value_type  = CachedObjectsParams.PARAM2_INT_STRING.param1;
        value.param1    = CachedObjectsParams.PARAM2_INT_STRING.param2;
        ReceiveValue(value_type, value);
    }
References CachedObjectsParams::PARAM2_INT_STRING, Serializer::Read(), and ReceiveValue().
OnScheduledTick()
void DebugMonitorValues::OnScheduledTick (float deltatime) inline private
Definition at line 43 of file debugmonitorvalues.c.
    {
        if ( GetGame().IsClient() ) return;
        if ( !GetGame().IsDebugMonitor() ) return; // turned off in server config
        m_TimeSinceLastTick += deltatime;
        if ( m_TimeSinceLastTick > VALUE_CHECK_INTERVAL )
        {
            m_TimeSinceLastTick = 0;
            CheckValues();
        }
    }
References CheckValues(), GetGame(), m_TimeSinceLastTick, and VALUE_CHECK_INTERVAL.
ReceiveValue()
void DebugMonitorValues::ReceiveValue (int value_type, Param param) inline private
Definition at line 154 of file debugmonitorvalues.c.
    {
        GetGame().GetMission().CreateDebugMonitor();
        switch (value_type)
        {
        case DebugMonitorValues.TYPE_HEALTH:
            {
                Param1<float> valueHealth = Param1<float>.Cast( param );
                //Print("ReceivedValue health " + valueHealth.param1.ToString());
                m_HealthClient = valueHealth.param1;
            }
            break;
        case DebugMonitorValues.TYPE_BLOOD:
            {
                Param1<float> valueBlood = Param1<float>.Cast( param );
                //Print("ReceivedValue blood " + valueBlood.param1.ToString());
                m_BloodClient = valueBlood.param1;
            }
            break;
        case DebugMonitorValues.TYPE_LAST_DAMAGE:
            {
                Param1<string> valueLastDamage = Param1<string>.Cast( param );
                //Print("ReceivedValue lastdamage " + valueLastDamage.param1);
                m_LastDamageClient = valueLastDamage.param1;
            }
            break;
        }
    }
References Mission::CreateDebugMonitor(), GetGame(), CGame::GetMission(), m_BloodClient, m_HealthClient, m_LastDamageClient, TYPE_BLOOD, TYPE_HEALTH, and TYPE_LAST_DAMAGE.
Referenced by OnRPCFloat(), and OnRPCString().
SendValue()
void DebugMonitorValues::SendValue (int value_type, Param param) inline private
Definition at line 126 of file debugmonitorvalues.c.
    {
        switch(value_type)
        {
        case DebugMonitorValues.TYPE_HEALTH:
        case DebugMonitorValues.TYPE_BLOOD:
            {
                Param1<float> value_float = Param1<float>.Cast( param );
                CachedObjectsParams.PARAM2_INT_FLOAT.param1 = value_type;
                CachedObjectsParams.PARAM2_INT_FLOAT.param2 = value_float.param1;
                //Print("SendingValue type " + value_type.ToString() + " value "  + value_float.ToString());
                GetGame().RPCSingleParam(m_Player, ERPCs.RPC_DEBUG_MONITOR_FLT, CachedObjectsParams.PARAM2_INT_FLOAT, true, m_Player.GetIdentity());
            }
            break;
        case DebugMonitorValues.TYPE_LAST_DAMAGE:
            {
                Param1<string> value_string = Param1<string>.Cast( param );
                CachedObjectsParams.PARAM2_INT_STRING.param1 = value_type;
                CachedObjectsParams.PARAM2_INT_STRING.param2 = value_string.param1;
                //Print("SendingValue type " + value_type.ToString() + " value "  + value_string);
                GetGame().RPCSingleParam(m_Player, ERPCs.RPC_DEBUG_MONITOR_STR, CachedObjectsParams.PARAM2_INT_STRING, true, m_Player.GetIdentity());
            }
            break;
        }
    }
References GetGame(), m_Player, CachedObjectsParams::PARAM2_INT_FLOAT, CachedObjectsParams::PARAM2_INT_STRING, CGame::RPCSingleParam(), TYPE_BLOOD, TYPE_HEALTH, and TYPE_LAST_DAMAGE.
Referenced by CheckBlood(), CheckHealth(), and CheckLastDamage().
SetLastDamage()
void DebugMonitorValues::SetLastDamage (string value) inline private
Definition at line 79 of file debugmonitorvalues.c.
    {
        m_CurrentLastDamage = value;
    }
References m_CurrentLastDamage.
Member Data Documentation
LAST_DAMAGE_FALL
const int DebugMonitorValues::LAST_DAMAGE_FALL = 1 private
Definition at line 9 of file debugmonitorvalues.c.
LAST_DAMAGE_HIT
const int DebugMonitorValues::LAST_DAMAGE_HIT = 2 private
Definition at line 10 of file debugmonitorvalues.c.
m_BloodClient
float DebugMonitorValues::m_BloodClient private
Definition at line 27 of file debugmonitorvalues.c.
Referenced by GetBlood(), and ReceiveValue().
m_BloodMaxValue
float DebugMonitorValues::m_BloodMaxValue private
Definition at line 25 of file debugmonitorvalues.c.
Referenced by CheckBlood(), and Init().
m_CurrentLastDamage
string DebugMonitorValues::m_CurrentLastDamage private
Definition at line 18 of file debugmonitorvalues.c.
Referenced by CheckLastDamage(), and SetLastDamage().
m_HealthClient
float DebugMonitorValues::m_HealthClient private
Definition at line 28 of file debugmonitorvalues.c.
Referenced by GetHealth(), and ReceiveValue().
m_HealthMaxValue
float DebugMonitorValues::m_HealthMaxValue private
Definition at line 24 of file debugmonitorvalues.c.
Referenced by CheckHealth(), and Init().
m_LastBloodUpdate
float DebugMonitorValues::m_LastBloodUpdate private
Definition at line 21 of file debugmonitorvalues.c.
Referenced by CheckBlood().
m_LastDamageClient
string DebugMonitorValues::m_LastDamageClient private
Definition at line 29 of file debugmonitorvalues.c.
Referenced by GetLastDamage(), and ReceiveValue().
m_lastDamageUpdate
string DebugMonitorValues::m_lastDamageUpdate private
Definition at line 22 of file debugmonitorvalues.c.
Referenced by CheckLastDamage().
m_LastHealthUpdate
float DebugMonitorValues::m_LastHealthUpdate private
Definition at line 20 of file debugmonitorvalues.c.
Referenced by CheckHealth().
m_Player
PlayerBase DebugMonitorValues::m_Player private
Definition at line 15 of file debugmonitorvalues.c.
Referenced by CheckBlood(), CheckHealth(), DebugMonitorValues(), Init(), and SendValue().
m_TimeSinceLastTick
float DebugMonitorValues::m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Definition at line 16 of file debugmonitorvalues.c.
Referenced by OnScheduledTick().
SENSITIVTY_PERCENTAGE
const float DebugMonitorValues::SENSITIVTY_PERCENTAGE = 1 private
Definition at line 13 of file debugmonitorvalues.c.
Referenced by CheckBlood(), and CheckHealth().
TYPE_BLOOD
const int DebugMonitorValues::TYPE_BLOOD = 2 private
Definition at line 4 of file debugmonitorvalues.c.
Referenced by CheckBlood(), ReceiveValue(), and SendValue().
TYPE_BODY_TEMP
const int DebugMonitorValues::TYPE_BODY_TEMP = 3 private
Definition at line 5 of file debugmonitorvalues.c.
TYPE_HEALTH
const int DebugMonitorValues::TYPE_HEALTH = 1 private
Definition at line 3 of file debugmonitorvalues.c.
Referenced by CheckHealth(), ReceiveValue(), and SendValue().
TYPE_LAST_DAMAGE
const int DebugMonitorValues::TYPE_LAST_DAMAGE = 5 private
Definition at line 7 of file debugmonitorvalues.c.
Referenced by CheckLastDamage(), ReceiveValue(), and SendValue().
TYPE_POSITION
const int DebugMonitorValues::TYPE_POSITION = 4 private
Definition at line 6 of file debugmonitorvalues.c.
VALUE_CHECK_INTERVAL
const float DebugMonitorValues::VALUE_CHECK_INTERVAL = 1 private
Definition at line 12 of file debugmonitorvalues.c.
Referenced by OnScheduledTick().