DayzKode: CAContinuousWaterSlot Class Reference
CAContinuousWaterSlot Class Reference
Private Member Functions
void CAContinuousWaterSlot (float quantity_used_per_second)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_PlantThirstyness
protected Slot m_Slot
protected float m_SpentQuantityTotal
protected float m_StartQuantity
protected float m_TimeToComplete
Detailed Description
Definition at line 1 of file cacontinuouswaterslot.c.
Constructor & Destructor Documentation
CAContinuousWaterSlot()
void CAContinuousWaterSlot::CAContinuousWaterSlot (float quantity_used_per_second) inline private
Definition at line 9 of file cacontinuouswaterslot.c.
    {
        m_QuantityUsedPerSecond = quantity_used_per_second;
    }
References CAContinuousQuantity::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int CAContinuousWaterSlot::Execute (ActionData action_data) inline private
Definition at line 59 of file cacontinuouswaterslot.c.
    {
        GardenBase target_GB;
        Class.CastTo(target_GB,  action_data.m_Target.GetObject() );
        m_ItemQuantity = action_data.m_MainItem.GetQuantity();
        m_ItemMaxQuantity = action_data.m_MainItem.GetQuantityMax();
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        if ( m_ItemQuantity <= 0 )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_Slot && m_SpentQuantity < m_ItemQuantity )
            {
                m_SpentQuantity += m_QuantityUsedPerSecond * action_data.m_Player.GetDeltaT();
                float water = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( m_SpentQuantity, m_Action.GetSpecialtyWeight(), true );
                m_Slot.GiveWater( water );
                m_SpentQuantityTotal += m_SpentQuantity;
                CalcAndSetQuantity( action_data );
                m_SpentQuantity = 0;
                return UA_PROCESSING;
            }
            else
            {
                CalcAndSetQuantity( action_data );
                OnCompletePogress( action_data );
                return UA_FINISHED;
            }
        }
    }
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, CAContinuousQuantity::m_ItemMaxQuantity, CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, ActionData::m_Player, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Slot, CAContinuousQuantity::m_SpentQuantity, m_SpentQuantityTotal, ActionData::m_Target, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousWaterSlot::GetProgress () inline private
Definition at line 100 of file cacontinuouswaterslot.c.
    {
        if ( m_ItemQuantity <= 0 )
            return 1;
        float progress = -(m_SpentQuantityTotal / m_StartQuantity);
        return progress;
    }
References CAContinuousQuantity::m_ItemQuantity, m_SpentQuantityTotal, and m_StartQuantity.
Setup()
override void CAContinuousWaterSlot::Setup (ActionData action_data) inline private
Definition at line 14 of file cacontinuouswaterslot.c.
    {
        GardenBase target_GB;
        if ( Class.CastTo(target_GB, action_data.m_Target.GetObject()) )
        {
            m_SpentQuantity = 0;
            m_StartQuantity = action_data.m_MainItem.GetQuantity();
            if ( !m_SpentUnits )
            {
                m_SpentUnits = new Param1<float>(0);
            }
            else
            {
                m_SpentUnits.param1 = 0;
            }
            if ( action_data.m_MainItem )
                m_ItemQuantity = action_data.m_MainItem.GetQuantity();
            if ( target_GB )
            {
                array<string> selections = new array<string>;
                target_GB.GetActionComponentNameList(action_data.m_Target.GetComponentIndex(), selections);
                for (int s = 0; s < selections.Count(); s++)
                {
                    string selection = selections[s];
                    m_Slot = target_GB.GetSlotBySelection( selection );
                    if (m_Slot)
                        break;
                }
                m_PlantThirstyness = m_Slot.GetWaterUsage() - m_Slot.GetWater();
            }
            m_TimeToComplete = (Math.Min(m_PlantThirstyness,m_ItemQuantity))/m_QuantityUsedPerSecond;
            if (m_TimeToComplete <= 0.1) // Division by zero prevention
            {
                m_TimeToComplete = 0.1;
            }
        }
    }
References Class::CastTo(), CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, m_PlantThirstyness, CAContinuousQuantity::m_QuantityUsedPerSecond, m_Slot, CAContinuousQuantity::m_SpentQuantity, CAContinuousQuantity::m_SpentUnits, m_StartQuantity, ActionData::m_Target, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_PlantThirstyness
protected float CAContinuousWaterSlot::m_PlantThirstyness private
Definition at line 3 of file cacontinuouswaterslot.c.
Referenced by Setup().
m_Slot
protected Slot CAContinuousWaterSlot::m_Slot private
Definition at line 7 of file cacontinuouswaterslot.c.
Referenced by Execute(), and Setup().
m_SpentQuantityTotal
protected float CAContinuousWaterSlot::m_SpentQuantityTotal private
Definition at line 5 of file cacontinuouswaterslot.c.
Referenced by Execute(), and GetProgress().
m_StartQuantity
protected float CAContinuousWaterSlot::m_StartQuantity private
Definition at line 6 of file cacontinuouswaterslot.c.
Referenced by GetProgress(), and Setup().
m_TimeToComplete
protected float CAContinuousWaterSlot::m_TimeToComplete private
Definition at line 4 of file cacontinuouswaterslot.c.
Referenced by Setup().