DayzKode: BleedingSourcesManagerBase Class Reference
BleedingSourcesManagerBase Class Reference
Private Member Functions
void ActivateAllBS ()
protected void AddBleedingSource (int bit)
override protected void AddBleedingSource (int bit)
protected void AddBleedingSourceEx (int bit, eBleedingSourceType type=eBleedingSourceType.NORMAL, int context=0)
bool AttemptAddBleedingSource (int component)
bool AttemptAddBleedingSourceBySelection (string selection_name)
bool AttemptAddBleedingSourceDirectly (int bit, eBleedingSourceType type=eBleedingSourceType.NORMAL, int context=0)
void BleedingSourcesManagerBase (PlayerBase player)
protected bool CanAddBleedingSource (int bit)
void CleanDebug ()
void DebugActivateBleedingSource (int source)
void DisplayDebug ()
void DisplayVisualDebug ()
protected int GetBitFromSelectionID (int id)
protected int GetBitFromSelectionName (string name)
int GetBleedingSourceActiveTime (int bit)
int GetBleedingSourceBitsByInvLocation (int inv_location)
int GetBleedingSourceCountRemote ()
protected BleedingSourceZone GetBleedingSourceMeta (int bit)
int GetBleedingSourcesCount ()
set< int > GetBleedingSourcesLocations ()
eBleedingSourceType GetBleedingSourceType (int bit)
protected BleedingSourceZone GetBleedingSourceZone (int bit)
int GetFreeBleedingSourceBitsByInvLocation (int inv_location)
int GetMostSignificantBleedingSource ()
int GetRegisteredSourcesCount ()
protected string GetSelectionNameFromBit (int bit)
int GetStorageVersion ()
protected void Init ()
override protected void Init ()
void OnBleedingBitsUpdate (int old_mask, int new_mask)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnStoreSave (ParamsWriteContext ctx)
void OnTick (float delta_time)
void OnUpdate ()
void OnVariablesSynchronized (int current_bits)
void ProcessHit (float damage, EntityAI source, int component, string zone, string ammo, vector modelPos)
protected void RegisterBleedingZone (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect")
protected void RegisterBleedingZoneEx (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect", int inv_location=0)
override protected void RegisterBleedingZoneEx (string name, int max_time, string bone="", vector orientation="0 0 0", vector offset="0 0 0", float flow_modifier=1, string particle_name="BleedingSourceEffect", int inv_location=0)
void Reload ()
void RemoveAllSources ()
void RemoveAnyBleedingSource ()
protected bool RemoveBleedingSource (int bit)
override protected bool RemoveBleedingSource (int bit)
void RemoveMostSignificantBleedingSource ()
void RemoveMostSignificantBleedingSourceEx (ItemBase item)
void RequestDeletion (int bit)
void SetBleedingSourceActiveTime (int bit, int time)
void SetBleedingSourceType (int bit, eBleedingSourceType type)
void SetBloodLoss (bool status)
void SetDiag (bool value)
protected void SetItem (ItemBase item)
void ~BleedingSourcesManagerServer ()
Private Attributes
protected int m_Bit
int m_BitOffset = 0
ref map< int, string > m_BitToFireGeom = new map<int, string>
int m_BleedingBits
ref map< int, ref BleedingSource > m_BleedingSources = new map<int, ref BleedingSource>
ref map< int, int > m_BleedingSourcesByLocation = new map<int, int>
ref map< string, ref BleedingSourceZone > m_BleedingSourceZone = new map<string, ref BleedingSourceZone>
ref array< int > m_DeleteList = new array<int>
bool m_DisableBloodLoss = false
bool m_EnableHitIndication = false
ItemBase m_Item
PlayerBase m_Player
Shape m_Point
bool m_ShowDiag
bool m_ShowingDiag
float m_Tick
const int STORAGE_VERSION = 103
const float TICK_INTERVAL_SEC = 3
Static Private Attributes
static ref set< int > m_BleedingSourcesLocationsList = new set<int>
static ref map< int, int > m_BleedingSourcesZonesMaskByLocation = new map<int, int>
Detailed Description
Definition at line 1 of file bleedingsourcesmanagerbase.c.
Constructor & Destructor Documentation
BleedingSourcesManagerBase()
void BleedingSourcesManagerBase::BleedingSourcesManagerBase (PlayerBase player) inline private
Definition at line 15 of file bleedingsourcesmanagerbase.c.
    {
        m_Player = player;
        Init();
    }
References Init(), and m_Player.
~BleedingSourcesManagerServer()
void BleedingSourcesManagerBase::~BleedingSourcesManagerServer () inline private
Definition at line 261 of file bleedingsourcesmanagerserver.c.
    {
        if (m_Player && !m_Player.IsAlive())
            RemoveAllSources();
    }
References m_Player, and RemoveAllSources().
Member Function Documentation
ActivateAllBS()
void BleedingSourcesManagerBase::ActivateAllBS () inline private
Definition at line 137 of file bleedingsourcesmanagerserver.c.
    {
        for(int i = 0; i < m_BleedingSourceZone.Count(); i++)
        {
            int bit = m_BleedingSourceZone.GetElement(i).GetBit();
            if( CanAddBleedingSource(bit) )
            {
                AddBleedingSource(bit);
            }
        }
    }
References AddBleedingSource(), and CanAddBleedingSource().
AddBleedingSource() [1/2]
protected void BleedingSourcesManagerBase::AddBleedingSource (int bit) inline private
Definition at line 244 of file bleedingsourcesmanagerbase.c.
    {
        BleedingSourceZone bsz = GetBleedingSourceMeta(bit);
        vector orientation = bsz.GetOrientation();
        vector offset = bsz.GetOffset();
        string bone_name =  bsz.GetBoneName();
        float flow_modifier = bsz.GetFlowModifier();
        int max_time = bsz.GetMaxTime();
        string particle_name = bsz.GetParticleName();
        int inventory_loc = bsz.GetInvLocation();
        m_BleedingSourcesByLocation.Set(inventory_loc, (m_BleedingSourcesByLocation.Get(inventory_loc) | bit));
        m_BleedingSources.Insert(bit, new BleedingSource(m_Player, bit,bone_name, orientation, offset, max_time, flow_modifier, particle_name) );
        m_Player.OnBleedingSourceAdded();
    }
References BleedingSource(), GetBleedingSourceMeta(), BleedingSourceZone::GetBoneName(), BleedingSourceZone::GetFlowModifier(), BleedingSourceZone::GetInvLocation(), BleedingSourceZone::GetMaxTime(), BleedingSourceZone::GetOffset(), BleedingSourceZone::GetOrientation(), BleedingSourceZone::GetParticleName(), m_BleedingSources, m_BleedingSourcesByLocation, and m_Player.
Referenced by ActivateAllBS(), AddBleedingSourceEx(), AttemptAddBleedingSource(), AttemptAddBleedingSourceBySelection(), DebugActivateBleedingSource(), OnBleedingBitsUpdate(), OnStoreLoad(), and Reload().
AddBleedingSource() [2/2]
override protected void BleedingSourcesManagerBase::AddBleedingSource (int bit) inline private
Definition at line 25 of file bleedingsourcesmanagerserver.c.
    {
        m_Player.SetBleedingBits(m_Player.GetBleedingBits() | bit );
        super.AddBleedingSource(bit);
    }
References m_Player.
AddBleedingSourceEx()
protected void BleedingSourcesManagerBase::AddBleedingSourceEx (int bit, eBleedingSourceType type = eBleedingSourceType.NORMAL, int context = 0) inline private
Definition at line 238 of file bleedingsourcesmanagerbase.c.
    {
        AddBleedingSource(bit);
        m_BleedingSources.Get(bit).SetType(type);
    }
References AddBleedingSource(), and m_BleedingSources.
Referenced by AttemptAddBleedingSourceDirectly().
AttemptAddBleedingSource()
bool BleedingSourcesManagerBase::AttemptAddBleedingSource (int component) inline private
Definition at line 184 of file bleedingsourcesmanagerbase.c.
    {
        int bit = GetBitFromSelectionID(component);
        if ( bit == 0 )
        {
            return false;
        }
        if ( CanAddBleedingSource(bit) )
        {
            AddBleedingSource(bit);
            return true;
        }
        return false;
    }
References AddBleedingSource(), CanAddBleedingSource(), component, and GetBitFromSelectionID().
Referenced by ProcessHit().
AttemptAddBleedingSourceBySelection()
bool BleedingSourcesManagerBase::AttemptAddBleedingSourceBySelection (string selection_name) inline private
Definition at line 202 of file bleedingsourcesmanagerbase.c.
    {
        selection_name.ToLower();
        int bit = GetBitFromSelectionName(selection_name);
        if ( bit == 0 )
        {
            return false;
        }
        if ( CanAddBleedingSource(bit) )
        {
            AddBleedingSource(bit);
            return true;
        }
        return false;
    }
References AddBleedingSource(), CanAddBleedingSource(), GetBitFromSelectionName(), and string::ToLower().
AttemptAddBleedingSourceDirectly()
bool BleedingSourcesManagerBase::AttemptAddBleedingSourceDirectly (int bit, eBleedingSourceType type = eBleedingSourceType.NORMAL, int context = 0) inline private
Definition at line 221 of file bleedingsourcesmanagerbase.c.
    {
        if(CanAddBleedingSource(bit))
        {
            AddBleedingSourceEx(bit, type, context);
            return true;
        }
        return false;
    }
References AddBleedingSourceEx(), and CanAddBleedingSource().
CanAddBleedingSource()
protected bool BleedingSourcesManagerBase::CanAddBleedingSource (int bit) inline private
Definition at line 232 of file bleedingsourcesmanagerbase.c.
    {
        if (!GetBleedingSourceMeta(bit)) return false;
        return ((m_Player.GetBleedingBits() & bit) == 0 );
    }
References GetBleedingSourceMeta(), and m_Player.
Referenced by ActivateAllBS(), AttemptAddBleedingSource(), AttemptAddBleedingSourceBySelection(), AttemptAddBleedingSourceDirectly(), DebugActivateBleedingSource(), and OnStoreLoad().
CleanDebug()
void BleedingSourcesManagerBase::CleanDebug () inline private
Definition at line 212 of file bleedingsourcesmanagerremote.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("Bleeding Sources", 50, 50);
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), and DbgUI::EndCleanupScope().
Referenced by OnUpdate().
DebugActivateBleedingSource()
void BleedingSourcesManagerBase::DebugActivateBleedingSource (int source) inline private
Definition at line 177 of file bleedingsourcesmanagerserver.c.
    {
        RemoveAllSources();
        if(source >= m_BleedingSourceZone.Count() || !m_BleedingSourceZone.GetElement(source)) return;
        int bit = m_BleedingSourceZone.GetElement(source).GetBit();
        if( bit && CanAddBleedingSource(bit) )
        {
            AddBleedingSource(bit);
        }
    }
References AddBleedingSource(), CanAddBleedingSource(), and RemoveAllSources().
DisplayDebug()
void BleedingSourcesManagerBase::DisplayDebug () inline private
Definition at line 158 of file bleedingsourcesmanagerremote.c.
    {
        m_ShowingDiag = true;
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("Bleeding Sources", 50, 50);
        int pow = 0;
        for(int i = 0; i < BIT_INT_SIZE ; i++)
        {
            int bit = Math.Pow(2, pow);
            pow++;
            if( (m_BleedingBits & bit) != 0)
            {
                BleedingSourceZone bsz = GetBleedingSourceMeta(bit);
                string name = GetSelectionNameFromBit(bit);
                string slot_name =  InventorySlots.GetSlotName(bsz.GetInvLocation());
                DbgUI.Text(name + "| slot name: "+ slot_name);
            }
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), BIT_INT_SIZE, DbgUI::End(), DbgUI::EndCleanupScope(), GetBleedingSourceMeta(), BleedingSourceZone::GetInvLocation(), GetSelectionNameFromBit(), InventorySlots::GetSlotName(), name, Math::Pow(), and DbgUI::Text().
Referenced by OnUpdate().
DisplayVisualDebug()
void BleedingSourcesManagerBase::DisplayVisualDebug () inline private
Definition at line 185 of file bleedingsourcesmanagerremote.c.
    {
        /*
        if(m_Point)
        {
            Debug.RemoveShape(m_Point);
        }
        int boneIdx = m_Player.GetBoneIndexByName("LeftKneeExtra");
        int pointIdx = m_Player.GetMemoryPointIndex("lknee");
        vector posLS = DayZPlayerUtils.GetMemoryPointPositionBoneRelative(m_Player, boneIdx, pointIdx);
        vector pTm[4];
        m_Player.GetBoneTransformMS(boneIdx, pTm);
        vector posMS = posLS.Multiply4(pTm);
        vector pos = m_Player.ModelToWorld(posMS);
        m_Point = Debug.DrawSphere(pos, 0.1, COLOR_RED);
        */
        for(int i = 0; i < m_BleedingSources.Count(); i++)
        {
            m_BleedingSources.GetElement(i).DrawDebugShape();
        }
    }
Referenced by OnUpdate().
GetBitFromSelectionID()
protected int BleedingSourcesManagerBase::GetBitFromSelectionID (int id) inline private
Definition at line 97 of file bleedingsourcesmanagerbase.c.
    {
        CachedObjectsArrays.ARRAY_STRING.Clear();
        m_Player.GetActionComponentNameList(id, CachedObjectsArrays.ARRAY_STRING, "fire");
        for (int i = 0; i < CachedObjectsArrays.ARRAY_STRING.Count(); i++)
        {
            /*
            string name = CachedObjectsArrays.ARRAY_STRING.Get(i);
            PrintString(name);
            */
            int bit = GetBitFromSelectionName(CachedObjectsArrays.ARRAY_STRING.Get(i));
            if (  bit !=0 )
            {
                return bit;
            }
        }
        return 0;
    }
References CachedObjectsArrays::ARRAY_STRING, GetBitFromSelectionName(), and m_Player.
Referenced by AttemptAddBleedingSource().
GetBitFromSelectionName()
protected int BleedingSourcesManagerBase::GetBitFromSelectionName (string name) inline private
Definition at line 170 of file bleedingsourcesmanagerbase.c.
    {
        if (!m_BleedingSourceZone.Get(name))
        {
            return 0;
        }
        return m_BleedingSourceZone.Get(name).GetBit();
    }
References m_BleedingSourceZone, and name.
Referenced by AttemptAddBleedingSourceBySelection(), and GetBitFromSelectionID().
GetBleedingSourceActiveTime()
int BleedingSourcesManagerBase::GetBleedingSourceActiveTime (int bit) inline private
Definition at line 261 of file bleedingsourcesmanagerbase.c.
    {
        int time = -1;
        if (m_BleedingSources.Contains(bit))
        {
            time = m_BleedingSources.Get(bit).GetActiveTime();
        }
        return time;
    }
References m_BleedingSources.
Referenced by OnStoreSave().
GetBleedingSourceBitsByInvLocation()
int BleedingSourcesManagerBase::GetBleedingSourceBitsByInvLocation (int inv_location) inline private
Definition at line 77 of file bleedingsourcesmanagerbase.c.
    {
        if(m_BleedingSourcesByLocation.Contains(inv_location))
        {
            return m_BleedingSourcesByLocation.Get(inv_location);
        }
        return 0;
    }
References m_BleedingSourcesByLocation.
Referenced by GetFreeBleedingSourceBitsByInvLocation().
GetBleedingSourceCountRemote()
int BleedingSourcesManagerBase::GetBleedingSourceCountRemote () inline private
Definition at line 94 of file bleedingsourcesmanagerremote.c.
    {
        int bleeding_source_count = 0;
        int pow = 0;
        for(int i = 0; i < BIT_INT_SIZE ; i++)
        {
            int bit = Math.Pow(2, pow);
            pow++;
            if( (m_BleedingBits & bit) != 0)
            {
                bleeding_source_count++;
            }
        }
        return bleeding_source_count;
    }
References BIT_INT_SIZE, and Math::Pow().
GetBleedingSourceMeta()
protected BleedingSourceZone BleedingSourcesManagerBase::GetBleedingSourceMeta (int bit) inline private
Definition at line 117 of file bleedingsourcesmanagerbase.c.
    {
        return m_BleedingSourceZone.Get(GetSelectionNameFromBit(bit));
    }
References GetSelectionNameFromBit(), and m_BleedingSourceZone.
Referenced by AddBleedingSource(), CanAddBleedingSource(), DisplayDebug(), GetMostSignificantBleedingSource(), and RemoveBleedingSource().
GetBleedingSourcesCount()
int BleedingSourcesManagerBase::GetBleedingSourcesCount () inline private
Definition at line 309 of file bleedingsourcesmanagerbase.c.
    {
        return m_BleedingSources.Count();
    }
References m_BleedingSources.
GetBleedingSourcesLocations()
set< int > BleedingSourcesManagerBase::GetBleedingSourcesLocations () inline private
Definition at line 70 of file bleedingsourcesmanagerbase.c.
    {
        return m_BleedingSourcesLocationsList;
    }
References m_BleedingSourcesLocationsList.
GetBleedingSourceType()
eBleedingSourceType BleedingSourcesManagerBase::GetBleedingSourceType (int bit) inline private
Definition at line 286 of file bleedingsourcesmanagerbase.c.
    {
        if (m_BleedingSources.Contains(bit))
        {
            return m_BleedingSources.Get(bit).GetType();
        }
        return -1;
    }
References m_BleedingSources.
Referenced by OnStoreSave().
GetBleedingSourceZone()
protected BleedingSourceZone BleedingSourcesManagerBase::GetBleedingSourceZone (int bit) inline private
Definition at line 10 of file bleedingsourcesmanagerserver.c.
    {
        return m_BleedingSourceZone.Get(GetSelectionNameFromBit(bit));
    }
References GetSelectionNameFromBit().
GetFreeBleedingSourceBitsByInvLocation()
int BleedingSourcesManagerBase::GetFreeBleedingSourceBitsByInvLocation (int inv_location) inline private
Definition at line 87 of file bleedingsourcesmanagerbase.c.
    {
        if(m_BleedingSourcesZonesMaskByLocation.Contains(inv_location))
        {
            return (~m_BleedingSourcesZonesMaskByLocation.Get(inv_location) & GetBleedingSourceBitsByInvLocation(inv_location)) | (m_BleedingSourcesZonesMaskByLocation.Get(inv_location) & ~GetBleedingSourceBitsByInvLocation(inv_location));//xor
        }
        return 0;
    }
References GetBleedingSourceBitsByInvLocation(), and m_BleedingSourcesZonesMaskByLocation.
GetMostSignificantBleedingSource()
int BleedingSourcesManagerBase::GetMostSignificantBleedingSource () inline private
Definition at line 85 of file bleedingsourcesmanagerserver.c.
    {
        int bleeding_sources_bits = m_Player.GetBleedingBits();
        float highest_flow;
        int highest_flow_bit;
        int bit_offset;
        for(int i = 0; i < BIT_INT_SIZE; i++)
        {
            int bit = 1 << bit_offset;
            if( (bit & bleeding_sources_bits) != 0 )
            {
                BleedingSourceZone meta = GetBleedingSourceMeta(bit);
                if(meta)
                {
                    if( meta.GetFlowModifier() > highest_flow )
                    {
                        highest_flow = meta.GetFlowModifier();
                        highest_flow_bit = bit;
                        //Print(meta.GetSelectionName());
                    }
                }
            }
            bit_offset++;
        }
        return highest_flow_bit;
    }
References BIT_INT_SIZE, GetBleedingSourceMeta(), BleedingSourceZone::GetFlowModifier(), and m_Player.
Referenced by RemoveMostSignificantBleedingSource().
GetRegisteredSourcesCount()
int BleedingSourcesManagerBase::GetRegisteredSourcesCount () inline private
Definition at line 122 of file bleedingsourcesmanagerbase.c.
    {
        return m_BitOffset;
    }
References m_BitOffset.
GetSelectionNameFromBit()
protected string BleedingSourcesManagerBase::GetSelectionNameFromBit (int bit) inline private
Definition at line 179 of file bleedingsourcesmanagerbase.c.
    {
        return m_BitToFireGeom.Get(bit);
    }
References m_BitToFireGeom.
Referenced by DisplayDebug(), GetBleedingSourceMeta(), and GetBleedingSourceZone().
GetStorageVersion()
int BleedingSourcesManagerBase::GetStorageVersion () inline private
Definition at line 15 of file bleedingsourcesmanagerserver.c.
    {
        return STORAGE_VERSION;
    }
References STORAGE_VERSION.
Init() [1/2]
protected void BleedingSourcesManagerBase::Init () inline private
Definition at line 21 of file bleedingsourcesmanagerbase.c.
    {
        //dmgZone_head
        RegisterBleedingZoneEx("Head",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 0 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.MASK);
        //dmgZone_torso
        RegisterBleedingZoneEx("Neck", PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL,"", "-180 0 0" , "0.02 -0.05 0.05", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.HEADGEAR);
        RegisterBleedingZoneEx("Pelvis",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -135 0" , "0 0.12 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("Spine",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 55 0" , "0 -0.1 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("Spine1",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 155 0" , "0 -0.1 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("Spine2",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 55 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("Spine3",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 155 0" , "0 -0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, "BleedingSourceEffect",InventorySlots.BODY);
        //dmgZone_leftArm
        RegisterBleedingZoneEx("LeftShoulder",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect", InventorySlots.BODY);
        RegisterBleedingZoneEx("LeftArm", PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "","0 90 90" , "0 -0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("LeftArmRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("LeftForeArm",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        //dmgZone_rightArm
        RegisterBleedingZoneEx("RightShoulder",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("RightArm", PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL,"", "0 -90 0" , "0 0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("RightArmRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        RegisterBleedingZoneEx("RightForeArm",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.05 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.BODY);
        //dmgZone_leftHand
        RegisterBleedingZoneEx("LeftForeArmRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0.1 0 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffectLight", InventorySlots.GLOVES);
        //dmgZone_rightHand
        RegisterBleedingZoneEx("RightForeArmRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "-0.1 0 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffectLight", InventorySlots.GLOVES);
        //dmgZone_leftLeg
        RegisterBleedingZoneEx("LeftLeg",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("LeftLegRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("LeftUpLeg",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.12 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("LeftUpLegRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM , "BleedingSourceEffect",InventorySlots.LEGS);
        //dmgZone_rightLeg
        RegisterBleedingZoneEx("RightLeg",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.06 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("RightLegRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("RightUpLeg",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.12 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        RegisterBleedingZoneEx("RightUpLegRoll",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.06 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, "BleedingSourceEffect",InventorySlots.LEGS);
        //dmgZone_leftFoot
        RegisterBleedingZoneEx("LeftFoot",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 180 0" , "0 0 0.035", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffectLight", InventorySlots.LEGS);
        RegisterBleedingZoneEx("LeftToeBase",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 -90 0" , "0 0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffect",InventorySlots.FEET);
        //dmgZone_rightFoot
        RegisterBleedingZoneEx("RightFoot",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 0 0" , "0 0 -0.035", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffectLight", InventorySlots.LEGS);
        RegisterBleedingZoneEx("RightToeBase",PlayerConstants.BLEEDING_SOURCE_DURATION_NORMAL, "", "0 90 0" , "0 -0.07 0", PlayerConstants.BLEEDING_SOURCE_FLOW_MODIFIER_LOW, "BleedingSourceEffect", InventorySlots.FEET);
    }
References PlayerConstants::BLEEDING_SOURCE_DURATION_NORMAL, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_HIGH, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_LOW, PlayerConstants::BLEEDING_SOURCE_FLOW_MODIFIER_MEDIUM, and RegisterBleedingZoneEx().
Referenced by BleedingSourcesManagerBase(), and Reload().
Init() [2/2]
override protected void BleedingSourcesManagerBase::Init () inline private
Definition at line 10 of file bleedingsourcesmanagerremote.c.
    {
        super.Init();
        if (GetGame().GetMission().GetEffectWidgets()/* && m_Player.IsControlledPlayer()*/)
        {
            Param3<bool,int,float> par = new Param3<bool,int,float>(true,0,0);
            GetGame().GetMission().GetEffectWidgets().RegisterGameplayEffectData(EffectWidgetsTypes.BLEEDING_LAYER,par);
        }
    }
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), and GameplayEffectWidgets_base::RegisterGameplayEffectData().
OnBleedingBitsUpdate()
void BleedingSourcesManagerBase::OnBleedingBitsUpdate (int old_mask, int new_mask) inline private
Definition at line 68 of file bleedingsourcesmanagerremote.c.
    {
        for(int i = 0; i < 32; i++)
        {
            int compare_bit = 1 << i;
            int new_compare_result_bit = compare_bit & new_mask;
            int old_compare_result_bit = compare_bit & old_mask;
            if( new_compare_result_bit )
            {
                if( !(new_compare_result_bit & old_mask))
                {
                    //a different active bit in the new mask
                    AddBleedingSource(new_compare_result_bit);
                }
            }
            else
            {
                if( new_compare_result_bit != old_compare_result_bit )
                {
                    RemoveBleedingSource(old_compare_result_bit);
                }
            }
        }
    }
References AddBleedingSource(), and RemoveBleedingSource().
Referenced by OnVariablesSynchronized().
OnStoreLoad()
bool BleedingSourcesManagerBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 218 of file bleedingsourcesmanagerserver.c.
    {
        int active_bits;
        if(!ctx.Read(active_bits))
        {
            return false;
        }
        int bit_offset = 0;
        for(int i = 0; i < BIT_INT_SIZE; i++)
        {
            int bit = 1 << bit_offset;
            if( (bit & active_bits) != 0 && CanAddBleedingSource(bit))
            {
                AddBleedingSource(bit);
                int active_time = 0;
                if(!ctx.Read(active_time))
                {
                    return false;
                }
                else
                {
                    SetBleedingSourceActiveTime(bit,active_time);
                }
                if( version >= 121 )//type was added in this version
                {
                    eBleedingSourceType type = eBleedingSourceType.NORMAL;
                    if (!ctx.Read(type))
                    {
                        return false;
                    }
                    else
                    {
                        SetBleedingSourceType(bit,type);
                    }
                }
            }
            bit_offset++;
        }
        return true;
    }
References AddBleedingSource(), BIT_INT_SIZE, CanAddBleedingSource(), Serializer::Read(), SetBleedingSourceActiveTime(), and SetBleedingSourceType().
OnStoreSave()
void BleedingSourcesManagerBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 196 of file bleedingsourcesmanagerserver.c.
    {
        //int count = m_BleedingSources.Count();
        int active_bits = m_Player.GetBleedingBits();
        ctx.Write(active_bits);
        int bit_offset = 0;
        for(int i = 0; i < BIT_INT_SIZE; i++)
        {
            int bit = 1 << bit_offset;
            if( (bit & active_bits) != 0 )
            {
                int active_time = GetBleedingSourceActiveTime(bit);
                eBleedingSourceType type = GetBleedingSourceType(bit);
                ctx.Write(active_time);
                ctx.Write(type);
            }
            bit_offset++;
        }
    }
References BIT_INT_SIZE, GetBleedingSourceActiveTime(), GetBleedingSourceType(), m_Player, and Serializer::Write().
OnTick()
void BleedingSourcesManagerBase::OnTick (float delta_time) inline private
Definition at line 115 of file bleedingsourcesmanagerserver.c.
    {
        m_Tick += delta_time;
        if( m_Tick > TICK_INTERVAL_SEC )
        {
            while( m_DeleteList.Count() > 0 )
            {
                RemoveBleedingSource(m_DeleteList.Get(0));
                m_DeleteList.Remove(0);
            }
            float blood_scale = Math.InverseLerp(PlayerConstants.BLOOD_THRESHOLD_FATAL, PlayerConstants.BLEEDING_LOW_PRESSURE_BLOOD, m_Player.GetHealth( "GlobalHealth", "Blood" ));
            blood_scale = Math.Clamp( blood_scale, PlayerConstants.BLEEDING_LOW_PRESSURE_MIN_MOD, 1 );
            for(int i = 0; i < m_BleedingSources.Count(); i++)
            {
                m_BleedingSources.GetElement(i).OnUpdateServer( m_Tick, blood_scale, m_DisableBloodLoss );
            }
            m_Tick = 0;
        }
    }
References PlayerConstants::BLEEDING_LOW_PRESSURE_BLOOD, PlayerConstants::BLEEDING_LOW_PRESSURE_MIN_MOD, PlayerConstants::BLOOD_THRESHOLD_FATAL, Math::Clamp(), Math::InverseLerp(), m_Player, m_Tick, and RemoveBleedingSource().
OnUpdate()
void BleedingSourcesManagerBase::OnUpdate () inline private
Definition at line 142 of file bleedingsourcesmanagerremote.c.
    {
        #ifndef NO_GUI
        if(m_ShowDiag)
        {
            DisplayDebug();
            DisplayVisualDebug();
        }
        else if( m_ShowingDiag )
        {
            CleanDebug();
            m_ShowingDiag = false;
        }
        #endif
    }
References CleanDebug(), DisplayDebug(), and DisplayVisualDebug().
OnVariablesSynchronized()
void BleedingSourcesManagerBase::OnVariablesSynchronized (int current_bits) inline private
Definition at line 32 of file bleedingsourcesmanagerremote.c.
    {
        if (current_bits != m_BleedingBits)
        {
            if(m_BleedingBits == 0)
            {
                m_Player.OnBleedingBegin();
            }
            OnBleedingBitsUpdate(m_BleedingBits, current_bits);
            m_BleedingBits = current_bits;
            if(m_BleedingBits == 0)
            {
                m_Player.OnBleedingEnd();
            }
        }
    }
References m_Player, and OnBleedingBitsUpdate().
ProcessHit()
void BleedingSourcesManagerBase::ProcessHit (float damage, EntityAI source, int component, string zone, string ammo, vector modelPos) inline private
Definition at line 150 of file bleedingsourcesmanagerserver.c.
    {
        float dmg_max = m_Player.GetMaxHealth(zone, "Blood");
        float dmg = damage;
        float bleed_threshold = GetGame().ConfigGetFloat( "CfgAmmo " + ammo + " DamageApplied " + "bleedThreshold" );
        bleed_threshold = Math.Clamp(bleed_threshold,0,1);
        //Print("dmg_max = " + dmg_max);
        //Print("dmg = " + dmg);
        //Print("bleed_threshold = " + bleed_threshold);
        //hackerino for zombino:
        if (source && source.IsZombie())
        {
            int chance = Math.RandomInt(0,100); //Cast die, probability comes from Blood damage in infected ammo config
            if (chance <= damage)
            {
                AttemptAddBleedingSource(component);
            }
        }
        else if ( dmg > (dmg_max * (1 - bleed_threshold)) )
        {
            AttemptAddBleedingSource(component);
            //Print("BLEEDING");
        }
    }
References AttemptAddBleedingSource(), Math::Clamp(), component, CGame::ConfigGetFloat(), GetGame(), m_Player, and Math::RandomInt().
RegisterBleedingZone()
protected void BleedingSourcesManagerBase::RegisterBleedingZone (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect") inline private
Definition at line 155 of file bleedingsourcesmanagerbase.c.
    {
        RegisterBleedingZoneEx(name, max_time, bone, orientation, offset, flow_modifier, particle_name);
    }
References name, and RegisterBleedingZoneEx().
RegisterBleedingZoneEx() [1/2]
protected void BleedingSourcesManagerBase::RegisterBleedingZoneEx (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect", int inv_location = 0) inline private
Definition at line 127 of file bleedingsourcesmanagerbase.c.
    {
        if ( m_BitOffset == BIT_INT_SIZE)
        {
            Error("Too many bleeding sources, max is "+BIT_INT_SIZE.ToString());
        }
        else
        {
            name.ToLower();
            //PrintString(name);
            //int bit = Math.Pow(2, m_BitOffset);
            m_Bit = 1 << m_BitOffset;
            //PrintString(bit.ToString());
            string bone_name = bone;
            if (bone_name == "")
            {
                bone_name = name;
            }
            m_BleedingSourceZone.Insert(name, new BleedingSourceZone(name, m_Bit, offset, orientation, bone_name, max_time, flow_modifier, particle_name));
            m_BleedingSourceZone.Get(name).SetInvLocation(inv_location);
            m_BitToFireGeom.Insert(m_Bit, name);
            m_BleedingSourcesZonesMaskByLocation.Set( inv_location, m_BleedingSourcesZonesMaskByLocation.Get(inv_location) | m_Bit);//set a bit to 1 to already existing bitmask for that location
            m_BleedingSourcesLocationsList.Insert(inv_location);
            m_BitOffset++;
        }
    }
References BIT_INT_SIZE, Error(), m_Bit, m_BitOffset, m_BitToFireGeom, m_BleedingSourcesLocationsList, m_BleedingSourcesZonesMaskByLocation, m_BleedingSourceZone, name, and string::ToLower().
Referenced by Init(), and RegisterBleedingZone().
RegisterBleedingZoneEx() [2/2]
override protected void BleedingSourcesManagerBase::RegisterBleedingZoneEx (string name, int max_time, string bone = "", vector orientation = "0 0 0", vector offset = "0 0 0", float flow_modifier = 1, string particle_name = "BleedingSourceEffect", int inv_location = 0) inline private
Definition at line 21 of file bleedingsourcesmanagerremote.c.
    {
        super.RegisterBleedingZoneEx(name,max_time,bone,orientation,offset,flow_modifier,particle_name,inv_location);
        if (GetGame().GetMission().GetEffectWidgets()/* && m_Player.IsControlledPlayer()*/)
        {
            Param3<bool,int,float> par = new Param3<bool,int,float>(false,m_Bit,flow_modifier);
            GetGame().GetMission().GetEffectWidgets().RegisterGameplayEffectData(EffectWidgetsTypes.BLEEDING_LAYER,par);
        }
    }
References Mission::GetEffectWidgets(), GetGame(), CGame::GetMission(), m_Bit, name, and GameplayEffectWidgets_base::RegisterGameplayEffectData().
Reload()
void BleedingSourcesManagerBase::Reload () inline private
Definition at line 49 of file bleedingsourcesmanagerremote.c.
    {
        m_BleedingSourceZone.Clear();
        m_BitOffset = 0;
        Init();
        int bit_offset = 0;
        for(int i = 0; i < BIT_INT_SIZE; i++)
        {
            int bit = 1 << bit_offset;
            bit_offset++;
            if( (bit & m_BleedingBits) != 0 )
            {
                RemoveBleedingSource(bit);
                AddBleedingSource(bit);
            }
        }
    }
References AddBleedingSource(), BIT_INT_SIZE, Init(), and RemoveBleedingSource().
RemoveAllSources()
void BleedingSourcesManagerBase::RemoveAllSources () inline private
Definition at line 160 of file bleedingsourcesmanagerbase.c.
    {
        //int count = m_BleedingSources.Count();
        while (m_BleedingSources.Count() > 0 )
        {
            int bit = m_BleedingSources.GetKey(0);
            RemoveBleedingSource(bit);
        }
    }
References m_BleedingSources, and RemoveBleedingSource().
Referenced by DebugActivateBleedingSource(), and ~BleedingSourcesManagerServer().
RemoveAnyBleedingSource()
void BleedingSourcesManagerBase::RemoveAnyBleedingSource () inline private
Definition at line 64 of file bleedingsourcesmanagerserver.c.
    {
        int bleeding_sources_bits = m_Player.GetBleedingBits();
        int rightmost_bit = bleeding_sources_bits & (-bleeding_sources_bits);
        RemoveBleedingSource(rightmost_bit);
    }
References m_Player, and RemoveBleedingSource().
RemoveBleedingSource() [1/2]
protected bool BleedingSourcesManagerBase::RemoveBleedingSource (int bit) inline private
Definition at line 295 of file bleedingsourcesmanagerbase.c.
    {
        if (m_BleedingSources.Contains(bit))
        {
            BleedingSourceZone bsz = GetBleedingSourceMeta(bit);
            int inventory_loc = bsz.GetInvLocation();
            m_BleedingSourcesByLocation.Set(inventory_loc, (m_BleedingSourcesByLocation.Get(inventory_loc) & ~bit));//deactivate the bit
            m_BleedingSources.Remove(bit);
            m_Player.OnBleedingSourceRemovedEx(m_Item);
            return true;
        }
        return false;
    }
References GetBleedingSourceMeta(), BleedingSourceZone::GetInvLocation(), m_BleedingSources, m_BleedingSourcesByLocation, m_Item, and m_Player.
Referenced by OnBleedingBitsUpdate(), OnTick(), Reload(), RemoveAllSources(), RemoveAnyBleedingSource(), and RemoveMostSignificantBleedingSource().
RemoveBleedingSource() [2/2]
override protected bool BleedingSourcesManagerBase::RemoveBleedingSource (int bit) inline private
Definition at line 31 of file bleedingsourcesmanagerserver.c.
    {
        if(!super.RemoveBleedingSource(bit))
        {
            Error("Failed to remove bleeding source:" + bit);
        }
        int inverse_bit_mask = ~bit;
        m_Player.SetBleedingBits(m_Player.GetBleedingBits() & inverse_bit_mask );
        //infection moved here to allow proper working in singleplayer
        float chanceToInfect;
        if (m_Item)
        {
            chanceToInfect = m_Item.GetInfectionChance(0, CachedObjectsParams.PARAM1_BOOL);
        }
        else
        {
            chanceToInfect = PlayerConstants.BLEEDING_SOURCE_CLOSE_INFECTION_CHANCE;
        }
        float diceRoll = Math.RandomFloat01();
        if (diceRoll < chanceToInfect)
        {
            m_Player.InsertAgent(eAgents.WOUND_AGENT);
        }
        m_Item = null;//reset, so that next call, if induced by self-healing, will have no item
        return true;
    }
References PlayerConstants::BLEEDING_SOURCE_CLOSE_INFECTION_CHANCE, Error(), ItemBase::GetInfectionChance(), m_Item, m_Player, CachedObjectsParams::PARAM1_BOOL, and Math::RandomFloat01().
RemoveMostSignificantBleedingSource()
void BleedingSourcesManagerBase::RemoveMostSignificantBleedingSource () inline private
Definition at line 72 of file bleedingsourcesmanagerserver.c.
    {
        int bit = GetMostSignificantBleedingSource();
        if( bit != 0)
            RemoveBleedingSource(bit);
    }
References GetMostSignificantBleedingSource(), and RemoveBleedingSource().
Referenced by RemoveMostSignificantBleedingSourceEx().
RemoveMostSignificantBleedingSourceEx()
void BleedingSourcesManagerBase::RemoveMostSignificantBleedingSourceEx (ItemBase item) inline private
Definition at line 79 of file bleedingsourcesmanagerserver.c.
    {
        SetItem(item);
        RemoveMostSignificantBleedingSource();
    }
References RemoveMostSignificantBleedingSource(), and SetItem().
RequestDeletion()
void BleedingSourcesManagerBase::RequestDeletion (int bit) inline private
Definition at line 20 of file bleedingsourcesmanagerserver.c.
    {
        m_DeleteList.Insert(bit);
    }
SetBleedingSourceActiveTime()
void BleedingSourcesManagerBase::SetBleedingSourceActiveTime (int bit, int time) inline private
Definition at line 271 of file bleedingsourcesmanagerbase.c.
    {
        if (m_BleedingSources.Contains(bit))
        {
            m_BleedingSources.Get(bit).SetActiveTime(time);
        }
    }
References m_BleedingSources.
Referenced by OnStoreLoad().
SetBleedingSourceType()
void BleedingSourcesManagerBase::SetBleedingSourceType (int bit, eBleedingSourceType type) inline private
Definition at line 279 of file bleedingsourcesmanagerbase.c.
    {
        if (m_BleedingSources.Contains(bit))
        {
            m_BleedingSources.Get(bit).SetType(type);
        }
    }
References m_BleedingSources.
Referenced by OnStoreLoad().
SetBloodLoss()
void BleedingSourcesManagerBase::SetBloodLoss (bool status) inline private
Definition at line 191 of file bleedingsourcesmanagerserver.c.
    {
        m_DisableBloodLoss = status;
    }
SetDiag()
void BleedingSourcesManagerBase::SetDiag (bool value) inline private
Definition at line 112 of file bleedingsourcesmanagerremote.c.
    {
        m_ShowDiag = value;
        return;
        int boneIdx = m_Player.GetBoneIndexByName("RightArmExtra");
        if ( boneIdx != -1 )
        {
          Object linkedObject = GetGame().CreateObject("Ammo_ArrowBolt", "0 0 0");
        //linkedObject.SetPosition("0 1 0");
        //linkedObject.SetOrientation("0 90 0");
          /*
          Set local space transform for linked object
          */
            BleedingSourceEffect eff = new BleedingSourceEffect();
            eff.SetAutodestroy(true);
            SEffectManager.PlayInWorld( eff, "0 0 0" );
            Particle p = eff.GetParticle();
            //p.SetOrientation("0 90 0");
            m_Player.AddChild(p, boneIdx);
             m_Player.AddChild(linkedObject, boneIdx);
        }
    }
References CGame::CreateObject(), GetGame(), EffectParticle::GetParticle(), m_Player, and SEffectManager::PlayInWorld().
SetItem()
protected void BleedingSourcesManagerBase::SetItem (ItemBase item) inline private
Definition at line 64 of file bleedingsourcesmanagerbase.c.
    {
        m_Item = item;
    }
References m_Item.
Referenced by RemoveMostSignificantBleedingSourceEx().
Member Data Documentation
m_Bit
protected int BleedingSourcesManagerBase::m_Bit private
Definition at line 12 of file bleedingsourcesmanagerbase.c.
Referenced by RegisterBleedingZoneEx().
m_BitOffset
int BleedingSourcesManagerBase::m_BitOffset = 0 private
Definition at line 13 of file bleedingsourcesmanagerbase.c.
Referenced by GetRegisteredSourcesCount(), and RegisterBleedingZoneEx().
m_BitToFireGeom
ref map<int, string> BleedingSourcesManagerBase::m_BitToFireGeom = new map<int, string> private
Definition at line 11 of file bleedingsourcesmanagerbase.c.
Referenced by GetSelectionNameFromBit(), and RegisterBleedingZoneEx().
m_BleedingBits
int BleedingSourcesManagerBase::m_BleedingBits private
Definition at line 4 of file bleedingsourcesmanagerremote.c.
m_BleedingSources
ref map<int, ref BleedingSource> BleedingSourcesManagerBase::m_BleedingSources = new map<int, ref BleedingSource> private
Definition at line 3 of file bleedingsourcesmanagerbase.c.
Referenced by AddBleedingSource(), AddBleedingSourceEx(), GetBleedingSourceActiveTime(), GetBleedingSourcesCount(), GetBleedingSourceType(), RemoveAllSources(), RemoveBleedingSource(), SetBleedingSourceActiveTime(), and SetBleedingSourceType().
m_BleedingSourcesByLocation
ref map<int, int> BleedingSourcesManagerBase::m_BleedingSourcesByLocation = new map<int, int> private
Definition at line 5 of file bleedingsourcesmanagerbase.c.
Referenced by AddBleedingSource(), GetBleedingSourceBitsByInvLocation(), and RemoveBleedingSource().
m_BleedingSourcesLocationsList
ref set<int> BleedingSourcesManagerBase::m_BleedingSourcesLocationsList = new set<int> static private
Definition at line 7 of file bleedingsourcesmanagerbase.c.
Referenced by GetBleedingSourcesLocations(), and RegisterBleedingZoneEx().
m_BleedingSourcesZonesMaskByLocation
ref map<int, int> BleedingSourcesManagerBase::m_BleedingSourcesZonesMaskByLocation = new map<int, int> static private
Definition at line 6 of file bleedingsourcesmanagerbase.c.
Referenced by GetFreeBleedingSourceBitsByInvLocation(), and RegisterBleedingZoneEx().
m_BleedingSourceZone
ref map<string, ref BleedingSourceZone> BleedingSourcesManagerBase::m_BleedingSourceZone = new map<string, ref BleedingSourceZone> private
Definition at line 4 of file bleedingsourcesmanagerbase.c.
Referenced by GetBitFromSelectionName(), GetBleedingSourceMeta(), and RegisterBleedingZoneEx().
m_DeleteList
ref array<int> BleedingSourcesManagerBase::m_DeleteList = new array<int> private
Definition at line 6 of file bleedingsourcesmanagerserver.c.
m_DisableBloodLoss
bool BleedingSourcesManagerBase::m_DisableBloodLoss = false private
Definition at line 5 of file bleedingsourcesmanagerserver.c.
m_EnableHitIndication
bool BleedingSourcesManagerBase::m_EnableHitIndication = false private
Definition at line 8 of file bleedingsourcesmanagerremote.c.
m_Item
ItemBase BleedingSourcesManagerBase::m_Item private
Definition at line 8 of file bleedingsourcesmanagerbase.c.
Referenced by RemoveBleedingSource(), and SetItem().
m_Player
PlayerBase BleedingSourcesManagerBase::m_Player private
Definition at line 9 of file bleedingsourcesmanagerbase.c.
Referenced by AddBleedingSource(), BleedingSourcesManagerBase(), CanAddBleedingSource(), GetBitFromSelectionID(), and RemoveBleedingSource().
m_Point
Shape BleedingSourcesManagerBase::m_Point private
Definition at line 7 of file bleedingsourcesmanagerremote.c.
m_ShowDiag
bool BleedingSourcesManagerBase::m_ShowDiag private
Definition at line 5 of file bleedingsourcesmanagerremote.c.
m_ShowingDiag
bool BleedingSourcesManagerBase::m_ShowingDiag private
Definition at line 6 of file bleedingsourcesmanagerremote.c.
m_Tick
float BleedingSourcesManagerBase::m_Tick private
Definition at line 4 of file bleedingsourcesmanagerserver.c.
STORAGE_VERSION
const int BleedingSourcesManagerBase::STORAGE_VERSION = 103 private
Definition at line 8 of file bleedingsourcesmanagerserver.c.
Referenced by GetStorageVersion().
TICK_INTERVAL_SEC
const float BleedingSourcesManagerBase::TICK_INTERVAL_SEC = 3 private
Definition at line 3 of file bleedingsourcesmanagerserver.c.