DayzKode: UIPopupScript Class Reference
UIPopupScript Class Reference
Private Member Functions
void AddItemToClipboard (TextListboxWidget text_listbox_widget)
void ChangeConfigFilter ()
void ClearHierarchy ()
void CollapseHierarchy (int row)
void ExpandHierarchy (int row)
void FindInHierarchy (string class_name)
string GetCurrentPositionName ()
protected PluginSceneManager GetSceneEditor ()
bool OnChange (Widget w, int x, int y, bool finished)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnChange (Widget w, int x, int y, bool finished)
override bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
void OnClose ()
override void OnClose ()
override void OnClose ()
void OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
override void OnOpen (Param param)
void OnUpdate ()
void OnUpdate ()
protected UIPopupScript PopupBack ()
protected UIPopupScript PopupOpen (int popup_id, Param param)
void RenderVariables (int row)
void ResetSliders ()
void ResetSliders ()
void SetDeleteName (string scene_name)
void SetLabelText (string text)
void SetRenameName (string rename_name)
void Show (bool show)
void UIPopupScript (Widget wgt)
void UIPopupScriptConfigs (Widget wgt)
void UIPopupScriptEditorSettings (Widget wgt)
void UIPopupScriptInitScript (Widget wgt)
void UIPopupScriptNotify (Widget wgt)
void UIPopupScriptPositionManager (Widget wgt)
void UIPopupScriptPresetNew (Widget wgt)
void UIPopupScriptPresetRename (Widget wgt)
void UIPopupScriptSceneDelete (Widget wgt)
void UIPopupScriptSceneManager (Widget wgt)
void UIPopupScriptSceneNew (Widget wgt)
void UIPopupScriptSceneRename (Widget wgt)
void UIPopupScriptSceneSettings (Widget wgt)
void UpdateSceneList ()
void UpdateSliderFog ()
void UpdateSliderFog ()
void UpdateSliderOvercast ()
void UpdateSliderOvercast ()
void UpdateSliderRain ()
void UpdateSliderRain ()
void UpdateSliderStartDay (int month, int day)
void UpdateSliderStartDay (int month, int day)
void UpdateSliderStartTime (int hour, int minute)
void UpdateSliderStartTime (int hour, int minute)
void UpdateSliderWindForce ()
void UpdateSliderWindForce ()
void ~UIPopupScriptSceneManager ()
void ~UIPopupScriptSceneSettings ()
Private Attributes
private ButtonWidget m_BtnCancel
private ButtonWidget m_BtnCopyToClipboard
private ButtonWidget m_BtnNo
private ButtonWidget m_BtnOk
private ButtonWidget m_BtnRun
private ButtonWidget m_BtnSave
private ButtonWidget m_BtnSceneDelete
private ButtonWidget m_BtnSceneDuplicate
private ButtonWidget m_BtnSceneLoad
private ButtonWidget m_BtnSceneNew
private ButtonWidget m_BtnSceneRename
private ButtonWidget m_BtnYes
private ButtonWidget m_CancelButton
private PluginConfigDebugProfileFixed m_ConfigDebugProfileFixed
private TextListboxWidget m_ConfigHierarchyTextListbox
private TextListboxWidget m_ConfigVariablesTextListbox
private int m_CurrDay
private float m_CurrFog
private int m_CurrHour
private int m_CurrMinute
private int m_CurrMonth
private float m_CurrOvercast
private float m_CurrRain
private float m_CurrWindForce
private int m_CurrYear
private string m_DeleteScene
private EditBoxWidget m_Editbox
private EditBoxWidget m_EdxRotationDelta
private TextListboxWidget m_LstListScenes
private TextListboxWidget m_LstPositionList
private MultilineEditBoxWidget m_MedxInitScript
private PluginConfigViewer m_ModuleConfigViewer
private PluginSceneManager m_ModuleSceneManager
private EditBoxWidget m_ObjectConfigFilter
private int m_OrigDay
private float m_OrigFog
private int m_OrigHour
private int m_OrigMinute
private int m_OrigMonth
private float m_OrigOvercast
private float m_OrigRain
private float m_OrigWindForce
private int m_OrigYear
private string m_RenameName
private SceneObject m_SceneObject
private int m_SceneObjectIndex
private SliderWidget m_SldFog
private SliderWidget m_SldOvercast
private SliderWidget m_SldRain
private SliderWidget m_SldStartDay
private SliderWidget m_SldStartTime
private SliderWidget m_SldWindForce
private ButtonWidget m_TeleportButton
private EditBoxWidget m_TxtCurrentX
private EditBoxWidget m_TxtCurrentY
private TextWidget m_TxtFogValue
private TextWidget m_TxtLabel
private TextWidget m_TxtOvercastValue
private TextWidget m_TxtRainValue
private EditBoxWidget m_TxtSelectedX
private EditBoxWidget m_TxtSelectedY
private TextWidget m_TxtStartDayValue
private TextWidget m_TxtStartTimeValue
private TextWidget m_TxtWeatherTime
private TextWidget m_TxtWindForceValue
protected Widget m_WgtRoot
private CheckBoxWidget m_WgtTglSavePlayerPos
private CheckBoxWidget m_WgtTglSeleHighlight
Static Private Attributes
static private const int m_DaysInMonth [12] = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 }
Detailed Description
Definition at line 1 of file uipopupscript.c.
Constructor & Destructor Documentation
UIPopupScript()
void UIPopupScript::UIPopupScript (Widget wgt) inline private
Definition at line 6 of file uipopupscript.c.
    {
        m_WgtRoot = wgt;
    }
References m_WgtRoot.
~UIPopupScriptSceneManager()
void UIPopupScript::~UIPopupScriptSceneManager () inline private
Definition at line 87 of file uipopupscriptscenemanager.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnUpdate);
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
~UIPopupScriptSceneSettings()
void UIPopupScript::~UIPopupScriptSceneSettings () inline private
Definition at line 72 of file uipopupscriptscenesettings.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnUpdate);
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
Member Function Documentation
AddItemToClipboard()
void UIPopupScript::AddItemToClipboard (TextListboxWidget text_listbox_widget) inline private
Definition at line 41 of file uipopupscriptconfigs.c.
    {
        int selected_row_index = text_listbox_widget.GetSelectedRow();
        if ( selected_row_index != -1 )
        {
            string item_name;
            text_listbox_widget.GetItemText( selected_row_index, 0, item_name );
            GetGame().CopyToClipboard( item_name );
        }
    }
References CGame::CopyToClipboard(), and GetGame().
Referenced by OnClick().
ChangeConfigFilter()
void UIPopupScript::ChangeConfigFilter () inline private
Definition at line 23 of file uipopupscriptconfigs.c.
    {
        if ( m_ObjectConfigFilter.GetText() == "" )
        {
            ClearHierarchy();
        }
        else
        {
            FindInHierarchy( m_ObjectConfigFilter.GetText() );
        }
    }
References ClearHierarchy(), and FindInHierarchy().
Referenced by OnChange().
ClearHierarchy()
void UIPopupScript::ClearHierarchy () inline private
Definition at line 155 of file uipopupscriptconfigs.c.
    {
        // config hierarchy
        // string config_path = "configfile CfgVehicles APC";
        // string config_path = "";
        m_ConfigHierarchyTextListbox.ClearItems();
        m_ConfigVariablesTextListbox.ClearItems();
        ref TStringArray base_classes = new TStringArray;
        Debug.GetBaseConfigClasses( base_classes );
        string config_path = "configfile";
        ref TStringArray variables = m_ModuleConfigViewer.GetConfigHierarchy( config_path );
        for ( int i = 0; i < variables.Count(); i++ )
        {
            string variable = variables.Get(i);
            for ( int j = 0; j < base_classes.Count(); j++ )
            {
                if ( variable == base_classes.Get(j) )
                {
                    string new_config_path = ( config_path + " " + variable ).Trim();
                    m_ConfigHierarchyTextListbox.AddItem( "+ " + variable, new ConfigParams( false, variable, 0, new_config_path, 0 ), 0);
                }
            }
        }
    }
References string::Get(), and Debug::GetBaseConfigClasses().
Referenced by ChangeConfigFilter(), and OnOpen().
CollapseHierarchy()
void UIPopupScript::CollapseHierarchy (int row) inline private
Definition at line 109 of file uipopupscriptconfigs.c.
    {
        if( row <= -1 && row >= m_ConfigHierarchyTextListbox.GetNumItems() )
        {
            return;
        }
        ConfigParams config_params;
        ConfigParams config_params_next;
        m_ConfigHierarchyTextListbox.GetItemData( row, 0, config_params );
        m_ConfigHierarchyTextListbox.GetItemData( row + 1, 0, config_params_next );
        int deep = config_params.param5;
        int deep_next = config_params_next.param5;
        int max_count = m_ConfigHierarchyTextListbox.GetNumItems();
        int remove_lines_count = 0;
        // Print(max_count);
        for ( int i = row + 1; i < max_count; i++)
        {
            if ( deep < deep_next && i <= max_count )
            {
                remove_lines_count = remove_lines_count + 1;
                m_ConfigHierarchyTextListbox.GetItemData( i, 0, config_params_next );
                deep_next = config_params_next.param5;
            }
        }
        // remove remove_lines_count lines from row
        // remove_lines_count = remove_lines_count - 1;
        for ( i = 1; i < remove_lines_count; i++ )
        {
            int x = row + 1;
            if ( x < max_count )
            {
                m_ConfigHierarchyTextListbox.RemoveRow( x );
            }
        }
        string offset = "";
        for ( i = 0; i < deep; i++)
        {
            offset = offset + "  ";
        }
        m_ConfigHierarchyTextListbox.SetItem( row, offset + "+ " + config_params.param2, new ConfigParams( false, config_params.param2, 0, config_params.param4, deep ), 0 );
    }
References x.
Referenced by OnClick().
ExpandHierarchy()
void UIPopupScript::ExpandHierarchy (int row) inline private
Definition at line 69 of file uipopupscriptconfigs.c.
    {
        if( row <= -1 && row >= m_ConfigHierarchyTextListbox.GetNumItems() )
        {
            return;
        }
        ref TStringArray variables;
        // get current row data
        ConfigParams config_params;
        m_ConfigHierarchyTextListbox.GetItemData( row, 0, config_params );
        string config_path = config_params.param4;
        int deep = config_params.param5;
        string offset = "";
        for ( int i = 0; i < deep; i++)
        {
            offset = offset + "  ";
        }
        // change selected node
        variables = m_ModuleConfigViewer.GetConfigHierarchy( config_path );
        int childrens_count = variables.Count();
        m_ConfigHierarchyTextListbox.SetItem( row, offset + "- " + config_params.param2, new ConfigParams( true, config_params.param2, childrens_count, config_path, deep ), 0 );
        offset = offset + "  ";
        // render childrens
        deep = deep + 1;
        childrens_count = 0;
        for ( i = variables.Count() - 1; i >= 0; i-- )
        {
            string new_config_path = ( config_path + " " + variables.Get(i) ).Trim();
            m_ConfigHierarchyTextListbox.AddItem( offset + "+ " + variables.Get(i), new ConfigParams( false, variables.Get(i), childrens_count, new_config_path, deep  ), 0, (row + 1) );
        }
    }
References string::Get().
Referenced by OnClick().
FindInHierarchy()
void UIPopupScript::FindInHierarchy (string class_name) inline private
Definition at line 184 of file uipopupscriptconfigs.c.
    {
        m_ConfigHierarchyTextListbox.ClearItems();
        m_ConfigVariablesTextListbox.ClearItems();
        class_name.ToLower(  );
        string config_base_path = "configfile";
        ref TStringArray base_classes = new TStringArray;
        Debug.GetBaseConfigClasses( base_classes );
        string filter_lower = class_name;
        filter_lower.ToLower(  );
        ref TStringArray filters = new TStringArray;
        filter_lower.Split( " ", filters );
        for ( int i = 0; i < base_classes.Count(); i++ )
        {
            string config_path = config_base_path + " " + base_classes.Get(i);
            ref TStringArray variables = m_ModuleConfigViewer.GetConfigHierarchy( config_path );
            for ( int j = 0; j < variables.Count(); j++ )
            {
                string variable = variables.Get(j);
                string variable_lower = variable;
                variable_lower.ToLower(  );
                for ( int k = 0; k < filters.Count(); k++ )
                {
                    if ( variable_lower.Contains(filters.Get(k)))
                    {
                        string new_config_path = ( config_path + " " + variable ).Trim();
                        m_ConfigHierarchyTextListbox.AddItem( "+ " + variable, new ConfigParams( false, variable, 0, new_config_path, 0 ), 0);
                        break;
                    }
                }
            }
        }
    }
References class_name, string::Contains(), string::Get(), Debug::GetBaseConfigClasses(), string::Split(), and string::ToLower().
Referenced by ChangeConfigFilter().
GetCurrentPositionName()
string UIPopupScript::GetCurrentPositionName () inline private
Definition at line 82 of file uipopupscriptpositionmanager.c.
    {
        if ( m_LstPositionList.GetSelectedRow() != -1 )
        {
            string position_name;
            m_LstPositionList.GetItemText( m_LstPositionList.GetSelectedRow(), 0, position_name );
            return position_name;
        }
        return "";
    }
Referenced by OnItemSelected().
GetSceneEditor()
protected PluginSceneManager UIPopupScript::GetSceneEditor () inline private
Definition at line 55 of file uipopupscript.c.
    {
        PluginSceneManager m = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
        return m;
    }
References GetPlugin().
OnChange() [1/5]
bool UIPopupScript::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 29 of file uipopupscript.c.
    {
        return false;
    }
OnChange() [2/5]
override bool UIPopupScript::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 225 of file uipopupscriptconfigs.c.
    {
        super.OnChange( w, x, y, finished );
        if ( w == m_ObjectConfigFilter )
        {
            ChangeConfigFilter();
        }
        return false;
    }
References ChangeConfigFilter(), x, and y.
OnChange() [3/5]
override bool UIPopupScript::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 63 of file uipopupscripteditorsettings.c.
    {
        if ( w == m_EdxRotationDelta )
        {
            int angle = m_EdxRotationDelta.GetText().ToInt();
            if ( angle > 0 )
            {
                m_ModuleSceneManager.SetRotationAngle( angle );
            }
            return true;
        }
        return false;
    }
OnChange() [4/5]
override bool UIPopupScript::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 205 of file uipopupscriptscenemanager.c.
    {
        if ( w == m_SldStartTime )
        {
            float slider_value_start_time = m_SldStartTime.GetCurrent() * 0.01;
            float start_time_f = slider_value_start_time * 1439;
            int start_time = start_time_f;
            m_CurrHour = start_time / 60;
            m_CurrMinute = start_time % 60;
            UpdateSliderStartTime( m_CurrHour, m_CurrMinute );
            GetGame().GetWorld().SetDate( m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute );
            return true;
        }
        else if ( w == m_SldStartDay )
        {
            float slider_value_start_day = m_SldStartDay.GetCurrent();
            float start_day_f = slider_value_start_day * 3.64 + 1;
            int start_day = start_day_f;
            for ( int i = 0; i < 12; i++ )
            {
                int days = m_DaysInMonth[i];
                if ( start_day <= days )
                {
                    m_CurrMonth = i+1;
                    m_CurrDay = start_day;
                    break;
                }
                else
                {
                    start_day -= days;
                }
            }
            UpdateSliderStartDay( m_CurrMonth, m_CurrDay );
            GetGame().GetWorld().SetDate( m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute );
            return true;
        }
        else if ( w == m_SldOvercast )
        {
            m_CurrOvercast = m_SldOvercast.GetCurrent() * 0.01;
            GetGame().GetWeather().GetOvercast().Set( m_CurrOvercast, 0, 1000 );
            UpdateSliderOvercast();
            return true;
        }
        else if ( w == m_SldRain )
        {
            m_CurrRain = m_SldRain.GetCurrent() * 0.01;
            GetGame().GetWeather().GetRain().Set( m_CurrRain, 0, 1000 );
            UpdateSliderRain();
            return true;
        }
        else if ( w == m_SldFog )
        {
            m_CurrFog = m_SldFog.GetCurrent() * 0.01;
            GetGame().GetWeather().GetFog().Set( m_CurrFog, 0, 1000 );
            UpdateSliderFog();
            return true;
        }
        else if ( w == m_SldWindForce )
        {
            float wind_slider = m_SldWindForce.GetCurrent() * 0.01;
            m_CurrWindForce = GetGame().GetWeather().GetWindMaximumSpeed() * wind_slider;
            GetGame().GetWeather().SetWindSpeed( m_CurrWindForce );
            UpdateSliderWindForce();
            return true;
        }
        return false;
    }
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), WeatherPhenomenon::Set(), World::SetDate(), Weather::SetWindSpeed(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
OnChange() [5/5]
override bool UIPopupScript::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 115 of file uipopupscriptscenesettings.c.
    {
        if ( w == m_SldStartTime )
        {
            float slider_value_start_time = m_SldStartTime.GetCurrent() * 0.01;
            float start_time_f = slider_value_start_time * 1439;
            int start_time = start_time_f;
            m_CurrHour = start_time / 60;
            m_CurrMinute = start_time % 60;
            UpdateSliderStartTime( m_CurrHour, m_CurrMinute );
            GetGame().GetWorld().SetDate( m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute );
            return true;
        }
        else if ( w == m_SldStartDay )
        {
            float slider_value_start_day = m_SldStartDay.GetCurrent();
            float start_day_f = slider_value_start_day * 3.64 + 1;
            int start_day = start_day_f;
            for ( int i = 0; i < 12; i++ )
            {
                int days = m_DaysInMonth[i];
                if ( start_day <= days )
                {
                    m_CurrMonth = i+1;
                    m_CurrDay = start_day;
                    break;
                }
                else
                {
                    start_day -= days;
                }
            }
            UpdateSliderStartDay( m_CurrMonth, m_CurrDay );
            GetGame().GetWorld().SetDate( m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute );
            return true;
        }
        else if ( w == m_SldOvercast )
        {
            UpdateSliderOvercast();
            m_CurrOvercast = m_SldOvercast.GetCurrent() * 0.01;
            GetGame().GetWeather().GetOvercast().Set( m_CurrOvercast, 0, 1000 );
            return true;
        }
        else if ( w == m_SldRain )
        {
            UpdateSliderRain();
            m_CurrRain = m_SldRain.GetCurrent() * 0.01;
            GetGame().GetWeather().GetRain().Set( m_CurrRain, 0, 1000 );
            return true;
        }
        else if ( w == m_SldFog )
        {
            UpdateSliderFog();
            m_CurrFog = m_SldFog.GetCurrent() * 0.01;
            GetGame().GetWeather().GetFog().Set( m_CurrFog, 0, 1000 );
            return true;
        }
        else if ( w == m_SldWindForce )
        {
            UpdateSliderWindForce();
            m_CurrWindForce = m_SldWindForce.GetCurrent() * 0.01;
            //GetGame().GetWeather().SetWindSpeed( m_CurrWindForce );
            return true;
        }
        return false;
    }
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), WeatherPhenomenon::Set(), World::SetDate(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
OnClick() [1/13]
bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 24 of file uipopupscript.c.
    {
        return false;
    }
OnClick() [2/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 237 of file uipopupscriptconfigs.c.
    {
        super.OnClick( w, x, y, button );
        if ( w == m_BtnOk )
        {
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCopyToClipboard )
        {
            AddItemToClipboard( m_ConfigVariablesTextListbox );
            return true;
        }
        else if ( w == m_ConfigHierarchyTextListbox )
        {
            int objects_row_index = m_ConfigHierarchyTextListbox.GetSelectedRow();
            if ( objects_row_index > -1 && objects_row_index < m_ConfigHierarchyTextListbox.GetNumItems() )
            {
                ConfigParams config_params;
                m_ConfigHierarchyTextListbox.GetItemData( objects_row_index, 0, config_params );
                if ( config_params.param1 == false )
                {
                    ExpandHierarchy( objects_row_index );
                }
                else
                {
                    CollapseHierarchy( objects_row_index );
                }
                RenderVariables( objects_row_index );
            }
            return true;
        }
        return false;
    }
References AddItemToClipboard(), CollapseHierarchy(), ExpandHierarchy(), PopupBack(), RenderVariables(), x, and y.
OnClick() [3/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 38 of file uipopupscripteditorsettings.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_WgtTglSeleHighlight )
        {
            m_ModuleSceneManager.SetDrawSelection(m_WgtTglSeleHighlight.IsChecked());
        }
        else if ( w == m_WgtTglSavePlayerPos )
        {
            m_ModuleSceneManager.SetLoadPlayerPos(m_WgtTglSavePlayerPos.IsChecked());
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References PopupBack(), x, and y.
OnClick() [4/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 53 of file uipopupscriptinitscript.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnRun )
        {
            if ( m_SceneObject != NULL )
            {
                string text_run;
                m_MedxInitScript.GetText( text_run );
                m_ModuleSceneManager.ExecuteEnforceScript( m_SceneObjectIndex, m_SceneObject, text_run );
            }
        }
        else if ( w == m_BtnSave )
        {
            if ( m_SceneObject != NULL )
            {
                string text_script;
                m_MedxInitScript.GetText( text_script );
                m_SceneObject.SetInitScript( text_script );
            }
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References PopupBack(), SceneObject::SetInitScript(), x, and y.
OnClick() [5/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file uipopupscriptnotify.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnOk )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References PopupBack(), x, and y.
OnClick() [6/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 55 of file uipopupscriptpositionmanager.c.
    {
        if ( w == m_TeleportButton )
        {
            float pos_x = m_TxtSelectedX.GetText().ToFloat();
            float pos_z = m_TxtSelectedY.GetText().ToFloat();
            PluginSceneManager.GetInstance().SelectedObjectSetPosX( pos_x );
            PluginSceneManager.GetInstance().SelectedObjectSetPosZ( pos_z );
            PopupBack();
            return true;
        }
        else if ( w == m_CancelButton )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References PopupBack().
OnClick() [7/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file uipopupscriptpresetnew.c.
    {
        super.OnClick( w, x, y, button );
        if ( w == m_BtnOk )
        {
            EditBoxWidget wgt_text = EditBoxWidget.Cast( m_WgtRoot.FindAnyWidget("fld_ppp_pn_new_name") );
            PluginConfigDebugProfile m_ConfigDebugProfile = PluginConfigDebugProfile.Cast( GetPlugin(PluginConfigDebugProfile) );
            m_ConfigDebugProfile.PresetAdd( wgt_text.GetText() );
            SceneEditorMenu menu = SceneEditorMenu.Cast( GetGame().GetUIManager().GetMenu() );
            menu.RefreshLists();
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References GetGame(), GetPlugin(), m_WgtRoot, PopupBack(), x, and y.
OnClick() [8/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 26 of file uipopupscriptpresetrename.c.
    {
        super.OnClick( w, x, y, button );
        if ( w == m_BtnOk )
        {
            EditBoxWidget wgt_text = EditBoxWidget.Cast( m_WgtRoot.FindAnyWidget("fld_ppp_pr_new_name") );
            SceneEditorMenu menu = SceneEditorMenu.Cast( GetGame().GetUIManager().GetMenu() );
            menu.RenamePreset( wgt_text.GetText() );
            menu.RefreshLists();
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References GetGame(), m_WgtRoot, PopupBack(), x, and y.
OnClick() [9/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 19 of file uipopupscriptscenedelete.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnYes )
        {
            PluginSceneManager editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
            editor.SceneDelete(m_DeleteScene);
            PopupBack();
            return true;
        }
        else if ( w == m_BtnNo )
        {
            m_DeleteScene = STRING_EMPTY;
            PopupBack();
            return true;
        }
        return false;
    }
References GetPlugin(), PopupBack(), STRING_EMPTY, x, and y.
OnClick() [10/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 95 of file uipopupscriptscenemanager.c.
    {
        super.OnClick(w, x, y, button);
        string scene_name;
        PluginSceneManager editor;
        if ( w == m_BtnCancel )
        {
            GetGame().GetWorld().SetDate( m_OrigYear, m_OrigMonth, m_OrigDay, m_OrigHour, m_OrigMinute );
            Weather weather = GetGame().GetWeather();
            weather.GetOvercast().Set( m_OrigOvercast, 0, 1000 );
            weather.GetRain().Set( m_OrigRain, 0, 1000 );
            weather.GetFog().Set( m_OrigFog, 0, 1000 );
            weather.SetWindSpeed( m_OrigWindForce );
            PopupBack();
            return true;
        }
        else if ( w == m_BtnSceneNew )
        {
            PopupOpen(SceneEditorMenu.POPUP_ID_SCENE_NEW, NULL);
            return true;
        }
        else if ( w == m_BtnSceneLoad )
        {
            if ( m_LstListScenes.GetSelectedRow() != -1 )
            {
                m_LstListScenes.GetItemText( m_LstListScenes.GetSelectedRow(), 0, scene_name );
                editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
                editor.SceneLoad(scene_name);
                PopupBack();
                return true;
            }
        }
        else if ( w == m_BtnSceneRename )
        {
            m_LstListScenes.GetItemText( m_LstListScenes.GetSelectedRow(), 0, scene_name );
            UIPopupScriptSceneRename popup_rename = UIPopupScriptSceneRename.Cast( PopupOpen(SceneEditorMenu.POPUP_ID_SCENE_RENAME, NULL) );
            popup_rename.SetRenameName(scene_name);
            return true;
        }
        else if ( w == m_BtnSceneDuplicate )
        {
            if ( m_LstListScenes.GetSelectedRow() != -1 )
            {
                m_LstListScenes.GetItemText( m_LstListScenes.GetSelectedRow(), 0, scene_name );
                editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
                editor.SceneDuplicate(scene_name);
                UpdateSceneList();
                return true;
            }
        }
        else if ( w == m_BtnSceneDelete )
        {
            if ( m_LstListScenes.GetSelectedRow() != -1 )
            {
                m_LstListScenes.GetItemText( m_LstListScenes.GetSelectedRow(), 0, scene_name );
                editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
                editor.SceneDelete(scene_name);
                if ( editor.SceneCanDelete(scene_name) )
                {
                    UIPopupScriptSceneDelete popup_delete = UIPopupScriptSceneDelete.Cast( PopupOpen(SceneEditorMenu.POPUP_ID_SCENE_DELETE, NULL) );
                    popup_delete.SetDeleteName(scene_name);
                }
                else
                {
                    UIPopupScriptNotify popup_notify = UIPopupScriptNotify.Cast( PopupOpen(SceneEditorMenu.POPUP_ID_NOTIFY, NULL) );
                    popup_notify.SetLabelText("You cant delete current loaded scene!");
                }
                UpdateSceneList();
                return true;
            }
        }
        else if ( w == m_BtnSave )
        {
            m_OrigYear = m_CurrYear;
            m_OrigMonth = m_CurrMonth;
            m_OrigDay = m_CurrDay;
            m_OrigHour = m_CurrHour;
            m_OrigMinute = m_CurrMinute;
            m_OrigOvercast = m_CurrOvercast;
            m_OrigRain = m_CurrRain;
            m_OrigFog = m_CurrFog;
            m_OrigWindForce = m_CurrWindForce;
            editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
            editor.SetWeather(m_CurrOvercast, m_CurrRain, m_CurrFog, m_CurrWindForce);
            editor.SetDate(m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute);
            editor.SceneSave();
            PopupBack();
            return true;
        }
        return false;
    }
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), GetPlugin(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), m_CurrDay, m_CurrFog, m_CurrHour, m_CurrMinute, m_CurrMonth, m_CurrOvercast, m_CurrRain, m_CurrWindForce, m_CurrYear, PopupBack(), PopupOpen(), WeatherPhenomenon::Set(), World::SetDate(), Weather::SetWindSpeed(), UpdateSceneList(), x, and y.
OnClick() [11/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 18 of file uipopupscriptscenenew.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnOk )
        {
            EditBoxWidget wgt_text = EditBoxWidget.Cast( m_WgtRoot.FindAnyWidget("fld_ppp_sn_new_name") );
            PluginSceneManager editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
            Log("OnClick -> SceneLoad");
            editor.SceneLoad(wgt_text.GetText());
            editor.SceneSave();
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References GetPlugin(), Log(), m_WgtRoot, PopupBack(), x, and y.
OnClick() [12/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 19 of file uipopupscriptscenerename.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnOk )
        {
            EditBoxWidget wgt_text = EditBoxWidget.Cast( m_WgtRoot.FindAnyWidget("fld_ppp_sn_rnm_new_name") );
            PluginSceneManager editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
            editor.SceneRename(m_RenameName, wgt_text.GetText());
            m_RenameName = STRING_EMPTY;
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References GetPlugin(), m_WgtRoot, PopupBack(), STRING_EMPTY, x, and y.
OnClick() [13/13]
override bool UIPopupScript::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 79 of file uipopupscriptscenesettings.c.
    {
        super.OnClick(w, x, y, button);
        if ( w == m_BtnSave )
        {
            m_OrigYear = m_CurrYear;
            m_OrigMonth = m_CurrMonth;
            m_OrigDay = m_CurrDay;
            m_OrigHour = m_CurrHour;
            m_OrigMinute = m_CurrMinute;
            m_OrigOvercast = m_CurrOvercast;
            m_OrigRain = m_CurrRain;
            m_OrigFog = m_CurrFog;
            m_OrigWindForce = m_CurrWindForce;
            PluginSceneManager editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
            editor.SetWeather(m_CurrOvercast, m_CurrRain, m_CurrFog, m_CurrWindForce);
            editor.SetDate(m_CurrYear, m_CurrMonth, m_CurrDay, m_CurrHour, m_CurrMinute);
            PopupBack();
            return true;
        }
        else if ( w == m_BtnCancel )
        {
            PopupBack();
            return true;
        }
        return false;
    }
References GetPlugin(), m_CurrDay, m_CurrFog, m_CurrHour, m_CurrMinute, m_CurrMonth, m_CurrOvercast, m_CurrRain, m_CurrWindForce, m_CurrYear, PopupBack(), x, and y.
OnClose() [1/3]
void UIPopupScript::OnClose () inline private
Definition at line 15 of file uipopupscript.c.
    {
    }
OnClose() [2/3]
override void UIPopupScript::OnClose () inline private
Definition at line 351 of file uipopupscriptscenemanager.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnUpdate);
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), OnUpdate(), and ScriptInvoker::Remove().
OnClose() [3/3]
override void UIPopupScript::OnClose () inline private
Definition at line 233 of file uipopupscriptscenesettings.c.
    {
        Weather weather = GetGame().GetWeather();
        GetGame().GetWorld().SetDate( m_OrigYear, m_OrigMonth, m_OrigDay, m_OrigHour, m_OrigMinute );
        weather.GetOvercast().Set( m_OrigOvercast, 0, 1000 );
        weather.GetRain().Set( m_OrigRain, 0, 1000 );
        weather.GetFog().Set( m_OrigFog, 0, 1000 );
        //weather.SetWindSpeed( m_OrigWindForce );
    }
References Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), CGame::GetWorld(), WeatherPhenomenon::Set(), and World::SetDate().
OnItemSelected()
void UIPopupScript::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 75 of file uipopupscriptpositionmanager.c.
    {
        vector position = m_ConfigDebugProfileFixed.GetPositionByName( GetCurrentPositionName() );
        m_TxtSelectedX.SetText( position[0].ToString() );
        m_TxtSelectedY.SetText( position[2].ToString() );
    }
References GetCurrentPositionName(), and ToString().
OnOpen() [1/8]
void UIPopupScript::OnOpen (Param param) inline private
Definition at line 11 of file uipopupscript.c.
    {
    }
Referenced by UIScriptedMenu::PopupOpen().
OnOpen() [2/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 35 of file uipopupscriptconfigs.c.
    {
        m_ModuleConfigViewer    = PluginConfigViewer.Cast( GetPlugin( PluginConfigViewer ) );
        ClearHierarchy();
    }
References ClearHierarchy(), and GetPlugin().
OnOpen() [3/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 28 of file uipopupscripteditorsettings.c.
    {
        m_WgtTglSeleHighlight.SetChecked( m_ModuleSceneManager.GetDrawSelection() );
        m_WgtTglSavePlayerPos.SetChecked( m_ModuleSceneManager.GetLoadPlayerPos() );
        m_EdxRotationDelta.SetText( m_ModuleSceneManager.GetRotationAngle().ToString() );
    }
OnOpen() [4/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 31 of file uipopupscriptinitscript.c.
    {
        m_MedxInitScript.SetText( "" );
        if ( param != NULL )
        {
            Param2<int, SceneObject> param_scene_object = Param2<int, SceneObject>.Cast( param );
            int index = param_scene_object.param1;
            SceneObject scene_object = param_scene_object.param2;
            if ( index > -1 && scene_object != NULL )
            {
                m_SceneObjectIndex = index;
                m_SceneObject = scene_object;
                m_MedxInitScript.SetText( m_SceneObject.GetInitScript() );
            }
        }
    }
References SceneObject::GetInitScript().
OnOpen() [5/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 38 of file uipopupscriptpositionmanager.c.
    {
        if( PluginSceneManager.GetInstance() )
        {
            if( PluginSceneManager.GetInstance().GetSelectedSceneObject() )
            {
                vector player_pos = PluginSceneManager.GetInstance().GetSelectedSceneObject().GetPosition();
                m_TxtCurrentX.SetText( player_pos[0].ToString() );
                m_TxtCurrentY.SetText( player_pos[2].ToString() );
            }
        }
    }
References ToString().
OnOpen() [6/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 17 of file uipopupscriptpresetrename.c.
    {
        SceneEditorMenu menu = SceneEditorMenu.Cast( GetGame().GetUIManager().GetMenu() );
        m_Editbox.SetText( menu.GetCurrentPresetName() );
    }
References GetGame().
OnOpen() [7/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 317 of file uipopupscriptscenemanager.c.
    {
        //Log("Poup Scene Manager OnOpen");
        UpdateSceneList();
        GetGame().GetWorld().GetDate( m_OrigYear, m_OrigMonth, m_OrigDay, m_OrigHour, m_OrigMinute );
        Weather weather = GetGame().GetWeather();
        m_OrigOvercast = weather.GetOvercast().GetActual();
        m_OrigRain = weather.GetRain().GetActual();
        m_OrigFog = weather.GetFog().GetActual();
        m_OrigWindForce = weather.GetWindSpeed();
        m_CurrYear = m_OrigYear;
        m_CurrMonth = m_OrigMonth;
        m_CurrDay = m_OrigDay;
        m_CurrHour = m_OrigHour;
        m_CurrMinute = m_OrigMinute;
        m_CurrOvercast = m_OrigOvercast;
        m_CurrRain = m_OrigRain;
        m_CurrFog = m_OrigFog;
        m_CurrWindForce = m_OrigWindForce;
        Print( "Year" );
        Print( m_CurrYear );
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Insert(this.OnUpdate);
        ResetSliders();
    }
References CALL_CATEGORY_SYSTEM, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetUpdateQueue(), CGame::GetWeather(), Weather::GetWindSpeed(), CGame::GetWorld(), ScriptInvoker::Insert(), m_OrigDay, m_OrigFog, m_OrigHour, m_OrigMinute, m_OrigMonth, m_OrigOvercast, m_OrigRain, m_OrigWindForce, m_OrigYear, OnUpdate(), Print(), ResetSliders(), and UpdateSceneList().
OnOpen() [8/8]
override void UIPopupScript::OnOpen (Param param) inline private
Definition at line 201 of file uipopupscriptscenesettings.c.
    {
        GetGame().GetWorld().GetDate( m_OrigYear, m_OrigMonth, m_OrigDay, m_OrigHour, m_OrigMinute );
        Weather weather = GetGame().GetWeather();
        m_OrigOvercast = weather.GetOvercast().GetActual();
        m_OrigRain = weather.GetRain().GetActual();
        m_OrigFog = weather.GetFog().GetActual();
        m_OrigWindForce = weather.GetWindSpeed();
        m_CurrYear = m_OrigYear;
        m_CurrMonth = m_OrigMonth;
        m_CurrDay = m_OrigDay;
        m_CurrHour = m_OrigHour;
        m_CurrMinute = m_OrigMinute;
        m_CurrOvercast = m_OrigOvercast;
        m_CurrRain = m_OrigRain;
        m_CurrFog = m_OrigFog;
        m_CurrWindForce = m_OrigWindForce;
        Print( "Year" );
        Print( m_CurrYear );
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Insert(this.OnUpdate);
        ResetSliders();
    }
References CALL_CATEGORY_SYSTEM, WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetUpdateQueue(), CGame::GetWeather(), Weather::GetWindSpeed(), CGame::GetWorld(), ScriptInvoker::Insert(), m_OrigDay, m_OrigFog, m_OrigHour, m_OrigMinute, m_OrigMonth, m_OrigOvercast, m_OrigRain, m_OrigWindForce, m_OrigYear, OnUpdate(), Print(), and ResetSliders().
OnUpdate() [1/2]
void UIPopupScript::OnUpdate () inline private
Definition at line 359 of file uipopupscriptscenemanager.c.
    {
        m_TxtWeatherTime.SetText(GetGame().GetWeather().GetTime().ToString());
    }
References GetGame(), GetTime(), and ToString().
OnUpdate() [2/2]
void UIPopupScript::OnUpdate () inline private
Definition at line 247 of file uipopupscriptscenesettings.c.
    {
        m_TxtWeatherTime.SetText(GetGame().GetWeather().GetTime().ToString());
    }
References GetGame(), GetTime(), and ToString().
PopupBack()
protected UIPopupScript UIPopupScript::PopupBack () inline private
Definition at line 37 of file uipopupscript.c.
    {
        SceneEditorMenu menu = SceneEditorMenu.Cast( GetGame().GetUIManager().GetMenu() );
        return menu.PopupBack();
    }
References GetGame(), and PopupBack().
Referenced by OnClick(), and PopupBack().
PopupOpen()
protected UIPopupScript UIPopupScript::PopupOpen (int popup_id, Param param) inline private
Definition at line 46 of file uipopupscript.c.
    {
        SceneEditorMenu menu = SceneEditorMenu.Cast( GetGame().GetUIManager().GetMenu() );
        return menu.PopupOpen(popup_id, param);
    }
References GetGame(), and PopupOpen().
Referenced by OnClick(), and PopupOpen().
RenderVariables()
void UIPopupScript::RenderVariables (int row) inline private
Definition at line 52 of file uipopupscriptconfigs.c.
    {
        ConfigParams config_params;
        if( row > -1 && row < m_ConfigHierarchyTextListbox.GetNumItems() )
        {
            m_ConfigHierarchyTextListbox.GetItemData( row, 0, config_params );
            m_ConfigVariablesTextListbox.ClearItems();
            ref TStringArray variables;
            string path = config_params.param4;
            variables = m_ModuleConfigViewer.GetConfigVariables( path );
            for ( int i = 0; i < variables.Count(); i++ )
            {
                m_ConfigVariablesTextListbox.AddItem( variables.Get(i), NULL, 0);
            }
        }
    }
References path.
Referenced by OnClick().
ResetSliders() [1/2]
void UIPopupScript::ResetSliders () inline private
Definition at line 367 of file uipopupscriptscenemanager.c.
    {
        int year, month, day, hour, minute;
        GetGame().GetWorld().GetDate( year, month, day, hour, minute );
        m_SldStartTime.SetCurrent( ((hour * 60) + minute) / 14.39 );
        UpdateSliderStartTime( hour, minute );
        float start_day = day;
        int month_tmp = month;
        while ( month_tmp > 1 )
        {
            month_tmp--;
            start_day += m_DaysInMonth[month];
        }
        m_SldStartDay.SetCurrent( start_day / 3.64 );
        UpdateSliderStartDay( month, day );
        Weather weather = GetGame().GetWeather();
        m_SldOvercast.SetCurrent(weather.GetOvercast().GetActual() * 100);
        UpdateSliderOvercast();
        m_SldRain.SetCurrent(weather.GetRain().GetActual() * 100);
        UpdateSliderRain();
        m_SldFog.SetCurrent(weather.GetFog().GetActual() * 100);
        UpdateSliderFog();
        float wind_slider = m_SldWindForce.GetCurrent() * 0.01;
        m_CurrWindForce = weather.GetWindMaximumSpeed() * wind_slider;
        weather.SetWindSpeed( m_CurrWindForce );
        UpdateSliderWindForce();
    }
References WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), CGame::GetWorld(), Weather::SetWindSpeed(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
Referenced by OnOpen().
ResetSliders() [2/2]
void UIPopupScript::ResetSliders () inline private
Definition at line 255 of file uipopupscriptscenesettings.c.
    {
        int year, month, day, hour, minute;
        GetGame().GetWorld().GetDate( year, month, day, hour, minute );
        m_SldStartTime.SetCurrent( ((hour * 60) + minute) / 14.39 );
        UpdateSliderStartTime( hour, minute );
        float start_day = day;
        int month_tmp = month;
        while ( month_tmp > 1 )
        {
            month_tmp--;
            start_day += m_DaysInMonth[month];
        }
        m_SldStartDay.SetCurrent( start_day / 3.64 );
        UpdateSliderStartDay( month, day );
        Weather weather = GetGame().GetWeather();
        m_SldOvercast.SetCurrent(weather.GetOvercast().GetActual() * 100);
        UpdateSliderOvercast();
        m_SldRain.SetCurrent(weather.GetRain().GetActual() * 100);
        UpdateSliderRain();
        m_SldFog.SetCurrent(weather.GetFog().GetActual() * 100);
        UpdateSliderFog();
        float slider_wind_value = ( weather.GetWindSpeed() / weather.GetWindMaximumSpeed() ) * 100;
        m_SldWindForce.SetCurrent( slider_wind_value );
        UpdateSliderWindForce();
    }
References WeatherPhenomenon::GetActual(), World::GetDate(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), Weather::GetWindSpeed(), CGame::GetWorld(), UpdateSliderFog(), UpdateSliderOvercast(), UpdateSliderRain(), UpdateSliderStartDay(), UpdateSliderStartTime(), and UpdateSliderWindForce().
SetDeleteName()
void UIPopupScript::SetDeleteName (string scene_name) inline private
Definition at line 43 of file uipopupscriptscenedelete.c.
    {
        m_DeleteScene = scene_name;
    }
SetLabelText()
void UIPopupScript::SetLabelText (string text) inline private
Definition at line 35 of file uipopupscriptnotify.c.
    {
        m_TxtLabel.SetText(text);
    }
SetRenameName()
void UIPopupScript::SetRenameName (string rename_name) inline private
Definition at line 49 of file uipopupscriptscenerename.c.
    {
        m_RenameName = rename_name;
    }
Show()
void UIPopupScript::Show (bool show) inline private
Definition at line 19 of file uipopupscript.c.
    {
        m_WgtRoot.Show(show);
    }
References m_WgtRoot.
Referenced by UIScriptedMenu::PopupBack(), and UIScriptedMenu::PopupOpen().
UIPopupScriptConfigs()
void UIPopupScript::UIPopupScriptConfigs (Widget wgt) inline private
Definition at line 14 of file uipopupscriptconfigs.c.
    {
        m_BtnOk     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pc_ok") );
        m_ConfigHierarchyTextListbox = TextListboxWidget.Cast( wgt.FindAnyWidget("ConfigHierarchy") );
        m_ConfigVariablesTextListbox = TextListboxWidget.Cast( wgt.FindAnyWidget("ConfigVariables") );
        m_BtnCopyToClipboard = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pc_copy") );
        m_ObjectConfigFilter = EditBoxWidget.Cast( wgt.FindAnyWidget("ObjectConfigFilter") );
    }
UIPopupScriptEditorSettings()
void UIPopupScript::UIPopupScriptEditorSettings (Widget wgt) inline private
Definition at line 14 of file uipopupscripteditorsettings.c.
    {
        m_ModuleSceneManager = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
        m_WgtTglSeleHighlight   = CheckBoxWidget.Cast( wgt.FindAnyWidget("cbx_ppp_est_flag_selection") );
        m_WgtTglSavePlayerPos   = CheckBoxWidget.Cast( wgt.FindAnyWidget("cbx_ppp_est_flag_load_player_pos") );
        m_EdxRotationDelta      = EditBoxWidget.Cast( wgt.FindAnyWidget("ebx_ppp_est_rotation_delta_value") );
        m_BtnCancel             = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_est_cancel") );
    }
References GetPlugin().
UIPopupScriptInitScript()
void UIPopupScript::UIPopupScriptInitScript (Widget wgt) inline private
Definition at line 17 of file uipopupscriptinitscript.c.
    {
        m_ModuleSceneManager = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
        m_MedxInitScript    = MultilineEditBoxWidget.Cast( wgt.FindAnyWidget("pnl_ppp_is_init_script_value") );
        m_BtnRun            = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_is_run") );
        m_BtnSave           = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_is_save") );
        m_BtnCancel         = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_is_cancel") );
    }
References GetPlugin().
UIPopupScriptNotify()
void UIPopupScript::UIPopupScriptNotify (Widget wgt) inline private
Definition at line 9 of file uipopupscriptnotify.c.
    {
        m_BtnOk     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_notify_ok") );
        m_TxtLabel  = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_notify_label") );
    }
UIPopupScriptPositionManager()
void UIPopupScript::UIPopupScriptPositionManager (Widget wgt) inline private
Definition at line 15 of file uipopupscriptpositionmanager.c.
    {
        m_ConfigDebugProfileFixed   = PluginConfigDebugProfileFixed.Cast( GetPlugin( PluginConfigDebugProfileFixed ) );
        m_LstPositionList   = TextListboxWidget.Cast( wgt.FindAnyWidget("tls_ppp_pm_positions_list") );
        m_TxtSelectedX = EditBoxWidget.Cast( wgt.FindAnyWidget("pnl_ppp_pm_selected_x_value") );
        m_TxtSelectedY = EditBoxWidget.Cast( wgt.FindAnyWidget("pnl_ppp_pm_selected_y_value") );
        m_TxtCurrentX = EditBoxWidget.Cast( wgt.FindAnyWidget("pnl_ppp_pm_current_x_value") );
        m_TxtCurrentY = EditBoxWidget.Cast( wgt.FindAnyWidget("pnl_ppp_pm_current_y_value") );
        m_TeleportButton = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pm_teleport") );
        m_CancelButton = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pm_cancel") );
        TStringArray positions_array = new TStringArray;
        m_ConfigDebugProfileFixed.GetAllPositionsNames( positions_array );
        for ( int i = 0; i < positions_array.Count(); i++ )
        {
            m_LstPositionList.AddItem( positions_array.Get(i), new PresetParams ( positions_array.Get(i), true, false), 0);
        }
    }
References GetPlugin().
UIPopupScriptPresetNew()
void UIPopupScript::UIPopupScriptPresetNew (Widget wgt) inline private
Definition at line 9 of file uipopupscriptpresetnew.c.
    {
        m_BtnOk     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pn_ok") );
        m_BtnCancel = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pn_cancel") );
    }
UIPopupScriptPresetRename()
void UIPopupScript::UIPopupScriptPresetRename (Widget wgt) inline private
Definition at line 10 of file uipopupscriptpresetrename.c.
    {
        m_BtnOk     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pr_ok") );
        m_BtnCancel = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_pr_cancel") );
        m_Editbox = EditBoxWidget.Cast( wgt.FindAnyWidget("fld_ppp_pr_new_name") );
    }
UIPopupScriptSceneDelete()
void UIPopupScript::UIPopupScriptSceneDelete (Widget wgt) inline private
Definition at line 10 of file uipopupscriptscenedelete.c.
    {
        m_BtnYes    = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_dlt_yes") );
        m_BtnNo     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_dlt_no") );
    }
UIPopupScriptSceneManager()
void UIPopupScript::UIPopupScriptSceneManager (Widget wgt) inline private
Definition at line 53 of file uipopupscriptscenemanager.c.
    {
        m_BtnCancel         = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_cancel") );
        m_BtnSceneNew       = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_mission_new") );
        m_BtnSceneLoad      = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_mission_load") );
        m_BtnSceneRename    = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_mission_rename") );
        m_BtnSceneDelete    = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_mission_delete") );
        m_BtnSceneDuplicate = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sm_mission_duplicate") );
        m_LstListScenes = TextListboxWidget.Cast( wgt.FindAnyWidget("tls_ppp_sm_scene_list") );
        m_BtnSave           = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_st_save") );
        m_TxtWeatherTime    = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_w_time_value") );
        m_SldStartTime      = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_start_time") );
        m_TxtStartTimeValue = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_start_time_value") );
        m_SldStartDay       = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_start_day") );
        m_TxtStartDayValue  = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_start_day_value") );
        m_SldOvercast       = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_overcast") );
        m_TxtOvercastValue  = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_overcast_value") );
        m_SldRain           = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_rain") );
        m_TxtRainValue      = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_rain_value") );
        m_SldFog            = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_fog") );
        m_TxtFogValue       = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_fog_value") );
        m_SldWindForce      = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_wind_force") );
        m_TxtWindForceValue = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_wind_force_value") );
    }
UIPopupScriptSceneNew()
void UIPopupScript::UIPopupScriptSceneNew (Widget wgt) inline private
Definition at line 9 of file uipopupscriptscenenew.c.
    {
        m_BtnOk     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_ok") );
        m_BtnCancel = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_cancel") );
    }
UIPopupScriptSceneRename()
void UIPopupScript::UIPopupScriptSceneRename (Widget wgt) inline private
Definition at line 10 of file uipopupscriptscenerename.c.
    {
        m_BtnOk         = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_rnm_ok") );
        m_BtnCancel     = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_sn_rnm_cancel") );
    }
UIPopupScriptSceneSettings()
void UIPopupScript::UIPopupScriptSceneSettings (Widget wgt) inline private
Definition at line 46 of file uipopupscriptscenesettings.c.
    {
        m_BtnSave           = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_st_save") );
        m_BtnCancel         = ButtonWidget.Cast( wgt.FindAnyWidget("btn_ppp_st_cancel") );
        m_TxtWeatherTime    = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_w_time_value") );
        m_SldStartTime      = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_start_time") );
        m_TxtStartTimeValue = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_start_time_value") );
        m_SldStartDay       = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_start_day") );
        m_TxtStartDayValue  = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_start_day_value") );
        m_SldOvercast       = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_overcast") );
        m_TxtOvercastValue  = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_overcast_value") );
        m_SldRain           = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_rain") );
        m_TxtRainValue      = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_rain_value") );
        m_SldFog            = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_fog") );
        m_TxtFogValue       = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_fog_value") );
        m_SldWindForce      = SliderWidget.Cast( wgt.FindAnyWidget("sld_ppp_st_wind_force") );
        m_TxtWindForceValue = TextWidget.Cast( wgt.FindAnyWidget("txt_ppp_st_wind_force_value") );
    }
UpdateSceneList()
void UIPopupScript::UpdateSceneList () inline private
Definition at line 292 of file uipopupscriptscenemanager.c.
    {
        m_LstListScenes.ClearItems();
        PluginSceneManager editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
        TStringArray scene_list = editor.GetSceneList();
        string loaded_scene_name = editor.SceneGetName();
        for ( int i = 0; i < scene_list.Count(); ++i )
        {
            string scene_name = scene_list.Get(i);
            m_LstListScenes.AddItem(scene_name, NULL, 0);
            if ( scene_name == loaded_scene_name )
            {
                m_LstListScenes.SelectRow(i);
            }
        }
    }
References GetPlugin().
Referenced by OnClick(), and OnOpen().
UpdateSliderFog() [1/2]
void UIPopupScript::UpdateSliderFog () inline private
Definition at line 425 of file uipopupscriptscenemanager.c.
    {
        string label_text = m_SldFog.GetCurrent().ToString()+"%";
        m_TxtFogValue.SetText( label_text );
    }
Referenced by OnChange(), and ResetSliders().
UpdateSliderFog() [2/2]
void UIPopupScript::UpdateSliderFog () inline private
Definition at line 312 of file uipopupscriptscenesettings.c.
    {
        string label_text = m_SldFog.GetCurrent().ToString()+"%";
        m_TxtFogValue.SetText( label_text );
    }
UpdateSliderOvercast() [1/2]
void UIPopupScript::UpdateSliderOvercast () inline private
Definition at line 413 of file uipopupscriptscenemanager.c.
    {
        string label_text = m_SldOvercast.GetCurrent().ToString()+"%";
        m_TxtOvercastValue.SetText( label_text );
    }
Referenced by OnChange(), and ResetSliders().
UpdateSliderOvercast() [2/2]
void UIPopupScript::UpdateSliderOvercast () inline private
Definition at line 300 of file uipopupscriptscenesettings.c.
    {
        string label_text = m_SldOvercast.GetCurrent().ToString()+"%";
        m_TxtOvercastValue.SetText( label_text );
    }
UpdateSliderRain() [1/2]
void UIPopupScript::UpdateSliderRain () inline private
Definition at line 419 of file uipopupscriptscenemanager.c.
    {
        string label_text = m_SldRain.GetCurrent().ToString()+"%";
        m_TxtRainValue.SetText( label_text );
    }
Referenced by OnChange(), and ResetSliders().
UpdateSliderRain() [2/2]
void UIPopupScript::UpdateSliderRain () inline private
Definition at line 306 of file uipopupscriptscenesettings.c.
    {
        string label_text = m_SldRain.GetCurrent().ToString()+"%";
        m_TxtRainValue.SetText( label_text );
    }
UpdateSliderStartDay() [1/2]
void UIPopupScript::UpdateSliderStartDay (int month, int day) inline private
Definition at line 407 of file uipopupscriptscenemanager.c.
    {
        string label_text = day.ToString() + "." + month.ToString() + ". " + m_CurrYear.ToString();
        m_TxtStartDayValue.SetText( label_text );
    }
Referenced by OnChange(), and ResetSliders().
UpdateSliderStartDay() [2/2]
void UIPopupScript::UpdateSliderStartDay (int month, int day) inline private
Definition at line 294 of file uipopupscriptscenesettings.c.
    {
        string label_text = day.ToString() + "." + month.ToString() + ". " + m_CurrYear.ToString();
        m_TxtStartDayValue.SetText( label_text );
    }
UpdateSliderStartTime() [1/2]
void UIPopupScript::UpdateSliderStartTime (int hour, int minute) inline private
Definition at line 401 of file uipopupscriptscenemanager.c.
    {
        string label_text = hour.ToStringLen(2) + ":" + minute.ToStringLen(2);
        m_TxtStartTimeValue.SetText( label_text );
    }
Referenced by OnChange(), and ResetSliders().
UpdateSliderStartTime() [2/2]
void UIPopupScript::UpdateSliderStartTime (int hour, int minute) inline private
Definition at line 288 of file uipopupscriptscenesettings.c.
    {
        string label_text = hour.ToStringLen(2) + ":" + minute.ToStringLen(2);
        m_TxtStartTimeValue.SetText( label_text );
    }
UpdateSliderWindForce() [1/2]
void UIPopupScript::UpdateSliderWindForce () inline private
Definition at line 431 of file uipopupscriptscenemanager.c.
    {
        string label_text = m_CurrWindForce.ToString()+"ms";
        m_TxtWindForceValue.SetText( label_text );
    }
References float::ToString().
Referenced by OnChange(), and ResetSliders().
UpdateSliderWindForce() [2/2]
void UIPopupScript::UpdateSliderWindForce () inline private
Definition at line 318 of file uipopupscriptscenesettings.c.
    {
        string label_text = m_SldWindForce.GetCurrent().ToString()+"%";
        m_TxtWindForceValue.SetText( label_text );
    }
Member Data Documentation
m_BtnCancel
private ButtonWidget UIPopupScript::m_BtnCancel private
Definition at line 4 of file uipopupscriptconfigs.c.
m_BtnCopyToClipboard
private ButtonWidget UIPopupScript::m_BtnCopyToClipboard private
Definition at line 5 of file uipopupscriptconfigs.c.
m_BtnNo
private ButtonWidget UIPopupScript::m_BtnNo private
Definition at line 4 of file uipopupscriptscenedelete.c.
m_BtnOk
private ButtonWidget UIPopupScript::m_BtnOk private
Definition at line 3 of file uipopupscriptconfigs.c.
m_BtnRun
private ButtonWidget UIPopupScript::m_BtnRun private
Definition at line 5 of file uipopupscriptinitscript.c.
m_BtnSave
private ButtonWidget UIPopupScript::m_BtnSave private
Definition at line 6 of file uipopupscriptinitscript.c.
m_BtnSceneDelete
private ButtonWidget UIPopupScript::m_BtnSceneDelete private
Definition at line 8 of file uipopupscriptscenemanager.c.
m_BtnSceneDuplicate
private ButtonWidget UIPopupScript::m_BtnSceneDuplicate private
Definition at line 7 of file uipopupscriptscenemanager.c.
m_BtnSceneLoad
private ButtonWidget UIPopupScript::m_BtnSceneLoad private
Definition at line 5 of file uipopupscriptscenemanager.c.
m_BtnSceneNew
private ButtonWidget UIPopupScript::m_BtnSceneNew private
Definition at line 4 of file uipopupscriptscenemanager.c.
m_BtnSceneRename
private ButtonWidget UIPopupScript::m_BtnSceneRename private
Definition at line 6 of file uipopupscriptscenemanager.c.
m_BtnYes
private ButtonWidget UIPopupScript::m_BtnYes private
Definition at line 3 of file uipopupscriptscenedelete.c.
m_CancelButton
private ButtonWidget UIPopupScript::m_CancelButton private
Definition at line 10 of file uipopupscriptpositionmanager.c.
m_ConfigDebugProfileFixed
private PluginConfigDebugProfileFixed UIPopupScript::m_ConfigDebugProfileFixed private
Definition at line 8 of file uipopupscriptpositionmanager.c.
m_ConfigHierarchyTextListbox
private TextListboxWidget UIPopupScript::m_ConfigHierarchyTextListbox private
Definition at line 7 of file uipopupscriptconfigs.c.
m_ConfigVariablesTextListbox
private TextListboxWidget UIPopupScript::m_ConfigVariablesTextListbox private
Definition at line 8 of file uipopupscriptconfigs.c.
m_CurrDay
private int UIPopupScript::m_CurrDay private
Definition at line 42 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrFog
private float UIPopupScript::m_CurrFog private
Definition at line 47 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrHour
private int UIPopupScript::m_CurrHour private
Definition at line 43 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrMinute
private int UIPopupScript::m_CurrMinute private
Definition at line 44 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrMonth
private int UIPopupScript::m_CurrMonth private
Definition at line 41 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrOvercast
private float UIPopupScript::m_CurrOvercast private
Definition at line 45 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrRain
private float UIPopupScript::m_CurrRain private
Definition at line 46 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrWindForce
private float UIPopupScript::m_CurrWindForce private
Definition at line 48 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_CurrYear
private int UIPopupScript::m_CurrYear private
Definition at line 40 of file uipopupscriptscenemanager.c.
Referenced by OnClick().
m_DaysInMonth
static private const int UIPopupScript::m_DaysInMonth = { 31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31 } static private
Definition at line 11 of file uipopupscriptscenemanager.c.
m_DeleteScene
private string UIPopupScript::m_DeleteScene private
Definition at line 5 of file uipopupscriptscenedelete.c.
m_Editbox
private EditBoxWidget UIPopupScript::m_Editbox private
Definition at line 5 of file uipopupscriptpresetrename.c.
m_EdxRotationDelta
private EditBoxWidget UIPopupScript::m_EdxRotationDelta private
Definition at line 5 of file uipopupscripteditorsettings.c.
m_LstListScenes
private TextListboxWidget UIPopupScript::m_LstListScenes private
Definition at line 9 of file uipopupscriptscenemanager.c.
m_LstPositionList
private TextListboxWidget UIPopupScript::m_LstPositionList private
Definition at line 3 of file uipopupscriptpositionmanager.c.
m_MedxInitScript
private MultilineEditBoxWidget UIPopupScript::m_MedxInitScript private
Definition at line 3 of file uipopupscriptinitscript.c.
m_ModuleConfigViewer
private PluginConfigViewer UIPopupScript::m_ModuleConfigViewer private
Definition at line 10 of file uipopupscriptconfigs.c.
m_ModuleSceneManager
private PluginSceneManager UIPopupScript::m_ModuleSceneManager private
Definition at line 9 of file uipopupscripteditorsettings.c.
m_ObjectConfigFilter
private EditBoxWidget UIPopupScript::m_ObjectConfigFilter private
Definition at line 12 of file uipopupscriptconfigs.c.
m_OrigDay
private int UIPopupScript::m_OrigDay private
Definition at line 32 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigFog
private float UIPopupScript::m_OrigFog private
Definition at line 37 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigHour
private int UIPopupScript::m_OrigHour private
Definition at line 33 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigMinute
private int UIPopupScript::m_OrigMinute private
Definition at line 34 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigMonth
private int UIPopupScript::m_OrigMonth private
Definition at line 31 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigOvercast
private float UIPopupScript::m_OrigOvercast private
Definition at line 35 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigRain
private float UIPopupScript::m_OrigRain private
Definition at line 36 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigWindForce
private float UIPopupScript::m_OrigWindForce private
Definition at line 38 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_OrigYear
private int UIPopupScript::m_OrigYear private
Definition at line 30 of file uipopupscriptscenemanager.c.
Referenced by OnOpen().
m_RenameName
private string UIPopupScript::m_RenameName private
Definition at line 5 of file uipopupscriptscenerename.c.
m_SceneObject
private SceneObject UIPopupScript::m_SceneObject private
Definition at line 10 of file uipopupscriptinitscript.c.
m_SceneObjectIndex
private int UIPopupScript::m_SceneObjectIndex private
Definition at line 9 of file uipopupscriptinitscript.c.
m_SldFog
private SliderWidget UIPopupScript::m_SldFog private
Definition at line 25 of file uipopupscriptscenemanager.c.
m_SldOvercast
private SliderWidget UIPopupScript::m_SldOvercast private
Definition at line 21 of file uipopupscriptscenemanager.c.
m_SldRain
private SliderWidget UIPopupScript::m_SldRain private
Definition at line 23 of file uipopupscriptscenemanager.c.
m_SldStartDay
private SliderWidget UIPopupScript::m_SldStartDay private
Definition at line 19 of file uipopupscriptscenemanager.c.
m_SldStartTime
private SliderWidget UIPopupScript::m_SldStartTime private
Definition at line 17 of file uipopupscriptscenemanager.c.
m_SldWindForce
private SliderWidget UIPopupScript::m_SldWindForce private
Definition at line 27 of file uipopupscriptscenemanager.c.
m_TeleportButton
private ButtonWidget UIPopupScript::m_TeleportButton private
Definition at line 9 of file uipopupscriptpositionmanager.c.
m_TxtCurrentX
private EditBoxWidget UIPopupScript::m_TxtCurrentX private
Definition at line 6 of file uipopupscriptpositionmanager.c.
m_TxtCurrentY
private EditBoxWidget UIPopupScript::m_TxtCurrentY private
Definition at line 7 of file uipopupscriptpositionmanager.c.
m_TxtFogValue
private TextWidget UIPopupScript::m_TxtFogValue private
Definition at line 26 of file uipopupscriptscenemanager.c.
m_TxtLabel
private TextWidget UIPopupScript::m_TxtLabel private
Definition at line 4 of file uipopupscriptnotify.c.
m_TxtOvercastValue
private TextWidget UIPopupScript::m_TxtOvercastValue private
Definition at line 22 of file uipopupscriptscenemanager.c.
m_TxtRainValue
private TextWidget UIPopupScript::m_TxtRainValue private
Definition at line 24 of file uipopupscriptscenemanager.c.
m_TxtSelectedX
private EditBoxWidget UIPopupScript::m_TxtSelectedX private
Definition at line 4 of file uipopupscriptpositionmanager.c.
m_TxtSelectedY
private EditBoxWidget UIPopupScript::m_TxtSelectedY private
Definition at line 5 of file uipopupscriptpositionmanager.c.
m_TxtStartDayValue
private TextWidget UIPopupScript::m_TxtStartDayValue private
Definition at line 20 of file uipopupscriptscenemanager.c.
m_TxtStartTimeValue
private TextWidget UIPopupScript::m_TxtStartTimeValue private
Definition at line 18 of file uipopupscriptscenemanager.c.
m_TxtWeatherTime
private TextWidget UIPopupScript::m_TxtWeatherTime private
Definition at line 15 of file uipopupscriptscenemanager.c.
m_TxtWindForceValue
private TextWidget UIPopupScript::m_TxtWindForceValue private
Definition at line 28 of file uipopupscriptscenemanager.c.
m_WgtRoot
protected Widget UIPopupScript::m_WgtRoot private
Definition at line 61 of file uipopupscript.c.
Referenced by Show(), and UIPopupScript().
m_WgtTglSavePlayerPos
private CheckBoxWidget UIPopupScript::m_WgtTglSavePlayerPos private
Definition at line 4 of file uipopupscripteditorsettings.c.
m_WgtTglSeleHighlight
private CheckBoxWidget UIPopupScript::m_WgtTglSeleHighlight private
Definition at line 3 of file uipopupscripteditorsettings.c.