DayzKode: AlarmClock_ColorBase Class Reference
AlarmClock_ColorBase Class Reference
Private Member Functions
protected void AnimateAlarmHand (float value)
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
override string GetDebugText ()
override string GetDestroyedSound ()
override string GetExplosiveTriggerSlotName ()
override string GetHitSound ()
override string GetRingingSound ()
override string GetToggleSound ()
override void Init ()
override void OnDebugButtonPressServer (int button_index)
override void OnDebugSpawn ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
void OnUpdate ()
override void SetActions ()
void ~AlarmClock_ColorBase ()
Private Attributes
const string DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet"
const string HIT_SOUND = "AlarmClock_Hit_SoundSet"
const string RINGING_SOUND = "AlarmClock_Ring_Loop_SoundSet"
const string TURN_TOGGLE_SOUND = "AlarmClock_Turn_Off_SoundSet"
Static Private Attributes
static ref NoiseParams m_NoisePar
static NoiseSystem m_NoiseSystem
Detailed Description
Definition at line 1 of file alarmclock.c.
Constructor & Destructor Documentation
~AlarmClock_ColorBase()
void AlarmClock_ColorBase::~AlarmClock_ColorBase () inline private
Definition at line 27 of file alarmclock.c.
    {
        #ifndef SERVER
        OnRingingStopClient();
        #endif
    }
References OnRingingStopClient().
Member Function Documentation
AnimateAlarmHand()
protected void AlarmClock_ColorBase::AnimateAlarmHand (float value) inline private
Definition at line 132 of file alarmclock.c.
    {
        SetAnimationPhaseNow("ClockAlarm", value);
    }
GetDebugButtonNames()
override void AlarmClock_ColorBase::GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4) inline private
Definition at line 64 of file alarmclock.c.
    {
        button1 = "SetAlarmAhead1Min";
    }
GetDebugText()
override string AlarmClock_ColorBase::GetDebugText () inline private
Definition at line 79 of file alarmclock.c.
    {
        string debug_output;
        if( GetGame().IsDedicatedServer())
        {
            debug_output = "alarm in: " + GetAlarmInMin().ToString() + " mins" + "\n";
            debug_output +=  "current state: " +  typename.EnumToString(EAlarmClockState, m_State) + "\n";;
            debug_output +=  "ringing for " + m_RingingDuration.ToString()+ " secs" + "\n";
            debug_output +=  "ringing max " + GetRingingDurationMax().ToString()+ " secs" + "\n";
        }
        else
        {
            debug_output = "this is client";
        }
        return debug_output;
    }
References GetAlarmInMin(), GetGame(), GetRingingDurationMax(), m_RingingDuration, m_State, and float::ToString().
GetDestroyedSound()
override string AlarmClock_ColorBase::GetDestroyedSound () inline private
Definition at line 54 of file alarmclock.c.
    {
        return DESTROYED_SOUND;
    }
References DESTROYED_SOUND.
GetExplosiveTriggerSlotName()
override string AlarmClock_ColorBase::GetExplosiveTriggerSlotName () inline private
Definition at line 69 of file alarmclock.c.
    {
        return "TriggerAlarmClock";
    }
GetHitSound()
override string AlarmClock_ColorBase::GetHitSound () inline private
Definition at line 59 of file alarmclock.c.
    {
        return HIT_SOUND;
    }
References HIT_SOUND.
GetRingingSound()
override string AlarmClock_ColorBase::GetRingingSound () inline private
Definition at line 49 of file alarmclock.c.
    {
        return RINGING_SOUND;
    }
References RINGING_SOUND.
GetToggleSound()
override string AlarmClock_ColorBase::GetToggleSound () inline private
Definition at line 44 of file alarmclock.c.
    {
        return TURN_TOGGLE_SOUND;
    }
References TURN_TOGGLE_SOUND.
Init()
override void AlarmClock_ColorBase::Init () inline private
Definition at line 12 of file alarmclock.c.
    {
        super.Init();
        if ( GetGame().IsServer() )
        {
            m_NoiseSystem = GetGame().GetNoiseSystem();
            if ( m_NoiseSystem && !m_NoisePar )
            {
                // Create and load noise parameters
                m_NoisePar = new NoiseParams;
                m_NoisePar.LoadFromPath("cfgVehicles " + GetType() + " NoiseAlarmClock");
            }
        }
    }
References GetGame(), CGame::GetNoiseSystem(), GetType(), m_NoisePar, m_NoiseSystem, and NoiseParams().
OnDebugButtonPressServer()
override void AlarmClock_ColorBase::OnDebugButtonPressServer (int button_index) inline private
Definition at line 74 of file alarmclock.c.
    {
        SetAlarmInXMins(1);
    }
References SetAlarmInXMins().
OnDebugSpawn()
override void AlarmClock_ColorBase::OnDebugSpawn () inline private
Definition at line 184 of file alarmclock.c.
    {
        TurnOn();
        MakeRingingStart();
    }
References MakeRingingStart(), and TurnOn().
OnStoreLoad()
override bool AlarmClock_ColorBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 138 of file alarmclock.c.
    {
        if (!super.OnStoreLoad(ctx, version))
            return false;
        if (version < 126)
        {
            return true;
        }
        EAlarmClockState state;
        if ( !ctx.Read( state ) )
        {
            return false;
        }
        float time;
        if ( !ctx.Read( time ) )
        {
            return false;
        }
        SetAlarmTimeServer(time);
        SetState(state);
        if ( state == EAlarmClockState.SET )
        {
            TurnOn();
        }
        else if (state == EAlarmClockState.RINGING )
        {
            MakeRingingStart();
        }
        return true;
    }
References MakeRingingStart(), Serializer::Read(), SetAlarmTimeServer(), SetState(), and TurnOn().
OnStoreSave()
override void AlarmClock_ColorBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 176 of file alarmclock.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_State);
        ctx.Write(m_AlarmTime01);
    }
References m_AlarmTime01, m_State, and Serializer::Write().
OnUpdate()
void AlarmClock_ColorBase::OnUpdate () inline private
Definition at line 97 of file alarmclock.c.
    {
        if ( IsAlarmOn() )
        {
            //due to variable server time flow(day-night time accel), it's not possible to simply set a timer for X secs without some convoluted math/code, so we need to check at regular intervals
            int alarm_hand_in_minutes = ConvertAlarmHand01ToMins12h(m_AlarmTime01);
            int pass, hour, minute;
            GetGame().GetWorld().GetDate(pass, pass, pass, hour, minute);
            int curr_time_in_minutes = ConvertTimeToMins12h(hour, minute);
            //Print(GetAlarmInMin());
            if ( alarm_hand_in_minutes == curr_time_in_minutes )
            {
                MakeRingingStart();
            }
        }
        if ( IsRinging())
        {
            m_RingingDuration += UPDATE_TICK_RATE;
            if (m_RingingDuration >= GetRingingDurationMax())
            {
                TurnOff();
            }
            else if ( m_NoiseSystem )
            {
                m_NoiseSystem.AddNoiseTarget( GetPosition(), UPDATE_TICK_RATE, m_NoisePar);
            }
        }
    }
References NoiseSystem::AddNoiseTarget(), ConvertAlarmHand01ToMins12h(), ConvertTimeToMins12h(), World::GetDate(), GetGame(), GetPosition, GetRingingDurationMax(), CGame::GetWorld(), IsAlarmOn(), IsRinging(), m_AlarmTime01, m_NoisePar, m_NoiseSystem, m_RingingDuration, MakeRingingStart(), TurnOff(), and UPDATE_TICK_RATE.
SetActions()
override void AlarmClock_ColorBase::SetActions () inline private
Definition at line 35 of file alarmclock.c.
    {
        super.SetActions();
        AddAction(ActionSetAlarmClock);
        AddAction(ActionTurnOnAlarmClock);
        AddAction(ActionTurnOffAlarmClock);
    }
References ActionTurnOffAlarmClock(), ActionTurnOnAlarmClock(), and AddAction().
Member Data Documentation
DESTROYED_SOUND
const string AlarmClock_ColorBase::DESTROYED_SOUND = "AlarmClock_Destroyed_SoundSet" private
Definition at line 5 of file alarmclock.c.
Referenced by GetDestroyedSound().
HIT_SOUND
const string AlarmClock_ColorBase::HIT_SOUND = "AlarmClock_Hit_SoundSet" private
Definition at line 6 of file alarmclock.c.
Referenced by GetHitSound().
m_NoisePar
ref NoiseParams AlarmClock_ColorBase::m_NoisePar static private
Definition at line 9 of file alarmclock.c.
Referenced by Init(), and OnUpdate().
m_NoiseSystem
NoiseSystem AlarmClock_ColorBase::m_NoiseSystem static private
Definition at line 10 of file alarmclock.c.
Referenced by Init(), and OnUpdate().
RINGING_SOUND
const string AlarmClock_ColorBase::RINGING_SOUND = "AlarmClock_Ring_Loop_SoundSet" private
Definition at line 3 of file alarmclock.c.
Referenced by GetRingingSound().
TURN_TOGGLE_SOUND
const string AlarmClock_ColorBase::TURN_TOGGLE_SOUND = "AlarmClock_Turn_Off_SoundSet" private
Definition at line 4 of file alarmclock.c.
Referenced by GetToggleSound().