DayzKode: Switchable_Base Class Reference
Switchable_Base Class Reference
Private Member Functions
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override ScriptedLightBase GetLight ()
override ScriptedLightBase GetLight ()
void InitAttachmentsSlotsToCheck (out array< int > AttSlots)
Enter att slot types to check on attach.
override bool IsLightSource ()
override bool IsLightSource ()
override void OnInventoryExit (Man player)
override void OnInventoryExit (Man player)
override void OnWork (float consumed_energy)
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStart ()
override void OnWorkStop ()
override void OnWorkStop ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void UniversalLight ()
Private Attributes
ref array< int > m_AttachmentSlotsCheck
PistollightLight m_Light
UniversallightLight m_Light
Static Private Attributes
static int GLASS_ID = 0
static string LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat"
static string LIGHT_OFF_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3.rvmat"
static string LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat"
static string LIGHT_ON_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3_on.rvmat"
static int REFLECTOR_ID = 1
Detailed Description
Definition at line 1 of file chainsaw.c.
Member Function Documentation
CanPutAsAttachment() [1/2]
override bool Switchable_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 18 of file tlrlight.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( !parent.IsKindOf("PlateCarrierHolster") && !parent.IsKindOf("PlateCarrierComplete") && !parent.IsKindOf("CarrierHolsterSolo") && !parent.IsKindOf("ChestHolster") )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [2/2]
override bool Switchable_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 25 of file universallight.c.
    {
        if ( !super.CanPutAsAttachment(parent) ) {return false;}
        bool req_attachment         = false;
        bool rail_attachment_found   = false;
        int slot_id;
        ItemBase attachment;
        for ( int i = 0; i < parent.GetInventory().GetAttachmentSlotsCount(); i++ )
        {
            slot_id = parent.GetInventory().GetAttachmentSlotId(i);
            if ( m_AttachmentSlotsCheck.Find(slot_id) != -1 )
            {
                req_attachment = true;
                attachment = ItemBase.Cast(parent.GetInventory().FindAttachment(slot_id));
                if ( attachment && attachment.ConfigIsExisting("hasRailFunctionality") && attachment.ConfigGetBool("hasRailFunctionality") )
                    rail_attachment_found = true;
            }
        }
        return !req_attachment || (req_attachment && rail_attachment_found);
    }
References GetAttachmentSlotsCount().
CanPutInCargo()
override bool Switchable_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file chainsaw.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        if( !GetCompEM().IsSwitchedOn() )
        {
            return true;
        }
        return false;
    }
GetLight() [1/2]
override ScriptedLightBase Switchable_Base::GetLight () inline private
Definition at line 13 of file tlrlight.c.
    {
        return m_Light;
    }
References m_Light.
Referenced by ItemBase::EEItemLocationChanged().
GetLight() [2/2]
override ScriptedLightBase Switchable_Base::GetLight () inline private
Definition at line 20 of file universallight.c.
    {
        return m_Light;
    }
References m_Light.
InitAttachmentsSlotsToCheck()
void Switchable_Base::InitAttachmentsSlotsToCheck (out array< int > AttSlots) inline private
Enter att slot types to check on attach.
Definition at line 123 of file universallight.c.
    {
        if (!AttSlots)
        {
            AttSlots = new array<int>;
            AttSlots.Insert(InventorySlots.GetSlotIdFromString("weaponHandguardM4"));
            AttSlots.Insert(InventorySlots.GetSlotIdFromString("weaponHandguardAK"));
            AttSlots.Insert(InventorySlots.GetSlotIdFromString("weaponHandguardMP5"));
        }
    }
References InventorySlots::GetSlotIdFromString().
Referenced by UniversalLight().
IsLightSource() [1/2]
override bool Switchable_Base::IsLightSource () inline private
Definition at line 99 of file tlrlight.c.
    {
        return true;
    }
IsLightSource() [2/2]
override bool Switchable_Base::IsLightSource () inline private
Definition at line 117 of file universallight.c.
    {
        return true;
    }
OnInventoryExit() [1/2]
override void Switchable_Base::OnInventoryExit (Man player) inline private
Definition at line 77 of file tlrlight.c.
    {
        super.OnInventoryExit(player);
        if ( GetCompEM().IsWorking() )
        {
            if (player)
            {
                vector ori_rotate = player.GetOrientation();
                ori_rotate = ori_rotate + Vector(270,0,0);
                SetOrientation(ori_rotate);
            }
        }
    }
References SetOrientation(), and Vector().
OnInventoryExit() [2/2]
override void Switchable_Base::OnInventoryExit (Man player) inline private
Definition at line 95 of file universallight.c.
    {
        super.OnInventoryExit(player);
        if ( GetCompEM().IsWorking() )
        {
            if (player)
            {
                vector ori_rotate = player.GetOrientation();
                ori_rotate = ori_rotate + Vector(270,0,0);
                SetOrientation(ori_rotate);
            }
        }
    }
References SetOrientation(), and Vector().
OnWork() [1/2]
override void Switchable_Base::OnWork (float consumed_energy) inline private
Definition at line 40 of file tlrlight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            Battery9V battery = Battery9V.Cast( GetCompEM().GetEnergySource() );
            if (battery  &&  m_Light)
            {
                float efficiency = battery.GetEfficiency0To1();
                if ( efficiency < 1 )
                {
                    m_Light.SetIntensity( efficiency, GetCompEM().GetUpdateInterval() );
                }
                else
                {
                    m_Light.SetIntensity( 1, 0 );
                }
            }
        }
    }
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWork() [2/2]
override void Switchable_Base::OnWork (float consumed_energy) inline private
Definition at line 58 of file universallight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            Battery9V battery = Battery9V.Cast( GetCompEM().GetEnergySource() );
            if (battery  &&  m_Light)
            {
                float efficiency = battery.GetEfficiency0To1();
                if ( efficiency < 1 )
                {
                    m_Light.SetIntensity( efficiency, GetCompEM().GetUpdateInterval() );
                }
                else
                {
                    m_Light.SetIntensity( 1, 0 );
                }
            }
        }
    }
References GetGame(), m_Light, and PointLightBase::SetIntensity().
OnWorkStart() [1/2]
override void Switchable_Base::OnWorkStart () inline private
Definition at line 29 of file tlrlight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            m_Light = PistollightLight.Cast(  ScriptedLightBase.CreateLight(PistollightLight, "0 0 0", 0.08)  ); // Position is zero because light is attached on parent immediately.
            m_Light.AttachOnMemoryPoint(this, "beamStart", "beamEnd");
            SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR);
        }
    }
References GetGame(), and m_Light.
OnWorkStart() [2/2]
override void Switchable_Base::OnWorkStart () inline private
Definition at line 47 of file universallight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            m_Light = UniversallightLight.Cast(  ScriptedLightBase.CreateLight(UniversallightLight, "0 0 0", 0.08)  ); // Position is zero because light is attached on parent immediately.
            m_Light.AttachOnMemoryPoint(this, "beamStart", "beamEnd");
            SetObjectMaterial(GLASS_ID, LIGHT_ON_GLASS);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_ON_REFLECTOR);
        }
    }
References GetGame(), and m_Light.
OnWorkStop() [1/2]
override void Switchable_Base::OnWorkStop () inline private
Definition at line 62 of file tlrlight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            if (m_Light)
                m_Light.FadeOut();
            m_Light = NULL;
            SetObjectMaterial(GLASS_ID, LIGHT_OFF_GLASS);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_OFF_REFLECTOR);
        }
    }
References GetGame(), and m_Light.
OnWorkStop() [2/2]
override void Switchable_Base::OnWorkStop () inline private
Definition at line 80 of file universallight.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            if (m_Light)
                m_Light.FadeOut();
            m_Light = NULL;
            SetObjectMaterial(GLASS_ID, LIGHT_OFF_GLASS);
            SetObjectMaterial(REFLECTOR_ID, LIGHT_OFF_REFLECTOR);
        }
    }
References GetGame(), and m_Light.
SetActions() [1/3]
override void Switchable_Base::SetActions () inline private
Definition at line 13 of file chainsaw.c.
    {
        super.SetActions();
        AddAction(ActionSawPlanks);
        AddAction(ActionDestroyPart);
    }
References AddAction().
SetActions() [2/3]
override void Switchable_Base::SetActions () inline private
Definition at line 92 of file tlrlight.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnWhileInHands);
        AddAction(ActionTurnOffWhileInHands);
    }
References AddAction().
SetActions() [3/3]
override void Switchable_Base::SetActions () inline private
Definition at line 110 of file universallight.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnWhileInHands);
        AddAction(ActionTurnOffWhileInHands);
    }
References AddAction().
UniversalLight()
void Switchable_Base::UniversalLight () inline private
Definition at line 15 of file universallight.c.
    {
        InitAttachmentsSlotsToCheck(m_AttachmentSlotsCheck);
    }
References InitAttachmentsSlotsToCheck().
Member Data Documentation
GLASS_ID
static int Switchable_Base::GLASS_ID = 0 static private
Definition at line 6 of file tlrlight.c.
LIGHT_OFF_GLASS
static string Switchable_Base::LIGHT_OFF_GLASS = "dz\\gear\\tools\\data\\flashlight_glass.rvmat" static private
Definition at line 8 of file tlrlight.c.
LIGHT_OFF_REFLECTOR
static string Switchable_Base::LIGHT_OFF_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3.rvmat" static private
Definition at line 9 of file tlrlight.c.
LIGHT_ON_GLASS
static string Switchable_Base::LIGHT_ON_GLASS = "dz\\gear\\tools\\data\\flashlight_glass_on.rvmat" static private
Definition at line 10 of file tlrlight.c.
LIGHT_ON_REFLECTOR
static string Switchable_Base::LIGHT_ON_REFLECTOR = "dz\\weapons\\attachments\\data\\TLS3_on.rvmat" static private
Definition at line 11 of file tlrlight.c.
m_AttachmentSlotsCheck
ref array<int> Switchable_Base::m_AttachmentSlotsCheck private
Definition at line 13 of file universallight.c.
m_Light [1/2]
PistollightLight Switchable_Base::m_Light private
Definition at line 3 of file tlrlight.c.
Referenced by GetLight().
m_Light [2/2]
UniversallightLight Switchable_Base::m_Light private
Definition at line 3 of file universallight.c.
REFLECTOR_ID
static int Switchable_Base::REFLECTOR_ID = 1 static private
Definition at line 5 of file tlrlight.c.