DayzKode: ActionRepackTentCB Class Reference
ActionRepackTentCB Class Reference
Private Member Functions
override void CreateActionComponent ()
void DropDuringRepacking ()
Detailed Description
Definition at line 1 of file actionrepacktent.c.
Member Function Documentation
CreateActionComponent()
override void ActionRepackTentCB::CreateActionComponent () inline private
Definition at line 3 of file actionrepacktent.c.
    {
        m_ActionData.m_ActionComponent = new CAContinuousTime( UATimeSpent.UNPACK );
    }
References ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, and UATimeSpent::UNPACK.
DropDuringRepacking()
void ActionRepackTentCB::DropDuringRepacking () inline private
Definition at line 8 of file actionrepacktent.c.
    {
        vector orientation = m_ActionData.m_Player.GetOrientation();
        vector position = m_ActionData.m_Player.GetPosition() + m_ActionData.m_Player.GetDirection();
        vector rotation_matrix[3];
        float direction[4];
        InventoryLocation source = new InventoryLocation;
        InventoryLocation destination = new InventoryLocation;
        Math3D.YawPitchRollMatrix( orientation, rotation_matrix );
        Math3D.MatrixToQuat( rotation_matrix, direction );
        vector ground_position = position;
        ground_position[1] = GetGame().SurfaceY(ground_position[0],ground_position[2]);
        if ( vector.DistanceSq( m_ActionData.m_Player.GetPosition(), ground_position ) > UAMaxDistances.DEFAULT * UAMaxDistances.DEFAULT)
        {
            if ( m_ActionData.m_MainItem.GetInventory().GetCurrentInventoryLocation( source ) )
            {
                destination.SetGroundEx( m_ActionData.m_MainItem, position, direction );
                m_ActionData.m_Player.PredictiveTakeToDst(source, destination);
            }
        }
        else
        {
            if ( m_ActionData.m_MainItem.GetInventory().GetCurrentInventoryLocation( source ) )
            {
                destination.SetGroundEx( m_ActionData.m_MainItem, ground_position, direction );
                m_ActionData.m_Player.PredictiveTakeToDst(source, destination);
            }
        }
    }
References UAMaxDistances::DEFAULT, vector::DistanceSq(), GetGame(), ActionBaseCB::m_ActionData, ActionData::m_MainItem, ActionData::m_Player, Math3D::MatrixToQuat(), InventoryLocation::SetGroundEx(), CGame::SurfaceY(), and Math3D::YawPitchRollMatrix().
Referenced by ActionRepackTent::OnStartAnimationLoopClient(), and ActionRepackTent::OnStartAnimationLoopServer().