DayzKode: DebugPrint Class Reference
DebugPrint Class Reference
Static Private Member Functions
static string AdjustDebugLog (string msg)
Function adjust received message for debug console (Do not use)
static void EnableTracingLogs (bool enable)
static private bool IsDebugLog (string msg)
static private bool IsStackTrace (string msg)
static void Log (string msg)
Prints debug message with normal prio.
static void LogAndTrace (string msg)
Prints debug message as normal message and prints stack trace of calls.
static void LogError (string msg)
Prints debug message as error message.
static void LogErrorAndTrace (string msg)
Prints debug message as error message and prints stack trace of calls.
static private void LogMessage (string msg, int msg_type, bool trace=false)
static void LogWarning (string msg)
Prints debug message as warning message.
static void LogWarningAndTrace (string msg)
Prints debug message as warning message and prints stack trace of calls.
static void OnInit ()
static private string TrimDebugLog (string msg)
static private string TrimStackTrace (string msg)
Static Private Attributes
static private const int MSG_COUNT = 3
static private const int MSG_ERROR = 2
static private const int MSG_LOG = 0
static private const int MSG_WARNING = 1
static private string s_MsgPrefix [MSG_COUNT]
static private bool s_MsgStackMarked
static private string s_MsgStackMarkEnd
static private string s_MsgStackMarkStart
static private bool s_TraceAllLogs
Detailed Description
Definition at line 1 of file debugprint.c.
Member Function Documentation
AdjustDebugLog()
static string DebugPrint::AdjustDebugLog (string msg) inline static private
Function adjust received message for debug console (Do not use)
Parameters
msg string Message for adjust
Returns
string Adjusted Message
string msg = DebugPrint.AdjustDebugLog("s = 'Hello World, this is error log'");
DebugPrint.Log(msg);
>> Hello World, this is error log
Definition at line 141 of file debugprint.c.
    {
        if ( IsStackTrace(msg) )
        {
            return TrimStackTrace(msg);
        }
        if ( IsDebugLog(msg) )
        {
            return TrimDebugLog(msg);
        }
        return msg;
    }
References IsDebugLog(), IsStackTrace(), TrimDebugLog(), and TrimStackTrace().
EnableTracingLogs()
static void DebugPrint::EnableTracingLogs (bool enable) inline static private
Definition at line 156 of file debugprint.c.
    {
        s_TraceAllLogs = enable;
    }
References s_TraceAllLogs.
IsDebugLog()
static private bool DebugPrint::IsDebugLog (string msg) inline static private
Definition at line 161 of file debugprint.c.
    {
        for ( int i = 0; i < MSG_COUNT; ++i )
        {
            if ( msg.IndexOf(s_MsgPrefix[i]) != -1 )
            {
                return true;
            }
        }
        return false;
    }
References string::IndexOf(), MSG_COUNT, and s_MsgPrefix.
Referenced by AdjustDebugLog().
IsStackTrace()
static private bool DebugPrint::IsStackTrace (string msg) inline static private
Definition at line 187 of file debugprint.c.
    {
        if ( s_MsgStackMarked && msg.IndexOf(s_MsgStackMarkEnd) != -1 )
        {
            s_MsgStackMarked = false;
            return false;
        }
        if ( s_MsgStackMarked )
        {
            return true;
        }
        if ( msg.IndexOf(s_MsgStackMarkStart) != -1 )
        {
            s_MsgStackMarked = true;
            return true;
        }
        return false;
    }
References string::IndexOf(), s_MsgStackMarked, s_MsgStackMarkEnd, and s_MsgStackMarkStart.
Referenced by AdjustDebugLog().
Log()
static void DebugPrint::Log (string msg) inline static private
Prints debug message with normal prio.
Parameters
msg string Debug message for print
Returns
void None
DebugPrint.Log("Hello World");
>> [Log]: Hello World;
Definition at line 37 of file debugprint.c.
    {
        LogMessage(msg, MSG_LOG, s_TraceAllLogs);
    }
References LogMessage(), MSG_LOG, and s_TraceAllLogs.
LogAndTrace()
static void DebugPrint::LogAndTrace (string msg) inline static private
Prints debug message as normal message and prints stack trace of calls.
Parameters
msg string Debug message for print
Returns
void None
DebugPrint.LogAndTrace("Hello World, this is normal log");
>> [Log]: Hello World, this is normal log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 56 of file debugprint.c.
    {
        LogMessage(msg, MSG_LOG, true);
    }
References LogMessage(), and MSG_LOG.
LogError()
static void DebugPrint::LogError (string msg) inline static private
Prints debug message as error message.
Parameters
msg string Debug message for error print
Returns
void None
DebugPrint.LogError("Hello World, this is error log");
>> [Error]: Hello World, this is error log
Definition at line 105 of file debugprint.c.
    {
        LogMessage(msg, MSG_ERROR, s_TraceAllLogs);
    }
References LogMessage(), MSG_ERROR, and s_TraceAllLogs.
LogErrorAndTrace()
static void DebugPrint::LogErrorAndTrace (string msg) inline static private
Prints debug message as error message and prints stack trace of calls.
Parameters
msg string Debug message for error print
Returns
void None
DebugPrint.LogErrorAndTrace("Hello World, this is error log");
>> [Error]: Hello World, this is error log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 124 of file debugprint.c.
    {
        LogMessage(msg, MSG_ERROR, true);
    }
References LogMessage(), and MSG_ERROR.
Referenced by SyncPlayerList::CreatePlayerList(), OnlineServices::ErrorCaught(), OnlineServices::LoadFriends(), OnlineServices::LoadMPPrivilege(), OnlineServices::LoadPermissions(), OnlineServices::LoadServers(), OnlineServices::LoadVoicePrivilege(), OnlineServices::SetServerFavorited(), OnlineServices::ShowInviteScreen(), and OnlineServices::ShowUserProfile().
LogMessage()
static private void DebugPrint::LogMessage (string msg, int msg_type, bool trace = false) inline static private
Definition at line 218 of file debugprint.c.
    {
        string mesg = "["+s_MsgPrefix[msg_type]+"]: "+msg;
        Print(mesg);
        if ( trace )
        {
            DumpStack();
        }
    }
References DumpStack(), Print(), and s_MsgPrefix.
Referenced by Log(), LogAndTrace(), LogError(), LogErrorAndTrace(), LogWarning(), and LogWarningAndTrace().
LogWarning()
static void DebugPrint::LogWarning (string msg) inline static private
Prints debug message as warning message.
Parameters
msg string Debug message for warning print
Returns
void None
DebugPrint.LogWarning("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
Definition at line 71 of file debugprint.c.
    {
        LogMessage(msg, MSG_WARNING, s_TraceAllLogs);
    }
References LogMessage(), MSG_WARNING, and s_TraceAllLogs.
LogWarningAndTrace()
static void DebugPrint::LogWarningAndTrace (string msg) inline static private
Prints debug message as warning message and prints stack trace of calls.
Parameters
msg string Debug message for warning print
Returns
void None
DebugPrint.LogWarningAndTrace("Hello World, this is warning log");
>> [Warning]: Hello World, this is warning log
>>      -- Stack trace --
>>      OnKeyPress() Scripts/mission/missionGameplay.c : 230
>>      OnKeyPress() Scripts/DayZGame.c : 346
>>      -----------------
Definition at line 90 of file debugprint.c.
    {
        LogMessage(msg, MSG_WARNING, true);
    }
References LogMessage(), and MSG_WARNING.
OnInit()
static void DebugPrint::OnInit () inline static private
Definition at line 14 of file debugprint.c.
    {
        s_MsgPrefix[MSG_LOG]        = "Log";
        s_MsgPrefix[MSG_WARNING]    = "Warning";
        s_MsgPrefix[MSG_ERROR]      = "Error";
        s_MsgStackMarkStart         = "-- Stack trace --";
        s_MsgStackMarked            = false;
        s_MsgStackMarkEnd           = "-----------------";
        s_TraceAllLogs              = false;
    }
References MSG_ERROR, MSG_LOG, MSG_WARNING, s_MsgPrefix, s_MsgStackMarked, s_MsgStackMarkEnd, s_MsgStackMarkStart, and s_TraceAllLogs.
TrimDebugLog()
static private string DebugPrint::TrimDebugLog (string msg) inline static private
Definition at line 173 of file debugprint.c.
    {
        int msg_lenght = msg.Length();
        int log_start = msg.IndexOf("'") + 1;
        if ( log_start == -1 )
        {
            return msg;
        }
        int log_lenght = msg_lenght - log_start - 2;
        return msg.Substring(log_start, log_lenght);
    }
References string::IndexOf(), string::Length(), and string::Substring().
Referenced by AdjustDebugLog().
TrimStackTrace()
static private string DebugPrint::TrimStackTrace (string msg) inline static private
Definition at line 208 of file debugprint.c.
    {
        if ( msg.IndexOf("DebugPrint.c") != -1 )
        {
            return string.Empty;
        }
        return msg;
    }
References string::Empty, and string::IndexOf().
Referenced by AdjustDebugLog().
Member Data Documentation
MSG_COUNT
private const int DebugPrint::MSG_COUNT = 3 static private
Definition at line 6 of file debugprint.c.
Referenced by IsDebugLog().
MSG_ERROR
private const int DebugPrint::MSG_ERROR = 2 static private
Definition at line 5 of file debugprint.c.
Referenced by LogError(), LogErrorAndTrace(), and OnInit().
MSG_LOG
private const int DebugPrint::MSG_LOG = 0 static private
Definition at line 3 of file debugprint.c.
Referenced by Log(), LogAndTrace(), and OnInit().
MSG_WARNING
private const int DebugPrint::MSG_WARNING = 1 static private
Definition at line 4 of file debugprint.c.
Referenced by LogWarning(), LogWarningAndTrace(), and OnInit().
s_MsgPrefix
private string DebugPrint::s_MsgPrefix[MSG_COUNT] static private
Definition at line 8 of file debugprint.c.
Referenced by IsDebugLog(), LogMessage(), and OnInit().
s_MsgStackMarked
private bool DebugPrint::s_MsgStackMarked static private
Definition at line 11 of file debugprint.c.
Referenced by IsStackTrace(), and OnInit().
s_MsgStackMarkEnd
private string DebugPrint::s_MsgStackMarkEnd static private
Definition at line 10 of file debugprint.c.
Referenced by IsStackTrace(), and OnInit().
s_MsgStackMarkStart
private string DebugPrint::s_MsgStackMarkStart static private
Definition at line 9 of file debugprint.c.
Referenced by IsStackTrace(), and OnInit().
s_TraceAllLogs
private bool DebugPrint::s_TraceAllLogs static private
Definition at line 12 of file debugprint.c.
Referenced by EnableTracingLogs(), Log(), LogError(), LogWarning(), and OnInit().