DayzKode: AnalyticsManagerClient Class Reference
AnalyticsManagerClient Class Reference
Private Member Functions
void Event_OnEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot)
void Event_OnPlayerIgnitedFireplace (EFireIgniteType ignite_type)
void OnActionBandageTarget ()
void OnActionCookedSteak ()
void OnActionDrink ()
void OnActionEat ()
void OnActionFinishedGutDeer ()
void OnActionFinishedShaveSelf ()
void OnActionRestrain ()
void OnItemAttachedAtPlayer (EntityAI item, string slot_name)
void RegisterEvents ()
void UnregisterEvents ()
Static Private Attributes
static const int GEAR_COUNT = 3
static string m_FullGear [GEAR_COUNT] = {"Shoulder","Melee","Back"}
Detailed Description
Definition at line 1 of file analyticsmanagerclient.c.
Member Function Documentation
Event_OnEntityKilled()
void AnalyticsManagerClient::Event_OnEntityKilled (EntityAI victim, EntityAI killer, EntityAI source, bool is_headshot) inline private
Definition at line 173 of file analyticsmanagerclient.c.
    {
        if ( killer != null && killer.IsPlayer() && killer.GetID() == GetGame().GetPlayer().GetID() )
        {
            Achievements.OnPlayerKilled(victim, killer, source, is_headshot);
        }
    }
References GetGame(), GetID(), GetPlayer(), and Achievements::OnPlayerKilled().
Referenced by RegisterEvents(), and UnregisterEvents().
Event_OnPlayerIgnitedFireplace()
void AnalyticsManagerClient::Event_OnPlayerIgnitedFireplace (EFireIgniteType ignite_type) inline private
Definition at line 148 of file analyticsmanagerclient.c.
    {
        switch ( ignite_type )
        {
            case EFireIgniteType.Matchbox:
            {
                Achievements.OnActionIgniteMatchbox();
                break;
            }
            case EFireIgniteType.Roadflare:
            {
                Achievements.OnActionIgniteRoadflare();
                break;
            }
            case EFireIgniteType.HandDrill:
            {
                Achievements.OnActionIgniteDrill();
                break;
            }
        }
    }
References Achievements::OnActionIgniteDrill(), Achievements::OnActionIgniteMatchbox(), and Achievements::OnActionIgniteRoadflare().
Referenced by RegisterEvents(), and UnregisterEvents().
OnActionBandageTarget()
void AnalyticsManagerClient::OnActionBandageTarget () inline private
Definition at line 69 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionMedsSurvivor();
    }
References Achievements::OnActionMedsSurvivor().
Referenced by ActionBandageTarget::OnFinishProgressClient().
OnActionCookedSteak()
void AnalyticsManagerClient::OnActionCookedSteak () inline private
Definition at line 37 of file analyticsmanagerclient.c.
    {
        Achievements.OnCookedSteak();
    }
References Achievements::OnCookedSteak().
Referenced by CAContinuousTimeCooking::Execute().
OnActionDrink()
void AnalyticsManagerClient::OnActionDrink () inline private
Definition at line 29 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionDrink();
    }
References Achievements::OnActionDrink().
Referenced by AnimatedActionBase::End().
OnActionEat()
void AnalyticsManagerClient::OnActionEat () inline private
Definition at line 21 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionEat();
    }
References Achievements::OnActionEat().
Referenced by AnimatedActionBase::End().
OnActionFinishedGutDeer()
void AnalyticsManagerClient::OnActionFinishedGutDeer () inline private
Definition at line 53 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionGutDeer();
    }
References Achievements::OnActionGutDeer().
Referenced by ActionSkinning::OnFinishProgressClient().
OnActionFinishedShaveSelf()
void AnalyticsManagerClient::OnActionFinishedShaveSelf () inline private
Definition at line 45 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionShave();
    }
References Achievements::OnActionShave().
Referenced by ActionShave::OnFinishProgressClient().
OnActionRestrain()
void AnalyticsManagerClient::OnActionRestrain () inline private
Definition at line 61 of file analyticsmanagerclient.c.
    {
        Achievements.OnActionHandcuff();
    }
References Achievements::OnActionHandcuff().
Referenced by ActionHandcuffTarget::OnExecuteClient(), and ActionRestrainTarget::OnFinishProgressClient().
OnItemAttachedAtPlayer()
void AnalyticsManagerClient::OnItemAttachedAtPlayer (EntityAI item, string slot_name) inline private
Definition at line 77 of file analyticsmanagerclient.c.
    {
        bool weapon_present;
        bool melee_present;
        bool backpack_present;
        HumanInventory inventory;
        if ( GetDayZGame().GetGameState() != DayZGameState.IN_GAME )
        {
            return;
        }
        Man player = GetGame().GetPlayer();
        if (!player)
        {
            return;
        }
        inventory = player.GetHumanInventory();
        if ( player && inventory )
        {
            for ( int i = 0; i < GEAR_COUNT; ++i )
            {
                int slot_id = InventorySlots.GetSlotIdFromString(m_FullGear[i]);
                EntityAI att_item = inventory.FindAttachment( slot_id ); // Boris V [27.2.2019]: Consider using player.GetItemOnSlot(m_FullGear[i]) instead.
                if ( !att_item )
                {
                    //Print("index: "+ i +" slot_id: "+ slot_id +" = "+ att_item + " EMPTY");
                    continue;
                }
                //checks for firearm
                if (att_item.IsWeapon())
                    weapon_present = true;
                //checks for melee weapon
                else if (!att_item.IsWeapon() && att_item.GetInventory().HasInventorySlot(InventorySlots.GetSlotIdFromString("Melee")))
                    melee_present = true;
                //checks for backpack
                else if (!att_item.IsWeapon() && att_item.GetInventory().HasInventorySlot(InventorySlots.GetSlotIdFromString("Back")))
                    backpack_present = true;
                //Print("index: "+ i +" slot_id: "+ slot_id +" = "+ att_item + " ATTACHED");
            }
            //separate check for hand slot; TODO remove duplicates
            att_item = inventory.GetEntityInHands();
            if ( att_item )
            {
                //checks for firearm
                if (att_item.IsWeapon())
                    weapon_present = true;
                //checks for melee weapon
                else if (!att_item.IsWeapon() && att_item.GetInventory().HasInventorySlot(InventorySlots.GetSlotIdFromString("Melee")) )
                    melee_present = true;
                //checks for backpack
                else if (!att_item.IsWeapon() && att_item.GetInventory().HasInventorySlot(InventorySlots.GetSlotIdFromString("Back")))
                    backpack_present = true;
            }
            if (weapon_present && melee_present && backpack_present)
            {
                //Print("---EAchievementActionId.ACTION_EQUIP_GEAR");
                Achievements.OnEquippedFullGear();
            }
        }
    }
References GEAR_COUNT, GetDayZGame(), HumanInventory::GetEntityInHands(), GetGame(), GetGameState(), CGame::GetPlayer(), InventorySlots::GetSlotIdFromString(), m_FullGear, and Achievements::OnEquippedFullGear().
Referenced by ManBase::EEItemAttached(), and InventoryItem::EEItemLocationChanged().
RegisterEvents()
void AnalyticsManagerClient::RegisterEvents () inline private
Definition at line 6 of file analyticsmanagerclient.c.
    {
        ClientData.SyncEvent_OnEntityKilled.Insert(Event_OnEntityKilled);
        ClientData.SyncEvent_OnPlayerIgnitedFireplace.Insert(Event_OnPlayerIgnitedFireplace);
    }
References Event_OnEntityKilled(), Event_OnPlayerIgnitedFireplace(), ScriptInvoker::Insert(), ClientData::SyncEvent_OnEntityKilled, and ClientData::SyncEvent_OnPlayerIgnitedFireplace.
UnregisterEvents()
void AnalyticsManagerClient::UnregisterEvents () inline private
Definition at line 12 of file analyticsmanagerclient.c.
    {
        ClientData.SyncEvent_OnEntityKilled.Remove(Event_OnEntityKilled);
        ClientData.SyncEvent_OnPlayerIgnitedFireplace.Remove(Event_OnPlayerIgnitedFireplace);
    }
References Event_OnEntityKilled(), Event_OnPlayerIgnitedFireplace(), ScriptInvoker::Remove(), ClientData::SyncEvent_OnEntityKilled, and ClientData::SyncEvent_OnPlayerIgnitedFireplace.
Member Data Documentation
GEAR_COUNT
const int AnalyticsManagerClient::GEAR_COUNT = 3 static private
Definition at line 3 of file analyticsmanagerclient.c.
Referenced by OnItemAttachedAtPlayer().
m_FullGear
string AnalyticsManagerClient::m_FullGear[GEAR_COUNT] = {"Shoulder","Melee","Back"} static private
Definition at line 4 of file analyticsmanagerclient.c.
Referenced by OnItemAttachedAtPlayer().