DayzKode: InventoryItem Class Reference
InventoryItem Class Reference
Private Member Functions
void AddAction (typename actionName)
void AddLightSourceItem (ItemBase lightsource)
Adds a light source child.
bool AddQuantity (float value, bool destroy_config=true, bool destroy_forced=false)
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
override void AddTemperature (float value)
override void AddWet (float value)
override void AfterStoreLoad ()
bool AllowFoodConsumption ()
override bool CanBeCombined (EntityAI other_item, bool reservation_check=true, bool stack_max_limit=false)
bool CanBeCooked ()
bool CanBeCookedOnStick ()
bool CanBeDigged ()
bool CanBeDisinfected ()
bool CanBeMovedOverride ()
bool CanBeRepairedByCrafting ()
override bool CanBeSplit ()
bool CanDecay ()
override bool CanDisplayCargo ()
bool CanEat ()
bool CanExplodeInFire ()
protected bool CanHaveTemperature ()
protected bool CanHaveWetness ()
bool CanMakeGardenplot ()
override bool CanObstruct ()
bool CanPlayDeployLoopSound ()
protected bool CanProcessDecay ()
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveItemIntoCargo (EntityAI item)
bool CanRepair (ItemBase item_repair_kit)
override string ChangeIntoOnAttach (string slot)
override string ChangeIntoOnDetach ()
void CheckOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void Close ()
void CombineItems (ItemBase other_item, bool use_stack_max=true)
override void CombineItemsClient (EntityAI entity2, bool use_stack_max=true)
int ComputeQuantityUsed (ItemBase other_item, bool use_stack_max=true)
float ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max=true)
bool ContainsAgent (int agent_id)
void ConvertEnergyToQuantity ()
void CopyScriptPropertiesFrom (EntityAI oldItem)
bool DamageItemAttachments (float damage)
bool DamageItemInCargo (float damage)
void DeSerializeNumericalVars (array< float > floats)
void DoAmmoExplosion ()
override void EECargoIn (EntityAI item)
override void EEDelete (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEKilled (Object killer)
override void EEOnAfterLoad ()
override void EEOnCECreate ()
Called when entity is being created as new by CE/ Debug.
override void EOnContact (IEntity other, Contact extra)
override void EOnInit (IEntity other, int extra)
void ExplodeAmmo ()
override void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
bool GetActionWidgetOverride (out typename name)
If we need a different (handheld)item action widget displayed, the logic goes in here.
override int GetAgents ()
override string GetAttachmentSoundType ()
float GetBandagingEffectivity ()
void GetColor (out int r, out int g, out int b, out int a)
gets item's color variable as components
string GetColorString ()
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
int GetDamageSystemVersionChange ()
Re-sets DamageSystem changes.
void GetDebugActions (out TSelectableActionInfoArray outputList)
string GetDeployFinishSoundset ()
string GetDeploySoundset ()
float GetDeployTime ()
how long it takes to deploy this item in seconds
float GetDisinfectQuantity (int system=0, Param param1=null)
float GetEnergy ()
string GetExplosiveTriggerSlotName ()
float GetFilterDamageRatio ()
array< string > GetHeadHidingSelection ()
float GetHeatIsolation ()
float GetHeatIsolationInit ()
float GetInfectionChance (int system=0, Param param=null)
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
float GetItemModelLength ()
int GetItemSize ()
ScriptedLightBase GetLight ()
ItemBase GetLightSourceItem ()
int GetLiquidType ()
int GetLiquidTypeInit ()
string GetLockSoundSet ()
int GetLockType ()
string GetLoopDeploySoundset ()
int GetMuzzleID ()
Returns global muzzle ID. If not found, then it gets automatically registered.
int GetNumberOfItems ()
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
float GetOverheatingCoef ()
float GetOverheatingValue ()
string GetPlaceSoundset ()
float GetProtectionLevel (int type, bool consider_filter=false, int system=0)
override float GetQuantity ()
int GetQuantityInit ()
override int GetQuantityMax ()
int GetQuantityMin ()
float GetQuantityNormalized ()
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
override int GetQuickBarBonus ()
void GetRecipesActions (Man player, out TSelectableActionInfoArray outputList)
RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
Remotely controlled devices helpers.
float GetSingleInventoryItemWeight ()
override int GetTargetQuantityMax (int attSlotID=-1)
override float GetTemperature ()
override float GetTemperatureInit ()
override float GetTemperatureMax ()
override float GetTemperatureMin ()
float GetUnitWeight (bool include_wetness=true)
Returns weight of unit, useful for stackable items.
array< int > GetValidFinishers ()
returns an array of possible finishers
array< float > GetVariablesFloat ()
override float GetWet ()
override float GetWetInit ()
override float GetWetMax ()
override float GetWetMin ()
WrittenNoteData GetWrittenNoteData ()
bool HasFoodStage ()
bool HasMuzzle ()
Returns true if this item has a muzzle (weapons, suppressors)
bool HasQuantity ()
bool HidesSelectionBySlot ()
void HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB)
string IDToName (int id)
void IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
void InitializeActions ()
void InitItemVariables ()
override void InsertAgent (int agent, float count=1)
override bool IsBeingPlaced ()
bool IsBloodContainer ()
bool IsCargoException4x3 (EntityAI item)
bool IsColorSet ()
bool IsCombineAll (ItemBase other_item, bool use_stack_max=false)
bool IsDeployable ()
bool IsDeploySound ()
bool IsExplosive ()
bool IsFacingPlayer (PlayerBase player, string selection)
bool IsFullQuantity ()
override bool IsHeavyBehaviour ()
override bool IsHologram ()
override bool IsIgnoredByConstruction ()
override bool IsItemBase ()
bool IsLightSource ()
bool IsLiquidContainer ()
bool IsLiquidPresent ()
bool IsNVG ()
override bool IsOneHandedBehaviour ()
bool IsOpen ()
bool IsOverheatingEffectActive ()
bool IsPlaceSound ()
bool IsPlayerInside (PlayerBase player, string selection)
bool IsResultOfSplit ()
bool IsServerCheck (bool allow_client)
bool IsSoundSynchRemote ()
override bool IsTakeable ()
override bool IsTwoHandedBehaviour ()
bool IsVariableSet (int variable)
'true' if this variable has ever been changed from default
void ItemBase ()
void KillAllOverheatingParticles ()
override bool KindOf (string tag)
bool LoadAgents (ParamsReadContext ctx, int version)
void LoadParticleConfigOnFire (int id)
void LoadParticleConfigOnOverheating (int id)
bool LoadVariables (ParamsReadContext ctx, int version=-1)
void LockToParent ()
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
void MessageToOwnerAction (string text)
Send message to owner player in yellow color.
void MessageToOwnerFriendly (string text)
Send message to owner player in green color.
void MessageToOwnerImportant (string text)
Send message to owner player in red color.
void MessageToOwnerStatus (string text)
Send message to owner player in grey color.
int NameToID (string name)
bool OnAction (int action_id, Man player, ParamsReadContext ctx)
void OnActivatedByItem (notnull ItemBase item)
Called when this item is activated by other.
void OnActivatedByTripWire ()
void OnApply (PlayerBase player)
void OnAttachmentQuantityChanged (ItemBase item)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
void OnAttachmentQuantityChangedEx (ItemBase item, float delta)
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
override void OnCEUpdate ()
void OnCombine (ItemBase other_item)
override void OnCreatePhysics ()
void OnEndPlacement ()
override void OnEnergyAdded ()
override void OnEnergyConsumed ()
void OnInventoryEnter (Man player)
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
void OnInventoryExit (Man player)
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
override void OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void OnItemInHandsPlayerSwimStart (PlayerBase player)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
void OnOverheatingDecay ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementStarted (Man player)
void OnQuantityChanged (float delta)
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
override void OnRightClick ()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
void OnSyncVariables (ParamsReadContext ctx)
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
void Open ()
Implementations only.
void PerformDamageSystemReinit ()
void PlayAttachSound (string slot_type)
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
void PlayDeployFinishSound ()
void PlayDeploySound ()
void PlayDetachSound (string slot_type)
void PlayPlaceSound ()
protected void PreLoadSoundAttachmentType ()
Attachment Sound Type getting from config file.
protected void ProcessDecay (float delta, bool hasRootAsPlayer)
void ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
void ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB)
bool ReadVarsFromCTX (ParamsReadContext ctx, int version=-1)
void RefreshPhysics ()
void RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori)
void RemoveAction (typename actionName)
override void RemoveAgent (int agent_id)
override void RemoveAllAgents ()
override void RemoveAllAgentsExcept (int agents_to_keep_mask)
void RemoveItemVariable (int variable)
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
void RemoveLightSourceItem ()
bool Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight)
void SaveAgents (ParamsWriteContext ctx)
void SaveVariables (ParamsWriteContext ctx)
void SerializeNumericalVars (array< float > floats_out)
void SetActions ()
void SetCanBeMovedOverride (bool setting)
void SetCEBasedQuantity ()
void SetCleanness (int value, bool allow_client=false)
void SetColor (int r, int g, int b, int a)
void SetIsBeingPlaced (bool is_being_placed)
void SetIsDeploySound (bool is_deploy_sound)
void SetIsHologram (bool is_hologram)
void SetIsPlaceSound (bool is_place_sound)
void SetLiquidType (int value, bool allow_client=false)
bool SetQuantity (float value, bool destroy_config=true, bool destroy_forced=false, bool allow_client=false, bool clamp_to_stack_max=true)
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
void SetQuantityMax ()
void SetQuantityNormalized (float value, bool destroy_config=true, bool destroy_forced=false)
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
void SetResultOfSplit (bool value)
override void SetTakeable (bool pState)
override void SetTemperature (float value, bool allow_client=false)
override void SetTemperatureMax ()
void SetVariableMask (int variable)
override void SetWet (float value, bool allow_client=false)
override void SetWetMax ()
void SetZoneDamageCEInit ()
Sets zone damages to match randomized global health set by CE (CE spawn only)
void SoundSynchRemote ()
void SoundSynchRemoteReset ()
void SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player)
void SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col)
void SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id)
void SplitIntoStackMaxHands (PlayerBase player)
void SplitIntoStackMaxHandsClient (PlayerBase player)
void SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst)
void SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst)
ItemBase SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst)
void SplitItem (PlayerBase player)
void SplitItemToInventoryLocation (notnull InventoryLocation dst)
void StartOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void StopItemDynamicPhysics ()
void StopOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
void TransferAgents (int agents)
transfer agents from another item
void TransferModifiers (PlayerBase reciever)
void TransferVariablesFloat (array< float > float_vars)
void UnlockFromParent ()
Unlocks this item from its attachment slot of its parent.
void UpdateAllOverheatingParticles ()
void UpdateOverheating (ItemBase weapon=null, string ammoType="", ItemBase muzzle_owner=null, ItemBase suppressor=null, string config_to_search="")
override void UpdateWeight (WeightUpdateType updateType=WeightUpdateType.FULL, float weightAdjustment=0)
void WriteVarsToCTX (ParamsWriteContext ctx)
void ~ItemBase ()
Static Private Member Functions
static int GetDebugActionsMask ()
static void PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void SetDebugActionsMask (int mask)
static void StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
static void UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search)
Private Attributes
bool can_this_be_combined = false
bool m_ActionsInitialize
PluginAdminLog m_AdminLog
private int m_AttachedAgents
protected bool m_CanBeDigged
bool m_CanBeMovedOverride
bool m_CanShowQuantity
bool m_CanThisBeSplit = false
ref Timer m_CheckOverheating
int m_Cleanness
int m_CleannessInit
int m_CleannessMax
int m_CleannessMin
int m_ColorComponentA
int m_ColorComponentB
int m_ColorComponentG
int m_ColorComponentR
ref array< int > m_CompatibleLocks = new array<int>
float m_ConfigWeight = -1
ref TIntArray m_ContinuousActions
int m_Count
bool m_FixDamageSystemInit = false
bool m_HasQuantityBar
protected ref TStringArray m_HeadHidingSelections
float m_HeatIsolation
protected bool m_HideSelectionsBySlot
int m_ImpactSoundSurfaceHash
float m_ImpactSpeed
TInputActionMap m_InputActionMap
ref TIntArray m_InteractActions
bool m_IsBeingPlaced
bool m_IsDeploySound
bool m_IsHologram
bool m_IsOverheatingEffectActive
bool m_IsPlaceSound
bool m_IsSoundSynchRemote
bool m_IsStoreLoad = false
bool m_IsTakeable
int m_ItemBehaviour = -1
bool m_ItemBeingDroppedPhys
float m_ItemModelLength
ItemBase m_LightSourceItem
protected ref EffectSound m_LockingSound
protected string m_LockSoundSet = ""
protected int m_LockType
int m_MaxOverheatingValue = 0
ref map< int, ref array< ref WeaponParticlesOnOverheating > > m_OnOverheatingEffect
float m_OverheatingDecayInterval = 1
ref array< ref OverheatingParticle > m_OverheatingParticles
float m_OverheatingShots
ref Timer m_PhysDropTimer
int m_QuickBarBonus = 0
bool m_RecipesInitialized
int m_ShotsToStartOverheating = 0
ref TIntArray m_SingleUseActions
protected bool m_IsResultOfSplit string m_SoundAttType
distinguish if item has been created as new or it came from splitting (server only flag)
float m_StoreLoadedQuantity = float.LOWEST
bool m_ThrowItemOnDrop
int m_VariablesMask
int m_VarLiquidType
float m_VarQuantity
int m_VarQuantityInit
int m_VarQuantityMax
int m_VarQuantityMin
float m_VarStackMax
float m_VarTemperature
float m_VarTemperatureInit
float m_VarTemperatureMax
float m_VarTemperatureMin
float m_VarWet
float m_VarWetInit
float m_VarWetMax
float m_VarWetMin
bool m_WantPlayImpactSound
Static Private Attributes
static int m_DebugActionsMask
static ref map< typename, ref TInputActionMap > m_ItemTypeActionsMap = new map<typename, ref TInputActionMap>
static int m_LastRegisteredWeaponID = 0
static ref map< int, ref array< ref WeaponParticlesOnBulletCasingEject > > m_OnBulletCasingEjectEffect
static ref map< int, ref array< ref WeaponParticlesOnFire > > m_OnFireEffect
static ref map< string, int > m_WeaponTypeToID
Detailed Description
Definition at line 13 of file itembase.c.
Constructor & Destructor Documentation
~ItemBase()
void InventoryItem::~ItemBase () inline private
Definition at line 704 of file itembase.c.
    {
        if ( GetGame() && GetGame().GetPlayer() && ( !GetGame().IsDedicatedServer() ) )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            int r_index = player.GetHumanInventory().FindUserReservedLocationIndex(this);
            if (r_index >= 0)
            {
                    InventoryLocation r_il = new InventoryLocation;
                    player.GetHumanInventory().GetUserReservedLocation(r_index,r_il);
                    player.GetHumanInventory().ClearUserReservedLocationAtIndex(r_index);
                    int r_type = r_il.GetType();
                    if ( r_type == InventoryLocationType.CARGO || r_type == InventoryLocationType.PROXYCARGO )
                    {
                        r_il.GetParent().GetOnReleaseLock().Invoke( this );
                    }
                    else if ( r_type == InventoryLocationType.ATTACHMENT )
                    {
                        r_il.GetParent().GetOnAttachmentReleaseLock().Invoke( this, r_il.GetSlot() );
                    }
            }
            player.GetHumanInventory().ClearUserReservedLocation( this );
        }
        SEffectManager.DestroyEffect( m_LockingSound );
    }
References SEffectManager::DestroyEffect(), GetGame(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), and m_LockingSound.
Member Function Documentation
AddAction()
void InventoryItem::AddAction (typename actionName) inline private
Definition at line 304 of file itembase.c.
    {
        ActionBase action = ActionManagerBase.GetAction(actionName);
        if (!action)
        {
            Debug.LogError("Action " + actionName + " dosn't exist!");
            return;
        }
        typename ai = action.GetInputType();
        if (!ai)
        {
            m_ActionsInitialize = false;
            return;
        }
        array<ActionBase_Basic> action_array = m_InputActionMap.Get( ai );
        if (!action_array)
        {
            action_array = new array<ActionBase_Basic>;
            m_InputActionMap.Insert(ai, action_array);
        }
        if ( LogManager.IsActionLogEnable() )
        {
            Debug.ActionLog(action.ToString() + " -> " + ai, this.ToString() , "n/a", "Add action" );
        }
        if (action_array.Find(action) != -1)
        {
            Debug.Log("Action " + action.Type() + " already added to " + this + ", skipping!");
        }
        else
        {
            action_array.Insert(action);
        }
    }
References ActionBase(), Debug::ActionLog(), ActionManagerBase::GetAction(), LogManager::IsActionLogEnable(), Debug::Log(), Debug::LogError(), m_ActionsInitialize, and m_InputActionMap.
AddLightSourceItem()
void InventoryItem::AddLightSourceItem (ItemBase lightsource) inline private
Adds a light source child.
Definition at line 4711 of file itembase.c.
    {
        m_LightSourceItem = lightsource;
    }
References m_LightSourceItem.
AddQuantity()
bool InventoryItem::AddQuantity (float value, bool destroy_config = true, bool destroy_forced = false) inline private
add item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted
Definition at line 3297 of file itembase.c.
    {
        return SetQuantity(GetQuantity() + value, destroy_config, destroy_forced);
    }
References GetQuantity(), and SetQuantity().
AddTemperature()
override void InventoryItem::AddTemperature (float value) inline private
Definition at line 3707 of file itembase.c.
    {
        SetTemperature( value + GetTemperature() );
    }
References GetTemperature(), and SetTemperature().
AddWet()
override void InventoryItem::AddWet (float value) inline private
Definition at line 3764 of file itembase.c.
    {
        SetWet( GetWet() + value );
    }
References GetWet(), and SetWet().
AfterStoreLoad()
override void InventoryItem::AfterStoreLoad () inline private
Definition at line 3157 of file itembase.c.
    {
        super.AfterStoreLoad();
        if (m_FixDamageSystemInit)
        {
            PerformDamageSystemReinit();
        }
        if ( m_StoreLoadedQuantity != float.LOWEST )
        {
            SetQuantity(m_StoreLoadedQuantity);
            m_StoreLoadedQuantity = float.LOWEST;//IMPORTANT to do this !! we use 'm_StoreLoadedQuantity' inside SetQuantity to distinguish between initial quantity setting and the consequent(normal gameplay) calls
        }
        UpdateWeight();
    }
References float::LOWEST, LOWEST, m_FixDamageSystemInit, m_StoreLoadedQuantity, PerformDamageSystemReinit(), SetQuantity(), and UpdateWeight().
AllowFoodConsumption()
bool InventoryItem::AllowFoodConsumption () inline private
Definition at line 3834 of file itembase.c.
    {
        return true;
    }
CanBeCombined()
override bool InventoryItem::CanBeCombined (EntityAI other_item, bool reservation_check = true, bool stack_max_limit = false) inline private
Definition at line 1957 of file itembase.c.
    {
        //Print("CanBeCombined - " + this + ": " + GetQuantity() + " + " + other_item + ": " + other_item.GetQuantity());
        //TODO: delete check zero quantity check after fix double posts hands fsm events
        if ( !other_item || GetType() != other_item.GetType() || (IsFullQuantity() && other_item.GetQuantity() > 0) || other_item == this)
            return false;
        if ( GetHealthLevel() == GameConstants.STATE_RUINED || other_item.GetHealthLevel() == GameConstants.STATE_RUINED )
            return false;
        //can_this_be_combined = ConfigGetBool("canBeSplit");
        if ( !can_this_be_combined )
            return false;
        Magazine mag = Magazine.Cast(this);
        if (mag)
        {
            if ( mag.GetAmmoCount() >= mag.GetAmmoMax())
                return false;
            if(stack_max_limit)
            {
                Magazine other_mag = Magazine.Cast(other_item);
                if(other_item)
                {
                    if(mag.GetAmmoCount() + other_mag.GetAmmoCount() > mag.GetAmmoMax())
                        return false;
                }
            }
        }
        else
        {
            //TODO: delete check zero quantity check after fix double posts hands fsm events
            if ( GetQuantity() >= GetQuantityMax() && other_item.GetQuantity() > 0  )
                return false;
            if (stack_max_limit && (GetQuantity() + other_item.GetQuantity()  > GetQuantityMax()))
                return false;
        }
        PlayerBase player = null;
        if ( CastTo( player, GetHierarchyRootPlayer() ) ) //false when attached to player's attachment slot
        {
            if ( player.GetInventory().HasAttachment( this ) )
                return false;
            if ( player.IsItemsToDelete())
                return false;
        }
        if ( reservation_check && (GetInventory().HasInventoryReservation( this, null ) || other_item.GetInventory().HasInventoryReservation( other_item, null )))
            return false;
        int slotID;
        string slotName;
        if (GetInventory().GetCurrentAttachmentSlotInfo(slotID,slotName) && GetHierarchyParent().GetInventory().GetSlotLock(slotID))
            return false;
        return true;
    }
References can_this_be_combined, GetCurrentAttachmentSlotInfo(), GetHealthLevel(), GetQuantity(), GetQuantityMax(), GetSlotLock(), GetType(), HasInventoryReservation(), IsFullQuantity(), and GameConstants::STATE_RUINED.
CanBeCooked()
bool InventoryItem::CanBeCooked () inline private
Definition at line 2473 of file itembase.c.
    {
        return false;
    }
CanBeCookedOnStick()
bool InventoryItem::CanBeCookedOnStick () inline private
Definition at line 2478 of file itembase.c.
    {
        return false;
    }
CanBeDigged()
bool InventoryItem::CanBeDigged () inline private
Definition at line 904 of file itembase.c.
    {
        return m_CanBeDigged;
    }
References m_CanBeDigged.
CanBeDisinfected()
bool InventoryItem::CanBeDisinfected () inline private
Definition at line 3184 of file itembase.c.
    {
        return false;
    }
CanBeMovedOverride()
bool InventoryItem::CanBeMovedOverride () inline private
Definition at line 2513 of file itembase.c.
    {
        return m_CanBeMovedOverride;
    }
References m_CanBeMovedOverride.
CanBeRepairedByCrafting()
bool InventoryItem::CanBeRepairedByCrafting () inline private
Definition at line 861 of file itembase.c.
    {
        return true;
    }
CanBeSplit()
override bool InventoryItem::CanBeSplit () inline private
Definition at line 1490 of file itembase.c.
    {
        if ( m_CanThisBeSplit )
            return ( GetQuantity() > 1 );
        return false;
    }
References GetQuantity(), and m_CanThisBeSplit.
CanDecay()
bool InventoryItem::CanDecay () inline private
Definition at line 4643 of file itembase.c.
    {
        // return true used on selected food clases so they can decay
        return false;
    }
CanDisplayCargo()
override bool InventoryItem::CanDisplayCargo () inline private
Definition at line 4130 of file itembase.c.
{return IsOpen();}
References IsOpen().
CanEat()
bool InventoryItem::CanEat () inline private
Definition at line 2454 of file itembase.c.
    {
        return true;
    }
CanExplodeInFire()
bool InventoryItem::CanExplodeInFire () inline private
Definition at line 2448 of file itembase.c.
    {
        return false;
    }
CanHaveTemperature()
protected bool InventoryItem::CanHaveTemperature () inline private
Definition at line 4662 of file itembase.c.
    {
        // return true used on selected items that have a temperature effect
        return false;
    }
CanHaveWetness()
protected bool InventoryItem::CanHaveWetness () inline private
Definition at line 4656 of file itembase.c.
    {
        // return true used on selected items that have a wetness effect
        return false;
    }
CanMakeGardenplot()
bool InventoryItem::CanMakeGardenplot () inline private
Definition at line 909 of file itembase.c.
    {
        return false;
    }
CanObstruct()
override bool InventoryItem::CanObstruct () inline private
Definition at line 878 of file itembase.c.
    {
        return !IsPlayerInside(PlayerBase.Cast(g_Game.GetPlayer()), "");
    }
References g_Game, and ItemBase::IsPlayerInside().
CanPlayDeployLoopSound()
bool InventoryItem::CanPlayDeployLoopSound () inline private
Definition at line 4474 of file itembase.c.
    {
        return IsBeingPlaced() && IsSoundSynchRemote();
    }
References IsBeingPlaced(), and IsSoundSynchRemote().
CanProcessDecay()
protected bool InventoryItem::CanProcessDecay () inline private
Definition at line 4649 of file itembase.c.
    {
        // this is stub, implemented on Edible_Base class
        // used to determine whether it is still necessary for the food to decay
        return false;
    }
CanPutAsAttachment()
override bool InventoryItem::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 4150 of file itembase.c.
    {
        if (!super.CanPutAsAttachment(parent))
        {
            return false;
        }
        if (!IsRuined() && !parent.IsRuined())
        {
            return true;
        }
        return false;
    }
References IsRuined().
CanPutInCargo()
override bool InventoryItem::CanPutInCargo (EntityAI parent) inline private
Definition at line 4136 of file itembase.c.
    {
        if ( parent )
        {
            if ( parent.IsInherited(DayZInfected) )
                return true;
            if ( !parent.IsRuined() )
                return true;
        }
        return true;
    }
CanReceiveAttachment()
override bool InventoryItem::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 4174 of file itembase.c.
    {
        //removed 15.06. coz of loading from storage -> after load items in cargo was lost -> waiting for proper solution
        //if ( GetHealthLevel() == GameConstants.STATE_RUINED )
        //  return false;
        GameInventory attachmentInv = attachment.GetInventory();
        if (attachmentInv && attachmentInv.GetCargo() && attachmentInv.GetCargo().GetItemCount() > 0)
        {
            if (GetHierarchyParent() && !GetHierarchyParent().IsInherited(PlayerBase))
                return false;
        }
        return super.CanReceiveAttachment( attachment, slotId );
    }
CanReceiveItemIntoCargo()
override bool InventoryItem::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 4165 of file itembase.c.
    {
        //removed 15.06. coz of loading from storage -> after load items in cargo was lost -> waiting for proper solution
        //if ( GetHealthLevel() == GameConstants.STATE_RUINED )
        //  return false;
        return super.CanReceiveItemIntoCargo( item );
    }
CanRepair()
bool InventoryItem::CanRepair (ItemBase item_repair_kit) inline private
Definition at line 2484 of file itembase.c.
    {
        PluginRepairing module_repairing = PluginRepairing.Cast( GetPlugin(PluginRepairing) );
        return module_repairing.CanRepair(this, item_repair_kit);
    }
References GetPlugin().
ChangeIntoOnAttach()
override string InventoryItem::ChangeIntoOnAttach (string slot) inline private
Definition at line 1313 of file itembase.c.
    {
        int idx;
        TStringArray inventory_slots = new TStringArray;
        TStringArray attach_types = new TStringArray;
        ConfigGetTextArray("ChangeInventorySlot",inventory_slots);
        if (inventory_slots.Count() < 1) //is string
        {
            inventory_slots.Insert(ConfigGetString("ChangeInventorySlot"));
            attach_types.Insert(ConfigGetString("ChangeIntoOnAttach"));
        }
        else //is array
        {
            ConfigGetTextArray("ChangeIntoOnAttach",attach_types);
        }
        idx = inventory_slots.Find(slot);
        if (idx < 0)
            return "";
        return attach_types.Get(idx);
    }
References ConfigGetString(), and ConfigGetTextArray().
ChangeIntoOnDetach()
override string InventoryItem::ChangeIntoOnDetach () inline private
Definition at line 1337 of file itembase.c.
    {
        int idx = -1;
        string slot;
        TStringArray inventory_slots = new TStringArray;
        TStringArray detach_types = new TStringArray;
        this.ConfigGetTextArray("ChangeInventorySlot",inventory_slots);
        if (inventory_slots.Count() < 1) //is string
        {
            inventory_slots.Insert(this.ConfigGetString("ChangeInventorySlot"));
            detach_types.Insert(this.ConfigGetString("ChangeIntoOnDetach"));
        }
        else //is array
        {
            this.ConfigGetTextArray("ChangeIntoOnDetach",detach_types);
            if (detach_types.Count() < 1)
                detach_types.Insert(this.ConfigGetString("ChangeIntoOnDetach"));
        }
        for (int i = 0; i < inventory_slots.Count(); i++)
        {
            slot = inventory_slots.Get(i);
        }
        if (slot != "")
        {
            if (detach_types.Count() == 1)
                idx = 0;
            else
                idx = inventory_slots.Find(slot);
        }
        if (idx < 0)
            return "";
        return detach_types.Get(idx);
    }
References ConfigGetString(), and ConfigGetTextArray().
CheckOverheating()
void InventoryItem::CheckOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
Definition at line 506 of file itembase.c.
    {
        if (m_OverheatingShots >= m_ShotsToStartOverheating  &&  IsOverheatingEffectActive())
            UpdateOverheating(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
        if (m_OverheatingShots >= m_ShotsToStartOverheating  &&  !IsOverheatingEffectActive())
            StartOverheating(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
        if (m_OverheatingShots < m_ShotsToStartOverheating  &&  IsOverheatingEffectActive())
            StopOverheating(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
        if (m_OverheatingShots > m_MaxOverheatingValue)
        {
            m_OverheatingShots = m_MaxOverheatingValue;
        }
    }
References IsOverheatingEffectActive(), m_MaxOverheatingValue, m_OverheatingShots, m_ShotsToStartOverheating, StartOverheating(), StopOverheating(), and UpdateOverheating().
Close()
void InventoryItem::Close () inline private
Definition at line 4128 of file itembase.c.
{}
CombineItems()
void InventoryItem::CombineItems (ItemBase other_item, bool use_stack_max = true) inline private
Definition at line 2059 of file itembase.c.
    {
        if( !CanBeCombined(other_item, false) )
            return;
        if( !IsMagazine() && other_item )
        {
            float quantity_used = ComputeQuantityUsedEx(other_item,use_stack_max);
            if( quantity_used != 0 )
            {
                float hp1 = GetHealth01("","");
                float hp2 = other_item.GetHealth01("","");
                float hpResult = ((hp1*GetQuantity()) + (hp2*quantity_used));
                hpResult = hpResult / ( GetQuantity() + quantity_used );
                hpResult *= GetMaxHealth();
                Math.Round( hpResult );
                SetHealth("", "Health", hpResult );
                AddQuantity(quantity_used);
                other_item.AddQuantity(-quantity_used);
            }
        }
        OnCombine(other_item);
    }
References AddQuantity(), ItemBase::CanBeCombined(), ComputeQuantityUsedEx(), GetHealth01(), GetMaxHealth(), GetQuantity(), IsMagazine(), ItemBase::OnCombine(), Math::Round(), and SetHealth().
CombineItemsClient()
override void InventoryItem::CombineItemsClient (EntityAI entity2, bool use_stack_max = true) inline private
Definition at line 787 of file itembase.c.
    {
        /*
        ref Param1<EntityAI> item = new Param1<EntityAI>(entity2);
        RPCSingleParam( ERPCs.RPC_ITEM_COMBINE, item, GetGame().GetPlayer() );
        */
        ItemBase item2 = ItemBase.Cast(entity2);
        if ( GetGame().IsClient() )
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                ctx.Write(-1);
                ItemBase i1 = this; // @NOTE: workaround for correct serialization
                ctx.Write(i1);
                ctx.Write(item2);
                ctx.Write(use_stack_max);
                ctx.Write(-1);
                ctx.Send();
                if ( IsCombineAll(item2, use_stack_max) )
                {
                    GetGame().GetPlayer().GetInventory().AddInventoryReservationEx(item2,null,GameInventory.c_InventoryReservationTimeoutShortMS);
                }
            }
        }
        else if ( !GetGame().IsMultiplayer() )
        {
            CombineItems(item2, use_stack_max);
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), CombineItems(), GetGame(), CGame::GetPlayer(), INPUT_UDT_ITEM_MANIPULATION, IsCombineAll(), ScriptInputUserData::Send(), and Serializer::Write().
ComputeQuantityUsed()
int InventoryItem::ComputeQuantityUsed (ItemBase other_item, bool use_stack_max = true) inline private
Definition at line 2035 of file itembase.c.
    {
        return ComputeQuantityUsedEx(other_item, use_stack_max);
    }
References ComputeQuantityUsedEx().
ComputeQuantityUsedEx()
float InventoryItem::ComputeQuantityUsedEx (ItemBase other_item, bool use_stack_max = true) inline private
Definition at line 2040 of file itembase.c.
    {
        float other_item_quantity = other_item.GetQuantity();
        float this_free_space;
        float stack_max = GetQuantityMax();
        this_free_space = stack_max - GetQuantity();
        if( other_item_quantity > this_free_space )
        {
            return this_free_space;
        }
        else
        {
            return other_item_quantity;
        }
    }
References GetQuantity(), and GetQuantityMax().
ContainsAgent()
bool InventoryItem::ContainsAgent (int agent_id) inline private
Definition at line 3964 of file itembase.c.
    {
        if( agent_id & m_AttachedAgents )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References m_AttachedAgents.
ConvertEnergyToQuantity()
void InventoryItem::ConvertEnergyToQuantity () inline private
Definition at line 3680 of file itembase.c.
    {
        if ( GetGame().IsServer()  &&  HasEnergyManager()  &&  GetCompEM().HasConversionOfEnergyToQuantity() )
        {
            if ( HasQuantity() )
            {
                float energy_0to1 = GetCompEM().GetEnergy0To1();
                SetQuantityNormalized( energy_0to1 );
            }
        }
    }
References GetGame(), HasQuantity(), and SetQuantityNormalized().
CopyScriptPropertiesFrom()
void InventoryItem::CopyScriptPropertiesFrom (EntityAI oldItem) inline private
Definition at line 4705 of file itembase.c.
    {
        MiscGameplayFunctions.TransferItemProperties(oldItem, this);
    }
DamageItemAttachments()
bool InventoryItem::DamageItemAttachments (float damage) inline private
Definition at line 1473 of file itembase.c.
    {
        int attachment_count = GetInventory().AttachmentCount();
        if ( attachment_count > 0 )
        {
            int random_pick = Math.RandomInt(0, attachment_count);
            ItemBase attachment = ItemBase.Cast( GetInventory().GetAttachmentFromIndex(random_pick));
            if (!attachment.IsExplosive())
            {
                attachment.AddHealth("","",damage);
                return true;
            }
        }
        return false;
    }
References GetAttachmentFromIndex(), and Math::RandomInt().
DamageItemInCargo()
bool InventoryItem::DamageItemInCargo (float damage) inline private
Definition at line 1454 of file itembase.c.
    {
        if ( GetInventory().GetCargo() )
        {
            int item_count = GetInventory().GetCargo().GetItemCount();
            if ( item_count > 0 )
            {
                int random_pick = Math.RandomInt(0, item_count);
                ItemBase item = ItemBase.Cast( GetInventory().GetCargo().GetItem(random_pick) );
                if (!item.IsExplosive())
                {
                    item.AddHealth("","",damage);
                    return true;
                }
            }
        }
        return false;
    }
References GetCargo(), GetItem(), and Math::RandomInt().
DeSerializeNumericalVars()
void InventoryItem::DeSerializeNumericalVars (array< float > floats) inline private
Definition at line 2766 of file itembase.c.
    {
        // the order of serialization must be the same as the order of de-serialization
        int index = 0;
        int mask = Math.Round(floats.Get(index));
        index++;
        //--------------------------------------------
        if( mask & VARIABLE_QUANTITY )
        {
            if ( m_IsStoreLoad )
            {
                m_StoreLoadedQuantity = floats.Get(index);
            }
            else
            {
                float quantity = floats.Get(index);
                SetQuantity(quantity, true, false, false, false );
            }
            index++;
        }
        //--------------------------------------------
        if( mask & VARIABLE_TEMPERATURE )
        {
            float temperature = floats.Get(index);
            SetTemperature(temperature);
            index++;
        }
        //--------------------------------------------
        if( mask & VARIABLE_WET )
        {
            float wet = floats.Get(index);
            SetWet(wet);
            index++;
        }
        //--------------------------------------------
        if( mask & VARIABLE_LIQUIDTYPE )
        {
            int liquidtype = Math.Round(floats.Get(index));
            SetLiquidType(liquidtype);
            index++;
        }
        //--------------------------------------------
        if( mask & VARIABLE_COLOR )
        {
            m_ColorComponentR = Math.Round(floats.Get(index));
            index++;
            m_ColorComponentG = Math.Round(floats.Get(index));
            index++;
            m_ColorComponentB = Math.Round(floats.Get(index));
            index++;
            m_ColorComponentA = Math.Round(floats.Get(index));
            index++;
        }
        if( mask & VARIABLE_CLEANNESS )
        {
            int cleanness = Math.Round(floats.Get(index));
            SetCleanness(cleanness);
            index++;
        }
        //--------------------------------------------
    }
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_IsStoreLoad, m_StoreLoadedQuantity, Math::Round(), SetCleanness(), SetLiquidType(), SetQuantity(), SetTemperature(), SetWet(), VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_TEMPERATURE, and VARIABLE_WET.
DoAmmoExplosion()
void InventoryItem::DoAmmoExplosion () inline private
Definition at line 1389 of file itembase.c.
    {
        Magazine magazine = Magazine.Cast( this );
        int pop_sounds_count = 6;
        string pop_sounds[ 6 ] = { "ammopops_1","ammopops_2","ammopops_3","ammopops_4","ammopops_5","ammopops_6" };
        //play sound
        int sound_idx = Math.RandomInt( 0, pop_sounds_count - 1 );
        string sound_name = pop_sounds[ sound_idx ];
        GetGame().CreateSoundOnObject( this, sound_name, 20, false );
        //remove ammo count
        magazine.ServerAddAmmoCount( -1 );
        //if condition then repeat -> ExplodeAmmo
        float min_temp_to_explode   = 100;      //min temperature for item to explode
        if ( magazine.GetAmmoCount() > 0 && GetTemperature() >= min_temp_to_explode )   //TODO ? add check for parent -> fireplace
        {
            ExplodeAmmo();
        }
    }
References CGame::CreateSoundOnObject(), ExplodeAmmo(), GetGame(), GetTemperature(), and Math::RandomInt().
EECargoIn()
override void InventoryItem::EECargoIn (EntityAI item) inline private
Definition at line 954 of file itembase.c.
    {
        super.EECargoIn(item);
    }
EEDelete()
override void InventoryItem::EEDelete (EntityAI parent) inline private
Definition at line 1229 of file itembase.c.
    {
        super.EEDelete(parent);
        PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
        if(player)
        {
            OnInventoryExit(player);
            if(player.IsAlive())
            {
                int r_index = player.GetHumanInventory().FindUserReservedLocationIndex(this);
                if(r_index >= 0 )
                {
                    InventoryLocation r_il = new InventoryLocation;
                    player.GetHumanInventory().GetUserReservedLocation(r_index,r_il);
                    player.GetHumanInventory().ClearUserReservedLocationAtIndex(r_index);
                    int r_type = r_il.GetType();
                    if( r_type == InventoryLocationType.CARGO || r_type == InventoryLocationType.PROXYCARGO )
                    {
                        r_il.GetParent().GetOnReleaseLock().Invoke( this );
                    }
                    else if( r_type == InventoryLocationType.ATTACHMENT )
                    {
                        r_il.GetParent().GetOnAttachmentReleaseLock().Invoke( this, r_il.GetSlot() );
                    }
                }
                player.RemoveQuickBarEntityShortcut(this);
            }
        }
    }
References InventoryLocation::GetParent(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), and ItemBase::OnInventoryExit().
EEHealthLevelChanged()
override void InventoryItem::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
drops content of container when ruined in fireplace
Definition at line 1857 of file itembase.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        if (GetGame().IsServer())
        {
            if (newLevel == GameConstants.STATE_RUINED)
            {
                EntityAI parent = GetHierarchyParent();
                if (parent && parent.IsFireplace())
                {
                    CargoBase cargo = GetInventory().GetCargo();
                    if (cargo)
                    {
                        for (int i = 0; i < cargo.GetItemCount(); ++i)
{
                            parent.GetInventory().TakeEntityToInventory(InventoryMode.SERVER, FindInventoryLocationType.CARGO, cargo.GetItem(i));
                        }
                    }
                }
            }
            if (IsResultOfSplit())
            {
                // reset the splitting result flag, return to normal item behavior
                SetResultOfSplit(false);
                return;
            }
            if (m_Cleanness != 0 && oldLevel < newLevel && newLevel != 0)
            {
                SetCleanness(0);//unclean the item upon damage dealt
            }
        }
    }
References GetGame(), CargoBase::GetItem(), CargoBase::GetItemCount(), IsResultOfSplit(), m_Cleanness, SetCleanness(), SetResultOfSplit(), and GameConstants::STATE_RUINED.
EEHitBy()
override void InventoryItem::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 1413 of file itembase.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        const int CHANCE_DAMAGE_CARGO = 4;
        const int CHANCE_DAMAGE_ATTACHMENT = 1;
        const int CHANCE_DAMAGE_NOTHING = 2;
        if ( IsClothing() || IsContainer() || IsItemTent() )
        {
            float dmg = damageResult.GetDamage("","Health") * -0.5;
            int chances;
            int rnd;
            if (GetInventory().GetCargo())
            {
                chances = CHANCE_DAMAGE_CARGO + CHANCE_DAMAGE_ATTACHMENT + CHANCE_DAMAGE_NOTHING;
                rnd = Math.RandomInt(0,chances);
                if (rnd < CHANCE_DAMAGE_CARGO)
                {
                    DamageItemInCargo(dmg);
                }
                else if (rnd < (chances - CHANCE_DAMAGE_NOTHING) )
                {
                    DamageItemAttachments(dmg);
                }
            }
            else
            {
                chances = CHANCE_DAMAGE_ATTACHMENT + CHANCE_DAMAGE_NOTHING;
                rnd = Math.RandomInt(0,chances);
                if (rnd < CHANCE_DAMAGE_ATTACHMENT)
                {
                    DamageItemAttachments(dmg);
                }
            }
        }
    }
References component, DamageItemAttachments(), DamageItemInCargo(), GetCargo(), TotalDamageResult::GetDamage(), ItemBase::IsClothing(), ItemBase::IsContainer(), ItemBase::IsItemTent(), and Math::RandomInt().
EEItemLocationChanged()
override void InventoryItem::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 959 of file itembase.c.
    {
        super.EEItemLocationChanged(oldLoc,newLoc);
        PlayerBase new_player = null;
        PlayerBase old_player = null;
        if ( newLoc.GetParent() )
            new_player = PlayerBase.Cast(newLoc.GetParent().GetHierarchyRootPlayer());
        if ( oldLoc.GetParent() )
            old_player = PlayerBase.Cast(oldLoc.GetParent().GetHierarchyRootPlayer());
        /*if ( old_player )
            old_player.UpdateQuickBarEntityVisibility(this);*/
        /*if ( old_player != new_player )
        {
            if ( old_player )
                old_player.SetEnableQuickBarEntityShortcut(this, false);
            if ( new_player )
                new_player.SetEnableQuickBarEntityShortcut(this, true);
        }*/
        if (old_player && oldLoc.GetType() == InventoryLocationType.HANDS)
        {
            int r_index = old_player.GetHumanInventory().FindUserReservedLocationIndex(this);
            if (r_index >= 0)
            {
                    InventoryLocation r_il = new InventoryLocation;
                    old_player.GetHumanInventory().GetUserReservedLocation(r_index,r_il);
                    old_player.GetHumanInventory().ClearUserReservedLocationAtIndex(r_index);
                    int r_type = r_il.GetType();
                    if ( r_type == InventoryLocationType.CARGO || r_type == InventoryLocationType.PROXYCARGO )
                    {
                        r_il.GetParent().GetOnReleaseLock().Invoke( this );
                    }
                    else if ( r_type == InventoryLocationType.ATTACHMENT )
                    {
                        r_il.GetParent().GetOnAttachmentReleaseLock().Invoke( this, r_il.GetSlot() );
                    }
            }
            //old_player.GetHumanInventory().ClearUserReservedLocation(this);
            //GetOnReleaseLock().Invoke(this);
        }
        if (newLoc.GetType() == InventoryLocationType.HANDS)
        {
            if (new_player)
                new_player.ForceStandUpForHeavyItems(newLoc.GetItem());
            if (new_player == old_player)
            {
                if ( oldLoc.GetParent() && !(oldLoc.GetParent() != new_player && oldLoc.GetType() == InventoryLocationType.ATTACHMENT) && new_player.GetHumanInventory().LocationGetEntity(oldLoc) == NULL )
                {
                    if ( oldLoc.GetType() == InventoryLocationType.CARGO)
                    {
                        if ( oldLoc.GetParent().GetInventory().TestAddEntityInCargoExLoc(oldLoc, false, false, false, true, false, false) )
{
                            new_player.GetHumanInventory().SetUserReservedLocation(this,oldLoc);
                        }
                    }
                }
                if ( new_player.GetHumanInventory().FindUserReservedLocationIndex( this ) >= 0 )
                {
                    int type = oldLoc.GetType();
                    if ( type == InventoryLocationType.CARGO || type == InventoryLocationType.PROXYCARGO )
                    {
                        oldLoc.GetParent().GetOnSetLock().Invoke( this );
                    }
                    else if ( type == InventoryLocationType.ATTACHMENT )
                    {
                        oldLoc.GetParent().GetOnAttachmentSetLock().Invoke( this, oldLoc.GetSlot() );
                    }
                }
                if (!m_OldLocation)
                {
                    m_OldLocation = new InventoryLocation;
                }
                m_OldLocation.Copy(oldLoc);
            }
            else
            {
                if (m_OldLocation)
                {
                    m_OldLocation.Reset();
                }
            }
            GetGame().GetAnalyticsClient().OnItemAttachedAtPlayer(this,"Hands");
        }
        else
        {
            if (new_player)
            {
                int res_index = new_player.GetHumanInventory().FindCollidingUserReservedLocationIndex(this, newLoc );
                if (res_index >= 0)
                {
                    InventoryLocation il = new InventoryLocation;
                    new_player.GetHumanInventory().GetUserReservedLocation(res_index,il);
                    ItemBase it = ItemBase.Cast(il.GetItem());
                    new_player.GetHumanInventory().ClearUserReservedLocationAtIndex(res_index);
                    int rel_type = il.GetType();
                    if ( rel_type == InventoryLocationType.CARGO || rel_type == InventoryLocationType.PROXYCARGO )
                    {
                        il.GetParent().GetOnReleaseLock().Invoke( it );
                    }
                    else if ( rel_type == InventoryLocationType.ATTACHMENT )
                    {
                        il.GetParent().GetOnAttachmentReleaseLock().Invoke( it, il.GetSlot() );
                    }
                    //it.GetOnReleaseLock().Invoke(it);
                }
            }
            else if (old_player && newLoc.GetType() == InventoryLocationType.GROUND && m_ThrowItemOnDrop)
            {
                //Print("---ThrowPhysically---");
                //ThrowPhysically(old_player, vector.Zero);
                m_ThrowItemOnDrop = false;
            }
            if (m_OldLocation)
            {
                m_OldLocation.Reset();
            }
        }
    }
References InventoryLocation::Copy(), CGame::GetAnalyticsClient(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), m_ThrowItemOnDrop, AnalyticsManagerClient::OnItemAttachedAtPlayer(), and InventoryLocation::Reset().
EEKilled()
override void InventoryItem::EEKilled (Object killer) inline private
item is able to explode in fire
Definition at line 1263 of file itembase.c.
    {
        super.EEKilled(killer);
        if (killer && killer.IsFireplace() && CanExplodeInFire())
        {
            if (GetTemperature() >= GameConstants.ITEM_TEMPERATURE_TO_EXPLODE_MIN)
            {
                if (IsMagazine())
                {
                    if (Magazine.Cast(this).GetAmmoCount() > 0)
                    {
                        ExplodeAmmo();
                    }
                }
                else
                {
                    Explode(DamageType.EXPLOSION);
                }
            }
        }
    }
References ItemBase::CanExplodeInFire(), Explode(), ExplodeAmmo(), GetTemperature(), IsMagazine(), and GameConstants::ITEM_TEMPERATURE_TO_EXPLODE_MIN.
EEOnAfterLoad()
override void InventoryItem::EEOnAfterLoad () inline private
Definition at line 3174 of file itembase.c.
    {
        super.EEOnAfterLoad();
        if (m_FixDamageSystemInit)
        {
            m_FixDamageSystemInit = false;
        }
    }
References m_FixDamageSystemInit.
EEOnCECreate()
override void InventoryItem::EEOnCECreate () inline private
Called when entity is being created as new by CE/ Debug.
Definition at line 4114 of file itembase.c.
    {
        //Print("EEOnCECreate");
        if( !IsMagazine() && HasQuantity() ) SetCEBasedQuantity();
        //SetCEBasedQuantity();
        SetZoneDamageCEInit();
    }
References HasQuantity(), IsMagazine(), ItemBase::SetCEBasedQuantity(), and SetZoneDamageCEInit().
EOnContact()
override void InventoryItem::EOnContact (IEntity other, Contact extra) inline private
Definition at line 1093 of file itembase.c.
    {
        super.EOnContact(other, extra);
        float impactSpeed = ProcessImpactSound(other, extra, m_ConfigWeight, m_ImpactSoundSurfaceHash);
        if (impactSpeed > 0.0)
        {
            m_ImpactSpeed  = impactSpeed;
            if (GetGame().IsClient() || !GetGame().IsMultiplayer())
            {
                PlayImpactSound(m_ConfigWeight, m_ImpactSpeed, m_ImpactSoundSurfaceHash);
            }
            else
            {
                m_WantPlayImpactSound = true;
                SetSynchDirty();
            }
        }
/*      if (m_ItemBeingDroppedPhys)
        {
            Print("ItemBase | EOnContact");
            SetDynamicPhysicsLifeTime(0.5);
            m_ItemBeingDroppedPhys = false;
        }
        return;
        //--------------------------------
        if (m_ItemBeingDroppedPhys && extra.Normal[1] == 1.0 || (Math.AbsFloat(extra.RelativeNormalVelocityAfter) < 0.03 && extra.Normal[1] > 0.9))
        {
            Print("ItemBase | EOnContact");
            SetDynamicPhysicsLifeTime(0.5);
            m_ItemBeingDroppedPhys = false;
        }*/
    }
References GetGame(), m_ConfigWeight, m_ImpactSoundSurfaceHash, m_ImpactSpeed, and m_WantPlayImpactSound.
EOnInit()
override void InventoryItem::EOnInit (IEntity other, int extra) inline private
Definition at line 1225 of file itembase.c.
    {
    }
ExplodeAmmo()
void InventoryItem::ExplodeAmmo () inline private
Definition at line 1376 of file itembase.c.
    {
        //timer
        ref Timer explode_timer = new Timer( CALL_CATEGORY_SYSTEM );
        //min/max time
        float min_time = 1;
        float max_time = 3;
        float delay = Math.RandomFloat( min_time, max_time );
        explode_timer.Run( delay, this, "DoAmmoExplosion" );
    }
References CALL_CATEGORY_SYSTEM, and Math::RandomFloat().
GetActions()
override void InventoryItem::GetActions (typename action_input_type , out array< ActionBase_Basic > actions) inline private
Definition at line 281 of file itembase.c.
    {
        if (!m_ActionsInitialize)
        {
            m_ActionsInitialize = true;
            InitializeActions();
        }
        actions = m_InputActionMap.Get(action_input_type);
    }
References InitializeActions(), m_ActionsInitialize, and m_InputActionMap.
GetActionWidgetOverride()
bool InventoryItem::GetActionWidgetOverride (out typename name) inline private
If we need a different (handheld)item action widget displayed, the logic goes in here.
Definition at line 4733 of file itembase.c.
    {
        return false;
    }
GetAgents()
override int InventoryItem::GetAgents () inline private
Definition at line 4011 of file itembase.c.
    {
        return m_AttachedAgents;
    }
References m_AttachedAgents.
GetAttachmentSoundType()
override string InventoryItem::GetAttachmentSoundType () inline private
Definition at line 4379 of file itembase.c.
    {
        return m_SoundAttType;
    }
References m_SoundAttType.
GetBandagingEffectivity()
float InventoryItem::GetBandagingEffectivity () inline private
Definition at line 4523 of file itembase.c.
    {
        return 1.0;
    };
GetColor()
void InventoryItem::GetColor (out int r, out int g, out int b, out int a) inline private
gets item's color variable as components
Definition at line 3864 of file itembase.c.
    {
        r = m_ColorComponentR;
        g = m_ColorComponentG;
        b = m_ColorComponentB;
        a = m_ColorComponentA;
    }
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, and m_ColorComponentR.
GetColorString()
string InventoryItem::GetColorString () inline private
Returns item's PROCEDURAL color as formated string, i.e. "#(argb,8,8,3)color(0.15,0.15,0.15,1.0,CO)".
Definition at line 3878 of file itembase.c.
    {
        int r,g,b,a;
        GetColor(r,g,b,a);
        r = r/255;
        g = g/255;
        b = b/255;
        a = a/255;
        return MiscGameplayFunctions.GetColorString(r, g, b, a);
    }
References GetColor().
GetDamageSystemVersionChange()
int InventoryItem::GetDamageSystemVersionChange () inline private
Re-sets DamageSystem changes.
Returns
storage version on which the config changes occured (default -1, to be overriden!)
Note
Significant changes to DamageSystem in item configs have to be re-set by increasing the storage version and overriding this method. Default return is -1 (does nothing).
Definition at line 698 of file itembase.c.
    {
        return -1;
    }
GetDebugActions()
void InventoryItem::GetDebugActions (out TSelectableActionInfoArray outputList) inline private
Definition at line 2113 of file itembase.c.
    {
        //weight
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.GET_TOTAL_WEIGHT, "Print Weight"));
        //quantity
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.ADD_QUANTITY, "Quantity +20%"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.REMOVE_QUANTITY, "Quantity -20%"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.SET_QUANTITY_0, "Set Quantity 0"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.SET_MAX_QUANTITY, "Set Quantity Max"));
        //health
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.ADD_HEALTH, "Health +20%"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.REMOVE_HEALTH, "Health -20%"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DESTROY_HEALTH, "Health 0"));
        //temperature
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.ADD_TEMPERATURE, "Temperature +20"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.REMOVE_TEMPERATURE, "Temperature -20"));
        //wet
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.ADD_WETNESS, "Wetness +20"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.REMOVE_WETNESS, "Wetness -20"));
        //liquidtype
        if( IsLiquidContainer() )
        {
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.LIQUIDTYPE_UP, "LiquidType Next"));
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.LIQUIDTYPE_DOWN, "LiquidType Previous"));
        }
        //strings
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.INJECT_STRING_TIGER, "Inject String Tiger"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.INJECT_STRING_RABBIT, "Inject String Rabbit"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.SPIN, "Spin"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.MAKE_SPECIAL, "Make Special"));
        // watch
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.WATCH_ITEM, "Watch"));
        outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DELETE, "Delete"));
        string button1, button2, button3, button4;
        GetDebugButtonNames(button1, button2, button3, button4);
        if (button1)
        {
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START, button1));
        }
        if (button2)
        {
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START+1, button2));
        }
        if (button3)
        {
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START+2, button3));
        }
        if (button4)
        {
            outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START+3, button4));
        }
        // print bullets
        //outputList.Insert(new TSelectableActionInfo(SAT_DEBUG_ACTION, EActions.PRINT_BULLETS, "Print Bullets"));
        //ctx.AddAction("ShowID",USE_ENUM_HERE,NULL,2000,false,false);
        //ctx.AddAction("Predend Consume",USE_ENUM_HERE,NULL, 1011,false,false);
        //ctx.AddAction("IsEmpty",USE_ENUM_HERE,NULL, 1012,false,false);
        //ctx.AddAction("HasAnyCargo",USE_ENUM_HERE,NULL, 1013,false,false);
        //ctx.AddAction("LightOn",USE_ENUM_HERE,NULL, 1013,false,false);
        //ctx.AddAction("Set Health 200", USE_ENUM_HERE, NULL, 1003, false, false);
        //ctx.AddAction("PrintQuantityMax", USE_ENUM_HERE, NULL, 1000, false, false);
        //ctx.AddAction("Print Classname", USE_ENUM_HERE, NULL, 1000, false, false);
        //ctx.AddAction("Has In Cargo", USE_ENUM_HERE, NULL, 1000, false, false);
        //ctx.AddAction("Print Health(new)", USE_ENUM_HERE, NULL, 1000, false, false);
        //ctx.AddAction("Quantity -1", USE_ENUM_HERE, NULL, 1004, false, false);
        //ctx.AddAction("IsMagazine", USE_ENUM_HERE, NULL, 1005, false, false);
        //ctx.AddAction("Ammo +1", USE_ENUM_HERE, NULL, 1006, false, false);
        //ctx.AddAction("Set Health 1", USE_ENUM_HERE, NULL, 1002, false, false);
        //ctx.AddAction("Ammo -1", USE_ENUM_HERE, NULL, 1007, false, false);
        //ctx.AddAction("Ammo SetMax", USE_ENUM_HERE, NULL, 1008, false, false);
        //ctx.AddAction("LightOff",USE_ENUM_HERE,NULL, 1022,false,false);
    }
References GetDebugButtonNames(), IsLiquidContainer(), and SAT_DEBUG_ACTION.
GetDebugActionsMask()
static int InventoryItem::GetDebugActionsMask () inline static private
Definition at line 736 of file itembase.c.
    {
        return ItemBase.m_DebugActionsMask;
    }
GetDeployFinishSoundset()
string InventoryItem::GetDeployFinishSoundset () inline private
Definition at line 4422 of file itembase.c.
    {
    }
GetDeploySoundset()
string InventoryItem::GetDeploySoundset () inline private
Definition at line 4407 of file itembase.c.
    {
    }
GetDeployTime()
float InventoryItem::GetDeployTime () inline private
how long it takes to deploy this item in seconds
Definition at line 4347 of file itembase.c.
    {
        return UATimeSpent.DEFAULT_DEPLOY;
    }
References UATimeSpent::DEFAULT_DEPLOY.
GetDisinfectQuantity()
float InventoryItem::GetDisinfectQuantity (int system = 0, Param param1 = null) inline private
Definition at line 655 of file itembase.c.
    {
        return 250;//default value
    }
GetEnergy()
float InventoryItem::GetEnergy () inline private
Definition at line 3654 of file itembase.c.
    {
        float energy = 0;
        if ( this.HasEnergyManager() )
        {
            energy = this.GetCompEM().GetEnergy();
        }
        return energy;
    }
GetExplosiveTriggerSlotName()
string InventoryItem::GetExplosiveTriggerSlotName () inline private
Definition at line 849 of file itembase.c.
    {
        return "";
    }
GetFilterDamageRatio()
float InventoryItem::GetFilterDamageRatio () inline private
Definition at line 660 of file itembase.c.
    {
        return 0;
    }
GetHeadHidingSelection()
array< string > InventoryItem::GetHeadHidingSelection () inline private
Definition at line 4528 of file itembase.c.
    {
        return m_HeadHidingSelections;
    }
References m_HeadHidingSelections.
GetHeatIsolation()
float InventoryItem::GetHeatIsolation () inline private
Definition at line 3741 of file itembase.c.
    {
        return m_HeatIsolation;
    }
References m_HeatIsolation.
GetHeatIsolationInit()
float InventoryItem::GetHeatIsolationInit () inline private
Definition at line 3737 of file itembase.c.
    {
        return ConfigGetFloat("heatIsolation");
    }
References ConfigGetFloat().
GetInfectionChance()
float InventoryItem::GetInfectionChance (int system = 0, Param param = null) inline private
Infection chance while/after using this item, originally used for wound infection after bandaging, params 'system' and 'param' can allow usage by other systems as well.
Definition at line 649 of file itembase.c.
    {
        return 0.0;
    }
GetItemModelLength()
float InventoryItem::GetItemModelLength () inline private
Definition at line 3811 of file itembase.c.
    {
        if (ConfigIsExisting("itemModelLength"))
        {
            return ConfigGetFloat("itemModelLength");
        }
        return 0;
    }
References ConfigGetFloat(), and ConfigIsExisting().
GetItemSize()
int InventoryItem::GetItemSize () inline private
Definition at line 2498 of file itembase.c.
    {
        /*
        vector v_size = this.ConfigGetVector("itemSize");
        int v_size_x = v_size[0];
        int v_size_y = v_size[1];
        int size = v_size_x * v_size_y;
        return size;
        */
        return 1;
    }
GetLight()
ScriptedLightBase InventoryItem::GetLight () private
GetLightSourceItem()
ItemBase InventoryItem::GetLightSourceItem () inline private
Definition at line 4721 of file itembase.c.
    {
        return m_LightSourceItem;
    }
References m_LightSourceItem.
GetLiquidType()
int InventoryItem::GetLiquidType () inline private
Definition at line 3903 of file itembase.c.
    {
        return m_VarLiquidType;
    }
References m_VarLiquidType.
GetLiquidTypeInit()
int InventoryItem::GetLiquidTypeInit () inline private
Definition at line 3898 of file itembase.c.
    {
        return ConfigGetInt("varLiquidTypeInit");
    }
References ConfigGetInt().
GetLockSoundSet()
string InventoryItem::GetLockSoundSet () inline private
Definition at line 3847 of file itembase.c.
    {
        return m_LockSoundSet;
    }
References m_LockSoundSet.
GetLockType()
int InventoryItem::GetLockType () inline private
Definition at line 3842 of file itembase.c.
    {
        return m_LockType;
    }
References m_LockType.
GetLoopDeploySoundset()
string InventoryItem::GetLoopDeploySoundset () inline private
Definition at line 4417 of file itembase.c.
    {
    }
GetMuzzleID()
int InventoryItem::GetMuzzleID () inline private
Returns global muzzle ID. If not found, then it gets automatically registered.
Definition at line 675 of file itembase.c.
    {
        if (!m_WeaponTypeToID)
            m_WeaponTypeToID = new map<string, int>;
        if ( m_WeaponTypeToID.Contains( GetType() ) )
        {
            return m_WeaponTypeToID.Get( GetType() );
        }
        else
        {
            // Register new weapon ID
            m_WeaponTypeToID.Insert(GetType(), ++m_LastRegisteredWeaponID);
        }
        return m_LastRegisteredWeaponID;
    }
References GetType(), m_LastRegisteredWeaponID, and m_WeaponTypeToID.
GetNumberOfItems()
int InventoryItem::GetNumberOfItems () inline private
Returns the number of items in cargo, otherwise returns 0(non-cargo objects). Recursive.
Definition at line 3593 of file itembase.c.
    {
        int item_count = 0;
        ItemBase item;
        if ( GetInventory().GetCargo() != NULL )
        {
            item_count = GetInventory().GetCargo().GetItemCount();
        }
        for ( int i = 0; i < GetInventory().AttachmentCount(); i++ )
        {
            Class.CastTo(item,GetInventory().GetAttachmentFromIndex(i));
            if ( item )
                item_count += item.GetNumberOfItems();
        }
        return item_count;
    }
References Class::CastTo(), and GetCargo().
GetOverheatingCoef()
float InventoryItem::GetOverheatingCoef () inline private
Definition at line 585 of file itembase.c.
    {
        if (m_MaxOverheatingValue > 0)
            return (m_OverheatingShots - m_ShotsToStartOverheating) / m_MaxOverheatingValue;
        return -1;
    }
References m_MaxOverheatingValue, m_OverheatingShots, and m_ShotsToStartOverheating.
GetOverheatingValue()
float InventoryItem::GetOverheatingValue () inline private
Definition at line 485 of file itembase.c.
    {
        return m_OverheatingShots;
    }
References m_OverheatingShots.
GetPlaceSoundset()
string InventoryItem::GetPlaceSoundset () inline private
Definition at line 4412 of file itembase.c.
    {
    }
GetProtectionLevel()
float InventoryItem::GetProtectionLevel (int type, bool consider_filter = false, int system = 0) inline private
Definition at line 4074 of file itembase.c.
    {
        if (IsDamageDestroyed() || (HasQuantity() && GetQuantity() <= 0) )
        {
            return 0;
        }
        if( GetInventory().GetAttachmentSlotsCount() != 0 )//is it an item with attachable filter ?
        {
            ItemBase filter = ItemBase.Cast(FindAttachmentBySlotName("GasMaskFilter"));
            if (filter )
            {
                return filter.GetProtectionLevel(type, false, system);//it's a valid filter, return the protection
            }
            else return 0;//otherwise return 0 when no filter attached
        }
        string subclass_path, entryName;
        switch (type)
        {
            case DEF_BIOLOGICAL:
                entryName = "biological";
                break;
            case DEF_CHEMICAL:
                entryName = "chemical";
                break;
            default:
                entryName = "biological";
                break;
        }
        subclass_path = "CfgVehicles " + this.GetType() + " Protection ";
        return GetGame().ConfigGetFloat(subclass_path + entryName);
    }
References CGame::ConfigGetFloat(), DEF_BIOLOGICAL, DEF_CHEMICAL, GetAttachmentSlotsCount(), GetGame(), GetQuantity(), GetType(), HasQuantity(), and IsDamageDestroyed().
GetQuantity()
override float InventoryItem::GetQuantity () inline private
Definition at line 3392 of file itembase.c.
    {
        return m_VarQuantity;
    }
References m_VarQuantity.
GetQuantityInit()
int InventoryItem::GetQuantityInit () inline private
Definition at line 3375 of file itembase.c.
    {
        return m_VarQuantityInit;
    }
References m_VarQuantityInit.
GetQuantityMax()
override int InventoryItem::GetQuantityMax () inline private
Definition at line 3332 of file itembase.c.
    {
        float max = 0;
        InventoryLocation il = new InventoryLocation;
        if (GetInventory())
            GetInventory().GetCurrentInventoryLocation(il);
        int slot = il.GetSlot();
        if ( slot != -1 )
            max = InventorySlots.GetStackMaxForSlotId( slot );
        if ( max <= 0 )
            max = m_VarStackMax;
        if ( max <= 0 )
            max = m_VarQuantityMax;
        return max;
    }
References InventoryLocation::GetSlot(), InventorySlots::GetStackMaxForSlotId(), m_VarQuantityMax, and m_VarStackMax.
GetQuantityMin()
int InventoryItem::GetQuantityMin () inline private
Definition at line 3370 of file itembase.c.
    {
        return m_VarQuantityMin;
    }
References m_VarQuantityMin.
GetQuantityNormalized()
float InventoryItem::GetQuantityNormalized () inline private
Gets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, value 2500 will result in 0.5)
Definition at line 3318 of file itembase.c.
    {
        return Math.InverseLerp(GetQuantityMin(), GetQuantityMax(),m_VarQuantity );
    }
References GetQuantityMax(), GetQuantityMin(), Math::InverseLerp(), and m_VarQuantity.
GetQuickBarBonus()
override int InventoryItem::GetQuickBarBonus () inline private
Definition at line 264 of file itembase.c.
    {
        return m_QuickBarBonus;
    }
References m_QuickBarBonus.
GetRecipesActions()
void InventoryItem::GetRecipesActions (Man player, out TSelectableActionInfoArray outputList) inline private
Definition at line 2093 of file itembase.c.
    {
        PlayerBase p = PlayerBase.Cast( player );
        array<int> recipes_ids = p.m_Recipes;
        PluginRecipesManager module_recipes_manager = PluginRecipesManager.Cast( GetPlugin(PluginRecipesManager) );
        if( module_recipes_manager )
        {
            EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
            module_recipes_manager.GetValidRecipes( ItemBase.Cast( this ), ItemBase.Cast( item_in_hands ),recipes_ids, PlayerBase.Cast( player ) );
        }
        for(int i = 0;i < recipes_ids.Count();i++)
        {
            int key = recipes_ids.Get(i);
            string recipe_name = module_recipes_manager.GetRecipeName(key);
            outputList.Insert( new TSelectableActionInfo( SAT_CRAFTING, key, recipe_name ) );
        }
    }
References HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), GetPlugin(), and SAT_CRAFTING.
GetRemotelyActivatedItemBehaviour()
RemotelyActivatedItemBehaviour InventoryItem::GetRemotelyActivatedItemBehaviour () private
Remotely controlled devices helpers.
GetSingleInventoryItemWeight()
float InventoryItem::GetSingleInventoryItemWeight () inline private
Definition at line 3403 of file itembase.c.
    {
        float item_wetness = GetWet();
        float itemQuantity = 0;
        float Weight = 0;
        if (GetQuantity() != 0)
        {
            itemQuantity = GetQuantity();
        }
        if ( m_CanThisBeSplit ) //quantity determines size of the stack
        {
            Weight = ((item_wetness + 1) * m_ConfigWeight * itemQuantity);
        }
        else if (ConfigGetString("stackedUnit") == "cm") //duct tape, at the moment
        {
            int MaxLength = ConfigGetInt("varQuantityMax");
            Weight = ((item_wetness + 1) * m_ConfigWeight * itemQuantity/MaxLength);
        }
        else if (itemQuantity != 1) //quantity determines weight of item without container (i.e. sardines in a can)
        {
            Weight = ((item_wetness + 1) * (m_ConfigWeight + itemQuantity));
        }
        else
        {
            Weight = ((item_wetness + 1) * m_ConfigWeight);
        }
        return Math.Round(Weight);
    }
References ConfigGetInt(), ConfigGetString(), GetQuantity(), GetWet(), m_CanThisBeSplit, m_ConfigWeight, and Math::Round().
GetTargetQuantityMax()
override int InventoryItem::GetTargetQuantityMax (int attSlotID = -1) inline private
Definition at line 3354 of file itembase.c.
    {
        float quantity_max = 0;
        if (attSlotID != -1)
            quantity_max = InventorySlots.GetStackMaxForSlotId( attSlotID );
        if ( quantity_max <= 0 )
            quantity_max = m_VarStackMax;
        if ( quantity_max <= 0 )
            quantity_max = m_VarQuantityMax;
        return quantity_max;
    }
References InventorySlots::GetStackMaxForSlotId(), m_VarQuantityMax, and m_VarStackMax.
GetTemperature()
override float InventoryItem::GetTemperature () inline private
Definition at line 3717 of file itembase.c.
    {
        return m_VarTemperature;
    }
References m_VarTemperature.
GetTemperatureInit()
override float InventoryItem::GetTemperatureInit () inline private
Definition at line 3722 of file itembase.c.
    {
        return m_VarTemperatureInit;
    }
References m_VarTemperatureInit.
GetTemperatureMax()
override float InventoryItem::GetTemperatureMax () inline private
Definition at line 3732 of file itembase.c.
    {
        return m_VarTemperatureMax;
    }
References m_VarTemperatureMax.
GetTemperatureMin()
override float InventoryItem::GetTemperatureMin () inline private
Definition at line 3727 of file itembase.c.
    {
        return m_VarTemperatureMin;
    }
References m_VarTemperatureMin.
GetUnitWeight()
float InventoryItem::GetUnitWeight (bool include_wetness = true) inline private
Returns weight of unit, useful for stackable items.
Definition at line 3613 of file itembase.c.
    {
        float weight = 0;
        float wetness = 1;
        if (include_wetness)
            wetness += GetWet();
        if ( m_CanThisBeSplit ) //quantity determines size of the stack
        {
            weight = wetness * m_ConfigWeight;
        }
        else if (ConfigGetFloat("liquidContainerType") > 0) //is a liquid container, default liquid weight is set to 1. May revisit later?
        {
            weight = 1;
        }
        return weight;
    }
References ConfigGetFloat(), GetWet(), m_CanThisBeSplit, and m_ConfigWeight.
GetValidFinishers()
array< int > InventoryItem::GetValidFinishers () inline private
returns an array of possible finishers
Definition at line 4727 of file itembase.c.
    {
        return null;
    }
GetVariablesFloat()
array< float > InventoryItem::GetVariablesFloat () inline private
Definition at line 2680 of file itembase.c.
    {
        CachedObjectsArrays.ARRAY_FLOAT.Clear();
        SerializeNumericalVars(CachedObjectsArrays.ARRAY_FLOAT);
        return CachedObjectsArrays.ARRAY_FLOAT;
    }
References CachedObjectsArrays::ARRAY_FLOAT, and SerializeNumericalVars().
GetWet()
override float InventoryItem::GetWet () inline private
Definition at line 3774 of file itembase.c.
    {
        return m_VarWet;
    }
References m_VarWet.
GetWetInit()
override float InventoryItem::GetWetInit () inline private
Definition at line 3789 of file itembase.c.
    {
        return m_VarWetInit;
    }
References m_VarWetInit.
GetWetMax()
override float InventoryItem::GetWetMax () inline private
Definition at line 3779 of file itembase.c.
    {
        return m_VarWetMax;
    }
References m_VarWetMax.
GetWetMin()
override float InventoryItem::GetWetMin () inline private
Definition at line 3784 of file itembase.c.
    {
        return m_VarWetMin;
    }
References m_VarWetMin.
GetWrittenNoteData()
WrittenNoteData InventoryItem::GetWrittenNoteData () inline private
Definition at line 4538 of file itembase.c.
{};
HasFoodStage()
bool InventoryItem::HasFoodStage () inline private
Definition at line 2467 of file itembase.c.
    {
        string config_path = string.Format("CfgVehicles %1 Food FoodStages", GetType());
        return GetGame().ConfigIsExisting( config_path );
    }
References CGame::ConfigIsExisting(), GetGame(), and GetType().
HasMuzzle()
bool InventoryItem::HasMuzzle () inline private
Returns true if this item has a muzzle (weapons, suppressors)
Definition at line 666 of file itembase.c.
    {
        if (IsInherited(Weapon)  ||  IsInherited(SuppressorBase))
            return true;
        return false;
    }
HasQuantity()
bool InventoryItem::HasQuantity () inline private
Definition at line 3380 of file itembase.c.
    {
        if( GetQuantityMax() - GetQuantityMin() == 0 )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
References GetQuantityMax(), and GetQuantityMin().
HidesSelectionBySlot()
bool InventoryItem::HidesSelectionBySlot () inline private
Definition at line 4533 of file itembase.c.
    {
        return m_HideSelectionsBySlot;
    }
References m_HideSelectionsBySlot.
HierarchyCheck()
void InventoryItem::HierarchyCheck (out bool hasParent, out bool hasRootAsPlayer, out ItemBase refParentIB) inline private
Definition at line 4621 of file itembase.c.
    {
        // hierarchy check for an item to decide whether it has some parent and it is in some player inventory
        EntityAI parent = GetHierarchyParent();
        if ( !parent )
        {
            hasParent = false;
            hasRootAsPlayer = false;
        }
        else
        {
            hasParent = true;
            hasRootAsPlayer = (GetHierarchyRootPlayer() != null);
            refParentIB = ItemBase.Cast( parent );
        }
    }
IDToName()
string InventoryItem::IDToName (int id) inline private
Definition at line 2693 of file itembase.c.
    {
        PluginVariables plugin = PluginVariables.Cast( GetPlugin(PluginVariables) );
        return plugin.GetName(id);
    }
References GetPlugin().
IncreaseOverheating()
void InventoryItem::IncreaseOverheating (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline private
Definition at line 490 of file itembase.c.
    {
        if (m_MaxOverheatingValue > 0)
        {
            m_OverheatingShots++;
            if (!m_CheckOverheating)
                    m_CheckOverheating = new Timer( CALL_CATEGORY_SYSTEM );
            m_CheckOverheating.Stop();
            m_CheckOverheating.Run(m_OverheatingDecayInterval, this, "OnOverheatingDecay");
            CheckOverheating(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
        }
    }
References CALL_CATEGORY_SYSTEM, CheckOverheating(), m_CheckOverheating, m_MaxOverheatingValue, m_OverheatingDecayInterval, and m_OverheatingShots.
InitializeActions()
void InventoryItem::InitializeActions () inline private
Definition at line 269 of file itembase.c.
    {
        m_InputActionMap = m_ItemTypeActionsMap.Get( this.Type() );
        if (!m_InputActionMap)
        {
            TInputActionMap iam = new TInputActionMap;
            m_InputActionMap = iam;
            SetActions();
            m_ItemTypeActionsMap.Insert( this.Type(), m_InputActionMap);
        }
    }
References m_InputActionMap, m_ItemTypeActionsMap, ItemBase::SetActions(), and Type.
InitItemVariables()
void InventoryItem::InitItemVariables () inline private
Definition at line 185 of file itembase.c.
    {
        m_VarQuantityInit = ConfigGetInt("varQuantityInit");
        m_VarQuantity = m_VarQuantityInit;//should be by the CE, this is just a precaution
        m_VarQuantityMin = ConfigGetInt("varQuantityMin");
        m_VarQuantityMax = ConfigGetInt("varQuantityMax");
        m_VarStackMax = ConfigGetFloat("varStackMax");
        m_Count = ConfigGetInt("count");
        m_CanShowQuantity = ConfigGetBool("quantityShow");
        m_HasQuantityBar = ConfigGetBool("quantityBar");
        m_VarTemperatureInit = ConfigGetFloat("varTemperatureInit");
        m_VarTemperature = m_VarTemperatureInit;
        m_VarTemperatureMin = ConfigGetFloat("varTemperatureMin");
        m_VarTemperatureMax = ConfigGetFloat("varTemperatureMax");
        m_CleannessInit = ConfigGetInt("varCleannessInit");
        m_Cleanness = m_CleannessInit;
        m_CleannessMin = ConfigGetInt("varCleannessMin");
        m_CleannessMax = ConfigGetInt("varCleannessMax");
        m_WantPlayImpactSound = false;
        m_ImpactSpeed = 0.0;
        m_VarWetInit = ConfigGetFloat("varWetInit");
        m_VarWet = m_VarWetInit;
        m_VarWetMin = ConfigGetFloat("varWetMin");
        m_VarWetMax = ConfigGetFloat("varWetMax");
        m_VarLiquidType = GetLiquidTypeInit();
        m_IsBeingPlaced = false;
        m_IsHologram = false;
        m_IsPlaceSound = false;
        m_IsDeploySound = false;
        m_IsTakeable = true;
        m_IsSoundSynchRemote = false;
        m_CanBeMovedOverride = false;
        m_HeatIsolation = GetHeatIsolationInit();
        m_ItemModelLength = GetItemModelLength();
        m_CanBeDigged = ConfigGetBool("canBeDigged");
        ConfigGetIntArray("compatibleLocks", m_CompatibleLocks);
        m_LockType = ConfigGetInt("lockType");
        //Define if item can be split and set ability to be combined accordingly
        if (ConfigIsExisting("canBeSplit"))
        {
            can_this_be_combined = ConfigGetBool("canBeSplit");
            m_CanThisBeSplit = can_this_be_combined;
        }
        if (ConfigIsExisting("itemBehaviour"))
            m_ItemBehaviour = ConfigGetInt("itemBehaviour");
        //RegisterNetSyncVariableInt("m_VariablesMask");
        if ( HasQuantity() ) RegisterNetSyncVariableFloat("m_VarQuantity", GetQuantityMin(), m_VarQuantityMax );
        RegisterNetSyncVariableFloat("m_VarTemperature", GetTemperatureMin(),GetTemperatureMax() );
        RegisterNetSyncVariableFloat("m_VarWet", GetWetMin(), GetWetMax(), 2 );
        RegisterNetSyncVariableInt("m_VarLiquidType");
        RegisterNetSyncVariableInt("m_Cleanness",0,1);
        RegisterNetSyncVariableBoolSignal("m_WantPlayImpactSound");
        RegisterNetSyncVariableFloat("m_ImpactSpeed");
        RegisterNetSyncVariableInt("m_ImpactSoundSurfaceHash");
        RegisterNetSyncVariableInt("m_ColorComponentR", 0, 255);
        RegisterNetSyncVariableInt("m_ColorComponentG", 0, 255);
        RegisterNetSyncVariableInt("m_ColorComponentB", 0, 255);
        RegisterNetSyncVariableInt("m_ColorComponentA", 0, 255);
        RegisterNetSyncVariableBool("m_IsBeingPlaced");
        RegisterNetSyncVariableBool("m_IsTakeable");
        RegisterNetSyncVariableBool("m_IsHologram");
        m_LockSoundSet = ConfigGetString("lockSoundSet");
    }
References can_this_be_combined, ConfigGetBool(), ConfigGetFloat(), ConfigGetInt(), ConfigGetIntArray(), ConfigGetString(), ConfigIsExisting(), GetHeatIsolationInit(), GetItemModelLength(), GetLiquidTypeInit(), GetQuantityMin(), GetTemperatureMax(), GetTemperatureMin(), GetWetMax(), GetWetMin(), HasQuantity(), m_CanBeDigged, m_CanBeMovedOverride, m_CanShowQuantity, m_CanThisBeSplit, m_Cleanness, m_CleannessInit, m_CleannessMax, m_CleannessMin, m_CompatibleLocks, m_Count, m_HasQuantityBar, m_HeatIsolation, m_ImpactSpeed, m_IsBeingPlaced, m_IsDeploySound, m_IsHologram, m_IsPlaceSound, m_IsSoundSynchRemote, m_IsTakeable, m_ItemBehaviour, m_ItemModelLength, m_LockSoundSet, m_LockType, m_VarLiquidType, m_VarQuantity, m_VarQuantityInit, m_VarQuantityMax, m_VarQuantityMin, m_VarStackMax, m_VarTemperature, m_VarTemperatureInit, m_VarTemperatureMax, m_VarTemperatureMin, m_VarWet, m_VarWetInit, m_VarWetMax, m_VarWetMin, and m_WantPlayImpactSound.
InsertAgent()
override void InventoryItem::InsertAgent (int agent, float count = 1) inline private
Definition at line 3996 of file itembase.c.
    {
        if( count < 1 )
            return;
        //Debug.Log("Inserting Agent on item: " + agent.ToString() +" count: " + count.ToString());
        m_AttachedAgents = (agent | m_AttachedAgents);
    }
References m_AttachedAgents.
IsBeingPlaced()
override bool InventoryItem::IsBeingPlaced () inline private
Definition at line 883 of file itembase.c.
    {
        return m_IsBeingPlaced;
    }
References m_IsBeingPlaced.
IsBloodContainer()
bool InventoryItem::IsBloodContainer () inline private
Definition at line 832 of file itembase.c.
    {
        return false;
    }
IsCargoException4x3()
bool InventoryItem::IsCargoException4x3 (EntityAI item) inline private
Definition at line 4700 of file itembase.c.
    {
        return ( item.IsKindOf( "Cauldron" ) || item.IsKindOf( "Pot" ) || item.IsKindOf( "FryingPan" ) || item.IsKindOf( "SmallProtectorCase" ) || ( item.IsKindOf( "PortableGasStove" ) && item.FindAttachmentBySlotName("CookingEquipment") ) );
    }
IsColorSet()
bool InventoryItem::IsColorSet () inline private
Definition at line 3872 of file itembase.c.
    {
        return IsVariableSet(VARIABLE_COLOR);
    }
References IsVariableSet(), and VARIABLE_COLOR.
IsCombineAll()
bool InventoryItem::IsCombineAll (ItemBase other_item, bool use_stack_max = false) inline private
Definition at line 2020 of file itembase.c.
    {
        return ComputeQuantityUsed( other_item, use_stack_max ) == other_item.GetQuantity();
    }
References ComputeQuantityUsed().
IsDeployable()
bool InventoryItem::IsDeployable () inline private
Definition at line 4341 of file itembase.c.
    {
        return false;
    }
IsDeploySound()
bool InventoryItem::IsDeploySound () inline private
Definition at line 4442 of file itembase.c.
    {
        return m_IsDeploySound;
    }
References m_IsDeploySound.
IsExplosive()
bool InventoryItem::IsExplosive () inline private
explosive
Definition at line 844 of file itembase.c.
    {
        return false;
    }
IsFacingPlayer()
bool InventoryItem::IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 868 of file itembase.c.
    {
        return true;
    }
IsFullQuantity()
bool InventoryItem::IsFullQuantity () inline private
Definition at line 3397 of file itembase.c.
    {
        return GetQuantity() >= GetQuantityMax();
    }
References GetQuantity(), and GetQuantityMax().
IsHeavyBehaviour()
override bool InventoryItem::IsHeavyBehaviour () inline private
Definition at line 4311 of file itembase.c.
    {
        if (m_ItemBehaviour == 0)
        {
            return true;
        }
        return false;
    }
References m_ItemBehaviour.
IsHologram()
override bool InventoryItem::IsHologram () inline private
Definition at line 899 of file itembase.c.
    {
        return m_IsHologram;
    }
References m_IsHologram.
IsIgnoredByConstruction()
override bool InventoryItem::IsIgnoredByConstruction () inline private
Definition at line 2460 of file itembase.c.
    {
        return true;
    }
IsItemBase()
override bool InventoryItem::IsItemBase () inline private
Definition at line 2597 of file itembase.c.
    {
        return true;
    }
IsLightSource()
bool InventoryItem::IsLightSource () inline private
Definition at line 856 of file itembase.c.
    {
        return false;
    }
IsLiquidContainer()
bool InventoryItem::IsLiquidContainer () inline private
Definition at line 827 of file itembase.c.
    {
        return ( ConfigGetFloat("liquidContainerType") != 0 );
    }
References ConfigGetFloat().
IsLiquidPresent()
bool InventoryItem::IsLiquidPresent () inline private
Definition at line 821 of file itembase.c.
    {
        return ( GetLiquidType() != 0 && HasQuantity() );
    }
References GetLiquidType(), and HasQuantity().
IsNVG()
bool InventoryItem::IsNVG () inline private
Definition at line 837 of file itembase.c.
    {
        return false;
    }
IsOneHandedBehaviour()
override bool InventoryItem::IsOneHandedBehaviour () inline private
Definition at line 4321 of file itembase.c.
    {
        if (m_ItemBehaviour == 1)
        {
            return true;
        }
        return false;
    }
References m_ItemBehaviour.
IsOpen()
bool InventoryItem::IsOpen () inline private
Definition at line 4129 of file itembase.c.
{return true;}
IsOverheatingEffectActive()
bool InventoryItem::IsOverheatingEffectActive () inline private
Definition at line 523 of file itembase.c.
    {
        return m_IsOverheatingEffectActive;
    }
References m_IsOverheatingEffectActive.
IsPlaceSound()
bool InventoryItem::IsPlaceSound () inline private
Definition at line 4432 of file itembase.c.
    {
        return m_IsPlaceSound;
    }
References m_IsPlaceSound.
IsPlayerInside()
bool InventoryItem::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 873 of file itembase.c.
    {
        return true;
    }
IsResultOfSplit()
bool InventoryItem::IsResultOfSplit () inline private
Definition at line 2025 of file itembase.c.
    {
        return m_IsResultOfSplit;
    }
IsServerCheck()
bool InventoryItem::IsServerCheck (bool allow_client) inline private
Definition at line 3794 of file itembase.c.
    {
        if (g_Game.IsServer())
            return true;
        if(allow_client) return true;
        if( GetGame().IsClient() && GetGame().IsMultiplayer() )
        {
            Error("Attempting to change variable client side, variables are supposed to be changed on server only !!");
            return false;
        }
        else
        {
            return true;
        }
    }
References Error(), g_Game, and GetGame().
IsSoundSynchRemote()
bool InventoryItem::IsSoundSynchRemote () inline private
Definition at line 4402 of file itembase.c.
    {
        return m_IsSoundSynchRemote;
    }
References m_IsSoundSynchRemote.
IsTakeable()
override bool InventoryItem::IsTakeable () inline private
Definition at line 4361 of file itembase.c.
    {
        return m_IsTakeable;
    }
References m_IsTakeable.
IsTwoHandedBehaviour()
override bool InventoryItem::IsTwoHandedBehaviour () inline private
Definition at line 4331 of file itembase.c.
    {
        if (m_ItemBehaviour == 2)
        {
            return true;
        }
        return false;
    }
References m_ItemBehaviour.
IsVariableSet()
bool InventoryItem::IsVariableSet (int variable) inline private
'true' if this variable has ever been changed from default
Definition at line 3646 of file itembase.c.
    {
        return (variable & m_VariablesMask);
    }
References m_VariablesMask.
ItemBase()
void InventoryItem::ItemBase () inline private
Definition at line 134 of file itembase.c.
    {
        SetEventMask(EntityEvent.INIT); // Enable EOnInit event
        InitItemVariables();
        m_SingleUseActions = new TIntArray;
        m_ContinuousActions = new TIntArray;
        m_InteractActions = new TIntArray;
        if (!GetGame().IsDedicatedServer())
        {
            if (HasMuzzle())
            {
                LoadParticleConfigOnFire( GetMuzzleID() );
                if ( m_ShotsToStartOverheating == 0 )
                {
                    LoadParticleConfigOnOverheating( GetMuzzleID() );
                }
            }
            PreLoadSoundAttachmentType();
            m_ActionsInitialize = false;
        }
        m_OldLocation = null;
        if ( GetGame().IsServer() )
        {
            m_AdminLog = PluginAdminLog.Cast( GetPlugin(PluginAdminLog) );
        }
        if ( ConfigIsExisting("headSelectionsToHide") )
        {
            m_HeadHidingSelections = new TStringArray;
            ConfigGetTextArray("headSelectionsToHide",m_HeadHidingSelections);
        }
        m_HideSelectionsBySlot = false;
        if ( ConfigIsExisting("hideSelectionsByinventorySlot") )
        {
            m_HideSelectionsBySlot = ConfigGetBool("hideSelectionsByinventorySlot");
        }
        m_ConfigWeight = ConfigGetInt("weight");
        m_QuickBarBonus = Math.Max(0, ConfigGetInt("quickBarBonus"));
        m_IsResultOfSplit = false;
    }
References ConfigGetBool(), ConfigGetInt(), ConfigGetTextArray(), ConfigIsExisting(), GetGame(), GetMuzzleID(), GetPlugin(), HasMuzzle(), ItemBase::InitItemVariables(), LoadParticleConfigOnFire(), LoadParticleConfigOnOverheating(), m_ActionsInitialize, m_AdminLog, m_ConfigWeight, m_ContinuousActions, m_HeadHidingSelections, m_HideSelectionsBySlot, m_InteractActions, m_QuickBarBonus, m_ShotsToStartOverheating, m_SingleUseActions, Math::Max(), and PreLoadSoundAttachmentType().
KillAllOverheatingParticles()
void InventoryItem::KillAllOverheatingParticles () inline private
Definition at line 621 of file itembase.c.
    {
        if (m_OverheatingParticles)
        {
            for (int i = m_OverheatingParticles.Count(); i > 0; i--)
            {
                int id = i - 1;
                OverheatingParticle OP = m_OverheatingParticles.Get(id);
                if (OP)
                {
                    Particle p = OP.GetParticle();
                    if (p)
                    {
                        p.Stop();
                    }
                    delete OP;
                }
            }
            m_OverheatingParticles.Clear();
            delete m_OverheatingParticles;
        }
    }
References OverheatingParticle::GetParticle(), m_OverheatingParticles, and Particle::Stop().
KindOf()
override bool InventoryItem::KindOf (string tag) inline private
Definition at line 2603 of file itembase.c.
    {
        bool found = false;
        string item_name = this.GetType();
        ref TStringArray item_tag_array = new TStringArray;
        GetGame().ConfigGetTextArray("cfgVehicles " + item_name + " itemInfo", item_tag_array);
        int array_size = item_tag_array.Count();
        for (int i = 0; i < array_size; i++)
        {
            if ( item_tag_array.Get(i) == tag )
            {
                found = true;
                break;
            }
        }
        return found;
    }
References CGame::ConfigGetTextArray(), GetGame(), and GetType().
LoadAgents()
bool InventoryItem::LoadAgents (ParamsReadContext ctx, int version) inline private
Definition at line 4058 of file itembase.c.
    {
        if(!ctx.Read(m_AttachedAgents))
            return false;
        return true;
    }
References m_AttachedAgents, and Serializer::Read().
LoadParticleConfigOnFire()
void InventoryItem::LoadParticleConfigOnFire (int id) inline private
Definition at line 360 of file itembase.c.
    {
        if (!m_OnFireEffect)
            m_OnFireEffect = new map<int, ref array<ref WeaponParticlesOnFire>>;
        if (!m_OnBulletCasingEjectEffect)
            m_OnBulletCasingEjectEffect = new map<int, ref array<ref WeaponParticlesOnBulletCasingEject>>;
        string config_to_search = "CfgVehicles";
        string muzzle_owner_config;
        if ( !m_OnFireEffect.Contains(id) )
        {
            if (IsInherited(Weapon))
                config_to_search = "CfgWeapons";
            muzzle_owner_config = config_to_search + " " + GetType() + " ";
            string config_OnFire_class = muzzle_owner_config + "Particles " + "OnFire ";
            int config_OnFire_subclass_count = GetGame().ConfigGetChildrenCount(config_OnFire_class);
            if (config_OnFire_subclass_count > 0)
            {
                array<ref WeaponParticlesOnFire> WPOF_array = new array<ref WeaponParticlesOnFire>;
                for (int i = 0; i < config_OnFire_subclass_count; i++)
                {
                    string particle_class = "";
                    GetGame().ConfigGetChildName(config_OnFire_class, i, particle_class);
                    string config_OnFire_entry = config_OnFire_class + particle_class;
                    WeaponParticlesOnFire WPOF = new WeaponParticlesOnFire(this, config_OnFire_entry);
                    WPOF_array.Insert(WPOF);
                }
                m_OnFireEffect.Insert(id, WPOF_array);
            }
        }
        if ( !m_OnBulletCasingEjectEffect.Contains(id) )
        {
            config_to_search = "CfgWeapons"; // Bullet Eject efect is supported on weapons only.
            muzzle_owner_config = config_to_search + " " + GetType() + " ";
            string config_OnBulletCasingEject_class = muzzle_owner_config + "Particles " + "OnBulletCasingEject ";
            int config_OnBulletCasingEject_count = GetGame().ConfigGetChildrenCount(config_OnBulletCasingEject_class);
            if (config_OnBulletCasingEject_count > 0  &&  IsInherited(Weapon))
            {
                array<ref WeaponParticlesOnBulletCasingEject> WPOBE_array = new array<ref WeaponParticlesOnBulletCasingEject>;
                for (i = 0; i < config_OnBulletCasingEject_count; i++)
                {
                    string particle_class2 = "";
                    GetGame().ConfigGetChildName(config_OnBulletCasingEject_class, i, particle_class2);
                    string config_OnBulletCasingEject_entry = config_OnBulletCasingEject_class + particle_class2;
                    WeaponParticlesOnBulletCasingEject WPOBE = new WeaponParticlesOnBulletCasingEject(this, config_OnBulletCasingEject_entry);
                    WPOBE_array.Insert(WPOBE);
                }
                m_OnBulletCasingEjectEffect.Insert(id, WPOBE_array);
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), GetType(), m_OnBulletCasingEjectEffect, and m_OnFireEffect.
LoadParticleConfigOnOverheating()
void InventoryItem::LoadParticleConfigOnOverheating (int id) inline private
Definition at line 429 of file itembase.c.
    {
        if (!m_OnOverheatingEffect)
            m_OnOverheatingEffect = new map<int, ref array<ref WeaponParticlesOnOverheating>>;
        if ( !m_OnOverheatingEffect.Contains(id) )
        {
            string config_to_search = "CfgVehicles";
            if (IsInherited(Weapon))
                config_to_search = "CfgWeapons";
            string muzzle_owner_config = config_to_search + " " + GetType() + " ";
            string config_OnOverheating_class = muzzle_owner_config + "Particles " + "OnOverheating ";
            if (GetGame().ConfigIsExisting(config_OnOverheating_class))
            {
                m_ShotsToStartOverheating = GetGame().ConfigGetFloat(config_OnOverheating_class + "shotsToStartOverheating");
                if (m_ShotsToStartOverheating == 0)
                {
                    m_ShotsToStartOverheating = -1; // This prevents futher readings from config for future creations of this item
                    string error = "Error reading config " + GetType() + ">Particles>OnOverheating - Parameter shotsToStartOverheating is configured wrong or is missing! Its value must be 1 or higher!";
                    Error(error);
                    return;
                }
                m_OverheatingDecayInterval = GetGame().ConfigGetFloat(config_OnOverheating_class + "overheatingDecayInterval");
                m_MaxOverheatingValue = GetGame().ConfigGetFloat(config_OnOverheating_class + "maxOverheatingValue");
                int config_OnOverheating_subclass_count = GetGame().ConfigGetChildrenCount(config_OnOverheating_class);
                array<ref WeaponParticlesOnOverheating> WPOOH_array = new array<ref WeaponParticlesOnOverheating>;
                for (int i = 0; i < config_OnOverheating_subclass_count; i++)
                {
                    string particle_class = "";
                    GetGame().ConfigGetChildName(config_OnOverheating_class, i, particle_class);
                    string config_OnOverheating_entry = config_OnOverheating_class + particle_class;
                    int  entry_type = GetGame().ConfigGetType(config_OnOverheating_entry);
                    if ( entry_type == CT_CLASS )
                    {
                        WeaponParticlesOnOverheating WPOF = new WeaponParticlesOnOverheating(this, config_OnOverheating_entry);
                        WPOOH_array.Insert(WPOF);
                    }
                }
                m_OnOverheatingEffect.Insert(id, WPOOH_array);
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetType(), ConfigIsExisting(), Error(), GetGame(), GetType(), m_MaxOverheatingValue, m_OnOverheatingEffect, m_OverheatingDecayInterval, and m_ShotsToStartOverheating.
LoadVariables()
bool InventoryItem::LoadVariables (ParamsReadContext ctx, int version = -1) inline private
Definition at line 3006 of file itembase.c.
    {
        int varFlags;
        if( version <= 108 && version != -1 )
        {
            //read the flags
            if(!ctx.Read(CachedObjectsParams.PARAM1_INT))
            {
                return false;
            }
            else
            {
                varFlags = CachedObjectsParams.PARAM1_INT.param1;
                //--------------
                if( varFlags & ItemVariableFlags.FLOAT )
                {
                    if(!ReadVarsFromCTX(ctx, version))
                        return false;
                }
            }
        }
        else
        {
            //read the flags
            if(!ctx.Read(varFlags))
            {
                return false;
            }
            else
            {
                //--------------
                if( varFlags & ItemVariableFlags.FLOAT )
                {
                    if(!ReadVarsFromCTX(ctx, version))
                        return false;
                }
            }
        }
        return true;
    }
References ItemVariableFlags::FLOAT, CachedObjectsParams::PARAM1_INT, Serializer::Read(), and ReadVarsFromCTX().
LockToParent()
void InventoryItem::LockToParent () inline private
Locks this item in it's current attachment slot of its parent. This makes the "locked" icon visible in inventory over this item.
Definition at line 762 of file itembase.c.
    {
        EntityAI parent = GetHierarchyParent();
        if (parent)
        {
            InventoryLocation inventory_location_to_lock = new InventoryLocation;
            GetInventory().GetCurrentInventoryLocation( inventory_location_to_lock );
            parent.GetInventory().SetSlotLock( inventory_location_to_lock.GetSlot(), true );
        }
    }
References InventoryLocation::GetSlot().
MessageToOwnerAction()
void InventoryItem::MessageToOwnerAction (string text) inline private
Send message to owner player in yellow color.
Returns
void
item_stone.MessageToOwnerAction("Some Action Message");
Definition at line 2551 of file itembase.c.
    {
        PlayerBase player = PlayerBase.Cast( this.GetHierarchyRootPlayer() );
        if ( player )
        {
            player.MessageAction( text );
        }
    }
MessageToOwnerFriendly()
void InventoryItem::MessageToOwnerFriendly (string text) inline private
Send message to owner player in green color.
Returns
void
item_stone.MessageToOwnerFriendly("Some Friendly Message");
Definition at line 2569 of file itembase.c.
    {
        PlayerBase player = PlayerBase.Cast( this.GetHierarchyRootPlayer() );
        if ( player )
        {
            player.MessageFriendly( text );
        }
    }
MessageToOwnerImportant()
void InventoryItem::MessageToOwnerImportant (string text) inline private
Send message to owner player in red color.
Returns
void
item_stone.MessageToOwnerImportant("Some Important Message");
Definition at line 2587 of file itembase.c.
    {
        PlayerBase player = PlayerBase.Cast( this.GetHierarchyRootPlayer() );
        if ( player )
        {
            player.MessageImportant( text );
        }
    }
MessageToOwnerStatus()
void InventoryItem::MessageToOwnerStatus (string text) inline private
Send message to owner player in grey color.
Returns
void
item_stone.MessageToOwnerStatus("Some Status Message");
Definition at line 2533 of file itembase.c.
    {
        PlayerBase player = PlayerBase.Cast( this.GetHierarchyRootPlayer() );
        if ( player )
        {
            player.MessageStatus( text );
        }
    }
NameToID()
int InventoryItem::NameToID (string name) inline private
Definition at line 2687 of file itembase.c.
    {
        PluginVariables plugin = PluginVariables.Cast( GetPlugin(PluginVariables) );
        return plugin.GetID(name);
    }
References GetPlugin(), and name.
OnAction()
bool InventoryItem::OnAction (int action_id, Man player, ParamsReadContext ctx) inline private
Definition at line 2200 of file itembase.c.
    {
        if (action_id >= EActions.RECIPES_RANGE_START && action_id < EActions.RECIPES_RANGE_END)
        {
            PluginRecipesManager plugin_recipes_manager = PluginRecipesManager.Cast( GetPlugin(PluginRecipesManager) );
            int idWithoutOffset = action_id - EActions.RECIPES_RANGE_START;
            PlayerBase p = PlayerBase.Cast( player );
            if ( EActions.RECIPES_RANGE_START  < 1000 )
            {
                float anim_length = plugin_recipes_manager.GetRecipeLengthInSecs(idWithoutOffset);
                float specialty_weight = plugin_recipes_manager.GetRecipeSpecialty(idWithoutOffset);
                //p.SetUpCrafting( idWithoutOffset, this, player.GetHierarchyRootPlayer().GetHumanInventory().GetEntityInHands(),anim_length, specialty_weight);
            }
            else//this part is for the [DEBUG] actions
            {
                //plugin_recipes_manager.PerformRecipeClientRequest( idWithoutOffset, this, player.GetHierarchyRootPlayer().GetHumanInventory().GetEntityInHands() );
            }
        }
        if ( GetGame().IsServer() )
        {
            if (action_id >= EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START && action_id < EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_END)
            {
                int id = action_id - EActions.DEBUG_ITEM_WATCH_BUTTON_RANGE_START;
                OnDebugButtonPressServer(id + 1);
            }
            else if (action_id >= EActions.DEBUG_AGENTS_RANGE_INJECT_START && action_id < EActions.DEBUG_AGENTS_RANGE_INJECT_END)
            {
                int agent_id = action_id - EActions.DEBUG_AGENTS_RANGE_INJECT_START;
                InsertAgent(agent_id,100);
            }
            else if (action_id >= EActions.DEBUG_AGENTS_RANGE_REMOVE_START && action_id < EActions.DEBUG_AGENTS_RANGE_REMOVE_END)
            {
                int agent_id2 = action_id - EActions.DEBUG_AGENTS_RANGE_REMOVE_START;
                RemoveAgent(agent_id2);
            }
            else if ( action_id == EActions.ADD_QUANTITY )
            {
                if(IsMagazine())
                {
                    Magazine mag = Magazine.Cast(this);
                    mag.ServerSetAmmoCount( mag.GetAmmoCount() + mag.GetAmmoMax() * 0.2 );
                }
                else
                {
                    AddQuantity(GetQuantityMax() * 0.2);
                }
                if ( m_EM )
                {
                    m_EM.AddEnergy(m_EM.GetEnergyMax() * 0.2);
                }
                //PrintVariables();
            }
            else if ( action_id == EActions.REMOVE_QUANTITY ) //Quantity -20%
            {
                if(IsMagazine())
                {
                    Magazine mag2 = Magazine.Cast(this);
                    mag2.ServerSetAmmoCount( mag2.GetAmmoCount() - mag2.GetAmmoMax() * 0.2 );
                }
                else
                {
                    AddQuantity(- GetQuantityMax() * 0.2);
                }
                if ( m_EM )
                {
                    m_EM.AddEnergy(- m_EM.GetEnergyMax() * 0.2);
                }
                //PrintVariables();
            }
            else if ( action_id == EActions.SET_QUANTITY_0 ) //SetMaxQuantity
            {
                SetQuantity(0);
                if ( m_EM )
                {
                    m_EM.SetEnergy(0);
                }
            }
            else if ( action_id == EActions.SET_MAX_QUANTITY ) //SetMaxQuantity
            {
                SetQuantityMax();
                if ( m_EM )
                {
                    m_EM.SetEnergy(m_EM.GetEnergyMax());
                }
            }
            else if ( action_id == EActions.GET_TOTAL_WEIGHT ) //Prints total weight of item + its contents
            {
                Print(GetWeight());
            }
            else if ( action_id == EActions.ADD_HEALTH )
            {
                AddHealth("","",GetMaxHealth("","Health")/5);
            }
            else if ( action_id == EActions.REMOVE_HEALTH )
            {
                AddHealth("","",-GetMaxHealth("","Health")/5);
            }
            else if ( action_id == EActions.DESTROY_HEALTH )
            {
                SetHealth01("","",0);
            }
            else if ( action_id == EActions.SPIN ) //SetMaxQuantity
            {
                Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(GetAttachmentByType(Magnum_Cylinder));
                Magnum_Ejector ejector = Magnum_Ejector.Cast(GetAttachmentByType(Magnum_Ejector));
        //Magnum_Base magnum = Magnum_Base.Cast(m_weapon);
        //Magazine mag = m_weapon.GetMagazine(0);
                if (cylinder)
                {
                    float a  = cylinder.GetAnimationPhase("Rotate_Cylinder");
                    if (a + 0.167 > 1.0)
                    {
                        Print("-----RESET-----");
                        a -= 1.0;
                        cylinder.ResetAnimationPhase("Rotate_Cylinder", a );
                        ejector.ResetAnimationPhase("Rotate_Ejector", a );
                    }
                    a += 0.167;
                    Print(a);
                    cylinder.SetAnimationPhase("Rotate_Cylinder", a );
                    ejector.ResetAnimationPhase("Rotate_Ejector", a );
                }
                /*Weapon_Base wpn = Weapon_Base.Cast(this);
                if(wpn)
                {
                    Magazine mag = wpn.GetMagazine(0);
                    if(mag)
                    {
                        float a  = mag.GetAnimationPhase("rotate");
                        a += 0.3;
                        if(a > 1.0)
                            a -= 1.0;
                        mag.SetAnimationPhase("rotate", a );
                    }
                }*/
                /*if(a > 1.0)
                    a -= 1.0;
                SetAnimationPhase("cylinder_rotate", a + 0.2);*/
            }
            else if ( action_id == EActions.WATCH_ITEM )
            {
                PluginItemDiagnostic mid = PluginItemDiagnostic.Cast( GetPlugin(PluginItemDiagnostic) );
                mid.RegisterDebugItem( ItemBase.Cast( this ), PlayerBase.Cast( player ));
                #ifdef DEVELOPER
                SetDebugDeveloper_item(this);
                #endif
            }
            else if ( action_id == EActions.ADD_TEMPERATURE )
            {
                AddTemperature(20);
                //PrintVariables();
            }
            else if ( action_id == EActions.REMOVE_TEMPERATURE )
            {
                AddTemperature(-20);
                //PrintVariables();
            }
            else if ( action_id == EActions.ADD_WETNESS )
            {
                AddWet(GetWetMax()/5);
                //PrintVariables();
            }
            else if ( action_id == EActions.REMOVE_WETNESS )
            {
                AddWet(-GetWetMax()/5);
                //PrintVariables();
            }
            else if ( action_id == EActions.LIQUIDTYPE_UP )
            {
                int curr_type = GetLiquidType();
                SetLiquidType(curr_type * 2);
                //AddWet(1);
                //PrintVariables();
            }
            else if ( action_id == EActions.LIQUIDTYPE_DOWN )
            {
                int curr_type2 = GetLiquidType();
                SetLiquidType(curr_type2 / 2);
            }
            else if ( action_id == EActions.PRINT_BULLETS )
            {
                if ( IsMagazine() )
                {
                    Magazine this_mag;
                    Class.CastTo(this_mag, this);
                    for (int i = 0; i < this_mag.GetAmmoCount(); i++)
                    {
                        float damage;
                        string class_name;
                        this_mag.GetCartridgeAtIndex(i, damage, class_name);
                        PrintString("Bullet: " + class_name +", " + "Damage: "+ damage.ToString() );
                    }
                }
            }
            else if ( action_id == EActions.MAKE_SPECIAL )
            {
                OnDebugSpawn();
            }
            else if (action_id == EActions.DELETE)
            {
                Delete();
            }
        }
        return false;
    }
References AddHealth(), AddQuantity(), AddTemperature(), AddWet(), Class::CastTo(), class_name, Delete(), GetGame(), GetLiquidType(), GetMaxHealth(), GetPlugin(), GetQuantityMax(), GetWetMax(), InsertAgent(), IsMagazine(), OnDebugButtonPressServer(), ItemBase::OnDebugSpawn(), PluginItemDiagnostic(), Print(), PrintString(), RemoveAgent(), SetHealth01(), SetLiquidType(), SetQuantity(), SetQuantityMax(), and float::ToString().
OnActivatedByItem()
void InventoryItem::OnActivatedByItem (notnull ItemBase item) private
Called when this item is activated by other.
OnActivatedByTripWire()
void InventoryItem::OnActivatedByTripWire () private
DEPRECATED use OnActivatedByItem below Called when this item is activated from a trip wire that was stepped on.
OnApply()
void InventoryItem::OnApply (PlayerBase player) private
OnAttachmentQuantityChanged()
void InventoryItem::OnAttachmentQuantityChanged (ItemBase item) inline private
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 1846 of file itembase.c.
    {
        // insert code here
    }
OnAttachmentQuantityChangedEx()
void InventoryItem::OnAttachmentQuantityChangedEx (ItemBase item, float delta) inline private
Called on server side when some attachment's quantity is changed. Call super.OnAttachmentQuantityChanged(item); first when overriding this event.
Definition at line 1852 of file itembase.c.
    {
        OnAttachmentQuantityChanged(item);
    }
References OnAttachmentQuantityChanged().
OnCEUpdate()
override void InventoryItem::OnCEUpdate () inline private
Definition at line 4668 of file itembase.c.
    {
        super.OnCEUpdate();
        bool hasParent = false, hasRootAsPlayer = false;
        ItemBase refParentIB;
        bool wwtu = g_Game.IsWorldWetTempUpdateEnabled();
        bool foodDecay = g_Game.IsFoodDecayEnabled();
        if ( wwtu || foodDecay )
        {
            bool processWetness = wwtu && CanHaveWetness();
            bool processTemperature = wwtu && CanHaveTemperature();
            bool processDecay  = foodDecay && CanDecay() && CanProcessDecay();
            if ( processWetness || processTemperature || processDecay)
            {
                HierarchyCheck( hasParent, hasRootAsPlayer, refParentIB );
                if ( processWetness )
                    ProcessItemWetness( m_ElapsedSinceLastUpdate, hasParent, hasRootAsPlayer, refParentIB );
                if ( processTemperature )
                    ProcessItemTemperature( m_ElapsedSinceLastUpdate, hasParent, hasRootAsPlayer, refParentIB );
                if ( processDecay )
                    ProcessDecay( m_ElapsedSinceLastUpdate, hasRootAsPlayer );
            }
        }
    }
References ItemBase::CanDecay(), ItemBase::CanHaveTemperature(), CanHaveWetness(), ItemBase::CanProcessDecay(), g_Game, HierarchyCheck(), ItemBase::ProcessDecay(), ProcessItemTemperature(), and ProcessItemWetness().
OnCombine()
void InventoryItem::OnCombine (ItemBase other_item) inline private
Definition at line 2086 of file itembase.c.
    {
    }
OnCreatePhysics()
override void InventoryItem::OnCreatePhysics () inline private
Definition at line 1135 of file itembase.c.
    {
        if ( m_ItemBeingDroppedPhys )
        {
            //GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(StopItemDynamicPhysics,3000);
            //--------------------------------
            /*
            if (!m_PhysDropTimer)
            {
                m_PhysDropTimer = new Timer;
            }
            else
            {
                m_PhysDropTimer.Stop()
            }
            m_PhysDropTimer.Run(GameConstants.ITEM_DROP_TIMER,this,"StopItemDynamicPhysics");
            */
            //Print("++++dropping item phys");
        }
        RefreshPhysics();
    }
References m_ItemBeingDroppedPhys, and ItemBase::RefreshPhysics().
OnEndPlacement()
void InventoryItem::OnEndPlacement () inline private
Definition at line 897 of file itembase.c.
{}
OnEnergyAdded()
override void InventoryItem::OnEnergyAdded () inline private
Definition at line 3672 of file itembase.c.
    {
        super.OnEnergyAdded();
        ConvertEnergyToQuantity();
    }
References ConvertEnergyToQuantity().
OnEnergyConsumed()
override void InventoryItem::OnEnergyConsumed () inline private
Definition at line 3665 of file itembase.c.
    {
        super.OnEnergyConsumed();
        ConvertEnergyToQuantity();
    }
References ConvertEnergyToQuantity().
OnInventoryEnter()
void InventoryItem::OnInventoryEnter (Man player) inline private
Event called on item when it is placed in the player(Man) inventory, passes the owner as a parameter.
Definition at line 3910 of file itembase.c.
    {
        PlayerBase nplayer;
        if ( PlayerBase.CastTo(nplayer, player) )
        {
            //nplayer.OnItemInventoryEnter(this);
            nplayer.SetEnableQuickBarEntityShortcut(this,true);
        }
    }
OnInventoryExit()
void InventoryItem::OnInventoryExit (Man player) inline private
Event called on item when it is removed from the player(Man) inventory, passes the old owner as a parameter.
Definition at line 3922 of file itembase.c.
    {
        PlayerBase nplayer;
        if ( PlayerBase.CastTo(nplayer,player) )
        {
            //nplayer.OnItemInventoryExit(this);
            nplayer.SetEnableQuickBarEntityShortcut(this,false);
        }
        //if(!GetGame().IsDedicatedServer())
        player.GetHumanInventory().ClearUserReservedLocationForContainer(this);
        if ( HasEnergyManager() )
        {
            GetCompEM().UpdatePlugState(); // Unplug the el. device if it's necesarry.
        }
    }
OnItemAttachmentSlotChanged()
override void InventoryItem::OnItemAttachmentSlotChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 1162 of file itembase.c.
    {
    }
OnItemInHandsPlayerSwimStart()
void InventoryItem::OnItemInHandsPlayerSwimStart (PlayerBase player) private
OnItemLocationChanged()
override void InventoryItem::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 1167 of file itembase.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
        Man owner_player_old = NULL;
        Man owner_player_new = NULL;
        if (old_owner)
        {
            if (old_owner.IsMan())
            {
                owner_player_old = Man.Cast( old_owner );
            }
            else
            {
                owner_player_old = Man.Cast( old_owner.GetHierarchyRootPlayer() );
            }
        }
        if (new_owner)
        {
            if ( new_owner.IsMan() )
            {
                owner_player_new = Man.Cast( new_owner );
            }
            else
            {
                owner_player_new = Man.Cast( new_owner.GetHierarchyRootPlayer() );
            }
        }
        if ( owner_player_old != owner_player_new )
        {
            if ( owner_player_old )
            {
                array<EntityAI> subItemsExit = new array<EntityAI>;
                GetInventory().EnumerateInventory(InventoryTraversalType.PREORDER,subItemsExit);
                for (int i = 0; i < subItemsExit.Count(); i++)
                {
                    ItemBase item_exit = ItemBase.Cast(subItemsExit.Get(i));
                    item_exit.OnInventoryExit(owner_player_old);
                }
            }
            if ( owner_player_new )
            {
                array<EntityAI> subItemsEnter = new array<EntityAI>;
                GetInventory().EnumerateInventory(InventoryTraversalType.PREORDER,subItemsEnter);
                for (int j = 0; j < subItemsEnter.Count(); j++)
                {
                    ItemBase item_enter = ItemBase.Cast(subItemsEnter.Get(j));
                    item_enter.OnInventoryEnter(owner_player_new);
                }
            }
        }
    }
References EntityAI::IsMan(), ItemBase::OnInventoryEnter(), and ItemBase::OnInventoryExit().
OnOverheatingDecay()
void InventoryItem::OnOverheatingDecay () inline private
Definition at line 528 of file itembase.c.
    {
        if (m_MaxOverheatingValue > 0)
            m_OverheatingShots -= 1 + m_OverheatingShots / m_MaxOverheatingValue; // The hotter a barrel is, the faster it needs to cool down.
        else
            m_OverheatingShots--;
        if (m_OverheatingShots <= 0)
        {
            m_CheckOverheating.Stop();
            m_OverheatingShots = 0;
        }
        else
        {
            if (!m_CheckOverheating)
                m_CheckOverheating = new Timer( CALL_CATEGORY_GAMEPLAY );
            m_CheckOverheating.Stop();
            m_CheckOverheating.Run(m_OverheatingDecayInterval, this, "OnOverheatingDecay");
        }
        CheckOverheating(this, "", this);
    }
References CALL_CATEGORY_GAMEPLAY, CheckOverheating(), m_CheckOverheating, m_MaxOverheatingValue, m_OverheatingDecayInterval, and m_OverheatingShots.
OnPlacementComplete()
override void InventoryItem::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 3950 of file itembase.c.
    {
        if ( m_AdminLog )
        {
            m_AdminLog.OnPlacementComplete( player, this );
        }
        super.OnPlacementComplete( player, position, orientation );
    }
References m_AdminLog.
OnPlacementStarted()
override void InventoryItem::OnPlacementStarted (Man player) inline private
Definition at line 3943 of file itembase.c.
    {
        super.OnPlacementStarted( player );
        SetTakeable(false);
    }
References SetTakeable().
OnQuantityChanged()
void InventoryItem::OnQuantityChanged (float delta) inline private
Called on server side when this item's quantity is changed. Call super.OnQuantityChanged(); first when overriding this event.
Definition at line 1822 of file itembase.c.
    {
        ItemBase parent = ItemBase.Cast( GetHierarchyParent() );
        if (parent)
        {
            parent.OnAttachmentQuantityChangedEx(this, delta);
        }
        if (m_CanThisBeSplit && delta > 0 && GetUnitWeight(false) != -1)
        {
            UpdateWeight(WeightUpdateType.RECURSIVE_ADD, GetUnitWeight(false) * delta);
        }
        else if (m_CanThisBeSplit && delta < 0 && GetUnitWeight(false) != -1)
        {
            UpdateWeight(WeightUpdateType.RECURSIVE_REMOVE, -GetUnitWeight(false) * delta);
        }
        else
        {
            UpdateWeight();
        }
    }
References GetUnitWeight(), m_CanThisBeSplit, and UpdateWeight().
OnRightClick()
override void InventoryItem::OnRightClick () inline private
Definition at line 1895 of file itembase.c.
    {
        super.OnRightClick();
        if ( CanBeSplit() && !GetDayZGame().IsLeftCtrlDown() && !GetGame().GetPlayer().GetInventory().HasInventoryReservation(this,null) )
        {
            if ( GetGame().IsClient() )
            {
                if ( ScriptInputUserData.CanStoreInputUserData() )
                {
                    vector m4[4];
                    PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
                    EntityAI root = GetHierarchyRoot();
                    InventoryLocation dst = new InventoryLocation;
                    if ( !player.GetInventory().FindFirstFreeLocationForNewEntity(GetType(), FindInventoryLocationType.CARGO, dst) )
                    {
                        if (root)
{
                            root.GetTransform(m4);
                            dst.SetGround(this, m4);
                        }
                        else
                            GetInventory().GetCurrentInventoryLocation(dst);
                    }
                    else
                    {
                        dst.SetCargo( dst.GetParent(), this, dst.GetIdx(), dst.GetRow(), dst.GetCol(), dst.GetFlip());
                        if ( GetGame().GetPlayer().GetInventory().HasInventoryReservation( null, dst) )
{
                            if (root)
{
                                root.GetTransform(m4);
                                dst.SetGround(this, m4);
                            }
                            else
                                GetInventory().GetCurrentInventoryLocation(dst);
                        }
                        else
{
                            GetGame().GetPlayer().GetInventory().AddInventoryReservationEx( null, dst, GameInventory.c_InventoryReservationTimeoutShortMS);
                        }
                    }
                    ScriptInputUserData ctx = new ScriptInputUserData;
                    ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                    ctx.Write(4);
                    ItemBase thiz = this; // @NOTE: workaround for correct serialization
                    ctx.Write(thiz);
                    dst.WriteToContext(ctx);
                    ctx.Write(true); // dummy
                    ctx.Send();
                }
            }
            else if ( !GetGame().IsMultiplayer() )
            {
                SplitItem( PlayerBase.Cast( GetGame().GetPlayer() ) );
            }
        }
    }
References CanBeSplit(), ScriptInputUserData::CanStoreInputUserData(), InventoryLocation::GetCol(), GetDayZGame(), InventoryLocation::GetFlip(), GetGame(), InventoryLocation::GetIdx(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetRow(), GetType(), HasInventoryReservation(), INPUT_UDT_ITEM_MANIPULATION, IsLeftCtrlDown(), ScriptInputUserData::Send(), InventoryLocation::SetCargo(), InventoryLocation::SetGround(), SplitItem(), Serializer::Write(), and InventoryLocation::WriteToContext().
Referenced by VicinitySlotsContainer::MouseClick().
OnRPC()
override void InventoryItem::OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 2623 of file itembase.c.
    {
        //Debug.Log("OnRPC called");
        super.OnRPC( sender, rpc_type,ctx );
        //Play soundset for attachment locking ( ActionLockAttachment.c )
        switch ( rpc_type )
        {
            #ifndef SERVER
            case ERPCs.RPC_SOUND_LOCK_ATTACH:
                Param2<bool, string> p = new Param2<bool, string>(false, "");
                if ( !ctx.Read( p ) )
                    return;
                bool play = p.param1;
                string soundSet = p.param2;
                if ( play )
                {
                    if ( m_LockingSound )
                    {
                        if ( !m_LockingSound.IsSoundPlaying() )
{
                            m_LockingSound = SEffectManager.PlaySound( soundSet, GetPosition(), 0, 0, true );
                        }
                    }
                    else
                    {
                        m_LockingSound = SEffectManager.PlaySound( soundSet, GetPosition(), 0, 0, true );
                    }
                }
                else
                {
                    SEffectManager.DestroyEffect( m_LockingSound );
                }
            break;
            #endif
        }
        if ( GetWrittenNoteData() )
        {
            GetWrittenNoteData().OnRPC( sender, rpc_type,ctx );
        }
    }
References SEffectManager::DestroyEffect(), GetPosition, ItemBase::GetWrittenNoteData(), EffectSound::IsSoundPlaying(), m_LockingSound, WrittenNoteData::OnRPC(), SEffectManager::PlaySound(), and Serializer::Read().
OnStoreLoad()
override bool InventoryItem::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 3049 of file itembase.c.
    {
        m_IsStoreLoad = true;
        if (GetDamageSystemVersionChange() != -1 && version < GetDamageSystemVersionChange())
        {
            m_FixDamageSystemInit = true;
        }
        if ( !super.OnStoreLoad(ctx, version) )
        {
            m_IsStoreLoad = false;
            return false;
        }
        if (version >= 114)
        {
            bool hasQuickBarIndexSaved;
            if (!ctx.Read(hasQuickBarIndexSaved))
            {
                m_IsStoreLoad = false;
                return false;
            }
            if (hasQuickBarIndexSaved)
            {
                int itmQBIndex;
                //Load quickbar item bind
                if (!ctx.Read(itmQBIndex))
                {
                    m_IsStoreLoad = false;
                    return false;
                }
                PlayerBase parentPlayer = PlayerBase.Cast(GetHierarchyRootPlayer());
                if ( itmQBIndex != -1 && parentPlayer )
                    parentPlayer.SetLoadedQuickBarItemBind(this, itmQBIndex);
            }
        }
        else
        {
            // Backup of how it used to be
            PlayerBase player;
            int itemQBIndex;
            if (version == int.MAX)
            {
                if (!ctx.Read(itemQBIndex))
                {
                    m_IsStoreLoad = false;
                    return false;
                }
            }
            else if ( Class.CastTo(player, GetHierarchyRootPlayer()) )
            {
                //Load quickbar item bind
                if (!ctx.Read(itemQBIndex))
                {
                    m_IsStoreLoad = false;
                    return false;
                }
                if ( itemQBIndex != -1 && player )
                    player.SetLoadedQuickBarItemBind(this,itemQBIndex);
            }
        }
        // variable management system
        if ( !LoadVariables(ctx, version) )
        {
            m_IsStoreLoad = false;
            return false;
        }
        //agent trasmission system
        if ( !LoadAgents(ctx, version) )
        {
            m_IsStoreLoad = false;
            return false;
        }
        m_IsStoreLoad = false;
        return true;
    }
References Class::CastTo(), ItemBase::GetDamageSystemVersionChange(), LoadAgents(), LoadVariables(), m_FixDamageSystemInit, m_IsStoreLoad, MAX, and Serializer::Read().
OnStoreSave()
override void InventoryItem::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 3136 of file itembase.c.
    {
        super.OnStoreSave(ctx);
        PlayerBase player;
        if (PlayerBase.CastTo(player,GetHierarchyRootPlayer()))
        {
            ctx.Write(true); // Keep track of if we should actually read this in or not
            //Save quickbar item bind
            int itemQBIndex = -1;
            itemQBIndex = player.FindQuickBarEntityIndex(this);
            ctx.Write(itemQBIndex);
        }
        else
        {
            ctx.Write(false); // Keep track of if we should actually read this in or not
        }
        SaveVariables(ctx);// variable management system
        SaveAgents(ctx);//agent trasmission system
    }
References SaveAgents(), SaveVariables(), and Serializer::Write().
OnSyncVariables()
void InventoryItem::OnSyncVariables (ParamsReadContext ctx) inline private
Definition at line 2699 of file itembase.c.
    {
        //Debug.Log("OnSyncVariables called for item:  "+ ToString(this.GetType()),"varSync");
        //read the flags
        //ref Param1<int> pflags = new Param1<int>(0);
        int varFlags;
        if( !ctx.Read(varFlags) )
            return;
        //ctx.Read(CachedObjectsParams.PARAM1_INT);
        //int varFlags = CachedObjectsParams.PARAM1_INT.param1;
        //--------------
        if( varFlags & ItemVariableFlags.FLOAT )
        {
            ReadVarsFromCTX(ctx);
        }
        /*
        if( varFlags & ItemVariableFlags.STRING )
        {
            OnSyncStrings(ctx);
        }
        */
    }
References ItemVariableFlags::FLOAT, Serializer::Read(), and ReadVarsFromCTX().
OnVariablesSynchronized()
override void InventoryItem::OnVariablesSynchronized () inline private
Definition at line 3191 of file itembase.c.
    {
        /*
        if(QUANTITY_DEBUG_REMOVE_ME)
        {
            PrintString("==================== CLIENT ==========================");
            int low, high;
            GetNetworkID(low, high);
            PrintString("entity:"+low.ToString()+"| high:"+high.ToString());
            PrintString("getting quantity, current:"+m_VarQuantity.ToString());
        }
        */
        if (m_Initialized)
        {
            UpdateWeight();
            if (GetHierarchyParent())
                GetHierarchyParent().UpdateWeight();
            #ifdef PLATFORM_CONSOLE
            //bruteforce it is
            if (m_CanThisBeSplit)
            {
                UIScriptedMenu menu = GetGame().GetUIManager().FindMenu(MENU_INVENTORY);
                if( menu )
                {
                    menu.Refresh();
                }
            }
            #endif
        }
        if (!dBodyIsDynamic(this) && m_WantPlayImpactSound)
        {
            PlayImpactSound(m_ConfigWeight, m_ImpactSpeed, m_ImpactSoundSurfaceHash);
            m_WantPlayImpactSound = false;
        }
        super.OnVariablesSynchronized();
    }
References dBodyIsDynamic(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), m_CanThisBeSplit, m_ConfigWeight, m_ImpactSoundSurfaceHash, m_ImpactSpeed, m_Initialized, m_WantPlayImpactSound, MENU_INVENTORY, UIScriptedMenu::Refresh(), and UpdateWeight().
OnWasAttached()
override void InventoryItem::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 1286 of file itembase.c.
    {
        super.OnWasAttached(parent, slot_id);
        if ( HasQuantity() )
            UpdateNetSyncVariableFloat( "m_VarQuantity", GetQuantityMin(), m_VarQuantityMax );
        PlayAttachSound(InventorySlots.GetSlotName(slot_id));
    }
References GetQuantityMin(), InventorySlots::GetSlotName(), HasQuantity(), m_VarQuantityMax, and PlayAttachSound().
OnWasDetached()
override void InventoryItem::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 1296 of file itembase.c.
    {
        super.OnWasDetached(parent, slot_id);
        if ( HasQuantity() )
            UpdateNetSyncVariableFloat( "m_VarQuantity", GetQuantityMin(), m_VarQuantityMax );
        //PlayDetachSound(InventorySlots.GetSlotName(slot_id));
        PlayerBase player = PlayerBase.Cast(parent);
        if (player)
        {
            if ( !GetGame().IsServer() )
                return;
        }
    }
References GetGame(), GetQuantityMin(), HasQuantity(), and m_VarQuantityMax.
Open()
void InventoryItem::Open () inline private
Implementations only.
Definition at line 4127 of file itembase.c.
{}
PerformDamageSystemReinit()
void InventoryItem::PerformDamageSystemReinit () inline private
Definition at line 4546 of file itembase.c.
    {
        array<string> zone_names = new array<string>;
        GetDamageZones(zone_names);
        for (int i = 0; i < zone_names.Count(); i++)
        {
            SetHealthMax(zone_names.Get(i),"Health");
        }
        SetHealthMax("","Health");
    }
References GetDamageZones(), and SetHealthMax().
PlayAttachSound()
void InventoryItem::PlayAttachSound (string slot_type) inline private
Plays sound on item attach. Be advised, the config structure may slightly change in 1.11 update to allow for more complex use.
Definition at line 4480 of file itembase.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if (ConfigIsExisting("attachSoundSet"))
            {
                string cfg_path = "";
                string soundset = "";
                string type_name = GetType();
                TStringArray cfg_soundset_array = new TStringArray;
                TStringArray cfg_slot_array = new TStringArray;
                ConfigGetTextArray("attachSoundSet",cfg_soundset_array);
                ConfigGetTextArray("attachSoundSlot",cfg_slot_array);
                if (cfg_soundset_array.Count() > 0 && cfg_soundset_array.Count() == cfg_slot_array.Count())
                {
                    for (int i = 0; i < cfg_soundset_array.Count(); i++)
                    {
                        if (cfg_slot_array[i] == slot_type)
{
                            soundset = cfg_soundset_array[i];
                            break;
                        }
                    }
                }
                if (soundset != "")
                {
                    EffectSound sound = SEffectManager.PlaySound(soundset, GetPosition());
                    sound.SetAutodestroy( true );
                }
            }
        }
    }
References ConfigGetTextArray(), ConfigIsExisting(), GetGame(), GetPosition, GetType(), SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayBulletCasingEjectParticles()
static void InventoryItem::PlayBulletCasingEjectParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
Definition at line 4230 of file itembase.c.
    {
        int id = muzzle_owner.GetMuzzleID();
        array<ref WeaponParticlesOnBulletCasingEject> WPOBE_array = m_OnBulletCasingEjectEffect.Get(id);
        if (WPOBE_array)
        {
            for (int i = 0; i < WPOBE_array.Count(); i++)
            {
                WeaponParticlesOnBulletCasingEject WPOBE = WPOBE_array.Get(i);
                if (WPOBE)
                {
                    WPOBE.OnActivate(weapon, 0, ammoType, muzzle_owner, suppressor, config_to_search);
                }
            }
        }
    }
References m_OnBulletCasingEjectEffect.
PlayDeployFinishSound()
void InventoryItem::PlayDeployFinishSound () inline private
Definition at line 4456 of file itembase.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            EffectSound sound = SEffectManager.PlaySound( GetDeployFinishSoundset(), GetPosition() );
            sound.SetAutodestroy( true );
        }
    }
References ItemBase::GetDeployFinishSoundset(), GetGame(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayDeploySound()
void InventoryItem::PlayDeploySound () inline private
Definition at line 4447 of file itembase.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            EffectSound sound = SEffectManager.PlaySound( GetDeploySoundset(), GetPosition() );
            sound.SetAutodestroy( true );
        }
    }
References ItemBase::GetDeploySoundset(), GetGame(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PlayDetachSound()
void InventoryItem::PlayDetachSound (string slot_type) inline private
Definition at line 4516 of file itembase.c.
    {
        //TODO - evaluate if needed and devise universal config structure if so
    }
PlayFireParticles()
static void InventoryItem::PlayFireParticles (ItemBase weapon, int muzzle_index, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
Definition at line 4210 of file itembase.c.
    {
        int id = muzzle_owner.GetMuzzleID();
        array<ref WeaponParticlesOnFire> WPOF_array = m_OnFireEffect.Get(id);
        if (WPOF_array)
        {
            for (int i = 0; i < WPOF_array.Count(); i++)
            {
                WeaponParticlesOnFire WPOF = WPOF_array.Get(i);
                if (WPOF)
                {
                    WPOF.OnActivate(weapon, muzzle_index, ammoType, muzzle_owner, suppressor, config_to_search);
                }
            }
        }
    }
References m_OnFireEffect.
PlayOverheatingParticles()
static void InventoryItem::PlayOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
Definition at line 4250 of file itembase.c.
    {
        int id = muzzle_owner.GetMuzzleID();
        array<ref WeaponParticlesOnOverheating> WPOOH_array = weapon.m_OnOverheatingEffect.Get(id);
        if (WPOOH_array)
        {
            for (int i = 0; i < WPOOH_array.Count(); i++)
            {
                WeaponParticlesOnOverheating WPOOH = WPOOH_array.Get(i);
                if (WPOOH)
                {
                    WPOOH.OnActivate(weapon, 0, ammoType, muzzle_owner, suppressor, config_to_search);
                }
            }
        }
    }
PlayPlaceSound()
void InventoryItem::PlayPlaceSound () inline private
Definition at line 4465 of file itembase.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            EffectSound sound = SEffectManager.PlaySound( GetPlaceSoundset(), GetPosition() );
            sound.SetAutodestroy( true );
        }
    }
References GetGame(), ItemBase::GetPlaceSoundset(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
PreLoadSoundAttachmentType()
protected void InventoryItem::PreLoadSoundAttachmentType () inline private
Attachment Sound Type getting from config file.
Definition at line 4367 of file itembase.c.
    {
        string att_type = "None";
        if( ConfigIsExisting("soundAttType") )
        {
            att_type = ConfigGetString("soundAttType");
        }
        m_SoundAttType = att_type;
    }
References ConfigGetString(), ConfigIsExisting(), and m_SoundAttType.
ProcessDecay()
protected void InventoryItem::ProcessDecay (float delta, bool hasRootAsPlayer) inline private
Definition at line 4638 of file itembase.c.
    {
        // this is stub, implemented on Edible_Base
    }
ProcessItemTemperature()
void InventoryItem::ProcessItemTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
Definition at line 4595 of file itembase.c.
    {
        if ( !hasRootAsPlayer )
        {
            if ( !hasParent )
            {
                // cooling on ground
                if ( ( GetTemperature() > GetTemperatureMin() ) && !IsFireplace() )
                    AddTemperature( delta * GameConstants.TEMPERATURE_RATE_COOLING_GROUND );
            }
            else if ( refParentIB )
            {
                // cooling of an item inside other
                if ( ( GetTemperature() > GetTemperatureMin() ) && !IsFireplace() && ( GetTemperature() > refParentIB.GetTemperature() ) )
                    AddTemperature( delta * GameConstants.TEMPERATURE_RATE_COOLING_INSIDE );
            }
        }
    }
References AddTemperature(), GetTemperature(), GetTemperatureMin(), IsFireplace(), GameConstants::TEMPERATURE_RATE_COOLING_GROUND, and GameConstants::TEMPERATURE_RATE_COOLING_INSIDE.
ProcessItemWetness()
void InventoryItem::ProcessItemWetness (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
Definition at line 4570 of file itembase.c.
    {
        if ( !hasRootAsPlayer )
        {
            if ( !hasParent )
            {
                // drying on ground
                if ( m_VarWet > m_VarWetMin )
                    AddWet( delta * GameConstants.WETNESS_RATE_DRYING_GROUND );
            }
            else if ( refParentIB )
            {
                // parent is wet
                if ( ( refParentIB.GetWet() >= GameConstants.STATE_SOAKING_WET ) && ( m_VarWet < m_VarWetMax ) )
                    AddWet( delta * GameConstants.WETNESS_RATE_WETTING_INSIDE );
                // parent has liquid inside
                else if ( ( refParentIB.GetLiquidType() != 0 ) && ( refParentIB.GetQuantity() > 0 ) && ( m_VarWet < m_VarWetMax ) )
                    AddWet( delta * GameConstants.WETNESS_RATE_WETTING_LIQUID );
                // drying
                else if ( m_VarWet > m_VarWetMin )
                    AddWet( delta * GameConstants.WETNESS_RATE_DRYING_INSIDE );
            }
        }
    }
References AddWet(), m_VarWet, m_VarWetMax, m_VarWetMin, GameConstants::STATE_SOAKING_WET, GameConstants::WETNESS_RATE_DRYING_GROUND, GameConstants::WETNESS_RATE_DRYING_INSIDE, GameConstants::WETNESS_RATE_WETTING_INSIDE, and GameConstants::WETNESS_RATE_WETTING_LIQUID.
ProcessItemWetnessAndTemperature()
void InventoryItem::ProcessItemWetnessAndTemperature (float delta, bool hasParent, bool hasRootAsPlayer, ItemBase refParentIB) inline private
Definition at line 4615 of file itembase.c.
    {
        ProcessItemWetness(delta, hasParent, hasRootAsPlayer, refParentIB);
        ProcessItemTemperature(delta, hasParent, hasRootAsPlayer, refParentIB);
    }
References ProcessItemTemperature(), and ProcessItemWetness().
ReadVarsFromCTX()
bool InventoryItem::ReadVarsFromCTX (ParamsReadContext ctx, int version = -1) inline private
Definition at line 2869 of file itembase.c.
    {
        int numOfItems;
        int intValue;
        float value;
        if( version <= 108 && version!= -1 )
        {
            if(!ctx.Read(CachedObjectsParams.PARAM1_INT))
                return false;
            numOfItems = CachedObjectsParams.PARAM1_INT.param1;
            CachedObjectsArrays.ARRAY_FLOAT.Clear();
            for(int i = 0; i < numOfItems; i++)
            {
                if(!ctx.Read(CachedObjectsParams.PARAM1_FLOAT))
                    return false;
                value = CachedObjectsParams.PARAM1_FLOAT.param1;
                CachedObjectsArrays.ARRAY_FLOAT.Insert(value);
            }
            DeSerializeNumericalVars(CachedObjectsArrays.ARRAY_FLOAT);
            return true;
        }
        else if( version <= 116 && version!= -1)
        {
            if(!ctx.Read(numOfItems))
                return false;
            CachedObjectsArrays.ARRAY_FLOAT.Clear();
            for(int j = 0; j < numOfItems; j++)
            {
                if(!ctx.Read(value))
                    return false;
                CachedObjectsArrays.ARRAY_FLOAT.Insert(value);
            }
            DeSerializeNumericalVars(CachedObjectsArrays.ARRAY_FLOAT);
            return true;
        }
        else
        {
            int mask;
            if ( !ctx.Read(mask) )
                return false;
            if( mask & VARIABLE_QUANTITY )
            {
                if ( !ctx.Read(value) )
                    return false;
                if ( m_IsStoreLoad )
                {
                    m_StoreLoadedQuantity = value;
                }
                else
                {
                    SetQuantity(value, true, false, false, false );
                }
            }
            //--------------------------------------------
            if( mask & VARIABLE_TEMPERATURE )
            {
                if ( !ctx.Read(value) )
                    return false;
                SetTemperature(value);
            }
            //--------------------------------------------
            if( mask & VARIABLE_WET )
            {
                if ( !ctx.Read(value) )
                    return false;
                SetWet(value);
            }
            //--------------------------------------------
            if( mask & VARIABLE_LIQUIDTYPE )
            {
                if ( !ctx.Read(intValue) )
                    return false;
                SetLiquidType(intValue);
            }
            //--------------------------------------------
            if( mask & VARIABLE_COLOR )
            {
                if ( !ctx.Read(intValue) )
                    return false;
                m_ColorComponentR = intValue;
                if ( !ctx.Read(value) )
                    return false;
                m_ColorComponentG = intValue;
                if ( !ctx.Read(value) )
                    return false;
                m_ColorComponentB = intValue;
                if ( !ctx.Read(value) )
                    return false;
                m_ColorComponentA = intValue;
            }
            //--------------------------------------------
            if( mask & VARIABLE_CLEANNESS )
            {
                if ( !ctx.Read(intValue) )
                    return false;
                SetCleanness(intValue);
            }
        }
        return true;
    }
References CachedObjectsArrays::ARRAY_FLOAT, DeSerializeNumericalVars(), m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_IsStoreLoad, m_StoreLoadedQuantity, CachedObjectsParams::PARAM1_FLOAT, CachedObjectsParams::PARAM1_INT, Serializer::Read(), SetCleanness(), SetLiquidType(), SetQuantity(), SetTemperature(), SetWet(), VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_TEMPERATURE, and VARIABLE_WET.
RefreshPhysics()
void InventoryItem::RefreshPhysics () inline private
Definition at line 1130 of file itembase.c.
    {
    }
RegisterOverheatingParticle()
void InventoryItem::RegisterOverheatingParticle (Particle p, float min_heat_coef, float max_heat_coef, int particle_id, Object parent, vector local_pos, vector local_ori) inline private
Definition at line 571 of file itembase.c.
    {
        if (!m_OverheatingParticles)
            m_OverheatingParticles = new array<ref OverheatingParticle>;
        OverheatingParticle OP = new OverheatingParticle();
        OP.RegisterParticle(p);
        OP.SetOverheatingLimitMin(min_heat_coef);
        OP.SetOverheatingLimitMax(max_heat_coef);
        OP.SetParticleParams(particle_id, parent, local_pos, local_ori);
        m_OverheatingParticles.Insert(OP);
    }
References m_OverheatingParticles, particle_id, OverheatingParticle::RegisterParticle(), OverheatingParticle::SetOverheatingLimitMax(), OverheatingParticle::SetOverheatingLimitMin(), and OverheatingParticle::SetParticleParams().
RemoveAction()
void InventoryItem::RemoveAction (typename actionName) inline private
Definition at line 342 of file itembase.c.
    {
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        ActionBase action = player.GetActionManager().GetAction(actionName);
        typename ai = action.GetInputType();
        array<ActionBase_Basic> action_array = m_InputActionMap.Get( ai );
        if (action_array)
        {
            action_array.RemoveItem(action);
        }
    }
References ActionBase(), GetGame(), GetPlayer(), and m_InputActionMap.
RemoveAgent()
override void InventoryItem::RemoveAgent (int agent_id) inline private
Definition at line 3977 of file itembase.c.
    {
        if( ContainsAgent(agent_id) )
        {
            m_AttachedAgents = ~agent_id & m_AttachedAgents;
        }
    }
References ContainsAgent(), and m_AttachedAgents.
RemoveAllAgents()
override void InventoryItem::RemoveAllAgents () inline private
Definition at line 3986 of file itembase.c.
    {
        m_AttachedAgents = 0;
    }
References m_AttachedAgents.
RemoveAllAgentsExcept()
override void InventoryItem::RemoveAllAgentsExcept (int agents_to_keep_mask) inline private
Definition at line 3991 of file itembase.c.
    {
        m_AttachedAgents = m_AttachedAgents & agent_to_keep;
    }
References m_AttachedAgents.
RemoveItemVariable()
void InventoryItem::RemoveItemVariable (int variable) inline private
Removes variable from variable mask, making it appear as though the variable has never been changed from default.
Definition at line 3640 of file itembase.c.
    {
        m_VariablesMask = ~variable & m_VariablesMask;
    }
References m_VariablesMask.
RemoveLightSourceItem()
void InventoryItem::RemoveLightSourceItem () inline private
Definition at line 4716 of file itembase.c.
    {
        m_LightSourceItem = null;
    }
References m_LightSourceItem.
Repair()
bool InventoryItem::Repair (PlayerBase player, ItemBase item_repair_kit, float specialty_weight) inline private
Definition at line 2491 of file itembase.c.
    {
        PluginRepairing module_repairing = PluginRepairing.Cast( GetPlugin(PluginRepairing) );
        return module_repairing.Repair(player, this, item_repair_kit, specialty_weight);
    }
References GetPlugin().
SaveAgents()
void InventoryItem::SaveAgents (ParamsWriteContext ctx) inline private
Definition at line 4065 of file itembase.c.
    {
        ctx.Write(m_AttachedAgents);
    }
References m_AttachedAgents, and Serializer::Write().
SaveVariables()
void InventoryItem::SaveVariables (ParamsWriteContext ctx) inline private
Definition at line 2983 of file itembase.c.
    {
        //Debug.Log("Saving Item Stage 0 "+ClassName(this)+" " + ToString(this));
        //first set the flags
        int varFlags = 0;
        if ( m_VariablesMask )
            varFlags = ItemVariableFlags.FLOAT;
        ctx.Write(varFlags);
        //-------------------
        //now serialize the variables
        //floats
        if ( m_VariablesMask )
            WriteVarsToCTX(ctx);
    }
References ItemVariableFlags::FLOAT, m_VariablesMask, Serializer::Write(), and WriteVarsToCTX().
SerializeNumericalVars()
void InventoryItem::SerializeNumericalVars (array< float > floats_out) inline private
Definition at line 2726 of file itembase.c.
    {
        // the order of serialization must be the same as the order of de-serialization
        floats_out.Insert(m_VariablesMask);
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_QUANTITY) )
        {
            floats_out.Insert(m_VarQuantity);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_TEMPERATURE) )
        {
            floats_out.Insert(m_VarTemperature);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_WET) )
        {
            floats_out.Insert(m_VarWet);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_LIQUIDTYPE) )
        {
            floats_out.Insert(m_VarLiquidType);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_COLOR) )
        {
            floats_out.Insert(m_ColorComponentR);
            floats_out.Insert(m_ColorComponentG);
            floats_out.Insert(m_ColorComponentB);
            floats_out.Insert(m_ColorComponentA);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_CLEANNESS) )
        {
            floats_out.Insert(m_Cleanness);
        }
        //--------------------------------------------
    }
References IsVariableSet(), m_Cleanness, m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_VariablesMask, m_VarLiquidType, m_VarQuantity, m_VarTemperature, m_VarWet, VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_TEMPERATURE, and VARIABLE_WET.
SetActions()
void InventoryItem::SetActions () inline private
Definition at line 292 of file itembase.c.
    {
        AddAction(ActionTakeItem);
        AddAction(ActionTakeItemToHands);
        AddAction(ActionWorldCraft);
        //AddAction(ActionWorldCraftSwitch);
        AddAction(ActionDropItem);
        AddAction(ActionAttachWithSwitch);
        //AddAction();
        //AddAction();
    }
References AddAction().
SetCanBeMovedOverride()
void InventoryItem::SetCanBeMovedOverride (bool setting) inline private
Definition at line 2520 of file itembase.c.
    {
        m_CanBeMovedOverride = setting;
    }
References m_CanBeMovedOverride.
SetCEBasedQuantity()
void InventoryItem::SetCEBasedQuantity () inline private
Definition at line 746 of file itembase.c.
    {
        if ( GetEconomyProfile() )
        {
            float q_min = GetEconomyProfile().GetQuantityMin();
            float q_max = GetEconomyProfile().GetQuantityMax();
            if ( q_max > 0 )
            {
                float quantity_randomized = Math.RandomFloatInclusive(q_min, q_max);
                //PrintString("<==> Normalized quantity for item: "+ GetType()+", qmin:"+q_min.ToString()+"; qmax:"+q_max.ToString()+";quantity:" +quantity_randomized.ToString());
                    SetQuantityNormalized(quantity_randomized, false);
            }
        }
    }
References Math::RandomFloatInclusive(), and SetQuantityNormalized().
SetCleanness()
void InventoryItem::SetCleanness (int value, bool allow_client = false) inline private
Definition at line 3820 of file itembase.c.
    {
        if ( !IsServerCheck(allow_client) )
            return;
        int previousValue = m_Cleanness;
        m_Cleanness = Math.Clamp(value, m_CleannessMin, m_CleannessMax);
        if ( previousValue != m_Cleanness )
            SetVariableMask(VARIABLE_CLEANNESS);
    }
References Math::Clamp(), IsServerCheck(), m_Cleanness, m_CleannessMax, m_CleannessMin, SetVariableMask(), and VARIABLE_CLEANNESS.
SetColor()
void InventoryItem::SetColor (int r, int g, int b, int a) inline private
Definition at line 3855 of file itembase.c.
    {
        m_ColorComponentR = r;
        m_ColorComponentG = g;
        m_ColorComponentB = b;
        m_ColorComponentA = a;
        SetVariableMask(VARIABLE_COLOR);
    }
References m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, SetVariableMask(), and VARIABLE_COLOR.
SetDebugActionsMask()
static void InventoryItem::SetDebugActionsMask (int mask) inline static private
Definition at line 741 of file itembase.c.
    {
        ItemBase.m_DebugActionsMask = mask;
    }
SetIsBeingPlaced()
void InventoryItem::SetIsBeingPlaced (bool is_being_placed) inline private
Definition at line 888 of file itembase.c.
    {
        m_IsBeingPlaced = is_being_placed;
        if (!is_being_placed)
            OnEndPlacement();
        SetSynchDirty();
    }
References m_IsBeingPlaced, and ItemBase::OnEndPlacement().
SetIsDeploySound()
void InventoryItem::SetIsDeploySound (bool is_deploy_sound) inline private
Definition at line 4437 of file itembase.c.
    {
        m_IsDeploySound = is_deploy_sound;
    }
References m_IsDeploySound.
SetIsHologram()
void InventoryItem::SetIsHologram (bool is_hologram) inline private
Definition at line 914 of file itembase.c.
    {
        m_IsHologram = is_hologram;
        SetSynchDirty();
    }
References m_IsHologram.
SetIsPlaceSound()
void InventoryItem::SetIsPlaceSound (bool is_place_sound) inline private
Definition at line 4427 of file itembase.c.
    {
        m_IsPlaceSound = is_place_sound;
    }
References m_IsPlaceSound.
SetLiquidType()
void InventoryItem::SetLiquidType (int value, bool allow_client = false) inline private
Definition at line 3891 of file itembase.c.
    {
        if( !IsServerCheck(allow_client) ) return;
        m_VarLiquidType = value;
        SetVariableMask(VARIABLE_LIQUIDTYPE);
    }
References IsServerCheck(), m_VarLiquidType, SetVariableMask(), and VARIABLE_LIQUIDTYPE.
SetQuantity()
bool InventoryItem::SetQuantity (float value, bool destroy_config = true, bool destroy_forced = false, bool allow_client = false, bool clamp_to_stack_max = true) inline private
Set item quantity[related to varQuantity... config entry], destroy_config = true > if the quantity reaches varQuantityMin or lower and the item config contains the varQuantityDestroyOnMin = true entry, the item gets destroyed. destroy_forced = true means item gets destroyed when quantity reaches varQuantityMin or lower regardless of config setting, returns true if the item gets deleted.
Definition at line 3236 of file itembase.c.
    {
        if ( !IsServerCheck(allow_client) )
            return false;
        if ( !HasQuantity() )
            return false;
        if ( IsLiquidContainer() && GetLiquidType() == 0 )
        {
            Debug.LogError("No LiquidType specified, try setting 'varLiquidTypeInit' to a particular liquid type");
            return false;
        }
        float min = GetQuantityMin();
        float max = GetQuantityMax();
        bool on_min_value = value <= (min + 0.001); //workaround, items with "varQuantityDestroyOnMin = true;" get destroyed
        if ( on_min_value )
        {
            if ( destroy_config )
            {
                bool dstr = ConfigGetBool("varQuantityDestroyOnMin");
                if ( dstr )
                {
                    m_VarQuantity = Math.Clamp(value, min, max);
                    this.Delete();
                    return true;
                }
            }
            else if ( destroy_forced )
            {
                m_VarQuantity = Math.Clamp(value, min, max);
                this.Delete();
                return true;
            }
            // we get here if destroy_config IS true AND dstr(config destroy param) IS false;
            RemoveAllAgents();//we remove all agents when we got to the min value, but the item is not getting deleted
        }
        float delta = m_VarQuantity;
        m_VarQuantity = Math.Clamp(value, min, max);
        if ( m_StoreLoadedQuantity == float.LOWEST )//any other value means we are setting quantity from storage
        {
            delta = m_VarQuantity - delta;
            if (delta)
            {
                OnQuantityChanged(delta);
            }
        }
        SetVariableMask(VARIABLE_QUANTITY);
        return false;
    }
References Math::Clamp(), ConfigGetBool(), Delete(), GetLiquidType(), GetQuantityMax(), GetQuantityMin(), HasQuantity(), IsLiquidContainer(), IsServerCheck(), Debug::LogError(), LOWEST, m_StoreLoadedQuantity, m_VarQuantity, OnQuantityChanged(), RemoveAllAgents(), SetVariableMask(), and VARIABLE_QUANTITY.
SetQuantityMax()
void InventoryItem::SetQuantityMax () inline private
Definition at line 3302 of file itembase.c.
    {
        float max = GetQuantityMax();
        SetQuantity(max);
    }
References GetQuantityMax(), and SetQuantity().
SetQuantityNormalized()
void InventoryItem::SetQuantityNormalized (float value, bool destroy_config = true, bool destroy_forced = false) inline private
Sets quantity in normalized 0..1 form between the item's Min a Max values as defined by item's config(for Min 0 and Max 5000, setting 0.5 will result in value 2500)
Definition at line 3309 of file itembase.c.
    {
        float value_clamped = Math.Clamp(value, 0, 1);//just to make sure
        int result = Math.Round(Math.Lerp(GetQuantityMin(), GetQuantityMax(), value_clamped));
        SetQuantity(result, destroy_config, destroy_forced);
    }
References Math::Clamp(), GetQuantityMax(), GetQuantityMin(), Math::Lerp(), Math::Round(), and SetQuantity().
SetResultOfSplit()
void InventoryItem::SetResultOfSplit (bool value) inline private
Definition at line 2030 of file itembase.c.
    {
        m_IsResultOfSplit = value;
    }
SetTakeable()
override void InventoryItem::SetTakeable (bool pState) inline private
Definition at line 4355 of file itembase.c.
    {
        m_IsTakeable = pState;
        SetSynchDirty();
    }
References m_IsTakeable.
SetTemperature()
override void InventoryItem::SetTemperature (float value, bool allow_client = false) inline private
Definition at line 3692 of file itembase.c.
    {
        if ( !IsServerCheck(allow_client) )
            return;
        float min = GetTemperatureMin();
        float max = GetTemperatureMax();
        float previousValue = m_VarTemperature;
        m_VarTemperature = Math.Clamp(value, min, max);
        if ( previousValue != m_VarTemperature )
            SetVariableMask(VARIABLE_TEMPERATURE);
    }
References Math::Clamp(), GetTemperatureMax(), GetTemperatureMin(), IsServerCheck(), m_VarTemperature, SetVariableMask(), and VARIABLE_TEMPERATURE.
SetTemperatureMax()
override void InventoryItem::SetTemperatureMax () inline private
Definition at line 3712 of file itembase.c.
    {
        SetTemperature(m_VarTemperatureMax);
    }
References m_VarTemperatureMax, and SetTemperature().
SetVariableMask()
void InventoryItem::SetVariableMask (int variable) inline private
Definition at line 3630 of file itembase.c.
    {
        m_VariablesMask = variable | m_VariablesMask;
        if( GetGame().IsServer() )
        {
            SetSynchDirty();
        }
    }
References GetGame(), and m_VariablesMask.
SetWet()
override void InventoryItem::SetWet (float value, bool allow_client = false) inline private
Definition at line 3746 of file itembase.c.
    {
        if ( !IsServerCheck(allow_client) )
            return;
        float min = GetWetMin();
        float max = GetWetMax();
        float previousValue = m_VarWet;
        m_VarWet = Math.Clamp(value, min, max);
        //UpdateWeight();
        if ( previousValue != m_VarWet )
            SetVariableMask(VARIABLE_WET);
    }
References Math::Clamp(), GetWetMax(), GetWetMin(), IsServerCheck(), m_VarWet, SetVariableMask(), and VARIABLE_WET.
SetWetMax()
override void InventoryItem::SetWetMax () inline private
Definition at line 3769 of file itembase.c.
    {
        SetWet(m_VarWetMax);
    }
References m_VarWetMax, and SetWet().
SetZoneDamageCEInit()
void InventoryItem::SetZoneDamageCEInit () inline private
Sets zone damages to match randomized global health set by CE (CE spawn only)
Definition at line 4558 of file itembase.c.
    {
        float global_health = GetHealth01("","Health");
        array<string> zones = new array<string>;
        GetDamageZones(zones);
        //set damage of all zones to match global health level
        for (int i = 0; i < zones.Count(); i++)
        {
            SetHealth01(zones.Get(i),"Health",global_health);
        }
    }
References GetDamageZones(), GetHealth01(), and SetHealth01().
SoundSynchRemote()
void InventoryItem::SoundSynchRemote () inline private
Definition at line 4395 of file itembase.c.
    {
        m_IsSoundSynchRemote = true;
        SetSynchDirty();
    }
References m_IsSoundSynchRemote.
SoundSynchRemoteReset()
void InventoryItem::SoundSynchRemoteReset () inline private
Definition at line 4388 of file itembase.c.
    {
        m_IsSoundSynchRemote = false;
        SetSynchDirty();
    }
References m_IsSoundSynchRemote.
SplitIntoStackMax()
void InventoryItem::SplitIntoStackMax (EntityAI destination_entity, int slot_id, PlayerBase player) inline private
Definition at line 1521 of file itembase.c.
    {
        float split_quantity_new;
        ref ItemBase new_item;
        float quantity = GetQuantity();
        float stack_max = GetTargetQuantityMax(slot_id);
        InventoryLocation loc = new InventoryLocation;
        if ( destination_entity && slot_id != -1 && InventorySlots.IsSlotIdValid( slot_id ) )
        {
            if ( stack_max <= GetQuantity() )
                split_quantity_new = stack_max;
            else
                split_quantity_new = GetQuantity();
            new_item = ItemBase.Cast( destination_entity.GetInventory().CreateAttachmentEx( this.GetType(), slot_id ) );
            if ( new_item )
            {
                new_item.SetResultOfSplit(true);
                MiscGameplayFunctions.TransferItemProperties( this, new_item );
                AddQuantity( -split_quantity_new );
                new_item.SetQuantity( split_quantity_new );
            }
        }
        else if ( destination_entity && slot_id == -1 )
        {
            if ( quantity > stack_max )
                split_quantity_new = stack_max;
            else
                split_quantity_new = quantity;
            if (destination_entity.GetInventory().FindFreeLocationFor( this, FindInventoryLocationType.ANY, loc ))
            {
                Object o = destination_entity.GetInventory().LocationCreateEntity( loc, GetType(), ECE_IN_INVENTORY, RF_DEFAULT );
                new_item = ItemBase.Cast( o );
            }
            if ( new_item )
            {
                new_item.SetResultOfSplit(true);
                MiscGameplayFunctions.TransferItemProperties( this, new_item );
                AddQuantity( -split_quantity_new );
                new_item.SetQuantity( split_quantity_new );
            }
        }
        else
        {
            if ( stack_max != 0 )
            {
                if ( stack_max < GetQuantity() )
                {
                    split_quantity_new = GetQuantity() - stack_max;
                }
                if ( split_quantity_new == 0 )
                {
                    if ( !GetGame().IsMultiplayer() )
                        player.PhysicalPredictiveDropItem( this );
                    else
                        player.ServerDropEntity( this );
                    return;
                }
                new_item = ItemBase.Cast( GetGame().CreateObjectEx( GetType(), player.GetWorldPosition(), ECE_PLACE_ON_SURFACE ) );
                if ( new_item )
                {
                    new_item.SetResultOfSplit(true);
                    MiscGameplayFunctions.TransferItemProperties( this, new_item );
                    SetQuantity( split_quantity_new );
                    new_item.SetQuantity( stack_max );
                    new_item.PlaceOnSurface();
                }
            }
        }
    }
References AddQuantity(), ECE_IN_INVENTORY, ECE_PLACE_ON_SURFACE, GetGame(), GetQuantity(), GetTargetQuantityMax(), GetType(), InventorySlots::IsSlotIdValid(), RF_DEFAULT, and SetQuantity().
SplitIntoStackMaxCargo()
void InventoryItem::SplitIntoStackMaxCargo (EntityAI destination_entity, int idx, int row, int col) inline private
Definition at line 1680 of file itembase.c.
    {
        float quantity = GetQuantity();
        float split_quantity_new;
        ref ItemBase new_item;
        if( destination_entity )
        {
            float stackable = GetTargetQuantityMax();
            if( quantity > stackable )
                split_quantity_new = stackable;
            else
                split_quantity_new = quantity;
            new_item = ItemBase.Cast( destination_entity.GetInventory().CreateEntityInCargoEx( this.GetType(), idx, row, col, false ) );
            if( new_item )
            {
                new_item.SetResultOfSplit(true);
                MiscGameplayFunctions.TransferItemProperties(this,new_item);
                AddQuantity( -split_quantity_new );
                new_item.SetQuantity( split_quantity_new );
            }
        }
    }
References AddQuantity(), GetQuantity(), and GetTargetQuantityMax().
SplitIntoStackMaxCargoClient()
void InventoryItem::SplitIntoStackMaxCargoClient (EntityAI destination_entity, int idx, int row, int col) inline private
Definition at line 1619 of file itembase.c.
    {
        if( GetGame().IsClient() )
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                ctx.Write(2);
                ItemBase dummy = this; // @NOTE: workaround for correct serialization
                ctx.Write(dummy);
                ctx.Write(destination_entity);
                ctx.Write(true);
                ctx.Write(idx);
                ctx.Write(row);
                ctx.Write(col);
                ctx.Send();
            }
        }
        else if( !GetGame().IsMultiplayer() )
        {
            SplitIntoStackMaxCargo( destination_entity, idx, row, col );
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxCargo(), and Serializer::Write().
SplitIntoStackMaxClient()
void InventoryItem::SplitIntoStackMaxClient (EntityAI destination_entity, int slot_id) inline private
Definition at line 1498 of file itembase.c.
    {
        if( GetGame().IsClient() )
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                ctx.Write(1);
                ItemBase i1 = this; // @NOTE: workaround for correct serialization
                ctx.Write(i1);
                ctx.Write(destination_entity);
                ctx.Write(true);
                ctx.Write(slot_id);
                ctx.Send();
            }
        }
        else if( !GetGame().IsMultiplayer() )
        {
            SplitIntoStackMax( destination_entity, slot_id, PlayerBase.Cast( GetGame().GetPlayer() ) );
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetPlayer(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMax(), and Serializer::Write().
SplitIntoStackMaxHands()
void InventoryItem::SplitIntoStackMaxHands (PlayerBase player) inline private
Definition at line 1728 of file itembase.c.
    {
        float quantity = GetQuantity();
        float split_quantity_new;
        ref ItemBase new_item;
        if( player )
        {
            float stackable = GetTargetQuantityMax();
            if( quantity > stackable )
                split_quantity_new = stackable;
            else
                split_quantity_new = quantity;
            EntityAI in_hands = player.GetHumanInventory().CreateInHands(this.GetType());
            new_item = ItemBase.Cast(in_hands);
            if( new_item )
            {
                new_item.SetResultOfSplit(true);
                MiscGameplayFunctions.TransferItemProperties(this,new_item);
                AddQuantity( -split_quantity_new );
                new_item.SetQuantity( split_quantity_new );
            }
        }
    }
References AddQuantity(), GetQuantity(), GetTargetQuantityMax(), and GetType().
SplitIntoStackMaxHandsClient()
void InventoryItem::SplitIntoStackMaxHandsClient (PlayerBase player) inline private
Definition at line 1704 of file itembase.c.
    {
        if( GetGame().IsClient() )
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                ctx.Write(3);
                ItemBase i1 = this; // @NOTE: workaround for correct serialization
                ctx.Write(i1);
                ItemBase destination_entity = this;
                ctx.Write(destination_entity);
                ctx.Write(true);
                ctx.Write(0);
                ctx.Send();
            }
        }
        else if( !GetGame().IsMultiplayer() )
        {
            SplitIntoStackMaxHands( player );
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxHands(), and Serializer::Write().
SplitIntoStackMaxToInventoryLocation()
void InventoryItem::SplitIntoStackMaxToInventoryLocation (notnull InventoryLocation dst) inline private
Definition at line 1644 of file itembase.c.
    {
        SplitIntoStackMaxToInventoryLocationEx( dst );
    }
References SplitIntoStackMaxToInventoryLocationEx().
SplitIntoStackMaxToInventoryLocationClient()
void InventoryItem::SplitIntoStackMaxToInventoryLocationClient (notnull InventoryLocation dst) inline private
Definition at line 1598 of file itembase.c.
    {
        if ( GetGame().IsClient() )
        {
            if (ScriptInputUserData.CanStoreInputUserData())
            {
                ScriptInputUserData ctx = new ScriptInputUserData;
                ctx.Write(INPUT_UDT_ITEM_MANIPULATION);
                ctx.Write(4);
                ItemBase thiz = this; // @NOTE: workaround for correct serialization
                ctx.Write(thiz);
                dst.WriteToContext(ctx);
                ctx.Send();
            }
        }
        else if ( !GetGame().IsMultiplayer() )
        {
            SplitIntoStackMaxToInventoryLocation( dst );
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), INPUT_UDT_ITEM_MANIPULATION, ScriptInputUserData::Send(), SplitIntoStackMaxToInventoryLocation(), and Serializer::Write().
SplitIntoStackMaxToInventoryLocationEx()
ItemBase InventoryItem::SplitIntoStackMaxToInventoryLocationEx (notnull InventoryLocation dst) inline private
Definition at line 1649 of file itembase.c.
    {
        float quantity = GetQuantity();
        float split_quantity_new;
        ItemBase new_item;
        if ( dst.IsValid() )
        {
            int slot_id = dst.GetSlot();
            float stack_max = GetTargetQuantityMax(slot_id);
            if ( quantity > stack_max )
                split_quantity_new = stack_max;
            else
                split_quantity_new = quantity;
            new_item = ItemBase.Cast( GameInventory.LocationCreateEntity( dst, this.GetType(), ECE_IN_INVENTORY, RF_DEFAULT ) );
            if ( new_item )
            {
                new_item.SetResultOfSplit(true);
                MiscGameplayFunctions.TransferItemProperties(this,new_item);
                AddQuantity( -split_quantity_new );
                new_item.SetQuantity( split_quantity_new );
            }
            return new_item;
        }
        return null;
    }
References AddQuantity(), ECE_IN_INVENTORY, GetQuantity(), ItemBase::GetSlot(), GetTargetQuantityMax(), and RF_DEFAULT.
SplitItem()
void InventoryItem::SplitItem (PlayerBase player) inline private
Definition at line 1786 of file itembase.c.
    {
        if ( !CanBeSplit() )
        {
            return;
        }
        float quantity = GetQuantity();
        float split_quantity_new = Math.Floor(quantity / 2);
        InventoryLocation invloc = new InventoryLocation;
        bool found = player.GetInventory().FindFirstFreeLocationForNewEntity(GetType(), FindInventoryLocationType.ATTACHMENT, invloc);
        ItemBase new_item;
        new_item = player.CreateCopyOfItemInInventoryOrGroundEx(this, true);
        if (new_item)
        {
            if (new_item.GetQuantityMax() < split_quantity_new)
            {
                split_quantity_new = new_item.GetQuantityMax();
            }
            if (found && invloc.IsValid() && invloc.GetType() == InventoryLocationType.ATTACHMENT && split_quantity_new > 1)
            {
                AddQuantity(-1);
                new_item.SetQuantity(1);
            }
            else
            {
                AddQuantity(-split_quantity_new);
                new_item.SetQuantity( split_quantity_new );
            }
        }
    }
References AddQuantity(), CanBeSplit(), Math::Floor(), GetQuantity(), GetType(), InventoryLocation::GetType(), and InventoryLocation::IsValid().
SplitItemToInventoryLocation()
void InventoryItem::SplitItemToInventoryLocation (notnull InventoryLocation dst) inline private
Definition at line 1753 of file itembase.c.
    {
        if ( !CanBeSplit() )
            return;
        float quantity = GetQuantity();
        float split_quantity_new = Math.Floor( quantity * 0.5 );
        ItemBase new_item = ItemBase.Cast( GameInventory.LocationCreateEntity( dst, GetType(), ECE_IN_INVENTORY, RF_DEFAULT ) );
        if ( new_item )
        {
            if (new_item.GetQuantityMax() < split_quantity_new)
            {
                split_quantity_new = new_item.GetQuantityMax();
            }
            new_item.SetResultOfSplit(true);
            MiscGameplayFunctions.TransferItemProperties(this, new_item);
            if (dst.IsValid() && dst.GetType() == InventoryLocationType.ATTACHMENT && split_quantity_new > 1)
            {
                AddQuantity(-1);
                new_item.SetQuantity(1);
            }
            else
            {
                AddQuantity(-split_quantity_new);
                new_item.SetQuantity( split_quantity_new );
            }
        }
    }
References AddQuantity(), CanBeSplit(), ECE_IN_INVENTORY, Math::Floor(), GetQuantity(), GetType(), and RF_DEFAULT.
StartOverheating()
void InventoryItem::StartOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
Definition at line 552 of file itembase.c.
    {
        m_IsOverheatingEffectActive = true;
        ItemBase.PlayOverheatingParticles(this, ammoType, this, suppressor, "CfgWeapons" );
    }
References m_IsOverheatingEffectActive.
StopItemDynamicPhysics()
void InventoryItem::StopItemDynamicPhysics () inline private
Definition at line 4540 of file itembase.c.
    {
        SetDynamicPhysicsLifeTime(0.01);
        m_ItemBeingDroppedPhys = false;
    }
References m_ItemBeingDroppedPhys, and SetDynamicPhysicsLifeTime().
StopOverheating()
void InventoryItem::StopOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
Definition at line 565 of file itembase.c.
    {
        m_IsOverheatingEffectActive = false;
        ItemBase.StopOverheatingParticles(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
    }
References m_IsOverheatingEffectActive.
StopOverheatingParticles()
static void InventoryItem::StopOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
Definition at line 4290 of file itembase.c.
    {
        int id = muzzle_owner.GetMuzzleID();
        array<ref WeaponParticlesOnOverheating> WPOOH_array = weapon.m_OnOverheatingEffect.Get(id);
        if (WPOOH_array)
        {
            for (int i = 0; i < WPOOH_array.Count(); i++)
            {
                WeaponParticlesOnOverheating WPOOH = WPOOH_array.Get(i);
                if (WPOOH)
                {
                    WPOOH.OnDeactivate(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
                }
            }
        }
    }
TransferAgents()
void InventoryItem::TransferAgents (int agents) inline private
transfer agents from another item
Definition at line 4005 of file itembase.c.
    {
        m_AttachedAgents = (m_AttachedAgents | agents);
    }
References m_AttachedAgents.
TransferModifiers()
void InventoryItem::TransferModifiers (PlayerBase reciever) private
TransferVariablesFloat()
void InventoryItem::TransferVariablesFloat (array< float > float_vars) inline private
Definition at line 2675 of file itembase.c.
    {
        DeSerializeNumericalVars(float_vars);
    }
References DeSerializeNumericalVars().
UnlockFromParent()
void InventoryItem::UnlockFromParent () inline private
Unlocks this item from its attachment slot of its parent.
Definition at line 775 of file itembase.c.
    {
        EntityAI parent = GetHierarchyParent();
        if (parent)
        {
            InventoryLocation inventory_location_to_unlock = new InventoryLocation;
            GetInventory().GetCurrentInventoryLocation( inventory_location_to_unlock );
            parent.GetInventory().SetSlotLock( inventory_location_to_unlock.GetSlot(), false );
        }
    }
References InventoryLocation::GetSlot().
UpdateAllOverheatingParticles()
void InventoryItem::UpdateAllOverheatingParticles () inline private
Definition at line 593 of file itembase.c.
    {
        if (m_OverheatingParticles)
        {
            float overheat_coef = GetOverheatingCoef();
            int count = m_OverheatingParticles.Count();
            for (int i = count; i > 0; --i)
            {
                int id = i - 1;
                OverheatingParticle OP = m_OverheatingParticles.Get(id);
                Particle p = OP.GetParticle();
                float overheat_min = OP.GetOverheatingLimitMin();
                float overheat_max = OP.GetOverheatingLimitMax();
                if (overheat_coef < overheat_min  &&  overheat_coef >= overheat_max)
                {
                    if (p)
                    {
                        p.Stop();
                        OP.RegisterParticle(null);
                    }
                }
            }
        }
    }
References GetOverheatingCoef(), OverheatingParticle::GetOverheatingLimitMax(), OverheatingParticle::GetOverheatingLimitMin(), OverheatingParticle::GetParticle(), m_OverheatingParticles, OverheatingParticle::RegisterParticle(), and Particle::Stop().
UpdateOverheating()
void InventoryItem::UpdateOverheating (ItemBase weapon = null, string ammoType = "", ItemBase muzzle_owner = null, ItemBase suppressor = null, string config_to_search = "") inline private
Definition at line 558 of file itembase.c.
    {
        KillAllOverheatingParticles();
        ItemBase.UpdateOverheatingParticles(this, ammoType, this, suppressor, "CfgWeapons" );
        UpdateAllOverheatingParticles();
    }
References KillAllOverheatingParticles(), and UpdateAllOverheatingParticles().
UpdateOverheatingParticles()
static void InventoryItem::UpdateOverheatingParticles (ItemBase weapon, string ammoType, ItemBase muzzle_owner, ItemBase suppressor, string config_to_search) inline static private
Definition at line 4270 of file itembase.c.
    {
        int id = muzzle_owner.GetMuzzleID();
        array<ref WeaponParticlesOnOverheating> WPOOH_array = weapon.m_OnOverheatingEffect.Get(id);
        if (WPOOH_array)
        {
            for (int i = 0; i < WPOOH_array.Count(); i++)
            {
                WeaponParticlesOnOverheating WPOOH = WPOOH_array.Get(i);
                if (WPOOH)
                {
                    WPOOH.OnUpdate(weapon, ammoType, muzzle_owner, suppressor, config_to_search);
                }
            }
        }
    }
UpdateWeight()
override void InventoryItem::UpdateWeight (WeightUpdateType updateType = WeightUpdateType.FULL, float weightAdjustment = 0) inline private
Definition at line 3433 of file itembase.c.
    {
        //float itemWetness = GetWet() + 1;
        float current_quantity = GetQuantity();
        /*DumpStack();
        Print(this);
        Print("Initial weight: " + m_Weight);
        Print("Initial adjustement: " + weightAdjustment);
        Print("current_quantity: " + current_quantity);
        Print("updateType: " + updateType);*/
        switch (updateType)
        {
            case WeightUpdateType.FULL:
                {
                    int i = 0;
                    float totalWeight;
                    //float item_wetness = this.GetWet();
                    int AttachmentsCount = 0;
                    CargoBase cargo;
                    /*Print("this: " + this);
                    Print("GetInventory() " + GetInventory());
                    Print("-----------------------------");*/
                    if (GetInventory())
                    {
                        AttachmentsCount = GetInventory().AttachmentCount();
                        cargo = GetInventory().GetCargo();
                    }
                    //attachments?
                    if (AttachmentsCount > 0)
                    {
                        for (i = 0; i < AttachmentsCount; i++)
{
                            totalWeight += GetInventory().GetAttachmentFromIndex(i).GetWeight();
                        }
                    }
                    //cargo?
                    if (cargo != NULL )
                    {
                        for (i = 0; i < cargo.GetItemCount(); i++)
{
                            totalWeight += cargo.GetItem(i).GetWeight();
                        }
                    }
                    //other
                    {
                        if ( m_CanThisBeSplit ) //quantity determines size of the stack
{
                            totalWeight += /*Math.Round((item_wetness + 1) **/ this.GetQuantity() * m_ConfigWeight;
                            //Print("this: " + this);
                            //Print("this.GetQuantity(): " + this.GetQuantity());
                            //Print("totalWeight: " + totalWeight);
                            //Print("-----------------------------");
                        }
                        else if (this.ConfigGetString("stackedUnit") == "cm") //duct tape, at the moment
{
                            int MaxLength = GetQuantityMax();
                            totalWeight += /*Math.Round(((item_wetness + 1) **/ m_ConfigWeight * (this.GetQuantity() / MaxLength);
                        }
                        else //quantity determines weight of item without container (i.e. sardines in a can)
{
                            totalWeight += /*Math.Round((item_wetness + 1) **/ (this.GetQuantity() + m_ConfigWeight);
                        }
                    }
                    m_Weight = Math.Round(totalWeight);
                    //Print("FULL");
                    //Print("weightAdjustment: " + weightAdjustment);
                    //Print("m_Weight: " + m_Weight);
                }
                break;
            case WeightUpdateType.ADD:
                m_Weight += weightAdjustment;
                //Print("ADD");
                //Print("weightAdjustment: " + weightAdjustment);
                //Print("m_Weight: " + m_Weight);
                break;
            case WeightUpdateType.REMOVE:
                m_Weight -= weightAdjustment;
                //Print("REMOVE");
                //Print("weightAdjustment: " + weightAdjustment);
                //Print("m_Weight: " + m_Weight);
                break;
            case WeightUpdateType.RECURSIVE_ADD:
                {
                    if (weightAdjustment == 0) //First one in hierarchy
                    {
                        current_quantity = GetQuantity();
                        if ( m_CanThisBeSplit ) //quantity determines size of the stack
{
                            weightAdjustment = /*itemWetness **/ current_quantity * m_ConfigWeight;
                        }
                        else if (ConfigGetString("stackedUnit") == "cm") //duct tape, at the moment
{
                            weightAdjustment = /*itemWetness **/ m_ConfigWeight * (current_quantity / GetQuantityMax());
                        }
                        else //quantity determines weight of item without container (i.e. sardines in a can)
{
                            weightAdjustment = /*itemWetness **/ (current_quantity + m_ConfigWeight);
                        }
                        weightAdjustment = Math.Round(weightAdjustment);
                    }
                    m_Weight += weightAdjustment;
                    //Print("RECURSIVE_ADD");
                    //Print("weightAdjustment: " + weightAdjustment);
                    //Print("m_Weight: " + m_Weight);
                    EntityAI hierarchyParent = GetHierarchyParent();
                    if (hierarchyParent && !hierarchyParent.IsInherited(PlayerBase))
                        hierarchyParent.UpdateWeight(WeightUpdateType.RECURSIVE_ADD, weightAdjustment);
                }
                break;
            case WeightUpdateType.RECURSIVE_REMOVE:
                {
                    if (weightAdjustment == 0) //First one in hierarchy
                    {
                        current_quantity = GetQuantity();
                        if ( m_CanThisBeSplit ) //quantity determines size of the stack
{
                            weightAdjustment = /*itemWetness **/ current_quantity * m_ConfigWeight;
                        }
                        else if (ConfigGetString("stackedUnit") == "cm") //duct tape, at the moment
{
                            weightAdjustment = /*itemWetness **/ m_ConfigWeight * (current_quantity/GetQuantityMax());
                        }
                        else //quantity determines weight of item without container (i.e. sardines in a can)
{
                            weightAdjustment = /*itemWetness **/ (current_quantity + m_ConfigWeight);
                        }
                        weightAdjustment = Math.Round(weightAdjustment);
                    }
                    m_Weight -= weightAdjustment;
                    //Print("RECURSIVE_REMOVE");
                    //Print("weightAdjustment: " + weightAdjustment);
                    //Print("m_Weight: " + m_Weight);
                    EntityAI hp = GetHierarchyParent();
                    if (hp && !hp.IsInherited(PlayerBase))
                        hp.UpdateWeight(WeightUpdateType.RECURSIVE_REMOVE, weightAdjustment);
                }
                break;
            default:
                break;
        }
    }
References ConfigGetString(), CargoBase::GetItem(), CargoBase::GetItemCount(), GetQuantity(), GetQuantityMax(), m_CanThisBeSplit, m_ConfigWeight, and Math::Round().
WriteVarsToCTX()
void InventoryItem::WriteVarsToCTX (ParamsWriteContext ctx) inline private
Definition at line 2830 of file itembase.c.
    {
        ctx.Write(m_VariablesMask);
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_QUANTITY) )
        {
            ctx.Write(m_VarQuantity);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_TEMPERATURE) )
        {
            ctx.Write(m_VarTemperature);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_WET) )
        {
            ctx.Write(m_VarWet);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_LIQUIDTYPE) )
        {
            ctx.Write(m_VarLiquidType);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_COLOR) )
        {
            ctx.Write(m_ColorComponentR);
            ctx.Write(m_ColorComponentG);
            ctx.Write(m_ColorComponentB);
            ctx.Write(m_ColorComponentA);
        }
        //--------------------------------------------
        if( IsVariableSet(VARIABLE_CLEANNESS) )
        {
            ctx.Write(m_Cleanness);
        }
    }
References IsVariableSet(), m_Cleanness, m_ColorComponentA, m_ColorComponentB, m_ColorComponentG, m_ColorComponentR, m_VariablesMask, m_VarLiquidType, m_VarQuantity, m_VarTemperature, m_VarWet, VARIABLE_CLEANNESS, VARIABLE_COLOR, VARIABLE_LIQUIDTYPE, VARIABLE_QUANTITY, VARIABLE_TEMPERATURE, VARIABLE_WET, and Serializer::Write().
Member Data Documentation
can_this_be_combined
bool InventoryItem::can_this_be_combined = false private
Definition at line 71 of file itembase.c.
m_ActionsInitialize
bool InventoryItem::m_ActionsInitialize private
Definition at line 17 of file itembase.c.
m_AdminLog
PluginAdminLog InventoryItem::m_AdminLog private
Definition at line 122 of file itembase.c.
m_AttachedAgents
private int InventoryItem::m_AttachedAgents private
Definition at line 96 of file itembase.c.
m_CanBeDigged
protected bool InventoryItem::m_CanBeDigged private
Definition at line 76 of file itembase.c.
m_CanBeMovedOverride
bool InventoryItem::m_CanBeMovedOverride private
Definition at line 69 of file itembase.c.
m_CanShowQuantity
bool InventoryItem::m_CanShowQuantity private
Definition at line 74 of file itembase.c.
m_CanThisBeSplit
bool InventoryItem::m_CanThisBeSplit = false private
Definition at line 72 of file itembase.c.
m_CheckOverheating
ref Timer InventoryItem::m_CheckOverheating private
Definition at line 112 of file itembase.c.
m_Cleanness
int InventoryItem::m_Cleanness private
Definition at line 46 of file itembase.c.
m_CleannessInit
int InventoryItem::m_CleannessInit private
Definition at line 47 of file itembase.c.
m_CleannessMax
int InventoryItem::m_CleannessMax private
Definition at line 49 of file itembase.c.
m_CleannessMin
int InventoryItem::m_CleannessMin private
Definition at line 48 of file itembase.c.
m_ColorComponentA
int InventoryItem::m_ColorComponentA private
Definition at line 84 of file itembase.c.
m_ColorComponentB
int InventoryItem::m_ColorComponentB private
Definition at line 83 of file itembase.c.
m_ColorComponentG
int InventoryItem::m_ColorComponentG private
Definition at line 82 of file itembase.c.
m_ColorComponentR
int InventoryItem::m_ColorComponentR private
Definition at line 81 of file itembase.c.
m_CompatibleLocks
ref array<int> InventoryItem::m_CompatibleLocks = new array<int> private
Definition at line 128 of file itembase.c.
m_ConfigWeight
float InventoryItem::m_ConfigWeight = -1 private
Definition at line 57 of file itembase.c.
m_ContinuousActions
ref TIntArray InventoryItem::m_ContinuousActions private
Definition at line 91 of file itembase.c.
m_Count
int InventoryItem::m_Count private
Definition at line 32 of file itembase.c.
m_DebugActionsMask
int InventoryItem::m_DebugActionsMask static private
Definition at line 19 of file itembase.c.
m_FixDamageSystemInit
bool InventoryItem::m_FixDamageSystemInit = false private
Definition at line 70 of file itembase.c.
m_HasQuantityBar
bool InventoryItem::m_HasQuantityBar private
Definition at line 75 of file itembase.c.
m_HeadHidingSelections
protected ref TStringArray InventoryItem::m_HeadHidingSelections private
Definition at line 118 of file itembase.c.
m_HeatIsolation
float InventoryItem::m_HeatIsolation private
Definition at line 55 of file itembase.c.
m_HideSelectionsBySlot
protected bool InventoryItem::m_HideSelectionsBySlot private
Definition at line 119 of file itembase.c.
m_ImpactSoundSurfaceHash
int InventoryItem::m_ImpactSoundSurfaceHash private
Definition at line 53 of file itembase.c.
m_ImpactSpeed
float InventoryItem::m_ImpactSpeed private
Definition at line 52 of file itembase.c.
m_InputActionMap
TInputActionMap InventoryItem::m_InputActionMap private
Definition at line 16 of file itembase.c.
m_InteractActions
ref TIntArray InventoryItem::m_InteractActions private
Definition at line 92 of file itembase.c.
m_IsBeingPlaced
bool InventoryItem::m_IsBeingPlaced private
Definition at line 61 of file itembase.c.
m_IsDeploySound
bool InventoryItem::m_IsDeploySound private
Definition at line 64 of file itembase.c.
m_IsHologram
bool InventoryItem::m_IsHologram private
Definition at line 62 of file itembase.c.
m_IsOverheatingEffectActive
bool InventoryItem::m_IsOverheatingEffectActive private
Definition at line 110 of file itembase.c.
m_IsPlaceSound
bool InventoryItem::m_IsPlaceSound private
Definition at line 63 of file itembase.c.
m_IsSoundSynchRemote
bool InventoryItem::m_IsSoundSynchRemote private
Definition at line 66 of file itembase.c.
m_IsStoreLoad
bool InventoryItem::m_IsStoreLoad = false private
Definition at line 73 of file itembase.c.
m_IsTakeable
bool InventoryItem::m_IsTakeable private
Definition at line 65 of file itembase.c.
m_ItemBehaviour
int InventoryItem::m_ItemBehaviour = -1 private
Definition at line 59 of file itembase.c.
m_ItemBeingDroppedPhys
bool InventoryItem::m_ItemBeingDroppedPhys private
Definition at line 68 of file itembase.c.
m_ItemModelLength
float InventoryItem::m_ItemModelLength private
Definition at line 56 of file itembase.c.
m_ItemTypeActionsMap
ref map<typename, ref TInputActionMap> InventoryItem::m_ItemTypeActionsMap = new map<typename, ref TInputActionMap> static private
Definition at line 15 of file itembase.c.
m_LastRegisteredWeaponID
int InventoryItem::m_LastRegisteredWeaponID = 0 static private
Definition at line 107 of file itembase.c.
m_LightSourceItem
ItemBase InventoryItem::m_LightSourceItem private
Definition at line 88 of file itembase.c.
m_LockingSound
protected ref EffectSound InventoryItem::m_LockingSound private
Definition at line 130 of file itembase.c.
m_LockSoundSet
protected string InventoryItem::m_LockSoundSet = "" private
Definition at line 131 of file itembase.c.
m_LockType
protected int InventoryItem::m_LockType private
Definition at line 129 of file itembase.c.
m_MaxOverheatingValue
int InventoryItem::m_MaxOverheatingValue = 0 private
Definition at line 114 of file itembase.c.
m_OnBulletCasingEjectEffect
ref map<int, ref array<ref WeaponParticlesOnBulletCasingEject> > InventoryItem::m_OnBulletCasingEjectEffect static private
Definition at line 104 of file itembase.c.
m_OnFireEffect
ref map<int, ref array<ref WeaponParticlesOnFire> > InventoryItem::m_OnFireEffect static private
Definition at line 103 of file itembase.c.
m_OnOverheatingEffect
ref map<int, ref array<ref WeaponParticlesOnOverheating> > InventoryItem::m_OnOverheatingEffect private
Definition at line 105 of file itembase.c.
m_OverheatingDecayInterval
float InventoryItem::m_OverheatingDecayInterval = 1 private
Definition at line 115 of file itembase.c.
m_OverheatingParticles
ref array<ref OverheatingParticle> InventoryItem::m_OverheatingParticles private
Definition at line 116 of file itembase.c.
m_OverheatingShots
float InventoryItem::m_OverheatingShots private
Definition at line 111 of file itembase.c.
m_PhysDropTimer
ref Timer InventoryItem::m_PhysDropTimer private
Definition at line 125 of file itembase.c.
m_QuickBarBonus
int InventoryItem::m_QuickBarBonus = 0 private
Definition at line 60 of file itembase.c.
m_RecipesInitialized
bool InventoryItem::m_RecipesInitialized private
Definition at line 20 of file itembase.c.
m_ShotsToStartOverheating
int InventoryItem::m_ShotsToStartOverheating = 0 private
Definition at line 113 of file itembase.c.
m_SingleUseActions
ref TIntArray InventoryItem::m_SingleUseActions private
Definition at line 90 of file itembase.c.
m_SoundAttType
protected bool m_IsResultOfSplit string InventoryItem::m_SoundAttType private
distinguish if item has been created as new or it came from splitting (server only flag)
Definition at line 79 of file itembase.c.
m_StoreLoadedQuantity
float InventoryItem::m_StoreLoadedQuantity = float.LOWEST private
Definition at line 34 of file itembase.c.
m_ThrowItemOnDrop
bool InventoryItem::m_ThrowItemOnDrop private
Definition at line 67 of file itembase.c.
m_VariablesMask
int InventoryItem::m_VariablesMask private
Definition at line 26 of file itembase.c.
m_VarLiquidType
int InventoryItem::m_VarLiquidType private
Definition at line 58 of file itembase.c.
m_VarQuantity
float InventoryItem::m_VarQuantity private
Definition at line 28 of file itembase.c.
m_VarQuantityInit
int InventoryItem::m_VarQuantityInit private
Definition at line 29 of file itembase.c.
m_VarQuantityMax
int InventoryItem::m_VarQuantityMax private
Definition at line 31 of file itembase.c.
m_VarQuantityMin
int InventoryItem::m_VarQuantityMin private
Definition at line 30 of file itembase.c.
m_VarStackMax
float InventoryItem::m_VarStackMax private
Definition at line 33 of file itembase.c.
m_VarTemperature
float InventoryItem::m_VarTemperature private
Definition at line 36 of file itembase.c.
m_VarTemperatureInit
float InventoryItem::m_VarTemperatureInit private
Definition at line 37 of file itembase.c.
m_VarTemperatureMax
float InventoryItem::m_VarTemperatureMax private
Definition at line 39 of file itembase.c.
m_VarTemperatureMin
float InventoryItem::m_VarTemperatureMin private
Definition at line 38 of file itembase.c.
m_VarWet
float InventoryItem::m_VarWet private
Definition at line 41 of file itembase.c.
m_VarWetInit
float InventoryItem::m_VarWetInit private
Definition at line 42 of file itembase.c.
m_VarWetMax
float InventoryItem::m_VarWetMax private
Definition at line 44 of file itembase.c.
m_VarWetMin
float InventoryItem::m_VarWetMin private
Definition at line 43 of file itembase.c.
m_WantPlayImpactSound
bool InventoryItem::m_WantPlayImpactSound private
Definition at line 51 of file itembase.c.
m_WeaponTypeToID
ref map<string, int> InventoryItem::m_WeaponTypeToID static private
Definition at line 106 of file itembase.c.