DayzKode: AnalyticsManagerServer Class Reference
AnalyticsManagerServer Class Reference
Private Member Functions
void OnEntityHit (EntityAI source, Man target)
void OnEntityKilled (Object killer, EntityAI target)
protected void OnInfectedKilled (Man killer, EntityAI target)
void OnPlayerConnect (Man player)
void OnPlayerDisconnect (Man player)
protected void OnPlayerKilled (Man killer, EntityAI target)
protected void OnPlayerToPlayerHit (Man shooter, Man target)
Private Attributes
const string STAT_DISTANCE = "dist"
const string STAT_INFECTED_KILLED = "infected_killed"
const string STAT_LONGEST_SURVIVOR_HIT = "longest_survivor_hit"
const string STAT_PLAYERS_KILLED = "players_killed"
const string STAT_PLAYTIME = "playtime"
Detailed Description
Definition at line 1 of file analyticsmanagerserver.c.
Member Function Documentation
OnEntityHit()
void AnalyticsManagerServer::OnEntityHit (EntityAI source, Man target) inline private
Definition at line 41 of file analyticsmanagerserver.c.
    {
        if (source)
        {
            Man survivor = source.GetHierarchyRootPlayer();
            if ( survivor && source.IsWeapon() )
            {
                OnPlayerToPlayerHit( survivor, target );
            }
        }
    }
References OnPlayerToPlayerHit().
Referenced by ManBase::EEHitBy().
OnEntityKilled()
void AnalyticsManagerServer::OnEntityKilled (Object killer, EntityAI target) inline private
Definition at line 78 of file analyticsmanagerserver.c.
    {
        EntityAI killer_entity = EntityAI.Cast( killer );
        if ( killer_entity )
        {
            Man killer_survivor = killer_entity.GetHierarchyRootPlayer();
            if ( killer_survivor )
            {
                if ( target.IsPlayer() )
                {
                    OnPlayerKilled( killer_survivor, target );
                }
                else if ( target.IsZombie() )
                {
                    OnInfectedKilled( killer_survivor, target );
                }
            }
        }
    }
References OnInfectedKilled(), and OnPlayerKilled().
Referenced by Plastic_Explosive::EEKilled(), and Ammo_40mm_Smoke_ColorBase::EEKilled().
OnInfectedKilled()
protected void AnalyticsManagerServer::OnInfectedKilled (Man killer, EntityAI target) inline private
Definition at line 113 of file analyticsmanagerserver.c.
    {
        /*
        Print("");
        Print("-------------");
        Print(killer.GetDisplayName() + " killed infected " + target.GetDisplayName() );
        Print("-------------");
        Print("");
        */
        //update stat
        killer.StatUpdate( STAT_INFECTED_KILLED, 1 );
//      killer.StatSyncToClient();
    }
References STAT_INFECTED_KILLED.
Referenced by OnEntityKilled().
OnPlayerConnect()
void AnalyticsManagerServer::OnPlayerConnect (Man player) inline private
Definition at line 9 of file analyticsmanagerserver.c.
    {
        player.StatRegister( STAT_DISTANCE );
        player.StatRegister( STAT_PLAYTIME );
        player.StatRegister( STAT_PLAYERS_KILLED );
        player.StatRegister( STAT_INFECTED_KILLED );
        player.StatRegister( STAT_LONGEST_SURVIVOR_HIT );
        //player.StatSyncToClient();
    }
References STAT_DISTANCE, STAT_INFECTED_KILLED, STAT_LONGEST_SURVIVOR_HIT, STAT_PLAYERS_KILLED, and STAT_PLAYTIME.
Referenced by ManBase::OnConnect().
OnPlayerDisconnect()
void AnalyticsManagerServer::OnPlayerDisconnect (Man player) inline private
Definition at line 20 of file analyticsmanagerserver.c.
    {
        player.StatUpdateByPosition( STAT_DISTANCE );
        player.StatUpdateByTime( STAT_PLAYTIME );
        /*
        Print("");
        Print("-------------");
        Print( STAT_DISTANCE                + " " + player.StatGet( STAT_DISTANCE ).ToString() );
        Print( STAT_PLAYTIME                + " " + player.StatGet( STAT_PLAYTIME ).ToString() );
        Print( STAT_PLAYERS_KILLED          + " " + player.StatGet( STAT_PLAYERS_KILLED ).ToString() );
        Print( STAT_INFECTED_KILLED         + " " + player.StatGet( STAT_INFECTED_KILLED ).ToString() );
        Print( STAT_LONGEST_SURVIVOR_HIT    + " " + player.StatGet( STAT_LONGEST_SURVIVOR_HIT ).ToString() );
        Print("-------------");
        Print("");
        */
        //player.StatSyncToClient();
    }
References STAT_DISTANCE, and STAT_PLAYTIME.
Referenced by ManBase::OnDisconnect().
OnPlayerKilled()
protected void AnalyticsManagerServer::OnPlayerKilled (Man killer, EntityAI target) inline private
Definition at line 98 of file analyticsmanagerserver.c.
    {
        /*
        Print("");
        Print("-------------");
        Print(killer.GetDisplayName() + " killed player " + target.GetDisplayName() );
        Print("-------------");
        Print("");
        */
        //update stat
        killer.StatUpdate( STAT_PLAYERS_KILLED, 1 );
//      killer.StatSyncToClient();
    }
References STAT_PLAYERS_KILLED.
Referenced by OnEntityKilled().
OnPlayerToPlayerHit()
protected void AnalyticsManagerServer::OnPlayerToPlayerHit (Man shooter, Man target) inline private
Definition at line 53 of file analyticsmanagerserver.c.
    {
        //calculate distance
        float longest_hit_dist = shooter.StatGet( STAT_LONGEST_SURVIVOR_HIT );
        float current_dist = vector.Distance( shooter.GetPosition(), target.GetPosition() );
        float dist_update;
        if ( longest_hit_dist < current_dist )
        {
            dist_update = current_dist - longest_hit_dist;
        }
        /*
        Print("");
        Print("-------------");
        Print(shooter.GetDisplayName() + " hit " + target.GetDisplayName() + " from " + longest_hit_dist.ToString() + " m" );
        Print("-------------");
        Print("");
        */
        //update stat
        shooter.StatUpdate( STAT_LONGEST_SURVIVOR_HIT, dist_update );
    }
References vector::Distance(), and STAT_LONGEST_SURVIVOR_HIT.
Referenced by OnEntityHit().
Member Data Documentation
STAT_DISTANCE
const string AnalyticsManagerServer::STAT_DISTANCE = "dist" private
Definition at line 3 of file analyticsmanagerserver.c.
Referenced by OnPlayerConnect(), OnPlayerDisconnect(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_INFECTED_KILLED
const string AnalyticsManagerServer::STAT_INFECTED_KILLED = "infected_killed" private
Definition at line 6 of file analyticsmanagerserver.c.
Referenced by OnInfectedKilled(), OnPlayerConnect(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_LONGEST_SURVIVOR_HIT
const string AnalyticsManagerServer::STAT_LONGEST_SURVIVOR_HIT = "longest_survivor_hit" private
Definition at line 7 of file analyticsmanagerserver.c.
Referenced by OnPlayerConnect(), OnPlayerToPlayerHit(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_PLAYERS_KILLED
const string AnalyticsManagerServer::STAT_PLAYERS_KILLED = "players_killed" private
Definition at line 5 of file analyticsmanagerserver.c.
Referenced by OnPlayerConnect(), OnPlayerKilled(), and ScriptedWidgetEventHandler::UpdateStats().
STAT_PLAYTIME
const string AnalyticsManagerServer::STAT_PLAYTIME = "playtime" private
Definition at line 4 of file analyticsmanagerserver.c.
Referenced by OnPlayerConnect(), OnPlayerDisconnect(), and ScriptedWidgetEventHandler::UpdateStats().