DayzKode: ConstructionActionData Class Reference
ConstructionActionData Class Reference
Private Member Functions
void CombineItems (ItemBase target, ItemBase item)
void ConstructionActionData ()
PlayerBase GetActionInitiator ()
EntityAI GetActualAttachmentToDetach ()
void GetAttachmentsFromSelection (EntityAI target, string selection, out array< EntityAI > attachments)
int GetAttachmentSlotFromSelection (PlayerBase player, EntityAI target, ItemBase item_to_attach, string selection)
int GetAttachmentsToDetachCount ()
ConstructionPart GetBuildPartAtIndex (int idx)
ConstructionPart GetBuildPartNoToolAtIndex (int idx)
CombinationLock GetCombinationLock ()
int GetConstructionPartsCount ()
ConstructionPart GetCurrentBuildPart ()
string GetDialNumberText ()
string GetMainPartName ()
string GetMainPartNameNoTool ()
int GetSlotId ()
Object GetTarget ()
ConstructionPart GetTargetPart ()
void OnUpdateActions (Object item, Object target, int component_index)
void OnUpdateActionsNoTool (Object item, Object target, int component_index)
void RefreshAttachmentsToDetach (EntityAI target, string main_part_name)
void RefreshPartsToBuild (string main_part_name, ItemBase tool, bool use_tool=true)
void ResetActionIndexes ()
void SetActionInitiator (PlayerBase action_initiator)
void SetCombinationLock (CombinationLock combination_lock)
void SetNextAttachmentIndex ()
void SetNextIndex ()
void SetSlotId (int slot_id)
void SetTarget (Object target)
void SetTargetPart (ConstructionPart target_part)
Private Attributes
PlayerBase m_ActionInitiator
protected ActionVariantManager m_ActionNoToolVariantManager
protected ActionVariantManager m_ActionVariantManager
ref array< EntityAI > m_Attachments
int m_AttachmentsIndex
ref array< ConstructionPart > m_BuildParts
ref array< ConstructionPart > m_BuildPartsNoTool
CombinationLock m_CombinationLock
string m_MainPartName
string m_MainPartNameNoTool
int m_PartIndex
int m_SlotId
Object m_Target
ref ConstructionPart m_TargetPart
Detailed Description
Definition at line 1 of file constructionactiondata.c.
Constructor & Destructor Documentation
ConstructionActionData()
void ConstructionActionData::ConstructionActionData () inline private
Definition at line 28 of file constructionactiondata.c.
    {
        m_BuildParts = new ref array<ConstructionPart>;
        m_BuildPartsNoTool = new ref array<ConstructionPart>;
        m_PartIndex = 0;
        m_Attachments = new ref array<EntityAI>;
        m_AttachmentsIndex = 0;
        if ( GetGame().IsClient() || !GetGame().IsMultiplayer() )
        {
            m_ActionVariantManager = ActionManagerClient.GetVariantManager( ActionBuildPart );
            m_ActionVariantManager.GetOnUpdateInvoker().Clear();
            m_ActionVariantManager.GetOnUpdateInvoker().Insert(OnUpdateActions);
            m_ActionNoToolVariantManager = ActionManagerClient.GetVariantManager( ActionBuildShelter );
            m_ActionNoToolVariantManager.GetOnUpdateInvoker().Clear();
            m_ActionNoToolVariantManager.GetOnUpdateInvoker().Insert(OnUpdateActionsNoTool);
        }
    }
References ScriptInvoker::Clear(), GetGame(), ActionVariantManager::GetOnUpdateInvoker(), ActionManagerClient::GetVariantManager(), ScriptInvoker::Insert(), m_ActionNoToolVariantManager, m_ActionVariantManager, m_Attachments, m_AttachmentsIndex, m_BuildParts, m_BuildPartsNoTool, m_PartIndex, OnUpdateActions(), and OnUpdateActionsNoTool().
Member Function Documentation
CombineItems()
void ConstructionActionData::CombineItems (ItemBase target, ItemBase item) inline private
Definition at line 322 of file constructionactiondata.c.
    {
        if ( target.ConfigGetBool( "canBeSplit" ) && item && !target.IsFullQuantity() )
        {
            int quantity_used = target.ComputeQuantityUsed( item, true );
            if( quantity_used != 0 )
            {
                target.AddQuantity( quantity_used );
                item.AddQuantity( -quantity_used );
            }
        }
    }
GetActionInitiator()
PlayerBase ConstructionActionData::GetActionInitiator () inline private
Definition at line 97 of file constructionactiondata.c.
    {
        return m_ActionInitiator;
    }
References m_ActionInitiator.
Referenced by BaseBuildingBase::CanReceiveAttachment().
GetActualAttachmentToDetach()
EntityAI ConstructionActionData::GetActualAttachmentToDetach () inline private
Definition at line 364 of file constructionactiondata.c.
    {
        if ( GetAttachmentsToDetachCount() > 0 )
        {
            m_AttachmentsIndex = Math.Clamp( m_AttachmentsIndex, 0, GetAttachmentsToDetachCount() - 1 );
            if ( m_Attachments && GetAttachmentsToDetachCount() > ( m_AttachmentsIndex ) )
            {
                return m_Attachments.Get( m_AttachmentsIndex );
            }
        }
        return NULL;
    }
References Math::Clamp(), GetAttachmentsToDetachCount(), m_Attachments, and m_AttachmentsIndex.
Referenced by ActionTakeMaterialToHands::ActionCondition(), ActionTakeMaterialToHands::CreateAndSetupActionCallback(), ActionTakeMaterialToHands::OnActionInfoUpdate(), and ActionTakeMaterialToHands::OnExecuteImpl().
GetAttachmentsFromSelection()
void ConstructionActionData::GetAttachmentsFromSelection (EntityAI target, string selection, out array< EntityAI > attachments) inline private
Definition at line 284 of file constructionactiondata.c.
    {
        attachments.Clear();        //clear output
        string cfg_path = "cfgVehicles" + " " + target.GetType() + " "+ "GUIInventoryAttachmentsProps";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                string child_selection;
                GetGame().ConfigGetText( cfg_path + " " + child_name + " " + "selection", child_selection );
                if ( selection == child_selection )
                {
                    ref array<string> attachment_slots = new array<string>;
                    GetGame().ConfigGetTextArray( cfg_path + " " + child_name + " " + "attachmentSlots", attachment_slots );
                    for ( int j = 0; j < attachment_slots.Count(); ++j )
                    {
                        int target_slot_id = InventorySlots.GetSlotIdFromString( attachment_slots.Get( j ) );
                        //is attached and can be detached
                        EntityAI attachment = target.GetInventory().FindAttachment( target_slot_id );
                        if ( attachment && target.GetInventory().CanRemoveAttachmentEx( attachment, target_slot_id ) && !target.GetInventory().GetSlotLock( target_slot_id ) )
{
                            attachments.Insert( attachment );
                        }
                    }
                }
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and InventorySlots::GetSlotIdFromString().
Referenced by RefreshAttachmentsToDetach().
GetAttachmentSlotFromSelection()
int ConstructionActionData::GetAttachmentSlotFromSelection (PlayerBase player, EntityAI target, ItemBase item_to_attach, string selection) inline private
Definition at line 234 of file constructionactiondata.c.
    {
        string cfg_path = "cfgVehicles" + " " + target.GetType() + " "+ "GUIInventoryAttachmentsProps";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                string child_selection;
                GetGame().ConfigGetText( cfg_path + " " + child_name + " " + "selection", child_selection );
                if ( selection == child_selection )
                {
                    ref array<string> attachment_slots = new array<string>;
                    GetGame().ConfigGetTextArray( cfg_path + " " + child_name + " " + "attachmentSlots", attachment_slots );
                    for ( int j = 0; j < attachment_slots.Count(); ++j )
                    {
                        int target_slot_id = InventorySlots.GetSlotIdFromString( attachment_slots.Get( j ) );
                        int item_slot_count = item_to_attach.GetInventory().GetSlotIdCount();
                        for ( int k = 0; k < item_slot_count; ++k )
{
                            int item_slot_id = item_to_attach.GetInventory().GetSlotId( k );
                            ItemBase attachment_item = ItemBase.Cast( target.GetInventory().FindAttachment( item_slot_id ) );
                            if ( target_slot_id == item_slot_id )
{
                                if (  target.GetInventory().CanAddAttachmentEx( item_to_attach, item_slot_id ) && target.CanReceiveAttachment( item_to_attach, item_slot_id ) || attachment_item && attachment_item.CanBeCombined( item_to_attach ) )
{
                                    if(target.CanDisplayAttachmentSlot(target_slot_id))
                                        return item_slot_id;
                                    else
                                        return -1;
                                }
                            }
                        }
                    }
                }
            }
        }
        return -1;
    }
References ItemBase::CanBeCombined(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and InventorySlots::GetSlotIdFromString().
Referenced by ActionAttachToConstruction::ActionCondition().
GetAttachmentsToDetachCount()
int ConstructionActionData::GetAttachmentsToDetachCount () inline private
Definition at line 359 of file constructionactiondata.c.
    {
        return m_Attachments.Count();
    }
References m_Attachments.
Referenced by ActionTakeMaterialToHandsSwitch::ActionCondition(), GetActualAttachmentToDetach(), and SetNextAttachmentIndex().
GetBuildPartAtIndex()
ConstructionPart ConstructionActionData::GetBuildPartAtIndex (int idx) inline private
Definition at line 168 of file constructionactiondata.c.
    {
        if( m_BuildParts.Count() > idx )
        {
            return m_BuildParts.Get( idx );
        }
        return null;
    }
References m_BuildParts.
Referenced by BuildCondition(), ComplexBuildCollideCheckClient(), ActionBuildPart::OnActionInfoUpdate(), and ActionBuildPart::SetupAction().
GetBuildPartNoToolAtIndex()
ConstructionPart ConstructionActionData::GetBuildPartNoToolAtIndex (int idx) inline private
Definition at line 177 of file constructionactiondata.c.
    {
        if( m_BuildPartsNoTool.Count() > idx )
        {
            return m_BuildPartsNoTool.Get( idx );
        }
        return null;
    }
References m_BuildPartsNoTool.
Referenced by BuildCondition(), ComplexBuildCollideCheckClient(), ActionBuildShelter::DetermineConstructionSounds(), ActionBuildShelter::GetText(), ActionBuildShelter::OnActionInfoUpdate(), and ActionBuildShelter::SetupAction().
GetCombinationLock()
CombinationLock ConstructionActionData::GetCombinationLock () inline private
Definition at line 189 of file constructionactiondata.c.
    {
        return m_CombinationLock;
    }
References m_CombinationLock.
Referenced by OnFinishProgressServer(), and ActionNextCombinationLockDialOnTarget::Start().
GetConstructionPartsCount()
int ConstructionActionData::GetConstructionPartsCount () inline private
Definition at line 157 of file constructionactiondata.c.
    {
        return m_BuildParts.Count();
    }
References m_BuildParts.
GetCurrentBuildPart()
ConstructionPart ConstructionActionData::GetCurrentBuildPart () inline private
Definition at line 163 of file constructionactiondata.c.
    {
        return null;
    }
GetDialNumberText()
string ConstructionActionData::GetDialNumberText () inline private
Definition at line 199 of file constructionactiondata.c.
    {
        string dial_text;
        if ( m_CombinationLock )
        {
            string combination_text = m_CombinationLock.GetCombination().ToString();
            //insert zeros to dials with 0 value
            int length_diff = m_CombinationLock.GetLockDigits() - combination_text.Length();
            for ( int i = 0; i < length_diff; ++i )
            {
                combination_text = "0" + combination_text;
            }
            //assemble the whole combination with selected part
            for ( int j = 0; j < m_CombinationLock.GetLockDigits(); ++j )
            {
                if ( j == m_CombinationLock.GetDialIndex() )
                {
                    dial_text += string.Format( "[%1]", combination_text.Get( j ) );
                }
                else
                {
                    dial_text += string.Format( " %1 ", combination_text.Get( j ) );
                }
            }
        }
        return dial_text;
    }
References string::Format(), string::Get(), string::Length(), and m_CombinationLock.
Referenced by OnActionInfoUpdate().
GetMainPartName()
string ConstructionActionData::GetMainPartName () inline private
Definition at line 52 of file constructionactiondata.c.
    {
        return m_MainPartName;
    }
References m_MainPartName.
GetMainPartNameNoTool()
string ConstructionActionData::GetMainPartNameNoTool () inline private
Definition at line 57 of file constructionactiondata.c.
    {
        return m_MainPartNameNoTool;
    }
References m_MainPartNameNoTool.
GetSlotId()
int ConstructionActionData::GetSlotId () inline private
Definition at line 87 of file constructionactiondata.c.
    {
        return m_SlotId;
    }
References m_SlotId.
Referenced by ActionAttachToConstruction::OnExecuteImpl().
GetTarget()
Object ConstructionActionData::GetTarget () inline private
Definition at line 67 of file constructionactiondata.c.
    {
        return m_Target;
    }
References m_Target.
GetTargetPart()
ConstructionPart ConstructionActionData::GetTargetPart () inline private
Definition at line 77 of file constructionactiondata.c.
    {
        return m_TargetPart;
    }
References m_TargetPart.
Referenced by ActionDismantlePart::GetAdminLogMessage(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionDestroyPart::OnActionInfoUpdate(), ActionDismantlePart::OnActionInfoUpdate(), ActionRepairPart::OnActionInfoUpdate(), ActionDestroyPart::OnFinishProgressServer(), and ActionDismantlePart::OnFinishProgressServer().
OnUpdateActions()
void ConstructionActionData::OnUpdateActions (Object item, Object target, int component_index) inline private
Definition at line 113 of file constructionactiondata.c.
    {
        ItemBase tool = ItemBase.Cast( item );
        if ( tool )
        {
            BaseBuildingBase base_building_object = BaseBuildingBase.Cast( target );
            if ( base_building_object )
            {
                string main_part_name = target.GetActionComponentName( component_index );
                base_building_object.GetConstruction().GetConstructionPartsToBuild( main_part_name, m_BuildParts, tool, m_MainPartName, true );
                m_ActionVariantManager.SetActionVariantCount(m_BuildParts.Count());
            }
            else
            {
                m_BuildParts.Clear();
                m_ActionVariantManager.Clear();
            }
        }
        else
        {
            m_BuildParts.Clear();
            m_ActionVariantManager.Clear();
        }
        //not needed
        //m_Target = target;
    }
References ActionVariantManager::Clear(), m_ActionVariantManager, m_BuildParts, m_MainPartName, and ActionVariantManager::SetActionVariantCount().
Referenced by ConstructionActionData().
OnUpdateActionsNoTool()
void ConstructionActionData::OnUpdateActionsNoTool (Object item, Object target, int component_index) inline private
Definition at line 141 of file constructionactiondata.c.
    {
        BaseBuildingBase base_building_object = BaseBuildingBase.Cast( target );
        if ( base_building_object )
        {
            string main_part_name = target.GetActionComponentName( component_index );
            base_building_object.GetConstruction().GetConstructionPartsToBuild( main_part_name, m_BuildPartsNoTool, null, m_MainPartNameNoTool, false );
            m_ActionNoToolVariantManager.SetActionVariantCount(m_BuildPartsNoTool.Count());
        }
        else
        {
            m_BuildPartsNoTool.Clear();
            m_ActionNoToolVariantManager.Clear();
        }
    }
References ActionVariantManager::Clear(), m_ActionNoToolVariantManager, m_BuildPartsNoTool, m_MainPartNameNoTool, and ActionVariantManager::SetActionVariantCount().
Referenced by ConstructionActionData().
RefreshAttachmentsToDetach()
void ConstructionActionData::RefreshAttachmentsToDetach (EntityAI target, string main_part_name) inline private
Definition at line 335 of file constructionactiondata.c.
    {
        GetAttachmentsFromSelection( target, main_part_name, m_Attachments );
    }
References GetAttachmentsFromSelection(), and m_Attachments.
Referenced by ActionTakeMaterialToHands::ActionCondition(), and ActionTakeMaterialToHandsSwitch::ActionCondition().
RefreshPartsToBuild()
void ConstructionActionData::RefreshPartsToBuild (string main_part_name, ItemBase tool, bool use_tool = true) inline private
Definition at line 108 of file constructionactiondata.c.
    {
    }
ResetActionIndexes()
void ConstructionActionData::ResetActionIndexes () inline private
Definition at line 382 of file constructionactiondata.c.
    {
        m_PartIndex = 0;
        m_AttachmentsIndex = 0;
    }
References m_AttachmentsIndex, and m_PartIndex.
SetActionInitiator()
void ConstructionActionData::SetActionInitiator (PlayerBase action_initiator) inline private
Definition at line 92 of file constructionactiondata.c.
    {
        m_ActionInitiator = action_initiator;
    }
References m_ActionInitiator.
Referenced by BaseBuildingBase::CanReceiveAttachment(), and ActionAttachToConstruction::OnStartClient().
SetCombinationLock()
void ConstructionActionData::SetCombinationLock (CombinationLock combination_lock) inline private
Definition at line 194 of file constructionactiondata.c.
    {
        m_CombinationLock = CombinationLock.Cast( combination_lock );
    }
References m_CombinationLock.
Referenced by ActionCondition(), ActionNextCombinationLockDialOnTarget::ActionCondition(), and ActionNextCombinationLockDial::ActionCondition().
SetNextAttachmentIndex()
void ConstructionActionData::SetNextAttachmentIndex () inline private
Definition at line 340 of file constructionactiondata.c.
    {
        if ( GetAttachmentsToDetachCount() > 1 )
        {
            if ( m_AttachmentsIndex <= GetAttachmentsToDetachCount() - 2 )
            {
                m_AttachmentsIndex++;
            }
            else if ( m_AttachmentsIndex >= GetAttachmentsToDetachCount() >  - 1 )
            {
                m_AttachmentsIndex = 0;
            }
        }
        else
        {
            m_AttachmentsIndex = 0;
        }
    }
References GetAttachmentsToDetachCount(), and m_AttachmentsIndex.
Referenced by ActionTakeMaterialToHandsSwitch::Start().
SetNextIndex()
void ConstructionActionData::SetNextIndex () inline private
Definition at line 103 of file constructionactiondata.c.
    {
    }
Referenced by ActionHandsPartSwitch::SetNextIndex(), and ActionBuildPartSwitch::SetNextIndex().
SetSlotId()
void ConstructionActionData::SetSlotId (int slot_id) inline private
Definition at line 82 of file constructionactiondata.c.
    {
        m_SlotId = slot_id;
    }
References m_SlotId.
Referenced by ActionAttachToConstruction::ActionCondition().
SetTarget()
void ConstructionActionData::SetTarget (Object target) inline private
Definition at line 62 of file constructionactiondata.c.
    {
        m_Target = target;
    }
References m_Target.
Referenced by BuildCondition().
SetTargetPart()
void ConstructionActionData::SetTargetPart (ConstructionPart target_part) inline private
Definition at line 72 of file constructionactiondata.c.
    {
        m_TargetPart = target_part;
    }
References m_TargetPart.
Referenced by ActionDestroyPart::DestroyCondition(), ActionDismantlePart::DismantleCondition(), and ActionRepairPart::RepairCondition().
Member Data Documentation
m_ActionInitiator
PlayerBase ConstructionActionData::m_ActionInitiator private
Definition at line 19 of file constructionactiondata.c.
Referenced by GetActionInitiator(), and SetActionInitiator().
m_ActionNoToolVariantManager
protected ActionVariantManager ConstructionActionData::m_ActionNoToolVariantManager private
Definition at line 24 of file constructionactiondata.c.
Referenced by ConstructionActionData(), and OnUpdateActionsNoTool().
m_ActionVariantManager
protected ActionVariantManager ConstructionActionData::m_ActionVariantManager private
Definition at line 23 of file constructionactiondata.c.
Referenced by ConstructionActionData(), and OnUpdateActions().
m_Attachments
ref array<EntityAI> ConstructionActionData::m_Attachments private
Definition at line 21 of file constructionactiondata.c.
Referenced by ConstructionActionData(), GetActualAttachmentToDetach(), GetAttachmentsToDetachCount(), and RefreshAttachmentsToDetach().
m_AttachmentsIndex
int ConstructionActionData::m_AttachmentsIndex private
Definition at line 26 of file constructionactiondata.c.
Referenced by ConstructionActionData(), GetActualAttachmentToDetach(), ResetActionIndexes(), and SetNextAttachmentIndex().
m_BuildParts
ref array<ConstructionPart> ConstructionActionData::m_BuildParts private
Definition at line 6 of file constructionactiondata.c.
Referenced by ConstructionActionData(), GetBuildPartAtIndex(), GetConstructionPartsCount(), and OnUpdateActions().
m_BuildPartsNoTool
ref array<ConstructionPart> ConstructionActionData::m_BuildPartsNoTool private
Definition at line 7 of file constructionactiondata.c.
Referenced by ConstructionActionData(), GetBuildPartNoToolAtIndex(), and OnUpdateActionsNoTool().
m_CombinationLock
CombinationLock ConstructionActionData::m_CombinationLock private
Definition at line 15 of file constructionactiondata.c.
Referenced by GetCombinationLock(), GetDialNumberText(), and SetCombinationLock().
m_MainPartName
string ConstructionActionData::m_MainPartName private
Definition at line 10 of file constructionactiondata.c.
Referenced by GetMainPartName(), and OnUpdateActions().
m_MainPartNameNoTool
string ConstructionActionData::m_MainPartNameNoTool private
Definition at line 11 of file constructionactiondata.c.
Referenced by GetMainPartNameNoTool(), and OnUpdateActionsNoTool().
m_PartIndex
int ConstructionActionData::m_PartIndex private
Definition at line 9 of file constructionactiondata.c.
Referenced by ConstructionActionData(), and ResetActionIndexes().
m_SlotId
int ConstructionActionData::m_SlotId private
Definition at line 18 of file constructionactiondata.c.
Referenced by GetSlotId(), and SetSlotId().
m_Target
Object ConstructionActionData::m_Target private
Definition at line 3 of file constructionactiondata.c.
Referenced by GetTarget(), and SetTarget().
m_TargetPart
ref ConstructionPart ConstructionActionData::m_TargetPart private
Definition at line 12 of file constructionactiondata.c.
Referenced by GetTargetPart(), and SetTargetPart().