DayzKode: PluginDayzPlayerDebugUserData Class Reference
PluginDayzPlayerDebugUserData Class Reference
Private Member Functions
int GetInt ()
int GetStanceMask ()
bool IsFullBody ()
void PluginDayzPlayerDebugUserData (int pUserData, bool pFullBody, int pStanceMask=-1)
Private Attributes
protected bool m_bIsFullBody
protected int m_iStanceMask
protected int m_iUserData
Detailed Description
Definition at line 4 of file plugindayzplayerdebug.c.
Constructor & Destructor Documentation
PluginDayzPlayerDebugUserData()
void PluginDayzPlayerDebugUserData::PluginDayzPlayerDebugUserData (int pUserData, bool pFullBody, int pStanceMask = -1) inline private
Definition at line 6 of file plugindayzplayerdebug.c.
    {
        m_iUserData     = pUserData;
        m_bIsFullBody   = pFullBody;
        m_iStanceMask   = pStanceMask;
    }
References m_bIsFullBody, m_iStanceMask, and m_iUserData.
Member Function Documentation
GetInt()
int PluginDayzPlayerDebugUserData::GetInt () inline private
Definition at line 14 of file plugindayzplayerdebug.c.
    {
        return m_iUserData;
    }
References m_iUserData.
Referenced by Actions_Start().
GetStanceMask()
int PluginDayzPlayerDebugUserData::GetStanceMask () inline private
Definition at line 24 of file plugindayzplayerdebug.c.
    {
            return m_iStanceMask;
    }
References m_iStanceMask.
Referenced by Actions_Start().
IsFullBody()
bool PluginDayzPlayerDebugUserData::IsFullBody () inline private
Definition at line 19 of file plugindayzplayerdebug.c.
    {
            return m_bIsFullBody;
    }
References m_bIsFullBody.
Referenced by Actions_Start().
Member Data Documentation
m_bIsFullBody
protected bool PluginDayzPlayerDebugUserData::m_bIsFullBody private
Definition at line 30 of file plugindayzplayerdebug.c.
Referenced by IsFullBody(), and PluginDayzPlayerDebugUserData().
m_iStanceMask
protected int PluginDayzPlayerDebugUserData::m_iStanceMask private
Definition at line 31 of file plugindayzplayerdebug.c.
Referenced by GetStanceMask(), and PluginDayzPlayerDebugUserData().
m_iUserData
protected int PluginDayzPlayerDebugUserData::m_iUserData private
Definition at line 29 of file plugindayzplayerdebug.c.
Referenced by GetInt(), and PluginDayzPlayerDebugUserData().