DayzKode: NotificationUI Class Reference
NotificationUI Class Reference
Private Member Functions
void AddNotification (NotificationRuntimeData data)
void AddVoiceNotification (string player, string name)
void ClearVoiceNotifications ()
void NotificationUI ()
void RemoveNotification (NotificationRuntimeData data)
void RemoveVoiceNotification (string player)
void Update (float timeslice)
void UpdateTargetHeight ()
void ~NotificationUI ()
Private Attributes
protected float m_CurrentHeight
protected ref Widget m_NotificationContent
protected ref map< NotificationRuntimeData, Widget > m_Notifications
protected ref Widget m_Root
protected ref Widget m_Spacer
protected float m_TargetHeight
protected ref Widget m_VoiceContent
protected ref map< string, Widget > m_VoiceNotifications
protected ref map< string, Widget > m_WidgetTimers
protected float m_Width
Static Private Attributes
static float m_VelArr [1]
Detailed Description
Definition at line 1 of file notificationui.c.
Constructor & Destructor Documentation
NotificationUI()
void NotificationUI::NotificationUI () inline private
Definition at line 16 of file notificationui.c.
    {
        m_Root                  = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notifications.layout");
        m_Spacer                = m_Root.FindAnyWidget( "NotificationSpacer" );
        m_VoiceContent          = m_Root.FindAnyWidget( "VoiceContent" );
        m_NotificationContent   = m_Root.FindAnyWidget( "NotificationContent" );
        m_Notifications         = new map<NotificationRuntimeData, Widget>;
        m_VoiceNotifications    = new map<string, Widget>;
        m_WidgetTimers          = new map<string, Widget>;
        NotificationSystem.BindOnAdd( AddNotification );
        NotificationSystem.BindOnRemove( RemoveNotification );
    }
References AddNotification(), NotificationSystem::BindOnAdd(), NotificationSystem::BindOnRemove(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_NotificationContent, m_Notifications, m_Root, m_Spacer, m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, and RemoveNotification().
~NotificationUI()
void NotificationUI::~NotificationUI () inline private
Definition at line 30 of file notificationui.c.
    {
        NotificationSystem.UnbindOnAdd( AddNotification );
        NotificationSystem.UnbindOnRemove( RemoveNotification );
    }
References AddNotification(), RemoveNotification(), NotificationSystem::UnbindOnAdd(), and NotificationSystem::UnbindOnRemove().
Member Function Documentation
AddNotification()
void NotificationUI::AddNotification (NotificationRuntimeData data) inline private
Definition at line 36 of file notificationui.c.
    {
        Widget notification         = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notification_element.layout", m_NotificationContent);
        ImageWidget icon            = ImageWidget.Cast( notification.FindAnyWidget( "Image" ) );
        RichTextWidget title        = RichTextWidget.Cast( notification.FindAnyWidget( "Title" ) );
        if( data.GetIcon() != "" )
            icon.LoadImageFile( 0, data.GetIcon() );
        title.SetText( data.GetTitleText() );
        if( data.GetDetailText() != "" )
        {
            Widget bottom_spacer    = notification.FindAnyWidget( "BottomSpacer" );
            RichTextWidget detail   = RichTextWidget.Cast( notification.FindAnyWidget( "Detail" ) );
            bottom_spacer.Show(true);
            detail.SetText( data.GetDetailText() );
            detail.Update();
            bottom_spacer.Update();
            notification.Update();
        }
        m_Notifications.Insert( data, notification );
        UpdateTargetHeight();
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_NotificationContent, m_Notifications, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
AddVoiceNotification()
void NotificationUI::AddVoiceNotification (string player, string name) inline private
Definition at line 73 of file notificationui.c.
    {
        if (!m_VoiceNotifications.Contains(player))
        {
            Widget notification;
            if (!m_WidgetTimers.Contains(player))
            {
                notification = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/notifications/notification_voice_element.layout", m_VoiceContent);
            }
            else
            {
                notification = m_WidgetTimers.Get(player);
                m_WidgetTimers.Remove(player);
                notification.SetAlpha( 120 / 255 );
                Widget w_c = notification.FindAnyWidget( "Name" );
                if( w_c )
                {
                    w_c.SetAlpha( 1 );
                }
            }
            RichTextWidget title = RichTextWidget.Cast(notification.FindAnyWidget("Name"));
            m_VoiceNotifications.Insert(player, notification);
            title.SetText(name);
            UpdateTargetHeight();
        }
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_VoiceContent, m_VoiceNotifications, m_WidgetTimers, name, and UpdateTargetHeight().
Referenced by AddVoiceNotification().
ClearVoiceNotifications()
void NotificationUI::ClearVoiceNotifications () inline private
Definition at line 112 of file notificationui.c.
    {
        for( int i = 0; i < m_VoiceNotifications.Count(); i++ )
        {
            Widget w = m_VoiceNotifications.GetElement( i );
            delete w;
        }
        m_VoiceNotifications.Clear();
        UpdateTargetHeight();
    }
References m_VoiceNotifications, and UpdateTargetHeight().
Referenced by OnEvent().
RemoveNotification()
void NotificationUI::RemoveNotification (NotificationRuntimeData data) inline private
Definition at line 62 of file notificationui.c.
    {
        if( m_Notifications.Contains( data ) )
        {
            Widget notification = m_Notifications.Get( data );
            m_WidgetTimers.Insert( m_WidgetTimers.Count().ToString() + data.GetTime().ToString(), notification );
            m_Notifications.Remove( data );
            UpdateTargetHeight();
        }
    }
References m_Notifications, m_WidgetTimers, and UpdateTargetHeight().
Referenced by NotificationUI(), and ~NotificationUI().
RemoveVoiceNotification()
void NotificationUI::RemoveVoiceNotification (string player) inline private
Definition at line 101 of file notificationui.c.
    {
        if( m_VoiceNotifications.Contains( player ) )
        {
            Widget notification = m_VoiceNotifications.Get( player );
            m_WidgetTimers.Insert( player, notification );
            m_VoiceNotifications.Remove( player );
            UpdateTargetHeight();
        }
    }
References m_VoiceNotifications, m_WidgetTimers, and UpdateTargetHeight().
Referenced by RemoveVoiceNotification().
Update()
void NotificationUI::Update (float timeslice) inline private
Definition at line 135 of file notificationui.c.
    {
        float x;
        m_Spacer.GetScreenSize( x, m_TargetHeight );
        bool is_near = ( m_CurrentHeight + 0.01 < m_TargetHeight || m_CurrentHeight - 0.01 > m_TargetHeight );
        if( is_near )
        {
            m_CurrentHeight = Math.SmoothCD(m_CurrentHeight, m_TargetHeight, m_VelArr, 0.2, 10000, timeslice);
            m_Root.SetSize( m_Width, m_CurrentHeight );
        }
        else if( m_TargetHeight != m_CurrentHeight )
        {
            m_CurrentHeight = m_TargetHeight;
            m_Root.SetSize( m_Width, m_CurrentHeight );
            m_VelArr[0] = 0;
        }
        for( int i = 0; i < m_WidgetTimers.Count(); )
        {
            Widget w        = m_WidgetTimers.GetElement( i );
            float new_alpha = Math.Clamp( w.GetAlpha() - timeslice / NOTIFICATION_FADE_TIME, 0, 1 );
            if( new_alpha > 0 )
            {
                w.SetAlpha( new_alpha );
                Widget w_c = w.FindAnyWidget( "TopSpacer" );
                Widget w_c2 = w.FindAnyWidget( "BottomSpacer" );
                Widget w_c3 = w.FindAnyWidget( "Title" );
                Widget w_c4 = w.FindAnyWidget( "Detail" );
                Widget w_c5 = w.FindAnyWidget( "Name" );
                if( w_c && w_c2 )
                {
                    float new_alpha_cont    = Math.Clamp( w_c.GetAlpha() - timeslice / NOTIFICATION_FADE_TIME, 0, 1 );
                    w_c.SetAlpha( new_alpha_cont );
                    w_c2.SetAlpha( new_alpha_cont );
                    w_c3.SetAlpha( new_alpha_cont );
                    w_c4.SetAlpha( new_alpha_cont );
                }
                if( w_c5 )
                {
                    float new_alpha_voice   = Math.Clamp( w_c5.GetAlpha() - timeslice / NOTIFICATION_FADE_TIME, 0, 1 );
                    w_c5.SetAlpha(new_alpha_voice);
                }
                i++;
            }
            else
            {
                delete w;
                m_WidgetTimers.RemoveElement( i );
                UpdateTargetHeight();
            }
        }
    }
References Math::Clamp(), m_CurrentHeight, m_Root, m_Spacer, m_TargetHeight, m_VelArr, m_WidgetTimers, m_Width, NOTIFICATION_FADE_TIME, Math::SmoothCD(), UpdateTargetHeight(), and x.
Referenced by OnUpdate().
UpdateTargetHeight()
void NotificationUI::UpdateTargetHeight () inline private
Definition at line 123 of file notificationui.c.
    {
        m_VoiceContent.Update();
        m_NotificationContent.Update();
        m_Spacer.Update();
        float x;
        m_Spacer.GetScreenSize( x, m_TargetHeight );
        m_Root.GetScreenSize( m_Width, m_CurrentHeight );
    }
References m_CurrentHeight, m_NotificationContent, m_Root, m_Spacer, m_TargetHeight, m_VoiceContent, m_Width, and x.
Referenced by AddNotification(), AddVoiceNotification(), ClearVoiceNotifications(), RemoveNotification(), RemoveVoiceNotification(), and Update().
Member Data Documentation
m_CurrentHeight
protected float NotificationUI::m_CurrentHeight private
Definition at line 12 of file notificationui.c.
Referenced by Update(), and UpdateTargetHeight().
m_NotificationContent
protected ref Widget NotificationUI::m_NotificationContent private
Definition at line 6 of file notificationui.c.
Referenced by AddNotification(), NotificationUI(), and UpdateTargetHeight().
m_Notifications
protected ref map<NotificationRuntimeData, Widget> NotificationUI::m_Notifications private
Definition at line 8 of file notificationui.c.
Referenced by AddNotification(), NotificationUI(), and RemoveNotification().
m_Root
protected ref Widget NotificationUI::m_Root private
Definition at line 3 of file notificationui.c.
Referenced by NotificationUI(), Update(), and UpdateTargetHeight().
m_Spacer
protected ref Widget NotificationUI::m_Spacer private
Definition at line 4 of file notificationui.c.
Referenced by NotificationUI(), Update(), and UpdateTargetHeight().
m_TargetHeight
protected float NotificationUI::m_TargetHeight private
Definition at line 13 of file notificationui.c.
Referenced by Update(), and UpdateTargetHeight().
m_VelArr
float NotificationUI::m_VelArr[1] static private
Definition at line 134 of file notificationui.c.
Referenced by Update().
m_VoiceContent
protected ref Widget NotificationUI::m_VoiceContent private
Definition at line 5 of file notificationui.c.
Referenced by AddVoiceNotification(), NotificationUI(), and UpdateTargetHeight().
m_VoiceNotifications
protected ref map<string, Widget> NotificationUI::m_VoiceNotifications private
Definition at line 9 of file notificationui.c.
Referenced by AddVoiceNotification(), ClearVoiceNotifications(), NotificationUI(), and RemoveVoiceNotification().
m_WidgetTimers
protected ref map<string, Widget> NotificationUI::m_WidgetTimers private
Definition at line 14 of file notificationui.c.
Referenced by AddVoiceNotification(), NotificationUI(), RemoveNotification(), RemoveVoiceNotification(), and Update().
m_Width
protected float NotificationUI::m_Width private
Definition at line 11 of file notificationui.c.
Referenced by Update(), and UpdateTargetHeight().