DayzKode: CarRearLightBase Class Reference
CarRearLightBase Class Reference
Private Member Functions
void CivilianSedanRearLight ()
void Hatchback_02RearLight ()
void Offroad_02RearLight ()
void OffroadHatchbackRearLight ()
void Sedan_02RearLight ()
void Truck_01RearLight ()
Detailed Description
Definition at line 1 of file civiliansedanrearlight.c.
Member Function Documentation
CivilianSedanRearLight()
void CarRearLightBase::CivilianSedanRearLight () inline private
Definition at line 3 of file civiliansedanrearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 1;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 270;
        m_SegregatedBrakeColorRGB = Vector(1, 0.6, 0.05);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 13;
        m_SegregatedAngle = 180;
        m_SegregatedColorRGB = Vector(1.0, 1.0, 0.8);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 2.5;
        m_AggregatedRadius = 15;
        m_AggregatedAngle = 180;
        m_AggregatedColorRGB = Vector(1.0, 0.8, 0.6);
        FadeIn(0.1);
        SetFadeOutTime(0.1);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().
Hatchback_02RearLight()
void CarRearLightBase::Hatchback_02RearLight () inline private
Definition at line 3 of file hatchback_02rearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 1;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 270;
        m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 13;
        m_SegregatedAngle = 180;
        m_SegregatedColorRGB = Vector(1.0, 1.0, 1.0);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 2.5;
        m_AggregatedRadius = 15;
        m_AggregatedAngle = 180;
        m_AggregatedColorRGB = Vector(1.0, 0.5, 0.5);
        FadeIn(0.1);
        SetFadeOutTime(0.1);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().
Offroad_02RearLight()
void CarRearLightBase::Offroad_02RearLight () inline private
Definition at line 3 of file offroad_02rearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 6;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 220;
        m_SegregatedBrakeColorRGB = Vector(0.95, 0.15, 0.13);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 15;
        m_SegregatedAngle = 160;
        m_SegregatedColorRGB = Vector(0.64, 0.60, 0.62);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 7;
        m_AggregatedRadius = 18;
        m_AggregatedAngle = 170;
        m_AggregatedColorRGB = Vector(1.0, 0.4, 0.5);
        FadeIn(0.1);
        SetFadeOutTime(0.05);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().
OffroadHatchbackRearLight()
void CarRearLightBase::OffroadHatchbackRearLight () inline private
Definition at line 3 of file offroadhatchbackrearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 1;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 180;
        m_SegregatedBrakeColorRGB = Vector(1, 0.05, 0.05);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 13;
        m_SegregatedAngle = 180;
        m_SegregatedColorRGB = Vector(1.0, 1.0, 1.0);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 2.5;
        m_AggregatedRadius = 15;
        m_AggregatedAngle = 180;
        m_AggregatedColorRGB = Vector(1.0, 0.5, 0.5);
        FadeIn(0.1);
        SetFadeOutTime(0.1);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().
Sedan_02RearLight()
void CarRearLightBase::Sedan_02RearLight () inline private
Definition at line 3 of file sedan_02rearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 5;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 160;
        m_SegregatedBrakeColorRGB = Vector(0.95, 0.16, 0.05);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 10;
        m_SegregatedAngle = 120;
        m_SegregatedColorRGB = Vector(0.80, 0.85, 0.9);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 5;
        m_AggregatedRadius = 10;
        m_AggregatedAngle = 160;
        m_AggregatedColorRGB = Vector(0.9, 0.4, 0.5);
        FadeIn(0.1);
        SetFadeOutTime(0.05);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().
Truck_01RearLight()
void CarRearLightBase::Truck_01RearLight () inline private
Definition at line 3 of file truck_01rearlight.c.
    {
        // Brake light only
        m_SegregatedBrakeBrightness = 5;
        m_SegregatedBrakeRadius = 6;
        m_SegregatedBrakeAngle = 160;
        m_SegregatedBrakeColorRGB = Vector(0.75, 0.16, 0.05);
        // Reverse light only
        m_SegregatedBrightness = 2;
        m_SegregatedRadius = 10;
        m_SegregatedAngle = 120;
        m_SegregatedColorRGB = Vector(0.80, 0.85, 0.9);
        // Brake & Revese lights combined
        m_AggregatedBrightness = 5;
        m_AggregatedRadius = 10;
        m_AggregatedAngle = 160;
        m_AggregatedColorRGB = Vector(0.85, 0.35, 0.45);
        FadeIn(0.1);
        SetFadeOutTime(0.05);
        SetVisibleDuringDaylight(false);
        SetCastShadow(false);
        SetFlareVisible(false);
        SegregateLight();
    }
References Vector().