DayzKode: TrapSpawnBase Class Reference
TrapSpawnBase Class Reference
Private Member Functions
override void AlignCatch (ItemBase obj, string catch_name)
override bool CanBePlaced (Man player, vector position)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override string GetDeploySoundset ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetLoopDeploySoundset ()
override bool IsDeployable ()
override bool IsDeployable ()
override bool IsPlaceableAtPosition (vector position)
override bool IsPlaceableAtPosition (vector position)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnVariablesSynchronized ()
override void OnVariablesSynchronized ()
override void OnVariablesSynchronized ()
override void SetActions ()
override void SetupTrap ()
override void SpawnCatch ()
override void SpawnCatch ()
override void SpawnCatch ()
void Trap_FishNet ()
void Trap_RabbitSnare ()
void Trap_SmallFish ()
Detailed Description
Definition at line 1 of file trap_fishnet.c.
Member Function Documentation
AlignCatch()
override void TrapSpawnBase::AlignCatch (ItemBase obj, string catch_name) inline private
Definition at line 191 of file trap_rabbitsnare.c.
    {
        if ( catch_name == "Animal_LepusEuropaeus" )
        {
            obj.SetOrientation( GetOrientation() );
            vector forward_vec = GetDirection();
            vector side_vec = forward_vec.Perpend(  ) * -0.22;
            forward_vec = forward_vec * -0.3;
            vector chatch_pos = obj.GetPosition() + forward_vec + side_vec;
            obj.SetPosition( chatch_pos );
        }
    }
References GetDirection(), GetOrientation(), and vector::Perpend().
CanBePlaced()
override bool TrapSpawnBase::CanBePlaced (Man player, vector position) inline private
Definition at line 31 of file trap_rabbitsnare.c.
    {
        if (m_IsBeingPlaced)
            return true;
        int liquidType;
        string surfaceType;
        g_Game.SurfaceUnderObject(PlayerBase.Cast(player).GetHologramLocal().GetProjectionEntity(), surfaceType, liquidType);
        return g_Game.IsSurfaceDigable(surfaceType);
    }
References g_Game, and m_IsBeingPlaced.
CanReceiveAttachment() [1/2]
override bool TrapSpawnBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 100 of file trap_fishnet.c.
    {
        if ( !attachment.IsInherited( Worm ) )
            return false;
        return super.CanReceiveAttachment( attachment, slotId );
    }
CanReceiveAttachment() [2/2]
override bool TrapSpawnBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 96 of file trap_smallfish.c.
    {
        if ( !attachment.IsInherited( Worm ) )
            return false;
        return super.CanReceiveAttachment( attachment, slotId );
    }
GetDeploySoundset() [1/2]
override string TrapSpawnBase::GetDeploySoundset () inline private
Definition at line 174 of file trap_fishnet.c.
    {
        return "placeFishNetTrap_SoundSet";
    }
GetDeploySoundset() [2/2]
override string TrapSpawnBase::GetDeploySoundset () inline private
Definition at line 166 of file trap_rabbitsnare.c.
    {
        return "placeRabbitSnareTrap_SoundSet";
    }
GetLoopDeploySoundset() [1/2]
override string TrapSpawnBase::GetLoopDeploySoundset () inline private
Definition at line 179 of file trap_fishnet.c.
    {
        return "fishnet_deploy_SoundSet";
    }
Referenced by ItemBase::PlayDeployLoopSound().
GetLoopDeploySoundset() [2/2]
override string TrapSpawnBase::GetLoopDeploySoundset () inline private
Definition at line 171 of file trap_rabbitsnare.c.
    {
        return "rabbitsnare_deploy_SoundSet";
    }
IsDeployable() [1/2]
override bool TrapSpawnBase::IsDeployable () inline private
Definition at line 169 of file trap_fishnet.c.
    {
        return true;
    }
IsDeployable() [2/2]
override bool TrapSpawnBase::IsDeployable () inline private
Definition at line 161 of file trap_rabbitsnare.c.
    {
        return true;
    }
IsPlaceableAtPosition() [1/2]
override bool TrapSpawnBase::IsPlaceableAtPosition (vector position) inline private
Definition at line 95 of file trap_fishnet.c.
    {
        return IsSurfaceWater( position );
    }
Referenced by ActionActivateTrap::ActionCondition(), ItemBase::CanBePlaced(), Hologram::EvaluateCollision(), and ItemBase::IsPlaceable().
IsPlaceableAtPosition() [2/2]
override bool TrapSpawnBase::IsPlaceableAtPosition (vector position) inline private
Definition at line 91 of file trap_smallfish.c.
    {
        return IsSurfaceWater( position );
    }
OnPlacementComplete() [1/2]
override void TrapSpawnBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 162 of file trap_fishnet.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        SetIsPlaceSound( true );
    }
References SetIsPlaceSound().
Referenced by ActionActivateTrap::OnFinishProgressServer().
OnPlacementComplete() [2/2]
override void TrapSpawnBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 154 of file trap_rabbitsnare.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        SetIsPlaceSound( true );
    }
References SetIsPlaceSound().
OnVariablesSynchronized() [1/3]
override void TrapSpawnBase::OnVariablesSynchronized () inline private
Definition at line 29 of file trap_fishnet.c.
    {
        super.OnVariablesSynchronized();
        if ( IsPlaceSound() )
        {
            PlayPlaceSound();
        }
    }
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [2/3]
override void TrapSpawnBase::OnVariablesSynchronized () inline private
Definition at line 43 of file trap_rabbitsnare.c.
    {
        super.OnVariablesSynchronized();
        if (IsPlaceSound())
        {
            PlayPlaceSound();
        }
    }
References IsPlaceSound(), and PlayPlaceSound().
OnVariablesSynchronized() [3/3]
override void TrapSpawnBase::OnVariablesSynchronized () inline private
Definition at line 28 of file trap_smallfish.c.
    {
        super.OnVariablesSynchronized();
        if ( IsPlaceSound() )
        {
            PlayPlaceSound();
        }
    }
References IsPlaceSound(), and PlayPlaceSound().
SetActions()
override void TrapSpawnBase::SetActions () inline private
Definition at line 176 of file trap_rabbitsnare.c.
    {
        super.SetActions();
        // We remove the hunting trap deploy action in order to all advanced placement
        RemoveAction(ActionDeployHuntingTrap);
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), AddAction(), and RemoveAction().
SetupTrap()
override void TrapSpawnBase::SetupTrap () inline private
Definition at line 53 of file trap_rabbitsnare.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( GetHierarchyRootPlayer().CanDropEntity( this ) )
            {
                if ( IsRuined() )
                {
                    PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
                }
                else
                {
                    PlayerBase owner_player = PlayerBase.Cast( GetHierarchyRootPlayer() );
                    //GetDirection
                    vector trapPos = owner_player.GetDirection();
                    trapPos[1] = 0;
                    SetPosition( owner_player.GetPosition() + trapPos );
                    SetActive();
                    SetOrientation( owner_player.GetOrientation() );
                }
            }
        }
    }
References GetGame(), IsRuined(), SetActive(), SetOrientation(), and SetPosition().
SpawnCatch() [1/3]
override void TrapSpawnBase::SpawnCatch () inline private
Definition at line 43 of file trap_fishnet.c.
    {
        super.SpawnCatch();
        if ( m_CanCatch )
        {
            multiMap<string, float> catches;
            vector pos = GetPosition();
            ItemBase catch;
            // Select catch type depending on water type ( FRESH VS SALT )
            if ( GetGame().SurfaceIsSea( pos[0], pos[2] ) )
            {
                catches = m_CatchesSea;
            }
            else if ( GetGame().SurfaceIsPond( pos[0], pos[2] ) )
            {
                catches = m_CatchesPond;
            }
            if ( catches && catches.Count() > 0 )
            {
                // select random object from catches
                int count = catches.Count() - 1;
                int randomCatchIndex = Math.RandomInt( 0, count );
                if ( Math.RandomFloat(0, 100) < m_FinalCatchProb )
                {
                    catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex(randomCatchIndex), m_PreyPos, ECE_NONE ) );
                    // Set the quantity of caught prey
                    if ( catch )
                        CatchSetQuant( catch );
                }
                // We change the trap state and visuals
                SetUsed();
                // We remove the bait from this trap
                if ( m_Bait )
                    m_Bait.Delete();
            }
            // Deal damage to trap
            AddDefect();
        }
    }
References AddDefect(), ECE_NONE, GetGame(), GetPosition, Math::RandomFloat(), and Math::RandomInt().
SpawnCatch() [2/3]
override void TrapSpawnBase::SpawnCatch () inline private
Definition at line 80 of file trap_rabbitsnare.c.
    {
        super.SpawnCatch();
        if ( m_CanCatch )
        {
            multiMap<string, float> catches;
            // We read the relevant catch map
            ItemBase catch;
            catches = m_CatchesGroundAnimal;
            // The catch map contains data
            if ( catches && catches.Count() > 0 )
            {
                // select random object from catches
                int count = catches.Count() - 1;
                int randomCatchIndex = Math.RandomInt( 0, count );
                if ( Math.RandomFloat(0, 100) < m_FinalCatchProb )
                {
                    if ( m_Bait )
                    {
                        if ( m_Bait.IsInherited( Worm ) )
{
                            // We can only catch chicken, so exclude the rabbit
                            randomCatchIndex = Math.RandomInt( 0, count - 1 );
                            catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex( randomCatchIndex ), m_PreyPos, ECE_PLACE_ON_SURFACE ) );
                        }
                        else
{
                            // Get the last index, which is the rabbit
                            randomCatchIndex = count;
                            catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex( randomCatchIndex ), m_PreyPos, ECE_PLACE_ON_SURFACE ) );
                        }
                    }
                    else
                    {
                        // No bait, 50 / 50 rabbit
                        randomCatchIndex = Math.RandomIntInclusive( 0, 1 );
                        if ( randomCatchIndex == 0 )
{
                            randomCatchIndex = Math.RandomInt( 0, count - 1 );
                            catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex( randomCatchIndex ), m_PreyPos, ECE_PLACE_ON_SURFACE ) );
                        }
                        else
{
                            randomCatchIndex = count;
                            catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex( randomCatchIndex ), m_PreyPos, ECE_PLACE_ON_SURFACE ) );
                        }
                    }
                    // We set quantity of prey
                    if ( catch )
                        CatchSetQuant( catch );
                }
                // We update the state
                SetUsed();
                // We remove the bait from this trap
                if ( m_Bait )
                    m_Bait.Delete();
            }
            // We damage the trap
            AddDefect();
        }
    }
References AddDefect(), ECE_PLACE_ON_SURFACE, GetGame(), Math::RandomFloat(), Math::RandomInt(), and Math::RandomIntInclusive().
SpawnCatch() [3/3]
override void TrapSpawnBase::SpawnCatch () inline private
Definition at line 38 of file trap_smallfish.c.
    {
        super.SpawnCatch();
        if ( m_CanCatch )
        {
            // We get the prey position for spawning
            multiMap<string, float> catches;
            vector pos = GetPosition();
            ItemBase catch;
            // Select catch type depending on water type ( FRESH VS SALT )
            if ( GetGame().SurfaceIsSea( pos[0], pos[2] ) )
            {
                catches = m_CatchesSea;
            }
            else if ( GetGame().SurfaceIsPond( pos[0], pos[2] ) )
            {
                catches = m_CatchesPond;
            }
            if ( catches && catches.Count() > 0 )
            {
                // select random object from catches
                int count = catches.Count() - 1;
                int randomCatchIndex = Math.RandomInt( 0, count );
                if ( Math.RandomFloat(0, 100) < m_FinalCatchProb )
                {
                    catch = ItemBase.Cast( GetGame().CreateObjectEx( catches.GetKeyByIndex(randomCatchIndex), m_PreyPos, ECE_NONE ) );
                    // Set the quantity of caught prey
                    if ( catch )
                        CatchSetQuant( catch );
                }
                // We change the trap state and visuals
                SetUsed();
                // We remove the bait from this trap
                if ( m_Bait )
                    m_Bait.Delete();
            }
            // Deal damage to trap
            AddDefect();
        }
    }
References AddDefect(), ECE_NONE, GetGame(), GetPosition, Math::RandomFloat(), and Math::RandomInt().
Trap_FishNet()
void TrapSpawnBase::Trap_FishNet () inline private
Definition at line 3 of file trap_fishnet.c.
    {
        m_DefectRate = 15;          //Added damage after trap activation
        m_InitWaitTime = Math.RandomFloat(900,1500);
        m_UpdateWaitTime = 30;
        m_IsFoldable = true;
        m_MinimalDistanceFromPlayersToCatch     = 15;
        m_BaitCatchProb                         = 85;
        m_NoBaitCatchProb                       = 15;
        m_AnimationPhaseSet                     = "inventory";
        m_AnimationPhaseTriggered               = "placing";
        m_AnimationPhaseUsed                    = "triggered";
        m_WaterSurfaceForSetup = true;
        m_CatchesPond = new multiMap<string, float>;
        m_CatchesPond.Insert("Carp",1);
        m_CatchesSea = new multiMap<string, float>;
        m_CatchesSea.Insert("Mackerel",1);
    }
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomFloat().
Trap_RabbitSnare()
void TrapSpawnBase::Trap_RabbitSnare () inline private
Definition at line 3 of file trap_rabbitsnare.c.
    {
        m_DefectRate = 15;          //Added damage after trap activation
        m_InitWaitTime                          = Math.RandomInt(900, 1500);
        m_UpdateWaitTime                        = 30;
        m_IsFoldable                            = true;
        m_IsUsable                              = true;
        m_MinimalDistanceFromPlayersToCatch     = 30;
        m_BaitCatchProb                         = 85;
        m_NoBaitCatchProb                       = 15;
        m_AnimationPhaseSet                     = "inventory";
        m_AnimationPhaseTriggered               = "placing";
        m_AnimationPhaseUsed                    = "triggered";
        m_WaterSurfaceForSetup = false;
        m_CatchesGroundAnimal = new multiMap<string, float>;
        m_CatchesGroundAnimal.Insert("DeadRooster", 1);
        m_CatchesGroundAnimal.Insert("DeadChicken_White", 1);
        m_CatchesGroundAnimal.Insert("DeadChicken_Spotted", 1);
        m_CatchesGroundAnimal.Insert("DeadChicken_Brown", 1);
        // ALWAYS keep rabbit last as that is how it gets the rabbit in case of rabbit specific bait
        m_CatchesGroundAnimal.Insert("DeadRabbit", 1);
    }
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomInt().
Trap_SmallFish()
void TrapSpawnBase::Trap_SmallFish () inline private
Definition at line 3 of file trap_smallfish.c.
    {
        m_DefectRate = 15;          //Added damage after trap activation
        m_InitWaitTime = Math.RandomFloat(900,1500);
        m_UpdateWaitTime = 30;
        m_AnimationPhaseSet                     = "inventory";
        m_AnimationPhaseTriggered               = "placing";
        m_AnimationPhaseUsed                    = "triggered";
        m_MinimalDistanceFromPlayersToCatch     = 15;
        m_BaitCatchProb                         = 85;
        m_NoBaitCatchProb                       = 15;
        m_WaterSurfaceForSetup = true;
        m_CatchesPond = new multiMap<string, float>;
        m_CatchesPond.Insert("Bitterlings", 1);
        m_CatchesSea = new multiMap<string, float>;
        m_CatchesSea.Insert("Sardines",1);
    }
References m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DefectRate, m_InitWaitTime, and Math::RandomFloat().