DayzKode: HandsHeader Class Reference
HandsHeader Class Reference
Private Member Functions
void HandsHeader (LayoutHolder parent, string function_name)
override void SetLayoutName ()
void ShowCollapseButtons (bool show, bool force=false)
override void UpdateInterval ()
Private Attributes
protected bool m_ForceHideCollapseButtons
protected Widget m_ItemHeader
Detailed Description
Definition at line 1 of file handsheader.c.
Constructor & Destructor Documentation
HandsHeader()
void HandsHeader::HandsHeader (LayoutHolder parent, string function_name) inline private
Definition at line 6 of file handsheader.c.
    {
        m_DefaultFontSize   = 24;
        m_ItemHeader        = m_MainWidget.FindAnyWidget( "hands_item_header" );
        m_MainWidget        = GetMainWidget().FindAnyWidget( "height_wrapper" );
        m_DefaultColor      = GetMainWidget().GetColor();
        #ifdef PLATFORM_CONSOLE
        ShowCollapseButtons( false, true );
        #endif
    }
References Header::m_DefaultColor, Header::m_DefaultFontSize, m_ItemHeader, and ShowCollapseButtons().
Member Function Documentation
SetLayoutName()
override void HandsHeader::SetLayoutName () inline private
Definition at line 18 of file handsheader.c.
    {
        m_LayoutName = WidgetLayoutName.HandsHeader;
    }
References WidgetLayoutName::HandsHeader.
ShowCollapseButtons()
void HandsHeader::ShowCollapseButtons (bool show, bool force = false) inline private
Definition at line 45 of file handsheader.c.
    {
        m_ForceHideCollapseButtons = force;
        #ifdef PLATFORM_CONSOLE
        m_CollapseButton.Show( false );
        #else
        m_CollapseButton.Show( show );
        #endif
    }
References Header::m_CollapseButton, and m_ForceHideCollapseButtons.
Referenced by HandsHeader(), HandsContainer::RemoveItem(), HandsContainer::ShowAtt(), and UpdateInterval().
UpdateInterval()
override void HandsHeader::UpdateInterval () inline private
Definition at line 23 of file handsheader.c.
    {
        PlayerBase p = PlayerBase.Cast( GetGame().GetPlayer() );
        if (!p)
            return;
        EntityAI item = p.GetHumanInventory().GetEntityInHands();
        if ( !m_ForceHideCollapseButtons )
        {
            if ( item && !item.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) && item.CanDisplayCargo() )
            {
                ShowCollapseButtons( true );
            }
            else
            {
                ShowCollapseButtons( false );
            }
        }
        m_ItemHeader.Show( item != null );
    }
References GetGame(), GetPlayer(), m_ForceHideCollapseButtons, m_ItemHeader, and ShowCollapseButtons().
Referenced by HandsContainer::UpdateInterval().
Member Data Documentation
m_ForceHideCollapseButtons
protected bool HandsHeader::m_ForceHideCollapseButtons private
Definition at line 3 of file handsheader.c.
Referenced by ShowCollapseButtons(), and UpdateInterval().
m_ItemHeader
protected Widget HandsHeader::m_ItemHeader private
Definition at line 4 of file handsheader.c.
Referenced by HandsHeader(), and UpdateInterval().