DayzKode: ActionVariantManager Class Reference
ActionVariantManager Class Reference
Private Member Functions
void ActionVariantManager (typename type)
void Clear ()
int GetActions (out array< ref ActionBase > variants_action)
int GetActionsCount ()
ScriptInvoker GetOnUpdateInvoker ()
void SetActionVariantCount (int count)
void UpdateVariants (Object item, Object target, int componet_index)
Private Attributes
protected ref ScriptInvoker e_OnUpdate
protected m_type
protected ref array< ref ActionBase > m_VariantActions
Detailed Description
Definition at line 1 of file actionvariantsmanager.c.
Constructor & Destructor Documentation
ActionVariantManager()
void ActionVariantManager::ActionVariantManager (typename type) inline private
Definition at line 7 of file actionvariantsmanager.c.
    {
        m_type = type;
        m_VariantActions = new array<ref ActionBase>;
        e_OnUpdate = new ScriptInvoker();
    }
References e_OnUpdate, m_type, and m_VariantActions.
Member Function Documentation
Clear()
void ActionVariantManager::Clear () inline private
Definition at line 19 of file actionvariantsmanager.c.
    {
        m_VariantActions.Clear();
    }
References m_VariantActions.
Referenced by CraftingManager::OnUpdate(), ConstructionActionData::OnUpdateActions(), and ConstructionActionData::OnUpdateActionsNoTool().
GetActions()
int ActionVariantManager::GetActions (out array< ref ActionBase > variants_action) inline private
Definition at line 40 of file actionvariantsmanager.c.
    {
        variants_action = m_VariantActions;
        return m_VariantActions.Count();
    }
References m_VariantActions.
Referenced by GetVariants().
GetActionsCount()
int ActionVariantManager::GetActionsCount () inline private
Definition at line 46 of file actionvariantsmanager.c.
    {
        return m_VariantActions.Count();
    }
References m_VariantActions.
Referenced by GetVariantsCount().
GetOnUpdateInvoker()
ScriptInvoker ActionVariantManager::GetOnUpdateInvoker () inline private
Definition at line 14 of file actionvariantsmanager.c.
    {
        return e_OnUpdate;
    }
References e_OnUpdate.
Referenced by ConstructionActionData::ConstructionActionData(), and CraftingManager::CraftingManager().
SetActionVariantCount()
void ActionVariantManager::SetActionVariantCount (int count) inline private
Definition at line 24 of file actionvariantsmanager.c.
    {
        if ( count < m_VariantActions.Count() )
        {
            m_VariantActions.Clear();
        }
        for (int i = m_VariantActions.Count(); i < count; i++ )
        {
            ActionBase action = ActionManagerBase.GetActionVariant( m_type );
            action.SetVariantID(i);
            m_VariantActions.Insert(action);
        }
    }
References ActionBase(), ActionManagerBase::GetActionVariant(), m_type, and m_VariantActions.
Referenced by CraftingManager::OnUpdate(), ConstructionActionData::OnUpdateActions(), and ConstructionActionData::OnUpdateActionsNoTool().
UpdateVariants()
void ActionVariantManager::UpdateVariants (Object item, Object target, int componet_index) inline private
Definition at line 51 of file actionvariantsmanager.c.
    {
        e_OnUpdate.Invoke( item, target, componet_index );
    }
References e_OnUpdate, and ScriptInvoker::Invoke().
Referenced by UpdateVariants().
Member Data Documentation
e_OnUpdate
protected ref ScriptInvoker ActionVariantManager::e_OnUpdate private
Definition at line 5 of file actionvariantsmanager.c.
Referenced by ActionVariantManager(), GetOnUpdateInvoker(), and UpdateVariants().
m_type
protected ActionVariantManager::m_type private
Definition at line 4 of file actionvariantsmanager.c.
Referenced by ActionVariantManager(), and SetActionVariantCount().
m_VariantActions
protected ref array<ref ActionBase> ActionVariantManager::m_VariantActions private
Definition at line 3 of file actionvariantsmanager.c.
Referenced by ActionVariantManager(), Clear(), GetActions(), GetActionsCount(), and SetActionVariantCount().