DayzKode: PluginConfigHandler Class Reference
PluginConfigHandler Class Reference
Private Member Functions
string DecodeInitScript (string script)
string EncodeInitScript (string script)
protected array< ref CfgParam > GetArray (string key)
int GetBatchSpawnQuantity ()
array< ref CfgParam > GetBatchSpawnRectangle ()
protected bool GetBool (string key)
bool GetCharacterAgentsVisible ()
bool GetCharacterDebugVisible ()
bool GetCharacterLevelsVisible ()
bool GetCharacterModifiersVisible ()
bool GetCharacterStatsVisible ()
bool GetCharacterStomachVisible ()
int GetConfigClassesFlag ()
array< ref CfgParam > GetDefaultBatchRectParams ()
string GetDefaultPreset ()
int GetEmoteFromSlot (string slot)
int GetEmoteSlot1 ()
int GetEmoteSlot10 ()
int GetEmoteSlot11 ()
int GetEmoteSlot2 ()
int GetEmoteSlot3 ()
int GetEmoteSlot4 ()
int GetEmoteSlot5 ()
int GetEmoteSlot6 ()
int GetEmoteSlot7 ()
int GetEmoteSlot8 ()
int GetEmoteSlot9 ()
override string GetFileName ()
override string GetFileName ()
override string GetFileName ()
override string GetFileName ()
protected float GetFloat (string key)
bool GetFreeCameraCrosshairVisible ()
protected int GetInt (string key)
protected int GetInt (string key)
int GetItemCategoryFlag ()
float GetItemHealth (string preset_name, int item_index)
protected CfgParam GetItemParam (string preset_name, int item_index, string param_name)
protected array< ref CfgParam > GetItemParams (string preset_name, int item_index)
int GetItemQuantity (string preset_name, int item_index)
string GetItemSearch ()
bool GetLogsEnabled ()
bool GetMergeType ()
protected CfgParamArray GetNewCfgParamArray (array< ref CfgParam > params)
protected CfgParamBool GetNewCfgParamBool (bool value)
protected CfgParamFloat GetNewCfgParamFloat (float value)
protected CfgParamInt GetNewCfgParamInt (int value)
protected CfgParamInt GetNewCfgParamInt (int value)
protected CfgParamString GetNewCfgParamString (string value)
string GetPathScenes ()
bool GetPresetItems (string preset_name, out TStringArray arr, string param_name="")
TStringArray GetPresets ()
bool GetSceneEditorDrawSelection ()
bool GetSceneEditorLoadPlayerPos ()
string GetSceneEditorName ()
int GetSceneEditorRotationAngle ()
TStringArray GetSceneList ()
bool GetShowItemPreview ()
string GetSoundsetFilter ()
float GetSpawnDistance ()
protected string GetString (string key)
protected void GetSubParametersInStringArray (string setting_name, string sub_param_name, out TStringArray arr)
int GetTabSelected ()
bool GetTempVisible ()
bool GetVersionVisible ()
bool ItemAddToPreset (string preset_name, string item_name)
bool ItemRemoveFromPreset (string preset_name, int item_index)
void LoadSceneObjects (SceneData scene)
void LoadScenePlayer (SceneData scene)
void LoadSceneSettings (SceneData scene)
void LoadSceneWeather (SceneData scene)
override void OnInit ()
override void OnInit ()
override void OnInit ()
void PluginConfigDebugProfile ()
void PluginConfigEmotesProfile ()
bool PresetAdd (string preset_name)
bool PresetRemove (string preset_name)
bool PresetRename (string old_preset_name, string new_preset_name)
protected void RemovePreset (string preset_name)
void SaveSceneObjects (SceneData scene)
void SaveScenePlayer (SceneData scene)
void SaveSceneSettings (SceneData scene)
void SaveSceneWeather (SceneData scene)
SceneData SceneDataLoad (string scene_name)
void SceneDataSave (SceneData scene)
void SceneDelete (string scene_name)
void SceneDuplicate (string scene_name)
void SceneRename (string scene_name, string scene_name_new)
protected CfgParamArray SetArray (string key, array< ref CfgParam > params)
void SetBatchSpawnQuantity (int value)
void SetBatchSpawnRectangle (int row, int column, float rowStep, float columnStep)
protected CfgParamBool SetBool (string key, bool value)
void SetCharacterAgentsVisible (bool is_visible)
void SetCharacterDebugVisible (bool is_visible)
void SetCharacterLevelsVisible (bool is_visible)
void SetCharacterModifiersVisible (bool is_visible)
void SetCharacterStatsVisible (bool is_visible)
void SetCharacterStomachVisible (bool is_visible)
void SetConfigClassesFlag (int flag)
void SetDefaultPreset (string value)
void SetEmoteSlot1 (int emoted_id)
void SetEmoteSlot10 (int emoted_id)
void SetEmoteSlot11 (int emoted_id)
void SetEmoteSlot2 (int emoted_id)
void SetEmoteSlot3 (int emoted_id)
void SetEmoteSlot4 (int emoted_id)
void SetEmoteSlot5 (int emoted_id)
void SetEmoteSlot6 (int emoted_id)
void SetEmoteSlot7 (int emoted_id)
void SetEmoteSlot8 (int emoted_id)
void SetEmoteSlot9 (int emoted_id)
protected CfgParamFloat SetFloat (string key, float value)
void SetFreeCameraCrosshairVisible (bool is_visible)
protected CfgParamInt SetInt (string key, int value)
protected CfgParamInt SetInt (string key, int value)
void SetItemCategoryFlag (int flag)
bool SetItemHealth (string preset_name, int item_index, float health)
bool SetItemQuantity (string preset_name, int item_index, int quantity)
void SetItemSearch (string value)
void SetLogsEnabled (bool value)
void SetMergeType (bool is_visible)
protected void SetPreset (string preset_name, int index=-1)
void SetSceneEditorDrawSelection (bool value)
void SetSceneEditorLoadPlayerPos (bool value)
void SetSceneEditorName (string value)
void SetSceneEditorRotationAngle (int value)
void SetShowItemPreview (bool show)
void SetSoundsetFilter (string content)
void SetSpawnDistance (float value)
protected CfgParamString SetString (string key, string value)
void SetTabSelected (int value)
void SetTempVisible (bool is_visible)
void SetVersionVisible (bool is_visible)
bool SwapItem (string preset_name, int item1_index, int item2_index)
Static Private Member Functions
static PluginConfigDebugProfile GetInstance ()
static PluginConfigEmotesProfile GetInstance ()
static PluginMissionConfig GetInstance ()
Private Attributes
protected const string BATCH_QUANT = "batch_spawn_quantity"
protected const string BATCH_RECT = "batch_spawn_rect"
protected const string CHAR_AGENTS_VIS = "console_character_agents_visible"
protected const string CHAR_DEBUG_VIS = "console_character_debug_visible"
protected const string CHAR_LEVELS_VIS = "console_character_levels_visible"
protected const string CHAR_MODIFIERS_VIS = "console_character_modifiers_visible"
protected const string CHAR_STATS_VIS = "console_character_stats_visible"
protected const string CHAR_STOMACH_VIS = "console_character_stomach_visible"
protected const string CONFIG_CLASSES_FLAG = "toggled_config_classes_flag"
protected const string FILE_NAME = "scene_editor.cfg"
protected string FILE_ROOT = "$saves:"
protected const string FILE_ROOT_SCENES = "scenes"
protected const string FREE_CAMERA_CROSSHAIR = "console_free_camera_crosshair_visible"
protected const string ITEM_CATEGORY_FLAG = "toggled_item_categories_flag"
protected const string ITEM_PREVIEW = "show_item_preview"
protected const string ITEM_SEARCH = "console_ItemSearch"
protected const string ITEM_TAB_SELECTED = "console_TabSelected"
protected const string LOGS_ENABLED = "logs_enabled"
TStringArray m_CfgTemplate
protected ref map< string, ref CfgParam > m_DefaultValues
protected string m_FileSceneName
protected ref TStringArray m_PresetList
protected const string MERGE_TYPE = "category_merge_type"
protected const string PARAM_DAY = "InitDay"
protected const string PARAM_FOG = "WeatherInitFog"
protected const string PARAM_HOUR = "InitHour"
protected const string PARAM_MINUTE = "InitMinute"
protected const string PARAM_MISSION = "Mission"
protected const string PARAM_MONTH = "InitMonth"
protected const string PARAM_OBJ_ATT = "Att"
protected const string PARAM_OBJ_COUNT = "SceneObjectsCount"
protected const string PARAM_OBJ_DMG = "damage"
protected const string PARAM_OBJ_HLT = "health"
protected const string PARAM_OBJ_ISCR = "init_script"
protected const string PARAM_OBJ_LNK = "Lnk"
protected const string PARAM_OBJ_NAME = "SceneObject"
protected const string PARAM_OBJ_POS = "position"
protected const string PARAM_OBJ_ROT = "rotation"
protected const string PARAM_OBJ_TYPE = "type"
protected const string PARAM_OVERCAST = "WeatherInitOvercast"
protected const string PARAM_PLAYER = "Player"
protected const string PARAM_RAIN = "WeatherInitRain"
protected const string PARAM_TIME = "InitTime"
protected const string PARAM_WIND_F = "WeatherInitWindForce"
protected const string PARAM_YEAR = "InitYear"
protected const string PRESET_DEFAULT = "console_preset_default"
protected const string PRESET_LIST = "console_presets"
protected const string SCENE_DRAW_SELECTION = "scene_editor_draw_selection"
protected const string SCENE_EDITOR_SCENE = "scene_load"
protected const string SCENE_LOAD_PLAYER_POS = "scene_editor_load_player_pos"
protected const string SCENE_ROTATION_ANGLE = "scene_editor_rotation_angle"
protected const string SOUNDFILTER = "soundset_editbox"
protected const string SPAWN_DISTANCE = "console_SpawnDistance"
protected const string SUB_PARAM_ITEM = "item"
protected const string SUB_PARAM_ITEM_HEALTH = "health"
protected const string SUB_PARAM_ITEM_NAME = "name"
protected const string SUB_PARAM_ITEM_QUANTITY = "quantity"
protected const string TEMP_VIS = "console_temperature_visible"
protected const string VERSION_VIS = "console_version_visible"
Detailed Description
Definition at line 1 of file pluginconfigdebugprofile.c.
Member Function Documentation
DecodeInitScript()
string PluginConfigHandler::DecodeInitScript (string script) inline private
Definition at line 143 of file pluginconfigscene.c.
    {
        script.Replace( "^", "\"" );
        script.Replace( "$", "\n" );
        return script;
    }
References string::Replace().
Referenced by LoadSceneObjects(), and LoadScenePlayer().
EncodeInitScript()
string PluginConfigHandler::EncodeInitScript (string script) inline private
Definition at line 133 of file pluginconfigscene.c.
    {
        script.Replace( "\"", "^" );
        script.Replace( "\n", "$" );
        return script;
    }
References string::Replace().
Referenced by SaveSceneObjects(), and SaveScenePlayer().
GetArray()
protected array< ref CfgParam > PluginConfigHandler::GetArray (string key) inline private
Definition at line 105 of file pluginconfigdebugprofile.c.
    {
        if ( ParamExist(key) )
        {
            CfgParamArray param = CfgParamArray.Cast( GetParamByName( key, CFG_TYPE_ARRAY ) );
            return param.GetValues();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamArray default_param = CfgParamArray.Cast( m_DefaultValues.Get( key ) );
                return SetArray( key, default_param.GetValues() ).GetValues();
            }
            else
            {
                return SetArray( key, new array<ref CfgParam> ).GetValues();
            }
        }
    }
References CFG_TYPE_ARRAY.
GetBatchSpawnQuantity()
int PluginConfigHandler::GetBatchSpawnQuantity () inline private
Definition at line 453 of file pluginconfigdebugprofile.c.
    {
        return GetInt( BATCH_QUANT );
    }
References GetInt().
GetBatchSpawnRectangle()
array< ref CfgParam > PluginConfigHandler::GetBatchSpawnRectangle () inline private
Definition at line 423 of file pluginconfigdebugprofile.c.
    {
        return GetArray( BATCH_RECT );
    }
GetBool()
protected bool PluginConfigHandler::GetBool (string key) inline private
Definition at line 137 of file pluginconfigdebugprofile.c.
    {
        if ( ParamExist(key) )
        {
            CfgParamBool param = CfgParamBool.Cast( GetParamByName( key, CFG_TYPE_BOOL ) );
            return param.GetValue();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamBool default_param = CfgParamBool.Cast( m_DefaultValues.Get( key ) );
                return SetBool( key, default_param.GetValue() ).GetValue();
            }
            else
            {
                return SetBool( key, false ).GetValue();
            }
        }
    }
References CFG_TYPE_BOOL.
GetCharacterAgentsVisible()
bool PluginConfigHandler::GetCharacterAgentsVisible () inline private
Definition at line 546 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_AGENTS_VIS );
    }
GetCharacterDebugVisible()
bool PluginConfigHandler::GetCharacterDebugVisible () inline private
Definition at line 559 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_DEBUG_VIS );
    }
GetCharacterLevelsVisible()
bool PluginConfigHandler::GetCharacterLevelsVisible () inline private
Definition at line 504 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_LEVELS_VIS );
    }
GetCharacterModifiersVisible()
bool PluginConfigHandler::GetCharacterModifiersVisible () inline private
Definition at line 533 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_MODIFIERS_VIS );
    }
GetCharacterStatsVisible()
bool PluginConfigHandler::GetCharacterStatsVisible () inline private
Definition at line 519 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_STATS_VIS );
    }
GetCharacterStomachVisible()
bool PluginConfigHandler::GetCharacterStomachVisible () inline private
Definition at line 572 of file pluginconfigdebugprofile.c.
    {
        return GetBool( CHAR_STOMACH_VIS );
    }
GetConfigClassesFlag()
int PluginConfigHandler::GetConfigClassesFlag () inline private
Definition at line 664 of file pluginconfigdebugprofile.c.
    {
        return GetInt( CONFIG_CLASSES_FLAG );
    }
References GetInt().
GetDefaultBatchRectParams()
array< ref CfgParam > PluginConfigHandler::GetDefaultBatchRectParams () inline private
Definition at line 310 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> params = new array<ref CfgParam>;
        CfgParamInt param1 = new CfgParamInt("");
        param1.SetValue(5);
        CfgParamInt param2 = new CfgParamInt("");
        param2.SetValue(5);
        CfgParamFloat param3 = new CfgParamFloat("");
        param3.SetValue(1.0);
        CfgParamFloat param4 = new CfgParamFloat("");
        param4.SetValue(1.0);
        params.Insert(param1);
        params.Insert(param2);
        params.Insert(param3);
        params.Insert(param4);
        return params;
    }
GetDefaultPreset()
string PluginConfigHandler::GetDefaultPreset () inline private
Definition at line 410 of file pluginconfigdebugprofile.c.
    {
        return GetString( PRESET_DEFAULT );
    }
GetEmoteFromSlot()
int PluginConfigHandler::GetEmoteFromSlot (string slot) inline private
Definition at line 224 of file pluginconfigemotesprofile.c.
    {
        return GetInt( slot );
    }
References GetInt().
GetEmoteSlot1()
int PluginConfigHandler::GetEmoteSlot1 () inline private
Definition at line 104 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_1.ToString() );
    }
References GetInt().
GetEmoteSlot10()
int PluginConfigHandler::GetEmoteSlot10 () inline private
Definition at line 194 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_10.ToString() );
    }
References GetInt().
GetEmoteSlot11()
int PluginConfigHandler::GetEmoteSlot11 () inline private
Definition at line 204 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_11.ToString() );
    }
References GetInt().
GetEmoteSlot2()
int PluginConfigHandler::GetEmoteSlot2 () inline private
Definition at line 114 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_2.ToString() );
    }
References GetInt().
GetEmoteSlot3()
int PluginConfigHandler::GetEmoteSlot3 () inline private
Definition at line 124 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_3.ToString() );
    }
References GetInt().
GetEmoteSlot4()
int PluginConfigHandler::GetEmoteSlot4 () inline private
Definition at line 134 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_4.ToString() );
    }
References GetInt().
GetEmoteSlot5()
int PluginConfigHandler::GetEmoteSlot5 () inline private
Definition at line 144 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_5.ToString() );
    }
References GetInt().
GetEmoteSlot6()
int PluginConfigHandler::GetEmoteSlot6 () inline private
Definition at line 154 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_6.ToString() );
    }
References GetInt().
GetEmoteSlot7()
int PluginConfigHandler::GetEmoteSlot7 () inline private
Definition at line 164 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_7.ToString() );
    }
References GetInt().
GetEmoteSlot8()
int PluginConfigHandler::GetEmoteSlot8 () inline private
Definition at line 174 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_8.ToString() );
    }
References GetInt().
GetEmoteSlot9()
int PluginConfigHandler::GetEmoteSlot9 () inline private
Definition at line 184 of file pluginconfigemotesprofile.c.
    {
        return GetInt( EmoteSlots.EMOTE_9.ToString() );
    }
References GetInt().
GetFileName() [1/4]
override string PluginConfigHandler::GetFileName () inline private
Definition at line 350 of file pluginconfigdebugprofile.c.
    {
        return CFG_FILE_DEBUG_PROFILE;
    }
References CFG_FILE_DEBUG_PROFILE.
Referenced by SceneDataLoad().
GetFileName() [2/4]
override string PluginConfigHandler::GetFileName () inline private
Definition at line 96 of file pluginconfigemotesprofile.c.
    {
        return CFG_FILE_EMOTES_PROFILE;
    }
References CFG_FILE_EMOTES_PROFILE.
GetFileName() [3/4]
override string PluginConfigHandler::GetFileName () inline private
Definition at line 54 of file pluginconfigscene.c.
    {
        return GetPathScenes()+"\\"+m_FileSceneName;
    }
References GetPathScenes(), and m_FileSceneName.
GetFileName() [4/4]
override string PluginConfigHandler::GetFileName () inline private
Definition at line 33 of file pluginmissionconfig.c.
    {
        return g_Game.GetMissionFolderPath() +"\\"+ FILE_NAME;
    }
References FILE_NAME, and g_Game.
GetFloat()
protected float PluginConfigHandler::GetFloat (string key) inline private
Definition at line 169 of file pluginconfigdebugprofile.c.
    {
        if ( ParamExist(key) )
        {
            CfgParamFloat param = CfgParamFloat.Cast( GetParamByName( key, CFG_TYPE_FLOAT ) );
            return param.GetValue();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamFloat default_param = CfgParamFloat.Cast( m_DefaultValues.Get( key ) );
                return SetFloat( key, default_param.GetValue() ).GetValue();
            }
            else
            {
                return SetFloat( key, 0.0 ).GetValue();
            }
        }
    }
References CFG_TYPE_FLOAT.
GetFreeCameraCrosshairVisible()
bool PluginConfigHandler::GetFreeCameraCrosshairVisible () inline private
Definition at line 585 of file pluginconfigdebugprofile.c.
    {
        return GetBool( FREE_CAMERA_CROSSHAIR );
    }
GetInstance() [1/3]
static PluginConfigDebugProfile PluginConfigHandler::GetInstance () inline static private
Definition at line 39 of file pluginconfigdebugprofile.c.
    {
        return PluginConfigDebugProfile.Cast( GetPlugin(PluginConfigDebugProfile) );
    }
References GetPlugin().
GetInstance() [2/3]
static PluginConfigEmotesProfile PluginConfigHandler::GetInstance () inline static private
Definition at line 22 of file pluginconfigemotesprofile.c.
    {
        return PluginConfigEmotesProfile.Cast( GetPlugin(PluginConfigEmotesProfile) );
    }
References GetPlugin().
GetInstance() [3/3]
static PluginMissionConfig PluginConfigHandler::GetInstance () inline static private
Definition at line 9 of file pluginmissionconfig.c.
    {
        return PluginMissionConfig.Cast( GetPlugin(PluginMissionConfig) );
    }
References GetPlugin().
GetInt() [1/2]
protected int PluginConfigHandler::GetInt (string key) inline private
Definition at line 201 of file pluginconfigdebugprofile.c.
    {
        if ( ParamExist(key) )
        {
            CfgParamInt param = CfgParamInt.Cast( GetParamByName( key, CFG_TYPE_INT ) );
            return param.GetValue();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamInt default_param = CfgParamInt.Cast( m_DefaultValues.Get( key ) );
                return SetInt( key, default_param.GetValue() ).GetValue();
            }
            else
            {
                return SetInt( key, 0 ).GetValue();
            }
        }
    }
References CFG_TYPE_INT.
GetInt() [2/2]
protected int PluginConfigHandler::GetInt (string key) inline private
Definition at line 49 of file pluginconfigemotesprofile.c.
    {
        if ( ParamExist(key) )
        {
            CfgParamInt param = CfgParamInt.Cast( GetParamByName( key, CFG_TYPE_INT ) );
            return param.GetValue();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamInt default_param = CfgParamInt.Cast( m_DefaultValues.Get( key ) );
                return SetInt( key, default_param.GetValue() ).GetValue();
            }
            else
            {
                return SetInt( key, 0 ).GetValue();
            }
        }
    }
References CFG_TYPE_INT, and SetInt().
GetItemCategoryFlag()
int PluginConfigHandler::GetItemCategoryFlag () inline private
Definition at line 678 of file pluginconfigdebugprofile.c.
    {
        return GetInt( ITEM_CATEGORY_FLAG );
    }
References GetInt().
GetItemHealth()
float PluginConfigHandler::GetItemHealth (string preset_name, int item_index) inline private
Definition at line 888 of file pluginconfigdebugprofile.c.
    {
        CfgParam param = GetItemParam( preset_name, item_index, SUB_PARAM_ITEM_HEALTH );
        if ( param == NULL )
        {
            return 100;
        }
        else
        {
            CfgParamFloat param_float = CfgParamFloat.Cast( param );
            return param_float.GetValue();
        }
    }
GetItemParam()
protected CfgParam PluginConfigHandler::GetItemParam (string preset_name, int item_index, string param_name) inline private
Definition at line 867 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> item_params = GetItemParams( preset_name, item_index );
        if ( item_params == NULL )
        {
            return NULL;
        }
        CfgParam param = NULL;
        for ( int i = 0; i < item_params.Count(); i++ )
        {
            if ( item_params.Get(i).GetName() == param_name )
            {
                param = item_params.Get(i);
            }
        }
        return param;
    }
GetItemParams()
protected array< ref CfgParam > PluginConfigHandler::GetItemParams (string preset_name, int item_index) inline private
Definition at line 847 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find( preset_name ) == -1 )
        {
            return NULL;
        }
        array<ref CfgParam> params = GetArray( preset_name );
        if ( item_index >= params.Count() )
        {
            return NULL;
        }
        CfgParamArray params_array = CfgParamArray.Cast( params.Get( item_index ) );
        array<ref CfgParam> item_params = params_array.GetValues();
        return item_params;
    }
GetItemQuantity()
int PluginConfigHandler::GetItemQuantity (string preset_name, int item_index) inline private
Definition at line 929 of file pluginconfigdebugprofile.c.
    {
        CfgParam param = GetItemParam( preset_name, item_index, SUB_PARAM_ITEM_QUANTITY );
        if ( param == NULL )
        {
            return -1;
        }
        else
        {
            CfgParamInt param_int = CfgParamInt.Cast( param );
            return param_int.GetValue();
        }
    }
GetItemSearch()
string PluginConfigHandler::GetItemSearch () inline private
Definition at line 465 of file pluginconfigdebugprofile.c.
    {
        return GetString( ITEM_SEARCH );
    }
GetLogsEnabled()
bool PluginConfigHandler::GetLogsEnabled () inline private
Definition at line 491 of file pluginconfigdebugprofile.c.
    {
        return GetBool( LOGS_ENABLED );
    }
GetMergeType()
bool PluginConfigHandler::GetMergeType () inline private
Definition at line 611 of file pluginconfigdebugprofile.c.
    {
        return GetBool( MERGE_TYPE );
    }
GetNewCfgParamArray()
protected CfgParamArray PluginConfigHandler::GetNewCfgParamArray (array< ref CfgParam > params) inline private
Definition at line 47 of file pluginconfigdebugprofile.c.
    {
        CfgParamArray param = new CfgParamArray( "" );
        param.SetParams( params );
        return param;
    }
GetNewCfgParamBool()
protected CfgParamBool PluginConfigHandler::GetNewCfgParamBool (bool value) inline private
Definition at line 57 of file pluginconfigdebugprofile.c.
    {
        CfgParamBool param = new CfgParamBool( "" );
        param.SetValue( value );
        return param;
    }
GetNewCfgParamFloat()
protected CfgParamFloat PluginConfigHandler::GetNewCfgParamFloat (float value) inline private
Definition at line 67 of file pluginconfigdebugprofile.c.
    {
        CfgParamFloat param = new CfgParamFloat( "" );
        param.SetValue( value );
        return param;
    }
GetNewCfgParamInt() [1/2]
protected CfgParamInt PluginConfigHandler::GetNewCfgParamInt (int value) inline private
Definition at line 77 of file pluginconfigdebugprofile.c.
    {
        CfgParamInt param = new CfgParamInt( "" );
        param.SetValue( value );
        return param;
    }
GetNewCfgParamInt() [2/2]
protected CfgParamInt PluginConfigHandler::GetNewCfgParamInt (int value) inline private
Definition at line 31 of file pluginconfigemotesprofile.c.
    {
        CfgParamInt param = new CfgParamInt( "" );
        param.SetValue( value );
        return param;
    }
GetNewCfgParamString()
protected CfgParamString PluginConfigHandler::GetNewCfgParamString (string value) inline private
Definition at line 87 of file pluginconfigdebugprofile.c.
    {
        CfgParamString param = new CfgParamString( "" );
        param.SetValue( value );
        return param;
    }
GetPathScenes()
string PluginConfigHandler::GetPathScenes () inline private
Definition at line 46 of file pluginconfigscene.c.
    {
        return FILE_ROOT+"\\"+FILE_ROOT_SCENES;
    }
References FILE_ROOT_SCENES.
Referenced by GetFileName(), GetSceneList(), SceneDelete(), SceneDuplicate(), and SceneRename().
GetPresetItems()
bool PluginConfigHandler::GetPresetItems (string preset_name, out TStringArray arr, string param_name = "") inline private
Definition at line 733 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find(preset_name) == -1 )
        {
            return false;
        }
        if(param_name == "")
            param_name = SUB_PARAM_ITEM_NAME;
        GetSubParametersInStringArray( preset_name, param_name, arr );
        return true;
    }
GetPresets()
TStringArray PluginConfigHandler::GetPresets () inline private
Definition at line 691 of file pluginconfigdebugprofile.c.
    {
        return m_PresetList;
    }
GetSceneEditorDrawSelection()
bool PluginConfigHandler::GetSceneEditorDrawSelection () inline private
Definition at line 358 of file pluginconfigdebugprofile.c.
    {
        return GetBool( SCENE_DRAW_SELECTION );
    }
GetSceneEditorLoadPlayerPos()
bool PluginConfigHandler::GetSceneEditorLoadPlayerPos () inline private
Definition at line 371 of file pluginconfigdebugprofile.c.
    {
        return GetBool( SCENE_LOAD_PLAYER_POS );
    }
GetSceneEditorName()
string PluginConfigHandler::GetSceneEditorName () inline private
Definition at line 41 of file pluginmissionconfig.c.
    {
        CfgParamString cfg_scene_name = CfgParamString.Cast( GetParamByName( SCENE_EDITOR_SCENE, CFG_TYPE_STRING ) );
        if ( cfg_scene_name.GetValue() == STRING_EMPTY )
        {
            cfg_scene_name.SetValue( PluginSceneManager.SCENE_DEFAULT_NAME );
            SaveConfigToFile();
        }
        return cfg_scene_name.GetValue();
    }
References CFG_TYPE_STRING, and STRING_EMPTY.
GetSceneEditorRotationAngle()
int PluginConfigHandler::GetSceneEditorRotationAngle () inline private
Definition at line 384 of file pluginconfigdebugprofile.c.
    {
        return GetInt( SCENE_ROTATION_ANGLE );
    }
References GetInt().
GetSceneList()
TStringArray PluginConfigHandler::GetSceneList () inline private
Definition at line 99 of file pluginconfigscene.c.
    {
        if ( !FileExist( GetPathScenes() ) )
        {
            MakeDirectory( GetPathScenes() );
        }
        string  file_name;
        int     file_attr;
        int     flags;
        TStringArray list = new TStringArray;
        string path_find_pattern = GetPathScenes()+"/*."+PluginSceneManager.SCENE_SUFIX; //*/
        FindFileHandle file_handler = FindFile(path_find_pattern, file_name, file_attr, flags);
        bool found = true;
        while ( found )
        {
            int pos = file_name.IndexOf(".");
            if ( pos > -1 )
            {
                list.Insert( file_name.Substring(0, pos) );
            }
            found = FindNextFile(file_handler, file_name, file_attr);
        }
        return list;
    }
References FileExist(), FindFile(), FindNextFile(), GetPathScenes(), string::IndexOf(), MakeDirectory(), and string::Substring().
GetShowItemPreview()
bool PluginConfigHandler::GetShowItemPreview () inline private
Definition at line 650 of file pluginconfigdebugprofile.c.
    {
        return GetBool( ITEM_PREVIEW );
    }
GetSoundsetFilter()
string PluginConfigHandler::GetSoundsetFilter () inline private
Definition at line 624 of file pluginconfigdebugprofile.c.
    {
        return GetString( SOUNDFILTER );
    }
GetSpawnDistance()
float PluginConfigHandler::GetSpawnDistance () inline private
Definition at line 478 of file pluginconfigdebugprofile.c.
    {
        return GetFloat( SPAWN_DISTANCE );
    }
GetString()
protected string PluginConfigHandler::GetString (string key) inline private
Definition at line 236 of file pluginconfigdebugprofile.c.
    {
        CfgParamString param = CfgParamString.Cast( GetParamByName( key, CFG_TYPE_STRING ) );
        if ( param && param.GetValue() != STRING_EMPTY )
        {
            return param.GetValue();
        }
        else
        {
            if ( m_DefaultValues.Contains(key) )
            {
                CfgParamString default_param = CfgParamString.Cast( m_DefaultValues.Get( key ) );
                CfgParamString param_string = SetString( key, default_param.GetValue() );
                if(param_string)
                    return param_string.GetValue();
            }
            else
            {
                return SetString( key, "" ).GetValue();
            }
        }
        return "";
    }
References CFG_TYPE_STRING, and STRING_EMPTY.
GetSubParametersInStringArray()
protected void PluginConfigHandler::GetSubParametersInStringArray (string setting_name, string sub_param_name, out TStringArray arr) inline private
Definition at line 261 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> items = GetArray( setting_name );
        for ( int i = 0; i < items.Count(); i++ )
        {
            CfgParamArray items_array = CfgParamArray.Cast( items.Get(i) );
            array<ref CfgParam> item_params = items_array.GetValues();
            for ( int j = 0; j < item_params.Count(); j++ )
            {
                if ( item_params.Get(j).GetName() == sub_param_name )
                {
                    CfgParamString param_string = CfgParamString.Cast( item_params.Get( j ) );
                    arr.Insert( param_string.GetValue() );
                }
            }
        }
    }
GetTabSelected()
int PluginConfigHandler::GetTabSelected () inline private
Definition at line 397 of file pluginconfigdebugprofile.c.
    {
        return GetInt( ITEM_TAB_SELECTED );
    }
References GetInt().
GetTempVisible()
bool PluginConfigHandler::GetTempVisible () inline private
Definition at line 637 of file pluginconfigdebugprofile.c.
    {
        return GetBool( TEMP_VIS );
    }
GetVersionVisible()
bool PluginConfigHandler::GetVersionVisible () inline private
Definition at line 598 of file pluginconfigdebugprofile.c.
    {
        return GetBool( VERSION_VIS );
    }
ItemAddToPreset()
bool PluginConfigHandler::ItemAddToPreset (string preset_name, string item_name) inline private
Definition at line 790 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find( preset_name ) == -1 )
        {
            return false;
        }
        CfgParamString param = new CfgParamString( SUB_PARAM_ITEM_NAME );
        param.SetValue( item_name );
        CfgParamArray item_params = new CfgParamArray( SUB_PARAM_ITEM );
        item_params.InsertValue( param );
        array<ref CfgParam> params = GetArray( preset_name );
        params.Insert( item_params );
        SaveConfigToFile();
        return true;
    }
ItemRemoveFromPreset()
bool PluginConfigHandler::ItemRemoveFromPreset (string preset_name, int item_index) inline private
Definition at line 811 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find( preset_name ) == -1 )
        {
            return false;
        }
        array<ref CfgParam> params = GetArray( preset_name );
        if ( item_index >= params.Count() )
        {
            return false;
        }
        params.Remove( item_index );
        SaveConfigToFile();
        return true;
    }
LoadSceneObjects()
void PluginConfigHandler::LoadSceneObjects (SceneData scene) inline private
Definition at line 555 of file pluginconfigscene.c.
    {
        CfgParamInt cfg_obj_count = CfgParamInt.Cast( GetParamByName(PARAM_OBJ_COUNT, CFG_TYPE_INT) );
        int obj_count = cfg_obj_count.GetValue();
        for ( int i = 0; i < obj_count; ++i )
        {
            string param_name = PARAM_OBJ_NAME+"_"+i.ToString();
            // Load scene object name
            CfgParamArray cfg_obj = CfgParamArray.Cast( GetParamByName(param_name, CFG_TYPE_ARRAY) );
            CfgParamString  cfg_obj_type    = CfgParamString.Cast( cfg_obj.GetValueByName(PARAM_OBJ_TYPE, CFG_TYPE_STRING) );
            CfgParamString  cfg_obj_pos     = CfgParamString.Cast( cfg_obj.GetValueByName(PARAM_OBJ_POS, CFG_TYPE_STRING) );
            CfgParamFloat   cfg_obj_rot     = CfgParamFloat.Cast( cfg_obj.GetValueByName(PARAM_OBJ_ROT, CFG_TYPE_FLOAT) );
            CfgParamFloat   cfg_obj_hlt     = CfgParamFloat.Cast( cfg_obj.GetValueByName(PARAM_OBJ_HLT, CFG_TYPE_FLOAT) );
            CfgParamString  cfg_obj_iscr    = CfgParamString.Cast( cfg_obj.GetValueByName(PARAM_OBJ_ISCR, CFG_TYPE_STRING) );
//PrintString(itoa(i)+ " Loading param_name: "+ param_name+ " => object type: "+ cfg_obj_type.GetValue());
            // Create Scene Object + position
            SceneObject scn_obj = scene.CreateSceneObject(cfg_obj_type.GetValue(), cfg_obj_pos.GetValue().ToVector());
            // Setup rotation
            scn_obj.SetRotation(cfg_obj_rot.GetValue());
            // Setup health
            scn_obj.SetHealth(cfg_obj_hlt.GetValue());
            // Setup init script
            scn_obj.SetInitScript( DecodeInitScript(cfg_obj_iscr.GetValue()) );
            // Setup indices for linked objects
            CfgParamArray cfg_obj_param_links = CfgParamArray.Cast( GetParamByName(param_name + "_" + PARAM_OBJ_LNK, CFG_TYPE_ARRAY) );
            array<ref CfgParam> cfg_obj_links = cfg_obj_param_links.GetValues();
            for ( int lnko = 0; lnko < cfg_obj_links.Count(); lnko++ )
            {
                CfgParamInt cfg_obj_param_lnk_int = CfgParamInt.Cast( cfg_obj_links.Get(lnko) );
                scn_obj.m_LinkedSceneObjectsIndices.Insert( cfg_obj_param_lnk_int.GetValue() );
            }
            string param_name_att = param_name +"_"+ PARAM_OBJ_ATT;
            if ( ParamExist(param_name_att) )
            {
                CfgParamArray cfg_param_att = CfgParamArray.Cast( GetParamByName(param_name_att, CFG_TYPE_ARRAY) );
                array<ref CfgParam> cfg_param_attachments = cfg_param_att.GetValues();
                for ( int j = 0; j < cfg_param_attachments.Count(); ++j )
                {
                    CfgParamString cfg_param_att_str = CfgParamString.Cast( cfg_param_attachments.Get(j) );
                    scn_obj.GetObject().GetInventory().CreateAttachment( cfg_param_att_str.GetValue() );
                }
            }
        }
    }
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, SceneData::CreateSceneObject(), DecodeInitScript(), SceneObject::GetObject(), SceneObject::m_LinkedSceneObjectsIndices, PARAM_OBJ_ATT, SceneObject::SetHealth(), SceneObject::SetInitScript(), SceneObject::SetRotation(), and string::ToString().
Referenced by SceneDataLoad().
LoadScenePlayer()
void PluginConfigHandler::LoadScenePlayer (SceneData scene) inline private
Definition at line 509 of file pluginconfigscene.c.
    {
        // Only in local game (without server, (GetGame.GetPlayer is null on server! -> by design)
        if ( GetGame().GetPlayer() != NULL )
        {
            CfgParamArray   cfg_player      = CfgParamArray.Cast( GetParamByName(PARAM_PLAYER, CFG_TYPE_ARRAY) );
            CfgParamString  cfg_ply_pos     = CfgParamString.Cast( cfg_player.GetValueByName(PARAM_OBJ_POS, CFG_TYPE_STRING) );
            CfgParamFloat   cfg_ply_rot     = CfgParamFloat.Cast( cfg_player.GetValueByName(PARAM_OBJ_ROT, CFG_TYPE_FLOAT) );
            CfgParamFloat   cfg_ply_hlt     = CfgParamFloat.Cast( cfg_player.GetValueByName(PARAM_OBJ_HLT, CFG_TYPE_FLOAT) );
            CfgParamString  cfg_ply_iscr    = CfgParamString.Cast( cfg_player.GetValueByName(PARAM_OBJ_ISCR, CFG_TYPE_STRING) );
            ScenePlayer scn_player = scene.CreateScenePlayer();
            scn_player.LinkEntityAI(GetGame().GetPlayer());
            if ( PluginSceneManager.GetInstance().GetLoadPlayerPos() )
            {
                // start scene position
                vector start_pos = cfg_ply_pos.GetValue().ToVector();
                if ( start_pos != vector.Zero )
                {
                    // Set Position
                    scn_player.SetPosition(cfg_ply_pos.GetValue().ToVector());
                    // Set Rotation
                    scn_player.SetRotation(cfg_ply_rot.GetValue());
                }
            }
            // Set Health
            // Health check. Do not spawn player character as dead. He can still be spawned as injured.
            float health2 = cfg_ply_hlt.GetValue();
            if (health2 <= 0)
                health2 = scn_player.GetMaxHealth();
            scn_player.SetHealth(health2);
            // Exe Script
            scn_player.SetInitScript( DecodeInitScript(cfg_ply_iscr.GetValue()) );
        }
//PrintString("LoadScenePlayer.. Finished");
    }
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_STRING, SceneData::CreateScenePlayer(), DecodeInitScript(), GetGame(), GetPlayer(), and vector::Zero.
Referenced by SceneDataLoad().
LoadSceneSettings()
void PluginConfigHandler::LoadSceneSettings (SceneData scene) inline private
Definition at line 403 of file pluginconfigscene.c.
    {
        // Load Mission Name
        CfgParamString cfg_mission = CfgParamString.Cast( GetParamByName(PARAM_MISSION, CFG_TYPE_STRING) );
        scene.SetNameMission(cfg_mission.GetValue());
        // Load Time
        CfgParamFloat cfg_time = CfgParamFloat.Cast( GetParamByName(PARAM_TIME, CFG_TYPE_FLOAT) );
        scene.SetInitTime(cfg_time.GetValue());
        int year, month, day, hour, minute;
        GetGame().GetWorld().GetDate( year, month, day, hour, minute );
        // Load Year
        if ( ParamExist(PARAM_YEAR) )
        {
            CfgParamInt cfg_year = CfgParamInt.Cast( GetParamByName( PARAM_YEAR, CFG_TYPE_INT ) );
            scene.SetInitYear( cfg_year.GetValue() );
        }
        else
        {
            scene.SetInitYear( year );
        }
        // Load Month
        if ( ParamExist(PARAM_MONTH) )
        {
            CfgParamInt cfg_month = CfgParamInt.Cast( GetParamByName( PARAM_MONTH, CFG_TYPE_INT ) );
            scene.SetInitMonth( cfg_month.GetValue() );
        }
        else
        {
            scene.SetInitMonth( month );
        }
        // Load Day
        if ( ParamExist(PARAM_DAY) )
        {
            CfgParamInt cfg_day = CfgParamInt.Cast(  GetParamByName( PARAM_DAY, CFG_TYPE_INT ) );
            scene.SetInitDay( cfg_day.GetValue() );
        }
        else
        {
            scene.SetInitDay( day );
        }
        // Load Hour
        if ( ParamExist(PARAM_HOUR) )
        {
            CfgParamInt cfg_hour = CfgParamInt.Cast( GetParamByName( PARAM_HOUR, CFG_TYPE_INT ) );
            scene.SetInitHour( cfg_hour.GetValue() );
        }
        else
        {
            scene.SetInitHour( hour );
        }
        // Load Minute
        if ( ParamExist(PARAM_MINUTE) )
        {
            CfgParamInt cfg_minute = CfgParamInt.Cast( GetParamByName( PARAM_MINUTE, CFG_TYPE_INT ) );
            scene.SetInitMinute( cfg_minute.GetValue() );
        }
        else
        {
            scene.SetInitMinute( minute );
        }
    }
References CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, World::GetDate(), GetGame(), CGame::GetWorld(), SceneData::SetInitDay(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitTime(), SceneData::SetInitYear(), and SceneData::SetNameMission().
Referenced by SceneDataLoad().
LoadSceneWeather()
void PluginConfigHandler::LoadSceneWeather (SceneData scene) inline private
Definition at line 475 of file pluginconfigscene.c.
    {
        //Load Weather Overcast
        if ( ParamExist(PARAM_OVERCAST) )
        {
            CfgParamFloat cfg_overcast = CfgParamFloat.Cast( GetParamByName(PARAM_OVERCAST, CFG_TYPE_FLOAT) );
            scene.SetInitOvercast(cfg_overcast.GetValue());
        }
        //Load Weather Rain
        if ( ParamExist(PARAM_RAIN) )
        {
            CfgParamFloat cfg_rain = CfgParamFloat.Cast( GetParamByName(PARAM_RAIN, CFG_TYPE_FLOAT) );
            scene.SetInitRain(cfg_rain.GetValue());
        }
        //Load Weather Fog
        if ( ParamExist(PARAM_FOG) )
        {
            CfgParamFloat cfg_fog = CfgParamFloat.Cast( GetParamByName(PARAM_FOG, CFG_TYPE_FLOAT) );
            scene.SetInitFog(cfg_fog.GetValue());
        }
        //Load Weather Wind Force
        if ( ParamExist(PARAM_WIND_F) )
        {
            CfgParamFloat cfg_wind_force = CfgParamFloat.Cast( GetParamByName(PARAM_WIND_F, CFG_TYPE_FLOAT) );
            scene.SetInitWindForce(cfg_wind_force.GetValue());
        }
    }
References CFG_TYPE_FLOAT, SceneData::SetInitFog(), SceneData::SetInitOvercast(), SceneData::SetInitRain(), and SceneData::SetInitWindForce().
Referenced by SceneDataLoad().
OnInit() [1/3]
override void PluginConfigHandler::OnInit () inline private
Definition at line 333 of file pluginconfigdebugprofile.c.
    {
        super.OnInit();
        array<ref CfgParam> params = GetArray( PRESET_LIST );
        m_PresetList = new TStringArray;
        for ( int i = 0; i < params.Count(); i++ )
        {
            CfgParamString param = CfgParamString.Cast( params.Get( i ) );
            m_PresetList.Insert( param.GetValue() );
        }
    }
OnInit() [2/3]
override void PluginConfigHandler::OnInit () inline private
Definition at line 36 of file pluginconfigscene.c.
    {
        //super.OnInit();
        FILE_ROOT = g_Game.GetMissionFolderPath();
    }
References g_Game.
OnInit() [3/3]
override void PluginConfigHandler::OnInit () inline private
Definition at line 17 of file pluginmissionconfig.c.
    {
        super.OnInit();
        CfgParamString cfg_scene_name = CfgParamString.Cast( GetParamByName( SCENE_EDITOR_SCENE, CFG_TYPE_STRING ) );
        if ( cfg_scene_name.GetValue() == STRING_EMPTY )
        {
            cfg_scene_name.SetValue( PluginSceneManager.SCENE_DEFAULT_NAME );
            SaveConfigToFile();
        }
    }
References CFG_TYPE_STRING, and STRING_EMPTY.
PluginConfigDebugProfile()
void PluginConfigHandler::PluginConfigDebugProfile () inline private
Definition at line 283 of file pluginconfigdebugprofile.c.
    {
        m_DefaultValues = new map<string, ref CfgParam>;
        m_DefaultValues.Insert(SCENE_DRAW_SELECTION,    GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(SCENE_LOAD_PLAYER_POS,   GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(SCENE_ROTATION_ANGLE,    GetNewCfgParamInt(15) );
        m_DefaultValues.Insert(ITEM_TAB_SELECTED,       GetNewCfgParamInt(0) );
        m_DefaultValues.Insert(PRESET_DEFAULT,          GetNewCfgParamString("") );
        m_DefaultValues.Insert(ITEM_SEARCH,             GetNewCfgParamString("") );
        m_DefaultValues.Insert(SPAWN_DISTANCE,          GetNewCfgParamFloat(0.0) );
        m_DefaultValues.Insert(LOGS_ENABLED,            GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(CHAR_STATS_VIS,          GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(CHAR_LEVELS_VIS,         GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(CHAR_MODIFIERS_VIS,      GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(CHAR_AGENTS_VIS,         GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(CHAR_DEBUG_VIS,          GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(FREE_CAMERA_CROSSHAIR,   GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(VERSION_VIS,             GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(CONFIG_CLASSES_FLAG,     GetNewCfgParamInt(15) );
        m_DefaultValues.Insert(TEMP_VIS,                GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(MERGE_TYPE,              GetNewCfgParamBool(false) );
        m_DefaultValues.Insert(ITEM_PREVIEW,            GetNewCfgParamBool(true) );
        m_DefaultValues.Insert(BATCH_RECT,              GetNewCfgParamArray(GetDefaultBatchRectParams()) );
        m_DefaultValues.Insert(BATCH_QUANT,             GetNewCfgParamInt(10) );
        m_DefaultValues.Insert(SOUNDFILTER,             GetNewCfgParamString("") );
    }
PluginConfigEmotesProfile()
void PluginConfigHandler::PluginConfigEmotesProfile () inline private
Definition at line 73 of file pluginconfigemotesprofile.c.
    {
        m_DefaultValues = new map<string, ref CfgParam>;
        //Here you can configure default EMOTES
        m_DefaultValues.Insert( EmoteSlots.EMOTE_1.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_GREETING) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_2.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_SOS) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_3.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_HEART) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_4.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_TAUNT) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_5.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_SURRENDER) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_6.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_TAUNTKISS) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_7.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_POINT) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_8.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_TAUNTELBOW) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_9.ToString(),  GetNewCfgParamInt(EmoteConstants.ID_EMOTE_THUMB) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_10.ToString(), GetNewCfgParamInt(EmoteConstants.ID_EMOTE_THROAT) );
        m_DefaultValues.Insert( EmoteSlots.EMOTE_11.ToString(), GetNewCfgParamInt(EmoteConstants.ID_EMOTE_SUICIDE) );
        //m_DefaultValues.Insert( EMOTE_12, GetNewCfgParamInt(EmoteConstants.ID_EMOTE_DANCE) );
        //m_DefaultValues.Insert( EMOTE_12, GetNewCfgParamInt(EmoteConstants.ID_EMOTE_SOS) );
    }
References EmoteConstants::ID_EMOTE_GREETING, EmoteConstants::ID_EMOTE_HEART, EmoteConstants::ID_EMOTE_POINT, EmoteConstants::ID_EMOTE_SOS, EmoteConstants::ID_EMOTE_SUICIDE, EmoteConstants::ID_EMOTE_SURRENDER, EmoteConstants::ID_EMOTE_TAUNT, EmoteConstants::ID_EMOTE_TAUNTELBOW, EmoteConstants::ID_EMOTE_TAUNTKISS, EmoteConstants::ID_EMOTE_THROAT, and EmoteConstants::ID_EMOTE_THUMB.
PresetAdd()
bool PluginConfigHandler::PresetAdd (string preset_name) inline private
Definition at line 746 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find(preset_name) > -1 )
        {
            return false;
        }
        SetPreset( preset_name );
        SetArray( preset_name, new array<ref CfgParam> );
        SaveConfigToFile();
        return true;
    }
PresetRemove()
bool PluginConfigHandler::PresetRemove (string preset_name) inline private
Definition at line 760 of file pluginconfigdebugprofile.c.
    {
        if ( m_PresetList.Find(preset_name) == -1 )
        {
            return false;
        }
        RemovePreset( preset_name );
        RemoveParamByName( preset_name );
        SaveConfigToFile();
        return true;
    }
PresetRename()
bool PluginConfigHandler::PresetRename (string old_preset_name, string new_preset_name) inline private
Definition at line 774 of file pluginconfigdebugprofile.c.
    {
        int index = m_PresetList.Find( old_preset_name );
        if ( index == -1 )
        {
            return false;
        }
        SetPreset( new_preset_name, index );
        RenameParam( old_preset_name, new_preset_name );
        SaveConfigToFile();
        return true;
    }
RemovePreset()
protected void PluginConfigHandler::RemovePreset (string preset_name) inline private
Definition at line 719 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> params = GetArray( PRESET_LIST );
        for ( int i = 0; i < params.Count(); i++ )
        {
            CfgParamString param = CfgParamString.Cast( params.Get(i) );
            if ( param.GetValue() == preset_name )
            {
                params.RemoveItem( param );
                m_PresetList.RemoveItem( preset_name );
            }
        }
    }
SaveSceneObjects()
void PluginConfigHandler::SaveSceneObjects (SceneData scene) inline private
Definition at line 276 of file pluginconfigscene.c.
    {
        array<ref SceneObject> objects = scene.GetSceneObjects();
        // Save Objects
        for ( int i = 0; i < objects.Count(); ++i )
        {
            SceneObject obj = objects.Get(i);
            string param_name;
            param_name = PARAM_OBJ_NAME+"_"+i.ToString();
            // Save Scene Object
            CfgParamArray cfg_param_obj = CfgParamArray.Cast( GetParamByName(param_name, CFG_TYPE_ARRAY) );
            // Obj Type Name
            CfgParamString cfg_param_obj_type = CfgParamString.Cast( cfg_param_obj.GetValueByName(PARAM_OBJ_TYPE, CFG_TYPE_STRING)  );
            cfg_param_obj_type.SetValue(obj.GetTypeName());
            // Obj Position
            CfgParamString cfg_param_obj_pos = CfgParamString.Cast( cfg_param_obj.GetValueByName(PARAM_OBJ_POS, CFG_TYPE_STRING)  );
            cfg_param_obj_pos.SetValue(obj.GetPositionAsString());
            // Obj Rotation
            CfgParamFloat cfg_param_obj_rot = CfgParamFloat.Cast( cfg_param_obj.GetValueByName(PARAM_OBJ_ROT, CFG_TYPE_FLOAT)  );
            cfg_param_obj_rot.SetValue(obj.GetRotation());
            // Obj Health
            CfgParamFloat cfg_param_obj_hlt = CfgParamFloat.Cast( cfg_param_obj.GetValueByName(PARAM_OBJ_HLT, CFG_TYPE_FLOAT)  );
            cfg_param_obj_hlt.SetValue(obj.GetHealth());
            // Obj Init Script
            CfgParamString cfg_param_obj_iscr = CfgParamString.Cast( cfg_param_obj.GetValueByName(PARAM_OBJ_ISCR, CFG_TYPE_STRING) );
            cfg_param_obj_iscr.SetValue( EncodeInitScript(obj.GetInitScript()) );
            EntityAI e_obj = obj.GetObject();
            int attcount = e_obj.GetInventory().AttachmentCount();
            if ( attcount > 0 )
            {
                string param_name_att = param_name+"_"+PARAM_OBJ_ATT;
                CfgParamArray cfg_param_att = CfgParamArray.Cast( GetParamByName(param_name_att, CFG_TYPE_ARRAY) );
                cfg_param_att.Clear();
                for (int att = 0; att < attcount; att++)
                {
                    EntityAI attachment = e_obj.GetInventory().GetAttachmentFromIndex(att);
                    CfgParamString cfg_param_att_str = new CfgParamString("");
                    cfg_param_att_str.SetValue( attachment.GetType() );
                    cfg_param_att.InsertValue( cfg_param_att_str );
                }
            }
            array<SceneObject> linked_scene_objects = obj.GetLinkedSceneObjects();
            if ( linked_scene_objects.Count() > 0 )
            {
                string param_name_lnk = param_name + "_" + PARAM_OBJ_LNK;
                CfgParamArray cfg_param_lnk = CfgParamArray.Cast( GetParamByName( param_name_lnk, CFG_TYPE_ARRAY ) );
                cfg_param_lnk.Clear();
                for ( int lnk = 0; lnk < linked_scene_objects.Count(); lnk++ )
                {
                    CfgParamInt cfg_param_lnk_int = new CfgParamInt("");
                    int index = objects.Find( linked_scene_objects.Get(lnk) );
                    if ( index >= 0 )
                    {
                        cfg_param_lnk_int.SetValue( index );
                        cfg_param_lnk.InsertValue( cfg_param_lnk_int );
                    }
                }
            }
        }
        // Save Count Of objects
        CfgParamInt cfg_obj_count = CfgParamInt.Cast( GetParamByName(PARAM_OBJ_COUNT, CFG_TYPE_INT) );
        cfg_obj_count.SetValue(objects.Count());
    }
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, EncodeInitScript(), SceneObject::GetHealth(), SceneObject::GetInitScript(), SceneObject::GetLinkedSceneObjects(), SceneObject::GetObject(), SceneObject::GetPositionAsString(), SceneObject::GetRotation(), SceneData::GetSceneObjects(), SceneObject::GetTypeName(), PARAM_OBJ_ATT, PARAM_OBJ_LNK, and string::ToString().
Referenced by SceneDataSave().
SaveScenePlayer()
void PluginConfigHandler::SaveScenePlayer (SceneData scene) inline private
Definition at line 244 of file pluginconfigscene.c.
    {
        array<ref ScenePlayer> players = scene.GetScenePlayers();
        if ( players.Count() > 0 )
        {
            ScenePlayer plyr = players.Get(0);
            // Save Player
            CfgParamArray cfg_param_player = CfgParamArray.Cast( GetParamByName(PARAM_PLAYER, CFG_TYPE_ARRAY) );
            // Obj Position
            CfgParamString cfg_param_player_pos = CfgParamString.Cast( cfg_param_player.GetValueByName(PARAM_OBJ_POS, CFG_TYPE_STRING) );
            cfg_param_player_pos.SetValue(plyr.GetPositionAsString());
            // Obj Rotation
            CfgParamFloat cfg_param_player_rot = CfgParamFloat.Cast( cfg_param_player.GetValueByName(PARAM_OBJ_ROT, CFG_TYPE_FLOAT) );
            cfg_param_player_rot.SetValue(plyr.GetRotation());
            // Obj Health
            CfgParamFloat cfg_param_player_hlt = CfgParamFloat.Cast( cfg_param_player.GetValueByName(PARAM_OBJ_HLT, CFG_TYPE_FLOAT) );
            cfg_param_player_hlt.SetValue(plyr.GetHealth());
            // Obj Init Script
            CfgParamString cfg_param_player_iscr = CfgParamString.Cast( cfg_param_player.GetValueByName(PARAM_OBJ_ISCR, CFG_TYPE_STRING) );
            cfg_param_player_iscr.SetValue( EncodeInitScript(plyr.GetInitScript()) );
        }
    }
References CFG_TYPE_ARRAY, CFG_TYPE_FLOAT, CFG_TYPE_STRING, EncodeInitScript(), and SceneData::GetScenePlayers().
Referenced by SceneDataSave().
SaveSceneSettings()
void PluginConfigHandler::SaveSceneSettings (SceneData scene) inline private
Definition at line 188 of file pluginconfigscene.c.
    {
        // Save Mission Name
        CfgParamString cfg_mission = CfgParamString.Cast( GetParamByName(PARAM_MISSION, CFG_TYPE_STRING) );
        cfg_mission.SetValue(scene.GetNameMission());
        // Save Time
        CfgParamFloat cfg_time = CfgParamFloat.Cast( GetParamByName(PARAM_TIME, CFG_TYPE_FLOAT) );
        cfg_time.SetValue(scene.GetInitTime());
        // Save Year
        CfgParamInt cfg_year = CfgParamInt.Cast( GetParamByName(PARAM_YEAR, CFG_TYPE_INT) );
        cfg_year.SetValue(scene.GetInitYear());
        // Save Month
        CfgParamInt cfg_month = CfgParamInt.Cast( GetParamByName(PARAM_MONTH, CFG_TYPE_INT) );
        cfg_month.SetValue(scene.GetInitMonth());
        // Save Day
        CfgParamInt cfg_day = CfgParamInt.Cast( GetParamByName(PARAM_DAY, CFG_TYPE_INT) );
        cfg_day.SetValue(scene.GetInitDay());
        // Save Hour
        CfgParamInt cfg_hour = CfgParamInt.Cast( GetParamByName(PARAM_HOUR, CFG_TYPE_INT) );
        cfg_hour.SetValue(scene.GetInitHour());
        // Save Minute
        CfgParamInt cfg_minute = CfgParamInt.Cast( GetParamByName(PARAM_MINUTE, CFG_TYPE_INT) );
        cfg_minute.SetValue(scene.GetInitMinute());
    }
References CFG_TYPE_FLOAT, CFG_TYPE_INT, CFG_TYPE_STRING, SceneData::GetInitDay(), SceneData::GetInitHour(), SceneData::GetInitMinute(), SceneData::GetInitMonth(), SceneData::GetInitTime(), SceneData::GetInitYear(), and SceneData::GetNameMission().
Referenced by SceneDataSave().
SaveSceneWeather()
void PluginConfigHandler::SaveSceneWeather (SceneData scene) inline private
Definition at line 222 of file pluginconfigscene.c.
    {
        // Save Weather Overcast
        CfgParamFloat cfg_overcast = CfgParamFloat.Cast( GetParamByName(PARAM_OVERCAST, CFG_TYPE_FLOAT) );
        cfg_overcast.SetValue(scene.GetInitOvercast());
        // Save Weather Rain
        CfgParamFloat cfg_rain = CfgParamFloat.Cast( GetParamByName(PARAM_RAIN, CFG_TYPE_FLOAT) );
        cfg_rain.SetValue(scene.GetInitRain());
        // Save Weather Fog
        CfgParamFloat cfg_fog = CfgParamFloat.Cast( GetParamByName(PARAM_FOG, CFG_TYPE_FLOAT) );
        cfg_fog.SetValue(scene.GetInitFog());
        // Save Weather Wind Force
        CfgParamFloat cfg_wind_force = CfgParamFloat.Cast( GetParamByName(PARAM_WIND_F, CFG_TYPE_FLOAT) );
        cfg_wind_force.SetValue(scene.GetInitWindForce());
    }
References CFG_TYPE_FLOAT, SceneData::GetInitFog(), SceneData::GetInitOvercast(), SceneData::GetInitRain(), and SceneData::GetInitWindForce().
Referenced by SceneDataSave().
SceneDataLoad()
SceneData PluginConfigHandler::SceneDataLoad (string scene_name) inline private
Definition at line 368 of file pluginconfigscene.c.
    {
        m_FileSceneName = scene_name+"."+PluginSceneManager.SCENE_SUFIX;
//PrintString("Loading scene: "+ scene_name);
        LoadConfigFile();
        // Load Scene name
        SceneData scene = new SceneData;
        scene.SetNameScene(scene_name);
        // Load Scene settings
        LoadSceneSettings(scene);
        // Load Scene Weather
        LoadSceneWeather(scene);
        // Load Scene Player
        LoadScenePlayer(scene);
        // Load Scene Objects
        LoadSceneObjects(scene);
        if ( !FileExist(GetFileName()) )
        {
            SceneDataSave(scene);
        }
        return scene;
    }
References FileExist(), GetFileName(), LoadSceneObjects(), LoadScenePlayer(), LoadSceneSettings(), LoadSceneWeather(), SceneDataSave(), and SceneData::SetNameScene().
SceneDataSave()
void PluginConfigHandler::SceneDataSave (SceneData scene) inline private
Definition at line 159 of file pluginconfigscene.c.
    {
        PluginSceneManager module_scene_editor = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
        EntityAI player = PluginSceneManager.PLAYER;
        // Log("Saving started....")
        m_FileSceneName = scene.GetNameScene()+"."+PluginSceneManager.SCENE_SUFIX;
        // Save Settings
        SaveSceneSettings(scene);
        // Save Weater
        SaveSceneWeather(scene);
        // Save Players
        SaveScenePlayer(scene);
        // Save Objects
        SaveSceneObjects(scene);
        // Save To File
        SaveConfigToFile();
    }
References SceneData::GetNameScene(), GetPlugin(), SaveSceneObjects(), SaveScenePlayer(), SaveSceneSettings(), and SaveSceneWeather().
Referenced by SceneDataLoad().
SceneDelete()
void PluginConfigHandler::SceneDelete (string scene_name) inline private
Definition at line 72 of file pluginconfigscene.c.
    {
        string file_path = GetPathScenes()+"\\"+scene_name+"."+PluginSceneManager.SCENE_SUFIX;
        PluginFileHandler.FileDelete(file_path);
    }
References GetPathScenes().
SceneDuplicate()
void PluginConfigHandler::SceneDuplicate (string scene_name) inline private
Definition at line 81 of file pluginconfigscene.c.
    {
        string file_path = GetPathScenes()+"\\"+scene_name+"."+PluginSceneManager.SCENE_SUFIX;
        string file_path_new = file_path;
        int i = 0;
        while ( FileExist(file_path_new) )
        {
            file_path_new = GetPathScenes()+"\\"+scene_name+"_copy"+i.ToString()+"."+PluginSceneManager.SCENE_SUFIX;
            i++;
        }
        PluginFileHandler.FileDuplicate(file_path, file_path_new);
    }
References FileExist(), GetPathScenes(), and string::ToString().
SceneRename()
void PluginConfigHandler::SceneRename (string scene_name, string scene_name_new) inline private
Definition at line 62 of file pluginconfigscene.c.
    {
        string file_path = GetPathScenes()+"\\"+scene_name+"."+PluginSceneManager.SCENE_SUFIX;
        string file_path_new = GetPathScenes()+"\\"+scene_name_new+"."+PluginSceneManager.SCENE_SUFIX;
        PluginFileHandler.FileRename(file_path, file_path_new);
    }
References GetPathScenes().
SetArray()
protected CfgParamArray PluginConfigHandler::SetArray (string key, array< ref CfgParam > params) inline private
Definition at line 97 of file pluginconfigdebugprofile.c.
    {
        CfgParamArray param = CfgParamArray.Cast( GetParamByName( key, CFG_TYPE_ARRAY ) );
        param.SetParams( params );
        SaveConfigToFile();
        return param;
    }
References CFG_TYPE_ARRAY.
SetBatchSpawnQuantity()
void PluginConfigHandler::SetBatchSpawnQuantity (int value) inline private
Definition at line 458 of file pluginconfigdebugprofile.c.
    {
        SetInt( BATCH_QUANT, value );
    }
SetBatchSpawnRectangle()
void PluginConfigHandler::SetBatchSpawnRectangle (int row, int column, float rowStep, float columnStep) inline private
Definition at line 428 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> params = GetArray( BATCH_RECT );
        params.Clear();
        CfgParamString param;
        CfgParamInt param1 = new CfgParamInt("");
        param1.SetValue(row);
        CfgParamInt param2 = new CfgParamInt("");
        param2.SetValue(column);
        CfgParamFloat param3 = new CfgParamFloat("");
        param3.SetValue(rowStep);
        CfgParamFloat param4 = new CfgParamFloat("");
        param4.SetValue(columnStep);
        params.Insert(param1);
        params.Insert(param2);
        params.Insert(param3);
        params.Insert(param4);
        SaveConfigToFile();
    }
SetBool()
protected CfgParamBool PluginConfigHandler::SetBool (string key, bool value) inline private
Definition at line 129 of file pluginconfigdebugprofile.c.
    {
        CfgParamBool param = CfgParamBool.Cast( GetParamByName( key, CFG_TYPE_BOOL ) );
        param.SetValue( value );
        SaveConfigToFile();
        return param;
    }
References CFG_TYPE_BOOL.
SetCharacterAgentsVisible()
void PluginConfigHandler::SetCharacterAgentsVisible (bool is_visible) inline private
Definition at line 551 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_AGENTS_VIS, is_visible );
    }
SetCharacterDebugVisible()
void PluginConfigHandler::SetCharacterDebugVisible (bool is_visible) inline private
Definition at line 564 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_DEBUG_VIS, is_visible );
    }
SetCharacterLevelsVisible()
void PluginConfigHandler::SetCharacterLevelsVisible (bool is_visible) inline private
Definition at line 510 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_LEVELS_VIS, is_visible );
    }
SetCharacterModifiersVisible()
void PluginConfigHandler::SetCharacterModifiersVisible (bool is_visible) inline private
Definition at line 538 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_MODIFIERS_VIS, is_visible );
    }
SetCharacterStatsVisible()
void PluginConfigHandler::SetCharacterStatsVisible (bool is_visible) inline private
Definition at line 525 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_STATS_VIS, is_visible );
    }
SetCharacterStomachVisible()
void PluginConfigHandler::SetCharacterStomachVisible (bool is_visible) inline private
Definition at line 577 of file pluginconfigdebugprofile.c.
    {
        SetBool( CHAR_STOMACH_VIS, is_visible );
    }
SetConfigClassesFlag()
void PluginConfigHandler::SetConfigClassesFlag (int flag) inline private
Definition at line 669 of file pluginconfigdebugprofile.c.
    {
        SetInt( CONFIG_CLASSES_FLAG, flag );
    }
SetDefaultPreset()
void PluginConfigHandler::SetDefaultPreset (string value) inline private
Definition at line 415 of file pluginconfigdebugprofile.c.
    {
        SetString( PRESET_DEFAULT, value );
    }
SetEmoteSlot1()
void PluginConfigHandler::SetEmoteSlot1 (int emoted_id) inline private
Definition at line 109 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_1.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot10()
void PluginConfigHandler::SetEmoteSlot10 (int emoted_id) inline private
Definition at line 199 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_10.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot11()
void PluginConfigHandler::SetEmoteSlot11 (int emoted_id) inline private
Definition at line 209 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_11.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot2()
void PluginConfigHandler::SetEmoteSlot2 (int emoted_id) inline private
Definition at line 119 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_2.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot3()
void PluginConfigHandler::SetEmoteSlot3 (int emoted_id) inline private
Definition at line 129 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_3.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot4()
void PluginConfigHandler::SetEmoteSlot4 (int emoted_id) inline private
Definition at line 139 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_4.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot5()
void PluginConfigHandler::SetEmoteSlot5 (int emoted_id) inline private
Definition at line 149 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_5.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot6()
void PluginConfigHandler::SetEmoteSlot6 (int emoted_id) inline private
Definition at line 159 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_6.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot7()
void PluginConfigHandler::SetEmoteSlot7 (int emoted_id) inline private
Definition at line 169 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_7.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot8()
void PluginConfigHandler::SetEmoteSlot8 (int emoted_id) inline private
Definition at line 179 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_8.ToString(), emoted_id );
    }
References SetInt().
SetEmoteSlot9()
void PluginConfigHandler::SetEmoteSlot9 (int emoted_id) inline private
Definition at line 189 of file pluginconfigemotesprofile.c.
    {
        SetInt( EmoteSlots.EMOTE_9.ToString(), emoted_id );
    }
References SetInt().
SetFloat()
protected CfgParamFloat PluginConfigHandler::SetFloat (string key, float value) inline private
Definition at line 161 of file pluginconfigdebugprofile.c.
    {
        CfgParamFloat param = CfgParamFloat.Cast( GetParamByName( key, CFG_TYPE_FLOAT ) );
        param.SetValue( value );
        SaveConfigToFile();
        return param;
    }
References CFG_TYPE_FLOAT.
SetFreeCameraCrosshairVisible()
void PluginConfigHandler::SetFreeCameraCrosshairVisible (bool is_visible) inline private
Definition at line 590 of file pluginconfigdebugprofile.c.
    {
        SetBool( FREE_CAMERA_CROSSHAIR, is_visible );
    }
SetInt() [1/2]
protected CfgParamInt PluginConfigHandler::SetInt (string key, int value) inline private
Definition at line 193 of file pluginconfigdebugprofile.c.
    {
        CfgParamInt param = CfgParamInt.Cast( GetParamByName( key, CFG_TYPE_INT ) );
        param.SetValue( value );
        SaveConfigToFile();
        return param;
    }
References CFG_TYPE_INT.
Referenced by GetInt(), SetEmoteSlot1(), SetEmoteSlot10(), SetEmoteSlot11(), SetEmoteSlot2(), SetEmoteSlot3(), SetEmoteSlot4(), SetEmoteSlot5(), SetEmoteSlot6(), SetEmoteSlot7(), SetEmoteSlot8(), and SetEmoteSlot9().
SetInt() [2/2]
protected CfgParamInt PluginConfigHandler::SetInt (string key, int value) inline private
Definition at line 41 of file pluginconfigemotesprofile.c.
    {
        CfgParamInt param = CfgParamInt.Cast( GetParamByName( key, CFG_TYPE_INT ) );
        param.SetValue( value );
        //SaveConfigToFile();
        return param;
    }
References CFG_TYPE_INT.
SetItemCategoryFlag()
void PluginConfigHandler::SetItemCategoryFlag (int flag) inline private
Definition at line 683 of file pluginconfigdebugprofile.c.
    {
        SetInt( ITEM_CATEGORY_FLAG, flag );
    }
SetItemHealth()
bool PluginConfigHandler::SetItemHealth (string preset_name, int item_index, float health) inline private
Definition at line 903 of file pluginconfigdebugprofile.c.
    {
        CfgParam param = GetItemParam( preset_name, item_index, SUB_PARAM_ITEM_HEALTH );
        if ( param != NULL )
        {
            CfgParamFloat param_float = CfgParamFloat.Cast( param );
            param_float.SetValue( health );
        }
        else
        {
            array<ref CfgParam> item_params = GetItemParams( preset_name, item_index );
            if ( item_params != NULL )
            {
                CfgParamFloat new_param = new CfgParamFloat( SUB_PARAM_ITEM_HEALTH );
                new_param.SetValue( health );
                item_params.Insert( new_param );
            }
        }
        SaveConfigToFile();
        return true;
    }
SetItemQuantity()
bool PluginConfigHandler::SetItemQuantity (string preset_name, int item_index, int quantity) inline private
Definition at line 944 of file pluginconfigdebugprofile.c.
    {
        CfgParam param = GetItemParam( preset_name, item_index, SUB_PARAM_ITEM_QUANTITY );
        if ( param != NULL )
        {
            CfgParamInt param_int = CfgParamInt.Cast( param );
            param_int.SetValue( quantity );
        }
        else
        {
            array<ref CfgParam> item_params = GetItemParams( preset_name, item_index );
            if ( item_params != NULL )
            {
                CfgParamInt new_param = new CfgParamInt( SUB_PARAM_ITEM_QUANTITY );
                new_param.SetValue( quantity );
                item_params.Insert( new_param );
            }
        }
        SaveConfigToFile();
        return true;
    }
SetItemSearch()
void PluginConfigHandler::SetItemSearch (string value) inline private
Definition at line 470 of file pluginconfigdebugprofile.c.
    {
        SetString( ITEM_SEARCH, value );
    }
SetLogsEnabled()
void PluginConfigHandler::SetLogsEnabled (bool value) inline private
Definition at line 496 of file pluginconfigdebugprofile.c.
    {
        SetBool( LOGS_ENABLED, value );
    }
SetMergeType()
void PluginConfigHandler::SetMergeType (bool is_visible) inline private
Definition at line 616 of file pluginconfigdebugprofile.c.
    {
        SetBool( MERGE_TYPE, is_visible );
    }
SetPreset()
protected void PluginConfigHandler::SetPreset (string preset_name, int index = -1) inline private
Definition at line 696 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> params = GetArray( PRESET_LIST );
        CfgParamString param;
        if ( index == -1 )
        {
            param = new CfgParamString( "" );
            param.SetValue( preset_name );
            params.Insert( param );
            m_PresetList.Insert( preset_name );
        }
        else
        {
            param = CfgParamString.Cast( params.Get( index ) );
            param.SetValue( preset_name );
            params.Set( index, param );
            m_PresetList.Set( index, preset_name );
        }
        SaveConfigToFile();
    }
SetSceneEditorDrawSelection()
void PluginConfigHandler::SetSceneEditorDrawSelection (bool value) inline private
Definition at line 363 of file pluginconfigdebugprofile.c.
    {
        SetBool( SCENE_DRAW_SELECTION, value );
    }
SetSceneEditorLoadPlayerPos()
void PluginConfigHandler::SetSceneEditorLoadPlayerPos (bool value) inline private
Definition at line 376 of file pluginconfigdebugprofile.c.
    {
        SetBool( SCENE_LOAD_PLAYER_POS, value );
    }
SetSceneEditorName()
void PluginConfigHandler::SetSceneEditorName (string value) inline private
Definition at line 57 of file pluginmissionconfig.c.
    {
        CfgParamString cfg_scene_name = CfgParamString.Cast( GetParamByName( SCENE_EDITOR_SCENE, CFG_TYPE_STRING ) );
        cfg_scene_name.SetValue( value );
        SaveConfigToFile();
    }
References CFG_TYPE_STRING.
SetSceneEditorRotationAngle()
void PluginConfigHandler::SetSceneEditorRotationAngle (int value) inline private
Definition at line 389 of file pluginconfigdebugprofile.c.
    {
        SetInt( SCENE_ROTATION_ANGLE, value );
    }
SetShowItemPreview()
void PluginConfigHandler::SetShowItemPreview (bool show) inline private
Definition at line 655 of file pluginconfigdebugprofile.c.
    {
        SetBool( ITEM_PREVIEW, show );
    }
SetSoundsetFilter()
void PluginConfigHandler::SetSoundsetFilter (string content) inline private
Definition at line 629 of file pluginconfigdebugprofile.c.
    {
        SetString( SOUNDFILTER, content );
    }
SetSpawnDistance()
void PluginConfigHandler::SetSpawnDistance (float value) inline private
Definition at line 483 of file pluginconfigdebugprofile.c.
    {
        SetFloat( SPAWN_DISTANCE, value );
    }
SetString()
protected CfgParamString PluginConfigHandler::SetString (string key, string value) inline private
Definition at line 225 of file pluginconfigdebugprofile.c.
    {
        CfgParamString param = CfgParamString.Cast( GetParamByName( key, CFG_TYPE_STRING ) );
        if(param)
        {
            param.SetValue( value );
            SaveConfigToFile();
        }
        return param;
    }
References CFG_TYPE_STRING.
SetTabSelected()
void PluginConfigHandler::SetTabSelected (int value) inline private
Definition at line 402 of file pluginconfigdebugprofile.c.
    {
        SetInt( ITEM_TAB_SELECTED, value );
    }
SetTempVisible()
void PluginConfigHandler::SetTempVisible (bool is_visible) inline private
Definition at line 642 of file pluginconfigdebugprofile.c.
    {
        SetBool( TEMP_VIS, is_visible );
    }
SetVersionVisible()
void PluginConfigHandler::SetVersionVisible (bool is_visible) inline private
Definition at line 603 of file pluginconfigdebugprofile.c.
    {
        SetBool( VERSION_VIS, is_visible );
    }
SwapItem()
bool PluginConfigHandler::SwapItem (string preset_name, int item1_index, int item2_index) inline private
Definition at line 832 of file pluginconfigdebugprofile.c.
    {
        array<ref CfgParam> params = GetArray( preset_name );
        if ( item1_index >= params.Count() || item2_index >= params.Count() )
        {
            return false;
        }
        params.SwapItems( item1_index, item2_index );
        SaveConfigToFile();
        return true;
    }
Member Data Documentation
BATCH_QUANT
protected const string PluginConfigHandler::BATCH_QUANT = "batch_spawn_quantity" private
Definition at line 30 of file pluginconfigdebugprofile.c.
BATCH_RECT
protected const string PluginConfigHandler::BATCH_RECT = "batch_spawn_rect" private
Definition at line 29 of file pluginconfigdebugprofile.c.
CHAR_AGENTS_VIS
protected const string PluginConfigHandler::CHAR_AGENTS_VIS = "console_character_agents_visible" private
Definition at line 14 of file pluginconfigdebugprofile.c.
CHAR_DEBUG_VIS
protected const string PluginConfigHandler::CHAR_DEBUG_VIS = "console_character_debug_visible" private
Definition at line 15 of file pluginconfigdebugprofile.c.
CHAR_LEVELS_VIS
protected const string PluginConfigHandler::CHAR_LEVELS_VIS = "console_character_levels_visible" private
Definition at line 12 of file pluginconfigdebugprofile.c.
CHAR_MODIFIERS_VIS
protected const string PluginConfigHandler::CHAR_MODIFIERS_VIS = "console_character_modifiers_visible" private
Definition at line 13 of file pluginconfigdebugprofile.c.
CHAR_STATS_VIS
protected const string PluginConfigHandler::CHAR_STATS_VIS = "console_character_stats_visible" private
Definition at line 11 of file pluginconfigdebugprofile.c.
CHAR_STOMACH_VIS
protected const string PluginConfigHandler::CHAR_STOMACH_VIS = "console_character_stomach_visible" private
Definition at line 16 of file pluginconfigdebugprofile.c.
CONFIG_CLASSES_FLAG
protected const string PluginConfigHandler::CONFIG_CLASSES_FLAG = "toggled_config_classes_flag" private
Definition at line 26 of file pluginconfigdebugprofile.c.
FILE_NAME
protected const string PluginConfigHandler::FILE_NAME = "scene_editor.cfg" private
Definition at line 3 of file pluginmissionconfig.c.
Referenced by GetFileName().
FILE_ROOT
protected string PluginConfigHandler::FILE_ROOT = "$saves:" private
Definition at line 3 of file pluginconfigscene.c.
FILE_ROOT_SCENES
protected const string PluginConfigHandler::FILE_ROOT_SCENES = "scenes" private
Definition at line 4 of file pluginconfigscene.c.
Referenced by GetPathScenes().
FREE_CAMERA_CROSSHAIR
protected const string PluginConfigHandler::FREE_CAMERA_CROSSHAIR = "console_free_camera_crosshair_visible" private
Definition at line 17 of file pluginconfigdebugprofile.c.
ITEM_CATEGORY_FLAG
protected const string PluginConfigHandler::ITEM_CATEGORY_FLAG = "toggled_item_categories_flag" private
Definition at line 27 of file pluginconfigdebugprofile.c.
ITEM_PREVIEW
protected const string PluginConfigHandler::ITEM_PREVIEW = "show_item_preview" private
Definition at line 28 of file pluginconfigdebugprofile.c.
ITEM_SEARCH
protected const string PluginConfigHandler::ITEM_SEARCH = "console_ItemSearch" private
Definition at line 9 of file pluginconfigdebugprofile.c.
ITEM_TAB_SELECTED
protected const string PluginConfigHandler::ITEM_TAB_SELECTED = "console_TabSelected" private
Definition at line 6 of file pluginconfigdebugprofile.c.
LOGS_ENABLED
protected const string PluginConfigHandler::LOGS_ENABLED = "logs_enabled" private
Definition at line 25 of file pluginconfigdebugprofile.c.
m_CfgTemplate
TStringArray PluginConfigHandler::m_CfgTemplate private
Definition at line 29 of file pluginconfigscene.c.
m_DefaultValues
protected ref map< string, ref CfgParam > PluginConfigHandler::m_DefaultValues private
Definition at line 33 of file pluginconfigdebugprofile.c.
m_FileSceneName
protected string PluginConfigHandler::m_FileSceneName private
Definition at line 31 of file pluginconfigscene.c.
Referenced by GetFileName().
m_PresetList
protected ref TStringArray PluginConfigHandler::m_PresetList private
Definition at line 34 of file pluginconfigdebugprofile.c.
MERGE_TYPE
protected const string PluginConfigHandler::MERGE_TYPE = "category_merge_type" private
Definition at line 19 of file pluginconfigdebugprofile.c.
PARAM_DAY
protected const string PluginConfigHandler::PARAM_DAY = "InitDay" private
Definition at line 10 of file pluginconfigscene.c.
PARAM_FOG
protected const string PluginConfigHandler::PARAM_FOG = "WeatherInitFog" private
Definition at line 15 of file pluginconfigscene.c.
PARAM_HOUR
protected const string PluginConfigHandler::PARAM_HOUR = "InitHour" private
Definition at line 11 of file pluginconfigscene.c.
PARAM_MINUTE
protected const string PluginConfigHandler::PARAM_MINUTE = "InitMinute" private
Definition at line 12 of file pluginconfigscene.c.
PARAM_MISSION
protected const string PluginConfigHandler::PARAM_MISSION = "Mission" private
Definition at line 6 of file pluginconfigscene.c.
PARAM_MONTH
protected const string PluginConfigHandler::PARAM_MONTH = "InitMonth" private
Definition at line 9 of file pluginconfigscene.c.
PARAM_OBJ_ATT
protected const string PluginConfigHandler::PARAM_OBJ_ATT = "Att" private
Definition at line 20 of file pluginconfigscene.c.
Referenced by LoadSceneObjects(), and SaveSceneObjects().
PARAM_OBJ_COUNT
protected const string PluginConfigHandler::PARAM_OBJ_COUNT = "SceneObjectsCount" private
Definition at line 18 of file pluginconfigscene.c.
PARAM_OBJ_DMG
protected const string PluginConfigHandler::PARAM_OBJ_DMG = "damage" private
Definition at line 25 of file pluginconfigscene.c.
PARAM_OBJ_HLT
protected const string PluginConfigHandler::PARAM_OBJ_HLT = "health" private
Definition at line 26 of file pluginconfigscene.c.
PARAM_OBJ_ISCR
protected const string PluginConfigHandler::PARAM_OBJ_ISCR = "init_script" private
Definition at line 27 of file pluginconfigscene.c.
PARAM_OBJ_LNK
protected const string PluginConfigHandler::PARAM_OBJ_LNK = "Lnk" private
Definition at line 21 of file pluginconfigscene.c.
Referenced by SaveSceneObjects().
PARAM_OBJ_NAME
protected const string PluginConfigHandler::PARAM_OBJ_NAME = "SceneObject" private
Definition at line 19 of file pluginconfigscene.c.
PARAM_OBJ_POS
protected const string PluginConfigHandler::PARAM_OBJ_POS = "position" private
Definition at line 23 of file pluginconfigscene.c.
PARAM_OBJ_ROT
protected const string PluginConfigHandler::PARAM_OBJ_ROT = "rotation" private
Definition at line 24 of file pluginconfigscene.c.
PARAM_OBJ_TYPE
protected const string PluginConfigHandler::PARAM_OBJ_TYPE = "type" private
Definition at line 22 of file pluginconfigscene.c.
PARAM_OVERCAST
protected const string PluginConfigHandler::PARAM_OVERCAST = "WeatherInitOvercast" private
Definition at line 13 of file pluginconfigscene.c.
PARAM_PLAYER
protected const string PluginConfigHandler::PARAM_PLAYER = "Player" private
Definition at line 17 of file pluginconfigscene.c.
PARAM_RAIN
protected const string PluginConfigHandler::PARAM_RAIN = "WeatherInitRain" private
Definition at line 14 of file pluginconfigscene.c.
PARAM_TIME
protected const string PluginConfigHandler::PARAM_TIME = "InitTime" private
Definition at line 7 of file pluginconfigscene.c.
PARAM_WIND_F
protected const string PluginConfigHandler::PARAM_WIND_F = "WeatherInitWindForce" private
Definition at line 16 of file pluginconfigscene.c.
PARAM_YEAR
protected const string PluginConfigHandler::PARAM_YEAR = "InitYear" private
Definition at line 8 of file pluginconfigscene.c.
PRESET_DEFAULT
protected const string PluginConfigHandler::PRESET_DEFAULT = "console_preset_default" private
Definition at line 8 of file pluginconfigdebugprofile.c.
PRESET_LIST
protected const string PluginConfigHandler::PRESET_LIST = "console_presets" private
Definition at line 7 of file pluginconfigdebugprofile.c.
SCENE_DRAW_SELECTION
protected const string PluginConfigHandler::SCENE_DRAW_SELECTION = "scene_editor_draw_selection" private
Definition at line 3 of file pluginconfigdebugprofile.c.
SCENE_EDITOR_SCENE
protected const string PluginConfigHandler::SCENE_EDITOR_SCENE = "scene_load" private
Definition at line 4 of file pluginmissionconfig.c.
SCENE_LOAD_PLAYER_POS
protected const string PluginConfigHandler::SCENE_LOAD_PLAYER_POS = "scene_editor_load_player_pos" private
Definition at line 4 of file pluginconfigdebugprofile.c.
SCENE_ROTATION_ANGLE
protected const string PluginConfigHandler::SCENE_ROTATION_ANGLE = "scene_editor_rotation_angle" private
Definition at line 5 of file pluginconfigdebugprofile.c.
SOUNDFILTER
protected const string PluginConfigHandler::SOUNDFILTER = "soundset_editbox" private
Definition at line 31 of file pluginconfigdebugprofile.c.
SPAWN_DISTANCE
protected const string PluginConfigHandler::SPAWN_DISTANCE = "console_SpawnDistance" private
Definition at line 10 of file pluginconfigdebugprofile.c.
SUB_PARAM_ITEM
protected const string PluginConfigHandler::SUB_PARAM_ITEM = "item" private
Definition at line 21 of file pluginconfigdebugprofile.c.
SUB_PARAM_ITEM_HEALTH
protected const string PluginConfigHandler::SUB_PARAM_ITEM_HEALTH = "health" private
Definition at line 23 of file pluginconfigdebugprofile.c.
SUB_PARAM_ITEM_NAME
protected const string PluginConfigHandler::SUB_PARAM_ITEM_NAME = "name" private
Definition at line 22 of file pluginconfigdebugprofile.c.
SUB_PARAM_ITEM_QUANTITY
protected const string PluginConfigHandler::SUB_PARAM_ITEM_QUANTITY = "quantity" private
Definition at line 24 of file pluginconfigdebugprofile.c.
TEMP_VIS
protected const string PluginConfigHandler::TEMP_VIS = "console_temperature_visible" private
Definition at line 20 of file pluginconfigdebugprofile.c.
VERSION_VIS
protected const string PluginConfigHandler::VERSION_VIS = "console_version_visible" private
Definition at line 18 of file pluginconfigdebugprofile.c.