DayzKode: Ammo_40mm_Explosive Class Reference
Ammo_40mm_Explosive Class Reference
Private Member Functions
override void EEKilled (Object killer)
override void OnActivatedByItem (notnull ItemBase item)
override void OnDamageDestroyed (int oldLevel)
override bool ShootsExplosiveAmmo ()
Detailed Description
Definition at line 64 of file ammunitionpiles.c.
Member Function Documentation
EEKilled()
override void Ammo_40mm_Explosive::EEKilled (Object killer) inline private
Definition at line 79 of file ammunitionpiles.c.
    {
        super.EEKilled(killer);
        DamageSystem.ExplosionDamage(this, null, "Explosion_40mm_Ammo", GetPosition(), DamageType.EXPLOSION);
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( DeleteSafe, 1000, false);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and GetPosition.
OnActivatedByItem()
override void Ammo_40mm_Explosive::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 71 of file ammunitionpiles.c.
    {
        if (GetGame().IsServer())
        {
            DamageSystem.ExplosionDamage(this, null, "Explosion_40mm_Ammo", item.GetPosition(), DamageType.EXPLOSION);
        }
    }
References GetGame().
OnDamageDestroyed()
override void Ammo_40mm_Explosive::OnDamageDestroyed (int oldLevel) inline private
Definition at line 86 of file ammunitionpiles.c.
    {
        super.OnDamageDestroyed(oldLevel);
        #ifndef SERVER
        ClearFlags(EntityFlags.VISIBLE, false);
        #endif
    }
References ClearFlags().
ShootsExplosiveAmmo()
override bool Ammo_40mm_Explosive::ShootsExplosiveAmmo () inline private
Definition at line 66 of file ammunitionpiles.c.
    {
        return true;
    }