DayzKode: MapMarkerTypes Class Reference
MapMarkerTypes Class Reference
Static Private Member Functions
static string GetMarkerTypeFromID (int id)
static void Init ()
static void RegisterMarkerType (int id, string path)
Static Private Attributes
static protected ref map< int, string > m_MarkerTypes
Detailed Description
Definition at line 1 of file mapmarkersinfo.c.
Member Function Documentation
GetMarkerTypeFromID()
static string MapMarkerTypes::GetMarkerTypeFromID (int id) inline static private
Definition at line 36 of file mapmarkersinfo.c.
    {
        return m_MarkerTypes.Get(id);
    }
References m_MarkerTypes.
Referenced by UIScriptedMenu::AddMarker(), and UIScriptedMenu::LoadMapMarkers().
Init()
static void MapMarkerTypes::Init () inline static private
Definition at line 5 of file mapmarkersinfo.c.
    {
        m_MarkerTypes = new ref map<int,string>;
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_BORDER_CROSS,"\\DZ\\gear\\navigation\\data\\map_border_cross_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_BROADLEAF,"\\DZ\\gear\\navigation\\data\\map_broadleaf_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_CAMP,"\\DZ\\gear\\navigation\\data\\map_camp_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_FACTORY,"\\DZ\\gear\\navigation\\data\\map_factory_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_FIR,"\\DZ\\gear\\navigation\\data\\map_fir_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_FIREDEP,"\\DZ\\gear\\navigation\\data\\map_firedep_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_GOVOFFICE,"\\DZ\\gear\\navigation\\data\\map_govoffice_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_HILL,"\\DZ\\gear\\navigation\\data\\map_hill_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_MONUMENT,"\\DZ\\gear\\navigation\\data\\map_monument_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_PALM,"\\DZ\\gear\\navigation\\data\\map_palm_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_POLICE,"\\DZ\\gear\\navigation\\data\\map_police_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_STATION,"\\DZ\\gear\\navigation\\data\\map_station_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_STORE,"\\DZ\\gear\\navigation\\data\\map_store_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_TOURISM,"\\DZ\\gear\\navigation\\data\\map_tourism_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_TRANSMITTER,"\\DZ\\gear\\navigation\\data\\map_transmitter_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_TSHELTER,"\\DZ\\gear\\navigation\\data\\map_tshelter_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_TSIGN,"\\DZ\\gear\\navigation\\data\\map_tsign_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_VIEWPOINT,"\\DZ\\gear\\navigation\\data\\map_viewpoint_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_VINEYARD,"\\DZ\\gear\\navigation\\data\\map_vineyard_ca.paa");
        RegisterMarkerType(eMapMarkerTypes.MARKERTYPE_MAP_WATERPUMP,"\\DZ\\gear\\navigation\\data\\map_waterpump_ca.paa");
    }
References m_MarkerTypes, and RegisterMarkerType().
Referenced by MissionBase::OnInit().
RegisterMarkerType()
static void MapMarkerTypes::RegisterMarkerType (int id, string path) inline static private
Definition at line 31 of file mapmarkersinfo.c.
    {
        m_MarkerTypes.Set(id,path);
    }
References m_MarkerTypes, and path.
Referenced by Init().
Member Data Documentation
m_MarkerTypes
protected ref map<int,string> MapMarkerTypes::m_MarkerTypes static private
Definition at line 3 of file mapmarkersinfo.c.
Referenced by GetMarkerTypeFromID(), Init(), and RegisterMarkerType().