DayzKode: ActionAnimateSeats Class Reference
ActionAnimateSeats Class Reference
Private Member Functions
void ActionAnimateSeats ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedInVehicle ()
Detailed Description
Definition at line 1 of file actionanimateseats.c.
Constructor & Destructor Documentation
ActionAnimateSeats()
void ActionAnimateSeats::ActionAnimateSeats () inline private
Definition at line 3 of file actionanimateseats.c.
    {
        m_Text = "#move_seat";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionAnimateSeats::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 8 of file actionanimateseats.c.
    {
        if( !target ) return false;
        if( !IsInReach(player, target, UAMaxDistances.DEFAULT) ) return false;
        Object targetObject = target.GetObject();
        Entity targetEnt = Entity.Cast(targetObject);
        Transport transport;
        CarScript car;
        int crewIdx;
        //string selection = targetObject.GetActionComponentName(target.GetComponentIndex());
        array<string> selections = new array<string>();
        targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections);
        if ( !Class.CastTo(transport, targetObject) )
            return false;
        if ( Class.CastTo(car, targetEnt) )
        {
            for (int i = 0; i < selections.Count(); i++)
            {
                m_AnimSource = car.GetAnimSourceFromSelection( selections[i]) ;
                if ( m_AnimSource != "" )
                {
                    //return true; //TODO:: NEED A LINK BETWEEN SeatBack and seat with crew after that we can REMOVE the return
                    HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
                    if ( m_AnimSource == "SeatDriver" )
                    {
                        if ( transport.CrewMember( DayZPlayerConstants.VEHICLESEAT_DRIVER ) )
                            return false;
                        if ( !vehCmd && car.GetCarDoorsState( "NivaDriverDoors" ) == CarDoorState.DOORS_CLOSED )
                            return false;
                    }
                    if ( m_AnimSource == "SeatCoDriver" )
                    {
                        if ( transport.CrewMember( DayZPlayerConstants.VEHICLESEAT_CODRIVER ) )
                            return false;
                        if ( !vehCmd && car.GetCarDoorsState( "NivaCoDriverDoors" ) == CarDoorState.DOORS_CLOSED )
                            return false;
                    }
                    if ( !vehCmd && !transport.CanReachSeatFromDoors(selections[i], player.GetPosition(), 1.0) )
                        return false;
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, CarScript::GetAnimSourceFromSelection(), CarScript::GetCarDoorsState(), IsInReach(), and ActionAnimateCarSelection::m_AnimSource.
CanBeUsedInVehicle()
override bool ActionAnimateSeats::CanBeUsedInVehicle () inline private
Definition at line 67 of file actionanimateseats.c.
    {
        return true;
    }