DayzKode: SlotsIcon Class Reference
SlotsIcon Class Reference
Private Member Functions
void CheckHasItemSize ()
void CheckHasQuantity ()
void CheckHasTemperature ()
void CheckIsMagazine ()
void CheckIsWeapon ()
void Clear ()
Widget GetAmmoIcon ()
Widget GetColorWidget ()
Widget GetColWidget ()
Container GetContainer ()
Widget GetCursorWidget ()
Widget GetEmptySelectedPanel ()
EntityAI GetEntity ()
ImageWidget GetGhostSlot ()
ItemBase GetItem ()
Widget GetItemSizePanel ()
TextWidget GetItemSizeWidget ()
Widget GetMountedWidget ()
Object GetObject ()
Widget GetOutOfReachWidget ()
Widget GetPanelWidget ()
TextWidget GetQuantityItem ()
Widget GetQuantityPanel ()
ProgressBarWidget GetQuantityProgress ()
Widget GetQuantityStack ()
Widget GetRadialIcon ()
Widget GetRadialIconClosed ()
Widget GetRadialIconPanel ()
ItemPreviewWidget GetRender ()
Widget GetReservedWidget ()
Widget GetSelectedPanel ()
string GetSlotDesc ()
string GetSlotDisplayName ()
int GetSlotID ()
EntityAI GetSlotParent ()
void Init (EntityAI obj, bool reservation=false)
bool IsOutOfReach ()
bool IsReserved ()
override bool IsVisible ()
bool MouseEnter (Widget w, int x, int y)
bool MouseEnterGhostSlot (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget s, int x, int y)
bool MouseLeaveGhostSlot (Widget w, Widget s, int x, int y)
void OnIconDrag (Widget w)
void OnIconDrop (Widget w)
override void Refresh ()
void RefreshMuzzleIcon ()
override void SetActive (bool active)
void SetContainer (Container container)
void SetItemPreview ()
void SetItemSize ()
override void SetLayoutName ()
void SetQuantity ()
void SetSlotDesc (string text)
void SetSlotDisplayName (string text)
void SetSlotID (int slot_ID)
void SetSlotParent (EntityAI parent)
void SetTemperature ()
void SlotsIcon (LayoutHolder parent, Widget root, int index, EntityAI slot_parent)
void UpdateFlip (bool flipped)
override void UpdateInterval ()
void ~SlotsIcon ()
Static Private Member Functions
static int GetNormalHeight ()
static int GetNormalWidth ()
Private Attributes
protected Widget m_AmmoIcon
protected Widget m_ColorWidget
protected Widget m_ColWidget
protected Container m_Container
protected float m_CurrQuantity = -1
protected Widget m_CursorWidget
protected Widget m_EmptySelectedPanel
protected ImageWidget m_GhostSlot
protected bool m_HasItemSize = false
protected bool m_HasQuantity = false
protected bool m_HasTemperature = false
protected bool m_IsDragged = false
protected bool m_IsMagazine = false
protected bool m_IsWeapon = false
protected ItemBase m_Item
protected ItemPreviewWidget m_ItemPreview
protected Widget m_ItemSizePanel
protected TextWidget m_ItemSizeWidget
protected Widget m_MountedWidget
protected EntityAI m_Obj
protected Widget m_OutOfReachWidget
protected Widget m_PanelWidget
protected TextWidget m_QuantityItem
protected Widget m_QuantityPanel
protected ProgressBarWidget m_QuantityProgress
protected Widget m_QuantityStack
protected Widget m_RadialIcon
protected Widget m_RadialIconClosed
protected Widget m_RadialIconPanel
protected bool m_Reserved
protected Widget m_ReservedWidget
protected Widget m_SelectedPanel
protected string m_SlotDesc
protected string m_SlotDisplayName
protected int m_SlotID
protected EntityAI m_SlotParent
Static Private Attributes
static protected int m_NormalHeight
static protected int m_NormalWidth
Detailed Description
Definition at line 1 of file slotsicon.c.
Constructor & Destructor Documentation
SlotsIcon()
void SlotsIcon::SlotsIcon (LayoutHolder parent, Widget root, int index, EntityAI slot_parent) inline private
Definition at line 54 of file slotsicon.c.
    {
        m_MainWidget            = root;
        m_PanelWidget           = m_MainWidget.FindAnyWidget( "PanelWidget" + index );
        m_CursorWidget          = m_MainWidget.FindAnyWidget( "Cursor" + index );
        m_ColWidget             = m_MainWidget.FindAnyWidget( "Col" + index );
        m_MountedWidget         = m_MainWidget.FindAnyWidget( "Mounted" + index );
        m_OutOfReachWidget      = m_MainWidget.FindAnyWidget( "OutOfReach" + index );
        m_ItemPreview           = ItemPreviewWidget.Cast( m_MainWidget.FindAnyWidget( "Render" + index ) );
        m_ItemPreview.SetForceFlipEnable(true);
        m_ItemPreview.SetForceFlip(false);
        m_GhostSlot             = ImageWidget.Cast( m_MainWidget.FindAnyWidget( "GhostSlot" + index ) );
        m_ColorWidget           = m_MainWidget.FindAnyWidget( "Color" + index );
        m_SelectedPanel         = m_MainWidget.FindAnyWidget( "Selected" + index );
        m_EmptySelectedPanel    = m_MainWidget.FindAnyWidget( "EmptySelected" + index );
        m_QuantityPanel         = m_MainWidget.FindAnyWidget( "QuantityPanel" + index );
        m_QuantityItem          = TextWidget.Cast( m_MainWidget.FindAnyWidget( "Quantity" + index ) );
        m_QuantityProgress      = ProgressBarWidget.Cast( m_MainWidget.FindAnyWidget( "QuantityBar" + index ) );
        m_QuantityStack         = m_MainWidget.FindAnyWidget( "QuantityStackPanel" + index );
        m_ItemSizePanel         = m_MainWidget.FindAnyWidget( "ItemSizePanel" + index );
        m_ItemSizeWidget        = TextWidget.Cast( m_MainWidget.FindAnyWidget( "ItemSize" + index ) );
        m_AmmoIcon              = m_MainWidget.FindAnyWidget( "AmmoIcon" + index );
        m_RadialIconPanel       = m_MainWidget.FindAnyWidget( "RadialIconPanel" + index );
        m_RadialIconClosed      = m_MainWidget.FindAnyWidget( "RadialIconClosed" + index );
        m_RadialIcon            = m_MainWidget.FindAnyWidget( "RadialIcon" + index );
        m_ReservedWidget = Widget.Cast( GetGame().GetWorkspace().CreateWidgets( "gui/layouts/inventory_new/reserved_icon.layout", m_MainWidget ) );
        m_ReservedWidget.Show(false);
        WidgetEventHandler.GetInstance().RegisterOnMouseEnter( m_PanelWidget,  this, "MouseEnter" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_PanelWidget,  this, "MouseLeave" );
        WidgetEventHandler.GetInstance().RegisterOnMouseEnter( m_GhostSlot,  this, "MouseEnterGhostSlot" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_GhostSlot,  this, "MouseLeaveGhostSlot" );
        WidgetEventHandler.GetInstance().RegisterOnMouseEnter( m_RadialIconPanel,  this, "MouseEnterCategory" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_RadialIconPanel,  this, "MouseLeaveCategory" );
        WidgetEventHandler.GetInstance().RegisterOnDrag( m_PanelWidget, this, "OnIconDrag" );
        WidgetEventHandler.GetInstance().RegisterOnDrop( m_PanelWidget, this, "OnIconDrop" );
        //WidgetEventHandler.GetInstance().RegisterOnMouseEnter( m_ReservedWidget,  this, "MouseEnter" );
        //WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_ReservedWidget,  this, "MouseLeave" );
        m_Reserved              = false;
        m_SlotID                = -1;
        m_Item                  = null;
        m_Obj                   = null;
        m_Container             = null;
        m_SlotParent            = slot_parent;
        m_PanelWidget.SetUserData(this);
        m_ItemPreview.SetUserData(this);
        m_GhostSlot.SetUserData(this);
        m_MainWidget.SetUserData(this);
        float w,h;
        root.GetSize(w,h);
        m_NormalWidth = w;
        m_NormalHeight = h;
        SetActive( false );
    }
References GetGame(), WidgetEventHandler::GetInstance(), m_AmmoIcon, m_ColorWidget, m_ColWidget, m_Container, m_CursorWidget, m_EmptySelectedPanel, m_GhostSlot, m_Item, m_ItemPreview, m_ItemSizePanel, m_ItemSizeWidget, m_MountedWidget, m_NormalHeight, m_NormalWidth, m_Obj, m_OutOfReachWidget, m_PanelWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_RadialIcon, m_RadialIconClosed, m_RadialIconPanel, m_Reserved, m_ReservedWidget, m_SelectedPanel, m_SlotID, m_SlotParent, WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnMouseEnter(), WidgetEventHandler::RegisterOnMouseLeave(), SetActive(), ItemPreviewWidget::SetForceFlip(), and ItemPreviewWidget::SetForceFlipEnable().
~SlotsIcon()
void SlotsIcon::~SlotsIcon () inline private
Definition at line 169 of file slotsicon.c.
    {
        if (m_IsDragged)
        {
            m_IsDragged = false;
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().SetIsDragging( false );
        }
        if (m_Obj)
        {
            m_Obj.GetOnItemFlipped().Remove( UpdateFlip );
            m_Obj.GetOnViewIndexChanged().Remove( SetItemPreview );
        }
    }
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_IsDragged, m_Obj, ItemManager::SetIsDragging(), SetItemPreview(), and UpdateFlip().
Member Function Documentation
CheckHasItemSize()
void SlotsIcon::CheckHasItemSize () inline private
Definition at line 597 of file slotsicon.c.
    {
        #ifdef PLATFORM_CONSOLE
        string config = "CfgVehicles " + m_Obj.GetType() + " GUIInventoryAttachmentsProps";
        m_HasItemSize = ( InventoryItem.Cast( m_Obj ) && !GetGame().ConfigIsExisting( config ) );
        #else
        m_HasItemSize = false;
        #endif
    }
References CGame::ConfigIsExisting(), GetGame(), m_HasItemSize, and m_Obj.
Referenced by Init().
CheckHasQuantity()
void SlotsIcon::CheckHasQuantity () inline private
Definition at line 585 of file slotsicon.c.
    {
        if( m_Item )
        {
            m_HasQuantity = ( QuantityConversions.HasItemQuantity( m_Item ) != QUANTITY_HIDDEN );
            if( m_HasQuantity )
            {
                m_QuantityPanel.Show( true );
            }
        }
    }
References QuantityConversions::HasItemQuantity(), m_HasQuantity, m_Item, m_QuantityPanel, and QUANTITY_HIDDEN.
Referenced by Init().
CheckHasTemperature()
void SlotsIcon::CheckHasTemperature () inline private
Definition at line 577 of file slotsicon.c.
    {
        if( m_Item )
        {
            m_HasTemperature = ( m_Item.GetTemperatureMax() != 0 && m_Item.GetTemperatureMin() != 0 );
        }
    }
References m_HasTemperature, and m_Item.
Referenced by Init().
CheckIsMagazine()
void SlotsIcon::CheckIsMagazine () inline private
Definition at line 572 of file slotsicon.c.
    {
        m_IsMagazine = ( Magazine.Cast( m_Obj ) != null );
    }
References m_IsMagazine, and m_Obj.
Referenced by Init().
CheckIsWeapon()
void SlotsIcon::CheckIsWeapon () inline private
Definition at line 567 of file slotsicon.c.
    {
        m_IsWeapon = ( Weapon_Base.Cast( m_Obj ) != null );
    }
References m_IsWeapon, and m_Obj.
Referenced by Init().
Clear()
void SlotsIcon::Clear () inline private
Definition at line 502 of file slotsicon.c.
    {
        if (m_IsDragged)
        {
            OnIconDrop(m_PanelWidget);
            Widget a = CancelWidgetDragging();
            ItemManager.GetInstance().SetWidgetDraggable( a, false );
        }
        if( m_Obj )
        {
            m_Obj.GetOnItemFlipped().Remove( UpdateFlip );
            m_Obj.GetOnViewIndexChanged().Remove( SetItemPreview );
            HideOwnedTooltip();
        }
        m_Obj = null;
        m_Item = null;
        m_Container = null;
        m_ItemPreview.Show( false );
        m_ItemPreview.SetItem( null );
        m_CurrQuantity = -1;
        m_IsWeapon = false;
        m_IsMagazine = false;
        m_HasTemperature = false;
        m_HasQuantity = false;
        m_HasItemSize = false;
        m_GhostSlot.Show( true );
        m_AmmoIcon.Show( false );
        m_PanelWidget.Show( false );
        m_RadialIconPanel.Show( false );
        m_QuantityPanel.Show( false );
        if(GetSlotID() != -1)
        {
            int stack_max = InventorySlots.GetStackMaxForSlotId( GetSlotID() );
            if(stack_max > 1)
            {
                m_QuantityPanel.Show( true );
                m_QuantityItem.SetText( string.Format("0/%1", stack_max.ToString()) );
                m_QuantityStack.Show( true );
                m_QuantityProgress.Show( false );
                m_PanelWidget.Show( true );
                m_ItemPreview.Show( true );
            }
        }
        m_ColWidget.Show( false );
        m_SelectedPanel.Show( false );
        m_EmptySelectedPanel.Show( false );
        m_MountedWidget.Show( false );
        m_OutOfReachWidget.Show( false );
        m_ReservedWidget.Show( false );
        if( m_ItemSizePanel )
            m_ItemSizePanel.Show( false );
        if( m_ColorWidget )
            m_ColorWidget.Show( false );
        Refresh();
    }
References CancelWidgetDragging(), ItemManager::GetInstance(), GetSlotID(), InventorySlots::GetStackMaxForSlotId(), m_AmmoIcon, m_ColorWidget, m_ColWidget, m_Container, m_CurrQuantity, m_EmptySelectedPanel, m_GhostSlot, m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsDragged, m_IsMagazine, m_IsWeapon, m_Item, m_ItemPreview, m_ItemSizePanel, m_MountedWidget, m_Obj, m_OutOfReachWidget, m_PanelWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_RadialIconPanel, m_ReservedWidget, m_SelectedPanel, OnIconDrop(), Refresh(), ItemPreviewWidget::SetItem(), SetItemPreview(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
Referenced by Attachments::AttachmentRemoved(), Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), Attachments::OnAttachmentReservationRelease(), PlayerContainer::OnAttachmentReservationRelease(), PlayerContainer::PlayerContainer(), AttachmentCategoriesRow::RefreshSlot(), PlayerContainer::SetPlayer(), and VicinitySlotsContainer::ShowItemsInContainers().
GetAmmoIcon()
Widget SlotsIcon::GetAmmoIcon () inline private
Definition at line 290 of file slotsicon.c.
    {
        return m_AmmoIcon;
    }
References m_AmmoIcon.
GetColorWidget()
Widget SlotsIcon::GetColorWidget () inline private
Definition at line 240 of file slotsicon.c.
    {
        return m_ColorWidget;
    }
References m_ColorWidget.
GetColWidget()
Widget SlotsIcon::GetColWidget () inline private
Definition at line 215 of file slotsicon.c.
    {
        return m_ColWidget;
    }
References m_ColWidget.
GetContainer()
Container SlotsIcon::GetContainer () inline private
Definition at line 149 of file slotsicon.c.
    {
        return m_Container;
    }
References m_Container.
Referenced by AttachmentCategoriesContainer::ExpandCollapseContainer(), AttachmentCategoriesContainer::MouseClick(), AttachmentCategoriesRow::OnMouseButtonDown(), and ZombieContainer::ToggleContainer().
GetCursorWidget()
Widget SlotsIcon::GetCursorWidget () inline private
Definition at line 210 of file slotsicon.c.
    {
        return m_CursorWidget;
    }
References m_CursorWidget.
Referenced by Attachments::SelectItem(), SlotsContainer::SelectItem(), and SlotsContainer::UpdateIcon().
GetEmptySelectedPanel()
Widget SlotsIcon::GetEmptySelectedPanel () inline private
Definition at line 250 of file slotsicon.c.
    {
        return m_EmptySelectedPanel;
    }
References m_EmptySelectedPanel.
GetEntity()
EntityAI SlotsIcon::GetEntity () inline private
Definition at line 353 of file slotsicon.c.
    {
        return EntityAI.Cast( m_Obj );
    }
References m_Obj.
Referenced by PlayerContainer::DraggingOver(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), AttachmentCategoriesRow::RefreshSlot(), PlayerContainer::Select(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), ZombieContainer::ToggleContainer(), and Attachments::UpdateInterval().
GetGhostSlot()
ImageWidget SlotsIcon::GetGhostSlot () inline private
Definition at line 235 of file slotsicon.c.
    {
        return m_GhostSlot;
    }
References m_GhostSlot.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
GetItem()
ItemBase SlotsIcon::GetItem () inline private
Definition at line 358 of file slotsicon.c.
    {
        return m_Item;
    }
References m_Item.
Referenced by AttachmentCategoriesRow::OnMouseButtonDown().
GetItemSizePanel()
Widget SlotsIcon::GetItemSizePanel () inline private
Definition at line 280 of file slotsicon.c.
    {
        return m_ItemSizePanel;
    }
References m_ItemSizePanel.
GetItemSizeWidget()
TextWidget SlotsIcon::GetItemSizeWidget () inline private
Definition at line 285 of file slotsicon.c.
    {
        return m_ItemSizeWidget;
    }
References m_ItemSizeWidget.
GetMountedWidget()
Widget SlotsIcon::GetMountedWidget () inline private
Definition at line 225 of file slotsicon.c.
    {
        return m_MountedWidget;
    }
References m_MountedWidget.
Referenced by AttachmentCategoriesRow::RefreshSlot(), and Attachments::UpdateInterval().
GetNormalHeight()
static int SlotsIcon::GetNormalHeight () inline static private
Definition at line 758 of file slotsicon.c.
    {
        return m_NormalHeight;
    }
References m_NormalHeight.
Referenced by ItemManager::CalculateTooltipSlotPosition().
GetNormalWidth()
static int SlotsIcon::GetNormalWidth () inline static private
Definition at line 753 of file slotsicon.c.
    {
        return m_NormalWidth;
    }
References m_NormalWidth.
Referenced by ItemManager::CalculateTooltipSlotPosition().
GetObject()
Object SlotsIcon::GetObject () inline private
Definition at line 348 of file slotsicon.c.
    {
        return m_Obj;
    }
References m_Obj.
Referenced by AttachmentCategoriesContainer::Close(), SlotsContainer::GetFocusedItem(), RefreshMuzzleIcon(), and SetActive().
GetOutOfReachWidget()
Widget SlotsIcon::GetOutOfReachWidget () inline private
Definition at line 260 of file slotsicon.c.
    {
        return m_OutOfReachWidget;
    }
References m_OutOfReachWidget.
Referenced by AttachmentCategoriesRow::RefreshSlot(), and Attachments::UpdateInterval().
GetPanelWidget()
Widget SlotsIcon::GetPanelWidget () inline private
Definition at line 205 of file slotsicon.c.
    {
        return m_PanelWidget;
    }
References m_PanelWidget.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), VicinitySlotsContainer::ShowItemsInContainers(), UpdateFlip(), Attachments::UpdateInterval(), and VicinitySlotsContainer::VicinitySlotsContainer().
GetQuantityItem()
TextWidget SlotsIcon::GetQuantityItem () inline private
Definition at line 265 of file slotsicon.c.
    {
        return m_QuantityItem;
    }
References m_QuantityItem.
GetQuantityPanel()
Widget SlotsIcon::GetQuantityPanel () inline private
Definition at line 255 of file slotsicon.c.
    {
        return m_QuantityPanel;
    }
References m_QuantityPanel.
GetQuantityProgress()
ProgressBarWidget SlotsIcon::GetQuantityProgress () inline private
Definition at line 270 of file slotsicon.c.
    {
        return m_QuantityProgress;
    }
References m_QuantityProgress.
GetQuantityStack()
Widget SlotsIcon::GetQuantityStack () inline private
Definition at line 275 of file slotsicon.c.
    {
        return m_QuantityStack;
    }
References m_QuantityStack.
GetRadialIcon()
Widget SlotsIcon::GetRadialIcon () inline private
Definition at line 305 of file slotsicon.c.
    {
        return m_RadialIcon;
    }
References m_RadialIcon.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), ZombieContainer::InitGhostSlots(), ZombieContainer::ItemAttached(), and LayoutHolder::SetOpenForSlotIcon().
GetRadialIconClosed()
Widget SlotsIcon::GetRadialIconClosed () inline private
Definition at line 300 of file slotsicon.c.
    {
        return m_RadialIconClosed;
    }
References m_RadialIconClosed.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), and ZombieContainer::ItemAttached().
GetRadialIconPanel()
Widget SlotsIcon::GetRadialIconPanel () inline private
Definition at line 295 of file slotsicon.c.
    {
        return m_RadialIconPanel;
    }
References m_RadialIconPanel.
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), AttachmentCategoriesRow::RefreshSlot(), VicinitySlotsContainer::ShowItemsInContainers(), and LayoutHolder::UpdateRadialIcon().
GetRender()
ItemPreviewWidget SlotsIcon::GetRender () inline private
Definition at line 230 of file slotsicon.c.
    {
        return m_ItemPreview;
    }
References m_ItemPreview.
Referenced by AttachmentCategoriesSlotsContainer::GetFocusedItem(), AttachmentCategoriesRow::RefreshSlot(), and VicinitySlotsContainer::ShowItemsInContainers().
GetReservedWidget()
Widget SlotsIcon::GetReservedWidget () inline private
Definition at line 220 of file slotsicon.c.
    {
        return m_ReservedWidget;
    }
References m_ReservedWidget.
GetSelectedPanel()
Widget SlotsIcon::GetSelectedPanel () inline private
Definition at line 245 of file slotsicon.c.
    {
        return m_SelectedPanel;
    }
References m_SelectedPanel.
GetSlotDesc()
string SlotsIcon::GetSlotDesc () inline private
Definition at line 164 of file slotsicon.c.
    {
        return m_SlotDesc;
    }
References m_SlotDesc.
Referenced by SlotsContainer::UpdateIcon().
GetSlotDisplayName()
string SlotsIcon::GetSlotDisplayName () inline private
Definition at line 154 of file slotsicon.c.
    {
        return m_SlotDisplayName;
    }
References m_SlotDisplayName.
Referenced by SlotsContainer::UpdateIcon().
GetSlotID()
int SlotsIcon::GetSlotID () inline private
Definition at line 190 of file slotsicon.c.
    {
        return m_SlotID;
    }
References m_SlotID.
Referenced by Clear(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), Attachments::GetFocusedSlot(), AttachmentCategoriesRow::GetFocusedSlot(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), AttachmentCategoriesRow::RefreshSlot(), Attachments::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
GetSlotParent()
EntityAI SlotsIcon::GetSlotParent () inline private
Definition at line 185 of file slotsicon.c.
    {
        return m_SlotParent;
    }
References m_SlotParent.
Referenced by HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), ClosableContainer::MouseClick2(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
Init()
void SlotsIcon::Init (EntityAI obj, bool reservation = false) inline private
Definition at line 460 of file slotsicon.c.
    {
        if( m_Obj != obj )
        {
            Clear();
            m_Obj   = obj;
            m_Item  = ItemBase.Cast( m_Obj );
            m_Obj.GetOnItemFlipped().Insert( UpdateFlip );
            m_Obj.GetOnViewIndexChanged().Insert( SetItemPreview );
            m_Reserved = reservation;
            m_Container = null;
            if(reservation)
            {
                ItemManager.GetInstance().SetWidgetDraggable( m_PanelWidget, false );
                m_IsWeapon = false;
                m_IsMagazine = false;
                m_HasTemperature = false;
                m_HasQuantity = false;
                m_HasItemSize = false;
            }
            else
            {
                CheckIsWeapon();
                CheckIsMagazine();
                CheckHasTemperature();
                CheckHasQuantity();
                CheckHasItemSize();
            }
            m_ReservedWidget.Show(reservation);
            SetItemPreview();
            m_GhostSlot.Show( false );
            m_PanelWidget.Show( true );
            Refresh();
        }
    }
References CheckHasItemSize(), CheckHasQuantity(), CheckHasTemperature(), CheckIsMagazine(), CheckIsWeapon(), Clear(), ItemManager::GetInstance(), m_Container, m_GhostSlot, m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsMagazine, m_IsWeapon, m_Item, m_Obj, m_PanelWidget, m_Reserved, m_ReservedWidget, Refresh(), SetItemPreview(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
Referenced by Attachments::AttachmentAdded(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), Attachments::OnAttachmentReservationSet(), PlayerContainer::OnAttachmentReservationSet(), AttachmentCategoriesRow::RefreshSlot(), and VicinitySlotsContainer::ShowItemsInContainers().
IsOutOfReach()
bool SlotsIcon::IsOutOfReach () inline private
Definition at line 607 of file slotsicon.c.
    {
        bool oot = ( m_OutOfReachWidget.IsVisible() || m_MountedWidget.IsVisible() );
        return oot;
    }
References m_MountedWidget, and m_OutOfReachWidget.
Referenced by AttachmentCategoriesRow::CanCombine(), AttachmentCategoriesRow::Combine(), AttachmentCategoriesRow::IsItemActive(), AttachmentCategoriesRow::IsItemWithQuantityActive(), MouseEnter(), Attachments::Select(), AttachmentCategoriesRow::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), Attachments::SelectItem(), SlotsContainer::SelectItem(), AttachmentCategoriesRow::TransferItem(), and AttachmentCategoriesRow::TransferItemToVicinity().
IsReserved()
bool SlotsIcon::IsReserved () inline private
Definition at line 200 of file slotsicon.c.
    {
        return m_Reserved;
    }
References m_Reserved.
Referenced by ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), PlayerContainer::DraggingOver(), ClosableContainer::DraggingOverHeader(), PlayerContainer::ItemAttached(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), PlayerContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), Attachments::Select(), PlayerContainer::Select(), SlotsContainer::SelectItem(), ClosableContainer::TakeAsAttachment(), and Attachments::UpdateInterval().
IsVisible()
override bool SlotsIcon::IsVisible () inline private
Definition at line 129 of file slotsicon.c.
    {
        return m_MainWidget.IsVisible();
    }
Referenced by SlotsContainer::GetVisibleFocus(), AttachmentCategoriesContainer::OnHide(), SlotsContainer::SetDefaultFocus(), SlotsContainer::SetNextLeftActive(), SlotsContainer::SetNextRightActive(), and SlotsContainer::SetVisibleFocus().
MouseEnter()
bool SlotsIcon::MouseEnter (Widget w, int x, int y) inline private
Definition at line 613 of file slotsicon.c.
    {
        if( m_Reserved )
            return MouseEnterGhostSlot(w, x, y);
        PrepareOwnedTooltip( m_Item, x, y );
        if( GetDragWidget() != m_PanelWidget && !IsOutOfReach() )
        {
            m_SelectedPanel.Show( true );
        }
        return true;
    }
References GetDragWidget(), IsOutOfReach(), m_Item, m_PanelWidget, m_Reserved, m_SelectedPanel, MouseEnterGhostSlot(), x, and y.
MouseEnterGhostSlot()
bool SlotsIcon::MouseEnterGhostSlot (Widget w, int x, int y) inline private
Definition at line 626 of file slotsicon.c.
    {
        float pos_x, pos_y;
        m_MainWidget.GetScreenPos(pos_x, pos_y);
        x = pos_x;
        y = pos_y;
        PrepareOwnedSlotsTooltip( m_MainWidget, m_SlotDisplayName, m_SlotDesc, x, y );
        if( GetDragWidget() != m_PanelWidget )
        {
            m_EmptySelectedPanel.Show( true );
        }
        return true;
    }
References GetDragWidget(), m_EmptySelectedPanel, m_PanelWidget, m_SlotDesc, m_SlotDisplayName, x, and y.
Referenced by MouseEnter().
MouseLeave()
bool SlotsIcon::MouseLeave (Widget w, Widget s, int x, int y) inline private
Definition at line 644 of file slotsicon.c.
    {
        if( m_Reserved )
            return MouseLeaveGhostSlot(w, s, x, y);
        HideOwnedTooltip();
        if( GetDragWidget() != m_PanelWidget )
        {
            m_SelectedPanel.Show( false );
        }
        return true;
    }
References GetDragWidget(), m_PanelWidget, m_Reserved, m_SelectedPanel, MouseLeaveGhostSlot(), x, and y.
MouseLeaveGhostSlot()
bool SlotsIcon::MouseLeaveGhostSlot (Widget w, Widget s, int x, int y) inline private
Definition at line 657 of file slotsicon.c.
    {
        HideOwnedSlotsTooltip();
        if( GetDragWidget() != m_PanelWidget )
        {
            m_EmptySelectedPanel.Show( false );
        }
        return true;
    }
References GetDragWidget(), m_EmptySelectedPanel, and m_PanelWidget.
Referenced by MouseLeave().
OnIconDrag()
void SlotsIcon::OnIconDrag (Widget w) inline private
Definition at line 684 of file slotsicon.c.
    {
        if(!m_Obj || !w)
        {
            return;
        }
        ItemManager.GetInstance().HideDropzones();
        if( m_Obj.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
        {
            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
        }
        else
        {
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
        }
        ItemManager.GetInstance().SetIsDragging( true );
        int icon_x, icon_y;
        float icon_size, y;
        int m_sizeX, m_sizeY;
        if( m_Item )
        {
            GetGame().GetInventoryItemSize( m_Item, icon_x, icon_y );
            CargoContainer c_parent = CargoContainer.Cast( m_Parent );
            HandsPreview h_parent = HandsPreview.Cast( m_Parent );
            if( GetRoot().m_MainWidget.FindAnyWidget( "HandsPanel" ) )
            {
                GetRoot().m_MainWidget.FindAnyWidget( "HandsPanel" ).GetScreenSize( icon_size, y );
            }
            icon_size = icon_size / 10;
            w.SetFlags( WidgetFlags.EXACTSIZE );
            m_ItemPreview.SetForceFlipEnable(false);
            if( !m_Item.GetInventory().GetFlipCargo() )
            {
                w.SetSize( icon_x * icon_size , icon_y * icon_size );
            }
            else
            {
                w.SetSize( icon_y * icon_size , icon_x * icon_size );
            }
            m_ColWidget.Show( true );
            m_SelectedPanel.Show( true );
            ItemManager.GetInstance().SetDraggedItem( m_Item );
        }
        m_IsDragged = true;
    }
References GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ItemManager::HideDropzones(), m_ColWidget, m_IsDragged, m_Item, m_ItemPreview, m_Obj, m_Parent, m_SelectedPanel, ItemManager::SetDraggedItem(), ItemPreviewWidget::SetForceFlipEnable(), ItemManager::SetIsDragging(), and y.
OnIconDrop()
void SlotsIcon::OnIconDrop (Widget w) inline private
Definition at line 739 of file slotsicon.c.
    {
        m_IsDragged = false;
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        w.ClearFlags( WidgetFlags.EXACTSIZE );
        w.SetSize( 1, 1 );
        m_ColWidget.Show( false );
        m_SelectedPanel.Show( false );
        m_EmptySelectedPanel.Show( false );
        m_SelectedPanel.SetColor( ARGBF( 1, 1, 1, 1 ) );
        m_ItemPreview.SetForceFlipEnable(true);
    }
References ARGBF(), ItemManager::GetInstance(), ItemManager::HideDropzones(), m_ColWidget, m_EmptySelectedPanel, m_IsDragged, m_ItemPreview, m_SelectedPanel, ItemPreviewWidget::SetForceFlipEnable(), and ItemManager::SetIsDragging().
Referenced by Clear().
Refresh()
override void SlotsIcon::Refresh () inline private
Definition at line 333 of file slotsicon.c.
    {
        if( m_HasTemperature )
            SetTemperature();
        if( m_IsWeapon )
            RefreshMuzzleIcon();
        if( m_HasQuantity )
            SetQuantity();
    }
References m_HasQuantity, m_HasTemperature, m_IsWeapon, RefreshMuzzleIcon(), SetQuantity(), and SetTemperature().
Referenced by Clear(), Init(), and AttachmentCategoriesRow::RefreshSlot().
RefreshMuzzleIcon()
void SlotsIcon::RefreshMuzzleIcon () inline private
Definition at line 363 of file slotsicon.c.
    {
        Weapon_Base wpn = Weapon_Base.Cast( GetObject() );
        if( wpn )
        {
            if( wpn.IsShowingChamberedBullet() )
            {
                int mi = wpn.GetCurrentMuzzle();
                m_AmmoIcon.Show( wpn.IsChamberFull( mi ) );
            }
            else
            {
                m_AmmoIcon.Show( false );
            }
        }
    }
References GetObject(), Weapon_Base::IsShowingChamberedBullet(), and m_AmmoIcon.
Referenced by Refresh(), and UpdateInterval().
SetActive()
override void SlotsIcon::SetActive (bool active) inline private
Definition at line 310 of file slotsicon.c.
    {
        super.SetActive( active );
        float x, y;
        if( active && GetObject() )
        {
            GetMainWidget().GetScreenPos( x, y );
            PrepareOwnedTooltip( EntityAI.Cast( GetObject() ), x, y );
        }
        else if (active)
        {
            GetMainWidget().GetScreenPos( x, y );
            PrepareOwnedSlotsTooltip( GetMainWidget(), m_SlotDisplayName, m_SlotDesc, x, y );
        }
        m_SelectedPanel.Show( active );
    }
References GetObject(), m_SelectedPanel, m_SlotDesc, m_SlotDisplayName, x, and y.
SetContainer()
void SlotsIcon::SetContainer (Container container) inline private
Definition at line 139 of file slotsicon.c.
    {
        m_Container = container;
    }
References m_Container.
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), and AttachmentCategoriesRow::RefreshSlot().
SetItemPreview()
void SlotsIcon::SetItemPreview () inline private
Definition at line 430 of file slotsicon.c.
    {
        m_ItemPreview.Show( true );
        m_ItemPreview.SetItem( EntityAI.Cast( m_Obj ) );
        m_ItemPreview.SetModelOrientation( "0 0 0" );
        m_ItemPreview.SetView( m_Obj.GetViewIndex() );
    }
References m_ItemPreview, m_Obj, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
Referenced by Clear(), Init(), and ~SlotsIcon().
SetItemSize()
void SlotsIcon::SetItemSize () inline private
Definition at line 438 of file slotsicon.c.
    {
        if( m_HasItemSize )
        {
            int size_x, size_y;
            GetGame().GetInventoryItemSize( InventoryItem.Cast( m_Obj ), size_x, size_y );
            m_ItemSizePanel.Show( true );
            m_ItemSizeWidget.SetText( ( size_x * size_y ).ToString() );
        }
    }
References GetGame(), CGame::GetInventoryItemSize(), m_HasItemSize, m_ItemSizePanel, m_ItemSizeWidget, m_Obj, and ToString().
Referenced by UpdateInterval().
SetLayoutName()
override void SlotsIcon::SetLayoutName () inline private
Definition at line 328 of file slotsicon.c.
    {
        m_LayoutName = "";
    }
SetQuantity()
void SlotsIcon::SetQuantity () inline private
Definition at line 381 of file slotsicon.c.
    {
        if (m_Item)
        {
            int quantityType = QuantityConversions.HasItemQuantity(m_Item);
            if (quantityType != QUANTITY_HIDDEN && m_CurrQuantity != QuantityConversions.GetItemQuantity(m_Item))
            {
                m_CurrQuantity = QuantityConversions.GetItemQuantity(m_Item);
                if (quantityType == QUANTITY_COUNT)
                {
                    string q_text = QuantityConversions.GetItemQuantityText(m_Item, true);
                    if (QuantityConversions.GetItemQuantityMax(m_Item) == 1 || q_text == "")
                    {
                        m_QuantityStack.Show(false);
                    }
                    else
                    {
                        m_QuantityItem.SetText(q_text);
                        m_QuantityStack.Show(true);
                    }
                    m_QuantityProgress.Show(false);
                }
                else if (quantityType == QUANTITY_PROGRESS)
                {
                    float progress_max  = m_QuantityProgress.GetMax();
                    int max             = m_Item.GetQuantityMax();
                    int count           = m_Item.ConfigGetInt("count");
                    float quantity      = m_CurrQuantity;
                    if (count > 0)
                    {
                        max = count;
                    }
                    if (max > 0)
                    {
                        float value = Math.Round((quantity / max) * 100);
                        m_QuantityProgress.SetCurrent(value);
                    }
                    m_QuantityStack.Show(false);
                    m_QuantityProgress.Show(true);
                }
            }
        }
    }
References QuantityConversions::GetItemQuantity(), QuantityConversions::GetItemQuantityMax(), QuantityConversions::GetItemQuantityText(), QuantityConversions::HasItemQuantity(), m_CurrQuantity, m_Item, m_QuantityItem, m_QuantityProgress, m_QuantityStack, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, and Math::Round().
Referenced by Refresh(), and UpdateInterval().
SetSlotDesc()
void SlotsIcon::SetSlotDesc (string text) inline private
Definition at line 159 of file slotsicon.c.
    {
        m_SlotDesc = text;
    }
References m_SlotDesc.
SetSlotDisplayName()
void SlotsIcon::SetSlotDisplayName (string text) inline private
Definition at line 144 of file slotsicon.c.
    {
        m_SlotDisplayName = text;
    }
References m_SlotDisplayName.
Referenced by Attachments::AttachmentAdded(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), and PlayerContainer::PlayerContainer().
SetSlotID()
void SlotsIcon::SetSlotID (int slot_ID) inline private
Definition at line 195 of file slotsicon.c.
    {
        m_SlotID = slot_ID;
    }
References m_SlotID.
Referenced by Attachments::AttachmentAdded(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), ZombieContainer::InitGhostSlots(), and PlayerContainer::PlayerContainer().
SetSlotParent()
void SlotsIcon::SetSlotParent (EntityAI parent) inline private
Definition at line 134 of file slotsicon.c.
    {
        m_SlotParent = parent;
    }
References m_SlotParent.
Referenced by PlayerContainer::SetPlayer().
SetTemperature()
void SlotsIcon::SetTemperature () inline private
Definition at line 343 of file slotsicon.c.
    {
        ItemManager.GetInstance().SetIconTemperature( EntityAI.Cast( m_Obj ), m_MainWidget );
    }
References ItemManager::GetInstance(), m_Obj, and ItemManager::SetIconTemperature().
Referenced by Refresh(), and UpdateInterval().
UpdateFlip()
void SlotsIcon::UpdateFlip (bool flipped) inline private
Definition at line 450 of file slotsicon.c.
    {
        if( !m_Reserved )
        {
            float x_content, y_content;
            GetPanelWidget().GetScreenSize( x_content, y_content );
            GetPanelWidget().SetSize( y_content, x_content );
        }
    }
References GetPanelWidget(), and m_Reserved.
Referenced by Clear(), Init(), and ~SlotsIcon().
UpdateInterval()
override void SlotsIcon::UpdateInterval () inline private
Definition at line 669 of file slotsicon.c.
    {
        if( m_Item )
        {
            if( m_HasTemperature )
                SetTemperature();
            if( m_IsWeapon )
                RefreshMuzzleIcon();
            if( m_HasQuantity )
                SetQuantity();
            if( m_HasItemSize )
                SetItemSize();
        }
    }
References m_HasItemSize, m_HasQuantity, m_HasTemperature, m_IsWeapon, m_Item, RefreshMuzzleIcon(), SetItemSize(), SetQuantity(), and SetTemperature().
Referenced by VicinitySlotsContainer::ShowItemsInContainers(), Attachments::UpdateInterval(), AttachmentCategoriesContainer::UpdateInterval(), and PlayerContainer::UpdateInterval().
Member Data Documentation
m_AmmoIcon
protected Widget SlotsIcon::m_AmmoIcon private
Definition at line 46 of file slotsicon.c.
Referenced by Clear(), GetAmmoIcon(), RefreshMuzzleIcon(), and SlotsIcon().
m_ColorWidget
protected Widget SlotsIcon::m_ColorWidget private
Definition at line 31 of file slotsicon.c.
Referenced by Clear(), GetColorWidget(), and SlotsIcon().
m_ColWidget
protected Widget SlotsIcon::m_ColWidget private
Definition at line 23 of file slotsicon.c.
Referenced by Clear(), GetColWidget(), OnIconDrag(), OnIconDrop(), and SlotsIcon().
m_Container
protected Container SlotsIcon::m_Container private
Definition at line 16 of file slotsicon.c.
Referenced by Clear(), GetContainer(), Init(), SetContainer(), and SlotsIcon().
m_CurrQuantity
protected float SlotsIcon::m_CurrQuantity = -1 private
Definition at line 11 of file slotsicon.c.
Referenced by Clear(), and SetQuantity().
m_CursorWidget
protected Widget SlotsIcon::m_CursorWidget private
Definition at line 22 of file slotsicon.c.
Referenced by GetCursorWidget(), and SlotsIcon().
m_EmptySelectedPanel
protected Widget SlotsIcon::m_EmptySelectedPanel private
Definition at line 33 of file slotsicon.c.
Referenced by Clear(), GetEmptySelectedPanel(), MouseEnterGhostSlot(), MouseLeaveGhostSlot(), OnIconDrop(), and SlotsIcon().
m_GhostSlot
protected ImageWidget SlotsIcon::m_GhostSlot private
Definition at line 29 of file slotsicon.c.
Referenced by Clear(), GetGhostSlot(), Init(), and SlotsIcon().
m_HasItemSize
protected bool SlotsIcon::m_HasItemSize = false private
Definition at line 10 of file slotsicon.c.
Referenced by CheckHasItemSize(), Clear(), Init(), SetItemSize(), and UpdateInterval().
m_HasQuantity
protected bool SlotsIcon::m_HasQuantity = false private
Definition at line 9 of file slotsicon.c.
Referenced by CheckHasQuantity(), Clear(), Init(), Refresh(), and UpdateInterval().
m_HasTemperature
protected bool SlotsIcon::m_HasTemperature = false private
Definition at line 8 of file slotsicon.c.
Referenced by CheckHasTemperature(), Clear(), Init(), Refresh(), and UpdateInterval().
m_IsDragged
protected bool SlotsIcon::m_IsDragged = false private
Definition at line 18 of file slotsicon.c.
Referenced by Clear(), OnIconDrag(), OnIconDrop(), and ~SlotsIcon().
m_IsMagazine
protected bool SlotsIcon::m_IsMagazine = false private
Definition at line 7 of file slotsicon.c.
Referenced by CheckIsMagazine(), Clear(), and Init().
m_IsWeapon
protected bool SlotsIcon::m_IsWeapon = false private
Definition at line 6 of file slotsicon.c.
Referenced by CheckIsWeapon(), Clear(), Init(), Refresh(), and UpdateInterval().
m_Item
protected ItemBase SlotsIcon::m_Item private
Definition at line 14 of file slotsicon.c.
Referenced by CheckHasQuantity(), CheckHasTemperature(), Clear(), GetItem(), Init(), MouseEnter(), OnIconDrag(), SetQuantity(), SlotsIcon(), and UpdateInterval().
m_ItemPreview
protected ItemPreviewWidget SlotsIcon::m_ItemPreview private
Definition at line 28 of file slotsicon.c.
Referenced by Clear(), GetRender(), OnIconDrag(), OnIconDrop(), SetItemPreview(), and SlotsIcon().
m_ItemSizePanel
protected Widget SlotsIcon::m_ItemSizePanel private
Definition at line 43 of file slotsicon.c.
Referenced by Clear(), GetItemSizePanel(), SetItemSize(), and SlotsIcon().
m_ItemSizeWidget
protected TextWidget SlotsIcon::m_ItemSizeWidget private
Definition at line 44 of file slotsicon.c.
Referenced by GetItemSizeWidget(), SetItemSize(), and SlotsIcon().
m_MountedWidget
protected Widget SlotsIcon::m_MountedWidget private
Definition at line 24 of file slotsicon.c.
Referenced by Clear(), GetMountedWidget(), IsOutOfReach(), and SlotsIcon().
m_NormalHeight
protected int SlotsIcon::m_NormalHeight static private
Definition at line 4 of file slotsicon.c.
Referenced by GetNormalHeight(), and SlotsIcon().
m_NormalWidth
protected int SlotsIcon::m_NormalWidth static private
Definition at line 3 of file slotsicon.c.
Referenced by GetNormalWidth(), and SlotsIcon().
m_Obj
protected EntityAI SlotsIcon::m_Obj private
Definition at line 13 of file slotsicon.c.
Referenced by CheckHasItemSize(), CheckIsMagazine(), CheckIsWeapon(), Clear(), GetEntity(), GetObject(), Init(), OnIconDrag(), SetItemPreview(), SetItemSize(), SetTemperature(), SlotsIcon(), and ~SlotsIcon().
m_OutOfReachWidget
protected Widget SlotsIcon::m_OutOfReachWidget private
Definition at line 25 of file slotsicon.c.
Referenced by Clear(), GetOutOfReachWidget(), IsOutOfReach(), and SlotsIcon().
m_PanelWidget
protected Widget SlotsIcon::m_PanelWidget private
Definition at line 20 of file slotsicon.c.
Referenced by Clear(), GetPanelWidget(), Init(), MouseEnter(), MouseEnterGhostSlot(), MouseLeave(), MouseLeaveGhostSlot(), and SlotsIcon().
m_QuantityItem
protected TextWidget SlotsIcon::m_QuantityItem private
Definition at line 36 of file slotsicon.c.
Referenced by Clear(), GetQuantityItem(), SetQuantity(), and SlotsIcon().
m_QuantityPanel
protected Widget SlotsIcon::m_QuantityPanel private
Definition at line 35 of file slotsicon.c.
Referenced by CheckHasQuantity(), Clear(), GetQuantityPanel(), and SlotsIcon().
m_QuantityProgress
protected ProgressBarWidget SlotsIcon::m_QuantityProgress private
Definition at line 37 of file slotsicon.c.
Referenced by Clear(), GetQuantityProgress(), SetQuantity(), and SlotsIcon().
m_QuantityStack
protected Widget SlotsIcon::m_QuantityStack private
Definition at line 38 of file slotsicon.c.
Referenced by Clear(), GetQuantityStack(), SetQuantity(), and SlotsIcon().
m_RadialIcon
protected Widget SlotsIcon::m_RadialIcon private
Definition at line 50 of file slotsicon.c.
Referenced by GetRadialIcon(), and SlotsIcon().
m_RadialIconClosed
protected Widget SlotsIcon::m_RadialIconClosed private
Definition at line 49 of file slotsicon.c.
Referenced by GetRadialIconClosed(), and SlotsIcon().
m_RadialIconPanel
protected Widget SlotsIcon::m_RadialIconPanel private
Definition at line 48 of file slotsicon.c.
Referenced by Clear(), GetRadialIconPanel(), and SlotsIcon().
m_Reserved
protected bool SlotsIcon::m_Reserved private
Definition at line 52 of file slotsicon.c.
Referenced by Init(), IsReserved(), MouseEnter(), MouseLeave(), SlotsIcon(), and UpdateFlip().
m_ReservedWidget
protected Widget SlotsIcon::m_ReservedWidget private
Definition at line 26 of file slotsicon.c.
Referenced by Clear(), GetReservedWidget(), Init(), and SlotsIcon().
m_SelectedPanel
protected Widget SlotsIcon::m_SelectedPanel private
Definition at line 32 of file slotsicon.c.
Referenced by Clear(), GetSelectedPanel(), MouseEnter(), MouseLeave(), OnIconDrag(), OnIconDrop(), SetActive(), and SlotsIcon().
m_SlotDesc
protected string SlotsIcon::m_SlotDesc private
Definition at line 41 of file slotsicon.c.
Referenced by GetSlotDesc(), MouseEnterGhostSlot(), SetActive(), and SetSlotDesc().
m_SlotDisplayName
protected string SlotsIcon::m_SlotDisplayName private
Definition at line 40 of file slotsicon.c.
Referenced by GetSlotDisplayName(), MouseEnterGhostSlot(), SetActive(), and SetSlotDisplayName().
m_SlotID
protected int SlotsIcon::m_SlotID private
Definition at line 17 of file slotsicon.c.
Referenced by GetSlotID(), SetSlotID(), and SlotsIcon().
m_SlotParent
protected EntityAI SlotsIcon::m_SlotParent private
Definition at line 15 of file slotsicon.c.
Referenced by GetSlotParent(), SetSlotParent(), and SlotsIcon().