DayzKode: CTObjectFollower Class Reference
CTObjectFollower Class Reference
Private Member Functions
void AddItem (string item)
void CTActor (int index, vector pos, vector orient, string type, array< string > items, string hands_item, CameraToolsMenu parent)
string GetActorType ()
string GetHandsItem ()
array< string > GetItems ()
void Reset ()
void SetHandsItem (string item)
void SetItems (array< string > items)
void ~CTActor ()
Private Attributes
protected string m_HandsItem
protected EntityAI m_HandsItemObj
protected int m_Index
protected TextWidget m_IndexWidget
protected ref array< string > m_Items
protected Widget m_Root
Detailed Description
Definition at line 1 of file ctactor.c.
Constructor & Destructor Documentation
~CTActor()
void CTObjectFollower::~CTActor () inline private
Definition at line 30 of file ctactor.c.
    {
        delete m_FollowerRoot;
    }
Member Function Documentation
AddItem()
void CTObjectFollower::AddItem (string item) inline private
Definition at line 42 of file ctactor.c.
    {
        PlayerBase p = PlayerBase.Cast( m_FollowedObject );
        if( p.GetInventory().CreateAttachment( item ) )
            m_Items.Insert( item );
    }
CTActor()
void CTObjectFollower::CTActor (int index, vector pos, vector orient, string type, array< string > items, string hands_item, CameraToolsMenu parent) inline private
Definition at line 13 of file ctactor.c.
    {
        m_FollowerRoot      = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/camera_tools/event_tracker.layout", null );
        m_FollowerButton    = m_FollowerRoot.FindAnyWidget( "IconPanel" );
        m_IndexWidget       = TextWidget.Cast( m_FollowerRoot.FindAnyWidget( "Text" ) );
        m_Index             = index;
        m_Position          = pos;
        m_Orientation       = orient;
        m_Menu              = parent;
        m_IndexWidget.SetText( m_Index.ToString() );
        m_FollowerRoot.SetHandler( this );
        CreateFollowedObject( type );
        SetHandsItem( hands_item );
        SetItems( items );
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Menu, m_Orientation, m_Position, SetHandsItem(), and SetItems().
Referenced by ScriptedWidgetEventHandler::OnMouseButtonDown().
GetActorType()
string CTObjectFollower::GetActorType () inline private
Definition at line 35 of file ctactor.c.
    {
        if( m_FollowedObject )
            return m_FollowedObject.GetType();
        return "";
    }
GetHandsItem()
string CTObjectFollower::GetHandsItem () inline private
Definition at line 81 of file ctactor.c.
    {
        return m_HandsItem;
    }
References m_HandsItem.
GetItems()
array< string > CTObjectFollower::GetItems () inline private
Definition at line 62 of file ctactor.c.
    {
        return m_Items;
    }
References m_Items.
Referenced by Reset().
Reset()
void CTObjectFollower::Reset () inline private
Definition at line 86 of file ctactor.c.
    {
        string type = m_FollowedObject.GetType();
        DestroyFollowedObject();
        CreateFollowedObject( type );
        SetHandsItem( m_HandsItem );
        SetItems( GetItems() );
    }
References GetItems(), SetHandsItem(), and SetItems().
SetHandsItem()
void CTObjectFollower::SetHandsItem (string item) inline private
Definition at line 67 of file ctactor.c.
    {
        m_HandsItem = item;
        if ( m_HandsItemObj && m_FollowedObject)
        {
            HumanInventory.Cast( m_FollowedObject.GetInventory() ).LocalDestroyEntity( m_HandsItemObj );
            GetGame().ObjectDelete( m_HandsItemObj );
        }
        if (item)
        {
            HumanInventory.Cast( m_FollowedObject.GetInventory() ).CreateInHands( item );
        }
    }
References HumanInventory::CreateInHands(), GetGame(), HumanInventory::LocalDestroyEntity(), and CGame::ObjectDelete().
Referenced by CTActor(), and Reset().
SetItems()
void CTObjectFollower::SetItems (array< string > items) inline private
Definition at line 49 of file ctactor.c.
    {
        m_Items = items;
        PlayerBase p = PlayerBase.Cast( m_FollowedObject );
        if( p )
        {
            foreach( string item : items )
            {
                p.GetInventory().CreateAttachment( item );
            }
        }
    }
Referenced by CTActor(), and Reset().
Member Data Documentation
m_HandsItem
protected string CTObjectFollower::m_HandsItem private
Definition at line 8 of file ctactor.c.
Referenced by GetHandsItem().
m_HandsItemObj
protected EntityAI CTObjectFollower::m_HandsItemObj private
Definition at line 11 of file ctactor.c.
m_Index
protected int CTObjectFollower::m_Index private
Definition at line 3 of file ctactor.c.
m_IndexWidget
protected TextWidget CTObjectFollower::m_IndexWidget private
Definition at line 6 of file ctactor.c.
m_Items
protected ref array<string> CTObjectFollower::m_Items private
Definition at line 9 of file ctactor.c.
Referenced by GetItems().
m_Root
protected Widget CTObjectFollower::m_Root private
Definition at line 5 of file ctactor.c.