DayzKode: PMTF Class Reference
PMTF Class Reference
Private Member Functions
protected ParticleManager CreatePMFixedBlocking (int size)
bool GetManager (int id, out ParticleManager pm)
int InsertManager (ParticleManager pm)
protected void PrintActiveStats ()
protected void PrintPMStats (notnull ParticleManager pm)
Private Attributes
private ref map< int, ref ParticleManager > m_Managers = new map<int, ref ParticleManager>()
Static Private Attributes
static private int PM_CREATED = 0
Detailed Description
Definition at line 1 of file pmtf.c.
Member Function Documentation
CreatePMFixedBlocking()
protected ParticleManager PMTF::CreatePMFixedBlocking (int size) inline private
Definition at line 42 of file pmtf.c.
    {
        return new ParticleManager(new ParticleManagerSettings(size, ParticleManagerSettingsFlags.BLOCKING));
    }
References ParticleManager(), and ParticleManagerSettings().
Referenced by TestCreationSmallBlocking(), PMTPlayback::TestOnePlaying(), and TestOwnership().
GetManager()
bool PMTF::GetManager (int id, out ParticleManager pm) inline private
Definition at line 17 of file pmtf.c.
    {
        return m_Managers.Find(id, pm);
    }
References m_Managers.
Referenced by PMTPlayback::CheckOnePlaying(), and CheckTestEvents().
InsertManager()
int PMTF::InsertManager (ParticleManager pm) inline private
Definition at line 9 of file pmtf.c.
    {
        Assert(m_Managers.Insert(PM_CREATED, pm));
        ++PM_CREATED;
        return PM_CREATED - 1;
    }
References Assert(), m_Managers, and PM_CREATED.
Referenced by TestEvents(), PMTPlayback::TestOnePlaying(), and TestOwnership().
PrintActiveStats()
protected void PMTF::PrintActiveStats () inline private
Definition at line 32 of file pmtf.c.
    {
        Debug.ParticleLog(string.Format(
            "Active ParticleManagers: %1 | Active ParticleSources: %2", ParticleManager.GetStaticActiveCount(), ParticleSource.GetStaticActiveCount()),
        this, "PrintActiveStats");
    }
References ParticleSource::GetStaticActiveCount(), Debug::ParticleLog(), and ParticleManager().
Referenced by TestCleanup().
PrintPMStats()
protected void PMTF::PrintPMStats (notnull ParticleManager pm) inline private
Definition at line 25 of file pmtf.c.
    {
        Debug.ParticleLog(string.Format(
            "Poolsize: %1 | Allocated: %2 | Virtual: %3 | Playing: %4", pm.GetPoolSize(), pm.GetAllocatedCount(), pm.GetVirtualCount(), pm.GetPlayingCount()),
        this, "PrintPMStats", pm);
    }
References Debug::ParticleLog().
Referenced by TestCreationSmallBlocking().
Member Data Documentation
m_Managers
private ref map<int, ref ParticleManager> PMTF::m_Managers = new map<int, ref ParticleManager>() private
Definition at line 4 of file pmtf.c.
Referenced by GetManager(), and InsertManager().
PM_CREATED
private int PMTF::PM_CREATED = 0 static private
Definition at line 3 of file pmtf.c.
Referenced by InsertManager().