DayzKode: float Class Reference
float Class Reference
Private Member Functions
proto string ToString ()
Private Attributes
const float LOWEST = -FLT_MAX
const float MAX = FLT_MAX
const float MIN = FLT_MIN
Detailed Description
Definition at line 90 of file enconvert.c.
Member Function Documentation
ToString()
proto string float::ToString () private
Referenced by HudDebugWinBase::AddValue(), PluginBase::CheckInit(), StatDebugObject::Debug(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PoweredOptic_Base::DoMeasurement(), CAContinuousTransferQuantity::Execute(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), Environment::GetDebugMessage(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), PluginBase::GetHitMessage(), VicinitySlotsContainer::GetItemQuantityText(), QuantityConversions::GetItemQuantityText(), PlayerStatRecord::GetStringOutput(), GetStrValue(), StatDebugObject::GetValue(), ScriptedWidgetEventHandler::GetValueString(), UIScriptedMenu::LateInit(), UIScriptedMenu::NextPrevPage(), InventoryItem::OnAction(), HumanCommandActionCallback::OnAnimationEvent(), UIScriptedMenu::OnClick(), ManBase::OnRPC(), OpenAndSwitchLambda::OnSuccess(), OnUpdate(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), UIScriptedMenu::Refresh(), ScriptedWidgetEventHandler::SetAcceleration(), DebugMonitor::SetBlood(), UIScriptedMenu::SetBlurValue(), ScriptedWidgetEventHandler::SetDOF(), ScriptedWidgetEventHandler::SetEventTime(), ScriptedWidgetEventHandler::SetFOV(), DebugMonitor::SetHealth(), ScriptedWidgetEventHandler::SetInterpTime(), ScriptedWidgetEventHandler::SetItemQuantity(), PluginFileHandler::SetParameterFloat(), Managed::ShowDebugValues(), UIScriptedMenu::ShowItemButtons(), UpdateDamageWidget(), UpdateDistanceWidget(), UIScriptedMenu::UpdateItemInfoQuantity(), UIScriptedMenu::UpdateItemInfoTemperature(), UIPopupScript::UpdateSliderWindForce(), PluginBase::UpdateStatWidget(), and HudDebugWinBase::UpdateValues().
Member Data Documentation
LOWEST
const float float::LOWEST = -FLT_MAX private
Definition at line 94 of file enconvert.c.
Referenced by InventoryItem::AfterStoreLoad(), InitValues(), and TruncateVec().
MAX
const float float::MAX = FLT_MAX private
Definition at line 93 of file enconvert.c.
Referenced by GetMeleeTargetEx(), UniversalTemperatureSourceDebug::GetTemperature(), SendEvent(), and TruncateVec().
MIN
const float float::MIN = FLT_MIN private
Definition at line 92 of file enconvert.c.