DayzKode: ActionSwitchLights Class Reference
ActionSwitchLights Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionSwitchLights ()
override bool CanBeUsedInVehicle ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasTarget ()
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actionswitchlights.c.
Constructor & Destructor Documentation
ActionSwitchLights()
void ActionSwitchLights::ActionSwitchLights () inline private
Definition at line 3 of file actionswitchlights.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_HEADLIGHT;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text              = "#switch_lights";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionSwitchLights::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file actionswitchlights.c.
    {
        HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            Transport trans = vehCommand.GetTransport();
            if ( trans )
            {
                CarScript car;
                if ( Class.CastTo(car, trans) )
                {
                    if ( car.CrewMemberIndex( player ) == DayZPlayerConstants.VEHICLESEAT_DRIVER )
                    {
                        if ( !car.IsScriptedLightsOn() )
{
                            EntityAI neededItem = null;
                            if ( car.IsVitalCarBattery() ) neededItem = car.FindAttachmentBySlotName("CarBattery");
                            if ( car.IsVitalTruckBattery() ) neededItem = car.FindAttachmentBySlotName("TruckBattery");
                            if (neededItem && !neededItem.IsRuined())
{
                                return neededItem.GetCompEM() && neededItem.GetCompEM().GetEnergy() > 0;
                            }
                        }
                        else
{
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), CarScript::IsVitalCarBattery(), and CarScript::IsVitalTruckBattery().
CanBeUsedInVehicle()
override bool ActionSwitchLights::CanBeUsedInVehicle () inline private
Definition at line 81 of file actionswitchlights.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionSwitchLights::CreateConditionComponents () inline private
Definition at line 10 of file actionswitchlights.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionSwitchLights::GetInputType () inline private
Definition at line 16 of file actionswitchlights.c.
    {
        return ToggleLightsActionInput;
    }
HasTarget()
override bool ActionSwitchLights::HasTarget () inline private
Definition at line 21 of file actionswitchlights.c.
    {
        return false;
    }
OnExecuteServer()
override void ActionSwitchLights::OnExecuteServer (ActionData action_data) inline private
Definition at line 64 of file actionswitchlights.c.
    {
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            Transport trans = vehCommand.GetTransport();
            if ( trans )
            {
                CarScript car;
                if ( Class.CastTo(car, trans) )
                {
                    car.ToggleHeadlights();
                }
            }
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.