DayzKode: Grenade_Base Class Reference
Grenade_Base Class Reference
Private Member Functions
protected void Activate ()
void ActivateImmediate ()
void ActivateRandomTime ()
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanExplodeInFire ()
protected override void CreateLight ()
protected void Deactivate ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
protected void ExplodeGrenade (EGrenadeType grenade_type)
DEPRECATED - for backward compatibility only.
void FlashGrenade ()
EGrenadeType GetGrenadeType ()
void Grenade_Base ()
protected override void InitiateExplosion ()
bool IsPinnable ()
bool IsPinned ()
void M67Grenade ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnActivatedByTripWire ()
DEPRECATED use OnActivatedByItem.
protected void OnActivateFinished ()
protected void OnActivateImmediate ()
protected void OnActivateStarted ()
protected void OnDeactivate ()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
protected void OnPin ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
protected void OnUnpin ()
override void OnWasAttached (EntityAI parent, int slot_id)
void Pin ()
void RGD5Grenade ()
override void SetActions ()
void SetFuseDelay (float delay)
void SetGrenadeType (EGrenadeType type)
void SetPinnable (bool state)
void Unpin ()
void ~FlashGrenade ()
void ~M67Grenade ()
void ~RGD5Grenade ()
Private Attributes
protected const float DEFAULT_FUSE_DELAY = 10
const float FX_RANGE_MAX_MULT = 1.0
protected float m_FuseDelay
protected ref Timer m_FuseTimer
protected EGrenadeType m_GrenadeType
protected bool m_Pinnable
protected bool m_Pinned
protected float m_RemainingFuseTime
Detailed Description
Definition at line 1 of file flashgrenade.c.
Constructor & Destructor Documentation
~FlashGrenade()
void Grenade_Base::~FlashGrenade () inline private
Definition at line 92 of file flashgrenade.c.
{}
~M67Grenade()
void Grenade_Base::~M67Grenade () inline private
Definition at line 10 of file m67grenade.c.
{}
~RGD5Grenade()
void Grenade_Base::~RGD5Grenade () inline private
Definition at line 10 of file rgd5grenade.c.
{}
Grenade_Base()
void Grenade_Base::Grenade_Base () inline private
Definition at line 292 of file grenade_base.c.
    {
        m_Pinned            = true;
        m_FuseTimer         = new Timer;
        m_RemainingFuseTime = -1;
        SetPinnable(true);
        SetFuseDelay(DEFAULT_FUSE_DELAY);
        SetGrenadeType(EGrenadeType.FRAGMENTATION);
        RegisterNetSyncVariableBool("m_Pinned");
    }
References DEFAULT_FUSE_DELAY, m_FuseTimer, m_Pinned, m_RemainingFuseTime, SetFuseDelay(), SetGrenadeType(), and SetPinnable().
Member Function Documentation
Activate()
protected void Grenade_Base::Activate () inline private
run only the remaining part (already unpinned and pinned)
Definition at line 122 of file grenade_base.c.
    {
        if (!m_FuseTimer.IsRunning())
        {
            if (m_RemainingFuseTime > 0)
            {
                //Debug.Log(string.Format("Grenade activated num of seconds to explosion: %1", m_RemainingFuseTime));
                m_FuseTimer.Run(m_RemainingFuseTime, this, "OnActivateFinished");
            }
            else
            {
                //Debug.Log(string.Format("Grenade activated num of seconds to explosion: %1", m_FuseDelay));
                m_FuseTimer.Run(m_FuseDelay, this, "OnActivateFinished");
            }
        }
    }
References m_FuseDelay, m_FuseTimer, and m_RemainingFuseTime.
Referenced by EEItemLocationChanged().
ActivateImmediate()
void Grenade_Base::ActivateImmediate () inline private
Definition at line 90 of file grenade_base.c.
    {
        OnActivateImmediate();
    }
References OnActivateImmediate().
Referenced by ActivateRandomTime().
ActivateRandomTime()
void Grenade_Base::ActivateRandomTime () inline private
to millis
Definition at line 95 of file grenade_base.c.
    {
        float delay = Math.RandomFloat(1, 20);
        delay *= 1000;
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(ActivateImmediate, delay, false);
    }
References ActivateImmediate(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and Math::RandomFloat().
CanBeArmed()
override bool Grenade_Base::CanBeArmed () inline private
Definition at line 248 of file grenade_base.c.
    {
        return false;
    }
CanBeDisarmed()
override bool Grenade_Base::CanBeDisarmed () inline private
Definition at line 253 of file grenade_base.c.
    {
        return false;
    }
CanExplodeInFire()
override bool Grenade_Base::CanExplodeInFire () inline private
Definition at line 258 of file grenade_base.c.
    {
        return true;
    }
CreateLight()
protected override void Grenade_Base::CreateLight () inline private
Definition at line 87 of file flashgrenade.c.
    {
        m_Light = ExplosiveLight.Cast(ScriptedLightBase.CreateLight(FlashGrenadeLight, GetPosition()));
    }
References FlashGrenadeLight(), GetPosition, and m_Light.
Deactivate()
protected void Grenade_Base::Deactivate () inline private
Definition at line 141 of file grenade_base.c.
    {
        if (m_FuseTimer.IsRunning())
        {
            m_RemainingFuseTime = m_FuseTimer.GetRemaining();
            m_FuseTimer.Stop();
            OnDeactivate();
        }
    }
References m_FuseTimer, m_RemainingFuseTime, and OnDeactivate().
Referenced by OnPin(), and OnWasAttached().
EEItemLocationChanged()
override void Grenade_Base::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
activate grenade when it leaves player hands (safety handle released)
Definition at line 271 of file grenade_base.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (newLoc.GetType() != InventoryLocationType.HANDS && !IsPinned())
        {
            Activate();
        }
    }
References Activate(), and IsPinned().
ExplodeGrenade()
protected void Grenade_Base::ExplodeGrenade (EGrenadeType grenade_type) inline private
DEPRECATED - for backward compatibility only.
Definition at line 171 of file grenade_base.c.
    {
        InitiateExplosion();
    }
References InitiateExplosion().
FlashGrenade()
void Grenade_Base::FlashGrenade () inline private
Definition at line 79 of file flashgrenade.c.
    {
        SetAmmoType("FlashGrenade_Ammo");
        SetFuseDelay(2);
        SetGrenadeType(EGrenadeType.ILLUMINATING);
        SetParticleExplosion(ParticleList.GRENADE_M84);
    }
References ParticleList::GRENADE_M84, SetAmmoType(), SetFuseDelay(), SetGrenadeType(), and SetParticleExplosion().
GetGrenadeType()
EGrenadeType Grenade_Base::GetGrenadeType () inline private
Definition at line 117 of file grenade_base.c.
    {
        return m_GrenadeType;
    }
References m_GrenadeType.
Referenced by InitiateExplosion().
InitiateExplosion()
protected override void Grenade_Base::InitiateExplosion () inline private
Definition at line 151 of file grenade_base.c.
    {
        switch (GetGrenadeType())
        {
            case EGrenadeType.FRAGMENTATION:
            case EGrenadeType.ILLUMINATING:
                for (int i = 0; i < m_AmmoTypes.Count(); i++)
                {
                    Explode(DamageType.EXPLOSION, m_AmmoTypes[i]);
                }
            break;
            case EGrenadeType.CHEMICAL:
            case EGrenadeType.NON_LETHAL:
            break;
        }
        OnExplode();
    }
References Explode(), GetGrenadeType(), m_AmmoTypes, and OnExplode().
Referenced by ExplodeGrenade().
IsPinnable()
bool Grenade_Base::IsPinnable () inline private
cannot be pinned once the fuse has started
Definition at line 79 of file grenade_base.c.
    {
        if (m_FuseTimer.IsRunning())
        {
            return false;
        }
        return m_Pinnable;
    }
References m_FuseTimer, and m_Pinnable.
Referenced by ActionSingleUseBase::ActionCondition().
IsPinned()
bool Grenade_Base::IsPinned () inline private
Definition at line 74 of file grenade_base.c.
    {
        return m_Pinned;
    }
References m_Pinned.
Referenced by ActionSingleUseBase::ActionCondition(), and EEItemLocationChanged().
M67Grenade()
void Grenade_Base::M67Grenade () inline private
Definition at line 3 of file m67grenade.c.
    {
        SetAmmoType("M67Grenade_Ammo");
        SetFuseDelay(4);
        SetParticleExplosion(ParticleList.M67);
    }
References ParticleList::M67, SetAmmoType(), SetFuseDelay(), and SetParticleExplosion().
OnActivatedByItem()
override void Grenade_Base::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 63 of file grenade_base.c.
    {
        if (item == this)
        {
            OnActivateFinished();
            return;
        }
        Unpin();
    }
References OnActivateFinished(), and Unpin().
OnActivatedByTripWire()
override void Grenade_Base::OnActivatedByTripWire () private
DEPRECATED use OnActivatedByItem.
OnActivateFinished()
protected void Grenade_Base::OnActivateFinished () inline private
Definition at line 199 of file grenade_base.c.
    {
        if (GetGame().IsServer())
        {
            SetHealth("", "", 0.0); // causes explosion when grenade is destroyed
            SetTakeable(false);
        }
    }
References GetGame(), SetHealth(), and SetTakeable().
Referenced by Grenade_ChemGas::EOnContact(), and OnActivatedByItem().
OnActivateImmediate()
protected void Grenade_Base::OnActivateImmediate () inline private
Definition at line 208 of file grenade_base.c.
    {
        if (GetGame().IsServer())
        {
            SetHealth("", "", 0.0); // causes explosion when grenade is destroyed
            SetTakeable(false);
        }
    }
References GetGame(), SetHealth(), and SetTakeable().
Referenced by ActivateImmediate().
OnActivateStarted()
protected void Grenade_Base::OnActivateStarted () private
Referenced by OnUnpin().
OnDeactivate()
protected void Grenade_Base::OnDeactivate () private
Referenced by Deactivate().
OnExplosionEffects()
override void Grenade_Base::OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType) inline private
values less than 1.0 make no sense
removes possible obstacles made by items around the grenade(or on the same position)
Definition at line 5 of file flashgrenade.c.
    {
        super.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if (player)
        {
            vector headPos          = player.GetDamageZonePos("Head"); // animated position in the middle of the zone
            float ammoRangeKill     = GetGame().ConfigGetFloat(string.Format("CfgAmmo %1 indirectHitRange", ammoType));
            float ammoRangeMaxMult  = 4.0;
            string indirectHitRangeMultiplier = string.Format("CfgAmmo %1 indirectHitRangeMultiplier", ammoType);
            if (GetGame().ConfigIsExisting(indirectHitRangeMultiplier))
            {
                ammoRangeMaxMult = Math.Clamp(GetGame().ConfigGetFloat(indirectHitRangeMultiplier), 1.0, float.MAX);
            }
            float ammoRangeMax = ammoRangeKill * ammoRangeMaxMult;
            ammoRangeMax = Math.Clamp(ammoRangeMax * FX_RANGE_MAX_MULT, ammoRangeKill, ammoRangeMax);
            float dist          = vector.Distance(headPos, pos);
            float distSq        = vector.DistanceSq(headPos, pos);
            float radiusMaxSq = Math.SqrFloat(ammoRangeMax);
            if (distSq <= radiusMaxSq)
            {
                // ignore collisions with parent if fireplace
                InventoryItem invItem = InventoryItem.Cast(source);
                EntityAI parent = invItem.GetHierarchyParent();
                array<Object> excluded = new array<Object>;
                if (!parent || !parent.IsFireplace())
                    parent = null;
                else if (parent)
                    excluded.Insert(parent);
                array<ref RaycastRVResult> results = new array<ref RaycastRVResult>;
                excluded.Insert(this); //Ignore self for visibility check
                //There shouldn't be cases justifying we go further than first entry (if in fireplace, self does not impact)
                RaycastRVParams rayParams   = new RaycastRVParams(pos, headPos, excluded[0]);
                rayParams.flags             = CollisionFlags.ALLOBJECTS;
                DayZPhysics.RaycastRVProxy(rayParams, results, excluded);
                array<Object> hitObjects = new array<Object>;
                for (int i = 0; i < results.Count(); i++)
                {
                    if (results[i].obj && !results[i].obj.IsInherited(ItemBase))
                    {
                        hitObjects.Insert(results[i].obj);
                    }
                }
                //If player is not first index, object is between player and grenade
                if (hitObjects.Count() && PlayerBase.Cast(hitObjects[0]))
                {
                    float effectCoef;
                    if (ammoRangeMax == ammoRangeKill)
                    {
                        effectCoef = 1.0; //edge case, landed right on the edge
                    }
                    effectCoef = 1 - ((dist - ammoRangeKill) / (ammoRangeMax - ammoRangeKill));
                    effectCoef = Math.Clamp(effectCoef, 0.1, 100.0);
                    player.OnPlayerReceiveFlashbangHitStart(MiscGameplayFunctions.IsPlayerOrientedTowardPos(player, pos, 60));
                    player.GetFlashbangEffect().SetupFlashbangValues(effectCoef, effectCoef, effectCoef);
                }
            }
        }
    }
References Math::Clamp(), ConfigGetFloat(), CGame::ConfigGetFloat(), ConfigIsExisting(), vector::Distance(), vector::DistanceSq(), RaycastRVParams::flags, GetGame(), GetPlayer(), MAX, DayZPhysics::RaycastRVProxy(), and Math::SqrFloat().
OnPin()
protected void Grenade_Base::OnPin () inline private
Definition at line 176 of file grenade_base.c.
    {
        m_Pinned = true;
        if (GetGame().IsServer())
        {
            SetSynchDirty();
        }
        Deactivate();
    }
References Deactivate(), GetGame(), and m_Pinned.
Referenced by Pin().
OnStoreLoad()
override bool Grenade_Base::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 229 of file grenade_base.c.
    {
        if (!super.OnStoreLoad(ctx, version))
            return false;
        bool pinned;
        if (version >= 107)
        {
            if (!ctx.Read(pinned))
            {
                return false;
            }
            m_Pinned = pinned;
        }
        return true;
    }
References m_Pinned, and Serializer::Read().
OnStoreSave()
override void Grenade_Base::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 219 of file grenade_base.c.
    {
        super.OnStoreSave(ctx);
        if (GetGame().SaveVersion() >= 107)
        {
            ctx.Write(m_Pinned);
        }
    }
References GetGame(), m_Pinned, and Serializer::Write().
OnUnpin()
protected void Grenade_Base::OnUnpin () inline private
Definition at line 187 of file grenade_base.c.
    {
        m_Pinned = false;
        if (GetGame().IsServer())
        {
            SetSynchDirty();
        }
        OnActivateStarted();
    }
References GetGame(), m_Pinned, and OnActivateStarted().
Referenced by Unpin().
OnWasAttached()
override void Grenade_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 282 of file grenade_base.c.
    {
        super.OnWasAttached(parent, slot_id);
        if (parent.IsAnyInherited({TrapBase,ImprovisedExplosive}))
        {
            Deactivate();
        }
    }
References Deactivate().
Pin()
void Grenade_Base::Pin () inline private
Definition at line 44 of file grenade_base.c.
    {
        if (!m_Pinned && m_Pinnable)
        {
            OnPin();
        }
    }
References m_Pinnable, m_Pinned, and OnPin().
Referenced by ActionSingleUseBase::OnExecute().
RGD5Grenade()
void Grenade_Base::RGD5Grenade () inline private
Definition at line 3 of file rgd5grenade.c.
    {
        SetAmmoType("RGD5Grenade_Ammo");
        SetFuseDelay(4);
        SetParticleExplosion(ParticleList.RGD5);
    }
References ParticleList::RGD5, SetAmmoType(), SetFuseDelay(), and SetParticleExplosion().
SetActions()
override void Grenade_Base::SetActions () inline private
Definition at line 263 of file grenade_base.c.
    {
        super.SetActions();
        AddAction(ActionUnpin);
        AddAction(ActionPin);
    }
References AddAction().
SetFuseDelay()
void Grenade_Base::SetFuseDelay (float delay) inline private
Definition at line 107 of file grenade_base.c.
    {
        m_FuseDelay = delay;
    }
References m_FuseDelay.
Referenced by FlashGrenade(), Grenade_Base(), M67Grenade(), and RGD5Grenade().
SetGrenadeType()
void Grenade_Base::SetGrenadeType (EGrenadeType type) inline private
Definition at line 112 of file grenade_base.c.
    {
        m_GrenadeType = type;
    }
References m_GrenadeType.
Referenced by FlashGrenade(), Grenade_Base(), and Grenade_ChemGas::Grenade_ChemGas().
SetPinnable()
void Grenade_Base::SetPinnable (bool state) inline private
Definition at line 102 of file grenade_base.c.
    {
        m_Pinnable = state;
    }
References m_Pinnable.
Referenced by Grenade_Base(), and Grenade_ChemGas::Grenade_ChemGas().
Unpin()
void Grenade_Base::Unpin () inline private
Definition at line 52 of file grenade_base.c.
    {
        if (m_Pinned)
        {
            OnUnpin();
        }
    }
References m_Pinned, and OnUnpin().
Referenced by OnActivatedByItem(), and ActionSingleUseBase::OnExecute().
Member Data Documentation
DEFAULT_FUSE_DELAY
protected const float Grenade_Base::DEFAULT_FUSE_DELAY = 10 private
Definition at line 32 of file grenade_base.c.
Referenced by Grenade_Base().
FX_RANGE_MAX_MULT
const float Grenade_Base::FX_RANGE_MAX_MULT = 1.0 private
Definition at line 3 of file flashgrenade.c.
m_FuseDelay
protected float Grenade_Base::m_FuseDelay private
Definition at line 35 of file grenade_base.c.
Referenced by Activate(), and SetFuseDelay().
m_FuseTimer
protected ref Timer Grenade_Base::m_FuseTimer private
Definition at line 34 of file grenade_base.c.
Referenced by Activate(), Deactivate(), Grenade_Base(), and IsPinnable().
m_GrenadeType
protected EGrenadeType Grenade_Base::m_GrenadeType private
Definition at line 42 of file grenade_base.c.
Referenced by GetGrenadeType(), and SetGrenadeType().
m_Pinnable
protected bool Grenade_Base::m_Pinnable private
Definition at line 39 of file grenade_base.c.
Referenced by IsPinnable(), Pin(), and SetPinnable().
m_Pinned
protected bool Grenade_Base::m_Pinned private
Definition at line 38 of file grenade_base.c.
Referenced by Grenade_Base(), Grenade_ChemGas::Grenade_ChemGas(), IsPinned(), OnPin(), OnStoreLoad(), OnStoreSave(), OnUnpin(), Pin(), and Unpin().
m_RemainingFuseTime
protected float Grenade_Base::m_RemainingFuseTime private
Definition at line 36 of file grenade_base.c.
Referenced by Activate(), Deactivate(), and Grenade_Base().