DayzKode: ActionMenu Class Reference
ActionMenu Class Reference
Private Member Functions
void ActionMenu ()
void Hide ()
void HideWithFadeout ()
void Init (Widget actions_panel_widget, TextWidget default_action_widget)
void NextAction ()
void NextActionCategory ()
void PrevAction ()
void PrevActionCategory ()
void Refresh ()
void Show ()
void UpdateWidgets ()
Private Attributes
private const float FADE_IN_TIME = 0.3
private const float FADE_OUT_TIME = 0.3
private const float HIDE_MENU_TIME = 5
private ref array< TextWidget > m_actionItems
private Widget m_actionsPanelWidget
private TextWidget m_defaultActionWidget
private ref WidgetFadeTimer m_FadeTimer
private ref Timer m_hide_timer
private bool m_visible
Detailed Description
Definition at line 1 of file actionmenu.c.
Constructor & Destructor Documentation
ActionMenu()
void ActionMenu::ActionMenu () inline private
Definition at line 15 of file actionmenu.c.
    {
        m_actionItems = new array<TextWidget>;
        m_FadeTimer = new WidgetFadeTimer;
        m_hide_timer = new Timer(CALL_CATEGORY_GUI);
        m_visible = false;
    }
References CALL_CATEGORY_GUI, m_actionItems, m_FadeTimer, m_hide_timer, and m_visible.
Member Function Documentation
Hide()
void ActionMenu::Hide () inline private
Definition at line 163 of file actionmenu.c.
    {
        if( !m_visible )
            return;
        m_visible = false;
        m_hide_timer.Stop();
        m_FadeTimer.Stop();
        //m_defaultActionWidget.Show(false);
        m_actionsPanelWidget.Show(false);
    }
References m_actionsPanelWidget, m_FadeTimer, m_hide_timer, and m_visible.
HideWithFadeout()
void ActionMenu::HideWithFadeout () inline private
Definition at line 175 of file actionmenu.c.
    {
        //m_defaultActionWidget.Show(false);
        if (m_actionsPanelWidget.IsVisible())
            m_FadeTimer.FadeOut(m_actionsPanelWidget, FADE_OUT_TIME, true);
    }
References FADE_OUT_TIME, m_actionsPanelWidget, and m_FadeTimer.
Init()
void ActionMenu::Init (Widget actions_panel_widget, TextWidget default_action_widget) inline private
Definition at line 23 of file actionmenu.c.
    {
        m_defaultActionWidget = default_action_widget;
        m_actionsPanelWidget = actions_panel_widget;
        m_actionItems.Clear();
        int i = 0;
        TextWidget w = TextWidget.Cast( m_actionsPanelWidget.FindAnyWidget("ActionListItem" + i.ToString()) );
        while (w)
        {
            m_actionItems.Insert(w);
            w.Show(false);
            i++;
            w = TextWidget.Cast( m_actionsPanelWidget.FindAnyWidget("ActionListItem" + i.ToString()) );
        }
        m_defaultActionWidget.Show(false);
        m_actionsPanelWidget.Show(true);
        m_actionsPanelWidget.SetAlpha(0);
    }
References m_actionItems, m_actionsPanelWidget, and m_defaultActionWidget.
NextAction()
void ActionMenu::NextAction () inline private
Definition at line 104 of file actionmenu.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.GetActionManager().SelectNextAction();
        UpdateWidgets();
        m_hide_timer.Run(HIDE_MENU_TIME, this, "HideWithFadeout");
    }
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
NextActionCategory()
void ActionMenu::NextActionCategory () inline private
Definition at line 124 of file actionmenu.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.GetActionManager().SelectNextActionCategory();
        UpdateWidgets();
        m_hide_timer.Run(HIDE_MENU_TIME, this, "HideWithFadeout");
    }
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
PrevAction()
void ActionMenu::PrevAction () inline private
Definition at line 114 of file actionmenu.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.GetActionManager().SelectPrevAction();
        UpdateWidgets();
        m_hide_timer.Run(HIDE_MENU_TIME, this, "HideWithFadeout");
    }
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
PrevActionCategory()
void ActionMenu::PrevActionCategory () inline private
Definition at line 134 of file actionmenu.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.GetActionManager().SelectPrevActionCategory();
        UpdateWidgets();
        m_hide_timer.Run(HIDE_MENU_TIME, this, "HideWithFadeout");
    }
References GetGame(), GetPlayer(), HIDE_MENU_TIME, m_hide_timer, and UpdateWidgets().
Refresh()
void ActionMenu::Refresh () inline private
Definition at line 153 of file actionmenu.c.
    {
        if( !m_visible )
            Show();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( player.GetActionManager().IsSelectableActionsChanged() )
            UpdateWidgets();
    }
References GetGame(), GetPlayer(), m_visible, Show(), and UpdateWidgets().
Show()
void ActionMenu::Show () inline private
Definition at line 144 of file actionmenu.c.
    {
        if( m_visible )
            return;
        m_visible = true;
        m_hide_timer.Run(HIDE_MENU_TIME, this, "HideWithFadeout");
    }
References HIDE_MENU_TIME, m_hide_timer, and m_visible.
Referenced by Refresh().
UpdateWidgets()
void ActionMenu::UpdateWidgets () inline private
Definition at line 44 of file actionmenu.c.
    {
#ifdef DEVELOPER
        // tmp
        bool newATSelection = true;
        newATSelection = DiagMenu.GetBool( DiagMenuIDs.DM_ACTION_TARGETS_NEW, true );
        // read the action manager
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        TSelectableActionInfoArray actions = player.GetActionManager().GetSelectableActions();
        int selectedActionIndex = player.GetActionManager().GetSelectedActionIndex();
        // clear state
        m_defaultActionWidget.Show(false);
        if( actions.Count() <= 1 )
            m_FadeTimer.FadeOut(m_actionsPanelWidget, FADE_OUT_TIME, true);
        else
            m_FadeTimer.FadeIn(m_actionsPanelWidget, FADE_IN_TIME, true);
        // update state
        for (int i = 0; i < m_actionItems.Count(); i++)
        {
            TextWidget w = m_actionItems.Get(i);
            if (i < actions.Count())
            {
                TSelectableActionInfo actionInfo = actions.Get(i);
                w.SetText(actionInfo.param3);
                if (i == selectedActionIndex)
                {
                    w.SetColor(0xFFFFEC44);
                    m_defaultActionWidget.SetText(actionInfo.param3);
                    if ( !newATSelection )
                    {
                        m_defaultActionWidget.Show(true);
                    }
                }
                else
                {
                    w.SetColor(0xFFFFFFFF);
                }
                w.Show(true);
            }
            else
            {
                w.Show(false);
            }
        }
        float sx;
        float sy;
        m_actionsPanelWidget.GetSize(sx, sy);
        m_actionsPanelWidget.SetSize(sx, 8 + (actions.Count() * 32));
#endif
    }
References FADE_IN_TIME, FADE_OUT_TIME, DiagMenu::GetBool(), GetGame(), GetPlayer(), m_actionItems, m_actionsPanelWidget, m_defaultActionWidget, and m_FadeTimer.
Referenced by NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Refresh().
Member Data Documentation
FADE_IN_TIME
private const float ActionMenu::FADE_IN_TIME = 0.3 private
Definition at line 3 of file actionmenu.c.
Referenced by UpdateWidgets().
FADE_OUT_TIME
private const float ActionMenu::FADE_OUT_TIME = 0.3 private
Definition at line 4 of file actionmenu.c.
Referenced by HideWithFadeout(), and UpdateWidgets().
HIDE_MENU_TIME
private const float ActionMenu::HIDE_MENU_TIME = 5 private
Definition at line 5 of file actionmenu.c.
Referenced by NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Show().
m_actionItems
private ref array<TextWidget> ActionMenu::m_actionItems private
Definition at line 8 of file actionmenu.c.
Referenced by ActionMenu(), Init(), and UpdateWidgets().
m_actionsPanelWidget
private Widget ActionMenu::m_actionsPanelWidget private
Definition at line 10 of file actionmenu.c.
Referenced by Hide(), HideWithFadeout(), Init(), and UpdateWidgets().
m_defaultActionWidget
private TextWidget ActionMenu::m_defaultActionWidget private
Definition at line 9 of file actionmenu.c.
Referenced by Init(), and UpdateWidgets().
m_FadeTimer
private ref WidgetFadeTimer ActionMenu::m_FadeTimer private
Definition at line 7 of file actionmenu.c.
Referenced by ActionMenu(), Hide(), HideWithFadeout(), and UpdateWidgets().
m_hide_timer
private ref Timer ActionMenu::m_hide_timer private
Definition at line 11 of file actionmenu.c.
Referenced by ActionMenu(), Hide(), NextAction(), NextActionCategory(), PrevAction(), PrevActionCategory(), and Show().
m_visible
private bool ActionMenu::m_visible private
Definition at line 13 of file actionmenu.c.
Referenced by ActionMenu(), Hide(), Refresh(), and Show().