DayzKode: Hit_Plaster Class Reference
Hit_Plaster Class Reference
Private Member Functions
void Hit_Plaster ()
Detailed Description
Definition at line 1 of file hit_plaster.c.
Constructor & Destructor Documentation
Hit_Plaster()
void Hit_Plaster::Hit_Plaster () inline private
Definition at line 3 of file hit_plaster.c.
    {
        SetEnterParticle(ParticleList.IMPACT_PLASTER_ENTER);
        SetExitParticle(ParticleList.IMPACT_PLASTER_EXIT);
        SetRicochetParticle(ParticleList.IMPACT_PLASTER_RICOCHET);
    }
References ParticleList::IMPACT_PLASTER_ENTER, ParticleList::IMPACT_PLASTER_EXIT, ParticleList::IMPACT_PLASTER_RICOCHET, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().