DayzKode: DayZPlayerImplementAiming Class Reference
DayZPlayerImplementAiming Class Reference
Private Member Functions
protected void ApplyBreathingPattern (out float x_axis, out float y_axis, float pAmplitude, float pTotalTime, float weight)
protected void ApplyHorizontalNoise (out float x_axis, out float y_axis, float smooth_time, float max_velocity_low, float max_velocity_high, float velocity_modifier, float max_distance, float weight, float pDt)
protected void ApplyShakes (out float x_axis, out float y_axis, int level)
protected float CalculateSwayMultiplier ()
protected float CalculateWeight (int stance_index, float current_stamina, float camera_sway_modifier, bool holding_breath)
void DayZPlayerImplementAiming (DayZPlayerImplement player)
void DbgPrintAimingImplement (string val)
int GetCurrentSwayState ()
float GetSwayWeight ()
void OnFinisherBegin (float currentAimY)
void OnRaiseBegin (DayZPlayerImplement player)
void OnSwayStateChange (int state)
bool ProcessAimFilters (float pDt, SDayZPlayerAimingModel pModel, int stance_index)
bool ProcessStealthFilters (float pDt, SDayZPlayerAimingModel pModel)
void RequestKuruShake (float amount)
void SetAimNoiseAllowed (bool state)
void SetCamShakeValues (float x_axis, float y_axis)
void SetProceduralRecoilEnabled (bool state)
void SetRecoil (Weapon_Base weapon)
protected bool UpdateSwayState (int state)
Private Attributes
protected bool m_AimNoiseAllowed = true
protected float m_BreathingXAxisOffset
protected float m_BreathingYAxisOffset
protected float m_CamShakeX
protected float m_CamShakeY
protected ref RecoilBase m_CurrentRecoil
protected float m_FilterVelocityStealthAimY [1] = {0}
protected bool m_HoldingBreathSet
protected float m_HorizontalNoise
protected float m_HorizontalNoiseVelocity [1] = {0}
protected float m_HorizontalNoiseXAxisOffset
protected float m_HorizontalTargetValue
protected ref KuruShake m_KuruShake
protected float m_LastSwayMultiplier = PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT
protected float m_MaxVelocity
protected DayZPlayerImplement m_PlayerDpi
protected PlayerBase m_PlayerPb
protected bool m_ProceduralRecoilEnabled = true
protected float m_ReferenceTime = 0
protected int m_ShakeCount
protected float m_StateStartSwayMultiplier
protected float m_StealthAimY_Last
protected vector m_SwayModifier = "1 1 1"
protected int m_SwayState = -1
protected float m_SwayStateStartTime
protected float m_SwayWeight
protected float m_TotalTime
protected const float SWAY_WEIGHT_SCALER = 1
Static Private Attributes
static protected float m_AimXClampRanges [] = { -180, -20, 90, 0, -50, 90, 180, -20, 90 }
Detailed Description
Definition at line 31 of file dayzplayerimplementaiming.c.
Constructor & Destructor Documentation
DayZPlayerImplementAiming()
void DayZPlayerImplementAiming::DayZPlayerImplementAiming (DayZPlayerImplement player) inline private
Definition at line 72 of file dayzplayerimplementaiming.c.
    {
        m_PlayerDpi = player;
        Class.CastTo(m_PlayerPb, player);
        UpdateSwayState(eSwayStates.DEFAULT);
    }
References Class::CastTo(), m_PlayerDpi, m_PlayerPb, and UpdateSwayState().
Member Function Documentation
ApplyBreathingPattern()
protected void DayZPlayerImplementAiming::ApplyBreathingPattern (out float x_axis, out float y_axis, float pAmplitude, float pTotalTime, float weight) inline private
Definition at line 345 of file dayzplayerimplementaiming.c.
    {
        float multiplier = Math.Lerp(PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT,0,m_LastSwayMultiplier); //TODO revise
        #ifdef DEVELOPER
        DbgPrintAimingImplement("m_LastSwayMultiplier: " + m_LastSwayMultiplier);
        DbgPrintAimingImplement("pAmplitude: " + pAmplitude);
        DbgPrintAimingImplement("pTotalTime: " + pTotalTime);
        DbgPrintAimingImplement("weight: " + weight);
        DbgPrintAimingImplement("multiplier: " + multiplier);
        #endif
        x_axis = (Math.Sin(pTotalTime) * pAmplitude / 4) * weight;
        y_axis = (Math.Sin((pTotalTime) * 0.8 + 0.6 ) * pAmplitude) * weight;
        #ifdef DEVELOPER
        DbgPrintAimingImplement("y_axis_midproduct: " + y_axis);
        #endif
        x_axis += m_BreathingXAxisOffset * multiplier;
        y_axis += m_BreathingYAxisOffset * multiplier;
    }
References DbgPrintAimingImplement(), Math::Lerp(), m_BreathingXAxisOffset, m_BreathingYAxisOffset, m_LastSwayMultiplier, and Math::Sin().
Referenced by ProcessAimFilters().
ApplyHorizontalNoise()
protected void DayZPlayerImplementAiming::ApplyHorizontalNoise (out float x_axis, out float y_axis, float smooth_time, float max_velocity_low, float max_velocity_high, float velocity_modifier, float max_distance, float weight, float pDt) inline private
Definition at line 366 of file dayzplayerimplementaiming.c.
    {
        if ( Math.AbsFloat(m_HorizontalTargetValue - m_HorizontalNoise) < 0.01)
        {
            //acquire new target
            m_MaxVelocity = m_PlayerPb.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSAimingModel, max_velocity_low, max_velocity_high);
            m_HorizontalTargetValue = (Math.RandomFloat01() - 0.5) * 2 * max_distance;
            m_HorizontalNoiseVelocity[0] = 0;
        }
        m_HorizontalNoise = Math.SmoothCD( m_HorizontalNoise, m_HorizontalTargetValue, m_HorizontalNoiseVelocity, smooth_time, m_MaxVelocity * velocity_modifier, pDt);
        x_axis = m_HorizontalNoise * weight;
        float multiplier = Math.Lerp(PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT,0,m_LastSwayMultiplier); //TODO revise
        x_axis += m_HorizontalNoiseXAxisOffset * multiplier;
    }
References Math::AbsFloat(), Math::Lerp(), m_HorizontalNoise, m_HorizontalNoiseVelocity, m_HorizontalNoiseXAxisOffset, m_HorizontalTargetValue, m_LastSwayMultiplier, m_MaxVelocity, m_PlayerPb, Math::RandomFloat01(), and Math::SmoothCD().
Referenced by ProcessAimFilters().
ApplyShakes()
protected void DayZPlayerImplementAiming::ApplyShakes (out float x_axis, out float y_axis, int level) inline private
Definition at line 383 of file dayzplayerimplementaiming.c.
    {
        float weight = level / PlayerBase.SHAKE_LEVEL_MAX;
        m_ShakeCount++;
        int shakes_threshold = Math.Round(m_PlayerPb.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSAimingModel, 2, 4));
        if (m_ShakeCount > shakes_threshold)
        {
            m_ShakeCount = 0;
            float modifier = m_PlayerPb.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSAimingModel, 0.45, 0.9);
            x_axis = modifier * weight * m_PlayerPb.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSAimingModel, 0, 1);
            y_axis = modifier * weight * m_PlayerPb.GetRandomGeneratorSyncManager().GetRandomInRange(RandomGeneratorSyncUsage.RGSAimingModel, 0, 1);
        }
    }
References m_PlayerPb, m_ShakeCount, and Math::Round().
Referenced by ProcessAimFilters().
CalculateSwayMultiplier()
protected float DayZPlayerImplementAiming::CalculateSwayMultiplier () inline private
Definition at line 285 of file dayzplayerimplementaiming.c.
    {
        float max;
        float time;
        float time_clamped;
        float ret;
        if (m_PlayerPb.IsHoldingBreath())
        {
            time = m_TotalTime - m_ReferenceTime;
            if (time < PlayerSwayConstants.SWAY_TIME_IN)
            {
                UpdateSwayState(eSwayStates.HOLDBREATH_IN);
                max = PlayerSwayConstants.SWAY_TIME_IN;
                time_clamped = Math.Clamp((m_TotalTime - m_SwayStateStartTime),0,max);
                ret = Math.Lerp(m_LastSwayMultiplier,PlayerSwayConstants.SWAY_MULTIPLIER_STABLE,time_clamped/max);
            }
            else if (time >= PlayerSwayConstants.SWAY_TIME_IN && time < (PlayerSwayConstants.SWAY_TIME_IN + PlayerSwayConstants.SWAY_TIME_STABLE))
            {
                UpdateSwayState(eSwayStates.HOLDBREATH_STABLE);
                ret = PlayerSwayConstants.SWAY_MULTIPLIER_STABLE;
            }
            else
            {
                UpdateSwayState(eSwayStates.HOLDBREATH_EXHAUSTED);
                max = PlayerSwayConstants.SWAY_TIME_EXHAUSTED;
                time_clamped = Math.Clamp((m_TotalTime - m_SwayStateStartTime),0,max);
                ret = Math.Lerp(PlayerSwayConstants.SWAY_MULTIPLIER_STABLE,PlayerSwayConstants.SWAY_MULTIPLIER_EXHAUSTED,(time_clamped/max));
            }
        }
        else
        {
            UpdateSwayState(eSwayStates.DEFAULT);
            max = PlayerSwayConstants.SWAY_TIME_OUT;
            time_clamped = Math.Clamp((m_TotalTime - m_SwayStateStartTime),0,max);
            ret = Math.Lerp(m_LastSwayMultiplier,1,time_clamped/max);
        }
        return ret;
    }
References Math::Clamp(), Math::Lerp(), m_LastSwayMultiplier, m_PlayerPb, m_ReferenceTime, m_SwayStateStartTime, m_TotalTime, and UpdateSwayState().
Referenced by ProcessAimFilters().
CalculateWeight()
protected float DayZPlayerImplementAiming::CalculateWeight (int stance_index, float current_stamina, float camera_sway_modifier, bool holding_breath) inline private
Definition at line 398 of file dayzplayerimplementaiming.c.
    {
        if (m_PlayerDpi.GetCommand_Move() && m_PlayerDpi.GetCommand_Move().IsInRoll())//when the player is rolling, set a constant and disregard everything else
        {
            return PlayerSwayConstants.SWAY_ROLL;
        }
        float stance_modifier;
        //float scale = SWAY_WEIGHT_SCALER;
        switch ( stance_index )
        {
            case DayZPlayerConstants.STANCEIDX_RAISEDERECT:
                stance_modifier = 0.5;
            break;
            case DayZPlayerConstants.STANCEIDX_RAISEDCROUCH:
                stance_modifier = 0.75;
            break;
            case DayZPlayerConstants.STANCEIDX_RAISEDPRONE:
                stance_modifier = 0.9;
            break;
            default:
                stance_modifier = 0.75;
                //Debug.LogError("stance mask out of definition");
            break;
        }
        #ifdef DEVELOPER
        DbgPrintAimingImplement("current_stamina: " + current_stamina);
        DbgPrintAimingImplement("camera_sway_modifier: " + camera_sway_modifier);
        DbgPrintAimingImplement("holding_breath: " + holding_breath);
        #endif
        return (1 - stance_modifier) * m_AimNoiseAllowed * camera_sway_modifier * SWAY_WEIGHT_SCALER;
    }
References DbgPrintAimingImplement(), m_AimNoiseAllowed, m_PlayerDpi, and SWAY_WEIGHT_SCALER.
Referenced by ProcessAimFilters().
DbgPrintAimingImplement()
void DayZPlayerImplementAiming::DbgPrintAimingImplement (string val) inline private
Definition at line 432 of file dayzplayerimplementaiming.c.
    {
        #ifdef DEVELOPER
        if (GetDayZGame().IsAimLogEnabled())
            Print("DayZPlayerImplementAiming | " + val);
        #endif
    }
References GetDayZGame(), IsAimLogEnabled(), and Print().
Referenced by ApplyBreathingPattern(), CalculateWeight(), and ProcessAimFilters().
GetCurrentSwayState()
int DayZPlayerImplementAiming::GetCurrentSwayState () inline private
Definition at line 340 of file dayzplayerimplementaiming.c.
    {
        return m_SwayState;
    }
References m_SwayState.
GetSwayWeight()
float DayZPlayerImplementAiming::GetSwayWeight () inline private
Definition at line 121 of file dayzplayerimplementaiming.c.
    {
        return m_SwayWeight;
    }
References m_SwayWeight.
OnFinisherBegin()
void DayZPlayerImplementAiming::OnFinisherBegin (float currentAimY) inline private
Definition at line 102 of file dayzplayerimplementaiming.c.
    {
        m_StealthAimY_Last = currentAimY;
        m_FilterVelocityStealthAimY[0] = 0;
    }
References m_FilterVelocityStealthAimY, and m_StealthAimY_Last.
Referenced by AimingModel().
OnRaiseBegin()
void DayZPlayerImplementAiming::OnRaiseBegin (DayZPlayerImplement player) inline private
Definition at line 93 of file dayzplayerimplementaiming.c.
    {
        Weapon_Base weapon = Weapon_Base.Cast(player.GetHumanInventory().GetEntityInHands());
        if(weapon)
        {
            m_SwayModifier = weapon.GetPropertyModifierObject().m_SwayModifiers;
        }
    }
References m_SwayModifier.
Referenced by AimingModel().
OnSwayStateChange()
void DayZPlayerImplementAiming::OnSwayStateChange (int state) inline private
Definition at line 108 of file dayzplayerimplementaiming.c.
    {
        switch (state)
        {
            case eSwayStates.HOLDBREATH_EXHAUSTED:
                m_PlayerPb.OnHoldBreathExhausted();
            break;
            default:
            break;
        }
    }
References m_PlayerPb.
Referenced by UpdateSwayState().
ProcessAimFilters()
bool DayZPlayerImplementAiming::ProcessAimFilters (float pDt, SDayZPlayerAimingModel pModel, int stance_index) inline private
get sway
get recoil
hands offset
cam offset
clamp aim ranges
mouse offset
Definition at line 149 of file dayzplayerimplementaiming.c.
    {
        float breathing_offset_x;
        float breathing_offset_y;
        float noise_offset_x;
        float noise_offset_y;
        float shake_offset_x;
        float shake_offset_y;
        float recoil_offset_mouse_x;
        float recoil_offset_mouse_y;
        float recoil_offset_hands_x;
        float recoil_offset_hands_y;
        float kuru_offset_x;
        float kuru_offset_y;
        //float player_stamina = m_PlayerPb.GetStaminaHandler().GetStaminaNormalized();
        float player_stamina = m_PlayerPb.GetStaminaHandler().GetSyncedStaminaNormalized();
        #ifdef DEVELOPER
        DbgPrintAimingImplement("Player: " + m_PlayerPb + " | ProcessAimFilters | timestamp: " + m_PlayerPb.GetSimulationTimeStamp());
        #endif
        //negates stamina effect during hold breath
        if ( m_PlayerPb.IsHoldingBreath() )
        {
            player_stamina = 1;
        }
        float speed = (((1.0 - player_stamina) * 3.0) + 1.0) * m_SwayModifier[2];
        m_TotalTime += pDt * speed;
        if (m_PlayerPb.IsHoldingBreath() && !m_HoldingBreathSet)
        {
            m_ReferenceTime = m_TotalTime;
        }
        else if (!m_PlayerPb.IsHoldingBreath() && m_HoldingBreathSet)
        {
            m_ReferenceTime = m_TotalTime;
        }
        float adjusted_sway_multiplier = CalculateSwayMultiplier();
        m_LastSwayMultiplier = adjusted_sway_multiplier;
        m_SwayWeight = CalculateWeight( stance_index, player_stamina, 0.5/*m_PlayerPb.m_CameraSwayModifier*/, m_PlayerPb.IsHoldingBreath() ) * adjusted_sway_multiplier;
        ApplyBreathingPattern(breathing_offset_x, breathing_offset_y, 3.0, m_TotalTime, m_SwayWeight);
        ApplyHorizontalNoise(noise_offset_x, noise_offset_y, 0.2, 0.5, 3.0 * m_SwayModifier[0], speed, 3 * m_SwayModifier[1], m_SwayWeight, pDt);
        int shake_level = m_PlayerPb.GetShakeLevel();
        if (shake_level != 0)
        {
            ApplyShakes(shake_offset_x, shake_offset_y, shake_level);
        }
        if( m_CurrentRecoil )
        {
            m_CurrentRecoil.Update(pModel, recoil_offset_mouse_x, recoil_offset_mouse_y, recoil_offset_hands_x, recoil_offset_hands_y, pDt);
        }
        if( m_KuruShake )
        {
            m_KuruShake.Update(pDt, kuru_offset_x, kuru_offset_y);
        }
        pModel.m_fAimXHandsOffset = breathing_offset_x + noise_offset_x + recoil_offset_hands_x + shake_offset_x + kuru_offset_x;
        pModel.m_fAimYHandsOffset = breathing_offset_y + noise_offset_y + recoil_offset_hands_y + shake_offset_y + kuru_offset_y;
        #ifdef DEVELOPER
        DbgPrintAimingImplement("breathing_offset_y: " + breathing_offset_y);
        DbgPrintAimingImplement("noise_offset_y: " + noise_offset_y);
        DbgPrintAimingImplement("recoil_offset_hands_y: " + recoil_offset_hands_y);
        DbgPrintAimingImplement("shake_offset_y: " + shake_offset_y);
        DbgPrintAimingImplement("kuru_offset_y: " + kuru_offset_y);
        DbgPrintAimingImplement("pModel.m_fAimYHandsOffset: " + pModel.m_fAimYHandsOffset);
        #endif
        pModel.m_fAimXCamOffset = -shake_offset_x - recoil_offset_hands_x - kuru_offset_x + m_CamShakeX;
        pModel.m_fAimYCamOffset = -shake_offset_y - recoil_offset_hands_y - kuru_offset_y + m_CamShakeY;
        #ifdef DEVELOPER
        DbgPrintAimingImplement("m_CamShakeY: " + m_CamShakeY);
        DbgPrintAimingImplement("pModel.m_fAimYCamOffset: " + pModel.m_fAimYCamOffset);
        #endif
        if (stance_index == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
        {
            float newVal = DayZPlayerUtils.LinearRangeClamp(pModel.m_fCurrentAimX, pModel.m_fCurrentAimY, m_AimXClampRanges);
            pModel.m_fAimYHandsOffset += newVal - pModel.m_fCurrentAimY;
        }
        if( m_PlayerDpi.IsInOptics() && m_KuruShake )
        {
            //TODO - do not offset mouse
        }
        pModel.m_fAimXMouseShift = recoil_offset_mouse_x -kuru_offset_x / 10;
        pModel.m_fAimYMouseShift = recoil_offset_mouse_y + kuru_offset_y / 10;
        #ifdef DEVELOPER
        DbgPrintAimingImplement("recoil_offset_mouse_y: " + recoil_offset_mouse_y);
        DbgPrintAimingImplement("pModel.m_fAimYMouseShift: " + pModel.m_fAimYMouseShift);
        #endif
        if ( m_PlayerPb.IsHoldingBreath() && !m_HoldingBreathSet)
        {
            m_HoldingBreathSet = true;
            m_HorizontalNoiseXAxisOffset = noise_offset_x;
            m_BreathingXAxisOffset = breathing_offset_x;
            m_BreathingYAxisOffset = breathing_offset_y;
        }
        else if(!m_PlayerPb.IsHoldingBreath() && m_HoldingBreathSet)
        {
            m_HoldingBreathSet = false;
        }
        if(!m_PlayerPb.IsHoldingBreath() && m_LastSwayMultiplier == PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT && m_HorizontalNoiseXAxisOffset != 0)
        {
            m_HorizontalNoiseXAxisOffset = 0;
            m_BreathingXAxisOffset = 0;
            m_BreathingYAxisOffset = 0;
        }
        #ifdef DEVELOPER
        DbgPrintAimingImplement("----------------------------");
        #endif
        return true;
    }
References ApplyBreathingPattern(), ApplyHorizontalNoise(), ApplyShakes(), CalculateSwayMultiplier(), CalculateWeight(), DbgPrintAimingImplement(), DayZPlayerUtils::LinearRangeClamp(), m_AimXClampRanges, m_BreathingXAxisOffset, m_BreathingYAxisOffset, m_CamShakeX, m_CamShakeY, m_CurrentRecoil, SDayZPlayerAimingModel::m_fAimXCamOffset, SDayZPlayerAimingModel::m_fAimXHandsOffset, SDayZPlayerAimingModel::m_fAimXMouseShift, SDayZPlayerAimingModel::m_fAimYCamOffset, SDayZPlayerAimingModel::m_fAimYHandsOffset, SDayZPlayerAimingModel::m_fAimYMouseShift, SDayZPlayerAimingModel::m_fCurrentAimX, SDayZPlayerAimingModel::m_fCurrentAimY, m_HoldingBreathSet, m_HorizontalNoiseXAxisOffset, m_KuruShake, m_LastSwayMultiplier, m_PlayerDpi, m_PlayerPb, m_ReferenceTime, m_SwayModifier, m_SwayWeight, m_TotalTime, KuruShake::Update(), and RecoilBase::Update().
Referenced by AimingModel().
ProcessStealthFilters()
bool DayZPlayerImplementAiming::ProcessStealthFilters (float pDt, SDayZPlayerAimingModel pModel) inline private
Definition at line 142 of file dayzplayerimplementaiming.c.
    {
        m_StealthAimY_Last = Math.SmoothCD(m_StealthAimY_Last, 0, m_FilterVelocityStealthAimY, 0.3, 1000, pDt);
        pModel.m_fAimYMouseShift = -(pModel.m_fCurrentAimY - m_StealthAimY_Last);
        return true;
    }
References SDayZPlayerAimingModel::m_fAimYMouseShift, SDayZPlayerAimingModel::m_fCurrentAimY, m_FilterVelocityStealthAimY, m_StealthAimY_Last, and Math::SmoothCD().
Referenced by AimingModel().
RequestKuruShake()
void DayZPlayerImplementAiming::RequestKuruShake (float amount) inline private
Definition at line 87 of file dayzplayerimplementaiming.c.
    {
        if(!m_KuruShake)
            m_KuruShake = new KuruShake(m_PlayerPb, amount);
    }
References m_KuruShake, and m_PlayerPb.
Referenced by ManBase::OnSyncJuncture().
SetAimNoiseAllowed()
void DayZPlayerImplementAiming::SetAimNoiseAllowed (bool state) inline private
Definition at line 126 of file dayzplayerimplementaiming.c.
    {
        m_AimNoiseAllowed = state;
    }
References m_AimNoiseAllowed.
SetCamShakeValues()
void DayZPlayerImplementAiming::SetCamShakeValues (float x_axis, float y_axis) inline private
Definition at line 136 of file dayzplayerimplementaiming.c.
    {
        m_CamShakeX = x_axis;
        m_CamShakeY = y_axis;
    }
References m_CamShakeX, and m_CamShakeY.
SetProceduralRecoilEnabled()
void DayZPlayerImplementAiming::SetProceduralRecoilEnabled (bool state) inline private
Definition at line 131 of file dayzplayerimplementaiming.c.
    {
        m_ProceduralRecoilEnabled = state;
    }
References m_ProceduralRecoilEnabled.
SetRecoil()
void DayZPlayerImplementAiming::SetRecoil (Weapon_Base weapon) inline private
Definition at line 79 of file dayzplayerimplementaiming.c.
    {
        if( m_ProceduralRecoilEnabled )
        {
            m_CurrentRecoil = weapon.SpawnRecoilObject();
        }
    }
References m_CurrentRecoil, m_ProceduralRecoilEnabled, and Weapon_Base::SpawnRecoilObject().
UpdateSwayState()
protected bool DayZPlayerImplementAiming::UpdateSwayState (int state) inline private
Definition at line 326 of file dayzplayerimplementaiming.c.
    {
        if (state != m_SwayState)
        {
            m_SwayState = state;
            m_SwayStateStartTime = m_TotalTime;
            m_StateStartSwayMultiplier = m_LastSwayMultiplier;
            OnSwayStateChange(state);
            return true;
        }
        return false;
    }
References m_LastSwayMultiplier, m_StateStartSwayMultiplier, m_SwayState, m_SwayStateStartTime, m_TotalTime, and OnSwayStateChange().
Referenced by CalculateSwayMultiplier(), and DayZPlayerImplementAiming().
Member Data Documentation
m_AimNoiseAllowed
protected bool DayZPlayerImplementAiming::m_AimNoiseAllowed = true private
Definition at line 55 of file dayzplayerimplementaiming.c.
Referenced by CalculateWeight(), and SetAimNoiseAllowed().
m_AimXClampRanges
protected float DayZPlayerImplementAiming::m_AimXClampRanges[] = { -180, -20, 90, 0, -50, 90, 180, -20, 90 } static private
Definition at line 70 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters().
m_BreathingXAxisOffset
protected float DayZPlayerImplementAiming::m_BreathingXAxisOffset private
Definition at line 52 of file dayzplayerimplementaiming.c.
Referenced by ApplyBreathingPattern(), and ProcessAimFilters().
m_BreathingYAxisOffset
protected float DayZPlayerImplementAiming::m_BreathingYAxisOffset private
Definition at line 53 of file dayzplayerimplementaiming.c.
Referenced by ApplyBreathingPattern(), and ProcessAimFilters().
m_CamShakeX
protected float DayZPlayerImplementAiming::m_CamShakeX private
Definition at line 62 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters(), and SetCamShakeValues().
m_CamShakeY
protected float DayZPlayerImplementAiming::m_CamShakeY private
Definition at line 63 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters(), and SetCamShakeValues().
m_CurrentRecoil
protected ref RecoilBase DayZPlayerImplementAiming::m_CurrentRecoil private
Definition at line 57 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters(), and SetRecoil().
m_FilterVelocityStealthAimY
protected float DayZPlayerImplementAiming::m_FilterVelocityStealthAimY[1] = {0} private
Definition at line 68 of file dayzplayerimplementaiming.c.
Referenced by OnFinisherBegin(), and ProcessStealthFilters().
m_HoldingBreathSet
protected bool DayZPlayerImplementAiming::m_HoldingBreathSet private
Definition at line 54 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters().
m_HorizontalNoise
protected float DayZPlayerImplementAiming::m_HorizontalNoise private
Definition at line 40 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise().
m_HorizontalNoiseVelocity
protected float DayZPlayerImplementAiming::m_HorizontalNoiseVelocity[1] = {0} private
Definition at line 42 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise().
m_HorizontalNoiseXAxisOffset
protected float DayZPlayerImplementAiming::m_HorizontalNoiseXAxisOffset private
Definition at line 51 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise(), and ProcessAimFilters().
m_HorizontalTargetValue
protected float DayZPlayerImplementAiming::m_HorizontalTargetValue private
Definition at line 41 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise().
m_KuruShake
protected ref KuruShake DayZPlayerImplementAiming::m_KuruShake private
Definition at line 61 of file dayzplayerimplementaiming.c.
Referenced by ProcessAimFilters(), and RequestKuruShake().
m_LastSwayMultiplier
protected float DayZPlayerImplementAiming::m_LastSwayMultiplier = PlayerSwayConstants.SWAY_MULTIPLIER_DEFAULT private
Definition at line 49 of file dayzplayerimplementaiming.c.
Referenced by ApplyBreathingPattern(), ApplyHorizontalNoise(), CalculateSwayMultiplier(), ProcessAimFilters(), and UpdateSwayState().
m_MaxVelocity
protected float DayZPlayerImplementAiming::m_MaxVelocity private
Definition at line 60 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise().
m_PlayerDpi
protected DayZPlayerImplement DayZPlayerImplementAiming::m_PlayerDpi private
Definition at line 43 of file dayzplayerimplementaiming.c.
Referenced by CalculateWeight(), DayZPlayerImplementAiming(), and ProcessAimFilters().
m_PlayerPb
protected PlayerBase DayZPlayerImplementAiming::m_PlayerPb private
Definition at line 44 of file dayzplayerimplementaiming.c.
Referenced by ApplyHorizontalNoise(), ApplyShakes(), CalculateSwayMultiplier(), DayZPlayerImplementAiming(), OnSwayStateChange(), ProcessAimFilters(), and RequestKuruShake().
m_ProceduralRecoilEnabled
protected bool DayZPlayerImplementAiming::m_ProceduralRecoilEnabled = true private
Definition at line 56 of file dayzplayerimplementaiming.c.
Referenced by SetProceduralRecoilEnabled(), and SetRecoil().
m_ReferenceTime
protected float DayZPlayerImplementAiming::m_ReferenceTime = 0 private
Definition at line 46 of file dayzplayerimplementaiming.c.
Referenced by CalculateSwayMultiplier(), and ProcessAimFilters().
m_ShakeCount
protected int DayZPlayerImplementAiming::m_ShakeCount private
Definition at line 58 of file dayzplayerimplementaiming.c.
Referenced by ApplyShakes().
m_StateStartSwayMultiplier
protected float DayZPlayerImplementAiming::m_StateStartSwayMultiplier private
Definition at line 50 of file dayzplayerimplementaiming.c.
Referenced by UpdateSwayState().
m_StealthAimY_Last
protected float DayZPlayerImplementAiming::m_StealthAimY_Last private
Definition at line 67 of file dayzplayerimplementaiming.c.
Referenced by OnFinisherBegin(), and ProcessStealthFilters().
m_SwayModifier
protected vector DayZPlayerImplementAiming::m_SwayModifier = "1 1 1" private
Definition at line 64 of file dayzplayerimplementaiming.c.
Referenced by OnRaiseBegin(), and ProcessAimFilters().
m_SwayState
protected int DayZPlayerImplementAiming::m_SwayState = -1 private
Definition at line 65 of file dayzplayerimplementaiming.c.
Referenced by GetCurrentSwayState(), and UpdateSwayState().
m_SwayStateStartTime
protected float DayZPlayerImplementAiming::m_SwayStateStartTime private
Definition at line 47 of file dayzplayerimplementaiming.c.
Referenced by CalculateSwayMultiplier(), and UpdateSwayState().
m_SwayWeight
protected float DayZPlayerImplementAiming::m_SwayWeight private
Definition at line 59 of file dayzplayerimplementaiming.c.
Referenced by GetSwayWeight(), and ProcessAimFilters().
m_TotalTime
protected float DayZPlayerImplementAiming::m_TotalTime private
Definition at line 45 of file dayzplayerimplementaiming.c.
Referenced by CalculateSwayMultiplier(), ProcessAimFilters(), and UpdateSwayState().
SWAY_WEIGHT_SCALER
protected const float DayZPlayerImplementAiming::SWAY_WEIGHT_SCALER = 1 private
This HeadingModel - Clamps heading
Definition at line 39 of file dayzplayerimplementaiming.c.
Referenced by CalculateWeight().