DayzKode: CarHornShortActionInput Class Reference
CarHornShortActionInput Class Reference
Private Member Functions
void CarHornShortActionInput (PlayerBase player)
override ActionBase GetAction ()
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
Private Attributes
ref ActionTarget targetNew
Detailed Description
Definition at line 659 of file actioninput.c.
Constructor & Destructor Documentation
CarHornShortActionInput()
void CarHornShortActionInput::CarHornShortActionInput (PlayerBase player) inline private
Definition at line 663 of file actioninput.c.
    {
        SetInput("UACarHorn");
        m_InputType         = ActionInputType.AIT_SINGLE;
        m_Priority          = 100;
        m_DetectFromItem    = false;
        m_DetectFromTarget  = false;
        m_DetectFromPlayer  = false;
    }
References m_Priority, and SetInput().
Member Function Documentation
GetAction()
override ActionBase CarHornShortActionInput::GetAction () inline private
Definition at line 727 of file actioninput.c.
    {
        return m_SelectAction;
    }
References m_SelectAction.
UpdatePossibleActions()
override void CarHornShortActionInput::UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Definition at line 673 of file actioninput.c.
    {
        if (ForceActionCheck(player))
        {
            m_SelectAction = m_ForcedActionData.m_Action;
            return;
        }
        m_SelectAction = null;
        array<ActionBase_Basic> possibleActions;
        ActionBase action;
        int i;
        m_MainItem = null;
        if (player && player.IsInVehicle())
        {
            HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
            if (vehCommand)
            {
                Transport trans = vehCommand.GetTransport();
                if (trans)
                {
                    targetNew = new ActionTarget(trans, null, -1, vector.Zero, -1);
                    ForceActionTarget(targetNew);
                }
            }
            if (!targetNew)
            {
                ClearForcedTarget();
            }
        }
        target = m_ForcedTarget;
        m_Target = m_ForcedTarget;
        if (target && target.GetObject())
        {
            target.GetObject().GetActions(this.Type(), possibleActions);
            if (possibleActions)
            {
                for (i = 0; i < possibleActions.Count(); i++)
                {
                    action = ActionBase.Cast(possibleActions.Get(i));
                    if (action.Can(player, target, m_MainItem, action_condition_mask))
                    {
                        m_SelectAction = action;
                        return;
                    }
                }
            }
        }
    }
References ActionBase(), ActionTarget, HumanCommandVehicle::GetTransport(), m_MainItem, m_SelectAction, m_Target, targetNew, Type, and vector::Zero.
Member Data Documentation
targetNew
ref ActionTarget CarHornShortActionInput::targetNew private
Definition at line 661 of file actioninput.c.
Referenced by UpdatePossibleActions().