DayzKode: Param Class Reference
Param Class Reference
Tools
Base Param Class with no parameters. Used as general purpose parameter overloaded with Param1 to Param4 templates.
Private Member Functions
bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
override bool Deserializer (Serializer ctx)
void Param1 (T1 p1)
void Param2 (T1 p1, T2 p2)
void Param3 (T1 p1, T2 p2, T3 p3)
void Param4 (T1 p1, T2 p2, T3 p3, T4 p4)
void Param5 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5)
void Param6 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6)
bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
override bool Serialize (Serializer ctx)
Private Attributes
T1 param1
T2 param2
T3 param3
T4 param4
T5 param5
T6 param6
Detailed Description
Base Param Class with no parameters. Used as general purpose parameter overloaded with Param1 to Param4 templates.
Param Class Template with six parameters.
Param Class Template with five parameters.
Param Class Template with four parameters.
usage:
Param Class Template with three parameters.
usage:
Param Class Template with two parameters.
usage:
Param Class Template with one parameter.
usage:
Param paramA = new Param1<int>(55);
Param paramB = new Param1<string>("Hello");
Param param = new Param2<float, string>(3.14, "Pi");
Param param = new Param3<float, string, bool>(2.89, "Lala", true);
Param param = new Param4<int, bool, float, string>(100, false, 79.9, "Test");
Definition at line 11 of file param.c.
Member Function Documentation
Deserializer() [1/7]
bool Param::Deserializer (Serializer ctx) inline private
Definition at line 18 of file param.c.
    {
        return false;
    }
Deserializer() [2/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 46 of file param.c.
    {
        return ctx.Read(param1);
    }
References Serializer::Read().
Deserializer() [3/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 75 of file param.c.
    {
        return ctx.Read(param1) && ctx.Read(param2);
    }
References Serializer::Read().
Deserializer() [4/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 106 of file param.c.
    {
        return ctx.Read(param1) && ctx.Read(param2) && ctx.Read(param3);
    }
References Serializer::Read().
Deserializer() [5/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 139 of file param.c.
    {
        return ctx.Read(param1) && ctx.Read(param2) && ctx.Read(param3) && ctx.Read(param4);
    }
References Serializer::Read().
Deserializer() [6/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 170 of file param.c.
    {
        return ctx.Read(param1) && ctx.Read(param2) && ctx.Read(param3) && ctx.Read(param4) && ctx.Read(param5);
    }
References Serializer::Read().
Deserializer() [7/7]
override bool Param::Deserializer (Serializer ctx) inline private
Definition at line 203 of file param.c.
    {
        return ctx.Read(param1) && ctx.Read(param2) && ctx.Read(param3) && ctx.Read(param4) && ctx.Read(param5) && ctx.Read(param6);
    }
References Serializer::Read().
Param1()
void Param::Param1 (T1 p1) inline private
Definition at line 36 of file param.c.
    {
        param1 = p1;
    }
Param2()
void Param::Param2 (T1 p1, T2 p2) inline private
Definition at line 64 of file param.c.
    {
        param1 = p1;
        param2 = p2;
    }
Param3()
void Param::Param3 (T1 p1, T2 p2, T3 p3) inline private
Definition at line 94 of file param.c.
    {
        param1 = p1;
        param2 = p2;
        param3 = p3;
    }
Param4()
void Param::Param4 (T1 p1, T2 p2, T3 p3, T4 p4) inline private
Definition at line 126 of file param.c.
    {
        param1 = p1;
        param2 = p2;
        param3 = p3;
        param4 = p4;
    }
Param5()
void Param::Param5 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5) inline private
Definition at line 156 of file param.c.
    {
        param1 = p1;
        param2 = p2;
        param3 = p3;
        param4 = p4;
        param5 = p5;
    }
Param6()
void Param::Param6 (T1 p1, T2 p2, T3 p3, T4 p4, T5 p5, T6 p6) inline private
Definition at line 188 of file param.c.
    {
        param1 = p1;
        param2 = p2;
        param3 = p3;
        param4 = p4;
        param5 = p5;
        param6 = p6;
    }
Serialize() [1/7]
bool Param::Serialize (Serializer ctx) inline private
Definition at line 13 of file param.c.
    {
        return false;
    }
Serialize() [2/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 41 of file param.c.
    {
        return ctx.Write(param1);
    }
References Serializer::Write().
Serialize() [3/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 70 of file param.c.
    {
        return ctx.Write(param1) && ctx.Write(param2);
    }
References Serializer::Write().
Serialize() [4/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 101 of file param.c.
    {
        return ctx.Write(param1) && ctx.Write(param2) && ctx.Write(param3);
    }
References Serializer::Write().
Serialize() [5/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 134 of file param.c.
    {
        return ctx.Write(param1) && ctx.Write(param2) && ctx.Write(param3) && ctx.Write(param4);
    }
References Serializer::Write().
Serialize() [6/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 165 of file param.c.
    {
        return ctx.Write(param1) && ctx.Write(param2) && ctx.Write(param3) && ctx.Write(param4) && ctx.Write(param5);
    }
References Serializer::Write().
Serialize() [7/7]
override bool Param::Serialize (Serializer ctx) inline private
Definition at line 198 of file param.c.
    {
        return ctx.Write(param1) && ctx.Write(param2) && ctx.Write(param3) && ctx.Write(param4) && ctx.Write(param5) && ctx.Write(param6);
    }
References Serializer::Write().
Member Data Documentation
param1
T1 Param::param1 private
Definition at line 34 of file param.c.
Referenced by PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), and PPEClassBase::SetFinalParameterValue().
param2
T2 Param::param2 private
Definition at line 62 of file param.c.
param3
T3 Param::param3 private
Definition at line 92 of file param.c.
param4
T4 Param::param4 private
Definition at line 124 of file param.c.
param5
T5 Param::param5 private
Definition at line 154 of file param.c.
param6
T6 Param::param6 private
Definition at line 186 of file param.c.