DayzKode: CollapsibleContainer Class Reference
CollapsibleContainer Class Reference
Private Member Functions
bool CanDisplayAnyCategory ()
void CollapseButtonOnMouseButtonDown (Widget w)
void CollapsibleContainer (LayoutHolder parent, int sort=-1)
EntityAI GetEntity ()
override Header GetHeader ()
override void Insert (LayoutHolder container, int pos=-1, bool immedUpdate=true)
bool IsHidden ()
void LoadDefaultState ()
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void OnHide ()
override void OnShow ()
override void Refresh ()
override void Remove (LayoutHolder container)
void SetCollapsibleHeaderArrowState (bool open)
override void SetHeader (Header header)
override void SetLayoutName ()
override void Toggle ()
void UpdateCollapseButtons ()
Private Attributes
protected ref CollapsibleHeader m_CollapsibleHeader
protected bool m_Hidden
Detailed Description
Definition at line 1 of file collapsiblecontainer.c.
Constructor & Destructor Documentation
CollapsibleContainer()
void CollapsibleContainer::CollapsibleContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 6 of file collapsiblecontainer.c.
    {
        m_MainWidget.Show( true );
        if ( sort > -1 )
            m_MainWidget.SetSort( sort + 2 );
        m_MainWidget = m_MainWidget.FindAnyWidget( "header" );
        m_Body = new array<ref LayoutHolder>;
        m_CollapsibleHeader = new CollapsibleHeader( this, "CollapseButtonOnMouseButtonDown" );
    }
References m_CollapsibleHeader.
Member Function Documentation
CanDisplayAnyCategory()
bool CollapsibleContainer::CanDisplayAnyCategory () inline private
Definition at line 86 of file collapsiblecontainer.c.
    {
        return false;
    }
CollapseButtonOnMouseButtonDown()
void CollapsibleContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 131 of file collapsiblecontainer.c.
    {
        Toggle();
    }
References Toggle().
GetEntity()
EntityAI CollapsibleContainer::GetEntity () inline private
Definition at line 24 of file collapsiblecontainer.c.
    {
        return m_Entity;
    }
References m_Entity.
GetHeader()
override Header CollapsibleContainer::GetHeader () inline private
Definition at line 176 of file collapsiblecontainer.c.
    {
        return m_CollapsibleHeader;
    }
References m_CollapsibleHeader.
Referenced by PlayerContainer::PlayerContainer(), and ZombieContainer::ZombieContainer().
Insert()
override void CollapsibleContainer::Insert (LayoutHolder container, int pos = -1, bool immedUpdate = true) inline private
Definition at line 66 of file collapsiblecontainer.c.
    {
        super.Insert( container, pos, immedUpdate );
        //if ( immedUpdate )
        //{
            RecomputeOpenedContainers();
            UpdateCollapseButtons();
        //}
        SetCollapsibleHeaderArrowState(m_Hidden);
    }
References m_Hidden, SetCollapsibleHeaderArrowState(), and UpdateCollapseButtons().
Referenced by AttachmentCategoriesContainer::InitGhostSlots().
IsHidden()
bool CollapsibleContainer::IsHidden () inline private
Definition at line 126 of file collapsiblecontainer.c.
    {
        return m_Hidden;
    }
References m_Hidden.
Referenced by PlayerContainer::UpdateRadialIcon(), and ZombieContainer::UpdateRadialIcon().
LoadDefaultState()
void CollapsibleContainer::LoadDefaultState () inline private
Definition at line 111 of file collapsiblecontainer.c.
    {
        m_Hidden = !ItemManager.GetInstance().GetDefaultHeaderOpenState( "VICINITY" );
        //m_Closed = m_Hidden;
        if ( m_Hidden )
        {
            OnHide();
        }
        else
        {
            OnShow();
        }
    }
References ItemManager::GetDefaultHeaderOpenState(), ItemManager::GetInstance(), m_Hidden, OnHide(), and OnShow().
Referenced by VicinityContainer::VicinityContainer().
OnChildAdd()
override bool CollapsibleContainer::OnChildAdd (Widget w, Widget child) inline private
Definition at line 169 of file collapsiblecontainer.c.
    {
        if( w == GetMainWidget() )
            GetMainWidget().Update();
        return true;
    }
OnChildRemove()
override bool CollapsibleContainer::OnChildRemove (Widget w, Widget child) inline private
Definition at line 162 of file collapsiblecontainer.c.
    {
        if( w == GetMainWidget() )
            GetMainWidget().Update();
        return true;
    }
OnDropReceivedFromHeader()
override void CollapsibleContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 29 of file collapsiblecontainer.c.
{ }
OnHide()
override void CollapsibleContainer::OnHide () inline private
Definition at line 52 of file collapsiblecontainer.c.
    {
        m_Hidden = true;
        if (m_CollapsibleHeader)
        {
            SetCollapsibleHeaderArrowState(m_Hidden);
        }
        else
        {
            super.OnHide();
        }
    }
References m_CollapsibleHeader, m_Hidden, and SetCollapsibleHeaderArrowState().
Referenced by LoadDefaultState(), and Toggle().
OnShow()
override void CollapsibleContainer::OnShow () inline private
Definition at line 36 of file collapsiblecontainer.c.
    {
        super.OnShow();
        m_Hidden = false;
        for (int i = 0; i < m_Body.Count(); i++)
        {
            m_Body.Get( i ).OnShow();
            Container c = Container.Cast(m_Body.Get(i));
            if (c)
            {
                c.Open();
            }
        }
        SetCollapsibleHeaderArrowState(m_Hidden);
    }
References m_Hidden, Container::Open(), and SetCollapsibleHeaderArrowState().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), LoadDefaultState(), AttachmentCategoriesContainer::Open(), and Toggle().
Refresh()
override void CollapsibleContainer::Refresh () inline private
Definition at line 31 of file collapsiblecontainer.c.
    {
        super.Refresh();
    }
Referenced by ZombieContainer::ItemAttached(), ZombieContainer::ItemDetached(), and VicinityContainer::UpdateInterval().
Remove()
override void CollapsibleContainer::Remove (LayoutHolder container) inline private
Definition at line 79 of file collapsiblecontainer.c.
    {
        super.Remove( container );
        RecomputeOpenedContainers();
        UpdateCollapseButtons();
    }
References UpdateCollapseButtons().
Referenced by PlayerContainer::ItemDetached(), ZombieContainer::ItemDetached(), and VicinityContainer::UpdateInterval().
SetCollapsibleHeaderArrowState()
void CollapsibleContainer::SetCollapsibleHeaderArrowState (bool open) inline private
Definition at line 186 of file collapsiblecontainer.c.
    {
        if (m_CollapsibleHeader)
        {
            m_CollapsibleHeader.SetArrowButtonOpened(open);
        }
    }
References m_CollapsibleHeader, and CollapsibleHeader::SetArrowButtonOpened().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), Insert(), OnHide(), OnShow(), and Toggle().
SetHeader()
override void CollapsibleContainer::SetHeader (Header header) inline private
Definition at line 181 of file collapsiblecontainer.c.
    {
        m_CollapsibleHeader = CollapsibleHeader.Cast(header);
    }
References m_CollapsibleHeader.
Referenced by PlayerContainer::PlayerContainer(), and ZombieContainer::ZombieContainer().
SetLayoutName()
override void CollapsibleContainer::SetLayoutName () inline private
Definition at line 19 of file collapsiblecontainer.c.
    {
        m_LayoutName = WidgetLayoutName.CollapsibleContainer;
    }
References WidgetLayoutName::CollapsibleContainer.
Toggle()
override void CollapsibleContainer::Toggle () inline private
Definition at line 136 of file collapsiblecontainer.c.
    {
        if (!m_Hidden)
        {
            for (int i = 1; i < m_Body.Count(); i++)
            {
                m_Body.Get( i ).OnHide();
                Container c = Container.Cast(m_Body.Get(i));
                if (c)
                {
                    c.Close();
                }
            }
            OnHide();
        }
        else
        {
            OnShow();
        }
        m_Closed = m_Hidden;
        SetCollapsibleHeaderArrowState(m_Hidden);
        UpdateCollapseButtons();
    }
References Container::Close(), m_Hidden, OnHide(), OnShow(), SetCollapsibleHeaderArrowState(), and UpdateCollapseButtons().
Referenced by CollapseButtonOnMouseButtonDown().
UpdateCollapseButtons()
void CollapsibleContainer::UpdateCollapseButtons () inline private
Definition at line 91 of file collapsiblecontainer.c.
    {
        #ifndef PLATFORM_CONSOLE
        if (m_Body.Count() < 2)
        {
            if (m_CollapsibleHeader)
            {
                m_CollapsibleHeader.ShowCollapseButton(false);
            }
        }
        else
        {
            if (m_CollapsibleHeader)
            {
                m_CollapsibleHeader.ShowCollapseButton(true);
            }
        }
        #endif
    }
References m_CollapsibleHeader, and Header::ShowCollapseButton().
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), Insert(), Remove(), Toggle(), and VicinityContainer::UpdateInterval().
Member Data Documentation
m_CollapsibleHeader
protected ref CollapsibleHeader CollapsibleContainer::m_CollapsibleHeader private
Definition at line 3 of file collapsiblecontainer.c.
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), CollapsibleContainer(), GetHeader(), AttachmentCategoriesContainer::IsHeaderActive(), OnHide(), AttachmentCategoriesContainer::OnHide(), PlayerContainer::PlayerContainer(), SetCollapsibleHeaderArrowState(), SetHeader(), AttachmentCategoriesContainer::SetHeaderName(), ZombieContainer::SetHeaderName(), UpdateCollapseButtons(), AttachmentCategoriesContainer::UpdateInterval(), and VicinityContainer::VicinityContainer().
m_Hidden
protected bool CollapsibleContainer::m_Hidden private
Definition at line 4 of file collapsiblecontainer.c.
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), VicinityContainer::CollapseButtonOnMouseButtonDown(), Insert(), IsHidden(), LoadDefaultState(), OnHide(), OnShow(), Toggle(), AttachmentCategoriesContainer::UpdateInterval(), and AttachmentCategoriesContainer::UpdateRadialIcon().