DayzKode: VehicleBattery Class Reference
VehicleBattery Class Reference
Private Member Functions
override bool CanDetachAttachment (EntityAI parent)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI player)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool DisplayNameRuinAttach ()
float GetEfficiency0To1 ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
override void OnEnergyAdded ()
override void OnEnergyConsumed ()
override void OnInventoryEnter (Man player)
override void OnMovedInsideCargo (EntityAI container)
override void OnQuantityChanged (float delta)
override void SetActions ()
override void SetCEBasedQuantity ()
override bool ShowZonesHealth ()
void VehicleBattery ()
Private Attributes
private int m_Efficiency0To10
ENERGY CONSUMPTION.
Static Private Attributes
static private float m_EfficiencyDecayStart = 0.1
Detailed Description
Definition at line 1 of file vehiclebattery.c.
Constructor & Destructor Documentation
VehicleBattery()
void VehicleBattery::VehicleBattery () inline private
Definition at line 166 of file vehiclebattery.c.
    {
        m_Efficiency0To10 = 10;
        RegisterNetSyncVariableInt("m_Efficiency0To10");
    }
References m_Efficiency0To10.
Member Function Documentation
CanDetachAttachment()
override bool VehicleBattery::CanDetachAttachment (EntityAI parent) inline private
Definition at line 21 of file vehiclebattery.c.
    {
        return true;
    }
CanDisplayAttachmentSlot()
override bool VehicleBattery::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 126 of file vehiclebattery.c.
    {
        if ( GetCompEM().IsPlugged() )
            return false;
        return super.CanDisplayAttachmentSlot( slot_id );
    }
CanPutAsAttachment()
override bool VehicleBattery::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file vehiclebattery.c.
    {
        if (!super.CanPutAsAttachment(parent))
            return false;
        string obj_type = parent.GetType();
        if ( parent.IsInherited(BatteryCharger) )
        {
            BatteryCharger charger = BatteryCharger.Cast( parent );
            return charger.CanReceiveAttachment(this, InventorySlots.INVALID);
        }
        if (GetCompEM().GetPluggedDevice())
            return false;
        return true;
    }
References ItemBase::BatteryCharger().
CanPutInCargo()
override bool VehicleBattery::CanPutInCargo (EntityAI parent) inline private
Definition at line 58 of file vehiclebattery.c.
    {
        super.CanPutInCargo( parent );
        ItemBase powered_device = ItemBase.Cast( GetCompEM().GetPluggedDevice() ); // Should return metal wire or barbed wire attachment
        if ( powered_device )
        {
            //We block placing in cargo if metal wire is plugged
            //metal wires plugged to batteries in cargo cause too many issues for little gameplay gain
            if ( powered_device.IsInherited( MetalWire ) )
            {
                return false;
            }
        }
        return true;
    }
References ItemBase::MetalWire().
CanPutIntoHands()
override bool VehicleBattery::CanPutIntoHands (EntityAI player) inline private
Definition at line 34 of file vehiclebattery.c.
    {
        if ( !super.CanPutIntoHands( parent ) )
        {
            return false;
        }
        if ( HasEnergyManager() )
        {
            ItemBase powered_device = ItemBase.Cast( GetCompEM().GetPluggedDevice() ); // Should return metal wire or barbed wire attachment
            if ( powered_device  &&  powered_device.IsInherited( MetalWire ) )
            {
                return true;
            }
            else if (powered_device)
            {
                return false;
            }
        }
        return true;
    }
References ItemBase::MetalWire().
CanReceiveAttachment()
override bool VehicleBattery::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 26 of file vehiclebattery.c.
    {
        if (GetCompEM().IsPlugged())
            return false;
        return super.CanReceiveAttachment(attachment, slotId);
    }
DisplayNameRuinAttach()
override bool VehicleBattery::DisplayNameRuinAttach () inline private
Definition at line 133 of file vehiclebattery.c.
    {
        return true;
    }
GetEfficiency0To1()
float VehicleBattery::GetEfficiency0To1 () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 174 of file vehiclebattery.c.
    {
        return m_Efficiency0To10 * 0.1;
    }
References m_Efficiency0To10.
GetEfficiencyDecayStart()
float VehicleBattery::GetEfficiencyDecayStart () inline private
Returns efficiency of this battery. The value is synchronized from server to all clients and is accurate down to 0.1 unit.
Definition at line 180 of file vehiclebattery.c.
    {
        return m_EfficiencyDecayStart;
    }
References m_EfficiencyDecayStart.
OnEnergyAdded()
override void VehicleBattery::OnEnergyAdded () inline private
Definition at line 210 of file vehiclebattery.c.
    {
        super.OnEnergyAdded();
        if ( GetGame().IsServer() )
        {
            float energy_coef = GetCompEM().GetEnergy0To1();
            if ( energy_coef < m_EfficiencyDecayStart  &&  m_EfficiencyDecayStart > 0)
            {
                m_Efficiency0To10 = Math.Round(  (energy_coef / m_EfficiencyDecayStart) * 10  );
                SetSynchDirty();
            }
            else
            {
                m_Efficiency0To10 = 10;
                SetSynchDirty();
            }
        }
    }
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnEnergyConsumed()
override void VehicleBattery::OnEnergyConsumed () inline private
Definition at line 193 of file vehiclebattery.c.
    {
        super.OnEnergyConsumed();
        if ( GetGame().IsServer() )
        {
            float energy_coef = GetCompEM().GetEnergy0To1();
            if ( energy_coef < m_EfficiencyDecayStart  &&  m_EfficiencyDecayStart > 0 )
            {
                m_Efficiency0To10 = Math.Round(  (energy_coef / m_EfficiencyDecayStart) * 10  );
            }
            SetSynchDirty();
        }
    }
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnInventoryEnter()
override void VehicleBattery::OnInventoryEnter (Man player) inline private
Definition at line 76 of file vehiclebattery.c.
    {
        super.OnInventoryEnter(player);
        if (GetHierarchyParent() == player || (GetHierarchyParent() && GetHierarchyParent().GetInventory().GetCargo()))
        {
            if ( HasEnergyManager() )
            {
                ItemBase powered_device = ItemBase.Cast( GetCompEM().GetPluggedDevice() ); // Should return metal wire or barbed wire attachment
                if ( powered_device )
                {
                    if ( powered_device.IsInherited( MetalWire ) )
                    {
                        //Unplug the device the wire is powering, but keep wire plugged to battery
                        if ( powered_device.GetCompEM().IsPlugged() )
                            powered_device.GetCompEM().UnplugDevice( powered_device.GetCompEM().GetPluggedDevice() );
                    }
                    else
                    {
                        this.GetCompEM().UnplugAllDevices();
                    }
                }
            }
        }
    }
References GetCargo(), and ItemBase::MetalWire().
OnMovedInsideCargo()
override void VehicleBattery::OnMovedInsideCargo (EntityAI container) inline private
Definition at line 103 of file vehiclebattery.c.
    {
        super.OnMovedInsideCargo(container);
        if ( HasEnergyManager() )
        {
            ItemBase powered_device = ItemBase.Cast( GetCompEM().GetPluggedDevice() ); // Should return metal wire or barbed wire attachment
            if ( powered_device )
            {
                //Should not be possible, but better safe than sorry
                if ( powered_device.IsInherited( MetalWire ) )
                {
                    powered_device.GetCompEM().UnplugAllDevices();
                }
                else
                {
                    this.GetCompEM().UnplugAllDevices();
                }
            }
        }
    }
References ItemBase::MetalWire().
OnQuantityChanged()
override void VehicleBattery::OnQuantityChanged (float delta) inline private
Definition at line 154 of file vehiclebattery.c.
    {
        super.OnQuantityChanged(delta);
    }
SetActions()
override void VehicleBattery::SetActions () inline private
Definition at line 143 of file vehiclebattery.c.
    {
        super.SetActions();
        //AddAction(ActionAttach);
        AddAction(ActionAttachOnSelection);
        AddAction(ActionDetach);
        //AddAction(ActionAttachPowerSourceToPanel); SHOULD NOT BE USED ANYMORE
        AddAction(ActionPlugTargetIntoThis);
    }
References ActionDetach(), and AddAction().
SetCEBasedQuantity()
override void VehicleBattery::SetCEBasedQuantity () inline private
Definition at line 186 of file vehiclebattery.c.
    {
        super.SetCEBasedQuantity();
        if ( GetCompEM() )
            GetCompEM().SetEnergy( GetCompEM().GetEnergyMax() * ( GetQuantity() / GetQuantityMax() ) );
    }
References GetQuantity(), and GetQuantityMax().
ShowZonesHealth()
override bool VehicleBattery::ShowZonesHealth () inline private
Definition at line 138 of file vehiclebattery.c.
    {
        return true;
    }
Member Data Documentation
m_Efficiency0To10
private int VehicleBattery::m_Efficiency0To10 private
ENERGY CONSUMPTION.
Definition at line 163 of file vehiclebattery.c.
Referenced by GetEfficiency0To1(), OnEnergyAdded(), OnEnergyConsumed(), and VehicleBattery().
m_EfficiencyDecayStart
private float VehicleBattery::m_EfficiencyDecayStart = 0.1 static private
Definition at line 164 of file vehiclebattery.c.
Referenced by GetEfficiencyDecayStart(), OnEnergyAdded(), and OnEnergyConsumed().