DayzKode: ActionTransferLiquid Class Reference
ActionTransferLiquid Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTransferLiquid ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override string GetText ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasProneException ()
override void OnEndAnimationLoop (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoop (ActionData action_data)
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 24 of file actiontransferliquid.c.
Constructor & Destructor Documentation
ActionTransferLiquid()
void ActionTransferLiquid::ActionTransferLiquid () inline private
Definition at line 26 of file actiontransferliquid.c.
    {
        m_CallbackClass = ActionTransferLiquidCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EMPTY_VESSEL;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_EMPTY_VESSEL;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionTransferLiquid::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 54 of file actiontransferliquid.c.
    {
        ItemBase target_item = ItemBase.Cast(target.GetObject());
        if ( target_item && item )
        {
            bool can_drain = Liquid.CanTransfer(target_item,item);
            bool can_pour = Liquid.CanTransfer(item,target_item);
            if (can_drain && can_pour)
            {
                return true;
            }
            else if (!can_pour && can_drain)
            {
                if ( (!GetGame().IsDedicatedServer()) && !player.GetLiquidTendencyDrain() )
                {
                    player.SetLiquidTendencyDrain(true);
                    return false;
                }
                else
                {
                    return true;
                }
            }
            else if (!can_drain && can_pour)
            {
                if ( (!GetGame().IsDedicatedServer()) && player.GetLiquidTendencyDrain() )
                {
                    player.SetLiquidTendencyDrain(false);
                    return false;
                }
                else
                {
                    return true;
                }
            }
        }
        return false;
    }
References Liquid::CanTransfer(), and GetGame().
CreateActionData()
override ActionData ActionTransferLiquid::CreateActionData () inline private
Definition at line 111 of file actiontransferliquid.c.
    {
        TransferLiquidActionData action_data = new TransferLiquidActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionTransferLiquid::CreateConditionComponents () inline private
Definition at line 34 of file actiontransferliquid.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetText()
override string ActionTransferLiquid::GetText () inline private
Definition at line 45 of file actiontransferliquid.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player.GetLiquidTendencyDrain() )
            return "#drain_liquid";
        else
            return "#pour_liquid";
    }
References GetGame(), and GetPlayer().
HandleReciveData()
override void ActionTransferLiquid::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 141 of file actiontransferliquid.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        TransferLiquidActionReciveData recive_data_transfer = TransferLiquidActionReciveData.Cast(action_recive_data);
        TransferLiquidActionData.Cast(action_data).m_Tendency = recive_data_transfer.m_TendencyRecived;
    }
References TransferLiquidActionReciveData::m_TendencyRecived.
HasProneException()
override bool ActionTransferLiquid::HasProneException () inline private
Definition at line 40 of file actiontransferliquid.c.
    {
        return true;
    }
OnEndAnimationLoop()
override void ActionTransferLiquid::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 165 of file actiontransferliquid.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            Bottle_Base target_vessel = Bottle_Base.Cast( action_data.m_Target.GetObject());
            Param1<bool> play = new Param1<bool>( false );
            if (TransferLiquidActionData.Cast(action_data).m_Tendency)
                GetGame().RPCSingleParam( target_vessel, SoundTypeBottle.EMPTYING, play, true );
            else
                GetGame().RPCSingleParam( target_vessel, SoundTypeBottle.POURING, play, true );
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnFinishProgressServer()
override void ActionTransferLiquid::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 106 of file actiontransferliquid.c.
    {
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References ActionData::m_Player, and m_SpecialtyWeight.
OnStartAnimationLoop()
override void ActionTransferLiquid::OnStartAnimationLoop (ActionData action_data) inline private
Definition at line 149 of file actiontransferliquid.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            Bottle_Base vessel_in_hands = Bottle_Base.Cast( action_data.m_Target.GetObject() );
            Param1<bool> play = new Param1<bool>( true );
            if (TransferLiquidActionData.Cast(action_data))
            {
                if (TransferLiquidActionData.Cast(action_data).m_Tendency == true)
                    GetGame().RPCSingleParam( vessel_in_hands, SoundTypeBottle.EMPTYING, play, true );
                else if (!TransferLiquidActionData.Cast(action_data).m_Tendency == false)
                    GetGame().RPCSingleParam( vessel_in_hands, SoundTypeBottle.POURING, play, true );
            }
        }
    }
References GetGame(), ActionData::m_Target, and CGame::RPCSingleParam().
OnStartClient()
override void ActionTransferLiquid::OnStartClient (ActionData action_data) inline private
Definition at line 95 of file actiontransferliquid.c.
    {
        TransferLiquidActionData.Cast(action_data).m_Tendency = action_data.m_Player.GetLiquidTendencyDrain();
    }
References ActionData::m_Player.
OnStartServer()
override void ActionTransferLiquid::OnStartServer (ActionData action_data) inline private
Definition at line 100 of file actiontransferliquid.c.
    {
        if (!GetGame().IsMultiplayer())
            TransferLiquidActionData.Cast(action_data).m_Tendency = action_data.m_Player.GetLiquidTendencyDrain();
    }
References GetGame(), and ActionData::m_Player.
ReadFromContext()
override bool ActionTransferLiquid::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 124 of file actiontransferliquid.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new TransferLiquidActionReciveData;
        }
        TransferLiquidActionReciveData recive_data_transfer = TransferLiquidActionReciveData.Cast(action_recive_data);
        super.ReadFromContext(ctx, action_recive_data);
        bool tendency_drain;
        if ( !ctx.Read(tendency_drain) )
            return false;
        recive_data_transfer.m_TendencyRecived = tendency_drain;
        return true;
    }
References TransferLiquidActionReciveData::m_TendencyRecived, and Serializer::Read().
WriteToContext()
override void ActionTransferLiquid::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 117 of file actiontransferliquid.c.
    {
        super.WriteToContext(ctx, action_data);
        ctx.Write(action_data.m_Player.GetLiquidTendencyDrain());
    }
References ActionData::m_Player, and Serializer::Write().