DayzKode: InjurySoundHandlerBase Class Reference
InjurySoundHandlerBase Class Reference
Private Member Functions
eInjurySoundZones DetermineInjuryZone (eInjuryHandlerLevels level)
void PlaySound (eInjurySoundZones zone)
void ProcessSound (eInjurySoundZones zone)
override void Update ()
Private Attributes
eInjuryHandlerLevels m_InjuryLevel
eInjurySoundZones m_InjurySoundZone
ref HumanMovementState m_MovementState = new HumanMovementState
float m_SoundTime
const float SOUND_INTERVALS_HEAVY_MAX = 12
const float SOUND_INTERVALS_HEAVY_MIN = 3
const float SOUND_INTERVALS_LIGHT_MAX = 30
const float SOUND_INTERVALS_LIGHT_MIN = 15
const float SOUND_INTERVALS_MEDIUM_MAX = 25
const float SOUND_INTERVALS_MEDIUM_MIN = 10
Detailed Description
Definition at line 24 of file injurysoundhandler.c.
Member Function Documentation
DetermineInjuryZone()
eInjurySoundZones InjurySoundHandlerBase::DetermineInjuryZone (eInjuryHandlerLevels level) inline private
Definition at line 36 of file injurysoundhandler.c.
    {
        if( level == eInjuryHandlerLevels.PRISTINE )
            return eInjurySoundZones.NONE;
        m_Player.GetMovementState(m_MovementState);
        int speed = m_MovementState.m_iMovement;
        int stance = m_MovementState.m_iStanceIdx;
        //int stance_lvl_down = DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH;
        if( speed == 0 )
            return eInjurySoundZones.NONE;
        level--;// shift the level so that we play from higher damage
        if( stance ==  DayZPlayerConstants.STANCEIDX_PRONE || stance ==  DayZPlayerConstants.STANCEIDX_CROUCH )
        {
            level--;
        }
        if( speed == DayZPlayerConstants.MOVEMENTIDX_WALK )
        {
            level--;
        }
        else if(speed == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
        {
            level++;
        }
        level = Math.Clamp(level, eInjurySoundZones.NONE, eInjurySoundZones.HEAVY);
        return level;
    }
References Math::Clamp(), m_MovementState, and m_Player.
Referenced by Update().
PlaySound()
void InjurySoundHandlerBase::PlaySound (eInjurySoundZones zone) inline private
Definition at line 111 of file injurysoundhandler.c.
    {
        m_Player.PlaySoundEvent(EPlayerSoundEventID.INJURED_LIGHT);
    }
References m_Player.
ProcessSound()
void InjurySoundHandlerBase::ProcessSound (eInjurySoundZones zone) inline private
Definition at line 81 of file injurysoundhandler.c.
    {
        //Print("injury sound zone:"+ zone);
        // process sound here
        if( GetGame().GetTime() > m_SoundTime)
        {
            float offset_time;
            if(zone == eInjurySoundZones.NONE)
            {
                offset_time = 3000;
                m_SoundTime = GetGame().GetTime() + offset_time;
                return;
            }
            if(zone == eInjurySoundZones.LIGHT)
            {
                offset_time = Math.RandomFloatInclusive(SOUND_INTERVALS_LIGHT_MIN, SOUND_INTERVALS_LIGHT_MAX) * 1000;
            }
            else if(zone == eInjurySoundZones.MEDIUM)
            {
                offset_time = Math.RandomFloatInclusive(SOUND_INTERVALS_MEDIUM_MIN, SOUND_INTERVALS_MEDIUM_MAX) * 1000;
            }
            else if(zone == eInjurySoundZones.HEAVY)
            {
                offset_time = Math.RandomFloatInclusive(SOUND_INTERVALS_HEAVY_MIN, SOUND_INTERVALS_HEAVY_MAX) * 1000;
            }
            m_SoundTime = GetGame().GetTime() + offset_time;
            PlaySound(zone);
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), m_SoundTime, PlaySound(), Math::RandomFloatInclusive(), SOUND_INTERVALS_LIGHT_MAX, and SOUND_INTERVALS_LIGHT_MIN.
Update()
override void InjurySoundHandlerBase::Update () inline private
Definition at line 70 of file injurysoundhandler.c.
    {
        m_InjuryLevel = m_Player.m_HealthLevel;
        if( m_InjuryLevel != eInjuryHandlerLevels.PRISTINE )
        {
            eInjurySoundZones zone = DetermineInjuryZone(m_Player.m_HealthLevel);
            ProcessSound(zone);
        }
    }
References DetermineInjuryZone(), m_Player, and ProcessSound().
Member Data Documentation
m_InjuryLevel
eInjuryHandlerLevels InjurySoundHandlerBase::m_InjuryLevel private
Definition at line 32 of file injurysoundhandler.c.
m_InjurySoundZone
eInjurySoundZones InjurySoundHandlerBase::m_InjurySoundZone private
Definition at line 31 of file injurysoundhandler.c.
m_MovementState
ref HumanMovementState InjurySoundHandlerBase::m_MovementState = new HumanMovementState private
Definition at line 30 of file injurysoundhandler.c.
m_SoundTime
float InjurySoundHandlerBase::m_SoundTime private
Definition at line 33 of file injurysoundhandler.c.
SOUND_INTERVALS_HEAVY_MAX
const float InjurySoundHandlerBase::SOUND_INTERVALS_HEAVY_MAX = 12 private
Definition at line 28 of file injurysoundhandler.c.
SOUND_INTERVALS_HEAVY_MIN
const float InjurySoundHandlerBase::SOUND_INTERVALS_HEAVY_MIN = 3 private
Definition at line 28 of file injurysoundhandler.c.
SOUND_INTERVALS_LIGHT_MAX
const float InjurySoundHandlerBase::SOUND_INTERVALS_LIGHT_MAX = 30 private
Definition at line 26 of file injurysoundhandler.c.
SOUND_INTERVALS_LIGHT_MIN
const float InjurySoundHandlerBase::SOUND_INTERVALS_LIGHT_MIN = 15 private
Definition at line 26 of file injurysoundhandler.c.
SOUND_INTERVALS_MEDIUM_MAX
const float InjurySoundHandlerBase::SOUND_INTERVALS_MEDIUM_MAX = 25 private
Definition at line 27 of file injurysoundhandler.c.
SOUND_INTERVALS_MEDIUM_MIN
const float InjurySoundHandlerBase::SOUND_INTERVALS_MEDIUM_MIN = 10 private
Definition at line 27 of file injurysoundhandler.c.