DayzKode: TrapTrigger Class Reference
TrapTrigger Class Reference
Trigger used by traps.
Private Member Functions
override protected bool CanAddObjectAsInsider (Object object)
override protected void OnEnterServerEvent (TriggerInsider insider)
override protected void OnLeaveServerEvent (TriggerInsider insider)
void SetParentObject (TrapBase obj)
Private Attributes
TrapBase m_ParentObj
Detailed Description
Trigger used by traps.
Definition at line 2 of file traptrigger.c.
Member Function Documentation
CanAddObjectAsInsider()
override protected bool TrapTrigger::CanAddObjectAsInsider (Object object) inline private
Definition at line 18 of file traptrigger.c.
    {
        return object.IsInherited(EntityAI) && m_ParentObj && m_ParentObj.IsActive();
    }
References m_ParentObj.
OnEnterServerEvent()
override protected void TrapTrigger::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 23 of file traptrigger.c.
    {
        #ifdef DEVELOPER
        m_CanSendDbg = false;
        #endif
        if (m_ParentObj && m_ParentObj.IsActive())
        {
            m_ParentObj.SnapOnObject(EntityAI.Cast(insider.GetObject()));
        }
    }
References TriggerInsider::GetObject(), and m_ParentObj.
OnLeaveServerEvent()
override protected void TrapTrigger::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 35 of file traptrigger.c.
    {
        if (m_ParentObj && m_ParentObj.IsActive())
        {
            m_ParentObj.RemoveFromObject(EntityAI.Cast(insider.GetObject()));
        }
    }
References TriggerInsider::GetObject(), and m_ParentObj.
SetParentObject()
void TrapTrigger::SetParentObject (TrapBase obj) inline private
Definition at line 10 of file traptrigger.c.
    {
        if (GetGame().IsServer())
        {
            m_ParentObj = obj;
        }
    }
References GetGame(), and m_ParentObj.
Referenced by CreateTrigger(), and TrapBase::CreateTrigger().
Member Data Documentation
m_ParentObj
TrapBase TrapTrigger::m_ParentObj private
Definition at line 4 of file traptrigger.c.
Referenced by CanAddObjectAsInsider(), OnEnterServerEvent(), OnLeaveServerEvent(), and SetParentObject().