DayzKode: RemoteDetonatorTrigger Class Reference
RemoteDetonatorTrigger Class Reference
Private Member Functions
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
EntityAI GetControlledDevice ()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
bool IsConnected ()
override bool IsKit ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnAnimationPhaseStarted (string animSource, float phase)
override void OnCEUpdate ()
override void OnVariablesSynchronized ()
override void PairRemote (notnull EntityAI trigger)
void RemoteDetonatorTrigger ()
override void SetActions ()
void SetControlledDevice (EntityAI pDevice)
override void UnpairRemote ()
Static Private Member Functions
static RemoteDetonatorTrigger SpawnInPlayerHands (notnull EntityAI pEntity)
Private Attributes
protected const string ANIM_PHASE_TRIGGER = "trigger"
protected bool m_LED
protected ref RemotelyActivatedItemBehaviour m_RAIB
Detailed Description
Definition at line 46 of file remotedetonator.c.
Constructor & Destructor Documentation
RemoteDetonatorTrigger()
void RemoteDetonatorTrigger::RemoteDetonatorTrigger () inline private
Definition at line 53 of file remotedetonator.c.
    {
        m_RAIB = new RemotelyActivatedItemBehaviour(this);
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
        RegisterNetSyncVariableInt("m_LastLEDState", 0, EnumTools.GetEnumSize(ERemoteDetonatorLEDState));
        UpdateLED(m_LastLEDState);
    }
References EnumTools::GetEnumSize(), m_LastLEDState, m_RAIB, and UpdateLED().
Member Function Documentation
EEItemLocationChanged()
override void RemoteDetonatorTrigger::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 81 of file remotedetonator.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (m_RAIB)
        {
            m_RAIB.Pair();
        }
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
GetControlledDevice()
EntityAI RemoteDetonatorTrigger::GetControlledDevice () inline private
Definition at line 149 of file remotedetonator.c.
    {
        return m_RAIB.GetPairDevice();
    }
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by ActionCondition(), ActionTriggerRemotely::ActionCondition(), OnActivatedByItem(), OnCEUpdate(), and ActionTriggerRemotely::OnExecuteServer().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour RemoteDetonatorTrigger::GetRemotelyActivatedItemBehaviour () inline private
Definition at line 91 of file remotedetonator.c.
    {
        return m_RAIB;
    }
References m_RAIB.
IsConnected()
bool RemoteDetonatorTrigger::IsConnected () inline private
Definition at line 144 of file remotedetonator.c.
    {
        return m_RAIB.IsPaired();
    }
References RemotelyActivatedItemBehaviour::IsPaired(), and m_RAIB.
Referenced by ActionCondition(), ActionTriggerRemotely::ActionCondition(), OnCEUpdate(), and ActionTriggerRemotely::OnExecuteServer().
IsKit()
override bool RemoteDetonatorTrigger::IsKit () inline private
Definition at line 64 of file remotedetonator.c.
    {
        return false;
    }
OnActivatedByItem()
override void RemoteDetonatorTrigger::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 124 of file remotedetonator.c.
    {
        if (GetGame().IsServer())
        {
            if (m_RAIB.IsPaired() && !IsRuined())
            {
                ItemBase device = ItemBase.Cast(GetControlledDevice());
                if (device && vector.DistanceSq(GetPosition(), device.GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
                {
                    device.OnActivatedByItem(this);
                }
            }
        }
    }
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetControlledDevice(), GetGame(), GetPosition, RemotelyActivatedItemBehaviour::IsPaired(), IsRuined(), m_RAIB, and Math::SqrFloat().
OnAnimationPhaseStarted()
override void RemoteDetonatorTrigger::OnAnimationPhaseStarted (string animSource, float phase) inline private
Definition at line 182 of file remotedetonator.c.
    {
        if (animSource == ANIM_PHASE_TRIGGER)
        {
            if (phase > 0.01)
            {
                UpdateLED(ERemoteDetonatorLEDState.OFF);
            }
        }
    }
References ANIM_PHASE_TRIGGER, and UpdateLED().
OnCEUpdate()
override void RemoteDetonatorTrigger::OnCEUpdate () inline private
Definition at line 96 of file remotedetonator.c.
    {
        super.OnCEUpdate();
        if (!IsRuined() && IsConnected() && GetControlledDevice())
        {
            if (vector.DistanceSq(GetPosition(), GetControlledDevice().GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
            {
                UpdateLED(ERemoteDetonatorLEDState.LIT);
                return;
            }
        }
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetControlledDevice(), GetPosition, IsConnected(), IsRuined(), Math::SqrFloat(), and UpdateLED().
OnVariablesSynchronized()
override void RemoteDetonatorTrigger::OnVariablesSynchronized () inline private
Definition at line 69 of file remotedetonator.c.
    {
        super.OnVariablesSynchronized();
        if (m_RAIB)
        {
            m_RAIB.OnVariableSynchronized();
        }
        UpdateLED(m_LastLEDState);
    }
References m_LastLEDState, m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), and UpdateLED().
PairRemote()
override void RemoteDetonatorTrigger::PairRemote (notnull EntityAI trigger) inline private
Definition at line 113 of file remotedetonator.c.
    {
        m_RAIB.Pair(trigger);
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
Referenced by OnEndServer().
SetActions()
override void RemoteDetonatorTrigger::SetActions () inline private
Definition at line 193 of file remotedetonator.c.
    {
        super.SetActions();
        RemoveAction(ActionAttachExplosivesTrigger);
        AddAction(ActionAttachOnTrap);
        AddAction(ActionDisarmExplosiveWithRemoteDetonator);
        AddAction(ActionTriggerRemotely);
    }
References ActionAttachExplosivesTrigger(), ActionDisarmExplosiveWithRemoteDetonator(), AddAction(), and RemoveAction().
SetControlledDevice()
void RemoteDetonatorTrigger::SetControlledDevice (EntityAI pDevice) inline private
Definition at line 139 of file remotedetonator.c.
    {
        m_RAIB.Pair(pDevice);
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
Referenced by OnEndServer(), and ClaymoreMine::OnPlacementComplete().
SpawnInPlayerHands()
static RemoteDetonatorTrigger RemoteDetonatorTrigger::SpawnInPlayerHands (notnull EntityAI pEntity) inline static private
item replaced, use different IK
Definition at line 154 of file remotedetonator.c.
    {
        string type = "RemoteDetonatorTrigger";
        RemoteDetonatorTrigger rdt;
        PlayerBase player = PlayerBase.Cast(pEntity);
        if (player)
        {
            if (player.GetItemInHands())
            {
                ReplaceItemWithNewLambdaBase lambda = new ReplaceItemWithNewLambdaBase(player.GetItemInHands(), type);
                MiscGameplayFunctions.TurnItemIntoItemEx(player, lambda);
                rdt = RemoteDetonatorTrigger.Cast(player.GetItemInHands());
            }
            else
            {
                rdt = RemoteDetonatorTrigger.Cast(player.GetHumanInventory().CreateInHands(type));
            }
            if (player.GetItemInHands())
            {
                player.GetItemAccessor().OnItemInHandsChanged();
            }
        }
        return rdt;
    }
Referenced by CreateRemoteDetonatorReceiverAsAttachment(), and ClaymoreMine::OnPlacementComplete().
UnpairRemote()
override void RemoteDetonatorTrigger::UnpairRemote () inline private
Definition at line 118 of file remotedetonator.c.
    {
        UpdateLED(ERemoteDetonatorLEDState.OFF);
        m_RAIB.Unpair();
    }
References m_RAIB, RemotelyActivatedItemBehaviour::Unpair(), and UpdateLED().
Member Data Documentation
ANIM_PHASE_TRIGGER
protected const string RemoteDetonatorTrigger::ANIM_PHASE_TRIGGER = "trigger" private
Definition at line 48 of file remotedetonator.c.
Referenced by OnAnimationPhaseStarted().
m_LED
protected bool RemoteDetonatorTrigger::m_LED private
Definition at line 50 of file remotedetonator.c.
m_RAIB
protected ref RemotelyActivatedItemBehaviour RemoteDetonatorTrigger::m_RAIB private
Definition at line 51 of file remotedetonator.c.
Referenced by EEItemLocationChanged(), GetControlledDevice(), GetRemotelyActivatedItemBehaviour(), IsConnected(), OnActivatedByItem(), OnVariablesSynchronized(), PairRemote(), RemoteDetonatorTrigger(), SetControlledDevice(), and UnpairRemote().