DayzKode: ActionPlugTargetIntoThis Class Reference
ActionPlugTargetIntoThis Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPlugTargetIntoThis ()
override bool Can (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override bool IsDeploymentAction ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
Private Attributes
bool m_Retoggle
Detailed Description
Definition at line 1 of file actionplugtargetintothis.c.
Constructor & Destructor Documentation
ActionPlugTargetIntoThis()
void ActionPlugTargetIntoThis::ActionPlugTargetIntoThis () inline private
Definition at line 5 of file actionplugtargetintothis.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE;
        m_Retoggle = false;
        m_Text = "#connect_together";
    }
References AnimatedActionBase::m_CommandUID, m_Retoggle, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionPlugTargetIntoThis::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 45 of file actionplugtargetintothis.c.
    {
        EntityAI target_EAI = EntityAI.Cast( target.GetObject() ); //Keep for backwards compatibility
        ItemBase target_IB = ItemBase.Cast( target.GetObject() );
        //Prevent plugging to items in inventory
        if ( target_IB && target_IB.GetHierarchyRoot() == target_IB &&  item  &&  target_IB.HasEnergyManager()  &&  item.HasEnergyManager() )
        {
            if ( !target_IB.GetCompEM().IsPlugged()  &&  item.GetCompEM().CanReceivePlugFrom(target_IB) )
            {
                //hotfix, re-work entire action!
                return target_IB.IsElectricAppliance();
            }
            // Special case for vehicle batteries
            if ( item.IsInherited(VehicleBattery))
            {
                MetalWire metal_wire = MetalWire.Cast( item.GetCompEM().GetPluggedDevice() );
                if ( metal_wire  &&  metal_wire.GetCompEM().CanReceivePlugFrom(target_IB) )
                {
                    return true; // We can power the action_data.m_Target from vehicle battery because it has metal wire attached.
                }
            }
        }
        return false;
    }
References ItemBase::IsElectricAppliance().
Can()
override bool ActionPlugTargetIntoThis::Can (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 18 of file actionplugtargetintothis.c.
    {
        if ( super.Can( player, target, item ) )
        {
            if ( player.IsPlacingLocal() )
            {
                m_Retoggle = true;
                player.GetHologramLocal().SetIsHidden( true );
                player.GetHologramLocal().GetProjectionEntity().HideAllSelections();
            }
        }
        if ( !super.Can( player, target, item ) )
        {
            if ( m_Retoggle )
            {
                m_Retoggle = false;
                player.GetHologramLocal().SetIsHidden( false );
                player.GetHologramLocal().GetProjectionEntity().ShowAllSelections();
            }
        }
        return super.Can( player, target, item );
    }
References m_Retoggle.
CreateConditionComponents()
override void ActionPlugTargetIntoThis::CreateConditionComponents () inline private
Definition at line 12 of file actionplugtargetintothis.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsDeploymentAction()
override bool ActionPlugTargetIntoThis::IsDeploymentAction () inline private
Definition at line 74 of file actionplugtargetintothis.c.
    {
        return true;
    }
OnExecuteClient()
override void ActionPlugTargetIntoThis::OnExecuteClient (ActionData action_data) inline private
Definition at line 84 of file actionplugtargetintothis.c.
    {
        //action_data.m_Player.PlacingCancelLocal(); // Cance advanced placement without unplugging main object from power source
        m_Retoggle = false;
    }
References m_Retoggle.
OnExecuteServer()
override void ActionPlugTargetIntoThis::OnExecuteServer (ActionData action_data) inline private
Definition at line 79 of file actionplugtargetintothis.c.
    {
        Process(action_data);
    }
References Process().
Process()
void ActionPlugTargetIntoThis::Process (ActionData action_data) inline private
Definition at line 90 of file actionplugtargetintothis.c.
    {
        ItemBase target_IB = ItemBase.Cast( action_data.m_Target.GetObject() );
        if ( action_data.m_MainItem.IsInherited(VehicleBattery) )
        {
            // Car/truck batteries can have a metal wire attached through which they can power common electric appliances
            MetalWire metal_wire = MetalWire.Cast( action_data.m_MainItem.GetCompEM().GetPluggedDevice() );
            if (metal_wire)
            {
                target_IB.GetCompEM().PlugThisInto(metal_wire);
            }
        }
        else
        {
            // Everything else in general
            target_IB.GetCompEM().PlugThisInto(action_data.m_MainItem);
        }
        // Special case for spotlights
        if ( target_IB.IsInherited(Spotlight) )
        {
            Spotlight spotlight = Spotlight.Cast( target_IB );
            spotlight.Unfold();
        }
        target_IB.GetInventory().TakeEntityAsAttachment( InventoryMode.LOCAL, action_data.m_MainItem );
        action_data.m_Player.ServerDropEntity( action_data.m_MainItem );
    }
References ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and ItemBase::Unfold().
Referenced by OnExecuteServer().
Member Data Documentation
m_Retoggle
bool ActionPlugTargetIntoThis::m_Retoggle private
Definition at line 3 of file actionplugtargetintothis.c.
Referenced by ActionPlugTargetIntoThis(), Can(), and OnExecuteClient().