DayzKode: DayZPlayerTypeVoiceSoundLookupTable Class Reference
DayZPlayerTypeVoiceSoundLookupTable Class Reference
Private Member Functions
void DayZPlayerTypeVoiceSoundLookupTableImpl ()
override NoiseParams GetNoiseParams (int eventId)
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash)
Static Private Member Functions
static DayZPlayerTypeVoiceSoundLookupTableImpl GetInstance ()
Private Attributes
private autoptr map< int, ref PlayerVoiceLookupTable > m_pSoundTableInstances
private autoptr map< int, PlayerVoiceLookupTable > m_pSoundTables
Static Private Attributes
static private ref DayZPlayerTypeVoiceSoundLookupTableImpl m_instance
Detailed Description
Definition at line 165 of file dayzplayercfgsounds.c.
Member Function Documentation
DayZPlayerTypeVoiceSoundLookupTableImpl()
void DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl () inline private
Definition at line 167 of file dayzplayercfgsounds.c.
    {
        m_pSoundTableInstances = new map<int, ref PlayerVoiceLookupTable>;
        m_pSoundTables = new map<int, PlayerVoiceLookupTable>();
        string cfgPath = "CfgVehicles SurvivorBase AnimEvents SoundVoice ";
        int childCount = GetGame().ConfigGetChildrenCount(cfgPath);
        //Print("childCount:" + childCount);
        for(int i = 0; i < childCount; i++)
        {
            string defName;
            GetGame().ConfigGetChildName(cfgPath, i, defName);
            string defPath = cfgPath + defName + " ";
            int id = GetGame().ConfigGetInt(defPath + "id");
            string tableName;
            GetGame().ConfigGetText(defPath + "soundLookupTable", tableName);
            PlayerVoiceLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
            if(table == NULL)
            {
                table = new PlayerVoiceLookupTable();
                table.LoadTable(tableName);
                m_pSoundTableInstances.Insert(tableName.Hash(), table);
                string noiseName;
                if(GetGame().ConfigGetText(defPath + "noise", noiseName))
                {
                    NoiseParams np = new NoiseParams;
                    np.Load(noiseName);
                    table.SetNoiseParam(np);
                }
            }
            m_pSoundTables.Insert(id, table);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, m_pSoundTables, and PlayerVoiceLookupTable().
Referenced by GetInstance().
GetInstance()
static DayZPlayerTypeVoiceSoundLookupTableImpl DayZPlayerTypeVoiceSoundLookupTable::GetInstance () inline static private
Definition at line 228 of file dayzplayercfgsounds.c.
    {
        if(m_instance == NULL)
            m_instance = new DayZPlayerTypeVoiceSoundLookupTableImpl();
        return m_instance;
    }
References DayZPlayerTypeVoiceSoundLookupTableImpl(), m_instance, and m_instance.
Referenced by DayZPlayerTypeRegisterSounds().
GetNoiseParams()
override NoiseParams DayZPlayerTypeVoiceSoundLookupTable::GetNoiseParams (int eventId) inline private
Definition at line 219 of file dayzplayercfgsounds.c.
    {
        PlayerVoiceLookupTable table = m_pSoundTables.Get(eventId);
        if(table == NULL)
            return NULL;
        return table.GetNoiseParam();
    }
References m_pSoundTables, and PlayerVoiceLookupTable().
GetSoundBuilder()
override SoundObjectBuilder DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder (int eventId, int parameterHash) inline private
Definition at line 206 of file dayzplayercfgsounds.c.
    {
        PlayerVoiceLookupTable table = m_pSoundTables.Get(eventId);
        if(table == NULL)
            return NULL;
        SoundObjectBuilder soundBuilder = table.GetSoundBuilder(parameterHash);
        if(soundBuilder == NULL)
            return NULL;
        return soundBuilder;
    }
References m_pSoundTables, and PlayerVoiceLookupTable().
Referenced by ProcessVoiceEvent().
Member Data Documentation
m_instance
private ref DayZPlayerTypeVoiceSoundLookupTableImpl DayZPlayerTypeVoiceSoundLookupTable::m_instance static private
Definition at line 236 of file dayzplayercfgsounds.c.
Referenced by GetInstance().
m_pSoundTableInstances
private autoptr map<int, ref PlayerVoiceLookupTable> DayZPlayerTypeVoiceSoundLookupTable::m_pSoundTableInstances private
Definition at line 237 of file dayzplayercfgsounds.c.
m_pSoundTables
private autoptr map<int, PlayerVoiceLookupTable> DayZPlayerTypeVoiceSoundLookupTable::m_pSoundTables private
Definition at line 238 of file dayzplayercfgsounds.c.