DayzKode: FireplaceBase Class Reference
FireplaceBase Class Reference
Private Member Functions
override void AfterStoreLoad ()
void BarrelHoles_ColorBase ()
override bool CanAssignAttachmentsToQuickbar ()
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanBeIgnitedBy (EntityAI igniter=NULL)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanDisplayCargo ()
override bool CanExtinguishFire ()
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanLoadAttachment (EntityAI attachment)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseCargo (EntityAI cargo)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanRemoveFromCargo (EntityAI parent)
override bool CanRemoveFromHands (EntityAI player)
override bool CanRemoveFromHands (EntityAI player)
override bool CanShowSmoke ()
override bool CanShowSmoke ()
override void Close ()
void CloseLoad ()
void ContactEvent (IEntity other, vector position)
void DestroyClutterCutter (Object clutter_cutter)
void DestroyClutterCutter (Object clutter_cutter)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EOnContact (IEntity other, Contact extra)
override void EOnTouch (IEntity other, int extra)
void Fireplace ()
void FireplaceIndoor ()
override int GetDamageSystemVersionChange ()
override string GetInvulnerabilityTypeString ()
override string GetPlaceSoundset ()
override string GetPlaceSoundset ()
override protected vector GetSmokeEffectPosition ()
override protected vector GetSmokeEffectPosition ()
override bool HasFlammableMaterial ()
override bool HasFlammableMaterial ()
override bool HasFlammableMaterial ()
override bool HasFlammableMaterial ()
override float HeightStartCheckOverride ()
override bool IsBarrelWithHoles ()
override bool IsBaseFireplace ()
override bool IsFireplaceIndoor ()
override bool IsIgnited ()
override bool IsIgnited ()
override bool IsIgnited ()
override bool IsIgnited ()
override bool IsIndoorOven ()
override bool IsOpen ()
override bool IsPrepareToDelete ()
override bool IsPrepareToDelete ()
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override bool IsThisIgnitionSuccessful (EntityAI item_source=NULL)
override void OnBeforeTryDelete ()
override void OnDebugSpawn ()
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedTarget (EntityAI ignited_item)
override void OnIgnitedThis (EntityAI fire_source)
override void OnIgnitedThis (EntityAI fire_source)
override void OnIgnitedThis (EntityAI fire_source)
override void OnIgnitedThis (EntityAI fire_source)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void Open ()
void OpenLoad ()
void OvenIndoor ()
override void ParticleNormalSmokeStart ()
override void ParticleNormalSmokeStart ()
override void ParticleSmallSmokeStart ()
override void ParticleSmallSmokeStart ()
override void RefreshFireplacePhysics ()
override void RefreshPhysics ()
override void SetActions ()
override void SetActions ()
override void SetCookingEquipment (ItemBase equipment)
void SetFirePointIndex (int fire_point_index)
void SetFirePointIndex (int fire_point_index)
void SetSmokePointPosition (vector smoke_point_pos)
void SetSmokePointPosition (vector smoke_point_pos)
void SoundBarrelClosePlay ()
void SoundBarrelOpenPlay ()
protected void UpdateVisualState ()
Static Private Member Functions
static bool CanIgniteEntityAsFireplace (notnull EntityAI entity)
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world)
static bool CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world)
static int GetFirePointIndex (string action_selection)
static int GetFirePointIndex (string action_selection)
static Fireplace IgniteEntityAsFireplace (notnull EntityAI entity, notnull EntityAI fire_source)
Private Attributes
const string ANIMATION_CLOSED = "LidOn"
const string ANIMATION_OPENED = "LidOff"
bool m_ContactEventProcessing
protected int m_FirePointIndex = 1
protected bool m_IsOpenedClient = false
protected ref OpenableBehaviour m_Openable
protected float m_SmokePosX
protected float m_SmokePosY
protected float m_SmokePosZ
Static Private Attributes
static const string FIREPOINT_ACTION_SELECTION = "fireplace_action"
static const string FIREPOINT_FIRE_POSITION = "fireplace_point"
static const string FIREPOINT_PLACE_ROT = "fireplace_rot"
static const string FIREPOINT_SMOKE_POSITION = "fireplace_smoke"
static const string OVENPOINT_ACTION_SELECTION = "oven_action"
static const string OVENPOINT_FIRE_POSITION = "oven_point"
static const string OVENPOINT_PLACE_ROT = "oven_rot"
static const string OVENPOINT_SMOKE_POSITION = "oven_smoke"
Detailed Description
Definition at line 1 of file barrelholes_colorbase.c.
Member Function Documentation
AfterStoreLoad()
override void FireplaceBase::AfterStoreLoad () inline private
Definition at line 556 of file fireplace.c.
    {
        super.AfterStoreLoad();
        if ( IsBurning() )
        {
            if ( !m_ClutterCutter )
            {
                m_ClutterCutter = GetGame().CreateObjectEx( OBJECT_CLUTTER_CUTTER, GetPosition(), ECE_PLACE_ON_SURFACE );
                m_ClutterCutter.SetOrientation( GetOrientation() );
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), GetOrientation(), GetPosition, IsBurning(), m_ClutterCutter, and OBJECT_CLUTTER_CUTTER.
BarrelHoles_ColorBase()
void FireplaceBase::BarrelHoles_ColorBase () inline private
Definition at line 11 of file barrelholes_colorbase.c.
    {
        //Particles - default for FireplaceBase
        PARTICLE_FIRE_START     = ParticleList.BARREL_FIRE_START;
        PARTICLE_SMALL_FIRE     = ParticleList.BARREL_SMALL_FIRE;
        PARTICLE_NORMAL_FIRE    = ParticleList.BARREL_NORMAL_FIRE;
        PARTICLE_SMALL_SMOKE    = ParticleList.BARREL_SMALL_SMOKE;
        PARTICLE_NORMAL_SMOKE   = ParticleList.BARREL_NORMAL_SMOKE;
        PARTICLE_FIRE_END       = ParticleList.BARREL_FIRE_END;
        PARTICLE_STEAM_END      = ParticleList.BARREL_FIRE_STEAM_2END;
        m_Openable = new OpenableBehaviour(false);
        //synchronized variables
        RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
        ProcessInvulnerabilityCheck(GetInvulnerabilityTypeString());
        m_LightDistance = 50;
    }
References ParticleList::BARREL_FIRE_END, ParticleList::BARREL_FIRE_START, ParticleList::BARREL_FIRE_STEAM_2END, ParticleList::BARREL_NORMAL_FIRE, ParticleList::BARREL_NORMAL_SMOKE, ParticleList::BARREL_SMALL_FIRE, ParticleList::BARREL_SMALL_SMOKE, GetInvulnerabilityTypeString(), m_LightDistance, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
CanAssignAttachmentsToQuickbar()
override bool FireplaceBase::CanAssignAttachmentsToQuickbar () inline private
Definition at line 464 of file fireplace.c.
    {
        return false;
    }
CanBeIgnitedBy() [1/4]
override bool FireplaceBase::CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 474 of file barrelholes_colorbase.c.
    {
        if ( HasAnyKindling() && !IsBurning() && IsOpen() && !GetHierarchyParent() )
        {
            return true;
        }
        return false;
    }
References HasAnyKindling(), IsBurning(), and IsOpen().
CanBeIgnitedBy() [2/4]
override bool FireplaceBase::CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 580 of file fireplace.c.
    {
        return HasAnyKindling() && !IsBurning() && !GetHierarchyParent();
    }
References HasAnyKindling(), and IsBurning().
CanBeIgnitedBy() [3/4]
override bool FireplaceBase::CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 321 of file fireplaceindoor.c.
    {
        if ( HasAnyKindling() && !GetHierarchyParent() )
        {
            return true;
        }
        return false;
    }
References HasAnyKindling().
CanBeIgnitedBy() [4/4]
override bool FireplaceBase::CanBeIgnitedBy (EntityAI igniter = NULL) inline private
Definition at line 303 of file ovenindoor.c.
    {
        if ( HasAnyKindling() && !GetHierarchyParent() )
        {
            return true;
        }
        return false;
    }
References HasAnyKindling().
CanDetachAttachment()
override bool FireplaceBase::CanDetachAttachment (EntityAI parent) inline private
Definition at line 56 of file barrelholes_colorbase.c.
    {
        if ( GetNumberOfItems() == 0)
            return true;
        return false;
    }
References GetNumberOfItems().
CanDisplayAttachmentCategory() [1/2]
override bool FireplaceBase::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 368 of file barrelholes_colorbase.c.
    {
        //super
        if( !super.CanDisplayAttachmentCategory( category_name ) )
        {
            return false;
        }
        //
        if ( ( category_name == "CookingEquipment" ) || ( category_name == "Smoking" ) )
        {
            return !IsOpen();
        }
        else
        {
            return IsOpen();
        }
        return true;
    }
References IsOpen().
CanDisplayAttachmentCategory() [2/2]
override bool FireplaceBase::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 442 of file fireplace.c.
    {
        if ( !super.CanDisplayAttachmentCategory( category_name ) )
            return false;
        if ( IsOven() )
        {
            if ( category_name == "CookingEquipment" )
                return false;
            if ( ( category_name == "DirectCooking" ) || ( category_name == "Smoking" ) )
                return true;
        }
        else
        {
            if ( category_name == "CookingEquipment" )
                return true;
            if ( ( category_name == "DirectCooking" ) || ( category_name == "Smoking" ) )
                return false;
        }
        return true;
    }
References IsOven().
CanDisplayAttachmentSlot()
override bool FireplaceBase::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 94 of file fireplace.c.
    {
        string slot_name = InventorySlots.GetSlotName(slot_id);
        if ( super.CanDisplayAttachmentSlot(slot_id) )
        {
            if ( slot_name != "CookingEquipment" || FindAttachmentBySlotName( "CookingTripod" ) )
                return true;
        }
        return false;
    }
References InventorySlots::GetSlotName().
CanDisplayCargo()
override bool FireplaceBase::CanDisplayCargo () inline private
Definition at line 356 of file barrelholes_colorbase.c.
    {
        //super
        if( !super.CanDisplayCargo() )
        {
            return false;
        }
        //
        return IsOpen();
    }
References IsOpen().
CanExtinguishFire()
override bool FireplaceBase::CanExtinguishFire () inline private
Definition at line 452 of file barrelholes_colorbase.c.
    {
        if ( IsOpen() && IsBurning() )
        {
            return true;
        }
        return false;
    }
References IsBurning(), and IsOpen().
Referenced by ActionExtinguishFireplaceByExtinguisher::ActionCondition(), and ActionExtinguishFireplaceByLiquid::ActionCondition().
CanIgniteEntityAsFireplace()
static bool FireplaceBase::CanIgniteEntityAsFireplace (notnull EntityAI entity) inline static private
Definition at line 734 of file fireplace.c.
    {
        //check ceiling (enough space for smoke)
        if (MiscGameplayFunctions.IsUnderRoof(entity, FireplaceBase.MIN_CEILING_HEIGHT) && IsEntityOnInteriorSurface(entity))
        {
            return false;
        }
        //check surface
        if (FireplaceBase.IsEntityOnWaterSurface(entity))
        {
            return false;
        }
        if (!MiscGameplayFunctions.IsUnderRoof(entity))
            return !FireplaceBase.IsRainingAboveEntity(entity);
        return true;
    }
References IsEntityOnInteriorSurface().
CanIgniteItem() [1/4]
override bool FireplaceBase::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 484 of file barrelholes_colorbase.c.
    {
        if ( IsBurning() && IsOpen() )
        {
            return true;
        }
        return false;
    }
References IsBurning(), and IsOpen().
CanIgniteItem() [2/4]
override bool FireplaceBase::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 585 of file fireplace.c.
    {
        return IsBurning();
    }
References IsBurning().
CanIgniteItem() [3/4]
override bool FireplaceBase::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 331 of file fireplaceindoor.c.
    {
        if ( IsBurning() )
        {
            return true;
        }
        return false;
    }
References IsBurning().
CanIgniteItem() [4/4]
override bool FireplaceBase::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 313 of file ovenindoor.c.
    {
        if ( IsBurning() )
        {
            return true;
        }
        return false;
    }
References IsBurning().
CanLoadAttachment() [1/2]
override bool FireplaceBase::CanLoadAttachment (EntityAI attachment) inline private
Definition at line 154 of file barrelholes_colorbase.c.
    {
        ItemBase item = ItemBase.Cast( attachment );
        if ( GetHealthLevel() == GameConstants.STATE_RUINED )
            return false;
        return super.CanLoadAttachment(attachment);
    }
References ItemBase::CanLoadAttachment(), GetHealthLevel(), and GameConstants::STATE_RUINED.
CanLoadAttachment() [2/2]
override bool FireplaceBase::CanLoadAttachment (EntityAI attachment) inline private
IsOven() &&
Definition at line 106 of file fireplace.c.
    {
        if ( !super.CanLoadAttachment(attachment) )
            return false;
        ItemBase item = ItemBase.Cast( attachment );
        //cookware
        if ( ( item.Type() == ATTACHMENT_CAULDRON ) || ( item.Type() == ATTACHMENT_COOKING_POT ) )
        {
            //if ( IsItemTypeAttached( ATTACHMENT_TRIPOD ) /*|| IsOven()*/ )
                return true;
        }
        if ( item.Type() == ATTACHMENT_FRYING_PAN )
        {
            //if ( IsOven() )
                return true;
        }
        // food on direct cooking slots
        //if ( IsOven() )
        //{
            if ( item.IsKindOf( "Edible_Base" ) )
                return true;
        //}
        //tripod
        if ( item.Type() == ATTACHMENT_TRIPOD )
        {
            if (  GetHierarchyParent() == NULL )
                return true;
        }
        //stones
        if ( item.Type() == ATTACHMENT_STONES )
        {
            if ( GetHierarchyParent() /*|| IsBurning()*/ )
                return false;
            return true;
        }
        return true;
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ATTACHMENT_STONES, and ATTACHMENT_TRIPOD.
CanLoadItemIntoCargo() [1/2]
override bool FireplaceBase::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 315 of file barrelholes_colorbase.c.
    {
        if (!super.CanLoadItemIntoCargo( item ))
            return false;
        if ( GetHealthLevel() == GameConstants.STATE_RUINED )
            return false;
        if ( GetHierarchyParent() )
            return false;
        return true;
    }
References GetHealthLevel(), and GameConstants::STATE_RUINED.
CanLoadItemIntoCargo() [2/2]
override bool FireplaceBase::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 415 of file fireplace.c.
    {
        if (!super.CanLoadItemIntoCargo( item ))
            return false;
        if ( GetHierarchyParent() )
            return false;
        return true;
    }
CanPlaceFireplaceInSelectedSpot() [1/2]
static bool FireplaceBase::CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world) inline static private
Definition at line 99 of file fireplaceindoor.c.
    {
        //Get fire point index position
        vector fire_point_pos = building.GetSelectionPositionMS( FIREPOINT_FIRE_POSITION + fire_point_index.ToString() );
        vector fire_point_rot = building.GetSelectionPositionMS( FIREPOINT_PLACE_ROT + fire_point_index.ToString() );
        fire_point_pos_world = building.ModelToWorld( fire_point_pos );
        fire_point_rot_world = building.ModelToWorld( fire_point_rot );
        //check if there is any FireplaceIndoor objects near selected fire point
        ref array<Object> nearest_objects = new array<Object>;
        ref array<CargoBase> proxy_cargos = new array<CargoBase>;
        GetGame().GetObjectsAtPosition3D( fire_point_pos_world, 0.25, nearest_objects, proxy_cargos );
        for ( int i = 0; i < nearest_objects.Count(); ++i )
        {
            Object object = nearest_objects.Get( i );
            if ( object.IsInherited( FireplaceIndoor ) )
            {
                return false;
            }
        }
        return true;
    }
References GetGame(), CGame::GetObjectsAtPosition3D(), and string::ToString().
CanPlaceFireplaceInSelectedSpot() [2/2]
static bool FireplaceBase::CanPlaceFireplaceInSelectedSpot (Object building, int fire_point_index, out vector fire_point_pos_world, out vector fire_point_rot_world) inline static private
Definition at line 99 of file ovenindoor.c.
    {
        //Get fire point index position
        vector fire_point_pos = building.GetSelectionPositionMS( OVENPOINT_FIRE_POSITION + fire_point_index.ToString() );
        vector fire_point_rot = building.GetSelectionPositionMS( OVENPOINT_PLACE_ROT + fire_point_index.ToString() );
        fire_point_pos_world = building.ModelToWorld( fire_point_pos );
        fire_point_rot_world = building.ModelToWorld( fire_point_rot );
        //check if there is any FireplaceIndoor objects near selected fire point
        ref array<Object> nearest_objects = new array<Object>;
        ref array<CargoBase> proxy_cargos = new array<CargoBase>;
        GetGame().GetObjectsAtPosition3D( fire_point_pos_world, 1, nearest_objects, proxy_cargos );
        for ( int i = 0; i < nearest_objects.Count(); ++i )
        {
            Object object = nearest_objects.Get( i );
            if ( object.IsInherited( OvenIndoor ) )
            {
                return false;
            }
        }
        return true;
    }
References GetGame(), CGame::GetObjectsAtPosition3D(), and string::ToString().
CanPutInCargo() [1/4]
override bool FireplaceBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 287 of file barrelholes_colorbase.c.
    {
        if ( !super.CanPutInCargo( parent ) )
            return false;
        if ( IsBurning() || !IsCargoEmpty() || DirectCookingSlotsInUse() || IsOpen() )
            return false;
        return true;
    }
References DirectCookingSlotsInUse(), IsBurning(), IsCargoEmpty(), and IsOpen().
CanPutInCargo() [2/4]
override bool FireplaceBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 386 of file fireplace.c.
    {
        if (!super.CanPutInCargo(parent))
        {
            return false;
        }
        if (HasAshes() || IsBurning() || HasStones() || HasStoneCircle() || IsOven() || !IsCargoEmpty() || HasCookingStand())
        {
            return false;
        }
        return true;
    }
References HasAshes(), HasCookingStand(), HasStoneCircle(), HasStones(), IsBurning(), IsCargoEmpty(), and IsOven().
CanPutInCargo() [3/4]
override bool FireplaceBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 288 of file fireplaceindoor.c.
    {
        return false;
    }
CanPutInCargo() [4/4]
override bool FireplaceBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 276 of file ovenindoor.c.
    {
        return false;
    }
CanPutIntoHands() [1/4]
override bool FireplaceBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 335 of file barrelholes_colorbase.c.
    {
        if (!super.CanPutIntoHands(parent))
        {
            return false;
        }
        if (IsBurning() || !IsCargoEmpty() || DirectCookingSlotsInUse() || SmokingSlotsInUse())
        {
            return false;
        }
        if ( !GetInventory().IsAttachment() && IsOpen() )
        {
            return false;
        }
        return true;
    }
References DirectCookingSlotsInUse(), IsAttachment(), IsBurning(), IsCargoEmpty(), IsOpen(), and SmokingSlotsInUse().
CanPutIntoHands() [2/4]
override bool FireplaceBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 427 of file fireplace.c.
    {
        if (!super.CanPutIntoHands(parent))
        {
            return false;
        }
        if (HasAshes() || IsBurning() || HasStones() || HasStoneCircle() || IsOven() || !IsCargoEmpty() || HasCookingStand())
        {
            return false;
        }
        return true;
    }
References HasAshes(), HasCookingStand(), HasStoneCircle(), HasStones(), IsBurning(), IsCargoEmpty(), and IsOven().
CanPutIntoHands() [3/4]
override bool FireplaceBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 305 of file fireplaceindoor.c.
    {
        return false;
    }
CanPutIntoHands() [4/4]
override bool FireplaceBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 287 of file ovenindoor.c.
    {
        return false;
    }
CanReceiveAttachment() [1/2]
override bool FireplaceBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 128 of file barrelholes_colorbase.c.
    {
        ItemBase item = ItemBase.Cast( attachment );
        if ( GetHealthLevel() == GameConstants.STATE_RUINED || GetHierarchyRootPlayer() != null )
            return false;
        //direct cooking slots
        if ( !IsOpen() )
        {
            if ( ( item.Type() == ATTACHMENT_CAULDRON ) || ( item.Type() == ATTACHMENT_COOKING_POT ) || ( item.Type() == ATTACHMENT_FRYING_PAN ) || ( item.IsKindOf( "Edible_Base" ) ) )
            {
                return super.CanReceiveAttachment(attachment, slotId);
            }
        }
        else
        {
            if ( IsKindling( item ) || IsFuel( item ) )
            {
                return super.CanReceiveAttachment(attachment, slotId);
            }
        }
        return false;
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ItemBase::CanReceiveAttachment(), GetHealthLevel(), IsFuel(), IsKindling(), IsOpen(), and GameConstants::STATE_RUINED.
CanReceiveAttachment() [2/2]
override bool FireplaceBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 46 of file fireplace.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        ItemBase item = ItemBase.Cast( attachment );
        //cookware
        if ( ( item.Type() == ATTACHMENT_CAULDRON ) || ( item.Type() == ATTACHMENT_COOKING_POT ) )
        {
            if ( FindAttachmentBySlotName( "CookingTripod" ) || IsOven() )
                return true;
            return false;
        }
        if ( item.Type() == ATTACHMENT_FRYING_PAN )
        {
            if ( IsOven() )
                return true;
            return false;
        }
        // food on direct cooking slots
        if ( item.IsKindOf( "Edible_Base" ) )
        {
            if ( IsOven() )
                return true;
            return false;
        }
        //tripod
        if ( item.IsInherited(TripodBase) )
        {
            if (!IsOven() && !GetHierarchyParent())
                return true;
            return false;
        }
        //stones
        if ( item.Type() == ATTACHMENT_STONES )
        {
            if ( !GetHierarchyParent() && !IsBurning() )
                return true;
            return false;
        }
        return true;
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ATTACHMENT_STONES, IsBurning(), and IsOven().
CanReceiveItemIntoCargo() [1/3]
override bool FireplaceBase::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 304 of file barrelholes_colorbase.c.
    {
        if ( GetHealthLevel() == GameConstants.STATE_RUINED )
            return false;
        if ( !IsOpen() || GetHierarchyParent() )
            return false;
        return super.CanReceiveItemIntoCargo( item );
    }
References GetHealthLevel(), IsOpen(), and GameConstants::STATE_RUINED.
CanReceiveItemIntoCargo() [2/3]
override bool FireplaceBase::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 407 of file fireplace.c.
    {
        if ( GetHierarchyParent() )
            return false;
        return super.CanReceiveItemIntoCargo( item );
    }
CanReceiveItemIntoCargo() [3/3]
override bool FireplaceBase::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 299 of file fireplaceindoor.c.
    {
        return super.CanReceiveItemIntoCargo( item );
    }
CanReleaseAttachment() [1/2]
override bool FireplaceBase::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 150 of file fireplace.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        ItemBase item = ItemBase.Cast(attachment);
        //stones
        if (item.Type() == ATTACHMENT_STONES)
        {
            if (IsBurning())
            {
                return false;
            }
            int stone_quantity = item.GetQuantity();
            if (HasStoneCircle() && stone_quantity <= 8)
            {
                return false;
            }
            if (IsOven())
            {
                return false;
            }
        }
        return true;
    }
References ATTACHMENT_STONES, HasStoneCircle(), IsBurning(), and IsOven().
CanReleaseAttachment() [2/2]
override bool FireplaceBase::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 160 of file ovenindoor.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        ItemBase item = ItemBase.Cast(attachment);
        if (IsKindling(item) || IsFuel(item))
        {
            return !IsBurning();
        }
        return true;
    }
References IsBurning(), IsFuel(), and IsKindling().
CanReleaseCargo()
override bool FireplaceBase::CanReleaseCargo (EntityAI cargo) inline private
Definition at line 329 of file barrelholes_colorbase.c.
    {
        return IsOpen();
    }
References IsOpen().
CanRemoveFromCargo() [1/4]
override bool FireplaceBase::CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 298 of file barrelholes_colorbase.c.
    {
        return true;
    }
CanRemoveFromCargo() [2/4]
override bool FireplaceBase::CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 401 of file fireplace.c.
    {
        return true;
    }
CanRemoveFromCargo() [3/4]
override bool FireplaceBase::CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 293 of file fireplaceindoor.c.
    {
        return true;
    }
CanRemoveFromCargo() [4/4]
override bool FireplaceBase::CanRemoveFromCargo (EntityAI parent) inline private
Definition at line 281 of file ovenindoor.c.
    {
        return true;
    }
CanRemoveFromHands() [1/2]
override bool FireplaceBase::CanRemoveFromHands (EntityAI player) inline private
Definition at line 310 of file fireplaceindoor.c.
    {
        return false;
    }
CanRemoveFromHands() [2/2]
override bool FireplaceBase::CanRemoveFromHands (EntityAI player) inline private
Definition at line 292 of file ovenindoor.c.
    {
        return false;
    }
CanShowSmoke() [1/2]
override bool FireplaceBase::CanShowSmoke () inline private
Definition at line 463 of file barrelholes_colorbase.c.
    {
        return IsOpen();
    }
References IsOpen().
Referenced by RefreshFireParticlesAndSounds().
CanShowSmoke() [2/2]
override bool FireplaceBase::CanShowSmoke () inline private
Definition at line 475 of file fireplace.c.
    {
        return !IsOven();
    }
References IsOven().
Close()
override void FireplaceBase::Close () inline private
Definition at line 412 of file barrelholes_colorbase.c.
    {
        m_Openable.Close();
        m_RoofAbove = true;
        SoundSynchRemote();
        SetTakeable(true);
        UpdateVisualState();
    }
References m_RoofAbove, SetTakeable(), and SoundSynchRemote().
CloseLoad()
void FireplaceBase::CloseLoad () inline private
Definition at line 422 of file barrelholes_colorbase.c.
    {
        m_Openable.Close();
        m_RoofAbove = true;
        SetSynchDirty();
        SetTakeable(true);
        UpdateVisualState();
    }
References m_RoofAbove, and SetTakeable().
ContactEvent()
void FireplaceBase::ContactEvent (IEntity other, vector position) inline private
Definition at line 34 of file fireplace.c.
    {
        if ( GetGame().IsServer() && !m_ContactEventProcessing && dBodyIsActive(this) && !IsSetForDeletion() )
        {
            m_ContactEventProcessing = true;
            MiscGameplayFunctions.ThrowAllItemsInInventory(this, 0);
            CheckForDestroy();
            m_ContactEventProcessing = false;
        }
    }
References dBodyIsActive(), and GetGame().
Referenced by EOnContact(), and EOnTouch().
DestroyClutterCutter() [1/2]
void FireplaceBase::DestroyClutterCutter (Object clutter_cutter) inline private
Definition at line 526 of file barrelholes_colorbase.c.
    {
        GetGame().ObjectDelete( clutter_cutter );
    }
References GetGame(), and CGame::ObjectDelete().
DestroyClutterCutter() [2/2]
void FireplaceBase::DestroyClutterCutter (Object clutter_cutter) inline private
Definition at line 481 of file fireplace.c.
    {
        GetGame().ObjectDelete( clutter_cutter );
    }
References GetGame(), and CGame::ObjectDelete().
EEItemAttached() [1/4]
override void FireplaceBase::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 164 of file barrelholes_colorbase.c.
    {
        super.EEItemAttached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            AddToFireConsumables(item_base);
        }
        // direct cooking/smoking slots
        bool edible_base_attached = false;
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = item_base;
            edible_base_attached = true;
        break;
        }
        // reset cooking time (to prevent the cooking exploit)
        if (GetGame().IsServer() && edible_base_attached)
        {
            Edible_Base edBase = Edible_Base.Cast(item_base);
            if (edBase)
            {
                if (edBase.GetFoodStage())
                {
                    edBase.SetCookingTime(0);
                }
            }
        }
        RefreshFireplaceVisuals();
    }
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemAttached() [2/4]
override void FireplaceBase::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 181 of file fireplace.c.
    {
        super.EEItemAttached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            AddToFireConsumables(item_base);
        }
        //cookware
        if (item_base.Type() == ATTACHMENT_COOKING_POT)
        {
            SetCookingEquipment(item_base);
            //rotate handle (if not in 'Oven' stage)
            if (GetGame().IsServer() && !IsOven())
            {
                item_base.SetAnimationPhase(ANIMATION_COOKWARE_HANDLE, 0);
            }
        }
        if (item.Type() == ATTACHMENT_CAULDRON)
        {
            SetCookingEquipment(item_base);
            //rotate handle (if not in 'Oven' stage)
            if (GetGame().IsServer() && !IsOven())
            {
                item_base.SetAnimationPhase(ANIMATION_CAULDRON_HANDLE, 0);
            }
        }
        // direct cooking/smoking slots
        bool edible_base_attached = false;
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = item_base;
            edible_base_attached = true;
        break;
        }
        // reset cooking time (to prevent the cooking exploit)
        if (GetGame().IsServer() && edible_base_attached)
        {
            Edible_Base edBase = Edible_Base.Cast(item_base);
            if (edBase)
            {
                if (edBase.GetFoodStage())
                {
                    edBase.SetCookingTime(0);
                }
            }
        }
        //TODO
        //add SetViewIndex when attaching various attachments
        RefreshFireplaceVisuals();
    }
References AddToFireConsumables(), ANIMATION_CAULDRON_HANDLE, ANIMATION_COOKWARE_HANDLE, ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, GetGame(), IsFuel(), IsKindling(), IsOven(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and SetCookingEquipment().
EEItemAttached() [3/4]
override void FireplaceBase::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 160 of file fireplaceindoor.c.
    {
        super.EEItemAttached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if ( IsKindling(item_base) || IsFuel(item_base))
        {
            AddToFireConsumables(item_base);
        }
        // direct cooking slots, smoking slots
        bool edible_base_attached = false;
        switch ( slot_name )
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = item_base;
            edible_base_attached = true;
        break;
        }
        // reset cooking time (to prevent the cooking exploit)
        if (GetGame().IsServer() && edible_base_attached)
        {
            Edible_Base edBase = Edible_Base.Cast(item_base);
            if (edBase)
            {
                if (edBase.GetFoodStage())
                {
                    edBase.SetCookingTime(0);
                }
            }
        }
        RefreshFireplaceVisuals();
    }
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemAttached() [4/4]
override void FireplaceBase::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 176 of file ovenindoor.c.
    {
        super.EEItemAttached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            AddToFireConsumables(item_base);
        }
        // direct cooking/smoking slots
        bool edible_base_attached = false;
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = item_base;
            edible_base_attached = true;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = item_base;
            edible_base_attached = true;
        break;
        }
        // reset cooking time (to prevent the cooking exploit)
        if (GetGame().IsServer() && edible_base_attached)
        {
            Edible_Base edBase = Edible_Base.Cast(item_base);
            if (edBase)
            {
                if ( edBase.GetFoodStage())
                {
                    edBase.SetCookingTime(0);
                }
            }
        }
        RefreshFireplaceVisuals();
    }
References AddToFireConsumables(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, and RefreshFireplaceVisuals().
EEItemDetached() [1/4]
override void FireplaceBase::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 231 of file barrelholes_colorbase.c.
    {
        super.EEItemDetached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            RemoveFromFireConsumables(GetFireConsumableByItem(item_base));
        }
        // direct cooking / smoking slots
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = null;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = null;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = null;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = null;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = null;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = null;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = null;
        break;
        }
        // cookware-specifics (remove audio visuals)
        if (item_base.Type() == ATTACHMENT_CAULDRON || item_base.Type() == ATTACHMENT_COOKING_POT)
        {
            ClearCookingEquipment(item_base);
            Bottle_Base cooking_pot = Bottle_Base.Cast(item);
            cooking_pot.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_FRYING_PAN)
        {
            ClearCookingEquipment(item_base);
            FryingPan frying_pan = FryingPan.Cast(item);
            frying_pan.RemoveAudioVisualsOnClient();
        }
        RefreshFireplaceVisuals();
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [2/4]
override void FireplaceBase::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 268 of file fireplace.c.
    {
        super.EEItemDetached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            RemoveFromFireConsumables(GetFireConsumableByItem(item_base));
        }
        //cookware
        if (item_base.Type() == ATTACHMENT_COOKING_POT)
        {
            ClearCookingEquipment(item_base);
            //rotate handle
            if (GetGame().IsServer())
            {
                item_base.SetAnimationPhase(ANIMATION_COOKWARE_HANDLE, 1);
            }
            //remove audio visuals
            Bottle_Base cooking_pot = Bottle_Base.Cast(item);
            cooking_pot.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_CAULDRON)
        {
            ClearCookingEquipment(item_base);
            //rotate handle
            if (GetGame().IsServer())
            {
                item_base.SetAnimationPhase(ANIMATION_CAULDRON_HANDLE, 1);
            }
            //remove audio visuals
            Bottle_Base cauldron = Bottle_Base.Cast( item );
            cauldron.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_FRYING_PAN)
        {
            ClearCookingEquipment(item_base);
            //remove audio visuals
            FryingPan frying_pan = FryingPan.Cast(item);
            frying_pan.RemoveAudioVisualsOnClient();
        }
        // direct cooking/smoking slots
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = null;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = null;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = null;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = null;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = null;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = null;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = null;
        break;
        }
        //no attachments left, no cargo items & no ashes are present
        CheckForDestroy();
        //TODO
        //add SetViewIndex when detaching various attachments
        RefreshFireplaceVisuals();
    }
References ANIMATION_CAULDRON_HANDLE, ANIMATION_COOKWARE_HANDLE, ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), GetGame(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [3/4]
override void FireplaceBase::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 221 of file fireplaceindoor.c.
    {
        super.EEItemDetached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            RemoveFromFireConsumables(GetFireConsumableByItem(item_base));
        }
        CheckForDestroy();
        // direct cooking/smoking slots
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = null;
        break;
        case "DirectCookingB":
            m_DirectCookingSlots[1] = null;
        break;
        case "DirectCookingC":
            m_DirectCookingSlots[2] = null;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = null;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = null;
        break;
        case "SmokingC":
            m_SmokingSlots[2] = null;
        break;
        case "SmokingD":
            m_SmokingSlots[3] = null;
        break;
        }
        // cookware-specifics (remove audio visuals)
        if (item_base.Type() == ATTACHMENT_COOKING_POT)
        {
            ClearCookingEquipment(item_base);
            Bottle_Base cooking_pot = Bottle_Base.Cast(item);
            cooking_pot.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_CAULDRON)
        {
            ClearCookingEquipment(item_base);
            Bottle_Base cauldron = Bottle_Base.Cast(item);
            cauldron.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_FRYING_PAN)
        {
            ClearCookingEquipment(item_base);
            FryingPan frying_pan = FryingPan.Cast(item);
            frying_pan.RemoveAudioVisualsOnClient();
        }
        RefreshFireplaceVisuals();
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EEItemDetached() [4/4]
override void FireplaceBase::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 221 of file ovenindoor.c.
    {
        super.EEItemDetached(item, slot_name);
        ItemBase item_base = ItemBase.Cast(item);
        if (IsKindling(item_base) || IsFuel(item_base))
        {
            RemoveFromFireConsumables(GetFireConsumableByItem(item_base));
        }
        CheckForDestroy();
        // direct cooking/smoking slots
        switch (slot_name)
        {
        case "DirectCookingA":
            m_DirectCookingSlots[0] = null;
        break;
        case "SmokingA":
            m_SmokingSlots[0] = null;
        break;
        case "SmokingB":
            m_SmokingSlots[1] = null;
        break;
        }
        // cookware-specifics (remove audio visuals)
        if (item_base.Type() == ATTACHMENT_COOKING_POT)
        {
            ClearCookingEquipment(item_base);
            Bottle_Base cooking_pot = Bottle_Base.Cast(item);
            cooking_pot.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_CAULDRON)
        {
            ClearCookingEquipment(item_base);
            Bottle_Base cauldron = Bottle_Base.Cast(item);
            cauldron.RemoveAudioVisualsOnClient();
        }
        if (item_base.Type() == ATTACHMENT_FRYING_PAN)
        {
            ClearCookingEquipment(item_base);
            FryingPan frying_pan = FryingPan.Cast(item);
            frying_pan.RemoveAudioVisualsOnClient();
        }
        RefreshFireplaceVisuals();
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, ClearCookingEquipment(), GetFireConsumableByItem(), IsFuel(), IsKindling(), m_DirectCookingSlots, m_SmokingSlots, RefreshFireplaceVisuals(), and RemoveFromFireConsumables().
EOnContact()
override void FireplaceBase::EOnContact (IEntity other, Contact extra) inline private
Definition at line 29 of file fireplace.c.
    {
        ContactEvent( other, extra.Position );
    }
References ContactEvent(), and Contact::Position.
EOnTouch()
override void FireplaceBase::EOnTouch (IEntity other, int extra) inline private
Definition at line 24 of file fireplace.c.
    {
        ContactEvent( other, GetPosition() );
    }
References ContactEvent(), and GetPosition.
Fireplace()
void FireplaceBase::Fireplace () inline private
Definition at line 5 of file fireplace.c.
    {
        //Particles - default for FireplaceBase
        PARTICLE_FIRE_START     = ParticleList.CAMP_FIRE_START;
        PARTICLE_SMALL_FIRE     = ParticleList.CAMP_SMALL_FIRE;
        PARTICLE_NORMAL_FIRE    = ParticleList.CAMP_NORMAL_FIRE;
        PARTICLE_SMALL_SMOKE    = ParticleList.CAMP_SMALL_SMOKE;
        PARTICLE_NORMAL_SMOKE   = ParticleList.CAMP_NORMAL_SMOKE;
        PARTICLE_FIRE_END       = ParticleList.CAMP_FIRE_END;
        PARTICLE_STEAM_END      = ParticleList.CAMP_STEAM_2END;
        SetEventMask( EntityEvent.CONTACT | EntityEvent.TOUCH );
    }
References ParticleList::CAMP_FIRE_END, ParticleList::CAMP_FIRE_START, ParticleList::CAMP_NORMAL_FIRE, ParticleList::CAMP_NORMAL_SMOKE, ParticleList::CAMP_SMALL_FIRE, ParticleList::CAMP_SMALL_SMOKE, ParticleList::CAMP_STEAM_2END, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
FireplaceIndoor()
void FireplaceBase::FireplaceIndoor () inline private
Definition at line 13 of file fireplaceindoor.c.
    {
        //Particles - default for FireplaceBase
        PARTICLE_FIRE_START     = ParticleList.HOUSE_FIRE_START;
        PARTICLE_SMALL_FIRE     = ParticleList.HOUSE_SMALL_FIRE;
        PARTICLE_NORMAL_FIRE    = ParticleList.HOUSE_NORMAL_FIRE;
        PARTICLE_SMALL_SMOKE    = ParticleList.HOUSE_SMALL_SMOKE;
        PARTICLE_NORMAL_SMOKE   = ParticleList.HOUSE_NORMAL_SMOKE;
        PARTICLE_FIRE_END       = ParticleList.HOUSE_FIRE_END;
        PARTICLE_STEAM_END      = ParticleList.HOUSE_FIRE_STEAM_2END;
        //register sync variables
        RegisterNetSyncVariableFloat( "m_SmokePosX", 0, 0, 2 );
        RegisterNetSyncVariableFloat( "m_SmokePosY", 0, 0, 2 );
        RegisterNetSyncVariableFloat( "m_SmokePosZ", 0, 0, 2 );
        RegisterNetSyncVariableInt( "m_FirePointIndex", 0, 9 );
        m_LightDistance = 50;
        m_RoofAbove = true;
    }
References ParticleList::HOUSE_FIRE_END, ParticleList::HOUSE_FIRE_START, ParticleList::HOUSE_FIRE_STEAM_2END, ParticleList::HOUSE_NORMAL_FIRE, ParticleList::HOUSE_NORMAL_SMOKE, ParticleList::HOUSE_SMALL_FIRE, ParticleList::HOUSE_SMALL_SMOKE, m_LightDistance, m_RoofAbove, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
GetDamageSystemVersionChange()
override int FireplaceBase::GetDamageSystemVersionChange () inline private
Definition at line 32 of file barrelholes_colorbase.c.
    {
        return 110;
    }
GetFirePointIndex() [1/2]
static int FireplaceBase::GetFirePointIndex (string action_selection) inline static private
Definition at line 88 of file fireplaceindoor.c.
    {
        int index_location = action_selection.Length() - 1;
        return action_selection.Substring( index_location, 1 ).ToInt();
    }
References string::Length(), string::Substring(), and string::ToInt().
GetFirePointIndex() [2/2]
static int FireplaceBase::GetFirePointIndex (string action_selection) inline static private
Definition at line 88 of file ovenindoor.c.
    {
        int index_location = action_selection.Length() - 1;
        return action_selection.Substring( index_location, 1 ).ToInt();
    }
References string::Length(), string::Substring(), and string::ToInt().
GetInvulnerabilityTypeString()
override string FireplaceBase::GetInvulnerabilityTypeString () inline private
Definition at line 37 of file barrelholes_colorbase.c.
    {
        return "disableContainerDamage";
    }
GetPlaceSoundset() [1/2]
override string FireplaceBase::GetPlaceSoundset () inline private
Definition at line 552 of file barrelholes_colorbase.c.
    {
        return "placeBarrel_SoundSet";
    }
GetPlaceSoundset() [2/2]
override string FireplaceBase::GetPlaceSoundset () inline private
Definition at line 758 of file fireplace.c.
    {
        return "placeFireplace_SoundSet";
    }
GetSmokeEffectPosition() [1/2]
override protected vector FireplaceBase::GetSmokeEffectPosition () inline private
Definition at line 135 of file fireplaceindoor.c.
    {
        return Vector( m_SmokePosX, m_SmokePosY, m_SmokePosZ );
    }
References Vector().
Referenced by ParticleNormalSmokeStart(), ParticleNormalSmokeStart(), ParticleSmallSmokeStart(), and ParticleSmallSmokeStart().
GetSmokeEffectPosition() [2/2]
override protected vector FireplaceBase::GetSmokeEffectPosition () inline private
Definition at line 135 of file ovenindoor.c.
    {
        return Vector( m_SmokePosX, m_SmokePosY, m_SmokePosZ );
    }
References Vector().
HasFlammableMaterial() [1/4]
override bool FireplaceBase::HasFlammableMaterial () inline private
Definition at line 469 of file barrelholes_colorbase.c.
    {
        return true;
    }
HasFlammableMaterial() [2/4]
override bool FireplaceBase::HasFlammableMaterial () inline private
Definition at line 575 of file fireplace.c.
    {
        return true;
    }
HasFlammableMaterial() [3/4]
override bool FireplaceBase::HasFlammableMaterial () inline private
Definition at line 316 of file fireplaceindoor.c.
    {
        return true;
    }
HasFlammableMaterial() [4/4]
override bool FireplaceBase::HasFlammableMaterial () inline private
Definition at line 298 of file ovenindoor.c.
    {
        return true;
    }
HeightStartCheckOverride()
override float FireplaceBase::HeightStartCheckOverride () inline private
Definition at line 469 of file fireplace.c.
    {
        return 0.32;
    }
IgniteEntityAsFireplace()
static Fireplace FireplaceBase::IgniteEntityAsFireplace (notnull EntityAI entity, notnull EntityAI fire_source) inline static private
Definition at line 702 of file fireplace.c.
    {
        //get player
        PlayerBase player = PlayerBase.Cast( fire_source.GetHierarchyRootPlayer() );
        //create fireplace
        Fireplace fireplace = Fireplace.Cast( GetGame().CreateObjectEx( "Fireplace" , entity.GetPosition(), ECE_PLACE_ON_SURFACE ) );
        //attach
        if ( !GetGame().IsMultiplayer() )       //clear inventory reservation (single player)
        {
            InventoryLocation loc = new InventoryLocation;
            entity.GetInventory().GetCurrentInventoryLocation( loc );
            player.GetInventory().ClearInventoryReservationEx( entity, loc );
        }
        if ( GetGame().IsServer() && GetGame().IsMultiplayer() )
        {
            player.ServerTakeEntityToTargetAttachment( fireplace, entity ); // multiplayer server side
        }
        else
        {
            player.LocalTakeEntityToTargetAttachment( fireplace, entity ); // single player or multiplayer client side
        }
        //start fire
        fireplace.StartFire();
        fireplace.OnIgnitedThis(fire_source);
        return fireplace;
    }
References ECE_PLACE_ON_SURFACE, and GetGame().
IsBarrelWithHoles()
override bool FireplaceBase::IsBarrelWithHoles () inline private
Definition at line 94 of file barrelholes_colorbase.c.
    {
        return true;
    }
Referenced by GetSteamPosition(), RefreshFireplaceVisuals(), and StartHeating().
IsBaseFireplace()
override bool FireplaceBase::IsBaseFireplace () inline private
Definition at line 19 of file fireplace.c.
    {
        return true;
    }
Referenced by ActionCondition(), ActionCookOnStick::ActionCondition(), ActionIgniteFireplaceByAir::ActionCondition(), GetSteamPosition(), OnVariablesSynchronized(), and StartHeating().
IsFireplaceIndoor()
override bool FireplaceBase::IsFireplaceIndoor () inline private
Definition at line 155 of file fireplaceindoor.c.
    {
        return true;
    }
Referenced by ActionCookOnStick::ActionCondition(), ActionIgniteFireplaceByAir::ActionCondition(), GetSteamPosition(), RefreshFireplaceVisuals(), StartFire(), StartHeating(), and StopFire().
IsIgnited() [1/4]
override bool FireplaceBase::IsIgnited () inline private
Definition at line 494 of file barrelholes_colorbase.c.
    {
        return IsBurning();
    }
References IsBurning().
IsIgnited() [2/4]
override bool FireplaceBase::IsIgnited () inline private
Definition at line 590 of file fireplace.c.
    {
        return IsBurning();
    }
References IsBurning().
IsIgnited() [3/4]
override bool FireplaceBase::IsIgnited () inline private
Definition at line 341 of file fireplaceindoor.c.
    {
        return IsBurning();
    }
References IsBurning().
IsIgnited() [4/4]
override bool FireplaceBase::IsIgnited () inline private
Definition at line 323 of file ovenindoor.c.
    {
        return IsBurning();
    }
References IsBurning().
IsIndoorOven()
override bool FireplaceBase::IsIndoorOven () inline private
Definition at line 155 of file ovenindoor.c.
    {
        return true;
    }
Referenced by GetSteamPosition(), and RefreshFireplaceVisuals().
IsOpen()
override bool FireplaceBase::IsOpen () inline private
Definition at line 432 of file barrelholes_colorbase.c.
    {
        return m_Openable.IsOpened();
    }
IsPrepareToDelete() [1/2]
override bool FireplaceBase::IsPrepareToDelete () inline private
Definition at line 226 of file barrelholes_colorbase.c.
    {
        return false;
    }
IsPrepareToDelete() [2/2]
override bool FireplaceBase::IsPrepareToDelete () inline private
Definition at line 379 of file fireplace.c.
    {
        return GetInventory().AttachmentCount() == 0 && !IsBurning() && !HasAshes();
    }
References HasAshes(), and IsBurning().
IsThisIgnitionSuccessful() [1/4]
override bool FireplaceBase::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 531 of file barrelholes_colorbase.c.
    {
        //check kindling
        if ( !HasAnyKindling() && IsOpen() )
        {
            return false;
        }
        //check surface
        if ( IsOnWaterSurface() )
        {
            return false;
        }
        return true;
    }
References HasAnyKindling(), IsOnWaterSurface(), and IsOpen().
IsThisIgnitionSuccessful() [2/4]
override bool FireplaceBase::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 636 of file fireplace.c.
    {
        SetIgniteFailure( false );
        Param1<bool> failure;
        //check kindling
        if ( !HasAnyKindling() )
        {
            return false;
        }
        //check roof
        if ( !IsOven() )
        {
            if ( !IsCeilingHighEnoughForSmoke() && IsOnInteriorSurface() )
            {
                return false;
            }
        }
        //check surface
        if ( IsOnWaterSurface() )
        {
            return false;
        }
        //check wetness
        if ( IsWet() )
        {
            SetIgniteFailure( true );
            failure = new Param1<bool>( GetIgniteFailure() );
            GetGame().RPCSingleParam( this, FirePlaceFailure.WET, failure, true );
            return false;
        }
        // check if the fireplace isnt below a roof
        //  excluding this check whein oven stage
        if ( !IsOven() && !MiscGameplayFunctions.IsUnderRoof( this ) )
        {
            // if not, check if there is strong rain or wind
            if ( IsRainingAbove() )
            {
                SetIgniteFailure( true );
                failure = new Param1<bool>( GetIgniteFailure() );
                GetGame().RPCSingleParam( this, FirePlaceFailure.WET, failure, true );
                return false;
            }
            if ( IsWindy() )
            {
                SetIgniteFailure( true );
                failure = new Param1<bool>( GetIgniteFailure() );
                GetGame().RPCSingleParam( this, FirePlaceFailure.WIND, failure, true );
                return false;
            }
        }
        return true;
    }
References GetGame(), GetIgniteFailure(), HasAnyKindling(), IsCeilingHighEnoughForSmoke(), IsOnInteriorSurface(), IsOnWaterSurface(), IsOven(), IsRainingAbove(), IsWet(), IsWindy(), CGame::RPCSingleParam(), and SetIgniteFailure().
IsThisIgnitionSuccessful() [3/4]
override bool FireplaceBase::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 356 of file fireplaceindoor.c.
    {
        SetIgniteFailure( false );
        Param1<bool> failure;
        //check kindling
        if ( !HasAnyKindling() )
        {
            return false;
        }
        //check wetness
        if ( IsWet() )
        {
            SetIgniteFailure( true );
            failure = new Param1<bool>( GetIgniteFailure() );
            GetGame().RPCSingleParam( this, FirePlaceFailure.WET, failure, true );
            return false;
        }
        return true;
    }
References GetGame(), GetIgniteFailure(), HasAnyKindling(), IsWet(), CGame::RPCSingleParam(), and SetIgniteFailure().
IsThisIgnitionSuccessful() [4/4]
override bool FireplaceBase::IsThisIgnitionSuccessful (EntityAI item_source = NULL) inline private
Definition at line 338 of file ovenindoor.c.
    {
        //check kindling
        if ( !HasAnyKindling() )
        {
            return false;
        }
        //check wetness
        if ( IsWet() )
        {
            return false;
        }
        return true;
    }
References HasAnyKindling(), and IsWet().
OnBeforeTryDelete()
override void FireplaceBase::OnBeforeTryDelete () inline private
Definition at line 373 of file fireplace.c.
    {
        super.OnBeforeTryDelete();
        MiscGameplayFunctions.DropAllItemsInInventoryInBounds(this, m_HalfExtents);
    }
References m_HalfExtents.
OnDebugSpawn()
override void FireplaceBase::OnDebugSpawn () inline private
Definition at line 568 of file barrelholes_colorbase.c.
    {
        m_Openable.Open();
        super.OnDebugSpawn();
        m_Openable.Close();
    }
OnIgnitedTarget() [1/4]
override void FireplaceBase::OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 499 of file barrelholes_colorbase.c.
    {
    }
OnIgnitedTarget() [2/4]
override void FireplaceBase::OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 595 of file fireplace.c.
    {
    }
OnIgnitedTarget() [3/4]
override void FireplaceBase::OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 346 of file fireplaceindoor.c.
    {
    }
OnIgnitedTarget() [4/4]
override void FireplaceBase::OnIgnitedTarget (EntityAI ignited_item) inline private
Definition at line 328 of file ovenindoor.c.
    {
    }
OnIgnitedThis() [1/4]
override void FireplaceBase::OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 503 of file barrelholes_colorbase.c.
    {
        //remove grass
        Object cc_object = GetGame().CreateObjectEx( OBJECT_CLUTTER_CUTTER , GetPosition(), ECE_PLACE_ON_SURFACE );
        cc_object.SetOrientation ( GetOrientation() );
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( DestroyClutterCutter, 0.2, false, cc_object );
        //start fire
        StartFire();
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), GetOrientation(), GetPosition, OBJECT_CLUTTER_CUTTER, and StartFire().
Referenced by OnDebugButtonPressServer().
OnIgnitedThis() [2/4]
override void FireplaceBase::OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 599 of file fireplace.c.
    {
        //remove grass
        Object cc_object = GetGame().CreateObjectEx( OBJECT_CLUTTER_CUTTER , GetPosition(), ECE_PLACE_ON_SURFACE );
        cc_object.SetOrientation ( GetOrientation() );
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( DestroyClutterCutter, 200, false, cc_object );
        //start fire
        StartFire();
        if ( fire_source )
        {
            Man player = fire_source.GetHierarchyRootPlayer();
            if ( player )
            {
                EFireIgniteType ignate_type = EFireIgniteType.Unknow;
                if ( fire_source.ClassName() == "Matchbox"  )
                {
                    ignate_type = EFireIgniteType.Matchbox;
                }
                else if ( fire_source.ClassName() == "Roadflare"  )
                {
                    ignate_type = EFireIgniteType.Roadflare;
                }
                else if ( fire_source.ClassName() == "HandDrillKit"  )
                {
                    ignate_type = EFireIgniteType.HandDrill;
                }
                SyncEvents.SendPlayerIgnatedFireplace( player, ignate_type );
            }
        }
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), GetOrientation(), GetPosition, OBJECT_CLUTTER_CUTTER, SyncEvents::SendPlayerIgnatedFireplace(), and StartFire().
OnIgnitedThis() [3/4]
override void FireplaceBase::OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 350 of file fireplaceindoor.c.
    {
        //start fire
        StartFire();
    }
References StartFire().
OnIgnitedThis() [4/4]
override void FireplaceBase::OnIgnitedThis (EntityAI fire_source) inline private
Definition at line 332 of file ovenindoor.c.
    {
        //start fire
        StartFire();
    }
References StartFire().
OnStoreLoad() [1/4]
override bool FireplaceBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 71 of file barrelholes_colorbase.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        bool opened;
        if ( version >= 110 && !ctx.Read( opened ) )
        {
            return false;
        }
        if ( opened )
        {
            OpenLoad();
        }
        else
        {
            CloseLoad();
        }
        return true;
    }
References Serializer::Read().
OnStoreLoad() [2/4]
override bool FireplaceBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 533 of file fireplace.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        if ( version >= 110 )
        {
            // read stone circle state
            if ( !ctx.Read( m_HasStoneCircle ) )
            {
                m_HasStoneCircle = false;
                return false;
            }
            // read stone oven state
            if ( !ctx.Read( m_IsOven ) )
            {
                m_IsOven = false;
                return false;
            }
        }
        return true;
    }
References m_HasStoneCircle, m_IsOven, and Serializer::Read().
OnStoreLoad() [3/4]
override bool FireplaceBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 50 of file fireplaceindoor.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Fireplace Indoor data ---
        //fire point name
        if ( !ctx.Read( m_FirePointIndex ) )
        {
            m_FirePointIndex = 1;       //set default
            return false;
        }
        //smoke position
        if ( !ctx.Read( m_SmokePosX ) )
        {
            m_SmokePosX = 0;        //set default
            return false;
        }
        if ( !ctx.Read( m_SmokePosY ) )
        {
            m_SmokePosY = 0;        //set default
            return false;
        }
        if ( !ctx.Read( m_SmokePosZ ) )
        {
            m_SmokePosZ = 0;        //set default
            return false;
        }
        //---
        return true;
    }
References m_FirePointIndex, and Serializer::Read().
OnStoreLoad() [4/4]
override bool FireplaceBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 50 of file ovenindoor.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Fireplace Indoor data ---
        //fire point name
        if ( !ctx.Read( m_FirePointIndex ) )
        {
            m_FirePointIndex = 1;       //set default
            return false;
        }
        //smoke position
        if ( !ctx.Read( m_SmokePosX ) )
        {
            m_SmokePosX = 0;        //set default
            return false;
        }
        if ( !ctx.Read( m_SmokePosY ) )
        {
            m_SmokePosY = 0;        //set default
            return false;
        }
        if ( !ctx.Read( m_SmokePosZ ) )
        {
            m_SmokePosZ = 0;        //set default
            return false;
        }
        //---
        return true;
    }
References m_FirePointIndex, and Serializer::Read().
OnStoreSave() [1/4]
override void FireplaceBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 64 of file barrelholes_colorbase.c.
    {
        super.OnStoreSave( ctx );
        ctx.Write( m_Openable.IsOpened() );
    }
References Serializer::Write().
OnStoreSave() [2/4]
override void FireplaceBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 519 of file fireplace.c.
    {
        super.OnStoreSave(ctx);
        if ( GetGame().SaveVersion() >= 110 )
        {
            // save stone circle state
            ctx.Write( m_HasStoneCircle );
            // save stone oven state
            ctx.Write( m_IsOven );
        }
    }
References GetGame(), m_HasStoneCircle, m_IsOven, and Serializer::Write().
OnStoreSave() [3/4]
override void FireplaceBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 37 of file fireplaceindoor.c.
    {
        super.OnStoreSave( ctx );
        //fire point name
        ctx.Write( m_FirePointIndex );
        //smoke position
        ctx.Write( m_SmokePosX );
        ctx.Write( m_SmokePosY );
        ctx.Write( m_SmokePosZ );
    }
References m_FirePointIndex, and Serializer::Write().
OnStoreSave() [4/4]
override void FireplaceBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 37 of file ovenindoor.c.
    {
        super.OnStoreSave( ctx );
        //fire point name
        ctx.Write( m_FirePointIndex );
        //smoke position
        ctx.Write( m_SmokePosX );
        ctx.Write( m_SmokePosY );
        ctx.Write( m_SmokePosZ );
    }
References m_FirePointIndex, and Serializer::Write().
OnVariablesSynchronized()
override void FireplaceBase::OnVariablesSynchronized () inline private
Definition at line 99 of file barrelholes_colorbase.c.
    {
        super.OnVariablesSynchronized();
        if ( !IsBeingPlaced() )
        {
            //Refresh particles and sounds
            RefreshFireParticlesAndSounds( false );
            //sound sync
            if ( IsSoundSynchRemote() && !IsBeingPlaced() && m_Initialized )
            {
                if ( IsOpen() )
                {
                    SoundBarrelOpenPlay();
                }
                if ( !IsOpen() )
                {
                    SoundBarrelClosePlay();
                }
            }
        }
        UpdateVisualState();
    }
References IsBeingPlaced(), IsOpen(), IsSoundSynchRemote(), m_Initialized, and RefreshFireParticlesAndSounds().
OnWasAttached()
override void FireplaceBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 42 of file barrelholes_colorbase.c.
    {
        super.OnWasAttached(parent, slot_id);
        Open();
    }
References Open().
OnWasDetached()
override void FireplaceBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 49 of file barrelholes_colorbase.c.
    {
        super.OnWasDetached(parent, slot_id);
        Close();
    }
References Close().
Open()
override void FireplaceBase::Open () inline private
Definition at line 391 of file barrelholes_colorbase.c.
    {
        m_Openable.Open();
        m_RoofAbove = false;
        SoundSynchRemote();
        SetTakeable(false);
        UpdateVisualState();
    }
References m_RoofAbove, SetTakeable(), and SoundSynchRemote().
OpenLoad()
void FireplaceBase::OpenLoad () inline private
Definition at line 402 of file barrelholes_colorbase.c.
    {
        m_Openable.Open();
        m_RoofAbove = false;
        SetSynchDirty();
        SetTakeable(false);
        UpdateVisualState();
    }
References m_RoofAbove, and SetTakeable().
OvenIndoor()
void FireplaceBase::OvenIndoor () inline private
Definition at line 13 of file ovenindoor.c.
    {
        //Particles - default for FireplaceBase
        PARTICLE_FIRE_START     = ParticleList.OVEN_FIRE_START;
        PARTICLE_SMALL_FIRE     = ParticleList.OVEN_SMALL_FIRE;
        PARTICLE_NORMAL_FIRE    = ParticleList.OVEN_NORMAL_FIRE;
        PARTICLE_SMALL_SMOKE    = ParticleList.HOUSE_SMALL_SMOKE;
        PARTICLE_NORMAL_SMOKE   = ParticleList.HOUSE_NORMAL_SMOKE;
        PARTICLE_FIRE_END       = ParticleList.OVEN_FIRE_END;
        PARTICLE_STEAM_END      = ParticleList.BARREL_FIRE_STEAM_2END;
        //register sync variables
        RegisterNetSyncVariableFloat( "m_SmokePosX", 0, 0, 2 );
        RegisterNetSyncVariableFloat( "m_SmokePosY", 0, 0, 2 );
        RegisterNetSyncVariableFloat( "m_SmokePosZ", 0, 0, 2 );
        RegisterNetSyncVariableInt( "m_FirePointIndex", 0, 9 );
        m_LightDistance = 50;
        m_RoofAbove = true;
    }
References ParticleList::BARREL_FIRE_STEAM_2END, ParticleList::HOUSE_NORMAL_SMOKE, ParticleList::HOUSE_SMALL_SMOKE, m_LightDistance, m_RoofAbove, ParticleList::OVEN_FIRE_END, ParticleList::OVEN_FIRE_START, ParticleList::OVEN_NORMAL_FIRE, ParticleList::OVEN_SMALL_FIRE, PARTICLE_FIRE_END, PARTICLE_FIRE_START, PARTICLE_NORMAL_FIRE, PARTICLE_NORMAL_SMOKE, PARTICLE_SMALL_FIRE, PARTICLE_SMALL_SMOKE, and PARTICLE_STEAM_END.
ParticleNormalSmokeStart() [1/2]
override void FireplaceBase::ParticleNormalSmokeStart () inline private
Definition at line 147 of file fireplaceindoor.c.
    {
        PlayParticle( m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, GetSmokeEffectPosition(), true );
    }
References GetSmokeEffectPosition(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalSmokeStart() [2/2]
override void FireplaceBase::ParticleNormalSmokeStart () inline private
Definition at line 147 of file ovenindoor.c.
    {
        PlayParticle( m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, GetSmokeEffectPosition(), true );
    }
References GetSmokeEffectPosition(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, and PlayParticle().
ParticleSmallSmokeStart() [1/2]
override void FireplaceBase::ParticleSmallSmokeStart () inline private
Definition at line 141 of file fireplaceindoor.c.
    {
        PlayParticle( m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, GetSmokeEffectPosition(), true );
    }
References GetSmokeEffectPosition(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallSmokeStart() [2/2]
override void FireplaceBase::ParticleSmallSmokeStart () inline private
Definition at line 141 of file ovenindoor.c.
    {
        PlayParticle( m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, GetSmokeEffectPosition(), true );
    }
References GetSmokeEffectPosition(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, and PlayParticle().
RefreshFireplacePhysics()
override void FireplaceBase::RefreshFireplacePhysics () inline private
Definition at line 513 of file fireplace.c.
    {
        RefreshPhysics();
    }
References RefreshPhysics().
Referenced by OnItemLocationChanged(), and RefreshFireplaceVisuals().
RefreshPhysics()
override void FireplaceBase::RefreshPhysics () inline private
Definition at line 486 of file fireplace.c.
    {
        super.RefreshPhysics();
        //Oven
        if ( IsOven() )
        {
            RemoveProxyPhysics( ANIMATION_OVEN );
            AddProxyPhysics( ANIMATION_OVEN );
        }
        else
        {
            RemoveProxyPhysics( ANIMATION_OVEN );
        }
        //Tripod
        if ( IsItemTypeAttached( ATTACHMENT_TRIPOD ) )
        {
            RemoveProxyPhysics( ANIMATION_TRIPOD );
            AddProxyPhysics( ANIMATION_TRIPOD );
        }
        else
        {
            RemoveProxyPhysics( ANIMATION_TRIPOD );
        }
    }
References AddProxyPhysics(), ANIMATION_OVEN, ANIMATION_TRIPOD, ATTACHMENT_TRIPOD, IsItemTypeAttached(), IsOven(), and RemoveProxyPhysics().
Referenced by RefreshFireplacePhysics().
SetActions() [1/2]
override void FireplaceBase::SetActions () inline private
Definition at line 557 of file barrelholes_colorbase.c.
    {
        AddAction(ActionAttachOnSelection);
        super.SetActions();
        AddAction(ActionOpenBarrelHoles);
        AddAction(ActionCloseBarrelHoles);
        AddAction(ActionPlaceObject);
        AddAction(ActionTogglePlaceObject);
    }
References AddAction().
SetActions() [2/2]
override void FireplaceBase::SetActions () inline private
Definition at line 763 of file fireplace.c.
    {
        super.SetActions();
        AddAction(ActionPlaceFireplaceIntoBarrel);
        AddAction(ActionPlaceFireplaceIndoor);
        AddAction(ActionPlaceOvenIndoor);
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionPlaceObject);
        AddAction(ActionBuildOven);
        AddAction(ActionDismantleOven);
        AddAction(ActionBuildStoneCircle);
        AddAction(ActionDismantleStoneCircle);
    }
References ActionBuildOven(), ActionBuildStoneCircle(), ActionDismantleOven(), ActionDismantleStoneCircle(), and AddAction().
SetCookingEquipment()
override void FireplaceBase::SetCookingEquipment (ItemBase equipment) inline private
Definition at line 354 of file fireplace.c.
    {
        super.SetCookingEquipment(equipment);
        TripodBase stand = TripodBase.Cast(FindAttachmentBySlotName("CookingTripod"));
        if (stand)
        {
            if (equipment)
            {
                stand.LockToParent();
            }
            else
            {
                stand.UnlockFromParent();
            }
        }
    }
Referenced by ClearCookingEquipment(), EEItemAttached(), and EEItemAttached().
SetFirePointIndex() [1/2]
void FireplaceBase::SetFirePointIndex (int fire_point_index) inline private
Definition at line 94 of file fireplaceindoor.c.
    {
        m_FirePointIndex = fire_point_index;
    }
References m_FirePointIndex.
SetFirePointIndex() [2/2]
void FireplaceBase::SetFirePointIndex (int fire_point_index) inline private
Definition at line 94 of file ovenindoor.c.
    {
        m_FirePointIndex = fire_point_index;
    }
References m_FirePointIndex.
SetSmokePointPosition() [1/2]
void FireplaceBase::SetSmokePointPosition (vector smoke_point_pos) inline private
Definition at line 125 of file fireplaceindoor.c.
    {
        m_SmokePosX = smoke_point_pos[0];
        m_SmokePosY = smoke_point_pos[1];
        m_SmokePosZ = smoke_point_pos[2];
    }
SetSmokePointPosition() [2/2]
void FireplaceBase::SetSmokePointPosition (vector smoke_point_pos) inline private
Definition at line 125 of file ovenindoor.c.
    {
        m_SmokePosX = smoke_point_pos[0];
        m_SmokePosY = smoke_point_pos[1];
        m_SmokePosZ = smoke_point_pos[2];
    }
SoundBarrelClosePlay()
void FireplaceBase::SoundBarrelClosePlay () inline private
Definition at line 520 of file barrelholes_colorbase.c.
    {
        EffectSound sound = SEffectManager.PlaySound( "barrel_close_SoundSet", GetPosition() );
        sound.SetAutodestroy( true );
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
SoundBarrelOpenPlay()
void FireplaceBase::SoundBarrelOpenPlay () inline private
Definition at line 514 of file barrelholes_colorbase.c.
    {
        EffectSound sound = SEffectManager.PlaySound( "barrel_open_SoundSet", GetPosition() );
        sound.SetAutodestroy( true );
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
UpdateVisualState()
protected void FireplaceBase::UpdateVisualState () inline private
Definition at line 437 of file barrelholes_colorbase.c.
    {
        if ( IsOpen() )
        {
            SetAnimationPhase( ANIMATION_OPENED, 0 );
            SetAnimationPhase( ANIMATION_CLOSED, 1 );
        }
        else
        {
            SetAnimationPhase( ANIMATION_OPENED, 1 );
            SetAnimationPhase( ANIMATION_CLOSED, 0 );
        }
    }
References IsOpen().
Member Data Documentation
ANIMATION_CLOSED
const string FireplaceBase::ANIMATION_CLOSED = "LidOn" private
Definition at line 5 of file barrelholes_colorbase.c.
ANIMATION_OPENED
const string FireplaceBase::ANIMATION_OPENED = "LidOff" private
Definition at line 4 of file barrelholes_colorbase.c.
FIREPOINT_ACTION_SELECTION
const string FireplaceBase::FIREPOINT_ACTION_SELECTION = "fireplace_action" static private
Definition at line 8 of file fireplaceindoor.c.
FIREPOINT_FIRE_POSITION
const string FireplaceBase::FIREPOINT_FIRE_POSITION = "fireplace_point" static private
Definition at line 9 of file fireplaceindoor.c.
FIREPOINT_PLACE_ROT
const string FireplaceBase::FIREPOINT_PLACE_ROT = "fireplace_rot" static private
Definition at line 10 of file fireplaceindoor.c.
FIREPOINT_SMOKE_POSITION
const string FireplaceBase::FIREPOINT_SMOKE_POSITION = "fireplace_smoke" static private
Definition at line 11 of file fireplaceindoor.c.
m_ContactEventProcessing
bool FireplaceBase::m_ContactEventProcessing private
Definition at line 3 of file fireplace.c.
m_FirePointIndex
protected int FireplaceBase::m_FirePointIndex = 1 private
Definition at line 6 of file fireplaceindoor.c.
m_IsOpenedClient
protected bool FireplaceBase::m_IsOpenedClient = false private
Definition at line 7 of file barrelholes_colorbase.c.
m_Openable
protected ref OpenableBehaviour FireplaceBase::m_Openable private
Definition at line 9 of file barrelholes_colorbase.c.
m_SmokePosX
protected float FireplaceBase::m_SmokePosX private
Definition at line 3 of file fireplaceindoor.c.
m_SmokePosY
protected float FireplaceBase::m_SmokePosY private
Definition at line 4 of file fireplaceindoor.c.
m_SmokePosZ
protected float FireplaceBase::m_SmokePosZ private
Definition at line 5 of file fireplaceindoor.c.
OVENPOINT_ACTION_SELECTION
const string FireplaceBase::OVENPOINT_ACTION_SELECTION = "oven_action" static private
Definition at line 8 of file ovenindoor.c.
OVENPOINT_FIRE_POSITION
const string FireplaceBase::OVENPOINT_FIRE_POSITION = "oven_point" static private
Definition at line 9 of file ovenindoor.c.
OVENPOINT_PLACE_ROT
const string FireplaceBase::OVENPOINT_PLACE_ROT = "oven_rot" static private
Definition at line 10 of file ovenindoor.c.
OVENPOINT_SMOKE_POSITION
const string FireplaceBase::OVENPOINT_SMOKE_POSITION = "oven_smoke" static private
Definition at line 11 of file ovenindoor.c.