DayzKode: SlotsContainer Class Reference
SlotsContainer Class Reference
Private Member Functions
override EntityAI GetFocusedItem ()
override SlotsIcon GetFocusedSlotsIcon ()
SlotsIcon GetSlotIcon (int index)
int GetVisibleFocus ()
override bool IsDisplayable ()
override bool IsEmpty ()
override bool SelectItem ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetFocus (int index)
override void SetLastFocus ()
override void SetLayoutName ()
override void SetNextLeftActive ()
override void SetNextRightActive ()
void SetVisibleFocus (int index)
void SlotsContainer (LayoutHolder parent, EntityAI slot_parent)
override void Unfocus ()
override void UnfocusAll ()
void UpdateIcon ()
bool VerifySlotsIconVisibility (int idx=-1)
Returns 'true' if radial icon is VISIBLE and also OPEN (individual icon or any icon, use parameter..)
Private Attributes
protected ref array< ref SlotsIcon > m_Icons
int m_VisibleColumnCount
Detailed Description
Definition at line 1 of file slotscontainer.c.
Constructor & Destructor Documentation
SlotsContainer()
void SlotsContainer::SlotsContainer (LayoutHolder parent, EntityAI slot_parent) inline private
Definition at line 6 of file slotscontainer.c.
    {
        m_Icons = new array<ref SlotsIcon>;
        for ( int i = 0; i < ITEMS_IN_ROW; i++ )
        {
            if ( GetRootWidget().FindAnyWidget( "Icon" + i ) )
                m_Icons.Insert( new SlotsIcon( this, GetRootWidget().FindAnyWidget( "Icon" + i ), i , slot_parent) );
            else
            {
                Widget child = GetRootWidget().GetChildren();
                while ( child )
                {
                    child = child.GetSibling();
                }
            }
        }
    }
References FindAnyWidget(), ITEMS_IN_ROW, and m_Icons.
Member Function Documentation
GetFocusedItem()
override EntityAI SlotsContainer::GetFocusedItem () inline private
Definition at line 226 of file slotscontainer.c.
    {
        SlotsIcon focus_icon = GetFocusedSlotsIcon();
        if(focus_icon)
        {
            return EntityAI.Cast(focus_icon.GetObject());
        }
        return null;
    }
References GetFocusedSlotsIcon(), and SlotsIcon::GetObject().
Referenced by SelectItem(), and UpdateIcon().
GetFocusedSlotsIcon()
override SlotsIcon SlotsContainer::GetFocusedSlotsIcon () inline private
Definition at line 217 of file slotscontainer.c.
    {
        if (m_Icons.Count())
        {
            return m_Icons.Get(m_FocusedColumn);
        }
        return null;
    }
References m_Icons.
Referenced by AttachmentCategoriesSlotsContainer::ExpandCollapseContainer(), AttachmentCategoriesSlotsContainer::GetFocusedID(), GetFocusedItem(), AttachmentCategoriesSlotsContainer::GetFocusedItem(), and SelectItem().
GetSlotIcon()
SlotsIcon SlotsContainer::GetSlotIcon (int index) inline private
Definition at line 207 of file slotscontainer.c.
    {
        if ( m_Icons.IsValidIndex( index ) )
        {
            return m_Icons.Get( index );
        }
        return null;
    }
References m_Icons.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ZombieContainer::GetSlotsIcon(), AttachmentsGroupContainer::GetSlotsIcon(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), IsDisplayable(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), VicinitySlotsContainer::RecomputeNumberOfContainers(), AttachmentCategoriesContainer::ShowInSlots(), VicinitySlotsContainer::ShowItemsInContainers(), and UpdateIcon().
GetVisibleFocus()
int SlotsContainer::GetVisibleFocus () inline private
Definition at line 75 of file slotscontainer.c.
    {
        int visible_icons_count = 0;
        for (int i = 0; i < GetColumnCount(); i++)
        {
            if (m_FocusedColumn == i)
            {
                return visible_icons_count;
            }
            SlotsIcon icon = m_Icons[i];
            if (icon.IsVisible())
            {
                visible_icons_count++;
            }
        }
        return visible_icons_count - 1;
    }
References SlotsIcon::IsVisible(), and m_Icons.
Referenced by AttachmentsGroupContainer::SetNextActive(), and AttachmentsGroupContainer::SetPreviousActive().
IsDisplayable()
override bool SlotsContainer::IsDisplayable () inline private
Definition at line 193 of file slotscontainer.c.
    {
        if (m_ForcedShow)
            return true;
        for (int i = 0; i < m_ColumnCount; i++)
        {
            if ( GetSlotIcon(i).IsVisible() )
            {
                return true;
            }
        }
        return false;
    }
References GetSlotIcon(), and IsVisible().
IsEmpty()
override bool SlotsContainer::IsEmpty () inline private
Definition at line 188 of file slotscontainer.c.
    {
        return false;
    }
SelectItem()
override bool SlotsContainer::SelectItem () inline private
Definition at line 175 of file slotscontainer.c.
    {
        ItemBase item = ItemBase.Cast( GetFocusedItem() );
        SlotsIcon icon = GetFocusedSlotsIcon();
        if( item && !item.IsLockedInSlot() && !icon.IsOutOfReach() && !icon.IsReserved() && item.IsTakeable())
        {
            ItemManager.GetInstance().SetSelectedItem( item, null, icon.GetCursorWidget(), icon );
            return true;
        }
        return false;
    }
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), GetFocusedSlotsIcon(), ItemManager::GetInstance(), SlotsIcon::IsOutOfReach(), SlotsIcon::IsReserved(), ItemBase::IsTakeable(), and ItemManager::SetSelectedItem().
SetDefaultFocus()
override void SlotsContainer::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 24 of file slotscontainer.c.
    {
        m_FocusedColumn = 0;
        for (int i = 0; i < GetColumnCount(); i++)
        {
            SlotsIcon icon = m_Icons[i];
            if (icon.IsVisible())
            {
                m_FocusedColumn = i;
                break;
            }
        }
        SetFocus( m_FocusedColumn );
    }
References SlotsIcon::IsVisible(), m_Icons, and SetFocus().
Referenced by SetLastFocus().
SetFocus()
void SlotsContainer::SetFocus (int index) inline private
Definition at line 45 of file slotscontainer.c.
    {
        if ( index >= 0 && index < m_Icons.Count() )
        {
            m_Icons.Get( index ).GetCursorWidget().Show( true );
        }
        UpdateIcon();
    }
References m_Icons, and UpdateIcon().
Referenced by SetDefaultFocus(), and SetVisibleFocus().
SetLastFocus()
override void SlotsContainer::SetLastFocus () inline private
Definition at line 40 of file slotscontainer.c.
    {
        SetDefaultFocus();
    }
References SetDefaultFocus().
SetLayoutName()
override void SlotsContainer::SetLayoutName () inline private
Definition at line 238 of file slotscontainer.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_LayoutName = WidgetLayoutName.InventorySlotsContainerXbox;
        #else
            switch ( InventoryMenu.GetWidthType() )
            {
                case ScreenWidthType.NARROW:
                {
                    m_LayoutName = WidgetLayoutName.InventorySlotsContainerNarrow;
                    break;
                }
                case ScreenWidthType.MEDIUM:
                {
                    m_LayoutName = WidgetLayoutName.InventorySlotsContainerMedium;
                    break;
                }
                case ScreenWidthType.WIDE:
                {
                    m_LayoutName = WidgetLayoutName.InventorySlotsContainerWide;
                    break;
                }
            }
        #endif
    }
References InventoryMenu(), WidgetLayoutName::InventorySlotsContainerMedium, WidgetLayoutName::InventorySlotsContainerNarrow, WidgetLayoutName::InventorySlotsContainerWide, and WidgetLayoutName::InventorySlotsContainerXbox.
SetNextLeftActive()
override void SlotsContainer::SetNextLeftActive () inline private
Definition at line 116 of file slotscontainer.c.
    {
        Unfocus();
        int index = m_FocusedColumn - 1;
        for (int i = 0; i < GetColumnCount(); i++ )
        {
            if (index < 0)
            {
                index = GetColumnCount() - 1;
            }
            SlotsIcon icon = m_Icons[index];
            if (icon.IsVisible())
            {
                m_FocusedColumn = index;
                break;
            }
            index--;
        }
        UpdateIcon();
    }
References SlotsIcon::IsVisible(), m_Icons, Unfocus(), and UpdateIcon().
SetNextRightActive()
override void SlotsContainer::SetNextRightActive () inline private
Definition at line 93 of file slotscontainer.c.
    {
        Unfocus();
        int index = m_FocusedColumn + 1;
        for (int i = 0; i < GetColumnCount(); i++ )
        {
            if (index >= GetColumnCount())
            {
                index = 0;
            }
            SlotsIcon icon = m_Icons[index];
            if (icon.IsVisible())
            {
                m_FocusedColumn = index;
                break;
            }
            index++;
        }
        UpdateIcon();
    }
References SlotsIcon::IsVisible(), m_Icons, Unfocus(), and UpdateIcon().
SetVisibleFocus()
void SlotsContainer::SetVisibleFocus (int index) inline private
Definition at line 54 of file slotscontainer.c.
    {
        Unfocus();
        int visible_icons_count = 0;
        m_FocusedColumn = 0;
        for (int i = 0; i < GetColumnCount(); i++)
        {
            SlotsIcon icon = m_Icons[i];
            if (icon.IsVisible())
            {
                m_FocusedColumn = i;
                if (visible_icons_count == index)
                    break;
                visible_icons_count++;
            }
        }
        SetFocus( m_FocusedColumn );
    }
References SlotsIcon::IsVisible(), m_Icons, SetFocus(), and Unfocus().
Referenced by AttachmentsGroupContainer::SetNextActive(), and AttachmentsGroupContainer::SetPreviousActive().
Unfocus()
override void SlotsContainer::Unfocus () inline private
Definition at line 166 of file slotscontainer.c.
    {
        Widget w = m_Icons.Get( m_FocusedColumn ).GetCursorWidget();
        if ( w )
        {
            w.Show( false );
        }
    }
References m_Icons.
Referenced by SetNextLeftActive(), SetNextRightActive(), and SetVisibleFocus().
UnfocusAll()
override void SlotsContainer::UnfocusAll () inline private
Definition at line 158 of file slotscontainer.c.
    {
        for (int i = 0; i < m_Icons.Count(); i++)
        {
            m_Icons.Get( i ).GetCursorWidget().Show( false );
        }
    }
References m_Icons.
UpdateIcon()
void SlotsContainer::UpdateIcon () inline private
Definition at line 139 of file slotscontainer.c.
    {
        float x, y;
        SlotsIcon icon = GetSlotIcon( m_FocusedColumn );
        icon.GetCursorWidget().Show( true );
        icon.GetCursorWidget().GetScreenPos( x, y );
        EntityAI focused_item = GetFocusedItem();
        if ( focused_item )
        {
            PrepareOwnedTooltip( focused_item, -1, y ); //custom positioning for the controller
        }
        else
        {
            PrepareOwnedSlotsTooltip( icon.GetCursorWidget(), icon.GetSlotDisplayName(), icon.GetSlotDesc(), x, y );
        }
    }
References SlotsIcon::GetCursorWidget(), GetFocusedItem(), SlotsIcon::GetSlotDesc(), SlotsIcon::GetSlotDisplayName(), GetSlotIcon(), x, and y.
Referenced by SetFocus(), SetNextLeftActive(), and SetNextRightActive().
VerifySlotsIconVisibility()
bool SlotsContainer::VerifySlotsIconVisibility (int idx = -1) inline private
Returns 'true' if radial icon is VISIBLE and also OPEN (individual icon or any icon, use parameter..)
Definition at line 266 of file slotscontainer.c.
    {
        if (idx != -1)
        {
            return m_Icons[idx].IsVisible() && m_Icons[idx].GetRadialIconPanel().IsVisible() && m_Icons[idx].GetRadialIcon().IsVisible();
        }
        else
        {
            int count = m_Icons.Count();
            for (int i = 0; i < count; i++)
            {
                if (m_Icons[i].IsVisible() && m_Icons[i].GetRadialIconPanel().IsVisible() && m_Icons[i].GetRadialIcon().IsVisible())
                {
                    return true;
                }
            }
        }
        return false;
    }
References IsVisible(), and m_Icons.
Member Data Documentation
m_Icons
protected ref array<ref SlotsIcon> SlotsContainer::m_Icons private
Definition at line 3 of file slotscontainer.c.
Referenced by GetFocusedSlotsIcon(), GetSlotIcon(), GetVisibleFocus(), SetDefaultFocus(), SetFocus(), SetNextLeftActive(), SetNextRightActive(), SetVisibleFocus(), SlotsContainer(), Unfocus(), UnfocusAll(), and VerifySlotsIconVisibility().
m_VisibleColumnCount
int SlotsContainer::m_VisibleColumnCount private
Definition at line 4 of file slotscontainer.c.