DayzKode: SoundSetMap Class Reference
SoundSetMap Class Reference
Static Private Member Functions
static int GetSoundSetID (string name)
static string GetSoundSetName (int id)
static void Init ()
Static Private Attributes
static ref map< int, string > m_SoundSetMapIDByID = new map<int, string>
static ref map< string, int > m_SoundSetMapIDByName = new map<string, int>
Detailed Description
Definition at line 1 of file soundsetmap.c.
Member Function Documentation
GetSoundSetID()
static int SoundSetMap::GetSoundSetID (string name) inline static private
Definition at line 27 of file soundsetmap.c.
    {
        return m_SoundSetMapIDByName.Get(name);
    }
References m_SoundSetMapIDByName, and name.
GetSoundSetName()
static string SoundSetMap::GetSoundSetName (int id) inline static private
Definition at line 22 of file soundsetmap.c.
    {
        return m_SoundSetMapIDByID.Get(id);
    }
References m_SoundSetMapIDByID.
Init()
static void SoundSetMap::Init () inline static private
Definition at line 6 of file soundsetmap.c.
    {
        string path = "CfgSoundSets";
        int soundCount = GetGame().ConfigGetChildrenCount(path);
        for (int i = 1; i < soundCount; i++)
        {
            string soundClassName;
            GetGame().ConfigGetChildName(path, i, soundClassName);
            m_SoundSetMapIDByID.Insert(i,soundClassName);
            m_SoundSetMapIDByName.Insert(soundClassName,i);
            //PrintString(soundClassName);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), m_SoundSetMapIDByID, m_SoundSetMapIDByName, and path.
Referenced by MissionBaseWorld::MissionBase().
Member Data Documentation
m_SoundSetMapIDByID
ref map<int, string> SoundSetMap::m_SoundSetMapIDByID = new map<int, string> static private
Definition at line 3 of file soundsetmap.c.
Referenced by GetSoundSetName(), and Init().
m_SoundSetMapIDByName
ref map<string, int> SoundSetMap::m_SoundSetMapIDByName = new map<string, int> static private
Definition at line 4 of file soundsetmap.c.
Referenced by GetSoundSetID(), and Init().