DayzKode: Plastic_Explosive Class Reference
Plastic_Explosive Class Reference
Private Member Functions
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanRemoveFromHands (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEKilled (Object killer)
special behaviour - do not call super from ExplosivesBase
override bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override void EOnInit (IEntity other, int extra)
override EntityAI GetPairDevice ()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override bool HasLockedTriggerSlots ()
override bool IsDeployable ()
override bool IsTakeable ()
override void LockTriggerSlots ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnDisarmed (bool pWithTool)
protected void OnTriggerAttached (EntityAI entity)
protected void OnTriggerDetached (EntityAI entity)
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void PairRemote (notnull EntityAI trigger)
void Plastic_Explosive ()
override void SetActions ()
override void UnlockTriggerSlots ()
override void UnpairRemote ()
override void UpdateLED (int pState)
protected void UpdateVisuals (EntityAI entity)
Private Attributes
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote"
protected ref RemotelyActivatedItemBehaviour m_RAIB
protected bool m_UsedAsCharge
protected const string SLOT_TRIGGER = "TriggerRemoteDetonator_Receiver"
Detailed Description
Definition at line 1 of file plastic_explosive.c.
Constructor & Destructor Documentation
Plastic_Explosive()
void Plastic_Explosive::Plastic_Explosive () inline private
Definition at line 10 of file plastic_explosive.c.
    {
        m_RAIB = new RemotelyActivatedItemBehaviour(this);
        SetAmmoType("Plastic_Explosive_Ammo");
        SetParticleExplosion(ParticleList.PLASTIC_EXPLOSION);
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
    }
References m_RAIB, ParticleList::PLASTIC_EXPLOSION, SetAmmoType(), and SetParticleExplosion().
Member Function Documentation
CanBeArmed()
override bool Plastic_Explosive::CanBeArmed () inline private
Definition at line 228 of file plastic_explosive.c.
    {
        if (!super.CanBeArmed())
        {
            return false;
        }
        return HasLockedTriggerSlots() && !GetArmed();
    }
References GetArmed(), and HasLockedTriggerSlots().
CanBeDisarmed()
override bool Plastic_Explosive::CanBeDisarmed () inline private
Definition at line 238 of file plastic_explosive.c.
    {
        return GetArmed();
    }
References GetArmed().
CanDisplayAttachmentSlot()
override bool Plastic_Explosive::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 114 of file plastic_explosive.c.
    {
        string slotName = InventorySlots.GetSlotName(slot_id);
        switch (slotName)
        {
        case SLOT_TRIGGER:
            return FindAttachmentBySlotName(slotName) != null;
        break;
        }
        return true;
    }
References InventorySlots::GetSlotName(), and SLOT_TRIGGER.
CanPutInCargo()
override bool Plastic_Explosive::CanPutInCargo (EntityAI parent) inline private
Definition at line 71 of file plastic_explosive.c.
    {
        if ( !super.CanPutInCargo(parent) )
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanPutIntoHands()
override bool Plastic_Explosive::CanPutIntoHands (EntityAI parent) inline private
Definition at line 81 of file plastic_explosive.c.
    {
        if (!super.CanPutIntoHands(parent))
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanReceiveAttachment()
override bool Plastic_Explosive::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 96 of file plastic_explosive.c.
    {
        InventoryLocation il = new InventoryLocation();
        GetInventory().GetCurrentInventoryLocation(il);
        if (il.GetType() == InventoryLocationType.HANDS)
        {
            return false;
        }
        ClockBase timer = ClockBase.Cast(attachment);
        if (timer && !timer.IsAlarmOn())
        {
            return false;
        }
        return !GetArmed();
    }
References ClockBase(), GetArmed(), and InventoryLocation::GetType().
CanRemoveFromHands()
override bool Plastic_Explosive::CanRemoveFromHands (EntityAI parent) inline private
Definition at line 91 of file plastic_explosive.c.
    {
        return IsTakeable();
    }
References IsTakeable().
EEHealthLevelChanged()
override void Plastic_Explosive::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 179 of file plastic_explosive.c.
    {
        super.EEHealthLevelChanged(oldLevel, newLevel, zone);
        if (GetGame().IsServer())
        {
            if (newLevel == GameConstants.STATE_RUINED)
            {
                for (int attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
                {
                    ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
                    if (attachment)
                    {
                        attachment.UnlockFromParent();
                        attachment.SetHealth("", "", 0.0);
                    }
                }
                SetArmed(false);
                SetTakeable(true);
            }
        }
    }
References GetGame(), SetArmed(), SetTakeable(), and GameConstants::STATE_RUINED.
EEItemAttached()
override void Plastic_Explosive::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 302 of file plastic_explosive.c.
    {
        super.EEItemAttached(item, slot_name);
        switch (slot_name)
        {
        case SLOT_TRIGGER:
            OnTriggerAttached(item);
        break;
        }
    }
References OnTriggerAttached(), and SLOT_TRIGGER.
EEItemDetached()
override void Plastic_Explosive::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 314 of file plastic_explosive.c.
    {
        super.EEItemDetached(item, slot_name);
        switch (slot_name)
        {
        case SLOT_TRIGGER:
            OnTriggerDetached(item);
        break;
        }
    }
References OnTriggerDetached(), and SLOT_TRIGGER.
EEItemLocationChanged()
override void Plastic_Explosive::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 61 of file plastic_explosive.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (m_RAIB)
        {
            m_RAIB.Pair();
        }
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EEKilled()
override void Plastic_Explosive::EEKilled (Object killer) inline private
special behaviour - do not call super from ExplosivesBase
Definition at line 27 of file plastic_explosive.c.
    {
        //analytics (behaviour from EntityAI)
        GetGame().GetAnalyticsServer().OnEntityKilled(killer, this);
    }
References CGame::GetAnalyticsServer(), GetGame(), and AnalyticsManagerServer::OnEntityKilled().
EEOnDamageCalculated()
override bool Plastic_Explosive::EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
ignores explosion damage from other Plastic_Explosive that are used as charge(like 2 PE fired via IED)
Definition at line 168 of file plastic_explosive.c.
    {
        if (damageType == DamageType.EXPLOSION)
        {
            return !m_UsedAsCharge;
        }
        return true;
    }
References m_UsedAsCharge.
EOnInit()
override void Plastic_Explosive::EOnInit (IEntity other, int extra) inline private
Definition at line 21 of file plastic_explosive.c.
    {
        LockTriggerSlots();
    }
References LockTriggerSlots().
GetPairDevice()
override EntityAI Plastic_Explosive::GetPairDevice () inline private
Definition at line 223 of file plastic_explosive.c.
    {
        return m_RAIB.GetPairDevice();
    }
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by OnActivatedByItem(), and UnpairRemote().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour Plastic_Explosive::GetRemotelyActivatedItemBehaviour () inline private
Definition at line 203 of file plastic_explosive.c.
    {
        return m_RAIB;
    }
References m_RAIB.
HasLockedTriggerSlots()
override bool Plastic_Explosive::HasLockedTriggerSlots () inline private
Definition at line 33 of file plastic_explosive.c.
    {
        return GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGER));
    }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
Referenced by CanBeArmed().
IsDeployable()
override bool Plastic_Explosive::IsDeployable () inline private
Definition at line 133 of file plastic_explosive.c.
    {
        return !GetArmed();
    }
References GetArmed().
IsTakeable()
override bool Plastic_Explosive::IsTakeable () inline private
Definition at line 128 of file plastic_explosive.c.
    {
        return !GetArmed() && super.IsTakeable();
    }
References GetArmed().
Referenced by CanPutInCargo(), CanPutIntoHands(), and CanRemoveFromHands().
LockTriggerSlots()
override void Plastic_Explosive::LockTriggerSlots () inline private
Definition at line 38 of file plastic_explosive.c.
    {
        GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGER), true);
    }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
Referenced by EOnInit(), and OnDisarmed().
OnActivatedByItem()
override void Plastic_Explosive::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 243 of file plastic_explosive.c.
    {
        if (GetGame().IsServer())
        {
            if (GetHealthLevel("") == GameConstants.STATE_RUINED)
            {
                return;
            }
            if (item == this)
            {
                SetHealth("", "", 0.0);
                InitiateExplosion();
                return;
            }
            if (m_RAIB.IsPaired() && GetArmed())
            {
                if (GetPairDevice() == item)
                {
                    SetHealth("", "", 0.0);
                    InitiateExplosion();
                }
            }
        }
    }
References GetArmed(), GetGame(), GetHealthLevel(), GetPairDevice(), InitiateExplosion(), RemotelyActivatedItemBehaviour::IsPaired(), m_RAIB, SetHealth(), and GameConstants::STATE_RUINED.
OnDisarmed()
override void Plastic_Explosive::OnDisarmed (bool pWithTool) inline private
Definition at line 270 of file plastic_explosive.c.
    {
        super.OnDisarmed(pWithTool);
        UnpairRemote();
        UpdateVisuals(null);
        for (int att = 0; att < GetInventory().AttachmentCount(); att++)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
            if (attachment)
            {
                attachment.UnlockFromParent();
                if (attachment.IsInherited(RemoteDetonator))
                {
                    if (pWithTool)
                    {
                        GetInventory().DropEntity(InventoryMode.SERVER, this, attachment);
                        attachment.SetHealth("", "", 0.0);
                    }
                    else
                    {
                        attachment.Delete();
                    }
                }
            }
        }
        LockTriggerSlots();
        SetTakeable(true);
    }
References LockTriggerSlots(), SetTakeable(), UnpairRemote(), and UpdateVisuals().
OnTriggerAttached()
protected void Plastic_Explosive::OnTriggerAttached (EntityAI entity) inline private
Definition at line 335 of file plastic_explosive.c.
    {
        Arm();
        UpdateVisuals(entity);
        UpdateLED(ERemoteDetonatorLEDState.LIT);
        for (int att = 0; att < GetInventory().AttachmentCount(); att++)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
            if (attachment)
            {
                attachment.LockToParent();
            }
        }
    }
References Arm(), UpdateLED(), and UpdateVisuals().
Referenced by EEItemAttached().
OnTriggerDetached()
protected void Plastic_Explosive::OnTriggerDetached (EntityAI entity) inline private
Definition at line 351 of file plastic_explosive.c.
    {
        UpdateVisuals(null);
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
References UpdateLED(), and UpdateVisuals().
Referenced by EEItemDetached().
OnVariablesSynchronized()
override void Plastic_Explosive::OnVariablesSynchronized () inline private
Definition at line 48 of file plastic_explosive.c.
    {
        super.OnVariablesSynchronized();
        if (m_RAIB)
        {
            m_RAIB.OnVariableSynchronized();
        }
        int slotId = InventorySlots.GetSlotIdFromString(SLOT_TRIGGER);
        UpdateVisuals(GetInventory().FindAttachment(slotId));
    }
References FindAttachment(), InventorySlots::GetSlotIdFromString(), m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), SLOT_TRIGGER, and UpdateVisuals().
OnWasAttached()
override void Plastic_Explosive::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 146 of file plastic_explosive.c.
    {
        super.OnWasAttached(parent, slot_id);
        m_UsedAsCharge = false;
        if (parent && parent.IsInherited(ExplosivesBase))
        {
            m_UsedAsCharge = true;
        }
    }
References ExplosivesBase(), and m_UsedAsCharge.
OnWasDetached()
override void Plastic_Explosive::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 158 of file plastic_explosive.c.
    {
        super.OnWasDetached(parent, slot_id);
        if (parent && !parent.IsInherited(ExplosivesBase))
        {
            m_UsedAsCharge = false;
        }
    }
References ExplosivesBase(), and m_UsedAsCharge.
PairRemote()
override void Plastic_Explosive::PairRemote (notnull EntityAI trigger) inline private
Definition at line 208 of file plastic_explosive.c.
    {
        m_RAIB.Pair(trigger);
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
SetActions()
override void Plastic_Explosive::SetActions () inline private
Definition at line 138 of file plastic_explosive.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), and AddAction().
UnlockTriggerSlots()
override void Plastic_Explosive::UnlockTriggerSlots () inline private
Definition at line 43 of file plastic_explosive.c.
    {
        GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGER), false);
    }
References InventorySlots::GetSlotIdFromString(), and SLOT_TRIGGER.
UnpairRemote()
override void Plastic_Explosive::UnpairRemote () inline private
Definition at line 213 of file plastic_explosive.c.
    {
        if (GetPairDevice())
        {
            GetPairDevice().UnpairRemote();
        }
        m_RAIB.Unpair();
    }
References GetPairDevice(), m_RAIB, and RemotelyActivatedItemBehaviour::Unpair().
Referenced by OnDisarmed().
UpdateLED()
override void Plastic_Explosive::UpdateLED (int pState) inline private
Definition at line 326 of file plastic_explosive.c.
    {
        RemoteDetonatorReceiver receiver = RemoteDetonatorReceiver.Cast(FindAttachmentBySlotName(SLOT_TRIGGER));
        if (receiver)
        {
            receiver.UpdateLED(pState, true);
        }
    }
References RemoteDetonatorReceiver(), and SLOT_TRIGGER.
Referenced by OnTriggerAttached(), and OnTriggerDetached().
UpdateVisuals()
protected void Plastic_Explosive::UpdateVisuals (EntityAI entity) inline private
Definition at line 357 of file plastic_explosive.c.
    {
        if (entity)
        {
            SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 0.0);
        }
        else
        {
            SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
        }
    }
References ANIM_PHASE_TRIGGER_REMOTE.
Member Data Documentation
ANIM_PHASE_TRIGGER_REMOTE
protected const string Plastic_Explosive::ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote" private
Definition at line 4 of file plastic_explosive.c.
Referenced by UpdateVisuals().
m_RAIB
protected ref RemotelyActivatedItemBehaviour Plastic_Explosive::m_RAIB private
Definition at line 8 of file plastic_explosive.c.
Referenced by EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), OnActivatedByItem(), OnVariablesSynchronized(), PairRemote(), Plastic_Explosive(), and UnpairRemote().
m_UsedAsCharge
protected bool Plastic_Explosive::m_UsedAsCharge private
Definition at line 6 of file plastic_explosive.c.
Referenced by EEOnDamageCalculated(), OnWasAttached(), and OnWasDetached().
SLOT_TRIGGER
protected const string Plastic_Explosive::SLOT_TRIGGER = "TriggerRemoteDetonator_Receiver" private
Definition at line 3 of file plastic_explosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), EEItemDetached(), HasLockedTriggerSlots(), LockTriggerSlots(), OnVariablesSynchronized(), UnlockTriggerSlots(), and UpdateLED().