DayzKode: HumanCommandWeapons Class Reference
HumanCommandWeapons Class Reference
Private Member Functions
proto native int DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native void DebugResetEvents ()
proto native float GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
proto native float GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
proto native int GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
proto native int GetRunningActionType ()
returns -1 when no action is running or appropriate action type
private void HumanCommandWeapons ()
proto native bool IsActionFinished ()
proto native int IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native bool IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
proto native bool IsThrowingMode ()
proto native void LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
void RegisterDefaultEvents ()
proto native void RegisterEvent (string pName, int pId)
register events
proto native void SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
proto native void SetADS (bool pState)
sets head tilt to optics
proto native void SetInitState (int pFrameIndex)
proto native void SetThrowingMode (bool pState)
proto native bool StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
proto native void ThrowItem (int throwType)
proto native bool WasItemLeaveHandsEvent ()
private void ~HumanCommandWeapons ()
Static Private Member Functions
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx)
just static version of SetInitState
Detailed Description
Definition at line 940 of file human.c.
Constructor & Destructor Documentation
HumanCommandWeapons()
private void HumanCommandWeapons::HumanCommandWeapons () inline private
Definition at line 942 of file human.c.
{}
~HumanCommandWeapons()
private void HumanCommandWeapons::~HumanCommandWeapons () inline private
Definition at line 943 of file human.c.
{}
Member Function Documentation
DebugIsEvent()
proto native int HumanCommandWeapons::DebugIsEvent () private
return -1 when there is no event, otherwise it returns pId of event from animation
Referenced by PluginDayzPlayerDebug_Weapons::Tick().
DebugResetEvents()
proto native void HumanCommandWeapons::DebugResetEvents () private
Referenced by PluginDayzPlayerDebug_Weapons::PluginDayzPlayerDebug_Weapons().
GetBaseAimingAngleLR()
proto native float HumanCommandWeapons::GetBaseAimingAngleLR () private
returns base aiming angle LR - without sway/offsets/...
Referenced by HandleProneKick(), and DayZPlayerImplementThrowing::HandleThrowing().
GetBaseAimingAngleUD()
proto native float HumanCommandWeapons::GetBaseAimingAngleUD () private
returns base aiming angle UD - without sway/offsets/...
Referenced by DayZPlayerImplementThrowing::HandleThrowing(), and UpdateUDAngle().
GetRunningAction()
proto native int HumanCommandWeapons::GetRunningAction () private
returns -1 when no action is running or RELOAD,MECHANISM, ....
Referenced by FirearmActionAttachMagazine::ActionCondition(), FirearmActionAttachMagazineQuick::ActionCondition(), FirearmActionLoadBullet::ActionCondition(), FirearmActionLoadBulletQuick::ActionCondition(), CommandHandlerDebug(), HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and PluginDayzPlayerDebug_Weapons::Tick().
GetRunningActionType()
proto native int HumanCommandWeapons::GetRunningActionType () private
returns -1 when no action is running or appropriate action type
Referenced by HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and PluginDayzPlayerDebug_Weapons::Tick().
IsActionFinished()
proto native bool HumanCommandWeapons::IsActionFinished () private
Referenced by CommandHandlerDebug(), HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and Play().
IsEvent()
proto native int HumanCommandWeapons::IsEvent () private
return -1 when there is no event, otherwise it returns pId of event from animation
Referenced by CommandHandlerDebug(), HandleInventory(), and HandleWeaponEvents().
IsInWeaponReloadBulletSwitchState()
proto native bool HumanCommandWeapons::IsInWeaponReloadBulletSwitchState () private
returns true when clip visual change is needed for reload clip action
IsThrowingMode()
proto native bool HumanCommandWeapons::IsThrowingMode () private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
LiftWeapon()
proto native void HumanCommandWeapons::LiftWeapon (bool pState) private
command for lifting weapon near obstacled (works only when weapon is raised)
Referenced by ManBase::ProcessLiftWeapon(), and ManBase::SendLiftWeaponSync().
RegisterDefaultEvents()
void HumanCommandWeapons::RegisterDefaultEvents () inline private
Definition at line 976 of file human.c.
    {
        RegisterEvent("Weapon_AttachmentHide", WeaponEvents.ATTACHMENT_HIDE);
        RegisterEvent("Weapon_AttachmentShow", WeaponEvents.ATTACHMENT_SHOW);
        RegisterEvent("Weapon_BulletEject", WeaponEvents.BULLET_EJECT);
        RegisterEvent("Weapon_BulletHide", WeaponEvents.BULLET_HIDE);
        RegisterEvent("Weapon_BulletHide2", WeaponEvents.BULLET_HIDE2);
        RegisterEvent("Weapon_BulletInChamber", WeaponEvents.BULLET_IN_CHAMBER);
        RegisterEvent("Weapon_BulletInMagazine", WeaponEvents.BULLET_IN_MAGAZINE);
        RegisterEvent("Weapon_BulletShow", WeaponEvents.BULLET_SHOW);
        RegisterEvent("Weapon_BulletShow2", WeaponEvents.BULLET_SHOW2);
        RegisterEvent("Weapon_CanUnjam_End", WeaponEvents.CANUNJAM_END);
        RegisterEvent("Weapon_CanUnjam_Start", WeaponEvents.CANUNJAM_START);
        RegisterEvent("Weapon_Cocked", WeaponEvents.COCKED);
        RegisterEvent("Weapon_MagazineAttached", WeaponEvents.MAGAZINE_ATTACHED);
        RegisterEvent("Weapon_MagazineDetached", WeaponEvents.MAGAZINE_DETACHED);
        RegisterEvent("Weapon_MagazineHide", WeaponEvents.MAGAZINE_HIDE);
        RegisterEvent("Weapon_MagazineShow", WeaponEvents.MAGAZINE_SHOW);
        RegisterEvent("Weapon_SliderOpen", WeaponEvents.SLIDER_OPEN);
        RegisterEvent("Weapon_Unjammed", WeaponEvents.UNJAMMED);
        RegisterEvent("Weapon_Hammer_Uncocked", WeaponEvents.HAMMER_UNCOCKED);
        RegisterEvent("Weapon_Hammer_Cocked", WeaponEvents.HAMMER_COCKED);
        RegisterEvent("Weapon_Change_Hide", WeaponEvents.CHANGE_HIDE);
        RegisterEvent("Weapon_Change_Show", WeaponEvents.CHANGE_SHOW);
        RegisterEvent("Weapon_CylinderRotate", WeaponEvents.CYLINDER_ROTATE);
    }
References RegisterEvent().
RegisterEvent()
proto native void HumanCommandWeapons::RegisterEvent (string pName, int pId) private
register events
Referenced by RegisterDefaultEvents().
SetActionProgressParams()
proto native void HumanCommandWeapons::SetActionProgressParams (float pStart, float pEnd) private
sets start and end animation position - f.e. for reload clip action
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), and DayZPlayerImplementThrowing::HandleThrowing().
SetADS()
proto native void HumanCommandWeapons::SetADS (bool pState) private
sets head tilt to optics
Referenced by ExitSights(), HandleADS(), SetIronsights(), and SetOptics().
SetInitState()
proto native void HumanCommandWeapons::SetInitState (int pFrameIndex) private
this sets to a weapon init state each weapon has a different weapon state those states are defined by animation set by AddItemInHandsProfileIK - in DayZPlayerCfgBase.c each frame of animation is one init state
Referenced by PluginDayzPlayerDebug_Weapons::OnClick(), WeaponManager::RefreshAnimationState(), and SyncAnimState().
SetThrowingMode()
proto native void HumanCommandWeapons::SetThrowingMode (bool pState) private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
StartAction()
proto native bool HumanCommandWeapons::StartAction (WeaponActions pAction, int pActionType) private
start reload,mechanism,chambering,unjam ...
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), CommandHandlerDebug(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), and WeaponStartAction::OnUpdate().
StaticSetInitState()
proto static native void HumanCommandWeapons::StaticSetInitState (Human pHuman, int pFrameIdx) static private
just static version of SetInitState
Referenced by SyncAnimState().
ThrowItem()
proto native void HumanCommandWeapons::ThrowItem (int throwType) private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().
WasItemLeaveHandsEvent()
proto native bool HumanCommandWeapons::WasItemLeaveHandsEvent () private
Referenced by DayZPlayerImplementThrowing::HandleThrowing().