DayzKode: DynamicArea_Flare Class Reference
DynamicArea_Flare Class Reference
Private Member Functions
void DynamicArea_Flare ()
override void EEDelete (EntityAI parent)
override void EOnFrame (IEntity other, float timeSlice)
Private Attributes
const float FALL_SPEED = 0.5
const float LIFETIME = 40000
private Particle m_Particle
Detailed Description
Definition at line 2 of file dynamicarea_flare.c.
Constructor & Destructor Documentation
DynamicArea_Flare()
void DynamicArea_Flare::DynamicArea_Flare () inline private
Definition at line 7 of file dynamicarea_flare.c.
    {
        SetEventMask( EntityEvent.FRAME );
        SetFlags( EntityFlags.ACTIVE, false );
        // We create the particle effect
        m_Particle = ParticleManager.GetInstance().PlayOnObject( ParticleList.FLAREPROJ_ACTIVATE_RED, this );
        // We specify we will delete this object after set time
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater( GetGame().ObjectDeleteOnClient, LIFETIME, false, this );
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ParticleList::FLAREPROJ_ACTIVATE_RED, CGame::GetCallQueue(), GetGame(), LIFETIME, m_Particle, ParticleManager(), and SetFlags().
Member Function Documentation
EEDelete()
override void DynamicArea_Flare::EEDelete (EntityAI parent) inline private
Definition at line 28 of file dynamicarea_flare.c.
    {
        if ( m_Particle )
            m_Particle.Stop();
    }
References m_Particle, and Particle::Stop().
EOnFrame()
override void DynamicArea_Flare::EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 20 of file dynamicarea_flare.c.
    {
        vector newPos = GetPosition();
        newPos[1] = newPos[1] - ( FALL_SPEED * timeSlice );
        SetPosition( newPos );
    }
References FALL_SPEED, GetPosition, and SetPosition().
Member Data Documentation
FALL_SPEED
const float DynamicArea_Flare::FALL_SPEED = 0.5 private
Definition at line 4 of file dynamicarea_flare.c.
Referenced by EOnFrame().
LIFETIME
const float DynamicArea_Flare::LIFETIME = 40000 private
Definition at line 5 of file dynamicarea_flare.c.
Referenced by DynamicArea_Flare().
m_Particle
private Particle DynamicArea_Flare::m_Particle private
Definition at line 6 of file dynamicarea_flare.c.
Referenced by DynamicArea_Flare(), and EEDelete().