DayzKode: ActionTakeHybridAttachmentToHands Class Reference
ActionTakeHybridAttachmentToHands Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionTakeHybridAttachmentToHands ()
override bool CanContinue (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProgress ()
override bool HasProneException ()
override void OnExecuteClient (ActionData action_data)
protected void OnExecuteImpl (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actiontakehybridattachmenttohands.c.
Constructor & Destructor Documentation
ActionTakeHybridAttachmentToHands()
void ActionTakeHybridAttachmentToHands::ActionTakeHybridAttachmentToHands () inline private
Definition at line 3 of file actiontakehybridattachmenttohands.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS;
        m_Text = "#take_to_hands";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeHybridAttachmentToHands::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actiontakehybridattachmenttohands.c.
    {
        EntityAI tgt_entity = EntityAI.Cast( target.GetObject() );
        if ( tgt_entity && BaseBuildingBase.Cast(tgt_entity) &&!tgt_entity.IsBeingPlaced() /*&& BaseBuildingBase.Cast(tgt_entity).IsPlayerInside(player,"")*/ )
        {
            string component_name = tgt_entity.GetActionComponentName( target.GetComponentIndex() );
            ItemBase attachment = ItemBase.Cast(tgt_entity.FindAttachmentBySlotName(component_name));
            if ( attachment && player.GetInventory().CanAddEntityIntoHands(attachment) && attachment.IsTakeable() )
            {
                return true;
            }
        }
        return false;
    }
References ItemBase::IsTakeable().
CanContinue()
override bool ActionTakeHybridAttachmentToHands::CanContinue (ActionData action_data) inline private
Definition at line 49 of file actiontakehybridattachmenttohands.c.
    {
        return true;
    }
CreateAndSetupActionCallback()
override void ActionTakeHybridAttachmentToHands::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 91 of file actiontakehybridattachmenttohands.c.
    {
        EntityAI tgt_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        string component_name = tgt_entity.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
        ItemBase attachment;
        bool heavy_item = false;
        if ( tgt_entity && ItemBase.CastTo(attachment, tgt_entity.FindAttachmentBySlotName(component_name)) )
        {
            ActionBaseCB callback;
            if ( attachment && attachment.ConfigIsExisting("heavyItem") && attachment.ConfigGetBool("heavyItem") )
            {
                heavy_item = true;
            }
        }
        if( heavy_item )
        {
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            if( action_data.m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT) )
            {
                Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS,GetCallbackClassTypename()));
            }
            else
            {
                Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HANDS,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_PRONE));
            }
        }
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionData::m_Callback, ActionData::m_Player, and ActionData::m_Target.
CreateConditionComponents()
override void ActionTakeHybridAttachmentToHands::CreateConditionComponents () inline private
Definition at line 10 of file actiontakehybridattachmenttohands.c.
    {
        m_ConditionItem = new CCINotPresent;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionTakeHybridAttachmentToHands::GetInputType () inline private
Definition at line 21 of file actiontakehybridattachmenttohands.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionTakeHybridAttachmentToHands::HasProgress () inline private
Definition at line 26 of file actiontakehybridattachmenttohands.c.
    {
        return false;
    }
HasProneException()
override bool ActionTakeHybridAttachmentToHands::HasProneException () inline private
Definition at line 16 of file actiontakehybridattachmenttohands.c.
    {
        return true;
    }
OnExecuteClient()
override void ActionTakeHybridAttachmentToHands::OnExecuteClient (ActionData action_data) inline private
Definition at line 54 of file actiontakehybridattachmenttohands.c.
    {
        OnExecuteImpl(action_data);
    }
References OnExecuteImpl().
OnExecuteImpl()
protected void ActionTakeHybridAttachmentToHands::OnExecuteImpl (ActionData action_data) inline private
Definition at line 59 of file actiontakehybridattachmenttohands.c.
    {
        EntityAI tgt_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        string component_name = tgt_entity.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
        ItemBase attachment;
        if ( tgt_entity && ItemBase.CastTo(attachment, tgt_entity.FindAttachmentBySlotName(component_name)) )
        {
            ClearInventoryReservationEx(action_data);
            float stackable = attachment.GetTargetQuantityMax(-1);
            if( stackable == 0 || stackable >= attachment.GetQuantity() )
            {
                //take to hands
                action_data.m_Player.PredictiveTakeEntityToHands( attachment );
            }
            else if( stackable != 0 && stackable < attachment.GetQuantity() )
            {
                //split and take to hands
                attachment.SplitIntoStackMaxHandsClient( action_data.m_Player );
            }
        }
    }
References ClearInventoryReservationEx(), ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().
OnExecuteServer()
override void ActionTakeHybridAttachmentToHands::OnExecuteServer (ActionData action_data) inline private
Definition at line 83 of file actiontakehybridattachmenttohands.c.
    {
        if (GetGame().IsMultiplayer())
            return; // multiplayer handled on client side via OnExecuteClient
        else
            OnExecuteImpl(action_data); // single player
    }
References GetGame(), and OnExecuteImpl().