DayzKode: FirearmActionDetachMagazine Class Reference
FirearmActionDetachMagazine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool CanBePerformedFromQuickbar ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
void FirearmActionDetachMagazine ()
override GetInputType ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool InventoryReservation (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStageStart (SequentialActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 147 of file firearmactiondetachmagazine.c.
Constructor & Destructor Documentation
FirearmActionDetachMagazine()
void FirearmActionDetachMagazine::FirearmActionDetachMagazine () inline private
Definition at line 149 of file firearmactiondetachmagazine.c.
    {
    }
Member Function Documentation
ActionCondition()
override bool FirearmActionDetachMagazine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 266 of file firearmactiondetachmagazine.c.
    {
        if (!super.ActionCondition( player, target, item ))
            return false;
        Weapon_Base wpn = Weapon_Base.Cast( item );
        int mi = wpn.GetCurrentMuzzle();
        return wpn && wpn.GetMagazine(mi) == target.GetObject();
    }
ActionConditionContinue()
override bool FirearmActionDetachMagazine::ActionConditionContinue (ActionData action_data) inline private
Definition at line 276 of file firearmactiondetachmagazine.c.
    {
        return true;
    }
CanBePerformedFromQuickbar()
override bool FirearmActionDetachMagazine::CanBePerformedFromQuickbar () inline private
Definition at line 261 of file firearmactiondetachmagazine.c.
    {
        return true;
    }
CreateActionData()
override ActionData FirearmActionDetachMagazine::CreateActionData () inline private
Definition at line 153 of file firearmactiondetachmagazine.c.
    {
        ActionData action_data = new AdvDetachMagActionData;
        return action_data;
    }
CreateConditionComponents()
override void FirearmActionDetachMagazine::CreateConditionComponents () inline private
Definition at line 255 of file firearmactiondetachmagazine.c.
    {
        m_ConditionItem = new CCIDummy;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override FirearmActionDetachMagazine::GetInputType () inline private
Definition at line 250 of file firearmactiondetachmagazine.c.
    {
        return QuickaBarActionInput;
    }
HandleReciveData()
override void FirearmActionDetachMagazine::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 238 of file firearmactiondetachmagazine.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        AdvDetachMagActionReciveData recive_data_dm = AdvDetachMagActionReciveData.Cast(action_recive_data);
        AdvDetachMagActionData action_data_dm = AdvDetachMagActionData.Cast(action_data);
        action_data_dm.m_ilWeapon.Copy(recive_data_dm.m_ilWeapon);
        action_data_dm.m_ilMagazine.Copy(recive_data_dm.m_ilMagazine);
    }
References InventoryLocation::Copy(), AdvDetachMagActionReciveData::m_ilMagazine, and AdvDetachMagActionReciveData::m_ilWeapon.
InventoryReservation()
override bool FirearmActionDetachMagazine::InventoryReservation (ActionData action_data) inline private
Definition at line 160 of file firearmactiondetachmagazine.c.
    {
        Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
        Magazine mag = Magazine.Cast(action_data.m_Target.GetObject());
        InventoryLocation ilWpn = new InventoryLocation();
        InventoryLocation ilMag = new InventoryLocation();
        int ur_index = action_data.m_Player.GetHumanInventory().FindUserReservedLocationIndex(wpn);
        if(ur_index > -1)
            action_data.m_Player.GetHumanInventory().GetUserReservedLocation(ur_index,ilWpn);
        else
        {
            action_data.m_Player.GetInventory().FindFreeLocationFor(wpn, FindInventoryLocationType.ANY_CARGO | FindInventoryLocationType.ATTACHMENT, ilWpn);
                //return false;
        }
        if( !action_data.m_Player.GetInventory().FindFreeLocationFor(mag, FindInventoryLocationType.ANY_CARGO, ilMag) )
            return false;
        if( !super.InventoryReservation( action_data ) )
            return false;
        AdvDetachMagActionData action_data_dm = AdvDetachMagActionData.Cast(action_data);
        if( !action_data.m_Player.GetInventory().AddInventoryReservationEx(wpn,ilWpn,10000) )
            return false;
        if( !action_data.m_Player.GetInventory().AddInventoryReservationEx(mag,ilMag,10000) )
            return false;
        action_data_dm.m_ReservedInventoryLocations.Insert(ilWpn);
        action_data_dm.m_ReservedInventoryLocations.Insert(ilMag);
        action_data_dm.m_ilWeapon = ilWpn;
        action_data_dm.m_ilMagazine = ilMag;
        return true;
    }
References ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
OnEndServer()
override void FirearmActionDetachMagazine::OnEndServer (ActionData action_data) inline private
Definition at line 362 of file firearmactiondetachmagazine.c.
    {
        GetGame().ClearJuncture(action_data.m_Player, EntityAI.Cast(action_data.m_Target.GetObject()));
    }
References CGame::ClearJuncture(), GetGame(), ActionData::m_Player, and ActionData::m_Target.
OnStageStart()
override void FirearmActionDetachMagazine::OnStageStart (SequentialActionData action_data) inline private
Definition at line 281 of file firearmactiondetachmagazine.c.
    {
        if( action_data.m_ReciveEndInput )
        {
            End( action_data );
            return;
        }
        super.OnStageStart(action_data);
        Weapon_Base wpn;
        Magazine mag;
        //InventoryLocation il = new InventoryLocation();
        AdvDetachMagActionData action_data_dm = AdvDetachMagActionData.Cast(action_data);
        switch (action_data.m_Stage)
        {
            case 0:
                action_data.m_Player.GetWeaponManager().DetachMagazine(action_data_dm.m_ilMagazine,this);
                break;
            case 1:
                if ( !action_data_dm.m_ilWeapon.IsValid() )
                {
                    End( action_data );
                    break;
                }
                wpn = Weapon_Base.Cast(action_data.m_MainItem);
                mag = Magazine.Cast(action_data.m_Target.GetObject());
                action_data.m_Player.GetHumanInventory().ClearUserReservedLocation(wpn);
                if ( ( !GetGame().IsDedicatedServer() ) && !mag.GetHierarchyParent() )
                {
                    InventoryMode invMode = InventoryMode.PREDICTIVE;
                    if ( action_data.m_Player.NeedInventoryJunctureFromServer(mag, action_data.m_Player, action_data.m_Player) || action_data.m_Player.NeedInventoryJunctureFromServer(wpn, action_data.m_Player, action_data.m_Player) )
                        invMode = InventoryMode.JUNCTURE;
                    action_data.m_Player.GetInventory().ForceSwapEntities(invMode, mag, wpn, action_data_dm.m_ilWeapon);
                }
                End( action_data );
                break;
            default:
                End( action_data );
                break;
        }
    }
References End(), GetGame(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_ReciveEndInput, SequentialActionData::m_Stage, and ActionData::m_Target.
OnStartServer()
override void FirearmActionDetachMagazine::OnStartServer (ActionData action_data) inline private
Definition at line 356 of file firearmactiondetachmagazine.c.
    {
        AdvDetachMagActionData action_data_dm = AdvDetachMagActionData.Cast(action_data);
        GetGame().AddInventoryJunctureEx(action_data.m_Player, EntityAI.Cast(action_data.m_Target.GetObject()),action_data_dm.m_ilMagazine, true, 10000);
    }
References CGame::AddInventoryJunctureEx(), GetGame(), ActionData::m_Player, and ActionData::m_Target.
OnUpdate()
override void FirearmActionDetachMagazine::OnUpdate (ActionData action_data) inline private
Definition at line 329 of file firearmactiondetachmagazine.c.
    {
        super.OnUpdate( action_data );
        SequentialActionData ad = SequentialActionData.Cast(action_data);
        if(ad)
        {
            switch (ad.m_Stage)
            {
                case 0:
                    Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
                    if ( (!wpn || ad.m_Player.GetItemInHands()!=wpn || !ad.m_Player.GetWeaponManager().IsRunning()) && !ad.m_Player.IsJumpInProgress() )
                    {
                        SetStage(1, ad);
                    }
                    break;
                case 1:
                    //action_data.m_Player.GetHandFs
                    break;
                default:
                    break;
            }
        }
    }
References ActionData::m_MainItem, ActionData::m_Player, SequentialActionData::m_Stage, and SetStage().
ReadFromContext()
override bool FirearmActionDetachMagazine::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 213 of file firearmactiondetachmagazine.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new AdvDetachMagActionReciveData;
        }
        if(!super.ReadFromContext( ctx, action_recive_data ))
            return false;
        AdvDetachMagActionReciveData recive_data_dm;
        recive_data_dm = AdvDetachMagActionReciveData.Cast( action_recive_data );
        recive_data_dm.m_ilWeapon = new InventoryLocation;
        recive_data_dm.m_ilMagazine = new InventoryLocation;
        if(!recive_data_dm.m_ilWeapon.ReadFromContext(ctx))
            return false;
        if(!recive_data_dm.m_ilMagazine.ReadFromContext(ctx))
            return false;
        return true;
    }
References AdvDetachMagActionReciveData::m_ilMagazine, AdvDetachMagActionReciveData::m_ilWeapon, and InventoryLocation::ReadFromContext().
WriteToContext()
override void FirearmActionDetachMagazine::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 202 of file firearmactiondetachmagazine.c.
    {
        super.WriteToContext(ctx, action_data);
        AdvDetachMagActionData action_data_dm;
        AdvDetachMagActionData.CastTo(action_data_dm, action_data);
        action_data_dm.m_ilWeapon.WriteToContext(ctx);
        action_data_dm.m_ilMagazine.WriteToContext(ctx);
    }