DayzKode: WeaponFire Class Reference
WeaponFire Class Reference
Private Member Functions
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
Detailed Description
Definition at line 98 of file weaponfire.c.
Member Function Documentation
OnEntry() [1/3]
override void WeaponFire::OnEntry (WeaponEventBase e) inline private
Definition at line 100 of file weaponfire.c.
    {
        m_dtAccumulator = 0;
        if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponFire bang!"); }
        //m_weapon.Fire();
        int mi = m_weapon.GetCurrentMuzzle();
        if (TryFireWeapon(m_weapon, mi))
        {
            DayZPlayerImplement p;
            if (Class.CastTo(p, e.m_player))
                p.GetAimingModel().SetRecoil(m_weapon);
            m_weapon.EjectCasing(mi);
            m_weapon.OnFire(mi);
        }
        super.OnEntry(e);
    }
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dtAccumulator, WeaponEventBase::m_player, m_weapon, TryFireWeapon(), and wpnPrint().
Referenced by BotStateBase::OnEntry().
OnEntry() [2/3]
override void WeaponFire::OnEntry (WeaponEventBase e) inline private
Definition at line 316 of file weaponfire.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (!m_weapon.IsJammed())
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " ejected fired out casing"); }
                int mi = m_weapon.GetCurrentMuzzle();
                m_weapon.EjectCasing(mi);
                m_weapon.EffectBulletHide(mi);
                m_weapon.SelectionBulletHide();
                pushToChamberFromAttachedMagazine(m_weapon, mi);
            }
        }
    }
References LogManager::IsWeaponLogEnable(), m_weapon, pushToChamberFromAttachedMagazine(), and wpnDebugPrint().
OnEntry() [3/3]
override void WeaponFire::OnEntry (WeaponEventBase e) inline private
Definition at line 337 of file weaponfire.c.
    {
        super.OnEntry(e);
        if (!m_weapon.IsJammed())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " ejected fired out casing"); }
            int mi = m_weapon.GetCurrentMuzzle();
            m_weapon.EjectCasing(mi);
            m_weapon.EffectBulletHide(mi);
            m_weapon.SelectionBulletHide();
            pushToChamberFromInnerMagazine(m_weapon, mi);
        }
    }
References LogManager::IsWeaponLogEnable(), m_weapon, pushToChamberFromInnerMagazine(), and wpnDebugPrint().