DayzKode: ActionUnfoldEntity Class Reference
ActionUnfoldEntity Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionUnfoldEntity ()
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 2 of file actionunfoldentity.c.
Constructor & Destructor Documentation
ActionUnfoldEntity()
void ActionUnfoldEntity::ActionUnfoldEntity () inline private
Definition at line 4 of file actionunfoldentity.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
    }
References AnimatedActionBase::m_CommandUID.
Member Function Documentation
ActionCondition()
override bool ActionUnfoldEntity::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 17 of file actionunfoldentity.c.
    {
        if (item)
            return true;
        return false;
    }
ActionConditionContinue()
override bool ActionUnfoldEntity::ActionConditionContinue (ActionData action_data) inline private
Definition at line 24 of file actionunfoldentity.c.
{ return true; }
CreateConditionComponents()
override void ActionUnfoldEntity::CreateConditionComponents () inline private
Definition at line 9 of file actionunfoldentity.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionUnfoldEntity::HasTarget () inline private
Definition at line 15 of file actionunfoldentity.c.
{ return false; }
OnExecuteClient()
override void ActionUnfoldEntity::OnExecuteClient (ActionData action_data) inline private
Definition at line 26 of file actionunfoldentity.c.
    {
        ClearInventoryReservationEx(action_data);
    }
References ClearInventoryReservationEx().
OnExecuteServer()
override void ActionUnfoldEntity::OnExecuteServer (ActionData action_data) inline private
Definition at line 31 of file actionunfoldentity.c.
    {
        if ( !GetGame().IsMultiplayer() )
            ClearInventoryReservationEx(action_data);
        ItemBase old_item = action_data.m_MainItem;
        if (old_item.ConfigIsExisting("ChangeIntoOnDetach"))
        {
            string str = old_item.ChangeIntoOnDetach();
            if (str  != "")
            {
                UnfoldEntityLambda lambda = new UnfoldEntityLambda(action_data.m_MainItem, str, action_data.m_Player);
                lambda.SetTransferParams(true, true, true, false, 1);
                action_data.m_Player.ServerReplaceItemInHandsWithNew(lambda);
            }
        }
    }
References ClearInventoryReservationEx(), GetGame(), ActionData::m_MainItem, and ActionData::m_Player.