DayzKode: BuildingSuper Class Reference
BuildingSuper Class Reference
Private Member Functions
protected void BonfireHeating ()
DEPRECATED.
void BuildingWithFireplace ()
override void EEDelete (EntityAI parent)
override void EEInit ()
override float GetLiquidThroughputCoef ()
override float GetLiquidThroughputCoef ()
override bool IsBuilding ()
override bool IsBuilding ()
override bool IsFuelStation ()
override bool IsWell ()
void Land_Misc_Greenhouse ()
override void SetActions ()
Private Attributes
const float CONST_FIRE_TEMP = 1000
maximum value for temperature that will be transfered to player (environment)
protected ref Timer m_BonfireHeatingTimer
protected BonfireLight m_Light
protected Particle m_ParticleFire
protected Particle m_ParticleSmoke
protected EffectSound m_SoundFireLoop
protected ref UniversalTemperatureSourceLambdaConstant m_UTSLBonfire
protected ref UniversalTemperatureSource m_UTSource
DEPRECATED.
protected ref UniversalTemperatureSourceSettings m_UTSSettings
const float PARAM_FULL_HEAT_RADIUS = 5
const float PARAM_HEAT_RADIUS = 15
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
const float TIMER_HEATING_UPDATE_INTERVAL = 2
Detailed Description
Definition at line 1 of file buildingwithfireplace.c.
Member Function Documentation
BonfireHeating()
protected void BuildingSuper::BonfireHeating () inline private
DEPRECATED.
Definition at line 111 of file bonfire.c.
{};
BuildingWithFireplace()
void BuildingSuper::BuildingWithFireplace () inline private
Definition at line 3 of file buildingwithfireplace.c.
    {
    }
EEDelete()
override void BuildingSuper::EEDelete (EntityAI parent) inline private
Definition at line 73 of file bonfire.c.
    {
        super.EEDelete(parent);
        #ifndef SERVER
        // outside of bubble - do effects cleanup (light, particles, sound)
        // light
        if (m_Light)
        {
            m_Light.FadeOut();
        }
        // particles
        if (m_ParticleSmoke)
        {
            m_ParticleSmoke.Stop();
        }
        if (m_ParticleFire)
        {
            m_ParticleFire.Stop();
        }
        // sounds
        if (m_SoundFireLoop)
        {
            m_SoundFireLoop.SoundStop();
        }
        #endif
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetActive(false);
        }
    }
References GetGame(), m_Light, m_ParticleSmoke, m_SoundFireLoop, m_UTSource, EffectSound::SoundStop(), and Particle::Stop().
EEInit()
override void BuildingSuper::EEInit () inline private
Definition at line 22 of file bonfire.c.
    {
        super.EEInit();
        #ifndef SERVER
        // object creation - create effects (light, particles, sound)
        // light
        if (!m_Light)
        {
            m_Light = BonfireLight.Cast(ScriptedLightBase.CreateLight(BonfireLight, Vector(0,0,0), 1));
            m_Light.AttachOnMemoryPoint(this, m_Light.m_MemoryPoint);
            m_Light.FadeBrightnessTo(m_Light.m_FireBrightness, 0);
            m_Light.FadeRadiusTo(m_Light.m_FireRadius, 0);
        }
        // particles
        if (!m_ParticleSmoke)
        {
            m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(ParticleList.BONFIRE_SMOKE, this, GetMemoryPointPos("bonfire_smoke"), Vector(0,0,0), true);
        }
        if (!m_ParticleFire)
        {
            m_ParticleFire = ParticleManager.GetInstance().PlayOnObject(ParticleList.BONFIRE_FIRE, this, GetMemoryPointPos("bonfire_fire"), Vector(0,0,0), true);
        }
        // sounds
        if (!m_SoundFireLoop)
        {
            PlaySoundSetLoop(m_SoundFireLoop, "HeavyFire_SoundSet", 1.0, 2.0);
        }
        #endif
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_UpdateInterval  = TIMER_HEATING_UPDATE_INTERVAL;
            m_UTSSettings.m_Updateable      = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = CONST_FIRE_TEMP;
            m_UTSSettings.m_TemperatureCap  = PARAM_MAX_TRANSFERED_TEMPERATURE;
            m_UTSSettings.m_RangeFull       = PARAM_FULL_HEAT_RADIUS;
            m_UTSSettings.m_RangeMax        = PARAM_HEAT_RADIUS;
            m_UTSLBonfire                   = new UniversalTemperatureSourceLambdaConstant();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLBonfire);
            m_UTSource.SetActive(true);
        }
    }
References ParticleList::BONFIRE_FIRE, ParticleList::BONFIRE_SMOKE, CONST_FIRE_TEMP, GetGame(), GetMemoryPointPos(), PointLightBase::m_FireBrightness, PointLightBase::m_FireRadius, m_Light, PointLightBase::m_MemoryPoint, m_ParticleSmoke, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, m_SoundFireLoop, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, ParticleManager(), PlaySoundSetLoop(), TIMER_HEATING_UPDATE_INTERVAL, and Vector().
GetLiquidThroughputCoef() [1/2]
override float BuildingSuper::GetLiquidThroughputCoef () inline private
Definition at line 13 of file fuelstation.c.
    {
        return LIQUID_THROUGHPUT_FUELSTATION;
    }
References LIQUID_THROUGHPUT_FUELSTATION.
GetLiquidThroughputCoef() [2/2]
override float BuildingSuper::GetLiquidThroughputCoef () inline private
Definition at line 13 of file well.c.
    {
        return LIQUID_THROUGHPUT_WELL;
    }
References LIQUID_THROUGHPUT_WELL.
IsBuilding() [1/2]
override bool BuildingSuper::IsBuilding () inline private
Definition at line 3 of file fuelstation.c.
    {
        return false;
    }
IsBuilding() [2/2]
override bool BuildingSuper::IsBuilding () inline private
Definition at line 3 of file well.c.
    {
        return false;
    }
IsFuelStation()
override bool BuildingSuper::IsFuelStation () inline private
Definition at line 8 of file fuelstation.c.
    {
        return true;
    }
IsWell()
override bool BuildingSuper::IsWell () inline private
Definition at line 8 of file well.c.
    {
        return true;
    }
Land_Misc_Greenhouse()
void BuildingSuper::Land_Misc_Greenhouse () inline private
Definition at line 3 of file land_misc_greenhouse.c.
    {
    }
SetActions()
override void BuildingSuper::SetActions () inline private
Definition at line 18 of file well.c.
    {
        super.SetActions();
        AddAction(ActionWashHandsWellOne);
        AddAction(ActionDrinkWellContinuous);
    }
References AddAction().
Member Data Documentation
CONST_FIRE_TEMP
const float BuildingSuper::CONST_FIRE_TEMP = 1000 private
maximum value for temperature that will be transfered to player (environment)
Definition at line 7 of file bonfire.c.
Referenced by EEInit().
m_BonfireHeatingTimer
protected ref Timer BuildingSuper::m_BonfireHeatingTimer private
Definition at line 15 of file bonfire.c.
m_Light
protected BonfireLight BuildingSuper::m_Light private
Definition at line 9 of file bonfire.c.
m_ParticleFire
protected Particle BuildingSuper::m_ParticleFire private
Definition at line 10 of file bonfire.c.
m_ParticleSmoke
protected Particle BuildingSuper::m_ParticleSmoke private
Definition at line 11 of file bonfire.c.
m_SoundFireLoop
protected EffectSound BuildingSuper::m_SoundFireLoop private
Definition at line 12 of file bonfire.c.
m_UTSLBonfire
protected ref UniversalTemperatureSourceLambdaConstant BuildingSuper::m_UTSLBonfire private
Definition at line 20 of file bonfire.c.
m_UTSource
protected ref UniversalTemperatureSource BuildingSuper::m_UTSource private
DEPRECATED.
Definition at line 18 of file bonfire.c.
m_UTSSettings
protected ref UniversalTemperatureSourceSettings BuildingSuper::m_UTSSettings private
Definition at line 19 of file bonfire.c.
PARAM_FULL_HEAT_RADIUS
const float BuildingSuper::PARAM_FULL_HEAT_RADIUS = 5 private
Definition at line 5 of file bonfire.c.
Referenced by EEInit().
PARAM_HEAT_RADIUS
const float BuildingSuper::PARAM_HEAT_RADIUS = 15 private
Definition at line 4 of file bonfire.c.
Referenced by EEInit().
PARAM_MAX_TRANSFERED_TEMPERATURE
const float BuildingSuper::PARAM_MAX_TRANSFERED_TEMPERATURE = 25 private
Definition at line 6 of file bonfire.c.
Referenced by EEInit().
TIMER_HEATING_UPDATE_INTERVAL
const float BuildingSuper::TIMER_HEATING_UPDATE_INTERVAL = 2 private
Definition at line 3 of file bonfire.c.
Referenced by EEInit().