DayzKode: WBModuleDef Class Reference
WBModuleDef Class Reference
Private Member Functions
proto native external bool Close ()
proto external bool GetCmdLine (string name, out string value)
proto native external BaseContainer GetContainer (int index=0)
proto native external int GetNumContainers ()
proto native external bool Save ()
proto native external bool SetOpenedResource (string filename)
Detailed Description
Definition at line 19 of file workbenchapi.c.
Member Function Documentation
Close()
proto native external bool WBModuleDef::Close () private
Referenced by ResavePlugin::RunCommandline().
GetCmdLine()
proto external bool WBModuleDef::GetCmdLine (string name, out string value) private
Referenced by ResavePlugin::RunCommandline().
GetContainer()
proto native external BaseContainer WBModuleDef::GetContainer (int index = 0) private
Referenced by CheckLocalisationPlugin::CheckTextIDs().
GetNumContainers()
proto native external int WBModuleDef::GetNumContainers () private
Save()
proto native external bool WBModuleDef::Save () private
Referenced by ResavePlugin::Resave().
SetOpenedResource()
proto native external bool WBModuleDef::SetOpenedResource (string filename) private
Referenced by CheckLocalisationPlugin::CheckTextIDs(), and ResavePlugin::Resave().