DayzKode: Tabber Class Reference
Tabber Class Reference
Private Member Functions
override bool OnClick (Widget w, int x, int y, int button)
void OnWidgetScriptInit (Widget w)
protected void SelectTab (int index)
Private Attributes
Widget ButtonsPanel
Widget ContentPanel
reference int SelectedTab
Detailed Description
Definition at line 2 of file tabber.c.
Member Function Documentation
OnClick()
override bool Tabber::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 16 of file tabber.c.
    {
        if (w && w.GetParent() == ButtonsPanel)
        {
            SelectedTab = 0;
            Widget iw = ButtonsPanel.GetChildren();
            while(iw)
            {
                if (iw == w) break;
                SelectedTab++;
                iw = iw.GetSibling();
            }
            SelectTab(SelectedTab);
        }
        return false;
    }
References ButtonsPanel, SelectedTab, and SelectTab().
OnWidgetScriptInit()
void Tabber::OnWidgetScriptInit (Widget w) inline private
Definition at line 9 of file tabber.c.
    {
        w.SetHandler(this);
        SelectTab(SelectedTab);
    }
References SelectedTab, and SelectTab().
SelectTab()
protected void Tabber::SelectTab (int index) inline private
Definition at line 36 of file tabber.c.
    {
        Print(index);
        int n = 0;
        Widget w = ContentPanel.GetChildren();
        while(w)
        {
            if (n == index)
            {
                w.Show(true);
            }
            else
            {
                w.Show(false);
            }
            n++;
            w = w.GetSibling();
        }
    }
References ContentPanel, and Print().
Referenced by OnClick(), and OnWidgetScriptInit().
Member Data Documentation
ButtonsPanel
Widget Tabber::ButtonsPanel private
Definition at line 4 of file tabber.c.
Referenced by OnClick().
ContentPanel
Widget Tabber::ContentPanel private
Definition at line 5 of file tabber.c.
Referenced by SelectTab().
SelectedTab
reference int Tabber::SelectedTab private
Definition at line 6 of file tabber.c.
Referenced by OnClick(), and OnWidgetScriptInit().