DayzKode: ChatLine Class Reference
ChatLine Class Reference
Private Member Functions
void ChatLine (Widget root_widget)
void Clear ()
protected int ColorNameToColor (string pColorName)
void Set (ChatMessageEventParams params)
protected void SetColorByParam (string pParamValue, int pFallback)
private void SetColour (int colour)
void ~ChatLine ()
Private Attributes
private const string ADMIN_PREFIX = "(" + "#STR_MP_MASTER" + ") "
private const int ADMIN_TEXT_COLOUR = ARGB(255, 255, 255, 0)
private const int DEFAULT_COLOUR = ARGB(255, 255, 255, 255)
const float FADE_IN_DURATION = 0.5
const float FADE_OUT_DURATION = 3
const float FADE_TIMEOUT = 30
private const string GAME_PREFIX = "(" + "#layout_chat_game" + ") "
private const int GAME_TEXT_COLOUR = ARGB(255, 255, 0, 0)
private ref WidgetFadeTimer m_FadeTimer
TextWidget m_NameWidget
Widget m_RootWidget
TextWidget m_TextWidget
private ref Timer m_TimeoutTimer
private const string RADIO_PREFIX = "(" + "#str_radio" + ") "
Detailed Description
Definition at line 1 of file chatline.c.
Constructor & Destructor Documentation
ChatLine()
void ChatLine::ChatLine (Widget root_widget) inline private
Definition at line 23 of file chatline.c.
    {
        m_RootWidget    = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_chat_item.layout", root_widget);
        m_NameWidget    = TextWidget.Cast( m_RootWidget.FindAnyWidget( "ChatItemSenderWidget" ) );
        m_TextWidget    = TextWidget.Cast( m_RootWidget.FindAnyWidget( "ChatItemTextWidget" ) );
        m_FadeTimer     = new WidgetFadeTimer;
        m_TimeoutTimer  = new Timer(CALL_CATEGORY_GUI);
    }
References CALL_CATEGORY_GUI, WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_FadeTimer, m_NameWidget, m_RootWidget, m_TextWidget, and m_TimeoutTimer.
~ChatLine()
void ChatLine::~ChatLine () inline private
Definition at line 34 of file chatline.c.
    {
        delete m_TextWidget;
    }
References m_TextWidget.
Member Function Documentation
Clear()
void ChatLine::Clear () inline private
Definition at line 130 of file chatline.c.
    {
        m_RootWidget.Show( false );
        m_TimeoutTimer.Stop();
        m_FadeTimer.Stop();
    }
References m_FadeTimer, m_RootWidget, and m_TimeoutTimer.
ColorNameToColor()
protected int ChatLine::ColorNameToColor (string pColorName) inline private
Definition at line 137 of file chatline.c.
    {
        int color = 0xFFFFFFFF;
        switch (pColorName)
        {
        case "colorStatusChannel":
            color = COLOR_BLUE;
        break;
        case "colorAction":
            color = COLOR_YELLOW;
        break;
        case "colorFriendly":
            color = COLOR_GREEN;
        break;
        case "colorImportant":
            color = COLOR_RED;
        break;
        }
        return color;
    }
References COLOR_BLUE, COLOR_GREEN, COLOR_RED, and COLOR_YELLOW.
Referenced by SetColorByParam().
Set()
void ChatLine::Set (ChatMessageEventParams params) inline private
Definition at line 39 of file chatline.c.
    {
        int channel;
        m_NameWidget.SetText("");
        m_TextWidget.SetText("");
        SetColour(DEFAULT_COLOUR);
        m_RootWidget.Show(true);
        channel = params.param1; // 0 = Survior   1 = Game/System   2 = Admin
        /*
        if (params.param2 != "")
        {
            m_NameWidget.SetText( params.param2 + " : ");
        }
        if( channel & CCSystem )
        {
            if(params.param2 != "")
            {
                m_NameWidget.SetText(GAME_PREFIX + ": " );
            }
            SetColour(GAME_TEXT_COLOUR);
        }
        else if( channel & CCAdmin )
        {
            m_NameWidget.SetText(ADMIN_PREFIX + ": ");
            SetColour(ADMIN_TEXT_COLOUR);
        }
        else if( channel & CCTransmitter )
        {
            m_NameWidget.SetText(RADIO_PREFIX + params.param2 + " : ");
        }
        */
        if ( channel & CCSystem )
        {
            // Game
            if (params.param2 != "")
            {
                m_NameWidget.SetText(GAME_PREFIX + ": " );
            }
            SetColorByParam(params.param4, GAME_TEXT_COLOUR);
        }
        else if ( channel & CCAdmin )
        {
            // Admin
            m_NameWidget.SetText(ADMIN_PREFIX + ": ");
            SetColorByParam(params.param4, ADMIN_TEXT_COLOUR);
        }
        else if ( channel & CCTransmitter )
        {
            // Radio - Trasnmitter
            m_NameWidget.SetText(RADIO_PREFIX + params.param2 + " : ");
        }
        else if ( channel == 0 || channel & CCDirect )
        {
            // Player
            if (params.param2 != "")
            {
                m_NameWidget.SetText(params.param2 + " : ");
            }
        }
        m_TextWidget.SetText(params.param3);
        m_FadeTimer.FadeIn(m_RootWidget, FADE_IN_DURATION);
        m_TimeoutTimer.Run(FADE_TIMEOUT, m_FadeTimer, "FadeOut", new Param2<Widget, float>(m_RootWidget, FADE_OUT_DURATION));
    }
References ADMIN_PREFIX, ADMIN_TEXT_COLOUR, DEFAULT_COLOUR, FADE_IN_DURATION, FADE_OUT_DURATION, FADE_TIMEOUT, GAME_PREFIX, GAME_TEXT_COLOUR, m_FadeTimer, m_NameWidget, m_RootWidget, m_TextWidget, m_TimeoutTimer, RADIO_PREFIX, SetColorByParam(), and SetColour().
Referenced by Chat::AddInternal().
SetColorByParam()
protected void ChatLine::SetColorByParam (string pParamValue, int pFallback) inline private
Definition at line 119 of file chatline.c.
    {
        if (pParamValue != "")
        {
            SetColour(ColorNameToColor(pParamValue));
            return;
        }
        SetColour(pFallback);
    }
References ColorNameToColor(), and SetColour().
Referenced by Set().
SetColour()
private void ChatLine::SetColour (int colour) inline private
Definition at line 113 of file chatline.c.
    {
        m_NameWidget.SetColor(colour);
        m_TextWidget.SetColor(colour);
    }
References m_NameWidget, and m_TextWidget.
Referenced by Set(), and SetColorByParam().
Member Data Documentation
ADMIN_PREFIX
private const string ChatLine::ADMIN_PREFIX = "(" + "#STR_MP_MASTER" + ") " private
Definition at line 10 of file chatline.c.
Referenced by Set().
ADMIN_TEXT_COLOUR
private const int ChatLine::ADMIN_TEXT_COLOUR = ARGB(255, 255, 255, 0) private
Definition at line 13 of file chatline.c.
Referenced by Set().
DEFAULT_COLOUR
private const int ChatLine::DEFAULT_COLOUR = ARGB(255, 255, 255, 255) private
Definition at line 11 of file chatline.c.
Referenced by Set().
FADE_IN_DURATION
const float ChatLine::FADE_IN_DURATION = 0.5 private
Definition at line 6 of file chatline.c.
Referenced by Set().
FADE_OUT_DURATION
const float ChatLine::FADE_OUT_DURATION = 3 private
Definition at line 5 of file chatline.c.
Referenced by Set().
FADE_TIMEOUT
const float ChatLine::FADE_TIMEOUT = 30 private
Definition at line 4 of file chatline.c.
Referenced by Set().
GAME_PREFIX
private const string ChatLine::GAME_PREFIX = "(" + "#layout_chat_game" + ") " private
Definition at line 9 of file chatline.c.
Referenced by Set().
GAME_TEXT_COLOUR
private const int ChatLine::GAME_TEXT_COLOUR = ARGB(255, 255, 0, 0) private
Definition at line 12 of file chatline.c.
Referenced by Set().
m_FadeTimer
private ref WidgetFadeTimer ChatLine::m_FadeTimer private
Definition at line 20 of file chatline.c.
Referenced by ChatLine(), Clear(), and Set().
m_NameWidget
TextWidget ChatLine::m_NameWidget private
Definition at line 17 of file chatline.c.
Referenced by ChatLine(), Set(), and SetColour().
m_RootWidget
Widget ChatLine::m_RootWidget private
Definition at line 16 of file chatline.c.
Referenced by Chat::AddInternal(), ChatLine(), Clear(), and Set().
m_TextWidget
TextWidget ChatLine::m_TextWidget private
Definition at line 18 of file chatline.c.
Referenced by ChatLine(), Set(), SetColour(), and ~ChatLine().
m_TimeoutTimer
private ref Timer ChatLine::m_TimeoutTimer private
Definition at line 21 of file chatline.c.
Referenced by ChatLine(), Clear(), and Set().
RADIO_PREFIX
private const string ChatLine::RADIO_PREFIX = "(" + "#str_radio" + ") " private
Definition at line 8 of file chatline.c.
Referenced by Set().