DayzKode: ActionDefibrilateBase Class Reference
ActionDefibrilateBase Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
bool CanDefibrillate (Defibrillator defib)
void DefibrillateClient (PlayerBase player, Defibrillator defib)
void DefibrillateServer (PlayerBase player, Defibrillator defib)
Detailed Description
Definition at line 1 of file actiondefibrilatebase.c.
Member Function Documentation
ActionCondition()
override bool ActionDefibrilateBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 3 of file actiondefibrilatebase.c.
    {
        Defibrillator defib;
        Class.CastTo(defib, item);
        return CanDefibrillate(defib);
    }
References CanDefibrillate(), and Class::CastTo().
CanDefibrillate()
bool ActionDefibrilateBase::CanDefibrillate (Defibrillator defib) inline private
Definition at line 11 of file actiondefibrilatebase.c.
    {
        if ( defib.IsCharged() )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
Referenced by ActionCondition().
DefibrillateClient()
void ActionDefibrilateBase::DefibrillateClient (PlayerBase player, Defibrillator defib) inline private
Definition at line 23 of file actiondefibrilatebase.c.
    {
        defib.DischargeClient(player);
    }
Referenced by ActionDefibrilateSelf::OnFinishProgressClient(), and ActionDefibrilateTarget::OnFinishProgressClient().
DefibrillateServer()
void ActionDefibrilateBase::DefibrillateServer (PlayerBase player, Defibrillator defib) inline private
Definition at line 28 of file actiondefibrilatebase.c.
    {
        if ( defib.IsCharged() )
        {
            defib.DischargeServer(player);
            float regain_energy = player.GetSoftSkillsManager().SubtractSpecialtyBonus( defib.GetEnergyNeededToCharge(), this.GetSpecialtyWeight() );
            regain_energy = defib.GetEnergyNeededToCharge() - regain_energy;
            ItemBase battery;
            if (Class.CastTo(battery, defib.GetCompEM().GetEnergySource()))
            {
                battery.GetCompEM().AddEnergy( regain_energy );
            }
            else
            {
                DPrint("ERROR! Defibrillator has no battery! Defibrillator softskill bonus can't be applied!");
            }
        }
        player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), DPrint(), and m_SpecialtyWeight.
Referenced by ActionDefibrilateSelf::OnFinishProgressServer(), and ActionDefibrilateTarget::OnFinishProgressServer().