DayzKode: ActionDismantlePart Class Reference
ActionDismantlePart Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionDismantlePart ()
override bool CanBeUsedLeaning ()
override void CreateConditionComponents ()
protected bool DismantleCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
override string GetAdminLogMessage (ActionData action_data)
override string GetText ()
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
protected void SetBuildingAnimation (ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Detailed Description
Definition at line 26 of file actiondismantlepart.c.
Constructor & Destructor Documentation
ActionDismantlePart()
void ActionDismantlePart::ActionDismantlePart () inline private
Definition at line 28 of file actiondismantlepart.c.
    {
        m_CallbackClass = ActionDismantlePartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#dismantle";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionDismantlePart::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 73 of file actiondismantlepart.c.
    {
        if ( player.IsPlacingLocal() )
            return false;
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        return DismantleCondition( player, target, item, true ) && player.m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE;
    }
References DismantleCondition().
ActionConditionContinue()
override bool ActionDismantlePart::ActionConditionContinue (ActionData action_data) inline private
Definition at line 85 of file actiondismantlepart.c.
    {
        return DismantleCondition( action_data.m_Player, action_data.m_Target, action_data.m_MainItem , false ) && action_data.m_Player.m_MovementState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_PRONE;
    }
References DismantleCondition(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool ActionDismantlePart::CanBeUsedLeaning () inline private
Definition at line 68 of file actiondismantlepart.c.
    {
        return false;
    }
CreateConditionComponents()
override void ActionDismantlePart::CreateConditionComponents () inline private
Definition at line 39 of file actiondismantlepart.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;//CCTNonRuined( UAMaxDistances.BASEBUILDING );
    }
References m_ConditionItem, and m_ConditionTarget.
DismantleCondition()
protected bool ActionDismantlePart::DismantleCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
Definition at line 141 of file actiondismantlepart.c.
    {
        if ( player && !player.IsPlacingLocal() && !player.IsPlacingServer() )
        {
            Object target_object = target.GetObject();
            EntityAI target_entity;
            if ( target_object && target_object.CanUseConstruction() )
            {
                //invalid if is gate and is locked
                if ( Class.CastTo(target_entity,target_object) && (target_entity.FindAttachmentBySlotName("Att_CombinationLock") || target_entity.FindAttachmentBySlotName("Material_FPole_Flag")) )
                {
                    return false;
                }
                string part_name = target_object.GetActionComponentName( target.GetComponentIndex() );
                BaseBuildingBase base_building = BaseBuildingBase.Cast( target_object );
                Construction construction = base_building.GetConstruction();
                ConstructionPart construction_part = construction.GetConstructionPartToDismantle( part_name, item );
                if ( construction_part )
                {
                    /*Print("DismantleCondition");
                    Print(part_name);
                    Print("construction_part.GetPartName: " + construction_part.GetPartName());
                    Print("construction_part.GetMainPartName: " + construction_part.GetMainPartName());
                    Print("-----");*/
                    //invalid on gate if the gate is opened
                    if ( construction_part.IsGate() && base_building.IsOpened() )
                        return false;
                    //camera and position checks
                    bool checked = false;
                    if ( construction_part.IsBase() )
                        checked = true;
                    if ( !checked && base_building.IsPlayerInside( player, part_name ) && !player.GetInputController().CameraIsFreeLook() )
                    {
                        //Camera check (client-only)
                        if ( camera_check )
{
                            if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
{
                                if ( base_building.IsFacingCamera( part_name ) )
{
                                    return false;
                                }
                            }
                        }
                        checked = true;
                    }
                    if ( checked )
                    {
                        ConstructionActionData construction_action_data = player.GetConstructionActionData();
                        construction_action_data.SetTargetPart( construction_part );
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Class::CastTo(), Construction(), GetGame(), ConstructionPart::IsBase(), BaseBuildingBase::IsFacingCamera(), ConstructionPart::IsGate(), BaseBuildingBase::IsOpened(), BaseBuildingBase::IsPlayerInside(), and ConstructionActionData::SetTargetPart().
Referenced by ActionCondition(), and ActionConditionContinue().
GetAdminLogMessage()
override string ActionDismantlePart::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 210 of file actiondismantlepart.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        ConstructionPart construction_part = construction_action_data.GetTargetPart();
        string message = string.Format("Dismantled %1 from %2 with %3", construction_part.GetName(), action_data.m_Target.GetObject().GetDisplayName(), action_data.m_MainItem.GetDisplayName() );
        return message;
    }
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
GetText()
override string ActionDismantlePart::GetText () inline private
Definition at line 51 of file actiondismantlepart.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player )
        {
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            ConstructionPart constrution_part = construction_action_data.GetTargetPart();
            if ( constrution_part )
            {
                return "#dismantle" + " " + constrution_part.GetName();
            }
        }
        return "";
    }
References GetGame(), ConstructionPart::GetName(), GetPlayer(), and ConstructionActionData::GetTargetPart().
OnActionInfoUpdate()
override void ActionDismantlePart::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 45 of file actiondismantlepart.c.
    {
        ConstructionActionData construction_action_data = player.GetConstructionActionData();
        m_Text = "#dismantle " + construction_action_data.GetTargetPart().GetName();
    }
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void ActionDismantlePart::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 90 of file actiondismantlepart.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        ConstructionPart construction_part = construction_action_data.GetTargetPart();
        if ( construction.CanDismantlePart( construction_part.GetPartName(), action_data.m_MainItem ) )
        {
            //build
            construction.DismantlePartServer( action_data.m_Player, construction_part.GetPartName(), AT_DISMANTLE_PART );
            //add damage to tool
            action_data.m_MainItem.DecreaseHealth( UADamageApplied.DISMANTLE, false );
        }
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References AT_DISMANTLE_PART, Construction(), UADamageApplied::DISMANTLE, ConstructionPart::GetPartName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
SetBuildingAnimation()
protected void ActionDismantlePart::SetBuildingAnimation (ItemBase item) inline private
Definition at line 122 of file actiondismantlepart.c.
    {
        switch ( item.Type() )
        {
            case Pickaxe:
            case Shovel:
            case FarmingHoe:
            case FieldShovel:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIG;
                break;
            case Pliers:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
                break;
            default:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
                break;
        }
    }
References AnimatedActionBase::m_CommandUID.
Referenced by SetupAction().
SetupAction()
override bool ActionDismantlePart::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 110 of file actiondismantlepart.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data ) )
        {
            SetBuildingAnimation( item );
            return true;
        }
        return false;
    }
References SetBuildingAnimation().