DayzKode: CCIBase Class Reference
CCIBase Class Reference
Private Member Functions
bool Can (PlayerBase player, ItemBase item)
override bool Can (PlayerBase player, ItemBase item)
bool CanContinue (PlayerBase player, ItemBase item)
Detailed Description
Definition at line 1 of file ccibase.c.
Member Function Documentation
Can() [1/2]
bool CCIBase::Can (PlayerBase player, ItemBase item) inline private
Definition at line 3 of file ccibase.c.
    {
        return true;
    }
Referenced by Can(), and CanContinue().
Can() [2/2]
override bool CCIBase::Can (PlayerBase player, ItemBase item) inline private
Definition at line 3 of file ccinotruinedanddry.c.
    {
        return ( item && !item.IsDamageDestroyed() && item.GetWet() <= 0 ) ;
    }
CanContinue()
bool CCIBase::CanContinue (PlayerBase player, ItemBase item) inline private
Definition at line 8 of file ccibase.c.
    {
        return ( Can(player,item) && item && item == player.GetItemInHands() );
    }
References Can().
Referenced by CanContinue().