DayzKode: ActionDrinkPondContinuous Class Reference
ActionDrinkPondContinuous Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDrinkPondContinuous ()
override void CreateConditionComponents ()
override GetInputType ()
override bool IsDrink ()
override void OnEnd (ActionData action_data)
override void OnEndAnimationLoopServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStart (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Private Attributes
private const float WATER_DRANK_PER_SEC = 35
Detailed Description
Definition at line 9 of file actiondrinkpondcontinuous.c.
Constructor & Destructor Documentation
ActionDrinkPondContinuous()
void ActionDrinkPondContinuous::ActionDrinkPondContinuous () inline private
Definition at line 13 of file actiondrinkpondcontinuous.c.
    {
        m_CallbackClass = ActionDrinkPondContinuousCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DRINKPOND;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#drink";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionDrinkPondContinuous::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 38 of file actiondrinkpondcontinuous.c.
    {
        // Other conditions are in CCTWaterSurface
        // Note: using SurfaceIsPond makes you unable to drink under bridges
        //return true /*g_Game.SurfaceIsPond(pos_cursor[0], pos_cursor[2])*/;
        if ( item && item.IsHeavyBehaviour() )
            return false;
        return player.CanEatAndDrink();
    }
CreateConditionComponents()
override void ActionDrinkPondContinuous::CreateConditionComponents () inline private
Definition at line 32 of file actiondrinkpondcontinuous.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTWaterSurface(UAMaxDistances.DEFAULT, UAWaterType.FRESH);
    }
References UAMaxDistances::DEFAULT, UAWaterType::FRESH, m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionDrinkPondContinuous::GetInputType () inline private
Definition at line 27 of file actiondrinkpondcontinuous.c.
    {
        return ContinuousInteractActionInput;
    }
IsDrink()
override bool ActionDrinkPondContinuous::IsDrink () inline private
Definition at line 22 of file actiondrinkpondcontinuous.c.
    {
        return true;
    }
OnEnd()
override void ActionDrinkPondContinuous::OnEnd (ActionData action_data) inline private
Definition at line 56 of file actiondrinkpondcontinuous.c.
    {
        action_data.m_Player.TryHideItemInHands(false);
    }
References ActionData::m_Player.
OnEndAnimationLoopServer()
override void ActionDrinkPondContinuous::OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 69 of file actiondrinkpondcontinuous.c.
    {
        //Print("OnEndAnimationLoopServer");
        if ( action_data.m_Player.HasBloodyHands() && !action_data.m_Player.GetInventory().FindAttachment( InventorySlots.GLOVES ) )
        {
            action_data.m_Player.SetBloodyHandsPenalty();
        }
    }
References ActionData::m_Player.
OnFinishProgressServer()
override void ActionDrinkPondContinuous::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 61 of file actiondrinkpondcontinuous.c.
    {
        //Print("OnFinishProgressServer");
        Param1<float> nacdata = Param1<float>.Cast( action_data.m_ActionComponent.GetACData() );
        float amount = UAQuantityConsumed.DRINK;
        action_data.m_Player.Consume(NULL, amount, EConsumeType.ENVIRO_POND);
    }
References UAQuantityConsumed::DRINK, CABase::GetACData(), ActionData::m_ActionComponent, and ActionData::m_Player.
OnStart()
override void ActionDrinkPondContinuous::OnStart (ActionData action_data) inline private
Definition at line 49 of file actiondrinkpondcontinuous.c.
    {
        super.OnStart(action_data);
        action_data.m_Player.TryHideItemInHands(true);
    }
References ActionData::m_Player.
ReadFromContext()
override bool ActionDrinkPondContinuous::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 88 of file actiondrinkpondcontinuous.c.
    {
        super.ReadFromContext(ctx, action_recive_data);
        if( HasTarget() )
        {
            vector cursor_position;
            if ( !ctx.Read(cursor_position) )
                return false;
            action_recive_data.m_Target.SetCursorHitPos(cursor_position);
        }
        return true;
    }
References HasTarget(), and Serializer::Read().
WriteToContext()
override void ActionDrinkPondContinuous::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 78 of file actiondrinkpondcontinuous.c.
    {
        super.WriteToContext(ctx, action_data);
        if( HasTarget() )
        {
            ctx.Write(action_data.m_Target.GetCursorHitPos());
        }
    }
References HasTarget(), ActionData::m_Target, and Serializer::Write().
Member Data Documentation
WATER_DRANK_PER_SEC
private const float ActionDrinkPondContinuous::WATER_DRANK_PER_SEC = 35 private
Definition at line 11 of file actiondrinkpondcontinuous.c.