DayzKode: ActionLockDoors Class Reference
ActionLockDoors Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionLockDoors ()
override void CreateConditionComponents ()
protected void LockDoor (ActionTarget target)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionlockdoors.c.
Constructor & Destructor Documentation
ActionLockDoors()
void ActionLockDoors::ActionLockDoors () inline private
Definition at line 11 of file actionlockdoors.c.
    {
        m_CallbackClass = ActionLockDoorsCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_HIGH;
        m_Text = "#lock_door";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionLockDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 27 of file actionlockdoors.c.
    {
        if( !target ) return false;
        //if( IsDamageDestroyed(action_data.m_Target) ) return false;
        if( !IsBuilding(target) ) return false;
        if( !IsInReach(player, target, UAMaxDistances.DEFAULT) ) return false;
        Building building;
        if( Class.CastTo(building, target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(target.GetComponentIndex());
            if ( doorIndex != -1 )
                return (!building.IsDoorOpen(doorIndex) && !building.IsDoorLocked(doorIndex));
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, IsBuilding(), and IsInReach().
CreateConditionComponents()
override void ActionLockDoors::CreateConditionComponents () inline private
Definition at line 21 of file actionlockdoors.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
LockDoor()
protected void ActionLockDoors::LockDoor (ActionTarget target) inline private
Definition at line 44 of file actionlockdoors.c.
    {
        Building building;
        if ( Class.CastTo(building, target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(target.GetComponentIndex());
            if ( doorIndex != -1 )
            {
                building.LockDoor(doorIndex);
            }
        }
    }
References Class::CastTo().
Referenced by OnFinishProgressServer().
OnFinishProgressServer()
override void ActionLockDoors::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 58 of file actionlockdoors.c.
    {
        LockDoor(action_data.m_Target);
        //Damage the Lockpick
        //float dmg = action_data.m_MainItem.GetMaxHealth() * 0.04; //Multiply max health by 'x' amount depending on number of usages wanted (0.04 = 25)
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        float skillLevel = action_data.m_Player.GetSoftSkillsManager().GetSpecialtyLevel();
        float appliedDamage = 5 + 2*skillLevel;
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, appliedDamage);
    }
References LockDoor(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.