DayzKode: StomachItem Class Reference
StomachItem Class Reference
Private Member Functions
void AddAgents (int agents)
void AddAmount (float amount)
float GetAmount ()
string GetClassName ()
int GetFoodStage ()
float GetNutritions (float digestion_points, NutritionalProfile profile, out float water, out float energy, out float toxicity)
bool ProcessDigestion (float digestion_points, out float water, out float energy, out float toxicity, out float volume, out int agents, out float consumed_amount)
void SetFoodStage (int food_stage)
void StomachItem (string class_name, float amount, NutritionalProfile profile, int foodstage, int agents)
Private Attributes
int m_Agents
float m_Amount
string m_ClassName
int m_FoodStage
ref NutritionalProfile m_Profile
Detailed Description
Definition at line 1 of file playerstomach.c.
Constructor & Destructor Documentation
StomachItem()
void StomachItem::StomachItem (string class_name, float amount, NutritionalProfile profile, int foodstage, int agents) inline private
Definition at line 10 of file playerstomach.c.
    {
        m_Amount = amount;
        m_Profile = profile;
        //m_IsLiquid = is_liquid;
        m_FoodStage = foodstage;
        m_ClassName = class_name;
        m_Agents = agents;
    }
References class_name, m_Agents, m_Amount, m_ClassName, m_FoodStage, and m_Profile.
Member Function Documentation
AddAgents()
void StomachItem::AddAgents (int agents) inline private
Definition at line 60 of file playerstomach.c.
    {
        m_Agents = m_Agents | agents;
    }
References m_Agents.
Referenced by AddToStomach().
AddAmount()
void StomachItem::AddAmount (float amount) inline private
Definition at line 55 of file playerstomach.c.
    {
        m_Amount += amount;
    }
References m_Amount.
Referenced by AddToStomach().
GetAmount()
float StomachItem::GetAmount () inline private
Definition at line 49 of file playerstomach.c.
    {
        return m_Amount;
    }
References m_Amount.
GetClassName()
string StomachItem::GetClassName () inline private
Definition at line 20 of file playerstomach.c.
    {
        return m_ClassName;
    }
References m_ClassName.
Referenced by AddToStomach().
GetFoodStage()
int StomachItem::GetFoodStage () inline private
Definition at line 38 of file playerstomach.c.
    {
        return m_FoodStage;
    }
References m_FoodStage.
Referenced by AddToStomach().
GetNutritions()
float StomachItem::GetNutritions (float digestion_points, NutritionalProfile profile, out float water, out float energy, out float toxicity) inline private
Definition at line 76 of file playerstomach.c.
    {
        float energy_per_unit = profile.GetEnergy() / 100;
        float water_per_unit = profile.GetWaterContent() / 100;
        float toxicity_per_unit = profile.GetToxicity();
        float digestability = profile.GetDigestibility();
        if(digestability == 0)//if undefined
        {
            digestability = 1;
        }
        float consumed_quantity = digestion_points * digestability;
        if( m_Amount < consumed_quantity )
        {
            consumed_quantity = m_Amount;
        }
        if ( consumed_quantity > 0 )
        {
            water = consumed_quantity * water_per_unit;
            energy = consumed_quantity * energy_per_unit;
            toxicity = consumed_quantity * toxicity_per_unit;
        }
        return consumed_quantity;
    }
References NutritionalProfile::GetDigestibility(), NutritionalProfile::GetEnergy(), NutritionalProfile::GetToxicity(), NutritionalProfile::GetWaterContent(), and m_Amount.
Referenced by ProcessDigestion().
ProcessDigestion()
bool StomachItem::ProcessDigestion (float digestion_points, out float water, out float energy, out float toxicity, out float volume, out int agents, out float consumed_amount) inline private
Definition at line 67 of file playerstomach.c.
    {
        agents = m_Agents;
        consumed_amount = GetNutritions(digestion_points, m_Profile, water, energy, toxicity );
        m_Amount -= consumed_amount;
        volume = m_Profile.GetFullnessIndex() * m_Amount;
        return( m_Amount < 0.001 );
    }
References NutritionalProfile::GetFullnessIndex(), GetNutritions(), m_Agents, m_Amount, and m_Profile.
Referenced by ProcessNutrients().
SetFoodStage()
void StomachItem::SetFoodStage (int food_stage) inline private
Definition at line 43 of file playerstomach.c.
    {
        m_FoodStage = food_stage;
    }
References m_FoodStage.
Member Data Documentation
m_Agents
int StomachItem::m_Agents private
Definition at line 8 of file playerstomach.c.
Referenced by AddAgents(), OnStoreSave(), ProcessDigestion(), and StomachItem().
m_Amount
float StomachItem::m_Amount private
Definition at line 4 of file playerstomach.c.
Referenced by AddAmount(), GetAmount(), GetNutritions(), OnStoreSave(), ProcessDigestion(), and StomachItem().
m_ClassName
string StomachItem::m_ClassName private
Definition at line 7 of file playerstomach.c.
Referenced by GetClassName(), OnStoreSave(), and StomachItem().
m_FoodStage
int StomachItem::m_FoodStage private
Definition at line 5 of file playerstomach.c.
Referenced by GetFoodStage(), OnStoreSave(), SetFoodStage(), and StomachItem().
m_Profile
ref NutritionalProfile StomachItem::m_Profile private
Definition at line 3 of file playerstomach.c.
Referenced by ProcessDigestion(), and StomachItem().