DayzKode: BaseBuildingBase Class Reference
BaseBuildingBase Class Reference
Private Member Functions
void AddRefresherTime01 (float fraction)
override void AfterStoreLoad ()
override void AfterStoreLoad ()
override void AfterStoreLoad ()
void AnimateFlag (float delta)
override bool CanBeRepairedToPristine ()
override bool CanBeRepairedToPristine ()
override bool CanBeRepairedToPristine ()
override bool CanBeRepairedToPristine ()
bool CanCloseFence ()
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanDisplayAttachmentSlot (int slot_id)
bool CanOpenFence ()
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanUseConstructionBuild ()
override bool CanUseHandConstruction ()
protected void CheckFenceClosed ()
protected void CheckFenceOpened ()
int CheckGateState ()
override bool CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player)
void CheckLoadedVariables (int max_duration)
override bool CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player)
override bool CheckSlotVerticalDistance (int slot_id, PlayerBase player)
void CloseFence ()
override void CreateAreaDamage (string slot_name, float rotation_angle=0)
void Fence ()
bool GateAttachmentConditions (int slotId)
void GateAttachmentsSanityCheck ()
BarbedWire GetBarbedWire1 ()
BarbedWire GetBarbedWire2 ()
CamoNet GetCamoNet ()
CombinationLock GetCombinationLock ()
override string GetConstructionKitType ()
override string GetConstructionKitType ()
override string GetConstructionKitType ()
override string GetConstructionKitType ()
int GetGateState ()
override vector GetKitSpawnPosition ()
override vector GetKitSpawnPosition ()
override vector GetKitSpawnPosition ()
override int GetMeleeTargetType ()
override int GetMeleeTargetType ()
override int GetMeleeTargetType ()
override int GetMeleeTargetType ()
float GetRefresherTime01 ()
void HandleDropAttachment (ItemBase item)
void HandleRefreshers ()
Client-side, saves positions of active lifetime refreshers to MissionGameplay.
bool HasFullyConstructedGate ()
bool HasHinges ()
override bool HasProperDistance (string selection, PlayerBase player)
override bool HasProperDistance (string selection, PlayerBase player)
override bool HasProperDistance (string selection, PlayerBase player)
override bool HasProperDistance (string selection, PlayerBase player)
void InitRefresherData ()
void InsertRefresherPosition ()
override bool IsFacingCamera (string selection)
override bool IsFacingCamera (string selection)
override bool IsFacingCamera (string selection)
override bool IsFacingCamera (string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
override bool IsFacingPlayer (PlayerBase player, string selection)
bool IsLocked ()
override bool IsOpened ()
override bool IsPlayerInside (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
override bool IsPlayerInside (PlayerBase player, string selection)
override bool MustBeBuiltFromOutside ()
override bool NameOverride (out string output)
override void OnCEUpdate ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override array< string > OnDebugSpawnBuildExcludes ()
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartBuiltServer (notnull Man player, string part_name, int action_id)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override void OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override void OnPartDismantledServer (notnull Man player, string part_name, int action_id)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnVariablesSynchronized ()
void OpenFence ()
override bool PerformRoofCheckForBase (string partName, PlayerBase player, out bool result)
override void PostAreaDamageActions ()
void RemoveRefresherPosition (int idx=-2)
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void SetGateState (int state)
void SetOpenedState (bool state)
void SetRefresherActive (bool state)
void SetRefreshTimer01 (float fraction)
void ShelterSite ()
protected void SoundGateCloseEnd ()
protected void SoundGateCloseStart ()
protected void SoundGateOpenStart ()
void TerritoryFlag ()
override bool TranslateSlotFromSelection (string selection_name, out int slot_id)
void UpdateBarbedWireAreaDamagePos (float rotation_angle=0, bool to_delete=false)
override void UpdateVisuals ()
void Watchtower ()
void ~TerritoryFlag ()
Private Attributes
ATTACHMENT_BARBED_WIRE = BarbedWire
ATTACHMENT_CAMONET = CamoNet
ATTACHMENT_COMBINATION_LOCK = CombinationLock
const string ATTACHMENT_SLOT_COMBINATION_LOCK = "Att_CombinationLock"
ATTACHMENT_WOODEN_LOG = WoodenLog
string ATTSLOT_BARBEDWIRE_DOWN = "Wall_Barbedwire_1"
string ATTSLOT_BARBEDWIRE_UP = "Wall_Barbedwire_2"
string ATTSLOT_CAMONET = "Wall_Camonet"
const float GATE_ROTATION_ANGLE_DEG = 100
const float GATE_ROTATION_TIME_APPROX = 2000
const int GATE_STATE_FULL = 2
const int GATE_STATE_NONE = 0
const int GATE_STATE_PARTIAL = 1
protected int m_FlagRefresherFrequency = GameConstants.REFRESHER_FREQUENCY_DEFAULT
protected int m_FlagRefresherMaxDuration = GameConstants.REFRESHER_MAX_DURATION_DEFAULT
protected int m_GateState = 0
protected bool m_IsOpened = false
protected bool m_IsOpenedClient = false
bool m_RefresherActive
bool m_RefresherActiveLocal
bool m_RefresherInitialized
int m_RefresherTimeRemaining
int m_RefreshTimeCounter
protected EffectSound m_SoundGate_End
protected EffectSound m_SoundGate_Start
protected bool m_ToDiscard = false
const float MAX_ACTION_DETECTION_ANGLE_RAD = 1.3
const float MAX_ACTION_DETECTION_DISTANCE = 2.0
const float MAX_FLOOR_VERTICAL_DISTANCE = 0.5
const float MIN_ACTION_DETECTION_ANGLE_RAD = 0.35
const string SOUND_GATE_CLOSE_END = "DoorWoodTowerClose_end_SoundSet"
const string SOUND_GATE_CLOSE_START = "DoorWoodTowerClose_start_SoundSet"
const string SOUND_GATE_OPEN_START = "DoorWoodTowerOpen_SoundSet"
Static Private Attributes
static const string BASE_ROOF_NAME = "_roof"
static const string BASE_VIEW_NAME = "level_"
static const string BASE_WALL_NAME = "_wall_"
static const int MAX_WATCHTOWER_FLOORS = 3
static const int MAX_WATCHTOWER_WALLS = 3
Detailed Description
Definition at line 1 of file fence.c.
Constructor & Destructor Documentation
~TerritoryFlag()
void BaseBuildingBase::~TerritoryFlag () inline private
Definition at line 29 of file totem.c.
    {
        RemoveRefresherPosition();
    }
References RemoveRefresherPosition().
Member Function Documentation
AddRefresherTime01()
void BaseBuildingBase::AddRefresherTime01 (float fraction) inline private
Definition at line 516 of file totem.c.
    {
        float temp = Math.Clamp(m_RefresherTimeRemaining + (fraction * m_FlagRefresherMaxDuration), 0, m_FlagRefresherMaxDuration);
        m_RefresherTimeRemaining = Math.Round(temp);
        SetRefresherActive(m_RefresherTimeRemaining > 0);
        //Print(m_RefresherTimeRemaining);
    }
References Math::Clamp(), Math::Round(), and SetRefresherActive().
Referenced by OnDebugSpawn().
AfterStoreLoad() [1/3]
override void BaseBuildingBase::AfterStoreLoad () inline private
Definition at line 257 of file fence.c.
    {
        super.AfterStoreLoad();
        //set gate state
        ConstructionPart gate_part = GetConstruction().GetGateConstructionPart();
        SetGateState( CheckGateState() );
        //update gate state visual
        if ( IsOpened() )
        {
            OpenFence();
        }
        UpdateVisuals();
        bsbDebugPrint("[bsb] AfterStoreLoad - build=" + gate_part.IsBuilt() + " opened=" + IsOpened());
    }
References bsbDebugPrint(), CheckGateState(), GetConstruction(), ConstructionPart::IsBuilt(), IsOpened(), IsOpened(), OpenFence(), SetGateState(), and UpdateVisuals().
AfterStoreLoad() [2/3]
override void BaseBuildingBase::AfterStoreLoad () inline private
Definition at line 145 of file totem.c.
    {
        super.AfterStoreLoad();
        if (!m_RefresherInitialized && GetCEApi())
        {
            InitRefresherData();
        }
        SetSynchDirty();
        UpdateVisuals();
    }
References GetCEApi(), InitRefresherData(), and UpdateVisuals().
AfterStoreLoad() [3/3]
override void BaseBuildingBase::AfterStoreLoad () inline private
Definition at line 399 of file watchtower.c.
    {
        super.AfterStoreLoad();
        UpdateVisuals();
    }
References UpdateVisuals().
AnimateFlag()
void BaseBuildingBase::AnimateFlag (float delta) inline private
Definition at line 488 of file totem.c.
    {
        float temp = Math.Clamp( delta,0,1 );
        float phase_new;
        if (temp < 0.01 || temp > 0.99)
        {
            phase_new = Math.Round(temp);
        }
        else
            phase_new = temp;
        SetAnimationPhase("flag_mast",phase_new);
        GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString("Material_FPole_Flag"),phase_new != 1);
    }
References Math::Clamp(), InventorySlots::GetSlotIdFromString(), and Math::Round().
Referenced by OnCEUpdate(), OnDebugSpawn(), and OnStoreLoad().
CanBeRepairedToPristine() [1/4]
override bool BaseBuildingBase::CanBeRepairedToPristine () inline private
Definition at line 425 of file fence.c.
    {
        return true;
    }
CanBeRepairedToPristine() [2/4]
override bool BaseBuildingBase::CanBeRepairedToPristine () inline private
Definition at line 77 of file sheltersite.c.
    {
        return true;
    }
CanBeRepairedToPristine() [3/4]
override bool BaseBuildingBase::CanBeRepairedToPristine () inline private
Definition at line 350 of file totem.c.
    {
        return true;
    }
CanBeRepairedToPristine() [4/4]
override bool BaseBuildingBase::CanBeRepairedToPristine () inline private
Definition at line 128 of file watchtower.c.
    {
        return true;
    }
CanCloseFence()
bool BaseBuildingBase::CanCloseFence () inline private
Definition at line 441 of file fence.c.
    {
        if ( HasHinges() && IsOpened() )
        {
            return true;
        }
        return false;
    }
References HasHinges(), and IsOpened().
CanDisplayAttachmentCategory() [1/3]
override bool BaseBuildingBase::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 197 of file fence.c.
    {
        if ( category_name == "Attachments" || category_name == "Material" )
        {
            if ( !HasBase() )
            {
                return false;
            }
        }
        return true;
    }
References HasBase().
CanDisplayAttachmentCategory() [2/3]
override bool BaseBuildingBase::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 85 of file totem.c.
    {
        if ( category_name == "Base" && !HasBase() )
            return true;
        else if ( category_name == "Support" && HasBase() && !GetConstruction().IsPartConstructed("support") )
            return true;
        else if ( category_name == "Pole" && GetConstruction().IsPartConstructed("support") && !GetConstruction().IsPartConstructed("pole") )
            return true;
        else if ( category_name == "Flag" && GetConstruction().IsPartConstructed("pole") )
            return true;
        else
            return false;
    }
References GetConstruction(), HasBase(), and IsPartConstructed().
CanDisplayAttachmentCategory() [3/3]
override bool BaseBuildingBase::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 245 of file watchtower.c.
    {
        //super
        if ( !super.CanDisplayAttachmentCategory( category_name ) )
            return false;
        //
        category_name.ToLower();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //level 1
        if ( category_name.Contains( "level_1" ) )
        {
            if ( category_name.Contains( "level_1_" ) )
            {
                return GetConstruction().IsPartConstructed( "level_1_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
            else
            {
                return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
        }
        //level 2
        if ( category_name.Contains( "level_2" ) )
        {
            if ( category_name.Contains( "level_2_" ) )
            {
                return GetConstruction().IsPartConstructed( "level_2_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_1_roof" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
            }
        }
        //level 3
        if ( category_name.Contains( "level_3" ) )
        {
            if ( category_name.Contains( "level_3_" ) )
            {
                return GetConstruction().IsPartConstructed( "level_3_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_2_roof" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
            }
        }
        return true;
    }
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), GetGame(), GetPlayer(), and string::ToLower().
CanDisplayAttachmentSlot() [1/2]
override bool BaseBuildingBase::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 176 of file fence.c.
    {
        if (!super.CanDisplayAttachmentSlot(slot_id))
            return false;
        string slot_name = InventorySlots.GetSlotName(slot_id);
        if ( slot_name == "Att_CombinationLock" )
        {
            if ( !HasFullyConstructedGate() )
            {
                return false;
            }
        }
        if ( !GateAttachmentConditions(InventorySlots.GetSlotIdFromString(slot_name)) )
            return false;
        return true;
    }
References GateAttachmentConditions(), InventorySlots::GetSlotIdFromString(), InventorySlots::GetSlotName(), and HasFullyConstructedGate().
CanDisplayAttachmentSlot() [2/2]
override bool BaseBuildingBase::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 198 of file watchtower.c.
    {
        //super
        if ( !super.CanDisplayAttachmentSlot( slot_id ) )
            return false;
        string slot_name = InventorySlots.GetSlotName(slot_id);
        slot_name.ToLower();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //base attachments
        if ( slot_name.Contains( "material_l1" ) || slot_name.Contains( "level_1_" ) )
        {
            if ( slot_name.Contains( "woodenlogs" ) )
            {
                return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_1_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
        }
        else if ( slot_name.Contains( "material_l2" ) || slot_name.Contains( "level_2_" ) )
        {
            if ( slot_name.Contains( "woodenlogs" ) )
            {
                return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_2_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
            }
        }
        else if ( slot_name.Contains( "material_l3" ) || slot_name.Contains( "level_3_" ) )
        {
            if ( slot_name.Contains( "woodenlogs" ) )
            {
                return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_3_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
            }
        }
        return true;
    }
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), GetGame(), GetPlayer(), InventorySlots::GetSlotName(), and string::ToLower().
CanOpenFence()
bool BaseBuildingBase::CanOpenFence () inline private
Definition at line 431 of file fence.c.
    {
        if ( HasHinges() && !IsOpened() && !IsLocked() )
        {
            return true;
        }
        return false;
    }
References HasHinges(), IsLocked(), and IsOpened().
CanPutIntoHands() [1/4]
override bool BaseBuildingBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 410 of file fence.c.
    {
        if( !super.CanPutIntoHands( parent ) )
        {
            return false;
        }
        if ( HasBase() )
        {
            return false;
        }
        return true;
    }
References HasBase().
CanPutIntoHands() [2/4]
override bool BaseBuildingBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 72 of file sheltersite.c.
    {
        return false;
    }
CanPutIntoHands() [3/4]
override bool BaseBuildingBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 345 of file totem.c.
    {
        return false;
    }
CanPutIntoHands() [4/4]
override bool BaseBuildingBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 123 of file watchtower.c.
    {
        return false;
    }
CanReceiveAttachment() [1/3]
override bool BaseBuildingBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 371 of file fence.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        //manage action initiator (AT_ATTACH_TO_CONSTRUCTION)
        if ( !GetGame().IsDedicatedServer() )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if ( player )
            {
                ConstructionActionData construction_action_data = player.GetConstructionActionData();
                //reset action initiator
                construction_action_data.SetActionInitiator( NULL );
            }
        }
        //conditions
        if ( attachment.Type() != ATTACHMENT_WOODEN_LOG )
        {
            if ( !HasBase() )
            {
                return false;
            }
        }
        if ( attachment.IsInherited( ATTACHMENT_COMBINATION_LOCK ) )
        {
            return ( HasFullyConstructedGate() && !IsOpened() );
        }
        if ( !GateAttachmentConditions(slotId) )
            return false;
        return true;
    }
References GateAttachmentConditions(), GetGame(), GetPlayer(), HasBase(), HasFullyConstructedGate(), IsOpened(), and ConstructionActionData::SetActionInitiator().
CanReceiveAttachment() [2/3]
override bool BaseBuildingBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 276 of file totem.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        //manage action initiator (AT_ATTACH_TO_CONSTRUCTION)
        if ( !GetGame().IsDedicatedServer() )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if ( player )
            {
                ConstructionActionData construction_action_data = player.GetConstructionActionData();
                //reset action initiator
                construction_action_data.SetActionInitiator( NULL );
            }
        }
        //conditions
        string slot_name = InventorySlots.GetSlotName(slotId);
        //flag item attachment
        if ( slot_name == "Material_FPole_Flag" )
        {
            if ( GetConstruction().IsPartConstructed("pole") )
                return true;
            else
                return false;
        }
        //materials
        ConstructionPart part;
        ConstructionPart part_lowest;
        int part_id = -1;
        for (int i = 0; i < GetConstruction().GetConstructionParts().Count(); i++)
        {
            part = GetConstruction().GetConstructionParts().GetElement(i);
            if (!part.IsBuilt())
            {
                if (part_id == -1 || part_id > part.GetId())
                {
                    part_lowest = part;
                    part_id = part.GetId();
                }
            }
        }
        if (part_lowest /*&& !part_lowest.IsBuilt()*/)
        {
            string cfg_path = "cfgVehicles " + GetType() + " Construction " + part_lowest.GetMainPartName() + " " + part_lowest.GetPartName() + " Materials";
            string material_path;
            if ( GetGame().ConfigIsExisting(cfg_path) )
            {
                string child_name;
                string child_slot_name;
                for ( i = 0; i < GetGame().ConfigGetChildrenCount( cfg_path ); i++ )
                {
                    GetGame().ConfigGetChildName( cfg_path, i, child_name );
                    material_path = "" + cfg_path + " " + child_name + " slot_name";
                    if ( GetGame().ConfigGetText(material_path,child_slot_name) && child_slot_name == slot_name )
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), ConfigIsExisting(), GetConstruction(), GetGame(), ConstructionPart::GetId(), ConstructionPart::GetMainPartName(), ConstructionPart::GetPartName(), GetPlayer(), InventorySlots::GetSlotName(), GetType(), ConstructionPart::IsBuilt(), IsPartConstructed(), and ConstructionActionData::SetActionInitiator().
CanReceiveAttachment() [3/3]
override bool BaseBuildingBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 90 of file watchtower.c.
    {
        if ( !super.CanReceiveAttachment( attachment, slotId ) )
            return false;
        //because CanReceiveAttachment() method can be called on all clients in the vicinity, vertical distance check needs to be skipped on clients that don't
        //interact with the object through attach action (AT_ATTACH_TO_CONSTRUCTION)
        PlayerBase player;
        if ( !GetGame().IsDedicatedServer() )
        {
            //check action initiator (AT_ATTACH_TO_CONSTRUCTION)
            player = PlayerBase.Cast( GetGame().GetPlayer() );
            if ( player )
            {
                ConstructionActionData construction_action_data = player.GetConstructionActionData();
                PlayerBase action_initiator = construction_action_data.GetActionInitiator();
                if ( action_initiator == player )
                {
                    construction_action_data.SetActionInitiator( NULL );                //reset action initiator
                }
                else
                {
                    player = null;                  //do not do vertical check (next)
                }
            }
        }
        //
        return CheckSlotVerticalDistance( slotId, player );
    }
References CheckSlotVerticalDistance(), ConstructionActionData::GetActionInitiator(), GetGame(), GetPlayer(), and ConstructionActionData::SetActionInitiator().
CanUseConstructionBuild()
override bool BaseBuildingBase::CanUseConstructionBuild () inline private
Definition at line 722 of file fence.c.
    {
        return !IsOpened();
    }
References IsOpened().
CanUseHandConstruction()
override bool BaseBuildingBase::CanUseHandConstruction () inline private
Definition at line 82 of file sheltersite.c.
    {
        return true;
    }
CheckFenceClosed()
protected void BaseBuildingBase::CheckFenceClosed () inline private
Definition at line 545 of file fence.c.
    {
        if ( GetAnimationPhase( "Wall_Gate_Rotate" ) == 0 )         //animation finished - closed
        {
            //client or single player
            if ( !GetGame().IsDedicatedServer() )
            {
                //play sound
                if ( this ) SoundGateCloseEnd();
            }
            UpdateBarbedWireAreaDamagePos(GetAnimationPhase( "Wall_Gate_Rotate" ));
            //remove check
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Remove( CheckFenceClosed );
        }
    }
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SoundGateCloseEnd(), and UpdateBarbedWireAreaDamagePos().
CheckFenceOpened()
protected void BaseBuildingBase::CheckFenceOpened () inline private
Definition at line 535 of file fence.c.
    {
        if ( GetAnimationPhase( "Wall_Gate_Rotate" ) == GATE_ROTATION_ANGLE_DEG )           //animation finished - open
        {
            UpdateBarbedWireAreaDamagePos(GetAnimationPhase( "Wall_Gate_Rotate" ));
            //remove check
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Remove( CheckFenceOpened );
        }
    }
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), and UpdateBarbedWireAreaDamagePos().
CheckGateState()
int BaseBuildingBase::CheckGateState () inline private
Definition at line 77 of file fence.c.
    {
        ConstructionPart gate_part = GetConstruction().GetGateConstructionPart();
        int state = GATE_STATE_NONE;
        if( gate_part.IsBuilt() )
        {
            ConstructionPart req_part;
            array<string> req_parts = gate_part.GetRequiredParts();
            for (int i = 0; i < req_parts.Count(); i++)
            {
                req_part = GetConstruction().GetConstructionPart(req_parts.Get(i));
                if(!req_part.IsBuilt())
                    break;
            }
            if( i != req_parts.Count() )
            {
                state = GATE_STATE_PARTIAL;
            }
            else
            {
                state = GATE_STATE_FULL;
            }
        }
        return state;
    }
References GATE_STATE_FULL, GATE_STATE_NONE, GATE_STATE_PARTIAL, GetConstruction(), ConstructionPart::GetRequiredParts(), and ConstructionPart::IsBuilt().
Referenced by AfterStoreLoad(), OnPartBuiltServer(), OnPartDestroyedServer(), and OnPartDismantledServer().
CheckLevelVerticalDistance()
override bool BaseBuildingBase::CheckLevelVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 383 of file watchtower.c.
    {
        if ( player )
        {
            if ( selection.Contains( "level_1_" ) )
                return CheckMemoryPointVerticalDistance( max_dist, "level_1", player );
            if ( selection.Contains( "level_2_" ) )
                return CheckMemoryPointVerticalDistance( max_dist, "level_2", player );
            if ( selection.Contains( "level_3_" ) )
                return CheckMemoryPointVerticalDistance( max_dist, "level_3", player );
        }
        return false;
    }
References CheckMemoryPointVerticalDistance(), and string::Contains().
Referenced by IsPlayerInside().
CheckLoadedVariables()
void BaseBuildingBase::CheckLoadedVariables (int max_duration) inline private
Definition at line 529 of file totem.c.
    {
        if (max_duration != m_FlagRefresherMaxDuration)
        {
            m_RefresherTimeRemaining = m_FlagRefresherMaxDuration * m_RefresherTimeRemaining / max_duration;
        }
    }
Referenced by OnStoreLoad().
CheckMemoryPointVerticalDistance()
override bool BaseBuildingBase::CheckMemoryPointVerticalDistance (float max_dist, string selection, PlayerBase player) inline private
Definition at line 357 of file watchtower.c.
    {
        if ( player )
        {
            //check vertical distance
            vector player_pos = player.GetPosition();
            vector pos;
            if ( MemoryPointExists( selection ) )
            {
                pos = ModelToWorld( GetMemoryPointPos( selection ) );
            }
            if ( Math.AbsFloat( player_pos[1] - pos[1] ) <= max_dist )
            {
                return true;
            }
            else
            {
                return false;
            }
        }
        return true;
    }
References Math::AbsFloat(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
Referenced by CanDisplayAttachmentCategory(), CanDisplayAttachmentSlot(), CheckLevelVerticalDistance(), and CheckSlotVerticalDistance().
CheckSlotVerticalDistance()
override bool BaseBuildingBase::CheckSlotVerticalDistance (int slot_id, PlayerBase player) inline private
Definition at line 295 of file watchtower.c.
    {
        string slot_name;
        InventorySlots.GetSelectionForSlotId( slot_id , slot_name );
        slot_name.ToLower();
        //wall attachments
        //level 1
        if ( slot_name.Contains( "material_l1" ) || slot_name.Contains( "level_1_" ) )
        {
            if ( slot_name.Contains( "woodenlogs" ) )
            {
                return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
            else
            {
                return GetConstruction().IsPartConstructed( "level_1_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_1", player );
            }
        }
        //level 2
        if ( slot_name.Contains( "material_l2" ) || slot_name.Contains( "level_2_" ) )
        {
            if ( slot_name.Contains( "material_l2w" ) || slot_name.Contains( "level_2_wall" ) )
            {
                return GetConstruction().IsPartConstructed( "level_2_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
            }
            else
            {
                if ( slot_name.Contains( "woodenlogs" ) )
                {
                    return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
                }
                else
                {
                    return GetConstruction().IsPartConstructed( "level_1_roof" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_2", player );
                }
            }
        }
        //level 3
        if ( slot_name.Contains( "material_l3" ) || slot_name.Contains( "level_3_" ) )
        {
            if ( slot_name.Contains( "material_l3w" ) || slot_name.Contains( "level_3_wall" ) )
            {
                return GetConstruction().IsPartConstructed( "level_3_base" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
            }
            else
            {
                if ( slot_name.Contains( "woodenlogs" ) )
                {
                    return CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
                }
                else
                {
                    return GetConstruction().IsPartConstructed( "level_2_roof" ) && CheckMemoryPointVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, "level_3", player );
                }
            }
        }
        return true;
    }
References CheckMemoryPointVerticalDistance(), string::Contains(), GetConstruction(), InventorySlots::GetSelectionForSlotId(), and string::ToLower().
Referenced by ActionAttachToConstruction::ActionCondition(), and CanReceiveAttachment().
CloseFence()
void BaseBuildingBase::CloseFence () inline private
Definition at line 493 of file fence.c.
    {
        //server or single player
        if ( GetGame().IsServer() )
        {
            float value = 0;
            SetAnimationPhase( "Wall_Interact_Rotate",              value );
            SetAnimationPhase( "Wall_Barbedwire_1_Mounted_Rotate",  value );
            SetAnimationPhase( "Wall_Barbedwire_2_Mounted_Rotate",  value );
            SetAnimationPhase( "Wall_Camonet_Rotate",               value );
            SetAnimationPhase( "Wall_Gate_Rotate",                  value );
            SetAnimationPhase( "Wall_Base_Down_Rotate",             value );
            SetAnimationPhase( "Wall_Base_Up_Rotate",               value );
            SetAnimationPhase( "Wall_Wood_Down_Rotate",             value );
            SetAnimationPhase( "Wall_Wood_Up_Rotate",               value );
            SetAnimationPhase( "Wall_Metal_Down_Rotate",            value );
            SetAnimationPhase( "Wall_Metal_Up_Rotate",              value );
            SetOpenedState( false );
            //regenerate navmesh
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( UpdateNavmesh, GATE_ROTATION_TIME_APPROX, false );
            //synchronize
            SynchronizeBaseState();
        }
        //client or single player
        if ( !GetGame().IsDedicatedServer() )
        {
            //play sound
            SoundGateCloseStart();
        }
        //remove BarbedWire AreaDamageTrigger
        UpdateBarbedWireAreaDamagePos(0,true);
        //add check
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Remove(CheckFenceOpened);
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( CheckFenceClosed, 0, true );
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SetOpenedState(), SoundGateCloseStart(), SynchronizeBaseState(), UpdateBarbedWireAreaDamagePos(), and UpdateNavmesh().
Referenced by OnPartDestroyedServer(), and OnVariablesSynchronized().
CreateAreaDamage()
override void BaseBuildingBase::CreateAreaDamage (string slot_name, float rotation_angle = 0) inline private
Definition at line 562 of file fence.c.
    {
        if ( IsOpened() )
        {
            rotation_angle = 100;
        }
        super.CreateAreaDamage( slot_name, rotation_angle );
    }
References IsOpened().
Fence()
void BaseBuildingBase::Fence () inline private
Definition at line 36 of file fence.c.
    {
        //synchronized variables
        //RegisterNetSyncVariableBool( "m_HasHinges" );
        //RegisterNetSyncVariableBool( "m_GateFullyConstructed" );
        RegisterNetSyncVariableBool( "m_IsOpened" );
        RegisterNetSyncVariableInt( "m_GateState" );
    }
GateAttachmentConditions()
bool BaseBuildingBase::GateAttachmentConditions (int slotId) inline private
Definition at line 793 of file fence.c.
    {
        if ( GetGateState() == GATE_STATE_PARTIAL )
        {
            ConstructionPart wall_base_down = GetConstruction().GetConstructionPart("wall_base_down");
            ConstructionPart wall_base_up = GetConstruction().GetConstructionPart("wall_base_up");
            string slot_name = InventorySlots.GetSlotName(slotId);
            if ( !wall_base_up.IsBuilt() )
            {
                if ( slot_name == ATTSLOT_CAMONET || slot_name == ATTSLOT_BARBEDWIRE_UP )
                {
                    return false;
                }
            }
            if ( !wall_base_down.IsBuilt() )
            {
                if ( slot_name == ATTSLOT_BARBEDWIRE_DOWN )
                {
                    return false;
                }
            }
        }
        return true;
    }
References GetConstruction(), GetGateState(), InventorySlots::GetSlotName(), and ConstructionPart::IsBuilt().
Referenced by CanDisplayAttachmentSlot(), and CanReceiveAttachment().
GateAttachmentsSanityCheck()
void BaseBuildingBase::GateAttachmentsSanityCheck () inline private
Definition at line 757 of file fence.c.
    {
        ConstructionPart wall_base_down = GetConstruction().GetConstructionPart("wall_base_down");
        ConstructionPart wall_base_up = GetConstruction().GetConstructionPart("wall_base_up");
        if(GetBarbedWire1() && !wall_base_down.IsBuilt())
        {
            HandleDropAttachment(GetBarbedWire1());
            HandleDropAttachment(GetCombinationLock());
        }
        if( ( GetCamoNet() || GetBarbedWire2() ) && !wall_base_up.IsBuilt() )
        {
            HandleDropAttachment(GetBarbedWire2());
            HandleDropAttachment(GetCamoNet());
            HandleDropAttachment(GetCombinationLock());
        }
    }
References GetBarbedWire1(), GetBarbedWire2(), GetCamoNet(), GetCombinationLock(), GetConstruction(), HandleDropAttachment(), and ConstructionPart::IsBuilt().
GetBarbedWire1()
BarbedWire BaseBuildingBase::GetBarbedWire1 () inline private
Definition at line 149 of file fence.c.
    {
        BarbedWire barbedwire = BarbedWire.Cast( FindAttachmentBySlotName( "Wall_Barbedwire_1" ) );
        return barbedwire;
    }
Referenced by GateAttachmentsSanityCheck(), OnPartDestroyedServer(), and UpdateBarbedWireAreaDamagePos().
GetBarbedWire2()
BarbedWire BaseBuildingBase::GetBarbedWire2 () inline private
Definition at line 155 of file fence.c.
    {
        BarbedWire barbedwire = BarbedWire.Cast( FindAttachmentBySlotName( "Wall_Barbedwire_2" ) );
        return barbedwire;
    }
Referenced by GateAttachmentsSanityCheck(), OnPartDestroyedServer(), and UpdateBarbedWireAreaDamagePos().
GetCamoNet()
CamoNet BaseBuildingBase::GetCamoNet () inline private
Definition at line 143 of file fence.c.
    {
        CamoNet camonet = CamoNet.Cast( FindAttachmentBySlotName( "Wall_Camonet" ) );
        return camonet;
    }
Referenced by GateAttachmentsSanityCheck(), and OnPartDestroyedServer().
GetCombinationLock()
CombinationLock BaseBuildingBase::GetCombinationLock () inline private
Definition at line 137 of file fence.c.
    {
        CombinationLock combination_lock = CombinationLock.Cast( FindAttachmentBySlotName( ATTACHMENT_SLOT_COMBINATION_LOCK ) );
        return combination_lock;
    }
Referenced by GateAttachmentsSanityCheck(), IsLocked(), and OnPartDestroyedServer().
GetConstructionKitType() [1/4]
override string BaseBuildingBase::GetConstructionKitType () inline private
Definition at line 45 of file fence.c.
    {
        return "FenceKit";
    }
Referenced by ItemBase::CreateConstructionKit(), and ItemBase::CreateConstructionKitInHands().
GetConstructionKitType() [2/4]
override string BaseBuildingBase::GetConstructionKitType () inline private
Definition at line 10 of file sheltersite.c.
    {
        return "ShelterKit";
    }
GetConstructionKitType() [3/4]
override string BaseBuildingBase::GetConstructionKitType () inline private
Definition at line 50 of file totem.c.
    {
        return "TerritoryFlagKit";
    }
GetConstructionKitType() [4/4]
override string BaseBuildingBase::GetConstructionKitType () inline private
Definition at line 21 of file watchtower.c.
    {
        return "WatchtowerKit";
    }
GetGateState()
int BaseBuildingBase::GetGateState () inline private
Definition at line 72 of file fence.c.
    {
        return m_GateState;
    }
References m_GateState.
Referenced by GateAttachmentConditions().
GetKitSpawnPosition() [1/3]
override vector BaseBuildingBase::GetKitSpawnPosition () inline private
Definition at line 162 of file fence.c.
    {
        if ( MemoryPointExists( "kit_spawn_position" ) )
        {
            vector position;
            position = GetMemoryPointPos( "kit_spawn_position" );
            return ModelToWorld( position );
        }
        return GetPosition();
    }
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
Referenced by ItemBase::CreateConstructionKit().
GetKitSpawnPosition() [2/3]
override vector BaseBuildingBase::GetKitSpawnPosition () inline private
Definition at line 21 of file sheltersite.c.
    {
        if ( MemoryPointExists( "kit_spawn_position" ) )
        {
            vector position;
            position = GetMemoryPointPos( "kit_spawn_position" );
            return ModelToWorld( position );
        }
        return GetPosition();
    }
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
GetKitSpawnPosition() [3/3]
override vector BaseBuildingBase::GetKitSpawnPosition () inline private
Definition at line 72 of file totem.c.
    {
        if ( MemoryPointExists( "kit_spawn_position" ) )
        {
            vector position;
            position = GetMemoryPointPos( "kit_spawn_position" );
            return ModelToWorld( position );
        }
        return GetPosition();
    }
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), and ModelToWorld().
GetMeleeTargetType() [1/4]
override int BaseBuildingBase::GetMeleeTargetType () inline private
Definition at line 50 of file fence.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetMeleeTargetType() [2/4]
override int BaseBuildingBase::GetMeleeTargetType () inline private
Definition at line 15 of file sheltersite.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetMeleeTargetType() [3/4]
override int BaseBuildingBase::GetMeleeTargetType () inline private
Definition at line 55 of file totem.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetMeleeTargetType() [4/4]
override int BaseBuildingBase::GetMeleeTargetType () inline private
Definition at line 26 of file watchtower.c.
    {
        return EMeleeTargetType.NONALIGNABLE;
    }
GetRefresherTime01()
float BaseBuildingBase::GetRefresherTime01 () inline private
Definition at line 524 of file totem.c.
    {
        return m_RefresherTimeRemaining / m_FlagRefresherMaxDuration;
    }
References m_FlagRefresherMaxDuration.
Referenced by OnCEUpdate(), and OnStoreLoad().
HandleDropAttachment()
void BaseBuildingBase::HandleDropAttachment (ItemBase item) inline private
Definition at line 774 of file fence.c.
    {
        BarbedWire wire;
        CombinationLock lock;
        if (Class.CastTo(wire,item)) //special barbed wire beh.
        {
            wire.SetMountedState( false );
            GetInventory().DropEntity(InventoryMode.SERVER, this, wire);
        }
        else if (Class.CastTo(lock,item))
        {
            lock.UnlockServer(null,this);
        }
        else if (item)//generic behaviour
        {
            GetInventory().DropEntity(InventoryMode.SERVER, this, item);
        }
    }
References Class::CastTo().
Referenced by GateAttachmentsSanityCheck(), and OnPartDestroyedServer().
HandleRefreshers()
void BaseBuildingBase::HandleRefreshers () inline private
Client-side, saves positions of active lifetime refreshers to MissionGameplay.
Definition at line 179 of file totem.c.
    {
        Mission mission = GetGame().GetMission();
        if (!mission.m_ActiveRefresherLocations)
            return;
        int idx = mission.m_ActiveRefresherLocations.Find(GetPosition());
        if ( m_RefresherActive && idx == -1 )
        {
            InsertRefresherPosition();
        }
        else if ( !m_RefresherActive && idx > -1 )
        {
            RemoveRefresherPosition(idx);
        }
    }
References GetGame(), CGame::GetMission(), GetPosition, InsertRefresherPosition(), Mission::m_ActiveRefresherLocations, mission, and RemoveRefresherPosition().
Referenced by OnVariablesSynchronized().
HasFullyConstructedGate()
bool BaseBuildingBase::HasFullyConstructedGate () inline private
Definition at line 61 of file fence.c.
    {
        return m_GateState == GATE_STATE_FULL;
    }
References GATE_STATE_FULL.
Referenced by CanDisplayAttachmentSlot(), and CanReceiveAttachment().
HasHinges()
bool BaseBuildingBase::HasHinges () inline private
Definition at line 56 of file fence.c.
    {
        return m_GateState > GATE_STATE_NONE;
    }
References GATE_STATE_NONE.
Referenced by CanCloseFence(), and CanOpenFence().
HasProperDistance() [1/4]
override bool BaseBuildingBase::HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 707 of file fence.c.
    {
        if ( MemoryPointExists( selection ) )
        {
            vector selection_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            float distance = vector.Distance( selection_pos, player.GetPosition() );
            if ( distance >= MAX_ACTION_DETECTION_DISTANCE )
            {
                return false;
            }
        }
        return true;
    }
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
Referenced by ActionRepairPart::RepairCondition().
HasProperDistance() [2/4]
override bool BaseBuildingBase::HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 149 of file sheltersite.c.
    {
        if ( MemoryPointExists( selection ) )
        {
            vector selection_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            float distance = vector.Distance( selection_pos, player.GetPosition() );
            if ( distance >= MAX_ACTION_DETECTION_DISTANCE )
            {
                return false;
            }
        }
        return true;
    }
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
HasProperDistance() [3/4]
override bool BaseBuildingBase::HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 450 of file totem.c.
    {
        //TODO
        if ( MemoryPointExists( selection ) )
        {
            vector selection_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            float distance = vector.Distance( selection_pos, player.GetPosition() );
            if ( distance >= MAX_ACTION_DETECTION_DISTANCE )
            {
                return false;
            }
        }
        return true;
    }
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
HasProperDistance() [4/4]
override bool BaseBuildingBase::HasProperDistance (string selection, PlayerBase player) inline private
Definition at line 546 of file watchtower.c.
    {
        if ( MemoryPointExists( selection ) )
        {
            vector selection_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            float distance = vector.Distance( selection_pos, player.GetPosition() );
            if ( distance >= MAX_ACTION_DETECTION_DISTANCE )
            {
                return false;
            }
        }
        return true;
    }
References vector::Distance(), GetMemoryPointPos(), MemoryPointExists(), and ModelToWorld().
InitRefresherData()
void BaseBuildingBase::InitRefresherData () inline private
Definition at line 34 of file totem.c.
    {
        int frequency = GetCEApi().GetCEGlobalInt("FlagRefreshFrequency");
        int max_duration = GetCEApi().GetCEGlobalInt("FlagRefreshMaxDuration");
        if ( frequency > 0)
        {
            m_FlagRefresherFrequency = frequency;
        }
        if ( max_duration > 0 )
        {
            m_FlagRefresherMaxDuration = max_duration;
        }
        m_RefresherInitialized = true;
    }
References GetCEApi().
Referenced by AfterStoreLoad(), and TerritoryFlag().
InsertRefresherPosition()
void BaseBuildingBase::InsertRefresherPosition () inline private
Definition at line 208 of file totem.c.
    {
        Mission mission = GetGame().GetMission();
        mission.m_ActiveRefresherLocations.Insert(GetPosition());
    }
References GetGame(), CGame::GetMission(), GetPosition, Mission::m_ActiveRefresherLocations, and mission.
Referenced by HandleRefreshers().
IsFacingCamera() [1/4]
override bool BaseBuildingBase::IsFacingCamera (string selection) inline private
Definition at line 682 of file fence.c.
    {
        vector ref_dir = GetDirection();
        vector cam_dir = GetGame().GetCurrentCameraDirection();
        //ref_dir = GetGame().GetCurrentCameraPosition() - GetPosition();
        ref_dir.Normalize();
        ref_dir[1] = 0;     //ignore height
        cam_dir.Normalize();
        cam_dir[1] = 0;     //ignore height
        if ( ref_dir.Length() != 0 )
        {
            float angle = Math.Acos( cam_dir * ref_dir );
            if ( angle >= MAX_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
Referenced by BuildCondition(), ActionDestroyPart::DestroyCondition(), ActionDismantlePart::DismantleCondition(), and ActionRepairPart::RepairCondition().
IsFacingCamera() [2/4]
override bool BaseBuildingBase::IsFacingCamera (string selection) inline private
Definition at line 92 of file sheltersite.c.
    {
        vector ref_dir = GetDirection();
        vector cam_dir = GetGame().GetCurrentCameraDirection();
        //ref_dir = GetGame().GetCurrentCameraPosition() - GetPosition();
        ref_dir.Normalize();
        ref_dir[1] = 0;     //ignore height
        cam_dir.Normalize();
        cam_dir[1] = 0;     //ignore height
        if ( ref_dir.Length() != 0 )
        {
            float angle = Math.Acos( cam_dir * ref_dir );
            if ( angle >= MAX_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
IsFacingCamera() [3/4]
override bool BaseBuildingBase::IsFacingCamera (string selection) inline private
Definition at line 423 of file totem.c.
    {
        return false; //TODO
        vector ref_dir = GetDirection();
        vector cam_dir = GetGame().GetCurrentCameraDirection();
        //ref_dir = GetGame().GetCurrentCameraPosition() - GetPosition();
        ref_dir.Normalize();
        ref_dir[1] = 0;     //ignore height
        cam_dir.Normalize();
        cam_dir[1] = 0;     //ignore height
        if ( ref_dir.Length() != 0 )
        {
            float angle = Math.Acos( cam_dir * ref_dir );
            if ( angle >= MAX_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::Acos(), CGame::GetCurrentCameraDirection(), GetDirection(), GetGame(), vector::Length(), and vector::Normalize().
IsFacingCamera() [4/4]
override bool BaseBuildingBase::IsFacingCamera (string selection) inline private
Definition at line 478 of file watchtower.c.
    {
        vector ref_pos;
        vector ref_dir;
        vector cam_dir = GetGame().GetCurrentCameraDirection();
        if ( MemoryPointExists( selection ) )
        {
            ref_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            ref_dir = ref_pos - GetPosition();
            ref_dir.Normalize();
            ref_dir[1] = 0;     //ignore height
            cam_dir[1] = 0;     //ignore height
            if ( ref_dir.Length() > 0.5 )       //if the distance (m) is too low, ignore this check
            {
                float dot = vector.Dot( cam_dir, ref_dir );
                if ( dot < 0 )
                {
                    return true;
                }
            }
        }
        return false;
    }
References vector::Dot(), CGame::GetCurrentCameraDirection(), GetGame(), GetMemoryPointPos(), GetPosition, vector::Length(), MemoryPointExists(), ModelToWorld(), and vector::Normalize().
IsFacingPlayer() [1/3]
override bool BaseBuildingBase::IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 655 of file fence.c.
    {
        vector fence_pos = GetPosition();
        vector player_pos = player.GetPosition();
        vector ref_dir = GetDirection();
        //vector fence_player_dir = player_pos - fence_pos;
        vector fence_player_dir = player.GetDirection();
        fence_player_dir.Normalize();
        fence_player_dir[1] = 0;    //ignore height
        ref_dir.Normalize();
        ref_dir[1] = 0;         //ignore height
        if ( ref_dir.Length() != 0 )
        {
            float angle = Math.Acos( fence_player_dir * ref_dir );
            if ( angle >= MAX_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::Acos(), GetDirection(), GetPosition, vector::Length(), and vector::Normalize().
Referenced by ActionRepairPart::RepairCondition().
IsFacingPlayer() [2/3]
override bool BaseBuildingBase::IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 394 of file totem.c.
    {
        return true; //TODO
        vector fence_pos = GetPosition();
        vector player_pos = player.GetPosition();
        vector ref_dir = GetDirection();
        //vector fence_player_dir = player_pos - fence_pos;
        vector fence_player_dir = player.GetDirection();
        fence_player_dir.Normalize();
        fence_player_dir[1] = 0;    //ignore height
        ref_dir.Normalize();
        ref_dir[1] = 0;         //ignore height
        if ( ref_dir.Length() != 0 )
        {
            float angle = Math.Acos( fence_player_dir * ref_dir );
            if ( angle >= MAX_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::Acos(), GetDirection(), GetPosition, vector::Length(), and vector::Normalize().
IsFacingPlayer() [3/3]
override bool BaseBuildingBase::IsFacingPlayer (PlayerBase player, string selection) inline private
Definition at line 429 of file watchtower.c.
    {
        vector ref_pos;
        vector ref_dir;
        vector player_dir;
        float dot;
        bool has_memory_point = MemoryPointExists( selection );
        if ( has_memory_point )
        {
            ref_pos = ModelToWorld( GetMemoryPointPos( selection ) );
            ref_dir = ref_pos - GetPosition();
        }
        else
        {
            ref_pos = GetPosition();
            ref_dir = ref_pos - player.GetPosition();
        }
        ref_dir.Normalize();
        ref_dir[1] = 0;             //ignore height
        player_dir = player.GetDirection();
        player_dir.Normalize();
        player_dir[1] = 0;          //ignore height
        if ( ref_dir.Length() != 0 )
        {
            dot = vector.Dot( player_dir, ref_dir );
        }
        if ( has_memory_point )
        {
            if ( dot < 0 && Math.AbsFloat( dot ) > MIN_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        else
        {
            if ( dot > 0 && Math.AbsFloat( dot ) > MIN_ACTION_DETECTION_ANGLE_RAD )
            {
                return true;
            }
        }
        return false;
    }
References Math::AbsFloat(), vector::Dot(), GetMemoryPointPos(), GetPosition, vector::Length(), MemoryPointExists(), ModelToWorld(), and vector::Normalize().
IsLocked()
bool BaseBuildingBase::IsLocked () inline private
Definition at line 115 of file fence.c.
    {
        CombinationLock combination_lock = GetCombinationLock();
        if ( combination_lock && combination_lock.IsLocked() )
        {
            return true;
        }
        return false;
    }
References GetCombinationLock().
Referenced by CanOpenFence(), and OnPartDismantledServer().
IsOpened()
override bool BaseBuildingBase::IsOpened () inline private
Definition at line 110 of file fence.c.
    {
        return m_IsOpened;
    }
References m_IsOpened.
Referenced by AfterStoreLoad(), CanCloseFence(), CanOpenFence(), CanReceiveAttachment(), CanUseConstructionBuild(), CreateAreaDamage(), ActionDismantlePart::DismantleCondition(), and OnPartDestroyedServer().
IsPlayerInside() [1/4]
override bool BaseBuildingBase::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 619 of file fence.c.
    {
        vector player_pos = player.GetPosition();
        vector fence_pos = GetPosition();
        vector ref_dir = GetDirection();
        ref_dir[1] = 0;
        ref_dir.Normalize();
        vector x[2];
        vector b1,b2;
        GetCollisionBox(x);
        b1 = x[0];
        b2 = x[1];
        vector dir_to_fence = fence_pos - player_pos;
        dir_to_fence[1] = 0;
        float len = dir_to_fence.Length();
        dir_to_fence.Normalize();
        vector ref_dir_angle = ref_dir.VectorToAngles();
        vector dir_to_fence_angle = dir_to_fence.VectorToAngles();
        vector test_angles = dir_to_fence_angle - ref_dir_angle;
        vector test_position = test_angles.AnglesToVector() * len;
        if(test_position[0] < b1[0] || test_position[0] > b2[0] || test_position[2] < 0.2 || test_position[2] > 2.2 )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
Referenced by ActionUnmountBarbedWire::ActionCondition(), ActionTakeMaterialToHands::ActionCondition(), ActionAttachToConstruction::ActionCondition(), ActionTakeMaterialToHandsSwitch::ActionCondition(), BuildCondition(), ActionDismantlePart::DismantleCondition(), and VicinityContainer::UpdateInterval().
IsPlayerInside() [2/4]
override bool BaseBuildingBase::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 117 of file sheltersite.c.
    {
        vector player_pos = player.GetPosition();
        vector object_pos = GetPosition();
        vector ref_dir = GetDirection();
        ref_dir[1] = 0;
        ref_dir.Normalize();
        vector min,max;
        min = -GetMemoryPointPos( "BoundingBox_min" );
        max = -GetMemoryPointPos( "BoundingBox_max" );
        vector dir_to_object = object_pos - player_pos;
        dir_to_object[1] = 0;
        float len = dir_to_object.Length();
        dir_to_object.Normalize();
        vector ref_dir_angle = ref_dir.VectorToAngles();
        vector dir_to_object_angle = dir_to_object.VectorToAngles();
        vector test_angles = dir_to_object_angle - ref_dir_angle;
        vector test_position = test_angles.AnglesToVector() * len;
        if(test_position[0] > max[0] || test_position[0] < min[0] || test_position[2] > max[2] || test_position[2] < min[2] )
        {
            return false;
        }
        return true;
    }
References vector::AnglesToVector(), GetDirection(), GetMemoryPointPos(), GetPosition, vector::Length(), vector::Normalize(), and vector::VectorToAngles().
IsPlayerInside() [3/4]
override bool BaseBuildingBase::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 356 of file totem.c.
    {
        return true; //TODO
        vector player_pos = player.GetPosition();
        vector fence_pos = GetPosition();
        vector ref_dir = GetDirection();
        ref_dir[1] = 0;
        ref_dir.Normalize();
        vector x[2];
        vector b1,b2;
        GetCollisionBox(x);
        b1 = x[0];
        b2 = x[1];
        vector dir_to_fence = fence_pos - player_pos;
        dir_to_fence[1] = 0;
        float len = dir_to_fence.Length();
        dir_to_fence.Normalize();
        vector ref_dir_angle = ref_dir.VectorToAngles();
        vector dir_to_fence_angle = dir_to_fence.VectorToAngles();
        vector test_angles = dir_to_fence_angle - ref_dir_angle;
        vector test_position = test_angles.AnglesToVector() * len;
        if(test_position[0] < b1[0] || test_position[0] > b2[0] || test_position[2] < 0.2 || test_position[2] > 2.2 )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
References vector::AnglesToVector(), GetCollisionBox(), GetDirection(), GetPosition, vector::Length(), vector::Normalize(), vector::VectorToAngles(), and x.
IsPlayerInside() [4/4]
override bool BaseBuildingBase::IsPlayerInside (PlayerBase player, string selection) inline private
Definition at line 508 of file watchtower.c.
    {
        if ( selection != "")
        {
            CheckLevelVerticalDistance( MAX_FLOOR_VERTICAL_DISTANCE, selection, player );
        }
        vector player_pos = player.GetPosition();
        vector tower_pos = GetPosition();
        vector ref_dir = GetDirection();
        ref_dir[1] = 0;
        ref_dir.Normalize();
        vector min,max;
        min = -GetMemoryPointPos( "interact_min" );
        max = -GetMemoryPointPos( "interact_max" );
        vector dir_to_tower = tower_pos - player_pos;
        dir_to_tower[1] = 0;
        float len = dir_to_tower.Length();
        dir_to_tower.Normalize();
        vector ref_dir_angle = ref_dir.VectorToAngles();
        vector dir_to_tower_angle = dir_to_tower.VectorToAngles();
        vector test_angles = dir_to_tower_angle - ref_dir_angle;
        vector test_position = test_angles.AnglesToVector() * len;
        if (test_position[0] > max[0] || test_position[0] < min[0] || test_position[2] > max[2] || test_position[2] < min[2] )
        {
            return false;
        }
        return true;
    }
References vector::AnglesToVector(), CheckLevelVerticalDistance(), GetDirection(), GetMemoryPointPos(), GetPosition, vector::Length(), vector::Normalize(), and vector::VectorToAngles().
MustBeBuiltFromOutside()
override bool BaseBuildingBase::MustBeBuiltFromOutside () inline private
Definition at line 87 of file sheltersite.c.
    {
        return true;
    }
Referenced by BuildCondition().
NameOverride()
override bool BaseBuildingBase::NameOverride (out string output) inline private
Definition at line 126 of file fence.c.
    {
        if ( m_GateState != GATE_STATE_NONE )
        {
            output = "#str_cfgvehicles_construction_part_gate";  //changes object displayed name if in 'gate' state
            output.ToUpper();
            return true;
        }
        return false;
    }
OnCEUpdate()
override void BaseBuildingBase::OnCEUpdate () inline private
Definition at line 157 of file totem.c.
    {
        super.OnCEUpdate();
        int time_elapsed_rounded = Math.Round(m_ElapsedSinceLastUpdate);
        if ( m_RefresherTimeRemaining > 0 )
        {
            m_RefreshTimeCounter += time_elapsed_rounded;
            if ( m_RefreshTimeCounter >= m_FlagRefresherFrequency )
            {
                GetCEApi().RadiusLifetimeReset(GetPosition(),GameConstants.REFRESHER_RADIUS);
                m_RefresherTimeRemaining = Math.Clamp(m_RefresherTimeRemaining - m_RefreshTimeCounter,0,m_FlagRefresherMaxDuration);
                m_RefreshTimeCounter = 0; //possibly carry over the rest?
                AnimateFlag( 1 - GetRefresherTime01() );
            }
        }
        SetRefresherActive(m_RefresherTimeRemaining > 0);
    }
References AnimateFlag(), Math::Clamp(), GetCEApi(), GetPosition, GetRefresherTime01(), GameConstants::REFRESHER_RADIUS, Math::Round(), and SetRefresherActive().
OnDebugSpawn() [1/3]
override void BaseBuildingBase::OnDebugSpawn () inline private
Definition at line 896 of file fence.c.
    {
        super.OnDebugSpawn();
        GetInventory().CreateInInventory("CamoNet");
        for (int i = 0; i < 2; ++i)
        {
            BarbedWire wire = BarbedWire.Cast(GetInventory().CreateInInventory("BarbedWire"));
            wire.SetMountedState(true);
        }
    }
References CreateInInventory().
OnDebugSpawn() [2/3]
override void BaseBuildingBase::OnDebugSpawn () inline private
Definition at line 553 of file totem.c.
    {
        super.OnDebugSpawn();
        GetInventory().CreateInInventory("Flag_DayZ");
        AnimateFlag(0);
        AddRefresherTime01(1);
    }
References AddRefresherTime01(), and AnimateFlag().
OnDebugSpawn() [3/3]
override void BaseBuildingBase::OnDebugSpawn () inline private
Definition at line 599 of file watchtower.c.
    {
        super.OnDebugSpawn();
        int i;
        for (i = 0; i < MAX_WATCHTOWER_FLOORS * MAX_WATCHTOWER_WALLS; ++i)
        {
            GetInventory().CreateInInventory("CamoNet");
        }
        for (i = 0; i < 2 * MAX_WATCHTOWER_WALLS; ++i)
        {
            BarbedWire wire = BarbedWire.Cast(GetInventory().CreateInInventory("BarbedWire"));
            wire.SetMountedState(true);
        }
    }
References CreateInInventory(), and MAX_WATCHTOWER_WALLS.
OnDebugSpawnBuildExcludes() [1/2]
override array< string > BaseBuildingBase::OnDebugSpawnBuildExcludes () inline private
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 858 of file fence.c.
    {
        array<string> excludes = {};
        #ifdef DEVELOPER
        bool bWood = DiagMenu.GetBool(DiagMenuIDs.DM_BUILD_WOOD);
        #else
        bool bWood = false;
        #endif
        if (bWood)
        {
            excludes.Insert("_metal_");
        }
        else
        {
            excludes.Insert("_wood_");
        }
        #ifdef DEVELOPER
        bool bGate = DiagMenu.GetBool(DiagMenuIDs.DM_BUILD_GATE);
        #else
        bool bGate = false;
        #endif
        if (bGate)
        {
            excludes.Insert("platform");
        }
        else
        {
            excludes.Insert("gate");
        }
        return excludes;
    }
References DiagMenu::GetBool().
Referenced by ItemBase::FullyBuild().
OnDebugSpawnBuildExcludes() [2/2]
override array< string > BaseBuildingBase::OnDebugSpawnBuildExcludes () inline private
Excludes certain parts from being built by OnDebugSpawn, uses Contains to compare.
Definition at line 576 of file watchtower.c.
    {
        array<string> excludes;
        #ifdef DEVELOPER
        bool bWood = DiagMenu.GetBool(DiagMenuIDs.DM_BUILD_WOOD);
        #else
        bool bWood = false;
        #endif
        if (bWood)
        {
            excludes = {"_metal_"};
        }
        else
        {
            excludes = {"_wood_"};
        }
        return excludes;
    }
References DiagMenu::GetBool().
OnPartBuiltServer() [1/4]
override void BaseBuildingBase::OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 297 of file fence.c.
    {
        ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        super.OnPartBuiltServer( player, part_name, action_id );
        SetGateState( CheckGateState() );
        //drop attachments without carrier part
        if (constrution_part.IsGate())
            //GateAttachmentsSanityCheck();
        //update visuals (server)
        UpdateVisuals();
    }
References CheckGateState(), GetConstruction(), ConstructionPart::IsGate(), SetGateState(), and UpdateVisuals().
Referenced by ItemBase::FullyBuild().
OnPartBuiltServer() [2/4]
override void BaseBuildingBase::OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 36 of file sheltersite.c.
    {
        ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        string shelter_type = "";
        switch (part_name)
        {
            case "leather":
                shelter_type = "ShelterLeather";
            break;
            case "fabric":
                shelter_type = "ShelterFabric";
            break;
            case "stick":
                shelter_type = "ShelterStick";
            break;
            default: {};
        }
        if (shelter_type != "")
        {
            GetConstruction().DropNonUsableMaterialsServer( player, part_name );
            MiscGameplayFunctions.TurnItemIntoItem(this, shelter_type, PlayerBase.Cast(player));
            PluginAdminLog admin_log = PluginAdminLog.Cast( GetPlugin(PluginAdminLog) );
            if (admin_log)
            {
                admin_log.DirectAdminLogPrint(" built " + shelter_type + " with Hands ");
            }
        }
        //super.OnPartBuiltServer( part_name, action_id );
    }
References GetConstruction(), and GetPlugin().
OnPartBuiltServer() [3/4]
override void BaseBuildingBase::OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 247 of file totem.c.
    {
        //ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        super.OnPartBuiltServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References UpdateVisuals().
OnPartBuiltServer() [4/4]
override void BaseBuildingBase::OnPartBuiltServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 406 of file watchtower.c.
    {
        super.OnPartBuiltServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References UpdateVisuals().
OnPartDestroyedServer() [1/3]
override void BaseBuildingBase::OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 335 of file fence.c.
    {
        super.OnPartDestroyedServer( player, part_name, action_id );
        //check gate state
        ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        if ( constrution_part.IsGate() && destroyed_by_connected_part ) //avoids attachment dropping on regular hinges destruction
        {
            //drop regular attachments
            HandleDropAttachment(GetBarbedWire1());
            HandleDropAttachment(GetBarbedWire2());
            HandleDropAttachment(GetCamoNet());
            HandleDropAttachment(GetCombinationLock());
            //rotate back to place
            if ( IsOpened() )
                CloseFence();
        }
        if ( part_name == "wall_base_down" )
        {
            HandleDropAttachment(GetBarbedWire1());
            HandleDropAttachment(GetCombinationLock());
        }
        if ( part_name == "wall_base_up" )
        {
            HandleDropAttachment(GetBarbedWire2());
            HandleDropAttachment(GetCamoNet());
            HandleDropAttachment(GetCombinationLock());
        }
        SetGateState( CheckGateState() );
        //update visuals (server)
        UpdateVisuals();
    }
References CheckGateState(), CloseFence(), GetBarbedWire1(), GetBarbedWire2(), GetCamoNet(), GetCombinationLock(), GetConstruction(), HandleDropAttachment(), ConstructionPart::IsGate(), IsOpened(), SetGateState(), and UpdateVisuals().
OnPartDestroyedServer() [2/3]
override void BaseBuildingBase::OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 267 of file totem.c.
    {
        super.OnPartDestroyedServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References UpdateVisuals().
OnPartDestroyedServer() [3/3]
override void BaseBuildingBase::OnPartDestroyedServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false) inline private
Definition at line 420 of file watchtower.c.
    {
        super.OnPartDestroyedServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References UpdateVisuals().
OnPartDismantledServer() [1/3]
override void BaseBuildingBase::OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 313 of file fence.c.
    {
        ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        //check gate state
        if ( constrution_part.IsGate() )
        {
            if ( IsLocked() )
            {
                CombinationLock combination_lock = CombinationLock.Cast( FindAttachmentBySlotName( ATTACHMENT_SLOT_COMBINATION_LOCK ) );
                combination_lock.UnlockServer( player , this );
            }
        }
        super.OnPartDismantledServer( player, part_name, action_id );
        SetGateState( CheckGateState() );
        //update visuals (server)
        UpdateVisuals();
    }
References CheckGateState(), GetConstruction(), ConstructionPart::IsGate(), IsLocked(), SetGateState(), and UpdateVisuals().
OnPartDismantledServer() [2/3]
override void BaseBuildingBase::OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 257 of file totem.c.
    {
        ConstructionPart constrution_part = GetConstruction().GetConstructionPart( part_name );
        super.OnPartDismantledServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References GetConstruction(), and UpdateVisuals().
OnPartDismantledServer() [3/3]
override void BaseBuildingBase::OnPartDismantledServer (notnull Man player, string part_name, int action_id) inline private
Definition at line 413 of file watchtower.c.
    {
        super.OnPartDismantledServer( player, part_name, action_id );
        //update visuals (server)
        UpdateVisuals();
    }
References UpdateVisuals().
OnStoreLoad() [1/2]
override bool BaseBuildingBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 222 of file fence.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Fence data ---
        //has gate
        if (version < 110)
        {
            if ( !ctx.Read( m_ToDiscard ) )
            {
                m_ToDiscard = false;
                return false;
            }
            m_GateState = GATE_STATE_NONE;
        }
        else if ( !ctx.Read( m_GateState ) )
        {
            m_GateState = GATE_STATE_NONE;
            return false;
        }
        //is opened
        if ( !ctx.Read( m_IsOpened ) )
        {
            m_IsOpened = false;
            return false;
        }
        bsbDebugPrint("[bsb] OnStoreLoad - build=" + m_GateState + " opened=" + m_IsOpened);
        //---
        return true;
    }
References bsbDebugPrint(), GATE_STATE_NONE, m_IsOpened, and Serializer::Read().
OnStoreLoad() [2/2]
override bool BaseBuildingBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 111 of file totem.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //int loaded_frequency;
        int loaded_max_duration;
        if ( !ctx.Read( m_RefresherTimeRemaining ) )
        {
            return false;
        }
        if ( !ctx.Read( m_RefreshTimeCounter ) )
        {
            return false;
        }
        if ( !ctx.Read( loaded_max_duration ) )
        {
            return false;
        }
        if ( version >= 118 && !ctx.Read( m_RefresherActive ) )
        {
            return false;
        }
        CheckLoadedVariables(loaded_max_duration);
        AnimateFlag(1 - GetRefresherTime01());
        return true;
    }
References AnimateFlag(), CheckLoadedVariables(), GetRefresherTime01(), and Serializer::Read().
OnStoreSave() [1/2]
override void BaseBuildingBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 212 of file fence.c.
    {
        super.OnStoreSave( ctx );
        //write
        ctx.Write( m_GateState );
        ctx.Write( m_IsOpened );
        bsbDebugPrint("[bsb] OnStoreSave - build=" + m_GateState + " opened=" + m_IsOpened);
    }
References bsbDebugPrint(), m_IsOpened, and Serializer::Write().
OnStoreSave() [2/2]
override void BaseBuildingBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 101 of file totem.c.
    {
        super.OnStoreSave( ctx );
        ctx.Write( m_RefresherTimeRemaining );
        ctx.Write( m_RefreshTimeCounter );
        ctx.Write( m_FlagRefresherMaxDuration );
        ctx.Write( m_RefresherActive );
    }
References Serializer::Write().
OnVariablesSynchronized() [1/2]
override void BaseBuildingBase::OnVariablesSynchronized () inline private
Definition at line 276 of file fence.c.
    {
        super.OnVariablesSynchronized();
        if ( m_IsOpenedClient != m_IsOpened )
        {
            m_IsOpenedClient = m_IsOpened;
            if ( m_IsOpenedClient )
            {
                OpenFence();
            }
            else
            {
                CloseFence();
            }
        }
    }
References CloseFence(), m_IsOpened, m_IsOpened, and OpenFence().
OnVariablesSynchronized() [2/2]
override void BaseBuildingBase::OnVariablesSynchronized () inline private
Definition at line 234 of file totem.c.
    {
        super.OnVariablesSynchronized();
        if ( m_RefresherActive != m_RefresherActiveLocal )
        {
            HandleRefreshers();
            m_RefresherActiveLocal = m_RefresherActive;
        }
    }
References HandleRefreshers(), and m_RefresherActive.
OpenFence()
void BaseBuildingBase::OpenFence () inline private
Definition at line 451 of file fence.c.
    {
        //server or single player
        if ( GetGame().IsServer() )
        {
            float value = GATE_ROTATION_ANGLE_DEG;
            SetAnimationPhase( "Wall_Interact_Rotate",              value );
            SetAnimationPhase( "Wall_Barbedwire_1_Mounted_Rotate",  value );
            SetAnimationPhase( "Wall_Barbedwire_2_Mounted_Rotate",  value );
            SetAnimationPhase( "Wall_Camonet_Rotate",               value );
            SetAnimationPhase( "Wall_Gate_Rotate",                  value );
            SetAnimationPhase( "Wall_Base_Down_Rotate",             value );
            SetAnimationPhase( "Wall_Base_Up_Rotate",               value );
            SetAnimationPhase( "Wall_Wood_Down_Rotate",             value );
            SetAnimationPhase( "Wall_Wood_Up_Rotate",               value );
            SetAnimationPhase( "Wall_Metal_Down_Rotate",            value );
            SetAnimationPhase( "Wall_Metal_Up_Rotate",              value );
            SetOpenedState( true );
            //regenerate navmesh
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( UpdateNavmesh, GATE_ROTATION_TIME_APPROX, false );
            //synchronize
            SynchronizeBaseState();
        }
        //client or single player
        if ( !GetGame().IsDedicatedServer() )
        {
            //play sound
            SoundGateOpenStart();
        }
        //remove BarbedWire AreaDamageTrigger
        UpdateBarbedWireAreaDamagePos(0,true);
        //add check
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Remove(CheckFenceClosed);
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( CheckFenceOpened, 0, true );
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), GATE_ROTATION_ANGLE_DEG, CGame::GetCallQueue(), GetGame(), ScriptCallQueue::Remove(), SetOpenedState(), SoundGateOpenStart(), SynchronizeBaseState(), UpdateBarbedWireAreaDamagePos(), and UpdateNavmesh().
Referenced by AfterStoreLoad(), and OnVariablesSynchronized().
PerformRoofCheckForBase()
override bool BaseBuildingBase::PerformRoofCheckForBase (string partName, PlayerBase player, out bool result) inline private
Definition at line 133 of file watchtower.c.
    {
        if (CfgGameplayHandler.GetDisablePerformRoofCheck())
            return false;
        if (partName != "level_1_base" && partName != "level_2_base" && partName != "level_3_base" && partName != "level_3_roof")
        {
            return false;
        }
        vector center;
        vector orientation = GetOrientation();
        vector edge_length;
        vector min_max[2];
        ref array<Object> excluded_objects = new array<Object>;
        ref array<Object> collided_objects = new array<Object>;
        excluded_objects.Insert( this );
        excluded_objects.Insert( player );
        if ( partName == "level_2_base" )
        {
            min_max[0] = GetMemoryPointPos( "level_2_wall_1_down_min" );
            min_max[1] = GetMemoryPointPos( "level_2_roof_max" );
        }
        else if ( partName == "level_3_base" )
        {
            min_max[0] = GetMemoryPointPos( "level_3_wall_1_down_min" );
            min_max[1] = GetMemoryPointPos( "level_3_wall_2_up_max" );
        }
        else if ( partName == "level_3_roof" )
        {
            min_max[0] = GetMemoryPointPos( "level_3_roof_min" );
            min_max[1] = GetMemoryPointPos( "level_3_roof_max" );
        }
        else
        {
            //min_max[0] = GetMemoryPointPos( "level_1_wall_1_up_min" );
            //min_max[0] = GetMemoryPointPos( "level_1_wall_1_down_min" );
            min_max[0] = GetMemoryPointPos( "level_1_collisioncheck_min" );
            min_max[1] = GetMemoryPointPos( "level_1_roof_max" );
        }
        center = GetPosition();
        center[1] = center[1] + ( min_max[1][1] + min_max[0][1] ) / 2;
        edge_length[0] = min_max[1][0] - min_max[0][0];
        edge_length[2] = min_max[1][2] - min_max[0][2];
        edge_length[1] = min_max[1][1] - min_max[0][1];
        result = false;
        /*result = */GetGame().IsBoxCollidingGeometry( center, orientation, edge_length, ObjIntersectView, ObjIntersectGeom, excluded_objects, collided_objects );
        if ( collided_objects.Count() > 0 )
        {
            foreach ( Object o : collided_objects )
            {
                if (Building.Cast(o))
                {
                    result = true;
                }
            }
        }
        return true;
    }
References CfgGameplayHandler::GetDisablePerformRoofCheck(), GetGame(), GetMemoryPointPos(), GetOrientation(), GetPosition, and CGame::IsBoxCollidingGeometry().
Referenced by ComplexBuildCollideCheckClient().
PostAreaDamageActions()
override void BaseBuildingBase::PostAreaDamageActions () inline private
Definition at line 607 of file fence.c.
    {
        /*if (GetBarbedWire1())
        {
            //DecreaseHealth("Wall_BarbedWire_1", "", 1000); //why no dmg to wire???
            //BarbedWire wire = GetBarbedWire1();
            //wire.PostAreaDamageActions();
            //Print(GetHealth("BarbedWire1", ""));
        }*/
    }
RemoveRefresherPosition()
void BaseBuildingBase::RemoveRefresherPosition (int idx = -2) inline private
Definition at line 214 of file totem.c.
    {
        if (!GetGame() || (GetGame().IsMultiplayer() && GetGame().IsServer()) )
            return;
        Mission mission = GetGame().GetMission();
        if (!mission || !mission.m_ActiveRefresherLocations)
            return;
        if (idx == -2)
        {
            idx = mission.m_ActiveRefresherLocations.Find(GetPosition());
        }
        if (idx > -1)
        {
            mission.m_ActiveRefresherLocations.Remove(idx);
        }
    }
References GetGame(), CGame::GetMission(), GetPosition, Mission::m_ActiveRefresherLocations, and mission.
Referenced by HandleRefreshers(), and ~TerritoryFlag().
SetActions() [1/4]
override void BaseBuildingBase::SetActions () inline private
Definition at line 829 of file fence.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionPlaceObject);
        AddAction(ActionFoldBaseBuildingObject);
        //AddAction(ActionDialCombinationLockOnTarget);
        //AddAction(ActionNextCombinationLockDialOnTarget);
        AddAction(ActionOpenFence);
        AddAction(ActionCloseFence);
    }
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [2/4]
override void BaseBuildingBase::SetActions () inline private
Definition at line 164 of file sheltersite.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionPlaceObject);
        AddAction(ActionFoldBaseBuildingObject);
        AddAction(ActionBuildShelter);
    }
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [3/4]
override void BaseBuildingBase::SetActions () inline private
Definition at line 471 of file totem.c.
    {
        super.SetActions();
        AddAction(ActionRaiseFlag);
        AddAction(ActionLowerFlag);
        AddAction(ActionFoldBaseBuildingObject);
    }
References ActionFoldBaseBuildingObject(), and AddAction().
SetActions() [4/4]
override void BaseBuildingBase::SetActions () inline private
Definition at line 561 of file watchtower.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionPlaceObject);
        AddAction(ActionFoldBaseBuildingObject);
    }
References ActionFoldBaseBuildingObject(), and AddAction().
SetGateState()
void BaseBuildingBase::SetGateState (int state) inline private
Definition at line 66 of file fence.c.
    {
        m_GateState = state;
        SetSynchDirty();
    }
Referenced by AfterStoreLoad(), OnPartBuiltServer(), OnPartDestroyedServer(), and OnPartDismantledServer().
SetOpenedState()
void BaseBuildingBase::SetOpenedState (bool state) inline private
Definition at line 105 of file fence.c.
    {
        m_IsOpened = state;
    }
References m_IsOpened.
Referenced by CloseFence(), and OpenFence().
SetRefresherActive()
void BaseBuildingBase::SetRefresherActive (bool state) inline private
Definition at line 196 of file totem.c.
    {
        if ( m_RefresherActive != state )
        {
            m_RefresherActive = state;
            SetSynchDirty();
            //update on refresher activation / last update on refresher deactivation
            GetCEApi().RadiusLifetimeReset(GetPosition(),GameConstants.REFRESHER_RADIUS); //TODO spammable!!!
        }
    }
References GetCEApi(), GetPosition, and GameConstants::REFRESHER_RADIUS.
Referenced by AddRefresherTime01(), and OnCEUpdate().
SetRefreshTimer01()
void BaseBuildingBase::SetRefreshTimer01 (float fraction) inline private
Definition at line 503 of file totem.c.
    {
        float temp = Math.Clamp(m_FlagRefresherMaxDuration * fraction, 0, m_FlagRefresherMaxDuration);
        m_RefresherTimeRemaining = Math.Round(temp);
    }
References Math::Clamp(), and Math::Round().
ShelterSite()
void BaseBuildingBase::ShelterSite () inline private
Definition at line 6 of file sheltersite.c.
    {
    }
SoundGateCloseEnd()
protected void BaseBuildingBase::SoundGateCloseEnd () inline private
Definition at line 748 of file fence.c.
    {
        //client or single player
        if ( !GetGame().IsDedicatedServer() )
        {
            PlaySoundSet( m_SoundGate_End, SOUND_GATE_CLOSE_END, 0.1, 0.1 );
        }
    }
References GetGame(), and PlaySoundSet().
Referenced by CheckFenceClosed().
SoundGateCloseStart()
protected void BaseBuildingBase::SoundGateCloseStart () inline private
Definition at line 739 of file fence.c.
    {
        //client or single player
        if ( !GetGame().IsDedicatedServer() )
        {
            PlaySoundSet( m_SoundGate_Start, SOUND_GATE_CLOSE_START, 0.1, 0.1 );
        }
    }
References GetGame(), and PlaySoundSet().
Referenced by CloseFence().
SoundGateOpenStart()
protected void BaseBuildingBase::SoundGateOpenStart () inline private
Definition at line 730 of file fence.c.
    {
        //client or single player
        if ( !GetGame().IsDedicatedServer() )
        {
            PlaySoundSet( m_SoundGate_Start, SOUND_GATE_OPEN_START, 0.1, 0.1 );
        }
    }
References GetGame(), and PlaySoundSet().
Referenced by OpenFence().
TerritoryFlag()
void BaseBuildingBase::TerritoryFlag () inline private
Definition at line 15 of file totem.c.
    {
        m_RefresherActive = false;
        m_RefresherActiveLocal = false;
        m_RefresherInitialized = false;
        m_RefresherTimeRemaining = 0;
        if ( GetCEApi() )
        {
            InitRefresherData();
        }
        RegisterNetSyncVariableBool("m_RefresherActive");
    }
References GetCEApi(), and InitRefresherData().
TranslateSlotFromSelection()
override bool BaseBuildingBase::TranslateSlotFromSelection (string selection_name, out int slot_id) inline private
Definition at line 819 of file fence.c.
    {
        if ( selection_name == "wall_camonet_attach" )
        {
            slot_id = InventorySlots.GetSlotIdFromString("Wall_Camonet");
            return true;
        }
        return false;
    }
References InventorySlots::GetSlotIdFromString().
UpdateBarbedWireAreaDamagePos()
void BaseBuildingBase::UpdateBarbedWireAreaDamagePos (float rotation_angle = 0, bool to_delete = false) inline private
Definition at line 573 of file fence.c.
    {
        int slot_id;
        string slot_name;
        string slot_name_mounted;
        if ( GetBarbedWire1() && GetBarbedWire1().IsMounted() )
        {
            GetBarbedWire1().GetInventory().GetCurrentAttachmentSlotInfo(slot_id,slot_name);
            slot_name_mounted = slot_name + "_Mounted";
            if (to_delete)
            {
                DestroyAreaDamage( slot_name_mounted );
            }
            else
            {
                super.CreateAreaDamage( slot_name_mounted, rotation_angle );
            }
        }
        if ( GetBarbedWire2() && GetBarbedWire2().IsMounted() )
        {
            GetBarbedWire2().GetInventory().GetCurrentAttachmentSlotInfo(slot_id,slot_name);
            slot_name_mounted = slot_name + "_Mounted";
            if (to_delete)
            {
                DestroyAreaDamage( slot_name_mounted );
            }
            else
            {
                super.CreateAreaDamage( slot_name_mounted, rotation_angle );
            }
        }
    }
References DestroyAreaDamage(), GetBarbedWire1(), and GetBarbedWire2().
Referenced by CheckFenceClosed(), CheckFenceOpened(), CloseFence(), and OpenFence().
UpdateVisuals()
override void BaseBuildingBase::UpdateVisuals () inline private
Definition at line 44 of file watchtower.c.
    {
        super.UpdateVisuals();
        SetAnimationPhase( "level_1", 0); //always visible
        SetAnimationPhase( "level_1_wall_1", 0); //always visible
        SetAnimationPhase( "level_1_wall_2", 0); //always visible
        SetAnimationPhase( "level_1_wall_3", 0); //always visible
        string part_name = "";
        bool built = false;
        for ( int i = 1; i < MAX_WATCHTOWER_FLOORS; ++i )
        {
            //roof checks
            part_name = "" + BASE_VIEW_NAME + i + BASE_ROOF_NAME;
            built = GetConstruction().IsPartConstructed(part_name);
            //Print(part_name);
            //Print(built);
            //string tmp = "";
            if ( built )
            {
                SetAnimationPhase( BASE_VIEW_NAME + (i + 1), 0); //show
                for ( int j = 1; j < MAX_WATCHTOWER_WALLS + 1; ++j )
                {
                    //tmp = BASE_VIEW_NAME + (i + 1) + BASE_WALL_NAME + j;
                    //Print(tmp);
                    SetAnimationPhase( BASE_VIEW_NAME + (i + 1) + BASE_WALL_NAME + j, 0); //show
                }
            }
            else
            {
                SetAnimationPhase( BASE_VIEW_NAME + (i + 1), 1 ); //hide
                for ( j = 1; j < MAX_WATCHTOWER_WALLS + 1; ++j )
                {
                    //tmp = BASE_VIEW_NAME + (i + 1) + BASE_WALL_NAME + j;
                    //Print(tmp);
                    SetAnimationPhase( BASE_VIEW_NAME + (i + 1) + BASE_WALL_NAME + j, 1); //hide
                }
            }
        }
    }
References BASE_ROOF_NAME, GetConstruction(), and MAX_WATCHTOWER_FLOORS.
Referenced by AfterStoreLoad(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ItemBase::OnPartBuiltServer(), OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), OnPartDismantledServer(), and ItemBase::OnSynchronizedClient().
Watchtower()
void BaseBuildingBase::Watchtower () inline private
Definition at line 17 of file watchtower.c.
    {
    }
Member Data Documentation
ATTACHMENT_BARBED_WIRE
BaseBuildingBase::ATTACHMENT_BARBED_WIRE = BarbedWire private
Definition at line 3 of file watchtower.c.
ATTACHMENT_CAMONET
BaseBuildingBase::ATTACHMENT_CAMONET = CamoNet private
Definition at line 4 of file watchtower.c.
ATTACHMENT_COMBINATION_LOCK
BaseBuildingBase::ATTACHMENT_COMBINATION_LOCK = CombinationLock private
Definition at line 20 of file fence.c.
ATTACHMENT_SLOT_COMBINATION_LOCK
const string BaseBuildingBase::ATTACHMENT_SLOT_COMBINATION_LOCK = "Att_CombinationLock" private
Definition at line 7 of file fence.c.
ATTACHMENT_WOODEN_LOG
BaseBuildingBase::ATTACHMENT_WOODEN_LOG = WoodenLog private
Definition at line 19 of file fence.c.
ATTSLOT_BARBEDWIRE_DOWN
string BaseBuildingBase::ATTSLOT_BARBEDWIRE_DOWN = "Wall_Barbedwire_1" private
Definition at line 23 of file fence.c.
ATTSLOT_BARBEDWIRE_UP
string BaseBuildingBase::ATTSLOT_BARBEDWIRE_UP = "Wall_Barbedwire_2" private
Definition at line 24 of file fence.c.
ATTSLOT_CAMONET
string BaseBuildingBase::ATTSLOT_CAMONET = "Wall_Camonet" private
Definition at line 22 of file fence.c.
BASE_ROOF_NAME
const string BaseBuildingBase::BASE_ROOF_NAME = "_roof" static private
Definition at line 13 of file watchtower.c.
Referenced by UpdateVisuals().
BASE_VIEW_NAME
const string BaseBuildingBase::BASE_VIEW_NAME = "level_" static private
Definition at line 11 of file watchtower.c.
BASE_WALL_NAME
const string BaseBuildingBase::BASE_WALL_NAME = "_wall_" static private
Definition at line 12 of file watchtower.c.
GATE_ROTATION_ANGLE_DEG
const float BaseBuildingBase::GATE_ROTATION_ANGLE_DEG = 100 private
Definition at line 13 of file fence.c.
Referenced by OpenFence().
GATE_ROTATION_TIME_APPROX
const float BaseBuildingBase::GATE_ROTATION_TIME_APPROX = 2000 private
Definition at line 14 of file fence.c.
GATE_STATE_FULL
const int BaseBuildingBase::GATE_STATE_FULL = 2 private
Definition at line 5 of file fence.c.
Referenced by CheckGateState(), and HasFullyConstructedGate().
GATE_STATE_NONE
const int BaseBuildingBase::GATE_STATE_NONE = 0 private
Definition at line 3 of file fence.c.
Referenced by CheckGateState(), HasHinges(), and OnStoreLoad().
GATE_STATE_PARTIAL
const int BaseBuildingBase::GATE_STATE_PARTIAL = 1 private
Definition at line 4 of file fence.c.
Referenced by CheckGateState().
m_FlagRefresherFrequency
protected int BaseBuildingBase::m_FlagRefresherFrequency = GameConstants.REFRESHER_FREQUENCY_DEFAULT private
Definition at line 12 of file totem.c.
m_FlagRefresherMaxDuration
protected int BaseBuildingBase::m_FlagRefresherMaxDuration = GameConstants.REFRESHER_MAX_DURATION_DEFAULT private
Definition at line 13 of file totem.c.
Referenced by GetRefresherTime01().
m_GateState
protected int BaseBuildingBase::m_GateState = 0 private
Definition at line 31 of file fence.c.
Referenced by GetGateState().
m_IsOpened
protected bool BaseBuildingBase::m_IsOpened = false private
Definition at line 29 of file fence.c.
Referenced by IsOpened(), and OnVariablesSynchronized().
m_IsOpenedClient
protected bool BaseBuildingBase::m_IsOpenedClient = false private
Definition at line 30 of file fence.c.
m_RefresherActive
bool BaseBuildingBase::m_RefresherActive private
Definition at line 6 of file totem.c.
Referenced by OnVariablesSynchronized().
m_RefresherActiveLocal
bool BaseBuildingBase::m_RefresherActiveLocal private
Definition at line 7 of file totem.c.
m_RefresherInitialized
bool BaseBuildingBase::m_RefresherInitialized private
Definition at line 8 of file totem.c.
m_RefresherTimeRemaining
int BaseBuildingBase::m_RefresherTimeRemaining private
Definition at line 9 of file totem.c.
m_RefreshTimeCounter
int BaseBuildingBase::m_RefreshTimeCounter private
Definition at line 10 of file totem.c.
m_SoundGate_End
protected EffectSound BaseBuildingBase::m_SoundGate_End private
Definition at line 34 of file fence.c.
m_SoundGate_Start
protected EffectSound BaseBuildingBase::m_SoundGate_Start private
Definition at line 33 of file fence.c.
m_ToDiscard
protected bool BaseBuildingBase::m_ToDiscard = false private
Definition at line 28 of file fence.c.
MAX_ACTION_DETECTION_ANGLE_RAD
const float BaseBuildingBase::MAX_ACTION_DETECTION_ANGLE_RAD = 1.3 private
Definition at line 16 of file fence.c.
MAX_ACTION_DETECTION_DISTANCE
const float BaseBuildingBase::MAX_ACTION_DETECTION_DISTANCE = 2.0 private
Definition at line 17 of file fence.c.
MAX_FLOOR_VERTICAL_DISTANCE
const float BaseBuildingBase::MAX_FLOOR_VERTICAL_DISTANCE = 0.5 private
Definition at line 6 of file watchtower.c.
MAX_WATCHTOWER_FLOORS
const int BaseBuildingBase::MAX_WATCHTOWER_FLOORS = 3 static private
Definition at line 14 of file watchtower.c.
Referenced by UpdateVisuals().
MAX_WATCHTOWER_WALLS
const int BaseBuildingBase::MAX_WATCHTOWER_WALLS = 3 static private
Definition at line 15 of file watchtower.c.
Referenced by OnDebugSpawn().
MIN_ACTION_DETECTION_ANGLE_RAD
const float BaseBuildingBase::MIN_ACTION_DETECTION_ANGLE_RAD = 0.35 private
Definition at line 8 of file watchtower.c.
SOUND_GATE_CLOSE_END
const string BaseBuildingBase::SOUND_GATE_CLOSE_END = "DoorWoodTowerClose_end_SoundSet" private
Definition at line 10 of file fence.c.
SOUND_GATE_CLOSE_START
const string BaseBuildingBase::SOUND_GATE_CLOSE_START = "DoorWoodTowerClose_start_SoundSet" private
Definition at line 9 of file fence.c.
SOUND_GATE_OPEN_START
const string BaseBuildingBase::SOUND_GATE_OPEN_START = "DoorWoodTowerOpen_SoundSet" private
Definition at line 8 of file fence.c.