DayzKode: BackendApi Class Reference
BackendApi Class Reference
Private Member Functions
private void BackendApi ()
proto native void FeedbackMessage (BackendCallback cb, JsonApiStruct dataObject, string message)
Send feedback message and/ or script object with whatever data on it (additionally it is possible to handle callback as well)
proto native string GetCredentialsItem (EBackendCredentials item)
Get credentials value per item.
string GetErrorCode (int code)
Error code to string.
proto native bool Initiate ()
Initiate backend - request processing.
proto native bool IsBusy ()
Backend is busy - authentication in process.
proto native bool IsDisconnected ()
Backend offline - authentication may be initiated.
proto native bool IsRuntime ()
Backend fully working and initialized.
void OnCannotInitiate (int code)
Called when initiate cannot be called.
void OnCannotShutdown (int code)
Called when shutdown cannot be proceeded.
void OnFail (string step)
Called when step failed.
void OnSuccess (string step)
Called when step was successfully proceeded.
proto native void PlayerRequest (int request, BackendCallback cb, JsonApiStruct dataObject, int iPlayerId)
Ask player request with callback result from controller (Lobby)
proto native void Request (int request, BackendCallback cb, JsonApiStruct dataObject)
Ask specific request with callback result.
proto native void SetCredentialsItem (EBackendCredentials item, string str)
Set credentials value per item.
proto native bool Shutdown ()
Shutdown backend - request processing.
proto native void VerifyCredentials ()
Invoke credentials update (authenticate with new name+password)
private void ~BackendApi ()
Detailed Description
Definition at line 129 of file backendapi.c.
Constructor & Destructor Documentation
BackendApi()
private void BackendApi::BackendApi () inline private
Definition at line 131 of file backendapi.c.
{}
~BackendApi()
private void BackendApi::~BackendApi () inline private
Definition at line 132 of file backendapi.c.
{}
Member Function Documentation
FeedbackMessage()
proto native void BackendApi::FeedbackMessage (BackendCallback cb, JsonApiStruct dataObject, string message) private
Send feedback message and/ or script object with whatever data on it (additionally it is possible to handle callback as well)
Parameters
cb Is script callback where you will recieve result/ error or even data when request finsihes
data Is optional callback when request uses or response return Json data and you want to work with object
message Is custom
GetCredentialsItem()
proto native string BackendApi::GetCredentialsItem (EBackendCredentials item) private
Get credentials value per item.
Parameters
item Is type of EBackendCredentials parameter you want to read
GetErrorCode()
string BackendApi::GetErrorCode (int code) inline private
Error code to string.
Definition at line 159 of file backendapi.c.
    {
        string result;
        if ( code == EBackendError.EBERR_OK )
            result = "OK";
        else if ( code == EBackendError.EBERR_UNKNOWN )
            result = "Offline";
        else if ( code == EBackendError.EBERR_DISABLED )
            result = "Communication Disabled";
        else if ( code == EBackendError.EBERR_INVALID_STATE )
            result = "Cannot be called from current state";
        else if ( code == EBackendError.EBERR_BUSY )
            result = "Busy processing requests";
        else if ( code == EBackendError.EBERR_ALREADY_OFFLINE )
            result = "Already disconnected";
        else if ( code == EBackendError.EBERR_ALREADY_ONLINE )
            result = "Already connected";
        else if ( code == EBackendError.EBERR_LOGIN_FAILED )
            result = "Failed to logon";
        else if ( code == EBackendError.EBERR_AUTH_FAILED )
            result = "Failed to Authenticate";
        else
            result = "*";
        return result;
    }
Referenced by OnCannotInitiate(), and OnCannotShutdown().
Initiate()
proto native bool BackendApi::Initiate () private
Initiate backend - request processing.
IsBusy()
proto native bool BackendApi::IsBusy () private
Backend is busy - authentication in process.
IsDisconnected()
proto native bool BackendApi::IsDisconnected () private
Backend offline - authentication may be initiated.
IsRuntime()
proto native bool BackendApi::IsRuntime () private
Backend fully working and initialized.
OnCannotInitiate()
void BackendApi::OnCannotInitiate (int code) inline private
Called when initiate cannot be called.
Definition at line 190 of file backendapi.c.
    {
        Print("!!! [Backend] Cannot Initiate: "+ GetErrorCode(code));
    }
References GetErrorCode(), and Print().
OnCannotShutdown()
void BackendApi::OnCannotShutdown (int code) inline private
Called when shutdown cannot be proceeded.
Definition at line 198 of file backendapi.c.
    {
        Print("!!! [Backend] Cannot Shutdown: "+ GetErrorCode(code));
    }
References GetErrorCode(), and Print().
OnFail()
void BackendApi::OnFail (string step) inline private
Called when step failed.
Definition at line 214 of file backendapi.c.
    {
        Print( "[Backend] Failed to Proceed: " + step );
    }
References Print().
OnSuccess()
void BackendApi::OnSuccess (string step) inline private
Called when step was successfully proceeded.
Definition at line 206 of file backendapi.c.
    {
        Print( "[Backend] Successfully Solicited: " + step );
    }
References Print().
PlayerRequest()
proto native void BackendApi::PlayerRequest (int request, BackendCallback cb, JsonApiStruct dataObject, int iPlayerId) private
Ask player request with callback result from controller (Lobby)
Parameters
request Is type of request, which is EBackendRequest
cb Is script callback where you will recieve result/ error or even data when request finsihes
data Is optional callback when request uses or response return Json data and you want to work with object
iPlayerId Is Player Id used on player identity
Request()
proto native void BackendApi::Request (int request, BackendCallback cb, JsonApiStruct dataObject) private
Ask specific request with callback result.
Parameters
request Is type of request, which is EBackendRequest
cb Is script callback where you will recieve result/ error or even data when request finsihes
data Is optional callback when request uses or response return Json data and you want to work with object
SetCredentialsItem()
proto native void BackendApi::SetCredentialsItem (EBackendCredentials item, string str) private
Set credentials value per item.
Parameters
item Is type of EBackendCredentials parameter you want to set
str Is value itself
Shutdown()
proto native bool BackendApi::Shutdown () private
Shutdown backend - request processing.
VerifyCredentials()
proto native void BackendApi::VerifyCredentials () private
Invoke credentials update (authenticate with new name+password)