DayzKode: TriggerInsider Class Reference
TriggerInsider Class Reference
The object which is in a trigger and its metadata.
Private Member Functions
Object GetObject ()
void TriggerInsider (Object obj)
void ~TriggerInsider ()
Private Attributes
ref OLinkT insider
float lastUpdated
Last time the object was updated in seconds, is used for calculating deltaTime.
protected Object m_Object
Object that data belongs to.
float timeEntered
Time the object was first seen in seconds.
int timeStamp
Last time the object was seen in ms.
Detailed Description
The object which is in a trigger and its metadata.
Definition at line 2 of file trigger.c.
Constructor & Destructor Documentation
TriggerInsider()
void TriggerInsider::TriggerInsider (Object obj) inline private
Definition at line 18 of file trigger.c.
    {
        insider = new OLinkT(obj);
        m_Object = obj;
    }
References insider, and m_Object.
~TriggerInsider()
void TriggerInsider::~TriggerInsider () inline private
Definition at line 24 of file trigger.c.
    {
    }
Member Function Documentation
GetObject()
Object TriggerInsider::GetObject () inline private
Definition at line 28 of file trigger.c.
    {
        return m_Object;
    }
References m_Object.
Referenced by TriggerEvents::Enter(), EvaluateDamageInternal(), Trigger::GetInsiderForObject(), Trigger::GetInsiderIndexForObject(), TriggerEvents::Leave(), Trigger::OnEnterBeginEvent(), OnEnterClientEvent(), EffectTrigger::OnEnterClientEvent(), EffectTrigger::OnEnterServerEvent(), TrapTrigger::OnEnterServerEvent(), OnEvaluateDamage(), AreaDamageLoopedDeferred_NoVehicle::OnEvaluateDamageEx(), Trigger::OnLeaveBeginEvent(), EffectTrigger::OnLeaveClientEvent(), OnLeaveClientEvent(), EffectTrigger::OnLeaveServerEvent(), TrapTrigger::OnLeaveServerEvent(), EffectTrigger::OnStayServerEvent(), Trigger::RemoveInsider(), Trigger::RemoveInsiderByObject(), ShouldRemoveInsider(), EffectTrigger::ShouldRemoveInsider(), TriggerEvents::Stay(), AreaDamageTriggerBase::UpdateInsiders(), and Trigger::UpdateInsiders().
Member Data Documentation
insider
ref OLinkT TriggerInsider::insider private
Definition at line 4 of file trigger.c.
Referenced by TriggerInsider().
lastUpdated
float TriggerInsider::lastUpdated private
Last time the object was updated in seconds, is used for calculating deltaTime.
Definition at line 16 of file trigger.c.
Referenced by Trigger::AddInsider(), AreaDamageLoopedDeferred::CalculateDamageScale(), CalculateDamageScale(), and Trigger::UpdateInsiders().
m_Object
protected Object TriggerInsider::m_Object private
Object that data belongs to.
Definition at line 7 of file trigger.c.
Referenced by GetObject(), and TriggerInsider().
timeEntered
float TriggerInsider::timeEntered private
Time the object was first seen in seconds.
Definition at line 13 of file trigger.c.
Referenced by Trigger::AddInsider(), AreaDamageLoopedDeferred::CalculateDamageScale(), and CalculateDamageScale().
timeStamp
int TriggerInsider::timeStamp private
Last time the object was seen in ms.
Definition at line 10 of file trigger.c.
Referenced by Trigger::AddInsider(), and AreaDamageTriggerBase::UpdateInsiders().