DayzKode: AIBehaviourHLData Class Reference
AIBehaviourHLData Class Reference
Private Member Functions
private void AIBehaviourHLData ()
void OnParseConfig ()
proto native void ParseAlertLevel (string name)
proto native void ParseBehaviourSlot (string name)
proto native float ReadParamValue (string paramName, float defValue)
private void ~AIBehaviourHLData ()
Detailed Description
Definition at line 26 of file aibehaviour.c.
Constructor & Destructor Documentation
AIBehaviourHLData()
private void AIBehaviourHLData::AIBehaviourHLData () inline private
Definition at line 28 of file aibehaviour.c.
{}
~AIBehaviourHLData()
private void AIBehaviourHLData::~AIBehaviourHLData () inline private
Definition at line 29 of file aibehaviour.c.
{}
Member Function Documentation
OnParseConfig()
void AIBehaviourHLData::OnParseConfig () private
ParseAlertLevel()
proto native void AIBehaviourHLData::ParseAlertLevel (string name) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().
ParseBehaviourSlot()
proto native void AIBehaviourHLData::ParseBehaviourSlot (string name) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().
ReadParamValue()
proto native float AIBehaviourHLData::ReadParamValue (string paramName, float defValue) private
Referenced by AIBehaviourHLDataZombie2::OnParseConfig().