DayzKode: BleedingNotfr Class Reference
BleedingNotfr Class Reference
Private Member Functions
void BleedingNotfr (NotifiersManager manager)
override void DisplayBadge ()
override int GetNotifierType ()
override void HideBadge ()
Detailed Description
Definition at line 1 of file bleedingnotfr.c.
Constructor & Destructor Documentation
BleedingNotfr()
void BleedingNotfr::BleedingNotfr (NotifiersManager manager) inline private
Definition at line 3 of file bleedingnotfr.c.
    {
        m_TendencyBufferSize = 8;
        m_Active = false;
    }
References NotifierBase::m_Active, and NotifierBase::m_TendencyBufferSize.
Member Function Documentation
DisplayBadge()
override void BleedingNotfr::DisplayBadge () inline private
Definition at line 14 of file bleedingnotfr.c.
    {
        DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_BLEEDING));
        if( dis_elm )
        {
            dis_elm.SetLevel(eBadgeLevel.FIRST);
        }
    }
References GetElement(), and NotifierBase::GetVirtualHud().
GetNotifierType()
override int BleedingNotfr::GetNotifierType () inline private
Definition at line 9 of file bleedingnotfr.c.
    {
        return eNotifiers.NTF_BLEEDISH;
    }
HideBadge()
override void BleedingNotfr::HideBadge () inline private
Definition at line 24 of file bleedingnotfr.c.
    {
        DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_BLEEDING));
        if( dis_elm )
        {
            dis_elm.SetLevel(eBadgeLevel.NONE);
        }
    }
References GetElement(), and NotifierBase::GetVirtualHud().