DayzKode: ImprovisedExplosive Class Reference
ImprovisedExplosive Class Reference
Private Member Functions
override bool CanBeArmed ()
override bool CanBeDisarmed ()
override bool CanDisplayAttachmentSlot (int slot_id)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanRemoveFromHands (EntityAI parent)
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EOnInit (IEntity other, int extra)
override EntityAI GetPairDevice ()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override bool HasLockedTriggerSlots ()
void ImprovisedExplosive ()
override protected void InitiateExplosion ()
not exploding itself, rely on attached explosives
override bool IsDeployable ()
override bool IsTakeable ()
override bool IsTimerDetonable ()
override void LockTriggerSlots ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnDisarmed (bool pWithTool)
protected void OnTriggerAttached (EntityAI entity)
protected void OnTriggerDetached (EntityAI entity)
override void OnVariablesSynchronized ()
override void PairRemote (notnull EntityAI trigger)
override void SetActions ()
override void UnlockTriggerSlots ()
override void UnpairRemote ()
override void UpdateLED (int pState)
protected void UpdateVisuals (EntityAI entity)
Private Attributes
protected const string ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock"
protected const string ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty"
protected const string ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote"
protected const string ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer"
protected ref RemotelyActivatedItemBehaviour m_RAIB
protected const int SLOT_EXPLOSIVE_COUNT = 2
protected const string SLOT_EXPLOSIVES [SLOT_EXPLOSIVE_COUNT]
protected const string SLOT_TRIGGERS [SLOT_TRIGGERS_COUNT]
protected const int SLOT_TRIGGERS_COUNT = 3
protected const float TIME_TRIGGER_DELAY_SECS = 0.3
protected const float TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1
protected const float TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0
Static Private Attributes
static protected const string SLOT_EXPLOSIVE_A = "IEDExplosiveA"
static protected const string SLOT_EXPLOSIVE_B = "IEDExplosiveB"
static protected const string SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock"
static protected const string SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer"
static protected const string SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver"
Detailed Description
Definition at line 1 of file improvisedexplosive.c.
Constructor & Destructor Documentation
ImprovisedExplosive()
void ImprovisedExplosive::ImprovisedExplosive () inline private
Definition at line 34 of file improvisedexplosive.c.
    {
        m_RAIB = new RemotelyActivatedItemBehaviour(this);
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
    }
References m_RAIB.
Member Function Documentation
CanBeArmed()
override bool ImprovisedExplosive::CanBeArmed () inline private
Definition at line 128 of file improvisedexplosive.c.
    {
        if (GetArmed())
        {
            return false;
        }
        if (!HasLockedTriggerSlots())
        {
            return false;
        }
        for (int i = 0; i < SLOT_EXPLOSIVE_COUNT; i++)
        {
            EntityAI explosive = GetInventory().FindAttachmentByName(SLOT_EXPLOSIVES[i]);
            if (explosive)
            {
                return true;
            }
        }
        return false;
    }
References GetArmed(), HasLockedTriggerSlots(), SLOT_EXPLOSIVE_COUNT, and SLOT_EXPLOSIVES.
CanBeDisarmed()
override bool ImprovisedExplosive::CanBeDisarmed () inline private
Definition at line 152 of file improvisedexplosive.c.
    {
        return true;
    }
CanDisplayAttachmentSlot()
override bool ImprovisedExplosive::CanDisplayAttachmentSlot (int slot_id) inline private
Definition at line 185 of file improvisedexplosive.c.
    {
        string slotName = InventorySlots.GetSlotName(slot_id);
        switch (slotName)
        {
        case SLOT_TRIGGER_ALARM_CLOCK:
        case SLOT_TRIGGER_KITCHEN_TIMER:
        case SLOT_TRIGGER_REMOTE:
            return FindAttachmentBySlotName(slotName) != null;
        break;
        }
        return true;
    }
References InventorySlots::GetSlotName(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
CanPutIntoHands()
override bool ImprovisedExplosive::CanPutIntoHands (EntityAI parent) inline private
Definition at line 157 of file improvisedexplosive.c.
    {
        return IsTakeable();
    }
References IsTakeable().
CanReceiveAttachment()
override bool ImprovisedExplosive::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 167 of file improvisedexplosive.c.
    {
        InventoryLocation il = new InventoryLocation();
        GetInventory().GetCurrentInventoryLocation(il);
        for (int i = 0; i < SLOT_TRIGGERS_COUNT; i++)
        {
            if (slotId == InventorySlots.GetSlotIdFromString(SLOT_TRIGGERS[i]))
            {
                if (il.GetType() == InventoryLocationType.HANDS)
                {
                    return false;
                }
            }
        }
        return !GetArmed();
    }
References GetArmed(), InventorySlots::GetSlotIdFromString(), InventoryLocation::GetType(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
CanRemoveFromHands()
override bool ImprovisedExplosive::CanRemoveFromHands (EntityAI parent) inline private
Definition at line 162 of file improvisedexplosive.c.
    {
        return IsTakeable();
    }
References IsTakeable().
EEHealthLevelChanged()
override void ImprovisedExplosive::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 224 of file improvisedexplosive.c.
    {
        super.EEHealthLevelChanged(oldLevel, newLevel, zone);
        if (GetGame().IsServer())
        {
            if (newLevel == GameConstants.STATE_RUINED)
            {
                for (int attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
                {
                    ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
                    if (attachment)
                    {
                        attachment.UnlockFromParent();
                        attachment.SetHealth("", "", 0.0);
                    }
                }
                SetArmed(false);
                SetTakeable(true);
            }
        }
    }
References GetGame(), SetArmed(), SetTakeable(), and GameConstants::STATE_RUINED.
EEItemAttached()
override void ImprovisedExplosive::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 334 of file improvisedexplosive.c.
    {
        super.EEItemAttached(item, slot_name);
        switch (slot_name)
        {
        case SLOT_TRIGGER_ALARM_CLOCK:
        case SLOT_TRIGGER_KITCHEN_TIMER:
        case SLOT_TRIGGER_REMOTE:
            OnTriggerAttached(FindAttachmentBySlotName(slot_name));
        break;
        }
    }
References OnTriggerAttached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemDetached()
override void ImprovisedExplosive::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 348 of file improvisedexplosive.c.
    {
        super.EEItemDetached(item, slot_name);
        switch (slot_name)
        {
        case SLOT_TRIGGER_ALARM_CLOCK:
        case SLOT_TRIGGER_KITCHEN_TIMER:
        case SLOT_TRIGGER_REMOTE:
            OnTriggerDetached(FindAttachmentBySlotName(slot_name));
        break;
        }
    }
References OnTriggerDetached(), SLOT_TRIGGER_ALARM_CLOCK, SLOT_TRIGGER_KITCHEN_TIMER, and SLOT_TRIGGER_REMOTE.
EEItemLocationChanged()
override void ImprovisedExplosive::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 93 of file improvisedexplosive.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (m_RAIB)
        {
            m_RAIB.Pair();
        }
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EOnInit()
override void ImprovisedExplosive::EOnInit (IEntity other, int extra) inline private
Definition at line 42 of file improvisedexplosive.c.
    {
        LockTriggerSlots();
    }
References LockTriggerSlots().
GetPairDevice()
override EntityAI ImprovisedExplosive::GetPairDevice () inline private
Definition at line 123 of file improvisedexplosive.c.
    {
        return m_RAIB.GetPairDevice();
    }
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by UnpairRemote().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour ImprovisedExplosive::GetRemotelyActivatedItemBehaviour () inline private
Definition at line 103 of file improvisedexplosive.c.
    {
        return m_RAIB;
    }
References m_RAIB.
HasLockedTriggerSlots()
override bool ImprovisedExplosive::HasLockedTriggerSlots () inline private
Definition at line 47 of file improvisedexplosive.c.
    {
        for (int i = 0; i < SLOT_TRIGGERS_COUNT; i++)
        {
            return GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGERS[i]));
        }
        return false;
    }
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
Referenced by CanBeArmed().
InitiateExplosion()
override protected void ImprovisedExplosive::InitiateExplosion () private
not exploding itself, rely on attached explosives
IsDeployable()
override bool ImprovisedExplosive::IsDeployable () inline private
Definition at line 211 of file improvisedexplosive.c.
    {
        return !GetArmed();
    }
References GetArmed().
IsTakeable()
override bool ImprovisedExplosive::IsTakeable () inline private
Definition at line 206 of file improvisedexplosive.c.
    {
        return !GetArmed() && super.IsTakeable();
    }
References GetArmed().
Referenced by CanPutIntoHands(), and CanRemoveFromHands().
IsTimerDetonable()
override bool ImprovisedExplosive::IsTimerDetonable () inline private
Definition at line 201 of file improvisedexplosive.c.
    {
        return true;
    }
LockTriggerSlots()
override void ImprovisedExplosive::LockTriggerSlots () inline private
Definition at line 57 of file improvisedexplosive.c.
    {
        for (int i = 0; i < SLOT_TRIGGERS_COUNT; i++)
        {
            GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGERS[i]), true);
        }
    }
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
Referenced by EOnInit(), and OnDisarmed().
OnActivatedByItem()
override void ImprovisedExplosive::OnActivatedByItem (notnull ItemBase item) inline private
cache attachments
unlock attachments first
triggers specific handling
go through attached explosives
defer delete to allow ringing
final traverse - attached explosives activation
defer damage to trigger attachments to allow ringing
Definition at line 248 of file improvisedexplosive.c.
    {
        if (GetGame().IsServer() && GetArmed())
        {
            ItemBase attachment;
            bool isTimeTriggered = false;
            array<ItemBase> attachmentsCache = new array<ItemBase>();
            int attachmentIdx;
            for (attachmentIdx = 0; attachmentIdx < GetInventory().AttachmentCount(); attachmentIdx++)
            {
                attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
                if (attachment)
                {
                    attachmentsCache.Insert(attachment);
                }
            }
            for (attachmentIdx = 0; attachmentIdx < attachmentsCache.Count(); attachmentIdx++)
            {
                attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(attachmentIdx));
                if (attachmentsCache[attachmentIdx])
                {
                    attachmentsCache[attachmentIdx].UnlockFromParent();
                }
            }
            for (attachmentIdx = 0; attachmentIdx < attachmentsCache.Count(); attachmentIdx++)
            {
                attachment = ItemBase.Cast(attachmentsCache[attachmentIdx]);
                if (attachment.IsInherited(ClockBase))
                {
                    isTimeTriggered = true;
                }
            }
            for (attachmentIdx = 0; attachmentIdx < attachmentsCache.Count(); attachmentIdx++)
            {
                attachment = ItemBase.Cast(attachmentsCache[attachmentIdx]);
                if (attachment && !attachment.IsAnyInherited({RemoteDetonator, ClockBase}))
                {
                    GetInventory().DropEntityInBounds(InventoryMode.SERVER, this, attachment, "0.5 0 0.5", 0, 0, 0);
                    attachment.SetAnimationPhase(ANIM_PHASE_VISIBILITY, 1.0);
                    attachment.SetTakeable(false);
                }
            }
            float delayFor = TIME_TRIGGER_INITIAL_DELAY_SECS;
            if (isTimeTriggered)
            {
                delayFor = TIME_TRIGGER_INITIAL_DELAY_SECS + TIME_TRIGGER_TIMER_BASED_DELAY_SECS;
                GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeleteSafe, delayFor * 1000, false);
            }
            else
            {
                DeleteSafe();
            }
            for (attachmentIdx = 0; attachmentIdx < attachmentsCache.Count(); attachmentIdx++)
            {
                attachment = ItemBase.Cast(attachmentsCache[attachmentIdx]);
                if (attachment.IsAnyInherited({RemoteDetonator,ClockBase}))
                {
                    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(attachment.SetHealth, delayFor * 1000, false, "", "", 0.0);
                }
                if (attachment && !attachment.IsAnyInherited({RemoteDetonator, ClockBase}))
                {
                    Param1<ItemBase> params = new Param1<ItemBase>(attachment);
                    GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLaterByName(attachment, "OnActivatedByItem", delayFor * 1000, false, params);
                    delayFor += TIME_TRIGGER_DELAY_SECS;
                }
            }
        }
    }
References ANIM_PHASE_VISIBILITY, CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ScriptCallQueue::CallLaterByName(), ClockBase(), GetArmed(), CGame::GetCallQueue(), GetGame(), TIME_TRIGGER_DELAY_SECS, TIME_TRIGGER_INITIAL_DELAY_SECS, and TIME_TRIGGER_TIMER_BASED_DELAY_SECS.
OnDisarmed()
override void ImprovisedExplosive::OnDisarmed (bool pWithTool) inline private
Definition at line 362 of file improvisedexplosive.c.
    {
        super.OnDisarmed(pWithTool);
        UnpairRemote();
        for (int att = 0; att < GetInventory().AttachmentCount(); att++)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
            if (attachment)
            {
                attachment.UnlockFromParent();
                if (attachment.IsInherited(ClockBase))
                {
                    if (pWithTool)
                    {
                        GetInventory().DropEntity(InventoryMode.SERVER, this, attachment);
                    }
                }
                if (attachment.IsInherited(RemoteDetonator))
                {
                    if (pWithTool)
                    {
                        GetInventory().DropEntity(InventoryMode.SERVER, this, attachment);
                        attachment.SetHealth("", "", 0.0);
                    }
                    else
                    {
                        attachment.Delete();
                    }
                }
            }
        }
        LockTriggerSlots();
        SetTakeable(true);
    }
References ClockBase(), LockTriggerSlots(), SetTakeable(), and UnpairRemote().
OnTriggerAttached()
protected void ImprovisedExplosive::OnTriggerAttached (EntityAI entity) inline private
Definition at line 411 of file improvisedexplosive.c.
    {
        UpdateVisuals(entity);
        UpdateLED(ERemoteDetonatorLEDState.LIT);
        if (entity.IsInherited(ClockBase))
        {
            Arm();
        }
        for (int att = 0; att < GetInventory().AttachmentCount(); att++)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(att));
            if (attachment)
            {
                attachment.LockToParent();
            }
        }
    }
References Arm(), ClockBase(), UpdateLED(), and UpdateVisuals().
Referenced by EEItemAttached().
OnTriggerDetached()
protected void ImprovisedExplosive::OnTriggerDetached (EntityAI entity) inline private
Definition at line 431 of file improvisedexplosive.c.
    {
        UpdateVisuals(null);
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
References UpdateLED(), and UpdateVisuals().
Referenced by EEItemDetached().
OnVariablesSynchronized()
override void ImprovisedExplosive::OnVariablesSynchronized () inline private
Definition at line 73 of file improvisedexplosive.c.
    {
        super.OnVariablesSynchronized();
        if (m_RAIB)
        {
            m_RAIB.OnVariableSynchronized();
        }
        for (int i = 0; i < SLOT_TRIGGERS_COUNT; i++)
        {
            EntityAI trigger = GetInventory().FindAttachmentByName(SLOT_TRIGGERS[i]);
            if (trigger)
            {
                UpdateVisuals(trigger);
                break;
            }
        }
    }
References m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), SLOT_TRIGGERS, SLOT_TRIGGERS_COUNT, and UpdateVisuals().
PairRemote()
override void ImprovisedExplosive::PairRemote (notnull EntityAI trigger) inline private
Definition at line 108 of file improvisedexplosive.c.
    {
        m_RAIB.Pair(trigger);
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
SetActions()
override void ImprovisedExplosive::SetActions () inline private
Definition at line 216 of file improvisedexplosive.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), and AddAction().
UnlockTriggerSlots()
override void ImprovisedExplosive::UnlockTriggerSlots () inline private
Definition at line 65 of file improvisedexplosive.c.
    {
        for (int i = 0; i < SLOT_TRIGGERS_COUNT; i++)
        {
            GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(SLOT_TRIGGERS[i]), false);
        }
    }
References InventorySlots::GetSlotIdFromString(), SLOT_TRIGGERS, and SLOT_TRIGGERS_COUNT.
UnpairRemote()
override void ImprovisedExplosive::UnpairRemote () inline private
Definition at line 113 of file improvisedexplosive.c.
    {
        if (GetPairDevice())
        {
            GetPairDevice().UnpairRemote();
        }
        m_RAIB.Unpair();
    }
References GetPairDevice(), m_RAIB, and RemotelyActivatedItemBehaviour::Unpair().
Referenced by OnDisarmed().
UpdateLED()
override void ImprovisedExplosive::UpdateLED (int pState) inline private
Definition at line 402 of file improvisedexplosive.c.
    {
        RemoteDetonatorReceiver receiver = RemoteDetonatorReceiver.Cast(FindAttachmentBySlotName(SLOT_TRIGGER_REMOTE));
        if (receiver)
        {
            receiver.UpdateLED(pState, true);
        }
    }
References RemoteDetonatorReceiver(), and SLOT_TRIGGER_REMOTE.
Referenced by OnTriggerAttached(), and OnTriggerDetached().
UpdateVisuals()
protected void ImprovisedExplosive::UpdateVisuals (EntityAI entity) inline private
Definition at line 437 of file improvisedexplosive.c.
    {
        if (entity)
        {
            if (entity.IsInherited(RemoteDetonator))
            {
                SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 0.0);
            }
            else if (entity.IsInherited(AlarmClock_ColorBase))
            {
                SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 0.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
            }
            else if (entity.IsInherited(KitchenTimer))
            {
                SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 0.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
                SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
            }
        }
        else
        {
            SetAnimationPhase(ANIM_PHASE_TRIGGER_EMPTY, 0.0);
            SetAnimationPhase(ANIM_PHASE_TRIGGER_TIMER, 1.0);
            SetAnimationPhase(ANIM_PHASE_TRIGGER_CLOCK, 1.0);
            SetAnimationPhase(ANIM_PHASE_TRIGGER_REMOTE, 1.0);
        }
    }
References ANIM_PHASE_TRIGGER_CLOCK, ANIM_PHASE_TRIGGER_EMPTY, ANIM_PHASE_TRIGGER_REMOTE, and ANIM_PHASE_TRIGGER_TIMER.
Member Data Documentation
ANIM_PHASE_TRIGGER_CLOCK
protected const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_CLOCK = "TriggerClock" private
Definition at line 29 of file improvisedexplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_EMPTY
protected const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_EMPTY = "TriggerEmpty" private
Definition at line 27 of file improvisedexplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_REMOTE
protected const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_REMOTE = "TriggerRemote" private
Definition at line 30 of file improvisedexplosive.c.
Referenced by UpdateVisuals().
ANIM_PHASE_TRIGGER_TIMER
protected const string ImprovisedExplosive::ANIM_PHASE_TRIGGER_TIMER = "TriggerTimer" private
Definition at line 28 of file improvisedexplosive.c.
Referenced by UpdateVisuals().
m_RAIB
protected ref RemotelyActivatedItemBehaviour ImprovisedExplosive::m_RAIB private
Definition at line 32 of file improvisedexplosive.c.
Referenced by EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), ImprovisedExplosive(), OnVariablesSynchronized(), PairRemote(), and UnpairRemote().
SLOT_EXPLOSIVE_A
protected const string ImprovisedExplosive::SLOT_EXPLOSIVE_A = "IEDExplosiveA" static private
Definition at line 11 of file improvisedexplosive.c.
SLOT_EXPLOSIVE_B
protected const string ImprovisedExplosive::SLOT_EXPLOSIVE_B = "IEDExplosiveB" static private
Definition at line 12 of file improvisedexplosive.c.
SLOT_EXPLOSIVE_COUNT
protected const int ImprovisedExplosive::SLOT_EXPLOSIVE_COUNT = 2 private
Definition at line 14 of file improvisedexplosive.c.
Referenced by CanBeArmed().
SLOT_EXPLOSIVES
protected const string ImprovisedExplosive::SLOT_EXPLOSIVES[SLOT_EXPLOSIVE_COUNT] private
Initial value:
= {
        SLOT_EXPLOSIVE_A,
        SLOT_EXPLOSIVE_B
    }
Definition at line 15 of file improvisedexplosive.c.
Referenced by CanBeArmed().
SLOT_TRIGGER_ALARM_CLOCK
protected const string ImprovisedExplosive::SLOT_TRIGGER_ALARM_CLOCK = "TriggerAlarmClock" static private
Definition at line 7 of file improvisedexplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_KITCHEN_TIMER
protected const string ImprovisedExplosive::SLOT_TRIGGER_KITCHEN_TIMER = "TriggerKitchenTimer" static private
Definition at line 8 of file improvisedexplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), and EEItemDetached().
SLOT_TRIGGER_REMOTE
protected const string ImprovisedExplosive::SLOT_TRIGGER_REMOTE = "TriggerRemoteDetonator_Receiver" static private
Definition at line 9 of file improvisedexplosive.c.
Referenced by CanDisplayAttachmentSlot(), EEItemAttached(), EEItemDetached(), and UpdateLED().
SLOT_TRIGGERS
protected const string ImprovisedExplosive::SLOT_TRIGGERS[SLOT_TRIGGERS_COUNT] private
Initial value:
= {
        SLOT_TRIGGER_ALARM_CLOCK,
        SLOT_TRIGGER_KITCHEN_TIMER,
        SLOT_TRIGGER_REMOTE
    }
Definition at line 21 of file improvisedexplosive.c.
Referenced by CanReceiveAttachment(), HasLockedTriggerSlots(), LockTriggerSlots(), OnVariablesSynchronized(), and UnlockTriggerSlots().
SLOT_TRIGGERS_COUNT
protected const int ImprovisedExplosive::SLOT_TRIGGERS_COUNT = 3 private
Definition at line 20 of file improvisedexplosive.c.
Referenced by CanReceiveAttachment(), HasLockedTriggerSlots(), LockTriggerSlots(), OnVariablesSynchronized(), and UnlockTriggerSlots().
TIME_TRIGGER_DELAY_SECS
protected const float ImprovisedExplosive::TIME_TRIGGER_DELAY_SECS = 0.3 private
Definition at line 5 of file improvisedexplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_INITIAL_DELAY_SECS
protected const float ImprovisedExplosive::TIME_TRIGGER_INITIAL_DELAY_SECS = 0.1 private
Definition at line 3 of file improvisedexplosive.c.
Referenced by OnActivatedByItem().
TIME_TRIGGER_TIMER_BASED_DELAY_SECS
protected const float ImprovisedExplosive::TIME_TRIGGER_TIMER_BASED_DELAY_SECS = 1.0 private
Definition at line 4 of file improvisedexplosive.c.
Referenced by OnActivatedByItem().