DayzKode: DayZCreatureAnimScriptDebug Class Reference
DayZCreatureAnimScriptDebug Class Reference
Private Member Functions
proto native void ActivateCommand (int index, int userInt, float userFloat)
proto native int GetCommandCount ()
proto native int GetCommandID (int index)
proto native owned string GetCommandName (int index)
proto native bool GetVariableBool (int index)
proto native int GetVariableCount ()
proto native float GetVariableFloat (int index)
proto native int GetVariableInt (int index)
proto native owned string GetVariableName (int index)
proto native int GetVariableType (int index)
void OnAnimationEvent (string evType, int userInt, string userString)
void OnAnimationEventsStart ()
void OnAnimationPrediction (string predName)
void OnAnimationTag (string tagName)
proto native void SetCreature (DayZCreature creature)
proto native bool SetVariableBool (int index, bool value)
proto native float SetVariableFloat (int index, float value)
proto native int SetVariableInt (int index, int value)
Private Attributes
ref array< ref DayZCreatureAnimScriptDebugAnimEventData > m_AnimEvents = new array<ref DayZCreatureAnimScriptDebugAnimEventData>
ref array< ref DayZCreatureAnimScriptDebugAnimPredictionData > m_AnimPredictions = new array<ref DayZCreatureAnimScriptDebugAnimPredictionData>
ref array< ref DayZCreatureAnimScriptDebugAnimTagData > m_AnimTags = new array<ref DayZCreatureAnimScriptDebugAnimTagData>
ref array< string > m_EventsFilter = new array<string>
const int m_iMaxAnimEventsCount = 50
Detailed Description
Definition at line 5 of file plugindayzcreatureaidebug.c.
Member Function Documentation
ActivateCommand()
proto native void DayZCreatureAnimScriptDebug::ActivateCommand (int index, int userInt, float userFloat) private
Referenced by ActivateCommand().
GetCommandCount()
proto native int DayZCreatureAnimScriptDebug::GetCommandCount () private
Referenced by InitDebugObject(), and OnGUI_CommandsEdit().
GetCommandID()
proto native int DayZCreatureAnimScriptDebug::GetCommandID (int index) private
Referenced by ActivateCommand(), and OnGUI_CommandsEdit().
GetCommandName()
proto native owned string DayZCreatureAnimScriptDebug::GetCommandName (int index) private
Referenced by OnGUI_CommandsEdit().
GetVariableBool()
proto native bool DayZCreatureAnimScriptDebug::GetVariableBool (int index) private
Referenced by GetStrValue().
GetVariableCount()
proto native int DayZCreatureAnimScriptDebug::GetVariableCount () private
Referenced by InitDebugObject(), OnGUI_Variables(), and OnGUI_VariablesEdit().
GetVariableFloat()
proto native float DayZCreatureAnimScriptDebug::GetVariableFloat (int index) private
Referenced by GetStrValue().
GetVariableInt()
proto native int DayZCreatureAnimScriptDebug::GetVariableInt (int index) private
Referenced by GetStrValue().
GetVariableName()
proto native owned string DayZCreatureAnimScriptDebug::GetVariableName (int index) private
Referenced by OnGUI_Variables(), and OnGUI_VariablesEdit().
GetVariableType()
proto native int DayZCreatureAnimScriptDebug::GetVariableType (int index) private
Referenced by GetStrValue(), GetStrValueType(), and GetVariableType().
OnAnimationEvent()
void DayZCreatureAnimScriptDebug::OnAnimationEvent (string evType, int userInt, string userString) inline private
Definition at line 39 of file plugindayzcreatureaidebug.c.
    {
        if (m_EventsFilter.Find(evType) != -1)
        {
            return;
        }
        m_AnimEvents.InsertAt(new DayZCreatureAnimScriptDebugAnimEventData(GetWorldTime(), evType, userInt, userString), 0);
        if (m_AnimEvents.Count() > m_iMaxAnimEventsCount)
        {
            m_AnimEvents.Remove(m_AnimEvents.Count() - 1);
        }
    }
References GetWorldTime(), m_AnimEvents, m_EventsFilter, and m_iMaxAnimEventsCount.
OnAnimationEventsStart()
void DayZCreatureAnimScriptDebug::OnAnimationEventsStart () inline private
Definition at line 33 of file plugindayzcreatureaidebug.c.
    {
        m_AnimPredictions.Clear();
        m_AnimTags.Clear();
    }
References m_AnimPredictions, and m_AnimTags.
OnAnimationPrediction()
void DayZCreatureAnimScriptDebug::OnAnimationPrediction (string predName) inline private
Definition at line 54 of file plugindayzcreatureaidebug.c.
    {
        m_AnimPredictions.Insert(new DayZCreatureAnimScriptDebugAnimPredictionData(predName));
    }
References m_AnimPredictions.
OnAnimationTag()
void DayZCreatureAnimScriptDebug::OnAnimationTag (string tagName) inline private
Definition at line 59 of file plugindayzcreatureaidebug.c.
    {
        m_AnimTags.Insert(new DayZCreatureAnimScriptDebugAnimTagData(tagName));
    }
References m_AnimTags.
SetCreature()
proto native void DayZCreatureAnimScriptDebug::SetCreature (DayZCreature creature) private
Referenced by InitDebugObject().
SetVariableBool()
proto native bool DayZCreatureAnimScriptDebug::SetVariableBool (int index, bool value) private
Referenced by SetValueBool().
SetVariableFloat()
proto native float DayZCreatureAnimScriptDebug::SetVariableFloat (int index, float value) private
Referenced by SetValueFloat().
SetVariableInt()
proto native int DayZCreatureAnimScriptDebug::SetVariableInt (int index, int value) private
Referenced by SetValueInt().
Member Data Documentation
m_AnimEvents
ref array<ref DayZCreatureAnimScriptDebugAnimEventData> DayZCreatureAnimScriptDebug::m_AnimEvents = new array<ref DayZCreatureAnimScriptDebugAnimEventData> private
Definition at line 29 of file plugindayzcreatureaidebug.c.
Referenced by OnAnimationEvent(), and OnGUI_AnimEvents().
m_AnimPredictions
ref array<ref DayZCreatureAnimScriptDebugAnimPredictionData> DayZCreatureAnimScriptDebug::m_AnimPredictions = new array<ref DayZCreatureAnimScriptDebugAnimPredictionData> private
Definition at line 30 of file plugindayzcreatureaidebug.c.
Referenced by OnAnimationEventsStart(), OnAnimationPrediction(), and OnGUI_AnimEvents().
m_AnimTags
ref array<ref DayZCreatureAnimScriptDebugAnimTagData> DayZCreatureAnimScriptDebug::m_AnimTags = new array<ref DayZCreatureAnimScriptDebugAnimTagData> private
Definition at line 31 of file plugindayzcreatureaidebug.c.
Referenced by OnAnimationEventsStart(), OnAnimationTag(), and OnGUI_AnimEvents().
m_EventsFilter
ref array<string> DayZCreatureAnimScriptDebug::m_EventsFilter = new array<string> private
Definition at line 27 of file plugindayzcreatureaidebug.c.
Referenced by OnAnimationEvent(), and OnGUI_AnimEvents().
m_iMaxAnimEventsCount
const int DayZCreatureAnimScriptDebug::m_iMaxAnimEventsCount = 50 private
Definition at line 26 of file plugindayzcreatureaidebug.c.
Referenced by OnAnimationEvent().