DayzKode: ActionInteractBaseCB Class Reference
ActionInteractBaseCB Class Reference
Private Member Functions
override void CreateActionComponent ()
override void EndActionComponent ()
override void InitActionComponent ()
override void OnAnimationEvent (int pEventID)
Detailed Description
Definition at line 1 of file actioninteractbase.c.
Member Function Documentation
CreateActionComponent()
override void ActionInteractBaseCB::CreateActionComponent () inline private
Definition at line 3 of file actioninteractbase.c.
    {
        m_ActionData.m_ActionComponent = new CAInteract;
    }
References ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
Referenced by InitActionComponent().
EndActionComponent()
override void ActionInteractBaseCB::EndActionComponent () inline private
Definition at line 45 of file actioninteractbase.c.
    {
        SetCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
        m_ActionData.m_State = UA_FINISHED;
    }
References ActionBaseCB::m_ActionData, ActionData::m_State, ActionBaseCB::SetCommand(), and UA_FINISHED.
InitActionComponent()
override void ActionInteractBaseCB::InitActionComponent () inline private
Definition at line 24 of file actioninteractbase.c.
    {
#ifdef DEVELOPER
        if( LogManager.IsActionLogEnable() )
        {
            Debug.ActionLog("n/a", m_ActionData.m_Action.ToString() , "n/a", "InitActionComponent", m_ActionData.m_Player.ToString() );
        }
#endif
        m_Interrupted = false;
        m_Canceled = false;
        CreateActionComponent();
        if ( m_ActionData.m_ActionComponent )
        {
            m_ActionData.m_ActionComponent.Init(m_ActionData);
        }
        m_ActionData.m_State = UA_PROCESSING;
        RegisterAnimationEvent("ActionExec", UA_ANIM_EVENT);
        m_SoundObject = m_ActionData.m_Action.PlayActionSound(m_ActionData.m_Player);
    }
References Debug::ActionLog(), CreateActionComponent(), CABase::Init(), LogManager::IsActionLogEnable(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, ActionBaseCB::m_Canceled, ActionBaseCB::m_Interrupted, ActionData::m_Player, ActionBaseCB::m_SoundObject, ActionData::m_State, RegisterAnimationEvent(), UA_ANIM_EVENT, and UA_PROCESSING.
OnAnimationEvent()
override void ActionInteractBaseCB::OnAnimationEvent (int pEventID) inline private
Definition at line 8 of file actioninteractbase.c.
    {
#ifdef DEVELOPER
        if( LogManager.IsActionLogEnable() )
        {
            if(m_ActionData)
                Debug.ActionLog("n/a", m_ActionData.m_Action.ToString() , "n/a", "OnAnimationEvent", m_ActionData.m_Player.ToString() );
        }
#endif
        if ( !m_Interrupted && pEventID == UA_ANIM_EVENT && m_ActionData && m_ActionData.m_Action )
        {
            AnimatedActionBase action = AnimatedActionBase.Cast(m_ActionData.m_Action);
            action.OnAnimationEvent(m_ActionData);
        }
    }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), ActionData::m_Action, ActionBaseCB::m_ActionData, ActionBaseCB::m_Interrupted, ActionData::m_Player, AnimatedActionBase::OnAnimationEvent(), and UA_ANIM_EVENT.