DayzKode: ActionMountBarbedWire Class Reference
ActionMountBarbedWire Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionMountBarbedWire ()
override void CreateConditionComponents ()
override string GetAdminLogMessage (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
float m_DamageAmount
string m_SlotName
Detailed Description
Definition at line 9 of file actionmountbarbedwire.c.
Constructor & Destructor Documentation
ActionMountBarbedWire()
void ActionMountBarbedWire::ActionMountBarbedWire () inline private
Definition at line 14 of file actionmountbarbedwire.c.
    {
        m_CallbackClass = ActionMountBarbedWireCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_DamageAmount = 2;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#mount";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_DamageAmount, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionMountBarbedWire::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionmountbarbedwire.c.
    {
        Object targetObject = target.GetObject();
        if ( targetObject && targetObject.CanUseConstruction() && targetObject.CanUseConstructionBuild() )
        {
            BaseBuildingBase base_building = BaseBuildingBase.Cast( targetObject );
            string selection = targetObject.GetActionComponentName( target.GetComponentIndex() );
            if ( selection.Length() > 0 )
            {
                BarbedWire barbed_wire = BarbedWire.Cast( base_building.FindAttachmentBySlotName( selection ) );
                if ( barbed_wire && !barbed_wire.IsMounted() && !barbed_wire.IsRuined() )
                {
                    m_SlotName = selection;
                    return true;
                }
            }
        }
        return false;
    }
References string::Length(), and m_SlotName.
CreateConditionComponents()
override void ActionMountBarbedWire::CreateConditionComponents () inline private
Definition at line 26 of file actionmountbarbedwire.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.BASEBUILDING );
    }
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionMountBarbedWire::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 90 of file actionmountbarbedwire.c.
    {
        string message = string.Format("Player %1 Mounted BarbedWire on %2", action_data.m_Player, action_data.m_Target.GetObject() );
        return message;
    }
References string::Format(), ActionData::m_Player, and ActionData::m_Target.
OnFinishProgressServer()
override void ActionMountBarbedWire::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 57 of file actionmountbarbedwire.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        BarbedWire barbed_wire = BarbedWire.Cast( base_building.FindAttachmentBySlotName( m_SlotName ) );
        //mount and refresh parent
        barbed_wire.SetMountedState( true );
        //solution for DamageSystem's case sensitivity
        string zone = "invalid";
        array<string> zones = new array<string>;
        zones.Copy(base_building.GetEntityDamageZoneMap().GetKeyArray());
        string tmp = "";
        string test = "";
        for (int i = 0; i < zones.Count(); i++)
        {
            tmp = zones.Get(i);
            test = tmp;
            test.ToLower();
            if (test == m_SlotName)
            {
                zone = tmp;
                break;
            }
        }
        base_building.SetHealth01(zone,"Health",barbed_wire.GetHealth01("","Health")); //attachment slot names and damagezone names must match
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References ActionData::m_Player, m_SlotName, m_SpecialtyWeight, ActionData::m_Target, and string::ToLower().
Member Data Documentation
m_DamageAmount
float ActionMountBarbedWire::m_DamageAmount private
Definition at line 11 of file actionmountbarbedwire.c.
Referenced by ActionMountBarbedWire().
m_SlotName
string ActionMountBarbedWire::m_SlotName private
Definition at line 12 of file actionmountbarbedwire.c.
Referenced by ActionCondition(), and OnFinishProgressServer().