DayzKode: VONManagerBase Class Reference
VONManagerBase Class Reference
Private Member Functions
void HandleInput (Input inp)
void HideVoiceNotification ()
bool IsVonToggled ()
void OnEvent (EventType eventTypeId, Param params)
void OnVOIPThresholdChanged ()
void ShowVoiceNotification (int level, bool fading)
void VONManagerBase ()
Private Attributes
ref ScriptInvoker m_OnPartyChatChangedEvent
ref ScriptInvoker m_OnVonStateEvent
protected bool m_VoNToggled
Detailed Description
Definition at line 1 of file vonmanager.c.
Constructor & Destructor Documentation
VONManagerBase()
void VONManagerBase::VONManagerBase () inline private
Definition at line 7 of file vonmanager.c.
    {
        m_VoNToggled = false;
    }
References m_VoNToggled.
Member Function Documentation
HandleInput()
void VONManagerBase::HandleInput (Input inp) private
Referenced by MissionBase::OnUpdate().
HideVoiceNotification()
void VONManagerBase::HideVoiceNotification () private
Referenced by OnEvent(), and OnVOIPThresholdChanged().
IsVonToggled()
bool VONManagerBase::IsVonToggled () inline private
Definition at line 18 of file vonmanager.c.
    {
        return m_VoNToggled;
    }
References m_VoNToggled.
Referenced by VONManager::IsVONToggled().
OnEvent()
void VONManagerBase::OnEvent (EventType eventTypeId, Param params) private
Referenced by OnEvent().
OnVOIPThresholdChanged()
void VONManagerBase::OnVOIPThresholdChanged () private
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds().
ShowVoiceNotification()
void VONManagerBase::ShowVoiceNotification (int level, bool fading) private
Referenced by HandleInput(), OnEvent(), and OnVOIPThresholdChanged().
Member Data Documentation
m_OnPartyChatChangedEvent
ref ScriptInvoker VONManagerBase::m_OnPartyChatChangedEvent private
Definition at line 5 of file vonmanager.c.
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::~OptionsMenuSounds().
m_OnVonStateEvent
ref ScriptInvoker VONManagerBase::m_OnVonStateEvent private
Definition at line 4 of file vonmanager.c.
Referenced by ScriptedWidgetEventHandler::OptionsMenuSounds(), and ScriptedWidgetEventHandler::~OptionsMenuSounds().
m_VoNToggled
protected bool VONManagerBase::m_VoNToggled private
Definition at line 3 of file vonmanager.c.
Referenced by IsVonToggled(), and VONManagerBase().