DayzKode: ResavePlugin Class Reference
ResavePlugin Class Reference
Private Member Functions
bool Cancel ()
bool OK ()
void Resave (string file)
override void Run ()
override void RunCommandline ()
Private Attributes
string Extension
WBModuleDef m_module
Detailed Description
Definition at line 2 of file resavetool.c.
Member Function Documentation
Cancel()
bool ResavePlugin::Cancel () inline private
Definition at line 44 of file resavetool.c.
    {
        return false;
    }
OK()
bool ResavePlugin::OK () inline private
Definition at line 38 of file resavetool.c.
    {
        return true;
    }
Resave()
void ResavePlugin::Resave (string file) inline private
Definition at line 8 of file resavetool.c.
    {
        Print("Resaving: " + file);
        m_module.SetOpenedResource(file);
        m_module.Save();
    }
References Print(), WBModuleDef::Save(), and WBModuleDef::SetOpenedResource().
Run()
override void ResavePlugin::Run () inline private
Definition at line 15 of file resavetool.c.
    {
        if (Workbench.ScriptDialog("Resave", "Which files you want to resave?", this))
        {
            m_module = Workbench.GetModule("ResourceManager");
            Workbench.SearchResources(Extension, Resave);
        }
    }
References Workbench::GetModule(), Workbench::ScriptDialog(), and Workbench::SearchResources().
RunCommandline()
override void ResavePlugin::RunCommandline () inline private
Definition at line 24 of file resavetool.c.
    {
        m_module = Workbench.GetModule("ResourceManager");
        if (m_module.GetCmdLine("-extension", Extension))
        {
            Extension.Replace("\"", "");
        }
        Workbench.SearchResources(Extension, Resave);
        Workbench.GetModule("ResourceManager").Close();
    }
References WBModuleDef::Close(), WBModuleDef::GetCmdLine(), Workbench::GetModule(), string::Replace(), and Workbench::SearchResources().
Member Data Documentation
Extension
string ResavePlugin::Extension private
Definition at line 5 of file resavetool.c.
m_module
WBModuleDef ResavePlugin::m_module private
Definition at line 6 of file resavetool.c.