DayzKode: ClosableHeader Class Reference
ClosableHeader Class Reference
Private Member Functions
void ClosableHeader (LayoutHolder parent, string function_name)
bool MouseEnter (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget enter_w, int x, int y)
void OnDragHeader (Widget w, int x, int y)
void OnDropHeader (Widget w)
override void SetActive (bool active)
override void SetLayoutName ()
override void SetName (string name)
void UpdateFlip (bool flipped)
void ~ClosableHeader ()
Private Attributes
protected int m_DefaultSort
protected Widget m_DragRender
protected bool m_IsInLocalEquipment
protected ButtonWidget m_MoveDown
protected Widget m_MovePanel
protected ButtonWidget m_MoveUp
protected Widget m_PanelWidget
protected float m_SquareSize
Detailed Description
Definition at line 1 of file closableheader.c.
Constructor & Destructor Documentation
ClosableHeader()
void ClosableHeader::ClosableHeader (LayoutHolder parent, string function_name) inline private
Definition at line 14 of file closableheader.c.
    {
        m_MovePanel = GetMainWidget().FindAnyWidget( "MovePanel" );
        m_PanelWidget   = GetMainWidget().FindAnyWidget( "PanelWidget" );
        m_DragRender    = GetMainWidget().FindAnyWidget( "Drag_Render" );
        m_MoveUp    = ButtonWidget.Cast( GetMainWidget().FindAnyWidget( "MoveUp" ) );
        m_MoveDown  = ButtonWidget.Cast( GetMainWidget().FindAnyWidget( "MoveDown" ) );
        WidgetEventHandler.GetInstance().RegisterOnClick( m_MoveUp,  m_Parent, "MoveContainerUp" );
        WidgetEventHandler.GetInstance().RegisterOnClick( m_MoveDown,  m_Parent, "MoveContainerDown" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_MoveUp,  this, "MouseLeave" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( m_MoveDown,  this, "MouseLeave" );
        WidgetEventHandler.GetInstance().RegisterOnDrag( GetMainWidget() ,  this, "OnDragHeader" );
        WidgetEventHandler.GetInstance().RegisterOnDrop( GetMainWidget() ,  this, "OnDropHeader" );
        WidgetEventHandler.GetInstance().RegisterOnMouseEnter( GetMainWidget(),  this, "MouseEnter" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( GetMainWidget(),  this, "MouseLeave" );
        float temp;
        GetMainWidget().GetScreenSize( temp, m_SquareSize );
        m_DefaultColor          = m_PanelWidget.GetColor();
        m_DefaultFontSize       = 20;
        if( GetParent() && GetParent().GetParent() && GetParent().GetParent().GetParent() )
            m_IsInLocalEquipment    = GetParent().GetParent().GetParent().IsInherited( RightArea );
    }
References FindAnyWidget(), WidgetEventHandler::GetInstance(), GetParent(), Header::m_DefaultColor, Header::m_DefaultFontSize, m_DragRender, m_IsInLocalEquipment, m_MoveDown, m_MovePanel, m_MoveUp, m_PanelWidget, m_Parent, m_SquareSize, WidgetEventHandler::RegisterOnClick(), WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnMouseEnter(), and WidgetEventHandler::RegisterOnMouseLeave().
~ClosableHeader()
void ClosableHeader::~ClosableHeader () inline private
Definition at line 43 of file closableheader.c.
    {
        if( InventoryItem.Cast( m_Entity ) )
            InventoryItem.Cast( m_Entity ).GetOnItemFlipped().Remove( UpdateFlip );
    }
References Header::m_Entity, and UpdateFlip().
Member Function Documentation
MouseEnter()
bool ClosableHeader::MouseEnter (Widget w, int x, int y) inline private
Definition at line 151 of file closableheader.c.
    {
        if( m_IsInLocalEquipment && !GetDragWidget() )
        {
            #ifdef PLATFORM_CONSOLE
            m_MovePanel.Show( GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer() );
            #else
            m_MovePanel.Show( true );
            #endif
        }
        PrepareOwnedTooltip( m_Entity, x, y );
        return true;
    }
References GetDragWidget(), GetGame(), GetInput(), Header::m_Entity, m_IsInLocalEquipment, m_MovePanel, x, and y.
MouseLeave()
bool ClosableHeader::MouseLeave (Widget w, Widget enter_w, int x, int y) inline private
Definition at line 165 of file closableheader.c.
    {
        if( enter_w != m_MoveUp && enter_w != m_MoveDown && enter_w != m_CollapseButton )
        {
            if( m_IsInLocalEquipment )
            {
                m_MovePanel.Show( false );
            }
        }
        HideOwnedTooltip();
        return true;
    }
References Header::m_CollapseButton, m_IsInLocalEquipment, m_MoveDown, m_MovePanel, and m_MoveUp.
OnDragHeader()
void ClosableHeader::OnDragHeader (Widget w, int x, int y) inline private
Definition at line 66 of file closableheader.c.
    {
        ClosableContainer parent = ClosableContainer.Cast( m_Parent );
        if( parent && GetMainWidget() && m_Entity )
        {
            ItemPreviewWidget item_preview_drag = ItemPreviewWidget.Cast( m_DragRender );
            item_preview_drag.SetFlags(WidgetFlags.EXACTPOS );
            m_DefaultSort = GetRootWidget().GetSort();
            item_preview_drag.GetParent().GetParent().GetParent().GetParent().GetParent().GetParent().GetParent().GetParent().AddChild( GetRootWidget() );
            if( item_preview_drag && m_Entity )
            {
                item_preview_drag.SetItem( m_Entity );
                item_preview_drag.SetView( m_Entity.GetViewIndex() );
            }
            ItemManager.GetInstance().SetIsDragging( true );
            parent.HideContent( true );
            m_PanelWidget.Show( false );
            if( item_preview_drag )
                item_preview_drag.Show( true );
            int ww, hh;
            GetGame().GetInventoryItemSize( InventoryItem.Cast( m_Entity ), ww, hh );
            if( item_preview_drag )
            {
                m_Entity.GetOnItemFlipped().Insert( UpdateFlip );
                if( m_Entity.GetInventory().GetFlipCargo() )
                {
                    item_preview_drag.SetSize( hh * m_SquareSize, ww * m_SquareSize );
                }
                else
                {
                    item_preview_drag.SetSize( ww * m_SquareSize, hh * m_SquareSize );
                }
            }
        }
    }
References GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), m_DefaultSort, m_DragRender, Header::m_Entity, m_PanelWidget, m_Parent, m_SquareSize, ItemManager::SetIsDragging(), ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetView(), and UpdateFlip().
OnDropHeader()
void ClosableHeader::OnDropHeader (Widget w) inline private
Definition at line 124 of file closableheader.c.
    {
        ClosableContainer parent = ClosableContainer.Cast( m_Parent );
        parent.GetMainWidget().AddChild( GetRootWidget() );
        GetRootWidget().SetSort( 0 );
        if( parent )
        {
            //
            ItemPreviewWidget item_preview_drag = ItemPreviewWidget.Cast( m_DragRender );
            if( item_preview_drag )
            {
                item_preview_drag.SetItem( null );//TODO: is this safe?
            }
            //
            m_PanelWidget.Show( true );
            m_DragRender.Show( false );
            parent.ShowContent( true );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().SetIsDragging( false );
        }
        if( InventoryItem.Cast( m_Entity ) )
            InventoryItem.Cast( m_Entity ).GetOnItemFlipped().Remove( UpdateFlip );
    }
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_DragRender, Header::m_Entity, m_PanelWidget, m_Parent, ItemManager::SetIsDragging(), ItemPreviewWidget::SetItem(), and UpdateFlip().
SetActive()
override void ClosableHeader::SetActive (bool active) inline private
Definition at line 178 of file closableheader.c.
    {
        super.SetActive( active );
        if( active )
        {
            m_PanelWidget.SetColor( ARGBF( 1, 1, 0, 0 ) );
        }
        else
        {
            m_PanelWidget.SetColor( m_DefaultColor );
        }
    }
References ARGBF(), Header::m_DefaultColor, and m_PanelWidget.
SetLayoutName()
override void ClosableHeader::SetLayoutName () inline private
Definition at line 49 of file closableheader.c.
    {
        m_LayoutName = WidgetLayoutName.ClosableHeader;
    }
References WidgetLayoutName::ClosableHeader.
SetName()
override void ClosableHeader::SetName (string name) inline private
Definition at line 54 of file closableheader.c.
    {
        name.ToUpper();
        m_HeaderText.SetText( name );
        m_HeaderText.Update();
        float x, y;
        m_HeaderText.GetScreenSize( x, y );
        m_PanelWidget.SetSize( 1, y + InventoryMenu.GetHeightMultiplied( 10 ) );
    }
References InventoryMenu(), Header::m_HeaderText, m_PanelWidget, name, string::ToUpper(), x, and y.
UpdateFlip()
void ClosableHeader::UpdateFlip (bool flipped) inline private
Definition at line 106 of file closableheader.c.
    {
        ItemPreviewWidget item_preview_drag = ItemPreviewWidget.Cast( m_DragRender );
        if( InventoryItem.Cast( m_Entity ) && item_preview_drag )
        {
            int ww, hh;
            GetGame().GetInventoryItemSize( InventoryItem.Cast( m_Entity ), ww, hh );
            if( flipped )
            {
                item_preview_drag.SetSize( hh * m_SquareSize, ww * m_SquareSize );
            }
            else
            {
                item_preview_drag.SetSize( ww * m_SquareSize, hh * m_SquareSize );
            }
        }
    }
References GetGame(), CGame::GetInventoryItemSize(), m_DragRender, Header::m_Entity, and m_SquareSize.
Referenced by OnDragHeader(), OnDropHeader(), and ~ClosableHeader().
Member Data Documentation
m_DefaultSort
protected int ClosableHeader::m_DefaultSort private
Definition at line 4 of file closableheader.c.
Referenced by OnDragHeader().
m_DragRender
protected Widget ClosableHeader::m_DragRender private
Definition at line 8 of file closableheader.c.
Referenced by ClosableHeader(), OnDragHeader(), OnDropHeader(), and UpdateFlip().
m_IsInLocalEquipment
protected bool ClosableHeader::m_IsInLocalEquipment private
Definition at line 12 of file closableheader.c.
Referenced by ClosableHeader(), MouseEnter(), and MouseLeave().
m_MoveDown
protected ButtonWidget ClosableHeader::m_MoveDown private
Definition at line 10 of file closableheader.c.
Referenced by ClosableHeader(), and MouseLeave().
m_MovePanel
protected Widget ClosableHeader::m_MovePanel private
Definition at line 6 of file closableheader.c.
Referenced by ClosableHeader(), MouseEnter(), and MouseLeave().
m_MoveUp
protected ButtonWidget ClosableHeader::m_MoveUp private
Definition at line 9 of file closableheader.c.
Referenced by ClosableHeader(), and MouseLeave().
m_PanelWidget
protected Widget ClosableHeader::m_PanelWidget private
Definition at line 7 of file closableheader.c.
Referenced by ClosableHeader(), OnDragHeader(), OnDropHeader(), SetActive(), and SetName().
m_SquareSize
protected float ClosableHeader::m_SquareSize private
Definition at line 3 of file closableheader.c.
Referenced by ClosableHeader(), OnDragHeader(), and UpdateFlip().