DayzKode: Hit_Wood Class Reference
Hit_Wood Class Reference
Private Member Functions
void Hit_Wood ()
override void OnEnterCalculations (Particle p)
override void OnExitCalculations (Particle p, float outSpeedf)
Detailed Description
Definition at line 1 of file hit_wood.c.
Constructor & Destructor Documentation
Hit_Wood()
void Hit_Wood::Hit_Wood () inline private
Definition at line 3 of file hit_wood.c.
    {
        SetEnterParticle(ParticleList.IMPACT_WOOD_ENTER);
        SetExitParticle(ParticleList.IMPACT_WOOD_EXIT);
        SetRicochetParticle(ParticleList.IMPACT_WOOD_RICOCHET);
    }
References ParticleList::IMPACT_WOOD_ENTER, ParticleList::IMPACT_WOOD_EXIT, ParticleList::IMPACT_WOOD_RICOCHET, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().
Member Function Documentation
OnEnterCalculations()
override void Hit_Wood::OnEnterCalculations (Particle p) inline private
Definition at line 10 of file hit_wood.c.
    {
        // All values represent scale
        float velocity_min = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterSplashCoef);
        float velocity_max = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterSplashCoef);
        float size = MIN_SCALING_PARAM + ( m_StoppingForce * m_EnterSplashCoef)*0.5;
        float birth_rate = MIN_SCALING_PARAM + (m_StoppingForce * m_EnterSplashCoef)*0.5;
        if (velocity_min < MIN_SCALING_PARAM)
            velocity_min = MIN_SCALING_PARAM;
        if (size < MIN_SCALING_PARAM)
            size = MIN_SCALING_PARAM;
        if (birth_rate < MIN_SCALING_PARAM)
            birth_rate = MIN_SCALING_PARAM;
        p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
        p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
        p.ScaleParticleParam(EmitorParam.SIZE, size);
        p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
    }
References EffBulletImpactBase::m_EnterSplashCoef, EffBulletImpactBase::m_StoppingForce, EffBulletImpactBase::MIN_SCALING_PARAM, and Particle::ScaleParticleParam().
OnExitCalculations()
override void Hit_Wood::OnExitCalculations (Particle p, float outSpeedf) inline private
Definition at line 35 of file hit_wood.c.
    {
        float velocity_min = 1 + (outSpeedf * m_ExitSplashCoef);
        float velocity_max = 1 + (outSpeedf * m_ExitSplashCoef);
        float size = 1 + ( outSpeedf * m_ExitSplashCoef)*0.5;
        float birth_rate = 1 + (outSpeedf * m_ExitSplashCoef)*0.5;
        if (velocity_min < MIN_SCALING_PARAM)
            velocity_min = MIN_SCALING_PARAM;
        if (size < MIN_SCALING_PARAM)
            size = MIN_SCALING_PARAM;
        if (birth_rate < MIN_SCALING_PARAM)
            birth_rate = MIN_SCALING_PARAM;
        p.ScaleParticleParam(EmitorParam.VELOCITY, velocity_min);
        p.ScaleParticleParam(EmitorParam.VELOCITY_RND, velocity_max);
        p.ScaleParticleParam(EmitorParam.SIZE, size);
        p.ScaleParticleParam(EmitorParam.BIRTH_RATE, birth_rate);
    }
References EffBulletImpactBase::m_ExitSplashCoef, EffBulletImpactBase::MIN_SCALING_PARAM, and Particle::ScaleParticleParam().