DayzKode: ErrorProperties Class Reference
ErrorProperties Class Reference
Class which holds the properties and handling of an error.
Private Member Functions
void ErrorProperties (string message, string serverMessage)
string GetClientMessage (string additionalInfo="")
string GetServerMessage (string additionalInfo="")
void HandleError (int errorCode, string additionalInfo="")
Private Attributes
const string EP_HEADER_FORMAT_STRING = "%1 (%2)"
Formating for header (%1 = Header; %2 = ErrorCode)
const string EP_MESSAGE_FORMAT_STRING = "%1\n(%2)"
Formating for message (%1 = Message; %2 = AdditionalInfo)
protected string m_Message
Message which will appear on Client.
protected string m_ServerMessage
Message which will appear on Server.
Detailed Description
Class which holds the properties and handling of an error.
Definition at line 2 of file errorproperties.c.
Constructor & Destructor Documentation
ErrorProperties()
void ErrorProperties::ErrorProperties (string message, string serverMessage) inline private
Definition at line 10 of file errorproperties.c.
    {
        m_Message = message;
        m_ServerMessage = serverMessage;
    }
References m_Message, and m_ServerMessage.
Member Function Documentation
GetClientMessage()
string ErrorProperties::GetClientMessage (string additionalInfo = "") inline private
Definition at line 18 of file errorproperties.c.
    {
        if ( additionalInfo != "" )
            return string.Format(EP_MESSAGE_FORMAT_STRING, m_Message, additionalInfo);
        else
            return m_Message;
    }
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_Message.
Referenced by GetClientMessage().
GetServerMessage()
string ErrorProperties::GetServerMessage (string additionalInfo = "") inline private
Definition at line 26 of file errorproperties.c.
    {
        if ( additionalInfo != "" )
            return string.Format(EP_MESSAGE_FORMAT_STRING, m_ServerMessage, additionalInfo);
        else
            return m_ServerMessage;
    }
References EP_MESSAGE_FORMAT_STRING, string::Format(), and m_ServerMessage.
Referenced by GetServerMessage().
HandleError()
void ErrorProperties::HandleError (int errorCode, string additionalInfo = "") inline private
Definition at line 16 of file errorproperties.c.
{}
Referenced by OnErrorThrown().
Member Data Documentation
EP_HEADER_FORMAT_STRING
const string ErrorProperties::EP_HEADER_FORMAT_STRING = "%1 (%2)" private
Formating for header (%1 = Header; %2 = ErrorCode)
Definition at line 4 of file errorproperties.c.
EP_MESSAGE_FORMAT_STRING
const string ErrorProperties::EP_MESSAGE_FORMAT_STRING = "%1\n(%2)" private
Formating for message (%1 = Message; %2 = AdditionalInfo)
Definition at line 5 of file errorproperties.c.
Referenced by GetClientMessage(), and GetServerMessage().
m_Message
protected string ErrorProperties::m_Message private
Message which will appear on Client.
Definition at line 7 of file errorproperties.c.
Referenced by ErrorProperties(), GetClientMessage(), GetHeader(), and HandleError().
m_ServerMessage
protected string ErrorProperties::m_ServerMessage private
Message which will appear on Server.
Definition at line 8 of file errorproperties.c.
Referenced by ErrorProperties(), and GetServerMessage().