DayzKode: WeaponChambering_Base Class Reference
WeaponChambering_Base Class Reference
Private Member Functions
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
Detailed Description
Definition at line 85 of file weaponchambering.c.
Member Function Documentation
OnAbort() [1/2]
override void WeaponChambering_Base::OnAbort (WeaponEventBase e) inline private
Definition at line 112 of file weaponchambering.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        string magazineTypeName;
        if (m_magazineType.Length() > 0)
            magazineTypeName = m_magazineType;
        else
            magazineTypeName = m_weapon.GetChamberAmmoTypeName(mi);
        if ( GetGame().IsServer() )
        {
            if (DayZPlayerUtils.HandleDropCartridge(e.m_player, m_damage, m_type, magazineTypeName))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, ok - aborting, chambering cartridge dropped to ground"); }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - cannot abort removal from wpn (of old mag)");
        }
        m_weapon.EffectBulletHide(mi);
        m_weapon.SelectionBulletHide(); // force hide on abort
        m_magazineType = string.Empty;
        m_type = string.Empty;
        super.OnAbort(e);
    }
References Error(), GetGame(), DayZPlayerUtils::HandleDropCartridge(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [2/2]
override void WeaponChambering_Base::OnAbort (WeaponEventBase e) inline private
Definition at line 315 of file weaponchambering.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        string magazineTypeName;
        if (m_magazineType.Length() > 0)
            magazineTypeName = m_magazineType;
        else
            magazineTypeName = m_weapon.GetChamberAmmoTypeName(mi);
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            if (DayZPlayerUtils.HandleDropCartridge(e.m_player, m_damage, m_type, magazineTypeName))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, ok - aborting, chambering cartridge dropped to ground"); }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, error - cannot abort removal from wpn (of old mag)");
        }
        m_weapon.SelectionBulletHide(); // force hide on abort
        m_weapon.EffectBulletHide(m_weapon.GetCurrentMuzzle());
        m_magazineType = string.Empty;
        m_type = string.Empty;
        super.OnAbort(e);
    }
References Error(), GetGame(), DayZPlayerUtils::HandleDropCartridge(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnEntry() [1/2]
override void WeaponChambering_Base::OnEntry (WeaponEventBase e) inline private
Definition at line 87 of file weaponchambering.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (m_srcMagazine)
            {
                m_magazineType = m_srcMagazine.GetType();
                if (m_srcMagazine.ServerAcquireCartridge(m_damage, m_type))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, ok - cartridge acquired: dmg=" + m_damage + " type=" + m_type); }
                    m_weapon.SelectionBulletShow();
                    m_weapon.EffectBulletShow( m_weapon.GetCurrentMuzzle(), m_damage, m_type);
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - cannot take cartridge from magazine");
            }
            else
            {
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - no magazine to load from (m_srcMagazine=NULL)");
            }
        }
    }
References Error(), LogManager::IsWeaponLogEnable(), m_srcMagazine, m_weapon, and wpnDebugPrint().
OnEntry() [2/2]
override void WeaponChambering_Base::OnEntry (WeaponEventBase e) inline private
Definition at line 289 of file weaponchambering.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (m_srcMagazine)
            {
                m_magazineType = m_srcMagazine.GetType();
                if (m_srcMagazine.ServerAcquireCartridge(m_damage, m_type))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, ok - cartridge acquired: dmg=" + m_damage + " type=" + m_type); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, error - cannot take cartridge from magazine");
            }
            else
            {
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, error - no magazine to load from (m_srcMagazine=NULL)");
            }
            m_weapon.SelectionBulletShow();
            m_weapon.EffectBulletShow(m_weapon.GetCurrentMuzzle(),m_damage,m_type);
        }
    }
References Error(), LogManager::IsWeaponLogEnable(), m_srcMagazine, m_weapon, and wpnDebugPrint().
OnExit() [1/2]
override void WeaponChambering_Base::OnExit (WeaponEventBase e) inline private
Definition at line 141 of file weaponchambering.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        //if ( m_weapon.IsChamberFiredOut(mi) )
        //  m_weapon.EjectCasing(mi);
        if (m_weapon.PushCartridgeToChamber(mi, m_damage, m_type))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, ok - loaded chamber"); }
        }
        else
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge, error - cannot load chamber chamber!"); }
        m_magazineType = string.Empty;
        m_type = string.Empty;
        super.OnExit(e);
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnExit() [2/2]
override void WeaponChambering_Base::OnExit (WeaponEventBase e) inline private
Definition at line 343 of file weaponchambering.c.
    {
        float ammoDamage;
        string ammoTypeName;
        int mi = m_weapon.GetCurrentMuzzle();
        if (!m_weapon.IsInternalMagazineFull(mi))
        {
            if (m_weapon.PushCartridgeToInternalMagazine(mi, m_damage, m_type))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, ok - loaded chamber"); }
            }
            else
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering_Cartridge_InnerMag, error - cannot load chamber chamber!"); }
        }
        m_magazineType = string.Empty;
        super.OnExit(e);
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().