DayzKode: DayZPlayerImplementThrowing Class Reference
DayZPlayerImplementThrowing Class Reference
Private Member Functions
bool CanChangeThrowingStance (HumanInputController pHic)
bool CanContinueThrowing (HumanInputController pHic)
bool CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands)
void DayZPlayerImplementThrowing (DayZPlayer pPlayer)
void HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt)
bool IsThrowingAnimationPlaying ()
Throwing animation after button release.
bool IsThrowingInProgress ()
Throwing wind-up only (button hold)
bool IsThrowingModeEnabled ()
void ResetState ()
void SetThrowingModeEnabled (bool enable)
Private Attributes
private const float c_fThrowingForceCoef = 1.0
private const float c_fThrowingForceMax = 90.0
private const float c_fThrowingForceMin = 20.0
private bool m_bThrowingAnimationPlaying
private bool m_bThrowingInProgress
private bool m_bThrowingModeEnabled
private float m_fThrowingForce01
private DayZPlayer m_Player
Detailed Description
Definition at line 1 of file dayzplayerimplementthrowing.c.
Constructor & Destructor Documentation
DayZPlayerImplementThrowing()
void DayZPlayerImplementThrowing::DayZPlayerImplementThrowing (DayZPlayer pPlayer) inline private
Definition at line 3 of file dayzplayerimplementthrowing.c.
    {
        m_Player = pPlayer;
        SetThrowingModeEnabled(false);
        ResetState();
    }
References m_Player, ResetState(), and SetThrowingModeEnabled().
Member Function Documentation
CanChangeThrowingStance()
bool DayZPlayerImplementThrowing::CanChangeThrowingStance (HumanInputController pHic) inline private
Definition at line 150 of file dayzplayerimplementthrowing.c.
    {
        // don't change mode in raise
        if( pHic.IsWeaponRaised() )
            return false;
        // check if it's not a heavy item
        HumanItemBehaviorCfg itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
        if( itemCfg && itemCfg.m_iType == ItemBehaviorType.HEAVY )
            return false;
/*      HumanMovementState movementState = new HumanMovementState();
        m_Player.GetMovementState(movementState);
        if( movementState.IsInProne() )
            return false;*/
        PlayerBase playerPB = PlayerBase.Cast(m_Player);
        if( playerPB )
        {
            if( playerPB.GetEmoteManager().IsEmotePlaying() )
                return false;
            if( playerPB.GetActionManager().GetRunningAction() != NULL )
                return false;
            if( playerPB.IsRestrained() || playerPB.IsItemsToDelete())
                return false;
            if( playerPB.GetDayZPlayerInventory().IsProcessing() )
                return false;
            if( playerPB.GetWeaponManager().IsRunning() )
                return false;
        }
        return true;
    }
References HumanInputController::IsWeaponRaised(), HumanItemBehaviorCfg::m_iType, and m_Player.
Referenced by HandleThrowing().
CanContinueThrowing()
bool DayZPlayerImplementThrowing::CanContinueThrowing (HumanInputController pHic) inline private
Definition at line 188 of file dayzplayerimplementthrowing.c.
    {
        HumanItemBehaviorCfg itemInHandsCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
        bool boo = false;
        UAInterface input_interface = m_Player.GetInputInterface();
        if(input_interface && input_interface.SyncedPress("UAGear"))
        {
            boo = true;
        }
        if( boo || pHic.IsWeaponRaised() || (itemInHandsCfg && itemInHandsCfg.m_iType == ItemBehaviorType.HEAVY) )
        {
            return false;
        }
        return true;
    }
References HumanInputController::IsWeaponRaised(), HumanItemBehaviorCfg::m_iType, m_Player, and UAInterface::SyncedPress().
Referenced by CanContinueThrowingEx().
CanContinueThrowingEx()
bool DayZPlayerImplementThrowing::CanContinueThrowingEx (HumanInputController pHic, EntityAI pEntityInHands) inline private
Definition at line 204 of file dayzplayerimplementthrowing.c.
    {
        if ( pEntityInHands == null )
            return false;
        return CanContinueThrowing(pHic);
    }
References CanContinueThrowing().
Referenced by HandleThrowing().
HandleThrowing()
void DayZPlayerImplementThrowing::HandleThrowing (HumanInputController pHic, HumanCommandWeapons pHcw, EntityAI pEntityInHands, float pDt) inline private
current state
handle mode change
handle action
cancel throwing in case of raising hands or heavy item in hands
check event for throw
handle throw force
Definition at line 11 of file dayzplayerimplementthrowing.c.
    {
        if ( !pEntityInHands && !m_bThrowingAnimationPlaying )
        {
            if ( m_bThrowingModeEnabled )
            {
                SetThrowingModeEnabled(false);
                pHcw.SetThrowingMode(false);
            }
            return;
        }
        SetThrowingModeEnabled(pHcw.IsThrowingMode());
        if ( pHic.IsThrowingModeChange() && CanChangeThrowingStance(pHic) )
        {
            ResetState();
            pHcw.SetActionProgressParams(0, 0);
            pHcw.SetThrowingMode(!m_bThrowingModeEnabled);
        }
        if ( m_bThrowingModeEnabled )
        {
            if ( !CanContinueThrowingEx(pHic, pEntityInHands) )
            {
                SetThrowingModeEnabled(false);
                ResetState();
                pHcw.SetActionProgressParams(0, 0);
                pHcw.SetThrowingMode(false);
                return;
            }
            if ( pHcw.WasItemLeaveHandsEvent() )
            {
                float lr = pHcw.GetBaseAimingAngleLR();
                float ud = pHcw.GetBaseAimingAngleUD();
                vector aimOrientation = m_Player.GetOrientation();
                aimOrientation[0] = aimOrientation[0] + lr;
                //add 5 deg
                aimOrientation[1] = aimOrientation[1] + ud + 5;
                m_Player.GetHumanInventory().ThrowEntity(pEntityInHands, aimOrientation.AnglesToVector(), c_fThrowingForceMin + m_fThrowingForce01 * (c_fThrowingForceMax - c_fThrowingForceMin));
                return;
            }
            if ( !m_bThrowingAnimationPlaying )
            {
                if ( pHic.IsAttackButton() )
                {
                    if ( !m_bThrowingInProgress )
                        m_bThrowingInProgress = true;
                    m_fThrowingForce01 += pDt * c_fThrowingForceCoef;
                    if ( m_fThrowingForce01 > 1.0 )
                        m_fThrowingForce01 = 1.0;
                    pHcw.SetActionProgressParams(m_fThrowingForce01, 0);
                }
                else
                {
                    if ( m_bThrowingInProgress )
                    {
                        m_bThrowingInProgress = false;
                        int throwType = 1;
                        HumanItemBehaviorCfg itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
                        itemCfg = m_Player.GetItemAccessor().GetItemInHandsBehaviourCfg();
                        if ( itemCfg )
{
                            switch ( itemCfg.m_iType )
{
                                case ItemBehaviorType.TWOHANDED:
                                case ItemBehaviorType.POLEARMS:
                                    throwType = 2;
                                    break;
                                case ItemBehaviorType.FIREARMS:
                                    throwType = 3;
                            }
                        }
                        pHcw.ThrowItem(throwType);
                        m_bThrowingAnimationPlaying = true;
                    }
                }
            }
        }
        else
        {
            ResetState();
        }
    }
References vector::AnglesToVector(), c_fThrowingForceCoef, c_fThrowingForceMax, c_fThrowingForceMin, CanChangeThrowingStance(), CanContinueThrowingEx(), HumanCommandWeapons::GetBaseAimingAngleLR(), HumanCommandWeapons::GetBaseAimingAngleUD(), HumanInputController::IsAttackButton(), HumanCommandWeapons::IsThrowingMode(), HumanInputController::IsThrowingModeChange(), m_bThrowingAnimationPlaying, m_bThrowingInProgress, m_bThrowingModeEnabled, m_fThrowingForce01, HumanItemBehaviorCfg::m_iType, m_Player, ResetState(), HumanCommandWeapons::SetActionProgressParams(), HumanCommandWeapons::SetThrowingMode(), SetThrowingModeEnabled(), HumanCommandWeapons::ThrowItem(), and HumanCommandWeapons::WasItemLeaveHandsEvent().
Referenced by CommandHandler().
IsThrowingAnimationPlaying()
bool DayZPlayerImplementThrowing::IsThrowingAnimationPlaying () inline private
Throwing animation after button release.
Definition at line 145 of file dayzplayerimplementthrowing.c.
    {
        return m_bThrowingAnimationPlaying;
    }
References m_bThrowingAnimationPlaying.
Referenced by ManBase::CanChangeStance(), and ManBase::CanDeleteItems().
IsThrowingInProgress()
bool DayZPlayerImplementThrowing::IsThrowingInProgress () inline private
Throwing wind-up only (button hold)
Definition at line 139 of file dayzplayerimplementthrowing.c.
    {
        return m_bThrowingInProgress;
    }
References m_bThrowingInProgress.
IsThrowingModeEnabled()
bool DayZPlayerImplementThrowing::IsThrowingModeEnabled () inline private
Definition at line 133 of file dayzplayerimplementthrowing.c.
    {
        return m_bThrowingModeEnabled;
    }
References m_bThrowingModeEnabled.
ResetState()
void DayZPlayerImplementThrowing::ResetState () inline private
Definition at line 117 of file dayzplayerimplementthrowing.c.
    {
        m_fThrowingForce01 = 0;
        m_bThrowingInProgress = false;
        m_bThrowingAnimationPlaying = false;
    }
References m_bThrowingAnimationPlaying, m_bThrowingInProgress, and m_fThrowingForce01.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
SetThrowingModeEnabled()
void DayZPlayerImplementThrowing::SetThrowingModeEnabled (bool enable) inline private
Definition at line 124 of file dayzplayerimplementthrowing.c.
    {
        if (enable != m_bThrowingModeEnabled)
        {
            m_Player.OnThrowingModeChange(enable);
        }
        m_bThrowingModeEnabled = enable;
    }
References m_bThrowingModeEnabled, and m_Player.
Referenced by DayZPlayerImplementThrowing(), and HandleThrowing().
Member Data Documentation
c_fThrowingForceCoef
private const float DayZPlayerImplementThrowing::c_fThrowingForceCoef = 1.0 private
Definition at line 220 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing().
c_fThrowingForceMax
private const float DayZPlayerImplementThrowing::c_fThrowingForceMax = 90.0 private
Definition at line 219 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing().
c_fThrowingForceMin
private const float DayZPlayerImplementThrowing::c_fThrowingForceMin = 20.0 private
Definition at line 218 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing().
m_bThrowingAnimationPlaying
private bool DayZPlayerImplementThrowing::m_bThrowingAnimationPlaying private
Definition at line 215 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing(), IsThrowingAnimationPlaying(), and ResetState().
m_bThrowingInProgress
private bool DayZPlayerImplementThrowing::m_bThrowingInProgress private
Definition at line 214 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing(), IsThrowingInProgress(), and ResetState().
m_bThrowingModeEnabled
private bool DayZPlayerImplementThrowing::m_bThrowingModeEnabled private
Definition at line 213 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing(), IsThrowingModeEnabled(), and SetThrowingModeEnabled().
m_fThrowingForce01
private float DayZPlayerImplementThrowing::m_fThrowingForce01 private
Definition at line 216 of file dayzplayerimplementthrowing.c.
Referenced by HandleThrowing(), and ResetState().
m_Player
private DayZPlayer DayZPlayerImplementThrowing::m_Player private
Definition at line 212 of file dayzplayerimplementthrowing.c.
Referenced by CanChangeThrowingStance(), CanContinueThrowing(), DayZPlayerImplementThrowing(), HandleThrowing(), and SetThrowingModeEnabled().