DayzKode: HemolyticReactionMdfr Class Reference
HemolyticReactionMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
float CalculateRunTime ()
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
private float m_RunningTime
Detailed Description
Definition at line 1 of file hemolyticreaction.c.
Member Function Documentation
ActivateCondition()
override bool HemolyticReactionMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 16 of file hemolyticreaction.c.
    {
        return false;
    }
CalculateRunTime()
float HemolyticReactionMdfr::CalculateRunTime () inline private
Definition at line 55 of file hemolyticreaction.c.
    {
        float time = PlayerConstants.HEMOLYTIC_BLOODLOSS_AMOUNT / PlayerConstants.SALINE_BLOOD_REGEN_PER_SEC;
        return time;
    }
References PlayerConstants::HEMOLYTIC_BLOODLOSS_AMOUNT, and PlayerConstants::SALINE_BLOOD_REGEN_PER_SEC.
Referenced by Init().
DeactivateCondition()
override bool HemolyticReactionMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 36 of file hemolyticreaction.c.
    {
        float attached_time = GetAttachedTime();
        if(attached_time > m_RunningTime )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and m_RunningTime.
Init()
override void HemolyticReactionMdfr::Init () inline private
Definition at line 5 of file hemolyticreaction.c.
    {
        m_TrackActivatedTime = true;
        m_ID                    = eModifiers.MDF_HEMOLYTIC_REACTION;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
        m_IsPersistent = true;
        m_RunningTime = CalculateRunTime();
        DisableActivateCheck();
    }
References CalculateRunTime(), DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_RunningTime, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void HemolyticReactionMdfr::OnActivate (PlayerBase player) inline private
Definition at line 21 of file hemolyticreaction.c.
    {
        player.IncreaseDiseaseCount();
    }
OnDeactivate()
override void HemolyticReactionMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 26 of file hemolyticreaction.c.
    {
        player.DecreaseDiseaseCount();
    }
OnReconnect()
override void HemolyticReactionMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 31 of file hemolyticreaction.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void HemolyticReactionMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 50 of file hemolyticreaction.c.
    {
        player.AddHealth("","Blood",-PlayerConstants.HEMOLYTIC_BLOOD_DRAIN_PER_SEC * deltaT);
    }
References PlayerConstants::HEMOLYTIC_BLOOD_DRAIN_PER_SEC.
Member Data Documentation
m_RunningTime
private float HemolyticReactionMdfr::m_RunningTime private
Definition at line 3 of file hemolyticreaction.c.
Referenced by DeactivateCondition(), and Init().