DayzKode: CfgGameplayHandler Class Reference
CfgGameplayHandler Class Reference
Static Private Member Functions
static bool GetAllowRefillSpeedModifier ()
static bool GetDisable2dMap ()
static bool GetDisableBaseDamage ()
static bool GetDisableContainerDamage ()
static bool GetDisableDistanceCheck ()
static bool GetDisableHeightPlacementCheck ()
static bool GetDisableIsBaseViableCheck ()
static bool GetDisableIsClippingRoofCheck ()
static bool GetDisableIsCollidingAngleCheck ()
static bool GetDisableIsCollidingBBoxCheck ()
static bool GetDisableIsCollidingCheck ()
static bool GetDisableIsCollidingGPlotCheck ()
static bool GetDisableIsCollidingPlayerCheck ()
static bool GetDisableIsInTerrainCheck ()
static bool GetDisableIsPlacementPermittedCheck ()
static bool GetDisableIsUnderwaterCheck ()
static bool GetDisablePerformRoofCheck ()
static bool GetDisablePersonalLight ()
static bool GetDisableRespawnDialog ()
static array< float > GetEnvironmentMaxTemps ()
static array< float > GetEnvironmentMinTemps ()
static float GetHealthDepletionSpeed ()
static float GetHitIndicationBreakPoint ()
static int GetHitIndicationIndicatorColor ()
static float GetHitIndicationMaxDuration ()
static int GetHitIndicationMode ()
static bool GetHitIndicationOverrideEnabled ()
static bool GetHitIndicationPPEEnabled ()
static float GetHitIndicationScatter ()
static int GetHitIndicationTypeID ()
static int GetLightingConfig ()
static bool GetMapDisplayNavigationInfo ()
static bool GetMapDisplayPlayerPosition ()
static bool GetMapIgnoreMapOwnership ()
static bool GetMapIgnoreNavItemsOwnership ()
static float GetMovementRotationSpeedJog ()
static float GetMovementRotationSpeedSprint ()
static float GetMovementTimeToSprint ()
static float GetMovementTimeToStrafeJog ()
static float GetMovementTimeToStrafeSprint ()
static TStringArray GetObjectSpawnersArr ()
static float GetShockDepletionSpeed ()
static float GetShockRefillSpeedConscious ()
static float GetShockRefillSpeedUnconscious ()
static float GetSprintStaminaModifierCro ()
static float GetSprintStaminaModifierErc ()
static float GetStaminaDepletionSpeed ()
static float GetStaminaKgToStaminaPercentPenalty ()
static float GetStaminaMax ()
static float GetStaminaMinCap ()
static float GetStaminaWeightLimitThreshold ()
static bool GetUse3DMap ()
static bool LoadData ()
static void OnLoaded ()
static void OnRPC (Man player, ParamsReadContext ctx)
static void SyncDataSend (notnull Man player)
static void SyncDataSendEx (notnull PlayerIdentity identity)
Static Private Attributes
static ref CfgGameplayJson m_Data = new CfgGameplayJson
static private string m_Path = "$mission:cfgGameplay.json"
Detailed Description
Definition at line 1 of file cfggameplayhandler.c.
Member Function Documentation
GetAllowRefillSpeedModifier()
static bool CfgGameplayHandler::GetAllowRefillSpeedModifier () inline static private
Definition at line 303 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.ShockHandlingData.allowRefillSpeedModifier;
    }
References ITEM_ShockHandlingData::allowRefillSpeedModifier, m_Data, CfgGameplayJson::PlayerData, and ITEM_PlayerData::ShockHandlingData.
Referenced by ShockMdfr::OnTick().
GetDisable2dMap()
static bool CfgGameplayHandler::GetDisable2dMap () inline static private
Definition at line 178 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.disable2dMap;
    }
References ITEM_PlayerData::disable2dMap, m_Data, and CfgGameplayJson::PlayerData.
GetDisableBaseDamage()
static bool CfgGameplayHandler::GetDisableBaseDamage () inline static private
Definition at line 107 of file cfggameplayhandler.c.
    {
        return m_Data.GeneralData.disableBaseDamage;
    }
References ITEM_GeneralData::disableBaseDamage, CfgGameplayJson::GeneralData, and m_Data.
GetDisableContainerDamage()
static bool CfgGameplayHandler::GetDisableContainerDamage () inline static private
Definition at line 113 of file cfggameplayhandler.c.
    {
        return m_Data.GeneralData.disableContainerDamage;
    }
References ITEM_GeneralData::disableContainerDamage, CfgGameplayJson::GeneralData, and m_Data.
GetDisableDistanceCheck()
static bool CfgGameplayHandler::GetDisableDistanceCheck () inline static private
Definition at line 243 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.ConstructionData.disableDistanceCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disableDistanceCheck, and m_Data.
GetDisableHeightPlacementCheck()
static bool CfgGameplayHandler::GetDisableHeightPlacementCheck () inline static private
Definition at line 213 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableHeightPlacementCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableHeightPlacementCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::HeightPlacementCheck().
GetDisableIsBaseViableCheck()
static bool CfgGameplayHandler::GetDisableIsBaseViableCheck () inline static private
Definition at line 198 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsBaseViableCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsBaseViableCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsBaseViable().
GetDisableIsClippingRoofCheck()
static bool CfgGameplayHandler::GetDisableIsClippingRoofCheck () inline static private
Definition at line 193 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsClippingRoofCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsClippingRoofCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsClippingRoof().
GetDisableIsCollidingAngleCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingAngleCheck () inline static private
Definition at line 223 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsCollidingAngleCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingAngleCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingAngle().
GetDisableIsCollidingBBoxCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingBBoxCheck () inline static private
Definition at line 183 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsCollidingBBoxCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingBBoxCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::GetProjectionEntityPosition(), and Hologram::IsCollidingBBox().
GetDisableIsCollidingCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingCheck () inline static private
Definition at line 233 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.ConstructionData.disableIsCollidingCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disableIsCollidingCheck, and m_Data.
Referenced by IsColliding(), and IsCollidingEx().
GetDisableIsCollidingGPlotCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingGPlotCheck () inline static private
Definition at line 228 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsCollidingGPlotCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingGPlotCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingGPlot().
GetDisableIsCollidingPlayerCheck()
static bool CfgGameplayHandler::GetDisableIsCollidingPlayerCheck () inline static private
Definition at line 188 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsCollidingPlayerCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsCollidingPlayerCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsCollidingPlayer().
GetDisableIsInTerrainCheck()
static bool CfgGameplayHandler::GetDisableIsInTerrainCheck () inline static private
Definition at line 203 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsInTerrainCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsInTerrainCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsInTerrain().
GetDisableIsPlacementPermittedCheck()
static bool CfgGameplayHandler::GetDisableIsPlacementPermittedCheck () inline static private
Definition at line 218 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsPlacementPermittedCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsPlacementPermittedCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsPlacementPermitted().
GetDisableIsUnderwaterCheck()
static bool CfgGameplayHandler::GetDisableIsUnderwaterCheck () inline static private
Definition at line 208 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.HologramData.disableIsUnderwaterCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_HologramData::disableIsUnderwaterCheck, ITEM_BaseBuildingData::HologramData, and m_Data.
Referenced by Hologram::IsUnderwater().
GetDisablePerformRoofCheck()
static bool CfgGameplayHandler::GetDisablePerformRoofCheck () inline static private
Definition at line 238 of file cfggameplayhandler.c.
    {
        return m_Data.BaseBuildingData.ConstructionData.disablePerformRoofCheck;
    }
References CfgGameplayJson::BaseBuildingData, ITEM_BaseBuildingData::ConstructionData, ITEM_ConstructionData::disablePerformRoofCheck, and m_Data.
Referenced by BaseBuildingBase::PerformRoofCheckForBase().
GetDisablePersonalLight()
static bool CfgGameplayHandler::GetDisablePersonalLight () inline static private
! ===================================================================================== !! the naming convention for static functions in this file is Get+MemberVariableName !! ! =====================================================================================
Definition at line 78 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.disablePersonalLight;
    }
References ITEM_PlayerData::disablePersonalLight, m_Data, and CfgGameplayJson::PlayerData.
Referenced by PlayerBase::OnGameplayDataHandlerSync().
GetDisableRespawnDialog()
static bool CfgGameplayHandler::GetDisableRespawnDialog () inline static private
Definition at line 118 of file cfggameplayhandler.c.
    {
        return m_Data.GeneralData.disableRespawnDialog;
    }
References ITEM_GeneralData::disableRespawnDialog, CfgGameplayJson::GeneralData, and m_Data.
Referenced by MissionBase::OnGameplayDataHandlerLoad(), and ManBase::OnGameplayDataHandlerSync().
GetEnvironmentMaxTemps()
static array< float > CfgGameplayHandler::GetEnvironmentMaxTemps () inline static private
Definition at line 100 of file cfggameplayhandler.c.
    {
        return m_Data.WorldsData.environmentMaxTemps;
    }
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by WorldData::Init().
GetEnvironmentMinTemps()
static array< float > CfgGameplayHandler::GetEnvironmentMinTemps () inline static private
Definition at line 95 of file cfggameplayhandler.c.
    {
        return m_Data.WorldsData.environmentMinTemps;
    }
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by WorldData::Init().
GetHealthDepletionSpeed()
static float CfgGameplayHandler::GetHealthDepletionSpeed () inline static private
Definition at line 334 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.DrowningData.healthDepletionSpeed;
    }
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
Referenced by DrowningMdfr::OnTick().
GetHitIndicationBreakPoint()
static float CfgGameplayHandler::GetHitIndicationBreakPoint () inline static private
Definition at line 273 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionBreakPointRelative;
    }
References ITEM_HitIndicationData::hitDirectionBreakPointRelative, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationIndicatorColor()
static int CfgGameplayHandler::GetHitIndicationIndicatorColor () inline static private
Definition at line 263 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionIndicatorColorStr.HexToInt();
    }
References string::HexToInt(), ITEM_HitIndicationData::hitDirectionIndicatorColorStr, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMaxDuration()
static float CfgGameplayHandler::GetHitIndicationMaxDuration () inline static private
Definition at line 268 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionMaxDuration;
    }
References ITEM_HitIndicationData::hitDirectionMaxDuration, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationMode()
static int CfgGameplayHandler::GetHitIndicationMode () inline static private
Definition at line 253 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionBehaviour;
    }
References ITEM_HitIndicationData::hitDirectionBehaviour, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationOverrideEnabled()
static bool CfgGameplayHandler::GetHitIndicationOverrideEnabled () inline static private
Definition at line 248 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionOverrideEnabled;
    }
References ITEM_HitIndicationData::hitDirectionOverrideEnabled, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationPPEEnabled()
static bool CfgGameplayHandler::GetHitIndicationPPEEnabled () inline static private
Definition at line 283 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitIndicationPostProcessEnabled;
    }
References ITEM_UIData::HitIndicationData, ITEM_HitIndicationData::hitIndicationPostProcessEnabled, m_Data, and CfgGameplayJson::UIData.
Referenced by ManBase::OnGameplayDataHandlerSync().
GetHitIndicationScatter()
static float CfgGameplayHandler::GetHitIndicationScatter () inline static private
Definition at line 278 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionScatter;
    }
References ITEM_HitIndicationData::hitDirectionScatter, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetHitIndicationTypeID()
static int CfgGameplayHandler::GetHitIndicationTypeID () inline static private
Definition at line 258 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.HitIndicationData.hitDirectionStyle;
    }
References ITEM_HitIndicationData::hitDirectionStyle, ITEM_UIData::HitIndicationData, m_Data, and CfgGameplayJson::UIData.
Referenced by HitDirectionEffectBase::CheckValues().
GetLightingConfig()
static int CfgGameplayHandler::GetLightingConfig () inline static private
Definition at line 85 of file cfggameplayhandler.c.
    {
        return m_Data.WorldsData.lightingConfig;
    }
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by ManBase::UpdateLighting().
GetMapDisplayNavigationInfo()
static bool CfgGameplayHandler::GetMapDisplayNavigationInfo () inline static private
Definition at line 324 of file cfggameplayhandler.c.
    {
        return m_Data.MapData.displayNavInfo;
    }
References ITEM_MapData::displayNavInfo, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init().
GetMapDisplayPlayerPosition()
static bool CfgGameplayHandler::GetMapDisplayPlayerPosition () inline static private
Definition at line 319 of file cfggameplayhandler.c.
    {
        return m_Data.MapData.displayPlayerPosition;
    }
References ITEM_MapData::displayPlayerPosition, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init().
GetMapIgnoreMapOwnership()
static bool CfgGameplayHandler::GetMapIgnoreMapOwnership () inline static private
Definition at line 309 of file cfggameplayhandler.c.
    {
        return m_Data.MapData.ignoreMapOwnership;
    }
References ITEM_MapData::ignoreMapOwnership, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::CloseMapMenu(), MissionBase::OnUpdate(), and UIScriptedMenu::Update().
GetMapIgnoreNavItemsOwnership()
static bool CfgGameplayHandler::GetMapIgnoreNavItemsOwnership () inline static private
Definition at line 314 of file cfggameplayhandler.c.
    {
        return m_Data.MapData.ignoreNavItemsOwnership;
    }
References ITEM_MapData::ignoreNavItemsOwnership, m_Data, and CfgGameplayJson::MapData.
Referenced by UIScriptedMenu::Init(), and UIScriptedMenu::Update().
GetMovementRotationSpeedJog()
static float CfgGameplayHandler::GetMovementRotationSpeedJog () inline static private
Definition at line 168 of file cfggameplayhandler.c.
    {
        return Math.Max(0.01, m_Data.PlayerData.MovementData.rotationSpeedJog);
    }
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::rotationSpeedJog.
GetMovementRotationSpeedSprint()
static float CfgGameplayHandler::GetMovementRotationSpeedSprint () inline static private
Definition at line 173 of file cfggameplayhandler.c.
    {
        return Math.Max(0.01, m_Data.PlayerData.MovementData.rotationSpeedSprint);
    }
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::rotationSpeedSprint.
GetMovementTimeToSprint()
static float CfgGameplayHandler::GetMovementTimeToSprint () inline static private
Definition at line 158 of file cfggameplayhandler.c.
    {
        return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToSprint);
    }
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToSprint.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeJog()
static float CfgGameplayHandler::GetMovementTimeToStrafeJog () inline static private
Definition at line 153 of file cfggameplayhandler.c.
    {
        return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToStrafeJog);
    }
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToStrafeJog.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetMovementTimeToStrafeSprint()
static float CfgGameplayHandler::GetMovementTimeToStrafeSprint () inline static private
Definition at line 163 of file cfggameplayhandler.c.
    {
        return Math.Max(0.01, m_Data.PlayerData.MovementData.timeToStrafeSprint);
    }
References m_Data, Math::Max(), ITEM_PlayerData::MovementData, CfgGameplayJson::PlayerData, and ITEM_MovementData::timeToStrafeSprint.
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
GetObjectSpawnersArr()
static TStringArray CfgGameplayHandler::GetObjectSpawnersArr () inline static private
Definition at line 90 of file cfggameplayhandler.c.
    {
        return m_Data.WorldsData.objectSpawnersArr;
    }
References m_Data, and CfgGameplayJson::WorldsData.
Referenced by ObjectSpawnerHandler::SpawnObjects().
GetShockDepletionSpeed()
static float CfgGameplayHandler::GetShockDepletionSpeed () inline static private
Definition at line 339 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.DrowningData.shockDepletionSpeed;
    }
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
Referenced by DrowningMdfr::OnTick().
GetShockRefillSpeedConscious()
static float CfgGameplayHandler::GetShockRefillSpeedConscious () inline static private
Definition at line 293 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.ShockHandlingData.shockRefillSpeedConscious;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::ShockHandlingData, and ITEM_ShockHandlingData::shockRefillSpeedConscious.
Referenced by ShockMdfr::GetRefillSpeed().
GetShockRefillSpeedUnconscious()
static float CfgGameplayHandler::GetShockRefillSpeedUnconscious () inline static private
Definition at line 298 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.ShockHandlingData.shockRefillSpeedUnconscious;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::ShockHandlingData, and ITEM_ShockHandlingData::shockRefillSpeedUnconscious.
Referenced by ShockMdfr::GetRefillSpeed().
GetSprintStaminaModifierCro()
static float CfgGameplayHandler::GetSprintStaminaModifierCro () inline static private
Definition at line 128 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.sprintStaminaModifierCro;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintStaminaModifierCro, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Move().
GetSprintStaminaModifierErc()
static float CfgGameplayHandler::GetSprintStaminaModifierErc () inline static private
Definition at line 123 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.sprintStaminaModifierErc;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_StaminaData::sprintStaminaModifierErc, and ITEM_PlayerData::StaminaData.
Referenced by StaminaProcessor_Move().
GetStaminaDepletionSpeed()
static float CfgGameplayHandler::GetStaminaDepletionSpeed () inline static private
Definition at line 329 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.DrowningData.staminaDepletionSpeed;
    }
References ITEM_PlayerData::DrowningData, m_Data, and CfgGameplayJson::PlayerData.
GetStaminaKgToStaminaPercentPenalty()
static float CfgGameplayHandler::GetStaminaKgToStaminaPercentPenalty () inline static private
Definition at line 143 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.staminaKgToStaminaPercentPenalty;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaKgToStaminaPercentPenalty.
Referenced by Update().
GetStaminaMax()
static float CfgGameplayHandler::GetStaminaMax () inline static private
Definition at line 138 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.staminaMax;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaMax.
Referenced by DepleteStamina(), GetStaminaMax(), PlayerStatsPCO_Base::Init(), RegisterStaminaModifiers(), SetStamina(), Hud::SetStamina(), StaminaHandler(), and Update().
GetStaminaMinCap()
static float CfgGameplayHandler::GetStaminaMinCap () inline static private
Definition at line 148 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.staminaMinCap;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaMinCap.
Referenced by RegisterStaminaConsumers(), and Update().
GetStaminaWeightLimitThreshold()
static float CfgGameplayHandler::GetStaminaWeightLimitThreshold () inline static private
Definition at line 133 of file cfggameplayhandler.c.
    {
        return m_Data.PlayerData.StaminaData.staminaWeightLimitThreshold;
    }
References m_Data, CfgGameplayJson::PlayerData, ITEM_PlayerData::StaminaData, and ITEM_StaminaData::staminaWeightLimitThreshold.
Referenced by Update().
GetUse3DMap()
static bool CfgGameplayHandler::GetUse3DMap () inline static private
Definition at line 288 of file cfggameplayhandler.c.
    {
        return m_Data.UIData.use3DMap;
    }
References m_Data, CfgGameplayJson::UIData, and ITEM_UIData::use3DMap.
Referenced by UIScriptedMenu::CloseMapMenu(), ManBase::CommandHandler(), MissionBase::HandleMapToggleByKeyboardShortcut(), ActionUnfoldMapCB::PerformMapChange(), and ActionUnfoldMapCB::~ActionUnfoldMapCB().
LoadData()
static bool CfgGameplayHandler::LoadData () inline static private
Definition at line 7 of file cfggameplayhandler.c.
    {
        if ( !FileExist( m_Path ) )
        {
            m_Path = "";
            GetGame().GetWorldName( m_Path );
            m_Path = string.Format("DZ/worlds/%1/ce/cfgGameplay.json", m_Path );
        }
        if (!GetGame().ServerConfigGetInt( "enableCfgGameplayFile" ) || !FileExist( m_Path ))
        {
            m_Data.InitServer();
            OnLoaded();
            return false;
        }
        JsonFileLoader<CfgGameplayJson>.JsonLoadFile( m_Path, m_Data );//we are allowed to read the file, so we replace the default data with data from json
        OnLoaded();
        return true;
    }
References FileExist(), string::Format(), GetGame(), CGame::GetWorldName(), CfgGameplayJson::InitServer(), m_Data, m_Path, and OnLoaded().
Referenced by MissionBase::OnInit().
OnLoaded()
static void CfgGameplayHandler::OnLoaded () inline static private
Definition at line 29 of file cfggameplayhandler.c.
    {
        GetGame().GetMission().OnGameplayDataHandlerLoad();
        DayZGame.Cast(GetGame()).OnGameplayDataHandlerLoad();
        ObjectSpawnerHandler.OnGameplayDataHandlerLoad();
    }
References DayZGame(), GetGame(), CGame::GetMission(), Mission::OnGameplayDataHandlerLoad(), and ObjectSpawnerHandler::OnGameplayDataHandlerLoad().
Referenced by LoadData().
OnRPC()
static void CfgGameplayHandler::OnRPC (Man player, ParamsReadContext ctx) inline static private
Definition at line 51 of file cfggameplayhandler.c.
    {
        Param1<CfgGameplayJson> data = new Param1<CfgGameplayJson>(null);
        if ( ctx.Read(data) )
        {
            m_Data = data.param1;
        }
        else
        {
            ErrorEx("CfgGameplayHandler - client failed to read incoming data");
        }
    }
References ErrorEx, m_Data, and Serializer::Read().
Referenced by OnRPC().
SyncDataSend()
static void CfgGameplayHandler::SyncDataSend (notnull Man player) inline static private
Definition at line 37 of file cfggameplayhandler.c.
    {
        GetGame().RPCSingleParam(player, ERPCs.RPC_CFG_GAMEPLAY_SYNC, new Param1<CfgGameplayJson>(m_Data), true, player.GetIdentity());
    }
References GetGame(), m_Data, and CGame::RPCSingleParam().
SyncDataSendEx()
static void CfgGameplayHandler::SyncDataSendEx (notnull PlayerIdentity identity) inline static private
Definition at line 43 of file cfggameplayhandler.c.
    {
        //Debug.Log("SyncDataSendEx");
        GetGame().RPCSingleParam(null, ERPCs.RPC_CFG_GAMEPLAY_SYNC, new Param1<CfgGameplayJson>(m_Data), true, identity);
    }
References GetGame(), m_Data, and CGame::RPCSingleParam().
Referenced by MissionBase::OnEvent().
Member Data Documentation
m_Data
ref CfgGameplayJson CfgGameplayHandler::m_Data = new CfgGameplayJson static private
Definition at line 5 of file cfggameplayhandler.c.
Referenced by GetAllowRefillSpeedModifier(), GetDisable2dMap(), GetDisableBaseDamage(), GetDisableContainerDamage(), GetDisableDistanceCheck(), GetDisableHeightPlacementCheck(), GetDisableIsBaseViableCheck(), GetDisableIsClippingRoofCheck(), GetDisableIsCollidingAngleCheck(), GetDisableIsCollidingBBoxCheck(), GetDisableIsCollidingCheck(), GetDisableIsCollidingGPlotCheck(), GetDisableIsCollidingPlayerCheck(), GetDisableIsInTerrainCheck(), GetDisableIsPlacementPermittedCheck(), GetDisableIsUnderwaterCheck(), GetDisablePerformRoofCheck(), GetDisablePersonalLight(), GetDisableRespawnDialog(), GetEnvironmentMaxTemps(), GetEnvironmentMinTemps(), GetHealthDepletionSpeed(), GetHitIndicationBreakPoint(), GetHitIndicationIndicatorColor(), GetHitIndicationMaxDuration(), GetHitIndicationMode(), GetHitIndicationOverrideEnabled(), GetHitIndicationPPEEnabled(), GetHitIndicationScatter(), GetHitIndicationTypeID(), GetLightingConfig(), GetMapDisplayNavigationInfo(), GetMapDisplayPlayerPosition(), GetMapIgnoreMapOwnership(), GetMapIgnoreNavItemsOwnership(), GetMovementRotationSpeedJog(), GetMovementRotationSpeedSprint(), GetMovementTimeToSprint(), GetMovementTimeToStrafeJog(), GetMovementTimeToStrafeSprint(), GetObjectSpawnersArr(), GetShockDepletionSpeed(), GetShockRefillSpeedConscious(), GetShockRefillSpeedUnconscious(), GetSprintStaminaModifierCro(), GetSprintStaminaModifierErc(), GetStaminaDepletionSpeed(), GetStaminaKgToStaminaPercentPenalty(), GetStaminaMax(), GetStaminaMinCap(), GetStaminaWeightLimitThreshold(), GetUse3DMap(), LoadData(), OnRPC(), SyncDataSend(), and SyncDataSendEx().
m_Path
private string CfgGameplayHandler::m_Path = "$mission:cfgGameplay.json" static private
Definition at line 3 of file cfggameplayhandler.c.
Referenced by LoadData().