DayzKode: ModInfo Class Reference
ModInfo Class Reference
Private Member Functions
proto owned string GetAction ()
proto owned string GetAuthor ()
proto bool GetDefault ()
proto bool GetIsDLC ()
proto bool GetIsOwned ()
proto owned string GetLogo ()
proto owned string GetLogoOver ()
proto owned string GetLogoSmall ()
proto owned string GetName ()
proto owned string GetOverview ()
proto owned string GetPicture ()
proto owned string GetTooltip ()
proto owned string GetVersion ()
proto void GoToStore ()
Detailed Description
Definition at line 1 of file modinfo.c.
Member Function Documentation
GetAction()
proto owned string ModInfo::GetAction () private
GetAuthor()
proto owned string ModInfo::GetAuthor () private
GetDefault()
proto bool ModInfo::GetDefault () private
GetIsDLC()
proto bool ModInfo::GetIsDLC () private
Referenced by ScriptedWidgetEventHandler::ModsMenuSimpleEntry().
GetIsOwned()
proto bool ModInfo::GetIsOwned () private
Referenced by UIScriptedMenu::LoadMods(), and ScriptedWidgetEventHandler::ModsMenuSimpleEntry().
GetLogo()
proto owned string ModInfo::GetLogo () private
GetLogoOver()
proto owned string ModInfo::GetLogoOver () private
GetLogoSmall()
proto owned string ModInfo::GetLogoSmall () private
Referenced by UIScriptedMenu::LoadMods().
GetName()
proto owned string ModInfo::GetName () private
GetOverview()
proto owned string ModInfo::GetOverview () private
GetPicture()
proto owned string ModInfo::GetPicture () private
GetTooltip()
proto owned string ModInfo::GetTooltip () private
Referenced by ScriptedWidgetEventHandler::ShowTooltip().
GetVersion()
proto owned string ModInfo::GetVersion () private
GoToStore()
proto void ModInfo::GoToStore () private