DayzKode: ConstructionBoxTrigger Class Reference
ConstructionBoxTrigger Class Reference
Private Member Functions
string GetPartName ()
bool IsColliding ()
void SetPartName (string part_name)
override protected void UpdateInsiders (int timeout)
Private Attributes
string m_PartName
Detailed Description
Definition at line 1319 of file construction.c.
Member Function Documentation
GetPartName()
string ConstructionBoxTrigger::GetPartName () inline private
Definition at line 1328 of file construction.c.
    {
        return m_PartName;
    }
References m_PartName.
Referenced by CreateCollisionTrigger().
IsColliding()
bool ConstructionBoxTrigger::IsColliding () inline private
Definition at line 1338 of file construction.c.
    {
        if ( GetInsiders().Count() > 0 )
        {
            return true;
        }
        return false;
    }
References Count, and Trigger::GetInsiders().
Referenced by IsTriggerColliding().
SetPartName()
void ConstructionBoxTrigger::SetPartName (string part_name) inline private
Definition at line 1323 of file construction.c.
    {
        m_PartName = part_name;
    }
References m_PartName.
Referenced by CreateCollisionTrigger().
UpdateInsiders()
override protected void ConstructionBoxTrigger::UpdateInsiders (int timeout) inline private
Definition at line 1333 of file construction.c.
    {
        super.UpdateInsiders( 20 );
    }
Member Data Documentation
m_PartName
string ConstructionBoxTrigger::m_PartName private
Definition at line 1321 of file construction.c.
Referenced by GetPartName(), and SetPartName().