DayzKode: Lockpick Class Reference
Lockpick Class Reference
Private Member Functions
void Lockpick ()
override void SetActions ()
Detailed Description
Definition at line 1 of file lockpick.c.
Constructor & Destructor Documentation
Lockpick()
void Lockpick::Lockpick () inline private
Definition at line 3 of file lockpick.c.
    {
        m_MineDisarmRate = 90;
    }
Member Function Documentation
SetActions()
override void Lockpick::SetActions () inline private
Definition at line 8 of file lockpick.c.
    {
        super.SetActions();
        AddAction(ActionUnrestrainTarget);
        AddAction(ActionLockDoors);
        AddAction(ActionUnlockDoors);
        AddAction(ActionDisarmMine);
        AddAction(ActionDisarmExplosive);
    }
References ActionDisarmExplosive(), ActionDisarmMine(), and AddAction().