DayzKode: HandStartAction Class Reference
HandStartAction Class Reference
simple class starting animation action specified by m_action and m_actionType
Private Member Functions
void HandForceSwapingAnimated_Show (Man player=NULL, HandStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void HandStartHidingAnimated (Man player=NULL, HandStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void HandTakingAnimated_Show (Man player=NULL, HandStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
Private Attributes
ref InventoryLocation m_Dst
ref InventoryLocation m_Dst1 = null
ref InventoryLocation m_Dst2 = null
ref InventoryLocation m_Src
ref InventoryLocation m_Src1 = null
ref InventoryLocation m_Src2 = null
Detailed Description
simple class starting animation action specified by m_action and m_actionType
Definition at line 43 of file handanimatedforceswapping.c.
Member Function Documentation
HandForceSwapingAnimated_Show()
void HandStartAction::HandForceSwapingAnimated_Show (Man player = NULL, HandStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 50 of file handanimatedforceswapping.c.
{ }
HandStartHidingAnimated()
void HandStartAction::HandStartHidingAnimated (Man player = NULL, HandStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 3 of file handanimatedmovingtoatt.c.
    { }
HandTakingAnimated_Show()
void HandStartAction::HandTakingAnimated_Show (Man player = NULL, HandStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file handanimatedtakingfromatt.c.
    {
        m_Src = null;
        m_Dst = null;
    }
References m_Src.
IsWaitingForActionFinish() [1/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 83 of file handanimatedforceswapping.c.
{ return true; }
IsWaitingForActionFinish() [2/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 21 of file handanimatedmovingtoatt.c.
{ return m_ActionType == -1; }
IsWaitingForActionFinish() [3/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 63 of file handanimatedmovingtoatt.c.
{ return true; }
IsWaitingForActionFinish() [4/4]
override bool HandStartAction::IsWaitingForActionFinish () inline private
Definition at line 56 of file handanimatedtakingfromatt.c.
{ return true; }
OnAbort() [1/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 65 of file handanimatedforceswapping.c.
    {
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnAbort(e);
    }
OnAbort() [2/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 11 of file handanimatedmovingtoatt.c.
    {
        super.OnAbort(e);
    }
OnAbort() [3/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 51 of file handanimatedmovingtoatt.c.
    {
        m_Dst = NULL;
        super.OnAbort(e);
    }
OnAbort() [4/4]
override void HandStartAction::OnAbort (HandEventBase e) inline private
Definition at line 42 of file handanimatedtakingfromatt.c.
    {
        m_Src = null;
        m_Dst = null;
        super.OnAbort(e);
    }
References m_Src.
OnEntry() [1/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 52 of file handanimatedforceswapping.c.
    {
        if (m_Src1 && m_Src2 && m_Dst1 && m_Dst2 )
        {
            GameInventory.LocationSwap(m_Src1, m_Src2, m_Dst1, m_Dst2);
            e.m_Player.OnItemInHandsChanged();
        }
        else
            Error("[hndfsm] HandForceSwappingAnimated_Show is not properly configured!");
        super.OnEntry(e);
    }
References Error().
OnEntry() [2/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 6 of file handanimatedmovingtoatt.c.
    {
        super.OnEntry(e);
    }
OnEntry() [3/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 29 of file handanimatedmovingtoatt.c.
    {
        Man player = e.m_Player;
        if (m_Dst && m_Dst.IsValid())
        {
            EntityAI item = m_Dst.GetItem();
            InventoryLocation src = new InventoryLocation;
            if (item.GetInventory().GetCurrentInventoryLocation(src))
            {
                GameInventory.LocationSyncMoveEntity(src, m_Dst);
                player.OnItemInHandsChanged();
            }
            else
                Error("[hndfsm] " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " HandAnimatedMoveToDst_W4T- item " + item + " has no Inventory or Location, inv=" + item.GetInventory());
        }
        else
            Error("[hndfsm] HandAnimatedMoveToDst_W4T - event has no valid m_Dst");
        super.OnEntry(e);
    }
References Error().
OnEntry() [4/4]
override void HandStartAction::OnEntry (HandEventBase e) inline private
Definition at line 15 of file handanimatedtakingfromatt.c.
    {
        super.OnEntry(e);
        if (m_Src)
        {
            if (m_Src.IsValid())
            {
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryHFSMLogEnable() )
                {
                    Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "OnEntry", e.m_Player.ToString() );
                }
                #endif
                GameInventory.LocationSyncMoveEntity(m_Src, m_Dst);
                e.m_Player.OnItemInHandsChanged();
            }
            else
            {
                Error("[hndfsm] " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " HandTakingAnimated_Show m_Src=invalid, item not in bubble?");
            }
        }
        else
            Error("[hndfsm] HandTakingAnimated_Show, error - m_Src not configured");
    }
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), InventoryLocation::IsValid(), and m_Src.
OnExit() [1/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 74 of file handanimatedforceswapping.c.
    {
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnExit(e);
    }
OnExit() [2/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 16 of file handanimatedmovingtoatt.c.
    {
        super.OnExit(e);
    }
OnExit() [3/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 57 of file handanimatedmovingtoatt.c.
    {
        m_Dst = NULL;
        super.OnExit(e);
    }
OnExit() [4/4]
override void HandStartAction::OnExit (HandEventBase e) inline private
Definition at line 49 of file handanimatedtakingfromatt.c.
    {
        m_Src = null;
        m_Dst = null;
        super.OnExit(e);
    }
References m_Src.
Member Data Documentation
m_Dst
ref InventoryLocation HandStartAction::m_Dst private
Definition at line 27 of file handanimatedmovingtoatt.c.
m_Dst1
ref InventoryLocation HandStartAction::m_Dst1 = null private
Definition at line 47 of file handanimatedforceswapping.c.
m_Dst2
ref InventoryLocation HandStartAction::m_Dst2 = null private
Definition at line 48 of file handanimatedforceswapping.c.
m_Src
ref InventoryLocation HandStartAction::m_Src private
Definition at line 6 of file handanimatedtakingfromatt.c.
m_Src1
ref InventoryLocation HandStartAction::m_Src1 = null private
Definition at line 45 of file handanimatedforceswapping.c.
m_Src2
ref InventoryLocation HandStartAction::m_Src2 = null private
Definition at line 46 of file handanimatedforceswapping.c.