DayzKode: EntityLightSource Class Reference
EntityLightSource Class Reference
Private Member Functions
void AddLifetime (float life_in_s)
Prolongs the lifetime of the light in seconds. Use negative number to shorten its lifetime.
void AttachOnMemoryPoint (Object parent, string memory_point_start, string memory_point_target="")
Attaches this light on the parent entity's memory point, with optional direction target memory point.
void AttachOnObject (Object parent, vector local_pos="0 0 0", vector local_ori="0 0 0")
Attaches this light on the parent entity, with optional position and orientation offset.
private void CheckFadeOut (int current_time)
void CheckIfParentIsInCargo ()
private bool CheckLifetime (int current_time)
void CorrectLightPulseDuringDaylight ()
Call this after using SetBrightness(...) to fix light's intensity during daytime.
private void DeleteLightNow ()
private void DeleteLightWithDelay ()
Correct way of deleting light from memory. It is necesarry to have this delay due to hierarchy.
void Destroy ()
Switches off the light and deletes it from memory.
void DetachFromParent ()
Detaches this light from its parent entity.
void EnableDebug (bool state)
Enables some debug functionality of this light.
override void EOnFrame (IEntity other, float timeSlice)
On frame event. If you want to control your light within your own rules then override the event OnFrameLightSource and put your code there.
override void EOnInit (IEntity other, int extra)
void FadeBrightnessTo (float value, float time_in_s)
Fades the brightness of the light to the given value.
void FadeIn (float time_in_s)
Makes the light fade into existence. Works only at the moment the light is created. Consider using FadeBrightnessTo(...) and FadeRadiusTo(...) at anytime later during lifetime.
void FadeOut (float time_in_s=-1)
Starts the fade out process and destroys the light when its done. Optional parameter allows you to set time of this fade out in seconds. If not set, then default value (from SetFadeOutTime(...)) is used.
void FadeRadiusTo (float value, float time_in_s)
Fades the radius of the light to the given value.
Object GetAttachmentParent ()
Returns attachment parent.
float GetDancingShadowsAmplitude ()
Returns max movement range of pointlight within the dancing shadow effect.
float GetDancingShadowsMovementSpeed ()
Returns max movement speed of pointlight within the dancing shadow effect.
float GetDisableShadowsWithinRadius ()
Returns the range you put inside SetDisableShadowsWithinRadius(...)
float GetFlickerAmplitudeCoefMax ()
Returns flicker amplitude maximum.
float GetFlickerAmplitudeCoefMin ()
Returns flicker amplitude minimum.
float GetFlickerSpeed ()
Returns flicker speed.
private void HandleBrightnessFadeing (float timeSlice)
void HandleDancingShadows (float time, float timeSlice)
void HandleFlickering (float time, float timeSlice)
private void HandleRadiusFadeing (float timeSlice)
override bool IsScriptedLight ()
void OnFrameLightSource (IEntity other, float timeSlice)
Override this for custom functionality.
void ScriptedLightBase ()
Constructor. Everything here is executed before the constructor of all children.
void SetBrightnessTo (float value)
Sets the brightness of the light.
void SetDancingShadowsAmplitude (float max_deviation_in_meters)
Sets the maximum range of the point light within the dancing shadows effect.
void SetDancingShadowsMovementSpeed (float speed_in_meters_per_frame)
Sets the maximum speed of the point light within the dancing shadows effect.
void SetDisableShadowsWithinRadius (float radius_in_m)
When the light source gets within this radius (radius_in_m) around the camera, then it's shadows are disabled.
void SetFadeOutTime (float time_in_s)
Sets the fade out time in seconds. Fade out begins automatically as the light nears the end of its life time, or when method FadeOut() is called.
void SetFlickerAmplitude (float coef)
Sets the change coefficient of flickering light. (0.0 - 1.0 values, result of greater values are period time of light off)
void SetFlickerAmplitudeMax (float coef)
void SetFlickerAmplitudeMin (float coef)
void SetFlickerSpeed (float speed)
Sets speed of light flickering (random brightness coefficient change per second)
void SetLifetime (float life_in_s)
Makes the light destroy itself after the given time in seconds. The light will fade out if it's set to do so with SetFadeOutTime(...)
void SetRadiusTo (float value)
Sets the radius of the light.
void TryShadowOptimization ()
Optimizes shadows by disabling them on this light source while it's within the given radius around the camera.
private void UpdateLightMode (string slotName)
void UpdateMode ()
void ~ScriptedLightBase ()
Static Private Member Functions
static ScriptedLightBase CreateLight (typename name, vector global_pos="0 0 0", float fade_in_time_in_s=0)
Creates an instance of light on the given position. Optionally, use fade_in_time_in_s parameter to make the light fade into existence.
static ScriptedLightBase CreateLightAtObjMemoryPoint (typename name, notnull Object target, string memory_point_start, string memory_point_target="", vector global_pos="0 0 0", float fade_in_time_in_s=0)
Private Attributes
float m_Brightness
float m_BrightnessPulse
float m_BrightnessPulseAmplitudeMax
float m_BrightnessPulseAmplitudeMin
float m_BrightnessPulseSpeed
float m_BrightnessSpeedOfChange = 1
float m_BrightnessTarget
float m_DancingShadowsAmplitude
vector m_DancingShadowsLocalPos
float m_DancingShadowsSpeed
ref Timer m_DeleteTimer
float m_FadeInTime = -1
float m_FadeOutTime = -1
bool m_IsDebugEnabled = false
float m_LifetimeEnd = -1
float m_LifetimeStart
vector m_LocalOri
vector m_LocalPos
float m_OptimizeShadowsRadius = 0
Object m_Parent
float m_Radius
float m_RadiusSpeedOfChange = 1
float m_RadiusTarget
Static Private Attributes
static ref set< ScriptedLightBase > m_NightTimeOnlyLights = new set<ScriptedLightBase>()
Detailed Description
Definition at line 10 of file scriptedlightbase.c.
Constructor & Destructor Documentation
~ScriptedLightBase()
void EntityLightSource::~ScriptedLightBase () inline private
Definition at line 49 of file scriptedlightbase.c.
    {
        if (m_NightTimeOnlyLights)
        {
            int index = m_NightTimeOnlyLights.Find(this);
            if (index != -1)
            {
                m_NightTimeOnlyLights.Remove(index);
            }
        }
    }
Member Function Documentation
AddLifetime()
void EntityLightSource::AddLifetime (float life_in_s) inline private
Prolongs the lifetime of the light in seconds. Use negative number to shorten its lifetime.
Definition at line 372 of file scriptedlightbase.c.
    {
        m_LifetimeEnd += life_in_s * 1000;
    }
AttachOnMemoryPoint()
void EntityLightSource::AttachOnMemoryPoint (Object parent, string memory_point_start, string memory_point_target = "") inline private
Attaches this light on the parent entity's memory point, with optional direction target memory point.
Definition at line 157 of file scriptedlightbase.c.
    {
        if (parent.MemoryPointExists(memory_point_start))
        {
            m_LocalPos = parent.GetMemoryPointPos(memory_point_start);
            vector local_ori;
            if (memory_point_target != "" )
            {
                if (parent.MemoryPointExists(memory_point_target))
                {
                    vector target_pos = parent.GetSelectionPositionLS(memory_point_target);
                    target_pos = vector.Direction(m_LocalPos, target_pos);
                    local_ori = target_pos.VectorToAngles();
                }
                else
                {
                    ErrorEx("memory point 'memory_point_target' not found when attaching light");
                }
            }
            AttachOnObject(parent, m_LocalPos, local_ori);
            UpdateMode();
        }
        else
        {
            ErrorEx("memory point 'memory_point_start' not found when attaching light");
        }
    }
References vector::Direction(), ErrorEx, m_LocalPos, and vector::VectorToAngles().
AttachOnObject()
void EntityLightSource::AttachOnObject (Object parent, vector local_pos = "0 0 0", vector local_ori = "0 0 0") inline private
Attaches this light on the parent entity, with optional position and orientation offset.
Definition at line 122 of file scriptedlightbase.c.
    {
        if (!parent)
        {
            if (m_Parent)
            {
                m_Parent.RemoveChild(this);
            }
            return;
        }
        else
        {
            if (m_Parent)
            {
                m_Parent.RemoveChild(this);
            }
        }
        m_Parent = parent;
        m_LocalPos = local_pos;
        m_LocalOri = local_ori;
        SetOrientation(local_ori);
        SetPosition(local_pos);
        parent.AddChild(this, -1);
        parent.Update();
    }
References m_LocalOri, m_LocalPos, m_Parent, SetOrientation(), and SetPosition().
CheckFadeOut()
private void EntityLightSource::CheckFadeOut (int current_time) inline private
Definition at line 622 of file scriptedlightbase.c.
    {
        // Control fade out of the light
        if ( m_FadeOutTime != -1  &&  m_LifetimeEnd != -1  &&  current_time > m_LifetimeEnd - m_FadeOutTime )
        {
            m_FadeOutTime = -1;
            m_FadeInTime = -1; // Stop fade in process
            float time_left_in_s = (m_LifetimeEnd - current_time) * 0.001;
            FadeBrightnessTo(0, time_left_in_s);
            FadeRadiusTo(0, time_left_in_s);
        }
    }
CheckIfParentIsInCargo()
void EntityLightSource::CheckIfParentIsInCargo () inline private
Definition at line 570 of file scriptedlightbase.c.
    {
        // TO DO: OPTIMIZE AND REFACTOR! THIS MUST BE HANDLED IN AN EVENT, NOT PER FRAME!
        if (m_Parent)
        {
            EntityAI parent_EAI = EntityAI.Cast( m_Parent );
            if (parent_EAI) // Check if the Cast was successfull
            {
                GameInventory GI = parent_EAI.GetInventory();
                if (GI) // Prevents handling of light on the parent item when it's projected in inventory as the item in inventory character's hands.
                {
                    bool is_in_cargo = GI.IsInCargo();
                    if (!is_in_cargo)
                    {
                        EntityAI parent2 = parent_EAI.GetHierarchyParent();
                        if (parent2  &&  parent2.GetInventory())
{
                            is_in_cargo = parent2.GetInventory().IsInCargo();
                        }
                    }
                    if ( is_in_cargo )
                    {
                        SetEnabled(false);
                    }
                    else
                    {
                        SetEnabled(true);
                    }
                }
            }
        }
    }
References m_Parent.
CheckLifetime()
private bool EntityLightSource::CheckLifetime (int current_time) inline private
Definition at line 610 of file scriptedlightbase.c.
    {
        if ( current_time > m_LifetimeEnd  &&  m_LifetimeEnd != -1 )
        {
            Destroy();
            return false;
        }
        return true;
    }
References Destroy().
CorrectLightPulseDuringDaylight()
void EntityLightSource::CorrectLightPulseDuringDaylight () inline private
Call this after using SetBrightness(...) to fix light's intensity during daytime.
Definition at line 260 of file scriptedlightbase.c.
    {
        if (m_Brightness < 100)
        {
            float v = m_Brightness * 0.01;
            if (v > 0)
            {
                float brightness_compesation = 1 / v;
                float compenset_brightness = (m_Brightness * m_BrightnessPulse) * brightness_compesation;
                SetBrightness(compenset_brightness);
                SetPulseCoef(v);
            }
        }
        else
        {
            SetPulseCoef(1);
        }
    }
CreateLight()
static ScriptedLightBase EntityLightSource::CreateLight (typename name , vector global_pos = "0 0 0", float fade_in_time_in_s = 0) inline static private
Creates an instance of light on the given position. Optionally, use fade_in_time_in_s parameter to make the light fade into existence.
Definition at line 220 of file scriptedlightbase.c.
    {
        ScriptedLightBase light_instance;
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // Client side
        {
            light_instance = ScriptedLightBase.Cast( GetGame().CreateObject(name.ToString(), global_pos, true) );
            if (!light_instance)
            {
                Error("Error! Light entity of name " + name.ToString() + " cannot be spawned! This name is incorrect or not inherited from ScriptedLightBase." );
                return null;
            }
            if (fade_in_time_in_s != 0)
            {
                light_instance.FadeIn(fade_in_time_in_s);
            }
        }
        else // Server side
        {
            if ( GetGame().IsDebug() )
            {
                Error("An instance of ScriptedLightBase was attempted to spawn on server side! Lights are CLIENT SIDE ONLY!");
            }
        }
        return light_instance;
    }
References Error(), GetGame(), name, and string::ToString().
CreateLightAtObjMemoryPoint()
static ScriptedLightBase EntityLightSource::CreateLightAtObjMemoryPoint (typename name , notnull Object target, string memory_point_start, string memory_point_target = "", vector global_pos = "0 0 0", float fade_in_time_in_s = 0) inline static private
Definition at line 208 of file scriptedlightbase.c.
    {
        ScriptedLightBase light;
        if (target.MemoryPointExists(memory_point_start))
        {
            light = CreateLight(name, global_pos, fade_in_time_in_s);
            light.AttachOnMemoryPoint(target, memory_point_start, memory_point_target);
        }
        return light;
    }
References CreateLight(), and name.
DeleteLightNow()
private void EntityLightSource::DeleteLightNow () inline private
Definition at line 116 of file scriptedlightbase.c.
    {
        GetGame().ObjectDelete(this);
    }
References GetGame(), and CGame::ObjectDelete().
DeleteLightWithDelay()
private void EntityLightSource::DeleteLightWithDelay () inline private
Correct way of deleting light from memory. It is necesarry to have this delay due to hierarchy.
Definition at line 101 of file scriptedlightbase.c.
    {
        DetachFromParent(); // This is the reason for the delay
        if (GetGame())
        {
            if (!m_DeleteTimer)
                m_DeleteTimer = new Timer( CALL_CATEGORY_SYSTEM );
            m_DeleteTimer.Run( 0.03 , this, "DeleteLightNow", NULL, true);
        }
    }
References CALL_CATEGORY_SYSTEM, GetGame(), and m_DeleteTimer.
Destroy()
void EntityLightSource::Destroy () inline private
Switches off the light and deletes it from memory.
Definition at line 319 of file scriptedlightbase.c.
    {
        ClearEventMask(EntityEvent.FRAME);
        SetEnabled(false);
        if (m_Parent)
            DeleteLightWithDelay();
        else
            DeleteLightNow();
    }
References m_Parent.
DetachFromParent()
void EntityLightSource::DetachFromParent () inline private
Detaches this light from its parent entity.
Definition at line 188 of file scriptedlightbase.c.
    {
        if (!m_Parent)
        {
            m_Parent = Object.Cast( GetParent() );
        }
        if (m_Parent)
        {
            if ( !m_Parent.ToDelete()  &&  !ToDelete() )
            {
                m_Parent.RemoveChild(this);
            }
        }
        m_Parent = null;
        m_LocalPos = Vector(0,0,0);
        m_LocalOri = Vector(0,0,0);
    }
References GetParent(), m_LocalOri, m_LocalPos, m_Parent, ToDelete(), and Vector().
EnableDebug()
void EntityLightSource::EnableDebug (bool state) inline private
Enables some debug functionality of this light.
Definition at line 434 of file scriptedlightbase.c.
    {
        m_IsDebugEnabled = state;
    }
EOnFrame()
override void EntityLightSource::EOnFrame (IEntity other, float timeSlice) inline private
On frame event. If you want to control your light within your own rules then override the event OnFrameLightSource and put your code there.
Definition at line 384 of file scriptedlightbase.c.
    {
        // Control lifetime of the light
        int current_time = GetGame().GetTime();
        if ( CheckLifetime(current_time) )
        {
            SetRadius(m_Radius);
        }
        else
        {
            return;
        }
        HandleFlickering(current_time - m_LifetimeStart, timeSlice);
        HandleDancingShadows(current_time - m_LifetimeStart, timeSlice);
        CheckFadeOut(current_time);
        HandleBrightnessFadeing(timeSlice);
        HandleRadiusFadeing(timeSlice);
        CheckIfParentIsInCargo();
        TryShadowOptimization();
        OnFrameLightSource(other, timeSlice);
    }
References GetGame(), CGame::GetTime(), and m_Radius.
EOnInit()
override void EntityLightSource::EOnInit (IEntity other, int extra) inline private
Definition at line 61 of file scriptedlightbase.c.
    {
        if (!IsVisibleDuringDaylight())
        {
            PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
            if (player && player.m_UndergroundPresence)
                SetVisibleDuringDaylight(true);
            m_NightTimeOnlyLights.Insert(this);
        }
    }
References GetGame(), and GetPlayer().
FadeBrightnessTo()
void EntityLightSource::FadeBrightnessTo (float value, float time_in_s) inline private
Fades the brightness of the light to the given value.
Definition at line 281 of file scriptedlightbase.c.
    {
        m_BrightnessTarget = value;
        if (time_in_s == 0)
        {
            m_BrightnessSpeedOfChange = 9999;
        }
        else
        {
            m_BrightnessSpeedOfChange = Math.AbsFloat(m_Brightness - m_BrightnessTarget) / time_in_s;
        }
    }
References Math::AbsFloat().
FadeIn()
void EntityLightSource::FadeIn (float time_in_s) inline private
Makes the light fade into existence. Works only at the moment the light is created. Consider using FadeBrightnessTo(...) and FadeRadiusTo(...) at anytime later during lifetime.
Definition at line 364 of file scriptedlightbase.c.
    {
        float brightness = m_Brightness;
        SetBrightnessTo(0);
        FadeBrightnessTo(brightness, time_in_s);
    }
FadeOut()
void EntityLightSource::FadeOut (float time_in_s = -1) inline private
Starts the fade out process and destroys the light when its done. Optional parameter allows you to set time of this fade out in seconds. If not set, then default value (from SetFadeOutTime(...)) is used.
Definition at line 343 of file scriptedlightbase.c.
    {
        float time_in_ms = time_in_s * 1000;
        if (time_in_s == -1)
        {
            float kill_time_in_s = m_FadeOutTime*0.001;
            FadeBrightnessTo(0, kill_time_in_s);
            FadeRadiusTo(0, kill_time_in_s);
            SetLifetime(kill_time_in_s);
        }
        else
        {
            FadeBrightnessTo(0, time_in_s);
            FadeRadiusTo(0, time_in_s);
            SetLifetime(time_in_s);
        }
    }
FadeRadiusTo()
void EntityLightSource::FadeRadiusTo (float value, float time_in_s) inline private
Fades the radius of the light to the given value.
Definition at line 304 of file scriptedlightbase.c.
    {
        m_RadiusTarget = value;
        if (time_in_s == 0)
        {
            m_RadiusSpeedOfChange = 9999;
        }
        else
        {
            m_RadiusSpeedOfChange = Math.AbsFloat(m_Radius - m_RadiusTarget) / time_in_s;
        }
    }
References Math::AbsFloat(), and m_Radius.
GetAttachmentParent()
Object EntityLightSource::GetAttachmentParent () inline private
Returns attachment parent.
Definition at line 151 of file scriptedlightbase.c.
    {
        return m_Parent;
    }
References m_Parent.
GetDancingShadowsAmplitude()
float EntityLightSource::GetDancingShadowsAmplitude () inline private
Returns max movement range of pointlight within the dancing shadow effect.
Definition at line 422 of file scriptedlightbase.c.
    {
        return m_DancingShadowsAmplitude;
    }
GetDancingShadowsMovementSpeed()
float EntityLightSource::GetDancingShadowsMovementSpeed () inline private
Returns max movement speed of pointlight within the dancing shadow effect.
Definition at line 428 of file scriptedlightbase.c.
    {
        return m_DancingShadowsSpeed;
    }
GetDisableShadowsWithinRadius()
float EntityLightSource::GetDisableShadowsWithinRadius () inline private
Returns the range you put inside SetDisableShadowsWithinRadius(...)
Definition at line 565 of file scriptedlightbase.c.
    {
        return m_OptimizeShadowsRadius;
    }
GetFlickerAmplitudeCoefMax()
float EntityLightSource::GetFlickerAmplitudeCoefMax () inline private
Returns flicker amplitude maximum.
Definition at line 529 of file scriptedlightbase.c.
    {
        return m_BrightnessPulseAmplitudeMax;
    }
GetFlickerAmplitudeCoefMin()
float EntityLightSource::GetFlickerAmplitudeCoefMin () inline private
Returns flicker amplitude minimum.
Definition at line 535 of file scriptedlightbase.c.
    {
        return m_BrightnessPulseAmplitudeMin;
    }
GetFlickerSpeed()
float EntityLightSource::GetFlickerSpeed () inline private
Returns flicker speed.
Definition at line 523 of file scriptedlightbase.c.
    {
        return m_BrightnessPulseSpeed;
    }
HandleBrightnessFadeing()
private void EntityLightSource::HandleBrightnessFadeing (float timeSlice) inline private
Definition at line 636 of file scriptedlightbase.c.
    {
        if ( m_Brightness != m_BrightnessTarget )
        {
            float brightness_difference = m_Brightness - m_BrightnessTarget;
            if (brightness_difference > m_BrightnessSpeedOfChange*timeSlice)
                brightness_difference = m_BrightnessSpeedOfChange*timeSlice;
            if (brightness_difference < -m_BrightnessSpeedOfChange*timeSlice)
                brightness_difference = -m_BrightnessSpeedOfChange*timeSlice;
            m_Brightness -= brightness_difference;
            if ( m_Brightness > 0  ||  m_BrightnessTarget > 0)
            {
                SetBrightness(m_Brightness * m_BrightnessPulse);
                CorrectLightPulseDuringDaylight();
            }
            else
            {
                Destroy();
                return;
            }
        }
        else
        {
            SetBrightness(m_Brightness * m_BrightnessPulse);
            CorrectLightPulseDuringDaylight();
        }
    }
References Destroy().
HandleDancingShadows()
void EntityLightSource::HandleDancingShadows (float time, float timeSlice) inline private
Definition at line 440 of file scriptedlightbase.c.
    {
        if (m_DancingShadowsAmplitude > 0)
        {
            for (int i = 0; i < 3; i++ )
            {
                m_DancingShadowsLocalPos[i] = m_DancingShadowsLocalPos[i] +  ( Math.RandomFloat(-m_DancingShadowsSpeed,m_DancingShadowsSpeed) * timeSlice) ;
                if (m_DancingShadowsLocalPos[i] > m_DancingShadowsAmplitude)
                    m_DancingShadowsLocalPos[i] = m_DancingShadowsAmplitude;
                if (m_DancingShadowsLocalPos[i] < -m_DancingShadowsAmplitude)
                    m_DancingShadowsLocalPos[i] = -m_DancingShadowsAmplitude;
            }
            if (m_Parent  &&  !m_Parent.ToDelete())
            {
                // In order to move with the light, it must be detached from its parent first
                m_Parent.RemoveChild(this);
                SetPosition(m_LocalPos + m_DancingShadowsLocalPos);
                m_Parent.AddChild(this, -1);
                m_Parent.Update();
            }
            if (m_IsDebugEnabled)
            {
                Particle p = ParticleManager.GetInstance().PlayInWorld( ParticleList.DEBUG_DOT, GetPosition() );
                p.SetParticleParam( EmitorParam.SIZE, 0.01);
            }
        }
        else
        {
            m_DancingShadowsLocalPos = Vector(0,0,0);
        }
    }
References ParticleList::DEBUG_DOT, GetPosition, m_LocalPos, m_Parent, ParticleManager(), Math::RandomFloat(), Particle::SetParticleParam(), SetPosition(), and Vector().
HandleFlickering()
void EntityLightSource::HandleFlickering (float time, float timeSlice) inline private
Definition at line 480 of file scriptedlightbase.c.
    {
        if (m_BrightnessPulseAmplitudeMax > 0)
        {
            m_BrightnessPulse += ( Math.RandomFloat(-m_BrightnessPulseSpeed, m_BrightnessPulseSpeed) ) * timeSlice;
            if (m_BrightnessPulse < m_BrightnessPulseAmplitudeMin + 1)
                m_BrightnessPulse = m_BrightnessPulseAmplitudeMin + 1;
            if (m_BrightnessPulse > m_BrightnessPulseAmplitudeMax + 1)
                m_BrightnessPulse = m_BrightnessPulseAmplitudeMax + 1;
        }
        else
        {
            m_BrightnessPulse = 1;
        }
    }
References Math::RandomFloat().
HandleRadiusFadeing()
private void EntityLightSource::HandleRadiusFadeing (float timeSlice) inline private
Definition at line 669 of file scriptedlightbase.c.
    {
        if ( m_Radius != m_RadiusTarget )
        {
            float radius_difference = m_Radius - m_RadiusTarget;
            if (radius_difference > m_RadiusSpeedOfChange*timeSlice)
                radius_difference = m_RadiusSpeedOfChange*timeSlice;
            if (radius_difference < -m_RadiusSpeedOfChange*timeSlice)
                radius_difference = -m_RadiusSpeedOfChange*timeSlice;
            m_Radius -= radius_difference;
            if ( m_Radius > 0  ||  m_RadiusTarget > 0)
            {
                SetRadius(m_Radius);
            }
            else
            {
                Destroy();
                return;
            }
        }
        else
        {
            SetRadius(m_Radius);
        }
    }
References Destroy(), and m_Radius.
IsScriptedLight()
override bool EntityLightSource::IsScriptedLight () inline private
Definition at line 72 of file scriptedlightbase.c.
    {
        return true;
    }
OnFrameLightSource()
void EntityLightSource::OnFrameLightSource (IEntity other, float timeSlice) inline private
Override this for custom functionality.
Definition at line 378 of file scriptedlightbase.c.
    {
        // ...
    }
ScriptedLightBase()
void EntityLightSource::ScriptedLightBase () inline private
Constructor. Everything here is executed before the constructor of all children.
Definition at line 41 of file scriptedlightbase.c.
    {
        m_LifetimeStart = GetGame().GetTime();
        SetEnabled(true);
        SetEventMask(EntityEvent.FRAME);
        SetEventMask(EntityEvent.INIT);
    }
References GetGame(), and CGame::GetTime().
SetBrightnessTo()
void EntityLightSource::SetBrightnessTo (float value) inline private
Sets the brightness of the light.
Definition at line 251 of file scriptedlightbase.c.
    {
        m_Brightness = value;
        m_BrightnessTarget = value;
        SetBrightness(m_Brightness * m_BrightnessPulse);
        CorrectLightPulseDuringDaylight();
    }
SetDancingShadowsAmplitude()
void EntityLightSource::SetDancingShadowsAmplitude (float max_deviation_in_meters) inline private
Sets the maximum range of the point light within the dancing shadows effect.
Definition at line 410 of file scriptedlightbase.c.
    {
        m_DancingShadowsAmplitude = Math.AbsFloat(max_deviation_in_meters);
    }
References Math::AbsFloat().
SetDancingShadowsMovementSpeed()
void EntityLightSource::SetDancingShadowsMovementSpeed (float speed_in_meters_per_frame) inline private
Sets the maximum speed of the point light within the dancing shadows effect.
Definition at line 416 of file scriptedlightbase.c.
    {
        m_DancingShadowsSpeed = Math.AbsFloat(speed_in_meters_per_frame);
    }
References Math::AbsFloat().
SetDisableShadowsWithinRadius()
void EntityLightSource::SetDisableShadowsWithinRadius (float radius_in_m) inline private
When the light source gets within this radius (radius_in_m) around the camera, then it's shadows are disabled.
Definition at line 559 of file scriptedlightbase.c.
    {
        m_OptimizeShadowsRadius = radius_in_m;
    }
SetFadeOutTime()
void EntityLightSource::SetFadeOutTime (float time_in_s) inline private
Sets the fade out time in seconds. Fade out begins automatically as the light nears the end of its life time, or when method FadeOut() is called.
Definition at line 337 of file scriptedlightbase.c.
    {
        m_FadeOutTime = time_in_s * 1000;
    }
SetFlickerAmplitude()
void EntityLightSource::SetFlickerAmplitude (float coef) inline private
Sets the change coefficient of flickering light. (0.0 - 1.0 values, result of greater values are period time of light off)
Definition at line 506 of file scriptedlightbase.c.
    {
        m_BrightnessPulseAmplitudeMax = Math.AbsFloat(coef);
        m_BrightnessPulseAmplitudeMin = -Math.AbsFloat(coef);
    }
References Math::AbsFloat().
SetFlickerAmplitudeMax()
void EntityLightSource::SetFlickerAmplitudeMax (float coef) inline private
Definition at line 512 of file scriptedlightbase.c.
    {
        m_BrightnessPulseAmplitudeMax = coef;
    }
SetFlickerAmplitudeMin()
void EntityLightSource::SetFlickerAmplitudeMin (float coef) inline private
Definition at line 517 of file scriptedlightbase.c.
    {
        m_BrightnessPulseAmplitudeMin = coef;
    }
SetFlickerSpeed()
void EntityLightSource::SetFlickerSpeed (float speed) inline private
Sets speed of light flickering (random brightness coefficient change per second)
Definition at line 500 of file scriptedlightbase.c.
    {
        m_BrightnessPulseSpeed = speed;
    }
SetLifetime()
void EntityLightSource::SetLifetime (float life_in_s) inline private
Makes the light destroy itself after the given time in seconds. The light will fade out if it's set to do so with SetFadeOutTime(...)
Definition at line 330 of file scriptedlightbase.c.
    {
        if(GetGame())
            m_LifetimeEnd = GetGame().GetTime() + life_in_s * 1000;
    }
References GetGame(), and CGame::GetTime().
SetRadiusTo()
void EntityLightSource::SetRadiusTo (float value) inline private
Sets the radius of the light.
Definition at line 296 of file scriptedlightbase.c.
    {
        m_Radius = value;
        m_RadiusTarget = value;
        SetRadius(m_Radius);
    }
References m_Radius.
TryShadowOptimization()
void EntityLightSource::TryShadowOptimization () inline private
Optimizes shadows by disabling them on this light source while it's within the given radius around the camera.
Definition at line 541 of file scriptedlightbase.c.
    {
        if (m_OptimizeShadowsRadius > 0)
        {
            float distance_to_camera = vector.Distance( GetPosition(), GetGame().GetCurrentCameraPosition() );
            if (distance_to_camera < m_OptimizeShadowsRadius)
            {
                SetCastShadow(false);
            }
            else
            {
                SetCastShadow(true);
            }
        }
    }
References vector::Distance(), GetGame(), and GetPosition.
UpdateLightMode()
private void EntityLightSource::UpdateLightMode (string slotName) private
UpdateMode()
void EntityLightSource::UpdateMode () inline private
Definition at line 77 of file scriptedlightbase.c.
    {
        ItemBase item = ItemBase.Cast(m_Parent);
        if (item)
        {
            InventoryLocation il = new InventoryLocation;
            item.GetInventory().GetCurrentInventoryLocation( il );
            string slotName;
            if (il.GetType() == InventoryLocationType.GROUND)
            {
                slotName = "Ground";
            }
            else if (il.GetSlot() != -1)
            {
                slotName = InventorySlots.GetSlotName(il.GetSlot());
            }
            UpdateLightMode(slotName);
        }
    }
References InventoryLocation::GetSlot(), InventorySlots::GetSlotName(), InventoryLocation::GetType(), and m_Parent.
Member Data Documentation
m_Brightness
float EntityLightSource::m_Brightness private
Definition at line 18 of file scriptedlightbase.c.
m_BrightnessPulse
float EntityLightSource::m_BrightnessPulse private
Definition at line 19 of file scriptedlightbase.c.
m_BrightnessPulseAmplitudeMax
float EntityLightSource::m_BrightnessPulseAmplitudeMax private
Definition at line 21 of file scriptedlightbase.c.
m_BrightnessPulseAmplitudeMin
float EntityLightSource::m_BrightnessPulseAmplitudeMin private
Definition at line 22 of file scriptedlightbase.c.
m_BrightnessPulseSpeed
float EntityLightSource::m_BrightnessPulseSpeed private
Definition at line 20 of file scriptedlightbase.c.
m_BrightnessSpeedOfChange
float EntityLightSource::m_BrightnessSpeedOfChange = 1 private
Definition at line 24 of file scriptedlightbase.c.
m_BrightnessTarget
float EntityLightSource::m_BrightnessTarget private
Definition at line 23 of file scriptedlightbase.c.
m_DancingShadowsAmplitude
float EntityLightSource::m_DancingShadowsAmplitude private
Definition at line 27 of file scriptedlightbase.c.
m_DancingShadowsLocalPos
vector EntityLightSource::m_DancingShadowsLocalPos private
Definition at line 34 of file scriptedlightbase.c.
m_DancingShadowsSpeed
float EntityLightSource::m_DancingShadowsSpeed private
Definition at line 28 of file scriptedlightbase.c.
m_DeleteTimer
ref Timer EntityLightSource::m_DeleteTimer private
Definition at line 36 of file scriptedlightbase.c.
m_FadeInTime
float EntityLightSource::m_FadeInTime = -1 private
Definition at line 15 of file scriptedlightbase.c.
m_FadeOutTime
float EntityLightSource::m_FadeOutTime = -1 private
Definition at line 14 of file scriptedlightbase.c.
m_IsDebugEnabled
bool EntityLightSource::m_IsDebugEnabled = false private
Definition at line 29 of file scriptedlightbase.c.
m_LifetimeEnd
float EntityLightSource::m_LifetimeEnd = -1 private
Definition at line 13 of file scriptedlightbase.c.
m_LifetimeStart
float EntityLightSource::m_LifetimeStart private
Definition at line 12 of file scriptedlightbase.c.
m_LocalOri
vector EntityLightSource::m_LocalOri private
Definition at line 33 of file scriptedlightbase.c.
m_LocalPos
vector EntityLightSource::m_LocalPos private
Definition at line 32 of file scriptedlightbase.c.
m_NightTimeOnlyLights
ref set<ScriptedLightBase> EntityLightSource::m_NightTimeOnlyLights = new set<ScriptedLightBase>() static private
Definition at line 38 of file scriptedlightbase.c.
m_OptimizeShadowsRadius
float EntityLightSource::m_OptimizeShadowsRadius = 0 private
Definition at line 26 of file scriptedlightbase.c.
m_Parent
Object EntityLightSource::m_Parent private
Definition at line 31 of file scriptedlightbase.c.
m_Radius
float EntityLightSource::m_Radius private
Definition at line 16 of file scriptedlightbase.c.
m_RadiusSpeedOfChange
float EntityLightSource::m_RadiusSpeedOfChange = 1 private
Definition at line 25 of file scriptedlightbase.c.
m_RadiusTarget
float EntityLightSource::m_RadiusTarget private
Definition at line 17 of file scriptedlightbase.c.