DayzKode: MainMenuButtonEffect Class Reference
MainMenuButtonEffect Class Reference
Private Member Functions
void MainMenuButtonEffect ()
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
void OnWidgetScriptInit (ButtonWidget w)
protected void Update (float tDelta)
void ~MainMenuButtonEffect ()
Private Attributes
reference float amount
protected ref AnimatorTimer m_anim
protected ButtonWidget m_root
protected float m_textProportion
protected float m_textProportion2
reference float speed
Detailed Description
Definition at line 1 of file mainmenubuttoneffect.c.
Constructor & Destructor Documentation
MainMenuButtonEffect()
void MainMenuButtonEffect::MainMenuButtonEffect () inline private
Definition at line 11 of file mainmenubuttoneffect.c.
    {
        if ( GetGame() )
        {
            GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(this.Update);
        }
        m_anim = new AnimatorTimer();
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), and ScriptedWidgetEventHandler::Update().
~MainMenuButtonEffect()
void MainMenuButtonEffect::~MainMenuButtonEffect () inline private
Definition at line 21 of file mainmenubuttoneffect.c.
    {
        if ( GetGame() && GetGame().GetUpdateQueue(CALL_CATEGORY_GUI) )
        {
            GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Remove(this.Update);
        }
    }
References CALL_CATEGORY_GUI, GetGame(), GetUpdateQueue(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and ScriptedWidgetEventHandler::Update().
Member Function Documentation
OnFocus()
override bool MainMenuButtonEffect::OnFocus (Widget w, int x, int y) inline private
Definition at line 49 of file mainmenubuttoneffect.c.
    {
        //if ( !m_anim.IsRunning() ) m_textProportion = m_root.GetTextProportion();
        if ( !m_anim.IsRunning() )
        {
            m_root.GetPos( m_textProportion, m_textProportion2 );
        }
        m_anim.Animate(1.0, speed);
        return false;
    }
References AnimatorTimer::Animate(), AnimatorTimer::IsRunning(), m_anim, m_root, m_textProportion, m_textProportion2, and speed.
OnFocusLost()
override bool MainMenuButtonEffect::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 62 of file mainmenubuttoneffect.c.
    {
        m_anim.Animate(0.0, speed);
        return false;
    }
References AnimatorTimer::Animate(), m_anim, and speed.
OnWidgetScriptInit()
void MainMenuButtonEffect::OnWidgetScriptInit (ButtonWidget w) inline private
Definition at line 30 of file mainmenubuttoneffect.c.
    {
        m_root = w;
        m_root.SetHandler(this);
    }
References m_root.
Update()
protected void MainMenuButtonEffect::Update (float tDelta) inline private
Definition at line 37 of file mainmenubuttoneffect.c.
    {
        m_anim.Tick(tDelta);
        float p = amount * m_anim.GetValue();
        //m_root.SetTextProportion( m_textProportion + (p * 0.5) );
        m_root.SetTextOffset( p * 4, 0 );
        float c = 1.0 - m_anim.GetValue();
        m_root.SetTextColor(ARGBF(1, 1, c, c));
    }
References amount, ARGBF(), AnimatorTimer::GetValue(), m_anim, m_root, and AnimatorTimer::Tick().
Member Data Documentation
amount
reference float MainMenuButtonEffect::amount private
Definition at line 4 of file mainmenubuttoneffect.c.
Referenced by Update().
m_anim
protected ref AnimatorTimer MainMenuButtonEffect::m_anim private
Definition at line 8 of file mainmenubuttoneffect.c.
Referenced by OnFocus(), OnFocusLost(), and Update().
m_root
protected ButtonWidget MainMenuButtonEffect::m_root private
Definition at line 7 of file mainmenubuttoneffect.c.
Referenced by OnFocus(), OnWidgetScriptInit(), and Update().
m_textProportion
protected float MainMenuButtonEffect::m_textProportion private
Definition at line 5 of file mainmenubuttoneffect.c.
Referenced by OnFocus().
m_textProportion2
protected float MainMenuButtonEffect::m_textProportion2 private
Definition at line 6 of file mainmenubuttoneffect.c.
Referenced by OnFocus().
speed
reference float MainMenuButtonEffect::speed private
Definition at line 3 of file mainmenubuttoneffect.c.
Referenced by OnFocus(), and OnFocusLost().