DayzKode: OptionSelectorSliderSetup Class Reference
OptionSelectorSliderSetup Class Reference
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Private Member Functions
override void Disable ()
override void Enable ()
override bool OnUpdate (Widget w)
void OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max)
void OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max)
void SetSlider2Value (float value)
Private Attributes
protected SliderWidget m_Slider2
Detailed Description
This Option Selector handles a Slider Marker, which basically has 2 sliders One slider is for selecting the value, and the other slider is for displaying some other value/ information.
Parameters
m_Slider2 other slider value, which can be used to convery some other info to the player
Definition at line 6 of file optionselectorlevelmarker.c.
Member Function Documentation
Disable()
override void OptionSelectorSliderSetup::Disable () inline private
Definition at line 42 of file optionselectorlevelmarker.c.
    {
        super.Disable();
        m_Slider2.SetFlags(WidgetFlags.IGNOREPOINTER);
    }
Enable()
override void OptionSelectorSliderSetup::Enable () inline private
Definition at line 36 of file optionselectorlevelmarker.c.
    {
        super.Enable();
        m_Slider2.ClearFlags(WidgetFlags.IGNOREPOINTER);
    }
Referenced by OptionSelectorLevelMarker(), and OptionSelectorSlider().
OnUpdate()
override bool OptionSelectorSliderSetup::OnUpdate (Widget w) inline private
Definition at line 53 of file optionselectorlevelmarker.c.
    {
        return false;
    }
OptionSelectorLevelMarker()
void OptionSelectorSliderSetup::OptionSelectorLevelMarker (Widget parent, float value, ScriptedWidgetEventHandler parentMenu, bool disabled, float min, float max) inline private
Definition at line 10 of file optionselectorlevelmarker.c.
    {
        m_Root                  = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/option_level_marker.layout", parent);
        #ifdef PLATFORM_CONSOLE
            m_Parent                = parent.GetParent().GetParent();
        #else
        #ifdef PLATFORM_WINDOWS
            m_Parent                = parent.GetParent();
        #endif
        #endif
        m_SelectorType          = 1;
        m_ParentClass           = parentMenu;
        m_Slider                = SliderWidget.Cast(m_Root.FindAnyWidget( "marker_value" ));
        m_Slider2               = SliderWidget.Cast(m_Root.FindAnyWidget( "other_slider_value" ));
        m_MinValue                  = min;
        m_MaxValue                  = max;
        SetValue(value, false);
        SetSlider2Value( 0 );
        Enable();
        m_Parent.SetHandler(this);
    }
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, SetSlider2Value(), and SetValue().
OptionSelectorSlider()
void OptionSelectorSliderSetup::OptionSelectorSlider (Widget parent, float value, ScriptedWidgetEventHandler parent_menu, bool disabled, float min, float max) inline private
Definition at line 3 of file optionselectorslider.c.
    {
        m_Root                  = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/option_slider.layout", parent );
        #ifdef PLATFORM_CONSOLE
            m_Parent                = parent.GetParent().GetParent();
        #else
        #ifdef PLATFORM_WINDOWS
            m_Parent                = parent.GetParent();
        #endif
        #endif
        m_SelectorType              = 1;
        m_ParentClass               = parent_menu;
        m_Slider                    = SliderWidget.Cast( m_Root.FindAnyWidget( "option_value" ) );
        m_Slider.SetCurrent( value );
        //m_DisablePanel                = m_Parent.GetParent().FindAnyWidget( m_Parent.GetName() + "_disable" );
        /*
        if ( !m_DisablePanel )
        {
            Print("Cant found disable panel: "+ m_Parent.GetName() );
        }
        */
        m_MinValue                  = min;
        m_MaxValue                  = max;
        SetValue( value );
        Enable();
        /*
        m_Enabled = !disabled;
        if( m_Enabled )
        {
            Enable();
        }
        else
        {
            Disable();
        }
        */
        //#ifdef PLATFORM_CONSOLE
        m_Parent.SetHandler( this );
        //#endif
    }
References WorkspaceWidget::CreateWidgets(), Enable(), GetGame(), CGame::GetWorkspace(), m_MaxValue, m_MinValue, m_Parent, m_Root, and SetValue().
SetSlider2Value()
void OptionSelectorSliderSetup::SetSlider2Value (float value) inline private
Definition at line 48 of file optionselectorlevelmarker.c.
    {
        m_Slider2.SetCurrent(NormalizeInput(value));
    }
Referenced by OptionSelectorLevelMarker().
Member Data Documentation
m_Slider2
protected SliderWidget OptionSelectorSliderSetup::m_Slider2 private
Definition at line 8 of file optionselectorlevelmarker.c.