DayzKode: OpenDirPlugin Class Reference
OpenDirPlugin Class Reference
Private Member Functions
override void Configure ()
void OkButton ()
override void Run ()
Detailed Description
Definition at line 2 of file opendir.c.
Member Function Documentation
Configure()
override void OpenDirPlugin::Configure () inline private
Definition at line 45 of file opendir.c.
    {
        Workbench.ScriptDialog("Configure OpenDir", "Usage: \n$path - will be replaced with file name", this);
    }
References Workbench::ScriptDialog().
OkButton()
void OpenDirPlugin::OkButton () inline private
Definition at line 51 of file opendir.c.
{}
Run()
override void OpenDirPlugin::Run () inline private
Definition at line 4 of file opendir.c.
    {
        ScriptEditor mod = Workbench.GetModule("ScriptEditor");
        if (mod)
        {
            string file;
            string absPath;
            if (mod.GetCurrentFile(file) && Workbench.GetAbsolutePath(file, absPath))
            {
                if (absPath.Length() < 2) return;
                absPath.Replace("\\", "/");
                if (absPath[1] != ":")
                {
                    string cwd;
                    Workbench.GetCwd(cwd);
                    absPath = cwd + "/" + absPath;
                }
                int index = absPath.IndexOf("/");
                int last_index = index;
                while(index != -1)
                {
                    last_index = index;
                    index = absPath.IndexOfFrom(last_index + 1, "/");
                }
                if (last_index == -1) return;
                string path = absPath.Substring(0, last_index);
                string command;
                command.Replace("$path", path);
                //Print(path);
                //Workbench.RunCmd(command);
                Workbench.RunCmd("cmd /c \"start " + path +"\"");
            }
        }
    }
References Workbench::GetAbsolutePath(), ScriptEditor::GetCurrentFile(), Workbench::GetCwd(), Workbench::GetModule(), string::IndexOf(), string::IndexOfFrom(), string::Length(), path, string::Replace(), Workbench::RunCmd(), and string::Substring().