DayzKode: TFModule Class Reference
TFModule Class Reference
Private Member Functions
void AddTest (Class instance, string test, bool repeat)
int Count ()
int Failed ()
int Pending ()
void PrintResult (string prefix="", TestFramework caller=null, string function="")
string Result ()
bool Run (bool fatal, float dt)
private bool RunTest (TFCaller caller, float dt)
int Success ()
void TFModule ()
Private Attributes
private int m_Count
private int m_Failed
private ref array< string > m_FailedTests
private ref TFResultArr m_Results
private ref array< string > m_SucceededTests
private int m_Success
private ref TFCallerArr m_Tests
Detailed Description
Definition at line 82 of file testframework.c.
Constructor & Destructor Documentation
TFModule()
void TFModule::TFModule () inline private
Definition at line 94 of file testframework.c.
    {
        m_Tests = {};
        m_Results = {};
        m_SucceededTests = {};
        m_FailedTests = {};
    }
References m_FailedTests, m_Results, m_SucceededTests, and m_Tests.
Member Function Documentation
AddTest()
void TFModule::AddTest (Class instance, string test, bool repeat) inline private
Definition at line 123 of file testframework.c.
    {
        ++m_Count;
        TFResult result = new TFResult(TFR.PENDING);
        m_Results.Insert(result);
        m_Tests.Insert(new TFCaller(instance, test, result));
    }
References m_Count, m_Results, m_Tests, and TFResult().
Referenced by AddFrameTest(), and AddInitTest().
Count()
int TFModule::Count () inline private
Definition at line 103 of file testframework.c.
    {
        return m_Count;
    }
References m_Count.
Referenced by Result().
Failed()
int TFModule::Failed () inline private
Definition at line 108 of file testframework.c.
    {
        return m_Failed;
    }
References m_Failed.
Referenced by Result().
Pending()
int TFModule::Pending () inline private
Definition at line 118 of file testframework.c.
    {
        return m_Count - (m_Failed + m_Success);
    }
References m_Count, m_Failed, and m_Success.
Referenced by Result().
PrintResult()
void TFModule::PrintResult (string prefix = "", TestFramework caller = null, string function = "") inline private
Definition at line 189 of file testframework.c.
    {
        Debug.TFLog(string.Format("%1%2", prefix, Result()), caller, function);
        if (m_SucceededTests.Count())
        {
            Debug.TFLog("   |-[SUCCESS]", caller, function);
            foreach (string success : m_SucceededTests)
            {
                Debug.TFLog(string.Format("        |- %1", success), caller, function);
            }
        }
        if (m_FailedTests.Count())
        {
            Debug.TFLog("   |-[FAILED]", caller, function);
            foreach (string fail : m_FailedTests)
            {
                Debug.TFLog(string.Format("        |- %1", fail), caller, function);
            }
        }
    }
References m_FailedTests, m_SucceededTests, Result(), and Debug::TFLog().
Referenced by ~TestFramework().
Result()
string TFModule::Result () inline private
Definition at line 184 of file testframework.c.
    {
        return string.Format("{ [TFModule] :: Tests: %1 | Success: %2 | Failed: %3 | Pending: %4 }", Count(), Success(), Failed(), Pending());
    }
References Count(), Failed(), string::Format(), Pending(), and Success().
Referenced by PrintResult().
Run()
bool TFModule::Run (bool fatal, float dt) inline private
Definition at line 133 of file testframework.c.
    {
        array<TFCaller> done = new array<TFCaller>();
        // Run the tests
        int runningTests = m_Tests.Count();
        for (int i = 0; i < runningTests; ++i)
        {
            TFCaller t = m_Tests[i];
            if (RunTest(t, dt))
                done.Insert(t);
        }
        // Remove finished tests
        foreach (TFCaller doneT : done)
            m_Tests.RemoveItem(doneT);
        // Validate fatal
        if (fatal && m_Tests.Count() > 0)
        {
            Print("- Active tests -------------------------");
            foreach (TFCaller rTest : m_Tests)
                Print(rTest.GetTest());
            Print("----------------------------------------");
            ErrorEx("Not all tests are done while run was fatal.");
            m_Tests.Clear();
        }
        return m_Tests.Count() == 0;
    }
References ErrorEx, m_Tests, Print(), and RunTest().
Referenced by EOnFrame(), and EOnInit().
RunTest()
private bool TFModule::RunTest (TFCaller caller, float dt) inline private
Definition at line 165 of file testframework.c.
    {
        TFR res = caller.Run(dt).Result;
        switch (res)
        {
            case TFR.FAIL:
                ++m_Failed;
                m_FailedTests.Insert(caller.GetTestEx());
                break;
            case TFR.SUCCESS:
                ++m_Success;
                m_SucceededTests.Insert(caller.GetTestEx());
                break;
        }
        return res != TFR.PENDING;
    }
References m_Failed, m_FailedTests, m_SucceededTests, and m_Success.
Referenced by Run().
Success()
int TFModule::Success () inline private
Definition at line 113 of file testframework.c.
    {
        return m_Success;
    }
References m_Success.
Referenced by Result().
Member Data Documentation
m_Count
private int TFModule::m_Count private
Definition at line 84 of file testframework.c.
Referenced by AddTest(), Count(), and Pending().
m_Failed
private int TFModule::m_Failed private
Definition at line 85 of file testframework.c.
Referenced by Failed(), Pending(), and RunTest().
m_FailedTests
private ref array<string> TFModule::m_FailedTests private
Definition at line 92 of file testframework.c.
Referenced by PrintResult(), RunTest(), and TFModule().
m_Results
private ref TFResultArr TFModule::m_Results private
Definition at line 89 of file testframework.c.
Referenced by AddTest(), and TFModule().
m_SucceededTests
private ref array<string> TFModule::m_SucceededTests private
Definition at line 91 of file testframework.c.
Referenced by PrintResult(), RunTest(), and TFModule().
m_Success
private int TFModule::m_Success private
Definition at line 86 of file testframework.c.
Referenced by Pending(), RunTest(), and Success().
m_Tests
private ref TFCallerArr TFModule::m_Tests private
Definition at line 88 of file testframework.c.
Referenced by AddTest(), Run(), and TFModule().