DayzKode: Ammo_40mm_Smoke_ColorBase Class Reference
Ammo_40mm_Smoke_ColorBase Class Reference
Private Member Functions
protected void Activate ()
void Ammo_40mm_Smoke_ColorBase ()
override bool CanPutInCargo (EntityAI parent)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
special behaviour - do not call super
override void OnActivatedByItem (notnull ItemBase item)
override void OnVariablesSynchronized ()
Private Attributes
protected bool m_Activated
protected int m_ParticleId
protected float m_ParticleLifetime
protected Particle m_ParticleSmoke
Detailed Description
Definition at line 125 of file ammunitionpiles.c.
Constructor & Destructor Documentation
Ammo_40mm_Smoke_ColorBase()
void Ammo_40mm_Smoke_ColorBase::Ammo_40mm_Smoke_ColorBase () inline private
Definition at line 132 of file ammunitionpiles.c.
    {
        RegisterNetSyncVariableBool("m_Activated");
    }
Member Function Documentation
Activate()
protected void Ammo_40mm_Smoke_ColorBase::Activate () inline private
Definition at line 155 of file ammunitionpiles.c.
    {
        m_ParticleLifetime = GetGame().ConfigGetFloat(string.Format("CfgMagazines %1 particleLifeTime", GetType()));
        m_Activated = true;
        SetSynchDirty();
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DeleteSafe, m_ParticleLifetime * 1000);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::ConfigGetFloat(), CGame::GetCallQueue(), GetGame(), GetType(), m_Activated, and m_ParticleLifetime.
Referenced by OnActivatedByItem().
CanPutInCargo()
override bool Ammo_40mm_Smoke_ColorBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 183 of file ammunitionpiles.c.
    {
        return !m_Activated;
    }
References m_Activated.
EEDelete()
override void Ammo_40mm_Smoke_ColorBase::EEDelete (EntityAI parent) inline private
Definition at line 171 of file ammunitionpiles.c.
    {
        #ifndef SERVER
        if (m_ParticleSmoke)
        {
            m_ParticleSmoke.Stop();
        }
        #endif
        super.EEDelete(parent);
    }
References m_ParticleSmoke, and Particle::Stop().
EEKilled()
override void Ammo_40mm_Smoke_ColorBase::EEKilled (Object killer) inline private
special behaviour - do not call super
Definition at line 165 of file ammunitionpiles.c.
    {
        //analytics (behaviour from EntityAI)
        GetGame().GetAnalyticsServer().OnEntityKilled(killer, this);
    }
References CGame::GetAnalyticsServer(), GetGame(), and AnalyticsManagerServer::OnEntityKilled().
OnActivatedByItem()
override void Ammo_40mm_Smoke_ColorBase::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 188 of file ammunitionpiles.c.
    {
        SetHealth("", "", 0.0);
        Activate();
    }
References Activate(), and SetHealth().
OnVariablesSynchronized()
override void Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized () inline private
Definition at line 137 of file ammunitionpiles.c.
    {
        super.OnVariablesSynchronized();
        if (m_Activated)
        {
            #ifndef SERVER
            string particleStrIdentifier = GetGame().ConfigGetTextOut(string.Format("CfgMagazines %1 particleStrIdentifier", GetType()));
            m_ParticleId = ParticleList.GetParticleIDByName(particleStrIdentifier);
            if (m_ParticleId > 0)
            {
                m_ParticleSmoke = ParticleManager.GetInstance().PlayOnObject(m_ParticleId, this);
                m_ParticleSmoke.SetWiggle(7, 0.3);
            }
            #endif
        }
    }
References CGame::ConfigGetTextOut(), GetGame(), ParticleList::GetParticleIDByName(), GetType(), m_Activated, m_ParticleId, m_ParticleSmoke, ParticleManager(), and Particle::SetWiggle().
Member Data Documentation
m_Activated
protected bool Ammo_40mm_Smoke_ColorBase::m_Activated private
Definition at line 130 of file ammunitionpiles.c.
Referenced by Activate(), CanPutInCargo(), and OnVariablesSynchronized().
m_ParticleId
protected int Ammo_40mm_Smoke_ColorBase::m_ParticleId private
Definition at line 129 of file ammunitionpiles.c.
Referenced by OnVariablesSynchronized().
m_ParticleLifetime
protected float Ammo_40mm_Smoke_ColorBase::m_ParticleLifetime private
Definition at line 128 of file ammunitionpiles.c.
Referenced by Activate().
m_ParticleSmoke
protected Particle Ammo_40mm_Smoke_ColorBase::m_ParticleSmoke private
Definition at line 127 of file ammunitionpiles.c.
Referenced by EEDelete(), and OnVariablesSynchronized().