DayzKode: RadialProgressBar Class Reference
RadialProgressBar Class Reference
Private Member Functions
void OnWidgetScriptInit (Widget w)
void RadialProgressBar ()
void SetProgress (float progress)
protected void Update (float tDelta)
protected void UpdateChild (Widget child, int index)
void ~RadialProgressBar ()
Private Attributes
protected ref AnimatorTimer m_Anim
protected string m_BarHider
protected string m_BarPart
protected Widget m_Root
protected float rotation = 0
reference float speed
protected int stage = 0
reference float start_rotation
protected float x
protected float y
protected float z
Detailed Description
Definition at line 2 of file radialprogressbar.c.
Constructor & Destructor Documentation
RadialProgressBar()
void RadialProgressBar::RadialProgressBar () inline private
Definition at line 16 of file radialprogressbar.c.
    {
        m_Anim = new AnimatorTimer();
        GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(this.Update);
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_Anim, and Update().
~RadialProgressBar()
void RadialProgressBar::~RadialProgressBar () inline private
Definition at line 23 of file radialprogressbar.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Remove(this.Update);
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
Member Function Documentation
OnWidgetScriptInit()
void RadialProgressBar::OnWidgetScriptInit (Widget w) inline private
Definition at line 98 of file radialprogressbar.c.
    {
        m_Root = w;
        m_BarHider = "BarHider_" + m_Root.GetName();
        m_BarPart = "BarPart2_" + m_Root.GetName();
        m_Anim.AnimateLoop( speed );
    }
References AnimatorTimer::AnimateLoop(), m_Anim, m_BarHider, m_BarPart, m_Root, and speed.
SetProgress()
void RadialProgressBar::SetProgress (float progress) inline private
Definition at line 28 of file radialprogressbar.c.
    {
        if( progress < 50 )
        {
            stage = 0;
        }
        rotation = 360 * ( progress / 100 );
    }
References rotation, and stage.
Update()
protected void RadialProgressBar::Update (float tDelta) inline private
Definition at line 38 of file radialprogressbar.c.
    {
        m_Anim.Tick(tDelta);
        Widget child = m_Root.GetChildren();
        int index = 0;
        while ( child )
        {
            UpdateChild( child, index );
            index++;
            child = child.GetSibling();
        }
    }
References m_Anim, m_Root, AnimatorTimer::Tick(), and UpdateChild().
UpdateChild()
protected void RadialProgressBar::UpdateChild (Widget child, int index) inline private
Definition at line 53 of file radialprogressbar.c.
    {
        float rotation_value = ( m_Anim.GetTargetValue() * Math.RAD2DEG );
        if( child.GetName() == m_BarHider )
        {
            if( stage == 0 )
            {
                if( rotation > 0 )
                {
                        child.GetChildren().Show(true);
                }
                else
                {
                        child.GetChildren().Show(false);
                }
                child.GetChildren().SetRotation( 0, 0, start_rotation + rotation);
                if(  rotation > 180 )
                {
                    stage = 1;
                    child.GetChildren().SetRotation(0, 0, 360);
                }
            }
        }
        else if( child.GetName() == m_BarPart )
        {
            if( stage == 0 )
            child.Show( false );
            if( stage == 1 )
            {
                child.Show( true );
                child.SetRotation( 0, 0, start_rotation + rotation );
                if( rotation > 360 )
                {
                    stage = 2;
                    child.SetRotation( 0, 0, 180 );
                }
            }
        }
    }
References AnimatorTimer::GetTargetValue(), m_Anim, m_BarHider, m_BarPart, Math::RAD2DEG, rotation, stage, and start_rotation.
Referenced by Update().
Member Data Documentation
m_Anim
protected ref AnimatorTimer RadialProgressBar::m_Anim private
Definition at line 10 of file radialprogressbar.c.
Referenced by OnWidgetScriptInit(), RadialProgressBar(), Update(), and UpdateChild().
m_BarHider
protected string RadialProgressBar::m_BarHider private
Definition at line 7 of file radialprogressbar.c.
Referenced by OnWidgetScriptInit(), and UpdateChild().
m_BarPart
protected string RadialProgressBar::m_BarPart private
Definition at line 8 of file radialprogressbar.c.
Referenced by OnWidgetScriptInit(), and UpdateChild().
m_Root
protected Widget RadialProgressBar::m_Root private
Definition at line 9 of file radialprogressbar.c.
Referenced by OnWidgetScriptInit(), and Update().
rotation
protected float RadialProgressBar::rotation = 0 private
Definition at line 12 of file radialprogressbar.c.
Referenced by SetProgress(), and UpdateChild().
speed
reference float RadialProgressBar::speed private
Definition at line 4 of file radialprogressbar.c.
Referenced by OnWidgetScriptInit().
stage
protected int RadialProgressBar::stage = 0 private
Definition at line 13 of file radialprogressbar.c.
Referenced by SetProgress(), and UpdateChild().
start_rotation
reference float RadialProgressBar::start_rotation private
Definition at line 5 of file radialprogressbar.c.
Referenced by UpdateChild().
x
protected float RadialProgressBar::x private
Definition at line 11 of file radialprogressbar.c.
y
protected float RadialProgressBar::y private
Definition at line 11 of file radialprogressbar.c.
z
protected float RadialProgressBar::z private
Definition at line 11 of file radialprogressbar.c.