DayzKode: DeferredHandEvent Class Reference
DeferredHandEvent Class Reference
Private Member Functions
override void ClearInventoryReservation (HumanInventory inventory)
void DeferredHandEvent (InventoryMode mode, HandEventBase e)
override bool ReserveInventory (HumanInventory inventory)
Private Attributes
ref HandEventBase m_event
Detailed Description
Definition at line 111 of file dayzplayerinventory.c.
Constructor & Destructor Documentation
DeferredHandEvent()
void DeferredHandEvent::DeferredHandEvent (InventoryMode mode, HandEventBase e) inline private
Definition at line 114 of file dayzplayerinventory.c.
    {
        m_mode = mode;
        m_event = e;
    }
References m_event, and DeferredEvent::m_mode.
Member Function Documentation
ClearInventoryReservation()
override void DeferredHandEvent::ClearInventoryReservation (HumanInventory inventory) inline private
Definition at line 125 of file dayzplayerinventory.c.
    {
        m_event.ClearInventoryReservation();
    }
References HandEventBase::ClearInventoryReservation(), and m_event.
Referenced by HandleHandEvent().
ReserveInventory()
override bool DeferredHandEvent::ReserveInventory (HumanInventory inventory) inline private
Definition at line 120 of file dayzplayerinventory.c.
    {
        return m_event.ReserveInventory();
    }
References m_event, and HandEventBase::ReserveInventory().
Referenced by HandleHandEvent().
Member Data Documentation
m_event
ref HandEventBase DeferredHandEvent::m_event private
Definition at line 113 of file dayzplayerinventory.c.
Referenced by ClearInventoryReservation(), DeferredHandEvent(), HandleHandEvent(), and ReserveInventory().