DayzKode: LOD Class Reference
LOD Class Reference
LOD class.
Private Member Functions
proto native owned string GetName (Object myObject)
proto native int GetPropertyCount ()
proto native owned string GetPropertyName (int index)
proto native owned string GetPropertyValue (int index)
Selection GetSelectionByName (string name)
proto native int GetSelectionCount ()
proto native bool GetSelections (notnull out array< Selection > selections)
proto native vector GetVertexPosition (int vertex_index)
private void LOD ()
private void ~LOD ()
Static Private Attributes
static const string NAME_FIRE = "fire"
static const string NAME_GEOMETRY = "geometry"
static const string NAME_MEMORY = "memory"
static const string NAME_ROADWAY = "roadway"
static const string NAME_VIEW = "view"
Detailed Description
LOD class.
Definition at line 199 of file gameplay.c.
Constructor & Destructor Documentation
LOD()
private void LOD::LOD () inline private
Definition at line 208 of file gameplay.c.
{}
~LOD()
private void LOD::~LOD () inline private
Definition at line 209 of file gameplay.c.
{}
Member Function Documentation
GetName()
proto native owned string LOD::GetName (Object myObject) private
GetPropertyCount()
proto native int LOD::GetPropertyCount () private
Referenced by ActionEnterLadder::Start().
GetPropertyName()
proto native owned string LOD::GetPropertyName (int index) private
Referenced by ActionEnterLadder::Start().
GetPropertyValue()
proto native owned string LOD::GetPropertyValue (int index) private
Referenced by ActionEnterLadder::Start().
GetSelectionByName()
Selection LOD::GetSelectionByName (string name) inline private
Definition at line 218 of file gameplay.c.
    {
        array<Selection> selections = new array<Selection>;
        GetSelections( selections );
        for ( int i = 0; i < selections.Count(); ++i )
        {
            string selection_name = selections.Get( i ).GetName();
            selection_name.ToLower();
            name.ToLower();
            if (selection_name == name)
            {
                return selections.Get( i );
            }
        }
        return null;
    }
References GetSelections(), name, and string::ToLower().
GetSelectionCount()
proto native int LOD::GetSelectionCount () private
GetSelections()
proto native bool LOD::GetSelections (notnull out array< Selection > selections) private
Referenced by ActionEnterLadder::ActionCondition(), AttachmentsOutOfReach::CreateAttachmentPosition(), ScriptedWidgetEventHandler::GetOnScreenPosition(), and GetSelectionByName().
GetVertexPosition()
proto native vector LOD::GetVertexPosition (int vertex_index) private
Referenced by Selection::GetVertexPosition().
Member Data Documentation
NAME_FIRE
const string LOD::NAME_FIRE = "fire" static private
Definition at line 204 of file gameplay.c.
Referenced by ScriptedWidgetEventHandler::GetItemDesc(), and ScriptedWidgetEventHandler::GetItemHealth().
NAME_GEOMETRY
const string LOD::NAME_GEOMETRY = "geometry" static private
Definition at line 202 of file gameplay.c.
NAME_MEMORY
const string LOD::NAME_MEMORY = "memory" static private
Definition at line 205 of file gameplay.c.
Referenced by ScriptedWidgetEventHandler::GetOnScreenPosition().
NAME_ROADWAY
const string LOD::NAME_ROADWAY = "roadway" static private
Definition at line 206 of file gameplay.c.
NAME_VIEW
const string LOD::NAME_VIEW = "view" static private
Definition at line 203 of file gameplay.c.
Referenced by ActionRepairCarEngine::ActionCondition(), Hologram::CorrectForWatchtower(), AttachmentsOutOfReach::CreateAttachmentPosition(), ScriptedWidgetEventHandler::GetItemDesc(), ScriptedWidgetEventHandler::GetItemHealth(), Hologram::IsObjectStatic(), and Hologram::SetOnGround().