DayzKode: RecipeCacheData Class Reference
RecipeCacheData Class Reference
Private Member Functions
int GetBitCount ()
int GetMask ()
void RecipeCacheData (int mask)
void SetMask (int mask)
Private Attributes
int m_BitCount
int m_Mask
Detailed Description
Definition at line 2 of file cacheobject.c.
Constructor & Destructor Documentation
RecipeCacheData()
void RecipeCacheData::RecipeCacheData (int mask) inline private
Definition at line 7 of file cacheobject.c.
    {
        SetMask(mask);
    }
References SetMask().
Member Function Documentation
GetBitCount()
int RecipeCacheData::GetBitCount () inline private
Definition at line 17 of file cacheobject.c.
    {
        return m_BitCount;
    }
References m_BitCount.
Referenced by GetBitCountByRecipeID().
GetMask()
int RecipeCacheData::GetMask () inline private
Definition at line 12 of file cacheobject.c.
    {
        return m_Mask;
    }
References m_Mask.
Referenced by GetMaskByRecipeID(), and UpdateMask().
SetMask()
void RecipeCacheData::SetMask (int mask) inline private
Definition at line 22 of file cacheobject.c.
    {
        m_Mask = mask;
        m_BitCount = Math.GetNumberOfSetBits(mask);
    }
References Math::GetNumberOfSetBits(), m_BitCount, and m_Mask.
Referenced by RecipeCacheData(), and UpdateMask().
Member Data Documentation
m_BitCount
int RecipeCacheData::m_BitCount private
Definition at line 5 of file cacheobject.c.
Referenced by DebugPrint(), GetBitCount(), and SetMask().
m_Mask
int RecipeCacheData::m_Mask private
Definition at line 4 of file cacheobject.c.
Referenced by DebugPrint(), GetMask(), and SetMask().