DayzKode: ActionHarvestCrops Class Reference
ActionHarvestCrops Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionHarvestCrops ()
override void CreateConditionComponents ()
override GetInputType ()
Slot GetPlantSlot (ActionTarget target)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnExecuteServer (ActionData action_data)
Private Attributes
PlantBase m_Plant
Detailed Description
Definition at line 1 of file actionharvestcrops.c.
Constructor & Destructor Documentation
ActionHarvestCrops()
void ActionHarvestCrops::ActionHarvestCrops () inline private
Definition at line 5 of file actionharvestcrops.c.
    {
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_MEDIUM;
        /*m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_FullBody = true;*/
    }
References m_SpecialtyWeight, and UASoftSkillsWeight::PRECISE_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionHarvestCrops::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 66 of file actionharvestcrops.c.
    {
        GardenBase garden_base;
        if ( Class.CastTo(garden_base, target.GetObject()))
        {
            Slot slot = GetPlantSlot(target);
            if (slot)
            {
                m_Plant = PlantBase.Cast(slot.GetPlant());
                bool is_mature = m_Plant.IsMature();
                bool is_spoiled = m_Plant.IsSpoiled();
                bool has_crops = m_Plant.HasCrops();
                int plant_state = m_Plant.GetPlantState();
                if ( is_mature && has_crops )
                {
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo(), GetPlantSlot(), and m_Plant.
CreateConditionComponents()
override void ActionHarvestCrops::CreateConditionComponents () inline private
Definition at line 60 of file actionharvestcrops.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor(UAMaxDistances.SMALL);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
GetInputType()
override ActionHarvestCrops::GetInputType () inline private
Definition at line 14 of file actionharvestcrops.c.
    {
        return ContinuousInteractActionInput;
    }
GetPlantSlot()
Slot ActionHarvestCrops::GetPlantSlot (ActionTarget target) inline private
Definition at line 19 of file actionharvestcrops.c.
    {
        GardenBase garden_base;
        if ( Class.CastTo(garden_base, target.GetObject()))
        {
            Slot slot;
            array<string> selections = new array<string>;
            garden_base.GetActionComponentNameList(target.GetComponentIndex(), selections);
            string selection;
            for (int s = 0; s < selections.Count(); s++)
            {
                selection = selections[s];
                slot = garden_base.GetSlotBySelection( selection );
                if (slot)
                    break;
            }
            if ( slot && slot.GetPlant() )
            {
                return slot;
            }
        }
        return null;
    }
References Class::CastTo().
Referenced by ActionCondition(), and OnActionInfoUpdate().
OnActionInfoUpdate()
override void ActionHarvestCrops::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 46 of file actionharvestcrops.c.
    {
        m_Text =  "#harvest";
        Slot slot = GetPlantSlot(target);
        if (slot)
        {
            m_Plant = PlantBase.Cast(slot.GetPlant());
            m_Text+=  " " +  MiscGameplayFunctions.GetItemDisplayName(m_Plant.GetCropsType());
        }
    }
References GetPlantSlot(), m_Plant, and m_Text.
OnExecuteServer()
override void ActionHarvestCrops::OnExecuteServer (ActionData action_data) inline private
Definition at line 91 of file actionharvestcrops.c.
    {
        if ( m_Plant )
        {
            m_Plant.Harvest( action_data.m_Player );
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References m_Plant, ActionData::m_Player, and m_SpecialtyWeight.
Member Data Documentation
m_Plant
PlantBase ActionHarvestCrops::m_Plant private
Definition at line 3 of file actionharvestcrops.c.
Referenced by ActionCondition(), OnActionInfoUpdate(), and OnExecuteServer().