DayzKode: ActionInput Class Reference
ActionInput Class Reference
Private Member Functions
void ActionInput ()
void ActionsSelectReset ()
void ClearForcedAction ()
void ClearForcedTarget ()
void ForceAction (ActionBase action, ActionTarget target, ItemBase item)
bool ForceActionCheck (PlayerBase player)
void ForceActionTarget (ActionTarget target)
ActionBase GetAction ()
int GetInputType ()
ActionBase GetPossibleAction ()
int GetPossibleActionIndex ()
array< ActionBase > GetPossibleActions ()
int GetPossibleActionsCount ()
int GetPriority ()
UAInput GetUAInput ()
ActionTarget GetUsedActionTarget ()
ItemBase GetUsedMainItem ()
bool HasInput ()
bool HasTarget ()
void Init (PlayerBase player, ActionManagerClient am)
bool IsActive ()
bool JustActivate ()
void OnActionEnd ()
void OnActionStart ()
void Reset ()
void SelectNextAction ()
void SelectPrevAction ()
void SetEnablity (bool value)
protected void SetInput (string input_name)
void Update ()
void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
bool WasEnded ()
Private Attributes
bool m_Active
int m_ConditionMask
bool m_DetectFromItem
bool m_DetectFromPlayer
bool m_DetectFromTarget
bool m_Enabled
ref ForcedActionData m_ForcedActionData
ref ActionTarget m_ForcedTarget
bool m_HasTarget
UAIDWrapper m_input
int m_InputType
bool m_JustActivate
ItemBase m_MainItem
PlayerBase m_Player
int m_Priority
ref ActionTarget m_Target
Detailed Description
Definition at line 19 of file actioninput.c.
Constructor & Destructor Documentation
ActionInput()
void ActionInput::ActionInput () inline private
Definition at line 43 of file actioninput.c.
    {
        m_Active = false;
        m_Enabled = true;
        m_ForcedTarget = null;
        m_ForcedActionData = null;
        m_HasTarget = false;
        m_JustActivate = false;
        m_DetectFromTarget = false;
        m_DetectFromItem = true;
        m_DetectFromPlayer = true;
        m_Priority = 100;
    }
References m_Active, m_DetectFromItem, m_DetectFromPlayer, m_DetectFromTarget, m_Enabled, m_ForcedActionData, m_ForcedTarget, m_HasTarget, m_JustActivate, and m_Priority.
Member Function Documentation
ActionsSelectReset()
void ActionInput::ActionsSelectReset () inline private
Definition at line 227 of file actioninput.c.
    {}
Referenced by OnActionStart(), Reset(), and ActionManagerClient::ResetInputsActions().
ClearForcedAction()
void ActionInput::ClearForcedAction () inline private
Definition at line 243 of file actioninput.c.
    {
        m_ForcedActionData = null;
    }
References m_ForcedActionData.
Referenced by ActionManagerClient::EjectAction().
ClearForcedTarget()
void ActionInput::ClearForcedTarget () inline private
Definition at line 248 of file actioninput.c.
    {
        m_ForcedTarget = NULL;
    }
References m_ForcedTarget.
ForceAction()
void ActionInput::ForceAction (ActionBase action, ActionTarget target, ItemBase item) inline private
Definition at line 230 of file actioninput.c.
    {
        m_ForcedActionData = new ForcedActionData;
        m_ForcedActionData.m_Action = action;
        m_ForcedActionData.m_Target = target;
        m_ForcedActionData.m_Item = item;
    }
References m_ForcedActionData.
Referenced by ActionManagerClient::InjectAction().
ForceActionCheck()
bool ActionInput::ForceActionCheck (PlayerBase player) inline private
Definition at line 253 of file actioninput.c.
    {
        if (m_ForcedActionData)
        {
            if (m_ForcedActionData.m_Action.Can(player, m_ForcedActionData.m_Target, m_ForcedActionData.m_Item))
            {
                m_MainItem = m_ForcedActionData.m_Item;
                m_Target = m_ForcedActionData.m_Target;
                return true;
            }
        }
        return false;
    }
References m_ForcedActionData, m_MainItem, and m_Target.
Referenced by NoIndicationActionInputBase::GetAction(), and UpdatePossibleActions().
ForceActionTarget()
void ActionInput::ForceActionTarget (ActionTarget target) inline private
Definition at line 238 of file actioninput.c.
    {
        m_ForcedTarget = target;
    }
References m_ForcedTarget.
GetAction()
ActionBase ActionInput::GetAction () inline private
Definition at line 182 of file actioninput.c.
    {
        return NULL;
    }
Referenced by ActionManagerClient::GetPossibleAction(), and ActionManagerClient::InputsUpdate().
GetInputType()
int ActionInput::GetInputType () inline private
Definition at line 89 of file actioninput.c.
    {
        return m_InputType;
    }
References m_InputType.
Referenced by ActionManagerClient::InputsUpdate().
GetPossibleAction()
ActionBase ActionInput::GetPossibleAction () inline private
Definition at line 202 of file actioninput.c.
    {
        return NULL;
    }
GetPossibleActionIndex()
int ActionInput::GetPossibleActionIndex () inline private
Definition at line 207 of file actioninput.c.
    {
        return -1;
    }
Referenced by ActionManagerClient::GetPossibleActionIndex().
GetPossibleActions()
array< ActionBase > ActionInput::GetPossibleActions () inline private
Definition at line 197 of file actioninput.c.
    {
        return NULL;
    }
Referenced by ActionManagerClient::GetPossibleActions().
GetPossibleActionsCount()
int ActionInput::GetPossibleActionsCount () inline private
Definition at line 274 of file actioninput.c.
    {
        return -1;
    }
Referenced by ActionManagerClient::GetPossibleActionCount(), ActionManagerClient::SelectNextAction(), and ActionManagerClient::SelectPrevAction().
GetPriority()
int ActionInput::GetPriority () inline private
Definition at line 284 of file actioninput.c.
    {
        return m_Priority;
    }
References m_Priority.
Referenced by ActionManagerClient::SetActioninputOrder().
GetUAInput()
UAInput ActionInput::GetUAInput () inline private
Definition at line 94 of file actioninput.c.
    {
        return m_input.InputP();
    }
References UAIDWrapper::InputP(), and m_input.
GetUsedActionTarget()
ActionTarget ActionInput::GetUsedActionTarget () inline private
Definition at line 187 of file actioninput.c.
    {
        return m_Target;
    }
References m_Target.
Referenced by ActionManagerClient::InputsUpdate().
GetUsedMainItem()
ItemBase ActionInput::GetUsedMainItem () inline private
Definition at line 192 of file actioninput.c.
    {
        return m_MainItem;
    }
References m_MainItem.
Referenced by ActionManagerClient::InputsUpdate().
HasInput()
bool ActionInput::HasInput () inline private
Definition at line 279 of file actioninput.c.
    {
        return m_input != NULL;
    }
References m_input.
HasTarget()
bool ActionInput::HasTarget () inline private
Definition at line 212 of file actioninput.c.
    {
        return false;
    }
Init()
void ActionInput::Init (PlayerBase player, ActionManagerClient am) inline private
Definition at line 60 of file actioninput.c.
    {
        m_Player = player;
        if ( LogManager.IsActionLogEnable())
        {
            Debug.ActionLog("n/a",this.ToString(), "n/a","Init()", player.ToString());
        }
    }
References Debug::ActionLog(), LogManager::IsActionLogEnable(), m_Player, and ToString().
IsActive()
bool ActionInput::IsActive () inline private
Definition at line 104 of file actioninput.c.
    {
        return m_Active;
    }
References m_Active.
JustActivate()
bool ActionInput::JustActivate () inline private
Definition at line 99 of file actioninput.c.
    {
        return m_JustActivate;
    }
References m_JustActivate.
Referenced by ActionManagerClient::InputsUpdate().
OnActionEnd()
void ActionInput::OnActionEnd () inline private
Definition at line 222 of file actioninput.c.
    {
        Reset();
    }
References Reset().
OnActionStart()
void ActionInput::OnActionStart () inline private
Definition at line 217 of file actioninput.c.
    {
        ActionsSelectReset();
    }
References ActionsSelectReset().
Referenced by ActionManagerClient::HandleInputsOnActionStart().
Reset()
void ActionInput::Reset () inline private
Definition at line 172 of file actioninput.c.
    {
        m_Active = false;
        ActionsSelectReset();
    }
References ActionsSelectReset(), and m_Active.
Referenced by ActionManagerClient::HandleInputsOnActionStart(), OnActionEnd(), and ActionManagerClient::ResetInputsState().
SelectNextAction()
void ActionInput::SelectNextAction () inline private
Definition at line 267 of file actioninput.c.
    {
    }
Referenced by ActionManagerClient::SelectNextAction().
SelectPrevAction()
void ActionInput::SelectPrevAction () inline private
Definition at line 271 of file actioninput.c.
    {}
Referenced by ActionManagerClient::SelectPrevAction().
SetEnablity()
void ActionInput::SetEnablity (bool value) inline private
Definition at line 71 of file actioninput.c.
    {
        m_Enabled = value;
    }
References m_Enabled.
SetInput()
protected void ActionInput::SetInput (string input_name) inline private
Definition at line 76 of file actioninput.c.
    {
        m_input = GetUApi().GetInputByName(input_name).GetPersistentWrapper();
        if ( LogManager.IsActionLogEnable())
        {
            if (m_input && m_input.InputP())
                Debug.ActionLog("(+) input set to " + input_name ,this.ToString(), "n/a","SetInput()", "n/a");
            else
                Debug.ActionLog("(-) input is not set to " + input_name ,this.ToString(), "n/a","SetInput()","n/a");
        }
    }
References Debug::ActionLog(), UAInputAPI::GetInputByName(), UAInput::GetPersistentWrapper(), GetUApi(), UAIDWrapper::InputP(), LogManager::IsActionLogEnable(), m_input, and ToString().
Referenced by ContinuousWeaponManipulationActionInput::ContinuousWeaponManipulationActionInput(), DropActionInput::DropActionInput(), and WeaponManipulationActionInput::WeaponManipulationActionInput().
Update()
void ActionInput::Update () inline private
Definition at line 114 of file actioninput.c.
    {
        if( !m_Enabled )
        {
            m_Active = false;
            m_JustActivate = false;
            return;
        }
        switch ( m_InputType )
        {
            case ActionInputType.AIT_CONTINUOUS:
                m_JustActivate = false;
                if(m_Active)
                {
                    m_Active = m_input.InputP().LocalHold();
                }
                else
                {
                    m_Active = m_input.InputP().LocalHoldBegin();
                    m_JustActivate = m_Active;
                }
                break;
            case ActionInputType.AIT_SINGLE:
                m_Active = m_input.InputP().LocalClick();
                m_JustActivate = m_Active;
                break;
            case ActionInputType.AIT_DOUBLECLICK:
                m_Active = m_input.InputP().LocalDoubleClick();
                m_JustActivate = m_Active;
                break;
            break;
            case ActionInputType.AIT_HOLDSINGLE:
                m_Active = m_input.InputP().LocalHoldBegin();
                m_JustActivate = m_Active;
                break;
            break;
            case ActionInputType.AIT_CLICKCONTINUOUS:
                m_JustActivate = false;
                if(m_Active)
                {
                    if ( m_input.InputP().LocalClick() )
                    {
                        m_Active = false;
                    }
                }
                else
                {
                    m_Active = m_input.InputP().LocalClick();
                    m_JustActivate = m_Active;
                }
                break;
            break;
            default:
                break;
        }
    }
References UAIDWrapper::InputP(), UAInput::LocalClick(), UAInput::LocalDoubleClick(), UAInput::LocalHold(), UAInput::LocalHoldBegin(), m_Active, m_Enabled, m_input, m_InputType, and m_JustActivate.
Referenced by ActionManagerClient::InputsUpdate().
UpdatePossibleActions()
void ActionInput::UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Definition at line 178 of file actioninput.c.
    {
    }
Referenced by ActionManagerClient::FindContextualUserActions().
WasEnded()
bool ActionInput::WasEnded () inline private
Definition at line 109 of file actioninput.c.
    {
        return !m_Active;
    }
References m_Active.
Referenced by ActionManagerClient::InputsUpdate().
Member Data Documentation
m_Active
bool ActionInput::m_Active private
Definition at line 41 of file actioninput.c.
Referenced by ActionInput(), IsActive(), Reset(), Update(), and WasEnded().
m_ConditionMask
int ActionInput::m_ConditionMask private
Definition at line 39 of file actioninput.c.
Referenced by NoIndicationActionInputBase::GetAction(), and NoIndicationActionInputBase::UpdatePossibleActions().
m_DetectFromItem
bool ActionInput::m_DetectFromItem private
Definition at line 24 of file actioninput.c.
Referenced by ActionInput().
m_DetectFromPlayer
bool ActionInput::m_DetectFromPlayer private
Definition at line 26 of file actioninput.c.
Referenced by ActionInput().
m_DetectFromTarget
bool ActionInput::m_DetectFromTarget private
Definition at line 25 of file actioninput.c.
Referenced by ActionInput(), and NoIndicationActionInputBase::NoIndicationActionInputBase().
m_Enabled
bool ActionInput::m_Enabled private
Definition at line 27 of file actioninput.c.
Referenced by ActionInput(), SetEnablity(), and Update().
m_ForcedActionData
ref ForcedActionData ActionInput::m_ForcedActionData private
Definition at line 35 of file actioninput.c.
Referenced by ActionInput(), ClearForcedAction(), ForceAction(), ForceActionCheck(), and NoIndicationActionInputBase::GetAction().
m_ForcedTarget
ref ActionTarget ActionInput::m_ForcedTarget private
Definition at line 33 of file actioninput.c.
Referenced by ActionInput(), ClearForcedTarget(), ForceActionTarget(), and UpdatePossibleActions().
m_HasTarget
bool ActionInput::m_HasTarget private
Definition at line 29 of file actioninput.c.
Referenced by ActionInput(), and HasTarget().
m_input
UAIDWrapper ActionInput::m_input private
Definition at line 21 of file actioninput.c.
Referenced by GetUAInput(), HasInput(), SetInput(), and Update().
m_InputType
int ActionInput::m_InputType private
Definition at line 22 of file actioninput.c.
Referenced by ContinuousWeaponManipulationActionInput::ContinuousWeaponManipulationActionInput(), DropActionInput::DropActionInput(), ExternalControlledActionInput::ExternalControlledActionInput(), GetInputType(), InventoryOnlyActionInput::InventoryOnlyActionInput(), Update(), and WeaponManipulationActionInput::WeaponManipulationActionInput().
m_JustActivate
bool ActionInput::m_JustActivate private
Definition at line 28 of file actioninput.c.
Referenced by ActionInput(), JustActivate(), and Update().
m_MainItem
ItemBase ActionInput::m_MainItem private
Definition at line 38 of file actioninput.c.
Referenced by ForceActionCheck(), NoIndicationActionInputBase::GetAction(), GetUsedMainItem(), and NoIndicationActionInputBase::UpdatePossibleActions().
m_Player
PlayerBase ActionInput::m_Player private
Definition at line 31 of file actioninput.c.
Referenced by NoIndicationActionInputBase::GetAction(), and Init().
m_Priority
int ActionInput::m_Priority private
Definition at line 23 of file actioninput.c.
Referenced by ActionInput(), and GetPriority().
m_Target
ref ActionTarget ActionInput::m_Target private
Definition at line 37 of file actioninput.c.
Referenced by ForceActionCheck(), NoIndicationActionInputBase::GetAction(), GetUsedActionTarget(), and NoIndicationActionInputBase::UpdatePossibleActions().