DayzKode: CarScript Class Reference
CarScript Class Reference
Private Member Functions
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override bool CanDisplayCargo ()
override bool CanDisplayCargo ()
override bool CanDisplayCargo ()
override bool CanDisplayCargo ()
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanReleaseAttachment (EntityAI attachment)
void CivilianSedan ()
override CarLightBase CreateFrontLight ()
override CarLightBase CreateFrontLight ()
override CarLightBase CreateFrontLight ()
override CarLightBase CreateFrontLight ()
override CarLightBase CreateFrontLight ()
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override CarRearLightBase CreateRearLight ()
override CarRearLightBase CreateRearLight ()
override CarRearLightBase CreateRearLight ()
override CarRearLightBase CreateRearLight ()
override CarRearLightBase CreateRearLight ()
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override bool CrewCanGetThrough (int posIdx)
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EEInit ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override int GetAnimInstance ()
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override string GetAnimSourceFromSelection (string selection)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCarDoorsState (string slotType)
override int GetCrewIndex (string selection)
override string GetDoorConditionPointFromSelection (string selection)
override string GetDoorConditionPointFromSelection (string selection)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatAnimationType (int posIdx)
override int GetSeatIndexFromDoor (string pDoorSelection)
override int GetSeatIndexFromDoor (string pDoorSelection)
override int GetSeatIndexFromDoor (string pDoorSelection)
override float GetTransportCameraDistance ()
override float GetTransportCameraDistance ()
override float GetTransportCameraDistance ()
override float GetTransportCameraDistance ()
override vector GetTransportCameraOffset ()
void Hatchback_02 ()
override bool IsVitalCarBattery ()
override bool IsVitalCarBattery ()
override bool IsVitalEngineBelt ()
override bool IsVitalEngineBelt ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalGlowPlug ()
override bool IsVitalRadiator ()
override bool IsVitalRadiator ()
override bool IsVitalRadiator ()
override bool IsVitalSparkPlug ()
override bool IsVitalSparkPlug ()
override bool IsVitalSparkPlug ()
override bool IsVitalTruckBattery ()
override bool IsVitalTruckBattery ()
override bool IsVitalTruckBattery ()
override bool IsVitalTruckBattery ()
override bool IsVitalTruckBattery ()
override bool IsVitalTruckBattery ()
void Offroad_02 ()
void OffroadHatchback ()
override void OnAnimationPhaseStarted (string animSource, float phase)
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStart ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override void OnEngineStop ()
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
override float OnSound (CarSoundCtrl ctrl, float oldValue)
void Sedan_02 ()
override void SetActions ()
override void SetActions ()
void Truck_01_Base ()
void Truck_02 ()
void Van_01 ()
Private Attributes
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
Detailed Description
Definition at line 1 of file civiliansedan.c.
Member Function Documentation
CanDisplayAttachmentCategory() [1/5]
override bool CarScript::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 138 of file civiliansedan.c.
    {
        //super
        if (!super.CanDisplayAttachmentCategory(category_name))
            return false;
        //
        category_name.ToLower();
        if (category_name.Contains("engine"))
        {
            if (GetCarDoorsState("CivSedanHood") == CarDoorState.DOORS_CLOSED)
                return false;
        }
        return true;
    }
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [2/5]
override bool CarScript::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 136 of file hatchback_02.c.
    {
        //super
        if ( !super.CanDisplayAttachmentCategory( category_name ) )
        return false;
        //
        category_name.ToLower();
        if ( category_name.Contains( "engine" ) )
        {
            if ( GetCarDoorsState("Hatchback_02_Hood") == CarDoorState.DOORS_CLOSED )
                return false;
        }
        return true;
    }
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [3/5]
override bool CarScript::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 150 of file offroad_02.c.
    {
        if ( !super.CanDisplayAttachmentCategory(category_name))
        {
            return false;
        }
        category_name.ToLower();
        if (category_name.Contains("engine"))
        {
            if (GetCarDoorsState("Offroad_02_Hood") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
        }
        return true;
    }
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [4/5]
override bool CarScript::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 141 of file offroadhatchback.c.
    {
        if (!super.CanDisplayAttachmentCategory(category_name))
        {
            return false;
        }
        category_name.ToLower();
        if (category_name.Contains("engine"))
        {
            if (GetCarDoorsState("NivaHood") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
        }
        return true;
    }
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayAttachmentCategory() [5/5]
override bool CarScript::CanDisplayAttachmentCategory (string category_name) inline private
Definition at line 152 of file sedan_02.c.
    {
        if ( !super.CanDisplayAttachmentCategory(category_name))
        {
            return false;
        }
        category_name.ToLower();
        if (category_name.Contains("engine"))
        {
            if (GetCarDoorsState("Sedan_02_Trunk") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
        }
        if (category_name.Contains("trunk"))
        {
            if (GetCarDoorsState("Sedan_02_Hood") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
        }
        return true;
    }
References string::Contains(), GetCarDoorsState(), and string::ToLower().
CanDisplayCargo() [1/5]
override bool CarScript::CanDisplayCargo () inline private
Definition at line 155 of file civiliansedan.c.
    {
        if ( !super.CanDisplayCargo() )
            return false;
        if ( GetCarDoorsState("CivSedanTrunk") == CarDoorState.DOORS_CLOSED )
            return false;
        return true;
    }
References GetCarDoorsState().
CanDisplayCargo() [2/5]
override bool CarScript::CanDisplayCargo () inline private
Definition at line 153 of file hatchback_02.c.
    {
        if ( !super.CanDisplayCargo() )
            return false;
        if ( GetCarDoorsState("Hatchback_02_Trunk") == CarDoorState.DOORS_CLOSED )
            return false;
        return true;
    }
References GetCarDoorsState().
CanDisplayCargo() [3/5]
override bool CarScript::CanDisplayCargo () inline private
Definition at line 169 of file offroad_02.c.
    {
        if ( !super.CanDisplayCargo() )
            return false;
        if ( GetCarDoorsState("Offroad_02_Trunk") == CarDoorState.DOORS_CLOSED )
            return false;
        return true;
    }
References GetCarDoorsState().
CanDisplayCargo() [4/5]
override bool CarScript::CanDisplayCargo () inline private
Definition at line 160 of file offroadhatchback.c.
    {
        if (!super.CanDisplayCargo())
        {
            return false;
        }
        if (GetCarDoorsState("NivaTrunk") == CarDoorState.DOORS_CLOSED)
        {
            return false;
        }
        return true;
    }
References GetCarDoorsState().
CanDisplayCargo() [5/5]
override bool CarScript::CanDisplayCargo () inline private
Definition at line 179 of file sedan_02.c.
    {
        if ( !super.CanDisplayCargo() )
            return false;
        if ( GetCarDoorsState("Sedan_02_Hood") == CarDoorState.DOORS_CLOSED )
            return false;
        return true;
    }
References GetCarDoorsState().
CanManipulateSpareWheel() [1/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 133 of file civiliansedan.c.
    {
        return GetCarDoorsState("CivSedanTrunk") != CarDoorState.DOORS_CLOSED;
    }
References GetCarDoorsState().
Referenced by CanReceiveAttachment(), and CanReleaseAttachment().
CanManipulateSpareWheel() [2/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 131 of file hatchback_02.c.
    {
        return GetCarDoorsState("Hatchback_02_Trunk") != CarDoorState.DOORS_CLOSED;
    }
References GetCarDoorsState().
CanManipulateSpareWheel() [3/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 145 of file offroad_02.c.
    {
        return GetCarDoorsState("Offroad_02_Trunk") != CarDoorState.DOORS_CLOSED;
    }
References GetCarDoorsState().
CanManipulateSpareWheel() [4/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 136 of file offroadhatchback.c.
    {
        return GetCarDoorsState("NivaHood") != CarDoorState.DOORS_CLOSED;
    }
References GetCarDoorsState().
CanManipulateSpareWheel() [5/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 147 of file sedan_02.c.
    {
        return GetCarDoorsState("Sedan_02_Hood") != CarDoorState.DOORS_CLOSED;
    }
References GetCarDoorsState().
CanManipulateSpareWheel() [6/6]
override protected bool CarScript::CanManipulateSpareWheel (string slotSelectionName) inline private
Definition at line 134 of file truck_01_base.c.
    {
        if (slotSelectionName == "wheel_spare_1")
        {
            return GetAnimationPhase("wheelSidePlate1") == 1.0);
        }
        if (slotSelectionName == "wheel_spare_2")
        {
            return GetAnimationPhase("wheelSidePlate2") == 1.0);
        }
        return super.CanManipulateSpareWheel(slotSelectionName);
    }
CanReachDoorsFromSeat() [1/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 386 of file civiliansedan.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsCargo1")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCargo2")
            {
                return true;
            }
        break;
        }
        return false;
    }
Referenced by ActionCarDoors::ActionCondition().
CanReachDoorsFromSeat() [2/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 371 of file hatchback_02.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsCargo1")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCargo2")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [3/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 373 of file offroad_02.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsCargo1")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCargo2")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [4/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 435 of file offroadhatchback.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [5/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 393 of file sedan_02.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsCargo1")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCargo2")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [6/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 313 of file truck_01_base.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [7/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 246 of file truck_02.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachDoorsFromSeat() [8/8]
override bool CarScript::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat) inline private
Definition at line 305 of file van_01.c.
    {
        switch( pCurrentSeat )
        {
        case 0:
            if (pDoorsSelection == "DoorsDriver")
            {
                return true;
            }
        break;
        case 1:
            if (pDoorsSelection == "DoorsCoDriver")
            {
                return true;
            }
        break;
        case 2:
            if (pDoorsSelection == "DoorsCargo1")
            {
                return true;
            }
        break;
        case 3:
            if (pDoorsSelection == "DoorsCargo2")
            {
                return true;
            }
        break;
        }
        return false;
    }
CanReachSeatFromSeat() [1/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 361 of file civiliansedan.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        case 2:
            if ( nextSeat == 3 )
                return true;
            break;
        case 3:
            if ( nextSeat == 2 )
                return true;
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [2/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 346 of file hatchback_02.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        case 2:
            if ( nextSeat == 3 )
                return true;
            break;
        case 3:
            if ( nextSeat == 2 )
                return true;
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [3/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 347 of file offroad_02.c.
    {
        //return false;
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        case 2:
            if ( nextSeat == 3 )
                return true;
            break;
        case 3:
            if ( nextSeat == 2 )
                return true;
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [4/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 396 of file offroadhatchback.c.
    {
        if ( nextSeat == 0 && GetAnimationPhase("SeatDriver") > 0.5  )
            return false;
        if ( nextSeat == 1 && GetAnimationPhase("SeatCoDriver") > 0.5  )
            return false;
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
            {
                return true;
            }
            break;
        case 1:
            if ( nextSeat == 0 )
            {
                return true;
            }
            break;
        case 2:
            if ( nextSeat == 3 )
            {
                return true;
            }
            break;
        case 3:
            if ( nextSeat == 2 )
            {
                return true;
            }
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [5/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 368 of file sedan_02.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        case 2:
            if ( nextSeat == 3 )
                return true;
            break;
        case 3:
            if ( nextSeat == 2 )
                return true;
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [6/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 296 of file truck_01_base.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        }
        return false;
    }
CanReachSeatFromSeat() [7/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 228 of file truck_02.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
        break;
        case 1:
            if ( nextSeat == 0 )
                return true;
        break;
        }
        return false;
    }
CanReachSeatFromSeat() [8/8]
override bool CarScript::CanReachSeatFromSeat (int currentSeat, int nextSeat) inline private
Definition at line 279 of file van_01.c.
    {
        switch( currentSeat )
        {
        case 0:
            if ( nextSeat == 1 )
                return true;
            break;
        case 1:
            if ( nextSeat == 0 )
                return true;
            break;
        case 2:
            if ( nextSeat == 3 )
                return true;
            break;
        case 3:
            if ( nextSeat == 2 )
                return true;
            break;
        }
        return false;
    }
CanReleaseAttachment() [1/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 117 of file civiliansedan.c.
    {
        if( !super.CanReleaseAttachment( attachment ) )
            return false;
        string attType = attachment.GetType();
        if ( EngineIsOn() || GetCarDoorsState("CivSedanHood") == CarDoorState.DOORS_CLOSED )
        {
            if ( attType == "CarRadiator" || attType == "CarBattery" || attType == "SparkPlug" )
                return false;
        }
        return true;
    }
References GetCarDoorsState().
CanReleaseAttachment() [2/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 112 of file hatchback_02.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        if (EngineIsOn() || GetCarDoorsState("Hatchback_02_Hood") == CarDoorState.DOORS_CLOSED)
        {
            string attType = attachment.GetType();
            if (attType == "CarRadiator" || attType == "CarBattery" || attType == "SparkPlug")
            {
                return false;
            }
        }
        return true;
    }
References GetCarDoorsState().
CanReleaseAttachment() [3/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 117 of file offroad_02.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        string attType = attachment.GetType();
        switch (attType)
        {
        case "CarBattery":
            if (GetCarDoorsState("Offroad_02_Hood") == CarDoorState.DOORS_CLOSED || EngineIsOn())
            {
                return false;
            }
            break;
        case "GlowPlug":
            if (GetCarDoorsState("Offroad_02_Hood") == CarDoorState.DOORS_CLOSED || EngineIsOn())
            {
                return false;
            }
            break;
        }
        return true;
    }
References GetCarDoorsState().
CanReleaseAttachment() [4/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 117 of file offroadhatchback.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        if (EngineIsOn() || GetCarDoorsState("NivaHood") == CarDoorState.DOORS_CLOSED)
        {
            string attType = attachment.GetType();
            if (attType == "CarRadiator" || attType == "CarBattery" || attType == "SparkPlug")
            {
                return false;
            }
        }
        return true;
    }
References GetCarDoorsState().
CanReleaseAttachment() [5/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 112 of file sedan_02.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        string attType = attachment.GetType();
        switch (attType)
        {
        case "CarBattery":
            if (GetCarDoorsState("Sedan_02_Trunk") == CarDoorState.DOORS_CLOSED || EngineIsOn())
            {
                return false;
            }
            break;
        case "SparkPlug":
            if (GetCarDoorsState("Sedan_02_Trunk") == CarDoorState.DOORS_CLOSED || EngineIsOn())
            {
                return false;
            }
            break;
        case "CarRadiator":
            if (GetCarDoorsState("Sedan_02_Hood") == CarDoorState.DOORS_CLOSED || EngineIsOn())
            {
                return false;
            }
            break;
        }
        return true;
    }
References GetCarDoorsState().
CanReleaseAttachment() [6/6]
override bool CarScript::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 119 of file truck_01_base.c.
    {
        if (!super.CanReleaseAttachment(attachment))
        {
            return false;
        }
        if (EngineIsOn() && attachment.GetType() == "TruckBattery")
        {
            return false;
        }
        return true;
    }
CivilianSedan()
void CarScript::CivilianSedan () inline private
Definition at line 7 of file civiliansedan.c.
    {
        m_dmgContactCoef        = 0.065;
        m_EngineStartOK         = "CivilianSedan_engine_start_SoundSet";
        m_EngineStartBattery    = "CivilianSedan_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "CivilianSedan_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "CivilianSedan_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "offroad_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "offroad_door_open_SoundSet";
        m_CarDoorCloseSound     = "offroad_door_close_SoundSet";
        m_CarHornShortSoundName = "CivilianSedan_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "CivilianSedan_Horn_SoundSet";
        SetEnginePos("0 0.7 1.6");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
CreateFrontLight() [1/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 106 of file civiliansedan.c.
    {
        return CarLightBase.Cast( ScriptedLightBase.CreateLight(CivilianSedanFrontLight) );
    }
Referenced by UpdateLightsClient().
CreateFrontLight() [2/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 107 of file hatchback_02.c.
    {
        return CarLightBase.Cast(ScriptedLightBase.CreateLight(Hatchback_02FrontLight));
    }
CreateFrontLight() [3/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 106 of file offroad_02.c.
    {
        return CarLightBase.Cast(ScriptedLightBase.CreateLight(Offroad_02FrontLight));
    }
CreateFrontLight() [4/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 112 of file offroadhatchback.c.
    {
        return CarLightBase.Cast( ScriptedLightBase.CreateLight(OffroadHatchbackFrontLight) );
    }
CreateFrontLight() [5/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 101 of file sedan_02.c.
    {
        return CarLightBase.Cast(ScriptedLightBase.CreateLight(Sedan_02FrontLight));
    }
CreateFrontLight() [6/6]
override CarLightBase CarScript::CreateFrontLight () inline private
Definition at line 108 of file truck_01_base.c.
    {
        return CarLightBase.Cast(ScriptedLightBase.CreateLight(Truck_01FrontLight));
    }
CreateRearLight() [1/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 112 of file civiliansedan.c.
    {
        return CarRearLightBase.Cast( ScriptedLightBase.CreateLight(CivilianSedanRearLight) );
    }
Referenced by UpdateLightsClient().
CreateRearLight() [2/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 101 of file hatchback_02.c.
    {
        return CarRearLightBase.Cast(ScriptedLightBase.CreateLight(Hatchback_02RearLight));
    }
CreateRearLight() [3/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 112 of file offroad_02.c.
    {
        return CarRearLightBase.Cast(ScriptedLightBase.CreateLight(Offroad_02RearLight));
    }
CreateRearLight() [4/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 107 of file offroadhatchback.c.
    {
        return CarRearLightBase.Cast( ScriptedLightBase.CreateLight(OffroadHatchbackRearLight) );
    }
CreateRearLight() [5/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 107 of file sedan_02.c.
    {
        return CarRearLightBase.Cast(ScriptedLightBase.CreateLight(Sedan_02RearLight));
    }
CreateRearLight() [6/6]
override CarRearLightBase CarScript::CreateRearLight () inline private
Definition at line 114 of file truck_01_base.c.
    {
        return CarRearLightBase.Cast(ScriptedLightBase.CreateLight(Truck_01RearLight));
    }
CrewCanGetThrough() [1/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 207 of file civiliansedan.c.
    {
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "CivSedanDriverDoors" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 1:
                if ( GetCarDoorsState( "CivSedanCoDriverDoors" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 2:
                if ( GetCarDoorsState( "CivSedanCargo1Doors" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 3:
                if ( GetCarDoorsState( "CivSedanCargo2Doors" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [2/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 199 of file hatchback_02.c.
    {
        switch (posIdx)
        {
        case 0:
            if (GetCarDoorsState("Hatchback_02_Door_1_1") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
            return true;
        case 1:
            if (GetCarDoorsState("Hatchback_02_Door_2_1") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
            return true;
        case 2:
            if (GetCarDoorsState("Hatchback_02_Door_1_2") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
            return true;
        case 3:
            if (GetCarDoorsState("Hatchback_02_Door_2_2") == CarDoorState.DOORS_CLOSED)
            {
                return false;
            }
            return true;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [3/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 215 of file offroad_02.c.
    {
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "Offroad_02_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 1:
                if ( GetCarDoorsState( "Offroad_02_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 2:
                if ( GetCarDoorsState( "Offroad_02_Door_1_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 3:
                if ( GetCarDoorsState( "Offroad_02_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [4/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 207 of file offroadhatchback.c.
    {
        CarDoor carDoor;
        switch (posIdx)
        {
        case 0:
            if (GetCarDoorsState("NivaDriverDoors") == CarDoorState.DOORS_CLOSED)
                return false;
            else if (GetAnimationPhase("SeatDriver") > 0.5)
                return false;
            return true;
        break;
        case 1:
            if (GetCarDoorsState("NivaCoDriverDoors") == CarDoorState.DOORS_CLOSED)
                return false;
            else if (GetAnimationPhase("SeatCoDriver") > 0.5)
                return false;
            return true;
        break;
        case 2:
            if (GetCarDoorsState("NivaDriverDoors") == CarDoorState.DOORS_CLOSED)
                return false;
            else if (GetAnimationPhase("SeatDriver") <= 0.5)
                return false;
            return true;
        break;
        case 3:
            if (GetCarDoorsState("NivaCoDriverDoors") == CarDoorState.DOORS_CLOSED)
                return false;
            else if (GetAnimationPhase("SeatCoDriver") <= 0.5)
                return false;
            return true;
        break;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [5/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 225 of file sedan_02.c.
    {
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "Sedan_02_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 1:
                if ( GetCarDoorsState( "Sedan_02_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 2:
                if ( GetCarDoorsState( "Sedan_02_Door_1_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 3:
                if ( GetCarDoorsState( "Sedan_02_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [6/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 149 of file truck_01_base.c.
    {
        CarDoor carDoor;
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "Truck_01_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            case 1:
                if ( GetCarDoorsState( "Truck_01_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [7/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 127 of file truck_02.c.
    {
        CarDoor carDoor;
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "Truck_02_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                {
                    return false;
                }
                return true;
            break;
            case 1:
                if ( GetCarDoorsState( "Truck_02_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                {
                    return false;
                }
                return true;
            break;
        }
        return false;
    }
References GetCarDoorsState().
CrewCanGetThrough() [8/8]
override bool CarScript::CrewCanGetThrough (int posIdx) inline private
Definition at line 145 of file van_01.c.
    {
        switch( posIdx )
        {
            case 0:
                if ( GetCarDoorsState( "Van_01_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 1:
                if ( GetCarDoorsState( "Van_01_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 2:
                if ( GetCarDoorsState( "Van_01_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
            case 3:
                if ( GetCarDoorsState( "Van_01_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
            case 4:
                if ( GetCarDoorsState( "Van_01_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    return false;
                return true;
            break;
        }
        return false;
    }
References GetCarDoorsState().
EEInit() [1/8]
override void CarScript::EEInit () inline private
Definition at line 26 of file civiliansedan.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [2/8]
override void CarScript::EEInit () inline private
Definition at line 26 of file hatchback_02.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [3/8]
override void CarScript::EEInit () inline private
Definition at line 26 of file offroad_02.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [4/8]
override void CarScript::EEInit () inline private
Definition at line 26 of file offroadhatchback.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [5/8]
override void CarScript::EEInit () inline private
Definition at line 26 of file sedan_02.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [6/8]
override void CarScript::EEInit () inline private
Definition at line 27 of file truck_01_base.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [7/8]
override void CarScript::EEInit () inline private
Definition at line 13 of file truck_02.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EEInit() [8/8]
override void CarScript::EEInit () inline private
Definition at line 12 of file van_01.c.
    {
        super.EEInit();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_ManualUpdate    = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = 30;
            m_UTSSettings.m_RangeFull       = 0.5;
            m_UTSSettings.m_RangeMax        = 2;
            m_UTSSettings.m_TemperatureCap  = 25;
            m_UTSLEngine                    = new UniversalTemperatureSourceLambdaEngine();
            m_UTSource                      = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLEngine);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_ManualUpdate, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [1/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file civiliansedan.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [2/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file hatchback_02.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [3/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file offroad_02.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [4/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file offroadhatchback.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [5/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 65 of file sedan_02.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [6/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 66 of file truck_01_base.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [7/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 52 of file truck_02.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
EOnPostSimulate() [8/8]
override void CarScript::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 51 of file van_01.c.
    {
        super.EOnPostSimulate(other, timeSlice);
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if (m_UTSource.IsActive())
            {
                m_UTSource.Update(m_UTSSettings, m_UTSLEngine);
            }
        }
    }
References GetGame(), m_UTSLEngine, m_UTSource, and m_UTSSettings.
GetAnimInstance() [1/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 78 of file civiliansedan.c.
    {
        return VehicleAnimInstances.SEDAN;
    }
GetAnimInstance() [2/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 78 of file hatchback_02.c.
    {
        return VehicleAnimInstances.GOLF;
    }
GetAnimInstance() [3/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 78 of file offroad_02.c.
    {
        return VehicleAnimInstances.HMMWV;
    }
GetAnimInstance() [4/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 78 of file offroadhatchback.c.
    {
        return VehicleAnimInstances.HATCHBACK;
    }
GetAnimInstance() [5/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 78 of file sedan_02.c.
    {
        return VehicleAnimInstances.S120;
    }
GetAnimInstance() [6/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 89 of file truck_01_base.c.
    {
        return VehicleAnimInstances.V3S;
    }
GetAnimInstance() [7/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 65 of file truck_02.c.
    {
        return VehicleAnimInstances.MULTICAR;
    }
GetAnimInstance() [8/8]
override int CarScript::GetAnimInstance () inline private
Definition at line 65 of file van_01.c.
    {
        return VehicleAnimInstances.CIVVAN;
    }
GetAnimSourceFromSelection() [1/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 330 of file civiliansedan.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_cargo1":
            return "DoorsCargo1";
        case "doors_cargo2":
            return "DoorsCargo2";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        }
        return "";
    }
Referenced by ActionAnimateCarSelection::ActionCondition(), ActionAnimateSeats::ActionCondition(), ActionCarDoors::ActionCondition(), ActionCarDoorsOutside::ActionCondition(), ActionCarDoors::OnStartServer(), and ActionCarDoorsOutside::OnStartServer().
GetAnimSourceFromSelection() [2/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 314 of file hatchback_02.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_cargo1":
            return "DoorsCargo1";
        case "doors_cargo2":
            return "DoorsCargo2";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        }
        return "";
    }
GetAnimSourceFromSelection() [3/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 326 of file offroad_02.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_cargo1":
            return "DoorsCargo1";
        case "doors_cargo2":
            return "DoorsCargo2";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        }
        return "";
    }
GetAnimSourceFromSelection() [4/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 333 of file offroadhatchback.c.
    {
        switch (selection)
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        case "seatback_driver":
            return "SeatDriver";
        case "seatback_codriver":
            return "SeatCoDriver";
        }
        return "";
    }
GetAnimSourceFromSelection() [5/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 336 of file sedan_02.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_cargo1":
            return "DoorsCargo1";
        case "doors_cargo2":
            return "DoorsCargo2";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        }
        return "";
    }
GetAnimSourceFromSelection() [6/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 275 of file truck_01_base.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        case "wheelsideplate1":
            return "WheelSidePlate1";
        case "wheelsideplate2":
            return "WheelSidePlate2";
        }
        return "";
    }
GetAnimSourceFromSelection() [7/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 182 of file truck_02.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_hood":
            return "DoorsHood";
        case "doors_trunk":
            return "DoorsTrunk";
        case "wheelsideplate1":
            return "WheelSidePlate1";
        case "wheelsideplate2":
            return "WheelSidePlate2";
        }
        return "";
    }
GetAnimSourceFromSelection() [8/8]
override string CarScript::GetAnimSourceFromSelection (string selection) inline private
Definition at line 224 of file van_01.c.
    {
        switch( selection )
        {
        case "doors_driver":
            return "DoorsDriver";
        case "doors_codriver":
            return "DoorsCoDriver";
        case "doors_cargo1":
            return "DoorsCargo1";
        case "doors_cargo2":
            return "DoorsCargo2";
        case "doors_cargo3":
            return "DoorsCargo3";
        case "doors_hood":
            return "DoorsHood";
        }
        return "";
    }
GetCarDoorsState() [1/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 166 of file civiliansedan.c.
    {
        CarDoor carDoor;
        Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "CivSedanDriverDoors":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
            break;
        case "CivSedanCoDriverDoors":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
            break;
        case "CivSedanCargo1Doors":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo1");
            break;
        case "CivSedanCargo2Doors":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo2");
            break;
        case "CivSedanTrunk":
            return TranslateAnimationPhaseToCarDoorState("DoorsTrunk");
            break;
        case "CivSedanHood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
            break;
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
Referenced by ActionLockAttachment::ActionCondition(), ActionRepairCarPart::ActionCondition(), ActionAnimateSeats::ActionCondition(), ActionCarDoors::ActionCondition(), InventoryItemSuper::CanDetachAttachment(), CanDisplayAttachmentCategory(), CanDisplayCargo(), CanManipulateSpareWheel(), CanReleaseAttachment(), CrewCanGetThrough(), and OnSound().
GetCarDoorsState() [2/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 164 of file hatchback_02.c.
    {
        CarDoor carDoor;
        Class.CastTo(carDoor, FindAttachmentBySlotName(slotType));
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "Hatchback_02_Door_1_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
        case "Hatchback_02_Door_2_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
        case "Hatchback_02_Door_1_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo1");
        case "Hatchback_02_Door_2_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo2");
        case "Hatchback_02_Hood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
        case "Hatchback_02_Trunk":
            return TranslateAnimationPhaseToCarDoorState("DoorsTrunk");
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [3/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 180 of file offroad_02.c.
    {
        CarDoor carDoor;
        Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "Offroad_02_Door_1_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
        case "Offroad_02_Door_2_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
        case "Offroad_02_Door_1_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo1");
        case "Offroad_02_Door_2_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo2");
        case "Offroad_02_Hood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
        case "Offroad_02_Trunk":
            return TranslateAnimationPhaseToCarDoorState("DoorsTrunk");
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [4/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 175 of file offroadhatchback.c.
    {
        CarDoor carDoor;
        Class.CastTo(carDoor, FindAttachmentBySlotName(slotType));
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "NivaDriverDoors":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
            break;
        case "NivaCoDriverDoors":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
            break;
        case "NivaHood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
            break;
        case "NivaTrunk":
            return TranslateAnimationPhaseToCarDoorState("DoorsTrunk");
            break;
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [5/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 190 of file sedan_02.c.
    {
        CarDoor carDoor;
        Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "Sedan_02_Door_1_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
        case "Sedan_02_Door_2_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
        case "Sedan_02_Door_1_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo1");
        case "Sedan_02_Door_2_2":
            return TranslateAnimationPhaseToCarDoorState("DoorsCargo2");
        case "Sedan_02_Hood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
        case "Sedan_02_Trunk":
            return TranslateAnimationPhaseToCarDoorState("DoorsTrunk");
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [6/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 253 of file truck_01_base.c.
    {
        CarDoor carDoor;
        Class.CastTo(carDoor, FindAttachmentBySlotName(slotType));
        if (!carDoor)
        {
            return CarDoorState.DOORS_MISSING;
        }
        switch (slotType)
        {
        case "Truck_01_Door_1_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsDriver");
        case "Truck_01_Door_2_1":
            return TranslateAnimationPhaseToCarDoorState("DoorsCoDriver");
        case "Truck_01_Hood":
            return TranslateAnimationPhaseToCarDoorState("DoorsHood");
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo(), and TranslateAnimationPhaseToCarDoorState().
GetCarDoorsState() [7/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 83 of file truck_02.c.
    {
        CarDoor carDoor;
        switch( slotType )
        {
            case "Truck_02_Door_1_1":
                Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
                if ( carDoor )
                {
                    if ( GetAnimationPhase("DoorsDriver") > 0.5 )
                    {
                        return CarDoorState.DOORS_OPEN;
                    }
                    else
                    {
                        return CarDoorState.DOORS_CLOSED;
                    }
                }
                return CarDoorState.DOORS_MISSING;
            break;
            case "Truck_02_Door_2_1":
                Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
                if ( carDoor )
                {
                    if ( GetAnimationPhase("DoorsCoDriver") > 0.5 )
                    {
                        return CarDoorState.DOORS_OPEN;
                    }
                    else
                    {
                        return CarDoorState.DOORS_CLOSED;
                    }
                }
                return CarDoorState.DOORS_MISSING;
            break;
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo().
GetCarDoorsState() [8/8]
override int CarScript::GetCarDoorsState (string slotType) inline private
Definition at line 91 of file van_01.c.
    {
        CarDoor carDoor;
        Class.CastTo( carDoor, FindAttachmentBySlotName( slotType ) );
        if ( !carDoor )
            return CarDoorState.DOORS_MISSING;
        switch( slotType )
        {
            case "Van_01_Door_1_1":
                if ( GetAnimationPhase("DoorsDriver") > 0.5 )
                    return CarDoorState.DOORS_OPEN;
                else
                    return CarDoorState.DOORS_CLOSED;
            break;
            case "Van_01_Door_2_1":
                if ( GetAnimationPhase("DoorsCoDriver") > 0.5 )
                    return CarDoorState.DOORS_OPEN;
                else
                    return CarDoorState.DOORS_CLOSED;
            break;
            case "Van_01_Door_2_2":
                if ( GetAnimationPhase("DoorsCargo1") > 0.5 )
                    return CarDoorState.DOORS_OPEN;
                else
                    return CarDoorState.DOORS_CLOSED;
            break;
            case "Van_01_Trunk_1":
                if ( GetAnimationPhase("DoorsCargo3") > 0.5 )
                    return CarDoorState.DOORS_OPEN;
                else
                    return CarDoorState.DOORS_CLOSED;
            break;
            case "Van_01_Trunk_2":
                if ( GetAnimationPhase("DoorsCargo2") > 0.5 )
                    return CarDoorState.DOORS_OPEN;
                else
                    return CarDoorState.DOORS_CLOSED;
            break;
        }
        return CarDoorState.DOORS_MISSING;
    }
References Class::CastTo().
GetCrewIndex()
override int CarScript::GetCrewIndex (string selection) inline private
Definition at line 373 of file offroadhatchback.c.
    {
        switch( selection )
        {
        case "seatback_driver":
            return 0;
        case "seatback_codriver":
            return 1;
        }
        return -1;
    }
GetDoorConditionPointFromSelection() [1/2]
override string CarScript::GetDoorConditionPointFromSelection (string selection) inline private
Definition at line 354 of file offroadhatchback.c.
    {
        switch( selection )
        {
        case "seat_driver":
        case "seatback_driver":
        case "seat_cargo1":
            return "seat_con_1_1";
        break;
        case "seat_codriver":
        case "seatback_codriver":
        case "seat_cargo2":
            return "seat_con_2_1";
        break;
        }
        return "";
    }
Referenced by CanReachSeatFromDoors().
GetDoorConditionPointFromSelection() [2/2]
override string CarScript::GetDoorConditionPointFromSelection (string selection) inline private
Definition at line 246 of file van_01.c.
    {
            switch( selection )
        {
            case "seat_driver":
                return "seat_con_1_1";
            break;
            case "seat_codriver":
                return "seat_con_2_1";
            break;
            case "seat_cargo1":
            case "seat_cargo2":
            case "seat_cargo3":
                return "seat_con_1_2";
            break;
        }
        return "";
    };
GetDoorInvSlotNameFromSeatPos() [1/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 264 of file civiliansedan.c.
    {
        switch( posIdx )
        {
        case 0:
            return "CivSedanDriverDoors";
        break;
        case 1:
            return "CivSedanCoDriverDoors";
        break;
        case 2:
            return "CivSedanCargo1Doors";
        break;
        case 3:
            return "CivSedanCargo2Doors";
        break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
Referenced by ActionCarDoors::ActionCondition().
GetDoorInvSlotNameFromSeatPos() [2/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 260 of file hatchback_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "Hatchback_02_Door_1_1";
        break;
        case 1:
            return "Hatchback_02_Door_2_1";
        break;
        case 2:
            return "Hatchback_02_Door_1_2";
        break;
        case 3:
            return "Hatchback_02_Door_2_2";
        break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
GetDoorInvSlotNameFromSeatPos() [3/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 272 of file offroad_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "Offroad_02_Door_1_1";
        break;
        case 1:
            return "Offroad_02_Door_2_1";
        break;
        case 2:
            return "Offroad_02_Door_1_2";
        break;
        case 3:
            return "Offroad_02_Door_2_2";
        break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
GetDoorInvSlotNameFromSeatPos() [4/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 269 of file offroadhatchback.c.
    {
        switch (posIdx)
        {
        case 0:
        case 2:
            return "NivaDriverDoors";
        break;
        case 1:
        case 3:
            return "NivaCoDriverDoors";
        break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
GetDoorInvSlotNameFromSeatPos() [5/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 282 of file sedan_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "Sedan_02_Door_1_1";
        break;
        case 1:
            return "Sedan_02_Door_2_1";
        break;
        case 2:
            return "Sedan_02_Door_1_2";
        break;
        case 3:
            return "Sedan_02_Door_2_2";
        break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
GetDoorInvSlotNameFromSeatPos() [6/6]
override string CarScript::GetDoorInvSlotNameFromSeatPos (int posIdx) inline private
Definition at line 185 of file truck_01_base.c.
    {
        switch( posIdx )
        {
            case 0:
                return "Truck_01_Door_1_1";
            break;
            case 1:
                return "Truck_01_Door_2_1";
            break;
        }
        return super.GetDoorInvSlotNameFromSeatPos(posIdx);
    }
GetDoorSelectionNameFromSeatPos() [1/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 243 of file civiliansedan.c.
    {
        switch( posIdx )
        {
        case 0:
            return "doors_driver";
        break;
        case 1:
            return "doors_codriver";
        break;
        case 2:
            return "doors_cargo1";
        break;
        case 3:
            return "doors_cargo2";
        break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
Referenced by ActionCarDoors::ActionCondition(), and ActionCarDoors::OnStartServer().
GetDoorSelectionNameFromSeatPos() [2/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 239 of file hatchback_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "doors_driver";
        break;
        case 1:
            return "doors_codriver";
        break;
        case 2:
            return "doors_cargo1";
        break;
        case 3:
            return "doors_cargo2";
        break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
GetDoorSelectionNameFromSeatPos() [3/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 251 of file offroad_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "doors_driver";
        break;
        case 1:
            return "doors_codriver";
        break;
        case 2:
            return "doors_cargo1";
        break;
        case 3:
            return "doors_cargo2";
        break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
GetDoorSelectionNameFromSeatPos() [4/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 252 of file offroadhatchback.c.
    {
        switch (posIdx)
        {
        case 0:
        case 2:
            return "doors_driver";
        break;
        case 1:
        case 3:
            return "doors_codriver";
        break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
GetDoorSelectionNameFromSeatPos() [5/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 261 of file sedan_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return "doors_driver";
        break;
        case 1:
            return "doors_codriver";
        break;
        case 2:
            return "doors_cargo1";
        break;
        case 3:
            return "doors_cargo2";
        break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
GetDoorSelectionNameFromSeatPos() [6/6]
override string CarScript::GetDoorSelectionNameFromSeatPos (int posIdx) inline private
Definition at line 170 of file truck_01_base.c.
    {
        switch( posIdx )
        {
            case 0:
                return "doors_driver";
            break;
            case 1:
                return "doors_codriver";
            break;
        }
        return super.GetDoorSelectionNameFromSeatPos(posIdx);
    }
GetSeatAnimationType() [1/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 88 of file civiliansedan.c.
    {
        switch (posIdx)
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_R;
        }
        return 0;
    }
GetSeatAnimationType() [2/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 83 of file hatchback_02.c.
    {
        switch (posIdx)
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_R;
        }
        return 0;
    }
GetSeatAnimationType() [3/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 88 of file offroad_02.c.
    {
        switch (posIdx)
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_R;
        }
        return 0;
    }
GetSeatAnimationType() [4/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 88 of file offroadhatchback.c.
    {
        switch( posIdx )
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_R;
        }
        return 0;
    }
GetSeatAnimationType() [5/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 83 of file sedan_02.c.
    {
        switch (posIdx)
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_R;
        }
        return 0;
    }
GetSeatAnimationType() [6/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 94 of file truck_01_base.c.
    {
        switch (posIdx)
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        }
        return 0;
    }
GetSeatAnimationType() [7/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 70 of file truck_02.c.
    {
        switch( posIdx )
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        }
        return 0;
    }
GetSeatAnimationType() [8/8]
override int CarScript::GetSeatAnimationType (int posIdx) inline private
Definition at line 71 of file van_01.c.
    {
        switch( posIdx )
        {
        case 0:
            return DayZPlayerConstants.VEHICLESEAT_DRIVER;
        case 1:
            return DayZPlayerConstants.VEHICLESEAT_CODRIVER;
        case 2:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 3:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        case 4:
            return DayZPlayerConstants.VEHICLESEAT_PASSENGER_L;
        }
        return 0;
    }
GetSeatIndexFromDoor() [1/3]
override int CarScript::GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 468 of file offroadhatchback.c.
    {
        switch (pDoorSelection)
        {
            case "DoorsDriver":
                return 0;
                break;
            case "DoorsCoDriver":
                return 1;
                break;
        }
        return -1;
    }
Referenced by ActionCarDoorsOutside::ActionCondition().
GetSeatIndexFromDoor() [2/3]
override int CarScript::GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 334 of file truck_01_base.c.
    {
        switch (pDoorSelection)
        {
            case "DoorsDriver":
                return 0;
                break;
            case "DoorsCoDriver":
                return 1;
                break;
        }
        return -1;
    }
GetSeatIndexFromDoor() [3/3]
override int CarScript::GetSeatIndexFromDoor (string pDoorSelection) inline private
Definition at line 268 of file truck_02.c.
    {
        switch (pDoorSelection)
        {
            case "DoorsDriver":
                return 0;
                break;
            case "DoorsCoDriver":
                return 1;
                break;
        }
        return -1;
    }
GetTransportCameraDistance() [1/4]
override float CarScript::GetTransportCameraDistance () inline private
Definition at line 83 of file civiliansedan.c.
    {
        return 4.5;
    }
GetTransportCameraDistance() [2/4]
override float CarScript::GetTransportCameraDistance () inline private
Definition at line 83 of file offroad_02.c.
    {
        return 5.1;
    }
GetTransportCameraDistance() [3/4]
override float CarScript::GetTransportCameraDistance () inline private
Definition at line 83 of file offroadhatchback.c.
    {
        return 3.5;
    }
GetTransportCameraDistance() [4/4]
override float CarScript::GetTransportCameraDistance () inline private
Definition at line 79 of file truck_01_base.c.
    {
        return 6.0;
    }
GetTransportCameraOffset()
override vector CarScript::GetTransportCameraOffset () inline private
Definition at line 84 of file truck_01_base.c.
    {
        return "0 3.2 0";
    }
Hatchback_02()
void CarScript::Hatchback_02 () inline private
Definition at line 7 of file hatchback_02.c.
    {
        m_dmgContactCoef        = 0.070;
        m_EngineStartOK         = "Hatchback_02_engine_start_SoundSet";
        m_EngineStartBattery    = "Hatchback_02_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "Hatchback_02_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "Hatchback_02_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "offroad_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "offroad_door_open_SoundSet";
        m_CarDoorCloseSound     = "offroad_door_close_SoundSet";
        m_CarHornShortSoundName = "Hatchback_02_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "Hatchback_02_Horn_SoundSet";
        SetEnginePos("0 0.7 1.4");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
IsVitalCarBattery() [1/2]
override bool CarScript::IsVitalCarBattery () inline private
Definition at line 349 of file truck_01_base.c.
    {
        return false;
    }
Referenced by ActionSwitchLights::ActionCondition(), EOnPostSimulate(), GetBattery(), and OnBeforeEngineStart().
IsVitalCarBattery() [2/2]
override bool CarScript::IsVitalCarBattery () inline private
Definition at line 203 of file truck_02.c.
    {
        return false;
    }
IsVitalEngineBelt() [1/2]
override bool CarScript::IsVitalEngineBelt () inline private
Definition at line 364 of file truck_01_base.c.
    {
        return false;
    }
IsVitalEngineBelt() [2/2]
override bool CarScript::IsVitalEngineBelt () inline private
Definition at line 218 of file truck_02.c.
    {
        return false;
    }
IsVitalGlowPlug() [1/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 356 of file civiliansedan.c.
    {
        return false;
    }
Referenced by EOnPostSimulate(), and OnBeforeEngineStart().
IsVitalGlowPlug() [2/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 341 of file hatchback_02.c.
    {
        return false;
    }
IsVitalGlowPlug() [3/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 391 of file offroadhatchback.c.
    {
        return false;
    }
IsVitalGlowPlug() [4/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 363 of file sedan_02.c.
    {
        return false;
    }
IsVitalGlowPlug() [5/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 359 of file truck_01_base.c.
    {
        return false;
    }
IsVitalGlowPlug() [6/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 213 of file truck_02.c.
    {
        return false;
    }
IsVitalGlowPlug() [7/7]
override bool CarScript::IsVitalGlowPlug () inline private
Definition at line 273 of file van_01.c.
    {
        return false;
    }
IsVitalRadiator() [1/3]
override bool CarScript::IsVitalRadiator () inline private
Definition at line 416 of file offroad_02.c.
    {
        return false;
    }
Referenced by EOnPostSimulate(), and Hud::RefreshVehicleHud().
IsVitalRadiator() [2/3]
override bool CarScript::IsVitalRadiator () inline private
Definition at line 369 of file truck_01_base.c.
    {
        return false;
    }
IsVitalRadiator() [3/3]
override bool CarScript::IsVitalRadiator () inline private
Definition at line 223 of file truck_02.c.
    {
        return false;
    }
IsVitalSparkPlug() [1/3]
override bool CarScript::IsVitalSparkPlug () inline private
Definition at line 411 of file offroad_02.c.
    {
        return false;
    }
Referenced by EOnPostSimulate(), and OnBeforeEngineStart().
IsVitalSparkPlug() [2/3]
override bool CarScript::IsVitalSparkPlug () inline private
Definition at line 354 of file truck_01_base.c.
    {
        return false;
    }
IsVitalSparkPlug() [3/3]
override bool CarScript::IsVitalSparkPlug () inline private
Definition at line 208 of file truck_02.c.
    {
        return false;
    }
IsVitalTruckBattery() [1/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 351 of file civiliansedan.c.
    {
        return false;
    }
Referenced by ActionSwitchLights::ActionCondition(), EOnPostSimulate(), GetBattery(), and OnBeforeEngineStart().
IsVitalTruckBattery() [2/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 336 of file hatchback_02.c.
    {
        return false;
    }
IsVitalTruckBattery() [3/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 406 of file offroad_02.c.
    {
        return false;
    }
IsVitalTruckBattery() [4/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 386 of file offroadhatchback.c.
    {
        return false;
    }
IsVitalTruckBattery() [5/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 358 of file sedan_02.c.
    {
        return false;
    }
IsVitalTruckBattery() [6/6]
override bool CarScript::IsVitalTruckBattery () inline private
Definition at line 267 of file van_01.c.
    {
        return false;
    }
Offroad_02()
void CarScript::Offroad_02 () inline private
Definition at line 7 of file offroad_02.c.
    {
        m_dmgContactCoef        = 0.0365;
        m_EngineStartOK         = "Offroad_02_engine_start_SoundSet";
        m_EngineStartBattery    = "Offroad_02_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "Offroad_02_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "Offroad_02_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "offroad_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "offroad_02_door_open_SoundSet";
        m_CarDoorCloseSound     = "offroad_02_door_close_SoundSet";
        m_CarHornShortSoundName = "Offroad_02_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "Offroad_02_Horn_SoundSet";
        SetEnginePos("0 0.7 1.7");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
OffroadHatchback()
void CarScript::OffroadHatchback () inline private
Definition at line 7 of file offroadhatchback.c.
    {
        m_dmgContactCoef        = 0.075;
        m_EngineStartOK         = "offroad_engine_start_SoundSet";
        m_EngineStartBattery    = "offroad_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "offroad_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "offroad_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "offroad_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "offroad_door_open_SoundSet";
        m_CarDoorCloseSound     = "offroad_door_close_SoundSet";
        m_CarHornShortSoundName = "Offroad_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "Offroad_Horn_SoundSet";
        SetEnginePos("0 0.7 1.2");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
OnAnimationPhaseStarted()
override void CarScript::OnAnimationPhaseStarted (string animSource, float phase) inline private
Definition at line 225 of file truck_01_base.c.
    {
        super.OnAnimationPhaseStarted(animSource, phase);
        #ifndef SERVER
        switch (animSource)
        {
        case "wheelsideplate1":
        case "wheelsideplate2":
            EffectSound sound;
            if (phase == 0)
            {
                sound = SEffectManager.PlaySound("Truck_01_Gear_Open_Side_Plate_SoundSet", GetPosition(), 0.1, 0.1);
            }
            else
            {
                sound = SEffectManager.PlaySound("Truck_01_Gear_Close_Side_Plate_SoundSet", GetPosition(), 0.1, 0.1);
            }
            if (sound)
            {
                sound.SetAutodestroy(true);
            }
        break;
        }
        #endif
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnDebugSpawn() [1/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 419 of file civiliansedan.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "CivSedanWheel" );
            entity.GetInventory().CreateInInventory( "CivSedanWheel" );
            entity.GetInventory().CreateInInventory( "CivSedanWheel" );
            entity.GetInventory().CreateInInventory( "CivSedanWheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            entity.GetInventory().CreateInInventory( "CivSedanDoors_Driver" );
            entity.GetInventory().CreateInInventory( "CivSedanDoors_CoDriver" );
            entity.GetInventory().CreateInInventory( "CivSedanDoors_BackLeft" );
            entity.GetInventory().CreateInInventory( "CivSedanDoors_BackRight" );
            entity.GetInventory().CreateInInventory( "CivSedanHood" );
            entity.GetInventory().CreateInInventory( "CivSedanTrunk" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "CivSedanWheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
        Fill( CarFluid.OIL, 4.0 );
    }
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [2/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 404 of file hatchback_02.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_1" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_2" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_1" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_2" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Hood" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Trunk" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
        Fill( CarFluid.OIL, 4.0 );
    }
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [3/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 421 of file offroad_02.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Offroad_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "GlowPlug" );
            //entity.GetInventory().CreateInInventory( "Offroad_02_Door_1_1" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Door_1_2" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Door_2_1" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Door_2_2" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Hood" );
            entity.GetInventory().CreateInInventory( "Offroad_02_Trunk" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "GlowPlug" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "Offroad_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "GlowkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 120 );
    }
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [4/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 482 of file offroadhatchback.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "HatchbackWheel" );
            entity.GetInventory().CreateInInventory( "HatchbackWheel" );
            entity.GetInventory().CreateInInventory( "HatchbackWheel" );
            entity.GetInventory().CreateInInventory( "HatchbackWheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //entity.GetInventory().CreateInInventory( "HatchbackDoors_Driver" );
            entity.GetInventory().CreateInInventory( "HatchbackDoors_CoDriver" );
            entity.GetInventory().CreateInInventory( "HatchbackHood" );
            entity.GetInventory().CreateInInventory( "HatchbackTrunk" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "HatchbackWheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
        Fill( CarFluid.OIL, 4.0 );
    }
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [5/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 426 of file sedan_02.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Sedan_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //entity.GetInventory().CreateInInventory( "Sedan_02_Door_1_1" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Door_1_2" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Door_2_1" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Door_2_2" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Hood" );
            entity.GetInventory().CreateInInventory( "Sedan_02_Trunk" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
        Fill( CarFluid.OIL, 4.0 );
    }
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [6/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 387 of file truck_01_base.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Truck_01_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_01_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_01_WheelDouble" );
            entity.GetInventory().CreateInInventory( "Truck_01_WheelDouble" );
            entity.GetInventory().CreateInInventory( "Truck_01_WheelDouble" );
            entity.GetInventory().CreateInInventory( "Truck_01_WheelDouble" );
            entity.GetInventory().CreateInInventory( "TruckBattery" );
            entity.GetInventory().CreateInInventory( "Truck_01_Door_1_1" );
            entity.GetInventory().CreateInInventory( "Truck_01_Door_2_1" );
            entity.GetInventory().CreateInInventory( "Truck_01_Hood" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "Truck_01_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_01_Wheel" );
            entity.GetInventory().CreateInInventory( "TruckBattery" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 120 );
        Fill( CarFluid.OIL, 4.0 );
    };
References Class::CastTo(), and LIQUID_WATER.
OnDebugSpawn() [7/7]
override void CarScript::OnDebugSpawn () inline private
Definition at line 282 of file truck_02.c.
    {
        EntityAI entity;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Truck_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Truck_02_Wheel" );
            entity.GetInventory().CreateInInventory( "TruckBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "Truck_02_Door_1_1" );
            entity.GetInventory().CreateInInventory( "Truck_02_Door_2_1" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.OIL, 4.0 );
    };
References Class::CastTo().
OnEngineStart() [1/8]
override void CarScript::OnEngineStart () inline private
Definition at line 45 of file civiliansedan.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [2/8]
override void CarScript::OnEngineStart () inline private
Definition at line 45 of file hatchback_02.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [3/8]
override void CarScript::OnEngineStart () inline private
Definition at line 45 of file offroad_02.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [4/8]
override void CarScript::OnEngineStart () inline private
Definition at line 45 of file offroadhatchback.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [5/8]
override void CarScript::OnEngineStart () inline private
Definition at line 45 of file sedan_02.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [6/8]
override void CarScript::OnEngineStart () inline private
Definition at line 46 of file truck_01_base.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [7/8]
override void CarScript::OnEngineStart () inline private
Definition at line 32 of file truck_02.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStart() [8/8]
override void CarScript::OnEngineStart () inline private
Definition at line 31 of file van_01.c.
    {
        super.OnEngineStart();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(true, 20.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [1/8]
override void CarScript::OnEngineStop () inline private
Definition at line 55 of file civiliansedan.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [2/8]
override void CarScript::OnEngineStop () inline private
Definition at line 55 of file hatchback_02.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [3/8]
override void CarScript::OnEngineStop () inline private
Definition at line 55 of file offroad_02.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [4/8]
override void CarScript::OnEngineStop () inline private
Definition at line 55 of file offroadhatchback.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [5/8]
override void CarScript::OnEngineStop () inline private
Definition at line 55 of file sedan_02.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [6/8]
override void CarScript::OnEngineStop () inline private
Definition at line 56 of file truck_01_base.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [7/8]
override void CarScript::OnEngineStop () inline private
Definition at line 42 of file truck_02.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnEngineStop() [8/8]
override void CarScript::OnEngineStop () inline private
Definition at line 41 of file van_01.c.
    {
        super.OnEngineStop();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSource.SetDefferedActive(false, 10.0);
        }
    }
References GetGame(), and m_UTSource.
OnSound() [1/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 287 of file civiliansedan.c.
    {
        switch (ctrl)
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            if (GetCarDoorsState("CivSedanDriverDoors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("CivSedanCoDriverDoors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("CivSedanCargo1Doors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("CivSedanCargo2Doors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetHealthLevel("WindowFront") == GameConstants.STATE_RUINED)
            {
                newValue -= 0.6;
            }
            if (GetHealthLevel("WindowBack") == GameConstants.STATE_RUINED)
            {
                newValue -= 0.6;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), GetCarDoorsState(), GetHealthLevel(), and GameConstants::STATE_RUINED.
OnSound() [2/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 281 of file hatchback_02.c.
    {
        switch (ctrl)
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            if (GetCarDoorsState("Hatchback_02_Door_1_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Hatchback_02_Door_2_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Hatchback_02_Door_1_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Hatchback_02_Door_2_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), and GetCarDoorsState().
OnSound() [3/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 293 of file offroad_02.c.
    {
        switch ( ctrl )
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            if (GetCarDoorsState("Offroad_02_Door_1_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Offroad_02_Door_2_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Offroad_02_Door_1_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Offroad_02_Door_2_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), and GetCarDoorsState().
OnSound() [4/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 288 of file offroadhatchback.c.
    {
        float tempCap = 0.0;
        switch (ctrl)
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            if (GetCarDoorsState("NivaDriverDoors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.5;
            }
            if (GetCarDoorsState("NivaCoDriverDoors") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.5;
            }
            if (GetCarDoorsState("NivaTrunk") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.3;
            }
            if (GetHealthLevel("WindowFront") == GameConstants.STATE_RUINED)
            {
                newValue -= 0.6;
            }
            if (GetHealthLevel("WindowLR") == GameConstants.STATE_RUINED)
            {
                newValue -= 0.2;
            }
            if (GetHealthLevel("WindowRR") == GameConstants.STATE_RUINED)
            {
                newValue -= 0.2;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), GetCarDoorsState(), GetHealthLevel(), and GameConstants::STATE_RUINED.
OnSound() [5/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 303 of file sedan_02.c.
    {
        switch ( ctrl )
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            if (GetCarDoorsState("Sedan_02_Door_1_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Sedan_02_Door_2_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Sedan_02_Door_1_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            if (GetCarDoorsState("Sedan_02_Door_2_2") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.25;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), and GetCarDoorsState().
OnSound() [6/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 200 of file truck_01_base.c.
    {
        switch (ctrl)
        {
        case CarSoundCtrl.DOORS:
            float newValue = 0;
            //-----
            if (GetCarDoorsState("Truck_01_Door_1_1") == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.4;
            }
            if (GetCarDoorsState( "Truck_01_Door_2_1" ) == CarDoorState.DOORS_CLOSED)
            {
                newValue += 0.4;
            }
            return Math.Clamp(newValue, 0, 1);
        break;
        }
        return super.OnSound(ctrl, oldValue);
    }
References Math::Clamp(), and GetCarDoorsState().
OnSound() [7/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 154 of file truck_02.c.
    {
        switch ( ctrl )
        {
            case CarSoundCtrl.DOORS:
                float newValue = 0;
                //-----
                if ( GetCarDoorsState( "Truck_02_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                {
                    newValue += 0.4;
                }
                if ( GetCarDoorsState( "Truck_02_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                {
                    newValue += 0.4;
                }
                if ( newValue > 1 )
                    newValue = 1;
            return newValue;
            break;
        }
        return oldValue;
    }
References GetCarDoorsState().
OnSound() [8/8]
override float CarScript::OnSound (CarSoundCtrl ctrl, float oldValue) inline private
Definition at line 186 of file van_01.c.
    {
        switch ( ctrl )
        {
            case CarSoundCtrl.DOORS:
                float newValue = 0;
                //-----
                if ( GetCarDoorsState( "Van_01_Door_1_1" ) == CarDoorState.DOORS_CLOSED )
                    newValue += 0.25;
                //-----
                if ( GetCarDoorsState( "Van_01_Door_2_1" ) == CarDoorState.DOORS_CLOSED )
                    newValue += 0.25;
                //-----
                if ( GetCarDoorsState( "Van_01_Door_2_2" ) == CarDoorState.DOORS_CLOSED )
                    newValue += 0.25;
                //-----
                if ( GetCarDoorsState( "Van_01_Trunk_1" ) == CarDoorState.DOORS_CLOSED )
                    newValue += 0.125;
                //-----
                if ( GetCarDoorsState( "Van_01_Trunk_2" ) == CarDoorState.DOORS_CLOSED )
                    newValue += 0.125;
                if ( newValue > 1 )
                    newValue = 1;
                return newValue;
            break;
        }
        return oldValue;
    }
References GetCarDoorsState().
Sedan_02()
void CarScript::Sedan_02 () inline private
Definition at line 7 of file sedan_02.c.
    {
        m_dmgContactCoef        = 0.130;
        m_EngineStartOK         = "Sedan_02_engine_start_SoundSet";
        m_EngineStartBattery    = "Sedan_02_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "Sedan_02_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "Sedan_02_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "offroad_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "offroad_door_open_SoundSet";
        m_CarDoorCloseSound     = "offroad_door_close_SoundSet";
        m_CarHornShortSoundName = "Sedan_02_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "Sedan_02_Horn_SoundSet";
        SetEnginePos("0 0.7 -1.7");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
SetActions() [1/2]
override void CarScript::SetActions () inline private
Definition at line 535 of file offroadhatchback.c.
    {
        super.SetActions();
        AddAction(ActionAnimateSeats);
    }
References AddAction().
Referenced by InitializeActions().
SetActions() [2/2]
override void CarScript::SetActions () inline private
Definition at line 374 of file truck_01_base.c.
    {
        super.SetActions();
        //AddAction( ActionAnimateCarSelection );
        AddAction( ActionSidePlateInteract );
        AddAction(ActionDetachFromTarget_SpecificSlot_WoodenLogs);
        AddAction(ActionDetachFromTarget_SpecificSlot_WoodenPlanks);
        AddAction(ActionDetachFromTarget_SpecificSlot_MetalSheets);
        AddAction(ActionDetachFromTarget_SpecificSlotsCategory_Barrel);
        AddAction(ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate);
    }
References ActionDetachFromTarget_SpecificSlot_MetalSheets(), ActionDetachFromTarget_SpecificSlot_WoodenLogs(), ActionDetachFromTarget_SpecificSlotsCategory_WoodenCrate(), and AddAction().
Truck_01_Base()
void CarScript::Truck_01_Base () inline private
Definition at line 7 of file truck_01_base.c.
    {
        m_dmgContactCoef        = 0.018;
        m_enginePtcPos          = "0 1.346 2.205";
        m_EngineStartOK         = "Truck_01_engine_start_SoundSet";
        m_EngineStartBattery    = "Truck_01_engine_failed_start_battery_SoundSet";
        m_EngineStartPlug       = "Truck_01_engine_failed_start_sparkplugs_SoundSet";
        m_EngineStartFuel       = "Truck_01_engine_failed_start_fuel_SoundSet";
        m_EngineStopFuel        = "Truck_01_engine_stop_fuel_SoundSet";
        m_CarDoorOpenSound      = "Truck_01_door_open_SoundSet";
        m_CarDoorCloseSound     = "Truck_01_door_close_SoundSet";
        m_CarHornShortSoundName = "Truck_01_Horn_Short_SoundSet";
        m_CarHornLongSoundName  = "Truck_01_Horn_SoundSet";
        SetEnginePos("0 1.4 2.25");
    }
References m_CarDoorCloseSound, m_CarDoorOpenSound, m_CarHornLongSoundName, m_CarHornShortSoundName, m_dmgContactCoef, m_enginePtcPos, m_EngineStartBattery, m_EngineStartFuel, m_EngineStartOK, m_EngineStartPlug, and m_EngineStopFuel.
Truck_02()
void CarScript::Truck_02 () inline private
Definition at line 7 of file truck_02.c.
    {
        m_dmgContactCoef = 0.018;
        m_enginePtcPos = "0 1.346 2.205";
    }
References m_dmgContactCoef, and m_enginePtcPos.
Van_01()
void CarScript::Van_01 () inline private
Definition at line 7 of file van_01.c.
    {
        m_dmgContactCoef = 0.070; //TODO::Set proper value
    }
References m_dmgContactCoef.
Member Data Documentation
m_UTSLEngine
protected ref UniversalTemperatureSourceLambdaEngine CarScript::m_UTSLEngine private
Definition at line 5 of file civiliansedan.c.
m_UTSource
protected ref UniversalTemperatureSource CarScript::m_UTSource private
Definition at line 3 of file civiliansedan.c.
m_UTSSettings
protected ref UniversalTemperatureSourceSettings CarScript::m_UTSSettings private
Definition at line 4 of file civiliansedan.c.