DayzKode: BiosLobbyService Class Reference
BiosLobbyService Class Reference
Private Member Functions
proto native void AddServerFavorite (string ipAddress, int port, int steamQueryPort)
proto native void GetCachedFavoriteServerInfo (array< ref CachedServerInfo > favServersInfoCache)
Get cached info about favorited servers (ONLY ON WINDOWS)
proto native void GetFavoriteServers (TStringArray favServers)
proto native EBiosError GetFirstServerWithEmptySlot (GetFirstServerWithEmptySlotInput inputValues)
First 1st free server.
proto native EBiosError GetServerModList (string serverId)
proto native EBiosError GetServers (GetServersInput inputValues)
Query game servers.
void OnDoneAsync (GetServersResult result_list, EBiosError error, string response)
Async callback for GetServers.
void OnGetFirstServerWithEmptySlot (GetFirstServerWithEmptySlotResult result_list, EBiosError error)
void OnServerModList (GetServerModListResult result_list, EBiosError error)
Async callback for GetServerModList.
proto native void RemoveServerFavorite (string ipAddress, int port, int steamQueryPort)
Detailed Description
Definition at line 479 of file bioslobbyservice.c.
Member Function Documentation
AddServerFavorite()
proto native void BiosLobbyService::AddServerFavorite (string ipAddress, int port, int steamQueryPort) private
Referenced by OnlineServices::SetServerFavorited().
GetCachedFavoriteServerInfo()
proto native void BiosLobbyService::GetCachedFavoriteServerInfo (array< ref CachedServerInfo > favServersInfoCache) private
Get cached info about favorited servers (ONLY ON WINDOWS)
Parameters
favServersInfoCache gets populated with data with format: key = Query End Point, value.param1 = Server Name, value.param2 = Connection Port
Referenced by OnlineServices::GetCachedFavServerInfo().
GetFavoriteServers()
proto native void BiosLobbyService::GetFavoriteServers (TStringArray favServers) private
Referenced by OnlineServices::GetFavoriteServers().
GetFirstServerWithEmptySlot()
proto native EBiosError BiosLobbyService::GetFirstServerWithEmptySlot (GetFirstServerWithEmptySlotInput inputValues) private
First 1st free server.
The async result is returned in the OnGetFirstServerWithEmptySlot callback.
Referenced by OnlineServices::AutoConnectToEmptyServer(), and OnlineServices::OnAutoConnectToEmptyServer().
GetServerModList()
proto native EBiosError BiosLobbyService::GetServerModList (string serverId) private
Async function to retrieve info about mods for specific server (only for PC)
Parameters
serverId have to be an id returned by callbacks issued by last call to GetServers if GetServers is used another time the id's must be upated
Referenced by OnlineServices::GetServerModList().
GetServers()
proto native EBiosError BiosLobbyService::GetServers (GetServersInput inputValues) private
Query game servers.
The async result is returned in the OnDoneAsync callback. Expected errors: BAD_PARAMETER - if atleast one of the permissions is not supported on the current platform, or atleast one of the input arrays is NULL.
Parameters
inputValues input structure
Referenced by OnlineServices::GetCurrentServerInfo(), and OnlineServices::LoadServers().
OnDoneAsync()
void BiosLobbyService::OnDoneAsync (GetServersResult result_list, EBiosError error, string response) inline private
Async callback for GetServers.
Parameters
result_list result object
error error indicating success or fail of the async operation.
response for debugging - this is the data returned by the server; or an empty string ;)
Definition at line 522 of file bioslobbyservice.c.
    {
        /*
        if (result_list.m_Results != null && result_list.m_Results.Count() > 0)
            Print(result_list.m_Results[0].m_TimeOfDay);
        */
        OnlineServices.OnLoadServersAsync( result_list, error, response );
    }
References OnlineServices::OnLoadServersAsync().
OnGetFirstServerWithEmptySlot()
void BiosLobbyService::OnGetFirstServerWithEmptySlot (GetFirstServerWithEmptySlotResult result_list, EBiosError error) inline private
Definition at line 531 of file bioslobbyservice.c.
    {
        OnlineServices.OnAutoConnectToEmptyServer( result_list, error );
    }
References OnlineServices::OnAutoConnectToEmptyServer().
OnServerModList()
void BiosLobbyService::OnServerModList (GetServerModListResult result_list, EBiosError error) inline private
Async callback for GetServerModList.
Definition at line 537 of file bioslobbyservice.c.
    {
        OnlineServices.OnGetServerModList( result_list, error );
    }
References OnlineServices::OnGetServerModList().
RemoveServerFavorite()
proto native void BiosLobbyService::RemoveServerFavorite (string ipAddress, int port, int steamQueryPort) private
Referenced by OnlineServices::SetServerFavorited().