DayzKode: BiosClientServices Class Reference
BiosClientServices Class Reference
BiosClientServices class provides individual online services.
Private Member Functions
private void BiosClientServices ()
proto native BiosLobbyService GetLobbyService ()
proto native BiosPackageService GetPackageService ()
proto native BiosPrivacyService GetPrivacyService ()
proto native BiosSessionService GetSessionService ()
proto native BiosSocialService GetSocialService ()
void ~BiosClientServices ()
Detailed Description
BiosClientServices class provides individual online services.
Bohemia interactive online services (Bios), Client services API. Use the individual Get methods to access individual service providers. Do not store references to individual service providers, use the Get methods instead. Temporary storage in a function body is fine as long as the owning BiosClientServices object is referenced. Do not attempt to construct this object. It is currently provided by the engine.
Definition at line 9 of file biosclientservices.c.
Constructor & Destructor Documentation
BiosClientServices()
private void BiosClientServices::BiosClientServices () inline private
Definition at line 11 of file biosclientservices.c.
{}
~BiosClientServices()
void BiosClientServices::~BiosClientServices () inline private
Definition at line 12 of file biosclientservices.c.
    {
    }
Member Function Documentation
GetLobbyService()
proto native BiosLobbyService BiosClientServices::GetLobbyService () private
Referenced by OnlineServices::AutoConnectToEmptyServer(), OnlineServices::GetCachedFavServerInfo(), OnlineServices::GetCurrentServerInfo(), OnlineServices::GetFavoriteServers(), OnlineServices::GetServerModList(), OnlineServices::LoadServers(), OnlineServices::OnAutoConnectToEmptyServer(), and OnlineServices::SetServerFavorited().
GetPackageService()
proto native BiosPackageService BiosClientServices::GetPackageService () private
Referenced by OnlineServices::CheckUpdate(), and OnlineServices::PromptUpdate().
GetPrivacyService()
proto native BiosPrivacyService BiosClientServices::GetPrivacyService () private
Referenced by OnlineServices::LoadMPPrivilege(), OnlineServices::LoadPermissions(), and OnlineServices::LoadVoicePrivilege().
GetSessionService()
proto native BiosSessionService BiosClientServices::GetSessionService () private
Referenced by OnlineServices::EnterGameplaySession(), OnlineServices::GetSession(), OnlineServices::GetSessionHandle(), OnlineServices::LeaveGameplaySession(), OnlineServices::SetGameplayActivity(), OnlineServices::SetMultiplayState(), OnlineServices::SetPendingInviteList(), OnlineServices::SetSessionHandle(), and OnlineServices::ShowInviteScreen().
GetSocialService()
proto native BiosSocialService BiosClientServices::GetSocialService () private
Referenced by OnlineServices::LoadFriends(), and OnlineServices::ShowUserProfile().