DayzKode: StaticGUIUtils Class Reference
StaticGUIUtils Class Reference
Static Private Member Functions
static string VerifyIconImageString (int imageset_group=IMAGESETGROUP_INVENTORY, string icon_name="")
Checks for improperly formated, legacy image names and corrects them to default format.
Static Private Attributes
static const int IMAGESETGROUP_INVENTORY = 0
Detailed Description
Definition at line 1 of file staticguiutils.c.
Member Function Documentation
VerifyIconImageString()
static string StaticGUIUtils::VerifyIconImageString (int imageset_group = IMAGESETGROUP_INVENTORY, string icon_name = "") inline static private
Checks for improperly formated, legacy image names and corrects them to default format.
Definition at line 7 of file staticguiutils.c.
    {
        if (icon_name == "")
        {
            return "set:dayz_inventory image:missing";
        }
        if ( !icon_name.Contains("image:") )
        {
            switch (imageset_group)
            {
                case IMAGESETGROUP_INVENTORY:
                    return "set:dayz_inventory image:" + icon_name;
            }
        }
        return icon_name;
    }
References IMAGESETGROUP_INVENTORY.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), and PlayerContainer::PlayerContainer().
Member Data Documentation
IMAGESETGROUP_INVENTORY
const int StaticGUIUtils::IMAGESETGROUP_INVENTORY = 0 static private
Definition at line 3 of file staticguiutils.c.
Referenced by AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), AttachmentCategoriesContainer::LoadAttachmentCategoriesIcon(), PlayerContainer::PlayerContainer(), and VerifyIconImageString().