DayzKode: CAContinuousEmptyMagazine Class Reference
CAContinuousEmptyMagazine Class Reference
Private Member Functions
void CAContinuousEmptyMagazine (float eject_time)
void CalcAndSetQuantity (ActionData action_data)
override int Cancel (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_SpentQuantity
protected ref Param1< float > m_SpentUnits
protected float m_TargetUnits
protected float m_Time
protected float m_TimeToEjectOneBullet
Detailed Description
Definition at line 1 of file cacontinuousemptymagazine.c.
Constructor & Destructor Documentation
CAContinuousEmptyMagazine()
void CAContinuousEmptyMagazine::CAContinuousEmptyMagazine (float eject_time) inline private
Definition at line 9 of file cacontinuousemptymagazine.c.
    {
        m_TimeToEjectOneBullet = eject_time;
        m_Time = 0;
    }
References m_Time, and m_TimeToEjectOneBullet.
Member Function Documentation
CalcAndSetQuantity()
void CAContinuousEmptyMagazine::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 83 of file cacontinuousemptymagazine.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( action_data.m_MainItem )
            {
                Magazine itm;
                Class.CastTo(itm, action_data.m_MainItem);
                if ( m_SpentUnits )
                {
                    m_SpentUnits.param1 = m_SpentQuantity;
                    SetACData(m_SpentUnits);
                }
                itm.ServerAddAmmoCount(-m_SpentQuantity);
            }
        }
    }
References Class::CastTo(), GetGame(), ActionData::m_MainItem, m_SpentQuantity, m_SpentUnits, and CABase::SetACData().
Cancel()
override int CAContinuousEmptyMagazine::Cancel (ActionData action_data) inline private
Definition at line 64 of file cacontinuousemptymagazine.c.
    {
        if ( !action_data.m_Player || !action_data.m_MainItem )
        {
            return UA_ERROR;
        }
        CalcAndSetQuantity( action_data );
        return UA_CANCEL;
    }
References CalcAndSetQuantity(), ActionData::m_MainItem, ActionData::m_Player, UA_CANCEL, and UA_ERROR.
Execute()
override int CAContinuousEmptyMagazine::Execute (ActionData action_data) inline private
Definition at line 32 of file cacontinuousemptymagazine.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        if ( m_TargetUnits == 0 )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_SpentQuantity < m_TargetUnits )
            {
                m_Time += action_data.m_Player.GetDeltaT();
                if ( m_Time > m_TimeToEjectOneBullet )
                {
                    m_Time = 0;
                    m_SpentQuantity += 1;
                }
                return UA_PROCESSING;
            }
            else
            {
                CalcAndSetQuantity( action_data );
                OnCompletePogress(action_data);
                return UA_FINISHED;
            }
        }
    }
References CalcAndSetQuantity(), ActionData::m_Player, m_SpentQuantity, m_TargetUnits, m_Time, m_TimeToEjectOneBullet, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousEmptyMagazine::GetProgress () inline private
Definition at line 75 of file cacontinuousemptymagazine.c.
    {
        //float progress = m_SpentQuantity/m_TargetUnits;
        return m_SpentQuantity/m_TargetUnits;
    }
References m_SpentQuantity, and m_TargetUnits.
Setup()
override void CAContinuousEmptyMagazine::Setup (ActionData action_data) inline private
Definition at line 15 of file cacontinuousemptymagazine.c.
    {
        if ( !m_SpentUnits )
        {
            m_SpentUnits = new Param1<float>(0);
        }
        else
        {
            m_SpentUnits.param1 = 0;
        }
        m_SpentQuantity = 0;
        Magazine itm;
        Class.CastTo(itm, action_data.m_MainItem);
        m_TargetUnits = itm.GetAmmoCount();
    }
References Class::CastTo(), ActionData::m_MainItem, m_SpentQuantity, m_SpentUnits, and m_TargetUnits.
Member Data Documentation
m_SpentQuantity
protected float CAContinuousEmptyMagazine::m_SpentQuantity private
Definition at line 4 of file cacontinuousemptymagazine.c.
Referenced by CalcAndSetQuantity(), Execute(), GetProgress(), and Setup().
m_SpentUnits
protected ref Param1<float> CAContinuousEmptyMagazine::m_SpentUnits private
Definition at line 7 of file cacontinuousemptymagazine.c.
Referenced by CalcAndSetQuantity(), and Setup().
m_TargetUnits
protected float CAContinuousEmptyMagazine::m_TargetUnits private
Definition at line 3 of file cacontinuousemptymagazine.c.
Referenced by Execute(), GetProgress(), and Setup().
m_Time
protected float CAContinuousEmptyMagazine::m_Time private
Definition at line 5 of file cacontinuousemptymagazine.c.
Referenced by CAContinuousEmptyMagazine(), and Execute().
m_TimeToEjectOneBullet
protected float CAContinuousEmptyMagazine::m_TimeToEjectOneBullet private
Definition at line 6 of file cacontinuousemptymagazine.c.
Referenced by CAContinuousEmptyMagazine(), and Execute().