DayzKode: ContaminatedArea_Dynamic Class Reference
ContaminatedArea_Dynamic Class Reference
Private Member Functions
void ContaminatedArea_Dynamic ()
override void CreateTrigger (vector pos, int radius)
override void EEDelete (EntityAI parent)
override void EEInit ()
override void EEOnCECreate ()
float GetFinishDecayLifetime ()
float GetRemainingTime ()
float GetStartDecayLifetime ()
override void InitZone ()
override void InitZoneClient ()
override void InitZoneServer ()
override void OnParticleAllocation (ParticleManager pm, array< ParticleSource > particles)
override void OnVariablesSynchronized ()
void PlayExplosionLight ()
void PlayFlareVFX ()
void PlayFX ()
void SetDecayState (int newState)
void SpawnItems ()
override void Tick ()
Private Attributes
const int AIRBORNE_EXPLOSION_DELAY = 20
const float AIRBORNE_FX_OFFSET = 50
const int AREA_SETUP_DELAY = 10
const float ARTILLERY_SHELL_SPEED = 100
const int DECAY_END_PART_BIRTH_RATE = 1
const float DECAY_END_PART_SIZE = 17
const int DECAY_START_PART_BIRTH_RATE = 1
const float DECAY_START_PART_SIZE = 32
const float FINISH_DECAY_LIFETIME = 300
protected int m_DecayState = eAreaDecayStage.INIT
protected FlareLight m_FlareLight
protected ref Timer m_FXTimer
protected vector m_OffsetPos
protected ShellLight m_ShellLight
protected ref Timer m_StartupTimer
const ref array< int > SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)}
const ref array< float > SPAWN_ITEM_RAD_MAX = {15}
const ref array< float > SPAWN_ITEM_RAD_MIN = {5}
const ref array< string > SPAWN_ITEM_TYPE = {"Grenade_ChemGas"}
const float START_DECAY_LIFETIME = 900
Detailed Description
Definition at line 31 of file contaminatedarea_dynamic.c.
Constructor & Destructor Documentation
ContaminatedArea_Dynamic()
void ContaminatedArea_Dynamic::ContaminatedArea_Dynamic () inline private
Definition at line 61 of file contaminatedarea_dynamic.c.
    {
        RegisterNetSyncVariableInt("m_DecayState");
    }
Member Function Documentation
CreateTrigger()
override void ContaminatedArea_Dynamic::CreateTrigger (vector pos, int radius) inline private
Definition at line 289 of file contaminatedarea_dynamic.c.
    {
        super.CreateTrigger( pos, radius );
        // This handles the specific case of dynamic triggers as some additionnal parameters are present
        ContaminatedTrigger_Dynamic dynaTrigger = ContaminatedTrigger_Dynamic.Cast( m_Trigger );
        if ( dynaTrigger )
        {
            dynaTrigger.SetLocalEffects( m_AroundParticleID, m_TinyParticleID, m_PPERequesterIdx );
            dynaTrigger.SetAreaState( m_DecayState );
        }
    }
References ContaminatedTrigger_Dynamic(), EffectArea::m_AroundParticleID, m_DecayState, EffectArea::m_PPERequesterIdx, EffectArea::m_TinyParticleID, and EffectArea::m_Trigger.
EEDelete()
override void ContaminatedArea_Dynamic::EEDelete (EntityAI parent) inline private
Definition at line 341 of file contaminatedarea_dynamic.c.
    {
        super.EEDelete( parent );
    }
EEInit()
override void ContaminatedArea_Dynamic::EEInit () inline private
Definition at line 170 of file contaminatedarea_dynamic.c.
    {
        // We make sure we have the particle array
        if ( !m_ToxicClouds )
            m_ToxicClouds = new array<Particle>;
        // We set the values for dynamic area as these are not set through JSON and are standardized
        m_Name = "Default Dynamic";
        m_Radius = 120;
        m_PositiveHeight = 7;
        m_NegativeHeight = 10;
        m_InnerRings = 1;
        m_InnerSpacing = 40;
        m_OuterSpacing = 30;
        m_OuterRingOffset = 0;
        m_Type = eZoneType.DYNAMIC;
        m_TriggerType = "ContaminatedTrigger_Dynamic";
        SetSynchDirty();
        #ifdef DEVELOPER
        // Debugs when placing entity by hand using internal tools
        /*if ( GetGame().IsServer() && !GetGame().IsMultiplayer() )
        {
            Debug.Log("YOU CAN IGNORE THE FOLLOWING DUMP");
            InitZone();
            Debug.Log("YOU CAN USE FOLLOWING DATA PROPERLY");
        }*/
        #endif
        m_OffsetPos = GetPosition();
        m_OffsetPos[1] = m_OffsetPos[1] + AIRBORNE_FX_OFFSET;
        // If a player arrives slightly later during the creation process we check if playing the flare FX is relevant
        if ( m_DecayState == eAreaDecayStage.INIT )
            PlayFlareVFX();
        if ( m_DecayState == eAreaDecayStage.LIVE )
            InitZone(); // If it has already been created, we simply do the normal setup, no cool effects, force the LIVE state
        else if ( GetGame().IsClient() && m_DecayState > eAreaDecayStage.LIVE )
            InitZoneClient(); // Same as before but without state forcing
        super.EEInit();
    }
References AIRBORNE_FX_OFFSET, GetGame(), GetPosition, InitZone(), InitZoneClient(), m_DecayState, EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_Name, EffectArea::m_NegativeHeight, m_OffsetPos, EffectArea::m_OuterRingOffset, EffectArea::m_OuterSpacing, EffectArea::m_PositiveHeight, EffectArea::m_Radius, EffectArea::m_ToxicClouds, EffectArea::m_TriggerType, EffectArea::m_Type, and PlayFlareVFX().
EEOnCECreate()
override void ContaminatedArea_Dynamic::EEOnCECreate () inline private
Definition at line 66 of file contaminatedarea_dynamic.c.
    {
        // We get the PPE index for future usage and synchronization ( we must do it here for dynamic as it is not read through file )
        if ( GetGame().IsServer() )
            m_PPERequesterIdx = GetRequesterIndex(m_PPERequesterType);
        SetSynchDirty();
        // If this is the first initialization, we delay it in order to play cool effects
        if ( m_DecayState == eAreaDecayStage.INIT )
        {
            vector areaPos = GetPosition();
            m_OffsetPos = areaPos;
            m_OffsetPos[1] = m_OffsetPos[1] + AIRBORNE_FX_OFFSET;
            // play artillery sound, sent to be played for everyone on server
            array<vector> artilleryPoints = GetGame().GetMission().GetWorldData().GetArtyFiringPos();
            vector closestPoint = areaPos;
            int dist = 0;
            int temp;
            int index = 0;
            for ( int i = 0; i < artilleryPoints.Count(); i++ )
            {
                temp = vector.DistanceSq( artilleryPoints.Get( i ), areaPos );
                if ( temp < dist || dist == 0 )
                {
                    dist = temp;
                    index = i;
                }
            }
            closestPoint = artilleryPoints.Get( index );
            // We calculate the delay depending on distance from firing position to simulate shell travel time
            float delay = vector.Distance( closestPoint, areaPos );
            delay = delay / ARTILLERY_SHELL_SPEED;
            delay += AIRBORNE_EXPLOSION_DELAY; // We add the base, minimum time ( no area can start before this delay )
            Param3<vector, vector, float> pos; // The value to be sent through RPC
            array<ref Param> params; // The RPC params
            // We prepare to send the message
            pos = new Param3<vector, vector, float>( closestPoint, areaPos, delay );
            params = new array<ref Param>;
            // We send the message with this set of coords
            params.Insert( pos );
            GetGame().RPC( null, ERPCs.RPC_SOUND_ARTILLERY_SINGLE, params, true );
            m_FXTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
            m_FXTimer.Run( delay, this, "PlayFX" );
            delay += AREA_SETUP_DELAY; // We have an additional delay between shell detonation and finalization of area creation
            // setup zone
            m_StartupTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
            m_StartupTimer.Run( delay, this, "InitZone" );
        }
    }
References AIRBORNE_EXPLOSION_DELAY, AIRBORNE_FX_OFFSET, AREA_SETUP_DELAY, ARTILLERY_SHELL_SPEED, CALL_CATEGORY_GAMEPLAY, vector::Distance(), vector::DistanceSq(), WorldData::GetArtyFiringPos(), GetGame(), CGame::GetMission(), GetPosition, EffectArea::GetRequesterIndex(), Mission::GetWorldData(), m_DecayState, m_FXTimer, m_OffsetPos, EffectArea::m_PPERequesterIdx, EffectArea::m_PPERequesterType, m_StartupTimer, and CGame::RPC().
GetFinishDecayLifetime()
float ContaminatedArea_Dynamic::GetFinishDecayLifetime () inline private
Definition at line 135 of file contaminatedarea_dynamic.c.
    {
        return FINISH_DECAY_LIFETIME;
    }
References FINISH_DECAY_LIFETIME.
Referenced by Tick().
GetRemainingTime()
float ContaminatedArea_Dynamic::GetRemainingTime () inline private
Definition at line 125 of file contaminatedarea_dynamic.c.
    {
        return GetLifetime();
    }
Referenced by Tick().
GetStartDecayLifetime()
float ContaminatedArea_Dynamic::GetStartDecayLifetime () inline private
Definition at line 130 of file contaminatedarea_dynamic.c.
    {
        return START_DECAY_LIFETIME;
    }
References START_DECAY_LIFETIME.
Referenced by Tick().
InitZone()
override void ContaminatedArea_Dynamic::InitZone () inline private
Definition at line 216 of file contaminatedarea_dynamic.c.
    {
        m_DecayState = eAreaDecayStage.LIVE;
        SetSynchDirty();
        super.InitZone();
    }
References m_DecayState.
Referenced by EEInit().
InitZoneClient()
override void ContaminatedArea_Dynamic::InitZoneClient () inline private
Definition at line 256 of file contaminatedarea_dynamic.c.
    {
        super.InitZoneClient();
        if ( !m_ToxicClouds )
            m_ToxicClouds = new array<Particle>;
        // We spawn VFX on client
        PlaceParticles( GetWorldPosition(), m_Radius, m_InnerRings, m_InnerSpacing, m_OuterRingToggle, m_OuterSpacing, m_OuterRingOffset, m_ParticleID );
    }
References GetWorldPosition(), EffectArea::m_InnerRings, EffectArea::m_InnerSpacing, EffectArea::m_OuterRingOffset, EffectArea::m_OuterRingToggle, EffectArea::m_OuterSpacing, EffectArea::m_ParticleID, EffectArea::m_Radius, EffectArea::m_ToxicClouds, and EffectArea::PlaceParticles().
Referenced by EEInit(), and OnVariablesSynchronized().
InitZoneServer()
override void ContaminatedArea_Dynamic::InitZoneServer () inline private
Definition at line 224 of file contaminatedarea_dynamic.c.
    {
        super.InitZoneServer();
        SpawnItems();
        // We create the trigger on server
        if ( m_TriggerType != "" )
            CreateTrigger( m_Position, m_Radius );
    }
References CreateTrigger(), EffectArea::m_Position, EffectArea::m_Radius, EffectArea::m_TriggerType, and SpawnItems().
OnParticleAllocation()
override void ContaminatedArea_Dynamic::OnParticleAllocation (ParticleManager pm, array< ParticleSource > particles) inline private
Definition at line 267 of file contaminatedarea_dynamic.c.
    {
        super.OnParticleAllocation(pm, particles);
        if ( m_DecayState > eAreaDecayStage.LIVE )
        {
            foreach ( ParticleSource p : particles )
            {
                if ( m_DecayState == eAreaDecayStage.DECAY_END )
                {
                    p.SetParameter( 0, EmitorParam.BIRTH_RATE, DECAY_END_PART_BIRTH_RATE );
                    p.SetParameter( 0, EmitorParam.SIZE, DECAY_END_PART_SIZE );
                }
                else
                {
                    p.SetParameter( 0, EmitorParam.BIRTH_RATE, DECAY_START_PART_BIRTH_RATE );
                    p.SetParameter( 0, EmitorParam.SIZE, DECAY_START_PART_SIZE );
                }
            }
        }
    }
References DECAY_END_PART_BIRTH_RATE, DECAY_END_PART_SIZE, DECAY_START_PART_BIRTH_RATE, DECAY_START_PART_SIZE, and m_DecayState.
OnVariablesSynchronized()
override void ContaminatedArea_Dynamic::OnVariablesSynchronized () inline private
Definition at line 346 of file contaminatedarea_dynamic.c.
    {
        super.OnVariablesSynchronized();
        if ( !m_ToxicClouds )
            m_ToxicClouds = new array<Particle>;
        switch ( m_DecayState )
        {
            case eAreaDecayStage.START:
                PlayExplosionLight();
            break;
            case eAreaDecayStage.LIVE:
                InitZoneClient();
            break;
            case eAreaDecayStage.DECAY_START:
            {
                // We go through all the particles bound to this area and update relevant parameters
                //Debug.Log("We start decay");
                foreach ( Particle p : m_ToxicClouds )
                {
                    p.SetParameter( 0, EmitorParam.BIRTH_RATE, DECAY_START_PART_BIRTH_RATE );
                    p.SetParameter( 0, EmitorParam.SIZE, DECAY_START_PART_SIZE );
                }
                break;
            }
            case eAreaDecayStage.DECAY_END:
            {
                // We go through all the particles bound to this area and update relevant parameters
                //Debug.Log("We finish decay");
                foreach ( Particle prt : m_ToxicClouds )
                {
                    prt.SetParameter( 0, EmitorParam.BIRTH_RATE, DECAY_END_PART_BIRTH_RATE );
                    prt.SetParameter( 0, EmitorParam.SIZE, DECAY_END_PART_SIZE );
                }
                break;
            }
            default:
            break;
        }
    }
References DECAY_END_PART_BIRTH_RATE, DECAY_END_PART_SIZE, DECAY_START_PART_BIRTH_RATE, DECAY_START_PART_SIZE, InitZoneClient(), m_DecayState, EffectArea::m_ToxicClouds, and PlayExplosionLight().
PlayExplosionLight()
void ContaminatedArea_Dynamic::PlayExplosionLight () inline private
Definition at line 324 of file contaminatedarea_dynamic.c.
    {
        m_ShellLight = ShellLight.Cast( ScriptedLightBase.CreateLight( ShellLight, m_OffsetPos ) );
    }
References m_OffsetPos, m_ShellLight, and ShellLight().
Referenced by OnVariablesSynchronized().
PlayFlareVFX()
void ContaminatedArea_Dynamic::PlayFlareVFX () inline private
Definition at line 329 of file contaminatedarea_dynamic.c.
    {
        if ( GetGame().IsClient() || ( GetGame().IsServer() && !GetGame().IsMultiplayer() ) )
        {
            // We spawn locally the dummy object which will be used to move and manage the particle
            DynamicArea_Flare dummy = DynamicArea_Flare.Cast( GetGame().CreateObjectEx( "DynamicArea_Flare", m_OffsetPos, ECE_SETUP | ECE_LOCAL ) );
            // We add some light to reinforce the effect
            m_FlareLight = FlareLightContamination.Cast(ScriptedLightBase.CreateLight( FlareLightContamination, m_OffsetPos ));
        }
    }
References ECE_LOCAL, ECE_SETUP, GetGame(), m_FlareLight, and m_OffsetPos.
Referenced by EEInit().
PlayFX()
void ContaminatedArea_Dynamic::PlayFX () inline private
Definition at line 302 of file contaminatedarea_dynamic.c.
    {
        if ( GetGame().IsServer() )
        {
            Param1<vector> pos; // The value to be sent through RPC
            array<ref Param> params; // The RPC params
            // We prepare to send the message
            pos = new Param1<vector>( vector.Zero );
            params = new array<ref Param>;
            // We send the message with this set of coords
            pos.param1 = m_OffsetPos;
            params.Insert( pos );
            GetGame().RPC( null, ERPCs.RPC_SOUND_CONTAMINATION, params, true );
            // We go to the next stage
            m_DecayState = eAreaDecayStage.START;
            SetSynchDirty();
        }
    }
References GetGame(), m_DecayState, m_OffsetPos, CGame::RPC(), and vector::Zero.
SetDecayState()
void ContaminatedArea_Dynamic::SetDecayState (int newState) inline private
Definition at line 156 of file contaminatedarea_dynamic.c.
    {
        if (m_DecayState != newState)
        {
            m_DecayState = newState;
            // We update the trigger state values as we also want to update player bound effects
            if ( m_Trigger )
                ContaminatedTrigger_Dynamic.Cast( m_Trigger ).SetAreaState( m_DecayState );
            SetSynchDirty();
        }
    }
References ContaminatedTrigger_Dynamic(), m_DecayState, and EffectArea::m_Trigger.
Referenced by Tick().
SpawnItems()
void ContaminatedArea_Dynamic::SpawnItems () inline private
Definition at line 234 of file contaminatedarea_dynamic.c.
    {
        //Print("---------============ Spawning items at pos:"+m_Position);
        foreach (int j, string type:SPAWN_ITEM_TYPE)
        {
            //Print("----------------------------------");
            for (int i = 0; i < SPAWN_ITEM_COUNT[j]; i++)
            {
                vector randomDir2d = vector.RandomDir2D();
                float randomDist = Math.RandomFloatInclusive(SPAWN_ITEM_RAD_MIN[j],SPAWN_ITEM_RAD_MAX[j]);
                vector spawnPos = m_Position + (randomDir2d * randomDist);
                InventoryLocation il = new InventoryLocation;
                vector mat[4];
                Math3D.MatrixIdentity4(mat);
                mat[3] = spawnPos;
                il.SetGround(NULL, mat);
                //Print("Spawning item:"+ type + " at position:" + il.GetPos());
                GetGame().CreateObjectEx(type, il.GetPos(), ECE_PLACE_ON_SURFACE);
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), EffectArea::m_Position, Math3D::MatrixIdentity4(), vector::RandomDir2D(), Math::RandomFloatInclusive(), SPAWN_ITEM_COUNT, SPAWN_ITEM_RAD_MAX, SPAWN_ITEM_RAD_MIN, and SPAWN_ITEM_TYPE.
Referenced by InitZoneServer().
Tick()
override void ContaminatedArea_Dynamic::Tick () inline private
Definition at line 140 of file contaminatedarea_dynamic.c.
    {
        if ( GetRemainingTime() < GetFinishDecayLifetime() )
        {
            // The second state of decay, further reduction of particle density and size
            SetDecayState( eAreaDecayStage.DECAY_END );
        }
        else if ( GetRemainingTime() < GetStartDecayLifetime() )
        {
            // The first state of decay, slight reduction in particle density and size
            SetDecayState( eAreaDecayStage.DECAY_START );
        }
    }
References GetFinishDecayLifetime(), GetRemainingTime(), GetStartDecayLifetime(), and SetDecayState().
Member Data Documentation
AIRBORNE_EXPLOSION_DELAY
const int ContaminatedArea_Dynamic::AIRBORNE_EXPLOSION_DELAY = 20 private
Definition at line 41 of file contaminatedarea_dynamic.c.
Referenced by EEOnCECreate().
AIRBORNE_FX_OFFSET
const float ContaminatedArea_Dynamic::AIRBORNE_FX_OFFSET = 50 private
Definition at line 43 of file contaminatedarea_dynamic.c.
Referenced by EEInit(), and EEOnCECreate().
AREA_SETUP_DELAY
const int ContaminatedArea_Dynamic::AREA_SETUP_DELAY = 10 private
Definition at line 42 of file contaminatedarea_dynamic.c.
Referenced by EEOnCECreate().
ARTILLERY_SHELL_SPEED
const float ContaminatedArea_Dynamic::ARTILLERY_SHELL_SPEED = 100 private
Definition at line 44 of file contaminatedarea_dynamic.c.
Referenced by EEOnCECreate().
DECAY_END_PART_BIRTH_RATE
const int ContaminatedArea_Dynamic::DECAY_END_PART_BIRTH_RATE = 1 private
Definition at line 50 of file contaminatedarea_dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_END_PART_SIZE
const float ContaminatedArea_Dynamic::DECAY_END_PART_SIZE = 17 private
Definition at line 49 of file contaminatedarea_dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_START_PART_BIRTH_RATE
const int ContaminatedArea_Dynamic::DECAY_START_PART_BIRTH_RATE = 1 private
Definition at line 48 of file contaminatedarea_dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
DECAY_START_PART_SIZE
const float ContaminatedArea_Dynamic::DECAY_START_PART_SIZE = 32 private
Definition at line 47 of file contaminatedarea_dynamic.c.
Referenced by OnParticleAllocation(), and OnVariablesSynchronized().
FINISH_DECAY_LIFETIME
const float ContaminatedArea_Dynamic::FINISH_DECAY_LIFETIME = 300 private
Definition at line 52 of file contaminatedarea_dynamic.c.
Referenced by GetFinishDecayLifetime().
m_DecayState
protected int ContaminatedArea_Dynamic::m_DecayState = eAreaDecayStage.INIT private
Definition at line 38 of file contaminatedarea_dynamic.c.
Referenced by CreateTrigger(), EEInit(), EEOnCECreate(), InitZone(), OnParticleAllocation(), OnVariablesSynchronized(), PlayFX(), and SetDecayState().
m_FlareLight
protected FlareLight ContaminatedArea_Dynamic::m_FlareLight private
Definition at line 35 of file contaminatedarea_dynamic.c.
Referenced by PlayFlareVFX().
m_FXTimer
protected ref Timer ContaminatedArea_Dynamic::m_FXTimer private
Definition at line 34 of file contaminatedarea_dynamic.c.
Referenced by EEOnCECreate().
m_OffsetPos
protected vector ContaminatedArea_Dynamic::m_OffsetPos private
Definition at line 37 of file contaminatedarea_dynamic.c.
Referenced by EEInit(), EEOnCECreate(), PlayExplosionLight(), PlayFlareVFX(), and PlayFX().
m_ShellLight
protected ShellLight ContaminatedArea_Dynamic::m_ShellLight private
Definition at line 36 of file contaminatedarea_dynamic.c.
Referenced by PlayExplosionLight().
m_StartupTimer
protected ref Timer ContaminatedArea_Dynamic::m_StartupTimer private
Definition at line 33 of file contaminatedarea_dynamic.c.
Referenced by EEOnCECreate().
SPAWN_ITEM_COUNT
const ref array<int> ContaminatedArea_Dynamic::SPAWN_ITEM_COUNT = {Math.RandomIntInclusive(2,5)} private
Definition at line 56 of file contaminatedarea_dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MAX
const ref array<float> ContaminatedArea_Dynamic::SPAWN_ITEM_RAD_MAX = {15} private
Definition at line 58 of file contaminatedarea_dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_RAD_MIN
const ref array<float> ContaminatedArea_Dynamic::SPAWN_ITEM_RAD_MIN = {5} private
Definition at line 57 of file contaminatedarea_dynamic.c.
Referenced by SpawnItems().
SPAWN_ITEM_TYPE
const ref array<string> ContaminatedArea_Dynamic::SPAWN_ITEM_TYPE = {"Grenade_ChemGas"} private
Definition at line 55 of file contaminatedarea_dynamic.c.
Referenced by SpawnItems().
START_DECAY_LIFETIME
const float ContaminatedArea_Dynamic::START_DECAY_LIFETIME = 900 private
Definition at line 51 of file contaminatedarea_dynamic.c.
Referenced by GetStartDecayLifetime().