DayzKode: Hologram Class Reference
Hologram Class Reference
Private Member Functions
void AddProjectionRotation (float addition)
vector AlignProjectionOnTerrain (float timeslice)
void CheckPowerSource ()
vector CorrectForWatchtower (int contactComponent, vector contactPos, PlayerBase player, Object hitObject)
string CorrectMaterialPathName ()
void CreateTrigger ()
void EvaluateCollision (ItemBase action_item=null)
protected vector GetCollisionBoxSize (vector min_max[2])
vector GetDefaultOrientation ()
int GetHiddenSelection (string selection)
vector GetLeftCloseProjectionVector ()
vector GetLeftFarProjectionVector ()
EntityAI GetParentEntity ()
protected void GetProjectionCollisionBox (out vector min_max[2])
float GetProjectionDiameter ()
EntityAI GetProjectionEntity ()
protected vector GetProjectionEntityPosition (PlayerBase player)
string GetProjectionName (ItemBase item)
vector GetProjectionOrientation ()
vector GetProjectionPosition ()
float GetProjectionRadius ()
vector GetProjectionRotation ()
vector GetRightCloseProjectionVector ()
vector GetRightFarProjectionVector ()
bool GetUpdatePosition ()
bool HeightPlacementCheck ()
Checks height relative to player's position.
vector HideWhenClose (vector pos)
void Hologram (PlayerBase player, vector pos, ItemBase item)
bool IsBaseFlat (vector contact_pos_left_close, vector contact_pos_right_close, vector contact_pos_left_far, vector contact_pos_right_far)
bool IsBaseIntact (Object under_left_close, Object under_right_close, Object under_left_far, Object under_right_far)
bool IsBaseStatic (Object objectToCheck)
bool IsBaseViable ()
bool IsBehindObstacle ()
DEPRECATED.
bool IsClippingRoof ()
bool IsColliding ()
bool IsCollidingAngle ()
bool IsCollidingBBox (ItemBase action_item=null)
bool IsCollidingGPlot ()
bool IsCollidingPlayer ()
bool IsCollidingZeroPos ()
bool IsFenceOrWatchtowerKit ()
bool IsFloating ()
bool IsHidden ()
bool IsInTerrain ()
bool IsObjectStatic (Object obj)
bool IsPlacementPermitted ()
Checks if the item can be legally placed (usually checked by action as well)
bool IsProjectionTrap ()
bool IsSurfaceSea (vector position)
bool IsSurfaceWater (vector position)
bool IsUnderwater ()
EntityAI PlaceEntity (EntityAI entity_for_placing)
string ProjectionBasedOnParent ()
void RefreshTrigger ()
void RefreshVisual ()
void SetAnimations ()
protected bool SetHologramPosition (vector startPosition, float minProjectionDistance, float maxProjectionDistance, inout vector contactPosition)
Sets hologram position based on player and projection distance.
void SetIsColliding (bool is_colliding)
void SetIsCollidingGPlot (bool is_colliding_gplot)
void SetIsCollidingPlayer (bool is_colliding)
void SetIsFloating (bool is_floating)
void SetIsHidden (bool is_hidden)
vector SetOnGround (vector position)
void SetProjectionEntity (EntityAI projection)
void SetProjectionOrientation (vector orientation)
void SetProjectionPosition (vector position)
void SetSelectionToRefresh (array< string > selection)
void SetSelectionToRefresh (string selection)
void SetUpdatePosition (bool state)
vector SmoothProjectionMovement (vector y_p_r, float timeslice)
void SubtractProjectionRotation (float subtraction)
void UpdateHologram (float timeslice)
void UpdateSelections ()
void ~Hologram ()
Static Private Member Functions
static bool DoesHaveProjection (ItemBase item)
DEPRECATED.
Private Attributes
protected const string ANIMATION_INVENTORY = "Inventory"
protected const string ANIMATION_PLACING = "Placing"
protected const float DISTANCE_SMALL_PROJECTION = 1
protected const float LARGE_PROJECTION_DISTANCE_LIMIT = 6
Deprecated.
protected const float LOOKING_TO_SKY = 0.75
protected bool m_AlignToTerrain
protected int m_ContactComponent
protected vector m_ContactDir
protected vector m_DefaultOrientation
protected vector m_FromAdjusted
protected bool m_IsColliding
protected bool m_IsCollidingGPlot
protected bool m_IsCollidingPlayer
protected bool m_IsFloating
protected bool m_IsHidden
protected bool m_IsSlope
protected ItemBase m_Parent
protected PlayerBase m_Player
protected EntityAI m_Projection
protected ProjectionTrigger m_ProjectionTrigger
protected string m_ProjectionTypename
protected vector m_Rotation
protected ref set< string > m_SelectionsToRefresh = new set<string>
protected float m_SlopeTolerance
protected bool m_UpdatePosition
protected vector m_y_p_r_previous
protected vector m_YawPitchRollLimit
protected const float PROJECTION_TRANSITION_MAX = 0.25
protected const float PROJECTION_TRANSITION_MIN = 1
protected const string SELECTION_INVENTORY = "inventory"
protected const string SELECTION_PLACING = "placing"
protected const float SMALL_PROJECTION_GROUND = 2
protected const float SMALL_PROJECTION_RADIUS = 1
protected const int SPAWN_FLAGS = ECE_LOCAL
protected const string SUFFIX_MATERIAL_DEPLOYABLE = "_deployable.rvmat"
protected const string SUFFIX_MATERIAL_POWERED = "_powered.rvmat"
protected const string SUFFIX_MATERIAL_UNDEPLOYABLE = "_undeployable.rvmat"
Static Private Attributes
static const float DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF = 1.5
static const protected ref array< string > m_WatchtowerBlockedComponentNames = new array<string>
static const protected ref array< string > m_WatchtowerIgnoreComponentNames = new array<string>
Detailed Description
Definition at line 1 of file hologram.c.
Constructor & Destructor Documentation
Hologram()
void Hologram::Hologram (PlayerBase player, vector pos, ItemBase item) inline private
Definition at line 60 of file hologram.c.
    {
        m_Player = player;
        m_Parent = item;
        m_Projection = NULL;
        m_ProjectionTrigger = NULL;
        m_UpdatePosition = true;
        m_Rotation = "0 0 0";
        m_ContactComponent = -1;
        m_FromAdjusted = "0 0 0";
        // If the static names are empty, generate the needed names
        // Refer to their definitions to see why these are required
        if (m_WatchtowerIgnoreComponentNames.Count() == 0)
        {
            string baseStringBegin = Watchtower.BASE_VIEW_NAME;
            string baseIgnoreStringEnd = Watchtower.BASE_WALL_NAME;
            int floors = Watchtower.MAX_WATCHTOWER_FLOORS;
            int walls = Watchtower.MAX_WATCHTOWER_WALLS;
            string compName;
            for (int i = 1; i < floors + 1; ++i)
            {
                compName = baseStringBegin + i.ToString();
                for (int j = 1; j < walls + 1; ++j)
                    m_WatchtowerIgnoreComponentNames.Insert(compName + baseIgnoreStringEnd + j.ToString());
                if (i != 1)
                    m_WatchtowerBlockedComponentNames.Insert(compName);
                else
                    m_WatchtowerIgnoreComponentNames.Insert(compName);
            }
        }
        string configPathProjectionTypename = string.Format("CfgVehicles %1 projectionTypename", m_Parent.GetType());
        if (GetGame().ConfigIsExisting(configPathProjectionTypename))
        {
            m_ProjectionTypename = GetGame().ConfigGetTextOut(configPathProjectionTypename);
        }
        EntityAI projectionEntity;
        if (GetGame().IsMultiplayer() && GetGame().IsServer())
        {
            projectionEntity = EntityAI.Cast(GetGame().CreateObjectEx(ProjectionBasedOnParent(), pos, ECE_PLACE_ON_SURFACE));
            projectionEntity.SetAllowDamage(false);
            SetProjectionEntity(projectionEntity);
            SetAnimations();
        }
        else
        {
            projectionEntity = EntityAI.Cast(GetGame().CreateObjectEx(ProjectionBasedOnParent(), pos, ECE_TRACE|ECE_LOCAL));
            if (projectionEntity == null)
            {
                ErrorEx(string.Format("Cannot create hologram entity from config class %1", ProjectionBasedOnParent()), ErrorExSeverity.WARNING);
                return;
            }
            SetProjectionEntity(projectionEntity);
            SetAnimations();
            CreateTrigger();
            RefreshTrigger();
        }
        if (ItemBase.Cast(projectionEntity))
        {
            ItemBase.Cast(GetProjectionEntity()).SetIsHologram(true);
        }
        string configPathSlope = string.Format("CfgVehicles %1 slopeTolerance", GetProjectionEntity().GetType());
        if (GetGame().ConfigIsExisting(configPathSlope))
        {
            m_SlopeTolerance = GetGame().ConfigGetFloat(configPathSlope);
        }
        string configPathAlign = string.Format("CfgVehicles %1 alignHologramToTerain", GetProjectionEntity().GetType());
        if (GetGame().ConfigIsExisting(configPathAlign))
        {
            m_AlignToTerrain = GetGame().ConfigGetInt(configPathAlign);
        }
        string configPathOrientationLimit = string.Format("CfgVehicles %1 yawPitchRollLimit", GetProjectionEntity().GetType());
        if (GetGame().ConfigIsExisting(configPathOrientationLimit))
        {
            m_YawPitchRollLimit = GetGame().ConfigGetVector(configPathOrientationLimit);
        }
    }
References CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetTextOut(), CGame::ConfigGetVector(), ConfigIsExisting(), CreateTrigger(), ECE_LOCAL, ECE_PLACE_ON_SURFACE, ECE_TRACE, ErrorEx, GetGame(), GetProjectionEntity(), GetType(), m_AlignToTerrain, m_ContactComponent, m_FromAdjusted, m_Parent, m_Player, m_Projection, m_ProjectionTrigger, m_ProjectionTypename, m_Rotation, m_SlopeTolerance, m_UpdatePosition, m_WatchtowerBlockedComponentNames, m_WatchtowerIgnoreComponentNames, m_YawPitchRollLimit, ProjectionBasedOnParent(), RefreshTrigger(), SetAnimations(), SetProjectionEntity(), and string::ToString().
~Hologram()
void Hologram::~Hologram () inline private
Definition at line 148 of file hologram.c.
    {
        if (GetGame())
        {
            if (m_Projection)
            {
                GetGame().ObjectDelete(m_Projection);
            }
            if (m_ProjectionTrigger)
            {
                GetGame().ObjectDelete(m_ProjectionTrigger);
            }
        }
        #ifdef DEVELOPER
        DestroyDebugCollisionBox();
        #endif
    }
References DestroyDebugCollisionBox(), GetGame(), m_Projection, m_ProjectionTrigger, and CGame::ObjectDelete().
Member Function Documentation
AddProjectionRotation()
void Hologram::AddProjectionRotation (float addition) inline private
Definition at line 1351 of file hologram.c.
    {
        m_Rotation[0] = m_Rotation[0] + addition;
    }
References m_Rotation.
AlignProjectionOnTerrain()
vector Hologram::AlignProjectionOnTerrain (float timeslice) inline private
Definition at line 285 of file hologram.c.
    {
        vector y_p_r;
        if ( m_AlignToTerrain )
        {
            vector projection_orientation_angles = GetDefaultOrientation() + GetProjectionRotation();
            vector mat0[3];
            vector mat1[3];
            vector mat2[3];
            vector projection_position = m_Projection.GetPosition();
            vector normal;
            if ( m_ContactDir.Length() > 0 )
            {
                normal = m_ContactDir;
            }
            else
            {
                normal = GetGame().SurfaceGetNormal( projection_position[0], projection_position[2] );
            }
            vector angles = normal.VectorToAngles();
            angles[1] = angles[1] + 270;
            angles[0] = Math.Clamp( angles[0], 0, 360 );
            angles[1] = Math.Clamp( angles[1], 0, 360 );
            angles[2] = Math.Clamp( angles[2], 0, 360 );
            projection_orientation_angles[0] = projection_orientation_angles[0] + ( 360 - angles[0] );
            Math3D.YawPitchRollMatrix( projection_orientation_angles, mat0 );
            Math3D.YawPitchRollMatrix( angles, mat1 );
            Math3D.MatrixMultiply3( mat1, mat0, mat2 );
            y_p_r = Math3D.MatrixToAngles( mat2 );
        }
        else
        {
            y_p_r = GetDefaultOrientation() + GetProjectionRotation();
            if ( y_p_r[0] > 180 )
            {
                y_p_r[0] = y_p_r[0] - 360;
            }
            if ( y_p_r[0] < -180 )
            {
                y_p_r[0] = y_p_r[0] + 360;
            }
        }
        return SmoothProjectionMovement( y_p_r, timeslice );
    }
References Math::Clamp(), GetDefaultOrientation(), GetGame(), GetProjectionRotation(), vector::Length(), m_AlignToTerrain, m_ContactDir, m_Projection, Math3D::MatrixMultiply3(), Math3D::MatrixToAngles(), SmoothProjectionMovement(), CGame::SurfaceGetNormal(), vector::VectorToAngles(), and Math3D::YawPitchRollMatrix().
Referenced by UpdateHologram().
CheckPowerSource()
void Hologram::CheckPowerSource () inline private
Definition at line 951 of file hologram.c.
    {
        //in range of its power source.
        if ( m_Player && m_Parent && m_Parent.HasEnergyManager() && m_Parent.GetCompEM().IsPlugged() )
        {
            // Unplug the device when the player is too far from the power source.
            m_Parent.GetCompEM().UpdatePlugState();
            // Delete local hologram when plug is rippled out and advanced placement is active
            if( GetGame().IsMultiplayer() && GetGame().IsClient() )
            {
                if (!m_Parent.GetCompEM().IsPlugged())
                    m_Player.TogglePlacingLocal();
            }
        }
    }
References GetGame(), m_Parent, and m_Player.
Referenced by UpdateHologram().
CorrectForWatchtower()
vector Hologram::CorrectForWatchtower (int contactComponent, vector contactPos, PlayerBase player, Object hitObject) inline private
Definition at line 1203 of file hologram.c.
    {
        // Raycast has hit one of the trigger boxes that show construction prompts, so projection would be floating in the air without this correction
        if (m_WatchtowerIgnoreComponentNames.Find(hitObject.GetActionComponentName(contactComponent, LOD.NAME_VIEW)) != -1 )
            contactPos[1] = hitObject.GetActionComponentPosition(contactComponent, LOD.NAME_VIEW)[1];
        return contactPos;
    }
References m_WatchtowerIgnoreComponentNames, and LOD::NAME_VIEW.
Referenced by GetProjectionEntityPosition().
CorrectMaterialPathName()
string Hologram::CorrectMaterialPathName () inline private
Definition at line 1507 of file hologram.c.
    {
        if (IsColliding() || IsFloating())
        {
            return SUFFIX_MATERIAL_UNDEPLOYABLE;
        }
        else if (m_Parent.HasEnergyManager())
        {
            ComponentEnergyManager comp_em = m_Parent.GetCompEM();
            string SEL_CORD_PLUGGED = m_Parent.GetCompEM().SEL_CORD_PLUGGED;
            string SEL_CORD_FOLDED = m_Parent.GetCompEM().SEL_CORD_FOLDED;
            if (comp_em.IsPlugged() && comp_em.IsEnergySourceAtReach(GetProjectionPosition()))
            {
                m_Projection.SetAnimationPhase(SEL_CORD_PLUGGED, 0);
                m_Projection.SetAnimationPhase(SEL_CORD_FOLDED, 1);
                return SUFFIX_MATERIAL_POWERED;
            }
            else
            {
                m_Projection.SetAnimationPhase(SEL_CORD_PLUGGED, 1);
                m_Projection.SetAnimationPhase(SEL_CORD_FOLDED, 0);
            }
        }
        return SUFFIX_MATERIAL_DEPLOYABLE;
    }
References GetProjectionPosition(), IsColliding(), ComponentEnergyManager::IsEnergySourceAtReach(), IsFloating(), ComponentEnergyManager::IsPlugged(), m_Parent, m_Projection, ItemBase::SEL_CORD_FOLDED, ItemBase::SEL_CORD_PLUGGED, SUFFIX_MATERIAL_DEPLOYABLE, SUFFIX_MATERIAL_POWERED, and SUFFIX_MATERIAL_UNDEPLOYABLE.
Referenced by RefreshVisual().
CreateTrigger()
void Hologram::CreateTrigger () inline private
Definition at line 367 of file hologram.c.
    {
        Class.CastTo(m_ProjectionTrigger, g_Game.CreateObjectEx("ProjectionTrigger", GetProjectionPosition(), SPAWN_FLAGS));
        m_ProjectionTrigger.SetOrientation(GetProjectionOrientation());
        m_ProjectionTrigger.SetParentObject(this);
        m_ProjectionTrigger.SetParentOwner(m_Player);
        RefreshVisual();
    }
References Class::CastTo(), g_Game, GetProjectionOrientation(), GetProjectionPosition(), m_Player, m_ProjectionTrigger, RefreshVisual(), and SPAWN_FLAGS.
Referenced by Hologram().
DoesHaveProjection()
static bool Hologram::DoesHaveProjection (ItemBase item) inline static private
DEPRECATED.
Definition at line 240 of file hologram.c.
    {
        return item && (item.IsDeployable() || item.CanMakeGardenplot() || item.IsInherited(DeployableContainer_Base));
    }
References ItemBase::CanMakeGardenplot(), DeployableContainer_Base(), and ItemBase::IsDeployable().
EvaluateCollision()
void Hologram::EvaluateCollision (ItemBase action_item = null) inline private
Definition at line 424 of file hologram.c.
    {
        if ( IsFloating() || IsHidden() || IsCollidingBBox(action_item) || IsCollidingPlayer() || IsClippingRoof() || !IsBaseViable() || IsCollidingGPlot() || IsCollidingZeroPos() || IsCollidingAngle() || !IsPlacementPermitted() || !HeightPlacementCheck() || IsUnderwater() || IsInTerrain() )
        {
            SetIsColliding( true );
        }
        else if ( m_Projection.IsInherited( TrapSpawnBase ))
        {
            #ifdef DEVELOPER
            DebugText("Inherits from TrapSpawnBase, checking IsPlaceableAtposition", true);
            #endif
            TrapSpawnBase trap_spawn_base;
            Class.CastTo( trap_spawn_base,  m_Projection );
            SetIsColliding( !trap_spawn_base.IsPlaceableAtPosition( m_Projection.GetPosition() ) );
        }
        else if ( m_Projection.IsInherited( TrapBase ))
        {
            #ifdef DEVELOPER
            DebugText("Inherits from TrapBase, checking IsPlaceableAtposition", true);
            #endif
            TrapBase trap_base;
            Class.CastTo(trap_base,  m_Projection);
            SetIsColliding( !trap_base.IsPlaceableAtPosition( m_Projection.GetPosition() ) );
        }
        else
        {
            SetIsColliding( false );
        }
    }
References Class::CastTo(), HeightPlacementCheck(), IsBaseViable(), IsClippingRoof(), IsCollidingAngle(), IsCollidingBBox(), IsCollidingGPlot(), IsCollidingPlayer(), IsCollidingZeroPos(), IsFloating(), IsHidden(), IsInTerrain(), TrapSpawnBase::IsPlaceableAtPosition(), IsPlacementPermitted(), IsUnderwater(), m_Projection, and SetIsColliding().
Referenced by UpdateHologram().
GetCollisionBoxSize()
protected vector Hologram::GetCollisionBoxSize (vector min_max[2]) inline private
Definition at line 1002 of file hologram.c.
    {
        vector box_size = Vector(1,1,1);
        box_size[0] = min_max[1][0] - min_max[0][0];
        box_size[2] = min_max[1][2] - min_max[0][2];
        box_size[1] = min_max[1][1] - min_max[0][1];
        return box_size;
    }
References Vector().
Referenced by GetProjectionDiameter(), GetProjectionRadius(), and IsCollidingBBox().
GetDefaultOrientation()
vector Hologram::GetDefaultOrientation () inline private
Definition at line 1445 of file hologram.c.
    {
        m_DefaultOrientation = GetGame().GetCurrentCameraDirection().VectorToAngles();
        m_DefaultOrientation[1] = 0;
        if (!GetParentEntity().PlacementCanBeRotated())
        {
            m_DefaultOrientation = vector.Zero;
        }
        return m_DefaultOrientation;
    }
References CGame::GetCurrentCameraDirection(), GetGame(), GetParentEntity(), m_DefaultOrientation, vector::VectorToAngles(), and vector::Zero.
Referenced by AlignProjectionOnTerrain().
GetHiddenSelection()
int Hologram::GetHiddenSelection (string selection) inline private
Definition at line 1458 of file hologram.c.
    {
        int idx = m_Projection.GetHiddenSelectionIndex(selection);
        if ( idx != -1 )
            return idx;
        else
            return 0;
    }
References m_Projection.
Referenced by RefreshVisual().
GetLeftCloseProjectionVector()
vector Hologram::GetLeftCloseProjectionVector () inline private
Definition at line 1013 of file hologram.c.
    {
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        return min_max[0];
    }
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetLeftFarProjectionVector()
vector Hologram::GetLeftFarProjectionVector () inline private
Definition at line 1031 of file hologram.c.
    {
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        min_max[0][2] = min_max[1][2];
        return min_max[0];
    }
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetParentEntity()
EntityAI Hologram::GetParentEntity () inline private
Definition at line 1257 of file hologram.c.
    {
        return m_Parent;
    }
References m_Parent.
Referenced by GetDefaultOrientation().
GetProjectionCollisionBox()
protected void Hologram::GetProjectionCollisionBox (out vector min_max[2]) inline private
Definition at line 991 of file hologram.c.
    {
        if (!m_Projection.GetCollisionBox( min_max ) && m_Projection.MemoryPointExists("box_placing_min"))
        {
            min_max[0] = m_Projection.GetMemoryPointPos( "box_placing_min" );
            min_max[1] = m_Projection.GetMemoryPointPos( "box_placing_max" );
            //Debug.DrawSphere(m_Projection.ModelToWorld(min_max[0]) , 0.8,Colors.RED, ShapeFlags.ONCE);
            //Debug.DrawSphere(m_Projection.ModelToWorld(min_max[1]), 0.8,Colors.RED, ShapeFlags.ONCE);
        }
    }
References m_Projection.
Referenced by GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetProjectionDiameter(), GetProjectionRadius(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsCollidingBBox(), and RefreshTrigger().
GetProjectionDiameter()
float Hologram::GetProjectionDiameter () inline private
Definition at line 1218 of file hologram.c.
    {
        float diameter;
        float radius;
        vector diagonal;
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        diagonal = GetCollisionBoxSize( min_max );
        diameter = diagonal.Length();
        return diameter;
    }
References GetCollisionBoxSize(), GetProjectionCollisionBox(), and vector::Length().
Referenced by SetOnGround().
GetProjectionEntity()
EntityAI Hologram::GetProjectionEntity () inline private
Definition at line 1267 of file hologram.c.
    {
        return m_Projection;
    }
References m_Projection.
Referenced by ActionDigGardenPlot::ActionCondition(), HeightPlacementCheck(), Hologram(), IsPlacementPermitted(), and PlaceEntity().
GetProjectionEntityPosition()
protected vector Hologram::GetProjectionEntityPosition (PlayerBase player) inline private
will not push hologram up when there is direct hit of an item
Definition at line 1062 of file hologram.c.
    {
        float minProjectionDistance;
        float maxProjectionDistance;
        m_ContactDir = vector.Zero;
        vector minMax[2];
        float projectionRadius = GetProjectionRadius();
        float cameraToPlayerDistance = vector.Distance(GetGame().GetCurrentCameraPosition(), player.GetPosition());
        if (projectionRadius < SMALL_PROJECTION_RADIUS) // objects with radius smaller than 1m
        {
            minProjectionDistance = SMALL_PROJECTION_RADIUS;
            maxProjectionDistance = SMALL_PROJECTION_RADIUS * 2;
        }
        else
        {
            minProjectionDistance = projectionRadius;
            maxProjectionDistance = projectionRadius * 2;
            maxProjectionDistance = Math.Clamp(maxProjectionDistance, SMALL_PROJECTION_RADIUS, LARGE_PROJECTION_DISTANCE_LIMIT);
        }
        vector from = GetGame().GetCurrentCameraPosition();
        //adjusts raycast origin to player head approx. level (limits results behind the character)
        if ( DayZPlayerCamera3rdPerson.Cast(player.GetCurrentCamera()) )
        {
            vector head_pos;
            MiscGameplayFunctions.GetHeadBonePos(player,head_pos);
            float dist = vector.Distance(head_pos,from);
            from = from + GetGame().GetCurrentCameraDirection() * dist;
        }
        vector to = from + (GetGame().GetCurrentCameraDirection() * (maxProjectionDistance + cameraToPlayerDistance));
        vector contactPosition;
        set<Object> hitObjects = new set<Object>();
        DayZPhysics.RaycastRV(from, to, contactPosition, m_ContactDir, m_ContactComponent, hitObjects, player, m_Projection, false, false, ObjIntersectFire);
        bool contactHitProcessed = false;
        if (!CfgGameplayHandler.GetDisableIsCollidingBBoxCheck())
        {
            if (hitObjects.Count() > 0)
            {
                if (hitObjects[0].IsInherited(Watchtower))
                {
                    contactHitProcessed = true;
                    contactPosition = CorrectForWatchtower(m_ContactComponent, contactPosition, player, hitObjects[0]);
                }
                if (!contactHitProcessed && hitObjects[0].IsInherited(InventoryItem))
                    contactPosition = hitObjects[0].GetPosition();
            }
        }
        static const float raycastOriginOffsetOnFail = 0.25;
        static const float minDistFromStart = 0.01;
        // Camera isn't correctly positioned in some cases, leading to raycasts hitting the object directly behind the camera
        if ((hitObjects.Count() > 0) && (vector.DistanceSq(from, contactPosition) < minDistFromStart))
        {
            from = contactPosition + GetGame().GetCurrentCameraDirection() * raycastOriginOffsetOnFail;
            DayZPhysics.RaycastRV( from, to, contactPosition, m_ContactDir, m_ContactComponent, hitObjects, player, m_Projection, false, false, ObjIntersectFire );
        }
        bool isFloating = SetHologramPosition(player.GetPosition(), minProjectionDistance, maxProjectionDistance, contactPosition);
        SetIsFloating(isFloating);
        #ifdef DEVELOPER
        DrawDebugArrow(minProjectionDistance, maxProjectionDistance);
        if (DiagMenu.GetBool(DiagMenuIDs.DM_HOLOGRAM))
        {
            Debug.DrawSphere(GetProjectionPosition(), 0.1, 0x99FF0000, ShapeFlags.ONCE|ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE);
        }
        #endif
        m_FromAdjusted = from;
        return contactPosition;
    }
References Math::Clamp(), CorrectForWatchtower(), DayZPlayerCamera3rdPerson(), vector::Distance(), vector::DistanceSq(), Debug::DrawSphere(), DiagMenu::GetBool(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), CfgGameplayHandler::GetDisableIsCollidingBBoxCheck(), GetGame(), GetProjectionPosition(), GetProjectionRadius(), LARGE_PROJECTION_DISTANCE_LIMIT, m_ContactComponent, m_ContactDir, m_FromAdjusted, m_Projection, DayZPhysics::RaycastRV(), SetHologramPosition(), SetIsFloating(), SMALL_PROJECTION_RADIUS, and vector::Zero.
Referenced by UpdateHologram().
GetProjectionName()
string Hologram::GetProjectionName (ItemBase item) inline private
configuration override
Definition at line 212 of file hologram.c.
    {
        if (m_ProjectionTypename != "")
        {
            return m_ProjectionTypename;
        }
        if (!item)
        {
            return "";
        }
        if (item.CanMakeGardenplot())
        {
            return "GardenPlotPlacing";
        }
        //Camping & Base building
        if (item.IsInherited( TentBase ) || item.IsBasebuildingKit())
        {
            return item.GetType() + "Placing";
        }
        return item.GetType();
    }
References ItemBase::CanMakeGardenplot(), ItemBase::IsBasebuildingKit(), and m_ProjectionTypename.
Referenced by ProjectionBasedOnParent().
GetProjectionOrientation()
vector Hologram::GetProjectionOrientation () inline private
Definition at line 1437 of file hologram.c.
    {
        if (m_Projection)
            return m_Projection.GetOrientation();
        return vector.Zero;
    }
References m_Projection, and vector::Zero.
Referenced by CreateTrigger(), IsCollidingBBox(), and RefreshTrigger().
GetProjectionPosition()
vector Hologram::GetProjectionPosition () inline private
Definition at line 1429 of file hologram.c.
    {
        if (m_Projection)
            return m_Projection.GetPosition();
        return vector.Zero;
    }
References m_Projection, and vector::Zero.
Referenced by CorrectMaterialPathName(), CreateTrigger(), GetProjectionEntityPosition(), HeightPlacementCheck(), IsBaseFlat(), IsCollidingZeroPos(), IsPlacementPermitted(), and RefreshTrigger().
GetProjectionRadius()
float Hologram::GetProjectionRadius () inline private
Definition at line 1232 of file hologram.c.
    {
        float diameter;
        float radius;
        vector diagonal;
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        diagonal = GetCollisionBoxSize( min_max );
        diameter = diagonal.Length();
        radius = diameter / 2;
        return radius;
    }
References GetCollisionBoxSize(), GetProjectionCollisionBox(), and vector::Length().
Referenced by GetProjectionEntityPosition().
GetProjectionRotation()
vector Hologram::GetProjectionRotation () inline private
Definition at line 1346 of file hologram.c.
    {
        return m_Rotation;
    }
References m_Rotation.
Referenced by AlignProjectionOnTerrain().
GetRightCloseProjectionVector()
vector Hologram::GetRightCloseProjectionVector () inline private
Definition at line 1021 of file hologram.c.
    {
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        min_max[1][1] = min_max[0][1];
        min_max[1][2] = min_max[0][2];
        return min_max[1];
    }
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetRightFarProjectionVector()
vector Hologram::GetRightFarProjectionVector () inline private
Definition at line 1040 of file hologram.c.
    {
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        min_max[1][1] = min_max[0][1];
        return min_max[1];
    }
References GetProjectionCollisionBox().
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot(), IsBaseViable(), IsInTerrain(), and IsUnderwater().
GetUpdatePosition()
bool Hologram::GetUpdatePosition () inline private
Definition at line 1252 of file hologram.c.
    {
        return m_UpdatePosition;
    }
References m_UpdatePosition.
Referenced by UpdateHologram().
HeightPlacementCheck()
bool Hologram::HeightPlacementCheck () inline private
Checks height relative to player's position.
Definition at line 797 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableHeightPlacementCheck())
            return true;
        if ( GetProjectionEntity() ) //simple height check
        {
            vector playerpos = m_Player.GetPosition();
            vector projectionpos = GetProjectionPosition();
            float delta1 = playerpos[1] - projectionpos[1];
            if ( delta1 > DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF || delta1 < -DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF )
            {
                #ifdef DEVELOPER
                DebugText("HeightPlacementCheck(must be true): ", true, false, " | Height difference between item and player is larger than " + DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF);
                #endif
                return false;
            }
        }
        #ifdef DEVELOPER
        DebugText("HeightPlacementCheck(must be true): ", true, true);
        #endif
        return true;
    }
References DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF, CfgGameplayHandler::GetDisableHeightPlacementCheck(), GetProjectionEntity(), GetProjectionPosition(), and m_Player.
Referenced by EvaluateCollision().
HideWhenClose()
vector Hologram::HideWhenClose (vector pos) inline private
Definition at line 1416 of file hologram.c.
    {
        //if the hologram is too close to player when he looks to the sky, send the projection to away
        vector cam_dir = GetGame().GetCurrentCameraDirection();
        if( cam_dir[1] > LOOKING_TO_SKY )
        {
            pos = "0 0 0";
        }
        return pos;
    }
References CGame::GetCurrentCameraDirection(), GetGame(), and LOOKING_TO_SKY.
Referenced by SetOnGround().
IsBaseFlat()
bool Hologram::IsBaseFlat (vector contact_pos_left_close, vector contact_pos_right_close, vector contact_pos_left_far, vector contact_pos_right_far) inline private
Definition at line 762 of file hologram.c.
    {
        vector projection_pos = GetProjectionPosition();
        float slope_pos_left_close = Math.AbsFloat(projection_pos[1] - contact_pos_left_close[1]);
        float slope_pos_right_close = Math.AbsFloat(projection_pos[1] - contact_pos_right_close[1]);
        float slope_pos_left_far = Math.AbsFloat(projection_pos[1] - contact_pos_left_far[1]);
        float slope_pos_right_far = Math.AbsFloat(projection_pos[1] - contact_pos_right_far[1]);
        bool isTrue = slope_pos_left_close < m_SlopeTolerance && slope_pos_right_close < m_SlopeTolerance && slope_pos_left_far < m_SlopeTolerance && slope_pos_right_far < m_SlopeTolerance;
        #ifdef DEVELOPER
        DebugText("IsBaseFlat(must be true): ", true, isTrue, " (slope < slopeTolerance) | slopeTolerance:  " + m_SlopeTolerance + " | lc: " + slope_pos_left_close + " | rc: " + slope_pos_right_close + " | lf: " + slope_pos_left_far + " | rf: " + slope_pos_right_far);
        DrawArrow(projection_pos, contact_pos_left_close, slope_pos_left_close < m_SlopeTolerance);
        DrawArrow(projection_pos, contact_pos_right_close, slope_pos_right_close < m_SlopeTolerance);
        DrawArrow(projection_pos, contact_pos_left_far, slope_pos_left_far < m_SlopeTolerance);
        DrawArrow(projection_pos, contact_pos_right_far, slope_pos_right_far < m_SlopeTolerance);
        #endif
        return isTrue;
        }
References Math::AbsFloat(), GetProjectionPosition(), and m_SlopeTolerance.
Referenced by IsBaseViable().
IsBaseIntact()
bool Hologram::IsBaseIntact (Object under_left_close, Object under_right_close, Object under_left_far, Object under_right_far) inline private
Definition at line 676 of file hologram.c.
    {
        bool isTrue = (under_left_close == under_right_close && under_right_close == under_left_far && under_left_far == under_right_far);
        #ifdef DEVELOPER
        DebugText("IsBaseIntact(must be true and all equal): ", true, isTrue, " | ulc: " + Object.GetDebugName(under_left_close) + " | urc: " + Object.GetDebugName(under_right_close) + " | ulf: " + Object.GetDebugName(under_left_far) + " | urf: " + Object.GetDebugName(under_right_far));
        if (!isTrue)
        {
            array<bool> conditions = new array<bool>();
            conditions.Insert(under_left_close == null);
            conditions.Insert(under_right_close == null);
            conditions.Insert(under_left_far == null);
            conditions.Insert(under_right_far == null);
            int amountOfNull = 0;
            if (!under_left_close)
                ++amountOfNull;
            if (!under_right_close)
                ++amountOfNull;
            if (!under_left_far)
                ++amountOfNull;
            if (!under_right_far)
                ++amountOfNull;
            if ( amountOfNull < 3 )
                for ( int i = 0; i < conditions.Count(); ++i)
                    conditions[i] = !conditions[i];
            DrawBaseSpheres(conditions);
        }
        #endif
        return isTrue;
    }
Referenced by IsBaseViable().
IsBaseStatic()
bool Hologram::IsBaseStatic (Object objectToCheck) inline private
Definition at line 658 of file hologram.c.
    {
        //check if the object below hologram is dynamic object. Dynamic objects like barrels can be taken to hands
        //and item which had been placed on top of them, would stay floating in the air
        #ifdef DEVELOPER
        if (objectToCheck == null)
            DebugText("IsBaseStatic(must be true): ", true, true, " | objectToCheck is null (this is good)");
        else
            DebugText("IsBaseStatic(must be true): ", true, IsObjectStatic(objectToCheck));
        #endif
        return objectToCheck == null || IsObjectStatic(objectToCheck);
    }
References IsObjectStatic().
Referenced by IsBaseViable().
IsBaseViable()
bool Hologram::IsBaseViable () inline private
Definition at line 566 of file hologram.c.
    {
        //This function is not required to solve server-side fixes for clipping, saves calculations and potential false negatives
        if (GetGame().IsServer() && GetGame().IsMultiplayer())
            return true;
        if (CfgGameplayHandler.GetDisableIsBaseViableCheck())
            return true;
        vector from_left_close = m_Projection.CoordToParent( GetLeftCloseProjectionVector() );
        vector to_left_close_down = from_left_close + "0 -1 0";
        vector from_right_close = m_Projection.CoordToParent( GetRightCloseProjectionVector() );
        vector to_right_close_down = from_right_close + "0 -1 0";
        vector from_left_far = m_Projection.CoordToParent( GetLeftFarProjectionVector() );
        vector to_left_far_down = from_left_far + "0 -1 0";
        vector from_right_far = m_Projection.CoordToParent( GetRightFarProjectionVector() );
        vector to_right_far_down = from_right_far + "0 -1 0";
        vector contact_pos_left_close;
        vector contact_pos_right_close;
        vector contact_pos_left_far;
        vector contact_pos_right_far;
        vector contact_dir_left_close;
        vector contact_dir_right_close;
        vector contact_dir_left_far;
        vector contact_dir_right_far;
        int contact_component_left_close;
        int contact_component_right_close;
        int contact_component_left_far;
        int contact_component_right_far;
        set<Object> results_left_close = new set<Object>;
        set<Object> results_right_close = new set<Object>;
        set<Object> results_left_far = new set<Object>;
        set<Object> results_right_far = new set<Object>;
        Object obj_left_close;
        Object obj_right_close;
        Object obj_left_far;
        Object obj_right_far;
        //Not sure what the intention here was before, but it boiled down to a very bloated version of what you see here right now
        DayZPhysics.RaycastRV( from_left_close, to_left_close_down, contact_pos_left_close, contact_dir_left_close, contact_component_left_close, results_left_close, null, m_Projection, false, false, ObjIntersectFire );
        if (results_left_close.Count() > 0)
            obj_left_close = results_left_close[results_left_close.Count() - 1];
        DayZPhysics.RaycastRV( from_right_close, to_right_close_down, contact_pos_right_close, contact_dir_right_close, contact_component_right_close, results_right_close, null, m_Projection, false, false, ObjIntersectFire );
        if (results_right_close.Count() > 0)
            obj_right_close = results_right_close[results_right_close.Count() - 1];
        DayZPhysics.RaycastRV( from_left_far, to_left_far_down, contact_pos_left_far, contact_dir_left_far, contact_component_left_far, results_left_far, null, m_Projection, false, false, ObjIntersectFire );
        if (results_left_far.Count() > 0)
            obj_left_far = results_left_far[results_left_far.Count() - 1];
        DayZPhysics.RaycastRV( from_right_far, to_right_far_down, contact_pos_right_far, contact_dir_right_far, contact_component_right_far, results_right_far, null, m_Projection, false, false, ObjIntersectFire );
        if (results_right_far.Count() > 0)
            obj_right_far = results_right_far[results_right_far.Count() - 1];
        return IsBaseIntact( obj_left_close, obj_right_close, obj_left_far, obj_right_far ) && IsBaseStatic( obj_left_close ) && IsBaseFlat( contact_pos_left_close, contact_pos_right_close, contact_pos_left_far, contact_pos_right_far );
    }
References CfgGameplayHandler::GetDisableIsBaseViableCheck(), GetGame(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsBaseFlat(), IsBaseIntact(), IsBaseStatic(), m_Projection, and DayZPhysics::RaycastRV().
Referenced by EvaluateCollision().
IsBehindObstacle()
bool Hologram::IsBehindObstacle () inline private
DEPRECATED.
Definition at line 651 of file hologram.c.
    {
        ErrorEx("Deprecated check - do not use", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
IsClippingRoof()
bool Hologram::IsClippingRoof () inline private
Definition at line 454 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsClippingRoofCheck())
            return false;
        if (GetGame().IsServer() && GetGame().IsMultiplayer())
            return false;
        //Some locations allow you to look up and attempt placing the hologram on the bottom side of a floor - most notably the floors of a watchtower
        //This check also prevents some very unnatural placements
        bool b1 = m_Projection.GetPosition()[1] > GetGame().GetCurrentCameraPosition()[1];
        bool b2 = false;
        #ifdef DEVELOPER
        vector from, to;
        #endif
        if (m_Projection.DoPlacingHeightCheck())
        {
            b2 = MiscGameplayFunctions.IsUnderRoofEx(m_Projection, GameConstants.ROOF_CHECK_RAYCAST_DIST, ObjIntersectFire);
            #ifdef DEVELOPER
            MiscGameplayFunctions.IsUnderRoofFromToCalculation(m_Projection, from, to);
            DrawArrow(from, to, !b2);
            #endif
        }
        #ifdef DEVELOPER
        DebugText("IsClippingRoof: ", false, b1, " | (projection height) " + m_Projection.GetPosition()[1] + " > (camera height) " + GetGame().GetCurrentCameraPosition()[1]);
        DebugText("IsClippingRoof: ", false, b2, " | (DoPlacingHeightCheck) " + m_Projection.DoPlacingHeightCheck() + " && (IsUnderRoof) " + MiscGameplayFunctions.IsUnderRoof(m_Projection) + " | from: " + from[1] + " | to: " + to[1]);
        #endif
        return b1 || b2;
    }
References CGame::GetCurrentCameraPosition(), CfgGameplayHandler::GetDisableIsClippingRoofCheck(), GetGame(), m_Projection, and GameConstants::ROOF_CHECK_RAYCAST_DIST.
Referenced by EvaluateCollision().
IsColliding()
bool Hologram::IsColliding () inline private
Definition at line 1308 of file hologram.c.
    {
        return m_IsColliding;
    }
References m_IsColliding.
Referenced by ActionDigGardenPlot::ActionCondition(), and CorrectMaterialPathName().
IsCollidingAngle()
bool Hologram::IsCollidingAngle () inline private
Definition at line 486 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingAngleCheck())
            return false;
        vector projection_orientation = m_Projection.GetOrientation();
        bool isTrue = Math.AbsFloat( projection_orientation[1] ) > m_YawPitchRollLimit[1] || Math.AbsFloat( projection_orientation[2] ) > m_YawPitchRollLimit[2];
        #ifdef DEVELOPER
        DebugText("IsCollidingAngle: ", false, isTrue, " | (proj pitch) " + Math.AbsFloat( projection_orientation[1] ) + " > (pitch limit) " + m_YawPitchRollLimit[1] + " | (proj roll) " + Math.AbsFloat( projection_orientation[2] ) + " > (roll limit) " + m_YawPitchRollLimit[2]);
        #endif
        return isTrue;
    }
References Math::AbsFloat(), CfgGameplayHandler::GetDisableIsCollidingAngleCheck(), m_Projection, and m_YawPitchRollLimit.
Referenced by EvaluateCollision().
IsCollidingBBox()
bool Hologram::IsCollidingBBox (ItemBase action_item = null) inline private
Definition at line 519 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingBBoxCheck())
            return false;
        vector center;
        vector relativeOffset; //we need to lift BBox, because it is calculated from the bottom of projection, and not from the middle
        vector absoluteOffset = "0 0.01 0"; //we need to lift BBox even more, because it colliddes with house floors due to various reasons (probably geometry or float imperfections)
        vector orientation = GetProjectionOrientation();
        vector edgeLength;
        vector minMax[2];
        array<Object> excludedObjects = new array<Object>();
        array<Object> collidedObjects = new array<Object>();
        GetProjectionCollisionBox(minMax);
        relativeOffset[1] = (minMax[1][1] - minMax[0][1]) * 0.5;
        center = m_Projection.GetPosition() + relativeOffset + absoluteOffset;
        edgeLength = GetCollisionBoxSize(minMax);
        excludedObjects.Insert(m_Projection);
        excludedObjects.Insert(m_Player);
        if (action_item)
            excludedObjects.Insert(action_item);
        //add is construction check
        // Base building objects behave in a way that causes this test to generate false positives
        bool isTrue = GetGame().IsBoxCollidingGeometry(center, orientation, edgeLength, ObjIntersectFire, ObjIntersectGeom, excludedObjects, collidedObjects);
        #ifdef DEVELOPER
        if (DiagMenu.GetBool(DiagMenuIDs.DM_HOLOGRAM))
        {
            string text = "";
            foreach (Object object: collidedObjects)
                text += " | " + Object.GetDebugName(object);
            DebugText("IsCollidingBBox: ", false, isTrue, text);
            int color = 0x01FFFFFF;
            if (isTrue)
                color = 0x33F22613;
            DrawDebugCollisionBox(minMax, color);
        }
        #endif
        return isTrue;
    }
References DrawDebugCollisionBox(), DiagMenu::GetBool(), GetCollisionBoxSize(), CfgGameplayHandler::GetDisableIsCollidingBBoxCheck(), GetGame(), GetProjectionCollisionBox(), GetProjectionOrientation(), CGame::IsBoxCollidingGeometry(), m_Player, and m_Projection.
Referenced by EvaluateCollision().
IsCollidingGPlot()
bool Hologram::IsCollidingGPlot () inline private
Definition at line 628 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingGPlotCheck())
            return false;
        #ifdef DEVELOPER
        DebugText("IsCollidingGPlot: ", false, m_IsCollidingGPlot);
        #endif
        return m_IsCollidingGPlot;
    }
References CfgGameplayHandler::GetDisableIsCollidingGPlotCheck(), and m_IsCollidingGPlot.
Referenced by EvaluateCollision().
IsCollidingPlayer()
bool Hologram::IsCollidingPlayer () inline private
Definition at line 1321 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingPlayerCheck())
            return false;
        #ifdef DEVELOPER
        DebugText("IsCollidingPlayer: ", false, m_IsCollidingPlayer);
        #endif
        return m_IsCollidingPlayer;
    }
References CfgGameplayHandler::GetDisableIsCollidingPlayerCheck(), and m_IsCollidingPlayer.
Referenced by EvaluateCollision().
IsCollidingZeroPos()
bool Hologram::IsCollidingZeroPos () inline private
Definition at line 639 of file hologram.c.
    {
        vector origin = Vector(0, 0, 0);
        bool isTrue = GetProjectionPosition() == origin;
        #ifdef DEVELOPER
        DebugText("IsCollidingZeroPos: ", false, isTrue);
        #endif
        return isTrue;
    }
References GetProjectionPosition(), and Vector().
Referenced by EvaluateCollision().
IsFenceOrWatchtowerKit()
bool Hologram::IsFenceOrWatchtowerKit () inline private
Definition at line 1198 of file hologram.c.
    {
        return m_Parent.IsBasebuildingKit() || m_Parent.IsInherited(TentBase);
    }
References ItemBase::IsBasebuildingKit(), and m_Parent.
IsFloating()
bool Hologram::IsFloating () inline private
Definition at line 1300 of file hologram.c.
    {
        #ifdef DEVELOPER
        DebugText("IsFloating: ", false, m_IsFloating);
        #endif
        return m_IsFloating;
    }
References m_IsFloating.
Referenced by CorrectMaterialPathName(), EvaluateCollision(), and SetProjectionPosition().
IsHidden()
bool Hologram::IsHidden () inline private
Definition at line 1313 of file hologram.c.
    {
        #ifdef DEVELOPER
        DebugText("IsHidden: ", false, m_IsHidden);
        #endif
        return m_IsHidden;
    }
References m_IsHidden.
Referenced by EvaluateCollision().
IsInTerrain()
bool Hologram::IsInTerrain () inline private
Definition at line 864 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsInTerrainCheck())
            return false;
        vector fromHeightOffset = "0 0.3 0";
        vector toHeightOffset = "0 1 0";
        vector from_left_close = m_Projection.CoordToParent( GetLeftCloseProjectionVector() ) + fromHeightOffset;
        vector to_left_close_down = from_left_close + toHeightOffset;
        vector from_right_close = m_Projection.CoordToParent( GetRightCloseProjectionVector() ) + fromHeightOffset;
        vector to_right_close_down = from_right_close + toHeightOffset;
        vector from_left_far = m_Projection.CoordToParent( GetLeftFarProjectionVector() ) + fromHeightOffset;
        vector to_left_far_down = from_left_far + toHeightOffset;
        vector from_right_far = m_Projection.CoordToParent( GetRightFarProjectionVector() ) + fromHeightOffset;
        vector to_right_far_down = from_right_far + toHeightOffset;
        vector contact_pos_left_close;
        vector contact_pos_right_close;
        vector contact_pos_left_far;
        vector contact_pos_right_far;
        vector contact_dir_left_close;
        vector contact_dir_right_close;
        vector contact_dir_left_far;
        vector contact_dir_right_far;
        int contact_component_left_close;
        int contact_component_right_close;
        int contact_component_left_far;
        int contact_component_right_far;
        #ifdef DEVELOPER
        // I'd rather duplicate this on internal than introduce (even) more raycasts than needed on retail..
        set<Object> lcO = new set<Object>();
        set<Object> rcO = new set<Object>();
        set<Object> lfO = new set<Object>();
        set<Object> rfO = new set<Object>();
        bool lc = DayZPhysics.RaycastRV( from_left_close, to_left_close_down, contact_pos_left_close, contact_dir_left_close, contact_component_left_close, lcO, m_Projection, m_Projection, false, true, ObjIntersectFire );
        bool rc = DayZPhysics.RaycastRV( from_right_close, to_right_close_down, contact_pos_right_close, contact_dir_right_close, contact_component_right_close, rcO, m_Projection, m_Projection, false, true, ObjIntersectFire );
        bool lf = DayZPhysics.RaycastRV( from_left_far, to_left_far_down, contact_pos_left_far, contact_dir_left_far, contact_component_left_far, lfO, m_Projection, m_Projection, false, true, ObjIntersectFire );
        bool rf = DayZPhysics.RaycastRV( from_right_far, to_right_far_down, contact_pos_right_far, contact_dir_right_far, contact_component_right_far, rfO, m_Projection, m_Projection, false, true, ObjIntersectFire );
        bool isTrue = ( lc || rc || lf || rf );
        string text = "";
        if (isTrue)
        {
            if (lc)
                text += " | lc";
            if (rc)
                text += " | rc";
            if (lf)
                text += " | lf";
            if (rf)
                text += " | rf";
            if (lcO.Count() > 0)
                text += " | lcO: " + lcO[0];
            if (rcO.Count() > 0)
                text += " | rcO: " + rcO[0];
            if (lfO.Count() > 0)
                text += " | lfO: " + lfO[0];
            if (rfO.Count() > 0)
                text += " | rfO: " + rfO[0];
            array<bool> conditions = {!lc, !rc, !lf, !rf};
            DrawBaseSpheres(conditions);
        }
        DebugText("IsInTerrain: ", false, isTrue, text);
        #endif
        if (DayZPhysics.RaycastRV( from_left_close, to_left_close_down, contact_pos_left_close, contact_dir_left_close, contact_component_left_close, NULL, m_Projection, m_Projection, false, true, ObjIntersectFire ))
            return true;
        if (DayZPhysics.RaycastRV( from_right_close, to_right_close_down, contact_pos_right_close, contact_dir_right_close, contact_component_right_close, NULL,m_Projection, m_Projection, false, true, ObjIntersectFire ))
            return true;
        if (DayZPhysics.RaycastRV( from_left_far, to_left_far_down, contact_pos_left_far, contact_dir_left_far, contact_component_left_far, NULL, m_Projection, m_Projection, false, true, ObjIntersectFire ))
            return true;
        if (DayZPhysics.RaycastRV( from_right_far, to_right_far_down, contact_pos_right_far, contact_dir_right_far, contact_component_right_far, NULL, m_Projection, m_Projection, false, true, ObjIntersectFire ))
            return true;
        return false;
    }
References CfgGameplayHandler::GetDisableIsInTerrainCheck(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), m_Projection, and DayZPhysics::RaycastRV().
Referenced by EvaluateCollision().
IsObjectStatic()
bool Hologram::IsObjectStatic (Object obj) inline private
Definition at line 671 of file hologram.c.
    {
        return obj.IsBuilding() || obj.IsPlainObject() || (!m_Parent.IsInherited(KitBase) && obj.IsInherited(BaseBuildingBase) && (m_WatchtowerBlockedComponentNames.Find(obj.GetActionComponentName(m_ContactComponent, LOD.NAME_VIEW)) == -1));
    }
References m_ContactComponent, m_Parent, m_WatchtowerBlockedComponentNames, and LOD::NAME_VIEW.
Referenced by IsBaseStatic().
IsPlacementPermitted()
bool Hologram::IsPlacementPermitted () inline private
Checks if the item can be legally placed (usually checked by action as well)
Definition at line 783 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsPlacementPermittedCheck())
            return true;
        ItemBase item = m_Player.GetItemInHands();
        bool isTrue = ( item && item.Type() == GetProjectionEntity().Type() && !item.CanBePlaced(m_Player, GetProjectionPosition()) );
        isTrue = !isTrue; // ??????
        #ifdef DEVELOPER
        DebugText("IsPlacementPermitted(must be true): ", true, isTrue, " (Note: CanBePlaced function on item and projection type must be same as item type)");
        #endif
        return isTrue;
    }
References ItemBase::CanBePlaced(), CfgGameplayHandler::GetDisableIsPlacementPermittedCheck(), GetProjectionEntity(), GetProjectionPosition(), and m_Player.
Referenced by EvaluateCollision().
IsProjectionTrap()
bool Hologram::IsProjectionTrap () inline private
Definition at line 1213 of file hologram.c.
    {
        return m_Projection.IsInherited( TrapBase ) || m_Projection.IsInherited( TrapSpawnBase );
    }
References m_Projection.
IsSurfaceSea()
bool Hologram::IsSurfaceSea (vector position) inline private
Definition at line 1056 of file hologram.c.
    {
        CGame game = GetGame();
        return game.SurfaceIsSea( position[0], position[2] );
    }
References GetGame(), and CGame::SurfaceIsSea().
Referenced by IsUnderwater().
IsSurfaceWater()
bool Hologram::IsSurfaceWater (vector position) inline private
Definition at line 1050 of file hologram.c.
    {
        CGame game = GetGame();
        return game.SurfaceIsSea( position[0], position[2] ) || game.SurfaceIsPond( position[0], position[2] );
    }
References GetGame(), CGame::SurfaceIsPond(), and CGame::SurfaceIsSea().
IsUnderwater()
bool Hologram::IsUnderwater () inline private
Definition at line 821 of file hologram.c.
    {
        if (CfgGameplayHandler.GetDisableIsUnderwaterCheck())
            return false;
        // Fast check middle of object
        string type;
        int liquid;
        g_Game.SurfaceUnderObject(m_Projection, type, liquid);
        if (liquid == LIQUID_WATER)
        {
            #ifdef DEVELOPER
            DebugText("IsUnderwater: ", false, true, " | Surface under object is water");
            #endif
            return true;
        }
        // Check every corner of the object
        vector left_close = m_Projection.CoordToParent( GetLeftCloseProjectionVector() );
        vector right_close = m_Projection.CoordToParent( GetRightCloseProjectionVector() );
        vector left_far = m_Projection.CoordToParent( GetLeftFarProjectionVector() );
        vector right_far = m_Projection.CoordToParent( GetRightFarProjectionVector() );
        bool surface_sea_water = IsSurfaceSea(left_close) || IsSurfaceSea(right_close) || IsSurfaceSea(left_far) || IsSurfaceSea(right_far);
        #ifdef DEVELOPER
        // I'd rather duplicate this on internal than introduce (even) more raycasts than needed on retail..
        float lc = g_Game.GetWaterDepth(left_close);
        float rc = g_Game.GetWaterDepth(right_close);
        float lf = g_Game.GetWaterDepth(left_far);
        float rf = g_Game.GetWaterDepth(right_far);
        bool isTrue = (lc > 0 || rc > 0 || lf > 0 || rf > 0 || surface_sea_water);
        DebugText("IsUnderwater: ", false, isTrue, " surface_sea_water: " + surface_sea_water + " | (all must be less than zero) | lc: " + lc + " | rc: " + rc + " | lf: " + lf + " | rf: " + rf);
        //DebugText("Corner Height: ", false, true, " lc: " + left_close[1] + " | rc: " + right_close[1] + " | lf: " + left_far[1] + " | rf: " + right_far[1]);
        if (isTrue)
        {
            array<bool> conditions = {lc <= 0, rc <= 0, lf <= 0, rf <= 0};
            DrawBaseSpheres(conditions);
        }
        #endif
        return (surface_sea_water || g_Game.GetWaterDepth(left_close) > 0 || g_Game.GetWaterDepth(right_close) > 0 || g_Game.GetWaterDepth(left_far) > 0 || g_Game.GetWaterDepth(right_far) > 0);
    }
References g_Game, CfgGameplayHandler::GetDisableIsUnderwaterCheck(), GetLeftCloseProjectionVector(), GetLeftFarProjectionVector(), GetRightCloseProjectionVector(), GetRightFarProjectionVector(), IsSurfaceSea(), LIQUID_WATER, and m_Projection.
Referenced by EvaluateCollision().
PlaceEntity()
EntityAI Hologram::PlaceEntity (EntityAI entity_for_placing) inline private
Definition at line 968 of file hologram.c.
    {
        //string-based comparison
        if (entity_for_placing.IsInherited(TentBase) || entity_for_placing.IsBasebuildingKit() )
        {
            return entity_for_placing;
        }
        if (m_Projection.IsInherited(GardenPlotPlacing))
        {
            Class.CastTo(entity_for_placing, GetGame().CreateObjectEx( "GardenPlot", m_Projection.GetPosition(), ECE_OBJECT_SWAP ));
            return entity_for_placing;
        }
        //inheritance comparison
        if( !GetProjectionEntity().IsKindOf( m_Parent.GetType() ))
        {
            Class.CastTo(entity_for_placing, GetGame().CreateObjectEx( m_Projection.GetType(), m_Projection.GetPosition(), ECE_OBJECT_SWAP ));
        }
        return entity_for_placing;
    }
References Class::CastTo(), ECE_OBJECT_SWAP, GetGame(), GetProjectionEntity(), IsKindOf(), m_Parent, and m_Projection.
ProjectionBasedOnParent()
string Hologram::ProjectionBasedOnParent () inline private
Definition at line 207 of file hologram.c.
    {
        return GetProjectionName(m_Parent);
    }
References GetProjectionName(), and m_Parent.
Referenced by Hologram().
RefreshTrigger()
void Hologram::RefreshTrigger () inline private
Definition at line 378 of file hologram.c.
    {
        vector min_max[2];
        GetProjectionCollisionBox( min_max );
        m_ProjectionTrigger.SetPosition(GetProjectionPosition());
        m_ProjectionTrigger.SetOrientation(GetProjectionOrientation());
        m_ProjectionTrigger.SetExtents(min_max[0], min_max[1]);
    }
References GetProjectionCollisionBox(), GetProjectionOrientation(), GetProjectionPosition(), and m_ProjectionTrigger.
Referenced by Hologram(), and UpdateHologram().
RefreshVisual()
void Hologram::RefreshVisual () inline private
Definition at line 1483 of file hologram.c.
    {
        if (m_Projection)
        {
            static const string textureName = "#(argb,8,8,3)color(0.5,0.5,0.5,0.75,ca)";
            int hidden_selection            = 0;
            string selection_to_refresh;
            string config_material          = string.Format("CfgVehicles %1 hologramMaterial", m_Projection.GetType());
            string hologram_material        = GetGame().ConfigGetTextOut(config_material);
            string config_model             = string.Format("CfgVehicles %1 hologramMaterialPath", m_Projection.GetType());
            string hologram_material_path   = string.Format("%1\\%2%3", GetGame().ConfigGetTextOut(config_model), hologram_material, CorrectMaterialPathName());
            for (int i = 0; i < m_SelectionsToRefresh.Count(); ++i)
            {
                selection_to_refresh = m_SelectionsToRefresh.Get(i);
                hidden_selection = GetHiddenSelection(selection_to_refresh);
                m_Projection.SetObjectTexture(hidden_selection, textureName);
                m_Projection.SetObjectMaterial(hidden_selection, hologram_material_path);
            }
        }
    }
References CGame::ConfigGetTextOut(), CorrectMaterialPathName(), string::Format(), GetGame(), GetHiddenSelection(), m_Projection, and m_SelectionsToRefresh.
Referenced by CreateTrigger(), and UpdateHologram().
SetAnimations()
void Hologram::SetAnimations () inline private
Definition at line 168 of file hologram.c.
    {
        if ( m_Projection.HasAnimation( ANIMATION_PLACING ) )
        {
            m_Projection.SetAnimationPhase( ANIMATION_PLACING, 0 );
            SetSelectionToRefresh( SELECTION_PLACING );
            if ( m_Projection.HasAnimation( ANIMATION_INVENTORY ) )
            {
                m_Projection.SetAnimationPhase( ANIMATION_INVENTORY, 1 );
            }
        }
        else
        {
            UpdateSelections();
            SetSelectionToRefresh( SELECTION_INVENTORY );
        }
    }
References ANIMATION_INVENTORY, ANIMATION_PLACING, m_Projection, SELECTION_INVENTORY, SELECTION_PLACING, SetSelectionToRefresh(), and UpdateSelections().
Referenced by Hologram().
SetHologramPosition()
protected bool Hologram::SetHologramPosition (vector startPosition, float minProjectionDistance, float maxProjectionDistance, inout vector contactPosition) inline private
Sets hologram position based on player and projection distance.
Parameters
startPosition start position
minProjectionDistance lower distance limit
maxProjectionDistance higher distance limit
inout contactPosition is position of the hologram contact with ground/object
Returns
true if hologram is floating (is on the near or far edge)
Definition at line 1149 of file hologram.c.
    {
        float playerToProjectionDistance = vector.Distance(startPosition, contactPosition);
        vector playerToProjection;
        #ifdef DEVELOPER
        DebugText("SetHologramPosition::startPosition: ", false, m_IsHidden, string.Format(" | %1", startPosition));
        DebugText("SetHologramPosition::contactPosition [in]: ", false, m_IsHidden, string.Format(" | %1", contactPosition));
        DebugText("SetHologramPosition::minProjectionDistance: ", false, m_IsHidden, string.Format(" | %1", minProjectionDistance));
        DebugText("SetHologramPosition::maxProjectionDistance: ", false, m_IsHidden, string.Format(" | %1", maxProjectionDistance));
        DebugText("SetHologramPosition::playerToProjectionDistance: ", false, m_IsHidden, string.Format(" | %1", playerToProjectionDistance));
        #endif
        //hologram is at min distance from player
        if (playerToProjectionDistance <= minProjectionDistance)
        {
            playerToProjection = contactPosition - startPosition;
            playerToProjection.Normalize();
            //prevents the hologram to go underground/floor while hologram exceeds minProjectionDistance
            playerToProjection[1] = playerToProjection[1] + PROJECTION_TRANSITION_MIN;
            contactPosition = startPosition + (playerToProjection * minProjectionDistance);
            #ifdef DEVELOPER
            DebugText("SetHologramPosition::contactPosition[out] (< minProjectDistance): ", false, m_IsHidden, string.Format(" | %1", contactPosition));
            #endif
            return true;
        }
        //hologram is at max distance from player
        else if (playerToProjectionDistance >= maxProjectionDistance)
        {
            playerToProjection = contactPosition - startPosition;
            playerToProjection.Normalize();
            //prevents the hologram to go underground/floor while hologram exceeds maxProjectionDistance
            playerToProjection[1] = playerToProjection[1] + PROJECTION_TRANSITION_MAX;
            contactPosition = startPosition + (playerToProjection * maxProjectionDistance);
            #ifdef DEVELOPER
            DebugText("SetHologramPosition::contactPosition[out] (< maxProjectionDistance): ", false, m_IsHidden, string.Format(" | %1", contactPosition));
            #endif
            return true;
        }
        return false;
    }
References vector::Distance(), m_IsHidden, vector::Normalize(), PROJECTION_TRANSITION_MAX, and PROJECTION_TRANSITION_MIN.
Referenced by GetProjectionEntityPosition().
SetIsColliding()
void Hologram::SetIsColliding (bool is_colliding) inline private
Definition at line 1277 of file hologram.c.
    {
        #ifdef DEVELOPER
        DebugText("Is colliding: ", false, is_colliding);
        #endif
        m_IsColliding = is_colliding;
    }
References m_IsColliding.
Referenced by EvaluateCollision().
SetIsCollidingGPlot()
void Hologram::SetIsCollidingGPlot (bool is_colliding_gplot) inline private
Definition at line 1295 of file hologram.c.
    {
        m_IsCollidingGPlot = is_colliding_gplot;
    }
References m_IsCollidingGPlot.
Referenced by ActionDigGardenPlot::CheckSurfaceBelowGardenPlot().
SetIsCollidingPlayer()
void Hologram::SetIsCollidingPlayer (bool is_colliding) inline private
Definition at line 1290 of file hologram.c.
    {
        m_IsCollidingPlayer = is_colliding;
    }
References m_IsCollidingPlayer.
SetIsFloating()
void Hologram::SetIsFloating (bool is_floating) inline private
Definition at line 1272 of file hologram.c.
    {
        m_IsFloating = is_floating;
    }
References m_IsFloating.
Referenced by GetProjectionEntityPosition().
SetIsHidden()
void Hologram::SetIsHidden (bool is_hidden) inline private
Definition at line 1285 of file hologram.c.
    {
        m_IsHidden = is_hidden;
    }
References m_IsHidden.
SetOnGround()
vector Hologram::SetOnGround (vector position) inline private
Definition at line 1361 of file hologram.c.
    {
        vector from = position;
        vector ground;
        vector player_to_projection_vector;
        float projection_diameter = GetProjectionDiameter();
        ground = Vector(0, -Math.Max(projection_diameter, SMALL_PROJECTION_GROUND), 0);
        vector to = from + ground;
        vector contact_pos = to;
        RaycastRVParams rayInput = new RaycastRVParams(from, to, m_Projection);
        rayInput.flags = CollisionFlags.ALLOBJECTS;
        array<ref RaycastRVResult> results = new array<ref RaycastRVResult>;
        if (DayZPhysics.RaycastRVProxy(rayInput, results))
        {
            RaycastRVResult res;
            for (int i = 0; i < results.Count(); i++)
            {
                res = results.Get(i);
                if (res.entry || (!res.obj && !res.parent))
                {
                    contact_pos = res.pos;
                    break;
                }
            }
        }
        //LOS check
        if (contact_pos != "0 0 0")
        {
            vector check_pos;
            vector check_dir;
            int check_component = -1;
            set<Object> hit_object = new set<Object>;
            to = contact_pos;
            to[1] = to[1] + 0.1;
            from = m_FromAdjusted;
            if (DayZPhysics.RaycastRV(from, to, check_pos, check_dir, check_component, hit_object, null, m_Player, false, false, ObjIntersectFire))
            {
                if ((hit_object.Count() > 0)&& (!hit_object[0].IsInherited(Watchtower) || (hit_object[0].IsInherited(Watchtower) && (m_WatchtowerIgnoreComponentNames.Find(hit_object[0].GetActionComponentName(check_component, LOD.NAME_VIEW)) == -1))))
                {
                    contact_pos = "0 0 0";
                }
            }
        }
        HideWhenClose(contact_pos);
        return contact_pos;
    }
References RaycastRVResult::entry, RaycastRVParams::flags, GetProjectionDiameter(), HideWhenClose(), m_FromAdjusted, m_Player, m_Projection, m_WatchtowerIgnoreComponentNames, Math::Max(), LOD::NAME_VIEW, RaycastRVResult::obj, RaycastRVResult::parent, RaycastRVResult::pos, DayZPhysics::RaycastRV(), DayZPhysics::RaycastRVProxy(), SMALL_PROJECTION_GROUND, and Vector().
Referenced by SetProjectionPosition().
SetProjectionEntity()
void Hologram::SetProjectionEntity (EntityAI projection) inline private
Definition at line 1262 of file hologram.c.
    {
        m_Projection = projection;
    }
References m_Projection.
Referenced by Hologram().
SetProjectionOrientation()
void Hologram::SetProjectionOrientation (vector orientation) inline private
Definition at line 1341 of file hologram.c.
    {
        m_Projection.SetOrientation(orientation);
    }
References m_Projection.
Referenced by UpdateHologram().
SetProjectionPosition()
void Hologram::SetProjectionPosition (vector position) inline private
Definition at line 1331 of file hologram.c.
    {
        m_Projection.SetPosition( position );
        if (IsFloating())
        {
            m_Projection.SetPosition(SetOnGround(position));
        }
    }
References IsFloating(), m_Projection, and SetOnGround().
Referenced by UpdateHologram().
SetSelectionToRefresh() [1/2]
void Hologram::SetSelectionToRefresh (array< string > selection) inline private
Definition at line 1475 of file hologram.c.
    {
        for ( int i = 0; i < selection.Count(); i++ )
        {
            m_SelectionsToRefresh.Insert( selection.Get(i) );
        }
    }
References m_SelectionsToRefresh.
SetSelectionToRefresh() [2/2]
void Hologram::SetSelectionToRefresh (string selection) inline private
Definition at line 1469 of file hologram.c.
    {
        m_SelectionsToRefresh.Insert( selection );
    }
References m_SelectionsToRefresh.
Referenced by SetAnimations().
SetUpdatePosition()
void Hologram::SetUpdatePosition (bool state) inline private
Definition at line 1247 of file hologram.c.
    {
        m_UpdatePosition = state;
    }
References m_UpdatePosition.
SmoothProjectionMovement()
vector Hologram::SmoothProjectionMovement (vector y_p_r, float timeslice) inline private
Definition at line 340 of file hologram.c.
    {
        if ( m_y_p_r_previous )
        {
            if ( Math.AbsFloat( y_p_r[0] - m_y_p_r_previous[0] ) > 100 )
            {
                if ( y_p_r[0] > 0 )
                {
                    m_y_p_r_previous[0] = m_y_p_r_previous[0] + 360;
                }
                if ( y_p_r[0] < 0 )
                {
                    m_y_p_r_previous[0] = m_y_p_r_previous[0] - 360;
                }
            }
            y_p_r[0] = Math.Lerp( m_y_p_r_previous[0], y_p_r[0], 15 * timeslice );
            y_p_r[1] = Math.Lerp( m_y_p_r_previous[1], y_p_r[1], 15 * timeslice );
            y_p_r[2] = Math.Lerp( m_y_p_r_previous[2], y_p_r[2], 15 * timeslice );
        }
        m_y_p_r_previous = y_p_r;
        return y_p_r;
    }
References Math::AbsFloat(), Math::Lerp(), and m_y_p_r_previous.
Referenced by AlignProjectionOnTerrain().
SubtractProjectionRotation()
void Hologram::SubtractProjectionRotation (float subtraction) inline private
Definition at line 1356 of file hologram.c.
    {
        m_Rotation[0] = m_Rotation[0] - subtraction;
    }
References m_Rotation.
UpdateHologram()
void Hologram::UpdateHologram (float timeslice) inline private
Definition at line 246 of file hologram.c.
    {
        if ( !m_Parent )
        {
            m_Player.TogglePlacingLocal();
            return;
        }
        if ( m_Player.IsSwimming() || m_Player.IsClimbingLadder() || m_Player.IsRaised() || m_Player.IsClimbing() || m_Player.IsRestrained() || m_Player.IsUnconscious() )
        {
            m_Player.TogglePlacingLocal();
            return;
        }
        if ( !GetUpdatePosition() )
        {
            return;
        }
        #ifdef DEVELOPER
        DebugConfigValues();
        DestroyDebugCollisionBox();
        #endif
        // update hologram position
        SetProjectionPosition( GetProjectionEntityPosition( m_Player ) );
        SetProjectionOrientation( AlignProjectionOnTerrain( timeslice ) );
        EvaluateCollision();
        RefreshTrigger();
        CheckPowerSource();
        RefreshVisual();
        m_Projection.OnHologramBeingPlaced( m_Player );
    }
References AlignProjectionOnTerrain(), CheckPowerSource(), DestroyDebugCollisionBox(), EvaluateCollision(), GetProjectionEntityPosition(), GetUpdatePosition(), m_Parent, m_Player, m_Projection, RefreshTrigger(), RefreshVisual(), SetProjectionOrientation(), and SetProjectionPosition().
UpdateSelections()
void Hologram::UpdateSelections () inline private
Definition at line 188 of file hologram.c.
    {
        string cfg_access = "CfgVehicles " + m_Projection.GetType() + " AnimationSources ";
        if ( GetGame().ConfigIsExisting(cfg_access) )
        {
            int cfg_access_count = g_Game.ConfigGetChildrenCount(cfg_access);
            for ( int i = 0; i < cfg_access_count; ++i )
            {
                string found_anim;
                GetGame().ConfigGetChildName(cfg_access, i, found_anim);
                float anim_phase = m_Parent.GetAnimationPhase(found_anim);
                m_Projection.SetAnimationPhase(found_anim, anim_phase);
            }
        }
    }
References CGame::ConfigGetChildName(), ConfigIsExisting(), g_Game, GetGame(), m_Parent, and m_Projection.
Referenced by SetAnimations().
Member Data Documentation
ANIMATION_INVENTORY
protected const string Hologram::ANIMATION_INVENTORY = "Inventory" private
Definition at line 33 of file hologram.c.
Referenced by SetAnimations().
ANIMATION_PLACING
protected const string Hologram::ANIMATION_PLACING = "Placing" private
Definition at line 32 of file hologram.c.
Referenced by SetAnimations().
DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF
const float Hologram::DEFAULT_MAX_PLACEMENT_HEIGHT_DIFF = 1.5 static private
Definition at line 44 of file hologram.c.
Referenced by HeightPlacementCheck().
DISTANCE_SMALL_PROJECTION
protected const float Hologram::DISTANCE_SMALL_PROJECTION = 1 private
Definition at line 39 of file hologram.c.
LARGE_PROJECTION_DISTANCE_LIMIT
protected const float Hologram::LARGE_PROJECTION_DISTANCE_LIMIT = 6 private
Deprecated.
Definition at line 40 of file hologram.c.
Referenced by GetProjectionEntityPosition().
LOOKING_TO_SKY
protected const float Hologram::LOOKING_TO_SKY = 0.75 private
Definition at line 43 of file hologram.c.
Referenced by HideWhenClose().
m_AlignToTerrain
protected bool Hologram::m_AlignToTerrain private
Definition at line 47 of file hologram.c.
Referenced by AlignProjectionOnTerrain(), and Hologram().
m_ContactComponent
protected int Hologram::m_ContactComponent private
Definition at line 49 of file hologram.c.
Referenced by GetProjectionEntityPosition(), Hologram(), and IsObjectStatic().
m_ContactDir
protected vector Hologram::m_ContactDir private
Definition at line 30 of file hologram.c.
Referenced by AlignProjectionOnTerrain(), and GetProjectionEntityPosition().
m_DefaultOrientation
protected vector Hologram::m_DefaultOrientation private
Definition at line 27 of file hologram.c.
Referenced by GetDefaultOrientation().
m_FromAdjusted
protected vector Hologram::m_FromAdjusted private
Definition at line 31 of file hologram.c.
Referenced by GetProjectionEntityPosition(), Hologram(), and SetOnGround().
m_IsColliding
protected bool Hologram::m_IsColliding private
Definition at line 19 of file hologram.c.
Referenced by IsColliding(), and SetIsColliding().
m_IsCollidingGPlot
protected bool Hologram::m_IsCollidingGPlot private
Definition at line 20 of file hologram.c.
Referenced by IsCollidingGPlot(), and SetIsCollidingGPlot().
m_IsCollidingPlayer
protected bool Hologram::m_IsCollidingPlayer private
Definition at line 22 of file hologram.c.
Referenced by IsCollidingPlayer(), and SetIsCollidingPlayer().
m_IsFloating
protected bool Hologram::m_IsFloating private
Definition at line 23 of file hologram.c.
Referenced by IsFloating(), and SetIsFloating().
m_IsHidden
protected bool Hologram::m_IsHidden private
Definition at line 25 of file hologram.c.
Referenced by IsHidden(), SetHologramPosition(), and SetIsHidden().
m_IsSlope
protected bool Hologram::m_IsSlope private
Definition at line 21 of file hologram.c.
m_Parent
protected ItemBase Hologram::m_Parent private
Definition at line 13 of file hologram.c.
Referenced by CheckPowerSource(), CorrectMaterialPathName(), GetParentEntity(), Hologram(), IsFenceOrWatchtowerKit(), IsObjectStatic(), PlaceEntity(), ProjectionBasedOnParent(), UpdateHologram(), and UpdateSelections().
m_Player
protected PlayerBase Hologram::m_Player private
Definition at line 15 of file hologram.c.
Referenced by CheckPowerSource(), CreateTrigger(), HeightPlacementCheck(), Hologram(), IsCollidingBBox(), IsPlacementPermitted(), SetOnGround(), and UpdateHologram().
m_Projection
protected EntityAI Hologram::m_Projection private
Definition at line 14 of file hologram.c.
Referenced by AlignProjectionOnTerrain(), CorrectMaterialPathName(), EvaluateCollision(), GetHiddenSelection(), GetProjectionCollisionBox(), GetProjectionEntity(), GetProjectionEntityPosition(), GetProjectionOrientation(), GetProjectionPosition(), Hologram(), IsBaseViable(), IsClippingRoof(), IsCollidingAngle(), IsCollidingBBox(), IsInTerrain(), IsProjectionTrap(), IsUnderwater(), PlaceEntity(), RefreshVisual(), SetAnimations(), SetOnGround(), SetProjectionEntity(), SetProjectionOrientation(), SetProjectionPosition(), UpdateHologram(), UpdateSelections(), and ~Hologram().
m_ProjectionTrigger
protected ProjectionTrigger Hologram::m_ProjectionTrigger private
Definition at line 16 of file hologram.c.
Referenced by CreateTrigger(), Hologram(), RefreshTrigger(), and ~Hologram().
m_ProjectionTypename
protected string Hologram::m_ProjectionTypename private
Definition at line 17 of file hologram.c.
Referenced by GetProjectionName(), and Hologram().
m_Rotation
protected vector Hologram::m_Rotation private
Definition at line 28 of file hologram.c.
Referenced by AddProjectionRotation(), GetProjectionRotation(), Hologram(), and SubtractProjectionRotation().
m_SelectionsToRefresh
protected ref set<string> Hologram::m_SelectionsToRefresh = new set<string> private
Definition at line 51 of file hologram.c.
Referenced by RefreshVisual(), and SetSelectionToRefresh().
m_SlopeTolerance
protected float Hologram::m_SlopeTolerance private
Definition at line 46 of file hologram.c.
Referenced by Hologram(), and IsBaseFlat().
m_UpdatePosition
protected bool Hologram::m_UpdatePosition private
Definition at line 24 of file hologram.c.
Referenced by GetUpdatePosition(), Hologram(), and SetUpdatePosition().
m_WatchtowerBlockedComponentNames
const protected ref array<string> Hologram::m_WatchtowerBlockedComponentNames = new array<string> static private
Definition at line 58 of file hologram.c.
Referenced by Hologram(), and IsObjectStatic().
m_WatchtowerIgnoreComponentNames
const protected ref array<string> Hologram::m_WatchtowerIgnoreComponentNames = new array<string> static private
Definition at line 55 of file hologram.c.
Referenced by CorrectForWatchtower(), Hologram(), and SetOnGround().
m_y_p_r_previous
protected vector Hologram::m_y_p_r_previous private
Definition at line 29 of file hologram.c.
Referenced by SmoothProjectionMovement().
m_YawPitchRollLimit
protected vector Hologram::m_YawPitchRollLimit private
Definition at line 48 of file hologram.c.
Referenced by Hologram(), and IsCollidingAngle().
PROJECTION_TRANSITION_MAX
protected const float Hologram::PROJECTION_TRANSITION_MAX = 0.25 private
Definition at line 42 of file hologram.c.
Referenced by SetHologramPosition().
PROJECTION_TRANSITION_MIN
protected const float Hologram::PROJECTION_TRANSITION_MIN = 1 private
Definition at line 41 of file hologram.c.
Referenced by SetHologramPosition().
SELECTION_INVENTORY
protected const string Hologram::SELECTION_INVENTORY = "inventory" private
Definition at line 35 of file hologram.c.
Referenced by SetAnimations().
SELECTION_PLACING
protected const string Hologram::SELECTION_PLACING = "placing" private
Definition at line 34 of file hologram.c.
Referenced by SetAnimations().
SMALL_PROJECTION_GROUND
protected const float Hologram::SMALL_PROJECTION_GROUND = 2 private
Definition at line 38 of file hologram.c.
Referenced by SetOnGround().
SMALL_PROJECTION_RADIUS
protected const float Hologram::SMALL_PROJECTION_RADIUS = 1 private
Definition at line 37 of file hologram.c.
Referenced by GetProjectionEntityPosition().
SPAWN_FLAGS
protected const int Hologram::SPAWN_FLAGS = ECE_LOCAL private
Definition at line 6 of file hologram.c.
Referenced by CreateTrigger().
SUFFIX_MATERIAL_DEPLOYABLE
protected const string Hologram::SUFFIX_MATERIAL_DEPLOYABLE = "_deployable.rvmat" private
Definition at line 9 of file hologram.c.
Referenced by CorrectMaterialPathName().
SUFFIX_MATERIAL_POWERED
protected const string Hologram::SUFFIX_MATERIAL_POWERED = "_powered.rvmat" private
Definition at line 11 of file hologram.c.
Referenced by CorrectMaterialPathName().
SUFFIX_MATERIAL_UNDEPLOYABLE
protected const string Hologram::SUFFIX_MATERIAL_UNDEPLOYABLE = "_undeployable.rvmat" private
Definition at line 10 of file hologram.c.
Referenced by CorrectMaterialPathName().