DayzKode: DayZIntroScenePC Class Reference
DayZIntroScenePC Class Reference
Private Member Functions
void CharacterRotate ()
void CharacterRotationStart ()
void CharacterRotationStop ()
void DayZIntroScenePC ()
bool IsClickEnabled ()
bool IsRotatingCharacter ()
void SetClickEnable (bool enable)
protected override void SetInitPostprocesses ()
void Update ()
Private Attributes
protected float m_Angle
protected float m_Angle_offset = 0
protected float m_BlurValue
protected float m_DeltaX
protected float m_DeltaZ
protected float m_DiffX
protected bool m_EnableClick
protected float m_NewX = 0
protected float m_NewZ = 0
protected ref OptionsMenu m_optmenu
protected float m_Radius
protected float m_Radius_original
protected bool m_RotatingCharacter
protected int m_RotatingCharacterMouseX
protected int m_RotatingCharacterMouseY
protected float m_RotatingCharacterRot
Detailed Description
Definition at line 1 of file dayzintroscenepc.c.
Constructor & Destructor Documentation
DayZIntroScenePC()
void DayZIntroScenePC::DayZIntroScenePC () inline private
Definition at line 22 of file dayzintroscenepc.c.
    {
        SetClickEnable( true );
        m_DeltaX = Math.AbsFloat(m_CharacterPos[0] - m_Camera.GetPosition()[0]);
        m_DeltaZ = Math.AbsFloat(m_CharacterPos[2] - m_Camera.GetPosition()[2]);
        if (!m_Radius || m_Radius == 0)
        {
            m_Radius = Math.Sqrt (Math.Pow(m_DeltaX, 2) + Math.Pow(m_DeltaZ, 2));
            m_Radius_original = m_Radius;
        }
    }
References Math::AbsFloat(), DayZIntroScene::m_Camera, DayZIntroScene::m_CharacterPos, m_DeltaX, m_DeltaZ, m_Radius, m_Radius_original, Math::Pow(), SetClickEnable(), and Math::Sqrt().
Member Function Documentation
CharacterRotate()
void DayZIntroScenePC::CharacterRotate () inline private
Definition at line 86 of file dayzintroscenepc.c.
    {
        if (m_Character && m_Character.GetCharacterObj())
        {
            int actual_mouse_x;
            int actual_mouse_y;
            float coef;
            g_Game.GetMousePos(actual_mouse_x, actual_mouse_y);
            m_DiffX = m_RotatingCharacterMouseX - actual_mouse_x;
            coef = ( m_RotatingCharacterRot + (m_DiffX * 0.5) ) / 360;
            coef = coef - Math.Floor(coef);
            m_CharacterRot[0] = coef * 360;
            m_Character.GetCharacterObj().SetOrientation(m_CharacterRot);
        }
    }
References Math::Floor(), g_Game, DayZIntroScene::m_Character, DayZIntroScene::m_CharacterRot, m_DiffX, m_RotatingCharacterMouseX, and m_RotatingCharacterRot.
Referenced by Update().
CharacterRotationStart()
void DayZIntroScenePC::CharacterRotationStart () inline private
Definition at line 59 of file dayzintroscenepc.c.
    {
        m_RotatingCharacter = true;
        g_Game.GetMousePos(m_RotatingCharacterMouseX, m_RotatingCharacterMouseY);
        if (m_Character)
        {
            m_RotatingCharacterRot = m_CharacterRot[0];
        }
    }
References g_Game, DayZIntroScene::m_Character, DayZIntroScene::m_CharacterRot, m_RotatingCharacter, m_RotatingCharacterMouseX, m_RotatingCharacterMouseY, and m_RotatingCharacterRot.
Referenced by UIScriptedMenu::OnMouseButtonDown().
CharacterRotationStop()
void DayZIntroScenePC::CharacterRotationStop () inline private
Definition at line 71 of file dayzintroscenepc.c.
    {
        if (m_RotatingCharacter)
        {
            m_RotatingCharacter = false;
        }
    }
References m_RotatingCharacter.
Referenced by UIScriptedMenu::OnMouseButtonUp().
IsClickEnabled()
bool DayZIntroScenePC::IsClickEnabled () inline private
Definition at line 53 of file dayzintroscenepc.c.
    {
        return m_EnableClick;
    }
References m_EnableClick.
IsRotatingCharacter()
bool DayZIntroScenePC::IsRotatingCharacter () inline private
Definition at line 80 of file dayzintroscenepc.c.
    {
        return m_RotatingCharacter;
    }
References m_RotatingCharacter.
SetClickEnable()
void DayZIntroScenePC::SetClickEnable (bool enable) inline private
Definition at line 47 of file dayzintroscenepc.c.
    {
        m_EnableClick = enable;
    }
References m_EnableClick.
Referenced by DayZIntroScenePC().
SetInitPostprocesses()
protected override void DayZIntroScenePC::SetInitPostprocesses () inline private
Definition at line 36 of file dayzintroscenepc.c.
    {
        super.SetInitPostprocesses();
        PPERequester_MenuEffects requester;
        Class.CastTo(requester,PPERequesterBank.GetRequester(PPERequester_MenuEffects));
        requester.SetVignetteIntensity(0.5);
    }
References Class::CastTo().
Update()
void DayZIntroScenePC::Update () inline private
Definition at line 106 of file dayzintroscenepc.c.
    {
        if (m_Character && m_RotatingCharacter)
        {
            CharacterRotate();
        }
    }
References CharacterRotate(), DayZIntroScene::m_Character, and m_RotatingCharacter.
Member Data Documentation
m_Angle
protected float DayZIntroScenePC::m_Angle private
Definition at line 13 of file dayzintroscenepc.c.
m_Angle_offset
protected float DayZIntroScenePC::m_Angle_offset = 0 private
Definition at line 14 of file dayzintroscenepc.c.
m_BlurValue
protected float DayZIntroScenePC::m_BlurValue private
Definition at line 17 of file dayzintroscenepc.c.
m_DeltaX
protected float DayZIntroScenePC::m_DeltaX private
Definition at line 11 of file dayzintroscenepc.c.
Referenced by DayZIntroScenePC().
m_DeltaZ
protected float DayZIntroScenePC::m_DeltaZ private
Definition at line 12 of file dayzintroscenepc.c.
Referenced by DayZIntroScenePC().
m_DiffX
protected float DayZIntroScenePC::m_DiffX private
Definition at line 10 of file dayzintroscenepc.c.
Referenced by CharacterRotate().
m_EnableClick
protected bool DayZIntroScenePC::m_EnableClick private
Definition at line 3 of file dayzintroscenepc.c.
Referenced by IsClickEnabled(), and SetClickEnable().
m_NewX
protected float DayZIntroScenePC::m_NewX = 0 private
Definition at line 15 of file dayzintroscenepc.c.
m_NewZ
protected float DayZIntroScenePC::m_NewZ = 0 private
Definition at line 16 of file dayzintroscenepc.c.
m_optmenu
protected ref OptionsMenu DayZIntroScenePC::m_optmenu private
Definition at line 19 of file dayzintroscenepc.c.
m_Radius
protected float DayZIntroScenePC::m_Radius private
Definition at line 8 of file dayzintroscenepc.c.
Referenced by DayZIntroScenePC().
m_Radius_original
protected float DayZIntroScenePC::m_Radius_original private
Definition at line 9 of file dayzintroscenepc.c.
Referenced by DayZIntroScenePC().
m_RotatingCharacter
protected bool DayZIntroScenePC::m_RotatingCharacter private
Definition at line 4 of file dayzintroscenepc.c.
Referenced by CharacterRotationStart(), CharacterRotationStop(), IsRotatingCharacter(), and Update().
m_RotatingCharacterMouseX
protected int DayZIntroScenePC::m_RotatingCharacterMouseX private
Definition at line 5 of file dayzintroscenepc.c.
Referenced by CharacterRotate(), and CharacterRotationStart().
m_RotatingCharacterMouseY
protected int DayZIntroScenePC::m_RotatingCharacterMouseY private
Definition at line 6 of file dayzintroscenepc.c.
Referenced by CharacterRotationStart().
m_RotatingCharacterRot
protected float DayZIntroScenePC::m_RotatingCharacterRot private
Definition at line 7 of file dayzintroscenepc.c.
Referenced by CharacterRotate(), and CharacterRotationStart().