DayzKode: DoubleBarrel_Base Class Reference
DoubleBarrel_Base Class Reference
Private Member Functions
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override void InitStateMachine ()
override void SetActions ()
Private Attributes
ref WeaponStateBase E_E
ref WeaponStateBase E_F
ref WeaponStateBase E_L
ref WeaponStateBase F_E
ref WeaponStateBase F_F
ref WeaponStateBase F_L
ref WeaponStateBase L_E
ref WeaponStateBase L_L
Detailed Description
Definition at line 119 of file doublebarrel_base.c.
Member Function Documentation
CanChamberBullet()
override bool DoubleBarrel_Base::CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 299 of file doublebarrel_base.c.
    {
        for(int i = 0; i < GetMuzzleCount(); i++)
        {
            if( CanChamberFromMag(i, mag) )
            {
                if(IsChamberEmpty(i))
                    return true;
                if(IsChamberFiredOut(i))
                    return true;
            }
        }
        return false;
    }
References IsChamberFiredOut().
InitStateMachine()
override void DoubleBarrel_Base::InitStateMachine () inline private
Definition at line 130 of file doublebarrel_base.c.
    {
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_END));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_1));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_2));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_3));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_4));
        // setup abilities
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY));
        // basic weapon states
        L_L = new DoubleBarrelLoadedLoaded(this, NULL, DoubleBarrelAnimState.DEFAULT);
        L_E = new DoubleBarrelLoadedEmpty(this, NULL, DoubleBarrelAnimState.DEFAULT);
        E_L = new DoubleBarrelEmptyLoaded(this, NULL, DoubleBarrelAnimState.DEFAULT);
        F_L = new DoubleBarrelFireoutLoaded(this, NULL, DoubleBarrelAnimState.DEFAULT);
        F_F = new DoubleBarrelFireoutFireout(this, NULL, DoubleBarrelAnimState.DEFAULT);
        F_E = new DoubleBarrelFireoutEmpty(this, NULL, DoubleBarrelAnimState.DEFAULT);
        E_F = new DoubleBarrelEmptyFireout(this, NULL, DoubleBarrelAnimState.DEFAULT);
        E_E = new DoubleBarrelEmptyEmpty(this, NULL, DoubleBarrelAnimState.DEFAULT);
        WeaponStateBase     Mech = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
        ChamberMultiBullet  Chamber_E = new ChamberMultiBullet(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_2,WeaponActionChamberingTypes.CHAMBERING_END);
        ChamberMultiBullet  Chamber_L_E = new ChamberMultiBullet(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_3,WeaponActionChamberingTypes.CHAMBERING_END);
        ChamberMultiBullet  Chamber_F_L = new ChamberMultiBullet(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_4,WeaponActionChamberingTypes.CHAMBERING_END);
        ChamberMultiBullet  Chamber_E_L = new ChamberMultiBullet(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_DOUBLE_1,WeaponActionChamberingTypes.CHAMBERING_END);
        WeaponStateBase     Unjam_J = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START);
        WeaponStateBase     Trigger_L_E = new WeaponFireMultiMuzzle(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase     Trigger_E_L = new WeaponFireMultiMuzzle(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase     Trigger_F_L = new WeaponFireMultiMuzzle(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase     Trigger_L_L = new WeaponFireMultiMuzzle(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase     Trigger_F_F = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
        WeaponStateBase     Trigger_F_E = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
        WeaponStateBase     Trigger_E_F = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
        WeaponStateBase     Trigger_E_E = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_DRY);
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
        WeaponEventBase __T__ = new WeaponEventTrigger;
        //WeaponEventBase __U__ = new WeaponEventUnjam;
        WeaponEventBase __M__ = new WeaponEventMechanism;
        WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
        WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
        WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
        m_fsm = new WeaponFSM();
        m_fsm.AddTransition(new WeaponTransition( E_E,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( L_L,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( L_E,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( E_L,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( F_L,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( F_F,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( F_E,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition( E_F,          __M__,  Mech));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _fin_,  E_E));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  F_F, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  F_E, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberEmpty(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  E_F, NULL, new GuardAnd( new WeaponGuardChamberEmpty(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  F_L, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  L_L, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  L_E, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberEmpty(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  E_L, NULL, new GuardAnd( new WeaponGuardChamberEmpty(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  E_E));
        m_fsm.AddTransition(new WeaponTransition( F_F,          __L__,  Chamber_E));
        m_fsm.AddTransition(new WeaponTransition( F_E,          __L__,  Chamber_E));
        m_fsm.AddTransition(new WeaponTransition( E_F,          __L__,  Chamber_E));
        m_fsm.AddTransition(new WeaponTransition( E_E,          __L__,  Chamber_E));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _fin_,  L_E, NULL, new WeaponGuardChamberEmpty(this, MuzzleIndex.Second)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _fin_,  L_L));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  F_F, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  F_E, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberEmpty(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  E_F, NULL, new GuardAnd( new WeaponGuardChamberEmpty(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  L_L, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  L_E, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberEmpty(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  E_E));
        m_fsm.AddTransition(new WeaponTransition( L_E,          __L__,  Chamber_L_E));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_L_E, _abt_,  L_L, NULL, new WeaponGuardChamberFull(this, MuzzleIndex.Second)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_L_E, _abt_,  L_E));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_L_E, _fin_,  L_L, NULL, new WeaponGuardChamberFull(this, MuzzleIndex.Second)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_L_E, _fin_,  L_E));
        m_fsm.AddTransition(new WeaponTransition( E_L,          __L__,  Chamber_E_L));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E_L, _abt_,  L_L, NULL, new WeaponGuardChamberFull(this, MuzzleIndex.First)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E_L, _abt_,  E_L));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E_L, _fin_,  L_L, NULL, new WeaponGuardChamberFull(this, MuzzleIndex.First)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E_L, _fin_,  E_L));
        m_fsm.AddTransition(new WeaponTransition( F_L,          __L__,  Chamber_F_L));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _abt_,  F_L, NULL, new WeaponGuardChamberFiredOut(this, MuzzleIndex.First)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _abt_,  L_L, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _abt_,  E_L, NULL, new GuardAnd( new WeaponGuardChamberEmpty(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _abt_,  L_E));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _fin_,  F_L, NULL, new WeaponGuardChamberFiredOut(this, MuzzleIndex.First)));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _fin_,  L_L, NULL, new GuardAnd( new WeaponGuardChamberFull(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _fin_,  E_L, NULL, new GuardAnd( new WeaponGuardChamberEmpty(this, MuzzleIndex.First), new WeaponGuardChamberFull(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_F_L, _fin_,  L_E));
        m_fsm.AddTransition(new WeaponTransition( L_E,          __T__,  Trigger_L_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_E, _fin_,  F_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_E, _rto_,  F_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_E, _abt_,  F_E));
        m_fsm.AddTransition(new WeaponTransition( E_L,          __T__,  Trigger_E_L));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_L, _fin_,  E_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_L, _rto_,  E_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_L, _abt_,  E_F));
        m_fsm.AddTransition(new WeaponTransition( F_L,          __T__,  Trigger_F_L));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_L, _fin_,  F_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_L, _rto_,  F_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_L, _abt_,  F_F));
        m_fsm.AddTransition(new WeaponTransition( L_L,          __T__,  Trigger_L_L));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _fin_,  F_F, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _rto_,  F_F, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _abt_,  F_F, NULL, new GuardAnd( new WeaponGuardChamberFiredOut(this, MuzzleIndex.First), new WeaponGuardChamberFiredOut(this, MuzzleIndex.Second))));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _fin_,  F_L));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _rto_,  F_L));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_L_L, _abt_,  F_L));
        m_fsm.AddTransition(new WeaponTransition( F_F,          __T__,  Trigger_F_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_F, _fin_,  F_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_F, _dto_,  F_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_F, _abt_,  F_F));
        m_fsm.AddTransition(new WeaponTransition( F_E,          __T__,  Trigger_F_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_E, _fin_,  F_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_E, _dto_,  F_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_F_E, _abt_,  F_E));
        m_fsm.AddTransition(new WeaponTransition( E_F,          __T__,  Trigger_E_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_F, _fin_,  E_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_F, _dto_,  E_F));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_F, _abt_,  E_F));
        m_fsm.AddTransition(new WeaponTransition( E_E,          __T__,  Trigger_E_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_E, _fin_,  E_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_E, _dto_,  E_E));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_E_E, _abt_,  E_E));
        m_fsm.SetInitialState(E_E);
        for(int i = 0; i < GetMuzzleCount(); i++)
        {
            HideBullet(i);
        }
        m_fsm.Start();
    }
References ChamberMultiBullet(), E_E, E_F, E_L, F_E, F_F, F_L, L_E, and L_L.
SetActions()
override void DoubleBarrel_Base::SetActions () inline private
Definition at line 315 of file doublebarrel_base.c.
    {
        super.SetActions();
        AddAction(FirearmActionLoadMultiBullet);
        RemoveAction(FirearmActionLoadBulletQuick); // Easy reload
        AddAction(FirearmActionLoadMultiBulletQuick); // Easy reload
    }
References AddAction(), and RemoveAction().
Member Data Documentation
E_E
ref WeaponStateBase DoubleBarrel_Base::E_E private
Definition at line 128 of file doublebarrel_base.c.
Referenced by InitStateMachine().
E_F
ref WeaponStateBase DoubleBarrel_Base::E_F private
Definition at line 127 of file doublebarrel_base.c.
Referenced by InitStateMachine().
E_L
ref WeaponStateBase DoubleBarrel_Base::E_L private
Definition at line 123 of file doublebarrel_base.c.
Referenced by InitStateMachine().
F_E
ref WeaponStateBase DoubleBarrel_Base::F_E private
Definition at line 126 of file doublebarrel_base.c.
Referenced by InitStateMachine().
F_F
ref WeaponStateBase DoubleBarrel_Base::F_F private
Definition at line 125 of file doublebarrel_base.c.
Referenced by InitStateMachine().
F_L
ref WeaponStateBase DoubleBarrel_Base::F_L private
Definition at line 124 of file doublebarrel_base.c.
Referenced by InitStateMachine().
L_E
ref WeaponStateBase DoubleBarrel_Base::L_E private
Definition at line 122 of file doublebarrel_base.c.
Referenced by InitStateMachine().
L_L
ref WeaponStateBase DoubleBarrel_Base::L_L private
Definition at line 121 of file doublebarrel_base.c.
Referenced by InitStateMachine().