DayzKode: Grenade_ChemGas Class Reference
Grenade_ChemGas Class Reference
Private Member Functions
override protected void Activate ()
override void EEKilled (Object killer)
override void EOnContact (IEntity other, Contact extra)
protected string GetExplosionSoundSet ()
void Grenade_ChemGas ()
override void OnDamageDestroyed (int oldLevel)
override protected void OnExplode ()
void ~Grenade_ChemGas ()
Private Attributes
protected bool m_Exploded
protected EffectSound m_ExplosionSound
protected ParticleSource m_ParticleExploded
Detailed Description
Definition at line 1 of file grenade_chemgas.c.
Constructor & Destructor Documentation
Grenade_ChemGas()
void Grenade_ChemGas::Grenade_ChemGas () inline private
Definition at line 8 of file grenade_chemgas.c.
    {
        SetParticleExplosion(ParticleList.RGD5);
        SetGrenadeType(EGrenadeType.CHEMICAL);
        m_Pinned = false;
        SetPinnable(false);
        Arm();
    }
References Arm(), Grenade_Base::m_Pinned, ParticleList::RGD5, Grenade_Base::SetGrenadeType(), SetParticleExplosion(), and Grenade_Base::SetPinnable().
~Grenade_ChemGas()
void Grenade_ChemGas::~Grenade_ChemGas () private
Member Function Documentation
Activate()
override protected void Grenade_ChemGas::Activate () inline private
Definition at line 66 of file grenade_chemgas.c.
    {
        //we don't want base functionality here
    }
EEKilled()
override void Grenade_ChemGas::EEKilled (Object killer) inline private
Definition at line 47 of file grenade_chemgas.c.
    {
        super.EEKilled(killer);
    }
EOnContact()
override void Grenade_ChemGas::EOnContact (IEntity other, Contact extra) inline private
Definition at line 34 of file grenade_chemgas.c.
    {
        super.EOnContact(other, extra);
        if (GetGame().IsServer())
        {
            if (!m_Exploded)
            {
                OnActivateFinished();
            }
        }
    }
References GetGame(), m_Exploded, and Grenade_Base::OnActivateFinished().
GetExplosionSoundSet()
protected string Grenade_ChemGas::GetExplosionSoundSet () inline private
Definition at line 29 of file grenade_chemgas.c.
    {
        return "Grenade_detonation_SoundSet";
    }
Referenced by OnDamageDestroyed().
OnDamageDestroyed()
override void Grenade_ChemGas::OnDamageDestroyed (int oldLevel) inline private
Definition at line 52 of file grenade_chemgas.c.
    {
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(Delete, 1000);
        }
        #ifndef SERVER
        ClearFlags(EntityFlags.VISIBLE, false);
        m_ParticleExploded = ParticleManager.GetInstance().PlayInWorld(ParticleList.GRENADE_CHEM_BREAK, GetPosition());
        PlaySoundSet( m_ExplosionSound, GetExplosionSoundSet(), 0, 0 );
        #endif
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ClearFlags(), Delete(), CGame::GetCallQueue(), GetExplosionSoundSet(), GetGame(), GetPosition, ParticleList::GRENADE_CHEM_BREAK, m_ExplosionSound, m_ParticleExploded, ParticleManager(), and PlaySoundSet().
OnExplode()
override protected void Grenade_ChemGas::OnExplode () inline private
Definition at line 19 of file grenade_chemgas.c.
    {
        m_Exploded = true;
        if (GetGame().IsServer())
        {
            GetGame().CreateObject("ContaminatedArea_Local", GetPosition());
        }
    }
References CGame::CreateObject(), GetGame(), GetPosition, and m_Exploded.
Member Data Documentation
m_Exploded
protected bool Grenade_ChemGas::m_Exploded private
Definition at line 3 of file grenade_chemgas.c.
Referenced by EOnContact(), and OnExplode().
m_ExplosionSound
protected EffectSound Grenade_ChemGas::m_ExplosionSound private
Definition at line 5 of file grenade_chemgas.c.
Referenced by OnDamageDestroyed().
m_ParticleExploded
protected ParticleSource Grenade_ChemGas::m_ParticleExploded private
Definition at line 4 of file grenade_chemgas.c.
Referenced by OnDamageDestroyed().