DayzKode: ActionMeasureTemperatureTarget Class Reference
ActionMeasureTemperatureTarget Class Reference
Private Member Functions
void ActionMeasureTemperatureTarget ()
override void CreateConditionComponents ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionmeasuretemperaturetarget.c.
Constructor & Destructor Documentation
ActionMeasureTemperatureTarget()
void ActionMeasureTemperatureTarget::ActionMeasureTemperatureTarget () inline private
Definition at line 11 of file actionmeasuretemperaturetarget.c.
    {
        m_CallbackClass = ActionMeasureTemperatureTargetCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_SALINEBLOODBAGTARGET;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_Text = "#measure_persons_temperature";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateConditionComponents()
override void ActionMeasureTemperatureTarget::CreateConditionComponents () inline private
Definition at line 21 of file actionmeasuretemperaturetarget.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressClient()
override void ActionMeasureTemperatureTarget::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 27 of file actionmeasuretemperaturetarget.c.
    {
        PlayerBase ntarget = PlayerBase.Cast( action_data.m_Target.GetObject() );
        Thermometer thermometer = Thermometer.Cast(action_data.m_MainItem);
        if(thermometer)
        {
            ntarget.SetLastUAMessage("" + thermometer.GetTemperatureValue(ntarget).ToString() + "#degrees_celsius");
        }
    }
References ActionData::m_MainItem, and ActionData::m_Target.
Referenced by OnFinishProgressServer().
OnFinishProgressServer()
override void ActionMeasureTemperatureTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 38 of file actionmeasuretemperaturetarget.c.
    {
        if (!GetGame().IsMultiplayer())
        {
            OnFinishProgressClient(action_data);
            return;
        }
        PlayerBase ntarget = PlayerBase.Cast( action_data.m_Target.GetObject() );
        Thermometer thermometer = Thermometer.Cast(action_data.m_MainItem);
        if(thermometer)
        {
            ScriptRPC rpc = new ScriptRPC();
            rpc.Write(thermometer.GetTemperatureValue(ntarget));
            rpc.Send(ntarget, ERPCs.RPC_SYNC_THERMOMETER, true, ntarget.GetIdentity() );
        }
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Target, OnFinishProgressClient(), ScriptRPC::Send(), and Serializer::Write().