DayzKode: CheckLocalisationPlugin Class Reference
CheckLocalisationPlugin Class Reference
Private Member Functions
void CheckTextIDs (string file)
void FindTexts (WidgetSource src)
override void Run ()
Private Attributes
WBModuleDef m_module
ref array< string > m_results = new array<string>
Detailed Description
Definition at line 2 of file checkloctool.c.
Member Function Documentation
CheckTextIDs()
void CheckLocalisationPlugin::CheckTextIDs (string file) inline private
Definition at line 27 of file checkloctool.c.
    {
        m_module.SetOpenedResource(file);
        WidgetSource cont = m_module.GetContainer();
        int lastIndex = m_results.Count();
        FindTexts(cont);
        if (lastIndex != m_results.Count())
        {
            m_results.InsertAt(file + ":", lastIndex);
            m_results.Insert("");
        }
    }
References WBModuleDef::GetContainer(), and WBModuleDef::SetOpenedResource().
FindTexts()
void CheckLocalisationPlugin::FindTexts (WidgetSource src) inline private
Definition at line 7 of file checkloctool.c.
    {
        if (src)
        {
            int idx = src.VarIndex("text");
            if (idx != -1)
            {
                string text;
                if (src.Get(idx, text) && !text.Contains("#"))
                {
                    m_results.Insert("Text = \"" + text + "\" in Widget: " + src.GetName());
                }
            }
            FindTexts(src.GetChildren());
            FindTexts(src.GetSibling());
        }
    }
References string::Contains(), BaseContainer::Get(), WidgetSource::GetChildren(), BaseContainer::GetName(), WidgetSource::GetSibling(), and BaseContainer::VarIndex().
Run()
override void CheckLocalisationPlugin::Run () inline private
Definition at line 40 of file checkloctool.c.
    {
        m_module = Workbench.GetModule("ResourceManager");
        Workbench.SearchResources(".layout", CheckTextIDs);
        if (m_results.Count())
        {
            string res;
            foreach(string file: m_results)
            {
                res += file;
                res += "\n";
            }
        }
        else
        {
            res = "All texts are localised.";
        }
        Workbench.Dialog("Results", res);
    }
References Workbench::Dialog(), Workbench::GetModule(), and Workbench::SearchResources().
Member Data Documentation
m_module
WBModuleDef CheckLocalisationPlugin::m_module private
Definition at line 5 of file checkloctool.c.
m_results
ref array<string> CheckLocalisationPlugin::m_results = new array<string> private
Definition at line 4 of file checkloctool.c.