DayzKode: ServerBrowserTabConsolePages Class Reference
ServerBrowserTabConsolePages Class Reference
Private Member Functions
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
protected override void LoadEntries (int cur_page_index, GetServersResultRowArray page_entries)
protected override void LoadExtraEntries (int index)
override void OnLoadServersAsyncFinished ()
override bool PassFilter (GetServersResultRow result)
override void PressX ()
override void PressY ()
override void RefreshList ()
override void SetFocusFilters ()
Detailed Description
Definition at line 1 of file serverbrowserfavoritestabconsolepages.c.
Member Function Documentation
Construct()
protected override void ServerBrowserTabConsolePages::Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 3 of file serverbrowserfavoritestabconsolepages.c.
    {
        super.Construct(parent, menu, type);
        // disabling filter section
        m_Root.FindAnyWidget("filters_content").Show(false);
        m_Root.FindAnyWidget("reset_filter_button").Show(false);
    }
References m_Root.
LoadEntries()
protected override void ServerBrowserTabConsolePages::LoadEntries (int cur_page_index, GetServersResultRowArray page_entries) inline private
Definition at line 20 of file serverbrowserfavoritestabconsolepages.c.
    {
        if (cur_page_index == 1)
        {
            m_OnlineFavServers.Clear();
        }
        super.LoadEntries(cur_page_index, page_entries);
    }
References m_OnlineFavServers.
Referenced by ServerBrowserTab::OnLoadServersAsyncConsole().
LoadExtraEntries()
protected override void ServerBrowserTabConsolePages::LoadExtraEntries (int index) inline private
Definition at line 30 of file serverbrowserfavoritestabconsolepages.c.
    {
        if ( !m_Menu || m_Menu.GetServersLoadingTab() != m_TabType )
        {
            return;
        }
        // m_PagesCount for FAVORITES tab is determined by total number of favorited servers
        TStringArray favIds = m_Menu.GetFavoritedServerIds();
        m_PagesCount = Math.Ceil((float)favIds.Count() /  SERVER_BROWSER_PAGE_SIZE);
        // offlineFavIds will always have same order, even across pages,
        // to ensure we display only fav servers that HAVEN'T been displayed yet
        TStringArray offlineFavIds = new TStringArray();
        offlineFavIds.Reserve(favIds.Count() - m_OnlineFavServers.Count());
        foreach (string ipPort : favIds)
        {
            if (m_OnlineFavServers.Find(ipPort) == -1)
            {
                offlineFavIds.Insert(ipPort);
            }
        }
        // appending offline servers to server list
        int totalServersAlreadyShown = (GetCurrentPage() - 1) * SERVER_BROWSER_PAGE_SIZE + index;
        int startingIndex = totalServersAlreadyShown - m_OnlineFavServers.Count();
        for (int i = startingIndex; i < offlineFavIds.Count(); ++i)
        {
            string favServerId = offlineFavIds[i];
            // only append server if there is a free entry left on the page
            if (index >= SERVER_BROWSER_PAGE_SIZE)
            {
                break;
            }
            if (m_OnlineFavServers.Find(favServerId) > -1)
            {
                continue;
            }
            array<string> parts = new array<string>;
            favServerId.Split(":", parts);
            GetServersResultRow offlineRow = new GetServersResultRow();
            offlineRow.m_Name = favServerId;
            offlineRow.m_Id = favServerId;
            offlineRow.m_HostIp = parts[0];
            offlineRow.m_HostPort = parts[1].ToInt();
            offlineRow.m_SteamQueryPort = offlineRow.m_HostPort;
            offlineRow.m_Favorite = true;
            ServerBrowserEntry entry = GetServerEntryByIndex( index );
            entry.FillInfo(offlineRow);
            entry.SetIsOnline(false);
            entry.UpdateEntry();
            m_EntryWidgets.Insert(favServerId, entry);
            m_EntriesSorted[m_SortType].Insert(offlineRow);
            index++;
        }
    }
References Math::Ceil(), GetCurrentPage(), m_EntriesSorted, m_EntryWidgets, m_Menu, m_OnlineFavServers, m_SortType, m_TabType, SERVER_BROWSER_PAGE_SIZE, and string::Split().
Referenced by ServerBrowserTab::LoadEntries().
OnLoadServersAsyncFinished()
override void ServerBrowserTabConsolePages::OnLoadServersAsyncFinished () inline private
Definition at line 12 of file serverbrowserfavoritestabconsolepages.c.
    {
        // m_TotalLoadedServers for FAVORITES tab is determined by total number of favorited servers
        TStringArray favIds = m_Menu.GetFavoritedServerIds();
        m_TotalLoadedServers = favIds.Count();
        super.OnLoadServersAsyncFinished();
    }
References m_Menu, and m_TotalLoadedServers.
Referenced by ServerBrowserTab::OnLoadServersAsyncConsole().
PassFilter()
override bool ServerBrowserTabConsolePages::PassFilter (GetServersResultRow result) inline private
Definition at line 104 of file serverbrowserfavoritestabconsolepages.c.
    {
        if (m_TabType == TabType.FAVORITE)
        {
            if (!m_Menu.IsFavorited(result.GetIpPort()))
            {
                return false;
            }
        }
        return super.PassFilter(result);
    }
References m_Menu, and m_TabType.
Referenced by ServerBrowserTab::LoadEntries().
PressX()
override void ServerBrowserTabConsolePages::PressX () inline private
Definition at line 134 of file serverbrowserfavoritestabconsolepages.c.
    {
        if ( (GetGame().GetTime() - m_TimeLastServerRefresh) > 1000 )
        {
            SetCurrentPage(1);
            super.PressX();
        }
    }
References GetGame(), GetTime(), and SetCurrentPage().
Referenced by ServerBrowserTab::OnClick().
PressY()
override void ServerBrowserTabConsolePages::PressY () inline private
Definition at line 117 of file serverbrowserfavoritestabconsolepages.c.
    {
        switch ( m_SelectedPanel )
        {
            // filters are disabled for console FAVORITES tab, so do nothing
            case SelectedPanel.FILTERS:
            {
                break;
            }
            default:
            {
                super.PressY();
                break;
            }
        }
    }
References m_SelectedPanel.
RefreshList()
override void ServerBrowserTabConsolePages::RefreshList () inline private
Definition at line 94 of file serverbrowserfavoritestabconsolepages.c.
    {
        super.RefreshList();
#ifdef PLATFORM_WINDOWS
        m_CurrentFilterInput.SetFavorited( true );
#endif
        AddFavoritesToFilter(m_CurrentFilterInput);
        OnlineServices.LoadServers(m_CurrentFilterInput);
    }
References AddFavoritesToFilter(), OnlineServices::LoadServers(), m_CurrentFilterInput, and GetServersInput::SetFavorited().
Referenced by ServerBrowserTab::ApplyFilters(), ServerBrowserTab::LeftRelease(), ServerBrowserTab::OnClick(), ServerBrowserTab::PressX(), and ServerBrowserTab::RightRelease().
SetFocusFilters()
override void ServerBrowserTabConsolePages::SetFocusFilters () inline private
Definition at line 143 of file serverbrowserfavoritestabconsolepages.c.
    {
        super.SetFocusFilters();
        m_Menu.ShowYButton(false);
        m_Menu.ShowAButton(false);
        // focus on the back button instead of filter section
        m_Menu.BackButtonFocus();
        UpdatePageButtons();
    }
References m_Menu.
Referenced by ServerBrowserTab::Construct(), ServerBrowserTab::Focus(), ServerBrowserTab::OnLoadServersAsyncConsole(), ServerBrowserTab::PressSholderLeft(), and ServerBrowserTab::PressSholderRight().