DayzKode: AIBehaviourHLZombie2 Class Reference
AIBehaviourHLZombie2 Class Reference
Private Member Functions
private void AIBehaviourHLZombie2 ()
AIBehaviourHLDataZombie2 GetData ()
override void OnInit ()
void ShowDebugInfo ()
override void Simulate (float timeDelta)
private void ~AIBehaviourHLZombie2 ()
Detailed Description
Definition at line 74 of file aibehaviour.c.
Constructor & Destructor Documentation
AIBehaviourHLZombie2()
private void AIBehaviourHLZombie2::AIBehaviourHLZombie2 () inline private
Definition at line 84 of file aibehaviour.c.
{}
~AIBehaviourHLZombie2()
private void AIBehaviourHLZombie2::~AIBehaviourHLZombie2 () inline private
Definition at line 85 of file aibehaviour.c.
{}
Member Function Documentation
GetData()
AIBehaviourHLDataZombie2 AIBehaviourHLZombie2::GetData () inline private
Definition at line 79 of file aibehaviour.c.
    {
        return AIBehaviourHLDataZombie2.Cast( GetTemplateData() );
    }
References GetTemplateData().
OnInit()
override void AIBehaviourHLZombie2::OnInit () inline private
Definition at line 87 of file aibehaviour.c.
    {
        SetNextBehaviour(0x7b9a4ee9);
        SwitchToNextBehaviour();
        //Print("OnInit");
        //data = GetData();
        //float a = data.m_fDamageToCrawl;
        //Print(a);
    }
References SetNextBehaviour(), and SwitchToNextBehaviour().
ShowDebugInfo()
void AIBehaviourHLZombie2::ShowDebugInfo () inline private
Definition at line 103 of file aibehaviour.c.
    {
        //Print(time);
    };
Simulate()
override void AIBehaviourHLZombie2::Simulate (float timeDelta) inline private
Definition at line 97 of file aibehaviour.c.
    {
        //time = time + timeDelta;
        //Print("B2");
    }