DayzKode: CABase Class Reference
CABase Class Reference
Private Member Functions
int Cancel (ActionData action_data)
int Execute (ActionData action_data)
Param GetACData ()
float GetProgress ()
void Init (ActionData action_data)
int Interrupt (ActionData action_data)
bool IsContinuousAction ()
void SetACData (Param units)
void Setup (ActionData action_data)
Private Attributes
protected ref Param m_ACData
protected ActionBase m_Action
protected float m_LastTick
protected ref Param2< float, float > m_ProgressParam
Detailed Description
Definition at line 1 of file cabase.c.
Member Function Documentation
Cancel()
int CABase::Cancel (ActionData action_data) inline private
Definition at line 29 of file cabase.c.
    {
        return UA_CANCEL;
    }
References UA_CANCEL.
Referenced by ActionContinuousBaseCB::UserEndsAction().
Execute()
int CABase::Execute (ActionData action_data) inline private
Definition at line 24 of file cabase.c.
    {
        return UA_ERROR;
    }
References UA_ERROR.
Referenced by ActionBaseCB::ProgressActionComponent().
GetACData()
Param CABase::GetACData () inline private
Definition at line 48 of file cabase.c.
    {
        if ( m_ACData )
        {
            return m_ACData;
        }
        return NULL;
    }
References m_ACData.
Referenced by ActionCollectBloodSelf::OnEndServer(), ActionCollectBloodTarget::OnEndServer(), ActionCollectSampleSelf::OnEndServer(), ActionCollectSampleTarget::OnEndServer(), ActionDisinfectPlantBit::OnExecuteServer(), ActionRepairWithToolFromHands::OnExecuteServer(), ActionDisinfectPlant::OnFinishProgressClient(), ActionWaterPlant::OnFinishProgressClient(), ActionDisinfectPlant::OnFinishProgressServer(), ActionDrinkPondContinuous::OnFinishProgressServer(), ActionDrinkWellContinuous::OnFinishProgressServer(), ActionWaterPlant::OnFinishProgressServer(), ActionGiveSalineSelf::OnFinishProgressServer(), and ActionGiveSalineTarget::OnFinishProgressServer().
GetProgress()
float CABase::GetProgress () inline private
Definition at line 62 of file cabase.c.
    {
        return 0;
    }
Referenced by ActionBaseCB::GetActionComponentProgress(), and AnimatedActionBase::GetProgress().
Init()
void CABase::Init (ActionData action_data) inline private
Definition at line 8 of file cabase.c.
    {
        m_ProgressParam = new Param2<float,float>(0,0);
        m_Action = action_data.m_Action;
        if ( !m_ACData )
        {
            m_ACData = new Param;
        }
        m_LastTick = GetGame().GetTime();
        Setup(action_data);
    }
References GetGame(), CGame::GetTime(), m_ACData, ActionData::m_Action, m_Action, m_LastTick, m_ProgressParam, and Setup().
Referenced by ActionContinuousBaseCB::InitActionComponent(), ActionInteractBaseCB::InitActionComponent(), and ActionSingleUseBaseCB::InitActionComponent().
Interrupt()
int CABase::Interrupt (ActionData action_data) inline private
Definition at line 34 of file cabase.c.
    {
        Cancel( action_data );
        return UA_INTERRUPT;
    }
References Cancel(), and UA_INTERRUPT.
Referenced by ActionUnfoldMapCB::OnFinish(), and ActionBaseCB::OnFinish().
IsContinuousAction()
bool CABase::IsContinuousAction () inline private
Definition at line 57 of file cabase.c.
    {
        return false;
    }
SetACData()
void CABase::SetACData (Param units) inline private
Definition at line 40 of file cabase.c.
    {
        if ( m_ACData )
        {
            m_ACData = units;
        }
    }
References m_ACData.
Referenced by CAContinuousEmpty::CalcAndSetQuantity(), CAContinuousEmptyMagazine::CalcAndSetQuantity(), CAContinuousFill::CalcAndSetQuantity(), CAContinuousFillBrakes::CalcAndSetQuantity(), CAContinuousFillCoolant::CalcAndSetQuantity(), CAContinuousFillFuel::CalcAndSetQuantity(), CAContinuousFillOil::CalcAndSetQuantity(), CAContinuousFillPowerGenerator::CalcAndSetQuantity(), CAContinuousQuantity::CalcAndSetQuantity(), CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), CAContinuousQuantityEdible::CalcAndSetQuantity(), CAContinuousQuantityExtinguish::CalcAndSetQuantity(), CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), CAContinuousQuantityRepeat::CalcAndSetQuantity(), CAContinuousTransferQuantity::CalcAndSetQuantity(), CASingleUseQuantity::CalcAndSetQuantity(), CASingleUseQuantityEdible::CalcAndSetQuantity(), CAContinuousRepeat::Cancel(), CAContinuousTime::Cancel(), CAContinuousCraft::Execute(), CAContinuousMineWood::Execute(), CAContinuousRepeat::Execute(), CAContinuousRepeatFishing::Execute(), CAContinuousRepeatStartEngine::Execute(), CAContinuousTime::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousWringClothes::Execute(), and CAInteractLoop::Execute().
Setup()
void CABase::Setup (ActionData action_data) inline private
Definition at line 20 of file cabase.c.
    {
    }
Referenced by Init().
Member Data Documentation
m_ACData
protected ref Param CABase::m_ACData private
Definition at line 5 of file cabase.c.
Referenced by GetACData(), Init(), and SetACData().
m_Action
protected ActionBase CABase::m_Action private
Definition at line 3 of file cabase.c.
Referenced by CAContinuousDisinfectPlant::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CAContinuousWringClothes::Execute(), CAContinuousMineRock::GetMiningData(), CAContinuousMineWood::GetMiningData(), Init(), CAContinuousEmpty::Setup(), CAContinuousFill::Setup(), CAContinuousFillPowerGenerator::Setup(), CAContinuousMineWood::Setup(), CAContinuousRepeat::Setup(), CAContinuousTime::Setup(), CAContinuousTimeCooking::Setup(), and CAInteractLoop::Setup().
m_LastTick
protected float CABase::m_LastTick private
Definition at line 4 of file cabase.c.
Referenced by Init().
m_ProgressParam
protected ref Param2<float,float> CABase::m_ProgressParam private
Definition at line 6 of file cabase.c.
Referenced by Init().