DayzKode: AmmoEffects Class Reference
AmmoEffects Class Reference
Static data holder for certain ammo config values.
Static Private Member Functions
Ammo particles
Methods regarding getting/playing ammo particle
static int GetAmmoParticleID (string ammoType)
Get the ParticleList ID for the particle for this ammoType.
static bool PlayAmmoParticle (string ammoType, vector pos)
Attempt to play the ammo particle at pos if found, returns true on success.
Ammo effects
Methods regarding getting/playing ammo effect
static GetAmmoEffectTypename (string ammoType)
Get the typename for the effect for this ammoType.
static bool PlayAmmoEffect (string ammoType, vector pos)
Attempt to play the ammo effect at pos if found, returns true on success.
Lifetime
Creation and cleanup
static void Init ()
Initialize the containers: this is done this way, to have these not exist on server.
static void Cleanup ()
Clean up the data.
Static Private Attributes
static ref map< string, typename > m_AmmoEffects
Key: Ammo class name; Data: ParticleList ID.
static ref map< string, int > m_AmmoParticles
Key: Ammo class name; Data: ParticleList ID.
Detailed Description
Static data holder for certain ammo config values.
Note
Kept the names similar to what is in config, but it might be a little deceiving as this is mainly used for explosives
Definition at line 5 of file ammoeffects.c.
Member Function Documentation
Cleanup()
static void AmmoEffects::Cleanup () inline static private
Clean up the data.
Definition at line 128 of file ammoeffects.c.
    {
        /* These ain't containing no refs, so whatever
        m_AmmoParticles.Clear();
        m_AmmoEffects.Clear();
        */
    }
Referenced by CGame::~CGame().
GetAmmoEffectTypename()
static AmmoEffects::GetAmmoEffectTypename (string ammoType) inline static private
Get the typename for the effect for this ammoType.
Definition at line 68 of file ammoeffects.c.
    {
        typename typeName;
        // Search for it in the static map
        if ( !m_AmmoEffects.Find(ammoType, typeName) )
        {
            // Load it in when we can't find it
            string effectName;
            GetGame().ConfigGetText(string.Format("cfgAmmo %1 effect", ammoType), effectName);
            // If we found a valid entry, try looking for it in ParticleList
            if ( effectName != "" )
            {
                typeName = effectName.ToType();
            }
            // Store it for next search
            m_AmmoEffects.Insert(ammoType, typeName);
        }
        return typeName;
    }
References CGame::ConfigGetText(), GetGame(), m_AmmoEffects, and string::ToType().
Referenced by PlayAmmoEffect().
GetAmmoParticleID()
static int AmmoEffects::GetAmmoParticleID (string ammoType) inline static private
Get the ParticleList ID for the particle for this ammoType.
Definition at line 21 of file ammoeffects.c.
    {
        int particleID;
        // Search for it in the static map
        if ( !m_AmmoParticles.Find(ammoType, particleID) )
        {
            // Load it in when we can't find it
            string particleFileName;
            GetGame().ConfigGetText(string.Format("cfgAmmo %1 particle", ammoType), particleFileName);
            // If we found a valid entry, try looking for it in ParticleList
            if ( particleFileName != "" )
            {
                particleID = ParticleList.GetParticleIDByName(particleFileName);
            }
            // Store it for next search
            m_AmmoParticles.Insert(ammoType, particleID);
        }
        return particleID;
    }
References CGame::ConfigGetText(), GetGame(), ParticleList::GetParticleIDByName(), and m_AmmoParticles.
Referenced by PlayAmmoParticle().
Init()
static void AmmoEffects::Init () inline static private
Initialize the containers: this is done this way, to have these not exist on server.
Definition at line 121 of file ammoeffects.c.
    {
        m_AmmoParticles = new map<string, int>();
        m_AmmoEffects = new map<string, typename>();
    }
References m_AmmoEffects, and m_AmmoParticles.
Referenced by CGame::CGame().
PlayAmmoEffect()
static bool AmmoEffects::PlayAmmoEffect (string ammoType, vector pos) inline static private
Attempt to play the ammo effect at pos if found, returns true on success.
Definition at line 93 of file ammoeffects.c.
    {
        typename typeName = GetAmmoEffectTypename(ammoType);
        if ( typeName )
        {
            Effect eff = Effect.Cast(typeName.Spawn());
            if ( eff )
            {
                eff.SetAutodestroy(true);
                return SEffectManager.PlayInWorld( eff, pos );
            }
        }
        return false;
    }
References Effect(), GetAmmoEffectTypename(), and SEffectManager::PlayInWorld().
Referenced by OnExplodeClient().
PlayAmmoParticle()
static bool AmmoEffects::PlayAmmoParticle (string ammoType, vector pos) inline static private
Attempt to play the ammo particle at pos if found, returns true on success.
Definition at line 46 of file ammoeffects.c.
    {
        int particleID = GetAmmoParticleID(ammoType);
        if (ParticleList.IsValidId(particleID))
        {
            return ParticleManager.GetInstance().PlayInWorld(particleID, pos) != null;
        }
        return false;
    }
References GetAmmoParticleID(), ParticleList::IsValidId(), and ParticleManager().
Referenced by OnExplodeClient().
Member Data Documentation
m_AmmoEffects
ref map<string, typename> AmmoEffects::m_AmmoEffects static private
Key: Ammo class name; Data: ParticleList ID.
Definition at line 11 of file ammoeffects.c.
Referenced by GetAmmoEffectTypename(), and Init().
m_AmmoParticles
ref map<string, int> AmmoEffects::m_AmmoParticles static private
Key: Ammo class name; Data: ParticleList ID.
Definition at line 8 of file ammoeffects.c.
Referenced by GetAmmoParticleID(), and Init().