DayzKode: NoiseSystem Class Reference
NoiseSystem Class Reference
Private Member Functions
proto void AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier=1.0)
proto void AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier=1.0)
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
private void NoiseSystem ()
private void ~NoiseSystem ()
Detailed Description
Definition at line 1 of file noise.c.
Constructor & Destructor Documentation
NoiseSystem()
private void NoiseSystem::NoiseSystem () inline private
Definition at line 3 of file noise.c.
{}
~NoiseSystem()
private void NoiseSystem::~NoiseSystem () inline private
Definition at line 4 of file noise.c.
{}
Member Function Documentation
AddNoise()
proto void NoiseSystem::AddNoise (EntityAI source_entity, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
Referenced by AddNoise(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), and DayZInfected::ProcessSoundVoiceEvent().
AddNoisePos()
proto void NoiseSystem::AddNoisePos (EntityAI source_entity, vector pos, NoiseParams noise_params, float external_strenght_multiplier = 1.0) private
Referenced by CloseCombatEffects(), Heating(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), OnWork(), and OnWorkStart().
AddNoiseTarget()
proto void NoiseSystem::AddNoiseTarget (vector pos, float lifetime, NoiseParams noise_params, float external_strength_multiplier = 1.0) private
Will make a noise at that position which the AI will "see" for the duration of 'lifetime'.
Referenced by ExplosionEffectsEx(), FirearmEffects(), GenerateAINoiseAtPosition(), GenerateCarHornAINoise(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().