DayzKode: ActionBuryBody Class Reference
ActionBuryBody Class Reference
Private Member Functions
void ActionBuryBody ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionburybody.c.
Constructor & Destructor Documentation
ActionBuryBody()
void ActionBuryBody::ActionBuryBody () inline private
Definition at line 11 of file actionburybody.c.
    {
        m_CallbackClass     = ActionBuryBodyCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight   = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#bury";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionBuryBody::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 28 of file actionburybody.c.
    {
        if (player.IsPlacingLocal())
        {
            return false;
        }
        EntityAI bodyEAI;
        Class.CastTo(bodyEAI, target.GetObject());
        if (bodyEAI && !bodyEAI.IsAlive() && (bodyEAI.IsInherited(DayZCreature) || bodyEAI.IsInherited(Man) || bodyEAI.IsInherited(DeadChicken_ColorBase) ) && !bodyEAI.GetParent())
        {
            int liquidType;
            string surfaceType;
            GetGame().SurfaceUnderObject(bodyEAI, surfaceType, liquidType);
            if (GetGame().IsSurfaceDigable(surfaceType))
            {
                return true;
            }
        }
        return false;
    }
References Class::CastTo(), GetGame(), and CGame::SurfaceUnderObject().
CreateConditionComponents()
override void ActionBuryBody::CreateConditionComponents () inline private
Definition at line 21 of file actionburybody.c.
    {
        m_ConditionTarget   = new CCTDummy();
        m_ConditionItem     = new CCINonRuined();
    }
References m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void ActionBuryBody::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 53 of file actionburybody.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        g_Game.ObjectDelete(targetObject);
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 4);
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty(m_SpecialtyWeight);
    }
References g_Game, ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.