DayzKode: ActionDetachPowerSourceFromPanel Class Reference
ActionDetachPowerSourceFromPanel Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDetachPowerSourceFromPanel ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
Detailed Description
Definition at line 2 of file actiondetachpowersourcefrompanel.c.
Constructor & Destructor Documentation
ActionDetachPowerSourceFromPanel()
void ActionDetachPowerSourceFromPanel::ActionDetachPowerSourceFromPanel () inline private
Definition at line 4 of file actiondetachpowersourcefrompanel.c.
    {
        m_Text = "#detach_power_source";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool ActionDetachPowerSourceFromPanel::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 9 of file actiondetachpowersourcefrompanel.c.
    {
        Object target_object = target.GetObject();
        if ( player && target_object )
        {
            EntityAI target_entity = EntityAI.Cast( target.GetObject() );
            string selection = target_object.GetActionComponentName( target.GetComponentIndex() );
            if ( target_entity && target_entity.GetInventory() && target_entity.GetInventory().AttachmentCount() > 0 && selection == "power_source" )   //has any power source attachment attached
            {
                return true;
            }
        }
        return false;
    }
OnExecuteClient()
override void ActionDetachPowerSourceFromPanel::OnExecuteClient (ActionData action_data) inline private
Definition at line 28 of file actiondetachpowersourcefrompanel.c.
    {
        Process(action_data);
    }
References Process().
OnExecuteServer()
override void ActionDetachPowerSourceFromPanel::OnExecuteServer (ActionData action_data) inline private
Definition at line 33 of file actiondetachpowersourcefrompanel.c.
    {
        Process(action_data);
    }
References Process().
Process()
void ActionDetachPowerSourceFromPanel::Process (ActionData action_data) inline private
Definition at line 38 of file actiondetachpowersourcefrompanel.c.
    {
        EntityAI target_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        EntityAI attachment;
        int attachments_count = target_entity.GetInventory().AttachmentCount();
        for ( int j = 0; j < attachments_count; j++ )               //find any attached power source
        {
            // @TODO: vezme prvni att?
            attachment = target_entity.GetInventory().GetAttachmentFromIndex( j );
            if ( attachment )
                break;
        }
        if ( attachment )
        {
            action_data.m_Player.PredictiveTakeEntityToHands(attachment );
        }
    }
References ActionData::m_Player, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().