DayzKode: DayZIntroScene Class Reference
DayZIntroScene Class Reference
Private Member Functions
void DayZIntroScene ()
Camera GetIntroCamera ()
IntroSceneCharacter GetIntroCharacter ()
protected void GetSelectedUserName ()
void ResetIntroCamera ()
protected void SetInitPostprocesses ()
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
protected vector SnapToGround (vector pos)
protected vector SwapYZ (vector vec)
void ~DayZIntroScene ()
Private Attributes
protected Camera m_Camera
protected vector m_CameraTrans [4]
protected ref IntroSceneCharacter m_Character
protected vector m_CharacterPos
protected vector m_CharacterRot
protected ref OptionsMenu m_OptionsMenu
protected vector m_Target
protected Weather m_Weather
Detailed Description
Definition at line 1 of file dayzintroscene.c.
Constructor & Destructor Documentation
DayZIntroScene()
void DayZIntroScene::DayZIntroScene () inline private
Definition at line 13 of file dayzintroscene.c.
    {
        World w = g_Game.GetWorld();
        string root_path = "cfgCharacterScenes " + g_Game.GetWorldName();
        int count = g_Game.ConfigGetChildrenCount(root_path);
        int index = Math.RandomInt(0, count - 1);
        string childName;
        g_Game.ConfigGetChildName(root_path, index, childName);
        string scene_path = root_path + " " + childName;
        m_Target = SwapYZ(g_Game.ConfigGetVector(scene_path + " target"));
        vector position = SwapYZ(g_Game.ConfigGetVector(scene_path + " position"));
        TIntArray date = new TIntArray;
        TFloatArray storm = new TFloatArray;
        g_Game.ConfigGetIntArray(scene_path + " date", date);
        float fov = g_Game.ConfigGetFloat(scene_path + " fov");
        float overcast = g_Game.ConfigGetFloat(scene_path + " overcast");
        float rain = g_Game.ConfigGetFloat(scene_path + " rain");
        float fog = g_Game.ConfigGetFloat(scene_path + " fog");
        float windspeed = -1;
        if ( g_Game.ConfigIsExisting(scene_path + " windspeed") )   windspeed = g_Game.ConfigGetFloat(scene_path + " windspeed");
        g_Game.ConfigGetFloatArray(scene_path + " storm", storm);
        World world = g_Game.GetWorld();
        if (world && date.Count() >= 5)
        {
            world.SetDate(date.Get(0), date.Get(1), date.Get(2), date.Get(3), date.Get(4));
        }
        GetGame().ObjectDelete( m_Camera );
        Class.CastTo(m_Camera, g_Game.CreateObject("staticcamera", SnapToGround(position), true)); //Vector(position[0] , position[1] + 1, position[2])
        Math3D.MatrixIdentity4(m_CameraTrans);
        if (m_Camera)
        {
            //m_Camera.SetPosition(Vector(m_Camera.GetPosition()[0],m_Camera.GetPosition()[1]+0,m_Camera.GetPosition()[2]));
            m_Camera.LookAt(m_Target);
            m_Camera.SetFOV(fov);
            m_Camera.SetFocus(5.0, 0.0); //5.0, 1.0
            m_Camera.SetActive(true);
            Math3D.DirectionAndUpMatrix(m_Target - SnapToGround(position), "0 1 0", m_CameraTrans);
            m_CameraTrans[3] = m_Camera.GetPosition();
            m_CharacterPos = Vector(0.685547, -0.988281, 3.68823).Multiply4(m_CameraTrans);
            float pos_x = m_CharacterPos[0];
            float pos_z = m_CharacterPos[2];
            float pos_y = GetGame().SurfaceY(pos_x, pos_z);
            vector ground_demo_pos = Vector(pos_x, pos_y, pos_z);
            m_CharacterPos = ground_demo_pos;
            vector to_cam_dir = m_Camera.GetPosition() - m_CharacterPos;
            m_CharacterRot[0] = Math.Atan2(to_cam_dir[0], to_cam_dir[2]) * Math.RAD2DEG;
        }
        m_Weather = g_Game.GetWeather();
        m_Weather.GetOvercast().SetLimits( overcast, overcast );
        m_Weather.GetRain().SetLimits( rain, rain );
        m_Weather.GetFog().SetLimits( fog, fog );
        m_Weather.GetOvercast().Set( overcast, 0, 0);
        m_Weather.GetRain().Set( rain, 0, 0);
        m_Weather.GetFog().Set( fog, 0, 0);
        if ( storm.Count() == 3 )
        {
            m_Weather.SetStorm(storm.Get(0),storm.Get(1),storm.Get(2));
        }
        if ( windspeed != -1 )
        {
            m_Weather.SetWindSpeed(windspeed);
            m_Weather.SetWindMaximumSpeed(windspeed);
            m_Weather.SetWindFunctionParams(1,1,1);
        }
        m_Character = new IntroSceneCharacter();
        m_Character.LoadCharacterData(m_CharacterPos, m_CharacterRot);
        PPEffects.Init(); //Deprecated, left in for legacy purposes only
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(SetInitPostprocesses);
    }
References Math::Atan2(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, Class::CastTo(), Math3D::DirectionAndUpMatrix(), g_Game, CGame::GetCallQueue(), Weather::GetFog(), GetGame(), Weather::GetOvercast(), Weather::GetRain(), PPEffects::Init(), Managed::IntroSceneCharacter(), m_Camera, m_CameraTrans, m_Character, m_CharacterPos, m_CharacterRot, m_Target, m_Weather, Math3D::MatrixIdentity4(), vector::Multiply4(), CGame::ObjectDelete(), Math::RAD2DEG, Math::RandomInt(), WeatherPhenomenon::Set(), World::SetDate(), SetInitPostprocesses(), WeatherPhenomenon::SetLimits(), Weather::SetStorm(), Weather::SetWindFunctionParams(), Weather::SetWindMaximumSpeed(), Weather::SetWindSpeed(), SnapToGround(), CGame::SurfaceY(), SwapYZ(), and Vector().
~DayZIntroScene()
void DayZIntroScene::~DayZIntroScene () inline private
Definition at line 102 of file dayzintroscene.c.
    {
        if (PPEManagerStatic.GetPPEManager())
            PPEManagerStatic.GetPPEManager().StopAllEffects(PPERequesterCategory.ALL);
    }
References PPEManagerStatic::GetPPEManager().
Member Function Documentation
GetIntroCamera()
Camera DayZIntroScene::GetIntroCamera () inline private
Definition at line 119 of file dayzintroscene.c.
    {
        return m_Camera;
    }
References m_Camera.
Referenced by UIScriptedMenu::OnShow(), and ResetIntroCamera().
GetIntroCharacter()
IntroSceneCharacter DayZIntroScene::GetIntroCharacter () inline private
Definition at line 111 of file dayzintroscene.c.
    {
        return m_Character;
    }
References m_Character.
Referenced by UIScriptedMenu::CanSaveDefaultCharacter(), UIScriptedMenu::ConnectLastSession(), UIScriptedMenu::NextCharacter(), UIScriptedMenu::OnChangeCharacter(), UIScriptedMenu::OnMouseEnter(), UIScriptedMenu::OnShow(), UIScriptedMenu::OpenMenuServerBrowser(), UIScriptedMenu::PreviousCharacter(), and ResetIntroCamera().
GetSelectedUserName()
protected void DayZIntroScene::GetSelectedUserName () inline private
Definition at line 142 of file dayzintroscene.c.
    {
        string name;
        BiosUserManager user_manager = GetGame().GetUserManager();
        if( user_manager )
        {
            BiosUser user = user_manager.GetSelectedUser();
            if( user )
            {
                g_Game.SetPlayerGameName( user.GetName() );
                return;
            }
        }
        g_Game.SetPlayerGameName(GameConstants.DEFAULT_CHARACTER_NAME);
    }
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
ResetIntroCamera()
void DayZIntroScene::ResetIntroCamera () inline private
Definition at line 127 of file dayzintroscene.c.
    {
        if ( GetIntroCharacter().GetCharacterObj() )
        {
            GetIntroCamera().LookAt( GetIntroCharacter().GetPosition() + Vector( 0, 1, 0 ) );
            //GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater( SceneCharacterSetPos, 250 );
        }
    }
References Managed::GetCharacterObj(), GetIntroCamera(), GetIntroCharacter(), Managed::GetPosition(), and Vector().
Referenced by UIScriptedMenu::Init().
SetInitPostprocesses()
protected void DayZIntroScene::SetInitPostprocesses () inline private
Since this can get created at the same time as DayZGame, non-static postprocesses need to be deffered.
Definition at line 137 of file dayzintroscene.c.
    {
        PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop();
    }
Referenced by DayZIntroScene().
SnapToGround()
protected vector DayZIntroScene::SnapToGround (vector pos) inline private
Definition at line 170 of file dayzintroscene.c.
    {
        float pos_x = pos[0];
        float pos_z = pos[2];
        float pos_y = GetGame().SurfaceY(pos_x, pos_z);
        vector tmp_pos = Vector(pos_x, pos_y, pos_z);
        tmp_pos[1] = tmp_pos[1] + pos[1];
        return tmp_pos;
    }
References GetGame(), CGame::SurfaceY(), and Vector().
Referenced by DayZIntroScene().
SwapYZ()
protected vector DayZIntroScene::SwapYZ (vector vec) inline private
Definition at line 159 of file dayzintroscene.c.
    {
        vector tmp;
        tmp[0] = vec[0];
        tmp[1] = vec[2];
        tmp[2] = vec[1];
        return tmp;
    }
Referenced by DayZIntroScene().
Member Data Documentation
m_Camera
protected Camera DayZIntroScene::m_Camera private
Definition at line 4 of file dayzintroscene.c.
Referenced by DayZIntroScene(), DayZIntroScenePC::DayZIntroScenePC(), and GetIntroCamera().
m_CameraTrans
protected vector DayZIntroScene::m_CameraTrans[4] private
Definition at line 5 of file dayzintroscene.c.
Referenced by DayZIntroScene().
m_Character
protected ref IntroSceneCharacter DayZIntroScene::m_Character private
Definition at line 3 of file dayzintroscene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), DayZIntroScene(), GetIntroCharacter(), and DayZIntroScenePC::Update().
m_CharacterPos
protected vector DayZIntroScene::m_CharacterPos private
Definition at line 6 of file dayzintroscene.c.
Referenced by DayZIntroScene(), and DayZIntroScenePC::DayZIntroScenePC().
m_CharacterRot
protected vector DayZIntroScene::m_CharacterRot private
Definition at line 7 of file dayzintroscene.c.
Referenced by DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), and DayZIntroScene().
m_OptionsMenu
protected ref OptionsMenu DayZIntroScene::m_OptionsMenu private
Definition at line 11 of file dayzintroscene.c.
m_Target
protected vector DayZIntroScene::m_Target private
Definition at line 9 of file dayzintroscene.c.
Referenced by DayZIntroScene().
m_Weather
protected Weather DayZIntroScene::m_Weather private
Definition at line 8 of file dayzintroscene.c.
Referenced by DayZIntroScene().