DayzKode: ActionInteractLoopBase Class Reference
ActionInteractLoopBase Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionInteractLoopBase ()
void ActionWashHandsWaterOne ()
void ActionWashHandsWellOne ()
override void CreateConditionComponents ()
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
override void OnEndServer (ActionData action_data)
Detailed Description
Definition at line 37 of file actioninteractloopbase.c.
Constructor & Destructor Documentation
ActionInteractLoopBase()
void ActionInteractLoopBase::ActionInteractLoopBase () inline private
Definition at line 39 of file actioninteractloopbase.c.
    {
        m_CallbackClass = ActionInteractLoopBaseCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
    }
References AnimatedActionBase::m_CallbackClass, and AnimatedActionBase::m_CommandUID.
Member Function Documentation
ActionCondition() [1/2]
override bool ActionInteractLoopBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file actionwashhandswaterone.c.
    {
        // Other conditions are in CCTWaterSurface
        return ( GetGame().IsMultiplayer() && GetGame().IsServer() ) || ( player.HasBloodyHands() && !player.GetItemInHands() && !player.GetItemOnSlot("Gloves") );
    }
References GetGame().
ActionCondition() [2/2]
override bool ActionInteractLoopBase::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file actionwashhandswellone.c.
    {
        return player.HasBloodyHands() && !player.GetItemInHands() && !player.GetItemOnSlot("Gloves") && target.GetObject() && target.GetObject().IsWell();
    }
ActionWashHandsWaterOne()
void ActionInteractLoopBase::ActionWashHandsWaterOne () inline private
Definition at line 11 of file actionwashhandswaterone.c.
    {
        m_CallbackClass     = ActionWashHandsWaterOneCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSPOND;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#wash_hands";
    }
References m_FullBody, m_StanceMask, and m_Text.
ActionWashHandsWellOne()
void ActionInteractLoopBase::ActionWashHandsWellOne () inline private
Definition at line 11 of file actionwashhandswellone.c.
    {
        m_CallbackClass     = ActionWashHandsWellOneCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONFB_WASHHANDSWELL;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#wash_hands";
    }
References m_FullBody, m_StanceMask, and m_Text.
CreateConditionComponents() [1/2]
override void ActionInteractLoopBase::CreateConditionComponents () inline private
Definition at line 20 of file actionwashhandswaterone.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTWaterSurface(UAMaxDistances.DEFAULT, UAWaterType.ALL);
    }
References UAWaterType::ALL, UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
CreateConditionComponents() [2/2]
override void ActionInteractLoopBase::CreateConditionComponents () inline private
Definition at line 20 of file actionwashhandswellone.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTObject(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnEndServer() [1/2]
override void ActionInteractLoopBase::OnEndServer (ActionData action_data) inline private
Definition at line 32 of file actionwashhandswaterone.c.
    {
        if (action_data.m_State == UA_FINISHED)
        {
            PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
            module_lifespan.UpdateBloodyHandsVisibility( action_data.m_Player, false );
        }
    }
References GetPlugin(), ActionData::m_Player, ActionData::m_State, PluginLifespan(), and UA_FINISHED.
OnEndServer() [2/2]
override void ActionInteractLoopBase::OnEndServer (ActionData action_data) inline private
Definition at line 31 of file actionwashhandswellone.c.
    {
        if (action_data.m_State == UA_FINISHED)
        {
            PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
            module_lifespan.UpdateBloodyHandsVisibility( action_data.m_Player, false );
        }
    }
References GetPlugin(), ActionData::m_Player, ActionData::m_State, PluginLifespan(), and UA_FINISHED.