DayzKode: StaminaModifiers Class Reference
StaminaModifiers Class Reference
Private Member Functions
StaminaModifier GetModifierData (EStaminaModifiers modifier)
void RegisterExponential (EStaminaModifiers modifier, float startValue, float exponent, float startTime, float duration, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register exponential modifier - depletes stamina for startValue, and, after a startTime, lerps from 0 to exponent over duration
void RegisterFixed (EStaminaModifiers modifier, float value, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register single value modifier - depletes stamina for that value
void RegisterLinear (EStaminaModifiers modifier, float startValue, float endValue, float startTime, float duration, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register lerped modifier - depletes stamina for startValue, and, after a startTime, lerps to endValue over duration
void RegisterRandomized (EStaminaModifiers modifier, float minValue, float maxValue, float cooldown=GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION)
register randomized modifier - stamina will be depleted by value between min and max value;
void StaminaModifiers ()
Private Attributes
const int EXPONENTIAL = 3
const int FIXED = 0
const int LINEAR = 2
protected ref map< EStaminaModifiers, ref StaminaModifier > m_StaminaModifiers
const int RANDOMIZED = 1
Detailed Description
Definition at line 178 of file staminahandler.c.
Constructor & Destructor Documentation
StaminaModifiers()
void StaminaModifiers::StaminaModifiers () inline private
Definition at line 187 of file staminahandler.c.
    {
        m_StaminaModifiers = new map<EStaminaModifiers, ref StaminaModifier>;
    }
References m_StaminaModifiers.
Member Function Documentation
GetModifierData()
StaminaModifier StaminaModifiers::GetModifierData (EStaminaModifiers modifier) inline private
Definition at line 228 of file staminahandler.c.
    {
        return m_StaminaModifiers.Get(modifier);
    }
References m_StaminaModifiers.
Referenced by DepleteStamina(), and ResetCooldown().
RegisterExponential()
void StaminaModifiers::RegisterExponential (EStaminaModifiers modifier, float startValue, float exponent, float startTime, float duration, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register exponential modifier - depletes stamina for startValue, and, after a startTime, lerps from 0 to exponent over duration
Definition at line 222 of file staminahandler.c.
    {
        StaminaModifier sm = new StaminaModifier(EXPONENTIAL, startValue, exponent, cooldown, startTime, duration);
        m_StaminaModifiers.Set(modifier, sm);
    }
References EXPONENTIAL, m_StaminaModifiers, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
RegisterFixed()
void StaminaModifiers::RegisterFixed (EStaminaModifiers modifier, float value, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register single value modifier - depletes stamina for that value
init of StaminaModifier - type and min, max values (min is not relevant for that type)
Definition at line 193 of file staminahandler.c.
    {
        if ( !m_StaminaModifiers.Contains(modifier) )
        {
            StaminaModifier sm = new StaminaModifier(FIXED, -1, value, cooldown);
            m_StaminaModifiers.Set(modifier, sm);
        }
    }
References FIXED, m_StaminaModifiers, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
RegisterLinear()
void StaminaModifiers::RegisterLinear (EStaminaModifiers modifier, float startValue, float endValue, float startTime, float duration, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register lerped modifier - depletes stamina for startValue, and, after a startTime, lerps to endValue over duration
Definition at line 215 of file staminahandler.c.
    {
        StaminaModifier sm = new StaminaModifier(LINEAR, startValue, endValue, cooldown, startTime, duration);
        m_StaminaModifiers.Set(modifier, sm);
    }
References LINEAR, m_StaminaModifiers, and StaminaModifier().
RegisterRandomized()
void StaminaModifiers::RegisterRandomized (EStaminaModifiers modifier, float minValue, float maxValue, float cooldown = GameConstants.STAMINA_REGEN_COOLDOWN_DEPLETION) inline private
register randomized modifier - stamina will be depleted by value between min and max value;
init of StaminaModifier - type, min, max values
Definition at line 204 of file staminahandler.c.
    {
        if ( !m_StaminaModifiers.Contains(modifier) )
        {
            StaminaModifier sm = new StaminaModifier(RANDOMIZED, minValue, maxValue, cooldown);
            m_StaminaModifiers.Set(modifier, sm);
        }
    }
References m_StaminaModifiers, RANDOMIZED, and StaminaModifier().
Referenced by RegisterStaminaModifiers().
Member Data Documentation
EXPONENTIAL
const int StaminaModifiers::EXPONENTIAL = 3 private
Definition at line 183 of file staminahandler.c.
Referenced by DepleteStamina(), and RegisterExponential().
FIXED
const int StaminaModifiers::FIXED = 0 private
Definition at line 180 of file staminahandler.c.
Referenced by DepleteStamina(), and RegisterFixed().
LINEAR
const int StaminaModifiers::LINEAR = 2 private
Definition at line 182 of file staminahandler.c.
Referenced by DepleteStamina(), and RegisterLinear().
m_StaminaModifiers
protected ref map<EStaminaModifiers, ref StaminaModifier> StaminaModifiers::m_StaminaModifiers private
Definition at line 185 of file staminahandler.c.
Referenced by GetModifierData(), RegisterExponential(), RegisterFixed(), RegisterLinear(), RegisterRandomized(), and StaminaModifiers().
RANDOMIZED
const int StaminaModifiers::RANDOMIZED = 1 private
Definition at line 181 of file staminahandler.c.
Referenced by DepleteStamina(), and RegisterRandomized().