DayzKode: InventoryItemType Class Reference
InventoryItemType Class Reference
Private Member Functions
proto native owned string GetName ()
AnimSoundEvent GetSoundEvent (int event_id)
private void InventoryItemType ()
void LoadSoundEvents ()
private void ~InventoryItemType ()
Private Attributes
ref array< ref AnimSoundEvent > m_animSoundEvents
Detailed Description
Definition at line 1 of file inventoryitemtype.c.
Constructor & Destructor Documentation
InventoryItemType()
private void InventoryItemType::InventoryItemType () inline private
Definition at line 5 of file inventoryitemtype.c.
    {
        LoadSoundEvents();
    }
References LoadSoundEvents().
~InventoryItemType()
private void InventoryItemType::~InventoryItemType () private
Member Function Documentation
GetName()
proto native owned string InventoryItemType::GetName () private
Referenced by LoadSoundEvents().
GetSoundEvent()
AnimSoundEvent InventoryItemType::GetSoundEvent (int event_id) inline private
Definition at line 50 of file inventoryitemtype.c.
    {
        for (int i = 0; i < m_animSoundEvents.Count(); i++)
        {
            AnimSoundEvent soundEvent = m_animSoundEvents.Get(i);
            if (soundEvent.m_iID == event_id)
            {
                return soundEvent;
            }
        }
        return null;
    }
References m_animSoundEvents.
Referenced by ProcessWeaponEvent().
LoadSoundEvents()
void InventoryItemType::LoadSoundEvents () inline private
Definition at line 12 of file inventoryitemtype.c.
    {
        string cfgPath = "CfgVehicles " + GetName() + " AnimEvents SoundWeapon";
        m_animSoundEvents = new array<ref AnimSoundEvent>;
        int soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
        if (soundCount <= 0)//try other path
        {
            cfgPath = "CfgWeapons " + GetName() + " AnimEvents SoundWeapon";
            soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
        }
        if (soundCount <= 0)//try other path
        {
            cfgPath = "CfgMagazines " + GetName() + " AnimEvents SoundWeapon";
            soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
        }
        if (soundCount <= 0)//try other path
        {
            cfgPath = "CfgAmmo " + GetName() + " AnimEvents SoundWeapon";
            soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
        }
        for (int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(cfgPath, i, soundName);
            string soundPath = cfgPath + " " + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if (soundEvent.IsValid())
                m_animSoundEvents.Insert(soundEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), GetName(), and m_animSoundEvents.
Referenced by InventoryItemType().
Member Data Documentation
m_animSoundEvents
ref array<ref AnimSoundEvent> InventoryItemType::m_animSoundEvents private
Definition at line 3 of file inventoryitemtype.c.
Referenced by GetSoundEvent(), and LoadSoundEvents().