DayzKode: UniversalTemperatureSourceLambdaBase Class Reference
UniversalTemperatureSourceLambdaBase Class Reference
Private Member Functions
void DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings)
void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
void UniversalTemperatureSourceLambdaBase ()
void ~UniversalTemperatureSourceLambdaBase ()
Private Attributes
const float HEAT_THROUGH_AIR_COEF = 0.003
Detailed Description
Definition at line 1 of file universaltemperaturesourcelambdabase.c.
Constructor & Destructor Documentation
UniversalTemperatureSourceLambdaBase()
void UniversalTemperatureSourceLambdaBase::UniversalTemperatureSourceLambdaBase () inline private
Definition at line 5 of file universaltemperaturesourcelambdabase.c.
{};
~UniversalTemperatureSourceLambdaBase()
void UniversalTemperatureSourceLambdaBase::~UniversalTemperatureSourceLambdaBase () inline private
Definition at line 6 of file universaltemperaturesourcelambdabase.c.
{};
Member Function Documentation
DryItemsInVicinity()
void UniversalTemperatureSourceLambdaBase::DryItemsInVicinity (UniversalTemperatureSourceSettings pSettings) inline private
heat transfer to items (no in player possession)
drying of items around the fireplace (based on distance)
Definition at line 10 of file universaltemperaturesourcelambdabase.c.
    {
        float distance;
        array<Object> nearestObjects = new array<Object>;
        vector pos = pSettings.m_Position;
        if (pSettings.m_Parent != null)
        {
            pos = pSettings.m_Parent.GetPosition();
        }
        GetGame().GetObjectsAtPosition(pos, pSettings.m_RangeMax, nearestObjects, null);
        for (int i = 0; i < nearestObjects.Count(); i++)
        {
            EntityAI nearestEnt = EntityAI.Cast(nearestObjects.Get(i));
            if (nearestEnt && nearestEnt.HasWetness() && nearestEnt != pSettings.m_Parent && nearestEnt.GetParent() == null)
            {
                float wetness = nearestEnt.GetWet();
                if (wetness > 0)
                {
                    distance = vector.Distance(nearestEnt.GetPosition(), pSettings.m_Position);
                    distance = Math.Max(distance, 0.1); //min distance cannot be 0 (division by zero)
                    wetness = wetness * (HEAT_THROUGH_AIR_COEF / distance);
                    wetness = Math.Clamp(wetness, nearestEnt.GetWetMin(), nearestEnt.GetWetMax());
                    nearestEnt.AddWet(-wetness);
                }
            }
        }
    }
References Math::Clamp(), vector::Distance(), GetGame(), CGame::GetObjectsAtPosition(), HEAT_THROUGH_AIR_COEF, UniversalTemperatureSourceSettings::m_Parent, UniversalTemperatureSourceSettings::m_Position, UniversalTemperatureSourceSettings::m_RangeMax, and Math::Max().
Referenced by UniversalTemperatureSourceLambdaFireplace::Execute().
Execute()
void UniversalTemperatureSourceLambdaBase::Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues) inline private
Definition at line 8 of file universaltemperaturesourcelambdabase.c.
{};
Referenced by UniversalTemperatureSourceDebug::Update().
Member Data Documentation
HEAT_THROUGH_AIR_COEF
const float UniversalTemperatureSourceLambdaBase::HEAT_THROUGH_AIR_COEF = 0.003 private
Definition at line 3 of file universaltemperaturesourcelambdabase.c.
Referenced by DryItemsInVicinity().