DayzKode: SoftSkillsManager Class Reference
SoftSkillsManager Class Reference
Private Member Functions
float AddExponentialPrecise (float specialty_weight)
float AddExponentialRough (float specialty_weight)
float AddLinearPrecise (float specialty_weight)
float AddLinearRough (float specialty_weight)
void AddSpecialty (float specialty_weight)
float AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
float AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency=2)
void CreateDebugWindow (bool create)
float GetComponentBonusAfter ()
float GetComponentBonusBefore ()
float GetCoolDownValue ()
float GetGeneralBonusAfter ()
float GetGeneralBonusBefore ()
float GetLastUAValue ()
void GetPreciseRoughLevels ()
PlayerBase GetSoftSkillsPlayer ()
bool GetSoftSkillsState ()
float GetSpecialtyLevel ()
void InitSpecialty (float specialty_level)
bool IsCoolDown ()
float IsDebug ()
bool IsLinear ()
void ResetDebugWindow ()
void SetBonusAfter (bool is_cacomponent, float adjusted_value)
void SetBonusBefore (bool is_cacomponent, float base_value)
void SetComponentBonusAfter (float component_bonus_after)
void SetComponentBonusBefore (float component_bonus_before)
void SetCoolDown (bool cool_down)
void SetCoolDownValue (float cooldown_value)
void SetGeneralBonusAfter (float general_bonus_after)
void SetGeneralBonusBefore (float general_bonus_before)
void SetIsDebug (bool is_debug)
void SetLastUAValue (float last_ua_value)
void SetLinearState (bool model)
void SetSoftSkillsState (bool state)
void SetSpecialtyLevel (float specialty_level)
void SoftSkillsManager (PlayerBase player)
void StartCoolDownTimer (float cooldown_value)
void StartSynchTimer ()
void StopSynchTimer ()
float SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent=false, float limit_efficiency=2)
void SynchDebugStats ()
void SynchSpecialtyLevel ()
void ~SoftSkillsManager ()
Private Attributes
protected float m_ComponentBonusAfter
protected float m_ComponentBonusBefore
protected ref Timer m_CoolDownTimer = new Timer()
protected float m_CoolDownValue
protected ref SoftSkillManagerDebug m_DebugWindow
protected float m_GeneralBonusAfter
protected float m_GeneralBonusBefore
protected bool m_IsActive
protected bool m_IsCoolDown
protected float m_IsDebugMode
protected bool m_IsLinear
protected float m_LastUAValue
protected PlayerBase m_Player
protected float m_PreciseLevel
protected float m_RoughLevel
protected float m_SpecialtyLevel
protected ref Timer m_SynchTimer
protected int m_UserActionsCounter
Static Private Attributes
static protected const float COOLDOWN_TIMER = 5
static protected const int DEFAULT_EFFICIENCY = 0
static protected const float PRECISE_WEIGHT_LIMIT = -1
static protected const float ROUGH_WEIGHT_LIMIT = 1
Detailed Description
Definition at line 1 of file softskillsmanager.c.
Constructor & Destructor Documentation
SoftSkillsManager()
void SoftSkillsManager::SoftSkillsManager (PlayerBase player) inline private
Definition at line 33 of file softskillsmanager.c.
    {
        m_Player = player;
        m_IsCoolDown = false;
        m_IsLinear = false;
        m_IsActive = true;
        m_IsDebugMode = false;
    }
References m_IsActive, m_IsCoolDown, m_IsDebugMode, m_IsLinear, and m_Player.
~SoftSkillsManager()
void SoftSkillsManager::~SoftSkillsManager () inline private
Definition at line 48 of file softskillsmanager.c.
    {
        delete m_CoolDownTimer;
    }
References m_CoolDownTimer.
Member Function Documentation
AddExponentialPrecise()
float SoftSkillsManager::AddExponentialPrecise (float specialty_weight) inline private
Definition at line 74 of file softskillsmanager.c.
    {
        m_UserActionsCounter -= 1;
        if( m_UserActionsCounter == 0)
        {
            m_UserActionsCounter = -1;
            m_SpecialtyLevel = 0;
        }
        float adjusted_weight = specialty_weight / Math.Sqrt( Math.AbsInt( m_UserActionsCounter ) );
        SetLastUAValue( adjusted_weight );
        m_SpecialtyLevel += adjusted_weight;
        m_SpecialtyLevel = Math.Clamp( m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT );
        return m_SpecialtyLevel;
    }
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddExponentialRough()
float SoftSkillsManager::AddExponentialRough (float specialty_weight) inline private
Definition at line 95 of file softskillsmanager.c.
    {
        m_UserActionsCounter += 1;
        if( m_UserActionsCounter == 0)
        {
            m_UserActionsCounter = 1;
            m_SpecialtyLevel = 0;
        }
        float adjusted_weight = specialty_weight / Math.Sqrt( Math.AbsInt( m_UserActionsCounter ) );
        SetLastUAValue( adjusted_weight );
        m_SpecialtyLevel += adjusted_weight;
        m_SpecialtyLevel = Math.Clamp( m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT );
        return m_SpecialtyLevel;
    }
References Math::AbsInt(), Math::Clamp(), m_SpecialtyLevel, m_UserActionsCounter, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, SetLastUAValue(), and Math::Sqrt().
Referenced by AddSpecialty().
AddLinearPrecise()
float SoftSkillsManager::AddLinearPrecise (float specialty_weight) inline private
Definition at line 54 of file softskillsmanager.c.
    {
        m_SpecialtyLevel += specialty_weight;
        SetLastUAValue( specialty_weight );
        m_SpecialtyLevel = Math.Clamp( m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT );
        return m_SpecialtyLevel;
    }
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddLinearRough()
float SoftSkillsManager::AddLinearRough (float specialty_weight) inline private
Definition at line 64 of file softskillsmanager.c.
    {
        m_SpecialtyLevel += specialty_weight;
        SetLastUAValue( specialty_weight );
        m_SpecialtyLevel = Math.Clamp( m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT );
        return m_SpecialtyLevel;
    }
References Math::Clamp(), m_SpecialtyLevel, PRECISE_WEIGHT_LIMIT, ROUGH_WEIGHT_LIMIT, and SetLastUAValue().
Referenced by AddSpecialty().
AddSpecialty()
void SoftSkillsManager::AddSpecialty (float specialty_weight) inline private
Definition at line 116 of file softskillsmanager.c.
    {
        if( GetSoftSkillsState() )
        {
            if( !IsCoolDown() )
            {
                    if( specialty_weight < 0 )
                    {
                        if( IsLinear() )
{
                            SetSpecialtyLevel( AddLinearPrecise( specialty_weight ) );
                        }
                        else
{
                             SetSpecialtyLevel( AddExponentialPrecise( specialty_weight ) );
                        }
                        m_Player.GetStatSpecialty().Set( m_SpecialtyLevel );
                        StartCoolDownTimer( Math.AbsFloat( ( specialty_weight * 100 ) ) * COOLDOWN_TIMER );
                        SynchSpecialtyLevel();
                    }
                    else if( specialty_weight > 0 )
                    {
                        if( IsLinear() )
{
                            SetSpecialtyLevel( AddLinearRough( specialty_weight ) );
                        }
                        else
{
                            SetSpecialtyLevel( AddExponentialRough( specialty_weight ) );
                        }
                        m_Player.GetStatSpecialty().Set( m_SpecialtyLevel );
                        StartCoolDownTimer( Math.AbsFloat( ( specialty_weight * 100 ) ) * COOLDOWN_TIMER );
                        SynchSpecialtyLevel();
                    }
                    else
                    {
                        //if the specialty weight for a recipe or UA is set to 0, it will increase neither specialty, nor UA counter
                        return;
                    }
                }
            else
            {
                StartCoolDownTimer( Math.AbsFloat( ( specialty_weight * 100 ) ) * COOLDOWN_TIMER );
            }
        }
    }
References Math::AbsFloat(), AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), COOLDOWN_TIMER, GetSoftSkillsState(), IsCoolDown(), IsLinear(), m_Player, m_SpecialtyLevel, SetSpecialtyLevel(), StartCoolDownTimer(), and SynchSpecialtyLevel().
AddSpecialtyBonus()
float SoftSkillsManager::AddSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline private
Definition at line 168 of file softskillsmanager.c.
    {
        if ( specialty_weight == 0 )
        {
            return base_value;
        }
        SetBonusBefore( is_cacomponent, base_value);
        float adjusted_value;
        GetPreciseRoughLevels();
        if ( limit_efficiency != 0 )
        {
            if ( specialty_weight < 0 )
            {
                adjusted_value = base_value + ( ( base_value * m_PreciseLevel ) / limit_efficiency );
            }
            else
            {
                adjusted_value = base_value + ( ( base_value * m_RoughLevel ) / limit_efficiency );
            }
        }
        else
        {
            if ( specialty_weight < 0 )
            {
                adjusted_value = base_value + ( ( base_value * m_PreciseLevel ) );
            }
            else
            {
                adjusted_value = base_value + ( ( base_value * m_RoughLevel ) );
            }
        }
        SetBonusAfter( is_cacomponent, adjusted_value );
        return adjusted_value;
    }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
AdjustCraftingTime()
float SoftSkillsManager::AdjustCraftingTime (float base_time, float specialty_weight, float limit_efficiency = 2) inline private
Definition at line 256 of file softskillsmanager.c.
    {
        if ( specialty_weight == 0 )
        {
            return base_time;
        }
        SetBonusBefore( false, base_time);
        float adjusted_time;
        GetPreciseRoughLevels();
        if ( specialty_weight < 0 )
        {
            adjusted_time = base_time - ( ( base_time * m_PreciseLevel ) / limit_efficiency );
        }
        else
        {
            adjusted_time = base_time - ( ( base_time * m_RoughLevel ) / limit_efficiency );
        }
        SetBonusAfter( false, adjusted_time );
        return adjusted_time;
    }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
CreateDebugWindow()
void SoftSkillsManager::CreateDebugWindow (bool create) inline private
Definition at line 380 of file softskillsmanager.c.
    {
        if ( create )
        {
            m_DebugWindow = new SoftSkillManagerDebug( this );
            SetIsDebug( create );
        }
        else
        {
            ResetDebugWindow();
            SetIsDebug( create );
            delete m_DebugWindow;
        }
    }
References m_DebugWindow, ResetDebugWindow(), SetIsDebug(), and SoftSkillManagerDebug().
GetComponentBonusAfter()
float SoftSkillsManager::GetComponentBonusAfter () inline private
Definition at line 488 of file softskillsmanager.c.
    {
        return m_ComponentBonusAfter;
    }
References m_ComponentBonusAfter.
GetComponentBonusBefore()
float SoftSkillsManager::GetComponentBonusBefore () inline private
Definition at line 476 of file softskillsmanager.c.
    {
        return m_ComponentBonusBefore;
    }
References m_ComponentBonusBefore.
GetCoolDownValue()
float SoftSkillsManager::GetCoolDownValue () inline private
Definition at line 426 of file softskillsmanager.c.
    {
        return m_CoolDownValue;
    }
References m_CoolDownValue.
GetGeneralBonusAfter()
float SoftSkillsManager::GetGeneralBonusAfter () inline private
Definition at line 512 of file softskillsmanager.c.
    {
        return m_GeneralBonusAfter;
    }
References m_GeneralBonusAfter.
GetGeneralBonusBefore()
float SoftSkillsManager::GetGeneralBonusBefore () inline private
Definition at line 500 of file softskillsmanager.c.
    {
        return m_GeneralBonusBefore;
    }
References m_GeneralBonusBefore.
GetLastUAValue()
float SoftSkillsManager::GetLastUAValue () inline private
Definition at line 432 of file softskillsmanager.c.
    {
        return m_LastUAValue;
    }
References m_LastUAValue.
GetPreciseRoughLevels()
void SoftSkillsManager::GetPreciseRoughLevels () inline private
Definition at line 338 of file softskillsmanager.c.
    {
        if( m_SpecialtyLevel > 0)
        {
            m_RoughLevel = m_SpecialtyLevel;
            m_PreciseLevel = DEFAULT_EFFICIENCY;
        }
        else if ( m_SpecialtyLevel < 0)
        {
            m_RoughLevel = DEFAULT_EFFICIENCY;
            m_PreciseLevel =  Math.AbsFloat( m_SpecialtyLevel );
        }
        else
        {
            m_RoughLevel = DEFAULT_EFFICIENCY;
            m_PreciseLevel = DEFAULT_EFFICIENCY;
        }
    }
References Math::AbsFloat(), DEFAULT_EFFICIENCY, m_PreciseLevel, m_RoughLevel, and m_SpecialtyLevel.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
GetSoftSkillsPlayer()
PlayerBase SoftSkillsManager::GetSoftSkillsPlayer () inline private
Definition at line 284 of file softskillsmanager.c.
    {
        return m_Player;
    }
References m_Player.
GetSoftSkillsState()
bool SoftSkillsManager::GetSoftSkillsState () inline private
Definition at line 320 of file softskillsmanager.c.
    {
        return m_IsActive;
    }
References m_IsActive.
Referenced by AddSpecialty().
GetSpecialtyLevel()
float SoftSkillsManager::GetSpecialtyLevel () inline private
Definition at line 296 of file softskillsmanager.c.
    {
        return m_SpecialtyLevel;
    }
References m_SpecialtyLevel.
Referenced by OnUpdate().
InitSpecialty()
void SoftSkillsManager::InitSpecialty (float specialty_level) inline private
Definition at line 42 of file softskillsmanager.c.
    {
        SetSpecialtyLevel( specialty_level );
        SynchSpecialtyLevel();
    }
References SetSpecialtyLevel(), and SynchSpecialtyLevel().
IsCoolDown()
bool SoftSkillsManager::IsCoolDown () inline private
Definition at line 366 of file softskillsmanager.c.
    {
        return m_IsCoolDown;
    }
References m_IsCoolDown.
Referenced by AddSpecialty().
IsDebug()
float SoftSkillsManager::IsDebug () inline private
Definition at line 414 of file softskillsmanager.c.
    {
        return m_IsDebugMode;
    }
References m_IsDebugMode.
Referenced by SetBonusAfter(), and SetBonusBefore().
IsLinear()
bool SoftSkillsManager::IsLinear () inline private
Definition at line 332 of file softskillsmanager.c.
    {
        return m_IsLinear;
    }
References m_IsLinear.
Referenced by AddSpecialty().
ResetDebugWindow()
void SoftSkillsManager::ResetDebugWindow () inline private
Definition at line 544 of file softskillsmanager.c.
    {
        SetSpecialtyLevel( 0 );
        SetLastUAValue( 0 );
        SetComponentBonusBefore( 0 );
        SetComponentBonusAfter( 0 );
        SetGeneralBonusBefore( 0 );
        SetGeneralBonusAfter( 0 );
        SetCoolDownValue( 0 );
        SynchSpecialtyLevel();
    }
References SetComponentBonusAfter(), SetComponentBonusBefore(), SetCoolDownValue(), SetGeneralBonusAfter(), SetGeneralBonusBefore(), SetLastUAValue(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
Referenced by CreateDebugWindow().
SetBonusAfter()
void SoftSkillsManager::SetBonusAfter (bool is_cacomponent, float adjusted_value) inline private
Definition at line 460 of file softskillsmanager.c.
    {
        if( IsDebug() )
            {
                if( is_cacomponent )
                {
                    SetComponentBonusAfter(adjusted_value);
                }
                else
                {
                    SetGeneralBonusAfter(adjusted_value);
                }
            }
    }
References IsDebug(), SetComponentBonusAfter(), and SetGeneralBonusAfter().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetBonusBefore()
void SoftSkillsManager::SetBonusBefore (bool is_cacomponent, float base_value) inline private
Definition at line 444 of file softskillsmanager.c.
    {
        if( IsDebug() )
        {
            if( is_cacomponent )
            {
                SetComponentBonusBefore(base_value);
            }
            else
            {
                SetGeneralBonusBefore(base_value);
            }
        }
    }
References IsDebug(), SetComponentBonusBefore(), and SetGeneralBonusBefore().
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), and SubtractSpecialtyBonus().
SetComponentBonusAfter()
void SoftSkillsManager::SetComponentBonusAfter (float component_bonus_after) inline private
Definition at line 494 of file softskillsmanager.c.
    {
        m_ComponentBonusAfter = component_bonus_after;
    }
References m_ComponentBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetComponentBonusBefore()
void SoftSkillsManager::SetComponentBonusBefore (float component_bonus_before) inline private
Definition at line 482 of file softskillsmanager.c.
    {
        m_ComponentBonusBefore = component_bonus_before;
    }
References m_ComponentBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetCoolDown()
void SoftSkillsManager::SetCoolDown (bool cool_down) inline private
Definition at line 372 of file softskillsmanager.c.
    {
        m_IsCoolDown = cool_down;
    }
References m_IsCoolDown.
Referenced by StartCoolDownTimer().
SetCoolDownValue()
void SoftSkillsManager::SetCoolDownValue (float cooldown_value) inline private
Definition at line 420 of file softskillsmanager.c.
    {
        m_CoolDownValue = cooldown_value;
    }
References m_CoolDownValue.
Referenced by ResetDebugWindow(), and StartCoolDownTimer().
SetGeneralBonusAfter()
void SoftSkillsManager::SetGeneralBonusAfter (float general_bonus_after) inline private
Definition at line 518 of file softskillsmanager.c.
    {
        m_GeneralBonusAfter = general_bonus_after;
    }
References m_GeneralBonusAfter.
Referenced by ResetDebugWindow(), and SetBonusAfter().
SetGeneralBonusBefore()
void SoftSkillsManager::SetGeneralBonusBefore (float general_bonus_before) inline private
Definition at line 506 of file softskillsmanager.c.
    {
        m_GeneralBonusBefore = general_bonus_before;
    }
References m_GeneralBonusBefore.
Referenced by ResetDebugWindow(), and SetBonusBefore().
SetIsDebug()
void SoftSkillsManager::SetIsDebug (bool is_debug) inline private
Definition at line 408 of file softskillsmanager.c.
    {
        m_IsDebugMode = is_debug;
    }
References m_IsDebugMode.
Referenced by CreateDebugWindow(), StartSynchTimer(), and StopSynchTimer().
SetLastUAValue()
void SoftSkillsManager::SetLastUAValue (float last_ua_value) inline private
Definition at line 438 of file softskillsmanager.c.
    {
        m_LastUAValue = last_ua_value;
    }
References m_LastUAValue.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), and ResetDebugWindow().
SetLinearState()
void SoftSkillsManager::SetLinearState (bool model) inline private
Definition at line 326 of file softskillsmanager.c.
    {
        m_IsLinear = model;
    }
References m_IsLinear.
SetSoftSkillsState()
void SoftSkillsManager::SetSoftSkillsState (bool state) inline private
Definition at line 314 of file softskillsmanager.c.
    {
        m_IsActive = state;
    }
References m_IsActive.
SetSpecialtyLevel()
void SoftSkillsManager::SetSpecialtyLevel (float specialty_level) inline private
Definition at line 290 of file softskillsmanager.c.
    {
        m_SpecialtyLevel = specialty_level;
    }
References m_SpecialtyLevel.
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
StartCoolDownTimer()
void SoftSkillsManager::StartCoolDownTimer (float cooldown_value) inline private
Definition at line 358 of file softskillsmanager.c.
    {
        SetCoolDown( true );
        SetCoolDownValue( cooldown_value );
        m_CoolDownTimer.Run( cooldown_value, this, "SetCoolDown", new Param1<bool>( false ) );
    }
References m_CoolDownTimer, SetCoolDown(), and SetCoolDownValue().
Referenced by AddSpecialty().
StartSynchTimer()
void SoftSkillsManager::StartSynchTimer () inline private
Definition at line 524 of file softskillsmanager.c.
    {
        SetIsDebug( true );
        m_SynchTimer = new Timer;
        m_SynchTimer.Run( 2, this, "SynchDebugStats", NULL, true );
    }
References m_SynchTimer, and SetIsDebug().
StopSynchTimer()
void SoftSkillsManager::StopSynchTimer () inline private
Definition at line 532 of file softskillsmanager.c.
    {
        SetIsDebug( false );
        if( m_SynchTimer )
        {
            m_SynchTimer.Stop();
            delete m_SynchTimer;
        }
    }
References m_SynchTimer, and SetIsDebug().
SubtractSpecialtyBonus()
float SoftSkillsManager::SubtractSpecialtyBonus (float base_value, float specialty_weight, bool is_cacomponent = false, float limit_efficiency = 2) inline private
Definition at line 212 of file softskillsmanager.c.
    {
        if ( specialty_weight == 0 )
        {
            return base_value;
        }
        SetBonusBefore( is_cacomponent, base_value);
        float adjusted_value;
        GetPreciseRoughLevels();
        if ( limit_efficiency != 0 )
        {
            if ( specialty_weight < 0 )
            {
                adjusted_value = base_value - ( ( base_value * m_PreciseLevel  ) / limit_efficiency );
            }
            else
            {
                adjusted_value = base_value - ( ( base_value * m_RoughLevel ) / limit_efficiency );
            }
        }
        else
        {
            if ( specialty_weight < 0 )
            {
                adjusted_value = base_value - ( ( base_value * m_PreciseLevel  ) );
            }
            else
            {
                adjusted_value = base_value - ( ( base_value * m_RoughLevel ) );
            }
        }
        SetBonusAfter( is_cacomponent, adjusted_value );
        return adjusted_value;
    }
References GetPreciseRoughLevels(), m_PreciseLevel, m_RoughLevel, SetBonusAfter(), and SetBonusBefore().
SynchDebugStats()
void SoftSkillsManager::SynchDebugStats () inline private
Definition at line 396 of file softskillsmanager.c.
    {
        if ( GetGame().IsServer() && GetGame().IsMultiplayer() )
        {
            Param5<float, float, float, float, bool> debug_stats;
            debug_stats = new Param5<float, float, float, float, bool>( m_GeneralBonusBefore, m_GeneralBonusAfter, m_LastUAValue, m_CoolDownValue, m_IsCoolDown );
            GetGame().RPCSingleParam( m_Player, ERPCs.RPC_SOFT_SKILLS_STATS_SYNC, debug_stats, true, m_Player.GetIdentity() );
        }
    }
References GetGame(), m_CoolDownValue, m_GeneralBonusAfter, m_GeneralBonusBefore, m_IsCoolDown, m_LastUAValue, m_Player, and CGame::RPCSingleParam().
SynchSpecialtyLevel()
void SoftSkillsManager::SynchSpecialtyLevel () inline private
Definition at line 302 of file softskillsmanager.c.
    {
        ref Param1<float> specialty_level;
        if( GetGame().IsServer() )
        {
            specialty_level = new Param1<float>( m_SpecialtyLevel );
            GetGame().RPCSingleParam( m_Player, ERPCs.RPC_SOFT_SKILLS_SPECIALTY_SYNC, specialty_level, true, m_Player.GetIdentity() );
        }
    }
References GetGame(), m_Player, m_SpecialtyLevel, and CGame::RPCSingleParam().
Referenced by AddSpecialty(), InitSpecialty(), and ResetDebugWindow().
Member Data Documentation
COOLDOWN_TIMER
protected const float SoftSkillsManager::COOLDOWN_TIMER = 5 static private
Definition at line 17 of file softskillsmanager.c.
Referenced by AddSpecialty().
DEFAULT_EFFICIENCY
protected const int SoftSkillsManager::DEFAULT_EFFICIENCY = 0 static private
Definition at line 14 of file softskillsmanager.c.
Referenced by GetPreciseRoughLevels().
m_ComponentBonusAfter
protected float SoftSkillsManager::m_ComponentBonusAfter private
Definition at line 25 of file softskillsmanager.c.
Referenced by GetComponentBonusAfter(), and SetComponentBonusAfter().
m_ComponentBonusBefore
protected float SoftSkillsManager::m_ComponentBonusBefore private
Definition at line 24 of file softskillsmanager.c.
Referenced by GetComponentBonusBefore(), and SetComponentBonusBefore().
m_CoolDownTimer
protected ref Timer SoftSkillsManager::m_CoolDownTimer = new Timer() private
Definition at line 19 of file softskillsmanager.c.
Referenced by StartCoolDownTimer(), and ~SoftSkillsManager().
m_CoolDownValue
protected float SoftSkillsManager::m_CoolDownValue private
Definition at line 22 of file softskillsmanager.c.
Referenced by GetCoolDownValue(), SetCoolDownValue(), and SynchDebugStats().
m_DebugWindow
protected ref SoftSkillManagerDebug SoftSkillsManager::m_DebugWindow private
Definition at line 29 of file softskillsmanager.c.
Referenced by CreateDebugWindow().
m_GeneralBonusAfter
protected float SoftSkillsManager::m_GeneralBonusAfter private
Definition at line 27 of file softskillsmanager.c.
Referenced by GetGeneralBonusAfter(), SetGeneralBonusAfter(), and SynchDebugStats().
m_GeneralBonusBefore
protected float SoftSkillsManager::m_GeneralBonusBefore private
Definition at line 26 of file softskillsmanager.c.
Referenced by GetGeneralBonusBefore(), SetGeneralBonusBefore(), and SynchDebugStats().
m_IsActive
protected bool SoftSkillsManager::m_IsActive private
Definition at line 9 of file softskillsmanager.c.
Referenced by GetSoftSkillsState(), SetSoftSkillsState(), and SoftSkillsManager().
m_IsCoolDown
protected bool SoftSkillsManager::m_IsCoolDown private
Definition at line 10 of file softskillsmanager.c.
Referenced by IsCoolDown(), SetCoolDown(), SoftSkillsManager(), and SynchDebugStats().
m_IsDebugMode
protected float SoftSkillsManager::m_IsDebugMode private
Definition at line 21 of file softskillsmanager.c.
Referenced by IsDebug(), SetIsDebug(), and SoftSkillsManager().
m_IsLinear
protected bool SoftSkillsManager::m_IsLinear private
Definition at line 8 of file softskillsmanager.c.
Referenced by IsLinear(), SetLinearState(), and SoftSkillsManager().
m_LastUAValue
protected float SoftSkillsManager::m_LastUAValue private
Definition at line 23 of file softskillsmanager.c.
Referenced by GetLastUAValue(), SetLastUAValue(), and SynchDebugStats().
m_Player
protected PlayerBase SoftSkillsManager::m_Player private
Definition at line 3 of file softskillsmanager.c.
Referenced by AddSpecialty(), GetSoftSkillsPlayer(), SoftSkillsManager(), SynchDebugStats(), and SynchSpecialtyLevel().
m_PreciseLevel
protected float SoftSkillsManager::m_PreciseLevel private
Definition at line 6 of file softskillsmanager.c.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_RoughLevel
protected float SoftSkillsManager::m_RoughLevel private
Definition at line 5 of file softskillsmanager.c.
Referenced by AddSpecialtyBonus(), AdjustCraftingTime(), GetPreciseRoughLevels(), and SubtractSpecialtyBonus().
m_SpecialtyLevel
protected float SoftSkillsManager::m_SpecialtyLevel private
Definition at line 4 of file softskillsmanager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), AddLinearRough(), AddSpecialty(), GetPreciseRoughLevels(), GetSpecialtyLevel(), SetSpecialtyLevel(), and SynchSpecialtyLevel().
m_SynchTimer
protected ref Timer SoftSkillsManager::m_SynchTimer private
Definition at line 31 of file softskillsmanager.c.
Referenced by StartSynchTimer(), and StopSynchTimer().
m_UserActionsCounter
protected int SoftSkillsManager::m_UserActionsCounter private
Definition at line 12 of file softskillsmanager.c.
Referenced by AddExponentialPrecise(), and AddExponentialRough().
PRECISE_WEIGHT_LIMIT
protected const float SoftSkillsManager::PRECISE_WEIGHT_LIMIT = -1 static private
Definition at line 15 of file softskillsmanager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().
ROUGH_WEIGHT_LIMIT
protected const float SoftSkillsManager::ROUGH_WEIGHT_LIMIT = 1 static private
Definition at line 16 of file softskillsmanager.c.
Referenced by AddExponentialPrecise(), AddExponentialRough(), AddLinearPrecise(), and AddLinearRough().