DayzKode: Hit_Foliage Class Reference
Hit_Foliage Class Reference
Private Member Functions
override float CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight)
void Hit_Foliage ()
Detailed Description
Definition at line 1 of file hit_foliage.c.
Constructor & Destructor Documentation
Hit_Foliage()
void Hit_Foliage::Hit_Foliage () inline private
Definition at line 3 of file hit_foliage.c.
    {
        SetEnterParticle(ParticleList.IMPACT_FOLIAGE_ENTER);
        SetExitParticle(ParticleList.IMPACT_FOLIAGE_EXIT);
        SetRicochetParticle(ParticleList.IMPACT_FOLIAGE_RICOCHET);
    }
References ParticleList::IMPACT_FOLIAGE_ENTER, ParticleList::IMPACT_FOLIAGE_EXIT, ParticleList::IMPACT_FOLIAGE_RICOCHET, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().
Member Function Documentation
CalculateStoppingForce()
override float Hit_Foliage::CalculateStoppingForce (float in_speedf, float out_speedf, string ammoType, float weight) inline private
Definition at line 10 of file hit_foliage.c.
    {
        if ( m_ImpactType == ImpactTypes.MELEE )
        {
            return 500;
        }
        float projectile_weight_coef = weight / DEFAULT_PROJECTILE_WEIGHT;
        float stopping_force = in_speedf * projectile_weight_coef * 0.5;
        return stopping_force;
    }
References EffBulletImpactBase::DEFAULT_PROJECTILE_WEIGHT, and EffBulletImpactBase::m_ImpactType.