DayzKode: MaskMdfr Class Reference
MaskMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
void HandleSounds (PlayerBase player, float deltaT, MaskBase mask)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const float IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.3
const float LOW_FILTER_SOUND_EVENT_MAX = 9
const float LOW_FILTER_SOUND_EVENT_MIN = 3
const float LOW_FILTER_SOUND_THRESHOLD = 0.2
float m_NextSoundEventTime
float m_SoundTimeAccu1
const float OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.03
const float STAMINA_DEPLETION_MODIFIER = 1.25
const float STAMINA_RECOVERY_MODIFIER = 0.5
Detailed Description
Definition at line 1 of file mask.c.
Member Function Documentation
ActivateCondition()
override bool MaskMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 25 of file mask.c.
    {
        return MaskBase.Cast(player.GetInventory().FindAttachment(InventorySlots.MASK)) != null;
    }
Referenced by DeactivateCondition().
DeactivateCondition()
override bool MaskMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 30 of file mask.c.
    {
        return !ActivateCondition( player);
    }
References ActivateCondition().
HandleSounds()
void MaskMdfr::HandleSounds (PlayerBase player, float deltaT, MaskBase mask) inline private
Definition at line 68 of file mask.c.
    {
        float filter_quantity_01 = mask.GetFilterQuantity01();
        if(mask.CanHaveExternalFilter() && !mask.IsExternalFilterAttached())
            return;
        if(filter_quantity_01 > LOW_FILTER_SOUND_THRESHOLD)
            return;
        float low_quantity_norm = Math.InverseLerp(0, LOW_FILTER_SOUND_THRESHOLD, filter_quantity_01);//should give us 0..1 based on normalized quantity between 0 and LOW_FILTER_SOUND_THRESHOLD
        m_SoundTimeAccu1 += deltaT;
        if( m_SoundTimeAccu1 >= m_NextSoundEventTime)
        {
            m_NextSoundEventTime = Math.Lerp(LOW_FILTER_SOUND_EVENT_MIN, LOW_FILTER_SOUND_EVENT_MAX,low_quantity_norm);
            EPlayerSoundEventID event_type = EPlayerSoundEventID.STAMINA_LOW_FILTER_UPPER;
            //under 50% of low filter quantity (not overall filter quantity!!)
            if (low_quantity_norm < 0.5)
            {
                event_type = EPlayerSoundEventID.STAMINA_LOW_FILTER_MID;
            }
            if (low_quantity_norm < 0.25)
            {
                event_type = EPlayerSoundEventID.STAMINA_LOW_FILTER_LOWER;
            }
            player.RequestSoundEventEx(event_type, false, EPlayerSoundEventParam.HIGHEST_PRIORITY);
            m_SoundTimeAccu1 = 0;
        }
    }
References Math::InverseLerp(), Math::Lerp(), LOW_FILTER_SOUND_EVENT_MAX, LOW_FILTER_SOUND_EVENT_MIN, LOW_FILTER_SOUND_THRESHOLD, m_NextSoundEventTime, and m_SoundTimeAccu1.
Referenced by OnTick().
Init()
override void MaskMdfr::Init () inline private
Definition at line 17 of file mask.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_MASK;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE_SHORT;
    }
References DEFAULT_TICK_TIME_ACTIVE_SHORT, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void MaskMdfr::OnActivate (PlayerBase player) inline private
Definition at line 105 of file mask.c.
    {
        //m_NextSoundEventTime = Math.RandomFloat(LOW_FILTER_SOUND_EVENT_MIN, LOW_FILTER_SOUND_EVENT_MAX);
    }
OnDeactivate()
override void MaskMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 110 of file mask.c.
    {
        StaminaSoundHandlerServer.Cast(player.GetPlayerSoundManagerServer().GetHandler(eSoundHandlers.STAMINA)).SetStaminaZoneOffset(0);
        player.GetStaminaHandler().DeactivateRecoveryModifier(EStaminaMultiplierTypes.MASK);
        player.GetStaminaHandler().DeactivateDepletionModifier(EStaminaMultiplierTypes.MASK);
    }
OnReconnect()
override void MaskMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 100 of file mask.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void MaskMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 35 of file mask.c.
    {
        MaskBase mask = MaskBase.Cast(player.GetInventory().FindAttachment(InventorySlots.MASK));
        float consume_quantity = OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC;
        bool inside_area = m_Manager.IsModifierActive(eModifiers.MDF_AREAEXPOSURE);
        if(inside_area)
        {
            consume_quantity = IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC;
        }
        if ( mask && !mask.IsDamageDestroyed())
        {
            bool consuming_filter = mask.ConsumeQuantity(consume_quantity * deltaT, player);
            StaminaSoundHandlerServer.Cast(player.GetPlayerSoundManagerServer().GetHandler(eSoundHandlers.STAMINA)).SetStaminaZoneOffset(1);
            if (mask.HasValidFilter())
            {
                player.GetStaminaHandler().ActivateRecoveryModifier(EStaminaMultiplierTypes.MASK);
                player.GetStaminaHandler().ActivateDepletionModifier(EStaminaMultiplierTypes.MASK);
            }
            else
            {
                player.GetStaminaHandler().DeactivateRecoveryModifier(EStaminaMultiplierTypes.MASK);
                player.GetStaminaHandler().DeactivateDepletionModifier(EStaminaMultiplierTypes.MASK);
            }
            HandleSounds(player, deltaT, mask);
        }
    }
References HandleSounds(), IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC, m_Manager, and OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC.
Member Data Documentation
IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC
const float MaskMdfr::IN_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.3 private
Definition at line 3 of file mask.c.
Referenced by OnTick().
LOW_FILTER_SOUND_EVENT_MAX
const float MaskMdfr::LOW_FILTER_SOUND_EVENT_MAX = 9 private
Definition at line 10 of file mask.c.
Referenced by HandleSounds().
LOW_FILTER_SOUND_EVENT_MIN
const float MaskMdfr::LOW_FILTER_SOUND_EVENT_MIN = 3 private
Definition at line 9 of file mask.c.
Referenced by HandleSounds().
LOW_FILTER_SOUND_THRESHOLD
const float MaskMdfr::LOW_FILTER_SOUND_THRESHOLD = 0.2 private
Definition at line 12 of file mask.c.
Referenced by HandleSounds().
m_NextSoundEventTime
float MaskMdfr::m_NextSoundEventTime private
Definition at line 15 of file mask.c.
Referenced by HandleSounds().
m_SoundTimeAccu1
float MaskMdfr::m_SoundTimeAccu1 private
Definition at line 14 of file mask.c.
Referenced by HandleSounds().
OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC
const float MaskMdfr::OUT_AREA_CONSUME_FILTER_QUANTITY_PER_SEC = 0.03 private
Definition at line 4 of file mask.c.
Referenced by OnTick().
STAMINA_DEPLETION_MODIFIER
const float MaskMdfr::STAMINA_DEPLETION_MODIFIER = 1.25 private
Definition at line 7 of file mask.c.
Referenced by Init().
STAMINA_RECOVERY_MODIFIER
const float MaskMdfr::STAMINA_RECOVERY_MODIFIER = 0.5 private
Definition at line 6 of file mask.c.
Referenced by Init().