DayzKode: PlayerIdentityBase Class Reference
PlayerIdentityBase Class Reference
Player description (base engine class)
Private Member Functions
proto int GetBandwidthAvg ()
bandwidth estimation (in kbps)
proto int GetBandwidthMax ()
bandwidth estimation (in kbps)
proto int GetBandwidthMin ()
bandwidth estimation (in kbps)
proto string GetFullName ()
full name of player
proto string GetId ()
unique id of player (hashed steamID, database Xbox id...) can be used in database or logs
proto string GetName ()
nick (short) name of player
proto int GetPingAvg ()
ping range estimation
proto int GetPingMax ()
ping range estimation
proto int GetPingMin ()
ping range estimation
proto string GetPlainId ()
plaintext unique id of player (cannot be used in database or logs)
proto Man GetPlayer ()
get player
proto int GetPlayerId ()
id of player in one session (is reused after player disconnects)
private void PlayerIdentityBase ()
This is a C++ managed class, so script has no business managing the lifetime.
private void ~PlayerIdentityBase ()
Detailed Description
Player description (base engine class)
Definition at line 334 of file gameplay.c.
Constructor & Destructor Documentation
PlayerIdentityBase()
private void PlayerIdentityBase::PlayerIdentityBase () private
This is a C++ managed class, so script has no business managing the lifetime.
~PlayerIdentityBase()
private void PlayerIdentityBase::~PlayerIdentityBase () private
Member Function Documentation
GetBandwidthAvg()
proto int PlayerIdentityBase::GetBandwidthAvg () private
bandwidth estimation (in kbps)
GetBandwidthMax()
proto int PlayerIdentityBase::GetBandwidthMax () private
bandwidth estimation (in kbps)
GetBandwidthMin()
proto int PlayerIdentityBase::GetBandwidthMin () private
bandwidth estimation (in kbps)
GetFullName()
proto string PlayerIdentityBase::GetFullName () private
full name of player
GetId()
proto string PlayerIdentityBase::GetId () private
unique id of player (hashed steamID, database Xbox id...) can be used in database or logs
Referenced by PluginBase::GetPlayerPrefix(), LogSuicide(), MissionBase::OnClientDisconnectedEvent(), and MissionBase::OnEvent().
GetName()
proto string PlayerIdentityBase::GetName () private
nick (short) name of player
Referenced by SyncPlayerList::CreatePlayerList(), PluginBase::GetPlayerPrefix(), and LogSuicide().
GetPingAvg()
proto int PlayerIdentityBase::GetPingAvg () private
ping range estimation
GetPingMax()
proto int PlayerIdentityBase::GetPingMax () private
ping range estimation
GetPingMin()
proto int PlayerIdentityBase::GetPingMin () private
ping range estimation
GetPlainId()
proto string PlayerIdentityBase::GetPlainId () private
plaintext unique id of player (cannot be used in database or logs)
Referenced by SyncPlayerList::CreatePlayerList(), and OnRPC().
GetPlayer()
proto Man PlayerIdentityBase::GetPlayer () private
get player
GetPlayerId()
proto int PlayerIdentityBase::GetPlayerId () private
id of player in one session (is reused after player disconnects)