DayzKode: FlashbangEffect Class Reference
FlashbangEffect Class Reference
Private Member Functions
protected void ClearVisual ()
void FlashbangEffect (PlayerBase player, bool visual=true)
protected void PlaySound ()
protected void ResetAttenuationFilter ()
protected void SetAttenuationFilter ()
void SetupFlashbangValues (float progress_mult=1.0, float visual_value_max=1.0, float sound_value_max=1.0)
protected void SetVisual (float val)
void Stop ()
protected void StopSound ()
void Update (float deltatime)
void ~FlashbangEffect ()
Private Attributes
protected const float ALPHA_MAX = 1.0
protected const float ALPHA_MIN = 0.0
protected float m_AlphaMaxActual
protected float m_BreakPoint
protected float m_DayTimeToggle
protected ref Timer m_DeferAttenuation
protected EffectSound m_FlashbangEffectSound
protected float m_HitDuration
SFX will be played ~0.5s AFTER VFX.
protected bool m_Initialized
protected PlayerBase m_Player
protected float m_ProgressMultiplier
protected PPERequester_FlashbangEffects m_Requester
protected float m_SoundMaxActual
protected float m_SoundStopTime
protected float m_TimeActive
protected bool m_Visual
protected const float SOUND_DEFER_TIME = 0.4
Detailed Description
Definition at line 1 of file flashbangeffect.c.
Constructor & Destructor Documentation
FlashbangEffect()
void FlashbangEffect::FlashbangEffect (PlayerBase player, bool visual = true) inline private
naive time of the day selector
-1: night; 1: day
Definition at line 28 of file flashbangeffect.c.
    {
        m_Player = player;
        m_Visual = visual;
        m_Initialized = false;
        m_HitDuration = 8.0;
        m_BreakPoint = 2.5;
        m_AlphaMaxActual = ALPHA_MAX;
        m_SoundMaxActual = 1.0;
        m_ProgressMultiplier = 1.0;
        m_FlashbangEffectSound = null;
        if (m_Visual)
        {
            Class.CastTo(m_Requester,PPERequesterBank.GetRequester(PPERequester_FlashbangEffects));
            m_Requester.Start();
        }
        m_DeferAttenuation = new ref Timer();
        m_DeferAttenuation.Run(SOUND_DEFER_TIME, this, "PlaySound", null, false);
        m_DayTimeToggle = 5;
        if ( g_Game.GetDayTime() >= 22.0 || g_Game.GetDayTime() < 7.0 )
        {
            m_DayTimeToggle = 10;
        }
    }
References ALPHA_MAX, Class::CastTo(), g_Game, m_AlphaMaxActual, m_BreakPoint, m_DayTimeToggle, m_DeferAttenuation, m_FlashbangEffectSound, m_HitDuration, m_Initialized, m_Player, m_ProgressMultiplier, m_Requester, m_SoundMaxActual, m_Visual, and SOUND_DEFER_TIME.
~FlashbangEffect()
void FlashbangEffect::~FlashbangEffect () inline private
Definition at line 59 of file flashbangeffect.c.
    {
        if ( m_Visual )
        {
            ClearVisual();
        }
        if ( m_Player )
        {
            m_Player.OnPlayerReceiveFlashbangHitEnd();
        }
        if ( m_DeferAttenuation.IsRunning() )
        {
            m_DeferAttenuation.Stop();
        }
        m_DeferAttenuation = null;
        SEffectManager.DestroyEffect(m_FlashbangEffectSound);
    }
References ClearVisual(), SEffectManager::DestroyEffect(), m_DeferAttenuation, m_FlashbangEffectSound, m_Player, and m_Visual.
Member Function Documentation
ClearVisual()
protected void FlashbangEffect::ClearVisual () inline private
Definition at line 147 of file flashbangeffect.c.
    {
        if (m_Requester)
        {
            m_Requester.Stop();
        }
    }
References m_Requester.
Referenced by ~FlashbangEffect().
PlaySound()
protected void FlashbangEffect::PlaySound () inline private
Definition at line 94 of file flashbangeffect.c.
    {
        if ( !m_Initialized )
        {
            Error("" + this + " not initialized");
            return;
        }
        vector pos;
        MiscGameplayFunctions.GetHeadBonePos(m_Player, pos);
        if (!m_FlashbangEffectSound)
        {
            m_FlashbangEffectSound = SEffectManager.CreateSound("Tinnitus_SoundSet", pos);
        }
        if (!m_FlashbangEffectSound.IsPlaying())
        {
            m_FlashbangEffectSound.SetParent(m_Player);
            m_FlashbangEffectSound.SetAttachedLocalPos(m_Player.WorldToModel(pos));
            m_FlashbangEffectSound.SetSoundWaveKind(WaveKind.WAVEEFFECTEX);
            m_FlashbangEffectSound.SetSoundFadeIn(4 * Math.Clamp(m_ProgressMultiplier,0.5,1.0)); //TODO
            m_SoundStopTime = 2 * Math.Clamp(m_ProgressMultiplier,0.5,1.0);
            m_FlashbangEffectSound.SetSoundFadeOut(m_SoundStopTime); //TODO
            m_FlashbangEffectSound.SetSoundMaxVolume(Math.Clamp(m_SoundMaxActual,0.1,1.0)); //TODO
            m_FlashbangEffectSound.SetSoundLoop(true);
            m_FlashbangEffectSound.SoundPlay();
            SetAttenuationFilter();
        }
    }
References Math::Clamp(), SEffectManager::CreateSound(), Error(), EffectSound::IsPlaying(), m_FlashbangEffectSound, m_Initialized, m_Player, m_ProgressMultiplier, m_SoundMaxActual, m_SoundStopTime, SetAttenuationFilter(), EffectSound::SetParent(), EffectSound::SetSoundFadeIn(), EffectSound::SetSoundFadeOut(), EffectSound::SetSoundLoop(), EffectSound::SetSoundMaxVolume(), EffectSound::SetSoundWaveKind(), and EffectSound::SoundPlay().
ResetAttenuationFilter()
protected void FlashbangEffect::ResetAttenuationFilter () inline private
Definition at line 134 of file flashbangeffect.c.
    {
        m_Player.SetMasterAttenuation("");
    }
References m_Player.
Referenced by Update().
SetAttenuationFilter()
protected void FlashbangEffect::SetAttenuationFilter () inline private
Definition at line 126 of file flashbangeffect.c.
    {
        if ( !m_DeferAttenuation.IsRunning() || m_Player.GetMasterAttenuation() != "FlashbangAttenuation" )
        {
            m_Player.SetMasterAttenuation("FlashbangAttenuation");
        }
    }
References m_DeferAttenuation, and m_Player.
Referenced by PlaySound().
SetupFlashbangValues()
void FlashbangEffect::SetupFlashbangValues (float progress_mult = 1.0, float visual_value_max = 1.0, float sound_value_max = 1.0) inline private
Definition at line 80 of file flashbangeffect.c.
    {
        if ( !m_Initialized )
        {
            m_Initialized = true;
            m_ProgressMultiplier = progress_mult;
            m_AlphaMaxActual = visual_value_max;
            m_SoundMaxActual = sound_value_max;
            m_HitDuration *= m_ProgressMultiplier;
            m_BreakPoint *= m_ProgressMultiplier;
        }
    }
References m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_ProgressMultiplier, and m_SoundMaxActual.
SetVisual()
protected void FlashbangEffect::SetVisual (float val) inline private
Definition at line 155 of file flashbangeffect.c.
    {
        if (m_Requester && m_Requester.IsRequesterRunning())
        {
            m_Requester.SetFlashbangIntensity(val, m_DayTimeToggle);
        }
    }
References m_DayTimeToggle, and m_Requester.
Referenced by Update().
Stop()
void FlashbangEffect::Stop () inline private
Definition at line 163 of file flashbangeffect.c.
    {
        StopSound();
    }
References StopSound().
StopSound()
protected void FlashbangEffect::StopSound () inline private
Definition at line 139 of file flashbangeffect.c.
    {
        if (m_FlashbangEffectSound)
        {
            m_FlashbangEffectSound.SoundStop();
        }
    }
References m_FlashbangEffectSound, and EffectSound::SoundStop().
Referenced by Stop(), and Update().
Update()
void FlashbangEffect::Update (float deltatime) inline private
Definition at line 168 of file flashbangeffect.c.
    {
        if ( !m_Initialized )
        {
            Error("" + this + " not initialized");
        }
        else if ( m_Visual )
        {
            float value;
            if ( m_TimeActive <= m_BreakPoint )
            {
                value = m_AlphaMaxActual;
                //Print("Flashbango | m_AlphaMaxActual: " + value);
            }
            else
            {
                value = Math.InverseLerp(m_HitDuration - m_BreakPoint, m_HitDuration, m_TimeActive);
                value = Math.Clamp(value,0.0,1.0);
                value = m_AlphaMaxActual - value * m_AlphaMaxActual;
                //Print("Flashbango | tmp_value: " + value);
            }
            SetVisual(value);
        }
        m_TimeActive += deltatime;
        if (m_TimeActive >= m_HitDuration - m_SoundStopTime)
        {
            StopSound();
        }
        if (m_TimeActive >= m_HitDuration)
        {
            ResetAttenuationFilter();
            delete this;
        }
    }
References Math::Clamp(), Error(), Math::InverseLerp(), m_AlphaMaxActual, m_BreakPoint, m_HitDuration, m_Initialized, m_SoundStopTime, m_TimeActive, m_Visual, ResetAttenuationFilter(), SetVisual(), and StopSound().
Member Data Documentation
ALPHA_MAX
protected const float FlashbangEffect::ALPHA_MAX = 1.0 private
Definition at line 4 of file flashbangeffect.c.
Referenced by FlashbangEffect().
ALPHA_MIN
protected const float FlashbangEffect::ALPHA_MIN = 0.0 private
Definition at line 3 of file flashbangeffect.c.
m_AlphaMaxActual
protected float FlashbangEffect::m_AlphaMaxActual private
Definition at line 13 of file flashbangeffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_BreakPoint
protected float FlashbangEffect::m_BreakPoint private
Definition at line 9 of file flashbangeffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_DayTimeToggle
protected float FlashbangEffect::m_DayTimeToggle private
Definition at line 11 of file flashbangeffect.c.
Referenced by FlashbangEffect(), and SetVisual().
m_DeferAttenuation
protected ref Timer FlashbangEffect::m_DeferAttenuation private
Definition at line 24 of file flashbangeffect.c.
Referenced by FlashbangEffect(), SetAttenuationFilter(), and ~FlashbangEffect().
m_FlashbangEffectSound
protected EffectSound FlashbangEffect::m_FlashbangEffectSound private
Definition at line 21 of file flashbangeffect.c.
Referenced by FlashbangEffect(), PlaySound(), StopSound(), and ~FlashbangEffect().
m_HitDuration
protected float FlashbangEffect::m_HitDuration private
SFX will be played ~0.5s AFTER VFX.
Definition at line 8 of file flashbangeffect.c.
Referenced by FlashbangEffect(), SetupFlashbangValues(), and Update().
m_Initialized
protected bool FlashbangEffect::m_Initialized private
Definition at line 18 of file flashbangeffect.c.
Referenced by FlashbangEffect(), PlaySound(), SetupFlashbangValues(), and Update().
m_Player
protected PlayerBase FlashbangEffect::m_Player private
Definition at line 20 of file flashbangeffect.c.
Referenced by FlashbangEffect(), PlaySound(), ResetAttenuationFilter(), SetAttenuationFilter(), and ~FlashbangEffect().
m_ProgressMultiplier
protected float FlashbangEffect::m_ProgressMultiplier private
Definition at line 15 of file flashbangeffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_Requester
protected PPERequester_FlashbangEffects FlashbangEffect::m_Requester private
Definition at line 26 of file flashbangeffect.c.
Referenced by ClearVisual(), FlashbangEffect(), and SetVisual().
m_SoundMaxActual
protected float FlashbangEffect::m_SoundMaxActual private
Definition at line 14 of file flashbangeffect.c.
Referenced by FlashbangEffect(), PlaySound(), and SetupFlashbangValues().
m_SoundStopTime
protected float FlashbangEffect::m_SoundStopTime private
Definition at line 22 of file flashbangeffect.c.
Referenced by PlaySound(), and Update().
m_TimeActive
protected float FlashbangEffect::m_TimeActive private
Definition at line 10 of file flashbangeffect.c.
Referenced by Update().
m_Visual
protected bool FlashbangEffect::m_Visual private
Definition at line 17 of file flashbangeffect.c.
Referenced by FlashbangEffect(), Update(), and ~FlashbangEffect().
SOUND_DEFER_TIME
protected const float FlashbangEffect::SOUND_DEFER_TIME = 0.4 private
Definition at line 6 of file flashbangeffect.c.
Referenced by FlashbangEffect().