DayzKode: VONManager Class Reference
VONManager Class Reference
Manager class which handles Voice-over-network functionality while player is connected to a server.
Static Private Member Functions
static void CleanupInstance ()
Uninitializes VONManager, runs when user disconnects from server.
static VONManagerBase GetInstance ()
Main way to access VONManager functionality from script.
static void Init ()
Initializes VONManager, runs when user first connects to a server.
static bool IsVoiceThresholdMinimum ()
Specifies whether user's voice activation threshold value is equal to the minimum voice activation threshold value.
static bool IsVONToggled ()
Specifies whether VON mode is toggled or not.
Static Private Attributes
static private ref VONManagerBase m_VONManager = new VONManagerBase()
Detailed Description
Manager class which handles Voice-over-network functionality while player is connected to a server.
Definition at line 300 of file vonmanager.c.
Member Function Documentation
CleanupInstance()
static void VONManager::CleanupInstance () inline static private
Uninitializes VONManager, runs when user disconnects from server.
Definition at line 325 of file vonmanager.c.
    {
        delete m_VONManager;
        m_VONManager = new VONManagerBase();
    }
References m_VONManager.
Referenced by CGame::~CGame().
GetInstance()
static VONManagerBase VONManager::GetInstance () inline static private
Main way to access VONManager functionality from script.
Returns
Instance of VONManagerImplementation if logged on to server, or VONManagerBase otherwise
Definition at line 308 of file vonmanager.c.
    {
        return m_VONManager;
    }
References m_VONManager.
Referenced by OnEvent(), MissionBase::OnUpdate(), and ScriptedWidgetEventHandler::OptionsMenuSounds().
Init()
static void VONManager::Init () inline static private
Initializes VONManager, runs when user first connects to a server.
Definition at line 316 of file vonmanager.c.
    {
        delete m_VONManager;
        m_VONManager = new VONManagerImplementation();
    }
References m_VONManager, and VONManagerImplementation().
Referenced by CGame::CGame().
IsVoiceThresholdMinimum()
static bool VONManager::IsVoiceThresholdMinimum () inline static private
Specifies whether user's voice activation threshold value is equal to the minimum voice activation threshold value.
Returns
True if threshold minimum, false otherwise
Definition at line 344 of file vonmanager.c.
    {
        GameOptions gameOptions = new GameOptions();
        NumericOptionsAccess noa;
        Class.CastTo(noa, gameOptions.GetOptionByType( OptionAccessType.AT_OPTIONS_VON_THRESHOLD_SLIDER ));
        return noa.ReadValue() <= GetGame().GetSoundScene().GetSilenceThreshold();
    }
References Class::CastTo(), GetGame(), GameOptions::GetOptionByType(), and CGame::GetSoundScene().
Referenced by HandleInput(), OnEvent(), and OnVOIPThresholdChanged().
IsVONToggled()
static bool VONManager::IsVONToggled () inline static private
Specifies whether VON mode is toggled or not.
Returns
True if in Voice Activation mode, False if in Push-to-Talk mode
Definition at line 335 of file vonmanager.c.
    {
        return m_VONManager.IsVonToggled();
    }
References VONManagerBase::IsVonToggled(), and m_VONManager.
Member Data Documentation
m_VONManager
private ref VONManagerBase VONManager::m_VONManager = new VONManagerBase() static private
Definition at line 302 of file vonmanager.c.
Referenced by CleanupInstance(), GetInstance(), Init(), and IsVONToggled().