DayzKode: ActionRepositionPluggedItem Class Reference
ActionRepositionPluggedItem Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRepositionPluggedItem ()
override bool CanBeUsedOnBack ()
override bool CanContinue (ActionData action_data)
override void CreateAndSetupActionCallback (ActionData action_data)
override GetInputType ()
override bool HasProgress ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override void Start (ActionData action_data)
Private Attributes
protected ItemBase m_SourceForReplug = NULL
Detailed Description
Definition at line 1 of file actionrepositionpluggeditem.c.
Constructor & Destructor Documentation
ActionRepositionPluggedItem()
void ActionRepositionPluggedItem::ActionRepositionPluggedItem () inline private
Definition at line 6 of file actionrepositionpluggeditem.c.
    {
        m_CallbackClass = ActionInteractBaseCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        /*m_CallbackClass = ActionBuildPartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;*/
        m_Text = "#reposition";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionRepositionPluggedItem::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 124 of file actionrepositionpluggeditem.c.
    {
        ItemBase tgt_item = ItemBase.Cast( target.GetObject() );
        EntityAI tgt_parent = EntityAI.Cast(tgt_item.GetHierarchyParent());
        if ( !tgt_item || !tgt_item.IsTakeable() || tgt_item.IsBeingPlaced() || (tgt_item.GetCompEM() && !tgt_item.GetCompEM().IsPlugged()) || ( tgt_item.GetHierarchyParent() && !BaseBuildingBase.Cast(tgt_item.GetHierarchyParent()) ) || ((tgt_parent && !tgt_item.CanDetachAttachment(tgt_parent)) || (tgt_parent && !tgt_parent.CanReleaseAttachment(tgt_item))) )
            return false;
        if ( tgt_item.HasEnergyManager() && tgt_item.GetCompEM().IsPlugged() )
        {
            return player.GetInventory().CanAddEntityIntoHands(tgt_item);
        }
        return false;
    }
References ItemBase::CanDetachAttachment(), and ItemBase::IsTakeable().
CanBeUsedOnBack()
override bool ActionRepositionPluggedItem::CanBeUsedOnBack () inline private
Definition at line 195 of file actionrepositionpluggeditem.c.
    {
        return false;
    }
CanContinue()
override bool ActionRepositionPluggedItem::CanContinue (ActionData action_data) inline private
Definition at line 139 of file actionrepositionpluggeditem.c.
    {
        return true;
    }
CreateAndSetupActionCallback()
override void ActionRepositionPluggedItem::CreateAndSetupActionCallback (ActionData action_data) inline private
Definition at line 172 of file actionrepositionpluggeditem.c.
    {
        //Print("starting - CreateAndSetupActionCallback");
        EntityAI target = EntityAI.Cast(action_data.m_Target.GetObject());
        ActionBaseCB callback;
        if (!target)
            return;
        if (target.IsHeavyBehaviour())
        {
            //Print("heavybehaviour");
            Class.CastTo(callback, action_data.m_Player.StartCommand_Action(DayZPlayerConstants.CMD_ACTIONFB_PICKUP_HEAVY,GetCallbackClassTypename(),DayZPlayerConstants.STANCEMASK_ERECT));
        }
        else
        {
            Class.CastTo(callback, action_data.m_Player.AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_HANDS,GetCallbackClassTypename()));
        }
        callback.SetActionData(action_data);
        callback.InitActionComponent();
        action_data.m_Callback = callback;
    }
References Class::CastTo(), AnimatedActionBase::GetCallbackClassTypename(), ActionBaseCB::InitActionComponent(), ActionData::m_Callback, ActionData::m_Player, ActionData::m_Target, and ActionBaseCB::SetActionData().
GetInputType()
override ActionRepositionPluggedItem::GetInputType () inline private
Definition at line 18 of file actionrepositionpluggeditem.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionRepositionPluggedItem::HasProgress () inline private
Definition at line 23 of file actionrepositionpluggeditem.c.
    {
        return false;
    }
OnExecuteClient()
override void ActionRepositionPluggedItem::OnExecuteClient (ActionData action_data) inline private
Definition at line 163 of file actionrepositionpluggeditem.c.
    {
        InventoryLocation il = new InventoryLocation;
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        ClearInventoryReservationEx(action_data);
        action_data.m_Player.PredictiveTakeEntityToHands( ntarget );
    }
References ClearInventoryReservationEx(), ActionData::m_Player, and ActionData::m_Target.
OnExecuteServer()
override void ActionRepositionPluggedItem::OnExecuteServer (ActionData action_data) inline private
Definition at line 151 of file actionrepositionpluggeditem.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        InventoryLocation il = new InventoryLocation;
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        ClearInventoryReservationEx(action_data);
        action_data.m_Player.PredictiveTakeEntityToHands( ntarget );
    }
References ClearInventoryReservationEx(), GetGame(), ActionData::m_Player, and ActionData::m_Target.
Start()
override void ActionRepositionPluggedItem::Start (ActionData action_data) inline private
Definition at line 144 of file actionrepositionpluggeditem.c.
    {
        super.Start( action_data );
        ItemBase ntarget = ItemBase.Cast(action_data.m_Target.GetObject());
        action_data.m_Player.TogglePlacingLocal(ntarget);
    }
References ActionData::m_Player, and ActionData::m_Target.
Member Data Documentation
m_SourceForReplug
protected ItemBase ActionRepositionPluggedItem::m_SourceForReplug = NULL private
Definition at line 3 of file actionrepositionpluggeditem.c.