DayzKode: ActionPlugIn Class Reference
ActionPlugIn Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionPlugIn ()
override void CreateConditionComponents ()
ItemBase GetAttachedDevice (ItemBase parent)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void Process (ActionData action_data)
Detailed Description
Definition at line 1 of file actionplugin.c.
Constructor & Destructor Documentation
ActionPlugIn()
void ActionPlugIn::ActionPlugIn () inline private
Definition at line 3 of file actionplugin.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE;
        m_Text = "#plug_in";
    }
References AnimatedActionBase::m_CommandUID, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionPlugIn::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 15 of file actionplugin.c.
    {
        if ( player.IsPlacingLocal() )
            return false;
        ItemBase target_IB = ItemBase.Cast( target.GetObject() );
        //Prevent plugging to items in inventory
        if ( target_IB && target_IB.GetHierarchyRoot() == target_IB &&  item )
        {
            if ( item.HasEnergyManager()  &&  !item.GetCompEM().IsPlugged()  &&  target_IB.HasEnergyManager()  &&  target_IB.GetCompEM().CanReceivePlugFrom(item) )
            {
                return true;
            }
            ItemBase attached_device = GetAttachedDevice(target_IB);
            //Will only ever affect batteries
            if ( attached_device )
            {
                if ( attached_device.GetCompEM().HasFreeSocket() )
                    return true;
            }
        }
        return false;
    }
References GetAttachedDevice().
CreateConditionComponents()
override void ActionPlugIn::CreateConditionComponents () inline private
Definition at line 9 of file actionplugin.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetAttachedDevice()
ItemBase ActionPlugIn::GetAttachedDevice (ItemBase parent) inline private
Definition at line 86 of file actionplugin.c.
    {
        string parent_type = parent.GetType();
        if ( parent.IsInherited(CarBattery)  ||  parent.IsInherited(TruckBattery) )
        {
            ItemBase parent_attachment = ItemBase.Cast( parent.GetAttachmentByType(MetalWire) );
            if (!parent_attachment)
            {
                parent_attachment = ItemBase.Cast( parent.GetAttachmentByType(BarbedWire) );
            }
            return parent_attachment;
        }
        return NULL;
    }
Referenced by ActionCondition(), and OnExecuteServer().
OnExecuteClient()
override void ActionPlugIn::OnExecuteClient (ActionData action_data) inline private
Definition at line 74 of file actionplugin.c.
    {
        if ( !action_data.m_Player.IsPlacingLocal() )
        {
            action_data.m_Player.TogglePlacingLocal();
        }
        else
        {
            Process(action_data);
        }
    }
References ActionData::m_Player, and Process().
OnExecuteServer()
override void ActionPlugIn::OnExecuteServer (ActionData action_data) inline private
Definition at line 43 of file actionplugin.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        ItemBase target_IB = ItemBase.Cast( targetObject );
        if ( target_IB.HasEnergyManager() )
        {
            ItemBase attached_device = GetAttachedDevice(target_IB);
            if (attached_device)
            {
                target_IB = attached_device;
            }
            action_data.m_MainItem.GetCompEM().PlugThisInto(target_IB);
            if ( !action_data.m_Player.IsPlacingServer() )
            {
                Process(action_data);
            }
        }
    }
References GetAttachedDevice(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and Process().
Process()
void ActionPlugIn::Process (ActionData action_data) inline private
Definition at line 66 of file actionplugin.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        ItemBase target_IB = ItemBase.Cast( targetObject );
        target_IB.GetInventory().TakeEntityAsAttachment( InventoryMode.LOCAL, action_data.m_MainItem );
    }
References ActionData::m_MainItem, and ActionData::m_Target.
Referenced by OnExecuteClient(), and OnExecuteServer().