DayzKode: RightArea Class Reference
RightArea Class Reference
Private Member Functions
override bool Combine ()
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override bool EquipItem ()
override void ExpandCollapseContainer ()
float GetCurrentContainerBottomY ()
float GetCurrentContainerTopY ()
PlayerContainer GetPlayerContainer ()
override ScrollWidget GetScrollWidget ()
bool HasEntityContainerVisible (EntityAI entity)
override bool InspectItem ()
bool IsPlayerEquipmentActive ()
void MoveUpDownIcons ()
override void OnShow ()
override void Refresh ()
void RightArea (LayoutHolder parent)
override bool Select ()
override bool SelectItem ()
override void SetLayoutName ()
override void SetParentWidget ()
override bool SplitItem ()
void SwapItemsInOrder (int slot1, int slot2)
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void UnfocusGrid ()
override void UpdateInterval ()
override void UpdateSelectionIcons ()
Private Attributes
protected Widget m_ContentParent
protected ref SizeToChild m_ContentResize
protected Widget m_DownIcon
ref PlayerContainer m_PlayerContainer
protected bool m_ProcessGridMovement
protected ScrollWidget m_ScrollWidget
protected bool m_ShouldChangeSize = true
protected Widget m_UpIcon
Detailed Description
Definition at line 1 of file rightarea.c.
Constructor & Destructor Documentation
RightArea()
void RightArea::RightArea (LayoutHolder parent) inline private
Definition at line 14 of file rightarea.c.
    {
        m_MainWidget.Show(true);
        m_ScrollWidget  = ScrollWidget.Cast( m_MainWidget.FindAnyWidget( "Scroller" ) );
        m_MainWidget        = m_MainWidget.FindAnyWidget("Content");
        //m_ContentParent       = m_RootWidget.FindAnyWidget("ContentParent");
        m_PlayerContainer   = new PlayerContainer(this, false);
        m_PlayerContainer.SetPlayer(PlayerBase.Cast(GetGame().GetPlayer()));
        m_Body.Insert(m_PlayerContainer);
        m_ActiveIndex = 0;
        m_ProcessGridMovement = false;
        m_UpIcon        = m_RootWidget.FindAnyWidget( "Up" );
        m_DownIcon      = m_RootWidget.FindAnyWidget( "Down" );
        //m_ContentParent.GetScript( m_ContentResize );
        RecomputeOpenedContainers();
    }
References GetGame(), GetPlayer(), m_DownIcon, m_PlayerContainer, m_ProcessGridMovement, m_RootWidget, m_ScrollWidget, m_UpIcon, and PlayerContainer::SetPlayer().
Member Function Documentation
Combine()
override bool RightArea::Combine () inline private
Definition at line 54 of file rightarea.c.
    {
        return m_PlayerContainer.Combine();
    }
References PlayerContainer::Combine(), and m_PlayerContainer.
Referenced by UpdateInterval().
DraggingOverHeader()
override void RightArea::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 39 of file rightarea.c.
    {
        m_PlayerContainer.DraggingOverHeader(w, x, y, receiver);
    }
References PlayerContainer::DraggingOverHeader(), m_PlayerContainer, x, and y.
Referenced by DraggingOverRightPanel().
EquipItem()
override bool RightArea::EquipItem () inline private
Definition at line 64 of file rightarea.c.
    {
        return m_PlayerContainer.EquipItem();
    }
References PlayerContainer::EquipItem(), and m_PlayerContainer.
Referenced by UpdateInterval().
ExpandCollapseContainer()
override void RightArea::ExpandCollapseContainer () inline private
Definition at line 104 of file rightarea.c.
    {
        m_PlayerContainer.ExpandCollapseContainer();
    }
References PlayerContainer::ExpandCollapseContainer(), and m_PlayerContainer.
Referenced by UpdateInterval().
GetCurrentContainerBottomY()
float RightArea::GetCurrentContainerBottomY () inline private
Definition at line 218 of file rightarea.c.
    {
        float x, y;
        GetMainWidget().Update();
        GetMainWidget().GetScreenPos( x, y );
        float cont_screen_pos       = GetFocusedContainerYScreenPos();
        float cont_screen_height    = GetFocusedContainerHeight();
        return cont_screen_pos - y + cont_screen_height;
    }
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetCurrentContainerTopY()
float RightArea::GetCurrentContainerTopY () inline private
Definition at line 208 of file rightarea.c.
    {
        float x, y;
        GetMainWidget().Update();
        GetMainWidget().GetScreenPos( x, y );
        float cont_screen_pos = GetFocusedContainerYScreenPos();
        return cont_screen_pos - y;
    }
References Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by MoveUpDownIcons().
GetPlayerContainer()
PlayerContainer RightArea::GetPlayerContainer () inline private
Definition at line 34 of file rightarea.c.
    {
        return m_PlayerContainer;
    }
References m_PlayerContainer.
Referenced by UpdateConsoleToolbar().
GetScrollWidget()
override ScrollWidget RightArea::GetScrollWidget () inline private
Definition at line 195 of file rightarea.c.
    {
        return m_ScrollWidget;
    }
References m_ScrollWidget.
HasEntityContainerVisible()
bool RightArea::HasEntityContainerVisible (EntityAI entity) inline private
Definition at line 89 of file rightarea.c.
    {
        return m_PlayerContainer.HasEntityContainerVisible(entity);
    }
References PlayerContainer::HasEntityContainerVisible(), and m_PlayerContainer.
InspectItem()
override bool RightArea::InspectItem () inline private
Definition at line 74 of file rightarea.c.
    {
        return m_PlayerContainer.InspectItem();
    }
References PlayerContainer::InspectItem(), and m_PlayerContainer.
Referenced by UpdateInterval().
IsPlayerEquipmentActive()
bool RightArea::IsPlayerEquipmentActive () inline private
Definition at line 99 of file rightarea.c.
    {
        return m_PlayerContainer.IsPlayerEquipmentActive();
    }
References PlayerContainer::IsPlayerEquipmentActive(), and m_PlayerContainer.
Referenced by UpdateConsoleToolbar().
MoveUpDownIcons()
void RightArea::MoveUpDownIcons () inline private
Definition at line 156 of file rightarea.c.
    {
        if (m_UpIcon && m_DownIcon)
        {
            m_UpIcon.Show( m_IsActive );
            m_DownIcon.Show( m_IsActive );
            if( m_IsActive )
            {
                float x, y;
                m_UpIcon.GetScreenSize( x, y );
                float top_y     = GetCurrentContainerTopY();
                m_UpIcon.SetPos( 0, Math.Clamp( top_y, 0, 99999 ) );
                #ifndef PLATFORM_CONSOLE
                float x2, y2;
                m_DownIcon.GetScreenSize( x2, y2 );
                float bottom_y  = GetCurrentContainerBottomY() - y2;
                float diff      = bottom_y - ( top_y + y );
                if( diff < 0 )
                {
                    top_y += diff / 2;
                    bottom_y -= diff / 2;
                }
                m_DownIcon.SetPos( 0, bottom_y );
                #endif
            }
        }
        /*else
        {
            ErrorEx("up/down icons not present!");
        }
        #else
        m_ScrollWidget.Update();
        #endif*/
    }
References Math::Clamp(), GetCurrentContainerBottomY(), GetCurrentContainerTopY(), m_DownIcon, m_IsActive, m_UpIcon, x, and y.
Referenced by UpdateSelectionIcons().
OnShow()
override void RightArea::OnShow () inline private
Definition at line 142 of file rightarea.c.
    {
        super.OnShow();
        Refresh();
    }
References Refresh().
Refresh()
override void RightArea::Refresh () inline private
Definition at line 109 of file rightarea.c.
    {
        m_ScrollWidget.Update();
        m_PlayerContainer.Refresh();
        m_ShouldChangeSize = true;
    }
References m_PlayerContainer, m_ScrollWidget, m_ShouldChangeSize, and PlayerContainer::Refresh().
Referenced by OnShow(), Refresh(), and Reset().
Select()
override bool RightArea::Select () inline private
Definition at line 44 of file rightarea.c.
    {
        return m_PlayerContainer.Select();
    }
References m_PlayerContainer, and PlayerContainer::Select().
Referenced by UpdateInterval().
SelectItem()
override bool RightArea::SelectItem () inline private
Definition at line 49 of file rightarea.c.
    {
        return m_PlayerContainer.SelectItem();
    }
References m_PlayerContainer, and Container::SelectItem().
Referenced by EnableMicromanagement().
SetLayoutName()
override void RightArea::SetLayoutName () inline private
Definition at line 116 of file rightarea.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_LayoutName = WidgetLayoutName.RightAreaXbox;
        #else
            switch (InventoryMenu.GetWidthType())
            {
            case ScreenWidthType.NARROW:
                m_LayoutName = WidgetLayoutName.RightAreaNarrow;
            break;
            case ScreenWidthType.MEDIUM:
                m_LayoutName = WidgetLayoutName.RightAreaMedium;
            break;
            case ScreenWidthType.WIDE:
                m_LayoutName = WidgetLayoutName.RightAreaWide;
            break;
            }
        #endif
    }
References InventoryMenu(), WidgetLayoutName::RightAreaMedium, WidgetLayoutName::RightAreaNarrow, WidgetLayoutName::RightAreaWide, and WidgetLayoutName::RightAreaXbox.
SetParentWidget()
override void RightArea::SetParentWidget () inline private
Definition at line 137 of file rightarea.c.
    {
        m_ParentWidget = m_Parent.GetMainWidget().FindAnyWidget("RightPanel");
    }
References m_Parent.
SplitItem()
override bool RightArea::SplitItem () inline private
Definition at line 59 of file rightarea.c.
    {
        return m_PlayerContainer.SplitItem();
    }
References m_PlayerContainer, and PlayerContainer::SplitItem().
Referenced by UpdateInterval().
SwapItemsInOrder()
void RightArea::SwapItemsInOrder (int slot1, int slot2) inline private
Definition at line 94 of file rightarea.c.
    {
        m_PlayerContainer.SwapItemsInOrder(slot1, slot2);
    }
References m_PlayerContainer, and PlayerContainer::SwapItemsInOrder().
TransferItem()
override bool RightArea::TransferItem () inline private
Definition at line 69 of file rightarea.c.
    {
        return m_PlayerContainer.TransferItem();
    }
References m_PlayerContainer, and PlayerContainer::TransferItem().
TransferItemToVicinity()
override bool RightArea::TransferItemToVicinity () inline private
Definition at line 79 of file rightarea.c.
    {
        return m_PlayerContainer.TransferItemToVicinity();
    }
References m_PlayerContainer, and PlayerContainer::TransferItemToVicinity().
Referenced by UpdateInterval().
UnfocusGrid()
override void RightArea::UnfocusGrid () inline private
Definition at line 84 of file rightarea.c.
    {
        m_PlayerContainer.UnfocusGrid();
    }
References m_PlayerContainer.
Referenced by MoveFocusByArea(), ResetFocusedContainers(), and UpdateInterval().
UpdateInterval()
override void RightArea::UpdateInterval () inline private
Definition at line 148 of file rightarea.c.
    {
        super.UpdateInterval();
        m_PlayerContainer.UpdateInterval();
        CheckScrollbarVisibility();
    }
References m_PlayerContainer, and PlayerContainer::UpdateInterval().
Referenced by UpdateInterval().
UpdateSelectionIcons()
override void RightArea::UpdateSelectionIcons () inline private
Definition at line 200 of file rightarea.c.
    {
        #ifdef PLATFORM_CONSOLE
            ScrollToActiveContainer();
        #endif
        MoveUpDownIcons();
    }
References MoveUpDownIcons().
Member Data Documentation
m_ContentParent
protected Widget RightArea::m_ContentParent private
Definition at line 4 of file rightarea.c.
m_ContentResize
protected ref SizeToChild RightArea::m_ContentResize private
Definition at line 10 of file rightarea.c.
m_DownIcon
protected Widget RightArea::m_DownIcon private
Definition at line 8 of file rightarea.c.
Referenced by MoveUpDownIcons(), and RightArea().
m_PlayerContainer
ref PlayerContainer RightArea::m_PlayerContainer private
Definition at line 3 of file rightarea.c.
Referenced by Combine(), DraggingOverHeader(), EquipItem(), ExpandCollapseContainer(), GetPlayerContainer(), HasEntityContainerVisible(), InspectItem(), IsPlayerEquipmentActive(), Refresh(), RightArea(), Select(), SelectItem(), SplitItem(), SwapItemsInOrder(), TransferItem(), TransferItemToVicinity(), UnfocusGrid(), and UpdateInterval().
m_ProcessGridMovement
protected bool RightArea::m_ProcessGridMovement private
Definition at line 12 of file rightarea.c.
Referenced by RightArea().
m_ScrollWidget
protected ScrollWidget RightArea::m_ScrollWidget private
Definition at line 6 of file rightarea.c.
Referenced by GetScrollWidget(), Refresh(), and RightArea().
m_ShouldChangeSize
protected bool RightArea::m_ShouldChangeSize = true private
Definition at line 11 of file rightarea.c.
Referenced by Refresh().
m_UpIcon
protected Widget RightArea::m_UpIcon private
Definition at line 7 of file rightarea.c.
Referenced by MoveUpDownIcons(), and RightArea().