DayzKode: DayZPlayerTypeUtils Class Reference
DayZPlayerTypeUtils Class Reference
Static Private Member Functions
static void DayZPlayerTypeCreate (DayZPlayerType pType)
static void DayZPlayerTypeInitMovement (DayZPlayerType pType)
Detailed Description
Definition at line 17 of file dayzplayercfgbase.c.
Member Function Documentation
DayZPlayerTypeCreate()
static void DayZPlayerTypeUtils::DayZPlayerTypeCreate (DayZPlayerType pType) inline static private
register all item types
register all sounds
register camera creators
other configs
look limits look limits
aiming limits
camera shoot params
register hit components for AI melee
Definition at line 19 of file dayzplayercfgbase.c.
    {
        //  Print("DayZPlayerTypeCreate called");
        DayZPlayerTypeRegisterItems(pType);
        DayZPlayerTypeRegisterSounds(pType);
        DayZPlayerCameras.RegisterCameras(pType);
        pType.SetLookLimits(-85, 85, -160, 160);
        pType.SetAimLimits(-85, 85, -180, 180);
        pType.SetCameraShootParams(250, 0.01, 0.866);
        pType.RegisterHitComponentsForAI();
    }
References DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), and DayZPlayerCameras::RegisterCameras().
Referenced by DayZPlayerTypeCreate().
DayZPlayerTypeInitMovement()
static void DayZPlayerTypeUtils::DayZPlayerTypeInitMovement (DayZPlayerType pType) inline static private
set move settings:
run sprint (SHIFT HOLD) filter
< filter span value [s]
< filter speed value [val/s]
WSAD direction filter
< direction filter timeout [s]
< sprint direction filter timeout [s]
< direction filter max rot speed [rad/s]
< max sprint angle [rad]
< this is when char starts tu turn
< this is end norm time (turn amount is not updated after this time)
< this is norm time when new turn from old turn is evaluated again (turn->turn)
<
<
<
<
< Water level (in meters) - m_iMaxSpeedNormal_WaterLevelLow and m_iMaxSpeedFast_WaterLevelLow are applied when character is deeper
< Water level (in meters) - m_iMaxSpeedNormal_WaterLevelHigh and m_iMaxSpeedFast_WaterLevelHigh are applied when character is deeper
< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
Definition at line 48 of file dayzplayercfgbase.c.
    {
        //--------------------------------------------------------------
        // VIKTOR, JOHNNY - nastaveni Movu !!!
        SHumanCommandMoveSettings hmcs = pType.CommandMoveSettingsW();
        hmcs.m_fRunSpringTimeout            = CfgGameplayHandler.GetMovementTimeToSprint();
        hmcs.m_fRunSpringMaxChange          = 8.0;
        hmcs.m_fDirFilterTimeout            = CfgGameplayHandler.GetMovementTimeToStrafeJog();
        hmcs.m_fDirFilterSprintTimeout      = CfgGameplayHandler.GetMovementTimeToStrafeSprint();
        hmcs.m_fDirFilterSpeed              = Math.DEG2RAD * 360;
        hmcs.m_fMaxSprintAngle              = Math.DEG2RAD * 45.01;
        hmcs.m_fTurnAngle                   = 45;
        hmcs.m_fTurnEndUpdateNTime          = 0.7;
        hmcs.m_fTurnNextNTime               = 0.9;
        hmcs.m_fHeadingChangeLimiterIdle    = 500000;
        hmcs.m_fHeadingChangeLimiterWalk    = 2000;
        hmcs.m_fHeadingChangeLimiterRun     = 1500;
        hmcs.m_fLeaningSpeed                = 4.5;
        hmcs.m_fWaterLevelSpeedRectrictionLow   = 0.5;
        hmcs.m_fWaterLevelSpeedRectrictionHigh  = 1.0;
        //hmcs.m_iMaxSpeedNormal_WaterLevelLow  = 2;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedFast_WaterLevelLow        = 2;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedNormal_WaterLevelHigh = 1;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedFast_WaterLevelHigh       = 1;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
        // proposal 1
        //hmcs.m_iMaxSpeedNormal_WaterLevelLow  = 1;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedFast_WaterLevelLow        = 2;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedNormal_WaterLevelHigh = 1;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
        //hmcs.m_iMaxSpeedFast_WaterLevelHigh       = 1;            //!< Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
        // proposal 2
        hmcs.m_iMaxSpeedNormal_WaterLevelLow    = -1;
        hmcs.m_iMaxSpeedFast_WaterLevelLow      = -1;
        hmcs.m_iMaxSpeedNormal_WaterLevelHigh   = 1;
        hmcs.m_iMaxSpeedFast_WaterLevelHigh     = 2;
        //--------------------------------------------------------------
        // VIKTOR, JOHNNY, PETERN - nastaveni speedu animaci
        // DayZPlayerUtils.DebugOverrideAnimationSpeed("dz/anims/anm/player/moves/rifles/p_rfl_erc_runF_low.anm", 2.0);
        //DayZPlayerUtils.DebugOverrideAnimationTranslation("dz/anims/anm/player/moves/rifles/p_rfl_erc_runF_low.anm", "0 0 10" );
        //Melee evades
        //LEFT
        //DayZPlayerUtils.DebugOverrideAnimationSpeed("dz/anims/anm/player/moves/unarmed/p_erc_evadeL_ras.anm", 2.0);
        //DayZPlayerUtils.DebugOverrideAnimationTranslation("dz/anims/anm/player/moves/unarmed/p_erc_evadeL_ras.anm", "0 0 10");
        //RIGHT
        //DayZPlayerUtils.DebugOverrideAnimationSpeed("dz/anims/anm/player/moves/unarmed/p_erc_evadeR_ras.anm", 1);
        //DayZPlayerUtils.DebugOverrideAnimationTranslation("dz/anims/anm/player/moves/unarmed/p_erc_evadeR_ras.anm", "2 0 0");
        //BACK
        //DayZPlayerUtils.DebugOverrideAnimationSpeed("dz/anims/anm/player/moves/unarmed/p_erc_evadeB_ras.anm", 2.0);
        //DayZPlayerUtils.DebugOverrideAnimationTranslation("dz/anims/anm/player/moves/unarmed/p_erc_evadeB_ras.anm", "0 0 10");
    }
References Math::DEG2RAD, CfgGameplayHandler::GetMovementTimeToSprint(), CfgGameplayHandler::GetMovementTimeToStrafeJog(), CfgGameplayHandler::GetMovementTimeToStrafeSprint(), and SHumanCommandMoveSettings().
Referenced by DayZPlayerTypeInitMovement().