DayzKode: WeaponGuardBase Class Reference
WeaponGuardBase Class Reference
represents guard on a transition from state to state
Private Member Functions
void GuardAnd (WeaponGuardBase arg0=NULL, WeaponGuardBase arg1=NULL)
bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
override bool GuardCondition (WeaponEventBase e)
void GuardNot (WeaponGuardBase arg0=NULL)
void GuardOr (WeaponGuardBase arg0=NULL, WeaponGuardBase arg1=NULL)
void WeaponGuardAnyChamberEmpty (Weapon_Base w=NULL, int muzzle_index=0)
void WeaponGuardAnyChamberFiredOut (Weapon_Base w=NULL)
void WeaponGuardCanAttachMag (Weapon_Base w=NULL)
void WeaponGuardCanDetachMag (Weapon_Base w=NULL)
void WeaponGuardCanSwapMag (Weapon_Base w=NULL)
void WeaponGuardChamberEmpty (Weapon_Base w=NULL, int muzzle_index=0)
void WeaponGuardChamberFiredOut (Weapon_Base w=NULL, int muzzle_index=0)
void WeaponGuardChamberFull (Weapon_Base w=NULL, int muzzle_index=0)
void WeaponGuardChamberHasRoomForMoreThanOne (Weapon_Base w=NULL)
void WeaponGuardChamberHasRoomForOne (Weapon_Base w=NULL)
void WeaponGuardChamberMultiHasRoomBulltet (Weapon_Base w=NULL)
void WeaponGuardChamberMultiHasRoomBulltetIgnoreLast (Weapon_Base w=NULL)
void WeaponGuardCurrentChamberEmpty (Weapon_Base w=NULL)
void WeaponGuardCurrentChamberFiredOut (Weapon_Base w=NULL)
void WeaponGuardCurrentChamberFull (Weapon_Base w=NULL)
void WeaponGuardHasAmmoInEvent (Weapon_Base w=NULL)
void WeaponGuardHasAmmoInLoopedState (WeaponChambering_Base state)
void WeaponGuardHasAmmoInnerMagazine (Weapon_Base w=NULL)
void WeaponGuardHasMag (Weapon_Base w=NULL)
void WeaponGuardInnerMagazineFull (Weapon_Base w=NULL)
void WeaponGuardInnerMagazineFullShareChamber (Weapon_Base w=NULL)
void WeaponGuardIsDestroyed (Weapon_Base w=NULL)
void WeaponGuardJammed (Weapon_Base w=NULL)
void WeaponGuardMagazinesHaveEqualSizes (Weapon_Base w=NULL)
Private Attributes
ref WeaponGuardBase m_arg0
ref WeaponGuardBase m_arg1
protected int m_muzzle
WeaponChambering_Base m_state
protected Weapon_Base m_weapon
Detailed Description
represents guard on a transition from state to state
Definition at line 4 of file guards.c.
Member Function Documentation
GuardAnd()
void WeaponGuardBase::GuardAnd (WeaponGuardBase arg0 = NULL, WeaponGuardBase arg1 = NULL) inline private
Definition at line 19 of file guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
GuardCondition() [1/29]
bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 11 of file guards.c.
{ return true; }
GuardCondition() [2/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 21 of file guards.c.
    {
        bool result = m_arg0.GuardCondition(e) && m_arg1.GuardCondition(e);
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - " + m_arg0.Type() + " && " + m_arg1.Type() + " = " + result); }
        return result;
    }
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [3/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 35 of file guards.c.
    {
        bool result = !m_arg0.GuardCondition(e);
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - ! " + m_arg0.Type() + " = " + result); }
        return result;
    }
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [4/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 50 of file guards.c.
    {
        bool result = m_arg0.GuardCondition(e) || m_arg1.GuardCondition(e);
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - " + m_arg0.Type() + " || " + m_arg1.Type() + " = " + result); }
        return result;
    }
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [5/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 65 of file guards.c.
    {
        /*int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsChamberJammed(mi))*/
        if(m_weapon.IsJammed())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - jammed"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - not jammed"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [6/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 84 of file guards.c.
    {
        if (m_weapon.IsDamageDestroyed())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - weapon destroyed"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - weapon not destroyed"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [7/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 120 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.GetInternalMagazineCartridgeCount(mi) >= 1)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - has ammo in inner magazine"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - no ammo in inner magazine"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [8/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 138 of file guards.c.
    {
        Magazine mag = e.m_magazine;
        if (mag != NULL && mag.GetAmmoCount() > 0)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - has ammo in event"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - no ammo in event"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [9/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 157 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        Magazine mag = m_weapon.GetMagazine(mi);
        if (mag != NULL)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - has magazine"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - no magazine"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [10/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 177 of file guards.c.
    {
        if (m_weapon.IsChamberEmpty(m_muzzle))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") empty"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") not empty"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [11/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 194 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsChamberEmpty(mi))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber empty"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber not empty"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [12/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 213 of file guards.c.
    {
        for (int i = 0; i < m_weapon.GetMuzzleCount(); i++)
        {
            if (m_weapon.IsChamberEmpty(i))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - multi chamber (" + i + ") empty"); }
                return true;
            }
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - no chamber empty"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [13/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 234 of file guards.c.
    {
        if (m_weapon.IsChamberFull(m_muzzle))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") full"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") not full"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [14/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 251 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsChamberFull(mi))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber full"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber not full"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [15/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 270 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsInternalMagazineFull(mi))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - internal magazine full"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - internal magazine not full"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [16/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 288 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if ( m_weapon.IsChamberFull(mi) && m_weapon.IsInternalMagazineFull(mi))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - internal magazine with share chamber is full"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - internal magazine with share chamber is not full"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [17/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 308 of file guards.c.
    {
        if (m_weapon.IsChamberFiredOut(m_muzzle))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") fireout"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber (" + m_muzzle + ") not fireout"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [18/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 325 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.IsChamberFiredOut(mi))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber fired out"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber not fired out"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [19/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 343 of file guards.c.
    {
        for (int i = 0; i < m_weapon.GetMuzzleCount(); i++)
        {
            if (m_weapon.IsChamberFiredOut(i))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - multi chamber (" + i + ") fired out"); }
                return true;
            }
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - any chamber has not fired out"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [20/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 364 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon && e.m_magazine && m_weapon.CanAttachMagazine(mi, e.m_magazine))
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - can attach magazine"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - cannot attach magazine"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [21/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 382 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        Magazine attached_mag = m_weapon.GetMagazine(mi);
        if (m_weapon && e.m_magazine && e.m_magazine != attached_mag /*&& m_weapon.CanSwapMagazine(mi, e.m_magazine)*/)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - can swap magazine"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - cannot swap magazine"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [22/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 401 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon && e.m_magazine && m_weapon.GetMagazine(mi)/* && m_weapon.CanDetachMagazine(mi, e.m_magazine)*/)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - can detach magazine"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - cannot detach magazine"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
GuardCondition() [23/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 419 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.GetInternalMagazineMaxCartridgeCount(mi) - m_weapon.GetInternalMagazineCartridgeCount(mi) > 1)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has room for more than 1b"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has no room for more than 1b"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [24/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 437 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        if (m_weapon.GetTotalMaxCartridgeCount(mi) - m_weapon.GetTotalCartridgeCount(mi) == 1)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has room for 1b"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has no room for 1b"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [25/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 455 of file guards.c.
    {
        int i = m_weapon.GetMuzzleCount() - 1;
        for ( ; i >= 0; i--)
        {
            if (m_weapon.GetTotalMaxCartridgeCount(i) - m_weapon.GetTotalCartridgeCount(i) >= 1)
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has room for 1b"); }
                return true;
            }
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has no room for 1b"); }
        }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [26/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 476 of file guards.c.
    {
        int i = m_weapon.GetMuzzleCount() - 1;
        bool emty_one = false;
        for ( ; i >= 0; i--)
        {
            if (m_weapon.GetTotalMaxCartridgeCount(i) - m_weapon.GetTotalCartridgeCount(i) >= 1)
            {
                if ( !emty_one )
                {
                    emty_one = true;
                }
                else
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has room for 1b"); }
                    return true;
                }
            }
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - chamber has no room for 1b"); }
        }
        return false;
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
GuardCondition() [27/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 506 of file guards.c.
    {
        Magazine mag = m_state.m_srcMagazine;
        if (mag != NULL && mag.GetAmmoCount() > 0)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - has ammo in looped state"); }
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] guard - no ammo in looped state"); }
        return false;
    }
References LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
GuardCondition() [28/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 524 of file guards.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        Magazine mag = m_weapon.GetMagazine(mi);
        Magazine mag2 = e.m_magazine;
        if (mag != NULL && mag2 != NULL)
        {
            bool eq = magazinesHaveEqualSizes(mag, mag2);
            if (eq)
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - same inventory sizes"); }
                return true;
            }
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - different inventory sizes"); }
            return false;
        }
        Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " guard - mag == NULL or mag2 == NULL, cannot perform comparison");
        return false;
    }
References Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, m_weapon, magazinesHaveEqualSizes(), and wpnDebugPrint().
GuardCondition() [29/29]
override bool WeaponGuardBase::GuardCondition (WeaponEventBase e) inline private
Definition at line 548 of file guards.c.
    {
        PlayerBase player = PlayerBase.Cast(e.m_player);
        return player.GetWeaponManager().WantContinue();
    }
References WeaponEventBase::m_player.
GuardNot()
void WeaponGuardBase::GuardNot (WeaponGuardBase arg0 = NULL) inline private
Definition at line 33 of file guards.c.
{ m_arg0 = arg0; }
GuardOr()
void WeaponGuardBase::GuardOr (WeaponGuardBase arg0 = NULL, WeaponGuardBase arg1 = NULL) inline private
Definition at line 48 of file guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
WeaponGuardAnyChamberEmpty()
void WeaponGuardBase::WeaponGuardAnyChamberEmpty (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 211 of file guards.c.
{ m_weapon = w; m_muzzle = muzzle_index; }
References m_weapon.
WeaponGuardAnyChamberFiredOut()
void WeaponGuardBase::WeaponGuardAnyChamberFiredOut (Weapon_Base w = NULL) inline private
Definition at line 341 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCanAttachMag()
void WeaponGuardBase::WeaponGuardCanAttachMag (Weapon_Base w = NULL) inline private
Definition at line 362 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCanDetachMag()
void WeaponGuardBase::WeaponGuardCanDetachMag (Weapon_Base w = NULL) inline private
Definition at line 399 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCanSwapMag()
void WeaponGuardBase::WeaponGuardCanSwapMag (Weapon_Base w = NULL) inline private
Definition at line 380 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardChamberEmpty()
void WeaponGuardBase::WeaponGuardChamberEmpty (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 175 of file guards.c.
{ m_weapon = w; m_muzzle = muzzle_index; }
References m_weapon.
WeaponGuardChamberFiredOut()
void WeaponGuardBase::WeaponGuardChamberFiredOut (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 306 of file guards.c.
{ m_weapon = w; m_muzzle = muzzle_index; }
References m_weapon.
WeaponGuardChamberFull()
void WeaponGuardBase::WeaponGuardChamberFull (Weapon_Base w = NULL, int muzzle_index = 0) inline private
Definition at line 232 of file guards.c.
{ m_weapon = w; m_muzzle = muzzle_index; }
References m_weapon.
WeaponGuardChamberHasRoomForMoreThanOne()
void WeaponGuardBase::WeaponGuardChamberHasRoomForMoreThanOne (Weapon_Base w = NULL) inline private
Definition at line 417 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardChamberHasRoomForOne()
void WeaponGuardBase::WeaponGuardChamberHasRoomForOne (Weapon_Base w = NULL) inline private
Definition at line 435 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardChamberMultiHasRoomBulltet()
void WeaponGuardBase::WeaponGuardChamberMultiHasRoomBulltet (Weapon_Base w = NULL) inline private
Definition at line 453 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardChamberMultiHasRoomBulltetIgnoreLast()
void WeaponGuardBase::WeaponGuardChamberMultiHasRoomBulltetIgnoreLast (Weapon_Base w = NULL) inline private
Definition at line 474 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCurrentChamberEmpty()
void WeaponGuardBase::WeaponGuardCurrentChamberEmpty (Weapon_Base w = NULL) inline private
Definition at line 192 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCurrentChamberFiredOut()
void WeaponGuardBase::WeaponGuardCurrentChamberFiredOut (Weapon_Base w = NULL) inline private
Definition at line 323 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardCurrentChamberFull()
void WeaponGuardBase::WeaponGuardCurrentChamberFull (Weapon_Base w = NULL) inline private
Definition at line 249 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardHasAmmoInEvent()
void WeaponGuardBase::WeaponGuardHasAmmoInEvent (Weapon_Base w = NULL) inline private
Definition at line 136 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardHasAmmoInLoopedState()
void WeaponGuardBase::WeaponGuardHasAmmoInLoopedState (WeaponChambering_Base state) inline private
Definition at line 504 of file guards.c.
{ m_state = state; }
WeaponGuardHasAmmoInnerMagazine()
void WeaponGuardBase::WeaponGuardHasAmmoInnerMagazine (Weapon_Base w = NULL) inline private
Definition at line 118 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardHasMag()
void WeaponGuardBase::WeaponGuardHasMag (Weapon_Base w = NULL) inline private
Definition at line 155 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardInnerMagazineFull()
void WeaponGuardBase::WeaponGuardInnerMagazineFull (Weapon_Base w = NULL) inline private
Definition at line 268 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardInnerMagazineFullShareChamber()
void WeaponGuardBase::WeaponGuardInnerMagazineFullShareChamber (Weapon_Base w = NULL) inline private
Definition at line 286 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardIsDestroyed()
void WeaponGuardBase::WeaponGuardIsDestroyed (Weapon_Base w = NULL) inline private
Definition at line 82 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardJammed()
void WeaponGuardBase::WeaponGuardJammed (Weapon_Base w = NULL) inline private
Definition at line 63 of file guards.c.
{ m_weapon = w; }
References m_weapon.
WeaponGuardMagazinesHaveEqualSizes()
void WeaponGuardBase::WeaponGuardMagazinesHaveEqualSizes (Weapon_Base w = NULL) inline private
Definition at line 522 of file guards.c.
{ m_weapon = w; }
References m_weapon.
Member Data Documentation
m_arg0
ref WeaponGuardBase WeaponGuardBase::m_arg0 private
Definition at line 16 of file guards.c.
m_arg1
ref WeaponGuardBase WeaponGuardBase::m_arg1 private
Definition at line 17 of file guards.c.
m_muzzle
protected int WeaponGuardBase::m_muzzle private
Definition at line 174 of file guards.c.
m_state
WeaponChambering_Base WeaponGuardBase::m_state private
Definition at line 503 of file guards.c.
m_weapon
protected Weapon_Base WeaponGuardBase::m_weapon private
Definition at line 62 of file guards.c.