DayzKode: ActionGetInTransport Class Reference
ActionGetInTransport Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionGetInTransport ()
override bool CanBeUsedInRestrain ()
override void CreateConditionComponents ()
override int GetActionCategory ()
override GetInputType ()
override bool HasProgress ()
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
override void OnUpdate (ActionData action_data)
override void Start (ActionData action_data)
Detailed Description
Definition at line 1 of file actiongetintransport.c.
Constructor & Destructor Documentation
ActionGetInTransport()
void ActionGetInTransport::ActionGetInTransport () inline private
Definition at line 3 of file actiongetintransport.c.
    {
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#get_in_vehicle";
    }
References m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionGetInTransport::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file actiongetintransport.c.
    {
        Transport trans = null;
        if (!target)
        {
            return false;
        }
        if (!Class.CastTo(trans, target.GetObject()))
        {
            return false;
        }
        if (player.GetItemInHands() && player.GetItemInHands().IsHeavyBehaviour())
        {
            return false;
        }
        if (player.GetCommand_Vehicle())
        {
            return false;
        }
        int componentIndex  = target.GetComponentIndex();
        int crew_index      = trans.CrewPositionIndex(componentIndex);
        if (crew_index < 0)
        {
            return false;
        }
        Human crew = trans.CrewMember(crew_index);
        if (crew)
        {
            return false;
        }
        if (!trans.CrewCanGetThrough(crew_index) || !trans.IsAreaAtDoorFree(crew_index))
        {
            return false;
        }
        array<string> selections = new array<string>();
        trans.GetActionComponentNameList(componentIndex, selections);
        for (int i = 0; i < selections.Count(); i++)
        {
            if (trans.CanReachSeatFromDoors(selections[i], player.GetPosition(), 1.0))
            {
                return true;
            }
        }
        return false;
    }
References Class::CastTo(), and Transport::IsAreaAtDoorFree().
CanBeUsedInRestrain()
override bool ActionGetInTransport::CanBeUsedInRestrain () inline private
Definition at line 115 of file actiongetintransport.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionGetInTransport::CreateConditionComponents () inline private
Definition at line 10 of file actiongetintransport.c.
    {
        m_ConditionItem     = new CCINone;
        m_ConditionTarget   = new CCTCursorNoRuinCheck;
    }
References m_ConditionItem, and m_ConditionTarget.
GetActionCategory()
override int ActionGetInTransport::GetActionCategory () inline private
Definition at line 132 of file actiongetintransport.c.
    {
        return AC_INTERACT;
    }
References AC_INTERACT.
GetInputType()
override ActionGetInTransport::GetInputType () inline private
Definition at line 16 of file actiongetintransport.c.
    {
        return ContinuousInteractActionInput;
    }
HasProgress()
override bool ActionGetInTransport::HasProgress () inline private
Definition at line 21 of file actiongetintransport.c.
    {
        return false;
    }
OnEndClient()
override void ActionGetInTransport::OnEndClient (ActionData action_data) inline private
Definition at line 137 of file actiongetintransport.c.
    {
        if (action_data.m_Player.GetInventory())
        {
                action_data.m_Player.GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        }
    }
References ActionData::m_Player.
OnEndServer()
override void ActionGetInTransport::OnEndServer (ActionData action_data) inline private
Definition at line 145 of file actiongetintransport.c.
    {
        if (action_data.m_Player.GetInventory())
        {
            action_data.m_Player.GetInventory().UnlockInventory(LOCK_FROM_SCRIPT);
        }
        CarScript car = CarScript.Cast(action_data.m_Target.GetObject());
        if (car)
        {
            car.ForceUpdateLightsEnd();
        }
    }
References ActionData::m_Player, and ActionData::m_Target.
OnStartServer()
override void ActionGetInTransport::OnStartServer (ActionData action_data) inline private
Definition at line 106 of file actiongetintransport.c.
    {
        CarScript car = CarScript.Cast(action_data.m_Target.GetObject());
        if (car)
        {
            car.ForceUpdateLightsStart();
        }
    }
References ActionData::m_Target.
OnUpdate()
override void ActionGetInTransport::OnUpdate (ActionData action_data) inline private
Definition at line 120 of file actiongetintransport.c.
    {
        if (action_data.m_State == UA_START)
        {
            if (!action_data.m_Player.GetCommand_Vehicle() || !action_data.m_Player.GetCommand_Vehicle().IsGettingIn())
            {
                End(action_data);
            }
        }
    }
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
Start()
override void ActionGetInTransport::Start (ActionData action_data) inline private
Definition at line 82 of file actiongetintransport.c.
    {
        super.Start( action_data );
        Transport trans = Transport.Cast(action_data.m_Target.GetObject());
        int componentIndex = action_data.m_Target.GetComponentIndex();
        int crew_index = trans.CrewPositionIndex(componentIndex);
        int seat = trans.GetSeatAnimationType(crew_index);
        HumanCommandVehicle vehCommand = action_data.m_Player.StartCommand_Vehicle(trans, crew_index, seat);
        if (vehCommand)
        {
            vehCommand.SetVehicleType(trans.GetAnimInstance());
            action_data.m_Player.TryHideItemInHands(true);
            GetDayZGame().GetBacklit().OnEnterCar();
            if (action_data.m_Player.GetInventory())
            {
                action_data.m_Player.GetInventory().LockInventory(LOCK_FROM_SCRIPT);
            }
        }
    }
References GetDayZGame(), ActionData::m_Player, ActionData::m_Target, and HumanCommandVehicle::SetVehicleType().