DayzKode: MissionBase Class Reference
MissionBase Class Reference
Private Member Functions
override void AbortMission ()
override void AddActiveInputExcludes (array< string > excludes)
Adds one or more exclude groups to disable and refreshes excludes.
override void AddActiveInputRestriction (int restrictor)
Adds one input restriction (specific behaviour oudside regular excludes, defined below)
protected void AddNewPlayerLogout (PlayerBase player, notnull LogoutInfo info)
void CloseAllMenus ()
override void Continue ()
void ControlPersonalLight (PlayerBase player)
PlayerBase CreateCharacter (PlayerIdentity identity, vector pos, ParamsReadContext ctx, string characterName)
override void CreateDebugMonitor ()
void CreateIntroScene ()
override void CreateLogoutMenu (UIMenuPanel parent)
void DestroyAllMenus ()
void DestroyInventory ()
void DisplayHairDebug ()
override void EnableAllInputs (bool bForceSupress=false)
Removes all active input excludes and restrictions.
void EquipCharacter (MenuDefaultCharacterData char_data)
Spawns character equip from received data. Checks validity against config, randomizes if invalid value and config array not empty.
override array< vector > GetActiveRefresherLocations ()
override int GetControlDisabledMode ()
(mostly)DEPRECATED; only set on the old 'PlayerControlDisable' method
override GameplayEffectWidgets GetEffectWidgets ()
float GetHoldActionTime ()
override Hud GetHud ()
HudDebug GetHudDebug ()
DayZIntroScenePC GetIntroScenePC ()
DayZIntroSceneXbox GetIntroSceneXbox ()
InventoryMenu GetInventory ()
AbstractWave GetMenuMusic ()
override ImageWidget GetMicrophoneIcon ()
override WidgetFadeTimer GetMicWidgetFadeTimer ()
override UIScriptedMenu GetNoteMenu ()
override int GetRespawnModeClient ()
UIManager GetUIManager ()
override map< int, ref WidgetFadeTimer > GetVoiceLevelTimers ()
override map< int, ImageWidget > GetVoiceLevelWidgets ()
void HandleBody (PlayerBase player)
protected void HandleMapToggleByKeyboardShortcut (Man player)
override void HideChat ()
override void HideCrosshairVisibility ()
override void HideInventory ()
void HideVehicleInfo ()
override void HideVoiceLevelWidgets ()
void InitInventory ()
override bool InsertCorpse (Man player)
void InvokeOnConnect (PlayerBase player, PlayerIdentity identity)
void InvokeOnDisconnect (PlayerBase player)
override bool IsControlDisabled ()
returns if ANY exclude groups, restriction (or deprecated disable, if applicable) is active
override bool IsInputExcludeActive (string exclude)
Returns true if the particular input exclude group had been activated via script and is active.
override bool IsInputRestrictionActive (int restriction)
Returns true if the particular 'restriction' (those govern special behaviour outside regular input excludes, EInputRestrictors) is active.
protected bool IsMapUnfoldActionRunning (ActionBase pAction)
override bool IsMissionGameplay ()
override bool IsPaused ()
override bool IsPlayerDisconnecting (Man player)
override bool IsPlayerRespawning ()
override bool IsServer ()
override bool IsVoNActive ()
int LocalPressTime ()
int LocalReleaseTime ()
void MissionGameplay ()
void MissionServer ()
void MoveHudForInventory (bool inv_open)
void OnClientDisconnectedEvent (PlayerIdentity identity, PlayerBase player, int logoutTime, bool authFailed)
PlayerBase OnClientNewEvent (PlayerIdentity identity, vector pos, ParamsReadContext ctx)
void OnClientPrepareEvent (PlayerIdentity identity, out bool useDB, out vector pos, out float yaw, out int preloadTimeout)
void OnClientReadyEvent (PlayerIdentity identity, PlayerBase player)
void OnClientReconnectEvent (PlayerIdentity identity, PlayerBase player)
void OnClientRespawnEvent (PlayerIdentity identity, PlayerBase player)
override void OnEvent (EventType eventTypeId, Param params)
override void OnEvent (EventType eventTypeId, Param params)
override void OnGameplayDataHandlerLoad ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
void OnInputDeviceChanged (int device)
override void OnItemUsed (InventoryItem item, Man owner)
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
override void OnKeyRelease (int key)
void OnMenuEnter (int menu_id)
override void OnMissionFinish ()
override void OnMissionFinish ()
override void OnMissionStart ()
override void OnMissionStart ()
override void OnMissionStart ()
override void OnPlayerRespawned (Man player)
override void OnUpdate (float timeslice)
override void OnUpdate (float timeslice)
override void OnUpdate (float timeslice)
override void Pause ()
override void PlayerControlDisable (int mode)
Deprecated; simple input restrictions.
override void PlayerControlEnable (bool bForceSupress)
Deprecated; removes last input exclude and associated controls restrictions.
void PlayerDisconnected (PlayerBase player, PlayerIdentity identity, string uid)
void PlayMusic ()
bool ProcessLoginData (ParamsReadContext ctx)
returns whether received data is valid, ctx can be filled on client in StoreLoginData()
void RandomArtillery (float deltaTime)
override void RefreshCrosshairVisibility ()
override void RefreshExcludes ()
refreshes any active excludes
override void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress=false)
Removes one or more exclude groups and refreshes excludes.
override void RemoveActiveInputRestriction (int restrictor)
Removes one restriction (specific behaviour oudside regular excludes, defined below)
override void Reset ()
override void ResetGUI ()
void SendMuteListToServer (map< string, bool > mute_list)
void SetActionDownTime (int time_down)
void SetActionUpTime (int time_up)
override void SetNoteMenu (UIScriptedMenu menu)
override void SetPlayerRespawning (bool state)
override void SetRespawnModeClient (int mode)
override void SetVoNActive (bool active)
override void ShowChat ()
void ShowHairDebugValues (bool state)
override void ShowInventory ()
void ShowVehicleInfo ()
int SortedInsert (array< int > list, int number)
void StartingEquipSetup (PlayerBase player, bool clothesChosen)
can be overriden to manually set up starting equip. 'clothesChosen' is legacy parameter, does nothing.
override void StartLogoutMenu (int time)
void StopMusic ()
void SyncGlobalLighting (PlayerBase player)
override void SyncRespawnModeInfo (PlayerIdentity identity)
void TickScheduler (float timeslice)
void TickScheduler (float timeslice)
void UpdateCorpseStatesServer ()
void UpdateDebugMonitor ()
void UpdateLogoutPlayers ()
void UpdatePlayersStats ()
override void UpdateVoiceLevelWidgets (int level)
bool VerifyAttachmentType (int slot_ID, string attachment_type)
void ~MissionGameplay ()
void ~MissionServer ()
Private Attributes
protected const ref array< vector > CHERNARUS_STRIKE_POS
protected const int HOLD_LIMIT_TIME = 300
protected const ref array< vector > LIVONIA_STRIKE_POS
protected int m_ActionDownTime
ref ActionMenu m_ActionMenu
protected int m_ActionUpTime
protected ref array< string > m_ActiveInputExcludeGroups
protected ref array< int > m_ActiveInputRestrictions
private float m_ArtyBarrageTimer = 0
protected float m_ArtyDelay = 0
ref Chat m_Chat
Widget m_ChatChannelArea
ref WidgetFadeTimer m_ChatChannelFadeTimer
ref Timer m_ChatChannelHideTimer
TextWidget m_ChatChannelText
protected bool m_ControlDisabled
protected int m_ControlDisabledMode
private CreditsMenu m_CreditsMenu
int m_currentPlayer
ref array< ref CorpseData > m_DeadPlayersArray
ref DebugMonitor m_DebugMonitor
protected ref GameplayEffectWidgets m_EffectWidgets
protected ref array< vector > m_FiringPos
ref IngameHud m_Hud
ref HudDebug m_HudDebug
Widget m_HudRootWidget
bool m_Initialized
protected bool m_InitOnce
private ref DayZIntroScenePC m_IntroScenePC
private ref DayZIntroSceneXbox m_IntroSceneXbox
ref InventoryMenu m_InventoryMenu
int m_LifeState
ref LogoutMenu m_Logout
ref map< PlayerBase, ref LogoutInfo > m_LogoutPlayers
private UIScriptedMenu m_mainmenu
protected int m_MaxSimultaneousStrikes = 0
private AbstractWave m_MenuMusic
ref WidgetFadeTimer m_MicFadeTimer
ImageWidget m_MicrophoneIcon
protected int m_MinSimultaneousStrikes = 0
MissionBase m_mission
PluginAdditionalInfo m_moduleDefaultCharacter
ref map< PlayerBase, ref LogoutInfo > m_NewLogoutPlayers
bool m_NoCutscene
NoteMenu m_Note
protected bool m_PauseQueued
protected bool m_PlayArty = false
PlayerBase m_player
protected bool m_PlayerRespawning
ref array< Man > m_Players
protected bool m_QuickbarHold
int m_RespawnMode
protected int m_RespawnModeClient
protected ref Timer m_ToggleHudTimer
protected UIManager m_UIManager
protected Widget m_VoiceLevels
protected ref map< int, ImageWidget > m_VoiceLevelsWidgets
protected ref map< int, ref WidgetFadeTimer > m_VoiceLevelTimers
protected bool m_VoNActive
const int SCHEDULER_PLAYERS_PER_TICK = 5
Detailed Description
Definition at line 1 of file missiongameplay.c.
Constructor & Destructor Documentation
~MissionGameplay()
void MissionBase::~MissionGameplay () inline private
Definition at line 70 of file missiongameplay.c.
    {
        DestroyInventory();
        //GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Remove(this.UpdateDebugMonitor);
    #ifndef NO_GUI
        if (g_Game.GetUIManager() && g_Game.GetUIManager().ScreenFadeVisible())
        {
            g_Game.GetUIManager().ScreenFadeOut(0);
        }
    #endif
    }
References DestroyInventory(), and g_Game.
~MissionServer()
void MissionBase::~MissionServer () inline private
Definition at line 69 of file missionserver.c.
    {
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Remove(this.UpdatePlayersStats);
    }
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
Member Function Documentation
AbortMission()
override void MissionBase::AbortMission () inline private
Definition at line 1240 of file missiongameplay.c.
    {
        #ifdef BULDOZER
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(g_Game.RequestExit, IDC_MAIN_QUIT);
        #else
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(GetGame().AbortMission);
        #endif
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, g_Game, CGame::GetCallQueue(), GetGame(), and IDC_MAIN_QUIT.
Referenced by CreateLogoutMenu().
AddActiveInputExcludes()
override void MissionBase::AddActiveInputExcludes (array< string > excludes) inline private
Adds one or more exclude groups to disable and refreshes excludes.
Definition at line 894 of file missiongameplay.c.
    {
        super.AddActiveInputExcludes(excludes);
        if (excludes.Count() != 0)
        {
            bool changed = false;
            if (!m_ActiveInputExcludeGroups)
            {
                m_ActiveInputExcludeGroups = new array<string>;
            }
            for (int i = 0; i < excludes.Count(); i++)
            {
                if (m_ActiveInputExcludeGroups.Find(excludes[i]) == -1)
                {
                    m_ActiveInputExcludeGroups.Insert(excludes[i]);
                    changed = true;
                }
            }
            //m_ActiveInputExcludeGroups.Sort(); //?
            if (changed)
            {
                RefreshExcludes();
                #ifdef BULDOZER
                    GetUApi().SupressNextFrame(true);
                #endif
            }
        }
    }
References GetUApi(), RefreshExcludes(), and UAInputAPI::SupressNextFrame().
Referenced by OnUpdate(), Pause(), PlayerControlDisable(), ShowChat(), and ShowInventory().
AddActiveInputRestriction()
override void MissionBase::AddActiveInputRestriction (int restrictor) inline private
Adds one input restriction (specific behaviour oudside regular excludes, defined below)
Definition at line 927 of file missiongameplay.c.
    {
        //unique behaviour outside regular excludes
        if (restrictor > -1)
        {
            switch (restrictor)
            {
                case EInputRestrictors.INVENTORY:
                {
                    GetUApi().GetInputByName("UAWalkRunForced").ForceEnable(true); // force walk on!
                    PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
                    if ( player )
                    {
                        ItemBase item = player.GetItemInHands();
                        if (item && item.IsWeapon())
                            player.RequestResetADSSync();
                    }
                    break;
                }
                case EInputRestrictors.MAP:
                {
                    GetUApi().GetInputByName("UAWalkRunForced").ForceEnable(true); // force walk on!
                    break;
                }
            }
            if (!m_ActiveInputRestrictions)
            {
                m_ActiveInputRestrictions = new array<int>;
            }
            if (m_ActiveInputRestrictions.Find(restrictor) == -1)
            {
                m_ActiveInputRestrictions.Insert(restrictor);
            }
        }
    }
References UAInput::ForceEnable(), GetGame(), UAInputAPI::GetInputByName(), GetPlayer(), and GetUApi().
Referenced by OnUpdate(), PlayerControlDisable(), and ShowInventory().
AddNewPlayerLogout()
protected void MissionBase::AddNewPlayerLogout (PlayerBase player, notnull LogoutInfo info) inline private
Definition at line 213 of file missionserver.c.
    {
        m_LogoutPlayers.Insert(player, info);
        m_NewLogoutPlayers.Remove(player);
    }
CloseAllMenus()
void MissionBase::CloseAllMenus () inline private
Definition at line 1035 of file missiongameplay.c.
    {
        GetUIManager().CloseAll();
    }
References UIManager::CloseAll(), and GetUIManager().
Referenced by OnUpdate(), and Pause().
Continue()
override void MissionBase::Continue () inline private
Definition at line 1209 of file missiongameplay.c.
    {
        int menu_id = GetGame().GetUIManager().GetMenu().GetID();
        if ( !IsPaused() || ( menu_id != MENU_INGAME && menu_id != MENU_LOGOUT && menu_id != MENU_RESPAWN_DIALOGUE ) || ( m_Logout && m_Logout.layoutRoot.IsVisible() ) )
        {
            return;
        }
        m_PauseQueued = false;
        RemoveActiveInputExcludes({"menu"},true);
        GetUIManager().CloseMenu(MENU_INGAME);
        //GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(CloseInGameMenu,1,true);
    }
References UIManager::CloseMenu(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), GetUIManager(), IsPaused(), MENU_INGAME, MENU_LOGOUT, MENU_RESPAWN_DIALOGUE, and RemoveActiveInputExcludes().
Referenced by OnUpdate().
ControlPersonalLight()
void MissionBase::ControlPersonalLight (PlayerBase player) inline private
Definition at line 403 of file missionserver.c.
    {
        if ( player )
        {
            bool is_personal_light = ! GetGame().ServerConfigGetInt( "disablePersonalLight" );
            Param1<bool> personal_light_toggle = new Param1<bool>(is_personal_light);
            GetGame().RPCSingleParam(player, ERPCs.RPC_TOGGLE_PERSONAL_LIGHT, personal_light_toggle, true, player.GetIdentity());
        }
        else
        {
            Error("Error! Player was not initialized at the right time. Thus cannot send RPC command to enable or disable personal light!");
        }
    }
References Error(), GetGame(), CGame::RPCSingleParam(), and CGame::ServerConfigGetInt().
Referenced by OnEvent().
CreateCharacter()
PlayerBase MissionBase::CreateCharacter (PlayerIdentity identity, vector pos, ParamsReadContext ctx, string characterName) inline private
Definition at line 436 of file missionserver.c.
    {
        Entity playerEnt;
        playerEnt = GetGame().CreatePlayer(identity, characterName, pos, 0, "NONE");//Creates random player
        Class.CastTo(m_player, playerEnt);
        GetGame().SelectPlayer(identity, m_player);
        return m_player;
    }
References Class::CastTo(), CGame::CreatePlayer(), GetGame(), m_player, m_player, and CGame::SelectPlayer().
Referenced by OnClientNewEvent().
CreateDebugMonitor()
override void MissionBase::CreateDebugMonitor () inline private
Definition at line 1292 of file missiongameplay.c.
    {
        if (!m_DebugMonitor)
        {
            m_DebugMonitor = new DebugMonitor();
            m_DebugMonitor.Init();
        }
    }
CreateIntroScene()
void MissionBase::CreateIntroScene () inline private
Definition at line 63 of file missionmainmenu.c.
    {
#ifdef PLATFORM_CONSOLE
        m_IntroSceneXbox = new DayZIntroSceneXbox;
#else
        Print("misssionMainMenu CreateIntroScene");
        m_IntroScenePC = new DayZIntroScenePC;
#endif
    }
References Print().
Referenced by OnInit(), and Reset().
CreateLogoutMenu()
override void MissionBase::CreateLogoutMenu (UIMenuPanel parent) inline private
Definition at line 1249 of file missiongameplay.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        // do not show logout screen if player's dead
        if (!player || player.IsDamageDestroyed())
        {
            // exit the game immediately
            AbortMission();
            return;
        }
        if (parent)
        {
            m_Logout = LogoutMenu.Cast(parent.EnterScriptedMenu(MENU_LOGOUT));
            if (m_Logout)
            {
                m_Logout.SetLogoutTime();
            }
        }
    }
References AbortMission(), UIMenuPanel::EnterScriptedMenu(), GetGame(), GetPlayer(), and MENU_LOGOUT.
DestroyAllMenus()
void MissionBase::DestroyAllMenus () inline private
Definition at line 1041 of file missiongameplay.c.
    {
        if( GetUIManager() )
        {
            GetUIManager().HideDialog();
            GetUIManager().CloseAll();
        }
        DestroyInventory();
        if( m_Chat )
            m_Chat.Clear();
    }
References UIManager::CloseAll(), DestroyInventory(), GetUIManager(), and UIManager::HideDialog().
Referenced by MissionGameplay(), OnEvent(), and OnMissionFinish().
DestroyInventory()
void MissionBase::DestroyInventory () inline private
Definition at line 1106 of file missiongameplay.c.
    {
        if ( m_InventoryMenu )
        {
            if (!m_InventoryMenu.GetParentMenu() && GetUIManager().GetMenu() != m_InventoryMenu)
            {
                m_InventoryMenu.SetParentMenu(GetUIManager().GetMenu()); //hack; guarantees the 'm_pCurrentMenu' will be set to whatever is on top currently
            }
            m_InventoryMenu.Close();
            m_InventoryMenu = NULL;
        }
    }
References GetUIManager().
Referenced by DestroyAllMenus(), ResetGUI(), and ~MissionGameplay().
DisplayHairDebug()
void MissionBase::DisplayHairDebug () inline private
Definition at line 1383 of file missiongameplay.c.
    {
        if ( DiagMenu.GetBool(DiagMenuIDs.DM_HAIR_DISPLAY_DEBUG) )
        {
            if(!GetGame().IsDedicatedServer())
                ShowHairDebugValues(true);
        }
        else
        {
            if(!GetGame().IsDedicatedServer())
                ShowHairDebugValues(false);
        }
    }
References DiagMenu::GetBool(), GetGame(), and ShowHairDebugValues().
Referenced by OnUpdate().
EnableAllInputs()
override void MissionBase::EnableAllInputs (bool bForceSupress = false) inline private
Removes all active input excludes and restrictions.
Definition at line 978 of file missiongameplay.c.
    {
        m_ControlDisabledMode = -1;
        if (m_ActiveInputRestrictions)
        {
            int count = m_ActiveInputRestrictions.Count();
            for (int i = 0; i < count; i++)
            {
                RemoveActiveInputRestriction(m_ActiveInputRestrictions[0]);
            }
            m_ActiveInputRestrictions.Clear(); //redundant?
        }
        if (m_ActiveInputExcludeGroups)
        {
            m_ActiveInputExcludeGroups.Clear();
        }
        GetUApi().UpdateControls();
        // supress control for next frame
        GetUApi().SupressNextFrame(bForceSupress);
    }
References GetUApi(), RemoveActiveInputRestriction(), UAInputAPI::SupressNextFrame(), and UAInputAPI::UpdateControls().
Referenced by OnMissionFinish().
EquipCharacter()
void MissionBase::EquipCharacter (MenuDefaultCharacterData char_data) inline private
Spawns character equip from received data. Checks validity against config, randomizes if invalid value and config array not empty.
Definition at line 448 of file missionserver.c.
    {
        int slot_ID;
        string attachment_type;
        for (int i = 0; i < DefaultCharacterCreationMethods.GetAttachmentSlotsArray().Count(); i++)
        {
            slot_ID = DefaultCharacterCreationMethods.GetAttachmentSlotsArray().Get(i);
            attachment_type = "";
            if ( m_RespawnMode != GameConstants.RESPAWN_MODE_CUSTOM || !char_data.GetAttachmentMap().Find(slot_ID,attachment_type) || !VerifyAttachmentType(slot_ID,attachment_type) ) //todo insert verification fn here
            {
                //randomize
                if ( DefaultCharacterCreationMethods.GetConfigArrayCountFromSlotID(slot_ID) > 0 )
                {
                    attachment_type = DefaultCharacterCreationMethods.GetConfigAttachmentTypes(slot_ID).GetRandomElement();
                }
                else //undefined, moving on
                    continue;
            }
            if (attachment_type != "")
            {
                m_player.GetInventory().CreateAttachmentEx(attachment_type,slot_ID);
            }
        }
        StartingEquipSetup(m_player, true);
    }
References Count, MenuDefaultCharacterData::GetAttachmentMap(), m_player, GameConstants::RESPAWN_MODE_CUSTOM, and StartingEquipSetup().
Referenced by OnClientNewEvent().
GetActiveRefresherLocations()
override array< vector > MissionBase::GetActiveRefresherLocations () inline private
Definition at line 1552 of file missiongameplay.c.
    {
        return m_ActiveRefresherLocations;
    }
GetControlDisabledMode()
override int MissionBase::GetControlDisabledMode () inline private
(mostly)DEPRECATED; only set on the old 'PlayerControlDisable' method
Definition at line 1030 of file missiongameplay.c.
    {
        return m_ControlDisabledMode;
    }
References m_ControlDisabledMode.
GetEffectWidgets()
override GameplayEffectWidgets MissionBase::GetEffectWidgets () inline private
Definition at line 1567 of file missiongameplay.c.
    {
        return m_EffectWidgets;
    }
References m_EffectWidgets.
GetHoldActionTime()
float MissionBase::GetHoldActionTime () inline private
Definition at line 1377 of file missiongameplay.c.
    {
        float hold_action_time = LocalReleaseTime() - LocalPressTime();
        return hold_action_time;
    }
References LocalPressTime(), and LocalReleaseTime().
GetHud()
override Hud MissionBase::GetHud () inline private
Definition at line 1155 of file missiongameplay.c.
    {
        return m_Hud;
    }
References m_Hud.
Referenced by HideVehicleInfo(), MoveHudForInventory(), and ShowVehicleInfo().
GetHudDebug()
HudDebug MissionBase::GetHudDebug () inline private
Definition at line 1160 of file missiongameplay.c.
    {
        return m_HudDebug;
    }
References m_HudDebug.
Referenced by HideCrosshairVisibility(), and RefreshCrosshairVisibility().
GetIntroScenePC()
DayZIntroScenePC MissionBase::GetIntroScenePC () inline private
Definition at line 43 of file missionmainmenu.c.
    {
        #ifdef PLATFORM_CONSOLE
            Error("missionMainMenu->GetIntroScenePC on PLATFORM_CONSOLE is not implemented!");
            return null;
        #else
            return m_IntroScenePC;
        #endif
    }
References Error(), and m_IntroScenePC.
GetIntroSceneXbox()
DayZIntroSceneXbox MissionBase::GetIntroSceneXbox () inline private
Definition at line 53 of file missionmainmenu.c.
    {
        #ifdef PLATFORM_CONSOLE
            return m_IntroSceneXbox;
        #else
            Error("missionMainMenu->GetIntroScenePC on PLATFORM_PC is not implemented!");
            return null;
        #endif
    }
References Error(), and m_IntroSceneXbox.
GetInventory()
InventoryMenu MissionBase::GetInventory () inline private
Definition at line 82 of file missiongameplay.c.
    {
        return m_InventoryMenu;
    }
References m_InventoryMenu.
GetMenuMusic()
AbstractWave MissionBase::GetMenuMusic () inline private
Definition at line 183 of file missionmainmenu.c.
    {
        return m_MenuMusic;
    }
References m_MenuMusic.
GetMicrophoneIcon()
override ImageWidget MissionBase::GetMicrophoneIcon () inline private
Definition at line 1473 of file missiongameplay.c.
    {
        return m_MicrophoneIcon;
    }
References m_MicrophoneIcon.
GetMicWidgetFadeTimer()
override WidgetFadeTimer MissionBase::GetMicWidgetFadeTimer () inline private
Definition at line 1478 of file missiongameplay.c.
    {
        return m_MicFadeTimer;
    }
References m_MicFadeTimer.
GetNoteMenu()
override UIScriptedMenu MissionBase::GetNoteMenu () inline private
Definition at line 1512 of file missiongameplay.c.
    {
        return m_Note;
    };
References m_Note.
GetRespawnModeClient()
override int MissionBase::GetRespawnModeClient () inline private
Definition at line 1562 of file missiongameplay.c.
    {
        return m_RespawnModeClient;
    }
References m_RespawnModeClient.
GetUIManager()
UIManager MissionBase::GetUIManager () inline private
Definition at line 167 of file missiongameplay.c.
    {
        return m_UIManager;
    }
References m_UIManager.
Referenced by CloseAllMenus(), Continue(), DestroyAllMenus(), DestroyInventory(), HideInventory(), InitInventory(), OnEvent(), OnItemUsed(), OnMenuEnter(), OnMissionFinish(), OnMissionStart(), OnUpdate(), Pause(), ShowInventory(), and UpdateVoiceLevelWidgets().
GetVoiceLevelTimers()
override map< int, ref WidgetFadeTimer > MissionBase::GetVoiceLevelTimers () inline private
Definition at line 1488 of file missiongameplay.c.
    {
        return m_VoiceLevelTimers;
    }
References m_VoiceLevelTimers.
GetVoiceLevelWidgets()
override map< int, ImageWidget > MissionBase::GetVoiceLevelWidgets () inline private
Definition at line 1483 of file missiongameplay.c.
    {
        return m_VoiceLevelsWidgets;
    }
References m_VoiceLevelsWidgets.
HandleBody()
void MissionBase::HandleBody (PlayerBase player) inline private
Definition at line 623 of file missionserver.c.
    {
        if (player.IsAlive() && !player.IsRestrained() && !player.IsUnconscious())
        {
            // remove the body
            player.Delete();
        }
        else if (player.IsUnconscious() || player.IsRestrained())
        {
            // kill character
            player.SetHealth("", "", 0.0);
        }
    }
Referenced by PlayerDisconnected().
HandleMapToggleByKeyboardShortcut()
protected void MissionBase::HandleMapToggleByKeyboardShortcut (Man player) inline private
Definition at line 1301 of file missiongameplay.c.
    {
        UIManager um = GetGame().GetUIManager();
        if (um && !um.IsMenuOpen(MENU_MAP))
        {
            um.CloseAll();
            if (!CfgGameplayHandler.GetUse3DMap())
            {
                um.EnterScriptedMenu(MENU_MAP, null);
                GetGame().GetMission().AddActiveInputExcludes({"map"});
            }
            else
            {
                GetGame().GetMission().AddActiveInputExcludes({"loopedactions"});
            }
            GetGame().GetMission().AddActiveInputRestriction(EInputRestrictors.MAP);
        }
    }
References Mission::AddActiveInputExcludes(), Mission::AddActiveInputRestriction(), UIManager::CloseAll(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), CfgGameplayHandler::GetUse3DMap(), UIManager::IsMenuOpen(), and MENU_MAP.
Referenced by OnUpdate().
HideChat()
override void MissionBase::HideChat () inline private
Definition at line 1138 of file missiongameplay.c.
    {
        RemoveActiveInputExcludes({"menu"},true);
    }
References RemoveActiveInputExcludes().
HideCrosshairVisibility()
override void MissionBase::HideCrosshairVisibility () inline private
Definition at line 1171 of file missiongameplay.c.
    {
        if (GetHudDebug())
        GetHudDebug().HideCrosshairVisibility();
    }
References GetHudDebug().
HideInventory()
override void MissionBase::HideInventory () inline private
Definition at line 1094 of file missiongameplay.c.
    {
        if ( m_InventoryMenu )
        {
            GetUIManager().HideScriptedMenu(m_InventoryMenu);
            RemoveActiveInputExcludes({"inventory"},false);
            RemoveActiveInputRestriction(EInputRestrictors.INVENTORY);
            PlayerBase.Cast(GetGame().GetPlayer()).OnInventoryMenuClose();
            VicinityItemManager.GetInstance().ResetRefreshCounter();
        }
    }
References GetGame(), VicinityItemManager::GetInstance(), GetPlayer(), GetUIManager(), UIManager::HideScriptedMenu(), RemoveActiveInputExcludes(), RemoveActiveInputRestriction(), and VicinityItemManager::ResetRefreshCounter().
Referenced by OnUpdate().
HideVehicleInfo()
void MissionBase::HideVehicleInfo () inline private
Definition at line 1149 of file missiongameplay.c.
    {
        if( GetHud() )
            GetHud().HideVehicleInfo();
    }
References GetHud(), and Hud::HideVehicleInfo().
HideVoiceLevelWidgets()
override void MissionBase::HideVoiceLevelWidgets () inline private
Definition at line 1503 of file missiongameplay.c.
    {
        for ( int n = 0; n < m_VoiceLevelsWidgets.Count(); n++ )
        {
            ImageWidget voiceWidget = m_VoiceLevelsWidgets.Get( n );
            voiceWidget.Show(false);
        }
    }
Referenced by OnInit().
InitInventory()
void MissionBase::InitInventory () inline private
Definition at line 179 of file missiongameplay.c.
    {
        if ( !m_InventoryMenu )
        {
            m_InventoryMenu = InventoryMenu.Cast( GetUIManager().CreateScriptedMenu(MENU_INVENTORY, null) );
        }
    }
References CreateScriptedMenu(), GetUIManager(), InventoryMenu(), and MENU_INVENTORY.
Referenced by ResetGUI(), and ShowInventory().
InsertCorpse()
override bool MissionBase::InsertCorpse (Man player) inline private
Definition at line 659 of file missionserver.c.
    {
        CorpseData corpse_data = new CorpseData(PlayerBase.Cast(player),GetGame().GetTime());
        return m_DeadPlayersArray.Insert(corpse_data) >= 0;
    }
References GetGame(), and GetTime().
InvokeOnConnect()
void MissionBase::InvokeOnConnect (PlayerBase player, PlayerIdentity identity) inline private
Definition at line 374 of file missionserver.c.
    {
        Debug.Log("InvokeOnConnect:"+this.ToString(),"Connect");
        if( player ) player.OnConnect();
    }
References Debug::Log(), and ToString().
Referenced by OnEvent().
InvokeOnDisconnect()
void MissionBase::InvokeOnDisconnect (PlayerBase player) inline private
Definition at line 380 of file missionserver.c.
    {
        Debug.Log("InvokeOnDisconnect:"+this.ToString(),"Connect");
        if( player ) player.OnDisconnect();
    }
References Debug::Log(), and ToString().
Referenced by PlayerDisconnected().
IsControlDisabled()
override bool MissionBase::IsControlDisabled () inline private
returns if ANY exclude groups, restriction (or deprecated disable, if applicable) is active
Definition at line 1002 of file missiongameplay.c.
    {
        bool active = false;
        if (m_ActiveInputExcludeGroups)
        {
            active |= m_ActiveInputExcludeGroups.Count() > 0;
        }
        if (m_ActiveInputRestrictions)
        {
            active |= m_ActiveInputRestrictions.Count() > 0;
        }
        active |= m_ControlDisabledMode >= INPUT_EXCLUDE_ALL; //legacy stuff, Justin case
        return active;
    }
References INPUT_EXCLUDE_ALL.
IsInputExcludeActive()
override bool MissionBase::IsInputExcludeActive (string exclude) inline private
Returns true if the particular input exclude group had been activated via script and is active.
Definition at line 1018 of file missiongameplay.c.
    {
        return m_ActiveInputExcludeGroups && m_ActiveInputExcludeGroups.Find(exclude) != -1;
    }
Referenced by OnUpdate().
IsInputRestrictionActive()
override bool MissionBase::IsInputRestrictionActive (int restriction) inline private
Returns true if the particular 'restriction' (those govern special behaviour outside regular input excludes, EInputRestrictors) is active.
Definition at line 1024 of file missiongameplay.c.
    {
        return m_ActiveInputRestrictions && m_ActiveInputRestrictions.Find(restriction) != -1;
    }
Referenced by OnUpdate().
IsMapUnfoldActionRunning()
protected bool MissionBase::IsMapUnfoldActionRunning (ActionBase pAction) inline private
Definition at line 1321 of file missiongameplay.c.
    {
        return !pAction || pAction.Type() != ActionUnfoldMap;
    }
References ActionUnfoldMap().
Referenced by OnUpdate().
IsMissionGameplay()
override bool MissionBase::IsMissionGameplay () inline private
Definition at line 1235 of file missiongameplay.c.
    {
        return true;
    }
IsPaused()
override bool MissionBase::IsPaused () inline private
Definition at line 1177 of file missiongameplay.c.
    {
        return GetGame().GetUIManager().IsMenuOpen(MENU_INGAME);
    }
References GetGame(), CGame::GetUIManager(), UIManager::IsMenuOpen(), and MENU_INGAME.
Referenced by Continue(), OnUpdate(), and Pause().
IsPlayerDisconnecting()
override bool MissionBase::IsPlayerDisconnecting (Man player) inline private
Definition at line 184 of file missionserver.c.
    {
        return ( m_LogoutPlayers && m_LogoutPlayers.Contains(PlayerBase.Cast(player)) ) || ( m_NewLogoutPlayers && m_NewLogoutPlayers.Contains(PlayerBase.Cast(player)) );
    }
IsPlayerRespawning()
override bool MissionBase::IsPlayerRespawning () inline private
Definition at line 1547 of file missiongameplay.c.
    {
        return m_PlayerRespawning;
    }
References m_PlayerRespawning.
IsServer()
override bool MissionBase::IsServer () inline private
Definition at line 179 of file missionserver.c.
    {
        return true;
    }
Referenced by MissionBaseWorld::MissionBase(), and MissionBaseWorld::OnLog().
IsVoNActive()
override bool MissionBase::IsVoNActive () inline private
Definition at line 1493 of file missiongameplay.c.
    {
        return m_VoNActive;
    }
References m_VoNActive.
LocalPressTime()
int MissionBase::LocalPressTime () inline private
Definition at line 1367 of file missiongameplay.c.
    {
        return m_ActionDownTime;
    }
References m_ActionDownTime.
Referenced by GetHoldActionTime().
LocalReleaseTime()
int MissionBase::LocalReleaseTime () inline private
Definition at line 1372 of file missiongameplay.c.
    {
        return m_ActionUpTime;
    }
References m_ActionUpTime.
Referenced by GetHoldActionTime().
MissionGameplay()
void MissionBase::MissionGameplay () inline private
Definition at line 49 of file missiongameplay.c.
    {
        DestroyAllMenus();
        m_Initialized               = false;
        m_EffectWidgets             = new GameplayEffectWidgets;
        m_HudRootWidget             = null;
        m_Chat                      = new Chat;
        m_ActionMenu                = new ActionMenu;
        m_LifeState                 = -1;
        m_Hud                       = new IngameHud;
        m_VoNActive                 = false;
        m_PauseQueued               = false;
        m_ChatChannelFadeTimer      = new WidgetFadeTimer;
        m_MicFadeTimer              = new WidgetFadeTimer;
        m_ChatChannelHideTimer      = new Timer(CALL_CATEGORY_GUI);
        m_ToggleHudTimer            = new Timer(CALL_CATEGORY_GUI);
        m_ActiveRefresherLocations  = new array<vector>;
        SyncEvents.RegisterEvents();
    }
References CALL_CATEGORY_GUI, DestroyAllMenus(), m_Hud, m_Initialized, and SyncEvents::RegisterEvents().
MissionServer()
void MissionBase::MissionServer () inline private
Definition at line 57 of file missionserver.c.
    {
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(this.UpdatePlayersStats, 30000, true);
        m_DeadPlayersArray = new array<ref CorpseData>;
        UpdatePlayersStats();
        m_Players = new array<Man>;
        m_LogoutPlayers = new map<PlayerBase, ref LogoutInfo>;
        m_NewLogoutPlayers = new map<PlayerBase, ref LogoutInfo>;
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), and UpdatePlayersStats().
MoveHudForInventory()
void MissionBase::MoveHudForInventory (bool inv_open) inline private
Definition at line 1055 of file missiongameplay.c.
    {
        #ifdef PLATFORM_CONSOLE
        IngameHud hud = IngameHud.Cast( GetHud() );
        if( hud )
        {
            if( inv_open )
            {
                hud.GetHudPanelWidget().SetPos( 0, -0.055 );
            }
            else
            {
                hud.GetHudPanelWidget().SetPos( 0, 0 );
            }
        }
        #endif
    }
References GetHud().
OnClientDisconnectedEvent()
void MissionBase::OnClientDisconnectedEvent (PlayerIdentity identity, PlayerBase player, int logoutTime, bool authFailed) inline private
Definition at line 538 of file missionserver.c.
    {
        bool disconnectNow = true;
        // TODO: get out of vehicle
        // using database and no saving if authorization failed
        if (GetHive() && !authFailed)
        {
            if (player.IsAlive())
            {
                if (!m_LogoutPlayers.Contains(player) && !m_NewLogoutPlayers.Contains(player))
                {
                    Print("[Logout]: New player " + identity.GetId() + " with logout time " + logoutTime.ToString());
                    // send statistics to client
                    player.StatSyncToClient();
                    // inform client about logout time
                    GetGame().SendLogoutTime(player, logoutTime);
                    // wait for some time before logout and save
                    LogoutInfo params = new LogoutInfo(GetGame().GetTime() + logoutTime * 1000, identity.GetId());
                    m_NewLogoutPlayers.Insert(player, params);
                    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(AddNewPlayerLogout, 0, false, player, params);
                    // allow reconnecting to old char only if not in cars, od ladders etc. as they cannot be properly synchronized for reconnect
                    //if (!player.GetCommand_Vehicle() && !player.GetCommand_Ladder())
                    //{
                    //  GetGame().AddToReconnectCache(identity);
                    //}
                    // wait until logout timer runs out
                    disconnectNow = false;
                }
                return;
            }
        }
        if (disconnectNow)
        {
            Print("[Logout]: New player " + identity.GetId() + " with instant logout");
            // inform client about instant logout
            GetGame().SendLogoutTime(player, 0);
            PlayerDisconnected(player, identity, identity.GetId());
        }
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), GetHive(), PlayerIdentityBase::GetId(), GetTime(), PlayerDisconnected(), Print(), CGame::SendLogoutTime(), and string::ToString().
Referenced by OnEvent().
OnClientNewEvent()
PlayerBase MissionBase::OnClientNewEvent (PlayerIdentity identity, vector pos, ParamsReadContext ctx) inline private
Definition at line 486 of file missionserver.c.
    {
        string characterType;
        //m_RespawnMode = GetGame().ServerConfigGetInt("setRespawnMode"); //todo - init somewhere safe
        //SyncRespawnModeInfo(identity);
        // get login data for new character
        if ( ProcessLoginData(ctx) && (m_RespawnMode == GameConstants.RESPAWN_MODE_CUSTOM) && !GetGame().GetMenuDefaultCharacterData(false).IsRandomCharacterForced() )
        {
            if (GetGame().ListAvailableCharacters().Find(GetGame().GetMenuDefaultCharacterData().GetCharacterType()) > -1)
                characterType = GetGame().GetMenuDefaultCharacterData().GetCharacterType();
            else //random type
                characterType = GetGame().CreateRandomPlayer();
        }
        else
        {
            characterType = GetGame().CreateRandomPlayer();
            GetGame().GetMenuDefaultCharacterData().GenerateRandomEquip();
        }
        if (CreateCharacter(identity, pos, ctx, characterType))
        {
            EquipCharacter(GetGame().GetMenuDefaultCharacterData());
        }
        return m_player;
    }
References CreateCharacter(), CGame::CreateRandomPlayer(), EquipCharacter(), MenuDefaultCharacterData::GenerateRandomEquip(), MenuDefaultCharacterData::GetCharacterType(), GetGame(), CGame::GetMenuDefaultCharacterData(), ListAvailableCharacters(), m_player, ProcessLoginData(), and GameConstants::RESPAWN_MODE_CUSTOM.
Referenced by OnEvent().
OnClientPrepareEvent()
void MissionBase::OnClientPrepareEvent (PlayerIdentity identity, out bool useDB, out vector pos, out float yaw, out int preloadTimeout) inline private
Definition at line 386 of file missionserver.c.
    {
        if (GetHive())
        {
            // use character from database
            useDB = true;
        }
        else
        {
            // use following data without database
            useDB = false;
            pos = "1189.3 0.0 5392.48";
            yaw = 0;
        }
    }
References GetHive().
Referenced by OnEvent().
OnClientReadyEvent()
void MissionBase::OnClientReadyEvent (PlayerIdentity identity, PlayerBase player) inline private
Definition at line 513 of file missionserver.c.
    {
        GetGame().SelectPlayer(identity, player);
    }
References GetGame(), and CGame::SelectPlayer().
Referenced by OnEvent().
OnClientReconnectEvent()
void MissionBase::OnClientReconnectEvent (PlayerIdentity identity, PlayerBase player) inline private
Definition at line 530 of file missionserver.c.
    {
        if ( player )
        {
            player.OnReconnect();
        }
    }
Referenced by OnEvent().
OnClientRespawnEvent()
void MissionBase::OnClientRespawnEvent (PlayerIdentity identity, PlayerBase player) inline private
Definition at line 518 of file missionserver.c.
    {
        if(player)
        {
            if (player.IsUnconscious() || player.IsRestrained())
            {
                // kill character
                player.SetHealth("", "", 0.0);
            }
        }
    }
Referenced by OnEvent().
OnEvent() [1/2]
override void MissionBase::OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 659 of file missiongameplay.c.
    {
        super.OnEvent(eventTypeId, params);
        InventoryMenu menu;
        Man player = GetGame().GetPlayer();
        switch (eventTypeId)
        {
            case ChatMessageEventTypeID:
                ChatMessageEventParams chat_params = ChatMessageEventParams.Cast( params );
                if (m_LifeState == EPlayerStates.ALIVE)
                {
                    m_Chat.Add(chat_params);
                }
                break;
            case ChatChannelEventTypeID:
                ChatChannelEventParams cc_params = ChatChannelEventParams.Cast( params );
                ChatInputMenu chatMenu = ChatInputMenu.Cast( GetUIManager().FindMenu(MENU_CHAT_INPUT) );
                if (chatMenu)
                {
                    chatMenu.UpdateChannel();
                }
                else
                {
                    m_ChatChannelText.SetText(ChatInputMenu.GetChannelName(cc_params.param1));
                    m_ChatChannelFadeTimer.FadeIn(m_ChatChannelArea, 0.5, true);
                    m_ChatChannelHideTimer.Run(2, m_ChatChannelFadeTimer, "FadeOut", new Param3<Widget, float, bool>(m_ChatChannelArea, 0.5, true));
                }
                break;
            case WindowsResizeEventTypeID:
                DestroyAllMenus();
                m_Hud.OnResizeScreen();
                break;
            case SetFreeCameraEventTypeID:
                SetFreeCameraEventParams set_free_camera_event_params = SetFreeCameraEventParams.Cast( params );
                PluginDeveloper plugin_developer = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
                plugin_developer.OnSetFreeCameraEvent( PlayerBase.Cast( player ), set_free_camera_event_params.param1 );
                break;
        }
    }
References DestroyAllMenus(), GetGame(), CGame::GetPlayer(), GetPlugin(), GetUIManager(), InventoryMenu(), m_Hud, MENU_CHAT_INPUT, and Hud::OnResizeScreen().
OnEvent() [2/2]
override void MissionBase::OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 252 of file missionserver.c.
    {
        PlayerIdentity identity;
        PlayerBase player;
        int counter = 0;
        switch(eventTypeId)
        {
        case ClientPrepareEventTypeID:
            ClientPrepareEventParams clientPrepareParams;
            Class.CastTo(clientPrepareParams, params);
            CfgGameplayHandler.SyncDataSendEx(clientPrepareParams.param1);
            UndergroundAreaLoader.SyncDataSend(clientPrepareParams.param1);
            OnClientPrepareEvent(clientPrepareParams.param1, clientPrepareParams.param2, clientPrepareParams.param3, clientPrepareParams.param4, clientPrepareParams.param5);
            break;
        case ClientNewEventTypeID:
            ClientNewEventParams newParams;
            Class.CastTo(newParams, params);
            player = OnClientNewEvent(newParams.param1, newParams.param2, newParams.param3);
            if (!player)
            {
                Debug.Log("ClientNewEvent: Player is empty");
                return;
            }
            identity = newParams.param1;
            InvokeOnConnect(player,identity );
            SyncEvents.SendPlayerList();
            ControlPersonalLight(player);
            SyncGlobalLighting(player);
            break;
        case ClientReadyEventTypeID:
            ClientReadyEventParams readyParams;
            Class.CastTo(readyParams, params);
            identity = readyParams.param1;
            Class.CastTo(player, readyParams.param2);
            if (!player)
            {
                Debug.Log("ClientReadyEvent: Player is empty");
                return;
            }
            OnClientReadyEvent(identity, player);
            InvokeOnConnect(player, identity);
            // Send list of players at all clients
            SyncEvents.SendPlayerList();
            ControlPersonalLight(player);
            SyncGlobalLighting(player);
            break;
        case ClientRespawnEventTypeID:
            ClientRespawnEventParams respawnParams;
            Class.CastTo(respawnParams, params);
            identity = respawnParams.param1;
            Class.CastTo(player, respawnParams.param2);
            if (!player)
            {
                Debug.Log("ClientRespawnEvent: Player is empty");
                return;
            }
            OnClientRespawnEvent(identity, player);
            break;
        case ClientReconnectEventTypeID:
            ClientReconnectEventParams reconnectParams;
            Class.CastTo(reconnectParams, params);
            identity = reconnectParams.param1;
            Class.CastTo(player, reconnectParams.param2);
            if (!player)
            {
                Debug.Log("ClientReconnectEvent: Player is empty");
                return;
            }
            OnClientReconnectEvent(identity, player);
            break;
        case ClientDisconnectedEventTypeID:
            ClientDisconnectedEventParams discoParams;
            Class.CastTo(discoParams, params);
            identity = discoParams.param1;
            Class.CastTo(player, discoParams.param2);
            int logoutTime = discoParams.param3;
            bool authFailed = discoParams.param4;
            if (!player)
            {
                Debug.Log("ClientDisconnectenEvent: Player is empty");
                return;
            }
            OnClientDisconnectedEvent(identity, player, logoutTime, authFailed);
            break;
        case LogoutCancelEventTypeID:
            LogoutCancelEventParams logoutCancelParams;
            Class.CastTo(logoutCancelParams, params);
            Class.CastTo(player, logoutCancelParams.param1);
            identity = player.GetIdentity();
            if (identity)
            {
                // disable reconnecting to old char
                // GetGame().RemoveFromReconnectCache(identity.GetId());
                Print("[Logout]: Player " + identity.GetId() + " cancelled");
            }
            else
            {
                Print("[Logout]: Player cancelled");
            }
            m_LogoutPlayers.Remove(player);
            m_NewLogoutPlayers.Remove(player);
            break;
        }
    }
References Class::CastTo(), ControlPersonalLight(), PlayerIdentityBase::GetId(), InvokeOnConnect(), Debug::Log(), OnClientDisconnectedEvent(), OnClientNewEvent(), OnClientPrepareEvent(), OnClientReadyEvent(), OnClientReconnectEvent(), OnClientRespawnEvent(), Print(), SyncEvents::SendPlayerList(), UndergroundAreaLoader::SyncDataSend(), CfgGameplayHandler::SyncDataSendEx(), and SyncGlobalLighting().
OnGameplayDataHandlerLoad()
override void MissionBase::OnGameplayDataHandlerLoad () inline private
Definition at line 104 of file missionserver.c.
    {
        //Print("MissionServer - OnGameplayDataHandlerLoad()");
        m_RespawnMode = CfgGameplayHandler.GetDisableRespawnDialog();
        GetGame().SetDebugMonitorEnabled(GetGame().ServerConfigGetInt("enableDebugMonitor"));
        InitialiseWorldData();
    }
References CfgGameplayHandler::GetDisableRespawnDialog(), GetGame(), InitialiseWorldData(), and CGame::SetDebugMonitorEnabled().
OnInit() [1/3]
override void MissionBase::OnInit () inline private
Definition at line 87 of file missiongameplay.c.
    {
        super.OnInit();
        if ( m_Initialized )
        {
            return;
        }
        #ifdef DEVELOPER
        if (!GetGame().IsMultiplayer())//to make it work in single during development
        {
            UndergroundAreaLoader.SpawnAllTriggerCarriers();
        }
        #endif
        PPEffects.Init(); //DEPRECATED, left in for legacy purposes only
        MapMarkerTypes.Init();
        m_UIManager = GetGame().GetUIManager();
        m_Initialized               = true;
        // init hud ui
        if ( !m_HudRootWidget )
        {
            m_HudRootWidget         = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_hud.layout");
            m_HudRootWidget.Show(false);
            m_Chat.Init(m_HudRootWidget.FindAnyWidget("ChatFrameWidget"));
            m_ActionMenu.Init( m_HudRootWidget.FindAnyWidget("ActionsPanel"), TextWidget.Cast( m_HudRootWidget.FindAnyWidget("DefaultActionWidget") ) );
            m_Hud.Init( m_HudRootWidget.FindAnyWidget("HudPanel") );
            // von enabled icon
            m_MicrophoneIcon = ImageWidget.Cast( m_HudRootWidget.FindAnyWidget("mic") );
            m_MicrophoneIcon.Show(false);
            // von voice level
            m_VoiceLevels = m_HudRootWidget.FindAnyWidget("VoiceLevelsPanel");
            m_VoiceLevelsWidgets = new map<int, ImageWidget>; // [key] voice level
            m_VoiceLevelTimers = new map<int,ref WidgetFadeTimer>; // [key] voice level
            if( m_VoiceLevels )
            {
                m_VoiceLevelsWidgets.Set(VoiceLevelWhisper, ImageWidget.Cast( m_VoiceLevels.FindAnyWidget("Whisper") ));
                m_VoiceLevelsWidgets.Set(VoiceLevelTalk, ImageWidget.Cast( m_VoiceLevels.FindAnyWidget("Talk") ));
                m_VoiceLevelsWidgets.Set(VoiceLevelShout, ImageWidget.Cast( m_VoiceLevels.FindAnyWidget("Shout") ));
                m_VoiceLevelTimers.Set(VoiceLevelWhisper, new WidgetFadeTimer);
                m_VoiceLevelTimers.Set(VoiceLevelTalk, new WidgetFadeTimer);
                m_VoiceLevelTimers.Set(VoiceLevelShout, new WidgetFadeTimer);
            }
            HideVoiceLevelWidgets();
            // chat channel
            m_ChatChannelArea       = m_HudRootWidget.FindAnyWidget("ChatChannelPanel");
            m_ChatChannelText       = TextWidget.Cast( m_HudRootWidget.FindAnyWidget("ChatChannelText") );
        }
        // init hud ui
        #ifdef DEVELOPER
            m_HudDebug              = new HudDebug;
            if ( !m_HudDebug.IsInitialized() )
            {
                m_HudDebug.Init( GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_hud_debug.layout") );
                PluginConfigDebugProfile.GetInstance().SetLogsEnabled(LogManager.IsLogsEnable());
            }
        #endif
        if ( GetGame().IsMultiplayer() )
        {
            OnlineServices.m_MuteUpdateAsyncInvoker.Insert( SendMuteListToServer );
        }
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetUIManager(), CGame::GetWorkspace(), HideVoiceLevelWidgets(), HudDebug(), PPEffects::Init(), MapMarkerTypes::Init(), Hud::Init(), ScriptInvoker::Insert(), LogManager::IsLogsEnable(), m_Hud, m_Initialized, OnlineServices::m_MuteUpdateAsyncInvoker, and UndergroundAreaLoader::SpawnAllTriggerCarriers().
OnInit() [2/3]
override void MissionBase::OnInit () inline private
Definition at line 10 of file missionmainmenu.c.
    {
        if (!m_NoCutscene)
        {
            CreateIntroScene();
        }
        if (!m_mainmenu)
        {
            #ifdef PLATFORM_CONSOLE
            if ( g_Game.GetGameState() != DayZGameState.PARTY )
            {
                m_mainmenu = UIScriptedMenu.Cast( g_Game.GetUIManager().EnterScriptedMenu( MENU_TITLE_SCREEN, null ) );
            }
            #else
                m_mainmenu = UIScriptedMenu.Cast( g_Game.GetUIManager().EnterScriptedMenu( MENU_MAIN, null ) );
            #endif
        }
        GetOnInputDeviceChanged().Insert(OnInputDeviceChanged);
    }
References CreateIntroScene(), g_Game, MENU_MAIN, MENU_TITLE_SCREEN, and OnInputDeviceChanged().
OnInit() [3/3]
override void MissionBase::OnInit () inline private
Definition at line 74 of file missionserver.c.
    {
        //Print("OnInit()");
        super.OnInit();
        CfgGameplayHandler.LoadData();
        UndergroundAreaLoader.SpawnAllTriggerCarriers();
        //Either pass consts in Init.c or insert all desired coords ( or do both ;) )
        m_FiringPos = new array<vector>;
    }
References CfgGameplayHandler::LoadData(), and UndergroundAreaLoader::SpawnAllTriggerCarriers().
OnInputDeviceChanged()
void MissionBase::OnInputDeviceChanged (int device) inline private
Definition at line 128 of file missionmainmenu.c.
    {
        if (m_CreditsMenu)
        {
            m_CreditsMenu.UpdateInfoPanelText(device);
        }
    }
OnItemUsed()
override void MissionBase::OnItemUsed (InventoryItem item, Man owner) inline private
Definition at line 704 of file missiongameplay.c.
    {
        if (item && GetUIManager().GetMenu() == NULL)
        {
            if (item.IsInherited(ItemBook))
            {
                BookMenu bookMenu = BookMenu.Cast( GetUIManager().EnterScriptedMenu(MENU_BOOK, NULL) );
                if (bookMenu)
                {
                    bookMenu.ReadBook(item);
                }
            }
        }
    }
References GetUIManager(), and MENU_BOOK.
OnKeyPress()
override void MissionBase::OnKeyPress (int key) inline private
Definition at line 648 of file missiongameplay.c.
    {
        super.OnKeyPress(key);
        m_Hud.KeyPress(key);
    }
References Hud::KeyPress(), and m_Hud.
OnKeyRelease() [1/2]
override void MissionBase::OnKeyRelease (int key) inline private
Definition at line 654 of file missiongameplay.c.
    {
        super.OnKeyRelease(key);
    }
OnKeyRelease() [2/2]
override void MissionBase::OnKeyRelease (int key) inline private
Definition at line 136 of file missionmainmenu.c.
    {
        super.OnKeyRelease(key);
        if ( key == KeyCode.KC_Q )
        {
            /*
            array<int> list = new  array<int>();
            Print("Start--------");
            list.Debug();
            int i = 0;
            while ( i < 20 )
            {
                SortedInsert(list, Math.RandomIntInclusive(0, 20));
                i += 1;
            }
            Print("End--------");
            list.Debug();
            */
        }
    }
OnMenuEnter()
void MissionBase::OnMenuEnter (int menu_id) inline private
Definition at line 116 of file missionmainmenu.c.
    {
        switch (menu_id)
        {
            case MENU_CREDITS:
            {
                m_CreditsMenu = CreditsMenu.Cast(GetGame().GetUIManager().GetMenu());
                //Print(m_CreditsMenu);
            }
        }
    }
References GetGame(), GetUIManager(), and MENU_CREDITS.
OnMissionFinish() [1/2]
override void MissionBase::OnMissionFinish () inline private
Definition at line 205 of file missiongameplay.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //Print("OnMissionFinish");
        GetUIManager().HideDialog();
        DestroyAllMenus();
        m_Chat.Destroy();
        delete m_HudRootWidget;
        #ifdef PLATFORM_CONSOLE
            OnlineServices.m_MuteUpdateAsyncInvoker.Remove( SendMuteListToServer );
        #endif
        if (m_DebugMonitor)
            m_DebugMonitor.Hide();
        g_Game.GetUIManager().ShowUICursor(false);
        PPEManagerStatic.GetPPEManager().StopAllEffects(PPERequesterCategory.ALL);
        EnableAllInputs();
        g_Game.SetMissionState( DayZGame.MISSION_STATE_FINNISH );
    }
References DayZGame(), DestroyAllMenus(), EnableAllInputs(), g_Game, GetGame(), GetPlayer(), PPEManagerStatic::GetPPEManager(), GetUIManager(), UIManager::HideDialog(), m_HudRootWidget, OnlineServices::m_MuteUpdateAsyncInvoker, and ScriptInvoker::Remove().
OnMissionFinish() [2/2]
override void MissionBase::OnMissionFinish () inline private
Definition at line 88 of file missionmainmenu.c.
    {
        if ( m_mainmenu )
            m_mainmenu.Cleanup();
        GetGame().GetUIManager().CloseAll();
        m_mainmenu = NULL;
        m_IntroScenePC = null;
        m_IntroSceneXbox = null;
        m_CreditsMenu = null;
        g_Game.GetUIManager().ShowUICursor(false);
    }
References UIManager::CloseAll(), g_Game, GetGame(), and CGame::GetUIManager().
OnMissionStart() [1/3]
override void MissionBase::OnMissionStart () inline private
Definition at line 172 of file missiongameplay.c.
    {
        g_Game.SetConnecting(false);
        GetUIManager().ShowUICursor(false);
        g_Game.SetMissionState( DayZGame.MISSION_STATE_GAME );
    }
References DayZGame(), g_Game, GetUIManager(), and UIManager::ShowUICursor().
OnMissionStart() [2/3]
override void MissionBase::OnMissionStart () inline private
Definition at line 73 of file missionmainmenu.c.
    {
        if (m_mainmenu)
        {
            //m_mainmenu.FadeIn(2.0);   //Fade in method is currently commented in MainMenu class
        }
        g_Game.GetUIManager().ShowUICursor(true);
        g_Game.SetMissionState( DayZGame.MISSION_STATE_MAINMENU );
        //Print("*** MissionMainMenu.OnMissionStart()");
        g_Game.LoadingHide(true);
        ProgressAsync.DestroyAllPendingProgresses();
        PlayMusic();
    }
References DayZGame(), ProgressAsync::DestroyAllPendingProgresses(), g_Game, and PlayMusic().
OnMissionStart() [3/3]
override void MissionBase::OnMissionStart () inline private
Definition at line 84 of file missionserver.c.
    {
        super.OnMissionStart();
        // We will load the Effect areas on Default mission start
        EffectAreaLoader.CreateZones();
    }
References EffectAreaLoader::CreateZones().
OnPlayerRespawned()
override void MissionBase::OnPlayerRespawned (Man player) inline private
Definition at line 1522 of file missiongameplay.c.
    {
        #ifdef DEVELOPER
            if (m_HudDebug)
                m_HudDebug.RefreshByLocalProfile();
        #endif
        PlayerBase playerBase = PlayerBase.Cast(player);
        if (playerBase)
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(playerBase.ShowDeadScreen, DayZPlayerImplement.DEAD_SCREEN_DELAY, false, false, 0);
        }
        GetGame().GetSoundScene().SetSoundVolume(g_Game.m_volume_sound,1);
        GetGame().GetSoundScene().SetSpeechExVolume(g_Game.m_volume_speechEX,1);
        GetGame().GetSoundScene().SetMusicVolume(g_Game.m_volume_music,1);
        GetGame().GetSoundScene().SetVOIPVolume(g_Game.m_volume_VOIP,1);
        GetGame().GetSoundScene().SetRadioVolume(g_Game.m_volume_radio,1);
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), g_Game, CGame::GetCallQueue(), GetGame(), and CGame::GetSoundScene().
OnUpdate() [1/3]
override void MissionBase::OnUpdate (float timeslice) inline private
Definition at line 228 of file missiongameplay.c.
    {
        Man player = GetGame().GetPlayer();
        PlayerBase playerPB = PlayerBase.Cast(player);
        TickScheduler(timeslice);
        UpdateDummyScheduler();//for external entities
        UIScriptedMenu menu = m_UIManager.GetMenu();
        InventoryMenu inventory = InventoryMenu.Cast( m_UIManager.FindMenu(MENU_INVENTORY) );
        NoteMenu note_menu = NoteMenu.Cast( m_UIManager.FindMenu(MENU_NOTE) );
        GesturesMenu gestures_menu = GesturesMenu.Cast(m_UIManager.FindMenu(MENU_GESTURES));
        RadialQuickbarMenu quickbar_menu = RadialQuickbarMenu.Cast(m_UIManager.FindMenu(MENU_RADIAL_QUICKBAR));
        InspectMenuNew inspect = InspectMenuNew.Cast( m_UIManager.FindMenu(MENU_INSPECT) );
        Input input = GetGame().GetInput();
        ActionBase runningAction;
        if ( playerPB )
        {
            #ifdef DEVELOPER
            if ( DiagMenu.GetBool(DiagMenuIDs.DM_HOLOGRAM) )
            {
                DbgUI.Begin("Hologram Debug", 5, 5);
            }
            #endif
            if ( playerPB.GetHologramLocal() )
            {
                playerPB.GetHologramLocal().UpdateHologram( timeslice );
            }
            #ifdef DEVELOPER
            else if ( DiagMenu.GetBool(DiagMenuIDs.DM_HOLOGRAM) )
            {
                DbgUI.Text("No active Hologram");
            }
            if ( DiagMenu.GetBool(DiagMenuIDs.DM_HOLOGRAM) )
            {
                DbgUI.End();
            }
            #endif
            runningAction = playerPB.GetActionManager().GetRunningAction();
        }
#ifdef PLATFORM_CONSOLE
        //'Special behaviour' (read 'hack') for colliding VON distance input actions [CONSOLE ONLY]
        if ( input.LocalValue("UAVoiceModifierHelper",false) && !menu)
        {
            GetUApi().GetInputByName("UAUIQuickbarRadialOpen").Lock();
            GetUApi().GetInputByName("UAZoomInToggle").Lock();
            GetUApi().GetInputByName("UAPersonView").Lock();
            GetUApi().GetInputByName("UALeanLeft").Lock();
            GetUApi().GetInputByName("UALeanRight").Lock();
        }
        else if ( input.LocalRelease("UAVoiceModifierHelper",false) ) //unlocks on release, if already excluded, all the other inputs should be locked/unlocked in the exclude (if defined properly!)
        {
            GetUApi().GetInputByName("UAUIQuickbarRadialOpen").Unlock();
            GetUApi().GetInputByName("UAZoomInToggle").Unlock();
            GetUApi().GetInputByName("UAPersonView").Unlock();
            GetUApi().GetInputByName("UALeanLeft").Unlock();
            GetUApi().GetInputByName("UALeanRight").Unlock();
            RefreshExcludes();
        }
        //Radial quickbar
        if ( input.LocalPress("UAUIQuickbarRadialOpen",false) )
        {
            //open quickbar menu
            if ( playerPB.IsAlive() && !playerPB.IsRaised() && !playerPB.IsUnconscious() && !playerPB.GetCommand_Vehicle() )    //player hands not raised, player is not in prone and player is not interacting with vehicle
            {
                if ( !GetUIManager().IsMenuOpen( MENU_RADIAL_QUICKBAR ) )
                {
                    RadialQuickbarMenu.OpenMenu();
                    m_Hud.ShowHudUI( false );
                }
            }
        }
        bool b1 = RadialQuickbarMenu.GetItemToAssign() != null;
        //close quickbar menu from world
        if ( GetUIManager().IsMenuOpen( MENU_RADIAL_QUICKBAR ) && (!RadialQuickbarMenu.GetMenuInstance().GetParentMenu() || RadialQuickbarMenu.GetMenuInstance().GetParentMenu() != inventory) && (input.LocalRelease("UAUIQuickbarRadialOpen",false) || !input.LocalValue("UAUIQuickbarRadialOpen",false)) )
        {
            RadialQuickbarMenu.CloseMenu();
            quickbar_menu.SetMenuClosing(true);
            m_Hud.ShowHudUI( true );
        }
        //Radial Quickbar from inventory
        if ( (RadialQuickbarMenu.instance && RadialQuickbarMenu.GetMenuInstance().GetParentMenu() && RadialQuickbarMenu.GetMenuInstance().GetParentMenu() == inventory) && GetGame().GetInput().LocalRelease("UAUIQuickbarRadialInventoryOpen",false) )
        {
            //close radial quickbar menu
            if ( GetGame().GetUIManager().IsMenuOpen( MENU_RADIAL_QUICKBAR ) )
            {
                RadialQuickbarMenu.CloseMenu();
                quickbar_menu.SetMenuClosing(true);
                RadialQuickbarMenu.SetItemToAssign( NULL );
                AddActiveInputExcludes({"inventory"});
                AddActiveInputRestriction(EInputRestrictors.INVENTORY);
            }
        }
        //Special behaviour for leaning [CONSOLE ONLY]
        if ( playerPB && !GetGame().IsInventoryOpen() )
        {
            if ( playerPB.IsRaised() || playerPB.IsInRasedProne() )
            {
                GetUApi().GetInputByName( "UALeanLeft"  ).Unlock();
                GetUApi().GetInputByName( "UALeanRight" ).Unlock();
            }
            else
            {
                GetUApi().GetInputByName( "UALeanLeft"  ).Lock();
                GetUApi().GetInputByName( "UALeanRight" ).Lock();
            }
        }
        else
        {
            if ( playerPB )
            {
                GetUApi().GetInputByName( "UALeanLeft"  ).Lock();
                GetUApi().GetInputByName( "UALeanRight" ).Lock();
            }
        }
        //Special behaviour for freelook & zeroing [CONSOLE ONLY]
        if ( playerPB )
        {
            if ( playerPB.IsRaised() )
            {
                GetUApi().GetInputByName( "UALookAround"    ).Lock();       //disable freelook
                GetUApi().GetInputByName( "UALookAroundToggle"  ).Lock();       //disable freelook
                GetUApi().GetInputByName( "UAZeroingUp"     ).Unlock();     //enable zeroing
                GetUApi().GetInputByName( "UAZeroingDown"   ).Unlock();
            }
            else
            {
                GetUApi().GetInputByName( "UALookAround"    ).Unlock(); //enable freelook
                GetUApi().GetInputByName( "UALookAroundToggle"  ).Unlock(); //enable freelook
                GetUApi().GetInputByName( "UAZeroingUp"     ).Lock();       //disable zeroing
                GetUApi().GetInputByName( "UAZeroingDown"   ).Lock();
            }
        }
#endif
        //Gestures
        if ( input.LocalPress("UAUIGesturesOpen",false) )
        {
            //open gestures menu
            if ( !playerPB.IsRaised() && (playerPB.GetActionManager().ActionPossibilityCheck(playerPB.m_MovementState.m_CommandTypeId) || playerPB.IsEmotePlaying()) && !playerPB.GetCommand_Vehicle() )
            {
                if ( !GetUIManager().IsMenuOpen( MENU_GESTURES ) )
                {
                    GesturesMenu.OpenMenu();
                    m_Hud.ShowHudUI( false );
                }
            }
        }
        if ( input.LocalRelease("UAUIGesturesOpen",false) || input.LocalValue("UAUIGesturesOpen",false) == 0 )
        {
            //close gestures menu
            if ( GetUIManager().IsMenuOpen( MENU_GESTURES ) )
            {
                GesturesMenu.CloseMenu();
                gestures_menu.SetMenuClosing(true);
                m_Hud.ShowHudUI( true );
            }
        }
        if (player && m_LifeState == EPlayerStates.ALIVE && !player.IsUnconscious() )
        {
            // enables HUD on spawn
            if (m_HudRootWidget)
            {
                m_HudRootWidget.Show(true);
            }
        #ifndef NO_GUI
            // fade out black screen
            if ( GetUIManager().ScreenFadeVisible() )
            {
                 GetUIManager().ScreenFadeOut(0.5);
            }
        #endif
            if (input.LocalPress("UAGear",false))
            {
                if (!inventory && playerPB.CanManipulateInventory() && IsMapUnfoldActionRunning(runningAction))
                {
                    ShowInventory();
                    menu = m_InventoryMenu;
                }
                else if (menu == inventory)
                {
                    HideInventory();
                }
            }
            if (input.LocalPress("UAUIMenu",false) && menu && inventory && menu == inventory)
            {
                HideInventory();
            }
            #ifndef PLATFORM_CONSOLE
            if ( input.LocalPress("UAChat",false) )
            {
                ChatInputMenu chat = ChatInputMenu.Cast( m_UIManager.FindMenu(MENU_CHAT) );
                if ( menu == NULL )
                {
                    ShowChat();
                }
            }
            #endif
            // voice level updated
            VONManager.GetInstance().HandleInput(input);
            if (input.LocalHold("UAUIQuickbarToggle", false))
            {
                if (!m_QuickbarHold)
                {
                    m_QuickbarHold = true;
                    m_Hud.ShowHudPlayer(m_Hud.IsHideHudPlayer());
                }
            }
            if (input.LocalRelease("UAUIQuickbarToggle", false))
            {
                if (!m_QuickbarHold)
                {
                    m_Hud.ShowQuickbarPlayer(m_Hud.IsHideQuickbarPlayer());
                }
                m_QuickbarHold = false;
            }
            if ( g_Game.GetInput().LocalPress("UAZeroingUp",false) || g_Game.GetInput().LocalPress("UAZeroingDown",false) || g_Game.GetInput().LocalPress("UAToggleWeapons",false) )
            {
                m_Hud.ZeroingKeyPress();
            }
            if ( menu == NULL )
            {
                m_ActionMenu.Refresh();
                if (input.LocalPress("UANextActionCategory",false))
                {
                    m_ActionMenu.NextActionCategory();
                }
                else if (input.LocalPress("UAPrevActionCategory",false))
                {
                    m_ActionMenu.PrevActionCategory();
                }
                else if (input.LocalPress("UANextAction",false))
                {
                    m_ActionMenu.NextAction();
                }
                else if (input.LocalPress("UAPrevAction",false))
                {
                    m_ActionMenu.PrevAction();
                }
            }
            else
            {
                m_ActionMenu.Hide();
            }
            //hologram rotation
            if (menu == NULL && playerPB.IsPlacingLocal() && playerPB.GetHologramLocal().GetParentEntity().PlacementCanBeRotated())
            {
                if ( input.LocalRelease("UANextAction",false) )
                {
                    playerPB.GetHologramLocal().SubtractProjectionRotation(15);
                }
                if ( input.LocalRelease("UAPrevAction",false) )
                {
                    playerPB.GetHologramLocal().AddProjectionRotation(15);
                }
            }
            if (CfgGameplayHandler.GetMapIgnoreMapOwnership())
            {
                if (input.LocalPress("UAMapToggle", false) && !m_UIManager.GetMenu())
                {
                    if (IsMapUnfoldActionRunning(runningAction))
                    {
                        HandleMapToggleByKeyboardShortcut(player);
                    }
                }
            }
        }
        // life state check
        if (player)
        {
            int life_state = player.GetPlayerState();
            // life state changed
            if (m_LifeState != life_state)
            {
                m_LifeState = life_state;
                if (m_LifeState != EPlayerStates.ALIVE)
                {
                    CloseAllMenus();
                }
            }
        }
        if (menu && !menu.UseKeyboard() && menu.UseMouse())
        {
            int i;
            for (i = 0; i < 5; i++)
            {
                input.DisableKey(i | INPUT_DEVICE_MOUSE);
                input.DisableKey(i | INPUT_ACTION_TYPE_DOWN_EVENT | INPUT_DEVICE_MOUSE);
                input.DisableKey(i | INPUT_ACTION_TYPE_DOUBLETAP | INPUT_DEVICE_MOUSE);
            }
            for (i = 0; i < 6; i++)
            {
                input.DisableKey(i | INPUT_DEVICE_MOUSE_AXIS);
            }
        }
        if (!m_UIManager.IsDialogVisible())
        {
            if ( menu )
            {
                if ( menu == inspect )
                {
                    if (input.LocalPress("UAGear",false))
                    {
                        if ( ItemManager.GetInstance().GetSelectedItem() == NULL )
{
                            HideInventory();
                        }
                    }
                    else if (input.LocalPress("UAUIBack",false))
                    {
                        if ( ItemManager.GetInstance().GetSelectedItem() == NULL )
{
                            HideInventory();
                        }
                    }
                }
                else if (menu == note_menu && (!IsInputExcludeActive("inventory") || !IsInputRestrictionActive(EInputRestrictors.INVENTORY)))
                {
                    AddActiveInputExcludes({"inventory"});
                    AddActiveInputRestriction(EInputRestrictors.INVENTORY);
                }
                else if (menu == gestures_menu && !gestures_menu.IsMenuClosing() && !IsInputExcludeActive("radialmenu"))
                {
                    AddActiveInputExcludes({"radialmenu"});
                    GetUApi().GetInputByName("UAUIGesturesOpen").Unlock();
                }
                else if (menu == quickbar_menu && !quickbar_menu.IsMenuClosing() && !IsInputExcludeActive("radialmenu"))
                {
                    AddActiveInputExcludes({"radialmenu"});
                    GetUApi().GetInputByName("UAUIQuickbarRadialOpen").Unlock();
                }
                else if ( IsPaused() )
                {
                    InGameMenuXbox menu_xb = InGameMenuXbox.Cast( GetGame().GetUIManager().GetMenu() );
                    if ( !g_Game.GetUIManager().ScreenFadeVisible() && ( !menu_xb || !menu_xb.IsOnlineOpen() ) )
                    {
                        if ( input.LocalPress("UAUIMenu",false) )
{
                            Continue();
                        }
                        else if ( input.LocalPress( "UAUIBack", false ) )
{
                            Continue();
                        }
                    }
                    else if ( input.LocalPress( "UAUIBack", false ) )
                    {
                        if ( menu_xb && menu_xb.IsOnlineOpen() )
{
                            menu_xb.CloseOnline();
                        }
                    }
                }
            }
            else if (input.LocalPress("UAUIMenu",false))
            {
                if (IsMapUnfoldActionRunning(runningAction))
                {
                    Pause();
                }
            }
            //final controls check that suppresses inputs to avoid input collision. If anything needed to be handled without forced input suppression, it had been at this point.
            /*if ( playerPB )
            {
                //Print("playerPB.m_hac: " + playerPB.m_hac);
                if ( IsControlDisabled() && !menu && !m_PauseQueued && !playerPB.GetCommand_Melee2() && !playerPB.m_hac )
                {
                    EnableAllInputs(true);
                }
            }*/
        }
        UpdateDebugMonitor();
        SEffectManager.Event_OnFrameUpdate(timeslice);
        if (!GetGame().IsMultiplayer())
            m_WorldData.UpdateBaseEnvTemperature( timeslice );
#ifdef DEVELOPER
        DisplayHairDebug();
#endif
        super.OnUpdate( timeslice );
    }
References ActionBase(), AddActiveInputExcludes(), AddActiveInputRestriction(), DbgUI::Begin(), CloseAllMenus(), Continue(), Input::DisableKey(), DisplayHairDebug(), DbgUI::End(), SEffectManager::Event_OnFrameUpdate, UIManager::FindMenu(), g_Game, DiagMenu::GetBool(), GetGame(), CGame::GetInput(), GetInput(), UAInputAPI::GetInputByName(), VONManager::GetInstance(), ItemManager::GetInstance(), CfgGameplayHandler::GetMapIgnoreMapOwnership(), UIManager::GetMenu(), CGame::GetPlayer(), ItemManager::GetSelectedItem(), GetUApi(), GetUIManager(), VONManagerBase::HandleInput(), HandleMapToggleByKeyboardShortcut(), HideInventory(), INPUT_ACTION_TYPE_DOUBLETAP, INPUT_ACTION_TYPE_DOWN_EVENT, INPUT_DEVICE_MOUSE, INPUT_DEVICE_MOUSE_AXIS, InventoryMenu(), UIManager::IsDialogVisible(), Hud::IsHideHudPlayer(), Hud::IsHideQuickbarPlayer(), IsInputExcludeActive(), IsInputRestrictionActive(), IsInventoryOpen(), IsMapUnfoldActionRunning(), UIScriptedMenu::IsMenuClosing(), IsPaused(), Input::LocalHold(), Input::LocalPress(), Input::LocalRelease(), Input::LocalValue(), UAInput::Lock(), m_Hud, m_InventoryMenu, m_WorldData, MENU_CHAT, MENU_GESTURES, MENU_INSPECT, MENU_INVENTORY, MENU_NOTE, MENU_RADIAL_QUICKBAR, Pause(), RefreshExcludes(), UIManager::ScreenFadeOut(), ShowChat(), Hud::ShowHudPlayer(), Hud::ShowHudUI(), ShowInventory(), Hud::ShowQuickbarPlayer(), DbgUI::Text(), TickScheduler(), UAInput::Unlock(), WorldData::UpdateBaseEnvTemperature(), UpdateDebugMonitor(), UpdateDummyScheduler(), UIScriptedMenu::UseKeyboard(), UIScriptedMenu::UseMouse(), and Hud::ZeroingKeyPress().
OnUpdate() [2/3]
override void MissionBase::OnUpdate (float timeslice) inline private
Definition at line 101 of file missionmainmenu.c.
    {
        //Print("("+ GetGame().GetTime() +") ____OnUpdate: " + timeslice);
        if ( g_Game.IsLoading() )
        {
            return;
        }
        if (m_IntroScenePC)
        {
            m_IntroScenePC.Update();
        }
    }
References g_Game.
OnUpdate() [3/3]
override void MissionBase::OnUpdate (float timeslice) inline private
Definition at line 92 of file missionserver.c.
    {
        UpdateDummyScheduler();
        TickScheduler(timeslice);
        UpdateLogoutPlayers();
        m_WorldData.UpdateBaseEnvTemperature( timeslice );  // re-calculate base enviro temperature
        RandomArtillery( timeslice );
        super.OnUpdate( timeslice );
    }
References m_WorldData, RandomArtillery(), TickScheduler(), WorldData::UpdateBaseEnvTemperature(), UpdateDummyScheduler(), and UpdateLogoutPlayers().
Pause()
override void MissionBase::Pause () inline private
Definition at line 1182 of file missiongameplay.c.
    {
        if (IsPaused() || (GetGame().GetUIManager().GetMenu() && GetGame().GetUIManager().GetMenu().GetID() == MENU_INGAME))
        {
            return;
        }
        if ( g_Game.IsClient() && g_Game.GetGameState() != DayZGameState.IN_GAME )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if ( player && !player.IsPlayerLoaded() || IsPlayerRespawning() )
        {
            return;
        }
        m_PauseQueued = true;
        CloseAllMenus();
        // open ingame menu
        GetUIManager().EnterScriptedMenu( MENU_INGAME, GetGame().GetUIManager().GetMenu() );
        AddActiveInputExcludes({"menu"});
    }
References AddActiveInputExcludes(), CloseAllMenus(), UIManager::EnterScriptedMenu(), g_Game, GetGame(), GetID(), GetPlayer(), GetUIManager(), IsPaused(), and MENU_INGAME.
Referenced by OnUpdate().
PlayerControlDisable()
override void MissionBase::PlayerControlDisable (int mode) inline private
Deprecated; simple input restrictions.
Definition at line 781 of file missiongameplay.c.
    {
        super.PlayerControlDisable(mode);
        switch (mode)
        {
            case INPUT_EXCLUDE_ALL:
            {
                AddActiveInputExcludes({"menu"});
                break;
            }
            case INPUT_EXCLUDE_INVENTORY:
            {
                AddActiveInputExcludes({"inventory"});
                AddActiveInputRestriction(EInputRestrictors.INVENTORY);
                break;
            }
            case INPUT_EXCLUDE_MAP:
            {
                AddActiveInputExcludes({"loopedactions"});
                AddActiveInputRestriction(EInputRestrictors.MAP);
                break;
            }
            case INPUT_EXCLUDE_MOUSE_ALL:
            {
                AddActiveInputExcludes({"radialmenu"});
                break;
            }
            case INPUT_EXCLUDE_MOUSE_RADIAL:
            {
                AddActiveInputExcludes({"radialmenu"});
                break;
            }
            default:
            {
                Debug.Log("Unknown controls disable mode");
                return;
            }
        }
        m_ControlDisabledMode = mode;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player )
        {
            ItemBase item = player.GetItemInHands();
            if (item && item.IsWeapon())
                player.RequestResetADSSync();
        }
    }
References AddActiveInputExcludes(), AddActiveInputRestriction(), GetGame(), GetPlayer(), INPUT_EXCLUDE_ALL, INPUT_EXCLUDE_INVENTORY, INPUT_EXCLUDE_MAP, INPUT_EXCLUDE_MOUSE_ALL, INPUT_EXCLUDE_MOUSE_RADIAL, and Debug::Log().
PlayerControlEnable()
override void MissionBase::PlayerControlEnable (bool bForceSupress) inline private
Deprecated; removes last input exclude and associated controls restrictions.
Definition at line 732 of file missiongameplay.c.
    {
        super.PlayerControlEnable(bForceSupress);
        if (m_ControlDisabledMode != -1)
        {
            switch (m_ControlDisabledMode)
            {
                case INPUT_EXCLUDE_ALL:
                {
                    RemoveActiveInputExcludes({"menu"},bForceSupress);
                    break;
                }
                case INPUT_EXCLUDE_INVENTORY:
                {
                    RemoveActiveInputExcludes({"inventory"},bForceSupress);
                    RemoveActiveInputRestriction(EInputRestrictors.INVENTORY);
                    break;
                }
                case INPUT_EXCLUDE_MAP:
                {
                    RemoveActiveInputExcludes({"loopedactions"},bForceSupress);
                    RemoveActiveInputRestriction(EInputRestrictors.MAP);
                    break;
                }
                case INPUT_EXCLUDE_MOUSE_ALL:
                {
                    RemoveActiveInputExcludes({"radialmenu"},bForceSupress);
                    break;
                }
                case INPUT_EXCLUDE_MOUSE_RADIAL:
                {
                    RemoveActiveInputExcludes({"radialmenu"},bForceSupress);
                    break;
                }
            }
            m_ControlDisabledMode = -1;
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if (player)
            {
                HumanInputController hic = player.GetInputController();
                hic.LimitsDisableSprint(false);
            }
        }
    }
References GetGame(), GetPlayer(), INPUT_EXCLUDE_ALL, INPUT_EXCLUDE_INVENTORY, INPUT_EXCLUDE_MAP, INPUT_EXCLUDE_MOUSE_ALL, INPUT_EXCLUDE_MOUSE_RADIAL, HumanInputController::LimitsDisableSprint(), RemoveActiveInputExcludes(), and RemoveActiveInputRestriction().
PlayerDisconnected()
void MissionBase::PlayerDisconnected (PlayerBase player, PlayerIdentity identity, string uid) inline private
Definition at line 587 of file missionserver.c.
    {
        // Note: At this point, identity can be already deleted
        if (!player)
        {
            Print("[Logout]: Skipping player " + uid + ", already removed");
            return;
        }
        // disable reconnecting to old char
        //GetGame().RemoveFromReconnectCache(uid);
        // now player can't cancel logout anymore, so call everything needed upon disconnect
        InvokeOnDisconnect(player);
        Print("[Logout]: Player " + uid + " finished");
        if (GetHive())
        {
            // save player
            player.Save();
            // unlock player in DB
            GetHive().CharacterExit(player);
        }
        // handle player's existing char in the world
        player.ReleaseNetworkControls();
        HandleBody(player);
        // remove player from server
        GetGame().DisconnectPlayer(identity, uid);
        // Send list of players at all clients
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(SyncEvents.SendPlayerList, 1000);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), Hive::CharacterExit(), CGame::DisconnectPlayer(), CGame::GetCallQueue(), GetGame(), GetHive(), HandleBody(), InvokeOnDisconnect(), Print(), and SyncEvents::SendPlayerList().
Referenced by OnClientDisconnectedEvent(), and UpdateLogoutPlayers().
PlayMusic()
void MissionBase::PlayMusic () inline private
Definition at line 163 of file missionmainmenu.c.
    {
        if ( !m_MenuMusic )
        {
            SoundParams soundParams         = new SoundParams( "Music_Menu_SoundSet" );
            SoundObjectBuilder soundBuilder = new SoundObjectBuilder( soundParams );
            SoundObject soundObject         = soundBuilder.BuildSoundObject();
            soundObject.SetKind( WaveKind.WAVEMUSIC );
            m_MenuMusic = GetGame().GetSoundScene().Play2D(soundObject, soundBuilder);
            m_MenuMusic.Loop( true );
            m_MenuMusic.Play();
        }
    }
References SoundObjectBuilder::BuildSoundObject(), GetGame(), CGame::GetSoundScene(), AbstractWave::Loop(), AbstractWave::Play(), and SoundObject().
Referenced by OnMissionStart().
ProcessLoginData()
bool MissionBase::ProcessLoginData (ParamsReadContext ctx) inline private
returns whether received data is valid, ctx can be filled on client in StoreLoginData()
Definition at line 429 of file missionserver.c.
    {
        //creates temporary server-side structure for handling default character spawn
        return GetGame().GetMenuDefaultCharacterData(false).DeserializeCharacterData(ctx);
    }
References MenuDefaultCharacterData::DeserializeCharacterData(), GetGame(), and CGame::GetMenuDefaultCharacterData().
Referenced by OnClientNewEvent().
RandomArtillery()
void MissionBase::RandomArtillery (float deltaTime) inline private
Definition at line 114 of file missionserver.c.
    {
        // ARTY barrage
        if ( m_PlayArty )
        {
            // We only perform timer checks and increments if we enabled the artillery barrage
            if ( m_ArtyBarrageTimer > m_ArtyDelay )
            {
                //We clamp to guarantee 1 and never have multiple shots on same pos, even in case of entry error
                m_MaxSimultaneousStrikes = Math.Clamp( m_MaxSimultaneousStrikes, 1, m_FiringPos.Count() );
                m_MinSimultaneousStrikes = Math.Clamp( m_MinSimultaneousStrikes, 1, m_MaxSimultaneousStrikes );
                // Variables to be used in this scope
                int randPos; // Select random position
                Param1<vector> pos; // The value to be sent through RPC
                array<ref Param> params; // The RPC params
                if ( m_MaxSimultaneousStrikes == 1 )
                {
                    // We only have one set of coordinates to send
                    randPos = Math.RandomIntInclusive( 0, m_FiringPos.Count() - 1 );
                    pos = new Param1<vector>( m_FiringPos[randPos] );
                    params = new array<ref Param>;
                    params.Insert( pos );
                    GetGame().RPC( null, ERPCs.RPC_SOUND_ARTILLERY, params, true);
                }
                else
                {
                    //We will do some extra steps to
                    /*
                    1. Send multiple coords ( Send one RPC per coord set )
                    2. Ensure we don't have duplicates
                    */
                    array<int> usedIndices = new array<int>; // Will store all previusly fired upon indices
                    // We determine how many positions fire between MIN and MAX
                    int randFireNb = Math.RandomIntInclusive( m_MinSimultaneousStrikes, m_MaxSimultaneousStrikes );
                    for ( int i = 0; i < randFireNb; i++ )
                    {
                        randPos = Math.RandomIntInclusive( 0, m_FiringPos.Count() - 1 );
                        if ( usedIndices.Count() <= 0 || usedIndices.Find( randPos ) < 0 ) //We do not find the index or array is empty
{
                            // We prepare to send the message
                            pos = new Param1<vector>( m_FiringPos[randPos] );
                            params = new array<ref Param>;
                            // We send the message with this set of coords
                            params.Insert( pos );
                            GetGame().RPC( null, ERPCs.RPC_SOUND_ARTILLERY, params, true);
                            // We store the last used value
                            usedIndices.Insert(randPos);
                        }
                    }
                }
                // Reset timer for new loop
                m_ArtyBarrageTimer = 0.0;
            }
            m_ArtyBarrageTimer += deltaTime;
        }
    }
References Math::Clamp(), GetGame(), Math::RandomIntInclusive(), and CGame::RPC().
Referenced by OnUpdate().
RefreshCrosshairVisibility()
override void MissionBase::RefreshCrosshairVisibility () inline private
Definition at line 1165 of file missiongameplay.c.
    {
        if (GetHudDebug())
        GetHudDebug().RefreshCrosshairVisibility();
    }
References GetHudDebug().
RefreshExcludes()
override void MissionBase::RefreshExcludes () inline private
refreshes any active excludes
Definition at line 965 of file missiongameplay.c.
    {
        if (m_ActiveInputExcludeGroups)
        {
            for (int i = 0; i < m_ActiveInputExcludeGroups.Count(); i++)
            {
                GetUApi().ActivateExclude(m_ActiveInputExcludeGroups[i]);
            }
        }
        GetUApi().UpdateControls();
    }
References UAInputAPI::ActivateExclude(), GetUApi(), and UAInputAPI::UpdateControls().
Referenced by AddActiveInputExcludes(), OnUpdate(), and RemoveActiveInputExcludes().
RemoveActiveInputExcludes()
override void MissionBase::RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress = false) inline private
Removes one or more exclude groups and refreshes excludes.
Definition at line 833 of file missiongameplay.c.
    {
        super.RemoveActiveInputExcludes(excludes,bForceSupress);
        if (excludes.Count() != 0)
        {
            bool changed = false;
            if (!m_ActiveInputExcludeGroups)
            {
                m_ActiveInputExcludeGroups = new array<string>;
            }
            else
            {
                for (int i = 0; i < excludes.Count(); i++)
                {
                    if (m_ActiveInputExcludeGroups.Find(excludes[i]) != -1)
                    {
                        m_ActiveInputExcludeGroups.RemoveItem(excludes[i]);
                        changed = true;
                    }
                }
                //m_ActiveInputExcludeGroups.Sort(); //?
            }
            if (changed)
            {
                RefreshExcludes();
            }
            // supress control for next frame
            GetUApi().SupressNextFrame(bForceSupress);
        }
    }
References GetUApi(), RefreshExcludes(), and UAInputAPI::SupressNextFrame().
Referenced by Continue(), HideChat(), HideInventory(), and PlayerControlEnable().
RemoveActiveInputRestriction()
override void MissionBase::RemoveActiveInputRestriction (int restrictor) inline private
Removes one restriction (specific behaviour oudside regular excludes, defined below)
Definition at line 867 of file missiongameplay.c.
    {
        //unique behaviour outside regular excludes
        if (restrictor > -1)
        {
            switch (restrictor)
            {
                case EInputRestrictors.INVENTORY:
                {
                    GetUApi().GetInputByName("UAWalkRunForced").ForceEnable(false); // force walk off!
                    break;
                }
                case EInputRestrictors.MAP:
                {
                    GetUApi().GetInputByName("UAWalkRunForced").ForceEnable(false); // force walk off!
                    break;
                }
            }
            if (m_ActiveInputRestrictions && m_ActiveInputRestrictions.Find(restrictor) != -1)
            {
                m_ActiveInputRestrictions.RemoveItem(restrictor);
            }
        }
    }
References UAInput::ForceEnable(), UAInputAPI::GetInputByName(), and GetUApi().
Referenced by EnableAllInputs(), HideInventory(), and PlayerControlEnable().
Reset()
override void MissionBase::Reset () inline private
Definition at line 32 of file missionmainmenu.c.
    {
        #ifdef PLATFORM_CONSOLE
            delete m_IntroSceneXbox;
        #else
            delete m_IntroScenePC;
        #endif
        CreateIntroScene();
    }
References CreateIntroScene(), m_IntroScenePC, and m_IntroSceneXbox.
ResetGUI()
override void MissionBase::ResetGUI () inline private
Definition at line 1119 of file missiongameplay.c.
    {
        DestroyInventory();
        InitInventory();
    }
References DestroyInventory(), and InitInventory().
SendMuteListToServer()
void MissionBase::SendMuteListToServer (map< string, bool > mute_list) inline private
Definition at line 195 of file missiongameplay.c.
    {
        if( mute_list && mute_list.Count() > 0 )
        {
            ScriptRPC rpc = new ScriptRPC();
            rpc.Write(mute_list);
            rpc.Send(null, ERPCs.RPC_USER_SYNC_PERMISSIONS, true, null);
        }
    }
References ScriptRPC::Send(), and Serializer::Write().
SetActionDownTime()
void MissionBase::SetActionDownTime (int time_down) inline private
Definition at line 1357 of file missiongameplay.c.
    {
        m_ActionDownTime = time_down;
    }
SetActionUpTime()
void MissionBase::SetActionUpTime (int time_up) inline private
Definition at line 1362 of file missiongameplay.c.
    {
        m_ActionUpTime = time_up;
    }
SetNoteMenu()
override void MissionBase::SetNoteMenu (UIScriptedMenu menu) inline private
Definition at line 1517 of file missiongameplay.c.
    {
        m_Note = NoteMenu.Cast(menu);
    };
SetPlayerRespawning()
override void MissionBase::SetPlayerRespawning (bool state) inline private
Definition at line 1542 of file missiongameplay.c.
    {
        m_PlayerRespawning = state;
    }
SetRespawnModeClient()
override void MissionBase::SetRespawnModeClient (int mode) inline private
Definition at line 1557 of file missiongameplay.c.
    {
        m_RespawnModeClient = mode;
    }
SetVoNActive()
override void MissionBase::SetVoNActive (bool active) inline private
Definition at line 1498 of file missiongameplay.c.
    {
        m_VoNActive = active;
    }
ShowChat()
override void MissionBase::ShowChat () inline private
Definition at line 1125 of file missiongameplay.c.
    {
        m_ChatChannelHideTimer.Stop();
        m_ChatChannelFadeTimer.Stop();
        m_ChatChannelArea.Show(false);
        m_UIManager.EnterScriptedMenu(MENU_CHAT_INPUT, NULL);
        int level = GetGame().GetVoiceLevel();
        UpdateVoiceLevelWidgets(level);
        AddActiveInputExcludes({"menu"});
    }
References AddActiveInputExcludes(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetVoiceLevel(), MENU_CHAT_INPUT, and UpdateVoiceLevelWidgets().
Referenced by OnUpdate().
ShowHairDebugValues()
void MissionBase::ShowHairDebugValues (bool state) inline private
Definition at line 1397 of file missiongameplay.c.
    {
#ifdef DEVELOPER
        if( state )
        {
            PluginDiagMenu diagmenu = PluginDiagMenu.Cast(GetPlugin(PluginDiagMenu));
            int i                   = DiagMenu.GetValue(DiagMenuIDs.DM_HAIR_LEVEL);
            bool bState             = diagmenu.m_HairHidingStateMap.Get(i);
            string selectionState;
            if (!bState)
                selectionState      = "Hidden";
            else
                selectionState      = "Shown";
            string selectionName    = diagmenu.m_HairSelectionArray.Get(i);
            DbgUI.BeginCleanupScope();
            DbgUI.Begin("Hair Debug", 50, 150);
            DbgUI.Text("Current Hair Selection:" + selectionName);
            DbgUI.Text("State: " + selectionState);
            DbgUI.End();
            DbgUI.EndCleanupScope();
        }
        else
        {
            DbgUI.BeginCleanupScope();
            DbgUI.Begin("Hair Debug", 50, 50);
            DbgUI.End();
            DbgUI.EndCleanupScope();
        }
#endif
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), string::Get(), GetPlugin(), DiagMenu::GetValue(), and DbgUI::Text().
Referenced by DisplayHairDebug().
ShowInventory()
override void MissionBase::ShowInventory () inline private
Definition at line 1073 of file missiongameplay.c.
    {
        UIScriptedMenu menu = GetUIManager().GetMenu();
        if ( !menu && GetGame().GetPlayer().GetHumanInventory().CanOpenInventory() && !GetGame().GetPlayer().IsInventorySoftLocked() && GetGame().GetPlayer().GetHumanInventory().IsInventoryUnlocked() )
        {
            if( !m_InventoryMenu )
            {
                InitInventory();
            }
            if( !GetUIManager().FindMenu( MENU_INVENTORY ) )
            {
                GetUIManager().ShowScriptedMenu(m_InventoryMenu, null);
                PlayerBase.Cast(GetGame().GetPlayer()).OnInventoryMenuOpen();
            }
            AddActiveInputExcludes({"inventory"});
            AddActiveInputRestriction(EInputRestrictors.INVENTORY);
        }
    }
References AddActiveInputExcludes(), AddActiveInputRestriction(), GetGame(), UIManager::GetMenu(), GetPlayer(), GetUIManager(), InitInventory(), IsInventoryUnlocked(), MENU_INVENTORY, and UIManager::ShowScriptedMenu().
Referenced by OnUpdate().
ShowVehicleInfo()
void MissionBase::ShowVehicleInfo () inline private
Definition at line 1143 of file missiongameplay.c.
    {
        if( GetHud() )
            GetHud().ShowVehicleInfo();
    }
References GetHud(), and Hud::ShowVehicleInfo().
SortedInsert()
int MissionBase::SortedInsert (array< int > list, int number) inline private
Definition at line 188 of file missionmainmenu.c.
    {
        int find_number = number;
        int index_min = 0;
        int index_max = list.Count() - 1;
        int target_index = Math.Floor( index_max / 2 );
        if ( index_max == -1 )
        {
            list.Insert( number );
            return 0;
        }
        while ( true )
        {
            int target_value = list[target_index];
            if ( find_number == target_value || ((index_max - index_min) <= 1) )
            {
                for ( int i = index_min; i <= index_max; i++ )
                {
                    if ( find_number <= list[i] )
                    {
                        list.InsertAt( find_number, i );
                        return i;
                    }
                }
                index_max++;
                list.InsertAt( find_number, index_max );
                return target_index;
            }
            else if ( find_number < target_value )
            {
                index_max = target_index;
                target_index = Math.Floor( target_index / 2 );
            }
            else if ( find_number > target_value )
            {
                index_min = target_index;
                target_index += Math.Floor( (index_max - index_min) / 2 );
            }
        }
        return target_index;
    }
References Math::Floor().
StartingEquipSetup()
void MissionBase::StartingEquipSetup (PlayerBase player, bool clothesChosen) inline private
can be overriden to manually set up starting equip. 'clothesChosen' is legacy parameter, does nothing.
Definition at line 477 of file missionserver.c.
    {
    }
Referenced by EquipCharacter().
StartLogoutMenu()
override void MissionBase::StartLogoutMenu (int time) inline private
Definition at line 1272 of file missiongameplay.c.
    {
        if (m_Logout)
        {
            if (time > 0)
            {
                // character will be deleted from server int "time" seconds
                m_Logout.SetTime(time);
                m_Logout.Show();
                GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(m_Logout.UpdateTime, 1000, true);
            }
            else
            {
                // no waiting time -> player is most likely dead
                m_Logout.Exit();
            }
        }
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
StopMusic()
void MissionBase::StopMusic () inline private
Definition at line 177 of file missionmainmenu.c.
    {
        if ( m_MenuMusic )
            m_MenuMusic.Stop();
    }
References AbstractWave::Stop().
SyncGlobalLighting()
void MissionBase::SyncGlobalLighting (PlayerBase player) inline private
Definition at line 418 of file missionserver.c.
    {
        if ( player )
        {
            int lightingID = GetGame().ServerConfigGetInt( "lightingConfig" );
            Param1<int> lightID = new Param1<int>( lightingID );
            GetGame().RPCSingleParam( player, ERPCs.RPC_SEND_LIGHTING_SETUP, lightID, true, player.GetIdentity() );
        }
    }
References GetGame(), CGame::RPCSingleParam(), and CGame::ServerConfigGetInt().
Referenced by OnEvent().
SyncRespawnModeInfo()
override void MissionBase::SyncRespawnModeInfo (PlayerIdentity identity) inline private
Definition at line 698 of file missionserver.c.
    {
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(m_RespawnMode);
        rpc.Send(null, ERPCs.RPC_SERVER_RESPAWN_MODE, true, identity);
    }
References ScriptRPC::Send(), and Serializer::Write().
TickScheduler() [1/2]
void MissionBase::TickScheduler (float timeslice) inline private
Definition at line 187 of file missiongameplay.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( player )
            player.OnScheduledTick(timeslice);
    }
References GetGame(), and GetPlayer().
Referenced by OnUpdate().
TickScheduler() [2/2]
void MissionBase::TickScheduler (float timeslice) inline private
Definition at line 637 of file missionserver.c.
    {
        GetGame().GetWorld().GetPlayerList(m_Players);
        int players_count = m_Players.Count();
        int tick_count_max = Math.Min(players_count, SCHEDULER_PLAYERS_PER_TICK);
        for(int i = 0; i < tick_count_max; i++)
        {
            if(m_currentPlayer >= players_count )
            {
                m_currentPlayer = 0;
            }
            PlayerBase currentPlayer = PlayerBase.Cast(m_Players.Get(m_currentPlayer));
            if(currentPlayer)
                currentPlayer.OnTick();
            m_currentPlayer++;
        }
    }
References GetGame(), World::GetPlayerList(), CGame::GetWorld(), and Math::Min().
UpdateCorpseStatesServer()
void MissionBase::UpdateCorpseStatesServer () inline private
Definition at line 665 of file missionserver.c.
    {
        if (m_DeadPlayersArray.Count() == 0)//nothing to process, abort
            return;
        int current_time = GetGame().GetTime();
        array<int> invalid_corpses = new array<int>;
        CorpseData corpse_data;
        for (int i = 0; i < m_DeadPlayersArray.Count(); i++)
        {
            corpse_data = m_DeadPlayersArray.Get(i);
            if( !corpse_data || (corpse_data && (!corpse_data.m_Player || !corpse_data.m_bUpdate)) )
            {
                invalid_corpses.Insert(i);
            }
            else if( corpse_data.m_bUpdate && current_time - corpse_data.m_iLastUpdateTime >= 30000 )
            {
                corpse_data.UpdateCorpseState();
                corpse_data.m_iLastUpdateTime = current_time;
            }
        }
        //cleanup
        if (invalid_corpses.Count() > 0)
        {
            for (i = invalid_corpses.Count() - 1; i > -1; i--)
            {
                m_DeadPlayersArray.Remove(invalid_corpses.Get(i));
            }
        }
    }
References GetGame(), CGame::GetTime(), CorpseData::m_bUpdate, CorpseData::m_iLastUpdateTime, CorpseData::m_Player, and CorpseData::UpdateCorpseState().
Referenced by UpdatePlayersStats().
UpdateDebugMonitor()
void MissionBase::UpdateDebugMonitor () inline private
Definition at line 1339 of file missiongameplay.c.
    {
        if (!m_DebugMonitor) return;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if (player)
        {
            DebugMonitorValues values = player.GetDebugMonitorValues();
            if (values)
            {
                m_DebugMonitor.SetHealth(values.GetHealth());
                m_DebugMonitor.SetBlood(values.GetBlood());
                m_DebugMonitor.SetLastDamage(values.GetLastDamage());
                m_DebugMonitor.SetPosition(MiscGameplayFunctions.TruncateVec(player.GetPosition(),1));
            }
        }
    }
References DebugMonitorValues::GetBlood(), GetGame(), DebugMonitorValues::GetHealth(), DebugMonitorValues::GetLastDamage(), and GetPlayer().
Referenced by OnUpdate().
UpdateLogoutPlayers()
void MissionBase::UpdateLogoutPlayers () inline private
Definition at line 220 of file missionserver.c.
    {
        for ( int i = 0; i < m_LogoutPlayers.Count(); )
        {
            LogoutInfo info = m_LogoutPlayers.GetElement(i);
            if (GetGame().GetTime() >= info.param1)
            {
                PlayerIdentity identity;
                PlayerBase player = m_LogoutPlayers.GetKey(i);
                if (player)
                {
                    identity = player.GetIdentity();
                    m_LogoutPlayers.Remove(player);
                }
                else
                {
                    m_LogoutPlayers.RemoveElement(i);
                }
                // disable reconnecting to old char
                // GetGame().RemoveFromReconnectCache(info.param2);
                PlayerDisconnected(player, identity, info.param2);
            }
            else
            {
                ++i;
            }
        }
    }
References GetGame(), GetTime(), and PlayerDisconnected().
Referenced by OnUpdate().
UpdatePlayersStats()
void MissionBase::UpdatePlayersStats () inline private
Definition at line 189 of file missionserver.c.
    {
        PluginLifespan module_lifespan;
        Class.CastTo(module_lifespan, GetPlugin( PluginLifespan ));
        array<Man> players = new array<Man>;
        GetGame().GetPlayers( players );
        for ( int i = 0; i < players.Count(); i++ )
        {
            PlayerBase player;
            Class.CastTo(player, players.Get(i));
            if( player )
            {
                // NEW STATS API
                player.StatUpdateByTime("playtime");
                player.StatUpdateByPosition("dist");
                module_lifespan.UpdateLifespan( player );
            }
        }
        UpdateCorpseStatesServer();
    }
References Class::CastTo(), GetGame(), CGame::GetPlayers(), GetPlugin(), PluginLifespan(), and UpdateCorpseStatesServer().
Referenced by MissionServer().
UpdateVoiceLevelWidgets()
override void MissionBase::UpdateVoiceLevelWidgets (int level) inline private
Definition at line 1431 of file missiongameplay.c.
    {
        for( int n = 0; n < m_VoiceLevelsWidgets.Count(); n++ )
        {
            int voiceKey = m_VoiceLevelsWidgets.GetKey(n);
            ImageWidget voiceWidget = m_VoiceLevelsWidgets.Get(n);
            // stop fade timer since it will be refreshed
            WidgetFadeTimer timer = m_VoiceLevelTimers.Get(n);
            timer.Stop();
            // show widgets according to the level
            if( voiceKey <= level )
            {
                voiceWidget.SetAlpha(1.0); // reset from possible previous fade out
                voiceWidget.Show(true);
                if( !m_VoNActive && !GetUIManager().FindMenu(MENU_CHAT_INPUT) )
                    timer.FadeOut(voiceWidget, 3.0);
            }
            else
                voiceWidget.Show(false);
        }
        // fade out microphone icon when switching levels without von on
        if( !m_VoNActive )
        {
            if( !GetUIManager().FindMenu(MENU_CHAT_INPUT) )
            {
                m_MicrophoneIcon.SetAlpha(1.0);
                m_MicrophoneIcon.Show(true);
                m_MicFadeTimer.FadeOut(m_MicrophoneIcon, 3.0);
            }
        }
        else
        {
            // stop mic icon fade timer when von is activated
            m_MicFadeTimer.Stop();
        }
    }
References GetUIManager(), and MENU_CHAT_INPUT.
Referenced by ShowChat().
VerifyAttachmentType()
bool MissionBase::VerifyAttachmentType (int slot_ID, string attachment_type) inline private
Definition at line 481 of file missionserver.c.
    {
        return DefaultCharacterCreationMethods.GetConfigAttachmentTypes(slot_ID).Find(attachment_type) > -1;
    }
Member Data Documentation
CHERNARUS_STRIKE_POS
protected const ref array<vector> MissionBase::CHERNARUS_STRIKE_POS private
Initial value:
=
    {
        "-500.00 165.00 5231.69",
        "-500.00 300.00 9934.41",
        "10406.86 192.00 15860.00",
        "4811.75 370.00 15860.00",
        "-500.00 453.00 15860.00"
    }
Definition at line 28 of file missionserver.c.
HOLD_LIMIT_TIME
protected const int MissionBase::HOLD_LIMIT_TIME = 300 private
Definition at line 30 of file missiongameplay.c.
LIVONIA_STRIKE_POS
protected const ref array<vector> MissionBase::LIVONIA_STRIKE_POS private
Initial value:
=
    {
        "7440.00 417.00 -500.00",
        "-500.00 276.00 5473.00",
        "-500.00 265.00 9852.00",
        "4953.00 240.00 13300.00",
        "9620.00 188.00 13300.00",
        "13300.00 204.00 10322.00",
        "13300.00 288.00 6204.00",
        "13300.00 296.00 -500.00"
    }
Definition at line 38 of file missionserver.c.
m_ActionDownTime
protected int MissionBase::m_ActionDownTime private
Definition at line 31 of file missiongameplay.c.
Referenced by LocalPressTime().
m_ActionMenu
ref ActionMenu MissionBase::m_ActionMenu private
Definition at line 13 of file missiongameplay.c.
m_ActionUpTime
protected int MissionBase::m_ActionUpTime private
Definition at line 32 of file missiongameplay.c.
Referenced by LocalReleaseTime().
m_ActiveInputExcludeGroups
protected ref array<string> MissionBase::m_ActiveInputExcludeGroups private
Definition at line 36 of file missiongameplay.c.
m_ActiveInputRestrictions
protected ref array<int> MissionBase::m_ActiveInputRestrictions private
Definition at line 37 of file missiongameplay.c.
m_ArtyBarrageTimer
private float MissionBase::m_ArtyBarrageTimer = 0 private
Definition at line 18 of file missionserver.c.
m_ArtyDelay
protected float MissionBase::m_ArtyDelay = 0 private
Definition at line 22 of file missionserver.c.
m_Chat
ref Chat MissionBase::m_Chat private
Definition at line 12 of file missiongameplay.c.
m_ChatChannelArea
Widget MissionBase::m_ChatChannelArea private
Definition at line 25 of file missiongameplay.c.
m_ChatChannelFadeTimer
ref WidgetFadeTimer MissionBase::m_ChatChannelFadeTimer private
Definition at line 22 of file missiongameplay.c.
m_ChatChannelHideTimer
ref Timer MissionBase::m_ChatChannelHideTimer private
Definition at line 21 of file missiongameplay.c.
m_ChatChannelText
TextWidget MissionBase::m_ChatChannelText private
Definition at line 26 of file missiongameplay.c.
m_ControlDisabled
protected bool MissionBase::m_ControlDisabled private
Definition at line 34 of file missiongameplay.c.
m_ControlDisabledMode
protected int MissionBase::m_ControlDisabledMode private
Definition at line 35 of file missiongameplay.c.
Referenced by GetControlDisabledMode().
m_CreditsMenu
private CreditsMenu MissionBase::m_CreditsMenu private
Definition at line 4 of file missionmainmenu.c.
m_currentPlayer
int MissionBase::m_currentPlayer private
Definition at line 12 of file missionserver.c.
m_DeadPlayersArray
ref array<ref CorpseData> MissionBase::m_DeadPlayersArray private
Definition at line 8 of file missionserver.c.
m_DebugMonitor
ref DebugMonitor MissionBase::m_DebugMonitor private
Definition at line 17 of file missiongameplay.c.
m_EffectWidgets
protected ref GameplayEffectWidgets MissionBase::m_EffectWidgets private
Definition at line 19 of file missiongameplay.c.
Referenced by GetEffectWidgets().
m_FiringPos
protected ref array<vector> MissionBase::m_FiringPos private
Definition at line 25 of file missionserver.c.
m_Hud
ref IngameHud MissionBase::m_Hud private
Definition at line 14 of file missiongameplay.c.
Referenced by GetHud().
m_HudDebug
ref HudDebug MissionBase::m_HudDebug private
Definition at line 15 of file missiongameplay.c.
Referenced by GetHudDebug().
m_HudRootWidget
Widget MissionBase::m_HudRootWidget private
Definition at line 8 of file missiongameplay.c.
Referenced by OnMissionFinish().
m_Initialized
bool MissionBase::m_Initialized private
Definition at line 4 of file missiongameplay.c.
m_InitOnce
protected bool MissionBase::m_InitOnce private
Definition at line 33 of file missiongameplay.c.
m_IntroScenePC
private ref DayZIntroScenePC MissionBase::m_IntroScenePC private
Definition at line 5 of file missionmainmenu.c.
Referenced by GetIntroScenePC(), and Reset().
m_IntroSceneXbox
private ref DayZIntroSceneXbox MissionBase::m_IntroSceneXbox private
Definition at line 6 of file missionmainmenu.c.
Referenced by GetIntroSceneXbox(), and Reset().
m_InventoryMenu
ref InventoryMenu MissionBase::m_InventoryMenu private
Definition at line 11 of file missiongameplay.c.
Referenced by GetInventory(), and OnUpdate().
m_LifeState
int MissionBase::m_LifeState private
Definition at line 3 of file missiongameplay.c.
m_Logout
ref LogoutMenu MissionBase::m_Logout private
Definition at line 16 of file missiongameplay.c.
m_LogoutPlayers
ref map<PlayerBase, ref LogoutInfo> MissionBase::m_LogoutPlayers private
Definition at line 9 of file missionserver.c.
m_mainmenu
private UIScriptedMenu MissionBase::m_mainmenu private
Definition at line 3 of file missionmainmenu.c.
m_MaxSimultaneousStrikes
protected int MissionBase::m_MaxSimultaneousStrikes = 0 private
Definition at line 24 of file missionserver.c.
m_MenuMusic
private AbstractWave MissionBase::m_MenuMusic private
Definition at line 7 of file missionmainmenu.c.
Referenced by GetMenuMusic().
m_MicFadeTimer
ref WidgetFadeTimer MissionBase::m_MicFadeTimer private
Definition at line 23 of file missiongameplay.c.
Referenced by GetMicWidgetFadeTimer().
m_MicrophoneIcon
ImageWidget MissionBase::m_MicrophoneIcon private
Definition at line 9 of file missiongameplay.c.
Referenced by GetMicrophoneIcon().
m_MinSimultaneousStrikes
protected int MissionBase::m_MinSimultaneousStrikes = 0 private
Definition at line 23 of file missionserver.c.
m_mission
MissionBase MissionBase::m_mission private
Definition at line 54 of file missionserver.c.
m_moduleDefaultCharacter
PluginAdditionalInfo MissionBase::m_moduleDefaultCharacter private
Definition at line 55 of file missionserver.c.
m_NewLogoutPlayers
ref map<PlayerBase, ref LogoutInfo> MissionBase::m_NewLogoutPlayers private
Definition at line 10 of file missionserver.c.
m_NoCutscene
bool MissionBase::m_NoCutscene private
Definition at line 8 of file missionmainmenu.c.
m_Note
NoteMenu MissionBase::m_Note private
Definition at line 27 of file missiongameplay.c.
Referenced by GetNoteMenu().
m_PauseQueued
protected bool MissionBase::m_PauseQueued private
Definition at line 41 of file missiongameplay.c.
m_PlayArty
protected bool MissionBase::m_PlayArty = false private
Definition at line 21 of file missionserver.c.
m_player
PlayerBase MissionBase::m_player private
Definition at line 53 of file missionserver.c.
Referenced by CreateCharacter(), and OnClientNewEvent().
m_PlayerRespawning
protected bool MissionBase::m_PlayerRespawning private
Definition at line 39 of file missiongameplay.c.
Referenced by IsPlayerRespawning().
m_Players
ref array<Man> MissionBase::m_Players private
Definition at line 7 of file missionserver.c.
m_QuickbarHold
protected bool MissionBase::m_QuickbarHold private
Definition at line 38 of file missiongameplay.c.
m_RespawnMode
int MissionBase::m_RespawnMode private
Definition at line 13 of file missionserver.c.
m_RespawnModeClient
protected int MissionBase::m_RespawnModeClient private
Definition at line 40 of file missiongameplay.c.
Referenced by GetRespawnModeClient().
m_ToggleHudTimer
protected ref Timer MissionBase::m_ToggleHudTimer private
Definition at line 29 of file missiongameplay.c.
m_UIManager
protected UIManager MissionBase::m_UIManager private
Definition at line 6 of file missiongameplay.c.
Referenced by GetUIManager().
m_VoiceLevels
protected Widget MissionBase::m_VoiceLevels private
Definition at line 45 of file missiongameplay.c.
m_VoiceLevelsWidgets
protected ref map<int,ImageWidget> MissionBase::m_VoiceLevelsWidgets private
Definition at line 46 of file missiongameplay.c.
Referenced by GetVoiceLevelWidgets().
m_VoiceLevelTimers
protected ref map<int,ref WidgetFadeTimer> MissionBase::m_VoiceLevelTimers private
Definition at line 47 of file missiongameplay.c.
Referenced by GetVoiceLevelTimers().
m_VoNActive
protected bool MissionBase::m_VoNActive private
Definition at line 44 of file missiongameplay.c.
Referenced by IsVoNActive().
SCHEDULER_PLAYERS_PER_TICK
const int MissionBase::SCHEDULER_PLAYERS_PER_TICK = 5 private
Definition at line 11 of file missionserver.c.