DayzKode: Weapon Class Reference
Weapon Class Reference
script counterpart to engine's class Weapon
Private Member Functions
override void AfterStoreLoad ()
void AssembleGun ()
override on weapons with some assembly required
bool CanChamberBullet (int muzzleIndex, Magazine mag)
bool CanEjectBullet ()
bool CanProcessAction (int action, int actionType)
bool CanProcessWeaponEvents ()
void EEFired (int muzzleType, int mode, string ammoType)
override void EEInit ()
void ForceSyncSelectionState ()
AbilityRecord GetAbility (int index)
int GetAbilityCount ()
float GetChanceToJam ()
int GetCurrentStableStateID ()
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
WeaponStateBase GetCurrentState ()
returns currently active state
int GetInternalStateID ()
protected array< MuzzleState > GetMuzzleStates ()
Helper method for RandomizeFSMState.
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
float GetSyncChanceToJam ()
int GetWeaponAnimState ()
bool HasActionAbility (int action, int actionType)
query if weapon supports action and actionType
void HideBullet (int muzzleIndex)
void InitStateMachine ()
bool IsIdle ()
bool IsJammed ()
bool IsWaitingForActionFinish ()
returns true if state machine started playing action/actionType and waits for finish
bool JamCheck (int muzzleIndex)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
bool ProcessWeaponAbortEvent (WeaponEventBase e)
bool ProcessWeaponEvent (WeaponEventBase e)
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
void RandomizeFSMState ()
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
void ResetWeaponAnimState ()
void SaveCurrentFSMState (ParamsWriteContext ctx)
void SetJammed (bool value)
void SetWeaponAnimState (int state)
void ShowBullet (int muzzleIndex)
void SyncSelectionState (bool has_bullet, bool has_mag)
void Weapon_Base ()
Private Attributes
protected const float DEFAULT_DAMAGE_ON_SHOT = 0.05
protected PhxInteractionLayers hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI
protected ref array< ref AbilityRecord > m_abilities = new array<ref AbilityRecord>
protected bool m_BayonetAttached
protected int m_BayonetAttachmentIdx
ref array< int > m_bulletSelectionIndex = new array<int>
protected int m_BurstCount
protected bool m_ButtstockAttached
protected int m_ButtstockAttachmentIdx
ref array< float > m_ChanceToJam = new array<float>
protected float m_ChanceToJamSync = 0
protected float m_DmgPerShot = 0
ref array< float > m_DOFProperties
protected ref WeaponFSM m_fsm
weapon abilities
protected bool m_isJammed = false
weapon state machine
protected bool m_LiftWeapon = false
protected int m_magazineSimpleSelectionIndex = -1
animation state the weapon is in, -1 == uninitialized
protected ref PropertyModifiers m_PropertyModifierObject
protected int m_weaponAnimState = -1
protected int m_weaponHideBarrelIdx = -1
protected float m_WeaponLength
const int SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG
Full highest capacity magazine + chambered round.
const int SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG
Random bullet quantity + maybe chambered round.
Weapon With Ammo
Helpers for spawning ammo/magazine in weapon For the flags, either a combination of WeaponWithAmmoFlags can be used Or one of the preset 'const int' with 'SAMF_' prefix (SAMF_DEFAULT, SAMF_RNG)
bool SpawnAmmo (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
General method trying to attch magazine, fill inner magazine and fill chamber.
Magazine SpawnAttachedMagazine (string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to spawn and attach a magazine.
bool FillInnerMagazine (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the inner magazine.
bool FillChamber (string ammoType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Try to fill the chamber.
override int GetSlotsCountCorrect ()
Returns number of slots for attachments corrected for weapons.
PropertyModifiers GetPropertyModifierObject ()
void OnFire (int muzzle_index)
void OnFireModeChange (int fireMode)
void ValidateAndRepair ()
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override void EEItemAttached (EntityAI item, string slot_name)
override void EEItemDetached (EntityAI item, string slot_name)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override bool CanReleaseAttachment (EntityAI attachment)
override bool CanRemoveFromHands (EntityAI parent)
bool IsRemoteWeapon ()
void SyncEventToRemote (WeaponEventBase e)
RecoilBase SpawnRecoilObject ()
int GetWeaponSpecificCommand (int weaponAction, int subCommand)
bool CanFire ()
bool CanEnterIronsights ()
bool InitDOFProperties (out array< float > temp_array)
Initializes DOF properties for weapon's ironsight/optics cameras.
bool InitReliability (out array< float > reliability_array)
bool InitWeaponLength ()
gets weapon length from config for weaponlift raycast
ref array< float > GetWeaponDOF ()
bool LiftWeaponCheck (PlayerBase player)
void SetSyncJammingChance (float jamming_chance)
bool EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName)
unload bullet from chamber or internal magazine
bool CopyWeaponStateFrom (notnull Weapon_Base src)
override void SetBayonetAttached (bool pState, int slot_idx=-1)
attachment helpers (firearm melee)
override bool HasBayonetAttached ()
override int GetBayonetAttachmentIdx ()
override void SetButtstockAttached (bool pState, int slot_idx=-1)
override bool HasButtstockAttached ()
override int GetButtstockAttachmentIdx ()
void HideWeaponBarrel (bool state)
void ShowMagazine ()
void HideMagazine ()
override EntityAI ProcessMeleeItemDamage (int mode=0)
bool IsShowingChamberedBullet ()
int GetBurstCount ()
void ResetBurstCount ()
override void SetActions ()
override void OnDebugSpawn ()
static Weapon_Base CreateWeaponWithAmmo (string weaponType, string magazineType="", int flags=WeaponWithAmmoFlags.CHAMBER)
Create weapon with ammo.
Detailed Description
script counterpart to engine's class Weapon
Definition at line 48 of file inventoryitem.c.
Member Function Documentation
AfterStoreLoad()
override void Weapon::AfterStoreLoad () inline private
Definition at line 465 of file weapon_base.c.
    {
        if (m_fsm)
        {
            int mi = GetCurrentMuzzle();
            Magazine mag = GetMagazine(mi);
            bool has_mag = mag != null;
            bool has_bullet = !IsChamberEmpty(mi);
            SyncSelectionState(has_bullet, has_mag);
        }
    }
AssembleGun()
void Weapon::AssembleGun () private
override on weapons with some assembly required
CanChamberBullet()
bool Weapon::CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 213 of file weapon_base.c.
    {
        return CanChamberFromMag(muzzleIndex, mag) && (!IsChamberFull(muzzleIndex) || IsChamberFiredOut(muzzleIndex) || !IsInternalMagazineFull(muzzleIndex));
    }
References IsChamberFiredOut(), and IsChamberFull().
CanEjectBullet()
bool Weapon::CanEjectBullet () inline private
Definition at line 296 of file weapon_base.c.
{return true;}
CanEnterIronsights()
bool Weapon::CanEnterIronsights () inline private
Definition at line 1065 of file weapon_base.c.
    {
        ItemOptics optic = GetAttachedOptics();
        if ( !optic )
            return true;
        return optic.HasWeaponIronsightsOverride();
    }
CanFire()
bool Weapon::CanFire () inline private
Definition at line 1058 of file weapon_base.c.
    {
        if (!IsChamberEmpty(GetCurrentMuzzle()) && !IsChamberFiredOut(GetCurrentMuzzle()) && !IsJammed() && !m_LiftWeapon)
            return true;
        return false;
    }
References IsChamberFiredOut(), and IsJammed().
CanProcessAction()
bool Weapon::CanProcessAction (int action, int actionType) inline private
Definition at line 125 of file weapon_base.c.
    {
        return false; // @TODO
    }
CanProcessWeaponEvents()
Weapon::CanProcessWeaponEvents () inline private
Returns
true if weapon has running fsm
Definition at line 159 of file weapon_base.c.
{ return m_fsm && m_fsm.IsRunning(); }
CanReleaseAttachment()
override bool Weapon::CanReleaseAttachment (EntityAI attachment) inline private
Definition at line 970 of file weapon_base.c.
    {
        if ( !super.CanReleaseAttachment( attachment ) )
            return false;
        Magazine mag = Magazine.Cast(attachment);
        if (mag)
        {
            PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
            if ( player )
            {
                if ( player.GetItemInHands() == this )
                    return true;
            }
            return false;
        }
        return true;
    }
CanRemoveFromHands()
override bool Weapon::CanRemoveFromHands (EntityAI parent) inline private
Definition at line 1009 of file weapon_base.c.
    {
        if (IsIdle())
        {
            return true;
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " not in stable state=" + GetCurrentState().Type()); }
        return false; // do not allow removal of weapon while weapon is busy
    }
References IsIdle(), LogManager::IsWeaponLogEnable(), Type, and wpnDebugPrint().
CopyWeaponStateFrom()
bool Weapon::CopyWeaponStateFrom (notnull Weapon_Base src) inline private
Definition at line 1221 of file weapon_base.c.
    {
        float damage = 0.0;
        string type;
        for (int mi = 0; mi < src.GetMuzzleCount(); ++mi)
        {
            if (!src.IsChamberEmpty(mi))
            {
                if (src.GetCartridgeInfo(mi, damage, type))
                {
                    PushCartridgeToChamber(mi, damage, type);
                }
            }
            for (int ci = 0; ci < src.GetInternalMagazineCartridgeCount(mi); ++ci)
            {
                if (src.GetInternalMagazineCartridgeInfo(mi, ci, damage, type))
                {
                    PushCartridgeToInternalMagazine(mi, damage, type);
                }
            }
        }
        int dummy_version = int.MAX;
        PlayerBase parentPlayer = PlayerBase.Cast(src.GetHierarchyRootPlayer());
        if (!parentPlayer)
            dummy_version -= 1;
        ScriptReadWriteContext ctx = new ScriptReadWriteContext;
        src.OnStoreSave(ctx.GetWriteContext());
        OnStoreLoad(ctx.GetReadContext(), dummy_version);
        return true;
    }
References ScriptReadWriteContext::GetReadContext(), ScriptReadWriteContext::GetWriteContext(), and OnStoreLoad().
CreateWeaponWithAmmo()
Weapon::CreateWeaponWithAmmo (string weaponType, string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline static private
Create weapon with ammo.
Parameters
[in] weaponType string The weapon to create
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created weapon
Definition at line 581 of file weapon_base.c.
    {
        Weapon_Base wpn = Weapon_Base.Cast(GetGame().CreateObjectEx( weaponType, vector.Zero, ECE_PLACE_ON_SURFACE ));
        if ( !wpn )
        {
            ErrorEx(string.Format("%1 does not exist or is not a weapon.", weaponType));
            return null;
        }
        wpn.SpawnAmmo(magazineType, flags);
        return wpn;
    }
References ECE_PLACE_ON_SURFACE, ErrorEx, GetGame(), and vector::Zero.
EEFired()
void Weapon::EEFired (int muzzleType, int mode, string ammoType) inline private
Definition at line 229 of file weapon_base.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            ItemBase suppressor = GetAttachedSuppressor();
            // Muzzle flash & overheating effects
            ItemBase.PlayFireParticles(this, muzzleType, ammoType, this, suppressor, "CfgWeapons" );
            IncreaseOverheating(this, ammoType, this, suppressor, "CfgWeapons");
            if (suppressor)
            {
                ItemBase.PlayFireParticles(this, muzzleType, ammoType, suppressor, NULL, "CfgVehicles" );
                suppressor.IncreaseOverheating(this, ammoType, this, suppressor, "CfgVehicles");
            }
        }
        //obsolete, replaced by C++ solution!
/*
        if (GetGame().IsServer())
        {
            AddHealth("","Health",-m_DmgPerShot); //damages weapon
            if (suppressor)
                suppressor.AddHealth("","Health",-m_DmgPerShot); //damages suppressor; TODO add suppressor damage coeficient/parameter (?) to suppressors/weapons (?)
        }
*/
        //JamCheck(muzzleType);
        #ifdef DEVELOPER
        MiscGameplayFunctions.UnlimitedAmmoDebugCheck(this);
        #endif
    }
References GetGame(), and IncreaseOverheating().
EEInit()
override void Weapon::EEInit () inline private
Definition at line 115 of file weapon_base.c.
    {
        super.EEInit();
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Call( AssembleGun );
    }
References Weapon_Base::AssembleGun(), ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), and GetGame().
EEItemAttached()
override void Weapon::EEItemAttached (EntityAI item, string slot_name) inline private
Definition at line 901 of file weapon_base.c.
    {
        super.EEItemAttached(item, slot_name);
        GetPropertyModifierObject().UpdateModifiers();
        /*if (ItemOptics.Cast(item))
        {
            PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
            if( player )
            {
                if( player.GetItemInHands() == this )
                {
                    player.SetOpticsPreload(true,item);
                }
            }
        }*/
    }
EEItemDetached()
override void Weapon::EEItemDetached (EntityAI item, string slot_name) inline private
Definition at line 920 of file weapon_base.c.
    {
        super.EEItemDetached(item, slot_name);
        GetPropertyModifierObject().UpdateModifiers();
        /*if (ItemOptics.Cast(item))
        {
            PlayerBase player = PlayerBase.Cast( GetHierarchyRootPlayer() );
            if( player )
            {
                if( player.GetItemInHands() == this )
                {
                    player.SetOpticsPreload(false,item);
                }
            }
        }*/
    }
EEItemLocationChanged()
override void Weapon::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 939 of file weapon_base.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (newLoc.GetType() == InventoryLocationType.HANDS)
        {
            PlayerBase player;
            if (newLoc.GetParent() && PlayerBase.CastTo(player, newLoc.GetParent()))
            {
                HumanCommandMove cm = player.GetCommand_Move();
                if (cm)
                {
                    cm.SetMeleeBlock(false);
                }
            }
        }
    }
References HumanCommandMove::SetMeleeBlock().
EjectCartridge()
Weapon::EjectCartridge (int muzzleIndex, out float ammoDamage, out string ammoTypeName) inline private
unload bullet from chamber or internal magazine
@NOTE: EjectCartridge = GetCartridgeInfo + PopCartridge
Parameters
[in] muzzleIndex
[out] ammoDamage damage of the ammo
[out] ammoTypeName type name of the ejected ammo
Returns
true if bullet removed from chamber
Definition at line 1206 of file weapon_base.c.
    {
        if (IsChamberEjectable(muzzleIndex))
        {
            if (PopCartridgeFromChamber(muzzleIndex, ammoDamage, ammoTypeName))
                return true;
        }
        else if (GetInternalMagazineCartridgeCount(muzzleIndex) > 0)
        {
            if (PopCartridgeFromInternalMagazine(muzzleIndex, ammoDamage, ammoTypeName))
                return true;
        }
        return false;
    }
FillChamber()
Weapon::FillChamber (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to fill the chamber.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any chamber was filled
Definition at line 750 of file weapon_base.c.
    {
        // Quickly check if there are any chambers we can fill
        int muzzCount = GetMuzzleCount();
        bool anyEmpty = false;
        for (int m = 0; m < muzzCount; ++m)
        {
            if (IsChamberEmpty(m))
            {
                anyEmpty = true;
                break;
            }
        }
        if (!anyEmpty)
            return false;
        // Make sure the given ammoType is actually useable
        if (ammoType != "")
            if (!AmmoTypesAPI.MagazineTypeToAmmoType(ammoType, ammoType))
                return false;
        // Just so we don't '&' wastefully in a loop
        bool didSomething = false;
        bool chamberFullRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG_SPORADIC);
        bool chamberRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
        bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER);
        if (chamber || chamberRng || chamberFullRng)
        {
            int amountToChamber = muzzCount;
            // No need to do this for full rng, as that will roll for every muzzle
            if (chamberRng)
                amountToChamber = Math.RandomIntInclusive(0, muzzCount);
            bool chamberAmmoRng = (ammoType == "");
            bool chamberAmmoFullRng = chamberAmmoRng && (flags & WeaponWithAmmoFlags.AMMO_CHAMBER_RNG);
            // No full RNG flag, so pick one random and use only this one
            if (chamberAmmoRng && !chamberAmmoFullRng)
                ammoType = GetRandomChamberableAmmoTypeName(0);
            for (int i = 0; i < muzzCount; ++i)
            {
                // Skip when there's already something in the chamber
                if (!IsChamberEmpty(i))
                    continue;
                // Roll the rng when enabled
                if (chamberFullRng)
                    chamber = Math.RandomIntInclusive(0, 1);
                // We chambering
                if (chamber)
                {
                    // Full random, decide a new one for every muzzle
                    if ( chamberAmmoFullRng )
                        ammoType = GetRandomChamberableAmmoTypeName(i);
                    // Push it
                    PushCartridgeToChamber(i, 0, ammoType);
                    didSomething = true;
                    // Stop chambering when we hit the desired amount
                    --amountToChamber;
                    if (amountToChamber <= 0)
                        break;
                }
            }
        }
        // Only fix the FSM and Synchronize when absolutely needed
        if (!didSomething)
            return false;
        // FSM cares about chamber state
        RandomizeFSMState();
        Synchronize();
        return true;
    }
References AmmoTypesAPI::MagazineTypeToAmmoType(), Math::RandomIntInclusive(), and Synchronize().
FillInnerMagazine()
Weapon::FillInnerMagazine (string ammoType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to fill the inner magazine.
Parameters
[in] ammoType string The ammo to load, passing in empty string will select random
Note
It is best to fill in the actual 'ammo', as in the ones usually prefixed by 'Bullet_', to skip searching for it
Parameters
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
Whether any ammo was added to the gun or not
Definition at line 682 of file weapon_base.c.
    {
        // Don't try to fill it when there are none
        if (!HasInternalMagazine(-1))
            return false;
        // Make sure the given ammoType is actually useable
        if (ammoType != "")
        {
            if (!AmmoTypesAPI.MagazineTypeToAmmoType(ammoType, ammoType))
                return false;
        }
        bool didSomething = false;
        int muzzCount = GetMuzzleCount();
        bool ammoRng = ammoType == "";
        bool ammoFullRng = ammoRng && (flags & WeaponWithAmmoFlags.AMMO_MAG_RNG);
        // No full RNG flag, so pick one random and use only this one
        if (ammoRng && !ammoFullRng)
            ammoType = GetRandomChamberableAmmoTypeName(0);
        // Fill the internal magazine
        for (int i = 0; i < muzzCount; ++i)
        {
            int ammoCount = GetInternalMagazineMaxCartridgeCount(i);
            // Decide random quantity when enabled
            if ( flags & WeaponWithAmmoFlags.QUANTITY_RNG )
                ammoCount = Math.RandomIntInclusive(0, ammoCount);
            // Only do the things when there is actually ammo to fill
            if (ammoCount > 0)
            {
                // Push in the cartridges
                for (int j = 0; j < ammoCount; ++j)
                {
                    // Full random, decide a new one for every cartridge
                    if ( ammoFullRng )
                        ammoType = GetRandomChamberableAmmoTypeName(i);
                    PushCartridgeToInternalMagazine(i, 0, ammoType);
                    didSomething = true;
                }
            }
        }
        // Call the chamber method if asked for
        bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER) || (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
        if (chamber && FillChamber(ammoType, flags))
        {
            didSomething = true;
        }
        // Does not need any FSM fixing, FSM does not care about inner magazines
        return didSomething;
    }
References AmmoTypesAPI::MagazineTypeToAmmoType(), and Math::RandomIntInclusive().
ForceSyncSelectionState()
void Weapon::ForceSyncSelectionState () inline private
Definition at line 322 of file weapon_base.c.
    {
        int nMuzzles = GetMuzzleCount();
        for (int i = 0; i < nMuzzles; ++i)
        {
            if (IsChamberFull(i))
            {
                ShowBullet(i);
                float damage;
                string ammoTypeName;
                GetCartridgeInfo(i, damage, ammoTypeName);
                EffectBulletShow(i, damage, ammoTypeName);
            }
            else
            {
                HideBullet(i);
                EffectBulletHide(i);
            }
            Magazine mag = GetMagazine(i);
            if (mag)
                ShowMagazine();
            else
                HideMagazine();
        }
    }
References Weapon_Base::HideBullet(), IsChamberFull(), and Weapon_Base::ShowBullet().
GetAbility()
Weapon::GetAbility (int index) inline private
Parameters
[in] index index into m_abilities storage
Returns
ability record
Definition at line 154 of file weapon_base.c.
{ return m_abilities.Get(index); }
GetAbilityCount()
Weapon::GetAbilityCount () inline private
Returns
number of stored abilities
Definition at line 149 of file weapon_base.c.
{ return m_abilities.Count(); }
GetBayonetAttachmentIdx()
override int Weapon::GetBayonetAttachmentIdx () inline private
Definition at line 1267 of file weapon_base.c.
    {
        return m_BayonetAttachmentIdx;
    }
GetBurstCount()
int Weapon::GetBurstCount () inline private
Definition at line 1353 of file weapon_base.c.
    {
        return m_BurstCount;
    }
GetButtstockAttachmentIdx()
override int Weapon::GetButtstockAttachmentIdx () inline private
Definition at line 1283 of file weapon_base.c.
    {
        return m_ButtstockAttachmentIdx;
    }
GetChanceToJam()
float Weapon::GetChanceToJam () inline private
Definition at line 299 of file weapon_base.c.
    {
        int level = GetHealthLevel();
        if (level >= 0 && level < m_ChanceToJam.Count())
            return m_ChanceToJam[level];
        else
            return 0.0;
    }
References GetHealthLevel().
GetCurrentStableStateID()
Weapon::GetCurrentStableStateID () inline private
tries to return identifier of current stable state (or nearest stable state if unstable state is currently running)
Definition at line 515 of file weapon_base.c.
    {
        if (m_fsm)
        {
            return m_fsm.GetCurrentStableStateID();
        }
        return 0;
    }
GetCurrentState()
Weapon::GetCurrentState () inline private
returns currently active state
Returns
current state the FSM is in (or NULL)
Definition at line 165 of file weapon_base.c.
{ return m_fsm.GetCurrentState(); }
GetInternalStateID()
int Weapon::GetInternalStateID () inline private
Definition at line 505 of file weapon_base.c.
    {
        if (m_fsm)
            return m_fsm.GetInternalStateID();
        return 0;
    }
GetMuzzleStates()
protected array< MuzzleState > Weapon::GetMuzzleStates () inline private
Helper method for RandomizeFSMState.
Definition at line 544 of file weapon_base.c.
    {
        array<MuzzleState> muzzleStates = new array<MuzzleState>;
        int nMuzzles = GetMuzzleCount();
        for (int i = 0; i < nMuzzles; ++i)
        {
            MuzzleState state = MuzzleState.U;
            if (IsChamberFiredOut(i))
                state = MuzzleState.F;
            else if (IsChamberFull(i))
                state = MuzzleState.L;
            else if (IsChamberEmpty(i))
                state = MuzzleState.E;
            else
                ErrorEx(string.Format("Unable to identify chamber state of muzzle %1", i));
            muzzleStates.Insert(state);
        }
        return muzzleStates;
    }
References ErrorEx, IsChamberFiredOut(), and IsChamberFull().
GetPropertyModifierObject()
PropertyModifiers Weapon::GetPropertyModifierObject () inline private
Definition at line 849 of file weapon_base.c.
    {
        if (!m_PropertyModifierObject)
        {
            m_PropertyModifierObject = new PropertyModifiers(this);
        }
        return m_PropertyModifierObject;
    }
GetSlotsCountCorrect() [1/2]
override int Weapon::GetSlotsCountCorrect () inline private
Returns number of slots for attachments corrected for weapons.
Definition at line 841 of file weapon_base.c.
    {
        int ac = GetInventory().AttachmentCount();
        int sc = GetInventory().GetAttachmentSlotsCount() + GetMuzzleCount();
        if (ac > sc) sc = ac; // fix of some weapons which has 1 attachments but 0 slots...
        return sc;
    };
GetSlotsCountCorrect() [2/2]
override int Weapon::GetSlotsCountCorrect () inline private
Returns number of slots for attachments corrected for weapons.
Definition at line 6 of file binocularsbase.c.
    {
        return GetInventory().GetAttachmentSlotsCount();
    };
GetSyncChanceToJam()
float Weapon::GetSyncChanceToJam () inline private
Definition at line 298 of file weapon_base.c.
{ return m_ChanceToJamSync; }
GetWeaponAnimState()
int Weapon::GetWeaponAnimState () inline private
Definition at line 227 of file weapon_base.c.
{ return m_weaponAnimState; }
GetWeaponDOF()
ref array< float > Weapon::GetWeaponDOF () inline private
Definition at line 1107 of file weapon_base.c.
    {
        return m_DOFProperties;
    }
GetWeaponSpecificCommand()
int Weapon::GetWeaponSpecificCommand (int weaponAction, int subCommand) inline private
Definition at line 1056 of file weapon_base.c.
{ return subCommand; }
HasActionAbility()
Weapon::HasActionAbility (int action, int actionType) inline private
query if weapon supports action and actionType
Parameters
[in] action one of Human.actions (i.e. RELOAD, MECHANISM, ...)
[in] actionType one of Human.actionTypes (i.e. CHAMBERING_ONEBULLET_CLOSED, MECHANISM_CLOSED...)
Returns
true if weapon supports operation
Definition at line 135 of file weapon_base.c.
    {
        int count = GetAbilityCount();
        for (int i = 0; i < count; ++i)
        {
            AbilityRecord rec = GetAbility(i);
            if (rec.m_action == action && rec.m_actionType == actionType)
                return true;
        }
        return false;
    }
References AbilityRecord::m_action, and AbilityRecord::m_actionType.
HasBayonetAttached()
override bool Weapon::HasBayonetAttached () inline private
Definition at line 1262 of file weapon_base.c.
    {
        return m_BayonetAttached;
    }
HasButtstockAttached()
override bool Weapon::HasButtstockAttached () inline private
Definition at line 1278 of file weapon_base.c.
    {
        return m_ButtstockAttached;
    }
HideBullet()
void Weapon::HideBullet (int muzzleIndex) inline private
Definition at line 285 of file weapon_base.c.
    {
        if ( m_bulletSelectionIndex.Count() > muzzleIndex )
        {
            SetSimpleHiddenSelectionState(m_bulletSelectionIndex[muzzleIndex],0);
        }
        else
            SelectionBulletHide();
    }
HideMagazine()
void Weapon::HideMagazine () inline private
Definition at line 1308 of file weapon_base.c.
    {
        if (m_magazineSimpleSelectionIndex > -1)
            SetSimpleHiddenSelectionState(m_magazineSimpleSelectionIndex,0);
        else
            SelectionMagazineHide();
    }
HideWeaponBarrel()
void Weapon::HideWeaponBarrel (bool state) inline private
Definition at line 1288 of file weapon_base.c.
    {
        if ( !GetGame().IsDedicatedServer() )//hidden for client only
        {
            ItemOptics optics = GetAttachedOptics();
            if ( optics && !optics.AllowsDOF() && m_weaponHideBarrelIdx != -1 )
            {
                SetSimpleHiddenSelectionState(m_weaponHideBarrelIdx,!state);
            }
        }
    }
References GetGame().
InitDOFProperties()
bool Weapon::InitDOFProperties (out array< float > temp_array) inline private
Initializes DOF properties for weapon's ironsight/optics cameras.
Definition at line 1075 of file weapon_base.c.
    {
        if (GetGame().ConfigIsExisting("cfgWeapons " + GetType() + " PPDOFProperties"))
        {
            GetGame().ConfigGetFloatArray("cfgWeapons " + GetType() + " PPDOFProperties", temp_array);
            return true;
        }
        return false;
    }
References CGame::ConfigGetFloatArray(), ConfigIsExisting(), GetGame(), and GetType().
InitReliability()
bool Weapon::InitReliability (out array< float > reliability_array) inline private
Definition at line 1085 of file weapon_base.c.
    {
        if (GetGame().ConfigIsExisting("cfgWeapons " + GetType() + " Reliability ChanceToJam"))
        {
            GetGame().ConfigGetFloatArray("cfgWeapons " + GetType() + " Reliability ChanceToJam", reliability_array);
            return true;
        }
        return false;
    }
References CGame::ConfigGetFloatArray(), ConfigIsExisting(), GetGame(), and GetType().
InitStateMachine()
void Weapon::InitStateMachine () inline private
Definition at line 113 of file weapon_base.c.
{ }
InitWeaponLength()
bool Weapon::InitWeaponLength () inline private
gets weapon length from config for weaponlift raycast
Definition at line 1096 of file weapon_base.c.
    {
        if (ConfigIsExisting("WeaponLength"))
        {
            m_WeaponLength = ConfigGetFloat("WeaponLength");
            return true;
        }
        m_WeaponLength = 0.8; //default value if not set in config; should not be zero
        return false;
    }
References ConfigGetFloat(), and ConfigIsExisting().
IsIdle()
bool Weapon::IsIdle () inline private
Definition at line 175 of file weapon_base.c.
    {
        return CanProcessWeaponEvents() && GetCurrentState().IsIdle();
    }
IsJammed()
bool Weapon::IsJammed () inline private
Definition at line 295 of file weapon_base.c.
{ return m_isJammed; }
IsRemoteWeapon()
bool Weapon::IsRemoteWeapon () inline private
Definition at line 1019 of file weapon_base.c.
    {
        InventoryLocation il = new InventoryLocation;
        if (GetInventory().GetCurrentInventoryLocation(il))
        {
            EntityAI parent = il.GetParent();
            DayZPlayer dayzp = DayZPlayer.Cast(parent);
            if (il.GetType() == InventoryLocationType.HANDS && dayzp)
            {
                bool remote = dayzp.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_REMOTE;
                return remote;
            }
        }
        return true;
    }
References GetCurrentInventoryLocation(), InventoryLocation::GetParent(), and InventoryLocation::GetType().
IsShowingChamberedBullet()
bool Weapon::IsShowingChamberedBullet () inline private
Definition at line 1348 of file weapon_base.c.
    {
        return true;
    }
IsWaitingForActionFinish()
Weapon::IsWaitingForActionFinish () inline private
returns true if state machine started playing action/actionType and waits for finish
Definition at line 170 of file weapon_base.c.
    {
        return CanProcessWeaponEvents() && GetCurrentState().IsWaitingForActionFinish();
    }
JamCheck()
bool Weapon::JamCheck (int muzzleIndex) inline private
Definition at line 262 of file weapon_base.c.
    {
        PlayerBase player = PlayerBase.Cast(GetHierarchyRootPlayer());
        if ( player )
        {
            float rnd = player.GetRandomGeneratorSyncManager().GetRandom01(RandomGeneratorSyncUsage.RGSJam);
            //Print("Random Jam - " + rnd);
            if (rnd < GetSyncChanceToJam())
                return true;
        }
        return false;
    }
LiftWeaponCheck()
bool Weapon::LiftWeaponCheck (PlayerBase player) inline private
snippet below measures distance from "RightHandIndex1" bone for lifting calibration
Definition at line 1113 of file weapon_base.c.
    {
        int idx;
        float distance;
        float hit_fraction; //junk
        vector start, end;
        vector direction;
        vector usti_hlavne_position;
        vector trigger_axis_position;
        vector hit_pos, hit_normal; //junk
        Object obj;
        ItemBase attachment;
        m_LiftWeapon = false;
        // not a gun, no weap.raise for now
        if ( HasSelection("Usti hlavne") )
            return false;
        if (!player)
        {
            Print("Error: No weapon owner, returning");
            return false;
        }
        // weapon not raised
        if ( player.GetInputController() && !player.GetInputController().IsWeaponRaised() )
            return false;
        usti_hlavne_position = GetSelectionPositionLS( "Usti hlavne" );     // Usti hlavne
        trigger_axis_position = GetSelectionPositionLS("trigger_axis");
        // freelook raycast
        if (player.GetInputController().CameraIsFreeLook())
        {
            if (player.m_DirectionToCursor != vector.Zero)
            {
                direction = player.m_DirectionToCursor;
            }
            // if player raises weapon in freelook
            else
            {
                direction = MiscGameplayFunctions.GetHeadingVector(player);
            }
        }
        else
        {
            direction = GetGame().GetCurrentCameraDirection(); // exception for freelook. Much better this way!
        }
        idx = player.GetBoneIndexByName("Neck"); //RightHandIndex1
        if ( idx == -1 )
            { start = player.GetPosition()[1] + 1.5; }
        else
            { start = player.GetBonePositionWS(idx); }
        /*usti_hlavne_position = ModelToWorld(usti_hlavne_position);
        distance = vector.Distance(start,usti_hlavne_position);*/
        distance = m_WeaponLength;// - 0.05; //adjusted raycast length
        // if weapon has battel attachment, does longer cast
        if (ItemBase.CastTo(attachment,FindAttachmentBySlotName("weaponBayonet")) || ItemBase.CastTo(attachment,FindAttachmentBySlotName("weaponBayonetAK")) || ItemBase.CastTo(attachment,FindAttachmentBySlotName("weaponBayonetMosin")) || ItemBase.CastTo(attachment,FindAttachmentBySlotName("weaponBayonetSKS")) || ItemBase.CastTo(attachment,GetAttachedSuppressor()))
        {
            distance += attachment.m_ItemModelLength;
        }
        end = start + (direction * distance);
        DayZPhysics.RayCastBullet(start, end, hit_mask, player, obj, hit_pos, hit_normal, hit_fraction);
        // something is hit
        if (hit_pos != vector.Zero)
        {
            //Print(distance);
            m_LiftWeapon = true;
            return true;
        }
        return false;
    }
References CGame::GetCurrentCameraDirection(), GetGame(), GetSelectionPositionLS(), HasSelection(), Print(), DayZPhysics::RayCastBullet(), and vector::Zero.
LoadCurrentFSMState()
bool Weapon::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 432 of file weapon_base.c.
    {
        if (m_fsm)
        {
            if (m_fsm.LoadCurrentFSMState(ctx, version))
            {
                WeaponStableState state = WeaponStableState.Cast(GetCurrentState());
                if (state)
                {
                    SyncSelectionState(state.HasBullet(), state.HasMagazine());
                    state.SyncAnimState();
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " stable state loaded and synced."); }
                    return true;
                }
                else
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " unstable/error state loaded."); }
                    return false;
                }
            }
            else
            {
                Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " did not load.");
                return false;
            }
        }
        else
        {
            Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon.LoadCurrentFSMState: trying to load weapon without FSM (or uninitialized weapon) this=" + this + " type=" + GetType());
            return false;
        }
    }
References Error(), GetType(), WeaponStableState::HasBullet(), WeaponStableState::HasMagazine(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
OnDebugSpawn()
override void Weapon::OnDebugSpawn () inline private
Definition at line 1378 of file weapon_base.c.
    {
        SpawnAmmo("", SAMF_DEFAULT);
    }
OnFire()
void Weapon::OnFire (int muzzle_index) inline private
Definition at line 858 of file weapon_base.c.
    {
        m_BurstCount++;
    }
OnFireModeChange()
void Weapon::OnFireModeChange (int fireMode) inline private
Definition at line 863 of file weapon_base.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            EffectSound eff;
            if ( fireMode == 0 )
                eff = SEffectManager.PlaySound("Fire_Mode_Switch_Marked_Click_SoundSet", GetPosition());
            else
                eff = SEffectManager.PlaySound("Fire_Mode_Switch_Simple_Click_SoundSet", GetPosition());
            eff.SetAutodestroy(true);
        }
        ResetBurstCount();
    }
References GetGame(), GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
OnInventoryEnter()
override void Weapon::OnInventoryEnter (Man player) inline private
Definition at line 886 of file weapon_base.c.
    {
        m_PropertyModifierObject = null;
        ValidateAndRepair();
        super.OnInventoryEnter(player);
    }
OnInventoryExit()
override void Weapon::OnInventoryExit (Man player) inline private
Definition at line 895 of file weapon_base.c.
    {
        m_PropertyModifierObject = null;
        super.OnInventoryExit(player);
    }
OnItemLocationChanged()
override void Weapon::OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner) inline private
Definition at line 957 of file weapon_base.c.
    {
        super.OnItemLocationChanged(old_owner,new_owner);
        // HACK "resets" optics memory on optics
        PlayerBase player;
        if ( PlayerBase.CastTo(player,old_owner) )
        {
            player.SetReturnToOptics(false);
        }
        HideWeaponBarrel(false);
    }
OnStoreLoad()
override bool Weapon::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 349 of file weapon_base.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        if (version >= 113)
        {
            int current_muzzle = 0;
            if (!ctx.Read(current_muzzle))
            {
                Error("Weapon.OnStoreLoad " + this + " cannot read current muzzle!");
                return false;
            }
            if (current_muzzle >= GetMuzzleCount() || current_muzzle < 0)
                Error("Weapon.OnStoreLoad " + this + " trying to set muzzle index " + current_muzzle + " while it only has " + GetMuzzleCount() + " muzzles!");
            else
                SetCurrentMuzzle(current_muzzle);
        }
        if (version >= 105)
        {
            int mode_count = 0;
            if (!ctx.Read(mode_count))
            {
                Error("Weapon.OnStoreLoad " + this + " cannot read mode count!");
                return false;
            }
            for (int m = 0; m < mode_count; ++m)
            {
                int mode = 0;
                if (!ctx.Read(mode))
                {
                    Error("Weapon.OnStoreLoad " + this + " cannot read mode[" + m + "]");
                    return false;
                }
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " OnStoreLoad - loaded muzzle[" + m + "].mode = " + mode); }
                SetCurrentMode(m, mode);
            }
        }
        if ( version >= 106 )
        {
            if ( !ctx.Read(m_isJammed) )
            {
                Error("Weapon.OnStoreLoad cannot load jamming state");
                return false;
            }
        }
        if (m_fsm)
        {
            if (!m_fsm.OnStoreLoad(ctx, version))
                return false;
        }
        else
        {
            int dummy = 0;
            if (!ctx.Read(dummy))
                return false;
        }
        return true;
    }
References Error(), LogManager::IsWeaponLogEnable(), Serializer::Read(), and wpnDebugPrint().
OnStoreSave()
override void Weapon::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 477 of file weapon_base.c.
    {
        super.OnStoreSave(ctx);
        // current muzzle added in version 113
        int current_muzzle = GetCurrentMuzzle();
        ctx.Write(current_muzzle);
        // fire mode added in version 105
        int mode_count = GetMuzzleCount();
        ctx.Write(mode_count);
        for (int m = 0; m < mode_count; ++m)
            ctx.Write(GetCurrentMode(m));
        ctx.Write(m_isJammed);
        if (m_fsm)
            m_fsm.OnStoreSave(ctx);
        else
        {
            int dummy = 0;
            ctx.Write(dummy);
        }
    }
References Serializer::Write().
ProcessMeleeItemDamage()
override EntityAI Weapon::ProcessMeleeItemDamage (int mode = 0) inline private
Definition at line 1316 of file weapon_base.c.
    {
        EntityAI attachment;
        switch (mode)
        {
            case 0:
                super.ProcessMeleeItemDamage();
            break;
            case 1:
                attachment = GetInventory().FindAttachment(m_ButtstockAttachmentIdx);
            break;
            case 2:
                attachment = GetInventory().FindAttachment(m_BayonetAttachmentIdx);
            break;
            default:
                super.ProcessMeleeItemDamage();
            break;
        }
        if (attachment)
        {
            attachment.ProcessMeleeItemDamage();
            return attachment;
        }
        return this;
    }
ProcessWeaponAbortEvent()
Weapon::ProcessWeaponAbortEvent (WeaponEventBase e) inline private
@NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 204 of file weapon_base.c.
    {
        SyncEventToRemote(e);
        ProcessEventResult aa;
        m_fsm.ProcessAbortEvent(e, aa);
        return aa == ProcessEventResult.FSM_OK;
    }
ProcessWeaponEvent()
Weapon::ProcessWeaponEvent (WeaponEventBase e) inline private
weapon's fsm handling of events @NOTE: warning: ProcessWeaponEvent can be called only within DayZPlayer::HandleWeapons (or CommandHandler)
Definition at line 184 of file weapon_base.c.
    {
        SyncEventToRemote(e);
        // @NOTE: synchronous events not handled by fsm
        if (e.GetEventID() == WeaponEventID.SET_NEXT_MUZZLE_MODE)
        {
            SetNextMuzzleMode(GetCurrentMuzzle());
            return true;
        }
        if (m_fsm.ProcessEvent(e) == ProcessEventResult.FSM_OK)
            return true;
        //if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("FSM refused to process event (no transition): src=" + GetCurrentState().ToString() + " event=" + e.ToString()); }
        return false;
    }
References WeaponEventBase::GetEventID().
RandomizeFSMState()
Weapon::RandomizeFSMState () inline private
With the parameters given, selects a random suitable state for the FSM of the weapon @WARNING: Weapon_Base.Synchronize call might be needed, if this method is called while clients are connected.
Definition at line 528 of file weapon_base.c.
    {
        if (m_fsm)
        {
            int mi = GetCurrentMuzzle();
            Magazine mag = GetMagazine(mi);
            bool has_mag = mag != null;
            bool has_bullet = !IsChamberEmpty(mi);
            bool has_jam = IsJammed();
            array<MuzzleState> muzzleStates = GetMuzzleStates();
            m_fsm.RandomizeFSMStateEx(muzzleStates, has_mag, has_jam);
            ForceSyncSelectionState();
        }
    }
References IsJammed().
ResetBurstCount()
void Weapon::ResetBurstCount () inline private
Definition at line 1358 of file weapon_base.c.
    {
        m_BurstCount = 0;
    }
ResetWeaponAnimState()
void Weapon::ResetWeaponAnimState () inline private
Definition at line 222 of file weapon_base.c.
    {
        fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(this) + " resetting anim state: " + typename.EnumToString(PistolAnimState, m_weaponAnimState) + " --> " + typename.EnumToString(PistolAnimState, -1));
        m_weaponAnimState = -1;
    }
References fsmDebugSpam().
SaveCurrentFSMState()
void Weapon::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 417 of file weapon_base.c.
    {
        if (m_fsm && m_fsm.IsRunning())
        {
            if (m_fsm.SaveCurrentFSMState(ctx))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " state saved."); }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon=" + this + " state NOT saved.");
        }
        else
            Error("[wpnfsm] " + Object.GetDebugName(this) + " Weapon.SaveCurrentFSMState: trying to save weapon without FSM (or uninitialized weapon) this=" + this + " type=" + GetType());
    }
References Error(), GetType(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
SetActions()
override void Weapon::SetActions () inline private
Definition at line 1363 of file weapon_base.c.
    {
        super.SetActions();
        AddAction(FirearmActionUnjam);
        AddAction(FirearmActionAttachMagazine);
        AddAction(FirearmActionLoadBullet);
        AddAction(FirearmActionMechanicManipulate);
        AddAction(ActionTurnOnWeaponFlashlight);
        AddAction(ActionTurnOffWeaponFlashlight);
        AddAction(FirearmActionAttachMagazineQuick); // Easy reload
        AddAction(FirearmActionLoadBulletQuick); // Easy reload
    }
References AddAction().
SetBayonetAttached()
override void Weapon::SetBayonetAttached (bool pState, int slot_idx = -1) inline private
attachment helpers (firearm melee)
Definition at line 1256 of file weapon_base.c.
    {
        m_BayonetAttached = pState;
        m_BayonetAttachmentIdx = slot_idx;
    }
SetButtstockAttached()
override void Weapon::SetButtstockAttached (bool pState, int slot_idx = -1) inline private
Definition at line 1272 of file weapon_base.c.
    {
        m_ButtstockAttached = pState;
        m_ButtstockAttachmentIdx = slot_idx;
    }
SetJammed()
void Weapon::SetJammed (bool value) inline private
Definition at line 297 of file weapon_base.c.
{ m_isJammed = value; }
SetSyncJammingChance()
void Weapon::SetSyncJammingChance (float jamming_chance) inline private
Definition at line 1191 of file weapon_base.c.
    {
        m_ChanceToJamSync = jamming_chance;
    }
SetWeaponAnimState()
void Weapon::SetWeaponAnimState (int state) inline private
Definition at line 218 of file weapon_base.c.
    {
        m_weaponAnimState = state;
    }
ShowBullet()
void Weapon::ShowBullet (int muzzleIndex) inline private
Definition at line 275 of file weapon_base.c.
    {
        if ( m_bulletSelectionIndex.Count() > muzzleIndex )
        {
            SetSimpleHiddenSelectionState(m_bulletSelectionIndex[muzzleIndex],1);
        }
        else
            SelectionBulletShow();
    }
ShowMagazine()
void Weapon::ShowMagazine () inline private
Definition at line 1300 of file weapon_base.c.
    {
        if (m_magazineSimpleSelectionIndex > -1)
            SetSimpleHiddenSelectionState(m_magazineSimpleSelectionIndex,1);
        else
            SelectionMagazineShow();
    }
SpawnAmmo()
Weapon::SpawnAmmo (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
General method trying to attch magazine, fill inner magazine and fill chamber.
Parameters
[in] magazineType string The magazine to attach or ammo to load, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
whether anything was spawned or done
Definition at line 601 of file weapon_base.c.
    {
        // Attempt internal mag
        if ( HasInternalMagazine(-1) && FillInnerMagazine(magazineType, flags) )
            return true;
        // Attempt mag attachment
        if ( GetMagazineTypeCount(0) > 0 && SpawnAttachedMagazine(magazineType, flags) )
            return true;
        // Attempt chamber
        if ( FillChamber(magazineType, flags) )
            return true;
        return false;
    }
SpawnAttachedMagazine()
Weapon::SpawnAttachedMagazine (string magazineType = "", int flags = WeaponWithAmmoFlags.CHAMBER) inline private
Try to spawn and attach a magazine.
Parameters
[in] magazineType string The magazine to attach, passing in empty string will select random
[in] flags int Setup flags, please read WeaponWithAmmoFlags
Returns
The created magazine or null
Definition at line 624 of file weapon_base.c.
    {
        // Check if the gun has any magazines registered in config
        if ( GetMagazineTypeCount(0) == 0 )
        {
            ErrorEx(string.Format("No 'magazines' config entry for %1.", this));
            return null;
        }
        // Randomize when no specific one is given
        if ( magazineType == "" )
        {
            if ( flags & WeaponWithAmmoFlags.MAX_CAPACITY_MAG)
                magazineType = GetMaxMagazineTypeName(0);
            else
                magazineType = GetRandomMagazineTypeName(0);
        }
        EntityAI magAI = GetInventory().CreateAttachment(magazineType);
        if (!magAI)
        {
            ErrorEx(string.Format("Failed to create and attach %1 to %2", GetDebugName(magAI), this));
            return null;
        }
        Magazine mag;
        if (!CastTo(mag, magAI))
        {
            ErrorEx(string.Format("Expected magazine, created: %1", GetDebugName(magAI)));
            return null;
        }
        // Decide random quantity when enabled
        if (flags & WeaponWithAmmoFlags.QUANTITY_RNG)
            mag.ServerSetAmmoCount(Math.RandomIntInclusive(0, mag.GetAmmoMax()));
        // Fill chamber when flagged
        bool chamberRng = (flags & WeaponWithAmmoFlags.CHAMBER_RNG);
        bool chamber = (flags & WeaponWithAmmoFlags.CHAMBER) || chamberRng;
        if (chamber || chamberRng)
        {
            FillChamber(magazineType, flags);
        }
        // FSM cares about magazine state
        RandomizeFSMState();
        Synchronize();
        return mag;
    }
References ErrorEx, GetDebugName(), Math::RandomIntInclusive(), and Synchronize().
SpawnRecoilObject()
RecoilBase Weapon::SpawnRecoilObject () inline private
Definition at line 1051 of file weapon_base.c.
    {
        return new DefaultRecoil(this);
    }
SyncEventToRemote()
void Weapon::SyncEventToRemote (WeaponEventBase e) inline private
Definition at line 1035 of file weapon_base.c.
    {
        DayZPlayer p = DayZPlayer.Cast(GetHierarchyParent());
        if (p && p.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            ScriptRemoteInputUserData ctx = new ScriptRemoteInputUserData;
            ctx.Write(INPUT_UDT_WEAPON_REMOTE_EVENT);
            e.WriteToContext(ctx);
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(this) + " send 2 remote: sending e=" + e + " id=" + e.GetEventID() + " p=" + e.m_player + "  m=" + e.m_magazine); }
            p.StoreInputForRemotes(ctx);
        }
    }
References WeaponEventBase::GetEventID(), INPUT_UDT_WEAPON_REMOTE_EVENT, LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, WeaponEventBase::m_player, wpnDebugPrint(), Serializer::Write(), and WeaponEventBase::WriteToContext().
SyncSelectionState()
void Weapon::SyncSelectionState (bool has_bullet, bool has_mag) inline private
Definition at line 309 of file weapon_base.c.
    {
        if (has_bullet)
            SelectionBulletShow();
        else
            SelectionBulletHide();
        if (has_mag)
            ShowMagazine();
        else
            HideMagazine();
    }
ValidateAndRepair()
void Weapon::ValidateAndRepair () inline private
Definition at line 880 of file weapon_base.c.
    {
        if ( m_fsm )
            m_fsm.ValidateAndRepair();
    }
Weapon_Base()
void Weapon::Weapon_Base () inline private
Definition at line 67 of file weapon_base.c.
    {
        //m_DmgPerShot      = ConfigGetFloat("damagePerShot");
        m_BayonetAttached   = false;
        m_ButtstockAttached = false;
        m_BayonetAttachmentIdx = -1;
        m_ButtstockAttachmentIdx = -1;
        m_BurstCount = 0;
        m_DOFProperties = new array<float>;
        if ( ConfigIsExisting("simpleHiddenSelections") )
        {
            TStringArray selectionNames = new TStringArray;
            ConfigGetTextArray("simpleHiddenSelections",selectionNames);
            m_weaponHideBarrelIdx = selectionNames.Find("hide_barrel");
            m_magazineSimpleSelectionIndex = selectionNames.Find("magazine");
            int bulletIndex = selectionNames.Find("bullet");
            if ( bulletIndex != -1 )
            {
                m_bulletSelectionIndex.Insert(bulletIndex);
                for (int i = 2; i < 100; i++)
                {
                    bulletIndex = selectionNames.Find(string.Format("bullet%1",i));
                    if (bulletIndex != -1)
                    {
                        m_bulletSelectionIndex.Insert(bulletIndex);
                    }
                    else
                    {
                        break;
                    }
                }
            }
        }
        InitWeaponLength();
        InitDOFProperties(m_DOFProperties);
        if (GetGame().IsServer())
        {
            InitReliability(m_ChanceToJam);
        }
        InitStateMachine();
    }
References ConfigGetTextArray(), ConfigIsExisting(), GetGame(), and Weapon_Base::InitStateMachine().
Member Data Documentation
DEFAULT_DAMAGE_ON_SHOT
protected const float Weapon::DEFAULT_DAMAGE_ON_SHOT = 0.05 private
Definition at line 45 of file weapon_base.c.
hit_mask
protected PhxInteractionLayers Weapon::hit_mask = PhxInteractionLayers.CHARACTER | PhxInteractionLayers.BUILDING | PhxInteractionLayers.DOOR | PhxInteractionLayers.VEHICLE | PhxInteractionLayers.ROADWAY | PhxInteractionLayers.TERRAIN | PhxInteractionLayers.ITEM_SMALL | PhxInteractionLayers.ITEM_LARGE | PhxInteractionLayers.FENCE | PhxInteractionLayers.AI private
Definition at line 65 of file weapon_base.c.
m_abilities
protected ref array<ref AbilityRecord> Weapon::m_abilities = new array<ref AbilityRecord> private
Definition at line 46 of file weapon_base.c.
m_BayonetAttached
protected bool Weapon::m_BayonetAttached private
Definition at line 50 of file weapon_base.c.
m_BayonetAttachmentIdx
protected int Weapon::m_BayonetAttachmentIdx private
Definition at line 53 of file weapon_base.c.
m_bulletSelectionIndex
ref array<int> Weapon::m_bulletSelectionIndex = new array<int> private
Definition at line 60 of file weapon_base.c.
m_BurstCount
protected int Weapon::m_BurstCount private
Definition at line 52 of file weapon_base.c.
m_ButtstockAttached
protected bool Weapon::m_ButtstockAttached private
Definition at line 51 of file weapon_base.c.
m_ButtstockAttachmentIdx
protected int Weapon::m_ButtstockAttachmentIdx private
Definition at line 54 of file weapon_base.c.
m_ChanceToJam
ref array<float> Weapon::m_ChanceToJam = new array<float> private
Definition at line 62 of file weapon_base.c.
m_ChanceToJamSync
protected float Weapon::m_ChanceToJamSync = 0 private
Definition at line 63 of file weapon_base.c.
m_DmgPerShot
protected float Weapon::m_DmgPerShot = 0 private
Definition at line 58 of file weapon_base.c.
m_DOFProperties
ref array<float> Weapon::m_DOFProperties private
Definition at line 61 of file weapon_base.c.
m_fsm
protected ref WeaponFSM Weapon::m_fsm private
weapon abilities
Definition at line 47 of file weapon_base.c.
m_isJammed
protected bool Weapon::m_isJammed = false private
weapon state machine
Definition at line 48 of file weapon_base.c.
m_LiftWeapon
protected bool Weapon::m_LiftWeapon = false private
Definition at line 49 of file weapon_base.c.
m_magazineSimpleSelectionIndex
protected int Weapon::m_magazineSimpleSelectionIndex = -1 private
animation state the weapon is in, -1 == uninitialized
Definition at line 56 of file weapon_base.c.
m_PropertyModifierObject
protected ref PropertyModifiers Weapon::m_PropertyModifierObject private
Definition at line 64 of file weapon_base.c.
m_weaponAnimState
protected int Weapon::m_weaponAnimState = -1 private
Definition at line 55 of file weapon_base.c.
m_weaponHideBarrelIdx
protected int Weapon::m_weaponHideBarrelIdx = -1 private
Definition at line 57 of file weapon_base.c.
m_WeaponLength
protected float Weapon::m_WeaponLength private
Definition at line 59 of file weapon_base.c.
SAMF_DEFAULT
const int Weapon::SAMF_DEFAULT = WeaponWithAmmoFlags.CHAMBER | WeaponWithAmmoFlags.MAX_CAPACITY_MAG private
Full highest capacity magazine + chambered round.
Definition at line 41 of file weapon_base.c.
SAMF_RNG
const int Weapon::SAMF_RNG = WeaponWithAmmoFlags.CHAMBER_RNG | WeaponWithAmmoFlags.QUANTITY_RNG private
Random bullet quantity + maybe chambered round.
Definition at line 43 of file weapon_base.c.