DayzKode: OptionsAccess Class Reference
OptionsAccess Class Reference
Private Member Functions
proto native void Apply ()
Applies the option value if the value has changed and forgets the old value. This function has no effect on internal options, see OptionsAccess::Test.
proto native int GetAccessType ()
AccessType of current option.
proto native int GetControlType ()
Current option controller type. OA_CT_NUMERIC = 0, OA_CT_SWITCH = 1, OA_CT_LIST = 2.
proto native int GetDefaultIndex ()
proto native int GetDefaultIndex ()
proto native int GetIndex ()
proto native int GetIndex ()
proto native int GetItemsCount ()
proto void GetItemText (int index, out string value)
proto void GetItemText (out string value)
proto native int IsChanged ()
If the option value is changed and not applied or reverted. Value can already be set internally if the value was changed immediately.
proto native int NeedRestart ()
If the option value will take effect only after the game is restarted.
proto native void Revert ()
Reverts the option value to old value if the value has changed and wasnt applied. This function has effect on internal options.
proto native int SetChangeImmediately ()
If the value is changed internally immediately upon change.
proto native void SetIndex (int index)
proto native void Switch ()
proto native void Test ()
Sets the option value internaly if the value has changed and wasnt set immediately upon change.
Script Events API
Setting and getting of ScriptEvents
private proto void SetScriptEvents (Managed events)
Set the events.
private proto Managed GetScriptEvents ()
Get the events.
OptionsAccessEvents GetEvents ()
Get the events.
Events
Events called from C++
void OnRevert ()
Detailed Description
Definition at line 1229 of file gameplay.c.
Member Function Documentation
Apply()
proto native void OptionsAccess::Apply () private
Applies the option value if the value has changed and forgets the old value. This function has no effect on internal options, see OptionsAccess::Test.
GetAccessType()
proto native int OptionsAccess::GetAccessType () private
AccessType of current option.
Returns
AccessType
GetControlType()
proto native int OptionsAccess::GetControlType () private
Current option controller type. OA_CT_NUMERIC = 0, OA_CT_SWITCH = 1, OA_CT_LIST = 2.
Returns
ControlType
GetDefaultIndex() [1/2]
proto native int OptionsAccess::GetDefaultIndex () private
GetDefaultIndex() [2/2]
proto native int OptionsAccess::GetDefaultIndex () private
GetEvents()
OptionsAccessEvents OptionsAccess::GetEvents () inline private
Get the events.
Returns
ParticleManagerEvents If there is any events set, this will return them so that additional functionality can be bound to them
Definition at line 1301 of file gameplay.c.
    {
        return OptionsAccessEvents.Cast(GetScriptEvents());
    }
References GetScriptEvents().
Referenced by OnRevert().
GetIndex() [1/2]
proto native int OptionsAccess::GetIndex () private
GetIndex() [2/2]
proto native int OptionsAccess::GetIndex () private
GetItemsCount()
proto native int OptionsAccess::GetItemsCount () private
GetItemText() [1/2]
proto void OptionsAccess::GetItemText (int index, out string value) private
GetItemText() [2/2]
proto void OptionsAccess::GetItemText (out string value) private
GetScriptEvents()
private proto Managed OptionsAccess::GetScriptEvents () private
Get the events.
Returns
Managed If there is any events set, this will return them
Referenced by GetEvents().
IsChanged()
proto native int OptionsAccess::IsChanged () private
If the option value is changed and not applied or reverted. Value can already be set internally if the value was changed immediately.
Returns
1 if the value is changed, 0 othewise
NeedRestart()
proto native int OptionsAccess::NeedRestart () private
If the option value will take effect only after the game is restarted.
Returns
1 if the value is changed, 0 othewise
OnRevert()
void OptionsAccess::OnRevert () inline private
Definition at line 1315 of file gameplay.c.
    {
        GetEvents().Event_OnRevert.Invoke(this);
    }
References OptionsAccessEvents::Event_OnRevert, GetEvents(), and ScriptInvoker::Invoke().
Revert()
proto native void OptionsAccess::Revert () private
Reverts the option value to old value if the value has changed and wasnt applied. This function has effect on internal options.
SetChangeImmediately()
proto native int OptionsAccess::SetChangeImmediately () private
If the value is changed internally immediately upon change.
Returns
1 if the value is changed immediately, 0 othewise
SetIndex()
proto native void OptionsAccess::SetIndex (int index) private
SetScriptEvents()
private proto void OptionsAccess::SetScriptEvents (Managed events) private
Set the events.
Parameters
events Managed The events to set
Switch()
proto native void OptionsAccess::Switch () private
Test()
proto native void OptionsAccess::Test () private
Sets the option value internaly if the value has changed and wasnt set immediately upon change.