DayzKode: Hit_Glass Class Reference
Hit_Glass Class Reference
Private Member Functions
void Hit_Glass ()
Detailed Description
Definition at line 1 of file hit_glass.c.
Constructor & Destructor Documentation
Hit_Glass()
void Hit_Glass::Hit_Glass () inline private
Definition at line 3 of file hit_glass.c.
    {
        SetEnterParticle(ParticleList.IMPACT_GLASS_ENTER);
        SetExitParticle(ParticleList.IMPACT_GLASS_EXIT);
        SetRicochetParticle(ParticleList.IMPACT_GLASS_RICOCHET);
    }
References ParticleList::IMPACT_GLASS_ENTER, ParticleList::IMPACT_GLASS_EXIT, ParticleList::IMPACT_GLASS_RICOCHET, EffBulletImpactBase::SetEnterParticle(), EffBulletImpactBase::SetExitParticle(), and EffBulletImpactBase::SetRicochetParticle().