DayzKode: CrashBase Class Reference
CrashBase Class Reference
Private Member Functions
override void EEDelete (EntityAI parent)
override void EEOnCECreate ()
override string GetSoundSet ()
vector RandomizePosition (vector origin)
void SpawnRandomDeerLater ()
void SpawnRandomDeers ()
void Wreck_Mi8_Crashed ()
void Wreck_SantasSleigh ()
void Wreck_UH1Y ()
Private Attributes
int m_MaxDeersAmount = 4
int m_MaxDeersSpawnRange = 25
int m_MinDeersAmount = 2
int m_MinDeersSpawnRange = 5
XmasSleighLight m_SleighLight
Detailed Description
Definition at line 2 of file wreck_mi8.c.
Member Function Documentation
EEDelete()
override void CrashBase::EEDelete (EntityAI parent) inline private
Definition at line 36 of file wreck_santassleigh.c.
    {
        super.EEDelete(parent);
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( m_SleighLight )
                m_SleighLight.Destroy();
        }
    }
References GetGame().
EEOnCECreate()
override void CrashBase::EEOnCECreate () inline private
Definition at line 30 of file wreck_santassleigh.c.
    {
        super.EEOnCECreate();
        SpawnRandomDeerLater();
    }
References SpawnRandomDeerLater().
GetSoundSet()
override string CrashBase::GetSoundSet () inline private
Definition at line 25 of file wreck_santassleigh.c.
    {
        return "SledgeCrash_Distant_SoundSet";
    }
Referenced by House::EEInit(), and House::RequestSoundEvent().
RandomizePosition()
vector CrashBase::RandomizePosition (vector origin) inline private
Definition at line 72 of file wreck_santassleigh.c.
    {
        int randX;
        int randZ;
        randX = Math.RandomIntInclusive(m_MinDeersSpawnRange, m_MaxDeersSpawnRange);
        if (Math.RandomIntInclusive(0,1) < 1)
            randX = -randX;
        randZ = Math.RandomIntInclusive(m_MinDeersSpawnRange, m_MaxDeersSpawnRange);
        if (Math.RandomIntInclusive(0,1) < 1)
            randZ = -randZ;
        origin[0] = origin[0] + randX;
        origin[2] = origin[2] + randZ;
        return origin;
    }
References Math::RandomIntInclusive().
SpawnRandomDeerLater()
void CrashBase::SpawnRandomDeerLater () inline private
Definition at line 47 of file wreck_santassleigh.c.
    {
        //SpawnRandomDeers();
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( SpawnRandomDeers, 0);
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), and GetGame().
Referenced by EEOnCECreate().
SpawnRandomDeers()
void CrashBase::SpawnRandomDeers () inline private
Definition at line 54 of file wreck_santassleigh.c.
    {
        EntityAI deer;
        vector crash_pos = GetPosition();
        int deersAmount = Math.RandomIntInclusive(m_MinDeersAmount,m_MaxDeersAmount);
        for (int i = 0; i < m_MaxDeersAmount; i++)
        {
            vector deer_pos = RandomizePosition(crash_pos);
            deer = EntityAI.Cast(GetGame().CreateObject("Animal_CervusElaphus", deer_pos,false, true));
            deer.SetHealth01("","", 0);
            vector orientation = deer.GetOrientation();
            deer.SetOrientation(Vector(Math.RandomIntInclusive(0,360),orientation[1],orientation[2]));
        }
    }
References GetGame(), GetPosition, m_MaxDeersAmount, Math::RandomIntInclusive(), RandomizePosition(), and Vector().
Wreck_Mi8_Crashed()
void CrashBase::Wreck_Mi8_Crashed () inline private
Definition at line 4 of file wreck_mi8.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            m_ParticleEfx = ParticleManager.GetInstance().PlayOnObject(ParticleList.SMOKING_HELI_WRECK, this, Vector(2, 0, -5));
        }
    }
References GetGame(), ParticleManager(), ParticleList::SMOKING_HELI_WRECK, and Vector().
Wreck_SantasSleigh()
void CrashBase::Wreck_SantasSleigh () inline private
Definition at line 11 of file wreck_santassleigh.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            //particles - Aurora trail
            m_ParticleEfx = ParticleManager.GetInstance().PlayOnObject(ParticleList.AURORA_SANTA_WRECK, this, Vector(0, 0, 0));
            //lights - green light
            m_SleighLight = XmasSleighLight.Cast( ScriptedLightBase.CreateLight( XmasSleighLight, Vector(0, 0, 0) ) );
            m_SleighLight.AttachOnMemoryPoint( this, "light" );
        }
    }
References ParticleList::AURORA_SANTA_WRECK, GetGame(), ParticleManager(), and Vector().
Wreck_UH1Y()
void CrashBase::Wreck_UH1Y () inline private
Definition at line 3 of file wreck_uh1y.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            m_ParticleEfx = ParticleManager.GetInstance().PlayOnObject(ParticleList.SMOKING_HELI_WRECK, this, Vector(-0.5, 0, -1.0));
        }
    }
References GetGame(), ParticleManager(), ParticleList::SMOKING_HELI_WRECK, and Vector().
Member Data Documentation
m_MaxDeersAmount
int CrashBase::m_MaxDeersAmount = 4 private
Definition at line 6 of file wreck_santassleigh.c.
Referenced by SpawnRandomDeers().
m_MaxDeersSpawnRange
int CrashBase::m_MaxDeersSpawnRange = 25 private
Definition at line 8 of file wreck_santassleigh.c.
m_MinDeersAmount
int CrashBase::m_MinDeersAmount = 2 private
Definition at line 7 of file wreck_santassleigh.c.
m_MinDeersSpawnRange
int CrashBase::m_MinDeersSpawnRange = 5 private
Definition at line 9 of file wreck_santassleigh.c.
m_SleighLight
XmasSleighLight CrashBase::m_SleighLight private
Definition at line 4 of file wreck_santassleigh.c.