DayzKode: DayZTool Class Reference
DayZTool Class Reference
Private Member Functions
override void Configure ()
void DialogOk ()
void RunDayZBat (string filepath, bool wait=false)
Detailed Description
Definition at line 1 of file dayztools.c.
Member Function Documentation
Configure()
override void DayZTool::Configure () inline private
Definition at line 35 of file dayztools.c.
    {
        Workbench.ScriptDialog("Mission directory","", this);
    }
References Workbench::ScriptDialog().
DialogOk()
void DayZTool::DialogOk () inline private
Definition at line 41 of file dayztools.c.
    {
    }
RunDayZBat()
void DayZTool::RunDayZBat (string filepath, bool wait = false) inline private
Definition at line 3 of file dayztools.c.
    {
        if (filepath.Length() < 2) return;
        filepath.Replace("\\", "/");
        if (filepath[1] != ":")
        {
            string cwd;
            Workbench.GetCwd(cwd);
            filepath = cwd + "/" + filepath;
        }
        int index = filepath.IndexOf("/");
        int last_index = index;
        while(index != -1)
        {
            last_index = index;
            index = filepath.IndexOfFrom(last_index + 1, "/");
        }
        if (last_index == -1) return;
        string path = filepath.Substring(0, last_index);
        string bat = filepath.Substring(last_index + 1, filepath.Length() - last_index - 1);
        /*Print(filepath);
        Print(path);
        Print(bat);*/
        Workbench.RunCmd("cmd /c \"cd " + path + " & call " + bat + "\"", wait);
    }
References Workbench::GetCwd(), string::IndexOf(), string::IndexOfFrom(), string::Length(), path, string::Replace(), Workbench::RunCmd(), and string::Substring().