DayzKode: HumanCommandUnconscious Class Reference
HumanCommandUnconscious Class Reference
Private Member Functions
private void HumanCommandUnconscious ()
proto native bool IsInWater ()
proto native bool IsOnLand ()
proto native void WakeUp (int targetStance=-1)
private void ~HumanCommandUnconscious ()
Detailed Description
Definition at line 601 of file human.c.
Constructor & Destructor Documentation
HumanCommandUnconscious()
private void HumanCommandUnconscious::HumanCommandUnconscious () inline private
Definition at line 603 of file human.c.
{}
~HumanCommandUnconscious()
private void HumanCommandUnconscious::~HumanCommandUnconscious () inline private
Definition at line 604 of file human.c.
{}
Member Function Documentation
IsInWater()
proto native bool HumanCommandUnconscious::IsInWater () private
Referenced by GetTypeOfDeath().
IsOnLand()
proto native bool HumanCommandUnconscious::IsOnLand () private
Referenced by GetTypeOfDeath().
WakeUp()
proto native void HumanCommandUnconscious::WakeUp (int targetStance = -1) private
Referenced by ManBase::CommandHandler(), and PluginDayzPlayerDebug_OtherCmds::Uncon_End().