DayzKode: ActionTargets Class Reference
ActionTargets Class Reference
Private Member Functions
void ActionTargets (PlayerBase player)
vector CalculateRayStart ()
void Clear ()
private float ComputeUtility (Object pTarget, vector pRayStart, vector pRayEnd, Object cursorTarget, vector hitPos)
computes utility of target
private float DistSqrPoint2Line (vector pPoint, vector pL1, vector pL2)
distance between point and line
private void FilterObstructedObjects (Object cursor_target)
private void FilterObstructedObjectsEx (Object cursor_target, array< Object > vicinityObjects)
private int FindIndexForStoring (float value)
binary search algorithm
ActionTarget GetTarget (int index)
returns action target at index
int GetTargetsCount ()
returns count of founded targets
private bool IsObstructed (Object object)
private bool IsObstructedEx (Object object, IsObjectObstructedCache cache)
private void StoreTarget (ActionTarget pActionTarget)
inserts action into sorted array based on utility
void Update ()
Static Private Member Functions
static array< Object > GetVicinityObjects ()
Private Attributes
private const float c_ConeAngle = 30.0
private const float c_ConeHeightMax = 2.0
private const float c_ConeHeightMin = -0.5
private const float c_DistanceDelta = 0.3
private const float c_MaxActionDistance = UAMaxDistances.DEFAULT
private const float c_MaxTargetDistance = 3.0
private const float c_RayDistance = 5.0
searching properties
private const float c_UtilityMaxDistFromRaySqr = 0.8 * 0.8
private const float c_UtilityMaxValue = 10000
utility constants
private const string CE_CENTER = "ce_center"
p3d
private const int GROUPING_COUNT_THRESHOLD = 10
private const float HEIGHT_OFFSET = 0.2
private vector m_HitPos
private PlayerBase m_Player
player owner
private vector m_RayEnd
private ref array< ref ActionTarget > m_Targets
selected & sorted targets by utility function
private const int OBSTRUCTED_COUNT_THRESHOLD = 3
misc
Static Private Attributes
static private ref VicinityObjects m_VicinityObjects private bool m_Debug private vector m_RayStart
objects in vicinity
Detailed Description
Definition at line 173 of file actiontargets.c.
Constructor & Destructor Documentation
ActionTargets()
void ActionTargets::ActionTargets (PlayerBase player) inline private
Definition at line 175 of file actiontargets.c.
    {
        m_Player = player;
        m_VicinityObjects = new VicinityObjects;
        m_Targets = new array<ref ActionTarget>;
        m_Debug = false;
    }
References m_Player, and m_VicinityObjects.
Member Function Documentation
CalculateRayStart()
vector ActionTargets::CalculateRayStart () inline private
tmp hotfix - move the start point for a bit in 3p view (camera collision issue related)
Definition at line 194 of file actiontargets.c.
    {
        vector rayStart = GetGame().GetCurrentCameraPosition();
        if (m_Player.GetCurrentCamera() && m_Player.GetCurrentCamera().IsInherited(DayZPlayerCamera3rdPerson))
        {
            rayStart = GetGame().GetCurrentCameraPosition() + GetGame().GetCurrentCameraDirection() * 0.5;
        }
        return rayStart;
    }
References CGame::GetCurrentCameraPosition(), and GetGame().
Clear()
void ActionTargets::Clear () inline private
Definition at line 189 of file actiontargets.c.
    {
        m_Targets.Clear();
    }
Referenced by ActionManagerClient::Update().
ComputeUtility()
private float ActionTargets::ComputeUtility (Object pTarget, vector pRayStart, vector pRayEnd, Object cursorTarget, vector hitPos) inline private
computes utility of target
out of reach
ground and static objects
Definition at line 419 of file actiontargets.c.
    {
        if (vector.DistanceSq(hitPos, m_Player.GetPosition()) > c_MaxTargetDistance * c_MaxTargetDistance)
            return -1;
        if (pTarget)
        {
            if ( pTarget == cursorTarget )
            {
                if ( pTarget.GetType() == string.Empty )
                    return 0.01;
                if ( pTarget.IsBuilding() )
                    return 0.25;
                if ( pTarget.IsTransport() )
                    return 0.25;
                if ( pTarget.IsWell() )
                    return 0.9;
                vector playerPosXZ = m_Player.GetPosition();
                vector hitPosXZ = hitPos;
                playerPosXZ[1] = 0;
                hitPosXZ[1] = 0;
                if ( vector.DistanceSq(playerPosXZ, hitPosXZ) <= c_MaxTargetDistance * c_MaxTargetDistance )
                    return c_UtilityMaxValue;
            }
            float distSqr = DistSqrPoint2Line(pTarget.GetPosition(), pRayStart, pRayEnd);
            return (c_UtilityMaxDistFromRaySqr - distSqr) / c_UtilityMaxDistFromRaySqr;
        }
        return -1;
    }
References c_MaxTargetDistance, c_UtilityMaxDistFromRaySqr, c_UtilityMaxValue, vector::DistanceSq(), DistSqrPoint2Line(), and m_Player.
DistSqrPoint2Line()
private float ActionTargets::DistSqrPoint2Line (vector pPoint, vector pL1, vector pL2) inline private
distance between point and line
Definition at line 458 of file actiontargets.c.
    {
        vector v = pL2 - pL1;
        vector w = pPoint - pL1;
        float c1 = vector.Dot(w,v);
        float c2 = vector.Dot(v,v);
        if ( c1 <= 0 || c2 == 0 )
            return vector.DistanceSq(pPoint, pL1);
        float b = c1 / c2;
        vector nearestPoint = pL1 + (v * b);
        return vector.DistanceSq(pPoint, nearestPoint);
    }
References vector::DistanceSq(), and vector::Dot().
Referenced by ComputeUtility().
FilterObstructedObjects()
private void ActionTargets::FilterObstructedObjects (Object cursor_target) inline private
check if targets are not obstructed (eg.: wall)
check for object obstruction(if the object is not a proxy - has no parent)
when the number of obstructed items is higher than OBSTRUCTED_COUNT_THRESHOLD remove do no run obstruction check and skip these items
obstruction check
Definition at line 505 of file actiontargets.c.
    {
        int numObstructed = 0;
        int mCount = m_VicinityObjects.Count();
        IsObjectObstructedCache cache = new IsObjectObstructedCache(m_RayStart, mCount);
        mCount--;
        for ( int i = mCount; i >= 0; --i )
        {
            Object object = m_VicinityObjects.GetObject(i);
            Object parent = m_VicinityObjects.GetParent(i);
            if (object && !parent)
            {
                if (numObstructed > OBSTRUCTED_COUNT_THRESHOLD && object != cursor_target)
                {
                    m_VicinityObjects.Remove(object);
                    continue;
                }
                if (object != cursor_target && IsObstructedEx(object, cache))
                {
                    m_VicinityObjects.Remove(object);
                    numObstructed++;
                }
                cache.ClearCache();
            }
        }
    }
References IsObjectObstructedCache(), IsObstructedEx(), m_RayStart, m_VicinityObjects, and OBSTRUCTED_COUNT_THRESHOLD.
Referenced by FilterObstructedObjectsEx().
FilterObstructedObjectsEx()
private void ActionTargets::FilterObstructedObjectsEx (Object cursor_target, array< Object > vicinityObjects) inline private
Definition at line 474 of file actiontargets.c.
    {
        #ifdef DEVELOPER
        if (m_Debug)
            CleanupDebugShapes(obstruction);
        #endif
        array<Object> obstructingObjects = new array<Object>;
        MiscGameplayFunctions.FilterObstructingObjects(vicinityObjects, obstructingObjects);
        if ( obstructingObjects.Count() > 0 )
        {
            PlayerBase player = PlayerBase.Cast(g_Game.GetPlayer());
            int numObstructed = 0;
            int mCount = m_VicinityObjects.Count();
            if (mCount > GROUPING_COUNT_THRESHOLD)
            {
                array<Object> filteredObjects = new array<Object>;
                MiscGameplayFunctions.FilterObstructedObjectsByGrouping(m_RayStart, c_MaxTargetDistance, c_DistanceDelta, m_VicinityObjects.GetRawVicinityObjects(), vicinityObjects, filteredObjects);
                m_VicinityObjects.ClearVicinityObjects();
                m_VicinityObjects.TransformToVicinityObjects(filteredObjects);
            }
            else
            {
                FilterObstructedObjects(cursor_target);
            }
        }
    }
References c_DistanceDelta, c_MaxTargetDistance, FilterObstructedObjects(), g_Game, GROUPING_COUNT_THRESHOLD, m_Debug, m_RayStart, and m_VicinityObjects.
FindIndexForStoring()
private int ActionTargets::FindIndexForStoring (float value) inline private
binary search algorithm
Definition at line 398 of file actiontargets.c.
    {
        int left = 0;
        int right = m_Targets.Count() - 1;
        while ( left <= right )
        {
            int middle = (left + right) / 2;
            float middleValue = m_Targets.Get(middle).GetUtility();
            if ( middleValue == value )
                return middle;
            else if ( middleValue < value )
                right = middle - 1;
            else
                left = middle + 1;
        }
        return left;
    }
References m_Targets.
Referenced by StoreTarget().
GetTarget()
ActionTarget ActionTargets::GetTarget (int index) inline private
returns action target at index
Definition at line 386 of file actiontargets.c.
        { return m_Targets.Get(index); }
References m_Targets.
Referenced by ActionManagerClient::FindActionTarget().
GetTargetsCount()
int ActionTargets::GetTargetsCount () inline private
returns count of founded targets
Definition at line 382 of file actiontargets.c.
        { return m_Targets.Count(); }
References m_Targets.
Referenced by ActionManagerClient::FindActionTarget().
GetVicinityObjects()
static array< Object > ActionTargets::GetVicinityObjects () inline static private
Definition at line 184 of file actiontargets.c.
    {
        return m_VicinityObjects.GetVicinityObjects();
    }
References m_VicinityObjects.
IsObstructed()
private bool ActionTargets::IsObstructed (Object object) inline private
Definition at line 370 of file actiontargets.c.
    {
        IsObjectObstructedCache cache = new IsObjectObstructedCache(m_RayStart, 1);
        return IsObstructedEx(object, cache);
    }
References IsObjectObstructedCache(), IsObstructedEx(), and m_RayStart.
IsObstructedEx()
private bool ActionTargets::IsObstructedEx (Object object, IsObjectObstructedCache cache) inline private
Definition at line 376 of file actiontargets.c.
    {
        return MiscGameplayFunctions.IsObjectObstructedEx(object, cache);
    }
Referenced by FilterObstructedObjects(), and IsObstructed().
StoreTarget()
private void ActionTargets::StoreTarget (ActionTarget pActionTarget) inline private
inserts action into sorted array based on utility
Definition at line 390 of file actiontargets.c.
    {
        int index = FindIndexForStoring(pActionTarget.GetUtility());
        m_Targets.InsertAt(pActionTarget, index);
        //Print("StoreTarget; object: " + pActionTarget.GetObject() + " | parent: " + pActionTarget.GetParent() + " | idx: " + index);
    }
References FindIndexForStoring(), and m_Targets.
Update()
void ActionTargets::Update () inline private
clear state
camera & ray properties
if the cursor target is a proxy
ignores attachments on player
spacial search
removes player from the vicinity
transformation of array of Objects to hashmap (VicinityObjects)
removes Vicinity objects that are not directly visible from player position
select & sort targets based on utility function
action target for surface actions (lowest utility)
Definition at line 205 of file actiontargets.c.
    {
        int i;
#ifdef DEVELOPER
        m_Debug = DiagMenu.GetBool(DiagMenuIDs.DM_ACTION_TARGETS_DEBUG);
#endif
        m_VicinityObjects.ClearVicinityObjects();
        Clear();
        Object cursorTarget = null;
        EntityAI cursorTargetEntity = null;
        array<Object> vicinityObjects = new array<Object>;
        int hitComponentIndex;
        vector playerPos = m_Player.GetPosition();
        vector headingDirection = MiscGameplayFunctions.GetHeadingVector(m_Player);
        m_RayStart = CalculateRayStart();
        m_RayEnd = m_RayStart + GetGame().GetCurrentCameraDirection() * c_RayDistance;
        RaycastRVParams rayInput = new RaycastRVParams(m_RayStart, m_RayEnd, m_Player);
        rayInput.flags = CollisionFlags.ALLOBJECTS;
        //rayInput.sorted = true;
        array<ref RaycastRVResult> results = new array<ref RaycastRVResult>;
        if ( DayZPhysics.RaycastRVProxy(rayInput, results) )
        {
            if ( results.Count() > 0 )
            {
                array<float> distance_helper = new array<float>;
                array<float> distance_helper_unsorted = new array<float>;
                float distance;
                for (i = 0; i < results.Count(); i++)
                {
                    distance = vector.DistanceSq(results[i].pos, m_RayStart);
                    distance_helper.Insert(distance);
                    //Print("#" + i + " " + results.Get(i).obj);
                }
                //Print("--------------");
                distance_helper_unsorted.Copy(distance_helper);
                distance_helper.Sort();
                RaycastRVResult res;
                for ( i = 0; i < results.Count(); i++)
                {
                    res = results.Get(distance_helper_unsorted.Find(distance_helper[i])); //closest object
                    cursorTarget = res.obj;
                    Class.CastTo(cursorTargetEntity,cursorTarget);
                    if ( cursorTarget && ((cursorTarget.IsDamageDestroyed() && (cursorTarget.IsTree() || cursorTarget.IsBush())) || (cursorTargetEntity && cursorTargetEntity.IsHologram())) )
                        continue;
                    if ( res.hierLevel > 0 )
                    {
                        if ( !res.parent.IsMan() )
{
                            m_VicinityObjects.StoreVicinityObject(res.obj, res.parent);
                            //Print("storing, 1st pass (hier > 0): " + res.obj);
                        }
                        else
                            continue;
                    }
                    else
                    {
                        m_VicinityObjects.StoreVicinityObject(res.obj, null);
                        //Print("storing, 1st pass: " + res.obj);
                    }
                    m_HitPos = res.pos;
                    hitComponentIndex = res.component;
                    break;
                }
            }
            //else
                //Print("NO RESULTS FOUND!");
        }
        else
        {
            //Print("CAST UNSUCCESFUL");
            cursorTarget = null;
            m_HitPos = vector.Zero;
            hitComponentIndex = -1;
        }
        //Print(cursorTarget);
        DayZPlayerCamera camera = m_Player.GetCurrentCamera();
        if (camera && camera.GetCurrentPitch() <= -45) // Spatial search is a contributor to very heavy searching, limit it to when we are at least looking down
            DayZPlayerUtils.GetEntitiesInCone(playerPos, headingDirection, c_ConeAngle, c_MaxTargetDistance, c_ConeHeightMin, c_ConeHeightMax, vicinityObjects);
        vicinityObjects.RemoveItem(m_Player);
        //Print("m_VicinityObjects before" + m_VicinityObjects.Count());
        m_VicinityObjects.TransformToVicinityObjects(vicinityObjects);
        //Print("m_VicinityObjects after" + m_VicinityObjects.Count());
        FilterObstructedObjectsEx(cursorTarget, vicinityObjects);
        for ( i = 0; i < m_VicinityObjects.Count(); i++ )
        {
            Object object = m_VicinityObjects.GetObject(i);
            Object parent = m_VicinityObjects.GetParent(i);
            float utility = ComputeUtility(object, m_RayStart, m_RayEnd, cursorTarget, m_HitPos);
            if ( utility > 0 )
            {
                int targetComponent = -1;
                targetComponent = hitComponentIndex;
                ActionTarget at = new ActionTarget(object, parent, targetComponent, m_HitPos, utility);
                StoreTarget(at);
            }
            /*else
                Print("utility < 0; object: " + object + " | parent: " + parent);*/
        }
        if (m_HitPos == vector.Zero)
        {
            vector      contact_pos, contact_dir, hitNormal;
            int         contactComponent;
            float       hitFraction;
            Object      hitObject;
            m_RayEnd = m_RayStart + GetGame().GetCurrentCameraDirection() * c_RayDistance * 3;
            PhxInteractionLayers collisionLayerMask = PhxInteractionLayers.ROADWAY|PhxInteractionLayers.TERRAIN|PhxInteractionLayers.WATERLAYER;
            DayZPhysics.RayCastBullet(m_RayStart,m_RayEnd,collisionLayerMask,null,hitObject,contact_pos,hitNormal,hitFraction);
            m_HitPos = contact_pos;
        }
        m_Targets.Insert(new ActionTarget(null, null, -1, m_HitPos, 0));
#ifdef DEVELOPER
        if (m_Debug)
        {
            ShowDebugActionTargets(true);
            DrawDebugActionTargets(true);
            DrawDebugCone(true);
            DrawDebugRay(true);
            DrawSelectionPos(DiagMenu.GetBool(DiagMenuIDs.DM_ACTION_TARGETS_SELPOS_DEBUG));
        }
        else
        {
            ShowDebugActionTargets(false);
            DrawDebugActionTargets(false);
            DrawDebugCone(false);
            DrawDebugRay(false);
            DrawSelectionPos(false);
        }
#endif
        //Print("--------------");
    }
Referenced by ActionManagerClient::Update().
Member Data Documentation
c_ConeAngle
private const float ActionTargets::c_ConeAngle = 30.0 private
Definition at line 738 of file actiontargets.c.
c_ConeHeightMax
private const float ActionTargets::c_ConeHeightMax = 2.0 private
Definition at line 740 of file actiontargets.c.
c_ConeHeightMin
private const float ActionTargets::c_ConeHeightMin = -0.5 private
Definition at line 739 of file actiontargets.c.
c_DistanceDelta
private const float ActionTargets::c_DistanceDelta = 0.3 private
Definition at line 741 of file actiontargets.c.
Referenced by FilterObstructedObjectsEx().
c_MaxActionDistance
private const float ActionTargets::c_MaxActionDistance = UAMaxDistances.DEFAULT private
Definition at line 737 of file actiontargets.c.
c_MaxTargetDistance
private const float ActionTargets::c_MaxTargetDistance = 3.0 private
Definition at line 736 of file actiontargets.c.
Referenced by ComputeUtility(), and FilterObstructedObjectsEx().
c_RayDistance
private const float ActionTargets::c_RayDistance = 5.0 private
searching properties
Definition at line 735 of file actiontargets.c.
c_UtilityMaxDistFromRaySqr
private const float ActionTargets::c_UtilityMaxDistFromRaySqr = 0.8 * 0.8 private
Definition at line 745 of file actiontargets.c.
Referenced by ComputeUtility().
c_UtilityMaxValue
private const float ActionTargets::c_UtilityMaxValue = 10000 private
utility constants
Definition at line 744 of file actiontargets.c.
Referenced by ComputeUtility().
CE_CENTER
private const string ActionTargets::CE_CENTER = "ce_center" private
p3d
Definition at line 748 of file actiontargets.c.
GROUPING_COUNT_THRESHOLD
private const int ActionTargets::GROUPING_COUNT_THRESHOLD = 10 private
Definition at line 753 of file actiontargets.c.
Referenced by FilterObstructedObjectsEx().
HEIGHT_OFFSET
private const float ActionTargets::HEIGHT_OFFSET = 0.2 private
Definition at line 749 of file actiontargets.c.
m_HitPos
private vector ActionTargets::m_HitPos private
Definition at line 729 of file actiontargets.c.
m_Player
private PlayerBase ActionTargets::m_Player private
player owner
Definition at line 717 of file actiontargets.c.
Referenced by ActionTargets(), and ComputeUtility().
m_RayEnd
private vector ActionTargets::m_RayEnd private
Definition at line 728 of file actiontargets.c.
m_RayStart
private ref VicinityObjects m_VicinityObjects private bool m_Debug private vector ActionTargets::m_RayStart static private
objects in vicinity
Definition at line 727 of file actiontargets.c.
Referenced by FilterObstructedObjects(), FilterObstructedObjectsEx(), and IsObstructed().
m_Targets
private ref array<ref ActionTarget> ActionTargets::m_Targets private
selected & sorted targets by utility function
Definition at line 720 of file actiontargets.c.
Referenced by FindIndexForStoring(), GetTarget(), GetTargetsCount(), and StoreTarget().
OBSTRUCTED_COUNT_THRESHOLD
private const int ActionTargets::OBSTRUCTED_COUNT_THRESHOLD = 3 private
misc
Definition at line 752 of file actiontargets.c.
Referenced by FilterObstructedObjects().