DayzKode: BiosPrivacyService Class Reference
BiosPrivacyService Class Reference
BiosPrivacyService is used to query privacy permissions for a target user/s.
Private Member Functions
proto native EBiosError GetPermissionsAsync (array< string > uid_list, array< EBiosPrivacyPermission > permission_list)
Query for privacy permissions.
proto native EBiosError GetPrivilegeAsync (EBiosPrivacyPrivilege privilege, bool try_resolution)
Query for privileges.
void OnPermissions (BiosPrivacyUidResultArray result_list, EBiosError error)
Async callback for GetPermissionsAsync.
void OnPrivilege (EBiosPrivacyPrivilege privilege, EBiosError error)
Async callback for GetPrivilegeAsync.
Detailed Description
BiosPrivacyService is used to query privacy permissions for a target user/s.
Definition at line 53 of file biosprivacyservice.c.
Member Function Documentation
GetPermissionsAsync()
proto native EBiosError BiosPrivacyService::GetPermissionsAsync (array< string > uid_list, array< EBiosPrivacyPermission > permission_list) private
Query for privacy permissions.
The async result is returned in the OnPermissions callback. Expected errors: BAD_PARAMETER - if atleast one of the permissions is not supported on the current platform, or atleast one of the input arrays is NULL.
Parameters
uid_list list of target user Uid's for which to query privacy permissions.
permission_list list of requested permissions for each target user.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::LoadPermissions().
GetPrivilegeAsync()
proto native EBiosError BiosPrivacyService::GetPrivilegeAsync (EBiosPrivacyPrivilege privilege, bool try_resolution) private
Query for privileges.
The async result is returned in the OnPrivilege callback. Expected errors: BAD_PARAMETER - if atleast one of the privileges is not supported on the current platform, PURCHASE_REQUIRED, BANNED, NOT_ALLOWED - the privilege is granted,
Parameters
privilege the requested privilege.
tryResolution Xbox: show system GUI with error msg and attempts to resolve it if possible.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::LoadMPPrivilege(), and OnlineServices::LoadVoicePrivilege().
OnPermissions()
void BiosPrivacyService::OnPermissions (BiosPrivacyUidResultArray result_list, EBiosError error) inline private
Async callback for GetPermissionsAsync.
Parameters
result_list list of results for each requested user. NULL if failed.
error error indicating success or fail of the async operation.
Definition at line 91 of file biosprivacyservice.c.
    {
        if (result_list == null)
        {
            Print("biapi privacy error: " + error);
            return;
        }
        OnlineServices.OnPermissionsAsync( result_list, error );
    }
References OnlineServices::OnPermissionsAsync(), and Print().
OnPrivilege()
void BiosPrivacyService::OnPrivilege (EBiosPrivacyPrivilege privilege, EBiosError error) inline private
Async callback for GetPrivilegeAsync.
Parameters
privilege the requested privilege.
error error indicating success or fail of the async operation.
Definition at line 107 of file biosprivacyservice.c.
    {
        switch( privilege )
        {
            case EBiosPrivacyPrivilege.MULTIPLAYER_GAMEPLAY:
            {
                OnlineServices.OnLoadMPPrivilege( error );
                break;
            }
            case EBiosPrivacyPrivilege.COMMUNICATE_VOICE:
            {
                OnlineServices.OnLoadVoicePrivilege( error );
                break;
            }
        }
    }
References OnlineServices::OnLoadMPPrivilege(), and OnlineServices::OnLoadVoicePrivilege().