DayzKode: ReplaceItemWithNewLambdaBase Class Reference
ReplaceItemWithNewLambdaBase Class Reference
base class for transformation operations (creating one item from another)
Private Member Functions
protected bool CanExecuteLambda ()
void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Step E. copy properties from old object to the created one.
protected void CreateNetworkObjectInfo (EntityAI new_item)
Step G. - create NetworkObjectInfo for new item.
protected EntityAI CreateNewEntity ()
Step D. - create new entity (LOCAL) with specified type.
protected void DeleteOldEntity ()
Step F. - deletes physically old item.
string DumpToString ()
void Execute (HumanInventoryWithFSM fsm_to_notify=null)
protected void OnAbort ()
Step Out - notification on abort.
protected void OnSuccess (EntityAI new_item)
Step H. - notification on finish.
void OverrideNewLocation (InventoryLocation newLocation)
protected bool PrepareLocations ()
Step A. - prepare inventory locations.
protected void RemoveNetworkObjectInfo ()
Step C. - remove network part of the object @NOTE this operation does not delete the object, only removes its network part (and deletes it on client)
protected void RemoveOldItemFromLocation ()
Step B. - free location for new item @NOTE this operation does not delete the object, only removes it from inventory location.
void ReplaceItemWithNewLambdaBase (EntityAI old_item, string new_item_type)
protected void UndoRemoveNetworkObjectInfo ()
protected void UndoRemoveOldItemFromLocation ()
void VerifyItemTypeBySlotType ()
protected bool WantCreateNewEntity ()
Private Attributes
string m_NewItemType
protected ref InventoryLocation m_NewLocation
EntityAI m_OldItem
protected ref InventoryLocation m_OldLocation
protected bool m_RemoveFromLocationPassed = false
private bool m_RemoveNetworkObjectInfoPassed = false
Detailed Description
base class for transformation operations (creating one item from another)
Definition at line 4 of file replaceitemwithnewlambdabase.c.
Constructor & Destructor Documentation
ReplaceItemWithNewLambdaBase()
void ReplaceItemWithNewLambdaBase::ReplaceItemWithNewLambdaBase (EntityAI old_item, string new_item_type) inline private
Definition at line 13 of file replaceitemwithnewlambdabase.c.
    {
        m_OldItem = old_item;
        m_NewItemType = new_item_type;
    }
References m_NewItemType, and m_OldItem.
Member Function Documentation
CanExecuteLambda()
protected bool ReplaceItemWithNewLambdaBase::CanExecuteLambda () inline private
Definition at line 31 of file replaceitemwithnewlambdabase.c.
    {
        if (m_OldItem)
            if (GameInventory.LocationCanRemoveEntity(m_OldLocation))
                //if (WantCreateNewEntity() GameInventory.LocationTestAddEntityType(m_NewItemType, true, true, false, true))
                    return true;
        return false;
    }
References m_OldItem, and m_OldLocation.
Referenced by Execute().
CopyOldPropertiesToNew()
ReplaceItemWithNewLambdaBase::CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item) inline private
Step E. copy properties from old object to the created one.
@NOTE: This is supposed to be overriden in derived classes
Definition at line 185 of file replaceitemwithnewlambdabase.c.
    {
        hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step E) Copying props " + old_item + " --> " + new_item);
    }
References hndDebugPrint().
Referenced by Execute().
CreateNetworkObjectInfo()
ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo (EntityAI new_item) inline private
Step G. - create NetworkObjectInfo for new item.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 204 of file replaceitemwithnewlambdabase.c.
    {
        hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step G) CreateNetworkObjectInfo =" + new_item);
        if (new_item)
            GetGame().RemoteObjectTreeCreate(new_item); // G) this forces server to send CreateVehicle Message to client. This is needed for preserving the appearance of network operations on client (so that DeleteObject(old) arrives before CreateVehicle(new)). @NOTE: this does not delete the object on server, only it's network representation.
    }
References GetGame(), hndDebugPrint(), and CGame::RemoteObjectTreeCreate().
Referenced by Execute().
CreateNewEntity()
ReplaceItemWithNewLambdaBase::CreateNewEntity () inline private
Step D. - create new entity (LOCAL) with specified type.
@NOTE: if (!m_NewLocation || m_NewItemType.Empty) ==> this function does not create a new entity
Definition at line 123 of file replaceitemwithnewlambdabase.c.
    {
        if (WantCreateNewEntity())
        {
            VerifyItemTypeBySlotType();
            EntityAI new_item;
            switch (m_NewLocation.GetType())
            {
                case InventoryLocationType.GROUND:
                    new_item = EntityAI.Cast(GetGame().CreateObjectEx(m_NewItemType,m_NewLocation.GetPos(),ECE_PLACE_ON_SURFACE|ECE_LOCAL));
                    string path = "" + CFG_VEHICLESPATH + " " + m_NewItemType + " inherit_rotation";
                    bool keep_rotation = GetGame().ConfigIsExisting(path) && GetGame().ConfigGetInt(path) > 0;
                    if (keep_rotation)
                    {
                        new_item.SetOrientation(m_OldItem.GetOrientation()); //this one actually works...debug InventoryLocation
                    }
                break;
                case InventoryLocationType.ATTACHMENT:
                    // forces rawlocation in C++ to make location Valid
                    m_NewLocation.SetAttachment(m_NewLocation.GetParent(), null, m_NewLocation.GetSlot());
                    new_item = GameInventory.LocationCreateEntity(m_NewLocation, m_NewItemType, ECE_OBJECT_SWAP, RF_NONE);
                break;
                default:
                    new_item = GameInventory.LocationCreateLocalEntity(m_NewLocation, m_NewItemType, ECE_OBJECT_SWAP, RF_NONE);
                break;
            }
            hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step D) Created new new_item=" + new_item);
            if (new_item)
            {
                return new_item;
            }
            else
            {
                return null;
                /*InventoryLocation backupLocation = new InventoryLocation;
                vector mtx[4];
                Math3D.MatrixIdentity4(mtx);
                mtx[3] = m_OldItem.GetPosition();
                backupLocation.SetGround(null, mtx);
                hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step D) plan B - creating=" + m_NewItemType + " at bkp loc=" + backupLocation.DumpToString() + ", but failed");
                new_item = GameInventory.LocationCreateLocalEntity(backupLocation, m_NewItemType,ECE_OBJECT_SWAP,RF_NONE); // create LOCAL new one on ground
                if (!new_item)
                {
                    Error("[inv] ReplaceItemWithNewLambdaBase Step D) plan B - wanted to create=" + m_NewItemType + " at bkp loc=" + backupLocation.DumpToString() + ", but failed");
                    return null;
                }
                return new_item;*/
            }
        }
        // user did not asked for new entity
        return null;
    }
References CFG_VEHICLESPATH, CGame::ConfigGetInt(), CGame::ConfigIsExisting(), ECE_LOCAL, ECE_OBJECT_SWAP, ECE_PLACE_ON_SURFACE, GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetPos(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), hndDebugPrint(), m_NewItemType, m_NewLocation, m_OldItem, path, RF_NONE, InventoryLocation::SetAttachment(), VerifyItemTypeBySlotType(), and WantCreateNewEntity().
Referenced by Execute().
DeleteOldEntity()
ReplaceItemWithNewLambdaBase::DeleteOldEntity () inline private
Step F. - deletes physically old item.
Definition at line 193 of file replaceitemwithnewlambdabase.c.
    {
        hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step F) delete old item=" + m_OldItem);
        GetGame().ObjectDelete(m_OldItem);
    }
References GetGame(), hndDebugPrint(), m_OldItem, and CGame::ObjectDelete().
Referenced by Execute().
DumpToString()
string ReplaceItemWithNewLambdaBase::DumpToString () inline private
Definition at line 294 of file replaceitemwithnewlambdabase.c.
    {
        string s = "{ old=" + m_OldItem + " newType=" + m_NewItemType + "}";
        return s;
    }
References m_NewItemType, and m_OldItem.
Referenced by EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), and EntityAI::ReplaceItemWithNewImpl().
Execute()
void ReplaceItemWithNewLambdaBase::Execute (HumanInventoryWithFSM fsm_to_notify = null) inline private
Definition at line 231 of file replaceitemwithnewlambdabase.c.
    {
        int t = GetGame().GetTime();
        hndDebugPrint("[syncinv] t=" + t + " lambda.Execute start ");
        // A) init
        bool prepared = PrepareLocations();
        if (prepared && CanExecuteLambda())
        {
            // B) rm old (and delete on client)
            RemoveOldItemFromLocation();
            if (!m_RemoveFromLocationPassed)
            {
                Error("[inv] ReplaceItemWithNewLambdaBase Step B) ABORT - failed while rm old item from loc=" + InventoryLocation.DumpToStringNullSafe(m_OldLocation));
                if (fsm_to_notify)
                    fsm_to_notify.ProcessHandAbortEvent(new HandEventHumanCommandActionAborted(fsm_to_notify.GetManOwner()));
                OnAbort();
                return;
            }
            // C) rm NetworkObjectInfo from old item (+ send delete object tree to clients)
            RemoveNetworkObjectInfo();
            // D) mk new in place of old
            EntityAI new_item = CreateNewEntity();
            if (WantCreateNewEntity() && new_item == null)
            {
                //Error("[inv] ReplaceItemWithNewLambdaBase Step D) ABORT - wanted to create=" + m_NewItemType + " at loc=" + m_NewLocation.DumpToString() + ", but failed");
                Print("Error [inv] ReplaceItemWithNewLambdaBase Step D) ABORT - wanted to create=" + m_NewItemType + " at loc=" + InventoryLocation.DumpToStringNullSafe(m_NewLocation) + ", but failed");
                if (m_RemoveFromLocationPassed)
                    UndoRemoveOldItemFromLocation();
                if (m_RemoveNetworkObjectInfoPassed)
                    UndoRemoveNetworkObjectInfo();
                OnAbort();
                if (fsm_to_notify)
                    fsm_to_notify.ProcessHandAbortEvent(new HandEventHumanCommandActionAborted(fsm_to_notify.GetManOwner()));
                return;
            }
            // E) cpy props
            CopyOldPropertiesToNew(m_OldItem, new_item);
            // F) del old
            DeleteOldEntity();
            // G) mk new NetworkObjectInfo
            CreateNetworkObjectInfo(new_item);
            // H) notification
            OnSuccess(new_item);
        }
        else
        {
            Print("[syncinv] warning, lambda cannot be executed, skipping!");
        }
        int te = GetGame().GetTime();
        int dt = te - t;
        hndDebugPrint("[syncinv] te=" + te + " lambda.Execute end, exec time=" + dt);
    }
References CanExecuteLambda(), CopyOldPropertiesToNew(), CreateNetworkObjectInfo(), CreateNewEntity(), DeleteOldEntity(), InventoryLocation::DumpToStringNullSafe(), Error(), GetGame(), CGame::GetTime(), hndDebugPrint(), m_NewItemType, m_NewLocation, m_OldItem, m_OldLocation, m_RemoveFromLocationPassed, m_RemoveNetworkObjectInfoPassed, OnAbort(), OnSuccess(), PrepareLocations(), Print(), RemoveNetworkObjectInfo(), RemoveOldItemFromLocation(), UndoRemoveNetworkObjectInfo(), UndoRemoveOldItemFromLocation(), and WantCreateNewEntity().
Referenced by ReplaceItemWithNew().
OnAbort()
ReplaceItemWithNewLambdaBase::OnAbort () inline private
Step Out - notification on abort.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 226 of file replaceitemwithnewlambdabase.c.
    {
        Print("Error [inv] ReplaceItemWithNewLambdaBase OnAbort");
    }
References Print().
Referenced by Execute().
OnSuccess()
ReplaceItemWithNewLambdaBase::OnSuccess (EntityAI new_item) inline private
Step H. - notification on finish.
@NOTE: new_item can be null if the lambda did not create any item (intentionaly)
Definition at line 216 of file replaceitemwithnewlambdabase.c.
    {
        hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step H) OnSuccess=" + new_item);
    }
References hndDebugPrint().
Referenced by Execute().
OverrideNewLocation()
void ReplaceItemWithNewLambdaBase::OverrideNewLocation (InventoryLocation newLocation) inline private
Definition at line 19 of file replaceitemwithnewlambdabase.c.
    {
        m_NewLocation = newLocation;
    }
References m_NewLocation.
PrepareLocations()
ReplaceItemWithNewLambdaBase::PrepareLocations () inline private
Step A. - prepare inventory locations.
Definition at line 43 of file replaceitemwithnewlambdabase.c.
    {
        hndDebugPrint("[inv] ReplaceItemWithNewLambdaBase Step A) Prepare inventory locations, old_item=" + m_OldItem);
        m_OldLocation = new InventoryLocation;
        if (m_OldItem.GetInventory().GetCurrentInventoryLocation(m_OldLocation)) // A.1) store old location
        {
            if (m_NewLocation == null)
            {
                m_NewLocation = new InventoryLocation;
                m_NewLocation.CopyLocationFrom(m_OldLocation, true);    // A.2) prepare new location from old
                //setting proper location type for ground pos
                if (!m_NewLocation.GetParent())
                {
                    vector m4[4];
                    Math3D.MatrixIdentity4(m4);
                    m4[3] = m_NewLocation.GetPos();
                    string path = "" + CFG_VEHICLESPATH + " " + m_NewItemType + " inherit_rotation";
                    bool keep_rotation = GetGame().ConfigIsExisting(path) && GetGame().ConfigGetInt(path) > 0;
                    if (m_OldLocation.GetType() == InventoryLocationType.GROUND && keep_rotation)
                    {
                        float dir[4];
                        m_OldLocation.GetDir(dir);
                        m_NewLocation.SetGroundEx(null,m_NewLocation.GetPos(),dir);
                    }
                    else
                    {
                        m_NewLocation.SetGround(null,m4);
                    }
                }
            }
            return true;
        }
        else
            Error("[inv] ReplaceItemWithNewLambdaBase Step A.1) failed to get old_item inventory location");
        return false;
    }
References CFG_VEHICLESPATH, CGame::ConfigGetInt(), CGame::ConfigIsExisting(), InventoryLocation::CopyLocationFrom(), Error(), InventoryLocation::GetDir(), GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetPos(), InventoryLocation::GetType(), hndDebugPrint(), m_NewItemType, m_NewLocation, m_OldItem, m_OldLocation, Math3D::MatrixIdentity4(), path, InventoryLocation::SetGround(), and InventoryLocation::SetGroundEx().
Referenced by Execute().
RemoveNetworkObjectInfo()
ReplaceItemWithNewLambdaBase::RemoveNetworkObjectInfo () inline private
Step C. - remove network part of the object @NOTE this operation does not delete the object, only removes its network part (and deletes it on client)
Definition at line 107 of file replaceitemwithnewlambdabase.c.
    {
        GetGame().RemoteObjectTreeDelete(m_OldItem); // C) this forces server to send DeleteObject Message to client. This is needed for preserving the appearance of network operations on client (so that DeleteObject(old) arrives before CreateVehicle(new)). @NOTE: this does not delete the object on server, only it's network representation.
        // @NOTE: the item is not deleted right now on server, but rather after copying the properties in Step E)
        m_RemoveNetworkObjectInfoPassed = true;
    }
References GetGame(), m_OldItem, m_RemoveNetworkObjectInfoPassed, and CGame::RemoteObjectTreeDelete().
Referenced by Execute().
RemoveOldItemFromLocation()
ReplaceItemWithNewLambdaBase::RemoveOldItemFromLocation () inline private
Step B. - free location for new item @NOTE this operation does not delete the object, only removes it from inventory location.
Definition at line 86 of file replaceitemwithnewlambdabase.c.
    {
        if (!GameInventory.LocationRemoveEntity(m_OldLocation)) // B) remove entity from old inventory location (making it free for new item)
        {
            Error("[inv] ReplaceItemWithNewLambdaBase Step B) failed to remove old_item rom current inventory location");
            m_RemoveFromLocationPassed = false;
        }
        Print("[inv] ReplaceItemWithNewLambdaBase Step B) remove OK, loc=" + InventoryLocation.DumpToStringNullSafe(m_OldLocation));
        m_RemoveFromLocationPassed = true;
    }
References InventoryLocation::DumpToStringNullSafe(), Error(), m_OldLocation, m_RemoveFromLocationPassed, and Print().
Referenced by Execute().
UndoRemoveNetworkObjectInfo()
protected void ReplaceItemWithNewLambdaBase::UndoRemoveNetworkObjectInfo () inline private
Definition at line 113 of file replaceitemwithnewlambdabase.c.
    {
        GetGame().RemoteObjectTreeCreate(m_OldItem);
    }
References GetGame(), m_OldItem, and CGame::RemoteObjectTreeCreate().
Referenced by Execute().
UndoRemoveOldItemFromLocation()
protected void ReplaceItemWithNewLambdaBase::UndoRemoveOldItemFromLocation () inline private
Definition at line 96 of file replaceitemwithnewlambdabase.c.
    {
        if (!GameInventory.LocationAddEntity(m_OldLocation)) // B) undo
            Error("[inv] ReplaceItemWithNewLambdaBase Step B) failed to undo remove");
        Print("[inv] ReplaceItemWithNewLambdaBase Step B) undo remove OK, loc=" + InventoryLocation.DumpToStringNullSafe(m_OldLocation));
    }
References InventoryLocation::DumpToStringNullSafe(), Error(), m_OldLocation, and Print().
Referenced by Execute().
VerifyItemTypeBySlotType()
void ReplaceItemWithNewLambdaBase::VerifyItemTypeBySlotType () inline private
Definition at line 24 of file replaceitemwithnewlambdabase.c.
{}
Referenced by CreateNewEntity().
WantCreateNewEntity()
protected bool ReplaceItemWithNewLambdaBase::WantCreateNewEntity () inline private
Definition at line 26 of file replaceitemwithnewlambdabase.c.
    {
        return m_NewLocation && m_NewItemType != string.Empty;
    }
References string::Empty, m_NewItemType, and m_NewLocation.
Referenced by CreateNewEntity(), and Execute().
Member Data Documentation
m_NewItemType
string ReplaceItemWithNewLambdaBase::m_NewItemType private
Definition at line 7 of file replaceitemwithnewlambdabase.c.
Referenced by UnboxLambda::CopyOldPropertiesToNew(), CreateNewEntity(), DumpToString(), Execute(), PrepareLocations(), ReplaceItemWithNewLambdaBase(), and WantCreateNewEntity().
m_NewLocation
protected ref InventoryLocation ReplaceItemWithNewLambdaBase::m_NewLocation private
Definition at line 9 of file replaceitemwithnewlambdabase.c.
Referenced by DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), CreateNewEntity(), Execute(), OverrideNewLocation(), PrepareLocations(), and WantCreateNewEntity().
m_OldItem
EntityAI ReplaceItemWithNewLambdaBase::m_OldItem private
Definition at line 6 of file replaceitemwithnewlambdabase.c.
Referenced by CanExecuteLambda(), CreateNewEntity(), DeleteOldEntity(), DumpToString(), Execute(), PrepareLocations(), RemoveNetworkObjectInfo(), HumanInventory::ReplaceItemWithNew(), ReplaceItemWithNew(), ReplaceItemWithNewLambdaBase(), and UndoRemoveNetworkObjectInfo().
m_OldLocation
protected ref InventoryLocation ReplaceItemWithNewLambdaBase::m_OldLocation private
Definition at line 8 of file replaceitemwithnewlambdabase.c.
Referenced by CanExecuteLambda(), Execute(), PrepareLocations(), RemoveOldItemFromLocation(), and UndoRemoveOldItemFromLocation().
m_RemoveFromLocationPassed
protected bool ReplaceItemWithNewLambdaBase::m_RemoveFromLocationPassed = false private
Definition at line 10 of file replaceitemwithnewlambdabase.c.
Referenced by Execute(), and RemoveOldItemFromLocation().
m_RemoveNetworkObjectInfoPassed
private bool ReplaceItemWithNewLambdaBase::m_RemoveNetworkObjectInfoPassed = false private
Definition at line 11 of file replaceitemwithnewlambdabase.c.
Referenced by Execute(), and RemoveNetworkObjectInfo().