DayzKode: FliesMdfr Class Reference
FliesMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const float DISTANCE_SENSITIVITY_SQR = Math.SqrFloat(0.05)
const int IDLE_COUNT_THRESHOLD = 60
int m_IdleCount
vector m_PrevPosition
const int TICK_FREQUENCY = 15
Detailed Description
Definition at line 1 of file flies.c.
Member Function Documentation
ActivateCondition()
override bool FliesMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 20 of file flies.c.
    {
        return false;
    }
DeactivateCondition()
override bool FliesMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 25 of file flies.c.
    {
        return false;
    }
Init()
override void FliesMdfr::Init () inline private
Definition at line 10 of file flies.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_FLIES;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = TICK_FREQUENCY;
        DisableActivateCheck();
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, m_TrackActivatedTime, and TICK_FREQUENCY.
OnActivate()
override void FliesMdfr::OnActivate (PlayerBase player) inline private
Definition at line 63 of file flies.c.
    {
        m_IdleCount = 0;
        player.m_CorpseState = -PlayerConstants.CORPSE_STATE_DECAYED;
        player.SetSynchDirty();
    }
References PlayerConstants::CORPSE_STATE_DECAYED, and m_IdleCount.
OnDeactivate()
override void FliesMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 70 of file flies.c.
    {
    }
OnReconnect()
override void FliesMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 58 of file flies.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void FliesMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 30 of file flies.c.
    {
        float dist_sqr = vector.DistanceSq(player.GetPosition(), m_PrevPosition);
        if( dist_sqr < DISTANCE_SENSITIVITY_SQR)//has the player stayed still since last check
        {
            m_IdleCount++;
        }
        else
        {
            if(m_IdleCount >= IDLE_COUNT_THRESHOLD)//disable the effect
            {
                player.m_CorpseState = -PlayerConstants.CORPSE_STATE_DECAYED;
                player.SetSynchDirty();
            }
            m_IdleCount = 0;//player moved, reset the count
        }
        m_PrevPosition = player.GetPosition();
        if( m_IdleCount == IDLE_COUNT_THRESHOLD)//should we play the effect ?
        {
            player.m_CorpseState = PlayerConstants.CORPSE_STATE_DECAYED;
            player.SetSynchDirty();
        }
    }
References PlayerConstants::CORPSE_STATE_DECAYED, DISTANCE_SENSITIVITY_SQR, vector::DistanceSq(), IDLE_COUNT_THRESHOLD, m_IdleCount, and m_PrevPosition.
Member Data Documentation
DISTANCE_SENSITIVITY_SQR
const float FliesMdfr::DISTANCE_SENSITIVITY_SQR = Math.SqrFloat(0.05) private
Definition at line 3 of file flies.c.
Referenced by OnTick().
IDLE_COUNT_THRESHOLD
const int FliesMdfr::IDLE_COUNT_THRESHOLD = 60 private
Definition at line 5 of file flies.c.
Referenced by OnTick().
m_IdleCount
int FliesMdfr::m_IdleCount private
Definition at line 7 of file flies.c.
Referenced by OnActivate(), and OnTick().
m_PrevPosition
vector FliesMdfr::m_PrevPosition private
Definition at line 6 of file flies.c.
Referenced by OnTick().
TICK_FREQUENCY
const int FliesMdfr::TICK_FREQUENCY = 15 private
Definition at line 4 of file flies.c.
Referenced by Init().