DayzKode: Barrel_ColorBase Class Reference
Barrel_ColorBase Class Reference
Private Member Functions
void Barrel_ColorBase ()
void BleachClothes (ItemBase bleach, PlayerBase player)
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
override bool CanReleaseCargo (EntityAI attachment)
override void Close ()
void CloseLoad ()
void ColourClothes (ItemBase rci, ItemBase gci, ItemBase bci, PlayerBase player)
void ColourLeatherClothes (ItemBase color_source, PlayerBase player, string color)
void DetermineAction (PlayerBase player)
override int GetDamageSystemVersionChange ()
override float GetLiquidThroughputCoef ()
override string GetPlaceSoundset ()
bool IsLocked ()
override bool IsOpen ()
void Lock (float actiontime)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void Open ()
void OpenLoad ()
void ProduceFertilizer (ItemBase guts, ItemBase plant, PlayerBase player)
override void SetActions ()
void SoundBarrelClosePlay ()
void SoundBarrelOpenPlay ()
void TanPelts (ItemBase lime, PlayerBase player)
void Unlock ()
protected void UpdateVisualState ()
Private Attributes
private ref Timer m_BarrelOpener
private bool m_IsLocked = false
protected ref OpenableBehaviour m_Openable
ref RainProcurementManager m_RainProcurement
Detailed Description
Definition at line 1 of file barrel_colorbase.c.
Constructor & Destructor Documentation
Barrel_ColorBase()
void Barrel_ColorBase::Barrel_ColorBase () inline private
Definition at line 9 of file barrel_colorbase.c.
    {
        m_BarrelOpener = new Timer();
        m_Openable = new OpenableBehaviour(false);
        m_RainProcurement = new RainProcurementManager( this );
        m_HalfExtents = Vector(0.30,0.85,0.30);
        RegisterNetSyncVariableBool("m_Openable.m_IsOpened");
        RegisterNetSyncVariableBool("m_IsSoundSynchRemote");
        RegisterNetSyncVariableBool("m_IsPlaceSound");
    }
References m_BarrelOpener, m_HalfExtents, m_Openable, m_RainProcurement, and Vector().
Member Function Documentation
BleachClothes()
void Barrel_ColorBase::BleachClothes (ItemBase bleach, PlayerBase player) inline private
Definition at line 365 of file barrel_colorbase.c.
    {
        EntityAI item;
        int bleach_amount = bleach.GetQuantity();
        int item_count = GetInventory().GetCargo().GetItemCount();
        string item_name = "";
        for (int i = 0; i < item_count; i++)
        {
            item = GetInventory().GetCargo().GetItem(i);
            if ( item.IsClothing() )
            {
                if ( bleach_amount >= GameConstants.BAREL_BLEACH_PER_CLOTH )
                {
                    if ( ( GetGame().ObjectIsKindOf (item, "TShirt_ColorBase") && !GetGame().ObjectIsKindOf (item, "TShirt_White") ) || ( GetGame().ObjectIsKindOf (item, "Armband_ColorBase") && !GetGame().ObjectIsKindOf (item, "Armband_White") ) ) //cannot bleach white items...?
                    {
                        int index = item.GetType().IndexOf("_");
                        string itemtype = item.GetType().Substring( 0, index + 1 );
                        ItemBase itemIB = ItemBase.Cast(item);
                        MiscGameplayFunctions.TurnItemIntoItem(itemIB,itemtype+"White",player);
                        bleach_amount -= GameConstants.BAREL_BLEACH_PER_CLOTH;
                    }
                    if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherSack_ColorBase") )
                    {
                        item_name = "LeatherSack_Natural";
                    }
                    else if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherStorageVest_ColorBase") )
                    {
                        item_name = "LeatherStorageVest_Natural";
                    }
                    else if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherJacket_ColorBase") )
                    {
                        item_name = "LeatherJacket_Natural";
                    }
                    else if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherPants_ColorBase") )
                    {
                        item_name = "LeatherPants_Natural";
                    }
                    else if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherMoccasinsShoes_ColorBase") )
                    {
                        item_name = "LeatherMoccasinsShoes_Natural";
                    }
                    else if ( GetGame().IsKindOf (item.GetDisplayName(), "LeatherHat_ColorBase") )
                    {
                        item_name = "LeatherHat_Natural";
                    }
                    if ( item_name != "" )
                    {
                        TurnItemIntoItemLambda lambda = new TurnItemIntoItemLambda(item, item_name, player);
                        lambda.SetTransferParams(true, true, true);
                        player.ServerReplaceItemWithNew(lambda);
                        bleach_amount -= GameConstants.BAREL_BLEACH_PER_CLOTH;
                    }
                }
                else
                {
                    bleach.Delete();
                    break;
                }
            }
        }
        if ( bleach )
        {
            bleach.SetQuantity(bleach_amount);
        }
        if ( item_name != "" )
        {
            Lock(10);
        }
    }
References GameConstants::BAREL_BLEACH_PER_CLOTH, GetGame(), IsKindOf(), and Lock().
Referenced by DetermineAction().
CanDetachAttachment()
override bool Barrel_ColorBase::CanDetachAttachment (EntityAI parent) inline private
Definition at line 536 of file barrel_colorbase.c.
    {
        if ( GetNumberOfItems() == 0)
            return true;
        return false;
    }
References GetNumberOfItems().
CanPutInCargo()
override bool Barrel_ColorBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 501 of file barrel_colorbase.c.
    {
        if ( !super.CanPutInCargo( parent ))
            return false;
        if ( GetNumberOfItems() == 0 && !IsOpen() )
            return true;
        return false;
    }
References GetNumberOfItems(), and IsOpen().
CanPutIntoHands()
override bool Barrel_ColorBase::CanPutIntoHands (EntityAI parent) inline private
Definition at line 512 of file barrel_colorbase.c.
    {
        if ( !super.CanPutIntoHands( parent ))
            return false;
        if ( GetNumberOfItems() == 0 && (GetInventory().IsAttachment() || !IsOpen()) )
            return true;
        return false;
    }
References GetNumberOfItems(), IsAttachment(), and IsOpen().
CanReceiveItemIntoCargo()
override bool Barrel_ColorBase::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 523 of file barrel_colorbase.c.
    {
        if ( IsOpen() )
            return super.CanReceiveItemIntoCargo( item );
        return false;
    }
References IsOpen().
CanReleaseCargo()
override bool Barrel_ColorBase::CanReleaseCargo (EntityAI attachment) inline private
Definition at line 531 of file barrel_colorbase.c.
    {
        return IsOpen();
    }
References IsOpen().
Close()
override void Barrel_ColorBase::Close () inline private
Definition at line 85 of file barrel_colorbase.c.
    {
        m_Openable.Close();
        if (m_RainProcurement.IsRunning())
            m_RainProcurement.StopRainProcurement();
        SoundSynchRemote();
        SetTakeable(true);
        //SetSynchDirty(); //! called also in SoundSynchRemote - TODO
        UpdateVisualState();
    }
References OpenableBehaviour::Close(), RainProcurementManager::IsRunning(), m_Openable, m_RainProcurement, SetTakeable(), SoundSynchRemote(), RainProcurementManager::StopRainProcurement(), and UpdateVisualState().
Referenced by DetermineAction(), and OnWasDetached().
CloseLoad()
void Barrel_ColorBase::CloseLoad () inline private
Definition at line 98 of file barrel_colorbase.c.
    {
        m_Openable.Close();
        if (m_RainProcurement.IsRunning())
            m_RainProcurement.StopRainProcurement();
        SetSynchDirty();
        SetTakeable(true);
        UpdateVisualState();
    }
References OpenableBehaviour::Close(), RainProcurementManager::IsRunning(), m_Openable, m_RainProcurement, SetTakeable(), RainProcurementManager::StopRainProcurement(), and UpdateVisualState().
Referenced by OnStoreLoad().
ColourClothes()
void Barrel_ColorBase::ColourClothes (ItemBase rci, ItemBase gci, ItemBase bci, PlayerBase player) inline private
Definition at line 437 of file barrel_colorbase.c.
    {
        EntityAI item;
        float r = 0;
        float g = 0;
        float b = 0;
        float a = 1; //alpha
        int item_count = GetInventory().GetCargo().GetItemCount();
        bool was_colored = false;
        if ( rci )
        {
            r = rci.GetQuantity()/10;
            r = Math.Clamp(r, 0, 0.78); //TODO adjust clamp as needed, full RGB would result in a white item
        }
        if ( gci )
        {
            g = gci.GetQuantity()/10;
            g = Math.Clamp(g, 0, 0.78);
        }
        if ( bci )
        {
            b = bci.GetQuantity()/10;
            b = Math.Clamp(b, 0, 0.78);
        }
        for (int i = 0; i < item_count; i++)
        {
            item = GetInventory().GetCargo().GetItem(i);
            if ( item.IsClothing() )
            {
                if ( GetGame().ObjectIsKindOf (item, "TShirt_White") || GetGame().ObjectIsKindOf (item, "Armband_White") )
                {
                    ItemBase itemIB = ItemBase.Cast(item);
                    int index = itemIB.GetType().IndexOf("_");
                    string itemtype = itemIB.GetType().Substring( 0, index + 1 );
                    ColourClothesLambda clambda = new ColourClothesLambda(itemIB, itemtype + "Dyed", player, r, g, b, a);
                    clambda.SetTransferParams(true, true, true);
                    MiscGameplayFunctions.TurnItemIntoItemEx(player, clambda);
                    was_colored = true;
                }
            }
        }
        if ( was_colored )
        {
            if ( rci )
            {
                //rci.AddQuantity(-r*10,true,false);
                rci.Delete();
            }
            if ( gci )
            {
                //gci.AddQuantity(-g*10,true,false);
                gci.Delete();
            }
            if ( bci )
            {
                //bci.AddQuantity(-b*10,true,false);
                bci.Delete();
            }
            Lock(30);
        }
    }
References Math::Clamp(), GetGame(), and Lock().
Referenced by DetermineAction().
ColourLeatherClothes()
void Barrel_ColorBase::ColourLeatherClothes (ItemBase color_source, PlayerBase player, string color) inline private
Definition at line 314 of file barrel_colorbase.c.
    {
        EntityAI item;
        int item_count = GetInventory().GetCargo().GetItemCount();
        string item_name = "";
        for (int i = 0; i < item_count; i++)
        {
            item = GetInventory().GetCargo().GetItem(i);
            if ( item.IsClothing() )
            {
                if ( GetGame().ObjectIsKindOf (item, "LeatherSack_Natural") )
                {
                    item_name = "Bag_LeatherSack_"+color;
                }
                else if ( GetGame().ObjectIsKindOf (item, "LeatherStorageVest_Natural") )
                {
                    item_name = "Vest_LeatherStorage_"+color;
                }
                else if ( GetGame().ObjectIsKindOf (item, "LeatherJacket_Natural") )
                {
                    item_name = "Top_LeatherJacket_"+color;
                }
                else if ( GetGame().ObjectIsKindOf (item, "LeatherPants_Natural") )
                {
                    item_name = "Pants_LeatherPants_"+color;
                }
                else if ( GetGame().ObjectIsKindOf (item, "LeatherMoccasinsShoes_Natural") )
                {
                    item_name = "Shoes_LeatherMoccasins_"+color;
                }
                else if ( GetGame().ObjectIsKindOf (item, "LeatherHat_Natural") )
                {
                    item_name = "Hat_Leather_"+color;
                }
                if ( item_name != "" )
                {
                    TurnItemIntoItemLambda lambda = new TurnItemIntoItemLambda(item, item_name, player);
                    lambda.SetTransferParams(true, true, true);
                    player.ServerReplaceItemWithNew(lambda);
                }
            }
        }
        if ( item_name != "" )
        {
            Lock(20);
        }
    }
References GetGame(), and Lock().
Referenced by DetermineAction().
DetermineAction()
void Barrel_ColorBase::DetermineAction (PlayerBase player) inline private
Definition at line 188 of file barrel_colorbase.c.
    {
        int slot_id;
        ItemBase ingredient;
        slot_id = InventorySlots.GetSlotIdFromString("Lime");
        ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
        if ( ingredient && GetQuantity() > 10000 )
        {
            TanPelts(ingredient, player);
        }
        else
        {
            slot_id = InventorySlots.GetSlotIdFromString("Material_Nails");
            ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
            if ( ingredient && GetQuantity() > 10000 )
            {
                ColourLeatherClothes(ingredient, player, "Black");
            }
            else
            {
                slot_id = InventorySlots.GetSlotIdFromString("BirchBark");
                ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                if ( ingredient && GetQuantity() > 10000 )
                {
                    ColourLeatherClothes(ingredient, player, "Beige");
                }
                else
                {
                    slot_id = InventorySlots.GetSlotIdFromString("OakBark");
                    ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                    if ( ingredient && GetQuantity() > 10000 )
                    {
                        ColourLeatherClothes(ingredient, player, "Brown");
                    }
                    else
                    {
                        slot_id = InventorySlots.GetSlotIdFromString("Disinfectant");
                        ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                        if ( ingredient && GetQuantity() > 10000 )
{
                            BleachClothes(ingredient, player);
                        }
                        else
{
                            slot_id = InventorySlots.GetSlotIdFromString("Plant");
                            ingredient = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                            slot_id = InventorySlots.GetSlotIdFromString("Guts");
                            ItemBase reactant = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                            if ( ingredient && reactant && GetQuantity() > 5000 )
{
                                ProduceFertilizer(ingredient,reactant,player);
                            }
                            else
{
                                slot_id = InventorySlots.GetSlotIdFromString("BerryR");
                                ItemBase ingredientR = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                                slot_id = InventorySlots.GetSlotIdFromString("Plant");
                                ItemBase ingredientG = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                                slot_id = InventorySlots.GetSlotIdFromString("BerryB");
                                ItemBase ingredientB = ItemBase.Cast( GetInventory().FindAttachment(slot_id) );
                                if ( (ingredientR || ingredientG || ingredientB) && GetQuantity() > 10000)
{
                                    ColourClothes(ingredientR,ingredientG,ingredientB,player);
                                }
                            }
                        }
                    }
                }
            }
        }
        Close();
    }
References BleachClothes(), Close(), ColourClothes(), ColourLeatherClothes(), FindAttachment(), GetQuantity(), InventorySlots::GetSlotIdFromString(), ProduceFertilizer(), and TanPelts().
Referenced by ActionCloseBarrel::OnExecuteServer().
GetDamageSystemVersionChange()
override int Barrel_ColorBase::GetDamageSystemVersionChange () inline private
Definition at line 23 of file barrel_colorbase.c.
    {
        return 110;
    }
GetLiquidThroughputCoef()
override float Barrel_ColorBase::GetLiquidThroughputCoef () inline private
Definition at line 559 of file barrel_colorbase.c.
    {
        return LIQUID_THROUGHPUT_BARREL;
    }
References LIQUID_THROUGHPUT_BARREL.
GetPlaceSoundset()
override string Barrel_ColorBase::GetPlaceSoundset () inline private
Definition at line 553 of file barrel_colorbase.c.
    {
        return "placeBarrel_SoundSet";
    }
IsLocked()
bool Barrel_ColorBase::IsLocked () inline private
Definition at line 58 of file barrel_colorbase.c.
    {
        return m_IsLocked;
    }
References m_IsLocked.
Referenced by ActionCloseBarrel::ActionCondition(), and ActionOpenBarrel::ActionCondition().
IsOpen()
override bool Barrel_ColorBase::IsOpen () inline private
Definition at line 109 of file barrel_colorbase.c.
    {
        return m_Openable.IsOpened();
    }
References OpenableBehaviour::IsOpened(), and m_Openable.
Referenced by ActionCloseBarrel::ActionCondition(), ActionOpenBarrel::ActionCondition(), CanPutInCargo(), CanPutIntoHands(), CanReceiveItemIntoCargo(), CanReleaseCargo(), Liquid::CanTransfer(), Edible_Base::ConditionAttach(), Edible_Base::ConditionDetach(), OnVariablesSynchronized(), and UpdateVisualState().
Lock()
void Barrel_ColorBase::Lock (float actiontime) inline private
Definition at line 176 of file barrel_colorbase.c.
    {
        m_IsLocked = true;
        m_BarrelOpener.Run(actiontime, this, "Unlock", NULL,false);
    }
References m_BarrelOpener, and m_IsLocked.
Referenced by BleachClothes(), ColourClothes(), ColourLeatherClothes(), ProduceFertilizer(), and TanPelts().
OnPlacementComplete()
override void Barrel_ColorBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 546 of file barrel_colorbase.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        SetIsPlaceSound( true );
    }
References SetIsPlaceSound().
OnStoreLoad()
override bool Barrel_ColorBase::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 35 of file barrel_colorbase.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        bool opened;
        if ( version >= 110 && !ctx.Read( opened ) )
        {
            return false;
        }
        if ( opened )
        {
            OpenLoad();
        }
        else
        {
            CloseLoad();
        }
        return true;
    }
References CloseLoad(), OpenLoad(), and Serializer::Read().
OnStoreSave()
override void Barrel_ColorBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 28 of file barrel_colorbase.c.
    {
        super.OnStoreSave( ctx );
        ctx.Write( m_Openable.IsOpened() );
    }
References OpenableBehaviour::IsOpened(), m_Openable, and Serializer::Write().
OnVariablesSynchronized()
override void Barrel_ColorBase::OnVariablesSynchronized () inline private
Definition at line 142 of file barrel_colorbase.c.
    {
        super.OnVariablesSynchronized();
        if ( IsPlaceSound() )
        {
            PlayPlaceSound();
        }
        else if ( IsSoundSynchRemote() && !IsBeingPlaced() && m_Initialized )
        {
            if ( IsOpen() )
            {
                SoundBarrelOpenPlay();
            }
            else if ( !IsOpen() )
            {
                SoundBarrelClosePlay();
            }
        }
        UpdateVisualState();
    }
References IsBeingPlaced(), IsOpen(), IsPlaceSound(), IsSoundSynchRemote(), m_Initialized, PlayPlaceSound(), SoundBarrelClosePlay(), SoundBarrelOpenPlay(), and UpdateVisualState().
OnWasAttached()
override void Barrel_ColorBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 114 of file barrel_colorbase.c.
    {
        super.OnWasAttached(parent, slot_id);
        Open();
    }
References Open().
OnWasDetached()
override void Barrel_ColorBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 121 of file barrel_colorbase.c.
    {
        super.OnWasDetached(parent, slot_id);
        Close();
    }
References Close().
Open()
override void Barrel_ColorBase::Open () inline private
Definition at line 63 of file barrel_colorbase.c.
    {
        m_Openable.Open();
        m_RainProcurement.InitRainProcurement();
        SoundSynchRemote();
        SetTakeable(false);
        //SetSynchDirty(); //! called also in SoundSynchRemote - TODO
        UpdateVisualState();
    }
References RainProcurementManager::InitRainProcurement(), m_Openable, m_RainProcurement, OpenableBehaviour::Open(), SetTakeable(), SoundSynchRemote(), and UpdateVisualState().
Referenced by ActionOpenBarrel::OnExecuteServer(), OnWasAttached(), and Unlock().
OpenLoad()
void Barrel_ColorBase::OpenLoad () inline private
Definition at line 75 of file barrel_colorbase.c.
    {
        m_Openable.Open();
        m_RainProcurement.InitRainProcurement();
        SetSynchDirty();
        SetTakeable(false);
        UpdateVisualState();
    }
References RainProcurementManager::InitRainProcurement(), m_Openable, m_RainProcurement, OpenableBehaviour::Open(), SetTakeable(), and UpdateVisualState().
Referenced by OnStoreLoad().
ProduceFertilizer()
void Barrel_ColorBase::ProduceFertilizer (ItemBase guts, ItemBase plant, PlayerBase player) inline private
Definition at line 262 of file barrel_colorbase.c.
    {
        float lime_quantity = plant.GetQuantity()*GameConstants.BAREL_LIME_PER_PLANT;
        guts.Delete();
        plant.Delete();
        ItemBase lime = ItemBase.Cast( GetInventory().CreateInInventory("GardenLime") );
        lime.SetQuantity(lime_quantity);
        Lock(50);
    }
References GameConstants::BAREL_LIME_PER_PLANT, CreateInInventory(), and Lock().
Referenced by DetermineAction().
SetActions()
override void Barrel_ColorBase::SetActions () inline private
Definition at line 564 of file barrel_colorbase.c.
    {
        AddAction(ActionAttachOnSelection);
        super.SetActions();
        AddAction(ActionOpenBarrel);
        AddAction(ActionCloseBarrel);
    }
References AddAction().
SoundBarrelClosePlay()
void Barrel_ColorBase::SoundBarrelClosePlay () inline private
Definition at line 170 of file barrel_colorbase.c.
    {
        EffectSound sound = SEffectManager.PlaySound( "barrel_close_SoundSet", GetPosition() );
        sound.SetAutodestroy( true );
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnVariablesSynchronized().
SoundBarrelOpenPlay()
void Barrel_ColorBase::SoundBarrelOpenPlay () inline private
Definition at line 164 of file barrel_colorbase.c.
    {
        EffectSound sound = SEffectManager.PlaySound( "barrel_open_SoundSet", GetPosition() );
        sound.SetAutodestroy( true );
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnVariablesSynchronized().
TanPelts()
void Barrel_ColorBase::TanPelts (ItemBase lime, PlayerBase player) inline private
Definition at line 275 of file barrel_colorbase.c.
    {
        EntityAI item;
        int item_count = GetInventory().GetCargo().GetItemCount();
        int pelt_count = 0;
        int lime_amount = Math.Floor(lime.GetQuantity()/GameConstants.BAREL_LIME_PER_PELT);
        for (int i = 0; i < item_count; i++)
        {
            item = GetInventory().GetCargo().GetItem(i);
            if ( item.IsPeltBase() )
            {
                pelt_count = g_Game.ConfigGetInt("cfgVehicles " + item.GetType() + " peltGain");
                if ( pelt_count <= lime_amount )
                {
                    TanLeatherLambda lambda = new TanLeatherLambda(item, "TannedLeather", player, pelt_count);
                    lambda.SetTransferParams(true, true, true);
                    player.ServerReplaceItemWithNew(lambda);
                    lime_amount -= pelt_count;
                    if ( lime_amount <= 0 )
                    {
                        lime.Delete();
                        break;
                    }
                }
            }
        }
        if ( lime )
        {
            lime.SetQuantity(lime_amount*GameConstants.BAREL_LIME_PER_PELT);
        }
        if ( pelt_count > 0 )
        {
            Lock(30);
        }
    }
References GameConstants::BAREL_LIME_PER_PELT, Math::Floor(), g_Game, and Lock().
Referenced by DetermineAction().
Unlock()
void Barrel_ColorBase::Unlock () inline private
Definition at line 182 of file barrel_colorbase.c.
    {
        m_IsLocked = false;
        Open();
    }
References m_IsLocked, and Open().
UpdateVisualState()
protected void Barrel_ColorBase::UpdateVisualState () inline private
Definition at line 128 of file barrel_colorbase.c.
    {
        if ( IsOpen() )
        {
            SetAnimationPhase("Lid",1);
            SetAnimationPhase("Lid2",0);
        }
        else
        {
            SetAnimationPhase("Lid",0);
            SetAnimationPhase("Lid2",1);
        }
    }
References IsOpen().
Referenced by Close(), CloseLoad(), OnVariablesSynchronized(), Open(), and OpenLoad().
Member Data Documentation
m_BarrelOpener
private ref Timer Barrel_ColorBase::m_BarrelOpener private
Definition at line 4 of file barrel_colorbase.c.
Referenced by Barrel_ColorBase(), and Lock().
m_IsLocked
private bool Barrel_ColorBase::m_IsLocked = false private
Definition at line 3 of file barrel_colorbase.c.
Referenced by IsLocked(), Lock(), and Unlock().
m_Openable
protected ref OpenableBehaviour Barrel_ColorBase::m_Openable private
Definition at line 7 of file barrel_colorbase.c.
Referenced by Barrel_ColorBase(), Close(), CloseLoad(), IsOpen(), OnStoreSave(), Open(), and OpenLoad().
m_RainProcurement
ref RainProcurementManager Barrel_ColorBase::m_RainProcurement private
Definition at line 5 of file barrel_colorbase.c.
Referenced by Barrel_ColorBase(), Close(), CloseLoad(), Open(), and OpenLoad().