DayzKode: KitBase Class Reference
KitBase Class Reference
Private Member Functions
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override bool CanReceiveAttachment (EntityAI attachment, int slotId)
override void DisassembleKit (ItemBase item)
override void DisassembleKit (ItemBase item)
override void DisassembleKit (ItemBase item)
override void DisassembleKit (ItemBase item)
override bool DoPlacingHeightCheck ()
override bool DoPlacingHeightCheck ()
override bool DoPlacingHeightCheck ()
override bool DoPlacingHeightCheck ()
override string GetDeployFinishSoundset ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override float HeightCheckOverride ()
override float HeightCheckOverride ()
override float HeightCheckOverride ()
override float HeightCheckOverride ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnDebugSpawn ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool PlacementCanBeRotated ()
Detailed Description
Definition at line 1 of file fencekit.c.
Member Function Documentation
CanReceiveAttachment() [1/4]
override bool KitBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file fencekit.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        ItemBase att = ItemBase.Cast(GetInventory().FindAttachment(slotId));
        if (att)
            return false;
        return true;
    }
References FindAttachment().
CanReceiveAttachment() [2/4]
override bool KitBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file shelterkit.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        ItemBase att = ItemBase.Cast(GetInventory().FindAttachment(slotId));
        if (att)
            return false;
        return true;
    }
References FindAttachment().
CanReceiveAttachment() [3/4]
override bool KitBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 18 of file totemkit.c.
    {
        if ( !super.CanReceiveAttachment(attachment, slotId) )
            return false;
        ItemBase att = ItemBase.Cast(GetInventory().FindAttachment(slotId));
        if (att)
            return false;
        return true;
    }
References FindAttachment().
CanReceiveAttachment() [4/4]
override bool KitBase::CanReceiveAttachment (EntityAI attachment, int slotId) inline private
Definition at line 3 of file watchtowerkit.c.
    {
        ItemBase att = ItemBase.Cast(GetInventory().FindAttachment(slotId));
        if (att)
            return false;
        return super.CanReceiveAttachment(attachment, slotId);
    }
References ItemBase::CanReceiveAttachment(), and FindAttachment().
DisassembleKit() [1/4]
override void KitBase::DisassembleKit (ItemBase item) inline private
Definition at line 48 of file fencekit.c.
    {
        if (!IsHologram())
        {
            ItemBase stick = ItemBase.Cast(GetGame().CreateObjectEx("WoodenStick",GetPosition(),ECE_PLACE_ON_SURFACE));
            MiscGameplayFunctions.TransferItemProperties(this, stick);
            stick.SetQuantity(2);
            Rope rope = Rope.Cast(item);
            CreateRope(rope);
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
Referenced by ItemBase::EEItemDetached().
DisassembleKit() [2/4]
override void KitBase::DisassembleKit (ItemBase item) inline private
Definition at line 61 of file shelterkit.c.
    {
        if (!IsHologram())
        {
            ItemBase stick = ItemBase.Cast(GetGame().CreateObjectEx("WoodenStick",GetPosition(),ECE_PLACE_ON_SURFACE));
            MiscGameplayFunctions.TransferItemProperties(this, stick);
            stick.SetQuantity(4);
            Rope rope = Rope.Cast(item);
            CreateRope(rope);
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DisassembleKit() [3/4]
override void KitBase::DisassembleKit (ItemBase item) inline private
Definition at line 52 of file totemkit.c.
    {
        if (!IsHologram())
        {
            ItemBase stick = ItemBase.Cast(GetGame().CreateObjectEx("WoodenStick",GetPosition(),ECE_PLACE_ON_SURFACE));
            MiscGameplayFunctions.TransferItemProperties(this, stick);
            stick.SetQuantity(3);
            Rope rope = Rope.Cast(item);
            CreateRope(rope);
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DisassembleKit() [4/4]
override void KitBase::DisassembleKit (ItemBase item) inline private
Definition at line 44 of file watchtowerkit.c.
    {
        if (!IsHologram())
        {
            ItemBase stick = ItemBase.Cast(GetGame().CreateObjectEx("WoodenStick",GetPosition(),ECE_PLACE_ON_SURFACE));
            MiscGameplayFunctions.TransferItemProperties(this, stick);
            stick.SetQuantity(4);
            Rope rope = Rope.Cast(item);
            CreateRope(rope);
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and IsHologram().
DoPlacingHeightCheck() [1/4]
override bool KitBase::DoPlacingHeightCheck () inline private
Definition at line 38 of file fencekit.c.
    {
        return true;
    }
DoPlacingHeightCheck() [2/4]
override bool KitBase::DoPlacingHeightCheck () inline private
Definition at line 36 of file shelterkit.c.
    {
        return true;
    }
DoPlacingHeightCheck() [3/4]
override bool KitBase::DoPlacingHeightCheck () inline private
Definition at line 8 of file totemkit.c.
    {
        return true;
    }
DoPlacingHeightCheck() [4/4]
override bool KitBase::DoPlacingHeightCheck () inline private
Definition at line 34 of file watchtowerkit.c.
    {
        return true;
    }
GetDeployFinishSoundset()
override string KitBase::GetDeployFinishSoundset () inline private
Definition at line 56 of file shelterkit.c.
    {
        return "Shelter_Site_Build_Finish_SoundSet";
    }
GetDeploySoundset()
override string KitBase::GetDeploySoundset () inline private
Definition at line 46 of file shelterkit.c.
    {
        return "Shelter_Site_Build_Start_SoundSet";
    }
GetLoopDeploySoundset()
override string KitBase::GetLoopDeploySoundset () inline private
Definition at line 51 of file shelterkit.c.
    {
        return "Shelter_Site_Build_Loop_SoundSet";
    }
Referenced by ItemBase::PlayDeployLoopSound().
HeightCheckOverride() [1/4]
override float KitBase::HeightCheckOverride () inline private
Definition at line 43 of file fencekit.c.
    {
        return 2.54;
    }
HeightCheckOverride() [2/4]
override float KitBase::HeightCheckOverride () inline private
Definition at line 41 of file shelterkit.c.
    {
        return 1.6;
    }
HeightCheckOverride() [3/4]
override float KitBase::HeightCheckOverride () inline private
Definition at line 13 of file totemkit.c.
    {
        return 11.3;
    }
HeightCheckOverride() [4/4]
override float KitBase::HeightCheckOverride () inline private
Definition at line 39 of file watchtowerkit.c.
    {
        return 2.83;//9.56;
    }
OnDebugSpawn() [1/4]
override void KitBase::OnDebugSpawn () inline private
Definition at line 61 of file fencekit.c.
    {
        SpawnEntityOnGroundPos("Shovel", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Pliers", GetPosition());
        SpawnEntityOnGroundPos("WoodenLog", GetPosition());
        SpawnEntityOnGroundPos("WoodenLog", GetPosition());
        SpawnEntityOnGroundPos("Nail", GetPosition());
        SpawnEntityOnGroundPos("CamoNet", GetPosition());
        SpawnEntityOnGroundPos("BarbedWire", GetPosition());
        SpawnEntityOnGroundPos("BarbedWire", GetPosition());
        SpawnEntityOnGroundPos("MetalWire", GetPosition());
        SpawnEntityOnGroundPos("CombinationLock", GetPosition());
        SpawnEntityOnGroundPos("WoodenPlank", GetPosition());
        SpawnEntityOnGroundPos("WoodenPlank", GetPosition());
        SpawnEntityOnGroundPos("WoodenPlank", GetPosition());
        SpawnEntityOnGroundPos("WoodenPlank", GetPosition());
    }
References GetPosition.
OnDebugSpawn() [2/4]
override void KitBase::OnDebugSpawn () inline private
Definition at line 74 of file shelterkit.c.
    {
        SpawnEntityOnGroundPos("Shovel", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Pliers", GetPosition());
        for (int i0 = 0; i0 < 4; ++i0)
        {
            SpawnEntityOnGroundPos("LongWoodenStick", GetPosition());
        }
        for (int i1 = 0; i1 < 8; ++i1)
        {
            SpawnEntityOnGroundPos("TannedLeather", GetPosition());
        }
        for (int i2 = 0; i2 < 4; ++i2)
        {
            SpawnEntityOnGroundPos("Fabric", GetPosition());
        }
        for (int i3 = 0; i3 < 50; ++i3)
        {
            SpawnEntityOnGroundPos("WoodenStick", GetPosition());
        }
    }
References GetPosition.
OnDebugSpawn() [3/4]
override void KitBase::OnDebugSpawn () inline private
Definition at line 68 of file totemkit.c.
    {
        SpawnEntityOnGroundPos("SledgeHammer", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Shovel", GetPosition());
        Nail nails = Nail.Cast(SpawnEntityOnGroundPos("Nail", GetPosition()));
        nails.SetQuantity(60);
        SpawnEntityOnGroundPos("Rope", GetPosition());
        SpawnEntityOnGroundPos("MetalWire", GetPosition());
        SpawnEntityOnGroundPos("Flag_DayZ", GetPosition());
        for (int i0 = 0; i0 < 32; i0++)
        {
            SpawnEntityOnGroundPos("Stone", GetPosition());
        }
        for (int i1 = 0; i1 < 10; i1++)
        {
            SpawnEntityOnGroundPos("WoodenLog", GetPosition());
        }
    }
References GetPosition.
OnDebugSpawn() [4/4]
override void KitBase::OnDebugSpawn () inline private
Definition at line 57 of file watchtowerkit.c.
    {
        SpawnEntityOnGroundPos("Shovel", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Hammer", GetPosition());
        SpawnEntityOnGroundPos("Pliers", GetPosition());
        for (int i0 = 0; i0 < 30; i0++)
        {
            SpawnEntityOnGroundPos("WoodenPlank", GetPosition());
        }
        for (int i1 = 0; i1 < 10; i1++)
        {
            SpawnEntityOnGroundPos("WoodenLog", GetPosition());
        }
        for (int i2 = 0; i2 < 15; i2++)
        {
            SpawnEntityOnGroundPos("Nail", GetPosition());
        }
        for (int i3 = 0; i3 < 9; i3++)
        {
            SpawnEntityOnGroundPos("CamoNet", GetPosition());
        }
        for (int i4 = 0; i4 < 6; i4++)
        {
            SpawnEntityOnGroundPos("BarbedWire", GetPosition());
        }
    }
References GetPosition.
OnPlacementComplete() [1/4]
override void KitBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 19 of file fencekit.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            //Create fence
            Fence fence = Fence.Cast( GetGame().CreateObjectEx( "Fence", GetPosition(), ECE_PLACE_ON_SURFACE ) );
            fence.SetPosition( position );
            fence.SetOrientation( orientation );
            //make the kit invisible, so it can be destroyed from deploy UA when action ends
            HideAllSelections();
            SetIsDeploySound( true );
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [2/4]
override void KitBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 18 of file shelterkit.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            //Create shelter site
            ShelterSite site = ShelterSite.Cast( GetGame().CreateObjectEx( "ShelterSite", GetPosition(), ECE_PLACE_ON_SURFACE ) );
            site.SetPosition( position );
            site.SetOrientation( orientation );
            //make the kit invisible, so it can be destroyed from deploy UA when action ends
            HideAllSelections();
            SetIsDeploySound( true );
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [3/4]
override void KitBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 34 of file totemkit.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            //Create TerritoryFlag
            TerritoryFlag totem = TerritoryFlag.Cast( GetGame().CreateObjectEx( "TerritoryFlag", GetPosition(), ECE_PLACE_ON_SURFACE ) );
            totem.SetPosition( position );
            totem.SetOrientation( orientation );
            //make the kit invisible, so it can be destroyed from deploy UA when action ends
            HideAllSelections();
            SetIsDeploySound( true );
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
OnPlacementComplete() [4/4]
override void KitBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 16 of file watchtowerkit.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            //Create watchtower
            Watchtower watchtower = Watchtower.Cast( GetGame().CreateObjectEx( "Watchtower", GetPosition(), ECE_PLACE_ON_SURFACE ) );
            watchtower.SetPosition( position );
            watchtower.SetOrientation( orientation );
            //make the kit invisible, so it can be destroyed from deploy UA when action ends
            HideAllSelections();
            SetIsDeploySound( true );
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), GetPosition, and SetIsDeploySound().
PlacementCanBeRotated()
override bool KitBase::PlacementCanBeRotated () inline private
Definition at line 3 of file totemkit.c.
    {
        return false;
    }