DayzKode: DayZPlayerImplementSwimming Class Reference
DayZPlayerImplementSwimming Class Reference
Private Member Functions
bool CheckSwimmingStart (out vector waterLevel)
void DayZPlayerImplementSwimming (DayZPlayer pPlayer)
float GetCharacterDepth ()
float GetWaterDepth ()
bool HandleSwimming (int pCurrentCommandID, HumanCommandMove pCMove, HumanMovementState pState)
ha
Private Attributes
bool m_bWasSwimming = false
DayZPlayer m_pPlayer
SHumanCommandSwimSettings m_pSettings
Detailed Description
Definition at line 2 of file dayzplayerimplementswimming.c.
Constructor & Destructor Documentation
DayZPlayerImplementSwimming()
void DayZPlayerImplementSwimming::DayZPlayerImplementSwimming (DayZPlayer pPlayer) inline private
Definition at line 9 of file dayzplayerimplementswimming.c.
    {
        m_pPlayer   = pPlayer;
        m_pSettings = pPlayer.GetDayZPlayerType().CommandSwimSettingsW();
    }
References m_pPlayer, and m_pSettings.
Member Function Documentation
CheckSwimmingStart()
bool DayZPlayerImplementSwimming::CheckSwimmingStart (out vector waterLevel) inline private
Definition at line 31 of file dayzplayerimplementswimming.c.
    {
        return DayZPlayerUtils.CheckWaterLevel(m_pPlayer,waterLevel) == EWaterLevels.LEVEL_SWIM_START;
    }
References DayZPlayerUtils::CheckWaterLevel(), and m_pPlayer.
Referenced by HandleSwimming().
GetCharacterDepth()
float DayZPlayerImplementSwimming::GetCharacterDepth () inline private
Definition at line 23 of file dayzplayerimplementswimming.c.
    {
        vector  pp = m_pPlayer.GetPosition();
        vector  wl = HumanCommandSwim.WaterLevelCheck(m_pPlayer, pp);
        return wl[1];
    }
References HumanCommandSwim(), and m_pPlayer.
GetWaterDepth()
float DayZPlayerImplementSwimming::GetWaterDepth () inline private
Definition at line 15 of file dayzplayerimplementswimming.c.
    {
        vector  pp = m_pPlayer.GetPosition();
        vector  wl = HumanCommandSwim.WaterLevelCheck(m_pPlayer, pp);
        return wl[0];
    }
References HumanCommandSwim(), and m_pPlayer.
Referenced by HandleSwimming().
HandleSwimming()
bool DayZPlayerImplementSwimming::HandleSwimming (int pCurrentCommandID, HumanCommandMove pCMove, HumanMovementState pState) inline private
ha
get water level
now movement
handled !
Definition at line 37 of file dayzplayerimplementswimming.c.
    {
        if ( pCurrentCommandID == DayZPlayerConstants.COMMANDID_UNCONSCIOUS || pCurrentCommandID == DayZPlayerConstants.COMMANDID_DAMAGE )
            return false;
        m_bWasSwimming = false;
        if (pCurrentCommandID != DayZPlayerConstants.COMMANDID_SWIM)
        {
            vector wl;
            if ( CheckSwimmingStart(wl) )
            {
                m_pPlayer.StartCommand_Swim();
                m_bWasSwimming = true;
                return true;
            }
            if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_MOVE)
            {
                pCMove.SetCurrentWaterLevel(wl[1]);
                if (wl[1] > m_pSettings.m_fToErectLevel && pState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_ERECT && pState.m_iStanceIdx != DayZPlayerConstants.STANCEIDX_RAISEDERECT )
                {
                    if ( DayZPlayerUtils.PlayerCanChangeStance(m_pPlayer, DayZPlayerConstants.STANCEIDX_ERECT) )
                    {
                        pCMove.ForceStanceUp(DayZPlayerConstants.STANCEIDX_ERECT);
                    }
                    else
                    {
                        m_pPlayer.StartCommand_Swim();
                        m_bWasSwimming = true;
                        return true;
                    }
                }
                else if (wl[1] > m_pSettings.m_fToCrouchLevel && (pState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || pState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE))
                {
                    if ( DayZPlayerUtils.PlayerCanChangeStance(m_pPlayer, DayZPlayerConstants.STANCEIDX_CROUCH) )
                    {
                        pCMove.ForceStanceUp(DayZPlayerConstants.STANCEIDX_CROUCH);
                    }
                    else
                    {
                        m_pPlayer.StartCommand_Swim();
                        m_bWasSwimming = true;
                        return true;
                    }
                }
            }
            // not handled
            return false;
        }
        else // if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_SWIM)
        {
            if (GetWaterDepth() < m_pSettings.m_fWaterLevelOut)
            {
                if (DayZPlayerUtils.PlayerCanChangeStance(m_pPlayer, DayZPlayerConstants.STANCEIDX_ERECT, true))
                {
                    HumanCommandSwim hcs = m_pPlayer.GetCommand_Swim();
                    hcs.StopSwimming();
                    m_bWasSwimming = false;
                    return true;
                }
            }
            m_bWasSwimming = true;
            return true;
        }
    }
References CheckSwimmingStart(), HumanCommandMove::ForceStanceUp(), GetWaterDepth(), HumanCommandSwim(), m_bWasSwimming, SHumanCommandSwimSettings::m_fToCrouchLevel, SHumanCommandSwimSettings::m_fToErectLevel, SHumanCommandSwimSettings::m_fWaterLevelOut, HumanMovementState::m_iStanceIdx, m_pPlayer, m_pSettings, DayZPlayerUtils::PlayerCanChangeStance(), and HumanCommandMove::SetCurrentWaterLevel().
Referenced by CommandHandler().
Member Data Documentation
m_bWasSwimming
bool DayZPlayerImplementSwimming::m_bWasSwimming = false private
Definition at line 7 of file dayzplayerimplementswimming.c.
Referenced by CommandHandler(), and HandleSwimming().
m_pPlayer
DayZPlayer DayZPlayerImplementSwimming::m_pPlayer private
Definition at line 5 of file dayzplayerimplementswimming.c.
Referenced by CheckSwimmingStart(), DayZPlayerImplementSwimming(), GetCharacterDepth(), GetWaterDepth(), and HandleSwimming().
m_pSettings
SHumanCommandSwimSettings DayZPlayerImplementSwimming::m_pSettings private
Definition at line 6 of file dayzplayerimplementswimming.c.
Referenced by DayZPlayerImplementSwimming(), and HandleSwimming().