DayzKode: DayZPlayerCameraBase Class Reference
DayZPlayerCameraBase Class Reference
this is main camera class
Private Member Functions
void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult)
void DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput)
void DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput)
override vector GetBaseAngles ()
override vector GetBaseAngles ()
override vector GetBaseAngles ()
override string GetCameraName ()
override string GetCameraName ()
override string GetCameraName ()
EntityAI GetCurrentSightEntity ()
bool GetCurrentSightInfo (out vector camPos, out vector camDir)
float HoldBreathFOVEffect (float pDt)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
void SetupSightEntities ()
void UpdateBatteryOptics (EntityAI entity)
Private Attributes
protected bool m_bShoulderInLS
true - shoulder is in local space
protected vector m_CameraOffsetLS
local space offset
protected vector m_CameraOffsetMS
model space offset
float m_dynamicsSmoothTime
float m_dynamicsStrength
protected float m_fCameraLRShoulder
shoulder offsets
protected float m_fCameraLRShoulderVel [1]
protected float m_fDistance
distance from start
protected float m_fLeanDistance
shift on leaning
protected float m_fLeftRightAngle
left right angle in rad (in freelook only)
protected float m_fRoll
camera roll
protected float m_fShootFromCamera = 0.0
settings
protected float m_fShoulderWidth
shoulder camera widths
protected float m_fUpDownAngle
up down angle in rad
protected float m_fUpDownAngleAdd
up down angle in rad
protected int m_iBoneIndex = -1
main bone
protected bool m_isEntering = false
float m_movementAmplitudeX
float m_movementAmplitudeY
float m_movementFrequencyX
float m_movementFrequencyY
ref HumanMovementState m_MovementState = new HumanMovementState()
movement state
float m_movementTimeAcc
protected vector m_OffsetLS
position offset
protected vector m_OpticsCamDir
protected vector m_OpticsCamPos
protected bool m_opticsHasWeaponOverride = false
protected PPERequester_CameraADS m_RequesterADS
vector m_SightMisalignmentModifier
float m_velocityPitch [1]
float m_velocityYaw [1]
camera dynamics
protected ref array< float > temp_array
Static Private Attributes
static const float CONST_LR_MAX = 160.0
up limit
static const float CONST_LR_MIN = -160.0
down limit
static const float CONST_UD_MAX = 85.0
up limit
static const float CONST_UD_MIN = -85.0
down limit
static const float CONST_UD_MIN_BACK = -25.0
down limit on back
Detailed Description
this is main camera class
Definition at line 4 of file dayzplayercamera1stperson.c.
Member Function Documentation
AdjustCameraParameters()
void DayZPlayerCameraBase::AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult) inline private
Definition at line 198 of file dayzplayercameraironsights.c.
    {
        pOutResult.m_iDirectBone            = m_iBoneIndex;
        pOutResult.m_iDirectBoneMode        = 4;
        pOutResult.m_fFovAbsolute = HoldBreathFOVEffect(pDt);
        pOutResult.m_bUpdateWhenBlendOut    = false;
        pOutResult.m_fDistance              = 0;
        pOutResult.m_fUseHeading            = 0;
        pOutResult.m_fInsideCamera          = 1.0;
        pOutResult.m_fShootFromCamera       = m_fShootFromCamera;
        pOutResult.m_fNearPlane = 0.04; //0.07 default
    }
References HoldBreathFOVEffect(), m_fShootFromCamera, and m_iBoneIndex.
Referenced by OnUpdate().
DayZPlayerCamera1stPerson()
void DayZPlayerCameraBase::DayZPlayerCamera1stPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 13 of file dayzplayercamera1stperson.c.
    {
        m_iBoneIndex = pPlayer.GetBoneIndexByName("Head");
        if (m_iBoneIndex == -1)
        {
            Print("DayZPlayerCamera1stPerson: main bone not found");
        }
        m_OffsetLS = "0.04 0.04 0"; //x - up, y - forward
    }
References m_iBoneIndex, m_OffsetLS, and Print().
DayZPlayerCamera3rdPerson()
void DayZPlayerCameraBase::DayZPlayerCamera3rdPerson (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 13 of file dayzplayercamera3rdperson.c.
    {
        if (pInput.Camera3rdIsRightShoulder())
        {
            m_fCameraLRShoulder     = 1.0;
        }
        else
        {
            m_fCameraLRShoulder     = -1.0;
        }
        m_fCameraLRShoulderVel[0]   = 0.0;
        m_fRoll                     = 0.0;
        m_WeaponSwayModifier        = 1;
        m_fLeanDistance             = 0.3;
    }
References HumanInputController::Camera3rdIsRightShoulder(), m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fLeanDistance, m_fRoll, and m_WeaponSwayModifier.
DayZPlayerCameraIronsights()
void DayZPlayerCameraBase::DayZPlayerCameraIronsights (DayZPlayer pPlayer, HumanInputController pInput) inline private
Definition at line 32 of file dayzplayercameraironsights.c.
    {
        if (!temp_array)
            temp_array = new array<float>;
        m_iBoneIndex = pPlayer.GetBoneIndexByName("RightHand_Dummy");
        if (m_iBoneIndex == -1)
        {
            Print("DayZPlayerCamera1stPerson: main bone not found");
        }
        m_dynamicsStrength = 2;
        m_dynamicsSmoothTime = 0.3;
        SetupSightEntities();
        GetCurrentSightInfo(m_OpticsCamPos, m_OpticsCamDir);
        m_isEntering = true;
        m_WeaponSwayModifier = 0.5;
        m_movementTimeAcc = 0;
        m_movementAmplitudeX = 1;
        m_movementAmplitudeY = 1;
        m_movementFrequencyX = 1;
        m_movementFrequencyY = 2;
        Class.CastTo(m_RequesterADS,PPERequester_CameraADS.Cast(PPERequesterBank.GetRequester(PPERequester_CameraADS)));
        Init();
    }
References Class::CastTo(), GetCurrentSightInfo(), Init(), m_iBoneIndex, m_WeaponSwayModifier, Print(), and SetupSightEntities().
GetBaseAngles() [1/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline private
Definition at line 72 of file dayzplayercamera1stperson.c.
    {
        vector a;
        a[0] = m_fUpDownAngle;
        a[1] = m_fLeftRightAngle;
        a[2] = m_fUpDownAngleAdd;
        return a;
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
GetBaseAngles() [2/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline private
Definition at line 115 of file dayzplayercamera3rdperson.c.
    {
        vector a;
        a[0] = m_fUpDownAngle;
        a[1] = m_fLeftRightAngle;
        a[2] = m_fUpDownAngleAdd;
        return a;
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
GetBaseAngles() [3/3]
override vector DayZPlayerCameraBase::GetBaseAngles () inline private
Definition at line 189 of file dayzplayercameraironsights.c.
    {
        vector a;
        a[0] = m_fUpDownAngle;
        a[1] = m_fLeftRightAngle;
        a[2] = m_fUpDownAngleAdd;
        return a;
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
GetCameraName() [1/3]
override string DayZPlayerCameraBase::GetCameraName () inline private
Definition at line 81 of file dayzplayercamera1stperson.c.
    {
        return "DayZPlayerCamera1stPerson";
    }
GetCameraName() [2/3]
override string DayZPlayerCameraBase::GetCameraName () inline private
Definition at line 124 of file dayzplayercamera3rdperson.c.
    {
        return "DayZPlayerCamera3rdPerson";
    }
GetCameraName() [3/3]
override string DayZPlayerCameraBase::GetCameraName () inline private
Definition at line 293 of file dayzplayercameraironsights.c.
    {
        return "DayZPlayerCameraIronsights";
    }
GetCurrentSightEntity()
EntityAI DayZPlayerCameraBase::GetCurrentSightEntity () inline private
Definition at line 96 of file dayzplayercameraironsights.c.
    {
        if( m_opticsHasWeaponOverride )
            return m_opticsUsed;
        return m_weaponUsed;
    }
References m_opticsUsed, and m_weaponUsed.
Referenced by GetCurrentSightInfo(), and OnUpdate().
GetCurrentSightInfo()
bool DayZPlayerCameraBase::GetCurrentSightInfo (out vector camPos, out vector camDir) inline private
Definition at line 104 of file dayzplayercameraironsights.c.
    {
        EntityAI e = GetCurrentSightEntity();
        if( e == m_weaponUsed )
        {
            m_weaponUsed.GetCameraPoint(m_weaponUsed.GetCurrentMuzzle(), camPos, camDir);
            return true;
        }
        else if( e == m_opticsUsed )
        {
            m_opticsUsed.UseWeaponIronsightsOverride(m_opticsHasWeaponOverride);
            m_opticsUsed.GetCameraPoint(camPos, camDir);
            return true;
        }
        return false;
    }
References GetCurrentSightEntity(), m_opticsUsed, and m_weaponUsed.
Referenced by DayZPlayerCameraIronsights().
HoldBreathFOVEffect()
float DayZPlayerCameraBase::HoldBreathFOVEffect (float pDt) inline private
Definition at line 214 of file dayzplayercameraironsights.c.
    {
        if (m_pPlayer.IsHoldingBreath())
        {
            m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM, m_fFovAbsVel, 0.1, 1000, pDt);
        }
        else if (m_isEntering) //sets FOV immediatelly to avoid "floating camera" effect
        {
            m_fFovAbsolute = GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS;
            m_isEntering = false;
        }
        else
        {
            m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GameConstants.DZPLAYER_CAMERA_FOV_IRONSIGHTS, m_fFovAbsVel, 0.1, 1000, pDt);
        }
        return m_fFovAbsolute;
    }
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GameConstants::DZPLAYER_CAMERA_FOV_IRONSIGHTS, m_fFovAbsolute, m_fFovAbsVel, m_pPlayer, and Math::SmoothCD().
Referenced by AdjustCameraParameters().
OnActivate() [1/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 26 of file dayzplayercamera1stperson.c.
    {
        super.OnActivate(pPrevCamera, pPrevCameraResult);
        if (pPrevCamera)
        {
            vector  f = pPrevCamera.GetBaseAngles();
            m_fUpDownAngle      = f[0];
            m_fLeftRightAngle   = f[1];
            m_fUpDownAngleAdd   = f[2];
        }
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [2/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 32 of file dayzplayercamera3rdperson.c.
    {
        super.OnActivate(pPrevCamera, pPrevCameraResult);
        if (pPrevCamera)
        {
            vector  f = pPrevCamera.GetBaseAngles();
            m_fUpDownAngle      = f[0];
            m_fLeftRightAngle   = f[1];
            m_fUpDownAngleAdd   = f[2];
        }
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnActivate() [3/3]
override void DayZPlayerCameraBase::OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult) inline private
Definition at line 87 of file dayzplayercameraironsights.c.
    {
        super.OnActivate(pPrevCamera,pPrevCameraResult);
        vector  f = pPrevCamera.GetBaseAngles();
        m_fUpDownAngle      = f[0];
        m_fLeftRightAngle   = f[1];
        m_fUpDownAngleAdd   = f[2];
    }
References m_fLeftRightAngle, m_fUpDownAngle, and m_fUpDownAngleAdd.
OnUpdate() [1/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Definition at line 39 of file dayzplayercamera1stperson.c.
    {
        float   udAngle     = UpdateUDAngle(m_fUpDownAngle, m_fUpDownAngleAdd, CONST_UD_MIN, CONST_UD_MAX, pDt);
        m_CurrentCameraPitch = udAngle;
        m_fLeftRightAngle   = UpdateLRAngle(m_fLeftRightAngle, CONST_LR_MIN, CONST_LR_MAX, pDt);
        vector rot;
        rot[0] = m_fLeftRightAngle;
        rot[1] = udAngle;
        rot[2] = 0;
        Math3D.YawPitchRollMatrix(rot, pOutResult.m_CameraTM);
        pOutResult.m_CameraTM[3]        = m_OffsetLS;
        pOutResult.m_iDirectBone        = m_iBoneIndex;
        pOutResult.m_iDirectBoneMode    = 1;
        pOutResult.m_fUseHeading        = 1.0;
        pOutResult.m_fInsideCamera      = 1.0;
        pOutResult.m_fNearPlane = 0.04; //0.07 default
        ProcessCameraShake(pDt, m_fLeftRightAngle, m_fUpDownAngleAdd);
        InitCameraOnPlayer();
        StdFovUpdate(pDt, pOutResult);
        UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
    }
References CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, InitCameraOnPlayer(), m_CurrentCameraPitch, m_fLeftRightAngle, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_OffsetLS, m_pPlayer, ProcessCameraShake(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngle(), UpdateUDAngle(), and Math3D::YawPitchRollMatrix().
OnUpdate() [2/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Print(m_fLeftRightAngle);
base bone pos
apply shoulder dist
store distance
Definition at line 46 of file dayzplayercamera3rdperson.c.
    {
        m_pPlayer.GetMovementState(m_MovementState);
        float   udAngle     = UpdateUDAngle(m_fUpDownAngle, m_fUpDownAngleAdd, CONST_UD_MIN, CONST_UD_MAX, pDt);
        m_CurrentCameraPitch = udAngle;
        m_fLeftRightAngle   = UpdateLRAngle(m_fLeftRightAngle, CONST_LR_MIN, CONST_LR_MAX, pDt);
        ProcessCameraShake(pDt, m_fLeftRightAngle, m_fUpDownAngleAdd);
        // update l/r offsets and set it as
        if (m_pInput.Camera3rdIsRightShoulder())
        {
            m_fCameraLRShoulder = Math.SmoothCD(m_fCameraLRShoulder, 1.0, m_fCameraLRShoulderVel, 0.14, 1000, pDt);
        }
        else
        {
            m_fCameraLRShoulder = Math.SmoothCD(m_fCameraLRShoulder, -1.0, m_fCameraLRShoulderVel, 0.14, 1000, pDt);
        }
        float   shoulderDist = m_fCameraLRShoulder * m_fShoulderWidth + m_MovementState.m_fLeaning * m_fLeanDistance;
        vector rot;
        rot[0] = m_fLeftRightAngle;
        rot[1] = udAngle;
        rot[2] = m_fRoll;
        Math3D.YawPitchRollMatrix(rot, pOutResult.m_CameraTM);
        if (m_iBoneIndex != -1)
        {
            pOutResult.m_CameraTM[3]    = m_pPlayer.GetBonePositionMS(m_iBoneIndex);
        }
        else
        {
            pOutResult.m_CameraTM[3]    = "0 0 0";
        }
        vector msOffset = m_CameraOffsetMS;
        vector lsOffset = m_CameraOffsetLS;
        if (m_bShoulderInLS)
        {
            lsOffset[0] = lsOffset[0] + shoulderDist;
        }
        else
        {
            msOffset[0] = msOffset[0] + shoulderDist;
        }
        // ls offset + ms offset + shoulder width
        pOutResult.m_CameraTM[3]    = pOutResult.m_CameraTM[3] + pOutResult.m_CameraTM[0] * lsOffset[0] + pOutResult.m_CameraTM[1] * lsOffset[1] + pOutResult.m_CameraTM[2] * lsOffset[2] + msOffset;
        pOutResult.m_fDistance      = m_fDistance;
        pOutResult.m_fUseHeading    = 1.0;
        pOutResult.m_fInsideCamera  = 0.0;
        InitCameraOnPlayer();
        StdFovUpdate(pDt, pOutResult);
        UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
    }
References HumanInputController::Camera3rdIsRightShoulder(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, InitCameraOnPlayer(), m_bShoulderInLS, m_CameraOffsetLS, m_CameraOffsetMS, m_CurrentCameraPitch, m_fCameraLRShoulder, m_fCameraLRShoulderVel, m_fDistance, m_fLeanDistance, m_fLeftRightAngle, m_fLeftRightAngle, m_fRoll, m_fShoulderWidth, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_MovementState, m_pInput, m_pPlayer, ProcessCameraShake(), Math::SmoothCD(), StdFovUpdate(), UpdateCameraNV(), UpdateLRAngle(), UpdateUDAngle(), and Math3D::YawPitchRollMatrix().
OnUpdate() [3/3]
override void DayZPlayerCameraBase::OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult) inline private
update angles from input
Definition at line 122 of file dayzplayercameraironsights.c.
    {
        float min;
        DayZPlayerImplement player = DayZPlayerImplement.Cast(GetGame().GetPlayer());
        if (player && player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_RAISEDPRONE))
            min = CONST_UD_MIN_BACK;
        else
            min = CONST_UD_MIN;
        float   udAngle     = UpdateUDAngle(m_fUpDownAngle, m_fUpDownAngleAdd, min, CONST_UD_MAX, pDt);
        m_CurrentCameraPitch = udAngle;
        m_fLeftRightAngle   = UpdateLRAngle(m_fLeftRightAngle, CONST_LR_MIN, CONST_LR_MAX, pDt);
        // get model space transform matrix of the gun's eye vector
        vector matTM[4];
        HumanItemAccessor hia = m_pPlayer.GetItemAccessor();
        if(GetCurrentSightEntity())
            hia.WeaponGetCameraPointBoneRelative(GetCurrentSightEntity(), m_OpticsCamPos, m_OpticsCamDir, m_iBoneIndex, matTM);
        // aim change based on character movement
        vector aimChangeYPR;
        float aimChangeX = m_pInput.GetAimChange()[0] * Math.RAD2DEG;
        float aimChangeY = m_pInput.GetAimChange()[1] * Math.RAD2DEG;
        HumanCommandMove hcm = m_pPlayer.GetCommand_Move();
        if( hcm )
        {
            float speed = hcm.GetCurrentMovementSpeed();
            if( speed > 0 )
                m_movementTimeAcc += pDt;
            else
                m_movementTimeAcc = 0;
            aimChangeX += m_movementAmplitudeX * speed * Math.Sin(Math.PI2 * m_movementFrequencyX * m_movementTimeAcc);
            aimChangeY += m_movementAmplitudeY * speed * Math.Sin(Math.PI2 * m_movementFrequencyY * m_movementTimeAcc);
        }
        aimChangeYPR[0] = Math.SmoothCD(aimChangeYPR[0], -(m_dynamicsStrength * aimChangeY), m_velocityYaw, m_dynamicsSmoothTime, 1000, pDt);
        aimChangeYPR[1] = Math.SmoothCD(aimChangeYPR[1], -(m_dynamicsStrength * aimChangeX), m_velocityPitch, m_dynamicsSmoothTime, 1000, pDt);
        aimChangeYPR[2] = 0;
        vector dynamics[4];
        Math3D.YawPitchRollMatrix(aimChangeYPR, dynamics);
        dynamics[3] = vector.Zero;
        // aiming model offsets
        vector aimingMatTM[4];
        hia.WeaponGetAimingModelDirTm(aimingMatTM);
        // final offset matrix
        Math3D.MatrixMultiply4(dynamics, aimingMatTM, dynamics);
        Math3D.MatrixMultiply4(dynamics, matTM, pOutResult.m_CameraTM);
        AdjustCameraParameters(pDt, pOutResult);
        UpdateBatteryOptics(GetCurrentSightEntity());
        UpdateCameraNV(PlayerBase.Cast(m_pPlayer));
        if(m_CameraShake)
        {
            float x,y;
            m_CameraShake.Update(pDt, x, y);
            DayZPlayerImplement.Cast(m_pPlayer).GetAimingModel().SetCamShakeValues(x, y);
        }
    }
References AdjustCameraParameters(), CONST_LR_MAX, CONST_LR_MIN, CONST_UD_MAX, CONST_UD_MIN, CONST_UD_MIN_BACK, HumanInputController::GetAimChange(), HumanCommandMove::GetCurrentMovementSpeed(), GetCurrentSightEntity(), GetGame(), GetPlayer(), HumanItemAccessor(), m_CameraShake, m_CurrentCameraPitch, m_fLeftRightAngle, m_fUpDownAngle, m_fUpDownAngleAdd, m_iBoneIndex, m_pInput, m_pPlayer, Math3D::MatrixMultiply4(), Math::PI2, Math::RAD2DEG, Math::Sin(), Math::SmoothCD(), CameraShake::Update(), UpdateBatteryOptics(), UpdateCameraNV(), UpdateLRAngle(), UpdateUDAngle(), x, y, Math3D::YawPitchRollMatrix(), and vector::Zero.
SetCameraPP()
override void DayZPlayerCameraBase::SetCameraPP (bool state, DayZPlayerCamera launchedFrom) inline private
Definition at line 234 of file dayzplayercameraironsights.c.
    {
        //Print("SetCameraPP - ADS");
        if (PlayerBase.Cast(m_pPlayer) && launchedFrom.Type() != PlayerBase.Cast(m_pPlayer).GetCurrentPlayerCamera().Type())
        {
            //Print("DayZPlayerCameraIronsights | SetCameraPP | skipping, wrong camera type active!");
            return;
        }
        //if (!state || !m_weaponUsed || (PlayerBase.Cast(m_pPlayer) && launchedFrom != PlayerBase.Cast(m_pPlayer).GetCurrentPlayerCamera()))
        if (!state || !m_weaponUsed)
        {
            m_RequesterADS.Stop();
            if (IsCameraNV())
            {
                SetNVPostprocess(GetCameraNVType());
            }
            else
            {
                SetNVPostprocess(NVTypes.NONE);
            }
        }
        else
        {
            temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
            if (m_weaponUsed.GetWeaponDOF() || (m_opticsUsed && m_opticsUsed.GetOpticsDOF()))
            {
                if (m_opticsUsed && m_opticsUsed.GetOpticsDOF().Count() == 6)
                {
                    temp_array = m_opticsUsed.GetOpticsDOF();
                }
                else
                {
                    temp_array = m_weaponUsed.GetWeaponDOF();
                }
                if (temp_array.Count() != 6)
                    temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
            }
            m_RequesterADS.SetValuesIronsights(temp_array); //DOF only
            if (IsCameraNV())
            {
                SetNVPostprocess(GetCameraNVType());
            }
            else
            {
                SetNVPostprocess(NVTypes.NONE);
            }
        }
        if (m_weaponUsed)
        {
            m_weaponUsed.HideWeaponBarrel(false);
        }
    }
References GetCameraNVType(), IsCameraNV(), m_opticsUsed, m_pPlayer, m_weaponUsed, and SetNVPostprocess().
Referenced by OnActivate(), and UpdateCameraNV().
SetCameraPPDelay()
override void DayZPlayerCameraBase::SetCameraPPDelay (DayZPlayerCamera pPrevCamera) inline private
Definition at line 298 of file dayzplayercameraironsights.c.
    {
        if (pPrevCamera.GetCameraName() == "DayZPlayerCamera1stPerson")
        {
            //Print("---ironsights---DayZPlayerCamera1stPerson");
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_01;
        }
        else if (pPrevCamera.GetCameraName() == "DayZPlayerCameraOptics")
        {
            m_CameraPPDelay = 0;
        }
        else
        {
            //Print("---ironsights---else");
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_02;
        }
    }
References m_CameraPPDelay, DayZPlayerCameras::TIME_CAMERACHANGE_01, and DayZPlayerCameras::TIME_CAMERACHANGE_02.
Referenced by OnActivate().
SetupSightEntities()
void DayZPlayerCameraBase::SetupSightEntities () inline private
Definition at line 62 of file dayzplayercameraironsights.c.
    {
        EntityAI inHands = m_pPlayer.GetHumanInventory().GetEntityInHands();
        if (inHands)
        {
            m_weaponUsed = Weapon_Base.Cast(inHands);
            if( m_weaponUsed )
            {
                m_SightMisalignmentModifier = m_weaponUsed.GetPropertyModifierObject().m_SightMisalignment;
                m_dynamicsStrength = m_dynamicsStrength * m_SightMisalignmentModifier[0];
                m_dynamicsSmoothTime = m_dynamicsSmoothTime * m_SightMisalignmentModifier[1];
                m_opticsUsed = m_weaponUsed.GetAttachedOptics();
                if( m_opticsUsed )
                {
                    m_opticsHasWeaponOverride = m_opticsUsed.HasWeaponIronsightsOverride();
                }
            }
            else
            {
                m_opticsUsed = ItemOptics.Cast(inHands);
            }
        }
    }
References m_opticsUsed, m_pPlayer, and m_weaponUsed.
Referenced by DayZPlayerCameraIronsights().
UpdateBatteryOptics()
void DayZPlayerCameraBase::UpdateBatteryOptics (EntityAI entity) inline private
Definition at line 316 of file dayzplayercameraironsights.c.
    {
        ItemOptics optics = ItemOptics.Cast(entity);
        if (optics)
            optics.UpdateOpticsReddotVisibility();
    }
Referenced by OnUpdate().
Member Data Documentation
CONST_LR_MAX
static const float DayZPlayerCameraBase::CONST_LR_MAX = 160.0 static private
up limit
Definition at line 10 of file dayzplayercamera1stperson.c.
CONST_LR_MIN
static const float DayZPlayerCameraBase::CONST_LR_MIN = -160.0 static private
down limit
Definition at line 9 of file dayzplayercamera1stperson.c.
CONST_UD_MAX
static const float DayZPlayerCameraBase::CONST_UD_MAX = 85.0 static private
up limit
Definition at line 7 of file dayzplayercamera1stperson.c.
CONST_UD_MIN
static const float DayZPlayerCameraBase::CONST_UD_MIN = -85.0 static private
down limit
Definition at line 6 of file dayzplayercamera1stperson.c.
Referenced by OnUpdate().
CONST_UD_MIN_BACK
const float DayZPlayerCameraBase::CONST_UD_MIN_BACK = -25.0 static private
down limit on back
Definition at line 7 of file dayzplayercameraironsights.c.
Referenced by OnUpdate().
m_bShoulderInLS
protected bool DayZPlayerCameraBase::m_bShoulderInLS private
true - shoulder is in local space
Definition at line 135 of file dayzplayercamera3rdperson.c.
m_CameraOffsetLS
protected vector DayZPlayerCameraBase::m_CameraOffsetLS private
local space offset
Definition at line 132 of file dayzplayercamera3rdperson.c.
Referenced by OnUpdate().
m_CameraOffsetMS
protected vector DayZPlayerCameraBase::m_CameraOffsetMS private
model space offset
Definition at line 131 of file dayzplayercamera3rdperson.c.
Referenced by OnUpdate(), and OnUpdate().
m_dynamicsSmoothTime
float DayZPlayerCameraBase::m_dynamicsSmoothTime private
Definition at line 22 of file dayzplayercameraironsights.c.
m_dynamicsStrength
float DayZPlayerCameraBase::m_dynamicsStrength private
Definition at line 21 of file dayzplayercameraironsights.c.
m_fCameraLRShoulder
protected float DayZPlayerCameraBase::m_fCameraLRShoulder private
shoulder offsets
Definition at line 146 of file dayzplayercamera3rdperson.c.
m_fCameraLRShoulderVel
protected float DayZPlayerCameraBase::m_fCameraLRShoulderVel[1] private
Definition at line 147 of file dayzplayercamera3rdperson.c.
m_fDistance
protected float DayZPlayerCameraBase::m_fDistance private
distance from start
Definition at line 133 of file dayzplayercamera3rdperson.c.
Referenced by OnUpdate(), and OnUpdate().
m_fLeanDistance
protected float DayZPlayerCameraBase::m_fLeanDistance private
shift on leaning
Definition at line 137 of file dayzplayercamera3rdperson.c.
Referenced by OnUpdate().
m_fLeftRightAngle
protected float DayZPlayerCameraBase::m_fLeftRightAngle private
left right angle in rad (in freelook only)
Definition at line 91 of file dayzplayercamera1stperson.c.
Referenced by GetBaseAngles(), GetBaseAngles(), and OnUpdate().
m_fRoll
protected float DayZPlayerCameraBase::m_fRoll private
camera roll
Definition at line 136 of file dayzplayercamera3rdperson.c.
Referenced by OnUpdate(), and OnUpdate().
m_fShootFromCamera
protected float DayZPlayerCameraBase::m_fShootFromCamera = 0.0 private
settings
Definition at line 324 of file dayzplayercameraironsights.c.
Referenced by AdjustCameraParameters().
m_fShoulderWidth
protected float DayZPlayerCameraBase::m_fShoulderWidth private
shoulder camera widths
Definition at line 134 of file dayzplayercamera3rdperson.c.
m_fUpDownAngle
protected float DayZPlayerCameraBase::m_fUpDownAngle private
up down angle in rad
runtime values
up down angle in rad
Definition at line 89 of file dayzplayercamera1stperson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_fUpDownAngleAdd
protected float DayZPlayerCameraBase::m_fUpDownAngleAdd private
up down angle in rad
Definition at line 90 of file dayzplayercamera1stperson.c.
Referenced by GetBaseAngles(), and GetBaseAngles().
m_iBoneIndex
protected int DayZPlayerCameraBase::m_iBoneIndex = -1 private
main bone
runtime values
runtime config
main bone
right hand dummy bone index
Definition at line 86 of file dayzplayercamera1stperson.c.
Referenced by AdjustCameraParameters().
m_isEntering
protected bool DayZPlayerCameraBase::m_isEntering = false private
Definition at line 12 of file dayzplayercameraironsights.c.
m_movementAmplitudeX
float DayZPlayerCameraBase::m_movementAmplitudeX private
Definition at line 26 of file dayzplayercameraironsights.c.
m_movementAmplitudeY
float DayZPlayerCameraBase::m_movementAmplitudeY private
Definition at line 27 of file dayzplayercameraironsights.c.
m_movementFrequencyX
float DayZPlayerCameraBase::m_movementFrequencyX private
Definition at line 28 of file dayzplayercameraironsights.c.
m_movementFrequencyY
float DayZPlayerCameraBase::m_movementFrequencyY private
Definition at line 29 of file dayzplayercameraironsights.c.
m_MovementState
ref HumanMovementState DayZPlayerCameraBase::m_MovementState = new HumanMovementState() private
movement state
Definition at line 150 of file dayzplayercamera3rdperson.c.
m_movementTimeAcc
float DayZPlayerCameraBase::m_movementTimeAcc private
Definition at line 25 of file dayzplayercameraironsights.c.
m_OffsetLS
protected vector DayZPlayerCameraBase::m_OffsetLS private
position offset
Definition at line 87 of file dayzplayercamera1stperson.c.
m_OpticsCamDir
protected vector DayZPlayerCameraBase::m_OpticsCamDir private
Definition at line 329 of file dayzplayercameraironsights.c.
m_OpticsCamPos
protected vector DayZPlayerCameraBase::m_OpticsCamPos private
Definition at line 328 of file dayzplayercameraironsights.c.
m_opticsHasWeaponOverride
protected bool DayZPlayerCameraBase::m_opticsHasWeaponOverride = false private
Definition at line 13 of file dayzplayercameraironsights.c.
m_RequesterADS
protected PPERequester_CameraADS DayZPlayerCameraBase::m_RequesterADS private
Definition at line 16 of file dayzplayercameraironsights.c.
m_SightMisalignmentModifier
vector DayZPlayerCameraBase::m_SightMisalignmentModifier private
Definition at line 23 of file dayzplayercameraironsights.c.
m_velocityPitch
float DayZPlayerCameraBase::m_velocityPitch[1] private
Definition at line 20 of file dayzplayercameraironsights.c.
m_velocityYaw
float DayZPlayerCameraBase::m_velocityYaw[1] private
camera dynamics
Definition at line 19 of file dayzplayercameraironsights.c.
temp_array
protected ref array<float> DayZPlayerCameraBase::temp_array private
Definition at line 14 of file dayzplayercameraironsights.c.