DayzKode: Component Class Reference
Component Class Reference
Private Member Functions
void DebugBBoxDelete ()
override void DebugBBoxDelete ()
Shape DebugBBoxDraw ()
override Shape DebugBBoxDraw ()
void DebugBBoxSetColor (int color)
override void DebugBBoxSetColor (int color)
void DebugDirectionDelete ()
override void DebugDirectionDelete ()
Shape DebugDirectionDraw (float distance=1)
override Shape DebugDirectionDraw (float distance=1)
void DebugDirectionSetColor (int color)
void Event_OnAwake ()
void Event_OnFrame (IEntity other, float timeSlice)
void Event_OnInit ()
void Event_OnItemAttached (EntityAI item, string slot_name)
void Event_OnItemDetached (EntityAI item, string slot_name)
string GetCompName ()
int GetCompType ()
void LogThis (string msg, string fnc_name="n/a")
void LogThisError (string msg, string fnc_name="n/a")
void LogThisWarning (string msg, string fnc_name="n/a")
void OnDrawing ()
void SetParentEntityAI (EntityAI e)
Static Private Member Functions
static string GetNameByType (int comp_type)
static void Init ()
static bool IsTypeExist (int comp_type)
static void LogErrorBadCompType (int comp_type, string fnc_name)
static void LogWarningAlredyExist (int comp_type, string fnc_name)
Private Attributes
protected Shape m_DebugShapeBBox
protected Shape m_DebugShapeDirection
protected float m_DebugShapeDirectionDist
protected EntityAI m_ThisEntityAI
Static Private Attributes
static private string m_CompNames [COMP_TYPE_COUNT]
Detailed Description
Definition at line 15 of file component.c.
Member Function Documentation
DebugBBoxDelete() [1/2]
void Component::DebugBBoxDelete () private
DebugBBoxDelete() [2/2]
override void Component::DebugBBoxDelete () inline private
Definition at line 42 of file componententitydebug.c.
    {
        #ifndef DEVELOPER
        return;
        #endif
        if ( m_DebugShapeBBox )
        {
            m_DebugShapeBBox.Destroy();
            m_DebugShapeBBox = null;
        }
        if ( !m_DebugShapeDirection && !m_DebugShapeBBox )
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).Remove(OnDrawing);
        }
    }
References CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
DebugBBoxDraw() [1/2]
Shape Component::DebugBBoxDraw () private
DebugBBoxDraw() [2/2]
override Shape Component::DebugBBoxDraw () inline private
Definition at line 9 of file componententitydebug.c.
    {
        #ifndef DEVELOPER
        return null;
        #endif
        if ( m_DebugShapeBBox )
            m_DebugShapeBBox.Destroy();
        vector min_max[2];
        if (!m_ThisEntityAI.GetCollisionBox(min_max))
            return null;
        m_DebugShapeBBox = Debug.DrawBox(min_max[0], min_max[1]);
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(OnDrawing, 0, true);
        m_ThisEntityAI.SetEventMask(EntityEvent.FRAME);
        return null;
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), Debug::DrawBox(), CGame::GetCallQueue(), and GetGame().
DebugBBoxSetColor() [1/2]
void Component::DebugBBoxSetColor (int color) private
DebugBBoxSetColor() [2/2]
override void Component::DebugBBoxSetColor (int color) inline private
Definition at line 33 of file componententitydebug.c.
    {
        if ( m_DebugShapeBBox )
        {
            m_DebugShapeBBox.SetColor(color);
        }
    }
DebugDirectionDelete() [1/2]
void Component::DebugDirectionDelete () private
DebugDirectionDelete() [2/2]
override void Component::DebugDirectionDelete () inline private
Definition at line 84 of file componententitydebug.c.
    {
        #ifndef DEVELOPER
        return;
        #endif
        if ( m_DebugShapeDirection )
        {
            m_DebugShapeDirection.Destroy();
            m_DebugShapeDirection = null;
        }
        if ( !m_DebugShapeDirection && !m_DebugShapeBBox )
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).Remove(OnDrawing);
        }
    }
References CALL_CATEGORY_GUI, CGame::GetCallQueue(), GetGame(), and ScriptCallQueue::Remove().
DebugDirectionDraw() [1/2]
Shape Component::DebugDirectionDraw (float distance = 1) private
DebugDirectionDraw() [2/2]
override Shape Component::DebugDirectionDraw (float distance = 1) inline private
Definition at line 61 of file componententitydebug.c.
    {
        #ifndef DEVELOPER
        return null;
        #endif
        if ( m_DebugShapeDirection )
        {
            m_DebugShapeDirection.Destroy();
        }
        vector p1 = "0 0 0";
        vector p2 = m_ThisEntityAI.GetDirection() * m_DebugShapeDirectionDist;
        m_DebugShapeDirectionDist = distance;
        m_DebugShapeDirection = Debug.DrawArrow(p1, p2);
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(OnDrawing, 0, true);
        m_ThisEntityAI.SetEventMask(EntityEvent.FRAME);
        return null;
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), Debug::DrawArrow(), CGame::GetCallQueue(), GetGame(), and m_DebugShapeDirectionDist.
DebugDirectionSetColor()
void Component::DebugDirectionSetColor (int color) private
Event_OnAwake()
void Component::Event_OnAwake () inline private
Definition at line 102 of file component.c.
    {
    }
Referenced by ComponentsBank::CreateComponent().
Event_OnFrame()
void Component::Event_OnFrame (IEntity other, float timeSlice) private
Event_OnInit()
void Component::Event_OnInit () inline private
Definition at line 110 of file component.c.
    {
    }
Referenced by ComponentsBank::CreateComponent().
Event_OnItemAttached()
void Component::Event_OnItemAttached (EntityAI item, string slot_name) inline private
Definition at line 158 of file component.c.
    {
        LogThis("" + item + " -> " + slot_name,"Event_OnItemAttached");
        //Debug.Log("Component=>Event_OnItemAttached: " + item + " -> " + slot_name, );
    }
References LogThis().
Event_OnItemDetached()
void Component::Event_OnItemDetached (EntityAI item, string slot_name) inline private
Definition at line 167 of file component.c.
    {
        LogThis("" + item + " <- " + slot_name,"Event_OnItemDetached");
        //Log("Component=>Event_OnItemDetached: " + item + " <- " + slot_name );
    }
References LogThis().
GetCompName()
string Component::GetCompName () inline private
Definition at line 142 of file component.c.
    {
        return Component.GetNameByType(this.GetCompType());
    }
References GetCompType(), and GetNameByType().
Referenced by LogThis(), LogThisError(), and LogThisWarning().
GetCompType()
int Component::GetCompType () inline private
Definition at line 150 of file component.c.
    {
        return COMP_TYPE_UNDEFINED;
    }
References COMP_TYPE_UNDEFINED.
Referenced by GetCompName().
GetNameByType()
static string Component::GetNameByType (int comp_type) inline static private
Definition at line 48 of file component.c.
    {
        if ( IsTypeExist(comp_type) == false )
        {
            LogErrorBadCompType(comp_type, "Component->GetNameByType()");
            return "None";
        }
        return m_CompNames[comp_type];
    }
References IsTypeExist(), LogErrorBadCompType(), and m_CompNames.
Referenced by ComponentsBank::CreateComponent(), GetCompName(), and LogWarningAlredyExist().
Init()
static void Component::Init () inline static private
Definition at line 37 of file component.c.
    {
        m_CompNames[COMP_TYPE_ETITY_DEBUG]          = "ComponentEntityDebug";
        m_CompNames[COMP_TYPE_ENERGY_MANAGER]       = "ComponentEnergyManager";
        m_CompNames[COMP_TYPE_BODY_STAGING]         = "ComponentBodyStaging";
        m_CompNames[COMP_TYPE_ANIMAL_BLEEDING]      = "ComponentAnimalBleeding";
    }
References COMP_TYPE_ANIMAL_BLEEDING, COMP_TYPE_BODY_STAGING, COMP_TYPE_ENERGY_MANAGER, COMP_TYPE_ETITY_DEBUG, and m_CompNames.
Referenced by DayZGame().
IsTypeExist()
static bool Component::IsTypeExist (int comp_type) inline static private
Definition at line 62 of file component.c.
    {
        if ( comp_type < 0 || comp_type >= COMP_TYPE_COUNT )
        {
            return false;
        }
        return true;
    }
References COMP_TYPE_COUNT.
Referenced by ComponentsBank::CreateComponent(), ComponentsBank::GetComponent(), and GetNameByType().
LogErrorBadCompType()
static void Component::LogErrorBadCompType (int comp_type, string fnc_name) inline static private
Definition at line 76 of file component.c.
    {
        string msg = "Bad parameter comp_type='"+comp_type.ToString()+"'. Parameter must be 0-"+(COMP_TYPE_COUNT - 1).ToString()+". Returning component name 'None'.";
        Debug.LogError(msg, "Component", "n/a", fnc_name);
    }
References COMP_TYPE_COUNT, Debug::LogError(), and ToString().
Referenced by ComponentsBank::CreateComponent(), ComponentsBank::GetComponent(), and GetNameByType().
LogThis()
void Component::LogThis (string msg, string fnc_name = "n/a") inline private
Definition at line 118 of file component.c.
    {
        Debug.Log(msg, GetCompName(), "n/a", fnc_name, m_ThisEntityAI.ToString());
    }
References GetCompName(), Debug::Log(), and m_ThisEntityAI.
Referenced by Event_OnItemAttached(), and Event_OnItemDetached().
LogThisError()
void Component::LogThisError (string msg, string fnc_name = "n/a") inline private
Definition at line 134 of file component.c.
    {
        Debug.LogError(msg, GetCompName(), "n/a", fnc_name, m_ThisEntityAI.ToString());
    }
References GetCompName(), Debug::LogError(), and m_ThisEntityAI.
LogThisWarning()
void Component::LogThisWarning (string msg, string fnc_name = "n/a") inline private
Definition at line 126 of file component.c.
    {
        Debug.LogWarning(msg, GetCompName(), "n/a", fnc_name, m_ThisEntityAI.ToString());
    }
References GetCompName(), Debug::LogWarning(), and m_ThisEntityAI.
LogWarningAlredyExist()
static void Component::LogWarningAlredyExist (int comp_type, string fnc_name) inline static private
Definition at line 85 of file component.c.
    {
        string msg = "Component '"+Component.GetNameByType(comp_type)+"' already exists!";
        Debug.LogError(msg, "Component", "n/a", fnc_name);
    }
References GetNameByType(), and Debug::LogError().
Referenced by ComponentsBank::CreateComponent().
OnDrawing()
void Component::OnDrawing () inline private
Definition at line 102 of file componententitydebug.c.
    {
        #ifndef DEVELOPER
        return;
        #endif
        if ( m_DebugShapeBBox || m_DebugShapeDirection )
        {
            vector mat[4];
            m_ThisEntityAI.GetTransform(mat);
            if ( m_DebugShapeBBox )
            {
                m_DebugShapeBBox.SetMatrix(mat);
            }
            if ( m_DebugShapeDirection )
            {
                m_DebugShapeDirection.SetMatrix(mat);
            }
        }
    }
SetParentEntityAI()
void Component::SetParentEntityAI (EntityAI e) inline private
Definition at line 94 of file component.c.
    {
        m_ThisEntityAI = e;
    }
References m_ThisEntityAI.
Referenced by ComponentsBank::CreateComponent().
Member Data Documentation
m_CompNames
private string Component::m_CompNames[COMP_TYPE_COUNT] static private
Definition at line 20 of file component.c.
Referenced by GetNameByType(), and Init().
m_DebugShapeBBox
protected Shape Component::m_DebugShapeBBox private
Definition at line 4 of file componententitydebug.c.
m_DebugShapeDirection
protected Shape Component::m_DebugShapeDirection private
Definition at line 5 of file componententitydebug.c.
m_DebugShapeDirectionDist
protected float Component::m_DebugShapeDirectionDist private
Definition at line 6 of file componententitydebug.c.
Referenced by DebugDirectionDraw().
m_ThisEntityAI
protected EntityAI Component::m_ThisEntityAI private
Definition at line 24 of file component.c.
Referenced by ComponentAnimalBleeding::Bleed(), ComponentEnergyManager::CanBePluggedInto(), ComponentEnergyManager::CanReceivePlugFrom(), ComponentEnergyManager::CanWork(), ComponentEnergyManager::CheckWetness(), ComponentEnergyManager::ConsumeEnergy(), ComponentEnergyManager::DebugUpdate(), ComponentEnergyManager::DeviceUpdate(), ComponentEnergyManager::Event_OnAwake(), ComponentEnergyManager::Event_OnInit(), ComponentEnergyManager::FindAndConsumeEnergy(), ComponentEnergyManager::GetEnergyMax(), ComponentEnergyManager::GetThisEntityAI(), ComponentAnimalBleeding::InflictWoundDamage(), LogThis(), LogThisError(), LogThisWarning(), ComponentEnergyManager::OnAttachmentAdded(), ComponentEnergyManager::OnDeviceDestroyed(), ComponentEnergyManager::OnEnergyAdded(), ComponentEnergyManager::OnEnergyConsumed(), ComponentEnergyManager::OnIsPlugged(), ComponentEnergyManager::OnIsUnplugged(), ComponentEnergyManager::OnOwnSocketReleased(), ComponentEnergyManager::OnOwnSocketTaken(), ComponentEnergyManager::OnWork(), ComponentEnergyManager::PlugInDevice(), ComponentEnergyManager::PlugThisInto(), ComponentEnergyManager::ResetEnergyUsage(), SetParentEntityAI(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), ComponentEnergyManager::Synch(), ComponentBodyStaging::SynchSkinnedState(), ComponentEnergyManager::UnplugCordFromSocket(), ComponentEnergyManager::UnplugDevice(), ComponentEnergyManager::UnplugThis(), ComponentEnergyManager::UpdateCanWork(), ComponentEnergyManager::UpdatePlugState(), ComponentEnergyManager::UpdateSelections(), and ComponentEnergyManager::UpdateSocketSelections().