DayzKode: HungerNotfr Class Reference
HungerNotfr Class Reference
Private Member Functions
override void DisplayBadge ()
override void DisplayTendency (float delta)
override int GetNotifierType ()
override float GetObservedValue ()
override void HideBadge ()
void HungerNotfr (NotifiersManager manager)
Private Attributes
protected const float DEC_TRESHOLD_HIGH = -0.57
protected const float DEC_TRESHOLD_LOW = 0
protected const float DEC_TRESHOLD_MED = -0.35
protected const float INC_TRESHOLD_HIGH = 0.57
protected const float INC_TRESHOLD_LOW = 0
protected const float INC_TRESHOLD_MED = 0.35
Detailed Description
Definition at line 1 of file hungernotfr.c.
Constructor & Destructor Documentation
HungerNotfr()
void HungerNotfr::HungerNotfr (NotifiersManager manager) inline private
Definition at line 10 of file hungernotfr.c.
    {
    }
Member Function Documentation
DisplayBadge()
override void HungerNotfr::DisplayBadge () inline private
Definition at line 46 of file hungernotfr.c.
    {
    }
DisplayTendency()
override void HungerNotfr::DisplayTendency (float delta) inline private
Definition at line 19 of file hungernotfr.c.
    {
        //PrintString("delta:"+delta.ToString());
        int tendency = CalculateTendency(delta, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, INC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, DEC_TRESHOLD_HIGH);
        //GetVirtualHud().SetStatus(eDisplayElements.DELM_TDCY_ENERGY,tendency);
        //DSLevels level = DetermineLevel( GetObservedValue(), PlayerConstants.THRESHOLD_ENERGY_WARNING, PlayerConstants.THRESHOLD_ENERGY_CRITICAL, PlayerConstants.THRESHOLD_ENERGY_BLINKING, PlayerConstants.THRESHOLD_ENERGY_EXTRA );
        EStatLevels energy_level = m_Player.GetStatLevelEnergy();
        DisplayElementTendency dis_elm = DisplayElementTendency.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_TDCY_ENERGY));
        if( dis_elm )
        {
            dis_elm.SetTendency(tendency);
            dis_elm.SetSeriousnessLevel(energy_level);
        }
        /*
        Print("-----------------------------------------------------------");
        Print("water:"+ typename.EnumToString(EStatLevels,m_Player.GetStatLevelWater()));
        Print("energy:"+ typename.EnumToString(EStatLevels,m_Player.GetStatLevelEnergy()));
        Print("health:"+ typename.EnumToString(EStatLevels,m_Player.GetStatLevelHealth()));
        Print("blood:"+ typename.EnumToString(EStatLevels,m_Player.GetStatLevelBlood()));
        */
    }
References NotifierBase::CalculateTendency(), DEC_TRESHOLD_HIGH, DEC_TRESHOLD_LOW, DEC_TRESHOLD_MED, GetElement(), NotifierBase::GetVirtualHud(), INC_TRESHOLD_HIGH, INC_TRESHOLD_LOW, INC_TRESHOLD_MED, and NotifierBase::m_Player.
GetNotifierType()
override int HungerNotfr::GetNotifierType () inline private
Definition at line 14 of file hungernotfr.c.
    {
        return eNotifiers.NTF_HUNGRY;
    }
GetObservedValue()
override float HungerNotfr::GetObservedValue () inline private
Definition at line 56 of file hungernotfr.c.
    {
        return m_Player.GetStatEnergy().Get();
    }
References NotifierBase::m_Player.
HideBadge()
override void HungerNotfr::HideBadge () inline private
Definition at line 51 of file hungernotfr.c.
    {
    }
Member Data Documentation
DEC_TRESHOLD_HIGH
protected const float HungerNotfr::DEC_TRESHOLD_HIGH = -0.57 private
Definition at line 5 of file hungernotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_LOW
protected const float HungerNotfr::DEC_TRESHOLD_LOW = 0 private
Definition at line 3 of file hungernotfr.c.
Referenced by DisplayTendency().
DEC_TRESHOLD_MED
protected const float HungerNotfr::DEC_TRESHOLD_MED = -0.35 private
Definition at line 4 of file hungernotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_HIGH
protected const float HungerNotfr::INC_TRESHOLD_HIGH = 0.57 private
Definition at line 8 of file hungernotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_LOW
protected const float HungerNotfr::INC_TRESHOLD_LOW = 0 private
Definition at line 6 of file hungernotfr.c.
Referenced by DisplayTendency().
INC_TRESHOLD_MED
protected const float HungerNotfr::INC_TRESHOLD_MED = 0.35 private
Definition at line 7 of file hungernotfr.c.
Referenced by DisplayTendency().