DayzKode: SplitItemUtils Class Reference
SplitItemUtils Class Reference
Static Private Member Functions
static void TakeOrSplitToInventory (notnull PlayerBase player, notnull EntityAI target, notnull EntityAI item)
static void TakeOrSplitToInventoryLocation (notnull PlayerBase player, notnull InventoryLocation dst)
Detailed Description
Definition at line 1 of file splititemutils.c.
Member Function Documentation
TakeOrSplitToInventory()
static void SplitItemUtils::TakeOrSplitToInventory (notnull PlayerBase player, notnull EntityAI target, notnull EntityAI item) inline static private
Definition at line 3 of file splititemutils.c.
    {
        ItemBase item_base = ItemBase.Cast( item );
        if( !item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
            return;
        InventoryLocation il = new InventoryLocation;
        if( target.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ANY, il) )
        {
            if( item_base.GetTargetQuantityMax(il.GetSlot()) >= item_base.GetQuantity() )
            {
                if( il.GetType() == InventoryLocationType.ATTACHMENT )
                {
                    player.PredictiveTakeEntityToTargetAttachmentEx(il.GetParent(), item, il.GetSlot());
                }
                else
                {
                    InventoryLocation src = new InventoryLocation;
                    if (item.GetInventory().GetCurrentInventoryLocation(src))
                        player.PredictiveTakeToDst(src, il);
                }
            }
            else
            {
                item_base.SplitIntoStackMaxClient( il.GetParent(), il.GetSlot() );
            }
        }
    }
References InventoryLocation::GetParent(), InventoryLocation::GetSlot(), and InventoryLocation::GetType().
Referenced by AttachmentCategoriesRow::Combine(), PlayerContainer::OnDropReceivedFromGhostArea(), ClosableContainer::OnDropReceivedFromHeader(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), OnRightPanelDropReceived(), AttachmentCategoriesRow::Select(), HandsContainer::TakeAsAttachment(), and ClosableContainer::TakeAsAttachment().
TakeOrSplitToInventoryLocation()
static void SplitItemUtils::TakeOrSplitToInventoryLocation (notnull PlayerBase player, notnull InventoryLocation dst) inline static private
Definition at line 34 of file splititemutils.c.
    {
        ItemBase item_base = ItemBase.Cast( dst.GetItem() );
        int slot = dst.GetSlot();
        if( !dst.GetItem().GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
            return;
        float stack_max = item_base.GetTargetQuantityMax(slot);
        if( stack_max >= item_base.GetQuantity() )
        {
            InventoryLocation src = new InventoryLocation;
            if (dst.GetItem().GetInventory().GetCurrentInventoryLocation(src))
            {
                player.PredictiveTakeToDst(src, dst);
            }
            else
                Error("TakeIntoCargoEx cannot get src for dst=" + dst.DumpToString());
        }
        else
        {
            item_base.SplitIntoStackMaxToInventoryLocationClient( dst );
        }
    }
References Error(), and ItemBase::GetSlot().
Referenced by VicinitySlotsContainer::DoubleClick(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), Icon::DropReceivedFromMain(), OnCenterPanelDropReceived(), and VicinitySlotsContainer::TransferItem().