DayzKode: FracturedLegNotfr Class Reference
FracturedLegNotfr Class Reference
Private Member Functions
override void DisplayBadge ()
void FracturedLegNotfr (NotifiersManager manager)
override int GetNotifierType ()
override void HideBadge ()
override void SetActive (bool state)
Detailed Description
Definition at line 1 of file fracturedlegnotfr.c.
Constructor & Destructor Documentation
FracturedLegNotfr()
void FracturedLegNotfr::FracturedLegNotfr (NotifiersManager manager) inline private
Definition at line 3 of file fracturedlegnotfr.c.
    {
        m_Active = false;
    }
References NotifierBase::m_Active.
Member Function Documentation
DisplayBadge()
override void FracturedLegNotfr::DisplayBadge () inline private
Definition at line 26 of file fracturedlegnotfr.c.
    {
        DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_FRACTURE));
        if( dis_elm )
        {
            dis_elm.SetLevel(eBadgeLevel.FIRST);
        }
    }
References GetElement(), and NotifierBase::GetVirtualHud().
Referenced by SetActive().
GetNotifierType()
override int FracturedLegNotfr::GetNotifierType () inline private
Definition at line 8 of file fracturedlegnotfr.c.
    {
        return eNotifiers.NTF_FRACTURE;
    }
HideBadge()
override void FracturedLegNotfr::HideBadge () inline private
Definition at line 36 of file fracturedlegnotfr.c.
    {
        DisplayElementBadge dis_elm = DisplayElementBadge.Cast(GetVirtualHud().GetElement(eDisplayElements.DELM_BADGE_FRACTURE));
        if( dis_elm )
        {
            dis_elm.SetLevel(eBadgeLevel.NONE);
        }
    }
References GetElement(), and NotifierBase::GetVirtualHud().
Referenced by SetActive().
SetActive()
override void FracturedLegNotfr::SetActive (bool state) inline private
Definition at line 13 of file fracturedlegnotfr.c.
    {
        if (state == true)
        {
            DisplayBadge();
        }
        else
        {
            HideBadge();
        }
    }
References DisplayBadge(), and HideBadge().