DayzKode: Icon Class Reference
Icon Class Reference
Private Member Functions
void CheckHasQuantity ()
void CheckHasQuantityEx (bool refresh=true)
void CheckHasTemperature ()
void CheckIsMagazine ()
void CheckIsMagazineEx (bool refresh=true)
void CheckIsWeapon ()
void Combine (Widget w, int x, int y, Widget receiver)
bool CombineItems (EntityAI entity1, EntityAI entity2)
void CreateWhiteBackground ()
void DestroyWhiteBackground ()
void DoubleClick (Widget w, int x, int y, int button)
void DraggingOver (Widget w, int x, int y, Widget receiver)
void DraggingOverCombine (Widget w, int x, int y, Widget receiver)
void DraggingOverSwap (Widget w, int x, int y, Widget receiver)
void DropReceivedFromBackground (Widget w, int x, int y, Widget reciever)
void DropReceivedFromMain (Widget w, int x, int y, Widget receiver)
bool FlagAction (EntityAI entity1, EntityAI entity2, int combinationFlags)
void FullScreen ()
int GetCargoPos ()
Object GetObject ()
int GetPosX ()
int GetPosY ()
Widget GetSelectedWidget ()
int GetSizeX ()
int GetSizeY ()
int GetSort ()
void Icon (LayoutHolder parent, bool hands_icon=false)
void Init (EntityAI obj)
void InitEx (EntityAI obj, bool refresh=true)
void InitLock (EntityAI parent, EntityAI obj, int x_pos, int y_pos, bool flip)
bool IsDragged ()
void MouseClick (Widget w, int x, int y, int button)
bool MouseEnter (Widget w, int x, int y)
bool MouseLeave (Widget w, Widget s, int x, int y)
void OnDraggingOverBackground (Widget w, int x, int y, Widget reciever)
void OnPerformCombination (int combinationFlags)
void OnPerformRecipe (int id)
override void Refresh ()
void RefreshIconPos ()
void RefreshMuzzleIcon ()
void RefreshPos (int row, int column)
void RefreshQuickbar ()
void RevertToOriginalFlip ()
override void SetActive (bool active)
void SetCargoPos (int x)
void SetItemPreview ()
void SetItemPreviewEx (bool refresh=true)
void SetItemSize ()
void SetItemSizeEx (bool refresh=true)
override void SetLayoutName ()
override void SetParentWidget ()
void SetPos ()
void SetPos (int x, int y)
void SetPosEx (bool refresh=true)
void SetPosX (int x)
void SetPosY (int y)
void SetQuantity ()
void SetSize ()
void SetSize (int x, int y)
void SetSizeX (int x)
void SetSizeY (int y)
void SetSort (int index)
void SetTemperature ()
void ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags, Widget w, bool color_test)
void Swap (Widget w, int x, int y, Widget receiver)
void ToRefresh (Icon icon, Icon icon2)
void UpdateFlip (bool flipped)
override void UpdateInterval ()
void ~Icon ()
Private Attributes
protected ref array< ImageWidget > m_AmmoIcons
protected ImageWidget m_AmmoTypeIcon
protected int m_CargoPos
protected Widget m_ColorWidget
protected float m_CurrQuantity = -1
protected bool m_HandsIcon
protected bool m_HasQuantity = false
protected bool m_HasTemperature = false
protected bool m_IsDragged
protected bool m_IsMagazine = false
protected bool m_IsWeapon = false
protected ItemBase m_Item
protected ItemPreviewWidget m_ItemPreview
protected Widget m_ItemSizePanel
protected TextWidget m_ItemSizeWidget
protected EntityAI m_Lock
protected EntityAI m_Obj
protected int m_PosX
protected int m_PosY
protected bool m_PreviousFlipOrientation
protected TextWidget m_QuantityItem
protected Widget m_QuantityPanel
protected ProgressBarWidget m_QuantityProgress
protected Widget m_QuantityStack
protected Widget m_SelectedPanel
protected int m_SizeX
protected int m_SizeY
const int NUMBER_OF_TIMERS = 2
Detailed Description
Definition at line 1 of file icon.c.
Constructor & Destructor Documentation
Icon()
void Icon::Icon (LayoutHolder parent, bool hands_icon = false) inline private
Definition at line 40 of file icon.c.
    {
        m_HandsIcon = hands_icon;
        ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
        m_ItemPreview       = ItemPreviewWidget.Cast( GetMainWidget().FindAnyWidget( "Render" ) );
        m_ColorWidget       = GetMainWidget().FindAnyWidget( "Color" );
        m_SelectedPanel     = GetMainWidget().FindAnyWidget( "Selected" );
        m_QuantityPanel     = GetMainWidget().FindAnyWidget( "QuantityPanel" );
        m_QuantityItem      = TextWidget.Cast( GetMainWidget().FindAnyWidget( "Quantity" ) );
        m_QuantityProgress  = ProgressBarWidget.Cast( GetMainWidget().FindAnyWidget( "QuantityBar" ) );
        m_QuantityStack     = GetMainWidget().FindAnyWidget( "QuantityStackPanel" );
        m_ItemSizePanel     = GetMainWidget().FindAnyWidget( "ItemSizePanel" );
        m_ItemSizeWidget    = TextWidget.Cast( GetMainWidget().FindAnyWidget( "ItemSize" ) );
        m_AmmoTypeIcon      = ImageWidget.Cast( GetMainWidget().FindAnyWidget( "AmmoTypeIcon" ) );
        SetActive( false );
    }
References FindAnyWidget(), ItemManager::GetInstance(), m_AmmoTypeIcon, m_ColorWidget, m_HandsIcon, m_ItemPreview, m_ItemSizePanel, m_ItemSizeWidget, m_QuantityItem, m_QuantityPanel, m_QuantityProgress, m_QuantityStack, m_SelectedPanel, SetActive(), and ItemManager::SetSelectedItem().
~Icon()
void Icon::~Icon () inline private
Definition at line 62 of file icon.c.
    {
        if( m_Obj )
        {
            m_Obj.GetOnItemFlipped().Remove( UpdateFlip );
            m_Obj.GetOnViewIndexChanged().Remove( SetItemPreview );
        }
        if( m_IsDragged)
        {
            RevertToOriginalFlip();
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().SetIsDragging( false );
            m_IsDragged = false;
        }
    }
References ItemManager::GetInstance(), ItemManager::HideDropzones(), m_IsDragged, m_Obj, RevertToOriginalFlip(), ItemManager::SetIsDragging(), SetItemPreview(), and UpdateFlip().
Member Function Documentation
CheckHasQuantity()
void Icon::CheckHasQuantity () inline private
Definition at line 1825 of file icon.c.
    {
        CheckHasQuantityEx();
    }
References CheckHasQuantityEx().
CheckHasQuantityEx()
void Icon::CheckHasQuantityEx (bool refresh = true) inline private
Definition at line 1814 of file icon.c.
    {
        if ( m_Item )
        {
            m_HasQuantity = ( QuantityConversions.HasItemQuantity( m_Item ) != QUANTITY_HIDDEN );
            if ( m_HasQuantity )
                m_QuantityPanel.Show( true, refresh );
        }
    }
References QuantityConversions::HasItemQuantity(), m_HasQuantity, m_Item, m_QuantityPanel, and QUANTITY_HIDDEN.
Referenced by CheckHasQuantity(), and InitEx().
CheckHasTemperature()
void Icon::CheckHasTemperature () inline private
Definition at line 1806 of file icon.c.
    {
        if ( m_Item )
        {
            m_HasTemperature = ( m_Item.GetTemperatureMax() != 0 && m_Item.GetTemperatureMin() != 0 );
        }
    }
References m_HasTemperature, and m_Item.
Referenced by InitEx().
CheckIsMagazine()
void Icon::CheckIsMagazine () inline private
Definition at line 1801 of file icon.c.
    {
        CheckIsMagazineEx();
    }
References CheckIsMagazineEx().
CheckIsMagazineEx()
void Icon::CheckIsMagazineEx (bool refresh = true) inline private
Definition at line 1763 of file icon.c.
    {
        Magazine mag = Magazine.Cast( m_Obj );
        if ( mag )
        {
            m_IsMagazine = true;
            AmmoData data = Magazine.GetAmmoData( mag.ClassName() );
            if ( data )
            {
                ProjectileType p_type = data.m_ProjectileType;
                switch (p_type)
                {
                    case ProjectileType.None:
                    {
                        m_AmmoTypeIcon.Show( false, refresh );
                        break;
                    }
                    case ProjectileType.Tracer:
                    {
                        m_AmmoTypeIcon.LoadImageFile( 0, "set:dayz_gui image:tracer" );
                        m_AmmoTypeIcon.Show( true, refresh );
                        break;
                    }
                    case ProjectileType.AP:
                    {
                        m_AmmoTypeIcon.LoadImageFile( 0, "set:dayz_gui image:armor_piercing" );
                        m_AmmoTypeIcon.Show( true, refresh );
                        break;
                    }
                }
            }
        }
        else
        {
            m_IsMagazine = false;
        }
    }
References m_AmmoTypeIcon, m_IsMagazine, and m_Obj.
Referenced by CheckIsMagazine(), and InitEx().
CheckIsWeapon()
void Icon::CheckIsWeapon () inline private
Definition at line 1696 of file icon.c.
    {
        Weapon_Base wpn = Weapon_Base.Cast( m_Obj );
        if ( wpn )
        {
            m_AmmoIcons = new array<ImageWidget>;
            m_IsWeapon = true;
            float x_pos = 0.0;
            float widht = 0.0, height = 0.0;
            for (int i = 0; i < wpn.GetMuzzleCount(); i++)
            {
                if (i == 1)
                {
                    m_AmmoIcons[0].GetSize(widht,height);
                }
                x_pos += widht;
                Widget ammo_icon = Widget.Cast( GetGame().GetWorkspace().CreateWidgets( "gui/layouts/inventory_new/ammo_icon.layout", GetMainWidget() ) );
                ammo_icon.SetPos(x_pos, 0.0, false);
                ImageWidget ammo_icon_img = ImageWidget.Cast(ammo_icon.GetChildren());
                AmmoData data = Magazine.GetAmmoData( wpn.GetChamberAmmoTypeName( i ) );
                if ( data )
                {
                    CartridgeType c_type = data.m_CartridgeType;
                    switch ( c_type )
                    {
                        case CartridgeType.Pistol:
{
                            ammo_icon_img.LoadImageFile( 0, "set:dayz_gui image:cartridge_pistol" );
                            ammo_icon_img.LoadImageFile( 1, "set:dayz_gui image:shell_pistol" );
                            ammo_icon_img.LoadImageFile( 2, "set:dayz_gui image:jam_pistol" );
                            break;
                        }
                        case CartridgeType.Intermediate:
{
                            ammo_icon_img.LoadImageFile( 0, "set:dayz_gui image:cartridge_int" );
                            ammo_icon_img.LoadImageFile( 1, "set:dayz_gui image:shell_int" );
                            ammo_icon_img.LoadImageFile( 2, "set:dayz_gui image:jam_int" );
                            break;
                        }
                        case CartridgeType.FullPower:
{
                            ammo_icon_img.LoadImageFile( 0, "set:dayz_gui image:cartridge_fp" );
                            ammo_icon_img.LoadImageFile( 1, "set:dayz_gui image:shell_fp" );
                            ammo_icon_img.LoadImageFile( 2, "set:dayz_gui image:jam_fp" );
                            break;
                        }
                        case CartridgeType.Shell:
{
                            ammo_icon_img.LoadImageFile( 0, "set:dayz_gui image:cartridge_shell" );
                            ammo_icon_img.LoadImageFile( 1, "set:dayz_gui image:shell_shell" );
                            ammo_icon_img.LoadImageFile( 2, "set:dayz_gui image:jam_shell" );
                            break;
                        }
                    }
                }
                m_AmmoIcons.Insert(ammo_icon_img);
            }
        }
        else
        {
            m_IsWeapon = false;
        }
    }
References GetGame(), Widget::LoadImageFile(), m_AmmoIcons, m_IsWeapon, and m_Obj.
Referenced by InitEx().
Combine()
void Icon::Combine (Widget w, int x, int y, Widget receiver) inline private
Definition at line 751 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !iw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !iw )
        {
          iw = ItemPreviewWidget.Cast( w );
        }
        if( !iw.GetItem() )
        {
            return;
        }
        int flags = ItemManager.GetCombinationFlags( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands(), iw.GetItem() );
        ShowActionMenuCombine( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands(), iw.GetItem(), flags , w, false );
    }
References ItemManager::GetCombinationFlags(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), name, string::Replace(), ItemManager::SetIsDragging(), and ShowActionMenuCombine().
CombineItems()
bool Icon::CombineItems (EntityAI entity1, EntityAI entity2) inline private
Definition at line 776 of file icon.c.
    {
        int flags = ItemManager.GetCombinationFlags( entity1, entity2 );
        return FlagAction( entity1, entity2, flags );
    }
References FlagAction(), and ItemManager::GetCombinationFlags().
Referenced by Attachments::Combine(), Container::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
CreateWhiteBackground()
void Icon::CreateWhiteBackground () inline private
Definition at line 1251 of file icon.c.
    {
        m_PreviousFlipOrientation = m_Item.GetInventory().GetFlipCargo();
        ItemManager.GetInstance().SetDraggedIcon(this);
        ItemManager.GetInstance().SetDraggedItem(m_Item);
        m_IsDragged = true;
        ItemManager.GetInstance().SetIsDragging( true );
        int ww, hh;
        GetGame().GetInventoryItemSize( m_Item, ww, hh );
        if ( m_Item.GetInventory().GetFlipCargo() )
            SetSize( hh, ww );
        else
            SetSize( ww, hh );
        SetSize();
        if ( !m_HandsIcon )
        {
            Refresh();
        }
        else
        {
            m_ItemPreview.SetForceFlipEnable(false);
            m_ColorWidget.SetColor( ColorManager.BASE_COLOR );
            m_ColorWidget.SetAlpha( 0.1 );
        }
        m_SelectedPanel.Show( true );
    }
References ColorManager::BASE_COLOR, GetGame(), ItemManager::GetInstance(), CGame::GetInventoryItemSize(), m_ColorWidget, m_HandsIcon, m_IsDragged, m_Item, m_ItemPreview, m_PreviousFlipOrientation, m_SelectedPanel, Refresh(), ItemManager::SetDraggedIcon(), ItemManager::SetDraggedItem(), ItemPreviewWidget::SetForceFlipEnable(), ItemManager::SetIsDragging(), and SetSize().
DestroyWhiteBackground()
void Icon::DestroyWhiteBackground () inline private
Definition at line 1226 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        m_IsDragged = false;
        RevertToOriginalFlip();
        if ( m_HandsIcon )
        {
            m_ItemPreview.SetForceFlipEnable(true);
            m_ItemPreview.SetForceFlip(false);
            Refresh();
            FullScreen();
        }
        m_SelectedPanel.SetColor( ARGBF( 1, 1, 1, 1 ) );
        m_SelectedPanel.Show( false );
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
        if ( menu )
            menu.RefreshQuickbar();
    }
References ARGBF(), FullScreen(), GetGame(), ItemManager::GetInstance(), ItemManager::HideDropzones(), InventoryMenu(), m_HandsIcon, m_IsDragged, m_ItemPreview, m_SelectedPanel, MENU_INVENTORY, Refresh(), RevertToOriginalFlip(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), and ItemManager::SetIsDragging().
DoubleClick()
void Icon::DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 135 of file icon.c.
    {
        if( button == MouseState.LEFT )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if( player.GetInventory().HasInventoryReservation( m_Obj, null ) || player.GetInventory().IsInventoryLocked() || player.IsItemsToDelete() )
            {
                return;
            }
            InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
            if( w == null )
            {
                return;
            }
            ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
            if( !iw )
            {
              string name = w.GetName();
              name.Replace( "PanelWidget", "Render" );
              iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
            }
            if( !iw )
            {
              iw = ItemPreviewWidget.Cast( w );
            }
            if( !iw.GetItem() )
            {
                return;
            }
            EntityAI item = iw.GetItem();
            if( !item.GetInventory().CanRemoveEntity() )
                return;
            if( m_HandsIcon )
            {
                if( player.GetHumanInventory().CanRemoveEntityInHands() )
                {
                    player.PredictiveMoveItemFromHandsToInventory();
                }
                HideOwnedTooltip();
                if( menu )
                {
                    menu.RefreshQuickbar();
                }
                return;
            }
            InventoryLocation i1 = new InventoryLocation;
            EntityAI hands_item = player.GetHumanInventory().GetEntityInHands();
            EntityAI item_root_owner = item.GetHierarchyRoot();
            if( player.GetInventory().HasEntityInInventory( item ) && player.GetHumanInventory().CanAddEntityInHands( item ) )
            {
                player.PredictiveTakeEntityToHands( item );
            }
            else if( hands_item && item_root_owner == GetGame().GetPlayer() )
            {
                int index = player.GetHumanInventory().FindUserReservedLocationIndex(hands_item);
                if(index>=0)
                {
                    player.GetHumanInventory().GetUserReservedLocation( index, i1);
                }
                if( player.GetInventory().CanForceSwapEntitiesEx( item, null, hands_item, i1 ) )
                {
                    player.PredictiveForceSwapEntities( item, hands_item, i1);
                }
                else if( player.GetInventory().CanSwapEntitiesEx( item, hands_item ) )
                {
                    player.PredictiveSwapEntities( item, hands_item );
                }
            }
            else
            {
                bool found = false;
                if( item.GetInventory().CanRemoveEntity())
                {
                    InventoryLocation i2 = new InventoryLocation;
                    found = player.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ANY, i2 );
                    if( found )
                    {
                        if( i2.GetType() == FindInventoryLocationType.ATTACHMENT )
{
                            if( i2.GetParent() != player )
                                found = false;
                        }
                    }
                }
                if( found )
                {
                    if(player.GetHumanInventory().CanAddEntityToInventory(item))
                        player.PredictiveTakeEntityToInventory(FindInventoryLocationType.ANY, item);
                }
                else
                {
                    if( player.GetHumanInventory().CanAddEntityInHands( item ) )
                    {
                        player.PredictiveTakeEntityToHands( item );
                    }
                }
            }
            HideOwnedTooltip();
            if( menu )
            {
                menu.RefreshQuickbar();
            }
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetType(), InventoryMenu(), m_HandsIcon, m_Obj, MENU_INVENTORY, name, and string::Replace().
DraggingOver()
void Icon::DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 372 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        if( w == null )
        {
            return;
        }
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget receiver_ipw = ItemPreviewWidget.Cast( receiver.FindAnyWidget( "Render" ) );
        if( m_HandsIcon )
        {
            receiver_ipw = ItemPreviewWidget.Cast( receiver.GetParent().FindAnyWidget( "Render" ) );
        }
        ItemPreviewWidget w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( w_ipw == null )
        {
            w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        }
        if( w_ipw == null )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        InventoryItem receiver_entity = InventoryItem.Cast( receiver_ipw.GetItem() );
        InventoryItem w_entity = InventoryItem.Cast( w_ipw.GetItem() );
        InventoryLocation loc_dst;
        if( !receiver_entity || !w_entity )
        {
            return;
        }
        if( m_Lock )
        {
            if( receiver_entity == w_entity )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else
            {
                CargoContainer c_parent = CargoContainer.Cast( m_Parent );
                float parent_x;
                float parent_y;
                c_parent.GetRootWidget().GetScreenPos( parent_x, parent_y );
                float icon_size = c_parent.GetIconSize();
                float space_size = c_parent.GetSpaceSize();
                int PosX = (x-parent_x) / (icon_size + space_size);
                int PosY = (y-parent_y) / (icon_size + space_size);
                //Print("X: " + GetPosX() + " or " + PosX  + " ;Y: " + GetPosY() + " or " + PosY);
                EntityAI parent = m_Lock;
                CargoBase target_cargo  = parent.GetInventory().GetCargo();
                loc_dst = new InventoryLocation();
                loc_dst.SetCargoAuto(target_cargo, w_entity, PosY, PosX, w_entity.GetInventory().GetFlipCargo());
                if( parent.GetInventory().LocationCanAddEntity(loc_dst))
                {
                    ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                    ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                }
                else
                {
                    ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                    ItemManager.GetInstance().ShowSourceDropzone( w_entity );
                }
            }
        }
        else if( ( ItemBase.Cast( receiver_entity ) ).CanBeCombined( ItemBase.Cast( w_entity ) ) )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
            if( m_Obj.GetHierarchyRootPlayer() == player )
            {
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else if( !m_HandsIcon )
            {
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
            }
        }
        else
        {
            Magazine mag = Magazine.Cast(w_entity);
            Weapon_Base wpn = Weapon_Base.Cast(w_entity.GetHierarchyParent());
            EntityAI w_hierarchyParent = w_entity.GetHierarchyParent();
            EntityAI receiver_hierarchyParent = w_entity.GetHierarchyParent();
            if ( wpn && mag )
            {
                if( player.GetWeaponManager().CanSwapMagazine( wpn,  Magazine.Cast(receiver_entity) ) )
                {
                    ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                    if( m_Obj.GetHierarchyRootPlayer() == player )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else if( !m_HandsIcon )
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                }
                else
                {
                    ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                    ItemManager.GetInstance().ShowSourceDropzone( w_entity );
                }
            }
            else if ((w_hierarchyParent && (w_hierarchyParent.IsInherited(FenceKit) || w_hierarchyParent.IsInherited(WatchtowerKit))) || (receiver_hierarchyParent && (receiver_hierarchyParent.IsInherited(FenceKit) || receiver_hierarchyParent.IsInherited(WatchtowerKit))))
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( w_entity );
            }
            else
            {
                InventoryLocation il = new InventoryLocation;
                if( GameInventory.CanSwapEntitiesEx( receiver_entity, w_entity ) )
                {
                    ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                    if( m_Obj.GetHierarchyRootPlayer() == player )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else if( !m_HandsIcon )
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                }
                else if( GameInventory.CanForceSwapEntitiesEx( w_entity, null, receiver_entity, il ) )
                    {
                        ColorManager.GetInstance().SetColor( w, ColorManager.FSWAP_COLOR );
                        if( m_Obj.GetHierarchyRootPlayer() == player )
{
                            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                        }
                        else if( !m_HandsIcon )
{
                            ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                        }
                    }
                    else
                    {
                        ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                        ItemManager.GetInstance().ShowSourceDropzone( w_entity );
                    }
                }
            }
        }
References ColorManager::COMBINE_COLOR, ColorManager::FSWAP_COLOR, GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_HandsIcon, m_Lock, m_Obj, m_Parent, name, ColorManager::RED_COLOR, string::Replace(), InventoryLocation::SetCargoAuto(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), ColorManager::SWAP_COLOR, x, and y.
DraggingOverCombine()
void Icon::DraggingOverCombine (Widget w, int x, int y, Widget receiver) inline private
Definition at line 322 of file icon.c.
    {
        if( w == null )
        {
            return;
        }
        ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !iw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !iw )
        {
          iw = ItemPreviewWidget.Cast( w );
        }
        if( !iw.GetItem() )
        {
            return;
        }
        int flags = ItemManager.GetCombinationFlags( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands(), iw.GetItem() );
        ShowActionMenuCombine( GetGame().GetPlayer().GetHumanInventory().GetEntityInHands(), iw.GetItem(), flags , w , true);
    }
References ItemManager::GetCombinationFlags(), GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, string::Replace(), and ShowActionMenuCombine().
DraggingOverSwap()
void Icon::DraggingOverSwap (Widget w, int x, int y, Widget receiver) inline private
Definition at line 251 of file icon.c.
    {
        if( w == null )
        {
            return;
        }
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget receiver_ipw = ItemPreviewWidget.Cast( receiver.FindAnyWidget( "Render" ) );
        if( m_HandsIcon )
        {
            receiver_ipw = ItemPreviewWidget.Cast( receiver.GetParent().FindAnyWidget( "Render" ) );
        }
        ItemPreviewWidget w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( w_ipw == null )
        {
            w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        }
        if( w_ipw == null )
        {
            return;
        }
        InventoryItem receiver_entity = InventoryItem.Cast( receiver_ipw.GetItem() );
        InventoryItem w_entity = InventoryItem.Cast( w_ipw.GetItem() );
        if( !w_entity )
        {
            return;
        }
        InventoryLocation il = new InventoryLocation;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        int index = player.GetHumanInventory().FindUserReservedLocationIndex( m_Item );
        if(index >= 0)
        {
            player.GetHumanInventory().GetUserReservedLocation( index, il );
        }
        if( index < 0 && GameInventory.CanSwapEntitiesEx( receiver_entity, w_entity ) )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
        }
        else if( GameInventory.CanForceSwapEntitiesEx( w_entity, null, receiver_entity, il ) )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.FSWAP_COLOR );
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
        }
        else
        {
            /*if( m_HandsIcon )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
            }
            else
            {*/
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( w_entity );
            //}
        }
    }
References ColorManager::FSWAP_COLOR, ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), ItemManager::HideDropzones(), m_HandsIcon, m_Item, name, ColorManager::RED_COLOR, string::Replace(), ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
DropReceivedFromBackground()
void Icon::DropReceivedFromBackground (Widget w, int x, int y, Widget reciever) inline private
Definition at line 1316 of file icon.c.
    {
        Pos pa;
        if( reciever )
        {
            reciever.GetUserData( pa );
            if( m_Parent )
            {
                ContainerWithCargo item = ContainerWithCargo.Cast( m_Parent.m_Parent );
                if( item )
                {
                    item.DropReceived(w, m_PosY + pa.y, m_PosX + pa.x );
                }
            }
        }
    }
References m_Parent, m_PosX, m_PosY, and Pos().
DropReceivedFromMain()
void Icon::DropReceivedFromMain (Widget w, int x, int y, Widget receiver) inline private
Definition at line 931 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        ItemPreviewWidget receiver_ipw = ItemPreviewWidget.Cast( receiver.FindAnyWidget( "Render" ) );
        if( m_HandsIcon )
        {
            receiver_ipw = ItemPreviewWidget.Cast( receiver.GetParent().FindAnyWidget( "Render" ) );
        }
        ItemPreviewWidget w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( w_ipw == null )
        {
            w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        }
        if( w_ipw == null )
        {
            return;
        }
        InventoryItem receiver_entity = InventoryItem.Cast( receiver_ipw.GetItem() );
        InventoryItem w_entity = InventoryItem.Cast( w_ipw.GetItem() );
        if( !w_entity )
        {
            return;
        }
        int index;
        InventoryLocation loc_src;
        InventoryLocation loc_dst;
        if( m_Lock && receiver_entity == w_entity )
        {
            index = player.GetHumanInventory().FindUserReservedLocationIndex( m_Item );
            loc_src = new InventoryLocation;
            loc_dst = new InventoryLocation;
            m_Item.GetInventory().GetCurrentInventoryLocation( loc_src );
            player.GetHumanInventory().GetUserReservedLocation( index, loc_dst );
            if(loc_dst.GetParent().GetInventory().LocationCanAddEntity(loc_dst))
            {
                player.GetHumanInventory().ClearUserReservedLocation( m_Item );
                player.PredictiveTakeToDst( loc_src, loc_dst );
                m_Item.GetOnReleaseLock().Invoke(m_Item);
            }
        }
        else if( m_Lock )
        {
            CargoContainer c_parent = CargoContainer.Cast( m_Parent );
            float parent_x;
            float parent_y;
            c_parent.GetRootWidget().GetScreenPos( parent_x, parent_y );
            float icon_size = c_parent.GetIconSize();
            float space_size = c_parent.GetSpaceSize();
            int PosX = (x-parent_x) / (icon_size + space_size);
            int PosY = (y-parent_y) / (icon_size + space_size);
            //Print("X: " + GetPosX() + " or " + PosX  + " ;Y: " + GetPosY() + " or " + PosY);
            EntityAI parent = m_Lock;
            CargoBase target_cargo  = parent.GetInventory().GetCargo();
            loc_dst = new InventoryLocation();
            loc_dst.SetCargoAuto(target_cargo, w_entity, PosY, PosX, w_entity.GetInventory().GetFlipCargo());
            if( parent.GetInventory().LocationCanAddEntity(loc_dst))
            {
                player.GetHumanInventory().ClearUserReservedLocation( m_Item );
                m_Item.GetOnReleaseLock().Invoke(m_Item);
                SplitItemUtils.TakeOrSplitToInventoryLocation( player, loc_dst);
            }
            //player.PredictiveTakeEntityToCargoEx( w_entity, loc_dst.GetIdx(), loc_dst.GetRow(), loc_dst.GetCol() );
        }
        else
        {
            if( ( ItemBase.Cast( receiver_entity ) ).CanBeCombined( ItemBase.Cast( w_entity ) ) )
            {
                ( ItemBase.Cast( receiver_entity ) ).CombineItemsClient( ItemBase.Cast( w_entity ) );
            }
            else
            {
                Magazine mag = Magazine.Cast(w_entity);
                Weapon_Base wpn = Weapon_Base.Cast(w_entity.GetHierarchyParent());
                if( wpn && mag )
                {
                    if( player.GetWeaponManager().CanSwapMagazine( wpn,  Magazine.Cast(receiver_entity) ) )
                        player.GetWeaponManager().SwapMagazine( Magazine.Cast(receiver_entity) );
                            //return;
                }
                else
                {
                    if( GameInventory.CanSwapEntitiesEx( w_entity, receiver_entity ) )
                    {
                        player.PredictiveSwapEntities( w_entity, receiver_entity );
                        Icon icon = ItemManager.GetInstance().GetDraggedIcon();
                        if( m_Parent && m_Parent.IsInherited( IconsContainer ) )
{
                            ToRefresh( this, icon );
                        }
                    }
                    else
                    {
                        loc_src = new InventoryLocation;
                        loc_dst = new InventoryLocation;
                        InventoryLocation loc_temp = new InventoryLocation;
                        w_entity.GetInventory().GetCurrentInventoryLocation(loc_src);
                        w_entity.GetInventory().GetCurrentInventoryLocation(loc_temp);
                        receiver_entity.GetInventory().GetCurrentInventoryLocation(loc_dst);
                        loc_src.CopyLocationFrom(loc_dst,false);
                        loc_src.SetFlip(w_entity.GetInventory().GetFlipCargo());
                        loc_dst.CopyLocationFrom(loc_temp,false);
                        if (w_entity.IsInherited(Rope) && loc_dst.GetType() == InventoryLocationType.ATTACHMENT)
                            return;
                        if( GameInventory.CanForceSwapEntitiesEx( w_entity, loc_src, receiver_entity, loc_dst ) )
{
                            player.PredictiveForceSwapEntities( w_entity, receiver_entity, loc_dst );
                        }
                    }
                }
            }
        }
    }
References CombineItemsClient(), InventoryLocation::CopyLocationFrom(), ItemManager::GetDraggedIcon(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), InventoryLocation::GetParent(), GetPlayer(), InventoryLocation::GetType(), ItemManager::HideDropzones(), m_HandsIcon, m_Item, m_Lock, m_Parent, name, string::Replace(), InventoryLocation::SetCargoAuto(), InventoryLocation::SetFlip(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), ToRefresh(), x, and y.
FlagAction()
bool Icon::FlagAction (EntityAI entity1, EntityAI entity2, int combinationFlags) inline private
Definition at line 782 of file icon.c.
    {
        int current_flag;
        ContextMenu cmenu = GetGame().GetUIManager().GetMenu().GetContextMenu();
        m_am_entity1 = entity1;
        m_am_entity2 = entity2;
        cmenu.Hide();
        cmenu.Clear();
        int id = -1;
        if( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY2 )
        {
            ItemBase entity = ItemBase.Cast( entity1 );
            entity.CombineItemsClient( ItemBase.Cast( entity2 ) );
            return false;
        }
        if( entity1 == null || entity2 == null || combinationFlags == InventoryCombinationFlags.NONE )
            return true;
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT )
        {
            current_flag = InventoryCombinationFlags.ADD_AS_ATTACHMENT;
            cmenu.Add( "#inv_context_add_as_attachment", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.LOAD_CHAMBER )
        {
            current_flag = InventoryCombinationFlags.LOAD_CHAMBER;
            cmenu.Add( "#inv_context_load_chamber", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.ATTACH_MAGAZINE)
        {
            current_flag = InventoryCombinationFlags.ATTACH_MAGAZINE;
            cmenu.Add("#inv_context_attach_magazine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_CARGO )
        {
            current_flag = InventoryCombinationFlags.ADD_AS_CARGO;
            cmenu.Add( "#inv_context_add_as_cargo", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.SWAP )
        {
            current_flag = InventoryCombinationFlags.SWAP;
            cmenu.Add( "#inv_context_swap", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY )
        {
            current_flag = InventoryCombinationFlags.COMBINE_QUANTITY;
            cmenu.Add( "#inv_context_combine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.SET_ACTION)
        {
            current_flag = InventoryCombinationFlags.SET_ACTION;
            cmenu.Add("#inv_context_attach_magazine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.PERFORM_ACTION)
        {
            current_flag = InventoryCombinationFlags.PERFORM_ACTION;
            cmenu.Add("Perform Action2", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        int m_am_Pos_x,  m_am_Pos_y;
        GetMousePos( m_am_Pos_x, m_am_Pos_y );
        m_am_Pos_x -= 5;
        m_am_Pos_y -= 5;
        MissionGameplay mission = MissionGameplay.Cast( GetGame().GetMission() );
        /*if( combinationFlags & InventoryCombinationFlags.RECIPE_HANDS ||  combinationFlags & InventoryCombinationFlags.RECIPE_ANYWHERE )
        {
            OnPerformRecipe( id );
            return true;
        }
        else /*if( cmenu.Count() == 1 )*/
        //{
            OnPerformCombination( current_flag );
            return true;
        //}
        /*else
        {
            cmenu.Show( m_am_Pos_x, m_am_Pos_y );
            return true;
        }*/
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::ATTACH_MAGAZINE, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, GetGame(), UIManager::GetMenu(), GetMousePos(), CGame::GetUIManager(), InventoryCombinationFlags::LOAD_CHAMBER, mission, InventoryCombinationFlags::NONE, OnPerformCombination(), InventoryCombinationFlags::PERFORM_ACTION, InventoryCombinationFlags::SET_ACTION, and InventoryCombinationFlags::SWAP.
Referenced by CombineItems().
FullScreen()
void Icon::FullScreen () inline private
Definition at line 1378 of file icon.c.
    {
        if( m_IsDragged )
        {
            return;
        }
        GetRootWidget().ClearFlags( WidgetFlags.HEXACTSIZE + WidgetFlags.VEXACTSIZE );
        GetRootWidget().SetSize( 1, 1 );
        m_ColorWidget.SetColor( ARGB( 0, 0, 0, 0 ) );
    }
References ARGB(), m_ColorWidget, and m_IsDragged.
Referenced by HandsPreview::CreateNewIcon(), and DestroyWhiteBackground().
GetCargoPos()
int Icon::GetCargoPos () inline private
Definition at line 1215 of file icon.c.
    {
        return m_CargoPos;
    }
References m_CargoPos.
GetObject()
Object Icon::GetObject () inline private
Definition at line 1400 of file icon.c.
    {
        return m_Obj;
    }
References m_Obj.
Referenced by IconsContainer::AddItem(), Container::Combine(), Container::GetFocusedItem(), RefreshMuzzleIcon(), IconsContainer::RemoveItem(), Container::SelectItem(), and SetActive().
GetPosX()
int Icon::GetPosX () inline private
Definition at line 1850 of file icon.c.
    {
        return m_PosX;
    }
References m_PosX.
Referenced by SetPosEx().
GetPosY()
int Icon::GetPosY () inline private
Definition at line 1855 of file icon.c.
    {
        return m_PosY;
    }
References m_PosY.
Referenced by SetPosEx().
GetSelectedWidget()
Widget Icon::GetSelectedWidget () inline private
Definition at line 79 of file icon.c.
    {
        return m_SelectedPanel;
    }
References m_SelectedPanel.
GetSizeX()
int Icon::GetSizeX () inline private
Definition at line 1860 of file icon.c.
    {
        return m_SizeX;
    }
References m_SizeX.
Referenced by CargoContainerRow::GetIconSize().
GetSizeY()
int Icon::GetSizeY () inline private
Definition at line 1865 of file icon.c.
    {
        return m_SizeY;
    }
References m_SizeY.
Referenced by CargoContainerRow::GetIconSize().
GetSort()
int Icon::GetSort () inline private
Definition at line 1569 of file icon.c.
    {
        return GetMainWidget().GetSort( );
    }
Init()
void Icon::Init (EntityAI obj) inline private
Definition at line 1691 of file icon.c.
    {
        InitEx( obj );
    }
References InitEx().
Referenced by HandsPreview::CreateNewIcon().
InitEx()
void Icon::InitEx (EntityAI obj, bool refresh = true) inline private
Definition at line 1639 of file icon.c.
    {
        if ( obj != m_Obj )
        {
            if ( m_Obj )
            {
                m_Obj.GetOnItemFlipped().Remove( UpdateFlip );
                m_Obj.GetOnViewIndexChanged().Remove( SetItemPreview );
            }
            if ( obj )
            {
                obj.GetOnItemFlipped().Insert( UpdateFlip );
                obj.GetOnViewIndexChanged().Insert( SetItemPreview );
            }
        }
        if (m_HandsIcon)
        {
            m_ItemPreview.SetForceFlipEnable(true);
            m_ItemPreview.SetForceFlip(false);
        }
        m_Obj   = obj;
        m_Item  = ItemBase.Cast( m_Obj );
        m_Lock = null;
        SetItemPreviewEx(refresh);
        WidgetEventHandler.GetInstance().RegisterOnDrag( GetMainWidget(),  this, "CreateWhiteBackground" );
        WidgetEventHandler.GetInstance().RegisterOnDrop( GetMainWidget(),  this, "DestroyWhiteBackground" );
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( GetMainWidget(),  this, "DropReceivedFromMain" );
        WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( GetMainWidget(),  this, "MouseClick" );
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( GetMainWidget().FindAnyWidget( "Swap" ),  this, "Swap" );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( GetMainWidget().FindAnyWidget( "Swap" ),  this, "DraggingOverSwap" );
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( GetMainWidget().FindAnyWidget( "Combine" ),  this, "Combine" );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( GetMainWidget().FindAnyWidget( "Combine" ),  this, "DraggingOverCombine" );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( GetMainWidget(),  this, "DraggingOver" );
        WidgetEventHandler.GetInstance().RegisterOnMouseEnter( GetMainWidget(),  this, "MouseEnter" );
        WidgetEventHandler.GetInstance().RegisterOnMouseLeave( GetMainWidget(),  this, "MouseLeave" );
        WidgetEventHandler.GetInstance().RegisterOnDoubleClick( GetMainWidget(),  this, "DoubleClick" );
        SetItemSizeEx(refresh);
        CheckIsWeapon();
        CheckIsMagazineEx(refresh);
        CheckHasTemperature();
        CheckHasQuantityEx(refresh);
        m_RootWidget.FindAnyWidget( "Reserved" ).Show( false, refresh );
        if (refresh)
            Refresh();
    }
References CheckHasQuantityEx(), CheckHasTemperature(), CheckIsMagazineEx(), CheckIsWeapon(), FindAnyWidget(), WidgetEventHandler::GetInstance(), m_HandsIcon, m_Item, m_ItemPreview, m_Lock, m_Obj, m_RootWidget, Refresh(), WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDrag(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDrop(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseEnter(), WidgetEventHandler::RegisterOnMouseLeave(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), SetItemPreview(), SetItemPreviewEx(), SetItemSizeEx(), and UpdateFlip().
Referenced by Init(), and Container::InitIconEx().
InitLock()
void Icon::InitLock (EntityAI parent, EntityAI obj, int x_pos, int y_pos, bool flip) inline private
Definition at line 1618 of file icon.c.
    {
        m_Lock  = parent;
        m_Obj   = obj;
        m_Item  = ItemBase.Cast( m_Obj );
        SetPos( x_pos, y_pos );
        UpdateFlip( flip );
        ItemManager.GetInstance().SetWidgetDraggable( GetMainWidget(), false );
        WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( GetMainWidget(), this, "MouseClick" );
        WidgetEventHandler.GetInstance().RegisterOnDropReceived( GetMainWidget(),  this, "DropReceivedFromMain" );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( GetMainWidget(),  this, "DraggingOver" );
        m_RootWidget.FindAnyWidget( "Reserved" ).Show( true );
        m_ItemPreview.SetForceFlipEnable(true);
        m_ItemPreview.SetForceFlip(flip);
        SetItemPreview();
        Refresh();
    }
References ItemManager::GetInstance(), WidgetEventHandler::GetInstance(), m_Item, m_ItemPreview, m_Lock, m_Obj, m_RootWidget, Refresh(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), ItemPreviewWidget::SetForceFlip(), ItemPreviewWidget::SetForceFlipEnable(), SetItemPreview(), SetPos(), ItemManager::SetWidgetDraggable(), and UpdateFlip().
IsDragged()
bool Icon::IsDragged () inline private
Definition at line 84 of file icon.c.
    {
        return m_IsDragged;
    }
References m_IsDragged.
Referenced by HandsPreview::UpdateInterval().
MouseClick()
void Icon::MouseClick (Widget w, int x, int y, int button) inline private
Definition at line 871 of file icon.c.
    {
        if( button == MouseState.RIGHT )
        {
            if( m_Lock )
            {
                GetGame().GetPlayer().GetHumanInventory().ClearUserReservedLocationSynced( m_Item );
            }
            else
            {
                if( m_Item && m_Item.IsItemBase() )
                {
                    m_Item.OnRightClick();
                    if( m_HasQuantity )
                        SetQuantity();
                    #ifdef DEVELOPER
                    if( GetDayZGame().IsLeftCtrlDown() )
                        ShowActionMenu( m_Item );
                    #endif
                }
            }
        }
        else if (!m_Lock)
        {
            if ( button == MouseState.MIDDLE )
            {
                InspectItem( m_Item );
            }
            else if ( button == MouseState.LEFT )
            {
                PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
                if (g_Game.IsLeftCtrlDown())
                {
                    if ( player && player.CanDropEntity( m_Item ) )
                    {
                        if ( m_Item.GetTargetQuantityMax() < m_Item.GetQuantity() )
                            m_Item.SplitIntoStackMaxClient( null, -1 );
                        else
{
                            player.PhysicalPredictiveDropItem( m_Item );
                        }
                        ItemManager.GetInstance().SetWidgetDraggable( w, false );
                    }
                }
                else
                {
                    InventoryLocation il = new InventoryLocation;
                    m_Obj.GetInventory().GetCurrentInventoryLocation( il );
                    bool draggable = !player.GetInventory().HasInventoryReservation( m_Obj, null ) && !player.GetInventory().IsInventoryLocked() && !player.IsItemsToDelete();
                    draggable = draggable && ( m_Obj.GetHierarchyRoot() && m_Obj.GetInventory().CanRemoveEntity() || !m_Obj.GetHierarchyRoot() && AttachmentsOutOfReach.IsAttachmentReachable( m_Obj, "", il.GetSlot() ) );
                    ItemManager.GetInstance().SetWidgetDraggable( w, draggable );
                }
            }
        }
    }
References g_Game, GetDayZGame(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetSlot(), LayoutHolder::InspectItem(), AttachmentsOutOfReach::IsAttachmentReachable(), IsLeftCtrlDown(), m_HasQuantity, m_Item, m_Lock, m_Obj, SetQuantity(), and ItemManager::SetWidgetDraggable().
MouseEnter()
bool Icon::MouseEnter (Widget w, int x, int y) inline private
Definition at line 351 of file icon.c.
    {
        if( !m_IsDragged )
        {
            PrepareOwnedTooltip( m_Obj, x, y );
            m_SelectedPanel.Show( true );
        }
        return true;
    }
References m_IsDragged, m_Obj, m_SelectedPanel, x, and y.
MouseLeave()
bool Icon::MouseLeave (Widget w, Widget s, int x, int y) inline private
Definition at line 362 of file icon.c.
    {
        HideOwnedTooltip();
        if( !m_IsDragged )
        {
            m_SelectedPanel.Show( false );
        }
        return true;
    }
References m_IsDragged, and m_SelectedPanel.
OnDraggingOverBackground()
void Icon::OnDraggingOverBackground (Widget w, int x, int y, Widget reciever) inline private
Definition at line 1281 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        EntityAI entity = EntityAI.Cast( m_Obj );
        EntityAI owner = entity.GetHierarchyParent();
        if( owner && owner.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
        {
            ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
        }
        else if( !m_HandsIcon )
        {
            ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
        }
        if( w == null || reciever == null )
        {
            return;
        }
        Pos pa;
        reciever.GetUserData( pa );
        if( m_Parent )
        {
            ContainerWithCargo item = ContainerWithCargo.Cast( m_Parent.m_Parent );
            if( item )
            {
                item.DraggingOverGrid( w, m_PosY + pa.y, m_PosX + pa.x, reciever );
            }
            HandsContainer hands_item = HandsContainer.Cast( m_Parent.m_Parent );
            if( hands_item )
            {
                hands_item.DraggingOverGrid( w, m_PosY + pa.y, m_PosX + pa.x, reciever, null );
            }
        }
    }
References HandsContainer::DraggingOverGrid(), GetGame(), ItemManager::GetInstance(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ItemManager::HideDropzones(), m_HandsIcon, m_Obj, m_Parent, m_PosX, m_PosY, and Pos().
OnPerformCombination()
void Icon::OnPerformCombination (int combinationFlags) inline private
Definition at line 530 of file icon.c.
    {
        PlayerBase m_player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( m_am_entity1 == null || m_am_entity2 == null ) return;
        if( combinationFlags == InventoryCombinationFlags.NONE ) return;
        Weapon_Base wpn;
        Magazine mag;
        if( combinationFlags & InventoryCombinationFlags.LOAD_CHAMBER )
        {
            if( Class.CastTo(wpn,  m_am_entity1 ) && Class.CastTo(mag,  m_am_entity2 ) )
            {
                if( m_player.GetWeaponManager().CanLoadBullet(wpn, mag) )
                {
                    m_player.GetWeaponManager().LoadBullet(mag);
                    return;
                }
            }
        }
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT )
        {
            float stackable = m_am_entity2.GetTargetQuantityMax(-1);
            if ( stackable == 0 || stackable >= m_am_entity2.GetQuantity() )
            {
                m_player.PredictiveTakeEntityToTargetAttachment(m_am_entity1, m_am_entity2);
            }
            else
            {
                InventoryLocation il = new InventoryLocation;
                m_am_entity1.GetInventory().FindFreeLocationFor( m_am_entity2, FindInventoryLocationType.ATTACHMENT, il );
                ItemBase.Cast(m_am_entity2).SplitIntoStackMaxToInventoryLocationClient( il );
            }
        }
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_CARGO )
        {
            SplitItemUtils.TakeOrSplitToInventory(m_player, m_am_entity1, m_am_entity2);
        }
        if( combinationFlags & InventoryCombinationFlags.SWAP )
        {
            if( !m_player.PredictiveSwapEntities( m_am_entity1, m_am_entity2 ) && m_player.GetHumanInventory().CanAddEntityInHands( m_am_entity2 ) )
            {
                m_player.PredictiveTakeEntityToHands( m_am_entity2 );
            }
        }
        if( combinationFlags & InventoryCombinationFlags.TAKE_TO_HANDS )
        {
            if( m_player.GetHumanInventory().CanAddEntityInHands( m_am_entity2 ) )
            {
                m_player.PredictiveTakeEntityToHands( m_am_entity2 );
            }
        }
        if( combinationFlags & InventoryCombinationFlags.PERFORM_ACTION )
        {
            ActionManagerClient amc;
            Class.CastTo(amc, m_player.GetActionManager());
            if( m_am_entity1 == m_player.GetHumanInventory().GetEntityInHands() )
            {
                amc.PerformActionFromInventory(ItemBase.Cast( m_am_entity1 ),ItemBase.Cast( m_am_entity2 ));
            }
            else
            {
                amc.PerformActionFromInventory(ItemBase.Cast( m_am_entity2 ),ItemBase.Cast( m_am_entity1 ));
            }
        }
        if( combinationFlags & InventoryCombinationFlags.SET_ACTION )
        {
            ActionManagerClient amc2;
            Class.CastTo(amc2, m_player.GetActionManager());
            if( m_am_entity1 == m_player.GetHumanInventory().GetEntityInHands() )
            {
                amc2.SetActionFromInventory(ItemBase.Cast( m_am_entity1 ),ItemBase.Cast( m_am_entity2 ));
            }
            else
            {
                amc2.SetActionFromInventory(ItemBase.Cast( m_am_entity2 ),ItemBase.Cast( m_am_entity1 ));
            }
        }
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, Class::CastTo(), GetGame(), GetPlayer(), InventoryCombinationFlags::LOAD_CHAMBER, m_player, InventoryCombinationFlags::NONE, InventoryCombinationFlags::PERFORM_ACTION, ActionManagerClient::PerformActionFromInventory(), InventoryCombinationFlags::SET_ACTION, ActionManagerClient::SetActionFromInventory(), InventoryCombinationFlags::SWAP, InventoryCombinationFlags::TAKE_TO_HANDS, and SplitItemUtils::TakeOrSplitToInventory().
Referenced by FlagAction(), and ShowActionMenuCombine().
OnPerformRecipe()
void Icon::OnPerformRecipe (int id) inline private
Definition at line 742 of file icon.c.
    {
        if( m_am_entity1 == null || m_am_entity2 == null ) return;
        Debug.Log("OnPerformRecipe called for id:"+id.ToString(),"recipes");
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.GetCraftingManager().SetInventoryCraft( id, ItemBase.Cast( m_am_entity1 ), ItemBase.Cast( m_am_entity2 ) );
    }
References GetGame(), GetPlayer(), Debug::Log(), and ToString().
Refresh()
override void Icon::Refresh () inline private
Definition at line 1350 of file icon.c.
    {
        super.Refresh();
        if ( !m_HandsIcon )
            SetPos();
        if ( m_HasTemperature )
            SetTemperature();
        if ( m_IsWeapon )
            RefreshMuzzleIcon();
        if ( m_HasQuantity )
            SetQuantity();
    }
References m_HandsIcon, m_HasQuantity, m_HasTemperature, m_IsWeapon, RefreshMuzzleIcon(), SetPos(), SetQuantity(), and SetTemperature().
Referenced by HandsPreview::CreateNewIcon(), CreateWhiteBackground(), DestroyWhiteBackground(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), InitEx(), InitLock(), and RefreshIconPos().
RefreshIconPos()
void Icon::RefreshIconPos () inline private
Definition at line 1372 of file icon.c.
    {
        Refresh();
        GetMainWidget().Update();
    }
References Refresh().
Referenced by RefreshPos().
RefreshMuzzleIcon()
void Icon::RefreshMuzzleIcon () inline private
Definition at line 1405 of file icon.c.
    {
        Weapon_Base wpn = Weapon_Base.Cast( GetObject() );
        if( wpn )
        {
            int i;
            ImageWidget ammo_icon;
            if (!wpn.IsShowingChamberedBullet())
            {
                for (i = 0; i < m_AmmoIcons.Count(); i++)
                {
                    ammo_icon = m_AmmoIcons.Get(i);
                    ammo_icon.Show(false);
                }
            /*  int bullet_count = 0;
                int fireout_count = 0;
                for ( i = 0; i < wpn.GetMuzzleCount(); i++ )
                {
                    if (wpn.IsChamberFull(i))
                    {
                        if (wpn.IsChamberFiredOut(i))
{
                            fireout_count++;
                        }
                        else
{
                            bullet_count++;
                        }
                    }
                }
                int j;
                i = 0;
                for ( j= 0; j < bullet_count; j++ )
                {
                    if ( i > m_AmmoIcons.Count() )
                    {
                        //add plus ammo
                        break;
                    }
                    ammo_icon = m_AmmoIcons.Get(i);
                    ammo_icon.Show( true );
                    ammo_icon.SetImage( 0 );
                    i++;
                }
                for ( j= 0; j < fireout_count; j++ )
                {
                    if ( i > m_AmmoIcons.Count() )
                    {
                        //add plus ammo
                        break;
                    }
                    ammo_icon = m_AmmoIcons.Get(i);
                    ammo_icon.Show( true );
                    ammo_icon.SetImage( 1 );
                    i++;
                }
                for (j = i; j < m_AmmoIcons.Count(); j++)
                {
                    ammo_icon = m_AmmoIcons.Get(j);
                    ammo_icon.Show(false);
                }*/
            }
            else
            {
                //TODO MW - add more conplex logic
                for ( i = 0; i < wpn.GetMuzzleCount(); i++ )
                {
                    if ( i > m_AmmoIcons.Count() )
                    {
                        //add plus ammo
                        break;
                    }
                    ammo_icon = m_AmmoIcons.Get(i);
                    if( wpn.IsChamberFull( i ) )
                    {
                        if( wpn.IsJammed() )
{
                            ammo_icon.Show( true );
                            ammo_icon.SetImage( 2 );
                        }
                        else if( wpn.IsChamberFiredOut( i ) )
{
                            ammo_icon.Show( true );
                            ammo_icon.SetImage( 1 );
                        }
                        else
{
                            ammo_icon.Show( true );
                            ammo_icon.SetImage( 0 );
                        }
                    }
                    else
                    {
                        ammo_icon.Show( false );
                    }
                }
            }
        }
    }
References GetObject(), Weapon_Base::IsShowingChamberedBullet(), and m_AmmoIcons.
Referenced by Refresh(), and UpdateInterval().
RefreshPos()
void Icon::RefreshPos (int row, int column) inline private
Definition at line 1389 of file icon.c.
    {
        if( row != m_PosY || column != m_PosX )
        {
            m_PosX = column;
            m_PosY = row;
            SetPos();
            RefreshIconPos();
        }
    }
References m_PosX, m_PosY, RefreshIconPos(), and SetPos().
Referenced by AttachmentCategoriesRow::DropReceived().
RefreshQuickbar()
void Icon::RefreshQuickbar () inline private
Definition at line 125 of file icon.c.
    {
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
        HideOwnedTooltip();
        if( menu )
        {
            menu.RefreshQuickbar();
        }
    }
References GetGame(), InventoryMenu(), and MENU_INVENTORY.
RevertToOriginalFlip()
void Icon::RevertToOriginalFlip () inline private
Definition at line 1333 of file icon.c.
    {
        if (m_Item)
        {
            m_Item.GetInventory().SetFlipCargo(m_PreviousFlipOrientation);
            int ww, hh;
            GetGame().GetInventoryItemSize(m_Item, ww, hh);
            if (m_PreviousFlipOrientation)
                SetSize(hh, ww);
            else
                SetSize(ww, hh);
            SetSize();
        }
    }
References GetGame(), CGame::GetInventoryItemSize(), m_Item, m_PreviousFlipOrientation, and SetSize().
Referenced by DestroyWhiteBackground(), and ~Icon().
SetActive()
override void Icon::SetActive (bool active) inline private
Definition at line 89 of file icon.c.
    {
        super.SetActive( active );
        if( active && GetObject() )
        {
            float x, y;
            GetMainWidget().GetScreenPos( x, y );
            PrepareOwnedTooltip( EntityAI.Cast( GetObject() ), -1, y );
        }
        m_SelectedPanel.Show( active );
    }
References GetObject(), m_SelectedPanel, x, and y.
Referenced by HandsPreview::SetDefaultFocus(), CargoContainerRow::SetFocus(), Container::SetLastActive(), HandsPreview::SetLastFocus(), Container::Unfocus(), HandsPreview::Unfocus(), CargoContainerRow::UnfocusAll(), and Container::UpdateSelection().
SetCargoPos()
void Icon::SetCargoPos (int x) inline private
Definition at line 1220 of file icon.c.
    {
        GetMainWidget().SetSort( x );
        m_CargoPos = x;
    }
References m_CargoPos, and x.
Referenced by Container::InitIconEx(), and Container::MovedInCargo().
SetItemPreview()
void Icon::SetItemPreview () inline private
Definition at line 1582 of file icon.c.
    {
        SetItemPreviewEx();
    }
References SetItemPreviewEx().
Referenced by InitEx(), InitLock(), and ~Icon().
SetItemPreviewEx()
void Icon::SetItemPreviewEx (bool refresh = true) inline private
Definition at line 1574 of file icon.c.
    {
        m_ItemPreview.Show( true, refresh );
        m_ItemPreview.SetItem( EntityAI.Cast( m_Obj ) );
        m_ItemPreview.SetModelOrientation( "0 0 0" );
        m_ItemPreview.SetView( m_Obj.GetViewIndex() );
    }
References m_ItemPreview, m_Obj, ItemPreviewWidget::SetItem(), ItemPreviewWidget::SetModelOrientation(), and ItemPreviewWidget::SetView().
Referenced by InitEx(), and SetItemPreview().
SetItemSize()
void Icon::SetItemSize () inline private
Definition at line 1600 of file icon.c.
    {
        SetItemSizeEx();
    }
References SetItemSizeEx().
SetItemSizeEx()
void Icon::SetItemSizeEx (bool refresh = true) inline private
Definition at line 1587 of file icon.c.
    {
        #ifdef PLATFORM_CONSOLE
        m_ItemSizePanel.Show( true, refresh );
        m_ItemSizeWidget.Show( true, refresh );
        int size_x, size_y;
        GetGame().GetInventoryItemSize( m_Item, size_x, size_y );
        int capacity = size_x * size_y;
        m_ItemSizeWidget.SetText( capacity.ToString() );
        #endif
    }
References GetGame(), CGame::GetInventoryItemSize(), m_Item, m_ItemSizePanel, and m_ItemSizeWidget.
Referenced by InitEx(), and SetItemSize().
SetLayoutName()
override void Icon::SetLayoutName () inline private
Definition at line 1176 of file icon.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_LayoutName = WidgetLayoutName.IconXbox;
        #else
            switch( InventoryMenu.GetWidthType() )
            {
                case ScreenWidthType.NARROW:
                {
                    m_LayoutName = WidgetLayoutName.IconNarrow;
                    break;
                }
                case ScreenWidthType.MEDIUM:
                {
                    m_LayoutName = WidgetLayoutName.IconMedium;
                    break;
                }
                case ScreenWidthType.WIDE:
                {
                    m_LayoutName = WidgetLayoutName.IconWide;
                    break;
                }
            }
        #endif
    }
References WidgetLayoutName::IconMedium, WidgetLayoutName::IconNarrow, WidgetLayoutName::IconWide, WidgetLayoutName::IconXbox, and InventoryMenu().
SetParentWidget()
override void Icon::SetParentWidget () inline private
Definition at line 102 of file icon.c.
    {
        #ifndef PLATFORM_CONSOLE
        if( m_Parent.IsInherited( HandsPreview ) )
        {
            super.SetParentWidget();
        }
        else
        {
            if( m_Parent != null )
            {
                CargoContainer grid_container = CargoContainer.Cast( m_Parent );
                if( grid_container )
                {
                    m_ParentWidget = grid_container.GetMainWidget();
                }
            }
        }
        #else
        super.SetParentWidget();
        #endif
    }
References m_Parent.
SetPos() [1/2]
void Icon::SetPos () inline private
Definition at line 1904 of file icon.c.
    {
        SetPosEx();
    }
References SetPosEx().
Referenced by InitLock(), Refresh(), and RefreshPos().
SetPos() [2/2]
void Icon::SetPos (int x, int y) inline private
Definition at line 1209 of file icon.c.
    {
        m_PosX = x;
        m_PosY = y;
    }
References m_PosX, m_PosY, x, and y.
SetPosEx()
void Icon::SetPosEx (bool refresh = true) inline private
Definition at line 1870 of file icon.c.
    {
        CargoContainer c_parent = CargoContainer.Cast( m_Parent );
        HandsPreview h_parent = HandsPreview.Cast( m_Parent );
        Widget rootWidget = GetRootWidget();
        float icon_size, space_size;
        if ( c_parent )
        {
            icon_size = c_parent.GetIconSize();
            space_size = c_parent.GetSpaceSize();
        }
        else if ( h_parent )
        {
            icon_size = h_parent.GetIconSize();
            if (rootWidget)
            {
                rootWidget.SetFlags( WidgetFlags.EXACTSIZE, refresh );
            }
        }
        if (rootWidget)
        {
            #ifndef PLATFORM_CONSOLE
                rootWidget.SetPos( icon_size * GetPosX() + ( GetPosX() + 1 ) * space_size, icon_size * GetPosY() + ( GetPosY() + 1 ) * space_size, refresh );
                rootWidget.SetSize( icon_size * m_SizeX + ( m_SizeX ) * space_size, icon_size * m_SizeY + ( m_SizeY ) * space_size, refresh );
            #else
                int row = m_CargoPos / 5;
                int column = m_CargoPos % 5;
                rootWidget.SetPos( icon_size * column, icon_size * row, refresh );
                rootWidget.SetSize( icon_size, icon_size, refresh );
            #endif
        }
    }
References HandsPreview::GetIconSize(), GetPosX(), GetPosY(), m_CargoPos, m_Parent, m_SizeX, and m_SizeY.
Referenced by Container::InitIconEx(), and SetPos().
SetPosX()
void Icon::SetPosX (int x) inline private
Definition at line 1830 of file icon.c.
    {
        m_PosX = x;
    }
References m_PosX, and x.
Referenced by Container::InitIconEx().
SetPosY()
void Icon::SetPosY (int y) inline private
Definition at line 1835 of file icon.c.
    {
        m_PosY = y;
    }
References m_PosY, and y.
Referenced by Container::InitIconEx().
SetQuantity()
void Icon::SetQuantity () inline private
Definition at line 1513 of file icon.c.
    {
        if (m_Item)
        {
            int quantityType = QuantityConversions.HasItemQuantity(m_Item);
            if (quantityType != QUANTITY_HIDDEN && m_CurrQuantity != QuantityConversions.GetItemQuantity(m_Item))
            {
                m_CurrQuantity = QuantityConversions.GetItemQuantity(m_Item);
                if (quantityType == QUANTITY_COUNT)
                {
                    string q_text = QuantityConversions.GetItemQuantityText(m_Item);
                    if (QuantityConversions.GetItemQuantityMax(m_Item) == 1 || q_text == "")
                    {
                        m_QuantityStack.Show(false);
                    }
                    else
                    {
                        m_QuantityItem.SetText(q_text);
                        m_QuantityStack.Show(true);
                    }
                    m_QuantityProgress.Show(false);
                }
                else if (quantityType == QUANTITY_PROGRESS)
                {
                    float progress_max  = m_QuantityProgress.GetMax();
                    int max             = m_Item.GetQuantityMax();
                    int count           = m_Item.ConfigGetInt("count");
                    float quantity      = m_CurrQuantity;
                    if (count > 0)
                    {
                        max = count;
                    }
                    if (max > 0)
                    {
                        float value = Math.Round((quantity / max) * 100);
                        m_QuantityProgress.SetCurrent(value);
                    }
                    m_QuantityStack.Show(false);
                    m_QuantityProgress.Show(true);
                }
            }
        }
    }
References QuantityConversions::GetItemQuantity(), QuantityConversions::GetItemQuantityMax(), QuantityConversions::GetItemQuantityText(), QuantityConversions::HasItemQuantity(), m_CurrQuantity, m_Item, m_QuantityItem, m_QuantityProgress, m_QuantityStack, QUANTITY_COUNT, QUANTITY_HIDDEN, QUANTITY_PROGRESS, and Math::Round().
Referenced by MouseClick(), Refresh(), HandsPreview::RefreshQuantity(), Container::SplitItem(), and UpdateInterval().
SetSize() [1/2]
void Icon::SetSize () inline private
Definition at line 1909 of file icon.c.
    {
        CargoContainer c_parent = CargoContainer.Cast( m_Parent );
        HandsPreview h_parent = HandsPreview.Cast( m_Parent );
        float icon_size, space_size;
        Widget rootWidget = GetRootWidget();
        if( c_parent )
        {
            icon_size = c_parent.GetIconSize();
            space_size = c_parent.GetSpaceSize();
        }
        else if( h_parent )
        {
            icon_size = h_parent.GetIconSize();
            if (rootWidget)
            {
                GetRootWidget().SetFlags( WidgetFlags.EXACTSIZE );
            }
        }
        if (rootWidget)
        {
        #ifndef PLATFORM_CONSOLE
            GetRootWidget().SetSize( icon_size * m_SizeX + ( m_SizeX ) * space_size, icon_size * m_SizeY + ( m_SizeY ) * space_size );
        #else
            GetRootWidget().SetSize( icon_size, icon_size );
        #endif
        }
    }
References HandsPreview::GetIconSize(), m_Parent, m_SizeX, and m_SizeY.
Referenced by CreateWhiteBackground(), RevertToOriginalFlip(), and UpdateFlip().
SetSize() [2/2]
void Icon::SetSize (int x, int y) inline private
Definition at line 1203 of file icon.c.
    {
        m_SizeX = x;
        m_SizeY = y;
    }
References m_SizeX, m_SizeY, x, and y.
Referenced by Container::InitIconEx(), and Hud::SetCursorIconScale().
SetSizeX()
void Icon::SetSizeX (int x) inline private
Definition at line 1840 of file icon.c.
    {
        m_SizeX = x;
    }
References m_SizeX, and x.
SetSizeY()
void Icon::SetSizeY (int y) inline private
Definition at line 1845 of file icon.c.
    {
        m_SizeY = y;
    }
References m_SizeY, and y.
SetSort()
void Icon::SetSort (int index) inline private
Definition at line 1563 of file icon.c.
    {
        GetMainWidget().SetSort( index );
        GetMainWidget().Update();
    }
SetTemperature()
void Icon::SetTemperature () inline private
Definition at line 1367 of file icon.c.
    {
        ItemManager.GetInstance().SetIconTemperature( EntityAI.Cast( m_Obj ), m_RootWidget );
    }
References ItemManager::GetInstance(), m_Obj, m_RootWidget, and ItemManager::SetIconTemperature().
Referenced by Refresh(), UpdateInterval(), and IconsContainer::UpdateItemsTemperature().
ShowActionMenuCombine()
void Icon::ShowActionMenuCombine (EntityAI entity1, EntityAI entity2, int combinationFlags, Widget w, bool color_test) inline private
Definition at line 618 of file icon.c.
    {
        int current_flag;
        ContextMenu cmenu = GetGame().GetUIManager().GetMenu().GetContextMenu();
        m_am_entity1 = entity1;
        m_am_entity2 = entity2;
        cmenu.Hide();
        cmenu.Clear();
        int id = -1;
        if( entity1 == null || entity2 == null ) return;
        if( combinationFlags == InventoryCombinationFlags.NONE )
        {
            if( color_test )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( entity2 );
            }
            return;
        }
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_ATTACHMENT )
        {
            current_flag = InventoryCombinationFlags.ADD_AS_ATTACHMENT;
            cmenu.Add( "#inv_context_add_as_attachment", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.LOAD_CHAMBER )
        {
            current_flag = InventoryCombinationFlags.LOAD_CHAMBER;
            cmenu.Add( "#inv_context_load_chamber", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.ATTACH_MAGAZINE)
        {
            current_flag = InventoryCombinationFlags.ATTACH_MAGAZINE;
            cmenu.Add("#inv_context_attach_magazine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.ADD_AS_CARGO && !(combinationFlags & InventoryCombinationFlags.SET_ACTION) )
        {
            current_flag = InventoryCombinationFlags.ADD_AS_CARGO;
            cmenu.Add( "#inv_context_add_as_cargo", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.SWAP )
        {
            current_flag = InventoryCombinationFlags.SWAP;
            cmenu.Add( "#inv_context_swap", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY )
        {
            current_flag = InventoryCombinationFlags.COMBINE_QUANTITY;
            cmenu.Add( "#inv_context_combine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.SET_ACTION)
        {
            current_flag = InventoryCombinationFlags.SET_ACTION;
            cmenu.Add("#inv_context_attach_magazine", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        if(combinationFlags & InventoryCombinationFlags.PERFORM_ACTION)
        {
            current_flag = InventoryCombinationFlags.PERFORM_ACTION;
            cmenu.Add("Perform action", this, "OnPerformCombination", new Param1<int>( current_flag ) );
        }
        int m_am_Pos_x,  m_am_Pos_y;
        GetMousePos( m_am_Pos_x, m_am_Pos_y );
        m_am_Pos_x -= 5;
        m_am_Pos_y -= 5;
        if( color_test )
        {
            ItemManager.GetInstance().HideDropzones();
            ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
            ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
        }
        /*if( combinationFlags & InventoryCombinationFlags.RECIPE_HANDS ||  combinationFlags & InventoryCombinationFlags.RECIPE_ANYWHERE )
        {
            if( !color_test )
            {
                OnPerformRecipe( id );
                return;
            }
        }
        else*/ if( cmenu.Count() >= 1 )
        {
            if( !color_test )
            {
                OnPerformCombination( current_flag );
                return;
            }
        }
        else if( combinationFlags & InventoryCombinationFlags.COMBINE_QUANTITY2 )
        {
            if( color_test )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
                ItemManager.GetInstance().HideDropzones();
                ItemManager.GetInstance().GetCenterDropzone().SetAlpha( 1 );
            }
            else
            {
                ItemBase entity = ItemBase.Cast( entity1 );
                entity.CombineItemsClient( ItemBase.Cast( entity2 ) );
            }
            return;
        }
        else
        {
            if( color_test )
            {
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
                ItemManager.GetInstance().ShowSourceDropzone( entity2 );
            }
        /*  else
            {
                cmenu.Show( m_am_Pos_x, m_am_Pos_y );
            }*/
        }
    }
References InventoryCombinationFlags::ADD_AS_ATTACHMENT, InventoryCombinationFlags::ADD_AS_CARGO, InventoryCombinationFlags::ATTACH_MAGAZINE, ColorManager::COMBINE_COLOR, InventoryCombinationFlags::COMBINE_QUANTITY, InventoryCombinationFlags::COMBINE_QUANTITY2, ItemManager::GetCenterDropzone(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), UIManager::GetMenu(), GetMousePos(), CGame::GetUIManager(), ItemManager::HideDropzones(), InventoryCombinationFlags::LOAD_CHAMBER, InventoryCombinationFlags::NONE, OnPerformCombination(), InventoryCombinationFlags::PERFORM_ACTION, ColorManager::RED_COLOR, InventoryCombinationFlags::SET_ACTION, ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and InventoryCombinationFlags::SWAP.
Referenced by Combine(), and DraggingOverCombine().
Swap()
void Icon::Swap (Widget w, int x, int y, Widget receiver) inline private
Definition at line 1075 of file icon.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        ItemPreviewWidget receiver_ipw = ItemPreviewWidget.Cast( receiver.FindAnyWidget( "Render" ) );
        if( m_HandsIcon )
        {
            receiver_ipw = ItemPreviewWidget.Cast( receiver.GetParent().FindAnyWidget( "Render" ) );
        }
        ItemPreviewWidget w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        if( w_ipw == null )
        {
            w_ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        }
        if( w_ipw == null )
        {
            return;
        }
        InventoryItem receiver_entity = InventoryItem.Cast( receiver_ipw.GetItem() );
        InventoryItem w_entity = InventoryItem.Cast( w_ipw.GetItem() );
        if( !w_entity )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
        Weapon_Base wpn;
        Magazine mag;
        if( Class.CastTo(wpn,  item_in_hands ) && Class.CastTo(mag,  w_entity ) && Class.CastTo(wpn,  mag.GetHierarchyParent() ) )
        {
            return;
        }
        InventoryLocation il_fswap = new InventoryLocation;
        Icon icon = ItemManager.GetInstance().GetDraggedIcon();
        int index = player.GetHumanInventory().FindUserReservedLocationIndex(receiver_entity);
        if(index>=0)
        {
            player.GetHumanInventory().GetUserReservedLocation( index, il_fswap);
            if( GameInventory.CanForceSwapEntitiesEx( w_entity, null, receiver_entity, il_fswap ))
            {
                if( m_HandsIcon && !player.GetInventory().HasInventoryReservation( item_in_hands, null ) && !player.IsItemsToDelete() )
                {
                    GetGame().GetPlayer().PredictiveForceSwapEntities( w_entity, receiver_entity, il_fswap );
                }
            }
            else
            {
                if( GameInventory.CanSwapEntitiesEx( w_entity, receiver_entity  ) )
                {
                    if( !player.GetInventory().HasInventoryReservation( item_in_hands, null ) && !player.IsItemsToDelete() )
                    {
                        GetGame().GetPlayer().PredictiveSwapEntities( w_entity, receiver_entity );
                        if( m_Parent.IsInherited( IconsContainer ) )
{
                            ToRefresh( this, icon );
                        }
                    }
                }
            }
        }
        else
        {
            if( GameInventory.CanSwapEntitiesEx( w_entity, receiver_entity  ) )
            {
                if( !player.GetInventory().HasInventoryReservation( item_in_hands, null ) && !player.IsItemsToDelete() )
                {
                    GetGame().GetPlayer().PredictiveSwapEntities( w_entity, receiver_entity );
                    if( m_Parent.IsInherited( IconsContainer ) )
                    {
                        ToRefresh( this, icon );
                    }
                }
            }
            else if( GameInventory.CanForceSwapEntitiesEx( w_entity, null, receiver_entity, il_fswap ))
            {
                if( m_HandsIcon && !player.GetInventory().HasInventoryReservation( item_in_hands, null ) && !player.IsItemsToDelete() )
                {
                    GetGame().GetPlayer().PredictiveForceSwapEntities( w_entity, receiver_entity, il_fswap );
                }
            }
        }
    }
References Class::CastTo(), ItemManager::GetDraggedIcon(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), GetPlayer(), ItemManager::HideDropzones(), m_HandsIcon, m_Parent, name, string::Replace(), ItemManager::SetIsDragging(), and ToRefresh().
ToRefresh()
void Icon::ToRefresh (Icon icon, Icon icon2) inline private
Definition at line 1170 of file icon.c.
    {
        ( IconsContainer.Cast( m_Parent ) ).RemoveItem( icon );
        ( IconsContainer.Cast( m_Parent ) ).RemoveItem( icon2 );
    }
References m_Parent.
Referenced by DropReceivedFromMain(), and Swap().
UpdateFlip()
void Icon::UpdateFlip (bool flipped) inline private
Definition at line 1605 of file icon.c.
    {
        int size_x, size_y;
        GetGame().GetInventoryItemSize( m_Item, size_x, size_y );
        if ( flipped )
            SetSize( size_y, size_x );
        else
            SetSize( size_x, size_y );
        SetSize();
    }
References GetGame(), CGame::GetInventoryItemSize(), m_Item, and SetSize().
Referenced by InitEx(), InitLock(), and ~Icon().
UpdateInterval()
override void Icon::UpdateInterval () inline private
Definition at line 1939 of file icon.c.
    {
        if ( m_Item )
        {
            if ( m_HasTemperature )
                SetTemperature();
            if ( m_IsWeapon )
                RefreshMuzzleIcon();
            if ( m_HasQuantity )
                SetQuantity();
        }
    }
References m_HasQuantity, m_HasTemperature, m_IsWeapon, m_Item, RefreshMuzzleIcon(), SetQuantity(), and SetTemperature().
Referenced by HandsPreview::UpdateInterval().
Member Data Documentation
m_AmmoIcons
protected ref array<ImageWidget> Icon::m_AmmoIcons private
Definition at line 37 of file icon.c.
Referenced by CheckIsWeapon(), and RefreshMuzzleIcon().
m_AmmoTypeIcon
protected ImageWidget Icon::m_AmmoTypeIcon private
Definition at line 38 of file icon.c.
Referenced by CheckIsMagazineEx(), and Icon().
m_CargoPos
protected int Icon::m_CargoPos private
Definition at line 18 of file icon.c.
Referenced by GetCargoPos(), SetCargoPos(), and SetPosEx().
m_ColorWidget
protected Widget Icon::m_ColorWidget private
Definition at line 26 of file icon.c.
Referenced by CreateWhiteBackground(), FullScreen(), and Icon().
m_CurrQuantity
protected float Icon::m_CurrQuantity = -1 private
Definition at line 13 of file icon.c.
Referenced by SetQuantity().
m_HandsIcon
protected bool Icon::m_HandsIcon private
Definition at line 17 of file icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), DoubleClick(), DraggingOver(), DraggingOverSwap(), DropReceivedFromMain(), Icon(), InitEx(), OnDraggingOverBackground(), Refresh(), and Swap().
m_HasQuantity
protected bool Icon::m_HasQuantity = false private
Definition at line 12 of file icon.c.
Referenced by CheckHasQuantityEx(), MouseClick(), Refresh(), and UpdateInterval().
m_HasTemperature
protected bool Icon::m_HasTemperature = false private
Definition at line 11 of file icon.c.
Referenced by CheckHasTemperature(), Refresh(), and UpdateInterval().
m_IsDragged
protected bool Icon::m_IsDragged private
Definition at line 19 of file icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), FullScreen(), IsDragged(), MouseEnter(), MouseLeave(), and ~Icon().
m_IsMagazine
protected bool Icon::m_IsMagazine = false private
Definition at line 10 of file icon.c.
Referenced by CheckIsMagazineEx().
m_IsWeapon
protected bool Icon::m_IsWeapon = false private
Definition at line 9 of file icon.c.
Referenced by CheckIsWeapon(), Refresh(), and UpdateInterval().
m_Item
protected ItemBase Icon::m_Item private
Definition at line 16 of file icon.c.
Referenced by CheckHasQuantityEx(), CheckHasTemperature(), CreateWhiteBackground(), DraggingOverSwap(), DropReceivedFromMain(), InitEx(), InitLock(), MouseClick(), RevertToOriginalFlip(), SetItemSizeEx(), SetQuantity(), UpdateFlip(), and UpdateInterval().
m_ItemPreview
protected ItemPreviewWidget Icon::m_ItemPreview private
Definition at line 24 of file icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), Icon(), InitEx(), InitLock(), and SetItemPreviewEx().
m_ItemSizePanel
protected Widget Icon::m_ItemSizePanel private
Definition at line 34 of file icon.c.
Referenced by Icon(), and SetItemSizeEx().
m_ItemSizeWidget
protected TextWidget Icon::m_ItemSizeWidget private
Definition at line 35 of file icon.c.
Referenced by Icon(), and SetItemSizeEx().
m_Lock
protected EntityAI Icon::m_Lock private
Definition at line 8 of file icon.c.
Referenced by DraggingOver(), DropReceivedFromMain(), InitEx(), InitLock(), and MouseClick().
m_Obj
protected EntityAI Icon::m_Obj private
Definition at line 15 of file icon.c.
Referenced by CheckIsMagazineEx(), CheckIsWeapon(), DoubleClick(), DraggingOver(), GetObject(), InitEx(), InitLock(), MouseClick(), MouseEnter(), OnDraggingOverBackground(), SetItemPreviewEx(), SetTemperature(), and ~Icon().
m_PosX
protected int Icon::m_PosX private
Definition at line 5 of file icon.c.
Referenced by DropReceivedFromBackground(), GetPosX(), OnDraggingOverBackground(), RefreshPos(), SetPos(), and SetPosX().
m_PosY
protected int Icon::m_PosY private
Definition at line 6 of file icon.c.
Referenced by DropReceivedFromBackground(), GetPosY(), OnDraggingOverBackground(), RefreshPos(), SetPos(), and SetPosY().
m_PreviousFlipOrientation
protected bool Icon::m_PreviousFlipOrientation private
Definition at line 20 of file icon.c.
Referenced by CreateWhiteBackground(), and RevertToOriginalFlip().
m_QuantityItem
protected TextWidget Icon::m_QuantityItem private
Definition at line 30 of file icon.c.
Referenced by Icon(), and SetQuantity().
m_QuantityPanel
protected Widget Icon::m_QuantityPanel private
Definition at line 29 of file icon.c.
Referenced by CheckHasQuantityEx(), and Icon().
m_QuantityProgress
protected ProgressBarWidget Icon::m_QuantityProgress private
Definition at line 31 of file icon.c.
Referenced by Icon(), and SetQuantity().
m_QuantityStack
protected Widget Icon::m_QuantityStack private
Definition at line 32 of file icon.c.
Referenced by Icon(), and SetQuantity().
m_SelectedPanel
protected Widget Icon::m_SelectedPanel private
Definition at line 27 of file icon.c.
Referenced by CreateWhiteBackground(), DestroyWhiteBackground(), GetSelectedWidget(), Icon(), MouseEnter(), MouseLeave(), and SetActive().
m_SizeX
protected int Icon::m_SizeX private
Definition at line 3 of file icon.c.
Referenced by GetSizeX(), SetPosEx(), SetSize(), and SetSizeX().
m_SizeY
protected int Icon::m_SizeY private
Definition at line 4 of file icon.c.
Referenced by GetSizeY(), SetPosEx(), SetSize(), and SetSizeY().
NUMBER_OF_TIMERS
const int Icon::NUMBER_OF_TIMERS = 2 private
Definition at line 22 of file icon.c.