DayzKode: Material Class Reference
Material Class Reference
Private Member Functions
proto native int GetParamIndex (string paramName)
proto native void ResetParam (string propertyName)
proto bool SetParam (string propertyName, void value)
proto void SetParamByIndex (int paramIndex, void value)
Detailed Description
Definition at line 267 of file proto.c.
Member Function Documentation
GetParamIndex()
proto native int Material::GetParamIndex (string paramName) private
set parametr index for faster access to material properties
Parameters
paramName name of parameter
Returns
parameter index
ResetParam()
proto native void Material::ResetParam (string propertyName) private
reset parametr of material to default value
Parameters
paramName name of parameter
SetParam()
proto bool Material::SetParam (string propertyName, void value) private
set parametr of material by string name
Parameters
paramName name of parameter
value value
Referenced by PPEffects::FlashbangEffect(), PPEffects::HitEffect(), PPEffects::PerformSetLensEffect(), PPEffects::ResetColorize(), PPEffects::SetBloom(), PPEffects::SetBlur(), PPEffects::SetChromAbb(), PPEffects::SetNVParams(), PPEffects::SetRadialBlur(), PPEffects::SetVignette(), PPEffects::UpdateColor(), PPEffects::UpdateColorize(), and PPEffects::UpdateSaturation().
SetParamByIndex()
proto void Material::SetParamByIndex (int paramIndex, void value) private
set parametr of material by index
Parameters
paramName name of parameter
value value
Referenced by PPEClassBase::SetFinalParameterValue().