DayzKode: ActionDropItem Class Reference
ActionDropItem Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionDropItem ()
override bool CanBeUsedThrowing ()
override void CreateConditionComponents ()
override GetInputType ()
override bool HasProneException ()
override bool HasTarget ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
void PhysicalDropItem (ActionData action_data)
Private Attributes
string m_ItemName = ""
Detailed Description
Definition at line 10 of file actiondropitem.c.
Constructor & Destructor Documentation
ActionDropItem()
void ActionDropItem::ActionDropItem () inline private
Definition at line 14 of file actiondropitem.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_DROPITEM_HANDS;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_DROPITEM_HANDS;
        m_CallbackClass     = ActionDropItemCB;
        m_Text = "#drop_item";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionDropItem::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 53 of file actiondropitem.c.
    {
        if ( player.GetCommand_Vehicle() )
            return false;
        if ( player && item )
        {
            return true;
        }
        return false;
    }
ActionConditionContinue()
override bool ActionDropItem::ActionConditionContinue (ActionData action_data) inline private
Definition at line 48 of file actiondropitem.c.
    {
        return true;
    }
CanBeUsedThrowing()
override bool ActionDropItem::CanBeUsedThrowing () inline private
Definition at line 38 of file actiondropitem.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionDropItem::CreateConditionComponents () inline private
Definition at line 22 of file actiondropitem.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetInputType()
override ActionDropItem::GetInputType () inline private
Definition at line 28 of file actiondropitem.c.
    {
        return DropActionInput;
    }
HasProneException()
override bool ActionDropItem::HasProneException () inline private
Definition at line 33 of file actiondropitem.c.
    {
        return true;
    }
HasTarget()
override bool ActionDropItem::HasTarget () inline private
Definition at line 43 of file actiondropitem.c.
    {
        return false;
    }
OnExecuteClient()
override void ActionDropItem::OnExecuteClient (ActionData action_data) inline private
Definition at line 79 of file actiondropitem.c.
    {
        /*if (action_data.m_Player.GetItemInHands().IsHeavyBehaviour())
        {
            action_data.m_Player.PredictiveDropEntity(action_data.m_Player.GetItemInHands());
            if ( action_data.m_Player.IsPlacingLocal() )
            {
                action_data.m_Player.TogglePlacingLocal();
            }
        }
        else
        {
            PhysicalDropItem(action_data);
        }*/
        PhysicalDropItem(action_data);
    }
References PhysicalDropItem().
OnExecuteServer()
override void ActionDropItem::OnExecuteServer (ActionData action_data) inline private
Definition at line 65 of file actiondropitem.c.
    {
        if ( !GetGame().IsMultiplayer() )
        {
            /*action_data.m_Player.PredictiveDropEntity(action_data.m_Player.GetItemInHands());
            if ( action_data.m_Player.IsPlacingLocal() )
            {
                action_data.m_Player.TogglePlacingLocal();
            }*/
            PhysicalDropItem(action_data);
        }
    }
References GetGame(), and PhysicalDropItem().
PhysicalDropItem()
void ActionDropItem::PhysicalDropItem (ActionData action_data) inline private
Definition at line 97 of file actiondropitem.c.
    {
        action_data.m_Player.PhysicalPredictiveDropItem(action_data.m_Player.GetItemInHands());
    }
References ActionData::m_Player.
Referenced by OnExecuteClient(), and OnExecuteServer().
Member Data Documentation
m_ItemName
string ActionDropItem::m_ItemName = "" private
Definition at line 12 of file actiondropitem.c.