DayzKode: ScriptRPC Class Reference
ScriptRPC Class Reference
Private Member Functions
proto native void Reset ()
Reset internal buffer which stores written data. After Reset is callded, ScriptRPC can be used again as "new" ScriptRPC.
void ScriptRPC ()
proto native void Send (Object target, int rpc_type, bool guaranteed, PlayerIdentity recipient=NULL)
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients. Do not reset ScriptRPC internal state, so if is Send called multiple times in a row, it sends same (previously written) data again and again, until is Reset() called.
void ~ScriptRPC ()
Detailed Description
Definition at line 104 of file gameplay.c.
Constructor & Destructor Documentation
ScriptRPC()
void ScriptRPC::ScriptRPC () private
~ScriptRPC()
void ScriptRPC::~ScriptRPC () private
Member Function Documentation
Reset()
proto native void ScriptRPC::Reset () private
Reset internal buffer which stores written data. After Reset is callded, ScriptRPC can be used again as "new" ScriptRPC.
Send()
proto native void ScriptRPC::Send (Object target, int rpc_type, bool guaranteed, PlayerIdentity recipient = NULL) private
Initiate remote procedure call. When called on client, RPC is evaluated on server; When called on server, RPC is executed on all clients. Do not reset ScriptRPC internal state, so if is Send called multiple times in a row, it sends same (previously written) data again and again, until is Reset() called.
Parameters
target object on which remote procedure is called, when NULL, RPC is evaluated by CGame as global
rpc_type user defined identification of RPC
recipient specified client to send RPC to. If NULL, RPC will be send to all clients (specifying recipient increase security and decrease network traffic)
Referenced by ActionMeasureTemperatureSelf::OnFinishProgressServer(), ActionMeasureTemperatureTarget::OnFinishProgressServer(), RequestPlayerInfo(), PluginBase::RequestUniversalTemperatureSources(), PluginBase::SendDebug(), MissionBase::SendMuteListToServer(), NotificationSystem::SendNotificationToPlayerIdentity(), NotificationSystem::SendNotificationToPlayerIdentityExtended(), SendRPC(), and MissionBase::SyncRespawnModeInfo().