DayzKode: BackendCallback Class Reference
BackendCallback Class Reference
Private Member Functions
void OnDataReceive (string data, int size)
Called when data were recieved, you can ignore it when using callback to JsonStruct object with expand feature.
void OnError (int code)
Request finished with error result.
void OnSuccess (int code)
Request finished with success result.
void OnTimeout ()
Request not finished due to timeout.
Detailed Description
Definition at line 85 of file backendapi.c.
Member Function Documentation
OnDataReceive()
void BackendCallback::OnDataReceive (string data, int size) inline private
Called when data were recieved, you can ignore it when using callback to JsonStruct object with expand feature.
Parameters
data Contain received data, may be JSON, plain text, XML or image
size
Definition at line 92 of file backendapi.c.
    {
        Print("[BackendCallback] Data received, size=" + size);
        Print(data);
    }
References Print().
OnError()
void BackendCallback::OnError (int code) inline private
Request finished with error result.
Parameters
code Error code is type of EBackendError
Definition at line 102 of file backendapi.c.
    {
        Print("[BackendCallback] OnError: " + GetBackendApi().GetErrorCode(code));
    }
References GetBackendApi(), and Print().
OnSuccess()
void BackendCallback::OnSuccess (int code) inline private
Request finished with success result.
Parameters
code Code is type of EBackendRequest
Definition at line 111 of file backendapi.c.
    {
        Print("[BackendCallback] OnSuccess()");
    }
References Print().
OnTimeout()
void BackendCallback::OnTimeout () inline private
Request not finished due to timeout.
Definition at line 119 of file backendapi.c.
    {
        Print("[BackendCallback] OnTimeout");
    }
References Print().