DayzKode: ActionRepairPart Class Reference
ActionRepairPart Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionRepairPart ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override string GetAdminLogMessage (ActionData action_data)
override string GetText ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
protected bool RepairCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
protected override void SetBuildingAnimation (ItemBase item)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 39 of file actionrepairpart.c.
Constructor & Destructor Documentation
ActionRepairPart()
void ActionRepairPart::ActionRepairPart () inline private
Definition at line 41 of file actionrepairpart.c.
    {
        m_CallbackClass = ActionRepairPartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#repair";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionRepairPart::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 81 of file actionrepairpart.c.
    {
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        return RepairCondition( player, target, item, true );
    }
References RepairCondition().
ActionConditionContinue()
override bool ActionRepairPart::ActionConditionContinue (ActionData action_data) inline private
Definition at line 90 of file actionrepairpart.c.
    {
        return RepairCondition( action_data.m_Player, action_data.m_Target, action_data.m_MainItem , false );
    }
References ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and RepairCondition().
CreateActionData()
override ActionData ActionRepairPart::CreateActionData () inline private
Definition at line 137 of file actionrepairpart.c.
    {
        RepairPartActionData action_data = new RepairPartActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionRepairPart::CreateConditionComponents () inline private
Definition at line 52 of file actionrepairpart.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.BASEBUILDING );
    }
References UAMaxDistances::BASEBUILDING, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionRepairPart::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 237 of file actionrepairpart.c.
    {
        return " repaired " + action_data.m_Target.GetObject().GetDisplayName() + " with " + action_data.m_MainItem.GetDisplayName();
    }
References ActionData::m_MainItem, and ActionData::m_Target.
GetText()
override string ActionRepairPart::GetText () inline private
Definition at line 64 of file actionrepairpart.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( player )
        {
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            ConstructionPart constrution_part = construction_action_data.GetTargetPart();
            if ( constrution_part )
            {
                return "#repair" + " " + constrution_part.GetName();
            }
        }
        return "";
    }
References GetGame(), ConstructionPart::GetName(), GetPlayer(), and ConstructionActionData::GetTargetPart().
HandleReciveData()
override void ActionRepairPart::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 176 of file actionrepairpart.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        RepairPartActionReciveData recive_data_repair = RepairPartActionReciveData.Cast(action_recive_data);
        RepairPartActionData.Cast(action_data).m_ComponentIndex = recive_data_repair.m_ComponentIndexRecived;
    }
References RepairPartActionReciveData::m_ComponentIndexRecived.
OnActionInfoUpdate()
override void ActionRepairPart::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 58 of file actionrepairpart.c.
    {
        ConstructionActionData construction_action_data = player.GetConstructionActionData();
        m_Text = "#repair " + construction_action_data.GetTargetPart().GetName();
    }
References ConstructionPart::GetName(), ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void ActionRepairPart::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 95 of file actionrepairpart.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        //repairing
        string part_name = action_data.m_Target.GetObject().GetActionComponentName( RepairPartActionData.Cast(action_data).m_ComponentIndex );
        string zone_name;
        PluginRepairing module_repairing;
        Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
        DamageSystem.GetDamageZoneFromComponentName(base_building,part_name,zone_name);
        module_repairing.Repair(action_data.m_Player,action_data.m_MainItem,base_building,m_SpecialtyWeight,zone_name);
        //consume materials
        construction.TakeMaterialsServer(part_name,true);
        //add damage to tool
        action_data.m_MainItem.DecreaseHealth( UADamageApplied.REPAIR, false );
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), Construction(), GetPlugin(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and UADamageApplied::REPAIR.
ReadFromContext()
override bool ActionRepairPart::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 155 of file actionrepairpart.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new RepairPartActionReciveData;
        }
        RepairPartActionReciveData recive_data_repair = RepairPartActionReciveData.Cast(action_recive_data);
        super.ReadFromContext(ctx, action_recive_data);
        if( HasTarget() )
        {
            int component_index;
            if ( !ctx.Read(component_index) )
                return false;
            recive_data_repair.m_ComponentIndexRecived = component_index;
        }
        return true;
    }
References HasTarget(), RepairPartActionReciveData::m_ComponentIndexRecived, and Serializer::Read().
RepairCondition()
protected bool ActionRepairPart::RepairCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
Definition at line 184 of file actionrepairpart.c.
    {
        string zone_name;
        Object target_object = target.GetObject();
        if ( target_object && target_object.CanUseConstruction() )
        {
            string part_name = target_object.GetActionComponentName( target.GetComponentIndex() );
            BaseBuildingBase base_building = BaseBuildingBase.Cast( target_object );
            Construction construction = base_building.GetConstruction();
            ConstructionPart construction_part = construction.GetConstructionPart( part_name );
            if ( construction_part )
            {
                //camera and position checks
                if ( !base_building.IsFacingPlayer( player, part_name ) && !player.GetInputController().CameraIsFreeLook() && base_building.HasProperDistance( construction_part.GetMainPartName(), player ) )
                {
                    //Camera check (client-only)
                    if ( camera_check )
                    {
                        if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
{
                            if ( base_building.IsFacingCamera( part_name ) )
{
                                return false;
                            }
                        }
                    }
                    //damage check
                    DamageSystem.GetDamageZoneFromComponentName(base_building,part_name,zone_name);
                    if ( base_building.GetHealthLevel(zone_name) < GameConstants.STATE_WORN || base_building.GetHealthLevel(zone_name) == GameConstants.STATE_RUINED )
                    {
                        return false;
                    }
                    //materials check
                    if ( !construction.HasMaterials(part_name,true) )
                    {
                        return false;
                    }
                    ConstructionActionData construction_action_data = player.GetConstructionActionData();
                    construction_action_data.SetTargetPart( construction_part );
                    return true;
                }
            }
        }
        return false;
    }
References Construction(), GetGame(), ConstructionPart::GetMainPartName(), BaseBuildingBase::HasProperDistance(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ConstructionActionData::SetTargetPart(), GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
Referenced by ActionCondition(), and ActionConditionContinue().
SetBuildingAnimation()
protected override void ActionRepairPart::SetBuildingAnimation (ItemBase item) inline private
Definition at line 118 of file actionrepairpart.c.
    {
        switch( item.Type() )
        {
            case Pickaxe:
            case Shovel:
            case FarmingHoe:
            case FieldShovel:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIG;
                break;
            case Pliers:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
                break;
            default:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
                break;
        }
    }
References AnimatedActionBase::m_CommandUID.
WriteToContext()
override void ActionRepairPart::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 143 of file actionrepairpart.c.
    {
        super.WriteToContext(ctx, action_data);
        RepairPartActionData repair_action_data;
        if( HasTarget() && Class.CastTo(repair_action_data,action_data) )
        {
            repair_action_data.m_ComponentIndex = action_data.m_Target.GetComponentIndex();
            ctx.Write(repair_action_data.m_ComponentIndex);
        }
    }
References Class::CastTo(), HasTarget(), ActionData::m_Target, and Serializer::Write().