DayzKode: AnimalBase Class Reference
AnimalBase Class Reference
Private Member Functions
override string CaptureSound ()
override string CaptureSound ()
override string CaptureSound ()
override void RegisterHitComponentsForAI ()
override void RegisterHitComponentsForAI ()
override void RegisterHitComponentsForAI ()
override string ReleaseSound ()
override string ReleaseSound ()
override string ReleaseSound ()
Detailed Description
Definition at line 65 of file animalbase.c.
Member Function Documentation
CaptureSound() [1/3]
override string AnimalBase::CaptureSound () inline private
Definition at line 78 of file animalbase.c.
    {
        return "GoatBleat_B_SoundSet";
    }
CaptureSound() [2/3]
override string AnimalBase::CaptureSound () inline private
Definition at line 233 of file animalbase.c.
    {
        return "SheepBleat_E_SoundSet";
    }
CaptureSound() [3/3]
override string AnimalBase::CaptureSound () inline private
Definition at line 283 of file animalbase.c.
    {
        return "HogSqueal_SoundSet";
    }
RegisterHitComponentsForAI() [1/3]
override void AnimalBase::RegisterHitComponentsForAI () inline private
Definition at line 67 of file animalbase.c.
    {
        m_DefaultHitComponent = "Zone_Chest";
        m_DefaultHitPositionComponent = "Pelvis";
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 4);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 65);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
    }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
RegisterHitComponentsForAI() [2/3]
override void AnimalBase::RegisterHitComponentsForAI () inline private
Definition at line 221 of file animalbase.c.
    {
        m_DefaultHitComponent = "Zone_Chest";
        m_DefaultHitPositionComponent = "Pelvis";
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 4);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 15);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 55);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
    }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
RegisterHitComponentsForAI() [3/3]
override void AnimalBase::RegisterHitComponentsForAI () inline private
Definition at line 272 of file animalbase.c.
    {
        m_DefaultHitComponent = "Zone_Spine";
        m_DefaultHitPositionComponent = "Pelvis";
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Head", 3);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Neck", 55);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Belly", 15);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Legs", 70);
    }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
ReleaseSound() [1/3]
override string AnimalBase::ReleaseSound () inline private
Definition at line 83 of file animalbase.c.
    {
        return "GoatBleat_A_SoundSet";
    }
ReleaseSound() [2/3]
override string AnimalBase::ReleaseSound () inline private
Definition at line 238 of file animalbase.c.
    {
        return "SheepBleat_G_SoundSet";
    }
ReleaseSound() [3/3]
override string AnimalBase::ReleaseSound () inline private
Definition at line 288 of file animalbase.c.
    {
        return "HogGrunt_G_SoundSet";
    }