DayzKode: RainProcurementManager Class Reference
RainProcurementManager Class Reference
Private Member Functions
void InitRainProcurement ()
bool IsRunning ()
void RainProcurementCheck ()
void RainProcurementManager (ItemBase procuring_item)
void StopRainProcurement ()
Private Attributes
protected int m_IsUnderRoof
protected ItemBase m_ProcuringItem
protected ref Timer m_UpdateTimer
protected const int RAIN_COEFFICIENT = 10
Detailed Description
Definition at line 1 of file rainprocurementmanager.c.
Constructor & Destructor Documentation
RainProcurementManager()
void RainProcurementManager::RainProcurementManager (ItemBase procuring_item) inline private
Definition at line 8 of file rainprocurementmanager.c.
    {
        m_ProcuringItem = procuring_item;
    }
References m_ProcuringItem.
Member Function Documentation
InitRainProcurement()
void RainProcurementManager::InitRainProcurement () inline private
Definition at line 14 of file rainprocurementmanager.c.
    {
        m_IsUnderRoof = MiscGameplayFunctions.IsUnderRoof(m_ProcuringItem);
        //m_ProcuringItem.SetQuantity(0); /*set to 0 for debug purposses*/
        if ( !m_IsUnderRoof )
        {
            m_UpdateTimer = new Timer();
            m_UpdateTimer.Run( 10, this, "RainProcurementCheck", NULL, true );
        }
    }
References m_IsUnderRoof, m_ProcuringItem, and m_UpdateTimer.
Referenced by Barrel_ColorBase::Open(), and Barrel_ColorBase::OpenLoad().
IsRunning()
bool RainProcurementManager::IsRunning () inline private
Definition at line 70 of file rainprocurementmanager.c.
    {
        return m_UpdateTimer != null;
    }
References m_UpdateTimer.
Referenced by Barrel_ColorBase::Close(), and Barrel_ColorBase::CloseLoad().
RainProcurementCheck()
void RainProcurementManager::RainProcurementCheck () inline private
Definition at line 28 of file rainprocurementmanager.c.
    {
        float rain_intensity = GetGame().GetWeather().GetRain().GetActual();
        float fill_per_update = RAIN_COEFFICIENT * rain_intensity;
        if ( rain_intensity > 0 )
        {
            if ( m_ProcuringItem.GetQuantity() < m_ProcuringItem.GetQuantityMax() )
            {
                Liquid.FillContainerEnviro( m_ProcuringItem, LIQUID_WATER, fill_per_update );
                //Print( "Quantity of " + m_ProcuringItem + " is: " +  m_ProcuringItem.GetQuantity() );
            }
            else
            {
                //Print("vesel full");
                StopRainProcurement();
            }
        }
    }
References Liquid::FillContainerEnviro(), WeatherPhenomenon::GetActual(), GetGame(), Weather::GetRain(), CGame::GetWeather(), LIQUID_WATER, m_ProcuringItem, RAIN_COEFFICIENT, and StopRainProcurement().
StopRainProcurement()
void RainProcurementManager::StopRainProcurement () inline private
Definition at line 75 of file rainprocurementmanager.c.
    {
        if( !m_IsUnderRoof )
        {
            m_UpdateTimer.Stop();
        }
    }
References m_IsUnderRoof, and m_UpdateTimer.
Referenced by Barrel_ColorBase::Close(), Barrel_ColorBase::CloseLoad(), and RainProcurementCheck().
Member Data Documentation
m_IsUnderRoof
protected int RainProcurementManager::m_IsUnderRoof private
Definition at line 4 of file rainprocurementmanager.c.
Referenced by InitRainProcurement(), and StopRainProcurement().
m_ProcuringItem
protected ItemBase RainProcurementManager::m_ProcuringItem private
Definition at line 3 of file rainprocurementmanager.c.
Referenced by InitRainProcurement(), RainProcurementCheck(), and RainProcurementManager().
m_UpdateTimer
protected ref Timer RainProcurementManager::m_UpdateTimer private
Definition at line 5 of file rainprocurementmanager.c.
Referenced by InitRainProcurement(), IsRunning(), and StopRainProcurement().
RAIN_COEFFICIENT
protected const int RainProcurementManager::RAIN_COEFFICIENT = 10 private
Definition at line 6 of file rainprocurementmanager.c.
Referenced by RainProcurementCheck().