DayzKode: SymptomBase Class Reference
SymptomBase Class Reference
Private Member Functions
void Activate ()
void AnimationFinish ()
gets called upon animation Symptom exit
void AnimationPlayFailed ()
void AnimationStart ()
bool CanActivate ()
override bool CanActivate ()
override bool CanActivate ()
override bool CanActivate ()
override bool CanActivate ()
override bool CanActivate ()
bool CanBeInterupted ()
void CheckDestroy ()
void CheckSoundFinished ()
void Deactivate ()
void Destroy ()
float GetDuration ()
SymptomManager GetManager ()
int GetMaxCount ()
string GetName ()
void GetPersistentParams (array< Param > params)
PlayerBase GetPlayer ()
int GetPriority ()
int GetType ()
int GetUID ()
void Init (SymptomManager manager, PlayerBase player, int uid)
bool IsActivated ()
bool IsClientOnly ()
bool IsContaminationActive ()
bool IsContaminationActive ()
bool IsPersistent ()
bool IsPrimary ()
bool IsSyncToClient ()
void MakeParamObjectPersistent (Param object)
protected void OnAnimationFinish ()
override void OnAnimationFinish ()
protected void OnAnimationPlayFailed ()
override void OnAnimationPlayFailed ()
override void OnAnimationPlayFailed ()
override void OnAnimationPlayFailed ()
override void OnAnimationPlayFailed ()
protected void OnAnimationStart ()
override void OnAnimationStart ()
override void OnAnimationStart ()
bool OnConstructed (SymptomManager manager)
void OnDestructed ()
void OnGetActivatedClient (PlayerBase player)
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on a Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedClient (PlayerBase player)
override void OnGetActivatedClient (PlayerBase player)
override void OnGetActivatedClient (PlayerBase player)
override void OnGetActivatedClient (PlayerBase player)
void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
gets called once on an Symptom which is being activated
override void OnGetActivatedServer (PlayerBase player)
void OnGetDeactivatedClient (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedClient (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
only gets called once on an active Symptom that is being deactivated
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
override void OnGetDeactivatedServer (PlayerBase player)
void OnInit ()
this is just for the Symptom parameters set-up and is called even if the Symptom doesn't execute, don't put any gameplay code in here
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
void OnOwnerKilled ()
void OnUpdateClient (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
override void OnUpdateClient (PlayerBase player, float deltatime)
void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
override void OnUpdateServer (PlayerBase player, float deltatime)
gets called every frame
void PlayAnimationADD (int type)
void PlayAnimationFB (int animation, int stance_mask, float running_time=-1)
void PlaySound (EPlayerSoundEventID id)
void RequestDestroy ()
void SetDuration (float duration)
void SetParam (Param p)
override void SetParam (Param p)
SmptAnimMetaBase SpawnAnimMetaObject ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
override SmptAnimMetaBase SpawnAnimMetaObject ()
void SymptomBase ()
void SyncToClientActivated (int SYMPTOM_id, int uid)
void SyncToClientDeactivated (int SYMPTOM_id, int uid)
void Update (float deltatime)
void ~SymptomBase ()
Private Attributes
const int BLOOD_LOSS = 250
const int BLUR_DURATION = 3000
const int BLUR_DURATION_TIME_MAX = 2.5
const int BLUR_DURATION_TIME_MIN = 1.5
const float BLUR_STRENGTH_MAX = 0.25
const float BLUR_STRENGTH_MIN = 0.15
const int COUGH_BLOOD_LOSS = 50
float m_ActivatedTime
SymptomCB m_AnimCallback
bool m_AnimPlayRequested
float m_BloodSet
float m_BlurDuration
float m_BlurStrength
bool m_DestroyOnAnimFinish = true
bool m_DestroyRequested = false
float m_Duration
float m_EffectStartTime
float m_EffectTime
int m_ID
bool m_IsActivated
bool m_IsClientOnly
bool m_IsPersistent = false
bool m_IsTemplate = true
SymptomManager m_Manager
Material m_MatGauss
int m_MaxCount = -1
ref array< Param > m_PersistentParams = new array<Param>
bool m_PlayedSound
PlayerBase m_Player
ref Param1< vector > m_Position = new Param1<vector>("0 0 0")
int m_Priority
protected PPERequester_FeverEffects m_Requester
PPERequester_BloodLoss m_RequesterBloodLoss
float m_ServerUpdateDelta
float m_ServerUpdateInterval = 1
int m_ShakeLevel
SoundOnVehicle m_SoundObject
int m_SymptomType = -1
bool m_SyncToClient = false
float m_Time
int m_UID
const float MAX_TIME_ACTIVE_SAVEGUARD = 20
const int MAX_TIME_BETWEEN_EFFECTS = 35.0
const int MIN_TIME_BETWEEN_EFFECTS = 25.0
Detailed Description
Definition at line 1 of file statebase.c.
Constructor & Destructor Documentation
SymptomBase()
void SymptomBase::SymptomBase () inline private
Definition at line 30 of file statebase.c.
    {
    }
~SymptomBase()
void SymptomBase::~SymptomBase () inline private
Definition at line 34 of file statebase.c.
    {
    }
Member Function Documentation
Activate()
void SymptomBase::Activate () inline private
Definition at line 163 of file statebase.c.
    {
        m_IsActivated = true;
        if( GetGame() && GetGame().IsServer() )
        {
            OnGetActivatedServer(m_Player);
            if( GetGame().IsMultiplayer() )
            {
                if( IsSyncToClient() )
                    SyncToClientActivated( GetType(), GetUID() );
                #ifdef DEVELOPER
                GetManager().SendServerDebugToClient();
                #endif
            }
        }
        if( !GetGame().IsDedicatedServer() )
        {
            OnGetActivatedClient(m_Player);
        }
    }
References GetGame(), GetManager(), GetType(), GetUID(), IsSyncToClient(), m_IsActivated, m_Player, OnGetActivatedClient(), OnGetActivatedServer(), SymptomManager::SendServerDebugToClient(), and SyncToClientActivated().
Referenced by SymptomManager::UpdateActiveSymptoms().
AnimationFinish()
void SymptomBase::AnimationFinish () inline private
gets called upon animation Symptom exit
Definition at line 309 of file statebase.c.
    {
        //Print("*********** OnAnimationFinish ************");
        if( m_DestroyOnAnimFinish ) RequestDestroy();
        OnAnimationFinish();
    }
References m_DestroyOnAnimFinish, OnAnimationFinish(), and RequestDestroy().
Referenced by AnimationPlayFailed(), and AnimFinished().
AnimationPlayFailed()
void SymptomBase::AnimationPlayFailed () inline private
Definition at line 316 of file statebase.c.
    {
        OnAnimationPlayFailed();
        AnimationFinish();
    }
References AnimationFinish(), and OnAnimationPlayFailed().
Referenced by AnimFinished().
AnimationStart()
void SymptomBase::AnimationStart () inline private
Definition at line 322 of file statebase.c.
    {
        OnAnimationStart();
    }
References OnAnimationStart().
Referenced by SymptomManager::OnAnimationStarted().
CanActivate() [1/6]
bool SymptomBase::CanActivate () inline private
Definition at line 337 of file statebase.c.
{return true;}//server only
CanActivate() [2/6]
override bool SymptomBase::CanActivate () inline private
Definition at line 29 of file freezestate.c.
    {
        return true;
    }
CanActivate() [3/6]
override bool SymptomBase::CanActivate () inline private
Definition at line 29 of file hotstate.c.
    {
        return true;
    }
CanActivate() [4/6]
override bool SymptomBase::CanActivate () inline private
Definition at line 29 of file painheavystate.c.
    {
        return true;
    }
CanActivate() [5/6]
override bool SymptomBase::CanActivate () inline private
Definition at line 29 of file painlightstate.c.
    {
        return true;
    }
CanActivate() [6/6]
override bool SymptomBase::CanActivate () inline private
Definition at line 61 of file vomitstate.c.
    {
        return ( m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_MOVE || m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_ACTION );
    }
References m_Manager.
CanBeInterupted()
bool SymptomBase::CanBeInterupted () inline private
Definition at line 64 of file statebase.c.
    {
        if(m_AnimPlayRequested)
        {
            //Print("--------- preventing interrupt ---------");
            return false;
        }
        return true;
    }
References m_AnimPlayRequested.
CheckDestroy()
void SymptomBase::CheckDestroy () inline private
Definition at line 278 of file statebase.c.
    {
        CheckSoundFinished();
        if( IsPrimary() && m_ActivatedTime > MAX_TIME_ACTIVE_SAVEGUARD)
        {
            RequestDestroy();
        }
        if (m_DestroyRequested)
            Destroy();
    }
References CheckSoundFinished(), Destroy(), IsPrimary(), m_ActivatedTime, m_DestroyRequested, MAX_TIME_ACTIVE_SAVEGUARD, and RequestDestroy().
Referenced by Update().
CheckSoundFinished()
void SymptomBase::CheckSoundFinished () inline private
Definition at line 269 of file statebase.c.
    {
        if(GetGame().IsServer())
        {
            if(m_PlayedSound && m_ActivatedTime >= m_Duration)
                RequestDestroy();
        }
    }
References GetGame(), m_ActivatedTime, m_Duration, m_PlayedSound, and RequestDestroy().
Referenced by CheckDestroy().
Deactivate()
void SymptomBase::Deactivate () inline private
Definition at line 184 of file statebase.c.
    {
        if( !GetGame() ) return;
        m_IsActivated = false;
        if( GetGame().IsServer() )
        {
            OnGetDeactivatedServer(m_Player);
            if( GetGame().IsMultiplayer() && IsSyncToClient() )
            {
                SyncToClientDeactivated( GetType(), GetUID() );
            }
        }
        if( !GetGame().IsDedicatedServer() )
        {
            OnGetDeactivatedClient(m_Player);
        }
    }
References GetGame(), GetType(), GetUID(), IsSyncToClient(), m_IsActivated, m_Player, OnGetDeactivatedClient(), OnGetDeactivatedServer(), and SyncToClientDeactivated().
Referenced by OnDestructed().
Destroy()
void SymptomBase::Destroy () inline private
Definition at line 302 of file statebase.c.
    {
        if(!m_IsTemplate)
            OnDestructed();
    }
References m_IsTemplate, and OnDestructed().
Referenced by CheckDestroy().
GetDuration()
float SymptomBase::GetDuration () inline private
Definition at line 85 of file statebase.c.
    {
        return m_Duration;
    }
References m_Duration.
GetManager()
SymptomManager SymptomBase::GetManager () inline private
Definition at line 95 of file statebase.c.
    {
        return m_Manager;
    }
References m_Manager.
Referenced by Activate(), and OnDestructed().
GetMaxCount()
int SymptomBase::GetMaxCount () inline private
Definition at line 48 of file statebase.c.
    {
        return m_MaxCount;
    }
References m_MaxCount.
GetName()
string SymptomBase::GetName () inline private
Definition at line 90 of file statebase.c.
    {
        return this.ClassName();
    }
Referenced by SymptomManager::ShowAvailableSymptoms().
GetPersistentParams()
void SymptomBase::GetPersistentParams (array< Param > params) inline private
Definition at line 115 of file statebase.c.
    {
        for(int i = 0; i < m_PersistentParams.Count(); i++)
        {
            params.Insert(m_PersistentParams.Get(i));
        }
    }
References m_PersistentParams.
GetPlayer()
PlayerBase SymptomBase::GetPlayer () inline private
Definition at line 142 of file statebase.c.
    {
        return m_Player;
    }
References m_Player.
Referenced by PlaySound(), SyncToClientActivated(), and SyncToClientDeactivated().
GetPriority()
int SymptomBase::GetPriority () inline private
Definition at line 147 of file statebase.c.
    {
        return m_Priority;
    }
References m_Priority.
GetType()
int SymptomBase::GetType () inline private
Definition at line 100 of file statebase.c.
    {
        return m_ID;
    }
References m_ID.
Referenced by Activate(), Deactivate(), SymptomManager::OnSymptomExit(), PlayAnimationADD(), PlayAnimationFB(), SymptomManager::RegisterSymptom(), and SymptomManager::ShowAvailableSymptoms().
GetUID()
int SymptomBase::GetUID () inline private
Definition at line 53 of file statebase.c.
    {
        return m_UID;
    }
References m_UID.
Referenced by Activate(), and Deactivate().
Init()
void SymptomBase::Init (SymptomManager manager, PlayerBase player, int uid) inline private
Definition at line 39 of file statebase.c.
    {
        m_Manager = manager;
        m_Player = player;
        m_UID = uid;
        m_IsTemplate = false;
        OnInit();
    }
References m_IsTemplate, m_Manager, m_Player, m_UID, and OnInit().
Referenced by SymptomManager::RegisterSymptom(), and SymptomManager::SpawnSymptom().
IsActivated()
bool SymptomBase::IsActivated () inline private
Definition at line 203 of file statebase.c.
    {
        return m_IsActivated;
    }
References m_IsActivated.
Referenced by OnDestructed().
IsClientOnly()
bool SymptomBase::IsClientOnly () inline private
Definition at line 74 of file statebase.c.
    {
        return m_IsClientOnly;
    }
References m_IsClientOnly.
IsContaminationActive() [1/2]
bool SymptomBase::IsContaminationActive () inline private
Definition at line 14 of file coughstate.c.
    {
        return m_Player.GetModifiersManager().IsModifierActive(eModifiers.MDF_CONTAMINATION2) || m_Player.GetModifiersManager().IsModifierActive(eModifiers.MDF_CONTAMINATION3);
    }
References m_Player.
Referenced by OnAnimationFinish(), OnAnimationStart(), and OnGetActivatedServer().
IsContaminationActive() [2/2]
bool SymptomBase::IsContaminationActive () inline private
Definition at line 27 of file vomitstate.c.
    {
        return m_Player.GetModifiersManager().IsModifierActive(eModifiers.MDF_CONTAMINATION2) || m_Player.GetModifiersManager().IsModifierActive(eModifiers.MDF_CONTAMINATION3);
    }
References m_Player.
IsPersistent()
bool SymptomBase::IsPersistent () inline private
Definition at line 130 of file statebase.c.
    {
        return m_IsPersistent;
    }
References m_IsPersistent.
IsPrimary()
bool SymptomBase::IsPrimary () inline private
Definition at line 135 of file statebase.c.
    {
        if( m_SymptomType == SymptomTypes.PRIMARY)
            return true;
        else return false;
    }
References m_SymptomType.
Referenced by CheckDestroy(), and SymptomManager::OnSymptomExit().
IsSyncToClient()
bool SymptomBase::IsSyncToClient () inline private
Definition at line 110 of file statebase.c.
    {
        return m_SyncToClient;
    }
References m_SyncToClient.
Referenced by Activate(), and Deactivate().
MakeParamObjectPersistent()
void SymptomBase::MakeParamObjectPersistent (Param object) inline private
Definition at line 123 of file statebase.c.
    {
        if( !GetGame().IsServer() && !GetGame().IsMultiplayer() ) return;
        m_PersistentParams.Insert(object);
    }
References GetGame(), and m_PersistentParams.
Referenced by OnInit().
OnAnimationFinish() [1/2]
protected void SymptomBase::OnAnimationFinish () private
Referenced by AnimationFinish().
OnAnimationFinish() [2/2]
override void SymptomBase::OnAnimationFinish () inline private
deplete stamina
Definition at line 49 of file vomitstate.c.
    {
        m_Player.GetStaminaHandler().DepleteStamina(EStaminaModifiers.OVERALL_DRAIN);
        if (IsContaminationActive())
        {
            PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
            module_lifespan.UpdateBloodyHandsVisibilityEx( m_Player, eBloodyHandsTypes.JUST_BLOOD );
        }
    }
References GetPlugin(), IsContaminationActive(), m_Player, and PluginLifespan().
OnAnimationPlayFailed() [1/5]
protected void SymptomBase::OnAnimationPlayFailed () private
Referenced by AnimationPlayFailed().
OnAnimationPlayFailed() [2/5]
override void SymptomBase::OnAnimationPlayFailed () inline private
Definition at line 24 of file freezestate.c.
    {
    }
OnAnimationPlayFailed() [3/5]
override void SymptomBase::OnAnimationPlayFailed () inline private
Definition at line 24 of file hotstate.c.
    {
    }
OnAnimationPlayFailed() [4/5]
override void SymptomBase::OnAnimationPlayFailed () inline private
Definition at line 24 of file painheavystate.c.
    {
    }
OnAnimationPlayFailed() [5/5]
override void SymptomBase::OnAnimationPlayFailed () inline private
Definition at line 24 of file painlightstate.c.
    {
    }
OnAnimationStart() [1/3]
protected void SymptomBase::OnAnimationStart () private
Referenced by AnimationStart().
OnAnimationStart() [2/3]
override void SymptomBase::OnAnimationStart () inline private
Definition at line 30 of file coughstate.c.
    {
        if ( IsContaminationActive() )
        {
            PluginLifespan module_lifespan = PluginLifespan.Cast( GetPlugin( PluginLifespan ) );
            module_lifespan.UpdateBloodyHandsVisibilityEx( m_Player, eBloodyHandsTypes.JUST_BLOOD );
        }
    }
References GetPlugin(), IsContaminationActive(), m_Player, and PluginLifespan().
OnAnimationStart() [3/3]
override void SymptomBase::OnAnimationStart () inline private
Definition at line 32 of file vomitstate.c.
    {
        if(m_Player)
        {
            m_Player.GetStatToxicity().Set(0);
            if(m_Player.m_PlayerStomach)
                m_Player.m_PlayerStomach.ClearContents();
            if (IsContaminationActive())
            {
                m_Player.AddHealth("","Blood", -BLOOD_LOSS);
            }
        }
        //Print("------------ vomit start -------------");
    }
References IsContaminationActive(), and m_Player.
OnConstructed()
bool SymptomBase::OnConstructed (SymptomManager manager) inline private
Definition at line 152 of file statebase.c.
    {
    }
OnDestructed()
void SymptomBase::OnDestructed () inline private
Definition at line 157 of file statebase.c.
    {
        if( IsActivated() ) Deactivate();
        if( GetManager() ) m_Manager.OnSymptomExit(this, m_UID);
    }
References Deactivate(), GetManager(), IsActivated(), m_Manager, m_UID, and SymptomManager::OnSymptomExit().
Referenced by Destroy().
OnGetActivatedClient() [1/12]
void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
Definition at line 342 of file statebase.c.
{}
Referenced by Activate().
OnGetActivatedClient() [2/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 63 of file coughstate.c.
    {
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
OnGetActivatedClient() [3/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 53 of file freezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [4/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 53 of file hotstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [5/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 34 of file laughterstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [6/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 45 of file painheavystate.c.
    {
        //player.SpawnShockEffect(0.5);
        player.SpawnDamageDealtEffect2();
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [7/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on a Symptom which is being activated
Definition at line 45 of file painlightstate.c.
    {
        //player.SpawnShockEffect(0.5);
        CachedObjectsParams.PARAM2_FLOAT_FLOAT.param1 = 26;
        CachedObjectsParams.PARAM2_FLOAT_FLOAT.param2 = 0.25;
        player.SpawnDamageDealtEffect2(CachedObjectsParams.PARAM2_FLOAT_FLOAT);
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, CachedObjectsParams::PARAM2_FLOAT_FLOAT, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [8/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 39 of file sneezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [9/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
Definition at line 35 of file blindnessstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [10/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
Definition at line 53 of file bloodloss.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [11/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
Definition at line 79 of file feverblurstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedClient() [12/12]
override void SymptomBase::OnGetActivatedClient (PlayerBase player) inline private
Definition at line 45 of file handshivers.c.
    {
    }
OnGetActivatedServer() [1/13]
void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 341 of file statebase.c.
{}
Referenced by Activate().
OnGetActivatedServer() [2/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 46 of file coughstate.c.
    {
        if( m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_MOVE && !player.IsRaised() && player.GetCommand_Move() && player.GetCommand_Move() && !player.GetCommand_Move().IsOnBack())
        {
            PlayAnimationADD(1);
        }
        else
        {
            PlaySound(EPlayerSoundEventID.SYMPTOM_COUGH);
        }
        player.SpreadAgentsEx(3);
        if ( IsContaminationActive() )
            player.AddHealth("","Blood", -COUGH_BLOOD_LOSS);
    }
References IsContaminationActive(), m_Manager, PlayAnimationADD(), and PlaySound().
OnGetActivatedServer() [3/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file freezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        HumanMovementState hms = new HumanMovementState();
        player.GetMovementState(hms);
        ItemBase item = m_Player.GetItemInHands();
        if(!(item && item.IsHeavyBehaviour()) && m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_MOVE && hms.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_IDLE && !player.IsRestrained() )
        {
            PlayAnimationADD(2);
        }
        else
        {
            PlaySound(EPlayerSoundEventID.FREEZING);
        }
    }
References LogManager::IsSymptomLogEnable(), HumanMovementState::m_iMovement, m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [4/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file hotstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        HumanMovementState hms = new HumanMovementState();
        player.GetMovementState(hms);
        ItemBase item = m_Player.GetItemInHands();
        if(!(item && item.IsHeavyBehaviour()) && m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_MOVE && hms.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_IDLE && !player.IsRestrained() )
        {
            PlayAnimationADD(3);
        }
        else
        {
            PlaySound(EPlayerSoundEventID.HOT);
        }
    }
References LogManager::IsSymptomLogEnable(), HumanMovementState::m_iMovement, m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [5/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 26 of file laughterstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        PlaySound(EPlayerSoundEventID.SYMPTOM_LAUGHTER);
        player.SpreadAgentsEx(3);
    }
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [6/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file painheavystate.c.
    {
        if (LogManager.IsSymptomLogEnable())
            Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        PlaySound(EPlayerSoundEventID.TAKING_DMG_HEAVY);
        //player.AddHealth("","Shock",-10);
    }
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [7/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 35 of file painlightstate.c.
    {
        if (LogManager.IsSymptomLogEnable())
            Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        PlaySound(EPlayerSoundEventID.TAKING_DMG_LIGHT);
        //player.AddHealth("","Shock",-10);
    }
References LogManager::IsSymptomLogEnable(), m_Player, PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [8/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 24 of file sneezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
        if( m_Manager.GetCurrentCommandID() == DayZPlayerConstants.COMMANDID_MOVE && !player.IsRaised() && player.GetCommand_Move() && !player.GetCommand_Move().IsOnBack())
        {
            PlayAnimationADD(0);
        }
        else
        {
            PlaySound(EPlayerSoundEventID.SYMPTOM_SNEEZE);
        }
        player.SpreadAgentsEx(3);
    }
References LogManager::IsSymptomLogEnable(), m_Manager, m_Player, PlayAnimationADD(), PlaySound(), Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [9/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 67 of file vomitstate.c.
    {
        PlayAnimationFB(DayZPlayerConstants.CMD_ACTIONFB_VOMIT,DayZPlayerConstants.STANCEMASK_CROUCH, GetDuration() );
        //timer.Run(10, this, "Destroy");
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References GetDuration(), and PlayAnimationFB().
OnGetActivatedServer() [10/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 30 of file blindnessstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [11/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 48 of file bloodloss.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [12/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
gets called once on an Symptom which is being activated
Definition at line 74 of file feverblurstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetActivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetActivatedServer() [13/13]
override void SymptomBase::OnGetActivatedServer (PlayerBase player) inline private
Definition at line 35 of file handshivers.c.
    {
        player.SetShakesForced(m_ShakeLevel);
    }
OnGetDeactivatedClient() [1/13]
void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
Definition at line 345 of file statebase.c.
{}
Referenced by Deactivate().
OnGetDeactivatedClient() [2/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 75 of file coughstate.c.
    {
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
OnGetDeactivatedClient() [3/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 65 of file freezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [4/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 65 of file hotstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [5/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file laughterstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [6/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 59 of file painheavystate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [7/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 61 of file painlightstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [8/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 52 of file sneezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [9/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
Definition at line 80 of file vomitstate.c.
    {
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
OnGetDeactivatedClient() [10/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file blindnessstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
        PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop(); //TODO - use different PPERequester when connected, otherwise it would interfere with burlapsack blindness
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [11/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 64 of file bloodloss.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [12/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 90 of file feverblurstate.c.
    {
        m_Requester.Stop();
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, m_Requester, Debug::SymptomLog(), and ToString().
OnGetDeactivatedClient() [13/13]
override void SymptomBase::OnGetDeactivatedClient (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 52 of file handshivers.c.
    {
    }
OnGetDeactivatedServer() [1/13]
void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 344 of file statebase.c.
{}
Referenced by Deactivate().
OnGetDeactivatedServer() [2/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 69 of file coughstate.c.
    {
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
OnGetDeactivatedServer() [3/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 59 of file freezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [4/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 59 of file hotstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [5/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 40 of file laughterstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [6/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 53 of file painheavystate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [7/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 55 of file painlightstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [8/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 46 of file sneezestate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [9/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
only gets called once on an active Symptom that is being deactivated
Definition at line 75 of file vomitstate.c.
    {
        //if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
OnGetDeactivatedServer() [10/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 40 of file blindnessstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [11/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 58 of file bloodloss.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [12/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 84 of file feverblurstate.c.
    {
        if (LogManager.IsSymptomLogEnable()) Debug.SymptomLog("n/a", this.ToString(), "n/a", "OnGetDeactivated", m_Player.ToString());
    }
References LogManager::IsSymptomLogEnable(), m_Player, Debug::SymptomLog(), and ToString().
OnGetDeactivatedServer() [13/13]
override void SymptomBase::OnGetDeactivatedServer (PlayerBase player) inline private
Definition at line 40 of file handshivers.c.
    {
        player.SetShakesForced(0);
    }
OnInit() [1/13]
void SymptomBase::OnInit () inline private
this is just for the Symptom parameters set-up and is called even if the Symptom doesn't execute, don't put any gameplay code in here
Definition at line 333 of file statebase.c.
{}
Referenced by Init().
OnInit() [2/13]
override void SymptomBase::OnInit () inline private
Definition at line 5 of file coughstate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 100;
        m_ID = SymptomIDs.SYMPTOM_COUGH;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
    }
References m_ID, m_Priority, and m_SymptomType.
OnInit() [3/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file freezestate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 1;
        m_ID = SymptomIDs.SYMPTOM_FREEZE;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
        m_MaxCount = 2;
    }
References m_ID, m_Priority, and m_SymptomType.
OnInit() [4/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file hotstate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 1;
        m_ID = SymptomIDs.SYMPTOM_HOT;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
        m_MaxCount = 2;
    }
References m_ID, m_Priority, and m_SymptomType.
OnInit() [5/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file laughterstate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 0;
        m_ID = SymptomIDs.SYMPTOM_LAUGHTER;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
        m_Duration = 4;
    }
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [6/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file painheavystate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 1;
        m_ID = SymptomIDs.SYMPTOM_PAIN_HEAVY;
        m_SyncToClient = true;
        m_MaxCount = 2;
        m_Duration = 1;
    }
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [7/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file painlightstate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 1;
        m_ID = SymptomIDs.SYMPTOM_PAIN_LIGHT;
        m_SyncToClient = true;
        m_MaxCount = 2;
        m_Duration = 1;
    }
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [8/13]
override void SymptomBase::OnInit () inline private
Definition at line 4 of file sneezestate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 100;
        m_ID = SymptomIDs.SYMPTOM_SNEEZE;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
    }
References m_ID, m_Priority, and m_SymptomType.
OnInit() [9/13]
override void SymptomBase::OnInit () inline private
Definition at line 5 of file vomitstate.c.
    {
        m_SymptomType = SymptomTypes.PRIMARY;
        m_Priority = 100;
        m_ID = SymptomIDs.SYMPTOM_VOMIT;
        m_DestroyOnAnimFinish = true;
        m_SyncToClient = false;
        m_Duration = 5;
        m_MaxCount = 1;
    }
References m_Duration, m_ID, m_Priority, and m_SymptomType.
OnInit() [10/13]
override void SymptomBase::OnInit () inline private
Definition at line 8 of file blindnessstate.c.
    {
        m_SymptomType = SymptomTypes.SECONDARY;
        m_Priority = 0;
        m_ID = SymptomIDs.SYMPTOM_BLINDNESS;
        m_DestroyOnAnimFinish = true;
        m_IsPersistent = false;
        MakeParamObjectPersistent(m_Position);
    }
References m_ID, m_IsPersistent, m_Position, m_Priority, m_SymptomType, and MakeParamObjectPersistent().
OnInit() [11/13]
override void SymptomBase::OnInit () inline private
Definition at line 9 of file bloodloss.c.
    {
        m_SymptomType = SymptomTypes.SECONDARY;
        m_Priority = 0;
        m_ID = SymptomIDs.SYMPTOM_BLOODLOSS;
        m_DestroyOnAnimFinish = true;
        m_IsPersistent = false;
        m_SyncToClient = true;
        m_BloodSet = -1;
        if ( !GetGame().IsDedicatedServer() )
        {
            Class.CastTo(m_RequesterBloodLoss,PPERequester_BloodLoss.Cast(PPERequesterBank.GetRequester(PPERequester_BloodLoss)));
        }
    }
References Class::CastTo(), GetGame(), m_ID, m_IsPersistent, m_Priority, and m_SymptomType.
OnInit() [12/13]
override void SymptomBase::OnInit () inline private
Definition at line 22 of file feverblurstate.c.
    {
        m_SymptomType = SymptomTypes.SECONDARY;
        m_Priority = 0;
        m_ID = SymptomIDs.SYMPTOM_FEVERBLUR;
        m_DestroyOnAnimFinish = true;
        m_IsPersistent = false;
        m_SyncToClient = true;
        if ( !GetGame().IsDedicatedServer() )
        {
            Class.CastTo(m_Requester,PPERequesterBank.GetRequester(PPERequester_FeverEffects));
        }
    }
References Class::CastTo(), GetGame(), m_ID, m_IsPersistent, m_Priority, m_Requester, and m_SymptomType.
OnInit() [13/13]
override void SymptomBase::OnInit () inline private
Definition at line 6 of file handshivers.c.
    {
        m_SymptomType = SymptomTypes.SECONDARY;
        m_Priority = 0;
        m_ID = SymptomIDs.SYMPTOM_HAND_SHIVER;
        m_SyncToClient = false;
    }
References m_ID, m_Priority, and m_SymptomType.
OnOwnerKilled()
void SymptomBase::OnOwnerKilled () inline private
Definition at line 58 of file statebase.c.
    {
    }
OnUpdateClient() [1/13]
void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 339 of file statebase.c.
{}
Referenced by Update().
OnUpdateClient() [2/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 26 of file coughstate.c.
    {
    }
OnUpdateClient() [3/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file freezestate.c.
    {
    }
OnUpdateClient() [4/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file hotstate.c.
    {
    }
OnUpdateClient() [5/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file laughterstate.c.
    {
        int i = 1 + 1;
    }
OnUpdateClient() [6/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file painheavystate.c.
    {
    }
OnUpdateClient() [7/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 20 of file painlightstate.c.
    {
    }
OnUpdateClient() [8/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 19 of file sneezestate.c.
    {
    }
OnUpdateClient() [9/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 22 of file vomitstate.c.
    {
    }
OnUpdateClient() [10/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 23 of file blindnessstate.c.
    {
    }
OnUpdateClient() [11/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 31 of file bloodloss.c.
    {
        if ( player.IsPlayerSelected() && player.GetTransferValues() && player.GetTransferValues().GetBlood() != m_BloodSet )
        {
            m_BloodSet = player.GetTransferValues().GetBlood();
            if (m_BloodSet < 1.0)
            {
                m_RequesterBloodLoss.SetBloodLossLevel(m_BloodSet);
            }
            else
            {
                m_RequesterBloodLoss.Stop();
            }
        }
    }
OnUpdateClient() [12/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 44 of file feverblurstate.c.
    {
        m_Time += deltatime;
        if ( m_EffectStartTime <= 0 )
        {
            m_EffectStartTime = Math.RandomFloatInclusive(MIN_TIME_BETWEEN_EFFECTS, MAX_TIME_BETWEEN_EFFECTS);
            m_BlurDuration = Math.RandomFloatInclusive(BLUR_DURATION_TIME_MIN, BLUR_DURATION_TIME_MAX);
            m_BlurStrength = Math.RandomFloat(BLUR_STRENGTH_MIN, BLUR_STRENGTH_MAX);
            //PrintString("m_BlurDuration=" +m_BlurDuration.ToString());
        }
        if ( m_EffectStartTime > 0 && m_Time > m_EffectStartTime )
        {
            m_EffectTime += deltatime / m_BlurDuration;
            float cos_value = Math.Sin(m_EffectTime  * Math.PI);
            float val = cos_value * m_BlurStrength;
            //Print(val);
            m_Requester.SetFeverIntensity(val);
            //PrintString("cos=" +cos_value.ToString());
            if ( m_EffectTime >= 1 )
            {
                m_EffectTime = 0;
                m_EffectStartTime = -1;
                m_Time = 0;
            }
        }
    }
References m_BlurDuration, m_BlurStrength, m_Requester, m_Time, Math::PI, Math::RandomFloat(), Math::RandomFloatInclusive(), and Math::Sin().
OnUpdateClient() [13/13]
override void SymptomBase::OnUpdateClient (PlayerBase player, float deltatime) inline private
Definition at line 30 of file handshivers.c.
    {
    }
OnUpdateServer() [1/12]
void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 336 of file statebase.c.
{}
Referenced by Update().
OnUpdateServer() [2/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 21 of file coughstate.c.
    {
    }
OnUpdateServer() [3/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file freezestate.c.
    {
    }
OnUpdateServer() [4/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file hotstate.c.
    {
    }
OnUpdateServer() [5/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file laughterstate.c.
    {
    }
OnUpdateServer() [6/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file painheavystate.c.
    {
    }
OnUpdateServer() [7/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 15 of file painlightstate.c.
    {
    }
OnUpdateServer() [8/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 14 of file sneezestate.c.
    {
    }
OnUpdateServer() [9/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 17 of file vomitstate.c.
    {
    }
OnUpdateServer() [10/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 19 of file blindnessstate.c.
    {
    }
OnUpdateServer() [11/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 27 of file bloodloss.c.
    {
    }
OnUpdateServer() [12/12]
override void SymptomBase::OnUpdateServer (PlayerBase player, float deltatime) inline private
gets called every frame
Definition at line 38 of file feverblurstate.c.
    {
        //int i = 1 + 1;
    }
PlayAnimationADD()
void SymptomBase::PlayAnimationADD (int type) inline private
Definition at line 240 of file statebase.c.
    {
        DayZPlayerSyncJunctures.SendPlayerSymptomADD(m_Player, type, GetType());
        m_AnimPlayRequested = true;
    }
References GetType(), m_AnimPlayRequested, m_Player, and DayZPlayerSyncJunctures::SendPlayerSymptomADD().
Referenced by OnGetActivatedServer().
PlayAnimationFB()
void SymptomBase::PlayAnimationFB (int animation, int stance_mask, float running_time = -1) inline private
Definition at line 234 of file statebase.c.
    {
        DayZPlayerSyncJunctures.SendPlayerSymptomFB(m_Player, animation, GetType() , stance_mask, running_time );
        m_AnimPlayRequested = true;
    }
References GetType(), m_AnimPlayRequested, m_Player, and DayZPlayerSyncJunctures::SendPlayerSymptomFB().
Referenced by OnGetActivatedServer().
PlaySound()
void SymptomBase::PlaySound (EPlayerSoundEventID id) inline private
Definition at line 246 of file statebase.c.
    {
        GetPlayer().RequestSoundEvent(id);
        m_PlayedSound = true;
    }
References GetPlayer(), and m_PlayedSound.
RequestDestroy()
void SymptomBase::RequestDestroy () inline private
Definition at line 296 of file statebase.c.
    {
        m_DestroyRequested = true;
        //if(!IsActivated() ) Destroy();
    }
References m_DestroyRequested.
Referenced by AnimationFinish(), CheckDestroy(), and CheckSoundFinished().
SetDuration()
void SymptomBase::SetDuration (float duration) inline private
Definition at line 80 of file statebase.c.
    {
        m_Duration = duration;
    }
References m_Duration.
Referenced by PoisoningMdfr::OnTick(), CholeraMdfr::OnTick(), SalmonellaMdfr::OnTick(), and ToxicityMdfr::OnTick().
SetParam() [1/2]
void SymptomBase::SetParam (Param p) inline private
Definition at line 105 of file statebase.c.
    {
    }
Referenced by WoundInfectStage2Mdfr::OnActivate().
SetParam() [2/2]
override void SymptomBase::SetParam (Param p) inline private
Definition at line 15 of file handshivers.c.
    {
        Param1<int> p1 = Param1<int>.Cast(p);
        if ( p1 )
        {
            m_ShakeLevel = p1.param1;
            if ( m_ShakeLevel > PlayerBase.SHAKE_LEVEL_MAX )
            {
                m_ShakeLevel = PlayerBase.SHAKE_LEVEL_MAX;
            }
        }
    }
SpawnAnimMetaObject() [1/6]
SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 290 of file statebase.c.
    {
        return null;
    }
SpawnAnimMetaObject() [2/6]
override SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 40 of file coughstate.c.
    {
        return new SmptAnimMetaADD();
    }
SpawnAnimMetaObject() [3/6]
override SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 70 of file freezestate.c.
    {
        return new HeatComfortmMetaADD();
    }
SpawnAnimMetaObject() [4/6]
override SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 70 of file hotstate.c.
    {
        return new HeatComfortmMetaADD();
    }
SpawnAnimMetaObject() [5/6]
override SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 57 of file sneezestate.c.
    {
        return new SmptAnimMetaADD();
    }
SpawnAnimMetaObject() [6/6]
override SmptAnimMetaBase SymptomBase::SpawnAnimMetaObject () inline private
Definition at line 85 of file vomitstate.c.
    {
        return new SmptAnimMetaFB();
    }
SyncToClientActivated()
void SymptomBase::SyncToClientActivated (int SYMPTOM_id, int uid) inline private
Definition at line 252 of file statebase.c.
    {
        if( !GetPlayer() ) return;
        CachedObjectsParams.PARAM2_INT_INT.param1 = SYMPTOM_id;
        CachedObjectsParams.PARAM2_INT_INT.param2 = uid;
        GetGame().RPCSingleParam(GetPlayer(), ERPCs.RPC_PLAYER_SYMPTOM_ON, CachedObjectsParams.PARAM2_INT_INT,true,GetPlayer().GetIdentity() );
    }
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM2_INT_INT, and CGame::RPCSingleParam().
Referenced by Activate().
SyncToClientDeactivated()
void SymptomBase::SyncToClientDeactivated (int SYMPTOM_id, int uid) inline private
Definition at line 261 of file statebase.c.
    {
        if( !GetPlayer() ) return;
        CachedObjectsParams.PARAM2_INT_INT.param1 = SYMPTOM_id;
        CachedObjectsParams.PARAM2_INT_INT.param2 = uid;
        GetGame().RPCSingleParam(GetPlayer(), ERPCs.RPC_PLAYER_SYMPTOM_OFF, CachedObjectsParams.PARAM2_INT_INT,true,GetPlayer().GetIdentity() );
    }
References GetGame(), GetPlayer(), CachedObjectsParams::PARAM2_INT_INT, and CGame::RPCSingleParam().
Referenced by Deactivate().
Update()
void SymptomBase::Update (float deltatime) inline private
Definition at line 210 of file statebase.c.
    {
        if( GetGame().IsServer() )
        {
            m_ServerUpdateDelta += deltatime;
            if(m_ServerUpdateDelta > m_ServerUpdateInterval )
            {
                m_ActivatedTime += m_ServerUpdateDelta;
                OnUpdateServer(m_Player, m_ServerUpdateDelta);
                m_ServerUpdateDelta = 0;
            }
        }
        if( GetGame().IsClient() )
        {
            OnUpdateClient(m_Player, deltatime);
        }
        if( GetGame().IsServer() && !GetGame().IsMultiplayer() && !GetGame().IsMissionMainMenu() )
        {
            OnUpdateClient(m_Player, deltatime);
        }
        CheckDestroy();
    }
References CheckDestroy(), GetGame(), m_ActivatedTime, m_Player, m_ServerUpdateDelta, m_ServerUpdateInterval, OnUpdateClient(), and OnUpdateServer().
Referenced by SymptomManager::UpdateActiveSymptoms().
Member Data Documentation
BLOOD_LOSS
const int SymptomBase::BLOOD_LOSS = 250 private
Definition at line 4 of file vomitstate.c.
BLUR_DURATION
const int SymptomBase::BLUR_DURATION = 3000 private
Definition at line 4 of file blindnessstate.c.
BLUR_DURATION_TIME_MAX
const int SymptomBase::BLUR_DURATION_TIME_MAX = 2.5 private
Definition at line 16 of file feverblurstate.c.
BLUR_DURATION_TIME_MIN
const int SymptomBase::BLUR_DURATION_TIME_MIN = 1.5 private
Definition at line 15 of file feverblurstate.c.
BLUR_STRENGTH_MAX
const float SymptomBase::BLUR_STRENGTH_MAX = 0.25 private
Definition at line 13 of file feverblurstate.c.
BLUR_STRENGTH_MIN
const float SymptomBase::BLUR_STRENGTH_MIN = 0.15 private
Definition at line 12 of file feverblurstate.c.
COUGH_BLOOD_LOSS
const int SymptomBase::COUGH_BLOOD_LOSS = 50 private
Definition at line 3 of file coughstate.c.
m_ActivatedTime
float SymptomBase::m_ActivatedTime private
Definition at line 12 of file statebase.c.
Referenced by CheckDestroy(), CheckSoundFinished(), and Update().
m_AnimCallback
SymptomCB SymptomBase::m_AnimCallback private
Definition at line 26 of file statebase.c.
m_AnimPlayRequested
bool SymptomBase::m_AnimPlayRequested private
Definition at line 23 of file statebase.c.
Referenced by CanBeInterupted(), PlayAnimationADD(), and PlayAnimationFB().
m_BloodSet
float SymptomBase::m_BloodSet private
Definition at line 5 of file bloodloss.c.
m_BlurDuration
float SymptomBase::m_BlurDuration private
Definition at line 5 of file feverblurstate.c.
Referenced by OnUpdateClient().
m_BlurStrength
float SymptomBase::m_BlurStrength private
Definition at line 6 of file feverblurstate.c.
Referenced by OnUpdateClient().
m_DestroyOnAnimFinish
bool SymptomBase::m_DestroyOnAnimFinish = true private
Definition at line 16 of file statebase.c.
Referenced by AnimationFinish().
m_DestroyRequested
bool SymptomBase::m_DestroyRequested = false private
Definition at line 17 of file statebase.c.
Referenced by CheckDestroy(), and RequestDestroy().
m_Duration
float SymptomBase::m_Duration private
Definition at line 22 of file statebase.c.
Referenced by CheckSoundFinished(), GetDuration(), and SetDuration().
m_EffectStartTime
float SymptomBase::m_EffectStartTime private
Definition at line 8 of file feverblurstate.c.
m_EffectTime
float SymptomBase::m_EffectTime private
Definition at line 7 of file feverblurstate.c.
m_ID
int SymptomBase::m_ID private
Definition at line 13 of file statebase.c.
Referenced by GetType().
m_IsActivated
bool SymptomBase::m_IsActivated private
Definition at line 7 of file statebase.c.
Referenced by Activate(), Deactivate(), and IsActivated().
m_IsClientOnly
bool SymptomBase::m_IsClientOnly private
Definition at line 15 of file statebase.c.
Referenced by IsClientOnly().
m_IsPersistent
bool SymptomBase::m_IsPersistent = false private
Definition at line 19 of file statebase.c.
Referenced by IsPersistent().
m_IsTemplate
bool SymptomBase::m_IsTemplate = true private
Definition at line 11 of file statebase.c.
Referenced by Destroy(), and Init().
m_Manager
SymptomManager SymptomBase::m_Manager private
Definition at line 20 of file statebase.c.
Referenced by GetManager(), Init(), and OnDestructed().
m_MatGauss
Material SymptomBase::m_MatGauss private
Definition at line 3 of file blindnessstate.c.
m_MaxCount
int SymptomBase::m_MaxCount = -1 private
Definition at line 24 of file statebase.c.
Referenced by GetMaxCount().
m_PersistentParams
ref array<Param> SymptomBase::m_PersistentParams = new array<Param> private
Definition at line 28 of file statebase.c.
Referenced by GetPersistentParams(), and MakeParamObjectPersistent().
m_PlayedSound
bool SymptomBase::m_PlayedSound private
Definition at line 6 of file statebase.c.
Referenced by CheckSoundFinished(), and PlaySound().
m_Player
PlayerBase SymptomBase::m_Player private
Definition at line 8 of file statebase.c.
Referenced by Activate(), Deactivate(), GetPlayer(), Init(), PlayAnimationADD(), PlayAnimationFB(), and Update().
m_Position
ref Param1<vector> SymptomBase::m_Position = new Param1<vector>("0 0 0") private
Definition at line 5 of file blindnessstate.c.
m_Priority
int SymptomBase::m_Priority private
Definition at line 4 of file statebase.c.
Referenced by GetPriority().
m_Requester
protected PPERequester_FeverEffects SymptomBase::m_Requester private
Definition at line 10 of file feverblurstate.c.
m_RequesterBloodLoss
PPERequester_BloodLoss SymptomBase::m_RequesterBloodLoss private
Definition at line 6 of file bloodloss.c.
m_ServerUpdateDelta
float SymptomBase::m_ServerUpdateDelta private
Definition at line 10 of file statebase.c.
Referenced by Update().
m_ServerUpdateInterval
float SymptomBase::m_ServerUpdateInterval = 1 private
Definition at line 9 of file statebase.c.
Referenced by Update().
m_ShakeLevel
int SymptomBase::m_ShakeLevel private
Definition at line 4 of file handshivers.c.
m_SoundObject
SoundOnVehicle SymptomBase::m_SoundObject private
Definition at line 5 of file statebase.c.
m_SymptomType
int SymptomBase::m_SymptomType = -1 private
Definition at line 18 of file statebase.c.
Referenced by IsPrimary().
m_SyncToClient
bool SymptomBase::m_SyncToClient = false private
Definition at line 21 of file statebase.c.
Referenced by IsSyncToClient().
m_Time
float SymptomBase::m_Time private
Definition at line 9 of file feverblurstate.c.
m_UID
int SymptomBase::m_UID private
Definition at line 14 of file statebase.c.
Referenced by GetUID(), Init(), and OnDestructed().
MAX_TIME_ACTIVE_SAVEGUARD
const float SymptomBase::MAX_TIME_ACTIVE_SAVEGUARD = 20 private
Definition at line 3 of file statebase.c.
Referenced by CheckDestroy().
MAX_TIME_BETWEEN_EFFECTS
const int SymptomBase::MAX_TIME_BETWEEN_EFFECTS = 35.0 private
Definition at line 19 of file feverblurstate.c.
MIN_TIME_BETWEEN_EFFECTS
const int SymptomBase::MIN_TIME_BETWEEN_EFFECTS = 25.0 private
Definition at line 18 of file feverblurstate.c.