DayzKode: DayZCreatureAI Class Reference
DayZCreatureAI Class Reference
do not process rotations !
Private Member Functions
void CommandHandler (float dt, int currentCommandID, bool currentCommandFinished)
bool ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction)
float ComputeHitDirectionAngleDeg (EntityAI source)
float ConvertNonlethalDamage (float damage)
void DayZAnimal ()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
override protected void EOnContact (IEntity other, Contact extra)
int FindComponentDirectionOffset (string component)
proto native DayZAnimalCommandScript GetCommand_Script ()
override string GetDefaultHitComponent ()
override vector GetDefaultHitPosition ()
override string GetDefaultHitPositionComponent ()
override int GetHideIconMask ()
override string GetHitComponentForAI ()
proto native DayZAnimalInputController GetInputController ()
bool HandleDamageHit (int currentCommandID)
bool HandleDeath (int currentCommandID, DayZAnimalInputController inputController)
override bool IsAnimal ()
override bool IsHealthVisible ()
override bool IsInventoryVisible ()
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
void QueueDamageHit (int type, int direction)
void RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
protected vector SetDefaultHitPosition (string pSelection)
proto native void SignalAIAttackEnded ()
proto native void SignalAIAttackStarted ()
proto native void StartCommand_Attack ()
proto native void StartCommand_Death (int pType, int pDirection)
proto native void StartCommand_Hit (int pType, int pDirection)
proto native void StartCommand_Jump ()
proto native void StartCommand_Move ()
proto native DayZAnimalCommandScript StartCommand_Script (DayZAnimalCommandScript pInfectedCommand)
scripted commands
proto native DayZAnimalCommandScript StartCommand_ScriptInst (typename pCallbackClass)
int TranslateHitAngleDegToDirectionIndex (float angleDeg)
Private Attributes
int m_DamageHitDirection = 0
bool m_DamageHitToProcess = false
int m_DamageHitType = 0
protected string m_DefaultHitComponent
protected vector m_DefaultHitPosition
protected string m_DefaultHitPositionComponent
protected ref array< ref DayZAIHitComponent > m_HitComponentsForAI
Melee hit components (AI targeting)
Detailed Description
do not process rotations !
Definition at line 395 of file dayzanimal.c.
Member Function Documentation
CommandHandler()
void DayZCreatureAI::CommandHandler (float dt, int currentCommandID, bool currentCommandFinished) inline private
for mods
for mods
Definition at line 460 of file dayzanimal.c.
    {
        DayZAnimalInputController inputController = GetInputController();
        if( ModCommandHandlerBefore(dt, currentCommandID, currentCommandFinished) )
        {
            return;
        }
        if (HandleDeath(currentCommandID, inputController))
        {
            return;
        }
        if (currentCommandFinished)
        {
            if (currentCommandID == DayZAnimalConstants.COMMANDID_ATTACK)
            {
                SignalAIAttackEnded();
            }
            StartCommand_Move();
            return;
        }
        if( ModCommandHandlerInside(dt, currentCommandID, currentCommandFinished) )
        {
            return;
        }
        if (HandleDamageHit(currentCommandID))
        {
            if (currentCommandID  == DayZAnimalConstants.COMMANDID_ATTACK)
            {
                SignalAIAttackEnded();
            }
            return;
        }
        if (currentCommandID == DayZAnimalConstants.COMMANDID_MOVE)
        {
            if (inputController.IsJump())
            {
                StartCommand_Jump();
                return;
            }
            if (inputController.IsAttack())
            {
                StartCommand_Attack();
                SignalAIAttackStarted();
                return;
            }
        }
        if( ModCommandHandlerAfter(dt, currentCommandID, currentCommandFinished) )
        {
            return;
        }
    }
References GetInputController(), HandleDamageHit(), HandleDeath(), DayZAnimalInputController::IsAttack(), DayZAnimalInputController::IsJump(), ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), and StartCommand_Move().
ComputeDamageHitParams()
bool DayZCreatureAI::ComputeDamageHitParams (EntityAI source, string dmgZone, string ammo, out int type, out int direction) inline private
Definition at line 625 of file dayzanimal.c.
    {
        type = 0; // not used right now
        float angleDeg = ComputeHitDirectionAngleDeg(source);
        direction = TranslateHitAngleDegToDirectionIndex(angleDeg);
        direction += FindComponentDirectionOffset(dmgZone);
        return true;
    }
ComputeHitDirectionAngleDeg()
float DayZCreatureAI::ComputeHitDirectionAngleDeg (EntityAI source) inline private
Definition at line 637 of file dayzanimal.c.
    {
        vector targetDirection = GetDirection();
        vector toSourceDirection = (source.GetPosition() - GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        float dirAngleDeg = Math.Acos(cosFi) * Math.RAD2DEG;
        if ( cross[1] < 0 )
            dirAngleDeg = -dirAngleDeg;
        return dirAngleDeg;
    }
References Math::Acos(), vector::Dot(), GetDirection(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
ConvertNonlethalDamage()
float DayZCreatureAI::ConvertNonlethalDamage (float damage) inline private
Definition at line 761 of file dayzanimal.c.
    {
        float converted_dmg = damage * GameConstants.PROJECTILE_CONVERSION_ANIMALS;
        return converted_dmg;
    }
References GameConstants::PROJECTILE_CONVERSION_ANIMALS.
DayZAnimal()
void DayZCreatureAI::DayZAnimal () inline private
sets default hit position and cache it here (mainly for impact particles)
Definition at line 420 of file dayzanimal.c.
    {
        // testing: animals have no inventory by default
        //GetInventory().LockInventory(LOCK_FROM_SCRIPT); // Hides animals from vicinity in inventory. Remove this if wanted otherwise.
        m_HitComponentsForAI = new array<ref DayZAIHitComponent>;
        RegisterHitComponentsForAI();
        m_DefaultHitPosition = SetDefaultHitPosition(GetDefaultHitPositionComponent());
    }
References GetDefaultHitPositionComponent(), m_HitComponentsForAI, and RegisterHitComponentsForAI().
EEHitBy()
override void DayZCreatureAI::EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef) inline private
Definition at line 593 of file dayzanimal.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        m_TransportHitRegistered = false;
        if( ammo.ToType().IsInherited(Nonlethal_Base) )
        {
            //Print("DayZAnimal | EEHitBy | nonlethal hit");
            AddHealth("","Health",-ConvertNonlethalDamage(damageResult.GetDamage(dmgZone,"Shock")));
        }
        else
        {
            ComponentAnimalBleeding animal_bleeding = ComponentAnimalBleeding.Cast( GetComponent( COMP_TYPE_ANIMAL_BLEEDING ) );
            animal_bleeding.CreateWound( damageResult, dmgZone, ammo );
        }
        int type = 0;
        int direction = 0;
        if (ComputeDamageHitParams(source, dmgZone, ammo, type, direction) == true)
        {
            QueueDamageHit(type, direction);
        }
    }
References AddHealth(), COMP_TYPE_ANIMAL_BLEEDING, component, ComponentAnimalBleeding::CreateWound(), TotalDamageResult::GetDamage(), and string::ToType().
EOnContact()
override protected void DayZCreatureAI::EOnContact (IEntity other, Contact extra) inline private
Phx contact event
Definition at line 702 of file dayzanimal.c.
    {
        if( !IsAlive() )
            return;
        Transport transport = Transport.Cast(other);
        if( transport )
        {
            if ( GetGame().IsServer() )
            {
                RegisterTransportHit(transport);
            }
        }
    }
References GetGame(), and IsAlive().
FindComponentDirectionOffset()
int DayZCreatureAI::FindComponentDirectionOffset (string component) inline private
Definition at line 672 of file dayzanimal.c.
    {
        const int directionCount = 4;
        int offset = 0;
        if (component.Length() == 0)
        {
            offset = 0;
        }
        else if (component == "Zone_Head")
        {
            offset = directionCount;
        }
        else if (component == "Zone_Chest" || component == "Zone_Legs_Front" || component == "Zone_Spine_Front" || component == "Zone_Neck")
        {
            offset = 2 * directionCount;
        }
        else
        {
            offset = 3 * directionCount;
        }
        return offset;
    }
References component.
GetCommand_Script()
proto native DayZAnimalCommandScript DayZCreatureAI::GetCommand_Script () private
GetDefaultHitComponent()
override string DayZCreatureAI::GetDefaultHitComponent () inline private
Definition at line 741 of file dayzanimal.c.
    {
        return m_DefaultHitComponent;
    }
References m_DefaultHitComponent.
GetDefaultHitPosition()
override vector DayZCreatureAI::GetDefaultHitPosition () inline private
Definition at line 751 of file dayzanimal.c.
    {
        return m_DefaultHitPosition;
    }
GetDefaultHitPositionComponent()
override string DayZCreatureAI::GetDefaultHitPositionComponent () inline private
Definition at line 746 of file dayzanimal.c.
    {
        return m_DefaultHitPositionComponent;
    }
References m_DefaultHitPositionComponent.
GetHideIconMask()
override int DayZCreatureAI::GetHideIconMask () inline private
Definition at line 448 of file dayzanimal.c.
    {
        return EInventoryIconVisibility.HIDE_VICINITY;
        /*
        if (IsAlive())
        {
            return EInventoryIconVisibility.HIDE_VICINITY;
        }
        return super.GetHideIconMask();
        */
    }
GetHitComponentForAI()
override string DayZCreatureAI::GetHitComponentForAI () inline private
Definition at line 729 of file dayzanimal.c.
    {
        string hitComp;
        if (DayZAIHitComponentHelpers.SelectMostProbableHitComponent(m_HitComponentsForAI, hitComp))
        {
            return hitComp;
        }
        return GetDefaultHitComponent();
    }
References GetDefaultHitComponent(), m_HitComponentsForAI, and DayZAIHitComponentHelpers::SelectMostProbableHitComponent().
GetInputController()
proto native DayZAnimalInputController DayZCreatureAI::GetInputController () private
HandleDamageHit()
bool DayZCreatureAI::HandleDamageHit (int currentCommandID) inline private
Definition at line 578 of file dayzanimal.c.
    {
        if (m_DamageHitToProcess)
        {
            m_DamageHitToProcess = false;
            if (currentCommandID != DayZAnimalConstants.COMMANDID_HIT)
            {
                StartCommand_Hit(m_DamageHitType, m_DamageHitDirection);
            }
            return true;
        }
        return false;
    }
HandleDeath()
bool DayZCreatureAI::HandleDeath (int currentCommandID, DayZAnimalInputController inputController) inline private
Definition at line 550 of file dayzanimal.c.
    {
        if (inputController.IsDead())
        {
            if (currentCommandID == DayZAnimalConstants.COMMANDID_DEATH)
            {
                return true;
            }
            if (m_DamageHitToProcess)
            {
                m_DamageHitToProcess = false;
                StartCommand_Death(m_DamageHitType, m_DamageHitDirection);
            }
            else
            {
                StartCommand_Death(0, 0);
            }
            dBodySetInteractionLayer(this, PhxInteractionLayers.RAGDOLL);
            return true;
        }
        return false;
    }
References dBodySetInteractionLayer(), DayZAnimalInputController::IsDead(), and StartCommand_Death().
IsAnimal()
override bool DayZCreatureAI::IsAnimal () inline private
Definition at line 438 of file dayzanimal.c.
    {
        return true;
    }
IsHealthVisible()
override bool DayZCreatureAI::IsHealthVisible () inline private
Definition at line 433 of file dayzanimal.c.
    {
        return false;
    }
IsInventoryVisible()
override bool DayZCreatureAI::IsInventoryVisible () inline private
Definition at line 443 of file dayzanimal.c.
    {
        return false;
    }
ModCommandHandlerAfter()
bool DayZCreatureAI::ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 541 of file dayzanimal.c.
    {
        return false;
    }
ModCommandHandlerBefore()
bool DayZCreatureAI::ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
ModOverrides
Definition at line 531 of file dayzanimal.c.
    {
        return false;
    }
ModCommandHandlerInside()
bool DayZCreatureAI::ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished) inline private
Definition at line 536 of file dayzanimal.c.
    {
        return false;
    }
QueueDamageHit()
void DayZCreatureAI::QueueDamageHit (int type, int direction) inline private
Definition at line 618 of file dayzanimal.c.
    {
        m_DamageHitToProcess = true;
        m_DamageHitType = type;
        m_DamageHitDirection = direction;
    }
RegisterHitComponentsForAI()
void DayZCreatureAI::RegisterHitComponentsForAI () inline private
register hit components for AI melee (used by attacking AI)
registers default hit compoent for the entity
registers default hit position component for entity
register hit components that are selected by probability
Definition at line 718 of file dayzanimal.c.
    {
        m_DefaultHitComponent = "Zone_Chest";
        m_DefaultHitPositionComponent = "Pelvis";
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Zone_Chest", 50);
    }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, and DayZAIHitComponentHelpers::RegisterHitComponent().
SetDefaultHitPosition()
protected vector DayZCreatureAI::SetDefaultHitPosition (string pSelection) inline private
Definition at line 756 of file dayzanimal.c.
    {
        return GetSelectionPositionMS(pSelection);
    }
References GetSelectionPositionMS().
SignalAIAttackEnded()
proto native void DayZCreatureAI::SignalAIAttackEnded () private
SignalAIAttackStarted()
proto native void DayZCreatureAI::SignalAIAttackStarted () private
StartCommand_Attack()
proto native void DayZCreatureAI::StartCommand_Attack () private
StartCommand_Death()
proto native void DayZCreatureAI::StartCommand_Death (int pType, int pDirection) private
StartCommand_Hit()
proto native void DayZCreatureAI::StartCommand_Hit (int pType, int pDirection) private
StartCommand_Jump()
proto native void DayZCreatureAI::StartCommand_Jump () private
StartCommand_Move()
proto native void DayZCreatureAI::StartCommand_Move () private
StartCommand_Script()
proto native DayZAnimalCommandScript DayZCreatureAI::StartCommand_Script (DayZAnimalCommandScript pInfectedCommand) private
scripted commands
StartCommand_ScriptInst()
proto native DayZAnimalCommandScript DayZCreatureAI::StartCommand_ScriptInst (typename pCallbackClass) private
TranslateHitAngleDegToDirectionIndex()
int DayZCreatureAI::TranslateHitAngleDegToDirectionIndex (float angleDeg) inline private
Definition at line 658 of file dayzanimal.c.
    {
        if (angleDeg >= -20 && angleDeg <= 20) // front
        {
            return 1;
        }
        else if (angleDeg < 0) // left
        {
            return 2;
        }
        return 3; // right
    }
Member Data Documentation
m_DamageHitDirection
int DayZCreatureAI::m_DamageHitDirection = 0 private
Definition at line 548 of file dayzanimal.c.
m_DamageHitToProcess
bool DayZCreatureAI::m_DamageHitToProcess = false private
Definition at line 546 of file dayzanimal.c.
m_DamageHitType
int DayZCreatureAI::m_DamageHitType = 0 private
Definition at line 547 of file dayzanimal.c.
m_DefaultHitComponent
protected string DayZCreatureAI::m_DefaultHitComponent private
Definition at line 400 of file dayzanimal.c.
m_DefaultHitPosition
protected vector DayZCreatureAI::m_DefaultHitPosition private
Definition at line 402 of file dayzanimal.c.
m_DefaultHitPositionComponent
protected string DayZCreatureAI::m_DefaultHitPositionComponent private
Definition at line 401 of file dayzanimal.c.
m_HitComponentsForAI
protected ref array<ref DayZAIHitComponent> DayZCreatureAI::m_HitComponentsForAI private
Melee hit components (AI targeting)
Definition at line 399 of file dayzanimal.c.