DayzKode: Hud Class Reference
Hud Class Reference
Private Member Functions
void CleanupHitDirEffects ()
void DisplayBadge (int key, int value)
override void DisplayBadge (int key, int value)
void DisplayNotifier (int key, int tendency, int status)
override void DisplayNotifier (int key, int tendency, int status)
void DisplayPresence ()
override void DisplayPresence ()
void DisplayStance (int stance)
override void DisplayStance (int stance)
void DisplayTendencyNormal (int key, int tendency, int status)
void DisplayTendencyTemp (int key, int tendency, int status)
Widget GetHudPanelWidget ()
bool GetHudState ()
InventoryQuickbar GetQuickbar ()
bool GetQuickBarState ()
void HideCursor ()
override void HideCursor ()
void HideQuickbarTimer ()
void HideTemperature ()
void HideVehicleInfo ()
override void HideVehicleInfo ()
void IngameHud ()
void Init (Widget hud_panel_widget)
override void Init (Widget hud_panel_widget)
void InitBadgesAndNotifiers ()
void InitQuickbar ()
bool IsHideHudPlayer ()
bool IsHideQuickbarPlayer ()
bool IsHudVisible ()
bool IsQuickbarVisible ()
bool KeyPress (int key)
void OnResizeScreen ()
override void OnResizeScreen ()
void RefreshHudVisibility ()
void RefreshPlayerTags ()
void RefreshQuickbar (bool itemChanged=false)
override void RefreshQuickbar (bool itemChanged=false)
void RefreshQuickbarVisibility ()
void RefreshVehicleHud (float timeslice)
void SetCursorIcon (string icon)
override void SetCursorIcon (string icon)
void SetCursorIconOffset (string type, float x, float y)
override void SetCursorIconOffset (string type, float x, float y)
void SetCursorIconScale (string type, float percentage)
override void SetCursorIconScale (string type, float percentage)
void SetCursorIconSize (string type, float x, float y)
override void SetCursorIconSize (string type, float x, float y)
void SetLeftStatsVisibility (bool visible)
eg. stamina bar...
void SetPermanentCrossHair (bool show)
void SetStamina (int value, int range)
override void SetStamina (int value, int range)
void SetStaminaBarVisibility (bool show)
override void SetStaminaBarVisibility (bool show)
void SetStomachState (int state)
void SetTemperature (string temp)
override void SetTemperature (string temp)
void SetWalkieTalkieText (string text)
override void SetWalkieTalkieText (string text)
void Show (bool show)
override void Show (bool show)
void ShowCursor ()
override void ShowCursor ()
void ShowHud (bool show)
override void ShowHud (bool show)
void ShowHudInventory (bool show)
override void ShowHudInventory (bool show)
void ShowHudPlayer (bool show)
override void ShowHudPlayer (bool show)
void ShowHudUI (bool show)
override void ShowHudUI (bool show)
void ShowPlayerTag (float timeslice)
void ShowQuickBar (bool show)
override void ShowQuickBar (bool show)
global setting; is quickbar visibility allowed?
void ShowQuickbarPlayer (bool show)
override void ShowQuickbarPlayer (bool show)
void ShowQuickbarUI (bool show)
override void ShowQuickbarUI (bool show)
void ShowVehicleInfo ()
override void ShowVehicleInfo ()
void ShowWalkieTalkie (bool show)
override void ShowWalkieTalkie (bool show)
void ShowWalkieTalkie (int fadeOutSeconds)
override void ShowWalkieTalkie (int fadeOutSeconds)
void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max)
override void SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max)
void ToggleHeatBufferPlusSign (bool show)
override void ToggleHeatBufferPlusSign (bool show)
void Update (float timeslice)
override void Update (float timeslice)
void UpdateBloodName ()
override void UpdateBloodName ()
void UpdateHitDirEffects (float timeslice)
void UpdateSpecialtyMeter (float x, float y)
void ZeroingKeyPress ()
Private Attributes
protected const float FADE_IN_TIME = 0.3
protected const float FADE_OUT_TIME = 0.3
protected const float HIDE_MENU_TIME = 5
protected TextWidget m_ActionButtonText
protected TextWidget m_ActionDesc
protected Widget m_ActionItemQuantityWrapper protected ImageWidget m_ActionHealthMark
protected ImageWidget m_ActionIcon
protected Widget m_ActionIconFrame
protected TextWidget m_ActionItemDesc
protected Widget m_ActionMultipleItemsFrame
protected ProgressBarWidget m_ActionQuantityBar
protected Widget m_ActionQuantityBox
protected TextWidget m_ActionQuantityBoxText
protected Widget m_ActionTarget
protected ActionTargetsCursor m_ActionTargetsCursor
protected Widget m_ActionWidget
protected bool m_AnyBadgeVisible
protected Widget m_BadgeNotifierDivider
protected Widget m_Badges
protected ref map< int, int > m_BadgesWidgetDisplay
protected ref map< int, string > m_BadgesWidgetNames
protected ref map< int, ImageWidget > m_BadgesWidgets
protected float m_BlinkTime
protected TextWidget m_BloodPosType
protected TextWidget m_BloodType
PlayerBase m_CurrentTaggedPlayer
protected CarScript m_CurrentVehicle
protected ImageWidget m_CursorIcon
protected Widget m_CursorWidget
protected bool m_Faded
protected ref WidgetFadeTimer m_FadeTimerActionCursor
protected ref WidgetFadeTimer m_FadeTimerCrosshair
protected ref WidgetFadeTimer m_FadeTimerMagazineName
protected ref WidgetFadeTimer m_FadeTimerQuickbar
protected ref array< ref WidgetFadeTimer > m_FadeTimers = new array<ref WidgetFadeTimer>
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkie
protected ref WidgetFadeTimer m_FadeTimerWalkieTalkieText
protected ref WidgetFadeTimer m_FadeTimerWeaponName
protected ref WidgetFadeTimer m_FadeTimerWeaponStats
protected ref WidgetFadeTimer m_FadeTimerZeroingOld
protected ImageWidget m_HeatBufferPlus
protected ref Timer m_HideTimer
ref array< ref HitDirectionEffectBase > m_HitDirEffectArray
protected Widget m_HitIndicatorDown
protected Widget m_HitIndicatorLeft
protected Widget m_HitIndicatorRight
protected Widget m_HitIndicatorSingle
protected Widget m_HitIndicatorUp
protected bool m_HudHidePlayer
protected bool m_HudHideUI
protected bool m_HudInventory
protected Widget m_HudPanelWidget
protected bool m_HudState
protected bool m_InVehicleAsDriver
protected bool m_IsHudVisible
protected bool m_IsQuickbarVisible
protected bool m_IsStaminaVisible
protected bool m_IsTemperatureVisible
protected Widget m_LeftHudPanelWidget
protected Widget m_MouseContinuousAction
protected Widget m_MouseSingleAction
protected Widget m_Notifiers
protected ImageWidget m_PermanentCrossHair
int m_PlayerSpineIndex
Widget m_PlayerTag
TextWidget m_PlayerTagText
protected Widget m_Presence
protected Widget m_PresenceLevel0
protected Widget m_PresenceLevel1
protected Widget m_PresenceLevel2
protected Widget m_PresenceLevel3
protected Widget m_PresenceLevel4
protected ref InventoryQuickbar m_Quickbar
protected bool m_QuickbarHidePlayer
protected bool m_QuickbarHideUI
protected bool m_QuickbarState
protected Widget m_QuickbarWidget
protected Widget m_RadialProgressBar
protected Widget m_RadialProgressBar1
protected Widget m_RadialProgressBarCrossHair
protected Widget m_SpecializationIcon
protected Widget m_SpecializatonPanel
protected ProgressBarWidget m_Stamina
protected Widget m_StaminaBackground
protected float m_StaminaShowTime = 0.15
protected float m_StaminaTimer
protected Widget m_StanceCar
protected Widget m_StanceCrouch
protected Widget m_StancePanel
protected Widget m_StanceProne
protected Widget m_StanceStand
protected Widget m_StanceStandWalk
protected ref map< int, string > m_StatesWidgetNames
protected ref map< int, ImageWidget > m_StatesWidgets
protected float m_TemperatureShowTime = 30
protected float m_TemperatureTimer
protected ref map< ImageWidget, int > m_TendencyStatusCritical
ref Timer m_Timer
float m_TimeSinceLastEngineLightChange
protected ImageWidget m_VehicleBatteryLight
protected TextWidget m_VehicleCurrentGearValue
protected bool m_VehicleDamageZoneHitEngineState
protected float m_VehicleDamageZonesHitTimer
protected ImageWidget m_VehicleEngineLight
protected ImageWidget m_VehicleFuelLight
protected ImageWidget m_VehicleFuelPointer
int m_VehicleGearCount = -1
protected ref map< int, string > m_VehicleGearTable
protected ref map< int, string > m_VehicleGearTableAuto
protected ImageWidget m_VehicleHandBrakeLight
bool m_VehicleHasCoolant
bool m_VehicleHasOil
protected TextWidget m_VehicleNextGearValue
protected ImageWidget m_VehicleOilLight
protected Widget m_VehiclePanel
protected TextWidget m_VehiclePrevGearValue
protected ImageWidget m_VehicleRPMDial
protected ImageWidget m_VehicleRPMPointer
protected ImageWidget m_VehicleRPMRedline
protected ImageWidget m_VehicleSpeedPointer
protected TextWidget m_VehicleSpeedValue
protected Widget m_VehicleTemperatureIndicator
protected ImageWidget m_VehicleTemperatureLight
protected ImageWidget m_VehicleTemperaturePointer
protected ImageWidget m_VehicleWheelLight
protected Widget m_WalkieTalkie
protected bool m_ZeroingKeyPressed
protected ref Timer myTimer
protected const float TENDENCY_BLINK_TIME = 0.25
Detailed Description
Definition at line 615 of file gameplay.c.
Member Function Documentation
CleanupHitDirEffects()
void Hud::CleanupHitDirEffects () inline private
Definition at line 1404 of file ingamehud.c.
    {
        for (int i = m_HitDirEffectArray.Count() - 1; i > -1; i--)
        {
            if ( m_HitDirEffectArray[i].DurationCheck() )
            {
                m_HitDirEffectArray.Remove(i);
            }
        }
    }
Referenced by Update().
DisplayBadge() [1/2]
void Hud::DisplayBadge (int key, int value) inline private
Definition at line 620 of file gameplay.c.
{}
Referenced by PluginBase::SetBadge().
DisplayBadge() [2/2]
override void Hud::DisplayBadge (int key, int value) inline private
Definition at line 583 of file ingamehud.c.
    {
        TextWidget bleed_count = TextWidget.Cast( m_Badges.FindAnyWidget( "BleedingCount" ) );
        m_BadgesWidgetDisplay.Set( key, value );
        m_AnyBadgeVisible = false;
        for ( int i = 0; i < m_BadgesWidgetDisplay.Count(); i++ )
        {
            int badge_key = m_BadgesWidgetDisplay.GetKey( i );
            string badge_name = m_BadgesWidgetNames.Get( badge_key );
            ImageWidget badge_widget
            Class.CastTo(badge_widget,  m_Badges.FindAnyWidget( badge_name ) );
            if ( badge_widget )
            {
                if ( m_BadgesWidgetDisplay.Get( badge_key ) > 0 )
                {
                    badge_widget.Show( true );
                    m_AnyBadgeVisible = true;
                    if( badge_key == NTFKEY_BLEEDISH )
                    {
                        bleed_count.Show( true );
                        bleed_count.SetText( m_BadgesWidgetDisplay.Get( badge_key ).ToString() );
                    }
                }
                else
                {
                    if( badge_key == NTFKEY_BLEEDISH )
                    {
                        bleed_count.Show( false );
                    }
                    badge_widget.Show( false );
                }
            }
        }
        RefreshHudVisibility();
    }
References Class::CastTo(), NTFKEY_BLEEDISH, and RefreshHudVisibility().
DisplayNotifier() [1/2]
void Hud::DisplayNotifier (int key, int tendency, int status) inline private
Definition at line 619 of file gameplay.c.
{}
Referenced by PluginBase::DisplayTendency().
DisplayNotifier() [2/2]
override void Hud::DisplayNotifier (int key, int tendency, int status) inline private
Definition at line 446 of file ingamehud.c.
    {
        ImageWidget w;
        if ( key == NTFKEY_FEVERISH )
        {
            DisplayTendencyTemp( key, tendency, status );
        }
        else
        {
            DisplayTendencyNormal( key, tendency, status );
        }
        // tendency arrows
        string arrow_name = "ArrowUp";
        if ( tendency < 0 )
        {
            arrow_name = "ArrowDown";
        }
        tendency = Math.AbsInt( tendency );
        for ( int x = 1; x < 4; x++ )
        {
            Class.CastTo(w,  m_Notifiers.FindAnyWidget( String(  m_StatesWidgetNames.Get( key ) + "ArrowUp" + x.ToString() ) ) );
            if( w )
                w.Show( false );
            Class.CastTo(w,  m_Notifiers.FindAnyWidget( String(  m_StatesWidgetNames.Get( key ) + "ArrowDown" + x.ToString() ) ) );
            if( w )
                w.Show( false );
        }
        if( tendency > 0 )
        {
            string widget_name = m_StatesWidgetNames.Get( key ) + arrow_name + Math.Clamp( tendency, 1, 3 );
            Class.CastTo(w, m_Notifiers.FindAnyWidget( widget_name ) );
            if( w )
                w.Show( true );
        }
    }
References Math::AbsInt(), Class::CastTo(), Math::Clamp(), DisplayTendencyNormal(), DisplayTendencyTemp(), m_Notifiers, NTFKEY_FEVERISH, String(), and x.
DisplayPresence() [1/2]
void Hud::DisplayPresence () inline private
Definition at line 623 of file gameplay.c.
{}
Referenced by Update().
DisplayPresence() [2/2]
override void Hud::DisplayPresence () inline private
Definition at line 767 of file ingamehud.c.
    {
        PlayerBase player;
        if ( Class.CastTo(player, GetGame().GetPlayer()) )
        {
            int presence_level = player.GetNoisePresenceInAI();
            m_PresenceLevel0.Show( false );
            m_PresenceLevel1.Show( false );
            m_PresenceLevel2.Show( false );
            m_PresenceLevel3.Show( false );
            m_PresenceLevel4.Show( false );
            if ( presence_level > 0 )
            {
                m_PresenceLevel0.Show( true );
            }
            if ( presence_level > 1 )
            {
                m_PresenceLevel1.Show( true );
            }
            if ( presence_level > 2 )
            {
                m_PresenceLevel2.Show( true );
            }
            if ( presence_level > 3 )
            {
                m_PresenceLevel3.Show( true );
            }
            if ( presence_level > 4 )
            {
                m_PresenceLevel4.Show( true );
            }
        }
    }
References Class::CastTo(), GetGame(), and GetPlayer().
DisplayStance() [1/2]
void Hud::DisplayStance (int stance) inline private
Definition at line 622 of file gameplay.c.
{}
Referenced by PluginBase::SetStance().
DisplayStance() [2/2]
override void Hud::DisplayStance (int stance) inline private
Definition at line 725 of file ingamehud.c.
    {
        PlayerBase player;
        Class.CastTo(player,  GetGame().GetPlayer() );
        Car car;
        if ( !Class.CastTo(car, player.GetDrivingVehicle()) )
        {
            if( stance == 1 )
            {
                bool is_walking;
                m_StanceStand.Show(!is_walking);
                m_StanceStandWalk.Show(is_walking);
                m_StanceCrouch.Show(false);
                m_StanceProne.Show(false);
                m_StanceCar.Show( false );
            }
            if( stance == 2 )
            {
                m_StanceStand.Show(false);
                m_StanceStandWalk.Show(false);
                m_StanceCrouch.Show(true);
                m_StanceProne.Show(false);
                m_StanceCar.Show( false );
            }
            if( stance == 3 )
            {
                m_StanceStand.Show(false);
                m_StanceStandWalk.Show(false);
                m_StanceCrouch.Show(false);
                m_StanceProne.Show(true);
                m_StanceCar.Show( false );
            }
        }
        else
        {
            m_StanceStand.Show(false);
            m_StanceCrouch.Show(false);
            m_StanceProne.Show(false);
            m_StanceCar.Show( true );
        }
    }
References Class::CastTo(), GetGame(), and GetPlayer().
DisplayTendencyNormal()
void Hud::DisplayTendencyNormal (int key, int tendency, int status) inline private
Definition at line 485 of file ingamehud.c.
    {
        ImageWidget w;
        Class.CastTo(w,  m_Notifiers.FindAnyWidget( String( "Icon" + m_StatesWidgetNames.Get( key ) ) ) );
        if( w )
        {
            w.SetImage( Math.Clamp( status - 1, 0, 4 ) );
            float alpha = w.GetAlpha();
            switch( status )
            {
                case 3:
                    w.SetColor( ARGB( alpha * 255, 220, 220, 0 ) );     //yellow
                    m_TendencyStatusCritical.Remove( w );               //remove from blinking group
                    break;
                case 4:
                    w.SetColor( ARGB( alpha * 255, 220, 0, 0 ) );       //red
                    m_TendencyStatusCritical.Remove( w );               //remove from blinking group
                    break;
                case 5:
                    if ( !m_TendencyStatusCritical.Contains( w ) )
                    {
                        m_TendencyStatusCritical.Insert( w, ARGB( alpha * 255, 220, 0, 0 ) );   //add to blinking group
                    }
                    break;
                default:
                    w.SetColor( ARGB( alpha * 255, 220, 220, 220 ) );   //white
                    m_TendencyStatusCritical.Remove( w );               //remove from blinking group
                    break;
            }
        }
    }
References ARGB(), Class::CastTo(), Math::Clamp(), m_Notifiers, and String().
Referenced by DisplayNotifier().
DisplayTendencyTemp()
void Hud::DisplayTendencyTemp (int key, int tendency, int status) inline private
Definition at line 519 of file ingamehud.c.
    {
        ImageWidget w = ImageWidget.Cast( m_Notifiers.FindAnyWidget( String( "Icon" + m_StatesWidgetNames.Get( key ) ) ) );
        TextWidget temp_top = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueTop" ) );
        TextWidget temp_bot = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueBottom" ) );
        //string temp = player..ToString() + "C";
        float alpha = w.GetAlpha();
        if ( tendency < 0 )
        {
            temp_top.Show( true );
            temp_bot.Show( false );
        }
        else
        {
            temp_top.Show( false );
            temp_bot.Show( true );
        }
        switch( status )
        {
            case 2:
                w.SetColor( ARGB( alpha * 255, 220, 220, 0 ) );     //WARNING_PLUS
                m_TendencyStatusCritical.Remove( w );
                w.SetImage( 1 );
                break;
            case 3:
                w.SetColor( ARGB( alpha * 255, 220, 0, 0 ) );       //CRITICAL_PLUS
                m_TendencyStatusCritical.Remove( w );
                w.SetImage( 0 );
                break;
            case 4:
                if ( !m_TendencyStatusCritical.Contains( w ) )      //BLINKING_PLUS
                {
                    m_TendencyStatusCritical.Insert( w, ARGB( alpha * 255, 220, 0, 0 ) );
                }
                w.SetImage( 0 );
                break;
            case 5:
                w.SetColor( ARGB( alpha * 255, 0, 206, 209 ) );     //WARNING_MINUS
                m_TendencyStatusCritical.Remove( w );
                w.SetImage( 3 );
                break;
            case 6:
                w.SetColor( ARGB( alpha * 255, 30, 144, 220 ) );    //CRITICAL_MINUS
                m_TendencyStatusCritical.Remove( w );
                w.SetImage( 4 );
                break;
            case 7:                                                 //BLINKING_MINUS
                if ( !m_TendencyStatusCritical.Contains( w ) )
                {
                    m_TendencyStatusCritical.Insert( w, ARGB( alpha * 255, 30, 144, 220 ) );
                }
                w.SetImage( 4 );
                break;
            default:
                w.SetColor( ARGB( alpha * 255, 220, 220, 220 ) );   //DEFAULT
                m_TendencyStatusCritical.Remove( w );
                w.SetImage( 2 );
                break;
        }
    }
References ARGB(), m_Notifiers, and String().
Referenced by DisplayNotifier().
GetHudPanelWidget()
Widget Hud::GetHudPanelWidget () inline private
Definition at line 1183 of file ingamehud.c.
    {
        return m_HudPanelWidget;
    }
References m_HudPanelWidget.
GetHudState()
bool Hud::GetHudState () inline private
Definition at line 1132 of file ingamehud.c.
    {
        return m_HudState;
    }
References m_HudState.
GetQuickbar()
InventoryQuickbar Hud::GetQuickbar () inline private
Definition at line 1017 of file ingamehud.c.
    {
        return m_Quickbar;
    }
References m_Quickbar.
GetQuickBarState()
bool Hud::GetQuickBarState () inline private
Definition at line 1127 of file ingamehud.c.
    {
        return m_QuickbarState;
    }
References m_QuickbarState.
HideCursor() [1/2]
void Hud::HideCursor () inline private
Definition at line 625 of file gameplay.c.
{ }
HideCursor() [2/2]
override void Hud::HideCursor () inline private
Definition at line 416 of file ingamehud.c.
    {
        m_CursorWidget.Show( false );
    }
HideQuickbarTimer()
void Hud::HideQuickbarTimer () inline private
Definition at line 1419 of file ingamehud.c.
    {
    }
HideTemperature()
void Hud::HideTemperature () inline private
Definition at line 631 of file ingamehud.c.
    {
        m_IsTemperatureVisible = false;
        TextWidget temp_top = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueTop" ) );
        TextWidget temp_bot = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueBottom" ) );
        temp_top.SetText( "" );
        temp_bot.SetText( "" );
        m_TemperatureTimer = 0;
    }
References m_Notifiers.
Referenced by Update().
HideVehicleInfo() [1/2]
void Hud::HideVehicleInfo () private
Referenced by MissionBase::HideVehicleInfo(), and ManBase::OnVehicleSeatDriverLeft().
HideVehicleInfo() [2/2]
override void Hud::HideVehicleInfo () inline private
Definition at line 837 of file ingamehud.c.
    {
        m_HudPanelWidget.FindAnyWidget("PlayerPanel").Show(true);
        m_Presence.Show(true);
        m_StancePanel.Show(true);
        m_VehiclePanel.Show(false);
        m_InVehicleAsDriver = false;
        m_CurrentVehicle    = null;
        m_VehicleGearCount  = -1;
    }
IngameHud()
void Hud::IngameHud () inline private
Definition at line 150 of file ingamehud.c.
    {
        m_FadeTimerCrosshair            = new WidgetFadeTimer;
        m_FadeTimerActionCursor         = new WidgetFadeTimer;
        m_FadeTimerQuickbar         = new WidgetFadeTimer;
        m_FadeTimerWalkieTalkie     = new WidgetFadeTimer;
        m_FadeTimerWalkieTalkieText = new WidgetFadeTimer;
        m_StatesWidgets                 = new map<int, ImageWidget>; // [key] widgetName
        m_StatesWidgetNames             = new map<int, string>;
        m_TendencyStatusCritical        = new map<ImageWidget, int>;
        m_BadgesWidgets                 = new map<int, ImageWidget>; // [key] widgetName
        m_BadgesWidgetNames             = new map<int, string>;
        m_BadgesWidgetDisplay           = new map<int, int>;
        m_VehicleDamageZonesHitTimer    = 0;
        m_VehicleGearTable              = new map<int, string>;
        m_VehicleGearTable.Set(-1, "");
        m_VehicleGearTable.Set(CarGear.REVERSE, "R");
        m_VehicleGearTable.Set(CarGear.NEUTRAL, "N");
        m_VehicleGearTable.Set(CarGear.FIRST, "1");
        m_VehicleGearTable.Set(CarGear.SECOND, "2");
        m_VehicleGearTable.Set(CarGear.THIRD, "3");
        m_VehicleGearTable.Set(CarGear.FOURTH, "4");
        m_VehicleGearTable.Set(CarGear.FIFTH, "5");
        m_VehicleGearTable.Set(CarGear.SIXTH, "6");
        m_VehicleGearTable.Set(CarGear.SEVENTH, "7");
        m_VehicleGearTable.Set(CarGear.EIGTH, "8");
        m_VehicleGearTableAuto          = new map<int, string>;
        m_VehicleGearTableAuto.Set(-1, "");
        m_VehicleGearTableAuto.Set(CarAutomaticGearboxMode.R, "R");
        m_VehicleGearTableAuto.Set(CarAutomaticGearboxMode.N, "N");
        m_VehicleGearTableAuto.Set(CarAutomaticGearboxMode.D, "D");
    }
Init() [1/2]
void Hud::Init (Widget hud_panel_widget) inline private
Definition at line 618 of file gameplay.c.
{}
Referenced by MissionBase::OnInit().
Init() [2/2]
override void Hud::Init (Widget hud_panel_widget) inline private
gets scripted handler from widget
Definition at line 189 of file ingamehud.c.
    {
        m_HudPanelWidget = hud_panel_widget;
        m_HudPanelWidget.Show( true );
        //Quickbar
        m_QuickbarWidget        = m_HudPanelWidget.FindAnyWidget("QuickbarGrid");
        m_QuickbarWidget.Show( false );
        //Left HUD Panel
        m_LeftHudPanelWidget    = m_HudPanelWidget.FindAnyWidget("LeftHUDPanel");
        //TEMPORARY HACK!!! player is not present when Hud is being initialized
        myTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
        myTimer.Run( 1, this, "InitQuickbar" );
        m_CursorWidget = m_HudPanelWidget.FindAnyWidget("CursorIcons");
        m_CursorWidget.Show(true);
        Class.CastTo(m_CursorIcon, m_HudPanelWidget.FindAnyWidget("Cursor"));
        //Permanent Crosshair
        Class.CastTo(m_PermanentCrossHair, m_HudPanelWidget.FindAnyWidget("PermanentCrossHair"));
        m_WalkieTalkie = m_HudPanelWidget.FindAnyWidget("WalkieTalkie");
        //Panels
        Class.CastTo(m_Stamina, m_HudPanelWidget.FindAnyWidget("StaminaBar"));
        m_Presence                      = m_HudPanelWidget.FindAnyWidget("PresencePanel");
        m_Badges                        = hud_panel_widget.FindAnyWidget("BadgesPanel");
        m_Notifiers                     = m_HudPanelWidget.FindAnyWidget("NotifiersPanel");
        m_SpecializatonPanel            = m_HudPanelWidget.FindAnyWidget("SpecializationPanel");
        m_SpecializationIcon            = m_HudPanelWidget.FindAnyWidget("SpecializationIcon");
        m_BadgeNotifierDivider          = m_HudPanelWidget.FindAnyWidget("BadgeNotifierDivider");
        m_BloodType                     = TextWidget.Cast( m_HudPanelWidget.FindAnyWidget("BloodType") );
        m_BloodPosType                  = TextWidget.Cast( m_HudPanelWidget.FindAnyWidget("BloodPosType") );
        m_VehiclePanel                  = m_HudPanelWidget.FindAnyWidget("VehiclePanel");
        m_VehiclePanel.Show(false);
        m_VehicleRPMPointer             = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("RPMPointer") );
        m_VehicleRPMDial                = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("RPMDial") );
        m_VehicleRPMRedline             = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("RPMDialRedline") );
        m_VehicleSpeedPointer           = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("SpeedPointer") );
        m_VehicleSpeedValue             = TextWidget.Cast( m_VehiclePanel.FindAnyWidget("SpeedValue") );
        m_VehicleCurrentGearValue       = TextWidget.Cast( m_VehiclePanel.FindAnyWidget("Current") );
        m_VehicleNextGearValue          = TextWidget.Cast( m_VehiclePanel.FindAnyWidget("Next") );
        m_VehiclePrevGearValue          = TextWidget.Cast( m_VehiclePanel.FindAnyWidget("Prev") );
        m_VehicleBatteryLight           = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("BatteryLight"));
        m_VehicleEngineLight            = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("EngineLight"));
        m_VehicleOilLight               = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("OilLight"));
        m_VehicleHandBrakeLight         = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("HandBrakeLight"));
        m_VehicleWheelLight             = ImageWidget.Cast( m_VehiclePanel.FindAnyWidget("WheelLight"));
        m_VehicleTemperatureIndicator   = m_VehiclePanel.FindAnyWidget("TemperatureIndicator");
        m_VehicleTemperaturePointer     = ImageWidget.Cast(m_VehiclePanel.FindAnyWidget("TemperaturePointer"));
        m_VehicleTemperatureLight       = ImageWidget.Cast(m_VehiclePanel.FindAnyWidget("TemperatureLight"));
        m_VehicleFuelPointer            = ImageWidget.Cast(m_VehiclePanel.FindAnyWidget("FuelPointer"));
        m_VehicleFuelLight              = ImageWidget.Cast(m_VehiclePanel.FindAnyWidget("FuelLight"));
        m_StaminaBackground             = m_HudPanelWidget.FindAnyWidget("StaminaBackground");
        m_StaminaBackground.Show(true);
        m_StanceProne                   = m_HudPanelWidget.FindAnyWidget("StanceProne");
        m_StanceCrouch                  = m_HudPanelWidget.FindAnyWidget("StanceCrouch");
        m_StanceStand                   = m_HudPanelWidget.FindAnyWidget("StanceStand");
        m_StanceStandWalk               = m_HudPanelWidget.FindAnyWidget("StanceStandWalk");
        m_StanceCar                     = m_HudPanelWidget.FindAnyWidget("StanceCar");
        m_StancePanel                   = m_HudPanelWidget.FindAnyWidget("StancePanel");
        m_ActionTarget                  = m_HudPanelWidget.FindAnyWidget("ActionTargetsCursorWidget");
        m_ActionTarget.GetScript(m_ActionTargetsCursor);
        // heat buffer plus sign
        m_HeatBufferPlus = ImageWidget.Cast( m_HudPanelWidget.FindAnyWidget( "HeatBuffer" ) );
        if ( m_HeatBufferPlus )
            m_HeatBufferPlus.Show( false );
        #ifndef NO_GUI
        m_Timer = new Timer( CALL_CATEGORY_GAMEPLAY );
        m_Timer.Run(0.333, this, "RefreshQuickbar", NULL, true );
        #endif
        InitBadgesAndNotifiers();
        m_PresenceLevel0 = hud_panel_widget.FindAnyWidget("Presence0");
        m_PresenceLevel1 = hud_panel_widget.FindAnyWidget("Presence1");
        m_PresenceLevel2 = hud_panel_widget.FindAnyWidget("Presence2");
        m_PresenceLevel3 = hud_panel_widget.FindAnyWidget("Presence3");
        m_PresenceLevel4 = hud_panel_widget.FindAnyWidget("Presence4");
        m_PresenceLevel0.Show( false );
        m_PresenceLevel1.Show( false );
        m_PresenceLevel2.Show( false );
        m_PresenceLevel3.Show( false );
        m_PresenceLevel4.Show( false );
        SetLeftStatsVisibility( true );
        m_HudState = g_Game.GetProfileOption( EDayZProfilesOptions.HUD );
        //ShowQuickBar(GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer() && g_Game.GetProfileOption(EDayZProfilesOptions.QUICKBAR)); //unreliable
    }
References CALL_CATEGORY_GAMEPLAY, Class::CastTo(), g_Game, InitBadgesAndNotifiers(), m_BloodType, m_Notifiers, m_QuickbarWidget, m_SpecializationIcon, m_Stamina, m_Timer, and SetLeftStatsVisibility().
InitBadgesAndNotifiers()
void Hud::InitBadgesAndNotifiers () inline private
Definition at line 290 of file ingamehud.c.
    {
        // state notifiers
        m_StatesWidgetNames.Clear();
        m_StatesWidgets.Clear();
        m_StatesWidgetNames.Set( NTFKEY_THIRSTY, "Thirsty" );
        m_StatesWidgetNames.Set( NTFKEY_HUNGRY, "Hungry" );
        m_StatesWidgetNames.Set( NTFKEY_SICK, "Health" );
        m_StatesWidgetNames.Set( NTFKEY_BLEEDISH, "Blood" );
        m_StatesWidgetNames.Set( NTFKEY_FEVERISH, "Temperature" );
        m_Notifiers.Show( true );
        m_Badges.Show( true );
        int i = 0;
        int key = 0;
        for ( i = 0; i < m_StatesWidgetNames.Count(); i++ )
        {
            string widget_name = m_StatesWidgetNames.GetElement(i);
            key = m_StatesWidgetNames.GetKey(i);
            ImageWidget w;
            Class.CastTo(w,  m_Notifiers.FindAnyWidget( String( "Icon" + widget_name ) ) );
            m_StatesWidgets.Set( key, w );
            w.Show( true );
            for ( int y = 0; y < 5; y++ )
            {
                w.LoadImageFile( y, "set:dayz_gui image:icon" + widget_name + y );
            }
            w.SetImage( 0 );
            float alpha = w.GetAlpha();
            w.SetColor( ARGB( alpha * 255, 220, 220, 220 ) );   //white
            m_TendencyStatusCritical.Remove( w );
            // clear all arrows
            for ( int x = 1; x < 4; x++ )
            {
                Class.CastTo(w,  m_Notifiers.FindAnyWidget( String( widget_name + "ArrowUp" + x.ToString() ) ) );
                w.Show( false );
                Class.CastTo(w,  m_Notifiers.FindAnyWidget( String( widget_name + "ArrowDown" + x.ToString() ) ) );
                w.Show( false );
            }
        }
        // badges
        m_BadgesWidgetNames.Clear();
        m_BadgesWidgets.Clear();
        m_BadgesWidgetDisplay.Clear();
        m_BadgesWidgetNames.Set( NTFKEY_FRACTURE, "Fracture" );
        m_BadgesWidgetNames.Set( NTFKEY_STUFFED, "Stomach" );
        m_BadgesWidgetNames.Set( NTFKEY_SICK, "Sick" );
        m_BadgesWidgetNames.Set( NTFKEY_WETNESS, "Wetness" );
        m_BadgesWidgetNames.Set( NTFKEY_POISONED, "Poisoned" );
        m_BadgesWidgetNames.Set( NTFKEY_BLEEDISH, "Bleeding" );
        m_BadgesWidgetNames.Set( NTFKEY_LIVES, "Shock" );
        m_BadgesWidgetNames.Set( NTFKEY_PILLS, "Pills" );
        for ( i = 0; i < m_BadgesWidgetNames.Count(); i++ )
        {
            string badge_name = m_BadgesWidgetNames.GetElement(  i);
            key = m_BadgesWidgetNames.GetKey( i );
            ImageWidget badge_widget;
            Class.CastTo(badge_widget,  m_Badges.FindAnyWidget( badge_name ) );
            m_BadgesWidgets.Set( key, badge_widget );
            badge_widget.Show( false );
            m_BadgesWidgetDisplay.Set( key, false );
        }
        m_AnyBadgeVisible = false;
        m_BadgeNotifierDivider.Show(false);
    }
References ARGB(), Class::CastTo(), m_Notifiers, NTFKEY_BLEEDISH, NTFKEY_FEVERISH, NTFKEY_FRACTURE, NTFKEY_HUNGRY, NTFKEY_LIVES, NTFKEY_PILLS, NTFKEY_POISONED, NTFKEY_SICK, NTFKEY_STUFFED, NTFKEY_THIRSTY, NTFKEY_WETNESS, String(), x, and y.
Referenced by Init().
InitQuickbar()
void Hud::InitQuickbar () inline private
Definition at line 1009 of file ingamehud.c.
    {
        if (m_Quickbar == NULL)
        {
            m_Quickbar = new InventoryQuickbar( m_QuickbarWidget );
        }
    }
References m_Quickbar, and m_QuickbarWidget.
IsHideHudPlayer()
bool Hud::IsHideHudPlayer () inline private
Definition at line 1065 of file ingamehud.c.
    {
        return m_HudHidePlayer;
    }
References m_HudHidePlayer.
Referenced by MissionBase::OnUpdate(), and ScriptedWidgetEventHandler::Update().
IsHideQuickbarPlayer()
bool Hud::IsHideQuickbarPlayer () inline private
Definition at line 1060 of file ingamehud.c.
    {
        return m_QuickbarHidePlayer;
    }
References m_QuickbarHidePlayer.
Referenced by MissionBase::OnUpdate().
IsHudVisible()
bool Hud::IsHudVisible () inline private
Definition at line 1027 of file ingamehud.c.
    {
        return m_IsHudVisible;
    }
References m_IsHudVisible.
Referenced by ScriptedWidgetEventHandler::Update().
IsQuickbarVisible()
bool Hud::IsQuickbarVisible () inline private
Definition at line 1022 of file ingamehud.c.
    {
        return m_IsQuickbarVisible;
    }
References m_IsQuickbarVisible.
KeyPress()
bool Hud::KeyPress (int key) inline private
Definition at line 715 of file ingamehud.c.
    {
        return false;
    }
Referenced by MissionBase::OnKeyPress().
OnResizeScreen() [1/2]
void Hud::OnResizeScreen () private
Referenced by MissionBase::OnEvent().
OnResizeScreen() [2/2]
override void Hud::OnResizeScreen () inline private
Definition at line 363 of file ingamehud.c.
    {
        float x, y;
        m_HudPanelWidget.GetScreenSize( x, y );
        m_HudPanelWidget.Update();
        m_Badges.Update();
        m_Notifiers.SetPos( 0, 0 );
    }
References m_Notifiers, x, and y.
RefreshHudVisibility()
void Hud::RefreshHudVisibility () inline private
Definition at line 1038 of file ingamehud.c.
    {
        m_IsHudVisible = ( !m_HudHidePlayer && !m_HudHideUI && m_HudState ) || m_HudInventory;
        SetLeftStatsVisibility( m_IsHudVisible );
        m_Badges.Show( m_IsHudVisible );
        m_Notifiers.Show( m_IsHudVisible );
        m_BadgeNotifierDivider.Show( m_IsHudVisible && m_AnyBadgeVisible );
        #ifdef PLATFORM_CONSOLE
        m_SpecializatonPanel.Show(m_HudInventory);
        #else
        m_SpecializatonPanel.Show(false);
        #endif
    }
References m_HudState, m_Notifiers, and SetLeftStatsVisibility().
Referenced by DisplayBadge(), ShowHud(), ShowHudInventory(), ShowHudPlayer(), and ShowHudUI().
RefreshPlayerTags()
void Hud::RefreshPlayerTags () inline private
Definition at line 1216 of file ingamehud.c.
    {
        if( GetGame().GetPlayer() )
        {
            bool found = false;
            vector head_pos = GetGame().GetCurrentCameraPosition();
            float distance;
            foreach( Man player : ClientData.m_PlayerBaseList )
            {
                vector target_player = player.GetPosition();
                distance = vector.Distance( head_pos, target_player );
                target_player[1] = target_player[1] + 1.2;
                if( distance <= 15 && player != GetGame().GetPlayer() )
                {
                    vector screen_pos = GetGame().GetScreenPosRelative( target_player );
                    vector end_pos = head_pos + GetGame().GetCurrentCameraDirection() * 25;
                    RaycastRVParams params = new RaycastRVParams( head_pos, end_pos, GetGame().GetPlayer(), 0 );
                    params.sorted = true;
                    array<ref RaycastRVResult> results = new array<ref RaycastRVResult>;
                    DayZPhysics.RaycastRVProxy( params, results );
                    if( results.Count() > 0 )
                    {
                        if( results.Get( 0 ).obj == player )
{
                            m_CurrentTaggedPlayer = PlayerBase.Cast( player );
                            found = true;
                        }
                    }
                }
            }
            if( !found )
            {
                m_CurrentTaggedPlayer = null;
            }
        }
    }
References vector::Distance(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetPlayer(), CGame::GetScreenPosRelative(), ClientData::m_PlayerBaseList, array::obj, DayZPhysics::RaycastRVProxy(), and RaycastRVParams::sorted.
Referenced by Update().
RefreshQuickbar() [1/2]
void Hud::RefreshQuickbar (bool itemChanged = false) inline private
Definition at line 633 of file gameplay.c.
{}
RefreshQuickbar() [2/2]
override void Hud::RefreshQuickbar (bool itemChanged = false) inline private
Definition at line 1154 of file ingamehud.c.
    {
        if ((!m_QuickbarState || m_QuickbarHidePlayer || m_QuickbarHideUI) && !itemChanged) // Don't update when it is hidden or disabled
            return;
        if ( itemChanged )
        {
            UIManager manager = GetGame().GetUIManager();
            InventoryMenu inventory = InventoryMenu.Cast(manager.FindMenu( MENU_INVENTORY ));
            MissionGameplay mission = MissionGameplay.Cast(GetGame().GetMission());
            if ( mission )
            {
                inventory = mission.GetInventory();
            }
            if ( inventory )
            {
                inventory.RefreshQuickbar();
            }
        }
        if ( m_Quickbar )
        {
            m_Quickbar.UpdateItems( m_QuickbarWidget );
        }
    }
References UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), InventoryMenu(), m_Quickbar, m_QuickbarWidget, MENU_INVENTORY, and mission.
RefreshQuickbarVisibility()
void Hud::RefreshQuickbarVisibility () inline private
Definition at line 1032 of file ingamehud.c.
    {
        m_IsQuickbarVisible = !m_QuickbarHideUI && !m_QuickbarHidePlayer && m_QuickbarState;
        m_QuickbarWidget.Show( m_IsQuickbarVisible );
    }
References m_QuickbarState, and m_QuickbarWidget.
Referenced by ShowQuickBar(), ShowQuickbarPlayer(), and ShowQuickbarUI().
RefreshVehicleHud()
void Hud::RefreshVehicleHud (float timeslice) inline private
engine
fuel tank
temperature
general hit timer reset
Definition at line 849 of file ingamehud.c.
    {
        if (m_CurrentVehicle && !GetGame().GetUIManager().GetMenu())
        {
            m_VehiclePanel.Show(true);
            float rpm_value     = m_CurrentVehicle.EngineGetRPM() / m_CurrentVehicle.EngineGetRPMMax();
            float rpm_value_red = m_CurrentVehicle.EngineGetRPMRedline() / m_CurrentVehicle.EngineGetRPMMax();
            float speed_value   = m_CurrentVehicle.GetSpeedometerAbsolute() / 200;
            m_VehicleRPMPointer.SetRotation(0, 0, rpm_value * 270 - 130, true);
            m_VehicleSpeedPointer.SetRotation(0, 0, speed_value * 260 - 130, true);
            m_VehicleSpeedValue.SetText(Math.AbsInt(m_CurrentVehicle.GetSpeedometer()).ToString());
            int engineHealthLevel   = m_CurrentVehicle.GetHealthLevel("Engine");
            int fuelTankHealthLevel = m_CurrentVehicle.GetHealthLevel("FuelTank");
            bool newHealth          = false;
            if (m_CurrentVehicle.HasEngineZoneReceivedHit())
            {
                if (m_TimeSinceLastEngineLightChange > 0.35)
                {
                    m_VehicleEngineLight.Show(!m_VehicleEngineLight.IsVisible());
                    if (engineHealthLevel <= GameConstants.STATE_WORN)
                    {
                        m_VehicleEngineLight.SetColor(Colors.WHITE);
                    }
                    else
                    {
                        m_VehicleEngineLight.SetColor(ItemManager.GetItemHealthColor(engineHealthLevel));
                    }
                    m_VehicleEngineLight.SetAlpha(1);
                    m_TimeSinceLastEngineLightChange = 0;
                }
                m_TimeSinceLastEngineLightChange += timeslice;
                newHealth = true;
            }
            else if (engineHealthLevel > GameConstants.STATE_WORN)
            {
                m_VehicleEngineLight.SetColor(ItemManager.GetItemHealthColor(engineHealthLevel));
                m_VehicleEngineLight.SetAlpha(1);
                m_VehicleEngineLight.Show(true);
            }
            else
            {
                m_VehicleEngineLight.Show(false);
            }
            if (fuelTankHealthLevel <= GameConstants.STATE_WORN)
            {
                m_VehicleFuelLight.SetColor(Colors.WHITE);
                m_VehicleFuelLight.SetAlpha(1);
                m_VehicleFuelLight.Show(true);
            }
            else if (fuelTankHealthLevel > GameConstants.STATE_WORN)
            {
                m_VehicleFuelLight.SetColor(ItemManager.GetItemHealthColor(fuelTankHealthLevel));
                m_VehicleFuelLight.SetAlpha(1);
                m_VehicleFuelLight.Show(true);
            }
            if (m_CurrentVehicle.IsVitalRadiator())
            {
                m_VehicleTemperatureIndicator.Show(true);
                if (m_CurrentVehicle.HasRadiator())
                {
                    int radiatorHealthLevel = m_CurrentVehicle.GetRadiator().GetHealthLevel("");
                    if (radiatorHealthLevel <= GameConstants.STATE_WORN)
                    {
                        m_VehicleTemperatureLight.SetColor(Colors.WHITE);
                        m_VehicleTemperatureLight.SetAlpha(1);
                        m_VehicleTemperatureLight.Show(true);
                    }
                    else if (radiatorHealthLevel > GameConstants.STATE_WORN)
                    {
                        m_VehicleTemperatureLight.SetColor(ItemManager.GetItemHealthColor(radiatorHealthLevel));
                        m_VehicleTemperatureLight.SetAlpha(1);
                        m_VehicleTemperatureLight.Show(true);
                    }
                }
                else
                {
                    m_VehicleTemperatureLight.SetColor(Colors.COLOR_RUINED);
                    m_VehicleTemperatureLight.SetAlpha(1);
                    m_VehicleTemperatureLight.Show(true);
                }
            }
            else
            {
                m_VehicleTemperatureIndicator.Show(false);
            }
            m_VehicleHandBrakeLight.Show(m_CurrentVehicle.IsHandbrakeActive());
            m_VehicleWheelLight.Show(m_CurrentVehicle.WheelIsAnyLocked());
            int engagedGear = -1;
            int prevGear    = -1;
            int nextGear    = -1;
            if (m_CurrentVehicle.GearboxGetType() == CarGearboxType.MANUAL)
            {
                engagedGear = m_CurrentVehicle.GetGear();
                prevGear = engagedGear - 1;
                nextGear = engagedGear + 1;
                if (engagedGear == CarGear.NEUTRAL)
                {
                    prevGear = CarGear.REVERSE;
                }
                else if (engagedGear == CarGear.REVERSE)
                {
                    prevGear = -1;
                    nextGear = CarGear.NEUTRAL;
                }
                m_VehicleCurrentGearValue.SetText(m_VehicleGearTable.Get(engagedGear));
                m_VehicleNextGearValue.Show(nextGear < m_VehicleGearCount);
                m_VehicleNextGearValue.SetText(m_VehicleGearTable.Get(nextGear));
                m_VehiclePrevGearValue.SetText(m_VehicleGearTable.Get(prevGear));
            }
            else
            {
                engagedGear = m_CurrentVehicle.GearboxGetMode();
                prevGear = engagedGear - 1;
                nextGear = engagedGear + 1;
                m_VehicleCurrentGearValue.SetText(m_VehicleGearTableAuto.Get(engagedGear));
                m_VehicleNextGearValue.Show(nextGear < EnumTools.GetEnumSize(CarAutomaticGearboxMode));
                m_VehicleNextGearValue.SetText(m_VehicleGearTableAuto.Get(nextGear));
                m_VehiclePrevGearValue.SetText(m_VehicleGearTableAuto.Get(prevGear));
            }
            // refresh backlit
            GetDayZGame().GetBacklit().RefreshVehicleLayout(engagedGear, newHealth);
            m_VehicleFuelPointer.SetRotation( 0, 0, m_CurrentVehicle.GetFluidFraction( CarFluid.FUEL ) * 260 - 130, true );
            m_VehicleTemperaturePointer.SetRotation( 0, 0, -1 * m_CurrentVehicle.GetFluidFraction( CarFluid.COOLANT ) * 260 + 130, true );
            if (m_VehicleDamageZonesHitTimer > 1)
            {
                m_VehicleDamageZoneHitEngineState = false;
                m_VehicleDamageZonesHitTimer = 0;
            }
            m_VehicleDamageZonesHitTimer += timeslice;
        }
        else
        {
            m_VehiclePanel.Show(false);
        }
    }
References Math::AbsInt(), Colors::COLOR_RUINED, GetDayZGame(), EnumTools::GetEnumSize(), GetGame(), ItemManager::GetItemHealthColor(), CarScript::IsVitalRadiator(), GameConstants::STATE_WORN, and Colors::WHITE.
Referenced by Update().
SetCursorIcon() [1/2]
void Hud::SetCursorIcon (string icon) inline private
Definition at line 626 of file gameplay.c.
{ }
SetCursorIcon() [2/2]
override void Hud::SetCursorIcon (string icon) inline private
Definition at line 400 of file ingamehud.c.
    {
        if ( icon.Length() == 0 || icon == CursorIcons.None )
            m_CursorIcon.Show(false);
        else
        {
            m_CursorIcon.LoadImageFile( 0, icon );
            m_CursorIcon.Show(true);
        }
    }
References string::Length(), and CursorIcons::None.
SetCursorIconOffset() [1/2]
void Hud::SetCursorIconOffset (string type, float x, float y) inline private
Definition at line 628 of file gameplay.c.
{ }
SetCursorIconOffset() [2/2]
override void Hud::SetCursorIconOffset (string type, float x, float y) inline private
Definition at line 428 of file ingamehud.c.
    {
        m_CursorIcon.FindAnyWidget( type ).GetParent().SetPos( x, y );
    }
References x, and y.
SetCursorIconScale() [1/2]
void Hud::SetCursorIconScale (string type, float percentage) inline private
Definition at line 627 of file gameplay.c.
{ }
SetCursorIconScale() [2/2]
override void Hud::SetCursorIconScale (string type, float percentage) inline private
Definition at line 421 of file ingamehud.c.
    {
        float x, y;
        m_CursorIcon.FindAnyWidget( type ).GetParent().GetSize( x, y );
        m_CursorIcon.FindAnyWidget( type ).GetParent().SetSize( x * percentage, y * percentage );
    }
References Icon::SetSize(), x, and y.
SetCursorIconSize() [1/2]
void Hud::SetCursorIconSize (string type, float x, float y) inline private
Definition at line 629 of file gameplay.c.
{   }
SetCursorIconSize() [2/2]
override void Hud::SetCursorIconSize (string type, float x, float y) inline private
Definition at line 433 of file ingamehud.c.
    {
        m_CursorIcon.FindAnyWidget( type ).GetParent().SetSize( x, y );
    }
References x, and y.
SetLeftStatsVisibility()
void Hud::SetLeftStatsVisibility (bool visible) inline private
eg. stamina bar...
Definition at line 1138 of file ingamehud.c.
    {
        Widget child = m_LeftHudPanelWidget.GetChildren();
        while (child)
        {
            if (child.GetName() == "ChatFrameWidget")
            {
                child = child.GetSibling();
                continue
            }
            child.Show(visible);
            child = child.GetSibling();
        }
    }
Referenced by Init(), and RefreshHudVisibility().
SetPermanentCrossHair()
void Hud::SetPermanentCrossHair (bool show) inline private
Definition at line 653 of file gameplay.c.
{}
Referenced by PluginBase::SwitchPermanentCrossHair().
SetStamina() [1/2]
void Hud::SetStamina (int value, int range) inline private
Definition at line 621 of file gameplay.c.
{}
Referenced by PluginBase::SetStamina().
SetStamina() [2/2]
override void Hud::SetStamina (int value, int range) inline private
Definition at line 669 of file ingamehud.c.
    {
        float sx, sy;
        float max = CfgGameplayHandler.GetStaminaMax();
        float percentage = 1;
        if (max != 0)
        {
            percentage =  range / max;
        }
        if (range != 0)
        {
            m_Stamina.SetCurrent(( value / range ) * 100);
        }
        else
        {
            m_Stamina.SetCurrent(0);
        }
        m_Stamina.GetSize(sx, sy);
        m_Stamina.SetSize(percentage, sy);
        m_StaminaBackground.SetSize(1 - percentage, sy);
        // set health & blood values
        if (!GetGame().IsMultiplayer())
        {
            if (GetGame().GetPlayer())
            {
                PlayerBase player;
                Class.CastTo(player, GetGame().GetPlayer());
                if (player)
                {
                    float h1 = player.GetHealth("","");
                    float b1 = player.GetHealth("","Blood");
                    GetDayZGame().GetBacklit().SetHealth(h1);
                    GetDayZGame().GetBacklit().SetBlood(b1);
                }
            }
        }
        // update backlit
        GetDayZGame().GetBacklit().UpdatePlayer(false);
    }
References Class::CastTo(), GetDayZGame(), GetGame(), GetPlayer(), CfgGameplayHandler::GetStaminaMax(), and m_Stamina.
SetStaminaBarVisibility() [1/2]
void Hud::SetStaminaBarVisibility (bool show) private
Referenced by ManBase::StaminaHUDNotifier(), and Update().
SetStaminaBarVisibility() [2/2]
override void Hud::SetStaminaBarVisibility (bool show) inline private
Definition at line 641 of file ingamehud.c.
    {
        //m_StaminaBackground.Show( show );
        //m_Stamina.Show( show );
        if ( show )
        {
            m_Stamina.SetAlpha(1);
            //m_Stamina.SetTextColor( ColorManager.COLOR_NORMAL_TEXT );
        }
        else
        {
            m_Stamina.SetAlpha(0.3);
            //m_Stamina.SetTextColor( ColorManager.RED_COLOR );
        }
        m_IsStaminaVisible = show;
        m_StaminaTimer = 0;
    }
References m_Stamina.
SetStomachState()
void Hud::SetStomachState (int state) inline private
Definition at line 663 of file ingamehud.c.
    {
        ImageWidget stomach = ImageWidget.Cast( m_Badges.FindAnyWidget( "Stomach" ) );
        stomach.LoadImageFile( 0, "set:dayz_gui image:iconStomach" + state );
    }
SetTemperature() [1/2]
void Hud::SetTemperature (string temp) private
Referenced by ManBase::OnRPC().
SetTemperature() [2/2]
override void Hud::SetTemperature (string temp) inline private
Definition at line 621 of file ingamehud.c.
    {
        m_IsTemperatureVisible = true;
        TextWidget temp_top = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueTop" ) );
        TextWidget temp_bot = TextWidget.Cast( m_Notifiers.FindAnyWidget( "TemperatureValueBottom" ) );
        temp_top.SetText( temp );
        temp_bot.SetText( temp );
        m_TemperatureTimer = 0;
    }
References m_Notifiers.
SetWalkieTalkieText() [1/2]
void Hud::SetWalkieTalkieText (string text) inline private
Definition at line 632 of file gameplay.c.
{ }
SetWalkieTalkieText() [2/2]
override void Hud::SetWalkieTalkieText (string text) inline private
Definition at line 393 of file ingamehud.c.
    {
        TextWidget txt;
        Class.CastTo(txt, m_WalkieTalkie.FindAnyWidget("Text"));
        txt.SetText(text);
    }
References Class::CastTo().
Show() [1/2]
void Hud::Show (bool show) inline private
Definition at line 634 of file gameplay.c.
{}
Show() [2/2]
override void Hud::Show (bool show) inline private
Definition at line 372 of file ingamehud.c.
    {
        m_HudPanelWidget.Show( show );
    }
ShowCursor() [1/2]
void Hud::ShowCursor () inline private
Definition at line 624 of file gameplay.c.
{ }
ShowCursor() [2/2]
override void Hud::ShowCursor () inline private
Definition at line 411 of file ingamehud.c.
    {
        m_CursorWidget.Show( true );
    }
ShowHud() [1/2]
void Hud::ShowHud (bool show) private
ShowHud() [2/2]
override void Hud::ShowHud (bool show) inline private
Definition at line 1120 of file ingamehud.c.
    {
        m_HudState = show;
        m_HudHidePlayer = false;
        RefreshHudVisibility();
    }
References RefreshHudVisibility().
ShowHudInventory() [1/2]
void Hud::ShowHudInventory (bool show) private
ShowHudInventory() [2/2]
override void Hud::ShowHudInventory (bool show) inline private
Definition at line 1100 of file ingamehud.c.
    {
        m_HudInventory = show;
        RefreshHudVisibility();
    }
References RefreshHudVisibility().
ShowHudPlayer() [1/2]
void Hud::ShowHudPlayer (bool show) private
Referenced by ManBase::CloseMapEx(), MissionBase::OnUpdate(), UIScriptedMenu::ScriptConsole(), and UIScriptedMenu::~ScriptConsole().
ShowHudPlayer() [2/2]
override void Hud::ShowHudPlayer (bool show) inline private
Definition at line 1082 of file ingamehud.c.
    {
        m_HudHidePlayer = !show;
        if (m_HudState)
        {
            RefreshHudVisibility();
        }
    }
References RefreshHudVisibility().
ShowHudUI() [1/2]
void Hud::ShowHudUI (bool show) private
Referenced by UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), ManBase::OnPlayerLoaded(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), MissionBase::OnUpdate(), and UIScriptedMenu::~InspectMenuNew().
ShowHudUI() [2/2]
override void Hud::ShowHudUI (bool show) inline private
Definition at line 1091 of file ingamehud.c.
    {
        m_HudHideUI = !show;
        if (m_HudState)
        {
            RefreshHudVisibility();
        }
    }
References RefreshHudVisibility().
ShowPlayerTag()
void Hud::ShowPlayerTag (float timeslice) inline private
Definition at line 1261 of file ingamehud.c.
    {
        if( m_CurrentTaggedPlayer && m_CurrentTaggedPlayer.GetIdentity() )
        {
            if( !m_PlayerTag )
            {
                m_PlayerTag = GetGame().GetWorkspace().CreateWidgets("gui/layouts/new_ui/hud/hud_player_tag.layout");
                m_PlayerTagText = TextWidget.Cast( m_PlayerTag.FindAnyWidget( "TagText" ) );
                //m_PlayerTagText.SetText( m_CurrentTaggedPlayer.GetIdentity().GetName() );
            }
            m_PlayerSpineIndex = m_CurrentTaggedPlayer.GetBoneIndex( "Spine2" );
            vector player_pos = m_CurrentTaggedPlayer.GetBonePositionWS( m_PlayerSpineIndex );
            vector screen_pos = GetGame().GetScreenPosRelative( player_pos );
            if( screen_pos[2] > 0 )
            {
                if( screen_pos[0] > 0 && screen_pos[0] < 1 )
                {
                    if( screen_pos[1] > 0 && screen_pos[1] < 1 )
                    {
                        m_PlayerTagText.SetAlpha( Math.Clamp( m_PlayerTagText.GetAlpha() + timeslice * 10, 0, 1 ) );
                        m_PlayerTag.SetPos( 0.55, 0.55 );
                        m_PlayerTagText.SetText( m_CurrentTaggedPlayer.GetIdentity().GetName() );
                        //m_PlayerTagText.SetSize( 1, 1 - screen_pos[2] / 25  );
                        return;
                    }
                }
            }
        }
        if( m_PlayerTag )
        {
            float new_alpha = Math.Clamp( m_PlayerTagText.GetAlpha() - timeslice * 10, 0, 1 );
            m_PlayerTagText.SetAlpha( Math.Clamp( m_PlayerTagText.GetAlpha() - timeslice * 10, 0, 1 ) );
            if( new_alpha == 0 )
            {
                m_PlayerTagText.SetText( "" );
                m_CurrentTaggedPlayer = null;
            }
        }
    }
References Math::Clamp(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetScreenPosRelative(), and CGame::GetWorkspace().
Referenced by Update().
ShowQuickBar() [1/2]
void Hud::ShowQuickBar (bool show) private
Referenced by ManBase::OnPlayerLoaded().
ShowQuickBar() [2/2]
override void Hud::ShowQuickBar (bool show) inline private
global setting; is quickbar visibility allowed?
Definition at line 1112 of file ingamehud.c.
    {
        m_QuickbarState = show;
        //shown by default
        m_QuickbarHidePlayer = false;
        RefreshQuickbarVisibility();
    }
References RefreshQuickbarVisibility().
ShowQuickbarPlayer() [1/2]
void Hud::ShowQuickbarPlayer (bool show) private
Referenced by ManBase::CloseMapEx(), MissionBase::OnUpdate(), UIScriptedMenu::ScriptConsole(), and UIScriptedMenu::~ScriptConsole().
ShowQuickbarPlayer() [2/2]
override void Hud::ShowQuickbarPlayer (bool show) inline private
Definition at line 1076 of file ingamehud.c.
    {
        m_QuickbarHidePlayer = !show;
        RefreshQuickbarVisibility();
    }
References RefreshQuickbarVisibility().
ShowQuickbarUI() [1/2]
void Hud::ShowQuickbarUI (bool show) private
Referenced by UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), ManBase::OnPlayerLoaded(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), and UIScriptedMenu::~InspectMenuNew().
ShowQuickbarUI() [2/2]
override void Hud::ShowQuickbarUI (bool show) inline private
Definition at line 1070 of file ingamehud.c.
    {
        m_QuickbarHideUI = !show;
        RefreshQuickbarVisibility();
    }
References RefreshQuickbarVisibility().
ShowVehicleInfo() [1/2]
void Hud::ShowVehicleInfo () private
Referenced by ManBase::OnVehicleSeatDriverEnter(), and MissionBase::ShowVehicleInfo().
ShowVehicleInfo() [2/2]
override void Hud::ShowVehicleInfo () inline private
Definition at line 808 of file ingamehud.c.
    {
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if (player)
        {
            HumanCommandVehicle hcv = player.GetCommand_Vehicle();
            if (hcv)
            {
                m_CurrentVehicle = CarScript.Cast(hcv.GetTransport());
                if (m_CurrentVehicle)
                {
                    m_InVehicleAsDriver = true;
                    m_VehicleGearCount  = m_CurrentVehicle.GetGearsCount();
                    m_VehicleOilLight.Show(m_VehicleHasOil);
                    float rpm_value_red = m_CurrentVehicle.EngineGetRPMRedline() / m_CurrentVehicle.EngineGetRPMMax();
                    m_VehicleRPMDial.SetMaskProgress(rpm_value_red);
                    m_VehicleRPMRedline.SetMaskProgress(1 - rpm_value_red);
                    m_HudPanelWidget.FindAnyWidget("PlayerPanel").Show(false);
                    m_Presence.Show(false);
                    m_StancePanel.Show(false);
                    m_VehiclePanel.Show(true);
                }
            }
        }
    }
References GetGame(), GetPlayer(), and HumanCommandVehicle::GetTransport().
ShowWalkieTalkie() [1/4]
void Hud::ShowWalkieTalkie (bool show) inline private
Definition at line 630 of file gameplay.c.
{ }
ShowWalkieTalkie() [2/4]
override void Hud::ShowWalkieTalkie (bool show) inline private
Definition at line 377 of file ingamehud.c.
    {
        m_FadeTimerWalkieTalkie.Stop();
        m_FadeTimerWalkieTalkieText.Stop();
        m_WalkieTalkie.Show( show );
    }
ShowWalkieTalkie() [3/4]
void Hud::ShowWalkieTalkie (int fadeOutSeconds) inline private
Definition at line 631 of file gameplay.c.
{ }
ShowWalkieTalkie() [4/4]
override void Hud::ShowWalkieTalkie (int fadeOutSeconds) inline private
Definition at line 384 of file ingamehud.c.
    {
        m_WalkieTalkie.Show(true);
        m_FadeTimerWalkieTalkie.Stop();
        m_FadeTimerWalkieTalkieText.Stop();
        m_FadeTimerWalkieTalkie.FadeOut( m_WalkieTalkie.FindAnyWidget("Icon") , fadeOutSeconds );
        m_FadeTimerWalkieTalkieText.FadeOut( m_WalkieTalkie.FindAnyWidget("Text") , fadeOutSeconds );
    }
SpawnHitDirEffect() [1/2]
void Hud::SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max) private
Referenced by HandleDamageHit().
SpawnHitDirEffect() [2/2]
override void Hud::SpawnHitDirEffect (DayZPlayer player, float hit_direction, float intensity_max) inline private
Definition at line 1380 of file ingamehud.c.
    {
        if (HitDirectionEffectBase.m_Mode == HitDirectionModes.DISABLED)
        {
            return;
        }
        if (m_HitDirEffectArray == null)
        {
            m_HitDirEffectArray = new array<ref HitDirectionEffectBase>;
        }
        HitDirectionEffectBase hiteff = HitDirectionEffectBase.Cast(HitDirectionEffectBase.GetCurrentType().Spawn());
        hiteff.Init(player,hit_direction,intensity_max);
        m_HitDirEffectArray.Insert(hiteff);
    }
References HitDirectionEffectBase::GetCurrentType(), HitDirectionEffectBase::Init(), and HitDirectionEffectBase::m_Mode.
ToggleHeatBufferPlusSign() [1/2]
void Hud::ToggleHeatBufferPlusSign (bool show) private
Referenced by ManBase::EOnFrame().
ToggleHeatBufferPlusSign() [2/2]
override void Hud::ToggleHeatBufferPlusSign (bool show) inline private
Definition at line 1106 of file ingamehud.c.
    {
        m_HeatBufferPlus.Show( show );
    }
Update() [1/2]
void Hud::Update (float timeslice) inline private
Definition at line 638 of file gameplay.c.
{}
Referenced by ManBase::EOnFrame().
Update() [2/2]
override void Hud::Update (float timeslice) inline private
Definition at line 1304 of file ingamehud.c.
    {
        super.Update( timeslice );
        m_ActionTargetsCursor.Update();
        DisplayPresence();
        //
        //modifiers - tendency status (critical)
        if ( m_BlinkTime > TENDENCY_BLINK_TIME )
        {
            //get color & alpha
            if ( m_TendencyStatusCritical.Count() > 0 )
            {
                for ( int i = 0; i < m_TendencyStatusCritical.Count(); ++i )
                {
                    ImageWidget widget = m_TendencyStatusCritical.GetKey( i );
                    int alpha = widget.GetAlpha() * 255;
                    int color;
                    int colorA = ARGB( alpha, 255, 255, 255 );
                    int colorB = m_TendencyStatusCritical.Get( widget );
                    //set new color to different color
                    if ( widget.GetColor() == colorA )
                    {
                        color = colorB;
                    }
                    else
                    {
                        color = colorA;
                    }
                    widget.SetColor( color );
                }
            }
            m_BlinkTime = 0;    //reset
        }
        else
        {
            m_BlinkTime += timeslice;
        }
        if( m_IsTemperatureVisible )
        {
            m_TemperatureTimer += timeslice;
            if( m_TemperatureTimer > m_TemperatureShowTime )
            {
                HideTemperature();
            }
        }
        if ( !m_IsStaminaVisible )
        {
            m_StaminaTimer += timeslice;
            if ( m_StaminaTimer > m_StaminaShowTime )
            {
                SetStaminaBarVisibility( true );
            }
        }
        if ( m_HitDirEffectArray && m_HitDirEffectArray.Count() > 0 )
        {
            UpdateHitDirEffects(timeslice);
            CleanupHitDirEffects();
        }
        RefreshVehicleHud(timeslice);
        #ifdef PLATFORM_PS4
        RefreshPlayerTags();
        ShowPlayerTag(timeslice);
        #endif
    }
References ARGB(), CleanupHitDirEffects(), DisplayPresence(), HideTemperature(), RefreshPlayerTags(), RefreshVehicleHud(), SetStaminaBarVisibility(), ShowPlayerTag(), and UpdateHitDirEffects().
UpdateBloodName() [1/2]
void Hud::UpdateBloodName () inline private
Definition at line 635 of file gameplay.c.
{}
Referenced by ManBase::OnPlayerLoaded().
UpdateBloodName() [2/2]
override void Hud::UpdateBloodName () inline private
Definition at line 1188 of file ingamehud.c.
    {
        PlayerBase player;
        Class.CastTo(player, GetGame().GetPlayer() );
        if( player )
        {
            string blood_name;
            bool positive;
            BloodTypes.GetBloodTypeName( player.GetBloodType(), blood_name, positive );
            bool blood_type_visible = player.HasBloodTypeVisible();
            if( blood_type_visible )
            {
                m_BloodType.SetText( blood_name );
                if( positive )
                    m_BloodPosType.SetText( "+" );
                else
                    m_BloodPosType.SetText( "-" );
            }
            else
            {
                m_BloodType.SetText( "" );
                m_BloodPosType.SetText( "" );
            }
        }
    }
References Class::CastTo(), BloodTypes::GetBloodTypeName(), GetGame(), GetPlayer(), and m_BloodType.
UpdateHitDirEffects()
void Hud::UpdateHitDirEffects (float timeslice) inline private
Definition at line 1396 of file ingamehud.c.
    {
        for (int i = 0; i < m_HitDirEffectArray.Count(); i++)
        {
            m_HitDirEffectArray[i].Update(timeslice);
        }
    }
Referenced by Update().
UpdateSpecialtyMeter()
void Hud::UpdateSpecialtyMeter (float x, float y) inline private
Definition at line 1053 of file ingamehud.c.
    {
        #ifdef PLATFORM_CONSOLE
        m_SpecializationIcon.SetPos(x, y, true);
        #endif
    }
References m_SpecializationIcon, x, and y.
ZeroingKeyPress()
void Hud::ZeroingKeyPress () inline private
Definition at line 720 of file ingamehud.c.
    {
        m_ZeroingKeyPressed = true;
    }
Referenced by MissionBase::OnUpdate().
Member Data Documentation
FADE_IN_TIME
protected const float Hud::FADE_IN_TIME = 0.3 private
Definition at line 3 of file ingamehud.c.
FADE_OUT_TIME
protected const float Hud::FADE_OUT_TIME = 0.3 private
Definition at line 4 of file ingamehud.c.
HIDE_MENU_TIME
protected const float Hud::HIDE_MENU_TIME = 5 private
Definition at line 5 of file ingamehud.c.
m_ActionButtonText
protected TextWidget Hud::m_ActionButtonText private
Definition at line 117 of file ingamehud.c.
m_ActionDesc
protected TextWidget Hud::m_ActionDesc private
Definition at line 109 of file ingamehud.c.
m_ActionHealthMark
protected Widget m_ActionItemQuantityWrapper protected ImageWidget Hud::m_ActionHealthMark private
Definition at line 112 of file ingamehud.c.
m_ActionIcon
protected ImageWidget Hud::m_ActionIcon private
Definition at line 116 of file ingamehud.c.
m_ActionIconFrame
protected Widget Hud::m_ActionIconFrame private
Definition at line 119 of file ingamehud.c.
m_ActionItemDesc
protected TextWidget Hud::m_ActionItemDesc private
Definition at line 110 of file ingamehud.c.
m_ActionMultipleItemsFrame
protected Widget Hud::m_ActionMultipleItemsFrame private
Definition at line 120 of file ingamehud.c.
m_ActionQuantityBar
protected ProgressBarWidget Hud::m_ActionQuantityBar private
Definition at line 113 of file ingamehud.c.
m_ActionQuantityBox
protected Widget Hud::m_ActionQuantityBox private
Definition at line 114 of file ingamehud.c.
m_ActionQuantityBoxText
protected TextWidget Hud::m_ActionQuantityBoxText private
Definition at line 115 of file ingamehud.c.
m_ActionTarget
protected Widget Hud::m_ActionTarget private
Definition at line 122 of file ingamehud.c.
m_ActionTargetsCursor
protected ActionTargetsCursor Hud::m_ActionTargetsCursor private
Definition at line 123 of file ingamehud.c.
m_ActionWidget
protected Widget Hud::m_ActionWidget private
Definition at line 108 of file ingamehud.c.
m_AnyBadgeVisible
protected bool Hud::m_AnyBadgeVisible private
Definition at line 17 of file ingamehud.c.
m_BadgeNotifierDivider
protected Widget Hud::m_BadgeNotifierDivider private
Definition at line 68 of file ingamehud.c.
m_Badges
protected Widget Hud::m_Badges private
Definition at line 69 of file ingamehud.c.
m_BadgesWidgetDisplay
protected ref map<int,int> Hud::m_BadgesWidgetDisplay private
Definition at line 15 of file ingamehud.c.
m_BadgesWidgetNames
protected ref map<int,string> Hud::m_BadgesWidgetNames private
Definition at line 14 of file ingamehud.c.
m_BadgesWidgets
protected ref map<int,ImageWidget> Hud::m_BadgesWidgets private
Definition at line 16 of file ingamehud.c.
m_BlinkTime
protected float Hud::m_BlinkTime private
Definition at line 12 of file ingamehud.c.
m_BloodPosType
protected TextWidget Hud::m_BloodPosType private
Definition at line 67 of file ingamehud.c.
m_BloodType
protected TextWidget Hud::m_BloodType private
Definition at line 66 of file ingamehud.c.
m_CurrentTaggedPlayer
PlayerBase Hud::m_CurrentTaggedPlayer private
Definition at line 1257 of file ingamehud.c.
m_CurrentVehicle
protected CarScript Hud::m_CurrentVehicle private
Definition at line 63 of file ingamehud.c.
m_CursorIcon
protected ImageWidget Hud::m_CursorIcon private
Definition at line 105 of file ingamehud.c.
m_CursorWidget
protected Widget Hud::m_CursorWidget private
Definition at line 104 of file ingamehud.c.
m_Faded
protected bool Hud::m_Faded private
Definition at line 137 of file ingamehud.c.
m_FadeTimerActionCursor
protected ref WidgetFadeTimer Hud::m_FadeTimerActionCursor private
Definition at line 72 of file ingamehud.c.
m_FadeTimerCrosshair
protected ref WidgetFadeTimer Hud::m_FadeTimerCrosshair private
Definition at line 71 of file ingamehud.c.
m_FadeTimerMagazineName
protected ref WidgetFadeTimer Hud::m_FadeTimerMagazineName private
Definition at line 76 of file ingamehud.c.
m_FadeTimerQuickbar
protected ref WidgetFadeTimer Hud::m_FadeTimerQuickbar private
Definition at line 79 of file ingamehud.c.
m_FadeTimers
protected ref array<ref WidgetFadeTimer> Hud::m_FadeTimers = new array<ref WidgetFadeTimer> private
Definition at line 98 of file ingamehud.c.
m_FadeTimerWalkieTalkie
protected ref WidgetFadeTimer Hud::m_FadeTimerWalkieTalkie private
Definition at line 80 of file ingamehud.c.
m_FadeTimerWalkieTalkieText
protected ref WidgetFadeTimer Hud::m_FadeTimerWalkieTalkieText private
Definition at line 81 of file ingamehud.c.
m_FadeTimerWeaponName
protected ref WidgetFadeTimer Hud::m_FadeTimerWeaponName private
Definition at line 77 of file ingamehud.c.
m_FadeTimerWeaponStats
protected ref WidgetFadeTimer Hud::m_FadeTimerWeaponStats private
Definition at line 78 of file ingamehud.c.
m_FadeTimerZeroingOld
protected ref WidgetFadeTimer Hud::m_FadeTimerZeroingOld private
Definition at line 75 of file ingamehud.c.
m_HeatBufferPlus
protected ImageWidget Hud::m_HeatBufferPlus private
Definition at line 21 of file ingamehud.c.
m_HideTimer
protected ref Timer Hud::m_HideTimer private
Definition at line 70 of file ingamehud.c.
m_HitDirEffectArray
ref array<ref HitDirectionEffectBase> Hud::m_HitDirEffectArray private
Definition at line 148 of file ingamehud.c.
m_HitIndicatorDown
protected Widget Hud::m_HitIndicatorDown private
Definition at line 141 of file ingamehud.c.
m_HitIndicatorLeft
protected Widget Hud::m_HitIndicatorLeft private
Definition at line 142 of file ingamehud.c.
m_HitIndicatorRight
protected Widget Hud::m_HitIndicatorRight private
Definition at line 143 of file ingamehud.c.
m_HitIndicatorSingle
protected Widget Hud::m_HitIndicatorSingle private
Definition at line 144 of file ingamehud.c.
m_HitIndicatorUp
protected Widget Hud::m_HitIndicatorUp private
Definition at line 140 of file ingamehud.c.
m_HudHidePlayer
protected bool Hud::m_HudHidePlayer private
Definition at line 129 of file ingamehud.c.
Referenced by IsHideHudPlayer().
m_HudHideUI
protected bool Hud::m_HudHideUI private
Definition at line 128 of file ingamehud.c.
m_HudInventory
protected bool Hud::m_HudInventory private
Definition at line 130 of file ingamehud.c.
m_HudPanelWidget
protected Widget Hud::m_HudPanelWidget private
Definition at line 30 of file ingamehud.c.
Referenced by GetHudPanelWidget().
m_HudState
protected bool Hud::m_HudState private
Definition at line 131 of file ingamehud.c.
Referenced by GetHudState(), and RefreshHudVisibility().
m_InVehicleAsDriver
protected bool Hud::m_InVehicleAsDriver private
Definition at line 62 of file ingamehud.c.
m_IsHudVisible
protected bool Hud::m_IsHudVisible private
Definition at line 136 of file ingamehud.c.
Referenced by IsHudVisible().
m_IsQuickbarVisible
protected bool Hud::m_IsQuickbarVisible private
Definition at line 135 of file ingamehud.c.
Referenced by IsQuickbarVisible().
m_IsStaminaVisible
protected bool Hud::m_IsStaminaVisible private
Definition at line 23 of file ingamehud.c.
m_IsTemperatureVisible
protected bool Hud::m_IsTemperatureVisible private
Definition at line 18 of file ingamehud.c.
m_LeftHudPanelWidget
protected Widget Hud::m_LeftHudPanelWidget private
Definition at line 31 of file ingamehud.c.
m_MouseContinuousAction
protected Widget Hud::m_MouseContinuousAction private
Definition at line 100 of file ingamehud.c.
m_MouseSingleAction
protected Widget Hud::m_MouseSingleAction private
Definition at line 99 of file ingamehud.c.
m_Notifiers
protected Widget Hud::m_Notifiers private
Definition at line 65 of file ingamehud.c.
m_PermanentCrossHair
protected ImageWidget Hud::m_PermanentCrossHair private
Definition at line 126 of file ingamehud.c.
m_PlayerSpineIndex
int Hud::m_PlayerSpineIndex private
Definition at line 1256 of file ingamehud.c.
m_PlayerTag
Widget Hud::m_PlayerTag private
Definition at line 1258 of file ingamehud.c.
m_PlayerTagText
TextWidget Hud::m_PlayerTagText private
Definition at line 1259 of file ingamehud.c.
m_Presence
protected Widget Hud::m_Presence private
Definition at line 85 of file ingamehud.c.
m_PresenceLevel0
protected Widget Hud::m_PresenceLevel0 private
Definition at line 92 of file ingamehud.c.
m_PresenceLevel1
protected Widget Hud::m_PresenceLevel1 private
Definition at line 93 of file ingamehud.c.
m_PresenceLevel2
protected Widget Hud::m_PresenceLevel2 private
Definition at line 94 of file ingamehud.c.
m_PresenceLevel3
protected Widget Hud::m_PresenceLevel3 private
Definition at line 95 of file ingamehud.c.
m_PresenceLevel4
protected Widget Hud::m_PresenceLevel4 private
Definition at line 96 of file ingamehud.c.
m_Quickbar
protected ref InventoryQuickbar Hud::m_Quickbar private
Definition at line 33 of file ingamehud.c.
Referenced by GetQuickbar().
m_QuickbarHidePlayer
protected bool Hud::m_QuickbarHidePlayer private
Definition at line 133 of file ingamehud.c.
Referenced by IsHideQuickbarPlayer().
m_QuickbarHideUI
protected bool Hud::m_QuickbarHideUI private
Definition at line 132 of file ingamehud.c.
m_QuickbarState
protected bool Hud::m_QuickbarState private
Definition at line 134 of file ingamehud.c.
Referenced by GetQuickBarState(), and RefreshQuickbarVisibility().
m_QuickbarWidget
protected Widget Hud::m_QuickbarWidget private
Definition at line 32 of file ingamehud.c.
m_RadialProgressBar
protected Widget Hud::m_RadialProgressBar private
Definition at line 103 of file ingamehud.c.
m_RadialProgressBar1
protected Widget Hud::m_RadialProgressBar1 private
Definition at line 101 of file ingamehud.c.
m_RadialProgressBarCrossHair
protected Widget Hud::m_RadialProgressBarCrossHair private
Definition at line 102 of file ingamehud.c.
m_SpecializationIcon
protected Widget Hud::m_SpecializationIcon private
Definition at line 146 of file ingamehud.c.
m_SpecializatonPanel
protected Widget Hud::m_SpecializatonPanel private
Definition at line 145 of file ingamehud.c.
m_Stamina
protected ProgressBarWidget Hud::m_Stamina private
Definition at line 83 of file ingamehud.c.
m_StaminaBackground
protected Widget Hud::m_StaminaBackground private
Definition at line 84 of file ingamehud.c.
m_StaminaShowTime
protected float Hud::m_StaminaShowTime = 0.15 private
Definition at line 25 of file ingamehud.c.
m_StaminaTimer
protected float Hud::m_StaminaTimer private
Definition at line 24 of file ingamehud.c.
m_StanceCar
protected Widget Hud::m_StanceCar private
Definition at line 90 of file ingamehud.c.
m_StanceCrouch
protected Widget Hud::m_StanceCrouch private
Definition at line 89 of file ingamehud.c.
m_StancePanel
protected Widget Hud::m_StancePanel private
Definition at line 91 of file ingamehud.c.
m_StanceProne
protected Widget Hud::m_StanceProne private
Definition at line 86 of file ingamehud.c.
m_StanceStand
protected Widget Hud::m_StanceStand private
Definition at line 87 of file ingamehud.c.
m_StanceStandWalk
protected Widget Hud::m_StanceStandWalk private
Definition at line 88 of file ingamehud.c.
m_StatesWidgetNames
protected ref map<int,string> Hud::m_StatesWidgetNames private
Definition at line 7 of file ingamehud.c.
m_StatesWidgets
protected ref map<int,ImageWidget> Hud::m_StatesWidgets private
Definition at line 8 of file ingamehud.c.
m_TemperatureShowTime
protected float Hud::m_TemperatureShowTime = 30 private
Definition at line 20 of file ingamehud.c.
m_TemperatureTimer
protected float Hud::m_TemperatureTimer private
Definition at line 19 of file ingamehud.c.
m_TendencyStatusCritical
protected ref map<ImageWidget, int> Hud::m_TendencyStatusCritical private
Definition at line 10 of file ingamehud.c.
m_Timer
ref Timer Hud::m_Timer private
Definition at line 617 of file gameplay.c.
m_TimeSinceLastEngineLightChange
float Hud::m_TimeSinceLastEngineLightChange private
Definition at line 804 of file ingamehud.c.
m_VehicleBatteryLight
protected ImageWidget Hud::m_VehicleBatteryLight private
Definition at line 53 of file ingamehud.c.
m_VehicleCurrentGearValue
protected TextWidget Hud::m_VehicleCurrentGearValue private
Definition at line 49 of file ingamehud.c.
m_VehicleDamageZoneHitEngineState
protected bool Hud::m_VehicleDamageZoneHitEngineState private
Definition at line 59 of file ingamehud.c.
m_VehicleDamageZonesHitTimer
protected float Hud::m_VehicleDamageZonesHitTimer private
Definition at line 60 of file ingamehud.c.
m_VehicleEngineLight
protected ImageWidget Hud::m_VehicleEngineLight private
Definition at line 54 of file ingamehud.c.
m_VehicleFuelLight
protected ImageWidget Hud::m_VehicleFuelLight private
Definition at line 45 of file ingamehud.c.
m_VehicleFuelPointer
protected ImageWidget Hud::m_VehicleFuelPointer private
Definition at line 44 of file ingamehud.c.
m_VehicleGearCount
int Hud::m_VehicleGearCount = -1 private
Definition at line 803 of file ingamehud.c.
m_VehicleGearTable
protected ref map<int,string> Hud::m_VehicleGearTable private
Definition at line 27 of file ingamehud.c.
m_VehicleGearTableAuto
protected ref map<int,string> Hud::m_VehicleGearTableAuto private
Definition at line 28 of file ingamehud.c.
m_VehicleHandBrakeLight
protected ImageWidget Hud::m_VehicleHandBrakeLight private
Definition at line 56 of file ingamehud.c.
m_VehicleHasCoolant
bool Hud::m_VehicleHasCoolant private
Definition at line 806 of file ingamehud.c.
m_VehicleHasOil
bool Hud::m_VehicleHasOil private
Definition at line 805 of file ingamehud.c.
m_VehicleNextGearValue
protected TextWidget Hud::m_VehicleNextGearValue private
Definition at line 50 of file ingamehud.c.
m_VehicleOilLight
protected ImageWidget Hud::m_VehicleOilLight private
Definition at line 55 of file ingamehud.c.
m_VehiclePanel
protected Widget Hud::m_VehiclePanel private
Definition at line 35 of file ingamehud.c.
m_VehiclePrevGearValue
protected TextWidget Hud::m_VehiclePrevGearValue private
Definition at line 51 of file ingamehud.c.
m_VehicleRPMDial
protected ImageWidget Hud::m_VehicleRPMDial private
Definition at line 38 of file ingamehud.c.
m_VehicleRPMPointer
protected ImageWidget Hud::m_VehicleRPMPointer private
Definition at line 37 of file ingamehud.c.
m_VehicleRPMRedline
protected ImageWidget Hud::m_VehicleRPMRedline private
Definition at line 39 of file ingamehud.c.
m_VehicleSpeedPointer
protected ImageWidget Hud::m_VehicleSpeedPointer private
Definition at line 40 of file ingamehud.c.
m_VehicleSpeedValue
protected TextWidget Hud::m_VehicleSpeedValue private
Definition at line 47 of file ingamehud.c.
m_VehicleTemperatureIndicator
protected Widget Hud::m_VehicleTemperatureIndicator private
Definition at line 41 of file ingamehud.c.
m_VehicleTemperatureLight
protected ImageWidget Hud::m_VehicleTemperatureLight private
Definition at line 43 of file ingamehud.c.
m_VehicleTemperaturePointer
protected ImageWidget Hud::m_VehicleTemperaturePointer private
Definition at line 42 of file ingamehud.c.
m_VehicleWheelLight
protected ImageWidget Hud::m_VehicleWheelLight private
Definition at line 57 of file ingamehud.c.
m_WalkieTalkie
protected Widget Hud::m_WalkieTalkie private
Definition at line 106 of file ingamehud.c.
m_ZeroingKeyPressed
protected bool Hud::m_ZeroingKeyPressed private
Definition at line 138 of file ingamehud.c.
myTimer
protected ref Timer Hud::myTimer private
Definition at line 97 of file ingamehud.c.
TENDENCY_BLINK_TIME
protected const float Hud::TENDENCY_BLINK_TIME = 0.25 private
Definition at line 11 of file ingamehud.c.