DayzKode: EffectSound Class Reference
EffectSound Class Reference
Wrapper class for managing sound through SEffectManager.
Private Member Functions
EffectType
Information about what type of effect the Effect is, without the need for casting
override EffectType GetEffectType ()
Get what type of effect the Effect is.
override bool IsSound ()
Check whether the Effect is EffectSound without casting.
Playback
Methods to Play/Stop sound Generally, SEffectManager.PlaySound methods are used instead of SoundPlay
bool SoundPlayEx (out SoundParams params)
Plays sound.
bool SoundPlay ()
Plays sound.
override void Start ()
Plays sound.
void SoundStop ()
Stops sound.
override void Stop ()
Stops sound.
protected void SoundReset ()
Resets EffectSound.
bool IsSoundPlaying ()
Get whether EffectSound is currently playing.
override bool IsPlaying ()
Returns true when the effect is playing, false otherwise.
Sound load
Methods regarding the loading of the sound, used in SoundPlay
bool SoundLoadEx (out SoundParams params)
Loads in the sound when it is requested for playing through 'SoundPlayEx'.
bool SoundLoad ()
Loads in the sound when it is requested for playing.
bool IsSoundValid ()
Helper for checking if params are valid.
protected void ValidateSoundWave ()
Gets called to fill in the necessary data when the header has finished loading.
protected bool SoundWaveValidation ()
Validation of fade settings.
protected void UpdateEvents ()
Enables the frame event on the EffectSound.
Events
Various events that can be overriden for custom behaviour
override void Event_OnFrameUpdate (float time_delta)
Event called on frame when enabled by SetEnableEventFrame(true)
override void Event_OnRegistered (int id)
Event called from SEffectManager when the Effect is registered.
override void Event_OnUnregistered ()
Event called from SEffectManager when the Effect is unregistered.
void Event_OnSoundWaveStarted ()
Event called when sound starts playing.
void Event_OnSoundWaveEnded ()
Event called when sound stops playing.
void Event_OnSoundFadeInStopped ()
Event called when sound fade in stops.
void Event_OnSoundFadeOutStarted ()
Event called when sound fade out starts.
AutoDestroy
Methods regarding automatic cleanup on stop
override void SetAutodestroy (bool auto_destroy)
Sets whether Effect automatically cleans up when it stops.
override bool IsAutodestroy ()
Get whether Effect automatically cleans up when it stops.
void SetSoundAutodestroy (bool auto_destroy)
Sets whether EffectSound automatically cleans up when sound stops.
bool IsSoundAutodestroy ()
Get whether EffectSound automatically cleans up when sound stops.
Generic API
Setters and getters for generic data and properties
override void SetParent (Object parent_obj)
Set parent for the sound to follow.
override Object GetParent ()
Get parent for the EffectSound.
override void SetCurrentParent (Object parent_obj, bool updateCached=true)
Set parent for the sound to follow.
override Object GetCurrentParent ()
Get parent for the EffectSound.
override void SetCurrentPosition (vector pos, bool updateCached=true)
Set the world position of the managed sound.
override vector GetCurrentPosition ()
Get the current world position of the managed sound.
override void SetCurrentLocalPosition (vector pos, bool updateCached=true)
Set the current local position of the managed sound.
override vector GetCurrentLocalPosition ()
Get the current local position of the managed sound.
void SetSoundWaveKind (WaveKind wave_kind)
Set WaveKind for the sound.
void SetSoundSet (string snd)
Set soundset for the sound.
string GetSoundSet ()
Get soundset for the sound.
void SetSoundLoop (bool loop)
Set if the sound loops.
void SetEnviromentVariables (bool setEnvVariables)
Sets whether UpdateEnvSoundControllers needs to be called during Loading.
float GetSoundWaveLenght ()
Get the sound wave length.
float GetSoundWaveLength ()
Get the sound wave length.
void SetSoundVolume (float volume)
Set the RELATIVE volume for the sound.
float GetSoundVolume ()
Get the RELATIVE volume set by 'SetSoundVolume'.
void SetSoundMaxVolume (float volume)
Set the sound max volume.
float GetSoundWaveTime ()
Get the time since EffectSound started playing.
void SetSoundFadeIn (float fade_in)
Set the sound fade in duration.
void SetSoundFadeOut (float fade_out)
Set the sound fade out duration.
protected void SoundError (string err_msg)
Helper for throwing sound errors.
Private Attributes
Event invokers
ScriptInvonkers for certain events
ref ScriptInvoker Event_OnSoundWaveStarted = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundWaveEnded = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundFadeInStopped = new ScriptInvoker()
ref ScriptInvoker Event_OnSoundFadeOutStarted = new ScriptInvoker()
Sound objects and structures
Objects and structures for the sound
protected ref SoundParams m_SoundParams
protected ref SoundObjectBuilder m_SoundObjectBuilder
protected ref SoundObject m_SoundObject
protected AbstractWave m_SoundWaveObject
Generic data
Generic data for the sound
protected Object m_SoundParent
protected WaveKind m_SoundWaveKind
protected string m_SoundSetName
protected bool m_SoundLoop
protected bool m_SetEnvVariables
protected bool m_SoundAutodestroy
protected bool m_SoundWaveIsPlaying
protected float m_SoundWaveLenght
protected float m_SoundWaveVolume
protected float m_SoundWaveVolumeMax
protected float m_SoundWaveTime
Fading data
Data for fadein/fadeout for the sound
protected bool m_SoundWaveStarting
protected bool m_SoundWaveStopping
protected float m_SoundFadeInDuration
protected float m_SoundFadeOutStartTime
protected float m_SoundFadeOutDuration
protected float m_SoundFadeOutInitVolume
void EffectSound ()
ctor
void ~EffectSound ()
dtor
override void InitEffect ()
init
override string GetDebugName ()
Override when getting debug information.
Detailed Description
Wrapper class for managing sound through SEffectManager.
Definition at line 4 of file effectsound.c.
Constructor & Destructor Documentation
EffectSound()
void EffectSound::EffectSound () inline private
ctor
Definition at line 62 of file effectsound.c.
    {
        m_SoundWaveKind = WaveKind.WAVEEFFECTEX;
        m_SoundWaveVolume = 0;
        m_SoundWaveVolumeMax = 1;
        m_SoundAutodestroy = false;
        m_SoundWaveStopping = false;
    }
References m_SoundAutodestroy, m_SoundWaveKind, m_SoundWaveStopping, m_SoundWaveVolume, and m_SoundWaveVolumeMax.
~EffectSound()
void EffectSound::~EffectSound () inline private
dtor
Definition at line 74 of file effectsound.c.
    {
    }
Member Function Documentation
Event_OnFrameUpdate()
override void EffectSound::Event_OnFrameUpdate (float time_delta) inline private
Event called on frame when enabled by SetEnableEventFrame(true)
Note
Is always enabled on sound
Called from SEffectManager.Event_OnFrameUpdate in MissionGameplay.OnUpdate
Parameters
time_delta float Time passed since the previous frame
Definition at line 444 of file effectsound.c.
    {
        if ( IsSoundPlaying() )
        {
            // Make the sound follow the parent
            if ( m_SoundParent )
            {
                SetCurrentPosition( m_SoundParent.ModelToWorld( GetLocalPosition() ) );
            }
            // FadeIn
            if ( m_SoundWaveStarting )
            {
                if ( m_SoundFadeInDuration > 0 )
                {
                    SetSoundVolume( GetSoundVolume() + (time_delta / m_SoundFadeInDuration) );
                    if ( GetSoundVolume() >= m_SoundWaveVolumeMax )
                    {
                        Event_OnSoundFadeInStopped();
                        SetSoundVolume( m_SoundWaveVolumeMax );
                        m_SoundWaveStarting = false;
                    }
                }
                else
                {
                    SetSoundVolume( m_SoundWaveVolumeMax );
                    m_SoundWaveStarting = false;
                }
            }
            // FadeOut
            if ( m_SoundWaveStopping )
            {
                if ( m_SoundFadeOutDuration > 0 )
                {
                    if ( m_SoundFadeOutInitVolume == 0 )
                    {
                        m_SoundFadeOutInitVolume = GetSoundVolume();
                        Event_OnSoundFadeOutStarted();
                    }
                    SetSoundVolume( GetSoundVolume() - (m_SoundFadeOutInitVolume / m_SoundFadeOutDuration * time_delta) );
                }
                else
                {
                    SetSoundVolume( 0 );
                }
                if ( GetSoundVolume() <= 0 )
                {
                    if ( m_SoundWaveObject )
                    {
                        m_SoundWaveObject.Stop();
                    }
                }
            }
            // Counting timer here because loop play
            m_SoundWaveTime += time_delta;
        }
    }
References Event_OnSoundFadeInStopped, Event_OnSoundFadeOutStarted, GetLocalPosition(), GetSoundVolume(), IsSoundPlaying(), m_SoundFadeInDuration, m_SoundFadeOutDuration, m_SoundFadeOutInitVolume, m_SoundParent, m_SoundWaveObject, m_SoundWaveStarting, m_SoundWaveStopping, m_SoundWaveTime, m_SoundWaveVolumeMax, SetCurrentPosition(), SetSoundVolume(), and AbstractWave::Stop().
Event_OnRegistered()
override void EffectSound::Event_OnRegistered (int id) inline private
Event called from SEffectManager when the Effect is registered.
Note
Should only ever be called by SEffectManager!
Parameters
id int ID registered in SEffectManager
Definition at line 511 of file effectsound.c.
    {
        super.Event_OnRegistered(id);
        Event_OnSoundWaveEnded.Insert( SEffectManager.Event_OnSoundWaveEnded );
    }
References SEffectManager::Event_OnSoundWaveEnded(), Event_OnSoundWaveEnded, and ScriptInvoker::Insert().
Event_OnSoundFadeInStopped()
void EffectSound::Event_OnSoundFadeInStopped () inline private
Event called when sound fade in stops.
Note
Called from Event_OnFrameUpdate
Definition at line 559 of file effectsound.c.
    {
        Event_OnSoundFadeInStopped.Invoke(this);
    }
References Event_OnSoundFadeInStopped, and ScriptInvoker::Invoke().
Event_OnSoundFadeOutStarted()
void EffectSound::Event_OnSoundFadeOutStarted () inline private
Event called when sound fade out starts.
Note
Called from Event_OnFrameUpdate
Definition at line 568 of file effectsound.c.
    {
        Event_OnSoundFadeOutStarted.Invoke(this);
    }
References Event_OnSoundFadeOutStarted, and ScriptInvoker::Invoke().
Event_OnSoundWaveEnded()
void EffectSound::Event_OnSoundWaveEnded () inline private
Event called when sound stops playing.
Note
Inserted into events of m_SoundWaveObject
Definition at line 546 of file effectsound.c.
    {
        m_SoundWaveIsPlaying = false;
        Event_OnSoundWaveEnded.Invoke(this);
        Event_OnEffectEnded();
    }
References Event_OnEffectEnded, Event_OnSoundWaveEnded, ScriptInvoker::Invoke(), and m_SoundWaveIsPlaying.
Event_OnSoundWaveStarted()
void EffectSound::Event_OnSoundWaveStarted () inline private
Event called when sound starts playing.
Note
Inserted into events of m_SoundWaveObject
Definition at line 533 of file effectsound.c.
    {
        m_SoundWaveIsPlaying = true;
        Event_OnSoundWaveStarted.Invoke(this);
        Event_OnEffectStarted();
    }
References Event_OnEffectStarted, Event_OnSoundWaveStarted, ScriptInvoker::Invoke(), and m_SoundWaveIsPlaying.
Event_OnUnregistered()
override void EffectSound::Event_OnUnregistered () inline private
Event called from SEffectManager when the Effect is unregistered.
Note
Should only ever be called by SEffectManager!
Definition at line 522 of file effectsound.c.
    {
        super.Event_OnUnregistered();
        Event_OnSoundWaveEnded.Remove( SEffectManager.Event_OnSoundWaveEnded );
    }
References SEffectManager::Event_OnSoundWaveEnded(), Event_OnSoundWaveEnded, and ScriptInvoker::Remove().
GetCurrentLocalPosition()
override vector EffectSound::GetCurrentLocalPosition () inline private
Get the current local position of the managed sound.
Returns
vector The current local position of the managed sound
Definition at line 730 of file effectsound.c.
    {
        if (m_SoundObject)
        {
            Object parent = GetParent();
            if (parent)
                return parent.WorldToModel(m_SoundObject.GetPosition());
            else
                return m_SoundObject.GetPosition();
        }
        else
            return super.GetCurrentLocalPosition();
    }
References GetParent(), and m_SoundObject.
GetCurrentParent()
override Object EffectSound::GetCurrentParent () inline private
Get parent for the EffectSound.
Note
There is no real parenting with sound, so the setters and getters for parents do the exact same
Returns
Object The parent for the EffectSound
Definition at line 672 of file effectsound.c.
    {
        // .........
        if (m_SoundParent)
            return m_SoundParent;
        else
            return super.GetParent(); // Yes, intentionally this one
    }
References m_SoundParent.
GetCurrentPosition()
override vector EffectSound::GetCurrentPosition () inline private
Get the current world position of the managed sound.
Returns
vector The current world position of the managed sound
Definition at line 698 of file effectsound.c.
    {
        if (m_SoundObject)
            return m_SoundObject.GetPosition();
        else
            return super.GetCurrentPosition();
    }
References m_SoundObject.
GetDebugName()
override string EffectSound::GetDebugName () inline private
Override when getting debug information.
Definition at line 94 of file effectsound.c.
    {
        string identifier;
        if (m_SoundSetName != "")
        {
            identifier = m_SoundSetName;
        }
        else
        {
            identifier = "NO_SOUNDSET";
        }
        return string.Format("%1:%2", super.GetDebugName(), identifier);
    }
References string::Format(), and m_SoundSetName.
GetEffectType()
override EffectType EffectSound::GetEffectType () inline private
Get what type of effect the Effect is.
Returns
EffectType What type of effect the Effect is
Definition at line 120 of file effectsound.c.
    {
        return EffectType.SOUND;
    }
GetParent()
override Object EffectSound::GetParent () inline private
Get parent for the EffectSound.
Returns
Object The parent for the EffectSound
Definition at line 645 of file effectsound.c.
    {
        // .........
        if (m_SoundParent)
            return m_SoundParent;
        else
            return super.GetParent();
    }
References m_SoundParent.
Referenced by GetCurrentLocalPosition(), and SetCurrentLocalPosition().
GetSoundSet()
string EffectSound::GetSoundSet () inline private
Get soundset for the sound.
Returns
string Name of the soundset
Definition at line 769 of file effectsound.c.
    {
        return m_SoundSetName;
    }
References m_SoundSetName.
GetSoundVolume()
float EffectSound::GetSoundVolume () inline private
Get the RELATIVE volume set by 'SetSoundVolume'.
Returns
float The relative volume for the sound set by 'SetSoundVolume'
Definition at line 829 of file effectsound.c.
    {
        return m_SoundWaveVolume;
    }
References m_SoundWaveVolume.
Referenced by Event_OnFrameUpdate().
GetSoundWaveLenght()
float EffectSound::GetSoundWaveLenght () inline private
Get the sound wave length.
Note
Legacy, exists for backwards compatibility
Returns
float The sound wave length
Definition at line 800 of file effectsound.c.
    {
        return GetSoundWaveLength();
    }
References GetSoundWaveLength().
GetSoundWaveLength()
float EffectSound::GetSoundWaveLength () inline private
Get the sound wave length.
Returns
float The sound wave length
Definition at line 809 of file effectsound.c.
    {
        return m_SoundWaveLenght;
    }
References m_SoundWaveLenght.
Referenced by GetSoundWaveLenght(), and SoundWaveValidation().
GetSoundWaveTime()
float EffectSound::GetSoundWaveTime () inline private
Get the time since EffectSound started playing.
Warning
May not reflect the actual time of the sound, as it can start at negative time to simulate speed of sound
Returns
float The time since EffectSound started playing
Definition at line 852 of file effectsound.c.
    {
        return m_SoundWaveTime;
    }
References m_SoundWaveTime.
InitEffect()
override void EffectSound::InitEffect () inline private
init
Definition at line 82 of file effectsound.c.
    {
        super.InitEffect();
        // These will be called by the sound events
        Event_OnStarted.Remove(Event_OnEffectStarted);
        Event_OnStopped.Remove(Event_OnEffectEnded);
    }
References Event_OnEffectEnded, Event_OnEffectStarted, Event_OnStarted, Event_OnStopped, and ScriptInvoker::Remove().
IsAutodestroy()
override bool EffectSound::IsAutodestroy () inline private
Get whether Effect automatically cleans up when it stops.
Returns
bool Whether Effect automatically cleans up when it stops
Definition at line 597 of file effectsound.c.
    {
        return IsSoundAutodestroy();
    }
References IsSoundAutodestroy().
IsPlaying()
override bool EffectSound::IsPlaying () inline private
Returns true when the effect is playing, false otherwise.
Definition at line 273 of file effectsound.c.
    {
        return IsSoundPlaying(); // Just in case, as that's what used to be the actual way to check
    }
References IsSoundPlaying().
Referenced by FlashbangEffect::PlaySound().
IsSound()
override bool EffectSound::IsSound () inline private
Check whether the Effect is EffectSound without casting.
Returns
bool Whether the Effect is EffectSound
Definition at line 129 of file effectsound.c.
    {
        return true;
    }
IsSoundAutodestroy()
bool EffectSound::IsSoundAutodestroy () inline private
Get whether EffectSound automatically cleans up when sound stops.
Returns
bool Whether EffectSound automatically cleans up when sound stops
Definition at line 615 of file effectsound.c.
    {
        return m_SoundAutodestroy;
    }
References m_SoundAutodestroy.
Referenced by IsAutodestroy().
IsSoundPlaying()
bool EffectSound::IsSoundPlaying () inline private
Get whether EffectSound is currently playing.
Returns
bool Whether EffectSound is currently playing
Definition at line 265 of file effectsound.c.
    {
        return m_SoundWaveIsPlaying;
    }
References m_SoundWaveIsPlaying.
Referenced by Event_OnFrameUpdate(), IsPlaying(), InventoryItem::OnRPC(), ActionBuildShelter::PlayActionLoopSound(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), PlayDeployLoopSound(), PlayDisarmingLoopSound(), PlayEmptyingLoopSound(), PlayPouringLoopSound(), PlaySoundEx(), and SoundStop().
IsSoundValid()
bool EffectSound::IsSoundValid () inline private
Helper for checking if params are valid.
Definition at line 346 of file effectsound.c.
    {
        return m_SoundParams.IsValid();
    }
References SoundParams::IsValid(), and m_SoundParams.
SetAutodestroy()
override void EffectSound::SetAutodestroy (bool auto_destroy) inline private
Sets whether Effect automatically cleans up when it stops.
Note
This means that it will be unregistered from SEffectManager as well
Parameters
auto_destroy bool Whether Effect automatically cleans up when it stops
Definition at line 587 of file effectsound.c.
    {
        super.SetAutodestroy(auto_destroy);
        m_SoundAutodestroy = auto_destroy;
    }
References m_SoundAutodestroy.
Referenced by DelayedMidAirDetonation(), House::EEInit(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), HandleDoorsSound(), HandleEngineSound(), CarScript::OnAnimationPhaseStarted(), Weapon::OnFireModeChange(), OnRPC(), OnSteppedOn(), ActionBuildShelter::PlayActionFinishSound(), ActionBuildShelter::PlayActionStartSound(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), InventoryItem::PlayDeploySound(), InventoryItem::PlayPlaceSound(), PlaySound(), PlaySoundActivate(), TrapBase::PlaySoundBiteEmpty(), TrapBase::PlaySoundBiteLeg(), PlaySoundEx(), TrapBase::PlaySoundOpen(), PlaySoundSet(), SetSoundAutodestroy(), Barrel_ColorBase::SoundBarrelClosePlay(), FireplaceBase::SoundBarrelClosePlay(), Barrel_ColorBase::SoundBarrelOpenPlay(), FireplaceBase::SoundBarrelOpenPlay(), ItemBase::SoundTentClosePlay(), ItemBase::SoundTentCloseWindowPlay(), ItemBase::SoundTentOpenPlay(), ItemBase::SoundTentOpenWindowPlay(), StartActivate(), and StopEmptyingLoopSound().
SetCurrentLocalPosition()
override void EffectSound::SetCurrentLocalPosition (vector pos, bool updateCached = true) inline private
Set the current local position of the managed sound.
Parameters
pos vector The current local position for the managed sound
updateCached bool Whether to update the cached variable
Definition at line 711 of file effectsound.c.
    {
        super.SetCurrentLocalPosition(pos, updateCached);
        if (m_SoundObject)
        {
            Object parent = GetParent();
            if (parent)
                m_SoundObject.SetPosition(parent.ModelToWorld(pos));
            else
                m_SoundObject.SetPosition(pos);
        }
    }
References GetParent(), and m_SoundObject.
SetCurrentParent()
override void EffectSound::SetCurrentParent (Object parent_obj, bool updateCached = true) inline private
Set parent for the sound to follow.
Note
The position of the sound is adjusted to the parent in Event_OnFrameUpdate...
There is no real parenting with sound, so the setters and getters for parents do the exact same
Parameters
parent_obj Object The parent for the sound to follow
updateCached bool Whether to update the cached variable
Definition at line 661 of file effectsound.c.
    {
        super.SetCurrentParent(parent_obj, updateCached); // ...
        m_SoundParent = parent_obj; // ......
    }
References m_SoundParent.
SetCurrentPosition()
override void EffectSound::SetCurrentPosition (vector pos, bool updateCached = true) inline private
Set the world position of the managed sound.
Parameters
pos vector The world position of the managed sound
updateCached bool Whether to update the cached variable
Definition at line 686 of file effectsound.c.
    {
        super.SetCurrentPosition(pos, updateCached);
        if (m_SoundObject)
            m_SoundObject.SetPosition(pos);
    }
References m_SoundObject.
Referenced by Event_OnFrameUpdate(), and SoundPlayEx().
SetEnviromentVariables()
void EffectSound::SetEnviromentVariables (bool setEnvVariables) inline private
Sets whether UpdateEnvSoundControllers needs to be called during Loading.
Parameters
setEnvVariables bool Whether UpdateEnvSoundControllers is called
Definition at line 790 of file effectsound.c.
    {
        m_SetEnvVariables = setEnvVariables;
    }
References m_SetEnvVariables.
Referenced by SEffectManager::CreateSound().
SetParent()
override void EffectSound::SetParent (Object parent_obj) inline private
Set parent for the sound to follow.
Note
The position of the sound is adjusted to the parent in Event_OnFrameUpdate...
There is no real parenting with sound, so the setters and getters for parents do the exact same
Parameters
parent_obj Object The parent for the sound to follow
Definition at line 635 of file effectsound.c.
    {
        super.SetParent(parent_obj); // ...
        m_SoundParent = parent_obj; // ......
    }
References m_SoundParent.
Referenced by FlashbangEffect::PlaySound(), and SEffectManager::PlaySoundOnObject().
SetSoundAutodestroy()
void EffectSound::SetSoundAutodestroy (bool auto_destroy) inline private
Sets whether EffectSound automatically cleans up when sound stops.
Parameters
auto_destroy bool Whether EffectSound automatically cleans up when sound stops
Definition at line 606 of file effectsound.c.
    {
        SetAutodestroy(auto_destroy);
    }
References SetAutodestroy().
SetSoundFadeIn()
void EffectSound::SetSoundFadeIn (float fade_in) inline private
Set the sound fade in duration.
Parameters
fade_in float The fade in duration
Definition at line 861 of file effectsound.c.
    {
        m_SoundFadeInDuration = fade_in;
    }
References m_SoundFadeInDuration.
Referenced by SEffectManager::CreateSound(), and FlashbangEffect::PlaySound().
SetSoundFadeOut()
void EffectSound::SetSoundFadeOut (float fade_out) inline private
Set the sound fade out duration.
Parameters
fade_out float The fade out duration
Definition at line 870 of file effectsound.c.
    {
        m_SoundFadeOutDuration = fade_out;
    }
References m_SoundFadeOutDuration.
Referenced by SEffectManager::CreateSound(), FlashbangEffect::PlaySound(), ActionBuildShelter::StopActionLoopSound(), ItemBase::StopDeployLoopSound(), Inventory_Base::StopDeployLoopSound(), and StopDeployLoopSound().
SetSoundLoop()
void EffectSound::SetSoundLoop (bool loop) inline private
Set if the sound loops.
Parameters
loop bool Whether the sound should loop
Definition at line 778 of file effectsound.c.
    {
        m_SoundLoop = loop;
        if ( m_SoundWaveObject )
            m_SoundWaveObject.Loop( loop );
    }
References AbstractWave::Loop(), m_SoundLoop, and m_SoundWaveObject.
Referenced by SEffectManager::CreateSound(), FlashbangEffect::PlaySound(), and ValidateSoundWave().
SetSoundMaxVolume()
void EffectSound::SetSoundMaxVolume (float volume) inline private
Set the sound max volume.
Warning
Seems to purely be used for fade in effect, rather than really setting the max volume...
Adjusts the current volume to this value as well
Parameters
volume float The maximum volume for the sound
Definition at line 840 of file effectsound.c.
    {
        m_SoundWaveVolumeMax = volume;
        if ( m_SoundWaveObject )
            m_SoundWaveObject.SetVolumeRelative( m_SoundWaveVolume );
    }
References m_SoundWaveObject, m_SoundWaveVolume, m_SoundWaveVolumeMax, and AbstractWave::SetVolumeRelative().
Referenced by FlashbangEffect::PlaySound().
SetSoundSet()
void EffectSound::SetSoundSet (string snd) inline private
Set soundset for the sound.
Note
Needs to be set before playing
Parameters
snd string Name of the soundset to play
Definition at line 760 of file effectsound.c.
    {
        m_SoundSetName = snd;
    }
References m_SoundSetName.
Referenced by SEffectManager::CreateSound().
SetSoundVolume()
void EffectSound::SetSoundVolume (float volume) inline private
Set the RELATIVE volume for the sound.
Parameters
volume float The relative volume for the sound
Definition at line 818 of file effectsound.c.
    {
        m_SoundWaveVolume = volume;
        if ( m_SoundWaveObject )
            m_SoundWaveObject.SetVolumeRelative( volume );
    }
References m_SoundWaveObject, m_SoundWaveVolume, and AbstractWave::SetVolumeRelative().
Referenced by Event_OnFrameUpdate(), and ProcessSound().
SetSoundWaveKind()
void EffectSound::SetSoundWaveKind (WaveKind wave_kind) inline private
Set WaveKind for the sound.
Note
Needs to be set before playing
Parameters
wave_kind WaveKind The WaveKind for the sound
Definition at line 750 of file effectsound.c.
    {
        m_SoundWaveKind = wave_kind;
    }
References m_SoundWaveKind.
Referenced by HandleEngineSound(), and FlashbangEffect::PlaySound().
SoundError()
protected void EffectSound::SoundError (string err_msg) inline private
Helper for throwing sound errors.
Definition at line 882 of file effectsound.c.
    {
        ErrorEx(string.Format("%1: SoundSetName: '%2' :: %3", this, m_SoundSetName, err_msg));
    }
References ErrorEx, and m_SoundSetName.
Referenced by SoundLoadEx(), SoundPlayEx(), and SoundWaveValidation().
SoundLoad()
bool EffectSound::SoundLoad () inline private
Loads in the sound when it is requested for playing.
Note
Legacy, backwards compatibility
Definition at line 337 of file effectsound.c.
    {
        SoundParams params;
        return SoundLoadEx(params);
    }
References SoundLoadEx().
SoundLoadEx()
bool EffectSound::SoundLoadEx (out SoundParams params) inline private
Loads in the sound when it is requested for playing through 'SoundPlayEx'.
Parameters
params SoundParams Possibility of passing in an already existing SoundParams, else one will get created
Definition at line 291 of file effectsound.c.
    {
        if ( !m_SoundParams || !m_SoundParams.IsValid() )
        {
            if (!params)
            {
                params = new SoundParams( m_SoundSetName );
            }
            //Print("SoundLoad is loading..");
            m_SoundParams = params;
            if ( !m_SoundParams.IsValid() )
            {
                SoundError("Invalid sound set.");
                return false;
            }
            m_SoundObjectBuilder = new SoundObjectBuilder( m_SoundParams );
            if (m_SetEnvVariables)
            {
                m_SoundObjectBuilder.UpdateEnvSoundControllers(GetPosition());
            }
            m_SoundObject = m_SoundObjectBuilder.BuildSoundObject();
            if ( m_SoundObject )
            {
                m_SoundObject.SetKind( m_SoundWaveKind );
            }
            else
            {
                SoundError("m_SoundObject is null.");
            }
        }
        else
        {
            //Print("SoundLoad is loaded.");
        }
        return true;
    }
References SoundObjectBuilder::BuildSoundObject(), GetPosition, SoundParams::IsValid(), m_SetEnvVariables, m_SoundObject, m_SoundObjectBuilder, m_SoundParams, m_SoundSetName, m_SoundWaveKind, SoundError(), and SoundObjectBuilder::UpdateEnvSoundControllers().
Referenced by SoundLoad(), and SoundPlayEx().
SoundPlay()
bool EffectSound::SoundPlay () inline private
Plays sound.
Returns
bool Whether the sound will start playing
Definition at line 193 of file effectsound.c.
    {
        SoundParams params;
        return SoundPlayEx(params);
    }
References SoundPlayEx().
Referenced by HandleEngineSound(), FlashbangEffect::PlaySound(), SEffectManager::PlaySound(), SEffectManager::PlaySoundEnviroment(), PlaySoundEx(), SEffectManager::PlaySoundOnObject(), and Start().
SoundPlayEx()
bool EffectSound::SoundPlayEx (out SoundParams params) inline private
Plays sound.
Parameters
params SoundParams Sound Parameters for the sound
Returns
bool Whether the sound will start playing
Definition at line 149 of file effectsound.c.
    {
        super.Start();
        if (m_SoundSetName != "")
        {
            if ( SoundLoadEx(params) )
            {
                if (m_SetEnvVariables && m_SoundParams)
                {
                    m_SoundObjectBuilder.UpdateEnvSoundControllers(GetPosition());
                    m_SoundObject = m_SoundObjectBuilder.BuildSoundObject();
                    m_SoundObject.SetKind( m_SoundWaveKind );
                }
                if ( m_SoundObject )
                {
                    SetCurrentPosition(GetPosition(), false);
                    m_SoundWaveObject = GetGame().GetSoundScene().Play3D( m_SoundObject, m_SoundObjectBuilder );
                    if( !m_SoundWaveObject )
                        return false;
                    // Wait for header to be loaded before asking for its length, else we block the main thread
                    if (m_SoundWaveObject.IsHeaderLoaded())
                        ValidateSoundWave();
                    else
                        m_SoundWaveObject.GetEvents().Event_OnSoundWaveHeaderLoaded.Insert(ValidateSoundWave);
                    return true;
                }
                else
                {
                    SoundError("m_SoundObject is null.");
                }
            }
        }
        return false;
    }
References SoundObjectBuilder::BuildSoundObject(), AbstractWave::GetEvents(), GetGame(), GetPosition, CGame::GetSoundScene(), AbstractWave::IsHeaderLoaded(), m_SetEnvVariables, m_SoundObject, m_SoundObjectBuilder, m_SoundParams, m_SoundSetName, m_SoundWaveKind, m_SoundWaveObject, SetCurrentPosition(), SoundError(), SoundLoadEx(), SoundObjectBuilder::UpdateEnvSoundControllers(), and ValidateSoundWave().
Referenced by SEffectManager::PlaySoundCachedParams(), SEffectManager::PlaySoundParams(), and SoundPlay().
SoundReset()
protected void EffectSound::SoundReset () inline private
Resets EffectSound.
Definition at line 245 of file effectsound.c.
    {
        m_IsPlaying                 = false;
        m_SoundWaveIsPlaying        = false;
        m_SoundWaveVolume           = m_SoundWaveVolumeMax;
        m_SoundWaveTime             = 0;
        m_SoundFadeOutInitVolume    = 0;
        m_SoundFadeOutStartTime     = 0;
        if ( m_SoundWaveObject )
        {
            m_SoundWaveObject.Stop();
            m_SoundWaveObject.SetVolumeRelative( m_SoundWaveVolumeMax );
        }
    }
References m_IsPlaying, m_SoundFadeOutInitVolume, m_SoundFadeOutStartTime, m_SoundWaveIsPlaying, m_SoundWaveObject, m_SoundWaveTime, m_SoundWaveVolume, m_SoundWaveVolumeMax, AbstractWave::SetVolumeRelative(), and AbstractWave::Stop().
Referenced by SoundStop().
SoundStop()
void EffectSound::SoundStop () inline private
Stops sound.
Note
Will not be immediately if a SoundFadeOutDuration was set
Definition at line 211 of file effectsound.c.
    {
        super.Stop();
        if ( IsSoundPlaying() )
        {
            if ( m_SoundFadeOutDuration > 0 && !m_SoundWaveStopping )
            {
                m_SoundWaveStopping = true;
                m_SoundWaveStarting = false;
                m_SoundFadeOutStartTime = m_SoundWaveTime;
            }
            else
            {
                m_SoundWaveObject.Stop();
            }
        }
        else
        {
            SoundReset();
        }
    }
References IsSoundPlaying(), m_SoundFadeOutDuration, m_SoundFadeOutStartTime, m_SoundWaveObject, m_SoundWaveStarting, m_SoundWaveStopping, m_SoundWaveTime, SoundReset(), and AbstractWave::Stop().
Referenced by BuildingSuper::EEDelete(), ItemBase::OnIsCharged(), Stop(), ActionBuildShelter::StopActionLoopSound(), ItemBase::StopChargedAlarm(), ItemBase::StopChargingSound(), ItemBase::StopDeployLoopSound(), Inventory_Base::StopDeployLoopSound(), StopDeployLoopSound(), StopDisarmingLoopSound(), StopEmptyingLoopSound(), StopPouringLoopSound(), FlashbangEffect::StopSound(), and FlareSimulation::~FlareSimulation().
SoundWaveValidation()
protected bool EffectSound::SoundWaveValidation () inline private
Validation of fade settings.
Note
Called from 'ValidateSoundWave'
Definition at line 387 of file effectsound.c.
    {
        bool valid = true;
        if ( m_SoundFadeInDuration > GetSoundWaveLength() )
        {
            SoundError("FadeIn is longer than sound wave length.");
            valid = false;
        }
        if ( m_SoundFadeOutDuration > GetSoundWaveLength() )
        {
            SoundError("FadeOut is longer than sound wave length.");
            valid = false;
        }
        if ( m_SoundFadeOutDuration + m_SoundFadeInDuration > GetSoundWaveLength() )
        {
            SoundError("FadeIn & FadeOut are longer than sound wave length.");
            valid = false;
        }
        return valid;
    }
References GetSoundWaveLength(), m_SoundFadeInDuration, m_SoundFadeOutDuration, and SoundError().
Referenced by ValidateSoundWave().
Start()
override void EffectSound::Start () inline private
Plays sound.
Definition at line 202 of file effectsound.c.
    {
        SoundPlay();
    }
References SoundPlay().
Stop()
override void EffectSound::Stop () inline private
Stops sound.
Definition at line 237 of file effectsound.c.
    {
        SoundStop();
    }
References SoundStop().
Referenced by Land_Underground_Stairs_Exit::HandleAudioPlayback(), UIScriptedMenu::OnClick(), FireworksLauncher::OnFiringStartClient(), FireworksLauncherClientEvent::PlayExplosionSound(), and ~UndergroundHandlerClient().
UpdateEvents()
protected void EffectSound::UpdateEvents () inline private
Enables the frame event on the EffectSound.
Note
Called from 'ValidateSoundWave' when all is successful
So this is effectively enabling frame event on all valid EffectSound
Definition at line 417 of file effectsound.c.
    {
        if ( m_SoundWaveObject )
        {
            SetEnableEventFrame(true);
        }
        else
        {
            SetEnableEventFrame(false);
        }
    }
References m_SoundWaveObject, and SetEnableEventFrame().
Referenced by ValidateSoundWave().
ValidateSoundWave()
protected void EffectSound::ValidateSoundWave () inline private
Gets called to fill in the necessary data when the header has finished loading.
Note
Called from 'SoundPlayEx'
Definition at line 355 of file effectsound.c.
    {
        m_SoundWaveLenght = m_SoundWaveObject.GetLength();
        if ( SoundWaveValidation() )
        {
            if ( m_SoundFadeInDuration > 0 )
            {
                m_SoundWaveObject.SetVolumeRelative( 0 );
                m_SoundFadeOutStartTime = m_SoundWaveLenght - m_SoundFadeInDuration;
            }
            SetSoundLoop( m_SoundLoop );
            m_SoundWaveStarting = true;
            AbstractWaveEvents events = m_SoundWaveObject.GetEvents();
            events.Event_OnSoundWaveStarted.Insert( Event_OnSoundWaveStarted );
            events.Event_OnSoundWaveEnded.Insert( Event_OnSoundWaveEnded );
            UpdateEvents();
        }
        else
        {
            m_SoundWaveObject.Stop();
        }
    }
References Event_OnSoundWaveEnded, Event_OnSoundWaveStarted, AbstractWave::GetEvents(), AbstractWave::GetLength(), m_SoundFadeInDuration, m_SoundFadeOutStartTime, m_SoundLoop, m_SoundWaveLenght, m_SoundWaveObject, m_SoundWaveStarting, SetSoundLoop(), AbstractWave::SetVolumeRelative(), SoundWaveValidation(), AbstractWave::Stop(), and UpdateEvents().
Referenced by SoundPlayEx().
Member Data Documentation
Event_OnSoundFadeInStopped
ref ScriptInvoker EffectSound::Event_OnSoundFadeInStopped = new ScriptInvoker() private
Definition at line 12 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), and Event_OnSoundFadeInStopped().
Event_OnSoundFadeOutStarted
ref ScriptInvoker EffectSound::Event_OnSoundFadeOutStarted = new ScriptInvoker() private
Definition at line 13 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), and Event_OnSoundFadeOutStarted().
Event_OnSoundWaveEnded
ref ScriptInvoker EffectSound::Event_OnSoundWaveEnded = new ScriptInvoker() private
Definition at line 11 of file effectsound.c.
Referenced by Event_OnRegistered(), Event_OnSoundWaveEnded(), Event_OnUnregistered(), and ValidateSoundWave().
Event_OnSoundWaveStarted
ref ScriptInvoker EffectSound::Event_OnSoundWaveStarted = new ScriptInvoker() private
Definition at line 10 of file effectsound.c.
Referenced by Event_OnSoundWaveStarted(), and ValidateSoundWave().
m_SetEnvVariables
protected bool EffectSound::m_SetEnvVariables private
Definition at line 34 of file effectsound.c.
Referenced by SetEnviromentVariables(), SoundLoadEx(), and SoundPlayEx().
m_SoundAutodestroy
protected bool EffectSound::m_SoundAutodestroy private
Definition at line 35 of file effectsound.c.
Referenced by EffectSound(), IsSoundAutodestroy(), and SetAutodestroy().
m_SoundFadeInDuration
protected float EffectSound::m_SoundFadeInDuration private
Definition at line 50 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), SetSoundFadeIn(), SoundWaveValidation(), and ValidateSoundWave().
m_SoundFadeOutDuration
protected float EffectSound::m_SoundFadeOutDuration private
Definition at line 53 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), SetSoundFadeOut(), SoundStop(), and SoundWaveValidation().
m_SoundFadeOutInitVolume
protected float EffectSound::m_SoundFadeOutInitVolume private
Definition at line 54 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), and SoundReset().
m_SoundFadeOutStartTime
protected float EffectSound::m_SoundFadeOutStartTime private
Definition at line 52 of file effectsound.c.
Referenced by SoundReset(), SoundStop(), and ValidateSoundWave().
m_SoundLoop
protected bool EffectSound::m_SoundLoop private
Definition at line 33 of file effectsound.c.
Referenced by SetSoundLoop(), and ValidateSoundWave().
m_SoundObject
protected ref SoundObject EffectSound::m_SoundObject private
Definition at line 22 of file effectsound.c.
Referenced by GetCurrentLocalPosition(), GetCurrentPosition(), SetCurrentLocalPosition(), SetCurrentPosition(), SoundLoadEx(), and SoundPlayEx().
m_SoundObjectBuilder
protected ref SoundObjectBuilder EffectSound::m_SoundObjectBuilder private
Definition at line 21 of file effectsound.c.
Referenced by SoundLoadEx(), and SoundPlayEx().
m_SoundParams
protected ref SoundParams EffectSound::m_SoundParams private
Definition at line 20 of file effectsound.c.
Referenced by IsSoundValid(), SoundLoadEx(), and SoundPlayEx().
m_SoundParent
protected Object EffectSound::m_SoundParent private
Definition at line 30 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), GetCurrentParent(), GetParent(), SetCurrentParent(), and SetParent().
m_SoundSetName
protected string EffectSound::m_SoundSetName private
Definition at line 32 of file effectsound.c.
Referenced by GetDebugName(), GetSoundSet(), SetSoundSet(), SoundError(), SoundLoadEx(), and SoundPlayEx().
m_SoundWaveIsPlaying
protected bool EffectSound::m_SoundWaveIsPlaying private
Definition at line 36 of file effectsound.c.
Referenced by Event_OnSoundWaveEnded(), Event_OnSoundWaveStarted(), IsSoundPlaying(), and SoundReset().
m_SoundWaveKind
protected WaveKind EffectSound::m_SoundWaveKind private
Definition at line 31 of file effectsound.c.
Referenced by EffectSound(), SetSoundWaveKind(), SoundLoadEx(), and SoundPlayEx().
m_SoundWaveLenght
protected float EffectSound::m_SoundWaveLenght private
Definition at line 37 of file effectsound.c.
Referenced by GetSoundWaveLength(), and ValidateSoundWave().
m_SoundWaveObject
protected AbstractWave EffectSound::m_SoundWaveObject private
Definition at line 23 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), SetSoundLoop(), SetSoundMaxVolume(), SetSoundVolume(), SoundPlayEx(), SoundReset(), SoundStop(), UpdateEvents(), and ValidateSoundWave().
m_SoundWaveStarting
protected bool EffectSound::m_SoundWaveStarting private
Definition at line 47 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), SoundStop(), and ValidateSoundWave().
m_SoundWaveStopping
protected bool EffectSound::m_SoundWaveStopping private
Definition at line 48 of file effectsound.c.
Referenced by EffectSound(), Event_OnFrameUpdate(), and SoundStop().
m_SoundWaveTime
protected float EffectSound::m_SoundWaveTime private
Definition at line 40 of file effectsound.c.
Referenced by Event_OnFrameUpdate(), GetSoundWaveTime(), SoundReset(), and SoundStop().
m_SoundWaveVolume
protected float EffectSound::m_SoundWaveVolume private
Definition at line 38 of file effectsound.c.
Referenced by EffectSound(), GetSoundVolume(), SetSoundMaxVolume(), SetSoundVolume(), and SoundReset().
m_SoundWaveVolumeMax
protected float EffectSound::m_SoundWaveVolumeMax private
Definition at line 39 of file effectsound.c.
Referenced by EffectSound(), Event_OnFrameUpdate(), SetSoundMaxVolume(), and SoundReset().