DayzKode: ShockHandler Class Reference
ShockHandler Class Reference
Private Member Functions
void CheckValue (bool forceUpdate)
private void DealShock ()
float GetCurrentShock ()
float GetShock ()
private float LerpVignette (float x, float y, float deltaT)
private float NormalizeShockVal (float shock)
float SetMultiplier (float mult)
void SetShock (float dealtShock)
void ShockHandler (PlayerBase player)
private void ShockHitEffect (float compareBase)
protected void Synchronize ()
void Update (float deltaT)
Private Attributes
private const int HEAVY_SHOCK_HIT = 100
private const int INTENSITY_FACTOR = 1
private const int LIGHT_SHOCK_HIT = 33
protected float m_CumulatedShock
private float m_LerpRes
protected ref Param1< float > m_Param
protected PlayerBase m_Player
private float m_PrevVignette
private float m_PulseTimer
protected float m_Shock
private float m_ShockMultiplier = 1
protected float m_ShockValueMax
protected float m_ShockValueThreshold
private float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
private const int MID_SHOCK_HIT = 67
private const float PULSE_AMPLITUDE = 0.05
private const float PULSE_PERIOD = 0.5
protected const float UPDATE_THRESHOLD = 3
const float VALUE_CHECK_INTERVAL = 0.95
Detailed Description
Definition at line 1 of file shockhandler.c.
Constructor & Destructor Documentation
ShockHandler()
void ShockHandler::ShockHandler (PlayerBase player) inline private
Definition at line 28 of file shockhandler.c.
    {
        m_Player = player;
        m_Player.m_CurrentShock = m_Player.GetMaxHealth("", "Shock");
        m_PrevVignette = m_Player.m_CurrentShock * 0.01; //Equivalent to divided by 100
        m_ShockValueMax = m_Player.GetMaxHealth("", "Shock");
        m_ShockValueThreshold = m_ShockValueMax * 0.95;
        m_Param = new Param1<float>(0);
    }
References m_Param, m_Player, m_PrevVignette, m_ShockValueMax, and m_ShockValueThreshold.
Member Function Documentation
CheckValue()
void ShockHandler::CheckValue (bool forceUpdate) inline private
Definition at line 120 of file shockhandler.c.
    {
        m_CumulatedShock += m_Shock; // increment on both client and server
        if ( forceUpdate )
            m_PrevVignette = NormalizeShockVal( m_Player.m_CurrentShock );
        if ( GetGame().IsServer() )
        {
            m_Player.m_CurrentShock = m_Player.GetHealth("", "Shock");
            /*
            if (m_Player.m_CurrentShock <= 0)
                m_Player.SetHealthMax("", "Shock");
            */
            if ( m_CumulatedShock >= UPDATE_THRESHOLD || forceUpdate )
            {
                m_CumulatedShock *= m_ShockMultiplier;
                DealShock();
                m_CumulatedShock = 0;
                m_Shock = 0;
                Synchronize();
            }
        }
    }
References DealShock(), GetGame(), m_CumulatedShock, m_Player, m_PrevVignette, m_Shock, m_ShockMultiplier, NormalizeShockVal(), Synchronize(), and UPDATE_THRESHOLD.
Referenced by SetShock(), and Update().
DealShock()
private void ShockHandler::DealShock () inline private
Definition at line 113 of file shockhandler.c.
    {
        if ( GetGame().IsServer() )
            m_Player.GiveShock( -m_CumulatedShock );
    }
References GetGame(), m_CumulatedShock, and m_Player.
Referenced by CheckValue().
GetCurrentShock()
float ShockHandler::GetCurrentShock () inline private
Definition at line 96 of file shockhandler.c.
    {
        return m_Player.m_CurrentShock;
    }
References m_Player.
GetShock()
float ShockHandler::GetShock () inline private
Definition at line 101 of file shockhandler.c.
    {
        return m_Shock;
    }
References m_Shock.
LerpVignette()
private float ShockHandler::LerpVignette (float x, float y, float deltaT) inline private
Definition at line 165 of file shockhandler.c.
    {
        float output;
        output = Math.Lerp( x, y, deltaT );
        return output;
    }
References Math::Lerp(), x, and y.
Referenced by Update().
NormalizeShockVal()
private float ShockHandler::NormalizeShockVal (float shock) inline private
Definition at line 158 of file shockhandler.c.
    {
        float base = m_Player.GetMaxHealth("", "Shock") * INTENSITY_FACTOR;
        float normShock = shock / base;
        return normShock;
    }
References INTENSITY_FACTOR, and m_Player.
Referenced by CheckValue(), and Update().
SetMultiplier()
float ShockHandler::SetMultiplier (float mult) inline private
Definition at line 152 of file shockhandler.c.
    {
        m_ShockMultiplier = mult;
        return m_ShockMultiplier;
    }
References m_ShockMultiplier.
SetShock()
void ShockHandler::SetShock (float dealtShock) inline private
Definition at line 106 of file shockhandler.c.
    {
        m_Shock += dealtShock;
        CheckValue( false );
    }
References CheckValue(), and m_Shock.
ShockHitEffect()
private void ShockHandler::ShockHitEffect (float compareBase) inline private
Definition at line 173 of file shockhandler.c.
    {
        float shockDifference = compareBase - m_Player.m_CurrentShock;
        //Print(shockDifference);
        if ( shockDifference >= UPDATE_THRESHOLD )
        {
            if ( m_CumulatedShock < 25 )
                m_Player.SpawnShockEffect( MiscGameplayFunctions.Normalize( LIGHT_SHOCK_HIT, 100 ) );
            else if ( m_CumulatedShock < 50 )
                m_Player.SpawnShockEffect( MiscGameplayFunctions.Normalize( MID_SHOCK_HIT, 100 ) );
            else
                m_Player.SpawnShockEffect( MiscGameplayFunctions.Normalize( HEAVY_SHOCK_HIT, 100 ) );
        }
    }
References HEAVY_SHOCK_HIT, LIGHT_SHOCK_HIT, m_CumulatedShock, m_Player, MID_SHOCK_HIT, and UPDATE_THRESHOLD.
Referenced by Update().
Synchronize()
protected void ShockHandler::Synchronize () inline private
Definition at line 147 of file shockhandler.c.
    {
        DayZPlayerSyncJunctures.SendShock( m_Player, m_Player.m_CurrentShock );
    }
References m_Player, and DayZPlayerSyncJunctures::SendShock().
Referenced by CheckValue().
Update()
void ShockHandler::Update (float deltaT) inline private
Definition at line 38 of file shockhandler.c.
    {
        m_TimeSinceLastTick += deltaT;
        m_PulseTimer += deltaT;
        if ( GetGame().IsClient() )
        {
            //Deactivate tunnel vignette when player falls unconscious
            if ( m_Player.IsUnconscious() )
            {
                PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Stop();
                return;
            }
            //Deactivate if above visible threshold (also stops "zero bobbing" being sent all the time
            if ( m_Player.m_CurrentShock >= m_ShockValueThreshold)
            {
                PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Stop();
                return;
            }
            //Add bobbing to create pulsing effect
            float val = 0.0;
            if ( m_Player.m_CurrentShock > m_ShockValueMax * 0.8)
                val = MiscGameplayFunctions.Bobbing( PULSE_PERIOD, PULSE_AMPLITUDE, m_PulseTimer );
            float val_adjusted;
            if ( m_Player.m_CurrentShock != (m_PrevVignette * 100) )
            {
                //Interpolate between previous level and currently synchronized shock level
                m_LerpRes = LerpVignette( m_PrevVignette, NormalizeShockVal(m_Player.m_CurrentShock), m_TimeSinceLastTick );
                val_adjusted = 1 - Easing.EaseInQuart(m_LerpRes) + val;
            }
            else
            {
                val_adjusted = 1 - Easing.EaseInQuart( NormalizeShockVal(m_Player.m_CurrentShock)) + val;
            }
            m_Param.param1 = val_adjusted;
            PPERequesterBank.GetRequester(PPERequester_TunnelVisionEffects).Start(m_Param);
        }
        if ( m_TimeSinceLastTick > VALUE_CHECK_INTERVAL )
        {
            //Play the shock hit event (multiply prevVignette by 100 to "Un-Normalize" value)
            if ( GetGame().IsClient() )
            {
                ShockHitEffect( m_PrevVignette * 100 );
                m_PrevVignette = m_Player.m_CurrentShock * 0.01;
            }
            CheckValue( false );
            m_TimeSinceLastTick = 0;
        }
    }
References CheckValue(), Easing::EaseInQuart(), GetGame(), LerpVignette(), m_LerpRes, m_Param, m_Player, m_PrevVignette, m_PulseTimer, m_ShockValueMax, m_ShockValueThreshold, m_TimeSinceLastTick, NormalizeShockVal(), PULSE_AMPLITUDE, PULSE_PERIOD, ShockHitEffect(), and VALUE_CHECK_INTERVAL.
Member Data Documentation
HEAVY_SHOCK_HIT
private const int ShockHandler::HEAVY_SHOCK_HIT = 100 private
Definition at line 18 of file shockhandler.c.
Referenced by ShockHitEffect().
INTENSITY_FACTOR
private const int ShockHandler::INTENSITY_FACTOR = 1 private
Definition at line 19 of file shockhandler.c.
Referenced by NormalizeShockVal().
LIGHT_SHOCK_HIT
private const int ShockHandler::LIGHT_SHOCK_HIT = 33 private
Definition at line 16 of file shockhandler.c.
Referenced by ShockHitEffect().
m_CumulatedShock
protected float ShockHandler::m_CumulatedShock private
Definition at line 10 of file shockhandler.c.
Referenced by CheckValue(), DealShock(), and ShockHitEffect().
m_LerpRes
private float ShockHandler::m_LerpRes private
Definition at line 14 of file shockhandler.c.
Referenced by Update().
m_Param
protected ref Param1<float> ShockHandler::m_Param private
Definition at line 26 of file shockhandler.c.
Referenced by ShockHandler(), and Update().
m_Player
protected PlayerBase ShockHandler::m_Player private
Definition at line 6 of file shockhandler.c.
Referenced by CheckValue(), DealShock(), GetCurrentShock(), NormalizeShockVal(), ShockHandler(), ShockHitEffect(), Synchronize(), and Update().
m_PrevVignette
private float ShockHandler::m_PrevVignette private
Definition at line 13 of file shockhandler.c.
Referenced by CheckValue(), ShockHandler(), and Update().
m_PulseTimer
private float ShockHandler::m_PulseTimer private
Definition at line 24 of file shockhandler.c.
Referenced by Update().
m_Shock
protected float ShockHandler::m_Shock private
Definition at line 3 of file shockhandler.c.
Referenced by CheckValue(), GetShock(), and SetShock().
m_ShockMultiplier
private float ShockHandler::m_ShockMultiplier = 1 private
Definition at line 12 of file shockhandler.c.
Referenced by CheckValue(), and SetMultiplier().
m_ShockValueMax
protected float ShockHandler::m_ShockValueMax private
Definition at line 4 of file shockhandler.c.
Referenced by ShockHandler(), and Update().
m_ShockValueThreshold
protected float ShockHandler::m_ShockValueThreshold private
Definition at line 5 of file shockhandler.c.
Referenced by ShockHandler(), and Update().
m_TimeSinceLastTick
private float ShockHandler::m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Definition at line 11 of file shockhandler.c.
Referenced by Update().
MID_SHOCK_HIT
private const int ShockHandler::MID_SHOCK_HIT = 67 private
Definition at line 17 of file shockhandler.c.
Referenced by ShockHitEffect().
PULSE_AMPLITUDE
private const float ShockHandler::PULSE_AMPLITUDE = 0.05 private
Definition at line 23 of file shockhandler.c.
Referenced by Update().
PULSE_PERIOD
private const float ShockHandler::PULSE_PERIOD = 0.5 private
Definition at line 22 of file shockhandler.c.
Referenced by Update().
UPDATE_THRESHOLD
protected const float ShockHandler::UPDATE_THRESHOLD = 3 private
Definition at line 8 of file shockhandler.c.
Referenced by CheckValue(), and ShockHitEffect().
VALUE_CHECK_INTERVAL
const float ShockHandler::VALUE_CHECK_INTERVAL = 0.95 private
Definition at line 9 of file shockhandler.c.
Referenced by Update().