DayzKode: ActionViewOptics Class Reference
ActionViewOptics Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionViewOptics ()
bool CanWork (ItemBase item)
override void CreateConditionComponents ()
void EnterOptics (ItemOptics optic, PlayerBase player)
void ExitOptics (ItemOptics optic, PlayerBase player)
override bool HasProgress ()
override bool HasTarget ()
override bool IsFullBody (PlayerBase player)
override void OnEndAnimationLoopClient (ActionData action_data)
override void OnEndAnimationLoopServer (ActionData action_data)
override void OnEndClient (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actionviewoptics.c.
Constructor & Destructor Documentation
ActionViewOptics()
void ActionViewOptics::ActionViewOptics () inline private
Definition at line 3 of file actionviewoptics.c.
    {
        m_CallbackClass = ActionRaiseAndViewCB;
        m_CommandUID = DayZPlayerConstants.CMD_GESTUREFB_LOOKOPTICS;
        m_CommandUIDProne = DayZPlayerConstants.CMD_GESTUREFB_LOOKOPTICS;
        m_Text = "#Look_Through";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionViewOptics::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, item) && !optic.IsInOptics() && !player.IsNVGLowered() )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
ActionConditionContinue()
override bool ActionViewOptics::ActionConditionContinue (ActionData action_data) inline private
Definition at line 42 of file actionviewoptics.c.
    {
        return true;
    }
CanWork()
bool ActionViewOptics::CanWork (ItemBase item) inline private
Definition at line 107 of file actionviewoptics.c.
    {
        if ( !item.HasEnergyManager() )
        {
            return true;
        }
        else if ( item.GetCompEM() && item.GetCompEM().CanWork() )
        {
            return true;
        }
        return false;
    }
CreateConditionComponents()
override void ActionViewOptics::CreateConditionComponents () inline private
Definition at line 11 of file actionviewoptics.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
EnterOptics()
void ActionViewOptics::EnterOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 121 of file actionviewoptics.c.
    {
        player.SetIronsights(false);
        player.SetHandheldOpticsInUse(true);
        player.SetOptics(true);
        optic.EnterOptics();
        optic.HideSelection("hide");
        if (optic.HasEnergyManager())
            optic.GetCompEM().SwitchOn();
        player.GetAimingModel().SetAimNoiseAllowed(false);
    }
References ItemOptics::HideSelection().
Referenced by OnStartAnimationLoopClient(), and OnStartAnimationLoopServer().
ExitOptics()
void ActionViewOptics::ExitOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 133 of file actionviewoptics.c.
    {
        optic.ShowSelection("hide");
        player.ExitSights();
        player.SetHandheldOpticsInUse(false);
        if (optic.HasEnergyManager())
            optic.GetCompEM().SwitchOff();
        player.GetAimingModel().SetAimNoiseAllowed(true);
    }
References ItemOptics::ShowSelection().
Referenced by OnEndAnimationLoopClient(), OnEndAnimationLoopServer(), OnEndClient(), and OnEndServer().
HasProgress()
override bool ActionViewOptics::HasProgress () inline private
Definition at line 22 of file actionviewoptics.c.
    {
        return false;
    }
HasTarget()
override bool ActionViewOptics::HasTarget () inline private
Definition at line 27 of file actionviewoptics.c.
    {
        return false;
    }
IsFullBody()
override bool ActionViewOptics::IsFullBody (PlayerBase player) inline private
Definition at line 17 of file actionviewoptics.c.
    {
        return true;
    }
OnEndAnimationLoopClient()
override void ActionViewOptics::OnEndAnimationLoopClient (ActionData action_data) inline private
Definition at line 89 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) )
        {
            ExitOptics(optic, action_data.m_Player);
        }
    }
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndAnimationLoopServer()
override void ActionViewOptics::OnEndAnimationLoopServer (ActionData action_data) inline private
Definition at line 98 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) )
        {
            ExitOptics(optic, action_data.m_Player);
        }
    }
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndClient()
override void ActionViewOptics::OnEndClient (ActionData action_data) inline private
Definition at line 71 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) && optic.IsInOptics() )
        {
            ExitOptics(optic, action_data.m_Player);
        }
    }
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnEndServer()
override void ActionViewOptics::OnEndServer (ActionData action_data) inline private
Definition at line 80 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) && optic.IsInOptics() )
        {
            ExitOptics(optic, action_data.m_Player);
        }
    }
References Class::CastTo(), ExitOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnStartAnimationLoopClient()
override void ActionViewOptics::OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 59 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) )
        {
            if (!optic.IsInOptics())
            {
                EnterOptics(optic, action_data.m_Player);
            }
        }
    }
References Class::CastTo(), EnterOptics(), ActionData::m_MainItem, and ActionData::m_Player.
OnStartAnimationLoopServer()
override void ActionViewOptics::OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 47 of file actionviewoptics.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, action_data.m_MainItem) )
        {
            if (!optic.IsInOptics())
            {
                EnterOptics(optic, action_data.m_Player);
            }
        }
    }
References Class::CastTo(), EnterOptics(), ActionData::m_MainItem, and ActionData::m_Player.