DayzKode: OverheatingParticle Class Reference
OverheatingParticle Class Reference
Private Member Functions
float GetOverheatingLimitMax ()
float GetOverheatingLimitMin ()
Particle GetParticle ()
int GetParticleID ()
vector GetParticleOri ()
Object GetParticleParent ()
vector GetParticlePos ()
void RegisterParticle (Particle p)
void SetOverheatingLimitMax (float max)
void SetOverheatingLimitMin (float min)
void SetParticleParams (int particle_id, Object parent, vector local_pos, vector local_ori)
Private Attributes
vector m_LocalOri
vector m_LocalPos
float m_OverheatingLimitMax
float m_OverheatingLimitMin
Object m_Parent
Particle m_Particle
int m_ParticleID
Detailed Description
Definition at line 381 of file weaponparticles.c.
Member Function Documentation
GetOverheatingLimitMax()
float OverheatingParticle::GetOverheatingLimitMax () inline private
Definition at line 417 of file weaponparticles.c.
    {
        return m_OverheatingLimitMax;
    }
References m_OverheatingLimitMax.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetOverheatingLimitMin()
float OverheatingParticle::GetOverheatingLimitMin () inline private
Definition at line 412 of file weaponparticles.c.
    {
        return m_OverheatingLimitMin;
    }
References m_OverheatingLimitMin.
Referenced by InventoryItem::UpdateAllOverheatingParticles().
GetParticle()
Particle OverheatingParticle::GetParticle () inline private
Definition at line 397 of file weaponparticles.c.
    {
        return m_Particle;
    }
References m_Particle.
Referenced by InventoryItem::KillAllOverheatingParticles(), and InventoryItem::UpdateAllOverheatingParticles().
GetParticleID()
int OverheatingParticle::GetParticleID () inline private
Definition at line 430 of file weaponparticles.c.
    {
        return m_ParticleID;
    }
References m_ParticleID.
GetParticleOri()
vector OverheatingParticle::GetParticleOri () inline private
Definition at line 445 of file weaponparticles.c.
    {
        return m_LocalOri;
    }
References m_LocalOri.
GetParticleParent()
Object OverheatingParticle::GetParticleParent () inline private
Definition at line 435 of file weaponparticles.c.
    {
        return m_Parent;
    }
References m_Parent.
GetParticlePos()
vector OverheatingParticle::GetParticlePos () inline private
Definition at line 440 of file weaponparticles.c.
    {
        return m_LocalPos;
    }
References m_LocalPos.
RegisterParticle()
void OverheatingParticle::RegisterParticle (Particle p) inline private
Definition at line 392 of file weaponparticles.c.
    {
        m_Particle = p;
    }
References m_Particle.
Referenced by InventoryItem::RegisterOverheatingParticle(), and InventoryItem::UpdateAllOverheatingParticles().
SetOverheatingLimitMax()
void OverheatingParticle::SetOverheatingLimitMax (float max) inline private
Definition at line 407 of file weaponparticles.c.
    {
        m_OverheatingLimitMax = max;
    }
References m_OverheatingLimitMax.
Referenced by InventoryItem::RegisterOverheatingParticle().
SetOverheatingLimitMin()
void OverheatingParticle::SetOverheatingLimitMin (float min) inline private
Definition at line 402 of file weaponparticles.c.
    {
        m_OverheatingLimitMin = min;
    }
References m_OverheatingLimitMin.
Referenced by InventoryItem::RegisterOverheatingParticle().
SetParticleParams()
void OverheatingParticle::SetParticleParams (int particle_id, Object parent, vector local_pos, vector local_ori) inline private
Definition at line 422 of file weaponparticles.c.
    {
        m_ParticleID = particle_id;
        m_Parent = parent;
        m_LocalPos = local_pos;
        m_LocalOri = local_ori;
    }
References m_LocalOri, m_LocalPos, m_Parent, m_ParticleID, and particle_id.
Referenced by InventoryItem::RegisterOverheatingParticle().
Member Data Documentation
m_LocalOri
vector OverheatingParticle::m_LocalOri private
Definition at line 387 of file weaponparticles.c.
Referenced by GetParticleOri(), and SetParticleParams().
m_LocalPos
vector OverheatingParticle::m_LocalPos private
Definition at line 386 of file weaponparticles.c.
Referenced by GetParticlePos(), and SetParticleParams().
m_OverheatingLimitMax
float OverheatingParticle::m_OverheatingLimitMax private
Definition at line 390 of file weaponparticles.c.
Referenced by GetOverheatingLimitMax(), and SetOverheatingLimitMax().
m_OverheatingLimitMin
float OverheatingParticle::m_OverheatingLimitMin private
Definition at line 389 of file weaponparticles.c.
Referenced by GetOverheatingLimitMin(), and SetOverheatingLimitMin().
m_Parent
Object OverheatingParticle::m_Parent private
Definition at line 385 of file weaponparticles.c.
Referenced by GetParticleParent(), and SetParticleParams().
m_Particle
Particle OverheatingParticle::m_Particle private
Definition at line 383 of file weaponparticles.c.
Referenced by GetParticle(), and RegisterParticle().
m_ParticleID
int OverheatingParticle::m_ParticleID private
Definition at line 384 of file weaponparticles.c.
Referenced by GetParticleID(), and SetParticleParams().