DayzKode: DayZPlayerImplementFallDamage Class Reference
DayZPlayerImplementFallDamage Class Reference
Private Member Functions
float DamageCoef (float pHeight)
damage coef calculated from height
void DayZPlayerImplementFallDamage (DayZPlayer pPlayer)
void HandleFallDamage (float pHeight)
handle fall damage
Private Attributes
const string FD_AMMO = "FallDamage"
ammo type used for damaging
const float FD_DMG_FROM_HEIGHT = 2.5
damage will not be taken into account bellow this HeightToDamage
const float FD_MAX_DMG_AT_HEIGHT = 15
height where player gets 100% damage
const float FD_MAX_HEIGHT_LEG_BREAK = 8
height where legs break most of the time
DayZPlayer m_Player
Detailed Description
Definition at line 1 of file dayzplayerimplementfalldamage.c.
Constructor & Destructor Documentation
DayZPlayerImplementFallDamage()
void DayZPlayerImplementFallDamage::DayZPlayerImplementFallDamage (DayZPlayer pPlayer) inline private
Definition at line 10 of file dayzplayerimplementfalldamage.c.
    {
        m_Player    = pPlayer;
    }
References m_Player.
Member Function Documentation
DamageCoef()
float DayZPlayerImplementFallDamage::DamageCoef (float pHeight) inline private
damage coef calculated from height
Definition at line 16 of file dayzplayerimplementfalldamage.c.
    {
        if (pHeight >= FD_MAX_DMG_AT_HEIGHT)
            return 100;
        return (pHeight - FD_DMG_FROM_HEIGHT);
    }
References FD_DMG_FROM_HEIGHT, and FD_MAX_DMG_AT_HEIGHT.
Referenced by HandleFallDamage().
HandleFallDamage()
void DayZPlayerImplementFallDamage::HandleFallDamage (float pHeight) inline private
handle fall damage
no dmg height
updates injury state of player immediately
Definition at line 25 of file dayzplayerimplementfalldamage.c.
    {
        if (GetGame().IsServer())
        {
            if (pHeight <= FD_DMG_FROM_HEIGHT)
                return;
            vector posMS = m_Player.WorldToModel(m_Player.GetPosition());
            float normalizedHeight = MiscGameplayFunctions.Normalize(pHeight, FD_MAX_HEIGHT_LEG_BREAK); //Normalize the height player fell from
            float dmg; //Damage dealt to leg
            //This uses a quadratic EaseInOut function ro deal damage to legs
            /*if (normalizedHeight < 0.5)
                dmg = 2*Math.Pow(normalizedHeight,2);
            else
                dmg = 1 - Math.Pow(-2*normalizedHeight+2,2)/2;*/
            dmg = Easing.EaseInOutQuart(normalizedHeight);
            //We multiply by 100 to "un normalize" value and multiply by a random factor to deal extra damage to legs
            dmg = (dmg * 100) * Math.RandomFloatInclusive(0.8, 1.5);
            if ( pHeight >= FD_MAX_HEIGHT_LEG_BREAK )
                dmg += 100; //Simply adding 100 should be enough to break legs 100% of time without calling GetHealth method
            PlayerBase.Cast(m_Player).DamageAllLegs(dmg);
            //Deal global damage when falling
            m_Player.ProcessDirectDamage( DT_CUSTOM, m_Player, "", FD_AMMO, posMS, DamageCoef(pHeight) );
            PlayerBase pb = PlayerBase.Cast(m_Player);
            if (pb) pb.ForceUpdateInjuredState();
        }
    }
References DamageCoef(), Easing::EaseInOutQuart(), FD_AMMO, FD_DMG_FROM_HEIGHT, FD_MAX_HEIGHT_LEG_BREAK, GetGame(), m_Player, and Math::RandomFloatInclusive().
Referenced by CommandHandler().
Member Data Documentation
FD_AMMO
const string DayZPlayerImplementFallDamage::FD_AMMO = "FallDamage" private
ammo type used for damaging
Definition at line 3 of file dayzplayerimplementfalldamage.c.
Referenced by HandleFallDamage().
FD_DMG_FROM_HEIGHT
const float DayZPlayerImplementFallDamage::FD_DMG_FROM_HEIGHT = 2.5 private
damage will not be taken into account bellow this HeightToDamage
Definition at line 4 of file dayzplayerimplementfalldamage.c.
Referenced by CommandHandler(), DamageCoef(), and HandleFallDamage().
FD_MAX_DMG_AT_HEIGHT
const float DayZPlayerImplementFallDamage::FD_MAX_DMG_AT_HEIGHT = 15 private
height where player gets 100% damage
Definition at line 5 of file dayzplayerimplementfalldamage.c.
Referenced by DamageCoef().
FD_MAX_HEIGHT_LEG_BREAK
const float DayZPlayerImplementFallDamage::FD_MAX_HEIGHT_LEG_BREAK = 8 private
height where legs break most of the time
Definition at line 6 of file dayzplayerimplementfalldamage.c.
Referenced by HandleFallDamage().
m_Player
DayZPlayer DayZPlayerImplementFallDamage::m_Player private
Definition at line 8 of file dayzplayerimplementfalldamage.c.
Referenced by DayZPlayerImplementFallDamage(), and HandleFallDamage().