DayzKode: NotifierBase Class Reference
NotifierBase Class Reference
Private Member Functions
void AddToCyclicBuffer (float value)
protected int CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh)
protected eBadgeLevel DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3)
protected void DisplayBadge ()
void DisplayTendency (float delta)
float GetDeltaAvaraged ()
string GetName ()
int GetNotifierType ()
protected float GetObservedValue ()
VirtualHud GetVirtualHud ()
protected void HideBadge ()
bool IsActive ()
bool IsTimeToTick (int current_time)
void NotifierBase (NotifiersManager manager)
void OnTick (float current_time)
float ReadFromCyclicBuffer (int index)
void SetActive (bool state)
void SmoothOutFloatValues (array< float > values)
Private Attributes
bool m_Active
float m_DeltaT
bool m_FirstPass = true
float m_LastMA
float m_LastTendency
NotifiersManager m_Manager
PluginPlayerStatus m_ModulePlayerStatus
PlayerBase m_Player
bool m_ShowTendency
float m_TendencyBuffer [TENDENCY_BUFFER_SIZE]
int m_TendencyBufferSize = 3
int m_TendencyBufferWriteIterator
int m_TickInterval
int m_TickIntervalLastTick
ref Timer m_Timer1
int m_Type
const int TENDENCY_BUFFER_SIZE = 30
Detailed Description
Definition at line 1 of file notifierbase.c.
Constructor & Destructor Documentation
NotifierBase()
void NotifierBase::NotifierBase (NotifiersManager manager) inline private
Definition at line 31 of file notifierbase.c.
    {
        //m_Timer1 = new Timer();
        m_ModulePlayerStatus = PluginPlayerStatus.Cast(GetPlugin(PluginPlayerStatus));
        m_Active = true;
        m_Manager = manager;
        m_Player = manager.GetPlayer();
        m_TickInterval = 1000;
        manager.RegisterItself(GetNotifierType(), this);
    }
References GetNotifierType(), GetPlugin(), m_Active, m_Manager, m_ModulePlayerStatus, m_Player, and m_TickInterval.
Member Function Documentation
AddToCyclicBuffer()
void NotifierBase::AddToCyclicBuffer (float value) inline private
Definition at line 79 of file notifierbase.c.
    {
        m_TendencyBuffer[m_TendencyBufferWriteIterator] = value;
        m_TendencyBufferWriteIterator++;
        if( m_TendencyBufferWriteIterator == m_TendencyBufferSize )
        {
            m_TendencyBufferWriteIterator = 0;
            m_ShowTendency = true;
        }
    }
References m_ShowTendency, m_TendencyBuffer, m_TendencyBufferSize, and m_TendencyBufferWriteIterator.
Referenced by OnTick().
CalculateTendency()
protected int NotifierBase::CalculateTendency (float delta, float inctresholdlow, float inctresholdmed, float inctresholdhigh, float dectresholdlow, float dectresholdmed, float dectresholdhigh) inline private
Definition at line 171 of file notifierbase.c.
    {
        int tendency = TENDENCY_STABLE;
        if ( delta > inctresholdlow )   tendency = TENDENCY_INC_LOW;
        if ( delta > inctresholdmed )   tendency = TENDENCY_INC_MED;
        if ( delta > inctresholdhigh )  tendency = TENDENCY_INC_HIGH;
        if ( delta < dectresholdlow )   tendency = TENDENCY_DEC_LOW;
        if ( delta < dectresholdmed )   tendency = TENDENCY_DEC_MED;
        if ( delta < dectresholdhigh )  tendency = TENDENCY_DEC_HIGH;
        //Print(" " + delta + " tendency:  " + tendency +" " + this);
        return tendency;
    }
References TENDENCY_DEC_HIGH, TENDENCY_DEC_LOW, TENDENCY_DEC_MED, TENDENCY_INC_HIGH, TENDENCY_INC_LOW, TENDENCY_INC_MED, and TENDENCY_STABLE.
Referenced by BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), and WarmthNotfr::DisplayTendency().
DetermineBadgeLevel()
protected eBadgeLevel NotifierBase::DetermineBadgeLevel (float value, float lvl_1, float lvl_2, float lvl_3) inline private
Definition at line 185 of file notifierbase.c.
    {
        eBadgeLevel level = eBadgeLevel.NONE;
        if ( value > lvl_1 )    level = eBadgeLevel.FIRST;
        if ( value > lvl_2 )    level = eBadgeLevel.SECOND;
        if ( value > lvl_3 )    level = eBadgeLevel.THIRD;
        return  level;
    }
Referenced by StuffedNotfr::DisplayBadge().
DisplayBadge()
protected void NotifierBase::DisplayBadge () inline private
Definition at line 195 of file notifierbase.c.
    {
    }
Referenced by OnTick().
DisplayTendency()
void NotifierBase::DisplayTendency (float delta) inline private
Definition at line 75 of file notifierbase.c.
    {
    }
Referenced by OnTick().
GetDeltaAvaraged()
float NotifierBase::GetDeltaAvaraged () inline private
Definition at line 100 of file notifierbase.c.
    {
        array<float> values = new array<float>;
        for(int i = 0; i < m_TendencyBufferSize; i++)
        {
            values.Insert(ReadFromCyclicBuffer(i));
        }
        //SmoothOutFloatValues(values);
        //--------------------------------------------------------------------------
        float values_sum = 0;
        //PrintString("----------------------------");
        //PrintString("tendency:" + this.ClassName() );
        for(i = 0; i < values.Count(); i++)
        {
            float value = values.Get(i);
            values_sum += value;
            //PrintString( value.ToString() );
        }
        float sma = values_sum / m_TendencyBufferSize;
        if( m_FirstPass )
        {
            m_LastMA = sma;
            m_FirstPass = false;
        }
        float tnd = sma - m_LastMA;
        m_LastMA = sma;
        /*
        PrintString(GetName()+" tendency:" + tnd.ToString() );
        PrintString("----------------------------");
        */
        return tnd;
        //--------------------------------------------------------------------------
    }
References m_FirstPass, m_LastMA, m_TendencyBufferSize, and ReadFromCyclicBuffer().
Referenced by OnTick().
GetName()
string NotifierBase::GetName () inline private
Definition at line 59 of file notifierbase.c.
    {
        return this.ClassName() + " Notifier";
    }
GetNotifierType()
int NotifierBase::GetNotifierType () inline private
Definition at line 54 of file notifierbase.c.
    {
        return m_Type;
    }
References m_Type.
Referenced by NotifierBase().
GetObservedValue()
protected float NotifierBase::GetObservedValue () inline private
Definition at line 203 of file notifierbase.c.
    {
        return 0;
    }
Referenced by OnTick().
GetVirtualHud()
VirtualHud NotifierBase::GetVirtualHud () inline private
Definition at line 49 of file notifierbase.c.
    {
        return m_Player.GetVirtualHud();
    }
References m_Player.
Referenced by BleedingNotfr::DisplayBadge(), FracturedLegNotfr::DisplayBadge(), HeartbeatNotfr::DisplayBadge(), PillsNotfr::DisplayBadge(), SickNotfr::DisplayBadge(), StuffedNotfr::DisplayBadge(), WetnessNotfr::DisplayBadge(), BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), WarmthNotfr::DisplayTendency(), BleedingNotfr::HideBadge(), FracturedLegNotfr::HideBadge(), HeartbeatNotfr::HideBadge(), PillsNotfr::HideBadge(), SickNotfr::HideBadge(), StuffedNotfr::HideBadge(), and WetnessNotfr::HideBadge().
HideBadge()
protected void NotifierBase::HideBadge () inline private
Definition at line 199 of file notifierbase.c.
    {
    }
Referenced by SetActive().
IsActive()
bool NotifierBase::IsActive () inline private
Definition at line 64 of file notifierbase.c.
    {
        return m_Active;
    }
References m_Active.
IsTimeToTick()
bool NotifierBase::IsTimeToTick (int current_time) inline private
Definition at line 43 of file notifierbase.c.
    {
        return ( current_time > m_TickIntervalLastTick + m_TickInterval );
    }
References m_TickInterval, and m_TickIntervalLastTick.
OnTick()
void NotifierBase::OnTick (float current_time) inline private
Definition at line 156 of file notifierbase.c.
    {
        //------------
        /*
        float time = GetGame().GetTime();
        Print("ticking notifier "+ this.ClassName() +" for player " + m_Player.ToString() + " at time:" + time.ToString());
        */
        //------------
        m_TickIntervalLastTick = current_time;
        DisplayBadge();
        AddToCyclicBuffer( GetObservedValue() );
        if (m_ShowTendency) DisplayTendency( GetDeltaAvaraged() );
    }
References AddToCyclicBuffer(), DisplayBadge(), DisplayTendency(), GetDeltaAvaraged(), GetObservedValue(), m_ShowTendency, and m_TickIntervalLastTick.
ReadFromCyclicBuffer()
float NotifierBase::ReadFromCyclicBuffer (int index) inline private
Definition at line 90 of file notifierbase.c.
    {
        int indx = m_TendencyBufferWriteIterator + index;
        if( indx >= m_TendencyBufferSize)
        {
            indx = indx - m_TendencyBufferSize;
        }
        return m_TendencyBuffer[indx];
    }
References m_TendencyBuffer, m_TendencyBufferSize, and m_TendencyBufferWriteIterator.
Referenced by GetDeltaAvaraged().
SetActive()
void NotifierBase::SetActive (bool state) inline private
Definition at line 69 of file notifierbase.c.
    {
        m_Active = state;
        if ( !state ) HideBadge();
    }
References HideBadge(), and m_Active.
Referenced by ActivateByType(), and DeactivateByType().
SmoothOutFloatValues()
void NotifierBase::SmoothOutFloatValues (array< float > values) inline private
Definition at line 140 of file notifierbase.c.
    {
        float value1;
        float value2;
        for(int i = 0; i < values.Count() - 1; i++)
        {
            value1 = values.Get(i);
            value2 = values.Get(i + 1);
            float average = (value1 + value2) / 2;
            values.Set(i, average);
            values.Set(i + 1, average);
        }
        int index = values.Count() - 1;
        values.Set(index, value2);
    }
Member Data Documentation
m_Active
bool NotifierBase::m_Active private
Definition at line 12 of file notifierbase.c.
Referenced by BleedingNotfr::BleedingNotfr(), FeverNotfr::FeverNotfr(), FracturedLegNotfr::FracturedLegNotfr(), HeartbeatNotfr::HeartbeatNotfr(), IsActive(), NotifierBase(), PillsNotfr::PillsNotfr(), SetActive(), SickNotfr::SickNotfr(), StuffedNotfr::StuffedNotfr(), and WetnessNotfr::WetnessNotfr().
m_DeltaT
float NotifierBase::m_DeltaT private
Definition at line 4 of file notifierbase.c.
m_FirstPass
bool NotifierBase::m_FirstPass = true private
Definition at line 26 of file notifierbase.c.
Referenced by GetDeltaAvaraged().
m_LastMA
float NotifierBase::m_LastMA private
Definition at line 25 of file notifierbase.c.
Referenced by GetDeltaAvaraged().
m_LastTendency
float NotifierBase::m_LastTendency private
Definition at line 24 of file notifierbase.c.
m_Manager
NotifiersManager NotifierBase::m_Manager private
Definition at line 8 of file notifierbase.c.
Referenced by NotifierBase().
m_ModulePlayerStatus
PluginPlayerStatus NotifierBase::m_ModulePlayerStatus private
Definition at line 29 of file notifierbase.c.
Referenced by NotifierBase().
m_Player
PlayerBase NotifierBase::m_Player private
Definition at line 6 of file notifierbase.c.
Referenced by HeartbeatNotfr::DisplayBadge(), StuffedNotfr::DisplayBadge(), ThirstNotfr::DisplayBadge(), BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), BloodNotfr::GetObservedValue(), HealthNotfr::GetObservedValue(), HungerNotfr::GetObservedValue(), ThirstNotfr::GetObservedValue(), WarmthNotfr::GetObservedValue(), GetVirtualHud(), and NotifierBase().
m_ShowTendency
bool NotifierBase::m_ShowTendency private
Definition at line 11 of file notifierbase.c.
Referenced by AddToCyclicBuffer(), and OnTick().
m_TendencyBuffer
float NotifierBase::m_TendencyBuffer[TENDENCY_BUFFER_SIZE] private
Definition at line 22 of file notifierbase.c.
Referenced by AddToCyclicBuffer(), and ReadFromCyclicBuffer().
m_TendencyBufferSize
int NotifierBase::m_TendencyBufferSize = 3 private
Definition at line 9 of file notifierbase.c.
Referenced by AddToCyclicBuffer(), BleedingNotfr::BleedingNotfr(), GetDeltaAvaraged(), HealthNotfr::HealthNotfr(), ReadFromCyclicBuffer(), and WarmthNotfr::WarmthNotfr().
m_TendencyBufferWriteIterator
int NotifierBase::m_TendencyBufferWriteIterator private
Definition at line 23 of file notifierbase.c.
Referenced by AddToCyclicBuffer(), and ReadFromCyclicBuffer().
m_TickInterval
int NotifierBase::m_TickInterval private
Definition at line 20 of file notifierbase.c.
Referenced by HealthNotfr::HealthNotfr(), IsTimeToTick(), and NotifierBase().
m_TickIntervalLastTick
int NotifierBase::m_TickIntervalLastTick private
Definition at line 21 of file notifierbase.c.
Referenced by IsTimeToTick(), and OnTick().
m_Timer1
ref Timer NotifierBase::m_Timer1 private
Definition at line 5 of file notifierbase.c.
m_Type
int NotifierBase::m_Type private
Definition at line 7 of file notifierbase.c.
Referenced by GetNotifierType().
TENDENCY_BUFFER_SIZE
const int NotifierBase::TENDENCY_BUFFER_SIZE = 30 private
Definition at line 10 of file notifierbase.c.