DayzKode: ActionCloseDoors Class Reference
ActionCloseDoors Class Reference
Private Member Functions
void ActionCloseDoors ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
ref NoiseParams m_NoisePar
Detailed Description
Definition at line 1 of file actionclosedoors.c.
Constructor & Destructor Documentation
ActionCloseDoors()
void ActionCloseDoors::ActionCloseDoors () inline private
Definition at line 5 of file actionclosedoors.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#close";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionCloseDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 18 of file actionclosedoors.c.
    {
        if ( !target )
            return false;
        //if ( IsDamageDestroyed(action_data.m_Target) ) return false;
        if ( !IsBuilding(target) )
            return false;
        Building building;
        if ( Class.CastTo(building, target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(target.GetComponentIndex());
            if ( doorIndex != -1 )
            {
                if ( !IsInReach(player, target, UAMaxDistances.DEFAULT) )
                    return false;
                return building.IsDoorOpen(doorIndex);
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, IsBuilding(), and IsInReach().
CreateConditionComponents()
override void ActionCloseDoors::CreateConditionComponents () inline private
Definition at line 12 of file actionclosedoors.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionCloseDoors::OnEndServer (ActionData action_data) inline private
Definition at line 53 of file actionclosedoors.c.
    {
        m_NoisePar = new NoiseParams();
        m_NoisePar.LoadFromPath("CfgVehicles SurvivorBase NoiseActionDefault");
        NoiseSystem noise = GetGame().GetNoiseSystem();
        if ( noise )
        {
            if ( action_data.m_Player )
                noise.AddNoisePos(action_data.m_Player, action_data.m_Target.GetObject().GetPosition(), m_NoisePar);
        }
    }
References NoiseSystem::AddNoisePos(), GetGame(), CGame::GetNoiseSystem(), m_NoisePar, ActionData::m_Player, ActionData::m_Target, and NoiseParams().
OnStartServer()
override void ActionCloseDoors::OnStartServer (ActionData action_data) inline private
Definition at line 40 of file actionclosedoors.c.
    {
        Building building;
        if ( Class.CastTo(building, action_data.m_Target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(action_data.m_Target.GetComponentIndex());
            if ( doorIndex != -1 )
            {
                building.CloseDoor(doorIndex);
            }
        }
    }
References Class::CastTo(), and ActionData::m_Target.
Member Data Documentation
m_NoisePar
ref NoiseParams ActionCloseDoors::m_NoisePar private
Definition at line 3 of file actionclosedoors.c.
Referenced by OnEndServer().