DayzKode: Environment Class Reference
Environment Class Reference
Private Member Functions
void AddToEnvironmentTemperature (float pTemperature)
protected void ApplyDrynessToItem (ItemBase pItem)
protected void ApplyWetnessToItem (ItemBase pItem)
protected void BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat)
returns weighted avg heat comfort for bodypart
float CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts)
protected void CheckUnderRoof ()
Checks whether Player is sheltered.
protected void CheckWaterContact (out float pWaterLevel)
protected void CollectAndSetEnvironmentData ()
protected void CollectAndSetPlayerData ()
void Environment (PlayerBase pPlayer)
protected float EnvTempToCoef (float pTemp)
protected void GatherTemperatureSources ()
string GetDebugMessage ()
debug
protected float GetEnvironmentTemperature ()
protected float GetPlayerHeat ()
Returns heat player generated based on player's movement speed (for now)
float GetTemperature ()
protected float GetTemperatureHeightCorrection ()
float GetUniversalSourcesTemperageAverage ()
protected float GetWetDelta ()
protected float GetWindModifierPerSurface ()
void Init (PlayerBase pPlayer)
protected bool IsInsideBuilding ()
protected bool IsInsideVehicle ()
protected bool IsRaining ()
bool IsTemperatureSet ()
protected bool IsUnderRoof ()
protected bool IsWaterContact ()
protected bool OverridenHeatComfort (out float value)
DEPRECATED.
protected void ProcessItemsDryness ()
protected void ProcessItemsHeat ()
Calculates and process temperature of items.
protected void ProcessItemsWetness (array< int > pSlotIds)
protected void ProcessTemperatureSources ()
protected void ProcessWetnessByRain ()
protected void ProcessWetnessByWaterLevel (float pWaterLevel)
void SetEnvironmentTemperature ()
void Update (float pDelta)
Private Attributes
protected ref array< int > m_BodyParts
protected float m_Clouds = 0
protected float m_DayOrNight = 0
protected float m_EnvironmentTemperature = 0
protected ref array< int > m_FeetParts
protected float m_Fog = 0
protected ref array< int > m_HeadParts
protected float m_HeatBufferTimer
DEPRECATED.
protected float m_HeatComfort
protected float m_HeatSourceTemp
protected bool m_IsInWater
protected bool m_IsTempSet
protected bool m_IsUnderRoof
protected float m_ItemsWetnessMax
protected PlayerBase m_Player
protected float m_PlayerHeat
protected float m_PlayerHeightPos
protected float m_PlayerSpeed
protected float m_PlayerTemperature
protected float m_Rain = 0
protected float m_RoofCheckTimer
keeps wetness of most wet item in player's possesion
protected ref array< int > m_SlotIdsBottom
protected ref array< int > m_SlotIdsComplete
protected ref array< int > m_SlotIdsLower
protected ref array< int > m_SlotIdsUpper
protected string m_SurfaceType
protected float m_Time = 0
protected ref array< UTemperatureSource > m_UTemperatureSources
protected float m_UTSAverageTemperature
protected ref SimpleMovingAverage< float > m_UTSAverageTemperatureBuffer
protected float m_WaterLevel
protected float m_WetDryTick
protected float m_Wind = 0
protected ref SimpleMovingAverage< float > m_WindAverageBuffer
const float RAIN_LIMIT_LOW = 0.05
const float WATER_LEVEL_HIGH = 1.5
const float WATER_LEVEL_LOW = 0.5
const float WATER_LEVEL_MID = 1.2
const float WATER_LEVEL_NONE = 0.15
Detailed Description
Definition at line 1 of file environment.c.
Constructor & Destructor Documentation
Environment()
void Environment::Environment (PlayerBase pPlayer) inline private
Definition at line 56 of file environment.c.
    {
        Init(pPlayer);
    }
References Init().
Member Function Documentation
AddToEnvironmentTemperature()
void Environment::AddToEnvironmentTemperature (float pTemperature) inline private
Definition at line 217 of file environment.c.
{};
ApplyDrynessToItem()
protected void Environment::ApplyDrynessToItem (ItemBase pItem) inline private
Definition at line 617 of file environment.c.
    {
        if (pItem)
        {
            ItemBase parentIB;
            bool isParentWet = false;
            bool hasLiquid = false;
            InventoryLocation iLoc = new InventoryLocation;
            if (pItem.GetInventory().GetCurrentInventoryLocation(iLoc))
            {
                EntityAI parent = iLoc.GetParent();
                if (parent)
                {
                    parentIB = ItemBase.Cast(parent);
                    if (parentIB)
                    {
                        if (parentIB.GetWet() >= GameConstants.STATE_SOAKING_WET)
{
                            isParentWet = true;
                        }
                        if ((parentIB.GetLiquidType() != 0) && (parentIB.GetQuantity() > 0))
{
                            hasLiquid = true;
                        }
                    }
                    if ((pItem.GetWet() > m_ItemsWetnessMax) && (parent == m_Player))
                    {
                        m_ItemsWetnessMax = pItem.GetWet();
                    }
                }
            }
            if (!isParentWet && !hasLiquid)
            {
                pItem.AddWet(GetWetDelta());
                pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER);
                if (pItem.GetInventory().GetCargo())
                {
                    int inItemCount = pItem.GetInventory().GetCargo().GetItemCount();
                    for (int i = 0; i < inItemCount; i++)
                    {
                        ItemBase inItem;
                        if (Class.CastTo(inItem, pItem.GetInventory().GetCargo().GetItem(i)))
{
                            ApplyDrynessToItem(inItem);
                        }
                    }
                }
                int attCount = pItem.GetInventory().AttachmentCount();
                if (attCount > 0)
                {
                    for (int attIdx = 0; attIdx < attCount; attIdx++)
                    {
                        EntityAI attachment = pItem.GetInventory().GetAttachmentFromIndex(attIdx);
                        ItemBase itemAtt = ItemBase.Cast(attachment);
                        if (itemAtt)
{
                            ApplyDrynessToItem(itemAtt);
                        }
                    }
                }
            }
            if (hasLiquid)
            {
                pItem.AddWet(-1 * GetWetDelta() * 5.5);
                pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER * 5.5);
            }
            if (isParentWet)
            {
                if (pItem.GetWet() < parentIB.GetWet())
                {
                    pItem.AddWet(-1 * GetWetDelta() * 3.5);
                }
                pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER * 3.5);
            }
        }
    }
References ApplyDrynessToItem(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, InventoryLocation::GetParent(), GetWetDelta(), m_ItemsWetnessMax, m_Player, GameConstants::STATE_SOAKING_WET, and GameConstants::TEMPERATURE_RATE_COOLING_PLAYER.
Referenced by ApplyDrynessToItem(), and ProcessItemsDryness().
ApplyWetnessToItem()
protected void Environment::ApplyWetnessToItem (ItemBase pItem) inline private
Definition at line 544 of file environment.c.
    {
        if (pItem)
        {
            bool isParentWet = false;
            bool hasLiquid = false;
            float liquidMdfr = 1.0;
            InventoryLocation iLoc = new InventoryLocation;
            if (pItem.GetInventory().GetCurrentInventoryLocation(iLoc))
            {
                EntityAI parent = iLoc.GetParent();
                if (parent)
                {
                    ItemBase parentIB = ItemBase.Cast(parent);
                    if (parentIB)
                    {
                        if (parentIB.GetWet() >= GameConstants.STATE_SOAKING_WET)
{
                            isParentWet = true;
                        }
                        if ((parentIB.GetLiquidType() != 0) && (parentIB.GetQuantity() > 0 ))
{
                            hasLiquid = true;
                            liquidMdfr = 5.5;
                        }
                    }
                    else
                    {
                        isParentWet = true;
                    }
                    if ((pItem.GetWet() > m_ItemsWetnessMax) && (parent == m_Player))
                    {
                        m_ItemsWetnessMax = pItem.GetWet();
                    }
                }
            }
            if (isParentWet || hasLiquid)
            {
                pItem.AddWet(GetWetDelta() * liquidMdfr);
                pItem.AddTemperature(GameConstants.ENVIRO_TICK_RATE * GameConstants.TEMPERATURE_RATE_COOLING_PLAYER * liquidMdfr);
                if (pItem.GetInventory().GetCargo())
                {
                    int inItemCount = pItem.GetInventory().GetCargo().GetItemCount();
                    for (int i = 0; i < inItemCount; i++)
                    {
                        ItemBase inItem;
                        if (Class.CastTo(inItem, pItem.GetInventory().GetCargo().GetItem(i)))
{
                            ApplyWetnessToItem(inItem);
                        }
                    }
                }
                int attCount = pItem.GetInventory().AttachmentCount();
                if (attCount > 0)
                {
                    for (int attIdx = 0; attIdx < attCount; attIdx++)
                    {
                        EntityAI attachment = pItem.GetInventory().GetAttachmentFromIndex(attIdx);
                        ItemBase itemAtt = ItemBase.Cast(attachment);
                        if (itemAtt)
{
                            ApplyWetnessToItem(itemAtt);
                        }
                    }
                }
            }
        }
    }
References ApplyWetnessToItem(), Class::CastTo(), GameConstants::ENVIRO_TICK_RATE, InventoryLocation::GetParent(), GetWetDelta(), m_ItemsWetnessMax, m_Player, GameConstants::STATE_SOAKING_WET, and GameConstants::TEMPERATURE_RATE_COOLING_PLAYER.
Referenced by ApplyWetnessToItem(), and ProcessItemsWetness().
BodyPartHeatProperties()
protected void Environment::BodyPartHeatProperties (array< int > pBodyPartIds, float pCoef, out float pHeatComfort, out float pHeat) inline private
returns weighted avg heat comfort for bodypart
go through all body parts we've defined for that zone (ex.: head, body, feet)
Definition at line 791 of file environment.c.
    {
        int attCount;
        EntityAI attachment;
        ItemBase item;
        pHeatComfort = -1;
        attCount = m_Player.GetInventory().AttachmentCount();
        for (int attIdx = 0; attIdx < attCount; attIdx++)
        {
            attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
            if (attachment.IsClothing())
            {
                item = ItemBase.Cast(attachment);
                int attachmentSlot = attachment.GetInventory().GetSlotId(0);
                for (int i = 0; i < pBodyPartIds.Count(); i++)
                {
                    if (attachmentSlot == pBodyPartIds.Get(i))
                    {
                        float heatIsoMult = 1.0;
                        if (attachmentSlot == InventorySlots.VEST)
{
                            heatIsoMult = GameConstants.ENVIRO_HEATISOLATION_VEST_WEIGHT;
                        }
                        if (attachmentSlot == InventorySlots.BACK)
{
                            heatIsoMult = GameConstants.ENVIRO_HEATISOLATION_BACK_WEIGHT;
                        }
                        pHeatComfort += heatIsoMult * MiscGameplayFunctions.GetCurrentItemHeatIsolation(item);
                        // go through any attachments and cargo (only current level, ignore nested containers - they isolate)
                        int inAttCount = item.GetInventory().AttachmentCount();
                        if (inAttCount > 0)
{
                            for (int inAttIdx = 0; inAttIdx < inAttCount; inAttIdx++)
{
                                EntityAI inAttachment = item.GetInventory().GetAttachmentFromIndex(inAttIdx);
                                ItemBase itemAtt = ItemBase.Cast(inAttachment);
                                if (itemAtt)
{
                                    pHeat += itemAtt.GetTemperature();
                                }
                            }
                        }
                        if (item.GetInventory().GetCargo())
{
                            int inItemCount = item.GetInventory().GetCargo().GetItemCount();
                            for (int j = 0; j < inItemCount; j++)
{
                                ItemBase inItem;
                                if (Class.CastTo(inItem, item.GetInventory().GetCargo().GetItem(j)))
{
                                    pHeat += inItem.GetTemperature();
                                }
                            }
                        }
                    }
                }
            }
        }
        pHeatComfort = (pHeatComfort / pBodyPartIds.Count()) * pCoef;
        pHeat = (pHeat / pBodyPartIds.Count()) * pCoef;
    }
References Class::CastTo(), GameConstants::ENVIRO_HEATISOLATION_BACK_WEIGHT, GameConstants::ENVIRO_HEATISOLATION_VEST_WEIGHT, and m_Player.
Referenced by ProcessItemsHeat().
CalcTemperatureFromTemperatureSource()
float Environment::CalcTemperatureFromTemperatureSource (notnull UTemperatureSource uts) inline private
heat transfer through air to player (env temperature)
dist factor minimum should be at 0
Definition at line 929 of file environment.c.
    {
        float distance      = vector.Distance(m_Player.GetPosition(), uts.GetPosition());
        distance            = Math.Max(distance, 0.1);  //min distance cannot be 0 (division by zero)
        float temperature   = 0;
        //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::distance: %1", distance), "Environment");
        if (distance > uts.GetFullRange())
        {
            float distFactor = 1 - (distance / uts.GetMaxRange());
            distFactor = Math.Max(distFactor, 0.0);
            temperature = uts.GetTemperature() * distFactor;
            //temperature = Math.Clamp(temperature, uts.GetTemperatureMin(), uts.GetTemperatureMax());
            //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::distFactor: %1", distFactor), "Environment");
            //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::temperatureXX: %1", temperature), "Environment");
        }
        else
        {
            temperature = uts.GetTemperature();
        }
        //Debug.Log(string.Format("CalcTemperatureFromTemperatureSource::temperature: %1", temperature), "Environment");
        return temperature;
    }
References vector::Distance(), m_Player, and Math::Max().
Referenced by ProcessTemperatureSources().
CheckUnderRoof()
protected void Environment::CheckUnderRoof () inline private
Checks whether Player is sheltered.
Definition at line 252 of file environment.c.
    {
        // if inside vehicle return immediatelly
        if (IsInsideVehicle())
        {
            m_IsUnderRoof = false;
            return;
        }
        float hitFraction;
        vector hitPosition, hitNormal;
        vector from = m_Player.GetPosition();
        vector to = from + "0 25 0";
        Object hitObject;
        PhxInteractionLayers collisionLayerMask = PhxInteractionLayers.ITEM_LARGE|PhxInteractionLayers.BUILDING|PhxInteractionLayers.VEHICLE;
        m_IsUnderRoof = DayZPhysics.RayCastBullet(from, to, collisionLayerMask, null, hitObject, hitPosition, hitNormal, hitFraction);
    }
References IsInsideVehicle(), m_IsUnderRoof, m_Player, and DayZPhysics::RayCastBullet().
Referenced by Update().
CheckWaterContact()
protected void Environment::CheckWaterContact (out float pWaterLevel) inline private
sync info about water contact to player
update active surface
Definition at line 271 of file environment.c.
    {
        string surfType;
        int liquidType;
        g_Game.SurfaceUnderObject(m_Player, surfType, liquidType);
        switch ( liquidType )
        {
            case 0: // sea
            case LIQUID_WATER:
                vector wl = HumanCommandSwim.WaterLevelCheck(m_Player, m_Player.GetPosition());
                pWaterLevel = wl[0];
                m_IsInWater = true;
            break;
            default:
                pWaterLevel = 0;
                m_IsInWater = false;
            break;
        }
        m_Player.SetInWater(m_IsInWater);
        m_SurfaceType = surfType;
    }
References g_Game, HumanCommandSwim(), LIQUID_WATER, m_IsInWater, m_Player, and m_SurfaceType.
Referenced by Update().
CollectAndSetEnvironmentData()
protected void Environment::CollectAndSetEnvironmentData () inline private
Definition at line 430 of file environment.c.
    {
        Weather weather = g_Game.GetWeather();
        m_Rain          = weather.GetRain().GetActual();
        m_DayOrNight    = g_Game.GetWorld().GetSunOrMoon();
        m_Fog           = weather.GetFog().GetActual();
        m_Clouds        = weather.GetOvercast().GetActual();
        m_Wind          = m_WindAverageBuffer.Add(weather.GetWindSpeed() / weather.GetWindMaximumSpeed());
        SetEnvironmentTemperature();
    }
References g_Game, WeatherPhenomenon::GetActual(), Weather::GetFog(), Weather::GetOvercast(), Weather::GetRain(), Weather::GetWindMaximumSpeed(), Weather::GetWindSpeed(), m_Clouds, m_DayOrNight, m_Fog, m_Rain, m_Wind, m_WindAverageBuffer, and SetEnvironmentTemperature().
Referenced by Update().
CollectAndSetPlayerData()
protected void Environment::CollectAndSetPlayerData () inline private
Definition at line 415 of file environment.c.
    {
        vector playerPos = m_Player.GetPosition();
        m_PlayerHeightPos = playerPos[1];
        HumanCommandMove hcm = m_Player.GetCommand_Move();
        if (hcm)
        {
            m_PlayerSpeed = hcm.GetCurrentMovementSpeed();
        }
        m_PlayerHeat = GetPlayerHeat();
    }
References HumanCommandMove::GetCurrentMovementSpeed(), GetPlayerHeat(), m_Player, m_PlayerHeat, m_PlayerHeightPos, and m_PlayerSpeed.
Referenced by Update().
EnvTempToCoef()
protected float Environment::EnvTempToCoef (float pTemp) inline private
Definition at line 775 of file environment.c.
    {
        if (pTemp >= GameConstants.ENVIRO_HIGH_TEMP_LIMIT)
        {
            return 1;
        }
        if (pTemp <= GameConstants.ENVIRO_LOW_TEMP_LIMIT)
        {
            return -1;
        }
        return (pTemp - GameConstants.ENVIRO_PLAYER_COMFORT_TEMP) / GameConstants.ENVIRO_TEMP_EFFECT_ON_PLAYER;
    }
References GameConstants::ENVIRO_HIGH_TEMP_LIMIT, GameConstants::ENVIRO_LOW_TEMP_LIMIT, GameConstants::ENVIRO_PLAYER_COMFORT_TEMP, and GameConstants::ENVIRO_TEMP_EFFECT_ON_PLAYER.
Referenced by ProcessItemsHeat().
GatherTemperatureSources()
protected void Environment::GatherTemperatureSources () inline private
next temp source is too far
Definition at line 863 of file environment.c.
    {
        m_UTemperatureSources.Clear();
        array<Object> nearestObjects = new array<Object>;
        GetGame().GetObjectsAtPosition(m_Player.GetPosition(), GameConstants.ENVIRO_TEMP_SOURCES_LOOKUP_RADIUS, nearestObjects, null);
        for (int i = 0; i < nearestObjects.Count(); i++)
        {
            EntityAI ent = EntityAI.Cast(nearestObjects.Get(i));
            if (ent && ent.IsUniversalTemperatureSource() && ent != m_Player)
            {
                if (vector.DistanceSq(m_Player.GetPosition(), ent.GetPosition()) > Math.SqrFloat(ent.GetUniversalTemperatureSource().GetMaxRange()))
                {
                    continue;
                }
                m_UTemperatureSources.Insert(ent.GetUniversalTemperatureSource());
            }
        }
        if (m_Player.GetItemInHands() && m_Player.GetItemInHands().IsUniversalTemperatureSource())
        {
            m_UTemperatureSources.Insert(m_Player.GetItemInHands().GetUniversalTemperatureSource());
        }
    }
References vector::DistanceSq(), GameConstants::ENVIRO_TEMP_SOURCES_LOOKUP_RADIUS, GetGame(), CGame::GetObjectsAtPosition(), m_Player, m_UTemperatureSources, and Math::SqrFloat().
Referenced by Update().
GetDebugMessage()
string Environment::GetDebugMessage () inline private
debug
Definition at line 999 of file environment.c.
    {
        string message;
        message += "Player stats";
        message += "\nHeat comfort: " + m_HeatComfort.ToString();
        message += "\nInside: " + IsInsideBuilding().ToString() + " ("+m_Player.GetSurfaceType()+")";
        message += "\nUnder roof: " + m_IsUnderRoof.ToString() + " (" + (GameConstants.ENVIRO_TICK_ROOF_RC_CHECK - m_RoofCheckTimer) + ")";
        if (IsWaterContact() && m_WaterLevel > WATER_LEVEL_NONE)
        {
            message += "\nWater Level: " + m_WaterLevel;
        }
        message += "\n\nWeather stats";
        message += "\nEnv temperature (base): " + g_Game.GetMission().GetWorldData().GetBaseEnvTemperature().ToString();
        message += "\nEnv temperature (modified): " + m_EnvironmentTemperature.ToString();
        message += "\nWind: " + m_Wind.ToString() + " (x" + GetWindModifierPerSurface() + ")";
        message += "\nRain: " + m_Rain.ToString();
        message += "\nDay/Night (1/0): " + m_DayOrNight.ToString();
        message += "\nFog: " + m_Fog.ToString();
        message += "\nClouds: " + m_Clouds.ToString();
        message += "\nHeight: " + GetTemperatureHeightCorrection().ToString();
        message += "\nWet delta: " + GetWetDelta().ToString();
        return message;
    }
References GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, g_Game, GetTemperatureHeightCorrection(), GetWetDelta(), GetWindModifierPerSurface(), IsInsideBuilding(), IsWaterContact(), m_Clouds, m_DayOrNight, m_EnvironmentTemperature, m_Fog, m_HeatComfort, m_IsUnderRoof, m_Player, m_Rain, m_RoofCheckTimer, m_WaterLevel, m_Wind, bool::ToString(), float::ToString(), and WATER_LEVEL_NONE.
GetEnvironmentTemperature()
protected float Environment::GetEnvironmentTemperature () inline private
Definition at line 319 of file environment.c.
    {
        float temperature;
        temperature = g_Game.GetMission().GetWorldData().GetBaseEnvTemperature();
        temperature += Math.AbsFloat(temperature * m_Clouds * GameConstants.ENVIRO_CLOUDS_TEMP_EFFECT);
        if (IsWaterContact())
        {
            temperature -= Math.AbsFloat(temperature * GameConstants.ENVIRO_WATER_TEMPERATURE_COEF);
        }
        if (IsInsideBuilding())
        {
            temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_INSIDE_COEF);
        }
        else if (IsInsideVehicle())
        {
            temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_INSIDE_VEHICLE_COEF);
        }
        else if (IsUnderRoof())
        {
            temperature += Math.AbsFloat(temperature * GameConstants.ENVIRO_TEMPERATURE_UNDERROOF_COEF);
            temperature -= GameConstants.ENVIRO_TEMPERATURE_WIND_COEF * GetWindModifierPerSurface() * m_Wind;
        }
        else
        {
            temperature -= GameConstants.ENVIRO_TEMPERATURE_WIND_COEF * GetWindModifierPerSurface() * m_Wind;
            temperature -= Math.AbsFloat(temperature * m_Fog * GameConstants.ENVIRO_FOG_TEMP_EFFECT);
            temperature -= GetTemperatureHeightCorrection();
        }
        // incorporate temperature from temperature sources (buffer)
        if (Math.AbsFloat(m_UTSAverageTemperature) > 0.001)
        {
            temperature += m_UTSAverageTemperature;
        }
        return temperature;
    }
References Math::AbsFloat(), GameConstants::ENVIRO_CLOUDS_TEMP_EFFECT, GameConstants::ENVIRO_FOG_TEMP_EFFECT, GameConstants::ENVIRO_TEMPERATURE_INSIDE_COEF, GameConstants::ENVIRO_TEMPERATURE_INSIDE_VEHICLE_COEF, GameConstants::ENVIRO_TEMPERATURE_UNDERROOF_COEF, GameConstants::ENVIRO_TEMPERATURE_WIND_COEF, GameConstants::ENVIRO_WATER_TEMPERATURE_COEF, g_Game, GetTemperatureHeightCorrection(), GetWindModifierPerSurface(), IsInsideBuilding(), IsInsideVehicle(), IsUnderRoof(), IsWaterContact(), m_Clouds, m_Fog, m_UTSAverageTemperature, and m_Wind.
Referenced by GetWetDelta(), and SetEnvironmentTemperature().
GetPlayerHeat()
protected float Environment::GetPlayerHeat () inline private
Returns heat player generated based on player's movement speed (for now)
Definition at line 220 of file environment.c.
    {
        float heat = Math.Max(m_PlayerSpeed * GameConstants.ENVIRO_DEFAULT_ENTITY_HEAT, GameConstants.ENVIRO_DEFAULT_ENTITY_HEAT);
        return heat;
    }
References GameConstants::ENVIRO_DEFAULT_ENTITY_HEAT, m_PlayerSpeed, and Math::Max().
Referenced by CollectAndSetPlayerData(), and ProcessItemsHeat().
GetTemperature()
float Environment::GetTemperature () inline private
Definition at line 313 of file environment.c.
    {
        return m_EnvironmentTemperature;
    }
References m_EnvironmentTemperature.
GetTemperatureHeightCorrection()
protected float Environment::GetTemperatureHeightCorrection () inline private
Definition at line 302 of file environment.c.
    {
        float temperature_reduction = Math.Max(0, (m_PlayerHeightPos * GameConstants.ENVIRO_TEMPERATURE_HEIGHT_REDUCTION));
        return temperature_reduction;
    }
References GameConstants::ENVIRO_TEMPERATURE_HEIGHT_REDUCTION, m_PlayerHeightPos, and Math::Max().
Referenced by GetDebugMessage(), and GetEnvironmentTemperature().
GetUniversalSourcesTemperageAverage()
float Environment::GetUniversalSourcesTemperageAverage () inline private
Definition at line 924 of file environment.c.
    {
        return m_UTSAverageTemperature;
    }
References m_UTSAverageTemperature.
GetWetDelta()
protected float Environment::GetWetDelta () inline private
player is getting wet by movement/swimming in water (+differentiate wetDelta by water level)
player is getting wet from rain
player is drying
Definition at line 360 of file environment.c.
    {
        float wetDelta = 0;
        if ( IsWaterContact() )
        {
            if (m_WaterLevel >= WATER_LEVEL_HIGH)
            {
                wetDelta = 1;
            }
            else if (m_WaterLevel >= WATER_LEVEL_MID && m_WaterLevel < WATER_LEVEL_HIGH)
            {
                wetDelta = 0.66;
            }
            else if (m_WaterLevel >= WATER_LEVEL_LOW && m_WaterLevel < WATER_LEVEL_MID)
            {
                wetDelta = 0.66;
            }
            else if (m_WaterLevel >= WATER_LEVEL_NONE && m_WaterLevel < WATER_LEVEL_LOW)
            {
                wetDelta = 0.33;
            }
        }
        else if (IsRaining() && !IsInsideBuilding() && !IsUnderRoof() && !IsInsideVehicle())
        {
            wetDelta = GameConstants.ENVIRO_WET_INCREMENT * GameConstants.ENVIRO_TICKS_TO_WETNESS_CALCULATION * (m_Rain) * (1 + (GameConstants.ENVIRO_WIND_EFFECT * m_Wind));
        }
        else
        {
            float tempEffect = Math.Max(m_PlayerHeat + GetEnvironmentTemperature(), 1.0);
            if (m_HeatSourceTemp != 0)
            {
                tempEffect *= GameConstants.ENVIRO_FIRE_INCREMENT;
            }
            float weatherEffect = ((1 - (m_Fog * GameConstants.ENVIRO_FOG_DRY_EFFECT))) * (1 - (m_Clouds * GameConstants.ENVIRO_CLOUD_DRY_EFFECT));
            if (weatherEffect <= 0)
            {
                weatherEffect = 1.0;
            }
            wetDelta = -(GameConstants.ENVIRO_DRY_INCREMENT * weatherEffect * tempEffect);
            if (!IsInsideBuilding())
            {
                wetDelta *= 1 + (GameConstants.ENVIRO_WIND_EFFECT * m_Wind);
            }
        }
        return wetDelta;
    }
References GameConstants::ENVIRO_CLOUD_DRY_EFFECT, GameConstants::ENVIRO_DRY_INCREMENT, GameConstants::ENVIRO_FIRE_INCREMENT, GameConstants::ENVIRO_FOG_DRY_EFFECT, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GameConstants::ENVIRO_WET_INCREMENT, GameConstants::ENVIRO_WIND_EFFECT, GetEnvironmentTemperature(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsUnderRoof(), IsWaterContact(), m_Clouds, m_Fog, m_HeatSourceTemp, m_PlayerHeat, m_Rain, m_WaterLevel, m_Wind, Math::Max(), WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by ApplyDrynessToItem(), ApplyWetnessToItem(), and GetDebugMessage().
GetWindModifierPerSurface()
protected float Environment::GetWindModifierPerSurface () inline private
Definition at line 308 of file environment.c.
    {
        return g_Game.ConfigGetFloat( "CfgSurfaces " + m_SurfaceType + " windModifier" );
    }
References g_Game, and m_SurfaceType.
Referenced by GetDebugMessage(), and GetEnvironmentTemperature().
Init()
void Environment::Init (PlayerBase pPlayer) inline private
whole body slots
upper body part slots
bottom body part slots
lower body part slots
heat comfort related slots
Definition at line 61 of file environment.c.
    {
        m_Player                        = pPlayer;
        m_PlayerSpeed                   = 0.0;
        m_WetDryTick                    = 0.0;
        m_RoofCheckTimer                = 0.0;
        m_WaterLevel                    = 0.0;
        m_HeatComfort                   = 0.0;
        m_IsUnderRoof                   = false;
        m_IsInWater                     = false;
        m_SurfaceType                   = "cp_dirt";
        m_HeatBufferTimer               = 0.0;
        m_WindAverageBuffer             = new SimpleMovingAverage<float>(30, 0.5);
        m_UTSAverageTemperature         = 0.0;
        m_UTemperatureSources           = new array<UTemperatureSource>();
        m_UTSAverageTemperatureBuffer   = new SimpleMovingAverage<float>(10, 0);
        m_SlotIdsComplete       = new array<int>;
        m_SlotIdsComplete       = {
            InventorySlots.HEADGEAR,
            InventorySlots.MASK,
            InventorySlots.EYEWEAR,
            InventorySlots.GLOVES,
            InventorySlots.ARMBAND,
            InventorySlots.BODY,
            InventorySlots.VEST,
            InventorySlots.BACK,
            InventorySlots.LEGS,
            InventorySlots.FEET,
        };
        m_SlotIdsUpper          = new array<int>;
        m_SlotIdsUpper          = {
            InventorySlots.GLOVES,
            InventorySlots.ARMBAND,
            InventorySlots.BODY,
            InventorySlots.VEST,
            InventorySlots.BACK,
            InventorySlots.LEGS,
            InventorySlots.FEET,
        };
        m_SlotIdsBottom         = new array<int>;
        m_SlotIdsBottom         = {
            InventorySlots.LEGS,
            InventorySlots.FEET,
        };
        m_SlotIdsLower          = new array<int>;
        m_SlotIdsLower          = {
            InventorySlots.FEET,
        };
        m_HeadParts             = new array<int>;
        m_HeadParts             = {
            InventorySlots.HEADGEAR,
            InventorySlots.MASK,
        };
        m_BodyParts             = new array<int>;
        m_BodyParts             = {
            InventorySlots.GLOVES,
            InventorySlots.BODY,
            InventorySlots.BACK,
            InventorySlots.VEST,
        };
        m_FeetParts             = new array<int>;
        m_FeetParts             = {
            InventorySlots.LEGS,
            InventorySlots.FEET,
        };
    }
References m_BodyParts, m_FeetParts, m_HeadParts, m_HeatBufferTimer, m_HeatComfort, m_IsInWater, m_IsUnderRoof, m_Player, m_PlayerSpeed, m_RoofCheckTimer, m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, m_SurfaceType, m_UTemperatureSources, m_UTSAverageTemperature, m_UTSAverageTemperatureBuffer, m_WaterLevel, m_WetDryTick, and m_WindAverageBuffer.
IsInsideBuilding()
protected bool Environment::IsInsideBuilding () inline private
Definition at line 236 of file environment.c.
    {
        return m_Player && m_Player.IsSoundInsideBuilding();
    }
References m_Player.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsInsideVehicle()
protected bool Environment::IsInsideVehicle () inline private
Definition at line 241 of file environment.c.
    {
        return m_Player && m_Player.IsInVehicle();
    }
References m_Player.
Referenced by CheckUnderRoof(), GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsRaining()
protected bool Environment::IsRaining () inline private
Definition at line 246 of file environment.c.
    {
        return m_Rain > RAIN_LIMIT_LOW;
    }
References m_Rain, and RAIN_LIMIT_LOW.
Referenced by GetWetDelta(), and Update().
IsTemperatureSet()
bool Environment::IsTemperatureSet () inline private
Definition at line 211 of file environment.c.
    {
        return m_IsTempSet;
    }
References m_IsTempSet.
IsUnderRoof()
protected bool Environment::IsUnderRoof () inline private
Definition at line 226 of file environment.c.
    {
        return m_IsUnderRoof;
    }
References m_IsUnderRoof.
Referenced by GetEnvironmentTemperature(), GetWetDelta(), and Update().
IsWaterContact()
protected bool Environment::IsWaterContact () inline private
Definition at line 231 of file environment.c.
    {
        return m_IsInWater;
    }
References m_IsInWater.
Referenced by GetDebugMessage(), GetEnvironmentTemperature(), GetWetDelta(), and Update().
OverridenHeatComfort()
protected bool Environment::OverridenHeatComfort (out float value) inline private
DEPRECATED.
Definition at line 773 of file environment.c.
{};
ProcessItemsDryness()
protected void Environment::ProcessItemsDryness () inline private
force recalc of player's load (for stamina)
Definition at line 516 of file environment.c.
    {
        EntityAI attachment;
        ItemBase item;
        int attCount = m_Player.GetInventory().AttachmentCount();
        for (int attIdx = 0; attIdx < attCount; attIdx++)
        {
            attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
            if (attachment && attachment.IsItemBase())
            {
                item = ItemBase.Cast(attachment);
                ApplyDrynessToItem(item);
            }
        }
        if (m_Player.GetItemInHands())
        {
            ApplyDrynessToItem(m_Player.GetItemInHands());
        }
        m_Player.UpdateWeight();
        m_Player.SetPlayerLoad(m_Player.GetWeight());
    }
References ApplyDrynessToItem(), and m_Player.
Referenced by Update().
ProcessItemsHeat()
protected void Environment::ProcessItemsHeat () inline private
Calculates and process temperature of items.
Heat Comfort
Heat (from items);
Definition at line 703 of file environment.c.
    {
        float hcHead, hcBody, hcFeet;
        float hHead, hBody, hFeet;
        float heatComfortAvg;
        float heatAvg;
        BodyPartHeatProperties(m_HeadParts, GameConstants.ENVIRO_HEATCOMFORT_HEADPARTS_WEIGHT, hcHead, hHead);
        BodyPartHeatProperties(m_BodyParts, GameConstants.ENVIRO_HEATCOMFORT_BODYPARTS_WEIGHT, hcBody, hBody);
        BodyPartHeatProperties(m_FeetParts, GameConstants.ENVIRO_HEATCOMFORT_FEETPARTS_WEIGHT, hcFeet, hFeet);
        heatComfortAvg = (hcHead + hcBody + hcFeet) / 3;
        heatAvg = (hHead + hBody + hFeet) / 3;
        heatAvg = heatAvg * GameConstants.ENVIRO_ITEM_HEAT_TRANSFER_COEF;
        // heat buffer
        float applicableHB = 0.0;
        if (m_UTSAverageTemperature < 0.001)
        {
            applicableHB = m_Player.GetStatHeatBuffer().Get() / 30.0;
            if (applicableHB > 0.0)
            {
                if (m_HeatBufferTimer > 1.0)
                {
                    m_Player.GetStatHeatBuffer().Add(Math.Min(EnvTempToCoef(m_EnvironmentTemperature), -0.1) * GameConstants.ENVIRO_PLAYER_HEATBUFFER_DECREASE);
                }
                else
                {
                    m_HeatBufferTimer += GameConstants.ENVIRO_PLAYER_HEATBUFFER_TICK;
                }
            }
            else
            {
                m_HeatBufferTimer = 0.0;
            }
        }
        else
        {
            applicableHB = m_Player.GetStatHeatBuffer().Get() / 30.0;
            if (m_HeatComfort > PlayerConstants.THRESHOLD_HEAT_COMFORT_MINUS_WARNING)
            {
                m_Player.GetStatHeatBuffer().Add(GameConstants.ENVIRO_PLAYER_HEATBUFFER_INCREASE);
                m_HeatBufferTimer = 0.0;
            }
            else
            {
                m_HeatBufferTimer = 0.0;
            }
        }
        m_HeatComfort = (heatComfortAvg + heatAvg + (GetPlayerHeat() / 100)) + EnvTempToCoef(m_EnvironmentTemperature);
        if ((m_HeatComfort + applicableHB) < (PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01))
        {
            m_HeatComfort += applicableHB;
        }
        else
        {
            if (m_HeatComfort <= (PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01))
            {
                m_HeatComfort = PlayerConstants.THRESHOLD_HEAT_COMFORT_PLUS_WARNING - 0.01;
            }
        }
        m_HeatComfort = Math.Clamp(m_HeatComfort, m_Player.GetStatHeatComfort().GetMin(), m_Player.GetStatHeatComfort().GetMax());
        m_Player.GetStatHeatComfort().Set(m_HeatComfort);
    }
References BodyPartHeatProperties(), Math::Clamp(), GameConstants::ENVIRO_HEATCOMFORT_BODYPARTS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_FEETPARTS_WEIGHT, GameConstants::ENVIRO_HEATCOMFORT_HEADPARTS_WEIGHT, GameConstants::ENVIRO_ITEM_HEAT_TRANSFER_COEF, GameConstants::ENVIRO_PLAYER_HEATBUFFER_DECREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_INCREASE, GameConstants::ENVIRO_PLAYER_HEATBUFFER_TICK, EnvTempToCoef(), GetPlayerHeat(), m_BodyParts, m_EnvironmentTemperature, m_FeetParts, m_HeadParts, m_HeatBufferTimer, m_HeatComfort, m_Player, m_UTSAverageTemperature, Math::Min(), PlayerConstants::THRESHOLD_HEAT_COMFORT_MINUS_WARNING, and PlayerConstants::THRESHOLD_HEAT_COMFORT_PLUS_WARNING.
Referenced by Update().
ProcessItemsWetness()
protected void Environment::ProcessItemsWetness (array< int > pSlotIds) inline private
force recalc of player's load (for stamina)
Definition at line 481 of file environment.c.
    {
        EntityAI attachment;
        ItemBase item;
        int attCount = m_Player.GetInventory().AttachmentCount();
        for (int attIdx = 0; attIdx < attCount; attIdx++)
        {
            attachment = m_Player.GetInventory().GetAttachmentFromIndex(attIdx);
            if (attachment.IsItemBase())
            {
                item = ItemBase.Cast(attachment);
                int attachmentSlot = attachment.GetInventory().GetSlotId(0);
                for (int i = 0; i < pSlotIds.Count(); i++)
                {
                    if (attachmentSlot == pSlotIds.Get(i))
                    {
                        ApplyWetnessToItem(item);
                    }
                }
            }
        }
        if (m_Player.GetItemInHands())
        {
            ApplyWetnessToItem(m_Player.GetItemInHands());
        }
        m_Player.UpdateWeight();
        m_Player.SetPlayerLoad(m_Player.GetWeight());
    }
References ApplyWetnessToItem(), and m_Player.
Referenced by ProcessWetnessByRain(), and ProcessWetnessByWaterLevel().
ProcessTemperatureSources()
protected void Environment::ProcessTemperatureSources () inline private
adds average of 2 most significat sources to buffer
Definition at line 893 of file environment.c.
    {
        if (m_UTemperatureSources.Count() == 0)
        {
            m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add(0);
            return;
        }
        array<float> utsTemperatures = new array<float>();
        // get temperature from the source (based on distance), save it for min/max filtering
        for (int i = 0; i < m_UTemperatureSources.Count(); i++)
        {
            utsTemperatures.Insert(CalcTemperatureFromTemperatureSource(m_UTemperatureSources[i]));
        }
        float min = MiscGameplayFunctions.GetMinValue(utsTemperatures);
        float max = MiscGameplayFunctions.GetMaxValue(utsTemperatures);
        if (max > 0 && min < 0)
        {
            m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add((max + min) * 0.5);
        }
        else
        {
            m_UTSAverageTemperature = m_UTSAverageTemperatureBuffer.Add(max);
        }
    }
References CalcTemperatureFromTemperatureSource(), m_UTemperatureSources, m_UTSAverageTemperature, and m_UTSAverageTemperatureBuffer.
Referenced by Update().
ProcessWetnessByRain()
protected void Environment::ProcessWetnessByRain () inline private
Definition at line 448 of file environment.c.
    {
        ProcessItemsWetness(m_SlotIdsComplete);
    }
References m_SlotIdsComplete, and ProcessItemsWetness().
Referenced by Update().
ProcessWetnessByWaterLevel()
protected void Environment::ProcessWetnessByWaterLevel (float pWaterLevel) inline private
complete
upper part
bottom part
feet
Definition at line 453 of file environment.c.
    {
        ref array<int> slotIds = new array<int>;
        // process attachments by water depth
        if (pWaterLevel >= WATER_LEVEL_HIGH)
        {
            ProcessItemsWetness(m_SlotIdsComplete);
        }
        else if (pWaterLevel >= WATER_LEVEL_MID && pWaterLevel < WATER_LEVEL_HIGH)
        {
            ProcessItemsWetness(m_SlotIdsUpper);
        }
        else if (pWaterLevel >= WATER_LEVEL_LOW && pWaterLevel < WATER_LEVEL_MID)
        {
            ProcessItemsWetness(m_SlotIdsBottom);
        }
        else if (pWaterLevel >= WATER_LEVEL_NONE && pWaterLevel < WATER_LEVEL_LOW)
        {
            ProcessItemsWetness(m_SlotIdsLower);
        }
    }
References m_SlotIdsBottom, m_SlotIdsComplete, m_SlotIdsLower, m_SlotIdsUpper, ProcessItemsWetness(), WATER_LEVEL_HIGH, WATER_LEVEL_LOW, WATER_LEVEL_MID, and WATER_LEVEL_NONE.
Referenced by Update().
SetEnvironmentTemperature()
void Environment::SetEnvironmentTemperature () inline private
Definition at line 442 of file environment.c.
    {
        m_IsTempSet = true;
        m_EnvironmentTemperature = GetEnvironmentTemperature();
    }
References GetEnvironmentTemperature(), m_EnvironmentTemperature, and m_IsTempSet.
Referenced by CollectAndSetEnvironmentData().
Update()
void Environment::Update (float pDelta) inline private
check if player is under roof (only if the Building check is false)
Updates data
Process temperature
Process item wetness/dryness
setting of wetness/dryiness of player
reset item wetness counter;
Definition at line 145 of file environment.c.
    {
        if (m_Player)
        {
            m_RoofCheckTimer += pDelta;
            if ( m_RoofCheckTimer >= GameConstants.ENVIRO_TICK_ROOF_RC_CHECK )
            {
                if ( !IsInsideBuilding() )
                    CheckUnderRoof();
                m_RoofCheckTimer = 0;
            }
            m_Time += pDelta;
            if ( m_Time >= GameConstants.ENVIRO_TICK_RATE )
            {
                m_Time = 0;
                m_WetDryTick++; // Sets whether it is time to add wetness to items and clothing
                //Print(IsInsideBuilding().ToString());
                CheckWaterContact(m_WaterLevel);
                CollectAndSetPlayerData();
                CollectAndSetEnvironmentData();
                GatherTemperatureSources();
                ProcessTemperatureSources();
                ProcessItemsHeat();
                if ( m_WetDryTick >= GameConstants.ENVIRO_TICKS_TO_WETNESS_CALCULATION )
                {
                    if( IsWaterContact() )
                    {
                        ProcessWetnessByWaterLevel(m_WaterLevel);
                    }
                    else if( IsRaining() && !IsInsideBuilding() && !IsUnderRoof() && !IsInsideVehicle() )
                    {
                        ProcessWetnessByRain();
                    }
                    else
                    {
                        ProcessItemsDryness();
                    }
                    if ( ( m_ItemsWetnessMax < GameConstants.STATE_WET ) && ( m_Player.GetStatWet().Get() == 1 ) )
                    {
                        m_Player.GetStatWet().Set( 0 );
                    }
                    else if ( ( m_ItemsWetnessMax >= GameConstants.STATE_WET ) && ( m_Player.GetStatWet().Get() == 0 ) )
                    {
                        m_Player.GetStatWet().Set( 1 );
                    }
                    m_WetDryTick = 0;
                    m_ItemsWetnessMax = 0;
                }
            }
        }
    }
References CheckUnderRoof(), CheckWaterContact(), CollectAndSetEnvironmentData(), CollectAndSetPlayerData(), GameConstants::ENVIRO_TICK_RATE, GameConstants::ENVIRO_TICK_ROOF_RC_CHECK, GameConstants::ENVIRO_TICKS_TO_WETNESS_CALCULATION, GatherTemperatureSources(), IsInsideBuilding(), IsInsideVehicle(), IsRaining(), IsUnderRoof(), IsWaterContact(), m_ItemsWetnessMax, m_Player, m_RoofCheckTimer, m_Time, m_WaterLevel, m_WetDryTick, ProcessItemsDryness(), ProcessItemsHeat(), ProcessTemperatureSources(), ProcessWetnessByRain(), ProcessWetnessByWaterLevel(), and GameConstants::STATE_WET.
Member Data Documentation
m_BodyParts
protected ref array<int> Environment::m_BodyParts private
Definition at line 47 of file environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_Clouds
protected float Environment::m_Clouds = 0 private
Definition at line 27 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_DayOrNight
protected float Environment::m_DayOrNight = 0 private
Definition at line 26 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), and GetDebugMessage().
m_EnvironmentTemperature
protected float Environment::m_EnvironmentTemperature = 0 private
Definition at line 28 of file environment.c.
Referenced by GetDebugMessage(), GetTemperature(), ProcessItemsHeat(), and SetEnvironmentTemperature().
m_FeetParts
protected ref array<int> Environment::m_FeetParts private
Definition at line 48 of file environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_Fog
protected float Environment::m_Fog = 0 private
Definition at line 25 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_HeadParts
protected ref array<int> Environment::m_HeadParts private
Definition at line 46 of file environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_HeatBufferTimer
protected float Environment::m_HeatBufferTimer private
DEPRECATED.
Definition at line 39 of file environment.c.
Referenced by Init(), and ProcessItemsHeat().
m_HeatComfort
protected float Environment::m_HeatComfort private
Definition at line 20 of file environment.c.
Referenced by GetDebugMessage(), Init(), and ProcessItemsHeat().
m_HeatSourceTemp
protected float Environment::m_HeatSourceTemp private
Definition at line 38 of file environment.c.
Referenced by GetWetDelta().
m_IsInWater
protected bool Environment::m_IsInWater private
Definition at line 35 of file environment.c.
Referenced by CheckWaterContact(), Init(), and IsWaterContact().
m_IsTempSet
protected bool Environment::m_IsTempSet private
Definition at line 36 of file environment.c.
Referenced by IsTemperatureSet(), and SetEnvironmentTemperature().
m_IsUnderRoof
protected bool Environment::m_IsUnderRoof private
Definition at line 34 of file environment.c.
Referenced by CheckUnderRoof(), GetDebugMessage(), Init(), and IsUnderRoof().
m_ItemsWetnessMax
protected float Environment::m_ItemsWetnessMax private
Definition at line 11 of file environment.c.
Referenced by ApplyDrynessToItem(), ApplyWetnessToItem(), and Update().
m_Player
protected PlayerBase Environment::m_Player private
Definition at line 15 of file environment.c.
Referenced by ApplyDrynessToItem(), ApplyWetnessToItem(), BodyPartHeatProperties(), CalcTemperatureFromTemperatureSource(), CheckUnderRoof(), CheckWaterContact(), CollectAndSetPlayerData(), GatherTemperatureSources(), GetDebugMessage(), Init(), IsInsideBuilding(), IsInsideVehicle(), ProcessItemsDryness(), ProcessItemsHeat(), ProcessItemsWetness(), and Update().
m_PlayerHeat
protected float Environment::m_PlayerHeat private
Definition at line 19 of file environment.c.
Referenced by CollectAndSetPlayerData(), and GetWetDelta().
m_PlayerHeightPos
protected float Environment::m_PlayerHeightPos private
Definition at line 16 of file environment.c.
Referenced by CollectAndSetPlayerData(), and GetTemperatureHeightCorrection().
m_PlayerSpeed
protected float Environment::m_PlayerSpeed private
Definition at line 17 of file environment.c.
Referenced by CollectAndSetPlayerData(), GetPlayerHeat(), and Init().
m_PlayerTemperature
protected float Environment::m_PlayerTemperature private
Definition at line 18 of file environment.c.
m_Rain
protected float Environment::m_Rain = 0 private
Definition at line 23 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetWetDelta(), and IsRaining().
m_RoofCheckTimer
protected float Environment::m_RoofCheckTimer private
keeps wetness of most wet item in player's possesion
Definition at line 12 of file environment.c.
Referenced by GetDebugMessage(), Init(), and Update().
m_SlotIdsBottom
protected ref array<int> Environment::m_SlotIdsBottom private
Definition at line 43 of file environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsComplete
protected ref array<int> Environment::m_SlotIdsComplete private
Definition at line 41 of file environment.c.
Referenced by Init(), ProcessWetnessByRain(), and ProcessWetnessByWaterLevel().
m_SlotIdsLower
protected ref array<int> Environment::m_SlotIdsLower private
Definition at line 44 of file environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SlotIdsUpper
protected ref array<int> Environment::m_SlotIdsUpper private
Definition at line 42 of file environment.c.
Referenced by Init(), and ProcessWetnessByWaterLevel().
m_SurfaceType
protected string Environment::m_SurfaceType private
Definition at line 30 of file environment.c.
Referenced by CheckWaterContact(), GetWindModifierPerSurface(), and Init().
m_Time
protected float Environment::m_Time = 0 private
Definition at line 29 of file environment.c.
Referenced by Update().
m_UTemperatureSources
protected ref array<UTemperatureSource> Environment::m_UTemperatureSources private
Definition at line 53 of file environment.c.
Referenced by GatherTemperatureSources(), Init(), and ProcessTemperatureSources().
m_UTSAverageTemperature
protected float Environment::m_UTSAverageTemperature private
Definition at line 52 of file environment.c.
Referenced by GetEnvironmentTemperature(), GetUniversalSourcesTemperageAverage(), Init(), ProcessItemsHeat(), and ProcessTemperatureSources().
m_UTSAverageTemperatureBuffer
protected ref SimpleMovingAverage<float> Environment::m_UTSAverageTemperatureBuffer private
Definition at line 54 of file environment.c.
Referenced by Init(), and ProcessTemperatureSources().
m_WaterLevel
protected float Environment::m_WaterLevel private
Definition at line 33 of file environment.c.
Referenced by GetDebugMessage(), GetWetDelta(), Init(), and Update().
m_WetDryTick
protected float Environment::m_WetDryTick private
Definition at line 10 of file environment.c.
Referenced by Init(), and Update().
m_Wind
protected float Environment::m_Wind = 0 private
Definition at line 24 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), GetDebugMessage(), GetEnvironmentTemperature(), and GetWetDelta().
m_WindAverageBuffer
protected ref SimpleMovingAverage<float> Environment::m_WindAverageBuffer private
Definition at line 50 of file environment.c.
Referenced by CollectAndSetEnvironmentData(), and Init().
RAIN_LIMIT_LOW
const float Environment::RAIN_LIMIT_LOW = 0.05 private
Definition at line 3 of file environment.c.
Referenced by IsRaining().
WATER_LEVEL_HIGH
const float Environment::WATER_LEVEL_HIGH = 1.5 private
Definition at line 5 of file environment.c.
Referenced by GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_LOW
const float Environment::WATER_LEVEL_LOW = 0.5 private
Definition at line 7 of file environment.c.
Referenced by GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_MID
const float Environment::WATER_LEVEL_MID = 1.2 private
Definition at line 6 of file environment.c.
Referenced by GetWetDelta(), and ProcessWetnessByWaterLevel().
WATER_LEVEL_NONE
const float Environment::WATER_LEVEL_NONE = 0.15 private
Definition at line 8 of file environment.c.
Referenced by GetDebugMessage(), GetWetDelta(), and ProcessWetnessByWaterLevel().