DayzKode: InventoryActionHandler Class Reference
InventoryActionHandler Class Reference
Client only - manage set up crafting on client.
Private Member Functions
void DeactiveAction ()
void InventoryActionHandler (PlayerBase player)
bool IsActiveAction ()
void OnUpdate ()
void SetAction (ActionBase action, ActionTarget target, ItemBase main_item)
void SetAction (ActionBase action, ItemBase target_item, ItemBase main_item)
Private Attributes
const int IAH_CONTINUOUS = 2
const int IAH_SINGLE_USE = 1
ActionBase m_action
vector m_actionStartPos
bool m_isActive
ItemBase m_mainItem
PlayerBase m_player
ActionTarget m_target
bool m_useItemInHands
const float MIN_DISTANCE_TO_INTERRUPT = 1.0
Detailed Description
Client only - manage set up crafting on client.
Definition at line 2 of file inventoryactionhandler.c.
Constructor & Destructor Documentation
InventoryActionHandler()
void InventoryActionHandler::InventoryActionHandler (PlayerBase player) inline private
Definition at line 19 of file inventoryactionhandler.c.
    {
        m_player = player;
        m_isActive = false;
        m_action = null;
        m_target = null;
        m_mainItem = null;
        m_useItemInHands = false;
    }
References m_action, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
Member Function Documentation
DeactiveAction()
void InventoryActionHandler::DeactiveAction () inline private
Definition at line 105 of file inventoryactionhandler.c.
    {
        if( !m_isActive ) return;
        m_isActive = false;
        ActionManagerClient mngr;
        Class.CastTo(mngr, m_player.GetActionManager());
        mngr.EjectAction(m_action);
        mngr.ClearForceTarget();
        m_player.GetCraftingManager().ResetInventoryCraft();
        m_action = null;
        m_target = null;
        m_mainItem = null;
        m_useItemInHands = false;
    }
References Class::CastTo(), ActionManagerClient::ClearForceTarget(), ActionManagerClient::EjectAction(), m_action, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
Referenced by ActionManagerClient::OnActionEnd(), OnUpdate(), and ActionManagerClient::UnsetInventoryAction().
IsActiveAction()
bool InventoryActionHandler::IsActiveAction () inline private
Definition at line 63 of file inventoryactionhandler.c.
    {
        return m_isActive;
    }
References m_isActive.
OnUpdate()
void InventoryActionHandler::OnUpdate () inline private
Definition at line 68 of file inventoryactionhandler.c.
    {
        if( !m_isActive ) return;
        if( m_player.IsRaised() || m_player.GetCommand_Melee() )
        {
            DeactiveAction();
            return;
        }
        if( GetGame().IsInventoryOpen() )
        {
            DeactiveAction();
            return;
        }
        if (m_useItemInHands)
        {
            ItemBase handItem = m_player.GetItemInHands();
            if( handItem != m_mainItem )
            {
                DeactiveAction();
                return;
            }
        }
        if( Math.AbsFloat( vector.Distance(m_actionStartPos, m_player.GetPosition())) > MIN_DISTANCE_TO_INTERRUPT )
        {
            DeactiveAction();
            return;
        }
    }
References Math::AbsFloat(), DeactiveAction(), vector::Distance(), GetGame(), IsInventoryOpen(), m_actionStartPos, m_isActive, m_mainItem, m_player, m_useItemInHands, and MIN_DISTANCE_TO_INTERRUPT.
Referenced by ActionManagerClient::Update().
SetAction() [1/2]
void InventoryActionHandler::SetAction (ActionBase action, ActionTarget target, ItemBase main_item) inline private
Definition at line 42 of file inventoryactionhandler.c.
    {
        ActionManagerClient mngr;
        Class.CastTo(mngr, m_player.GetActionManager());
        m_action = action;
        m_target = target;
        m_mainItem = main_item;
        ItemBase itemInHand = m_player.GetItemInHands();
        m_useItemInHands = main_item == itemInHand;
        m_actionStartPos = m_player.GetPosition();
        m_isActive = true;
        //mngr.InjectAction( action, target, main_item );
        mngr.ForceTarget(m_target.GetObject());
        GetGame().GetMission().HideInventory();
    }
References Class::CastTo(), ActionManagerClient::ForceTarget(), GetGame(), CGame::GetMission(), Mission::HideInventory(), m_action, m_actionStartPos, m_isActive, m_mainItem, m_player, m_target, and m_useItemInHands.
SetAction() [2/2]
void InventoryActionHandler::SetAction (ActionBase action, ItemBase target_item, ItemBase main_item) inline private
Definition at line 30 of file inventoryactionhandler.c.
    {
        Object target_parent = null;
        if(target_item)
        {
            target_parent = target_item.GetHierarchyParent();
        }
        ActionTarget at = new ActionTarget(target_item, target_parent, -1, vector.Zero, -1);
        SetAction(action, at, main_item );
    }
References ActionTarget, SetAction(), and vector::Zero.
Referenced by SetAction(), and ActionManagerClient::SetInventoryAction().
Member Data Documentation
IAH_CONTINUOUS
const int InventoryActionHandler::IAH_CONTINUOUS = 2 private
Definition at line 16 of file inventoryactionhandler.c.
IAH_SINGLE_USE
const int InventoryActionHandler::IAH_SINGLE_USE = 1 private
Definition at line 15 of file inventoryactionhandler.c.
m_action
ActionBase InventoryActionHandler::m_action private
Definition at line 4 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), and SetAction().
m_actionStartPos
vector InventoryActionHandler::m_actionStartPos private
Definition at line 12 of file inventoryactionhandler.c.
Referenced by OnUpdate(), and SetAction().
m_isActive
bool InventoryActionHandler::m_isActive private
Definition at line 11 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), IsActiveAction(), OnUpdate(), and SetAction().
m_mainItem
ItemBase InventoryActionHandler::m_mainItem private
Definition at line 6 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
m_player
PlayerBase InventoryActionHandler::m_player private
Definition at line 9 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
m_target
ActionTarget InventoryActionHandler::m_target private
Definition at line 5 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), and SetAction().
m_useItemInHands
bool InventoryActionHandler::m_useItemInHands private
Definition at line 7 of file inventoryactionhandler.c.
Referenced by DeactiveAction(), InventoryActionHandler(), OnUpdate(), and SetAction().
MIN_DISTANCE_TO_INTERRUPT
const float InventoryActionHandler::MIN_DISTANCE_TO_INTERRUPT = 1.0 private
Definition at line 14 of file inventoryactionhandler.c.
Referenced by OnUpdate().