DayzKode: PlayerAgentPool Class Reference
PlayerAgentPool Class Reference
Private Member Functions
void AddAgent (int agent_id, float count)
void AntibioticsAttack (float attack_value)
void DigestAgent (int agent_id, float count)
int GetAgents ()
void GetDebugObject (array< ref Param > object_out)
int GetSingleAgentCount (int agent_id)
int GetStorageVersion ()
float GetTotalAgentCount ()
void GrowAgents (float deltaT)
void ImmuneSystemTick (float value, float deltaT)
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnStoreSave (ParamsWriteContext ctx)
void PlayerAgentPool (PlayerBase player)
void PrintAgents ()
void RemoteGrowRequestDebug (ParamsReadContext ctx)
void RemoveAgent (int agent_id)
void RemoveAllAgents ()
void SetAgentCount (int agent_id, float count)
void SpawnAgents (float deltaT)
void ~PlayerAgentPool ()
Private Attributes
int m_AgentMask
float m_LastTicked = 0
PlayerBase m_Player
PluginTransmissionAgents m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents))
float m_TotalAgentCount
ref map< int, float > m_VirusPool = new map<int,float>
ref array< int > m_VirusPoolArray = new array<int>
const int STORAGE_VERSION = 100
Detailed Description
Definition at line 1 of file playeragentpool.c.
Constructor & Destructor Documentation
PlayerAgentPool()
void PlayerAgentPool::PlayerAgentPool (PlayerBase player) inline private
Definition at line 14 of file playeragentpool.c.
    {
        m_Player = player;
    }
References m_Player.
~PlayerAgentPool()
void PlayerAgentPool::~PlayerAgentPool () inline private
Definition at line 19 of file playeragentpool.c.
    {
    }
Member Function Documentation
AddAgent()
void PlayerAgentPool::AddAgent (int agent_id, float count) inline private
Definition at line 139 of file playeragentpool.c.
    {
        int max_count = m_PluginTransmissionAgents.GetAgentMaxCount(agent_id);
        if( !m_VirusPool.Contains(agent_id) && count > 0 )//if it contains, maybe add count only ?
        {
            //m_VirusPool.Insert( agent_id, Math.Clamp(count,0,max_count) );
            SetAgentCount(agent_id,count);
        }
        else
        {
            float new_value = m_VirusPool.Get(agent_id) + count;
            //Print(new_value);
            SetAgentCount(agent_id,new_value);
        }
    }
References m_PluginTransmissionAgents, m_VirusPool, and SetAgentCount().
Referenced by DigestAgent(), RemoteGrowRequestDebug(), and SpawnAgents().
AntibioticsAttack()
void PlayerAgentPool::AntibioticsAttack (float attack_value) inline private
Definition at line 251 of file playeragentpool.c.
    {
        for(int i = 0; i < m_VirusPool.Count(); i++)
        {
            int agent_id = m_VirusPool.GetKey(i);
            float antibiotics_resistance = 1 - m_PluginTransmissionAgents.GetAgentAntiboticsResistanceEx(agent_id, m_Player);
            float delta = attack_value * antibiotics_resistance;
            float old_count = m_VirusPool.Get( agent_id );
            float new_count = old_count - delta;
            //PrintString("delta:"+delta.ToString());
            //PrintString("old_count:"+old_count.ToString());
            //PrintString("new_count:"+new_count.ToString());
            SetAgentCount(agent_id, new_count);
        }
    }
References m_Player, m_PluginTransmissionAgents, m_VirusPool, and SetAgentCount().
DigestAgent()
void PlayerAgentPool::DigestAgent (int agent_id, float count) inline private
Definition at line 134 of file playeragentpool.c.
    {
        AddAgent(agent_id, m_PluginTransmissionAgents.GetAgentDigestibility(agent_id) * count);
    }
References AddAgent(), and m_PluginTransmissionAgents.
GetAgents()
int PlayerAgentPool::GetAgents () inline private
Definition at line 190 of file playeragentpool.c.
    {
        return m_AgentMask;
    }
References m_AgentMask.
GetDebugObject()
void PlayerAgentPool::GetDebugObject (array< ref Param > object_out) inline private
Definition at line 284 of file playeragentpool.c.
    {
        int count = m_PluginTransmissionAgents.GetAgentList().Count();
        for(int i = 0; i < count;i++)
        {
            AgentBase agent = m_PluginTransmissionAgents.GetAgentList().GetElement(i);
            string agent_name = agent.GetName();
            int agent_id = agent.GetAgentType();
            int max_agents = m_PluginTransmissionAgents.GetAgentMaxCount(agent_id);
            string amount = GetSingleAgentCount(agent_id).ToString() + "/" + max_agents.ToString();
            object_out.Insert( new Param3<string,string, int>(agent_name, amount, agent_id) );
        }
        object_out.InsertAt(new Param1<int>(count) ,0);
    }
References GetSingleAgentCount(), and m_PluginTransmissionAgents.
GetSingleAgentCount()
int PlayerAgentPool::GetSingleAgentCount (int agent_id) inline private
Definition at line 195 of file playeragentpool.c.
    {
        if( m_VirusPool.Contains(agent_id) )
        {
            return m_VirusPool.Get( agent_id );
        }
        else return 0;
    }
References m_VirusPool.
Referenced by GetDebugObject(), and SpawnAgents().
GetStorageVersion()
int PlayerAgentPool::GetStorageVersion () inline private
Definition at line 24 of file playeragentpool.c.
    {
        return STORAGE_VERSION;
    }
References STORAGE_VERSION.
GetTotalAgentCount()
float PlayerAgentPool::GetTotalAgentCount () inline private
Definition at line 204 of file playeragentpool.c.
    {
        float agent_count;
        for(int i = 0; i < m_VirusPool.Count(); i++)
        {
            agent_count += m_VirusPool.GetElement(i);
        }
        return agent_count;
    }
References m_VirusPool.
GrowAgents()
void PlayerAgentPool::GrowAgents (float deltaT) inline private
Definition at line 48 of file playeragentpool.c.
    {
        if ( !IsPluginManagerExists() )//check if modules are running
            return;
        EStatLevels immunity_level = m_Player.GetImmunityLevel();
        m_TotalAgentCount = 0;
        for(int i = 0; i < m_VirusPool.Count(); i++)
        {
            int agent_id = m_VirusPool.GetKey(i);
            int max_count = m_PluginTransmissionAgents.GetAgentMaxCount( agent_id );
            EStatLevels agent_potency = m_PluginTransmissionAgents.GetAgentPotencyEx( agent_id, m_Player );
            float grow_delta;
            if( agent_potency <= immunity_level )
            {
                bool grow_during_antibiotics = m_PluginTransmissionAgents.GrowDuringAntibioticsAttack(agent_id, m_Player);
                if (m_Player.IsAntibioticsActive() && !grow_during_antibiotics)
                    continue;
                float invasibility = m_PluginTransmissionAgents.GetAgentInvasibilityEx( agent_id, m_Player );
                grow_delta = invasibility * deltaT;
            }
            else
            {
                float dieoff_speed = m_PluginTransmissionAgents.GetAgentDieOffSpeedEx( agent_id, m_Player );
                grow_delta = -dieoff_speed * deltaT;
            }
            //Print( agent_id );
            //Print( grow_delta );
            float old_count = m_VirusPool.Get( agent_id );
            float new_count = old_count + grow_delta;
            new_count = Math.Clamp(new_count, 0,max_count);
            m_TotalAgentCount += new_count;
            SetAgentCount(agent_id, new_count);
        }
    }
References Math::Clamp(), IsPluginManagerExists(), m_Player, m_PluginTransmissionAgents, m_TotalAgentCount, m_VirusPool, and SetAgentCount().
Referenced by ImmuneSystemTick().
ImmuneSystemTick()
void PlayerAgentPool::ImmuneSystemTick (float value, float deltaT) inline private
Definition at line 42 of file playeragentpool.c.
    {
        SpawnAgents(deltaT);
        GrowAgents(deltaT);
    }
References GrowAgents(), and SpawnAgents().
OnStoreLoad()
bool PlayerAgentPool::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 105 of file playeragentpool.c.
    {
        //Debug.Log("PlayerAgentPool OnStoreLoad called", "Agents");
        int count;
        if(!ctx.Read(count))
        {
            return false;
        }
        for(int i = 0; i < count;i++)
        {
            int key;
            int value;
            if(!ctx.Read(key))
            {
                return false;
            }
            if(!ctx.Read(value))
            {
                return false;
            }
            SetAgentCount( key,value );
        }
        return true;
    }
References Serializer::Read(), and SetAgentCount().
OnStoreSave()
void PlayerAgentPool::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 91 of file playeragentpool.c.
    {
        //Debug.Log("PlayerAgentPool OnStoreSave called", "Agents");
        ctx.Write( m_VirusPool.Count() );
        for(int i = 0; i < m_VirusPool.Count();i++)
        {
            int key = m_VirusPool.GetKey(i);
            int value = m_VirusPool.GetElement(i);
            ctx.Write( key );
            ctx.Write( value );
        }
    }
References m_VirusPool, and Serializer::Write().
PrintAgents()
void PlayerAgentPool::PrintAgents () inline private
Definition at line 29 of file playeragentpool.c.
    {
        if( m_VirusPool )
        {
            for(int i = 0; i < m_VirusPool.Count(); i++)
            {
                Debug.Log("Agent: "+ m_VirusPool.GetKey(i).ToString(), "Agents");
                Debug.Log("Count: "+ m_VirusPool.GetElement(i).ToString(), "Agents");
            }
        }
    }
References Debug::Log(), and m_VirusPool.
RemoteGrowRequestDebug()
void PlayerAgentPool::RemoteGrowRequestDebug (ParamsReadContext ctx) inline private
Definition at line 268 of file playeragentpool.c.
    {
        ctx.Read(CachedObjectsParams.PARAM1_INT);
        int id = CachedObjectsParams.PARAM1_INT.param1;
        int max = m_PluginTransmissionAgents.GetAgentMaxCount(Math.AbsInt(id));
        int grow = max / 10;
        if(id > 0)
        {
            AddAgent(id, grow);
        }
        else if( id < 0)
        {
            AddAgent(-id, -grow);
        }
    }
References Math::AbsInt(), AddAgent(), m_PluginTransmissionAgents, CachedObjectsParams::PARAM1_INT, and Serializer::Read().
RemoveAgent()
void PlayerAgentPool::RemoveAgent (int agent_id) inline private
Definition at line 165 of file playeragentpool.c.
    {
        SetAgentCount(agent_id, 0);
    }
References SetAgentCount().
RemoveAllAgents()
void PlayerAgentPool::RemoveAllAgents () inline private
Definition at line 170 of file playeragentpool.c.
    {
        m_AgentMask = 0;
        m_VirusPool.Clear();
    }
References m_AgentMask, and m_VirusPool.
SetAgentCount()
void PlayerAgentPool::SetAgentCount (int agent_id, float count) inline private
Definition at line 230 of file playeragentpool.c.
    {
        if(count > 0)
        {
            //Debug.Log("+ growing agent"+ agent_id.ToString() +"to count: "+count.ToString(), "Agents");
            m_VirusPool.Set( agent_id, count);
            m_AgentMask = m_AgentMask | agent_id;
        }
        else
        {
            //Debug.Log("- REMOVING agent"+ agent_id.ToString(), "Agents");
            m_VirusPool.Remove( agent_id );
            m_AgentMask = m_AgentMask & ~agent_id;
        }
        if(m_Player.m_Agents != m_AgentMask)
        {
            m_Player.m_Agents = m_AgentMask;
            m_Player.SetSynchDirty();
        }
    }
References m_AgentMask, m_Player, and m_VirusPool.
Referenced by AddAgent(), AntibioticsAttack(), GrowAgents(), OnStoreLoad(), and RemoveAgent().
SpawnAgents()
void PlayerAgentPool::SpawnAgents (float deltaT) inline private
Definition at line 214 of file playeragentpool.c.
    {
        int count = m_PluginTransmissionAgents.GetAgentList().Count();
        for(int i = 0; i < count;i++)
        {
            AgentBase agent = m_PluginTransmissionAgents.GetAgentList().GetElement(i);
            int agent_id = agent.GetAgentType();
            if( GetSingleAgentCount(agent_id)==0 && agent.AutoinfectCheck(deltaT, m_Player) )
            {
                AddAgent(agent_id,100);
            }
        }
    }
References AddAgent(), GetSingleAgentCount(), m_Player, and m_PluginTransmissionAgents.
Referenced by ImmuneSystemTick().
Member Data Documentation
m_AgentMask
int PlayerAgentPool::m_AgentMask private
Definition at line 8 of file playeragentpool.c.
Referenced by GetAgents(), RemoveAllAgents(), and SetAgentCount().
m_LastTicked
float PlayerAgentPool::m_LastTicked = 0 private
Definition at line 5 of file playeragentpool.c.
m_Player
PlayerBase PlayerAgentPool::m_Player private
Definition at line 7 of file playeragentpool.c.
Referenced by AntibioticsAttack(), GrowAgents(), PlayerAgentPool(), SetAgentCount(), and SpawnAgents().
m_PluginTransmissionAgents
PluginTransmissionAgents PlayerAgentPool::m_PluginTransmissionAgents = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents)) private
Definition at line 12 of file playeragentpool.c.
Referenced by AddAgent(), AntibioticsAttack(), DigestAgent(), GetDebugObject(), GrowAgents(), RemoteGrowRequestDebug(), and SpawnAgents().
m_TotalAgentCount
float PlayerAgentPool::m_TotalAgentCount private
Definition at line 6 of file playeragentpool.c.
Referenced by GrowAgents().
m_VirusPool
ref map<int,float> PlayerAgentPool::m_VirusPool = new map<int,float> private
Definition at line 3 of file playeragentpool.c.
Referenced by AddAgent(), AntibioticsAttack(), GetSingleAgentCount(), GetTotalAgentCount(), GrowAgents(), OnStoreSave(), PrintAgents(), RemoveAllAgents(), and SetAgentCount().
m_VirusPoolArray
ref array<int> PlayerAgentPool::m_VirusPoolArray = new array<int> private
Definition at line 4 of file playeragentpool.c.
STORAGE_VERSION
const int PlayerAgentPool::STORAGE_VERSION = 100 private
Definition at line 10 of file playeragentpool.c.
Referenced by GetStorageVersion().