DayzKode: UIManager Class Reference
UIManager Class Reference
Private Member Functions
bool Back ()
Close top window on windows stack, returns true when any window is closed.
bool CloseAll ()
Close all opened menus.
bool CloseAllSubmenus ()
Close all opened menus except first menu.
proto native void CloseDialog ()
bool CloseMenu (int id)
Close menu with specific ID (see MenuID)
proto native void CloseSpecificDialog (int id)
void CloseWindow (int id)
UIScriptedMenu CreateScriptedMenu (int id, UIMenuPanel parent)
void DeleteWindow (UIScriptedWindow window)
proto native UIScriptedMenu EnterScriptedMenu (int id, UIMenuPanel parent)
Create & open menu with specific id (see MenuID) and set its parent.
proto native void EnterServerBrowser (UIMenuPanel parentMenu)
UIScriptedMenu FindMenu (int id)
Returns menu with specific ID if it is open (see MenuID)
proto native int GetLoginQueuePosition ()
proto native UIScriptedMenu GetMenu ()
Returns most-top open menu.
proto native Widget GetWidgetUnderCursor ()
proto native void HideDialog ()
bool HideMenu (int id)
proto native void HideScriptedMenu (UIScriptedMenu menu)
proto native bool IsCursorVisible ()
proto native bool IsDialogQueued ()
proto native bool IsDialogVisible ()
bool IsMenuOpen (int id)
Returns true if menu with specific ID is opened (see MenuID)
proto native bool IsModalVisible ()
proto native bool IsScaledMode ()
bool IsWindowOpened (int id)
void OpenWindow (int id)
proto native void ScreenFadeIn (float duration, string text, int backgroundColor, int textColor)
proto native void ScreenFadeOut (float duration)
proto native bool ScreenFadeVisible ()
proto native void SetScaledMode (bool enabled)
proto native bool ShowCursor (bool visible)
proto native void ShowDialog (string caption, string text, int id, int butts, int def, int type, UIScriptedMenu handler)
Shows message dialog.
proto native bool ShowQueuedDialog ()
proto native UIScriptedMenu ShowScriptedMenu (UIScriptedMenu menu, UIMenuPanel parent)
void ShowUICursor (bool visible)
Detailed Description
Definition at line 1 of file uimanager.c.
Member Function Documentation
Back()
bool UIManager::Back () inline private
Close top window on windows stack, returns true when any window is closed.
Definition at line 64 of file uimanager.c.
    {
        if (IsDialogVisible() == false)
        {
            UIMenuPanel menu = GetMenu();
            if (menu)
            {
                menu.Close();
                return true;
            }
        }
        return false;
    }
References UIMenuPanel::Close(), GetMenu(), and IsDialogVisible().
Referenced by UIScriptedMenu::Apply(), Back(), UIScriptedMenu::Back(), UIScriptedMenu::ChangeAccount(), UIScriptedMenu::CloseMenu(), PluginBase::EditorToggle(), UIScriptedMenu::OnClick(), UIScriptedMenu::OnModalResult(), UIScriptedMenu::StopVideo(), PluginBase::ToggleCameraTools(), and UIScriptedMenu::Update().
CloseAll()
bool UIManager::CloseAll () inline private
Close all opened menus.
Definition at line 80 of file uimanager.c.
    {
        UIMenuPanel menu = GetMenu();
        while (menu)
        {
            if (menu.GetParentMenu())
            {
                menu = menu.GetParentMenu();
            }
            else
            {
                menu.Close();
                return true;
            }
        }
        return false;
    }
References UIMenuPanel::Close(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by MissionBase::CloseAllMenus(), ManBase::CloseInventoryMenu(), MissionBase::DestroyAllMenus(), UIScriptedMenu::GameRetry(), MissionBase::HandleMapToggleByKeyboardShortcut(), OnLoginTimeEvent(), MissionBase::OnMissionFinish(), ManBase::OnPlayerLoaded(), OnRespawnEvent(), ActionUnfoldMapCB::PerformMapChange(), and UpdateLoginQueue().
CloseAllSubmenus()
bool UIManager::CloseAllSubmenus () inline private
Close all opened menus except first menu.
Definition at line 100 of file uimanager.c.
    {
        UIMenuPanel menu = GetMenu();
        while (menu && menu.GetParentMenu() && menu.GetParentMenu().GetParentMenu())
        {
            menu = menu.GetParentMenu();
        }
        if (menu && menu.GetParentMenu())
        {
            menu.Close();
            return true;
        }
        return false;
    }
References UIMenuPanel::Close(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by BiosSessionService::OnGetSessionError(), BiosUserManager::OnJoin(), BiosUserManager::OnSignedOut(), BiosUserManager::OnUserLoggedOn(), and BiosSessionService::TryGetSession().
CloseDialog()
proto native void UIManager::CloseDialog () private
Referenced by DeleteGamepadDisconnectMenu(), LockControls(), BiosUserManager::OnSignedOut(), ManBase::OnUnconsciousStop(), and BiosUserManager::OnUserLoggedOn().
CloseMenu()
bool UIManager::CloseMenu (int id) inline private
Close menu with specific ID (see MenuID)
Definition at line 119 of file uimanager.c.
    {
        UIMenuPanel menu = GetMenu();
        while (menu)
        {if (menu.GetID() == id)
            {
                menu.Close();
                return true;
            }
            menu = menu.GetParentMenu();
        }
        return false;
    }
References UIMenuPanel::Close(), UIMenuPanel::GetID(), GetMenu(), and UIMenuPanel::GetParentMenu().
Referenced by MissionBase::Continue(), BiosUserManager::OnJoin(), and BiosUserManager::OnPartyHost().
CloseSpecificDialog()
proto native void UIManager::CloseSpecificDialog (int id) private
CloseWindow()
void UIManager::CloseWindow (int id) inline private
Definition at line 210 of file uimanager.c.
    {
        UIScriptedWindow window = UIScriptedWindow.GetWindow( id );
        if ( window )
        {
            UIScriptedWindow.RemoveFromActiveWindows( id );
            window.HideWindow();
            //delete window;
            GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(this.DeleteWindow, window );
            /*
            wtf? leak
            Timer delete_timer = new Timer ( CALL_CATEGORY_SYSTEM );
            Param1<UIScriptedWindow> params = new Param1<UIScriptedWindow>( window );
            delete_timer.Run( 0.5, this, "DeleteWindow", params, false );*/
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, DeleteWindow(), CGame::GetCallQueue(), GetGame(), UIScriptedWindow::GetWindow(), UIScriptedWindow::HideWindow(), and UIScriptedWindow::RemoveFromActiveWindows().
Referenced by UIScriptedWindow::CloseWindow(), and OpenWindow().
CreateScriptedMenu()
UIScriptedMenu UIManager::CreateScriptedMenu (int id, UIMenuPanel parent) inline private
Definition at line 17 of file uimanager.c.
    {
        UIScriptedMenu menu = EnterScriptedMenu(id, parent);
        HideScriptedMenu( menu );
        return menu;
    }
References EnterScriptedMenu(), and HideScriptedMenu().
DeleteWindow()
void UIManager::DeleteWindow (UIScriptedWindow window) inline private
Definition at line 230 of file uimanager.c.
    {
        delete window;
    }
Referenced by CloseWindow().
EnterScriptedMenu()
proto native UIScriptedMenu UIManager::EnterScriptedMenu (int id, UIMenuPanel parent) private
Create & open menu with specific id (see MenuID) and set its parent.
Referenced by CreateScriptedMenu(), PluginBase::EditorToggle(), MissionBase::HandleMapToggleByKeyboardShortcut(), BiosUserManager::OnPartyHost(), UIScriptedMenu::OpenMenu(), MissionBase::Pause(), ActionUnfoldMapCB::PerformMapChange(), SelectGamepad(), MissionBase::ShowChat(), and PluginBase::ToggleCameraTools().
EnterServerBrowser()
proto native void UIManager::EnterServerBrowser (UIMenuPanel parentMenu) private
FindMenu()
UIScriptedMenu UIManager::FindMenu (int id) inline private
Returns menu with specific ID if it is open (see MenuID)
Definition at line 161 of file uimanager.c.
    {
        UIScriptedMenu menu = GetMenu();
        while (menu)
        {
            if (menu.GetID() == id)
            {
                return menu;
            }
            menu = UIScriptedMenu.Cast( menu.GetParentMenu() );
        }
        return NULL;
    }
References GetMenu().
Referenced by ManBase::CloseMapEx(), UIScriptedMenu::Init(), IsMenuOpen(), UIScriptedMenu::OnClick(), ActionUnfoldMapCB::OnFinish(), ActionReadPaperCB::OnStateChange(), ActionWritePaperCB::OnStateChange(), ManBase::OnUnconsciousStop(), MissionBase::OnUpdate(), InventoryItem::OnVariablesSynchronized(), Hud::RefreshQuickbar(), and EntityAI::UpdateInventoryMenu().
GetLoginQueuePosition()
proto native int UIManager::GetLoginQueuePosition () private
Referenced by UpdateLoginQueue().
GetMenu()
proto native UIScriptedMenu UIManager::GetMenu () private
Returns most-top open menu.
Referenced by PluginBase::AddKeyframe(), Back(), CloseAll(), CloseAllSubmenus(), ManBase::CloseInventoryMenu(), CloseMenu(), MissionBase::Continue(), PluginBase::CursorHide(), PluginBase::CursorShow(), PluginBase::DeleteKeyframe(), MissionBaseWorld::DumpCurrentUILayout(), FindMenu(), Icon::FlagAction(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), HideMenu(), PluginBase::IsCurrentUIPageValid(), PluginBase::IsInConsole(), PluginBase::IsIngame(), BiosUserManager::OnGameNameChanged(), OnLoginTimeEvent(), ScriptedWidgetEventHandler::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), OnRespawnEvent(), MissionBase::OnUpdate(), PluginBase::PlayPause(), PluginBase::Save(), Dispatcher::SceneEditorCommand(), Dispatcher::ScriptConsoleAddPrint(), Dispatcher::ScriptConsoleGetSelectedItem(), Dispatcher::ScriptConsoleHistoryBack(), Dispatcher::ScriptConsoleHistoryForward(), SelectGamepad(), ScriptedWidgetEventHandler::SelectPlayer(), SetDatabaseID(), ScriptedWidgetEventHandler::ShowActionMenu(), HandsContainer::ShowActionMenuCombine(), Icon::ShowActionMenuCombine(), MissionBase::ShowInventory(), PluginBase::SpawnFromClipboard(), and UpdateLoginQueue().
GetWidgetUnderCursor()
proto native Widget UIManager::GetWidgetUnderCursor () private
HideDialog()
proto native void UIManager::HideDialog () private
Referenced by MissionBase::DestroyAllMenus(), and MissionBase::OnMissionFinish().
HideMenu()
bool UIManager::HideMenu (int id) inline private
Definition at line 136 of file uimanager.c.
    {
        UIScriptedMenu menu = GetMenu();
        while (menu)
        {
            if (menu.GetID() == id)
            {
                HideScriptedMenu( menu );
                return true;
            }
            menu = UIScriptedMenu.Cast( menu.GetParentMenu() );
        }
        return false;
    }
References GetMenu(), and HideScriptedMenu().
HideScriptedMenu()
proto native void UIManager::HideScriptedMenu (UIScriptedMenu menu) private
Referenced by CreateScriptedMenu(), MissionBase::HideInventory(), and HideMenu().
IsCursorVisible()
proto native bool UIManager::IsCursorVisible () private
IsDialogQueued()
proto native bool UIManager::IsDialogQueued () private
IsDialogVisible()
proto native bool UIManager::IsDialogVisible () private
Referenced by Back(), and MissionBase::OnUpdate().
IsMenuOpen()
bool UIManager::IsMenuOpen (int id) inline private
Returns true if menu with specific ID is opened (see MenuID)
Definition at line 155 of file uimanager.c.
    {
        return FindMenu(id) != null;
    }
References FindMenu().
Referenced by MissionBase::HandleMapToggleByKeyboardShortcut(), MissionBase::IsPaused(), Update(), and ActionManagerClient::Update().
IsModalVisible()
proto native bool UIManager::IsModalVisible () private
IsScaledMode()
proto native bool UIManager::IsScaledMode () private
IsWindowOpened()
bool UIManager::IsWindowOpened (int id) inline private
Definition at line 235 of file uimanager.c.
    {
        if ( UIScriptedWindow.GetWindow( id ) )
        {
            return true;
        }
        return false;
    }
References UIScriptedWindow::GetWindow().
OpenWindow()
void UIManager::OpenWindow (int id) inline private
Definition at line 179 of file uimanager.c.
    {
        UIScriptedWindow window = UIScriptedWindow.GetWindow( id );
        //if window is already opened, close it
        if ( window )
        {
            CloseWindow( id );
            return;
        }
        //create new window
        switch( id )
        {
            case GUI_WINDOW_MISSION_LOADER:
                window = GetGame().GetMission().CreateScriptedWindow( id );
                break;
            default: {};
        }
        if ( window )
        {
            window.Init();
            //add to active windows
            UIScriptedWindow.AddToActiveWindows( id, window );
        }
    }
References UIScriptedWindow::AddToActiveWindows(), CloseWindow(), Mission::CreateScriptedWindow(), GetGame(), CGame::GetMission(), UIScriptedWindow::GetWindow(), GUI_WINDOW_MISSION_LOADER, and UIScriptedWindow::Init().
ScreenFadeIn()
proto native void UIManager::ScreenFadeIn (float duration, string text, int backgroundColor, int textColor) private
Referenced by ShowDeadScreen(), and ManBase::ShowUnconsciousScreen().
ScreenFadeOut()
proto native void UIManager::ScreenFadeOut (float duration) private
Referenced by UIScriptedMenu::Init(), LoadProgressUpdate(), MissionBase::OnUpdate(), ShowDeadScreen(), and ManBase::ShowUnconsciousScreen().
ScreenFadeVisible()
proto native bool UIManager::ScreenFadeVisible () private
SetScaledMode()
proto native void UIManager::SetScaledMode (bool enabled) private
ShowCursor()
proto native bool UIManager::ShowCursor (bool visible) private
Referenced by UIScriptedMenu::OnHide(), UIScriptedMenu::OnMouseButtonDown(), UIScriptedMenu::Play(), ShowUICursor(), and UIScriptedMenu::Stop().
ShowDialog()
proto native void UIManager::ShowDialog (string caption, string text, int id, int butts, int def, int type, UIScriptedMenu handler) private
Shows message dialog.
Parameters
caption
text
id custom user id
butts DialogBoxType
def DialogBoxButton
type DialogMessageType
handler
usage :
const int QUIT_DIALOG_ID = 76;
GetGame().GetUIManager().ShowDialog("Quit", "Do You really want to quit?", QUIT_DIALOG_ID, DBT_YESNO, DBB_YES, DMT_QUESTION, this);
...
// after user pass dialog, callback on menu/event handler is called
ScriptedWidgetEventHandler::OnModalResult(Widget  w, int  x, int  y, int  code,  int  result)
{
  if (code == QUIT_DIALOG_ID && result == DBB_YES) // yes this is callback for dialog we show earlier and user press YES button
  {
      Quit();
  }
}
Referenced by UIScriptedMenu::Exit(), HandleError(), UIScriptedMenu::Init(), OnlineServices::OnAutoConnectToEmptyServer(), UIScriptedMenu::OnClick(), ScriptedWidgetEventHandler::OnClick(), UIScriptedMenu::OnClick_Respawn(), UIScriptedMenu::Play(), and BiosSessionService::TryGetSession().
ShowQueuedDialog()
proto native bool UIManager::ShowQueuedDialog () private
Referenced by CheckDialogs().
ShowScriptedMenu()
proto native UIScriptedMenu UIManager::ShowScriptedMenu (UIScriptedMenu menu, UIMenuPanel parent) private
Referenced by OnLoginTimeEvent(), MissionBase::ShowInventory(), and UpdateLoginQueue().
ShowUICursor()
void UIManager::ShowUICursor (bool visible) inline private
Definition at line 246 of file uimanager.c.
    {
        ShowCursor( visible );
    }
References ShowCursor().
Referenced by ScriptedWidgetEventHandler::Apply(), PluginBase::CaptureFocus(), CaptureFocus(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), Inventory(), UIMenuPanel::LockControls(), LockControls(), UIScriptedMenu::OnHide(), MissionBase::OnMissionStart(), UIScriptedMenu::OnShow(), PluginBase::ReleaseFocus(), ReleaseFocus(), PluginBase::SetDeveloperItemClientEx(), ToggleDebugWindowEvent(), PluginBase::ToggleFocus(), and UIMenuPanel::UnlockControls().