DayzKode: AITargetCallbacksPlayer Class Reference
AITargetCallbacksPlayer Class Reference
Private Member Functions
void AITargetCallbacksPlayer (PlayerBase pPlayer)
override vector GetHeadPositionWS ()
override float GetMaxVisionRangeModifier (EntityAI pApplicant)
override vector GetVisionPointPositionWS (EntityAI pApplicant)
Static Private Member Functions
static int StanceToMovementIdxTranslation (HumanMovementState pState)
Private Attributes
private int m_iChestBoneIndex
private int m_iHeadBoneIndex
private PlayerBase m_Player
Detailed Description
Definition at line 1 of file aitargetcallbacksplayer.c.
Constructor & Destructor Documentation
AITargetCallbacksPlayer()
void AITargetCallbacksPlayer::AITargetCallbacksPlayer (PlayerBase pPlayer) inline private
Definition at line 3 of file aitargetcallbacksplayer.c.
    {
        m_Player = pPlayer;
        m_iHeadBoneIndex = m_Player.GetBoneIndexByName("Head");
        m_iChestBoneIndex = m_Player.GetBoneIndexByName("Spine3");
    }
References m_iChestBoneIndex, m_iHeadBoneIndex, and m_Player.
Member Function Documentation
GetHeadPositionWS()
override vector AITargetCallbacksPlayer::GetHeadPositionWS () inline private
Definition at line 11 of file aitargetcallbacksplayer.c.
    {
        if( m_iHeadBoneIndex != -1 )
            return m_Player.GetBonePositionWS(m_iHeadBoneIndex);
        else
            return m_Player.GetPosition() + "0 1.7 0";
    }
References m_iHeadBoneIndex, and m_Player.
Referenced by GetVisionPointPositionWS().
GetMaxVisionRangeModifier()
override float AITargetCallbacksPlayer::GetMaxVisionRangeModifier (EntityAI pApplicant) inline private
player speed mofifications
stance modification
player visibility modification (from cloths)
mean value of the coefs
Definition at line 43 of file aitargetcallbacksplayer.c.
    {
        HumanMovementState state = new HumanMovementState;
        m_Player.GetMovementState(state);
        float mod = 1.0;
        float speedCoef = PlayerConstants.AI_VISIBILITY_RUN;
        float stanceCoef = PlayerConstants.AI_VISIBILITY_STANDING;
        float playerVisCoef = 1.0; //Use disabled since 1.12
        switch(AITargetCallbacksPlayer.StanceToMovementIdxTranslation(state))
        {
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
                speedCoef = PlayerConstants.AI_VISIBILITY_WALK;
                break;
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
                speedCoef = PlayerConstants.AI_VISIBILITY_IDLE;
                break;
        }
        switch(state.m_iStanceIdx)
        {
            case DayZPlayerConstants.STANCEIDX_CROUCH:
            case DayZPlayerConstants.STANCEIDX_RAISEDCROUCH:
                stanceCoef = PlayerConstants.AI_VISIBILITY_CROUCH;
                break;
            case DayZPlayerConstants.STANCEIDX_PRONE:
            case DayZPlayerConstants.STANCEIDX_RAISEDPRONE:
                stanceCoef = PlayerConstants.AI_VISIBILITY_PRONE;
                break;
        }
        //playerVisCoef = m_Player.GetVisibilityCoef();
        mod = (speedCoef + stanceCoef /*+ playerVisCoef*/) / 2;
        return mod;
    }
References PlayerConstants::AI_VISIBILITY_CROUCH, PlayerConstants::AI_VISIBILITY_IDLE, PlayerConstants::AI_VISIBILITY_PRONE, PlayerConstants::AI_VISIBILITY_RUN, PlayerConstants::AI_VISIBILITY_STANDING, PlayerConstants::AI_VISIBILITY_WALK, HumanMovementState::m_iStanceIdx, m_Player, and StanceToMovementIdxTranslation().
GetVisionPointPositionWS()
override vector AITargetCallbacksPlayer::GetVisionPointPositionWS (EntityAI pApplicant) inline private
Definition at line 19 of file aitargetcallbacksplayer.c.
    {
        DayZInfected infected = DayZInfected.Cast(pApplicant);
        if( infected )
        {
            DayZInfectedInputController ic = infected.GetInputController();
            if( ic )
            {
                int mindState = ic.GetMindState();
                if( mindState >= DayZInfectedConstants.MINDSTATE_ALERTED )
                {
                    return GetHeadPositionWS();
                }
                else
                {
                    if( m_iChestBoneIndex != -1 )
                        return m_Player.GetBonePositionWS(m_iChestBoneIndex);
                }
            }
        }
        return m_Player.GetPosition() + "0 1 0";
    }
References GetHeadPositionWS(), DayZInfectedInputController::GetMindState(), m_iChestBoneIndex, and m_Player.
StanceToMovementIdxTranslation()
static int AITargetCallbacksPlayer::StanceToMovementIdxTranslation (HumanMovementState pState) inline static private
Translates players speed (idx) and corrects it by current stance used mainly for visibility/audibility of player to AI
Definition at line 90 of file aitargetcallbacksplayer.c.
    {
        int movementSpeed = 0;
        switch (pState.m_iStanceIdx)
        {
        case DayZPlayerConstants.STANCEIDX_CROUCH:
            switch (pState.m_iMovement)
            {
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
                movementSpeed = DayZPlayerConstants.MOVEMENTIDX_IDLE;
                break;
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
                movementSpeed = DayZPlayerConstants.MOVEMENTIDX_WALK;
                break;
            case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
                movementSpeed = DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN;
                break;
            }
            break;
        case DayZPlayerConstants.STANCEIDX_PRONE:
            switch (pState.m_iMovement)
            {
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
                movementSpeed = DayZPlayerConstants.MOVEMENTIDX_IDLE;
                break;
            default:
                movementSpeed = DayZPlayerConstants.MOVEMENTIDX_WALK;
                break;
            }
            break;
        default:
            movementSpeed = pState.m_iMovement;
        }
        //Print("MovementState: " + movementSpeed);
        return movementSpeed;
    }
References HumanMovementState::m_iMovement, and HumanMovementState::m_iStanceIdx.
Referenced by GetMaxVisionRangeModifier(), GetMovementSpeedVisualCoef(), and NoiseAIEvaluate::GetNoiseMultiplierByPlayerSpeed().
Member Data Documentation
m_iChestBoneIndex
private int AITargetCallbacksPlayer::m_iChestBoneIndex private
Definition at line 133 of file aitargetcallbacksplayer.c.
Referenced by AITargetCallbacksPlayer(), and GetVisionPointPositionWS().
m_iHeadBoneIndex
private int AITargetCallbacksPlayer::m_iHeadBoneIndex private
Definition at line 132 of file aitargetcallbacksplayer.c.
Referenced by AITargetCallbacksPlayer(), and GetHeadPositionWS().
m_Player
private PlayerBase AITargetCallbacksPlayer::m_Player private
Definition at line 131 of file aitargetcallbacksplayer.c.
Referenced by AITargetCallbacksPlayer(), GetHeadPositionWS(), GetMaxVisionRangeModifier(), and GetVisionPointPositionWS().