DayzKode: PluginDayzPlayerDebug_OtherCmds Class Reference
PluginDayzPlayerDebug_OtherCmds Class Reference
Private Member Functions
void CommandHandler ()
void CreateModuleWidgets ()
void Death_Start ()
void DestroyModuleWidgets ()
void Hit_Start ()
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
void PluginDayzPlayerDebug_OtherCmds (Widget pMainWnd)
void Uncon_End ()
void Uncon_Start ()
void ~PluginDayzPlayerDebug_OtherCmds ()
Private Attributes
bool m_CH_DeathStart = false
bool m_CH_HitStart = false
bool m_CH_UnconEnd = false
bool m_CH_UnconStart = false
EditBoxWidget m_DeathDirectionEdit
ButtonWidget m_DeathStartButton
XComboBoxWidget m_DeathTypeCB
ButtonWidget m_HitStartButton
XComboBoxWidget m_HitTypeCB
Widget m_MainWnd
ButtonWidget m_UnconEndButton
ButtonWidget m_UnconStartButton
XComboBoxWidget m_UnconTypeCB
Detailed Description
Definition at line 5 of file plugindayzplayerdebug_othercmds.c.
Constructor & Destructor Documentation
PluginDayzPlayerDebug_OtherCmds()
void PluginDayzPlayerDebug_OtherCmds::PluginDayzPlayerDebug_OtherCmds (Widget pMainWnd) inline private
Definition at line 31 of file plugindayzplayerdebug_othercmds.c.
    {
        m_MainWnd = pMainWnd;
        CreateModuleWidgets();
    }
References CreateModuleWidgets(), and m_MainWnd.
~PluginDayzPlayerDebug_OtherCmds()
void PluginDayzPlayerDebug_OtherCmds::~PluginDayzPlayerDebug_OtherCmds () inline private
Definition at line 38 of file plugindayzplayerdebug_othercmds.c.
    {
        DestroyModuleWidgets();
    }
References DestroyModuleWidgets().
Member Function Documentation
CommandHandler()
void PluginDayzPlayerDebug_OtherCmds::CommandHandler () inline private
Definition at line 100 of file plugindayzplayerdebug_othercmds.c.
    {
        if( m_CH_DeathStart )
        {
            Death_Start();
            m_CH_DeathStart = false;
        }
        if( m_CH_HitStart )
        {
            Hit_Start();
            m_CH_HitStart = false;
        }
        if( m_CH_UnconStart )
        {
            Uncon_Start();
            m_CH_UnconStart = false;
        }
        if( m_CH_UnconEnd )
        {
            Uncon_End();
            m_CH_UnconEnd = false;
        }
    }
References Death_Start(), Hit_Start(), m_CH_DeathStart, m_CH_HitStart, m_CH_UnconEnd, m_CH_UnconStart, Uncon_End(), and Uncon_Start().
Referenced by CommandHandler().
CreateModuleWidgets()
void PluginDayzPlayerDebug_OtherCmds::CreateModuleWidgets () inline private
Definition at line 44 of file plugindayzplayerdebug_othercmds.c.
    {
        m_DeathTypeCB           = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("DeathTypeCB") );
        m_DeathDirectionEdit    = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("DeathDirectionEdit") );
        m_DeathStartButton      = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("DeathStartButton") );
        m_HitTypeCB             = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("HitTypeCB") );
        m_HitStartButton        = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("HitStartButton") );
        m_UnconTypeCB           = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("UnconTypeCB") );
        m_UnconStartButton      = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("UnconStartButton") );
        m_UnconEndButton        = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("UnconEndButton") );
    }
References m_DeathDirectionEdit, m_DeathStartButton, m_DeathTypeCB, m_HitStartButton, m_HitTypeCB, m_MainWnd, m_UnconEndButton, m_UnconStartButton, and m_UnconTypeCB.
Referenced by PluginDayzPlayerDebug_OtherCmds().
Death_Start()
void PluginDayzPlayerDebug_OtherCmds::Death_Start () inline private
Definition at line 127 of file plugindayzplayerdebug_othercmds.c.
    {
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if( !player )
            return;
        int deathType = m_DeathTypeCB.GetCurrentItem();
        if( deathType > 0 )
            deathType += 9;
        float deathDirection = m_DeathDirectionEdit.GetText().ToInt();
        player.StartCommand_Death(deathType, deathDirection, HumanCommandDeathCallback);
    }
References GetGame(), GetPlayer(), m_DeathDirectionEdit, and m_DeathTypeCB.
Referenced by CommandHandler().
DestroyModuleWidgets()
void PluginDayzPlayerDebug_OtherCmds::DestroyModuleWidgets () inline private
Definition at line 58 of file plugindayzplayerdebug_othercmds.c.
    {
    }
Referenced by ~PluginDayzPlayerDebug_OtherCmds().
Hit_Start()
void PluginDayzPlayerDebug_OtherCmds::Hit_Start () inline private
Definition at line 143 of file plugindayzplayerdebug_othercmds.c.
    {
        DayZPlayer player = DayZPlayer.Cast( GetGame().GetPlayer() );
        if( !player )
            return;
        float hitDirection = m_DeathDirectionEdit.GetText().ToInt();
        int hitType = m_HitTypeCB.GetCurrentItem();
        if( hitType == 0 )
        {
            player.AddCommandModifier_Damage(0, hitDirection);
        }
        else
        {
            player.StartCommand_Damage(0, hitDirection);
        }
    }
References GetGame(), GetPlayer(), m_DeathDirectionEdit, and m_HitTypeCB.
Referenced by CommandHandler().
OnClick()
bool PluginDayzPlayerDebug_OtherCmds::OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 66 of file plugindayzplayerdebug_othercmds.c.
    {
        if( w == m_DeathStartButton )
        {
            Print("PluginPlayerDebug: Death Start");
            m_CH_DeathStart = true;
            return true;
        }
        else if( w == m_HitStartButton )
        {
            Print("PluginPlayerDebug: Uncon Start");
            m_CH_HitStart = true;
            return true;
        }
        else if( w == m_UnconStartButton )
        {
            Print("PluginPlayerDebug: Uncon Start");
            m_CH_UnconStart = true;
            return true;
        }
        else if( w == m_UnconEndButton )
        {
            Print("PluginPlayerDebug: Uncon End");
            m_CH_UnconEnd = true;
            return true;
        }
        return false;
    }
References m_CH_DeathStart, m_CH_HitStart, m_CH_UnconEnd, m_CH_UnconStart, m_DeathStartButton, m_HitStartButton, m_UnconEndButton, m_UnconStartButton, and Print().
Uncon_End()
void PluginDayzPlayerDebug_OtherCmds::Uncon_End () inline private
Definition at line 173 of file plugindayzplayerdebug_othercmds.c.
    {
        DayZPlayerImplement player = DayZPlayerImplement.Cast( GetGame().GetPlayer() );
        if( !player )
            return;
        player.m_UnconsciousDebug = false;
        HumanCommandUnconscious hcu = player.GetCommand_Unconscious();
        if( hcu )
            hcu.WakeUp();
    }
References GetGame(), GetPlayer(), and HumanCommandUnconscious::WakeUp().
Referenced by CommandHandler().
Uncon_Start()
void PluginDayzPlayerDebug_OtherCmds::Uncon_Start () inline private
Definition at line 161 of file plugindayzplayerdebug_othercmds.c.
    {
        DayZPlayerImplement player = DayZPlayerImplement.Cast( GetGame().GetPlayer() );
        if( !player )
            return;
        int type = m_UnconTypeCB.GetCurrentItem();
        player.m_UnconsciousDebug = true;
        player.StartCommand_Unconscious(type);
    }
References GetGame(), GetPlayer(), and m_UnconTypeCB.
Referenced by CommandHandler().
Member Data Documentation
m_CH_DeathStart
bool PluginDayzPlayerDebug_OtherCmds::m_CH_DeathStart = false private
Definition at line 22 of file plugindayzplayerdebug_othercmds.c.
Referenced by CommandHandler(), and OnClick().
m_CH_HitStart
bool PluginDayzPlayerDebug_OtherCmds::m_CH_HitStart = false private
Definition at line 23 of file plugindayzplayerdebug_othercmds.c.
Referenced by CommandHandler(), and OnClick().
m_CH_UnconEnd
bool PluginDayzPlayerDebug_OtherCmds::m_CH_UnconEnd = false private
Definition at line 25 of file plugindayzplayerdebug_othercmds.c.
Referenced by CommandHandler(), and OnClick().
m_CH_UnconStart
bool PluginDayzPlayerDebug_OtherCmds::m_CH_UnconStart = false private
Definition at line 24 of file plugindayzplayerdebug_othercmds.c.
Referenced by CommandHandler(), and OnClick().
m_DeathDirectionEdit
EditBoxWidget PluginDayzPlayerDebug_OtherCmds::m_DeathDirectionEdit private
Definition at line 11 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), Death_Start(), and Hit_Start().
m_DeathStartButton
ButtonWidget PluginDayzPlayerDebug_OtherCmds::m_DeathStartButton private
Definition at line 12 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_DeathTypeCB
XComboBoxWidget PluginDayzPlayerDebug_OtherCmds::m_DeathTypeCB private
Definition at line 10 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and Death_Start().
m_HitStartButton
ButtonWidget PluginDayzPlayerDebug_OtherCmds::m_HitStartButton private
Definition at line 15 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_HitTypeCB
XComboBoxWidget PluginDayzPlayerDebug_OtherCmds::m_HitTypeCB private
Definition at line 14 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and Hit_Start().
m_MainWnd
Widget PluginDayzPlayerDebug_OtherCmds::m_MainWnd private
Definition at line 8 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and PluginDayzPlayerDebug_OtherCmds().
m_UnconEndButton
ButtonWidget PluginDayzPlayerDebug_OtherCmds::m_UnconEndButton private
Definition at line 19 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_UnconStartButton
ButtonWidget PluginDayzPlayerDebug_OtherCmds::m_UnconStartButton private
Definition at line 18 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and OnClick().
m_UnconTypeCB
XComboBoxWidget PluginDayzPlayerDebug_OtherCmds::m_UnconTypeCB private
Definition at line 17 of file plugindayzplayerdebug_othercmds.c.
Referenced by CreateModuleWidgets(), and Uncon_Start().