DayzKode: ActionAttachWithSwitch Class Reference
ActionAttachWithSwitch Class Reference
Private Member Functions
void ActionAttachWithSwitch ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBePerformedFromInventory ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override GetInputType ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Detailed Description
Definition at line 1 of file actionattachwithswich.c.
Constructor & Destructor Documentation
ActionAttachWithSwitch()
void ActionAttachWithSwitch::ActionAttachWithSwitch () inline private
Definition at line 3 of file actionattachwithswich.c.
    {
    }
Member Function Documentation
ActionCondition()
override bool ActionAttachWithSwitch::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 64 of file actionattachwithswich.c.
    {
        EntityAI target_entity = EntityAI.Cast( target.GetObject() );
        if( !item.CanSwitchDuringAttach(target_entity) )
            return false;
        if ( target_entity && item )
        {
            if ( target_entity.GetInventory() && target_entity.GetInventory().CanAddAttachment( item ) )
            {
                return true;
            }
        }
        return false;
    }
CanBePerformedFromInventory()
override bool ActionAttachWithSwitch::CanBePerformedFromInventory () inline private
Definition at line 20 of file actionattachwithswich.c.
    {
        return true;
    }
CreateActionData()
override ActionData ActionAttachWithSwitch::CreateActionData () inline private
Definition at line 25 of file actionattachwithswich.c.
    {
        AttachActionData action_data = new AttachActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionAttachWithSwitch::CreateConditionComponents () inline private
Definition at line 7 of file actionattachwithswich.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNonRuined( UAMaxDistances.DEFAULT );
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_ATTACHITEM;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, m_ConditionTarget, and m_StanceMask.
GetInputType()
override ActionAttachWithSwitch::GetInputType () inline private
Definition at line 15 of file actionattachwithswich.c.
    {
        return InventoryOnlyActionInput;
    }
OnExecuteClient()
override void ActionAttachWithSwitch::OnExecuteClient (ActionData action_data) inline private
Definition at line 106 of file actionattachwithswich.c.
    {
        ClearInventoryReservationEx(action_data);
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        EntityAI target_EAI;
        if ( action_data.m_Target.IsProxy() )
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetParent() ); // cast to ItemBase
        }
        else
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetObject() ); // cast to ItemBase
        }
        if (target_EAI && action_data_a.m_MainItem)
        {
            ref InventoryLocation il = new InventoryLocation;
            il.SetAttachment( target_EAI, action_data.m_MainItem, action_data_a.m_AttSlot );
            action_data.m_Player.PredictiveForceSwapEntities( target_EAI, action_data.m_MainItem, il );
        }
    }
References ClearInventoryReservationEx(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and InventoryLocation::SetAttachment().
OnExecuteServer()
override void ActionAttachWithSwitch::OnExecuteServer (ActionData action_data) inline private
Definition at line 80 of file actionattachwithswich.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        ClearInventoryReservationEx(action_data);
        AttachActionData action_data_a = AttachActionData.Cast(action_data);
        EntityAI target_EAI;
        if ( action_data.m_Target.IsProxy() )
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetParent() ); // cast to ItemBase
        }
        else
        {
            target_EAI = EntityAI.Cast( action_data_a.m_Target.GetObject() ); // cast to ItemBase
        }
        if (target_EAI && action_data_a.m_MainItem)
        {
            ref InventoryLocation il = new InventoryLocation;
            il.SetAttachment( target_EAI, action_data.m_MainItem, action_data_a.m_AttSlot );
            action_data.m_Player.PredictiveForceSwapEntities( target_EAI, action_data.m_MainItem, il );
        }
    }
References ClearInventoryReservationEx(), GetGame(), AttachActionData::m_AttSlot, ActionData::m_MainItem, ActionData::m_Player, ActionData::m_Target, and InventoryLocation::SetAttachment().
SetupAction()
override bool ActionAttachWithSwitch::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 31 of file actionattachwithswich.c.
    {
        ref InventoryLocation il = new InventoryLocation;
        if (!GetGame().IsDedicatedServer())
        {
            EntityAI target_entity;
            if ( target.IsProxy() )
            {
                target_entity = EntityAI.Cast( target.GetParent() );
            }
            else
            {
                target_entity = EntityAI.Cast( target.GetObject() );
            }
            if (!target_entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ATTACHMENT, il ))
                return false;
        }
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            if (!GetGame().IsDedicatedServer())
            {
                AttachActionData action_data_a = AttachActionData.Cast(action_data);
                action_data_a.m_AttSlot = il.GetSlot();
            }
            return true;
        }
        return false;
    }
References GetGame(), and AttachActionData::m_AttSlot.