DayzKode: OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
Private Member Functions
void AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t)
adds transition into transition table
array< ref FSMStateBase > GetCurrentState ()
bool IsRunning ()
returns true if machine is in running state
void OFSMBase ()
fsm transition table
ProcessEventResult ProcessEvent (FSMEventBase e)
instructs the state machine to process the event e
protected ProcessEventResult ProcessLocalTransition (int s, FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
instructs the state machine to process the event locally - no hierarchy is crossed
void SetInitialStates (array< ref FSMStateBase > initial_states)
void Start (array< ref FSMEventBase > initial_events=null)
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
void Terminate (array< ref FSMEventBase > terminal_events=null)
terminates the state machine
void Update (float dt)
if machine running, call OnUpdate() on current state
Private Attributes
protected ref array< ref FSMStateBase > m_InitialStates
current fsm state
protected ref array< ref FSMStateBase > m_States
protected ref array< ref FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > > m_Transitions
configurable initial state of the machine
Detailed Description
Definition at line 7 of file ofsmbase.c.
Constructor & Destructor Documentation
OFSMBase()
void OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::OFSMBase () inline private
fsm transition table
Definition at line 13 of file ofsmbase.c.
    {
        m_States = new array<ref FSMStateBase>;
        m_InitialStates = new array<ref FSMStateBase>;
        m_Transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>>;
    }
Member Function Documentation
AddTransition()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t) inline private
adds transition into transition table
Definition at line 110 of file ofsmbase.c.
    {
        m_Transitions.Insert(t);
    }
GetCurrentState()
array< ref FSMStateBase > OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetCurrentState () inline private
Definition at line 24 of file ofsmbase.c.
    {
        return m_States;
    }
IsRunning()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::IsRunning () inline private
returns true if machine is in running state
Definition at line 62 of file ofsmbase.c.
    {
        int sc = m_States.Count();
        if (sc)
        {
            for (int s = 0; s < sc; ++s)
                if (m_States[s] != null)
                    return true;
        }
        return false;
    }
ProcessEvent()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent (FSMEventBase e) inline private
instructs the state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
Definition at line 120 of file ofsmbase.c.
    {
        int count = m_Transitions.Count();
        for (int i = 0; i < count; ++i)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> row = m_Transitions.Get(i);
            if (row.m_event.Type() == e.Type())
            {
                for (int s = 0; s < m_States.Count(); ++s)
                {
                    if (row.m_srcState.Type() == m_States[s].Type() && row.m_event.Type() == e.Type())
                    {
                        FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_Transitions.Get(i);
                        bool hasGuard = t.m_guard != NULL;
                        if (!hasGuard || (hasGuard && t.m_guard.GuardCondition(e)))     // 1) exec guard (if any)
{
                            ProcessLocalTransition(s, t, e); // 2) process transition allowed by guard
                        }
                    }
                }
            }
        }
        return ProcessEventResult.FSM_NO_TRANSITION;
    }
ProcessLocalTransition()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition (int s, FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
instructs the state machine to process the event locally - no hierarchy is crossed
Parameters
[in] t the transition in m_transitions
[in] e event that will be used to process transition from current state
Returns
FSM_OK or FSM_TERMINATED
Definition at line 151 of file ofsmbase.c.
    {
        fsmbDebugPrint("[ofsm] (local) state=" + t.m_srcState.ToString() + "-------- event=" + e.ToString() + "[G=" + t.m_guard.ToString() +"]/A=" + t.m_action.ToString() + " --------|> dst=" + t.m_dstState.ToString());
        m_States[s].OnExit(e);          // 1) call onExit on old state
        if (t.m_action)
            t.m_action.Action(e);   // 2) execute transition action (if any)
        m_States[s] = t.m_dstState;     // 3) change state to new
        if (t.m_dstState != NULL)
        {
            m_States[s].OnEntry(e);     // 4a) call onEntry on new state
            return ProcessEventResult.FSM_OK;
        }
        else
        {
            fsmbDebugPrint("[ofsm] terminating fsm: state=" + t.m_srcState.ToString() + " event=" + e.ToString());
            return ProcessEventResult.FSM_TERMINATED; // 4b) or terminate
        }
    }
References fsmbDebugPrint().
SetInitialStates()
void OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::SetInitialStates (array< ref FSMStateBase > initial_states) inline private
Definition at line 32 of file ofsmbase.c.
    {
        m_InitialStates = initial_states;
        for (int s = 0; s < initial_states.Count(); ++s)
            m_States.Insert(initial_states[s]);
    }
Start()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start (array< ref FSMEventBase > initial_events = null) inline private
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
Parameters
[in] e optional event for starting the machind
Definition at line 44 of file ofsmbase.c.
    {
        fsmbDebugPrint("[ofsm] " + this.ToString() + "::Start(" + initial_events.ToString() + "), init_state=" + m_InitialStates.ToString());
        for (int s = 0; s < m_States.Count(); ++s)
        {
            m_States[s] = m_InitialStates[s];
            if (initial_events)
                m_States[s].OnEntry(initial_events[s]);
            else
                m_States[s].OnEntry(null);
        }
    }
References fsmbDebugPrint(), ToString(), and string::ToString().
Terminate()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate (array< ref FSMEventBase > terminal_events = null) inline private
terminates the state machine
Definition at line 77 of file ofsmbase.c.
    {
        if (IsRunning())
        {
            for (int s = 0; s < m_States.Count(); ++s)
            {
                if (terminal_events)
                    m_States[s].OnExit(terminal_events[s]);
                else
                    m_States[s].OnExit(null);
                m_States[s] = null;
            }
        }
    }
References IsRunning().
Update()
OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Update (float dt) inline private
if machine running, call OnUpdate() on current state
Definition at line 96 of file ofsmbase.c.
    {
        if (IsRunning())
        {
            for (int s = 0; s < m_States.Count(); ++s)
            {
                m_States[s].OnUpdate(dt);
            }
        }
    }
References IsRunning().
Member Data Documentation
m_InitialStates
protected ref array<ref FSMStateBase> OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_InitialStates private
current fsm state
Definition at line 10 of file ofsmbase.c.
m_States
protected ref array<ref FSMStateBase> OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_States private
Definition at line 9 of file ofsmbase.c.
m_Transitions
protected ref array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> > OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_Transitions private
configurable initial state of the machine
Definition at line 11 of file ofsmbase.c.