DayzKode: ModLoader Class Reference
ModLoader Class Reference
Static Private Member Functions
static array< ref ModStructure > GetMods ()
static void LoadMods ()
Static Private Attributes
static protected bool m_Loaded
static protected ref array< ref ModStructure > m_Mods
Detailed Description
Definition at line 1 of file modloader.c.
Member Function Documentation
GetMods()
static array< ref ModStructure > ModLoader::GetMods () inline static private
Definition at line 6 of file modloader.c.
    {
        //if( !m_Loaded )
            LoadMods();
        return m_Mods;
    }
References LoadMods(), and m_Mods.
LoadMods()
static void ModLoader::LoadMods () inline static private
Definition at line 13 of file modloader.c.
    {
        m_Mods = new array<ref ModStructure>;
        int mod_count = GetGame().ConfigGetChildrenCount( "CfgMods" );
        for( int i = 2; i < mod_count; i++ )
        {
            string mod_name;
            GetGame().ConfigGetChildName( "CfgMods", i, mod_name );
            m_Mods.Insert( new ModStructure( i, "CfgMods " + mod_name ) );
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and m_Mods.
Referenced by GetMods().
Member Data Documentation
m_Loaded
protected bool ModLoader::m_Loaded static private
Definition at line 3 of file modloader.c.
m_Mods
protected ref array<ref ModStructure> ModLoader::m_Mods static private
Definition at line 4 of file modloader.c.
Referenced by GetMods(), and LoadMods().