DayzKode: HandsPreview Class Reference
HandsPreview Class Reference
Private Member Functions
void CreateNewIcon (ItemBase item)
void DeleteIcon ()
override EntityAI GetFocusedItem ()
Icon GetIcon ()
float GetIconSize ()
protected ItemBase m_Item void HandsPreview (LayoutHolder parent)
void RefreshQuantity (EntityAI m_Item_to_refresh)
void RemoveItem ()
override bool Select ()
override bool SelectItem ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
override void SetLastFocus ()
override void SetLayoutName ()
override void Unfocus ()
override void UpdateInterval ()
void ~HandsPreview ()
Private Attributes
protected EntityAI m_AttachmentsInitialized
protected ref Icon m_Icon
protected float m_IconSize
Detailed Description
Definition at line 1 of file handspreview.c.
Constructor & Destructor Documentation
HandsPreview()
protected ItemBase m_Item void HandsPreview::HandsPreview (LayoutHolder parent) inline private
Definition at line 10 of file handspreview.c.
    {
        GetGame().GetPlayer().GetOnItemAddedToHands().Insert( CreateNewIcon );
        GetGame().GetPlayer().GetOnItemRemovedFromHands().Insert( DeleteIcon );
    }
References CreateNewIcon(), DeleteIcon(), GetGame(), and CGame::GetPlayer().
~HandsPreview()
void HandsPreview::~HandsPreview () inline private
Definition at line 16 of file handspreview.c.
    {
        GetGame().GetPlayer().GetOnItemAddedToHands().Remove( CreateNewIcon );
        GetGame().GetPlayer().GetOnItemRemovedFromHands().Remove( DeleteIcon );
    }
References CreateNewIcon(), DeleteIcon(), GetGame(), and CGame::GetPlayer().
Member Function Documentation
CreateNewIcon()
void HandsPreview::CreateNewIcon (ItemBase item) inline private
Definition at line 97 of file handspreview.c.
    {
        float y;
        GetRootWidget().GetParent().GetParent().GetParent().GetParent().GetScreenSize( m_IconSize, y );
        m_IconSize = m_IconSize / 10;
        m_Icon = new Icon( this, true );
        m_Icon.Refresh();
        if ( m_Icon )
        {
            m_Item = item;
            m_Icon.Init( m_Item );
            m_Icon.FullScreen();
            ( HandsContainer.Cast( m_Parent ) ).ShowAtt( m_Item );
            m_Icon.Refresh();
        }
        m_RootWidget.SetColor( ARGB( 180, 0, 0, 0 ) );
        m_Parent.GetParent().Refresh();
        Inventory.GetInstance().UpdateConsoleToolbar();
        HandsContainer parent = HandsContainer.Cast( m_Parent );
        HandsHeader header = HandsHeader.Cast( parent.GetHeader() );
        if( m_Item && !m_Item.GetInventory().GetCargo() )
        {
            string display_name = m_Item.GetDisplayName();
            display_name.ToUpper();
            header.SetName( display_name );
        }
    }
References ARGB(), Icon::FullScreen(), HandsContainer::GetHeader(), Icon::Init(), Inventory(), m_Icon, m_IconSize, m_Item, m_Parent, m_RootWidget, Icon::Refresh(), Header::SetName(), string::ToUpper(), and y.
Referenced by HandsContainer::HandsContainer(), HandsPreview(), and ~HandsPreview().
DeleteIcon()
void HandsPreview::DeleteIcon () inline private
Definition at line 129 of file handspreview.c.
    {
        RemoveItem();
        ( HandsContainer.Cast( m_Parent ) ).DestroyAtt();
        ( HandsContainer.Cast( m_Parent ) ).DestroyCargo();
        ( HandsContainer.Cast( m_Parent ) ).RemoveItem();
        m_AttachmentsInitialized = null;
        m_RootWidget.SetColor( ARGB( 166, 80, 80, 80 ) );
        m_Parent.GetParent().Refresh();
        Inventory.GetInstance().UpdateConsoleToolbar();
    }
References ARGB(), Inventory(), m_AttachmentsInitialized, m_Parent, m_RootWidget, and RemoveItem().
Referenced by HandsPreview(), and ~HandsPreview().
GetFocusedItem()
override EntityAI HandsPreview::GetFocusedItem () inline private
Definition at line 30 of file handspreview.c.
    {
        return m_Item;
    }
References m_Item.
GetIcon()
Icon HandsPreview::GetIcon () inline private
Definition at line 35 of file handspreview.c.
    {
        return m_Icon;
    }
References m_Icon.
Referenced by Attachments::Combine(), PlayerContainer::Combine(), and VicinitySlotsContainer::Combine().
GetIconSize()
float HandsPreview::GetIconSize () inline private
Definition at line 61 of file handspreview.c.
    {
        return m_IconSize;
    }
References m_IconSize.
Referenced by Icon::SetPosEx(), and Icon::SetSize().
RefreshQuantity()
void HandsPreview::RefreshQuantity (EntityAI m_Item_to_refresh) inline private
Definition at line 22 of file handspreview.c.
    {
        if ( m_Icon )
        {
            m_Icon.SetQuantity();
        }
    }
References m_Icon, and Icon::SetQuantity().
RemoveItem()
void HandsPreview::RemoveItem () inline private
Definition at line 71 of file handspreview.c.
    {
        delete m_Icon;
        m_Item = null;
    }
References m_Icon, and m_Item.
Referenced by DeleteIcon().
Select()
override bool HandsPreview::Select () inline private
Definition at line 151 of file handspreview.c.
    {
        Man player = GetGame().GetPlayer();
        EntityAI item_in_hands = m_Item;
        if( ItemManager.GetInstance().IsMicromanagmentMode() )
        {
            EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
            if( selected_item && selected_item.GetInventory().CanRemoveEntity() )
            {
                if(item_in_hands && item_in_hands.GetInventory().CanRemoveEntity())
                {
                    if( GameInventory.CanSwapEntitiesEx( item_in_hands, selected_item ) )
                    {
                        player.PredictiveSwapEntities( item_in_hands, selected_item );
                        return true;
                    }
                }
                else
                {
                    if ( player.GetHumanInventory().CanAddEntityInHands( selected_item ) && selected_item.GetInventory().CanRemoveEntity())
                    {
                        ItemBase item_base = ItemBase.Cast( selected_item );
                        float stackable = item_base.GetTargetQuantityMax();
                        if (stackable == 0 || item_base.GetQuantity() <= stackable)
{
                            GetGame().GetPlayer().PredictiveTakeEntityToHands( item_base );
                            return true;
                        }
                        else if( stackable != 0 && stackable <= item_base.GetQuantity() )
{
                            item_base.SplitIntoStackMaxHandsClient(PlayerBase.Cast( GetGame().GetPlayer() ));
                            return true;
                        }
                    }
                }
            }
        }
        return false;
    }
References GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), ItemManager::GetSelectedItem(), ItemManager::IsMicromanagmentMode(), m_Item, and EntityAI::PredictiveSwapEntities().
SelectItem()
override bool HandsPreview::SelectItem () inline private
Definition at line 141 of file handspreview.c.
    {
        if( m_Item )
        {
            ItemManager.GetInstance().SetSelectedItem( m_Item, null, null, null );
            return true;
        }
        return false;
    }
References ItemManager::GetInstance(), m_Item, and ItemManager::SetSelectedItem().
SetDefaultFocus()
override void HandsPreview::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 40 of file handspreview.c.
    {
        super.SetDefaultFocus(while_micromanagment_mode);
        if ( m_Icon )
            m_Icon.SetActive(true);
    }
References m_Icon, and Icon::SetActive().
SetLastFocus()
override void HandsPreview::SetLastFocus () inline private
Definition at line 47 of file handspreview.c.
    {
        super.SetLastFocus();
        if ( m_Icon )
            m_Icon.SetActive(true);
    }
References m_Icon, and Icon::SetActive().
SetLayoutName()
override void HandsPreview::SetLayoutName () inline private
Definition at line 66 of file handspreview.c.
    {
        m_LayoutName = WidgetLayoutName.HandsPreview;
    }
References WidgetLayoutName::HandsPreview.
Unfocus()
override void HandsPreview::Unfocus () inline private
Definition at line 54 of file handspreview.c.
    {
        super.Unfocus();
        if ( m_Icon )
            m_Icon.SetActive(false);
    }
References m_Icon, and Icon::SetActive().
UpdateInterval()
override void HandsPreview::UpdateInterval () inline private
Definition at line 77 of file handspreview.c.
    {
        bool show_combine_swap = ItemManager.GetInstance().IsDragging();
        #ifdef PLATFORM_CONSOLE
        if ( m_Icon && !m_Icon.IsDragged() && GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer() )
        #else
        if ( m_Icon && !m_Icon.IsDragged() )
        #endif
        {
            m_Icon.GetMainWidget().FindAnyWidget( "Combine" ).Show(  show_combine_swap );
            m_Icon.GetMainWidget().FindAnyWidget( "Swap" ).Show( show_combine_swap );
        }
        if ( m_Icon )
        {
            m_Icon.UpdateInterval();
        }
    }
References GetGame(), GetInput(), ItemManager::GetInstance(), Icon::IsDragged(), ItemManager::IsDragging(), m_Icon, and Icon::UpdateInterval().
Member Data Documentation
m_AttachmentsInitialized
protected EntityAI HandsPreview::m_AttachmentsInitialized private
Definition at line 4 of file handspreview.c.
Referenced by DeleteIcon().
m_Icon
protected ref Icon HandsPreview::m_Icon private
Definition at line 3 of file handspreview.c.
Referenced by CreateNewIcon(), GetIcon(), RefreshQuantity(), RemoveItem(), SetDefaultFocus(), SetLastFocus(), Unfocus(), and UpdateInterval().
m_IconSize
protected float HandsPreview::m_IconSize private
Definition at line 6 of file handspreview.c.
Referenced by CreateNewIcon(), and GetIconSize().