DayzKode: Chemlight_ColorBase Class Reference
Chemlight_ColorBase Class Reference
Private Member Functions
void Chemlight_ColorBase ()
void CreateLight ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
float GetEfficiency0To1 ()
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
float GetEfficiencyDecayStart ()
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
string GetMaterialForDamageState (bool glowing, int healthLevel=-1)
override void OnEnergyConsumed ()
override void OnInventoryExit (Man player)
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
void StandUp ()
Private Attributes
string m_DefaultMaterial
private int m_Efficiency0To10
string m_GlowMaterial
ChemlightLight m_Light
Static Private Attributes
static private float m_EfficiencyDecayStart = 0.05
Detailed Description
Definition at line 1 of file chemlight.c.
Constructor & Destructor Documentation
Chemlight_ColorBase()
void Chemlight_ColorBase::Chemlight_ColorBase () inline private
Definition at line 46 of file chemlight.c.
    {
        //materials
        array<string> config_materials  = GetHiddenSelectionsMaterials();
        if (config_materials.Count() == 2)
        {
            m_DefaultMaterial = config_materials[0];
            m_GlowMaterial = config_materials[1];
        }
        else
        {
            string error = "Error! Item " + GetType() + " must have 2 entries in config array hiddenSelectionsMaterials[]. One for the default state, the other one for the glowing state. Currently it has " + config_materials.Count() + ".";
            Error(error);
        }
        m_Efficiency0To10 = 10;
        RegisterNetSyncVariableInt("m_Efficiency0To10");
    }
References Error(), GetHiddenSelectionsMaterials(), GetType(), m_DefaultMaterial, m_Efficiency0To10, and m_GlowMaterial.
Member Function Documentation
CreateLight()
void Chemlight_ColorBase::CreateLight () inline private
Definition at line 66 of file chemlight.c.
    {
        SetObjectMaterial( 0, GetMaterialForDamageState(true) ); // must be server side!
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() ) // client side
        {
            m_Light = ChemlightLight.Cast( ScriptedLightBase.CreateLight( ChemlightLight, "0 0 0") );
            m_Light.AttachOnMemoryPoint(this, "light");
            string type = GetType();
            switch( type )
            {
                case "Chemlight_White":
                    m_Light.SetColorToWhite();
                    break;
                case "Chemlight_Red":
                    m_Light.SetColorToRed();
                    break;
                case "Chemlight_Green":
                    m_Light.SetColorToGreen();
                    break;
                case "Chemlight_Blue":
                    m_Light.SetColorToBlue();
                    break;
                case "Chemlight_Yellow":
                    m_Light.SetColorToYellow();
                    break;
                default: { m_Light.SetColorToWhite(); };
            }
        }
    }
References GetGame(), GetMaterialForDamageState(), GetType(), and m_Light.
Referenced by OnWork().
EEHealthLevelChanged()
override void Chemlight_ColorBase::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 39 of file chemlight.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        SetObjectMaterial( 0, GetMaterialForDamageState(GetCompEM().IsWorking(),newLevel) );
    }
References GetMaterialForDamageState().
GetEfficiency0To1()
float Chemlight_ColorBase::GetEfficiency0To1 () inline private
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 12 of file chemlight.c.
    {
        return m_Efficiency0To10 / 10;
    }
References m_Efficiency0To10.
Referenced by OnWork().
GetEfficiencyDecayStart()
float Chemlight_ColorBase::GetEfficiencyDecayStart () inline private
Returns efficiency. The value is synchronized from server to all clients and is accurate down to 0.1 units.
Definition at line 18 of file chemlight.c.
    {
        return m_EfficiencyDecayStart;
    }
References m_EfficiencyDecayStart.
GetMaterialForDamageState()
string Chemlight_ColorBase::GetMaterialForDamageState (bool glowing, int healthLevel = -1) inline private
Definition at line 165 of file chemlight.c.
    {
        int currentHealthLevel;
        int suffixIndex;
        string base;
        if (healthLevel == -1)
            currentHealthLevel = GetHealthLevel();
        else
            currentHealthLevel = healthLevel;
        if (glowing)
            base = m_GlowMaterial;
        else
            base = m_DefaultMaterial;
        suffixIndex = base.IndexOf(".rvmat");
        if (suffixIndex == -1)
        {
            Error("Error - no valid rvmat found for chemlight");
            return "";
        }
        base = base.Substring(0,suffixIndex);
        if (currentHealthLevel == GameConstants.STATE_BADLY_DAMAGED || currentHealthLevel == GameConstants.STATE_DAMAGED)
        {
            base = base + "_damage";
        }
        else if (currentHealthLevel == GameConstants.STATE_RUINED)
        {
            base = base + "_destruct";
        }
        return base + ".rvmat";
    }
References Error(), GetHealthLevel(), string::IndexOf(), m_DefaultMaterial, m_GlowMaterial, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and string::Substring().
Referenced by CreateLight(), EEHealthLevelChanged(), and OnWorkStop().
OnEnergyConsumed()
override void Chemlight_ColorBase::OnEnergyConsumed () inline private
Definition at line 23 of file chemlight.c.
    {
        super.OnEnergyConsumed();
        if ( GetGame().IsServer() )
        {
            float energy_coef = GetCompEM().GetEnergy0To1();
            if ( energy_coef < m_EfficiencyDecayStart  &&  m_EfficiencyDecayStart > 0 )
            {
                m_Efficiency0To10 = Math.Round(  (energy_coef / m_EfficiencyDecayStart) * 10  );
                SetSynchDirty();
            }
        }
    }
References GetGame(), m_Efficiency0To10, m_EfficiencyDecayStart, and Math::Round().
OnInventoryExit()
override void Chemlight_ColorBase::OnInventoryExit (Man player) inline private
Definition at line 106 of file chemlight.c.
    {
        super.OnInventoryExit(player);
        StandUp();
    }
References StandUp().
OnWork()
override void Chemlight_ColorBase::OnWork (float consumed_energy) inline private
Definition at line 141 of file chemlight.c.
    {
        if (!m_Light)
            CreateLight();
        // Handle fade out of chemlight
        if (m_Light)
        {
            float efficiency = GetEfficiency0To1();
            if ( efficiency < 1 )
            {
                m_Light.SetIntensity( efficiency, GetCompEM().GetUpdateInterval() );
            }
        }
    }
References CreateLight(), GetEfficiency0To1(), and m_Light.
OnWorkStart()
override void Chemlight_ColorBase::OnWorkStart () inline private
Definition at line 100 of file chemlight.c.
    {
    }
OnWorkStop()
override void Chemlight_ColorBase::OnWorkStop () inline private
Definition at line 122 of file chemlight.c.
    {
        SetObjectMaterial( 0, GetMaterialForDamageState(false) );
        if (m_Light)
        {
            m_Light.FadeOut();
        }
        if ( GetGame().IsServer() )
        {
            //Safeguard if item is turned off by another event than running out of energy
            if (GetCompEM().GetEnergy() > 0)
                return;
            SetHealth(0);
        }
    }
References GetEnergy(), GetGame(), GetMaterialForDamageState(), m_Light, and SetHealth().
SetActions()
override void Chemlight_ColorBase::SetActions () inline private
Definition at line 158 of file chemlight.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnWhileInHands);
    }
References AddAction().
StandUp()
void Chemlight_ColorBase::StandUp () inline private
Definition at line 113 of file chemlight.c.
    {
        if ( GetGame().IsServer()  &&  GetCompEM().IsWorking() )
        {
            vector ori_rotate = "0 0 0";
            SetOrientation(ori_rotate);
        }
    }
References GetGame(), and SetOrientation().
Referenced by OnInventoryExit().
Member Data Documentation
m_DefaultMaterial
string Chemlight_ColorBase::m_DefaultMaterial private
Definition at line 3 of file chemlight.c.
Referenced by Chemlight_ColorBase(), and GetMaterialForDamageState().
m_Efficiency0To10
private int Chemlight_ColorBase::m_Efficiency0To10 private
Definition at line 8 of file chemlight.c.
Referenced by Chemlight_ColorBase(), GetEfficiency0To1(), and OnEnergyConsumed().
m_EfficiencyDecayStart
private float Chemlight_ColorBase::m_EfficiencyDecayStart = 0.05 static private
Definition at line 9 of file chemlight.c.
Referenced by GetEfficiencyDecayStart(), and OnEnergyConsumed().
m_GlowMaterial
string Chemlight_ColorBase::m_GlowMaterial private
Definition at line 4 of file chemlight.c.
Referenced by Chemlight_ColorBase(), and GetMaterialForDamageState().
m_Light
ChemlightLight Chemlight_ColorBase::m_Light private
Definition at line 6 of file chemlight.c.
Referenced by CreateLight(), OnWork(), and OnWorkStop().