DayzKode: CollapsibleHeader Class Reference
CollapsibleHeader Class Reference
Private Member Functions
void CollapsibleHeader (LayoutHolder parent, string function_name)
bool IsHeaderVisible ()
void SetArrowButtonOpened (bool state)
void SetHeaderVisible (bool show)
override void SetLayoutName ()
Detailed Description
Definition at line 1 of file collapsibleheader.c.
Constructor & Destructor Documentation
CollapsibleHeader()
void CollapsibleHeader::CollapsibleHeader (LayoutHolder parent, string function_name) inline private
Definition at line 3 of file collapsibleheader.c.
    {
        m_DefaultFontSize = 24;
    }
References Header::m_DefaultFontSize.
Member Function Documentation
IsHeaderVisible()
bool CollapsibleHeader::IsHeaderVisible () inline private
Definition at line 19 of file collapsibleheader.c.
    {
        return m_MainWidget.IsVisible(); //m_MainWidget.IsVisibleHierarchy()
    }
SetArrowButtonOpened()
void CollapsibleHeader::SetArrowButtonOpened (bool state) inline private
Definition at line 13 of file collapsibleheader.c.
    {
        m_UpArrowButton.Show(state);
        m_DownArrowButton.Show(!state);
    }
References Header::m_DownArrowButton, and Header::m_UpArrowButton.
Referenced by CollapsibleContainer::SetCollapsibleHeaderArrowState().
SetHeaderVisible()
void CollapsibleHeader::SetHeaderVisible (bool show) inline private
Definition at line 24 of file collapsibleheader.c.
    {
        m_MainWidget.Show(show);
    }
Referenced by AttachmentCategoriesContainer::CollapseButtonOnMouseButtonDown(), and AttachmentCategoriesContainer::OnHide().
SetLayoutName()
override void CollapsibleHeader::SetLayoutName () inline private
Definition at line 8 of file collapsibleheader.c.
    {
        m_LayoutName = WidgetLayoutName.CollapsibleHeader;
    }
References WidgetLayoutName::CollapsibleHeader.