DayzKode: WeaponManager Class Reference
WeaponManager Class Reference
Private Member Functions
bool AttachMagazine (Magazine mag, ActionBase control_action=NULL)
bool CanAttachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanDetachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanEjectBullet (Weapon_Base wpn, bool reservationCheck=true)
bool CanEjectBulletVerified ()
bool CanFire (Weapon_Base wpn)
bool CanLoadBullet (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanSwapMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck=true)
bool CanUnjam (Weapon_Base wpn, bool reservationCheck=true)
int CompareMagazinesSuitability (Magazine mag1, Magazine mag2)
void DelayedRefreshAnimationState (int delay)
bool DetachMagazine (InventoryLocation invLoc, ActionBase control_action=NULL)
bool EjectBullet (ActionBase control_action=NULL)
bool EjectBulletVerified (ActionBase control_action=NULL)
void Fire (Weapon_Base wpn)
string GetCurrentModeName ()
Magazine GetNextPreparedMagazine (out int startIdx)
Magazine GetPreparedMagazine ()
bool InventoryReservation (Magazine mag, InventoryLocation invLoc)
bool IsRunning ()
bool LoadBullet (Magazine mag, ActionBase control_action=NULL)
bool LoadMultiBullet (Magazine mag, ActionBase control_action=NULL)
void LoadMultiBulletStop ()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnLiftWeapon ()
void OnMagazineAttach (Magazine mag)
void OnMagazineDetach (Magazine mag)
void OnMagazineInventoryEnter (Magazine mag)
void OnMagazineInventoryExit (Magazine mag)
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
void OnWeaponActionEnd ()
bool PrepareInventoryLocationForMagazineSwap (notnull Weapon_Base wpn, notnull Magazine new_mag, out InventoryLocation new_il)
void Refresh ()
void RefreshAnimationState ()
void SetEjectBulletTryTimestamp ()
bool SetNextMuzzleMode ()
void SetRunning (bool value)
void SetSutableMagazines ()
void SortMagazineAfterLoad ()
bool StartAction (int action, Magazine mag, InventoryLocation il, ActionBase control_action=NULL)
void StartPendingAction ()
bool SwapMagazine (Magazine mag, ActionBase control_action=NULL)
bool SwapMagazineEx (Magazine mag, InventoryLocation invLoc, ActionBase control_action=NULL)
private void Synchronize ()
bool Unjam (ActionBase control_action=NULL)
void Update (float deltaT)
bool WantContinue ()
void WeaponManager (PlayerBase player)
Private Attributes
protected const int FORCE_EJECT_BULLET_TIMEOUT = 2000
protected int m_AnimationRefreshCooldown
protected bool m_canEnd
protected ActionBase m_ControlAction
protected int m_ForceEjectBulletTimestamp
protected bool m_InIronSight
protected bool m_InOptic
protected bool m_InProgress
protected bool m_IsEventSended
protected bool m_justStart
protected int m_LastAcknowledgmentID
protected MagazineStorage m_MagazineInHand
protected ref array< Magazine > m_MagazinePilesInInventory
protected ref array< MagazineStorage > m_MagazineStorageInInventory
protected float m_NewJamChance
protected ref InventoryLocation m_PendingInventoryLocation
protected Magazine m_PendingTargetMagazine
protected int m_PendingWeaponAction
protected int m_PendingWeaponActionAcknowledgmentID
protected PlayerBase m_player
protected Magazine m_PreparedMagazine
protected bool m_readyToStart
protected ref array< Magazine > m_SuitableMagazines
protected ref InventoryLocation m_TargetInventoryLocation
protected bool m_WaitToSyncJamChance
protected bool m_WantContinue
protected Weapon_Base m_WeaponInHand
const float MAX_DROP_MAGAZINE_DISTANCE_SQ = 4
Detailed Description
Definition at line 1 of file weaponmanager.c.
Constructor & Destructor Documentation
WeaponManager()
void WeaponManager::WeaponManager (PlayerBase player) inline private
Definition at line 45 of file weaponmanager.c.
    {
        m_ForceEjectBulletTimestamp = -1;
        m_player = player;
        m_PendingWeaponActionAcknowledgmentID = -1;
        m_PendingTargetMagazine = NULL;
        m_PendingInventoryLocation = NULL;
        m_WeaponInHand = NULL;
        m_MagazineInHand = NULL;
        m_ControlAction = NULL;
        m_PendingWeaponAction = -1;
        m_LastAcknowledgmentID = 1;
        m_InProgress = false;
        m_WantContinue = true;
        m_IsEventSended = false;
        m_canEnd = false;
        m_readyToStart = false;
        m_AnimationRefreshCooldown = 0;
        m_NewJamChance = -1;
        m_WaitToSyncJamChance = false;
        m_MagazinePilesInInventory = new array<Magazine>;
        m_MagazineStorageInInventory = new array<MagazineStorage>;
        m_SuitableMagazines = new array<Magazine>;
        m_PreparedMagazine = null;
#ifdef DEVELOPER
        m_BurstOption = 0;
#endif
    }
References m_AnimationRefreshCooldown, m_canEnd, m_ControlAction, m_ForceEjectBulletTimestamp, m_InProgress, m_IsEventSended, m_LastAcknowledgmentID, m_MagazineInHand, m_MagazinePilesInInventory, m_MagazineStorageInInventory, m_NewJamChance, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_PreparedMagazine, m_readyToStart, m_SuitableMagazines, m_WaitToSyncJamChance, m_WantContinue, and m_WeaponInHand.
Member Function Documentation
AttachMagazine()
bool WeaponManager::AttachMagazine (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 344 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_ATTACH_MAGAZINE, mag, NULL, control_action);
    }
References AT_WPN_ATTACH_MAGAZINE, and StartAction().
Referenced by ManBase::PredictiveTakeEntityToTargetAttachment(), ManBase::PredictiveTakeEntityToTargetAttachmentEx(), and ManBase::ReloadWeapon().
CanAttachMagazine()
bool WeaponManager::CanAttachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 92 of file weaponmanager.c.
    {
        if ( !wpn || !mag )
            return false;
        if ( m_player.GetHumanInventory().GetEntityInHands() != wpn )
            return false;
        if ( wpn.IsDamageDestroyed())
            return false;
        //if ( mag.GetHierarchyRootPlayer() && mag.GetHierarchyRootPlayer() != m_player )
            //return false;
        if( m_player.IsItemsToDelete())
            return false;
        if ( reservationCheck && (m_player.GetInventory().HasInventoryReservation(wpn, null) || m_player.GetInventory().HasInventoryReservation(mag, null)))
            return false;
        InventoryLocation invLoc;
        invLoc = new InventoryLocation();
        mag.GetInventory().GetCurrentInventoryLocation(invLoc);
        Weapon_Base wnp2;
        //magazine is already in weapon
        if ( Class.CastTo(wnp2,  invLoc.GetParent()) )
            return false;
        int muzzleIndex = wpn.GetCurrentMuzzle();
        if (wpn.CanAttachMagazine(muzzleIndex, mag))
            return true;
        return false;
    }
References Class::CastTo(), InventoryLocation::GetParent(), and m_player.
Referenced by ManBase::GetMagazineToReload().
CanDetachMagazine()
bool WeaponManager::CanDetachMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 181 of file weaponmanager.c.
    {
        if ( !wpn || !mag )
            return false;
        if ( m_player.GetHumanInventory().GetEntityInHands() != wpn )
            return false;
        if ( mag.GetHierarchyParent() != wpn )
            return false;
        if( m_player.IsItemsToDelete())
            return false;
        if ( reservationCheck && (m_player.GetInventory().HasInventoryReservation(wpn, null) || m_player.GetInventory().HasInventoryReservation(mag, null)))
            return false;
        return true;
    }
References m_player.
CanEjectBullet()
bool WeaponManager::CanEjectBullet (Weapon_Base wpn, bool reservationCheck = true) inline private
Definition at line 257 of file weaponmanager.c.
    {
        if( !wpn )
            return false;
        if( m_player.GetHumanInventory().GetEntityInHands() != wpn)
            return false;
        if( m_player.IsItemsToDelete())
            return false;
        if( reservationCheck && m_player.GetInventory().HasInventoryReservation(wpn, null))
            return false;
        if( !wpn.CanEjectBullet() )
            return false;
        if( wpn.IsJammed(/*wpn.GetCurrentMuzzle()*/) )
            return false;
        return true;
    }
References Weapon_Base::CanEjectBullet(), and m_player.
CanEjectBulletVerified()
bool WeaponManager::CanEjectBulletVerified () inline private
Definition at line 394 of file weaponmanager.c.
    {
        int mi = m_WeaponInHand.GetCurrentMuzzle();
        if( !m_WeaponInHand.IsChamberFiredOut(mi) && !m_WeaponInHand.IsChamberEmpty(mi) )
        {
            int actual_time = GetGame().GetTime();
            if ( actual_time - m_ForceEjectBulletTimestamp > FORCE_EJECT_BULLET_TIMEOUT )
            {
                return false;
            }
        }
        return true;
    }
References FORCE_EJECT_BULLET_TIMEOUT, GetGame(), CGame::GetTime(), m_ForceEjectBulletTimestamp, and m_WeaponInHand.
CanFire()
bool WeaponManager::CanFire (Weapon_Base wpn) inline private
Definition at line 79 of file weaponmanager.c.
    {
        if( m_player.GetHumanInventory().GetEntityInHands() != wpn )
            return false;
        if( m_player.IsLiftWeapon() || !m_player.IsRaised() || wpn.IsDamageDestroyed() || m_player.GetDayZPlayerInventory().IsProcessing() || !m_player.IsWeaponRaiseCompleted() || m_player.IsFighting() )
            return false;
        return true;
    }
References m_player.
CanLoadBullet()
bool WeaponManager::CanLoadBullet (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 201 of file weaponmanager.c.
    {
        if ( !wpn || !mag )
            return false;
        if ( m_player.GetHumanInventory().GetEntityInHands() != wpn )
            return false;
        if( mag.IsDamageDestroyed() || wpn.IsDamageDestroyed())
            return false;
        //if ( mag.GetHierarchyRootPlayer() && mag.GetHierarchyRootPlayer() != m_player )
        //  return false;
        if( wpn.IsJammed(/*wpn.GetCurrentMuzzle()*/) )
            return false;
        if( m_player.IsItemsToDelete())
            return false;
        if ( reservationCheck && (m_player.GetInventory().HasInventoryReservation(wpn,null) || m_player.GetInventory().HasInventoryReservation(mag,null)))
            return false;
        for( int i = 0; i < wpn.GetMuzzleCount(); i++)
        {
            if( wpn.CanChamberBullet( i, mag ) )
                return true;
        }
        return false;
    }
References Weapon_Base::CanChamberBullet(), and m_player.
Referenced by ManBase::GetMagazineToReload().
CanSwapMagazine()
bool WeaponManager::CanSwapMagazine (Weapon_Base wpn, Magazine mag, bool reservationCheck = true) inline private
Definition at line 133 of file weaponmanager.c.
    {
        if ( !wpn || !mag )
            return false;
        if ( m_player.GetHumanInventory().GetEntityInHands() != wpn )
            return false;
        if ( mag.IsDamageDestroyed() || wpn.IsDamageDestroyed())
            return false;
        //if ( mag.GetHierarchyRootPlayer() && mag.GetHierarchyRootPlayer() != m_player )
            //return false;
        if( m_player.IsItemsToDelete())
            return false;
        if ( reservationCheck && (m_player.GetInventory().HasInventoryReservation(wpn, null) || m_player.GetInventory().HasInventoryReservation(mag, null)))
            return false;
        InventoryLocation invLoc;
        invLoc = new InventoryLocation();
        mag.GetInventory().GetCurrentInventoryLocation(invLoc);
        Weapon_Base wnp2;
        //second magazine is already in weapon
        if( Class.CastTo(wnp2,  invLoc.GetParent()) )
            return false;
        int muzzleIndex = wpn.GetCurrentMuzzle();
        Magazine mag2;
        if( !Class.CastTo(mag2, wpn.GetMagazine(muzzleIndex)) )
            return false;
        if( GameInventory.CanSwapEntitiesEx( mag, mag2 ) )
            return true;
        InventoryLocation il = new InventoryLocation();
        if( GameInventory.CanForceSwapEntitiesEx( mag, null, mag2, il ) )
            return true;
        return false;
    }
References Class::CastTo(), InventoryLocation::GetParent(), and m_player.
Referenced by ManBase::GetMagazineToReload().
CanUnjam()
bool WeaponManager::CanUnjam (Weapon_Base wpn, bool reservationCheck = true) inline private
Definition at line 233 of file weaponmanager.c.
    {
        if( !wpn )
            return false;
        if( m_player.GetHumanInventory().GetEntityInHands() != wpn)
            return false;
        if( wpn.IsDamageDestroyed())
            return false;
        if( m_player.IsItemsToDelete())
            return false;
        if ( reservationCheck && m_player.GetInventory().HasInventoryReservation(wpn, null))
            return false;
        if( !wpn.IsJammed(/*wpn.GetCurrentMuzzle()*/) )
            return false;
        return true;
    }
References m_player.
CompareMagazinesSuitability()
int WeaponManager::CompareMagazinesSuitability (Magazine mag1, Magazine mag2) inline private
Definition at line 1135 of file weaponmanager.c.
    {
        return mag1.GetAmmoCount() - mag2.GetAmmoCount();
    }
Referenced by OnMagazineInventoryEnter().
DelayedRefreshAnimationState()
void WeaponManager::DelayedRefreshAnimationState (int delay) inline private
Definition at line 986 of file weaponmanager.c.
    {
        if(m_WeaponInHand)
        {
            if(delay == 0)
            {
                RefreshAnimationState();
            }
            m_AnimationRefreshCooldown = delay;
        }
    }
References m_AnimationRefreshCooldown, m_WeaponInHand, and RefreshAnimationState().
Referenced by ManBase::OnCommandClimbStart(), ManBase::OnCommandDeathStart(), ManBase::OnCommandFallStart(), ManBase::OnCommandMelee2Start(), ManBase::OnCommandSwimStart(), and ManBase::OnJumpStart().
DetachMagazine()
bool WeaponManager::DetachMagazine (InventoryLocation invLoc, ActionBase control_action = NULL) inline private
Definition at line 349 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_DETACH_MAGAZINE, NULL, invLoc, control_action);
    }
References AT_WPN_DETACH_MAGAZINE, and StartAction().
Referenced by ManBase::PredictiveDropEntity(), ManBase::PredictiveTakeEntityToInventory(), ManBase::PredictiveTakeEntityToTargetCargo(), ManBase::PredictiveTakeEntityToTargetCargoEx(), ManBase::PredictiveTakeEntityToTargetInventory(), and ManBase::PredictiveTakeToDst().
EjectBullet()
bool WeaponManager::EjectBullet (ActionBase control_action = NULL) inline private
Definition at line 389 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_EJECT_BULLET, NULL, NULL, control_action);
    }
References AT_WPN_EJECT_BULLET, and StartAction().
Referenced by HandleWeapons().
EjectBulletVerified()
bool WeaponManager::EjectBulletVerified (ActionBase control_action = NULL) inline private
Definition at line 408 of file weaponmanager.c.
    {
        if ( m_WeaponInHand )
        {
            int mi = m_WeaponInHand.GetCurrentMuzzle();
            if ( !m_WeaponInHand.IsChamberFiredOut(mi) && !m_WeaponInHand.IsChamberEmpty(mi) )
            {
                m_ForceEjectBulletTimestamp = GetGame().GetTime();
                return StartAction(AT_WPN_EJECT_BULLET, NULL, NULL, control_action);
            }
            else
            {
                return StartAction(AT_WPN_EJECT_BULLET, NULL, NULL, control_action);
            }
        }
        return false;
    }
References AT_WPN_EJECT_BULLET, GetGame(), CGame::GetTime(), m_ForceEjectBulletTimestamp, m_WeaponInHand, and StartAction().
Fire()
void WeaponManager::Fire (Weapon_Base wpn) inline private
Definition at line 431 of file weaponmanager.c.
    {
        int mi = wpn.GetCurrentMuzzle();
        if( wpn.IsChamberFiredOut(mi) || wpn.IsJammed() || wpn.IsChamberEmpty(mi) )
        {
            wpn.ProcessWeaponEvent(new WeaponEventTrigger(m_player));
            return;
        }
        if(wpn.JamCheck(0))
        {
            wpn.ProcessWeaponEvent(new WeaponEventTriggerToJam(m_player));
        }
        else
        {
            wpn.ProcessWeaponEvent(new WeaponEventTrigger(m_player));
        }
    }
References m_player.
Referenced by HandleWeapons().
GetCurrentModeName()
string WeaponManager::GetCurrentModeName () inline private
Definition at line 1268 of file weaponmanager.c.
    {
        if( m_WeaponInHand )
        {
            int mi = m_WeaponInHand.GetCurrentMuzzle();
            return m_WeaponInHand.GetCurrentModeName(mi);
        }
        return "";
    }
References m_WeaponInHand.
GetNextPreparedMagazine()
Magazine WeaponManager::GetNextPreparedMagazine (out int startIdx) inline private
Definition at line 1037 of file weaponmanager.c.
    {
        for (int i = startIdx; i < m_SuitableMagazines.Count(); i++)
        {
            if (m_SuitableMagazines.Get(i).GetAmmoCount() > 0)
            {
                startIdx = i;
                return m_SuitableMagazines.Get(i);
            }
        }
        return null;
    }
References m_SuitableMagazines.
Referenced by FirearmActionLoadMultiBulletQuick::Start().
GetPreparedMagazine()
Magazine WeaponManager::GetPreparedMagazine () inline private
Definition at line 1020 of file weaponmanager.c.
    {
        for (int i = 0; i < m_SuitableMagazines.Count(); i++)
        {
            if(!m_SuitableMagazines.Get(i) || m_SuitableMagazines.Get(i).IsRuined() )
            {
                m_SuitableMagazines.Remove(i);
                i--;
                continue;
            }
            if (m_SuitableMagazines.Get(i).GetAmmoCount() > 0)
                return m_SuitableMagazines.Get(i);
        }
        return null;
    }
References m_SuitableMagazines.
InventoryReservation()
bool WeaponManager::InventoryReservation (Magazine mag, InventoryLocation invLoc) inline private
Definition at line 285 of file weaponmanager.c.
    {
        Weapon_Base weapon;
        InventoryLocation ilWeapon = new InventoryLocation();
        if (Weapon_Base.CastTo(weapon, m_player.GetItemInHands()) )
        {
            weapon.GetInventory().GetCurrentInventoryLocation(ilWeapon);
            if ( m_player.GetInventory().HasInventoryReservation(weapon, ilWeapon) )
            {
                return false;
            }
            else
            {
                m_player.GetInventory().AddInventoryReservationEx(weapon,ilWeapon,GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if( invLoc )
        {
            if ( m_player.GetInventory().HasInventoryReservation(invLoc.GetItem(),invLoc) )
            {
                m_player.GetInventory().ClearInventoryReservationEx(weapon, ilWeapon);
                return false;
            }
            else
            {
                m_player.GetInventory().AddInventoryReservationEx(invLoc.GetItem(),invLoc,GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if( mag )
        {
            m_TargetInventoryLocation = new InventoryLocation();
            m_TargetInventoryLocation.SetAttachment( m_WeaponInHand, mag, InventorySlots.MAGAZINE);
            if ( m_player.GetInventory().HasInventoryReservation(mag, m_TargetInventoryLocation) )
            //if ( !m_player.GetInventory().AddInventoryReservationEx( mag, m_TargetInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS) )
            {
                m_player.GetInventory().ClearInventoryReservationEx(weapon, ilWeapon);
                if (invLoc)
                {
                    m_player.GetInventory().ClearInventoryReservationEx(invLoc.GetItem(), invLoc);
                }
                return false;
            }
            else
            {
                m_player.GetInventory().AddInventoryReservationEx(mag, m_TargetInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        m_PendingTargetMagazine = mag;
        m_PendingInventoryLocation = invLoc;
        return true;
    }
References InventoryLocation::GetItem(), m_PendingInventoryLocation, m_PendingTargetMagazine, m_player, m_TargetInventoryLocation, m_WeaponInHand, and InventoryLocation::SetAttachment().
Referenced by StartAction().
IsRunning()
bool WeaponManager::IsRunning () inline private
Definition at line 818 of file weaponmanager.c.
    {
        return m_InProgress;
    }
References m_InProgress.
LoadBullet()
bool WeaponManager::LoadBullet (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 369 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_LOAD_BULLET, mag, NULL, control_action);
    }
References AT_WPN_LOAD_BULLET, and StartAction().
LoadMultiBullet()
bool WeaponManager::LoadMultiBullet (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 374 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_LOAD_MULTI_BULLETS_START, mag, NULL, control_action);
    }
References AT_WPN_LOAD_MULTI_BULLETS_START, and StartAction().
LoadMultiBulletStop()
void WeaponManager::LoadMultiBulletStop () inline private
Definition at line 379 of file weaponmanager.c.
    {
        if(m_InProgress) m_WantContinue = false;
    }
References m_InProgress, and m_WantContinue.
OnInputUserDataProcess()
bool WeaponManager::OnInputUserDataProcess (int userDataType, ParamsReadContext ctx) inline private
Definition at line 574 of file weaponmanager.c.
    {
        Weapon_Base wpn;
        int mi;
        InventoryLocation il;
        int slotID;
        bool accepted = false;
        if( userDataType == INPUT_UDT_WEAPON_ACTION)
        {
            if (!ctx.Read(m_PendingWeaponAction))
                return false;
            if (!ctx.Read(m_PendingWeaponActionAcknowledgmentID))
                return false;
            if(m_PendingTargetMagazine)
            {
                GetGame().ClearJuncture(m_player, m_PendingTargetMagazine);
                m_PendingTargetMagazine = NULL;
            }
            m_InProgress = true;
            m_IsEventSended = false;
            Magazine mag = NULL;
            Weapon_Base.CastTo( wpn, m_player.GetItemInHands() );
            if ( wpn )
                mi = wpn.GetCurrentMuzzle();
            switch (m_PendingWeaponAction)
            {
                case AT_WPN_ATTACH_MAGAZINE:
                {
                    if ( !ctx.Read(mag) )
                        break;
                    if ( !mag || !wpn )
                        break;
                    slotID = wpn.GetSlotFromMuzzleIndex(mi);
                    il = new InventoryLocation();
                    il.SetAttachment(wpn,mag,slotID);
                    if( GetGame().AddInventoryJunctureEx(m_player, mag, il, false, 10000) )
                        accepted = true;
                    m_PendingTargetMagazine = mag;
                    break;
                }
                case AT_WPN_SWAP_MAGAZINE:
                {
                    if ( !ctx.Read(mag) )
                        break;
                    il = new InventoryLocation();
                    if (!il.ReadFromContext(ctx))
                        break;
                    if ( !mag || !wpn )
                        break;
                    if ( !wpn.GetMagazine(mi) )
                        break;
                    if ( GetGame().AddActionJuncture(m_player,mag,10000) )
                        accepted = true;
                    m_PendingInventoryLocation = il;
                    m_PendingTargetMagazine = mag;
                    break;
                }
                case AT_WPN_DETACH_MAGAZINE:
                {
                    il = new InventoryLocation();
                    if ( !il.ReadFromContext(ctx) )
                        break;
                    if ( !il.IsValid() )
                        break;
                    if ( !wpn )
                        break;
                    Magazine det_mag = wpn.GetMagazine(mi);
                    mag = Magazine.Cast(il.GetItem());
                    if ( !det_mag || ( mag != det_mag) )
                        break;
                    if( GetGame().AddInventoryJunctureEx(m_player, il.GetItem(), il, true, 10000))
                        accepted = true;
                    m_PendingInventoryLocation = il;
                    m_PendingTargetMagazine = mag;
                    break;
                }
                case AT_WPN_LOAD_BULLET:
                {
                    ctx.Read(mag);
                    if ( !mag )
                        break;
                    if( GetGame().AddActionJuncture(m_player,mag,10000) )
                        accepted = true;
                    m_PendingTargetMagazine = mag;
                    break;
                }
                case AT_WPN_LOAD_MULTI_BULLETS_START:
                {
                    ctx.Read(mag);
                    if ( !mag )
                        break;
                    if( GetGame().AddActionJuncture(m_player,mag,10000) )
                        accepted = true;
                    m_PendingTargetMagazine = mag;
                    break;
                }
                case AT_WPN_UNJAM:
                {
                    accepted = true;
                    //Unjam();
                    break;
                }
                case AT_WPN_EJECT_BULLET:
                {
                    accepted = true;
                    break;
                }
                case AT_WPN_SET_NEXT_MUZZLE_MODE:
                {
                    accepted = true;
                    break;
                }
                default:
                    Error("unknown actionID=" + m_PendingWeaponAction);
                    break;
            }
            DayZPlayerSyncJunctures.SendWeaponActionAcknowledgment(m_player, m_PendingWeaponActionAcknowledgmentID, accepted);
        }
        return accepted;
    }
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SET_NEXT_MUZZLE_MODE, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, CGame::ClearJuncture(), Error(), GetGame(), InventoryLocation::GetItem(), INPUT_UDT_WEAPON_ACTION, InventoryLocation::IsValid(), m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, Serializer::Read(), InventoryLocation::ReadFromContext(), DayZPlayerSyncJunctures::SendWeaponActionAcknowledgment(), and InventoryLocation::SetAttachment().
OnLiftWeapon()
void WeaponManager::OnLiftWeapon () inline private
Definition at line 1262 of file weaponmanager.c.
    {
        if( m_WeaponInHand )
            m_WeaponInHand.ResetBurstCount();
    }
References m_WeaponInHand.
Referenced by ManBase::ProcessLiftWeapon(), and ManBase::SendLiftWeaponSync().
OnMagazineAttach()
void WeaponManager::OnMagazineAttach (Magazine mag) inline private
Definition at line 1125 of file weaponmanager.c.
    {
        OnMagazineInventoryExit(mag);
    }
References OnMagazineInventoryExit().
OnMagazineDetach()
void WeaponManager::OnMagazineDetach (Magazine mag) inline private
Definition at line 1130 of file weaponmanager.c.
    {
        OnMagazineInventoryEnter(mag);
    }
References OnMagazineInventoryEnter().
OnMagazineInventoryEnter()
void WeaponManager::OnMagazineInventoryEnter (Magazine mag) inline private
Definition at line 1050 of file weaponmanager.c.
    {
        if (mag)
        {
            Weapon_Base weapon = Weapon_Base.Cast(mag.GetHierarchyParent());
            if (weapon)
                return;
        }
        int i;
        MagazineStorage sMag = MagazineStorage.Cast(mag);
        if(sMag)
        {
            for(i = 0; i < m_MagazineStorageInInventory.Count(); i++ )
            {
                MagazineStorage s_mag_i = m_MagazineStorageInInventory[i];
                if(!s_mag_i)
                {
                    m_MagazineStorageInInventory.RemoveOrdered(i);
                    i--;
                    continue;
                }
                if(CompareMagazinesSuitability(s_mag_i,sMag)<0)
                    break;
            }
            m_MagazineStorageInInventory.InsertAt(sMag,i);
            SetSutableMagazines(); //TODO optimalize
            return;
        }
        if(mag)
        {
            for(i = 0; i < m_MagazinePilesInInventory.Count(); i++ )
            {
                Magazine mag_i = m_MagazinePilesInInventory[i];
                if(!mag_i)
                {
                    m_MagazinePilesInInventory.RemoveOrdered(i);
                    i--;
                    continue;
                }
                if(CompareMagazinesSuitability(mag_i,mag)<0)
                {
                    break;
                }
            }
            m_MagazinePilesInInventory.InsertAt(mag,i);
            SetSutableMagazines(); //TODO optimalize
        }
    }
References CompareMagazinesSuitability(), m_MagazinePilesInInventory, m_MagazineStorageInInventory, and SetSutableMagazines().
Referenced by OnMagazineDetach().
OnMagazineInventoryExit()
void WeaponManager::OnMagazineInventoryExit (Magazine mag) inline private
Definition at line 1108 of file weaponmanager.c.
    {
        m_SuitableMagazines.RemoveItem(mag);
        MagazineStorage sMag = MagazineStorage.Cast(mag);
        if(sMag)
        {
            m_MagazineStorageInInventory.RemoveItem(sMag);
            return;
        }
        if(mag)
        {
            m_MagazinePilesInInventory.RemoveItem(mag);
        }
    }
References m_MagazinePilesInInventory, m_MagazineStorageInInventory, and m_SuitableMagazines.
Referenced by OnMagazineAttach().
OnSyncJuncture()
void WeaponManager::OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx) inline private
Definition at line 524 of file weaponmanager.c.
    {
        if (pJunctureID == DayZPlayerSyncJunctures.SJ_WEAPON_SET_JAMMING_CHANCE )
        {
            pCtx.Read(m_NewJamChance);
        }
        else
        {
            int AcknowledgmentID;
            pCtx.Read(AcknowledgmentID);
            if ( AcknowledgmentID == m_PendingWeaponActionAcknowledgmentID)
            {
                if (pJunctureID == DayZPlayerSyncJunctures.SJ_WEAPON_ACTION_ACK_ACCEPT)
                {
                    m_readyToStart = true;
                }
                else if (pJunctureID == DayZPlayerSyncJunctures.SJ_WEAPON_ACTION_ACK_REJECT)
                {
                    if(m_PendingWeaponAction >= 0 )
                    {
                        if(!(GetGame().IsServer() && GetGame().IsMultiplayer()))
{
                            InventoryLocation ilWeapon = new InventoryLocation();
                            ItemBase weapon = m_player.GetItemInHands();
                            weapon.GetInventory().GetCurrentInventoryLocation(ilWeapon);
                            m_player.GetInventory().ClearInventoryReservationEx(m_player.GetItemInHands(),ilWeapon);
                            if( m_PendingTargetMagazine )
{
                                m_PendingTargetMagazine.GetInventory().ClearInventoryReservationEx(m_PendingTargetMagazine, m_TargetInventoryLocation );
                            }
                            if( m_PendingInventoryLocation )
{
                                m_player.GetInventory().ClearInventoryReservationEx( NULL, m_PendingInventoryLocation );
                            }
                        }
                        m_PendingWeaponActionAcknowledgmentID = -1;
                        m_PendingTargetMagazine = NULL;
                        m_PendingWeaponAction = -1;
                        m_PendingInventoryLocation = NULL;
                        m_InProgress = false;
                    }
                }
            }
        }
    }
References GetGame(), m_InProgress, m_NewJamChance, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_readyToStart, m_TargetInventoryLocation, Serializer::Read(), DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_ACCEPT, DayZPlayerSyncJunctures::SJ_WEAPON_ACTION_ACK_REJECT, and DayZPlayerSyncJunctures::SJ_WEAPON_SET_JAMMING_CHANCE.
OnWeaponActionEnd()
void WeaponManager::OnWeaponActionEnd () inline private
Definition at line 941 of file weaponmanager.c.
    {
        if ( !m_InProgress )
            return;
        if (!m_ControlAction)
        {
            if(GetGame().IsServer() && GetGame().IsMultiplayer())
            {
                if(m_PendingTargetMagazine)
                {
                    GetGame().ClearJuncture(m_player,m_PendingTargetMagazine);
                }
            }
            else
            {
                InventoryLocation il = new InventoryLocation();
                il.SetHands(m_player,m_player.GetItemInHands());
                m_player.GetInventory().ClearInventoryReservationEx(m_player.GetItemInHands(),il);
                if( m_PendingTargetMagazine )
                {
                    m_player.GetInventory().ClearInventoryReservationEx(m_PendingTargetMagazine, m_TargetInventoryLocation );
                }
                if( m_PendingInventoryLocation )
                {
                    m_player.GetInventory().ClearInventoryReservationEx( m_PendingInventoryLocation.GetItem(), m_PendingInventoryLocation );
                }
            }
        }
        m_ControlAction = NULL;
        m_PendingWeaponAction = -1;
        m_PendingTargetMagazine = NULL;
        m_PendingInventoryLocation = NULL;
        m_TargetInventoryLocation = NULL;
        m_PendingWeaponActionAcknowledgmentID = -1;
        //m_WeaponInHand = NULL;
        m_InProgress = false;
        m_readyToStart = false;
        m_WantContinue = true;
    }
References CGame::ClearJuncture(), GetGame(), InventoryLocation::GetItem(), m_ControlAction, m_InProgress, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, m_player, m_readyToStart, m_TargetInventoryLocation, m_WantContinue, and InventoryLocation::SetHands().
Referenced by Refresh(), StartPendingAction(), and Update().
PrepareInventoryLocationForMagazineSwap()
bool WeaponManager::PrepareInventoryLocationForMagazineSwap (notnull Weapon_Base wpn, notnull Magazine new_mag, out InventoryLocation new_il) inline private
Definition at line 1278 of file weaponmanager.c.
    {
        int muzzleIndex = wpn.GetCurrentMuzzle();
        Magazine old_mag = Magazine.Cast(wpn.GetMagazine(muzzleIndex));
        InventoryLocation temp = new InventoryLocation();
        if (old_mag)
        {
            bool result = GameInventory.CanSwapEntitiesEx(new_mag, old_mag);
            if ( result )
            {
                new_mag.GetInventory().GetCurrentInventoryLocation(new_il);
                new_il.SetItem(old_mag);
            }
            else
            {
                result = GameInventory.CanForceSwapEntitiesEx(new_mag, null, old_mag, new_il);
                float dir[4];
                if ( !result )
                {
                    new_il.SetGroundEx( old_mag,  m_player.GetPosition(), dir);
                }
            }
        }
        return true;
    }
References m_player.
Referenced by SwapMagazine().
Refresh()
void WeaponManager::Refresh () inline private
Definition at line 828 of file weaponmanager.c.
    {
        OnWeaponActionEnd();
    }
References OnWeaponActionEnd().
RefreshAnimationState()
void WeaponManager::RefreshAnimationState () inline private
Definition at line 998 of file weaponmanager.c.
    {
        if(m_WeaponInHand)
        {
            WeaponStableState state = WeaponStableState.Cast( m_WeaponInHand.GetCurrentState() );
            if (state)
            {
                HumanCommandWeapons hcw = m_player.GetCommandModifier_Weapons();
                if (hcw)
                {
                    hcw.SetInitState(state.m_animState);
                }
            }
        }
    }
References m_player, m_WeaponInHand, and HumanCommandWeapons::SetInitState().
Referenced by DelayedRefreshAnimationState(), ManBase::OnCommandClimbFinish(), ManBase::OnCommandFallFinish(), ManBase::OnCommandMelee2Finish(), ManBase::OnCommandSwimFinish(), ManBase::OnJumpEnd(), ManBase::OnStanceChange(), and Update().
SetEjectBulletTryTimestamp()
void WeaponManager::SetEjectBulletTryTimestamp () inline private
Definition at line 280 of file weaponmanager.c.
    {
        m_ForceEjectBulletTimestamp = GetGame().GetTime();
    }
References GetGame(), CGame::GetTime(), and m_ForceEjectBulletTimestamp.
SetNextMuzzleMode()
bool WeaponManager::SetNextMuzzleMode () inline private
Definition at line 426 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_SET_NEXT_MUZZLE_MODE, NULL, NULL, NULL);
    }
References AT_WPN_SET_NEXT_MUZZLE_MODE, and StartAction().
Referenced by HandleWeapons().
SetRunning()
void WeaponManager::SetRunning (bool value) inline private
Definition at line 823 of file weaponmanager.c.
    {
        m_InProgress = value;
    }
References m_InProgress.
SetSutableMagazines()
void WeaponManager::SetSutableMagazines () inline private
Definition at line 1201 of file weaponmanager.c.
    {
        m_SuitableMagazines.Clear();
        int i;
        if (m_WeaponInHand)
        {
            int mi = m_WeaponInHand.GetCurrentMuzzle();
            for (i = 0; i < m_MagazineStorageInInventory.Count(); i++ )
            {
                MagazineStorage s_mag = m_MagazineStorageInInventory[i];
                if (!s_mag)
                {
                    m_MagazineStorageInInventory.RemoveOrdered(i);
                    i--;
                    continue;
                }
                if ( m_WeaponInHand.TestAttachMagazine(mi, s_mag, false, true))
                    m_SuitableMagazines.Insert(s_mag);
            }
            for (i = 0; i < m_MagazinePilesInInventory.Count(); i++ )
            {
                Magazine mag = m_MagazinePilesInInventory[i];
                if (!mag)
                {
                    m_MagazinePilesInInventory.RemoveOrdered(i);
                    i--;
                    continue;
                }
                if (m_WeaponInHand.CanChamberFromMag(mi, mag))
                    m_SuitableMagazines.Insert(mag);
            }
//TODO m_MagazineStorageInInventory and m_MagazinePilesInInventory always sort
        }
        else if (m_MagazineInHand)
        {
            for (i = 0; i < m_MagazinePilesInInventory.Count(); i++ )
            {
                Magazine m_mag = m_MagazinePilesInInventory[i];
                if (!m_mag)
                {
                    m_MagazinePilesInInventory.RemoveOrdered(i);
                    i--;
                    continue;
                }
                if (m_MagazineInHand.IsCompatiableAmmo( m_mag ))
                    m_SuitableMagazines.Insert(m_mag);
            }
        }
        else
        {
            m_PreparedMagazine = null;
        }
    }
References m_MagazineInHand, m_MagazinePilesInInventory, m_MagazineStorageInInventory, m_PreparedMagazine, m_SuitableMagazines, and m_WeaponInHand.
Referenced by OnMagazineInventoryEnter(), SortMagazineAfterLoad(), and Update().
SortMagazineAfterLoad()
void WeaponManager::SortMagazineAfterLoad () inline private
Definition at line 1140 of file weaponmanager.c.
    {
        array<MagazineStorage>  magazines = new array<MagazineStorage>;
        array<Magazine> magazines_piles = new array<Magazine>;
        int low_mag1, high_mag1;
        int low_mag2, high_mag2;
        int i, j;
        for(i = 0; i < m_MagazineStorageInInventory.Count(); i++ )
        {
            MagazineStorage mag = m_MagazineStorageInInventory.Get(i);
            mag.GetNetworkID(low_mag1,high_mag1);
            for( j = 0; j < magazines.Count(); j++)
            {
                magazines.Get(j).GetNetworkID(low_mag2,high_mag2);
                if(low_mag1 > low_mag2)
                {
                    break;
                }
                else if (low_mag1 == low_mag2)
                {
                    if( high_mag1 > high_mag2 )
                    {
                        break;
                    }
                }
            }
            magazines.InsertAt(mag,j);
        }
        m_MagazineStorageInInventory.Clear();
        m_MagazineStorageInInventory.Copy(magazines);
        for(i = 0; i < m_MagazinePilesInInventory.Count(); i++ )
        {
            Magazine pile = m_MagazinePilesInInventory.Get(i);
            pile.GetNetworkID(low_mag1,high_mag1);
            for( j = 0; j < magazines_piles.Count(); j++)
            {
                magazines_piles.Get(j).GetNetworkID(low_mag2,high_mag2);
                if(low_mag1 > low_mag2)
                {
                    break;
                }
                else if (low_mag1 == low_mag2)
                {
                    if( high_mag1 > high_mag2 )
                    {
                        break;
                    }
                }
            }
            magazines_piles.InsertAt(pile,j);
        }
        m_MagazinePilesInInventory.Clear();
        m_MagazinePilesInInventory.Copy(magazines_piles);
        SetSutableMagazines();
    }
References m_MagazinePilesInInventory, m_MagazineStorageInInventory, and SetSutableMagazines().
StartAction()
bool WeaponManager::StartAction (int action, Magazine mag, InventoryLocation il, ActionBase control_action = NULL) inline private
Definition at line 716 of file weaponmanager.c.
    {
        //if it is controled by action inventory reservation and synchronization provide action itself
        if(control_action)
        {
            m_ControlAction = ActionBase.Cast(control_action);
            m_PendingWeaponAction = action;
            m_InProgress = true;
            m_IsEventSended = false;
            m_PendingTargetMagazine = mag;
            m_PendingInventoryLocation = il;
            StartPendingAction();
            return true;
        }
        if (GetGame().IsMultiplayer() && GetGame().IsServer())
            return false;
        if ( !ScriptInputUserData.CanStoreInputUserData() )
            return false;
        if ( !InventoryReservation(mag, il) )
            return false;
        m_PendingWeaponAction = action;
        m_InProgress = true;
        m_IsEventSended = false;
        if ( !GetGame().IsMultiplayer() )
            m_readyToStart = true;
        else
            Synchronize();
        return true;
    }
References ActionBase(), ScriptInputUserData::CanStoreInputUserData(), GetGame(), InventoryReservation(), m_ControlAction, m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_readyToStart, StartPendingAction(), and Synchronize().
Referenced by AttachMagazine(), DetachMagazine(), EjectBullet(), EjectBulletVerified(), LoadBullet(), LoadMultiBullet(), SetNextMuzzleMode(), SwapMagazine(), SwapMagazineEx(), and Unjam().
StartPendingAction()
void WeaponManager::StartPendingAction () inline private
Definition at line 753 of file weaponmanager.c.
    {
        m_WeaponInHand = Weapon_Base.Cast(m_player.GetItemInHands());
        if(!m_WeaponInHand)
        {
            OnWeaponActionEnd();
            return;
        }
        switch (m_PendingWeaponAction)
        {
            case AT_WPN_ATTACH_MAGAZINE:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventAttachMagazine(m_player, m_PendingTargetMagazine) );
                break;
            }
            case AT_WPN_SWAP_MAGAZINE:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventSwapMagazine(m_player, m_PendingTargetMagazine, m_PendingInventoryLocation) );
                break;
            }
            case AT_WPN_DETACH_MAGAZINE:
            {
                Magazine mag = Magazine.Cast(m_PendingInventoryLocation.GetItem());
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventDetachMagazine(m_player, mag, m_PendingInventoryLocation) );
                break;
            }
            case AT_WPN_LOAD_BULLET:
            {
                m_WantContinue = false;
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventLoad1Bullet(m_player, m_PendingTargetMagazine) );
                break;
            }
            case AT_WPN_LOAD_MULTI_BULLETS_START:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventLoad1Bullet(m_player, m_PendingTargetMagazine) );
                break;
            }
            case AT_WPN_LOAD_MULTI_BULLETS_END:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventContinuousLoadBulletEnd(m_player) );
                break;
            }
            case AT_WPN_UNJAM:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventUnjam(m_player, NULL) );
                break;
            }
            case AT_WPN_EJECT_BULLET:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventMechanism(m_player, NULL) );
                break;
            }
            case AT_WPN_SET_NEXT_MUZZLE_MODE:
            {
                m_player.GetDayZPlayerInventory().PostWeaponEvent( new WeaponEventSetNextMuzzleMode(m_player, NULL) );
                break;
            }
            default:
                m_InProgress = false;
                Error("unknown actionID=" + m_PendingWeaponAction);
        }
        m_IsEventSended = true;
        m_canEnd = false;
    }
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_END, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SET_NEXT_MUZZLE_MODE, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, Error(), InventoryLocation::GetItem(), m_canEnd, m_InProgress, m_IsEventSended, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_player, m_WantContinue, m_WeaponInHand, and OnWeaponActionEnd().
Referenced by StartAction(), and Update().
SwapMagazine()
bool WeaponManager::SwapMagazine (Magazine mag, ActionBase control_action = NULL) inline private
Definition at line 354 of file weaponmanager.c.
    {
        InventoryLocation il = new InventoryLocation();
        if (PrepareInventoryLocationForMagazineSwap(m_WeaponInHand, mag, il) )
        {
            return StartAction(AT_WPN_SWAP_MAGAZINE, mag, il, control_action);
        }
        return false;
    }
References AT_WPN_SWAP_MAGAZINE, m_WeaponInHand, PrepareInventoryLocationForMagazineSwap(), and StartAction().
Referenced by ManBase::PredictiveSwapEntities(), and ManBase::ReloadWeapon().
SwapMagazineEx()
bool WeaponManager::SwapMagazineEx (Magazine mag, InventoryLocation invLoc, ActionBase control_action = NULL) inline private
Definition at line 364 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_SWAP_MAGAZINE, mag, invLoc, control_action);
    }
References AT_WPN_SWAP_MAGAZINE, and StartAction().
Synchronize()
private void WeaponManager::Synchronize () inline private
Definition at line 465 of file weaponmanager.c.
    {
        if( GetGame().IsClient() )
        {
            m_PendingWeaponActionAcknowledgmentID = ++m_LastAcknowledgmentID;
            ScriptInputUserData ctx = new ScriptInputUserData;
            ctx.Write(INPUT_UDT_WEAPON_ACTION);
            ctx.Write(m_PendingWeaponAction);
            ctx.Write(m_PendingWeaponActionAcknowledgmentID);
            switch (m_PendingWeaponAction)
            {
                case AT_WPN_ATTACH_MAGAZINE:
                {
                    ctx.Write(m_PendingTargetMagazine);
                    break;
                }
                case AT_WPN_SWAP_MAGAZINE:
                {
                    ctx.Write(m_PendingTargetMagazine);
                    m_PendingInventoryLocation.WriteToContext(ctx);
                    break;
                }
                case AT_WPN_DETACH_MAGAZINE:
                {
                    m_PendingInventoryLocation.WriteToContext(ctx);
                    break;
                }
                case AT_WPN_LOAD_BULLET:
                {
                    ctx.Write(m_PendingTargetMagazine);
                    break;
                }
                case AT_WPN_LOAD_MULTI_BULLETS_START:
                {
                    ctx.Write(m_PendingTargetMagazine);
                    break;
                }
                case AT_WPN_UNJAM:
                {
                    break;
                }
                case AT_WPN_EJECT_BULLET:
                {
                    break;
                }
                default:
                break;
            }
            ctx.Send();
            //if( !m_player.GetDayZPlayerInventory().HasLockedHands() )
            //  m_player.GetDayZPlayerInventory().LockHands();
        }
    }
References AT_WPN_ATTACH_MAGAZINE, AT_WPN_DETACH_MAGAZINE, AT_WPN_EJECT_BULLET, AT_WPN_LOAD_BULLET, AT_WPN_LOAD_MULTI_BULLETS_START, AT_WPN_SWAP_MAGAZINE, AT_WPN_UNJAM, GetGame(), INPUT_UDT_WEAPON_ACTION, m_LastAcknowledgmentID, m_PendingInventoryLocation, m_PendingTargetMagazine, m_PendingWeaponAction, m_PendingWeaponActionAcknowledgmentID, ScriptInputUserData::Send(), Serializer::Write(), and InventoryLocation::WriteToContext().
Referenced by StartAction().
Unjam()
bool WeaponManager::Unjam (ActionBase control_action = NULL) inline private
Definition at line 384 of file weaponmanager.c.
    {
        return StartAction(AT_WPN_UNJAM, NULL, NULL, control_action);
    }
References AT_WPN_UNJAM, and StartAction().
Referenced by ManBase::ReloadWeapon().
Update()
void WeaponManager::Update (float deltaT) inline private
Definition at line 833 of file weaponmanager.c.
    {
        if (m_WeaponInHand != m_player.GetItemInHands())
        {
            if( m_WeaponInHand )
            {
                m_SuitableMagazines.Clear();
                OnWeaponActionEnd();
            }
            m_WeaponInHand = Weapon_Base.Cast(m_player.GetItemInHands());
            if ( m_WeaponInHand )
            {
                m_MagazineInHand = null;
                //SET new magazine
                SetSutableMagazines();
                m_WeaponInHand.SetSyncJammingChance(0);
            }
            m_AnimationRefreshCooldown = 0;
        }
        if (m_WeaponInHand)
        {
            if(m_AnimationRefreshCooldown)
            {
                m_AnimationRefreshCooldown--;
                if( m_AnimationRefreshCooldown == 0)
                {
                    RefreshAnimationState();
                }
            }
            if (!GetGame().IsMultiplayer())
            {
                m_WeaponInHand.SetSyncJammingChance(m_WeaponInHand.GetChanceToJam());
            }
            else
            {
                if ( m_NewJamChance >= 0)
                {
                    m_WeaponInHand.SetSyncJammingChance(m_NewJamChance);
                    m_NewJamChance = -1;
                    m_WaitToSyncJamChance = false;
                }
                if (GetGame().IsServer() && !m_WaitToSyncJamChance )
                {
                    float actual_chance_to_jam;
                    actual_chance_to_jam = m_WeaponInHand.GetChanceToJam();
                    if ( Math.AbsFloat(m_WeaponInHand.GetSyncChanceToJam() - m_WeaponInHand.GetChanceToJam()) > 0.001 )
                    {
                        DayZPlayerSyncJunctures.SendWeaponJamChance(m_player, m_WeaponInHand.GetChanceToJam());
                        m_WaitToSyncJamChance = true;
                    }
                }
            }
            if(m_readyToStart)
            {
                StartPendingAction();
                m_readyToStart = false;
                return;
            }
            if( !m_InProgress || !m_IsEventSended )
                return;
            if(m_canEnd)
            {
                if(m_WeaponInHand.IsIdle())
                {
                    OnWeaponActionEnd();
                }
                else if(m_justStart)
                {
                    m_InIronSight = m_player.IsInIronsights();
                    m_InOptic = m_player.IsInOptics();
                    if(m_InIronSight || m_InOptic)
                    {
                        //'RequestResetADSSync' can be called here, if ADS reset is desired
                        m_player.ExitSights();
                    }
                    m_justStart = false;
                }
            }
            else
            {
                m_canEnd = true;
                m_justStart = true;
            }
        }
        else
        {
            if ( m_MagazineInHand != m_player.GetItemInHands() )
            {
                m_MagazineInHand = MagazineStorage.Cast(m_player.GetItemInHands());
                if ( m_MagazineInHand )
                {
                    SetSutableMagazines();
                }
            }
        }
    }
References Math::AbsFloat(), Weapon_Base::GetChanceToJam(), GetGame(), m_AnimationRefreshCooldown, m_canEnd, m_InIronSight, m_InOptic, m_InProgress, m_IsEventSended, m_justStart, m_MagazineInHand, m_NewJamChance, m_player, m_readyToStart, m_SuitableMagazines, m_WaitToSyncJamChance, m_WeaponInHand, OnWeaponActionEnd(), RefreshAnimationState(), DayZPlayerSyncJunctures::SendWeaponJamChance(), SetSutableMagazines(), and StartPendingAction().
WantContinue()
bool WeaponManager::WantContinue () inline private
Definition at line 1015 of file weaponmanager.c.
    {
        return m_WantContinue;
    }
References m_WantContinue.
Member Data Documentation
FORCE_EJECT_BULLET_TIMEOUT
protected const int WeaponManager::FORCE_EJECT_BULLET_TIMEOUT = 2000 private
Definition at line 28 of file weaponmanager.c.
Referenced by CanEjectBulletVerified().
m_AnimationRefreshCooldown
protected int WeaponManager::m_AnimationRefreshCooldown private
Definition at line 43 of file weaponmanager.c.
Referenced by DelayedRefreshAnimationState(), Update(), and WeaponManager().
m_canEnd
protected bool WeaponManager::m_canEnd private
Definition at line 15 of file weaponmanager.c.
Referenced by StartPendingAction(), Update(), and WeaponManager().
m_ControlAction
protected ActionBase WeaponManager::m_ControlAction private
Definition at line 25 of file weaponmanager.c.
Referenced by OnWeaponActionEnd(), StartAction(), and WeaponManager().
m_ForceEjectBulletTimestamp
protected int WeaponManager::m_ForceEjectBulletTimestamp private
Definition at line 26 of file weaponmanager.c.
Referenced by CanEjectBulletVerified(), EjectBulletVerified(), SetEjectBulletTryTimestamp(), and WeaponManager().
m_InIronSight
protected bool WeaponManager::m_InIronSight private
Definition at line 20 of file weaponmanager.c.
Referenced by Update().
m_InOptic
protected bool WeaponManager::m_InOptic private
Definition at line 21 of file weaponmanager.c.
Referenced by Update().
m_InProgress
protected bool WeaponManager::m_InProgress private
Definition at line 17 of file weaponmanager.c.
Referenced by IsRunning(), LoadMultiBulletStop(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), SetRunning(), StartAction(), StartPendingAction(), Update(), and WeaponManager().
m_IsEventSended
protected bool WeaponManager::m_IsEventSended private
Definition at line 18 of file weaponmanager.c.
Referenced by OnInputUserDataProcess(), StartAction(), StartPendingAction(), Update(), and WeaponManager().
m_justStart
protected bool WeaponManager::m_justStart private
Definition at line 16 of file weaponmanager.c.
Referenced by Update().
m_LastAcknowledgmentID
protected int WeaponManager::m_LastAcknowledgmentID private
Definition at line 7 of file weaponmanager.c.
Referenced by Synchronize(), and WeaponManager().
m_MagazineInHand
protected MagazineStorage WeaponManager::m_MagazineInHand private
Definition at line 24 of file weaponmanager.c.
Referenced by SetSutableMagazines(), Update(), and WeaponManager().
m_MagazinePilesInInventory
protected ref array<Magazine> WeaponManager::m_MagazinePilesInInventory private
Definition at line 33 of file weaponmanager.c.
Referenced by OnMagazineInventoryEnter(), OnMagazineInventoryExit(), SetSutableMagazines(), SortMagazineAfterLoad(), and WeaponManager().
m_MagazineStorageInInventory
protected ref array<MagazineStorage> WeaponManager::m_MagazineStorageInInventory private
Definition at line 34 of file weaponmanager.c.
Referenced by OnMagazineInventoryEnter(), OnMagazineInventoryExit(), SetSutableMagazines(), SortMagazineAfterLoad(), and WeaponManager().
m_NewJamChance
protected float WeaponManager::m_NewJamChance private
Definition at line 39 of file weaponmanager.c.
Referenced by OnSyncJuncture(), Update(), and WeaponManager().
m_PendingInventoryLocation
protected ref InventoryLocation WeaponManager::m_PendingInventoryLocation private
Definition at line 13 of file weaponmanager.c.
Referenced by InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingTargetMagazine
protected Magazine WeaponManager::m_PendingTargetMagazine private
Definition at line 10 of file weaponmanager.c.
Referenced by InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingWeaponAction
protected int WeaponManager::m_PendingWeaponAction private
Definition at line 12 of file weaponmanager.c.
Referenced by OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), StartPendingAction(), Synchronize(), and WeaponManager().
m_PendingWeaponActionAcknowledgmentID
protected int WeaponManager::m_PendingWeaponActionAcknowledgmentID private
Definition at line 9 of file weaponmanager.c.
Referenced by OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), Synchronize(), and WeaponManager().
m_player
protected PlayerBase WeaponManager::m_player private
Definition at line 5 of file weaponmanager.c.
Referenced by CanAttachMagazine(), CanDetachMagazine(), CanEjectBullet(), CanFire(), CanLoadBullet(), CanSwapMagazine(), CanUnjam(), Fire(), InventoryReservation(), OnInputUserDataProcess(), OnSyncJuncture(), OnWeaponActionEnd(), PrepareInventoryLocationForMagazineSwap(), RefreshAnimationState(), StartPendingAction(), Update(), and WeaponManager().
m_PreparedMagazine
protected Magazine WeaponManager::m_PreparedMagazine private
Definition at line 36 of file weaponmanager.c.
Referenced by SetSutableMagazines(), and WeaponManager().
m_readyToStart
protected bool WeaponManager::m_readyToStart private
Definition at line 22 of file weaponmanager.c.
Referenced by OnSyncJuncture(), OnWeaponActionEnd(), StartAction(), Update(), and WeaponManager().
m_SuitableMagazines
protected ref array<Magazine> WeaponManager::m_SuitableMagazines private
Definition at line 35 of file weaponmanager.c.
Referenced by GetNextPreparedMagazine(), GetPreparedMagazine(), OnMagazineInventoryExit(), SetSutableMagazines(), Update(), and WeaponManager().
m_TargetInventoryLocation
protected ref InventoryLocation WeaponManager::m_TargetInventoryLocation private
Definition at line 11 of file weaponmanager.c.
Referenced by InventoryReservation(), OnSyncJuncture(), and OnWeaponActionEnd().
m_WaitToSyncJamChance
protected bool WeaponManager::m_WaitToSyncJamChance private
Definition at line 40 of file weaponmanager.c.
Referenced by Update(), and WeaponManager().
m_WantContinue
protected bool WeaponManager::m_WantContinue private
Definition at line 19 of file weaponmanager.c.
Referenced by LoadMultiBulletStop(), OnWeaponActionEnd(), StartPendingAction(), WantContinue(), and WeaponManager().
m_WeaponInHand
protected Weapon_Base WeaponManager::m_WeaponInHand private
Definition at line 23 of file weaponmanager.c.
Referenced by CanEjectBulletVerified(), DelayedRefreshAnimationState(), EjectBulletVerified(), GetCurrentModeName(), InventoryReservation(), OnLiftWeapon(), RefreshAnimationState(), SetSutableMagazines(), StartPendingAction(), SwapMagazine(), Update(), and WeaponManager().
MAX_DROP_MAGAZINE_DISTANCE_SQ
const float WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ = 4 private
Definition at line 3 of file weaponmanager.c.
Referenced by WeaponStateBase::OnAbort(), OnAbort(), and WeaponStateBase::OnExit().