DayzKode: WidgetEventHandler Class Reference
WidgetEventHandler Class Reference
Private Member Functions
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
override bool OnClick (Widget w, int x, int y, int button)
override bool OnDoubleClick (Widget w, int x, int y, int button)
override bool OnDrag (Widget w, int x, int y)
override bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
override bool OnDrop (Widget w, int x, int y, Widget reciever)
override bool OnDropReceived (Widget w, int x, int y, Widget reciever)
override bool OnFocus (Widget w, int x, int y)
override bool OnFocusLost (Widget w, int x, int y)
override bool OnMouseButtonDown (Widget w, int x, int y, int button)
override bool OnMouseButtonUp (Widget w, int x, int y, int button)
override bool OnMouseEnter (Widget w, int x, int y)
override bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
override bool OnMouseWheel (Widget w, int x, int y, int wheel)
void RegisterOnChildAdd (Widget w, Managed eventHandler, string functionName)
void RegisterOnChildRemove (Widget w, Managed eventHandler, string functionName)
void RegisterOnClick (Widget w, Managed eventHandler, string functionName)
void RegisterOnDoubleClick (Widget w, Managed eventHandler, string functionName)
void RegisterOnDrag (Widget w, Managed eventHandler, string functionName)
void RegisterOnDraggingOver (Widget w, Managed eventHandler, string functionName)
void RegisterOnDrop (Widget w, Managed eventHandler, string functionName)
void RegisterOnDropReceived (Widget w, Managed eventHandler, string functionName)
void RegisterOnFocus (Widget w, Managed eventHandler, string functionName)
void RegisterOnFocusLost (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseButtonDown (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseButtonUp (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseEnter (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseLeave (Widget w, Managed eventHandler, string functionName)
void RegisterOnMouseWheel (Widget w, Managed eventHandler, string functionName)
void UnregisterWidget (Widget w)
void WidgetEventHandler ()
Static Private Member Functions
static WidgetEventHandler GetInstance ()
Private Attributes
protected ref map< Widget, ref Param > m_OnChildAdd
protected ref map< Widget, ref Param > m_OnChildRemove
protected ref map< Widget, ref Param > m_OnClick
protected ref map< Widget, ref Param > m_OnController
protected ref map< Widget, ref Param > m_OnDoubleClick
protected ref map< Widget, ref Param > m_OnDrag
protected ref map< Widget, ref Param > m_OnDraggingOver
protected ref map< Widget, ref Param > m_OnDrop
protected ref map< Widget, ref Param > m_OnDropReceived
protected ref map< Widget, ref Param > m_OnFocus
protected ref map< Widget, ref Param > m_OnFocusLost
protected ref map< Widget, ref Param > m_OnMouseButtonDownRegister
protected ref map< Widget, ref Param > m_OnMouseButtonLeave
protected ref map< Widget, ref Param > m_OnMouseButtonUpRegister
protected ref map< Widget, ref Param > m_OnMouseEnter
protected ref map< Widget, ref Param > m_OnMouseWheel
Static Private Attributes
private static ref WidgetEventHandler s_instance
Detailed Description
Definition at line 1 of file widgeteventhandler.c.
Constructor & Destructor Documentation
WidgetEventHandler()
void WidgetEventHandler::WidgetEventHandler () inline private
Definition at line 27 of file widgeteventhandler.c.
    {
        s_instance = this;
        m_OnMouseButtonDownRegister = new map<Widget, ref Param>;
        m_OnMouseButtonUpRegister = new map<Widget, ref Param>;
        m_OnMouseWheel = new map<Widget, ref Param>;
        m_OnDropReceived = new map<Widget, ref Param>;
        m_OnDrag = new map<Widget, ref Param>;
        m_OnDrop = new map<Widget, ref Param>;
        m_OnDraggingOver = new map<Widget, ref Param>;
        m_OnMouseEnter = new map<Widget, ref Param>;
        m_OnMouseButtonLeave = new map<Widget, ref Param>;
        m_OnClick = new map<Widget, ref Param>;
        m_OnDoubleClick = new map<Widget, ref Param>;
        m_OnFocus = new map<Widget, ref Param>;
        m_OnFocusLost = new map<Widget, ref Param>;
        m_OnController = new map<Widget, ref Param>;
        m_OnChildAdd = new map<Widget, ref Param>;
        m_OnChildRemove = new map<Widget, ref Param>;
    }
References m_OnChildAdd, m_OnChildRemove, m_OnClick, m_OnController, m_OnDoubleClick, m_OnDrag, m_OnDraggingOver, m_OnDrop, m_OnDropReceived, m_OnFocus, m_OnFocusLost, m_OnMouseButtonDownRegister, m_OnMouseButtonLeave, m_OnMouseButtonUpRegister, m_OnMouseEnter, m_OnMouseWheel, and s_instance.
Member Function Documentation
GetInstance()
static WidgetEventHandler WidgetEventHandler::GetInstance () inline static private
Definition at line 22 of file widgeteventhandler.c.
    {
        return s_instance;
    }
References s_instance.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), CargoContainerRow::CargoContainerRow(), ClosableHeader::ClosableHeader(), ClosableContainer::ContainerWithCargo(), ClosableContainer::ContainerWithCargoAndAttachments(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), PlayerPreview::PlayerPreview(), VicinitySlotsContainer::RecomputeNumberOfContainers(), AttachmentCategoriesContainer::SetEntity(), SlotsIcon::SlotsIcon(), VicinityContainer::VicinityContainer(), VicinitySlotsContainer::VicinitySlotsContainer(), and ZombieContainer::ZombieContainer().
OnChildAdd()
override bool WidgetEventHandler::OnChildAdd (Widget w, Widget child) inline private
Definition at line 426 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnChildAdd.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnChildAdd.Remove( w );
        }
        Param param2 = new Param2<Widget, Widget>( w, child );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), and m_OnChildAdd.
OnChildRemove()
override bool WidgetEventHandler::OnChildRemove (Widget w, Widget child) inline private
Definition at line 445 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnChildRemove.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnChildRemove.Remove( w );
        }
        Param param2 = new Param2<Widget, Widget>( w, child );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), and m_OnChildRemove.
OnClick()
override bool WidgetEventHandler::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 174 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnClick.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnClick.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, int>( w, x, y, button );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnClick, x, and y.
OnDoubleClick()
override bool WidgetEventHandler::OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 193 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnDoubleClick.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnDoubleClick.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, int>( w, x, y, button );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDoubleClick, x, and y.
OnDrag()
override bool WidgetEventHandler::OnDrag (Widget w, int x, int y) inline private
Definition at line 288 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnDrag.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnDrag.Remove( w );
        }
        Param param2 = new Param3<Widget, int, int>( w, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDrag, x, and y.
OnDraggingOver()
override bool WidgetEventHandler::OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 326 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnDraggingOver.Get( reciever ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnDraggingOver.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, Widget>( w, x, y, reciever );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDraggingOver, x, and y.
OnDrop()
override bool WidgetEventHandler::OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 307 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnDrop.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnDrop.Remove( w );
        }
        Param param2 = new Param3<Widget, int, int>( w, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDrop, x, and y.
OnDropReceived()
override bool WidgetEventHandler::OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 345 of file widgeteventhandler.c.
    {
        if( w.GetName() == "GridItem" )
        {
            return false;
        }
        Param p = m_OnDropReceived.Get( reciever );
        Param2<Managed, string> param = Param2<Managed, string>.Cast( p );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnDropReceived.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, Widget>( w, x, y, reciever );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnDropReceived, x, and y.
OnFocus()
override bool WidgetEventHandler::OnFocus (Widget w, int x, int y) inline private
Definition at line 369 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnFocus.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnFocus.Remove( w );
        }
        Param param2 = new Param3<Widget, int, int>( w, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnFocus, x, and y.
OnFocusLost()
override bool WidgetEventHandler::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 388 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnFocusLost.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnFocusLost.Remove( w );
        }
        Param param2 = new Param3<Widget, int, int>( w, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnFocusLost, x, and y.
OnMouseButtonDown()
override bool WidgetEventHandler::OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 250 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnMouseButtonDownRegister.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnMouseButtonDownRegister.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, int>( w, x, y, button );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonDownRegister, x, and y.
OnMouseButtonUp()
override bool WidgetEventHandler::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 269 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnMouseButtonUpRegister.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnMouseButtonUpRegister.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, int>( w, x, y, button );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonUpRegister, x, and y.
OnMouseEnter()
override bool WidgetEventHandler::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 231 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnMouseEnter.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnMouseEnter.Remove( w );
        }
        Param param2 = new Param3<Widget, int, int>( w, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseEnter, x, and y.
OnMouseLeave()
override bool WidgetEventHandler::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 212 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnMouseButtonLeave.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnMouseButtonLeave.Remove( w );
        }
        Param param2 = new Param4<Widget, Widget, int, int>( w, enterW, x, y );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseButtonLeave, x, and y.
OnMouseWheel()
override bool WidgetEventHandler::OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 407 of file widgeteventhandler.c.
    {
        Param2<Managed, string> param = Param2<Managed, string>.Cast( m_OnMouseWheel.Get( w ) );
        if( param == NULL )
        {
            return false;
        }
        if( !param.param1 )
        {
            m_OnMouseWheel.Remove( w );
        }
        Param param2 = new Param4<Widget, int, int, int>( w, x, y, wheel );
        GetGame().GameScript.CallFunctionParams( param.param1, param.param2, NULL, param2 );
        return true;
    }
References ScriptModule::CallFunctionParams(), CGame::GameScript, GetGame(), m_OnMouseWheel, x, and y.
RegisterOnChildAdd()
void WidgetEventHandler::RegisterOnChildAdd (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 160 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnChildAdd.Insert( w, param );
    }
References m_OnChildAdd.
Referenced by LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetEntity(), VicinityContainer::VicinityContainer(), and ZombieContainer::ZombieContainer().
RegisterOnChildRemove()
void WidgetEventHandler::RegisterOnChildRemove (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 167 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnChildRemove.Insert( w, param );
    }
References m_OnChildRemove.
Referenced by LeftArea::LeftArea(), PlayerContainer::PlayerContainer(), AttachmentCategoriesContainer::SetEntity(), VicinityContainer::VicinityContainer(), and ZombieContainer::ZombieContainer().
RegisterOnClick()
void WidgetEventHandler::RegisterOnClick (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 133 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnClick.Insert( w, param );
    }
References m_OnClick.
Referenced by ClosableHeader::ClosableHeader().
RegisterOnDoubleClick()
void WidgetEventHandler::RegisterOnDoubleClick (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 140 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnDoubleClick.Insert( w, param );
    }
References m_OnDoubleClick.
Referenced by Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnDrag()
void WidgetEventHandler::RegisterOnDrag (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 98 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnDrag.Insert( w, param );
    }
References m_OnDrag.
Referenced by ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnDraggingOver()
void WidgetEventHandler::RegisterOnDraggingOver (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 112 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnDraggingOver.Insert( w, param );
    }
References m_OnDraggingOver.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), CargoContainerRow::CargoContainerRow(), ClosableContainer::ContainerWithCargo(), ClosableContainer::ContainerWithCargoAndAttachments(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnDrop()
void WidgetEventHandler::RegisterOnDrop (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 105 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnDrop.Insert( w, param );
    }
References m_OnDrop.
Referenced by ClosableHeader::ClosableHeader(), AttachmentCategoriesRow::Init(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnDropReceived()
void WidgetEventHandler::RegisterOnDropReceived (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 91 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnDropReceived.Insert( w, param );
    }
References m_OnDropReceived.
Referenced by CargoContainerRow::CargoContainerRow(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), Inventory(), PlayerContainer::PlayerContainer(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnFocus()
void WidgetEventHandler::RegisterOnFocus (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 147 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnFocus.Insert( w, param );
    }
References m_OnFocus.
RegisterOnFocusLost()
void WidgetEventHandler::RegisterOnFocusLost (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 153 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnFocusLost.Insert( w, param );
    }
References m_OnFocusLost.
RegisterOnMouseButtonDown()
void WidgetEventHandler::RegisterOnMouseButtonDown (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 70 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnMouseButtonDownRegister.Insert( w, param );
    }
References m_OnMouseButtonDownRegister.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), Header::Header(), AttachmentCategoriesRow::Init(), Attachments::InitAttachmentGrid(), Icon::InitEx(), ZombieContainer::InitGhostSlots(), Icon::InitLock(), PlayerContainer::PlayerContainer(), PlayerPreview::PlayerPreview(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnMouseButtonUp()
void WidgetEventHandler::RegisterOnMouseButtonUp (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 77 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnMouseButtonUpRegister.Insert( w, param );
    }
References m_OnMouseButtonUpRegister.
Referenced by ZombieContainer::InitGhostSlots(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), VicinitySlotsContainer::RecomputeNumberOfContainers(), and VicinitySlotsContainer::VicinitySlotsContainer().
RegisterOnMouseEnter()
void WidgetEventHandler::RegisterOnMouseEnter (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 119 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnMouseEnter.Insert( w, param );
    }
References m_OnMouseEnter.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnMouseLeave()
void WidgetEventHandler::RegisterOnMouseLeave (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 126 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnMouseButtonLeave.Insert( w, param );
    }
References m_OnMouseButtonLeave.
Referenced by AttachmentCategoriesSlotsContainer::AttachmentCategoriesSlotsContainer(), ClosableHeader::ClosableHeader(), Icon::InitEx(), and SlotsIcon::SlotsIcon().
RegisterOnMouseWheel()
void WidgetEventHandler::RegisterOnMouseWheel (Widget w, Managed eventHandler, string functionName) inline private
Definition at line 84 of file widgeteventhandler.c.
    {
        w.SetHandler( this );
        Param param = new Param2<Managed, string>( eventHandler, functionName );
        m_OnMouseWheel.Insert( w, param );
    }
References m_OnMouseWheel.
Referenced by PlayerPreview::PlayerPreview().
UnregisterWidget()
void WidgetEventHandler::UnregisterWidget (Widget w) inline private
Definition at line 48 of file widgeteventhandler.c.
    {
        m_OnMouseButtonDownRegister.Remove( w );
        m_OnMouseButtonUpRegister.Remove( w );
        m_OnMouseWheel.Remove( w );
        m_OnDropReceived.Remove( w );
        m_OnDrag.Remove( w );
        m_OnDrop.Remove( w );
        m_OnDraggingOver.Remove( w );
        m_OnMouseEnter.Remove( w );
        m_OnMouseButtonLeave.Remove( w );
        m_OnClick.Remove( w );
        m_OnDoubleClick.Remove( w );
        m_OnDoubleClick.Remove( w );
        m_OnFocus.Remove( w );
        m_OnFocusLost.Remove( w );
        m_OnController.Remove( w );
        m_OnChildAdd.Remove( w );
        m_OnChildRemove.Remove( w );
        w.SetHandler( NULL );
    }
References m_OnChildAdd, m_OnChildRemove, m_OnClick, m_OnController, m_OnDoubleClick, m_OnDrag, m_OnDraggingOver, m_OnDrop, m_OnDropReceived, m_OnFocus, m_OnFocusLost, m_OnMouseButtonDownRegister, m_OnMouseButtonLeave, m_OnMouseButtonUpRegister, m_OnMouseEnter, and m_OnMouseWheel.
Member Data Documentation
m_OnChildAdd
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnChildAdd private
Definition at line 19 of file widgeteventhandler.c.
Referenced by OnChildAdd(), RegisterOnChildAdd(), UnregisterWidget(), and WidgetEventHandler().
m_OnChildRemove
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnChildRemove private
Definition at line 20 of file widgeteventhandler.c.
Referenced by OnChildRemove(), RegisterOnChildRemove(), UnregisterWidget(), and WidgetEventHandler().
m_OnClick
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnClick private
Definition at line 14 of file widgeteventhandler.c.
Referenced by OnClick(), RegisterOnClick(), UnregisterWidget(), and WidgetEventHandler().
m_OnController
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnController private
Definition at line 18 of file widgeteventhandler.c.
Referenced by UnregisterWidget(), and WidgetEventHandler().
m_OnDoubleClick
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnDoubleClick private
Definition at line 15 of file widgeteventhandler.c.
Referenced by OnDoubleClick(), RegisterOnDoubleClick(), UnregisterWidget(), and WidgetEventHandler().
m_OnDrag
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnDrag private
Definition at line 9 of file widgeteventhandler.c.
Referenced by OnDrag(), RegisterOnDrag(), UnregisterWidget(), and WidgetEventHandler().
m_OnDraggingOver
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnDraggingOver private
Definition at line 11 of file widgeteventhandler.c.
Referenced by OnDraggingOver(), RegisterOnDraggingOver(), UnregisterWidget(), and WidgetEventHandler().
m_OnDrop
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnDrop private
Definition at line 10 of file widgeteventhandler.c.
Referenced by OnDrop(), RegisterOnDrop(), UnregisterWidget(), and WidgetEventHandler().
m_OnDropReceived
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnDropReceived private
Definition at line 8 of file widgeteventhandler.c.
Referenced by OnDropReceived(), RegisterOnDropReceived(), UnregisterWidget(), and WidgetEventHandler().
m_OnFocus
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnFocus private
Definition at line 16 of file widgeteventhandler.c.
Referenced by OnFocus(), RegisterOnFocus(), UnregisterWidget(), and WidgetEventHandler().
m_OnFocusLost
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnFocusLost private
Definition at line 17 of file widgeteventhandler.c.
Referenced by OnFocusLost(), RegisterOnFocusLost(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonDownRegister
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnMouseButtonDownRegister private
Definition at line 5 of file widgeteventhandler.c.
Referenced by OnMouseButtonDown(), RegisterOnMouseButtonDown(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonLeave
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnMouseButtonLeave private
Definition at line 13 of file widgeteventhandler.c.
Referenced by OnMouseLeave(), RegisterOnMouseLeave(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseButtonUpRegister
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnMouseButtonUpRegister private
Definition at line 6 of file widgeteventhandler.c.
Referenced by OnMouseButtonUp(), RegisterOnMouseButtonUp(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseEnter
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnMouseEnter private
Definition at line 12 of file widgeteventhandler.c.
Referenced by OnMouseEnter(), RegisterOnMouseEnter(), UnregisterWidget(), and WidgetEventHandler().
m_OnMouseWheel
protected ref map<Widget, ref Param> WidgetEventHandler::m_OnMouseWheel private
Definition at line 7 of file widgeteventhandler.c.
Referenced by OnMouseWheel(), RegisterOnMouseWheel(), UnregisterWidget(), and WidgetEventHandler().
s_instance
private static ref WidgetEventHandler WidgetEventHandler::s_instance static private
Definition at line 3 of file widgeteventhandler.c.
Referenced by GetInstance(), and WidgetEventHandler().