DayzKode: WeatherPhenomenon Class Reference
WeatherPhenomenon Class Reference
Private Member Functions
proto native float GetActual ()
Returns actual value of phenomenon in range <0, 1>.
proto native float GetForecast ()
Returns a forecast value the phenomenon is heading towards.
proto void GetForecastChangeLimits (out float fcMin, out float fcMax)
Reads limits of change when forecast is computed.
proto void GetForecastTimeLimits (out float ftMin, out float ftMax)
Reads time range in which next forecast can be computed.
proto void GetLimits (out float fnMin, out float fnMax)
Reads limits of this phenomenon.
proto native float GetNextChange ()
Reads the time in seconds when the next forecast will be computed.
proto native EWeatherPhenomenon GetType ()
Returns type of this phenomenon.
bool OnBeforeChange (float change, float time)
Is called every time the Phenomenon computes new forecast.
proto native void Set (float forecast, float time=0, float minDuration=0)
Sets the forecast.
proto native void SetForecastChangeLimits (float fcMin, float fcMax)
Sets limits of change when forecast is computed.
proto native void SetForecastTimeLimits (float ftMin, float ftMax)
Sets time range in which next forecast can be computed.
proto native void SetLimits (float fnMin, float fnMax)
Sets limits of this phenomenon.
proto native void SetNextChange (float time)
Sets the time in seconds when the next forecast will be computed.
private void WeatherPhenomenon ()
private void ~WeatherPhenomenon ()
Detailed Description
Weather phenomenon
Definition at line 22 of file weather.c.
Constructor & Destructor Documentation
WeatherPhenomenon()
private void WeatherPhenomenon::WeatherPhenomenon () inline private
Definition at line 24 of file weather.c.
{}
~WeatherPhenomenon()
private void WeatherPhenomenon::~WeatherPhenomenon () inline private
Definition at line 25 of file weather.c.
{}
Member Function Documentation
GetActual()
proto native float WeatherPhenomenon::GetActual () private
Returns actual value of phenomenon in range <0, 1>.
Referenced by ItemBase::CheckRainTick(), Environment::CollectAndSetEnvironmentData(), Cooling(), Heating(), ItemBase::Init(), OnBeforeChange(), UIPopupScript::OnOpen(), RainProcurementManager::RainProcurementCheck(), and UIPopupScript::ResetSliders().
GetForecast()
proto native float WeatherPhenomenon::GetForecast () private
Returns a forecast value the phenomenon is heading towards.
GetForecastChangeLimits()
proto void WeatherPhenomenon::GetForecastChangeLimits (out float fcMin, out float fcMax) private
Reads limits of change when forecast is computed.
Parameters
fcMin Forecast change minimum (in range <0, 1>).
fcMax Forecast change maximum (in range <0, 1>).
GetForecastTimeLimits()
proto void WeatherPhenomenon::GetForecastTimeLimits (out float ftMin, out float ftMax) private
Reads time range in which next forecast can be computed.
Parameters
ftMin Minimal number of seconds.
ftMax Maximal number of seconds.
GetLimits()
proto void WeatherPhenomenon::GetLimits (out float fnMin, out float fnMax) private
Reads limits of this phenomenon.
Parameters
fnMin Function minimum (in range <0, 1>).
fnMax Function maximum (in range <0, 1>).
GetNextChange()
proto native float WeatherPhenomenon::GetNextChange () private
Reads the time in seconds when the next forecast will be computed.
GetType()
proto native EWeatherPhenomenon WeatherPhenomenon::GetType () private
Returns type of this phenomenon.
Referenced by OnBeforeChange().
OnBeforeChange()
bool WeatherPhenomenon::OnBeforeChange (float change, float time) inline private
Is called every time the Phenomenon computes new forecast.
Note
Called on server only.
Parameters
change Computed change of forecast value.
time Seconds when the next forecast will be computed.
Returns
True when script modifies state of this phenomenon false otherwise.
Definition at line 118 of file weather.c.
    {
        // check if mission forces use of custom weather
        Weather weather = g_Game.GetWeather();
        if ( weather.GetMissionWeather() )
            return false;
        // check for active worlddata with custom onbeforechange behaviour
        Mission currentMission = g_Game.GetMission();
        if ( currentMission )
        {
            WorldData worldData = currentMission.GetWorldData();
            if ( worldData )
            {
                return worldData.WeatherOnBeforeChange( GetType(), GetActual(), change, time );
            }
        }
        return false;
    }
References g_Game, GetActual(), Weather::GetMissionWeather(), GetType(), Mission::GetWorldData(), and WorldData::WeatherOnBeforeChange().
Set()
proto native void WeatherPhenomenon::Set (float forecast, float time = 0, float minDuration = 0) private
Sets the forecast.
Parameters
forecast Desired forecast value that should be met in given time.
time A time of the next change (how long it takes in seconds to interpolate to given value).
minDuration A minimal time in seconds the change will last.
Referenced by DayZIntroScene::DayZIntroScene(), UIPopupScript::OnChange(), UIPopupScript::OnClick(), UIPopupScript::OnClose(), SceneData::SetInitFog(), SceneData::SetInitOvercast(), and SceneData::SetInitRain().
SetForecastChangeLimits()
proto native void WeatherPhenomenon::SetForecastChangeLimits (float fcMin, float fcMax) private
Sets limits of change when forecast is computed.
These limits govern how much the forecast value can change when it is computed by weather controller.
Default values are: fcMin = 0 fcMax = 1
Parameters
fcMin Forecast change minimum (in range <0, 1>).
fcMax Forecast change maximum (in range <0, 1>).
SetForecastTimeLimits()
proto native void WeatherPhenomenon::SetForecastTimeLimits (float ftMin, float ftMax) private
Sets time range in which next forecast can be computed.
Default values are: ftMin = 300 (5 minutes) ftMax = 3600 (1 hour)
Parameters
ftMin Minimal number of seconds.
ftMax Maximal number of seconds.
SetLimits()
proto native void WeatherPhenomenon::SetLimits (float fnMin, float fnMax) private
Sets limits of this phenomenon.
Actual value of this phenomenon will be always held in range <fnMin, fnMax>.
Default values are: fnMin = 0 fnMax = 1
Parameters
fnMin Function minimum (in range <0, 1>).
fnMax Function maximum (in range <0, 1>).
Referenced by DayZIntroScene::DayZIntroScene().
SetNextChange()
proto native void WeatherPhenomenon::SetNextChange (float time) private
Sets the time in seconds when the next forecast will be computed.