DayzKode: StaticTransmitter Class Reference
StaticTransmitter Class Reference
Private Member Functions
override bool DisableVicinityIcon ()
override bool IsStaticTransmitter ()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnSwitchOn ()
override void OnWorkStart ()
override void OnWorkStop ()
override void SetActions ()
void SetNextFrequency (PlayerBase player=NULL)
Detailed Description
Definition at line 1 of file land_radio_panelbig.c.
Member Function Documentation
DisableVicinityIcon()
override bool StaticTransmitter::DisableVicinityIcon () inline private
Definition at line 3 of file land_radio_panelbig.c.
    {
        return true;
    }
IsStaticTransmitter()
override bool StaticTransmitter::IsStaticTransmitter () inline private
Definition at line 36 of file land_radio_panelbig.c.
    {
        return true;
    }
OnStoreLoad()
override bool StaticTransmitter::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 17 of file land_radio_panelbig.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Panel Radio data ---
        //load and set tuned frequency
        int tuned_frequency_idx;
        if ( !ctx.Read( tuned_frequency_idx ) )
        {
            tuned_frequency_idx = 0;        //set default
        }
        SetFrequencyByIndex( tuned_frequency_idx );
        //---
        return true;
    }
References Serializer::Read().
OnStoreSave()
override void StaticTransmitter::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 9 of file land_radio_panelbig.c.
    {
        super.OnStoreSave( ctx );
        //store tuned frequency
        ctx.Write( GetTunedFrequencyIndex() );
    }
References Serializer::Write().
OnSwitchOn()
override void StaticTransmitter::OnSwitchOn () inline private
Definition at line 54 of file land_radio_panelbig.c.
    {
        if ( !GetCompEM().CanWork() )
        {
            GetCompEM().SwitchOff();
        }
    }
OnWorkStart()
override void StaticTransmitter::OnWorkStart () inline private
Definition at line 62 of file land_radio_panelbig.c.
    {
        //turn on broadcasting/receiving
        EnableBroadcast ( true );
        EnableReceive ( true );
        SwitchOn ( true );
    }
OnWorkStop()
override void StaticTransmitter::OnWorkStop () inline private
Definition at line 70 of file land_radio_panelbig.c.
    {
        //auto switch off (EM)
        GetCompEM().SwitchOff();
        //turn off broadcasting/receiving
        EnableBroadcast ( false );
        EnableReceive ( false );
        SwitchOn ( false );
    }
SetActions()
override void StaticTransmitter::SetActions () inline private
Definition at line 81 of file land_radio_panelbig.c.
    {
        super.SetActions();
        AddAction(ActionTuneFrequencyOnGround);
    }
References AddAction().
SetNextFrequency()
void StaticTransmitter::SetNextFrequency (PlayerBase player = NULL) inline private
Definition at line 41 of file land_radio_panelbig.c.
    {
        SetNextChannel();
        /*
        if ( player )
        {
            DisplayRadioInfo( GetTunedFrequency().ToString(), player );
        }
        */
    }