DayzKode: Potato Class Reference
Potato Class Reference
Private Member Functions
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool CanDecay ()
override void EEOnCECreate ()
override bool IsFruit ()
override void SetActions ()
Detailed Description
Definition at line 1 of file potato.c.
Member Function Documentation
CanBeCooked()
override bool Potato::CanBeCooked () inline private
Definition at line 3 of file potato.c.
    {
        return true;
    }
CanBeCookedOnStick()
override bool Potato::CanBeCookedOnStick () inline private
Definition at line 8 of file potato.c.
    {
        return true;
    }
CanDecay()
override bool Potato::CanDecay () inline private
Definition at line 18 of file potato.c.
    {
        return true;
    }
EEOnCECreate()
override void Potato::EEOnCECreate () inline private
Definition at line 33 of file potato.c.
    {
        int rand = Math.RandomInt(0,10);
        if ( rand > 6 )
        {
            ChangeFoodStage( FoodStageType.ROTTEN );
            SetHealth( "", "", GetMaxHealth()*0.1 );
        }
        else if ( rand > 2 )
        {
            ChangeFoodStage( FoodStageType.DRIED );
            SetHealth( "", "", GetMaxHealth()*0.4 );
        }
    }
References ChangeFoodStage(), GetMaxHealth(), Math::RandomInt(), and SetHealth().
IsFruit()
override bool Potato::IsFruit () inline private
Definition at line 13 of file potato.c.
    {
        return true;
    }
SetActions()
override void Potato::SetActions () inline private
Definition at line 23 of file potato.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEatFruit);
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
    }
References AddAction().