DayzKode: ActionEmptyMagazine Class Reference
ActionEmptyMagazine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionEmptyMagazine ()
bool CanEmpty (ItemBase item)
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool HasTarget ()
override void OnExecuteServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
Detailed Description
Definition at line 14 of file actionemptymagazine.c.
Constructor & Destructor Documentation
ActionEmptyMagazine()
void ActionEmptyMagazine::ActionEmptyMagazine () inline private
Definition at line 16 of file actionemptymagazine.c.
    {
        m_CallbackClass = ActionEmptyMagazineCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_EMPTYMAG;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_EMPTYMAG;
        m_Text = "#empty_magazine";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionEmptyMagazine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 63 of file actionemptymagazine.c.
    {
        Magazine itm;
        return CanEmpty(item);
    }
References CanEmpty().
ActionConditionContinue()
override bool ActionEmptyMagazine::ActionConditionContinue (ActionData action_data) inline private
Definition at line 58 of file actionemptymagazine.c.
    {
        return CanEmpty(action_data.m_MainItem);
    }
References CanEmpty(), and ActionData::m_MainItem.
CanEmpty()
bool ActionEmptyMagazine::CanEmpty (ItemBase item) inline private
Definition at line 52 of file actionemptymagazine.c.
    {
        Magazine mag;
        return ( item && Class.CastTo(mag, item) && mag.GetAmmoCount() > 0 );
    }
References Class::CastTo().
Referenced by ActionCondition(), and ActionConditionContinue().
CreateActionData()
override ActionData ActionEmptyMagazine::CreateActionData () inline private
Definition at line 35 of file actionemptymagazine.c.
    {
        EmptyMagazineActionData action_data = new EmptyMagazineActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionEmptyMagazine::CreateConditionComponents () inline private
Definition at line 41 of file actionemptymagazine.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionEmptyMagazine::HasProneException () inline private
Definition at line 47 of file actionemptymagazine.c.
    {
        return true;
    }
HasTarget()
override bool ActionEmptyMagazine::HasTarget () inline private
Definition at line 69 of file actionemptymagazine.c.
    {
        return false;
    }
OnExecuteServer()
override void ActionEmptyMagazine::OnExecuteServer (ActionData action_data) inline private
Definition at line 74 of file actionemptymagazine.c.
    {
        EmptyMagazineActionData emActionData = EmptyMagazineActionData.Cast(action_data);
        Magazine mag;
        if (!Class.CastTo(mag, action_data.m_MainItem))
            return;
        //float dmg;
        //string bulletType;
        /*int ammoCount = mag.GetAmmoCount();
        if(GetAmmoCount() > 0)
        {
            mag.Get
            mag.SetAmmoCount( ammoCount - 1 );
            array< Magazine > piles;
            if( !callback.m_magazinePile )
            {
                piles = MiscGameplayFunctions.CreateMagazinePilesFromBullet(bulletType, action_data.m_Player.GetPosition(),1,dmg);
                if( piles.Count() > 0 )
                    callback.m_magazinePile = piles.Get(0);
            }
            else
            {
                if( callback.m_magazinePile.GetAmmoMax() > callback.m_magazinePile.GetAmmoCount() && (vector.Distance(action_data.m_Player.GetPosition(), callback.m_magazinePile.GetPosition()) < MAX_GROUND_PILE_DISTANCE ) )
                {
                    callback.m_magazinePile.StoreCartridge(dmg, bulletType);
                }
                else
                {
                    piles = MiscGameplayFunctions.CreateMagazinePilesFromBullet(bulletType, action_data.m_Player.GetPosition(),1,dmg);
                    if( piles.Count() > 0 )
                        callback.m_magazinePile = piles.Get(0);
                }
            }
        }   */
        //----Uncomment after AcquireCartridge will work
        float dmg;
        string ammoType;
        if ( !mag.ServerAcquireCartridge(dmg,ammoType) )
            return;
        mag.ApplyManipulationDamage();
        string magazineTypeName;
        GetGame().ConfigGetText( "CfgAmmo " + ammoType + " spawnPileType" , magazineTypeName);
        if ( !DayZPlayerUtils.HandleStoreCartridge(action_data.m_Player, NULL, -1, dmg, ammoType, magazineTypeName, false) )
        {
            array< Magazine > piles;
            if ( !emActionData.m_magazinePile )
            {
                piles = MiscGameplayFunctions.CreateMagazinePilesFromBullet(ammoType,action_data.m_Player.GetPosition(),1,dmg);
                if ( piles.Count() > 0 )
                    emActionData.m_magazinePile = piles.Get(0);
            }
            else
            {
                if ( emActionData.m_magazinePile.GetAmmoMax() > emActionData.m_magazinePile.GetAmmoCount() && (vector.DistanceSq(action_data.m_Player.GetPosition(), emActionData.m_magazinePile.GetPosition()) < (UAMaxDistances.DEFAULT * UAMaxDistances.DEFAULT) ) )
                {
                    emActionData.m_magazinePile.ServerStoreCartridge(dmg,ammoType);
                }
                else
                {
                    piles = MiscGameplayFunctions.CreateMagazinePilesFromBullet(ammoType, action_data.m_Player.GetPosition(), 1, dmg);
                    if ( piles.Count() > 0 )
                        emActionData.m_magazinePile = piles.Get(0);
                }
            }
            //emActionData.m_magazinePile.SetSynchDirty();
        }
        //mag.SetSynchDirty();
    }
References Class::CastTo(), CGame::ConfigGetText(), UAMaxDistances::DEFAULT, vector::DistanceSq(), GetGame(), DayZPlayerUtils::HandleStoreCartridge(), EmptyMagazineActionData::m_magazinePile, ActionData::m_MainItem, and ActionData::m_Player.
SetupAction()
override bool ActionEmptyMagazine::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 24 of file actionemptymagazine.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data))
        {
            EmptyMagazineActionData emActionData = EmptyMagazineActionData.Cast(action_data);
            emActionData.m_magazinePile = NULL;
            return true;
        }
        return false;
    }
References EmptyMagazineActionData::m_magazinePile.