DayzKode: SoundObjectBuilder Class Reference
SoundObjectBuilder Class Reference
Private Member Functions
SoundObject BuildSoundObject ()
proto native void Initialize (SoundParams soundParams)
proto native void SetVariable (string name, float value)
void SoundObjectBuilder (SoundParams soundParams)
proto native void UpdateEnvSoundControllers (vector position)
Detailed Description
Definition at line 45 of file sound.c.
Constructor & Destructor Documentation
SoundObjectBuilder()
void SoundObjectBuilder::SoundObjectBuilder (SoundParams soundParams) private
Member Function Documentation
BuildSoundObject()
SoundObject SoundObjectBuilder::BuildSoundObject () inline private
Definition at line 49 of file sound.c.
    {
        return GetGame().GetSoundScene().BuildSoundObject(this);
    }
References GetGame(), and CGame::GetSoundScene().
Referenced by HandleView(), OnStepEvent(), EntityAI::PlayImpactSound(), MissionBase::PlayMusic(), ProcessAttachmentEvent(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), ProcessVoiceEvent(), ProcessWeaponEvent(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlayEx().
Initialize()
proto native void SoundObjectBuilder::Initialize (SoundParams soundParams) private
SetVariable()
proto native void SoundObjectBuilder::SetVariable (string name, float value) private
Referenced by DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), EntityAI::PlayImpactSound(), ProcessVoiceEvent(), ProcessWeaponEvent(), and SetVariablesLadderSoundObjectBuilder().
UpdateEnvSoundControllers()
proto native void SoundObjectBuilder::UpdateEnvSoundControllers (vector position) private
Referenced by EntityAI::PlayImpactSound(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), EffectSound::SoundLoadEx(), and EffectSound::SoundPlayEx().