DayzKode: BiosPackageService Class Reference
BiosPackageService Class Reference
Private Member Functions
proto native EBiosError CheckUpdateAsync ()
Async check if exist new update.
void OnCheckUpdate (BiosCheckUpdateResult checkUpdateResult, EBiosError error)
Callback function for CheckUpdateAsync()
void OnPromptUpdate (EBiosError error)
Callback function for PromptUpdateAsync()
void OnShowStore (EBiosError error)
Callback function for ShowStoreAsync()
proto native EBiosError PromptUpdateAsync ()
Prompt user to accept update with system GUI.
proto native EBiosError ShowStoreAsync ()
Show store for current title (system GUI). Only on Xbox.
Detailed Description
Definition at line 12 of file biospackageservice.c.
Member Function Documentation
CheckUpdateAsync()
proto native EBiosError BiosPackageService::CheckUpdateAsync () private
Async check if exist new update.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::CheckUpdate().
OnCheckUpdate()
void BiosPackageService::OnCheckUpdate (BiosCheckUpdateResult checkUpdateResult, EBiosError error) inline private
Callback function for CheckUpdateAsync()
Parameters
checkUpdateResult contain information about availability of new update and if it is mandatory.
error indicating success or fail of the async operation.
Definition at line 39 of file biospackageservice.c.
    {
        if ( !error && ( checkUpdateResult.m_IsUpdate || checkUpdateResult.m_IsMandatory ) )
        {
            OnlineServices.PromptUpdate();
        }
    }
References BiosCheckUpdateResult::m_IsMandatory, BiosCheckUpdateResult::m_IsUpdate, and OnlineServices::PromptUpdate().
OnPromptUpdate()
void BiosPackageService::OnPromptUpdate (EBiosError error) inline private
Callback function for PromptUpdateAsync()
Show system UI with update. On Xbox, game suspend after accept update.
Parameters
error indicating success or fail of the async operation.
Definition at line 55 of file biospackageservice.c.
    {
        OnlineServices.ErrorCaught( error );
    }
References OnlineServices::ErrorCaught().
OnShowStore()
void BiosPackageService::OnShowStore (EBiosError error) inline private
Callback function for ShowStoreAsync()
Parameters
error indicating success or fail of the async operation.
Definition at line 65 of file biospackageservice.c.
    {
        OnlineServices.ErrorCaught( error );
    }
References OnlineServices::ErrorCaught().
PromptUpdateAsync()
proto native EBiosError BiosPackageService::PromptUpdateAsync () private
Prompt user to accept update with system GUI.
Returns
EBiosError indicating if the async operation is pending.
Referenced by OnlineServices::PromptUpdate().
ShowStoreAsync()
proto native EBiosError BiosPackageService::ShowStoreAsync () private
Show store for current title (system GUI). Only on Xbox.
Returns
EBiosError indicating if the async operation is pending.