DayzKode: WeaponDebug Class Reference
WeaponDebug Class Reference
Private Member Functions
void AddPosToCyclicBuffer (vector pos)
void CycleDebugMode ()
void DisplayGeneralInfo ()
void DisplayTargetInfo ()
void DrawBarrelMemoryPoints (vector begin_point, vector end_point)
void DrawEyePoint (Weapon weapon)
void DrawLineOfFire (vector begin_point, vector end_point)
void DrawLineOfFireCameraHybrid (vector usti_hlavne_position, vector camera_dir, vector camera_pos, vector konec_hlavne_position)
void DrawLineOfFireMuzzleToHit (vector begin_point, vector camera_dir, vector camera_pos)
vector GetEyePointPosition (Weapon weapon)
Weapon GetWeaponInHands ()
void OnCommandHandlerUpdate ()
void OnKeyDown (KeyCode key)
void OnPostFrameUpdate ()
void OrderTrailArray ()
void RemoveAllShapes (bool is_exit=false)
void WeaponDebug ()
void ~WeaponDebug ()
Private Attributes
const int BUFFER_SIZE = 1000
const float CAMERA_BULLET_ORIGIN_OFFSET = 1
const float CAMERA_TRACE_MIN_DISTANCE_TOLERANCE = 0.3
const float COLLISIONS_DISTANCE_TOLERANCE = 0.01
vector m_AimTrailCyclic [BUFFER_SIZE]
vector m_AimTrailOrdered [BUFFER_SIZE]
int m_BufferIndex
eDebugMode m_CurrentMode
ref map< int, string > m_DebugModesNames = new map<int, string>
Shape m_HitShape
Shape m_HitShape2
Shape m_HitShape3
Shape m_HitShape4
bool m_IsDrawKeyHeldDown
bool m_IsFireKeyPressed
bool m_IsLMBPressed
bool m_IsToggleKeyPressed
Shape m_PermanentLine1
Shape m_PermanentLine2
Shape m_PermanentShape1
Shape m_PermanentShape2
Shape m_Shape_konec
Shape m_Shape_usti
Shape m_ShapeEye
Shape m_ShapeFireDirCamera
Shape m_ShapeFireDirection1
Shape m_ShapeFireDirection2
Shape m_ShapeTrailLines
float m_TargetDistance
Weapon m_WeaponInHands
const float MAX_MUZZLE_DISTANCE_TOLERANCE = 20
Detailed Description
Definition at line 11 of file weapondebug.c.
Constructor & Destructor Documentation
WeaponDebug()
void WeaponDebug::WeaponDebug () inline private
Definition at line 61 of file weapondebug.c.
    {
        m_DebugModesNames.Insert(eDebugMode.NORMAL, "Mode "+eDebugMode.NORMAL.ToString()+": shoot along the weapon barrel");
        m_DebugModesNames.Insert(eDebugMode.MUZZLE_FIRE,"Mode "+eDebugMode.MUZZLE_FIRE.ToString()+": shoot from muzzle end to camera trace hit point");
        m_DebugModesNames.Insert(eDebugMode.CAMERA_MUZZLE_HYBRID, "Mode "+eDebugMode.CAMERA_MUZZLE_HYBRID.ToString()+": shoot either from camera lens or from muzzle \n depending on the situation");
    }
References m_DebugModesNames.
~WeaponDebug()
void WeaponDebug::~WeaponDebug () inline private
Definition at line 68 of file weapondebug.c.
    {
        RemoveAllShapes(true);
    }
References RemoveAllShapes().
Member Function Documentation
AddPosToCyclicBuffer()
void WeaponDebug::AddPosToCyclicBuffer (vector pos) inline private
Definition at line 241 of file weapondebug.c.
    {
        m_AimTrailCyclic[m_BufferIndex] = pos;
        m_BufferIndex++;
        if (m_BufferIndex == BUFFER_SIZE)
        {
            m_BufferIndex = 0;
        }
    }
References BUFFER_SIZE, m_AimTrailCyclic, and m_BufferIndex.
Referenced by OnPostFrameUpdate().
CycleDebugMode()
void WeaponDebug::CycleDebugMode () inline private
Definition at line 146 of file weapondebug.c.
    {
        m_CurrentMode++;
        if ( m_CurrentMode == eDebugMode.COUNT )
        {
            m_CurrentMode = 0;
        }
    }
References m_CurrentMode.
Referenced by OnCommandHandlerUpdate().
DisplayGeneralInfo()
void WeaponDebug::DisplayGeneralInfo () inline private
Definition at line 285 of file weapondebug.c.
    {
        DbgUI.Begin("sway weight", 50, 50);
        DayZPlayerImplement player = DayZPlayerImplement.Cast(GetGame().GetPlayer());
        float sway_weight = player.GetAimingModel().GetSwayWeight();
        DbgUI.Text("value: " + sway_weight.ToString());
        DbgUI.Text("Hold LWIN to draw debug line");
        DbgUI.Text("Press X to simulate fire");
        DbgUI.Text("Press Z to cycle debug modes");
        DbgUI.Text("Debug " +m_DebugModesNames.Get(m_CurrentMode) );
        DbgUI.Text("");
        DbgUI.End();
    }
References DbgUI::Begin(), DbgUI::End(), GetGame(), GetPlayer(), m_CurrentMode, m_DebugModesNames, DbgUI::Text(), and float::ToString().
Referenced by OnPostFrameUpdate().
DisplayTargetInfo()
void WeaponDebug::DisplayTargetInfo () inline private
Definition at line 299 of file weapondebug.c.
    {
        DbgUI.Begin("target distance", 50,200);
        DbgUI.Text("value: " + m_TargetDistance.ToString());
        DbgUI.End();
    }
References DbgUI::Begin(), DbgUI::End(), m_TargetDistance, DbgUI::Text(), and float::ToString().
Referenced by OnPostFrameUpdate().
DrawBarrelMemoryPoints()
void WeaponDebug::DrawBarrelMemoryPoints (vector begin_point, vector end_point) inline private
Definition at line 206 of file weapondebug.c.
    {
        if (!m_IsDrawKeyHeldDown)
        {
            m_Shape_usti = Debug.DrawSphere(end_point, 0.011, Colors.GREEN, ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE|ShapeFlags.NOZBUFFER);
            m_Shape_konec = Debug.DrawSphere(begin_point, 0.011, Colors.GREEN, ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE|ShapeFlags.NOZBUFFER);
        }
    }
References Debug::DrawSphere(), Colors::GREEN, m_IsDrawKeyHeldDown, m_Shape_konec, and m_Shape_usti.
Referenced by OnPostFrameUpdate().
DrawEyePoint()
void WeaponDebug::DrawEyePoint (Weapon weapon) inline private
Definition at line 266 of file weapondebug.c.
    {
        vector position = GetEyePointPosition(weapon);
        m_ShapeEye = Debug.DrawSphere(position, 0.009, COLOR_BLUE, ShapeFlags.TRANSP|ShapeFlags.NOOUTLINE|ShapeFlags.NOZBUFFER);
    }
References COLOR_BLUE, Debug::DrawSphere(), GetEyePointPosition(), and m_ShapeEye.
Referenced by OnPostFrameUpdate().
DrawLineOfFire()
void WeaponDebug::DrawLineOfFire (vector begin_point, vector end_point) inline private
Definition at line 216 of file weapondebug.c.
    {
        vector contact_point;
        vector contact_dir;
        vector aim_point = end_point - begin_point;
        int contact_component;
        aim_point = aim_point.Normalized() * 100;
        aim_point = aim_point + end_point;
        m_ShapeFireDirection1 = Debug.DrawLine(end_point, aim_point);
        m_ShapeFireDirection2 = Debug.DrawLine(begin_point, end_point, ShapeFlags.NOZBUFFER );
        if ( DayZPhysics.RaycastRV(end_point, aim_point, contact_point, contact_dir, contact_component, null, null, null, false, false, ObjIntersectFire) )
        {
            m_HitShape = Debug.DrawSphere(contact_point, 0.04, COLOR_RED);
        }
        if ( m_IsFireKeyPressed )
        {
            Debug.RemoveShape(m_PermanentLine1);
            m_PermanentLine1 = Debug.DrawLine(end_point, contact_point, Colors.RED, ShapeFlags.NOZBUFFER );
        }
    }
References COLOR_RED, Debug::DrawLine(), Debug::DrawSphere(), m_HitShape, m_IsFireKeyPressed, m_PermanentLine1, m_ShapeFireDirection1, m_ShapeFireDirection2, vector::Normalized(), DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
DrawLineOfFireCameraHybrid()
void WeaponDebug::DrawLineOfFireCameraHybrid (vector usti_hlavne_position, vector camera_dir, vector camera_pos, vector konec_hlavne_position) inline private
Definition at line 354 of file weapondebug.c.
    {
        bool muzzle_shot;
        vector contact_point_cam_trace;
        vector contact_point_muzzle_trace;
        vector aim_at_position;
        vector contact_dir_muzzle;
        vector contact_dir;
        vector contact_point;
        int contact_component;
        int contact_component_muzzle;
        float distance_to_aim_at;
        vector end_point = camera_pos + camera_dir * 100;
        vector start_point = camera_pos + (CAMERA_BULLET_ORIGIN_OFFSET * camera_dir);
        vector weapon_aim_direction = usti_hlavne_position - konec_hlavne_position;
        weapon_aim_direction.Normalize();
        Man player = GetGame().GetPlayer();
        Object player_o;
        Class.CastTo(player_o, player);
        if ( DayZPhysics.RaycastRV(start_point, end_point, contact_point_cam_trace, contact_dir, contact_component,null, null, player_o , false, false, ObjIntersectFire) )
        {
            m_TargetDistance = vector.Distance(start_point, contact_point_cam_trace);
            aim_at_position = contact_point_cam_trace;
            if ( DayZPhysics.RaycastRV(usti_hlavne_position, contact_point_cam_trace, contact_point_muzzle_trace, contact_dir, contact_component,null, null, player_o , false, false, ObjIntersectFire, 0.05) )
            {
                float collision_distance = vector.Distance(contact_point_cam_trace, contact_point_muzzle_trace);
                float muzzle_collision_distance = vector.Distance(usti_hlavne_position, contact_point_muzzle_trace);
                if ((collision_distance > 2 && muzzle_collision_distance < MAX_MUZZLE_DISTANCE_TOLERANCE) || m_TargetDistance < CAMERA_TRACE_MIN_DISTANCE_TOLERANCE)
                {
                    muzzle_shot = true;
                    aim_at_position = contact_point_muzzle_trace;
                }
            }
        }
        distance_to_aim_at = vector.Distance(camera_pos, aim_at_position);
        if ( m_IsFireKeyPressed )
        {
            Debug.RemoveShape(m_PermanentLine1);
            Debug.RemoveShape(m_PermanentLine2);
            Debug.RemoveShape(m_PermanentShape1);
            vector contact_point_temp;
            if (muzzle_shot)
            {
                m_PermanentLine1 = Debug.DrawLine(usti_hlavne_position, usti_hlavne_position + weapon_aim_direction * 5, Colors.RED, ShapeFlags.NOZBUFFER );
                m_PermanentLine2 = Debug.DrawLine(camera_pos, contact_point_cam_trace, Colors.GREEN, ShapeFlags.NOZBUFFER );
                PrintString("muzle shot");
            }
            else
            {
                vector dir = contact_point_cam_trace - camera_pos;
                dir.Normalize();
                dir = dir * 100;
                float dst = vector.Distance(camera_pos, contact_point_cam_trace);
                float dist2 = vector.Distance(camera_pos, contact_point_cam_trace);
                //m_PermanentShape1 = Debug.DrawSphere(start_point, 0.015,Colors.GREEN);
                m_PermanentLine1 = Debug.DrawLine(start_point, contact_point_cam_trace + dir, Colors.RED, ShapeFlags.NOZBUFFER );
                PrintString("camera shot");
            }
        }
        float clamped_distance = Math.Clamp(distance_to_aim_at, 0 , 100);
        float distance_normalized = Math.InverseLerp(0, 100, clamped_distance);
        float hit_sphere_size = Math.Lerp(0.025, 0.75, distance_normalized);
        Debug.RemoveShape(m_HitShape4);
        Debug.RemoveShape(m_HitShape);
        m_HitShape = Debug.DrawSphere(contact_point_cam_trace, 0.20,Colors.GREEN, ShapeFlags.TRANSP);
        m_HitShape4 = Debug.DrawSphere(aim_at_position, hit_sphere_size);
    }
References CAMERA_BULLET_ORIGIN_OFFSET, CAMERA_TRACE_MIN_DISTANCE_TOLERANCE, Class::CastTo(), Math::Clamp(), vector::Distance(), Debug::DrawLine(), Debug::DrawSphere(), GetGame(), CGame::GetPlayer(), Colors::GREEN, Math::InverseLerp(), Math::Lerp(), m_HitShape, m_HitShape4, m_IsFireKeyPressed, m_PermanentLine1, m_PermanentLine2, m_PermanentShape1, m_TargetDistance, MAX_MUZZLE_DISTANCE_TOLERANCE, vector::Normalize(), PrintString(), DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
DrawLineOfFireMuzzleToHit()
void WeaponDebug::DrawLineOfFireMuzzleToHit (vector begin_point, vector camera_dir, vector camera_pos) inline private
Definition at line 307 of file weapondebug.c.
    {
        vector contact_point_cam_trace;
        vector contact_point_muzzle_trace;
        vector contact_dir_muzzle;
        vector contact_dir_camera;
        vector contact_point;
        vector contact_dir;
        int contact_component;
        int contact_component_muzzle;
        vector end_point = camera_pos + camera_dir * 1000;
        Man player = GetGame().GetPlayer();
        Object player_o;
        Class.CastTo(player_o, player);
        if ( DayZPhysics.RaycastRV(camera_pos, end_point, contact_point_cam_trace, contact_dir_camera, contact_component,null, null, player_o , false, false, ObjIntersectFire, 0.1) )
        {
            m_ShapeFireDirCamera = Debug.DrawLine(begin_point, contact_point_cam_trace, Colors.RED, ShapeFlags.NOZBUFFER );
            m_HitShape2 = Debug.DrawSphere(contact_point_cam_trace, 0.03, Colors.GREEN);
            m_TargetDistance =  vector.Distance( player.GetPosition(), contact_point_cam_trace);
            if ( m_IsFireKeyPressed )
            {
                Debug.RemoveShape(m_PermanentLine1);
                Debug.RemoveShape(m_PermanentLine2);
                m_PermanentLine1 = Debug.DrawLine(begin_point, contact_point_cam_trace, Colors.RED, ShapeFlags.NOZBUFFER );
                m_PermanentLine2 = Debug.DrawLine(camera_pos, contact_point_cam_trace, Colors.GREEN, ShapeFlags.NOZBUFFER );
            }
        }
        else
        {
            m_ShapeFireDirCamera = Debug.DrawLine(begin_point, end_point, Colors.GREEN, ShapeFlags.NOZBUFFER );
            m_TargetDistance = -1;
        }
        if ( DayZPhysics.RaycastRV(begin_point, contact_point_cam_trace, contact_point_muzzle_trace, contact_dir_muzzle, contact_component_muzzle, null, null, null, false, false, ObjIntersectFire, 0.0) )
        {
            m_HitShape3 = Debug.DrawSphere(contact_point_muzzle_trace, 0.03, COLOR_RED);
        }
    }
References Class::CastTo(), COLOR_RED, vector::Distance(), Debug::DrawLine(), Debug::DrawSphere(), GetGame(), CGame::GetPlayer(), Colors::GREEN, m_HitShape2, m_HitShape3, m_IsFireKeyPressed, m_PermanentLine1, m_PermanentLine2, m_ShapeFireDirCamera, m_TargetDistance, DayZPhysics::RaycastRV(), Colors::RED, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate().
GetEyePointPosition()
vector WeaponDebug::GetEyePointPosition (Weapon weapon) inline private
Definition at line 272 of file weapondebug.c.
    {
        string memory_point_name = weapon.ConfigGetString("memoryPointCamera");
        ItemBase optics = weapon.GetAttachedOptics();
        if (optics)
        {
            memory_point_name = optics.ConfigGetString("memoryPointCamera");
            return optics.ModelToWorld(optics.GetSelectionPositionLS( memory_point_name ));
        }
        return weapon.ModelToWorld(weapon.GetSelectionPositionLS( memory_point_name ));
    }
Referenced by DrawEyePoint().
GetWeaponInHands()
Weapon WeaponDebug::GetWeaponInHands () inline private
Definition at line 52 of file weapondebug.c.
    {
        Weapon weapon_in_hands;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if( player && player.GetItemInHands() ) Class.CastTo(weapon_in_hands,  player.GetItemInHands());
        return weapon_in_hands;
    }
References Class::CastTo(), GetGame(), and GetPlayer().
Referenced by OnPostFrameUpdate().
OnCommandHandlerUpdate()
void WeaponDebug::OnCommandHandlerUpdate () inline private
Definition at line 98 of file weapondebug.c.
    {
        m_IsLMBPressed = false;
        m_IsFireKeyPressed = false;
        if (KeyState(KeyCode.KC_LWIN) == 1)
        {
            if (!m_IsDrawKeyHeldDown)
            {
                OnKeyDown(KeyCode.KC_LWIN);
            }
            m_IsDrawKeyHeldDown = true;
        }
        else
        {
            if ( m_IsDrawKeyHeldDown )
            {
                //OnKeyUp();
            }
            m_IsDrawKeyHeldDown = false;
        }
        if (KeyState(KeyCode.KC_Z) == 1)
        {
            ClearKey(KeyCode.KC_Z);
            CycleDebugMode();
        }
        if (KeyState(KeyCode.KC_X) == 1)
        {
            m_IsFireKeyPressed = true;
            ClearKey(KeyCode.KC_X);
        }
        if (GetMouseState(MouseState.LEFT) & MB_PRESSED_MASK)
        {
            m_IsLMBPressed = true;
        }
    }
References ClearKey(), CycleDebugMode(), GetMouseState(), KeyState(), m_IsDrawKeyHeldDown, m_IsFireKeyPressed, m_IsLMBPressed, and OnKeyDown().
Referenced by ManBase::OnCommandHandlerTick().
OnKeyDown()
void WeaponDebug::OnKeyDown (KeyCode key) inline private
Definition at line 139 of file weapondebug.c.
    {
        if (key == KeyCode.KC_X)
        {
        }
    }
Referenced by OnCommandHandlerUpdate().
OnPostFrameUpdate()
void WeaponDebug::OnPostFrameUpdate () inline private
Definition at line 156 of file weapondebug.c.
    {
        if ( GetWeaponInHands() )
        {
            RemoveAllShapes();
            Weapon weapon = GetWeaponInHands();
            vector cameraDirection = GetGame().GetCurrentCameraDirection();
            vector cameraPosition = GetGame().GetCurrentCameraPosition();
            vector usti_hlavne_position = weapon.GetSelectionPositionMS( "usti hlavne" );//usti hlavne
            vector konec_hlavne_position = weapon.GetSelectionPositionMS( "konec hlavne" );//konec hlavne
            usti_hlavne_position = weapon.ModelToWorld(usti_hlavne_position);
            konec_hlavne_position = weapon.ModelToWorld(konec_hlavne_position);
            if ( m_CurrentMode == eDebugMode.NORMAL )
            {
                DrawLineOfFire(konec_hlavne_position,usti_hlavne_position );
            }
            if ( m_CurrentMode == eDebugMode.MUZZLE_FIRE )
            {
                DrawLineOfFireMuzzleToHit(usti_hlavne_position, cameraDirection, cameraPosition);
            }
            if ( m_CurrentMode == eDebugMode.CAMERA_MUZZLE_HYBRID )
            {
                DrawLineOfFireCameraHybrid(usti_hlavne_position, cameraDirection, cameraPosition, konec_hlavne_position);
            }
            if (m_IsDrawKeyHeldDown)
            {
                AddPosToCyclicBuffer(usti_hlavne_position);
                OrderTrailArray();
            }
            m_ShapeTrailLines = Debug.DrawLines( m_AimTrailOrdered,BUFFER_SIZE, COLOR_YELLOW, ShapeFlags.NOZBUFFER );
            DrawEyePoint(weapon);
            DrawBarrelMemoryPoints(konec_hlavne_position,usti_hlavne_position );
            DisplayGeneralInfo();
            DisplayTargetInfo();
            /*
            vector pos;
            weapon.GetProjectedCursorPos3d(pos);
            Debug.RemoveShape(temp_shape);
            temp_shape = Debug.DrawSphere(pos, 0.1, Colors.GREEN);
            */
        }
    }
References AddPosToCyclicBuffer(), BUFFER_SIZE, COLOR_YELLOW, DisplayGeneralInfo(), DisplayTargetInfo(), DrawBarrelMemoryPoints(), DrawEyePoint(), DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), Debug::DrawLines(), CGame::GetCurrentCameraDirection(), CGame::GetCurrentCameraPosition(), GetGame(), GetWeaponInHands(), m_AimTrailOrdered, m_CurrentMode, m_IsDrawKeyHeldDown, m_ShapeTrailLines, OrderTrailArray(), and RemoveAllShapes().
Referenced by ManBase::EOnPostFrame().
OrderTrailArray()
void WeaponDebug::OrderTrailArray () inline private
Definition at line 251 of file weapondebug.c.
    {
        int unordered_index;
        for (int i = 0; i < BUFFER_SIZE; i++)
        {
            unordered_index = m_BufferIndex + i;
            if ( unordered_index >= BUFFER_SIZE )
            {
                unordered_index = unordered_index - BUFFER_SIZE;
            }
            m_AimTrailOrdered[i] = m_AimTrailCyclic[unordered_index];
        }
    }
References BUFFER_SIZE, m_AimTrailCyclic, m_AimTrailOrdered, and m_BufferIndex.
Referenced by OnPostFrameUpdate().
RemoveAllShapes()
void WeaponDebug::RemoveAllShapes (bool is_exit = false) inline private
Definition at line 74 of file weapondebug.c.
    {
        Debug.RemoveShape(m_Shape_usti);
        Debug.RemoveShape(m_Shape_konec);
        Debug.RemoveShape(m_ShapeFireDirection1);
        Debug.RemoveShape(m_ShapeFireDirection2);
        Debug.RemoveShape(m_ShapeEye);
        Debug.RemoveShape(m_ShapeTrailLines);
        Debug.RemoveShape(m_ShapeFireDirCamera);
        Debug.RemoveShape(m_HitShape);
        Debug.RemoveShape(m_HitShape2);
        Debug.RemoveShape(m_HitShape3);
        Debug.RemoveShape(m_HitShape4);
        if ( is_exit )
        {
            Debug.RemoveShape(m_PermanentLine1);
            Debug.RemoveShape(m_PermanentLine2);
            Debug.RemoveShape(m_PermanentShape1);
            Debug.RemoveShape(m_PermanentShape2);
        }
    }
References m_HitShape, m_HitShape2, m_HitShape3, m_HitShape4, m_PermanentLine1, m_PermanentLine2, m_PermanentShape1, m_PermanentShape2, m_Shape_konec, m_Shape_usti, m_ShapeEye, m_ShapeFireDirCamera, m_ShapeFireDirection1, m_ShapeFireDirection2, m_ShapeTrailLines, and Debug::RemoveShape().
Referenced by OnPostFrameUpdate(), and ~WeaponDebug().
Member Data Documentation
BUFFER_SIZE
const int WeaponDebug::BUFFER_SIZE = 1000 private
Definition at line 13 of file weapondebug.c.
Referenced by AddPosToCyclicBuffer(), OnPostFrameUpdate(), and OrderTrailArray().
CAMERA_BULLET_ORIGIN_OFFSET
const float WeaponDebug::CAMERA_BULLET_ORIGIN_OFFSET = 1 private
Definition at line 16 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid().
CAMERA_TRACE_MIN_DISTANCE_TOLERANCE
const float WeaponDebug::CAMERA_TRACE_MIN_DISTANCE_TOLERANCE = 0.3 private
Definition at line 17 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid().
COLLISIONS_DISTANCE_TOLERANCE
const float WeaponDebug::COLLISIONS_DISTANCE_TOLERANCE = 0.01 private
Definition at line 14 of file weapondebug.c.
m_AimTrailCyclic
vector WeaponDebug::m_AimTrailCyclic[BUFFER_SIZE] private
Definition at line 27 of file weapondebug.c.
Referenced by AddPosToCyclicBuffer(), and OrderTrailArray().
m_AimTrailOrdered
vector WeaponDebug::m_AimTrailOrdered[BUFFER_SIZE] private
Definition at line 28 of file weapondebug.c.
Referenced by OnPostFrameUpdate(), and OrderTrailArray().
m_BufferIndex
int WeaponDebug::m_BufferIndex private
Definition at line 20 of file weapondebug.c.
Referenced by AddPosToCyclicBuffer(), and OrderTrailArray().
m_CurrentMode
eDebugMode WeaponDebug::m_CurrentMode private
Definition at line 26 of file weapondebug.c.
Referenced by CycleDebugMode(), DisplayGeneralInfo(), and OnPostFrameUpdate().
m_DebugModesNames
ref map<int, string> WeaponDebug::m_DebugModesNames = new map<int, string> private
Definition at line 30 of file weapondebug.c.
Referenced by DisplayGeneralInfo(), and WeaponDebug().
m_HitShape
Shape WeaponDebug::m_HitShape private
Definition at line 38 of file weapondebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_HitShape2
Shape WeaponDebug::m_HitShape2 private
Definition at line 42 of file weapondebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_HitShape3
Shape WeaponDebug::m_HitShape3 private
Definition at line 43 of file weapondebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_HitShape4
Shape WeaponDebug::m_HitShape4 private
Definition at line 44 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_IsDrawKeyHeldDown
bool WeaponDebug::m_IsDrawKeyHeldDown private
Definition at line 21 of file weapondebug.c.
Referenced by DrawBarrelMemoryPoints(), OnCommandHandlerUpdate(), and OnPostFrameUpdate().
m_IsFireKeyPressed
bool WeaponDebug::m_IsFireKeyPressed private
Definition at line 24 of file weapondebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and OnCommandHandlerUpdate().
m_IsLMBPressed
bool WeaponDebug::m_IsLMBPressed private
Definition at line 22 of file weapondebug.c.
Referenced by OnCommandHandlerUpdate().
m_IsToggleKeyPressed
bool WeaponDebug::m_IsToggleKeyPressed private
Definition at line 23 of file weapondebug.c.
m_PermanentLine1
Shape WeaponDebug::m_PermanentLine1 private
Definition at line 46 of file weapondebug.c.
Referenced by DrawLineOfFire(), DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_PermanentLine2
Shape WeaponDebug::m_PermanentLine2 private
Definition at line 47 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid(), DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_PermanentShape1
Shape WeaponDebug::m_PermanentShape1 private
Definition at line 49 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid(), and RemoveAllShapes().
m_PermanentShape2
Shape WeaponDebug::m_PermanentShape2 private
Definition at line 50 of file weapondebug.c.
Referenced by RemoveAllShapes().
m_Shape_konec
Shape WeaponDebug::m_Shape_konec private
Definition at line 35 of file weapondebug.c.
Referenced by DrawBarrelMemoryPoints(), and RemoveAllShapes().
m_Shape_usti
Shape WeaponDebug::m_Shape_usti private
Definition at line 34 of file weapondebug.c.
Referenced by DrawBarrelMemoryPoints(), and RemoveAllShapes().
m_ShapeEye
Shape WeaponDebug::m_ShapeEye private
Definition at line 39 of file weapondebug.c.
Referenced by DrawEyePoint(), and RemoveAllShapes().
m_ShapeFireDirCamera
Shape WeaponDebug::m_ShapeFireDirCamera private
Definition at line 41 of file weapondebug.c.
Referenced by DrawLineOfFireMuzzleToHit(), and RemoveAllShapes().
m_ShapeFireDirection1
Shape WeaponDebug::m_ShapeFireDirection1 private
Definition at line 36 of file weapondebug.c.
Referenced by DrawLineOfFire(), and RemoveAllShapes().
m_ShapeFireDirection2
Shape WeaponDebug::m_ShapeFireDirection2 private
Definition at line 37 of file weapondebug.c.
Referenced by DrawLineOfFire(), and RemoveAllShapes().
m_ShapeTrailLines
Shape WeaponDebug::m_ShapeTrailLines private
Definition at line 40 of file weapondebug.c.
Referenced by OnPostFrameUpdate(), and RemoveAllShapes().
m_TargetDistance
float WeaponDebug::m_TargetDistance private
Definition at line 25 of file weapondebug.c.
Referenced by DisplayTargetInfo(), DrawLineOfFireCameraHybrid(), and DrawLineOfFireMuzzleToHit().
m_WeaponInHands
Weapon WeaponDebug::m_WeaponInHands private
Definition at line 19 of file weapondebug.c.
MAX_MUZZLE_DISTANCE_TOLERANCE
const float WeaponDebug::MAX_MUZZLE_DISTANCE_TOLERANCE = 20 private
Definition at line 15 of file weapondebug.c.
Referenced by DrawLineOfFireCameraHybrid().