DayzKode: Inventory_Base Class Reference
Inventory_Base Class Reference
Private Member Functions
void AttachToObject (ItemBase parent)
bool CanBeFilledAtPosition (vector position)
bool CanBeManipulated ()
override bool CanDetachAttachment (EntityAI attachment)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanDetachAttachment (EntityAI parent)
override bool CanHaveTemperature ()
override bool CanLoadItemIntoCargo (EntityAI item)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanReceiveItemIntoCargo (EntityAI item)
void DetachFromObject (ItemBase parent)
override void EEDelete (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
void EmptySeedPack (PlayerBase player)
void Fill ()
void Fold ()
void FryingPan ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
int GetState ()
override array< int > GetValidFinishers ()
override array< int > GetValidFinishers ()
override bool HasProxyParts ()
void HescoBox ()
void HideOnItem (ItemBase item)
override bool IsContainer ()
override bool IsDeployable ()
override bool IsElectricAppliance ()
override bool IsMeleeFinisher ()
override bool IsMeleeFinisher ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnVariablesSynchronized ()
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
override void OnWorkStart ()
override void OnWorkStop ()
void ParticleCookingStart (int particle_id)
void ParticleCookingStop ()
void PlayDeployLoopSound ()
void RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
void RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned)
override void RefreshPhysics ()
void RefreshVisuals ()
void RemoveAudioVisuals ()
void RemoveAudioVisualsOnClient ()
void SeedPackBase ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
override void SetActions ()
void SetState (int state)
protected void SoundCookingStart (string sound_name)
protected void SoundCookingStop ()
void StopDeployLoopSound ()
void Synchronize ()
void Synchronize ()
void TurnOffItem (ItemBase item)
void TurnOnItem (ItemBase item)
void Unfold ()
void XmasLights ()
void ~FryingPan ()
void ~HescoBox ()
Private Attributes
private ItemBase m_AttachedTo = NULL
protected bool m_CookingIsBurned
protected bool m_CookingIsDone
protected bool m_CookingIsEmpty
protected CookingMethodType m_CookingMethod
ref protected EffectSound m_DeployLoopSound
protected Particle m_ParticleCooking
protected int m_ParticlePlaying = ParticleList.INVALID
protected SoundOnVehicle m_SoundCooking
protected string m_SoundPlaying = ""
protected int m_State
ref Timer m_Timer
protected int PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE
protected int PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START
protected int PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE
protected int PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE
protected int PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START
const string SOUND_BAKING_DONE = "bakeDone"
const string SOUND_BAKING_START = "bake"
const string SOUND_BURNING_DONE = "burned"
const string SOUND_DRYING_DONE = "dryDone"
const string SOUND_DRYING_START = "dry"
Static Private Attributes
static const int FILLED = 2
static const int FOLDED = 0
static private const float PACK_DAMAGE_TOLERANCE = 0.5
static const int PERCENTUAL_DAMAGE = 1
static const int UNFOLDED = 1
Detailed Description
Definition at line 1 of file barbedbaseballbat.c.
Constructor & Destructor Documentation
~HescoBox()
void Inventory_Base::~HescoBox () inline private
Definition at line 23 of file hescobox.c.
    {
        SEffectManager.DestroyEffect( m_DeployLoopSound );
    }
References SEffectManager::DestroyEffect(), and m_DeployLoopSound.
~FryingPan()
void Inventory_Base::~FryingPan () inline private
Definition at line 40 of file fryingpan.c.
{}
Member Function Documentation
AttachToObject()
void Inventory_Base::AttachToObject (ItemBase parent) inline private
Definition at line 27 of file xmaslights.c.
    {
        //SetPilotLight( false );
        m_AttachedTo = parent;
        TurnOnItem( parent );
        if ( GetCompEM().IsPlugged() )
        {
            parent.SetAnimationPhase( "Cord_plugged", 0);
            parent.SetAnimationPhase( "Cord_folded", 1);
        }
        else
        {
            parent.SetAnimationPhase( "Cord_plugged", 1);
            parent.SetAnimationPhase( "Cord_folded", 0);
        }
    }
References TurnOnItem().
CanBeFilledAtPosition()
bool Inventory_Base::CanBeFilledAtPosition (vector position) inline private
Definition at line 84 of file hescobox.c.
    {
        string surface_type;
        GetGame().SurfaceGetType( position[0], position[2], surface_type );
        return GetGame().IsSurfaceDigable(surface_type);
    }
References GetGame(), CGame::IsSurfaceDigable(), and CGame::SurfaceGetType().
CanBeManipulated()
bool Inventory_Base::CanBeManipulated () inline private
Definition at line 92 of file hescobox.c.
    {
        if ( GetState() == FOLDED )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References FOLDED, and GetState().
Referenced by CanPutIntoHands().
CanDetachAttachment() [1/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI attachment) inline private
Definition at line 27 of file atlasbipod.c.
    {
        return false;
    }
CanDetachAttachment() [2/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file ak_railhndgrd.c.
    {
        if ( Weapon_Base.Cast(parent) && parent.FindAttachmentBySlotName("weaponFlashlight")/*.IsKindOf("UniversalLight")*/ )
        {
            return false;
        }
        return true;
    }
CanDetachAttachment() [3/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file m4_rishndgrd.c.
    {
        if ( Weapon_Base.Cast(parent) && parent.FindAttachmentBySlotName("weaponFlashlight") )
        {
            return false;
        }
        return true;
    }
CanDetachAttachment() [4/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 3 of file mp5_railhndgrd.c.
    {
        if ( Weapon_Base.Cast(parent) && parent.FindAttachmentBySlotName("weaponFlashlight")/*.IsKindOf("UniversalLight")*/ )
        {
            return false;
        }
        return true;
    }
CanDetachAttachment() [5/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 42 of file nail.c.
    {
        bool is_barrel = false;
        bool is_opened_barrel = false;
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        if ( is_opened_barrel || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanDetachAttachment() [6/6]
override bool Inventory_Base::CanDetachAttachment (EntityAI parent) inline private
Definition at line 59 of file plantmaterial.c.
    {
        /*bool is_barrel = false;
        bool is_opened_barrel = false;
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        if ( is_opened_barrel || !is_barrel )
        {
            return true;
        }*/
        return false;
    }
CanHaveTemperature()
override bool Inventory_Base::CanHaveTemperature () inline private
Definition at line 47 of file fryingpan.c.
    {
        return true;
    }
CanLoadItemIntoCargo()
override bool Inventory_Base::CanLoadItemIntoCargo (EntityAI item) inline private
Definition at line 74 of file fryingpan.c.
    {
        if ( !super.CanLoadItemIntoCargo( item ) )
            return false;
        if ( IsCargoException4x3( item ) )
            return false;
        return true;
    }
References IsCargoException4x3().
CanPutAsAttachment() [1/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file atlasbipod.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        bool m4_hndgrd = false;
        bool ak_hndgrd = false;
        if ( parent.FindAttachmentBySlotName("weaponHandguardM4") != NULL )
        {
            m4_hndgrd = parent.FindAttachmentBySlotName("weaponHandguardM4").IsKindOf("M4_RISHndgrd");
        }
        if ( parent.FindAttachmentBySlotName("weaponHandguardAK") != NULL )
        {
            ak_hndgrd = parent.FindAttachmentBySlotName("weaponHandguardAK").IsKindOf("AK_RailHndgrd");
        }
        if ( m4_hndgrd || ak_hndgrd )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [2/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file mosin_bayonet.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( parent.FindAttachmentBySlotName("suppressorImpro") == null && parent.FindAttachmentBySlotName("weaponMuzzleMosin") == null )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [3/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file nail.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        const int SLOTS_ARRAY = 8;
        bool is_barrel = false;
        bool is_opened_barrel = false;
        bool slot_test = true;
        string slot_names[SLOTS_ARRAY] = { "BerryR", "BerryB", "Plant", "OakBark", "BirchBark", "Lime", "Disinfectant", "Guts" };
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        // all of the barrel slots are empty
        for ( int i = 0; i < SLOTS_ARRAY ; i++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names[i]) != NULL )
            {
                slot_test = false;
                break;
            }
        }
        if ( ( is_opened_barrel && slot_test ) || !is_barrel )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [4/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file plantmaterial.c.
    {
        if (!super.CanPutAsAttachment(parent))
        {
            return false;
        }
        /*const int SLOTS_ARRAY1 = 6;
        const int SLOTS_ARRAY2 = 7;
        bool is_barrel = false;
        bool is_opened_barrel = false;
        bool slot_test1 = true;
        bool slot_test2 = true;
        string slot_names1[SLOTS_ARRAY1] = { "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant", "Guts" };
        string slot_names2[SLOTS_ARRAY2] = { "BerryR", "BerryB", "Nails", "OakBark", "BirchBark", "Lime", "Disinfectant" };
        // is barrel
        if ( parent.IsKindOf("Barrel_ColorBase") )
        {
            is_barrel = true;
        }
        // is opened barrel
        if ( is_barrel && parent.GetAnimationPhase("Lid") == 1 )
        {
            is_opened_barrel = true;
        }
        // all of the barrel attachment slots are empty (first set of ingredients)
        for ( int idx1 = 0; idx1 < SLOTS_ARRAY1 ; idx1++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names1[idx1]) != NULL )
            {
                slot_test1 = false;
                break;
            }
        }
        // all of the barrel attachment slots are empty (second set of ingredients)
        for ( int idx2 = 0; idx2 < SLOTS_ARRAY2 ; idx2++ )
        {
            if ( parent.FindAttachmentBySlotName(slot_names2[idx2]) != NULL )
            {
                slot_test2 = false;
                break;
            }
        }
        if ( ( is_opened_barrel && slot_test1 ) || ( is_opened_barrel && slot_test2) || !is_barrel )
        {
            return true;
        }*/
        return false;
    }
CanPutAsAttachment() [5/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file red9bttstck.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( !parent.IsKindOf("PlateCarrierHolster") && !parent.IsKindOf("PlateCarrierComplete") && !parent.IsKindOf("CarrierHolsterSolo") && !parent.IsKindOf("ChestHolster") )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [6/6]
override bool Inventory_Base::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 13 of file sks_bayonet.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( parent.FindAttachmentBySlotName("suppressorImpro") == null && parent.FindAttachmentBySlotName("weaponMuzzle") == null )
        {
            return true;
        }
        return false;
    }
CanPutInCargo() [1/2]
override bool Inventory_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 3 of file candle.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        if ( !parent.HasSelection("flame") )
        {
            return true;
        }
        return false;
    }
CanPutInCargo() [2/2]
override bool Inventory_Base::CanPutInCargo (EntityAI parent) inline private
Definition at line 52 of file fryingpan.c.
    {
        if ( !super.CanPutInCargo( parent ) )
            return false;
        if ( parent && IsCargoException4x3( parent ) )
            return false;
        return true;
    }
References IsCargoException4x3().
CanPutIntoHands()
override bool Inventory_Base::CanPutIntoHands (EntityAI parent) inline private
Definition at line 33 of file hescobox.c.
    {
        if( !super.CanPutIntoHands( parent ) )
        {
            return false;
        }
        return CanBeManipulated();
    }
References CanBeManipulated().
CanReceiveItemIntoCargo()
override bool Inventory_Base::CanReceiveItemIntoCargo (EntityAI item) inline private
Definition at line 63 of file fryingpan.c.
    {
        if ( !super.CanReceiveItemIntoCargo( item ) )
            return false;
        if ( IsCargoException4x3( item ) )
            return false;
        return true;
    }
References IsCargoException4x3().
DetachFromObject()
void Inventory_Base::DetachFromObject (ItemBase parent) inline private
Definition at line 46 of file xmaslights.c.
    {
        m_AttachedTo = NULL;
        HideOnItem( parent );
        TurnOnItem( this );
        GetCompEM().UnplugThis();
    }
References HideOnItem(), and TurnOnItem().
EEDelete()
override void Inventory_Base::EEDelete (EntityAI parent) inline private
Definition at line 95 of file fryingpan.c.
    {
        super.EEDelete( parent );
        //remove audio visuals
        RemoveAudioVisuals();
    }
References RemoveAudioVisuals().
EEItemLocationChanged()
override void Inventory_Base::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 140 of file hescobox.c.
    {
        super.EEItemLocationChanged (oldLoc, newLoc);
        //RefreshPhysics();
    }
EmptySeedPack()
void Inventory_Base::EmptySeedPack (PlayerBase player) inline private
Definition at line 9 of file seedpackbase.c.
    {
        string pack_type = GetType();
        string seeds_type = "";
        GetGame().ConfigGetText( "cfgVehicles " + pack_type + " Horticulture ContainsSeedsType", seeds_type );
        int seeds_quantity_max = GetGame().ConfigGetInt( "cfgVehicles " + pack_type + " Horticulture ContainsSeedsQuantity" );
        int seeds_quantity = seeds_quantity_max;
        seeds_quantity = Math.Round( seeds_quantity_max * GetHealth01("","") );
        if ( seeds_quantity < 1 )
        {
            seeds_quantity = 1;
        }
        if (player)
        {
            EmptySeedsPackLambda lambda = new EmptySeedsPackLambda(this, seeds_type, player, seeds_quantity);
            player.ServerReplaceItemInHandsWithNew(lambda);
        }
        else
        {
            vector pos = GetPosition();
            GetGame().CreateObjectEx(seeds_type, pos, ECE_PLACE_ON_SURFACE);
            GetGame().ObjectDelete( this );
        }
    }
References CGame::ConfigGetInt(), CGame::ConfigGetText(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, EmptySeedsPackLambda(), GetGame(), GetHealth01(), GetPosition, GetType(), CGame::ObjectDelete(), and Math::Round().
Fill()
void Inventory_Base::Fill () inline private
Definition at line 178 of file hescobox.c.
    {
        this.HideSelection( "inventory" );
        this.HideSelection( "placing" );
        this.ShowSelection( "filled" );
        SetState( FILLED );
        RefreshPhysics();
        if ( GetGame().IsServer() )
        {
            Synchronize();
            DecreaseHealth( "", "", 5 ); //TODO Daniel implement soft skill bonus via useraction
            SetAllowDamage(false);
        }
    }
References DecreaseHealth(), GetGame(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnStoreLoad().
Fold()
void Inventory_Base::Fold () inline private
Definition at line 104 of file hescobox.c.
    {
        this.ShowSelection( "inventory" );
        this.HideSelection( "placing" );
        this.HideSelection( "filled" );
        SetState( FOLDED );
        RefreshPhysics();
        if ( GetGame().IsServer() )
        {
            SetAllowDamage(true);
            Synchronize();
            float fold_damage = ( GetMaxHealth( "", "" ) / 100 ) * PERCENTUAL_DAMAGE;
            DecreaseHealth( "", "", fold_damage );
        }
    }
References DecreaseHealth(), FOLDED, GetGame(), GetMaxHealth(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnStoreLoad().
FryingPan()
void Inventory_Base::FryingPan () inline private
Definition at line 33 of file fryingpan.c.
    {
        RegisterNetSyncVariableInt( "m_CookingMethod", CookingMethodType.NONE, CookingMethodType.COUNT );
        RegisterNetSyncVariableBool( "m_CookingIsDone" );
        RegisterNetSyncVariableBool( "m_CookingIsEmpty" );
        RegisterNetSyncVariableBool( "m_CookingIsBurned" );
    }
GetDeploySoundset()
override string Inventory_Base::GetDeploySoundset () inline private
Definition at line 255 of file hescobox.c.
    {
        return "placeHescoBox_SoundSet";
    }
GetLoopDeploySoundset()
override string Inventory_Base::GetLoopDeploySoundset () inline private
Definition at line 260 of file hescobox.c.
    {
        return "hescobox_deploy_SoundSet";
    }
Referenced by PlayDeployLoopSound().
GetState()
int Inventory_Base::GetState () inline private
Definition at line 74 of file hescobox.c.
    {
        return m_State;
    }
References m_State.
Referenced by CanBeIgnitedBy(), CanBeManipulated(), OnInventoryEnter(), and RefreshPhysics().
GetValidFinishers() [1/2]
override array< int > Inventory_Base::GetValidFinishers () inline private
Definition at line 8 of file mosin_bayonet.c.
    {
        return {EMeleeHitType.FINISHER_LIVERSTAB,EMeleeHitType.FINISHER_NECKSTAB};
    }
GetValidFinishers() [2/2]
override array< int > Inventory_Base::GetValidFinishers () inline private
Definition at line 8 of file sks_bayonet.c.
    {
        return {EMeleeHitType.FINISHER_LIVERSTAB,EMeleeHitType.FINISHER_NECKSTAB};
    }
HasProxyParts()
override bool Inventory_Base::HasProxyParts () inline private
Definition at line 28 of file hescobox.c.
    {
        return true;
    }
HescoBox()
void Inventory_Base::HescoBox () inline private
Definition at line 13 of file hescobox.c.
    {
        m_State = FOLDED;
        //synchronized variables
        RegisterNetSyncVariableInt( "m_State", FOLDED, FILLED );
        RegisterNetSyncVariableBool("m_IsSoundSynchRemote");
        RegisterNetSyncVariableBool("m_IsDeploySound");
    }
References FOLDED, FOLDED, and m_State.
HideOnItem()
void Inventory_Base::HideOnItem (ItemBase item) inline private
Definition at line 94 of file xmaslights.c.
    {
        item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_r"), "" );
        item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_g"), "" );
        item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_b"), "" );
        item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_y"), "" );
        item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_r"), "" );
        item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_g"), "" );
        item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_b"), "" );
        item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_y"), "" );
//      item.SetPilotLight(false);
        item.SetAnimationPhase( "Cord_plugged", 1);
        item.SetAnimationPhase( "Cord_folded", 1);
    }
Referenced by DetachFromObject().
IsContainer()
override bool Inventory_Base::IsContainer () inline private
Definition at line 42 of file fryingpan.c.
    {
        return true;
    }
IsDeployable()
override bool Inventory_Base::IsDeployable () inline private
Definition at line 250 of file hescobox.c.
    {
        return true;
    }
IsElectricAppliance()
override bool Inventory_Base::IsElectricAppliance () inline private
Definition at line 10 of file xmaslights.c.
    {
        return true;
    }
IsMeleeFinisher() [1/2]
override bool Inventory_Base::IsMeleeFinisher () inline private
Definition at line 3 of file mosin_bayonet.c.
    {
        return true;
    }
IsMeleeFinisher() [2/2]
override bool Inventory_Base::IsMeleeFinisher () inline private
Definition at line 3 of file sks_bayonet.c.
    {
        return true;
    }
OnPlacementComplete()
override void Inventory_Base::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 238 of file hescobox.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            Unfold();
            SetIsDeploySound( true );
        }
    }
References GetGame(), SetIsDeploySound(), and Unfold().
OnStoreLoad()
override bool Inventory_Base::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 203 of file hescobox.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        // Load folded/unfolded state
        int state = FOLDED;
        if ( !ctx.Read(state) )
            state = FOLDED;
        switch (state)
        {
            case FOLDED:
            {
                Fold();
                break;
            }
            case UNFOLDED:
            {
                Unfold();
                break;
            }
            case FILLED:
            {
                Fill();
                break;
            }
        }
        return true;
    }
References Fill(), FILLED, Fold(), FOLDED, Serializer::Read(), Unfold(), and UNFOLDED.
OnStoreSave()
override void Inventory_Base::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 195 of file hescobox.c.
    {
        super.OnStoreSave(ctx);
        // Save state
        ctx.Write( m_State );
    }
References m_State, and Serializer::Write().
OnVariablesSynchronized() [1/2]
override void Inventory_Base::OnVariablesSynchronized () inline private
Definition at line 47 of file hescobox.c.
    {
        super.OnVariablesSynchronized();
        //refresh visuals
        RefreshVisuals();
        if ( IsDeploySound() )
        {
            PlayDeploySound();
        }
        if ( CanPlayDeployLoopSound() )
        {
            PlayDeployLoopSound();
        }
        if ( m_DeployLoopSound && !CanPlayDeployLoopSound() )
        {
            StopDeployLoopSound();
        }
    }
References CanPlayDeployLoopSound(), IsDeploySound(), m_DeployLoopSound, PlayDeployLoopSound(), PlayDeploySound(), RefreshVisuals(), and StopDeployLoopSound().
OnVariablesSynchronized() [2/2]
override void Inventory_Base::OnVariablesSynchronized () inline private
Definition at line 111 of file fryingpan.c.
    {
        super.OnVariablesSynchronized();
        //refresh audio visuals
        if ( m_CookingMethod != CookingMethodType.NONE )
        {
            RefreshAudioVisuals( m_CookingMethod, m_CookingIsDone, m_CookingIsEmpty, m_CookingIsBurned );
        }
        else
        {
            RemoveAudioVisuals();
        }
    }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, RefreshAudioVisuals(), and RemoveAudioVisuals().
OnWasAttached() [1/3]
override void Inventory_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 23 of file mosin_bayonet.c.
    {
        super.OnWasAttached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetBayonetAttached(true,slot_id);
        }
    }
OnWasAttached() [2/3]
override void Inventory_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 23 of file sks_bayonet.c.
    {
        super.OnWasAttached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetBayonetAttached(true,slot_id);
        }
    }
OnWasAttached() [3/3]
override void Inventory_Base::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 3 of file attachments.c.
    {
        super.OnWasAttached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetButtstockAttached(true,slot_id);
        }
    }
OnWasDetached() [1/3]
override void Inventory_Base::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 33 of file mosin_bayonet.c.
    {
        super.OnWasDetached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetBayonetAttached(false);
        }
    }
OnWasDetached() [2/3]
override void Inventory_Base::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 33 of file sks_bayonet.c.
    {
        super.OnWasDetached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetBayonetAttached(false);
        }
    }
OnWasDetached() [3/3]
override void Inventory_Base::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 13 of file attachments.c.
    {
        super.OnWasDetached(parent, slot_id);
        if( parent.IsWeapon() )
        {
            parent.SetButtstockAttached(false);
        }
    }
OnWorkStart()
override void Inventory_Base::OnWorkStart () inline private
Definition at line 15 of file xmaslights.c.
    {
        TurnOnItem( m_AttachedTo );
        TurnOnItem( this );
    }
References TurnOnItem().
OnWorkStop()
override void Inventory_Base::OnWorkStop () inline private
Definition at line 21 of file xmaslights.c.
    {
        TurnOffItem( m_AttachedTo );
        TurnOffItem( this );
    }
References TurnOffItem().
ParticleCookingStart()
void Inventory_Base::ParticleCookingStart (int particle_id) inline private
Definition at line 198 of file fryingpan.c.
    {
        if ( m_ParticlePlaying != particle_id )
        {
            //stop previous particles
            ParticleCookingStop();
            //create new
            if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
            {
                vector local_pos = MiscGameplayFunctions.GetSteamPosition( GetHierarchyParent() );
                //TODO set steam position to pot (proxy) memory point (new hierarchy needed)
                //m_ParticleCooking = Particle.Create( particle_id, this, local_pos );
                m_ParticleCooking = ParticleManager.GetInstance().PlayInWorld( particle_id, local_pos );
                m_ParticlePlaying = particle_id;
            }
        }
    }
References GetGame(), m_ParticleCooking, m_ParticlePlaying, particle_id, ParticleCookingStop(), and ParticleManager().
Referenced by RefreshAudioVisuals().
ParticleCookingStop()
void Inventory_Base::ParticleCookingStop () inline private
Definition at line 216 of file fryingpan.c.
    {
        if ( m_ParticleCooking && GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            m_ParticleCooking.Stop();
            m_ParticleCooking = NULL;
            m_ParticlePlaying = ParticleList.INVALID;
        }
    }
References GetGame(), ParticleList::INVALID, m_ParticleCooking, and m_ParticlePlaying.
Referenced by ParticleCookingStart(), and RemoveAudioVisuals().
PlayDeployLoopSound()
void Inventory_Base::PlayDeployLoopSound () inline private
Definition at line 265 of file hescobox.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( !m_DeployLoopSound || !m_DeployLoopSound.IsSoundPlaying() )
            {
                m_DeployLoopSound = SEffectManager.PlaySound( GetLoopDeploySoundset(), GetPosition() );
            }
        }
    }
References GetGame(), GetLoopDeploySoundset(), GetPosition, EffectSound::IsSoundPlaying(), m_DeployLoopSound, and SEffectManager::PlaySound().
Referenced by OnVariablesSynchronized().
RefreshAudioVisuals()
void Inventory_Base::RefreshAudioVisuals (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
Definition at line 145 of file fryingpan.c.
    {
        string sound_name;
        int particle_id;
        //if at least one of the food items is burned
        if ( is_burned )
        {
            sound_name      = SOUND_BURNING_DONE;
            particle_id     = PARTICLE_BURNING_DONE;
        }
        //proper cooking methods
        else
        {
            if ( cooking_method == CookingMethodType.BAKING )
            {
                if ( is_done )                                          //DONE
                {
                    sound_name      = SOUND_BAKING_DONE;
                    particle_id     = PARTICLE_BAKING_DONE;
                }
                else                                                    //START
                {
                    sound_name      = SOUND_BAKING_START;
                    particle_id     = PARTICLE_BAKING_START;
                }
            }
            else if ( cooking_method == CookingMethodType.DRYING )
            {
                if ( is_done )                                          //DONE
                {
                    sound_name      = SOUND_DRYING_DONE;
                    particle_id     = PARTICLE_DRYING_DONE;
                }
                else                                                    //START
                {
                    sound_name      = SOUND_DRYING_START;
                    particle_id     = PARTICLE_DRYING_START;
                }
            }
        }
        //play effects
        ParticleCookingStart( particle_id );
        SoundCookingStart( sound_name );
    }
References PARTICLE_BAKING_DONE, PARTICLE_BAKING_START, PARTICLE_BURNING_DONE, PARTICLE_DRYING_DONE, PARTICLE_DRYING_START, particle_id, ParticleCookingStart(), SOUND_BAKING_DONE, SOUND_BAKING_START, SOUND_BURNING_DONE, SOUND_DRYING_DONE, SOUND_DRYING_START, and SoundCookingStart().
Referenced by OnVariablesSynchronized().
RefreshAudioVisualsOnClient()
void Inventory_Base::RefreshAudioVisualsOnClient (CookingMethodType cooking_method, bool is_done, bool is_empty, bool is_burned) inline private
Definition at line 134 of file fryingpan.c.
    {
        m_CookingMethod     = cooking_method;
        m_CookingIsDone     = is_done;
        m_CookingIsEmpty    = is_empty;
        m_CookingIsBurned   = is_burned;
        //synchronize
        Synchronize();
    }
References m_CookingIsBurned, m_CookingIsDone, m_CookingIsEmpty, m_CookingMethod, and Synchronize().
RefreshPhysics()
override void Inventory_Base::RefreshPhysics () inline private
Definition at line 147 of file hescobox.c.
    {
        super.RefreshPhysics();
        if ( this  &&  !ToDelete() )
        {
            RemoveProxyPhysics( "inventory" );
            RemoveProxyPhysics( "placing" );
            RemoveProxyPhysics( "filled" );
            int state = GetState();
            switch (state)
            {
                case UNFOLDED:
                    //ShowSelection( "placing" );
                    AddProxyPhysics( "placing" );
                return;
                case FOLDED:
                    AddProxyPhysics( "inventory" );
                return;
                case FILLED:
                    AddProxyPhysics( "filled" );
                return;
            }
        }
    }
References AddProxyPhysics(), FILLED, FOLDED, GetState(), RemoveProxyPhysics(), ToDelete(), and UNFOLDED.
Referenced by Fill(), Fold(), and Unfold().
RefreshVisuals()
void Inventory_Base::RefreshVisuals () inline private
Definition at line 70 of file hescobox.c.
    {
    }
Referenced by OnVariablesSynchronized().
RemoveAudioVisuals()
void Inventory_Base::RemoveAudioVisuals () inline private
Definition at line 192 of file fryingpan.c.
    {
        ParticleCookingStop();
        SoundCookingStop();
    }
References ParticleCookingStop(), and SoundCookingStop().
Referenced by EEDelete(), and OnVariablesSynchronized().
RemoveAudioVisualsOnClient()
void Inventory_Base::RemoveAudioVisualsOnClient () inline private
Definition at line 126 of file fryingpan.c.
    {
        m_CookingMethod = CookingMethodType.NONE;
        //synchronize
        Synchronize();
    }
References m_CookingMethod, and Synchronize().
SeedPackBase()
void Inventory_Base::SeedPackBase () inline private
Definition at line 5 of file seedpackbase.c.
    {
    }
SetActions() [1/10]
override void Inventory_Base::SetActions () inline private
Definition at line 3 of file hammer.c.
    {
        super.SetActions();
        AddAction(ActionRepairPart);
        AddAction(ActionMineRock1H);
        AddAction(ActionBuildPart);
    }
References AddAction().
SetActions() [2/10]
override void Inventory_Base::SetActions () inline private
Definition at line 285 of file hescobox.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionFoldObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), and AddAction().
SetActions() [3/10]
override void Inventory_Base::SetActions () inline private
Definition at line 85 of file fryingpan.c.
    {
        super.SetActions();
        AddAction(ActionCreateIndoorFireplace);
        AddAction(ActionCreateIndoorOven);
        AddAction(ActionAttach);
        AddAction(ActionDetach);
    }
References ActionAttach(), ActionDetach(), and AddAction().
SetActions() [4/10]
override void Inventory_Base::SetActions () inline private
Definition at line 43 of file mosin_bayonet.c.
    {
        super.SetActions();
        AddAction(ActionBurnSewTarget);
        AddAction(ActionUnrestrainTarget);
        AddAction(ActionBurnSewSelf);
        AddAction(ActionDigWorms);
    }
References AddAction().
SetActions() [5/10]
override void Inventory_Base::SetActions () inline private
Definition at line 84 of file plantmaterial.c.
    {
        super.SetActions();
        AddAction(ActionFertilizeSlot);
    }
References AddAction().
SetActions() [6/10]
override void Inventory_Base::SetActions () inline private
Definition at line 43 of file sks_bayonet.c.
    {
        super.SetActions();
        AddAction(ActionBurnSewTarget);
        AddAction(ActionUnrestrainTarget);
        AddAction(ActionSkinning);
        AddAction(ActionMineBush);
        AddAction(ActionMineTreeBark);
        AddAction(ActionBurnSewSelf);
        AddAction(ActionDigWorms);
        AddAction(ActionShaveTarget);
        AddAction(ActionShave);
    }
References AddAction().
SetActions() [7/10]
override void Inventory_Base::SetActions () inline private
Definition at line 3 of file pipewrench.c.
    {
        super.SetActions();
        //AddAction(ActionDismantlePart);
        //AddAction(ActionRepairCarEngine);
        AddAction(ActionMineRock);
    }
References AddAction().
SetActions() [8/10]
override void Inventory_Base::SetActions () inline private
Definition at line 40 of file seedpackbase.c.
    {
        super.SetActions();
        AddAction(ActionEmptySeedsPack);
    }
References AddAction().
SetActions() [9/10]
override void Inventory_Base::SetActions () inline private
Definition at line 3 of file sledgehammer.c.
    {
        super.SetActions();
        AddAction(ActionClapBearTrapWithThisItem);
        AddAction(ActionMineRock);
        AddAction(ActionDismantlePart);
        AddAction(ActionBuildPart);
        //AddAction(ActionDestroyPart);
    }
References AddAction().
SetActions() [10/10]
override void Inventory_Base::SetActions () inline private
Definition at line 113 of file xmaslights.c.
    {
        super.SetActions();
        AddAction(ActionAttachOnProxy);
        AddAction(ActionPlugIn);
        AddAction(ActionUnplugThisByCord);
    }
References AddAction().
SetState()
void Inventory_Base::SetState (int state) inline private
Definition at line 79 of file hescobox.c.
    {
        m_State = state;
    }
References m_State.
Referenced by Arm(), Disarm(), Fill(), Fold(), MakeRingingStart(), MakeRingingStop(), OnIgnitedThis(), OnInventoryEnter(), and Unfold().
SoundCookingStart()
protected void Inventory_Base::SoundCookingStart (string sound_name) inline private
Definition at line 226 of file fryingpan.c.
    {
        if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            if ( m_SoundPlaying != sound_name )
            {
                //stop previous sound
                SoundCookingStop();
                //create new
                m_SoundCooking = PlaySoundLoop( sound_name, 50 );
                m_SoundPlaying = sound_name;
            }
        }
    }
References GetGame(), m_SoundCooking, m_SoundPlaying, PlaySoundLoop(), and SoundCookingStop().
Referenced by RefreshAudioVisuals().
SoundCookingStop()
protected void Inventory_Base::SoundCookingStop () inline private
Definition at line 241 of file fryingpan.c.
    {
        if ( m_SoundCooking )
        {
            GetGame().ObjectDelete( m_SoundCooking );
            m_SoundCooking = NULL;
            m_SoundPlaying = "";
        }
    }
References GetGame(), m_SoundCooking, m_SoundPlaying, and CGame::ObjectDelete().
Referenced by RemoveAudioVisuals(), and SoundCookingStart().
StopDeployLoopSound()
void Inventory_Base::StopDeployLoopSound () inline private
Definition at line 276 of file hescobox.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            m_DeployLoopSound.SetSoundFadeOut(0.5);
            m_DeployLoopSound.SoundStop();
        }
    }
References GetGame(), m_DeployLoopSound, EffectSound::SetSoundFadeOut(), and EffectSound::SoundStop().
Referenced by OnVariablesSynchronized().
Synchronize() [1/2]
void Inventory_Base::Synchronize () inline private
Definition at line 42 of file hescobox.c.
    {
        SetSynchDirty();
    }
Referenced by Fill(), Fold(), RefreshAudioVisualsOnClient(), RemoveAudioVisualsOnClient(), and Unfold().
Synchronize() [2/2]
void Inventory_Base::Synchronize () inline private
Definition at line 103 of file fryingpan.c.
    {
        if ( GetGame() && GetGame().IsServer() )
        {
            SetSynchDirty();
        }
    }
References GetGame().
TurnOffItem()
void Inventory_Base::TurnOffItem (ItemBase item) inline private
Definition at line 78 of file xmaslights.c.
    {
        if ( item != NULL )
        {
            item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_r"), "dz\\gear\\camping\\data\\christmass_ligths_string.rvmat" );
            item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_g"), "dz\\gear\\camping\\data\\christmass_ligths_string.rvmat" );
            item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_b"), "dz\\gear\\camping\\data\\christmass_ligths_string.rvmat" );
            item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_y"), "dz\\gear\\camping\\data\\christmass_ligths_string.rvmat" );
            item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_r"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
            item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_g"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
            item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_b"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
            item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_y"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
            //item.SetPilotLight(false);
        }
    }
Referenced by OnWorkStop(), TurnOnItem(), and XmasLights().
TurnOnItem()
void Inventory_Base::TurnOnItem (ItemBase item) inline private
Definition at line 55 of file xmaslights.c.
    {
        if ( item != NULL )
        {
            if ( GetCompEM().IsWorking() )
            {
                item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_r"), "dz\\gear\\camping\\data\\christmas_lights_red_on.rvmat" );
                item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_g"), "dz\\gear\\camping\\data\\christmas_lights_green_on.rvmat" );
                item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_b"), "dz\\gear\\camping\\data\\christmas_lights_blue_on.rvmat" );
                item.SetObjectMaterial( item.GetHiddenSelectionIndex("xlights_glass_y"), "dz\\gear\\camping\\data\\christmas_lights_yellow_on.rvmat" );
                item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_r"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
                item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_g"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
                item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_b"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
                item.SetObjectTexture( item.GetHiddenSelectionIndex("xlights_glass_y"), "dz\\gear\\camping\\data\\christmas_lights_string_ca.paa" );
                //item.SetPilotLight(true);
            }
            else
            {
                TurnOffItem( item );
            }
        }
    }
References TurnOffItem().
Referenced by AttachToObject(), DetachFromObject(), and OnWorkStart().
Unfold()
void Inventory_Base::Unfold () inline private
Definition at line 122 of file hescobox.c.
    {
        this.HideSelection( "inventory" );
        this.ShowSelection( "placing" );
        this.HideSelection( "filled" );
        SetState( UNFOLDED );
        RefreshPhysics();
        if ( GetGame().IsServer() )
        {
            SetAllowDamage(true);
            Synchronize();
            float unfold_damage = ( GetMaxHealth( "", "" ) / 100 ) * PERCENTUAL_DAMAGE;
            DecreaseHealth( "", "", unfold_damage );
        }
    }
References DecreaseHealth(), GetGame(), GetMaxHealth(), RefreshPhysics(), SetAllowDamage(), SetState(), and Synchronize().
Referenced by OnPlacementComplete(), and OnStoreLoad().
XmasLights()
void Inventory_Base::XmasLights () inline private
Definition at line 5 of file xmaslights.c.
    {
        TurnOffItem( this );
    }
References TurnOffItem().
Member Data Documentation
FILLED
const int Inventory_Base::FILLED = 2 static private
Definition at line 5 of file hescobox.c.
Referenced by OnStoreLoad(), and RefreshPhysics().
FOLDED
const int Inventory_Base::FOLDED = 0 static private
Definition at line 3 of file hescobox.c.
Referenced by HescoBox(), OnStoreLoad(), and RefreshPhysics().
m_AttachedTo
private ItemBase Inventory_Base::m_AttachedTo = NULL private
Definition at line 3 of file xmaslights.c.
m_CookingIsBurned
protected bool Inventory_Base::m_CookingIsBurned private
Definition at line 7 of file fryingpan.c.
m_CookingIsDone
protected bool Inventory_Base::m_CookingIsDone private
Definition at line 5 of file fryingpan.c.
m_CookingIsEmpty
protected bool Inventory_Base::m_CookingIsEmpty private
Definition at line 6 of file fryingpan.c.
m_CookingMethod
protected CookingMethodType Inventory_Base::m_CookingMethod private
Definition at line 4 of file fryingpan.c.
m_DeployLoopSound
ref protected EffectSound Inventory_Base::m_DeployLoopSound private
Definition at line 9 of file hescobox.c.
m_ParticleCooking
protected Particle Inventory_Base::m_ParticleCooking private
Definition at line 10 of file fryingpan.c.
m_ParticlePlaying
protected int Inventory_Base::m_ParticlePlaying = ParticleList.INVALID private
Definition at line 11 of file fryingpan.c.
m_SoundCooking
protected SoundOnVehicle Inventory_Base::m_SoundCooking private
Definition at line 22 of file fryingpan.c.
m_SoundPlaying
protected string Inventory_Base::m_SoundPlaying = "" private
Definition at line 23 of file fryingpan.c.
m_State
protected int Inventory_Base::m_State private
Definition at line 11 of file hescobox.c.
Referenced by GetState(), GetState(), and OnVariablesSynchronized().
m_Timer
ref Timer Inventory_Base::m_Timer private
Definition at line 8 of file hescobox.c.
PACK_DAMAGE_TOLERANCE
private const float Inventory_Base::PACK_DAMAGE_TOLERANCE = 0.5 static private
Definition at line 3 of file seedpackbase.c.
PARTICLE_BAKING_DONE
protected int Inventory_Base::PARTICLE_BAKING_DONE = ParticleList.COOKING_BAKING_DONE private
Definition at line 14 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BAKING_START
protected int Inventory_Base::PARTICLE_BAKING_START = ParticleList.COOKING_BAKING_START private
Definition at line 13 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_BURNING_DONE
protected int Inventory_Base::PARTICLE_BURNING_DONE = ParticleList.COOKING_BURNING_DONE private
Definition at line 19 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_DONE
protected int Inventory_Base::PARTICLE_DRYING_DONE = ParticleList.COOKING_DRYING_DONE private
Definition at line 17 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
PARTICLE_DRYING_START
protected int Inventory_Base::PARTICLE_DRYING_START = ParticleList.COOKING_DRYING_START private
Definition at line 16 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
PERCENTUAL_DAMAGE
const int Inventory_Base::PERCENTUAL_DAMAGE = 1 static private
Definition at line 6 of file hescobox.c.
SOUND_BAKING_DONE
const string Inventory_Base::SOUND_BAKING_DONE = "bakeDone" private
Definition at line 26 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
SOUND_BAKING_START
const string Inventory_Base::SOUND_BAKING_START = "bake" private
Definition at line 25 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
SOUND_BURNING_DONE
const string Inventory_Base::SOUND_BURNING_DONE = "burned" private
Definition at line 31 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_DONE
const string Inventory_Base::SOUND_DRYING_DONE = "dryDone" private
Definition at line 29 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
SOUND_DRYING_START
const string Inventory_Base::SOUND_DRYING_START = "dry" private
Definition at line 28 of file fryingpan.c.
Referenced by RefreshAudioVisuals().
UNFOLDED
const int Inventory_Base::UNFOLDED = 1 static private
Definition at line 4 of file hescobox.c.
Referenced by OnStoreLoad(), and RefreshPhysics().