DayzKode: ClientKickedModule Class Reference
ClientKickedModule Class Reference
Private Member Functions
void ClientKickedModule ()
override void FillErrorDataMap ()
override void InitOptionalVariables ()
Detailed Description
Definition at line 174 of file clientkickedmodule.c.
Constructor & Destructor Documentation
ClientKickedModule()
void ClientKickedModule::ClientKickedModule () inline private
Definition at line 176 of file clientkickedmodule.c.
    {
        SetCategory(ErrorCategory.ClientKicked);
    }
Member Function Documentation
FillErrorDataMap()
override void ClientKickedModule::FillErrorDataMap () inline private
Definition at line 189 of file clientkickedmodule.c.
    {
        super.FillErrorDataMap();
        InsertDialogueErrorProperties(EClientKicked.SERVER_EXIT,                        "#STR_server_shutdown");
        InsertDialogueErrorProperties(EClientKicked.KICK_ALL_ADMIN,                     "#STR_kickAll_admin");
        InsertDialogueErrorProperties(EClientKicked.KICK_ALL_SERVER,                    "#STR_kickAll_server");
        InsertDialogueErrorProperties(EClientKicked.TIMEOUT,                            "#STR_MP_TIMEOUT_CLIENT");
        InsertErrorProperties(EClientKicked.LOGOUT); // No handling, just register it exists
        InsertDialogueErrorProperties(EClientKicked.KICK,                               "");
        InsertDialogueErrorProperties(EClientKicked.BAN,                                "#STR_MP_BANNED_CLIENT");
        InsertDialogueErrorProperties(EClientKicked.PING,                               "#STR_MP_MAX_PING");
        InsertSplitDialogueErrorProperties(EClientKicked.MODIFIED_DATA,                 "#STR_modified_data" + VERIFY, "#STR_modified_data");
        InsertSplitDialogueErrorProperties(EClientKicked.UNSTABLE_NETWORK,              "#STR_unstable_network_client", "#STR_unstable_network_server");
        InsertDialogueErrorProperties(EClientKicked.SERVER_SHUTDOWN,                    "#STR_server_shutdown");
        InsertDialogueErrorProperties(EClientKicked.NOT_WHITELISTED,                    "#multi_server_not_whitelisted_message");
        InsertDialogueErrorProperties(EClientKicked.NO_IDENTITY,                        "#STR_no_identity");
        InsertDialogueErrorProperties(EClientKicked.INVALID_UID,                        "#STR_invalid_UID");
        InsertSplitDialogueErrorProperties(EClientKicked.BANK_COUNT,                    "#STR_bank_count" + VERIFY, "#STR_bank_count");
        InsertDialogueErrorProperties(EClientKicked.ADMIN_KICK,                         "#STR_admin_kick");
        InsertDialogueErrorProperties(EClientKicked.INVALID_ID,                         "#STR_invalid_ID");
        InsertDialogueErrorProperties(EClientKicked.INPUT_HACK,                         "#STR_INPUT_HACK");
        InsertErrorProperties(EClientKicked.QUIT); // No handling, just register it exists
        InsertErrorProperties(EClientKicked.LEAVE); // No handling, just register it exists
        // LoginMachine kicks
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.LOGIN_MACHINE_ERROR,              "#server_browser_error_unknown", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.PLAYER_STATE_TIMEOUT,             "#STR_player_state_timeout", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.IDENTITY_NOT_CREATED,             "#STR_identity_not_created", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DUPLICATE_UID,                    "#STR_duplicate_UID", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_PING_RESPONSE,                 "#STR_db_ping_response", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_IDENTITY,                      "#STR_db_identity", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_TIMEOUT,                       "#STR_db_timeout", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_BAD_VERSION,                   "#STR_db_bad_version", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_ERROR,                         "#STR_db_error", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_APP_ERROR,                     "#STR_app_error", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_APP_EXIT,                      "#STR_app_exit", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_BAD_DATA,                      "#menu_character_check_fail", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.DB_GET_RESPONSE,                  "#STR_db_get_response", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NO_PLAYER,                        "#STR_no_player", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.CREATE_NEW_CLIENT,                "#STR_create_new_client", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.CREATE_LOADED_CHAR,               "#STR_create_loaded_char", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.LOAD_LOADED_CHAR,                 "#STR_load_loaded_char", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NO_NETWORK_INFO,                  "#STR_no_network_info", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.CREATE_READY_CLIENT,              "#STR_create_ready_client", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.RECONNECT_INFO,                   "#STR_reconnect_info", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.RECONNECT_IDENTITY,               "#STR_reconnect_identity", LOGIN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.RECONNECT_CHAR,                   "#STR_reconnect_char", LOGIN_PREFIX);
        // RespawnMachine Kicks
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.INIT_RESPAWN_IDENTITY,            "#STR_init_respawn_identity", RESPAWN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.RESPAWN_IDENTITY,                 "#STR_respawn_identity", RESPAWN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NEW_RESPAWN_NETWORK,              "#STR_new_respawn_network", RESPAWN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NEW_RESPAWN_IDENTITY,             "#STR_new_respawn_identity", RESPAWN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NEW_RESPAWN_INFO,                 "#STR_new_respawn_info", RESPAWN_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.RESPAWN_NEW_CLIENT,               "#STR_respawn_new_client", RESPAWN_PREFIX);
        // PlayerVerification Kicks
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.PLAYER_VERIFICATION,          "#server_browser_error_unknown", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.NO_INFO,                      "#STR_no_info", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.BROKEN_DATA,                  "#STR_broken_data", VE_PREFIX);
        // VerificationError
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VERIFICATION_ERROR,           "#server_browser_error_unknown", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_UNKNOWN,                   "#server_browser_error_unknown", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_DECOMPRESS,                "#STR_ve_decompress", VE_PREFIX);
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.VE_MISSING_MOD,          "#STR_ve_missing_mod" + MODS, VE_PREFIX, "#STR_ve_missing_mod");
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.VE_EXTRA_MOD,            "#STR_ve_extra_mod" + MODS, VE_PREFIX, "#STR_ve_extra_mod");
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_CLIENT_CORRUPT,            "#STR_ve_client_corrupt" + VERIFY, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_SERVER_CORRUPT,            "#STR_ve_server_corrupt", VE_PREFIX);
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.VE_UNEXPECTED_MOD_PBO,   "#STR_ve_unexpected_mod_pbo0"+"\n"+"#STR_ve_unexpected_mod_pbo1"+"\n"+"#STR_ve_unexpected_mod_pbo2"+"\n"+"#STR_ve_unexpected_mod_pbo3"+"\n", VE_PREFIX, "#STR_ve_unexpected_mod_pbo0");
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.VE_UM_ROGUE_PBO,         "#STR_ve_unexpected_mod_pbo0"+"\n"+"#STR_ve_unexpected_mod_pbo1"+"\n"+"#STR_ve_unexpected_mod_pbo2"+"\n"+"#STR_ve_unexpected_mod_pbo3"+"\n", VE_PREFIX, "#STR_ve_unexpected_mod_pbo0");
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_UM_CLIENT_UPDATED,         "#STR_ve_um_client_updated" + SERVER_MUST_UPDATE, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_UM_SERVER_UPDATED,         "#STR_ve_um_server_updated" + CLIENT_MUST_UPDATE, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_UNEXPECTED_SOURCE,         "#STR_ve_unexpected_source", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_PATCHED_PBO,               "#STR_ve_patched_pbo" + VERIFY, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_INTEGRITY,                 "#STR_ve_integrity" + VERIFY, VE_PREFIX);
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.VE_MISSING_BISIGN,       "#STR_ve_missing_bising" + VERIFY, VE_PREFIX, "#STR_ve_missing_bising");
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_MISSING_PBO,               "#STR_ve_missing_pbo", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_ROGUE_PBO,               "#STR_ve_m_rogue_pbo0"+"\n"+"#STR_ve_m_rogue_pbo1", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_CLIENT_UPDATED,          "#STR_ve_m_client_updated" + SERVER_MUST_UPDATE, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_SERVER_UPDATED,          "#STR_ve_m_server_updated0"+"\n"+"#STR_ve_m_server_updated1" + CLIENT_MUST_UPDATE, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_SERVER_CORRUPT,          "#STR_ve_m_server_corrupt0"+"\n"+"#STR_ve_m_server_corrupt1"+"\n", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_CLIENT_CORRUPT,          "#STR_ve_m_client_corrupt0"+"\n"+"#STR_ve_m_client_corrupt1" + VERIFY, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_M_UNEXPECTED_SOURCE,       "#STR_ve_m_unexpected_source", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.VE_GPROJ,                     VERIFY + " (.gproj)", VE_PREFIX);
        // PBO Mismatch
        InsertExtendedPrefixSplitDialogueErrorProperties(EClientKicked.PBO_MISMATCH,            "#STR_pbo_mismatch" + VERIFY, VE_PREFIX, "#STR_pbo_mismatch");
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.PBO_VERSION_MISMATCH,         "#STR_pbo_version_mismatch", VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.PBO_CLIENT_UPDATED,           "#STR_pbo_client_updated" + SERVER_MUST_UPDATE, VE_PREFIX);
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.PBO_SERVER_UPDATED,           "#STR_pbo_server_updated" + CLIENT_MUST_UPDATE, VE_PREFIX);
        // AuthError Kicks
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_ERROR,                   "#server_browser_error_unknown", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_NO_USER,                 "#STR_auth_no_user", AUTH_PREFIX);
        // Steam Validate
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_STEAM_VALIDATE,  "#server_browser_error_unknown", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_NO_SERVER,               "#STR_auth_no_server", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_TICKET,          "#STR_auth_invalid_ticket", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_DUPLICATE_REQUEST,       "#STR_auth_duplicate_request", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_VERSION,         "#STR_auth_invalid_version", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_GAME_MISMATCH,           "#STR_auth_game_mismatch", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_EXPIRED_TICKET,          "#STR_auth_expired_ticket", AUTH_PREFIX);
        // Steam OnValidate
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_STEAM_ONVALIDATE,"#server_browser_error_unknown", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_USER_NOT_CONNECTED,      "#STR_auth_user_not_connected", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_LICENCE,                 "#STR_auth_licence", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_SERVICE_BAN,             "#STR_auth_service_ban", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_LOGGED_IN_ELSEWHERE,     "#STR_auth_logged_in_elsewhere", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_TIMEOUT,                 "#STR_auth_timeout", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_CANCELED,                "#STR_auth_cancelled", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_ALREADY_USED,            "#STR_auth_already_used", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_TICKET_INVALID,          "#STR_auth_ticket_invalid", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_PUBLISHER_BAN,           "#STR_auth_publisher_ban", AUTH_PREFIX);
        // Bios Validate
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_BIOS_VALIDATE,   "#server_browser_error_unknown", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_BIOS_REQUEST_CREATE,     "#STR_auth_bios_request_create", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_BIOS_REQUEST_SEND,       "#STR_auth_bios_request_send", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_BIOS_REQUEST_WAIT,       "#STR_auth_bios_request_wait", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_UNKNOWN_BIOS_VALIDATE,   "#server_browser_error_unknown", AUTH_PREFIX);
        // Bios OnValidate
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_INVALID_BIOS_ONVALIDATE, "#server_browser_error_unknown", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_BIOS_WRONG_RESPONSE,     "#STR_auth_bios_wrong_response", AUTH_PREFIX);
        InsertPrefixDialogueErrorProperties(EClientKicked.AUTH_UNKNOWN_BIOS_ONVALIDATE, "#server_browser_error_unknown", AUTH_PREFIX);
        // BattlEye Kicks
        InsertExtendedPrefixDialogueErrorProperties(EClientKicked.BATTLEYE, "", "BattlEye\n");
        // Unauthorized Network Message
        InsertDialogueErrorProperties(EClientKicked.UNM1, UNM_MESSAGE);
        InsertDialogueErrorProperties(EClientKicked.UNM2, UNM_MESSAGE);
        InsertDialogueErrorProperties(EClientKicked.UNM3, UNM_MESSAGE);
        InsertDialogueErrorProperties(EClientKicked.UNM4, UNM_MESSAGE);
        InsertDialogueErrorProperties(EClientKicked.UNM5, UNM_MESSAGE);
        InsertDialogueErrorProperties(EClientKicked.UNM6, UNM_MESSAGE);
    }
References AUTH_PREFIX, CLIENT_MUST_UPDATE, InsertDialogueErrorProperties(), InsertErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), InsertSplitDialogueErrorProperties(), LOGIN_PREFIX, MODS, RESPAWN_PREFIX, SERVER_MUST_UPDATE, UNM_MESSAGE, VE_PREFIX, and VERIFY.
InitOptionalVariables()
override void ClientKickedModule::InitOptionalVariables () inline private
Definition at line 181 of file clientkickedmodule.c.
    {
        super.InitOptionalVariables();
        m_Header = "#menu_warning";
        m_Prefix = "#STR_MP_KICKED_CLIENT\n";
    }
References m_Header, and m_Prefix.