DayzKode: ActionTakeHybridAttachment Class Reference
ActionTakeHybridAttachment Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionTakeHybridAttachment ()
override bool CanBeUsedOnBack ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool InventoryReservation (ActionData action_data)
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Private Attributes
string m_ItemName = ""
Detailed Description
Definition at line 2 of file actiontakehybridattachment.c.
Constructor & Destructor Documentation
ActionTakeHybridAttachment()
void ActionTakeHybridAttachment::ActionTakeHybridAttachment () inline private
Definition at line 6 of file actiontakehybridattachment.c.
    {
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_PICKUP_INVENTORY;
        m_CommandUIDProne   = DayZPlayerConstants.CMD_ACTIONFB_PICKUP_INVENTORY;
        m_Text = "#take";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionTakeHybridAttachment::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 29 of file actiontakehybridattachment.c.
    {
        EntityAI tgt_entity = EntityAI.Cast( target.GetObject() );
        if ( tgt_entity && BaseBuildingBase.Cast(tgt_entity) &&!tgt_entity.IsBeingPlaced() )
        {
            string component_name = tgt_entity.GetActionComponentName( target.GetComponentIndex() );
            /*if (!tgt_entity.GetInventory().HasInventorySlot(InventorySlots.GetSlotIdFromString(component_name)))
                return false;*/
            ItemBase attachment = ItemBase.Cast(tgt_entity.FindAttachmentBySlotName(component_name));
            if ( attachment && player.GetInventory().CanAddEntityIntoInventory(attachment) && attachment.IsTakeable() )
            {
                return true;
            }
        }
        return false;
    }
References ItemBase::IsTakeable().
ActionConditionContinue()
override bool ActionTakeHybridAttachment::ActionConditionContinue (ActionData action_data) inline private
Definition at line 24 of file actiontakehybridattachment.c.
    {
        return true;
    }
CanBeUsedOnBack()
override bool ActionTakeHybridAttachment::CanBeUsedOnBack () inline private
Definition at line 50 of file actiontakehybridattachment.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionTakeHybridAttachment::CreateConditionComponents () inline private
Definition at line 13 of file actiontakehybridattachment.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionTakeHybridAttachment::HasProneException () inline private
Definition at line 19 of file actiontakehybridattachment.c.
    {
        return true;
    }
InventoryReservation()
override bool ActionTakeHybridAttachment::InventoryReservation (ActionData action_data) inline private
Definition at line 55 of file actiontakehybridattachment.c.
    {
        bool success = true;
        InventoryLocation il = new InventoryLocation;
        EntityAI tgt_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        string component_name = tgt_entity.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
        ItemBase attachment;
        if ( tgt_entity && ItemBase.CastTo(attachment, tgt_entity.FindAttachmentBySlotName(component_name)) )
        {
            action_data.m_Player.GetInventory().FindFreeLocationFor( attachment , FindInventoryLocationType.ANY, il );
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( attachment, il) )
            {
                success = false;
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( attachment, il, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if ( success )
        {
            if( il )
                action_data.m_ReservedInventoryLocations.Insert(il);
        }
        return success;
    }
References ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteClient()
override void ActionTakeHybridAttachment::OnExecuteClient (ActionData action_data) inline private
Definition at line 119 of file actiontakehybridattachment.c.
    {
        //Debug.Log("[Action DEBUG] Start time stamp: " + action_data.m_Player.GetSimulationTimeStamp());
        EntityAI tgt_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        string component_name = tgt_entity.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
        ItemBase attachment;
        if ( tgt_entity && ItemBase.CastTo(attachment, tgt_entity.FindAttachmentBySlotName(component_name)) )
        {
            InventoryLocation il = action_data.m_ReservedInventoryLocations.Get(0);
            InventoryLocation targetInventoryLocation = new InventoryLocation;
            attachment.GetInventory().GetCurrentInventoryLocation(targetInventoryLocation);
            ClearInventoryReservationEx(action_data);
            //SplitItemUtils.TakeOrSplitToInventoryLocation( action_data.m_Player, il );
            //action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
            float stackable = attachment.GetTargetQuantityMax(il.GetSlot());
            if( stackable == 0 || stackable >= attachment.GetQuantity() )
            {
                action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
            }
            else
            {
                attachment.SplitIntoStackMaxToInventoryLocationClient( il );
            }
        }
    }
References ClearInventoryReservationEx(), InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
OnExecuteServer()
override void ActionTakeHybridAttachment::OnExecuteServer (ActionData action_data) inline private
Definition at line 87 of file actiontakehybridattachment.c.
    {
        if (GetGame().IsMultiplayer())
            return;
        //Debug.Log("[Action DEBUG] Start time stamp: " + action_data.m_Player.GetSimulationTimeStamp());
        EntityAI tgt_entity = EntityAI.Cast( action_data.m_Target.GetObject() );
        string component_name = tgt_entity.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
        ItemBase attachment;
        if ( tgt_entity && ItemBase.CastTo(attachment, tgt_entity.FindAttachmentBySlotName(component_name)) )
        {
            InventoryLocation il = action_data.m_ReservedInventoryLocations.Get(0);
            InventoryLocation targetInventoryLocation = new InventoryLocation;
            attachment.GetInventory().GetCurrentInventoryLocation(targetInventoryLocation);
            ClearInventoryReservationEx(action_data);
            //SplitItemUtils.TakeOrSplitToInventoryLocation( action_data.m_Player, il );
            float stackable = attachment.GetTargetQuantityMax(il.GetSlot());
            if( stackable == 0 || stackable >= attachment.GetQuantity() )
            {
                action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
            }
            else
            {
                attachment.SplitIntoStackMaxToInventoryLocationClient( il );
            }
        }
        //action_data.m_Player.PredictiveTakeToDst(targetInventoryLocation, il);
    }
References ClearInventoryReservationEx(), GetGame(), InventoryLocation::GetSlot(), ActionData::m_Player, ActionData::m_ReservedInventoryLocations, and ActionData::m_Target.
Member Data Documentation
m_ItemName
string ActionTakeHybridAttachment::m_ItemName = "" private
Definition at line 4 of file actiontakehybridattachment.c.