DayzKode: Mission Class Reference
Mission Class Reference
Mission class.
Private Member Functions
void AbortMission ()
void AddActiveInputExcludes (array< string > excludes)
void AddActiveInputRestriction (int restrictor)
void AddDummyPlayerToScheduler (Man player)
void Continue ()
void CreateDebugMonitor ()
void CreateLogoutMenu (UIMenuPanel parent)
UIScriptedMenu CreateScriptedMenu (int id)
UIScriptedWindow CreateScriptedWindow (int id)
void EnableAllInputs (bool bForceSupress=false)
array< vector > GetActiveRefresherLocations ()
int GetControlDisabledMode ()
GameplayEffectWidgets_base GetEffectWidgets ()
Hud GetHud ()
ImageWidget GetMicrophoneIcon ()
WidgetFadeTimer GetMicWidgetFadeTimer ()
UIScriptedMenu GetNoteMenu ()
ScriptInvoker GetOnInputDeviceChanged ()
ScriptInvoker GetOnInputPresetChanged ()
int GetRespawnModeClient ()
map< int, ref WidgetFadeTimer > GetVoiceLevelTimers ()
map< int, ImageWidget > GetVoiceLevelWidgets ()
WorldData GetWorldData ()
WorldLighting GetWorldLighting ()
void HideChat ()
void HideCrosshairVisibility ()
void HideInventory ()
void HideVoiceLevelWidgets ()
bool InsertCorpse (Man player)
bool IsControlDisabled ()
bool IsGame ()
bool IsInputExcludeActive (string exclude)
bool IsInputRestrictionActive (int restriction)
bool IsMissionGameplay ()
bool IsPaused ()
bool IsPlayerDisconnecting (Man player)
bool IsPlayerRespawning ()
bool IsServer ()
bool IsVoNActive ()
void OnEvent (EventType eventTypeId, Param params)
void OnGameplayDataHandlerLoad ()
void OnInit ()
void OnItemUsed (InventoryItem item, Man owner)
void OnKeyPress (int key)
void OnKeyRelease (int key)
void OnMissionFinish ()
void OnMissionStart ()
void OnMouseButtonPress (int button)
void OnMouseButtonRelease (int button)
void OnPlayerRespawned (Man player)
void OnUpdate (float timeslice)
void Pause ()
void PlayerControlDisable (int mode)
deprecated
void PlayerControlEnable (bool bForceSupress)
void RefreshCrosshairVisibility ()
void RefreshExcludes ()
void RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress=false)
deprecated
void RemoveActiveInputRestriction (int restrictor)
void Reset ()
void ResetGUI ()
void SetNoteMenu (UIScriptedMenu menu)
void SetPlayerRespawning (bool state)
void SetRespawnModeClient (int mode)
for client-side usage
void SetVoNActive (bool active)
void ShowChat ()
void ShowInventory ()
void StartLogoutMenu (int time)
void SyncRespawnModeInfo (PlayerIdentity identity)
server-side
void UpdateVoiceLevelWidgets (int level)
private void ~Mission ()
Private Attributes
ref array< vector > m_ActiveRefresherLocations
protected ref ScriptInvoker m_OnInputDeviceChanged = new ScriptInvoker()
protected ref ScriptInvoker m_OnInputPresetChanged = new ScriptInvoker()
ScriptModule MissionScript
Detailed Description
Mission class.
Definition at line 660 of file gameplay.c.
Constructor & Destructor Documentation
~Mission()
private void Mission::~Mission () private
Member Function Documentation
AbortMission()
void Mission::AbortMission () inline private
Definition at line 731 of file gameplay.c.
{}
Referenced by DisconnectSessionScript(), UIScriptedMenu::Exit(), UIScriptedMenu::OnClick(), BiosSessionService::OnGetSessionError(), BiosUserManager::OnJoin(), UIScriptedMenu::OnModalResult(), BiosUserManager::OnSignedOut(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::SelectUserEx(), and BiosSessionService::TryGetSession().
AddActiveInputExcludes()
void Mission::AddActiveInputExcludes (array< string > excludes) private
Referenced by CreateGamepadDisconnectMenu(), MissionBase::HandleMapToggleByKeyboardShortcut(), ScriptedWidgetEventHandler::OnMouseEnter(), ManBase::OnRPC(), UIScriptedMenu::OnShow(), ActionUnfoldMapCB::PerformMapChange(), PluginBase::ToggleScriptConsole(), and UIScriptedMenu::WarningMenuBase().
AddActiveInputRestriction()
void Mission::AddActiveInputRestriction (int restrictor) private
Referenced by MissionBase::HandleMapToggleByKeyboardShortcut(), and ActionUnfoldMapCB::PerformMapChange().
AddDummyPlayerToScheduler()
void Mission::AddDummyPlayerToScheduler (Man player) inline private
Definition at line 681 of file gameplay.c.
{}
Referenced by ManBase::OnSpawnedFromConsole().
Continue()
void Mission::Continue () inline private
Definition at line 729 of file gameplay.c.
{}
Referenced by UIScriptedMenu::Cancel(), UIScriptedMenu::Exit(), and UIScriptedMenu::GameRespawn().
CreateDebugMonitor()
void Mission::CreateDebugMonitor () inline private
Definition at line 736 of file gameplay.c.
{}
Referenced by DebugMonitorValues::ReceiveValue().
CreateLogoutMenu()
void Mission::CreateLogoutMenu (UIMenuPanel parent) inline private
Definition at line 733 of file gameplay.c.
{}
CreateScriptedMenu()
UIScriptedMenu Mission::CreateScriptedMenu (int id) inline private
Definition at line 693 of file gameplay.c.
    {
        return NULL;
    }
Referenced by CreateScriptedMenu().
CreateScriptedWindow()
UIScriptedWindow Mission::CreateScriptedWindow (int id) inline private
Definition at line 698 of file gameplay.c.
    {
        return NULL;
    }
Referenced by UIManager::OpenWindow().
EnableAllInputs()
void Mission::EnableAllInputs (bool bForceSupress = false) private
Referenced by UIScriptedMenu::OnClick(), ManBase::OnSelectPlayer(), and UIScriptedMenu::~ScriptConsole().
GetActiveRefresherLocations()
array< vector > Mission::GetActiveRefresherLocations () private
Referenced by ManBase::IsTargetInActiveRefresherRange().
GetControlDisabledMode()
int Mission::GetControlDisabledMode () inline private
Definition at line 748 of file gameplay.c.
{}
GetEffectWidgets()
GameplayEffectWidgets_base Mission::GetEffectWidgets () inline private
Definition at line 801 of file gameplay.c.
{}
Referenced by ScriptedWidgetEventHandler::Apply(), BleedingSourcesManagerBase::Init(), ManBase::OnPlayerLoaded(), PPERequester_GameplayBase::OnStart(), PPERequester_GameplayBase::OnStop(), PPERequester_GameplayBase::OnUpdate(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), SetNVPostprocess(), StartSourceBleedingIndication(), StopSourceBleedingIndication(), and GameplayEffectsData::Update().
GetHud()
Hud Mission::GetHud () inline private
Definition at line 686 of file gameplay.c.
    {
        return NULL;
    }
Referenced by PluginBase::DisplayTendency(), ScriptedWidgetEventHandler::GetHud(), HandleDamageHit(), UIScriptedMenu::HudShow(), ManBase::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::InspectItem(), UIScriptedMenu::NoteMenu(), OnHide(), OnShow(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), UIScriptedMenu::ScriptConsole(), PluginBase::SetBadge(), PluginBase::SetStamina(), PluginBase::SetStance(), PluginBase::SwitchPermanentCrossHair(), ScriptedWidgetEventHandler::Update(), UpdateSpecialtyMeter(), VirtualHud(), UIScriptedMenu::~InGameMenuXbox(), UIScriptedMenu::~InspectMenuNew(), UIScriptedMenu::~NoteMenu(), and UIScriptedMenu::~ScriptConsole().
GetMicrophoneIcon()
ImageWidget Mission::GetMicrophoneIcon () inline private
Definition at line 794 of file gameplay.c.
    {
        return null;
    }
Referenced by IsVonToggled(), and ShowVoiceNotification().
GetMicWidgetFadeTimer()
WidgetFadeTimer Mission::GetMicWidgetFadeTimer () inline private
Definition at line 799 of file gameplay.c.
{}
Referenced by ShowVoiceNotification().
GetNoteMenu()
UIScriptedMenu Mission::GetNoteMenu () inline private
Definition at line 778 of file gameplay.c.
{};
GetOnInputDeviceChanged()
ScriptInvoker Mission::GetOnInputDeviceChanged () inline private
Definition at line 807 of file gameplay.c.
    {
        if (!m_OnInputDeviceChanged)
        {
            m_OnInputDeviceChanged = new ScriptInvoker;
        }
        return m_OnInputDeviceChanged;
    }
References m_OnInputDeviceChanged.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), ServerBrowserTab::Construct(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), and Input::OnLastInputDeviceChanged().
GetOnInputPresetChanged()
ScriptInvoker Mission::GetOnInputPresetChanged () inline private
Definition at line 817 of file gameplay.c.
    {
        if (!m_OnInputPresetChanged)
        {
            m_OnInputPresetChanged = new ScriptInvoker;
        }
        return m_OnInputPresetChanged;
    }
References m_OnInputPresetChanged.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), UIScriptedMenu::GesturesMenu(), UIScriptedMenu::InGameMenuXbox(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), UIScriptedMenu::OnClick(), UIScriptedMenu::PerformSwitchPreset(), UIScriptedMenu::RadialQuickbarMenu(), and SwitchPreset().
GetRespawnModeClient()
int Mission::GetRespawnModeClient () inline private
Definition at line 787 of file gameplay.c.
    {
        return -1;
    }
GetVoiceLevelTimers()
map< int, ref WidgetFadeTimer > Mission::GetVoiceLevelTimers () inline private
Definition at line 805 of file gameplay.c.
{}
Referenced by ShowVoiceNotification().
GetVoiceLevelWidgets()
map< int, ImageWidget > Mission::GetVoiceLevelWidgets () inline private
Definition at line 803 of file gameplay.c.
{}
Referenced by ShowVoiceNotification().
GetWorldData()
WorldData Mission::GetWorldData () inline private
Definition at line 703 of file gameplay.c.
    {
        return NULL;
    }
Referenced by ContaminatedArea_Dynamic::EEOnCECreate(), and WeatherPhenomenon::OnBeforeChange().
GetWorldLighting()
WorldLighting Mission::GetWorldLighting () inline private
Definition at line 708 of file gameplay.c.
    {
        return NULL;
    }
Referenced by ManBase::UpdateLighting().
HideChat()
void Mission::HideChat () inline private
Definition at line 766 of file gameplay.c.
{}
Referenced by UIScriptedMenu::OnHide().
HideCrosshairVisibility()
void Mission::HideCrosshairVisibility () inline private
Definition at line 740 of file gameplay.c.
{}
HideInventory()
void Mission::HideInventory () inline private
Definition at line 763 of file gameplay.c.
{}
Referenced by Dispatcher::MissionGameplayHideInventory(), ClothingBase::OnWasAttached(), InventoryActionHandler::SetAction(), and UpdateInterval().
HideVoiceLevelWidgets()
void Mission::HideVoiceLevelWidgets () inline private
Definition at line 769 of file gameplay.c.
{}
Referenced by IsVonToggled(), and UIScriptedMenu::OnHide().
InsertCorpse()
bool Mission::InsertCorpse (Man player) inline private
Definition at line 773 of file gameplay.c.
    {
        return false;
    }
IsControlDisabled()
bool Mission::IsControlDisabled () inline private
Definition at line 747 of file gameplay.c.
{}
IsGame()
bool Mission::IsGame () inline private
Definition at line 718 of file gameplay.c.
    {
        return false;
    }
IsInputExcludeActive()
bool Mission::IsInputExcludeActive (string exclude) private
IsInputRestrictionActive()
bool Mission::IsInputRestrictionActive (int restriction) private
IsMissionGameplay()
bool Mission::IsMissionGameplay () inline private
Definition at line 742 of file gameplay.c.
    {
        return false;
    }
IsPaused()
bool Mission::IsPaused () inline private
Definition at line 713 of file gameplay.c.
    {
        return false;
    }
Referenced by OnUpdate().
IsPlayerDisconnecting()
bool Mission::IsPlayerDisconnecting (Man player) private
Referenced by ActionRestrainTarget::ActionConditionContinue().
IsPlayerRespawning()
bool Mission::IsPlayerRespawning () private
IsServer()
bool Mission::IsServer () inline private
Definition at line 723 of file gameplay.c.
    {
        return false;
    }
IsVoNActive()
bool Mission::IsVoNActive () inline private
Definition at line 770 of file gameplay.c.
{}
Referenced by OnEvent().
OnEvent()
void Mission::OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 679 of file gameplay.c.
{}
Referenced by OnEvent().
OnGameplayDataHandlerLoad()
void Mission::OnGameplayDataHandlerLoad () inline private
Definition at line 684 of file gameplay.c.
{}
Referenced by CfgGameplayHandler::OnLoaded().
OnInit()
void Mission::OnInit () inline private
Definition at line 671 of file gameplay.c.
{}
OnItemUsed()
void Mission::OnItemUsed (InventoryItem item, Man owner) inline private
Definition at line 680 of file gameplay.c.
{}
OnKeyPress()
void Mission::OnKeyPress (int key) inline private
Definition at line 675 of file gameplay.c.
{}
Referenced by OnKeyPress().
OnKeyRelease()
void Mission::OnKeyRelease (int key) inline private
Definition at line 676 of file gameplay.c.
{}
Referenced by OnKeyRelease().
OnMissionFinish()
void Mission::OnMissionFinish () inline private
Definition at line 673 of file gameplay.c.
{}
OnMissionStart()
void Mission::OnMissionStart () inline private
Definition at line 672 of file gameplay.c.
{}
OnMouseButtonPress()
void Mission::OnMouseButtonPress (int button) inline private
Definition at line 677 of file gameplay.c.
{}
Referenced by OnMouseButtonPress().
OnMouseButtonRelease()
void Mission::OnMouseButtonRelease (int button) inline private
Definition at line 678 of file gameplay.c.
{}
Referenced by OnMouseButtonRelease().
OnPlayerRespawned()
void Mission::OnPlayerRespawned (Man player) private
Referenced by ManBase::OnPlayerLoaded().
OnUpdate()
void Mission::OnUpdate (float timeslice) inline private
Definition at line 674 of file gameplay.c.
{}
Referenced by OnUpdate().
Pause()
void Mission::Pause () inline private
Definition at line 728 of file gameplay.c.
{}
Referenced by CheckDialogs().
PlayerControlDisable()
void Mission::PlayerControlDisable (int mode) private
deprecated
PlayerControlEnable()
void Mission::PlayerControlEnable (bool bForceSupress) private
RefreshCrosshairVisibility()
void Mission::RefreshCrosshairVisibility () inline private
Definition at line 738 of file gameplay.c.
{}
Referenced by DeveloperFreeCamera::DisableFreeCamera(), DeveloperFreeCamera::EnableFreeCamera(), and DeveloperFreeCamera::OnSetFreeCameraEvent().
RefreshExcludes()
void Mission::RefreshExcludes () private
RemoveActiveInputExcludes()
void Mission::RemoveActiveInputExcludes (array< string > excludes, bool bForceSupress = false) private
deprecated
Referenced by ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), DeleteGamepadDisconnectMenu(), UIScriptedMenu::OnHide(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseLeave(), ManBase::OnRestrainStart(), PluginBase::ToggleScriptConsole(), ActionUnfoldMapCB::~ActionUnfoldMapCB(), UIScriptedMenu::~GesturesMenu(), UIScriptedMenu::~RadialQuickbarMenu(), and UIScriptedMenu::~WarningMenuBase().
RemoveActiveInputRestriction()
void Mission::RemoveActiveInputRestriction (int restrictor) private
Referenced by ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), ManBase::OnRestrainStart(), and ActionUnfoldMapCB::~ActionUnfoldMapCB().
Reset()
void Mission::Reset () inline private
Definition at line 682 of file gameplay.c.
{}
Referenced by Input::OnGamepadIdentification(), and BiosUserManager::OnUserPicked().
ResetGUI()
void Mission::ResetGUI () inline private
Definition at line 683 of file gameplay.c.
{}
Referenced by ScriptedWidgetEventHandler::Apply(), ManBase::OnSelectPlayer(), and PluginBase::ResetGUI().
SetNoteMenu()
void Mission::SetNoteMenu (UIScriptedMenu menu) inline private
Definition at line 779 of file gameplay.c.
{};
SetPlayerRespawning()
void Mission::SetPlayerRespawning (bool state) private
Referenced by ManBase::OnPlayerLoaded().
SetRespawnModeClient()
void Mission::SetRespawnModeClient (int mode) private
for client-side usage
Referenced by ManBase::OnGameplayDataHandlerSync().
SetVoNActive()
void Mission::SetVoNActive (bool active) inline private
Definition at line 771 of file gameplay.c.
{}
Referenced by OnEvent().
ShowChat()
void Mission::ShowChat () inline private
Definition at line 765 of file gameplay.c.
{}
ShowInventory()
void Mission::ShowInventory () inline private
Definition at line 762 of file gameplay.c.
{}
StartLogoutMenu()
void Mission::StartLogoutMenu (int time) inline private
Definition at line 734 of file gameplay.c.
{}
SyncRespawnModeInfo()
void Mission::SyncRespawnModeInfo (PlayerIdentity identity) inline private
server-side
Definition at line 792 of file gameplay.c.
{};
Referenced by ManBase::EEKilled(), and ManBase::OnSelectPlayer().
UpdateVoiceLevelWidgets()
void Mission::UpdateVoiceLevelWidgets (int level) inline private
Definition at line 767 of file gameplay.c.
{}
Referenced by UpdateVoiceLevel().
Member Data Documentation
m_ActiveRefresherLocations
ref array<vector> Mission::m_ActiveRefresherLocations private
Definition at line 664 of file gameplay.c.
Referenced by BaseBuildingBase::HandleRefreshers(), BaseBuildingBase::InsertRefresherPosition(), and BaseBuildingBase::RemoveRefresherPosition().
m_OnInputDeviceChanged
protected ref ScriptInvoker Mission::m_OnInputDeviceChanged = new ScriptInvoker() private
Definition at line 666 of file gameplay.c.
Referenced by GetOnInputDeviceChanged().
m_OnInputPresetChanged
protected ref ScriptInvoker Mission::m_OnInputPresetChanged = new ScriptInvoker() private
Definition at line 667 of file gameplay.c.
Referenced by GetOnInputPresetChanged().
MissionScript
ScriptModule Mission::MissionScript private
Definition at line 662 of file gameplay.c.