DayzKode: BarbedWireTrigger Class Reference
BarbedWireTrigger Class Reference
DEPRECATED UNUSED prototype for damage by BarbedWire, do not use as example.
Private Member Functions
override void OnEnter (Object obj)
void SetParentObject (ItemBase wire)
void SoundCollision ()
void SoundElectricShock ()
Private Attributes
ItemBase m_ParentBarbedWire
Static Private Attributes
static const string m_SoundsCollision [SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"}
static const string m_SoundsShock [SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"}
static const int SOUNDS_COLLISION_COUNT = 4
static const int SOUNDS_SHOCK_COUNT = 4
Detailed Description
DEPRECATED UNUSED prototype for damage by BarbedWire, do not use as example.
Definition at line 2 of file barbedwiretrigger.c.
Member Function Documentation
OnEnter()
override void BarbedWireTrigger::OnEnter (Object obj) inline private
Definition at line 11 of file barbedwiretrigger.c.
    {
        if ( g_Game.IsServer() )
        {
            if ( m_ParentBarbedWire )
            {
                if ( obj.IsInherited(PlayerBase) )
                {
                    // When a player touches the barbed wire
                    string cfg = "CfgVehicles BarbedWire barbedWireShockEnergyConsumption";
                    float needed_energy = GetGame().ConfigGetFloat(cfg);
                    bool energy_consumed = m_ParentBarbedWire.GetCompEM().ConsumeEnergy(needed_energy);
                    PlayerBase player = PlayerBase.Cast( obj );
                    if ( energy_consumed )
                    {
                        // TO DO:
                        //      -Do electrical damage.
                        //      -Cause bleeding?
                        //      -Do some damage!
                        player.MessageImportant( "*SCRATCH and ELECTROCUTION*" );
                        // Play sound
                        SoundCollision();
                        SoundElectricShock();
                    }
                    else
                    {
                        // TO DO:
                        //      -Cause bleeding?
                        //      -Do some damage!
                        player.MessageImportant( "*SCRATCH*" );
                        // Play sound
                        SoundCollision();
                    }
                }
                else
                {
                    // When an AI Agent touches the barbed wire
                    if ( obj.IsInherited(ManBase) )
                    {
                        ManBase AI_unit = ManBase.Cast( obj );
                        AI_unit.SetHealth("", "", 0);
                    }
                }
            }
        }
    }
References CGame::ConfigGetFloat(), g_Game, GetGame(), m_ParentBarbedWire, SoundCollision(), and SoundElectricShock().
SetParentObject()
void BarbedWireTrigger::SetParentObject (ItemBase wire) inline private
Definition at line 64 of file barbedwiretrigger.c.
    {
        if ( g_Game.IsServer() )
        {
            m_ParentBarbedWire = wire;
        }
    }
References g_Game, and m_ParentBarbedWire.
SoundCollision()
void BarbedWireTrigger::SoundCollision () inline private
Definition at line 81 of file barbedwiretrigger.c.
    {
        int random_index = Math.RandomInt(0, SOUNDS_COLLISION_COUNT);
        string sound_type = m_SoundsCollision[random_index];
        PlaySound(sound_type, 50);
    }
References m_SoundsCollision, PlaySound(), Math::RandomInt(), and SOUNDS_COLLISION_COUNT.
Referenced by OnEnter().
SoundElectricShock()
void BarbedWireTrigger::SoundElectricShock () inline private
Definition at line 73 of file barbedwiretrigger.c.
    {
        int random_index = Math.RandomInt(0, SOUNDS_SHOCK_COUNT);
        string sound_type = m_SoundsShock[random_index];
        PlaySound(sound_type, 50);
    }
References m_SoundsShock, PlaySound(), Math::RandomInt(), and SOUNDS_SHOCK_COUNT.
Referenced by OnEnter().
Member Data Documentation
m_ParentBarbedWire
ItemBase BarbedWireTrigger::m_ParentBarbedWire private
Definition at line 4 of file barbedwiretrigger.c.
Referenced by OnEnter(), and SetParentObject().
m_SoundsCollision
const string BarbedWireTrigger::m_SoundsCollision[SOUNDS_COLLISION_COUNT] = {"barbedFenceCollision1", "barbedFenceCollision2", "barbedFenceCollision3", "barbedFenceCollision4"} static private
Definition at line 7 of file barbedwiretrigger.c.
Referenced by SoundCollision().
m_SoundsShock
const string BarbedWireTrigger::m_SoundsShock[SOUNDS_SHOCK_COUNT] = {"electricFenceShock1", "electricFenceShock2", "electricFenceShock3", "electricFenceShock4"} static private
Definition at line 8 of file barbedwiretrigger.c.
Referenced by SoundElectricShock().
SOUNDS_COLLISION_COUNT
const int BarbedWireTrigger::SOUNDS_COLLISION_COUNT = 4 static private
Definition at line 5 of file barbedwiretrigger.c.
Referenced by SoundCollision().
SOUNDS_SHOCK_COUNT
const int BarbedWireTrigger::SOUNDS_SHOCK_COUNT = 4 static private
Definition at line 6 of file barbedwiretrigger.c.
Referenced by SoundElectricShock().