DayzKode: AreaDamageEvents Class Reference
AreaDamageEvents Class Reference
Events used across AreaDamage API, calling of these needs to be handled by parent.
Private Member Functions
void OnTriggerCreated ()
void OnTriggerDestroyed ()
Called when a trigger is destroyed.
void OnEnterBeginEvent (TriggerInsider insider)
void OnEnterServerEvent (TriggerInsider insider)
void OnEnterClientEvent (TriggerInsider insider)
void OnEnterEndEvent (TriggerInsider insider)
void OnStayStartBeginEvent (int nrOfInsiders)
void OnStayStartServerEvent (int nrOfInsiders)
void OnStayStartClientEvent (int nrOfInsiders)
void OnStayStartEndEvent (int nrOfInsiders)
void OnStayBeginEvent (TriggerInsider insider, float deltaTime)
void OnStayServerEvent (TriggerInsider insider, float deltaTime)
void OnStayClientEvent (TriggerInsider insider, float deltaTime)
void OnStayEndEvent (TriggerInsider insider, float deltaTime)
void OnStayFinishBeginEvent ()
void OnStayFinishServerEvent ()
void OnStayFinishClientEvent ()
void OnStayFinishEndEvent ()
void OnLeaveBeginEvent (TriggerInsider insider)
void OnLeaveServerEvent (TriggerInsider insider)
void OnLeaveClientEvent (TriggerInsider insider)
void OnLeaveEndEvent (TriggerInsider insider)
protected bool OnEvaluateDamage (TriggerInsider insider, float damageCoef)
protected void PreDamageActions ()
protected void PostDamageActions ()
Called after an object was damaged (only when it actually damaged an object)
Detailed Description
Events used across AreaDamage API, calling of these needs to be handled by parent.
Definition at line 2 of file areadamageevents.c.
Member Function Documentation
OnEnterBeginEvent()
void AreaDamageEvents::OnEnterBeginEvent (TriggerInsider insider) inline private
Called when an object enters the trigger
Definition at line 13 of file areadamageevents.c.
{}
OnEnterClientEvent()
void AreaDamageEvents::OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 15 of file areadamageevents.c.
{}
OnEnterEndEvent()
void AreaDamageEvents::OnEnterEndEvent (TriggerInsider insider) inline private
Definition at line 16 of file areadamageevents.c.
{}
OnEnterServerEvent()
void AreaDamageEvents::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 14 of file areadamageevents.c.
{}
OnEvaluateDamage()
protected bool AreaDamageEvents::OnEvaluateDamage (TriggerInsider insider, float damageCoef) inline private
Called when an object gets evaluated for taking damage
Definition at line 53 of file areadamageevents.c.
{ return false; }
Referenced by OnEvaluateDamageEx().
OnLeaveBeginEvent()
void AreaDamageEvents::OnLeaveBeginEvent (TriggerInsider insider) inline private
Called when an object leaves the trigger
Definition at line 45 of file areadamageevents.c.
{}
OnLeaveClientEvent()
void AreaDamageEvents::OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 47 of file areadamageevents.c.
{}
OnLeaveEndEvent()
void AreaDamageEvents::OnLeaveEndEvent (TriggerInsider insider) inline private
Definition at line 48 of file areadamageevents.c.
{}
OnLeaveServerEvent()
void AreaDamageEvents::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 46 of file areadamageevents.c.
{}
OnStayBeginEvent()
void AreaDamageEvents::OnStayBeginEvent (TriggerInsider insider, float deltaTime) inline private
Called in the update loop
Definition at line 29 of file areadamageevents.c.
{}
OnStayClientEvent()
void AreaDamageEvents::OnStayClientEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 31 of file areadamageevents.c.
{}
OnStayEndEvent()
void AreaDamageEvents::OnStayEndEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 32 of file areadamageevents.c.
{}
OnStayFinishBeginEvent()
void AreaDamageEvents::OnStayFinishBeginEvent () inline private
Called at the end of an update loop
Definition at line 37 of file areadamageevents.c.
{}
OnStayFinishClientEvent()
void AreaDamageEvents::OnStayFinishClientEvent () inline private
Definition at line 39 of file areadamageevents.c.
{}
OnStayFinishEndEvent()
void AreaDamageEvents::OnStayFinishEndEvent () inline private
Definition at line 40 of file areadamageevents.c.
{}
OnStayFinishServerEvent()
void AreaDamageEvents::OnStayFinishServerEvent () inline private
Definition at line 38 of file areadamageevents.c.
{}
OnStayServerEvent()
void AreaDamageEvents::OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 30 of file areadamageevents.c.
{}
OnStayStartBeginEvent()
void AreaDamageEvents::OnStayStartBeginEvent (int nrOfInsiders) inline private
Called at the beginning of an update loop
Definition at line 21 of file areadamageevents.c.
{}
OnStayStartClientEvent()
void AreaDamageEvents::OnStayStartClientEvent (int nrOfInsiders) inline private
Definition at line 23 of file areadamageevents.c.
{}
OnStayStartEndEvent()
void AreaDamageEvents::OnStayStartEndEvent (int nrOfInsiders) inline private
Definition at line 24 of file areadamageevents.c.
{}
OnStayStartServerEvent()
void AreaDamageEvents::OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 22 of file areadamageevents.c.
{}
OnTriggerCreated()
void AreaDamageEvents::OnTriggerCreated () inline private
Called when a trigger is created
Definition at line 6 of file areadamageevents.c.
{}
Referenced by Spawn().
OnTriggerDestroyed()
void AreaDamageEvents::OnTriggerDestroyed () inline private
Called when a trigger is destroyed.
Definition at line 8 of file areadamageevents.c.
{}
Referenced by Destroy().
PostDamageActions()
protected void AreaDamageEvents::PostDamageActions () inline private
Called after an object was damaged (only when it actually damaged an object)
Definition at line 60 of file areadamageevents.c.
{}
Referenced by EvaluateDamageInternal().
PreDamageActions()
protected void AreaDamageEvents::PreDamageActions () inline private
Called before an object is damaged (only when it actually damaged an object)
Definition at line 58 of file areadamageevents.c.
{}
Referenced by EvaluateDamageInternal().