DayzKode: CargoBase Class Reference
CargoBase Class Reference
represents base for cargo storage for entities
Private Member Functions
bool CanReceiveItemIntoCargo (EntityAI item)
condition EntityAI::CanReceiveItemIntoCargo for Cargo.
bool CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity)
condition EntityAI::CanSwapItemInCargo for Cargo.
private void CargoBase ()
proto native void ClearUserReservedLocation (notnull EntityAI eai)
proto native int FindEntityInCargo (notnull EntityAI e)
proto native EntityAI GetCargoOwner ()
get the entity that owns the cargo
proto native int GetHeight ()
proto native EntityAI GetItem (int index)
proto native int GetItemCount ()
proto bool GetItemRowCol (int index, out int row, out int col)
proto bool GetItemSize (int index, out int w, out int h)
proto native int GetOwnerCargoIndex ()
proto bool GetUserReservedLocation (int index, out EntityAI eai, out int row, out int col, out int w, out int h, out int flp)
proto native int GetUserReservedLocationCount ()
proto native int GetWidth ()
proto native bool IsProxyCargo ()
proto native void SetUserReservedLocation (notnull EntityAI eai)
private void ~CargoBase ()
Detailed Description
represents base for cargo storage for entities
@NOTE: rows == y axis
Definition at line 6 of file cargo.c.
Constructor & Destructor Documentation
CargoBase()
private void CargoBase::CargoBase () private
~CargoBase()
private void CargoBase::~CargoBase () private
Member Function Documentation
CanReceiveItemIntoCargo()
CargoBase::CanReceiveItemIntoCargo (EntityAI item) inline private
condition EntityAI::CanReceiveItemIntoCargo for Cargo.
Returns
true if cargo can be added, false otherwise
Definition at line 65 of file cargo.c.
{ return true; }
CanSwapItemInCargo()
CargoBase::CanSwapItemInCargo (EntityAI child_entity, EntityAI new_entity) inline private
condition EntityAI::CanSwapItemInCargo for Cargo.
Returns
true if cargo can be added, false otherwise
Definition at line 71 of file cargo.c.
{ return true; }
ClearUserReservedLocation()
proto native void CargoBase::ClearUserReservedLocation (notnull EntityAI eai) private
FindEntityInCargo()
CargoBase::FindEntityInCargo (notnull EntityAI e) private
Returns
find internal index of the entity in cargo or -1 if not found
GetCargoOwner()
CargoBase::GetCargoOwner () private
get the entity that owns the cargo
Returns
cargo owner
Referenced by VicinityContainer::UpdateInterval().
GetHeight()
CargoBase::GetHeight () private
Returns
height of the cargo
Referenced by ClosableContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), and Container::GetMaxCargoCapacity().
GetItem()
CargoBase::GetItem (int index) private
Returns
get item at specific index
Referenced by Container::AddedToCargoEx(), BurnItemsInFireplace(), CookWithEquipment(), InventoryItem::EEHealthLevelChanged(), Container::GetIcon(), GetItemTypeFromCargo(), ActionUnpackGift::OnFinishProgressServer(), Container::RemovedFromCargo(), Container::SetEntity(), TerminateCookingSounds(), and InventoryItem::UpdateWeight().
GetItemCount()
CargoBase::GetItemCount () private
Returns
number of items in cargo
Referenced by Container::AddedToCargoEx(), ScriptedWidgetEventHandler::AttachmentsWithInventoryOrCargoCount(), BurnItemsInFireplace(), CookWithEquipment(), ClosableContainer::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), InventoryItem::EEHealthLevelChanged(), Container::GetCargoCapacity(), Container::GetIcon(), GetItemTypeFromCargo(), ActionUnpackGift::OnFinishProgressServer(), Container::RemovedFromCargo(), Container::SetEntity(), TerminateCookingSounds(), and InventoryItem::UpdateWeight().
GetItemRowCol()
CargoBase::GetItemRowCol (int index, out int row, out int col) private
Parameters
[out] row returned row of the item at internal index
[out] col returned col. 0 on xbox
GetItemSize()
CargoBase::GetItemSize (int index, out int w, out int h) private
Parameters
[out] w returned width of the item at internal index
[out] h returned height of the item at internal index
Referenced by Container::GetCargoCapacity().
GetOwnerCargoIndex()
proto native int CargoBase::GetOwnerCargoIndex () private
Referenced by VicinityContainer::UpdateInterval().
GetUserReservedLocation()
CargoBase::GetUserReservedLocation (int index, out EntityAI eai, out int row, out int col, out int w, out int h, out int flp) private
Parameters
[in] idx index of the user reserved location
[out] eai returned entity of the user reservation at internal index
[out] row returned row of the user reservation at internal index
[out] col returned col
[out] w returned width of the user reservation at internal index
[out] h returned height of the user reservation at internal index
[out] flp returned flip
Returns
true if record found, false otherwise
GetUserReservedLocationCount()
proto native int CargoBase::GetUserReservedLocationCount () private
GetWidth()
CargoBase::GetWidth () private
Returns
width of the cargo
Referenced by ClosableContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), and Container::GetMaxCargoCapacity().
IsProxyCargo()
CargoBase::IsProxyCargo () private
Returns
true if cargo is in proxy object
SetUserReservedLocation()
proto native void CargoBase::SetUserReservedLocation (notnull EntityAI eai) private