DayzKode: SmokeGrenadeBase Class Reference
SmokeGrenadeBase Class Reference
Private Member Functions
void M18SmokeGrenade_ColorBase ()
void RDG2SmokeGrenade_ColorBase ()
void ~M18SmokeGrenade_ColorBase ()
void ~RDG2SmokeGrenade_ColorBase ()
Private Attributes
const string SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet"
const string SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet"
const string SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet"
Detailed Description
Definition at line 1 of file m18smokegrenade_colorbase.c.
Constructor & Destructor Documentation
~M18SmokeGrenade_ColorBase()
void SmokeGrenadeBase::~M18SmokeGrenade_ColorBase () inline private
Definition at line 16 of file m18smokegrenade_colorbase.c.
{}
~RDG2SmokeGrenade_ColorBase()
void SmokeGrenadeBase::~RDG2SmokeGrenade_ColorBase () inline private
Definition at line 17 of file rdg2smokegrenade_colorbase.c.
{}
Member Function Documentation
M18SmokeGrenade_ColorBase()
void SmokeGrenadeBase::M18SmokeGrenade_ColorBase () inline private
Definition at line 7 of file m18smokegrenade_colorbase.c.
    {
        SetAmmoType("");
        SetFuseDelay(2);
        SetSoundSmokeStart(SOUND_SMOKE_START);
        SetSoundSmokeLoop(SOUND_SMOKE_LOOP);
        SetSoundSmokeEnd(SOUND_SMOKE_END);
    }
References SetAmmoType(), SetSoundSmokeEnd(), SetSoundSmokeLoop(), SetSoundSmokeStart(), SOUND_SMOKE_END, SOUND_SMOKE_LOOP, and SOUND_SMOKE_START.
RDG2SmokeGrenade_ColorBase()
void SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase () inline private
Definition at line 7 of file rdg2smokegrenade_colorbase.c.
    {
        SetAmmoType("");
        SetFuseDelay(2);
        SetParticlePosition("0 0.1 0");
        SetSoundSmokeStart(SOUND_SMOKE_START);
        SetSoundSmokeLoop(SOUND_SMOKE_LOOP);
        SetSoundSmokeEnd(SOUND_SMOKE_END);
    }
References SetAmmoType(), SetParticlePosition(), SetSoundSmokeEnd(), SetSoundSmokeLoop(), SetSoundSmokeStart(), SOUND_SMOKE_END, SOUND_SMOKE_LOOP, and SOUND_SMOKE_START.
Member Data Documentation
SOUND_SMOKE_END
const string SmokeGrenadeBase::SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet" private
Definition at line 5 of file m18smokegrenade_colorbase.c.
SOUND_SMOKE_LOOP
const string SmokeGrenadeBase::SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet" private
Definition at line 4 of file m18smokegrenade_colorbase.c.
SOUND_SMOKE_START
const string SmokeGrenadeBase::SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet" private
Definition at line 3 of file m18smokegrenade_colorbase.c.