DayzKode: Land_Underground_EntranceBase Class Reference
Land_Underground_EntranceBase Class Reference
Private Member Functions
float AdjustTime (float originalTime, float adjustedTime=-1)
bool CanManipulate (Param param=null)
bool CheckShouldPlayPersistent (EUndegroundEntranceState state, EUndegroundEntranceState lastValidState)
void CleanUpOnClosedClient ()
void CleanUpOnDeleteClient ()
void CreateLights ()
override void EOnPostSimulate (IEntity other, float timeSlice)
void GetConnectedPanels (array< Land_Underground_Panel > panels)
float GetOpeningTime ()
void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void HandleVisualPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
bool IsInitDoorStateSync ()
void Land_Underground_EntranceBase ()
void Manipulate (Param param=null)
void NavmeshUpdate ()
void OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void OnDoorStateChangedServer (EUndegroundEntranceState newState)
void OnFinishedTimerServer ()
void OnUpdateClient (float timeSlice)
void OnUpdateServer ()
override void OnVariablesSynchronized ()
void OpenServer (bool force=false)
void RequestLatentTransition (float time, EUndegroundEntranceState targetState=EUndegroundEntranceState.UNINITIALIZED)
void SetDoorStateServer (EUndegroundEntranceState newState)
void ~Land_Underground_EntranceBase ()
Private Attributes
float m_AnimPhase
ref AnimationTimer m_AnimTimerDoorServer
ref array< Land_Underground_Panel > m_ConnectedPanels
EUndegroundEntranceState m_DoorState = EUndegroundEntranceState.CLOSED
EUndegroundEntranceState m_DoorStatePrev = EUndegroundEntranceState.UNINITIALIZED
EUndegroundDoorType m_DoorType
EntranceLight m_InteriorLight1
EntranceLight m_InteriorLight2
EntranceLight m_InteriorLight3
ref Timer m_NavmeshTimer
Detailed Description
Definition at line 51 of file land_underground_entrance.c.
Constructor & Destructor Documentation
Land_Underground_EntranceBase()
void Land_Underground_EntranceBase::Land_Underground_EntranceBase () inline private
Definition at line 65 of file land_underground_entrance.c.
    {
        m_DoorType = EUndegroundDoorType.MAIN;
        Land_Underground_Panel.RegisterEntrance(this);
        RegisterNetSyncVariableFloat("m_AnimPhase", 0,1,5);
        RegisterNetSyncVariableInt("m_DoorState", 0, EnumTools.GetLastEnumValue(EUndegroundEntranceState));
        #ifndef SERVER
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( CreateLights, 250);
        #endif
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CreateLights(), CGame::GetCallQueue(), GetGame(), EnumTools::GetLastEnumValue(), Land_Underground_Panel(), and m_DoorType.
~Land_Underground_EntranceBase()
void Land_Underground_EntranceBase::~Land_Underground_EntranceBase () inline private
Definition at line 79 of file land_underground_entrance.c.
    {
        Land_Underground_Panel.UnregisterEntrance(this);
        #ifndef SERVER
        CleanUpOnDeleteClient();
        #endif
    }
References CleanUpOnDeleteClient(), and Land_Underground_Panel().
Member Function Documentation
AdjustTime()
float Land_Underground_EntranceBase::AdjustTime (float originalTime, float adjustedTime = -1) inline private
Definition at line 152 of file land_underground_entrance.c.
    {
        #ifdef DEVELOPER
        float timeAccel = 1;
        if (adjustedTime != -1)
        {
            return adjustedTime;
        }
        if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.UNDERGROUND_ENTRANCE))
        {
            timeAccel = FeatureTimeAccel.GetFeatureTimeAccelValue();
            return originalTime / timeAccel;
        }
        #endif
        return originalTime;
    }
Referenced by Land_Underground_Stairs_Exit::GetOpeningTime(), OnDoorStateChangedServer(), Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUpdateServer().
CanManipulate()
bool Land_Underground_EntranceBase::CanManipulate (Param param = null) inline private
Definition at line 98 of file land_underground_entrance.c.
    {
        return m_DoorState == EUndegroundEntranceState.CLOSED;
    }
References m_DoorState.
Referenced by CanInteract().
CheckShouldPlayPersistent()
bool Land_Underground_EntranceBase::CheckShouldPlayPersistent (EUndegroundEntranceState state, EUndegroundEntranceState lastValidState) inline private
Definition at line 147 of file land_underground_entrance.c.
    {
        return m_DoorState == state || ( IsInitDoorStateSync() && m_DoorState > state && m_DoorState <= lastValidState);
    }
References IsInitDoorStateSync(), and m_DoorState.
Referenced by HandleAudioPlayback(), and HandleVisualPlayback().
CleanUpOnClosedClient()
void Land_Underground_EntranceBase::CleanUpOnClosedClient () private
Referenced by CleanUpOnDeleteClient(), and OnDoorStateChangedClient().
CleanUpOnDeleteClient()
void Land_Underground_EntranceBase::CleanUpOnDeleteClient () inline private
Definition at line 89 of file land_underground_entrance.c.
    {
        //anything we might have started playing when the door was activated
        CleanUpOnClosedClient();
    }
References CleanUpOnClosedClient().
Referenced by ~Land_Underground_EntranceBase().
CreateLights()
void Land_Underground_EntranceBase::CreateLights () private
Referenced by Land_Underground_EntranceBase().
EOnPostSimulate()
override void Land_Underground_EntranceBase::EOnPostSimulate (IEntity other, float timeSlice) inline private
Definition at line 115 of file land_underground_entrance.c.
    {
        #ifndef SERVER
        OnUpdateClient(timeSlice);
        #endif
    }
References OnUpdateClient().
GetConnectedPanels()
void Land_Underground_EntranceBase::GetConnectedPanels (array< Land_Underground_Panel > panels) inline private
Definition at line 129 of file land_underground_entrance.c.
    {
        if (!Land_Underground_Panel.m_Panels)
        {
            return;
        }
        foreach (Land_Underground_Panel p:Land_Underground_Panel.m_Panels)
        {
            if (p.GetClosestDoor() == this)
            {
                panels.Insert(p);
            }
        }
    }
References Land_Underground_Panel().
Referenced by OnDoorStateChangedClient().
GetOpeningTime()
float Land_Underground_EntranceBase::GetOpeningTime () inline private
Definition at line 170 of file land_underground_entrance.c.
    {
        return 30;
    }
Referenced by OnDoorStateChangedServer(), and OnUpdateServer().
HandleAudioPlayback()
void Land_Underground_EntranceBase::HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) private
Referenced by OnDoorStateChangedClient().
HandleVisualPlayback()
void Land_Underground_EntranceBase::HandleVisualPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) private
Referenced by OnDoorStateChangedClient().
IsInitDoorStateSync()
bool Land_Underground_EntranceBase::IsInitDoorStateSync () inline private
Definition at line 244 of file land_underground_entrance.c.
    {
        return m_DoorStatePrev == EUndegroundEntranceState.UNINITIALIZED;
    }
References m_DoorStatePrev.
Referenced by CheckShouldPlayPersistent().
Manipulate()
void Land_Underground_EntranceBase::Manipulate (Param param = null) inline private
Definition at line 103 of file land_underground_entrance.c.
    {
        OpenServer();
    }
References OpenServer().
Referenced by Interact().
NavmeshUpdate()
void Land_Underground_EntranceBase::NavmeshUpdate () inline private
Definition at line 108 of file land_underground_entrance.c.
    {
        GetGame().UpdatePathgraphRegionByObject(this);
    }
References GetGame(), and CGame::UpdatePathgraphRegionByObject().
Referenced by OnDoorStateChangedServer().
OnDoorStateChangedClient()
void Land_Underground_EntranceBase::OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) inline private
Definition at line 193 of file land_underground_entrance.c.
    {
        if (newState > EUndegroundEntranceState.CLOSED)
        {
            SetEventMask(EntityEvent.POSTSIMULATE);
        }
        else
        {
            ClearEventMask(EntityEvent.POSTSIMULATE);
            CleanUpOnClosedClient();
        }
        HandleAudioPlayback(newState, prevState);
        HandleVisualPlayback(newState, prevState);
        if (!m_ConnectedPanels)
        {
            m_ConnectedPanels = new array<Land_Underground_Panel>();
            GetConnectedPanels(m_ConnectedPanels);
        }
        foreach (Land_Underground_Panel p:m_ConnectedPanels)
        {
            p.OnDoorStateChangedClient(newState, prevState);
        }
    }
References CleanUpOnClosedClient(), GetConnectedPanels(), HandleAudioPlayback(), HandleVisualPlayback(), Land_Underground_Panel(), and m_ConnectedPanels.
Referenced by OnVariablesSynchronized().
OnDoorStateChangedServer()
void Land_Underground_EntranceBase::OnDoorStateChangedServer (EUndegroundEntranceState newState) private
Referenced by SetDoorStateServer().
OnFinishedTimerServer()
void Land_Underground_EntranceBase::OnFinishedTimerServer () private
OnUpdateClient()
void Land_Underground_EntranceBase::OnUpdateClient (float timeSlice) private
Referenced by EOnPostSimulate().
OnUpdateServer()
void Land_Underground_EntranceBase::OnUpdateServer () inline private
Definition at line 122 of file land_underground_entrance.c.
    {
        m_AnimPhase = m_AnimTimerDoorServer.GetValue() / AdjustTime(GetOpeningTime());// make 0..1
        SetAnimationPhaseNow("EntranceDoor",m_AnimPhase);
        SetSynchDirty();
    }
References AdjustTime(), GetOpeningTime(), AnimationTimer::GetValue(), m_AnimPhase, and m_AnimTimerDoorServer.
OnVariablesSynchronized()
override void Land_Underground_EntranceBase::OnVariablesSynchronized () inline private
Definition at line 233 of file land_underground_entrance.c.
    {
        super.OnVariablesSynchronized();
        if (m_DoorState != m_DoorStatePrev)
        {
            OnDoorStateChangedClient(m_DoorState, m_DoorStatePrev);
            m_DoorStatePrev = m_DoorState;
        }
    }
References m_DoorState, m_DoorStatePrev, and OnDoorStateChangedClient().
OpenServer()
void Land_Underground_EntranceBase::OpenServer (bool force = false) inline private
Definition at line 219 of file land_underground_entrance.c.
    {
        GetGame().RegisterNetworkStaticObject(this);
        if (m_DoorState == EUndegroundEntranceState.CLOSED || force)
        {
            SetDoorStateServer(EUndegroundEntranceState.OPENING_A);
        }
    }
References GetGame(), m_DoorState, CGame::RegisterNetworkStaticObject(), and SetDoorStateServer().
Referenced by Manipulate().
RequestLatentTransition()
void Land_Underground_EntranceBase::RequestLatentTransition (float time, EUndegroundEntranceState targetState = EUndegroundEntranceState.UNINITIALIZED) inline private
Definition at line 175 of file land_underground_entrance.c.
    {
        if (targetState == EUndegroundEntranceState.UNINITIALIZED)
        {
            targetState = m_DoorState + 1;
        }
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( SetDoorStateServer, time * 1000, false, targetState);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_DoorState, and SetDoorStateServer().
Referenced by OnDoorStateChangedServer(), and Land_Underground_Stairs_Exit::OnDoorStateChangedServer().
SetDoorStateServer()
void Land_Underground_EntranceBase::SetDoorStateServer (EUndegroundEntranceState newState) inline private
Definition at line 184 of file land_underground_entrance.c.
    {
        m_DoorState = newState;
        OnDoorStateChangedServer(newState);
        SetSynchDirty();
    }
References m_DoorState, and OnDoorStateChangedServer().
Referenced by OpenServer(), and RequestLatentTransition().
Member Data Documentation
m_AnimPhase
float Land_Underground_EntranceBase::m_AnimPhase private
Definition at line 55 of file land_underground_entrance.c.
Referenced by OnUpdateServer().
m_AnimTimerDoorServer
ref AnimationTimer Land_Underground_EntranceBase::m_AnimTimerDoorServer private
Definition at line 56 of file land_underground_entrance.c.
Referenced by Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), and OnUpdateServer().
m_ConnectedPanels
ref array<Land_Underground_Panel> Land_Underground_EntranceBase::m_ConnectedPanels private
Definition at line 58 of file land_underground_entrance.c.
Referenced by OnDoorStateChangedClient().
m_DoorState
EUndegroundEntranceState Land_Underground_EntranceBase::m_DoorState = EUndegroundEntranceState.CLOSED private
Definition at line 53 of file land_underground_entrance.c.
Referenced by CanManipulate(), CheckShouldPlayPersistent(), OnVariablesSynchronized(), OpenServer(), RequestLatentTransition(), and SetDoorStateServer().
m_DoorStatePrev
EUndegroundEntranceState Land_Underground_EntranceBase::m_DoorStatePrev = EUndegroundEntranceState.UNINITIALIZED private
Definition at line 54 of file land_underground_entrance.c.
Referenced by IsInitDoorStateSync(), and OnVariablesSynchronized().
m_DoorType
EUndegroundDoorType Land_Underground_EntranceBase::m_DoorType private
Definition at line 59 of file land_underground_entrance.c.
Referenced by GetLinkedDoorType(), Land_Underground_EntranceBase(), and Land_Underground_Stairs_Exit::Land_Underground_Stairs_Exit().
m_InteriorLight1
EntranceLight Land_Underground_EntranceBase::m_InteriorLight1 private
Definition at line 61 of file land_underground_entrance.c.
Referenced by Land_Underground_Stairs_Exit::CreateLights().
m_InteriorLight2
EntranceLight Land_Underground_EntranceBase::m_InteriorLight2 private
Definition at line 62 of file land_underground_entrance.c.
Referenced by Land_Underground_Stairs_Exit::CreateLights().
m_InteriorLight3
EntranceLight Land_Underground_EntranceBase::m_InteriorLight3 private
Definition at line 63 of file land_underground_entrance.c.
m_NavmeshTimer
ref Timer Land_Underground_EntranceBase::m_NavmeshTimer private
Definition at line 57 of file land_underground_entrance.c.