DayzKode: TrapBase Class Reference
TrapBase Class Reference
Private Member Functions
void BearTrap ()
override bool CanBeDisarmed ()
void CauseVictimToStartLimping (Object obj, string damagedZone)
override void CreateTrigger ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override string GetLoopDeploySoundset ()
override bool IsDeployable ()
override void OnActivate ()
override void OnDisarm ()
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
protected void OnServerSteppedOn (Object obj, string damageZone)
override void OnSteppedOn (EntityAI victim)
override void OnSteppedOut (EntityAI victim)
override void OnUpdate (EntityAI victim)
void PlaySoundBiteEmpty ()
void PlaySoundBiteLeg ()
void PlaySoundOpen ()
override void SetActions ()
Static Private Attributes
static const vector m_RaycastSources [RAYCAST_SOURCES_COUNT]
static const int RAYCAST_SOURCES_COUNT = 5
Detailed Description
Definition at line 1 of file trap_bear.c.
Member Function Documentation
BearTrap()
void TrapBase::BearTrap () inline private
Definition at line 14 of file trap_bear.c.
    {
        m_DamagePlayers             = 5;                // How much damage player gets when caught
        m_DamageOthers              = 5;                // How much damage other entities(CreatureAI) gets when caught
        m_DefectRate                = 0;
        m_InitWaitTime              = 0;                // After this time after deployment, the trap is activated
        m_AnimationPhaseGrounded    = "placing";
        m_AnimationPhaseSet         = "BearTrap_Set";
        m_AnimationPhaseTriggered   = "placing";
    }
References m_AnimationPhaseGrounded, m_AnimationPhaseSet, m_AnimationPhaseTriggered, m_DamageOthers, m_DamagePlayers, m_DefectRate, and m_InitWaitTime.
CanBeDisarmed()
override bool TrapBase::CanBeDisarmed () inline private
Definition at line 25 of file trap_bear.c.
    {
        return true;
    }
CauseVictimToStartLimping()
void TrapBase::CauseVictimToStartLimping (Object obj, string damagedZone) inline private
Definition at line 181 of file trap_bear.c.
    {
        PlayerBase player;
        ZombieBase zombie;
        if (Class.CastTo(player,obj))
        {
            player.DamageAllLegs(player.GetMaxHealth() * 2); //reduce legs health (not regular DamageSystem damage, does not transfer!)
        }
        else if (Class.CastTo(zombie,obj))
        {
            zombie.SetHealth("LeftLeg","Health",0.0);
            zombie.SetHealth("RightLeg","Health",0.0);
        }
    }
References Class::CastTo().
Referenced by OnServerSteppedOn().
CreateTrigger()
override void TrapBase::CreateTrigger () inline private
Definition at line 43 of file trap_bear.c.
    {
        super.CreateTrigger();
        vector mins     = "-0.1 -0.05 -0.1";
        vector maxs     = "0.1 0.4 0.1";
        m_TrapTrigger.SetOrientation(GetOrientation());
        m_TrapTrigger.SetExtents(mins, maxs);
        m_TrapTrigger.SetParentObject(this);
    }
References GetOrientation(), m_TrapTrigger, Trigger::SetExtents(), and TrapTrigger::SetParentObject().
Referenced by SetActive().
EEHealthLevelChanged()
override void TrapBase::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 30 of file trap_bear.c.
    {
        super.EEHealthLevelChanged(oldLevel, newLevel, zone);
        if (GetGame().IsServer())
        {
            if (newLevel == GameConstants.STATE_RUINED)
            {
                SetInactive();
            }
        }
    }
References GetGame(), SetInactive(), and GameConstants::STATE_RUINED.
GetLoopDeploySoundset()
override string TrapBase::GetLoopDeploySoundset () inline private
Definition at line 251 of file trap_bear.c.
    {
        return "beartrap_deploy_SoundSet";
    }
Referenced by PlayDeployLoopSound().
IsDeployable()
override bool TrapBase::IsDeployable () inline private
Definition at line 246 of file trap_bear.c.
    {
        return true;
    }
OnActivate()
override void TrapBase::OnActivate () inline private
Definition at line 214 of file trap_bear.c.
    {
        #ifndef SERVER
        PlaySoundOpen();
        #endif
    }
References PlaySoundOpen().
Referenced by SetActive().
OnDisarm()
override void TrapBase::OnDisarm () inline private
Definition at line 221 of file trap_bear.c.
    {
        #ifndef SERVER
        PlaySoundBiteEmpty();
        #endif
    }
References PlaySoundBiteEmpty().
Referenced by Disarm(), and OnRPC().
OnPlacementComplete()
override void TrapBase::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 232 of file trap_bear.c.
    {
        super.OnPlacementComplete(player, position, orientation);
        if (GetGame().IsServer())
        {
            PlayerBase player_PB = PlayerBase.Cast(player);
            StartActivate(player_PB);
            m_TrapTrigger.SetPosition(position);
            m_TrapTrigger.SetOrientation(orientation);
        }
    }
References GetGame(), m_TrapTrigger, and StartActivate().
OnServerSteppedOn()
protected void TrapBase::OnServerSteppedOn (Object obj, string damageZone) inline private
Generic limp handling
Definition at line 140 of file trap_bear.c.
    {
        if (obj.IsInherited(CarWheel))
        {
            obj.ProcessDirectDamage(DamageType.CLOSE_COMBAT, this, damageZone, "BearTrapHit_CarWheel", "0 0 0", 1);
            if (m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Stop();
            }
            SetInactive(false);
            Synch(EntityAI.Cast(obj));
            return;
        }
        ZombieBase zombie;
        string zoneUsed = damageZone;
        if (damageZone == "zone_leg_random")
        {
            zoneUsed = "LeftLeg";
            if (Math.RandomIntInclusive(0, 1) == 1)
            {
                zoneUsed = "RightLeg";
            }
        }
        if (obj.IsInherited(PlayerBase) || (Class.CastTo(zombie,obj) && !zombie.IsCrawling() && Math.RandomIntInclusive(0, 1) == 1))
        {
            CauseVictimToStartLimping(obj, "");
        }
        obj.ProcessDirectDamage(DamageType.CLOSE_COMBAT, this, zoneUsed, "BearTrapHit", "0 0 0", 1);
        SetInactive(false);
        Synch(EntityAI.Cast(obj));
    }
References Class::CastTo(), CauseVictimToStartLimping(), m_UpdateTimer, Math::RandomIntInclusive(), SetInactive(), and Synch().
Referenced by OnSteppedOn(), OnUpdate(), and OnUpdate().
OnSteppedOn()
override void TrapBase::OnSteppedOn (EntityAI victim) inline private
CarScript specific reaction on BearTrap
this is also called on client (OnRPC->SnapOn->OnSteppedOn chain)
Definition at line 67 of file trap_bear.c.
    {
        if (GetGame().IsServer() && victim)
        {
            if (!victim.GetAllowDamage())
            {
                return;
            }
            ZombieBase zombie;
            if (victim.IsInherited(CarScript))
            {
                Param1<EntityAI> params = new Param1<EntityAI>(victim);
                m_UpdateTimer.Run(UPDATE_TIMER_INTERVAL, this, "OnUpdate", params, true);
                return;
            }
            else
            {
                for (int i = 0; i < RAYCAST_SOURCES_COUNT; ++i)
                {
                    vector raycast_start_pos            = ModelToWorld(m_RaycastSources[i]);
                    vector raycast_end_pos              = "0 0.5 0" + raycast_start_pos;
                    RaycastRVParams rayInput            = new RaycastRVParams(raycast_start_pos, raycast_end_pos, this);
                    rayInput.flags                      = CollisionFlags.ALLOBJECTS;
                    rayInput.type                       = ObjIntersectFire;
                    rayInput.radius                     = 0.05;
                    array<ref RaycastRVResult> results  = new array<ref RaycastRVResult>;
                    if (DayZPhysics.RaycastRVProxy(rayInput, results))
                    {
                        RaycastRVResult res;
                        for (int j = 0; j < results.Count(); j++)
{
                            Object contact_obj = results[j].obj;
                            if (contact_obj && !contact_obj.IsInherited(ItemBase) && contact_obj.IsAlive())
{
                                OnServerSteppedOn(contact_obj, contact_obj.GetDamageZoneNameByComponentIndex(results[j].component));
                                break;
                            }
                        }
                    }
                }
                OnServerSteppedOn(victim, "zone_leg_random");
            }
        }
        else if (!GetGame().IsDedicatedServer())
        {
            if (victim)
            {
                if (victim.IsInherited(PlayerBase))
                {
                    victim.SpawnDamageDealtEffect();
                }
                PlaySoundBiteLeg();
            }
        }
    }
References RaycastRVParams::flags, GetGame(), m_UpdateTimer, ModelToWorld(), array::obj, OnServerSteppedOn(), PlaySoundBiteLeg(), RaycastRVParams::radius, RAYCAST_SOURCES_COUNT, DayZPhysics::RaycastRVProxy(), RaycastRVParams::type, and UPDATE_TIMER_INTERVAL.
Referenced by SnapOnObject().
OnSteppedOut()
override void TrapBase::OnSteppedOut (EntityAI victim) inline private
Definition at line 129 of file trap_bear.c.
    {
        if (victim.IsInherited(CarScript))
        {
            if (m_UpdateTimer && m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Stop();
            }
        }
    }
References m_UpdateTimer.
Referenced by RemoveFromObject().
OnUpdate()
override void TrapBase::OnUpdate (EntityAI victim) inline private
Definition at line 55 of file trap_bear.c.
    {
        if (victim && victim.IsInherited(CarScript))
        {
            EntityAI wheel = GetClosestCarWheel(victim);
            if (wheel)
            {
                OnServerSteppedOn(wheel, "");
            }
        }
    }
References GetClosestCarWheel(), and OnServerSteppedOn().
PlaySoundBiteEmpty()
void TrapBase::PlaySoundBiteEmpty () inline private
Definition at line 202 of file trap_bear.c.
    {
        EffectSound sound = SEffectManager.PlaySound("beartrapClose_SoundSet", GetPosition(), 0, 0, false);
        sound.SetAutodestroy(true);
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnDisarm().
PlaySoundBiteLeg()
void TrapBase::PlaySoundBiteLeg () inline private
Definition at line 196 of file trap_bear.c.
    {
        EffectSound sound = SEffectManager.PlaySound("beartrapCloseDamage_SoundSet", GetPosition(), 0, 0, false);
        sound.SetAutodestroy(true);
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnSteppedOn().
PlaySoundOpen()
void TrapBase::PlaySoundOpen () inline private
Definition at line 208 of file trap_bear.c.
    {
        EffectSound sound = SEffectManager.PlaySound("beartrapOpen_SoundSet", GetPosition(), 0, 0, false);
        sound.SetAutodestroy(true);
    }
References GetPosition, SEffectManager::PlaySound(), and EffectSound::SetAutodestroy().
Referenced by OnActivate().
SetActions()
override void TrapBase::SetActions () inline private
Definition at line 256 of file trap_bear.c.
    {
        super.SetActions();
        AddAction(ActionClapBearTrapWithThisItem);
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
    }
References ActionDeployObject(), and AddAction().
Member Data Documentation
m_RaycastSources
const vector TrapBase::m_RaycastSources[RAYCAST_SOURCES_COUNT] static private
Initial value:
= {
        "0.0 0.1 0.0",
        "0.2 0.1 0.2",
        "-.2 0.1 0.2",
        "0.2 0.1 -0.2",
        "-0.2 0.1 -0.2"
    }
Definition at line 6 of file trap_bear.c.
RAYCAST_SOURCES_COUNT
const int TrapBase::RAYCAST_SOURCES_COUNT = 5 static private
Definition at line 3 of file trap_bear.c.
Referenced by OnSteppedOn().