DayzKode: StaminaConsumers Class Reference
StaminaConsumers Class Reference
Private Member Functions
bool HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
bool HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap)
void RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold=-1)
void StaminaConsumers ()
Private Attributes
protected ref map< EStaminaConsumers, ref StaminaConsumer > m_StaminaConsumers
Detailed Description
Definition at line 39 of file staminahandler.c.
Constructor & Destructor Documentation
StaminaConsumers()
void StaminaConsumers::StaminaConsumers () inline private
Definition at line 43 of file staminahandler.c.
    {
        m_StaminaConsumers = new map<EStaminaConsumers, ref StaminaConsumer>;
    }
References m_StaminaConsumers.
Member Function Documentation
HasEnoughStaminaFor()
bool StaminaConsumers::HasEnoughStaminaFor (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap) inline private
Definition at line 63 of file staminahandler.c.
    {
        if ( m_StaminaConsumers && m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = m_StaminaConsumers.Get(consumer);
            if ( consumer != EStaminaConsumers.SPRINT )
            {
                if ( (isDepleted || (curStamina < sc.GetDrainThreshold()/* && curStamina < cap*/)) )
                {
                    sc.SetState(false);
                    return false;
                }
            }
            else
            {
                if( !isDepleted )
                {
                    if ( sc.GetState() )
                    {
                        sc.SetState(true);
                        return true;
                    }
                }
                else
                {
                    sc.SetState(false);
                    return false;
                }
            }
            if ( curStamina > sc.GetDrainThreshold() || curStamina == cap ) //Sometimes player can't go up to drain threshold
            {
                sc.SetState(true);
                return true;
            }
        }
        return false;
    }
References m_StaminaConsumers, and StaminaConsumer().
HasEnoughStaminaToStart()
bool StaminaConsumers::HasEnoughStaminaToStart (EStaminaConsumers consumer, float curStamina, bool isDepleted, float cap) inline private
Definition at line 104 of file staminahandler.c.
    {
        if ( m_StaminaConsumers && m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = m_StaminaConsumers.Get(consumer);
            if( (isDepleted || (curStamina < sc.GetActivationThreshold() && curStamina < cap)) )
            {
                sc.SetState(false);
                return false;
            }
            else
            {
                sc.SetState(true);
                return true;
            }
        }
        return false;
    }
References m_StaminaConsumers, and StaminaConsumer().
RegisterConsumer()
void StaminaConsumers::RegisterConsumer (EStaminaConsumers consumer, float threshold, float depletion_threshold = -1) inline private
init of StaminaConsumer - threshold, state
Definition at line 48 of file staminahandler.c.
    {
        if (depletion_threshold == -1)
        {
            depletion_threshold = threshold;
        }
        if ( !m_StaminaConsumers.Contains(consumer) )
        {
            StaminaConsumer sc = new StaminaConsumer(threshold, depletion_threshold, true);
            m_StaminaConsumers.Set(consumer, sc);
        }
    }
References m_StaminaConsumers, and StaminaConsumer().
Member Data Documentation
m_StaminaConsumers
protected ref map<EStaminaConsumers, ref StaminaConsumer> StaminaConsumers::m_StaminaConsumers private
Definition at line 41 of file staminahandler.c.
Referenced by HasEnoughStaminaFor(), HasEnoughStaminaToStart(), RegisterConsumer(), and StaminaConsumers().