DayzKode: CallQueue Class Reference
CallQueue Class Reference
Tools
DragQueue Class provide callbacks while mouse is dragging. Callback function must have exact arguments:
Private Member Functions
void DragQueue ()
override void Tick ()
System function, don't call it.
Private Attributes
private ref Param3< int, int, bool > m_mouse_params
Detailed Description
DragQueue Class provide callbacks while mouse is dragging. Callback function must have exact arguments:
void AnyFunctionName(int mouse_x, int mouse_y, bool is_dragging);
When mouse button is released, callback function is called one more time with is_dragging = false. Then all callbacks are automatically removed from queue.
usage:
 class XYZ
 {
    void UpdateDrag(int mouse_x, int mouse_y, bool is_dragging);
 }
...
 GetGame().GetDragQueue().Call(this, "UpdateDrag"); // calls "UpdateDrag" function on "this"
Definition at line 153 of file tools.c.
Member Function Documentation
DragQueue()
void CallQueue::DragQueue () inline private
Definition at line 157 of file tools.c.
    {
        m_mouse_params = new Param3<int, int, bool>(0,0,true);
    }
Tick()
override void CallQueue::Tick () inline private
System function, don't call it.
Definition at line 165 of file tools.c.
    {
        if (m_processing) return;
        m_processing = true;
        int last_index = 0;
        int mouse_x;
        int mouse_y;
        bool is_holding = false;
        CallQueueContext ctx;
        if (GetMouseState(MouseState.LEFT) & 0x80000000)
        {
            is_holding = true;
        }
        GetMousePos(mouse_x, mouse_y);
        if (!is_holding || mouse_x != m_mouse_params.param1 || mouse_y != m_mouse_params.param2)
        {
            m_mouse_params.param1 = mouse_x;
            m_mouse_params.param2 = mouse_y;
            m_mouse_params.param3 = is_holding;
            while (Count() > last_index)
            {
                ctx = Get(last_index);
                if (!ctx.IsValid())
                {
                    Remove(last_index);
                }
                else
                {
                    ctx.CallParams(m_mouse_params);
                    last_index++;
                }
            }
        }
        // clear queue when mouse button is released
        if (!is_holding)
        {
            Clear();
        }
        m_processing = false;
    }
References CallQueueContext::CallParams(), Count, Get(), GetMousePos(), GetMouseState(), CallQueueContext::IsValid(), and Remove().
Member Data Documentation
m_mouse_params
private ref Param3<int, int, bool> CallQueue::m_mouse_params private
Definition at line 155 of file tools.c.