DayzKode: ShockDamageMdfr Class Reference
ShockDamageMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int UNCONSIOUSS_COOLDOWN_TIME = 60
Detailed Description
Definition at line 1 of file shockdamage.c.
Member Function Documentation
ActivateCondition()
override bool ShockDamageMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 22 of file shockdamage.c.
    {
        if( !player.IsUnconscious() && player.GetHealth("","Blood") <= PlayerConstants.SHOCK_DAMAGE_BLOOD_THRESHOLD_HIGH && GetGame().GetTime() > (player.m_UnconsciousEndTime + UNCONSIOUSS_COOLDOWN_TIME) )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetGame(), GetTime(), PlayerConstants::SHOCK_DAMAGE_BLOOD_THRESHOLD_HIGH, and UNCONSIOUSS_COOLDOWN_TIME.
Referenced by DeactivateCondition().
DeactivateCondition()
override bool ShockDamageMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 34 of file shockdamage.c.
    {
        return !ActivateCondition(player);
    }
References ActivateCondition().
Init()
override void ShockDamageMdfr::Init () inline private
Definition at line 4 of file shockdamage.c.
    {
        m_TrackActivatedTime    = false;
        m_ID                    = eModifiers.MDF_SHOCK_DAMAGE;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 0.5;
    }
References DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void ShockDamageMdfr::OnActivate (PlayerBase player) inline private
Definition at line 12 of file shockdamage.c.
    {
    }
OnReconnect()
override void ShockDamageMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 17 of file shockdamage.c.
    {
    }
OnTick()
override void ShockDamageMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 40 of file shockdamage.c.
    {
        float blood =  player.GetHealth("","Blood");
        float value = Math.InverseLerp( PlayerConstants.SHOCK_DAMAGE_BLOOD_THRESHOLD_HIGH, PlayerConstants.SHOCK_DAMAGE_BLOOD_THRESHOLD_LOW, blood );
        value = Math.Clamp(value,0,1);
        float dmg = Math.Lerp( PlayerConstants.SHOCK_DAMAGE_HIGH, PlayerConstants.SHOCK_DAMAGE_LOW, value);
        float damage =  -dmg * deltaT;
        player.AddHealth("","Shock", damage);
        //PrintString(damage.ToString());
    }
References Math::Clamp(), Math::InverseLerp(), Math::Lerp(), PlayerConstants::SHOCK_DAMAGE_BLOOD_THRESHOLD_HIGH, PlayerConstants::SHOCK_DAMAGE_BLOOD_THRESHOLD_LOW, PlayerConstants::SHOCK_DAMAGE_HIGH, and PlayerConstants::SHOCK_DAMAGE_LOW.
Member Data Documentation
UNCONSIOUSS_COOLDOWN_TIME
const int ShockDamageMdfr::UNCONSIOUSS_COOLDOWN_TIME = 60 private
Definition at line 3 of file shockdamage.c.
Referenced by ActivateCondition().