DayzKode: ClosableContainer Class Reference
ClosableContainer Class Reference
Private Member Functions
void AttachmentAdded (EntityAI item, string slot, EntityAI parent)
void AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate=true)
void AttachmentRemoved (EntityAI item, string slot, EntityAI parent)
override bool CanCombine ()
override bool CanCombineAmmo ()
override bool CanEquip ()
override void Close ()
void ContainerWithCargo (Container parent, int sort=-1)
void ContainerWithCargoAndAttachments (LayoutHolder parent, int sort=-1)
void DoubleClick (Widget w, int x, int y, int button)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
override void DraggingOver (Widget w, int x, int y, Widget receiver)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever)
bool DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
void DropReceived (Widget w, int x, int y)
void DropReceived (Widget w, int x, int y, CargoContainer cargo)
override bool EquipItem ()
EntityAI GetEntity ()
EntityAI GetEntity ()
override EntityAI GetFocusedContainerEntity ()
override EntityAI GetFocusedContainerEntity ()
EntityAI GetItemPreviewItem (Widget w)
EntityAI GetItemPreviewItem (Widget w)
Widget GetItemPreviewWidget (Widget w)
ItemPreviewWidget GetItemPreviewWidgetDragOrDrop (Widget w)
void HideCargo ()
override bool InspectItem ()
override bool IsDisplayable ()
override bool IsEmpty ()
override bool IsFirstContainerFocused ()
override bool IsFirstContainerFocused ()
override bool IsItemActive ()
override bool IsItemWithQuantityActive ()
override bool IsLastContainerFocused ()
override bool IsLastContainerFocused ()
override bool IsLastIndex ()
override bool IsOpened ()
void LockCargo (bool value)
void MouseClick2 (Widget w, int x, int y, int button)
override void MoveGridCursor (int direction)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
void OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver)
override void Open ()
void RecomputeContainers ()
override void SetDefaultFocus (bool while_micromanagment_mode=false)
void SetEntity (EntityAI entity, bool immedUpdate=true)
void SetEntity (EntityAI entity, int cargo_index=0, bool immedUpdate=true)
void ShowCargo ()
override bool SplitItem ()
void TakeAsAttachment (Widget w, Widget receiver)
void TakeIntoHands (notnull PlayerBase player, notnull EntityAI item)
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void UnfocusAll ()
override void UnfocusAll ()
override void UpdateInterval ()
override void UpdateInterval ()
void ~ContainerWithCargoAndAttachments ()
Private Attributes
protected ref map< EntityAI, ref Attachments > m_AttachmentAttachments
protected ref map< EntityAI, ref AttachmentsWrapper > m_AttachmentAttachmentsContainers
protected ref map< EntityAI, ref CargoContainer > m_AttachmentCargos
protected ref array< int > m_AttachmentSlotsSorted
protected ref Attachments m_Atts
protected ref CargoContainer m_CargoGrid
protected int m_CargoIndex = -1
Detailed Description
Definition at line 1 of file containerwithcargo.c.
Constructor & Destructor Documentation
~ContainerWithCargoAndAttachments()
void ClosableContainer::~ContainerWithCargoAndAttachments () inline private
Definition at line 16 of file containerwithcargoandattachments.c.
    {
        if ( m_Entity )
        {
            m_Entity.GetOnItemAttached().Remove( AttachmentAdded );
            m_Entity.GetOnItemDetached().Remove( AttachmentRemoved );
        }
        if ( m_Atts )
            delete m_Atts;
        foreach ( EntityAI e, Attachments att : m_AttachmentAttachments )
        {
            delete att;
        }
        if ( m_AttachmentAttachments )
            m_AttachmentAttachments.Clear();
        if ( m_AttachmentAttachmentsContainers )
            m_AttachmentAttachmentsContainers.Clear();
        if ( m_AttachmentCargos )
            m_AttachmentCargos.Clear();
    }
References m_Atts, m_Entity, and ScriptedWidgetEventHandler::Remove().
Member Function Documentation
AttachmentAdded()
void ClosableContainer::AttachmentAdded (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 139 of file containerwithcargoandattachments.c.
    {
        AttachmentAddedEx(item, slot, parent);
    }
References AttachmentAddedEx().
AttachmentAddedEx()
void ClosableContainer::AttachmentAddedEx (EntityAI item, string slot, EntityAI parent, bool immedUpdate = true) inline private
Definition at line 77 of file containerwithcargoandattachments.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString( slot );
        int sort = -1;
        bool updateNeeded = false;
        ref Attachments att_cont = null;
        ref CargoContainer cont = null;
        if ( item.GetInventory().GetAttachmentSlotsCount() > 0 && item.CanDisplayAnyAttachmentSlot() )
        {
            updateNeeded = true;
            att_cont = new Attachments( this, item );
            sort = (m_AttachmentSlotsSorted.Find( slot_id ) * 2) + SORT_ATTACHMENTS_NEXT_OFFSET;
            att_cont.InitAttachmentGrid( sort );
            m_AttachmentAttachments.Insert( item, att_cont );
            m_AttachmentAttachmentsContainers.Insert( item, att_cont.GetWrapper() );
            att_cont.UpdateInterval();
        }
        if ( item.GetInventory().GetCargo() )
        {
            updateNeeded = true;
            cont = new CargoContainer( this, true );
            sort = (m_AttachmentSlotsSorted.Find( slot_id ) * 2) + SORT_CARGO_NEXT_OFFSET;
            cont.GetRootWidget().SetSort( sort );
            cont.SetEntity( item, false );
            Insert( cont, m_Atts.GetAttachmentHeight() + m_AttachmentCargos.Count() + 1 );
            m_AttachmentCargos.Insert( item, cont );
        }
        if (updateNeeded)
        {
            if (att_cont)
            {
                att_cont.ShowFalseAttachmentsHeader(true);
                if (cont)
                {
                    cont.ShowFalseCargoHeader(false);
                    cont.UpdateSize();
                    cont.SetAlternateFalseTextHeaderWidget(att_cont.GetFalseHeaderTextWidget());
                }
            }
            else if (cont)
            {
                cont.SetAlternateFalseTextHeaderWidget(null); //just to be safe..
            }
            RecomputeContainers();
            RecomputeOpenedContainers();
            Inventory.GetInstance().UpdateConsoleToolbar();
            if (m_Parent && immedUpdate)
                m_Parent.Refresh();
        }
    }
References InventorySlots::GetSlotIdFromString(), Inventory(), m_Parent, and RecomputeContainers().
Referenced by AttachmentAdded(), and SetEntity().
AttachmentRemoved()
void ClosableContainer::AttachmentRemoved (EntityAI item, string slot, EntityAI parent) inline private
Definition at line 144 of file containerwithcargoandattachments.c.
    {
        int slot_id = InventorySlots.GetSlotIdFromString( slot );
        CargoContainer old_cont = m_AttachmentCargos.Get( item );
        if( old_cont )
        {
            m_AttachmentCargos.Remove( item );
            delete old_cont;
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        AttachmentsWrapper old_att_cont = m_AttachmentAttachmentsContainers.Get( item );
        if( old_att_cont )
        {
            m_AttachmentAttachmentsContainers.Remove( item );
            m_AttachmentAttachments.Remove( item );
            delete old_att_cont;
            if( m_Parent )
                m_Parent.Refresh();
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
        RecomputeContainers();
        RecomputeOpenedContainers();
    }
References Container::Get(), InventorySlots::GetSlotIdFromString(), Inventory(), m_Parent, RecomputeContainers(), and LayoutHolder::Remove().
CanCombine()
override bool ClosableContainer::CanCombine () inline private
Definition at line 42 of file containerwithcargo.c.
    {
        return m_CargoGrid.CanCombine();
    }
CanCombineAmmo()
override bool ClosableContainer::CanCombineAmmo () inline private
Definition at line 47 of file containerwithcargo.c.
    {
        return m_CargoGrid.CanCombineAmmo();
    }
CanEquip()
override bool ClosableContainer::CanEquip () inline private
Definition at line 37 of file containerwithcargo.c.
    {
        return m_CargoGrid.CanEquip();
    }
Close()
override void ClosableContainer::Close () inline private
Definition at line 91 of file containerwithcargo.c.
    {
        if( !m_LockCargo )
        {
            ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), false );
            m_Closed = true;
            SetOpenForSlotIcon(false);
            OnHide();
            m_Parent.m_Parent.Refresh();
        }
        if ( m_SlotIcon )
        {
            m_SlotIcon.GetRadialIconPanel().Show( !m_LockCargo );
        }
    }
References ItemManager::GetInstance(), m_Entity, m_Parent, OnHide(), and ItemManager::SetDefaultOpenState().
Referenced by Container::CloseButtonOnMouseButtonDown(), and AttachmentCategoriesContainer::MouseClick().
ContainerWithCargo()
void ClosableContainer::ContainerWithCargo (Container parent, int sort = -1) inline private
Definition at line 6 of file containerwithcargo.c.
    {
        m_LockCargo = false;
        m_Parent = parent;
        m_CargoGrid = new CargoContainer( this );
        Insert( m_CargoGrid );
        m_CargoGrid.GetRootWidget().SetSort( 1 );
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( m_MainWidget,  this, "DraggingOverGrid" );
        RecomputeOpenedContainers();
    }
References WidgetEventHandler::GetInstance(), m_Parent, and WidgetEventHandler::RegisterOnDraggingOver().
Referenced by AttachmentCategoriesRow::RefreshSlot().
ContainerWithCargoAndAttachments()
void ClosableContainer::ContainerWithCargoAndAttachments (LayoutHolder parent, int sort = -1) inline private
Definition at line 11 of file containerwithcargoandattachments.c.
    {
        WidgetEventHandler.GetInstance().RegisterOnDraggingOver( m_MainWidget,  this, "DraggingOverHeader2" );
    }
References WidgetEventHandler::GetInstance(), and WidgetEventHandler::RegisterOnDraggingOver().
DoubleClick()
void ClosableContainer::DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 680 of file containerwithcargoandattachments.c.
    {
        if( button == MouseState.LEFT )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if( w == NULL || player.GetInventory().IsInventoryLocked() )
            {
                return;
            }
            ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
            if( !iw )
            {
                string name = w.GetName();
                name.Replace( "PanelWidget", "Render" );
                iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
            }
            if( !iw )
            {
                iw = ItemPreviewWidget.Cast( w );
            }
            EntityAI item = iw.GetItem();
            if( !item )
            {
                return;
            }
            SlotsIcon icon;
            iw.GetUserData(icon);
            if(icon && icon.IsReserved())
            {
                return;
            }
            if( !item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
                return;
            if( player.GetInventory().HasEntityInInventory( item ) && player.GetHumanInventory().CanAddEntityInHands( item ) )
            {
                player.PredictiveTakeEntityToHands( item );
            }
            else
            {
                if(player.GetInventory().CanAddEntityToInventory( item ) && item.GetInventory().CanRemoveEntity())
                {
                    player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ANY, InventoryItem.Cast( item ) );
                }
                else
                {
                    if( player.GetHumanInventory().CanAddEntityInHands( item ) )
                    {
                        player.PredictiveTakeEntityToHands( item );
                    }
                }
            }
            HideOwnedTooltip();
            name = w.GetName();
            name.Replace( "PanelWidget", "Temperature" );
            w.FindAnyWidget( name ).Show( false );
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), SlotsIcon::IsReserved(), name, and string::Replace().
DraggingOver() [1/2]
override void ClosableContainer::DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 440 of file containerwithcargo.c.
    {
        if( !w )
            return;
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
            return;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( item.GetInventory().CanRemoveEntity() && player.CanManipulateInventory() && m_Entity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && !m_Entity.GetInventory().HasEntityInCargo( item ) )
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            ItemManager.GetInstance().HideDropzones();
            if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
            {
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else
            {
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
            }
        }
        else
        {
            ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            ItemManager.GetInstance().ShowSourceDropzone( item );
        }
    }
References GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), m_Entity, ColorManager::RED_COLOR, ColorManager::SetColor(), and ItemManager::ShowSourceDropzone().
Referenced by DraggingOverHeader().
DraggingOver() [2/2]
override void ClosableContainer::DraggingOver (Widget w, int x, int y, Widget receiver) inline private
Definition at line 826 of file containerwithcargoandattachments.c.
    {
        DraggingOverHeader( w, x, y, receiver );
    }
References DraggingOverHeader(), x, and y.
DraggingOverGrid() [1/2]
bool ClosableContainer::DraggingOverGrid (Widget w, int x, int y, Widget reciever) inline private
Definition at line 250 of file containerwithcargo.c.
    {
        if( w == null )
        {
            return false;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( !player.CanManipulateInventory() )
        {
            return false;
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return false;
        }
        if( !item.GetInventory().CanRemoveEntity() )
        {
            return false;
        }
        int color, c_x, c_y;
        #ifdef PLATFORM_CONSOLE
        int idx = -1;
        #else
        int idx = 0;
        #endif
        CargoBase cargo = m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex);
        if( cargo )
        {
            c_x = cargo.GetHeight();
            c_y = cargo.GetWidth();
        }
        InventoryLocation dst = new InventoryLocation;
        #ifdef PLATFORM_CONSOLE
        x = 0;
        y = cargo.GetItemCount();
        m_Entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.CARGO, dst );
        #else
        dst.SetCargoAuto(cargo, item, x, y, item.GetInventory().GetFlipCargo());
        #endif
        #ifdef PLATFORM_CONSOLE
        if( dst.IsValid() && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
        #else
        if( m_Entity && c_x > x && c_y > y && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
        #endif
        {
            ItemManager.GetInstance().HideDropzones();
            if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
            {
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else
            {
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
            }
            color = ColorManager.GREEN_COLOR;
        }
        else
        {
            color = ColorManager.RED_COLOR;
            ItemManager.GetInstance().ShowSourceDropzone( item );
        }
        if( w.FindAnyWidget("Selected") )
        {
            w.FindAnyWidget("Selected").SetColor( color );
        }
        else
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Selected" );
            if( w.FindAnyWidget( name ) )
            {
                w.FindAnyWidget( name ).SetColor( color );
            }
        }
        return true;
    }
References GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), CargoBase::GetWidth(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, name, ColorManager::RED_COLOR, string::Replace(), InventoryLocation::SetCargoAuto(), ItemManager::ShowSourceDropzone(), x, and y.
DraggingOverGrid() [2/2]
bool ClosableContainer::DraggingOverGrid (Widget w, int x, int y, Widget reciever, CargoContainer cargo) inline private
Definition at line 747 of file containerwithcargoandattachments.c.
    {
        if( w == NULL )
        {
            return false;
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return false;
        }
        int color;
        int idx = 0;
        int c_x, c_y;
        EntityAI target_entity;
        CargoBase target_cargo;
        if( cargo == m_CargoGrid )
        {
            target_entity   = m_Entity;
            target_cargo    = m_Entity.GetInventory().GetCargo();
        }
        else
        {
            target_entity   = m_AttachmentCargos.GetKeyByValue( cargo );
            if( target_entity )
            {
                target_cargo    = target_entity.GetInventory().GetCargo();
            }
            else
                return false;
        }
        if( target_cargo && target_entity )
        {
            c_x = target_cargo.GetHeight();
            c_y = target_cargo.GetWidth();
        }
        else
            return false;
        if( c_x > x && c_y > y && target_entity.GetInventory().CanAddEntityInCargoEx( item, idx, x, y, item.GetInventory().GetFlipCargo() ) )
        {
            color = ColorManager.GREEN_COLOR;
            if( target_entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
            {
                ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
            }
            else
            {
                ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
            }
        }
        else
        {
            color = ColorManager.RED_COLOR;
        }
        if( w.FindAnyWidget("Selected") )
        {
            w.FindAnyWidget("Selected").SetColor( color );
        }
        else
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Selected" );
            if( w.FindAnyWidget( name ) )
            {
                w.FindAnyWidget( name ).SetColor( color );
            }
        }
        return true;
    }
References GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), CargoBase::GetWidth(), ColorManager::GREEN_COLOR, m_Entity, name, ColorManager::RED_COLOR, string::Replace(), x, and y.
DraggingOverHeader() [1/2]
override void ClosableContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 435 of file containerwithcargo.c.
    {
        DraggingOver( w, x, y, receiver );
    }
References DraggingOver(), x, and y.
Referenced by DraggingOver().
DraggingOverHeader() [2/2]
override void ClosableContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 831 of file containerwithcargoandattachments.c.
    {
        if( w == NULL )
        {
            return;
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        SlotsIcon slots_icon;
        receiver.GetUserData(slots_icon);
        EntityAI attached_entity;
        EntityAI receiver_item;
        bool is_reserved = false;
        int slot_id = -1;
        if(slots_icon)
        {
            attached_entity = slots_icon.GetSlotParent();
            slot_id         = slots_icon.GetSlotID();
            receiver_item   = slots_icon.GetEntity();
            is_reserved     = slots_icon.IsReserved();
        }
        Weapon_Base wpn;
        Magazine mag;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( m_Entity )
        {
            if( Class.CastTo(wpn,  m_Entity ) && Class.CastTo(mag,  item ) )
            {
                if( player.GetWeaponManager().CanAttachMagazine( wpn, mag ) )
                {
                    ItemManager.GetInstance().HideDropzones();
                    if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                    ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                }
            }
            else if( receiver_item && !is_reserved )
            {
                ItemBase receiver_itemIB    = ItemBase.Cast( receiver_item );
                ItemBase itemIB             = ItemBase.Cast( item );
                if( receiver_itemIB && itemIB && receiver_itemIB.CanBeCombined( itemIB ) )
                {
                    ItemManager.GetInstance().HideDropzones();
                    if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                    ColorManager.GetInstance().SetColor( w, ColorManager.COMBINE_COLOR );
                }
                else if( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
                {
                    ItemManager.GetInstance().HideDropzones();
                    if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                    ColorManager.GetInstance().SetColor( w, ColorManager.SWAP_COLOR );
                }
                else if( receiver_itemIB.GetInventory().CanAddAttachment( item ) )
                {
                    ItemManager.GetInstance().HideDropzones();
                    if( receiver_itemIB.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                    {
                        ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                    }
                    else
                    {
                        ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                    }
                    ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
                }
            }
            else if( attached_entity && attached_entity.GetInventory().CanAddAttachmentEx( item, slot_id ) )
            {
                ItemManager.GetInstance().HideDropzones();
                if( attached_entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                {
                    ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                }
                else
                {
                    ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                }
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            }
            else if( m_Entity.GetInventory().CanAddAttachment( item ) )
            {
                ItemManager.GetInstance().HideDropzones();
                if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                {
                    ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                }
                else
                {
                    ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                }
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            }
            else if( ( m_Entity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && !m_Entity.GetInventory().HasEntityInCargo( item ) ) /*|| player.GetHumanInventory().HasEntityInHands( item )*/ )
            {
                ItemManager.GetInstance().HideDropzones();
                if( m_Entity.GetHierarchyRootPlayer() == GetGame().GetPlayer() )
                {
                    ItemManager.GetInstance().GetRightDropzone().SetAlpha( 1 );
                }
                else
                {
                    ItemManager.GetInstance().GetLeftDropzone().SetAlpha( 1 );
                }
                ColorManager.GetInstance().SetColor( w, ColorManager.GREEN_COLOR );
            }
            else
            {
                ItemManager.GetInstance().ShowSourceDropzone( item );
                ColorManager.GetInstance().SetColor( w, ColorManager.RED_COLOR );
            }
        }
    }
References ItemBase::CanBeCombined(), Class::CastTo(), ColorManager::COMBINE_COLOR, SlotsIcon::GetEntity(), GetGame(), ColorManager::GetInstance(), ItemManager::GetInstance(), GetItemPreviewItem(), ItemManager::GetLeftDropzone(), GetPlayer(), ItemManager::GetRightDropzone(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ColorManager::GREEN_COLOR, ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Entity, ColorManager::RED_COLOR, ColorManager::SetColor(), ItemManager::ShowSourceDropzone(), and ColorManager::SWAP_COLOR.
DropReceived() [1/2]
void ClosableContainer::DropReceived (Widget w, int x, int y) inline private
Definition at line 339 of file containerwithcargo.c.
    {
        float xx, yy;
        GetMainWidget().Update();
        GetMainWidget().GetScreenSize( xx, yy );
        if( GetMainWidget().FindAnyWidget("Background") )
        {
            GetMainWidget().FindAnyWidget("Background").Show( true );
            GetMainWidget().FindAnyWidget("Background").SetSize( xx, yy );
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        #ifdef PLATFORM_CONSOLE
        if( m_CargoGrid.HasItem( item ) )
        {
            return;
        }
        #endif
        #ifdef PLATFORM_CONSOLE
        int idx = -1;
        #else
        int idx = 0;
        #endif
        int c_x, c_y;
        CargoBase cargo = m_Entity.GetInventory().GetCargoFromIndex(m_CargoIndex);
        if( cargo )
        {
            c_x = cargo.GetHeight();
            c_y = cargo.GetWidth();
        }
        InventoryLocation dst = new InventoryLocation;
        #ifdef PLATFORM_CONSOLE
        x = 0;
        y = cargo.GetItemCount();
        m_Entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.CARGO, dst );
        #else
        dst.SetCargoAuto(cargo, item, x, y, item.GetInventory().GetFlipCargo());
        #endif
        InventoryLocation src = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation(src);
        if(src.CompareLocationOnly(dst) && src.GetFlip() == dst.GetFlip())
            return;
        #ifdef PLATFORM_CONSOLE
        if(dst.IsValid() && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
        #else
        if( c_x > x && c_y > y && m_Entity.GetInventory().LocationCanAddEntityEx(dst))
        #endif
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            SplitItemUtils.TakeOrSplitToInventoryLocation( player, dst );
            Icon icon = m_CargoGrid.GetIcon( item );
            if( icon && w && w.FindAnyWidget("Selected") )
            {
                w.FindAnyWidget("Selected").SetColor( ColorManager.BASE_COLOR );
                icon.Refresh();
                Refresh();
            }
        }
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
    }
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), FindAnyWidget(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, Refresh(), Icon::Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
DropReceived() [2/2]
void ClosableContainer::DropReceived (Widget w, int x, int y, CargoContainer cargo) inline private
Definition at line 471 of file containerwithcargoandattachments.c.
    {
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        int idx = 0;
        int c_x, c_y;
        EntityAI target_entity;
        CargoBase target_cargo;
        if( cargo == m_CargoGrid )
        {
            target_entity   = m_Entity;
            target_cargo    = m_Entity.GetInventory().GetCargo();
            #ifdef PLATFORM_CONSOLE
            if( m_CargoGrid.HasItem( item ) )
            {
                return;
            }
            #endif
        }
        else
        {
            target_entity   = m_AttachmentCargos.GetKeyByValue( cargo );
            if( target_entity )
            {
                target_cargo    = target_entity.GetInventory().GetCargo();
                #ifdef PLATFORM_CONSOLE
                if( cargo.HasItem( item ) )
                {
                    return;
                }
                #endif
            }
            else
                return;
        }
        if( target_cargo && target_entity )
        {
            c_x = target_cargo.GetHeight();
            c_y = target_cargo.GetWidth();
        }
        else
            return;
        InventoryLocation dst = new InventoryLocation;
        #ifdef PLATFORM_CONSOLE
        x = 0;
        y = target_cargo.GetItemCount();
        target_entity.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.CARGO, dst );
        #else
        dst.SetCargoAuto(target_cargo, item, x, y, item.GetInventory().GetFlipCargo());
        #endif
        InventoryLocation src = new InventoryLocation;
        item.GetInventory().GetCurrentInventoryLocation(src);
        if(src.CompareLocationOnly(dst) && src.GetFlip() == dst.GetFlip())
            return;
        #ifdef PLATFORM_CONSOLE
        if(dst.IsValid() && target_entity.GetInventory().LocationCanAddEntity(dst))
        #else
        if( c_x > x && c_y > y && target_entity.GetInventory().LocationCanAddEntity(dst))
        #endif
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            SplitItemUtils.TakeOrSplitToInventoryLocation( player, dst );
            Icon icon = cargo.GetIcon( item );
            if( icon )
            {
                if( w && w.FindAnyWidget("Selected") )
                    w.FindAnyWidget("Selected").SetColor( ColorManager.BASE_COLOR );
                icon.Refresh();
                Refresh();
            }
        }
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
    }
References ColorManager::BASE_COLOR, InventoryLocation::CompareLocationOnly(), InventoryLocation::GetFlip(), GetGame(), CargoBase::GetHeight(), ItemManager::GetInstance(), CargoBase::GetItemCount(), GetItemPreviewItem(), GetPlayer(), CargoBase::GetWidth(), ItemManager::HideDropzones(), InventoryLocation::IsValid(), m_Entity, Refresh(), Icon::Refresh(), InventoryLocation::SetCargoAuto(), ItemManager::SetIsDragging(), SplitItemUtils::TakeOrSplitToInventoryLocation(), x, and y.
EquipItem()
override bool ClosableContainer::EquipItem () inline private
Definition at line 175 of file containerwithcargo.c.
    {
        return m_CargoGrid.EquipItem();
    }
GetEntity() [1/2]
EntityAI ClosableContainer::GetEntity () inline private
Definition at line 220 of file containerwithcargo.c.
    {
        return m_Entity;
    }
References m_Entity.
Referenced by OnDropReceivedFromHeader().
GetEntity() [2/2]
EntityAI ClosableContainer::GetEntity () inline private
Definition at line 356 of file containerwithcargoandattachments.c.
    {
        return m_Entity;
    }
References m_Entity.
GetFocusedContainerEntity() [1/2]
override EntityAI ClosableContainer::GetFocusedContainerEntity () inline private
Definition at line 225 of file containerwithcargo.c.
    {
        return m_Entity;
    }
References m_Entity.
GetFocusedContainerEntity() [2/2]
override EntityAI ClosableContainer::GetFocusedContainerEntity () inline private
Definition at line 210 of file containerwithcargoandattachments.c.
    {
        return m_Entity;
    }
References m_Entity.
GetItemPreviewItem() [1/2]
EntityAI ClosableContainer::GetItemPreviewItem (Widget w) inline private
Definition at line 230 of file containerwithcargo.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
          ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return null;
        }
        return ipw.GetItem();
    }
References ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by DraggingOver(), DraggingOverGrid(), DraggingOverHeader(), DropReceived(), OnDropReceivedFromHeader(), and TakeAsAttachment().
GetItemPreviewItem() [2/2]
EntityAI ClosableContainer::GetItemPreviewItem (Widget w) inline private
Definition at line 368 of file containerwithcargoandattachments.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
          ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw || !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return NULL;
        }
        return ipw.GetItem();
    }
References ItemPreviewWidget::GetItem(), name, and string::Replace().
GetItemPreviewWidget()
Widget ClosableContainer::GetItemPreviewWidget (Widget w) inline private
Definition at line 388 of file containerwithcargoandattachments.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
          ipw = ItemPreviewWidget.Cast( w );
        }
        return ipw;
    }
References name, and string::Replace().
GetItemPreviewWidgetDragOrDrop()
ItemPreviewWidget ClosableContainer::GetItemPreviewWidgetDragOrDrop (Widget w) inline private
Definition at line 361 of file containerwithcargoandattachments.c.
    {
        string name = w.GetName();
        name.Replace( "PanelWidget", "Render" );
        return ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
    }
References name, and string::Replace().
HideCargo()
void ClosableContainer::HideCargo () inline private
Definition at line 332 of file containerwithcargoandattachments.c.
    {
        if( m_CargoGrid )
        {
            if(m_CargoGrid.IsVisible())
            {
                m_CargoGrid.OnHide();
                RecomputeOpenedContainers();
            }
        }
    }
Referenced by SetEntity(), and UpdateInterval().
InspectItem()
override bool ClosableContainer::InspectItem () inline private
Definition at line 190 of file containerwithcargo.c.
    {
        return m_CargoGrid.InspectItem();
    }
Referenced by MouseClick2().
IsDisplayable()
override bool ClosableContainer::IsDisplayable () inline private
Definition at line 20 of file containerwithcargo.c.
    {
        if (m_Entity)
            return m_Entity.CanDisplayCargo();
        return false;
    }
References m_Entity.
Referenced by Container::Open(), SetEntity(), AttachmentCategoriesContainer::UpdateInterval(), and Container::UpdateRadialIcon().
IsEmpty()
override bool ClosableContainer::IsEmpty () inline private
Definition at line 27 of file containerwithcargo.c.
    {
        return m_CargoGrid.IsEmpty();
    }
IsFirstContainerFocused() [1/2]
override bool ClosableContainer::IsFirstContainerFocused () inline private
Definition at line 150 of file containerwithcargo.c.
    {
        return m_CargoGrid.IsFirstContainerFocused();
    }
IsFirstContainerFocused() [2/2]
override bool ClosableContainer::IsFirstContainerFocused () inline private
Definition at line 244 of file containerwithcargoandattachments.c.
    {
        return IsFirstIndex();
    }
IsItemActive()
override bool ClosableContainer::IsItemActive () inline private
Definition at line 32 of file containerwithcargo.c.
    {
        return m_CargoGrid.IsItemActive();
    }
IsItemWithQuantityActive()
override bool ClosableContainer::IsItemWithQuantityActive () inline private
Definition at line 52 of file containerwithcargo.c.
    {
        return m_CargoGrid.IsItemWithQuantityActive();
    }
IsLastContainerFocused() [1/2]
override bool ClosableContainer::IsLastContainerFocused () inline private
Definition at line 155 of file containerwithcargo.c.
    {
        return m_CargoGrid.IsLastContainerFocused();
    }
IsLastContainerFocused() [2/2]
override bool ClosableContainer::IsLastContainerFocused () inline private
Definition at line 249 of file containerwithcargoandattachments.c.
    {
        return IsLastIndex();
    }
References IsLastIndex().
IsLastIndex()
override bool ClosableContainer::IsLastIndex () inline private
Definition at line 239 of file containerwithcargoandattachments.c.
    {
        return m_ActiveIndex == ( m_OpenedContainers.Count() - 1 );
    }
Referenced by IsLastContainerFocused().
IsOpened()
override bool ClosableContainer::IsOpened () inline private
Definition at line 108 of file containerwithcargo.c.
    {
        return !m_Closed && !m_LockCargo;
    }
Referenced by PlayerContainer::HasEntityContainerVisible(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), AttachmentCategoriesContainer::MouseClick(), Container::OnShow(), UpdateInterval(), and Container::UpdateRadialIcon().
LockCargo()
void ClosableContainer::LockCargo (bool value) inline private
Definition at line 57 of file containerwithcargo.c.
    {
        if( value != m_LockCargo )
        {
            if( value )
            {
                m_LockCargo = true;
                OnHide();
            }
            else
            {
                m_LockCargo = false;
                SetOpenState(!m_Closed);
            }
        }
    }
References OnHide().
Referenced by SetEntity(), and UpdateInterval().
MouseClick2()
void ClosableContainer::MouseClick2 (Widget w, int x, int y, int button) inline private
Definition at line 404 of file containerwithcargoandattachments.c.
    {
        SlotsIcon slots_icon;
        w.GetUserData(slots_icon);
        EntityAI item = null;
        if(slots_icon)
            item = slots_icon.GetEntity();
        ItemBase itemAtPos = ItemBase.Cast( item );
        if( item )
        {
            bool reserved = false;
            reserved = slots_icon.IsReserved();
            if ( button == MouseState.RIGHT )
            {
                #ifdef DEVELOPER
                if( GetDayZGame().IsLeftCtrlDown() )
                    ShowActionMenu( InventoryItem.Cast(item) );
                #endif
                if( reserved )
                {
                    EntityAI att_parent = slots_icon.GetSlotParent();
                    GetGame().GetPlayer().GetHumanInventory().ClearUserReservedLocation( item );
                    att_parent.GetOnAttachmentReleaseLock().Invoke(item, slots_icon.GetSlotID());
                }
            }
            else if ( button == MouseState.MIDDLE )
            {
                if( !reserved )
                {
                    InspectItem( itemAtPos );
                }
            }
            else if ( button == MouseState.LEFT )
            {
                if( !reserved )
                {
                    PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
                    if ( g_Game.IsLeftCtrlDown() )
                    {
                        if( itemAtPos && itemAtPos.GetInventory().CanRemoveEntity() )
{
                            if( itemAtPos.GetTargetQuantityMax() < itemAtPos.GetQuantity() )
                                itemAtPos.SplitIntoStackMaxClient( player, -1 );
                            else
                                player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ANY, itemAtPos );
                        }
                    }
                    else
                    {
                        bool draggable = !player.GetInventory().HasInventoryReservation( item, null ) && !player.GetInventory().IsInventoryLocked() && item.GetInventory().CanRemoveEntity() && !player.IsItemsToDelete();
                        ItemManager.GetInstance().SetWidgetDraggable( w, draggable );
                    }
                }
            }
        }
    }
References g_Game, GetDayZGame(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), CGame::GetPlayer(), GetPlayer(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), InspectItem(), IsLeftCtrlDown(), SlotsIcon::IsReserved(), and ItemManager::SetWidgetDraggable().
MoveGridCursor()
override void ClosableContainer::MoveGridCursor (int direction) inline private
Definition at line 254 of file containerwithcargoandattachments.c.
    {
        Container c = GetFocusedContainer();
        if ( c )
        {
            c.MoveGridCursor( direction );
            Inventory.GetInstance().UpdateConsoleToolbar();
        }
    }
References Inventory().
OnDropReceivedFromHeader() [1/2]
override void ClosableContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 469 of file containerwithcargo.c.
    {
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        InventoryLocation src = new InventoryLocation();
        if( GetEntity() && item.GetInventory().GetCurrentInventoryLocation(src))
        {
            InventoryLocation dst = new InventoryLocation();
            if (m_Entity.GetInventory().FindFreeLocationFor(item, FindInventoryLocationType.ATTACHMENT, dst))
            {
                player.PredictiveTakeToDst(src, dst);
            }
            bool can_add = m_Entity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() );
            bool in_cargo = !player.GetInventory().HasEntityInInventory( item ) || !m_Entity.GetInventory().HasEntityInCargo( item );
            if( can_add && in_cargo )
            {
                SplitItemUtils.TakeOrSplitToInventory( player, m_Entity, item );
            }
        }
    }
References GetEntity(), GetGame(), GetItemPreviewItem(), GetPlayer(), m_Entity, and SplitItemUtils::TakeOrSplitToInventory().
OnDropReceivedFromHeader() [2/2]
override void ClosableContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 670 of file containerwithcargoandattachments.c.
    {
        TakeAsAttachment( w, receiver );
    }
References TakeAsAttachment().
OnDropReceivedFromHeader2()
void ClosableContainer::OnDropReceivedFromHeader2 (Widget w, int x, int y, Widget receiver) inline private
Definition at line 675 of file containerwithcargoandattachments.c.
    {
        TakeAsAttachment( w, receiver );
    }
References TakeAsAttachment().
Open()
override void ClosableContainer::Open () inline private
Definition at line 74 of file containerwithcargo.c.
    {
        if( !m_LockCargo )
        {
            ItemManager.GetInstance().SetDefaultOpenState( m_Entity.GetType(), true );
            m_Closed = false;
            SetOpenForSlotIcon(true);
            OnShow();
            m_Parent.m_Parent.Refresh();
        }
        if ( m_SlotIcon )
        {
            m_SlotIcon.GetRadialIconPanel().Show( !m_LockCargo );
        }
    }
References ItemManager::GetInstance(), m_Entity, m_Parent, OnShow(), and ItemManager::SetDefaultOpenState().
Referenced by AttachmentCategoriesContainer::InitGhostSlots(), and AttachmentCategoriesContainer::MouseClick().
RecomputeContainers()
void ClosableContainer::RecomputeContainers () inline private
Definition at line 42 of file containerwithcargoandattachments.c.
    {
        m_Body.Clear();
        if(m_Atts)
        {
            m_Body.Insert(m_Atts.GetWrapper());
        }
        if(m_CargoGrid)
        {
            m_Body.Insert(m_CargoGrid);
        }
        GameInventory inv = m_Entity.GetInventory();
        for (int i = 0; i < inv.AttachmentCount(); i++)
        {
            EntityAI ent = inv.GetAttachmentFromIndex(i);
            if(ent)
            {
                AttachmentsWrapper att = m_AttachmentAttachmentsContainers.Get(ent);
                if(att)
                {
                    m_Body.Insert(att);
                }
                CargoContainer cargo = m_AttachmentCargos.Get(ent);
                if(cargo)
                {
                    m_Body.Insert(cargo);
                }
            }
        }
    }
References Container::Get(), LayoutHolder::Insert(), and m_Entity.
Referenced by AttachmentAddedEx(), AttachmentRemoved(), and SetEntity().
SetDefaultFocus()
override void ClosableContainer::SetDefaultFocus (bool while_micromanagment_mode = false) inline private
Definition at line 160 of file containerwithcargo.c.
    {
        m_CargoGrid.SetDefaultFocus( while_micromanagment_mode );
    }
SetEntity() [1/2]
void ClosableContainer::SetEntity (EntityAI entity, bool immedUpdate = true) inline private
Definition at line 264 of file containerwithcargoandattachments.c.
    {
        m_Entity = entity;
        m_Atts = new Attachments( this, m_Entity );
        m_Atts.InitAttachmentGrid( SORT_ATTACHMENTS_OWN );
        m_AttachmentSlotsSorted = m_Atts.GetSlotsSorted();
        m_Entity.GetOnItemAttached().Insert( AttachmentAdded );
        m_Entity.GetOnItemDetached().Insert( AttachmentRemoved );
        m_ClosableHeader.SetItemPreview( m_Entity );
        CheckHeaderDragability();
        if ( m_Entity.GetInventory().GetCargo() )
        {
            m_CargoGrid = new CargoContainer( this, false );
            m_CargoGrid.GetRootWidget().SetSort( SORT_CARGO_OWN );
            m_CargoGrid.SetEntity( m_Entity, 0, immedUpdate );
            m_CargoGrid.UpdateHeaderText(); // TODO: refresh?
            Insert( m_CargoGrid );
        }
        else
        {
            string name = m_Entity.GetDisplayName();
            name.ToUpper();
            m_ClosableHeader.SetName( name );
        }
        m_AttachmentCargos                  = new map<EntityAI, ref CargoContainer>;
        m_AttachmentAttachmentsContainers   = new map<EntityAI, ref AttachmentsWrapper>;
        m_AttachmentAttachments             = new map<EntityAI, ref Attachments>;
        (Container.Cast( m_Parent )).Insert( this );
        foreach ( int slot_id : m_AttachmentSlotsSorted )
        {
            EntityAI item = m_Entity.GetInventory().FindAttachment( slot_id );
            if ( item )
                AttachmentAddedEx( item, InventorySlots.GetSlotName( slot_id ), m_Entity, false );
        }
        RecomputeContainers();
        if (m_CargoGrid)
        {
            bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
            if (m_CargoGrid.IsVisible() && hideCargo)
            {
                HideCargo();
            }
            else if (!m_CargoGrid.IsVisible() && !hideCargo)
            {
                ShowCargo();
            }
        }
        if( IsDisplayable() )
            SetOpenState( true );
        else
            SetOpenState( false );
        if (immedUpdate)
            m_Parent.m_Parent.Refresh();
        RecomputeOpenedContainers();
    }
References AttachmentAddedEx(), InventorySlots::GetSlotName(), HideCargo(), IsDisplayable(), m_Entity, m_Parent, name, RecomputeContainers(), ShowCargo(), and string::ToUpper().
SetEntity() [2/2]
void ClosableContainer::SetEntity (EntityAI entity, int cargo_index = 0, bool immedUpdate = true) inline private
Definition at line 195 of file containerwithcargo.c.
    {
        m_Entity = entity;
        m_CargoIndex = cargo_index;
        SetOpenState( true );
        m_CargoGrid.SetEntity( entity, immedUpdate );
        m_CargoGrid.UpdateHeaderText();
        m_ClosableHeader.SetItemPreview( entity );
        CheckHeaderDragability();
        ( Container.Cast( m_Parent ) ).Insert( this, -1, false );
        if ( m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo() )
            LockCargo(true);
        else
            LockCargo(false);
        if ( immedUpdate )
        {
            Refresh();
            GetMainWidget().Update();
        }
    }
References LockCargo(), m_Entity, m_Parent, and Refresh().
ShowCargo()
void ClosableContainer::ShowCargo () inline private
Definition at line 344 of file containerwithcargoandattachments.c.
    {
        if( m_CargoGrid )
        {
            if(!m_CargoGrid.IsVisible())
            {
                m_CargoGrid.OnShow();
                RecomputeOpenedContainers();
            }
        }
    }
Referenced by SetEntity(), and UpdateInterval().
SplitItem()
override bool ClosableContainer::SplitItem () inline private
Definition at line 170 of file containerwithcargo.c.
    {
        return m_CargoGrid.SplitItem();
    }
TakeAsAttachment()
void ClosableContainer::TakeAsAttachment (Widget w, Widget receiver) inline private
Definition at line 560 of file containerwithcargoandattachments.c.
    {
        ItemManager.GetInstance().HideDropzones();
        ItemManager.GetInstance().SetIsDragging( false );
        SlotsIcon slots_icon;
        EntityAI receiver_item;
        int slot_id = -1;
        bool is_reserved = false;
        EntityAI attached_entity;
        receiver.GetUserData(slots_icon);
        //string name = receiver.GetName();
        //name.Replace("PanelWidget", "Render");
        //ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget(name) );
        if( slots_icon )
        {
            receiver_item   = slots_icon.GetEntity();
            slot_id         = slots_icon.GetSlotID();
            attached_entity = slots_icon.GetSlotParent();
            is_reserved     = slots_icon.IsReserved();
        }
        EntityAI item = GetItemPreviewItem( w );
        if( !item )
        {
            return;
        }
        ItemBase item_base  = ItemBase.Cast( item );
        InventoryLocation il = new InventoryLocation;
        float stackable;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if( !item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
            return;
        EntityAI target_att_entity = m_Entity;
        Weapon_Base wpn;
        Magazine mag;
        if( Class.CastTo(wpn,  m_Entity ) && Class.CastTo(mag,  item ) )
        {
            if( player.GetWeaponManager().CanAttachMagazine( wpn, mag ) )
            {
                player.GetWeaponManager().AttachMagazine( mag );
            }
        }
        else if( receiver_item && !is_reserved )
        {
            if( ( ItemBase.Cast( receiver_item ) ).CanBeCombined( ItemBase.Cast( item ) ) )
            {
                ( ItemBase.Cast( receiver_item ) ).CombineItemsClient( ItemBase.Cast( item ) );
            }
            else if( GameInventory.CanSwapEntitiesEx( receiver_item, item ) )
            {
                if( !receiver_item.GetInventory().CanRemoveEntity() )
                    return;
                GetGame().GetPlayer().PredictiveSwapEntities( receiver_item, item );
            }
            else if( receiver_item.GetInventory().CanAddAttachment( item ) )
            {
                player.PredictiveTakeEntityToTargetAttachment(receiver_item, item);
            }
        }
        else if( attached_entity && attached_entity.GetInventory().CanAddAttachmentEx( item, slot_id ) )
        {
            stackable = item_base.GetTargetQuantityMax(slot_id);
            if( stackable == 0 || stackable >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachmentEx(attached_entity, item, slot_id);
            }
            else if( stackable != 0 && stackable < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( attached_entity, slot_id );
            }
        }
        else if(attached_entity && attached_entity.GetInventory().CanAddAttachment(item))
        {
            attached_entity.GetInventory().FindFreeLocationFor(item,FindInventoryLocationType.ATTACHMENT,il);
            stackable = item_base.GetTargetQuantityMax(il.GetSlot());
            if( stackable == 0 || stackable >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachmentEx(attached_entity, item, il.GetSlot());
            }
            else if( stackable != 0 && stackable < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( attached_entity, il.GetSlot() );
            }
        }
        else if( m_Entity.GetInventory().CanAddAttachment(item) )
        {
            m_Entity.GetInventory().FindFreeLocationFor(item,FindInventoryLocationType.ATTACHMENT,il);
            stackable = item_base.GetTargetQuantityMax(il.GetSlot());
            if( stackable == 0 || stackable >= item_base.GetQuantity() )
            {
                player.PredictiveTakeEntityToTargetAttachmentEx(m_Entity, item, il.GetSlot());
            }
            else if( stackable != 0 && stackable < item_base.GetQuantity() )
            {
                item_base.SplitIntoStackMaxClient( m_Entity, il.GetSlot() );
            }
        }
        else if( m_Entity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ) && !m_Entity.GetInventory().HasEntityInCargo( item ) )
        {
            SplitItemUtils.TakeOrSplitToInventory( PlayerBase.Cast( GetGame().GetPlayer() ), m_Entity, item );
        }
        /*else if( !player.GetInventory().HasEntityInInventory( item ) || !m_Entity.GetInventory().HasEntityInCargo( item ) )
        {
            SplitItemUtils.TakeOrSplitToInventory( PlayerBase.Cast( GetGame().GetPlayer() ), m_Entity, item );
        }*/
    }
References Class::CastTo(), CombineItemsClient(), SlotsIcon::GetEntity(), GetGame(), ItemManager::GetInstance(), GetItemPreviewItem(), CGame::GetPlayer(), GetPlayer(), InventoryLocation::GetSlot(), SlotsIcon::GetSlotID(), SlotsIcon::GetSlotParent(), ItemManager::HideDropzones(), SlotsIcon::IsReserved(), m_Entity, ItemManager::SetIsDragging(), and SplitItemUtils::TakeOrSplitToInventory().
Referenced by OnDropReceivedFromHeader(), and OnDropReceivedFromHeader2().
TakeIntoHands()
void ClosableContainer::TakeIntoHands (notnull PlayerBase player, notnull EntityAI item) inline private
Definition at line 416 of file containerwithcargo.c.
    {
        ItemBase item_base = ItemBase.Cast( item );
        if( !item.GetInventory().CanRemoveEntity() || !player.CanManipulateInventory() )
            return;
        float stackable = item_base.GetTargetQuantityMax();
        if( stackable == 0 || stackable >= item_base.GetQuantity() )
        {
            player.PredictiveTakeEntityToHands( item );
        }
        else if( stackable != 0 && stackable < item_base.GetQuantity() )
        {
            item_base.SplitIntoStackMaxHandsClient( player );
        }
    }
TransferItem()
override bool ClosableContainer::TransferItem () inline private
Definition at line 180 of file containerwithcargo.c.
    {
        return m_CargoGrid.TransferItem();
    }
TransferItemToVicinity()
override bool ClosableContainer::TransferItemToVicinity () inline private
Definition at line 185 of file containerwithcargo.c.
    {
        return m_CargoGrid.TransferItemToVicinity();
    }
UnfocusAll() [1/2]
override void ClosableContainer::UnfocusAll () inline private
Definition at line 165 of file containerwithcargo.c.
    {
        m_CargoGrid.Unfocus();
    }
UnfocusAll() [2/2]
override void ClosableContainer::UnfocusAll () inline private
Definition at line 215 of file containerwithcargoandattachments.c.
    {
        if( m_Atts )
        {
            m_Atts.UnfocusAll();
        }
        if( m_CargoGrid )
        {
            m_CargoGrid.UnfocusAll();
        }
        foreach( EntityAI e1, CargoContainer cargo : m_AttachmentCargos )
        {
            cargo.UnfocusAll();
        }
        foreach( EntityAI e2, Attachments att : m_AttachmentAttachments )
        {
            att.UnfocusAll();
        }
    }
UpdateInterval() [1/2]
override void ClosableContainer::UpdateInterval () inline private
Definition at line 113 of file containerwithcargo.c.
    {
        if ( m_Entity )
        {
            if ( m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo()  )
            {
                LockCargo(true);
                if ( m_CargoGrid.IsVisible() )
                {
                    RecomputeOpenedContainers();
                }
            }
            else
            {
                LockCargo(false);
                if ( !m_CargoGrid.IsVisible() )
                {
                    RecomputeOpenedContainers();
                }
            }
            super.UpdateInterval();
            m_CargoGrid.UpdateInterval();
            bool hide = m_LockCargo || ItemManager.GetInstance().GetDraggedItem() == m_Entity;
            if (!hide)
            {
                SetOpenForSlotIcon(IsOpened());
            }
            if ( m_SlotIcon )
            {
                m_SlotIcon.GetRadialIconPanel().Show( !hide );
            }
        }
    }
References ItemManager::GetDraggedItem(), ItemManager::GetInstance(), IsOpened(), LockCargo(), and m_Entity.
UpdateInterval() [2/2]
override void ClosableContainer::UpdateInterval () inline private
Definition at line 176 of file containerwithcargoandattachments.c.
    {
        if ( m_Entity )
        {
            if (m_CargoGrid)
            {
                bool hideCargo = m_Entity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) || !m_Entity.CanDisplayCargo() || m_ForcedHide;
                if (m_CargoGrid.IsVisible() && hideCargo)
                {
                    HideCargo();
                }
                else if (!m_CargoGrid.IsVisible() && !hideCargo)
                {
                    ShowCargo();
                }
                m_CargoGrid.UpdateInterval();
            }
            if ( m_SlotIcon )
            {
                bool hide = m_LockCargo || ItemManager.GetInstance().GetDraggedItem() == m_Entity;
                if (!hide)
                {
                    SetOpenForSlotIcon(IsOpened());
                }
                m_SlotIcon.GetRadialIconPanel().Show( !hide );
            }
            super.UpdateInterval();
        }
    }
References ItemManager::GetDraggedItem(), ItemManager::GetInstance(), HideCargo(), IsOpened(), m_Entity, and ShowCargo().
Member Data Documentation
m_AttachmentAttachments
protected ref map<EntityAI, ref Attachments> ClosableContainer::m_AttachmentAttachments private
Definition at line 8 of file containerwithcargoandattachments.c.
m_AttachmentAttachmentsContainers
protected ref map<EntityAI, ref AttachmentsWrapper> ClosableContainer::m_AttachmentAttachmentsContainers private
Definition at line 7 of file containerwithcargoandattachments.c.
m_AttachmentCargos
protected ref map<EntityAI, ref CargoContainer> ClosableContainer::m_AttachmentCargos private
Definition at line 6 of file containerwithcargoandattachments.c.
m_AttachmentSlotsSorted
protected ref array<int> ClosableContainer::m_AttachmentSlotsSorted private
Definition at line 9 of file containerwithcargoandattachments.c.
m_Atts
protected ref Attachments ClosableContainer::m_Atts private
Definition at line 3 of file containerwithcargoandattachments.c.
Referenced by ~ContainerWithCargoAndAttachments().
m_CargoGrid
protected ref CargoContainer ClosableContainer::m_CargoGrid private
Definition at line 3 of file containerwithcargo.c.
m_CargoIndex
protected int ClosableContainer::m_CargoIndex = -1 private
Definition at line 4 of file containerwithcargo.c.