DayzKode: HiddenSelectionsData Class Reference
HiddenSelectionsData Class Reference
Private Member Functions
int GetHiddenSelectionIndex (string selection)
TStringArray GetHiddenSelectionsMaterials ()
TStringArray GetHiddenSelectionsTextures ()
void HiddenSelectionsData (string type)
Static Private Member Functions
static array< string > GetHiddenSelectionsConfig (string type)
static array< string > GetHiddenSelectionsMaterialsConfig (string type)
static array< string > GetHiddenSelectionsTexturesConfig (string type)
Private Attributes
ref map< string, int > m_HiddenSelectionNameToIndex = new map<string, int>
ref array< string > m_HiddenSelections = new array<string>
ref array< string > m_HiddenSelectionsMaterials = new array<string>
ref array< string > m_HiddenSelectionsTextures = new array<string>
Detailed Description
Definition at line 1 of file hiddenselectionsdata.c.
Constructor & Destructor Documentation
HiddenSelectionsData()
void HiddenSelectionsData::HiddenSelectionsData (string type) inline private
Definition at line 9 of file hiddenselectionsdata.c.
    {
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelections",          type), m_HiddenSelections );
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelectionsTextures",  type), m_HiddenSelectionsTextures );
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelectionsMaterials", type), m_HiddenSelectionsMaterials );
        for (int i = 0; i < m_HiddenSelections.Count(); ++i)
            m_HiddenSelectionNameToIndex.Insert(m_HiddenSelections[i], i);
    }
References CGame::ConfigGetTextArray(), GetGame(), m_HiddenSelectionNameToIndex, m_HiddenSelections, m_HiddenSelectionsMaterials, and m_HiddenSelectionsTextures.
Member Function Documentation
GetHiddenSelectionIndex()
int HiddenSelectionsData::GetHiddenSelectionIndex (string selection) inline private
Definition at line 19 of file hiddenselectionsdata.c.
    {
        int index;
        if (m_HiddenSelectionNameToIndex.Find(selection, index))
            return index;
        return -1;
    }
References m_HiddenSelectionNameToIndex.
GetHiddenSelectionsConfig()
static array< string > HiddenSelectionsData::GetHiddenSelectionsConfig (string type) inline static private
Definition at line 38 of file hiddenselectionsdata.c.
    {
        array<string> hiddenSelections = new array<string>;
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelections", type), hiddenSelections );
        return hiddenSelections;
    }
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelections().
GetHiddenSelectionsMaterials()
TStringArray HiddenSelectionsData::GetHiddenSelectionsMaterials () inline private
Definition at line 33 of file hiddenselectionsdata.c.
    {
        return m_HiddenSelectionsMaterials;
    }
References m_HiddenSelectionsMaterials.
GetHiddenSelectionsMaterialsConfig()
static array< string > HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig (string type) inline static private
Definition at line 52 of file hiddenselectionsdata.c.
    {
        array<string> hiddenSelectionsMaterials = new array<string>;
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelectionsMaterials", type), hiddenSelectionsMaterials );
        return hiddenSelectionsMaterials;
    }
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelectionsMaterials().
GetHiddenSelectionsTextures()
TStringArray HiddenSelectionsData::GetHiddenSelectionsTextures () inline private
Definition at line 28 of file hiddenselectionsdata.c.
    {
        return m_HiddenSelectionsTextures;
    }
References m_HiddenSelectionsTextures.
GetHiddenSelectionsTexturesConfig()
static array< string > HiddenSelectionsData::GetHiddenSelectionsTexturesConfig (string type) inline static private
Definition at line 45 of file hiddenselectionsdata.c.
    {
        array<string> hiddenSelectionsTextures = new array<string>;
        GetGame().ConfigGetTextArray( string.Format("CfgVehicles %1 hiddenSelectionsTextures", type), hiddenSelectionsTextures );
        return hiddenSelectionsTextures;
    }
References CGame::ConfigGetTextArray(), and GetGame().
Referenced by GetHiddenSelectionsTextures().
Member Data Documentation
m_HiddenSelectionNameToIndex
ref map<string, int> HiddenSelectionsData::m_HiddenSelectionNameToIndex = new map<string, int> private
Definition at line 7 of file hiddenselectionsdata.c.
Referenced by GetHiddenSelectionIndex(), and HiddenSelectionsData().
m_HiddenSelections
ref array<string> HiddenSelectionsData::m_HiddenSelections = new array<string> private
Definition at line 3 of file hiddenselectionsdata.c.
Referenced by HiddenSelectionsData().
m_HiddenSelectionsMaterials
ref array<string> HiddenSelectionsData::m_HiddenSelectionsMaterials = new array<string> private
Definition at line 5 of file hiddenselectionsdata.c.
Referenced by GetHiddenSelectionsMaterials(), and HiddenSelectionsData().
m_HiddenSelectionsTextures
ref array<string> HiddenSelectionsData::m_HiddenSelectionsTextures = new array<string> private
Definition at line 4 of file hiddenselectionsdata.c.
Referenced by GetHiddenSelectionsTextures(), and HiddenSelectionsData().