DayzKode: DayZPlayerImplementHeading Class Reference
DayZPlayerImplementHeading Class Reference
Static Private Member Functions
static bool ClampHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
static bool NoHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
static bool RotateOrient (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff)
Static Private Attributes
static float CONST_ROTLIMIT = Math.PI * 0.95
Detailed Description
Definition at line 10 of file dayzplayerimplementheading.c.
Member Function Documentation
ClampHeading()
static bool DayZPlayerImplementHeading::ClampHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
This HeadingModel - Clamps heading
Definition at line 19 of file dayzplayerimplementheading.c.
    {
        float       aDiff = pModel.m_fHeadingAngle - pModel.m_fOrientationAngle;
        if (aDiff < -Math.PI)
        {
            aDiff += Math.PI2;
        }
        else if (aDiff > Math.PI)
        {
            aDiff -= Math.PI2;
        }
        // Print("Heading model: or: " + pModel.m_fOrientationAngle.ToString() + " head:" + pModel.m_fHeadingAngle.ToString() + " dif:" + aDiff.ToString());
        if (pLastHeadingDiff < -Math.PI_HALF && aDiff > 0)
        {
            aDiff                   = -Math.PI + 0.01;
            pLastHeadingDiff        = aDiff;
            pModel.m_fHeadingAngle  = pModel.m_fOrientationAngle + aDiff;
            // Print("-APA- : or: " + pModel.m_fOrientationAngle.ToString() + " head:" + pModel.m_fHeadingAngle.ToString() + " dif:" + aDiff.ToString());
            return true;        // modify heading
        }
        else if (pLastHeadingDiff > Math.PI_HALF && aDiff < 0)
        {
            aDiff                   = Math.PI - 0.01;
            pLastHeadingDiff        = aDiff;
            pModel.m_fHeadingAngle  = pModel.m_fOrientationAngle + aDiff;
            // Print("-APA- : or: " + pModel.m_fOrientationAngle.ToString() + " head:" + pModel.m_fHeadingAngle.ToString() + " dif:" + aDiff.ToString());
            return true;        // modify heading
        }
        pLastHeadingDiff    = aDiff;
        // Print("Heading model diff " + aDiff.ToString());
        return false;
    }
References Math::PI, Math::PI2, and Math::PI_HALF.
Referenced by HeadingModel(), and ManBase::HeadingModel().
NoHeading()
static bool DayZPlayerImplementHeading::NoHeading (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
Definition at line 122 of file dayzplayerimplementheading.c.
    {
        pLastHeadingDiff = 0;
        pModel.m_fHeadingAngle = pModel.m_fOrientationAngle;
        return true;
    }
Referenced by HeadingModel().
RotateOrient()
static bool DayZPlayerImplementHeading::RotateOrient (float pDt, SDayZPlayerHeadingModel pModel, out float pLastHeadingDiff) inline static private
Definition at line 67 of file dayzplayerimplementheading.c.
    {
        float       aDiff = pModel.m_fHeadingAngle - pModel.m_fOrientationAngle;
        while (aDiff < -Math.PI)
        {
            aDiff += Math.PI2;
        }
        while (aDiff > Math.PI)
        {
            aDiff -= Math.PI2;
        }
        // Print("Heading model: or: " + pModel.m_fOrientationAngle.ToString() + " head:" + pModel.m_fHeadingAngle.ToString() + " dif:" + aDiff.ToString());
        if (pLastHeadingDiff < -Math.PI_HALF && aDiff > 0)
        {
            aDiff -= Math.PI2;
        }
        else if (pLastHeadingDiff > Math.PI_HALF && aDiff < 0)
        {
            aDiff += Math.PI2;
        }
        pLastHeadingDiff    = aDiff;
        if (aDiff < -CONST_ROTLIMIT)
        {
            // character is somehow stucked (happens in prone stance)
            if (aDiff < -(Math.PI_HALF + CONST_ROTLIMIT))
            {
                pLastHeadingDiff = 0;
                return false;
            }
            pModel.m_fOrientationAngle += aDiff +  CONST_ROTLIMIT;
            return true;
        }
        else if (aDiff > CONST_ROTLIMIT)
        {
            // character is somehow stucked (happens in prone stance)
            if (aDiff > (Math.PI_HALF + CONST_ROTLIMIT))
            {
                pLastHeadingDiff = 0;
                return false;
            }
            pModel.m_fOrientationAngle += aDiff - CONST_ROTLIMIT;
            return true;
        }
        // Print("Heading model diff " + aDiff.ToString());
        return false;
    }
References CONST_ROTLIMIT, Math::PI, Math::PI2, and Math::PI_HALF.
Referenced by HeadingModel().
Member Data Documentation
CONST_ROTLIMIT
float DayZPlayerImplementHeading::CONST_ROTLIMIT = Math.PI * 0.95 static private
This HeadingModel - Rotates orientations - so player slides
Definition at line 64 of file dayzplayerimplementheading.c.
Referenced by RotateOrient().