DayzKode: ActionStopEngine Class Reference
ActionStopEngine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionStopEngine ()
override bool CanBeUsedInVehicle ()
override void CreateConditionComponents ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
override bool UseMainItem ()
Detailed Description
Definition at line 1 of file actionstopengine.c.
Constructor & Destructor Documentation
ActionStopEngine()
void ActionStopEngine::ActionStopEngine () inline private
Definition at line 3 of file actionstopengine.c.
    {
        m_CommandUID    = DayZPlayerConstants.CMD_ACTIONMOD_STOPENGINE;
        m_StanceMask    = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text          = "#stop_engine";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionStopEngine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 16 of file actionstopengine.c.
    {
        HumanCommandVehicle vehCmd = player.GetCommand_Vehicle();
        if (vehCmd && vehCmd.GetVehicleSeat() == DayZPlayerConstants.VEHICLESEAT_DRIVER)
        {
            Transport trans = vehCmd.GetTransport();
            if (trans)
            {
                Car car;
                if (Class.CastTo(car, trans) && car.EngineIsOn())
                {
                    return car.GetSpeedometerAbsolute() <= 8;
                }
            }
        }
        return false;
    }
References Class::CastTo(), Transport::GetSpeedometerAbsolute(), HumanCommandVehicle::GetTransport(), and HumanCommandVehicle::GetVehicleSeat().
CanBeUsedInVehicle()
override bool ActionStopEngine::CanBeUsedInVehicle () inline private
Definition at line 54 of file actionstopengine.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionStopEngine::CreateConditionComponents () inline private
Definition at line 10 of file actionstopengine.c.
    {
        m_ConditionItem     = new CCINone;
        m_ConditionTarget   = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
OnExecuteClient()
override void ActionStopEngine::OnExecuteClient (ActionData action_data) inline private
Definition at line 52 of file actionstopengine.c.
{}
OnExecuteServer()
override void ActionStopEngine::OnExecuteServer (ActionData action_data) inline private
Definition at line 35 of file actionstopengine.c.
    {
        HumanCommandVehicle vehCmd = action_data.m_Player.GetCommand_Vehicle();
        if (vehCmd)
        {
            Transport trans = vehCmd.GetTransport();
            if (trans)
            {
                CarScript car;
                if (Class.CastTo(car, trans))
                {
                    car.EngineStop();
                }
            }
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.
UseMainItem()
override bool ActionStopEngine::UseMainItem () inline private
Definition at line 59 of file actionstopengine.c.
    {
        return false;
    }