DayzKode: ActionViewBinoculars Class Reference
ActionViewBinoculars Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override void EnterOptics (ItemOptics optic, PlayerBase player)
override void ExitOptics (ItemOptics optic, PlayerBase player)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
Private Attributes
bool m_workingRangefinder
Detailed Description
Definition at line 1 of file actionviewbinoculars.c.
Member Function Documentation
ActionCondition()
override bool ActionViewBinoculars::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 18 of file actionviewbinoculars.c.
    {
        ItemOptics optic;
        if( Class.CastTo(optic, item) && !optic.IsInOptics() && !player.IsNVGLowered() )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
EnterOptics()
override void ActionViewBinoculars::EnterOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 28 of file actionviewbinoculars.c.
    {
        player.SetIronsights(false);
        player.SetHandheldOpticsInUse(true);
        player.SetOptics(true);
        optic.EnterOptics();
        optic.HideSelection("hide");
        if ( NVGoggles.Cast(optic) && optic.ConfigIsExisting("simpleHiddenSelections") )
        {
            optic.SetSimpleHiddenSelectionState(0,false);
        }
        if ( optic.HasEnergyManager() )
        {
            PoweredOptic_Base rf = PoweredOptic_Base.Cast(optic);
            if (!rf)
                return;
            rf.SetPlayer( player );
            if ( GetGame().IsServer() )
                rf.GetCompEM().SwitchOn();
        }
    }
References GetGame(), and ItemOptics::HideSelection().
ExitOptics()
override void ActionViewBinoculars::ExitOptics (ItemOptics optic, PlayerBase player) inline private
Definition at line 52 of file actionviewbinoculars.c.
    {
        optic.ShowSelection("hide");
        if ( NVGoggles.Cast(optic) && optic.ConfigIsExisting("simpleHiddenSelections") )
        {
            optic.SetSimpleHiddenSelectionState(0,true);
        }
        player.SetHandheldOpticsInUse(false);
        player.ExitSights();
        if ( optic.HasEnergyManager() )
        {
            PoweredOptic_Base rf = PoweredOptic_Base.Cast(optic);
            if (!rf)
                return;
            rf.SetPlayer( null );
            if ( GetGame().IsServer() )
                rf.GetCompEM().SwitchOff();
        }
    }
References GetGame(), and ItemOptics::ShowSelection().
OnActionInfoUpdate()
override void ActionViewBinoculars::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 5 of file actionviewbinoculars.c.
    {
        Rangefinder rangefinder = Rangefinder.Cast(item);
        if ( rangefinder )
        {
            m_Text = "#use_range_finder";
        }
        else
        {
            m_Text = "#Look_Through";
        }
    }
References m_Text.
Member Data Documentation
m_workingRangefinder
bool ActionViewBinoculars::m_workingRangefinder private
Definition at line 3 of file actionviewbinoculars.c.