DayzKode: CAContinuousMineWood Class Reference
CAContinuousMineWood Class Reference
Private Member Functions
void CAContinuousMineWood (float time_between_drops)
override int Cancel (ActionData action_data)
void CreatePrimaryItems (ActionData action_data)
void CreateSecondaryItems (ActionData action_data, string material_secondary="", int quantity_secondary=-1)
void DamagePlayersHands (PlayerBase player)
override int Execute (ActionData action_data)
bool GetMiningData (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_AdjustedDamageToMiningItemEachDrop
protected float m_AdjustedTimeBetweenMaterialDrops
protected int m_AmountOfDrops
protected float m_CycleTimeOverride
protected float m_DamageToMiningItemEachDrop
protected bool m_DataLoaded = false
protected ref map< string, int > m_MaterialAndQuantityMap
protected ItemBase m_MinedItem [MINEDITEM_MAX]
protected ItemBase m_SecondaryItem
protected ref Param1< float > m_SpentUnits
protected float m_TimeBetweenMaterialDrops
protected float m_TimeElpased
protected float m_TimeToComplete
protected const int MINEDITEM_MAX = 5
Detailed Description
Definition at line 1 of file cacontinuousminewood.c.
Constructor & Destructor Documentation
CAContinuousMineWood()
void CAContinuousMineWood::CAContinuousMineWood (float time_between_drops) inline private
Definition at line 20 of file cacontinuousminewood.c.
    {
        m_TimeBetweenMaterialDrops = time_between_drops;
        m_CycleTimeOverride = -1.0;
    }
References m_CycleTimeOverride, and m_TimeBetweenMaterialDrops.
Member Function Documentation
Cancel()
override int CAContinuousMineWood::Cancel (ActionData action_data) inline private
Definition at line 131 of file cacontinuousminewood.c.
    {
        ToolBase cut_tree_tool = ToolBase.Cast( action_data.m_MainItem );
        if (!cut_tree_tool)
            return super.Cancel( action_data );
        return super.Cancel( action_data );
    }
References ActionData::m_MainItem.
CreatePrimaryItems()
void CAContinuousMineWood::CreatePrimaryItems (ActionData action_data) inline private
Definition at line 161 of file cacontinuousminewood.c.
    {
        string material;
        int increment;
        for (int i = 0; i < m_MaterialAndQuantityMap.Count(); i++)
        {
            material = m_MaterialAndQuantityMap.GetKey(i);
            if (material != "")
            {
                increment = m_MaterialAndQuantityMap.GetElement(i);
                if ( !m_MinedItem[i] )
                {
                    m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material,action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
                    m_MinedItem[i].SetQuantity(increment);
                    //Print("CreateItems | first stack");
                }
                else if (m_MinedItem[i].HasQuantity())
                {
                    if ( m_MinedItem[i].IsFullQuantity() )
                    {
                        int stack_max = m_MinedItem[i].GetQuantityMax();
                        //Print("CreateItems | new stack");
                        increment -= stack_max - m_MinedItem[i].GetQuantity();
                        if (increment >= 1.0)
{
                            //m_MinedItem[i].SetQuantity(stack_max);
                            m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material,action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
                            m_MinedItem[i].SetQuantity(increment,false);
                        }
                    }
                    else
                    {
                        //Print("CreateItems | adding quantity to: " + (m_MinedItem[i].GetQuantity() + increment));
                        m_MinedItem[i].AddQuantity(increment,false);
                    }
                }
                else
                {
                    m_MinedItem[i] = ItemBase.Cast(GetGame().CreateObjectEx(material,action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
                }
            }
        }
    }
References ECE_PLACE_ON_SURFACE, GetGame(), HasQuantity(), IsFullQuantity(), m_MaterialAndQuantityMap, m_MinedItem, and ActionData::m_Player.
Referenced by Execute().
CreateSecondaryItems()
void CAContinuousMineWood::CreateSecondaryItems (ActionData action_data, string material_secondary = "", int quantity_secondary = -1) inline private
Definition at line 208 of file cacontinuousminewood.c.
    {
        if (material_secondary == "" || quantity_secondary <= 0)
        {
            return;
        }
        m_SecondaryItem = ItemBase.Cast(GetGame().CreateObjectEx(material_secondary,action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
        if ( !m_SecondaryItem.HasQuantity() )
        {
            CreateSecondaryItems(action_data,material_secondary,quantity_secondary - 1);
            return;
        }
        int increment = quantity_secondary;
        int stack_max = m_SecondaryItem.GetQuantityMax();
        int stacks_amount;// = Math.Ceil(increment/m_SecondaryItem.GetQuantityMax());
        stacks_amount = Math.Ceil(increment/stack_max);
        for (int i = 0; i < stacks_amount; i++)
        {
            if (increment > stack_max)
            {
                m_SecondaryItem.SetQuantity(stack_max);
                increment -= stack_max;
                m_SecondaryItem = ItemBase.Cast(GetGame().CreateObjectEx(material_secondary,action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE));
            }
            else
            {
                m_SecondaryItem.SetQuantity(increment);
            }
        }
    }
References Math::Ceil(), CreateSecondaryItems(), ECE_PLACE_ON_SURFACE, GetGame(), ActionData::m_Player, and m_SecondaryItem.
Referenced by CreateSecondaryItems(), and Execute().
DamagePlayersHands()
void CAContinuousMineWood::DamagePlayersHands (PlayerBase player) inline private
Definition at line 243 of file cacontinuousminewood.c.
    {
        //m_AdjustedDamageToMiningItemEachDrop
        ItemBase gloves = ItemBase.Cast(player.FindAttachmentBySlotName("Gloves"));
        if ( gloves && !gloves.IsDamageDestroyed() )
        {
            gloves.DecreaseHealth("","",m_AdjustedDamageToMiningItemEachDrop);
        }
        else
        {
            int rand = Math.RandomIntInclusive(0,9);
            //Print("rand: " + rand);
            if ( rand == 0 )
            {
                rand = Math.RandomIntInclusive(0,1);
                if ( rand == 0 && !player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll") )
                {
                    player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightForeArmRoll");
                }
                else if ( rand == 1 && !player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("RightForeArmRoll") )
                {
                    player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
                }
            }
        }
    }
References m_AdjustedDamageToMiningItemEachDrop, and Math::RandomIntInclusive().
Referenced by Execute().
Execute()
override int CAContinuousMineWood::Execute (ActionData action_data) inline private
Definition at line 56 of file cacontinuousminewood.c.
    {
        Object targetObject;
        Class.CastTo(targetObject, action_data.m_Target.GetObject());
        if ( !action_data.m_Player || !m_DataLoaded )
        {
            return UA_ERROR;
        }
        if ( (action_data.m_MainItem && action_data.m_MainItem.IsDamageDestroyed()) || targetObject.IsDamageDestroyed() )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_TimeElpased < m_AdjustedTimeBetweenMaterialDrops )
            {
                m_TimeElpased += action_data.m_Player.GetDeltaT();
            }
            else
            {
                if ( GetGame().IsServer() )
                {
                    float damage = 0;
                    if (m_AmountOfDrops > 0)
                        damage = (1 / m_AmountOfDrops) * 100;
                    targetObject.DecreaseHealth("","",damage,true);
                    CreatePrimaryItems(action_data);
                    if (action_data.m_MainItem)
                        action_data.m_MainItem.DecreaseHealth( "", "", m_AdjustedDamageToMiningItemEachDrop );
                    else
                    {
                        DamagePlayersHands(action_data.m_Player);
                    }
                }
                if ( targetObject.IsDamageDestroyed() )
                {
                    if ( m_SpentUnits )
                    {
                        m_SpentUnits.param1 = m_TimeElpased;
                        SetACData(m_SpentUnits);
                    }
                    if ( WoodBase.Cast(targetObject) )
                    {
                        WoodBase target_woodbase = WoodBase.Cast(targetObject);
                        if (target_woodbase.GetSecondaryOutput() != "")
                            CreateSecondaryItems(action_data,target_woodbase.GetSecondaryOutput(),target_woodbase.GetSecondaryDropsAmount());
                    }
                    if (action_data.m_MainItem)
                    {
                        targetObject.OnTreeCutDown( action_data.m_MainItem );
                    }
                    else
                    {
                        targetObject.OnTreeCutDown( action_data.m_Player );
                    }
                    OnCompletePogress(action_data);
                    return UA_FINISHED;
                }
                m_TimeElpased = m_TimeElpased - m_AdjustedTimeBetweenMaterialDrops;
                OnCompletePogress(action_data);
            }
            return UA_PROCESSING;
        }
    }
References Class::CastTo(), CreatePrimaryItems(), CreateSecondaryItems(), DamagePlayersHands(), GetGame(), m_AdjustedDamageToMiningItemEachDrop, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_DataLoaded, ActionData::m_MainItem, ActionData::m_Player, m_SpentUnits, ActionData::m_Target, m_TimeElpased, CAContinuousBase::OnCompletePogress(), CABase::SetACData(), UA_ERROR, UA_FINISHED, UA_PROCESSING, and WoodBase().
GetMiningData()
bool CAContinuousMineWood::GetMiningData (ActionData action_data) inline private
Definition at line 143 of file cacontinuousminewood.c.
    {
        MineActionData adata = MineActionData.Cast(action_data);
        WoodBase ntarget;
        if ( Class.CastTo(ntarget, action_data.m_Target.GetObject()) )
        {
            m_AmountOfDrops = /*Math.Max(1,*/ntarget.GetAmountOfDropsEx(action_data.m_MainItem,adata.m_HarvestType)/*)*/;
            m_CycleTimeOverride = ntarget.GetCycleTimeOverride(); //TODO
            //m_Material = ntarget.GetMaterial(action_data.m_MainItem);
            //m_AmountOfMaterialPerDrop = Math.Max(1,ntarget.GetAmountOfMaterialPerDrop(action_data.m_MainItem));
            ntarget.GetMaterialAndQuantityMapEx(action_data.m_MainItem,m_MaterialAndQuantityMap, adata.m_HarvestType);
            m_DamageToMiningItemEachDrop = ntarget.GetDamageToMiningItemEachDropEx(action_data.m_MainItem, adata.m_HarvestType );
            m_AdjustedDamageToMiningItemEachDrop = action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus( m_DamageToMiningItemEachDrop, m_Action.GetSpecialtyWeight(), true );
            return true;
        }
        return false;
    }
References Class::CastTo(), CABase::m_Action, m_AdjustedDamageToMiningItemEachDrop, m_AmountOfDrops, m_CycleTimeOverride, m_DamageToMiningItemEachDrop, MineActionData::m_HarvestType, ActionData::m_MainItem, m_MaterialAndQuantityMap, ActionData::m_Player, ActionData::m_Target, and WoodBase().
Referenced by Setup().
GetProgress()
override float CAContinuousMineWood::GetProgress () inline private
Definition at line 125 of file cacontinuousminewood.c.
    {
        //float progress = m_TimeElpased/m_AdjustedTimeBetweenMaterialDrops;
        return m_TimeElpased/m_AdjustedTimeBetweenMaterialDrops;
    }
References m_AdjustedTimeBetweenMaterialDrops, and m_TimeElpased.
Setup()
override void CAContinuousMineWood::Setup (ActionData action_data) inline private
Definition at line 26 of file cacontinuousminewood.c.
    {
        m_TimeElpased = 0;
        if ( !m_SpentUnits )
        {
            m_SpentUnits = new Param1<float>(0);
        }
        else
        {
            m_SpentUnits.param1 = 0;
        }
        m_MaterialAndQuantityMap = new map<string,int>;
        m_DataLoaded = GetMiningData(action_data);
        /*
        for(int i = 0; i < m_MaterialAndQuantityMap.Count(); i++)
        {
            Print("material = " + m_MaterialAndQuantityMap.GetKey(i) + "; quantity = " + m_MaterialAndQuantityMap.GetElement(i));
        }
        */
        if (m_CycleTimeOverride > -1.0)
        {
            m_TimeBetweenMaterialDrops = m_CycleTimeOverride;
            if (!action_data.m_MainItem) //hand action
                m_TimeBetweenMaterialDrops = m_TimeBetweenMaterialDrops * 3;
        }
        m_AdjustedTimeBetweenMaterialDrops = action_data.m_Player.GetSoftSkillsManager().SubtractSpecialtyBonus( m_TimeBetweenMaterialDrops, m_Action.GetSpecialtyWeight(), true );
        m_TimeToComplete = m_AmountOfDrops * m_AdjustedTimeBetweenMaterialDrops;
    }
References GetMiningData(), CABase::m_Action, m_AdjustedTimeBetweenMaterialDrops, m_AmountOfDrops, m_CycleTimeOverride, m_DataLoaded, ActionData::m_MainItem, m_MaterialAndQuantityMap, ActionData::m_Player, m_SpentUnits, m_TimeBetweenMaterialDrops, m_TimeElpased, and m_TimeToComplete.
Member Data Documentation
m_AdjustedDamageToMiningItemEachDrop
protected float CAContinuousMineWood::m_AdjustedDamageToMiningItemEachDrop private
Definition at line 8 of file cacontinuousminewood.c.
Referenced by DamagePlayersHands(), Execute(), CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_AdjustedTimeBetweenMaterialDrops
protected float CAContinuousMineWood::m_AdjustedTimeBetweenMaterialDrops private
Definition at line 4 of file cacontinuousminewood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_AmountOfDrops
protected int CAContinuousMineWood::m_AmountOfDrops private
Definition at line 9 of file cacontinuousminewood.c.
Referenced by Execute(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_CycleTimeOverride
protected float CAContinuousMineWood::m_CycleTimeOverride private
Definition at line 5 of file cacontinuousminewood.c.
Referenced by CAContinuousMineWood(), GetMiningData(), and Setup().
m_DamageToMiningItemEachDrop
protected float CAContinuousMineWood::m_DamageToMiningItemEachDrop private
Definition at line 7 of file cacontinuousminewood.c.
Referenced by CAContinuousMineRock::GetMiningData(), and GetMiningData().
m_DataLoaded
protected bool CAContinuousMineWood::m_DataLoaded = false private
Definition at line 15 of file cacontinuousminewood.c.
Referenced by Execute(), and Setup().
m_MaterialAndQuantityMap
protected ref map<string,int> CAContinuousMineWood::m_MaterialAndQuantityMap private
Definition at line 12 of file cacontinuousminewood.c.
Referenced by CreatePrimaryItems(), CAContinuousMineRock::GetMiningData(), GetMiningData(), and Setup().
m_MinedItem
protected ItemBase CAContinuousMineWood::m_MinedItem[MINEDITEM_MAX] private
Definition at line 17 of file cacontinuousminewood.c.
Referenced by CreatePrimaryItems().
m_SecondaryItem
protected ItemBase CAContinuousMineWood::m_SecondaryItem private
Definition at line 18 of file cacontinuousminewood.c.
Referenced by CreateSecondaryItems().
m_SpentUnits
protected ref Param1<float> CAContinuousMineWood::m_SpentUnits private
Definition at line 14 of file cacontinuousminewood.c.
Referenced by Execute(), and Setup().
m_TimeBetweenMaterialDrops
protected float CAContinuousMineWood::m_TimeBetweenMaterialDrops private
Definition at line 6 of file cacontinuousminewood.c.
Referenced by CAContinuousMineRock::CAContinuousMineRock(), CAContinuousMineWood(), and Setup().
m_TimeElpased
protected float CAContinuousMineWood::m_TimeElpased private
Definition at line 3 of file cacontinuousminewood.c.
Referenced by Execute(), GetProgress(), and Setup().
m_TimeToComplete
protected float CAContinuousMineWood::m_TimeToComplete private
Definition at line 13 of file cacontinuousminewood.c.
Referenced by Setup().
MINEDITEM_MAX
protected const int CAContinuousMineWood::MINEDITEM_MAX = 5 private
Definition at line 16 of file cacontinuousminewood.c.