DayzKode: InventoryInputUserData Class Reference
InventoryInputUserData Class Reference
Static Private Member Functions
static void SendInputUserDataDestroy (notnull InventoryLocation src)
static void SerializeDestroy (ParamsWriteContext ctx, notnull InventoryLocation src)
static void SerializeMove (ParamsWriteContext ctx, int type, notnull InventoryLocation src, notnull InventoryLocation dst)
move
static void SendInputUserDataMove (int type, notnull InventoryLocation src, notnull InventoryLocation dst)
static void SendServerMove (Man player, int type, notnull InventoryLocation src, notnull InventoryLocation dst)
static void SerializeSwap (ParamsWriteContext ctx, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap)
swap
static void SendInputUserDataSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap=false)
static void SendServerSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap=false)
static void SerializeHandEvent (ParamsWriteContext ctx, HandEventBase e)
hand
static void SendInputUserDataHandEvent (HandEventBase e)
static void SendServerHandEventViaInventoryCommand (notnull Man player, HandEventBase e)
Detailed Description
Definition at line 2 of file inventoryinputuserdata.c.
Member Function Documentation
SendInputUserDataDestroy()
static void InventoryInputUserData::SendInputUserDataDestroy (notnull InventoryLocation src) inline static private
Definition at line 114 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsClient())
        {
            syncDebugPrint("[syncinv] SendInputUserDataDestroy src=" + InventoryLocation.DumpToStringNullSafe(src));
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeDestroy(ctx, src);
            ctx.Send();
        }
    }
References InventoryLocation::DumpToStringNullSafe(), GetGame(), ScriptInputUserData::Send(), SerializeDestroy(), and syncDebugPrint().
SendInputUserDataHandEvent()
static void InventoryInputUserData::SendInputUserDataHandEvent (HandEventBase e) inline static private
Definition at line 79 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsClient())
        {
            syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms SendInputUserDataHandEvent e=" + e.DumpToString());
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeHandEvent(ctx, e);
            ctx.Send();
        }
    }
References HandEventBase::DumpToString(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeHandEvent(), and syncDebugPrint().
Referenced by HandleHandEvent().
SendInputUserDataMove()
static void InventoryInputUserData::SendInputUserDataMove (int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
Definition at line 13 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsClient())
        {
            syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms sending cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeMove(ctx, type, src, dst);
            ctx.Send();
        }
    }
References InventoryLocation::DumpToStringNullSafe(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeMove(), and syncDebugPrint().
Referenced by HandleTakeToDst().
SendInputUserDataSwap()
static void InventoryInputUserData::SendInputUserDataSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap = false) inline static private
Definition at line 48 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsClient())
        {
            syncDebugPrint("[syncinv] t=" + GetGame().GetTime() + "ms sending cmd=SWAP src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeSwap(ctx, src1, src2, dst1, dst2, skippedSwap);
            ctx.Send();
        }
    }
References InventoryLocation::DumpToStringNullSafe(), GetGame(), GetTime(), ScriptInputUserData::Send(), SerializeSwap(), and syncDebugPrint().
Referenced by HandleForceSwapEntities(), and HandleSwapEntities().
SendServerHandEventViaInventoryCommand()
static void InventoryInputUserData::SendServerHandEventViaInventoryCommand (notnull Man player, HandEventBase e) inline static private
Definition at line 90 of file inventoryinputuserdata.c.
    {
        // Warning: this uses NetworkMessageInventoryCommand
        if (GetGame().IsServer())
        {
            if (e.IsServerSideOnly())
                Error("[syncinv] SendServerHandEvent - called on server side event only, e=" + e.DumpToString());
            if (player.IsAlive())
                Error("[syncinv] SendServerHandEvent - called on living thing.. server hand command is only for dead people, e=" + e.DumpToString());
            syncDebugPrint("[syncinv] SendServerHandEventViaInventoryCommand SendInputUserDataHandEvent e=" + e.DumpToString());
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeHandEvent(ctx, e);
            GameInventory.ServerHandEvent(player, e.GetSrcEntity(), ctx);
        }
    }
References HandEventBase::DumpToString(), Error(), GetGame(), HandEventBase::IsServerSideOnly(), SerializeHandEvent(), and syncDebugPrint().
Referenced by HandleHandEvent().
SendServerMove()
static void InventoryInputUserData::SendServerMove (Man player, int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
Definition at line 24 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsServer())
        {
            syncDebugPrint("[syncinv] server sending cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeMove(ctx, type, src, dst);
            GameInventory.ServerLocationSyncMoveEntity(player, src.GetItem(), ctx);
        }
    }
References InventoryLocation::DumpToStringNullSafe(), GetGame(), SerializeMove(), and syncDebugPrint().
Referenced by TakeToDst().
SendServerSwap()
static void InventoryInputUserData::SendServerSwap (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap = false) inline static private
Definition at line 59 of file inventoryinputuserdata.c.
    {
        if (GetGame().IsServer())
        {
            syncDebugPrint("[syncinv] server sending cmd=SWAP src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
            ScriptInputUserData ctx = new ScriptInputUserData;
            SerializeSwap(ctx, src1, src2, dst1, dst2, skippedSwap);
            GameInventory.ServerLocationSwap(src1, src2, dst1, dst2, ctx);
        }
    }
References InventoryLocation::DumpToStringNullSafe(), GetGame(), SerializeSwap(), and syncDebugPrint().
SerializeDestroy()
static void InventoryInputUserData::SerializeDestroy (ParamsWriteContext ctx, notnull InventoryLocation src) inline static private
Definition at line 107 of file inventoryinputuserdata.c.
    {
        ctx.Write(INPUT_UDT_INVENTORY);
        ctx.Write(InventoryCommandType.DESTROY);
        src.WriteToContext(ctx);
    }
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by SendInputUserDataDestroy().
SerializeHandEvent()
static void InventoryInputUserData::SerializeHandEvent (ParamsWriteContext ctx, HandEventBase e) inline static private
hand
Definition at line 72 of file inventoryinputuserdata.c.
    {
        ctx.Write(INPUT_UDT_INVENTORY);
        ctx.Write(InventoryCommandType.HAND_EVENT);
        e.WriteToContext(ctx);
    }
References INPUT_UDT_INVENTORY, Serializer::Write(), and HandEventBase::WriteToContext().
Referenced by OnUpdate(), SendInputUserDataHandEvent(), SendServerHandEventViaInventoryCommand(), and SendServerHandEventViaJuncture().
SerializeMove()
static void InventoryInputUserData::SerializeMove (ParamsWriteContext ctx, int type, notnull InventoryLocation src, notnull InventoryLocation dst) inline static private
move
Definition at line 5 of file inventoryinputuserdata.c.
    {
        ctx.Write(INPUT_UDT_INVENTORY);
        ctx.Write(type);
        src.WriteToContext(ctx);
        dst.WriteToContext(ctx);
    }
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by OnUpdate(), SendInputUserDataMove(), SendServerMove(), and TakeToDst().
SerializeSwap()
static void InventoryInputUserData::SerializeSwap (ParamsWriteContext ctx, notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, bool skippedSwap) inline static private
swap
Definition at line 37 of file inventoryinputuserdata.c.
    {
        ctx.Write(INPUT_UDT_INVENTORY);
        ctx.Write(InventoryCommandType.SWAP);
        src1.WriteToContext(ctx);
        src2.WriteToContext(ctx);
        dst1.WriteToContext(ctx);
        dst2.WriteToContext(ctx);
        ctx.Write(skippedSwap);
    }
References INPUT_UDT_INVENTORY, and Serializer::Write().
Referenced by ProccessInputData(), SendInputUserDataSwap(), and SendServerSwap().