DayzKode: ZombieContainer Class Reference
ZombieContainer Class Reference
Private Member Functions
void AddSlotsContainer (int row_count)
override void CollapseButtonOnMouseButtonDown (Widget w)
void DoubleClick (Widget w, int x, int y, int button)
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override bool EquipItem ()
override void ExpandCollapseContainer ()
SlotsIcon GetSlotsIcon (int row, int column)
Widget GetWidgetSlot (int slot_number)
void InitGhostSlots ()
bool IsContainerWithCargoActive ()
bool IsEmptyItemActive ()
bool IsItemWithAttachmentsActive ()
bool IsItemWithContainerActive ()
override bool IsItemWithQuantityActive ()
bool IsZombieEquipmentActive ()
void ItemAttached (EntityAI item, string slot_name)
void ItemDetached (EntityAI item, string slot_name)
void OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver)
override void OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver)
override bool Select ()
void SetEntity (EntityAI zombie_entity)
void SetHeaderName ()
override bool SplitItem ()
void ToggleContainer (Widget w)
override bool TransferItem ()
override bool TransferItemToVicinity ()
override void UpdateRadialIcon ()
void ZombieContainer (LayoutHolder parent, int sort=-1)
void ~ZombieContainer ()
Private Attributes
protected ref ContainerWithCargo m_CargoGrid
protected ref AttachmentsGroupContainer m_Container
protected ref map< int, SlotsIcon > m_InventorySlots
protected ref map< EntityAI, ref Container > m_ShowedItems = new ref map<EntityAI, ref Container>
protected EntityAI m_ZombieEntity
Detailed Description
Definition at line 1 of file zombiecontainer.c.
Constructor & Destructor Documentation
ZombieContainer()
void ZombieContainer::ZombieContainer (LayoutHolder parent, int sort = -1) inline private
Definition at line 9 of file zombiecontainer.c.
    {
        m_InventorySlots = new ref map<int, SlotsIcon>;
        m_Container = new AttachmentsGroupContainer(this);
        m_Container.SetHeader(GetHeader());
        SetHeaderName();
        SetHeader(null);
        m_Body.Insert( m_Container );
        m_MainWidget = m_RootWidget.FindAnyWidget( "body" );
        WidgetEventHandler.GetInstance().RegisterOnChildAdd( m_MainWidget, this, "OnChildAdd" );
        WidgetEventHandler.GetInstance().RegisterOnChildRemove( m_MainWidget, this, "OnChildRemove" );
        RecomputeOpenedContainers();
    }
References CollapsibleContainer::GetHeader(), WidgetEventHandler::GetInstance(), m_Container, m_InventorySlots, m_RootWidget, WidgetEventHandler::RegisterOnChildAdd(), WidgetEventHandler::RegisterOnChildRemove(), AttachmentsGroupContainer::SetHeader(), CollapsibleContainer::SetHeader(), and SetHeaderName().
~ZombieContainer()
void ZombieContainer::~ZombieContainer () inline private
Definition at line 28 of file zombiecontainer.c.
    {
        if( m_ZombieEntity )
        {
            m_ZombieEntity.GetOnItemAttached().Remove(ItemAttached);
            m_ZombieEntity.GetOnItemDetached().Remove(ItemDetached);
        }
    }
References ItemAttached(), ItemDetached(), and m_ZombieEntity.
Member Function Documentation
AddSlotsContainer()
void ZombieContainer::AddSlotsContainer (int row_count) inline private
Definition at line 458 of file zombiecontainer.c.
    {
        ref SlotsContainer s_cont = new SlotsContainer( m_Container, m_ZombieEntity );
        s_cont.SetColumnCount( row_count );
        m_Container.Insert( s_cont );
    }
References m_Container, and m_ZombieEntity.
Referenced by InitGhostSlots().
CollapseButtonOnMouseButtonDown()
override void ZombieContainer::CollapseButtonOnMouseButtonDown (Widget w) inline private
Definition at line 542 of file zombiecontainer.c.
    {
        super.CollapseButtonOnMouseButtonDown(w);
    }
DoubleClick()
void ZombieContainer::DoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 473 of file zombiecontainer.c.
    {
        if( button == MouseState.LEFT )
        {
            if( w == null )
            {
                return;
            }
            ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
            if( !iw )
            {
                string name = w.GetName();
                name.Replace( "PanelWidget", "Render" );
                iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
            }
            if( !iw )
            {
                iw = ItemPreviewWidget.Cast( w );
            }
            ItemBase item = ItemBase.Cast( iw.GetItem() );
            if( !item )
            {
                return;
            }
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if( player.GetInventory().HasInventoryReservation( item, null ) || player.IsItemsToDelete() )
            {
                return;
            }
            if( !item.GetInventory().CanRemoveEntity() )
                return;
            if ( player.GetInventory().HasEntityInInventory( item ) && GetGame().GetPlayer().GetHumanInventory().CanAddEntityInHands( item ) )
            {
                player.PredictiveTakeEntityToHands( item );
            }
            else
            {
                InventoryLocation il = new InventoryLocation;
                if( player.GetInventory().FindFreeLocationFor( item, FindInventoryLocationType.ANY, il) )
                {
                    if( item.GetTargetQuantityMax(il.GetSlot()) < item.GetQuantity() )
                        item.SplitIntoStackMaxToInventoryLocationClient( il );
                    else
                        player.PredictiveTakeEntityToInventory( FindInventoryLocationType.ANY, item );
                }
                else if( GetGame().GetPlayer().GetHumanInventory().CanAddEntityInHands( item ) )
                {
                    if( item.GetTargetQuantityMax() < item.GetQuantity() )
                        item.SplitIntoStackMaxHandsClient( player );
                    else
                        player.PredictiveTakeEntityToHands( item );
                }
            }
            HideOwnedTooltip();
            InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu( MENU_INVENTORY ) );
            if( menu )
            {
                menu.RefreshQuickbar();
            }
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), InventoryLocation::GetSlot(), InventoryMenu(), MENU_INVENTORY, name, and string::Replace().
DraggingOverHeader()
override void ZombieContainer::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 134 of file zombiecontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast(w.FindAnyWidget( "Render" ));
        string name = receiver.GetName();
        name.Replace("PanelWidget", "Render");
        ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget( name ) );
        EntityAI receiver_item;
        if (receiver_iw)
        {
            receiver_item = receiver_iw.GetItem();
        }
        if(!ipw)
        {
            name = w.GetName();
            name.Replace("PanelWidget", "Render");
            ipw = ItemPreviewWidget.Cast(w.FindAnyWidget(name));
        }
        if(!ipw)
        {
          ipw = ItemPreviewWidget.Cast(w);
        }
        if( !ipw.IsInherited(ItemPreviewWidget))
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if(!item.GetInventory().CanRemoveEntity())
            return;
    }
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), name, and string::Replace().
EquipItem()
override bool ZombieContainer::EquipItem () inline private
Definition at line 557 of file zombiecontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().EquipItem();
        }
        else
        {
            EntityAI item = GetFocusedItem();
            if( item )
            {
                GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.ATTACHMENT, item );
                return true;
            }
        }
        return false;
    }
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
ExpandCollapseContainer()
override void ZombieContainer::ExpandCollapseContainer () inline private
Definition at line 93 of file zombiecontainer.c.
    {
        if( IsZombieEquipmentActive() )
        {
            ItemPreviewWidget item_preview = GetFocusedSlotsIcon().GetRender();
            ToggleContainer( item_preview.GetParent() );
        }
    }
References IsZombieEquipmentActive(), and ToggleContainer().
GetSlotsIcon()
SlotsIcon ZombieContainer::GetSlotsIcon (int row, int column) inline private
Definition at line 347 of file zombiecontainer.c.
    {
        return SlotsContainer.Cast( m_Container.Get( row ) ).GetSlotIcon( column );
    }
References Container::Get(), SlotsContainer::GetSlotIcon(), and m_Container.
Referenced by InitGhostSlots().
GetWidgetSlot()
Widget ZombieContainer::GetWidgetSlot (int slot_number) inline private
Definition at line 465 of file zombiecontainer.c.
    {
        int row = slot_number / ITEMS_IN_ROW;
        int column = slot_number % ITEMS_IN_ROW;
        return m_Container.Get( row ).GetMainWidget().FindAnyWidget( "Render" + column );
    }
References Container::Get(), ITEMS_IN_ROW, and m_Container.
InitGhostSlots()
void ZombieContainer::InitGhostSlots () inline private
Definition at line 352 of file zombiecontainer.c.
    {
        int row, column;
        SlotsIcon icon;
        bool has_cargo = m_ZombieEntity.GetInventory().GetCargo() != null;
        string config_path_ghosts_slots = "CfgVehicles ZombieBase InventoryEquipment playerSlots";
        ref array<string> player_ghosts_slots = new array<string>;
        GetGame().ConfigGetTextArray( config_path_ghosts_slots, player_ghosts_slots );
        for ( int i = 0; i < player_ghosts_slots.Count(); i++ )
        {
            string slot_name = player_ghosts_slots.Get ( i );
            string path = "CfgSlots" + " " + slot_name;
            if ( GetGame().ConfigIsExisting( path ) )
            {
                string icon_name; //icon_name must be in format "set:<setname> image:<imagename>"
                GetGame().ConfigGetText( path + " ghostIcon", icon_name );
                column = i % ITEMS_IN_ROW;
                //START - GetWidgetSlot
                row = i / ITEMS_IN_ROW;
                if( row >= m_Container.Count() )
                {
                    if ( has_cargo )
                    {
                        if( row < ( (player_ghosts_slots.Count() + 1 )/ ITEMS_IN_ROW ) )
                            AddSlotsContainer( ITEMS_IN_ROW );
                        else
                            AddSlotsContainer( ( player_ghosts_slots.Count() + 1 ) % ITEMS_IN_ROW );
                    }
                    else
                    {
                        if ( row < ( player_ghosts_slots.Count() / ITEMS_IN_ROW ) )
                            AddSlotsContainer( ITEMS_IN_ROW );
                        else
                            AddSlotsContainer( player_ghosts_slots.Count() % ITEMS_IN_ROW );
                    }
                }
                icon = GetSlotsIcon( row, column );
                icon.GetMainWidget().Show( true );
                icon.Clear();
                WidgetEventHandler.GetInstance().RegisterOnDoubleClick( icon.GetPanelWidget(),  this, "DoubleClick" );
                //END - GetWidgetSlot
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetPanelWidget(),  this, "OnDropReceivedFromGhostArea" );
                WidgetEventHandler.GetInstance().RegisterOnDropReceived( icon.GetGhostSlot(),  this, "OnDropReceivedFromGhostArea" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetPanelWidget(),  this, "DraggingOver" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetGhostSlot(),  this, "DraggingOver" );
                WidgetEventHandler.GetInstance().RegisterOnDraggingOver( icon.GetPanelWidget(),  this, "DraggingOver" );
                WidgetEventHandler.GetInstance().RegisterOnMouseButtonDown( icon.GetPanelWidget(),  this, "MouseClick" );
                icon.GetGhostSlot().LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,icon_name) );
                //END - LoadIconIntoWidgetSlot
                GetGame().ConfigGetText( path + " name", slot_name );
                int slot_id = InventorySlots.GetSlotIdFromString( slot_name );
                icon.SetSlotID( slot_id );
                icon.SetSlotDisplayName(InventorySlots.GetSlotDisplayName(slot_id));
                m_InventorySlots.Set( slot_id, icon );
                int slot = InventorySlots.GetSlotIdFromString( slot_name );
                ItemBase item = ItemBase.Cast( m_ZombieEntity.GetInventory().FindAttachment( slot ) );
                if( item )
                    ItemAttached( item, slot_name );
            }
        }
        if( m_ZombieEntity.GetInventory().GetCargo() )
        {
            row = player_ghosts_slots.Count() / ITEMS_IN_ROW;
            column = player_ghosts_slots.Count() % ITEMS_IN_ROW;
            if( row >= m_Container.Count() )
            {
                if( row < ( player_ghosts_slots.Count() + 1 / ITEMS_IN_ROW ) )
                    AddSlotsContainer( ITEMS_IN_ROW );
                else
                    AddSlotsContainer( ( player_ghosts_slots.Count() + 1 ) % ITEMS_IN_ROW );
            }
            icon = GetSlotsIcon( row, column );
            icon.GetMainWidget().Show( true );
            icon.Clear();
            icon.GetGhostSlot().LoadImageFile( 0, StaticGUIUtils.VerifyIconImageString(StaticGUIUtils.IMAGESETGROUP_INVENTORY,m_ZombieEntity.ConfigGetString("GUIInventoryCargoIcon")) );
            icon.SetSlotDisplayName( m_ZombieEntity.ConfigGetString("GUIInventoryCargoName") );
            icon.GetRadialIconPanel().Show( true );
            icon.GetRadialIcon().Show( true );
            WidgetEventHandler.GetInstance().RegisterOnMouseButtonUp( icon.GetGhostSlot(), this, "ToggleContainer" );
            m_CargoGrid = new ContainerWithCargo( this, false );
            m_CargoGrid.SetEntity( m_ZombieEntity );
            m_CargoGrid.GetHeader().GetMainWidget().ClearFlags( WidgetFlags.DRAGGABLE );
            m_ShowedItems.Insert( m_ZombieEntity, m_CargoGrid );
            icon.SetContainer(m_CargoGrid);
        }
        RecomputeOpenedContainers();
    }
References AddSlotsContainer(), SlotsIcon::Clear(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), SlotsIcon::GetGhostSlot(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIcon(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotDisplayName(), InventorySlots::GetSlotIdFromString(), GetSlotsIcon(), StaticGUIUtils::IMAGESETGROUP_INVENTORY, ItemAttached(), ITEMS_IN_ROW, m_CargoGrid, m_Container, m_InventorySlots, m_ShowedItems, m_ZombieEntity, path, WidgetEventHandler::RegisterOnDoubleClick(), WidgetEventHandler::RegisterOnDraggingOver(), WidgetEventHandler::RegisterOnDropReceived(), WidgetEventHandler::RegisterOnMouseButtonDown(), WidgetEventHandler::RegisterOnMouseButtonUp(), SlotsIcon::SetContainer(), SlotsIcon::SetSlotDisplayName(), SlotsIcon::SetSlotID(), and StaticGUIUtils::VerifyIconImageString().
Referenced by SetEntity().
IsContainerWithCargoActive()
bool ZombieContainer::IsContainerWithCargoActive () inline private
Definition at line 67 of file zombiecontainer.c.
    {
        return GetFocusedContainer().IsInherited( ContainerWithCargo );
    }
Referenced by UpdateConsoleToolbar().
IsEmptyItemActive()
bool ZombieContainer::IsEmptyItemActive () inline private
Definition at line 88 of file zombiecontainer.c.
    {
        return !GetFocusedItem();
    }
References Container::GetFocusedItem().
Referenced by UpdateConsoleToolbar().
IsItemWithAttachmentsActive()
bool ZombieContainer::IsItemWithAttachmentsActive () inline private
Definition at line 72 of file zombiecontainer.c.
    {
        return GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments );
    }
Referenced by UpdateConsoleToolbar().
IsItemWithContainerActive()
bool ZombieContainer::IsItemWithContainerActive () inline private
Definition at line 82 of file zombiecontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent && ( ent.GetInventory().GetCargo() || ent.GetSlotsCountCorrect() > 0 );
    }
References Container::GetFocusedItem().
Referenced by UpdateConsoleToolbar().
IsItemWithQuantityActive()
override bool ZombieContainer::IsItemWithQuantityActive () inline private
Definition at line 61 of file zombiecontainer.c.
    {
        EntityAI ent = GetFocusedItem();
        return ent && QuantityConversions.HasItemQuantity( ent ) && ent.CanBeSplit();
    }
References Container::GetFocusedItem(), and QuantityConversions::HasItemQuantity().
IsZombieEquipmentActive()
bool ZombieContainer::IsZombieEquipmentActive () inline private
Definition at line 77 of file zombiecontainer.c.
    {
        return GetFocusedContainer() == m_Container;
    }
References m_Container.
Referenced by ExpandCollapseContainer(), and UpdateConsoleToolbar().
ItemAttached()
void ZombieContainer::ItemAttached (EntityAI item, string slot_name) inline private
Definition at line 245 of file zombiecontainer.c.
    {
        int slot = InventorySlots.GetSlotIdFromString( slot_name );
        SlotsIcon icon = m_InventorySlots.Get( slot );
        if( icon )
        {
            icon.Init( item );
            if( m_ShowedItems.Contains( item ) == false )
            {
                string name;
                if( item.GetSlotsCountCorrect() > 0 )
                {
                    ContainerWithCargoAndAttachments iwca = new ContainerWithCargoAndAttachments( this, false );
                    iwca.SetEntity( item );
                    WidgetEventHandler.GetInstance().RegisterOnMouseButtonUp( icon.GetPanelWidget(),  this, "ToggleContainer" );
                    icon.GetRadialIconPanel().Show( true );
                    m_ShowedItems.Insert( item, iwca );
                    Refresh();
                }
                else if( item.GetInventory().GetCargo() )
                {
                    ContainerWithCargo iwc = new ContainerWithCargo( this, false );
                    iwc.SetEntity( item );
                    iwc.UpdateInterval();
                    WidgetEventHandler.GetInstance().RegisterOnMouseButtonUp( icon.GetPanelWidget(),  this, "ToggleContainer" );
                    m_ShowedItems.Insert( item, iwc );
                    icon.GetRadialIconPanel().Show(true);
                    Refresh();
                }
            }
            ClosableContainer conta = ClosableContainer.Cast( m_ShowedItems.Get( item ) );
            string config = "CfgVehicles " + item.GetType() + " GUIInventoryAttachmentsProps";
            if( conta && conta.IsInherited( ClosableContainer ) )
            {
                bool show_radial_icon = ( item.GetInventory().GetCargo() || item.GetSlotsCountCorrect() > 0 ) && !GetGame().ConfigIsExisting( config );
                Widget rip = icon.GetRadialIconPanel();
                Widget icon_open = icon.GetRadialIcon();
                Widget icon_closed = icon.GetRadialIconClosed();
                rip.Show( show_radial_icon );
                icon_open.Show( conta.IsOpened() );
                icon_closed.Show( !conta.IsOpened() );
            }
            RecomputeOpenedContainers();
        }
    }
References CGame::ConfigIsExisting(), GetGame(), WidgetEventHandler::GetInstance(), SlotsIcon::GetPanelWidget(), SlotsIcon::GetRadialIcon(), SlotsIcon::GetRadialIconClosed(), SlotsIcon::GetRadialIconPanel(), InventorySlots::GetSlotIdFromString(), SlotsIcon::Init(), ClosableContainer::IsOpened(), m_InventorySlots, m_ShowedItems, name, CollapsibleContainer::Refresh(), and WidgetEventHandler::RegisterOnMouseButtonUp().
Referenced by InitGhostSlots(), SetEntity(), and ~ZombieContainer().
ItemDetached()
void ZombieContainer::ItemDetached (EntityAI item, string slot_name) inline private
Definition at line 297 of file zombiecontainer.c.
    {
        int slot = InventorySlots.GetSlotIdFromString( slot_name );
        SlotsIcon icon = m_InventorySlots.Get( slot );
        if( icon )
        {
            Container con = m_ShowedItems.Get( item );
            if( con )
            {
                ( Container.Cast( con.m_Parent ) ).Remove( con );
                RecomputeOpenedContainers();
                GetMainWidget().Update();
                Refresh();
                m_ShowedItems.Remove( item );
            }
            icon.Clear();
            Inventory in = Inventory.Cast( GetRoot() );
            if( in )
                in.UpdateConsoleToolbar();
        }
    }
References SlotsIcon::Clear(), InventorySlots::GetSlotIdFromString(), Inventory(), m_InventorySlots, m_ShowedItems, CollapsibleContainer::Refresh(), and CollapsibleContainer::Remove().
Referenced by SetEntity(), and ~ZombieContainer().
OnDropReceivedFromGhostArea()
void ZombieContainer::OnDropReceivedFromGhostArea (Widget w, int x, int y, Widget receiver) inline private
Definition at line 169 of file zombiecontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget("Render"));
        string name = receiver.GetName();
        name.Replace("PanelWidget", "Render");
        ItemPreviewWidget receiver_iw = ItemPreviewWidget.Cast( receiver.FindAnyWidget(name));
        EntityAI receiver_item;
        if (receiver_iw)
        {
            receiver_item = receiver_iw.GetItem();
        }
        if( !ipw )
        {
            name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            ipw = ItemPreviewWidget.Cast( w.FindAnyWidget(name));
        }
        if(!ipw)
        {
          ipw = ItemPreviewWidget.Cast(w);
        }
        if(!ipw.IsInherited(ItemPreviewWidget))
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if(!item.GetInventory().CanRemoveEntity())
        {
            return;
        }
        if(receiver_item)
        {
            if(receiver_item.GetInventory().CanAddAttachment(item))
            {
                player.PredictiveTakeEntityToTargetAttachment(receiver_item, item);
                return;
            }
            else if(receiver_item.GetInventory().CanAddEntityInCargo(item, item.GetInventory().GetFlipCargo()) && !receiver_item.GetInventory().HasEntityInCargo(item))
            {
                player.PredictiveTakeEntityToTargetInventory(receiver_item, FindInventoryLocationType.ANY, item);
                return;
            }
        }
        if(item)
        {
            if(m_ZombieEntity.GetInventory().CanAddAttachment(item))
            {
                player.PredictiveTakeEntityToTargetAttachment(m_ZombieEntity, item);
            }
            else if(m_ZombieEntity.GetInventory().CanAddEntityToInventory(item))
            {
                player.PredictiveTakeEntityToTargetInventory(m_ZombieEntity, FindInventoryLocationType.ANY, item);
            }
        }
        if( item )
        {
            if( m_ZombieEntity.GetInventory().CanAddEntityInto(item, FindInventoryLocationType.CARGO ))
            {
                player.PredictiveTakeEntityToTargetInventory(m_ZombieEntity, FindInventoryLocationType.CARGO, item);
            }
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), GetPlayer(), m_ZombieEntity, name, and string::Replace().
OnDropReceivedFromHeader()
override void ZombieContainer::OnDropReceivedFromHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 102 of file zombiecontainer.c.
    {
        ItemPreviewWidget ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !ipw )
        {
          string name = w.GetName();
          name.Replace( "PanelWidget", "Render" );
          ipw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !ipw )
        {
          ipw = ItemPreviewWidget.Cast( w );
        }
        if( !ipw.IsInherited( ItemPreviewWidget ) )
        {
            return;
        }
        EntityAI item = ipw.GetItem();
        if( !item.GetInventory().CanRemoveEntity() )
            return;
        if (m_ZombieEntity.GetInventory().CanAddEntityInCargo( item, item.GetInventory().GetFlipCargo() ))
            GetGame().GetPlayer().PredictiveTakeEntityToTargetCargo( m_ZombieEntity, item );
        else if( m_ZombieEntity.GetInventory().CanAddEntityToInventory( item ) )
        {
            GetGame().GetPlayer().PredictiveTakeEntityToTargetInventory( m_ZombieEntity, FindInventoryLocationType.CARGO, item );
        }
    }
References GetGame(), ItemPreviewWidget::GetItem(), CGame::GetPlayer(), m_ZombieEntity, name, and string::Replace().
Select()
override bool ZombieContainer::Select () inline private
Definition at line 610 of file zombiecontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().Select();
        }
        else
        {
            SlotsIcon selected_slot = ItemManager.GetInstance().GetSelectedIcon();
            EntityAI focused_item = GetFocusedItem();
            EntityAI selected_item = ItemManager.GetInstance().GetSelectedItem();
            if( !(selected_slot && selected_slot.IsOutOfReach() ) )
            {
                if( selected_item )
                {
                    if( selected_item != focused_item)
                    {
                        if( selected_item.GetInventory().CanRemoveEntity() )
{
                            GetGame().GetPlayer().PredictiveTakeEntityToTargetInventory( m_ZombieEntity, FindInventoryLocationType.ANY, selected_item );
                            ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
                            return true;
                        }
                    }
                }
                else
                {
                    if( focused_item && focused_item.GetInventory().CanRemoveEntity() )
                    {
                        EntityAI item_in_hands = GetGame().GetPlayer().GetHumanInventory().GetEntityInHands();
                        if( item_in_hands && item_in_hands.GetInventory().CanRemoveEntity() )
{
                            if( GameInventory.CanSwapEntitiesEx( item_in_hands, focused_item ) )
{
                                GetGame().GetPlayer().PredictiveSwapEntities( item_in_hands, focused_item );
                                return true;
                            }
                            else
{
                                InventoryLocation il_hands_dst = new InventoryLocation;
                                if( GetGame().GetPlayer().GetHumanInventory().FindFreeLocationFor( item_in_hands, FindInventoryLocationType.ANY, il_hands_dst ) )
{
                                    InventoryMode invMode = InventoryMode.PREDICTIVE;
                                    if ( GetGame().GetPlayer().NeedInventoryJunctureFromServer(item_in_hands, item_in_hands.GetHierarchyParent(), il_hands_dst.GetParent()) || GetGame().GetPlayer().NeedInventoryJunctureFromServer(focused_item, focused_item.GetHierarchyParent(), GetGame().GetPlayer()) )
                                        invMode = InventoryMode.JUNCTURE;
                                    GetGame().GetPlayer().GetHumanInventory().ForceSwapEntities( InventoryMode.JUNCTURE, focused_item, item_in_hands, il_hands_dst );
                                    return true;
                                }
                            }
                        }
                        else
{
                            if( GetGame().GetPlayer().GetHumanInventory().CanAddEntityInHands( focused_item ) )
{
                                GetGame().GetPlayer().PredictiveTakeEntityToHands( focused_item );
                                return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
References FindFreeLocationFor(), Container::GetFocusedItem(), GetGame(), ItemManager::GetInstance(), InventoryLocation::GetParent(), CGame::GetPlayer(), GetPlayer(), ItemManager::GetSelectedIcon(), ItemManager::GetSelectedItem(), SlotsIcon::IsOutOfReach(), m_ZombieEntity, and ItemManager::SetSelectedItem().
SetEntity()
void ZombieContainer::SetEntity (EntityAI zombie_entity) inline private
Definition at line 37 of file zombiecontainer.c.
    {
        m_ZombieEntity = zombie_entity;
        m_ZombieEntity.GetOnItemAttached().Insert(ItemAttached);
        m_ZombieEntity.GetOnItemDetached().Insert(ItemDetached);
        InitGhostSlots();
        m_Parent.Refresh();
    }
References InitGhostSlots(), ItemAttached(), ItemDetached(), m_Parent, and m_ZombieEntity.
Referenced by VicinityContainer::UpdateInterval().
SetHeaderName()
void ZombieContainer::SetHeaderName () inline private
Definition at line 240 of file zombiecontainer.c.
    {
        m_CollapsibleHeader.SetName( "#container_inventory" );
    }
References CollapsibleContainer::m_CollapsibleHeader, and Header::SetName().
Referenced by ZombieContainer().
SplitItem()
override bool ZombieContainer::SplitItem () inline private
Definition at line 547 of file zombiecontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().SplitItem();
        }
        return false;
    }
ToggleContainer()
void ZombieContainer::ToggleContainer (Widget w) inline private
Definition at line 322 of file zombiecontainer.c.
    {
        EntityAI item;
        SlotsIcon slots_icon;
        ClosableContainer c;
        w.GetUserData(slots_icon);
        if (slots_icon)
            item = slots_icon.GetEntity();
        if (item)
        {
            c = ClosableContainer.Cast( m_ShowedItems.Get( item ) );
        }
        else
        {
            c = ClosableContainer.Cast(slots_icon.GetContainer());
        }
        if (c)
        {
            c.Toggle();
        }
        RecomputeOpenedContainers();
    }
References SlotsIcon::GetContainer(), SlotsIcon::GetEntity(), and m_ShowedItems.
Referenced by ExpandCollapseContainer().
TransferItem()
override bool ZombieContainer::TransferItem () inline private
Definition at line 575 of file zombiecontainer.c.
    {
        LeftArea left_area = LeftArea.Cast( GetParent() );
        EntityAI item;
        if( left_area )
        {
            if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
            {
                return GetFocusedContainer().TransferItem();
            }
            else
            {
                item = GetFocusedItem();
                if( item )
                {
                    GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, item );
                    return true;
                }
            }
        }
        else
        {
            if( !GetFocusedContainer().IsInherited( ContainerWithCargo ) && !GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
            {
                item = GetFocusedItem();
                if( item )
                {
                    GetGame().GetPlayer().PredictiveTakeEntityToInventory( FindInventoryLocationType.CARGO, item );
                    return true;
                }
            }
        }
        return false;
    }
References Container::GetFocusedItem(), GetGame(), GetParent(), and CGame::GetPlayer().
TransferItemToVicinity()
override bool ZombieContainer::TransferItemToVicinity () inline private
Definition at line 677 of file zombiecontainer.c.
    {
        if( GetFocusedContainer().IsInherited( ContainerWithCargo ) || GetFocusedContainer().IsInherited( ContainerWithCargoAndAttachments ) )
        {
            return GetFocusedContainer().TransferItemToVicinity();
        }
        else
        {
            Man player = GetGame().GetPlayer();
            ItemBase item = ItemBase.Cast( GetFocusedItem() );
            if( item && player.CanDropEntity( item ) )
            {
                if( item.GetTargetQuantityMax() < item.GetQuantity() )
                    item.SplitIntoStackMaxClient( null, -1 );
                else
                    player.PhysicalPredictiveDropItem( item );
                return true;
            }
        }
        return false;
    }
References Container::GetFocusedItem(), GetGame(), and CGame::GetPlayer().
UpdateRadialIcon()
override void ZombieContainer::UpdateRadialIcon () inline private
Definition at line 46 of file zombiecontainer.c.
    {
        if ( m_SlotIcon )
        {
            bool show_radial_icon;
            show_radial_icon = IsHidden();
            Widget rip = m_SlotIcon.GetRadialIconPanel();
            Widget icon_open = m_SlotIcon.GetRadialIcon();
            Widget icon_closed = m_SlotIcon.GetRadialIconClosed();
            rip.Show( !m_ZombieEntity.GetInventory().IsInventoryLockedForLockType( HIDE_INV_FROM_SCRIPT ) && m_ZombieEntity.CanDisplayCargo());
            icon_open.Show( show_radial_icon );
            icon_closed.Show( !show_radial_icon );
        }
    }
References CollapsibleContainer::IsHidden(), and m_ZombieEntity.
Member Data Documentation
m_CargoGrid
protected ref ContainerWithCargo ZombieContainer::m_CargoGrid private
Definition at line 4 of file zombiecontainer.c.
Referenced by InitGhostSlots().
m_Container
protected ref AttachmentsGroupContainer ZombieContainer::m_Container private
Definition at line 3 of file zombiecontainer.c.
Referenced by AddSlotsContainer(), GetSlotsIcon(), GetWidgetSlot(), InitGhostSlots(), IsZombieEquipmentActive(), and ZombieContainer().
m_InventorySlots
protected ref map<int, SlotsIcon> ZombieContainer::m_InventorySlots private
Definition at line 5 of file zombiecontainer.c.
Referenced by InitGhostSlots(), ItemAttached(), ItemDetached(), and ZombieContainer().
m_ShowedItems
protected ref map<EntityAI, ref Container> ZombieContainer::m_ShowedItems = new ref map<EntityAI, ref Container> private
Definition at line 6 of file zombiecontainer.c.
Referenced by InitGhostSlots(), ItemAttached(), ItemDetached(), and ToggleContainer().
m_ZombieEntity
protected EntityAI ZombieContainer::m_ZombieEntity private
Definition at line 7 of file zombiecontainer.c.
Referenced by AddSlotsContainer(), InitGhostSlots(), OnDropReceivedFromGhostArea(), OnDropReceivedFromHeader(), Select(), SetEntity(), UpdateRadialIcon(), and ~ZombieContainer().