DayzKode: ActionRepairTent Class Reference
ActionRepairTent Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRepairTent ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasTarget ()
override bool IsUsingProxies ()
override void OnFinishProgressServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
void RepairDamageTransfer (PlayerBase player, ItemBase repair_kit, ItemBase item, float specialty_weight, string damage_zone="")
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Private Attributes
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
m_LastValidType
Detailed Description
Definition at line 19 of file actionrepairtent.c.
Constructor & Destructor Documentation
ActionRepairTent()
void ActionRepairTent::ActionRepairTent () inline private
Definition at line 25 of file actionrepairtent.c.
    {
        m_CallbackClass = ActionRepairTentCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#repair";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepairTent::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 52 of file actionrepairtent.c.
    {
        Object targetObject = target.GetObject();
        Object targetParent = target.GetParent();
        if ( !targetParent || !targetParent.IsInherited(TentBase) )
            return false;
        if ( player && targetObject && targetParent )
        {
            array<string> selections = new array<string>;
            PluginRepairing module_repairing;
            Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
            targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections, "view");
            TentBase tent = TentBase.Cast( targetParent );
            string damageZone = "";
            for (int s = 0; s < selections.Count(); s++)
            {
                if ( DamageSystem.GetDamageZoneFromComponentName(tent, selections[s], damageZone) ) //NOTE: relevant fire geometry and view geometry selection names MUST match in order to get a valid damage zone
                {
                    //Print("selections[s]: " + selections[s] + " | damageZone: " + damageZone);
                    break;
                }
            }
            if ( damageZone != "" )
            {
                if (module_repairing.CanRepair(item,tent,damageZone))
                {
                    m_CurrentDamageZone = damageZone;
                    return true;
                }
            }
        }
        return false;
    }
References Class::CastTo(), GetPlugin(), and m_CurrentDamageZone.
CreateActionData()
override ActionData ActionRepairTent::CreateActionData () inline private
Definition at line 110 of file actionrepairtent.c.
    {
        RepairTentActionData action_data = new RepairTentActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionRepairTent::CreateConditionComponents () inline private
Definition at line 36 of file actionrepairtent.c.
    {
        m_ConditionItem = new CCINonRuined; //?
        m_ConditionTarget = new CCTCursorParent(UAMaxDistances.SMALL);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::SMALL.
HandleReciveData()
override void ActionRepairTent::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 148 of file actionrepairtent.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        RepairTentActionReciveData recive_data_repair = RepairTentActionReciveData.Cast(action_recive_data);
        RepairTentActionData.Cast(action_data).m_DamageZone = recive_data_repair.m_DamageZoneRecived;
    }
References RepairTentActionReciveData::m_DamageZoneRecived.
HasTarget()
override bool ActionRepairTent::HasTarget () inline private
Definition at line 47 of file actionrepairtent.c.
    {
        return true;
    }
Referenced by ReadFromContext(), and WriteToContext().
IsUsingProxies()
override bool ActionRepairTent::IsUsingProxies () inline private
Definition at line 42 of file actionrepairtent.c.
    {
        return true;
    }
OnFinishProgressServer()
override void ActionRepairTent::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 90 of file actionrepairtent.c.
    {
        Object targetObject = action_data.m_Target.GetObject();
        Object targetParent = action_data.m_Target.GetParent();
        string damageZone = RepairTentActionData.Cast(action_data).m_DamageZone;
        if (!GetGame().IsMultiplayer())
            damageZone = m_CurrentDamageZone;
        if ( targetParent && targetParent.IsInherited(TentBase) && damageZone != "" )
        {
            TentBase tent = TentBase.Cast( targetParent );
            PluginRepairing module_repairing;
            Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
            RepairDamageTransfer(action_data.m_Player,action_data.m_MainItem,tent,m_SpecialtyWeight,damageZone);
            module_repairing.Repair(action_data.m_Player,action_data.m_MainItem,tent,m_SpecialtyWeight,damageZone);
        }
    }
References Class::CastTo(), GetGame(), GetPlugin(), m_CurrentDamageZone, ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and RepairDamageTransfer().
ReadFromContext()
override bool ActionRepairTent::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 128 of file actionrepairtent.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new RepairTentActionReciveData;
        }
        super.ReadFromContext(ctx, action_recive_data);
        RepairTentActionReciveData recive_data_repair = RepairTentActionReciveData.Cast(action_recive_data);
        if( HasTarget() )
        {
            string zone;
            if ( !ctx.Read(zone) )
                return false;
            recive_data_repair.m_DamageZoneRecived = zone;
        }
        return true;
    }
References HasTarget(), RepairTentActionReciveData::m_DamageZoneRecived, and Serializer::Read().
RepairDamageTransfer()
void ActionRepairTent::RepairDamageTransfer (PlayerBase player, ItemBase repair_kit, ItemBase item, float specialty_weight, string damage_zone = "") inline private
Definition at line 156 of file actionrepairtent.c.
    {
        float transfer_to_global_coef = 0;
        array<string> transfer_zones = new array<string>;
        string path = "" + CFG_VEHICLESPATH + " " + item.GetType() + " DamageSystem DamageZones " + damage_zone;
        PluginRepairing module_repairing;
        Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
        GetGame().ConfigGetTextArray("" + path + " transferToZonesNames", transfer_zones);
        for (int i = 0; i < transfer_zones.Count(); i++)
        {
            transfer_to_global_coef += GetGame().ConfigGetFloat("" + path + " Health transferToGlobalCoef");
            if (transfer_zones.Get(i) == damage_zone)
                continue;
            module_repairing.Repair(player,repair_kit,item,specialty_weight,transfer_zones.Get(i),false);
        }
        //finally, repairs global
        if (transfer_to_global_coef > 0)
        {
            module_repairing.Repair(player,repair_kit,item,specialty_weight,"",false);
        }
    }
References Class::CastTo(), CFG_VEHICLESPATH, CGame::ConfigGetFloat(), CGame::ConfigGetTextArray(), GetGame(), GetPlugin(), and path.
Referenced by OnFinishProgressServer().
WriteToContext()
override void ActionRepairTent::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 116 of file actionrepairtent.c.
    {
        super.WriteToContext(ctx, action_data);
        RepairTentActionData repair_action_data;
        if( HasTarget() && Class.CastTo(repair_action_data,action_data) )
        {
            repair_action_data.m_DamageZone = m_CurrentDamageZone;
            ctx.Write(repair_action_data.m_DamageZone);
        }
    }
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Member Data Documentation
m_CurrentDamageZone
string ActionRepairTent::m_CurrentDamageZone = "" private
Definition at line 22 of file actionrepairtent.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int ActionRepairTent::m_LastValidComponentIndex = -1 private
Definition at line 23 of file actionrepairtent.c.
m_LastValidType
ActionRepairTent::m_LastValidType private
Definition at line 21 of file actionrepairtent.c.