DayzKode: ShockMdfr Class Reference
ShockMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
float GetRefillSpeed (PlayerBase player)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
private const float SHOCK_INCREMENT_PER_SEC = 1
private const float UNCONSCIOUS_LIMIT = 50
Detailed Description
Definition at line 1 of file shock.c.
Member Function Documentation
ActivateCondition()
override bool ShockMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 15 of file shock.c.
    {
        return true;
    }
DeactivateCondition()
override bool ShockMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 20 of file shock.c.
    {
        return false;
    }
GetRefillSpeed()
float ShockMdfr::GetRefillSpeed (PlayerBase player) inline private
Definition at line 33 of file shock.c.
    {
        if ( player.m_IsDrowning )
        {
            return 0;
        }
        if ( player.IsUnconscious() )
        {
            return CfgGameplayHandler.GetShockRefillSpeedUnconscious() * player.m_UnconRefillModifier;
        }
        if (player.GetBrokenLegs() != eBrokenLegs.BROKEN_LEGS || (player.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || player.m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE))
        {
            return CfgGameplayHandler.GetShockRefillSpeedConscious();
        }
        if ( player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS && (player.IsSwimming() || player.IsClimbingLadder()) )
        {
            return CfgGameplayHandler.GetShockRefillSpeedUnconscious();
        }
        return 0; //Block shock regen when standing with broken legs
    }
References CfgGameplayHandler::GetShockRefillSpeedConscious(), and CfgGameplayHandler::GetShockRefillSpeedUnconscious().
Referenced by OnTick().
Init()
override void ShockMdfr::Init () inline private
Definition at line 6 of file shock.c.
    {
        m_ID                    = eModifiers.MDF_SHOCK;
        m_TickIntervalInactive  = 1;
        m_TickIntervalActive    = 0.35;
        //DisableActivateCheck();
        DisableDeactivateCheck();
    }
References DisableDeactivateCheck(), m_ID, m_TickIntervalActive, and m_TickIntervalInactive.
OnActivate()
override void ShockMdfr::OnActivate (PlayerBase player) inline private
Definition at line 25 of file shock.c.
    {
    }
OnDeactivate()
override void ShockMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 29 of file shock.c.
    {
    }
OnReconnect()
override void ShockMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 72 of file shock.c.
    {
    }
OnTick()
override void ShockMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 54 of file shock.c.
    {
        //Print("m_UnconRefillModifier" + player.m_UnconRefillModifier);
        if ( GetGame().GetTime() > player.m_LastShockHitTime + PlayerConstants.SHOCK_REFILL_COOLDOWN_AFTER_HIT && player.GetPulseType() == EPulseType.REGULAR)
        {
            if (!player.IsUnconscious())
                player.m_UnconRefillModifier = 1;//reset this UnconRefillModifier some time after the player has been hit(we want the UnconRefillModifier to only apply to uncon induced by a projectile)
            if (player.GetHealth01("","Shock") == 1)//no need to continue if the shock is full
                return;
            if ( !CfgGameplayHandler.GetAllowRefillSpeedModifier() )
                player.m_UnconRefillModifier = 1;
            player.AddHealth("","Shock", deltaT * GetRefillSpeed(player) );
        }
    }
References CfgGameplayHandler::GetAllowRefillSpeedModifier(), GetGame(), GetRefillSpeed(), GetTime(), and PlayerConstants::SHOCK_REFILL_COOLDOWN_AFTER_HIT.
Member Data Documentation
SHOCK_INCREMENT_PER_SEC
private const float ShockMdfr::SHOCK_INCREMENT_PER_SEC = 1 private
Definition at line 4 of file shock.c.
UNCONSCIOUS_LIMIT
private const float ShockMdfr::UNCONSCIOUS_LIMIT = 50 private
Definition at line 3 of file shock.c.