DayzKode: StaticConstructionMethods Class Reference
StaticConstructionMethods Class Reference
Static Private Member Functions
static void SpawnConstructionMaterialPiles (notnull EntityAI entity, Man player, string cfg_path, string main_part_name, string damagezone_name="", bool is_base=false)
spawns material from any construction; 'player' parameter optional
Detailed Description
Definition at line 1220 of file construction.c.
Member Function Documentation
SpawnConstructionMaterialPiles()
static void StaticConstructionMethods::SpawnConstructionMaterialPiles (notnull EntityAI entity, Man player, string cfg_path, string main_part_name, string damagezone_name = "", bool is_base = false) inline static private
spawns material from any construction; 'player' parameter optional
Definition at line 1223 of file construction.c.
    {
        int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
        for ( int i = 0; i < child_count; i++ )
        {
            string child_name;
            GetGame().ConfigGetChildName( cfg_path, i, child_name );
            //get type, quantity from material
            string config_path;
            string type;
            string slot_name;
            config_path = cfg_path + " " + child_name + " " + "type";
            GetGame().ConfigGetText( config_path, type );
            config_path = cfg_path + " " + child_name + " " + "slot_name";
            GetGame().ConfigGetText( config_path, slot_name );
            config_path = cfg_path + " " + child_name + " " + "quantity";
            float quantity = GetGame().ConfigGetFloat( config_path );
            config_path = cfg_path + " " + child_name + " " + "lockable";
            bool lockable = GetGame().ConfigGetInt( config_path );
            //receive material quantity
            ItemBase attachment = ItemBase.Cast( entity.FindAttachmentBySlotName( slot_name ) );
            int slot_id;
            //material still attached
            if ( lockable )         //if lockable
            {
                if ( attachment )
                {
                    InventoryLocation src = new InventoryLocation;
                    attachment.GetInventory().GetCurrentInventoryLocation( src );
                    bsbDebugPrint("[bsb] " + Object.GetDebugName( entity) + " DropNonUsableMaterials UNlocking slot=" + src.GetSlot() );
                    entity.GetInventory().SetSlotLock( src.GetSlot() , false );
                    //detach if base
                    if ( is_base )
                    {
                        if ( GetGame().IsMultiplayer() && player )
{
                            InventoryLocation dst = new InventoryLocation;
                            GameInventory.SetGroundPosByOwner( player, src.GetItem(), dst );
                            player.ServerTakeToDst( src, dst );
                        }
                        else
{
                            entity.GetInventory().DropEntity( InventoryMode.PREDICTIVE, entity, attachment );
                        }
                    }
                }
            }
            else
            {
                float pile_health;
                float qty_coef;
                vector destination = entity.GetPosition();
                //placed on helper memory point, if available
                if ( entity.MemoryPointExists("" + main_part_name + "_materials") )
                {
                    destination = entity.GetMemoryPointPos("" + main_part_name + "_materials");
                    destination = GetGame().ObjectModelToWorld(entity,destination);
                }
                else if ( entity.MemoryPointExists(main_part_name) )
                {
                    destination = entity.GetMemoryPointPos(main_part_name);
                    destination = GetGame().ObjectModelToWorld(entity,destination);
                }
                //pile_health = GameConstants.DAMAGE_WORN_VALUE * MiscGameplayFunctions.GetTypeMaxGlobalHealth(type);
                pile_health = entity.GetHealth01(damagezone_name,"Health") * MiscGameplayFunctions.GetTypeMaxGlobalHealth(type);
                qty_coef =  1 - (entity.GetHealthLevel(damagezone_name) * Construction.DECONSTURCT_MATERIAL_LOSS) - Construction.DECONSTURCT_MATERIAL_LOSS;
                quantity *= qty_coef;
                quantity = Math.Max(Math.Floor(quantity),1);
                MiscGameplayFunctions.CreateItemBasePiles(type,destination,quantity,pile_health,true);
            }
        }
    }
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), Construction(), Math::Floor(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetSlot(), Math::Max(), and CGame::ObjectModelToWorld().
Referenced by TentBase::Deconstruct(), and ReceiveMaterialsServer().