DayzKode: ActionSawPlanksCB Class Reference
ActionSawPlanksCB Class Reference
Private Member Functions
override void CreateActionComponent ()
float GetDefaultTime ()
Static Private Attributes
static const float TIME_AXES = 1.2
static const float TIME_SAW_HACKSAW = 3.0
static const float TIME_SAW_HANDSAW = 1.5
Detailed Description
Definition at line 1 of file actionsawplanks.c.
Member Function Documentation
CreateActionComponent()
override void ActionSawPlanksCB::CreateActionComponent () inline private
Definition at line 7 of file actionsawplanks.c.
    {
        m_ActionData.m_ActionComponent = new CAContinuousRepeat(GetDefaultTime());
    }
References GetDefaultTime(), ActionData::m_ActionComponent, and ActionBaseCB::m_ActionData.
GetDefaultTime()
float ActionSawPlanksCB::GetDefaultTime () inline private
Definition at line 12 of file actionsawplanks.c.
    {
        string item_type = m_ActionData.m_MainItem.GetType();
        switch(item_type)
        {
            case "Hacksaw":
                return TIME_SAW_HACKSAW;
            break;
            case "HandSaw":
                return TIME_SAW_HANDSAW;
            break;
            default: // axes
                return TIME_AXES;
            break
        }
        Print("ActionSawPlanksCB | Item detection error, assigning negative time");
        return -1;
    }
References ActionBaseCB::m_ActionData, ActionData::m_MainItem, Print(), TIME_AXES, TIME_SAW_HACKSAW, and TIME_SAW_HANDSAW.
Referenced by CreateActionComponent().
Member Data Documentation
TIME_AXES
const float ActionSawPlanksCB::TIME_AXES = 1.2 static private
Definition at line 5 of file actionsawplanks.c.
Referenced by GetDefaultTime().
TIME_SAW_HACKSAW
const float ActionSawPlanksCB::TIME_SAW_HACKSAW = 3.0 static private
Definition at line 4 of file actionsawplanks.c.
Referenced by GetDefaultTime().
TIME_SAW_HANDSAW
const float ActionSawPlanksCB::TIME_SAW_HANDSAW = 1.5 static private
Definition at line 3 of file actionsawplanks.c.
Referenced by GetDefaultTime().