DayzKode: HumanCommandMelee2 Class Reference
HumanCommandMelee2 Class Reference
Private Member Functions
proto native void Cancel ()
cancels command melee and goes to HumanCommandMove
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target=null, vector hitPos=vector.Zero)
marks command to continue to combo
proto native int GetComboCount ()
proto native int GetCurrentHitType ()
private void HumanCommandMelee2 ()
proto native bool IsFinisher ()
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
proto native bool IsOnBack ()
is on back in prone stance?
proto native bool WasHit ()
is true only once after hit event
private void ~HumanCommandMelee2 ()
Static Private Attributes
static const int HIT_TYPE_FINISHER = 2
static const int HIT_TYPE_FINISHER_NECK = 3
static const int HIT_TYPE_HEAVY = 1
static const int HIT_TYPE_LIGHT = 0
Detailed Description
Definition at line 521 of file human.c.
Constructor & Destructor Documentation
HumanCommandMelee2()
private void HumanCommandMelee2::HumanCommandMelee2 () inline private
Definition at line 523 of file human.c.
{}
~HumanCommandMelee2()
private void HumanCommandMelee2::~HumanCommandMelee2 () inline private
Definition at line 524 of file human.c.
{}
Member Function Documentation
Cancel()
proto native void HumanCommandMelee2::Cancel () private
cancels command melee and goes to HumanCommandMove
Referenced by EEHitBy().
ContinueCombo()
proto native void HumanCommandMelee2::ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target = null, vector hitPos = vector.Zero) private
marks command to continue to combo
GetComboCount()
proto native int HumanCommandMelee2::GetComboCount () private
GetCurrentHitType()
proto native int HumanCommandMelee2::GetCurrentHitType () private
IsFinisher()
proto native bool HumanCommandMelee2::IsFinisher () private
Referenced by AimingModel().
IsInComboRange()
proto native bool HumanCommandMelee2::IsInComboRange () private
returns true if hit is in range, where person can continue to combo
IsOnBack()
proto native bool HumanCommandMelee2::IsOnBack () private
is on back in prone stance?
WasHit()
proto native bool HumanCommandMelee2::WasHit () private
is true only once after hit event
Referenced by HandleHitEvent().
Member Data Documentation
HIT_TYPE_FINISHER
const int HumanCommandMelee2::HIT_TYPE_FINISHER = 2 static private
Definition at line 528 of file human.c.
Referenced by DetermineFinisherAnimation().
HIT_TYPE_FINISHER_NECK
const int HumanCommandMelee2::HIT_TYPE_FINISHER_NECK = 3 static private
Definition at line 529 of file human.c.
Referenced by DetermineFinisherAnimation().
HIT_TYPE_HEAVY
const int HumanCommandMelee2::HIT_TYPE_HEAVY = 1 static private
Definition at line 527 of file human.c.
HIT_TYPE_LIGHT
const int HumanCommandMelee2::HIT_TYPE_LIGHT = 0 static private
Definition at line 526 of file human.c.