DayzKode: MissionBaseWorld Class Reference
MissionBaseWorld Class Reference
Private Member Functions
override void AddDummyPlayerToScheduler (Man player)
override UIScriptedMenu CreateScriptedMenu (int id)
override UIScriptedWindow CreateScriptedWindow (int id)
void DumpCurrentUILayout ()
void DumpWidget (Widget w, int tabs)
override WorldData GetWorldData ()
override WorldLighting GetWorldLighting ()
void InitialiseWorldData ()
void MissionBase ()
override void OnEvent (EventType eventTypeId, Param params)
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
void OnLog (string msg_log)
override void OnMouseButtonPress (int button)
override void OnMouseButtonRelease (int button)
void SpawnItems ()
void UpdateDummyScheduler ()
void ~MissionBase ()
Private Attributes
ref array< PlayerBase > m_DummyPlayers = new array<PlayerBase>
PluginDeveloper m_ModuleDeveloper
PluginKeyBinding m_ModuleKeyBinding PluginAdditionalInfo m_ModuleServerInfo
ref WidgetEventHandler m_WidgetEventHandler
int m_WidgetsInvisible
int m_WidgetsTotal
ref WorldData m_WorldData
ref WorldLighting m_WorldLighting
Detailed Description
Definition at line 1 of file missionbase.c.
Constructor & Destructor Documentation
~MissionBase()
void MissionBaseWorld::~MissionBase () inline private
Definition at line 42 of file missionbase.c.
    {
        PluginManagerDelete();
        if ( GetGame().IsClient() )
        {
            GetDayZGame().GetAnalyticsClient().UnregisterEvents();
        }
        TriggerEffectManager.DestroyInstance();
    }
References TriggerEffectManager::DestroyInstance(), GetDayZGame(), GetGame(), and PluginManagerDelete().
Member Function Documentation
AddDummyPlayerToScheduler()
override void MissionBaseWorld::AddDummyPlayerToScheduler (Man player) inline private
Definition at line 436 of file missionbase.c.
    {
        m_DummyPlayers.Insert(PlayerBase.Cast( player ));
    }
References m_DummyPlayers.
CreateScriptedMenu()
override UIScriptedMenu MissionBaseWorld::CreateScriptedMenu (int id) inline private
Definition at line 85 of file missionbase.c.
    {
        UIScriptedMenu menu = NULL;
        switch (id)
        {
        case MENU_MAIN:
#ifdef PLATFORM_CONSOLE
            menu = new MainMenuConsole;
#else
            menu = new MainMenu;
#endif
            break;
        case MENU_INGAME:
#ifdef PLATFORM_CONSOLE
            menu = new InGameMenuXbox;
#else
            menu = new InGameMenu;
#endif
            break;
        case MENU_CHARACTER:
            menu = new CharacterCreationMenu;
            break;
        case MENU_OPTIONS:
            menu = new OptionsMenu;
            break;
//      case MENU_***: removed - can be recycled to something else
//          menu = new ***;
//          break;
        case MENU_STARTUP:
            menu = new StartupMenu;
            break;
        case MENU_LOADING:
            menu = new LoadingMenu;
            break;
        case MENU_INVENTORY:
            menu = new InventoryMenu;
            break;
        case MENU_INSPECT:
            menu = new InspectMenuNew;
            break;
        case MENU_EARLYACCESS:
            menu = new EarlyAccessMenu;
            break;
        case MENU_SCRIPTCONSOLE:
            menu = new ScriptConsole;
            break;
        case MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME:
            menu = new ScriptConsoleNewPresetDialog;
            break;
        case MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME:
            menu = new ScriptConsoleRenamePresetDialog;
            break;
        case MENU_CHAT_INPUT:
            menu = new ChatInputMenu;
            break;
        case MENU_CONTROLS_PRESET:
            menu = new PresetsMenu;
            break;
        case MENU_NOTE:
            menu = new NoteMenu;
            break;
        case MENU_MAP:
            menu = new MapMenu;
            break;
        case MENU_BOOK:
            menu = new BookMenu;
            break;
        case MENU_SCENE_EDITOR:
            menu = new SceneEditorMenu;
            break;
        case MENU_HELP_SCREEN:
            menu = new HelpScreen;
            break;
        case MENU_GESTURES:
            menu = new GesturesMenu;
            break;
        case MENU_LOGOUT:
            menu = new LogoutMenu;
            break;
        case MENU_TITLE_SCREEN:
            menu = new TitleScreenMenu;
            break;
        case MENU_XBOX_CONTROLS:
            menu = new ControlsXboxNew;
            break;
        case MENU_RADIAL_QUICKBAR:
            menu = new RadialQuickbarMenu;
            break;
        case MENU_SERVER_BROWSER:
            menu = new ServerBrowserMenuNew;
            break;
        case MENU_LOGIN_QUEUE:
            menu = new LoginQueueBase;
            break;
        case MENU_LOGIN_TIME:
            menu = new LoginTimeBase;
            break;
        case MENU_CAMERA_TOOLS:
            menu = new CameraToolsMenu;
            break;
        case MENU_VIDEO:
            menu = new MainMenuVideo;
            break;
        case MENU_KEYBINDINGS:
            menu = new KeybindingsMenu;
            break;
        case MENU_TUTORIAL:
            menu = new TutorialsMenu;
            break;
        case MENU_CREDITS:
            menu = new CreditsMenu;
            break;
        case MENU_INVITE_TIMER:
            menu = new InviteMenu;
            break;
        case MENU_WARNING_ITEMDROP:
            menu = new ItemDropWarningMenu;
            break;
        case MENU_WARNING_TELEPORT:
            menu = new PlayerRepositionWarningMenu;
            break;
        case MENU_RESPAWN_DIALOGUE:
            menu = new RespawnDialogue;
            break;
        case MENU_CONNECT_ERROR:
            menu = new ConnectErrorScriptModuleUI;
            break;
        }
        if (menu)
        {
            menu.SetID(id);
        }
        return menu;
    }
References InventoryMenu(), MENU_BOOK, MENU_CAMERA_TOOLS, MENU_CHARACTER, MENU_CHAT_INPUT, MENU_CONNECT_ERROR, MENU_CONTROLS_PRESET, MENU_CREDITS, MENU_EARLYACCESS, MENU_GESTURES, MENU_HELP_SCREEN, MENU_INGAME, MENU_INSPECT, MENU_INVENTORY, MENU_INVITE_TIMER, MENU_KEYBINDINGS, MENU_LOADING, MENU_LOGIN_QUEUE, MENU_LOGIN_TIME, MENU_LOGOUT, MENU_MAIN, MENU_MAP, MENU_NOTE, MENU_OPTIONS, MENU_RADIAL_QUICKBAR, MENU_RESPAWN_DIALOGUE, MENU_SCENE_EDITOR, MENU_SCRIPTCONSOLE, MENU_SCRIPTCONSOLE_DIALOG_PRESET_NAME, MENU_SCRIPTCONSOLE_DIALOG_PRESET_RENAME, MENU_SERVER_BROWSER, MENU_STARTUP, MENU_TITLE_SCREEN, MENU_TUTORIAL, MENU_VIDEO, MENU_WARNING_ITEMDROP, MENU_WARNING_TELEPORT, and MENU_XBOX_CONTROLS.
CreateScriptedWindow()
override UIScriptedWindow MissionBaseWorld::CreateScriptedWindow (int id) inline private
Definition at line 223 of file missionbase.c.
    {
        UIScriptedWindow window = NULL;
        switch (id)
        {
        case GUI_WINDOW_MISSION_LOADER:
            window = new MissionLoader( GUI_WINDOW_MISSION_LOADER );
            break;
        }
        return window;
    }
References GUI_WINDOW_MISSION_LOADER.
DumpCurrentUILayout()
void MissionBaseWorld::DumpCurrentUILayout () inline private
Definition at line 288 of file missionbase.c.
    {
        UIScriptedMenu current_menu = GetGame().GetUIManager().GetMenu();
        if ( current_menu )
        {
            Widget widget_root = current_menu.GetLayoutRoot();
            if ( widget_root )
            {
                m_WidgetsTotal = 0;
                m_WidgetsInvisible = 0;
                Print( widget_root.GetName() +" ("+ widget_root.GetTypeName() +")");
                DumpWidget(widget_root.GetChildren(), 1);
                Print( "Widgets TOTAL: "+ m_WidgetsTotal.ToString() +" INVISIBLE: "+ m_WidgetsInvisible.ToString() +" VISIBLE: "+ (m_WidgetsTotal - m_WidgetsInvisible).ToString() );
            }
        }
    }
References DumpWidget(), GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), m_WidgetsInvisible, m_WidgetsTotal, and Print().
DumpWidget()
void MissionBaseWorld::DumpWidget (Widget w, int tabs) inline private
Definition at line 310 of file missionbase.c.
    {
        if ( !w )
        {
            return;
        }
        m_WidgetsTotal++;
        string tmp;
        for (int i = 0; i < tabs; i++)
        {
            tmp += "  ";
        }
        string invisible = "";
        if ( !w.IsVisibleHierarchy() )
        {
            invisible = "[invisible]";
            m_WidgetsInvisible++;
        }
        Print( tmp +"- "+ w.GetName() +" ("+ w.GetTypeName() +") "+ invisible );
        bool collapse = false;
        if ( w.GetChildren() )
        {
            collapse = true;
            Print(tmp +"{");
        }
        DumpWidget(w.GetChildren(), tabs + 1);
        if ( collapse )
        {
            Print(tmp +"}");
        }
        DumpWidget(w.GetSibling(), tabs);
    }
References DumpWidget(), m_WidgetsInvisible, m_WidgetsTotal, and Print().
GetWorldData()
override WorldData MissionBaseWorld::GetWorldData () inline private
Definition at line 80 of file missionbase.c.
    {
        return m_WorldData;
    }
References m_WorldData.
GetWorldLighting()
override WorldLighting MissionBaseWorld::GetWorldLighting () inline private
Definition at line 75 of file missionbase.c.
    {
        return m_WorldLighting;
    }
References m_WorldLighting.
InitialiseWorldData()
void MissionBaseWorld::InitialiseWorldData () inline private
Definition at line 53 of file missionbase.c.
    {
        string worldName = "empty";
        GetGame().GetWorldName(worldName);
        worldName.ToLower();
        switch ( worldName )
        {
            case "chernarusplus":
                m_WorldData = new ChernarusPlusData;
                break;
            case "enoch":
                m_WorldData = new EnochData;
                break;
            default:
                m_WorldData = new ChernarusPlusData;
                break;
        }
    }
References GetGame(), CGame::GetWorldName(), m_WorldData, and string::ToLower().
MissionBase()
void MissionBaseWorld::MissionBase () inline private
Definition at line 13 of file missionbase.c.
    {
        SetDispatcher(new DispatcherCaller);
        PluginManagerInit();
        m_WidgetEventHandler = new WidgetEventHandler;
        //Debug.DestroyAllShapes();
        //TODO clea up after Gamescom
        m_ModuleServerInfo = PluginAdditionalInfo.Cast( GetPlugin(PluginAdditionalInfo) );
        //
        SoundSetMap.Init();
        if (GetGame().IsServer())
        {
            InitialiseWorldData();
        }
        else
        {
            GetDayZGame().GetAnalyticsClient().RegisterEvents();
            m_WorldLighting = new WorldLighting;
        }
        // There is a possibility different maps/servers may be using different effects
        SEffectManager.Cleanup();
    }
References SEffectManager::Cleanup(), GetDayZGame(), GetGame(), GetPlugin(), SoundSetMap::Init(), InitialiseWorldData(), MissionBase::IsServer(), m_ModuleServerInfo, m_WidgetEventHandler, m_WorldLighting, PluginManagerInit(), and SetDispatcher().
OnEvent()
override void MissionBaseWorld::OnEvent (EventType eventTypeId, Param params) inline private
Definition at line 391 of file missionbase.c.
    {
        super.OnEvent(eventTypeId, params);
        /*
        switch(eventTypeId)
        {
        case ScriptLogEventTypeID:
            if ( GetGame().IsDebug() )
            {
                Param1<string> log_params = params;
                OnLog(log_params.param1);
            }
            break;
        }
        */
    }
OnKeyPress()
override void MissionBaseWorld::OnKeyPress (int key) inline private
Definition at line 273 of file missionbase.c.
    {
        super.OnKeyPress(key);
#ifdef DIAG_DEVELOPER
        if ( PluginKeyBinding.instance )
        {
            PluginKeyBinding.instance.OnKeyPress(key);
        }
#endif
    }
OnKeyRelease()
override void MissionBaseWorld::OnKeyRelease (int key) inline private
Definition at line 352 of file missionbase.c.
    {
        super.OnKeyRelease(key);
        if ( GetGame().IsDebug() )
        {
            if ( PluginKeyBinding.instance != NULL )
            {
                PluginKeyBinding.instance.OnKeyRelease(key);
            }
        }
    }
References GetGame().
OnLog()
void MissionBaseWorld::OnLog (string msg_log) inline private
Definition at line 410 of file missionbase.c.
    {
        if ( PluginDeveloper.GetInstance() )
        {
            if ( GetGame().IsServer() && !GetGame().IsMultiplayer() )
            {
                PluginDeveloper.GetInstance().PrintLogClient(msg_log);
            }
            else if ( GetGame().IsMultiplayer() && GetGame().IsClient() )
            {
                PluginDeveloper.GetInstance().PrintLogClient(msg_log);
            }
        }
    }
References GetGame(), and MissionBase::IsServer().
OnMouseButtonPress()
override void MissionBaseWorld::OnMouseButtonPress (int button) inline private
Definition at line 365 of file missionbase.c.
    {
        super.OnMouseButtonPress(button);
        if ( GetGame().IsDebug() )
        {
            if ( PluginKeyBinding.instance != NULL )
            {
                PluginKeyBinding.instance.OnMouseButtonPress(button);
            }
        }
    }
References GetGame().
OnMouseButtonRelease()
override void MissionBaseWorld::OnMouseButtonRelease (int button) inline private
Definition at line 378 of file missionbase.c.
    {
        super.OnMouseButtonRelease(button);
        if ( GetGame().IsDebug() )
        {
            if ( PluginKeyBinding.instance != NULL )
            {
                PluginKeyBinding.instance.OnMouseButtonRelease(button);
            }
        }
    }
References GetGame().
SpawnItems()
void MissionBaseWorld::SpawnItems () inline private
Definition at line 237 of file missionbase.c.
    {
        /*vector player_pos = "2558 16 2854";
        if (g_Game.GetPlayer())
        {
            g_Game.GetPlayer().GetPosition();
        }
        Print(player_pos);
        Print("Spawning items.");
        ref TStringArray items = new TStringArray;
        items.Insert("Hoodie_Blue");
        items.Insert("WoolCoat_Red");
        items.Insert("Raincoat_Orange");
        items.Insert("PressVest_Blue");
        items.Insert("Gorka_pants_summer");
        items.Insert("MilitaryBoots_Black");
        items.Insert("WoodAxe");
        items.Insert("Container_FirstAidKit");
        items.Insert("Consumable_DuctTape");
        items.Insert("Fruit_AppleFresh");
        items.Insert("ItemBookHunger");
        for (int i = 0; i < items.Count(); i++)
        {
            string item = items.Get(i);
            vector item_pos = player_pos;
            int x = i % 4;
            int z = i / 4;
            item_pos[0] = item_pos[0] + (x * 1);
            item_pos[2] = item_pos[2] + (z * 1);
            g_Game.CreateObject(item, item_pos, false);
        }*/
    }
UpdateDummyScheduler()
void MissionBaseWorld::UpdateDummyScheduler () inline private
Definition at line 425 of file missionbase.c.
    {
        for(int i = 0; i < m_DummyPlayers.Count(); i++)
        {
            if (m_DummyPlayers.Get(i))
            {
                m_DummyPlayers.Get(i).OnTick();
            }
        }
    }
References m_DummyPlayers.
Member Data Documentation
m_DummyPlayers
ref array<PlayerBase> MissionBaseWorld::m_DummyPlayers = new array<PlayerBase> private
Definition at line 11 of file missionbase.c.
m_ModuleDeveloper
PluginDeveloper MissionBaseWorld::m_ModuleDeveloper private
Definition at line 3 of file missionbase.c.
m_ModuleServerInfo
PluginKeyBinding m_ModuleKeyBinding PluginAdditionalInfo MissionBaseWorld::m_ModuleServerInfo private
Definition at line 5 of file missionbase.c.
m_WidgetEventHandler
ref WidgetEventHandler MissionBaseWorld::m_WidgetEventHandler private
Definition at line 7 of file missionbase.c.
m_WidgetsInvisible
int MissionBaseWorld::m_WidgetsInvisible private
Definition at line 286 of file missionbase.c.
m_WidgetsTotal
int MissionBaseWorld::m_WidgetsTotal private
Definition at line 285 of file missionbase.c.
m_WorldData
ref WorldData MissionBaseWorld::m_WorldData private
Definition at line 8 of file missionbase.c.
m_WorldLighting
ref WorldLighting MissionBaseWorld::m_WorldLighting private
Definition at line 9 of file missionbase.c.