DayzKode: HandActionBase Class Reference
HandActionBase Class Reference
actions
Private Member Functions
void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
override void Action (HandEventBase e)
Detailed Description
actions
represents action executed on transition just between OnExit from old state and OnEntry to new state
Definition at line 6 of file hand_actions.c.
Member Function Documentation
Action() [1/12]
void HandActionBase::Action (HandEventBase e) inline private
Definition at line 11 of file hand_actions.c.
{ }
Action() [2/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 17 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionCreated", e.m_Player.ToString() );
        }
        #endif
        e.m_Player.OnItemInHandsChanged();
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [3/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 32 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionTake", e.m_Player.ToString() );
        }
        #endif
        GameInventory.LocationSyncMoveEntity(e.GetSrc(), e.GetDst());
        e.m_Player.OnItemInHandsChanged();
    }
References HandEventBase::GetDst(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [4/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 48 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionDrop", e.m_Player.ToString() );
        }
        #endif
        GameInventory.LocationSyncMoveEntity(e.GetSrc(), e.GetDst());
        e.m_Player.OnItemInHandsChanged();
    }
References HandEventBase::GetDst(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [5/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 64 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionThrow", e.m_Player.ToString() );
        }
        #endif
        HandEventThrow throwEvent = HandEventThrow.Cast(e);
        GameInventory.LocationSyncMoveEntity(e.GetSrc(), e.GetDst());
        DayZPlayer player = DayZPlayer.Cast(e.m_Player);
        if ( player.GetInstanceType() != DayZPlayerInstanceType.INSTANCETYPE_REMOTE )
        {
            InventoryItem item = InventoryItem.Cast(e.GetSrcEntity());
            if( item )
                item.ThrowPhysically(player, throwEvent.GetForce());
            else
                Error("[hndfsm] HandActionThrow - src entity null!");
        }
        player.OnItemInHandsChanged();
    }
References Error(), HandEventBase::GetDst(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [6/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 92 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionMoveTo", e.m_Player.ToString() );
        }
        #endif
        HandEventMoveTo es = HandEventMoveTo.Cast(e);
        if (es)
        {
            GameInventory.LocationSyncMoveEntity(e.GetSrc(), es.m_Dst);
            e.m_Player.OnItemInHandsChanged();
        }
        else
            Error("[hndfsm] HandActionMoveTo - this is no HandEventMoveTo");
    }
References Error(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and HandEventBase::m_Dst.
Action() [7/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 114 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionDestroy", e.m_Player.ToString() );
        }
        #endif
        GetGame().ObjectDelete(e.GetSrcEntity());
        e.m_Player.OnItemInHandsChanged();
    }
References GetGame(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and CGame::ObjectDelete().
Action() [8/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 130 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionDestroyed", e.m_Player.ToString() );
        }
        #endif
        e.m_Player.OnItemInHandsChanged();
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [9/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 144 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionDestroyAndReplaceWithNew", e.m_Player.ToString() );
        }
        #endif
        Man player = e.m_Player;
        EntityAI itemInHands = player.GetHumanInventory().GetEntityInHands();
        InventoryLocation src = new InventoryLocation;
        if (itemInHands.GetInventory().GetCurrentInventoryLocation(src))
        {
            HandEventDestroyAndReplaceWithNew edr = HandEventDestroyAndReplaceWithNew.Cast(e);
            if (edr)
            {
                edr.m_Lambda.Execute();
                return;
            }
            else
                Error("[hndfsm] HandActionDestroyAndReplaceWithNew - not a HandEventDestroyAndReplaceWithNew event");
        }
        else
            Error("[hndfsm] HandActionDestroyAndReplaceWithNew - itemInHands has no InventoryLocation");
    }
References Error(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [10/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 182 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionReplaced", e.m_Player.ToString() );
        }
        #endif
        Man player = e.m_Player;
        player.OnItemInHandsChanged();
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [11/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 198 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionSwap", e.m_Player.ToString() );
        }
        #endif
        HandEventSwap es = HandEventSwap.Cast(e);
        if (es)
        {
            GameInventory.LocationSwap(es.GetSrc(), es.m_Src2, es.GetDst(), es.m_Dst2);
            e.m_Player.OnItemInHandsChanged();
        }
        else
            Error("[hndfsm] HandActionSwap - this is no HandEventSwap");
    }
References Error(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
Action() [12/12]
override void HandActionBase::Action (HandEventBase e) inline private
Definition at line 219 of file hand_actions.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "HandActionForceSwap", e.m_Player.ToString() );
        }
        #endif
        HandEventForceSwap es = HandEventForceSwap.Cast(e);
        if (es)
        {
            GameInventory.LocationSwap(es.GetSrc(), es.m_Src2, es.GetDst(), es.m_Dst2);
            e.m_Player.OnItemInHandsChanged();
        }
        else
            Error("[hndfsm] HandActionForceSwap - this is no HandEventForceSwap");
    }
References Error(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().