DayzKode: ImmunityBoost Class Reference
ImmunityBoost Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
float m_LastWaterLevel
ref HumanMovementState m_MovementState = new HumanMovementState()
float m_RegenTime
Detailed Description
Definition at line 1 of file immunityboost.c.
Member Function Documentation
ActivateCondition()
override bool ImmunityBoost::ActivateCondition (PlayerBase player) inline private
Definition at line 17 of file immunityboost.c.
    {
        return false;
    }
DeactivateCondition()
override bool ImmunityBoost::DeactivateCondition (PlayerBase player) inline private
Definition at line 52 of file immunityboost.c.
    {
        float attached_time = GetAttachedTime();
        if( attached_time >= m_RegenTime )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and m_RegenTime.
GetDebugText()
override string ImmunityBoost::GetDebugText () inline private
Definition at line 27 of file immunityboost.c.
    {
        return (m_RegenTime - GetAttachedTime()).ToString();
    }
References GetAttachedTime(), m_RegenTime, and string::ToString().
Init()
override void ImmunityBoost::Init () inline private
Definition at line 7 of file immunityboost.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_IMMUNITYBOOST;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 1;
        m_RegenTime = PlayerConstants.VITAMINS_LIFETIME_SECS;
    }
References DEFAULT_TICK_TIME_INACTIVE, m_ID, m_IsPersistent, m_RegenTime, m_TickIntervalActive, m_TickIntervalInactive, m_TrackActivatedTime, and PlayerConstants::VITAMINS_LIFETIME_SECS.
OnActivate()
override void ImmunityBoost::OnActivate (PlayerBase player) inline private
Definition at line 32 of file immunityboost.c.
    {
        player.SetImmunityBoosted(true);
        player.IncreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnDeactivate()
override void ImmunityBoost::OnDeactivate (PlayerBase player) inline private
Definition at line 42 of file immunityboost.c.
    {
        player.SetImmunityBoosted(false);
        player.DecreaseHealingsCount();
        /*
        if( player.GetNotifiersManager() )
            player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnReconnect()
override void ImmunityBoost::OnReconnect (PlayerBase player) inline private
Definition at line 22 of file immunityboost.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void ImmunityBoost::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 66 of file immunityboost.c.
    {
    }
Member Data Documentation
m_LastWaterLevel
float ImmunityBoost::m_LastWaterLevel private
Definition at line 3 of file immunityboost.c.
m_MovementState
ref HumanMovementState ImmunityBoost::m_MovementState = new HumanMovementState() private
Definition at line 4 of file immunityboost.c.
m_RegenTime
float ImmunityBoost::m_RegenTime private
Definition at line 5 of file immunityboost.c.
Referenced by DeactivateCondition(), GetDebugText(), and Init().