DayzKode: OpenableBehaviour Class Reference
OpenableBehaviour Class Reference
Private Member Functions
void Close ()
protected bool GetState ()
bool IsOpened ()
void Open ()
void OpenableBehaviour (bool bState=true)
protected void SetState (bool bState)
Private Attributes
protected bool m_IsOpened
Detailed Description
Definition at line 1 of file openablebehaviour.c.
Constructor & Destructor Documentation
OpenableBehaviour()
void OpenableBehaviour::OpenableBehaviour (bool bState = true) inline private
initial value
Definition at line 5 of file openablebehaviour.c.
    {
        m_IsOpened = bState;
    }
References m_IsOpened.
Member Function Documentation
Close()
void OpenableBehaviour::Close () inline private
Definition at line 15 of file openablebehaviour.c.
    {
        SetState(false);
    }
References SetState().
Referenced by Barrel_ColorBase::Close(), Compass::Close(), TelescopicBaton::Close(), and Barrel_ColorBase::CloseLoad().
GetState()
protected bool OpenableBehaviour::GetState () inline private
Definition at line 30 of file openablebehaviour.c.
    {
        return m_IsOpened;
    }
References m_IsOpened.
Referenced by IsOpened().
IsOpened()
bool OpenableBehaviour::IsOpened () inline private
Definition at line 20 of file openablebehaviour.c.
    {
        return GetState();
    }
References GetState().
Referenced by Barrel_ColorBase::IsOpen(), Compass::IsOpen(), TelescopicBaton::IsOpen(), and Barrel_ColorBase::OnStoreSave().
Open()
void OpenableBehaviour::Open () inline private
Definition at line 10 of file openablebehaviour.c.
    {
        SetState(true);
    }
References SetState().
Referenced by Barrel_ColorBase::Open(), Compass::Open(), TelescopicBaton::Open(), and Barrel_ColorBase::OpenLoad().
SetState()
protected void OpenableBehaviour::SetState (bool bState) inline private
Definition at line 25 of file openablebehaviour.c.
    {
        m_IsOpened = bState;
    }
References m_IsOpened.
Referenced by Close(), and Open().
Member Data Documentation
m_IsOpened
protected bool OpenableBehaviour::m_IsOpened private
Definition at line 3 of file openablebehaviour.c.
Referenced by GetState(), OpenableBehaviour(), and SetState().