DayzKode: PluginBase Class Reference
PluginBase Class Reference
Private Member Functions
void ActivateModifier (int id, PlayerBase player=NULL)
void AddKeyframe ()
void AddNewLineNoSave (string text)
void AddText (string text)
bool AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2)
void BleedingOut (PlayerBase player)
void Broadcast (int index)
Broadcasts an empty message on a channel provided in the 'index' parameter.
void BroadcastFloat (int index, float value)
void BroadcastInt (int index, int value)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
void BroadcastParam (int index, Param params)
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
void BroadcastString (int index, string value)
protected float CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd)
protected float CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type)
void CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
vector CalculatePos ()
private bool CanBeRepairedToPristine (Object item)
Item can be repaired to 100%.
bool CanRepair (ItemBase repair_kit, Object item, string damage_zone="")
private bool CanRepairToPristine (PlayerBase player)
Player can repair items to 100%; currently unused.
void CaptureFocus ()
void CaptureFocus ()
void CheckInit ()
void CheckInit ()
bool CheckMask (int source_mask, int target_mask)
void ClearFileNoSave ()
void ClearInventory (PlayerBase player)
void CommandHandler (DayZInfected infected)
void ConstructSimpleAgentList ()
bool ContainsFirstClass (string config_class_path, string class_path)
void CreateModuleWidgets ()
void CreateWidgetOverlay ()
void CursorHide ()
void CursorShow ()
void DeactivateModifier (int id, PlayerBase player=NULL)
void Decay ()
void DeleteKeyframe ()
void DeleteSceneObject (SceneObject obj)
void DeleteSelectedObject ()
private void DeselectObject ()
void DestroyModuleWidgets ()
protected bool DetermineChanceToTransmit (int agent_id, float protection, int inject_type)
void DirectAdminLogPrint (string str)
void DisplayTendency (int key, int tendency, int status=1)
void DrawDebugs ()
void EditorToggle ()
protected void EditorUpdate ()
private void EditorUpdateRuler ()
void EnableUpdate (bool enable, int type, PlayerBase player)
void EnableWidgets (bool enable)
void Event_OnClick ()
void Event_OnClickMiddle ()
SceneObject Event_OnDoubleClick ()
void Event_OnDrag ()
void ExecuteEnforceScript (int index, SceneObject scene_object, string script)
void ExecuteInitScripts ()
void FreeCameraControlDisable ()
void FreeCameraControlEnable ()
void GatherPlayerInfo ()
void GatherTemperatureSources (PlayerBase player)
float GetAgentAntiboticsResistance (int agent_id)
float GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player)
float GetAgentDieOffSpeedEx (int agent_id, PlayerBase player)
float GetAgentDigestibility (int agent_id)
float GetAgentInvasibility (int agent_id)
float GetAgentInvasibilityEx (int agent_id, PlayerBase player)
map< int, ref AgentBase > GetAgentList ()
EStatLevels GetAgentPotencyEx (int agent_id, PlayerBase player)
protected float GetAgentTransferabilityAirOut (int agent_id)
protected float GetAgentTransferabilityIn (int agent_id)
protected float GetAgentTransferabilityOut (int agent_id)
string GetBaseClassPath (string config_class_path, string class_path, string config_class)
string GetBaseClassPathCombined (string child_path, string base_class)
string GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class)
TStringArray GetConfig (string class_path, string filter_char)
TStringArray GetConfigHierarchy (string class_path)
TStringArray GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth=0, local bool check_base_class_of_class=false)
TStringArray GetConfigVariables (string class_path)
float GetDieOffSpeed (int agent_id)
bool GetDrawSelection ()
TStringArray GetFileContent ()
string GetFileName ()
string GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo)
int GetID (string name)
array< ref KeyBinding > GetKeyBindings ()
private float GetKitRepairCost (ItemBase repair_kit, Object item)
SceneData GetLoadedScene ()
bool GetLoadPlayerPos ()
string GetModuleName ()
GetModuleType ()
array< ref MouseBinding > GetMouseBindings ()
protected MouseButtonInfo GetMouseButtonInfo (int button)
private vector GetMousePositionInScene ()
string GetName (int id)
string GetOnlyChildPath (string config_class_path, string class_path)
PlantMaterialHealth GetPlantMaterial (string plant_type)
string GetPlantType (Object obj)
string GetPlayerPrefix (PlayerBase player, PlayerIdentity identity)
EStatLevels GetPotency (int agent_id)
protected float GetProtectionLevel (int type, int slot, Man player)
int GetRotationAngle ()
int GetRPCModifierID (ParamsReadContext ctx)
void GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock)
bool GetRPCUpdateState (ParamsReadContext ctx)
TStringArray GetSceneList ()
SceneObject GetSceneObjectByEntity (EntityAI entity)
SceneObject GetSceneObjectByIndex (int index)
array< ref SceneObject > GetSceneObjects ()
array< ref SceneObject > GetSceneObjectsAll ()
array< ref ScenePlayer > GetScenePlayers ()
SceneObject GetSelectedSceneObject ()
int GetSelectedSceneObjectIndex ()
map< int, string > GetSimpleAgentList ()
float GetSurfaceFertility (string surface_type)
bool GetWatching ()
bool GiveWormsToPlayer (PlayerBase player, float chance)
bool GrowDuringAntibioticsAttack (int agent_id, PlayerBase player)
void HandlePresetSpawn (PlayerBase player, ParamsReadContext ctx)
void HandleSetTime (PlayerBase player, ParamsReadContext ctx)
void Hide ()
void Hide ()
void Hide ()
void Init ()
void Init ()
void InitAttacks ()
void InitLoad ()
void InitWidgets ()
protected void InjectAgentsWithoutPlayer (EntityAI target, int agents)
protected void InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
protected void InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type)
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
protected float InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type)
will add agent to a given target
bool IsActive ()
protected bool IsCurrentUIPageValid (int ui_page_request)
bool IsEnabledFreeCamera ()
bool IsEven (int num)
even or odd
bool IsFree (Object target)
private bool IsInConsole ()
private bool IsIngame ()
protected bool IsKeyPressed (int key)
bool IsModifierLocked (int id, PlayerBase player=NULL)
private bool IsMouseInScene ()
bool IsOpened ()
bool IsPlayerRegistered (PlayerBase player)
bool IsReadOnly ()
private bool IsRepairValid (int repair_kit_type, int repairable_with_type)
bool IsRulerActivated ()
bool IsSetSystemInBitmask (PlayerBase player, int system_bit)
void LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
bool LoadFile ()
void LoadFromCfg ()
void Lock (Object target)
void LockModifier (int id, bool lock, PlayerBase player=NULL)
void Log (string msg, string label)
void LogPrint (string message)
string MakeTabs (int count, bool inheritance=false)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
buttons clicks
void OnContinouousAction (ActionData action_data)
void OnDamageEvent (PlayerBase player, TotalDamageResult damageResult)
void OnDestroy ()
override void OnDestroy ()
override void OnDestroy ()
override void OnDestroy ()
override void OnDestroy ()
void OnFrame ()
void OnGUITimer ()
void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
override void OnInit ()
void OnKeyPress (int key)
void OnKeyRelease (int key)
protected void OnMouse (int event_id, int button)
void OnMouseButtonPress (int button)
void OnMouseButtonRelease (int button)
void OnMouseWheel (int wheel)
void OnPlacementComplete (Man player, ItemBase item)
void OnRequestReceived (PlayerBase player, bool enable)
void OnRequestReceived (PlayerBase player, bool enable)
void OnRPC (ParamsReadContext ctx)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void OnRPC (ParamsReadContext ctx, PlayerBase player)
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void OnRPCAgents (ParamsReadContext ctx)
void OnRPCClearInventory (PlayerBase player)
void OnRPCLevels (ParamsReadContext ctx)
void OnRPCMods (ParamsReadContext ctx)
void OnRPCModsDetailed (ParamsReadContext ctx)
void OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx)
void OnRPCServerLogRecieved (ParamsReadContext ctx)
void OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx)
void OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx)
void OnRPCStats (ParamsReadContext ctx)
void OnRPCStatSet (ParamsReadContext ctx, PlayerBase player)
void OnRPCStomach (ParamsReadContext ctx)
void OnRPCSyncSceneObject (ParamsReadContext ctx)
void OnRPCTemp (ParamsReadContext ctx, PlayerBase player)
void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera)
void OnSpawnErrorReport (string name)
void OnUIEditorClosed ()
void OnUIEditorOpened ()
void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
override void OnUpdate (float delta_time)
void PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo)
void PlayerKilled (PlayerBase player, Object source)
void PlayerList ()
void PlayPause ()
void PluginAdminLog ()
void PluginBase ()
void PluginConfigViewer ()
void PluginDayZInfectedDebug ()
void PluginDeveloper ()
void PluginDeveloperSync ()
void PluginDrawCheckerboard ()
void PluginFileHandler ()
void PluginHorticulture ()
void PluginKeyBinding ()
void PluginMessageManager ()
void PluginObjectsInteractionManager ()
void PluginPlayerStatus ()
void PluginSceneManager ()
void PluginTransmissionAgents ()
void PluginUniversalTemperatureSourceClient ()
void PluginUniversalTemperatureSourceServer ()
void PluginVariables ()
void PrintedDebug ()
void PrintLogClient (string msg_log)
protected void ProcessUniversalTemperatureSources ()
void QuickSort (TStringArray arr, int left, int right)
int QuickSortPartition (TStringArray arr, int left, int right)
void RegisterAgent (AgentBase agent)
protected void RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description)
protected void RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description)
void RegisterPlayer (PlayerBase player)
void RegisterVariable (string name)
void Release (Object target)
void ReleaseFocus ()
void ReleaseFocus ()
void RemoveAllAgents (EntityAI target)
bool Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone="", bool use_kit_qty=true)
void RequestDetailedInfo (int id, notnull PlayerBase player)
void RequestUniversalTemperatureSources (PlayerBase player, int enable)
void ResetGUI ()
void ResetValues ()
void RestoreSceneObjectsLinks ()
void RulerAddPoint ()
void RulerClearVisuals ()
void RulerDelete ()
void RulerToggle ()
void Save ()
bool SaveFile ()
bool SceneCanDelete (string scene_name)
bool SceneDelete (string scene_name)
void SceneDuplicate (string scene_name)
private void SceneEditorMenuCmdPopup (string message)
private void SceneEditorMenuCmdRefresh ()
private void SceneEditorMenuCmdSave ()
string SceneGetName ()
void SceneLoad (string scene_name)
void SceneRename (string scene_name, string new_name)
void SceneSave ()
void SceneUnload ()
private void ScriptHistoryBack ()
private void ScriptHistoryNext ()
void SelectAndFocusPlayerObject ()
void SelectClassName (string class_name)
void SelectedObjectAddAttachment (string att_name)
void SelectedObjectDuplicate ()
void SelectedObjectFocus ()
void SelectedObjectRemoveAttachment (EntityAI e)
void SelectedObjectSetDamage (float value)
void SelectedObjectSetPosX (float value)
void SelectedObjectSetPosY (float value)
void SelectedObjectSetPosZ (float value)
void SelectedObjectSetRot (float dir)
void SelectObject (SceneObject obj)
void SendDebug ()
void SendDebug ()
void SendRPCAgents (PlayerBase player)
void SendRPCLevels (PlayerBase player)
void SendRPCMods (PlayerBase player)
void SendRPCModsDetail (PlayerBase player)
void SendRPCStats (PlayerBase player)
void SendRPCStomach (PlayerBase player)
void SendRPCTemp (PlayerBase player)
void SendServerLogToClient (string msg)
void SetBadge (int key, int value)
void SetDate (int year, int month, int day, int hour, int minute)
void SetDeveloperItemClient ()
void SetDrawSelection (bool draw)
void SetLoadPlayerPos (bool save)
void SetNotifier (int key, int index=9, string label="", int color=0xFFFFFFFF)
void SetRotationAngle (int angle)
void SetStamina (int value, int range)
void SetStance (int value)
void SetSystemInBitmask (PlayerBase player, int system_bit, bool state)
void SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity=-1, bool special=false, string presetName="")
void SetWatching (bool enable)
void SetWeather (float overcast, float rain, float fog, float wind_force)
void Show ()
void Show ()
void Show ()
void ShowCard (int pCard)
void ShowWidgets (bool show)
void ShowWidgets (bool show)
void SortStringArray (TStringArray arr)
EntityAI SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity)
tries to spawn item as attachment
EntityAI SpawnEntityInInventory (PlayerBase player, string item_name, float health, float quantity, bool special=false, string presetName="")
tries to spawn item somewhere in inventory
EntityAI SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health=-1, bool special=false, string presetName="")
spawns entity in direction of cursor at specified distance
void SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow=1, float gapColumn=1)
EntityAI SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos)
spawns entity on exact position
EntityAI SpawnFromClipboard ()
void SpawnNewInfectedEntity ()
void Subscribe (MessageReceiverBase receiver, int index)
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
void Suicide (PlayerBase player)
void SwitchPermanentCrossHair (bool state)
void Teleport (PlayerBase player, vector position)
Teleport player at position.
void TeleportAtCursor ()
Set Player position at his cursor position in the world.
void Tick ()
void ToggleCameraTools ()
void ToggleDebugWindowEvent ()
void ToggleDebugWindowSetMode (int pMode)
void ToggleFocus ()
void ToggleFreeCamera ()
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
void ToggleFreeCameraBackPos ()
Enable / Disable Free camera (Fly mod)
void ToggleHelpScreen ()
void ToggleMissionLoader ()
void ToggleScriptConsole ()
void TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size=1000)
float TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size=1000, int agents=0)
void UnconStart (PlayerBase player)
void UnconStop (PlayerBase player)
void UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2)
void Unsubscribe (MessageReceiverBase receiver, int index)
void UnsubscribeAll (MessageReceiverBase receiver)
void Update ()
void UpdateStatsLocal ()
void UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd)
void UpdateStatWidgets ()
void ~PluginAdminLog ()
void ~PluginBase ()
void ~PluginDayZInfectedDebug ()
void ~PluginDrawCheckerboard ()
void ~PluginFileHandler ()
void ~PluginSceneManager ()
void ~PluginVariables ()
Static Private Member Functions
static void BuildAgentArray (int agents, array< int > agents_out)
static bool FileDelete (string file)
static bool FileDuplicate (string source_name, string dest_name)
static void FileRename (string source_name, string dest_name)
static int GetAgentMaxCount (int agent_id)
static PluginCameraTools GetInstance ()
static PluginDeveloper GetInstance ()
static PluginSceneManager GetInstance ()
static string GetNameByID (int agent_id)
static int GetPlayerListTimer ()
static float GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter=true, int system=0)
static void RemoveAgent (EntityAI target, int agent_id)
static void SetDeveloperItemClientEx (notnull Object entity, bool getFocus=false)
Private Attributes
ref array< ref MessageReceiverBase > channelList [NUM_OF_CHANNELS]
int channelsUsed = 0
protected const int CLICK_TIME = 200
protected const int DOUBLE_CLICK_TIME = 300
float fadeInVolume = 1.1
float fadeOutVolume = 0.9
const float FOV = 0.5236
protected const int HOLD_CLICK_TIME_MIN = 300
const int INTERVAL = 1
const float LOOKUP_RADIUS = 20
[s]
float m_AccuTime
protected float m_AccuTime
[m]
protected int m_ActionsFilter
bool m_AgentsUpdateStatus
ref array< ref PluginDayZInfectedDebugAttackDesc > m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc>
XComboBoxWidget m_AttackDirCB
XComboBoxWidget m_AttackTypeCB
BleedingSourcesManagerServer m_BleedMgr
vector m_cam_pos
vector m_camera_dir
vector m_camera_orientation
vector m_cameraTrans [4]
ButtonWidget m_CardFightButton
Widget m_CardFightFrame
ButtonWidget m_CardMovementButton
Widget m_CardMovementFrame
bool m_CH_DoAttack = false
bool m_CH_DoHit = false
bool m_CH_DoKnucleOut = false
bool m_CH_DoTurn = false
command handler values
bool m_CH_DoVault = false
bool m_CH_GoToCrawl = false
bool m_CH_StartDeath = false
PlayerBase m_Character
vector m_character_pos
protected string m_ClassBrowserSelected
ref set< PlayerBase > m_ClientList = new set<PlayerBase>
protected ref set< PlayerBase > m_ClientList
DayZInfected m_ControlledInfected
controlled instance
XComboBoxWidget m_CrawlingTypeCB
int m_CurrentMode = 0
XComboBoxWidget m_DeathTypeCB
eRemoteDebugType m_DebugType
private ref Timer m_DecayTimer
vector m_demoPos
vector m_demoRot
int m_DetailedInfoRequested = 0
string m_DisplayName
float m_Distance
int m_DotIndex
string m_EnvironmentDebugMessage
protected int m_FeaturesMask
ref TStringArray m_FileContent
bool m_HasFocus = false
XComboBoxWidget m_HitBodyPartCB
EditBoxWidget m_HitDirEB
fight card
protected int m_HitFilter
string m_HitMessage
XComboBoxWidget m_HitTypeCB
private Hud m_Hud
int m_Id
bool m_Initialized
bool m_IsActive = false
private bool m_IsActive
bool m_IsConstructed = false
protected bool m_IsDragging
protected bool m_IsOpen
protected bool m_IsWinHolding
string m_ItemInHands
protected ref array< ref KeyBinding > m_KeyBindings
protected ref map< int, KeyBinding > m_KeyBindings
ButtonWidget m_KnucleOutButton
bool m_LevelsUpdateStatus
int m_LineLimit
private ref array< Object > m_LockedObjects
private ref array< float > m_LockedObjectsDecay
private ref Widget m_MainWindow
Widget m_MainWnd
main controls
string m_Message
XComboBoxWidget m_MindStateCB
bool m_ModsUpdateStatus
protected PluginConfigDebugProfile m_ModuleConfigDebugProfile
protected PluginConfigScene m_ModuleConfigScene
PluginDeveloper m_ModuleDeveloper
protected PluginDeveloper m_ModuleDeveloper
protected ref array< ref MouseBinding > m_MouseBindings
protected ref array< ref MouseButtonInfo > m_MouseButtons
EditBoxWidget m_MovementSpeedEB
private ref multiMap< int, string > m_NotifiersIcons
ref multiMap< int, int > m_NotifiersIndexColor
ref multiMap< int, string > m_NotifiersLabel
string m_Pid
protected int m_PlacementFilter
ref map< string, ref PlantMaterialHealth > m_PlantMaterials
PlayerBase m_Player
protected PlayerBase m_Player
ref array< ref SyncedValueAgent > m_PlayerAgentsSynced
autoptr array< Man > m_PlayerArray
ref map< PlayerBase, ref RemotePlayerDamageDebug > m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug>
ref array< ref RemotePlayerStatDebug > m_PlayerDebugStats = new array<ref RemotePlayerStatDebug>
ref array< ref SyncedValueLevel > m_PlayerLevelsSynced
protected int m_PlayerListFilter
string m_PlayerModsDetailedSynced
ref array< ref SyncedValueModifier > m_PlayerModsSynced
string m_PlayerName
string m_PlayerPrefix
string m_PlayerPrefix2
ref array< ref SyncedValue > m_PlayerStatsSynced
ref array< ref Param > m_PlayerStomachSynced
string m_PosArray [3]
vector m_Position
protected int m_PressedMouseID
ref PluginDayZInfectedDebugUIHandler m_pUIHandler
bool m_ReadOnly
ref map< PlayerBase, ref RegisterPlayerData > m_RegisteredPlayers
protected ref Widget m_RootWidget [MAX_SIMULTANEOUS_UTS]
ItemBase m_Ruler
bool m_RulerActivated
ref array< Shape > m_RulerLines
ref array< vector > m_RulerPoints
ref array< Shape > m_RulerSpheres
protected ref SceneData m_SceneData
UIScriptedMenu m_ScriptConsole
protected SceneObject m_SelectedObject
protected ref array< Shape > m_ShapesSceneObjects
ref map< int, string > m_SimpleAgentList = new map<int, string>
ref SoundObjectBuilder m_soundBuilder
ref SoundObject m_soundObject
ref SoundParams m_soundParams
PlayerBase m_Source
ButtonWidget m_SpawnEntityButton
XComboBoxWidget m_StanceCB
movement card
ButtonWidget m_StartAttackButton
ButtonWidget m_StartCrawlingButton
ButtonWidget m_StartDeathButton
ButtonWidget m_StartHitButton
ButtonWidget m_StartTurnButton
ButtonWidget m_StartVaultButton
PlayerStat< float > m_StatEnergy
protected ref TextListboxWidget m_StatListWidgets [MAX_SIMULTANEOUS_UTS]
bool m_StatsUpdateStatus
TextWidget m_StatusText
PlayerStat< float > m_StatWater
bool m_StomachUpdateStatus
ref Timer m_TickTimer
status refresh timer
protected float m_TimeLastClickPress
protected float m_TimeLastClickRelease
ref Timer m_Timer
EditBoxWidget m_TurnDirectionEB
XComboBoxWidget m_TurnTypeCB
ref Timer m_UpdateTimer
protected ref array< ref UTemperatureSourceDebug > m_UTemperatureSourceDebugs
protected float m_UTSAverageTemperature
ref map< int, string > m_Variables
XComboBoxWidget m_VaultingCB
bool m_Watching
AbstractWave m_wave
const int MAX_SIMULTANEOUS_UTS = 10
private const float TICK_RATE = 10
private const float TIME_TO_FORCED_UNLOCK = 60
const int TIMER_PLAYERLIST = GetPlayerListTimer()
Static Private Attributes
static PluginKeyBinding instance
static PluginSceneManager instance
static ref map< int, ref AgentBase > m_AgentList = new map<int, ref AgentBase>
static protected PluginCameraTools m_Instance
static protected bool m_IsOpen
static PlayerBase PLAYER
static string SCENE_DEFAULT_NAME = "default"
static const int SCENE_EDITOR_CMD_POPUP = 1
static const int SCENE_EDITOR_CMD_REFRESH = 0
static const int SCENE_EDITOR_CMD_SAVE = 2
static string SCENE_SUFIX = "scene"
Detailed Description
Class PluginMessageManager provides some basic Message Distribution mechanics, if you get instance of this plugin class on your object, you can use its methods to broadcast messages.
Definition at line 1 of file pluginbase.c.
Constructor & Destructor Documentation
PluginBase()
void PluginBase::PluginBase () inline private
Definition at line 3 of file pluginbase.c.
    {
    }
~PluginBase()
void PluginBase::~PluginBase () inline private
Definition at line 7 of file pluginbase.c.
    {
    }
~PluginAdminLog()
void PluginBase::~PluginAdminLog () inline private
Definition at line 58 of file pluginadminlog.c.
    {
    }
~PluginDayZInfectedDebug()
void PluginBase::~PluginDayZInfectedDebug () inline private
Definition at line 108 of file plugindayzinfecteddebug.c.
    {
        #ifndef NO_GUI
        DestroyModuleWidgets();
        #endif
    }
References DestroyModuleWidgets().
~PluginDrawCheckerboard()
void PluginBase::~PluginDrawCheckerboard () inline private
Definition at line 14 of file plugindrawcheckerboard.c.
{}
~PluginFileHandler()
void PluginBase::~PluginFileHandler () inline private
Definition at line 32 of file pluginfilehandler.c.
    {
        ClearFileNoSave();
    }
~PluginSceneManager()
void PluginBase::~PluginSceneManager () inline private
Definition at line 30 of file pluginscenemanager.c.
    {
        if ( instance == NULL )
        {
            instance = this;
        }
    }
~PluginVariables()
void PluginBase::~PluginVariables () inline private
Definition at line 13 of file pluginvariables.c.
    {
    }
Member Function Documentation
ActivateModifier()
void PluginBase::ActivateModifier (int id, PlayerBase player = NULL) inline private
Definition at line 661 of file plugindevelopersync.c.
    {
        if ( !player )
        {
            player = PlayerBase.Cast( GetDayZGame().GetPlayer() );
        }
        ModifiersManager mods_manager = player.GetModifiersManager();
        mods_manager.ActivateModifier( Math.AbsInt( id ) );
    }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
AddKeyframe()
void PluginBase::AddKeyframe () inline private
Definition at line 62 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnKeyPress( null, 0, 0, KeyCode.KC_Q );
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
AddNewLineNoSave()
void PluginBase::AddNewLineNoSave (string text) inline private
Definition at line 115 of file pluginfilehandler.c.
    {
        if ( m_LineLimit > -1 )
        {
            if ( m_LineLimit == 0 )
            {
                return;
            }
            int lines_count = m_FileContent.Count();
            if ( lines_count > 0 && lines_count >= m_LineLimit )
            {
                int remove_indexes = lines_count - m_LineLimit;
                for ( int i = 0; i <= remove_indexes; ++i )
                {
                    m_FileContent.RemoveOrdered(0);
                }
            }
        }
        m_FileContent.Insert(text);
    }
AddText()
void PluginBase::AddText (string text) inline private
Definition at line 109 of file pluginfilehandler.c.
    {
        AddNewLineNoSave(text);
        SaveFile();
    }
AreSceneObjectsLinked()
bool PluginBase::AreSceneObjectsLinked (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 689 of file pluginscenemanager.c.
    {
        if ( scene_object1.IsLinkedWithSceneObject(scene_object2) && scene_object2.IsLinkedWithSceneObject(scene_object1) )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References SceneObject::IsLinkedWithSceneObject().
BleedingOut()
void PluginBase::BleedingOut (PlayerBase player) inline private
Definition at line 328 of file pluginadminlog.c.
    {
        m_PlayerPrefix = this.GetPlayerPrefix( player ,  player.GetIdentity() );
        LogPrint( m_PlayerPrefix + " bled out" );
    }
References GetPlayerPrefix(), and LogPrint().
Broadcast()
void PluginBase::Broadcast (int index) inline private
Broadcasts an empty message on a channel provided in the 'index' parameter.
Definition at line 18 of file pluginmessagemanager.c.
    {
        //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
        array<ref MessageReceiverBase> x = channelList[index];
        //int test = channelList[index].Count();
        for(int i = 0; i < x.Count(); i++)
        {
            MessageReceiverBase mrb = x.Get(i);
            if( mrb != NULL )
            {
                //string s = "Broadcasting message to: "+ToString(mrb);
                //Log(s, LogTemplates.TEMPLATE_BROADCAST);
                mrb.OnReceive(index);
            }
        }
    }
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceive(), and x.
BroadcastFloat()
void PluginBase::BroadcastFloat (int index, float value) inline private
Definition at line 56 of file pluginmessagemanager.c.
    {
        //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
        array<ref MessageReceiverBase> x = channelList[index];
        //int test = channelList[index].Count();
        for(int i = 0; i < x.Count(); i++)
        {
            MessageReceiverBase mrb = x.Get(i);
            if( mrb )
            {
                //string s = "Broadcasting message to: "+ToString(mrb);
                //Log(s, LogTemplates.TEMPLATE_BROADCAST);
                mrb.OnReceiveFloat(index, value);
            }
        }
    }
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceiveFloat(), and x.
BroadcastInt()
void PluginBase::BroadcastInt (int index, int value) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Int variable.
Definition at line 37 of file pluginmessagemanager.c.
    {
        //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
        array<ref MessageReceiverBase> x = channelList[index];
        //int test = channelList[index].Count();
        for(int i = 0; i < x.Count(); i++)
        {
            MessageReceiverBase mrb = x.Get(i);
            if( mrb )
            {
                //string s = "Broadcasting message to: "+ToString(mrb);
                //Log(s, LogTemplates.TEMPLATE_BROADCAST);
                mrb.OnReceiveInt(index, value);
            }
        }
    }
References LayoutHolder::Count(), LayoutHolder::Get(), MessageReceiverBase::OnReceiveInt(), and x.
BroadcastParam()
void PluginBase::BroadcastParam (int index, Param params) inline private
Broadcasts a message on a channel provided in the 'index' parameter, passes the Param type object to the reciever.
Definition at line 92 of file pluginmessagemanager.c.
    {
        //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
        array<ref MessageReceiverBase> x = channelList[index];
        //int test = channelList[index].Count();
        for(int i = 0; i < x.Count(); i++)
        {
            if( x.Get(i) )
            {
                x.Get(i).OnReceiveParam(index, params);
            }
        }
    }
References LayoutHolder::Count(), LayoutHolder::Get(), and x.
BroadcastString()
void PluginBase::BroadcastString (int index, string value) inline private
Definition at line 75 of file pluginmessagemanager.c.
    {
        //Debug.Log("Broadcasting message on a channel: "+ ToString(index), "Messaging System");
        array<ref MessageReceiverBase> x = channelList[index];
        //int test = channelList[index].Count();
        for(int i = 0; i < x.Count(); i++)
        {
            if( x.Get(i) )
            {
                Print("broadcasting message to: ");
                Print(x.Get(i));
                x.Get(i).OnReceiveString(index, value);
            }
        }
    }
References LayoutHolder::Count(), LayoutHolder::Get(), Print(), and x.
BuildAgentArray()
static void PluginBase::BuildAgentArray (int agents, array< int > agents_out) inline static private
Definition at line 322 of file plugintransmissionagents.c.
    {
        int mask = 1;
        for(int i = 0; i < BIT_INT_SIZE; i++)
        {
            if( mask & agents )
                agents_out.Insert(mask);
            mask = mask * 2;
        }
    }
References BIT_INT_SIZE.
CalcTemperatureFromTemperatureSource()
protected float PluginBase::CalcTemperatureFromTemperatureSource (notnull UTemperatureSourceDebug utsd) inline private
heat transfer through air to player (env temperature)
dist factor minimum should be at 0
Definition at line 122 of file pluginuniversaltemperaturesourceclient.c.
    {
        float distance      = vector.Distance(m_Player.GetPosition(), utsd.GetValue(0).ToVector());
        distance            = Math.Max(distance, 0.1);  //min distance cannot be 0 (division by zero)
        float temperature   = 0;
        if (distance > utsd.GetValue(1).ToFloat())
        {
            float distFactor = 1 - (distance / utsd.GetValue(2).ToFloat());
            distFactor = Math.Max(distFactor, 0.0);
            temperature = utsd.GetValue(3).ToFloat() * distFactor;
        }
        else
        {
            temperature = utsd.GetValue(3).ToFloat();
        }
        //Print(temperature);
        return temperature;
    }
References vector::Distance(), m_Player, and Math::Max().
Referenced by ProcessUniversalTemperatureSources().
CalculateAgentsToTransmit()
protected float PluginBase::CalculateAgentsToTransmit (int agent_id, float protection, int dose_size, int inject_type) inline private
Definition at line 352 of file plugintransmissionagents.c.
    {
        //Debug.Log("protection: "+protection.ToString());
        float prot = 1 - protection; //reverse the value (in config, the higher the value, the higher the protection: 0 - 1) so that we can easily interpolate between 0 and 1 by multiplication
        //Debug.Log("prot: "+prot.ToString(), "Agents");
        float transf;
        if( inject_type == InjectTypes.PLAYER_TO_ITEM )
        {
            transf = GetAgentTransferabilityOut(agent_id);
        }
        else if( inject_type == InjectTypes.ITEM_TO_PLAYER )
        {
            transf = GetAgentTransferabilityIn(agent_id);
        }
        else if( inject_type == InjectTypes.PLAYER_AIR_PLAYER )
        {
            transf = GetAgentTransferabilityAirOut(agent_id);
        }
        //Debug.Log("transf: "+transf.ToString(), "Agents");
        //float result =  GetAgentInitialCount(agent_id) * prot * transf * dose_size;//final formula
        float result =  1 * prot * transf * dose_size;//final formula
        //result = Math.Ceil(result);
        //Debug.Log("result: "+result.ToString(), "Agents");
        return result;
    }
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), and GetAgentTransferabilityOut().
Referenced by InjectAgentsWithPlayerCount(), and InjectAgentWithPlayerDose().
CalculateHealth()
void PluginBase::CalculateHealth (PlayerBase player, ItemBase kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
Definition at line 29 of file pluginrepairing.c.
    {
        EntityAI entity;
        Class.CastTo(entity,item);
        if (entity != null)
        {
            //Print("" + item + " - damage allowed");
            entity.SetAllowDamage(true);
        }
        bool kit_has_quantity = kit.HasQuantity();
        int health_levels_count = item.GetNumberOfHealthLevels(damage_zone);
        float cur_kit_quantity = kit.GetQuantity();
        float kit_repair_cost_per_level = GetKitRepairCost( kit, item );
        float kit_repair_cost_adjusted; //used with specialty_weight, disconnected
        float new_quantity;
        int target_level = Math.Clamp(item.GetHealthLevel(damage_zone) - 1, 0, health_levels_count - 1);
        float health_coef;
        if ( !CanRepairToPristine( player ) && !CanBeRepairedToPristine( item ) )
        {
            target_level = Math.Clamp(target_level, GameConstants.STATE_WORN, health_levels_count - 1);
        }
        health_coef = item.GetHealthLevelValue(target_level,damage_zone);
        //handles kit depletion; TODO: move to separate method.
        if ( cur_kit_quantity > kit_repair_cost_per_level )
        {
            kit_repair_cost_adjusted = kit_repair_cost_per_level; //TODO: removed speciality weight for now, it should affect speed only (?).
            //kit_repair_cost_adjusted = player.GetSoftSkillsManager().SubtractSpecialtyBonus( kit_repair_cost_per_level, specialty_weight );
            kit_repair_cost_adjusted = Math.Clamp( kit_repair_cost_adjusted, 0, 100 );
            if(use_kit_qty)
            {
                new_quantity = kit.GetQuantity() - kit_repair_cost_adjusted;
                kit.SetQuantity( new_quantity );
            }
        }
        else if (!kit_has_quantity) //"kit" without quantity (hammers and such) for your every day repairing needs
        {
        }
        else
        {
            if(use_kit_qty)
            {
                kit.SetQuantity( 0 );
            }
        }
        if (item.GetHealth01(damage_zone,"Health") < health_coef)
        {
            item.SetHealth01(damage_zone,"Health",health_coef);
        }
        if (entity != null)
        {
            entity.ProcessInvulnerabilityCheck(entity.GetInvulnerabilityTypeString());
        }
    }
References CanBeRepairedToPristine(), CanRepairToPristine(), Class::CastTo(), Math::Clamp(), GetKitRepairCost(), and GameConstants::STATE_WORN.
Referenced by Repair().
CalculatePos()
vector PluginBase::CalculatePos () inline private
Definition at line 69 of file plugincharplacement.c.
    {
        vector cam_pos = FreeDebugCamera.GetInstance().GetPosition();
        Math3D.MatrixIdentity4(m_cameraTrans);
        Math3D.DirectionAndUpMatrix(m_camera_dir/* - SnapToGround(cam_pos)*/, "0 1 0", m_cameraTrans);
        m_cameraTrans[3] = cam_pos;
        m_demoPos = Vector(/*0.685547, -0.988281,*/0,0, 3.68823).Multiply4(m_cameraTrans);
        m_demoPos[1] = GetGame().SurfaceY(m_demoPos[0], m_demoPos[2]);
        return m_demoPos;
    }
References Math3D::DirectionAndUpMatrix(), GetGame(), m_demoPos, Math3D::MatrixIdentity4(), vector::Multiply4(), CGame::SurfaceY(), and Vector().
Referenced by OnUpdate().
CanBeRepairedToPristine()
private bool PluginBase::CanBeRepairedToPristine (Object item) inline private
Item can be repaired to 100%.
Definition at line 147 of file pluginrepairing.c.
    {
        return item.CanBeRepairedToPristine();
    }
CanRepair()
bool PluginBase::CanRepair (ItemBase repair_kit, Object item, string damage_zone = "") inline private
Definition at line 89 of file pluginrepairing.c.
    {
        int state = item.GetHealthLevel(damage_zone);
        if ( state != GameConstants.STATE_RUINED && (item.CanBeRepairedToPristine() && state >= GameConstants.STATE_WORN) || (!item.CanBeRepairedToPristine() && state >= GameConstants.STATE_DAMAGED ) )
        {
            int repair_kit_type = repair_kit.ConfigGetInt( "repairKitType" );
            ref array<int> repairable_with_types = new array<int>;
            item.ConfigGetIntArray( "repairableWithKits", repairable_with_types );
            for ( int i = 0; i < repairable_with_types.Count(); i++ )
            {
                int repairable_with_type = repairable_with_types.Get(i);
                if ( IsRepairValid( repair_kit_type, repairable_with_type ) )
                {
                    return true;
                }
            }
        }
        return false;
    }
References IsRepairValid(), GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CanRepairToPristine()
private bool PluginBase::CanRepairToPristine (PlayerBase player) inline private
Player can repair items to 100%; currently unused.
Definition at line 128 of file pluginrepairing.c.
    {
// temporary disabled
/*
        float specialty = player.GetStatSpecialty().Get();
        if ( specialty <= -0.5 || specialty >= 0.5 )
        {
            return true;
        }
        else
        {
            return false;
        }
*/
        return false;
    }
Referenced by CalculateHealth(), and Repair().
CaptureFocus() [1/2]
void PluginBase::CaptureFocus () inline private
Definition at line 139 of file plugindayzinfecteddebug.c.
    {
        if (!m_HasFocus)
        {
            GetGame().GetInput().ChangeGameFocus(1);
            GetGame().GetUIManager().ShowUICursor(true);
            m_HasFocus = true;
        }
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
Referenced by ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
CaptureFocus() [2/2]
void PluginBase::CaptureFocus () inline private
Definition at line 853 of file plugindevelopersync.c.
    {
        GetGame().GetInput().ChangeGameFocus( 1 );
        GetGame().GetUIManager().ShowUICursor( true );
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), and UIManager::ShowUICursor().
CheckInit() [1/2]
void PluginBase::CheckInit () inline private
Definition at line 17 of file plugincharplacement.c.
    {
        if ( m_Initialized )
        {
            Print("logging...");
            Log(FOV.ToString(),"FOV");
            Log(m_camera_dir.ToString(),"camera dir");
            Log(m_cam_pos.ToString(),"camera pos");
            Log(m_demoPos.ToString(),"character pos");
            return;
        }
        if( FreeDebugCamera.GetInstance().IsActive() )
            Init();
    }
References Init(), Log(), m_Initialized, Print(), float::ToString(), and vector::ToString().
CheckInit() [2/2]
void PluginBase::CheckInit () inline private
Definition at line 8 of file plugindoorruler.c.
    {
        if( FreeDebugCamera.GetInstance().IsActive() )
            Init();
    }
References Init().
CheckMask()
bool PluginBase::CheckMask (int source_mask, int target_mask) inline private
Definition at line 323 of file pluginkeybinding.c.
    {
        if ( ( source_mask & target_mask ) == target_mask )
        {
            return true;
        }
        return false;
    }
ClearFileNoSave()
void PluginBase::ClearFileNoSave () inline private
Definition at line 47 of file pluginfilehandler.c.
    {
        m_FileContent.Clear();
    }
ClearInventory()
void PluginBase::ClearInventory (PlayerBase player) inline private
Definition at line 594 of file plugindeveloper.c.
    {
        if ( GetGame().IsServer() )
        {
            player.ClearInventory();
        }
        else
        {
            Param1<int> params = new Param1<int>(0);
            player.RPCSingleParam(ERPCs.DEV_RPC_CLEAR_INV, params, true);
        }
    }
References GetGame().
Referenced by OnRPCClearInventory().
CommandHandler()
void PluginBase::CommandHandler (DayZInfected infected) inline private
Definition at line 348 of file plugindayzinfecteddebug.c.
    {
        if( infected != m_ControlledInfected )
            return;
        infected.GetInputController().OverrideMovementSpeed(true, m_MovementSpeedEB.GetText().ToFloat());
        DayZInfectedCommandMove moveCommand = infected.GetCommand_Move();
        if( moveCommand )
        {
            moveCommand.SetStanceVariation(m_StanceCB.GetCurrentItem());
            moveCommand.SetIdleState(m_MindStateCB.GetCurrentItem());
        }
        if( m_CH_DoTurn )
        {
            moveCommand.StartTurn(m_TurnDirectionEB.GetText().ToFloat(), m_TurnTypeCB.GetCurrentItem());
            m_CH_DoTurn = false;
        }
        if( m_CH_DoVault )
        {
            infected.StartCommand_Vault(m_VaultingCB.GetCurrentItem());
            m_CH_DoVault = false;
        }
        if( m_CH_DoKnucleOut )
        {
            infected.StartCommand_Vault(-1);
            m_CH_DoKnucleOut = false;
        }
        if( m_CH_GoToCrawl )
        {
            infected.StartCommand_Crawl(m_CrawlingTypeCB.GetCurrentItem());
            m_CH_GoToCrawl = false;
        }
        if( m_CH_DoHit )
        {
            float hitDir = m_HitDirEB.GetText().ToFloat();
            int bodyPart = m_HitBodyPartCB.GetCurrentItem();
            bool heavyHit = m_HitTypeCB.GetCurrentItem() == 1;
            infected.StartCommand_Hit(heavyHit, bodyPart, hitDir);
            m_CH_DoHit = false;
        }
        if( m_CH_StartDeath )
        {
            int deathType = m_DeathTypeCB.GetCurrentItem();
            float deathDir = m_HitDirEB.GetText().ToFloat();
            infected.StartCommand_Death(deathType, deathDir);
            m_CH_StartDeath = false;
        }
        if( m_CH_DoAttack )
        {
            float attackDir = m_AttackDirCB.GetCurrentItem();
            int attackType = m_AttackDescriptors.Get(m_AttackTypeCB.GetCurrentItem()).animValue;
            infected.StartCommand_Attack(null, attackType, attackDir);
            m_CH_DoAttack = false;
        }
    }
ConstructSimpleAgentList()
void PluginBase::ConstructSimpleAgentList () inline private
Definition at line 32 of file plugintransmissionagents.c.
    {
        string agent_name;
        int agent_type;
        for(int i = 0; i < m_AgentList.Count();i++)
        {
            AgentBase agent = m_AgentList.GetElement(i);
            agent_name = agent.GetName();
            agent_type = agent.GetAgentType();
            m_SimpleAgentList.Insert(agent_type, agent_name);
        }
    }
Referenced by GetSimpleAgentList().
ContainsFirstClass()
bool PluginBase::ContainsFirstClass (string config_class_path, string class_path) inline private
Definition at line 114 of file pluginconfigviewer.c.
    {
        int start = class_path.IndexOf(" ");
        string name = class_path;
        if ( start > -1 )
        {
            name = class_path.Substring(0, start );
        }
        int cfg_class_count = GetGame().ConfigGetChildrenCount( config_class_path );
        for ( int i = 0; i < cfg_class_count; i++ )
        {
            string cfg_class_name = "";
            GetGame().ConfigGetChildName( config_class_path, i, cfg_class_name );
            if ( cfg_class_name == name )
            {
                string full_name = config_class_path + " " + name;
                int type = GetGame().ConfigGetType( full_name );
                if ( type == CT_CLASS )
                {
                    return true;
                }
            }
        }
        if ( start == -1 )
        {
            return false;
        }
        else
        {
            string new_name =  class_path.Substring(start + 1, class_path.Length() - (start + 1) );
            return ContainsFirstClass( config_class_path + " " + name, new_name );
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetType(), ContainsFirstClass(), GetGame(), string::IndexOf(), string::Length(), name, and string::Substring().
Referenced by ContainsFirstClass(), and GetBaseClassPathRecursive().
CreateModuleWidgets()
void PluginBase::CreateModuleWidgets () inline private
main controls
movement card
fight card
fill some controls
Definition at line 197 of file plugindayzinfecteddebug.c.
    {
        if (!m_pUIHandler)
        {
            m_pUIHandler = new PluginDayZInfectedDebugUIHandler();
            m_pUIHandler.m_pPluginInfectedDebug = this;
        }
        if (!m_MainWnd)
        {
            m_MainWnd = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_infecteddebug.layout");
            m_MainWnd.SetHandler(m_pUIHandler);
            m_MainWnd.Show(false);
        }
        m_SpawnEntityButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("SpawnEntityButton") );
        m_CardMovementButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("CardMovementButton") );
        m_CardFightButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("CardFightButton") );
        m_CardMovementFrame = m_MainWnd.FindAnyWidget("CardMovementFrame");
        m_CardFightFrame = m_MainWnd.FindAnyWidget("CardFightFrame");
        m_StatusText = TextWidget.Cast( m_MainWnd.FindAnyWidget("StatusText") );
        m_StanceCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("StanceCB") );
        m_MindStateCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("MindStateCB") );
        m_MovementSpeedEB = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("MovementSpeedEB") );
        m_StartTurnButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartTurnButton") );
        m_TurnTypeCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("TurnTypeCB") );
        m_TurnDirectionEB = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("TurnDirectionEB") );
        m_VaultingCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("TurnTypeCB") );
        m_StartVaultButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartVaultButton") );
        m_KnucleOutButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("KnucleOutButton") );
        m_CrawlingTypeCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("TurnTypeCB") );
        m_StartCrawlingButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartCrawlingButton") );
        m_HitDirEB = EditBoxWidget.Cast( m_MainWnd.FindAnyWidget("HitDirEB") );
        m_HitTypeCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("HitTypeCB") );
        m_HitBodyPartCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("HitBodyPartCB") );
        m_StartHitButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartHitButton") );
        m_DeathTypeCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("DeathTypeCB") );
        m_StartDeathButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartDeathButton") );
        m_AttackTypeCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("AttackTypeCB") );
        m_AttackDirCB = XComboBoxWidget.Cast( m_MainWnd.FindAnyWidget("AttackDirCB") );
        m_StartAttackButton = ButtonWidget.Cast( m_MainWnd.FindAnyWidget("StartAttackButton") );
        InitAttacks();
        ShowCard(0);
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), InitAttacks(), m_MainWnd, m_pUIHandler, and ShowCard().
Referenced by PluginDayZInfectedDebug(), and PluginDayzPlayerDebug().
CreateWidgetOverlay()
void PluginBase::CreateWidgetOverlay () inline private
row counter
sets alpha level for even/odd child
Definition at line 16 of file plugindrawcheckerboard.c.
    {
#ifndef NO_GUI
        if (!m_MainWindow)
        {
            m_MainWindow = GetGame().GetWorkspace().CreateWidgets("gui/layouts/camera_checkerboard.layout");
            m_MainWindow.Show(false);
            int childId = 0;
            int row = 0;
            bool evenOrOdd;
            int tilesPerLine = 8;
            Widget child = m_MainWindow.GetChildren();
            while(child)
            {
                evenOrOdd = IsEven(childId);
                if(childId > (tilesPerLine * row) - 1)
                {
                    row++;
                }
                if(IsEven(row))
                {
                    evenOrOdd = !evenOrOdd;
                }
                if(evenOrOdd)
                    child.SetAlpha(0.15);
                else
                    child.SetAlpha(0.05);
                child = child.GetSibling();
                childId++;
            }
        }
#endif
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), and IsEven().
Referenced by PluginDrawCheckerboard().
CursorHide()
void PluginBase::CursorHide () inline private
Definition at line 35 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnHide();
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnHide().
CursorShow()
void PluginBase::CursorShow () inline private
Definition at line 44 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnShow();
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnShow().
DeactivateModifier()
void PluginBase::DeactivateModifier (int id, PlayerBase player = NULL) inline private
Definition at line 672 of file plugindevelopersync.c.
    {
        if ( !player )
        {
            player = PlayerBase.Cast( GetDayZGame().GetPlayer() );
        }
        ModifiersManager mods_manager = player.GetModifiersManager();
        mods_manager.DeactivateModifier( Math.AbsInt( id ) );
    }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Decay()
void PluginBase::Decay () inline private
Definition at line 59 of file pluginobjectsinteractionmanager.c.
    {
        if ( m_LockedObjectsDecay.Count() > 0 )
        {
            for ( int i = 0; i < m_LockedObjectsDecay.Count(); i++ )
            {
                if ( m_LockedObjectsDecay.Get(i) >= TIME_TO_FORCED_UNLOCK )
                {
                    m_LockedObjects.Remove(i);
                    m_LockedObjectsDecay.Remove(i);
                }
                else
                {
                    m_LockedObjectsDecay.Get(i) += TICK_RATE;
                }
            }
        }
    }
References TICK_RATE.
DeleteKeyframe()
void PluginBase::DeleteKeyframe () inline private
Definition at line 68 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnKeyPress( null, 0, 0, KeyCode.KC_E );
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
DeleteSceneObject()
void PluginBase::DeleteSceneObject (SceneObject obj) inline private
Definition at line 1091 of file pluginscenemanager.c.
    {
        if ( obj != NULL )
        {
            if ( obj.GetObject() != GetGame().GetPlayer() )
            {
                obj.UnlinkAll();
                if ( GetSelectedSceneObject() != NULL && GetSelectedSceneObject() == obj )
                {
                    DeselectObject();
                }
                m_SceneData.DeleteSceneObject(obj);
            }
            else
            {
                SceneEditorMenuCmdPopup("You cant delete player!");
            }
        }
        EditorUpdate();
    }
References GetGame(), SceneObject::GetObject(), GetPlayer(), and SceneObject::UnlinkAll().
DeleteSelectedObject()
void PluginBase::DeleteSelectedObject () inline private
Definition at line 439 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( selected_obj != NULL )
        {
            if ( !selected_obj.IsPlayer() )
            {
                array<ref SceneObject> scene_objects = GetSceneObjects();
                for ( int i = 0; i < scene_objects.Count(); i++ )
                {
                    if ( AreSceneObjectsLinked(scene_objects.Get(i), selected_obj) )
                    {
                        UnlinkSceneObjects(scene_objects.Get(i), selected_obj);
                    }
                }
                m_SceneData.DeleteSceneObject(selected_obj);
                scene_objects.RemoveItem(selected_obj);
                DeselectObject();
            }
            else
            {
                SceneEditorMenuCmdPopup("You cant delete player!");
            }
        }
        EditorUpdate();
    }
References SceneObject::IsPlayer().
DeselectObject()
private void PluginBase::DeselectObject () inline private
Definition at line 1137 of file pluginscenemanager.c.
    {
        m_SelectedObject = NULL;
    }
References m_SelectedObject.
DestroyModuleWidgets()
void PluginBase::DestroyModuleWidgets () inline private
Definition at line 256 of file plugindayzinfecteddebug.c.
    {
        delete m_MainWnd;
    }
References m_MainWnd.
Referenced by ~PluginDayZInfectedDebug(), and ~PluginDayzPlayerDebug().
DetermineChanceToTransmit()
protected bool PluginBase::DetermineChanceToTransmit (int agent_id, float protection, int inject_type) inline private
Definition at line 382 of file plugintransmissionagents.c.
    {
        //Debug.Log("protection: "+protection.ToString());
        float prot = 1 - protection; //reverse the value (in config, the higher the value, the higher the protection: 0 - 1) so that we can easily interpolate between 0 and 1 by multiplication
        //Debug.Log("prot: "+prot.ToString(), "Agents");
        float transf;
        if( inject_type == InjectTypes.PLAYER_TO_ITEM )
        {
            transf = GetAgentTransferabilityOut(agent_id);
        }
        else if( inject_type == InjectTypes.ITEM_TO_PLAYER )
        {
            transf = GetAgentTransferabilityIn(agent_id);
        }
        else if( inject_type == InjectTypes.PLAYER_AIR_PLAYER )
        {
            transf = GetAgentTransferabilityAirOut(agent_id);
        }
        #ifdef DEVELOPER
        //Debug.Log("transf: "+transf.ToString(), "Agents");
        #endif
        //float result =  GetAgentInitialCount(agent_id) * prot * transf * dose_size;//final formula
        bool dice = Math.RandomFloat01() < (prot * transf);
        //result = Math.Ceil(result);
        return dice;
    }
References GetAgentTransferabilityAirOut(), GetAgentTransferabilityIn(), GetAgentTransferabilityOut(), and Math::RandomFloat01().
Referenced by InjectAgentsWithPlayer().
DirectAdminLogPrint()
void PluginBase::DirectAdminLogPrint (string str) inline private
Definition at line 355 of file pluginadminlog.c.
    {
        LogPrint(str);
    }
References LogPrint().
DisplayTendency()
void PluginBase::DisplayTendency (int key, int tendency, int status = 1) inline private
Definition at line 42 of file pluginplayerstatus.c.
    {
        if ( key )
        {
            // display icon
            int icon_index = 0;  // maybe we'll have several icons for different tendencies
            if ( m_NotifiersIcons.HasKey( key ) )
            {
                string icon_name = m_NotifiersIcons.Get( key ).Get( icon_index );
                Mission mission = GetGame().GetMission();
                if ( mission )
                {
                    Hud hud = mission.GetHud();
                    if ( hud )
                    {
                        hud.DisplayNotifier( key, tendency, status );
                    }
                }
            }
        }
    }
References Hud::DisplayNotifier(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
DrawDebugs()
void PluginBase::DrawDebugs () inline private
Definition at line 48 of file pluginuniversaltemperaturesourceclient.c.
    {
        for (int i = 0; i < m_UTemperatureSourceDebugs.Count(); i++)
        {
            UTemperatureSourceDebug utsd = m_UTemperatureSourceDebugs.Get(i);
            float fullRange = utsd.GetValue(1).ToFloat();
            float maxRange  = utsd.GetValue(2).ToFloat();
            float temp      = utsd.GetValue(3).ToFloat();
            vector sphPos   = utsd.GetValue(0).ToVector();
            int fullRangeColor = COLOR_RED_A;
            int maxRangeColor = COLOR_YELLOW_A;
            if (temp < 0)
            {
                fullRangeColor = COLOR_GREEN_A;
                maxRangeColor = COLOR_BLUE_A;
            }
            Debug.DrawCylinder(sphPos, fullRange, fullRange, fullRangeColor, ShapeFlags.ONCE|ShapeFlags.TRANSP);
            Debug.DrawCylinder(sphPos, maxRange, maxRange, maxRangeColor, ShapeFlags.ONCE|ShapeFlags.TRANSP);
            Debug.DrawArrow(m_Player.GetPosition(), sphPos, 1.0, 0xffffffff, ShapeFlags.ONCE|ShapeFlags.TRANSP);
        }
        ProcessUniversalTemperatureSources();
        if (m_UTemperatureSourceDebugs.Count() > 0)
        {
            DbgUI.Begin("Universal Temp Sources", 10, 300);
            DbgUI.Text(string.Format("Lookup radius: %1m (server-side)", PluginUniversalTemperatureSourceServer.LOOKUP_RADIUS));
            DbgUI.Text(string.Format("Count: %1", m_UTemperatureSourceDebugs.Count()));
            DbgUI.Text(string.Format("Avg. temp: %1 C", m_UTSAverageTemperature));
            DbgUI.End();
        }
    }
References DbgUI::Begin(), COLOR_BLUE_A, COLOR_GREEN_A, COLOR_RED_A, COLOR_YELLOW_A, Debug::DrawArrow(), Debug::DrawCylinder(), DbgUI::End(), m_Player, ProcessUniversalTemperatureSources(), and DbgUI::Text().
Referenced by OnUpdate().
EditorToggle()
void PluginBase::EditorToggle () inline private
Definition at line 368 of file pluginscenemanager.c.
    {
        //Log("EditorToggle");
        if ( GetGame().IsMultiplayer() )
        {
            return;
        }
        if ( IsOpened() )
        {
            // Close UI Scene Editor Menu
            GetGame().GetUIManager().Back();
        }
        else
        {
            // Open UI Scene Editor Menu
            GetGame().GetUIManager().EnterScriptedMenu(MENU_SCENE_EDITOR, NULL);
            EditorUpdate();
        }
    }
References UIManager::Back(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), IsOpened(), and MENU_SCENE_EDITOR.
EditorUpdate()
protected void PluginBase::EditorUpdate () inline private
Definition at line 1145 of file pluginscenemanager.c.
    {
        if ( GetGame().IsMultiplayer() )
        {
            return;
        }
        array<ref SceneObject> objects = GetSceneObjects();
        if( !objects )
            return;
        for ( int i = 0; i < objects.Count(); ++i )
        {
            SceneObject obj = objects.Get(i);
            array<SceneObject> linked_scene_objects = obj.GetLinkedSceneObjects();
            int j;
            if ( IsOpened() )
            {
                obj.EditorShapeAdd();
                if ( GetSelectedSceneObject() && GetSelectedSceneObject() == obj )
                {
                    if ( GetDrawSelection() )
                    {
                        obj.EditorShapeSelect();
                    }
                }
                else
                {
                    obj.EditorShapeDeselect();
                }
                for ( j = 0; j < linked_scene_objects.Count(); j++ )
                {
                    obj.EditorLineAdd( linked_scene_objects.Get(j) );
                }
            }
            else
            {
                obj.EditorShapeRemove();
                if (linked_scene_objects)
                {
                    for ( j = 0; j < linked_scene_objects.Count(); j++ )
                    {
                        obj.EditorLineRemove( linked_scene_objects.Get(j) );
                    }
                }
            }
        }
        SceneEditorMenuCmdRefresh();
    }
References SceneObject::EditorLineAdd(), SceneObject::EditorLineRemove(), SceneObject::EditorShapeAdd(), SceneObject::EditorShapeDeselect(), SceneObject::EditorShapeRemove(), SceneObject::EditorShapeSelect(), GetGame(), SceneObject::GetLinkedSceneObjects(), and IsOpened().
EditorUpdateRuler()
private void PluginBase::EditorUpdateRuler () inline private
Definition at line 1242 of file pluginscenemanager.c.
    {
        RulerClearVisuals();
        for ( int i = 0; i < m_RulerPoints.Count(); ++i )
        {
            vector pos1 = m_RulerPoints.Get(i);
            m_RulerSpheres.Insert(Debug.DrawSphere(pos1, 0.1));
            if ( i < m_RulerPoints.Count() - 1 )
            {
                vector pos2 = m_RulerPoints.Get(i + 1);
                m_RulerLines.Insert(Debug.DrawLine(pos1, pos2));
            }
        }
    }
References Debug::DrawLine(), and Debug::DrawSphere().
EnableUpdate()
void PluginBase::EnableUpdate (bool enable, int type, PlayerBase player) inline private
Definition at line 76 of file plugindevelopersync.c.
    {
        //set update by type
        if ( !IsPlayerRegistered(player))
            RegisterPlayer( player );
        switch ( type )
        {
            case ERPCs.DEV_STATS_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.STATS, enable);
                break;
            }
            case ERPCs.DEV_LEVELS_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.LEVELS, enable);
                break;
            }
            case ERPCs.DEV_MODS_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.MODS, enable);
                break;
            }
            case ERPCs.DEV_AGENTS_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.AGENTS, enable);
                break;
            }
            case ERPCs.DEV_STOMACH_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.STOMACH, enable);
                break;
            }
            case ERPCs.DEV_TEMP_UPDATE:
            {
                SetSystemInBitmask(player, PDS_SYSTEMS.TEMPERATURE, enable);
                break;
            }
        }
        //remove players with empty mask
        for (int i = 0; i < m_RegisteredPlayers.Count(); i++)
        {
            if (m_RegisteredPlayers.GetElement(i).m_Bitmask == 0)
            {
                m_RegisteredPlayers.RemoveElement(i);
                i = 0;
            }
        }
        //start/stop the tick based on existence/absence of players registered
        if ( m_UpdateTimer )
        {
            if ( m_RegisteredPlayers.Count() == 0)
            {
                m_UpdateTimer.Stop();
            }
            else if (!m_UpdateTimer.IsRunning())
            {
                m_UpdateTimer.Run( 1, this, "Update", NULL, true );
            }
        }
    }
References IsPlayerRegistered(), m_UpdateTimer, RegisterPlayer(), and SetSystemInBitmask().
Referenced by OnRPC(), and OnRPCTemp().
EnableWidgets()
void PluginBase::EnableWidgets (bool enable) inline private
Definition at line 145 of file pluginuniversaltemperaturesourceclient.c.
    {
        for (int i = 0; i < MAX_SIMULTANEOUS_UTS; i++)
        {
            m_RootWidget[i].Show(enable);
        }
    }
References m_RootWidget, and MAX_SIMULTANEOUS_UTS.
Referenced by RequestPlayerInfo(), and RequestUniversalTemperatureSources().
Event_OnClick()
void PluginBase::Event_OnClick () inline private
Definition at line 116 of file pluginscenemanager.c.
    {
        if ( !IsMouseInScene() || !m_IsOpen )
        {
            return;
        }
        // Direction Vector from current active Camera
        vector dir = GetGame().GetPointerDirection();
        // Raycast from
        vector from = FreeDebugCamera.GetInstance().GetPosition();
        // Raycast to
        vector to = from + ( dir * 10000 );
        // Raycast out parameter
        vector contact_pos;
        vector contact_dir;
        int contact_component;
        set<Object> objects = new set<Object>;
        bool selected = false;
        if ( DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, objects) )
        {
            for ( int i = 0; i < objects.Count(); ++i )
            {
                Object obj = objects.Get(i);
                if ( obj.IsInherited( EntityAI ) )
                {
                    SceneObject sc_object = SceneObject.Cast( m_SceneData.GetSceneObjectByEntityAI(EntityAI.Cast( obj ) ) );
                    if ( sc_object == NULL )
                    {
                        //sc_object = m_SceneData.AddObject(obj);
                        return;
                    }
                    SelectObject( sc_object );
                    selected = true;
                    break;
                }
            }
        }
        if ( !selected )
        {
            DeselectObject();
            //  Ruler
            if ( IsRulerActivated() && GetSelectedSceneObject() == NULL )
            {
                RulerAddPoint();
            }
        }
        EditorUpdate();
    }
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
Event_OnClickMiddle()
void PluginBase::Event_OnClickMiddle () inline private
Definition at line 178 of file pluginscenemanager.c.
    {
        if ( !IsMouseInScene() || !m_IsOpen )
        {
            return;
        }
        if ( GetSelectedSceneObject() != NULL )
        {
            // Direction Vector from current active Camera
            vector dir = GetGame().GetPointerDirection();
            // Raycast from
            vector from = FreeDebugCamera.GetInstance().GetPosition();
            // Raycast to
            vector to = from + ( dir * 10000 );
            // Raycast out parameter
            vector contact_pos;
            vector contact_dir;
            int contact_component;
            set<Object> objects = new set<Object>;
            bool selected = false;
            if ( DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, objects) )
            {
                for ( int i = 0; i < objects.Count(); ++i )
                {
                    Object obj = objects.Get(i);
                    if ( obj.IsInherited( EntityAI ) )
                    {
                        EntityAI eai = EntityAI.Cast( obj );
                        SceneObject scene_object = m_SceneData.GetSceneObjectByEntityAI(eai);
                        if ( !scene_object.IsPlayer() )
{
                            if ( scene_object != NULL && scene_object != GetSelectedSceneObject() )
{
                                if ( !AreSceneObjectsLinked(GetSelectedSceneObject(), scene_object) )
{
                                    LinkSceneObjects( GetSelectedSceneObject(), scene_object );
                                }
                                else
{
                                    UnlinkSceneObjects( GetSelectedSceneObject(), scene_object );
                                }
                            }
                        }
                        else
{
                            SceneEditorMenuCmdPopup("I am sorry. You cant create link on player!");
                        }
                    }
                }
            }
        }
        EditorUpdate();
    }
References GetGame(), CGame::GetPointerDirection(), SceneObject::IsPlayer(), and DayZPhysics::RaycastRV().
Event_OnDoubleClick()
SceneObject PluginBase::Event_OnDoubleClick () inline private
Definition at line 276 of file pluginscenemanager.c.
    {
        if ( !IsMouseInScene() || !m_IsOpen || m_ClassBrowserSelected == "" )
        {
            return null;
        }
        // Direction Vector from current active Camera
        vector dir = GetGame().GetPointerDirection();
        // Raycast from
        vector from = FreeDebugCamera.GetInstance().GetPosition();
        // Raycast to
        vector to = from + ( dir * 10000 );
        // Raycast out parameter
        vector contact_pos;
        vector contact_dir;
        int contact_component;
        if ( DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component) )
        {
            SceneObject obj = m_SceneData.CreateSceneObject(m_ClassBrowserSelected, contact_pos);
            if ( obj != NULL )
            {
                SelectObject(obj);
                return obj;
            }
        }
        return NULL;
    }
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
Event_OnDrag()
void PluginBase::Event_OnDrag () inline private
Definition at line 241 of file pluginscenemanager.c.
    {
        if ( !IsMouseInScene() || !m_IsOpen )
        {
            return;
        }
        if ( GetSelectedSceneObject() != NULL )
        {
            // Direction Vector from current active Camera
            vector dir = GetGame().GetPointerDirection();
            // Raycast from
            vector from = FreeDebugCamera.GetInstance().GetPosition();
            // Raycast to
            vector to = from + ( dir * 10000 );
            // Raycast out parameter
            vector contact_pos;
            vector contact_dir;
            int contact_component;
            //Raycast(vector begPos, vector endPos, out vector contactPos, out vector contactDir, out int contactComponent, out set<Object> results = NULL, Object with = NULL, Object ignore = NULL,  bool sorted = false,  bool ground_only = false,  int iType = ObjIntersectView, float radius = 0.0);
            if ( DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component, NULL, NULL, NULL, false, true) )
            {
                GetSelectedSceneObject().SetPosition(contact_pos);
            }
            EditorUpdate();
        }
    }
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
ExecuteEnforceScript()
void PluginBase::ExecuteEnforceScript (int index, SceneObject scene_object, string script) inline private
Definition at line 898 of file pluginscenemanager.c.
    {
        if ( script != "" )
        {
            string cls = scene_object.GetObject().ClassName();
            string wrapped_script = "void scMngMain() \n{\n PluginSceneManager se = GetPlugin(Type(\"PluginSceneManager\")); \n SceneObject this_obj = se.GetSceneObjectByIndex(" + index.ToString() + "); \n " + cls + " this_eai = this_obj.GetObject(); \n " + script + "\n}\n";
            GetGame().ExecuteEnforceScript(wrapped_script, "scMngMain");
        }
    }
References CGame::ExecuteEnforceScript(), GetGame(), and SceneObject::GetObject().
ExecuteInitScripts()
void PluginBase::ExecuteInitScripts () inline private
Definition at line 355 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        for ( int i = 0; i < scene_objects.Count(); i++ )
        {
            SceneObject scene_object = scene_objects.Get(i);
            ExecuteEnforceScript( i, scene_object, scene_object.GetInitScript() );
        }
    }
References SceneObject::GetInitScript().
FileDelete()
static bool PluginBase::FileDelete (string file) inline static private
Definition at line 8 of file pluginfilehandler.c.
    {
        return DeleteFile(file);
    }
References DeleteFile().
FileDuplicate()
static bool PluginBase::FileDuplicate (string source_name, string dest_name) inline static private
Definition at line 3 of file pluginfilehandler.c.
    {
        return CopyFile(source_name, dest_name);
    }
References CopyFile().
FileRename()
static void PluginBase::FileRename (string source_name, string dest_name) inline static private
Definition at line 13 of file pluginfilehandler.c.
    {
        FileDuplicate(source_name, dest_name);
        FileDelete(source_name);
    }
FreeCameraControlDisable()
void PluginBase::FreeCameraControlDisable () inline private
Definition at line 424 of file pluginscenemanager.c.
    {
        // Disable Camera control
        GetGame().GetInput().ChangeGameFocus(1);
        // Enable Cursor
        GetGame().GetUIManager().ShowUICursor(true);
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnShow();
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::OnShow(), and UIManager::ShowUICursor().
FreeCameraControlEnable()
void PluginBase::FreeCameraControlEnable () inline private
Definition at line 409 of file pluginscenemanager.c.
    {
        // Enable Camera control
        GetGame().GetInput().ChangeGameFocus(-1);
        // Disable Cursor
        GetGame().GetUIManager().ShowUICursor(false);
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnHide();
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), UIManager::GetMenu(), CGame::GetUIManager(), UIScriptedMenu::OnHide(), and UIManager::ShowUICursor().
GatherPlayerInfo()
void PluginBase::GatherPlayerInfo () inline private
Definition at line 40 of file pluginremoteplayerdebugserver.c.
    {
        array<Man> players = new array<Man>;
        GetGame().GetPlayers(players);
        m_PlayerDebugStats.Clear();
        for(int i = 0; i < players.Count(); i++)
        {
            PlayerBase player = PlayerBase.Cast(players.Get(i));
            RemotePlayerStatDebug rpd = new RemotePlayerStatDebug(player);
            m_PlayerDebugStats.Insert(rpd);
        }
    }
References GetGame(), CGame::GetPlayers(), m_PlayerDebugStats, and RemotePlayerStatDebug().
Referenced by SendDebug().
GatherTemperatureSources()
void PluginBase::GatherTemperatureSources (PlayerBase player) inline private
Definition at line 31 of file pluginuniversaltemperaturesourceserver.c.
    {
        m_UTemperatureSourceDebugs.Clear();
        if (!player)
        {
            return;
        }
        vector playerPos                = player.GetPosition();
        array<Object> nearestObjects    = new array<Object>;
        GetGame().GetObjectsAtPosition(playerPos, LOOKUP_RADIUS, nearestObjects, null);
        UTemperatureSource uts;
        UTemperatureSourceDebug utsd;
        for (int i = 0; i < nearestObjects.Count(); i++)
        {
            EntityAI ent = EntityAI.Cast(nearestObjects.Get(i));
            if (ent && ent.IsUniversalTemperatureSource() && ent != player)
            {
                uts = ent.GetUniversalTemperatureSource();
                utsd = new UTemperatureSourceDebug();
                utsd.Add("position", uts.GetPosition().ToString(false));
                utsd.Add("fullrange", uts.GetFullRange().ToString());
                utsd.Add("maxrange", uts.GetMaxRange().ToString());
                utsd.Add("temperature", uts.GetTemperature().ToString());
                utsd.Add("temperatureraw", uts.GetTemperatureRaw().ToString());
                utsd.Commit();
                m_UTemperatureSourceDebugs.Insert(utsd);
            }
        }
        if (player.GetItemInHands() && player.GetItemInHands().IsUniversalTemperatureSource())
        {
            uts = player.GetItemInHands().GetUniversalTemperatureSource();
            utsd = new UTemperatureSourceDebug();
            utsd.Add("position", uts.GetPosition().ToString(false));
            utsd.Add("fullrange", uts.GetFullRange().ToString());
            utsd.Add("maxrange", uts.GetMaxRange().ToString());
            utsd.Add("temperature", uts.GetTemperature().ToString());
            utsd.Add("temperatureraw", uts.GetTemperatureRaw().ToString());
            utsd.Commit();
            m_UTemperatureSourceDebugs.Insert(utsd);
        }
    }
References GetGame(), and CGame::GetObjectsAtPosition().
Referenced by SendDebug().
GetAgentAntiboticsResistance()
float PluginBase::GetAgentAntiboticsResistance (int agent_id) inline private
Definition at line 113 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return 0;
        return m_AgentList.Get(agent_id).GetAntiboticsResistance();
    }
GetAgentAntiboticsResistanceEx()
float PluginBase::GetAgentAntiboticsResistanceEx (int agent_id, PlayerBase player) inline private
Definition at line 120 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return 0;
        return m_AgentList.Get(agent_id).GetAntibioticsResistanceEx(player);
    }
GetAgentDieOffSpeedEx()
float PluginBase::GetAgentDieOffSpeedEx (int agent_id, PlayerBase player) inline private
Definition at line 92 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return true;
        return m_AgentList.Get(agent_id).GetDieOffSpeedEx(player);
    }
GetAgentDigestibility()
float PluginBase::GetAgentDigestibility (int agent_id) inline private
Definition at line 151 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) )
            return 0;
        return m_AgentList.Get(agent_id).GetDigestibility();
    }
GetAgentInvasibility()
float PluginBase::GetAgentInvasibility (int agent_id) inline private
Definition at line 143 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) )
            return 0;
        return m_AgentList.Get(agent_id).GetInvasibility();
    }
GetAgentInvasibilityEx()
float PluginBase::GetAgentInvasibilityEx (int agent_id, PlayerBase player) inline private
Definition at line 104 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return true;
        return m_AgentList.Get(agent_id).GetInvasibilityEx(player);
    }
GetAgentList()
map< int, ref AgentBase > PluginBase::GetAgentList () inline private
Definition at line 46 of file plugintransmissionagents.c.
    {
        return  m_AgentList;
    }
References m_AgentList.
GetAgentMaxCount()
static int PluginBase::GetAgentMaxCount (int agent_id) inline static private
Definition at line 172 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return 0;
        return m_AgentList.Get(agent_id).GetMaxCount();
    }
GetAgentPotencyEx()
EStatLevels PluginBase::GetAgentPotencyEx (int agent_id, PlayerBase player) inline private
Definition at line 98 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return true;
        return m_AgentList.Get(agent_id).GetPotencyEx(player);
    }
GetAgentTransferabilityAirOut()
protected float PluginBase::GetAgentTransferabilityAirOut (int agent_id) inline private
Definition at line 132 of file plugintransmissionagents.c.
    {
        if(!m_AgentList.Get(agent_id)) return 0;
        return m_AgentList.Get(agent_id).GetTransferabilityAirOut();
    }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityIn()
protected float PluginBase::GetAgentTransferabilityIn (int agent_id) inline private
Definition at line 78 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return 0;
        return m_AgentList.Get(agent_id).GetTransferabilityIn();
    }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetAgentTransferabilityOut()
protected float PluginBase::GetAgentTransferabilityOut (int agent_id) inline private
Definition at line 126 of file plugintransmissionagents.c.
    {
        if(!m_AgentList.Get(agent_id)) return 0;
        return m_AgentList.Get(agent_id).GetTransferabilityOut();
    }
Referenced by CalculateAgentsToTransmit(), and DetermineChanceToTransmit().
GetBaseClassPath()
string PluginBase::GetBaseClassPath (string config_class_path, string class_path, string config_class) inline private
Definition at line 46 of file pluginconfigviewer.c.
    {
        if ( class_path == "" )
        {
            return "";
        }
        int start = config_class_path.Length();
        int count = class_path.Length() - start;
        string class_path_without_config_class = GetOnlyChildPath( config_class_path, class_path );
        ref TStringArray full_path = new TStringArray;
        GetGame().ConfigGetFullPath( config_class_path, full_path );
        if ( full_path.Count() > 1 && class_path_without_config_class != "" )
        {
            return GetBaseClassPathRecursive( config_class + " " + full_path.Get(1), class_path_without_config_class, config_class );
        }
        else
        {
            return "";
        }
    }
References CGame::ConfigGetFullPath(), string::Get(), GetBaseClassPathRecursive(), GetGame(), GetOnlyChildPath(), and string::Length().
Referenced by GetConfigRecursive().
GetBaseClassPathCombined()
string PluginBase::GetBaseClassPathCombined (string child_path, string base_class) inline private
Definition at line 70 of file pluginconfigviewer.c.
    {
        int current = -1;
        int last = 0;
        while ( true )
        {
            current = child_path.IndexOfFrom(last, " " );
            if ( current > -1 )
            {
                last = current+1;
            }
            else
            {
                break;
            }
        }
        string result = child_path.Substring(0, last ) + base_class;
        return result;
    }
References string::IndexOfFrom(), and string::Substring().
Referenced by GetConfigRecursive().
GetBaseClassPathRecursive()
string PluginBase::GetBaseClassPathRecursive (string config_class_path, string class_path, string config_class) inline private
Definition at line 92 of file pluginconfigviewer.c.
    {
        if ( ContainsFirstClass(config_class_path, class_path) )
        {
            return config_class_path + " " + class_path;
        }
        else
        {
            ref TStringArray full_path = new TStringArray;
            GetGame().ConfigGetFullPath( config_class_path, full_path );
            if ( full_path.Count() > 1 )
            {
                return GetBaseClassPathRecursive( config_class + " " + full_path.Get(1), class_path, config_class );
            }
            else
            {
                return "";
            }
        }
    }
References CGame::ConfigGetFullPath(), ContainsFirstClass(), string::Get(), GetBaseClassPathRecursive(), and GetGame().
Referenced by GetBaseClassPath(), and GetBaseClassPathRecursive().
GetConfig()
TStringArray PluginBase::GetConfig (string class_path, string filter_char) inline private
Definition at line 320 of file pluginconfigviewer.c.
    {
        int i;
        TStringArray filtered = new TStringArray;
        if ( class_path != "" )
        {
            PluginDeveloper module_dev = PluginDeveloper.Cast( GetPlugin( PluginDeveloper ) );
            TStringArray path_nodes = new TStringArray;
            class_path.Split( " ", path_nodes );
            if ( path_nodes.Count() >= 3 )
            {
                string c_class_path = path_nodes.Get(0) + " " + path_nodes.Get(1) + " " + path_nodes.Get(2);
                array<string> overridden = new array<string>;
                string config_class = path_nodes.Get( 1 );
                string class_name = path_nodes.Get( 2 );
                TStringArray result = GetConfigRecursive( c_class_path, class_name, c_class_path, config_class, overridden );
                TStringArray nested_start = new TStringArray;
                TStringArray nested_end = new TStringArray;
                TStringArray nested_inherited_start = new TStringArray;
                TStringArray nested_inherited_end = new TStringArray;
                string tabs = MakeTabs( 1 );
                string tabs_inherited = MakeTabs( 1, true );
                string check_tabs = MakeTabs( path_nodes.Count() - 1, true );
                nested_start.Insert( ":!" );
                nested_end.Insert( ":#" );
                nested_inherited_start.Insert( ":!" );
                nested_inherited_end.Insert( ":#" );
                string last_node = filter_char + MakeTabs( nested_start.Count() ) + "!";
                if ( path_nodes.Count() == 3 )
                {
                    last_node = filter_char + MakeTabs( 1 ) + "!";
                }
                else
                {
                    for ( i = 1; i < path_nodes.Count() - 2; i++ )
                    {
                        tabs = MakeTabs( i );
                        tabs_inherited = MakeTabs( i, true );
                        string path_node = path_nodes.Get(i+2);
                        path_node.ToLower(  );
                        nested_start.Insert( ":" + tabs + "!" + path_node );
                        nested_end.Insert( ":" + tabs + "#" + path_node );
                        nested_inherited_start.Insert( ":" + tabs_inherited + "!" + path_node );
                        nested_inherited_end.Insert( ":" + tabs_inherited + "#" + path_node );
                    }
                    last_node = filter_char + MakeTabs( i ) + "!";
                }
                int current_nest = 0;
                for ( i = 0; i < result.Count(); i++ )
                {
                    string current = result.Get( i );
                    string current_lower = current;
                    current_lower.ToLower( );
                    int len_current = current.Length();
                    if ( current_nest < nested_start.Count() )
                    {
                        int len_start = nested_start.Get(current_nest).Length();
                        if ( len_current >= len_start )
{
                            string prefix_start = current_lower;
                            if ( current_nest == 0 )
{
                                prefix_start = current_lower.Substring( 0, len_start );
                            }
                            if ( prefix_start == nested_start.Get(current_nest) || prefix_start == nested_inherited_start.Get(current_nest) )
{
                                current_nest++;
                                continue;
                            }
                        }
                    }
                    if ( current_nest >= 1 )
                    {
                        int len_end = nested_end.Get(current_nest - 1).Length();
                        if ( len_current >= len_end )
{
                            string prefix_end = current_lower;
                            if ( current_nest == 0 )
{
                                prefix_start = current_lower.Substring( 0, len_start );
                            }
                            if ( prefix_end == nested_end.Get(current_nest - 1) || prefix_end == nested_inherited_end.Get(current_nest - 1) )
{
                                current_nest--;
                            }
                        }
                    }
                    if ( current_nest == nested_start.Count() )
                    {
                        string first_char = current.Substring( 0, 1 );
                        if ( first_char == filter_char )
{
                            int bang_pos = current.IndexOf( "!" );
                            if ( bang_pos > -1 )
{
                                int len_last_node = last_node.Length();
                                if ( len_current >= len_last_node )
{
                                    string prefix_current = current_lower.Substring( 0, len_last_node );
                                    if ( last_node == prefix_current )
{
                                        filtered.Insert( current.Substring(bang_pos + 1, current.Length() - (bang_pos + 1)) );
                                    }
                                }
                            }
                        }
                    }
                }
                TStringArray without_duplications = new TStringArray;
                map<string, string> lowered = new map<string, string>;
                for ( i = 0; i < filtered.Count(); i++ )
                {
                    string c = filtered.Get( i );
                    string lower_c = c;
                    lower_c.ToLower();
                    if ( without_duplications.Find(lower_c) < 0 )
                    {
                        without_duplications.Insert( lower_c );
                        if ( lower_c != c )
{
                            lowered.Set( lower_c, c );
                        }
                    }
                }
                module_dev.SortStringArray( without_duplications );
                for ( i = 0; i < without_duplications.Count(); i++ )
                {
                    string cc = without_duplications.Get( i );
                    if ( lowered.Contains(cc) )
                    {
                        cc = lowered.Get( cc );
                    }
                    int tilda_index = cc.IndexOf( "~" );
                    if ( tilda_index > -1 )
                    {
                        string spaces = "    ";
                        if ( cc.IndexOf( "~}" ) > -1 )
{
                            spaces = "";
                        }
                        cc = spaces + cc.Substring(tilda_index + 1, cc.Length() - (tilda_index + 1) );
                    }
                    without_duplications.Set( i, cc );
                }
                return without_duplications;
            }
            else if ( filter_char == ":" )
            {
                int cnt_config = GetGame().ConfigGetChildrenCount( class_path );
                for ( i = 0; i < cnt_config; i++ )
                {
                    string config_name = "";
                    GetGame().ConfigGetChildName( class_path, i, config_name );
                    filtered.Insert( config_name );
                }
                module_dev.SortStringArray( filtered );
            }
        }
        else if ( filter_char == ":" )
        {
            filtered.Insert( "configfile" );
            filtered.Insert( "missionconfigfile" );
        }
        return filtered;
    }
References class_name, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), string::Get(), GetConfigRecursive(), GetGame(), GetPlugin(), string::IndexOf(), string::Length(), MakeTabs(), string::Split(), string::Substring(), and string::ToLower().
Referenced by GetConfigHierarchy(), and GetConfigVariables().
GetConfigHierarchy()
TStringArray PluginBase::GetConfigHierarchy (string class_path) inline private
Definition at line 533 of file pluginconfigviewer.c.
    {
        return GetConfig( class_path, ":" );
    }
References GetConfig().
GetConfigRecursive()
TStringArray PluginBase::GetConfigRecursive (string path, string name, string config_class_path, string config_class, local array< string > overridden, int depth = 0, local bool check_base_class_of_class = false) inline private
Definition at line 153 of file pluginconfigviewer.c.
    {
        string tabs = MakeTabs( depth + 1 );
        string child_path = path;
        int count = GetGame().ConfigGetChildrenCount( child_path );
        int i = 0;
        bool name_printed = false;
        TStringArray result = new TStringArray;
        for ( i = 0; i < count; i++ )
        {
            string child_name = "";
            GetGame().ConfigGetChildName( child_path, i, child_name );
            string c_child_path = child_path + " " + child_name;
            string child_name_lower = child_name;
            child_name_lower.ToLower();
            if ( overridden.Find(child_name_lower) == -1 )
            {
                if ( !name_printed )
                {
                    result.Insert( ":" + MakeTabs(depth, check_base_class_of_class) + "!" + name );
                    name_printed = true;
                }
                overridden.Insert( child_name_lower );
                int type = GetGame().ConfigGetType( c_child_path );
                if ( type != CT_CLASS )
                {
                    if ( type != CT_ARRAY )
                    {
                        result.Insert( "-" + tabs + "!" + child_name + " = " + GetGame().ConfigGetTextOut(c_child_path) );
                    }
                    else
                    {
                        result.Insert( "-" + tabs + "!" + child_name + "[] = {" );
                        TStringArray strs = new TStringArray;
                        GetGame().ConfigGetTextArray( c_child_path, strs );
                        string tabs_array = MakeTabs( depth + 2 );
                        int j;
                        for ( j = 0; j < strs.Count(); j++ )
{
                            result.Insert( "-" + tabs + "!" + child_name + "[]" + j.ToStringLen(6) + "~" + strs.Get(j) + "," );
                        }
                        result.Insert( "-" + tabs + "!" + child_name + "[]" + j.ToStringLen(6) + "~}" );
                    }
                }
                else
                {
                    array<string> overridden_sub = new array<string>;
                    if ( GetGame().ConfigGetChildrenCount(c_child_path) > 0 )
                    {
                        TStringArray config1 = GetConfigRecursive( c_child_path, child_name, config_class_path, config_class, overridden_sub, depth + 1 );
                        result.InsertAll( config1 );
                    }
                    else
                    {
                        result.Insert( ":" + tabs + "!" + child_name );
                    }
                    string cc_child_path = c_child_path;
                    string c_config_class_path = config_class_path;
                    string c_child_name = child_name;
                    int cc = 0;
                    while ( true )
                    {
                        string base_class = "";
                        GetGame().ConfigGetBaseName( cc_child_path, base_class );
                        int start = c_config_class_path.Length() + 1;
                        int len = cc_child_path.Length();
                        len -= c_config_class_path.Length() + c_child_name.Length();
                        len -= 2;
                        if ( base_class != "" )
{
                            string only_child_path = "";
                            if ( len < 0 )
{
                                only_child_path = base_class;
                            }
                            else
{
                                only_child_path = cc_child_path.Substring( start, len ) + " " + base_class;
                            }
                            string c_base_child_path = GetBaseClassPathCombined( cc_child_path, base_class );
                            string base_class_path = GetBaseClassPath( c_config_class_path, c_base_child_path, config_class );
                            if ( base_class_path != "" )
{
                                TStringArray config2 = GetConfigRecursive( base_class_path, base_class, base_class_path, config_class, overridden_sub, depth + 1, true );
                                result.InsertAll( config2 );
                            }
                            else
{
                                TStringArray config3 = GetConfigRecursive( base_class, base_class, base_class, config_class, overridden_sub, depth + 1, true );
                                result.InsertAll( config3 );
                                break;
                            }
                            cc_child_path = base_class_path;
                            c_child_name = base_class;
                            c_config_class_path = cc_child_path.Substring( 0, cc_child_path.Length() - only_child_path.Length() - 1);
                        }
                        else
{
                            break;
                        }
                    }
                }
            }
        }
        if ( name_printed )
        {
            result.Insert( ":" + MakeTabs(depth, check_base_class_of_class) + "#" + name );
        }
        if ( !check_base_class_of_class )
        {
            TStringArray full_path = new TStringArray;
            GetGame().ConfigGetFullPath( child_path, full_path );
            if ( full_path.Count() > 1 )
            {
                TStringArray config4 = GetConfigRecursive( config_class + " " + full_path.Get(1), full_path.Get(1), config_class + " " + full_path.Get(1), config_class, overridden, depth );
                result.InsertAll( config4 );
            }
        }
        else
        {
            string class_base_class = "";
            GetGame().ConfigGetBaseName( child_path, class_base_class );
            if ( class_base_class != "" )
            {
                string base_child_path = GetBaseClassPathCombined( child_path, class_base_class );
                string cc_base_child_path = GetBaseClassPath( config_class_path, base_child_path, config_class );
                if ( cc_base_child_path != "" )
                {
                    TStringArray config5 = GetConfigRecursive( cc_base_child_path, class_base_class, cc_base_child_path, config_class, overridden, depth, true );
                    result.InsertAll( config5 );
                }
                else
                {
                    TStringArray config6 = GetConfigRecursive( class_base_class, class_base_class, class_base_class, config_class, overridden, depth, true );
                    result.InsertAll( config6 );
                }
            }
        }
        return result;
    }
References CGame::ConfigGetBaseName(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFullPath(), CGame::ConfigGetTextArray(), CGame::ConfigGetType(), GetBaseClassPath(), GetBaseClassPathCombined(), GetConfigRecursive(), GetGame(), string::Length(), MakeTabs(), name, path, string::Substring(), and string::ToLower().
Referenced by GetConfig(), and GetConfigRecursive().
GetConfigVariables()
TStringArray PluginBase::GetConfigVariables (string class_path) inline private
Definition at line 528 of file pluginconfigviewer.c.
    {
        return GetConfig( class_path, "-" );
    }
References GetConfig().
GetDieOffSpeed()
float PluginBase::GetDieOffSpeed (int agent_id) inline private
Definition at line 158 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) )
            return 0;
        return m_AgentList.Get(agent_id).GetDieOffSpeed();
    }
GetDrawSelection()
bool PluginBase::GetDrawSelection () inline private
Definition at line 714 of file pluginscenemanager.c.
    {
        return m_ModuleConfigDebugProfile.GetSceneEditorDrawSelection();
    }
GetFileContent()
TStringArray PluginBase::GetFileContent () inline private
Definition at line 140 of file pluginfilehandler.c.
    {
        return m_FileContent;
    }
GetFileName()
string PluginBase::GetFileName () inline private
Definition at line 42 of file pluginfilehandler.c.
    {
        return string.Empty;
    }
References string::Empty.
GetHitMessage()
string PluginBase::GetHitMessage (TotalDamageResult damageResult, int component, string zone, string ammo) inline private
Definition at line 98 of file pluginadminlog.c.
    {
        if ( damageResult )
        {
            float dmg = damageResult.GetHighestDamage("Health");
            return " into " + zone + "(" + component.ToString() + ") for " + dmg.ToString() + " damage (" + ammo + ")";
        }
        else                // block
        {
            return " into Block" + "(" + component.ToString() + ") for 0 damage ";
        }
    }
References component, TotalDamageResult::GetHighestDamage(), and float::ToString().
Referenced by PlayerHitBy().
GetID()
int PluginBase::GetID (string name) inline private
Definition at line 32 of file pluginvariables.c.
    {
        return m_Variables.GetKeyByValue(name);
    }
References name.
GetInstance() [1/3]
static PluginCameraTools PluginBase::GetInstance () inline static private
Definition at line 11 of file plugincameratools.c.
    {
        return m_Instance;
    }
References m_Instance.
GetInstance() [2/3]
static PluginDeveloper PluginBase::GetInstance () inline static private
Definition at line 12 of file plugindeveloper.c.
    {
        return PluginDeveloper.Cast( GetPlugin( PluginDeveloper ) );
    }
References GetPlugin().
GetInstance() [3/3]
static PluginSceneManager PluginBase::GetInstance () inline static private
Definition at line 38 of file pluginscenemanager.c.
    {
        return PluginSceneManager.Cast( GetPlugin( PluginSceneManager ) );
    }
References GetPlugin().
GetKeyBindings()
array< ref KeyBinding > PluginBase::GetKeyBindings () inline private
Definition at line 263 of file pluginkeybinding.c.
    {
        return m_KeyBindings;
    }
GetKitRepairCost()
private float PluginBase::GetKitRepairCost (ItemBase repair_kit, Object item) inline private
Definition at line 152 of file pluginrepairing.c.
    {
        ref array<int> repair_kit_types = new array<int>;
        ref array<float> repair_kit_costs = new array<float>;
        item.ConfigGetIntArray( "repairableWithKits", repair_kit_types );
        item.ConfigGetFloatArray( "repairCosts", repair_kit_costs );
        int eligible_kit;
        int kit_in_hands = repair_kit.ConfigGetInt( "repairKitType" );
        for ( int i = 0; i < repair_kit_types.Count(); i++ )
        {
            eligible_kit = repair_kit_types.Get(i);
            if ( eligible_kit == kit_in_hands )
            {
                float repair_cost = repair_kit_costs.Get(i);
            }
        }
        return repair_cost;
    }
Referenced by CalculateHealth().
GetLoadedScene()
SceneData PluginBase::GetLoadedScene () inline private
Definition at line 977 of file pluginscenemanager.c.
    {
        return m_SceneData;
    }
GetLoadPlayerPos()
bool PluginBase::GetLoadPlayerPos () inline private
Definition at line 730 of file pluginscenemanager.c.
    {
        return m_ModuleConfigDebugProfile.GetSceneEditorLoadPlayerPos();
    }
GetModuleName()
string PluginBase::GetModuleName () inline private
Definition at line 28 of file pluginbase.c.
    {
        return ClassName();
    }
Referenced by GetModuleType(), and Log().
GetModuleType()
PluginBase::GetModuleType () inline private
Definition at line 33 of file pluginbase.c.
    {
        return GetModuleName().ToType();
    }
References GetModuleName(), and string::ToType().
GetMouseBindings()
array< ref MouseBinding > PluginBase::GetMouseBindings () inline private
Definition at line 271 of file pluginkeybinding.c.
    {
        return m_MouseBindings;
    }
GetMouseButtonInfo()
protected MouseButtonInfo PluginBase::GetMouseButtonInfo (int button) inline private
Definition at line 356 of file pluginkeybinding.c.
    {
        for ( int i = 0; i < m_MouseButtons.Count(); ++i )
        {
            MouseButtonInfo info = m_MouseButtons.Get(i);
            if ( info.GetButtonID() == button )
            {
                return info;
            }
        }
        return NULL;
    }
References MouseButtonInfo::GetButtonID().
GetMousePositionInScene()
private vector PluginBase::GetMousePositionInScene () inline private
Definition at line 1263 of file pluginscenemanager.c.
    {
        vector dir = GetGame().GetPointerDirection();
        vector from = FreeDebugCamera.GetInstance().GetPosition();
        vector to = from + ( dir * 10000 );
        vector contact_pos;
        vector contact_dir;
        int contact_component;
        if ( DayZPhysics.RaycastRV(from, to, contact_pos, contact_dir, contact_component) )
        {
            return contact_pos;
        }
        return "0 0 0";
    }
References GetGame(), CGame::GetPointerDirection(), and DayZPhysics::RaycastRV().
GetName()
string PluginBase::GetName (int id) inline private
Definition at line 27 of file pluginvariables.c.
    {
        return m_Variables.Get(id);
    }
References string::Get().
GetNameByID()
static string PluginBase::GetNameByID (int agent_id) inline static private
Definition at line 61 of file plugintransmissionagents.c.
    {
        return m_AgentList.Get(agent_id).GetName();
    }
References string::Get().
GetOnlyChildPath()
string PluginBase::GetOnlyChildPath (string config_class_path, string class_path) inline private
Definition at line 28 of file pluginconfigviewer.c.
    {
        int config_class_path_len = config_class_path.Length();
        int class_path_len = class_path.Length();
        if ( class_path_len > config_class_path_len )
        {
            int start = config_class_path_len;
            int count = class_path_len - start;
            return class_path.Substring(start, count).Trim();
        }
        else
        {
            return "";
        }
    }
References string::Length(), string::Substring(), and string::Trim().
Referenced by GetBaseClassPath().
GetPlantMaterial()
PlantMaterialHealth PluginBase::GetPlantMaterial (string plant_type) inline private
Definition at line 107 of file pluginhorticulture.c.
    {
        if ( m_PlantMaterials.Contains(plant_type) )
        {
            return m_PlantMaterials.Get(plant_type);
        }
        return NULL;
    }
GetPlantType()
string PluginBase::GetPlantType (Object obj) inline private
Definition at line 74 of file pluginhorticulture.c.
    {
        string seed_type = obj.GetType();
        string plant_type = "";
        GetGame().ConfigGetText( "cfgVehicles " + seed_type + " Horticulture PlantType", plant_type );
        return plant_type;
    }
References CGame::ConfigGetText(), and GetGame().
GetPlayerListTimer()
static int PluginBase::GetPlayerListTimer () inline static private
Definition at line 30 of file pluginadminlog.c.
    {
        return 300; // seconds
    }
GetPlayerPrefix()
string PluginBase::GetPlayerPrefix (PlayerBase player, PlayerIdentity identity) inline private
Definition at line 67 of file pluginadminlog.c.
    {
        m_Position = player.GetPosition();
        m_PosArray[3] = { m_Position[0].ToString(), m_Position[2].ToString(), m_Position[1].ToString() };
        for ( int i = 0; i < 3; i++ )   // trim position precision
        {
            m_DotIndex = m_PosArray[i].IndexOf(".");
            if ( m_DotIndex != -1 )
            {
            m_PosArray[i] = m_PosArray[i].Substring( 0, m_DotIndex + 2 );
            }
        }
        if ( !identity )    // return partial message even if it fails to fetch identity
        {
            return "Player \"" + "Unknown/Dead Entity" + "\" (id=" + "Unknown" + " pos=<" +  m_PosArray[0] + ", " + m_PosArray[1] + ", " + m_PosArray[2] + ">)";
        }
        m_PlayerName = "\"" + identity.GetName() + "\"";
        m_Pid = identity.GetId();
        if ( !player.IsAlive() )
        {
            m_PlayerName = m_PlayerName + " (DEAD)";
        }
        return "Player " + m_PlayerName + " (id=" + m_Pid + " pos=<" +  m_PosArray[0] + ", " + m_PosArray[1] + ", " + m_PosArray[2] + ">)";
    }
References PlayerIdentityBase::GetId(), PlayerIdentityBase::GetName(), string::IndexOf(), m_PlayerName, m_Position, string::Substring(), and vector::ToString().
Referenced by BleedingOut(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), UnconStart(), and UnconStop().
GetPotency()
EStatLevels PluginBase::GetPotency (int agent_id) inline private
Definition at line 165 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) )
            return 0;
        return m_AgentList.Get(agent_id).GetPotency();
    }
GetProtectionLevel()
protected float PluginBase::GetProtectionLevel (int type, int slot, Man player) inline private
Definition at line 345 of file plugintransmissionagents.c.
    {
        return GetProtectionLevelEx(type, slot, player);
    }
References GetProtectionLevelEx().
Referenced by TransmitAgentsEx().
GetProtectionLevelEx()
static float PluginBase::GetProtectionLevelEx (int type, int slot, Man player, bool consider_filter = true, int system = 0) inline static private
Definition at line 334 of file plugintransmissionagents.c.
    {
        ItemBase attachment = ItemBase.Cast(player.GetInventory().FindAttachment(slot));
        if(!attachment)
            return 0;
        return attachment.GetProtectionLevel(type, consider_filter, system);
    }
Referenced by GetProtectionLevel().
GetRotationAngle()
int PluginBase::GetRotationAngle () inline private
Definition at line 746 of file pluginscenemanager.c.
    {
        return m_ModuleConfigDebugProfile.GetSceneEditorRotationAngle();
    }
GetRPCModifierID()
int PluginBase::GetRPCModifierID (ParamsReadContext ctx) inline private
Definition at line 375 of file plugindevelopersync.c.
    {
        Param1<int> p = new Param1<int>( 0 );
        if ( ctx.Read( p ) )
        {
            return p.param1;
        }
        return 0;
    }
References Serializer::Read().
Referenced by OnRPC().
GetRPCModifierLock()
void PluginBase::GetRPCModifierLock (ParamsReadContext ctx, out int id, out bool lock) inline private
Definition at line 387 of file plugindevelopersync.c.
    {
        Param2<int, bool> p = new Param2<int, bool>( 0, false );
        if ( ctx.Read( p ) )
        {
            id = p.param1;
            lock = p.param2;
        }
    }
References Serializer::Read().
Referenced by OnRPC().
GetRPCUpdateState()
bool PluginBase::GetRPCUpdateState (ParamsReadContext ctx) inline private
Definition at line 363 of file plugindevelopersync.c.
    {
        Param1<bool> p = new Param1<bool>( 0 );
        if ( ctx.Read( p ) )
        {
            return p.param1;
        }
        return false;
    }
References Serializer::Read().
Referenced by OnRPC(), and OnRPCTemp().
GetSceneList()
TStringArray PluginBase::GetSceneList () inline private
Definition at line 1083 of file pluginscenemanager.c.
    {
        return m_ModuleConfigScene.GetSceneList();
    }
GetSceneObjectByEntity()
SceneObject PluginBase::GetSceneObjectByEntity (EntityAI entity) inline private
Definition at line 1059 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        if ( scene_objects != NULL )
        {
            for ( int i = 0; i <= scene_objects.Count(); ++i )
            {
                SceneObject obj = scene_objects.Get(i);
                EntityAI e = obj.GetObject();
                if ( e == entity )
                {
                    return obj;
                }
            }
        }
        return NULL;
    }
References SceneObject::GetObject().
GetSceneObjectByIndex()
SceneObject PluginBase::GetSceneObjectByIndex (int index) inline private
Definition at line 1041 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        if ( scene_objects != NULL )
        {
            if ( index > -1 && index < scene_objects.Count() )
            {
                return scene_objects.Get( index );
            }
        }
        return NULL;
    }
GetSceneObjects()
array< ref SceneObject > PluginBase::GetSceneObjects () inline private
Definition at line 1002 of file pluginscenemanager.c.
    {
        if ( m_SceneData )
        {
            return m_SceneData.GetSceneObjects();
        }
        return NULL;
    }
GetSceneObjectsAll()
array< ref SceneObject > PluginBase::GetSceneObjectsAll () inline private
Definition at line 1028 of file pluginscenemanager.c.
    {
        if ( m_SceneData )
        {
            return m_SceneData.GetSceneObjectsAll();
        }
        return NULL;
    }
GetScenePlayers()
array< ref ScenePlayer > PluginBase::GetScenePlayers () inline private
Definition at line 1015 of file pluginscenemanager.c.
    {
        if ( m_SceneData )
        {
            return m_SceneData.GetScenePlayers();
        }
        return NULL;
    }
GetSelectedSceneObject()
SceneObject PluginBase::GetSelectedSceneObject () inline private
Definition at line 491 of file pluginscenemanager.c.
    {
        return m_SelectedObject;
    }
References m_SelectedObject.
GetSelectedSceneObjectIndex()
int PluginBase::GetSelectedSceneObjectIndex () inline private
Definition at line 985 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        for ( int i = 0; i < scene_objects.Count(); i++ )
        {
            if ( GetSelectedSceneObject() == scene_objects.Get(i) )
            {
                return i;
            }
        }
        return -1;
    }
GetSimpleAgentList()
map< int, string > PluginBase::GetSimpleAgentList () inline private
Definition at line 51 of file plugintransmissionagents.c.
    {
        if( !m_IsConstructed )
        {
            ConstructSimpleAgentList();
            m_IsConstructed = true;
        }
        return m_SimpleAgentList;
    }
References ConstructSimpleAgentList(), and m_SimpleAgentList.
GetSurfaceFertility()
float PluginBase::GetSurfaceFertility (string surface_type) inline private
Definition at line 84 of file pluginhorticulture.c.
    {
        float fertility = 0.8;
        if ( surface_type == "hlina" || surface_type == "CRGrass1" || surface_type == "CRGrass2" || surface_type == "CRForest1" || surface_type == "CRForest2" || surface_type == "CRGrit1" )
        {
            fertility = 0.8;
        }
        return fertility;
    }
GetWatching()
bool PluginBase::GetWatching () inline private
Definition at line 35 of file pluginremoteplayerdebugserver.c.
    {
        return m_Watching;
    }
References m_Watching.
Referenced by OnDamageEvent().
GiveWormsToPlayer()
bool PluginBase::GiveWormsToPlayer (PlayerBase player, float chance) inline private
Definition at line 95 of file pluginhorticulture.c.
    {
        if ( Math.RandomFloat01() <= chance )
        {
            ItemBase item = ItemBase.Cast( player.GetHumanInventory().CreateInInventory("Food_Worm") );
            item.SetQuantity( 1 );
            return true;
        }
        return false;
    }
References Math::RandomFloat01().
GrowDuringAntibioticsAttack()
bool PluginBase::GrowDuringAntibioticsAttack (int agent_id, PlayerBase player) inline private
Definition at line 85 of file plugintransmissionagents.c.
    {
        if( !m_AgentList.Get(agent_id) ) return true;
        return m_AgentList.Get(agent_id).GrowDuringAntibioticsAttack(player);
    }
HandlePresetSpawn()
void PluginBase::HandlePresetSpawn (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 197 of file plugindeveloper.c.
    {
        #ifdef DEVELOPER
        if ( ctx.Read(CachedObjectsParams.PARAM1_STRING ) )
        {
            player.m_PresetSpawned = true;
            string preset_name = CachedObjectsParams.PARAM1_STRING.param1;
            string class_name = preset_name + "_Preset";
            typename type = class_name.ToType();
            if (type)
            {
                m_PresetObj = PresetSpawnBase.Cast(type.Spawn());
            }
            if (m_PresetObj)
            {
                m_PresetObj.Init(player);
            }
        }
        #endif
    }
References class_name, CachedObjectsParams::PARAM1_STRING, and Serializer::Read().
Referenced by OnRPC().
HandleSetTime()
void PluginBase::HandleSetTime (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 165 of file plugindeveloper.c.
    {
        #ifdef DEVELOPER
        Param5<int,int,int,int,int> p5 = new Param5<int,int,int,int,int>(0,0,0,0,0);
        if ( ctx.Read( p5 ) )
        {
            //float time01 = p5.param4 / 100;
            //int time_minutes = Math.Lerp(0, 24*60, time01 );
            int year = p5.param1;
            int month = p5.param2;
            int day = p5.param3;
            int hour = p5.param4;
            int minute = p5.param5;
            GetGame().GetWorld().SetDate(year,month, day, hour, minute);
            /*
            Debug.Log("year:" + year);
            Debug.Log("month:" + month);
            Debug.Log("day:" + day);
            Debug.Log("hour:" + hour);
            Debug.Log("minute:" + minute);
            */
        }
        #endif
    }
References GetGame(), CGame::GetWorld(), Serializer::Read(), and World::SetDate().
Referenced by OnRPC().
Hide() [1/3]
void PluginBase::Hide () inline private
Definition at line 177 of file plugindayzinfecteddebug.c.
    {
        ShowWidgets(false);
        m_IsActive = false;
        GetUApi().UpdateControls();
        m_TickTimer = NULL;
    }
References GetUApi(), m_IsActive, m_TickTimer, ShowWidgets(), and UAInputAPI::UpdateControls().
Referenced by SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Hide() [2/3]
void PluginBase::Hide () inline private
Definition at line 87 of file plugindrawcheckerboard.c.
    {
        ShowWidgets(false);
        m_IsActive = false;
    }
References m_IsActive, and ShowWidgets().
Hide() [3/3]
void PluginBase::Hide () inline private
Definition at line 25 of file pluginsounddebug.c.
    {
        m_TickTimer = NULL;
    }
References m_TickTimer.
Init() [1/2]
void PluginBase::Init () inline private
Definition at line 34 of file plugincharplacement.c.
    {
        if(m_Character)
            m_Character.Delete();
        m_Initialized = true;
        m_Character = PlayerBase.Cast( GetGame().CreateObject("SurvivorF_Judy", FreeDebugCamera.GetInstance().GetPosition(), false, false/*ai*/) );
        FreeDebugCamera.GetInstance().SetFOV(FOV); //default scene FOV
        m_demoRot = "0 0 0";
    }
References GetGame(), and m_Initialized.
Referenced by CheckInit().
Init() [2/2]
void PluginBase::Init () inline private
Definition at line 14 of file plugindoorruler.c.
    {
        if(m_Ruler)
            m_Ruler.Delete();
        m_Initialized = true;
        m_Ruler = ItemBase.Cast( GetGame().CreateObject("DoorTestCamera", FreeDebugCamera.GetInstance().GetPosition(), false, false/*ai*/) );
    }
References GetGame(), and m_Initialized.
InitAttacks()
void PluginBase::InitAttacks () inline private
Definition at line 421 of file plugindayzinfecteddebug.c.
    {
        m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Left Light", 0));
        m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Right Light", 1));
        m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Left Heavy", 2));
        m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Attack Right Heavy", 3));
        m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Crawl Attack", 7));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Crawl Attack Combo", 8));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Push Attack", 9));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Head Attack", 10));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Shoulder Attack", 11));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door LR Attack", 12));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Kick Attack", 13));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Charge R", 14));
        //m_AttackDescriptors.Insert(new PluginDayZInfectedDebugAttackDesc("Door Charge L", 15));
        for( int i = 0; i < m_AttackDescriptors.Count(); ++i )
        {
            m_AttackTypeCB.AddItem(m_AttackDescriptors.Get(i).name);
        }
    }
References PluginDayZInfectedDebugAttackDesc().
Referenced by CreateModuleWidgets().
InitLoad()
void PluginBase::InitLoad () inline private
Definition at line 312 of file pluginscenemanager.c.
    {
        PLAYER = PlayerBase.Cast( GetGame().GetPlayer() );
        SceneLoad( PluginMissionConfig.GetInstance().GetSceneEditorName() );
        RestoreSceneObjectsLinks();
        ExecuteInitScripts();
    }
References GetGame(), GetPlayer(), and PLAYER.
InitWidgets()
void PluginBase::InitWidgets () inline private
Definition at line 39 of file pluginuniversaltemperaturesourceclient.c.
    {
        for (int i = 0; i < MAX_SIMULTANEOUS_UTS; i++)
        {
            m_RootWidget[i] = GetGame().GetWorkspace().CreateWidgets("gui/layouts/debug/day_z_debug_remoteinfo.layout");
            m_StatListWidgets[i] = TextListboxWidget.Cast(m_RootWidget[i].FindAnyWidget("TextListboxWidget0"));
        }
    }
References WorkspaceWidget::CreateWidgets(), FindAnyWidget(), GetGame(), CGame::GetWorkspace(), m_RootWidget, m_StatListWidgets, and MAX_SIMULTANEOUS_UTS.
Referenced by OnInit(), and OnInit().
InjectAgentsWithoutPlayer()
protected void PluginBase::InjectAgentsWithoutPlayer (EntityAI target, int agents) inline private
Definition at line 264 of file plugintransmissionagents.c.
    {
        if( target.IsItemBase() )
        {
            ItemBase ib_target = ItemBase.Cast( target );
            ib_target.TransferAgents(agents);
        }
    }
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayer()
protected void PluginBase::InjectAgentsWithPlayer (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline private
will add agents to a given target, using chance of transmission and full dose size if chance succeeds
Definition at line 274 of file plugintransmissionagents.c.
    {
        if(target && (agents != 0) && target.IsEntityAI() )
        {
            int bit_count = Math.GetNumberOfSetBits(agents);
            for (int i = 0; i < bit_count; i++)
            {
                int agent_bit = Math.Pow(2,Math.GetNthBitSet(agents,i));
                if( DetermineChanceToTransmit(agent_bit, protection, inject_type))
                {
                    target.InsertAgent(agent_bit,dose_size);
                }
            }
        }
    }
References DetermineChanceToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentsWithPlayerCount()
protected void PluginBase::InjectAgentsWithPlayerCount (EntityAI target, int agents, float protection, int dose_size, int inject_type) inline private
will add agents to a given target, with no probability, but the dose size is modified by m_TransferabilityOut of the agent
Definition at line 292 of file plugintransmissionagents.c.
    {
        if(target && (agents != 0) && target.IsEntityAI() )
        {
            int bit_count = Math.GetNumberOfSetBits(agents);
            for (int i = 0; i < bit_count; i++)
            {
                int agent_bit = Math.Pow(2,Math.GetNthBitSet(agents,i));
                float count = CalculateAgentsToTransmit(agent_bit, protection, dose_size, inject_type);
                target.InsertAgent(agent_bit,count);
            }
        }
    }
References CalculateAgentsToTransmit(), Math::GetNthBitSet(), Math::GetNumberOfSetBits(), and Math::Pow().
Referenced by TransmitAgentsEx().
InjectAgentWithPlayerDose()
protected float PluginBase::InjectAgentWithPlayerDose (EntityAI target, int agent, float protection, float dose_size, int inject_type) inline private
will add agent to a given target
Definition at line 308 of file plugintransmissionagents.c.
    {
        float count = CalculateAgentsToTransmit(agent, protection, dose_size, inject_type);
        {
            if(count > 0)
            {
                target.InsertAgent(agent, count);
                return count;
            }
        }
        return 0;
    }
References CalculateAgentsToTransmit().
Referenced by TransmitAgentsEx().
IsActive()
bool PluginBase::IsActive () inline private
Definition at line 57 of file plugindrawcheckerboard.c.
    {
        return m_IsActive;
    }
References m_IsActive.
IsCurrentUIPageValid()
protected bool PluginBase::IsCurrentUIPageValid (int ui_page_request) inline private
Definition at line 303 of file pluginkeybinding.c.
    {
        int ui_page_current = MENU_NONE;
        if ( GetGame().GetUIManager().GetMenu() )
        {
            ui_page_current = GetGame().GetUIManager().GetMenu().GetID();
        }
        if ( ui_page_current < MENU_ANY || !CheckMask( ui_page_request, ui_page_current ) )
        {
            if ( CheckMask( ui_page_request, MENU_NONE ) || !CheckMask( ui_page_request, MENU_ANY ) )
            {
                return false;
            }
        }
        return true;
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), MENU_ANY, and MENU_NONE.
IsEnabledFreeCamera()
bool PluginBase::IsEnabledFreeCamera () inline private
Definition at line 41 of file plugindeveloper.c.
    {
        return DeveloperFreeCamera.IsFreeCameraEnabled();
    }
References DeveloperFreeCamera::IsFreeCameraEnabled().
IsEven()
bool PluginBase::IsEven (int num) inline private
even or odd
Definition at line 63 of file plugindrawcheckerboard.c.
    {
        if((num % 2) == 0)
            return true;
        else
            return false;
    }
Referenced by CreateWidgetOverlay().
IsFree()
bool PluginBase::IsFree (Object target) inline private
Definition at line 18 of file pluginobjectsinteractionmanager.c.
    {
        if ( target && m_LockedObjects.Count() > 0 )
        {
            for ( int i = 0; i < m_LockedObjects.Count(); i++ )
            {
                if ( m_LockedObjects.Get(i) == target )
                {
                    return false;
                }
            }
        }
        return true;
    }
Referenced by Lock().
IsInConsole()
private bool PluginBase::IsInConsole () inline private
Definition at line 673 of file plugindeveloper.c.
    {
        UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
        if ( menu_curr != NULL && menu_curr.GetID() == MENU_SCRIPTCONSOLE )
        {
            return true;
        }
        return false;
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and MENU_SCRIPTCONSOLE.
IsIngame()
private bool PluginBase::IsIngame () inline private
Definition at line 661 of file plugindeveloper.c.
    {
        UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
        if ( menu_curr == NULL )
        {
            return true;
        }
        return false;
    }
References GetGame(), UIManager::GetMenu(), and CGame::GetUIManager().
IsKeyPressed()
protected bool PluginBase::IsKeyPressed (int key) inline private
Definition at line 373 of file pluginkeybinding.c.
    {
        return ( KeyState(key) == 1 );
    }
References KeyState().
IsModifierLocked()
bool PluginBase::IsModifierLocked (int id, PlayerBase player = NULL) inline private
Definition at line 693 of file plugindevelopersync.c.
    {
        if ( !player )
        {
            player = PlayerBase.Cast( GetDayZGame().GetPlayer() );
        }
        ModifiersManager mods_manager = player.GetModifiersManager();
        return mods_manager.GetModifierLock( Math.AbsInt( id ) );
    }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
IsMouseInScene()
private bool PluginBase::IsMouseInScene () inline private
Definition at line 1227 of file pluginscenemanager.c.
    {
        Widget widget_under_mouse = GetWidgetUnderCursor();
        if ( widget_under_mouse != NULL && widget_under_mouse.GetName() == "pnl_SceneControl" )
        {
            return true;
        }
        return false;
    }
References GetWidgetUnderCursor().
IsOpened()
bool PluginBase::IsOpened () inline private
Definition at line 393 of file pluginscenemanager.c.
    {
        return m_IsOpen;
    }
IsPlayerRegistered()
bool PluginBase::IsPlayerRegistered (PlayerBase player) inline private
Definition at line 239 of file plugindevelopersync.c.
    {
        if ( m_RegisteredPlayers.Contains( player ))
        {
            return true;
        }
        return false;
    }
Referenced by EnableUpdate(), IsSetSystemInBitmask(), RegisterPlayer(), and SetSystemInBitmask().
IsReadOnly()
bool PluginBase::IsReadOnly () inline private
Definition at line 104 of file pluginfilehandler.c.
    {
        return m_ReadOnly;
    }
IsRepairValid()
private bool PluginBase::IsRepairValid (int repair_kit_type, int repairable_with_type) inline private
Definition at line 114 of file pluginrepairing.c.
    {
        if ( repair_kit_type > 0 && repairable_with_type > 0 )
        {
            if ( repair_kit_type == repairable_with_type )
            {
                return true;
            }
        }
        return false;
    }
Referenced by CanRepair().
IsRulerActivated()
bool PluginBase::IsRulerActivated () inline private
Definition at line 929 of file pluginscenemanager.c.
    {
        return m_RulerActivated;
    }
IsSetSystemInBitmask()
bool PluginBase::IsSetSystemInBitmask (PlayerBase player, int system_bit) inline private
Definition at line 209 of file plugindevelopersync.c.
    {
        if ( IsPlayerRegistered(player) )
        {
            return (m_RegisteredPlayers.Get(player).m_Bitmask & system_bit);
        }
        return false;
    }
References IsPlayerRegistered().
Referenced by RequestDetailedInfo().
LinkSceneObjects()
void PluginBase::LinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 671 of file pluginscenemanager.c.
    {
        scene_object1.LinkSceneObject(scene_object2);
        scene_object2.LinkSceneObject(scene_object1);
    }
References SceneObject::LinkSceneObject().
LoadFile()
bool PluginBase::LoadFile () inline private
Definition at line 52 of file pluginfilehandler.c.
    {
        ClearFileNoSave();
        FileHandle file_index = OpenFile(GetFileName(), FileMode.READ);
        if ( file_index == 0 )
        {
            return false;
        }
        string line_content = "";
        int char_count = FGets( file_index,  line_content );
        while ( char_count != -1 )
        {
            m_FileContent.Insert(line_content);
            char_count = FGets( file_index,  line_content );
        }
        CloseFile(file_index);
        return true;
    }
References CloseFile(), FGets(), PluginFileHandler::GetFileName(), and OpenFile().
LoadFromCfg()
void PluginBase::LoadFromCfg () inline private
Definition at line 12 of file pluginhorticulture.c.
    {
        string cfg_access = "CfgHorticulture"; // it is stored in dz\gear\cultivation\cfgHorticulture.hpp
        int cfg_horticulture_count = GetGame().ConfigGetChildrenCount( cfg_access );
        for ( int i = 0; i < cfg_horticulture_count; i++ )
        {
            string cfg_class_name = "";
            GetGame().ConfigGetChildName( cfg_access, i, cfg_class_name );
            string cfg_class_access = cfg_access + " " + cfg_class_name;
            int cfg_class_count = GetGame().ConfigGetChildrenCount( cfg_class_access );
            for ( int j = 0; j < cfg_class_count; j++ )
            {
                string cfg_subclass_name = "";
                GetGame().ConfigGetChildName( cfg_class_access, j, cfg_subclass_name );
                string cfg_subclass_access = cfg_class_access + " " + cfg_subclass_name;
                int cfg_subclass_count = GetGame().ConfigGetChildrenCount( cfg_subclass_access );
                PlantMaterialHealth plantMaterialHealth = NULL;
                if ( cfg_class_name == "Plants" )
                {
                    plantMaterialHealth = new PlantMaterialHealth;
                    m_PlantMaterials.Set( cfg_subclass_name, plantMaterialHealth );
                }
                for ( int k = 0; k < cfg_subclass_count; k++ )
                {
                    string cfg_variable_name = "";
                    GetGame().ConfigGetChildName( cfg_subclass_access, k, cfg_variable_name );
                    string cfg_variable_access = cfg_subclass_access + " " + cfg_variable_name;
                    if ( cfg_class_name == "Plants" )
                    {
                        string string_param = "";
                        GetGame().ConfigGetText( cfg_variable_access, string_param );
                        if ( cfg_variable_name == "infestedTex" )
{
                            plantMaterialHealth.m_InfestedTex = string_param;
                        }
                        else if ( cfg_variable_name == "infestedMat" )
{
                            plantMaterialHealth.m_InfestedMat = string_param;
                        }
                        else if ( cfg_variable_name == "healthyTex" )
{
                            plantMaterialHealth.m_HealthyTex = string_param;
                        }
                        else if ( cfg_variable_name == "healthyMat" )
{
                            plantMaterialHealth.m_HealthyMat = string_param;
                        }
                    }
                }
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), GetGame(), PlantMaterialHealth::m_HealthyMat, PlantMaterialHealth::m_HealthyTex, PlantMaterialHealth::m_InfestedMat, and PlantMaterialHealth::m_InfestedTex.
Referenced by PluginHorticulture(), and PluginLifespan().
Lock()
void PluginBase::Lock (Object target) inline private
Definition at line 33 of file pluginobjectsinteractionmanager.c.
    {
        if ( target && !IsFree(target) )
        {
            m_LockedObjects.Insert(target);
            m_LockedObjectsDecay.Insert(0);
        }
    }
References IsFree().
LockModifier()
void PluginBase::LockModifier (int id, bool lock, PlayerBase player = NULL) inline private
Definition at line 683 of file plugindevelopersync.c.
    {
        if ( !player )
        {
            player = PlayerBase.Cast( GetDayZGame().GetPlayer() );
        }
        ModifiersManager mods_manager = player.GetModifiersManager();
        mods_manager.SetModifierLock( Math.AbsInt( id ), lock );
    }
References Math::AbsInt(), GetDayZGame(), GetPlayer(), and ModifiersManager().
Referenced by OnRPC().
Log()
void PluginBase::Log (string msg, string label) inline private
Definition at line 23 of file pluginbase.c.
    {
        Debug.Log(msg, GetModuleName(), "n/a", label, "n/a");
    }
References GetModuleName(), and Debug::Log().
Referenced by CheckInit().
LogPrint()
void PluginBase::LogPrint (string message) inline private
Definition at line 62 of file pluginadminlog.c.
    {
        GetGame().AdminLog( message );
    }
References CGame::AdminLog(), and GetGame().
Referenced by BleedingOut(), DirectAdminLogPrint(), OnContinouousAction(), OnPlacementComplete(), PlayerHitBy(), PlayerKilled(), PlayerList(), Suicide(), UnconStart(), and UnconStop().
MakeTabs()
string PluginBase::MakeTabs (int count, bool inheritance = false) inline private
Definition at line 7 of file pluginconfigviewer.c.
    {
        if ( count == 0 )
        {
            return "";
        }
        string tabs = "|--";
        if ( inheritance )
        {
            tabs = "|<<";
        }
        for ( int i = 0; i < count - 1; i++ )
        {
            tabs = "|  " + tabs;
        }
        return tabs;
    }
Referenced by GetConfig(), and GetConfigRecursive().
OnChange()
bool PluginBase::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 330 of file plugindayzinfecteddebug.c.
    {
        return false;
    }
OnClick()
bool PluginBase::OnClick (Widget w, int x, int y, int button) inline private
buttons clicks
Definition at line 269 of file plugindayzinfecteddebug.c.
    {
        if( !m_HasFocus )
            return false;
        if( w == m_SpawnEntityButton )
        {
            ResetValues();
            SpawnNewInfectedEntity();
            return true;
        }
        if( w == m_CardMovementButton )
        {
            ShowCard(0);
            return true;
        }
        else if( w == m_CardFightButton )
        {
            ShowCard(1);
            return true;
        }
        else if( w == m_StartTurnButton )
        {
            m_CH_DoTurn = true;
            return true;
        }
        else if( w == m_StartVaultButton )
        {
            m_CH_DoVault = true;
            return true;
        }
        else if( w == m_KnucleOutButton )
        {
            m_CH_DoKnucleOut = true;
            return true;
        }
        else if( w == m_StartCrawlingButton )
        {
            m_CH_GoToCrawl = true;
            return true;
        }
        else if( w == m_StartHitButton )
        {
            m_CH_DoHit = true;
            return true;
        }
        else if( w == m_StartDeathButton )
        {
            m_CH_StartDeath = true;
            return true;
        }
        else if( w == m_StartAttackButton )
        {
            m_CH_DoAttack = true;
            return true;
        }
        return false;
    }
References m_HasFocus, ResetValues(), ShowCard(), and SpawnNewInfectedEntity().
OnContinouousAction()
void PluginBase::OnContinouousAction (ActionData action_data) inline private
Definition at line 306 of file pluginadminlog.c.
    {
        if ( m_ActionsFilter == 1 )
        {
            m_Message = action_data.m_Action.GetAdminLogMessage(action_data);
            if(m_Message == "")
                return;
            m_PlayerPrefix = this.GetPlayerPrefix( action_data.m_Player , action_data.m_Player.GetIdentity() );
            LogPrint( m_PlayerPrefix + m_Message );
        }
    }
References GetPlayerPrefix(), LogPrint(), ActionData::m_Action, and ActionData::m_Player.
OnDamageEvent()
void PluginBase::OnDamageEvent (PlayerBase player, TotalDamageResult damageResult) inline private
Definition at line 96 of file pluginremoteplayerdebugserver.c.
    {
        if( !GetWatching() || !damageResult ) return;
        float damage_global = damageResult.GetDamage("","");
        float damage_blood = damageResult.GetDamage("","Blood");
        float damage_shock = damageResult.GetDamage("","Shock");
        if( m_PlayerDebugDamage.Contains(player) )
        {
            m_PlayerDebugDamage.Get(player).AddDamage( damage_global, damage_blood, damage_shock );
        }
        else
        {
            RemotePlayerDamageDebug rpdd = new RemotePlayerDamageDebug(player);
            rpdd.AddDamage(damage_global, damage_blood, damage_shock);
            m_PlayerDebugDamage.Insert(player, rpdd);
        }
    }
References RemotePlayerDamageDebug::AddDamage(), TotalDamageResult::GetDamage(), GetWatching(), and m_PlayerDebugDamage.
OnDestroy() [1/5]
void PluginBase::OnDestroy () inline private
Definition at line 19 of file pluginbase.c.
    {
    }
Referenced by PluginManager::~PluginManager().
OnDestroy() [2/5]
override void PluginBase::OnDestroy () inline private
Definition at line 64 of file plugincharplacement.c.
    {
        FreeDebugCamera.GetInstance().SetFOV(g_Game.GetUserFOV());
    }
References g_Game.
OnDestroy() [3/5]
override void PluginBase::OnDestroy () inline private
Definition at line 117 of file pluginkeybinding.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Remove(this.OnFrame);
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), and ScriptInvoker::Remove().
OnDestroy() [4/5]
override void PluginBase::OnDestroy () inline private
Definition at line 62 of file pluginscenemanager.c.
    {
        SceneUnload();
    }
OnDestroy() [5/5]
override void PluginBase::OnDestroy () inline private
Definition at line 14 of file pluginsounddebug.c.
    {
        m_TickTimer = NULL;
    }
References m_TickTimer.
OnFrame()
void PluginBase::OnFrame () inline private
Definition at line 239 of file pluginkeybinding.c.
    {
        for ( int i = 0; i < m_MouseButtons.Count(); ++i )
        {
            MouseButtonInfo info = m_MouseButtons.Get(i);
            if ( info.IsButtonDown() )
            {
                int time_curr = GetGame().GetTime();
                int time_hold = info.GetTimeLastPress() + HOLD_CLICK_TIME_MIN;
                if ( time_hold < time_curr )
                {
    //Log("MB_EVENT_DRAG");
                    OnMouse( MB_EVENT_DRAG, info.GetButtonID() );
                }
            }
        }
    }
References MouseButtonInfo::GetButtonID(), GetGame(), CGame::GetTime(), MouseButtonInfo::GetTimeLastPress(), MouseButtonInfo::IsButtonDown(), and MB_EVENT_DRAG.
OnGUITimer()
void PluginBase::OnGUITimer () inline private
Definition at line 30 of file pluginsounddebug.c.
    {
        DbgUI.BeginCleanupScope();
        DbgUI.Begin("Sound debug", 10, 10);
        DbgUI.PushID_Str("SoundParams");
        DbgUI.Text("SoundParams: ");
        DbgUI.SameLine();
        string soundsetName = "BearGrowl_SoundSet";
        DbgUI.InputText("", soundsetName, 200);
        DbgUI.PopID();
        DbgUI.PushID_Str("Offset");
        DbgUI.Text("Offset pos: ");
        vector posOffset = "0 0 0";
        float posVal;
        DbgUI.SameLine();
        DbgUI.PushID_Int(1);
            DbgUI.InputFloat("", posVal, 80);
        DbgUI.PopID();
        posOffset[0] = posVal;
        DbgUI.SameLine();
        DbgUI.PushID_Int(2);
            DbgUI.InputFloat("", posVal, 80);
        DbgUI.PopID();
        posOffset[1] = posVal;
        DbgUI.SameLine();
        DbgUI.PushID_Int(3);
            DbgUI.InputFloat("", posVal, 80);
        DbgUI.PopID();
        posOffset[2] = posVal;
        DbgUI.PopID();
        if(DbgUI.Button("Create"))
        {
            m_soundParams = new SoundParams(soundsetName);
            m_soundBuilder = new SoundObjectBuilder(m_soundParams);
            m_soundObject = m_soundBuilder.BuildSoundObject();
            m_soundObject.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset);
        }
        DbgUI.Text("SoundObjectBuilder: ");
        DbgUI.Text("SoundObject: ");
        DbgUI.Text("AbstractWave: ");
        vector posOffset2 = "0 10 0";
        if(m_soundParams != NULL)
        {
            DbgUI.Text("FadeInFactor: ");
            DbgUI.SameLine();
            DbgUI.PushID_Str("fadeIn");
            DbgUI.InputFloat("", fadeInVolume, 80);
            DbgUI.PopID();
            DbgUI.Text("FadeOutFactor: ");
            DbgUI.SameLine();
            DbgUI.PushID_Str("fadeOut");
            DbgUI.InputFloat("", fadeOutVolume, 80);
            DbgUI.PopID();
            DbgUI.PushID_Str("Offset2");
            DbgUI.Text("Offset2 pos: ");
            float posVal2;
            DbgUI.SameLine();
            DbgUI.PushID_Int(100);
                posVal2 = posOffset2[0];
                DbgUI.InputFloat("", posVal2, 80);
            DbgUI.PopID();
            posOffset2[0] = posVal2;
            DbgUI.SameLine();
            DbgUI.PushID_Int(101);
                posVal2 = posOffset2[1];
                DbgUI.InputFloat("", posVal2, 80);
            DbgUI.PopID();
            posOffset2[1] = posVal2;
            DbgUI.SameLine();
            DbgUI.PushID_Int(102);
                posVal2 = posOffset2[2];
                DbgUI.InputFloat("", posVal2, 80);
            DbgUI.PopID();
            posOffset2[2] = posVal2;
            DbgUI.PopID();
            DbgUI.Text("skip: ");
            DbgUI.SameLine();
            float skip = 0.0;
            DbgUI.PushID_Int(200);
            DbgUI.InputFloat("", skip, 80);
            DbgUI.PopID();
            if(DbgUI.Button("Create and play"))
            {
                m_wave = GetGame().GetSoundScene().Play3D(m_soundObject, m_soundBuilder);
                m_wave.SetFadeInFactor(fadeInVolume);
                m_wave.Skip(skip);
                m_wave.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset2);
            }
        }
        if(m_wave != NULL)
        {
            DbgUI.Text("Wave length: " + m_wave.GetLength() + "s");
            //DbgUI.Text("Wave position: " + Math.Round(m_wave.GetCurrPosition() * 100) + "%");
            DbgUI.Text("Volume: ");
            DbgUI.SameLine();
            float volume = 1.0;
            DbgUI.InputFloat(" ", volume, 80);
            DbgUI.SameLine();
            if(DbgUI.Button("SetVolume"))
                m_wave.SetVolume(volume);
            DbgUI.SameLine();
            if(DbgUI.Button("SetVolumeRelative"))
                m_wave.SetVolumeRelative(volume);
            if(DbgUI.Button("Play"))
                m_wave.Play();
            if(DbgUI.Button("Stop"))
                m_wave.Stop();
            if(DbgUI.Button("Restart"))
                m_wave.Restart();
            if(DbgUI.Button("Repeat"))
                m_wave.Loop(true);
            if(DbgUI.Button("StopRepeat"))
                m_wave.Loop(false);
            if(DbgUI.Button("Set position"))
                m_wave.SetPosition(GetGame().GetPlayer().GetPosition() + posOffset2);
        }
        DbgUI.End();
        DbgUI.EndCleanupScope();
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::Button(), DbgUI::End(), DbgUI::EndCleanupScope(), GetGame(), GetPlayer(), GetPosition, CGame::GetSoundScene(), DbgUI::InputFloat(), DbgUI::InputText(), DbgUI::PopID(), DbgUI::PushID_Int(), DbgUI::PushID_Str(), DbgUI::SameLine(), and DbgUI::Text().
OnInit() [1/9]
void PluginBase::OnInit () inline private
Definition at line 11 of file pluginbase.c.
    {
    }
Referenced by PluginManager::PluginsInit().
OnInit() [2/9]
override void PluginBase::OnInit () inline private
Definition at line 6 of file plugincameratools.c.
    {
        m_Instance = this;
    }
References m_Instance.
OnInit() [3/9]
override void PluginBase::OnInit () inline private
Definition at line 52 of file plugindeveloper.c.
    {
        super.OnInit();
        DeveloperFreeCamera.OnInit();
    }
References DeveloperFreeCamera::OnInit().
OnInit() [4/9]
override void PluginBase::OnInit () inline private
Definition at line 19 of file pluginuniversaltemperaturesourceclient.c.
    {
        #ifndef NO_GUI
        InitWidgets();
        #endif
    }
References InitWidgets().
OnInit() [5/9]
override void PluginBase::OnInit () inline private
Definition at line 64 of file plugindevelopersync.c.
    {
        super.OnInit();
        if ( GetGame().IsServer() )
        {
            //create timer
            m_UpdateTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
        }
    }
References CALL_CATEGORY_GAMEPLAY, GetGame(), and m_UpdateTimer.
OnInit() [6/9]
override void PluginBase::OnInit () inline private
Definition at line 37 of file pluginfilehandler.c.
    {
        super.OnInit();
    }
OnInit() [7/9]
override void PluginBase::OnInit () inline private
Definition at line 30 of file pluginkeybinding.c.
    {
        super.OnInit();
        m_KeyBindings   = new array<ref KeyBinding>;
        m_MouseBindings = new array<ref MouseBinding>;
        m_MouseButtons  = new array<ref MouseButtonInfo>;
        m_MouseButtons.Insert ( new MouseButtonInfo( MouseState.LEFT ) );
        m_MouseButtons.Insert ( new MouseButtonInfo( MouseState.RIGHT ) );
        m_MouseButtons.Insert ( new MouseButtonInfo( MouseState.MIDDLE ) );
        GetGame().GetUpdateQueue(CALL_CATEGORY_SYSTEM).Insert(this.OnFrame);
        //Keyboard Binds    |UI_ID                          |Key1                   |Key2               |Callback Plugin        |Callback Function              |Info Shrtcut                   |Info Description
        //------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        //                  |constants.h                    |constants.h            |constants.h        |only plugin name       |only function                  |                               |
        //                  |MENU_***                       |KeyCode.KC_***         |KeyCode.KC_***     |                       |in plugin                      |                               |
        //------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
        #ifdef DEVELOPER
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_F1      ,"PluginDeveloper"      ,"ToggleHelpScreen"             ,"[LCTRL]+[F1]"                 ,"Show/Hide help screen");
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_F2      ,"PluginDeveloper"      ,"ResetGUI"                     ,"[LCTRL]+[F2]"                 ,"Resets shown UI for testing purposes");
        RegisterKeyBind(     MENU_NONE|MENU_SCRIPTCONSOLE   ,KeyCode.KC_LCONTROL    ,KeyCode.KC_GRAVE   ,"PluginDeveloper"      ,"ToggleScriptConsole"          ,"[LCTRL]+[~]"                  ,"Show/Hide this script console");
        RegisterKeyBind(     MENU_NONE|MENU_SCRIPTCONSOLE   ,KeyCode.KC_RCONTROL    ,KeyCode.KC_GRAVE   ,"PluginDeveloper"      ,"ToggleScriptConsole"          ,"[RCTRL]+[~]"                  ,"Show/Hide this script console");
        RegisterKeyBind(     MENU_NONE|MENU_SCENE_EDITOR    ,KeyCode.KC_LCONTROL    ,KeyCode.KC_TAB     ,"PluginSceneManager"   ,"EditorToggle"                 ,"[LCTRL]+[TAB]"                ,"Show/Hide Scripted Scene Editor");
        RegisterKeyBind(     MENU_NONE|MENU_SCENE_EDITOR    ,KeyCode.KC_RCONTROL    ,KeyCode.KC_TAB     ,"PluginSceneManager"   ,"EditorToggle"                 ,"[RCTRL]+[TAB]"                ,"Show/Hide Scripted Scene Editor");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_V       ,"PluginDeveloper"      ,"SpawnFromClipboard"           ,"[Right Shift]"                ,"Spawn item from clipboard");
        #endif
        #ifdef DIAG_DEVELOPER
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_INSERT      ,-1                 ,"PluginDeveloper"      ,"TeleportAtCursor"             ,"[Insert]"                     ,"Teleport player to cursor position");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_HOME        ,-1                 ,"PluginDeveloper"      ,"ToggleFreeCamera"             ,"[Home]"                       ,"Toggle free camera and teleport player to its position");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_DIVIDE      ,-1                 ,"PluginDeveloper"      ,"ToggleFreeCameraBackPos"      ,"[Divide numeric]"             ,"Toggle free camera, no player teleport");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_NUMPAD9 ,"PluginDeveloperSync"  ,"ToggleFocus"                  ,"[LCtrl]+[NUMPAD9]"            ,"Toggle game focus");
        #endif
        #ifdef DEVELOPER
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_Z       ,"PluginDeveloper"      ,"SetDeveloperItemClient"       ,"Starts watching the item"     ,"Sets the target as Watched item for debug purposes");
        RegisterKeyBind(     MENU_SCRIPTCONSOLE             ,KeyCode.KC_PRIOR       ,-1                 ,"PluginDeveloper"      ,"ScriptHistoryBack"            ,"[Page Up]"                    ,"Debug Console => Script history back");
        RegisterKeyBind(     MENU_SCRIPTCONSOLE             ,KeyCode.KC_NEXT        ,-1                 ,"PluginDeveloper"      ,"ScriptHistoryNext"            ,"[Page Down]"                  ,"Debug Console => Script history next");
        RegisterKeyBind(     MENU_SCENE_EDITOR              ,KeyCode.KC_DELETE      ,-1                 ,"PluginSceneManager"   ,"DeleteSelectedObject"         ,"[Delete]"                     ,"Scene Editor => Delete current selected object");
        RegisterKeyBind(     MENU_SCENE_EDITOR              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_S       ,"PluginSceneManager"   ,"SceneSave"                    ,"[LCtrl]+[S]"                  ,"Scene Editor => Save Current Scene");
        RegisterKeyBind(     MENU_SCENE_EDITOR              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_D       ,"PluginSceneManager"   ,"SelectedObjectDuplicate"      ,"[LCtrl]+[D]"                  ,"Scene Editor => Duplicate current selected object");
        RegisterKeyBind(     MENU_SCENE_EDITOR              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_F       ,"PluginSceneManager"   ,"SelectedObjectFocus"          ,"[LCtrl]+[F]"                  ,"Scene Editor => Focus camera on selected object");
        RegisterKeyBind(     MENU_SCENE_EDITOR              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_E       ,"PluginSceneManager"   ,"RulerToggle"                  ,"[LCtrl]+[E]"                  ,"Scene Editor => Enable/Disable addition of ruler points");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_PRIOR   ,"PluginRecipesManager" ,"CallbackGenerateCache"        ,"[LCtrl]+[BACKSPACE]"          ,"PluginRecipesManager => Generate recipe cache and save it to file");
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_DECIMAL ,"PluginItemDiagnostic" ,"ToggleDebugWindowEvent"       ,"[LCtrl]+[DECIMAL]"            ,"Close the Item Debug window");
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_NUMPAD0 ,"PluginDayzPlayerDebug","ToggleDebugWindowEvent"       ,"[LCtrl]+[NUMPAD0]"            ,"Open/Close Player debug window");
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_DECIMAL ,"PluginDayzPlayerDebug","ToggleDebugWindowEventP"      ,"[LCtrl]+[DECIMAL]"            ,"Open/Close Player debug window");
        RegisterKeyBind(     MENU_ANY                       ,KeyCode.KC_LCONTROL    ,KeyCode.KC_I       ,"PluginDayZInfectedDebug","ToggleDebugWindowEvent"                         ,"[LCtrl]+[NUMPAD1]"            ,"Open/Close Infected debug window");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_SCROLL  ,"PluginNutritionDumper"        ,"CheckInit"                    ,"[LCtrl]+[SCROLL LOCK]"        ,"Enable Door Ruler");
        RegisterKeyBind(     MENU_NONE                      ,KeyCode.KC_LCONTROL    ,KeyCode.KC_RBRACKET,"PluginCharPlacement"  ,"CheckInit"                    ,"[LCtrl]+[)]"                  ,"Enable CharPlacer");
        RegisterKeyBind(     MENU_NONE|MENU_CAMERA_TOOLS    ,KeyCode.KC_LCONTROL    ,KeyCode.KC_K       ,"PluginCameraTools"    ,"ToggleCameraTools"            ,"[LCtrl]+[K]"                  ,"Toggle Camera Recording Tools");
        RegisterKeyBind(     MENU_CAMERA_TOOLS              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_S       ,"PluginCameraTools"    ,"Save"                         ,"[X]"                          ,"Recording Tools => Start Recording Camera Path");
        RegisterKeyBind(     MENU_CAMERA_TOOLS              ,KeyCode.KC_P           ,-1                 ,"PluginCameraTools"    ,"PlayPause"                    ,"[C]"                          ,"Recording Tools => Stop Recording Camera Path");
        RegisterKeyBind(     MENU_CAMERA_TOOLS              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_Q       ,"PluginCameraTools"    ,"AddKeyframe"                  ,"[C]"                          ,"Recording Tools => Add Camera Point");
        RegisterKeyBind(     MENU_CAMERA_TOOLS              ,KeyCode.KC_LCONTROL    ,KeyCode.KC_E       ,"PluginCameraTools"    ,"DeleteKeyframe"               ,"[V]"                          ,"Recording Tools => Play Camera Line");
        //--------------------------------------------------------------------------------------------------------------------------------------------------------------
        // Mouses Binds     |UI_ID              |Mouse Button   |Mouse Event            |Callback Plugin        |Callback Function          |Info Shrtcut           |Info Description
        //----------------------------------------------------------------------------------------------------------------------------------------------------------------
        //                  |constants.h        |MouseState.LEFT        |MB_EVENT_CLICK         |only plugin name       |only function              |                       |
        //                  |MENU_***           |MouseState.RIGHT       |MB_EVENT_DOUBLECLICK   |                       |in plugin                  |                       |
        //                                      |MouseState.MIDDLE      |MB_EVENT_DRAG          |                       |                           |                       |
        //                                      |                       |MB_EVENT_RELEASE       |                       |                           |                       |
        //--------------------------------------------------------------------------------------------------------------------------------------------------------------
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.LEFT        ,MB_EVENT_CLICK         ,"PluginSceneManager"   ,"Event_OnClick"            ,"[LMB] Click"          ,"Mission Editor => Select object in scene");
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.LEFT        ,MB_EVENT_DOUBLECLICK   ,"PluginSceneManager"   ,"Event_OnDoubleClick"      ,"[LMB] Double Click"   ,"Mission Editor => Craete new object in scene");
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.LEFT        ,MB_EVENT_DRAG          ,"PluginSceneManager"   ,"Event_OnDrag"             ,"[LMB] Hold"           ,"Mission Editor => Moving with selected object");
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.MIDDLE      ,MB_EVENT_CLICK         ,"PluginSceneManager"   ,"Event_OnClickMiddle"      ,"[MMB] Click"          ,"Mission Editor => Link clicked object with selected object");
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.RIGHT       ,MB_EVENT_PRESS         ,"PluginSceneManager"   ,"FreeCameraControlEnable"  ,"[RMB] Hold"           ,"Mission Editor => Enable camera movement");
        RegisterMouseBind(  MENU_SCENE_EDITOR   ,MouseState.RIGHT       ,MB_EVENT_RELEASE       ,"PluginSceneManager"   ,"FreeCameraControlDisable" ,"[RMB] Release"        ,"Mission Editor => Disable camera movement");
        RegisterMouseBind(  MENU_NONE           ,MouseState.LEFT        ,MB_EVENT_CLICK         ,"PluginDayZCreatureAIDebug","Event_OnClick"        ,"[LMB] Click"          ,"DayZCreature graph debug => Capture entity during capture mode");
        RegisterMouseBind(  MENU_CAMERA_TOOLS   ,MouseState.RIGHT       ,MB_EVENT_RELEASE       ,"PluginCameraTools"    ,"CursorShow"               ,"[LMB] Click"          ,"DayZCreature graph debug => Capture entity during capture mode");
        // TO DO: (Boris V.) Remove the following commented-out mouse binds when weapon particles can be implemented properly. Also remove the events they call.
        //RegisterMouseBind(    MENU_NONE           ,MouseState.LEFT        ,MB_EVENT_PRESS         ,"PluginDeveloper"      ,"MuzzleParticleTestStart"  ,"[LMB] Hold"           ,"Debug particle");
        //RegisterMouseBind(    MENU_NONE           ,MouseState.LEFT        ,MB_EVENT_RELEASE       ,"PluginDeveloper"      ,"MuzzleParticleTestEnd"    ,"[LMB] Release"        ,"Debug particle2");
        #endif
        //--------------------------------------------------------------------------------------------------------------------------------------------------------------
    }
References CALL_CATEGORY_SYSTEM, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, MB_EVENT_DRAG, MB_EVENT_PRESS, MB_EVENT_RELEASE, MENU_ANY, MENU_CAMERA_TOOLS, MENU_NONE, MENU_SCENE_EDITOR, and MENU_SCRIPTCONSOLE.
OnInit() [8/9]
override void PluginBase::OnInit () inline private
Definition at line 46 of file pluginscenemanager.c.
    {
        m_ModuleDeveloper           = PluginDeveloper.Cast( GetPlugin(PluginDeveloper) );
        m_ModuleConfigScene         = PluginConfigScene.Cast( GetPlugin(PluginConfigScene) );
        m_ModuleConfigDebugProfile  = PluginConfigDebugProfile.Cast( GetPlugin(PluginConfigDebugProfile) );
        //Ruler
        m_RulerActivated = false;
        m_RulerPoints   = new array<vector>;
        m_RulerLines    = new array<Shape>;
        m_RulerSpheres  = new array<Shape>;
    }
References GetPlugin(), and m_ModuleDeveloper.
OnInit() [9/9]
override void PluginBase::OnInit () inline private
Definition at line 3 of file pluginsounddebug.c.
    {
        m_TickTimer = new Timer();
        m_TickTimer.Run(0.1, this, "OnGUITimer", NULL, true);
    }
References m_TickTimer.
OnKeyPress()
void PluginBase::OnKeyPress (int key) inline private
Definition at line 125 of file pluginkeybinding.c.
    {
        //Print("OnKeyPress "+ key );
        for ( int i = 0; i < m_KeyBindings.Count(); ++i )
        {
            KeyBinding key_binding = m_KeyBindings.Get(i);
            if ( !IsCurrentUIPageValid( key_binding.GetUIMenuID() ) )
            {
                continue;
            }
            bool key1_match = false;
            bool key2_match = false;
            if ( key_binding.GetKey1() > -1 )
            {
                if ( IsKeyPressed(key_binding.GetKey1()) )
                {
                    // Key1 is down
                    key1_match = true;
                }
            }
            else
            {
                // Key1 is not set
                key1_match = true;
            }
            if ( key_binding.GetKey2() > -1 )
            {
                if ( IsKeyPressed(key_binding.GetKey2()) )
                {
                    // Key2 is down
                    key2_match = true;
                }
            }
            else
            {
                // Key2 is not set
                key2_match = true;
            }
            if ( key1_match && key2_match )
            {
                //Log( "Call Method -> key press: " + itoa(key) + " " + key_binding.GetInfoDescription() );
                PluginBase m = GetPlugin(key_binding.GetCallbackTarget().ToType());
                GetGame().GameScript.CallFunction(m, key_binding.GetCallbackFunction(), NULL, 0);
                break;
            }
        }
    }
References ScriptModule::CallFunction(), CGame::GameScript, KeyBinding::GetCallbackFunction(), KeyBinding::GetCallbackTarget(), GetGame(), KeyBinding::GetKey1(), KeyBinding::GetKey2(), GetPlugin(), KeyBinding::GetUIMenuID(), and string::ToType().
OnKeyRelease()
void PluginBase::OnKeyRelease (int key) inline private
Definition at line 184 of file pluginkeybinding.c.
    {
    }
OnMouse()
protected void PluginBase::OnMouse (int event_id, int button) inline private
Definition at line 336 of file pluginkeybinding.c.
    {
        for ( int i = 0; i < m_MouseBindings.Count(); ++i )
        {
            MouseBinding mouse_binding = m_MouseBindings.Get(i);
            if ( mouse_binding.GetButtonID() == button && mouse_binding.GetMouseEvent() == event_id )
            {
                if ( IsCurrentUIPageValid( mouse_binding.GetUIMenuID() ) )
                {
                    PluginBase m = GetPlugin(mouse_binding.GetCallbackTarget().ToType());
                    GetGame().GameScript.CallFunction(m, mouse_binding.GetCallbackFunction(), NULL, 0);
                }
            }
        }
    }
References ScriptModule::CallFunction(), CGame::GameScript, MouseBinding::GetButtonID(), MouseBinding::GetCallbackFunction(), MouseBinding::GetCallbackTarget(), GetGame(), MouseBinding::GetMouseEvent(), GetPlugin(), MouseBinding::GetUIMenuID(), and string::ToType().
OnMouseButtonPress()
void PluginBase::OnMouseButtonPress (int button) inline private
Definition at line 191 of file pluginkeybinding.c.
    {
        MouseButtonInfo button_info = GetMouseButtonInfo( button );
        if (button_info == NULL) return;
        button_info.Press();
    //Log("****************************");
    //Log(" MB_EVENT_PRESS");
        OnMouse( MB_EVENT_PRESS, button );
    }
References MB_EVENT_PRESS, and MouseButtonInfo::Press().
OnMouseButtonRelease()
void PluginBase::OnMouseButtonRelease (int button) inline private
Definition at line 206 of file pluginkeybinding.c.
    {
        MouseButtonInfo button_info = GetMouseButtonInfo( button );
        if (button_info == NULL) return;
        int time_curr           = GetGame().GetTime();
        int time_last_press     = button_info.GetTimeLastPress();
        int time_last_release   = button_info.GetTimeLastRelease();
        int time_delta_press    = time_curr - time_last_press;
        int time_delta_relase   = time_curr - time_last_release;
        if ( time_delta_relase < DOUBLE_CLICK_TIME )
        {
    //Log(" DOUBLE_CLICK_TIME ");
            OnMouse( MB_EVENT_DOUBLECLICK, button );
        }
        else if ( time_delta_press < CLICK_TIME )
        {
    //Log(" MB_EVENT_CLICK ");
            OnMouse( MB_EVENT_CLICK, button );
        }
    //Log(" MB_EVENT_RELEASE");
        OnMouse( MB_EVENT_RELEASE, button );
        button_info.Release();
    }
References GetGame(), CGame::GetTime(), MouseButtonInfo::GetTimeLastPress(), MouseButtonInfo::GetTimeLastRelease(), MB_EVENT_CLICK, MB_EVENT_DOUBLECLICK, MB_EVENT_RELEASE, and MouseButtonInfo::Release().
OnMouseWheel()
void PluginBase::OnMouseWheel (int wheel) inline private
Definition at line 70 of file pluginscenemanager.c.
    {
        if ( !IsMouseInScene() )
        {
            return;
        }
        if ( GetSelectedSceneObject() )
        {
            GetSelectedSceneObject().AddRotation(GetRotationAngle() * wheel);
        }
        EditorUpdate();
    }
OnPlacementComplete()
void PluginBase::OnPlacementComplete (Man player, ItemBase item) inline private
Definition at line 287 of file pluginadminlog.c.
    {
        if ( m_PlacementFilter == 1 )
        {
            m_Source = PlayerBase.Cast( player );
            m_PlayerPrefix = this.GetPlayerPrefix( m_Source , m_Source.GetIdentity() );
            m_DisplayName = item.GetDisplayName();
            if ( m_DisplayName == "" )
            {
                LogPrint( m_PlayerPrefix + " placed unknown object" );
            }
            else
            {
                LogPrint( m_PlayerPrefix + " placed " + m_DisplayName );
            }
        }
    }
References GetPlayerPrefix(), and LogPrint().
OnRequestReceived() [1/2]
void PluginBase::OnRequestReceived (PlayerBase player, bool enable) inline private
Definition at line 116 of file pluginremoteplayerdebugserver.c.
    {
        int index = m_ClientList.Find(player);
        if(enable)
        {
            m_ClientList.Insert(player);
            SetWatching(true);
        }
        else if (index != -1 && m_ClientList.Count() != 0)
        {
            m_ClientList.Remove(index);
        }
        if( m_ClientList.Count() == 0 )
        {
            SetWatching(false);
        }
    }
References SetWatching().
Referenced by OnRPC().
OnRequestReceived() [2/2]
void PluginBase::OnRequestReceived (PlayerBase player, bool enable) inline private
Definition at line 101 of file pluginuniversaltemperaturesourceserver.c.
    {
        int index = m_ClientList.Find(player);
        if (enable)
        {
            m_ClientList.Insert(player);
        }
        else if (index != -1 && m_ClientList.Count() > 0)
        {
            m_ClientList.Remove(index);
        }
    }
OnRPC() [1/5]
void PluginBase::OnRPC (ParamsReadContext ctx) inline private
Definition at line 230 of file pluginuniversaltemperaturesourceclient.c.
    {
        //Debug.Log("OnRPC called", "PluginUniversalTemperatureSourceClient");
        //PrintedDebug();
        ctx.Read(m_UTemperatureSourceDebugs);
    }
References Serializer::Read().
OnRPC() [2/5]
void PluginBase::OnRPC (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 136 of file pluginremoteplayerdebugserver.c.
    {
        bool enable;
        ctx.Read(enable);
        OnRequestReceived(player, enable);
    }
References OnRequestReceived(), and Serializer::Read().
OnRPC() [3/5]
void PluginBase::OnRPC (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 115 of file pluginuniversaltemperaturesourceserver.c.
    {
        bool enable;
        ctx.Read(enable);
        OnRequestReceived(player, enable);
    }
References OnRequestReceived(), and Serializer::Read().
OnRPC() [4/5]
void PluginBase::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 59 of file plugindeveloper.c.
    {
    #ifdef DIAG_DEVELOPER
        switch (rpc_type)
        {
            case ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND:
            {
                OnRPCSpawnEntityOnGround(player, ctx); break;
            }
            case ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND_PATTERN_GRID:
            {
                OnRPCSpawnEntityOnGroundPatternGrid(player, ctx); break;
            }
            case ERPCs.DEV_RPC_SPAWN_ITEM_ON_CURSOR:
            {
                OnRPCSpawnEntityOnCursorDir(player, ctx); break;
            }
            case ERPCs.DEV_RPC_SPAWN_ITEM_IN_INVENTORY:
            {
                OnRPCSpawnEntity(player, ctx); break;
            }
            case ERPCs.DEV_RPC_CLEAR_INV:
            {
                OnRPCClearInventory(player); break;
            }
            case ERPCs.DEV_RPC_SEND_SERVER_LOG:
            {
                OnRPCServerLogRecieved( ctx ); break;
            }
            case ERPCs.RPC_SYNC_SCENE_OBJECT:
            {
                OnRPCSyncSceneObject( ctx ); break;
            }
            case ERPCs.DEV_RPC_PLUGIN_DZCREATURE_DEBUG:
            {
                OnRPCPluginDayzCreatureDebug(player, rpc_type, ctx); break;
            }
            case ERPCs.DEV_RPC_SPAWN_PRESET:
            {
                HandlePresetSpawn(player,ctx); break;
            }
            case ERPCs.DEV_RPC_SET_TIME:
            {
                HandleSetTime(player,ctx); break;
            }
        }
        DeveloperTeleport.OnRPC(player, rpc_type, ctx);
    #endif
    }
References HandlePresetSpawn(), HandleSetTime(), DeveloperTeleport::OnRPC(), OnRPCClearInventory(), OnRPCPluginDayzCreatureDebug(), OnRPCServerLogRecieved(), OnRPCSpawnEntity(), OnRPCSpawnEntityOnCursorDir(), OnRPCSpawnEntityOnGround(), OnRPCSpawnEntityOnGroundPatternGrid(), and OnRPCSyncSceneObject().
OnRPC() [5/5]
void PluginBase::OnRPC (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 252 of file plugindevelopersync.c.
    {
        if ( !GetGame().IsDebug() )
        {
            return;
        }
        switch ( rpc_type )
        {
            case ERPCs.DEV_STATS_UPDATE:
            {
                EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_STATS_UPDATE, player ); break;
            }
            case ERPCs.DEV_LEVELS_UPDATE:
            {
                EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_LEVELS_UPDATE, player ); break;
            }
            case ERPCs.DEV_MODS_UPDATE:
            {
                EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_MODS_UPDATE, player ); break;
            }
            case ERPCs.DEV_AGENTS_UPDATE:
            {
                EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_AGENTS_UPDATE, player ); break;
            }
            case ERPCs.DEV_STOMACH_UPDATE:
            {
                EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_STOMACH_UPDATE, player ); break;
            }
            case ERPCs.DEV_RPC_STATS_DATA:
            {
                OnRPCStats( ctx ); break;
            }
            case ERPCs.DEV_RPC_LEVELS_DATA:
            {
                OnRPCLevels( ctx ); break;
            }
            case ERPCs.DEV_RPC_MODS_DATA:
            {
                OnRPCMods( ctx ); break;
            }
            case ERPCs.DEV_RPC_MODS_DATA_DETAILED:
            {
                OnRPCModsDetailed( ctx ); break;
            }
            case ERPCs.DEV_RPC_AGENTS_DATA:
            {
                OnRPCAgents( ctx ); break;
            }
            case ERPCs.DEV_RPC_STOMACH_DATA:
            {
                OnRPCStomach( ctx ); break;
            }
            case ERPCs.DEV_RPC_MODS_ACTIVATE:
            {
                ActivateModifier( GetRPCModifierID( ctx ), player ); break;
            }
            case ERPCs.DEV_RPC_MODS_DETAILED:
            {
                RequestDetailedInfo( GetRPCModifierID( ctx ), player ); break;
            }
            case ERPCs.DEV_RPC_MODS_DEACTIVATE:
            {
                DeactivateModifier( GetRPCModifierID( ctx ), player ); break;
            }
            case ERPCs.DEV_RPC_MODS_LOCK:
            {
                int id;
                bool lock;
                GetRPCModifierLock( ctx, id, lock );
                LockModifier( id, lock, player ); break;
            }
            case ERPCs.DEV_RPC_MODS_RESET:
            {
                player.GetModifiersManager().DeactivateAllModifiers();
                break;
            }
            case ERPCs.DEV_RPC_STATS_RESET:
            {
                player.GetPlayerStats().ResetAllStats();
                break;
            }
            case ERPCs.DEV_RPC_STAT_SET:
            {
                OnRPCStatSet(ctx, player);
                break;
            }
            case ERPCs.DEV_TEMP_UPDATE:
            {
                OnRPCTemp(ctx, player);
                break;
            }
        }
    }
References ActivateModifier(), DeactivateModifier(), EnableUpdate(), GetGame(), GetRPCModifierID(), GetRPCModifierLock(), GetRPCUpdateState(), LockModifier(), OnRPCAgents(), OnRPCLevels(), OnRPCMods(), OnRPCModsDetailed(), OnRPCStats(), OnRPCStatSet(), OnRPCStomach(), OnRPCTemp(), and RequestDetailedInfo().
OnRPCAgents()
void PluginBase::OnRPCAgents (ParamsReadContext ctx) inline private
Definition at line 752 of file plugindevelopersync.c.
    {
        //clear values
        m_PlayerAgentsSynced.Clear();
        Param3<string, string, int> p3 = new Param3<string, string, int>( "", "" ,0 );
        Param1<int> p1 = new Param1<int>(0);
        //get param count
        int param_count = 0;
        if ( ctx.Read(p1) )
        {
            param_count = p1.param1;
        }
        //read values and set
        for ( int i = 0; i < param_count; i++ )
        {
            ctx.Read(p3);
            m_PlayerAgentsSynced.Insert( new SyncedValueAgent( p3.param1, p3.param2, p3.param3 ) );
        }
    }
References Serializer::Read(), and SyncedValueAgent().
Referenced by OnRPC().
OnRPCClearInventory()
void PluginBase::OnRPCClearInventory (PlayerBase player) inline private
Definition at line 233 of file plugindeveloper.c.
    {
        ClearInventory(player);
    }
References ClearInventory().
Referenced by OnRPC().
OnRPCLevels()
void PluginBase::OnRPCLevels (ParamsReadContext ctx) inline private
Definition at line 515 of file plugindevelopersync.c.
    {
        //clear values
        m_PlayerLevelsSynced.Clear();
        Param3<string, float, float> p3 = new Param3<string, float, float>( "", 0,0 );
        //get param count
        int param_count = 0;
        if ( ctx.Read(p3) )
        {
            param_count = p3.param2;
        }
        //read values and set
        for ( int i = 0; i < param_count; i++ )
        {
            if ( ctx.Read(p3) )
                m_PlayerLevelsSynced.Insert( new SyncedValueLevel( p3.param1, p3.param2, p3.param3 ) );
        }
    }
References Serializer::Read(), and SyncedValueLevel().
Referenced by OnRPC().
OnRPCMods()
void PluginBase::OnRPCMods (ParamsReadContext ctx) inline private
Definition at line 591 of file plugindevelopersync.c.
    {
        //clear values
        m_PlayerModsSynced.Clear();
        //ref Param3<string, float, bool> p = new Param3<string, float, bool>( "", 0, false );
        Param1<int> p1 = new Param1<int>(0);
        Param4<int, string, bool, bool> p4 = new Param4<int, string, bool, bool>( 0,"", false, false );
        //get param count
        int param_count = 0;
        if ( ctx.Read(p1) )
        {
            param_count = (int) p1.param1;
        }
        //read values and set
        for ( int i = 0; i < param_count; i++ )
        {
            if (ctx.Read(p4))
            {
                m_PlayerModsSynced.Insert( new SyncedValueModifier( p4.param1, p4.param2, p4.param3, p4.param4 ) );
            }
        }
    }
References int, and Serializer::Read().
Referenced by OnRPC().
OnRPCModsDetailed()
void PluginBase::OnRPCModsDetailed (ParamsReadContext ctx) inline private
Definition at line 616 of file plugindevelopersync.c.
    {
        Param1<string> p1 = new Param1<string>("");
        //get param count
        if ( ctx.Read(p1) )
        {
            m_PlayerModsDetailedSynced = p1.param1;
        }
    }
References Serializer::Read().
Referenced by OnRPC().
OnRPCPluginDayzCreatureDebug()
void PluginBase::OnRPCPluginDayzCreatureDebug (PlayerBase player, int rpc_type, ParamsReadContext ctx) inline private
Definition at line 156 of file plugindeveloper.c.
    {
        PluginDayZCreatureAIDebug pluginDZCreatureDebug = PluginDayZCreatureAIDebug.Cast( GetPlugin( PluginDayZCreatureAIDebug ) );
        if (pluginDZCreatureDebug)
        {
            pluginDZCreatureDebug.OnRpc(player, rpc_type, ctx);
        }
    }
References GetPlugin(), and PluginDayZCreatureAIDebug().
Referenced by OnRPC().
OnRPCServerLogRecieved()
void PluginBase::OnRPCServerLogRecieved (ParamsReadContext ctx) inline private
Definition at line 223 of file plugindeveloper.c.
    {
        Param1<string> param = new Param1<string>( "" );
        if ( ctx.Read(param) && param.param1 != "" )
        {
            Debug.ReceivedLogMessageFromServer(param.param1);
        }
    }
References Serializer::Read(), and Debug::ReceivedLogMessageFromServer().
Referenced by OnRPC().
OnRPCSpawnEntity()
void PluginBase::OnRPCSpawnEntity (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 265 of file plugindeveloper.c.
    {
        #ifdef DEVELOPER
        Param5<string, float, float,bool, string> p = new Param5<string, float, float, bool, string>("", 0, 0, false, "");
        if ( ctx.Read(p) )
        {
            EntityAI ent = SpawnEntityInInventory(player, p.param1, p.param2,  p.param3, p.param4);
            if (p.param5)
            {
                if (player.m_PresetSpawned)
                {
                    player.m_PresetSpawned = false;
                    player.m_PresetItems.Clear();
                }
                if (ent)
                {
                    player.m_PresetItems.Insert(ent);
                }
            }
        }
        #endif
    }
References Serializer::Read(), and SpawnEntityInInventory().
Referenced by OnRPC().
OnRPCSpawnEntityOnCursorDir()
void PluginBase::OnRPCSpawnEntityOnCursorDir (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 239 of file plugindeveloper.c.
    {
        Param6<string, float, float, float, bool, string> p = new Param6<string, float, float, float, bool, string>("", 0, 0, 0, false, "");
        if ( ctx.Read(p) )
        {
            SpawnEntityOnCursorDir(player, p.param1, p.param2, p.param3, p.param4, p.param5, p.param6);
        }
    }
References Serializer::Read(), and SpawnEntityOnCursorDir().
Referenced by OnRPC().
OnRPCSpawnEntityOnGround()
void PluginBase::OnRPCSpawnEntityOnGround (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 248 of file plugindeveloper.c.
    {
        Param4<string, float, float, vector> p = new Param4<string, float, float, vector>("", 0, 0, "0 0 0");
        if ( ctx.Read(p) )
        {
            SpawnEntityOnGroundPos(player, p.param1, p.param2,  p.param3,  p.param4);
        }
    }
References Serializer::Read(), and SpawnEntityOnGroundPos().
Referenced by OnRPC().
OnRPCSpawnEntityOnGroundPatternGrid()
void PluginBase::OnRPCSpawnEntityOnGroundPatternGrid (PlayerBase player, ParamsReadContext ctx) inline private
Definition at line 257 of file plugindeveloper.c.
    {
        auto p = new Param8<string,int, float, float, int, int, float, float>("",0,0,0,0,0,0,0);
        if ( ctx.Read(p) )
        {
            SpawnEntityOnGroundPatternGrid(player, p.param1, p.param2, p.param3, p.param4, p.param5, p.param6, p.param7, p.param8);
        }
    }
References Serializer::Read(), and SpawnEntityOnGroundPatternGrid().
Referenced by OnRPC().
OnRPCStats()
void PluginBase::OnRPCStats (ParamsReadContext ctx) inline private
Definition at line 426 of file plugindevelopersync.c.
    {
        //clear values
        m_PlayerStatsSynced.Clear();
        Param1<int> p_count = new Param1<int>(0);
        Param3<string, float, float> p = new Param3<string, float, float>( "", 0, 0 );
        //get param count
        int param_count = 0;
        if ( ctx.Read(p_count) )
        {
            param_count = p_count.param1;
        }
        //read values and set
        for ( int i = 0; i < param_count; i++ )
        {
            ctx.Read(p);
            m_PlayerStatsSynced.Insert( new SyncedValue( p.param1, p.param2, false, p.param3 ) );
        }
    }
References Serializer::Read().
Referenced by OnRPC().
OnRPCStatSet()
void PluginBase::OnRPCStatSet (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 472 of file plugindevelopersync.c.
    {
        Param2<string, float> p = new Param2<string, float>( "", 0 );
        if ( ctx.Read(p) )
        {
            for ( int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++ )
            {
                string label = player.m_PlayerStats.GetPCO().Get().Get( i ).GetLabel();
                if ( label == p.param1 )
                {
                    player.m_PlayerStats.GetPCO().Get().Get( i).SetByFloatEx(p.param2);
                }
            }
        }
    }
References Count, Get(), and Serializer::Read().
Referenced by OnRPC().
OnRPCStomach()
void PluginBase::OnRPCStomach (ParamsReadContext ctx) inline private
Definition at line 793 of file plugindevelopersync.c.
    {
        //clear values
        m_PlayerStomachSynced.Clear();
        Param1<int> p1 = new Param1<int>(0);
        int param_count = 0;
        if ( ctx.Read(p1) )
        {
            param_count = p1.param1;
        }
        if (param_count)
        {
            //invidividual stomach items
            for ( int i = 0; i < param_count; i++ )
            {
                Param4<int,int,int,float> p4 = new Param4<int,int,int,float>(0,0,0,0);
                ctx.Read(p4);
                m_PlayerStomachSynced.Insert(p4);
            }
            //volume
            Param1<float> p1b = new Param1<float>(0);
            ctx.Read(p1b);
            m_PlayerStomachSynced.Insert(p1b);
        }
    }
References Serializer::Read().
Referenced by OnRPC().
OnRPCSyncSceneObject()
void PluginBase::OnRPCSyncSceneObject (ParamsReadContext ctx) inline private
Definition at line 142 of file plugindeveloper.c.
    {
        Param3<string, EntityAI, Param> par = new Param3<string, EntityAI, Param>( "", NULL, new Param );
        if ( ctx.Read( par ) )
        {
            PluginSceneManager module_scene_editor = PluginSceneManager.Cast( GetPlugin( PluginSceneManager ) );
            SceneData   scene_data = module_scene_editor.GetLoadedScene();
            SceneObject scene_object = scene_data.GetSceneObjectByEntityAI( par.param2 );
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallByName( scene_object, par.param1, par.param3 );
        }
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallByName(), CGame::GetCallQueue(), GetGame(), GetPlugin(), SceneData::GetSceneObjectByEntityAI(), and Serializer::Read().
Referenced by OnRPC().
OnRPCTemp()
void PluginBase::OnRPCTemp (ParamsReadContext ctx, PlayerBase player) inline private
Definition at line 717 of file plugindevelopersync.c.
    {
        if (GetGame().IsServer() && GetGame().IsMultiplayer())
        {
            EnableUpdate( GetRPCUpdateState( ctx ), ERPCs.DEV_TEMP_UPDATE, player );
        }
        else if (!GetGame().IsMultiplayer() || GetGame().IsClient())
        {
            if ( ctx.Read(CachedObjectsParams.PARAM1_STRING) )
            {
                m_EnvironmentDebugMessage = CachedObjectsParams.PARAM1_STRING.param1;
            }
        }
    }
References EnableUpdate(), GetGame(), GetRPCUpdateState(), CachedObjectsParams::PARAM1_STRING, and Serializer::Read().
Referenced by OnRPC().
OnSetFreeCameraEvent()
void PluginBase::OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera) inline private
Definition at line 289 of file plugindeveloper.c.
    {
        DeveloperFreeCamera.OnSetFreeCameraEvent( player, camera );
    }
References DeveloperFreeCamera::OnSetFreeCameraEvent().
OnSpawnErrorReport()
void PluginBase::OnSpawnErrorReport (string name) inline private
Definition at line 294 of file plugindeveloper.c.
    {
        PrintString("PluginDeveloper.SpawnEntity() Warning- Cant spawn object: " + name);
        //DumpStack();
        PrintString("PluginDeveloper.SpawnEntity() Warning END");
    }
References name, and PrintString().
Referenced by SpawnEntityAsAttachment(), SpawnEntityInInventory(), SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
OnUIEditorClosed()
void PluginBase::OnUIEditorClosed () inline private
Definition at line 102 of file pluginscenemanager.c.
    {
        m_IsOpen = false;
        FreeCameraControlEnable();
        m_ModuleDeveloper.ToggleFreeCameraBackPos();
        EditorUpdate();
    }
References m_ModuleDeveloper.
OnUIEditorOpened()
void PluginBase::OnUIEditorOpened () inline private
Definition at line 88 of file pluginscenemanager.c.
    {
        m_IsOpen = true;
        DeveloperFreeCamera.EnableFreeCameraSceneEditor( PlayerBase.Cast( GetGame().GetPlayer() ) );
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(this.FreeCameraControlDisable);
        EditorUpdate();
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, DeveloperFreeCamera::EnableFreeCameraSceneEditor(), CGame::GetCallQueue(), GetGame(), and GetPlayer().
OnUpdate() [1/7]
void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 15 of file pluginbase.c.
    {
    }
Referenced by PluginManager::MainOnUpdate().
OnUpdate() [2/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 46 of file plugincharplacement.c.
    {
        if(!m_Initialized) return;
        if(!FreeDebugCamera.GetInstance().IsActive()) return;
        if(!m_Character) return;
        m_camera_orientation = FreeDebugCamera.GetInstance().GetOrientation();
        m_camera_orientation[1] = 1;
        FreeDebugCamera.GetInstance().SetOrientation(m_camera_orientation); //remove to unlock vertical axis
        m_cam_pos = FreeDebugCamera.GetInstance().GetPosition();
        m_character_pos = m_Character.GetPosition();
        m_camera_dir = FreeDebugCamera.GetInstance().GetDirection();
        m_camera_dir.Normalize();
        m_Character.SetPosition(CalculatePos());//(FreeDebugCamera.GetInstance().GetPosition() + ( m_camera_dir * 2) );
        m_demoRot[0] = Math.Atan2(-m_camera_dir[0], -m_camera_dir[2]) * Math.RAD2DEG;
        m_Character.SetOrientation(m_demoRot);//(FreeDebugCamera.GetInstance().GetPosition() - m_demoPos);
    }
References Math::Atan2(), CalculatePos(), m_Initialized, vector::Normalize(), and Math::RAD2DEG.
OnUpdate() [3/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 23 of file plugindoorruler.c.
    {
        if(!m_Initialized) return;
        if(!FreeDebugCamera.GetInstance().IsActive()) return;
        if(!m_Ruler) return;
        vector cam_pos = FreeDebugCamera.GetInstance().GetPosition();
        vector ruler_pos = m_Ruler.GetPosition();
        vector camera_dir = FreeDebugCamera.GetInstance().GetDirection();
        camera_dir.Normalize();
        m_Ruler.SetPosition(FreeDebugCamera.GetInstance().GetPosition() + ( camera_dir * 2) );
        m_Ruler.SetAngles(FreeDebugCamera.GetInstance().GetAngles());
    }
References m_Initialized, and vector::Normalize().
OnUpdate() [4/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 14 of file pluginremoteplayerdebugserver.c.
    {
        #ifdef SERVER
        if( m_ClientList.Count()!=0 )
        {
            m_AccuTime+=delta_time;
            if( m_AccuTime > INTERVAL )
            {
                m_AccuTime = 0;
                SendDebug();
            }
        }
        #endif
    }
References SendDebug().
OnUpdate() [5/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 26 of file pluginuniversaltemperaturesourceclient.c.
    {
        #ifndef NO_GUI
        if (!m_Player)
        {
            return;
        }
        UpdateStatWidgets();
        DrawDebugs();
        #endif
    }
References DrawDebugs(), m_Player, and UpdateStatWidgets().
OnUpdate() [6/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 17 of file pluginuniversaltemperaturesourceserver.c.
    {
        if (m_ClientList.Count() > 0)
        {
            m_AccuTime += delta_time;
            if (m_AccuTime > INTERVAL)
            {
                m_AccuTime = 0;
                SendDebug();
            }
        }
    }
References SendDebug().
OnUpdate() [7/7]
override void PluginBase::OnUpdate (float delta_time) inline private
Definition at line 9 of file pluginsounddebug.c.
    {
        ;
    }
PlayerHitBy()
void PluginBase::PlayerHitBy (TotalDamageResult damageResult, int damageType, PlayerBase player, EntityAI source, int component, string dmgZone, string ammo) inline private
Definition at line 167 of file pluginadminlog.c.
    {
        if ( player && source )
        {
            m_PlayerPrefix = this.GetPlayerPrefix( player ,  player.GetIdentity() ) + "[HP: " + player.GetHealth().ToString() + "]";
            m_HitMessage = this.GetHitMessage( damageResult, component, dmgZone, ammo );
            switch ( damageType )
            {
                case DT_CLOSE_COMBAT:   // Player melee, animals, infected
                    if ( m_HitFilter != 1 && ( source.IsZombie() || source.IsAnimal() ) )  // Infected & Animals
                    {
                        m_DisplayName = source.GetDisplayName();
                        LogPrint( m_PlayerPrefix + " hit by " + m_DisplayName + m_HitMessage );
                    }
                    else if ( source.IsPlayer() )               // Fists
                    {
                        m_Source = PlayerBase.Cast( source );
                        m_PlayerPrefix2 = this.GetPlayerPrefix( m_Source ,  m_Source.GetIdentity() );
                        LogPrint( m_PlayerPrefix + " hit by " + m_PlayerPrefix2 + m_HitMessage );
                    }
                    else if ( source.IsMeleeWeapon() )          // Melee weapons
                    {
                        m_ItemInHands = source.GetDisplayName();
                        m_Source = PlayerBase.Cast( source.GetHierarchyParent() );
                        m_PlayerPrefix2 = this.GetPlayerPrefix( m_Source ,  m_Source.GetIdentity() );
                        LogPrint( m_PlayerPrefix + " hit by " + m_PlayerPrefix2 + m_HitMessage + " with " + m_ItemInHands );
                    }
                    else
                    {
                        m_DisplayName = source.GetType();
                        LogPrint( m_PlayerPrefix + " hit by " + m_DisplayName + m_HitMessage );
                    }
                    break;
                case DT_FIRE_ARM:   // Player ranged
                    if ( source.IsWeapon() )
                    {
                        m_ItemInHands = source.GetDisplayName();
                        m_Source = PlayerBase.Cast( source.GetHierarchyParent() );
                        m_PlayerPrefix2 = this.GetPlayerPrefix( m_Source ,  m_Source.GetIdentity() );
                        m_Distance = vector.Distance( player.GetPosition(), m_Source.GetPosition() );
                        LogPrint( m_PlayerPrefix + " hit by " + m_PlayerPrefix2 + m_HitMessage + " with " + m_ItemInHands + " from " + m_Distance + " meters ");
                    }
                    else
                    {
                        m_DisplayName = source.GetType();
                        LogPrint( m_PlayerPrefix + " hit by " + m_DisplayName + m_HitMessage );
                    }
                    break;
                case DT_EXPLOSION:  // Explosion
                    LogPrint( m_PlayerPrefix + " hit by explosion (" + ammo + ")" );
                    break;
                case DT_STUN:       // unused atm
                    LogPrint( m_PlayerPrefix + " stunned by " + ammo );
                    break;
                case DT_CUSTOM:     // Others (Vehicle hit, fall, fireplace, barbed wire ...)
                    if ( ammo == "FallDamage" )         // Fall
                    {
                        LogPrint( m_PlayerPrefix + " hit by " + ammo );
                    }
                    else if ( source.GetType() == "AreaDamageManager" )
                    {
                        EntityAI parent = EntityAI.Cast( source );
                        if ( parent )
{
                            LogPrint( m_PlayerPrefix + " hit by " + parent.GetType() + " with " + ammo );
                        }
                    }
                    else
                    {
                        m_DisplayName = source.GetType();
                        LogPrint( m_PlayerPrefix + " hit by " + m_DisplayName + " with " + ammo );
                    }
                    break;
                default:
                    LogPrint("DEBUG: PlayerHitBy() unknown damageType: " + ammo );
                    break;
            }
        }
        else
        {
            LogPrint("DEBUG: player/source does not exist");
        }
    }
References component, vector::Distance(), GetHitMessage(), GetPlayerPrefix(), EntityAI::IsMeleeWeapon(), and LogPrint().
PlayerKilled()
void PluginBase::PlayerKilled (PlayerBase player, Object source) inline private
Definition at line 111 of file pluginadminlog.c.
    {
        if ( player && source )
        {
            m_PlayerPrefix = this.GetPlayerPrefix( player , player.GetIdentity() );
            if( player == source )  // deaths not caused by another object (starvation, dehydration)
            {
                m_StatWater = player.GetStatWater();
                m_StatEnergy = player.GetStatEnergy();
                m_BleedMgr = player.GetBleedingManagerServer();
                if ( m_StatWater && m_StatEnergy && m_BleedMgr )
                {
                    LogPrint( m_PlayerPrefix + " died. Stats> Water: " + m_StatWater.Get().ToString() + " Energy: " + m_StatEnergy.Get().ToString() + " Bleed sources: " + m_BleedMgr.GetBleedingSourcesCount().ToString() );
                }
                else if ( m_StatWater && m_StatEnergy && !m_BleedMgr )
                {
                    LogPrint( m_PlayerPrefix + " died. Stats> Water: " + m_StatWater.Get().ToString() + " Energy: " + m_StatEnergy.Get().ToString() );
                }
                else
                {
                    LogPrint( m_PlayerPrefix + " died. Stats> could not fetch");
                }
            }
            else if ( source.IsWeapon() || source.IsMeleeWeapon() )  // player
            {
                m_Source = PlayerBase.Cast( EntityAI.Cast( source ).GetHierarchyParent() );
                m_PlayerPrefix2 = "";
                if(m_Source)
                {
                    m_PlayerPrefix2 = this.GetPlayerPrefix( m_Source ,  m_Source.GetIdentity() );
                }
                if ( source.IsMeleeWeapon() )
                {
                    LogPrint( m_PlayerPrefix + " killed by " + m_PlayerPrefix2 + " with " + source.GetDisplayName() );
                }
                else
                {
                    m_Distance = vector.Distance( player.GetPosition(), m_Source.GetPosition() );
                    LogPrint( m_PlayerPrefix + " killed by " + m_PlayerPrefix2 + " with " + source.GetDisplayName() + " from " + m_Distance + " meters " );
                }
            }
            else                    // others
            {
                LogPrint( m_PlayerPrefix + " killed by " + source.GetType() );
            }
        }
        else
        {
            LogPrint("DEBUG: PlayerKilled() player/source does not exist");
        }
    }
References vector::Distance(), string::Get(), GetPlayerPrefix(), LogPrint(), and string::ToString().
PlayerList()
void PluginBase::PlayerList () inline private
Definition at line 335 of file pluginadminlog.c.
    {
        GetGame().GetPlayers( m_PlayerArray );
        if ( m_PlayerArray.Count() != 0 )
        {
            LogPrint( "##### PlayerList log: " + m_PlayerArray.Count().ToString() + " players" );
            foreach ( Man player: m_PlayerArray )
            {
                m_Player = PlayerBase.Cast(player);
                m_PlayerPrefix = this.GetPlayerPrefix( m_Player ,  m_Player.GetIdentity() );
                LogPrint( m_PlayerPrefix );
            }
            LogPrint( "#####" );
        }
    }
References GetGame(), GetPlayerPrefix(), CGame::GetPlayers(), LogPrint(), and m_Player.
PlayPause()
void PluginBase::PlayPause () inline private
Definition at line 56 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnKeyPress( null, 0, 0, KeyCode.KC_P );
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
PluginAdminLog()
void PluginBase::PluginAdminLog () inline private
Definition at line 42 of file pluginadminlog.c.
    {
        m_HitFilter = GetGame().ServerConfigGetInt("adminLogPlayerHitsOnly");  //  1 - log player hits only / 0 - log all hits ( animals/infected )
        m_PlacementFilter = GetGame().ServerConfigGetInt("adminLogPlacement"); //  1 - log placement ( traps, tents )
        m_ActionsFilter = GetGame().ServerConfigGetInt("adminLogBuildActions"); //  1 - log basebuilding actions ( build, dismantle, destroy )
        m_PlayerListFilter = GetGame().ServerConfigGetInt("adminLogPlayerList"); // 1 - log periodic player list with position every 5 minutes
        m_PlayerArray = new array<Man>;
        if ( m_PlayerListFilter == 1 )
        {
            m_Timer = new Timer();
            m_Timer.Run( TIMER_PLAYERLIST , this, "PlayerList", NULL, true );
        }
    }
References GetGame(), m_Timer, and CGame::ServerConfigGetInt().
PluginConfigViewer()
void PluginBase::PluginConfigViewer () inline private
Definition at line 3 of file pluginconfigviewer.c.
    {
    }
PluginDayZInfectedDebug()
void PluginBase::PluginDayZInfectedDebug () inline private
Definition at line 101 of file plugindayzinfecteddebug.c.
    {
        #ifndef NO_GUI
        CreateModuleWidgets();
        #endif
    }
References CreateModuleWidgets().
PluginDeveloper()
void PluginBase::PluginDeveloper () inline private
Definition at line 47 of file plugindeveloper.c.
    {
    }
PluginDeveloperSync()
void PluginBase::PluginDeveloperSync () inline private
Definition at line 45 of file plugindevelopersync.c.
    {
        m_RegisteredPlayers     = new map<PlayerBase, ref RegisterPlayerData>;
        m_PlayerStatsSynced     = new array<ref SyncedValue>;
        m_PlayerLevelsSynced    = new array<ref SyncedValueLevel>;
        m_PlayerModsSynced      = new array<ref SyncedValueModifier>;
        m_PlayerAgentsSynced    = new array<ref SyncedValueAgent>;
        m_PlayerStomachSynced   = new array<ref Param>;
        m_StatsUpdateStatus     = false;
        m_LevelsUpdateStatus    = false;
        m_ModsUpdateStatus      = false;
        m_AgentsUpdateStatus    = false;
        m_StomachUpdateStatus   = false;
    }
PluginDrawCheckerboard()
void PluginBase::PluginDrawCheckerboard () inline private
Definition at line 9 of file plugindrawcheckerboard.c.
    {
        CreateWidgetOverlay();
    }
References CreateWidgetOverlay().
PluginFileHandler()
void PluginBase::PluginFileHandler () inline private
Definition at line 24 of file pluginfilehandler.c.
    {
        m_FileContent = new TStringArray;
        m_LineLimit = -1;
        LoadFile();
    }
PluginHorticulture()
void PluginBase::PluginHorticulture () inline private
Definition at line 5 of file pluginhorticulture.c.
    {
        m_PlantMaterials = new map<string, ref PlantMaterialHealth>;
        LoadFromCfg();
    }
References LoadFromCfg().
PluginKeyBinding()
void PluginBase::PluginKeyBinding () inline private
Definition at line 19 of file pluginkeybinding.c.
    {
        if ( instance == null )
        {
            instance = this;
        }
    }
PluginMessageManager()
void PluginBase::PluginMessageManager () inline private
Definition at line 9 of file pluginmessagemanager.c.
    {
        for (int i = 0; i < NUM_OF_CHANNELS; i++)
        {
            channelList[i] = new array<ref MessageReceiverBase>;
        }
    }
References NUM_OF_CHANNELS.
PluginObjectsInteractionManager()
void PluginBase::PluginObjectsInteractionManager () inline private
Definition at line 9 of file pluginobjectsinteractionmanager.c.
    {
        m_LockedObjects = new array<Object>;
        m_LockedObjectsDecay = new array<float>;
        //TIMERDEPRECATED - timer for decaying objects
        m_DecayTimer = new Timer();
        m_DecayTimer.Run(TICK_RATE, this, "Decay", NULL,true);
    }
References m_DecayTimer.
PluginPlayerStatus()
void PluginBase::PluginPlayerStatus () inline private
Definition at line 8 of file pluginplayerstatus.c.
    {
        m_NotifiersLabel = new multiMap<int, string>; // [key] label
        m_NotifiersIndexColor = new multiMap<int, int>; // [key] index, color
        m_NotifiersIcons = new multiMap<int, string>; // [key] iconName
        m_NotifiersIcons.Insert( NTFKEY_HUNGRY, "iconHunger" );
        m_NotifiersIcons.Insert( NTFKEY_THIRSTY, "iconThirsty" );
        m_NotifiersIcons.Insert( NTFKEY_SICK, "iconHealth" );
        m_NotifiersIcons.Insert( NTFKEY_BACTERIA, "iconBacteria" );
        m_NotifiersIcons.Insert( NTFKEY_BLEEDISH, "iconBlood" );
        m_NotifiersIcons.Insert( NTFKEY_FEVERISH, "iconTemperature" );
        m_NotifiersIcons.Insert( NTFKEY_FRACTURE, "iconFracture" );
    }
References NTFKEY_BACTERIA, NTFKEY_BLEEDISH, NTFKEY_FEVERISH, NTFKEY_FRACTURE, NTFKEY_HUNGRY, NTFKEY_SICK, and NTFKEY_THIRSTY.
PluginSceneManager()
void PluginBase::PluginSceneManager () inline private
Definition at line 21 of file pluginscenemanager.c.
    {
        if ( instance == NULL )
        {
            instance = this;
        }
    }
PluginTransmissionAgents()
void PluginBase::PluginTransmissionAgents () inline private
Definition at line 14 of file plugintransmissionagents.c.
    {
        //add new agents here
        RegisterAgent(new InfluenzaAgent);
        RegisterAgent(new CholeraAgent);
        RegisterAgent(new SalmonellaAgent);
        RegisterAgent(new BrainAgent);
        RegisterAgent(new FoodPoisonAgent);
        RegisterAgent(new ChemicalAgent);
        RegisterAgent(new WoundAgent);
        RegisterAgent(new NerveAgent);
    }
References RegisterAgent().
PluginUniversalTemperatureSourceClient()
void PluginBase::PluginUniversalTemperatureSourceClient () inline private
Definition at line 14 of file pluginuniversaltemperaturesourceclient.c.
    {
        m_UTemperatureSourceDebugs = new array<ref UTemperatureSourceDebug>();
    }
PluginUniversalTemperatureSourceServer()
void PluginBase::PluginUniversalTemperatureSourceServer () inline private
Definition at line 11 of file pluginuniversaltemperaturesourceserver.c.
    {
        m_ClientList                = new set<PlayerBase>();
        m_UTemperatureSourceDebugs  = new array<ref UTemperatureSourceDebug>();
    }
PluginVariables()
void PluginBase::PluginVariables () inline private
Definition at line 3 of file pluginvariables.c.
    {
        m_Id = 0;
        m_Variables = new map<int, string>;
        //              ("variable name")
        RegisterVariable("varNote");
        RegisterVariable("varColor");
    }
References m_Id, and RegisterVariable().
PrintedDebug()
void PluginBase::PrintedDebug () inline private
Definition at line 219 of file pluginuniversaltemperaturesourceclient.c.
    {
        for (int i = 0; i < m_UTemperatureSourceDebugs.Count(); i++)
        {
            UTemperatureSourceDebug utsd = m_UTemperatureSourceDebugs.Get(i);
            PrintString("-------------------------------------");
            utsd.Debug();
            PrintString("-------------------------------------");
        }
    }
References PrintString().
PrintLogClient()
void PluginBase::PrintLogClient (string msg_log) inline private
Definition at line 112 of file plugindeveloper.c.
    {
        if ( g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE) )
        {
            Param1<string> msg_p = new Param1<string>(msg_log);
            CallMethod(CALL_ID_SCR_CNSL_ADD_PRINT, msg_p);
        }
    }
References CALL_ID_SCR_CNSL_ADD_PRINT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ProcessUniversalTemperatureSources()
protected void PluginBase::ProcessUniversalTemperatureSources () inline private
next temp source is too far (not cleaned on server, like in Environment, client need to know about all sources in MAXRANGE)
Definition at line 84 of file pluginuniversaltemperaturesourceclient.c.
    {
        if (m_UTemperatureSourceDebugs.Count() == 0)
        {
            m_UTSAverageTemperature = 0;
            return;
        }
        array<float> utsTemperatures = new array<float>();
        // get temperature from the source (based on distance), save it for min/max filtering
        for (int i = 0; i < m_UTemperatureSourceDebugs.Count(); i++)
        {
            UniversalTemperatureSourceDebug utsd = m_UTemperatureSourceDebugs[i];
            if (vector.DistanceSq(m_Player.GetPosition(), utsd.GetValue(0).ToVector()) > Math.SqrFloat(utsd.GetValue(2).ToFloat()))
            {
                continue;
            }
            utsTemperatures.Insert(CalcTemperatureFromTemperatureSource(m_UTemperatureSourceDebugs[i]));
        }
        float min = MiscGameplayFunctions.GetMinValue(utsTemperatures);
        float max = MiscGameplayFunctions.GetMaxValue(utsTemperatures);
        if (max > 0 && min < 0)
        {
            m_UTSAverageTemperature = (max + min) * 0.5;
        }
        else
        {
            m_UTSAverageTemperature = max;
        }
    }
References CalcTemperatureFromTemperatureSource(), vector::DistanceSq(), m_Player, and Math::SqrFloat().
Referenced by DrawDebugs().
QuickSort()
void PluginBase::QuickSort (TStringArray arr, int left, int right) inline private
Definition at line 730 of file plugindeveloper.c.
    {
        int j;
        if ( left < right )
        {
            j = QuickSortPartition( arr, left, right );
            QuickSort( arr, left, j - 1 );
            QuickSort( arr, j + 1, right );
        }
    }
References QuickSort(), and QuickSortPartition().
Referenced by QuickSort(), and SortStringArray().
QuickSortPartition()
int PluginBase::QuickSortPartition (TStringArray arr, int left, int right) inline private
Definition at line 686 of file plugindeveloper.c.
    {
        string pivot = arr.Get( left );
        int i = left;
        int j = right + 1;
        string temp;
        while ( true )
        {
            while ( true )
            {
                i++;
                if ( i > right || arr.Get(i) > pivot )
                {
                    break;
                }
            }
            while ( true )
            {
                j--;
                if ( arr.Get(j) <= pivot )
                {
                    break;
                }
            }
            if ( i >= j )
            {
                break;
            }
            temp = arr.Get( i );
            arr.Set( i, arr.Get(j) );
            arr.Set( j, temp );
        }
        temp = arr.Get( left );
        arr.Set( left, arr.Get(j) );
        arr.Set( j, temp );
        return j;
    }
Referenced by QuickSort().
RegisterAgent()
void PluginBase::RegisterAgent (AgentBase agent) inline private
Definition at line 27 of file plugintransmissionagents.c.
    {
        m_AgentList.Insert(agent.GetAgentType(), agent);
    }
Referenced by PluginTransmissionAgents().
RegisterKeyBind()
protected void PluginBase::RegisterKeyBind (int ui_id, int key_code1, int key_code2, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline private
Definition at line 287 of file pluginkeybinding.c.
    {
        m_KeyBindings.Insert( new KeyBinding(ui_id, key_code1, key_code2, plugin_name, fnc_name, info_shortcut, info_description) );
    }
RegisterMouseBind()
protected void PluginBase::RegisterMouseBind (int ui_id, int mouse_button, int mouse_event, string plugin_name, string fnc_name, string info_shortcut, string info_description) inline private
Definition at line 295 of file pluginkeybinding.c.
    {
        m_MouseBindings.Insert( new MouseBinding(ui_id, mouse_button, mouse_event, plugin_name, fnc_name, info_shortcut, info_description) );
    }
RegisterPlayer()
void PluginBase::RegisterPlayer (PlayerBase player) inline private
Definition at line 222 of file plugindevelopersync.c.
    {
        if ( !IsPlayerRegistered( player ) )
        {
            m_RegisteredPlayers.Insert( player, new RegisterPlayerData );
        }
    }
References IsPlayerRegistered(), and RegisterPlayerData().
Referenced by EnableUpdate().
RegisterVariable()
void PluginBase::RegisterVariable (string name) inline private
Definition at line 17 of file pluginvariables.c.
    {
        m_Id++;
        m_Variables.Set(m_Id,name);//REWORK.V maybe have 2 maps, one with key
    }
References m_Id, and name.
Referenced by PluginVariables().
Release()
void PluginBase::Release (Object target) inline private
Definition at line 42 of file pluginobjectsinteractionmanager.c.
    {
        if ( target && m_LockedObjects.Count() > 0 )
        {
            for ( int i = 0; i < m_LockedObjects.Count(); i++ )
            {
                if ( m_LockedObjects.Get(i) == target )
                {
                    m_LockedObjects.Remove(i);
                    m_LockedObjectsDecay.Remove(i);
                    break;
                }
            }
        }
    }
ReleaseFocus() [1/2]
void PluginBase::ReleaseFocus () inline private
Definition at line 150 of file plugindayzinfecteddebug.c.
    {
        if (m_HasFocus)
        {
            GetGame().GetInput().ChangeGameFocus(-1);
            GetGame().GetUIManager().ShowUICursor(false);
            m_HasFocus = false;
        }
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), m_HasFocus, and UIManager::ShowUICursor().
Referenced by ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), ToggleDebugWindowSetMode(), and ~PluginDayzPlayerDebug().
ReleaseFocus() [2/2]
void PluginBase::ReleaseFocus () inline private
Definition at line 859 of file plugindevelopersync.c.
    {
        GetGame().GetInput().ChangeGameFocus( -1 );
        GetGame().GetUIManager().ShowUICursor( false );
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), and UIManager::ShowUICursor().
RemoveAgent()
static void PluginBase::RemoveAgent (EntityAI target, int agent_id) inline static private
Definition at line 71 of file plugintransmissionagents.c.
    {
        target.RemoveAgent( agent_id );
    }
RemoveAllAgents()
void PluginBase::RemoveAllAgents (EntityAI target) inline private
Definition at line 66 of file plugintransmissionagents.c.
    {
        target.RemoveAllAgents();
    }
Repair()
bool PluginBase::Repair (PlayerBase player, ItemBase repair_kit, Object item, float specialty_weight, string damage_zone = "", bool use_kit_qty = true) inline private
Definition at line 3 of file pluginrepairing.c.
    {
        switch ( item.GetHealthLevel(damage_zone) )
        {
            case GameConstants.STATE_PRISTINE:
                break;
            case GameConstants.STATE_RUINED:
#ifdef DEVELOPER
                Print("PluginRepairing - repairing from GameConstants.STATE_RUINED");
#endif
                CalculateHealth( player, repair_kit, item, specialty_weight, damage_zone, use_kit_qty );
                break;
            case GameConstants.STATE_WORN:
                if( CanRepairToPristine( player ) || CanBeRepairedToPristine( item ) )
                {
                    CalculateHealth( player, repair_kit, item, specialty_weight,/* GameConstants.DAMAGE_PRISTINE_VALUE,*/ damage_zone, use_kit_qty );
                }
                break;
            default:
                CalculateHealth( player, repair_kit, item, specialty_weight, damage_zone, use_kit_qty );
                break;
        }
        return true;
    }
References CalculateHealth(), CanBeRepairedToPristine(), CanRepairToPristine(), Print(), GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
RequestDetailedInfo()
void PluginBase::RequestDetailedInfo (int id, notnull PlayerBase player) inline private
Definition at line 644 of file plugindevelopersync.c.
    {
        int modifier_id = Math.AbsInt( id );
        m_RegisteredPlayers.Get(player).m_DetailedModifierIndex = modifier_id;
        if (IsSetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED ))
        {
            SetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED, false);
        }
        else
        {
            SetSystemInBitmask(player, PDS_SYSTEMS.MODS_DETAILED, true);
        }
    }
References Math::AbsInt(), IsSetSystemInBitmask(), and SetSystemInBitmask().
Referenced by OnRPC().
RequestUniversalTemperatureSources()
void PluginBase::RequestUniversalTemperatureSources (PlayerBase player, int enable) inline private
Definition at line 200 of file pluginuniversaltemperaturesourceclient.c.
    {
        //Debug.Log("RequestUniversalTemperatureSources called", "PluginUniversalTemperatureSourceClient");
        if (!enable)
        {
            m_UTemperatureSourceDebugs.Clear();
            m_Player = null;
            EnableWidgets(false);
            return;
        }
        ScriptRPC rpc = new ScriptRPC();
        rpc.Write(enable);
        rpc.Send(player, ERPCs.DEV_REQUEST_UTS_DEBUG, true, player.GetIdentity());
        m_Player = player;
    }
References EnableWidgets(), m_Player, ScriptRPC::Send(), and Serializer::Write().
ResetGUI()
void PluginBase::ResetGUI () inline private
Definition at line 747 of file plugindeveloper.c.
    {
        if ( GetGame() && GetGame().GetMission() )
        {
            GetGame().GetMission().ResetGUI();
        }
    }
References GetGame(), CGame::GetMission(), and Mission::ResetGUI().
ResetValues()
void PluginBase::ResetValues () inline private
Definition at line 336 of file plugindayzinfecteddebug.c.
    {
    }
Referenced by OnClick().
RestoreSceneObjectsLinks()
void PluginBase::RestoreSceneObjectsLinks () inline private
Definition at line 326 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        for ( int i = 0; i < scene_objects.Count(); i++ )
        {
            SceneObject scene_object = scene_objects.Get(i);
            array<int> linked_scene_objects_indices = scene_object.m_LinkedSceneObjectsIndices;
            if (linked_scene_objects_indices)
            {
                for ( int j = 0; j < linked_scene_objects_indices.Count(); j++ )
                {
                    int index = linked_scene_objects_indices.Get(j);
                    if ( index >= 0 && index < scene_objects.Count() )
                    {
                        scene_object.LinkSceneObject( scene_objects.Get(index), false );
//PrintString("Load link: "+ ToString(scene_object.GetObject()) +" <-> "+ ToString(scene_objects.Get(index).GetObject()));
                    }
                }
            }
            scene_object.m_LinkedSceneObjectsIndices = NULL;
        }
    }
References SceneObject::LinkSceneObject(), and SceneObject::m_LinkedSceneObjectsIndices.
RulerAddPoint()
void PluginBase::RulerAddPoint () inline private
Definition at line 937 of file pluginscenemanager.c.
    {
        vector point_pos = GetMousePositionInScene();
        m_RulerPoints.Insert( point_pos );
        EditorUpdateRuler();
    }
RulerClearVisuals()
void PluginBase::RulerClearVisuals () inline private
Definition at line 949 of file pluginscenemanager.c.
    {
        for ( int i = 0; i < m_RulerLines.Count(); ++i )
        {
            m_RulerLines.Get(i).Destroy();
        }
        m_RulerLines.Clear();
        for ( int j = 0; j < m_RulerSpheres.Count(); ++j )
        {
            m_RulerSpheres.Get(j).Destroy();
        }
        m_RulerSpheres.Clear();
    }
RulerDelete()
void PluginBase::RulerDelete () inline private
Definition at line 967 of file pluginscenemanager.c.
    {
        m_RulerPoints.Clear();
        EditorUpdateRuler();
    }
RulerToggle()
void PluginBase::RulerToggle () inline private
Definition at line 912 of file pluginscenemanager.c.
    {
        if ( IsRulerActivated() )
        {
            m_RulerActivated = false;
        }
        else
        {
            m_RulerActivated = true;
        }
        SceneEditorMenuCmdRefresh();
    }
Save()
void PluginBase::Save () inline private
Definition at line 50 of file plugincameratools.c.
    {
        if( GetGame().GetUIManager().GetMenu() )
            GetGame().GetUIManager().GetMenu().OnKeyPress( null, 0, 0, KeyCode.KC_S );
    }
References GetGame(), UIManager::GetMenu(), CGame::GetUIManager(), and UIScriptedMenu::OnKeyPress().
SaveFile()
bool PluginBase::SaveFile () inline private
Definition at line 77 of file pluginfilehandler.c.
    {
        if ( m_ReadOnly )
        {
            return false;
        }
        //Log("SaveFile -> Opening File: "+GetFileName());
        FileHandle file_index = OpenFile(GetFileName(), FileMode.WRITE);
        if ( file_index == 0 )
        {
            return false;
        }
        for ( int i = 0; i < m_FileContent.Count(); ++i)
        {
            //Log("SaveFile -> Writing: "+m_FileContent.Get(i));
            FPrintln(file_index, m_FileContent.Get(i));
        }
        CloseFile(file_index);
        return true;
    }
References CloseFile(), FPrintln(), PluginFileHandler::GetFileName(), and OpenFile().
SceneCanDelete()
bool PluginBase::SceneCanDelete (string scene_name) inline private
Definition at line 790 of file pluginscenemanager.c.
    {
        if ( scene_name == m_SceneData.GetNameScene() )
        {
            return false;
        }
        return true;
    }
SceneDelete()
bool PluginBase::SceneDelete (string scene_name) inline private
Definition at line 803 of file pluginscenemanager.c.
    {
        if ( scene_name == m_SceneData.GetNameScene() )
        {
            return false;
        }
        m_ModuleConfigScene.SceneDelete(scene_name);
        EditorUpdate();
        return true;
    }
SceneDuplicate()
void PluginBase::SceneDuplicate (string scene_name) inline private
Definition at line 820 of file pluginscenemanager.c.
    {
        m_ModuleConfigScene.SceneDuplicate(scene_name);
        EditorUpdate();
    }
SceneEditorMenuCmdPopup()
private void PluginBase::SceneEditorMenuCmdPopup (string message) inline private
Definition at line 1211 of file pluginscenemanager.c.
    {
        CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param1<string>>(SCENE_EDITOR_CMD_POPUP, new Param1<string>(message)));
    }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdRefresh()
private void PluginBase::SceneEditorMenuCmdRefresh () inline private
Definition at line 1203 of file pluginscenemanager.c.
    {
        CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param>(SCENE_EDITOR_CMD_REFRESH, NULL));
    }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneEditorMenuCmdSave()
private void PluginBase::SceneEditorMenuCmdSave () inline private
Definition at line 1219 of file pluginscenemanager.c.
    {
        CallMethod(CALL_ID_SCENE_EDITOR_COMMAND, new Param2<int, Param>(SCENE_EDITOR_CMD_SAVE, NULL));
    }
References CALL_ID_SCENE_EDITOR_COMMAND, and CallMethod().
SceneGetName()
string PluginBase::SceneGetName () inline private
Definition at line 845 of file pluginscenemanager.c.
    {
        if ( m_SceneData )
        {
            return m_SceneData.GetNameScene();
        }
        return STRING_EMPTY;
    }
References STRING_EMPTY.
SceneLoad()
void PluginBase::SceneLoad (string scene_name) inline private
Definition at line 754 of file pluginscenemanager.c.
    {
        SceneUnload();
        PluginMissionConfig.GetInstance().SetSceneEditorName(scene_name);
        m_SceneData = m_ModuleConfigScene.SceneDataLoad(scene_name);
        if ( !(GetGame().IsMultiplayer() && GetGame().IsServer()) )
        {
            EditorUpdate();
        }
    }
References GetGame().
SceneRename()
void PluginBase::SceneRename (string scene_name, string new_name) inline private
Definition at line 830 of file pluginscenemanager.c.
    {
        m_ModuleConfigScene.SceneRename(scene_name, new_name);
        if ( scene_name == m_SceneData.GetNameScene() )
        {
            m_SceneData.SetNameScene(new_name);
        }
        EditorUpdate();
    }
SceneSave()
void PluginBase::SceneSave () inline private
Definition at line 779 of file pluginscenemanager.c.
    {
        m_ModuleConfigScene.ClearParams();
        m_ModuleConfigScene.SceneDataSave(m_SceneData);
        SceneEditorMenuCmdSave();
        EditorUpdate();
    }
SceneUnload()
void PluginBase::SceneUnload () inline private
Definition at line 770 of file pluginscenemanager.c.
    {
        m_SceneData = NULL;
        DeselectObject();
    }
ScriptHistoryBack()
private void PluginBase::ScriptHistoryBack () inline private
Definition at line 652 of file plugindeveloper.c.
    {
        // Console key press
        if ( g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE) )
        {
            CallMethod(CALL_ID_SCR_CNSL_HISTORY_BACK, NULL);
        }
    }
References CALL_ID_SCR_CNSL_HISTORY_BACK, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
ScriptHistoryNext()
private void PluginBase::ScriptHistoryNext () inline private
Definition at line 643 of file plugindeveloper.c.
    {
        // Console key press
        if ( g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE) )
        {
            CallMethod(CALL_ID_SCR_CNSL_HISTORY_NEXT, NULL);
        }
    }
References CALL_ID_SCR_CNSL_HISTORY_NEXT, CallMethod(), g_Game, and MENU_SCRIPTCONSOLE.
SelectAndFocusPlayerObject()
void PluginBase::SelectAndFocusPlayerObject () inline private
Definition at line 881 of file pluginscenemanager.c.
    {
        array<ref SceneObject> scene_objects = GetSceneObjects();
        for ( int i = 0; i < scene_objects.Count(); i++ )
        {
            if ( scene_objects.Get(i).GetObject() == GetGame().GetPlayer() )
            {
                SelectObject( scene_objects.Get(i) );
                SelectedObjectFocus();
                break;
            }
        }
    }
References GetGame(), and GetPlayer().
SelectClassName()
void PluginBase::SelectClassName (string class_name) inline private
Definition at line 401 of file pluginscenemanager.c.
    {
        m_ClassBrowserSelected = class_name;
    }
References class_name.
SelectedObjectAddAttachment()
void PluginBase::SelectedObjectAddAttachment (string att_name) inline private
Definition at line 645 of file pluginscenemanager.c.
    {
        if ( GetSelectedSceneObject() )
        {
            GetSelectedSceneObject().AddAttachment(att_name);
        }
        EditorUpdate();
    }
SelectedObjectDuplicate()
void PluginBase::SelectedObjectDuplicate () inline private
Definition at line 499 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( selected_obj )
        {
            if ( selected_obj.GetObject() == PLAYER )
            {
                return;
            }
            vector size = GetSelectedSceneObject().GetSize();
            vector new_pos = selected_obj.GetPosition() + Vector(1, 0, 1) + size;
            SceneObject obj = m_SceneData.CreateSceneObject(selected_obj.GetTypeName(), new_pos );
            obj.SetRotation(selected_obj.GetRotation());
            array<EntityAI> attachments = selected_obj.GetAttachments();
            for ( int i = 0; i < attachments.Count(); i++ )
            {
                obj.AddAttachment( attachments.Get(i).GetType() );
            }
            SelectObject(obj);
        }
    }
References SceneObject::AddAttachment(), SceneObject::GetAttachments(), SceneObject::GetObject(), SceneObject::GetPosition(), SceneObject::GetRotation(), SceneObject::GetTypeName(), PLAYER, SceneObject::SetRotation(), and Vector().
SelectedObjectFocus()
void PluginBase::SelectedObjectFocus () inline private
Definition at line 610 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( selected_obj )
        {
            vector      cam_pos = FreeDebugCamera.GetInstance().GetPosition();
            vector      obj_pos = selected_obj.GetPosition();
            vector      view_target = obj_pos;
            vector obj_size = selected_obj.GetSize();
            cam_pos = obj_pos;
            cam_pos[0] = cam_pos[0] + ( obj_size[0] * 2 );
            cam_pos[1] = cam_pos[1] + obj_size[1] + 0.5;
            cam_pos[2] = cam_pos[2] + ( obj_size[2] * 2 );
            view_target[1] = view_target[1] + (obj_size[1] * 0.5);
            vector cam_dir = view_target - cam_pos;
            cam_dir.Normalize();
            FreeDebugCamera.GetInstance().SetPosition(cam_pos);
            FreeDebugCamera.GetInstance().SetDirection(cam_dir);
            //vector debug_pos = cam_pos + (cam_dir * 50);
            //Debug.DrawLine(cam_pos, debug_pos);
            //Debug.DrawSphere(cam_pos);
        }
    }
References SceneObject::GetPosition(), SceneObject::GetSize(), and vector::Normalize().
SelectedObjectRemoveAttachment()
void PluginBase::SelectedObjectRemoveAttachment (EntityAI e) inline private
Definition at line 658 of file pluginscenemanager.c.
    {
        if ( GetSelectedSceneObject() )
        {
            GetSelectedSceneObject().RemoveAttachment(e);
        }
        EditorUpdate();
    }
SelectedObjectSetDamage()
void PluginBase::SelectedObjectSetDamage (float value) inline private
Definition at line 594 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        EntityAI selected_obj_EAI = selected_obj.GetObject();
        if ( selected_obj )
        {
            selected_obj.SetHealth(Math.Clamp ( value, 0, selected_obj_EAI.GetMaxHealth("", "") ));
            EditorUpdate();
        }
    }
References Math::Clamp(), SceneObject::GetObject(), and SceneObject::SetHealth().
SelectedObjectSetPosX()
void PluginBase::SelectedObjectSetPosX (float value) inline private
Definition at line 543 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( selected_obj )
        {
            vector v = selected_obj.GetPosition();
            v[0] = value;
            selected_obj.SetPosition(v);
            EditorUpdate();
        }
    }
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetPosY()
void PluginBase::SelectedObjectSetPosY (float value) inline private
Definition at line 560 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( selected_obj )
        {
            vector v = selected_obj.GetPosition();
            v[1] = value;
            selected_obj.SetPosition(v);
            EditorUpdate();
        }
    }
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetPosZ()
void PluginBase::SelectedObjectSetPosZ (float value) inline private
Definition at line 577 of file pluginscenemanager.c.
    {
        SceneObject selected_obj = GetSelectedSceneObject();
        if ( GetSelectedSceneObject() )
        {
            vector v = selected_obj.GetPosition();
            v[2] = value;
            selected_obj.SetPosition(v);
            EditorUpdate();
        }
    }
References SceneObject::GetPosition(), and SceneObject::SetPosition().
SelectedObjectSetRot()
void PluginBase::SelectedObjectSetRot (float dir) inline private
Definition at line 530 of file pluginscenemanager.c.
    {
        if ( GetSelectedSceneObject() )
        {
            GetSelectedSceneObject().SetRotation(dir);
            EditorUpdate();
        }
    }
SelectObject()
void PluginBase::SelectObject (SceneObject obj) inline private
Definition at line 474 of file pluginscenemanager.c.
    {
        if ( GetSelectedSceneObject() != NULL && GetSelectedSceneObject() == obj )
        {
            return;
        }
        DeselectObject();
        m_SelectedObject = obj;
        EditorUpdate();
    }
References m_SelectedObject.
SendDebug() [1/2]
void PluginBase::SendDebug () inline private
Definition at line 56 of file pluginremoteplayerdebugserver.c.
    {
        GatherPlayerInfo();
        array<ref RemotePlayerDamageDebug> player_damage = new array<ref RemotePlayerDamageDebug>;
        for(int i = 0; i < m_ClientList.Count(); i++)
        {
            PlayerBase player = m_ClientList.Get(i);
            if(player)
            {
                ScriptRPC rpc = new ScriptRPC();
                rpc.Write(m_PlayerDebugStats);
                for(int x = 0; x < m_PlayerDebugDamage.Count(); x++)
                {
                    PlayerBase player2 = m_PlayerDebugDamage.GetKey(x);
                    RemotePlayerDamageDebug value = m_PlayerDebugDamage.GetElement(x);
                    if(player2)
                    {
                        player_damage.Insert(value);
                    }
                    //int xs = 1 + 1;
                }
                rpc.Write(player_damage);
                rpc.Send( player, ERPCs.DEV_PLAYER_DEBUG_DATA, true, player.GetIdentity() );
                m_PlayerDebugDamage.Clear();
            }
            else
            {
                m_ClientList.Remove(i);
            }
        }
    }
References GatherPlayerInfo(), m_PlayerDebugDamage, m_PlayerDebugStats, ScriptRPC::Send(), Serializer::Write(), and x.
Referenced by OnUpdate().
SendDebug() [2/2]
void PluginBase::SendDebug () inline private
Definition at line 81 of file pluginuniversaltemperaturesourceserver.c.
    {
        for (int i = 0; i < m_ClientList.Count(); i++)
        {
            PlayerBase player = m_ClientList.Get(i);
            if (player)
            {
                GatherTemperatureSources(player);
                ScriptRPC rpc = new ScriptRPC();
                rpc.Write(m_UTemperatureSourceDebugs);
                rpc.Send(player, ERPCs.DEV_UTS_DEBUG_DATA, true, player.GetIdentity());
            }
            else
            {
                m_ClientList.Remove(i);
            }
        }
    }
References GatherTemperatureSources(), ScriptRPC::Send(), and Serializer::Write().
SendRPCAgents()
void PluginBase::SendRPCAgents (PlayerBase player) inline private
Definition at line 737 of file plugindevelopersync.c.
    {
        //write and send values
        if ( ( player && player.GetIdentity() && player.m_AgentPool != null ) || ( player && !GetGame().IsMultiplayer() && player.m_AgentPool != null ) )
        {
            //get agent pool data
            array<ref Param> agent_pool = new array<ref Param>;
            player.m_AgentPool.GetDebugObject( agent_pool );
            GetDayZGame().RPC( player, ERPCs.DEV_RPC_AGENTS_DATA, agent_pool, true, player.GetIdentity() );
        }
    }
References GetDayZGame(), and GetGame().
Referenced by Update().
SendRPCLevels()
void PluginBase::SendRPCLevels (PlayerBase player) inline private
Definition at line 494 of file plugindevelopersync.c.
    {
        //write and send values
        if ( player )
        {
            array<ref Param> rpc_params = new array<ref Param>;
            rpc_params.Insert(new Param3<string, float, float>( "Immunity: "+ typename.EnumToString(EStatLevels, player.GetImmunityLevel() ),player.GetImmunityLevel(), player.GetBordersImmunity()));
            rpc_params.Insert(new Param3<string, float, float>( "Blood: "+ typename.EnumToString(EStatLevels, player.GetStatLevelBlood()),player.GetStatLevelBlood(), player.GetStatBordersBlood()));
            rpc_params.Insert(new Param3<string, float, float>( "Health: "+ typename.EnumToString(EStatLevels, player.GetStatLevelHealth() ),player.GetStatLevelHealth(), player.GetStatBordersHealth()));
            rpc_params.Insert(new Param3<string, float, float>( "Energy: "+ typename.EnumToString(EStatLevels, player.GetStatLevelEnergy() ),player.GetStatLevelEnergy(), player.GetStatBordersEnergy()));
            rpc_params.Insert(new Param3<string, float, float>( "Water: "+ typename.EnumToString(EStatLevels, player.GetStatLevelWater() ),player.GetStatLevelWater(), player.GetStatBordersWater()));
            int param_count = rpc_params.Count();
            rpc_params.InsertAt( new Param3<string, float, float>( "PARAM_COUNT", param_count,0 ), 0);
            //send params
            GetDayZGame().RPC( player, ERPCs.DEV_RPC_LEVELS_DATA, rpc_params, true, player.GetIdentity() );
        }
    }
References GetDayZGame().
Referenced by Update().
SendRPCMods()
void PluginBase::SendRPCMods (PlayerBase player) inline private
Definition at line 538 of file plugindevelopersync.c.
    {
        //write and send values
        if ( player )
        {
            array<ref Param> rpc_params = new array<ref Param>;
            //get modifiers
            ModifiersManager mods_manager = player.GetModifiersManager();
            //param count
            array<ref ModifierDebugObj> modifiers = new array<ref ModifierDebugObj>;
            mods_manager.DbgGetModifiers( modifiers );
            float param_count = ( float ) modifiers.Count();
            rpc_params.Insert( new Param1<int>( param_count ));
            //set modifiers
            for ( int i = 0; i < modifiers.Count(); ++i )
            {
                int id = modifiers.Get(i).GetID();
                string name = modifiers.Get(i).GetName();
                bool active =  modifiers.Get(i).IsActive();
                bool locked =  modifiers.Get(i).IsLocked();
                rpc_params.Insert( new Param4<int, string, bool, bool>( id, name, active, locked ) );
            }
            //send params
            GetDayZGame().RPC( player, ERPCs.DEV_RPC_MODS_DATA, rpc_params, true, player.GetIdentity() );
        }
    }
References GetDayZGame(), ModifiersManager(), and name.
Referenced by Update().
SendRPCModsDetail()
void PluginBase::SendRPCModsDetail (PlayerBase player) inline private
Definition at line 575 of file plugindevelopersync.c.
    {
        //write and send values
        if ( player )
        {
            Param1<string> p1 = new Param1<string>("");
            ModifiersManager mods_manager = player.GetModifiersManager();
            int mod_id = m_RegisteredPlayers.Get(player).m_DetailedModifierIndex;
            p1.param1 = mods_manager.GetModifier(mod_id).GetDebugText();
            //send params
            if (p1.param1 != "")
                GetDayZGame().RPCSingleParam( player, ERPCs.DEV_RPC_MODS_DATA_DETAILED, p1, true, player.GetIdentity() );
        }
    }
References GetDayZGame(), and ModifiersManager().
Referenced by Update().
SendRPCStats()
void PluginBase::SendRPCStats (PlayerBase player) inline private
Definition at line 401 of file plugindevelopersync.c.
    {
        //write and send values
        if ( player )
        {
            array<ref Param> rpc_params = new array<ref Param>;
            //param count
            for ( int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++ )
            {
                string label = player.m_PlayerStats.GetPCO().Get().Get( i ).GetLabel();
                float value = (float) player.m_PlayerStats.GetPCO().Get().Get( i ).Get();
                float value_norm = (float) player.m_PlayerStats.GetPCO().Get().Get( i ).GetNormalized();
                rpc_params.Insert( new Param3<string, float, float>( label, value, value_norm ) );
            }
            rpc_params.Insert(new Param3<string, float, float>( "(NaS)Immunity", player.GetImmunity(),0 ));
            rpc_params.Insert(new Param3<string, float, float>( "(NaS)BrokenLegs", player.m_BrokenLegState,0 ));
            rpc_params.InsertAt( new Param1<int>(rpc_params.Count() ), 0);// param count
            //send params
            GetDayZGame().RPC( player, ERPCs.DEV_RPC_STATS_DATA, rpc_params, true, player.GetIdentity() );
        }
    }
References Count, Get(), and GetDayZGame().
Referenced by Update().
SendRPCStomach()
void PluginBase::SendRPCStomach (PlayerBase player) inline private
Definition at line 779 of file plugindevelopersync.c.
    {
        //write and send values
        if ( player )
        {
            array<ref Param> stomach = new array<ref Param>;
            int count = player.m_PlayerStomach.GetDebugObject( stomach );
            stomach.InsertAt(new Param1<int>(count), 0);
            GetDayZGame().RPC( player, ERPCs.DEV_RPC_STOMACH_DATA, stomach, true, player.GetIdentity() );
        }
    }
References GetDayZGame().
Referenced by Update().
SendRPCTemp()
void PluginBase::SendRPCTemp (PlayerBase player) inline private
Definition at line 708 of file plugindevelopersync.c.
    {
        if ( player )
        {
            CachedObjectsParams.PARAM1_STRING.param1 = player.m_Environment.GetDebugMessage();
            GetDayZGame().RPCSingleParam( player, ERPCs.DEV_TEMP_UPDATE, CachedObjectsParams.PARAM1_STRING, true, player.GetIdentity() );
        }
    }
References GetDayZGame(), and CachedObjectsParams::PARAM1_STRING.
Referenced by Update().
SendServerLogToClient()
void PluginBase::SendServerLogToClient (string msg) inline private
Definition at line 122 of file plugindeveloper.c.
    {
        if ( GetGame() )
        {
            array<Man> players = new array<Man>;
            GetGame().GetPlayers( players );
            for ( int i = 0; i < players.Count(); ++i )
            {
                Param1<string> param = new Param1<string>( msg );
                Man player = players.Get(i);
                if ( player  &&  player.HasNetworkID() )
                {
                    player.RPCSingleParam(ERPCs.DEV_RPC_SEND_SERVER_LOG, param, true, player.GetIdentity());
                }
            }
        }
    }
References GetGame(), and CGame::GetPlayers().
SetBadge()
void PluginBase::SetBadge (int key, int value) inline private
Definition at line 64 of file pluginplayerstatus.c.
    {
        if ( key )
        {
            Mission mission = GetGame().GetMission();
            if ( mission )
            {
                Hud hud = mission.GetHud();
                if ( hud )
                {
                    hud.DisplayBadge( key, value );
                }
            }
        }
    }
References Hud::DisplayBadge(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
SetDate()
void PluginBase::SetDate (int year, int month, int day, int hour, int minute) inline private
Definition at line 869 of file pluginscenemanager.c.
    {
        m_SceneData.SetInitYear(year);
        m_SceneData.SetInitMonth(month);
        m_SceneData.SetInitDay(day);
        m_SceneData.SetInitHour(hour);
        m_SceneData.SetInitMinute(minute);
    }
SetDeveloperItemClient()
void PluginBase::SetDeveloperItemClient () inline private
Definition at line 779 of file plugindeveloper.c.
    {
        #ifdef DEVELOPER
        Object entity;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        FreeDebugCamera debugCam = FreeDebugCamera.GetInstance();
        if (debugCam && debugCam.GetCurrentCamera())
        {
            entity = debugCam.GetCrosshairObject();
        }
        else
        {
            if (player && player.GetActionManager())
            {
                ActionTarget at = player.GetActionManager().FindActionTarget();
                entity = at.GetObject();
            }
        }
        if (entity)
        {
            SetDeveloperItemClientEx(entity, true);
        }
        #endif
    }
References ActionTarget, GetGame(), GetPlayer(), and SetDeveloperItemClientEx().
SetDeveloperItemClientEx()
static void PluginBase::SetDeveloperItemClientEx (notnull Object entity, bool getFocus = false) inline static private
Definition at line 755 of file plugindeveloper.c.
    {
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if (getFocus)
        {
            GetGame().GetInput().ChangeGameFocus(1);
            GetGame().GetUIManager().ShowUICursor(true);
        }
        if (GetGame().IsMultiplayer())
        {
            GetGame().RPCSingleParam(GetGame().GetPlayer(), ERPCs.DEV_SET_DEV_ITEM, new Param1<Object>(entity), true, GetGame().GetPlayer().GetIdentity());
        }
        else
        {
            PluginItemDiagnostic mid2 = PluginItemDiagnostic.Cast(GetPlugin(PluginItemDiagnostic));
            mid2.RegisterDebugItem(entity, player);
        }
        #ifdef DEVELOPER
        SetDebugDeveloper_item(entity);
        #endif
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), GetPlayer(), GetPlugin(), CGame::GetUIManager(), PluginItemDiagnostic(), CGame::RPCSingleParam(), and UIManager::ShowUICursor().
Referenced by SetDeveloperItemClient().
SetDrawSelection()
void PluginBase::SetDrawSelection (bool draw) inline private
Definition at line 704 of file pluginscenemanager.c.
    {
        m_ModuleConfigDebugProfile.SetSceneEditorDrawSelection(draw);
        EditorUpdate();
    }
SetLoadPlayerPos()
void PluginBase::SetLoadPlayerPos (bool save) inline private
Definition at line 722 of file pluginscenemanager.c.
    {
        m_ModuleConfigDebugProfile.SetSceneEditorLoadPlayerPos(save);
    }
SetNotifier()
void PluginBase::SetNotifier (int key, int index = 9, string label = "", int color = 0xFFFFFFFF) inline private
Definition at line 23 of file pluginplayerstatus.c.
    {
        if ( key )
        {
            if ( m_NotifiersLabel.HasKey( key ) )
            {
                m_NotifiersLabel.Remove( key );
                m_NotifiersIndexColor.Remove( key );
            }
            if ( label != "" )
            {
                m_NotifiersLabel.Insert( key, label );
                m_NotifiersIndexColor.Insert( key, index );
                m_NotifiersIndexColor.Insert( key, color );
            }
        }
    }
SetRotationAngle()
void PluginBase::SetRotationAngle (int angle) inline private
Definition at line 738 of file pluginscenemanager.c.
    {
        m_ModuleConfigDebugProfile.SetSceneEditorRotationAngle(angle);
    }
SetStamina()
void PluginBase::SetStamina (int value, int range) inline private
Definition at line 80 of file pluginplayerstatus.c.
    {
        // Log( String( "SetStamina" + itoa( value) ), LogTemplates.TEMPLATE_JANOSIK );
        Mission mission = GetGame().GetMission();
        if ( mission )
        {
            Hud hud = mission.GetHud();
            if ( hud )
            {
                hud.SetStamina( Math.Clamp( value, 0, range ), range );
            }
        }
    }
References Math::Clamp(), GetGame(), Mission::GetHud(), CGame::GetMission(), mission, and Hud::SetStamina().
SetStance()
void PluginBase::SetStance (int value) inline private
Definition at line 94 of file pluginplayerstatus.c.
    {
        Mission mission = GetGame().GetMission();
        if ( mission )
        {
            Hud hud = mission.GetHud();
            if ( hud )
            {
                hud.DisplayStance( value );
            }
        }
    }
References Hud::DisplayStance(), GetGame(), Mission::GetHud(), CGame::GetMission(), and mission.
SetSystemInBitmask()
void PluginBase::SetSystemInBitmask (PlayerBase player, int system_bit, bool state) inline private
Definition at line 195 of file plugindevelopersync.c.
    {
        if ( IsPlayerRegistered(player) )
        {
            int current_mask = m_RegisteredPlayers.Get(player).m_Bitmask;
            if (state)
                m_RegisteredPlayers.Get(player).m_Bitmask = current_mask | system_bit;
            else
                m_RegisteredPlayers.Get(player).m_Bitmask = current_mask & ~system_bit;
        }
    }
References IsPlayerRegistered().
Referenced by EnableUpdate(), and RequestDetailedInfo().
SetupSpawnedEntity()
void PluginBase::SetupSpawnedEntity (PlayerBase player, EntityAI entity, float health, float quantity = -1, bool special = false, string presetName = "") inline private
Definition at line 301 of file plugindeveloper.c.
    {
        #ifdef DEVELOPER
        if (presetName && player.m_PresetSpawned)//this is how we ascertain this is the first item being spawned from a new preset after a previous preset was already spawned in
        {
            player.m_PresetItems.Clear();
            player.m_PresetSpawned = false;//is set to 'true' elsewhere after all the items have been spawned in
        }
        if ( entity.IsInherited( PlayerBase ) )
        {
            PlayerBase plr = PlayerBase.Cast( entity );
            plr.OnSpawnedFromConsole();
        }
        else if ( entity.IsInherited(ItemBase) )
        {
            ItemBase item = ItemBase.Cast( entity );
            SetupSpawnedItem(item, health, quantity);
        }
        if (presetName)
        {
            player.m_PresetItems.Insert(entity);
        }
        if ( special )
            entity.OnDebugSpawn();
        #endif
    }
References SetupSpawnedItem().
Referenced by SpawnEntityOnCursorDir(), and SpawnEntityOnGroundPos().
SetWatching()
void PluginBase::SetWatching (bool enable) inline private
Definition at line 30 of file pluginremoteplayerdebugserver.c.
    {
        m_Watching = enable;
    }
Referenced by OnRequestReceived().
SetWeather()
void PluginBase::SetWeather (float overcast, float rain, float fog, float wind_force) inline private
Definition at line 858 of file pluginscenemanager.c.
    {
        m_SceneData.SetInitOvercast(overcast);
        m_SceneData.SetInitRain(rain);
        m_SceneData.SetInitFog(fog);
        m_SceneData.SetInitWindForce(wind_force);
    }
Show() [1/3]
void PluginBase::Show () inline private
Definition at line 161 of file plugindayzinfecteddebug.c.
    {
        ShowWidgets(true);
        m_IsActive = true;
        GetUApi().ActivateExclude("menu");
        GetUApi().UpdateControls();
        if (!m_TickTimer)
        {
            m_TickTimer = new Timer();
            m_TickTimer.Run(0.1, this, "Tick", NULL, true);
        }
    }
References UAInputAPI::ActivateExclude(), GetUApi(), m_IsActive, m_TickTimer, ShowWidgets(), and UAInputAPI::UpdateControls().
Referenced by SetDebugShowMode(), ToggleDebugWindowEventOld(), ToggleDebugWindowEventP(), ToggleDebugWindowSetMode(), and ToggleDebugWindowSetMode().
Show() [2/3]
void PluginBase::Show () inline private
Definition at line 80 of file plugindrawcheckerboard.c.
    {
        ShowWidgets(true);
        m_IsActive = true;
    }
References m_IsActive, and ShowWidgets().
Show() [3/3]
void PluginBase::Show () inline private
Definition at line 19 of file pluginsounddebug.c.
    {
        m_TickTimer = new Timer();
        m_TickTimer.Run(0.1, this, "OnGUITimer", NULL, true);
    }
References m_TickTimer.
ShowCard()
void PluginBase::ShowCard (int pCard) inline private
Definition at line 262 of file plugindayzinfecteddebug.c.
    {
        m_CardMovementFrame.Show(pCard == 0);
        m_CardFightFrame.Show(pCard == 1);
    }
Referenced by CreateModuleWidgets(), CreateModuleWidgets(), and OnClick().
ShowWidgets() [1/2]
void PluginBase::ShowWidgets (bool show) inline private
Definition at line 188 of file plugindayzinfecteddebug.c.
    {
        if(m_MainWnd)
        {
            m_MainWnd.Show(show);
        }
    }
References m_MainWnd.
Referenced by Hide(), Hide(), Show(), and Show().
ShowWidgets() [2/2]
void PluginBase::ShowWidgets (bool show) inline private
Definition at line 71 of file plugindrawcheckerboard.c.
    {
        if(m_MainWindow)
        {
            m_MainWindow.Show(show);
        }
    }
SortStringArray()
void PluginBase::SortStringArray (TStringArray arr) inline private
Definition at line 742 of file plugindeveloper.c.
    {
        QuickSort( arr, 0, arr.Count() - 1 );
    }
References QuickSort().
SpawnEntityAsAttachment()
PluginBase::SpawnEntityAsAttachment (PlayerBase player, EntityAI parent, string att_name, float health, float quantity) inline private
tries to spawn item as attachment
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
Definition at line 505 of file plugindeveloper.c.
    {
        if ( GetGame().IsServer() )
        {
            Weapon_Base wpn = Weapon_Base.Cast(parent);
            if (wpn)
            {
                GameInventory inventory = parent.GetInventory();
                return inventory.CreateInInventory(att_name);
                /*
                vector pos = player.GetPosition();
                EntityAI eai_gnd = SpawnEntityOnGroundPos(player, att_name, health, quantity, pos);
                Magazine mag_gnd = Magazine.Cast(eai_gnd);
                if (mag_gnd && player.GetWeaponManager().CanAttachMagazine(wpn, mag_gnd))
                {
                    player.GetWeaponManager().AttachMagazine(mag_gnd);
                }
                return eai_gnd;
                */
            }
            else
            {
                EntityAI eai = parent.GetInventory().CreateAttachment(att_name);
                if (eai)
                {
                    if ( eai.IsInherited(ItemBase) )
                    {
                        ItemBase i = ItemBase.Cast( eai );
                        SetupSpawnedItem(ItemBase.Cast( eai ), health, quantity);
                    }
                    return eai;
                }
                else
                    OnSpawnErrorReport(att_name);
            }
            return NULL;
        }
        else
        {
            // Client -> Server Spawning: Client Side
            Param3<string, float, float> params = new Param3<string, float, float>(att_name, health, quantity);
            player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_AS_ATTACHMENT, params, true);
        }
        return NULL;
    }
References GetGame(), OnSpawnErrorReport(), and SetupSpawnedItem().
SpawnEntityInInventory()
PluginBase::SpawnEntityInInventory (PlayerBase player, string item_name, float health, float quantity, bool special = false, string presetName = "") inline private
tries to spawn item somewhere in inventory
SpawnEntityInInventory queries future parent about free inventory location of the future item
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
Returns
entity if ok, null otherwise
Definition at line 446 of file plugindeveloper.c.
    {
        if ( player )
        {
            if ( GetGame().IsServer() )
            {
                InventoryLocation il = new InventoryLocation;
                if (player.GetInventory() && player.GetInventory().FindFirstFreeLocationForNewEntity(item_name, FindInventoryLocationType.ANY, il))
                {
                    Weapon_Base wpn = Weapon_Base.Cast(il.GetParent());
                    bool is_mag = il.GetSlot() == InventorySlots.MAGAZINE || il.GetSlot() == InventorySlots.MAGAZINE2 || il.GetSlot() == InventorySlots.MAGAZINE3;
                    if (wpn && is_mag)
                    {
                        vector pos = player.GetPosition();
                        EntityAI eai_gnd = SpawnEntityOnGroundPos(player, item_name, health, quantity, pos);
                        Magazine mag_gnd = Magazine.Cast(eai_gnd);
                        if (mag_gnd && player.GetWeaponManager().CanAttachMagazine(wpn, mag_gnd))
{
                            player.GetWeaponManager().AttachMagazine(mag_gnd);
                        }
                        return eai_gnd;
                    }
                    else
                    {
                        EntityAI eai = GetGame().SpawnEntity(item_name, il, ECE_IN_INVENTORY, RF_DEFAULT);
                        if ( eai && eai.IsInherited(ItemBase) )
{
                            if ( health < 0 )//check for default (-1)
{
                                health = eai.GetMaxHealth();
                            }
                            ItemBase i = ItemBase.Cast( eai );
                            SetupSpawnedItem(i, health, quantity);
                            if ( special )
                                eai.OnDebugSpawn();
                        }
                        return eai;
                    }
                }
                else
                    OnSpawnErrorReport(item_name);
                return NULL;
            }
            else
            {
                // Client -> Server Spawning: Client Side
                Param5<string, float, float, bool, string> params = new Param5<string, float, float, bool, string>(item_name, health, quantity, special, presetName );
                player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_IN_INVENTORY, params, true);
            }
        }
        return NULL;
    }
References ECE_IN_INVENTORY, GetGame(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), OnSpawnErrorReport(), RF_DEFAULT, SetupSpawnedItem(), and SpawnEntityOnGroundPos().
Referenced by OnRPCSpawnEntity().
SpawnEntityOnCursorDir()
PluginBase::SpawnEntityOnCursorDir (PlayerBase player, string item_name, float quantity, float distance, float health = -1, bool special = false, string presetName = "") inline private
spawns entity in direction of cursor at specified distance
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] distance distance of the item from player
Returns
entity if ok, null otherwise
Definition at line 408 of file plugindeveloper.c.
    {
        if ( GetGame().IsServer() )
        {
            // Client -> Server Spawning: Server Side
            EntityAI entity = player.SpawnEntityOnGroundOnCursorDir(item_name, distance);
            if ( entity )
            {
                if ( health < 0 && entity.GetMaxHealth() > 0)//check for default (-1)
                {
                    health = entity.GetMaxHealth();
                }
                SetupSpawnedEntity( player,entity, health, quantity, special, presetName );
            }
            else
                OnSpawnErrorReport( item_name );
            return entity;
        }
        else
        {
            // Client -> Server Spawning: Client Side
            Param6<string, float, float, float, bool, string> params = new Param6<string, float, float, float, bool, string>(item_name, quantity, distance, health, special, presetName);
            player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_CURSOR, params, true);
        }
        return NULL;
    }
References GetGame(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnCursorDir(), and SpawnFromClipboard().
SpawnEntityOnGroundPatternGrid()
void PluginBase::SpawnEntityOnGroundPatternGrid (PlayerBase player, string item_name, int count, float health, float quantity, int rows, int columns, float gapRow = 1, float gapColumn = 1) inline private
Definition at line 329 of file plugindeveloper.c.
    {
        if (!item_name)
        {
            return;
        }
        if ( GetGame().IsServer() )
        {
            float rowDist = 0;
            float columnDist = 0;
            vector playerPos = player.GetPosition();
            vector camDirForward = player.GetDirection();
            vector camDirRight = camDirForward.Perpend() * -1;
            int countLoop = 0;
            for (int i = 0; i < rows; i++)
            {
                vector posRow = playerPos + camDirForward * rowDist;
                vector offsetSide;
                columnDist = 0;
                for (int j = 0; j < columns; j++)
                {
                    offsetSide = camDirRight * columnDist;
                    vector placement = posRow + offsetSide;
                    float hlth = health * MiscGameplayFunctions.GetTypeMaxGlobalHealth( item_name );
                    SpawnEntityOnGroundPos(player, item_name, hlth, quantity, placement );
                    countLoop++;
                    if (countLoop == count)
                    {
                        return;
                    }
                    columnDist += gapColumn;
                }
                rowDist += gapRow;
            }
        }
        else
        {
            auto params = new Param8<string, int, float, float, int, int, float, float>(item_name, count, health, quantity, rows, columns, gapRow, gapColumn);
            player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND_PATTERN_GRID, params, true);
        }
    }
References GetGame(), vector::Perpend(), and SpawnEntityOnGroundPos().
Referenced by OnRPCSpawnEntityOnGroundPatternGrid().
SpawnEntityOnGroundPos()
PluginBase::SpawnEntityOnGroundPos (PlayerBase player, string item_name, float health, float quantity, vector pos) inline private
spawns entity on exact position
Parameters
[in] health health of the item
[in] quantity quantity to set if item.HasQuantity() (-1 == set to max)
[in] pos position where to spawn
Returns
entity if ok, null otherwise
Definition at line 382 of file plugindeveloper.c.
    {
        if ( GetGame().IsServer() )
        {
            EntityAI entity = player.SpawnEntityOnGroundPos(item_name, pos);
            if (entity)
                SetupSpawnedEntity(player, entity, health, quantity);
            else
                OnSpawnErrorReport(item_name);
            return entity;
        }
        else
        {
            Param4<string, float, float, vector> params = new Param4<string, float, float, vector>(item_name, health, quantity, pos);
            player.RPCSingleParam(ERPCs.DEV_RPC_SPAWN_ITEM_ON_GROUND, params, true);
        }
        return NULL;
    }
References GetGame(), OnSpawnErrorReport(), and SetupSpawnedEntity().
Referenced by OnRPCSpawnEntityOnGround(), SpawnEntityInInventory(), and SpawnEntityOnGroundPatternGrid().
SpawnFromClipboard()
EntityAI PluginBase::SpawnFromClipboard () inline private
Definition at line 551 of file plugindeveloper.c.
    {
        UIScriptedMenu menu_curr = GetGame().GetUIManager().GetMenu();
        if ( menu_curr == NULL )
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            if ( player )
            {
                if ( !GetGame().GetWorld().Is3rdPersonDisabled() )
                {
                    player.SetIsInThirdPerson(!player.IsInThirdPerson());//this counters the effect of switching camera through pressing the 'V' key
                }
                vector pos_player = player.GetPosition();
                // Get item from clipboard
                string      clipboard;
                GetGame().CopyFromClipboard(clipboard);
                if (!clipboard.Contains(","))
                {
                    //single item
                    EntityAI object_spawned_from_clipboard = SpawnEntityOnCursorDir(player, clipboard, -1, 1);
                    //Print(object_spawned_from_clipboard);
                }
                else
                {
                    TStringArray items = new TStringArray;
                    clipboard.Split( ",", items );
                    foreach(string item:items)
                    {
                        SpawnEntityOnCursorDir(player, item.Trim(), -1, 1);
                    }
                }
            }
        }
        return NULL;
    }
References string::Contains(), CGame::CopyFromClipboard(), GetGame(), UIManager::GetMenu(), GetPlayer(), CGame::GetUIManager(), SpawnEntityOnCursorDir(), and string::Split().
SpawnNewInfectedEntity()
void PluginBase::SpawnNewInfectedEntity () inline private
Definition at line 341 of file plugindayzinfecteddebug.c.
    {
        m_ControlledInfected = DayZInfected.Cast(GetGame().CreateObject("ZmbF_JournalistNormal_Blue", GetGame().GetPlayer().GetPosition(), 0, true));
        m_ControlledInfected.GetAIAgent().SetKeepInIdle(true);
    }
References GetGame(), GetPlayer(), and GetPosition.
Referenced by OnClick().
Subscribe()
void PluginBase::Subscribe (MessageReceiverBase receiver, int index) inline private
Subscribes an object to listen to messages on a channel provided in the 'index' parameter.
Definition at line 109 of file pluginmessagemanager.c.
    {
        if(index > channelsUsed) //this is used to speed up the unsubscribeAll method, instead of all channels, we sweep just those in usage
        {
            channelsUsed = index;
        }
        array<ref MessageReceiverBase> chan = channelList[index];
        if( chan.Find(receiver) >= 0 ) return;
        chan.Insert(receiver);
    }
Suicide()
void PluginBase::Suicide (PlayerBase player) inline private
Definition at line 321 of file pluginadminlog.c.
    {
        m_PlayerPrefix = this.GetPlayerPrefix( player ,  player.GetIdentity() );
        LogPrint( m_PlayerPrefix + " committed suicide" );
    }
References GetPlayerPrefix(), and LogPrint().
SwitchPermanentCrossHair()
void PluginBase::SwitchPermanentCrossHair (bool state) inline private
Definition at line 5 of file pluginpermanentcrosshair.c.
    {
        if (!m_Hud)
            m_Hud = GetGame().GetMission().GetHud();
        m_Hud.SetPermanentCrossHair(state);
    }
References GetGame(), Mission::GetHud(), CGame::GetMission(), m_Hud, and Hud::SetPermanentCrossHair().
Teleport()
void PluginBase::Teleport (PlayerBase player, vector position) inline private
Teleport player at position.
Definition at line 24 of file plugindeveloper.c.
    {
        DeveloperTeleport.SetPlayerPosition(player, position);
    }
References DeveloperTeleport::SetPlayerPosition().
TeleportAtCursor()
void PluginBase::TeleportAtCursor () inline private
Set Player position at his cursor position in the world.
Definition at line 18 of file plugindeveloper.c.
    {
        DeveloperTeleport.TeleportAtCursorEx();
    }
References DeveloperTeleport::TeleportAtCursorEx().
Tick()
void PluginBase::Tick () inline private
Definition at line 413 of file plugindayzinfecteddebug.c.
    {
        if( !m_ControlledInfected )
            return;
    }
ToggleCameraTools()
void PluginBase::ToggleCameraTools () inline private
Definition at line 19 of file plugincameratools.c.
    {
        if( !m_IsOpen )
        {
            GetGame().GetUIManager().EnterScriptedMenu( MENU_CAMERA_TOOLS, null );
        }
        else
        {
            GetGame().GetUIManager().Back();
        }
        m_IsOpen = !m_IsOpen;
    }
References UIManager::Back(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetUIManager(), and MENU_CAMERA_TOOLS.
ToggleDebugWindowEvent()
void PluginBase::ToggleDebugWindowEvent () inline private
Definition at line 116 of file plugindayzinfecteddebug.c.
    {
        m_CurrentMode++;
        if (m_CurrentMode > 2)
        {
            m_CurrentMode = 0;
        }
        ToggleDebugWindowSetMode(m_CurrentMode);
    }
References m_CurrentMode, and ToggleDebugWindowSetMode().
ToggleDebugWindowSetMode()
void PluginBase::ToggleDebugWindowSetMode (int pMode) inline private
Definition at line 128 of file plugindayzinfecteddebug.c.
    {
        switch (pMode)
        {
        case 0:     Hide(); ReleaseFocus(); break;
        case 1:     Show(); ReleaseFocus(); break;
        case 2:     Show(); CaptureFocus(); break;
        }
    }
References CaptureFocus(), Hide(), ReleaseFocus(), and Show().
Referenced by ToggleDebugWindowEvent(), and ToggleDebugWindowEvent().
ToggleFocus()
void PluginBase::ToggleFocus () inline private
Definition at line 865 of file plugindevelopersync.c.
    {
        if ( GetGame().GetInput().HasGameFocus() )
        {
            GetGame().GetInput().ChangeGameFocus( 1 );
            GetGame().GetUIManager().ShowUICursor( true );
        }
        else
        {
            GetGame().GetInput().ResetGameFocus();
            GetGame().GetUIManager().ShowUICursor( false );
        }
    }
References Input::ChangeGameFocus(), GetGame(), CGame::GetInput(), GetInput(), CGame::GetUIManager(), Input::ResetGameFocus(), and UIManager::ShowUICursor().
ToggleFreeCamera()
void PluginBase::ToggleFreeCamera () inline private
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
Definition at line 36 of file plugindeveloper.c.
    {
        DeveloperFreeCamera.FreeCameraToggle( PlayerBase.Cast( GetGame().GetPlayer() ), true );
    }
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleFreeCameraBackPos()
void PluginBase::ToggleFreeCameraBackPos () inline private
Enable / Disable Free camera (Fly mod)
Definition at line 30 of file plugindeveloper.c.
    {
        DeveloperFreeCamera.FreeCameraToggle( PlayerBase.Cast( GetGame().GetPlayer() ), false );
    }
References DeveloperFreeCamera::FreeCameraToggle(), GetGame(), and GetPlayer().
ToggleHelpScreen()
void PluginBase::ToggleHelpScreen () inline private
Definition at line 607 of file plugindeveloper.c.
    {
        if ( g_Game.GetUIManager().GetMenu() == NULL )
        {
            g_Game.GetUIManager().EnterScriptedMenu(MENU_HELP_SCREEN, NULL);
        }
        else if ( g_Game.GetUIManager().IsMenuOpen(MENU_HELP_SCREEN) )
        {
            g_Game.GetUIManager().Back();
        }
    }
References g_Game, and MENU_HELP_SCREEN.
ToggleMissionLoader()
void PluginBase::ToggleMissionLoader () inline private
Definition at line 637 of file plugindeveloper.c.
    {
        g_Game.GetUIManager().OpenWindow( GUI_WINDOW_MISSION_LOADER );
    }
References g_Game, and GUI_WINDOW_MISSION_LOADER.
ToggleScriptConsole()
void PluginBase::ToggleScriptConsole () inline private
Definition at line 619 of file plugindeveloper.c.
    {
        if ( GetGame() != null && GetGame().GetPlayer() != null )
        {
            if ( g_Game.GetUIManager().GetMenu() == NULL )
            {
                m_ScriptConsole = g_Game.GetUIManager().EnterScriptedMenu(MENU_SCRIPTCONSOLE, NULL);
                GetGame().GetMission().AddActiveInputExcludes({"menu"});
            }
            else if ( g_Game.GetUIManager().IsMenuOpen(MENU_SCRIPTCONSOLE) )
            {
                g_Game.GetUIManager().Back();
                GetGame().GetMission().RemoveActiveInputExcludes({"menu"},true);
            }
        }
    }
References Mission::AddActiveInputExcludes(), g_Game, GetGame(), CGame::GetMission(), GetPlayer(), MENU_SCRIPTCONSOLE, and Mission::RemoveActiveInputExcludes().
TransmitAgents()
void PluginBase::TransmitAgents (EntityAI source, EntityAI target, int pathway, int dose_size = 1000) inline private
Definition at line 259 of file plugintransmissionagents.c.
    {
         TransmitAgentsEx(source, target, pathway, dose_size);
    }
References TransmitAgentsEx().
TransmitAgentsEx()
float PluginBase::TransmitAgentsEx (EntityAI source, EntityAI target, int pathway, int dose_size = 1000, int agents = 0) inline private
Definition at line 192 of file plugintransmissionagents.c.
    {
        //Debug.Log("Transmitting agents for source: " +source.ToString()+", target: " +target.ToString(),"Agents");
        int sourceAgents = agents;
        int targetAgents;
        if(!sourceAgents && source) sourceAgents = source.GetAgents();//do not set sourceAgents again if already set
        if(target) targetAgents = target.GetAgents();
        float count = 0;
        switch (pathway)
        {
            case AGT_INV_OUT: //item leaving inventory
                break;
            case AGT_INV_IN: //item entering inventory
                break;
            case AGT_UACTION_TOUCH: //player touched the item
                //InjectAgents( source, targetAgents ,GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.GLOVES, player) );
                break;
            case AGT_WATER_POND:
                //target.InsertAgent(eAgents.CHOLERA, dose_size);
                InjectAgentsWithPlayer( target, eAgents.CHOLERA , 0, 1, InjectTypes.ITEM_TO_PLAYER );
                break;
            case AGT_UACTION_CONSUME:
                //InjectAgentsWithPlayer( target, sourceAgents , 0, dose_size, InjectTypes.ITEM_TO_PLAYER );
                InjectAgentsWithPlayer( source, targetAgents , 0, 1, InjectTypes.PLAYER_TO_ITEM );
                break;
            case AGT_UACTION_TO_PLAYER: //user action of a consumption, only from item to player
                InjectAgentsWithPlayerCount( target, sourceAgents , 0, dose_size, InjectTypes.ITEM_TO_PLAYER );
                break;
            case AGT_UACTION_TO_ITEM: //to transfer from the player to the consumed item
                InjectAgentsWithPlayer( target, sourceAgents , 0, 1, InjectTypes.PLAYER_TO_ITEM );
                break;
            case AGT_TRANSFER_COPY: //transferring liquid
                InjectAgentsWithoutPlayer( target, sourceAgents );
                break;
            case AGT_ITEM_TO_FLESH: //transferring liquid
                InjectAgentsWithPlayer( target, sourceAgents , 0, 1, InjectTypes.ITEM_TO_PLAYER);
                break;
            case AGT_AIRBOURNE_BIOLOGICAL:
                float prot_level_mask_target = GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.MASK, Man.Cast( target ));
                float prot_level_mask_source = GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.MASK, Man.Cast( source ));
                float prot_level_headgear_target = GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.HEADGEAR, Man.Cast( target ));
                float prot_level_headgear_source = GetProtectionLevel(DEF_BIOLOGICAL,InventorySlots.HEADGEAR, Man.Cast( source ));
                float prot_level_target = Math.Max(prot_level_mask_target, prot_level_headgear_target);//find the bigger of the 2, TODO: should be improved
                float prot_level_source = Math.Max(prot_level_mask_source, prot_level_headgear_source);//find the bigger of the 2, TODO: should be improved
                float prot_level_combined = 1 - (1 - prot_level_target) * (1 - prot_level_source);
                InjectAgentsWithPlayer( target, sourceAgents , prot_level_combined, 1, InjectTypes.PLAYER_AIR_PLAYER );
                break;
            case AGT_AIRBOURNE_CHEMICAL:
                float prot_level_mask_target2 = GetProtectionLevel(DEF_CHEMICAL,InventorySlots.MASK, Man.Cast( target ));
                count = InjectAgentWithPlayerDose( target, agents , prot_level_mask_target2, dose_size, InjectTypes.PLAYER_AIR_PLAYER );
                break;
        }
        return count;
    }
References AGT_AIRBOURNE_BIOLOGICAL, AGT_AIRBOURNE_CHEMICAL, AGT_INV_IN, AGT_INV_OUT, AGT_ITEM_TO_FLESH, AGT_TRANSFER_COPY, AGT_UACTION_CONSUME, AGT_UACTION_TO_ITEM, AGT_UACTION_TO_PLAYER, AGT_UACTION_TOUCH, AGT_WATER_POND, DEF_BIOLOGICAL, DEF_CHEMICAL, GetProtectionLevel(), InjectAgentsWithoutPlayer(), InjectAgentsWithPlayer(), InjectAgentsWithPlayerCount(), InjectAgentWithPlayerDose(), and Math::Max().
Referenced by TransmitAgents().
UnconStart()
void PluginBase::UnconStart (PlayerBase player) inline private
Definition at line 270 of file pluginadminlog.c.
    {
        m_PlayerPrefix = this.GetPlayerPrefix( player ,  player.GetIdentity() );
        LogPrint( m_PlayerPrefix + " is unconscious" );
    }
References GetPlayerPrefix(), and LogPrint().
UnconStop()
void PluginBase::UnconStop (PlayerBase player) inline private
Definition at line 277 of file pluginadminlog.c.
    {
        if ( player.IsAlive() )     // Do not log uncon stop for dead players
        {
            m_PlayerPrefix = this.GetPlayerPrefix( player ,  player.GetIdentity() );
            LogPrint( m_PlayerPrefix + " regained consciousness" );
        }
    }
References GetPlayerPrefix(), and LogPrint().
UnlinkSceneObjects()
void PluginBase::UnlinkSceneObjects (SceneObject scene_object1, SceneObject scene_object2) inline private
Definition at line 680 of file pluginscenemanager.c.
    {
        scene_object1.UnlinkSceneObject(scene_object2);
        scene_object2.UnlinkSceneObject(scene_object1);
    }
References SceneObject::UnlinkSceneObject().
Unsubscribe()
void PluginBase::Unsubscribe (MessageReceiverBase receiver, int index) inline private
Definition at line 120 of file pluginmessagemanager.c.
    {
        array<ref MessageReceiverBase> chan = channelList[index];
        int i = chan.Find(receiver);
        if( i >= 0 )
        {
            chan.Remove(i);
        }
    }
UnsubscribeAll()
void PluginBase::UnsubscribeAll (MessageReceiverBase receiver) inline private
Definition at line 130 of file pluginmessagemanager.c.
    {
        //GetGame().ProfilerStart("UnsubscribeAll");
        for (int i = 0; i <= channelsUsed; i++)
        {
            array<ref MessageReceiverBase> chan = channelList[i];
            int c = chan.Find(receiver);
            if( c >= 0 )
            {
                chan.Remove(c);
            }
        }
        //GetGame().ProfilerStop("UnsubscribeAll");
    }
References channelsUsed.
Update()
void PluginBase::Update () inline private
!!!! Highly suspect
Definition at line 146 of file plugindevelopersync.c.
    {
        if ( !GetDayZGame().IsMultiplayer() || GetDayZGame().IsServer() )
        {
            for ( int i = 0; i < m_RegisteredPlayers.Count(); i++ )
            {
                PlayerBase player = m_RegisteredPlayers.GetKey( i );
                if ( !player || !player.IsAlive() )
                {
                    m_RegisteredPlayers.RemoveElement(i);
                    i--;
                }
                else
                {
                    int bit_mask = m_RegisteredPlayers.Get( player ).m_Bitmask;
                    if ((PDS_SYSTEMS.MODS & bit_mask) != 0 )
                    {
                        SendRPCMods( player);
                        if ( PDS_SYSTEMS.MODS_DETAILED & bit_mask )
                            SendRPCModsDetail(  player);
                    }
                    if ((PDS_SYSTEMS.LEVELS & bit_mask) != 0 )
                    {
                        SendRPCLevels( player );
                    }
                    if ((PDS_SYSTEMS.STATS & bit_mask) != 0 )
                    {
                        SendRPCStats( player );
                    }
                    if ((PDS_SYSTEMS.STOMACH & bit_mask) != 0 )
                    {
                        SendRPCStomach( player );
                    }
                    if ((PDS_SYSTEMS.AGENTS & bit_mask) != 0 )
                    {
                        SendRPCAgents( player );
                    }
                    if ((PDS_SYSTEMS.TEMPERATURE & bit_mask) )
                    {
                        SendRPCTemp( player );
                    }
                }
            }
        }
    }
References GetDayZGame(), SendRPCAgents(), SendRPCLevels(), SendRPCMods(), SendRPCModsDetail(), SendRPCStats(), SendRPCStomach(), and SendRPCTemp().
UpdateStatsLocal()
void PluginBase::UpdateStatsLocal () inline private
Definition at line 452 of file plugindevelopersync.c.
    {
        PlayerBase player = PlayerBase.Cast( GetDayZGame().GetPlayer() );
        //clear values
        m_PlayerStatsSynced.Clear();
        //set values
        for ( int i = 0; i < player.m_PlayerStats.GetPCO().Get().Count(); i++ )
        {
            string label = player.m_PlayerStats.GetPCO().Get().Get( i ).GetLabel();
            float value = player.m_PlayerStats.GetPCO().Get().Get( i ).Get();
            float value_norm = player.m_PlayerStats.GetPCO().Get().Get( i ).GetNormalized();
            m_PlayerStatsSynced.Insert( new SyncedValue( label, value, false, value_norm ) );
        }
        m_PlayerStatsSynced.Insert(new SyncedValue(  "(NaS)Immunity", player.GetImmunity() , false, 0));
        m_PlayerStatsSynced.Insert(new SyncedValue(  "(NaS) BrokenLegs", player.m_BrokenLegState, false, 0));
    }
References Count, Get(), GetDayZGame(), and GetPlayer().
UpdateStatWidget()
void PluginBase::UpdateStatWidget (int rowIndex, UTemperatureSourceDebug utsd) inline private
Definition at line 184 of file pluginuniversaltemperaturesourceclient.c.
    {
        m_StatListWidgets[rowIndex].ClearItems();
        for (int i = 0; i < utsd.PairsCount(); i++)
        {
            m_StatListWidgets[rowIndex].AddItem(utsd.GetName(i), null, 0, i);
            m_StatListWidgets[rowIndex].SetItem(i, utsd.GetValue(i), null, 1);
        }
        int numPairs = utsd.PairsCount();
        // manually add value for distance (client only)
        m_StatListWidgets[rowIndex].AddItem("distance", null, 0, numPairs);
        m_StatListWidgets[rowIndex].SetItem(numPairs, vector.Distance(m_Player.GetPosition(), utsd.GetValue(0).ToVector()).ToString(), null, 1);
    }
References vector::Distance(), m_Player, m_StatListWidgets, and float::ToString().
Referenced by UpdateStatWidgets().
UpdateStatWidgets()
void PluginBase::UpdateStatWidgets () inline private
Definition at line 153 of file pluginuniversaltemperaturesourceclient.c.
    {
        int i = 0;
        for (; i < m_UTemperatureSourceDebugs.Count(); i++)
        {
            UTemperatureSourceDebug utsd = m_UTemperatureSourceDebugs.Get(i);
            vector pos = utsd.GetValue(0).ToVector();
            vector screen_pos_stats = GetGame().GetScreenPos(pos + "0 0 0");
            vector screen_pos_damage = GetGame().GetScreenPos(pos + "0 2 0");
            m_RootWidget[i].SetPos(screen_pos_stats[0],screen_pos_stats[1]);
            if (screen_pos_stats[2] > 0 && screen_pos_stats[0] > 0 && screen_pos_stats[1] > 0)
            {
                m_RootWidget[i].Show(true);
                UpdateStatWidget(i, utsd);
            }
            else
            {
                m_RootWidget[i].Show(false);
            }
        }
        for (; i < MAX_SIMULTANEOUS_UTS; i++)
        {
            if (m_RootWidget[i])
            {
                m_RootWidget[i].Show(false);
            }
        }
    }
References GetGame(), CGame::GetScreenPos(), m_RootWidget, MAX_SIMULTANEOUS_UTS, and UpdateStatWidget().
Referenced by OnUpdate().
Member Data Documentation
channelList
ref array<ref MessageReceiverBase> PluginBase::channelList[NUM_OF_CHANNELS] private
Definition at line 7 of file pluginmessagemanager.c.
channelsUsed
int PluginBase::channelsUsed = 0 private
Definition at line 6 of file pluginmessagemanager.c.
Referenced by UnsubscribeAll().
CLICK_TIME
protected const int PluginBase::CLICK_TIME = 200 private
Definition at line 276 of file pluginkeybinding.c.
DOUBLE_CLICK_TIME
protected const int PluginBase::DOUBLE_CLICK_TIME = 300 private
Definition at line 277 of file pluginkeybinding.c.
fadeInVolume
float PluginBase::fadeInVolume = 1.1 private
Definition at line 178 of file pluginsounddebug.c.
fadeOutVolume
float PluginBase::fadeOutVolume = 0.9 private
Definition at line 179 of file pluginsounddebug.c.
FOV
const float PluginBase::FOV = 0.5236 private
Definition at line 15 of file plugincharplacement.c.
HOLD_CLICK_TIME_MIN
protected const int PluginBase::HOLD_CLICK_TIME_MIN = 300 private
Definition at line 278 of file pluginkeybinding.c.
instance [1/2]
PluginKeyBinding PluginBase::instance static private
Definition at line 16 of file pluginkeybinding.c.
instance [2/2]
PluginSceneManager PluginBase::instance static private
Definition at line 6 of file pluginscenemanager.c.
INTERVAL
const int PluginBase::INTERVAL = 1 private
Definition at line 9 of file pluginremoteplayerdebugserver.c.
LOOKUP_RADIUS
const float PluginBase::LOOKUP_RADIUS = 20 private
[s]
Definition at line 4 of file pluginuniversaltemperaturesourceserver.c.
m_AccuTime [1/2]
float PluginBase::m_AccuTime private
Definition at line 8 of file pluginremoteplayerdebugserver.c.
m_AccuTime [2/2]
protected float PluginBase::m_AccuTime private
[m]
Definition at line 6 of file pluginuniversaltemperaturesourceserver.c.
m_ActionsFilter
protected int PluginBase::m_ActionsFilter private
Definition at line 23 of file pluginadminlog.c.
m_AgentList
ref map<int, ref AgentBase> PluginBase::m_AgentList = new map<int, ref AgentBase> static private
Definition at line 10 of file plugintransmissionagents.c.
Referenced by GetAgentList().
m_AgentsUpdateStatus
bool PluginBase::m_AgentsUpdateStatus private
Definition at line 42 of file plugindevelopersync.c.
m_AttackDescriptors
ref array<ref PluginDayZInfectedDebugAttackDesc> PluginBase::m_AttackDescriptors = new array<ref PluginDayZInfectedDebugAttackDesc> private
Definition at line 96 of file plugindayzinfecteddebug.c.
m_AttackDirCB
XComboBoxWidget PluginBase::m_AttackDirCB private
Definition at line 80 of file plugindayzinfecteddebug.c.
m_AttackTypeCB
XComboBoxWidget PluginBase::m_AttackTypeCB private
Definition at line 79 of file plugindayzinfecteddebug.c.
m_BleedMgr
BleedingSourcesManagerServer PluginBase::m_BleedMgr private
Definition at line 19 of file pluginadminlog.c.
m_cam_pos
vector PluginBase::m_cam_pos private
Definition at line 7 of file plugincharplacement.c.
m_camera_dir
vector PluginBase::m_camera_dir private
Definition at line 9 of file plugincharplacement.c.
m_camera_orientation
vector PluginBase::m_camera_orientation private
Definition at line 13 of file plugincharplacement.c.
m_cameraTrans
vector PluginBase::m_cameraTrans[4] private
Definition at line 10 of file plugincharplacement.c.
m_CardFightButton
ButtonWidget PluginBase::m_CardFightButton private
Definition at line 49 of file plugindayzinfecteddebug.c.
m_CardFightFrame
Widget PluginBase::m_CardFightFrame private
Definition at line 51 of file plugindayzinfecteddebug.c.
m_CardMovementButton
ButtonWidget PluginBase::m_CardMovementButton private
Definition at line 48 of file plugindayzinfecteddebug.c.
m_CardMovementFrame
Widget PluginBase::m_CardMovementFrame private
Definition at line 50 of file plugindayzinfecteddebug.c.
m_CH_DoAttack
bool PluginBase::m_CH_DoAttack = false private
Definition at line 93 of file plugindayzinfecteddebug.c.
m_CH_DoHit
bool PluginBase::m_CH_DoHit = false private
Definition at line 91 of file plugindayzinfecteddebug.c.
m_CH_DoKnucleOut
bool PluginBase::m_CH_DoKnucleOut = false private
Definition at line 89 of file plugindayzinfecteddebug.c.
m_CH_DoTurn
bool PluginBase::m_CH_DoTurn = false private
command handler values
Definition at line 87 of file plugindayzinfecteddebug.c.
m_CH_DoVault
bool PluginBase::m_CH_DoVault = false private
Definition at line 88 of file plugindayzinfecteddebug.c.
m_CH_GoToCrawl
bool PluginBase::m_CH_GoToCrawl = false private
Definition at line 90 of file plugindayzinfecteddebug.c.
m_CH_StartDeath
bool PluginBase::m_CH_StartDeath = false private
Definition at line 92 of file plugindayzinfecteddebug.c.
m_Character
PlayerBase PluginBase::m_Character private
Definition at line 4 of file plugincharplacement.c.
m_character_pos
vector PluginBase::m_character_pos private
Definition at line 8 of file plugincharplacement.c.
m_ClassBrowserSelected
protected string PluginBase::m_ClassBrowserSelected private
Definition at line 1131 of file pluginscenemanager.c.
m_ClientList [1/2]
ref set<PlayerBase> PluginBase::m_ClientList = new set<PlayerBase> private
Definition at line 4 of file pluginremoteplayerdebugserver.c.
m_ClientList [2/2]
protected ref set<PlayerBase> PluginBase::m_ClientList private
Definition at line 7 of file pluginuniversaltemperaturesourceserver.c.
m_ControlledInfected
DayZInfected PluginBase::m_ControlledInfected private
controlled instance
Definition at line 84 of file plugindayzinfecteddebug.c.
m_CrawlingTypeCB
XComboBoxWidget PluginBase::m_CrawlingTypeCB private
Definition at line 67 of file plugindayzinfecteddebug.c.
m_CurrentMode
int PluginBase::m_CurrentMode = 0 private
Definition at line 41 of file plugindayzinfecteddebug.c.
m_DeathTypeCB
XComboBoxWidget PluginBase::m_DeathTypeCB private
Definition at line 76 of file plugindayzinfecteddebug.c.
m_DebugType
eRemoteDebugType PluginBase::m_DebugType private
Definition at line 11 of file pluginremoteplayerdebugserver.c.
m_DecayTimer
private ref Timer PluginBase::m_DecayTimer private
Definition at line 7 of file pluginobjectsinteractionmanager.c.
m_demoPos
vector PluginBase::m_demoPos private
Definition at line 11 of file plugincharplacement.c.
Referenced by CalculatePos().
m_demoRot
vector PluginBase::m_demoRot private
Definition at line 12 of file plugincharplacement.c.
m_DetailedInfoRequested
int PluginBase::m_DetailedInfoRequested = 0 private
Definition at line 27 of file plugindevelopersync.c.
m_DisplayName
string PluginBase::m_DisplayName private
Definition at line 9 of file pluginadminlog.c.
m_Distance
float PluginBase::m_Distance private
Definition at line 11 of file pluginadminlog.c.
m_DotIndex
int PluginBase::m_DotIndex private
Definition at line 16 of file pluginadminlog.c.
m_EnvironmentDebugMessage
string PluginBase::m_EnvironmentDebugMessage private
Definition at line 36 of file plugindevelopersync.c.
m_FeaturesMask
protected int PluginBase::m_FeaturesMask private
Definition at line 4 of file plugindeveloper.c.
m_FileContent
ref TStringArray PluginBase::m_FileContent private
Definition at line 22 of file pluginfilehandler.c.
m_HasFocus
bool PluginBase::m_HasFocus = false private
Definition at line 42 of file plugindayzinfecteddebug.c.
m_HitBodyPartCB
XComboBoxWidget PluginBase::m_HitBodyPartCB private
Definition at line 73 of file plugindayzinfecteddebug.c.
m_HitDirEB
EditBoxWidget PluginBase::m_HitDirEB private
fight card
Definition at line 71 of file plugindayzinfecteddebug.c.
m_HitFilter
protected int PluginBase::m_HitFilter private
Definition at line 21 of file pluginadminlog.c.
m_HitMessage
string PluginBase::m_HitMessage private
Definition at line 10 of file pluginadminlog.c.
m_HitTypeCB
XComboBoxWidget PluginBase::m_HitTypeCB private
Definition at line 72 of file plugindayzinfecteddebug.c.
m_Hud
private Hud PluginBase::m_Hud private
Definition at line 3 of file pluginpermanentcrosshair.c.
m_Id
int PluginBase::m_Id private
Definition at line 24 of file pluginvariables.c.
m_Initialized
bool PluginBase::m_Initialized private
Definition at line 6 of file plugincharplacement.c.
m_Instance
protected PluginCameraTools PluginBase::m_Instance static private
Definition at line 3 of file plugincameratools.c.
m_IsActive [1/2]
bool PluginBase::m_IsActive = false private
Definition at line 43 of file plugindayzinfecteddebug.c.
Referenced by IsActive(), and IsActive().
m_IsActive [2/2]
private bool PluginBase::m_IsActive private
Definition at line 6 of file plugindrawcheckerboard.c.
m_IsConstructed
bool PluginBase::m_IsConstructed = false private
Definition at line 12 of file plugintransmissionagents.c.
m_IsDragging
protected bool PluginBase::m_IsDragging private
Definition at line 1126 of file pluginscenemanager.c.
m_IsOpen [1/2]
protected bool PluginBase::m_IsOpen static private
Definition at line 4 of file plugincameratools.c.
m_IsOpen [2/2]
protected bool PluginBase::m_IsOpen private
Definition at line 1132 of file pluginscenemanager.c.
m_IsWinHolding
protected bool PluginBase::m_IsWinHolding private
Definition at line 3 of file plugindeveloper.c.
m_ItemInHands
string PluginBase::m_ItemInHands private
Definition at line 14 of file pluginadminlog.c.
m_KeyBindings [1/2]
protected ref array<ref KeyBinding> PluginBase::m_KeyBindings private
Definition at line 280 of file pluginkeybinding.c.
m_KeyBindings [2/2]
protected ref map<int, KeyBinding> PluginBase::m_KeyBindings private
Definition at line 1128 of file pluginscenemanager.c.
m_KnucleOutButton
ButtonWidget PluginBase::m_KnucleOutButton private
Definition at line 65 of file plugindayzinfecteddebug.c.
m_LevelsUpdateStatus
bool PluginBase::m_LevelsUpdateStatus private
Definition at line 40 of file plugindevelopersync.c.
m_LineLimit
int PluginBase::m_LineLimit private
Definition at line 20 of file pluginfilehandler.c.
m_LockedObjects
private ref array<Object> PluginBase::m_LockedObjects private
Definition at line 3 of file pluginobjectsinteractionmanager.c.
m_LockedObjectsDecay
private ref array<float> PluginBase::m_LockedObjectsDecay private
Definition at line 4 of file pluginobjectsinteractionmanager.c.
m_MainWindow
private ref Widget PluginBase::m_MainWindow private
Definition at line 5 of file plugindrawcheckerboard.c.
m_MainWnd
Widget PluginBase::m_MainWnd private
main controls
Definition at line 46 of file plugindayzinfecteddebug.c.
Referenced by DestroyModuleWidgets(), and DestroyModuleWidgets().
m_Message
string PluginBase::m_Message private
Definition at line 8 of file pluginadminlog.c.
m_MindStateCB
XComboBoxWidget PluginBase::m_MindStateCB private
Definition at line 56 of file plugindayzinfecteddebug.c.
m_ModsUpdateStatus
bool PluginBase::m_ModsUpdateStatus private
Definition at line 41 of file plugindevelopersync.c.
m_ModuleConfigDebugProfile
protected PluginConfigDebugProfile PluginBase::m_ModuleConfigDebugProfile private
Definition at line 1119 of file pluginscenemanager.c.
m_ModuleConfigScene
protected PluginConfigScene PluginBase::m_ModuleConfigScene private
Definition at line 1118 of file pluginscenemanager.c.
m_ModuleDeveloper [1/2]
PluginDeveloper PluginBase::m_ModuleDeveloper private
Definition at line 3 of file plugincharplacement.c.
m_ModuleDeveloper [2/2]
protected PluginDeveloper PluginBase::m_ModuleDeveloper private
Definition at line 1117 of file pluginscenemanager.c.
m_MouseBindings
protected ref array<ref MouseBinding> PluginBase::m_MouseBindings private
Definition at line 282 of file pluginkeybinding.c.
m_MouseButtons
protected ref array<ref MouseButtonInfo> PluginBase::m_MouseButtons private
Definition at line 281 of file pluginkeybinding.c.
m_MovementSpeedEB
EditBoxWidget PluginBase::m_MovementSpeedEB private
Definition at line 57 of file plugindayzinfecteddebug.c.
m_NotifiersIcons
private ref multiMap<int, string> PluginBase::m_NotifiersIcons private
Definition at line 6 of file pluginplayerstatus.c.
m_NotifiersIndexColor
ref multiMap<int, int> PluginBase::m_NotifiersIndexColor private
Definition at line 4 of file pluginplayerstatus.c.
m_NotifiersLabel
ref multiMap<int, string> PluginBase::m_NotifiersLabel private
Definition at line 3 of file pluginplayerstatus.c.
m_Pid
string PluginBase::m_Pid private
Definition at line 4 of file pluginadminlog.c.
m_PlacementFilter
protected int PluginBase::m_PlacementFilter private
Definition at line 22 of file pluginadminlog.c.
m_PlantMaterials
ref map<string, ref PlantMaterialHealth> PluginBase::m_PlantMaterials private
Definition at line 3 of file pluginhorticulture.c.
m_Player [1/2]
PlayerBase PluginBase::m_Player private
Definition at line 12 of file pluginadminlog.c.
m_Player [2/2]
protected PlayerBase PluginBase::m_Player private
Definition at line 12 of file pluginuniversaltemperaturesourceclient.c.
m_PlayerAgentsSynced
ref array<ref SyncedValueAgent> PluginBase::m_PlayerAgentsSynced private
Definition at line 37 of file plugindevelopersync.c.
m_PlayerArray
autoptr array<Man> PluginBase::m_PlayerArray private
Definition at line 27 of file pluginadminlog.c.
m_PlayerDebugDamage
ref map<PlayerBase, ref RemotePlayerDamageDebug> PluginBase::m_PlayerDebugDamage = new map<PlayerBase, ref RemotePlayerDamageDebug> private
Definition at line 7 of file pluginremoteplayerdebugserver.c.
m_PlayerDebugStats
ref array<ref RemotePlayerStatDebug> PluginBase::m_PlayerDebugStats = new array<ref RemotePlayerStatDebug> private
Definition at line 6 of file pluginremoteplayerdebugserver.c.
m_PlayerLevelsSynced
ref array<ref SyncedValueLevel> PluginBase::m_PlayerLevelsSynced private
Definition at line 33 of file plugindevelopersync.c.
m_PlayerListFilter
protected int PluginBase::m_PlayerListFilter private
Definition at line 24 of file pluginadminlog.c.
m_PlayerModsDetailedSynced
string PluginBase::m_PlayerModsDetailedSynced private
Definition at line 35 of file plugindevelopersync.c.
m_PlayerModsSynced
ref array<ref SyncedValueModifier> PluginBase::m_PlayerModsSynced private
Definition at line 34 of file plugindevelopersync.c.
m_PlayerName
string PluginBase::m_PlayerName private
Definition at line 3 of file pluginadminlog.c.
m_PlayerPrefix
string PluginBase::m_PlayerPrefix private
Definition at line 6 of file pluginadminlog.c.
m_PlayerPrefix2
string PluginBase::m_PlayerPrefix2 private
Definition at line 7 of file pluginadminlog.c.
m_PlayerStatsSynced
ref array<ref SyncedValue> PluginBase::m_PlayerStatsSynced private
Definition at line 31 of file plugindevelopersync.c.
m_PlayerStomachSynced
ref array<ref Param> PluginBase::m_PlayerStomachSynced private
Definition at line 32 of file plugindevelopersync.c.
m_PosArray
string PluginBase::m_PosArray[3] private
Definition at line 15 of file pluginadminlog.c.
m_Position
vector PluginBase::m_Position private
Definition at line 5 of file pluginadminlog.c.
m_PressedMouseID
protected int PluginBase::m_PressedMouseID private
Definition at line 1125 of file pluginscenemanager.c.
m_pUIHandler
ref PluginDayZInfectedDebugUIHandler PluginBase::m_pUIHandler private
Definition at line 95 of file plugindayzinfecteddebug.c.
m_ReadOnly
bool PluginBase::m_ReadOnly private
Definition at line 19 of file pluginfilehandler.c.
m_RegisteredPlayers
ref map<PlayerBase, ref RegisterPlayerData> PluginBase::m_RegisteredPlayers private
Definition at line 29 of file plugindevelopersync.c.
m_RootWidget
protected ref Widget PluginBase::m_RootWidget[MAX_SIMULTANEOUS_UTS] private
Definition at line 9 of file pluginuniversaltemperaturesourceclient.c.
m_Ruler
ItemBase PluginBase::m_Ruler private
Definition at line 4 of file plugindoorruler.c.
m_RulerActivated
bool PluginBase::m_RulerActivated private
Definition at line 8 of file pluginscenemanager.c.
m_RulerLines
ref array<Shape> PluginBase::m_RulerLines private
Definition at line 10 of file pluginscenemanager.c.
m_RulerPoints
ref array<vector> PluginBase::m_RulerPoints private
Definition at line 9 of file pluginscenemanager.c.
m_RulerSpheres
ref array<Shape> PluginBase::m_RulerSpheres private
Definition at line 11 of file pluginscenemanager.c.
m_SceneData
protected ref SceneData PluginBase::m_SceneData private
Definition at line 1129 of file pluginscenemanager.c.
m_ScriptConsole
UIScriptedMenu PluginBase::m_ScriptConsole private
Definition at line 5 of file plugindeveloper.c.
m_SelectedObject
protected SceneObject PluginBase::m_SelectedObject private
Definition at line 1130 of file pluginscenemanager.c.
m_ShapesSceneObjects
protected ref array<Shape> PluginBase::m_ShapesSceneObjects private
Definition at line 1127 of file pluginscenemanager.c.
m_SimpleAgentList
ref map<int, string> PluginBase::m_SimpleAgentList = new map<int, string> private
Definition at line 11 of file plugintransmissionagents.c.
Referenced by GetSimpleAgentList().
m_soundBuilder
ref SoundObjectBuilder PluginBase::m_soundBuilder private
Definition at line 176 of file pluginsounddebug.c.
m_soundObject
ref SoundObject PluginBase::m_soundObject private
Definition at line 177 of file pluginsounddebug.c.
m_soundParams
ref SoundParams PluginBase::m_soundParams private
Definition at line 175 of file pluginsounddebug.c.
m_Source
PlayerBase PluginBase::m_Source private
Definition at line 13 of file pluginadminlog.c.
m_SpawnEntityButton
ButtonWidget PluginBase::m_SpawnEntityButton private
Definition at line 47 of file plugindayzinfecteddebug.c.
m_StanceCB
XComboBoxWidget PluginBase::m_StanceCB private
movement card
Definition at line 55 of file plugindayzinfecteddebug.c.
m_StartAttackButton
ButtonWidget PluginBase::m_StartAttackButton private
Definition at line 81 of file plugindayzinfecteddebug.c.
m_StartCrawlingButton
ButtonWidget PluginBase::m_StartCrawlingButton private
Definition at line 68 of file plugindayzinfecteddebug.c.
m_StartDeathButton
ButtonWidget PluginBase::m_StartDeathButton private
Definition at line 77 of file plugindayzinfecteddebug.c.
m_StartHitButton
ButtonWidget PluginBase::m_StartHitButton private
Definition at line 74 of file plugindayzinfecteddebug.c.
m_StartTurnButton
ButtonWidget PluginBase::m_StartTurnButton private
Definition at line 59 of file plugindayzinfecteddebug.c.
m_StartVaultButton
ButtonWidget PluginBase::m_StartVaultButton private
Definition at line 64 of file plugindayzinfecteddebug.c.
m_StatEnergy
PlayerStat<float> PluginBase::m_StatEnergy private
Definition at line 18 of file pluginadminlog.c.
m_StatListWidgets
protected ref TextListboxWidget PluginBase::m_StatListWidgets[MAX_SIMULTANEOUS_UTS] private
Definition at line 10 of file pluginuniversaltemperaturesourceclient.c.
m_StatsUpdateStatus
bool PluginBase::m_StatsUpdateStatus private
Definition at line 39 of file plugindevelopersync.c.
m_StatusText
TextWidget PluginBase::m_StatusText private
Definition at line 52 of file plugindayzinfecteddebug.c.
m_StatWater
PlayerStat<float> PluginBase::m_StatWater private
Definition at line 17 of file pluginadminlog.c.
m_StomachUpdateStatus
bool PluginBase::m_StomachUpdateStatus private
Definition at line 43 of file plugindevelopersync.c.
m_TickTimer
ref Timer PluginBase::m_TickTimer private
status refresh timer
Definition at line 99 of file plugindayzinfecteddebug.c.
m_TimeLastClickPress
protected float PluginBase::m_TimeLastClickPress private
Definition at line 1124 of file pluginscenemanager.c.
m_TimeLastClickRelease
protected float PluginBase::m_TimeLastClickRelease private
Definition at line 1123 of file pluginscenemanager.c.
m_Timer
ref Timer PluginBase::m_Timer private
Definition at line 26 of file pluginadminlog.c.
m_TurnDirectionEB
EditBoxWidget PluginBase::m_TurnDirectionEB private
Definition at line 61 of file plugindayzinfecteddebug.c.
m_TurnTypeCB
XComboBoxWidget PluginBase::m_TurnTypeCB private
Definition at line 60 of file plugindayzinfecteddebug.c.
m_UpdateTimer
ref Timer PluginBase::m_UpdateTimer private
Definition at line 28 of file plugindevelopersync.c.
m_UTemperatureSourceDebugs
protected ref array< ref UTemperatureSourceDebug > PluginBase::m_UTemperatureSourceDebugs private
Definition at line 7 of file pluginuniversaltemperaturesourceclient.c.
m_UTSAverageTemperature
protected float PluginBase::m_UTSAverageTemperature private
Definition at line 5 of file pluginuniversaltemperaturesourceclient.c.
m_Variables
ref map<int, string> PluginBase::m_Variables private
Definition at line 25 of file pluginvariables.c.
m_VaultingCB
XComboBoxWidget PluginBase::m_VaultingCB private
Definition at line 63 of file plugindayzinfecteddebug.c.
m_Watching
bool PluginBase::m_Watching private
Definition at line 12 of file pluginremoteplayerdebugserver.c.
Referenced by GetWatching().
m_wave
AbstractWave PluginBase::m_wave private
Definition at line 180 of file pluginsounddebug.c.
MAX_SIMULTANEOUS_UTS
const int PluginBase::MAX_SIMULTANEOUS_UTS = 10 private
Definition at line 3 of file pluginuniversaltemperaturesourceclient.c.
Referenced by EnableWidgets(), InitWidgets(), and UpdateStatWidgets().
PLAYER
PlayerBase PluginBase::PLAYER static private
Definition at line 5 of file pluginscenemanager.c.
SCENE_DEFAULT_NAME
string PluginBase::SCENE_DEFAULT_NAME = "default" static private
Definition at line 3 of file pluginscenemanager.c.
SCENE_EDITOR_CMD_POPUP
const int PluginBase::SCENE_EDITOR_CMD_POPUP = 1 static private
Definition at line 14 of file pluginscenemanager.c.
SCENE_EDITOR_CMD_REFRESH
const int PluginBase::SCENE_EDITOR_CMD_REFRESH = 0 static private
Definition at line 13 of file pluginscenemanager.c.
SCENE_EDITOR_CMD_SAVE
const int PluginBase::SCENE_EDITOR_CMD_SAVE = 2 static private
Definition at line 15 of file pluginscenemanager.c.
SCENE_SUFIX
string PluginBase::SCENE_SUFIX = "scene" static private
Definition at line 4 of file pluginscenemanager.c.
TICK_RATE
private const float PluginBase::TICK_RATE = 10 private
Definition at line 6 of file pluginobjectsinteractionmanager.c.
Referenced by Decay().
TIME_TO_FORCED_UNLOCK
private const float PluginBase::TIME_TO_FORCED_UNLOCK = 60 private
Definition at line 5 of file pluginobjectsinteractionmanager.c.
TIMER_PLAYERLIST
const int PluginBase::TIMER_PLAYERLIST = GetPlayerListTimer() private
Definition at line 28 of file pluginadminlog.c.