DayzKode: ActionRepairCarEngine Class Reference
ActionRepairCarEngine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRepairCarEngine ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Private Attributes
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
m_LastValidType
Detailed Description
Definition at line 19 of file actionrepaircarengine.c.
Constructor & Destructor Documentation
ActionRepairCarEngine()
void ActionRepairCarEngine::ActionRepairCarEngine () inline private
Definition at line 25 of file actionrepaircarengine.c.
    {
        m_CallbackClass = ActionRepairTentPartCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        //m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;// | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_FullBody = true;
        m_LockTargetOnUse = false;
        m_Text = "#repair";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepairCarEngine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 44 of file actionrepaircarengine.c.
    {
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        //m_CurrentDamageZone = "";
        Object targetObject = target.GetObject();
        Object targetParent = target.GetParent();
        CarScript car = CarScript.Cast( targetObject );
        EntityAI carEntity = EntityAI.Cast( targetObject );
        if ( !car || !player )
            return false;
         //m_MaximalActionDistance;
        //float distance = Math.AbsFloat( vector.Distance( car.GetPosition(),player.GetPosition() ));
        //if ( distance <= MAX_ACTION_DIST )
        //{
            if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
                return true;
            array<string> selections = new array<string>;
            PluginRepairing module_repairing;
            Class.CastTo( module_repairing, GetPlugin(PluginRepairing) );
            targetObject.GetActionComponentNameList( target.GetComponentIndex(), selections, LOD.NAME_VIEW);
            if (m_LastValidType != target.Type() || m_LastValidComponentIndex != target.GetComponentIndex() || m_CurrentDamageZone == "" )
            {
                string damageZone = "";
                string compName = "";
                for ( int s = 0; s < selections.Count(); s++ )
                {
                    compName = selections[s];
                    //NOTE: relevant fire geometry and view geometry selection names MUST match in order to get a valid damage zone
                    if ( carEntity && DamageSystem.GetDamageZoneFromComponentName( carEntity, compName, damageZone ))
                    {
                        int zoneHP = car.GetHealthLevel( damageZone );
                        if (zoneHP > GameConstants.STATE_WORN && zoneHP < GameConstants.STATE_RUINED)
{
                            m_CurrentDamageZone = damageZone;
                            m_LastValidComponentIndex = target.GetComponentIndex();
                            vector repairPos = carEntity.GetPosition();
                            //Exclude all zones except engine
                            if ( damageZone != "Engine")
                                return false;
                            else
                                repairPos = car.GetEnginePosWS();
                            /*float dist = vector.DistanceSq( repairPos, player.GetPosition() );
                            if ( dist < MAX_ACTION_DIST * MAX_ACTION_DIST)*/
                                return true;
                        }
                    }
                }
            //}
        }
        return false;
    }
References Class::CastTo(), GetGame(), GetPlugin(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, LOD::NAME_VIEW, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
CreateActionData()
override ActionData ActionRepairCarEngine::CreateActionData () inline private
Definition at line 164 of file actionrepaircarengine.c.
    {
        RepairCarPartActionData action_data = new RepairCarPartActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionRepairCarEngine::CreateConditionComponents () inline private
Definition at line 38 of file actionrepaircarengine.c.
    {
        m_ConditionItem = new CCINonRuined; //To change?
        m_ConditionTarget   = new CCTCursor(UAMaxDistances.REPAIR);
    }
References m_ConditionItem, m_ConditionTarget, and UAMaxDistances::REPAIR.
HandleReciveData()
override void ActionRepairCarEngine::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 202 of file actionrepaircarengine.c.
    {
        super.HandleReciveData( action_recive_data, action_data );
        RepairCarPartActionReciveData recive_data_repair = RepairCarPartActionReciveData.Cast( action_recive_data );
        RepairCarPartActionData.Cast( action_data ).m_DamageZone = recive_data_repair.m_DamageZoneRecived;
    }
References RepairCarPartActionReciveData::m_DamageZoneRecived.
OnFinishProgressServer()
override void ActionRepairCarEngine::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 111 of file actionrepaircarengine.c.
    {
        Object tgObject = action_data.m_Target.GetObject();
        ItemBase usedItem = action_data.m_MainItem;
        string damageZone = RepairCarPartActionData.Cast(action_data).m_DamageZone;
        if ( !GetGame().IsMultiplayer() )
            damageZone = m_CurrentDamageZone;
        if ( tgObject && damageZone != "" )
        {
            CarScript car = CarScript.Cast( tgObject );
            if ( car )
            {
                int newDmgLevel = car.GetHealthLevel( damageZone ) - 1;
                if ( newDmgLevel < 0 )
                    newDmgLevel = 0;
                float zoneMax = car.GetMaxHealth(damageZone,"");
                float dmgStateValue = zoneMax * GameConstants.DAMAGE_WORN_VALUE;
                float randomValue = Math.RandomFloatInclusive( zoneMax * 0.05, zoneMax * 0.15);
                switch ( newDmgLevel )
                {
                    case GameConstants.STATE_BADLY_DAMAGED:
                        car.SetHealth( damageZone, "", (zoneMax * GameConstants.DAMAGE_RUINED_VALUE) + randomValue );
                        break;
                    case GameConstants.STATE_DAMAGED:
                        car.SetHealth( damageZone, "", (zoneMax * GameConstants.DAMAGE_BADLY_DAMAGED_VALUE) + randomValue );
                        break;
                    case GameConstants.STATE_WORN:
                        car.SetHealth( damageZone, "", (zoneMax * GameConstants.DAMAGE_DAMAGED_VALUE) + randomValue );
                        break;
                    case GameConstants.STATE_PRISTINE:
                        car.SetHealth( damageZone, "", (zoneMax * GameConstants.DAMAGE_WORN_VALUE) + randomValue );
                        break;
                    default:
                        break;
                }
                MiscGameplayFunctions.DealAbsoluteDmg(usedItem, UADamageApplied.BUILD);
            }
        }
    }
References UADamageApplied::BUILD, GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GameConstants::DAMAGE_WORN_VALUE, GetGame(), m_CurrentDamageZone, ActionData::m_MainItem, ActionData::m_Target, Math::RandomFloatInclusive(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_PRISTINE, and GameConstants::STATE_WORN.
ReadFromContext()
override bool ActionRepairCarEngine::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 182 of file actionrepaircarengine.c.
    {
        if ( !action_recive_data )
            action_recive_data = new RepairCarPartActionReciveData;
        super.ReadFromContext( ctx, action_recive_data );
        RepairCarPartActionReciveData recive_data_repair = RepairCarPartActionReciveData.Cast( action_recive_data );
        if ( HasTarget() )
        {
            string zone;
            if ( !ctx.Read( zone ) )
                return false;
            recive_data_repair.m_DamageZoneRecived = zone;
        }
        return true;
    }
References HasTarget(), RepairCarPartActionReciveData::m_DamageZoneRecived, and Serializer::Read().
WriteToContext()
override void ActionRepairCarEngine::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 170 of file actionrepaircarengine.c.
    {
        super.WriteToContext( ctx, action_data );
        RepairCarPartActionData repair_action_data;
        if ( HasTarget() && Class.CastTo( repair_action_data,action_data ) )
        {
            repair_action_data.m_DamageZone = m_CurrentDamageZone;
            ctx.Write(repair_action_data.m_DamageZone);
        }
    }
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Member Data Documentation
m_CurrentDamageZone
string ActionRepairCarEngine::m_CurrentDamageZone = "" private
Definition at line 22 of file actionrepaircarengine.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int ActionRepairCarEngine::m_LastValidComponentIndex = -1 private
Definition at line 23 of file actionrepaircarengine.c.
Referenced by ActionCondition().
m_LastValidType
ActionRepairCarEngine::m_LastValidType private
Definition at line 21 of file actionrepaircarengine.c.
Referenced by ActionCondition().