DayzKode: ActionOpenBarrel Class Reference
ActionOpenBarrel Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionOpenBarrel ()
override void OnEndServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actionopenbarrel.c.
Constructor & Destructor Documentation
ActionOpenBarrel()
void ActionOpenBarrel::ActionOpenBarrel () inline private
Definition at line 3 of file actionopenbarrel.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_INTERACTONCE;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#open";
    }
References AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionOpenBarrel::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 10 of file actionopenbarrel.c.
    {
        Object target_object = target.GetObject();
        if ( target_object.IsItemBase() )
        {
            Barrel_ColorBase ntarget = Barrel_ColorBase.Cast( target_object );
            if( ntarget )
            {
                if( !ntarget.IsLocked() && !ntarget.IsOpen() )
                {
                    return true;
                }
            }
        }
        return false;
    }
References Barrel_ColorBase::IsLocked(), and Barrel_ColorBase::IsOpen().
OnEndServer()
override void ActionOpenBarrel::OnEndServer (ActionData action_data) inline private
Definition at line 37 of file actionopenbarrel.c.
    {
        Object target_object = action_data.m_Target.GetObject();
        Barrel_ColorBase ntarget = Barrel_ColorBase.Cast( target_object );
        if( ntarget )
        {
            ntarget.SoundSynchRemoteReset();
        }
    }
References ActionData::m_Target.
OnExecuteServer()
override void ActionOpenBarrel::OnExecuteServer (ActionData action_data) inline private
Definition at line 27 of file actionopenbarrel.c.
    {
        Object target_object = action_data.m_Target.GetObject();
        Barrel_ColorBase ntarget = Barrel_ColorBase.Cast( target_object );
        if( ntarget )
        {
            ntarget.Open();
        }
    }
References ActionData::m_Target, and Barrel_ColorBase::Open().