DayzKode: WeaponStateJammed Class Reference
WeaponStateJammed Class Reference
handle jamming state set jam/unjam state for weapon
Private Member Functions
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override int GetCurrentStateID ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasBullet ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override bool HasMagazine ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override void InitMuzzleArray ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsBoltOpen ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsJammed ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override bool IsRepairEnabled ()
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
Detailed Description
handle jamming state set jam/unjam state for weapon
Definition at line 52 of file sks.c.
Member Function Documentation
GetCurrentStateID() [1/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 56 of file sks.c.
{ return SKSStableStateID.SKS_JAM_BU1; }
GetCurrentStateID() [2/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 90 of file boltactionrifleexternalmagazine_base.c.
{ return BAREMStableStateID.BAREM_JAM_BU1_MA0; }
GetCurrentStateID() [3/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 102 of file boltactionrifleexternalmagazine_base.c.
{ return BAREMStableStateID.BAREM_JAM_BU1_MA1; }
GetCurrentStateID() [4/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 55 of file boltactionrifleinnermagazine_base.c.
{ return BARIMStableStateID.LoadedJammed; }
GetCurrentStateID() [5/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 64 of file pistol_base.c.
{ return PistolStableStateID.CLO_JAM_BU1_MA0; }
GetCurrentStateID() [6/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 110 of file pistol_base.c.
{ return PistolStableStateID.CLO_JAM_BU1_MA1; }
GetCurrentStateID() [7/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 55 of file repeater.c.
{ return RPTStableStateID.LoadedJammed; }
GetCurrentStateID() [8/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 66 of file rifleboltfree_base.c.
{ return RBFStableStateID.RBF_JAM_BU1_MA0; }
GetCurrentStateID() [9/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 78 of file rifleboltfree_base.c.
{ return RBFStableStateID.RBF_JAM_BU1_MA1; }
GetCurrentStateID() [10/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 93 of file rifleboltlock_base.c.
{ return RBLStableStateID.RBL_JAM_BU1_MA0; }
GetCurrentStateID() [11/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 105 of file rifleboltlock_base.c.
{ return RBLStableStateID.RBL_JAM_BU1_MA1; }
GetCurrentStateID() [12/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 52 of file riflesingleshot_base.c.
{ return RSSStableStateID.Jammed; }
GetCurrentStateID() [13/13]
override int WeaponStateJammed::GetCurrentStateID () inline private
Definition at line 52 of file mp133.c.
{ return PumpShotgunStableStateID.Jammed; }
HasBullet() [1/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 57 of file sks.c.
{ return true; }
HasBullet() [2/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 91 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
HasBullet() [3/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 103 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
HasBullet() [4/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 56 of file boltactionrifleinnermagazine_base.c.
{ return true; }
HasBullet() [5/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 65 of file pistol_base.c.
{ return true; }
HasBullet() [6/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 111 of file pistol_base.c.
{ return true; }
HasBullet() [7/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 56 of file repeater.c.
{ return true; }
HasBullet() [8/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 67 of file rifleboltfree_base.c.
{ return true; }
HasBullet() [9/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 79 of file rifleboltfree_base.c.
{ return true; }
HasBullet() [10/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 94 of file rifleboltlock_base.c.
{ return true; }
HasBullet() [11/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 106 of file rifleboltlock_base.c.
{ return true; }
HasBullet() [12/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 53 of file riflesingleshot_base.c.
{ return true; }
HasBullet() [13/13]
override bool WeaponStateJammed::HasBullet () inline private
Definition at line 53 of file mp133.c.
{ return true; }
HasMagazine() [1/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 58 of file sks.c.
{ return false; }
HasMagazine() [2/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 92 of file boltactionrifleexternalmagazine_base.c.
{ return false; }
HasMagazine() [3/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 104 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
HasMagazine() [4/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 57 of file boltactionrifleinnermagazine_base.c.
{ return false; }
HasMagazine() [5/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 66 of file pistol_base.c.
{ return false; }
HasMagazine() [6/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 112 of file pistol_base.c.
{ return true; }
HasMagazine() [7/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 57 of file repeater.c.
{ return false; }
HasMagazine() [8/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 68 of file rifleboltfree_base.c.
{ return false; }
HasMagazine() [9/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 80 of file rifleboltfree_base.c.
{ return true; }
HasMagazine() [10/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 95 of file rifleboltlock_base.c.
{ return false; }
HasMagazine() [11/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 107 of file rifleboltlock_base.c.
{ return true; }
HasMagazine() [12/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 54 of file riflesingleshot_base.c.
{ return false; }
HasMagazine() [13/13]
override bool WeaponStateJammed::HasMagazine () inline private
Definition at line 54 of file mp133.c.
{ return false; }
InitMuzzleArray() [1/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 62 of file sks.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [2/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 96 of file boltactionrifleexternalmagazine_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [3/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 108 of file boltactionrifleexternalmagazine_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [4/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 60 of file boltactionrifleinnermagazine_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [5/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 70 of file pistol_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [6/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 116 of file pistol_base.c.
{ m_muzzleHasBullet = {MuzzleState.L}; }
References m_muzzleHasBullet.
InitMuzzleArray() [7/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 60 of file repeater.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [8/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 72 of file rifleboltfree_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [9/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 84 of file rifleboltfree_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [10/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 99 of file rifleboltlock_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [11/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 111 of file rifleboltlock_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [12/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 58 of file riflesingleshot_base.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
InitMuzzleArray() [13/13]
override void WeaponStateJammed::InitMuzzleArray () inline private
Definition at line 58 of file mp133.c.
{ m_muzzleHasBullet = {MuzzleState.F}; }
References m_muzzleHasBullet.
IsBoltOpen() [1/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 60 of file sks.c.
{ return true; }
IsBoltOpen() [2/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 94 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsBoltOpen() [3/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 106 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsBoltOpen() [4/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 68 of file pistol_base.c.
{ return true; }
IsBoltOpen() [5/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 114 of file pistol_base.c.
{ return true; }
IsBoltOpen() [6/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 70 of file rifleboltfree_base.c.
{ return true; }
IsBoltOpen() [7/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 82 of file rifleboltfree_base.c.
{ return true; }
IsBoltOpen() [8/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 97 of file rifleboltlock_base.c.
{ return true; }
IsBoltOpen() [9/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 109 of file rifleboltlock_base.c.
{ return true; }
IsBoltOpen() [10/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 56 of file riflesingleshot_base.c.
{ return true; }
IsBoltOpen() [11/11]
override bool WeaponStateJammed::IsBoltOpen () inline private
Definition at line 56 of file mp133.c.
{ return true; }
IsJammed() [1/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 59 of file sks.c.
{ return true; }
IsJammed() [2/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 93 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsJammed() [3/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 105 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsJammed() [4/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 58 of file boltactionrifleinnermagazine_base.c.
{ return true; }
IsJammed() [5/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 67 of file pistol_base.c.
{ return true; }
IsJammed() [6/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 113 of file pistol_base.c.
{ return true; }
IsJammed() [7/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 58 of file repeater.c.
{ return true; }
IsJammed() [8/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 69 of file rifleboltfree_base.c.
{ return true; }
IsJammed() [9/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 81 of file rifleboltfree_base.c.
{ return true; }
IsJammed() [10/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 96 of file rifleboltlock_base.c.
{ return true; }
IsJammed() [11/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 108 of file rifleboltlock_base.c.
{ return true; }
IsJammed() [12/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 55 of file riflesingleshot_base.c.
{ return true; }
IsJammed() [13/13]
override bool WeaponStateJammed::IsJammed () inline private
Definition at line 55 of file mp133.c.
{ return true; }
IsRepairEnabled() [1/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 61 of file sks.c.
{ return true; }
IsRepairEnabled() [2/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 95 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsRepairEnabled() [3/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 107 of file boltactionrifleexternalmagazine_base.c.
{ return true; }
IsRepairEnabled() [4/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 59 of file boltactionrifleinnermagazine_base.c.
{ return true; }
IsRepairEnabled() [5/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 69 of file pistol_base.c.
{ return true; }
IsRepairEnabled() [6/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 115 of file pistol_base.c.
{ return true; }
IsRepairEnabled() [7/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 59 of file repeater.c.
{ return true; }
IsRepairEnabled() [8/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 71 of file rifleboltfree_base.c.
{ return true; }
IsRepairEnabled() [9/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 83 of file rifleboltfree_base.c.
{ return true; }
IsRepairEnabled() [10/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 98 of file rifleboltlock_base.c.
{ return true; }
IsRepairEnabled() [11/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 110 of file rifleboltlock_base.c.
{ return true; }
IsRepairEnabled() [12/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 57 of file riflesingleshot_base.c.
{ return true; }
IsRepairEnabled() [13/13]
override bool WeaponStateJammed::IsRepairEnabled () inline private
Definition at line 57 of file mp133.c.
{ return true; }
OnEntry() [1/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 54 of file sks.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [2/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 88 of file boltactionrifleexternalmagazine_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet nomag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [3/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 100 of file boltactionrifleexternalmagazine_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet mag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [4/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 53 of file boltactionrifleinnermagazine_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedJammed JF"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [5/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 62 of file pistol_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnstate] { CJF0 closed jammed bullet nomag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [6/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 108 of file pistol_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnstate] { CJF1 closed jammed bullet mag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnEntry() [7/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 53 of file repeater.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { LoadedJammed JF"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [8/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 64 of file rifleboltfree_base.c.
{ Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet nomag"); super.OnEntry(e); }
References m_weapon, and Print().
OnEntry() [9/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 76 of file rifleboltfree_base.c.
{ Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet mag"); super.OnEntry(e); }
References m_weapon, and Print().
OnEntry() [10/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 91 of file rifleboltlock_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet nomag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [11/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 103 of file rifleboltlock_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { jammed bullet mag"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [12/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file riflesingleshot_base.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Jammed J"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnEntry() [13/13]
override void WeaponStateJammed::OnEntry (WeaponEventBase e) inline private
Definition at line 50 of file mp133.c.
{ if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { Jammed L_J"); } super.OnEntry(e); }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [1/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 55 of file sks.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [2/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 89 of file boltactionrifleexternalmagazine_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet nomag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [3/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 101 of file boltactionrifleexternalmagazine_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet mag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [4/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 54 of file boltactionrifleinnermagazine_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedJammed JF"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [5/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 63 of file pistol_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnstate] } CJF0 closed jammed bullet nomag"); } }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [6/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 109 of file pistol_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnstate] } CJF1 closed jammed bullet mag"); } }
References LogManager::IsWeaponLogEnable(), and wpnPrint().
OnExit() [7/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 54 of file repeater.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } LoadedJammed JF"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [8/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 65 of file rifleboltfree_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet nomag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [9/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 77 of file rifleboltfree_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet mag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [10/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 92 of file rifleboltlock_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet nomag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [11/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 104 of file rifleboltlock_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } jammed bullet mag"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [12/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 51 of file riflesingleshot_base.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Jammed J"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().
OnExit() [13/13]
override void WeaponStateJammed::OnExit (WeaponEventBase e) inline private
Definition at line 51 of file mp133.c.
{ super.OnExit(e); if (LogManager.IsWeaponLogEnable()) { wpnPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } Jammed L_J"); } }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnPrint().