DayzKode: CAContinuousWaterPlant Class Reference
CAContinuousWaterPlant Class Reference
Private Member Functions
void CAContinuousWaterPlant (float quantity_used_per_second)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_PlantThirstyness
protected float m_TimeToComplete
Detailed Description
Definition at line 1 of file cacontinuouswaterplant.c.
Constructor & Destructor Documentation
CAContinuousWaterPlant()
void CAContinuousWaterPlant::CAContinuousWaterPlant (float quantity_used_per_second) inline private
Definition at line 6 of file cacontinuouswaterplant.c.
    {
        m_QuantityUsedPerSecond = quantity_used_per_second;
    }
References CAContinuousQuantity::m_QuantityUsedPerSecond.
Member Function Documentation
Execute()
override int CAContinuousWaterPlant::Execute (ActionData action_data) inline private
Definition at line 38 of file cacontinuouswaterplant.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        if ( m_ItemQuantity <= 0 )
        {
            return UA_FINISHED;
        }
        else
        {
            if ( m_SpentQuantity < m_ItemQuantity  &&  m_SpentQuantity < m_PlantThirstyness )
            {
                m_AdjustedQuantityUsedPerSecond = action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( m_QuantityUsedPerSecond, m_Action.GetSpecialtyWeight(), true);
                m_SpentQuantity += m_QuantityUsedPerSecond * action_data.m_Player.GetDeltaT();
                if ( m_Action )
                {
                    PlantBase plant;
                    Class.CastTo(plant,  action_data.m_Target.GetObject() );
                    Slot slot = plant.GetSlot();
                    slot.GiveWater( m_SpentQuantity );
                }
                return UA_PROCESSING;
            }
            else
            {
                CalcAndSetQuantity( action_data );
                OnCompletePogress(action_data);
                return UA_FINISHED;
            }
        }
    }
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, CAContinuousQuantity::m_AdjustedQuantityUsedPerSecond, CAContinuousQuantity::m_ItemQuantity, m_PlantThirstyness, ActionData::m_Player, CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, ActionData::m_Target, CAContinuousBase::OnCompletePogress(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousWaterPlant::GetProgress () inline private
Definition at line 74 of file cacontinuouswaterplant.c.
    {
        //float progress = (m_SpentQuantity*m_QuantityUsedPerSecond)/m_TimeToComplete;
        return (m_SpentQuantity*m_QuantityUsedPerSecond)/m_TimeToComplete;
    }
References CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, and m_TimeToComplete.
Setup()
override void CAContinuousWaterPlant::Setup (ActionData action_data) inline private
Definition at line 11 of file cacontinuouswaterplant.c.
    {
        PlantBase target_PB;
        if (Class.CastTo(target_PB, action_data.m_Target.GetObject()))
        {
            m_SpentQuantity = 0;
            if ( !m_SpentUnits )
            {
                m_SpentUnits = new Param1<float>(0);
            }
            else
            {
                m_SpentUnits.param1 = 0;
            }
            if ( action_data.m_MainItem )
            {
                m_ItemQuantity = action_data.m_MainItem.GetQuantity();
            }
            if ( target_PB )
            {
                m_PlantThirstyness = target_PB.GetWaterMax() - target_PB.GetWater();
            }
            m_TimeToComplete = (Math.Min(m_PlantThirstyness,m_ItemQuantity))/m_QuantityUsedPerSecond;
        }
    }
References Class::CastTo(), CAContinuousQuantity::m_ItemQuantity, ActionData::m_MainItem, m_PlantThirstyness, CAContinuousQuantity::m_QuantityUsedPerSecond, CAContinuousQuantity::m_SpentQuantity, CAContinuousQuantity::m_SpentUnits, ActionData::m_Target, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_PlantThirstyness
protected float CAContinuousWaterPlant::m_PlantThirstyness private
Definition at line 3 of file cacontinuouswaterplant.c.
Referenced by Execute(), and Setup().
m_TimeToComplete
protected float CAContinuousWaterPlant::m_TimeToComplete private
Definition at line 4 of file cacontinuouswaterplant.c.
Referenced by GetProgress(), and Setup().