DayzKode: FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase > Class Reference
Private Member Functions
void AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t)
adds transition into transition table
void FSMBase ()
fsm transition table
FSMStateBase GetCurrentState ()
returns currently active state
bool IsRunning ()
returns true if machine is in running state
ProcessEventResult ProcessEvent (FSMEventBase e)
instructs the state machine to process the event e
protected ProcessEventResult ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e)
instructs the state machine to process the event locally - no hierarchy is crossed
void SetInitialState (FSMStateBase initial_state)
sets the initial_state for starting the machine
void Start (FSMEventBase initial_event=NULL)
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
void Terminate (FSMEventBase terminal_event=NULL)
terminates the state machine
void Update (float dt)
if machine running, call OnUpdate() on current state
Private Attributes
protected ref FSMEventBase m_initialEvent
configurable initial state of the machine
protected ref FSMStateBase m_initialState
current fsm state
protected ref FSMStateBase m_state
protected ref array< ref FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > > m_transitions
configurable initial event to start the machine (null by default)
Detailed Description
Definition at line 46 of file fsmbase.c.
Constructor & Destructor Documentation
FSMBase()
void FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FSMBase () inline private
fsm transition table
Definition at line 53 of file fsmbase.c.
    {
        m_transitions = new array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase>>;
    }
Member Function Documentation
AddTransition()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::AddTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t) inline private
adds transition into transition table
Definition at line 116 of file fsmbase.c.
    {
        m_transitions.Insert(t);
    }
GetCurrentState()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::GetCurrentState () inline private
returns currently active state
Returns
current state the FSM is in (or NULL)
Definition at line 62 of file fsmbase.c.
    {
        return m_state;
    }
IsRunning()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::IsRunning () inline private
returns true if machine is in running state
Definition at line 90 of file fsmbase.c.
{ return m_state != NULL; }
ProcessEvent()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent (FSMEventBase e) inline private
instructs the state machine to process the event e
Parameters
[in] e event that will be used to find suitable transition from current state
Returns
FSM_OK if transition found and allowed by guard (if any)
Definition at line 126 of file fsmbase.c.
    {
        FSMStateBase curr_state = m_state;
        int count = m_transitions.Count();
        for (int i = 0; i < count; ++i)
        {
            FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> row = m_transitions.Get(i);
            if (row.m_srcState.Type() == curr_state.Type() && row.m_event.Type() == e.Type())
            {
                FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> t = m_transitions.Get(i);
                bool hasGuard = t.m_guard != NULL;
                if (!hasGuard || (hasGuard && t.m_guard.GuardCondition(e)))     // 1) exec guard (if any)
                {
                    ProcessLocalTransition(t, e); // 2) process transition allowed by guard
                }
            }
        }
        return ProcessEventResult.FSM_NO_TRANSITION;
    }
ProcessLocalTransition()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessLocalTransition (FSMTransition< FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase > t, FSMEventBase e) inline private
instructs the state machine to process the event locally - no hierarchy is crossed
Parameters
[in] t the transition in m_transitions
[in] e event that will be used to process transition from current state
Returns
FSM_OK or FSM_TERMINATED
Definition at line 153 of file fsmbase.c.
    {
        fsmbDebugPrint("[fsm] (local) state=" + t.m_srcState.ToString() + "-------- event=" + e.ToString() + "[G=" + t.m_guard.ToString() +"]/A=" + t.m_action.ToString() + " --------|> dst=" + t.m_dstState.ToString());
        m_state.OnExit(e);          // 1) call onExit on old state
        if (t.m_action)
            t.m_action.Action(e);   // 2) execute transition action (if any)
        m_state = t.m_dstState;     // 3) change state to new
        if (t.m_dstState != NULL)
        {
            m_state.OnEntry(e);     // 4a) call onEntry on new state
            return ProcessEventResult.FSM_OK;
        }
        else
        {
            fsmbDebugPrint("[fsm] terminating fsm: state=" + t.m_srcState.ToString() + " event=" + e.ToString());
            return ProcessEventResult.FSM_TERMINATED; // 4b) or terminate
        }
    }
References fsmbDebugPrint().
SetInitialState()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::SetInitialState (FSMStateBase initial_state) inline private
sets the initial_state for starting the machine
Definition at line 70 of file fsmbase.c.
    {
        m_initialState = initial_state;
    }
Start()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start (FSMEventBase initial_event = NULL) inline private
starts the state machine by entering the initial_state (using intial_event as argument to initial state's onEntry)
Parameters
[in] e optional event for starting the machind
Definition at line 79 of file fsmbase.c.
    {
        fsmbDebugPrint("[fsm] " + this.ToString() + "::Start(" + initial_event.ToString() + "), init_state=" + m_initialState.ToString());
        m_state = m_initialState;
        m_state.OnEntry(initial_event);
    }
References fsmbDebugPrint(), ToString(), and string::ToString().
Terminate()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate (FSMEventBase terminal_event = NULL) inline private
terminates the state machine
Definition at line 95 of file fsmbase.c.
    {
        if (IsRunning())
        {
            m_state.OnExit(terminal_event);
            m_state = NULL;
        }
    }
References IsRunning().
Update()
FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Update (float dt) inline private
if machine running, call OnUpdate() on current state
Definition at line 107 of file fsmbase.c.
    {
        if (IsRunning())
            m_state.OnUpdate(dt);
    }
References IsRunning().
Member Data Documentation
m_initialEvent
protected ref FSMEventBase FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_initialEvent private
configurable initial state of the machine
Definition at line 50 of file fsmbase.c.
m_initialState
protected ref FSMStateBase FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_initialState private
current fsm state
Definition at line 49 of file fsmbase.c.
m_state
protected ref FSMStateBase FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_state private
Definition at line 48 of file fsmbase.c.
m_transitions
protected ref array<ref FSMTransition<FSMStateBase, FSMEventBase, FSMActionBase, FSMGuardBase> > FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::m_transitions private
configurable initial event to start the machine (null by default)
Definition at line 51 of file fsmbase.c.