DayzKode: AreaDamageBase Class Reference
AreaDamageBase Class Reference
Private Member Functions
void AreaDamageBase (EntityAI parent)
void AreaDamageOneTime (EntityAI parent)
void AreaDamageOneTimeDeferred (EntityAI parent)
void AreaDamageOneTimeRaycasted (EntityAI parent)
void AreaDamageOneTimeRaycastedDeferred (EntityAI parent)
void AreaDamageRegular (EntityAI parent)
void AreaDamageRegularRaycasted (EntityAI parent)
void AreaDamageRegularRaycastedDeferred (EntityAI parent)
protected void EvaluateDamage (Object object)
protected void EvaluateDamage_Common (Object object, string hitzone)
protected void EvaluateDamage_Defer (Object object)
protected void EvaluateDamage_DeferLoop (Object object)
protected void EvaluateDamage_Loop (Object object)
protected string GetRandomHitZone (array< string > hitzones)
protected string GetRaycastedHitZone (Object victim, array< string > raycast_sources_str)
void OnEnter (Object object)
events
void OnEnterClient (Object object)
void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
override void OnEnterServer (Object object)
void OnLeave (Object object)
void OnLeaveClient (Object object)
void OnLeaveServer (Object object)
override void SetDeferDuration (float time)
override void SetDeferDuration (float time)
override void SetDeferDuration (float time)
override void SetHitZones (array< string > hitzones)
override void SetHitZones (array< string > hitzones)
override void SetHitZones (array< string > hitzones)
override void SetLoopInterval (float time)
override void SetLoopInterval (float time)
override void SetLoopInterval (float time)
override void SetRaycastSources (array< string > raycast_sources)
override void SetRaycastSources (array< string > raycast_sources)
override void SetRaycastSources (array< string > raycast_sources)
override void SetRaycastSources (array< string > raycast_sources)
void ~AreaDamageOneTime ()
void ~AreaDamageOneTimeDeferred ()
void ~AreaDamageOneTimeRaycasted ()
void ~AreaDamageOneTimeRaycastedDeferred ()
void ~AreaDamageRegular ()
void ~AreaDamageRegularRaycasted ()
void ~AreaDamageRegularRaycastedDeferred ()
Private Attributes
protected string m_AmmoName
protected AreaDamageBase m_AreaDamage
protected int m_DamageType
protected float m_DeferDuration
protected ref Timer m_DeferTimer
protected ref array< string > m_HitZones
protected float m_LoopInterval
protected ref array< typename > m_DamageableTypes protected ref Timer m_LoopTimer
protected float m_OthersDamage
protected float m_PlayerDamage
protected ref array< string > m_RaycastSources
Detailed Description
Definition at line 3 of file areadamage.c.
Constructor & Destructor Documentation
AreaDamageBase()
void AreaDamageBase::AreaDamageBase (EntityAI parent) inline private
Definition at line 23 of file areadamage.c.
    {
        m_AreaDamage        = this;
        m_PlayerDamage      = 0.0;
        m_OthersDamage      = 0.0;
        m_AmmoName          = "MeleeDamage";
        m_DamageType        = DT_CUSTOM;
        m_LoopInterval      = 1.0;
        m_DeferDuration     = 1.0;
        m_HitZones          = new array<string>;
        m_RaycastSources    = new array<string>;
        m_DamageableTypes   = new array<typename>;
        m_DamageableTypes.Insert(DayZPlayer);
        m_LoopTimer         = new Timer(CALL_CATEGORY_SYSTEM);
        m_DeferTimer        = new Timer(CALL_CATEGORY_SYSTEM);
        m_TriggerBaseClass = "AreaDamageTrigger";
    }
References CALL_CATEGORY_SYSTEM, m_AmmoName, m_AreaDamage, m_DamageType, m_DeferDuration, m_DeferTimer, m_HitZones, m_LoopInterval, m_LoopTimer, m_OthersDamage, m_PlayerDamage, m_RaycastSources, and m_TriggerBaseClass.
~AreaDamageOneTime()
void AreaDamageBase::~AreaDamageOneTime () inline private
Definition at line 9 of file areadamageonetime.c.
{}
~AreaDamageOneTimeDeferred()
void AreaDamageBase::~AreaDamageOneTimeDeferred () inline private
Definition at line 9 of file areadamageonetimedeferred.c.
{}
~AreaDamageOneTimeRaycasted()
void AreaDamageBase::~AreaDamageOneTimeRaycasted () inline private
Definition at line 9 of file areadamageonetimeraycasted.c.
{}
~AreaDamageOneTimeRaycastedDeferred()
void AreaDamageBase::~AreaDamageOneTimeRaycastedDeferred () inline private
Definition at line 9 of file areadamageonetimeraycasteddeferred.c.
{}
~AreaDamageRegular()
void AreaDamageBase::~AreaDamageRegular () inline private
Definition at line 9 of file areadamageregular.c.
{}
~AreaDamageRegularRaycasted()
void AreaDamageBase::~AreaDamageRegularRaycasted () inline private
Definition at line 9 of file areadamageregularraycasted.c.
{}
~AreaDamageRegularRaycastedDeferred()
void AreaDamageBase::~AreaDamageRegularRaycastedDeferred () inline private
Definition at line 9 of file areadamageregularraycasteddeferred.c.
{}
Member Function Documentation
AreaDamageOneTime()
void AreaDamageBase::AreaDamageOneTime (EntityAI parent) inline private
Definition at line 4 of file areadamageonetime.c.
    {
    }
AreaDamageOneTimeDeferred()
void AreaDamageBase::AreaDamageOneTimeDeferred (EntityAI parent) inline private
Definition at line 4 of file areadamageonetimedeferred.c.
    {
    }
AreaDamageOneTimeRaycasted()
void AreaDamageBase::AreaDamageOneTimeRaycasted (EntityAI parent) inline private
Definition at line 4 of file areadamageonetimeraycasted.c.
    {
    }
AreaDamageOneTimeRaycastedDeferred()
void AreaDamageBase::AreaDamageOneTimeRaycastedDeferred (EntityAI parent) inline private
Definition at line 4 of file areadamageonetimeraycasteddeferred.c.
    {
    }
AreaDamageRegular()
void AreaDamageBase::AreaDamageRegular (EntityAI parent) inline private
Definition at line 4 of file areadamageregular.c.
    {
    }
AreaDamageRegularRaycasted()
void AreaDamageBase::AreaDamageRegularRaycasted (EntityAI parent) inline private
Definition at line 4 of file areadamageregularraycasted.c.
    {
    }
AreaDamageRegularRaycastedDeferred()
void AreaDamageBase::AreaDamageRegularRaycastedDeferred (EntityAI parent) inline private
Definition at line 4 of file areadamageregularraycasteddeferred.c.
    {
    }
EvaluateDamage()
protected void AreaDamageBase::EvaluateDamage (Object object) inline private
Definition at line 103 of file areadamage.c.
    {
        string hitzone;
        if ( m_RaycastSources.Count() )
        {
            hitzone = GetRaycastedHitZone(object, m_RaycastSources);
            EvaluateDamage_Common(object, hitzone);
        }
        else
        {
            hitzone = GetRandomHitZone(m_HitZones);
            EvaluateDamage_Common(object, hitzone);
        }
    }
References EvaluateDamage_Common(), GetRandomHitZone(), GetRaycastedHitZone(), m_HitZones, and m_RaycastSources.
Referenced by OnEnterServer().
EvaluateDamage_Common()
protected void AreaDamageBase::EvaluateDamage_Common (Object object, string hitzone) inline private
Definition at line 119 of file areadamage.c.
    {
        if ( object && object.IsAlive() )
        {
            if ( object.IsAnyInherited( m_DamageableTypes ) )
            {
                //If we are hitting an infected or animal, we increase the damage dealt as they do not bleed
                //Change is multiplier
                /*DayZInfected dayzInfected = DayZInfected.Cast(object);
                DayZAnimal dayzAnimal = DayZAnimal.Cast(object);
                EntityAI eai = EntityAI.Cast(object);
                if ( dayzInfected || dayzAnimal )
                {
                    //Agents should not take damage from fireplace, but just in case, keep multiplier relatively low
                    if ( hitzone )
                    {
                        eai.ProcessDirectDamage(m_DamageType, EntityAI.Cast(m_ParentObject), hitzone, m_AmmoName, "0.5 0.5 0.5", 8);
                    }
                    else
                        eai.ProcessDirectDamage(m_DamageType, EntityAI.Cast(m_ParentObject), "", m_AmmoName, "0.5 0.5 0.5", 8);
    }
                else*/
                {
                    object.ProcessDirectDamage(m_DamageType, m_ParentObject, hitzone, m_AmmoName, "0.5 0.5 0.5", 1);
                }
                PostDamageActions();
            }
        }
    }
References IsAlive(), IsAnyInherited(), m_AmmoName, m_DamageType, m_ParentObject, and PostDamageActions().
Referenced by EvaluateDamage().
EvaluateDamage_Defer()
protected void AreaDamageBase::EvaluateDamage_Defer (Object object) inline private
Definition at line 93 of file areadamage.c.
    {
        m_DeferTimer.Run(m_DeferDuration, this, "EvaluateDamage", new Param1<Object>(object), false);
    }
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_DeferLoop()
protected void AreaDamageBase::EvaluateDamage_DeferLoop (Object object) inline private
Definition at line 98 of file areadamage.c.
    {
        m_DeferTimer.Run(m_DeferDuration, this, "EvaluateDamage_Loop", new Param1<Object>(object), false);
    }
References m_DeferDuration, and m_DeferTimer.
Referenced by OnEnterServer().
EvaluateDamage_Loop()
protected void AreaDamageBase::EvaluateDamage_Loop (Object object) inline private
Definition at line 88 of file areadamage.c.
    {
        m_LoopTimer.Run(m_LoopInterval, this, "EvaluateDamage", new Param1<Object>(object), true);
    }
References m_LoopInterval, m_LoopTimer, and array::Run().
Referenced by OnEnterServer().
GetRandomHitZone()
protected string AreaDamageBase::GetRandomHitZone (array< string > hitzones) inline private
common
Definition at line 154 of file areadamage.c.
    {
        Math.Randomize(-1);
        int idx = Math.RandomInt( 0, 100 ) % hitzones.Count();
        return hitzones[idx];
    }
References Math::RandomInt(), and Math::Randomize().
Referenced by EvaluateDamage().
GetRaycastedHitZone()
protected string AreaDamageBase::GetRaycastedHitZone (Object victim, array< string > raycast_sources_str) inline private
Definition at line 162 of file areadamage.c.
    {
        // Vertical raycast start positions:    Center,      North East,    North West,    South East,  South West
        //vector raycast_sources[5] = {"0.0 0.1 0.0", "0.2 0.1 0.2", "-.2 0.1 0.2", "0.2 0.1 -.2", "-.2 0.1 -.2"};
        string hitzone;
        vector contact_pos;
        vector contact_dir;
        int contactComponent;
        bool isSteppedOn = false;
        array<vector> raycast_sources = new array<vector>;
        ref set<Object> victims = new set<Object>;
        // convert Array of string to array of Vectors
        for ( int v = 0; v < raycast_sources_str.Count(); ++v)
        {
            raycast_sources.Insert(raycast_sources_str[v].ToVector());
        }
        for ( int i = 0; i < raycast_sources.Count(); ++i )
        {
            vector raycast_start_pos = m_AreaDamageTrigger.ModelToWorld( raycast_sources.Get(i) );
            vector raycast_end_pos = "0 0.5 0" + raycast_start_pos;
            //#ifdef DEVELOPER
            //Debug.DrawArrow( raycast_start_pos, raycast_end_pos );
            //#endif
            DayZPhysics.RaycastRV( raycast_start_pos, raycast_end_pos, contact_pos, contact_dir, contactComponent, victims , null, m_AreaDamageTrigger, true, false, ObjIntersectIFire);
            for ( int j = 0; j < victims.Count(); ++j )
            {
                Object contact_obj = victims.Get(j);
                if ( contact_obj.IsAnyInherited(m_DamageableTypes) )
                {
                    isSteppedOn = true;
                    break;
                }
            }
            if ( isSteppedOn )
            {
                EntityAI eai = EntityAI.Cast(victim);
                if ( eai )
                {
                    hitzone = eai.GetDamageZoneNameByComponentIndex(contactComponent);
                    break;
                }
            }
        }
        if ( isSteppedOn )
        {
            return hitzone;
        }
        else
        {
            // Damage random leg since we don't know what part of player's body was caught in the trap.
            string dmg_zone_rnd = "LeftFoot";
            if ( Math.RandomIntInclusive(0, 1) == 1 )
                dmg_zone_rnd = "RightFoot";
            return dmg_zone_rnd;
        }
    }
References m_AreaDamageTrigger, Math::RandomIntInclusive(), and DayZPhysics::RaycastRV().
Referenced by EvaluateDamage().
OnEnter()
void AreaDamageBase::OnEnter (Object object) inline private
events
Definition at line 48 of file areadamage.c.
    {
        if ( GetGame().IsServer() )
        {
            OnEnterServer(object);
        }
        else
        {
            OnEnterClient(object);
        }
    }
References GetGame(), OnEnterClient(), and OnEnterServer().
OnEnterClient()
void AreaDamageBase::OnEnterClient (Object object) inline private
Definition at line 59 of file areadamage.c.
{}
Referenced by OnEnter().
OnEnterServer() [1/8]
void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 60 of file areadamage.c.
{}
Referenced by OnEnter().
OnEnterServer() [2/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 16 of file areadamageonetime.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage(object);
    }
References EvaluateDamage().
OnEnterServer() [3/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file areadamageonetimedeferred.c.
    {
        super.OnEnterServer(object);;
        EvaluateDamage_Defer(object);
    }
References EvaluateDamage_Defer().
OnEnterServer() [4/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 16 of file areadamageonetimeraycasted.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage(object);
    }
References EvaluateDamage().
OnEnterServer() [5/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file areadamageonetimeraycasteddeferred.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage_Defer(object);
    }
References EvaluateDamage_Defer().
OnEnterServer() [6/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file areadamageregular.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage_Loop(object);
    }
OnEnterServer() [7/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 21 of file areadamageregularraycasted.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage_Loop(object);
    }
References EvaluateDamage_Loop().
OnEnterServer() [8/8]
override void AreaDamageBase::OnEnterServer (Object object) inline private
Definition at line 26 of file areadamageregularraycasteddeferred.c.
    {
        super.OnEnterServer(object);
        EvaluateDamage_DeferLoop(object);
    }
References EvaluateDamage_DeferLoop().
OnLeave()
void AreaDamageBase::OnLeave (Object object) inline private
Definition at line 62 of file areadamage.c.
    {
        if ( GetGame().IsServer() )
        {
            OnLeaveServer(object);
        }
        else
        {
            OnLeaveClient(object);
        }
    }
References GetGame(), OnLeaveClient(), and OnLeaveServer().
OnLeaveClient()
void AreaDamageBase::OnLeaveClient (Object object) inline private
Definition at line 74 of file areadamage.c.
{}
Referenced by OnLeave().
OnLeaveServer()
void AreaDamageBase::OnLeaveServer (Object object) inline private
stop all running timers
Definition at line 75 of file areadamage.c.
    {
        if ( m_DeferTimer && m_DeferTimer.IsRunning() )
        {
            m_DeferTimer.Stop();
        }
        if ( m_LoopTimer && m_LoopTimer.IsRunning() )
        {
            m_LoopTimer.Stop();
        }
    }
References m_DeferTimer, and m_LoopTimer.
Referenced by OnLeave().
SetDeferDuration() [1/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 11 of file areadamageonetimedeferred.c.
    {
        m_DeferDuration = time;
    }
References m_DeferDuration.
SetDeferDuration() [2/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 11 of file areadamageonetimeraycasteddeferred.c.
    {
        m_DeferDuration = time;
    }
References m_DeferDuration.
SetDeferDuration() [3/3]
override void AreaDamageBase::SetDeferDuration (float time) inline private
Definition at line 16 of file areadamageregularraycasteddeferred.c.
    {
        m_DeferDuration = time;
    }
References m_DeferDuration.
SetHitZones() [1/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 11 of file areadamageonetime.c.
    {
        m_HitZones = hitzones;
    }
SetHitZones() [2/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 16 of file areadamageonetimedeferred.c.
    {
        m_HitZones = hitzones;
    }
SetHitZones() [3/3]
override void AreaDamageBase::SetHitZones (array< string > hitzones) inline private
Definition at line 16 of file areadamageregular.c.
    {
        m_HitZones = hitzones;
    }
SetLoopInterval() [1/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file areadamageregular.c.
    {
        m_LoopInterval = time;
    }
SetLoopInterval() [2/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file areadamageregularraycasted.c.
    {
        m_LoopInterval = time;
    }
SetLoopInterval() [3/3]
override void AreaDamageBase::SetLoopInterval (float time) inline private
Definition at line 11 of file areadamageregularraycasteddeferred.c.
    {
        m_LoopInterval = time;
    }
SetRaycastSources() [1/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 11 of file areadamageonetimeraycasted.c.
    {
        m_RaycastSources = raycast_sources;
    }
SetRaycastSources() [2/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 16 of file areadamageonetimeraycasteddeferred.c.
    {
        m_RaycastSources = raycast_sources;
    }
SetRaycastSources() [3/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 16 of file areadamageregularraycasted.c.
    {
        m_RaycastSources = raycast_sources;
    }
SetRaycastSources() [4/4]
override void AreaDamageBase::SetRaycastSources (array< string > raycast_sources) inline private
Definition at line 21 of file areadamageregularraycasteddeferred.c.
    {
        m_RaycastSources = raycast_sources;
    }
Member Data Documentation
m_AmmoName
protected string AreaDamageBase::m_AmmoName private
Definition at line 10 of file areadamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_AreaDamage
protected AreaDamageBase AreaDamageBase::m_AreaDamage private
Definition at line 5 of file areadamage.c.
Referenced by AreaDamageBase().
m_DamageType
protected int AreaDamageBase::m_DamageType private
Definition at line 11 of file areadamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Common().
m_DeferDuration
protected float AreaDamageBase::m_DeferDuration private
Definition at line 14 of file areadamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), and EvaluateDamage_DeferLoop().
m_DeferTimer
protected ref Timer AreaDamageBase::m_DeferTimer private
Definition at line 21 of file areadamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Defer(), EvaluateDamage_DeferLoop(), and OnLeaveServer().
m_HitZones
protected ref array<string> AreaDamageBase::m_HitZones private
Definition at line 16 of file areadamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage().
m_LoopInterval
protected float AreaDamageBase::m_LoopInterval private
Definition at line 13 of file areadamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage_Loop().
m_LoopTimer
protected ref array<typename> m_DamageableTypes protected ref Timer AreaDamageBase::m_LoopTimer private
Definition at line 20 of file areadamage.c.
Referenced by AreaDamageBase(), EvaluateDamage_Loop(), and OnLeaveServer().
m_OthersDamage
protected float AreaDamageBase::m_OthersDamage private
Definition at line 8 of file areadamage.c.
Referenced by AreaDamageBase().
m_PlayerDamage
protected float AreaDamageBase::m_PlayerDamage private
Definition at line 7 of file areadamage.c.
Referenced by AreaDamageBase().
m_RaycastSources
protected ref array<string> AreaDamageBase::m_RaycastSources private
Definition at line 17 of file areadamage.c.
Referenced by AreaDamageBase(), and EvaluateDamage().