DayzKode: NoiseAIEvaluate Class Reference
NoiseAIEvaluate Class Reference
Static Private Member Functions
static float GetNoiseMultiplier (DayZPlayerImplement playerImplement)
static float GetNoiseMultiplierByPlayerSpeed (DayZPlayerImplement playerImplement)
static float GetNoiseMultiplierByShoes (DayZPlayerImplement playerImplement)
static float GetNoiseMultiplierBySurface (DayZPlayerImplement playerImplement)
Static Private Attributes
static float SURFACE_NOISE_WEIGHT = 0.25
Detailed Description
Definition at line 1 of file sensesaievaluate.c.
Member Function Documentation
GetNoiseMultiplier()
static float NoiseAIEvaluate::GetNoiseMultiplier (DayZPlayerImplement playerImplement) inline static private
Definition at line 5 of file sensesaievaluate.c.
    {
        float speedNoise    = GetNoiseMultiplierByPlayerSpeed(playerImplement);
        float shoesNoise    = GetNoiseMultiplierByShoes(playerImplement);
        float surfaceNoise  = GetNoiseMultiplierBySurface(playerImplement);
        surfaceNoise        *= SURFACE_NOISE_WEIGHT;
        float avgNoise      = (shoesNoise + surfaceNoise)/(1 + SURFACE_NOISE_WEIGHT);
        avgNoise            *= speedNoise;
        return avgNoise;
    }
References GetNoiseMultiplierByPlayerSpeed(), GetNoiseMultiplierByShoes(), GetNoiseMultiplierBySurface(), and SURFACE_NOISE_WEIGHT.
Referenced by OnStepEvent(), and ProcessNoiseComponents().
GetNoiseMultiplierByPlayerSpeed()
static float NoiseAIEvaluate::GetNoiseMultiplierByPlayerSpeed (DayZPlayerImplement playerImplement) inline static private
Definition at line 19 of file sensesaievaluate.c.
    {
        HumanMovementState hms = new HumanMovementState();
        playerImplement.GetMovementState(hms);
        if ( playerImplement.GetCommand_Move() && playerImplement.GetCommand_Move().IsInRoll() )
        {
            // When rolling we are prone, so we load that Noise value, hence we multiply
            return PlayerConstants.AI_NOISE_ROLL;
        }
        switch ( AITargetCallbacksPlayer.StanceToMovementIdxTranslation(hms) )
        {
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
                return PlayerConstants.AI_NOISE_IDLE;
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
                return PlayerConstants.AI_NOISE_WALK;
            case DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN:
                return PlayerConstants.AI_NOISE_CROUCH_RUN;
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
                return PlayerConstants.AI_NOISE_RUN;
            case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
                return PlayerConstants.AI_NOISE_SPRINT;
        }
        //Default return
        return PlayerConstants.AI_NOISE_SPRINT;
    }
References PlayerConstants::AI_NOISE_CROUCH_RUN, PlayerConstants::AI_NOISE_IDLE, PlayerConstants::AI_NOISE_ROLL, PlayerConstants::AI_NOISE_RUN, PlayerConstants::AI_NOISE_SPRINT, PlayerConstants::AI_NOISE_WALK, and AITargetCallbacksPlayer::StanceToMovementIdxTranslation().
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
GetNoiseMultiplierByShoes()
static float NoiseAIEvaluate::GetNoiseMultiplierByShoes (DayZPlayerImplement playerImplement) inline static private
Definition at line 55 of file sensesaievaluate.c.
    {
        switch ( playerImplement.GetBootsType() )
        {
            case AnimBootsType.None:
                return PlayerConstants.AI_NOISE_SHOES_NONE;
            case AnimBootsType.Sneakers:
                return PlayerConstants.AI_NOISE_SHOES_SNEAKERS;
            case AnimBootsType.Boots:
                return PlayerConstants.AI_NOISE_SHOES_BOOTS;
        }
        //Default return
        return PlayerConstants.AI_NOISE_SHOES_BOOTS;
    }
References PlayerConstants::AI_NOISE_SHOES_BOOTS, PlayerConstants::AI_NOISE_SHOES_NONE, and PlayerConstants::AI_NOISE_SHOES_SNEAKERS.
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
GetNoiseMultiplierBySurface()
static float NoiseAIEvaluate::GetNoiseMultiplierBySurface (DayZPlayerImplement playerImplement) inline static private
Definition at line 74 of file sensesaievaluate.c.
    {
        return playerImplement.GetSurfaceNoise();
    }
Referenced by GetNoiseMultiplier(), and ShowCoefsDbg().
Member Data Documentation
SURFACE_NOISE_WEIGHT
float NoiseAIEvaluate::SURFACE_NOISE_WEIGHT = 0.25 static private
Definition at line 3 of file sensesaievaluate.c.
Referenced by GetNoiseMultiplier().