DayzKode: PlayerStats Class Reference
PlayerStats Class Reference
Private Member Functions
void GatherAllRecords ()
bool GetAllowLogs ()
void GetDebugInfo (array< ref StatDebugObject > objects, int flags)
PlayerStatsPCO_Base GetPCO (int version=-1)
PlayerStatBase GetStatObject (int id)
void Init (Man player)
bool LoadStats (ParamsReadContext ctx, int version)
void PlayerStats (Man player)
void ResetAllStats ()
void SaveStats (ParamsWriteContext ctx)
void SetAllowLogs (bool enable)
void ~PlayerStats ()
Private Attributes
bool m_AllowLogs
ref PCOHandlerStats m_PCOhandler = new PCOHandlerStats()
Man m_Player
ref array< ref PlayerStatBase > m_PlayerStats
ref array< ref StatDebugObject > m_PlayerStatsDebug
ref Timer m_SyncTimer
string m_System = "Stats"
Detailed Description
Definition at line 6 of file playerstats.c.
Constructor & Destructor Documentation
PlayerStats()
void PlayerStats::PlayerStats (Man player) inline private
Definition at line 21 of file playerstats.c.
    {
        Init(player);
    }
References Init().
~PlayerStats()
void PlayerStats::~PlayerStats () inline private
Definition at line 36 of file playerstats.c.
    {
        //if( GetGame() && GetGame().IsDebugActions() ) GatherAllRecords();
    }
Member Function Documentation
GatherAllRecords()
void PlayerStats::GatherAllRecords () inline private
Definition at line 81 of file playerstats.c.
    {
        /*
        FileHandle file = OpenFile("$profile:StatRecords.log", FileMode.WRITE);
        FPrintln(file, "================================================================");
        FPrintln(file," ================== " + m_Player.ToString() +" ================== ");
        FPrintln(file, "================================================================");
        for(int i = 0; i < m_PlayerStats.Count(); i++)
        {
            array<PlayerStatRecord> records =  m_PlayerStats.Get(i).GetRecords();
            FPrintln(file, m_PlayerStats.Get(i).GetLabel() );
            for(int z = 0; z < records.Count(); z++)
            {
                PlayerStatRecord record = records.Get(z);
                string output = record.GetStringOutput();
                FPrintln(file, output);
            }
        }
        */
    }
GetAllowLogs()
bool PlayerStats::GetAllowLogs () inline private
Definition at line 66 of file playerstats.c.
    {
        return  m_AllowLogs;
    }
References m_AllowLogs.
GetDebugInfo()
void PlayerStats::GetDebugInfo (array< ref StatDebugObject > objects, int flags) inline private
Definition at line 71 of file playerstats.c.
    {
        /*
        for(int i = 0; i < m_PlayerStats.Count(); i++)
        {
            m_PlayerStats.Get(i).SerializeValue(objects, flags);
        }
        */
    }
GetPCO()
PlayerStatsPCO_Base PlayerStats::GetPCO (int version = -1) inline private
Definition at line 31 of file playerstats.c.
    {
        return m_PCOhandler.GetPCO(version);
    }
References PCOHandlerStats::GetPCO(), and m_PCOhandler.
Referenced by GetStatObject(), LoadStats(), ResetAllStats(), and SaveStats().
GetStatObject()
PlayerStatBase PlayerStats::GetStatObject (int id) inline private
Definition at line 42 of file playerstats.c.
    {
        PlayerStatsPCO_Base pco = GetPCO();
        if ( pco )
        {
            return pco.GetStatObject(id);
        }
        else
        {
            return null;
        }
    }
References GetPCO().
Init()
void PlayerStats::Init (Man player) inline private
Definition at line 26 of file playerstats.c.
    {
        m_Player        = player;
    }
References m_Player.
LoadStats()
bool PlayerStats::LoadStats (ParamsReadContext ctx, int version) inline private
Definition at line 122 of file playerstats.c.
    {
        PlayerStatsPCO_Base pco = GetPCO(version);
        if (pco && pco.OnStoreLoad(ctx))
        {
            //Print("********* LoadStats loading version: " + pco.GetVersion());
            return true;
        }
        else
        {
            return false;
        }
    }
References GetPCO().
ResetAllStats()
void PlayerStats::ResetAllStats () inline private
Definition at line 137 of file playerstats.c.
    {
        GetPCO().ResetAllStats();
    }
References GetPCO().
SaveStats()
void PlayerStats::SaveStats (ParamsWriteContext ctx) inline private
Definition at line 106 of file playerstats.c.
    {
        int current_version = GetGame().SaveVersion();
        PlayerStatsPCO_Base pco = GetPCO(current_version);
        if ( pco )
        {
            pco.OnStoreSave(ctx);
            //Print("Saving stats in version: "+ pco.GetVersion());
        }
        else
        {
            return;
        }
    }
References GetGame(), GetPCO(), and CGame::SaveVersion().
SetAllowLogs()
void PlayerStats::SetAllowLogs (bool enable) inline private
Definition at line 61 of file playerstats.c.
    {
        m_AllowLogs = enable;
    }
References m_AllowLogs.
Member Data Documentation
m_AllowLogs
bool PlayerStats::m_AllowLogs private
Definition at line 16 of file playerstats.c.
Referenced by GetAllowLogs(), and SetAllowLogs().
m_PCOhandler
ref PCOHandlerStats PlayerStats::m_PCOhandler = new PCOHandlerStats() private
Definition at line 12 of file playerstats.c.
Referenced by GetPCO().
m_Player
Man PlayerStats::m_Player private
Definition at line 15 of file playerstats.c.
Referenced by Init().
m_PlayerStats
ref array<ref PlayerStatBase> PlayerStats::m_PlayerStats private
Definition at line 8 of file playerstats.c.
m_PlayerStatsDebug
ref array<ref StatDebugObject> PlayerStats::m_PlayerStatsDebug private
Definition at line 9 of file playerstats.c.
m_SyncTimer
ref Timer PlayerStats::m_SyncTimer private
Definition at line 14 of file playerstats.c.
m_System
string PlayerStats::m_System = "Stats" private
Definition at line 17 of file playerstats.c.