DayzKode: WorldLighting Class Reference
WorldLighting Class Reference
Private Member Functions
void SetGlobalLighting (int lightingID)
void WorldLighting ()
void ~WorldLighting ()
Private Attributes
string lighting_darknight = "dz\\data\\lighting\\lighting_darknight.txt"
string lighting_default = "dz\\data\\lighting\\lighting_default.txt"
Detailed Description
Definition at line 1 of file worldlighting.c.
Constructor & Destructor Documentation
WorldLighting()
void WorldLighting::WorldLighting () inline private
Definition at line 6 of file worldlighting.c.
{}
~WorldLighting()
void WorldLighting::~WorldLighting () inline private
Definition at line 7 of file worldlighting.c.
{}
Member Function Documentation
SetGlobalLighting()
void WorldLighting::SetGlobalLighting (int lightingID) inline private
Definition at line 10 of file worldlighting.c.
    {
        switch ( lightingID )
        {
            case 0:
                GetGame().GetWorld().LoadNewLightingCfg( lighting_default );
                break;
            case 1:
                GetGame().GetWorld().LoadNewLightingCfg( lighting_darknight );
                break;
        }
    }
References GetGame(), CGame::GetWorld(), lighting_darknight, lighting_default, and World::LoadNewLightingCfg().
Referenced by ManBase::UpdateLighting().
Member Data Documentation
lighting_darknight
string WorldLighting::lighting_darknight = "dz\\data\\lighting\\lighting_darknight.txt" private
Definition at line 4 of file worldlighting.c.
Referenced by SetGlobalLighting().
lighting_default
string WorldLighting::lighting_default = "dz\\data\\lighting\\lighting_default.txt" private
Definition at line 3 of file worldlighting.c.
Referenced by SetGlobalLighting().