DayzKode: ActionDestroyCombinationLock Class Reference
ActionDestroyCombinationLock Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDestroyCombinationLock ()
override void CreateConditionComponents ()
override string GetAdminLogMessage (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Static Private Attributes
static int CYCLES = 5
Detailed Description
Definition at line 9 of file actiondestroycombinationlock.c.
Constructor & Destructor Documentation
ActionDestroyCombinationLock()
void ActionDestroyCombinationLock::ActionDestroyCombinationLock () inline private
Definition at line 12 of file actiondestroycombinationlock.c.
    {
        m_CallbackClass = ActionDestroyCombinationLockCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_MEDIUM;
        m_Text = "#destroy_combination_lock";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionDestroyCombinationLock::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 28 of file actiondestroycombinationlock.c.
    {
        Object target_object = target.GetObject();
        string selection = target_object.GetActionComponentName( target.GetComponentIndex() );
        Fence fence = Fence.Cast( target_object );
        if ( fence && fence.IsLocked() && selection == "wall_interact" )
        {
            return true;
        }
        return false;
    }
CreateConditionComponents()
override void ActionDestroyCombinationLock::CreateConditionComponents () inline private
Definition at line 22 of file actiondestroycombinationlock.c.
    {
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINonRuined;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionDestroyCombinationLock::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 66 of file actiondestroycombinationlock.c.
    {
        return " destroyed combination lock with " + action_data.m_MainItem.GetDisplayName();
    }
References ActionData::m_MainItem.
OnFinishProgressServer()
override void ActionDestroyCombinationLock::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 42 of file actiondestroycombinationlock.c.
    {
        Fence fence = Fence.Cast( action_data.m_Target.GetObject() );
        if ( fence )
        {
            CombinationLock combination_lock = fence.GetCombinationLock();
            if ( combination_lock )
            {
                combination_lock.AddHealth("","",-(combination_lock.GetMaxHealth("","")/CYCLES));
                if ( combination_lock.IsDamageDestroyed() )
                {
                    combination_lock.UnlockServer( action_data.m_Player, fence );
                    GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( combination_lock.DestroyLock, 200, false );
                }
            }
        }
        action_data.m_MainItem.DecreaseHealth( UADamageApplied.SAW_LOCK, false );
        //soft skills
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CYCLES, CGame::GetCallQueue(), GetGame(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, and UADamageApplied::SAW_LOCK.
Member Data Documentation
CYCLES
int ActionDestroyCombinationLock::CYCLES = 5 static private
Definition at line 11 of file actiondestroycombinationlock.c.
Referenced by OnFinishProgressServer().