DayzKode: DeveloperFreeCamera Class Reference
DeveloperFreeCamera Class Reference
Static Private Member Functions
static void DisableFreeCamera (PlayerBase player, bool teleport_player=false)
static protected void EnableFreeCamera (PlayerBase player)
static void EnableFreeCameraSceneEditor (PlayerBase player)
static void FreeCameraToggle (PlayerBase player, bool teleport_player=false)
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
static bool IsFreeCameraEnabled ()
Is free camera enabled.
static void OnInit ()
static void OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera)
Detailed Description
Definition at line 1 of file developerfreecamera.c.
Member Function Documentation
DisableFreeCamera()
static void DeveloperFreeCamera::DisableFreeCamera (PlayerBase player, bool teleport_player = false) inline static private
Definition at line 55 of file developerfreecamera.c.
    {
        if ( player )
        {
            if ( FreeDebugCamera.GetInstance().IsActive() )
            {
                if (teleport_player)
                    DeveloperTeleport.TeleportAtCursorEx();
                FreeDebugCamera.GetInstance().SetActive(false);
                #ifdef DEVELOPER
                if ( GetGame().GetMission() )
                {
                    GetGame().GetMission().RefreshCrosshairVisibility();
                }
                #endif
                //GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().GetMission(), "RefreshCrosshairVisibility", NULL);
            }
        }
        else
        {
            Debug.LogError("DisableFreeCamera( PlayerBase player, bool teleport_player ) -> player is NULL", "DeveloperFreeCamera");
        }
    }
References GetGame(), CGame::GetMission(), Debug::LogError(), Mission::RefreshCrosshairVisibility(), and DeveloperTeleport::TeleportAtCursorEx().
Referenced by FreeCameraToggle(), UIScriptedMenu::Play(), and UIScriptedMenu::~CameraToolsMenu().
EnableFreeCamera()
static protected void DeveloperFreeCamera::EnableFreeCamera (PlayerBase player) inline static private
Definition at line 34 of file developerfreecamera.c.
    {
        if ( player )
        {
            FreeDebugCamera.GetInstance().SetActive(true);
            #ifdef DEVELOPER
            GetGame().GetMission().RefreshCrosshairVisibility();
            //GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().GetMission(), "RefreshCrosshairVisibility", NULL);
            #endif
        }
        else
        {
            Print("EnableFreeCamera( PlayerBase player ) -> player is NULL");
            Debug.LogError("EnableFreeCamera( PlayerBase player ) -> player is NULL", "DeveloperFreeCamera");
        }
    }
References GetGame(), CGame::GetMission(), Debug::LogError(), Print(), and Mission::RefreshCrosshairVisibility().
Referenced by EnableFreeCameraSceneEditor(), and FreeCameraToggle().
EnableFreeCameraSceneEditor()
static void DeveloperFreeCamera::EnableFreeCameraSceneEditor (PlayerBase player) inline static private
Definition at line 20 of file developerfreecamera.c.
    {
        EnableFreeCamera(player);
    }
References EnableFreeCamera().
Referenced by UIScriptedMenu::Init(), PluginBase::OnUIEditorOpened(), and UIScriptedMenu::Update().
FreeCameraToggle()
static void DeveloperFreeCamera::FreeCameraToggle (PlayerBase player, bool teleport_player = false) inline static private
Enable / Disable Free camera (Fly mod) - disable of camera will teleport player at current free camera position.
Definition at line 8 of file developerfreecamera.c.
    {
        if ( !IsFreeCameraEnabled() )
        {
            EnableFreeCamera( player );
        }
        else
        {
            DisableFreeCamera( player, teleport_player );
        }
    }
References DisableFreeCamera(), EnableFreeCamera(), and IsFreeCameraEnabled().
Referenced by PluginBase::ToggleFreeCamera(), and PluginBase::ToggleFreeCameraBackPos().
IsFreeCameraEnabled()
static bool DeveloperFreeCamera::IsFreeCameraEnabled () inline static private
Is free camera enabled.
Definition at line 26 of file developerfreecamera.c.
    {
        return FreeDebugCamera.GetInstance().IsActive();
    }
Referenced by FreeCameraToggle(), PluginBase::IsEnabledFreeCamera(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), and ActionManagerClient::Update().
OnInit()
static void DeveloperFreeCamera::OnInit () inline static private
Definition at line 3 of file developerfreecamera.c.
    {
    }
Referenced by PluginBase::OnInit().
OnSetFreeCameraEvent()
static void DeveloperFreeCamera::OnSetFreeCameraEvent (PlayerBase player, FreeDebugCamera camera) inline static private
Definition at line 83 of file developerfreecamera.c.
    {
        if ( player )
        {
            #ifdef DEVELOPER
            if ( !GetGame().IsMultiplayer() )
            {
                PluginSceneManager plugin_scene_manager = PluginSceneManager.Cast( GetPlugin(PluginSceneManager) );
                if ( plugin_scene_manager.IsOpened() )
                {
                    plugin_scene_manager.EditorToggle();
                }
            }
            GetGame().GetMission().RefreshCrosshairVisibility();
            //GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().GetMission(), "RefreshCrosshairVisibility", NULL);
            #endif
        }
    }
References GetGame(), CGame::GetMission(), GetPlugin(), and Mission::RefreshCrosshairVisibility().
Referenced by PluginBase::OnSetFreeCameraEvent().