DayzKode: ActionSawPlanks Class Reference
ActionSawPlanks Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionSawPlanks ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
Private Attributes
ItemBase m_Planks
ref InventoryLocation m_PlanksLocation = new InventoryLocation
Static Private Attributes
static const int DECREASE_HEALTH_OF_TOOL_DEFAULT = 10
static const int YIELD = 3
Detailed Description
Definition at line 35 of file actionsawplanks.c.
Constructor & Destructor Documentation
ActionSawPlanks()
void ActionSawPlanks::ActionSawPlanks () inline private
Definition at line 45 of file actionsawplanks.c.
    {
        m_CallbackClass = ActionSawPlanksCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_MEDIUM;
        m_Text = "#saw_planks";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_MEDIUM.
Member Function Documentation
ActionCondition()
override bool ActionSawPlanks::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 61 of file actionsawplanks.c.
    {
        Object target_O = target.GetObject();
        if ( item  &&  target_O.IsInherited(PileOfWoodenPlanks))
        {
            string item_type = item.GetType();
            switch(item_type)
            {
                case "Chainsaw":
                    if ( item.HasEnergyManager()  &&  item.GetCompEM().CanWork() )
                    {
                        return true;
                    }
                    else
                    {
                        return false;
                    }
                break;
            }
            return true;
        }
        return false;
    }
CreateConditionComponents()
override void ActionSawPlanks::CreateConditionComponents () inline private
Definition at line 55 of file actionsawplanks.c.
    {
        m_ConditionTarget = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem = new CCINonRuined;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void ActionSawPlanks::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 89 of file actionsawplanks.c.
    {
        PileOfWoodenPlanks item_POWP = PileOfWoodenPlanks.Cast( action_data.m_Target.GetObject() );
        item_POWP.RemovePlanks(YIELD);
        vector pos = action_data.m_Player.GetPosition();
        InventoryLocation currentLoc = new InventoryLocation;
        if (m_Planks)
            m_Planks.GetInventory().GetCurrentInventoryLocation(currentLoc);
        if (!m_Planks || !currentLoc.CompareLocationOnly(m_PlanksLocation))
        {
            m_Planks = ItemBase.Cast( GetGame().CreateObjectEx("WoodenPlank", pos, ECE_PLACE_ON_SURFACE) );
            m_Planks.SetQuantity(YIELD);
            m_Planks.GetInventory().GetCurrentInventoryLocation(currentLoc);
            m_PlanksLocation.Copy(currentLoc);
        }
        else if ((m_Planks.GetQuantity() + YIELD) >= m_Planks.GetQuantityMax())
        {
            int remnant = m_Planks.GetQuantity() + YIELD - m_Planks.GetQuantityMax();
            m_Planks.SetQuantity(m_Planks.GetQuantityMax());
            if (remnant > 0)
            {
                m_Planks = ItemBase.Cast( GetGame().CreateObjectEx("WoodenPlank", pos, ECE_PLACE_ON_SURFACE) );
                m_Planks.SetQuantity(remnant);
                m_Planks.GetInventory().GetCurrentInventoryLocation(currentLoc);
                m_PlanksLocation.Copy(currentLoc);
            }
        }
        else
        {
            m_Planks.AddQuantity(YIELD);
        }
        ItemBase item = action_data.m_MainItem;
        string item_type = item.GetType();
        item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( UADamageApplied.SAW_PLANKS, GetSpecialtyWeight() ));
        /*switch(item_type)
        {
            case "WoodAxe":
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( DECREASE_HEALTH_OF_TOOL_AXE, GetSpecialtyWeight() ));
            break;
            case "FirefighterAxe":
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( DECREASE_HEALTH_OF_TOOL_AXE, GetSpecialtyWeight() ));
            break;
            case "FirefighterAxe_Black":
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( DECREASE_HEALTH_OF_TOOL_AXE, GetSpecialtyWeight() ));
            break;
            case "FirefighterAxe_Green":
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( DECREASE_HEALTH_OF_TOOL_AXE, GetSpecialtyWeight() ));
            break;
            case "Hatchet":
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( DECREASE_HEALTH_OF_TOOL_AXE, GetSpecialtyWeight() ));
            break;
            case "Chainsaw":
                if ( item.HasEnergyManager() )
                {
                    item.GetCompEM().ConsumeEnergy(DECREASE_FUEL_OF_CHAINSAW);
                }
            break;
            default: // Hacksaw and other
                item.DecreaseHealth( "", "", action_data.m_Player.GetSoftSkillsManager().AddSpecialtyBonus( UADamageApplied.SAW_PLANKS, GetSpecialtyWeight() ));
            break;
        }*/
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References InventoryLocation::CompareLocationOnly(), InventoryLocation::Copy(), ECE_PLACE_ON_SURFACE, GetGame(), GetSpecialtyWeight(), ActionData::m_MainItem, m_Planks, m_PlanksLocation, ActionData::m_Player, m_SpecialtyWeight, ActionData::m_Target, UADamageApplied::SAW_PLANKS, and YIELD.
Member Data Documentation
DECREASE_HEALTH_OF_TOOL_DEFAULT
const int ActionSawPlanks::DECREASE_HEALTH_OF_TOOL_DEFAULT = 10 static private
Definition at line 37 of file actionsawplanks.c.
m_Planks
ItemBase ActionSawPlanks::m_Planks private
Definition at line 42 of file actionsawplanks.c.
Referenced by OnFinishProgressServer().
m_PlanksLocation
ref InventoryLocation ActionSawPlanks::m_PlanksLocation = new InventoryLocation private
Definition at line 43 of file actionsawplanks.c.
Referenced by OnFinishProgressServer().
YIELD
const int ActionSawPlanks::YIELD = 3 static private
Definition at line 41 of file actionsawplanks.c.
Referenced by OnFinishProgressServer().