DayzKode: CCTBase Class Reference
CCTBase Class Reference
Private Member Functions
bool Can (PlayerBase player, ActionTarget target)
bool CanContinue (PlayerBase player, ActionTarget target)
Detailed Description
Definition at line 1 of file cctbase.c.
Member Function Documentation
Can()
bool CCTBase::Can (PlayerBase player, ActionTarget target) inline private
Definition at line 3 of file cctbase.c.
    {
        return true;
    }
Referenced by Can(), and CanContinue().
CanContinue()
bool CCTBase::CanContinue (PlayerBase player, ActionTarget target) inline private
Definition at line 8 of file cctbase.c.
    {
        return Can(player, target);
    }
References Can().
Referenced by CanContinue().