DayzKode: GameplayEffectWidgets_base Class Reference
GameplayEffectWidgets_base Class Reference
grouped gameplay effect widgets and their handling
Private Member Functions
override void AddActiveEffects (array< int > effects)
override void AddSuspendRequest (int request_id)
protected void CalculateBreathEffect (float timeSlice=0, int type=-1, Param p=null)
protected void CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle)
protected void CalculateOccluderEffect (int type, float timeSlice, Param p, int handle)
protected void CalculateValues (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Only one calculation per unique WidgetSet.
override void ClearSuspendRequests ()
array< int > CompileEffectListing ()
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
bool CreateHandledClass (typename handled_type, array< ref Widget > input, int type, int user_override)
void GameplayEffectWidgets ()
override int GetSuspendRequestCount ()
protected void HandleWidgetRoot (float timeSlice=0, Param p=null, int handle=-1)
protected void InitWidgetSet (int type, bool updating=false, int user_id_override=-1)
InitWidgetSet.
override bool IsAnyEffectRunning ()
override void OnVoiceEvent (float breathing_resistance01)
protected void PairIDToTypes ()
protected void ProcessWidgetUpdate (Widget w, int type, float timeSlice=0, Param p=null, int handle=-1)
override void RegisterGameplayEffectData (int id, Param p)
protected void RegisterLayouts (string path, array< int > types)
Registers new layout and ties effect IDs to it.
override void RemoveActiveEffects (array< int > effects)
override void RemoveSuspendRequest (int request_id)
override void StopAllEffects ()
protected TranslateIDToType (int typeID)
override void Update (float timeSlice)
Generic update, called on frame from the player.
protected void UpdateBreathEffect (ImageWidget w)
protected void UpdateFlashbangEffect (ImageWidget w)
protected void UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle)
protected void UpdateVisibility ()
override void UpdateWidgets (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
void ~GameplayEffectWidgets ()
Private Attributes
const float BREATH_COLOR_MULT_MAX = 0.8
const float BREATH_COLOR_MULT_MIN = 0.5
const float BREATH_HDR_MAX = 1.0
const float BREATH_HDR_MIN = 0.005
protected float m_BreathAlphaVal
protected int m_BreathColor
protected float m_BreathMultStamina
protected float m_BreathResidue
protected float m_FlashbangCoverAlphaVal
protected ref map< int, typename > m_IDToTypeMap
protected ref map< int, ref Widget > m_Layouts
protected ref Widget m_Root
protected ref set< int > m_RunningEffects
protected ref set< int > m_RunningEffectsPrevious
protected ref set< int > m_SuspendRequests
protected float m_TimeProgBreath
protected ref set< ref Widget > m_UniqueLayouts
protected ref array< ref Widget > m_UpdatedWidgetsCheck
protected ref array< int > m_UpdatedWidgetSetsCheck
protected ref array< int > m_UpdatingEffects
protected ref GameplayEffectDataMap m_WidgetDataMap
protected const int WIDGETSET_BREATH = 100
Detailed Description
grouped gameplay effect widgets and their handling
Definition at line 6 of file gameplayeffectwidgets.c.
Constructor & Destructor Documentation
~GameplayEffectWidgets()
void GameplayEffectWidgets_base::~GameplayEffectWidgets () inline private
Definition at line 72 of file gameplayeffectwidgets.c.
    {
        for (int i = 0; i < m_Layouts.Count(); i++)
        {
            if (m_Layouts.GetElement(i))
                m_Layouts.GetElement(i).Unlink();
        }
    }
Member Function Documentation
AddActiveEffects()
override void GameplayEffectWidgets_base::AddActiveEffects (array< int > effects) inline private
Definition at line 277 of file gameplayeffectwidgets.c.
    {
        if (effects && effects.Count() > 0)
        {
            m_RunningEffectsPrevious.Copy(m_RunningEffects);
            int value;
            for (int i = 0; i < effects.Count(); i++)
            {
                value = effects.Get(i);
                m_RunningEffects.Insert(value);
            }
            if (m_RunningEffectsPrevious.Count() != m_RunningEffects.Count())
            {
                UpdateVisibility();
            }
        }
    }
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick(), PPERequester_GameplayBase::OnStart(), SetNVPostprocess(), and StartSourceBleedingIndication().
AddSuspendRequest()
override void GameplayEffectWidgets_base::AddSuspendRequest (int request_id) inline private
Definition at line 336 of file gameplayeffectwidgets.c.
    {
        m_SuspendRequests.Insert(request_id);
        UpdateVisibility();
    }
References UpdateVisibility().
Referenced by PPERequester_GameplayBase::OnStart(), and ManBase::OnUnconsciousStart().
CalculateBreathEffect()
protected void GameplayEffectWidgets_base::CalculateBreathEffect (float timeSlice = 0, int type = -1, Param p = null) inline private
Definition at line 525 of file gameplayeffectwidgets.c.
    {
        float modifier = Math.Lerp(0.25, 0.5, m_BreathResidue);
        float speed = timeSlice * modifier;
        m_BreathResidue -= speed;
        m_BreathResidue = Math.Clamp(m_BreathResidue,0,1);
        float residue_final = Math.Lerp(0, 0.7, m_BreathResidue);
        float hdr_mult;
        hdr_mult = GetSceneHDRMul(0);
        hdr_mult = Math.Clamp(hdr_mult,BREATH_HDR_MIN,BREATH_HDR_MAX);
        hdr_mult = Math.InverseLerp(BREATH_HDR_MIN,BREATH_HDR_MAX,hdr_mult);
        hdr_mult = Math.Lerp(BREATH_COLOR_MULT_MAX,BREATH_COLOR_MULT_MIN,hdr_mult);
        m_BreathColor = ARGBF(0.0,1.0 * hdr_mult,1.0 * hdr_mult,1.0 * hdr_mult); //grayscaling of the image
        m_BreathAlphaVal = Math.Lerp(m_BreathAlphaVal, residue_final, timeSlice);
    }
References ARGBF(), Math::Clamp(), GetSceneHDRMul(), Math::InverseLerp(), and Math::Lerp().
Referenced by CalculateValues().
CalculateFlashbangEffect()
protected void GameplayEffectWidgets_base::CalculateFlashbangEffect (int type, float timeSlice, Param p, int handle) inline private
Definition at line 564 of file gameplayeffectwidgets.c.
    {
        Param1<float> par = Param1<float>.Cast(p);
        m_FlashbangCoverAlphaVal = par.param1;
        /*if (m_FlashbangCoverAlphaVal <= 0.0)
        {
            RemoveActiveEffects({EffectWidgetsTypes.COVER_FLASHBANG});
            return;
        }*/
    }
Referenced by CalculateValues().
CalculateOccluderEffect()
protected void GameplayEffectWidgets_base::CalculateOccluderEffect (int type, float timeSlice, Param p, int handle) inline private
Definition at line 553 of file gameplayeffectwidgets.c.
    {
    }
Referenced by CalculateValues().
CalculateValues()
protected void GameplayEffectWidgets_base::CalculateValues (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
Only one calculation per unique WidgetSet.
Definition at line 440 of file gameplayeffectwidgets.c.
    {
        if (m_UpdatedWidgetSetsCheck.Find(m_WidgetDataMap.Get(type).GetWidgetSetID()) != -1)
        {
            //Print("skipped updating set ID " + m_WidgetDataMap.Get(type).GetWidgetSetID() + " | effect: " + type);
            return;
        }
        switch (type)
        {
            case EffectWidgetsTypes.MOTO_BREATH:
            case EffectWidgetsTypes.HELMET_BREATH:
            case EffectWidgetsTypes.MASK_BREATH:
            {
                CalculateBreathEffect(timeSlice);
            }
            break;
            case EffectWidgetsTypes.MOTO_OCCLUDER:
            case EffectWidgetsTypes.EYEPATCH_OCCLUDER:
            case EffectWidgetsTypes.HELMET_OCCLUDER:
            case EffectWidgetsTypes.MASK_OCCLUDER:
            {
                CalculateOccluderEffect(type,timeSlice,p,handle);
            }
            break;
            case EffectWidgetsTypes.COVER_FLASHBANG:
            {
                CalculateFlashbangEffect(type,timeSlice,p,handle);
            }
            break;
            default:
                return; //no need to calculate anything
            break;
        }
        m_UpdatedWidgetSetsCheck.Insert(m_WidgetDataMap.Get(type).GetWidgetSetID());
    }
References CalculateBreathEffect(), CalculateFlashbangEffect(), and CalculateOccluderEffect().
Referenced by UpdateWidgets().
ClearSuspendRequests()
override void GameplayEffectWidgets_base::ClearSuspendRequests () inline private
Definition at line 352 of file gameplayeffectwidgets.c.
    {
        m_SuspendRequests.Clear();
        UpdateVisibility();
    }
References UpdateVisibility().
Referenced by ManBase::SimulateDeath().
CompileEffectListing()
array< int > GameplayEffectWidgets_base::CompileEffectListing () inline private
returns all vanilla effects, nested in a vanilla layout. If using different layouts for custom effects, please register and link separately
Definition at line 194 of file gameplayeffectwidgets.c.
    {
        array<int> ret = new array<int>;
        ret.Insert(EffectWidgetsTypes.MASK_OCCLUDER);
        ret.Insert(EffectWidgetsTypes.MASK_BREATH);
        ret.Insert(EffectWidgetsTypes.HELMET_OCCLUDER);
        ret.Insert(EffectWidgetsTypes.HELMET_BREATH);
        ret.Insert(EffectWidgetsTypes.MOTO_OCCLUDER);
        ret.Insert(EffectWidgetsTypes.MOTO_BREATH);
        ret.Insert(EffectWidgetsTypes.COVER_FLASHBANG);
        ret.Insert(EffectWidgetsTypes.NVG_OCCLUDER);
        ret.Insert(EffectWidgetsTypes.PUMPKIN_OCCLUDER);
        ret.Insert(EffectWidgetsTypes.EYEPATCH_OCCLUDER);
        return ret;
    }
Referenced by GameplayEffectWidgets().
CreateHandledClass()
bool GameplayEffectWidgets_base::CreateHandledClass (typename handled_type , array< ref Widget > input, int type, int user_override) inline private
Definition at line 181 of file gameplayeffectwidgets.c.
    {
        if (handled_type)
        {
            GameplayEffectsData data = GameplayEffectsData.Cast(handled_type.Spawn());
            data.Init(input,type,m_Layouts.Get(type),user_override);
            m_WidgetDataMap.Set(type, data);
            return true;
        }
        return false;
    }
References GameplayEffectsData::Init().
Referenced by InitWidgetSet().
GameplayEffectWidgets()
void GameplayEffectWidgets_base::GameplayEffectWidgets () inline private
Definition at line 32 of file gameplayeffectwidgets.c.
    {
        m_Root = GetGame().GetWorkspace().CreateWidget(FrameWidgetTypeID,0,0,1.0,1.0,WidgetFlags.VISIBLE | WidgetFlags.HEXACTPOS | WidgetFlags.VEXACTPOS, 0xffffffff, 0);
        m_Layouts = new map<int,ref Widget>;
        m_UniqueLayouts = new set<ref Widget>;
        m_WidgetDataMap = new GameplayEffectDataMap;
        m_RunningEffects = new set<int>;
        m_RunningEffectsPrevious = new set<int>;
        m_UpdatingEffects = new array<int>;
        m_UpdatedWidgetsCheck = new array<ref Widget>;
        m_UpdatedWidgetSetsCheck = new array<int>;
        m_SuspendRequests = new set<int>;
        m_IDToTypeMap = new map<int,typename>;
        m_TimeProgBreath = 0.0;
        m_BreathMultStamina = 1.0;
        PairIDToTypes();
        RegisterLayouts("gui/layouts/gameplay/CameraEffects.layout",CompileEffectListing());
        RegisterLayouts("gui/layouts/gameplay/BleedingEffects.layout",{EffectWidgetsTypes.BLEEDING_LAYER});
        InitWidgetSet(EffectWidgetsTypes.MASK_BREATH,true,WIDGETSET_BREATH);
        InitWidgetSet(EffectWidgetsTypes.HELMET_BREATH,true,WIDGETSET_BREATH);
        InitWidgetSet(EffectWidgetsTypes.MOTO_BREATH,true,WIDGETSET_BREATH);
        InitWidgetSet(EffectWidgetsTypes.MASK_OCCLUDER,false,EffectWidgetsTypes.MASK_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.HELMET_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.MOTO_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.NVG_OCCLUDER,false,EffectWidgetsTypes.NVG_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.PUMPKIN_OCCLUDER,false,EffectWidgetsTypes.NVG_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.EYEPATCH_OCCLUDER);
        InitWidgetSet(EffectWidgetsTypes.COVER_FLASHBANG);
        InitWidgetSet(EffectWidgetsTypes.BLEEDING_LAYER,true);
        UpdateVisibility();
    }
References CompileEffectListing(), WorkspaceWidget::CreateWidget(), GetGame(), CGame::GetWorkspace(), InitWidgetSet(), m_Root, PairIDToTypes(), RegisterLayouts(), and UpdateVisibility().
GetSuspendRequestCount()
override int GameplayEffectWidgets_base::GetSuspendRequestCount () inline private
Definition at line 358 of file gameplayeffectwidgets.c.
    {
        return m_SuspendRequests.Count();
    }
HandleWidgetRoot()
protected void GameplayEffectWidgets_base::HandleWidgetRoot (float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 584 of file gameplayeffectwidgets.c.
    {
        switch (handle)
        {
            default:
            {
                Param1<float> par = Param1<float>.Cast(p);
                if (par)
                {
                    float alpha_mod = Math.Clamp(par.param1,0.0,1.0);
                    //Print(alpha_mod);
                    m_Root.SetAlpha(alpha_mod);
                }
            }
            break;
        }
    }
References Math::Clamp(), and m_Root.
Referenced by UpdateWidgets().
InitWidgetSet()
protected void GameplayEffectWidgets_base::InitWidgetSet (int type, bool updating = false, int user_id_override = -1) inline private
InitWidgetSet.
Parameters
type int ID of effect widget type
updating bool Marks widgets for 'PlayerBase.EOnFrame' updating
user_id_override int UserID of a widget to be used instead (allows multiple types to use single widget)
InitWidgetSet(EffectWidgetsTypes.MASK_BREATH,true,BREATH);
Note
All child widgets MUST be of the same type if special functionality is required (ImageWidget etc.)
Definition at line 124 of file gameplayeffectwidgets.c.
    {
        Widget parent = null;
        if (user_id_override != -1)
        {
            parent = m_Layouts.Get(type).FindAnyWidgetById(user_id_override);
        }
        else
        {
            parent = m_Layouts.Get(type).FindAnyWidgetById(type);
        }
        if (!parent)
        {
            Print("InitWidgetSet | type: " + type + " - parent not found!");
            return;
        }
        array<ref Widget> output;
        Widget w = parent.GetChildren();
        if (w)
        {
            output = new array<ref Widget>;
            while (w)
            {
                w.Update();
                w.Show(false,true);
                output.Insert(w);
                w = w.GetSibling();
            }
            if (parent.GetChildren())
            {
                typename handled_type = TranslateIDToType(type);
                if ( handled_type )
                {
                    CreateHandledClass(handled_type,output,type,user_id_override);
                }
                else
                {
                    if (ImageWidget.Cast(parent.GetChildren()))
                    {
                        m_WidgetDataMap.Set(type, new GameplayEffectsDataImage(output,type,user_id_override) );
                    }
                    else
                    {
                        m_WidgetDataMap.Set(type, new GameplayEffectsData(output,type,user_id_override) );
                    }
                }
            }
            if (updating)
                m_UpdatingEffects.Insert(type);
        }
    }
References CreateHandledClass(), GameplayEffectsDataImage(), Print(), and TranslateIDToType().
Referenced by GameplayEffectWidgets().
IsAnyEffectRunning()
override bool GameplayEffectWidgets_base::IsAnyEffectRunning () inline private
Definition at line 331 of file gameplayeffectwidgets.c.
    {
        return m_RunningEffects && m_RunningEffects.Count() > 0;
    }
Referenced by ManBase::EOnFrame().
OnVoiceEvent()
override void GameplayEffectWidgets_base::OnVoiceEvent (float breathing_resistance01) inline private
Definition at line 634 of file gameplayeffectwidgets.c.
    {
        m_BreathResidue += Math.Lerp(0,0.35,breathing_resistance01);
        m_BreathResidue = Math.Clamp(m_BreathResidue,0,1);
    }
References Math::Clamp(), and Math::Lerp().
Referenced by ManBase::UpdateMaskBreathWidget().
PairIDToTypes()
protected void GameplayEffectWidgets_base::PairIDToTypes () inline private
Definition at line 96 of file gameplayeffectwidgets.c.
    {
        m_IDToTypeMap.Insert(EffectWidgetsTypes.BLEEDING_LAYER,GameplayEffectsDataBleeding);
    }
Referenced by GameplayEffectWidgets().
ProcessWidgetUpdate()
protected void GameplayEffectWidgets_base::ProcessWidgetUpdate (Widget w, int type, float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 481 of file gameplayeffectwidgets.c.
    {
        switch (type)
        {
            case EffectWidgetsTypes.MOTO_BREATH:
            case EffectWidgetsTypes.HELMET_BREATH:
            case EffectWidgetsTypes.MASK_BREATH:
            {
                UpdateBreathEffect(ImageWidget.Cast(w));
            }
            break;
            case EffectWidgetsTypes.MOTO_OCCLUDER:
            case EffectWidgetsTypes.EYEPATCH_OCCLUDER:
            case EffectWidgetsTypes.HELMET_OCCLUDER:
            case EffectWidgetsTypes.MASK_OCCLUDER:
            {
                UpdateOccluderEffect(ImageWidget.Cast(w),type,timeSlice,p,handle);
            }
            break;
            case EffectWidgetsTypes.COVER_FLASHBANG:
            {
                UpdateFlashbangEffect(ImageWidget.Cast(w));
            }
            break;
            default:
                //Print("---invalid widget type to update---");
            break;
        }
    }
References UpdateBreathEffect(), UpdateFlashbangEffect(), and UpdateOccluderEffect().
Referenced by UpdateWidgets().
RegisterGameplayEffectData()
override void GameplayEffectWidgets_base::RegisterGameplayEffectData (int id, Param p) inline private
Definition at line 106 of file gameplayeffectwidgets.c.
    {
        if (!m_WidgetDataMap.Get(id).DataInitialized())
        {
            m_WidgetDataMap.Get(id).RegisterData(p);
        }
    }
Referenced by BleedingSourcesManagerBase::Init(), and BleedingSourcesManagerBase::RegisterBleedingZoneEx().
RegisterLayouts()
protected void GameplayEffectWidgets_base::RegisterLayouts (string path, array< int > types) inline private
Registers new layout and ties effect IDs to it.
Note
Order of layout creation matters, they get layered on top of each other. Within a single layout, widget priorities govern the widget order.
Definition at line 85 of file gameplayeffectwidgets.c.
    {
        Widget w = GetGame().GetWorkspace().CreateWidgets(path,m_Root,false);
        m_UniqueLayouts.Insert(w);
        w.Show(false);
        foreach (int i : types)
        {
            m_Layouts.Set(i,w);
        }
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_Root, and path.
Referenced by GameplayEffectWidgets().
RemoveActiveEffects()
override void GameplayEffectWidgets_base::RemoveActiveEffects (array< int > effects) inline private
Definition at line 297 of file gameplayeffectwidgets.c.
    {
        if (effects && effects.Count() > 0)
        {
            m_RunningEffectsPrevious.Copy(m_RunningEffects);
            int value;
            int idx;
            for (int i = 0; i < effects.Count(); i++)
            {
                value = effects.Get(i);
                idx = m_RunningEffects.Find(value);
                if (idx != -1)
                {
                    m_RunningEffects.Remove(idx);
                }
            }
            if (m_RunningEffectsPrevious.Count() != m_RunningEffects.Count())
            {
                UpdateVisibility();
            }
        }
    }
References UpdateVisibility().
Referenced by ManBase::OnCommandHandlerTick(), PPERequester_GameplayBase::OnStop(), SetNVPostprocess(), and GameplayEffectsData::Update().
RemoveSuspendRequest()
override void GameplayEffectWidgets_base::RemoveSuspendRequest (int request_id) inline private
Definition at line 342 of file gameplayeffectwidgets.c.
    {
        int idx = m_SuspendRequests.Find(request_id);
        if (idx != -1)
        {
            m_SuspendRequests.Remove(idx);
        }
        UpdateVisibility();
    }
References UpdateVisibility().
Referenced by PPERequester_GameplayBase::OnStop(), and ManBase::OnUnconsciousStop().
StopAllEffects()
override void GameplayEffectWidgets_base::StopAllEffects () inline private
Definition at line 322 of file gameplayeffectwidgets.c.
    {
        m_Root.Show(false); //to avoid visual 'peeling'
        m_RunningEffectsPrevious.Copy(m_RunningEffects);
        m_RunningEffects.Clear();
        UpdateVisibility();
    }
References Widget::Clear(), m_Root, and UpdateVisibility().
Referenced by ManBase::SimulateDeath().
TranslateIDToType()
protected GameplayEffectWidgets_base::TranslateIDToType (int typeID) inline private
Definition at line 101 of file gameplayeffectwidgets.c.
    {
        return m_IDToTypeMap.Get(typeID);
    }
Referenced by InitWidgetSet().
Update()
override void GameplayEffectWidgets_base::Update (float timeSlice) inline private
Generic update, called on frame from the player.
Definition at line 604 of file gameplayeffectwidgets.c.
    {
        if (m_SuspendRequests.Count() > 0)
        {
            return;
        }
        UpdateWidgets(-1,timeSlice);
    }
References UpdateWidgets().
Referenced by ManBase::EOnFrame().
UpdateBreathEffect()
protected void GameplayEffectWidgets_base::UpdateBreathEffect (ImageWidget w) inline private
Definition at line 544 of file gameplayeffectwidgets.c.
    {
        w.SetColor(m_BreathColor);
        w.SetAlpha(m_BreathAlphaVal);
    }
Referenced by ProcessWidgetUpdate().
UpdateFlashbangEffect()
protected void GameplayEffectWidgets_base::UpdateFlashbangEffect (ImageWidget w) inline private
Definition at line 576 of file gameplayeffectwidgets.c.
    {
        w.SetAlpha(1 - m_FlashbangCoverAlphaVal);
    }
Referenced by ProcessWidgetUpdate().
UpdateOccluderEffect()
protected void GameplayEffectWidgets_base::UpdateOccluderEffect (ImageWidget w, int type, float timeSlice, Param p, int handle) inline private
Definition at line 557 of file gameplayeffectwidgets.c.
    {
    }
Referenced by ProcessWidgetUpdate().
UpdateVisibility()
protected void GameplayEffectWidgets_base::UpdateVisibility () inline private
Definition at line 211 of file gameplayeffectwidgets.c.
    {
        Widget w;
        //Hide diff
        int value;
        GameplayEffectsData dta;
        for (int i = 0; i < m_RunningEffectsPrevious.Count(); i++)
        {
            value = m_RunningEffectsPrevious.Get(i);
            dta = m_WidgetDataMap.Get(value);
            if (m_RunningEffects.Count() < 1 || m_RunningEffects.Find(value) == -1)
            {
                if (dta.HasDefinedHandle())
                {
                    dta.UpdateVisibility(false);
                }
                else
                {
                    for (int j = 0; j < m_WidgetDataMap.Get(value).GetWidgetSet().Count(); j++)
                    {
                        w = m_WidgetDataMap.Get(value).GetWidgetSet().Get(j);
                        w.Show(false);
                    }
                    w.GetParent().Show(false);
                }
            }
        }
        //Show running effects
        if (m_RunningEffects.Count() > 0)
        {
            value = 0;
            for (i = 0; i < m_RunningEffects.Count(); i++)
            {
                value = m_RunningEffects.Get(i);
                dta = m_WidgetDataMap.Get(value);
                if (dta.HasDefinedHandle())
                {
                    dta.m_LayoutRoot.Show(true);
                    dta.UpdateVisibility(true);
                }
                else
                {
                    for (j = 0; j < m_WidgetDataMap.Get(value).GetWidgetSet().Count(); j++)
                    {
                        w = m_WidgetDataMap.Get(value).GetWidgetSet().Get(j);
                        w.Update();
                        w.Show(true);
                    }
                    while (w) //dumb but necessary because of uncertain "visible" setting of the layout
                    {
                        w = w.GetParent();
                        if (w)
{
                            w.Show(true);
                        }
                    }
                }
            }
        }
        m_Root.Show(m_RunningEffects.Count() > 0 && m_SuspendRequests.Count() < 1);
        m_RunningEffectsPrevious.Clear();
    }
References Widget::Clear(), Count, GameplayEffectsData::HasDefinedHandle(), m_Root, and GameplayEffectsData::UpdateVisibility().
Referenced by AddActiveEffects(), AddSuspendRequest(), ClearSuspendRequests(), GameplayEffectWidgets(), RemoveActiveEffects(), RemoveSuspendRequest(), and StopAllEffects().
UpdateWidgets()
override void GameplayEffectWidgets_base::UpdateWidgets (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
Usually called in course of an OnFrame update, can be manually called from elsewhere with parameters.
Definition at line 364 of file gameplayeffectwidgets.c.
    {
        /*if (m_SuspendRequests.Count() > 0)
        {
            return;
        }*/
        GameplayEffectsData dta;
        array<ref Widget> widget_set;
        if (type == EffectWidgetsTypes.ROOT)
        {
            HandleWidgetRoot(timeSlice,p,handle);
        }
        else if (type == -1) //update stuff from the m_UpdatingEffects
        {
            int type_widgetset = 0;
            for (int i = 0; i < m_UpdatingEffects.Count(); i++)
            {
                if (m_RunningEffects.Find(m_UpdatingEffects.Get(i)) != -1)
                {
                    type_widgetset = m_UpdatingEffects.Get(i);
                    dta = m_WidgetDataMap.Get(type_widgetset);
                    if (dta.HasDefinedHandle() && dta.DataInitialized())
                    {
                        dta.Update(timeSlice,p,handle); //calculate and apply
                    }
                    else
                    {
                        CalculateValues(type_widgetset,timeSlice,p,handle);
                        widget_set = dta.GetWidgetSet();
                        foreach (Widget w : widget_set)
{
                            if (w.IsVisibleHierarchy() && m_UpdatedWidgetsCheck.Find(w) == -1)
{
                                m_UpdatedWidgetsCheck.Insert(w);
                                ProcessWidgetUpdate(w,type_widgetset,timeSlice,p,handle);
                            }
                        }
                    }
                }
            }
        }
        else //update specific widget set
        {
            if (m_RunningEffects.Find(type) != -1) //only do if the effect is running (FPS stonks!)
            {
                dta = m_WidgetDataMap.Get(type);
                if (dta.HasDefinedHandle() && dta.DataInitialized())
                {
                    dta.Update(timeSlice,p,handle); //calculate and apply
                }
                else
                {
                    CalculateValues(type,timeSlice,p,handle);
                    widget_set = dta.GetWidgetSet();
                    foreach (Widget w2 : widget_set)
                    {
                        if (w2.IsVisibleHierarchy() && m_UpdatedWidgetsCheck.Find(w2) == -1)
{
                            m_UpdatedWidgetsCheck.Insert(w2);
                            ProcessWidgetUpdate(w2,type,timeSlice,p,handle);
                        }
                    }
                }
            }
        }
        m_UpdatedWidgetsCheck.Clear();
        m_UpdatedWidgetSetsCheck.Clear();
    }
References CalculateValues(), GameplayEffectsData::DataInitialized(), HandleWidgetRoot(), GameplayEffectsData::HasDefinedHandle(), ProcessWidgetUpdate(), and GameplayEffectsData::Update().
Referenced by ScriptedWidgetEventHandler::Apply(), PPERequester_GameplayBase::OnUpdate(), StartSourceBleedingIndication(), StopSourceBleedingIndication(), and Update().
Member Data Documentation
BREATH_COLOR_MULT_MAX
const float GameplayEffectWidgets_base::BREATH_COLOR_MULT_MAX = 0.8 private
Definition at line 520 of file gameplayeffectwidgets.c.
BREATH_COLOR_MULT_MIN
const float GameplayEffectWidgets_base::BREATH_COLOR_MULT_MIN = 0.5 private
Definition at line 519 of file gameplayeffectwidgets.c.
BREATH_HDR_MAX
const float GameplayEffectWidgets_base::BREATH_HDR_MAX = 1.0 private
Definition at line 518 of file gameplayeffectwidgets.c.
BREATH_HDR_MIN
const float GameplayEffectWidgets_base::BREATH_HDR_MIN = 0.005 private
Definition at line 517 of file gameplayeffectwidgets.c.
m_BreathAlphaVal
protected float GameplayEffectWidgets_base::m_BreathAlphaVal private
Definition at line 29 of file gameplayeffectwidgets.c.
m_BreathColor
protected int GameplayEffectWidgets_base::m_BreathColor private
Definition at line 28 of file gameplayeffectwidgets.c.
m_BreathMultStamina
protected float GameplayEffectWidgets_base::m_BreathMultStamina private
Definition at line 21 of file gameplayeffectwidgets.c.
m_BreathResidue
protected float GameplayEffectWidgets_base::m_BreathResidue private
Definition at line 22 of file gameplayeffectwidgets.c.
m_FlashbangCoverAlphaVal
protected float GameplayEffectWidgets_base::m_FlashbangCoverAlphaVal private
Definition at line 30 of file gameplayeffectwidgets.c.
m_IDToTypeMap
protected ref map<int,typename> GameplayEffectWidgets_base::m_IDToTypeMap private
Definition at line 18 of file gameplayeffectwidgets.c.
m_Layouts
protected ref map<int,ref Widget> GameplayEffectWidgets_base::m_Layouts private
Definition at line 9 of file gameplayeffectwidgets.c.
m_Root
protected ref Widget GameplayEffectWidgets_base::m_Root private
Definition at line 8 of file gameplayeffectwidgets.c.
m_RunningEffects
protected ref set<int> GameplayEffectWidgets_base::m_RunningEffects private
Definition at line 12 of file gameplayeffectwidgets.c.
m_RunningEffectsPrevious
protected ref set<int> GameplayEffectWidgets_base::m_RunningEffectsPrevious private
Definition at line 13 of file gameplayeffectwidgets.c.
m_SuspendRequests
protected ref set<int> GameplayEffectWidgets_base::m_SuspendRequests private
Definition at line 17 of file gameplayeffectwidgets.c.
m_TimeProgBreath
protected float GameplayEffectWidgets_base::m_TimeProgBreath private
Definition at line 20 of file gameplayeffectwidgets.c.
m_UniqueLayouts
protected ref set<ref Widget> GameplayEffectWidgets_base::m_UniqueLayouts private
Definition at line 10 of file gameplayeffectwidgets.c.
m_UpdatedWidgetsCheck
protected ref array<ref Widget> GameplayEffectWidgets_base::m_UpdatedWidgetsCheck private
Definition at line 15 of file gameplayeffectwidgets.c.
m_UpdatedWidgetSetsCheck
protected ref array<int> GameplayEffectWidgets_base::m_UpdatedWidgetSetsCheck private
Definition at line 16 of file gameplayeffectwidgets.c.
m_UpdatingEffects
protected ref array<int> GameplayEffectWidgets_base::m_UpdatingEffects private
Definition at line 14 of file gameplayeffectwidgets.c.
m_WidgetDataMap
protected ref GameplayEffectDataMap GameplayEffectWidgets_base::m_WidgetDataMap private
Definition at line 11 of file gameplayeffectwidgets.c.
WIDGETSET_BREATH
protected const int GameplayEffectWidgets_base::WIDGETSET_BREATH = 100 private
Definition at line 25 of file gameplayeffectwidgets.c.