DayzKode: ScriptInvoker Class Reference
ScriptInvoker Class Reference
ScriptInvoker Class provide list of callbacks
usage:
Private Member Functions
proto native void Clear ()
remove all calls from list
proto void Insert (func fn)
insert method to list
proto void Invoke (void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
invoke call on all inserted methods with given arguments
proto void Remove (func fn)
remove specific call from list
Detailed Description
ScriptInvoker Class provide list of callbacks
usage:
class Player
{
 ref ScriptInvoker m_DeathInvoker    = new ScriptInvoker();
 void OnKilled()
 {
     m_DeathInvoker.Invoke(this);
 }
}
void LogPlayerDeath(p)
{
 Print("RIP " + p);
}
class Game
{
 void RemovePlayer(Player p)
 {
 }
 void GameOver()
 {
 }
}
void OnPlayerSpaned(Player p)
{
 Game game = GetGame();
 p.m_DeathInvoker.Insert(LogPlayerDeath);
 p.m_DeathInvoker.Insert(game.RemovePlayer);
 p.m_DeathInvoker.Insert(game.GameOver);
}
Definition at line 115 of file tools.c.
Member Function Documentation
Clear()
proto native void ScriptInvoker::Clear () private
remove all calls from list
Referenced by SEffectManager::Cleanup(), ConstructionActionData::ConstructionActionData(), CraftingManager::CraftingManager(), and ~VONManagerImplementation().
Insert()
proto void ScriptInvoker::Insert (func fn) private
insert method to list
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), NotificationSystem::BindOnAdd(), NotificationSystem::BindOnRemove(), ServerBrowserTab::Construct(), ConstructionActionData::ConstructionActionData(), ScriptedWidgetEventHandler::ContinuousActionProgress(), CraftingManager::CraftingManager(), CrossHairSelector(), EffectSound::Event_OnRegistered(), UIScriptedMenu::GesturesMenu(), UIScriptedMenu::InGameMenuXbox(), Init(), PluginManager::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), InitEffect(), Inventory(), ScriptedWidgetEventHandler::ItemActionsWidget(), MainMenuButtonEffect::MainMenuButtonEffect(), PluginBase::OnInit(), MissionBase::OnInit(), UIPopupScript::OnOpen(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialProgressBar::RadialProgressBar(), UIScriptedMenu::RadialQuickbarMenu(), ServerBrowserTab::RefreshList(), AnalyticsManagerClient::RegisterEvents(), SetEnableEventFrame(), EffectParticle::SetParticle(), UIScriptedMenu::SetServersLoadingTab(), and SoftSkillManagerDebug().
Invoke()
proto void ScriptInvoker::Invoke (void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) private
invoke call on all inserted methods with given arguments
Referenced by NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), CheckValue(), SEffectManager::Event_OnFrameUpdate(), EffectSound::Event_OnSoundFadeInStopped(), EffectSound::Event_OnSoundFadeOutStarted(), EffectSound::Event_OnSoundWaveEnded(), EffectSound::Event_OnSoundWaveStarted(), UIScriptedMenu::OnClick(), OnEvent(), OnlineServices::OnFriendsAsync(), OnlineServices::OnGetServerModList(), Input::OnLastInputDeviceChanged(), OnlineServices::OnLoadServersAsync(), OnParticleEnd(), OnParticleParented(), OnParticleReset(), OnParticleStart(), OnParticleStop(), OnParticleUnParented(), OnlineServices::OnPermissionsAsync(), OptionsAccess::OnRevert(), OnRPC(), OnUpdate(), UIScriptedMenu::PerformSwitchPreset(), Stop(), SwitchPreset(), ClientData::SyncEvent_OnEntityKilled(), ClientData::SyncEvent_OnPlayerIgnitedFireplace(), ClientData::SyncEvent_OnRecievedPlayerList(), NotificationSystem::Update(), and ActionVariantManager::UpdateVariants().
Remove()
proto void ScriptInvoker::Remove (func fn) private
remove specific call from list
Referenced by EffectSound::Event_OnUnregistered(), EffectParticle::InitEffect(), EffectSound::InitEffect(), ServerBrowserTab::LoadingServersStop(), UIPopupScript::OnClose(), PluginBase::OnDestroy(), MissionBase::OnMissionFinish(), SetEnableEventFrame(), EffectParticle::SetParticle(), UIScriptedMenu::SetServersLoadingTab(), NotificationSystem::UnbindOnAdd(), NotificationSystem::UnbindOnRemove(), AnalyticsManagerClient::UnregisterEvents(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ~CrossHairSelector(), UIScriptedMenu::~InGameMenuXbox(), ScriptedWidgetEventHandler::~ItemActionsWidget(), MainMenuButtonEffect::~MainMenuButtonEffect(), ScriptedWidgetEventHandler::~OptionsMenuSounds(), PluginManager::~PluginManager(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), RadialProgressBar::~RadialProgressBar(), UIScriptedMenu::~ServerBrowserMenuNew(), ~SoftSkillManagerDebug(), UIPopupScript::~UIPopupScriptSceneManager(), and UIPopupScript::~UIPopupScriptSceneSettings().