DayzKode: HandGuardBase Class Reference
HandGuardBase Class Reference
guards
Private Member Functions
void BotGuardHasItemInHands (Man p=NULL)
bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
override bool GuardCondition (HandEventBase e)
void HandGuardAnd (HandGuardBase arg0=NULL, HandGuardBase arg1=NULL)
void HandGuardCanForceSwap (Man p=NULL)
void HandGuardCanSwap (Man p=NULL)
void HandGuardHasDestroyedItemInHands (Man p=NULL)
void HandGuardHasItemInEvent (Man p=NULL)
void HandGuardHasItemInHands (Man p=NULL)
void HandGuardHasRoomForItem (Man p=NULL)
void HandGuardInstantForceSwap (Man p=NULL)
void HandGuardIsSameItemInHands (Man p=NULL)
void HandGuardNot (HandGuardBase arg0=NULL)
void HandGuardOr (HandGuardBase arg0=NULL, HandGuardBase arg1=NULL)
void HandSelectAnimationOfForceSwapInHandsEvent (Man p=NULL)
void HandSelectAnimationOfMoveFromHandsEvent (Man p=NULL)
void HandSelectAnimationOfTakeToHandsEvent (Man p=NULL)
bool ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2)
Private Attributes
ref HandGuardBase m_arg0
ref HandGuardBase m_arg1
ref HandGuardHasRoomForItem m_HasRoomGuard
protected Man m_Player
Detailed Description
guards
represents guard on a transition from state to state
Definition at line 6 of file hand_guards.c.
Member Function Documentation
BotGuardHasItemInHands()
void HandGuardBase::BotGuardHasItemInHands (Man p = NULL) inline private
Definition at line 61 of file botguards.c.
{ m_Player = p; }
References m_Player.
GuardCondition() [1/16]
bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 13 of file hand_guards.c.
{ return true; }
GuardCondition() [2/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 24 of file hand_guards.c.
    {
        bool result = m_arg0.GuardCondition(e) && m_arg1.GuardCondition(e);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type() + " && " + m_arg1.Type(), "HandGuardAnd" , "n/a", "GuardCondition", e.m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [3/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 45 of file hand_guards.c.
    {
        bool result = !m_arg0.GuardCondition(e);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type(), "HandGuardNot" , "n/a", "GuardCondition", e.m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [4/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 66 of file hand_guards.c.
    {
        bool result = m_arg0.GuardCondition(e) || m_arg1.GuardCondition(e);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_arg0.Type() + " || " + m_arg1.Type(), "HandGuardOr" , "n/a", "GuardCondition", e.m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
GuardCondition() [5/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 85 of file hand_guards.c.
    {
        EntityAI eai = e.GetSrcEntity();
        if (eai != NULL /* && CanTakeInHands*/)
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("GuardCondition result: true - " + eai, "HandGuardHasItemInEvent" , "n/a", "GuardCondition", m_Player.ToString() );
            }
            #endif
            return true;
        }
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: false - " + eai, "HandGuardHasItemInEvent" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return false;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [6/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 140 of file hand_guards.c.
    {
        bool result = false;
        if (e.GetSrcEntity() == m_Player.GetHumanInventory().GetEntityInHands())
        {
            result = true;
        }
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result + " - srcItem = " + e.GetSrcEntity() + " hnd= " + m_Player.GetHumanInventory().GetEntityInHands(), "HandGuardIsSameItemInHands" , "n/a", "GuardCondition", e.m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [7/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 163 of file hand_guards.c.
    {
        EntityAI hnd = m_Player.GetHumanInventory().GetEntityInHands();
        if (e.GetSrcEntity())
        {
            if (e.GetSrcEntity() == hnd)
            {
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryHFSMLogEnable() )
                {
                    Debug.InventoryHFSMLog("GuardCondition result: true - has same entity in hands " + hnd, "HandGuardHasDestroyedItemInHands" , "n/a", "GuardCondition", m_Player.ToString() );
                }
                #endif
                return true;
            }
            if (hnd == null)
            {
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryHFSMLogEnable() )
                {
                    Debug.InventoryHFSMLog("GuardCondition result: true - hands already empty", "HandGuardHasDestroyedItemInHands" , "n/a", "GuardCondition", m_Player.ToString() );
                }
                #endif
                return true;
            }
        }
        else
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("GuardCondition result: true - hands already empty and item destroyed", "HandGuardHasDestroyedItemInHands" , "n/a", "GuardCondition", m_Player.ToString() );
            }
            #endif
            return true;
        }
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: false -  destroyed entity not in hands", "HandGuardHasDestroyedItemInHands" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return false;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [8/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 215 of file hand_guards.c.
    {
        bool result = false;
        if (m_Player.GetHumanInventory().GetEntityInHands())
        {
            result = true;
        }
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result + " - " + m_Player.GetHumanInventory().GetEntityInHands(), "HandGuardHasItemInHands" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [9/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 238 of file hand_guards.c.
    {
        if (e.GetDst() && e.GetDst().IsValid())
        {
            if( !GetGame().IsDedicatedServer())
            {
                if(m_Player)
                    m_Player.GetHumanInventory().ClearInventoryReservationEx(e.GetDst().GetItem(),e.GetDst());
            }
            if (!GameInventory.LocationTestAddEntity(e.GetDst(), false, true, true, true, true, false))
            {
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryHFSMLogEnable() )
                {
                    Debug.InventoryHFSMLog("GuardCondition result: false - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()), "HandGuardHasRoomForItem" , "n/a", "GuardCondition", m_Player.ToString() );
                }
                #endif
                //hndDebugPrint("[hndfsm] HandGuardHasRoomForItem - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()));
                //Error("[hndfsm] HandGuardHasRoomForItem - no room at dst=" + InventoryLocation.DumpToStringNullSafe(e.GetDst()));
                return false;
            }
            if( !GetGame().IsDedicatedServer())
            {
                if(m_Player)
                    m_Player.GetHumanInventory().AddInventoryReservationEx(e.GetDst().GetItem(), e.GetDst(), GameInventory.c_InventoryReservationTimeoutShortMS);
            }
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("GuardCondition result: true", "HandGuardHasRoomForItem" , "n/a", "GuardCondition", m_Player.ToString() );
            }
            #endif
            return true;
        }
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: false - e.m_Dst is null", "HandGuardHasRoomForItem" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return false;
    }
References InventoryLocation::DumpToStringNullSafe(), HandEventBase::GetDst(), GetGame(), InventoryLocation::GetItem(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), InventoryLocation::IsValid(), and m_Player.
GuardCondition() [10/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 293 of file hand_guards.c.
    {
        HandEventSwap es = HandEventSwap.Cast(e);
        bool result = GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem());
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardCanSwap" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        //hndDebugPrint("[hndfsm] HandGuardCanSwap guard - cannot swap");
        return result;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [11/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 314 of file hand_guards.c.
    {
        HandEventForceSwap es = HandEventForceSwap.Cast(e);
        bool result = GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem());
        if (!result && es.m_Dst2)
            result = GameInventory.CanForceSwapEntitiesEx(es.GetSrc().GetItem(), null, es.m_Src2.GetItem(), es.m_Dst2);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardCanForceSwap" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return result;
    }
References Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [12/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 338 of file hand_guards.c.
    {
        HandEventForceSwap es = HandEventForceSwap.Cast(e);
        InventoryLocation src1 = es.m_Src;
        InventoryLocation dst2 = es.m_Dst2;
        bool result = false;
        if (src1.GetType() == InventoryLocationType.CARGO && dst2.GetType() == InventoryLocationType.CARGO)
        {
            if (src1.GetParent() == dst2.GetParent())
            {
                result = true;
            }
        }
        #ifdef DEVELOPER
        if (LogManager.IsInventoryHFSMLogEnable())
        {
            Debug.InventoryHFSMLog("GuardCondition result: " + result, "HandGuardInstantForceSwap" , "n/a", "GuardCondition", m_Player.ToString() );
        }
        #endif
        return result;
    }
References InventoryLocation::GetParent(), InventoryLocation::GetType(), Debug::InventoryHFSMLog(), LogManager::IsInventoryHFSMLogEnable(), and m_Player.
GuardCondition() [13/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 189 of file handanimated_guards.c.
    {
        int animType = -1;
        if (SelectAnimationOfTakeToHands(e.m_Player, e.GetSrc(), e.GetDst(), animType))
        {
            e.m_AnimationID = animType;
            return true;
        }
        return false;
    }
References HandEventBase::GetDst(), and SelectAnimationOfTakeToHands().
GuardCondition() [14/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 211 of file handanimated_guards.c.
    {
        if (m_HasRoomGuard.GuardCondition(e))
        {
            EntityAI eai = m_Player.GetHumanInventory().GetEntityInHands();
            if (eai)
            {
                InventoryLocation src = new InventoryLocation;
                if (eai.GetInventory().GetCurrentInventoryLocation(src))
                {
                    int animType = -1;
                    if (SelectAnimationOfMoveFromHands(e.m_Player, src, e.GetDst(), animType))
                    {
                        e.m_AnimationID = animType;
                        return true;
                    }
                    return false;
                }
            }
        }
        return false;
    }
References HandEventBase::GetDst(), m_Player, and SelectAnimationOfMoveFromHands().
GuardCondition() [15/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 250 of file handanimated_guards.c.
    {
        HandEventForceSwap es = HandEventForceSwap.Cast(e);
        if (es)
        {
            hndDebugPrint("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent FSwap e=" + e.DumpToString());
            if( !es.m_Src2.IsValid() || !es.m_Src.IsValid() )
            {
                Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - invalid item source");
                return false;
            }
            bool allow = false;
            if (GameInventory.CanSwapEntitiesEx(es.GetSrc().GetItem(), es.m_Src2.GetItem()))
                allow = true; // allow if ordinary swap
            else if (es.m_Dst2)
            {
                if (!GameInventory.CanForceSwapEntitiesEx(es.GetSrc().GetItem(), null, es.m_Src2.GetItem(), es.m_Dst2))
                {
                    Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - no room at dst=" + InventoryLocation.DumpToStringNullSafe(es.m_Dst2));
                }
                else
                {
                    allow = true;
                }
            }
            if (allow)
            {
                int animType1 = -1;
                int animType2 = -1;
                if (ProcessSwapEvent(e, animType1, animType2))
                {
                    e.m_AnimationID = animType1;
                    es.m_Animation2ID = animType2;
                    return true;
                }
            }
            else
                Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - m_HasRoomGuard.GuardCondition failed");
        }
        else
            Error("[hndfsm] HandSelectAnimationOfForceSwapInHandsEvent - not a swap event");
        return false;
    }
References HandEventBase::DumpToString(), InventoryLocation::DumpToStringNullSafe(), Error(), hndDebugPrint(), and HandEventBase::m_Animation2ID.
GuardCondition() [16/16]
override bool HandGuardBase::GuardCondition (HandEventBase e) inline private
Definition at line 63 of file botguards.c.
    {
        if (m_Player.GetHumanInventory().GetEntityInHands())
        {
            hndDebugPrint("[botfsm] guard - has valid entity in hands");
            return true;
        }
        hndDebugPrint("[botfsm] guard - no entity in hands");
        return false;
    }
References hndDebugPrint(), and m_Player.
HandGuardAnd()
void HandGuardBase::HandGuardAnd (HandGuardBase arg0 = NULL, HandGuardBase arg1 = NULL) inline private
Definition at line 22 of file hand_guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
HandGuardCanForceSwap()
void HandGuardBase::HandGuardCanForceSwap (Man p = NULL) inline private
Definition at line 312 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardCanSwap()
void HandGuardBase::HandGuardCanSwap (Man p = NULL) inline private
Definition at line 291 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasDestroyedItemInHands()
void HandGuardBase::HandGuardHasDestroyedItemInHands (Man p = NULL) inline private
Definition at line 161 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasItemInEvent()
void HandGuardBase::HandGuardHasItemInEvent (Man p = NULL) inline private
Definition at line 83 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasItemInHands()
void HandGuardBase::HandGuardHasItemInHands (Man p = NULL) inline private
Definition at line 213 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardHasRoomForItem()
void HandGuardBase::HandGuardHasRoomForItem (Man p = NULL) inline private
Definition at line 236 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
Referenced by HandSelectAnimationOfMoveFromHandsEvent().
HandGuardInstantForceSwap()
void HandGuardBase::HandGuardInstantForceSwap (Man p = NULL) inline private
Definition at line 336 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardIsSameItemInHands()
void HandGuardBase::HandGuardIsSameItemInHands (Man p = NULL) inline private
Definition at line 138 of file hand_guards.c.
{ m_Player = p; }
References m_Player.
HandGuardNot()
void HandGuardBase::HandGuardNot (HandGuardBase arg0 = NULL) inline private
Definition at line 43 of file hand_guards.c.
{ m_arg0 = arg0; }
HandGuardOr()
void HandGuardBase::HandGuardOr (HandGuardBase arg0 = NULL, HandGuardBase arg1 = NULL) inline private
Definition at line 64 of file hand_guards.c.
{ m_arg0 = arg0; m_arg1 = arg1; }
HandSelectAnimationOfForceSwapInHandsEvent()
void HandGuardBase::HandSelectAnimationOfForceSwapInHandsEvent (Man p = NULL) inline private
Definition at line 239 of file handanimated_guards.c.
{ m_Player = p; }
References m_Player.
HandSelectAnimationOfMoveFromHandsEvent()
void HandGuardBase::HandSelectAnimationOfMoveFromHandsEvent (Man p = NULL) inline private
Definition at line 206 of file handanimated_guards.c.
{
         m_Player = p;
        m_HasRoomGuard = new HandGuardHasRoomForItem(p);
    }
References HandGuardHasRoomForItem(), and m_Player.
HandSelectAnimationOfTakeToHandsEvent()
void HandGuardBase::HandSelectAnimationOfTakeToHandsEvent (Man p = NULL) inline private
Definition at line 187 of file handanimated_guards.c.
{ }
ProcessSwapEvent()
bool HandGuardBase::ProcessSwapEvent (notnull HandEventBase e, out int animType1, out int animType2) inline private
Definition at line 241 of file handanimated_guards.c.
    {
        HandEventSwap es = HandEventSwap.Cast(e);
        if (es)
            return SelectAnimationOfForceSwapInHands(e.m_Player, es.m_Src, es.m_Src2, es.m_Dst, es.m_Dst2, animType1, animType2);
        Error("HandSelectAnimationOfForceSwapInHandsEvent - not an swap event");
        return false;
    }
References Error(), and SelectAnimationOfForceSwapInHands().
Member Data Documentation
m_arg0
ref HandGuardBase HandGuardBase::m_arg0 private
Definition at line 19 of file hand_guards.c.
m_arg1
ref HandGuardBase HandGuardBase::m_arg1 private
Definition at line 20 of file hand_guards.c.
m_HasRoomGuard
ref HandGuardHasRoomForItem HandGuardBase::m_HasRoomGuard private
Definition at line 204 of file handanimated_guards.c.
m_Player
protected Man HandGuardBase::m_Player private
Definition at line 82 of file hand_guards.c.