DayzKode: ActionUnfoldMapCB Class Reference
ActionUnfoldMapCB Class Reference
Private Member Functions
void ActionUnfoldMapCB ()
bool CancelCondition (bool pEnable)
override void OnAnimationEvent (int pEventID)
override void OnFinish (bool pCanceled)
override void OnStateChange (int pOldState, int pCurrentState)
void PerformMapChange ()
override void SetActionData (ActionData action_data)
bool StateCheck ()
void ~ActionUnfoldMapCB ()
Private Attributes
bool m_CancelCondition
int m_FinalMovementState
bool m_HasReceivedEvent
int m_InitMovementState
bool m_MapFolding
Detailed Description
Definition at line 1 of file actionunfoldmap.c.
Constructor & Destructor Documentation
ActionUnfoldMapCB()
void ActionUnfoldMapCB::ActionUnfoldMapCB () inline private
Definition at line 9 of file actionunfoldmap.c.
    {
        RegisterAnimationEvent("ActionExec", UA_ANIM_EVENT);
        EnableStateChangeCallback();
        EnableCancelCondition(true);
    }
References EnableCancelCondition(), EnableStateChangeCallback(), RegisterAnimationEvent(), and UA_ANIM_EVENT.
~ActionUnfoldMapCB()
void ActionUnfoldMapCB::~ActionUnfoldMapCB () inline private
Definition at line 16 of file actionunfoldmap.c.
    {
        if (!CfgGameplayHandler.GetUse3DMap())
        {
            GetGame().GetMission().RemoveActiveInputExcludes({"map"}, false);
        }
        else
        {
            GetGame().GetMission().RemoveActiveInputExcludes({"loopedactions"}, false);
        }
        GetGame().GetMission().RemoveActiveInputRestriction(EInputRestrictors.MAP);
        if (!m_ActionData || !m_ActionData.m_Player )
            return;
        ItemMap chernomap = ItemMap.Cast(m_ActionData.m_Player.GetItemInHands());
        if (chernomap && m_ActionData.m_Player.IsMapOpen())
        {
            chernomap.SetMapStateOpen(false, m_ActionData.m_Player);
        }
    }
References GetGame(), CGame::GetMission(), CfgGameplayHandler::GetUse3DMap(), ActionBaseCB::m_ActionData, ActionData::m_Player, Mission::RemoveActiveInputExcludes(), and Mission::RemoveActiveInputRestriction().
Member Function Documentation
CancelCondition()
bool ActionUnfoldMapCB::CancelCondition (bool pEnable) inline private
Definition at line 44 of file actionunfoldmap.c.
    {
        return m_CancelCondition;
    }
References m_CancelCondition.
OnAnimationEvent()
override void ActionUnfoldMapCB::OnAnimationEvent (int pEventID) inline private
Definition at line 60 of file actionunfoldmap.c.
    {
        if (!m_ActionData || !m_ActionData.m_Player)
            return;
        switch (pEventID)
        {
            case UA_ANIM_EVENT:
                m_HasReceivedEvent = true;
                m_FinalMovementState = m_ActionData.m_Player.m_MovementState.m_iStanceIdx;
                if ( StateCheck() )
                {
                    PerformMapChange();
                    m_CancelCondition = false;
                }
                else
                {
                    m_CancelCondition = true;
                }
            break;
        }
    }
References ActionBaseCB::m_ActionData, m_CancelCondition, m_FinalMovementState, m_HasReceivedEvent, ActionData::m_Player, PerformMapChange(), StateCheck(), and UA_ANIM_EVENT.
OnFinish()
override void ActionUnfoldMapCB::OnFinish (bool pCanceled) inline private
Definition at line 84 of file actionunfoldmap.c.
    {
        //super.OnFinish(pCanceled);
        //Print(pCanceled);
        if ( m_ActionData && m_ActionData.m_Player )
        {
            if ( m_ActionData && m_ActionData.m_ActionComponent )
                m_ActionData.m_State = m_ActionData.m_ActionComponent.Interrupt(m_ActionData);
            if ( (!GetGame().IsDedicatedServer()) && GetGame().GetUIManager() && GetGame().GetUIManager().IsMenuOpen(MENU_MAP) )
            {
                GetGame().GetUIManager().FindMenu(MENU_MAP).Close();
            }
            ActionUnfoldMap action = ActionUnfoldMap.Cast(m_ActionData.m_Action);
            m_InitMovementState = -1;
            m_FinalMovementState = -1;
            m_ActionData.m_Player.SetMapClosingSyncSet(false); //reset
            ItemMap chernomap = ItemMap.Cast(m_ActionData.m_Player.GetItemInHands());
            if (chernomap && m_ActionData.m_Player.IsMapOpen())
            {
                chernomap.SetMapStateOpen(false, m_ActionData.m_Player);
            }
            if (action)
                action.End(m_ActionData);
        }
    }
References ActionUnfoldMap(), UIManager::FindMenu(), GetGame(), CGame::GetUIManager(), CABase::Interrupt(), ActionData::m_Action, ActionData::m_ActionComponent, ActionBaseCB::m_ActionData, m_FinalMovementState, m_InitMovementState, ActionData::m_Player, ActionData::m_State, and MENU_MAP.
OnStateChange()
override void ActionUnfoldMapCB::OnStateChange (int pOldState, int pCurrentState) inline private
Definition at line 49 of file actionunfoldmap.c.
    {
        if (!m_ActionData || !m_ActionData.m_Player)
            return;
        if ( ( pOldState == STATE_LOOP_IN && pCurrentState == STATE_LOOP_LOOP ) && !m_HasReceivedEvent )
        {
            m_CancelCondition = true;
        }
    }
References ActionBaseCB::m_ActionData, m_CancelCondition, m_HasReceivedEvent, ActionData::m_Player, STATE_LOOP_IN, and STATE_LOOP_LOOP.
PerformMapChange()
void ActionUnfoldMapCB::PerformMapChange () inline private
Definition at line 116 of file actionunfoldmap.c.
    {
        if (m_ActionData.m_Player.IsSwimming() || m_ActionData.m_Player.IsClimbing() || m_ActionData.m_Player.IsFalling() || m_ActionData.m_Player.IsClimbingLadder() || m_ActionData.m_Player.IsUnconscious() || m_ActionData.m_Player.IsRestrained())
            return;
        if ( m_CancelCondition ) { return; }
        ItemMap chernomap = ItemMap.Cast(m_ActionData.m_Player.GetItemInHands());
        if (chernomap && !m_ActionData.m_Player.IsMapOpen() && !m_MapFolding)
        {
            chernomap.SetMapStateOpen(true, m_ActionData.m_Player);
            if (!GetGame().IsMultiplayer() || GetGame().IsServer())
            {
                //chernomap.SyncMapMarkers();
            }
            if (!GetGame().IsDedicatedServer())
            {
                UIManager   m_UIManager;
                UIScriptedMenu  map_menu;
                m_UIManager = GetGame().GetUIManager();
                m_UIManager.CloseAll();
                if ( !CfgGameplayHandler.GetUse3DMap() )
                {
                    map_menu = m_UIManager.EnterScriptedMenu(MENU_MAP, NULL);
                    map_menu.InitMapItem(chernomap);
                    map_menu.LoadMapMarkers();
                    GetGame().GetMission().AddActiveInputExcludes({"map"});
                }
                else
                {
                    GetGame().GetMission().AddActiveInputExcludes({"loopedactions"});
                }
                GetGame().GetMission().AddActiveInputRestriction(EInputRestrictors.MAP);
            }
        }
        else if (chernomap && m_ActionData.m_Player.IsMapOpen())
        {
            chernomap.SetMapStateOpen(false, m_ActionData.m_Player);
            m_MapFolding = true;
            m_ActionData.m_Player.SetMapOpen(false);
        }
    }
References Mission::AddActiveInputExcludes(), Mission::AddActiveInputRestriction(), UIManager::CloseAll(), UIManager::EnterScriptedMenu(), GetGame(), CGame::GetMission(), CGame::GetUIManager(), CfgGameplayHandler::GetUse3DMap(), UIScriptedMenu::InitMapItem(), UIScriptedMenu::LoadMapMarkers(), ActionBaseCB::m_ActionData, m_CancelCondition, m_MapFolding, ActionData::m_Player, and MENU_MAP.
Referenced by OnAnimationEvent().
SetActionData()
override void ActionUnfoldMapCB::SetActionData (ActionData action_data) inline private
Definition at line 38 of file actionunfoldmap.c.
    {
        m_ActionData = action_data;
        m_InitMovementState = m_ActionData.m_Player.m_MovementState.m_iStanceIdx;
    }
References ActionBaseCB::m_ActionData, m_InitMovementState, and ActionData::m_Player.
StateCheck()
bool ActionUnfoldMapCB::StateCheck () inline private
Definition at line 160 of file actionunfoldmap.c.
    {
        return m_InitMovementState == m_FinalMovementState;
    }
References m_FinalMovementState, and m_InitMovementState.
Referenced by OnAnimationEvent().
Member Data Documentation
m_CancelCondition
bool ActionUnfoldMapCB::m_CancelCondition private
Definition at line 5 of file actionunfoldmap.c.
Referenced by CancelCondition(), OnAnimationEvent(), OnStateChange(), and PerformMapChange().
m_FinalMovementState
int ActionUnfoldMapCB::m_FinalMovementState private
Definition at line 7 of file actionunfoldmap.c.
Referenced by OnAnimationEvent(), OnFinish(), and StateCheck().
m_HasReceivedEvent
bool ActionUnfoldMapCB::m_HasReceivedEvent private
Definition at line 4 of file actionunfoldmap.c.
Referenced by OnAnimationEvent(), and OnStateChange().
m_InitMovementState
int ActionUnfoldMapCB::m_InitMovementState private
Definition at line 6 of file actionunfoldmap.c.
Referenced by OnFinish(), SetActionData(), and StateCheck().
m_MapFolding
bool ActionUnfoldMapCB::m_MapFolding private
Definition at line 3 of file actionunfoldmap.c.
Referenced by PerformMapChange().