DayzKode: Selection Class Reference
Selection Class Reference
Selection class.
Private Member Functions
proto native int GetLODVertexIndex (int sel_vertex_index)
proto native owned string GetName ()
proto native int GetVertexCount ()
vector GetVertexPosition (LOD lod, int index)
private void Selection ()
private void ~Selection ()
Detailed Description
Selection class.
Definition at line 175 of file gameplay.c.
Constructor & Destructor Documentation
Selection()
private void Selection::Selection () inline private
Definition at line 177 of file gameplay.c.
{}
~Selection()
private void Selection::~Selection () inline private
Definition at line 178 of file gameplay.c.
{}
Member Function Documentation
GetLODVertexIndex()
proto native int Selection::GetLODVertexIndex (int sel_vertex_index) private
Referenced by GetVertexPosition().
GetName()
proto native owned string Selection::GetName () private
GetVertexCount()
proto native int Selection::GetVertexCount () private
GetVertexPosition()
vector Selection::GetVertexPosition (LOD lod, int index) inline private
Definition at line 184 of file gameplay.c.
    {
        int lodIndex = GetLODVertexIndex(index);
        if (lodIndex == -1)
        {
            Error("Vertex doesn't exist");
            return vector.Zero;
        }
        return lod.GetVertexPosition(lodIndex);
    }
References Error(), GetLODVertexIndex(), LOD::GetVertexPosition(), and vector::Zero.