DayzKode: ActionDefibrilateSelf Class Reference
ActionDefibrilateSelf Class Reference
Private Member Functions
void ActionDefibrilateSelf ()
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actiondefibrilateself.c.
Constructor & Destructor Documentation
ActionDefibrilateSelf()
void ActionDefibrilateSelf::ActionDefibrilateSelf () inline private
Definition at line 11 of file actiondefibrilateself.c.
    {
        m_CallbackClass = ActionDefibrilateSelfCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_HIGH;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_CRAFTING;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#defibrilate_myself";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_HIGH.
Member Function Documentation
CreateConditionComponents()
override void ActionDefibrilateSelf::CreateConditionComponents () inline private
Definition at line 21 of file actiondefibrilateself.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionDefibrilateSelf::HasTarget () inline private
Definition at line 28 of file actiondefibrilateself.c.
    {
        return false;
    }
OnFinishProgressClient()
override void ActionDefibrilateSelf::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 33 of file actiondefibrilateself.c.
    {
        Defibrillator defib;
        PlayerBase player = action_data.m_Player;
        Class.CastTo(defib, action_data.m_MainItem);
        DefibrillateClient(action_data.m_Player, defib);
    }
References Class::CastTo(), ActionDefibrilateBase::DefibrillateClient(), ActionData::m_MainItem, and ActionData::m_Player.
OnFinishProgressServer()
override void ActionDefibrilateSelf::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 42 of file actiondefibrilateself.c.
    {
        Defibrillator defib;
        PlayerBase player = action_data.m_Player;
        Class.CastTo(defib, action_data.m_MainItem);
        DefibrillateServer(action_data.m_Player, defib);
    }
References Class::CastTo(), ActionDefibrilateBase::DefibrillateServer(), ActionData::m_MainItem, and ActionData::m_Player.