DayzKode: ActionCoverHeadTarget Class Reference
ActionCoverHeadTarget Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionCoverHeadTarget ()
override void CreateConditionComponents ()
bool IsWearingHeadgear (PlayerBase player)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actioncoverheadtarget.c.
Constructor & Destructor Documentation
ActionCoverHeadTarget()
void ActionCoverHeadTarget::ActionCoverHeadTarget () inline private
Definition at line 11 of file actioncoverheadtarget.c.
    {
        m_CallbackClass = ActionCoverHeadTargetCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_TARGET;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        //m_Animation = "INJECTEPIPENS";
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#put_on_targets_head";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCoverHeadTarget::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 28 of file actioncoverheadtarget.c.
    {
        PlayerBase targetPlayer;
        Class.CastTo(targetPlayer, target.GetObject());
        if ( !IsWearingHeadgear(targetPlayer) )
        {
            return true;
        }
        return false;
    }
References Class::CastTo(), and IsWearingHeadgear().
CreateConditionComponents()
override void ActionCoverHeadTarget::CreateConditionComponents () inline private
Definition at line 21 of file actioncoverheadtarget.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTMan(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
IsWearingHeadgear()
bool ActionCoverHeadTarget::IsWearingHeadgear (PlayerBase player) inline private
Definition at line 67 of file actioncoverheadtarget.c.
    {
        if ( player.GetInventory().FindAttachment(InventorySlots.HEADGEAR) )
        {
            return true;
        }
        return false;
    }
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionCoverHeadTarget::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 40 of file actioncoverheadtarget.c.
    {
        //setaperture will be called from here, or from statemachine
        PlayerBase ntarget;
        Class.CastTo(ntarget, action_data.m_Target.GetObject());
        CoverHeadOfTargetPlayerLambda lambda = new CoverHeadOfTargetPlayerLambda(action_data.m_MainItem, "BurlapSackCover", ntarget);
        action_data.m_Player.ServerReplaceItemInHandsWithNewElsewhere(lambda);
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.