DayzKode: ActionUnpackGift Class Reference
ActionUnpackGift Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionUnpackGift ()
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionunpackgift.c.
Constructor & Destructor Documentation
ActionUnpackGift()
void ActionUnpackGift::ActionUnpackGift () inline private
Definition at line 11 of file actionunpackgift.c.
    {
        m_CallbackClass = ActionUnpackGiftCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM;
        //m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_Text = "#STR_Unwrap";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionUnpackGift::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actionunpackgift.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionUnpackGift::CreateConditionComponents () inline private
Definition at line 21 of file actionunpackgift.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionUnpackGift::HasTarget () inline private
Definition at line 27 of file actionunpackgift.c.
    {
        return false;
    }
OnFinishProgressServer()
override void ActionUnpackGift::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 37 of file actionunpackgift.c.
    {
        ItemBase item = ItemBase.Cast(action_data.m_MainItem);
        CargoBase cargo = item.GetInventory().GetCargo();
        InventoryLocation il_dst = new InventoryLocation;
        InventoryLocation il_src = new InventoryLocation;
        float dmg = item.GetHealth01("","");
        if( dmg > 0.25 )
        {
            Object paper = GetGame().CreateObjectEx("GiftWrapPaper",action_data.m_Player.GetPosition(),ECE_PLACE_ON_SURFACE,RF_DEFAULT);
            paper.SetHealth01("","", dmg - 0.25 );
        }
        for(int i = cargo.GetItemCount() - 1; i >= 0 ; i--)
        {
            EntityAI cargo_item = cargo.GetItem(i);
            GameInventory.SetGroundPosByOwner(action_data.m_Player,cargo_item,il_dst);
            cargo_item.GetInventory().GetCurrentInventoryLocation(il_src);
            if(GetGame().IsDedicatedServer())
                action_data.m_Player.ServerTakeToDst( il_src, il_dst );
            else
                action_data.m_Player.LocalTakeToDst( il_src, il_dst );
        }
        item.DeleteSafe();
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), CargoBase::GetItem(), CargoBase::GetItemCount(), ActionData::m_MainItem, ActionData::m_Player, and RF_DEFAULT.