DayzKode: JsonFileLoader< Class T > Class Reference
JsonFileLoader< Class T > Class Reference
Static Private Member Functions
static void JsonLoadData (string string_data, out T data)
static void JsonLoadFile (string filename, out T data)
static string JsonMakeData (T data)
static void JsonSaveFile (string filename, T data)
Static Private Attributes
static protected ref JsonSerializer m_Serializer = new JsonSerializer
Detailed Description
Definition at line 1 of file jsonfileloader.c.
Member Function Documentation
JsonLoadData()
static void JsonFileLoader< Class T >::JsonLoadData (string string_data, out T data) inline static private
Definition at line 50 of file jsonfileloader.c.
    {
        string error;
        if( !m_Serializer )
            m_Serializer = new JsonSerializer;
        if( !m_Serializer.ReadFromString( data, string_data, error ) )
            Error( error );
    }
References Error().
JsonLoadFile()
static void JsonFileLoader< Class T >::JsonLoadFile (string filename, out T data) inline static private
Definition at line 5 of file jsonfileloader.c.
    {
        if( FileExist( filename ) )
        {
            string file_content;
            string line_content;
            string error;
            FileHandle handle = OpenFile( filename, FileMode.READ );
            if ( handle == 0 )
                return;
            while ( FGets( handle,  line_content ) >= 0 )
            {
                file_content += line_content;
            }
            CloseFile( handle );
            if( !m_Serializer )
                m_Serializer = new JsonSerializer;
            if( !m_Serializer.ReadFromString( data, file_content, error ) )
                Error( error );
        }
    }
References CloseFile(), Error(), FGets(), FileExist(), and OpenFile().
JsonMakeData()
static string JsonFileLoader< Class T >::JsonMakeData (T data) inline static private
Definition at line 60 of file jsonfileloader.c.
    {
        string string_data;
        if( !m_Serializer )
            m_Serializer = new JsonSerializer;
        m_Serializer.WriteToString( data, true, string_data );
        return string_data;
    }
References JsonSerializer::WriteToString().
JsonSaveFile()
static void JsonFileLoader< Class T >::JsonSaveFile (string filename, T data) inline static private
Definition at line 33 of file jsonfileloader.c.
    {
        string file_content;
        if( !m_Serializer )
            m_Serializer = new JsonSerializer;
        m_Serializer.WriteToString( data, true, file_content );
        FileHandle handle = OpenFile( filename, FileMode.WRITE );
        if ( handle == 0 )
            return;
        FPrint( handle, file_content );
        CloseFile( handle );
    }
References CloseFile(), FPrint(), OpenFile(), and JsonSerializer::WriteToString().
Member Data Documentation
m_Serializer
protected ref JsonSerializer JsonFileLoader< Class T >::m_Serializer = new JsonSerializer static private
Definition at line 3 of file jsonfileloader.c.