DayzKode: ClaymoreMine Class Reference
ClaymoreMine Class Reference
Private Member Functions
override void AfterStoreLoad ()
override bool CanBeDisarmed ()
override bool CanPutInCargo (EntityAI parent)
override bool CanPutIntoHands (EntityAI parent)
override bool CanRemoveFromHands (EntityAI parent)
void ClaymoreMine ()
override void EEDelete (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EEKilled (Object killer)
override void EOnInit (IEntity other, int extra)
override EntityAI GetPairDevice ()
override RemotelyActivatedItemBehaviour GetRemotelyActivatedItemBehaviour ()
override int GetViewIndex ()
override protected void InitiateExplosion ()
override bool IsDeployable ()
override bool IsTakeable ()
override void OnActivatedByItem (notnull ItemBase item)
override void OnArmed ()
override void OnDisarmed (bool pWithTool)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnVariablesSynchronized ()
override void PairRemote (notnull EntityAI trigger)
override void SetActions ()
override void UnpairRemote ()
protected void UpdateLED (ERemoteDetonatorLEDState pState, bool pForced=false)
protected void UpdateVisuals ()
Private Attributes
protected const string ANIM_PHASE_DEPLOYED = "Mine"
protected const string ANIM_PHASE_PACKED = "Bag"
protected ERemoteDetonatorLEDState m_LastLEDState
protected ref RemotelyActivatedItemBehaviour m_RAIB
protected const string SELECTION_NAME_LED = "LED"
Detailed Description
Definition at line 1 of file claymoremine.c.
Constructor & Destructor Documentation
ClaymoreMine()
void ClaymoreMine::ClaymoreMine () inline private
Definition at line 10 of file claymoremine.c.
    {
        m_RAIB = new RemotelyActivatedItemBehaviour(this);
        SetAmmoTypes({"ClaymoreMine_Ammo","ClaymoreMine_Secondary_Ammo"});
        SetParticleExplosion(ParticleList.CLAYMORE_EXPLOSION);
        SetParticleOrientation("90 0 0");
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdLow");
        RegisterNetSyncVariableInt("m_RAIB.m_PairDeviceNetIdHigh");
        UpdateLED(ERemoteDetonatorLEDState.OFF, true);
    }
References ParticleList::CLAYMORE_EXPLOSION, m_RAIB, SetAmmoTypes(), SetParticleExplosion(), SetParticleOrientation(), and UpdateLED().
Member Function Documentation
AfterStoreLoad()
override void ClaymoreMine::AfterStoreLoad () inline private
Definition at line 61 of file claymoremine.c.
    {
        super.AfterStoreLoad();
        UpdateVisuals();
        if (GetArmed())
        {
            UpdateLED(ERemoteDetonatorLEDState.LIT, true);
        }
    }
References GetArmed(), UpdateLED(), and UpdateVisuals().
CanBeDisarmed()
override bool ClaymoreMine::CanBeDisarmed () inline private
Definition at line 144 of file claymoremine.c.
    {
        return GetArmed();
    }
References GetArmed().
CanPutInCargo()
override bool ClaymoreMine::CanPutInCargo (EntityAI parent) inline private
Definition at line 94 of file claymoremine.c.
    {
        if (!super.CanPutInCargo(parent))
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanPutIntoHands()
override bool ClaymoreMine::CanPutIntoHands (EntityAI parent) inline private
Definition at line 104 of file claymoremine.c.
    {
        if (!super.CanPutIntoHands(parent))
        {
            return false;
        }
        return IsTakeable();
    }
References IsTakeable().
CanRemoveFromHands()
override bool ClaymoreMine::CanRemoveFromHands (EntityAI parent) inline private
Definition at line 114 of file claymoremine.c.
    {
        return IsTakeable();
    }
References IsTakeable().
EEDelete()
override void ClaymoreMine::EEDelete (EntityAI parent) inline private
Definition at line 40 of file claymoremine.c.
    {
        super.EEDelete(parent);
#ifdef DEVELOPER
#ifndef SERVER
        RemoveDebugVisuals();
#endif
#endif
    }
EEItemLocationChanged()
override void ClaymoreMine::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 84 of file claymoremine.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        if (m_RAIB)
        {
            m_RAIB.Pair();
        }
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
EEKilled()
override void ClaymoreMine::EEKilled (Object killer) inline private
Definition at line 29 of file claymoremine.c.
    {
        super.EEKilled(killer);
#ifdef DEVELOPER
#ifndef SERVER
        RemoveDebugVisuals();
#endif
#endif
    }
EOnInit()
override void ClaymoreMine::EOnInit (IEntity other, int extra) inline private
Definition at line 24 of file claymoremine.c.
    {
        UpdateVisuals();
    }
References UpdateVisuals().
GetPairDevice()
override EntityAI ClaymoreMine::GetPairDevice () inline private
Definition at line 139 of file claymoremine.c.
    {
        return m_RAIB.GetPairDevice();
    }
References RemotelyActivatedItemBehaviour::GetPairDevice(), and m_RAIB.
Referenced by OnActivatedByItem(), and UnpairRemote().
GetRemotelyActivatedItemBehaviour()
override RemotelyActivatedItemBehaviour ClaymoreMine::GetRemotelyActivatedItemBehaviour () inline private
Definition at line 119 of file claymoremine.c.
    {
        return m_RAIB;
    }
References m_RAIB.
GetViewIndex()
override int ClaymoreMine::GetViewIndex () inline private
Definition at line 275 of file claymoremine.c.
    {
        if (MemoryPointExists("invView2"))
        {
            if (GetArmed())
            {
                return 1;
            }
        }
        return 0;
    }
References GetArmed(), and MemoryPointExists().
InitiateExplosion()
override protected void ClaymoreMine::InitiateExplosion () inline private
Definition at line 51 of file claymoremine.c.
    {
        if (GetDefused())
        {
            return;
        }
        super.InitiateExplosion();
    }
References GetDefused().
IsDeployable()
override bool ClaymoreMine::IsDeployable () inline private
Definition at line 261 of file claymoremine.c.
    {
        return true;
    }
IsTakeable()
override bool ClaymoreMine::IsTakeable () inline private
Definition at line 256 of file claymoremine.c.
    {
        return !GetArmed();
    }
References GetArmed().
Referenced by CanPutInCargo(), CanPutIntoHands(), and CanRemoveFromHands().
OnActivatedByItem()
override void ClaymoreMine::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 149 of file claymoremine.c.
    {
        if (GetGame().IsServer())
        {
            if (m_RAIB.IsPaired() && GetArmed())
            {
                if (GetPairDevice() == item)
                {
                    SetHealth("", "", 0.0);
                }
            }
        }
    }
References GetArmed(), GetGame(), GetPairDevice(), RemotelyActivatedItemBehaviour::IsPaired(), m_RAIB, and SetHealth().
OnArmed()
override void ClaymoreMine::OnArmed () inline private
Definition at line 163 of file claymoremine.c.
    {
        super.OnArmed();
        UpdateVisuals();
        UpdateLED(ERemoteDetonatorLEDState.LIT, true);
#ifdef DEVELOPER
#ifndef SERVER
        // have to call this function a little later, after claymore transform has been finalized
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(DrawDamageZone, 500);
#endif
#endif
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), UpdateLED(), and UpdateVisuals().
OnDisarmed()
override void ClaymoreMine::OnDisarmed (bool pWithTool) inline private
Definition at line 178 of file claymoremine.c.
    {
        super.OnDisarmed(pWithTool);
#ifdef DEVELOPER
        RemoveDebugVisuals();
#endif
        SetDefused(pWithTool);
        UnpairRemote();
        if (pWithTool)
        {
            SetHealth("", "", 0.0);
        }
        UpdateVisuals();
        UpdateLED(ERemoteDetonatorLEDState.OFF, true);
    }
References SetDefused(), SetHealth(), UnpairRemote(), UpdateLED(), and UpdateVisuals().
OnPlacementComplete()
override void ClaymoreMine::OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0") inline private
Definition at line 198 of file claymoremine.c.
    {
        super.OnPlacementComplete(player, position, orientation);
        if (GetGame().IsServer())
        {
            RemoteDetonatorTrigger rdt = RemoteDetonatorTrigger.SpawnInPlayerHands(player);
            if (rdt)
            {
                rdt.SetControlledDevice(this);
                PairRemote(rdt);
                Arm();
            }
        }
    }
References Arm(), GetGame(), PairRemote(), RemoteDetonatorTrigger::SetControlledDevice(), and RemoteDetonatorTrigger::SpawnInPlayerHands().
OnVariablesSynchronized()
override void ClaymoreMine::OnVariablesSynchronized () inline private
Definition at line 72 of file claymoremine.c.
    {
        super.OnVariablesSynchronized();
        if (m_RAIB)
        {
            m_RAIB.OnVariableSynchronized();
        }
        UpdateVisuals();
    }
References m_RAIB, RemotelyActivatedItemBehaviour::OnVariableSynchronized(), and UpdateVisuals().
PairRemote()
override void ClaymoreMine::PairRemote (notnull EntityAI trigger) inline private
Definition at line 124 of file claymoremine.c.
    {
        m_RAIB.Pair(trigger);
    }
References m_RAIB, and RemotelyActivatedItemBehaviour::Pair().
Referenced by OnPlacementComplete().
SetActions()
override void ClaymoreMine::SetActions () inline private
Definition at line 266 of file claymoremine.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
        AddAction(ActionArmExplosive);
    }
References ActionDeployObject(), and AddAction().
UnpairRemote()
override void ClaymoreMine::UnpairRemote () inline private
Definition at line 129 of file claymoremine.c.
    {
        if (GetPairDevice())
        {
            GetPairDevice().UnpairRemote();
        }
        m_RAIB.Unpair();
    }
References GetPairDevice(), m_RAIB, and RemotelyActivatedItemBehaviour::Unpair().
Referenced by OnDisarmed().
UpdateLED()
protected void ClaymoreMine::UpdateLED (ERemoteDetonatorLEDState pState, bool pForced = false) inline private
Definition at line 236 of file claymoremine.c.
    {
        if (pState != m_LastLEDState || pForced)
        {
            int selectionIdx = GetHiddenSelectionIndex(SELECTION_NAME_LED);
            switch (pState)
            {
            case ERemoteDetonatorLEDState.LIT:
                SetObjectTexture(selectionIdx, RemoteDetonator.COLOR_LED_LIT);
            break;
            default:
                SetObjectTexture(selectionIdx, RemoteDetonator.COLOR_LED_OFF);
                break;
            }
            m_LastLEDState = pState;
        }
    }
References m_LastLEDState, and SELECTION_NAME_LED.
Referenced by AfterStoreLoad(), ClaymoreMine(), OnArmed(), and OnDisarmed().
UpdateVisuals()
protected void ClaymoreMine::UpdateVisuals () inline private
Definition at line 214 of file claymoremine.c.
    {
        if (GetArmed() || GetDefused())
        {
            ShowSelection(ANIM_PHASE_DEPLOYED);
            HideSelection(ANIM_PHASE_PACKED);
            if (GetOnViewIndexChanged())
            {
                GetOnViewIndexChanged().Invoke();
            }
        }
        else
        {
            HideSelection(ANIM_PHASE_DEPLOYED);
            ShowSelection(ANIM_PHASE_PACKED);
            if (GetOnViewIndexChanged())
            {
                GetOnViewIndexChanged().Invoke();
            }
        }
    }
References ANIM_PHASE_DEPLOYED, ANIM_PHASE_PACKED, GetArmed(), and GetDefused().
Referenced by AfterStoreLoad(), EOnInit(), OnArmed(), OnDisarmed(), and OnVariablesSynchronized().
Member Data Documentation
ANIM_PHASE_DEPLOYED
protected const string ClaymoreMine::ANIM_PHASE_DEPLOYED = "Mine" private
Definition at line 4 of file claymoremine.c.
Referenced by UpdateVisuals().
ANIM_PHASE_PACKED
protected const string ClaymoreMine::ANIM_PHASE_PACKED = "Bag" private
Definition at line 3 of file claymoremine.c.
Referenced by UpdateVisuals().
m_LastLEDState
protected ERemoteDetonatorLEDState ClaymoreMine::m_LastLEDState private
Definition at line 8 of file claymoremine.c.
Referenced by UpdateLED().
m_RAIB
protected ref RemotelyActivatedItemBehaviour ClaymoreMine::m_RAIB private
Definition at line 7 of file claymoremine.c.
Referenced by ClaymoreMine(), EEItemLocationChanged(), GetPairDevice(), GetRemotelyActivatedItemBehaviour(), OnActivatedByItem(), OnVariablesSynchronized(), PairRemote(), and UnpairRemote().
SELECTION_NAME_LED
protected const string ClaymoreMine::SELECTION_NAME_LED = "LED" private
Definition at line 5 of file claymoremine.c.
Referenced by UpdateLED().