DayzKode: BloodRegenMdfr Class Reference
BloodRegenMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
float GetRegenModifierEnergy (float energy)
float GetRegenModifierWater (float water)
override void Init ()
override void OnActivate (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Detailed Description
Definition at line 1 of file bloodregen.c.
Member Function Documentation
ActivateCondition()
override bool BloodRegenMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 11 of file bloodregen.c.
    {
        float m_MaxBlood = player.GetMaxHealth("GlobalHealth", "Blood");
        if ( player.GetHealth("GlobalHealth", "Blood") <= m_MaxBlood )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
DeactivateCondition()
override bool BloodRegenMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 29 of file bloodregen.c.
    {
        float m_MaxBlood = player.GetMaxHealth("GlobalHealth", "Blood");
        if ( player.GetHealth("GlobalHealth", "Blood") >= m_MaxBlood )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
GetRegenModifierEnergy()
float BloodRegenMdfr::GetRegenModifierEnergy (float energy) inline private
Definition at line 71 of file bloodregen.c.
    {
        float modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_ENERGY_HIGH;
        int energy_level = m_Player.GetStatLevelEnergy();
        //if( energy < PlayerConstants.BLOOD_REGEN_THRESHOLD_ENERGY_MID ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_ENERGY_MID}
        //if( energy < PlayerConstants.BLOOD_REGEN_THRESHOLD_ENERGY_LOW ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_ENERGY_LOW}
        if( energy_level == EStatLevels.MEDIUM ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_ENERGY_MID}
        if( energy_level >= EStatLevels.LOW ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_ENERGY_LOW}
        return modifier;
    }
References PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_HIGH, PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_LOW, PlayerConstants::BLOOD_REGEN_MODIFIER_ENERGY_MID, and m_Player.
Referenced by OnTick().
GetRegenModifierWater()
float BloodRegenMdfr::GetRegenModifierWater (float water) inline private
Definition at line 55 of file bloodregen.c.
    {
        float modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_WATER_HIGH;
        int water_level = m_Player.GetStatLevelWater();
        /*
        if( water < PlayerConstants.BLOOD_REGEN_THRESHOLD_WATER_MID ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_WATER_MID}
        if( water < PlayerConstants.BLOOD_REGEN_THRESHOLD_WATER_LOW ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_WATER_LOW}
        */
        if( water_level == EStatLevels.MEDIUM ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_WATER_MID}
        if( water_level >= EStatLevels.LOW ) {modifier = PlayerConstants.BLOOD_REGEN_MODIFIER_WATER_LOW}
        return modifier;
    }
References PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_HIGH, PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_LOW, PlayerConstants::BLOOD_REGEN_MODIFIER_WATER_MID, and m_Player.
Referenced by OnTick().
Init()
override void BloodRegenMdfr::Init () inline private
Definition at line 3 of file bloodregen.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_BLOOD_REGEN;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = DEFAULT_TICK_TIME_ACTIVE;
    }
References DEFAULT_TICK_TIME_ACTIVE, DEFAULT_TICK_TIME_INACTIVE, m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void BloodRegenMdfr::OnActivate (PlayerBase player) inline private
Definition at line 24 of file bloodregen.c.
    {
    }
OnTick()
override void BloodRegenMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 42 of file bloodregen.c.
    {
        float regen_modifier_water = GetRegenModifierWater( player.GetStatWater().Get() );
        float regen_modifier_energy = GetRegenModifierEnergy( player.GetStatEnergy().Get() );
        float blood_regen_speed = PlayerConstants.BLOOD_REGEN_RATE_PER_SEC * regen_modifier_water * regen_modifier_energy;
        /*
        PrintString("regen_modifier_water" + regen_modifier_water);
        PrintString("regen_modifier_energy" + regen_modifier_energy);
        PrintString("blood_regen_speed" + blood_regen_speed);
        */
        player.AddHealth("","Blood", blood_regen_speed * deltaT );
    }
References PlayerConstants::BLOOD_REGEN_RATE_PER_SEC, GetRegenModifierEnergy(), and GetRegenModifierWater().