DayzKode: PPERequestParamDataBase Class Reference
PPERequestParamDataBase Class Reference
Data for one material parameter, requester side.
Private Member Functions
int GetInteractionMask ()
int GetMaterialID ()
int GetParameterID ()
int GetPriorityLayer ()
int GetRequesterIDX ()
bool GetUpdatingDataValues ()
int GetVarType ()
void InitValues ()
override void InitValues ()
bool IsDataActive ()
bool IsSettingDefaultValues ()
void PPERequestParamDataBase (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET)
void PPERequestParamDataColor (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
void PPERequestParamDataInt (int requester_idx, int mat_id, int param_id, int data_type=0, int priority=0, int mask=PPOperators.SET, bool relative=false)
void SetDataActive (bool state)
void SetInteractionMask (int mask)
void SetPriorityLayer (int priority)
void SetSettingDefaultValues (bool state)
void SetUpdatingDataValues (bool state)
Private Attributes
ref array< float > m_ColorCurrent
ref array< float > m_ColorFormerTarget
ref array< float > m_ColorLast
ref array< float > m_ColorStart
ref array< float > m_ColorTarget
int m_IntCurrent
protected int m_InteractionMask
int m_IntLast
int m_IntTarget
protected bool m_IsActive
protected int m_MaterialID
protected int m_ParameterID
protected int m_Priority
PPERequesterBase m_Requester
protected int m_RequesterIDX
protected bool m_SettingDefaultValues
protected bool m_UpdatingDataValues
protected int m_VariableType
Detailed Description
Data for one material parameter, requester side.
Definition at line 2 of file pperequestdata.c.
Constructor & Destructor Documentation
PPERequestParamDataBase()
void PPERequestParamDataBase::PPERequestParamDataBase (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET) inline private
Definition at line 16 of file pperequestdata.c.
    {
        m_RequesterIDX = requester_idx;
        m_MaterialID = mat_id;
        m_ParameterID = param_id;
        m_VariableType = data_type;
        m_Priority = priority;
        m_InteractionMask = mask;
        m_UpdatingDataValues = false;
        m_SettingDefaultValues = false;
        m_IsActive = false;
        InitValues();
    }
References InitValues(), m_InteractionMask, m_IsActive, m_MaterialID, m_ParameterID, m_Priority, m_RequesterIDX, m_SettingDefaultValues, m_UpdatingDataValues, and m_VariableType.
Member Function Documentation
GetInteractionMask()
int PPERequestParamDataBase::GetInteractionMask () inline private
Definition at line 89 of file pperequestdata.c.
    {
        return m_InteractionMask;
    }
References m_InteractionMask.
GetMaterialID()
int PPERequestParamDataBase::GetMaterialID () inline private
Definition at line 69 of file pperequestdata.c.
    {
        return m_MaterialID;
    }
References m_MaterialID.
Referenced by SendMaterialValueData(), and PPERequesterBase::SetDefaultValuesAll().
GetParameterID()
int PPERequestParamDataBase::GetParameterID () inline private
Definition at line 74 of file pperequestdata.c.
    {
        return m_ParameterID;
    }
References m_ParameterID.
Referenced by PPEClassBase::InsertParamValueData(), SendMaterialValueData(), and PPERequesterBase::SetDefaultValuesAll().
GetPriorityLayer()
int PPERequestParamDataBase::GetPriorityLayer () inline private
Definition at line 99 of file pperequestdata.c.
    {
        return m_Priority;
    }
References m_Priority.
GetRequesterIDX()
int PPERequestParamDataBase::GetRequesterIDX () inline private
Definition at line 64 of file pperequestdata.c.
    {
        return m_RequesterIDX;
    }
References m_RequesterIDX.
Referenced by PPEClassBase::InsertParamValueData(), and PPEMatClassParameterCommandData::InsertRequestData().
GetUpdatingDataValues()
bool PPERequestParamDataBase::GetUpdatingDataValues () inline private
Definition at line 39 of file pperequestdata.c.
    {
        return m_UpdatingDataValues;
    }
References m_UpdatingDataValues.
GetVarType()
int PPERequestParamDataBase::GetVarType () inline private
Definition at line 79 of file pperequestdata.c.
    {
        return m_VariableType;
    }
References m_VariableType.
Referenced by PPERequesterBase::SetDefaultValuesAll().
InitValues() [1/2]
void PPERequestParamDataBase::InitValues () inline private
Definition at line 30 of file pperequestdata.c.
    {
    }
Referenced by PPERequestParamDataBase().
InitValues() [2/2]
override void PPERequestParamDataBase::InitValues () inline private
Definition at line 171 of file pperequestdata.c.
    {
        m_ColorTarget = {0.0,0.0,0.0,0.0};
        m_ColorCurrent = {0,0.0,0.0,0.0};
        m_ColorLast = {0.0,0.0,0.0,0.0};
        m_ColorFormerTarget = {0.0,0.0,0.0,0.0};
        m_ColorStart = {0.0,0.0,0.0,0.0};
    }
IsDataActive()
bool PPERequestParamDataBase::IsDataActive () inline private
Definition at line 49 of file pperequestdata.c.
    {
        return m_IsActive;
    }
References m_IsActive.
Referenced by PPERequesterBase::SetDefaultValuesAll().
IsSettingDefaultValues()
bool PPERequestParamDataBase::IsSettingDefaultValues () inline private
Definition at line 59 of file pperequestdata.c.
    {
        return m_SettingDefaultValues;
    }
References m_SettingDefaultValues.
PPERequestParamDataColor()
void PPERequestParamDataBase::PPERequestParamDataColor (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false) inline private
Definition at line 166 of file pperequestdata.c.
    {
        m_VariableType = PPEConstants.VAR_TYPE_COLOR;
    }
PPERequestParamDataInt()
void PPERequestParamDataBase::PPERequestParamDataInt (int requester_idx, int mat_id, int param_id, int data_type = 0, int priority = 0, int mask = PPOperators.SET, bool relative = false) inline private
Definition at line 125 of file pperequestdata.c.
    {
        m_IntCurrent = -1;
        m_IntLast = -1;
        m_VariableType = PPEConstants.VAR_TYPE_INT;
    }
SetDataActive()
void PPERequestParamDataBase::SetDataActive (bool state) inline private
Definition at line 44 of file pperequestdata.c.
    {
        m_IsActive = state;
    }
References m_IsActive.
Referenced by PPEClassBase::InsertParamValueData().
SetInteractionMask()
void PPERequestParamDataBase::SetInteractionMask (int mask) inline private
Definition at line 84 of file pperequestdata.c.
    {
        m_InteractionMask = mask;
    }
References m_InteractionMask.
SetPriorityLayer()
void PPERequestParamDataBase::SetPriorityLayer (int priority) inline private
Definition at line 94 of file pperequestdata.c.
    {
        m_Priority = priority;
    }
References m_Priority.
SetSettingDefaultValues()
void PPERequestParamDataBase::SetSettingDefaultValues (bool state) inline private
Definition at line 54 of file pperequestdata.c.
    {
        m_SettingDefaultValues = state;
    }
References m_SettingDefaultValues.
SetUpdatingDataValues()
void PPERequestParamDataBase::SetUpdatingDataValues (bool state) inline private
Definition at line 34 of file pperequestdata.c.
    {
        m_UpdatingDataValues = state;
    }
References m_UpdatingDataValues.
Referenced by PPEClassBase::InsertParamValueData().
Member Data Documentation
m_ColorCurrent
ref array<float> PPERequestParamDataBase::m_ColorCurrent private
Definition at line 160 of file pperequestdata.c.
m_ColorFormerTarget
ref array<float> PPERequestParamDataBase::m_ColorFormerTarget private
Definition at line 163 of file pperequestdata.c.
m_ColorLast
ref array<float> PPERequestParamDataBase::m_ColorLast private
Definition at line 161 of file pperequestdata.c.
m_ColorStart
ref array<float> PPERequestParamDataBase::m_ColorStart private
Definition at line 164 of file pperequestdata.c.
m_ColorTarget
ref array<float> PPERequestParamDataBase::m_ColorTarget private
Definition at line 159 of file pperequestdata.c.
m_IntCurrent
int PPERequestParamDataBase::m_IntCurrent private
Definition at line 122 of file pperequestdata.c.
m_InteractionMask
protected int PPERequestParamDataBase::m_InteractionMask private
Definition at line 13 of file pperequestdata.c.
Referenced by GetInteractionMask(), PPERequestParamDataBase(), and SetInteractionMask().
m_IntLast
int PPERequestParamDataBase::m_IntLast private
Definition at line 123 of file pperequestdata.c.
m_IntTarget
int PPERequestParamDataBase::m_IntTarget private
Definition at line 121 of file pperequestdata.c.
m_IsActive
protected bool PPERequestParamDataBase::m_IsActive private
Definition at line 6 of file pperequestdata.c.
Referenced by IsDataActive(), PPERequestParamDataBase(), and SetDataActive().
m_MaterialID
protected int PPERequestParamDataBase::m_MaterialID private
Definition at line 9 of file pperequestdata.c.
Referenced by GetMaterialID(), and PPERequestParamDataBase().
m_ParameterID
protected int PPERequestParamDataBase::m_ParameterID private
Definition at line 10 of file pperequestdata.c.
Referenced by GetParameterID(), and PPERequestParamDataBase().
m_Priority
protected int PPERequestParamDataBase::m_Priority private
Definition at line 14 of file pperequestdata.c.
Referenced by GetPriorityLayer(), PPERequestParamDataBase(), and SetPriorityLayer().
m_Requester
PPERequesterBase PPERequestParamDataBase::m_Requester private
Definition at line 4 of file pperequestdata.c.
Referenced by PPERequesterBase::GetRequestData().
m_RequesterIDX
protected int PPERequestParamDataBase::m_RequesterIDX private
Definition at line 12 of file pperequestdata.c.
Referenced by GetRequesterIDX(), and PPERequestParamDataBase().
m_SettingDefaultValues
protected bool PPERequestParamDataBase::m_SettingDefaultValues private
Definition at line 7 of file pperequestdata.c.
Referenced by IsSettingDefaultValues(), PPERequestParamDataBase(), and SetSettingDefaultValues().
m_UpdatingDataValues
protected bool PPERequestParamDataBase::m_UpdatingDataValues private
Definition at line 5 of file pperequestdata.c.
Referenced by GetUpdatingDataValues(), PPERequestParamDataBase(), and SetUpdatingDataValues().
m_VariableType
protected int PPERequestParamDataBase::m_VariableType private
Definition at line 11 of file pperequestdata.c.
Referenced by GetVarType(), and PPERequestParamDataBase().