DayzKode: WeaponStateBase Class Reference
WeaponStateBase Class Reference
represent weapon state base
Private Member Functions
void AddTransition (WeaponTransition t)
adds transition into m_fsm transition table
void AttachNewMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
void DetachOldMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
bool FindNextFreeMuzzle (int currentMuzzle, out int nextMuzzle)
WeaponFSM GetFSM ()
int GetInternalStateID ()
WeaponStateBase GetParentState ()
bool HasFSM ()
bool IsBoltOpen ()
bool IsIdle ()
idle state does not expect any animation events
override bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
override bool LoadCurrentFSMState (ParamsReadContext ctx, int version)
void LoopedChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
void LoopedChamberingEjectLast (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
override void OnAbort (WeaponEventBase e)
void OnAbort (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
destination of the cartridge
override void OnEntry (WeaponEventBase e)
destination of the cartridge
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnEntry (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
override void OnExit (WeaponEventBase e)
void OnStateChanged (WeaponStateBase src, WeaponStateBase dst)
called on current state when state machine has changed its state
void OnSubMachineChanged (WeaponStateBase src, WeaponStateBase dst)
called when sub-machine has changed its state
override void OnUpdate (float dt)
override void OnUpdate (float dt)
void OnUpdate (float dt)
bool ProcessEvent (WeaponEventBase e)
void RemoveNewMagazineFromInventory (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
void RifleChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void RifleEjectCasing (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void RifleReChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
source of the cartridge
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
bool SaveCurrentFSMState (ParamsWriteContext ctx)
override bool SaveCurrentFSMState (ParamsWriteContext ctx)
void SetInternalStateID (int i)
void SetParentState (WeaponStateBase parent)
allows construction of hierarchical state machine
void WeaponAttachMagazine (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponChamberFromAttMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
void WeaponChamberFromAttMagOnExit (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
void WeaponChamberFromInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int action=-1, int actionType=-1)
void WeaponChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponCharging (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponChargingInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponChargingMultiple (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponDetachingMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponEjectAllMuzzles (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
void WeaponEjectBullet (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponEjectCasing (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
void WeaponEjectCasingMultiMuzzle (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
void WeaponFireAndChamberNext (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponFireAndChamberNextFromInnerMag (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponFireLast (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponMagnumChambering (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int startActionType=-1, int endActionType=-1)
void WeaponRechamber (Weapon_Base w=NULL, WeaponStateBase parent=NULL, int actionEject=-1, int actionTypeEject=-1, int actionLoad=-1, int actionTypeLoad=-1)
void WeaponReplacingMagAndChamberNext (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
void WeaponStartAction (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
specific action sub-type
void WeaponStateBase (Weapon_Base w=NULL, WeaponStateBase parent=NULL)
internal state id used for load/restore
void WeaponUnjamming (Weapon_Base w=NULL, WeaponStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
Private Attributes
WeaponActions m_action
int m_actionEject
int m_actionLoad
int m_actionType
action to be played
int m_actionTypeEject
int m_actionTypeLoad
ref AttachNewMagazine m_attach
ref AttachNewMagazine_W4T m_attach
ref WeaponChambering_Cartridge m_chamber
ref WeaponChamberFromAttMag_W4T m_chamber
ref WeaponChambering_Base m_chamber
ref WeaponChamberFromInnerMag_W4T m_chamber
ref WeaponChamberFromInnerMag_W4T m_chamberFromInnerMag
float m_damage
ref DetachOldMagazine m_detach
ref InventoryLocation m_dst
magazine that will be detached
Magazine m_dstMagazine
float m_dtAccumulator
ref WeaponEjectBullet m_eje
source of the loaded cartridge
ref WeaponEjectCasing m_eject
ref WeaponEjectBullet_Cartridge m_eject
ref WeaponEjectAllMuzzles m_eject
ref WeaponEjectBullet_Cartridge_W4T m_eject
ref WeaponUnjamming_Cartridge_W4T m_eject
int m_endActionType
ref WeaponStartAction m_endLoop
ref WeaponFire m_fire
ref WeaponFireWithEject m_fire
ref WeaponFSM m_fsm
hierarchical parent state of this state (or null)
ref BulletHide_W4T m_hideB
ref MagazineHide_W4T m_hideM
ref OldMagazineHide m_hideOld
int m_InternalID = -1
nested state machine (or null)
float m_jamTime
ref WeaponChambering m_loa
Magazine m_magazine
string m_magazineType
ref InventoryLocation m_newDst
magazine that will be detached
Magazine m_newMagazine
magazine that will be detached
ref InventoryLocation m_newSrc
magazine that will be removed from inventory
Magazine m_oldMagazine
ref WeaponEjectBullet_Cartridge_W4T m_onBE
ref WeaponEjectCasing_W4T m_onBEFireOut
ref WeaponCharging_CK m_onCK
WeaponStateBase m_parentState
weapon that this state relates to
ref WeaponCylinderRotate m_rotate
Magazine m_srcMagazine
destination of the ejected cartridge
ref InventoryLocation m_srcMagazinePrevLocation
source of the cartridge
ref WeaponStateBase m_start
source of the cartridge
ref WeaponStartAction m_start
ref WeaponCharging_Start m_start
ref WeaponEjectBullet_Start m_start
destination of the cartridge
ref WeaponUnjamming_Start m_start
int m_startActionType
ref WeaponDetachingMag_Store m_store
ref SwapOldAndNewMagazine m_swapMags
string m_type
ref LoopedChambering_Wait4ShowBullet2 m_w4sb2
ref WeaponChambering_W4T m_w4t
ref WeaponUnjamming_W4T m_w4t
Weapon_Base m_weapon
Detailed Description
represent weapon state base
Class comes with entry/update/abort/exit hooks that can be overriden in custom states
Class is ready for hierarchic composition, i.e. this state having a sub-machine running under hood. If no m_fsm member is configured, class acts as ordinary plain finite machine state.
Definition at line 1 of file bullethide.c.
Constructor & Destructor Documentation
WeaponStateBase()
void WeaponStateBase::WeaponStateBase (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
internal state id used for load/restore
Definition at line 17 of file weaponstatebase.c.
{ m_weapon = w; m_parentState = parent; }
References m_parentState, and m_weapon.
Member Function Documentation
AddTransition()
WeaponStateBase::AddTransition (WeaponTransition t) inline private
adds transition into m_fsm transition table
Definition at line 89 of file weaponstatebase.c.
    {
        if (HasFSM())
            m_fsm.AddTransition(t);
        else
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " adding transition to state without FSM. Configure FSM first.");
    }
References Error(), HasFSM(), m_fsm, and m_weapon.
AttachNewMagazine()
void WeaponStateBase::AttachNewMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 219 of file weaponreplacingmagandchambernext.c.
    {
        m_newMagazine = NULL;
        m_newDst = NULL;
    }
DetachOldMagazine()
void WeaponStateBase::DetachOldMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 10 of file weaponreplacingmagandchambernext.c.
    {
        m_oldMagazine = NULL;
        m_newDst = NULL;
    }
References m_oldMagazine.
FindNextFreeMuzzle()
bool WeaponStateBase::FindNextFreeMuzzle (int currentMuzzle, out int nextMuzzle) inline private
Definition at line 879 of file weaponchambering.c.
    {
        nextMuzzle = currentMuzzle;
        int nMuzzles = m_weapon.GetMuzzleCount();
        for (int i = 0; i < nMuzzles; ++i)
        {
            --nextMuzzle;
            nextMuzzle = Math.WrapInt(nextMuzzle, 0, nMuzzles);
            if (m_weapon.IsChamberEmpty(nextMuzzle))
                return true;
        }
        return false;
    }
References m_weapon, and Math::WrapInt().
Referenced by OnEntry().
GetFSM()
WeaponFSM WeaponStateBase::GetFSM () inline private
Definition at line 29 of file weaponstatebase.c.
{ return m_fsm; }
References m_fsm.
GetInternalStateID()
int WeaponStateBase::GetInternalStateID () inline private
Definition at line 32 of file weaponstatebase.c.
{ return m_InternalID; }
References m_InternalID.
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::FindStateForInternalID(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::GetInternalStateID(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), and HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SetInternalID().
GetParentState()
WeaponStateBase::GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
Definition at line 26 of file weaponstatebase.c.
{ return m_parentState; }
References m_parentState.
HasFSM()
bool WeaponStateBase::HasFSM () inline private
Definition at line 28 of file weaponstatebase.c.
{ return m_fsm != NULL; }
References m_fsm.
Referenced by AddTransition(), IsWaitingForActionFinish(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnUpdate(), ProcessEvent(), and SaveCurrentFSMState().
IsBoltOpen()
WeaponStateBase::IsBoltOpen () inline private
Returns
true if weapon bolt is open
Definition at line 163 of file weaponstatebase.c.
{ return false; }
Referenced by WeaponParticlesBase::CheckBoltStateCondition().
IsIdle()
WeaponStateBase::IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Definition at line 158 of file weaponstatebase.c.
{ return false; }
Referenced by LoadCurrentFSMState(), and SaveCurrentFSMState().
IsWaitingForActionFinish() [1/9]
WeaponStateBase::IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state or active substate is waiting for finish signal
Definition at line 364 of file weaponchambering.c.
{ return true; }
IsWaitingForActionFinish() [2/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 9 of file weaponchamberinglooped.c.
{ return false; }
IsWaitingForActionFinish() [3/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 66 of file weaponcharging.c.
{ return true; }
IsWaitingForActionFinish() [4/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 45 of file weaponejectcasingandchamberfromattmag.c.
    {
        return false;
    }
IsWaitingForActionFinish() [5/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 117 of file weaponejectcasingandchamberfromattmag.c.
    {
        return false;
    }
IsWaitingForActionFinish() [6/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 225 of file weaponreplacingmagandchambernext.c.
    {
        return true;
    }
IsWaitingForActionFinish() [7/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 328 of file weaponreplacingmagandchambernext.c.
{ return true; }
IsWaitingForActionFinish() [8/9]
bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 152 of file weaponstatebase.c.
{ return HasFSM() && m_fsm.IsRunning() && m_fsm.GetCurrentState().IsWaitingForActionFinish(); }
References HasFSM(), and m_fsm.
IsWaitingForActionFinish() [9/9]
override bool WeaponStateBase::IsWaitingForActionFinish () inline private
Definition at line 161 of file weaponunjamming.c.
{ return true; }
LoadCurrentFSMState() [1/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 87 of file riflechambering.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RifleChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [2/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 106 of file riflerechambering.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber.LoadCurrentFSMState: cannot read m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [3/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 82 of file weaponattachmagazine.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory.LoadCurrentFSMState: cannot read m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_newSrc, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory.LoadCurrentFSMState: cannot read m_newSrc for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [4/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 55 of file weaponchambering.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_damage))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_damage for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_type))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_type for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_magazineType))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_magazineType for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [5/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 586 of file weaponchambering.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [6/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 1165 of file weaponchambering.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering.LoadCurrentFSMState: cannot read m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [7/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 250 of file weaponchamberinglooped.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering.LoadCurrentFSMState: cannot read m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [8/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 510 of file weaponchamberinglooped.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast.LoadCurrentFSMState: cannot read m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [9/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 110 of file weaponcharging.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet_Cartridge.LoadCurrentFSMState: cannot read m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [10/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 170 of file weaponcharging.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet_Cartridge.LoadCurrentFSMState: cannot read m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [11/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 77 of file weapondetachingmag.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_magazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store.LoadCurrentFSMState: cannot read m_magazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_dst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store.LoadCurrentFSMState: cannot read m_dst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_dst, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [12/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 183 of file weapondetachingmag.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_magazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag.LoadCurrentFSMState: cannot read m_magazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_dst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag.LoadCurrentFSMState: cannot read m_dst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_dst, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [13/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 125 of file weaponejectbullet.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet.LoadCurrentFSMState: cannot read m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Read().
LoadCurrentFSMState() [14/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 88 of file weaponrechamber.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.LoadCurrentFSMState: cannot read m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [15/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 86 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_oldMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.LoadCurrentFSMState: cannot read m_oldMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.LoadCurrentFSMState: cannot read m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_oldMagazine, m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [16/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 191 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine.LoadCurrentFSMState: cannot read m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine.LoadCurrentFSMState: cannot read m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [17/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 307 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine.LoadCurrentFSMState: cannot read m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationReadFromContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine.LoadCurrentFSMState: cannot read m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationReadFromContext(), and Serializer::Read().
LoadCurrentFSMState() [18/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 571 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.LoadCurrentFSMState: cannot read m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_oldMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.LoadCurrentFSMState: cannot read m_oldMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!m_newDst.ReadFromContext(ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.LoadCurrentFSMState: cannot read m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_oldMagazine, m_weapon, and Serializer::Read().
LoadCurrentFSMState() [19/20]
bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 54 of file weaponstatebase.c.
    {
        if (HasFSM())
        {
            if (IsIdle())
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::LoadCurrentFSMState - idle state, skipping other substates"); }
                if (m_fsm.LoadCurrentFSMState(ctx, version))
                    return true;
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::LoadCurrentFSMState - Cannot load stable state for weapon=" + this);
            }
            else
            {
                // if parent state is !idle (unstable) then load whole machine
                if (LogManager.IsWeaponLogEnable()) { wpnDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::LoadCurrentFSMState - NOT idle state, loading full submachine state"); }
                if (m_fsm.LoadCurrentUnstableFSMState(ctx, version))
                    return true;
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::LoadCurrentFSMState - Cannot load unstable state for weapon=" + this);
            }
            return false;
        }
        return true;
    }
References Error(), HasFSM(), IsIdle(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugSpam().
LoadCurrentFSMState() [20/20]
override bool WeaponStateBase::LoadCurrentFSMState (ParamsReadContext ctx, int version) inline private
Definition at line 134 of file weaponunjamming.c.
    {
        if (!super.LoadCurrentFSMState(ctx, version))
            return false;
        if (!ctx.Read(m_damage))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponUnjamming_Cartridge.LoadCurrentFSMState: cannot read m_damage for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Read(m_type))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponUnjamming_Cartridge.LoadCurrentFSMState: cannot read m_type for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Read().
LoopedChambering()
void WeaponStateBase::LoopedChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 27 of file weaponchamberinglooped.c.
    {
        m_action = action;
        m_startActionType = startActionType;
        m_endActionType = endActionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_startActionType);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        m_chamber = new WeaponChambering_Cartridge_ChambToMag(m_weapon, this);
        m_w4sb2 = LoopedChambering_Wait4ShowBullet2(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_endLoop = new LoopedChambering_EndLoop(m_weapon, this, m_action, m_endActionType); // @NOTE: termination playing action - dummy?
        // events
        WeaponEventBase                         _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventContinuousLoadBulletStart    __lS_ = new WeaponEventContinuousLoadBulletStart;
        WeaponEventContinuousLoadBulletEnd      __lE_ = new WeaponEventContinuousLoadBulletEnd;
        WeaponEventAnimBulletShow               __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletHide               __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventAnimBulletEject              __be_ = new WeaponEventAnimBulletEject;
        WeaponEventAnimBulletInMagazine         __bM_ = new WeaponEventAnimBulletInMagazine;
        WeaponEventAnimBulletShow2              _bs2_ = new WeaponEventAnimBulletShow2;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start,   __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_start,   __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_eject,   __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_w4sb2, NULL, new GuardAnd(new GuardAnd(new WeaponGuardHasAmmoInLoopedState(m_chamber), new WeaponGuardChamberHasRoomForMoreThanOne(m_weapon)),new WeaponGuardWeaponManagerWantContinue())));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_endLoop));
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(m_hideB,   __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_endLoop, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_hideB,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, and m_weapon.
LoopedChamberingEjectLast()
void WeaponStateBase::LoopedChamberingEjectLast (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 286 of file weaponchamberinglooped.c.
    {
        m_action = action;
        m_startActionType = startActionType;
        m_endActionType = endActionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_startActionType);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        m_chamber = new WeaponChambering_Cartridge_InnerMag(m_weapon, this);
        m_w4sb2 = new LoopedChambering_Wait4ShowBullet2(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_chamberFromInnerMag = new WeaponChamberFromInnerMag_W4T(m_weapon, this);
        m_endLoop = new LoopedChambering_EndLoop(m_weapon, this, m_action, m_endActionType); // @NOTE: termination playing action - dummy?
        // events
        WeaponEventBase                         _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventContinuousLoadBulletStart    __lS_ = new WeaponEventContinuousLoadBulletStart;
        WeaponEventContinuousLoadBulletEnd      __lE_ = new WeaponEventContinuousLoadBulletEnd;
        WeaponEventAnimCocked                   __wc_ = new WeaponEventAnimCocked;
        WeaponEventAnimBulletShow               __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletHide               __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventAnimBulletEject              __be_ = new WeaponEventAnimBulletEject;
        WeaponEventAnimBulletInMagazine         __bM_ = new WeaponEventAnimBulletInMagazine;
        WeaponEventAnimBulletShow2              _bs2_ = new WeaponEventAnimBulletShow2;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start  , __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_w4sb2, NULL, new GuardAnd(new GuardAnd(new WeaponGuardHasAmmoInLoopedState(m_chamber), new WeaponGuardChamberHasRoomForMoreThanOne(m_weapon)),new WeaponGuardWeaponManagerWantContinue())));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_endLoop));
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(m_hideB,   __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_endLoop, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_endLoop,             __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_eject,               __wc_, m_chamberFromInnerMag));
        m_fsm.AddTransition(new WeaponTransition(m_chamberFromInnerMag, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_hideB,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, and m_weapon.
OnAbort() [1/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 62 of file riflechambering.c.
    {
        super.OnAbort(e);
        m_srcMagazine = NULL;
    }
References m_srcMagazine.
OnAbort() [2/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 74 of file riflerechambering.c.
    {
        super.OnAbort(e);
        m_srcMagazine = NULL;
        m_dstMagazine = NULL;
    }
References m_srcMagazine.
OnAbort() [3/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 46 of file weaponattachmagazine.c.
    {
        m_newMagazine = NULL;
        m_newSrc = NULL;
        super.OnAbort(e);
    }
OnAbort() [4/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 190 of file weaponattachmagazine.c.
    {
        EntityAI leftHandItem = e.m_player.GetInventory().FindAttachment(InventorySlots.LEFTHAND);
        Magazine mag = Magazine.Cast(leftHandItem);
        if(mag)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( mag , null );
            InventoryLocation il = new InventoryLocation;
            e.m_player.GetInventory().FindFreeLocationFor( mag, FindInventoryLocationType.CARGO, il );
            if(!il || !il.IsValid())
            {
                if (DayZPlayerUtils.HandleDropMagazine(e.m_player, mag))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, ok - no inventory space for old magazine - dropped to ground"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, error - cannot drop magazine from left hand after not found inventory space for old magazine");
            }
            else
            {
                InventoryLocation oldSrc = new InventoryLocation;
                mag.GetInventory().GetCurrentInventoryLocation(oldSrc);
                if (GameInventory.LocationSyncMoveEntity(oldSrc, il))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, ok - old magazine removed from wpn (LHand->inv)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, error - cannot remove old mag from wpn");
            }
        }
        super.OnAbort(e);
    }
References Error(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [5/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 447 of file weaponchambering.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(),leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - abort"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - no inventory space for ammo pile - dropped to ground - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - abort");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - ammo pile removed from left hand (LHand->inv) - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, error - cannot remove ammo pile from wpn - abort");
                    }
                }
            }
        }
        super.OnAbort(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [6/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 1085 of file weaponchambering.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if (leftHandIl.IsValid())
            {
                if (m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if (vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if ( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if ( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - abort"); }
                                done = true;
                            }
                        }
                    }
                }
                if ( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if (!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - no inventory space for ammo pile - dropped to ground - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - abort");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - ammo pile removed from left hand (LHand->inv) - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot remove ammo pile from wpn - abort");
                    }
                }
            }
        }
        super.OnAbort(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [7/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 170 of file weaponchamberinglooped.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - abort"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - no inventory space for ammo pile - dropped to ground - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - abort");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - ammo pile removed from left hand (LHand->inv) - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot remove ammo pile from wpn - abort");
                    }
                }
            }
        }
        super.OnAbort(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [8/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 431 of file weaponchamberinglooped.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - ammo pile removed from left hand to previous location (LHand->inv) - abort"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - no inventory space for ammo pile - dropped to ground - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - abort");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - ammo pile removed from left hand (LHand->inv) - abort"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, error - cannot remove ammo pile from wpn - abort");
                    }
                }
            }
        }
        super.OnAbort(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnAbort() [9/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 85 of file weaponcharging.c.
    {
        m_dstMagazine = NULL;
        super.OnAbort(e);
    }
OnAbort() [10/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 145 of file weaponcharging.c.
    {
        m_dstMagazine = NULL;
        super.OnAbort(e);
    }
OnAbort() [11/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 24 of file weapondetachingmag.c.
    {
        m_magazine = NULL;
        m_dst = NULL;
        super.OnAbort(e);
    }
References m_dst.
OnAbort() [12/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 100 of file weaponejectbullet.c.
    {
        m_dstMagazine = NULL;
        super.OnAbort(e);
    }
OnAbort() [13/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 67 of file weaponfireandchambernext.c.
    {
        m_weapon.ResetBurstCount();
        super.OnAbort(e);
    }
References m_weapon.
OnAbort() [14/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 21 of file weaponreplacingmagandchambernext.c.
    {
        super.OnAbort(e);
        m_oldMagazine = NULL;
        m_newDst = NULL;
    }
References m_oldMagazine.
OnAbort() [15/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 153 of file weaponreplacingmagandchambernext.c.
    {
        //m_weapon.HideMagazine();
        m_newMagazine = NULL;
        m_newDst = NULL;
        super.OnAbort(e);
    }
OnAbort() [16/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 260 of file weaponreplacingmagandchambernext.c.
    {
        if (m_newMagazine && m_newDst)
        {
            if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_newMagazine))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, ok - aborting, detached magazine dropped to ground"); }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, error - cannot abort detaching of magazine");
            m_weapon.HideMagazine(); // force hide on abort
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine, aborting, but attached new magazine already in place"); }
        m_newMagazine = NULL;
        m_newDst = NULL;
        super.OnAbort(e);
    }
References Error(), DayZPlayerUtils::HandleDropMagazine(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [17/18]
override void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 502 of file weaponreplacingmagandchambernext.c.
    {
        super.OnAbort(e);
        EntityAI leftHandItem = e.m_player.GetInventory().FindAttachment(InventorySlots.LEFTHAND);
        Magazine mag = Magazine.Cast(leftHandItem);
        if (mag)
        {
            if (m_newMagazine)
                e.m_player.GetInventory().ClearInventoryReservationEx( m_newMagazine , null );
            if (m_oldMagazine)
                e.m_player.GetInventory().ClearInventoryReservationEx( m_oldMagazine , null );
            InventoryLocation il = new InventoryLocation();
            e.m_player.GetInventory().FindFreeLocationFor(mag, FindInventoryLocationType.CARGO, il);
            if (!il.IsValid())
            {
                if (DayZPlayerUtils.HandleDropMagazine(e.m_player, mag))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - no inventory space for old magazine - dropped to ground - abort"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot drop magazine from left hand after not found inventory space for old magazine - abort");
            }
            else
            {
                InventoryLocation oldSrc = new InventoryLocation();
                mag.GetInventory().GetCurrentInventoryLocation(oldSrc);
                if (GameInventory.LocationSyncMoveEntity(oldSrc, il))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - old magazine removed from wpn (LHand->inv) - abort"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot remove old mag from wpn - abort");
            }
        }
    }
References Error(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnAbort() [18/18]
void WeaponStateBase::OnAbort (WeaponEventBase e) inline private
Definition at line 129 of file weaponstatebase.c.
    {
        if (HasFSM() && m_fsm.IsRunning())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " OnAbort " + this.Type().ToString() + "  Has Sub-FSM! Aborting submachine..."); }
            m_fsm.Abort(e);
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } ABORTED " + this.Type().ToString()); }
    }
References HasFSM(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugPrint().
OnEntry() [1/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file bullethide.c.
    {
        super.OnEntry(e);
        if(e)
            m_weapon.SelectionBulletHide();
    }
References m_weapon.
OnEntry() [2/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file bulletshow.c.
    {
        super.OnEntry(e);
        if(e)
            m_weapon.ShowBullet(0);
    }
References m_weapon.
OnEntry() [3/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 18 of file bulletshow.c.
    {
        super.OnEntry(e);
        if(e)
            m_weapon.ShowBullet(1);
    }
References m_weapon.
OnEntry() [4/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file magazinehide.c.
    {
        super.OnEntry(e);
        //m_weapon.HideMagazine();
    }
OnEntry() [5/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 3 of file magazineshow.c.
    {
        super.OnEntry(e);
        if (e)
            m_weapon.ShowMagazine();
    }
References m_weapon.
OnEntry() [6/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 42 of file riflechambering.c.
    {
        if (e != NULL)
        {
            if (e.m_magazine != NULL)
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RifleChambering, taking mag from event e.mag=" + e.m_magazine.ToString()); }
                m_srcMagazine = e.m_magazine;
                m_chamber.m_srcMagazine = m_srcMagazine;
            }
        }
        else
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RifleChambering (e=NULL), m_srcMagazine=" + m_srcMagazine.ToString()); }
        }
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " m_srcMagazine=" + m_srcMagazine.ToString()); }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, m_srcMagazine, m_srcMagazine, m_weapon, and wpnDebugPrint().
OnEntry() [7/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 43 of file riflerechambering.c.
    {
        if (e)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber, mag=" + e.m_magazine.ToString()); }
            m_srcMagazine = e.m_magazine;
            m_chamber.m_srcMagazine = m_srcMagazine;
            // prepare magazine for ejected ammo
            int mi = m_weapon.GetCurrentMuzzle();
            string magazineTypeName = m_weapon.GetChamberedCartridgeMagazineTypeName(mi);
            float damage = 0.0;
            string type;
            if (m_weapon.GetCartridgeInfo(mi, damage, type))
            {
                bool is_single_or_server = !GetGame().IsMultiplayer() || GetGame().IsServer();
                if (is_single_or_server)
                {
                    m_dstMagazine = DayZPlayerUtils.SelectStoreCartridge(e.m_player, m_weapon, mi, m_srcMagazine, damage, magazineTypeName);
                    if (!m_dstMagazine)
                    {
                        Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + "   WeaponRechamber - error, cannot prepare mag for catridge, magType=" + magazineTypeName);
                    }
                }
            }
            m_eject.m_dstMagazine = m_dstMagazine;
        }
        super.OnEntry(e); // @NOTE: super after submachine init (prevent override from submachine start)
    }
References Error(), GetGame(), CGame::IsMultiplayer(), CGame::IsServer(), LogManager::IsWeaponLogEnable(), m_chamber, m_dstMagazine, m_eject, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_weapon, DayZPlayerUtils::SelectStoreCartridge(), and wpnDebugPrint().
OnEntry() [8/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 12 of file weaponattachmagazine.c.
    {
        if(e)
        {
            if (!m_newSrc.IsValid())
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory m_newSrc=invalid, item not in bubble?");
            if (m_newMagazine && m_newSrc && m_newSrc.IsValid())
            {
                InventoryLocation curr = new InventoryLocation;
                m_newMagazine.GetInventory().GetCurrentInventoryLocation(curr);
                if (m_newSrc.GetType() == InventoryLocationType.GROUND && curr.GetType() == InventoryLocationType.ATTACHMENT && curr.GetSlot() == InventorySlots.LEFTHAND)
                {
                    // already in LH
                }
                else
                {
                    InventoryLocation lhand = new InventoryLocation;
                    lhand.SetAttachment(e.m_player, m_newMagazine, InventorySlots.LEFTHAND);
                    if (GameInventory.LocationSyncMoveEntity(m_newSrc, lhand))
                    {
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory, ok - new magazine removed from inv (inv->LHand)"); }
                    }
                    else
                        Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory, error - cannot new remove mag from inv");
                }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory, error - no magazines configured for replace (m_old=m_new=NULL)");
        }
        super.OnEntry(e);
    }
References Error(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [9/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 163 of file weaponattachmagazine.c.
    {
        if (e)
        {
            Magazine mag = e.m_magazine;
            InventoryLocation newSrc = new InventoryLocation;
            mag.GetInventory().GetCurrentInventoryLocation(newSrc);
            // move to LH
            InventoryLocation lhand = new InventoryLocation;
            lhand.SetAttachment(e.m_player, mag, InventorySlots.LEFTHAND);
            if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, ok - new magazine removed from inv (inv->LHand)"); }
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponAttachMagazine, error - cannot new remove mag from inv");
            InventoryLocation il = new InventoryLocation;
            il.SetAttachment(m_weapon, mag, InventorySlots.MAGAZINE);
            m_attach.m_newMagazine = mag;
            m_attach.m_newDst = il;
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [10/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 8 of file weaponchamberfromattmag.c.
    {
        super.OnEntry(e);
        if(e)
        {
            int mi = m_weapon.GetCurrentMuzzle();
            pushToChamberFromAttachedMagazine(m_weapon, mi);
        }
    }
References m_weapon, and pushToChamberFromAttachedMagazine().
OnEntry() [11/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 29 of file weaponchamberfromattmag.c.
    {
        super.OnEntry(e);
        if (e)
        {
            int mi = m_weapon.GetCurrentMuzzle();
            pushToChamberFromInnerMagazine(m_weapon, mi);
        }
    }
References m_weapon, and pushToChamberFromInnerMagazine().
OnEntry() [12/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 410 of file weaponchambering.c.
    {
        if (e != NULL)
        {
            m_srcMagazine = e.m_magazine;
            if (m_srcMagazine != NULL)
            {
                InventoryLocation newSrc = new InventoryLocation;
                m_srcMagazine.GetInventory().GetCurrentInventoryLocation(newSrc);
                m_srcMagazinePrevLocation = newSrc;
                // move to LH
                InventoryLocation lhand = new InventoryLocation;
                lhand.SetAttachment(e.m_player, m_srcMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - ammo pile removed from inv (inv->LHand)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, error - cannot remove ammo pile from inv");
                m_chamber.m_srcMagazine = m_srcMagazine;
            }
            else
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering m_srcMagazine = NULL"); }
            }
        }
        else
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering (e=NULL), m_srcMagazine=" + m_srcMagazine.ToString()); }
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [13/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 895 of file weaponchambering.c.
    {
        int nextMuzzle;
        if (FindNextFreeMuzzle(m_weapon.GetCurrentMuzzle(), nextMuzzle))
        {
            Magnum_Base magnum = Magnum_Base.Cast(m_weapon);
            magnum.SetCylinderRotationAnimationPhase(magnum.GetCylinderRotation(nextMuzzle));
            m_weapon.SetCurrentMuzzle(nextMuzzle);
        }
        else
        {
            Print("WTF");
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References FindNextFreeMuzzle(), m_weapon, and Print().
OnEntry() [14/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 987 of file weaponchambering.c.
    {
        if (e != NULL)
        {
            m_srcMagazine = e.m_magazine;
            if (m_srcMagazine != NULL)
            {
                InventoryLocation newSrc = new InventoryLocation;
                m_srcMagazine.GetInventory().GetCurrentInventoryLocation(newSrc);
                m_srcMagazinePrevLocation = newSrc;
                // move to LH
                InventoryLocation lhand = new InventoryLocation;
                lhand.SetAttachment(e.m_player, m_srcMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - ammo pile removed from inv (inv->LHand)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, error - cannot remove ammo pile from inv");
                m_chamber.m_srcMagazine = m_srcMagazine;
            }
            else
            {
                Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering m_srcMagazine = NULL");
            }
        }
        else
        {
            Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering (e=NULL), m_srcMagazine=" + m_srcMagazine.ToString());
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [15/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 73 of file weaponchamberinglooped.c.
    {
        if (e != NULL)
        {
            m_srcMagazine = e.m_magazine;
            if (m_srcMagazine != NULL)
            {
                m_weapon.SelectionBulletHide();
                InventoryLocation newSrc = new InventoryLocation;
                m_srcMagazine.GetInventory().GetCurrentInventoryLocation(newSrc);
                m_srcMagazinePrevLocation = newSrc;
                // move to LH
                InventoryLocation lhand = new InventoryLocation;
                lhand.SetAttachment(e.m_player, m_srcMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - ammo pile removed from inv (inv->LHand)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot remove ammo pile from inv");
                m_chamber.m_srcMagazine = m_srcMagazine;
            }
            else
            {
                Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering m_srcMagazine = NULL");
            }
        }
        else
        {
            Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering (e=NULL), m_srcMagazine=" + m_srcMagazine.ToString());
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [16/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 336 of file weaponchamberinglooped.c.
    {
        if (e != NULL)
        {
            m_srcMagazine = e.m_magazine;
            if (m_srcMagazine != NULL)
            {
                InventoryLocation newSrc = new InventoryLocation;
                m_srcMagazine.GetInventory().GetCurrentInventoryLocation(newSrc);
                m_srcMagazinePrevLocation = newSrc;
                // move to LH
                InventoryLocation lhand = new InventoryLocation;
                lhand.SetAttachment(e.m_player, m_srcMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - ammo pile removed from inv (inv->LHand)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, error - cannot remove ammo pile from inv");
                m_chamber.m_srcMagazine = m_srcMagazine;
            }
            else
            {
                Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast m_srcMagazine = NULL");
            }
        }
        else
        {
            Print("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast (e=NULL), m_srcMagazine=" + m_srcMagazine.ToString());
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, Print(), InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [17/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
destination of the cartridge
Definition at line 73 of file weaponcharging.c.
    {
        super.OnEntry(e);
        if(e)
        {
            DayZPlayer p = e.m_player;
            int mi = m_weapon.GetCurrentMuzzle();
            ejectBulletAndStoreInMagazine(m_weapon, mi, m_dstMagazine, p); // MP-safe
        }
    }
References ejectBulletAndStoreInMagazine(), WeaponEventBase::m_player, and m_weapon.
OnEntry() [18/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
destination of the cartridge
Definition at line 129 of file weaponcharging.c.
    {
        super.OnEntry(e);
        if(e)
        {
            DayZPlayer p = e.m_player;
            for(int i = 0; i < m_weapon.GetMuzzleCount(); i++)
            {
                m_weapon.CreateRound(i);
                ejectBulletAndStoreInMagazine(m_weapon, i, m_dstMagazine, p); // MP-safe
                m_weapon.EffectBulletHide(i);
                m_weapon.HideBullet(i);
            }
        }
    }
References ejectBulletAndStoreInMagazine(), WeaponEventBase::m_player, and m_weapon.
OnEntry() [19/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 255 of file weaponcharging.c.
    {
        super.OnEntry(e);
    }
OnEntry() [20/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 327 of file weaponcharging.c.
    {
        super.OnEntry(e);
    }
OnEntry() [21/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 11 of file weapondetachingmag.c.
    {
        //if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + "  WeaponDetachingMag_Store, Detaching mag=" + m_magazine.ToString() +  "to loc=" + InventoryLocation.DumpToStringNullSafe(m_dst)); }
        super.OnEntry(e);
        if (e)
        {
            if (!m_magazine || !m_dst)
            {
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, error - no magazine to load from (m_magazine=NULL)");
            }
        }
    }
References Error(), m_dst, and m_weapon.
OnEntry() [22/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 138 of file weapondetachingmag.c.
    {
        if (e != NULL)
        {
            WeaponEventDetachMagazine de;
            if (Class.CastTo(de, e))
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("WeaponDetachingMag type=" + typename.EnumToString(InventoryLocationType, de.m_dst.GetType())); }
                m_magazine = e.m_magazine;
                m_dst = de.m_dst;
                m_store.m_magazine = m_magazine;
                m_store.m_dst = m_dst;
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("WeaponDetachingMag type=" + typename.EnumToString(InventoryLocationType, m_store.m_dst.GetType())); }
            }
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References Class::CastTo(), LogManager::IsWeaponLogEnable(), m_dst, m_dst, WeaponEventBase::m_magazine, m_magazine, and wpnDebugPrint().
OnEntry() [23/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 85 of file weaponejectbullet.c.
    {
        if (e)
        {
            if (e.m_magazine)
                m_dstMagazine = e.m_magazine;
            m_eject.m_dstMagazine = m_dstMagazine;
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet m_mag=" + m_dstMagazine.ToString() + ", e.mag=" + e.m_magazine.ToString()); }
        }
        super.OnEntry(e); // @NOTE: super after submachine init (prevent override from submachine start)
    }
References LogManager::IsWeaponLogEnable(), m_dstMagazine, m_eject, WeaponEventBase::m_magazine, m_weapon, and wpnDebugPrint().
OnEntry() [24/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 6 of file weaponejectcasingandchamberfromattmag.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " ejected fired out casing"); }
            int mi = m_weapon.GetCurrentMuzzle();
            if(m_weapon.IsChamberFiredOut(mi))
            {
                m_weapon.EjectCasing(mi);
            }
            m_weapon.EffectBulletHide(mi);
            m_weapon.SelectionBulletHide();
        }
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnEntry() [25/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 27 of file weaponejectcasingandchamberfromattmag.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " ejected fired out casing multi muzzle"); }
            for( int i = 0; i < m_weapon.GetMuzzleCount(); i++ )
            {
                if(m_weapon.IsChamberFiredOut(i))
                {
                    m_weapon.EjectCasing(i);
                    m_weapon.EffectBulletHide(i);
                    m_weapon.HideBullet(i);
                }
            }
        }
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnEntry() [26/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 61 of file weaponejectcasingandchamberfromattmag.c.
    {
        super.OnEntry(e);
        if (e)
        {
            Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(m_weapon.GetAttachmentByType(Magnum_Cylinder));
            if(cylinder)
            {
                cylinder.HideSelection("bullet");
                cylinder.HideSelection("bullet_2");
                cylinder.HideSelection("bullet_3");
                cylinder.HideSelection("bullet_4");
                cylinder.HideSelection("bullet_5");
                cylinder.HideSelection("bullet_6");
                cylinder.HideSelection("bullet_nose");
                cylinder.HideSelection("bullet_nose_2");
                cylinder.HideSelection("bullet_nose_3");
                cylinder.HideSelection("bullet_nose_4");
                cylinder.HideSelection("bullet_nose_5");
                cylinder.HideSelection("bullet_nose_6");
            }
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " ejected bullets from all muzzles"); }
            for( int i = 0; i < m_weapon.GetMuzzleCount(); i++ )
            {
                if(m_weapon.IsChamberFiredOut(i))
                {
                    m_weapon.EjectCasing(i);
                    m_weapon.EffectBulletHide(i);
                    m_weapon.HideBullet(i);
                    continue;
                }
                if(!m_weapon.IsChamberEmpty(i))
                {
                    DayZPlayer p = e.m_player;
                    if(m_dstMagazine && m_dstMagazine.GetAmmoCount() < m_dstMagazine.GetAmmoMax() )
                    {
                        m_weapon.CreateRound(i);
                        ejectBulletAndStoreInMagazine(m_weapon,i,m_dstMagazine,p);
                    }
                    else
                    {
                        m_weapon.CreateRound(i);
                        ejectBulletAndStoreInMagazine(m_weapon,i,null,p);
                    }
                    m_weapon.EffectBulletHide(i);
                    m_weapon.HideBullet(i);
                }
            }
        }
        //m_weapon.SelectionBulletHide();
    }
References ejectBulletAndStoreInMagazine(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnEntry() [27/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file weaponfireandchambernext.c.
    {
        super.OnEntry(e);
        if (e)
            m_dtAccumulator = 0;
    }
References m_dtAccumulator.
OnEntry() [28/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file weaponfireandchambernextfrominnermag.c.
    {
        super.OnEntry(e);
        if (e)
            m_dtAccumulator = 0;
    }
References m_dtAccumulator.
OnEntry() [29/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 31 of file weaponfirelast.c.
    {
        super.OnEntry(e);
        if (e)
            m_dtAccumulator = 0;
    }
References m_dtAccumulator.
OnEntry() [30/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 35 of file weaponrechamber.c.
    {
        if (e)
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber, mag=" + e.m_magazine.ToString()); }
            m_srcMagazine = e.m_magazine;
            m_loa.m_srcMagazine = m_srcMagazine;
            // prepare magazine for ejected ammo
            int mi = m_weapon.GetCurrentMuzzle();
            string magazineTypeName = m_weapon.GetChamberedCartridgeMagazineTypeName(mi);
            float damage = 0.0;
            string type;
            if (m_weapon.GetCartridgeInfo(mi, damage, type))
            {
                m_dstMagazine = DayZPlayerUtils.SelectStoreCartridge(e.m_player, m_weapon, mi, m_srcMagazine, damage, magazineTypeName);
                if (!m_dstMagazine)
                {
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + "   WeaponRechamber - error, cannot prepare mag for catridge, magType=" + magazineTypeName);
                }
            }
            e.m_magazine = m_dstMagazine; // @NOTE: override event mag - @TODO
        }
        super.OnEntry(e); // @NOTE: super after submachine init (prevent override from submachine start)
    }
References Error(), LogManager::IsWeaponLogEnable(), m_dstMagazine, WeaponEventBase::m_magazine, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazine, m_weapon, DayZPlayerUtils::SelectStoreCartridge(), and wpnDebugPrint().
OnEntry() [31/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 16 of file weaponreplacingmagandchambernext.c.
    {
        super.OnEntry(e);
    }
OnEntry() [32/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 126 of file weaponreplacingmagandchambernext.c.
    {
        super.OnEntry(e);
        if( e )
        {
            if (!m_newMagazine || !m_newDst || !m_newDst.IsValid())
            {
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine, error - m_newMagazine(" + m_newMagazine + ") or destination(" + InventoryLocation.DumpToStringNullSafe(m_newDst) + ") is not set ");
            }
            else
            {
                e.m_player.GetInventory().ClearInventoryReservationEx( m_newMagazine , m_newDst );
                m_weapon.ShowMagazine();
                InventoryLocation lhand = new InventoryLocation();
                lhand.SetAttachment(e.m_player, m_newMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(lhand, m_newDst))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine, ok - new magazine removed from inv (LHand->Att)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine, error - cannot remove new mag from LHand");
            }
        }
    }
References InventoryLocation::DumpToStringNullSafe(), Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [33/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 230 of file weaponreplacingmagandchambernext.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (m_newMagazine && m_newDst)
            {
                InventoryLocation il = new InventoryLocation();
                if (m_newMagazine.GetInventory().GetCurrentInventoryLocation(il))
                {
                    InventoryLocation lhand = new InventoryLocation();
                    lhand.SetAttachment(e.m_player, m_newMagazine, InventorySlots.LEFTHAND);
                    if (GameInventory.LocationSyncMoveEntity(il, m_newDst))
                    {
                        m_weapon.ShowMagazine();
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine, ok - attached new magazine (LHand->dst)"); }
                    }
                    else
                    {
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine, error - cannot attach new magazine!"); }
                    }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine, error - cannot get curr location");
            }
            else
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine, error - no magazines configured for replace (m_new=NULL)");
        }
    }
References Error(), LogManager::IsWeaponLogEnable(), WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), and wpnDebugPrint().
OnEntry() [34/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 406 of file weaponreplacingmagandchambernext.c.
    {
        if (e != NULL)
        {
            WeaponEventSwapMagazine se;
            if (Class.CastTo(se, e))
            {
                int mi = m_weapon.GetCurrentMuzzle();
                m_oldMagazine = m_weapon.GetMagazine(mi);
                m_newMagazine = se.m_magazine;
                m_newDst = se.m_dst;
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponReplacingMagAndChamberNext, m_oldMagazine= " + m_oldMagazine + " m_newMagazine= " + m_newMagazine + " m_oldMagazineDst= " + typename.EnumToString(InventoryLocationType, se.m_dst.GetType())); }
                InventoryLocation oldSrc = new InventoryLocation();
                InventoryLocation newSrc = new InventoryLocation();
                if (!m_newMagazine.GetInventory().GetCurrentInventoryLocation(newSrc))
                {
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponReplacingMagAndChamberNext cannot get curr inv loc of NEW mag=" + Object.GetDebugName(m_newMagazine));
                }
                if (!m_oldMagazine.GetInventory().GetCurrentInventoryLocation(oldSrc))
                {
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponReplacingMagAndChamberNext cannot get curr inv loc of OLD mag=" + Object.GetDebugName(m_oldMagazine));
                }
                // move to LH
                InventoryLocation lhand = new InventoryLocation();
                lhand.SetAttachment(e.m_player, m_newMagazine, InventorySlots.LEFTHAND);
                if (GameInventory.LocationSyncMoveEntity(newSrc, lhand))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory, ok - new magazine removed from inv (inv->LHand)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory, error - cannot new remove mag from inv");
                m_detach.m_oldMagazine = m_oldMagazine;
                m_detach.m_newDst = m_newDst;
                m_swapMags.m_newMagazine = m_newMagazine;
                oldSrc.SetItem(m_newMagazine);
                m_swapMags.m_newDst = oldSrc;
            }
        }
        super.OnEntry(e);
    }
References Class::CastTo(), Error(), LogManager::IsWeaponLogEnable(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, InventoryLocation::SetAttachment(), InventoryLocation::SetItem(), and wpnDebugPrint().
OnEntry() [35/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 15 of file weaponstartaction.c.
    {
        super.OnEntry(e);
        if (e)
        {
            if (e.m_player)
            {
                HumanCommandWeapons hcw = e.m_player.GetCommandModifier_Weapons();
                if (hcw)
                {
                    HumanCommandAdditives ad = e.m_player.GetCommandModifier_Additives();
                    if (ad)
                        ad.CancelModifier();
                    hcw.StartAction(m_action, m_actionType);
                    if (hcw.GetRunningAction() == m_action && hcw.GetRunningActionType() == m_actionType)
                    {
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("HCW: playing A=" + typename.EnumToString(WeaponActions, m_action) + " AT=" + WeaponActionTypeToString(m_action, m_actionType) + " fini=" + hcw.IsActionFinished()); }
                    }
                    else
                        Error("HCW: NOT playing A=" + typename.EnumToString(WeaponActions, m_action) + " AT=" + WeaponActionTypeToString(m_action, m_actionType) + " fini=" + hcw.IsActionFinished());
                }
                else
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("---: remote playing A=" + typename.EnumToString(WeaponActions, m_action) + " AT=" + WeaponActionTypeToString(m_action, m_actionType)); }
            }
            else
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("---: warning, no player wants to play A=" + typename.EnumToString(WeaponActions, m_action) + " AT=" + WeaponActionTypeToString(m_action, m_actionType)); }
            }
        }
    }
References Error(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), HumanCommandAdditives(), HumanCommandWeapons::IsActionFinished(), LogManager::IsWeaponLogEnable(), m_action, WeaponEventBase::m_player, HumanCommandWeapons::StartAction(), WeaponActionTypeToString(), and wpnDebugPrint().
OnEntry() [36/38]
void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 103 of file weaponstatebase.c.
    {
        if (HasFSM() && !m_fsm.IsRunning())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { " + this.Type().ToString() + "  Has Sub-FSM! Starting submachine..."); }
            m_fsm.Start(e);
        }
        else
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " { " + this.Type().ToString()); }
    }
References HasFSM(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugPrint().
OnEntry() [37/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 77 of file weaponunjamming.c.
    {
        super.OnEntry(e);
        if (e)
        {
            m_type = string.Empty;
            float dmg;
            string type;
            m_weapon.SetJammed(false);
            int mi = m_weapon.GetCurrentMuzzle();
            if (m_weapon.IsChamberFiredOut(mi))
            {
                m_weapon.EjectCasing(mi);
                m_weapon.EffectBulletHide(mi);
                m_weapon.SelectionBulletHide();
            }
            if (!m_weapon.IsChamberEmpty(mi))
            {
                DayZPlayer p = e.m_player;
                m_weapon.CreateRound(mi);
                ejectBulletAndStoreInMagazine(m_weapon, mi, null, p);
                m_weapon.EffectBulletHide(mi);
                m_weapon.SelectionBulletHide();
            }
        }
    }
References ejectBulletAndStoreInMagazine(), string::Empty, WeaponEventBase::m_player, and m_weapon.
OnEntry() [38/38]
override void WeaponStateBase::OnEntry (WeaponEventBase e) inline private
Definition at line 212 of file weaponunjamming.c.
    {
        super.OnEntry(e);
        if (e)
        {
            m_dtAccumulator = 0.0;
            m_jamTime = 5.0; // @TODO: rand
            m_start.m_dtAccumulator = m_dtAccumulator;
            m_start.m_jamTime = m_jamTime;
        }
    }
References m_dtAccumulator, m_dtAccumulator, m_jamTime, and m_start.
OnExit() [1/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 10 of file bullethide.c.
    {
        super.OnExit(e);
    }
OnExit() [2/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 10 of file bulletshow.c.
    {
        super.OnExit(e);
    }
OnExit() [3/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 25 of file bulletshow.c.
    {
        super.OnExit(e);
    }
OnExit() [4/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 9 of file magazinehide.c.
    {
        super.OnExit(e);
    }
OnExit() [5/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 10 of file magazineshow.c.
    {
        super.OnExit(e);
    }
OnExit() [6/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 68 of file riflechambering.c.
    {
        super.OnExit(e);
        m_srcMagazine = NULL;
    }
References m_srcMagazine.
OnExit() [7/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 81 of file riflerechambering.c.
    {
        super.OnExit(e);
        m_srcMagazine = NULL;
        m_dstMagazine = NULL;
    }
References m_srcMagazine.
OnExit() [8/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 54 of file weaponattachmagazine.c.
    {
        m_weapon.ShowMagazine();
        m_newMagazine = NULL;
        m_newSrc = NULL;
        super.OnExit(e);
    }
References m_weapon.
OnExit() [9/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 17 of file weaponchamberfromattmag.c.
    {
        super.OnExit(e);
    }
OnExit() [10/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 38 of file weaponchamberfromattmag.c.
    {
        super.OnExit(e);
    }
OnExit() [11/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 50 of file weaponchamberfromattmag.c.
    {
        int mi = m_weapon.GetCurrentMuzzle();
        pushToChamberFromAttachedMagazine(m_weapon, mi);
        super.OnExit(e);
    }
References m_weapon, and pushToChamberFromAttachedMagazine().
OnExit() [12/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 507 of file weaponchambering.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - exit"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - no inventory space for ammo pile - dropped to ground - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - exit");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, ok - ammo pile removed from left hand (LHand->inv) - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering, error - cannot remove ammo pile from wpn - exit");
                    }
                }
            }
        }
        super.OnExit(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [13/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 1025 of file weaponchambering.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if (leftHandIl.IsValid())
            {
                if (m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if (vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if ( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if ( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - exit"); }
                                done = true;
                            }
                        }
                    }
                }
                if ( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if (!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - no inventory space for ammo pile - dropped to ground - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - exit");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, ok - ammo pile removed from left hand (LHand->inv) - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering, error - cannot remove ammo pile from wpn - exit");
                    }
                }
            }
        }
        super.OnExit(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [14/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 111 of file weaponchamberinglooped.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - ammo pile removed from left hand to previous location (LHand->inv) - exit"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - no inventory space for ammo pile - dropped to ground - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - exit");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, ok - ammo pile removed from left hand (LHand->inv) - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering, error - cannot remove ammo pile from wpn - exit");
                    }
                }
            }
        }
        super.OnExit(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [15/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 372 of file weaponchamberinglooped.c.
    {
        bool done = false;
        if (m_srcMagazine)
        {
            e.m_player.GetInventory().ClearInventoryReservationEx( m_srcMagazine , m_srcMagazinePrevLocation );
            InventoryLocation leftHandIl = new InventoryLocation;
            m_srcMagazine.GetInventory().GetCurrentInventoryLocation(leftHandIl);
            if(leftHandIl.IsValid())
            {
                if(m_srcMagazinePrevLocation && m_srcMagazinePrevLocation.IsValid())
                {
                    if(vector.DistanceSq(m_srcMagazinePrevLocation.GetPos(), leftHandIl.GetPos()) < WeaponManager.MAX_DROP_MAGAZINE_DISTANCE_SQ )
                    {
                        if( GameInventory.LocationCanMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                            if( GameInventory.LocationSyncMoveEntity(leftHandIl,m_srcMagazinePrevLocation) )
{
                                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - ammo pile removed from left hand to previous location (LHand->inv) - exit"); }
                                done = true;
                            }
                        }
                    }
                }
                if( !done)
                {
                    InventoryLocation il = new InventoryLocation;
                    e.m_player.GetInventory().FindFreeLocationFor( m_srcMagazine, FindInventoryLocationType.CARGO, il );
                    if(!il || !il.IsValid())
                    {
                        if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_srcMagazine))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - no inventory space for ammo pile - dropped to ground - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, error - cannot drop ammo pile from left hand after not found inventory space for ammo pile - exit");
                    }
                    else
                    {
                        if (GameInventory.LocationSyncMoveEntity(leftHandIl, il))
{
                            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, ok - ammo pile removed from left hand (LHand->inv) - exit"); }
                        }
                        else
                            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast, error - cannot remove ammo pile from wpn - exit");
                    }
                }
            }
        }
        super.OnExit(e);
        m_srcMagazine = NULL;
        m_chamber.m_srcMagazine = NULL;
        m_srcMagazinePrevLocation = NULL;
    }
References vector::DistanceSq(), Error(), InventoryLocation::GetPos(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_chamber, WeaponEventBase::m_player, m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, WeaponManager::MAX_DROP_MAGAZINE_DISTANCE_SQ, and wpnDebugPrint().
OnExit() [16/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 91 of file weaponcharging.c.
    {
        m_dstMagazine = NULL;
        super.OnExit(e);
    }
OnExit() [17/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 151 of file weaponcharging.c.
    {
        m_dstMagazine = NULL;
        super.OnExit(e);
    }
OnExit() [18/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 259 of file weaponcharging.c.
    {
        super.OnExit(e);
    }
OnExit() [19/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 331 of file weaponcharging.c.
    {
        super.OnExit(e);
    }
OnExit() [20/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 32 of file weapondetachingmag.c.
    {
        InventoryLocation il = new InventoryLocation;
        if (m_magazine.GetInventory().GetCurrentInventoryLocation(il))
        {
            if (GameInventory.LocationSyncMoveEntity(il, m_dst))
            {
                m_weapon.HideMagazine();
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, ok - magazine removed from inv (inv->dst)"); }
            }
            else
            {
                // @TODO: drop on gnd
                Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, error - cannot store detached magazine!");
            }
        }
        else
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store, error - cannot get curr location");
        }
        m_magazine = NULL;
        m_dst = NULL;
        super.OnExit(e);
    }
References Error(), LogManager::IsWeaponLogEnable(), m_dst, m_weapon, and wpnDebugPrint().
OnExit() [21/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 157 of file weapondetachingmag.c.
    {
        m_dst = NULL;
        m_magazine = NULL;
        super.OnExit(e);
    }
References m_dst.
OnExit() [22/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 106 of file weaponejectbullet.c.
    {
        m_dstMagazine = NULL;
        super.OnExit(e);
    }
OnExit() [23/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 60 of file weaponfireandchambernext.c.
    {
        //m_weapon.ResetBurstCount();
        m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [24/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 55 of file weaponfireandchambernextfrominnermag.c.
    {
        m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [25/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 38 of file weaponfirelast.c.
    {
        m_dtAccumulator = 0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [26/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 62 of file weaponrechamber.c.
    {
        super.OnExit(e);
        m_dstMagazine = NULL;
        m_eje.m_dstMagazine = NULL;
        m_loa.m_srcMagazine = NULL;
    }
OnExit() [27/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 28 of file weaponreplacingmagandchambernext.c.
    {
        if (m_oldMagazine)
        {
            InventoryLocation il = new InventoryLocation();
            e.m_player.GetInventory().FindFreeLocationFor( m_oldMagazine , FindInventoryLocationType.CARGO, il );
            if (!m_newDst || !m_newDst.IsValid() || m_newDst.GetType() == InventoryLocationType.GROUND)
            {
                if (DayZPlayerUtils.HandleDropMagazine(e.m_player, m_oldMagazine))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - no inventory space for old magazine - dropped to ground"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot drop magazine from left hand after not found inventory space for old magazine");
            }
            else
            {
                InventoryLocation oldSrc = new InventoryLocation();
                m_oldMagazine.GetInventory().GetCurrentInventoryLocation(oldSrc);
                if (GameInventory.LocationSyncMoveEntity(oldSrc, m_newDst))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - old magazine removed from wpn (LHand->inv)"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot remove old mag from wpn");
            }
        }
        m_weapon.HideMagazine();
        m_oldMagazine = NULL;
        m_newDst = null;
        super.OnExit(e);
    }
References Error(), DayZPlayerUtils::HandleDropMagazine(), LogManager::IsWeaponLogEnable(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnExit() [28/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 163 of file weaponreplacingmagandchambernext.c.
    {
        m_newMagazine = NULL;
        m_newDst = NULL;
        super.OnExit(e);
    }
OnExit() [29/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 281 of file weaponreplacingmagandchambernext.c.
    {
        m_newMagazine = NULL;
        m_newDst = NULL;
        super.OnExit(e);
    }
OnExit() [30/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 455 of file weaponreplacingmagandchambernext.c.
    {
        super.OnExit(e);
        EntityAI leftHandItem = e.m_player.GetInventory().FindAttachment(InventorySlots.LEFTHAND);
        Magazine mag = Magazine.Cast(leftHandItem);
        if(mag)
        {
            if (m_newMagazine)
                e.m_player.GetInventory().ClearInventoryReservationEx( m_newMagazine , null );
            if (m_oldMagazine)
                e.m_player.GetInventory().ClearInventoryReservationEx( m_oldMagazine , null );
            InventoryLocation il = new InventoryLocation();
            e.m_player.GetInventory().FindFreeLocationFor(mag, FindInventoryLocationType.CARGO, il);
            if (!il.IsValid())
            {
                if (DayZPlayerUtils.HandleDropMagazine(e.m_player, mag))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - no inventory space for old magazine - dropped to ground - exit"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot drop magazine from left hand after not found inventory space for old magazine - exit");
            }
            else
            {
                InventoryLocation oldSrc = new InventoryLocation();
                mag.GetInventory().GetCurrentInventoryLocation(oldSrc);
                if (GameInventory.LocationSyncMoveEntity(oldSrc, il))
                {
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, ok - old magazine removed from wpn (LHand->inv) - exit"); }
                }
                else
                    Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine, error - cannot remove old mag from wpn - exit");
            }
        }
        m_oldMagazine = NULL;
        m_newMagazine = NULL;
        m_newDst = NULL;
    }
References Error(), DayZPlayerUtils::HandleDropMagazine(), InventoryLocation::IsValid(), LogManager::IsWeaponLogEnable(), m_oldMagazine, WeaponEventBase::m_player, m_weapon, and wpnDebugPrint().
OnExit() [31/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 47 of file weaponstartaction.c.
    {
        super.OnExit(e);
    }
OnExit() [32/34]
void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 143 of file weaponstatebase.c.
    {
        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(m_weapon) + " } " + this.Type().ToString()); }
    }
References LogManager::IsWeaponLogEnable(), m_weapon, and wpnDebugPrint().
OnExit() [33/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 110 of file weaponunjamming.c.
    {
        m_type = string.Empty;
        super.OnExit(e);
    }
References string::Empty.
OnExit() [34/34]
override void WeaponStateBase::OnExit (WeaponEventBase e) inline private
Definition at line 225 of file weaponunjamming.c.
    {
        m_dtAccumulator = 0.0;
        m_jamTime = 0.0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnStateChanged()
WeaponStateBase::OnStateChanged (WeaponStateBase src, WeaponStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 177 of file weaponstatebase.c.
{ }
OnSubMachineChanged()
WeaponStateBase::OnSubMachineChanged (WeaponStateBase src, WeaponStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 170 of file weaponstatebase.c.
{ }
OnUpdate() [1/3]
override void WeaponStateBase::OnUpdate (float dt) inline private
Definition at line 38 of file weaponfireandchambernext.c.
    {
        m_dtAccumulator += dt;
        DayZPlayerImplement p;
        Class.CastTo(p, m_weapon.GetHierarchyParent());
        if( p )
        {
            HumanInputController hic = p.GetInputController();
            int muzzleIndex = m_weapon.GetCurrentMuzzle();
            float reloadTime = m_weapon.GetReloadTime(muzzleIndex);
            if ( m_dtAccumulator >= reloadTime && ( hic.IsAttackButton() || (m_weapon.GetBurstCount() < m_weapon.GetCurrentModeBurstSize(muzzleIndex))))
            {
                if (m_weapon.CanProcessWeaponEvents())
                {
                    m_weapon.ProcessWeaponEvent(new WeaponEventReloadTimeout(p));
                }
            }
        }
    }
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [2/3]
override void WeaponStateBase::OnUpdate (float dt) inline private
Definition at line 38 of file weaponfireandchambernextfrominnermag.c.
    {
        m_dtAccumulator += dt;
        DayZPlayer p;
        Class.CastTo(p, m_weapon.GetHierarchyParent());
        if( p )
        {
            HumanInputController hic = p.GetInputController();
            int muzzleIndex = m_weapon.GetCurrentMuzzle();
            float reloadTime = m_weapon.GetReloadTime(muzzleIndex);
            if ( hic.IsAttackButton() && m_dtAccumulator >= reloadTime)
                if (m_weapon.CanProcessWeaponEvents())
                    m_weapon.ProcessWeaponEvent(new WeaponEventReloadTimeout(p));
        }
    }
References Class::CastTo(), HumanInputController::IsAttackButton(), m_dtAccumulator, and m_weapon.
OnUpdate() [3/3]
void WeaponStateBase::OnUpdate (float dt) inline private
Definition at line 119 of file weaponstatebase.c.
    {
        if (HasFSM() && m_fsm.IsRunning())
            m_fsm.GetCurrentState().OnUpdate(dt);
    }
References HasFSM(), and m_fsm.
ProcessEvent()
bool WeaponStateBase::ProcessEvent (WeaponEventBase e) inline private
Definition at line 80 of file weaponstatebase.c.
    {
        if (HasFSM())
            return m_fsm.ProcessEvent(e);
        return false;
    }
References HasFSM(), and m_fsm.
RemoveNewMagazineFromInventory()
void WeaponStateBase::RemoveNewMagazineFromInventory (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 6 of file weaponattachmagazine.c.
    {
        m_newMagazine = NULL;
        m_newSrc = NULL;
    }
RifleChambering()
void WeaponStateBase::RifleChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 12 of file riflechambering.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        m_chamber = new WeaponChambering_Cartridge(m_weapon, this);
        m_w4t = new WeaponChambering_W4T(m_weapon, this);
        // events
        WeaponEventAnimBulletEject __be_ = new WeaponEventAnimBulletEject;
        WeaponEventAnimBulletShow  __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletInChamber __bc_ = new WeaponEventAnimBulletInChamber;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start  , __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bc_, m_w4t));
        m_fsm.AddTransition(new WeaponTransition(m_w4t    , _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, and m_weapon.
RifleEjectCasing()
void WeaponStateBase::RifleEjectCasing (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 10 of file rifleejectcasing.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponStartAction(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        // events
        WeaponEventBase __be_ = new WeaponEventAnimBulletEject;
        WeaponEventBase __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(m_start, __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_eject, __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(m_hideB, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_eject, m_start, and m_weapon.
RifleReChambering()
void WeaponStateBase::RifleReChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 13 of file riflerechambering.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectBullet_Cartridge(m_weapon, this);
        m_chamber = new WeaponChambering_Cartridge(m_weapon, this);
        m_w4t = new WeaponChambering_W4T(m_weapon, this);
        // events
        WeaponEventAnimBulletEject __be_ = new WeaponEventAnimBulletEject;
        WeaponEventAnimBulletShow  __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletInChamber __bc_ = new WeaponEventAnimBulletInChamber;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start  , __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bc_, m_w4t));
        m_fsm.AddTransition(new WeaponTransition(m_w4t    , _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, and m_weapon.
SaveCurrentFSMState() [1/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 74 of file riflechambering.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RifleChambering.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState().
SaveCurrentFSMState() [2/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 88 of file riflerechambering.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber.SaveCurrentFSMState: cannot save m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponRechamber.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [3/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 63 of file weaponattachmagazine.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory.SaveCurrentFSMState: cannot write m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_newSrc, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " RemoveNewMagazineFromInventory.SaveCurrentFSMState: cannot write m_newSrc for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [4/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
source of the cartridge
Definition at line 27 of file weaponchambering.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_damage))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot write m_damage for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_type))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot write m_type for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_magazineType))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot write m_magazineType for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot write m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [5/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 567 of file weaponchambering.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot write m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [6/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 1145 of file weaponchambering.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponMagnumChambering.SaveCurrentFSMState: cannot write m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [7/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 230 of file weaponchamberinglooped.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChambering.SaveCurrentFSMState: cannot write m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [8/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 491 of file weaponchamberinglooped.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_srcMagazinePrevLocation, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " LoopedChamberingEjectLast.SaveCurrentFSMState: cannot write m_srcMagazinePrevLocation for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_srcMagazinePrevLocation, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [9/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 97 of file weaponcharging.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet_Cartridge.SaveCurrentFSMState: cannot write m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [10/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 157 of file weaponcharging.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet_Cartridge.SaveCurrentFSMState: cannot write m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [11/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 58 of file weapondetachingmag.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_magazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store.SaveCurrentFSMState: cannot write m_magazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_dst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag_Store.SaveCurrentFSMState: cannot write m_st for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_dst, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [12/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 164 of file weapondetachingmag.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_magazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag.SaveCurrentFSMState: cannot write m_magazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_dst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponDetachingMag.SaveCurrentFSMState: cannot write m_st for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_dst, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [13/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 112 of file weaponejectbullet.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponEjectBullet.LoadCurrentFSMState: cannot write m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Write().
SaveCurrentFSMState() [14/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 70 of file weaponrechamber.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_dstMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot save m_dstMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_srcMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponChambering.SaveCurrentFSMState: cannot save m_srcMagazine for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_srcMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [15/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 65 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_oldMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.SaveCurrentFSMState: cannot write m_oldMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.SaveCurrentFSMState: cannot write m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_oldMagazine, m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [16/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 171 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine.SaveCurrentFSMState: cannot write m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " SwapOldAndNewMagazine.SaveCurrentFSMState: cannot write m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [17/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 288 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine.SaveCurrentFSMState: cannot write m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!OptionalLocationWriteToContext(m_newDst, ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " AttachNewMagazine.SaveCurrentFSMState: cannot write m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, OptionalLocationWriteToContext(), and Serializer::Write().
SaveCurrentFSMState() [18/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 545 of file weaponreplacingmagandchambernext.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_newMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.SaveCurrentFSMState: cannot write m_newMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_oldMagazine))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.SaveCurrentFSMState: cannot write m_oldMagazine for weapon=" + m_weapon);
            return false;
        }
        if (!m_newDst.WriteToContext(ctx))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " DetachOldMagazine.SaveCurrentFSMState: cannot write m_newDst for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_oldMagazine, m_weapon, and Serializer::Write().
SaveCurrentFSMState() [19/20]
bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 34 of file weaponstatebase.c.
    {
        if (HasFSM())
        {
            if (IsIdle())
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::SaveCurrentFSMState - idle state, skipping other substates"); }
                return m_fsm.SaveCurrentFSMState(ctx);
            }
            else
            {
                // if parent state is !idle (unstable) then save whole machine
                if (LogManager.IsWeaponLogEnable()) { wpnDebugSpam("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponStateBase::SaveCurrentFSMState - NOT idle state, saving full submachine state"); }
                return m_fsm.SaveCurrentUnstableFSMState(ctx);
            }
            return false;
        }
        return true;
    }
References HasFSM(), IsIdle(), LogManager::IsWeaponLogEnable(), m_fsm, m_weapon, and wpnDebugSpam().
SaveCurrentFSMState() [20/20]
override bool WeaponStateBase::SaveCurrentFSMState (ParamsWriteContext ctx) inline private
Definition at line 116 of file weaponunjamming.c.
    {
        if (!super.SaveCurrentFSMState(ctx))
            return false;
        if (!ctx.Write(m_damage))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponUnjamming_Cartridge.SaveCurrentFSMState: cannot write m_damage for weapon=" + m_weapon);
            return false;
        }
        if (!ctx.Write(m_type))
        {
            Error("[wpnfsm] " + Object.GetDebugName(m_weapon) + " WeaponUnjamming_Cartridge.SaveCurrentFSMState: cannot write m_type for weapon=" + m_weapon);
            return false;
        }
        return true;
    }
References Error(), m_weapon, and Serializer::Write().
SetInternalStateID()
void WeaponStateBase::SetInternalStateID (int i) inline private
Definition at line 31 of file weaponstatebase.c.
{ m_InternalID = i; }
References m_InternalID.
Referenced by HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SetInternalID().
SetParentState()
WeaponStateBase::SetParentState (WeaponStateBase parent) inline private
allows construction of hierarchical state machine
Definition at line 22 of file weaponstatebase.c.
{ m_parentState = parent; }
References m_parentState.
WeaponAttachMagazine()
void WeaponStateBase::WeaponAttachMagazine (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 125 of file weaponattachmagazine.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponStartAction(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        m_attach = new AttachNewMagazine(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        m_onCK = new WeaponCharging_CK(m_weapon, this);
        // events: MS, MA, BE, CK
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase __ms_ = new WeaponEventAnimMagazineShow;
        WeaponEventBase __so_ = new WeaponEventAnimSliderOpen;
        WeaponEventBase __ma_ = new WeaponEventAnimMagazineAttached;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(   m_start, __ms_, m_attach));
        m_fsm.AddTransition(new WeaponTransition(   m_start, __so_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(   m_eject, __ms_, m_attach));
        m_fsm.AddTransition(new WeaponTransition(  m_attach, __ck_, m_chamber, NULL, new GuardAnd(new WeaponGuardCurrentChamberEmpty(m_weapon), new WeaponGuardHasAmmo(m_weapon)))); // when opened, there is no __be_ event
        m_fsm.AddTransition(new WeaponTransition(  m_attach, __ck_, m_onCK, NULL, new GuardAnd(new WeaponGuardCurrentChamberEmpty(m_weapon), new GuardNot(new WeaponGuardHasAmmo(m_weapon)))));
        m_fsm.AddTransition(new WeaponTransition(  m_attach, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition( m_chamber, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition( m_onCK, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponChamberFromAttMag()
void WeaponStateBase::WeaponChamberFromAttMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 5 of file weaponchamberfromattmag.c.
    { }
WeaponChamberFromAttMagOnExit()
void WeaponStateBase::WeaponChamberFromAttMagOnExit (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 47 of file weaponchamberfromattmag.c.
    { }
WeaponChamberFromInnerMag()
void WeaponStateBase::WeaponChamberFromInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int action = -1, int actionType = -1) inline private
Definition at line 26 of file weaponchamberfromattmag.c.
    { }
WeaponChambering()
void WeaponStateBase::WeaponChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 379 of file weaponchambering.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_actionType);
        m_chamber = new WeaponChambering_Cartridge(m_weapon, this);
        m_w4t = new WeaponChambering_W4T(m_weapon, this);
        m_eject = new WeaponEjectCasing(m_weapon, this);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventAnimBulletInChamber __bc_ = new WeaponEventAnimBulletInChamber;
        WeaponEventAnimBulletShow  __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletEject  __be_ = new WeaponEventAnimBulletEject;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start  , __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_start  , __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bc_, m_w4t));
        m_fsm.AddTransition(new WeaponTransition(m_w4t    , _fin_, null));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, and m_weapon.
Referenced by WeaponRechamber().
WeaponCharging()
void WeaponStateBase::WeaponCharging (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 14 of file weaponcharging.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponCharging_Start(m_weapon, this, m_action, m_actionType);
        m_onCK = new WeaponCharging_CK(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        m_eject = new WeaponEjectAllMuzzles(m_weapon, this);
        // events
        WeaponEventBase __be_ = new WeaponEventAnimBulletEject;
        WeaponEventBase __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_eject ));
        m_fsm.AddTransition(new WeaponTransition(  m_start, _fin_, NULL ));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_eject, NULL, new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon))); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onCK)); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(   m_eject, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_eject, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_eject, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_onCK, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, NULL));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponChargingInnerMag()
void WeaponStateBase::WeaponChargingInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 206 of file weaponcharging.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponCharging_Start(m_weapon, this, m_action, m_actionType);
        m_onBE = new WeaponEjectBullet_Cartridge_W4T(m_weapon, this);
        m_onBEFireOut = new WeaponEjectCasing_W4T(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_onCK = new WeaponCharging_CK(m_weapon, this);
        m_chamber = new WeaponChamberFromInnerMag_W4T(m_weapon, this);
        // events
        WeaponEventBase __be_ = new WeaponEventAnimBulletEject;
        WeaponEventBase __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_onBEFireOut, NULL, new WeaponGuardCurrentChamberFiredOut(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_onBE, NULL, new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_onBE, __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(  m_onBEFireOut, __bh_, m_hideB));
        //TODO after inner magazine rework this events must load new bullet
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onBEFireOut, NULL, new GuardAnd(new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon)), new WeaponGuardCurrentChamberFiredOut(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onBE, NULL, new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_chamber, NULL, new WeaponGuardHasAmmoInnerMagazine(m_weapon))); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onCK)); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, __ck_, m_chamber, NULL, new WeaponGuardHasAmmoInnerMagazine(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, __ck_, m_chamber, NULL, new WeaponGuardHasAmmoInnerMagazine(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, __ck_, m_chamber, NULL, new WeaponGuardHasAmmoInnerMagazine(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(  m_start, _fin_, NULL ));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_onCK, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_chamber, _fin_, NULL));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_start, and m_weapon.
WeaponChargingMultiple()
void WeaponStateBase::WeaponChargingMultiple (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 281 of file weaponcharging.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponCharging_Start(m_weapon, this, m_action, m_actionType);
        m_onBE = new WeaponEjectBullet_Cartridge_W4T(m_weapon, this);
        m_onBEFireOut = new WeaponEjectCasing_W4T(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_onCK = new WeaponCharging_CK(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        // events
        WeaponEventBase __be_ = new WeaponEventAnimBulletEject;
        WeaponEventBase __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_onBEFireOut, NULL, new WeaponGuardCurrentChamberFiredOut(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_onBE, NULL, new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_onBE, __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(  m_onBEFireOut, __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onBE, NULL, new GuardNot(new WeaponGuardCurrentChamberEmpty(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon))); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(  m_start, __ck_, m_onCK)); // some anims do not send BE event
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(   m_start, _fin_, NULL ));
        m_fsm.AddTransition(new WeaponTransition(   m_onBEFireOut, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_onBE, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_hideB, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(   m_onCK, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, NULL));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponDetachingMag()
void WeaponStateBase::WeaponDetachingMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 112 of file weapondetachingmag.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponDetachingMag_1(m_weapon, this, m_action, m_actionType);
        m_store = new WeaponDetachingMag_Store(m_weapon, this);
        m_hideM = new MagazineHide_W4T(m_weapon, this);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase __md_ = new WeaponEventAnimMagazineDetached;
        WeaponEventBase __mh_ = new WeaponEventAnimMagazineHide;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start, __md_, m_store));
        m_fsm.AddTransition(new WeaponTransition(m_store, __mh_, m_hideM));
        m_fsm.AddTransition(new WeaponTransition(m_hideM, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_store  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_start, and m_weapon.
WeaponEjectAllMuzzles()
void WeaponStateBase::WeaponEjectAllMuzzles (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 59 of file weaponejectcasingandchamberfromattmag.c.
{ }
Referenced by WeaponMagnumChambering().
WeaponEjectBullet()
void WeaponStateBase::WeaponEjectBullet (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 50 of file weaponejectbullet.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponEjectBullet_Start(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectBullet_Cartridge_W4T(m_weapon, this); // @TODO: workaround for missing BH event (_W4T)
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        // events
        WeaponEventBase __be_ = new WeaponEventAnimBulletEject;
        WeaponEventBase __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(  m_start, __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(  m_eject, __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(  m_eject, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(  m_hideB, __ck_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(  m_hideB, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(  m_eject, _fin_, NULL)); // @TODO: workaround for missing BH event
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
Referenced by WeaponRechamber().
WeaponEjectCasing()
void WeaponStateBase::WeaponEjectCasing (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 4 of file weaponejectcasingandchamberfromattmag.c.
{ }
WeaponEjectCasingMultiMuzzle()
void WeaponStateBase::WeaponEjectCasingMultiMuzzle (Weapon_Base w = NULL, WeaponStateBase parent = NULL) inline private
Definition at line 25 of file weaponejectcasingandchamberfromattmag.c.
{ }
WeaponFireAndChamberNext()
void WeaponStateBase::WeaponFireAndChamberNext (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file weaponfireandchambernext.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_fire = new WeaponFireAndChamber(m_weapon, this, m_action, m_actionType);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventAnimBulletEject  __be_ = new WeaponEventAnimBulletEject;
        WeaponEventReloadTimeout __to_ = new WeaponEventReloadTimeout;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(m_fire, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_fire, __to_, NULL));
        m_fsm.SetInitialState(m_fire);
    }
References m_action, and m_weapon.
WeaponFireAndChamberNextFromInnerMag()
void WeaponStateBase::WeaponFireAndChamberNextFromInnerMag (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 9 of file weaponfireandchambernextfrominnermag.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_fire = new WeaponFireAndChamber(m_weapon, this, m_action, m_actionType);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventAnimBulletEject  __be_ = new WeaponEventAnimBulletEject;
        WeaponEventReloadTimeout __to_ = new WeaponEventReloadTimeout;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(m_fire, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_fire, __to_, NULL));
        m_fsm.SetInitialState(m_fire);
    }
References m_action, and m_weapon.
WeaponFireLast()
void WeaponStateBase::WeaponFireLast (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 10 of file weaponfirelast.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_fire = new WeaponFireWithEject(m_weapon, this, m_action, m_actionType);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventReloadTimeout __to_ = new WeaponEventReloadTimeout;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(m_fire, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_fire, __to_, NULL));
        m_fsm.SetInitialState(m_fire);
    }
References m_action, and m_weapon.
WeaponMagnumChambering()
void WeaponStateBase::WeaponMagnumChambering (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int startActionType = -1, int endActionType = -1) inline private
Definition at line 934 of file weaponchambering.c.
    {
        m_action = action;
        m_startActionType = startActionType;
        m_endActionType = endActionType;
        // setup nested state machine
        m_start = new WeaponChambering_Start(m_weapon, this, m_action, m_startActionType);
        m_eject = new WeaponEjectAllMuzzles(m_weapon, this);
        m_rotate = new WeaponCylinderRotate(m_weapon, this);
        m_chamber = new WeaponChambering_MultiMuzzleMagnum(m_weapon, this);
        m_w4sb2 = LoopedChambering_Wait4ShowBullet2(m_weapon, this);
        m_hideB = new BulletHide_W4T(m_weapon, this);
        m_endLoop = new LoopedChambering_EndLoop(m_weapon, this, m_action, m_endActionType); // @NOTE: termination playing action - dummy?
        // events
        WeaponEventBase                         _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventContinuousLoadBulletStart    __lS_ = new WeaponEventContinuousLoadBulletStart;
        WeaponEventContinuousLoadBulletEnd      __lE_ = new WeaponEventContinuousLoadBulletEnd;
        WeaponEventCylinderRotate               __cr_ = new WeaponEventCylinderRotate;
        WeaponEventAnimBulletShow               __bs_ = new WeaponEventAnimBulletShow;
        WeaponEventAnimBulletHide               __bh_ = new WeaponEventAnimBulletHide;
        WeaponEventAnimBulletEject              __be_ = new WeaponEventAnimBulletEject;
        WeaponEventAnimBulletInMagazine         __bM_ = new WeaponEventAnimBulletInMagazine;
        WeaponEventAnimBulletShow2              _bs2_ = new WeaponEventAnimBulletShow2;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_start,   __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_start,   __cr_, m_rotate));
        m_fsm.AddTransition(new WeaponTransition(m_eject,   __cr_, m_rotate));
        m_fsm.AddTransition(new WeaponTransition(m_rotate,  __be_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(m_eject, __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_rotate, __bs_, m_chamber));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_w4sb2, null, new GuardAnd(new GuardAnd(new WeaponGuardHasAmmoInLoopedState(m_chamber), new WeaponGuardChamberMultiHasRoomBulltetIgnoreLast(m_weapon)),new WeaponGuardWeaponManagerWantContinue())));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, __bM_, m_endLoop));
        //m_fsm.AddTransition(new WeaponTransition(m_rotate, __bh_, m_chamber));
        //m_fsm.AddTransition(new WeaponTransition(m_w4sb2,     __bh_, m_hideB));
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   __cr_, m_rotate));
        m_fsm.AddTransition(new WeaponTransition(m_endLoop, _fin_, null));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_w4sb2,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_rotate,  _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject  , _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start  , _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_endActionType, m_endLoop, m_start, m_startActionType, m_w4sb2, m_weapon, and WeaponEjectAllMuzzles().
WeaponRechamber()
void WeaponStateBase::WeaponRechamber (Weapon_Base w = NULL, WeaponStateBase parent = NULL, int actionEject = -1, int actionTypeEject = -1, int actionLoad = -1, int actionTypeLoad = -1) inline private
Definition at line 15 of file weaponrechamber.c.
    {
        m_actionEject = actionEject;
        m_actionTypeEject = actionTypeEject;
        m_actionLoad = actionLoad;
        m_actionTypeLoad = actionTypeLoad;
        // setup nested state machine
        m_eje = new WeaponEjectBullet(m_weapon, this, m_actionEject, m_actionTypeEject);
        m_loa = new WeaponChambering(m_weapon, this, m_actionLoad, m_actionTypeLoad);
        // events
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(m_eje, _fin_, m_loa));
        m_fsm.AddTransition(new WeaponTransition(m_loa, _fin_, NULL));
        m_fsm.SetInitialState(m_eje);
    }
References m_weapon, WeaponChambering(), and WeaponEjectBullet().
WeaponReplacingMagAndChamberNext()
void WeaponStateBase::WeaponReplacingMagAndChamberNext (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 357 of file weaponreplacingmagandchambernext.c.
    {
        m_action = action;
        m_actionType = actionType;
        m_newMagazine = NULL;
        // setup nested state machine
        m_start = new WeaponStartAction(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponEjectCasing(m_weapon,this);
        m_detach = new DetachOldMagazine(m_weapon, this);
        m_hideOld = new OldMagazineHide(m_weapon, this);
        m_swapMags = new SwapOldAndNewMagazine(m_weapon, this);
        m_attach = new AttachNewMagazine_W4T(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        m_onCK = new WeaponCharging_CK(m_weapon, this);
        // events
        WeaponEventBase __so_ = new WeaponEventAnimSliderOpen;
        WeaponEventBase __md_ = new WeaponEventAnimMagazineDetached;
        WeaponEventBase __mh_ = new WeaponEventAnimMagazineHide;
        WeaponEventBase __ms_ = new WeaponEventAnimMagazineShow;
        WeaponEventBase __ma_ = new WeaponEventAnimMagazineAttached;
        WeaponEventBase __ck_ = new WeaponEventAnimCocked;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        m_fsm.AddTransition(new WeaponTransition(   m_start, __md_, m_detach));
        m_fsm.AddTransition(new WeaponTransition(   m_start, __so_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(   m_eject, __md_, m_detach));
        m_fsm.AddTransition(new WeaponTransition(  m_detach, __mh_, m_hideOld));
        m_fsm.AddTransition(new WeaponTransition( m_hideOld, __ms_, m_swapMags));
        m_fsm.AddTransition(new WeaponTransition(m_swapMags, __ma_, m_attach));
        m_fsm.AddTransition(new WeaponTransition(  m_attach, __ck_, m_chamber, NULL, new GuardAnd(new WeaponGuardCurrentChamberEmpty(m_weapon), new WeaponGuardHasAmmo(m_weapon))));
        m_fsm.AddTransition(new WeaponTransition(  m_attach, __ck_, m_onCK));
        m_fsm.AddTransition(new WeaponTransition(  m_attach, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition( m_chamber, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(    m_onCK, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_swapMags, _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_hideOld,  _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_detach,   _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_eject,    _fin_, null));
        m_fsm.AddTransition(new WeaponTransition(m_start,    _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
WeaponStartAction()
void WeaponStateBase::WeaponStartAction (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
specific action sub-type
Definition at line 9 of file weaponstartaction.c.
    {
        m_action = action;
        m_actionType = actionType;
    }
References m_action.
WeaponUnjamming()
void WeaponStateBase::WeaponUnjamming (Weapon_Base w = NULL, WeaponStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
Definition at line 180 of file weaponunjamming.c.
    {
        m_action = action;
        m_actionType = actionType;
        // setup nested state machine
        m_start = new WeaponUnjamming_Start(m_weapon, this, m_action, m_actionType);
        m_eject = new WeaponUnjamming_Cartridge_W4T(m_weapon, this);
        m_chamber = new WeaponChamberFromAttMag_W4T(m_weapon, this);
        m_w4t = new WeaponUnjamming_W4T(m_weapon, this);
        // events
        WeaponEventBase _uto_ = new WeaponEventUnjammingTimeout;
        WeaponEventBase _fto_ = new WeaponEventUnjammingFailedTimeout;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase __uj_ = new WeaponEventAnimUnjammed;
        m_fsm = new WeaponFSM(this); // @NOTE: set owner of the submachine fsm
        // transitions
        m_fsm.AddTransition(new WeaponTransition(  m_start, _uto_, m_eject));
        m_fsm.AddTransition(new WeaponTransition(  m_start, _fto_, m_w4t));
        m_fsm.AddTransition(new WeaponTransition(  m_eject, __uj_, m_chamber, NULL, new WeaponGuardHasAmmo(m_weapon)));
        m_fsm.AddTransition(new WeaponTransition(  m_eject, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(    m_w4t, _fin_, NULL));
        m_fsm.AddTransition(new WeaponTransition(m_chamber, _fin_, NULL));
        // Safety exits
        m_fsm.AddTransition(new WeaponTransition(m_start,    _fin_, null));
        m_fsm.SetInitialState(m_start);
    }
References m_action, m_chamber, m_eject, m_start, m_weapon, and WeaponGuardHasAmmo().
Member Data Documentation
m_action
WeaponActions WeaponStateBase::m_action private
Definition at line 3 of file riflechambering.c.
m_actionEject
int WeaponStateBase::m_actionEject private
Definition at line 5 of file weaponrechamber.c.
m_actionLoad
int WeaponStateBase::m_actionLoad private
Definition at line 7 of file weaponrechamber.c.
m_actionType
int WeaponStateBase::m_actionType private
action to be played
Definition at line 4 of file riflechambering.c.
m_actionTypeEject
int WeaponStateBase::m_actionTypeEject private
Definition at line 6 of file weaponrechamber.c.
m_actionTypeLoad
int WeaponStateBase::m_actionTypeLoad private
Definition at line 8 of file weaponrechamber.c.
m_attach [1/2]
ref AttachNewMagazine WeaponStateBase::m_attach private
Definition at line 120 of file weaponattachmagazine.c.
m_attach [2/2]
ref AttachNewMagazine_W4T WeaponStateBase::m_attach private
Definition at line 347 of file weaponreplacingmagandchambernext.c.
m_chamber [1/4]
ref WeaponChamberFromAttMag_W4T WeaponStateBase::m_chamber private
Definition at line 9 of file riflechambering.c.
m_chamber [2/4]
ref WeaponChamberFromAttMag_W4T WeaponStateBase::m_chamber private
Definition at line 121 of file weaponattachmagazine.c.
m_chamber [3/4]
ref WeaponChambering_Base WeaponStateBase::m_chamber private
Definition at line 929 of file weaponchambering.c.
m_chamber [4/4]
ref WeaponChamberFromInnerMag_W4T WeaponStateBase::m_chamber private
Definition at line 204 of file weaponcharging.c.
m_chamberFromInnerMag
ref WeaponChamberFromInnerMag_W4T WeaponStateBase::m_chamberFromInnerMag private
Definition at line 284 of file weaponchamberinglooped.c.
m_damage
float WeaponStateBase::m_damage private
Definition at line 22 of file weaponchambering.c.
m_detach
ref DetachOldMagazine WeaponStateBase::m_detach private
Definition at line 344 of file weaponreplacingmagandchambernext.c.
m_dst
ref InventoryLocation WeaponStateBase::m_dst private
magazine that will be detached
detached magazine
Definition at line 9 of file weapondetachingmag.c.
Referenced by OnEntry().
m_dstMagazine
Magazine WeaponStateBase::m_dstMagazine private
Definition at line 5 of file riflerechambering.c.
Referenced by OnEntry().
m_dtAccumulator
float WeaponStateBase::m_dtAccumulator private
Definition at line 6 of file weaponfireandchambernext.c.
Referenced by OnEntry().
m_eje
ref WeaponEjectBullet WeaponStateBase::m_eje private
source of the loaded cartridge
Definition at line 12 of file weaponrechamber.c.
m_eject [1/5]
ref WeaponEjectCasing WeaponStateBase::m_eject private
Definition at line 8 of file riflechambering.c.
m_eject [2/5]
ref WeaponEjectBullet_Cartridge WeaponStateBase::m_eject private
Definition at line 9 of file riflerechambering.c.
m_eject [3/5]
ref WeaponEjectAllMuzzles WeaponStateBase::m_eject private
Definition at line 927 of file weaponchambering.c.
m_eject [4/5]
ref WeaponEjectBullet_Cartridge_W4T WeaponStateBase::m_eject private
Definition at line 46 of file weaponejectbullet.c.
m_eject [5/5]
ref WeaponUnjamming_Cartridge_W4T WeaponStateBase::m_eject private
Definition at line 176 of file weaponunjamming.c.
m_endActionType
int WeaponStateBase::m_endActionType private
Definition at line 922 of file weaponchambering.c.
m_endLoop
ref WeaponStartAction WeaponStateBase::m_endLoop private
Definition at line 931 of file weaponchambering.c.
m_fire [1/2]
ref WeaponFire WeaponStateBase::m_fire private
Definition at line 7 of file weaponfireandchambernext.c.
m_fire [2/2]
ref WeaponFireWithEject WeaponStateBase::m_fire private
Definition at line 8 of file weaponfirelast.c.
m_fsm
ref WeaponFSM WeaponStateBase::m_fsm private
hierarchical parent state of this state (or null)
Definition at line 14 of file weaponstatebase.c.
Referenced by AddTransition(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnUpdate(), ProcessEvent(), and SaveCurrentFSMState().
m_hideB
ref BulletHide_W4T WeaponStateBase::m_hideB private
Definition at line 8 of file rifleejectcasing.c.
m_hideM
ref MagazineHide_W4T WeaponStateBase::m_hideM private
Definition at line 110 of file weapondetachingmag.c.
m_hideOld
ref OldMagazineHide WeaponStateBase::m_hideOld private
Definition at line 345 of file weaponreplacingmagandchambernext.c.
m_InternalID
int WeaponStateBase::m_InternalID = -1 private
nested state machine (or null)
Definition at line 15 of file weaponstatebase.c.
Referenced by GetInternalStateID(), and SetInternalStateID().
m_jamTime
float WeaponStateBase::m_jamTime private
Definition at line 173 of file weaponunjamming.c.
Referenced by OnEntry().
m_loa
ref WeaponChambering WeaponStateBase::m_loa private
Definition at line 13 of file weaponrechamber.c.
m_magazine
Magazine WeaponStateBase::m_magazine private
Definition at line 8 of file weapondetachingmag.c.
Referenced by OnEntry().
m_magazineType
string WeaponStateBase::m_magazineType private
Definition at line 24 of file weaponchambering.c.
m_newDst
ref InventoryLocation WeaponStateBase::m_newDst private
magazine that will be detached
magazine that will be attached
new magazine from inventory that will be attached
magazine that will be dropped on abort
Definition at line 8 of file weaponreplacingmagandchambernext.c.
m_newMagazine
Magazine WeaponStateBase::m_newMagazine private
magazine that will be detached
Definition at line 3 of file weaponattachmagazine.c.
m_newSrc
ref InventoryLocation WeaponStateBase::m_newSrc private
magazine that will be removed from inventory
Definition at line 4 of file weaponattachmagazine.c.
m_oldMagazine
Magazine WeaponStateBase::m_oldMagazine private
Definition at line 7 of file weaponreplacingmagandchambernext.c.
m_onBE
ref WeaponEjectBullet_Cartridge_W4T WeaponStateBase::m_onBE private
Definition at line 200 of file weaponcharging.c.
m_onBEFireOut
ref WeaponEjectCasing_W4T WeaponStateBase::m_onBEFireOut private
Definition at line 201 of file weaponcharging.c.
m_onCK
ref WeaponCharging_CK WeaponStateBase::m_onCK private
Definition at line 122 of file weaponattachmagazine.c.
m_parentState
WeaponStateBase WeaponStateBase::m_parentState private
weapon that this state relates to
Definition at line 13 of file weaponstatebase.c.
Referenced by GetParentState(), SetParentState(), and WeaponStateBase().
m_rotate
ref WeaponCylinderRotate WeaponStateBase::m_rotate private
Definition at line 928 of file weaponchambering.c.
m_srcMagazine
Magazine WeaponStateBase::m_srcMagazine private
destination of the ejected cartridge
Definition at line 5 of file riflechambering.c.
Referenced by OnEntry().
m_srcMagazinePrevLocation
ref InventoryLocation WeaponStateBase::m_srcMagazinePrevLocation private
source of the cartridge
Definition at line 372 of file weaponchambering.c.
m_start [1/5]
ref WeaponStartAction WeaponStateBase::m_start private
source of the cartridge
detached magazine destination
source of the loaded cartridge
Definition at line 7 of file riflechambering.c.
m_start [2/5]
ref WeaponStartAction WeaponStateBase::m_start private
Definition at line 6 of file rifleejectcasing.c.
m_start [3/5]
ref WeaponCharging_Start WeaponStateBase::m_start private
Definition at line 9 of file weaponcharging.c.
m_start [4/5]
ref WeaponEjectBullet_Start WeaponStateBase::m_start private
destination of the cartridge
Definition at line 45 of file weaponejectbullet.c.
m_start [5/5]
ref WeaponUnjamming_Start WeaponStateBase::m_start private
Definition at line 175 of file weaponunjamming.c.
m_startActionType
int WeaponStateBase::m_startActionType private
Definition at line 921 of file weaponchambering.c.
m_store
ref WeaponDetachingMag_Store WeaponStateBase::m_store private
Definition at line 109 of file weapondetachingmag.c.
m_swapMags
ref SwapOldAndNewMagazine WeaponStateBase::m_swapMags private
Definition at line 346 of file weaponreplacingmagandchambernext.c.
m_type
string WeaponStateBase::m_type private
Definition at line 23 of file weaponchambering.c.
m_w4sb2
ref LoopedChambering_Wait4ShowBullet2 WeaponStateBase::m_w4sb2 private
Definition at line 930 of file weaponchambering.c.
m_w4t [1/2]
ref WeaponChambering_W4T WeaponStateBase::m_w4t private
Definition at line 10 of file riflechambering.c.
m_w4t [2/2]
ref WeaponUnjamming_W4T WeaponStateBase::m_w4t private
Definition at line 177 of file weaponunjamming.c.
m_weapon
Weapon_Base WeaponStateBase::m_weapon private
Definition at line 12 of file weaponstatebase.c.
Referenced by AddTransition(), LoadCurrentFSMState(), OnAbort(), OnEntry(), OnExit(), SaveCurrentFSMState(), and WeaponStateBase().