DayzKode: ActionSwitchSeats Class Reference
ActionSwitchSeats Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionSwitchSeats ()
override bool CanBeUsedInVehicle ()
override void CreateConditionComponents ()
override void OnUpdate (ActionData action_data)
override void Start (ActionData action_data)
Detailed Description
Definition at line 2 of file actionswitchseats.c.
Constructor & Destructor Documentation
ActionSwitchSeats()
void ActionSwitchSeats::ActionSwitchSeats () inline private
Definition at line 4 of file actionswitchseats.c.
    {
        //m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_STARTENGINE;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
        m_SpecialtyWeight = 1.0;
        m_LockTargetOnUse = false;
        m_Text = "#change_seat";
    }
References m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionSwitchSeats::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 19 of file actionswitchseats.c.
    {
        Transport trans = null;
        int nextSeatIdx = -1;
        HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
        if ( !vehCommand  )
            return false;
        int componentIndex = target.GetComponentIndex();
        if ( !target )
            return false;
        if ( !Class.CastTo(trans, target.GetObject()) )
            return false;
        nextSeatIdx = trans.CrewPositionIndex( componentIndex );
        if ( nextSeatIdx < 0 )
            return false;
        Human crew = trans.CrewMember( nextSeatIdx );
        if ( crew )
            return false;
        if ( !trans.CanReachSeatFromSeat( trans.CrewMemberIndex( player ), nextSeatIdx ) )
            return false;
        return true;
    }
References Class::CastTo().
CanBeUsedInVehicle()
override bool ActionSwitchSeats::CanBeUsedInVehicle () inline private
Definition at line 91 of file actionswitchseats.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionSwitchSeats::CreateConditionComponents () inline private
Definition at line 13 of file actionswitchseats.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTObject;
    }
References m_ConditionItem, and m_ConditionTarget.
OnUpdate()
override void ActionSwitchSeats::OnUpdate (ActionData action_data) inline private
Definition at line 78 of file actionswitchseats.c.
    {
        if(action_data.m_State == UA_START)
        {
            HumanCommandVehicle hcv = action_data.m_Player.GetCommand_Vehicle();
            if( !hcv || !action_data.m_Player.GetCommand_Vehicle().IsSwitchSeat() )
            {
                End(action_data);
            }
        }
    }
References End(), ActionData::m_Player, ActionData::m_State, and UA_START.
Start()
override void ActionSwitchSeats::Start (ActionData action_data) inline private
Definition at line 53 of file actionswitchseats.c.
    {
        super.Start( action_data );
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if ( vehCommand )
        {
            Transport trans;
            if ( Class.CastTo(trans, action_data.m_Target.GetObject()) )
            {
                int nextSeat = trans.CrewPositionIndex( action_data.m_Target.GetComponentIndex() );
                int seat = trans.GetSeatAnimationType( nextSeat );
                if ( seat >= 0 )
                {
                    //pTransportPositionIndex, int pVehicleSeat
                    vehCommand.SwitchSeat( nextSeat, seat );
                    if ( !GetGame().IsDedicatedServer() )
                    {
                        action_data.m_Player.OnVehicleSwitchSeat( nextSeat );
                    }
                }
            }
        }
    }
References Class::CastTo(), GetGame(), ActionData::m_Player, ActionData::m_Target, and HumanCommandVehicle::SwitchSeat().