DayzKode: SmptAnimMetaBase Class Reference
SmptAnimMetaBase Class Reference
Private Member Functions
override void Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player)
override EAnimPlayState Play ()
void ~SmptAnimMetaFB ()
Private Attributes
float m_Duration
int m_StanceMask
Detailed Description
Definition at line 81 of file smptanimmeta.c.
Constructor & Destructor Documentation
~SmptAnimMetaFB()
void SmptAnimMetaBase::~SmptAnimMetaFB () inline private
Definition at line 86 of file smptanimmeta.c.
    {
        if(m_Player)
            m_Player.m_isFBsymptomPlaying = false;
    }
References m_Player.
Member Function Documentation
Init()
override void SmptAnimMetaBase::Init (ParamsReadContext ctx, SymptomManager manager, PlayerBase player) inline private
Definition at line 92 of file smptanimmeta.c.
    {
        super.Init(ctx, manager, player);
        DayZPlayerSyncJunctures.ReadPlayerSymptomFBParams( ctx,  m_AnimID, m_StanceMask, m_Duration);
    }
References m_AnimID, m_Duration, m_StanceMask, and DayZPlayerSyncJunctures::ReadPlayerSymptomFBParams().
Referenced by SymptomManager::SetAnimation().
Play()
override EAnimPlayState SmptAnimMetaBase::Play () inline private
Definition at line 98 of file smptanimmeta.c.
    {
        m_Canceled = false;
        HumanCommandActionCallback callback = m_Player.GetCommand_Action();
        if (!callback)
        {
            callback = m_Player.GetCommandModifier_Action();
        }
        if( callback )
        {
            callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
            m_Canceled = true;
        }
        if(!m_Canceled)
        {
            SymptomCB anim_callback = SymptomCB.Cast(m_Player.StartCommand_Action(m_AnimID, SymptomCB, m_StanceMask));
            if(anim_callback)
            {
                anim_callback.Init(m_Duration, m_Player);
                m_IsPlaying = true;
                m_Player.m_isFBsymptomPlaying = true;
                return EAnimPlayState.OK;
            }
            else
            {
                return EAnimPlayState.FAILED;
            }
        }
        return EAnimPlayState.POSTPONED;
    }
References m_AnimID, m_Canceled, m_Duration, m_IsPlaying, m_Player, and m_StanceMask.
Referenced by PlayRequest().
Member Data Documentation
m_Duration
float SmptAnimMetaBase::m_Duration private
Definition at line 84 of file smptanimmeta.c.
m_StanceMask
int SmptAnimMetaBase::m_StanceMask private
Definition at line 83 of file smptanimmeta.c.