DayzKode: PlayerSoundEventBase Class Reference
PlayerSoundEventBase Class Reference
Private Member Functions
override bool CanPlay (PlayerBase player)
override bool CanPlay (PlayerBase player)
override bool CanPlay (PlayerBase player)
override bool CanPlay (PlayerBase player)
override bool CanPlay (PlayerBase player)
void DamageSoundEvents ()
void DrowningEvents ()
override bool HasHoldBreathException ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void HeatComfortEventsBase ()
void HoldBreathSoundEventBase ()
void InjurySoundEvents ()
void MeleeAttackSoundEvents ()
override void OnEnd ()
override void OnEnd ()
override void OnPlay (PlayerBase player)
override void OnPlay (PlayerBase player)
void StaminaSoundEventBase ()
void SymptomSoundEventBase ()
Private Attributes
const int MAX_VOLUME = 4
Detailed Description
Definition at line 1 of file damageevents.c.
Member Function Documentation
CanPlay() [1/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 10 of file damageevents.c.
    {
        return true;
    }
Referenced by PlayRequestEx().
CanPlay() [2/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 9 of file drowningevents.c.
    {
        return true;
    }
CanPlay() [3/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 10 of file injuryevents.c.
    {
        return true;
    }
CanPlay() [4/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 8 of file jumpevents.c.
    {
        if( !super.CanPlay(player) )
        {
            return false;
        }
        return true;
    }
CanPlay() [5/5]
override bool PlayerSoundEventBase::CanPlay (PlayerBase player) inline private
Definition at line 9 of file meleeattack.c.
    {
        return true;
    }
DamageSoundEvents()
void PlayerSoundEventBase::DamageSoundEvents () inline private
Definition at line 4 of file damageevents.c.
    {
        m_HasPriorityOverTypes = -1;//-1 for all
        m_Type = EPlayerSoundEventType.DAMAGE;
    }
References m_HasPriorityOverTypes, and m_Type.
DrowningEvents()
void PlayerSoundEventBase::DrowningEvents () inline private
Definition at line 3 of file drowningevents.c.
    {
        m_HasPriorityOverTypes = -1;//-1 for all
        m_Type = EPlayerSoundEventType.DROWNING;
    }
References m_HasPriorityOverTypes, and m_Type.
HasHoldBreathException()
override bool PlayerSoundEventBase::HasHoldBreathException () inline private
Definition at line 8 of file holdbreathevents.c.
    {
        return true;
    }
Referenced by CanPlay().
HasPriorityOverCurrent() [1/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file damageevents.c.
    {
        return true;
    }
Referenced by PlayRequestEx().
HasPriorityOverCurrent() [2/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file drowningevents.c.
    {
        return true;
    }
HasPriorityOverCurrent() [3/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file heatcomfortevents.c.
    {
        return true;
    }
HasPriorityOverCurrent() [4/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 15 of file injuryevents.c.
    {
        return true;
    }
HasPriorityOverCurrent() [5/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 3 of file jumpevents.c.
    {
        return true;
    }
HasPriorityOverCurrent() [6/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 14 of file meleeattack.c.
    {
        if( type_other == EPlayerSoundEventType.DAMAGE )
        {
            return false;
        }
        return true;
    }
HasPriorityOverCurrent() [7/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 10 of file staminaevents.c.
    {
        return false;
    }
HasPriorityOverCurrent() [8/8]
override bool PlayerSoundEventBase::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other) inline private
Definition at line 9 of file symptomevents.c.
    {
        return true;
    }
HeatComfortEventsBase()
void PlayerSoundEventBase::HeatComfortEventsBase () inline private
Definition at line 4 of file heatcomfortevents.c.
    {
        m_HasPriorityOverTypes = EPlayerSoundEventType.DUMMY | EPlayerSoundEventType.INJURY | EPlayerSoundEventType.STAMINA | EPlayerSoundEventType.GENERAL;//-1 for all
        m_Type = EPlayerSoundEventType.GENERAL;
    }
References m_HasPriorityOverTypes, and m_Type.
HoldBreathSoundEventBase()
void PlayerSoundEventBase::HoldBreathSoundEventBase () inline private
Definition at line 3 of file holdbreathevents.c.
    {
        m_HasPriorityOverTypes = -1;
    }
References m_HasPriorityOverTypes.
InjurySoundEvents()
void PlayerSoundEventBase::InjurySoundEvents () inline private
Definition at line 4 of file injuryevents.c.
    {
        m_HasPriorityOverTypes = -1;//-1 for all
        m_Type = EPlayerSoundEventType.INJURY;
    }
References m_HasPriorityOverTypes, and m_Type.
MeleeAttackSoundEvents()
void PlayerSoundEventBase::MeleeAttackSoundEvents () inline private
Definition at line 3 of file meleeattack.c.
    {
        m_Type = EPlayerSoundEventType.MELEE;
        m_HasPriorityOverTypes = -1;
    }
References m_HasPriorityOverTypes, and m_Type.
OnEnd() [1/2]
override void PlayerSoundEventBase::OnEnd () inline private
Definition at line 24 of file jumpevents.c.
    {
        super.OnEnd();
        //m_Player.GetStaminaSoundHandlerClient().PostponeStamina(1000);
        if(m_Player)
            StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(1300);
    }
References m_Player.
Referenced by Play(), and ~PlayerSoundEventBase().
OnEnd() [2/2]
override void PlayerSoundEventBase::OnEnd () inline private
Definition at line 23 of file meleeattack.c.
    {
        super.OnEnd();
        if(m_Player)
            StaminaSoundHandlerClient.Cast(m_Player.m_PlayerSoundManagerClient.GetHandler(eSoundHandlers.STAMINA)).PostponeStamina(800);
    }
References m_Player.
OnPlay() [1/2]
override void PlayerSoundEventBase::OnPlay (PlayerBase player) inline private
Definition at line 17 of file jumpevents.c.
    {
        super.OnPlay(player);
        if( player.CanSpawnBreathVaporEffect() )
            player.SpawnBreathVaporEffect();
    }
OnPlay() [2/2]
override void PlayerSoundEventBase::OnPlay (PlayerBase player) inline private
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 15 of file staminaevents.c.
    {
        super.OnPlay(player);
        MaskBase mask = MaskBase.Cast(player.GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("Mask")));
        float rel_volume = 1;
        if(mask)
        {
            if(mask.IsExternalFilterAttached() || mask.HasIntegratedFilter())
            {
                rel_volume = Math.Lerp(MAX_VOLUME,1,mask.GetFilterQuantity01());
            }
        }
        if(m_SoundSetCallback)
            m_SoundSetCallback.SetVolumeRelative(rel_volume);
        #ifdef DEVELOPER
        if(!PluginDiagMenu.ENABLE_BREATH_VAPOR)//disabled in debug, do not spawn particles
            return;
        #endif
        if( player.CanSpawnBreathVaporEffect() )
            player.SpawnBreathVaporEffect();
    }
References InventorySlots::GetSlotIdFromString(), Math::Lerp(), m_SoundSetCallback, MAX_VOLUME, and AbstractWave::SetVolumeRelative().
StaminaSoundEventBase()
void PlayerSoundEventBase::StaminaSoundEventBase () inline private
Definition at line 4 of file staminaevents.c.
    {
        m_Type = EPlayerSoundEventType.STAMINA;
        m_HasPriorityOverTypes = EPlayerSoundEventType.STAMINA;
    }
References m_HasPriorityOverTypes, and m_Type.
SymptomSoundEventBase()
void PlayerSoundEventBase::SymptomSoundEventBase () inline private
Definition at line 3 of file symptomevents.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
        m_HasPriorityOverTypes = -1;
    }
References m_HasPriorityOverTypes, and m_Type.
Member Data Documentation
MAX_VOLUME
const int PlayerSoundEventBase::MAX_VOLUME = 4 private
Definition at line 3 of file staminaevents.c.