DayzKode: Analytics Class Reference
Analytics Class Reference
Static Private Member Functions
static void PlayerDeath (StatsEventDeathData data)
static void PlayerDisconnected (StatsEventDisconnectedData data)
static void PlayerMeasures (StatsEventMeasuresData data)
static void PlayerScoredKill (StatsEventScoredKillData data)
static void PlayerSpawned (StatsEventSpawnedData data)
Detailed Description
Definition at line 145 of file scriptanalytics.c.
Member Function Documentation
PlayerDeath()
static void Analytics::PlayerDeath (StatsEventDeathData data) inline static private
Definition at line 148 of file scriptanalytics.c.
    {
        ScriptAnalytics.SendPlayerDeath(data);
    }
PlayerDisconnected()
static void Analytics::PlayerDisconnected (StatsEventDisconnectedData data) inline static private
Definition at line 160 of file scriptanalytics.c.
    {
        ScriptAnalytics.SendPlayerDisconnected(data);
    }
Referenced by ManBase::OnDisconnect(), and OnEvent().
PlayerMeasures()
static void Analytics::PlayerMeasures (StatsEventMeasuresData data) inline static private
Definition at line 166 of file scriptanalytics.c.
    {
        ScriptAnalytics.SendPlayerMeasures(data);
    }
Referenced by ManBase::UpdatePlayerMeasures().
PlayerScoredKill()
static void Analytics::PlayerScoredKill (StatsEventScoredKillData data) inline static private
Definition at line 154 of file scriptanalytics.c.
    {
        ScriptAnalytics.SendPlayerScoredKill(data);
    }
PlayerSpawned()
static void Analytics::PlayerSpawned (StatsEventSpawnedData data) inline static private
Definition at line 172 of file scriptanalytics.c.
    {
        ScriptAnalytics.SendPlayerSpawned(data);
    }
Referenced by OnEvent().