DayzKode: Liquid Class Reference
Liquid Class Reference
Static Private Member Functions
static bool CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check=false)
static bool CanTransfer (ItemBase source_ent, ItemBase target_ent)
static void FillContainer (ItemBase container, int liquid_type, float amount)
static void FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents=false)
static int GetAgents (int liquid_type)
static float GetDigestibility (int liquid_type)
static float GetEnergy (int liquid_type)
static float GetFlammability (int liquid_type)
static float GetFullness (int liquid_type)
static string GetLiquidClassname (int liquid_type)
static private string GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property=false)
static string GetName (int liquid_type)
static float GetNutritionalIndex (int liquid_type)
static NutritionalProfile GetNutritionalProfileByName (string class_name)
static NutritionalProfile GetNutritionalProfileByType (int liquid_type)
static float GetToxicity (int liquid_type)
static float GetWaterContent (int liquid_type)
static bool InitAllLiquids ()
static NutritionalProfile SetUpNutritionalProfile (int liquid_type, string liquid_class_name)
static void Transfer (ItemBase source_ent, ItemBase target_ent, float quantity=-1)
Static Private Attributes
static ref map< string, ref NutritionalProfile > m_AllLiquidsByName = new map<string, ref NutritionalProfile>
static ref map< int, ref NutritionalProfile > m_AllLiquidsByType = new map<int, ref NutritionalProfile>
static bool m_Init = InitAllLiquids()
Detailed Description
Definition at line 1 of file liquid.c.
Member Function Documentation
CanFillContainer()
static bool Liquid::CanFillContainer (ItemBase container, int liquid_type, bool ignore_fullness_check = false) inline static private
Definition at line 148 of file liquid.c.
    {
        if (!container)
            return false;
        bool is_container_full = container.IsFullQuantity();
        if ( is_container_full && !ignore_fullness_check)
        {
            //Debug.Log("container is full", "LiquidTransfer");
            return false;
        }
        int container_mask = container.ConfigGetFloat("liquidContainerType");
        if ( container_mask == 0 )
        {
            //Debug.Log("target is not a container", "LiquidTransfer");
            return false;//if the target liquidContainerType is set to 0
        }
        if ( (liquid_type & container_mask) == 0 )
        {
            //Debug.Log("target liquidContainerType does not support this liquid type", "LiquidTransfer");
            return false;
        }
        float container_quantity    = container.GetQuantity();
        int container_liquid_type   = container.GetLiquidType();
        if ( container_quantity > 0 && container_liquid_type != liquid_type)
        {
            //Debug.Log("target is not empty AND is of different liquid type than liquid_type added in", "LiquidTransfer");
            return false;
        }
        return true;
    }
Referenced by ActionWorldLiquidActionSwitch::ActionCondition(), CanTransfer(), FillContainer(), and ActionFillBottleBase::GetLiquidType().
CanTransfer()
static bool Liquid::CanTransfer (ItemBase source_ent, ItemBase target_ent) inline static private
Definition at line 84 of file liquid.c.
    {
        if (!source_ent || !target_ent)
            return false;
        if ( !source_ent.IsItemBase() || !target_ent.IsItemBase() )
        {
            //Debug.Log("One of the Items is not of ItemBase type", "LiquidTransfer");
            return false;
        }
        Barrel_ColorBase barrelTarget = Barrel_ColorBase.Cast(target_ent);
        Barrel_ColorBase barrelSource = Barrel_ColorBase.Cast(source_ent);
        if ((barrelTarget && !barrelTarget.IsOpen()) || (barrelSource && !barrelSource.IsOpen()))
        {
            return false;
        }
        float source_quantity = source_ent.GetQuantity();
        if ( source_quantity <= 0 )
        {
            //Debug.Log("source has no quantity", "LiquidTransfer");
            return false;//if there is nothing to transfer
        }
        int source_liquid_type  = source_ent.GetLiquidType();
        if ( source_liquid_type < 1 )
        {
            //Debug.Log("source has some quantity, but does not have a valid liquidType set, liquidType = "+ToString(source_liquid_type), "LiquidTransfer");
            return false;//if source is not a container
        }
        if ( !CanFillContainer(target_ent,source_liquid_type) )
        {
            return false;
        }
        return true;
    }
References CanFillContainer(), and Barrel_ColorBase::IsOpen().
Referenced by ActionDrainLiquid::ActionCondition(), ActionPourLiquid::ActionCondition(), ActionTransferLiquid::ActionCondition(), RecipeBase::CanDo(), and Transfer().
FillContainer()
static void Liquid::FillContainer (ItemBase container, int liquid_type, float amount) inline static private
Definition at line 126 of file liquid.c.
    {
        if ( !CanFillContainer(container,liquid_type) )
        {
            return;
        }
        //filling
        container.SetLiquidType(liquid_type);
        container.AddQuantity(amount);
    }
References CanFillContainer().
Referenced by FillContainerEnviro(), and Transfer().
FillContainerEnviro()
static void Liquid::FillContainerEnviro (ItemBase container, int liquid_type, float amount, bool inject_agents = false) inline static private
Definition at line 138 of file liquid.c.
    {
        FillContainer(container,liquid_type,amount);
        if (inject_agents)
        {
            PluginTransmissionAgents plugin = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
            plugin.TransmitAgents(NULL, container, AGT_WATER_POND, amount);
        }
    }
References AGT_WATER_POND, FillContainer(), and GetPlugin().
Referenced by CAContinuousFill::CalcAndSetQuantity(), and RainProcurementManager::RainProcurementCheck().
GetAgents()
static int Liquid::GetAgents (int liquid_type) inline static private
Definition at line 241 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "agents", true).ToInt();
    }
References GetLiquidConfigProperty(), and string::ToInt().
GetDigestibility()
static float Liquid::GetDigestibility (int liquid_type) inline static private
Definition at line 281 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "digestibility", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetEnergy()
static float Liquid::GetEnergy (int liquid_type) inline static private
Definition at line 256 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "energy", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
GetFlammability()
static float Liquid::GetFlammability (int liquid_type) inline static private
Definition at line 271 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "flammability").ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
GetFullness()
static float Liquid::GetFullness (int liquid_type) inline static private
Definition at line 276 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "fullnessIndex", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetLiquidClassname()
static string Liquid::GetLiquidClassname (int liquid_type) inline static private
Definition at line 8 of file liquid.c.
    {
        NutritionalProfile liquid = m_AllLiquidsByType.Get(liquid_type);
        if (liquid)
        {
            return liquid.GetLiquidClassname();
        }
        return "";
    }
References NutritionalProfile::GetLiquidClassname(), and m_AllLiquidsByType.
Referenced by ManBase::Consume().
GetLiquidConfigProperty()
static private string Liquid::GetLiquidConfigProperty (int liquid_type, string property_name, bool is_nutrition_property = false) inline static private
Definition at line 187 of file liquid.c.
    {
        string cfg_classname = "cfgLiquidDefinitions";
        string property_value = "NULL_PROPERTY";
        int cfg_item_count = g_Game.ConfigGetChildrenCount(cfg_classname);
        for ( int i = 0; i < cfg_item_count; i++ )
        {
            string liquid_class_name;
            GetGame().ConfigGetChildName(cfg_classname, i, liquid_class_name);
            string liquid_full_path = string.Format("%1 %2", cfg_classname, liquid_class_name);
            int config_liquid_type = GetGame().ConfigGetInt(string.Format("%1 type", liquid_full_path) );
            if ( config_liquid_type == liquid_type )// found the specific class, now lets extract the values
            {
                if (!is_nutrition_property)
                {
                    GetGame().ConfigGetText(string.Format("%1 %2", liquid_full_path, property_name), property_value);
                    return property_value;
                }
                else
                {
                    GetGame().ConfigGetText(string.Format("%1 Nutrition %2", liquid_full_path, property_name), property_value);
                    return property_value;
                }
            }
        }
        return property_value;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), CGame::ConfigGetText(), g_Game, and GetGame().
Referenced by GetAgents(), GetDigestibility(), GetEnergy(), GetFlammability(), GetFullness(), GetName(), GetNutritionalIndex(), GetToxicity(), and GetWaterContent().
GetName()
static string Liquid::GetName (int liquid_type) inline static private
Definition at line 266 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "name");
    }
References GetLiquidConfigProperty().
GetNutritionalIndex()
static float Liquid::GetNutritionalIndex (int liquid_type) inline static private
Definition at line 261 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "nutritionalIndex", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetNutritionalProfileByName()
static NutritionalProfile Liquid::GetNutritionalProfileByName (string class_name) inline static private
Definition at line 222 of file liquid.c.
    {
        return m_AllLiquidsByName.Get(class_name);
    }
References class_name, and m_AllLiquidsByName.
Referenced by AddToStomach().
GetNutritionalProfileByType()
static NutritionalProfile Liquid::GetNutritionalProfileByType (int liquid_type) inline static private
Definition at line 217 of file liquid.c.
    {
        return m_AllLiquidsByType.Get(liquid_type);
    }
References m_AllLiquidsByType.
GetToxicity()
static float Liquid::GetToxicity (int liquid_type) inline static private
Definition at line 246 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "toxicity", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
GetWaterContent()
static float Liquid::GetWaterContent (int liquid_type) inline static private
Definition at line 251 of file liquid.c.
    {
        return Liquid.GetLiquidConfigProperty(liquid_type, "water", true).ToFloat();
    }
References GetLiquidConfigProperty(), and string::ToFloat().
Referenced by SetUpNutritionalProfile().
InitAllLiquids()
static bool Liquid::InitAllLiquids () inline static private
Definition at line 19 of file liquid.c.
    {
        string cfg_classname = "cfgLiquidDefinitions";
        string property_value = "NULL_PROPERTY";
        int cfg_item_count = g_Game.ConfigGetChildrenCount(cfg_classname);
        for ( int i = 0; i < cfg_item_count; i++ )
        {
            string liquid_class_name;
            GetGame().ConfigGetChildName(cfg_classname, i, liquid_class_name);
            string liquid_full_path = string.Format("%1 %2",cfg_classname, liquid_class_name);
            int config_liquid_type = GetGame().ConfigGetInt( string.Format("%1 type", liquid_full_path) );
            m_AllLiquidsByType.Insert(config_liquid_type, SetUpNutritionalProfile(config_liquid_type, liquid_class_name));
            m_AllLiquidsByName.Insert(liquid_class_name, SetUpNutritionalProfile(config_liquid_type, liquid_class_name));
        }
        return true;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetInt(), g_Game, GetGame(), m_AllLiquidsByName, m_AllLiquidsByType, and SetUpNutritionalProfile().
SetUpNutritionalProfile()
static NutritionalProfile Liquid::SetUpNutritionalProfile (int liquid_type, string liquid_class_name) inline static private
Definition at line 227 of file liquid.c.
    {
        float energy = GetEnergy(liquid_type);
        float nutritional_index = GetNutritionalIndex(liquid_type);
        float volume = GetFullness(liquid_type);
        float water_content = GetWaterContent(liquid_type);
        float toxicity = GetToxicity(liquid_type);
        int agents = GetAgents(liquid_type);
        float digest = GetDigestibility(liquid_type);
        NutritionalProfile profile = new NutritionalProfile(energy, water_content, nutritional_index, volume, toxicity, agents, digest );
        profile.MarkAsLiquid(liquid_type, liquid_class_name);
        return profile;
    }
References GetAgents(), GetDigestibility(), GetEnergy(), GetFullness(), GetNutritionalIndex(), GetToxicity(), GetWaterContent(), and NutritionalProfile::MarkAsLiquid().
Referenced by InitAllLiquids().
Transfer()
static void Liquid::Transfer (ItemBase source_ent, ItemBase target_ent, float quantity = -1) inline static private
Definition at line 39 of file liquid.c.
    {
        if ( !Liquid.CanTransfer(source_ent, target_ent) ) return;
        ItemBase source = source_ent;
        ItemBase target = target_ent;
//      Debug.Log("Transfer, source:"+source.ToString()+" target: "+target.ToString(), "LiquidTransfer");
        float source_quantity   = source.GetQuantity();
        float target_quantity   = target.GetQuantity();
        int source_liquid_type  = source.GetLiquidType();
        int target_liquid_type  = target.GetLiquidType();
        int target_mask         = target_ent.ConfigGetFloat("liquidContainerType");
        int source_mask         = source_ent.ConfigGetFloat("liquidContainerType");
        float available_capacity = target.GetQuantityMax() - target_quantity;
//      Debug.Log("target_mask ="+target_mask.ToString(), "LiquidTransfer");
//      Debug.Log("source_mask ="+source_mask.ToString(), "LiquidTransfer");
//      Debug.Log("source_liquid_type ="+source_liquid_type.ToString(), "LiquidTransfer");
//      Debug.Log("target_liquid_type ="+target_liquid_type.ToString(), "LiquidTransfer");
        //target.GetBloodType(source_liquid_type);//override target liquidType
        float quantity_to_transfer;
        //transfers all
        if (quantity == -1)
        {
            quantity_to_transfer = Math.Clamp(source_quantity,0,available_capacity);
        }
        //transfers exact ammount
        else
        {
            quantity_to_transfer = Math.Clamp(quantity,0,available_capacity);
        }
        //target.AddQuantity(quantity_to_transfer);
        PluginTransmissionAgents m_mta = PluginTransmissionAgents.Cast(GetPlugin(PluginTransmissionAgents));
        m_mta.TransmitAgents(source_ent, target_ent, AGT_TRANSFER_COPY);
        source.AddQuantity(-quantity_to_transfer);
        Liquid.FillContainer(target_ent,source_liquid_type,quantity_to_transfer);
    }
References AGT_TRANSFER_COPY, CanTransfer(), Math::Clamp(), FillContainer(), and GetPlugin().
Referenced by CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), and RecipeBase::Do().
Member Data Documentation
m_AllLiquidsByName
ref map<string, ref NutritionalProfile> Liquid::m_AllLiquidsByName = new map<string, ref NutritionalProfile> static private
Definition at line 4 of file liquid.c.
Referenced by GetNutritionalProfileByName(), and InitAllLiquids().
m_AllLiquidsByType
ref map<int, ref NutritionalProfile> Liquid::m_AllLiquidsByType = new map<int, ref NutritionalProfile> static private
Definition at line 3 of file liquid.c.
Referenced by GetLiquidClassname(), GetNutritionalProfileByType(), and InitAllLiquids().
m_Init
bool Liquid::m_Init = InitAllLiquids() static private
Definition at line 6 of file liquid.c.