DayzKode: AntibioticsMdfr Class Reference
AntibioticsMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override string GetDebugText ()
override string GetDebugTextSimple ()
override void Init ()
override void OnActivate (PlayerBase player)
override void OnDeactivate (PlayerBase player)
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
const int ANTIBIOTICS_LIFETIME = 300
const float ANTIBIOTICS_STRENGTH = 1
float m_RegenTime
Detailed Description
Definition at line 1 of file antibiotics.c.
Member Function Documentation
ActivateCondition()
override bool AntibioticsMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 19 of file antibiotics.c.
    {
        return false;
    }
DeactivateCondition()
override bool AntibioticsMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 60 of file antibiotics.c.
    {
        float attached_time = GetAttachedTime();
        if ( attached_time >= m_RegenTime )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
References GetAttachedTime(), and m_RegenTime.
GetDebugText()
override string AntibioticsMdfr::GetDebugText () inline private
Definition at line 29 of file antibiotics.c.
    {
        return (ANTIBIOTICS_LIFETIME - GetAttachedTime()).ToString();
    }
References ANTIBIOTICS_LIFETIME, GetAttachedTime(), and string::ToString().
GetDebugTextSimple()
override string AntibioticsMdfr::GetDebugTextSimple () inline private
Definition at line 35 of file antibiotics.c.
    {
    return (ANTIBIOTICS_LIFETIME - GetAttachedTime()).ToString();
    }
References ANTIBIOTICS_LIFETIME, GetAttachedTime(), and string::ToString().
Init()
override void AntibioticsMdfr::Init () inline private
Definition at line 7 of file antibiotics.c.
    {
        m_TrackActivatedTime = true;
        m_IsPersistent = true;
        m_ID                    = eModifiers.MDF_ANTIBIOTICS;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 3;
        m_RegenTime = ANTIBIOTICS_LIFETIME;
        DisableActivateCheck();
    }
References ANTIBIOTICS_LIFETIME, DEFAULT_TICK_TIME_INACTIVE, DisableActivateCheck(), m_ID, m_IsPersistent, m_RegenTime, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnActivate()
override void AntibioticsMdfr::OnActivate (PlayerBase player) inline private
Definition at line 40 of file antibiotics.c.
    {
        player.IncreaseHealingsCount();
        player.IncreaseAntibioticsCount();
        /*
        if ( player.GetNotifiersManager() )
            player.GetNotifiersManager().ActivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnDeactivate()
override void AntibioticsMdfr::OnDeactivate (PlayerBase player) inline private
Definition at line 50 of file antibiotics.c.
    {
        player.DecreaseHealingsCount();
        player.DecreaseAntibioticsCount();
        /*
        if ( player.GetNotifiersManager() )
            player.GetNotifiersManager().DeactivateByType(eNotifiers.NTF_PILLS);
        */
    }
OnReconnect()
override void AntibioticsMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 24 of file antibiotics.c.
    {
        OnActivate(player);
    }
References OnActivate().
OnTick()
override void AntibioticsMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 74 of file antibiotics.c.
    {
        player.AntibioticsAttack( ANTIBIOTICS_STRENGTH * deltaT );
    }
References ANTIBIOTICS_STRENGTH.
Member Data Documentation
ANTIBIOTICS_LIFETIME
const int AntibioticsMdfr::ANTIBIOTICS_LIFETIME = 300 private
Definition at line 4 of file antibiotics.c.
Referenced by GetDebugText(), GetDebugTextSimple(), and Init().
ANTIBIOTICS_STRENGTH
const float AntibioticsMdfr::ANTIBIOTICS_STRENGTH = 1 private
Definition at line 5 of file antibiotics.c.
Referenced by OnTick().
m_RegenTime
float AntibioticsMdfr::m_RegenTime private
Definition at line 3 of file antibiotics.c.
Referenced by DeactivateCondition(), and Init().