DayzKode: Managed Class Reference
Managed Class Reference
Enforce script essentials
TODO doc.
Private Member Functions
void AddActiveEffects (array< int > effects)
void AddSuspendRequest (int request_id)
bool AreEffectsSuspended ()
void BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent)
protected void CharacterLoad (int character_id, vector char_pos, vector char_rot)
protected void CharacterUnload ()
void CheckBlood ()
void CheckHealth ()
void CheckValues ()
void ClearSuspendRequests ()
void CreateDefaultCharacter ()
void CreateNewCharacter ()
void CreateNewCharacterById (int character_id)
void CreateNewCharacterByName (string character_name, bool randomize_equip=true)
void CreateNewCharacterRandom ()
bool DataInitialized ()
void GameplayEffectsData (array< ref Widget > input, int type, int user_override=-1)
float GetBlood ()
ECharGender GetCharacterGender ()
int GetCharacterID ()
string GetCharacterName ()
string GetCharacterNameById (int char_id)
PlayerBase GetCharacterObj ()
TStringArray GetCharGenderList ()
TStringArray GetCharList (ECharGender gender)
TStringArray GetCharPantsList ()
TStringArray GetCharShirtsList ()
TStringArray GetCharShoesList ()
bool GetEndNow ()
float GetHealth ()
void GetLastPlayedServer (int characterID, out string address, out string name, out int port)
int GetNextCharacterID ()
vector GetPosition ()
int GetPrevCharacterID ()
int GetSeverity ()
int GetSuspendRequestCount ()
array< ref Widget > GetWidgetSet ()
int GetWidgetSetID ()
int GetWidgetSetType ()
bool HasDefinedHandle ()
Returns 'true' if this class contains update info.
void IncreaseMaskUpdateCount ()
void Init ()
void Init (array< ref Widget > input, int type, Widget layout_root, int user_override=-1)
void InitIndicator (vector position)
void IntroSceneCharacter ()
bool IsAnyEffectRunning ()
bool IsCharacterFemale ()
bool IsDefaultCharacter ()
protected bool IsRunningDrops ()
Are any drops currently being animated?
void LoadCharacterData (vector char_pos, vector char_rot, bool default_char=false)
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
void OnRPC (ParamsReadContext ctx)
void OnScheduledTick (float deltatime)
void OnVoiceEvent (float breathing_resistance01)
void ReceiveValue (int value_type, float value)
void RegisterData (Param p)
void RegisterGameplayEffectData (int id, Param p)
void RemoveActiveEffects (array< int > effects)
void RemoveSuspendRequest (int request_id)
void ResetIndicator ()
void ResetMaskUpdateCount ()
protected void ResetSequence ()
void SaveCharName (string name)
void SaveDefaultCharacter ()
void SendInitValues ()
Sends values on object creation.
void SendValue (int value_type, float value)
void SetAttachment (string type, int slot)
void SetBreathIntensityStamina (float stamina_cap, float stamina_current)
void SetCharacterGender (ECharGender gender)
void SetCharacterID (int char_id)
void SetToDefaultCharacter ()
protected void SetupPlayerName (bool new_name)
void ShowDebugValues (bool show)
protected void StartRunningDrops ()
void StopAllEffects ()
void StopIndicator (bool instant=false)
void TransferValues (PlayerBase player)
void TrySpawnNextDrop ()
void Update (float timeSlice)
void Update (float timeSlice)
void Update (float timeSlice=0, Param p=null, int handle=-1)
void UpdateVisibility (bool state)
void UpdateWidgets (int type=-1, float timeSlice=0, Param p=null, int handle=-1)
void ~IntroSceneCharacter ()
Static Private Member Functions
static void Cleanup ()
static PPERequesterBase GetRequester (int index)
Returns an instance (singleton) of a requester based on index.
static PPERequesterBase GetRequester (typename type)
Returns an instance (singleton) of a requester based on typename.
static int GetRequesterID (typename type)
Returns an ID of a requester type.
static GetRequesterTypename (int index)
Returns a typename from a requester ID.
static void Init ()
static int RegisterRequester (typename type)
Registers new requester type.
static bool VerifyRequester (PPERequesterBase req)
Verifies the instance.
Private Attributes
const int BLOOD_THRESHOLD_LOW = 3000
ref set< ref BleedingIndicatorDropData > m_ActiveDrops
protected int m_ActiveDropsCount
int m_AnimType
protected float m_AverageFrequency
protected vector m_BasePosition
float m_BloodClient
float m_BloodMaxValue
protected MenuData m_CharacterDta
protected int m_CharacterId
protected PlayerBase m_CharacterObj
protected vector m_CharacterPos
protected vector m_CharacterRot
protected ref map< ECharGender, ref array< string > > m_Characters = new map<ECharGender, ref array<string>>
protected string m_CharacterType
protected ECharGender m_CharGender
protected ref TStringArray m_CharGenderList = new TStringArray
protected ref TStringArray m_CharPantsList = new TStringArray
protected ref TStringArray m_CharShirtList = new TStringArray
protected ref TStringArray m_CharShoesList = new TStringArray
ref set< int > m_CleanupQueue
protected int m_CurrentDropProbabilityStep
protected array< float > m_DropProbabilityArray
protected int m_DropProbabilityRollsCount
protected float m_DropSpawnMaxDelay
protected float m_DropSpawnMinDelay
protected int m_DropSpawnsQueued
protected bool m_EndNow = false
bool m_Fullbody
bool m_HasSource
float m_HealthClient
float m_HealthDamage
float m_HealthMaxValue
float m_HitDir
protected bool m_Initialized
protected bool m_InitialSyncSent
protected bool m_IsRunning = false
float m_LastBloodUpdate
protected float m_LastDropSpawnTime
float m_LastHealthUpdate
Widget m_LayoutRoot
int m_MaskWidgetUpdateCount
protected GameplayEffectsDataBleeding m_ParentMetaData
PlayerBase m_Player
protected float m_SequenceDuration
protected float m_SequenceTick
protected int m_Severity
protected int m_SourceID
protected bool m_Terminating = false
protected float m_TimeElapsedSequence
protected float m_TimeElapsedTotal
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
int m_Type
protected ref array< ref Widget > m_WidgetArray
int m_WidgetSetIdentifier
const float SENSITIVTY_PERCENTAGE = 1
const int TYPE_BLOOD = 2
const int TYPE_HEALTH = 1
const float VALUE_CHECK_INTERVAL = 5
Static Private Attributes
static const int INVALID = -1
static private bool m_Initialized = false
static private ref map< int, ref PPERequesterBase > m_Instances
static int m_lastID = -1
static private ref PPERequesterRegistrations m_Registrations
static const int REQ_BLOODLOSS = RegisterRequester(PPERequester_BloodLoss)
static const int REQ_BURLAPSACK = RegisterRequester(PPERequester_BurlapSackEffects)
static const int REQ_CAMERAADS = RegisterRequester(PPERequester_CameraADS)
static const int REQ_CAMERANV = RegisterRequester(PPERequester_CameraNV)
static const int REQ_CONTAMINATEDAREA = RegisterRequester(PPERequester_ContaminatedAreaTint)
static const int REQ_CONTROLLERBLUR = RegisterRequester(PPERequester_ControlsBlur)
static const int REQ_CONTROLLERDISCONNECT = RegisterRequester(PPERequester_ControllerDisconnectBlur)
static const int REQ_DEATHEFFECTS = RegisterRequester(PPERequester_DeathDarkening)
static const int REQ_DROWNING = RegisterRequester(PPERequester_Drowning)
static const int REQ_FEVEREFFECTS = RegisterRequester(PPERequester_FeverEffects)
static const int REQ_FLASHBANGEFFECTS = RegisterRequester(PPERequester_FlashbangEffects)
static const int REQ_GLASSESAVIATOR = RegisterRequester(PPERequester_GlassesAviator)
static const int REQ_GLASSESDESIGNER = RegisterRequester(PPERequester_GlassesDesignerBlack)
static const int REQ_GLASSESSPORTBLACK = RegisterRequester(PPERequester_GlassesSportBlack)
static const int REQ_GLASSESSPORTBLUE = RegisterRequester(PPERequester_GlassesSportBlue)
static const int REQ_GLASSESSPORTGREEN = RegisterRequester(PPERequester_GlassesSportGreen)
static const int REQ_GLASSESSPORTORANGE = RegisterRequester(PPERequester_GlassesSportOrange)
static const int REQ_GLASSESTACTICAL = RegisterRequester(PPERequester_TacticalGoggles)
static const int REQ_GLASSESWELDING = RegisterRequester(PPERequester_WeldingMask)
static const int REQ_HEALTHHITEFFECTS = RegisterRequester(PPERequester_HealthHitReaction)
static const int REQ_INTROCHROMABB = RegisterRequester(PPERequester_IntroChromAbb)
static const int REQ_INVENTORYBLUR = RegisterRequester(PPERequester_InventoryBlur)
static const int REQ_MENUEFFECTS = RegisterRequester(PPERequester_MenuEffects)
static const int REQ_MOTOHELMETBLACK = RegisterRequester(PPERequester_MotoHelmetBlack)
static const int REQ_PAINBLUR = RegisterRequester(PPERequester_PainBlur)
static const int REQ_SERVERBROWSEREFFECTS = RegisterRequester(PPERequester_ServerBrowserBlur)
static const int REQ_SHOCKHITEFFECTS = RegisterRequester(PPERequester_ShockHitReaction)
static const int REQ_SPOOKYAREA = RegisterRequester(PPERequester_SpookyAreaTint)
static const int REQ_TUNELVISSION = RegisterRequester(PPERequester_TunnelVisionEffects)
static const int REQ_TUTORIALEFFECTS = RegisterRequester(PPERequester_TutorialMenu)
static const int REQ_UNCONEFFECTS = RegisterRequester(PPERequester_UnconEffects)
static const int REQ_UNDERGROUND = RegisterRequester(PPERUndergroundAcco)
Detailed Description
TODO doc.
generic metadata class
indicator wrapper for a specific bleeding source.
extendable type to allow for smarter hit data syncing
Requester bank contains all registered type instances as singletons. Creating new instances outside of bank might be a bad idea (and a way to memory leakage)
Definition at line 117 of file enscript.c.
Constructor & Destructor Documentation
~IntroSceneCharacter()
void Managed::~IntroSceneCharacter () inline private
Definition at line 24 of file introscenecharacter.c.
    {
        CharacterUnload();
    }
References CharacterUnload().
Member Function Documentation
AddActiveEffects()
void Managed::AddActiveEffects (array< int > effects) inline private
Definition at line 10 of file gameplayeffectwidgets_base.c.
{}
AddSuspendRequest()
void Managed::AddSuspendRequest (int request_id) inline private
Definition at line 13 of file gameplayeffectwidgets_base.c.
{}
AreEffectsSuspended()
bool Managed::AreEffectsSuspended () inline private
Definition at line 9 of file gameplayeffectwidgets_base.c.
{}
BleedingIndicator()
void Managed::BleedingIndicator (int source_ID, int severity, GameplayEffectsDataBleeding parent) inline private
Definition at line 31 of file bleedingindicator.c.
    {
        m_Initialized = false;
        m_SourceID = source_ID;
        m_Severity = severity;
        m_ParentMetaData = parent;
        m_CurrentDropProbabilityStep = 0;
        m_ActiveDrops = new set<ref BleedingIndicatorDropData>;
        m_CleanupQueue = new set<int>;
        m_DropProbabilityArray = m_ParentMetaData.GetProbabilities(m_Severity);
        m_DropProbabilityRollsCount = m_DropProbabilityArray.Count();
        switch (m_Severity)
        {
            case BleedingIndicationConstants.INDICATOR_SEVERITY_LOW:
            {
                m_SequenceDuration = BleedingIndicationConstants.SEQUENCE_DURATION_LOW;
                m_AverageFrequency = BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_LOW;
                m_DropSpawnMinDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MIN_LOW;
                m_DropSpawnMaxDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MAX_LOW;
                break;
            }
            case BleedingIndicationConstants.INDICATOR_SEVERITY_MEDIUM:
            {
                m_SequenceDuration = BleedingIndicationConstants.SEQUENCE_DURATION_MEDIUM;
                m_AverageFrequency = BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_MEDIUM;
                m_DropSpawnMinDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MIN_MEDIUM;
                m_DropSpawnMaxDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MAX_MEDIUM;
                break;
            }
            case BleedingIndicationConstants.INDICATOR_SEVERITY_HIGH:
            {
                m_SequenceDuration = BleedingIndicationConstants.SEQUENCE_DURATION_HIGH;
                m_AverageFrequency = BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_HIGH;
                m_DropSpawnMinDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MIN_HIGH;
                m_DropSpawnMaxDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MAX_HIGH;
                break;
            }
            default:
            {
                m_AverageFrequency = BleedingIndicationConstants.SEQUENCE_DROP_AVERAGE_LOW;
                m_DropSpawnMinDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MIN_LOW;
                m_DropSpawnMaxDelay = BleedingIndicationConstants.SEQUENCE_DROP_DELAY_MAX_LOW;
                Debug.Log("Unknown severity value!");
            }
#ifdef DIAG_DEVELOPER
            if (DbgBleedingIndicationStaticInfo.m_DbgUseOverrideValues)
            {
                m_SequenceDuration = DbgBleedingIndicationStaticInfo.m_DbgSequenceDuration;
                m_DropSpawnMinDelay = DbgBleedingIndicationStaticInfo.m_DbgDropMinDelay;
                m_DropSpawnMaxDelay = DbgBleedingIndicationStaticInfo.m_DbgDropMaxDelay;
            }
#endif
        }
        m_TimeElapsedTotal = 0;
        m_TimeElapsedSequence = 0;
    }
References BleedingIndicationConstants::INDICATOR_SEVERITY_HIGH, BleedingIndicationConstants::INDICATOR_SEVERITY_LOW, BleedingIndicationConstants::INDICATOR_SEVERITY_MEDIUM, Debug::Log(), DbgBleedingIndicationStaticInfo::m_DbgDropMaxDelay, DbgBleedingIndicationStaticInfo::m_DbgDropMinDelay, DbgBleedingIndicationStaticInfo::m_DbgSequenceDuration, DbgBleedingIndicationStaticInfo::m_DbgUseOverrideValues, m_Initialized, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_LOW, BleedingIndicationConstants::SEQUENCE_DROP_AVERAGE_MEDIUM, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_LOW, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MAX_MEDIUM, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_HIGH, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_LOW, BleedingIndicationConstants::SEQUENCE_DROP_DELAY_MIN_MEDIUM, BleedingIndicationConstants::SEQUENCE_DURATION_HIGH, BleedingIndicationConstants::SEQUENCE_DURATION_LOW, and BleedingIndicationConstants::SEQUENCE_DURATION_MEDIUM.
CharacterLoad()
protected void Managed::CharacterLoad (int character_id, vector char_pos, vector char_rot) inline private
Definition at line 356 of file introscenecharacter.c.
    {
        if ( character_id == -1 )
        {
            Error("IntroSceneCharacter->CharacterLoad: character_id = "+ character_id +" Cant Load Character!!!");
            return;
        }
        CharacterUnload();
        SetCharacterID( character_id );
        m_CharacterObj = PlayerBase.Cast( m_CharacterDta.CreateCharacterPerson( character_id ) );
        if ( m_CharacterObj )
        {
            m_CharacterObj.PlaceOnSurface();
            m_CharacterObj.SetPosition(char_pos);
            m_CharacterObj.SetOrientation(char_rot);
        }
    }
References CharacterUnload(), MenuData::CreateCharacterPerson(), Error(), and SetCharacterID().
Referenced by CreateNewCharacterById().
CharacterUnload()
protected void Managed::CharacterUnload () inline private
Definition at line 344 of file introscenecharacter.c.
    {
        if ( m_CharacterObj )
        {
            g_Game.ObjectDelete(m_CharacterObj);
            m_CharacterObj = NULL;
        }
    }
References g_Game.
Referenced by CharacterLoad(), CreateDefaultCharacter(), CreateNewCharacter(), and ~IntroSceneCharacter().
CheckBlood()
void Managed::CheckBlood () inline private
Definition at line 142 of file transfervalues.c.
    {
        float blood_current = m_Player.GetHealth("","Blood");
        //float blood_normalized = blood_current / m_BloodMaxValue;
        float blood_normalized = Math.InverseLerp(BLOOD_THRESHOLD_LOW, m_BloodMaxValue, blood_current);
        blood_normalized = Math.Clamp(blood_normalized,0,1);
        float difference_normalized = blood_normalized - m_LastBloodUpdate;
        float diff_abs = Math.AbsFloat(difference_normalized);
        if( diff_abs > ( SENSITIVTY_PERCENTAGE /100 ) )
        {
            SendValue(TYPE_BLOOD, blood_normalized);
            m_LastBloodUpdate = blood_normalized;
        }
    }
References Math::AbsFloat(), Math::Clamp(), Math::InverseLerp(), m_LastBloodUpdate, m_Player, SendValue(), and SENSITIVTY_PERCENTAGE.
Referenced by CheckValues().
CheckHealth()
void Managed::CheckHealth () inline private
Definition at line 104 of file transfervalues.c.
    {
        float health_current = m_Player.GetHealth("","Health");
        float health_normalized = health_current / m_HealthMaxValue;
        float difference_normalized = health_normalized - m_LastHealthUpdate;
        float diff_abs = Math.AbsFloat(difference_normalized);
        if( diff_abs > ( SENSITIVTY_PERCENTAGE /100 ) )
        {
            SendValue(TYPE_HEALTH, health_normalized);
            m_LastHealthUpdate = health_normalized;
        }
    }
References Math::AbsFloat(), m_HealthMaxValue, m_LastHealthUpdate, m_LastHealthUpdate, m_Player, SendValue(), and SENSITIVTY_PERCENTAGE.
Referenced by CheckValues().
CheckValues()
void Managed::CheckValues () inline private
Definition at line 87 of file transfervalues.c.
    {
        CheckHealth();
        CheckBlood();
    }
References CheckBlood(), and CheckHealth().
Referenced by OnScheduledTick().
Cleanup()
static void Managed::Cleanup () inline static private
Definition at line 57 of file pperequesterbank.c.
    {
        if (m_Initialized)
        {
            delete m_Registrations;
            m_Instances.Clear();
        }
    }
References m_Initialized, m_Instances, and m_Registrations.
ClearSuspendRequests()
void Managed::ClearSuspendRequests () inline private
Definition at line 15 of file gameplayeffectwidgets_base.c.
{}
CreateDefaultCharacter()
void Managed::CreateDefaultCharacter () inline private
Definition at line 219 of file introscenecharacter.c.
    {
        CharacterUnload();
        //m_CharacterDta.RequestGetDefaultCharacterData();
        m_CharacterType = GetGame().GetMenuDefaultCharacterData().GetCharacterType();
        if (m_CharacterType != "")
        {
            CreateNewCharacter();
        }
        if(m_CharacterObj)
        {
            m_CharacterObj.PlaceOnSurface();
            m_CharacterObj.SetPosition(m_CharacterPos);
            m_CharacterObj.SetOrientation(m_CharacterRot);
        }
        else
        {
            string default_name = Widget.TranslateString( GameConstants.DEFAULT_CHARACTER_NAME );
            CreateNewCharacterRandom();
            //m_CharacterDta.SetCharacterName(GameConstants.DEFAULT_CHARACTER_MENU_ID, default_name);
            GetGame().GetMenuDefaultCharacterData().SetCharacterName(GameConstants.DEFAULT_CHARACTER_NAME);
        }
    }
References CharacterUnload(), CreateNewCharacter(), CreateNewCharacterRandom(), GameConstants::DEFAULT_CHARACTER_NAME, MenuDefaultCharacterData::GetCharacterType(), GetGame(), CGame::GetMenuDefaultCharacterData(), and MenuDefaultCharacterData::SetCharacterName().
Referenced by CreateNewCharacterById().
CreateNewCharacter()
void Managed::CreateNewCharacter () inline private
Definition at line 253 of file introscenecharacter.c.
    {
        // Unload old character (if exist)
        CharacterUnload();
        // Create Character
        m_CharacterObj = PlayerBase.Cast(g_Game.CreateObjectEx(m_CharacterType, m_CharacterPos, ECE_PLACE_ON_SURFACE));
        if (m_CharacterObj)
        {
            m_CharacterObj.PlaceOnSurface();
            m_CharacterObj.SetOrientation(m_CharacterRot);
            GetGame().GetMenuDefaultCharacterData().EquipDefaultCharacter(m_CharacterObj);
        }
        //Create New Random Character
        SetupPlayerName( true );
    }
References CharacterUnload(), ECE_PLACE_ON_SURFACE, MenuDefaultCharacterData::EquipDefaultCharacter(), g_Game, GetGame(), CGame::GetMenuDefaultCharacterData(), and SetupPlayerName().
Referenced by CreateDefaultCharacter(), and CreateNewCharacterByName().
CreateNewCharacterById()
void Managed::CreateNewCharacterById (int character_id) inline private
Definition at line 194 of file introscenecharacter.c.
    {
        if ( character_id == GameConstants.DEFAULT_CHARACTER_MENU_ID )
        {
            CreateDefaultCharacter();
        }
        else
        {
            CharacterLoad( character_id, m_CharacterPos, m_CharacterRot );
        }
    }
References CharacterLoad(), CreateDefaultCharacter(), and GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by LoadCharacterData().
CreateNewCharacterByName()
void Managed::CreateNewCharacterByName (string character_name, bool randomize_equip = true) inline private
Definition at line 209 of file introscenecharacter.c.
    {
        m_CharacterType = character_name;
        GetGame().GetMenuDefaultCharacterData().SetCharacterType(m_CharacterType);
        if (randomize_equip)
            GetGame().GetMenuDefaultCharacterData().GenerateRandomEquip();
        CreateNewCharacter();
    }
References CreateNewCharacter(), MenuDefaultCharacterData::GenerateRandomEquip(), GetGame(), CGame::GetMenuDefaultCharacterData(), and MenuDefaultCharacterData::SetCharacterType().
Referenced by CreateNewCharacterRandom().
CreateNewCharacterRandom()
void Managed::CreateNewCharacterRandom () inline private
Definition at line 179 of file introscenecharacter.c.
    {
        // Select random gender
        SetCharacterGender( Math.RandomInt(0, 2) );
        // Select random character skin (class name)
        string char_name_random = m_Characters[GetCharacterGender()].GetRandomElement();
        // Create new character
        CreateNewCharacterByName( char_name_random );
    }
References CreateNewCharacterByName(), GetCharacterGender(), Math::RandomInt(), and SetCharacterGender().
Referenced by CreateDefaultCharacter().
DataInitialized()
bool Managed::DataInitialized () inline private
Definition at line 59 of file gewidgetsmetadata.c.
    {
        return true;
    }
GameplayEffectsData()
void Managed::GameplayEffectsData (array< ref Widget > input, int type, int user_override = -1) inline private
Definition at line 13 of file gewidgetsmetadata.c.
    {
        m_WidgetArray = input;
        m_Type = type;
        m_WidgetSetIdentifier = type;
        if (user_override != -1)
        {
            m_WidgetSetIdentifier = user_override;
        }
    }
References m_Type.
GetBlood()
float Managed::GetBlood () inline private
Definition at line 93 of file transfervalues.c.
    {
        return m_BloodClient;
    }
References m_BloodClient.
GetCharacterGender()
ECharGender Managed::GetCharacterGender () inline private
Definition at line 121 of file introscenecharacter.c.
    {
        return m_CharGender;
    }
References m_CharGender.
Referenced by CreateNewCharacterRandom().
GetCharacterID()
int Managed::GetCharacterID () inline private
Definition at line 49 of file introscenecharacter.c.
    {
        return m_CharacterId;
    }
References m_CharacterId.
GetCharacterName()
string Managed::GetCharacterName () inline private
Definition at line 440 of file introscenecharacter.c.
    {
        string character_name;
        if (IsDefaultCharacter())
        {
            character_name = GetGame().GetMenuDefaultCharacterData().GetCharacterName();
        }
        else
        {
            m_CharacterDta.GetCharacterName(m_CharacterId, character_name);
        }
        return character_name;
    }
References MenuDefaultCharacterData::GetCharacterName(), MenuData::GetCharacterName(), GetGame(), CGame::GetMenuDefaultCharacterData(), and IsDefaultCharacter().
GetCharacterNameById()
string Managed::GetCharacterNameById (int char_id) inline private
Definition at line 426 of file introscenecharacter.c.
    {
        string character_name;
        if (char_id == GameConstants.DEFAULT_CHARACTER_MENU_ID)
        {
            character_name = GetGame().GetMenuDefaultCharacterData().GetCharacterName();
        }
        else
        {
            m_CharacterDta.GetCharacterName(char_id, character_name);
        }
        return character_name;
    }
References GameConstants::DEFAULT_CHARACTER_MENU_ID, MenuDefaultCharacterData::GetCharacterName(), MenuData::GetCharacterName(), GetGame(), and CGame::GetMenuDefaultCharacterData().
GetCharacterObj()
PlayerBase Managed::GetCharacterObj () inline private
Definition at line 57 of file introscenecharacter.c.
    {
        return m_CharacterObj;
    }
References m_CharacterObj.
Referenced by LoadCharacterData(), and DayZIntroScene::ResetIntroCamera().
GetCharGenderList()
TStringArray Managed::GetCharGenderList () inline private
Definition at line 65 of file introscenecharacter.c.
    {
        return m_CharGenderList;
    }
References m_CharGenderList.
GetCharList()
TStringArray Managed::GetCharList (ECharGender gender) inline private
Definition at line 73 of file introscenecharacter.c.
    {
        return m_Characters[gender];
    }
GetCharPantsList()
TStringArray Managed::GetCharPantsList () inline private
Definition at line 89 of file introscenecharacter.c.
    {
        return m_CharPantsList;
    }
References m_CharPantsList.
GetCharShirtsList()
TStringArray Managed::GetCharShirtsList () inline private
Definition at line 81 of file introscenecharacter.c.
    {
        return m_CharShirtList;
    }
References m_CharShirtList.
GetCharShoesList()
TStringArray Managed::GetCharShoesList () inline private
Definition at line 97 of file introscenecharacter.c.
    {
        return m_CharShoesList;
    }
References m_CharShoesList.
GetEndNow()
bool Managed::GetEndNow () inline private
Definition at line 256 of file bleedingindicator.c.
    {
        return m_EndNow;
    }
References m_EndNow.
GetHealth()
float Managed::GetHealth () inline private
Definition at line 99 of file transfervalues.c.
    {
        return m_HealthClient;
    }
References m_HealthClient.
GetLastPlayedServer()
void Managed::GetLastPlayedServer (int characterID, out string address, out string name, out int port) inline private
Definition at line 244 of file introscenecharacter.c.
    {
        m_CharacterDta.GetLastServerAddress(characterID,address);
        port = m_CharacterDta.GetLastServerPort(characterID);
        m_CharacterDta.GetLastServerName(characterID,name);
    }
References MenuData::GetLastServerAddress(), MenuData::GetLastServerName(), MenuData::GetLastServerPort(), and name.
GetNextCharacterID()
int Managed::GetNextCharacterID () inline private
Definition at line 137 of file introscenecharacter.c.
    {
        int count = m_CharacterDta.GetCharactersCount();
        if ( count == 0 )
        {
            return -1;
        }
        if ( m_CharacterId + 1 < count )
        {
            return m_CharacterId + 1;
        }
        else
        {
            return -1;
        }
    }
References MenuData::GetCharactersCount().
GetPosition()
vector Managed::GetPosition () inline private
Definition at line 129 of file introscenecharacter.c.
    {
        return m_CharacterObj.GetPosition();
    }
Referenced by DayZIntroScene::ResetIntroCamera().
GetPrevCharacterID()
int Managed::GetPrevCharacterID () inline private
Definition at line 159 of file introscenecharacter.c.
    {
        int count = m_CharacterDta.GetCharactersCount();
        if ( count == 0 )
        {
            return -1;
        }
        if ( m_CharacterId > -1 )
        {
            return m_CharacterId - 1;
        }
        return count - 1;
    }
References MenuData::GetCharactersCount().
GetRequester() [1/2]
static PPERequesterBase Managed::GetRequester (int index) inline static private
Returns an instance (singleton) of a requester based on index.
Parameters
index int Index of the registered requester.
Returns
PPERequesterBase Requester singleton.
Note
Returns only already registered instances, does not register anything.
Definition at line 105 of file pperequesterbank.c.
    {
        PPERequesterBase ret = m_Instances.Get(index);
        if (!ret)
        {
            Debug.Log("Requester idx '" + index + "' not found in bank! Register first in 'RegisterRequester' method.");
        }
        return ret;
    }
References Debug::Log(), and m_Instances.
GetRequester() [2/2]
static PPERequesterBase Managed::GetRequester (typename type) inline static private
Returns an instance (singleton) of a requester based on typename.
Parameters
type typename Typename of the requester.
Returns
PPERequesterBase Requester singleton.
Note
Returns only already registered instances, does not register anything.
Definition at line 72 of file pperequesterbank.c.
    {
        if (!type)
        {
            Error("Requested type is NULL!");
            return null;
        }
        PPERequesterBase temp;
        PPERequesterBase ret;
        for (int i = 0; i < m_Instances.Count(); i++)
        {
            temp = m_Instances.GetElement(i);
            if (temp.Type() == type)
            {
                Class.CastTo(ret,temp);
                break;
            }
        }
        if (!ret)
        {
            Debug.Log("'" + type.ToString() + "' not found in bank! Register first in 'RegisterRequester' method.");
        }
        return ret;
    }
References Class::CastTo(), Error(), Debug::Log(), and m_Instances.
GetRequesterID()
static int Managed::GetRequesterID (typename type) inline static private
Returns an ID of a requester type.
Parameters
type typename Typename of the requester.
Returns
int Requester ID.
Note
Returns '-1' if not found.
Definition at line 122 of file pperequesterbank.c.
    {
        int ret = -1;
        PPERequesterBase temp;
        for (int i = 0; i < m_Instances.Count(); i++)
        {
            temp = m_Instances.GetElement(i);
            if (temp.Type() == type)
            {
                ret = m_Instances.GetKey(i);
            }
        }
        if ( ret == -1 )
        {
            Debug.Log("Requester instance of the '" + type.ToString() + "' type not found in bank! Register first in 'RegisterRequester' method.");
        }
        return ret;
    }
References Debug::Log(), and m_Instances.
GetRequesterTypename()
static Managed::GetRequesterTypename (int index) inline static private
Returns a typename from a requester ID.
Parameters
index int ID of the requester.
Returns
typename Requester typename.
Definition at line 148 of file pperequesterbank.c.
    {
        typename ret;
        PPERequesterBase temp = m_Instances.Get(index);
        if ( !temp )
        {
            Debug.Log("No requester exists under idx '" + index + "' in bank! Register first in 'RegisterRequester' method.");
        }
        else
        {
            ret = temp.Type();
        }
        return ret;
    }
References Debug::Log(), and m_Instances.
GetSeverity()
int Managed::GetSeverity () inline private
Definition at line 261 of file bleedingindicator.c.
    {
        return m_Severity;
    }
References m_Severity.
GetSuspendRequestCount()
int Managed::GetSuspendRequestCount () inline private
Definition at line 16 of file gameplayeffectwidgets_base.c.
{}
GetWidgetSet()
array< ref Widget > Managed::GetWidgetSet () inline private
Definition at line 38 of file gewidgetsmetadata.c.
    {
        return m_WidgetArray;
    }
GetWidgetSetID()
int Managed::GetWidgetSetID () inline private
Definition at line 48 of file gewidgetsmetadata.c.
    {
        return m_WidgetSetIdentifier;
    }
GetWidgetSetType()
int Managed::GetWidgetSetType () inline private
Definition at line 43 of file gewidgetsmetadata.c.
    {
        return m_Type;
    }
References m_Type.
HasDefinedHandle()
bool Managed::HasDefinedHandle () inline private
Returns 'true' if this class contains update info.
Definition at line 54 of file gewidgetsmetadata.c.
    {
        return false;
    }
IncreaseMaskUpdateCount()
void Managed::IncreaseMaskUpdateCount () inline private
Definition at line 5 of file gameplayeffectwidgets_base.c.
{m_MaskWidgetUpdateCount++};
Init() [1/3]
static void Managed::Init () inline static private
Definition at line 47 of file pperequesterbank.c.
    {
        m_Registrations = new PPERequesterRegistrations;
        if (!m_Instances)
            m_Instances = new map<int,ref PPERequesterBase>;
        m_Initialized = true;
    }
References m_Initialized, m_Instances, m_Registrations, and PPERequesterRegistrations().
Referenced by TransferValues().
Init() [2/3]
void Managed::Init () inline private
Definition at line 35 of file transfervalues.c.
    {
        m_LastHealthUpdate  = 0;
        m_LastBloodUpdate   = 0;
        m_HealthMaxValue    = m_Player.GetMaxHealth("", "Health");
        m_BloodMaxValue     = m_Player.GetMaxHealth("", "Blood");
        m_BloodClient       = 0;
        m_HealthClient      = 0;
    }
References m_HealthMaxValue, m_LastHealthUpdate, and m_Player.
Init() [3/3]
void Managed::Init (array< ref Widget > input, int type, Widget layout_root, int user_override = -1) inline private
Definition at line 25 of file gewidgetsmetadata.c.
    {
        m_WidgetArray = input;
        m_Type = type;
        m_WidgetSetIdentifier = type;
        m_LayoutRoot = layout_root;
        if (user_override != -1)
        {
            m_WidgetSetIdentifier = user_override;
        }
    }
References m_Type.
InitIndicator()
void Managed::InitIndicator (vector position) inline private
Definition at line 91 of file bleedingindicator.c.
    {
        m_BasePosition = position;
        ResetIndicator();
        m_Initialized = true;
    }
References m_Initialized, and ResetIndicator().
IntroSceneCharacter()
void Managed::IntroSceneCharacter () inline private
Definition at line 19 of file introscenecharacter.c.
    {
        m_CharacterId = GameConstants.DEFAULT_CHARACTER_MENU_ID;
    }
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by DayZIntroScene::DayZIntroScene(), and DayZIntroSceneXbox::DayZIntroSceneXbox().
IsAnyEffectRunning()
bool Managed::IsAnyEffectRunning () inline private
Definition at line 8 of file gameplayeffectwidgets_base.c.
{}
IsCharacterFemale()
bool Managed::IsCharacterFemale () inline private
Definition at line 113 of file introscenecharacter.c.
    {
        return ( m_CharGender == ECharGender.Female );
    }
IsDefaultCharacter()
bool Managed::IsDefaultCharacter () inline private
Definition at line 29 of file introscenecharacter.c.
    {
        return m_CharacterId == GameConstants.DEFAULT_CHARACTER_MENU_ID;
    }
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
Referenced by GetCharacterName(), and SaveCharName().
IsRunningDrops()
protected bool Managed::IsRunningDrops () inline private
Are any drops currently being animated?
Definition at line 123 of file bleedingindicator.c.
    {
        return m_ActiveDropsCount > 0;
    }
Referenced by Update().
LoadCharacterData()
void Managed::LoadCharacterData (vector char_pos, vector char_rot, bool default_char = false) inline private
Generates random equip for the new IntroSceneCharacter, whatever is defined in 'cfgCharacterCreation'.
Definition at line 292 of file introscenecharacter.c.
    {
        m_CharacterDta = g_Game.GetMenuData();
        m_CharacterPos = char_pos;
        m_CharacterRot = char_rot;
        if (!default_char && m_CharacterDta.GetLastPlayedCharacter() > -1 )
        {
            m_CharacterId = m_CharacterDta.GetLastPlayedCharacter();
            m_CharacterDta.GetCharacterName(m_CharacterId, g_Game.GetPlayerGameName());
        }
        // Load all avalible options for character creation; mostly legacy stuff
        g_Game.ConfigGetTextArray("cfgCharacterCreation" + " gender",   m_CharGenderList);
        g_Game.ConfigGetTextArray("cfgCharacterCreation" + " top",      m_CharShirtList);
        g_Game.ConfigGetTextArray("cfgCharacterCreation" + " bottom",   m_CharPantsList);
        g_Game.ConfigGetTextArray("cfgCharacterCreation" + " shoe",     m_CharShoesList);
        // Init character table
        m_Characters.Clear();
        m_Characters.Insert( ECharGender.Male,      new array<string> );
        m_Characters.Insert( ECharGender.Female,    new array<string> );
        // Sort character by Gender
        TStringArray characters = GetGame().ListAvailableCharacters();
        for (int i = 0; i < characters.Count(); i++)
        {
            string char_cfg_name = characters.Get(i);
            if ( GetGame().IsKindOf(char_cfg_name, "SurvivorMale_Base") )
            {
                m_Characters[ECharGender.Male].Insert( char_cfg_name );
            }
            else
            {
                m_Characters[ECharGender.Female].Insert( char_cfg_name );
            }
        }
        CreateNewCharacterById(m_CharacterId/*, m_CharacterPos, m_CharacterRot*/);
        if (GetCharacterObj() )
        {
            if ( GetCharacterObj().IsMale() )
                SetCharacterGender(ECharGender.Male);
            else
                SetCharacterGender(ECharGender.Female);
        }
    }
References CreateNewCharacterById(), g_Game, MenuData::GetCharacterName(), GetCharacterObj(), GetGame(), MenuData::GetLastPlayedCharacter(), IsKindOf(), CGame::ListAvailableCharacters(), and SetCharacterGender().
OnRPC()
void Managed::OnRPC (ParamsReadContext ctx) inline private
Definition at line 198 of file transfervalues.c.
    {
        ctx.Read(CachedObjectsParams.PARAM2_INT_FLOAT);
        int value_type  = CachedObjectsParams.PARAM2_INT_FLOAT.param1;
        float value     = CachedObjectsParams.PARAM2_INT_FLOAT.param2;
        ReceiveValue(value_type, value);
    }
References CachedObjectsParams::PARAM2_INT_FLOAT, Serializer::Read(), and ReceiveValue().
OnScheduledTick()
void Managed::OnScheduledTick (float deltatime) inline private
Definition at line 45 of file transfervalues.c.
    {
        #ifdef DEVELOPER
        if ( DiagMenu.GetBool(DiagMenuIDs.DM_TRANSFER_VALUES_SHOW) )
        {
            if(!GetGame().IsDedicatedServer())
                ShowDebugValues(true);
        }
        else
        {
            if(!GetGame().IsDedicatedServer())
                ShowDebugValues(false);
        }
        #endif
        if( GetGame().IsClient() ) return;
        m_TimeSinceLastTick += deltatime;
        if (!m_InitialSyncSent)
        {
            SendInitValues();
        }
        else if( m_TimeSinceLastTick > VALUE_CHECK_INTERVAL )
        {
            /*
            Print(m_TimeSinceLastTick.ToString());
            Print(VALUE_CHECK_INTERVAL.ToString());
            Print("--------------");
            */
            m_TimeSinceLastTick = 0;
            CheckValues();
            // send sync junctures if necessary
            // TODO: !!!! event is sent too often, please fix it
            /*
            float damage = 1 - m_Player.GetHealth("", "") / 100;
            DayZPlayerSyncJunctures.SendInjury(m_Player, true, damage);
            */
        }
    }
References CheckValues(), DiagMenu::GetBool(), GetGame(), m_TimeSinceLastTick, SendInitValues(), ShowDebugValues(), and VALUE_CHECK_INTERVAL.
OnVoiceEvent()
void Managed::OnVoiceEvent (float breathing_resistance01) inline private
Definition at line 19 of file gameplayeffectwidgets_base.c.
{}
ReceiveValue()
void Managed::ReceiveValue (int value_type, float value) inline private
Definition at line 186 of file transfervalues.c.
    {
        if( value_type == TYPE_HEALTH )
        {
            m_HealthClient = value;
        }
        else if( value_type == TYPE_BLOOD )
        {
            m_BloodClient = value;
        }
    }
Referenced by OnRPC().
RegisterData()
void Managed::RegisterData (Param p) inline private
Definition at line 65 of file gewidgetsmetadata.c.
{}
RegisterGameplayEffectData()
void Managed::RegisterGameplayEffectData (int id, Param p) inline private
Definition at line 22 of file gameplayeffectwidgets_base.c.
{}
RegisterRequester()
static int Managed::RegisterRequester (typename type) inline static private
Registers new requester type.
Note
Performed only on game start. New requesters can be registered in 'PPERequesterRegistrations'
Definition at line 168 of file pperequesterbank.c.
    {
        if (!m_Instances)
            m_Instances = new map<int,ref PPERequesterBase>;
        if ( GetRequester(type) != null )
        {
            //Error("Trying to register an already existing requester type: " + type);
            Debug.Log("Trying to register an already existing requester type: " + type);
            return -1;
        }
        m_lastID++;
        PPERequesterBase req;
        req = PPERequesterBase.Cast(type.Spawn());
        req.SetRequesterIDX(m_lastID);
        m_Instances.Set(m_lastID,req);
        return m_lastID;
    }
References GetRequester(), Debug::Log(), m_Instances, m_lastID, m_lastID, and PPERequesterBase::SetRequesterIDX().
RemoveActiveEffects()
void Managed::RemoveActiveEffects (array< int > effects) inline private
Definition at line 11 of file gameplayeffectwidgets_base.c.
{}
RemoveSuspendRequest()
void Managed::RemoveSuspendRequest (int request_id) inline private
Definition at line 14 of file gameplayeffectwidgets_base.c.
{}
ResetIndicator()
void Managed::ResetIndicator () inline private
Definition at line 152 of file bleedingindicator.c.
    {
        m_Terminating = false;
        m_EndNow = false;
        m_TimeElapsedTotal = 0;
        m_CurrentDropProbabilityStep = 0;
        m_TimeElapsedSequence = 0;
        m_LastDropSpawnTime = 0;
        m_DropSpawnsQueued = 0;
    }
Referenced by InitIndicator().
ResetMaskUpdateCount()
void Managed::ResetMaskUpdateCount () inline private
Definition at line 6 of file gameplayeffectwidgets_base.c.
{m_MaskWidgetUpdateCount = 0};
ResetSequence()
protected void Managed::ResetSequence () inline private
Definition at line 145 of file bleedingindicator.c.
    {
        m_CurrentDropProbabilityStep = 0;
        m_TimeElapsedSequence = 0;
        m_DropSpawnsQueued = 0;
    }
Referenced by Update().
SaveCharName()
void Managed::SaveCharName (string name) inline private
Definition at line 457 of file introscenecharacter.c.
    {
        if (IsDefaultCharacter())
        {
            GetGame().GetMenuDefaultCharacterData().SetCharacterName(name);
        }
        else
        {
            m_CharacterDta.SetCharacterName(m_CharacterId, name);
        }
        m_CharacterDta.SaveCharactersLocal();
    }
References GetGame(), CGame::GetMenuDefaultCharacterData(), IsDefaultCharacter(), name, MenuData::SaveCharactersLocal(), MenuData::SetCharacterName(), and MenuDefaultCharacterData::SetCharacterName().
SaveDefaultCharacter()
void Managed::SaveDefaultCharacter () inline private
Definition at line 473 of file introscenecharacter.c.
    {
        //if (m_CharacterObj)
        {
            m_CharacterDta.RequestSetDefaultCharacterData();
        }
    }
References MenuData::RequestSetDefaultCharacterData().
SendInitValues()
void Managed::SendInitValues () inline private
Sends values on object creation.
Definition at line 159 of file transfervalues.c.
    {
        m_InitialSyncSent = true;
        //HP
        float health_current = m_Player.GetHealth("","Health");
        float health_normalized = health_current / m_HealthMaxValue;
        SendValue(TYPE_HEALTH, health_normalized);
        m_LastHealthUpdate = health_normalized;
        //Blood
        float blood_current = m_Player.GetHealth("","Blood");
        float blood_normalized = Math.InverseLerp(BLOOD_THRESHOLD_LOW, m_BloodMaxValue, blood_current);
        blood_normalized = Math.Clamp(blood_normalized,0,1);
        //Print("DbgBlood | SendInitValues | blood_normalized: " + blood_normalized);
        SendValue(TYPE_BLOOD, blood_normalized);
        m_LastBloodUpdate = blood_normalized;
    }
References Math::Clamp(), Math::InverseLerp(), m_HealthMaxValue, m_LastHealthUpdate, m_Player, and SendValue().
Referenced by OnScheduledTick().
SendValue()
void Managed::SendValue (int value_type, float value) inline private
Definition at line 178 of file transfervalues.c.
    {
        CachedObjectsParams.PARAM2_INT_FLOAT.param1 = value_type;
        CachedObjectsParams.PARAM2_INT_FLOAT.param2 = value;
        GetGame().RPCSingleParam(m_Player, ERPCs.RPC_DAMAGE_VALUE_SYNC, CachedObjectsParams.PARAM2_INT_FLOAT, true, m_Player.GetIdentity());
    }
References GetGame(), m_Player, CachedObjectsParams::PARAM2_INT_FLOAT, and CGame::RPCSingleParam().
Referenced by CheckBlood(), CheckHealth(), and SendInitValues().
SetAttachment()
void Managed::SetAttachment (string type, int slot) inline private
Definition at line 409 of file introscenecharacter.c.
    {
        if ( !m_CharacterObj )
        {
            return;
        }
        g_Game.ObjectDelete(m_CharacterObj.GetInventory().FindAttachment(slot));
        EntityAI entity = EntityAI.Cast( g_Game.CreateObjectEx(type, m_CharacterObj.GetPosition(), ECE_PLACE_ON_SURFACE) );
        if (entity)
        {
            m_CharacterObj.LocalTakeEntityAsAttachmentEx(entity, slot);
        }
    }
References ECE_PLACE_ON_SURFACE, and g_Game.
SetBreathIntensityStamina()
void Managed::SetBreathIntensityStamina (float stamina_cap, float stamina_current) inline private
Definition at line 20 of file gameplayeffectwidgets_base.c.
{}
SetCharacterGender()
void Managed::SetCharacterGender (ECharGender gender) inline private
Definition at line 105 of file introscenecharacter.c.
    {
        m_CharGender = gender;
    }
Referenced by CreateNewCharacterRandom(), and LoadCharacterData().
SetCharacterID()
void Managed::SetCharacterID (int char_id) inline private
Definition at line 41 of file introscenecharacter.c.
    {
        m_CharacterId = char_id;
    }
Referenced by CharacterLoad().
SetToDefaultCharacter()
void Managed::SetToDefaultCharacter () inline private
Definition at line 34 of file introscenecharacter.c.
    {
        m_CharacterId = GameConstants.DEFAULT_CHARACTER_MENU_ID;
    }
References GameConstants::DEFAULT_CHARACTER_MENU_ID.
SetupPlayerName()
protected void Managed::SetupPlayerName (bool new_name) inline private
Definition at line 382 of file introscenecharacter.c.
    {
        string name = GameConstants.DEFAULT_CHARACTER_NAME;
#ifdef PLATFORM_CONSOLE
        BiosUserManager user_manager = GetGame().GetUserManager();
        if( user_manager )
        {
            BiosUser user = user_manager.GetSelectedUser();
            if( user )
            {
                name = user.GetName();
            }
        }
#else
        if ( !new_name )
        {
            m_CharacterDta.GetCharacterName(m_CharacterId, name);
        }
#endif
        g_Game.SetPlayerGameName(name);
    }
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, MenuData::GetCharacterName(), GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
Referenced by CreateNewCharacter().
ShowDebugValues()
void Managed::ShowDebugValues (bool show) inline private
Definition at line 208 of file transfervalues.c.
    {
        #ifdef DEVELOPER
        if( show )
        {
            DbgUI.BeginCleanupScope();
            DbgUI.Begin("Values", 50, 50);
            DbgUI.Text("Blood: " + m_BloodClient.ToString());
            DbgUI.Text("Health: " + m_HealthClient.ToString());
            DbgUI.End();
            DbgUI.EndCleanupScope();
        }
        else
        {
            DbgUI.BeginCleanupScope();
            DbgUI.Begin("Values", 50, 50);
            DbgUI.End();
            DbgUI.EndCleanupScope();
        }
        #endif
    }
References DbgUI::Begin(), DbgUI::BeginCleanupScope(), DbgUI::End(), DbgUI::EndCleanupScope(), DbgUI::Text(), and float::ToString().
Referenced by OnScheduledTick().
StartRunningDrops()
protected void Managed::StartRunningDrops () inline private
Definition at line 112 of file bleedingindicator.c.
    {
        m_ActiveDropsCount = 0;
        m_IsRunning = true;
        TrySpawnNextDrop();
        m_DropSpawnsQueued = 0;
        m_CurrentDropProbabilityStep = (int)(m_DropProbabilityRollsCount - (m_DropProbabilityRollsCount / m_AverageFrequency));
    }
References int, m_IsRunning, and TrySpawnNextDrop().
Referenced by Update().
StopAllEffects()
void Managed::StopAllEffects () inline private
Definition at line 12 of file gameplayeffectwidgets_base.c.
{}
StopIndicator()
void Managed::StopIndicator (bool instant = false) inline private
Definition at line 98 of file bleedingindicator.c.
    {
        if (!m_Terminating)
        {
            m_IsRunning = false;
            if (instant)
            {
                m_EndNow = true;
            }
            m_Terminating = true;
        }
    }
References m_IsRunning.
TransferValues()
void Managed::TransferValues (PlayerBase player) inline private
Definition at line 28 of file transfervalues.c.
    {
        m_Player = player;
        m_InitialSyncSent = false;
        Init();
    }
References Init(), and m_Player.
TrySpawnNextDrop()
void Managed::TrySpawnNextDrop () inline private
Definition at line 128 of file bleedingindicator.c.
    {
        ImageWidget dropImage;
        if (Class.CastTo(dropImage,m_ParentMetaData.GetNextDropImage()) && !dropImage.IsVisible()) //IsVisible false means the drop is free to be used
        {
            BleedingIndicatorDropData data = new BleedingIndicatorDropData(dropImage,m_Severity);
            data.SetBasePosition(m_BasePosition);
            data.StartDrop();
            m_ActiveDrops.Insert(data);
            m_ActiveDropsCount++;
        }
        m_LastDropSpawnTime = m_TimeElapsedTotal;
        m_DropSpawnsQueued--;
    }
References Class::CastTo(), m_TimeElapsedTotal, BleedingIndicatorDropData::SetBasePosition(), and BleedingIndicatorDropData::StartDrop().
Referenced by StartRunningDrops(), and Update().
Update() [1/3]
void Managed::Update (float timeSlice) inline private
Definition at line 18 of file gameplayeffectwidgets_base.c.
{}
Update() [2/3]
void Managed::Update (float timeSlice) inline private
Definition at line 163 of file bleedingindicator.c.
    {
        if ( !m_Initialized )
        {
            return;
        }
#ifdef DEVELOPER
        if (DbgBleedingIndicationStaticInfo.m_DbgUseOverrideValues)
        {
            m_SequenceDuration = DbgBleedingIndicationStaticInfo.m_DbgSequenceDuration;
        }
#endif
        m_SequenceTick = m_SequenceDuration / m_DropProbabilityRollsCount;
        //run drops, if possible
        if (!m_Terminating)
        {
            if (m_IsRunning)
            {
                if (m_TimeElapsedSequence > (m_SequenceTick * m_CurrentDropProbabilityStep))
                {
                    if (m_CurrentDropProbabilityStep < m_DropProbabilityRollsCount)
                    {
                        float rnd = Math.RandomFloat01();
                        if (rnd < m_DropProbabilityArray[m_CurrentDropProbabilityStep])
{
                            m_DropSpawnsQueued++;
                        }
                        m_CurrentDropProbabilityStep++;
                    }
                }
                float sinceLastDrop = m_TimeElapsedTotal - m_LastDropSpawnTime;
                if (m_TimeElapsedSequence > m_SequenceDuration)
                {
                    ResetSequence();
                }
                else if (m_DropSpawnsQueued > 0) //spawn queued drop
                {
                    if (sinceLastDrop >= m_DropSpawnMinDelay)
                    {
                        TrySpawnNextDrop();
                    }
                }
                else if (sinceLastDrop > m_DropSpawnMaxDelay)
                {
                    TrySpawnNextDrop(); //guaranteed drop
                    m_CurrentDropProbabilityStep++; //substitutes a regular roll..
                }
            }
            else //1st drop ignores delay
            {
                StartRunningDrops();
            }
        }
        for (int i = 0; i < m_ActiveDropsCount; i++)
        {
            if (!m_EndNow)
            {
                //Simulate drops
                m_ActiveDrops[i].Update(timeSlice);
            }
            else
            {
                m_ActiveDrops[i].StopDrop();
            }
            if (!m_ActiveDrops[i].IsRunning())
            {
                m_CleanupQueue.Insert(i);
            }
        }
        //Cleanup drops
        for (i = m_CleanupQueue.Count() - 1; i >= 0; i--)
        {
            m_ActiveDrops.Remove(m_CleanupQueue[i]);
            m_ActiveDropsCount--;
        }
        m_CleanupQueue.Clear();
        if (m_Terminating && !IsRunningDrops())
        {
            m_EndNow = true;
        }
        m_TimeElapsedTotal += timeSlice;
        m_TimeElapsedSequence += timeSlice;
    }
References IsRunning(), IsRunningDrops(), m_ActiveDropsCount, DbgBleedingIndicationStaticInfo::m_DbgSequenceDuration, DbgBleedingIndicationStaticInfo::m_DbgUseOverrideValues, m_DropProbabilityRollsCount, m_Initialized, m_IsRunning, m_LastDropSpawnTime, Math::RandomFloat01(), ResetSequence(), StartRunningDrops(), and TrySpawnNextDrop().
Update() [3/3]
void Managed::Update (float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 66 of file gewidgetsmetadata.c.
{}
UpdateVisibility()
void Managed::UpdateVisibility (bool state) inline private
Definition at line 64 of file gewidgetsmetadata.c.
{}
UpdateWidgets()
void Managed::UpdateWidgets (int type = -1, float timeSlice = 0, Param p = null, int handle = -1) inline private
Definition at line 17 of file gameplayeffectwidgets_base.c.
{}
VerifyRequester()
static bool Managed::VerifyRequester (PPERequesterBase req) inline static private
Verifies the instance.
Definition at line 191 of file pperequesterbank.c.
    {
        if (!m_Initialized) //initial registrations are fair game
        {
            return true;
        }
        PPERequesterBase temp;
        for (int i = 0; i < m_Instances.Count(); i++)
        {
            temp = m_Instances.GetElement(i);
            if (temp == req)
            {
                return true;
            }
        }
        //Error("Requester instance " + req + " not valid! Please use registered instances from PPERequesterBank.");
        Debug.Log("Requester instance '" + req + "' not valid! Please use registered instances from PPERequesterBank.");
        return false;
    }
References Debug::Log(), m_Initialized, and m_Instances.
Member Data Documentation
BLOOD_THRESHOLD_LOW
const int Managed::BLOOD_THRESHOLD_LOW = 3000 private
Definition at line 10 of file transfervalues.c.
INVALID
const int Managed::INVALID = -1 static private
Definition at line 11 of file pperequesterbank.c.
m_ActiveDrops
ref set<ref BleedingIndicatorDropData> Managed::m_ActiveDrops private
Definition at line 28 of file bleedingindicator.c.
m_ActiveDropsCount
protected int Managed::m_ActiveDropsCount private
Definition at line 10 of file bleedingindicator.c.
Referenced by Update().
m_AnimType
int Managed::m_AnimType private
Definition at line 4 of file synchitinfo.c.
Referenced by DayZPlayerSyncJunctures::SendDamageHitEx().
m_AverageFrequency
protected float Managed::m_AverageFrequency private
Definition at line 16 of file bleedingindicator.c.
m_BasePosition
protected vector Managed::m_BasePosition private
Definition at line 26 of file bleedingindicator.c.
m_BloodClient
float Managed::m_BloodClient private
Definition at line 23 of file transfervalues.c.
Referenced by GetBlood().
m_BloodMaxValue
float Managed::m_BloodMaxValue private
Definition at line 21 of file transfervalues.c.
m_CharacterDta
protected MenuData Managed::m_CharacterDta private
Definition at line 5 of file introscenecharacter.c.
m_CharacterId
protected int Managed::m_CharacterId private
Definition at line 3 of file introscenecharacter.c.
Referenced by GetCharacterID().
m_CharacterObj
protected PlayerBase Managed::m_CharacterObj private
Definition at line 6 of file introscenecharacter.c.
Referenced by GetCharacterObj().
m_CharacterPos
protected vector Managed::m_CharacterPos private
Definition at line 7 of file introscenecharacter.c.
m_CharacterRot
protected vector Managed::m_CharacterRot private
Definition at line 8 of file introscenecharacter.c.
m_Characters
protected ref map<ECharGender, ref array<string> > Managed::m_Characters = new map<ECharGender, ref array<string>> private
Definition at line 15 of file introscenecharacter.c.
m_CharacterType
protected string Managed::m_CharacterType private
Definition at line 4 of file introscenecharacter.c.
m_CharGender
protected ECharGender Managed::m_CharGender private
Definition at line 17 of file introscenecharacter.c.
Referenced by GetCharacterGender().
m_CharGenderList
protected ref TStringArray Managed::m_CharGenderList = new TStringArray private
Definition at line 10 of file introscenecharacter.c.
Referenced by GetCharGenderList().
m_CharPantsList
protected ref TStringArray Managed::m_CharPantsList = new TStringArray private
Definition at line 12 of file introscenecharacter.c.
Referenced by GetCharPantsList().
m_CharShirtList
protected ref TStringArray Managed::m_CharShirtList = new TStringArray private
Definition at line 11 of file introscenecharacter.c.
Referenced by GetCharShirtsList().
m_CharShoesList
protected ref TStringArray Managed::m_CharShoesList = new TStringArray private
Definition at line 13 of file introscenecharacter.c.
Referenced by GetCharShoesList().
m_CleanupQueue
ref set<int> Managed::m_CleanupQueue private
Definition at line 29 of file bleedingindicator.c.
m_CurrentDropProbabilityStep
protected int Managed::m_CurrentDropProbabilityStep private
Definition at line 24 of file bleedingindicator.c.
m_DropProbabilityArray
protected array<float> Managed::m_DropProbabilityArray private
Definition at line 14 of file bleedingindicator.c.
m_DropProbabilityRollsCount
protected int Managed::m_DropProbabilityRollsCount private
Definition at line 25 of file bleedingindicator.c.
Referenced by Update().
m_DropSpawnMaxDelay
protected float Managed::m_DropSpawnMaxDelay private
Definition at line 23 of file bleedingindicator.c.
m_DropSpawnMinDelay
protected float Managed::m_DropSpawnMinDelay private
Definition at line 22 of file bleedingindicator.c.
m_DropSpawnsQueued
protected int Managed::m_DropSpawnsQueued private
Definition at line 9 of file bleedingindicator.c.
m_EndNow
protected bool Managed::m_EndNow = false private
Definition at line 7 of file bleedingindicator.c.
Referenced by GetEndNow().
m_Fullbody
bool Managed::m_Fullbody private
Definition at line 7 of file synchitinfo.c.
m_HasSource
bool Managed::m_HasSource private
Definition at line 9 of file synchitinfo.c.
m_HealthClient
float Managed::m_HealthClient private
Definition at line 24 of file transfervalues.c.
Referenced by GetHealth().
m_HealthDamage
float Managed::m_HealthDamage private
Definition at line 6 of file synchitinfo.c.
m_HealthMaxValue
float Managed::m_HealthMaxValue private
Definition at line 20 of file transfervalues.c.
Referenced by CheckHealth(), and SendInitValues().
m_HitDir
float Managed::m_HitDir private
Definition at line 5 of file synchitinfo.c.
m_Initialized [1/2]
private bool Managed::m_Initialized = false static private
Definition at line 7 of file pperequesterbank.c.
m_Initialized [2/2]
protected bool Managed::m_Initialized private
Definition at line 5 of file bleedingindicator.c.
m_InitialSyncSent
protected bool Managed::m_InitialSyncSent private
Definition at line 26 of file transfervalues.c.
m_Instances
private ref map<int,ref PPERequesterBase> Managed::m_Instances static private
Definition at line 6 of file pperequesterbank.c.
m_IsRunning
protected bool Managed::m_IsRunning = false private
Definition at line 8 of file bleedingindicator.c.
m_LastBloodUpdate
float Managed::m_LastBloodUpdate private
Definition at line 15 of file transfervalues.c.
Referenced by CheckBlood().
m_LastDropSpawnTime
protected float Managed::m_LastDropSpawnTime private
Definition at line 21 of file bleedingindicator.c.
Referenced by Update().
m_LastHealthUpdate
float Managed::m_LastHealthUpdate private
Definition at line 14 of file transfervalues.c.
Referenced by CheckHealth().
m_lastID
int Managed::m_lastID = -1 static private
Definition at line 9 of file pperequesterbank.c.
Referenced by RegisterRequester().
m_LayoutRoot
Widget Managed::m_LayoutRoot private
Definition at line 11 of file gewidgetsmetadata.c.
m_MaskWidgetUpdateCount
int Managed::m_MaskWidgetUpdateCount private
Definition at line 3 of file gameplayeffectwidgets_base.c.
m_ParentMetaData
protected GameplayEffectsDataBleeding Managed::m_ParentMetaData private
Definition at line 13 of file bleedingindicator.c.
m_Player
PlayerBase Managed::m_Player private
Definition at line 11 of file transfervalues.c.
m_Registrations
private ref PPERequesterRegistrations Managed::m_Registrations static private
Definition at line 45 of file pperequesterbank.c.
Referenced by Cleanup().
m_SequenceDuration
protected float Managed::m_SequenceDuration private
Definition at line 18 of file bleedingindicator.c.
m_SequenceTick
protected float Managed::m_SequenceTick private
Definition at line 17 of file bleedingindicator.c.
m_Severity
protected int Managed::m_Severity private
Definition at line 11 of file bleedingindicator.c.
Referenced by GetSeverity().
m_SourceID
protected int Managed::m_SourceID private
Definition at line 12 of file bleedingindicator.c.
m_Terminating
protected bool Managed::m_Terminating = false private
Definition at line 6 of file bleedingindicator.c.
m_TimeElapsedSequence
protected float Managed::m_TimeElapsedSequence private
Definition at line 20 of file bleedingindicator.c.
m_TimeElapsedTotal
protected float Managed::m_TimeElapsedTotal private
Definition at line 19 of file bleedingindicator.c.
Referenced by TrySpawnNextDrop().
m_TimeSinceLastTick
float Managed::m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1 private
Definition at line 12 of file transfervalues.c.
m_Type
int Managed::m_Type private
Definition at line 9 of file gewidgetsmetadata.c.
m_WidgetArray
protected ref array<ref Widget> Managed::m_WidgetArray private
Definition at line 8 of file gewidgetsmetadata.c.
m_WidgetSetIdentifier
int Managed::m_WidgetSetIdentifier private
Definition at line 10 of file gewidgetsmetadata.c.
REQ_BLOODLOSS
const int Managed::REQ_BLOODLOSS = RegisterRequester(PPERequester_BloodLoss) static private
Definition at line 25 of file pperequesterbank.c.
REQ_BURLAPSACK
const int Managed::REQ_BURLAPSACK = RegisterRequester(PPERequester_BurlapSackEffects) static private
Definition at line 29 of file pperequesterbank.c.
REQ_CAMERAADS
const int Managed::REQ_CAMERAADS = RegisterRequester(PPERequester_CameraADS) static private
Definition at line 24 of file pperequesterbank.c.
REQ_CAMERANV
const int Managed::REQ_CAMERANV = RegisterRequester(PPERequester_CameraNV) static private
Definition at line 23 of file pperequesterbank.c.
REQ_CONTAMINATEDAREA
const int Managed::REQ_CONTAMINATEDAREA = RegisterRequester(PPERequester_ContaminatedAreaTint) static private
Definition at line 39 of file pperequesterbank.c.
REQ_CONTROLLERBLUR
const int Managed::REQ_CONTROLLERBLUR = RegisterRequester(PPERequester_ControlsBlur) static private
Definition at line 36 of file pperequesterbank.c.
REQ_CONTROLLERDISCONNECT
const int Managed::REQ_CONTROLLERDISCONNECT = RegisterRequester(PPERequester_ControllerDisconnectBlur) static private
Definition at line 13 of file pperequesterbank.c.
REQ_DEATHEFFECTS
const int Managed::REQ_DEATHEFFECTS = RegisterRequester(PPERequester_DeathDarkening) static private
Definition at line 26 of file pperequesterbank.c.
REQ_DROWNING
const int Managed::REQ_DROWNING = RegisterRequester(PPERequester_Drowning) static private
Definition at line 43 of file pperequesterbank.c.
REQ_FEVEREFFECTS
const int Managed::REQ_FEVEREFFECTS = RegisterRequester(PPERequester_FeverEffects) static private
Definition at line 31 of file pperequesterbank.c.
REQ_FLASHBANGEFFECTS
const int Managed::REQ_FLASHBANGEFFECTS = RegisterRequester(PPERequester_FlashbangEffects) static private
Definition at line 32 of file pperequesterbank.c.
REQ_GLASSESAVIATOR
const int Managed::REQ_GLASSESAVIATOR = RegisterRequester(PPERequester_GlassesAviator) static private
Definition at line 18 of file pperequesterbank.c.
REQ_GLASSESDESIGNER
const int Managed::REQ_GLASSESDESIGNER = RegisterRequester(PPERequester_GlassesDesignerBlack) static private
Definition at line 19 of file pperequesterbank.c.
REQ_GLASSESSPORTBLACK
const int Managed::REQ_GLASSESSPORTBLACK = RegisterRequester(PPERequester_GlassesSportBlack) static private
Definition at line 14 of file pperequesterbank.c.
REQ_GLASSESSPORTBLUE
const int Managed::REQ_GLASSESSPORTBLUE = RegisterRequester(PPERequester_GlassesSportBlue) static private
Definition at line 15 of file pperequesterbank.c.
REQ_GLASSESSPORTGREEN
const int Managed::REQ_GLASSESSPORTGREEN = RegisterRequester(PPERequester_GlassesSportGreen) static private
Definition at line 16 of file pperequesterbank.c.
REQ_GLASSESSPORTORANGE
const int Managed::REQ_GLASSESSPORTORANGE = RegisterRequester(PPERequester_GlassesSportOrange) static private
Definition at line 17 of file pperequesterbank.c.
REQ_GLASSESTACTICAL
const int Managed::REQ_GLASSESTACTICAL = RegisterRequester(PPERequester_TacticalGoggles) static private
Definition at line 20 of file pperequesterbank.c.
REQ_GLASSESWELDING
const int Managed::REQ_GLASSESWELDING = RegisterRequester(PPERequester_WeldingMask) static private
Definition at line 22 of file pperequesterbank.c.
REQ_HEALTHHITEFFECTS
const int Managed::REQ_HEALTHHITEFFECTS = RegisterRequester(PPERequester_HealthHitReaction) static private
Definition at line 34 of file pperequesterbank.c.
REQ_INTROCHROMABB
const int Managed::REQ_INTROCHROMABB = RegisterRequester(PPERequester_IntroChromAbb) static private
Definition at line 30 of file pperequesterbank.c.
REQ_INVENTORYBLUR
const int Managed::REQ_INVENTORYBLUR = RegisterRequester(PPERequester_InventoryBlur) static private
Definition at line 12 of file pperequesterbank.c.
REQ_MENUEFFECTS
const int Managed::REQ_MENUEFFECTS = RegisterRequester(PPERequester_MenuEffects) static private
Definition at line 35 of file pperequesterbank.c.
REQ_MOTOHELMETBLACK
const int Managed::REQ_MOTOHELMETBLACK = RegisterRequester(PPERequester_MotoHelmetBlack) static private
Definition at line 21 of file pperequesterbank.c.
REQ_PAINBLUR
const int Managed::REQ_PAINBLUR = RegisterRequester(PPERequester_PainBlur) static private
Definition at line 41 of file pperequesterbank.c.
REQ_SERVERBROWSEREFFECTS
const int Managed::REQ_SERVERBROWSEREFFECTS = RegisterRequester(PPERequester_ServerBrowserBlur) static private
Definition at line 37 of file pperequesterbank.c.
REQ_SHOCKHITEFFECTS
const int Managed::REQ_SHOCKHITEFFECTS = RegisterRequester(PPERequester_ShockHitReaction) static private
Definition at line 33 of file pperequesterbank.c.
REQ_SPOOKYAREA
const int Managed::REQ_SPOOKYAREA = RegisterRequester(PPERequester_SpookyAreaTint) static private
Definition at line 40 of file pperequesterbank.c.
REQ_TUNELVISSION
const int Managed::REQ_TUNELVISSION = RegisterRequester(PPERequester_TunnelVisionEffects) static private
Definition at line 28 of file pperequesterbank.c.
REQ_TUTORIALEFFECTS
const int Managed::REQ_TUTORIALEFFECTS = RegisterRequester(PPERequester_TutorialMenu) static private
Definition at line 38 of file pperequesterbank.c.
REQ_UNCONEFFECTS
const int Managed::REQ_UNCONEFFECTS = RegisterRequester(PPERequester_UnconEffects) static private
Definition at line 27 of file pperequesterbank.c.
REQ_UNDERGROUND
const int Managed::REQ_UNDERGROUND = RegisterRequester(PPERUndergroundAcco) static private
Definition at line 42 of file pperequesterbank.c.
SENSITIVTY_PERCENTAGE
const float Managed::SENSITIVTY_PERCENTAGE = 1 private
Definition at line 8 of file transfervalues.c.
TYPE_BLOOD
const int Managed::TYPE_BLOOD = 2 private
Definition at line 5 of file transfervalues.c.
TYPE_HEALTH
const int Managed::TYPE_HEALTH = 1 private
Definition at line 4 of file transfervalues.c.
VALUE_CHECK_INTERVAL
const float Managed::VALUE_CHECK_INTERVAL = 5 private
Definition at line 7 of file transfervalues.c.