DayzKode: DayZPlayerCamera3rdPersonErcRaised Class Reference
DayZPlayerCamera3rdPersonErcRaised Class Reference
Private Member Functions
void DayZPlayerCamera3rdPersonErcRaisedMelee (DayZPlayer pPlayer, HumanInputController pInput)
void ~DayZPlayerCamera3rdPersonErcRaisedMelee ()
Detailed Description
Definition at line 350 of file dayzplayercamera3rdperson.c.
Constructor & Destructor Documentation
~DayZPlayerCamera3rdPersonErcRaisedMelee()
void DayZPlayerCamera3rdPersonErcRaised::~DayZPlayerCamera3rdPersonErcRaisedMelee () inline private
shift off override
Definition at line 360 of file dayzplayercamera3rdperson.c.
    {
        m_pInput.Override3rdIsRightShoulder(false, false);
    }
References m_pInput, and HumanInputController::Override3rdIsRightShoulder().
Member Function Documentation
DayZPlayerCamera3rdPersonErcRaisedMelee()
void DayZPlayerCamera3rdPersonErcRaised::DayZPlayerCamera3rdPersonErcRaisedMelee (DayZPlayer pPlayer, HumanInputController pInput) inline private
shift on override - stay at current state
Definition at line 352 of file dayzplayercamera3rdperson.c.
    {
        //Print("new camera: DayZPlayerCamera3rdPersonErcRaisedMelee");
        pInput.Override3rdIsRightShoulder(true, pInput.Camera3rdIsRightShoulder());
    }
References HumanInputController::Camera3rdIsRightShoulder(), and HumanInputController::Override3rdIsRightShoulder().