DayzKode: Land_Underground_Stairs_Exit Class Reference
Land_Underground_Stairs_Exit Class Reference
Private Member Functions
override void CleanUpOnClosedClient ()
override void CreateLights ()
override float GetOpeningTime ()
override void HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void Land_Underground_Stairs_Exit ()
override void OnDoorStateChangedServer (EUndegroundEntranceState newState)
void SoundEnded (Effect eff)
Private Attributes
const string CLOSING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Close_Loop_SoundSet"
const string CLOSING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Close_Start_SoundSet"
const string CLOSING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Close_End_SoundSet"
const string LOCKING_SOUNDSET = "UndergroundDoor_Lock_SoundSet"
EffectSound m_CloseSoundIn
EffectSound m_CloseSoundLoop
EffectSound m_CloseSoundOut
EffectSound m_LockingSound
EffectSound m_OpenSoundIn
EffectSound m_OpenSoundOut
const string OPENING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Open_Loop_SoundSet"
const string OPENING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Open_Start_SoundSet"
const string OPENING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Open_End_SoundSet"
Detailed Description
Definition at line 1 of file land_underground_stairs_exit.c.
Constructor & Destructor Documentation
Land_Underground_Stairs_Exit()
void Land_Underground_Stairs_Exit::Land_Underground_Stairs_Exit () inline private
Definition at line 22 of file land_underground_stairs_exit.c.
    {
        m_DoorType = EUndegroundDoorType.SMALL;
    }
References Land_Underground_EntranceBase::m_DoorType.
Member Function Documentation
CleanUpOnClosedClient()
override void Land_Underground_Stairs_Exit::CleanUpOnClosedClient () inline private
Definition at line 27 of file land_underground_stairs_exit.c.
    {
        SEffectManager.DestroySound(m_LockingSound);
        SEffectManager.DestroySound(m_OpenSoundIn);
        //SEffectManager.DestroySound(m_OpenSoundLoop);
        SEffectManager.DestroySound(m_OpenSoundOut);
        SEffectManager.DestroySound(m_CloseSoundIn);
        SEffectManager.DestroySound(m_CloseSoundLoop);
        SEffectManager.DestroySound(m_CloseSoundOut);
    }
References SEffectManager::DestroySound(), m_CloseSoundIn, m_CloseSoundLoop, m_CloseSoundOut, m_LockingSound, m_OpenSoundIn, and m_OpenSoundOut.
CreateLights()
override void Land_Underground_Stairs_Exit::CreateLights () inline private
Definition at line 106 of file land_underground_stairs_exit.c.
    {
        m_InteriorLight1 = EntranceLight.Cast(ScriptedLightBase.CreateLightAtObjMemoryPoint(EntranceLightStairs1, this, "Light1"));
        m_InteriorLight2 = EntranceLight.Cast(ScriptedLightBase.CreateLightAtObjMemoryPoint(EntranceLightStairs2, this, "Light2"));
    }
References EntranceLight(), EntranceLightStairs1(), Land_Underground_EntranceBase::m_InteriorLight1, and Land_Underground_EntranceBase::m_InteriorLight2.
GetOpeningTime()
override float Land_Underground_Stairs_Exit::GetOpeningTime () inline private
Definition at line 41 of file land_underground_stairs_exit.c.
    {
        return AdjustTime(3);
    }
References Land_Underground_EntranceBase::AdjustTime().
Referenced by OnDoorStateChangedServer().
HandleAudioPlayback()
override void Land_Underground_Stairs_Exit::HandleAudioPlayback (EUndegroundEntranceState newState, EUndegroundEntranceState prevState) inline private
Definition at line 77 of file land_underground_stairs_exit.c.
    {
        if (newState == EUndegroundEntranceState.OPENING_A)
        {
            PlaySoundSet( m_LockingSound, LOCKING_SOUNDSET, 0, 0 );
            PlaySoundSet( m_OpenSoundIn, OPENING_SOUNDSET_LOOP_IN, 0, 0 );
        }
        else if (newState == EUndegroundEntranceState.OPENING_B)
        {
            if (m_OpenSoundIn)
                m_OpenSoundIn.Stop();
            PlaySoundSet( m_OpenSoundOut, OPENING_SOUNDSET_LOOP_OUT, 0, 0 );
        }
        else if (newState == EUndegroundEntranceState.CLOSING_A)
        {
            PlaySoundSet( m_CloseSoundIn, CLOSING_SOUNDSET_LOOP_IN, 0, 0 );
            if(m_CloseSoundIn)
                m_CloseSoundIn.Event_OnEffectEnded.Insert(SoundEnded);
        }
        else if (newState == EUndegroundEntranceState.CLOSING_B)
        {
            if (m_CloseSoundLoop)
                m_CloseSoundLoop.Stop();
            PlaySoundSet( m_CloseSoundOut, CLOSING_SOUNDSET_LOOP_OUT, 0, 0 );
            PlaySoundSet( m_LockingSound, LOCKING_SOUNDSET, 0, 0 );
        }
    }
References CLOSING_SOUNDSET_LOOP_IN, CLOSING_SOUNDSET_LOOP_OUT, LOCKING_SOUNDSET, m_CloseSoundIn, m_CloseSoundLoop, m_CloseSoundOut, m_LockingSound, m_OpenSoundIn, m_OpenSoundOut, OPENING_SOUNDSET_LOOP_IN, OPENING_SOUNDSET_LOOP_OUT, PlaySoundSet(), SoundEnded(), and EffectSound::Stop().
OnDoorStateChangedServer()
override void Land_Underground_Stairs_Exit::OnDoorStateChangedServer (EUndegroundEntranceState newState) inline private
Definition at line 46 of file land_underground_stairs_exit.c.
    {
        switch (newState)
        {
            case EUndegroundEntranceState.OPENING_A:
                RequestLatentTransition(AdjustTime(1));
                SetAnimationPhase("EntranceDoor",1);
            break;
            case EUndegroundEntranceState.OPENING_B:
                GetGame().UpdatePathgraphRegionByObject(this);
                RequestLatentTransition(AdjustTime(6), EUndegroundEntranceState.CLOSING_A);
            break;
            case EUndegroundEntranceState.CLOSING_A:
                m_AnimTimerDoorServer = new AnimationTimer();
                m_AnimTimerDoorServer.Run(0, this, "OnUpdateServer", "OnFinishedTimerServer", GetOpeningTime(), false,1/ AdjustTime(1));
                RequestLatentTransition(AdjustTime(3));
            break;
            case EUndegroundEntranceState.CLOSING_B:
                RequestLatentTransition(AdjustTime(1), EUndegroundEntranceState.CLOSED);
                GetGame().UpdatePathgraphRegionByObject(this);
            break;
        }
    }
References Land_Underground_EntranceBase::AdjustTime(), GetGame(), GetOpeningTime(), Land_Underground_EntranceBase::m_AnimTimerDoorServer, Land_Underground_EntranceBase::RequestLatentTransition(), AnimationTimer::Run(), and CGame::UpdatePathgraphRegionByObject().
SoundEnded()
void Land_Underground_Stairs_Exit::SoundEnded (Effect eff) inline private
Definition at line 69 of file land_underground_stairs_exit.c.
    {
        if (eff == m_CloseSoundIn)
        {
            PlaySoundSetLoop( m_CloseSoundLoop, CLOSING_SOUNDSET_LOOP, 0, 0 );
        }
    }
References CLOSING_SOUNDSET_LOOP, m_CloseSoundIn, m_CloseSoundLoop, and PlaySoundSetLoop().
Referenced by HandleAudioPlayback().
Member Data Documentation
CLOSING_SOUNDSET_LOOP
const string Land_Underground_Stairs_Exit::CLOSING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Close_Loop_SoundSet" private
Definition at line 19 of file land_underground_stairs_exit.c.
Referenced by SoundEnded().
CLOSING_SOUNDSET_LOOP_IN
const string Land_Underground_Stairs_Exit::CLOSING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Close_Start_SoundSet" private
Definition at line 18 of file land_underground_stairs_exit.c.
Referenced by HandleAudioPlayback().
CLOSING_SOUNDSET_LOOP_OUT
const string Land_Underground_Stairs_Exit::CLOSING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Close_End_SoundSet" private
Definition at line 20 of file land_underground_stairs_exit.c.
Referenced by HandleAudioPlayback().
LOCKING_SOUNDSET
const string Land_Underground_Stairs_Exit::LOCKING_SOUNDSET = "UndergroundDoor_Lock_SoundSet" private
Definition at line 13 of file land_underground_stairs_exit.c.
Referenced by HandleAudioPlayback().
m_CloseSoundIn
EffectSound Land_Underground_Stairs_Exit::m_CloseSoundIn private
Definition at line 9 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), HandleAudioPlayback(), and SoundEnded().
m_CloseSoundLoop
EffectSound Land_Underground_Stairs_Exit::m_CloseSoundLoop private
Definition at line 10 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), HandleAudioPlayback(), and SoundEnded().
m_CloseSoundOut
EffectSound Land_Underground_Stairs_Exit::m_CloseSoundOut private
Definition at line 11 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_LockingSound
EffectSound Land_Underground_Stairs_Exit::m_LockingSound private
Definition at line 3 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_OpenSoundIn
EffectSound Land_Underground_Stairs_Exit::m_OpenSoundIn private
Definition at line 5 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
m_OpenSoundOut
EffectSound Land_Underground_Stairs_Exit::m_OpenSoundOut private
Definition at line 7 of file land_underground_stairs_exit.c.
Referenced by CleanUpOnClosedClient(), and HandleAudioPlayback().
OPENING_SOUNDSET_LOOP
const string Land_Underground_Stairs_Exit::OPENING_SOUNDSET_LOOP = "UndergroundSmallExitDoor_Open_Loop_SoundSet" private
Definition at line 15 of file land_underground_stairs_exit.c.
OPENING_SOUNDSET_LOOP_IN
const string Land_Underground_Stairs_Exit::OPENING_SOUNDSET_LOOP_IN = "UndergroundSmallExitDoor_Open_Start_SoundSet" private
Definition at line 14 of file land_underground_stairs_exit.c.
Referenced by HandleAudioPlayback().
OPENING_SOUNDSET_LOOP_OUT
const string Land_Underground_Stairs_Exit::OPENING_SOUNDSET_LOOP_OUT = "UndergroundSmallExitDoor_Open_End_SoundSet" private
Definition at line 16 of file land_underground_stairs_exit.c.
Referenced by HandleAudioPlayback().