DayzKode: EffectTrigger Class Reference
EffectTrigger Class Reference
Private Member Functions
override bool CanAddObjectAsInsider (Object object)
void EffectTrigger ()
override void EOnFrame (IEntity other, float timeSlice)
override string GetAmbientSoundsetName ()
string GetAmbientSoundsetName ()
override void OnEnterClientEvent (TriggerInsider insider)
override void OnEnterClientEvent (TriggerInsider insider)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnEnterServerEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnLeaveClientEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnLeaveServerEvent (TriggerInsider insider)
override void OnStayFinishServerEvent ()
override void OnStayServerEvent (TriggerInsider insider, float deltaTime)
override void OnStayStartServerEvent (int nrOfInsiders)
void SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx)
void SetupClientEffects (bool enable, notnull PlayerBase player)
override bool ShouldRemoveInsider (TriggerInsider insider)
Static Private Member Functions
static void TriggerEffect (EntityAI insider, typename triggerType)
Private Attributes
const float DAMAGE_TICK_RATE = 10
int m_AroundPartId
bool m_DealDamageFlag
float m_DeltaTime
TriggerEffectManager m_Manager
int m_PPERequester
float m_TimeAccuStay
int m_TinyPartId
Detailed Description
Definition at line 2 of file contaminatedtrigger.c.
Constructor & Destructor Documentation
EffectTrigger()
void EffectTrigger::EffectTrigger () inline private
Definition at line 13 of file effecttrigger.c.
    {
        RegisterNetSyncVariableInt("m_AroundPartId");
        RegisterNetSyncVariableInt("m_TinyPartId");
        RegisterNetSyncVariableInt("m_PPERequester");
        m_Manager = TriggerEffectManager.GetInstance();
        m_Manager.RegisterTriggerType( this );
    }
References TriggerEffectManager::GetInstance(), m_Manager, and TriggerEffectManager::RegisterTriggerType().
Member Function Documentation
CanAddObjectAsInsider()
override bool EffectTrigger::CanAddObjectAsInsider (Object object) inline private
Definition at line 68 of file effecttrigger.c.
    {
        DayZCreatureAI creature = DayZCreatureAI.Cast( object );
        if(creature)
        {
            return !creature.ResistContaminatedEffect();
        }
        else
        {
            PlayerBase player = PlayerBase.Cast(object);
            return player != null;
        }
    }
EOnFrame()
override void EffectTrigger::EOnFrame (IEntity other, float timeSlice) inline private
Definition at line 62 of file effecttrigger.c.
    {
        m_DeltaTime = timeSlice;
        super.EOnFrame(other, timeSlice);
    }
References m_DeltaTime.
GetAmbientSoundsetName() [1/2]
override string EffectTrigger::GetAmbientSoundsetName () inline private
Definition at line 96 of file contaminatedtrigger.c.
    {
        return "ContaminatedArea_SoundSet";
    }
Referenced by SetupClientEffects().
GetAmbientSoundsetName() [2/2]
string EffectTrigger::GetAmbientSoundsetName () inline private
Definition at line 37 of file effecttrigger.c.
    {
        return "";
    }
OnEnterClientEvent() [1/2]
override void EffectTrigger::OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 55 of file contaminatedtrigger.c.
    {
        super.OnEnterClientEvent( insider );
    }
OnEnterClientEvent() [2/2]
override void EffectTrigger::OnEnterClientEvent (TriggerInsider insider) inline private
Definition at line 103 of file effecttrigger.c.
    {
        super.OnEnterClientEvent( insider );
        if ( insider )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            // We will only handle the controlled player, as effects are only relevant to this player instance
            if (playerInsider && playerInsider.IsControlledPlayer() )
            {
                SetupClientEffects(true, playerInsider);
                // We then handle the update of player trigger state in manager
                m_Manager.OnPlayerEnter( playerInsider, this );
            }
        }
    }
References TriggerInsider::GetObject(), m_Manager, TriggerEffectManager::OnPlayerEnter(), and SetupClientEffects().
OnEnterServerEvent() [1/2]
override void EffectTrigger::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 10 of file contaminatedtrigger.c.
    {
        super.OnEnterServerEvent( insider );
        if ( insider )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            if ( playerInsider )
            {
                playerInsider.GetModifiersManager().ActivateModifier( eModifiers.MDF_AREAEXPOSURE );
            }
            else
            {
                DayZCreatureAI creature = DayZCreatureAI.Cast( insider.GetObject() );
                if(creature)
                    creature.IncreaseEffectTriggerCount();
            }
        }
    }
References TriggerInsider::GetObject().
OnEnterServerEvent() [2/2]
override void EffectTrigger::OnEnterServerEvent (TriggerInsider insider) inline private
Definition at line 84 of file effecttrigger.c.
    {
        super.OnEnterServerEvent( insider );
        // We don't need to test the trigger count as Modifiers handle such cases already
        if ( insider )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            if(playerInsider)
            {
                m_Manager.OnPlayerEnter( playerInsider, this );
            }
        }
    }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerEnter().
OnLeaveClientEvent() [1/2]
override void EffectTrigger::OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 60 of file contaminatedtrigger.c.
    {
        super.OnLeaveClientEvent( insider );
    }
OnLeaveClientEvent() [2/2]
override void EffectTrigger::OnLeaveClientEvent (TriggerInsider insider) inline private
Definition at line 137 of file effecttrigger.c.
    {
        super.OnLeaveClientEvent( insider );
        if ( insider )
        {
            // Make sure you pass the set variable for PPE effect
            // It will not remove the correct one if START and STOP don't point to the same Requester
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            // We will only handle the controlled player, as effects are only relevant to this player instance
            if ( playerInsider && playerInsider.IsControlledPlayer() )
            {
                // We first handle the update of player trigger state in manager
                m_Manager.OnPlayerExit( playerInsider, this );
                SetupClientEffects(false, playerInsider);
            }
        }
    }
References TriggerInsider::GetObject(), m_Manager, TriggerEffectManager::OnPlayerExit(), and SetupClientEffects().
OnLeaveServerEvent() [1/2]
override void EffectTrigger::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 33 of file contaminatedtrigger.c.
    {
        super.OnLeaveServerEvent( insider );
        if ( insider )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            if ( playerInsider && !m_Manager.IsPlayerInTriggerType( playerInsider, this ) )
            {
                playerInsider.GetModifiersManager().DeactivateModifier( eModifiers.MDF_AREAEXPOSURE );
            }
            else
            {
                DayZCreatureAI creature = DayZCreatureAI.Cast( insider.GetObject() );
                if(creature)
                    creature.DecreaseEffectTriggerCount();
            }
        }
    }
References TriggerInsider::GetObject(), and m_Manager.
OnLeaveServerEvent() [2/2]
override void EffectTrigger::OnLeaveServerEvent (TriggerInsider insider) inline private
Definition at line 122 of file effecttrigger.c.
    {
        super.OnLeaveServerEvent( insider );
        if ( insider )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            if ( playerInsider )
                m_Manager.OnPlayerExit( playerInsider, this );
        }
    }
References TriggerInsider::GetObject(), m_Manager, and TriggerEffectManager::OnPlayerExit().
OnStayFinishServerEvent()
override void EffectTrigger::OnStayFinishServerEvent () inline private
Definition at line 77 of file contaminatedtrigger.c.
    {
        if(m_DealDamageFlag)//the flag was previously set to true, the insiders have been updated at this point, reset the flag and the timer as well
        {
            m_TimeAccuStay = 0;
            m_DealDamageFlag = false;
        }
    }
OnStayServerEvent()
override void EffectTrigger::OnStayServerEvent (TriggerInsider insider, float deltaTime) inline private
Definition at line 86 of file contaminatedtrigger.c.
    {
        if ( m_DealDamageFlag )
        {
            DayZCreatureAI creature = DayZCreatureAI.Cast( insider.GetObject());
            if(creature && creature.m_EffectTriggerCount != 0)
                creature.DecreaseHealth("", "", GameConstants.AI_CONTAMINATION_DMG_PER_SEC * m_TimeAccuStay / creature.m_EffectTriggerCount);// we devide by m_EffectTriggerCount for multiple trigger presence(overlapping triggers)
        }
    }
References GameConstants::AI_CONTAMINATION_DMG_PER_SEC, and TriggerInsider::GetObject().
OnStayStartServerEvent()
override void EffectTrigger::OnStayStartServerEvent (int nrOfInsiders) inline private
Definition at line 66 of file contaminatedtrigger.c.
    {
        m_TimeAccuStay += m_DeltaTime;
        if (m_TimeAccuStay > DAMAGE_TICK_RATE)
        {
            m_DealDamageFlag = true;
            //this is where we would normally reset the m_TimeAccuStay, but we need the value as deltaT when dealing damage to the insiders, so we reset it only after the insider update in OnStayFinishServerEvent
        }
    }
References m_DeltaTime.
SetLocalEffects()
void EffectTrigger::SetLocalEffects (int aroundPartId, int tinyPartId, int ppeRequesterIdx) inline private
Definition at line 27 of file effecttrigger.c.
    {
        m_AroundPartId = aroundPartId;
        m_TinyPartId = tinyPartId;
        m_PPERequester = ppeRequesterIdx;
        SetSynchDirty();
    }
References m_AroundPartId, m_PPERequester, and m_TinyPartId.
Referenced by EffectArea::CreateTrigger().
SetupClientEffects()
void EffectTrigger::SetupClientEffects (bool enable, notnull PlayerBase player) inline private
Definition at line 42 of file effecttrigger.c.
    {
        if ( !m_Manager.IsPlayerInTriggerType( player, this ) )
        {
            if (enable)
            {
                player.SetContaminatedEffectEx( true, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName() );
            }
            else
            {
                player.SetContaminatedEffectEx( false, m_PPERequester );
            }
        }
    }
References GetAmbientSoundsetName(), TriggerEffectManager::IsPlayerInTriggerType(), m_AroundPartId, m_Manager, m_PPERequester, and m_TinyPartId.
Referenced by OnEnterClientEvent(), and OnLeaveClientEvent().
ShouldRemoveInsider()
override bool EffectTrigger::ShouldRemoveInsider (TriggerInsider insider) inline private
Definition at line 158 of file effecttrigger.c.
    {
        return !insider.GetObject().IsAlive();
    }
References TriggerInsider::GetObject().
TriggerEffect()
static void EffectTrigger::TriggerEffect (EntityAI insider, typename triggerType) inline static private
Definition at line 165 of file effecttrigger.c.
{}
Member Data Documentation
DAMAGE_TICK_RATE
const float EffectTrigger::DAMAGE_TICK_RATE = 10 private
Definition at line 4 of file contaminatedtrigger.c.
m_AroundPartId
int EffectTrigger::m_AroundPartId private
Definition at line 5 of file effecttrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().
m_DealDamageFlag
bool EffectTrigger::m_DealDamageFlag private
Definition at line 10 of file effecttrigger.c.
m_DeltaTime
float EffectTrigger::m_DeltaTime private
Definition at line 8 of file effecttrigger.c.
Referenced by EOnFrame(), and OnStayStartServerEvent().
m_Manager
TriggerEffectManager EffectTrigger::m_Manager private
Definition at line 11 of file effecttrigger.c.
Referenced by EffectTrigger(), OnEnterClientEvent(), OnEnterServerEvent(), OnLeaveClientEvent(), OnLeaveServerEvent(), and SetupClientEffects().
m_PPERequester
int EffectTrigger::m_PPERequester private
Definition at line 7 of file effecttrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().
m_TimeAccuStay
float EffectTrigger::m_TimeAccuStay private
Definition at line 9 of file effecttrigger.c.
m_TinyPartId
int EffectTrigger::m_TinyPartId private
Definition at line 6 of file effecttrigger.c.
Referenced by SetLocalEffects(), and SetupClientEffects().