DayzKode: ActionRepairTentPart Class Reference
ActionRepairTentPart Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionRepairTentPart ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasTarget ()
override bool IsUsingProxies ()
override void OnFinishProgressServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Private Attributes
string m_CurrentDamageZone = ""
int m_LastValidComponentIndex = -1
m_LastValidType
Detailed Description
Definition at line 19 of file actionrepairtentpart.c.
Constructor & Destructor Documentation
ActionRepairTentPart()
void ActionRepairTentPart::ActionRepairTentPart () inline private
Definition at line 25 of file actionrepairtentpart.c.
    {
        m_CallbackClass = ActionRepairTentPartCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#repair";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepairTentPart::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 52 of file actionrepairtentpart.c.
    {
        //m_CurrentDamageZone = "";
        Object targetObject = target.GetObject();
        Object targetParent = target.GetParent();
        if ( !targetParent || !targetParent.IsInherited(TentBase) )
            return false;
        if ( player && targetObject && targetParent )
        {
            array<string> selections = new array<string>;
            PluginRepairing module_repairing;
            Class.CastTo(module_repairing, GetPlugin(PluginRepairing));
            targetObject.GetActionComponentNameList(target.GetComponentIndex(), selections, "view");
            TentBase tent = TentBase.Cast( targetParent );
            if (m_LastValidType != targetObject.Type() || m_LastValidComponentIndex != target.GetComponentIndex() || m_CurrentDamageZone == "" || m_CurrentDamageZone == "Body")
            {
                string damageZone = "";
                for (int s = 0; s < selections.Count(); s++)
                {
                    if ( DamageSystem.GetDamageZoneFromComponentName(tent, selections[s], damageZone) ) //NOTE: relevant fire geometry and view geometry selection names MUST match in order to get a valid damage zone
                    {
                        //Print("#" + s + " damageZone: " + damageZone);
                        if (tent.GetHealthLevel("" + damageZone) == GameConstants.STATE_RUINED )
{
                            m_CurrentDamageZone = damageZone;
                            m_LastValidComponentIndex = target.GetComponentIndex();
                            break;
                        }else
                            continue;
                    }
                }
                if ( damageZone != "" && m_CurrentDamageZone != "Body" ) //This may seem like a duplicate but is required to work properly
                {
                    m_CurrentDamageZone = damageZone;
                    m_LastValidComponentIndex = target.GetComponentIndex();
                }
            }
            if ( m_CurrentDamageZone != "" && m_CurrentDamageZone != "Body" && tent.GetHealthLevel("" + damageZone) == GameConstants.STATE_RUINED )
            {
                return true;
            }
        }
        return false;
    }
References Class::CastTo(), GetPlugin(), m_CurrentDamageZone, m_LastValidComponentIndex, m_LastValidType, and GameConstants::STATE_RUINED.
CreateActionData()
override ActionData ActionRepairTentPart::CreateActionData () inline private
Definition at line 131 of file actionrepairtentpart.c.
    {
        RepairTentPartActionData action_data = new RepairTentPartActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionRepairTentPart::CreateConditionComponents () inline private
Definition at line 36 of file actionrepairtentpart.c.
    {
        m_ConditionItem = new CCINonRuined; //To change?
        m_ConditionTarget = new CCTCursorParent(UAMaxDistances.DEFAULT);
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
HandleReciveData()
override void ActionRepairTentPart::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 169 of file actionrepairtentpart.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        RepairTentPartActionReciveData recive_data_repair = RepairTentPartActionReciveData.Cast(action_recive_data);
        RepairTentPartActionData.Cast(action_data).m_DamageZone = recive_data_repair.m_DamageZoneRecived;
    }
References RepairTentPartActionReciveData::m_DamageZoneRecived.
HasTarget()
override bool ActionRepairTentPart::HasTarget () inline private
Definition at line 47 of file actionrepairtentpart.c.
    {
        return true;
    }
Referenced by ReadFromContext(), and WriteToContext().
IsUsingProxies()
override bool ActionRepairTentPart::IsUsingProxies () inline private
Definition at line 42 of file actionrepairtentpart.c.
    {
        return true;
    }
OnFinishProgressServer()
override void ActionRepairTentPart::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 101 of file actionrepairtentpart.c.
    {
        Object targetParent = action_data.m_Target.GetParent();
        ItemBase usedItem = action_data.m_MainItem;
        string damageZone = RepairTentPartActionData.Cast(action_data).m_DamageZone;
        if (!GetGame().IsMultiplayer())
            damageZone = m_CurrentDamageZone;
        if ( targetParent && targetParent.IsInherited(TentBase) && damageZone != "" )
        {
            TentBase tent = TentBase.Cast( targetParent );
            float m_RepairedLevel = usedItem.GetHealthLevel();
            tent.SetAllowDamage(true);
            targetParent.SetHealth01("" + damageZone, "", targetParent.GetHealthLevelValue(m_RepairedLevel));
            tent.ProcessInvulnerabilityCheck(tent.GetInvulnerabilityTypeString());
            if (usedItem.GetQuantity() > 1)
            {
                //Not really clean, but will do for now
                int val = usedItem.GetQuantity();
                val--;
                usedItem.SetQuantity(val);
            }
            else
                usedItem.Delete();
        }
    }
References GetGame(), m_CurrentDamageZone, ActionData::m_MainItem, and ActionData::m_Target.
ReadFromContext()
override bool ActionRepairTentPart::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 149 of file actionrepairtentpart.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new RepairTentPartActionReciveData;
        }
        super.ReadFromContext(ctx, action_recive_data);
        RepairTentPartActionReciveData recive_data_repair = RepairTentPartActionReciveData.Cast(action_recive_data);
        if( HasTarget() )
        {
            string zone;
            if ( !ctx.Read(zone) )
                return false;
            recive_data_repair.m_DamageZoneRecived = zone;
        }
        return true;
    }
References HasTarget(), RepairTentPartActionReciveData::m_DamageZoneRecived, and Serializer::Read().
WriteToContext()
override void ActionRepairTentPart::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 137 of file actionrepairtentpart.c.
    {
        super.WriteToContext(ctx, action_data);
        RepairTentPartActionData repair_action_data;
        if( HasTarget() && Class.CastTo(repair_action_data,action_data) )
        {
            repair_action_data.m_DamageZone = m_CurrentDamageZone;
            ctx.Write(repair_action_data.m_DamageZone);
        }
    }
References Class::CastTo(), HasTarget(), m_CurrentDamageZone, and Serializer::Write().
Member Data Documentation
m_CurrentDamageZone
string ActionRepairTentPart::m_CurrentDamageZone = "" private
Definition at line 22 of file actionrepairtentpart.c.
Referenced by ActionCondition(), OnFinishProgressServer(), and WriteToContext().
m_LastValidComponentIndex
int ActionRepairTentPart::m_LastValidComponentIndex = -1 private
Definition at line 23 of file actionrepairtentpart.c.
Referenced by ActionCondition().
m_LastValidType
ActionRepairTentPart::m_LastValidType private
Definition at line 21 of file actionrepairtentpart.c.
Referenced by ActionCondition().