DayzKode: ActionHandsPartSwitch Class Reference
ActionHandsPartSwitch Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionHandsPartSwitch ()
override void CreateConditionComponents ()
override GetInputType ()
override bool IsInstant ()
override void OnStartClient (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool RemoveForceTargetAfterUse ()
void SetNextIndex (ActionData action_data)
override bool UseAcknowledgment ()
Detailed Description
Definition at line 2 of file actionhandspartswitch.c.
Constructor & Destructor Documentation
ActionHandsPartSwitch()
void ActionHandsPartSwitch::ActionHandsPartSwitch () inline private
Definition at line 4 of file actionhandspartswitch.c.
    {
    }
Member Function Documentation
ActionCondition()
override bool ActionHandsPartSwitch::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 35 of file actionhandspartswitch.c.
    {
        return false;
    }
CreateConditionComponents()
override void ActionHandsPartSwitch::CreateConditionComponents () inline private
Definition at line 8 of file actionhandspartswitch.c.
    {
        m_ConditionItem = new CCINone; //'CCINotPresent' to perfom with empty hands only
        m_ConditionTarget = new CCTCursor;
        m_Text = "#switch_to_the_next_part";
    }
References m_ConditionItem, m_ConditionTarget, and m_Text.
GetInputType()
override ActionHandsPartSwitch::GetInputType () inline private
Definition at line 20 of file actionhandspartswitch.c.
    {
        return InteractActionInput;
    }
IsInstant()
override bool ActionHandsPartSwitch::IsInstant () inline private
Definition at line 15 of file actionhandspartswitch.c.
    {
        return true;
    }
OnStartClient()
override void ActionHandsPartSwitch::OnStartClient (ActionData action_data) inline private
Definition at line 41 of file actionhandspartswitch.c.
    {
        super.OnStartClient( action_data );
        SetNextIndex(action_data);
    }
References SetNextIndex().
OnStartServer()
override void ActionHandsPartSwitch::OnStartServer (ActionData action_data) inline private
Definition at line 48 of file actionhandspartswitch.c.
    {
        super.OnStartServer( action_data );
        if (!GetGame().IsMultiplayer())
            SetNextIndex(action_data);
    }
References GetGame(), and SetNextIndex().
RemoveForceTargetAfterUse()
override bool ActionHandsPartSwitch::RemoveForceTargetAfterUse () inline private
Definition at line 25 of file actionhandspartswitch.c.
    {
        return false;
    }
SetNextIndex()
void ActionHandsPartSwitch::SetNextIndex (ActionData action_data) inline private
Definition at line 56 of file actionhandspartswitch.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        construction_action_data.SetNextIndex();
    }
References ActionData::m_Player, and ConstructionActionData::SetNextIndex().
Referenced by OnStartClient(), and OnStartServer().
UseAcknowledgment()
override bool ActionHandsPartSwitch::UseAcknowledgment () inline private
Definition at line 30 of file actionhandspartswitch.c.
    {
        return true;
    }