DayzKode: TimerBase Class Reference
TimerBase Class Reference
Tools
Simple class for fading Widgets.
Private Member Functions
void FadeIn (Widget w, float time, bool continue_=false)
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
void FadeOut (Widget w, float time, bool continue_=false)
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
override private void OnTimer ()
override protected void OnTimer ()
override private void OnUpdate ()
void Run (float duration, Managed obj, string fn_name, Param params=NULL, bool loop=false)
Starts timer.
override void Stop ()
void Timer (int category=CALL_CATEGORY_SYSTEM)
void WidgetFadeTimer ()
Private Attributes
float m_alpha
bool m_fadeIn
protected string m_function
protected ref Param m_params
protected Managed m_target
private Widget m_widget
Detailed Description
Simple class for fading Widgets.
Timer class. Use when you want call function after some time, or repeatedly in time intervals. Call is not executed after the Timer object is deleted.
usage:
class MyObject
{
   ref Timer myTimer1;
   ref Timer myTimer2;
   ref Timer myTimer3;
   void MyObject()
   {
    myTimer1 = new Timer();
    myTimer1.Run(10, this, "Refresh"); // calls "Refresh" on "this" after 10 seconds
    myTimer2 = new Timer();
    myTimer2.Run(10, this, "Refresh", NULL, true); // calls "Refresh" on "this" every 10 seconds, until Pause or Stop is called
    myTimer3 = new Timer();
    myTimer3.Run(15, this, "Show", new Param1<bool>(false)); // calls "Show" on "this" with one bool argument after 15 seconds
   }
   void Refresh();
   void Show(bool visible);
}
Definition at line 418 of file tools.c.
Member Function Documentation
FadeIn()
void TimerBase::FadeIn (Widget w, float time, bool continue_ = false) inline private
Make "fade in" effect on Widget (transparency goes from 0.0 to 1.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 0.0 alpha
Definition at line 436 of file tools.c.
    {
        float alpha = w.GetAlpha();
        if (continue_ && alpha > 0.95)
        {
            w.SetAlpha(1.0);
            w.Show(true);
            return;
        }
        m_widget = w;
        m_fadeIn = true;
        OnStart(time, false);
        if (m_widget)
        {
            alpha = m_widget.GetAlpha();
            m_widget.SetAlpha(0);
            m_widget.Show(true);
        }
        if (continue_)
        {
            m_time = alpha * time;
        }
    }
References m_time, and OnStart().
FadeOut()
void TimerBase::FadeOut (Widget w, float time, bool continue_ = false) inline private
Make "fade out" effect on Widget (transparency goes from 1.0 to 0.0)
Parameters
w widget which will be faded
time duration of effect
continue - if True continue from current alpha value, otherwise always begin from 1.0 alpha
Definition at line 471 of file tools.c.
    {
        m_alpha = w.GetAlpha();
        if (continue_ && m_alpha < 0.05)
        {
            w.SetAlpha(0);
            w.Show(false);
            return;
        }
        m_widget = w;
        m_fadeIn = false;
        OnStart(time, false);
        if (m_widget && !continue_)
        {
            m_alpha = 1.0;
            m_widget.SetAlpha(m_alpha);
            m_widget.Show(true);
        }
        if (continue_)
        {
            m_time = (1.0 - m_alpha) * time;
        }
    }
References m_alpha, m_time, and OnStart().
OnTimer() [1/2]
override private void TimerBase::OnTimer () inline private
Definition at line 500 of file tools.c.
    {
        if (m_widget)
        {
            if (m_fadeIn)
            {
                m_widget.SetAlpha(1);
            }
            else
            {
                m_widget.SetAlpha(0);
                m_widget.Show(false);
            }
        }
    }
Referenced by Tick().
OnTimer() [2/2]
override protected void TimerBase::OnTimer () inline private
Definition at line 593 of file tools.c.
    {
        if (m_params)
        {
            GetGame().GameScript.CallFunctionParams(m_target, m_function, NULL, m_params);
            m_params = NULL;
        }
        else
        {
            GetGame().GameScript.CallFunction(m_target, m_function, NULL, 0);
        }
    }
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, and GetGame().
OnUpdate()
override private void TimerBase::OnUpdate () inline private
Definition at line 516 of file tools.c.
    {
        float timeDiff = m_time / m_duration;
        float progress = Math.Max( 0.0, timeDiff );
        if ( m_widget )
        {
            if ( m_fadeIn )
            {
                m_widget.SetAlpha( timeDiff );
            }
            else
            {
                m_widget.SetAlpha( m_alpha - timeDiff );
            }
        }
    }
References m_duration, m_time, and Math::Max().
Referenced by Tick().
Run()
void TimerBase::Run (float duration, Managed obj, string fn_name, Param params = NULL, bool loop = false) inline private
Starts timer.
Parameters
duration function is executed after this time (in seconds).
obj target object on which function will be executed
fn_name name of function (on object "obj") which will be executed
params function arguments see Param for usage, default NULL (no arguments)
loop when true, timer is looped endlessly and function is executed after every loop.
Definition at line 584 of file tools.c.
    {
        m_target = obj;
        m_function = fn_name;
        m_params = params;
        OnStart(duration, loop);
    }
References OnStart().
Stop()
override void TimerBase::Stop () inline private
Definition at line 606 of file tools.c.
    {
        super.Stop();
        m_params = NULL;
    }
Timer()
void TimerBase::Timer (int category = CALL_CATEGORY_SYSTEM) inline private
Definition at line 571 of file tools.c.
    {
        OnInit(category);
    }
References OnInit().
WidgetFadeTimer()
void TimerBase::WidgetFadeTimer () inline private
Definition at line 424 of file tools.c.
    {
        OnInit(CALL_CATEGORY_GUI);
        m_fadeIn = true;
    }
References CALL_CATEGORY_GUI, and OnInit().
Member Data Documentation
m_alpha
float TimerBase::m_alpha private
Definition at line 422 of file tools.c.
Referenced by FadeOut().
m_fadeIn
bool TimerBase::m_fadeIn private
Definition at line 421 of file tools.c.
m_function
protected string TimerBase::m_function private
Definition at line 568 of file tools.c.
m_params
protected ref Param TimerBase::m_params private
Definition at line 569 of file tools.c.
m_target
protected Managed TimerBase::m_target private
Definition at line 567 of file tools.c.
m_widget
private Widget TimerBase::m_widget private
Definition at line 420 of file tools.c.