DayzKode: Weapon_Base Class Reference
Weapon_Base Class Reference
shorthand
Private Member Functions
override void AssembleGun ()
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override bool CanChamberBullet (int muzzleIndex, Magazine mag)
override bool CanEjectBullet ()
override void EEHealthLevelChanged (int oldLevel, int newLevel, string zone)
override float GetChanceToJam ()
override float GetChanceToJam ()
override void HideBullet (int muzzleIndex)
override void InitStateMachine ()
override void InitStateMachine ()
override void InitStateMachine ()
override bool IsShowingChamberedBullet ()
void Magnum_Base ()
override void OnDebugSpawn ()
override void OnFire (int muzzle_index)
void Pistol_Base ()
void Rifle_Base ()
override void SetActions ()
override void SetActions ()
void SetAttachmentsHealth ()
void SetCylinderRotationAnimationPhase (float rot, bool reset=false)
override void ShowBullet (int muzzleIndex)
override RecoilBase SpawnRecoilObject ()
void SyncCylinderRotation (bool reset=true)
Static Private Member Functions
static float GetCylinderRotation (int muzzleIndex)
Private Attributes
const string ATT_SLOT_CYLINDER = "RevolverCylinder"
const string ATT_SLOT_EJECTOR = "RevolverEjector"
ref WeaponStateBase C
ref WeaponStateBase CC00
ref WeaponStateBase CC01
ref WeaponStateBase CC10
ref WeaponStateBase CC11
ref WeaponStateBase CD00
ref WeaponStateBase CD01
ref WeaponStateBase CJF0
ref WeaponStateBase CJF1
int m_ActiveMuzzle
int m_LastMuzzleloaded
ref WeaponStateBase OD00
ref WeaponStateBase OD01
Detailed Description
shorthand
script base for all weapons
@NOTE: this class is bound to core-config "Weapon_Base" config class
Definition at line 5 of file boltactionrifle_base.c.
Member Function Documentation
AssembleGun()
override void Weapon_Base::AssembleGun () inline private
Definition at line 181 of file magnum.c.
    {
        super.AssembleGun();
        if ( !FindAttachmentBySlotName(ATT_SLOT_EJECTOR) )
        {
            GetInventory().CreateAttachment("Magnum_Ejector");
        }
        if ( !FindAttachmentBySlotName(ATT_SLOT_CYLINDER) )
        {
            GetInventory().CreateAttachment("Magnum_Cylinder");
        }
        ForceSyncSelectionState();
        SyncCylinderRotation();
    }
Referenced by Weapon::EEInit().
CanChamberBullet() [1/2]
override bool Weapon_Base::CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 165 of file magnum.c.
    {
        for (int i = 0; i < GetMuzzleCount(); i++)
        {
            if ( CanChamberFromMag(i, mag) )
            {
                if (IsChamberEmpty(i))
                    return true;
                if (IsChamberFiredOut(i))
                    return true;
            }
        }
        return false;
    }
References IsChamberFiredOut().
Referenced by WeaponManager::CanLoadBullet().
CanChamberBullet() [2/2]
override bool Weapon_Base::CanChamberBullet (int muzzleIndex, Magazine mag) inline private
Definition at line 160 of file pistol_base.c.
    {
        return super.CanChamberBullet(muzzleIndex,mag) && IsChamberEmpty(muzzleIndex);
    }
CanEjectBullet()
override bool Weapon_Base::CanEjectBullet () inline private
Definition at line 296 of file magnum.c.
    {
        for (int i = 0; i < GetMuzzleCount(); i++)
        {
            if (IsChamberFull(i))
                return true;
        }
        return false;
    }
References IsChamberFull().
Referenced by WeaponManager::CanEjectBullet().
EEHealthLevelChanged()
override void Weapon_Base::EEHealthLevelChanged (int oldLevel, int newLevel, string zone) inline private
Definition at line 253 of file magnum.c.
    {
        super.EEHealthLevelChanged(oldLevel,newLevel,zone);
        if (GetGame().IsClient())
            return;
        SetAttachmentsHealth();
    }
References GetGame().
GetChanceToJam() [1/2]
override float Weapon_Base::GetChanceToJam () inline private
Definition at line 7 of file boltactionrifle_base.c.
    {
        return 0.0;
    }
Referenced by WeaponManager::Update().
GetChanceToJam() [2/2]
override float Weapon_Base::GetChanceToJam () inline private
Definition at line 576 of file pistol_base.c.
    {
        float chanceToJam = super.GetChanceToJam();
        Magazine mag = GetMagazine(GetCurrentMuzzle());
        if(mag)
        {
            chanceToJam = chanceToJam + ((1.0 - chanceToJam) * mag.GetChanceToJam());
        }
        else
        {
            chanceToJam = chanceToJam + ((1.0 - chanceToJam) * 0.1);
        }
        return chanceToJam;
    }
GetCylinderRotation()
static float Weapon_Base::GetCylinderRotation (int muzzleIndex) inline static private
Definition at line 199 of file magnum.c.
    {
        switch (muzzleIndex)
        {
            case 0:
                return MAGNUM_ROTATION_POSITION_0;
            case 1:
                return MAGNUM_ROTATION_POSITION_5;
            case 2:
                return MAGNUM_ROTATION_POSITION_4;
            case 3:
                return MAGNUM_ROTATION_POSITION_3;
            case 4:
                return MAGNUM_ROTATION_POSITION_2;
            case 5:
                return MAGNUM_ROTATION_POSITION_1;
        }
        ErrorEx(string.Format("Invalid muzzle index: %1", muzzleIndex));
        return MAGNUM_ROTATION_POSITION_0;
    }
References ErrorEx, MAGNUM_ROTATION_POSITION_0, MAGNUM_ROTATION_POSITION_1, MAGNUM_ROTATION_POSITION_2, MAGNUM_ROTATION_POSITION_3, MAGNUM_ROTATION_POSITION_4, and MAGNUM_ROTATION_POSITION_5.
HideBullet()
override void Weapon_Base::HideBullet (int muzzleIndex) inline private
Definition at line 329 of file magnum.c.
    {
        super.HideBullet(muzzleIndex);
        Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(GetAttachmentByType(Magnum_Cylinder));
        if (cylinder)
        {
            string bullet = "bullet";
            if (muzzleIndex > 0)
                bullet = string.Format("bullet_" + (muzzleIndex + 1));
            cylinder.HideSelection(bullet);
            string bullet_nose = "bullet_nose";
            if (muzzleIndex > 0)
                bullet_nose = string.Format("bullet_nose_" + (muzzleIndex + 1));
            cylinder.HideSelection(bullet_nose);
        }
    }
References string::Format().
Referenced by Weapon::ForceSyncSelectionState().
InitStateMachine() [1/3]
override void Weapon_Base::InitStateMachine () inline private
Definition at line 88 of file magnum.c.
    {
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED_KEEP));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_SPECIAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED));
        // setup state machine
        // basic weapon state
        C = new Magnum_Static_State(this, NULL, MagnumAnimState.DEFAULT);
        WeaponMagnumChambering Chamber = new WeaponMagnumChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED_KEEP,WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
        WeaponMagnumChambering Chamber_E = new WeaponMagnumChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_STARTLOOPABLE_CLOSED,WeaponActionChamberingTypes.CHAMBERING_ENDLOOPABLE);
        //WeaponMagnumChambering Chamber_CC00 = new WeaponMagnumChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_END);
        WeaponCharging Mech = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
        WeaponStateBase Trigger_normal = new WeaponFireMagnum(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase Trigger_dry = new WeaponFireMagnum(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED);
        // events
        WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
        WeaponEventBase __M__ = new WeaponEventMechanism;
        WeaponEventBase __T__ = new WeaponEventTrigger;
        WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
        WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
        m_fsm = new WeaponFSM();
        m_fsm.AddTransition(new WeaponTransition( C,                __L__,  Chamber, null, new WeaponGuardAnyChamberFiredOut(this))); // chamber from closed charged
        m_fsm.AddTransition(new WeaponTransition(  Chamber, _fin_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Chamber, _abt_,  C));
        m_fsm.AddTransition(new WeaponTransition( C,                __L__,  Chamber_E)); // chamber from closed charged
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _fin_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_E,   _abt_,  C));
        m_fsm.AddTransition(new WeaponTransition( C,                __M__,  Mech)); // charge from closed
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _fin_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Mech,        _abt_,  C));
        m_fsm.AddTransition(new WeaponTransition( C,                __T__,  Trigger_normal, null, new GuardAnd (new WeaponGuardCurrentChamberFull(this), new GuardNot(new WeaponGuardCurrentChamberFiredOut(this))) )); // fire.cocked
        m_fsm.AddTransition(new WeaponTransition(  Trigger_normal,  _fin_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_normal,  _dto_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_normal,  _abt_,  C));
        m_fsm.AddTransition(new WeaponTransition( C,                __T__,  Trigger_dry)); // fire.cocked
        m_fsm.AddTransition(new WeaponTransition(  Trigger_dry, _fin_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_dry,     _dto_,  C));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_dry,     _abt_,  C));
        m_fsm.SetInitialState(C);
        SelectionBulletHide();
        SetCurrentMuzzle(0);
        //HideMagazine();
        m_fsm.Start();
    }
Referenced by Weapon::Weapon_Base().
InitStateMachine() [2/3]
override void Weapon_Base::InitStateMachine () inline private
Definition at line 169 of file pistol_base.c.
    {
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_BULLET_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_OPENED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_OPENED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED_UNCOCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_END));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM));
        // setup state machine
        // basic weapon states
        // open-closed | discharged-charged | nobullet-bullet | nomag-mag
        // regexp: [OC][CDJ][01][01]
        CD00 = new Pistol_CLO_DIS_BU0_MA0(this, NULL, PistolAnimState.DEFAULT);
        CC00 = new Pistol_CLO_CHG_BU0_MA0(this, NULL, PistolAnimState.CLOSED_CHARGED);
        CC10 = new Pistol_CLO_CHG_BU1_MA0(this, NULL, PistolAnimState.CLOSED_CHARGED);
        CJF0 = new Pistol_CLO_JAM_BU1_MA0(this, NULL, PistolAnimState.JAMMED);
        OD00 = new Pistol_OPE_DIS_BU0_MA0(this, NULL, PistolAnimState.OPENED_DISCHARGED);
        CD01 = new Pistol_CLO_DIS_BU0_MA1(this, NULL, PistolAnimState.DEFAULT);
        CC01 = new Pistol_CLO_CHG_BU0_MA1(this, NULL, PistolAnimState.CLOSED_CHARGED);
        CC11 = new Pistol_CLO_CHG_BU1_MA1(this, NULL, PistolAnimState.CLOSED_CHARGED);
        CJF1 = new Pistol_CLO_JAM_BU1_MA1(this, NULL, PistolAnimState.JAMMED);
        OD01 = new Pistol_OPE_DIS_BU0_MA1(this, NULL, PistolAnimState.OPENED_DISCHARGED);
        // unstable (intermediate) states
        WeaponCharging Mech_CD00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED_UNCOCKED);
        WeaponCharging Mech_CC00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
        WeaponCharging Mech_CD01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED_UNCOCKED);
        WeaponCharging Mech_CC01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
        WeaponCharging Mech_OD00 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED);
        WeaponCharging Mech_OD01 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_OPENED);
        WeaponCharging Mech_CC10 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED); // eject with no mag
        WeaponCharging Mech_CC11 = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED); // eject with mag
        WeaponDryFire Trigger_CC00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED); // cock without clip
        WeaponDryFire Trigger_CD00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED);
        WeaponDryFire Trigger_OD00 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED);
        WeaponDryFire Trigger_CD01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED);
        WeaponDryFire Trigger_OD01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED);
        WeaponDryFire Trigger_CC01 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_COCKED); // cock with clip
        WeaponDryFire Trigger_CJF0 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED);
        WeaponDryFire Trigger_CJF1 = new WeaponDryFire(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_UNCOCKED);
        WeaponFireAndChamberNext Trigger_CC11 = new WeaponFireAndChamberNext(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL);
        WeaponStateBase Trigger_CC10 = new WeaponFireLast(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_NORMAL); // fire last no mag
        WeaponStateBase Trigger_CC11L = new WeaponFireLast(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_LAST); // fire last with mag
        WeaponStateBase Trigger_CC10J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM);
        WeaponStateBase Trigger_CC11J = new WeaponFireToJam(this, NULL, WeaponActions.FIRE, WeaponActionFireTypes.FIRE_JAM);
        WeaponStateBase Unjam_CJF0 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START);
        WeaponStateBase Unjam_CJF1 = new WeaponUnjamming(this, NULL, WeaponActions.UNJAMMING, WeaponActionUnjammingTypes.UNJAMMING_START);
        WeaponChambering Chamber_CD00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED_UNCOCKED);
        WeaponChambering Chamber_CC00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED);
        WeaponChambering Chamber_OD00 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_OPENED);
        WeaponChambering Chamber_CD01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED_UNCOCKED);
        WeaponChambering Chamber_CC01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_CLOSED);
        WeaponChambering Chamber_OD01 = new WeaponChambering(this, NULL, WeaponActions.CHAMBERING, WeaponActionChamberingTypes.CHAMBERING_ONEBULLET_OPENED);
        WeaponAttachMagazine Attach_CC10 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED);
        WeaponAttachMagazine Attach_CJF0 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED);
        WeaponAttachMagazine Attach_CD00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED);
        WeaponAttachMagazine Attach_CC00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED);
        WeaponAttachMagazine Attach_OD00 = new WeaponAttachMagazine(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED);
        WeaponReplacingMagAndChamberNext Reload_CD01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED);
        WeaponReplacingMagAndChamberNext Reload_CC01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED);
        WeaponReplacingMagAndChamberNext Reload_CC11 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_BULLET_CLOSED);
        WeaponReplacingMagAndChamberNext Reload_CJF1 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_BULLET_CLOSED);
        WeaponReplacingMagAndChamberNext Reload_OD01 = new WeaponReplacingMagAndChamberNext(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOADPISTOL_MAGAZINE_NOBULLET_OPENED);
        WeaponDetachingMag Detach_CC11 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH);
        WeaponDetachingMag Detach_CC01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH);
        WeaponDetachingMag Detach_CD01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH);
        WeaponDetachingMag Detach_OD01 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH);
        WeaponDetachingMag Detach_CJF1 = new WeaponDetachingMag(this, NULL, WeaponActions.RELOAD, WeaponActionReloadTypes.RELOAD_MAGAZINE_DETACH);
        // events
        WeaponEventBase __M__ = new WeaponEventMechanism;
        WeaponEventBase __T__ = new WeaponEventTrigger;
        WeaponEventBase __TJ_ = new WeaponEventTriggerToJam;
        WeaponEventBase __U__ = new WeaponEventUnjam;
        WeaponEventBase __L__ = new WeaponEventLoad1Bullet;
        WeaponEventBase __A__ = new WeaponEventAttachMagazine;
        WeaponEventBase __D__ = new WeaponEventDetachMagazine;
        WeaponEventBase __S__ = new WeaponEventSwapMagazine;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase _rto_ = new WeaponEventReloadTimeout;
        WeaponEventBase _dto_ = new WeaponEventDryFireTimeout;
        WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
        m_fsm = new WeaponFSM();
        // charging
        m_fsm.AddTransition(new WeaponTransition( CD00,             __M__,  Mech_CD00)); // charge from closed
        m_fsm.AddTransition(new WeaponTransition(  Mech_CD00,       _fin_,  CC00));
            Mech_CD00.AddTransition(new WeaponTransition( Mech_CD00.m_start,            _abt_,  CD00));
            Mech_CD00.AddTransition(new WeaponTransition( Mech_CD00.m_eject,            _abt_,  CC00));
            Mech_CD00.AddTransition(new WeaponTransition( Mech_CD00.m_onCK,             _abt_,  CC00));
            Mech_CD00.AddTransition(new WeaponTransition( Mech_CD00.m_chamber,          _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( CC00,             __M__,  Mech_CC00)); // charge from charged
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC00,       _fin_,  CC00));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC00,       _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( OD00,             __M__,  Mech_OD00)); // charge from opened
        m_fsm.AddTransition(new WeaponTransition(  Mech_OD00,       _fin_,  CC00));
            Mech_OD00.AddTransition(new WeaponTransition( Mech_OD00.m_start,            _abt_,  OD00));
            Mech_OD00.AddTransition(new WeaponTransition( Mech_OD00.m_eject,            _abt_,  CC00));
            Mech_OD00.AddTransition(new WeaponTransition( Mech_OD00.m_onCK,             _abt_,  CC00));
            Mech_OD00.AddTransition(new WeaponTransition( Mech_OD00.m_chamber,          _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( OD01,             __M__,  Mech_OD01)); // charge from opened with mag
        m_fsm.AddTransition(new WeaponTransition(  Mech_OD01,       _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this) ));
        m_fsm.AddTransition(new WeaponTransition(  Mech_OD01,       _fin_,  CC11));
            Mech_OD01.AddTransition(new WeaponTransition( Mech_OD01.m_start,            _abt_,  OD01));
            Mech_OD01.AddTransition(new WeaponTransition( Mech_OD01.m_eject,            _abt_,  CC01));
            Mech_OD01.AddTransition(new WeaponTransition( Mech_OD01.m_onCK,             _abt_,  CC01));
            Mech_OD01.AddTransition(new WeaponTransition( Mech_OD01.m_chamber,          _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CD01,             __M__,  Mech_CD01)); // charge from closed=1 with mag
        m_fsm.AddTransition(new WeaponTransition(  Mech_CD01,       _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CD01,       _fin_,  CC11));
            Mech_CD01.AddTransition(new WeaponTransition( Mech_CD01.m_start,            _abt_,  CD01));
            Mech_CD01.AddTransition(new WeaponTransition( Mech_CD01.m_eject,            _abt_,  CC01));
            Mech_CD01.AddTransition(new WeaponTransition( Mech_CD01.m_onCK,             _abt_,  CC01));
            Mech_CD01.AddTransition(new WeaponTransition( Mech_CD01.m_chamber,          _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC01,             __M__,  Mech_CC01)); // charge from closed/charged with mag
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC01,       _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC01,       _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC01,       _abt_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC01,       _abt_,  CC11));
        // eject good cartridge
        m_fsm.AddTransition(new WeaponTransition( CC10,             __M__,  Mech_CC10)); // eject chamber nomag
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC10,       _fin_,  CC00));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC10,       _abt_,  CC00, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC10,       _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( CC11,             __M__,  Mech_CC11 )); // eject with mag with ammo
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC11,       _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC11,       _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC11,       _abt_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Mech_CC11,       _abt_,  CC11));
        // Trigger_CC11e
        m_fsm.AddTransition(new WeaponTransition( CC00,             __T__,  Trigger_CC00)); // fire.cocked
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC00,    _fin_,  CD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC00,    _dto_,  CD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC00,    _abt_,  CD00));
        m_fsm.AddTransition(new WeaponTransition( CD00,             __T__,  Trigger_CD00)); // fire.uncocked
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD00,    _fin_,  CD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD00,    _dto_,  CD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD00,    _abt_,  CD00));
        m_fsm.AddTransition(new WeaponTransition( OD00,             __T__,  Trigger_OD00)); // opened fire.uncocked
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD00,    _fin_,  OD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD00,    _dto_,  OD00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD00,    _abt_,  OD00));
        m_fsm.AddTransition(new WeaponTransition( CD01,             __T__,  Trigger_CD01)); // fire.uncocked w mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD01,    _fin_,  CD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD01,    _dto_,  CD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CD01,    _abt_,  CD01));
        m_fsm.AddTransition(new WeaponTransition( OD01,             __T__,  Trigger_OD01)); // opened fire.uncocked w mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD01,    _fin_,  OD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD01,    _dto_,  OD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_OD01,    _abt_,  OD01));
        m_fsm.AddTransition(new WeaponTransition( CJF0,             __T__,  Trigger_CJF0)); // opened fire.uncocked w mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF0,    _fin_,  CJF0));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF0,    _dto_,  CJF0));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF0,    _abt_,  CJF0));
        m_fsm.AddTransition(new WeaponTransition( CJF1,             __T__,  Trigger_CJF1)); // opened fire.uncocked w mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF1,    _fin_,  CJF1));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF1,    _dto_,  CJF1));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CJF1,    _abt_,  CJF1));
        m_fsm.AddTransition(new WeaponTransition( CC10,             __T__,  Trigger_CC10)); // or fire.last (if not jammed)
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10,    _fin_,  CC00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10,    _rto_,  CC00));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10,    _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( CC10,             __TJ_,  Trigger_CC10J)); // or fire.last (if not jammed)
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10J,   _fin_,  CJF0 ));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10J,   _rto_,  CJF0 ));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC10J,   _abt_,  CJF0 ));
        m_fsm.AddTransition(new WeaponTransition( CC11,             __T__,  Trigger_CC11, NULL, new WeaponGuardHasAmmo(this))); // fire.normal + chamber next
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11,    _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11,    _rto_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11,    _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC11,             __T__,  Trigger_CC11L, NULL, new GuardNot(new WeaponGuardHasAmmo(this)))); // fire.last with mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11L,   _fin_,  OD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11L,   _rto_,  OD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11L,   _abt_,  OD01));
        m_fsm.AddTransition(new WeaponTransition( CC11,             __TJ_,  Trigger_CC11J )); // fire.last with mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11J,   _fin_,  CJF1 ));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11J,   _rto_,  CJF1 ));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC11J,   _abt_,  CJF1 ));
        m_fsm.AddTransition(new WeaponTransition( CC01,             __T__,  Trigger_CC01)); // fire.cocked with mag
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC01,    _fin_,  CD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC01,    _dto_,  CD01));
        m_fsm.AddTransition(new WeaponTransition(  Trigger_CC01,    _abt_,  CD01));
        // load cartridge
        m_fsm.AddTransition(new WeaponTransition( CD00,             __L__,  Chamber_CD00)); // chamber from closed=1
        m_fsm.AddTransition(new WeaponTransition(  Chamber_CD00,    _fin_,  CC10));
            Chamber_CD00.AddTransition(new WeaponTransition( Chamber_CD00.m_start,      _abt_,  CD00));
            Chamber_CD00.AddTransition(new WeaponTransition( Chamber_CD00.m_eject,      _abt_,  OD00));
            Chamber_CD00.AddTransition(new WeaponTransition( Chamber_CD00.m_chamber,    _abt_,  OD00));
            Chamber_CD00.AddTransition(new WeaponTransition( Chamber_CD00.m_w4t,        _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( OD00,             __L__,  Chamber_OD00)); // chamber from opened
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD00,    _fin_,  CC10));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD00,    _abt_,  OD00, NULL, new WeaponGuardCurrentChamberEmpty(this) ));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD00,    _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( CC00,             __L__,  Chamber_CC00)); // chamber from closed charged
        m_fsm.AddTransition(new WeaponTransition(  Chamber_CC00,    _fin_,  CC10));
            Chamber_CC00.AddTransition(new WeaponTransition( Chamber_CC00.m_start,      _abt_,  CC00));
            Chamber_CC00.AddTransition(new WeaponTransition( Chamber_CC00.m_eject,      _abt_,  OD00));
            Chamber_CC00.AddTransition(new WeaponTransition( Chamber_CC00.m_chamber,    _abt_,  OD00));
            Chamber_CC00.AddTransition(new WeaponTransition( Chamber_CC00.m_w4t,        _abt_,  CC10));
        // load cartridge with mag
        m_fsm.AddTransition(new WeaponTransition( CD01,             __L__,  Chamber_CD01, NULL, new WeaponGuardHasMag(this))); // chamber from closed=1 with mag
        m_fsm.AddTransition(new WeaponTransition(  Chamber_CD01,    _fin_,  CC11));
            Chamber_CD01.AddTransition(new WeaponTransition( Chamber_CD01.m_start,      _abt_,  CD01));
            Chamber_CD01.AddTransition(new WeaponTransition( Chamber_CD01.m_eject,      _abt_,  OD01));
            Chamber_CD01.AddTransition(new WeaponTransition( Chamber_CD01.m_chamber,    _abt_,  OD01));
            Chamber_CD01.AddTransition(new WeaponTransition( Chamber_CD01.m_w4t,        _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC01,             __L__,  Chamber_CC01, NULL, new WeaponGuardHasMag(this))); // chamber from closed=1 with mag
        m_fsm.AddTransition(new WeaponTransition(  Chamber_CC01,    _fin_,  CC11));
            Chamber_CC01.AddTransition(new WeaponTransition( Chamber_CC01.m_start,      _abt_,  CC01));
            Chamber_CC01.AddTransition(new WeaponTransition( Chamber_CC01.m_eject,      _abt_,  OD01));
            Chamber_CC01.AddTransition(new WeaponTransition( Chamber_CC01.m_chamber,    _abt_,  OD01));
            Chamber_CC01.AddTransition(new WeaponTransition( Chamber_CC01.m_w4t,        _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( OD01,             __L__,  Chamber_OD01, NULL, new WeaponGuardHasMag(this))); // chamber from opened with mag
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD01,    _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD01,    _abt_,  OD01, NULL, new WeaponGuardCurrentChamberEmpty(this) ));
        m_fsm.AddTransition(new WeaponTransition(  Chamber_OD01,    _abt_,  CC11));;
        m_fsm.AddTransition(new WeaponTransition( CJF0,             __A__,  Attach_CJF0, NULL, new WeaponGuardCanAttachMag(this))); // attach from JAM/b1/m0
        m_fsm.AddTransition(new WeaponTransition(  Attach_CJF0, _fin_,  CJF1));
        //m_fsm.AddTransition(new WeaponTransition(  Attach_CJF0,   _abt_,  CJF1, NULL, new WeaponGuardHasMag(this)));
        //m_fsm.AddTransition(new WeaponTransition(  Attach_CJF0,   _abt_,  CJF0));
            Attach_CJF0.AddTransition(new WeaponTransition( Attach_CJF0.m_start,        _abt_,  CJF0));
            Attach_CJF0.AddTransition(new WeaponTransition( Attach_CJF0.m_attach,       _abt_,  CJF0));
// zdokumentovano az sem
        // attach mag with no ammo
        m_fsm.AddTransition(new WeaponTransition( CD00,             __A__,  Attach_CD00, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b0/m0
        m_fsm.AddTransition(new WeaponTransition(  Attach_CD00,     _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Attach_CD00,     _fin_,  CC11));
            Attach_CD00.AddTransition(new WeaponTransition( Attach_CD00.m_start,        _abt_,  CD00));
            Attach_CD00.AddTransition(new WeaponTransition( Attach_CD00.m_attach,       _abt_,  CD00));
            Attach_CD00.AddTransition(new WeaponTransition( Attach_CD00.m_onCK,         _abt_,  CC01));
            Attach_CD00.AddTransition(new WeaponTransition( Attach_CD00.m_chamber,      _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC10,             __A__,  Attach_CC10, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b1/m0
        m_fsm.AddTransition(new WeaponTransition(  Attach_CC10,     _fin_,  CC11));
            Attach_CC10.AddTransition(new WeaponTransition( Attach_CC10.m_start,        _abt_,  CC10));
            Attach_CC10.AddTransition(new WeaponTransition( Attach_CC10.m_attach,       _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( OD00,             __A__,  Attach_OD00, NULL, new WeaponGuardCanAttachMag(this))); // attach from OPE/b0/m0
        m_fsm.AddTransition(new WeaponTransition(  Attach_OD00,     _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Attach_OD00,     _fin_,  CC11));
            Attach_OD00.AddTransition(new WeaponTransition( Attach_OD00.m_start,        _abt_,  OD00));
            Attach_OD00.AddTransition(new WeaponTransition( Attach_OD00.m_attach,       _abt_,  OD00));
            Attach_OD00.AddTransition(new WeaponTransition( Attach_OD00.m_onCK,         _abt_,  CC01));
            Attach_OD00.AddTransition(new WeaponTransition( Attach_OD00.m_chamber,      _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC00,             __A__,  Attach_CC00, NULL, new WeaponGuardCanAttachMag(this))); // attach from CLO/b0/m0 charged
        m_fsm.AddTransition(new WeaponTransition(  Attach_CC00, _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Attach_CC00, _fin_,  CC11));
            Attach_CC00.AddTransition(new WeaponTransition( Attach_CC00.m_start,        _abt_,  CC00));
            Attach_CC00.AddTransition(new WeaponTransition( Attach_CC00.m_attach,       _abt_,  CC00));
            Attach_CC00.AddTransition(new WeaponTransition( Attach_CC00.m_onCK,         _abt_,  CC01));
            Attach_CC00.AddTransition(new WeaponTransition( Attach_CC00.m_chamber,      _abt_,  CC11));
        // replace magazine
        m_fsm.AddTransition(new WeaponTransition( CD01,             __S__,  Reload_CD01, NULL, new WeaponGuardCanSwapMag(this))); // swap in CLO/b0/m1
        m_fsm.AddTransition(new WeaponTransition(  Reload_CD01,     _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CD01,     _fin_,  CC11));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_start,        _abt_,  CD01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_eject,        _abt_,  CD01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_detach,       _abt_,  CD01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_hideOld,      _abt_,  CD00));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_swapMags,     _abt_,  CD01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_attach,       _abt_,  CD01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_onCK,         _abt_,  CC01));
            Reload_CD01.AddTransition(new WeaponTransition( Reload_CD01.m_chamber,      _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CC11,             __S__, Reload_CC11, NULL, new WeaponGuardCanSwapMag(this))); // swap in CLO/b1/m1
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC11, _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC11, _abt_,  CC11, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC11, _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( CC01,             __S__,  Reload_CC01, NULL, new WeaponGuardCanSwapMag(this))); // CLO/b0/m1 swap with empty mag (no chamber)
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC01, _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC01, _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC01, _abt_,  CC11, NULL, new WeaponGuardCurrentChamberFull(this)) );
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC01, _abt_,  CC01, NULL, new WeaponGuardHasMag(this)) );
        m_fsm.AddTransition(new WeaponTransition(  Reload_CC01, _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( OD01,             __S__,  Reload_OD01, NULL, new WeaponGuardCanSwapMag(this))); // OPE/b0/m1 swap with empty mag (no chamber)
        m_fsm.AddTransition(new WeaponTransition(  Reload_OD01, _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Reload_OD01, _fin_,  CC11));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_start,         _abt_,  OD01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_eject,         _abt_,  OD01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_detach,        _abt_,  OD01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_hideOld,       _abt_,  OD00));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_swapMags,      _abt_,  OD01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_attach,        _abt_,  OD01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_onCK,          _abt_,  CC01));
            Reload_OD01.AddTransition(new WeaponTransition(Reload_OD01.m_chamber,       _abt_,  CC11));
        m_fsm.AddTransition(new WeaponTransition( CJF1,         __S__,  Reload_CJF1, NULL, new WeaponGuardCanSwapMag(this))); // swap in JAM/b1/m1
        m_fsm.AddTransition(new WeaponTransition(  Reload_CJF1, _fin_,  CJF1));
        m_fsm.AddTransition(new WeaponTransition(  Reload_CJF1, _abt_,  CC11, NULL, new WeaponGuardCurrentChamberFull(this)) );
        m_fsm.AddTransition(new WeaponTransition(  Reload_CJF1, _abt_,  CC01, NULL, new WeaponGuardHasMag(this)) );
        m_fsm.AddTransition(new WeaponTransition(  Reload_CJF1, _abt_,  CC00));
        // detach magazine
        m_fsm.AddTransition(new WeaponTransition( OD01,         __D__,  Detach_OD01, NULL, new WeaponGuardCanDetachMag(this))); // detach from OPE/b0/m1
        m_fsm.AddTransition(new WeaponTransition(  Detach_OD01, _fin_,  OD00));
        m_fsm.AddTransition(new WeaponTransition(  Detach_OD01, _abt_,  OD01, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Detach_OD01, _abt_,  OD00));
        m_fsm.AddTransition(new WeaponTransition( CC11,         __D__,  Detach_CC11, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b1/m1
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC11, _fin_,  CC10));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC11, _abt_,  CC11, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC11, _abt_,  CC10));
        m_fsm.AddTransition(new WeaponTransition( CC01,         __D__,  Detach_CC01, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b0/m1
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC01, _fin_,  CC00));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC01, _abt_,  CC01, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CC01, _abt_,  CC00));
        m_fsm.AddTransition(new WeaponTransition( CD01,         __D__,  Detach_CD01, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b0/m1 dischg
        m_fsm.AddTransition(new WeaponTransition(  Detach_CD01, _fin_,  CD00));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CD01, _abt_,  CD01, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CD01, _abt_,  CD00));
        m_fsm.AddTransition(new WeaponTransition( CJF1,         __D__,  Detach_CJF1, NULL, new WeaponGuardCanDetachMag(this))); // detach from CLO/b1/m1 jammed
        m_fsm.AddTransition(new WeaponTransition(  Detach_CJF1, _fin_,  CJF0));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CJF1, _abt_,  CJF1, NULL, new WeaponGuardHasMag(this)));
        m_fsm.AddTransition(new WeaponTransition(  Detach_CJF1, _abt_,  CJF0));
        // unjam
        m_fsm.AddTransition(new WeaponTransition( CJF0,         __U__,  Unjam_CJF0)); // unjam nomag
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF0,      _fin_,  CJF0, NULL, new WeaponGuardJammed(this)));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF0,      _fin_,  CC00, NULL, new GuardNot(new WeaponGuardJammed(this))));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF0,      _abt_,  CJF0));
        m_fsm.AddTransition(new WeaponTransition( CJF1,         __U__,  Unjam_CJF1)); // unjam with mag with ammo
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _fin_,  CJF1, NULL, new WeaponGuardJammed(this)));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _fin_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _fin_,  CC11));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _abt_,  CJF1, NULL, new WeaponGuardJammed(this)));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _abt_,  CC01, NULL, new WeaponGuardCurrentChamberEmpty(this)));
        m_fsm.AddTransition(new WeaponTransition(  Unjam_CJF1,      _abt_,  CC11));
        m_fsm.SetInitialState(CD00);
        SelectionBulletHide();
        HideMagazine();
        m_fsm.Start();
    }
References WeaponGuardHasAmmo().
InitStateMachine() [3/3]
override void Weapon_Base::InitStateMachine () inline private
Definition at line 16 of file rifle_base.c.
    {
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED));
        // setup state machine
        // basic weapon states
        WeaponStateBase E = new WeaponStableState(this, NULL, DefaultAnimState.DEFAULT);
        WeaponStateBase Mech = new WeaponCharging(this, NULL, WeaponActions.MECHANISM, WeaponActionMechanismTypes.MECHANISM_CLOSED);
        // events
        WeaponEventBase __M__ = new WeaponEventMechanism;
        WeaponEventBase _fin_ = new WeaponEventHumanCommandActionFinished;
        WeaponEventBase _abt_ = new WeaponEventHumanCommandActionAborted;
        m_fsm = new WeaponFSM();
        // charging
        m_fsm.AddTransition(new WeaponTransition(E      , __M__,    Mech));
        m_fsm.AddTransition(new WeaponTransition(Mech   , _fin_,    E));
        m_fsm.AddTransition(new WeaponTransition(Mech   , _abt_,    E));
        m_fsm.SetInitialState(E);
        SelectionBulletHide();
        m_fsm.Start();
    }
References E.
IsShowingChamberedBullet()
override bool Weapon_Base::IsShowingChamberedBullet () inline private
Definition at line 291 of file magnum.c.
    {
        return false;
    }
Referenced by Icon::RefreshMuzzleIcon(), and SlotsIcon::RefreshMuzzleIcon().
Magnum_Base()
void Weapon_Base::Magnum_Base () inline private
Definition at line 73 of file magnum.c.
    {
        m_LastMuzzleloaded = 0;
        m_ActiveMuzzle = 0;
        /*m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionTypes.CHAMBERING_STARTLOOPABLE_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.CHAMBERING, WeaponActionTypes.CHAMBERING_ENDLOOPABLE));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionTypes.MECHANISM_CLOSED));
        m_abilities.Insert(new AbilityRecord(WeaponActions.MECHANISM, WeaponActionTypes.MECHANISM_SPECIAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionTypes.UNJAMMING_START));
        m_abilities.Insert(new AbilityRecord(WeaponActions.UNJAMMING, WeaponActionTypes.UNJAMMING_END));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionTypes.FIRE_NORMAL));
        m_abilities.Insert(new AbilityRecord(WeaponActions.FIRE, WeaponActionTypes.FIRE_COCKED));*/
    }
OnDebugSpawn()
override void Weapon_Base::OnDebugSpawn () inline private
Definition at line 350 of file magnum.c.
    {
        super.OnDebugSpawn();
        EntityAI entity;
        if ( Class.CastTo(entity, this) )
        {
            entity.SpawnEntityOnGroundPos("Ammo_357", entity.GetPosition());
        }
    }
References Class::CastTo().
OnFire()
override void Weapon_Base::OnFire (int muzzle_index) inline private
Definition at line 278 of file magnum.c.
    {
        super.OnFire(muzzle_index);
        Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(GetAttachmentByType(Magnum_Cylinder));
        if (cylinder)
        {
            string bullet_nose = "bullet_nose";
            if (muzzle_index > 0)
                bullet_nose = string.Format("bullet_nose_" + (muzzle_index + 1));
            cylinder.HideSelection(bullet_nose);
        }
    }
References string::Format().
Pistol_Base()
void Weapon_Base::Pistol_Base () inline private
Definition at line 165 of file pistol_base.c.
    {
    }
Rifle_Base()
void Weapon_Base::Rifle_Base () inline private
Definition at line 12 of file rifle_base.c.
    {
    }
SetActions() [1/2]
override void Weapon_Base::SetActions () inline private
Definition at line 58 of file magnum.c.
    {
        super.SetActions();
        AddAction(FirearmActionLoadMultiBullet);
        RemoveAction(FirearmActionLoadBulletQuick); // Easy reload
        AddAction(FirearmActionLoadMultiBulletQuick); // Easy reload
    }
References AddAction(), and RemoveAction().
SetActions() [2/2]
override void Weapon_Base::SetActions () inline private
Definition at line 607 of file pistol_base.c.
    {
        super.SetActions();
        AddAction(FirearmActionDetachMagazine);
        //AddAction(ActionAdvancedDetachMagazine);
    }
References AddAction().
SetAttachmentsHealth()
void Weapon_Base::SetAttachmentsHealth () inline private
Definition at line 264 of file magnum.c.
    {
        EntityAI entity;
        ItemBase attachment;
        for (int i = 0; i < GetInventory().AttachmentCount(); i++)
        {
            entity = GetInventory().GetAttachmentFromIndex(i);
            if ( Class.CastTo(attachment,entity) )
            {
                attachment.SetHealth01("","Health",GetHealth01());
            }
        }
    }
References Class::CastTo(), and GetHealth01().
SetCylinderRotationAnimationPhase()
void Weapon_Base::SetCylinderRotationAnimationPhase (float rot, bool reset = false) inline private
Definition at line 222 of file magnum.c.
    {
        Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(GetAttachmentByType(Magnum_Cylinder));
        Magnum_Ejector ejector = Magnum_Ejector.Cast(GetAttachmentByType(Magnum_Ejector));
        if (cylinder && ejector)
        {
            float anim_phase = cylinder.GetAnimationPhase("Rotate_Cylinder");
            if ( Math.AbsFloat(anim_phase - rot) > 0.1 )
            {
                if (reset)
                {
                    cylinder.ResetAnimationPhase("Rotate_Cylinder", rot );
                    ejector.ResetAnimationPhase("Rotate_Ejector", rot );
                }
                else if (rot == MAGNUM_ROTATION_POSITION_0)
                {
                    cylinder.ResetAnimationPhase("Rotate_Cylinder", MAGNUM_ROTATION_POSITION_M1 );
                    ejector.ResetAnimationPhase("Rotate_Ejector", MAGNUM_ROTATION_POSITION_M1 );
                }
                cylinder.SetAnimationPhase("Rotate_Cylinder", rot );
                ejector.SetAnimationPhase("Rotate_Ejector", rot );
            }
        }
    }
References Math::AbsFloat(), MAGNUM_ROTATION_POSITION_0, and MAGNUM_ROTATION_POSITION_M1.
ShowBullet()
override void Weapon_Base::ShowBullet (int muzzleIndex) inline private
Definition at line 306 of file magnum.c.
    {
        super.ShowBullet(muzzleIndex);
        Magnum_Cylinder cylinder = Magnum_Cylinder.Cast(GetAttachmentByType(Magnum_Cylinder));
        if (cylinder)
        {
            string bullet = "bullet";
            if (muzzleIndex > 0)
                bullet = string.Format("bullet_" + (muzzleIndex + 1));
            cylinder.ShowSelection(bullet);
            if (!IsChamberFiredOut(muzzleIndex))
            {
                string bullet_nose = "bullet_nose";
                if (muzzleIndex > 0)
                    bullet_nose = string.Format("bullet_nose_" + (muzzleIndex + 1));
                cylinder.ShowSelection(bullet_nose);
            }
        }
    }
References string::Format(), and IsChamberFiredOut().
Referenced by Weapon::ForceSyncSelectionState().
SpawnRecoilObject()
override RecoilBase Weapon_Base::SpawnRecoilObject () inline private
Definition at line 68 of file magnum.c.
    {
        return new MagnumRecoil(this);
    }
Referenced by DayZPlayerImplementAiming::SetRecoil().
SyncCylinderRotation()
void Weapon_Base::SyncCylinderRotation (bool reset = true) inline private
Definition at line 248 of file magnum.c.
    {
        SetCylinderRotationAnimationPhase(GetCylinderRotation(GetCurrentMuzzle()), reset);
    }
Member Data Documentation
ATT_SLOT_CYLINDER
const string Weapon_Base::ATT_SLOT_CYLINDER = "RevolverCylinder" private
Definition at line 55 of file magnum.c.
ATT_SLOT_EJECTOR
const string Weapon_Base::ATT_SLOT_EJECTOR = "RevolverEjector" private
Definition at line 56 of file magnum.c.
C
ref WeaponStateBase Weapon_Base::C private
Definition at line 52 of file magnum.c.
CC00
ref WeaponStateBase Weapon_Base::CC00 private
Definition at line 150 of file pistol_base.c.
CC01
ref WeaponStateBase Weapon_Base::CC01 private
Definition at line 155 of file pistol_base.c.
CC10
ref WeaponStateBase Weapon_Base::CC10 private
Definition at line 151 of file pistol_base.c.
CC11
ref WeaponStateBase Weapon_Base::CC11 private
Definition at line 156 of file pistol_base.c.
CD00
ref WeaponStateBase Weapon_Base::CD00 private
Definition at line 149 of file pistol_base.c.
CD01
ref WeaponStateBase Weapon_Base::CD01 private
Definition at line 154 of file pistol_base.c.
CJF0
ref WeaponStateBase Weapon_Base::CJF0 private
Definition at line 152 of file pistol_base.c.
CJF1
ref WeaponStateBase Weapon_Base::CJF1 private
Definition at line 157 of file pistol_base.c.
m_ActiveMuzzle
int Weapon_Base::m_ActiveMuzzle private
Definition at line 54 of file magnum.c.
m_LastMuzzleloaded
int Weapon_Base::m_LastMuzzleloaded private
Definition at line 53 of file magnum.c.
OD00
ref WeaponStateBase Weapon_Base::OD00 private
Definition at line 153 of file pistol_base.c.
OD01
ref WeaponStateBase Weapon_Base::OD01 private
Definition at line 158 of file pistol_base.c.