DayzKode: Chat Class Reference
Chat Class Reference
Private Member Functions
void Add (ChatMessageEventParams params)
void AddInternal (ChatMessageEventParams params)
void Chat ()
void Clear ()
void Destroy ()
void Init (Widget root_widget)
void ~Chat ()
Private Attributes
const int LINE_COUNT = 12
protected int m_LastLine
protected int m_LineHeight
protected ref array< ref ChatLine > m_Lines
protected Widget m_RootWidget
Detailed Description
channel type, possible values CCSystem(1) CCAdmin(2) CCDirect(4) CCMegaphone(8) CCTransmitter(16) CCPublicAddressSystem(32) CCBattlEye(64)
Definition at line 14 of file chat.c.
Constructor & Destructor Documentation
Chat()
void Chat::Chat () inline private
Definition at line 23 of file chat.c.
    {
        m_Lines = new array<ref ChatLine>;
    }
References m_Lines.
~Chat()
void Chat::~Chat () inline private
Definition at line 28 of file chat.c.
    {
        Destroy();
    }
References Destroy().
Member Function Documentation
Add()
void Chat::Add (ChatMessageEventParams params) inline private
Definition at line 68 of file chat.c.
    {
        int max_lenght = ChatMaxUserLength;
        int name_lenght = params.param2.Length();
        int text_lenght = params.param3.Length();
        int total_lenght = text_lenght + name_lenght;
        int channel =  params.param1;
        if( channel & CCSystem || channel & CCBattlEye) //TODO separate battleye bellow
        {
            if( g_Game.GetProfileOption( EDayZProfilesOptions.GAME_MESSAGES ) )
                return;
            max_lenght = ChatMaxSystemLength; // system messages can be longer
        }
        //TODO add battleye filter to options
        /*else if( channel & CCBattlEye )
        {
            if( g_Game.GetProfileOption( EDayZProfilesOptions.BATTLEYE_MESSAGES ) )
                return;
        }*/
        else if( channel & CCAdmin )
        {
            if( g_Game.GetProfileOption( EDayZProfilesOptions.ADMIN_MESSAGES ) )
                return;
        }
        else if( channel & CCDirect || channel & CCMegaphone || channel & CCTransmitter || channel & CCPublicAddressSystem )
        {
            if( g_Game.GetProfileOption( EDayZProfilesOptions.PLAYER_MESSAGES ) )
                return;
        }
        else if( channel != 0 ) // 0 should be local messages to self
        {
            Print("Chat: Unknown channel " + channel);
            return;
        }
        if (total_lenght > max_lenght)
        {
            int pos = 0;
            int lenght = Math.Clamp(max_lenght - name_lenght, 0, text_lenght);
            ref ChatMessageEventParams tmp = new ChatMessageEventParams(params.param1, params.param2, "", params.param4);
            while (pos < text_lenght)
            {
                tmp.param3 = params.param3.Substring(pos, lenght);
                AddInternal(tmp);
                tmp.param2 = "";
                pos += lenght;
                lenght = Math.Clamp(text_lenght - pos, 0, max_lenght);
            }
        }
        else
        {
            AddInternal(params);
        }
    }
References AddInternal(), Math::Clamp(), g_Game, and Print().
AddInternal()
void Chat::AddInternal (ChatMessageEventParams params) inline private
Definition at line 127 of file chat.c.
    {
        m_LastLine = (m_LastLine + 1) % m_Lines.Count();
        ChatLine line = m_Lines.Get(m_LastLine);
        line.Set(params);
        for (int i = 0; i < m_Lines.Count(); i++)
        {
            line = m_Lines.Get((m_LastLine + 1 + i) % LINE_COUNT);
            line.m_RootWidget.SetPos(0, i * m_LineHeight);
            float x = 0;
            float y = 0;
            line.m_RootWidget.GetPos(x, y);
        }
    }
References LINE_COUNT, m_LastLine, m_LineHeight, m_Lines, ChatLine::m_RootWidget, ChatLine::Set(), x, and y.
Referenced by Add().
Clear()
void Chat::Clear () inline private
Definition at line 60 of file chat.c.
    {
        for (int i = 0; i < LINE_COUNT; i++)
        {
            m_Lines.Get(i).Clear();
        }
    }
References LINE_COUNT, and m_Lines.
Destroy()
void Chat::Destroy () inline private
Definition at line 55 of file chat.c.
    {
        m_Lines.Clear();
    }
References m_Lines.
Referenced by Init(), and ~Chat().
Init()
void Chat::Init (Widget root_widget) inline private
Definition at line 33 of file chat.c.
    {
        Destroy();
        m_RootWidget = root_widget;
        if (m_RootWidget)
        {
            float w;
            float h;
            m_RootWidget.GetSize(w,h);
            m_LineHeight = h / LINE_COUNT;
            m_LastLine = 0;
            for (int i = 0; i < LINE_COUNT; i++)
            {
                ChatLine line = new ChatLine(m_RootWidget);
                m_Lines.Insert(line);
            }
        }
    }
References Destroy(), LINE_COUNT, m_LastLine, m_LineHeight, m_Lines, and m_RootWidget.
Member Data Documentation
LINE_COUNT
const int Chat::LINE_COUNT = 12 private
Definition at line 16 of file chat.c.
Referenced by AddInternal(), Clear(), and Init().
m_LastLine
protected int Chat::m_LastLine private
Definition at line 20 of file chat.c.
Referenced by AddInternal(), and Init().
m_LineHeight
protected int Chat::m_LineHeight private
Definition at line 19 of file chat.c.
Referenced by AddInternal(), and Init().
m_Lines
protected ref array<ref ChatLine> Chat::m_Lines private
Definition at line 21 of file chat.c.
Referenced by AddInternal(), Chat(), Clear(), Destroy(), and Init().
m_RootWidget
protected Widget Chat::m_RootWidget private
Definition at line 18 of file chat.c.
Referenced by Init().