DayzKode: ActionDebug Class Reference
ActionDebug Class Reference
Private Member Functions
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool HasTarget ()
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void Start (ActionData action_data)
override bool UseAcknowledgment ()
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 12 of file actiondebug.c.
Member Function Documentation
CreateActionData()
override ActionData ActionDebug::CreateActionData () inline private
Definition at line 25 of file actiondebug.c.
    {
        ActionDebugData action_data = new ActionDebugData;
        return action_data;
    }
Referenced by SetupAction().
CreateConditionComponents()
override void ActionDebug::CreateConditionComponents () inline private
Definition at line 19 of file actiondebug.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HandleReciveData()
override void ActionDebug::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 86 of file actiondebug.c.
    {
        ActionDebugReciveData action_recive_data_d = ActionDebugReciveData.Cast(action_recive_data);
        ActionDebugData action_data_d = ActionDebugData.Cast(action_data);
        action_data_d.m_MainItem = action_recive_data_d.m_Item;
        action_data_d.m_DebugActionID = action_recive_data_d.m_DebugActionID;
    }
References ActionDebugReciveData::m_DebugActionID, and ActionDebugReciveData::m_Item.
Referenced by SetupAction().
HasTarget()
override bool ActionDebug::HasTarget () inline private
Definition at line 14 of file actiondebug.c.
    {
        return false;
    }
ReadFromContext()
override bool ActionDebug::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 64 of file actiondebug.c.
    {
        if(!action_recive_data)
        {
            action_recive_data = new ActionDebugReciveData;
        }
        ActionDebugReciveData action_recive_data_d = ActionDebugReciveData.Cast(action_recive_data);
        ItemBase item;
        int debugActionID;
        if(!ctx.Read(item))
            return false;
        if(!ctx.Read(debugActionID))
            return false;
        action_recive_data_d.m_Item = item;
        action_recive_data_d.m_DebugActionID = debugActionID;
        return true;
    }
References ActionDebugReciveData::m_DebugActionID, ActionDebugReciveData::m_Item, and Serializer::Read().
SetupAction()
override bool ActionDebug::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 31 of file actiondebug.c.
    {
        ActionDebugData action_data_d;
        Class.CastTo( action_data_d, CreateActionData());
        action_data_d.m_Action = this;
        action_data_d.m_Player = player;
        if (!GetGame().IsDedicatedServer() )
        {
            ref Param2<ItemBase,int> ndata = Param2<ItemBase,int>.Cast( extra_data );
            action_data_d.m_MainItem = ndata.param1;
            action_data_d.m_DebugActionID = ndata.param2;
        }
        ActionReciveData action_recive_data = player.GetActionManager().GetReciveData();
        if ( action_recive_data )
        {
            HandleReciveData(action_recive_data,action_data_d);
        }
        action_data = action_data_d;
        return true;
    }
References Class::CastTo(), CreateActionData(), GetGame(), and HandleReciveData().
Start()
override void ActionDebug::Start (ActionData action_data) inline private
Definition at line 95 of file actiondebug.c.
    {
        ActionDebugData action_data_d;
        Class.CastTo( action_data_d, action_data );
        action_data_d.m_MainItem.OnAction(action_data_d.m_DebugActionID,action_data_d.m_Player,NULL);
    }
References Class::CastTo().
UseAcknowledgment()
override bool ActionDebug::UseAcknowledgment () inline private
Definition at line 103 of file actiondebug.c.
    {
        return false;
    }
WriteToContext()
override void ActionDebug::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 55 of file actiondebug.c.
    {
        ActionDebugData action_data_d;
        Class.CastTo( action_data_d, action_data );
        ctx.Write(action_data_d.m_MainItem);
        ctx.Write(action_data_d.m_DebugActionID);
    }
References Class::CastTo(), and Serializer::Write().