DayzKode: HandEventDrop Class Reference
HandEventDrop Class Reference
Private Member Functions
override InventoryLocation GetDst ()
vector GetForce ()
void HandEventThrow (Man p=null, InventoryLocation src=null)
override void ReadFromContext (ParamsReadContext ctx)
void SetForce (vector force)
override void WriteToContext (ParamsWriteContext ctx)
Private Attributes
ref InventoryLocation m_Dst
vector m_Force
Detailed Description
Definition at line 346 of file hand_events.c.
Member Function Documentation
GetDst()
override InventoryLocation HandEventDrop::GetDst () inline private
Definition at line 368 of file hand_events.c.
    {
        return m_Dst;
    }
References m_Dst.
Referenced by HandEventBase::AcquireInventoryJunctureFromServer(), HandEventBase::CanPerformEvent(), and HandEventBase::CheckRequest().
GetForce()
vector HandEventDrop::GetForce () inline private
Definition at line 400 of file hand_events.c.
{ return m_Force; }
References m_Force.
HandEventThrow()
void HandEventDrop::HandEventThrow (Man p = null, InventoryLocation src = null) inline private
Definition at line 348 of file hand_events.c.
    {
        m_EventID = HandEventID.THROW;
        if( src )
        {
            vector mat[4];
            EntityAI entity = GetSrcEntity();
            if (entity)
            {
                m_Dst = new InventoryLocation;
                entity.GetTransform(mat);
                m_Dst.SetGround(entity, mat);
            }
            else
            {
                Error("[hndfsm] HandEventThrow src entity null!");
            }
        }
    }
References Error(), GetSrcEntity(), and m_EventID.
ReadFromContext()
override void HandEventDrop::ReadFromContext (ParamsReadContext ctx) inline private
Definition at line 373 of file hand_events.c.
    {
        super.ReadFromContext(ctx);
        m_Dst = new InventoryLocation;
        m_Dst.ReadFromContext(ctx);
        float x, y, z;
        ctx.Read(x);
        ctx.Read(y);
        ctx.Read(z);
        m_Force[0] = x;
        m_Force[1] = y;
        m_Force[2] = z;
    }
References Serializer::Read(), InventoryLocation::ReadFromContext(), x, and y.
SetForce()
void HandEventDrop::SetForce (vector force) inline private
Definition at line 399 of file hand_events.c.
{ m_Force = force; }
WriteToContext()
override void HandEventDrop::WriteToContext (ParamsWriteContext ctx) inline private
Definition at line 388 of file hand_events.c.
    {
        super.WriteToContext(ctx);
        m_Dst.WriteToContext(ctx);
        ctx.Write(m_Force[0]);
        ctx.Write(m_Force[1]);
        ctx.Write(m_Force[2]);
    }
References Serializer::Write().
Member Data Documentation
m_Dst
ref InventoryLocation HandEventDrop::m_Dst private
Definition at line 404 of file hand_events.c.
Referenced by GetDst().
m_Force
vector HandEventDrop::m_Force private
Definition at line 402 of file hand_events.c.
Referenced by GetForce().