DayzKode: FirearmActionAttachMagazine Class Reference
FirearmActionAttachMagazine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool CanBePerformedFromInventory ()
override bool CanBePerformedFromQuickbar ()
override ActionData CreateActionData ()
void FirearmActionAttachMagazine ()
override int GetActionCategory ()
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override bool InventoryReservation (ActionData action_data)
override bool Post_SetupAction (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
override void Start (ActionData action_data)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 11 of file firearmactionattachmagazine.c.
Constructor & Destructor Documentation
FirearmActionAttachMagazine()
void FirearmActionAttachMagazine::FirearmActionAttachMagazine () inline private
Definition at line 16 of file firearmactionattachmagazine.c.
    {
        m_Text = "#attach";
    }
References m_Text.
Member Function Documentation
ActionCondition()
override bool FirearmActionAttachMagazine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 26 of file firearmactionattachmagazine.c.
    {
        if (!super.ActionCondition( player, target, item ))
            return false;
        HumanCommandWeapons hcw = player.GetCommandModifier_Weapons();
        Magazine mag = Magazine.Cast(target.GetObject());
        Weapon_Base wpn = Weapon_Base.Cast(item);
        return mag && (player.GetWeaponManager().CanAttachMagazine(wpn,mag) || player.GetWeaponManager().CanSwapMagazine(wpn,mag)) && (!hcw || hcw.GetRunningAction() != WeaponActions.RELOAD);
    }
References HumanCommandWeapons::GetRunningAction().
ActionConditionContinue()
override bool FirearmActionAttachMagazine::ActionConditionContinue (ActionData action_data) inline private
Definition at line 37 of file firearmactionattachmagazine.c.
    {
        return true;
    }
CanBePerformedFromInventory()
override bool FirearmActionAttachMagazine::CanBePerformedFromInventory () inline private
Definition at line 213 of file firearmactionattachmagazine.c.
    {
        return true;
    }
CanBePerformedFromQuickbar()
override bool FirearmActionAttachMagazine::CanBePerformedFromQuickbar () inline private
Definition at line 218 of file firearmactionattachmagazine.c.
    {
        return true;
    }
CreateActionData()
override ActionData FirearmActionAttachMagazine::CreateActionData () inline private
Definition at line 42 of file firearmactionattachmagazine.c.
    {
        AttachMagazineActionData action_data = new AttachMagazineActionData;
        return action_data;
    }
GetActionCategory()
override int FirearmActionAttachMagazine::GetActionCategory () inline private
Definition at line 21 of file firearmactionattachmagazine.c.
    {
        return AC_SINGLE_USE;
    }
References AC_SINGLE_USE.
HandleReciveData()
override void FirearmActionAttachMagazine::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 77 of file firearmactionattachmagazine.c.
    {
        AttachMagazineActionReciveData recive_data_am = AttachMagazineActionReciveData.Cast(action_recive_data);
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        action_data.m_MainItem = action_recive_data.m_MainItem;
        if (!action_recive_data.m_Target)
        {
            action_data.m_Target = new ActionTarget(NULL, NULL, -1, vector.Zero, 0);
        }
        else
        {
            action_data.m_Target = action_recive_data.m_Target;
        }
        action_data_am.m_ilOldMagazine = recive_data_am.m_ilOldMagazine;
    }
References ActionTarget, AttachMagazineActionReciveData::m_ilOldMagazine, ActionData::m_MainItem, ActionData::m_Target, and vector::Zero.
InventoryReservation()
override bool FirearmActionAttachMagazine::InventoryReservation (ActionData action_data) inline private
Definition at line 115 of file firearmactionattachmagazine.c.
    {
        if( (IsLocal() || !UseAcknowledgment()) && IsInstant() )
            return true;
        bool success = true;
        InventoryLocation oldMagTargetInventoryLocation = NULL;
        InventoryLocation targetInventoryLocation = NULL;
        InventoryLocation handInventoryLocation = NULL;
        PlayerBase player = action_data.m_Player;
        AttachMagazineActionData am_action_data = AttachMagazineActionData.Cast(action_data);
        Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
        int muzzle_index = wpn.GetCurrentMuzzle();
        Magazine new_mag = Magazine.Cast(action_data.m_Target.GetObject());
        if (am_action_data.m_oldMagazine)
        {
            oldMagTargetInventoryLocation = new InventoryLocation;
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( am_action_data.m_oldMagazine, am_action_data.m_ilOldMagazine) )
            {
                success = false;
            }
            else
            {
                player.GetInventory().AddInventoryReservationEx(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine,GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if (success)
        {
            targetInventoryLocation = new InventoryLocation;
            targetInventoryLocation.SetAttachment( wpn, new_mag, InventorySlots.MAGAZINE);
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( new_mag, targetInventoryLocation) )
            {
                success = false;
                if (am_action_data.m_oldMagazine)
                {
                    player.GetInventory().ClearInventoryReservation(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine);
                }
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( new_mag, targetInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if (success)
        {
            handInventoryLocation = new InventoryLocation;
            handInventoryLocation.SetHands(action_data.m_Player, wpn);
            if ( action_data.m_Player.GetInventory().HasInventoryReservation( wpn, handInventoryLocation) )
            {
                if (am_action_data.m_oldMagazine)
                {
                    player.GetInventory().ClearInventoryReservation(am_action_data.m_oldMagazine,am_action_data.m_ilOldMagazine);
                }
                player.GetInventory().ClearInventoryReservation(new_mag, targetInventoryLocation);
                success = false;
            }
            else
            {
                action_data.m_Player.GetInventory().AddInventoryReservationEx( wpn, handInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
        }
        if ( success )
        {
            if (am_action_data.m_ilOldMagazine)
                action_data.m_ReservedInventoryLocations.Insert(am_action_data.m_ilOldMagazine);
            if (targetInventoryLocation)
                action_data.m_ReservedInventoryLocations.Insert(targetInventoryLocation);
            if (handInventoryLocation)
                action_data.m_ReservedInventoryLocations.Insert(handInventoryLocation);
        }
        return success;
    }
References IsInstant(), IsLocal(), ActionData::m_MainItem, ActionData::m_Player, ActionData::m_ReservedInventoryLocations, ActionData::m_Target, InventoryLocation::SetAttachment(), InventoryLocation::SetHands(), and UseAcknowledgment().
Referenced by Start().
Post_SetupAction()
override bool FirearmActionAttachMagazine::Post_SetupAction (ActionData action_data) inline private
Definition at line 94 of file firearmactionattachmagazine.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
            int muzzle_index = wpn.GetCurrentMuzzle();
            AttachMagazineActionData am_action_data = AttachMagazineActionData.Cast(action_data);
            am_action_data.m_oldMagazine = wpn.GetMagazine(muzzle_index);
            InventoryLocation new_il = new InventoryLocation;
            if (!action_data.m_Player.GetWeaponManager().PrepareInventoryLocationForMagazineSwap(wpn, Magazine.Cast(action_data.m_Target.GetObject()), new_il))
            {
                return false;
            }
            am_action_data.m_ilOldMagazine = new_il;
        }
        return true;
    }
References GetGame(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
ReadFromContext()
override bool FirearmActionAttachMagazine::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 58 of file firearmactionattachmagazine.c.
    {
        if (!action_recive_data)
        {
            action_recive_data = new AttachMagazineActionReciveData;
        }
        super.ReadFromContext(ctx, action_recive_data);
        InventoryLocation il = new InventoryLocation;
        if (!il.ReadFromContext(ctx))
            return false;
        AttachMagazineActionReciveData recive_data_am = AttachMagazineActionReciveData.Cast(action_recive_data);
        recive_data_am.m_ilOldMagazine = il;
        return true;
    }
References AttachMagazineActionReciveData::m_ilOldMagazine, and InventoryLocation::ReadFromContext().
Start()
override void FirearmActionAttachMagazine::Start (ActionData action_data) inline private
Definition at line 199 of file firearmactionattachmagazine.c.
    {
        super.Start( action_data );
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        Weapon_Base wpn = Weapon_Base.Cast(action_data.m_MainItem);
        Magazine mag = Magazine.Cast(action_data.m_Target.GetObject());
        ClearInventoryReservationEx(action_data);
        if ( action_data.m_Player.GetWeaponManager().CanAttachMagazine(wpn,mag,false) )
            action_data.m_Player.GetWeaponManager().AttachMagazine(mag, this);
        else
            action_data.m_Player.GetWeaponManager().SwapMagazineEx(mag, action_data_am.m_ilOldMagazine, this);
         InventoryReservation(action_data);
    }
References ClearInventoryReservationEx(), InventoryReservation(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
WriteToContext()
override void FirearmActionAttachMagazine::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 49 of file firearmactionattachmagazine.c.
    {
        super.WriteToContext(ctx, action_data);
        AttachMagazineActionData action_data_am = AttachMagazineActionData.Cast(action_data);
        action_data_am.m_ilOldMagazine.WriteToContext(ctx);
    }