DayzKode: ToggleLightsActionInput Class Reference
ToggleLightsActionInput Class Reference
Private Member Functions
override ActionBase GetAction ()
void ToggleLightsActionInput (PlayerBase player)
override void UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask)
Private Attributes
ref ActionTarget target_new
Detailed Description
Definition at line 746 of file actioninput.c.
Constructor & Destructor Documentation
ToggleLightsActionInput()
void ToggleLightsActionInput::ToggleLightsActionInput (PlayerBase player) inline private
Definition at line 750 of file actioninput.c.
    {
        SetInput("UAToggleHeadlight");
        m_InputType = ActionInputType.AIT_SINGLE;
        m_Priority = 100;
    }
References m_Priority, and SetInput().
Member Function Documentation
GetAction()
override ActionBase ToggleLightsActionInput::GetAction () inline private
Definition at line 829 of file actioninput.c.
    {
        return m_SelectAction;
    }
References m_SelectAction.
UpdatePossibleActions()
override void ToggleLightsActionInput::UpdatePossibleActions (PlayerBase player, ActionTarget target, ItemBase item, int action_condition_mask) inline private
Definition at line 757 of file actioninput.c.
    {
        if( ForceActionCheck(player) )
        {
            m_SelectAction = m_ForcedActionData.m_Action;
            return;
        }
        //ForceActionTarget(player.m_PlayerLightManager.
        m_SelectAction = NULL;
        array<ActionBase_Basic> possible_actions;
        ActionBase action;
        int i;
        m_MainItem = NULL;
        if ( player && !player.IsInVehicle() )
        {
            Clothing headgear = Clothing.Cast(player.FindAttachmentBySlotName("Headgear"));
            Clothing eyewear = Clothing.Cast(player.FindAttachmentBySlotName("Eyewear"));
            //TODO - extend this to allow for a switchable control over all possible light sources (depth 0 or 1 only?)
            if ( headgear && headgear.GetLightSourceItem() )
            {
                target_new = new ActionTarget(headgear, null, -1, vector.Zero, -1);
                ForceActionTarget(target_new);
            }
            else if ( eyewear && eyewear.GetLightSourceItem() )
            {
                target_new = new ActionTarget(eyewear, null, -1, vector.Zero, -1);
                ForceActionTarget(target_new);
            }
            else
                ClearForcedTarget();
        }
        else if ( player && player.IsInVehicle() )
        {
            HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
            if( vehCommand )
            {
                Transport trans = vehCommand.GetTransport();
                if( trans )
                {
                    target_new = new ActionTarget(trans, null, -1, vector.Zero, -1);
                    ForceActionTarget(target_new);
                }
            }
            if ( !target_new )
                ClearForcedTarget();
        }
        target = m_ForcedTarget;
        m_Target = m_ForcedTarget;
        if(target && target.GetObject())
        {
            target.GetObject().GetActions(this.Type(), possible_actions);
            if(possible_actions)
            {
                for (i = 0; i < possible_actions.Count(); i++)
                {
                    action = ActionBase.Cast(possible_actions.Get(i));
                    if ( action.Can(player, target, m_MainItem, action_condition_mask) )
                    {
                        m_SelectAction = action;
                        return;
                    }
                }
            }
        }
    }
References ActionBase(), ActionTarget, Clothing::GetLightSourceItem(), HumanCommandVehicle::GetTransport(), m_MainItem, m_SelectAction, m_Target, target_new, Type, and vector::Zero.
Member Data Documentation
target_new
ref ActionTarget ToggleLightsActionInput::target_new private
Definition at line 748 of file actioninput.c.
Referenced by UpdatePossibleActions().