DayzKode: DayZAIHitComponentHelpers Class Reference
DayZAIHitComponentHelpers Class Reference
Static Private Member Functions
static void RegisterHitComponent (array< ref DayZAIHitComponent > pHitComponents, string pName, float pWeight)
Register Hit Component for AI targeting.
static bool SelectMostProbableHitComponent (array< ref DayZAIHitComponent > pHitComponents, out string pHitComponent)
static int SumOfWeights (array< ref DayZAIHitComponent > pHitComponents)
Calculates the sum of all entries in DayZAIHitComponent array.
Detailed Description
Definition at line 8 of file dayzaihitcomponents.c.
Member Function Documentation
RegisterHitComponent()
DayZAIHitComponentHelpers::RegisterHitComponent (array< ref DayZAIHitComponent > pHitComponents, string pName, float pWeight) inline static private
Register Hit Component for AI targeting.
Register Hit Component for AI targeting to array defined on entity's Type (DayZPlayerType, DayZInfectedType, etc.) Uses component name from damage system (zone) and its weight.
Parameters
[in] pHitComponents array that keeps registered compoenents
[in] pName component name (zone in Damage System)
[in] pWeight weight of the component (probability)
Definition at line 21 of file dayzaihitcomponents.c.
    {
        DayZAIHitComponent newComponent = new DayZAIHitComponent();
        newComponent.m_Name = pName;
        newComponent.m_Weight = pWeight;
        pHitComponents.Insert(newComponent);
    }
References DayZAIHitComponent::m_Name, and DayZAIHitComponent::m_Weight.
Referenced by IsRefresherSignalingViable(), RegisterHitComponentsForAI(), DayZCreatureAI::RegisterHitComponentsForAI(), and AnimalBase::RegisterHitComponentsForAI().
SelectMostProbableHitComponent()
static bool DayZAIHitComponentHelpers::SelectMostProbableHitComponent (array< ref DayZAIHitComponent > pHitComponents, out string pHitComponent) inline static private
Definition at line 40 of file dayzaihitcomponents.c.
    {
        int weights = SumOfWeights(pHitComponents);
        float rnd = Math.RandomInt(0, weights);
        for ( int i = 0; i < pHitComponents.Count(); ++i )
        {
            DayZAIHitComponent hitComp = pHitComponents.Get(i);
            rnd -= hitComp.m_Weight;
            if (rnd <= 0)
            {
                pHitComponent = hitComp.m_Name;
                return true;
            }
        }
        return false;
    }
References DayZAIHitComponent::m_Name, DayZAIHitComponent::m_Weight, Math::RandomInt(), and SumOfWeights().
Referenced by GetHitComponentForAI(), and DayZCreatureAI::GetHitComponentForAI().
SumOfWeights()
DayZAIHitComponentHelpers::SumOfWeights (array< ref DayZAIHitComponent > pHitComponents) inline static private
Calculates the sum of all entries in DayZAIHitComponent array.
Parameters
[in] pHitComponents array that keeps registered compoenents
Returns
Sum of weights of all entries in array
Definition at line 68 of file dayzaihitcomponents.c.
    {
        int sum = 0;
        for( int i = 0; i < pHitComponents.Count(); ++i )
        {
            DayZAIHitComponent hitComp = pHitComponents.Get(i);
            sum += hitComp.m_Weight;
        }
        return sum;
    }
References DayZAIHitComponent::m_Weight.
Referenced by SelectMostProbableHitComponent().