DayzKode: vector Class Reference
vector Class Reference
Private Member Functions
proto vector AnglesToVector ()
Converts spherical coordinates (yaw, pitch, roll in degrees) to unit length vector.
vector GetRelAngles ()
Returns relative angles between -180 and 180, not 0 to 360.
proto vector InvMultiply3 (vector mat[3])
Invert-transforms vector.
proto vector InvMultiply4 (vector mat[4])
Invert-transforms position.
proto native float Length ()
Returns length of vector (magnitude)
proto native float LengthSq ()
Returns squared length (magnitudeSqr)
proto vector Multiply3 (vector mat[3])
Transforms vector.
proto vector Multiply4 (vector mat[4])
Transforms position.
proto float Normalize ()
Normalizes vector. Returns length.
proto vector Normalized ()
return normalized vector (keeps orginal vector untouched)
vector Perpend ()
Returns perpendicular vector. Perpendicular vector is computed as cross product between input vector and up vector (0, 1, 0).
proto void RotationMatrixFromAngles (out vector mat[3])
Creates rotation matrix from angles.
proto string ToString (bool beautify=true)
Vector to string.
proto vector VectorToAngles ()
Converts vector to spherical coordinates with radius = 1.
proto float VectorToYaw ()
Returns yaw of vector.
Static Private Member Functions
static vector ArrayToVec (float arr[])
Covert static array of floats into a vector.
static vector Direction (vector p1, vector p2)
Returns direction vector from point p1 to point p2.
static proto native float Distance (vector v1, vector v2)
Returns the distance between tips of two 3D vectors.
static proto native float DistanceSq (vector v1, vector v2)
Returns the squere distance between tips of two 3D vectors.
static float Dot (vector v1, vector v2)
Returns Dot product of vector v1 and vector v2.
static proto native vector Lerp (vector v1, vector v2, float t)
Lerp between two vectors.
static vector RandomDir ()
Returns randomly generated unit vector.
static vector RandomDir2D ()
Returns randomly generated XZ unit vector with the Y(up) axis set to 0.
static vector RotateAroundPoint (vector point, vector pos, vector axis, float cosAngle, float sinAngle)
Rotate a vector around point.
static vector RotateAroundZero (vector pos, vector axis, float cosAngle, float sinAngle)
Rotate a vector around 0,0,0.
static vector RotateAroundZeroDeg (vector vec, vector axis, float angle)
Rotate a vector around 0,0,0 by an angle in degrees.
static vector RotateAroundZeroRad (vector vec, vector axis, float angle)
Rotate a vector around 0,0,0 by an angle in radians.
proto static native vector YawToVector (float yaw)
Returns vector of yaw.
Static Private Attributes
static const vector Aside = "1 0 0"
static const vector Forward = "0 0 1"
static const vector Up = "0 1 0"
static const vector Zero = "0 0 0"
Detailed Description
Definition at line 99 of file enconvert.c.
Member Function Documentation
AnglesToVector()
proto vector vector::AnglesToVector () private
Converts spherical coordinates (yaw, pitch, roll in degrees) to unit length vector.
Returns
normalized direction vector
vector v1 = "45 0 0";
vector v2 = "15 60 0";
Print(v1.AnglesToVector());
Print(v2.AnglesToVector());
>> <0.707107,0,0.707107>
>> <0.12941,0.866025,0.482963>
Referenced by ItemBase::DoMeasurement(), DrawDebugShape(), DayZPlayerImplementThrowing::HandleThrowing(), IsEntityBehindEntityInAngle(), BaseBuildingBase::IsPlayerInside(), and TentBase::IsPlayerInside().
ArrayToVec()
static vector vector::ArrayToVec (float arr[]) inline static private
Covert static array of floats into a vector.
Parameters
arr vector in array format
Returns
vector resulting vector
Definition at line 496 of file enconvert.c.
    {
        return Vector(arr[0], arr[1], arr[2]);
    }
References Vector().
Referenced by ObjectSpawnerHandler::SpawnObject().
Direction()
static vector vector::Direction (vector p1, vector p2) inline static private
Returns direction vector from point p1 to point p2.
Parameters
p1 vector point from
p2 vector point to
Returns
vector direction vector
Definition at line 214 of file enconvert.c.
    {
        vector dir_vec;
        dir_vec[0] = p2[0] - p1[0];
        dir_vec[1] = p2[1] - p1[1];
        dir_vec[2] = p2[2] - p1[2];
        return dir_vec;
    }
Referenced by EntityLightSource::AttachOnMemoryPoint(), CarScript(), WeaponParticlesBase::CheckOrientationOverride(), and UIScriptedMenu::Update().
Distance()
static proto native float vector::Distance (vector v1, vector v2) static private
Returns the distance between tips of two 3D vectors.
Parameters
v1 vector 3D Vector 1
v2 vector 3D Vector 2
Returns
float Distance
float dist = vector.Distance("1 2 3", "4 5 6");
Print(dist);
>> dist = 5.19615
Referenced by ActionFillBrakes::ActionCondition(), ActionFillCoolant::ActionCondition(), ActionFillOil::ActionCondition(), ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), BotSelectNearestTarget(), Environment::CalcTemperatureFromTemperatureSource(), PluginBase::CalcTemperatureFromTemperatureSource(), PropertyModifiers::CalculateBarrelLength(), CalculateEyeAccoTarget(), CanReachSeatFromDoors(), DayZInfected::ChaseAttackLogic(), CheckAllowUpdate(), PoweredOptic_Base::DoMeasurement(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), UniversalTemperatureSourceLambdaBase::DryItemsInVicinity(), ContaminatedArea_Dynamic::EEOnCECreate(), EffBulletImpactBase::Event_OnStarted(), ExplosionEffects(), DayZInfected::FightAttackLogic(), GetCeilingHeight(), GetClosestCarWheel(), GetMeleeTargetEx(), GetMouseDistance(), ItemBase::GetNearestSlotIDByState(), Hologram::GetProjectionEntityPosition(), BaseBuildingBase::HasProperDistance(), HitZoneSelection(), AttachmentsOutOfReach::IsAttachmentReachable(), ComponentEnergyManager::IsEnergySourceAtReach(), IsObstructed(), ManBase::IsTargetInActiveRefresherRange(), Hit_MeatBones::OnEnterCalculations(), Grenade_Base::OnExplosionEffects(), Achievements::OnPlayerKilled(), AnalyticsManagerServer::OnPlayerToPlayerHit(), InventoryActionHandler::OnUpdate(), OnUpdate(), BotStateBase::OnUpdate(), PluginBase::PlayerHitBy(), PluginBase::PlayerKilled(), Pulling(), PluginRecipesManagerBase::RecipeSanityCheck(), Hud::RefreshPlayerTags(), VicinityItemManager::RefreshVicinityItems(), UIScriptedMenu::SetCameraData(), Hologram::SetHologramPosition(), DeveloperTeleport::TeleportAtCursor(), EntityLightSource::TryShadowOptimization(), UpdateDistanceWidget(), and PluginBase::UpdateStatWidget().
DistanceSq()
static proto native float vector::DistanceSq (vector v1, vector v2) static private
Returns the squere distance between tips of two 3D vectors.
Parameters
v1 vector 3D Vector 1
v2 vector 3D Vector 2
Returns
float Squere distance
float dist = vector.DistanceSq("0 0 0", "0 5 0");
Print(dist);
>> dist = 25
Referenced by ActionFillFuel::ActionCondition(), ActionEnterLadder::ActionCondition(), ActionTriggerRemotely::ActionCondition(), CCTCursor::Can(), CCTCursorNoObject::Can(), CCTCursorNoRuinCheck::Can(), CCTCursorParent::Can(), CCTMan::Can(), CCTNonRuined::Can(), CCTObject::Can(), CCTParent::Can(), CCTSurface::Can(), CCTTree::Can(), CCTWaterSurface::Can(), ActionTargets::ComputeUtility(), ComponentEnergyManager::DebugUpdate(), ActionTargets::DistSqrPoint2Line(), ActionRepackTentCB::DropDuringRepacking(), ContaminatedArea_Dynamic::EEOnCECreate(), EvaluateComponentEx(), DayZInfected::FightLogic(), FilterObstructedObjectsByGrouping(), Environment::GatherTemperatureSources(), GetClosestDoor(), GetClosestSafePos(), GetMeleeTargetEx(), ScriptedWidgetEventHandler::GetOnScreenPosition(), Hologram::GetProjectionEntityPosition(), HitZoneSelectionRaycast(), IsInReach(), IsObjectObstructedEx(), IsPlaceable(), ItemBase::IsPlaceable(), IsShortDistance(), WeaponStateBase::OnAbort(), OnAbort(), RemoteDetonatorTrigger::OnActivatedByItem(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), ActionEmptyMagazine::OnExecuteServer(), WeaponStateBase::OnExit(), Grenade_Base::OnExplosionEffects(), OnRPC(), FliesMdfr::OnTick(), PluginBase::ProcessUniversalTemperatureSources(), RefreshFireplaceVisuals(), VicinityItemManager::RefreshVicinityItems(), ResizeParticle(), FlareSimulation::Simulate(), SplitArrayIntoGroupsByDistance(), ManBase::SpreadAgentsEx(), TargetSelection(), and AreaDamageTriggerBase::UpdateInsiders().
Dot()
static float vector::Dot (vector v1, vector v2) inline static private
Returns Dot product of vector v1 and vector v2.
Parameters
v1 vector input vector
v2 vector input vector
Returns
vector direction vector
Definition at line 265 of file enconvert.c.
    {
        return ((v1[0] * v2[0]) + (v1[1] * v2[1]) + (v1[2] * v2[2]));
    }
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), CanBeIgnitedBy(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), ActionTargets::DistSqrPoint2Line(), DropAllItemsInInventoryInBounds(), DayZInfected::EvaluateCrawlTransitionAnimation(), EvaluateDamageHitAnimation(), EvaluateDeathAnimation(), EffBulletImpactBase::Event_OnStarted(), VicinityItemManager::ExcludeFromContainer_Phase1(), FilterObstructedObjectsByGrouping(), HitZoneSelectionRaycast(), IsEntityBehindEntityInAngle(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), IsPlayerOrientedTowardPos(), OnAttachmentRuined(), RotateAroundZero(), RotateAroundZeroDeg(), and RotateAroundZeroRad().
GetRelAngles()
vector vector::GetRelAngles () inline private
Returns relative angles between -180 and 180, not 0 to 360.
Returns
float Relative angles
vector angles = "-45 190 160";
Print(angles.GetRelAngles());
>> <-45,-170,160>
Definition at line 280 of file enconvert.c.
    {
        for(int i = 0; i < 3; i++) {
            if(value[i] > 180)
                value[i] = value[i] - 360;
            if(value[i] < -180)
                value[i] = value[i] + 360;
        }
        return value;
    }
InvMultiply3()
proto vector vector::InvMultiply3 (vector mat[3]) private
Invert-transforms vector.
Parameters
mat vector[3] transformation matrix
vec vector vector to transform
Returns
vector transformed vector
vector mat[3] = { "1.5 2.5 0", "0.1 1.3 0", "0 0 1" }; // rotation matrix
vector vec = "1 1 1";
Print(vec.InvMultiply3(mat));
>> <4,1.4,1>
Referenced by OnUpdate().
InvMultiply4()
proto vector vector::InvMultiply4 (vector mat[4]) private
Invert-transforms position.
Parameters
mat vector[4] transformation matrix
vec vector position to transform
Returns
vector transformed position
vector mat[4] = { "1 0 0 0", "0 1 0 0", "0 0 1 1", "3 1 2 1" }; // translation matrix
vector pos = "1 1 1";
Print(pos.InvMultiply4(mat));
>> <-2,0,-1>
Referenced by OnUpdate().
Length()
proto native float vector::Length () private
Returns length of vector (magnitude)
Returns
float Length of vector
vector vec = "1 0 1";
float length = vec.Length();
Print(length);
>> length = 1.41421
Referenced by Hologram::AlignProjectionOnTerrain(), EffBulletImpactBase::EvaluateEffect(), EffBulletImpactBase::Event_OnStarted(), Hit_MeatBones::Event_OnStarted(), FirearmEffects(), Hologram::GetProjectionDiameter(), Hologram::GetProjectionRadius(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), EntityAI::ProcessImpactSound(), and UIScriptedMenu::Update().
LengthSq()
proto native float vector::LengthSq () private
Returns squared length (magnitudeSqr)
Returns
float Length of vector
vector vec = "1 1 0";
float length = vec.LengthSq();
Print(length);
>> length = 2
Referenced by ManBase::BrokenLegWalkShock(), and DayZPlayerUtils::GetMeleeTarget().
Lerp()
static proto native vector vector::Lerp (vector v1, vector v2, float t) static private
Lerp between two vectors.
vector v1 = Vector(0,0,0);
vector v2 = Vector(5,6,1);
Print(vector.Lerp(v1, v2, 0.5));
Multiply3()
proto vector vector::Multiply3 (vector mat[3]) private
Transforms vector.
Parameters
mat vector[3] transformation matrix
vec vector vector to transform
Returns
vector transformed vector
vector mat[3] = { "2 0 0", "0 3 0", "0 0 1" }; // scale matrix
vector vec = "1 1 1";
Print(vec.Multiply3(mat));
>> <2,3,1>
Multiply4()
proto vector vector::Multiply4 (vector mat[4]) private
Transforms position.
Parameters
mat vector[4] transformation matrix
vec vector position to transform
Returns
vector transformed position
vector mat[4] = { "1 0 0 0", "0 1 0 0", "0 0 1 1", "3 1 2 1" }; // translation matrix
vector pos = "1 1 1";
Print(pos.Multiply4(mat));
>> <4,2,3>
Referenced by PluginBase::CalculatePos(), and DayZIntroScene::DayZIntroScene().
Normalize()
proto float vector::Normalize () private
Normalizes vector. Returns length.
Returns
float Length of origin vector
vector vec = "1 0 1";
float length = vec.Normalize();
Print(vec);
Print(length);
>> vec = <0.707107,0,0.707107>
>> length = 1.41421
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), CreateArrow(), CreateBridgeArrow(), ComponentEnergyManager::DrawArrow(), WeaponDebug::DrawLineOfFireCameraHybrid(), DayZInfected::EvaluateCrawlTransitionAnimation(), EvaluateDamageHitAnimation(), EvaluateDeathAnimation(), VicinityItemManager::ExcludeFromContainer_Phase1(), IsEntityBehindEntityInAngle(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), IsPlayerOrientedTowardPos(), KuruShake::KuruShake(), MeleeTargetSettings(), OnEndServer(), PluginBase::OnUpdate(), PluginBase::SelectedObjectFocus(), and Hologram::SetHologramPosition().
Normalized()
proto vector vector::Normalized () private
return normalized vector (keeps orginal vector untouched)
Referenced by CarScript(), CreateAndSetupActionCallback(), Debug::DrawCone(), WeaponDebug::DrawLineOfFire(), EffBulletImpactBase::Event_OnStarted(), GetHeadingVector(), GetProjectedCursorPos3d(), Math3D::GetRandomDir(), RandomDir(), RandomDir2D(), UIScriptedMenu::Update(), and DayZIntroSceneXbox::UpdateCharacterPos().
Perpend()
vector vector::Perpend () inline private
Returns perpendicular vector. Perpendicular vector is computed as cross product between input vector and up vector (0, 1, 0).
Returns
vector perpendicular vector
vector vec = "1 0 0";
Print(vec.Perpend());
>> <0,0,1>
Definition at line 203 of file enconvert.c.
    {
        return value * vector.Up;
    }
References Up.
Referenced by TrapSpawnBase::AlignCatch(), CreateArrow(), CreateBridgeArrow(), ComponentEnergyManager::DrawArrow(), and PluginBase::SpawnEntityOnGroundPatternGrid().
RandomDir()
static vector vector::RandomDir () inline static private
Returns randomly generated unit vector.
Returns
randomly generated unit vector
vector vec = vector.RandomDir();
Print(vec);
Print(vec.Length());
>> <-0.179424,0.966825,0.181816>
>> 1
Definition at line 237 of file enconvert.c.
    {
        return Vector(Math.RandomFloatInclusive(-1,1),Math.RandomFloatInclusive(-1,1),Math.RandomFloatInclusive(-1,1)).Normalized();
    }
References Normalized(), Math::RandomFloatInclusive(), and Vector().
RandomDir2D()
static vector vector::RandomDir2D () inline static private
Returns randomly generated XZ unit vector with the Y(up) axis set to 0.
Returns
randomly generated XZ unit vector
vector vec = vector.RandomDir();
Print(vec);
Print(vec.Length());
>> <0.631697,0,0.775216>
>> 1
Definition at line 254 of file enconvert.c.
    {
        return Vector(Math.RandomFloatInclusive(-1,1),0,Math.RandomFloatInclusive(-1,1)).Normalized();
    }
References Normalized(), Math::RandomFloatInclusive(), and Vector().
Referenced by ContaminatedArea_Dynamic::SpawnItems().
RotateAroundPoint()
static vector vector::RotateAroundPoint (vector point, vector pos, vector axis, float cosAngle, float sinAngle) inline static private
Rotate a vector around point.
Parameters
point point to rotate around
pos vector to rotate
axis axis to rotate around
cosAngle cos of angle
sinAngle sin of angle
Returns
vector transformed vector
Definition at line 485 of file enconvert.c.
    {
        vector offsetPos = pos - point;
        return RotateAroundZero(offsetPos, axis, cosAngle, sinAngle) + point;
    }
References RotateAroundZero().
RotateAroundZero()
static vector vector::RotateAroundZero (vector pos, vector axis, float cosAngle, float sinAngle) inline static private
Rotate a vector around 0,0,0.
Parameters
pos vector to rotate
axis axis to rotate around
cosAngle cos of angle
sinAngle sin of angle
Returns
vector transformed vector
Definition at line 471 of file enconvert.c.
    {
        return (pos * cosAngle) + ((axis * pos) * sinAngle) + (axis * vector.Dot(axis, pos)) * (1 - cosAngle);
    }
References Dot().
Referenced by FilterObstructedObjectsByGrouping(), EffectArea::PlaceParticles(), RotateAroundPoint(), and SetGroundPosByOwnerBounds().
RotateAroundZeroDeg()
static vector vector::RotateAroundZeroDeg (vector vec, vector axis, float angle) inline static private
Rotate a vector around 0,0,0 by an angle in degrees.
Parameters
vec vector to rotate
axis axis to rotate around
cosAngle angle in degrees
Returns
vector transformed vector
Definition at line 444 of file enconvert.c.
    {
        return (vec * Math.Cos(angle * Math.DEG2RAD)) + ((axis * vec) * Math.Sin(angle * Math.DEG2RAD)) + (axis * vector.Dot(axis, vec)) * (1 - Math.Cos(angle * Math.DEG2RAD));
    }
References Math::Cos(), Math::DEG2RAD, Dot(), and Math::Sin().
RotateAroundZeroRad()
static vector vector::RotateAroundZeroRad (vector vec, vector axis, float angle) inline static private
Rotate a vector around 0,0,0 by an angle in radians.
Parameters
vec vector to rotate
axis axis to rotate around
cosAngle angle in radians
Returns
vector transformed vector
Definition at line 457 of file enconvert.c.
    {
        return (vec * Math.Cos(angle)) + ((axis * vec) * Math.Sin(angle)) + (axis * vector.Dot(axis, vec)) * (1 - Math.Cos(angle));
    }
References Math::Cos(), Dot(), and Math::Sin().
RotationMatrixFromAngles()
proto void vector::RotationMatrixFromAngles (out vector mat[3]) private
Creates rotation matrix from angles.
Parameters
ang vector which contains angles
[out] mat vector created rotation matrix
vector mat[3];
vector ang = "70 15 45";
ang.RotationMatrixFromAngles(mat);
Print(mat);
>> <0.330366,0.0885213,-0.939693>,<0.458809,0.854988,0.241845>,<0.824835,-0.511037,0.241845>
ToString()
proto string vector::ToString (bool beautify = true) private
Vector to string.
Parameters
beautify If true verbose vector in more human readable form "<1, 1, 1>" instead of simple form "1 1 1"
Returns
string Converted vector as parsed string
vector v = "1 0 1";
Print(v.ToString());
Print(v.ToString(false));
>> '<1, 0, 1>'
>> '1 0 1'
Referenced by RecoilBase::ApplyMouseOffset(), PluginBase::CheckInit(), DbgShowBoneName(), PluginBase::GetPlayerPrefix(), SceneObject::GetPositionAsString(), UIScriptedMenu::Refresh(), UIScriptedMenu::SetCameraData(), and HudDebugWinBase::Update().
VectorToAngles()
proto vector vector::VectorToAngles () private
Converts vector to spherical coordinates with radius = 1.
Returns
vector spherical coordinates (yaw, pitch, roll in degrees)
vector v1 = "1 0 1";
vector v2 = "1 1 1";
Print(v1.VectorToAngles());
Print(v2.VectorToAngles());
>> <45,-0,0>
>> <45,35.2644,0>
Referenced by ActionEnterLadder::ActionCondition(), Hologram::AlignProjectionOnTerrain(), EntityLightSource::AttachOnMemoryPoint(), HitDirectionEffectBase::CalculateArrowPosition(), CarScript(), WeaponParticlesBase::CheckOrientationOverride(), ItemBase::DoMeasurement(), EffBulletImpactBase::Event_OnStarted(), Hologram::GetDefaultOrientation(), GetMeleeTargetEx(), CGame::GetSurfaceOrientation(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), FuelStation::OnExplosionEffects(), FireworksLauncher::OnFuseIgnitedClient(), VicinityItemManager::RefreshVicinityItems(), and UIScriptedMenu::Update().
VectorToYaw()
proto float vector::VectorToYaw () private
Returns yaw of vector.
Parameters
vec vector Vector to convert yaw
Returns
float Yaw of vector
vector v1 = "0 1 0";
vector v2 = "0.7 0.7 0";
Print(v1.ToYaw());
Print(v2.ToYaw());
>> 90
>> 45
YawToVector()
proto static native vector vector::YawToVector (float yaw) static private
Returns vector of yaw.
Parameters
yaw float Value of yaw
Returns
vector Yaw converted in vector
Print(vector.Yaw2Vector(90));
Print(vector.Yaw2Vector(45));
>> <0,1,0>
>> <0.707107,0.707107,0>
Referenced by RecoilBase::PostInit().
Member Data Documentation
Aside
const vector vector::Aside = "1 0 0" static private
Definition at line 102 of file enconvert.c.
Referenced by FilterObstructedObjectsByGrouping().
Forward
const vector vector::Forward = "0 0 1" static private
Definition at line 103 of file enconvert.c.
Referenced by DropAllItemsInInventoryInBounds(), and OnAttachmentRuined().
Up
const vector vector::Up = "0 1 0" static private
Definition at line 101 of file enconvert.c.
Referenced by CanBeIgnitedBy(), DayZSpectator::EOnFrame(), FilterObstructedObjectsByGrouping(), Perpend(), EffectArea::PlaceParticles(), and SetGroundPosByOwnerBounds().
Zero
const vector vector::Zero = "0 0 0" static private
Definition at line 104 of file enconvert.c.
Referenced by AddLightSource(), AreaDamageManager(), AreaDamageTriggerBase::AreaDamageTrigger(), ATCCachedObject::ATCCachedTarget(), CCTSurface::Can(), CCTWaterSurface::Can(), ActionManagerClient::CanPerformActionFromInventory(), ActionManagerClient::CanPerformActionFromQuickbar(), ActionManagerClient::CanSetActionFromInventory(), ManBase::CommandHandler(), CopyOldPropertiesToNew(), Particle::CreateParticleEffect(), Weapon::CreateWeaponWithAmmo(), DeployableContainer_Base(), EOnPostSimulate(), ExplosivesBase(), ActionManagerClient::FindActionTarget(), FirearmEffects(), FireplaceBase(), ActionManagerClient::ForceTarget(), GameplayEffectsData::GenerateSequenceRandomPosition(), DayZInfected::GetAttackPitch(), GetCurrentLocalPosition(), EffectParticle::GetCurrentOrientation(), GetCurrentPosition(), GetDefaultHitPosition(), Hologram::GetDefaultOrientation(), GetHeadingVector(), AITargetCallbacks::GetHeadPositionWS(), GetMemoryPointPosition(), ScriptedWidgetEventHandler::GetOnScreenPosition(), Hologram::GetProjectionEntityPosition(), Hologram::GetProjectionOrientation(), Hologram::GetProjectionPosition(), AreaDamageComponentRaycasted::GetRaycastedHitZone(), GetValveAligningPointsWS(), Selection::GetVertexPosition(), AITargetCallbacks::GetVisionPointPositionWS(), UIScriptedMenu::HandleLights(), UIScriptedMenu::HandleNVG(), HandleReciveData(), ActionWorldCraft::HandleReciveData(), FirearmActionAttachMagazine::HandleReciveData(), FirearmActionAttachMagazineQuick::HandleReciveData(), HitZoneSelectionRaycast(), Init(), InternalResetTarget(), ATCCachedObject::Invalidate(), Weapon::LiftWeaponCheck(), PluginConfigHandler::LoadScenePlayer(), Math3D::MatrixIdentity4(), OnActivate(), OnCenterPanelDropReceived(), BotWaitForChangeInHands::OnEntry(), OnEvent(), ActionCreateIndoorFireplace::OnExecuteServer(), ActionCreateIndoorOven::OnExecuteServer(), OnInputUserDataProcess(), ManBase::OnParticleEvent(), Trigger::OnRPC(), OnRPC(), DayZPlayerCameraBase::OnUpdate(), OnUpdate(), ActionManagerClient::PerformActionFromInventory(), ActionManagerClient::PerformActionFromQuickbar(), ManBase::PhysicalPredictiveDropItem(), EffectArea::PlaceParticles(), ContaminatedArea_Dynamic::PlayFX(), PlaySmokeParticle(), SEffectManager::PlaySoundOnObject(), FirearmActionAttachMagazineQuick::Post_SetupAction(), ManBase::PredictiveForceSwapEntities(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToHands(), ReadFromContext(), ManBase::ReloadWeapon(), RemoveLightSource(), InventoryActionHandler::SetAction(), ActionManagerClient::SetActionFromInventory(), FirearmActionLoadBulletQuick::SetupAction(), UndergroundTriggerCarrierBase::SpawnTrigger(), StandUp(), ItemBase::TentBase(), TestOwnership(), PMTPlayback::TestStopping(), ScriptedWidgetEventHandler::Update(), ActionManagerServer::Update(), CarHornShortActionInput::UpdatePossibleActions(), ToggleLightsActionInput::UpdatePossibleActions(), ToggleNVGActionInput::UpdatePossibleActions(), WeaponParticlesBase::WeaponParticlesBase(), and WriteToContext().