DayzKode: HungerMdfr Class Reference
HungerMdfr Class Reference
Private Member Functions
override bool ActivateCondition (PlayerBase player)
override bool DeactivateCondition (PlayerBase player)
override void Init ()
override void OnReconnect (PlayerBase player)
override void OnTick (PlayerBase player, float deltaT)
Private Attributes
protected float m_EnergyDelta
protected float m_LastEnergyLevel
ref HumanMovementState m_MovementState = new HumanMovementState()
Detailed Description
Definition at line 1 of file hunger.c.
Member Function Documentation
ActivateCondition()
override bool HungerMdfr::ActivateCondition (PlayerBase player) inline private
Definition at line 16 of file hunger.c.
    {
        return true;
    }
DeactivateCondition()
override bool HungerMdfr::DeactivateCondition (PlayerBase player) inline private
Definition at line 21 of file hunger.c.
    {
        return false;
    }
Init()
override void HungerMdfr::Init () inline private
Definition at line 7 of file hunger.c.
    {
        m_TrackActivatedTime = false;
        m_ID                    = eModifiers.MDF_HUNGER;
        m_TickIntervalInactive  = DEFAULT_TICK_TIME_INACTIVE;
        m_TickIntervalActive    = 1;
        DisableDeactivateCheck();
    }
References DEFAULT_TICK_TIME_INACTIVE, DisableDeactivateCheck(), m_ID, m_TickIntervalActive, m_TickIntervalInactive, and m_TrackActivatedTime.
OnReconnect()
override void HungerMdfr::OnReconnect (PlayerBase player) inline private
Definition at line 26 of file hunger.c.
    {
    }
OnTick()
override void HungerMdfr::OnTick (PlayerBase player, float deltaT) inline private
Definition at line 31 of file hunger.c.
    {
        player.GetMovementState(m_MovementState);
        float energy = player.GetStatEnergy().Get();
        float metabolic_speed = MiscGameplayFunctions.GetEnergyMetabolicSpeed(m_MovementState.m_iMovement);
        float modifier = energy/PlayerConstants.SL_ENERGY_MAX + PlayerConstants.CONSUMPTION_MULTIPLIER_BASE;
        metabolic_speed *= modifier; //non linear shaping for consumption curve (comment out to have it linear)
        player.GetStatEnergy().Add( -metabolic_speed * deltaT );
        if ( energy <= PlayerConstants.LOW_ENERGY_THRESHOLD )
        {
            player.SetMixedSoundState( eMixedSoundStates.HUNGRY );
            if( (player.GetStomach().GetDigestingType() & PlayerStomach.DIGESTING_ENERGY) == 0)
                player.AddHealth("GlobalHealth", "Health", -PlayerConstants.LOW_ENERGY_DAMAGE_PER_SEC * deltaT );
        }
        else
        {
            player.UnsetMixedSoundState( eMixedSoundStates.HUNGRY );
        }
    }
References PlayerConstants::CONSUMPTION_MULTIPLIER_BASE, PlayerConstants::LOW_ENERGY_DAMAGE_PER_SEC, PlayerConstants::LOW_ENERGY_THRESHOLD, HumanMovementState::m_iMovement, m_MovementState, PlayerStomach(), and PlayerConstants::SL_ENERGY_MAX.
Member Data Documentation
m_EnergyDelta
protected float HungerMdfr::m_EnergyDelta private
Definition at line 3 of file hunger.c.
m_LastEnergyLevel
protected float HungerMdfr::m_LastEnergyLevel private
Definition at line 4 of file hunger.c.
m_MovementState
ref HumanMovementState HungerMdfr::m_MovementState = new HumanMovementState() private
Definition at line 5 of file hunger.c.
Referenced by OnTick().