DayzKode: InventoryGridController Class Reference
InventoryGridController Class Reference
Private Member Functions
override bool CanAddItemInHandToInventory ()
override int GetItemCount (InventoryItem item)
override float GetItemQuantity (InventoryItem item)
override int GetItemQuantityMax (InventoryItem item)
override string GetItemQuantityText (InventoryItem item)
override int GetQuickbarItemColor (InventoryGrid grid, InventoryItem item)
override int HasItemQuantity (InventoryItem item)
void InventoryQuickbar (Widget quickbarGridWidget)
override void OnItemDrag (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDrop (InventoryGrid grid, Widget w, int row, int col)
override void OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col)
override void OnItemEnter (InventoryGrid grid, Widget w, int row, int col)
override void OnItemLeave (InventoryGrid grid, Widget w)
void Remove (InventoryItem itemToRemove)
void UpdateItems (Widget quickbarGridWidget)
void ~InventoryQuickbar ()
Private Attributes
protected int m_DraggingIndex
protected InventoryGrid m_Grid
protected ref TItemsMap m_Items
Detailed Description
Definition at line 1 of file inventoryquickbar.c.
Constructor & Destructor Documentation
~InventoryQuickbar()
void InventoryGridController::~InventoryQuickbar () inline private
Definition at line 15 of file inventoryquickbar.c.
    {
    }
Member Function Documentation
CanAddItemInHandToInventory()
override bool InventoryGridController::CanAddItemInHandToInventory () inline private
Definition at line 283 of file inventoryquickbar.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI itemInHand = player.GetHumanInventory().GetEntityInHands();
        return itemInHand && player.GetInventory().CanAddEntityToInventory(itemInHand);
    }
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::UpdateQuickbarItems().
GetItemCount()
override int InventoryGridController::GetItemCount (InventoryItem item) inline private
Definition at line 277 of file inventoryquickbar.c.
    {
        ItemBase ib = ItemBase.Cast(item);
        return ib.m_Count;
    }
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantity()
override float InventoryGridController::GetItemQuantity (InventoryItem item) inline private
Definition at line 266 of file inventoryquickbar.c.
    {
        return QuantityConversions.GetItemQuantity( item );
    }
References QuantityConversions::GetItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityMax()
override int InventoryGridController::GetItemQuantityMax (InventoryItem item) inline private
Definition at line 271 of file inventoryquickbar.c.
    {
        ItemBase ib = ItemBase.Cast(item);
        return ib.m_VarQuantityMax;
    }
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetItemQuantityText()
override string InventoryGridController::GetItemQuantityText (InventoryItem item) inline private
Definition at line 261 of file inventoryquickbar.c.
    {
        return QuantityConversions.GetItemQuantityText( item );
    }
References QuantityConversions::GetItemQuantityText().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
GetQuickbarItemColor()
override int InventoryGridController::GetQuickbarItemColor (InventoryGrid grid, InventoryItem item) inline private
Definition at line 235 of file inventoryquickbar.c.
    {
        int color = 0x0AFFFFFF;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        EntityAI itemInHand = player.GetHumanInventory().GetEntityInHands();
        if ( player && itemInHand == item )
        {
            if ( player.GetHumanInventory().FindUserReservedLocationIndex(item) != -1 || grid.CanAddItemInHandToInventory() )
                color = InventoryGrid.ITEM_COLOR_QUICKBAR_H_GOOD;
            else
                color = InventoryGrid.ITEM_COLOR_QUICKBAR_H_BAD;
        }
        else if ( itemInHand )
        {
            if ( !grid.CanAddItemInHandToInventory() && !GameInventory.CanSwapEntitiesEx(item, itemInHand) )
                color = InventoryGrid.ITEM_COLOR_QUICKBAR_I_BAD;
        }
        return color;
    }
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::RefreshQuickbarItemVariables().
HasItemQuantity()
override int InventoryGridController::HasItemQuantity (InventoryItem item) inline private
Definition at line 256 of file inventoryquickbar.c.
    {
        return QuantityConversions.HasItemQuantity( item );
    }
References QuantityConversions::HasItemQuantity().
Referenced by ScriptedWidgetEventHandler::RefreshItemVariables().
InventoryQuickbar()
void InventoryGridController::InventoryQuickbar (Widget quickbarGridWidget) inline private
Definition at line 8 of file inventoryquickbar.c.
    {
        m_DraggingIndex = INDEX_NOT_FOUND;
        m_Items = new TItemsMap;
        UpdateItems( quickbarGridWidget );
    }
References INDEX_NOT_FOUND, and UpdateItems().
OnItemDrag()
override void InventoryGridController::OnItemDrag (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 224 of file inventoryquickbar.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        InventoryItem item = InventoryItem.Cast( player.GetQuickBarEntity(col) );
        if (item)
        {
            m_DraggingIndex = col;
            m_Grid.SetItemColor(item, InventoryGrid.ITEM_COLOR_DRAG);
        }
    }
References GetGame(), and GetPlayer().
Referenced by ScriptedWidgetEventHandler::OnDrag().
OnItemDraggingOver()
override void InventoryGridController::OnItemDraggingOver (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 99 of file inventoryquickbar.c.
    {
        ItemPreviewWidget iw;
        InventoryItem dragged_item;
        iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !iw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if( !iw || !iw.GetItem() )
        {
            return;
        }
        if(!dragged_item && iw)
            dragged_item = InventoryItem.Cast( iw.GetItem() );
        if ( dragged_item == NULL)
            return;
        if (dragged_item && dragged_item.GetInventory().CanRemoveEntity() == false)
        {
            int color;
            color = ARGB( 150, 255, 1, 1 );
            if( w.FindAnyWidget("Selected") )
            {
                w.FindAnyWidget("Selected").SetColor( color );
            }
            else
            {
                name = w.GetName();
                name.Replace( "PanelWidget", "Cursor" );
                if( w.FindAnyWidget( name ) )
                {
                    w.FindAnyWidget( name ).SetColor( color );
                }
            }
        }
        else
        {
            color = ARGB( 150, 1, 255, 1 );
            if( w.FindAnyWidget("Selected") )
            {
                w.FindAnyWidget("Selected").SetColor( color );
            }
            else
            {
                name = w.GetName();
                name.Replace( "PanelWidget", "Cursor" );
                if( w.FindAnyWidget( name ) )
                {
                    w.FindAnyWidget( name ).SetColor( color );
                }
            }
        }
    }
References ARGB(), ItemPreviewWidget::GetItem(), name, and string::Replace().
Referenced by ScriptedWidgetEventHandler::OnDraggingOver().
OnItemDrop()
override void InventoryGridController::OnItemDrop (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 206 of file inventoryquickbar.c.
    {
        if (m_DraggingIndex != INDEX_NOT_FOUND)
        {
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            InventoryItem dragged_item = InventoryItem.Cast( player.GetQuickBarEntity(m_DraggingIndex) );
            Remove(dragged_item);
            m_DraggingIndex = INDEX_NOT_FOUND;
        }
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu(MENU_INVENTORY) );
        if ( menu )
        {
            menu.RefreshQuickbar();
        }
        ItemManager.GetInstance().HideDropzones();
    }
References GetGame(), ItemManager::GetInstance(), GetPlayer(), ItemManager::HideDropzones(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, and Remove().
Referenced by ScriptedWidgetEventHandler::OnDrop().
OnItemDropReceived()
override void InventoryGridController::OnItemDropReceived (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 162 of file inventoryquickbar.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        ItemBase dragged_item = ItemBase.Cast( ItemManager.GetInstance().GetDraggedItem() );
        ItemPreviewWidget iw = ItemPreviewWidget.Cast( w.FindAnyWidget( "Render" ) );
        if( !iw )
        {
            string name = w.GetName();
            name.Replace( "PanelWidget", "Render" );
            iw = ItemPreviewWidget.Cast( w.FindAnyWidget( name ) );
        }
        if(!dragged_item && iw)
            dragged_item = ItemBase.Cast( iw.GetItem() );
        if(dragged_item && dragged_item.GetHierarchyRootPlayer()!= GetGame().GetPlayer())
            return;
        ItemBase quickbar_item = ItemBase.Cast( player.GetQuickBarEntity(col) );
        if (m_DraggingIndex != INDEX_NOT_FOUND)
        {
            dragged_item = ItemBase.Cast( player.GetQuickBarEntity(m_DraggingIndex) );
        }
        if (dragged_item && dragged_item.GetInventory().CanRemoveEntity())
        {
            player.SetQuickBarEntityShortcut(dragged_item, col);
            if (quickbar_item && quickbar_item != dragged_item && m_DraggingIndex != INDEX_NOT_FOUND)
            {
                player.SetQuickBarEntityShortcut(quickbar_item, m_DraggingIndex);
            }
        }
        m_DraggingIndex = INDEX_NOT_FOUND;
        InventoryMenu menu = InventoryMenu.Cast( GetGame().GetUIManager().FindMenu(MENU_INVENTORY) );
        if ( menu )
        {
            menu.RefreshQuickbar();
        }
    }
References ItemManager::GetDraggedItem(), GetGame(), ItemManager::GetInstance(), ItemPreviewWidget::GetItem(), GetPlayer(), INDEX_NOT_FOUND, InventoryMenu(), MENU_INVENTORY, name, and string::Replace().
Referenced by ScriptedWidgetEventHandler::OnDropReceived().
OnItemEnter()
override void InventoryGridController::OnItemEnter (InventoryGrid grid, Widget w, int row, int col) inline private
Definition at line 81 of file inventoryquickbar.c.
    {
        Widget quickbar = grid.GetRoot();
        if( quickbar )
        {
            // quickbar.SetColor( 0xFFFFFFFF );
        }
    }
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnItemLeave()
override void InventoryGridController::OnItemLeave (InventoryGrid grid, Widget w) inline private
Definition at line 90 of file inventoryquickbar.c.
    {
        Widget quickbar = grid.GetRoot();
        if( quickbar )
        {
            // quickbar.SetColor( 0x7FFFFFFF );
        }
    }
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
Remove()
void InventoryGridController::Remove (InventoryItem itemToRemove) inline private
Definition at line 66 of file inventoryquickbar.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        for ( int i = 0; i < m_Grid.GetGridSize(); i++ )
        {
            InventoryItem item = InventoryItem.Cast( player.GetQuickBarEntity(i) );
            if(item == itemToRemove)
            {
                player.RemoveQuickBarEntityShortcut( item );
            }
        }
    }
References GetGame(), and GetPlayer().
Referenced by OnItemDrop().
UpdateItems()
void InventoryGridController::UpdateItems (Widget quickbarGridWidget) inline private
Definition at line 19 of file inventoryquickbar.c.
    {
        if( !quickbarGridWidget )
        {
            return;
        }
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        if ( !player )
            return;
        int i;
        // create grid and align it to center
        if( !m_Grid )
        {
            quickbarGridWidget.GetScript( m_Grid );
            m_Grid.SetController( this );
            m_Grid.GenerateQuickBarBackgroundTiles( 10 );
        }
        m_Items.Clear();
        InventoryItem item;
        if( m_Grid )
        {
            if( m_Grid.GetGridSize() != player.GetQuickBarSize() )
            {
                m_Grid.SetGridSize( player.GetQuickBarSize() );
            }
        }
        for( i = 0; i < m_Grid.GetGridSize(); i++)
        {
            item = InventoryItem.Cast( player.GetQuickBarEntity(i) );
            if( item )
            {
                m_Items.Set( item, Vector(i, 1, 1) );
            }
        }
        if( m_Grid )
        {
            m_Grid.UpdateQuickbarItems( m_Items );
        }
    }
References Widget::Clear(), GetGame(), GetPlayer(), and Vector().
Referenced by InventoryQuickbar().
Member Data Documentation
m_DraggingIndex
protected int InventoryGridController::m_DraggingIndex private
Definition at line 6 of file inventoryquickbar.c.
m_Grid
protected InventoryGrid InventoryGridController::m_Grid private
Definition at line 5 of file inventoryquickbar.c.
m_Items
protected ref TItemsMap InventoryGridController::m_Items private
Definition at line 4 of file inventoryquickbar.c.