DayzKode: SVNBlamePlugin Class Reference
SVNBlamePlugin Class Reference
Private Member Functions
override void Configure ()
void OkButton ()
override void Run ()
Private Attributes
string CommandLine
Detailed Description
Definition at line 2 of file blametool.c.
Member Function Documentation
Configure()
override void SVNBlamePlugin::Configure () inline private
Definition at line 25 of file blametool.c.
    {
        Workbench.ScriptDialog("Configure SVN Blame", "Usage: \n$path - will be replaced with file name\n$line - will be replaced with current line number", this);
    }
References Workbench::ScriptDialog().
OkButton()
void SVNBlamePlugin::OkButton () inline private
Definition at line 31 of file blametool.c.
{}
Run()
override void SVNBlamePlugin::Run () inline private
Definition at line 7 of file blametool.c.
    {
        ScriptEditor mod = Workbench.GetModule("ScriptEditor");
        if (mod)
        {
            string file;
            string absPath;
            if (mod.GetCurrentFile(file) && Workbench.GetAbsolutePath(file, absPath))
            {
                int line = mod.GetCurrentLine();
                string command = CommandLine;
                command.Replace("$path", absPath);
                command.Replace("$line", (line + 1).ToString());
                Workbench.RunCmd(command);
            }
        }
    }
References Workbench::GetAbsolutePath(), ScriptEditor::GetCurrentFile(), ScriptEditor::GetCurrentLine(), Workbench::GetModule(), string::Replace(), Workbench::RunCmd(), and ToString().
Member Data Documentation
CommandLine
string SVNBlamePlugin::CommandLine private
Definition at line 5 of file blametool.c.