DayzKode: DayZIntroSceneXbox Class Reference
DayZIntroSceneXbox Class Reference
Private Member Functions
protected Camera CameraCreate (vector cam_pos, float cam_rot_h, float cam_rot_v, float cam_fov, float cam_focus_dist, float cam_focus_strg)
bool CheckXboxClientUpdate ()
void CheckXboxClientUpdateLoopStart ()
void CheckXboxClientUpdateLoopStop ()
void CreateRandomCharacter ()
void DayZIntroSceneXbox ()
Camera GetCamera ()
IntroSceneCharacter GetIntroCharacter ()
bool IsCharacterFemale ()
void ResetIntroCamera ()
void SaveCharName (string name)
void SetCharacterFemale (bool fem)
protected void SetInitPostprocesses ()
void SetupCharacter ()
void SetupDate ()
void SetupParticles ()
vector SnapToGround (vector pos)
void UpdateCharacterPos ()
void UpdateSelectedUserName ()
void ~DayZIntroSceneXbox ()
Private Attributes
protected ref TStringArray m_AllCharacters
protected ref IntroSceneCharacter m_Character
protected vector m_CharacterDir
protected vector m_CharacterPos
protected ref TStringArray m_CharPantsList
protected ref TStringArray m_CharPersonalityFemaleList
protected ref TStringArray m_CharPersonalityMaleList
protected ref TStringArray m_CharShirtList
protected ref TStringArray m_CharShoesList
protected Object m_Clutter
protected ref TIntArray m_Date = new TIntArray
protected ref MenuCarEngineSmoke m_FXParticleCarSmoke
protected ref MenuEvaporation m_FXParticleStreamLeft
protected ref MenuEvaporation m_FXParticleStreamRight
protected ref TStringArray m_genderList
protected bool m_IsCharFemale
protected int m_LastPlayedCharacterID
protected MenuData m_MenuData
protected Camera m_SceneCamera
ref Timer m_TimerClientUpdate = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerDate = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerParticle = new Timer(CALL_CATEGORY_GAMEPLAY)
ref Timer m_TimerUpdate = new Timer(CALL_CATEGORY_GAMEPLAY)
protected Weather m_Weather
Detailed Description
Definition at line 1 of file dayzintroscenexbox.c.
Constructor & Destructor Documentation
DayZIntroSceneXbox()
void DayZIntroSceneXbox::DayZIntroSceneXbox () inline private
Definition at line 36 of file dayzintroscenexbox.c.
    {
        Print("DayZIntroSceneXbox Start");
        m_MenuData = g_Game.GetMenuData();
        m_LastPlayedCharacterID = m_MenuData.GetLastPlayedCharacter();
        m_CharacterPos = "0 0 0";
        m_CharacterDir = "0 0 0";
        //g_Game.m_PlayerName = "Survivor"; //default
        if ( m_MenuData.GetCharactersCount() == 0 )
        {
            m_LastPlayedCharacterID = -1;
        }
        if ( m_LastPlayedCharacterID > -1 )
        {
            m_MenuData.GetCharacterName(m_LastPlayedCharacterID, g_Game.GetPlayerGameName());
        }
        // Camera Setup
        vector camera_position;
        camera_position[0]          = 1323.0;   // X
        camera_position[1]          = 1.0;      // Y
        camera_position[2]          = 1590.37;  // Z
        float camera_rotation_h     = 100;
        float camera_rotation_v     = -3;
        float camera_fov            = 0.85;
        float camera_focus_distance = 0.0;
        float camera_focus_streght  = 0.0;
        // Character
        float character_distance = 2.25;
        // Camera Setup
        m_SceneCamera = CameraCreate(camera_position, camera_rotation_h, camera_rotation_v, camera_fov, camera_focus_distance, camera_focus_streght);
        m_SceneCamera.SetActive(true);
        PPEffects.Init(); //Deprecated, left in for legacy purposes only
        // Character Setup
        vector cam_dir = m_SceneCamera.GetDirection();
        m_CharacterPos = camera_position + ( cam_dir * character_distance );
        m_CharacterPos[1] = GetGame().SurfaceY(m_CharacterPos[0], m_CharacterPos[2]);
        m_CharacterDir = (camera_position - m_CharacterPos);
        m_Character = new IntroSceneCharacter();
        m_Character.LoadCharacterData(m_CharacterPos, m_CharacterDir);
        m_TimerParticle.Run(0.1, this, "SetupParticles", null, false);
        //m_TimerDate.Run(2.0, this, "SetupDate", null, false);
        m_TimerUpdate.Run(0.5, this, "SetupCharacter", null, true);
        vector clut_pos = SnapToGround( m_CharacterPos + "-1 0 0" );
        m_Clutter = GetGame().CreateObject( "ClutterCutter2x2", clut_pos, true );
        // Xbox check update
        CheckXboxClientUpdateLoopStart();
        GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(SetInitPostprocesses);
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CameraCreate(), CheckXboxClientUpdateLoopStart(), CGame::CreateObject(), g_Game, CGame::GetCallQueue(), MenuData::GetCharacterName(), MenuData::GetCharactersCount(), GetGame(), MenuData::GetLastPlayedCharacter(), PPEffects::Init(), Managed::IntroSceneCharacter(), m_Character, m_CharacterDir, m_CharacterPos, m_Clutter, m_LastPlayedCharacterID, m_MenuData, m_SceneCamera, m_TimerParticle, m_TimerUpdate, Print(), SetInitPostprocesses(), SnapToGround(), and CGame::SurfaceY().
~DayZIntroSceneXbox()
void DayZIntroSceneXbox::~DayZIntroSceneXbox () inline private
Definition at line 99 of file dayzintroscenexbox.c.
    {
        if ( m_TimerUpdate )
        {
            m_TimerUpdate.Stop();
            delete m_TimerUpdate;
            m_TimerUpdate = null;
        }
        if ( m_TimerParticle )
        {
            m_TimerParticle.Stop();
            delete m_TimerParticle;
            m_TimerParticle = null;
        }
        if ( m_TimerDate )
        {
            m_TimerDate.Stop();
            delete m_TimerDate;
            m_TimerDate = null;
        }
        CheckXboxClientUpdateLoopStop();
        GetGame().ObjectDelete( m_SceneCamera );
        if ( m_MenuData )
        {
            m_MenuData.ClearCharacters();
        }
        SEffectManager.DestroyEffect(m_FXParticleCarSmoke);
        SEffectManager.DestroyEffect(m_FXParticleStreamLeft);
        SEffectManager.DestroyEffect(m_FXParticleStreamRight);
        PPEManagerStatic.GetPPEManager().StopAllEffects(PPERequesterCategory.ALL);
    }
References CheckXboxClientUpdateLoopStop(), MenuData::ClearCharacters(), SEffectManager::DestroyEffect(), GetGame(), PPEManagerStatic::GetPPEManager(), m_FXParticleCarSmoke, m_FXParticleStreamLeft, m_FXParticleStreamRight, m_MenuData, m_SceneCamera, m_TimerDate, m_TimerParticle, m_TimerUpdate, and CGame::ObjectDelete().
Member Function Documentation
CameraCreate()
protected Camera DayZIntroSceneXbox::CameraCreate (vector cam_pos, float cam_rot_h, float cam_rot_v, float cam_fov, float cam_focus_dist, float cam_focus_strg) inline private
Definition at line 239 of file dayzintroscenexbox.c.
    {
        Camera cam = Camera.Cast( g_Game.CreateObject("staticcamera", SnapToGround(cam_pos), true));
        cam.SetOrientation( Vector( cam_rot_h, cam_rot_v, 0) );
        cam.SetFOV( cam_fov );
        cam.SetFocus(cam_focus_dist, cam_focus_strg);
        return cam;
    }
References g_Game, SnapToGround(), and Vector().
Referenced by DayZIntroSceneXbox().
CheckXboxClientUpdate()
bool DayZIntroSceneXbox::CheckXboxClientUpdate () inline private
Definition at line 231 of file dayzintroscenexbox.c.
    {
        return OnlineServices.CheckUpdate();
    }
References OnlineServices::CheckUpdate().
Referenced by CheckXboxClientUpdateLoopStart().
CheckXboxClientUpdateLoopStart()
void DayZIntroSceneXbox::CheckXboxClientUpdateLoopStart () inline private
Definition at line 207 of file dayzintroscenexbox.c.
    {
        if ( CheckXboxClientUpdate() )
        {
            m_TimerClientUpdate.Run(30, this, "CheckXboxClientUpdate", null, true);
        }
    }
References CheckXboxClientUpdate(), and m_TimerClientUpdate.
Referenced by DayZIntroSceneXbox().
CheckXboxClientUpdateLoopStop()
void DayZIntroSceneXbox::CheckXboxClientUpdateLoopStop () inline private
Definition at line 218 of file dayzintroscenexbox.c.
    {
        if ( m_TimerClientUpdate )
        {
            m_TimerClientUpdate.Stop();
            delete m_TimerClientUpdate;
            m_TimerClientUpdate = null;
        }
    }
References m_TimerClientUpdate.
Referenced by ~DayZIntroSceneXbox().
CreateRandomCharacter()
void DayZIntroSceneXbox::CreateRandomCharacter () inline private
Definition at line 284 of file dayzintroscenexbox.c.
    {
        string character_name;
        string params[2];
        m_IsCharFemale = Math.RandomInt(0, 2);
        if (m_IsCharFemale)
        {
            character_name = m_CharPersonalityFemaleList.GetRandomElement();
        }
        else
        {
            character_name = m_CharPersonalityMaleList.GetRandomElement();
        }
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLater(UpdateCharacterPos, 250);
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_CharPersonalityFemaleList, m_CharPersonalityMaleList, m_IsCharFemale, Math::RandomInt(), and UpdateCharacterPos().
GetCamera()
Camera DayZIntroSceneXbox::GetCamera () inline private
Definition at line 252 of file dayzintroscenexbox.c.
    {
        return m_SceneCamera;
    }
References m_SceneCamera.
GetIntroCharacter()
IntroSceneCharacter DayZIntroSceneXbox::GetIntroCharacter () inline private
Definition at line 151 of file dayzintroscenexbox.c.
    {
        return m_Character;
    }
References m_Character.
Referenced by UIScriptedMenu::Apply(), UIScriptedMenu::Back(), UIScriptedMenu::BottomChanged(), UIScriptedMenu::CheckNewOptions(), UIScriptedMenu::GenderChanged(), UIScriptedMenu::GetPlayerObj(), UIScriptedMenu::Init(), UIScriptedMenu::RandomizeCharacter(), UIScriptedMenu::Refresh(), UIScriptedMenu::Save(), UIScriptedMenu::SetCharacter(), UIScriptedMenu::ShoesChanged(), UIScriptedMenu::SkinChanged(), UIScriptedMenu::TopChanged(), and UIScriptedMenu::Update().
IsCharacterFemale()
bool DayZIntroSceneXbox::IsCharacterFemale () inline private
Definition at line 276 of file dayzintroscenexbox.c.
    {
        return m_IsCharFemale;
    }
References m_IsCharFemale.
ResetIntroCamera()
void DayZIntroSceneXbox::ResetIntroCamera () inline private
Definition at line 260 of file dayzintroscenexbox.c.
    {
    }
Referenced by UIScriptedMenu::CharacterCreationMenu().
SaveCharName()
void DayZIntroSceneXbox::SaveCharName (string name) inline private
Definition at line 328 of file dayzintroscenexbox.c.
    {
        GetDayZGame().InitCharacterMenuDataInfo(m_MenuData.GetCharactersCount());
        //if (!GetDayZGame().IsNewCharacter() && m_LastPlayedCharacterID > -1)
        //{
            m_MenuData.SetCharacterName(m_LastPlayedCharacterID, name);
        //}
        if (m_Character.IsDefaultCharacter())
        {
            GetGame().GetMenuDefaultCharacterData().SetCharacterName(name);
        }
        m_MenuData.SaveCharactersLocal();
    }
References MenuData::GetCharactersCount(), GetDayZGame(), GetGame(), CGame::GetMenuDefaultCharacterData(), m_Character, m_LastPlayedCharacterID, m_MenuData, name, MenuData::SaveCharactersLocal(), MenuData::SetCharacterName(), and MenuDefaultCharacterData::SetCharacterName().
SetCharacterFemale()
void DayZIntroSceneXbox::SetCharacterFemale (bool fem) inline private
Definition at line 268 of file dayzintroscenexbox.c.
    {
        m_IsCharFemale = fem;
    }
References m_IsCharFemale.
SetInitPostprocesses()
protected void DayZIntroSceneXbox::SetInitPostprocesses () inline private
Definition at line 139 of file dayzintroscenexbox.c.
    {
        PPERequester_MenuEffects requester;
        Class.CastTo(requester,PPERequesterBank.GetRequester(PPERequester_MenuEffects));
        requester.SetVignetteIntensity(0.3);
        PPERequesterBank.GetRequester(PPERequester_IntroChromAbb).Start();
    }
References Class::CastTo().
Referenced by DayZIntroSceneXbox().
SetupCharacter()
void DayZIntroSceneXbox::SetupCharacter () inline private
Definition at line 159 of file dayzintroscenexbox.c.
    {
        if ( m_Character.GetCharacterObj() )
        {
            vector v = m_Character.GetCharacterObj().GetOrientation();
            v[0] = -75;
            m_Character.GetCharacterObj().SetOrientation(v);
        }
    }
References m_Character.
SetupDate()
void DayZIntroSceneXbox::SetupDate () inline private
Definition at line 198 of file dayzintroscenexbox.c.
    {
        //g_Game.GetWorld().SetDate(m_Date.Get(0), m_Date.Get(1), m_Date.Get(2), m_Date.Get(3), m_Date.Get(4));
        //g_Game.GetWorld().SetDate(2020, 10, 15, 18, 20);
    }
SetupParticles()
void DayZIntroSceneXbox::SetupParticles () inline private
Definition at line 172 of file dayzintroscenexbox.c.
    {
        m_FXParticleCarSmoke = new MenuCarEngineSmoke();
        //SEffectManager.PlayInWorld(m_FXParticleCarSmoke, "1330.36 2.11628 1594.31");
        //SEffectManager.PlayInWorld(m_FXParticleCarSmoke, "1333.88 1.51392 1594.88");
        SEffectManager.PlayInWorld(m_FXParticleCarSmoke, "1331.52 2.34052 1593.55");
        vector pos = m_SceneCamera.GetPosition() + m_SceneCamera.GetDirection() * 1.5;
        vector dir = m_SceneCamera.GetDirection();
        float temp = dir[0];
        dir[0] = dir[2];
        dir[2] = -temp;
        vector pos_right = pos + (dir * 1.5);
        vector pos_left = pos + (-dir * 1.5);
        m_FXParticleStreamLeft = new MenuEvaporation();
        SEffectManager.PlayInWorld(m_FXParticleStreamLeft, pos_right);
        m_FXParticleStreamRight = new MenuEvaporation();
        SEffectManager.PlayInWorld(m_FXParticleStreamRight, pos_left);
    }
References m_FXParticleCarSmoke, m_FXParticleStreamLeft, m_FXParticleStreamRight, m_SceneCamera, and SEffectManager::PlayInWorld().
SnapToGround()
vector DayZIntroSceneXbox::SnapToGround (vector pos) inline private
Definition at line 344 of file dayzintroscenexbox.c.
    {
        float pos_x = pos[0];
        float pos_z = pos[2];
        float pos_y = GetGame().SurfaceY(pos_x, pos_z);
        vector tmp_pos = Vector(pos_x, pos_y, pos_z);
        tmp_pos[1] = tmp_pos[1] + pos[1];
        return tmp_pos;
    }
References GetGame(), CGame::SurfaceY(), and Vector().
Referenced by CameraCreate(), and DayZIntroSceneXbox().
UpdateCharacterPos()
void DayZIntroSceneXbox::UpdateCharacterPos () inline private
Definition at line 319 of file dayzintroscenexbox.c.
    {
        if (m_Character.GetCharacterObj())
        {
            m_Character.GetCharacterObj().SetPosition(m_CharacterPos);
            m_Character.GetCharacterObj().SetDirection(m_CharacterDir.Normalized() );
        }
    }
References m_Character, m_CharacterDir, m_CharacterPos, and vector::Normalized().
Referenced by CreateRandomCharacter().
UpdateSelectedUserName()
void DayZIntroSceneXbox::UpdateSelectedUserName () inline private
Definition at line 303 of file dayzintroscenexbox.c.
    {
        string name;
        BiosUserManager user_manager = GetGame().GetUserManager();
        if( user_manager )
        {
            BiosUser user = user_manager.GetSelectedUser();
            if( user )
            {
                g_Game.SetPlayerGameName( user.GetName() );
                return;
            }
        }
        g_Game.SetPlayerGameName(GameConstants.DEFAULT_CHARACTER_NAME);
    }
References GameConstants::DEFAULT_CHARACTER_NAME, g_Game, GetGame(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), and name.
Member Data Documentation
m_AllCharacters
protected ref TStringArray DayZIntroSceneXbox::m_AllCharacters private
Definition at line 12 of file dayzintroscenexbox.c.
m_Character
protected ref IntroSceneCharacter DayZIntroSceneXbox::m_Character private
Definition at line 14 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), GetIntroCharacter(), SaveCharName(), SetupCharacter(), and UpdateCharacterPos().
m_CharacterDir
protected vector DayZIntroSceneXbox::m_CharacterDir private
Definition at line 19 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), and UpdateCharacterPos().
m_CharacterPos
protected vector DayZIntroSceneXbox::m_CharacterPos private
Definition at line 18 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), and UpdateCharacterPos().
m_CharPantsList
protected ref TStringArray DayZIntroSceneXbox::m_CharPantsList private
Definition at line 10 of file dayzintroscenexbox.c.
m_CharPersonalityFemaleList
protected ref TStringArray DayZIntroSceneXbox::m_CharPersonalityFemaleList private
Definition at line 8 of file dayzintroscenexbox.c.
Referenced by CreateRandomCharacter().
m_CharPersonalityMaleList
protected ref TStringArray DayZIntroSceneXbox::m_CharPersonalityMaleList private
Definition at line 7 of file dayzintroscenexbox.c.
Referenced by CreateRandomCharacter().
m_CharShirtList
protected ref TStringArray DayZIntroSceneXbox::m_CharShirtList private
Definition at line 9 of file dayzintroscenexbox.c.
m_CharShoesList
protected ref TStringArray DayZIntroSceneXbox::m_CharShoesList private
Definition at line 11 of file dayzintroscenexbox.c.
m_Clutter
protected Object DayZIntroSceneXbox::m_Clutter private
Definition at line 17 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox().
m_Date
protected ref TIntArray DayZIntroSceneXbox::m_Date = new TIntArray private
Definition at line 20 of file dayzintroscenexbox.c.
m_FXParticleCarSmoke
protected ref MenuCarEngineSmoke DayZIntroSceneXbox::m_FXParticleCarSmoke private
Definition at line 24 of file dayzintroscenexbox.c.
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_FXParticleStreamLeft
protected ref MenuEvaporation DayZIntroSceneXbox::m_FXParticleStreamLeft private
Definition at line 25 of file dayzintroscenexbox.c.
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_FXParticleStreamRight
protected ref MenuEvaporation DayZIntroSceneXbox::m_FXParticleStreamRight private
Definition at line 26 of file dayzintroscenexbox.c.
Referenced by SetupParticles(), and ~DayZIntroSceneXbox().
m_genderList
protected ref TStringArray DayZIntroSceneXbox::m_genderList private
Definition at line 6 of file dayzintroscenexbox.c.
m_IsCharFemale
protected bool DayZIntroSceneXbox::m_IsCharFemale private
Definition at line 3 of file dayzintroscenexbox.c.
Referenced by CreateRandomCharacter(), IsCharacterFemale(), and SetCharacterFemale().
m_LastPlayedCharacterID
protected int DayZIntroSceneXbox::m_LastPlayedCharacterID private
Definition at line 4 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), and SaveCharName().
m_MenuData
protected MenuData DayZIntroSceneXbox::m_MenuData private
Definition at line 22 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), SaveCharName(), and ~DayZIntroSceneXbox().
m_SceneCamera
protected Camera DayZIntroSceneXbox::m_SceneCamera private
Definition at line 15 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), GetCamera(), SetupParticles(), and ~DayZIntroSceneXbox().
m_TimerClientUpdate
ref Timer DayZIntroSceneXbox::m_TimerClientUpdate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Definition at line 31 of file dayzintroscenexbox.c.
Referenced by CheckXboxClientUpdateLoopStart(), and CheckXboxClientUpdateLoopStop().
m_TimerDate
ref Timer DayZIntroSceneXbox::m_TimerDate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Definition at line 30 of file dayzintroscenexbox.c.
Referenced by ~DayZIntroSceneXbox().
m_TimerParticle
ref Timer DayZIntroSceneXbox::m_TimerParticle = new Timer(CALL_CATEGORY_GAMEPLAY) private
Definition at line 29 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), and ~DayZIntroSceneXbox().
m_TimerUpdate
ref Timer DayZIntroSceneXbox::m_TimerUpdate = new Timer(CALL_CATEGORY_GAMEPLAY) private
Definition at line 28 of file dayzintroscenexbox.c.
Referenced by DayZIntroSceneXbox(), and ~DayZIntroSceneXbox().
m_Weather
protected Weather DayZIntroSceneXbox::m_Weather private
Definition at line 16 of file dayzintroscenexbox.c.