DayzKode: ComponentEnergyManager Class Reference
ComponentEnergyManager Class Reference
Private Member Functions
float AddEnergy (float added_energy)
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
bool CanBePluggedInto (EntityAI potential_energy_provider)
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
bool CanReceivePlugFrom (EntityAI device_to_plug)
Energy manager: Returns true if this device can receive power plug of the other device.
bool CanSwitchOff ()
Energy manager: Checks if the device can be switched OFF.
bool CanSwitchOn ()
Energy manager: Checks if the device can be switched ON.
bool CanWork (float test_energy=-1)
Energy manager: Checks whenever this device can do work or not.
bool CheckWetness ()
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
void ClearLastUpdateTime ()
void ComponentEnergyManager ()
bool ConsumeEnergy (float amount)
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
void DebugUpdate ()
void DeviceUpdate ()
Shape DrawArrow (vector from, vector to, float size=0.5, int color=0xFFFFFFFF, float flags=0)
override void Event_OnAwake ()
override void Event_OnInit ()
protected bool FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state=false)
int GetAttachmentAction ()
void GetCompatiblePlugTypes (out TIntArray IDs)
override int GetCompType ()
float GetCordLength ()
Energy manager: Returns the length of the virtual power cord.
string GetCordTextureFile ()
Energy manager: Returns path to the cord texture file.
float GetCurrentUpdateTime ()
bool GetDebugPlugs ()
EntityAI GetDeviceBySocketID (int id)
Energy manager: Returns the device which is plugged into the given socket ID.
float GetEnergy ()
Energy manager: Returns the amount of stored energy this device has.
float GetEnergy0To1 ()
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
int GetEnergy0To100 ()
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
float GetEnergyMax ()
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
float GetEnergyMaxPristine ()
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
EntityAI GetEnergySource ()
Energy manager: Returns the energy source this device is plugged into.
int GetEnergySourceNetworkIDHigh ()
int GetEnergySourceNetworkIDLow ()
int GetEnergySourceStorageIDb1 ()
int GetEnergySourceStorageIDb2 ()
int GetEnergySourceStorageIDb3 ()
int GetEnergySourceStorageIDb4 ()
float GetEnergyUsage ()
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
protected int GetMySocketID ()
EntityAI GetPluggedDevice ()
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
array< EntityAI > GetPluggedDevices ()
Energy manager: Returns an array of devices which are plugged into this one.
int GetPluggedDevicesCount ()
Energy manager: Returns the number of devices plugged into this one.
EntityAI GetPlugOwner (string plug_selection_name)
Energy manager: Returns the device to which the given plug selection belongs to.
int GetPlugType ()
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
array< EntityAI > GetPoweredDevices ()
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
bool GetPreviousSwitchState ()
bool GetRestorePlugState ()
int GetSocketsCount ()
Energy manager: Returns the count of power sockets (whenever used or not)
EntityAI GetThisEntityAI ()
float GetUpdateInterval ()
Energy manager: Returns the update interval of this device.
float GetWetnessExposure ()
Returns wetness exposure value defined in config.
void HandleMoveInsideCargo (EntityAI container)
bool HasConversionOfEnergyToQuantity ()
Energy manager: Returns true if this item automatically converts its energy to quantity.
bool HasElectricityIcon ()
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
bool HasEnoughStoredEnergy ()
Energy manager: Returns true if this device has enough of stored energy for its own use.
bool HasFreeSocket (int socket_id=-1)
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
bool HasVisibleSocketsInInventory ()
bool IsCordFolded ()
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
bool IsEnergySourceAtReach (vector from_position, float add_tolerance=0, vector override_source_position="-1 -1 -1")
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
bool IsPassive ()
Energy manager: Returns true if this device is set to be passive. False if otherwise.
bool IsPlugCompatible (int plug_ID)
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
bool IsPlugged ()
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
bool IsSelectionAPlug (string selection_to_test)
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
bool IsSwitchedOn ()
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
bool IsWorking ()
Energy manager: Returns true if this device is working right now.
void OnAttachmentAdded (EntityAI elec_device)
void OnAttachmentRemoved (EntityAI elec_device)
void OnDeviceDestroyed ()
void OnEnergyAdded ()
Energy manager: Called when energy was added on this device.
void OnEnergyConsumed ()
Energy manager: Called when energy was consumed on this device.
void OnIsPlugged (EntityAI source_device)
void OnIsUnplugged (EntityAI last_energy_source)
void OnOwnSocketReleased (EntityAI device)
void OnOwnSocketTaken (EntityAI device)
void OnWork (float consumed_energy)
protected void PlugCordIntoSocket (EntityAI device_to_plug, int socket_id=-1)
protected bool PlugInDevice (EntityAI device_to_plug, int socket_id=-1)
bool PlugThisInto (EntityAI energy_source, int socket_id=-1)
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
void RefreshDebug ()
void RememberLastUpdateTime ()
void ResetEnergyUsage ()
Energy manager: Resets energy usage to default (config) value.
void RestorePlugState (bool state)
void SetAttachmentAction (int new_action_type)
void SetCordLength (float new_length)
Energy manager: Changes the length of the virtual power cord.
void SetCordTextureFile (string new_path)
void SetDebugPlugs (bool newVal)
void SetDeviceBySocketID (int id, EntityAI plugged_device)
Energy manager: Stores the device which is plugged into the given socket ID.
void SetElectricityIconVisibility (bool make_visible)
Energy manager: Sets visibility of the electricity icon (bolt).
void SetEnergy (float new_energy)
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
void SetEnergy0To1 (float energy01)
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
void SetEnergyMaxPristine (float new_limit)
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
protected void SetEnergySource (EntityAI source)
void SetEnergySourceClient (EntityAI source)
void SetEnergyUsage (float new_usage)
Energy manager: Changes the energy usage per second.
protected void SetMySocketID (int slot_ID)
void SetPassiveState (bool state=true)
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
protected void SetPlugOwner (string selection_name, EntityAI device)
void SetPlugType (int new_type)
protected void SetPowered (bool state)
void SetUpdateInterval (float value)
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
void StartUpdates ()
protected void StopUpdates ()
void StoreEnergySourceIDs (int b1, int b2, int b3, int b4)
void SwitchOff ()
Energy manager: Switches OFF the device.
void SwitchOn ()
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
void Synch ()
void UnplugAllDevices ()
Energy manager: Unplugs everything directly connected to this device.
protected void UnplugCordFromSocket (int socket_to_unplug_ID)
void UnplugDevice (EntityAI device_to_unplug)
Energy manager: Unplugs the given device from this one.
void UnplugThis ()
Energy manager: Unplugs this device from its power source.
void UpdateCanWork ()
void UpdatePlugState ()
Energy manager: Unplugs this device when it's necesarry.
void UpdateSelections ()
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
protected void UpdateSocketSelections (int socket_id, EntityAI device_to_plug)
protected void WakeUpWholeBranch (EntityAI original_caller)
void ~ComponentEnergyManager ()
Private Attributes
protected const float DEFAULT_UPDATE_INTERVAL = 15
protected int m_AttachmentActionType
protected bool m_AutoSwitchOff
protected bool m_AutoSwitchOffWhenInCargo
protected bool m_CanStopWork
protected bool m_CanWork
protected ref TIntArray m_CompatiblePlugTypes
protected bool m_ConvertEnergyToQuantity
protected float m_CordLength
protected string m_CordTextureFile
protected Shape m_DebugPlugArrow
ref Timer m_DebugUpdate
ref map< string, EntityAI > m_DeviceByPlugSelection
protected float m_Energy
EntityAI m_EnergySource
protected int m_EnergySourceNetworkIDHigh = -1
protected int m_EnergySourceNetworkIDLow = -1
protected int m_EnergySourceStorageIDb1
protected int m_EnergySourceStorageIDb2
protected int m_EnergySourceStorageIDb3
protected int m_EnergySourceStorageIDb4
protected float m_EnergyStorageMax
protected float m_EnergyUsage
protected bool m_HasElectricityIcon
protected bool m_IsPassiveDevice
protected bool m_IsPlugged
protected bool m_IsSwichedOn
protected bool m_IsSwichedOnPreviousState
protected bool m_IsWorking
protected float m_LastUpdateTime
protected int m_MySocketID = -1
ref array< EntityAI > m_PluggedDevices
protected int m_PlugType
protected float m_ReduceMaxEnergyByDamageCoef
protected bool m_RestorePlugState
protected bool m_ShowSocketsInInventory
EntityAI m_Sockets [MAX_SOCKETS_COUNT]
protected float m_SocketsCount
protected float m_UpdateInterval
ref Timer m_UpdateQuantityTimer
ref Timer m_UpdateTimer
protected float m_WetnessExposure
const int MAX_SOCKETS_COUNT = 4
Static Private Attributes
static protected const string _AVAILABLE = "_available"
static protected const string _PLUGGED = "_plugged"
static protected bool m_DebugPlugs = false
static const string SEL_CORD_FOLDED = "cord_folded"
static const string SEL_CORD_PLUGGED = "cord_plugged"
static protected const string SOCKET_ = "socket_"
Detailed Description
Definition at line 18 of file componentenergymanager.c.
Constructor & Destructor Documentation
ComponentEnergyManager()
void ComponentEnergyManager::ComponentEnergyManager () inline private
Definition at line 82 of file componentenergymanager.c.
    {
        // Disable debug arrows on public release, so that they don't use their timers.
        #ifndef DEVELOPER
        m_DebugPlugs = false;
        #endif
    }
References m_DebugPlugs.
~ComponentEnergyManager()
void ComponentEnergyManager::~ComponentEnergyManager () inline private
Definition at line 90 of file componentenergymanager.c.
    {
        if (m_DebugPlugArrow)
        {
            m_DebugPlugArrow.Destroy();
            m_DebugPlugArrow = NULL;
        }
    }
References m_DebugPlugArrow.
Member Function Documentation
AddEnergy()
float ComponentEnergyManager::AddEnergy (float added_energy) inline private
Energy manager: Adds energy to this device and clamps it within its min/max storage limits. Returns the amount of energy that was clamped. Negative value is supported, but you should still use ConsumeEnergy(...) for propper substraction of energy.
Definition at line 1233 of file componentenergymanager.c.
    {
        if (added_energy != 0)
        {
            #ifdef DIAG_DEVELOPER
            if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_RECHARGE))
            {
                float timeAccel = FeatureTimeAccel.GetFeatureTimeAccelValue();
                added_energy *= timeAccel;
            }
            #endif
            bool energy_was_added = (added_energy > 0);
            float energy_to_clamp = GetEnergy() + added_energy;
            float clamped_energy = Math.Clamp( energy_to_clamp, 0, GetEnergyMax() );
            SetEnergy(clamped_energy);
            StartUpdates();
            if (energy_was_added)
                OnEnergyAdded();
            else
                OnEnergyConsumed();
            return energy_to_clamp - clamped_energy;
        }
        return 0;
    }
References Math::Clamp(), GetEnergy(), GetEnergyMax(), OnEnergyAdded(), OnEnergyConsumed(), SetEnergy(), and StartUpdates().
Referenced by FindAndConsumeEnergy(), and ItemBase::OnIgnitedTarget().
CanBePluggedInto()
bool ComponentEnergyManager::CanBePluggedInto (EntityAI potential_energy_provider) inline private
Energy manager: Returns true if this device can be plugged into the given energy source. Otherwise returns false.
Definition at line 1004 of file componentenergymanager.c.
    {
        return potential_energy_provider.GetCompEM().CanReceivePlugFrom( m_ThisEntityAI );
    }
References Component::m_ThisEntityAI.
CanReceivePlugFrom()
bool ComponentEnergyManager::CanReceivePlugFrom (EntityAI device_to_plug) inline private
Energy manager: Returns true if this device can receive power plug of the other device.
Definition at line 982 of file componentenergymanager.c.
    {
        // The following conditions are broken down for the sake of easier reading/debugging.
        if ( HasFreeSocket()  &&  device_to_plug != m_ThisEntityAI)
        {
            if ( device_to_plug.GetCompEM().GetEnergySource() != m_ThisEntityAI)
            {
                if ( IsPlugCompatible(device_to_plug.GetCompEM().GetPlugType()) )
                {
                    if ( device_to_plug.GetCompEM().IsEnergySourceAtReach( device_to_plug.GetPosition(), 0, m_ThisEntityAI.GetPosition() ) )
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References HasFreeSocket(), IsPlugCompatible(), and Component::m_ThisEntityAI.
Referenced by PlugInDevice().
CanSwitchOff()
bool ComponentEnergyManager::CanSwitchOff () inline private
Energy manager: Checks if the device can be switched OFF.
Definition at line 855 of file componentenergymanager.c.
    {
        if ( IsPassive() )
        {
            return false;
        }
        return IsSwitchedOn();
    }
References IsPassive(), and IsSwitchedOn().
Referenced by SwitchOff().
CanSwitchOn()
bool ComponentEnergyManager::CanSwitchOn () inline private
Energy manager: Checks if the device can be switched ON.
Definition at line 747 of file componentenergymanager.c.
    {
        if ( !IsSwitchedOn() )
        {
            return true;
        }
        return false;
    }
References IsSwitchedOn().
Referenced by SwitchOn().
CanWork()
bool ComponentEnergyManager::CanWork (float test_energy = -1) inline private
Energy manager: Checks whenever this device can do work or not.
Parameters
test_energy float optional parameter will overwite the default energy consumption value of this device.
Returns
bool Returns true if this device will work when it's switched on. Otherwise it returns false.
Definition at line 763 of file componentenergymanager.c.
    {
        if ( GetGame().IsMultiplayer()  &&  GetGame().IsClient() )
        {
            return m_CanWork;
        }
        if (m_ThisEntityAI && m_ThisEntityAI.IsRuined())
        {
            return false;
        }
        // Check if the power source(s) (which can be serially connected) can provide needed energy.
        float       energy_usage    = test_energy;
        float       gathered_energy = GetEnergy();
        EntityAI    energy_source   = GetEnergySource();
        if (energy_usage == -1)
        {
            energy_usage = GetEnergyUsage();
        }
        if ( !CheckWetness() )
        {
            return false;
        }
        if (gathered_energy <= 0 && energy_usage <= 0) //empty power source
        {
            return false;
        }
        int cycle_limit = 500; // Sanity check to definitely avoid infinite cycles
        while ( gathered_energy < energy_usage ) // Look for energy source if we don't have enough stored energy
        {
            // Safetycheck!
            if (cycle_limit > 0)
            {
                cycle_limit--;
            }
            else
            {
                DPrint("Energy Manager ERROR: The 'cycle_limit' safety break had to be activated to prevent possible game freeze. Dumping debug information...");
                //Print(m_ThisEntityAI);
                //Print(this);
                //Print(energy_source);
                if (energy_source.GetCompEM())
                {
                    //Print(energy_source.GetCompEM());
                }
                //Print(gathered_energy);
                //Print(energy_usage);
                //Print(m_ThisEntityAI.GetPosition());
                if (energy_source)
                {
                    //Print(energy_source.GetPosition());
                }
                //Print("End of the 'cycle_limit' safety break ^ ");
                return false;
            }
            // ^ Safetycheck!
            if ( energy_source  &&  energy_source != m_ThisEntityAI  &&  !energy_source.IsRuined()  &&  energy_source.GetCompEM()  &&  energy_source.GetCompEM().IsSwitchedOn()  &&  energy_source.GetCompEM().CheckWetness() )
            {
                gathered_energy = gathered_energy + energy_source.GetCompEM().GetEnergy();
                energy_source = energy_source.GetCompEM().GetEnergySource();
            }
            else
            {
                // No power source, no energy.
                return false;
            }
        }
        // Enough energy was found
        return true;
    }
References CheckWetness(), DPrint(), GetEnergy(), GetEnergySource(), GetEnergyUsage(), GetGame(), m_CanWork, and Component::m_ThisEntityAI.
Referenced by UpdateCanWork().
CheckWetness()
bool ComponentEnergyManager::CheckWetness () inline private
Energy manager: Checks if this device is being stopped from working by its wetness level. Returns true when its wetness is not blocking it, false when its to owet to work.
Definition at line 849 of file componentenergymanager.c.
    {
        return (m_ThisEntityAI.GetWet() <= 1-m_WetnessExposure);
    }
References Component::m_ThisEntityAI, and m_WetnessExposure.
Referenced by CanWork(), and DeviceUpdate().
ClearLastUpdateTime()
void ComponentEnergyManager::ClearLastUpdateTime () inline private
Definition at line 1717 of file componentenergymanager.c.
    {
        m_LastUpdateTime = 0;
    }
References m_LastUpdateTime.
Referenced by DeviceUpdate().
ConsumeEnergy()
bool ComponentEnergyManager::ConsumeEnergy (float amount) inline private
Energy manager: Consumes the given amount of energy. If there is not enough of stored energy in this device, then it tries to take it from its power source, if any exists. Returns true if the requested amount of energy was consumed. Otherwise it returns false.
Definition at line 900 of file componentenergymanager.c.
    {
        return FindAndConsumeEnergy(m_ThisEntityAI, amount, true);
    }
References FindAndConsumeEnergy(), and Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
DebugUpdate()
void ComponentEnergyManager::DebugUpdate () inline private
Definition at line 107 of file componentenergymanager.c.
    {
        if ( GetDebugPlugs() )
        {
            if ( GetGame().IsMultiplayer()  &&  GetGame().IsServer() )
            {
                if (m_DebugUpdate)
                    m_DebugUpdate.Stop();
                return;
            }
            if (m_DebugPlugArrow)
            {
                m_DebugPlugArrow.Destroy();
                m_DebugPlugArrow = NULL;
            }
            if ( GetEnergySource() )
            {
                vector from = GetEnergySource().GetPosition() + "0 0.1 0";
                vector to = m_ThisEntityAI.GetPosition() + "0 0.1 0";
                //No need to draw an arrow in this situation as it would not be visible
                if ( vector.DistanceSq(from, to) == 0 )
                    return;
                if ( m_ThisEntityAI.GetType() == "BarbedWire" ) // Special case for debugging of electric fences. Temporal code until offsets in fences are fixed.
                {
                    EntityAI BBB = m_ThisEntityAI.GetHierarchyParent();
                    if ( BBB  &&  BBB.GetType() == "Fence" )
                    {
                        to = to + "0 -1.3 0";
                    }
                }
                m_DebugPlugArrow = DrawArrow( from, to );
            }
        }
    }
References vector::DistanceSq(), DrawArrow(), GetDebugPlugs(), GetEnergySource(), GetGame(), m_DebugPlugArrow, m_DebugUpdate, and Component::m_ThisEntityAI.
DeviceUpdate()
void ComponentEnergyManager::DeviceUpdate () inline private
Definition at line 1733 of file componentenergymanager.c.
    {
        //vector pos = m_ThisEntityAI.GetPosition();
        //string debug_message = "Object " + m_ThisEntityAI.GetType() + "  |  Energy: " + GetEnergy() + "  |  IsAtReach: " + (IsEnergySourceAtReach(pos)).ToString();
        //Print(debug_message);
        if ( !m_IsPassiveDevice )
        {
            // 'm_ThisEntityAI' and 'this' must be checked because this method is caled from a timer
            if ( m_ThisEntityAI  &&  this  &&  IsSwitchedOn()  &&  !m_ThisEntityAI.IsRuined()  &&  CheckWetness()  &&  m_CanWork  &&  !GetGame().IsMissionMainMenu() )
            {
                bool was_powered = IsWorking();
                float consumed_energy_coef;
                // Make sure to use only as much % of energy as needed since this function can be called at random.
                if ( m_LastUpdateTime == 0 )
                {
                    RememberLastUpdateTime();
                    consumed_energy_coef = 1.0;
                }
                else
                {
                    float updatetime = GetCurrentUpdateTime();
                    float time = updatetime - m_LastUpdateTime;
                    consumed_energy_coef = time / 1000;
                }
                if (consumed_energy_coef > 0) // Prevents calling of OnWork events when no energy is consumed
                {
                    m_LastUpdateTime = GetCurrentUpdateTime();
                    float consume_energy = GetEnergyUsage() * consumed_energy_coef;
                    bool has_consumed_enough = true;
                    if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // single player or server side multiplayer
                        has_consumed_enough = ConsumeEnergy( consume_energy );
                    SetPowered( has_consumed_enough );
                    if ( has_consumed_enough )
                    {
                        if ( !was_powered )
{
                            m_CanStopWork = true;
                            WakeUpWholeBranch(m_ThisEntityAI);
                            GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStart", NULL, 0);
                            UpdateCanWork();
                        }
                        OnWork( consume_energy );
                    }
                    else
                    {
                        if ( was_powered )
{
                            if (m_CanStopWork)
{
                                m_CanStopWork = false;
                                ClearLastUpdateTime();
                                GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStop", NULL, 0); // This event is called only once when the device STOPS being powered
                                UpdateCanWork();
                                if (m_AutoSwitchOff)
{
                                    SwitchOff();
                                }
                            }
                        }
                        StopUpdates();
                    }
                }
                else
                {
                    ClearLastUpdateTime();
                }
            }
            else if (this  &&  m_ThisEntityAI)
            {
                SetPowered( false );
                StopUpdates();
                if (m_CanStopWork)
                {
                    m_CanStopWork = false;
                    ClearLastUpdateTime();
                    GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnWorkStop", NULL, 0); // This event is called only once when the device STOPS being powered
                    UpdateCanWork();
                    if (m_AutoSwitchOff)
                    {
                        SwitchOff();
                    }
                }
            }
        }
    }
References ScriptModule::CallFunction(), CheckWetness(), ClearLastUpdateTime(), ConsumeEnergy(), CGame::GameScript, GetCurrentUpdateTime(), GetEnergyUsage(), GetGame(), IsSwitchedOn(), IsWorking(), m_AutoSwitchOff, m_CanStopWork, m_CanWork, m_IsPassiveDevice, m_LastUpdateTime, Component::m_ThisEntityAI, OnWork(), RememberLastUpdateTime(), SetPowered(), StopUpdates(), SwitchOff(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by SetPassiveState(), SwitchOff(), and SwitchOn().
DrawArrow()
Shape ComponentEnergyManager::DrawArrow (vector from, vector to, float size = 0.5, int color = 0xFFFFFFFF, float flags = 0) inline private
Definition at line 149 of file componentenergymanager.c.
    {
        vector dir = to - from;
        dir.Normalize();
        vector dir1 = dir * size;
        size = size * 0.5;
        vector dir2 = dir.Perpend() * size;
        vector pts[5];
        pts[0] = from;
        pts[1] = to;
        pts[2] = to - dir1 - dir2;
        pts[3] = to - dir1 + dir2;
        pts[4] = to;
        return Shape.CreateLines(color, flags, pts, 5);
    }
References vector::Normalize(), vector::Perpend(), and Shape.
Referenced by DebugUpdate().
Event_OnAwake()
override void ComponentEnergyManager::Event_OnAwake () inline private
Definition at line 174 of file componentenergymanager.c.
    {
        string cfg_item = "CfgVehicles " + m_ThisEntityAI.GetType();
        string cfg_energy_manager = cfg_item + " EnergyManager ";
        // Read all config parameters
        m_EnergyUsage                   = GetGame().ConfigGetFloat(cfg_energy_manager + "energyUsagePerSecond");
        bool switch_on                  = GetGame().ConfigGetFloat(cfg_energy_manager + "switchOnAtSpawn");
        m_AutoSwitchOff                 = GetGame().ConfigGetFloat(cfg_energy_manager + "autoSwitchOff");
        m_HasElectricityIcon            = GetGame().ConfigGetFloat(cfg_energy_manager + "hasIcon");
        m_AutoSwitchOffWhenInCargo      = GetGame().ConfigGetFloat(cfg_energy_manager + "autoSwitchOffWhenInCargo");
        m_Energy                        = GetGame().ConfigGetFloat(cfg_energy_manager + "energyAtSpawn");
        m_EnergyStorageMax              = GetGame().ConfigGetFloat(cfg_energy_manager + "energyStorageMax");
        m_ReduceMaxEnergyByDamageCoef   = GetGame().ConfigGetFloat(cfg_energy_manager + "reduceMaxEnergyByDamageCoef");
        m_SocketsCount                  = GetGame().ConfigGetFloat(cfg_energy_manager + "powerSocketsCount");
        m_IsPassiveDevice               = GetGame().ConfigGetFloat(cfg_energy_manager + "isPassiveDevice");
        m_CordLength                    = GetGame().ConfigGetFloat(cfg_energy_manager + "cordLength");
        m_PlugType                      = GetGame().ConfigGetFloat(cfg_energy_manager + "plugType");
        m_AttachmentActionType          = GetGame().ConfigGetFloat(cfg_energy_manager + "attachmentAction");
        m_WetnessExposure               = GetGame().ConfigGetFloat(cfg_energy_manager + "wetnessExposure");
        float update_interval           = GetGame().ConfigGetFloat(cfg_energy_manager + "updateInterval");
        m_ConvertEnergyToQuantity       = GetGame().ConfigGetFloat(cfg_energy_manager + "convertEnergyToQuantity");
        // Check if energy->quantity converion is configured properly
        float cfg_max_quantity = GetGame().ConfigGetFloat (cfg_item + " varQuantityMax");
        if (m_ConvertEnergyToQuantity  &&  cfg_max_quantity <= 0)
        {
            string error = "Error! Item " + m_ThisEntityAI.GetType() + " has invalid configuration of the energy->quantity conversion feature. To fix this, add 'varQuantityMax' parameter with value higher than 0 to the item's config. Then make sure to re-build the PBO containing this item!";
            Error(error);
            m_ConvertEnergyToQuantity = false;
        }
        else
        {
            if (m_ConvertEnergyToQuantity)
            {
                if (!m_UpdateQuantityTimer)
                    m_UpdateQuantityTimer = new Timer( CALL_CATEGORY_SYSTEM );
                m_UpdateQuantityTimer.Run( 0.3 , this, "OnEnergyAdded", NULL, false);
            }
        }
        // Set update interval
        if ( update_interval <= 0 )
            update_interval = DEFAULT_UPDATE_INTERVAL;
        SetUpdateInterval( update_interval );
        // If energyAtSpawn is present, then use its value for energyStorageMax if that cfg param is not present (for convenience's sake)
        string cfg_check_energy_limit = cfg_energy_manager + "energyStorageMax";
        if ( !GetGame().ConfigIsExisting (cfg_check_energy_limit)  &&  m_Energy > 0 )
        {
            m_EnergyStorageMax = m_Energy;
        }
        // Fill m_CompatiblePlugTypes
        string cfg_check_plug_types = cfg_energy_manager + "compatiblePlugTypes";
        if ( GetGame().ConfigIsExisting (cfg_check_plug_types) )
        {
            m_CompatiblePlugTypes = new TIntArray;
            GetGame().ConfigGetIntArray(cfg_check_plug_types, m_CompatiblePlugTypes);
        }
        if (GetSocketsCount() > 0)
            m_PluggedDevices = new array<EntityAI>;
        if ( m_CordLength < 0 )
        {
            m_CordLength = 0;
            string error_message_cord = "Warning! " + m_ThisEntityAI.GetType() + ": config parameter 'cordLength' is less than 0! Cord length should not be negative!";
            DPrint(error_message_cord);
        }
        if (GetSocketsCount() > 0)
        {
            m_DeviceByPlugSelection = new map<string,EntityAI>;
            // Prepare the m_DeviceByPlugSelection
            string cfg_animation_sources = "cfgVehicles " + m_ThisEntityAI.GetType() + " " + "AnimationSources ";
            int animation_sources_count = GetGame().ConfigGetChildrenCount(cfg_animation_sources);
            for (int i_selection = 0; i_selection < animation_sources_count; i_selection++)
            {
                // TO DO: This could be optimized so not all selections on item are considered as plug/socket selections.
                string selection;
                GetGame().ConfigGetChildName(cfg_animation_sources, i_selection, selection);
                m_DeviceByPlugSelection.Set(selection, NULL);
            }
        }
        // Prepare sockets
        if ( m_SocketsCount > MAX_SOCKETS_COUNT )
        {
            m_SocketsCount = MAX_SOCKETS_COUNT;
            string error_message_sockets = "Error! " + m_ThisEntityAI.GetType() + ": config parameter 'powerSocketsCount' is higher than the current limit (" + MAX_SOCKETS_COUNT.ToString() + ")! Raise the limit (constant MAX_SOCKETS_COUNT) or decrease the powerSocketsCount parameter for this device!";
            DPrint(error_message_sockets);
        }
        m_Sockets[MAX_SOCKETS_COUNT]; // Handles selections for plugs in the sockets. Feel free to change the limit if needed.
        GetGame().ConfigGetText(cfg_energy_manager + "cordTextureFile", m_CordTextureFile);
        if ( switch_on )
        {
            SwitchOn();
        }
        for ( int i = 0; i <= GetSocketsCount(); ++i )
        {
            m_ThisEntityAI.HideSelection ( SOCKET_ + i.ToString() + _PLUGGED );
        }
        // Show/hide inventory sockets
        m_ShowSocketsInInventory = false;
        if ( GetSocketsCount() > 0  &&  IsPlugCompatible(PLUG_COMMON_APPLIANCE)  &&  m_ThisEntityAI.GetType() != "MetalWire" ) // metal wire filter is hopefully temporal.
        {
            m_ShowSocketsInInventory = true;
        }
        m_CanWork = HasEnoughStoredEnergy();
        m_ThisEntityAI.HideSelection( SEL_CORD_PLUGGED );
        #ifdef DEVELOPER
        GetGame().m_EnergyManagerArray.Insert( this );
        #endif
    }
References _PLUGGED, CALL_CATEGORY_SYSTEM, CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetIntArray(), CGame::ConfigGetText(), ConfigIsExisting(), DEFAULT_UPDATE_INTERVAL, DPrint(), Error(), GetGame(), GetSocketsCount(), HasEnoughStoredEnergy(), IsPlugCompatible(), m_AttachmentActionType, m_AutoSwitchOff, m_AutoSwitchOffWhenInCargo, m_CanWork, m_CompatiblePlugTypes, m_ConvertEnergyToQuantity, m_CordLength, m_CordTextureFile, m_DeviceByPlugSelection, m_Energy, m_EnergyStorageMax, m_EnergyUsage, m_HasElectricityIcon, m_IsPassiveDevice, m_PluggedDevices, m_PlugType, m_ReduceMaxEnergyByDamageCoef, m_ShowSocketsInInventory, m_Sockets, m_SocketsCount, Component::m_ThisEntityAI, m_UpdateQuantityTimer, m_WetnessExposure, MAX_SOCKETS_COUNT, PLUG_COMMON_APPLIANCE, SEL_CORD_PLUGGED, SetUpdateInterval(), SOCKET_, SwitchOn(), and string::ToString().
Event_OnInit()
override void ComponentEnergyManager::Event_OnInit () inline private
Definition at line 100 of file componentenergymanager.c.
    {
        m_ThisEntityAI.m_EM = this;
        GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnInitEnergy", NULL, 0);
    }
References ScriptModule::CallFunction(), CGame::GameScript, GetGame(), and Component::m_ThisEntityAI.
FindAndConsumeEnergy()
protected bool ComponentEnergyManager::FindAndConsumeEnergy (EntityAI original_caller, float amount, bool ignore_switch_state = false) inline private
Definition at line 1670 of file componentenergymanager.c.
    {
        if ( (ignore_switch_state  ||  IsSwitchedOn())  &&  !m_ThisEntityAI.IsRuined() )
        {
            float available_energy = AddEnergy(-amount);
            if ( available_energy < 0  &&  IsPlugged() )
            {
                // This devices does not has enough of stored energy, therefore it will take it from its power source (which can be a chain of cable reels)
                EntityAI next_power_source = GetEnergySource();
                if (next_power_source  &&  next_power_source != original_caller) // Prevents infinite loop if the power source is the original caller itself
                {
                    return next_power_source.GetCompEM().FindAndConsumeEnergy( original_caller, -available_energy );
                }
            }
            if ( available_energy >= 0)
            {
                return true;
            }
            return false;
        }
        else
        {
            return false;
        }
    }
References AddEnergy(), GetEnergySource(), IsPlugged(), IsSwitchedOn(), and Component::m_ThisEntityAI.
Referenced by ConsumeEnergy().
GetAttachmentAction()
int ComponentEnergyManager::GetAttachmentAction () inline private
Definition at line 1120 of file componentenergymanager.c.
    {
        return m_AttachmentActionType;
    }
References m_AttachmentActionType.
Referenced by OnAttachmentAdded(), and OnAttachmentRemoved().
GetCompatiblePlugTypes()
void ComponentEnergyManager::GetCompatiblePlugTypes (out TIntArray IDs) inline private
Definition at line 621 of file componentenergymanager.c.
    {
        IDs = m_CompatiblePlugTypes;
    }
References m_CompatiblePlugTypes.
GetCompType()
override int ComponentEnergyManager::GetCompType () inline private
Definition at line 314 of file componentenergymanager.c.
    {
        return COMP_TYPE_ENERGY_MANAGER;
    }
References COMP_TYPE_ENERGY_MANAGER.
GetCordLength()
float ComponentEnergyManager::GetCordLength () inline private
Energy manager: Returns the length of the virtual power cord.
Definition at line 1293 of file componentenergymanager.c.
    {
        return m_CordLength;
    }
References m_CordLength.
Referenced by IsEnergySourceAtReach().
GetCordTextureFile()
string ComponentEnergyManager::GetCordTextureFile () inline private
Energy manager: Returns path to the cord texture file.
Definition at line 1333 of file componentenergymanager.c.
    {
        return m_CordTextureFile;
    }
References m_CordTextureFile.
GetCurrentUpdateTime()
float ComponentEnergyManager::GetCurrentUpdateTime () inline private
Definition at line 1727 of file componentenergymanager.c.
    {
        return GetGame().GetTime();
    }
References GetGame(), and CGame::GetTime().
Referenced by DeviceUpdate(), and RememberLastUpdateTime().
GetDebugPlugs()
bool ComponentEnergyManager::GetDebugPlugs () inline private
Definition at line 355 of file componentenergymanager.c.
    {
        return m_DebugPlugs;
    }
References m_DebugPlugs.
Referenced by DebugUpdate().
GetDeviceBySocketID()
EntityAI ComponentEnergyManager::GetDeviceBySocketID (int id) inline private
Energy manager: Returns the device which is plugged into the given socket ID.
Definition at line 1305 of file componentenergymanager.c.
    {
        return m_Sockets[id];
    }
References m_Sockets.
Referenced by HasFreeSocket(), PlugCordIntoSocket(), UnplugCordFromSocket(), and UpdateSelections().
GetEnergy()
float ComponentEnergyManager::GetEnergy () inline private
Energy manager: Returns the amount of stored energy this device has.
Definition at line 1227 of file componentenergymanager.c.
    {
        return m_Energy;
    }
References m_Energy.
Referenced by AddEnergy(), CanWork(), ItemBase::HasEnoughEnergyForRepair(), HasEnoughStoredEnergy(), and TransferItemVariables().
GetEnergy0To1()
float ComponentEnergyManager::GetEnergy0To1 () inline private
Energy manager: Returns % of stored energy this device has as float (from 0.0 to 1.0)
Definition at line 1185 of file componentenergymanager.c.
    {
        if ( m_EnergyStorageMax > 0 )
        {
            return m_Energy / m_EnergyStorageMax;
        }
        return 0;
    }
References m_Energy, and m_EnergyStorageMax.
GetEnergy0To100()
int ComponentEnergyManager::GetEnergy0To100 () inline private
Energy manager: Returns % of stored energy this device has as integer (from 0 to 100)
Definition at line 1173 of file componentenergymanager.c.
    {
        if ( m_EnergyStorageMax > 0 )
        {
            int coef = Math.Round( m_Energy / m_EnergyStorageMax * 100 );
            return coef;
        }
        return 0;
    }
References m_Energy, m_EnergyStorageMax, and Math::Round().
GetEnergyMax()
float ComponentEnergyManager::GetEnergyMax () inline private
Energy manager: Returns the maximum amount of energy this device can curently store. If parameter 'reduceMaxEnergyByDamageCoef' is used in the config of this device then the returned value will be reduced by damage.
Definition at line 1264 of file componentenergymanager.c.
    {
        float max_health = 0;
        if ( m_ThisEntityAI.HasDamageSystem() )
            max_health = m_ThisEntityAI.GetMaxHealth("","");
        //else if ( m_ReduceMaxEnergyByDamageCoef != 0 )
        //  Error("[ERROR] ReduceMaxEnergyByDamageCoef is setup but " + m_ThisEntityAI.GetType() + " does not have a Damage System");
        if ( max_health == 0 || m_ReduceMaxEnergyByDamageCoef == 0 )
            return GetEnergyMaxPristine();
        float health = 100;
        if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // TO DO: Remove this IF when method GetHealth can be called on client!
            health = m_ThisEntityAI.GetHealth("","");
        float damage_coef = 1 - (health / max_health);
        return GetEnergyMaxPristine() * (1 - ( damage_coef * m_ReduceMaxEnergyByDamageCoef ) );
    }
References GetEnergyMaxPristine(), GetGame(), m_ReduceMaxEnergyByDamageCoef, and Component::m_ThisEntityAI.
Referenced by AddEnergy(), and SetEnergy0To1().
GetEnergyMaxPristine()
float ComponentEnergyManager::GetEnergyMaxPristine () inline private
Energy manager: Returns the maximum amount of energy this device can store. It's damage is NOT taken into account.
Definition at line 1287 of file componentenergymanager.c.
    {
        return m_EnergyStorageMax;
    }
References m_EnergyStorageMax.
Referenced by GetEnergyMax().
GetEnergySource()
EntityAI ComponentEnergyManager::GetEnergySource () inline private
Energy manager: Returns the energy source this device is plugged into.
Definition at line 1299 of file componentenergymanager.c.
    {
        return m_EnergySource;
    }
References m_EnergySource.
Referenced by CanWork(), DebugUpdate(), FindAndConsumeEnergy(), IsEnergySourceAtReach(), OnAttachmentRemoved(), UnplugThis(), and UpdateSelections().
GetEnergySourceNetworkIDHigh()
int ComponentEnergyManager::GetEnergySourceNetworkIDHigh () inline private
Definition at line 1156 of file componentenergymanager.c.
    {
        return m_EnergySourceNetworkIDHigh;
    }
References m_EnergySourceNetworkIDHigh.
GetEnergySourceNetworkIDLow()
int ComponentEnergyManager::GetEnergySourceNetworkIDLow () inline private
Definition at line 1150 of file componentenergymanager.c.
    {
        return m_EnergySourceNetworkIDLow;
    }
References m_EnergySourceNetworkIDLow.
GetEnergySourceStorageIDb1()
int ComponentEnergyManager::GetEnergySourceStorageIDb1 () inline private
Definition at line 1126 of file componentenergymanager.c.
    {
        return m_EnergySourceStorageIDb1;
    }
References m_EnergySourceStorageIDb1.
GetEnergySourceStorageIDb2()
int ComponentEnergyManager::GetEnergySourceStorageIDb2 () inline private
Definition at line 1132 of file componentenergymanager.c.
    {
        return m_EnergySourceStorageIDb2;
    }
References m_EnergySourceStorageIDb2.
GetEnergySourceStorageIDb3()
int ComponentEnergyManager::GetEnergySourceStorageIDb3 () inline private
Definition at line 1138 of file componentenergymanager.c.
    {
        return m_EnergySourceStorageIDb3;
    }
References m_EnergySourceStorageIDb3.
GetEnergySourceStorageIDb4()
int ComponentEnergyManager::GetEnergySourceStorageIDb4 () inline private
Definition at line 1144 of file componentenergymanager.c.
    {
        return m_EnergySourceStorageIDb4;
    }
References m_EnergySourceStorageIDb4.
GetEnergyUsage()
float ComponentEnergyManager::GetEnergyUsage () inline private
Energy manager: Returns the number of energy this device needs to run itself (See its config >> energyUsagePerSecond)
Definition at line 1214 of file componentenergymanager.c.
    {
        #ifdef DIAG_DEVELOPER
        if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_CONSUMPTION))
        {
            float timeAccel = FeatureTimeAccel.GetFeatureTimeAccelValue();
            return m_EnergyUsage * timeAccel;
        }
        #endif
        return m_EnergyUsage;
    }
References m_EnergyUsage.
Referenced by CanWork(), DeviceUpdate(), HasEnoughStoredEnergy(), and SetEnergy().
GetMySocketID()
protected int ComponentEnergyManager::GetMySocketID () inline private
Definition at line 1701 of file componentenergymanager.c.
    {
        return m_MySocketID;
    }
References m_MySocketID.
GetPluggedDevice()
EntityAI ComponentEnergyManager::GetPluggedDevice () inline private
Energy manager: Returns a device which is plugged into this one. If there are more devices to choose from then it returns the first one that is found.
Definition at line 1322 of file componentenergymanager.c.
    {
        if ( GetPluggedDevicesCount() > 0 )
        {
            return GetPluggedDevices().Get(0);
        }
        return NULL;
    }
References GetPluggedDevices(), and GetPluggedDevicesCount().
GetPluggedDevices()
array< EntityAI > ComponentEnergyManager::GetPluggedDevices () inline private
Energy manager: Returns an array of devices which are plugged into this one.
Definition at line 1339 of file componentenergymanager.c.
    {
        return m_PluggedDevices;
    }
References m_PluggedDevices.
Referenced by GetPluggedDevice(), GetPluggedDevicesCount(), GetPoweredDevices(), IsSelectionAPlug(), PlugInDevice(), UnplugAllDevices(), UnplugDevice(), and WakeUpWholeBranch().
GetPluggedDevicesCount()
int ComponentEnergyManager::GetPluggedDevicesCount () inline private
Energy manager: Returns the number of devices plugged into this one.
Definition at line 1162 of file componentenergymanager.c.
    {
        if ( GetPluggedDevices() )
        {
            return GetPluggedDevices().Count();
        }
        return 0;
    }
References GetPluggedDevices().
Referenced by GetPluggedDevice(), GetPoweredDevices(), HasFreeSocket(), UnplugAllDevices(), and UnplugDevice().
GetPlugOwner()
EntityAI ComponentEnergyManager::GetPlugOwner (string plug_selection_name) inline private
Energy manager: Returns the device to which the given plug selection belongs to.
Definition at line 1311 of file componentenergymanager.c.
    {
        if ( m_DeviceByPlugSelection.Contains(plug_selection_name) )
        {
            return m_DeviceByPlugSelection.Get(plug_selection_name);
        }
        return NULL;
    }
References m_DeviceByPlugSelection.
GetPlugType()
int ComponentEnergyManager::GetPlugType () inline private
Energy manager: Returns plug type. Check \DZ\data\basicDefines.hpp OR \Scripts\Classes\Component_constants.h files for types of plugs.
Definition at line 1114 of file componentenergymanager.c.
    {
        return m_PlugType;
    }
References m_PlugType.
GetPoweredDevices()
array< EntityAI > ComponentEnergyManager::GetPoweredDevices () inline private
Energy manager: Returns an array of devices which are plugged into this one and are turned on.
Definition at line 1345 of file componentenergymanager.c.
    {
        array<EntityAI> return_array = new array<EntityAI>;
        int plugged_devices_c = GetPluggedDevicesCount();
        for ( int i = 0; i < plugged_devices_c; ++i )
        {
            EntityAI device = GetPluggedDevices().Get(i);
            if ( IsSwitchedOn() )
            {
                return_array.Insert(device);
            }
        }
        return return_array;
    }
References GetPluggedDevices(), GetPluggedDevicesCount(), and IsSwitchedOn().
GetPreviousSwitchState()
bool ComponentEnergyManager::GetPreviousSwitchState () inline private
Definition at line 866 of file componentenergymanager.c.
    {
        return m_IsSwichedOnPreviousState;
    }
References m_IsSwichedOnPreviousState.
GetRestorePlugState()
bool ComponentEnergyManager::GetRestorePlugState () inline private
Definition at line 735 of file componentenergymanager.c.
    {
        return m_RestorePlugState;
    }
References m_RestorePlugState.
GetSocketsCount()
int ComponentEnergyManager::GetSocketsCount () inline private
Energy manager: Returns the count of power sockets (whenever used or not)
Definition at line 1108 of file componentenergymanager.c.
    {
        return m_SocketsCount;
    }
References m_SocketsCount.
Referenced by Event_OnAwake(), HasFreeSocket(), IsSelectionAPlug(), PlugCordIntoSocket(), UpdateSelections(), and WakeUpWholeBranch().
GetThisEntityAI()
EntityAI ComponentEnergyManager::GetThisEntityAI () inline private
Definition at line 168 of file componentenergymanager.c.
    {
        return m_ThisEntityAI;
    }
References Component::m_ThisEntityAI.
GetUpdateInterval()
float ComponentEnergyManager::GetUpdateInterval () inline private
Energy manager: Returns the update interval of this device.
Definition at line 1196 of file componentenergymanager.c.
    {
        #ifdef DIAG_DEVELOPER
        if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_CONSUMPTION) || (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.ENERGY_RECHARGE)))
        {
            return 1;//when modifying time accel, we might want to see things happen when they should, instead of waiting for the next tick
        }
        #endif
        return m_UpdateInterval;
    }
References m_UpdateInterval.
Referenced by StartUpdates().
GetWetnessExposure()
float ComponentEnergyManager::GetWetnessExposure () inline private
Returns wetness exposure value defined in config.
Definition at line 1208 of file componentenergymanager.c.
    {
        return m_WetnessExposure;
    }
References m_WetnessExposure.
HandleMoveInsideCargo()
void ComponentEnergyManager::HandleMoveInsideCargo (EntityAI container) inline private
Definition at line 717 of file componentenergymanager.c.
    {
        if ( m_AutoSwitchOffWhenInCargo )
        {
            if (IsSwitchedOn())
            {
                SwitchOff();
            }
        }
    }
References IsSwitchedOn(), m_AutoSwitchOffWhenInCargo, and SwitchOff().
HasConversionOfEnergyToQuantity()
bool ComponentEnergyManager::HasConversionOfEnergyToQuantity () inline private
Energy manager: Returns true if this item automatically converts its energy to quantity.
Definition at line 1016 of file componentenergymanager.c.
    {
        return m_ConvertEnergyToQuantity;
    }
References m_ConvertEnergyToQuantity.
HasElectricityIcon()
bool ComponentEnergyManager::HasElectricityIcon () inline private
Energy manager: Returns true if the electricity icon (bolt) is supposed to be visible for this device. False if not.
Definition at line 1010 of file componentenergymanager.c.
    {
        return m_HasElectricityIcon;
    }
References m_HasElectricityIcon.
HasEnoughStoredEnergy()
bool ComponentEnergyManager::HasEnoughStoredEnergy () inline private
Energy manager: Returns true if this device has enough of stored energy for its own use.
Definition at line 912 of file componentenergymanager.c.
    {
        if ( GetEnergy() > GetEnergyUsage() )
        {
            return true;
        }
        return false;
    }
References GetEnergy(), and GetEnergyUsage().
Referenced by Event_OnAwake().
HasFreeSocket()
bool ComponentEnergyManager::HasFreeSocket (int socket_id = -1) inline private
Energy manager: Returns true if this device has any free socket to receive a plug. If optional parameter socket_id is provided then only that socket ID is checked.
Definition at line 923 of file componentenergymanager.c.
    {
        if (socket_id == -1)
        {
            int plugged_devices = GetPluggedDevicesCount();
            int plugged_devices_limit = GetSocketsCount();
            if ( plugged_devices < plugged_devices_limit )
            {
                return true;
            }
            return false;
        }
        else
        {
            EntityAI device = GetDeviceBySocketID(socket_id);
            if (device)
            {
                return false;
            }
            else
            {
                return true;
            }
        }
    }
References GetDeviceBySocketID(), GetPluggedDevicesCount(), and GetSocketsCount().
Referenced by CanReceivePlugFrom().
HasVisibleSocketsInInventory()
bool ComponentEnergyManager::HasVisibleSocketsInInventory () inline private
Definition at line 1078 of file componentenergymanager.c.
    {
        return m_ShowSocketsInInventory;
    }
References m_ShowSocketsInInventory.
IsCordFolded()
bool ComponentEnergyManager::IsCordFolded () inline private
Energy manager: Returns true if the cord of this device is folded. Returns false if it's plugged.
Definition at line 878 of file componentenergymanager.c.
    {
        if ( IsPlugged() )
            return false;
        return true;
    }
References IsPlugged().
IsEnergySourceAtReach()
bool ComponentEnergyManager::IsEnergySourceAtReach (vector from_position, float add_tolerance = 0, vector override_source_position = "-1 -1 -1") inline private
Energy manager: Returns true if this device's virtual power cord can reach its energy source at the given position, depending on its cordLength config parameter. Otherwise returns false.
Parameters
from_position vector position from where the measurement will be taken
add_tolerance float parameter will add to the cord's length in meters (optional)
Returns
bool True if the power source will be at reach for the plug, or if config param cordLength is absent or 0. False if not, or is not plugged, or this device lacks Energy Manager component.
vector position_player = GetGame().GetPlayer().GetPosition();
if (my_device.GetCompEM().IsEnergySourceAtReach(position_player))
{
    Print("Power source is at reach!");
}else{
    Print("Power source is NOT at reach!");
}
Definition at line 1037 of file componentenergymanager.c.
    {
        if ( !IsPlugged()  &&  override_source_position == "-1 -1 -1" )
        {
            return false;
        }
        if ( GetCordLength() == 0 ) // 0 is an exception, which means infinitely long cable.
        {
            return true;
        }
        vector source_pos;
        float distance;
        if ( override_source_position == "-1 -1 -1" )
        {
            EntityAI energy_source = GetEnergySource();
            if (!energy_source)
                return false;
            source_pos = energy_source.GetPosition();
            distance = vector.Distance( from_position, source_pos );
        }
        else
        {
            source_pos = override_source_position;
            distance = vector.Distance( from_position, source_pos );
        }
        if ( distance > GetCordLength() + add_tolerance )
        {
            return false;
        }
        else
        {
            return true;
        }
    }
References vector::Distance(), GetCordLength(), GetEnergySource(), and IsPlugged().
Referenced by Hologram::CorrectMaterialPathName(), and UpdatePlugState().
IsPassive()
bool ComponentEnergyManager::IsPassive () inline private
Energy manager: Returns true if this device is set to be passive. False if otherwise.
Definition at line 887 of file componentenergymanager.c.
    {
        return m_IsPassiveDevice;
    }
References m_IsPassiveDevice.
Referenced by CanSwitchOff().
IsPlugCompatible()
bool ComponentEnergyManager::IsPlugCompatible (int plug_ID) inline private
Energy manager: Checks if the given plug is compatible with this device's socket. Used by CanReceivePlugFrom() method.
Definition at line 953 of file componentenergymanager.c.
    {
        if ( plug_ID == PLUG_UNDEFINED )
        {
            return true; // When plugType is undefined in config then make it compatible.
        }
        if ( m_CompatiblePlugTypes )
        {
            for ( int i = 0; i < m_CompatiblePlugTypes.Count(); i++ )
            {
                int plug_ID_to_Check = m_CompatiblePlugTypes.Get(i);
                if ( plug_ID_to_Check == plug_ID )
                {
                    return true;
                }
            }
        }
        else
        {
            // Since the config parameter compatiblePlugTypes is not present, then accept all plugs for simplicity's sake
            return true;
        }
        return false;
    }
References m_CompatiblePlugTypes, and PLUG_UNDEFINED.
Referenced by CanReceivePlugFrom(), and Event_OnAwake().
IsPlugged()
bool ComponentEnergyManager::IsPlugged () inline private
Energy manager: Returns true if this device is plugged into some other device (even if they are OFF or ruined). Otherwise it returns false.
Definition at line 893 of file componentenergymanager.c.
    {
        return m_IsPlugged;
    }
References m_IsPlugged.
Referenced by Hologram::CorrectMaterialPathName(), FindAndConsumeEnergy(), IsCordFolded(), and IsEnergySourceAtReach().
IsSelectionAPlug()
bool ComponentEnergyManager::IsSelectionAPlug (string selection_to_test) inline private
Energy manager: Returns true if this selection is a plug that's plugged into this device. Otherwise returns false.
Definition at line 1084 of file componentenergymanager.c.
    {
        if ( GetPluggedDevices() )
        {
            int socket_count = GetSocketsCount();
            for ( int i = socket_count; i >= 0; --i )
            {
                string real_selection = SOCKET_ + i.ToString() +_PLUGGED;
                if ( selection_to_test == real_selection)
                {
                    return true;
                }
            }
        }
        return false;
    }
References _PLUGGED, GetPluggedDevices(), GetSocketsCount(), SOCKET_, and string::ToString().
IsSwitchedOn()
bool ComponentEnergyManager::IsSwitchedOn () inline private
Energy manager: Returns state of the switch. Whenever the device is working or not does not matter. Use IsWorking() to account for that as well.
Definition at line 872 of file componentenergymanager.c.
    {
        return m_IsSwichedOn;
    }
References m_IsSwichedOn.
Referenced by CanSwitchOff(), CanSwitchOn(), DeviceUpdate(), FindAndConsumeEnergy(), GetPoweredDevices(), HandleMoveInsideCargo(), and TransferItemVariables().
IsWorking()
bool ComponentEnergyManager::IsWorking () inline private
Energy manager: Returns true if this device is working right now.
Definition at line 906 of file componentenergymanager.c.
    {
        return m_IsWorking;
    }
References m_IsWorking.
Referenced by DeviceUpdate(), and SwitchOff().
OnAttachmentAdded()
void ComponentEnergyManager::OnAttachmentAdded (EntityAI elec_device) inline private
Definition at line 1425 of file componentenergymanager.c.
    {
        int attachment_action_type = GetAttachmentAction();
        if ( attachment_action_type == PLUG_THIS_INTO_ATTACHMENT )
        {
            if ( elec_device.GetCompEM().CanReceivePlugFrom( m_ThisEntityAI ) )
            {
                PlugThisInto(elec_device);
            }
        }
        else if ( attachment_action_type == PLUG_ATTACHMENTS_INTO_THIS )
        {
            elec_device.GetCompEM().PlugThisInto(m_ThisEntityAI);
        }
    }
References GetAttachmentAction(), Component::m_ThisEntityAI, PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and PlugThisInto().
OnAttachmentRemoved()
void ComponentEnergyManager::OnAttachmentRemoved (EntityAI elec_device) inline private
Definition at line 1443 of file componentenergymanager.c.
    {
        int attachment_action_type = GetAttachmentAction();
        if ( attachment_action_type == PLUG_THIS_INTO_ATTACHMENT )
        {
            if ( elec_device == GetEnergySource() )
            {
                UnplugThis();
            }
        }
        else if ( attachment_action_type == PLUG_ATTACHMENTS_INTO_THIS )
        {
            elec_device.GetCompEM().UnplugThis();
        }
    }
References GetAttachmentAction(), GetEnergySource(), PLUG_ATTACHMENTS_INTO_THIS, PLUG_THIS_INTO_ATTACHMENT, and UnplugThis().
OnDeviceDestroyed()
void ComponentEnergyManager::OnDeviceDestroyed () inline private
Definition at line 320 of file componentenergymanager.c.
    {
        bool was_working = m_ThisEntityAI.GetCompEM().IsWorking();
        SwitchOff();
        UnplugAllDevices();
        UnplugThis();
        SetPowered( false );
        if ( was_working )
            m_ThisEntityAI.OnWorkStop();
        ;
    }
References Component::m_ThisEntityAI, SetPowered(), SwitchOff(), UnplugAllDevices(), and UnplugThis().
OnEnergyAdded()
void ComponentEnergyManager::OnEnergyAdded () inline private
Energy manager: Called when energy was added on this device.
Definition at line 1482 of file componentenergymanager.c.
    {
        if (m_UpdateQuantityTimer)
        {
            m_UpdateQuantityTimer.Stop();
            m_UpdateQuantityTimer = NULL;
        }
        m_ThisEntityAI.OnEnergyAdded();
    }
References Component::m_ThisEntityAI, and m_UpdateQuantityTimer.
Referenced by AddEnergy().
OnEnergyConsumed()
void ComponentEnergyManager::OnEnergyConsumed () inline private
Energy manager: Called when energy was consumed on this device.
Definition at line 1476 of file componentenergymanager.c.
    {
        m_ThisEntityAI.OnEnergyConsumed();
    }
References Component::m_ThisEntityAI.
Referenced by AddEnergy().
OnIsPlugged()
void ComponentEnergyManager::OnIsPlugged (EntityAI source_device) inline private
Definition at line 1373 of file componentenergymanager.c.
    {
        if (m_DebugPlugs)
        {
            if (!m_DebugUpdate)
                m_DebugUpdate = new Timer( CALL_CATEGORY_SYSTEM );
            if (!m_DebugUpdate.IsRunning())
                m_DebugUpdate.Run(0.01, this, "DebugUpdate", NULL, true);
        }
        UpdateCanWork();
        m_ThisEntityAI.OnIsPlugged(source_device);
    }
References CALL_CATEGORY_SYSTEM, m_DebugPlugs, m_DebugUpdate, Component::m_ThisEntityAI, and UpdateCanWork().
OnIsUnplugged()
void ComponentEnergyManager::OnIsUnplugged (EntityAI last_energy_source) inline private
Definition at line 1390 of file componentenergymanager.c.
    {
        UpdateCanWork();
        m_ThisEntityAI.OnIsUnplugged( last_energy_source );
    }
References Component::m_ThisEntityAI, and UpdateCanWork().
OnOwnSocketReleased()
void ComponentEnergyManager::OnOwnSocketReleased (EntityAI device) inline private
Definition at line 1411 of file componentenergymanager.c.
    {
        //play sound
        if ( device.GetCompEM().GetPlugType() == PLUG_COMMON_APPLIANCE && m_ThisEntityAI.IsInitialized() )
        {
            EffectSound sound_unplug;
            m_ThisEntityAI.PlaySoundSet( sound_unplug, "cablereel_unplug_SoundSet", 0, 0 );
        }
        m_ThisEntityAI.OnOwnSocketReleased( device );
    }
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by UnplugDevice().
OnOwnSocketTaken()
void ComponentEnergyManager::OnOwnSocketTaken (EntityAI device) inline private
Definition at line 1398 of file componentenergymanager.c.
    {
        //play sound
        if ( device.GetCompEM().GetPlugType() == PLUG_COMMON_APPLIANCE && m_ThisEntityAI.IsInitialized() )
        {
            EffectSound sound_plug;
            m_ThisEntityAI.PlaySoundSet( sound_plug, "cablereel_plugin_SoundSet", 0, 0 );
        }
        m_ThisEntityAI.OnOwnSocketTaken(device);
    }
References Component::m_ThisEntityAI, and PLUG_COMMON_APPLIANCE.
Referenced by PlugInDevice().
OnWork()
void ComponentEnergyManager::OnWork (float consumed_energy) inline private
Definition at line 1367 of file componentenergymanager.c.
    {
        m_ThisEntityAI.OnWork(consumed_energy);
    }
References Component::m_ThisEntityAI.
Referenced by DeviceUpdate().
PlugCordIntoSocket()
protected void ComponentEnergyManager::PlugCordIntoSocket (EntityAI device_to_plug, int socket_id = -1) inline private
Definition at line 1532 of file componentenergymanager.c.
    {
        if (socket_id >= 0)
        {
            EntityAI plug_owner_by_socket = GetDeviceBySocketID(socket_id);
            if (!plug_owner_by_socket)
            {
                UpdateSocketSelections(socket_id, device_to_plug);
                return;
            }
        }
        int slots_c = GetSocketsCount();
        for ( int i = 0; i < slots_c; ++i )
        {
            EntityAI plug_owner = GetDeviceBySocketID(i);
            if ( !plug_owner ) // Check if this socket is available
            {
                UpdateSocketSelections(i, device_to_plug);
                break;
            }
        }
    }
References GetDeviceBySocketID(), GetSocketsCount(), and UpdateSocketSelections().
Referenced by PlugInDevice().
PlugInDevice()
protected bool ComponentEnergyManager::PlugInDevice (EntityAI device_to_plug, int socket_id = -1) inline private
Definition at line 1607 of file componentenergymanager.c.
    {
        if ( CanReceivePlugFrom(device_to_plug) )
        {
            if ( device_to_plug.GetCompEM().IsPlugged() )
                device_to_plug.GetCompEM().UnplugThis();
            GetPluggedDevices().Insert( device_to_plug );
            device_to_plug.GetCompEM().SetEnergySource(m_ThisEntityAI);
            PlugCordIntoSocket( device_to_plug, socket_id ); // Visualisation
            OnOwnSocketTaken( device_to_plug );
            device_to_plug.GetCompEM().OnIsPlugged(m_ThisEntityAI);
            WakeUpWholeBranch( m_ThisEntityAI );
            if (GetGame().IsServer() || !GetGame().IsMultiplayer())
            {
                device_to_plug.HideSelection( SEL_CORD_FOLDED );
                device_to_plug.ShowSelection( SEL_CORD_PLUGGED );
            }
            return true;
        }
        return false;
    }
References CanReceivePlugFrom(), GetGame(), GetPluggedDevices(), Component::m_ThisEntityAI, OnOwnSocketTaken(), PlugCordIntoSocket(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and WakeUpWholeBranch().
PlugThisInto()
bool ComponentEnergyManager::PlugThisInto (EntityAI energy_source, int socket_id = -1) inline private
Energy manager: Attempts to plug this device into the energy_source. Returns true if the action was successfull, or false if not (due to plug incompatibility or no free socket on the receiver). The ID of the power socket is chosen automatically unless optional parameter socket_id is used (starting from 0). If the given ID is not free then a free socket is found.
Definition at line 741 of file componentenergymanager.c.
    {
        return energy_source.GetCompEM().PlugInDevice(m_ThisEntityAI, socket_id);
    }
References Component::m_ThisEntityAI.
Referenced by OnAttachmentAdded().
RefreshDebug()
void ComponentEnergyManager::RefreshDebug () inline private
Definition at line 335 of file componentenergymanager.c.
    {
        if ( m_DebugPlugs )
        {
            if ( !m_DebugUpdate )
                m_DebugUpdate = new Timer( CALL_CATEGORY_SYSTEM );
            if ( !m_DebugUpdate.IsRunning() )
                m_DebugUpdate.Run(0.01, this, "DebugUpdate", NULL, true);
        }
        else
        {
            if ( m_DebugPlugArrow )
            {
                m_DebugPlugArrow.Destroy();
                m_DebugPlugArrow = NULL;
            }
        }
    }
References CALL_CATEGORY_SYSTEM, m_DebugPlugArrow, m_DebugPlugs, and m_DebugUpdate.
Referenced by SetDebugPlugs().
RememberLastUpdateTime()
void ComponentEnergyManager::RememberLastUpdateTime () inline private
Definition at line 1722 of file componentenergymanager.c.
    {
        m_LastUpdateTime = GetCurrentUpdateTime();
    }
References GetCurrentUpdateTime(), and m_LastUpdateTime.
Referenced by DeviceUpdate().
ResetEnergyUsage()
void ComponentEnergyManager::ResetEnergyUsage () inline private
Energy manager: Resets energy usage to default (config) value.
Definition at line 666 of file componentenergymanager.c.
    {
        string cfg_energy_usage = "CfgVehicles " + m_ThisEntityAI.GetType() + " EnergyManager ";
        m_EnergyUsage = GetGame().ConfigGetFloat (cfg_energy_usage + "energyUsagePerSecond");
    }
References CGame::ConfigGetFloat(), GetGame(), m_EnergyUsage, and Component::m_ThisEntityAI.
RestorePlugState()
void ComponentEnergyManager::RestorePlugState (bool state) inline private
Definition at line 517 of file componentenergymanager.c.
    {
        m_RestorePlugState = state;
    }
References m_RestorePlugState.
SetAttachmentAction()
void ComponentEnergyManager::SetAttachmentAction (int new_action_type) inline private
Definition at line 654 of file componentenergymanager.c.
    {
        m_AttachmentActionType = new_action_type;
    }
References m_AttachmentActionType.
SetCordLength()
void ComponentEnergyManager::SetCordLength (float new_length) inline private
Energy manager: Changes the length of the virtual power cord.
Definition at line 642 of file componentenergymanager.c.
    {
        m_CordLength = new_length;
    }
References m_CordLength.
SetCordTextureFile()
void ComponentEnergyManager::SetCordTextureFile (string new_path) inline private
Definition at line 673 of file componentenergymanager.c.
    {
        m_CordTextureFile = new_path;
    }
References m_CordTextureFile.
SetDebugPlugs()
void ComponentEnergyManager::SetDebugPlugs (bool newVal) inline private
Definition at line 360 of file componentenergymanager.c.
    {
        m_DebugPlugs = newVal;
        RefreshDebug();
    }
References m_DebugPlugs, and RefreshDebug().
SetDeviceBySocketID()
void ComponentEnergyManager::SetDeviceBySocketID (int id, EntityAI plugged_device) inline private
Energy manager: Stores the device which is plugged into the given socket ID.
Definition at line 685 of file componentenergymanager.c.
    {
        m_Sockets[id] = plugged_device;
    }
References m_Sockets.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetElectricityIconVisibility()
void ComponentEnergyManager::SetElectricityIconVisibility (bool make_visible) inline private
Energy manager: Sets visibility of the electricity icon (bolt).
Definition at line 692 of file componentenergymanager.c.
    {
        m_HasElectricityIcon = make_visible;
    }
References m_HasElectricityIcon.
SetEnergy()
void ComponentEnergyManager::SetEnergy (float new_energy) inline private
Energy manager: Sets stored energy for this device. It ignores the min/max limit!
Definition at line 523 of file componentenergymanager.c.
    {
        if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client can't change energy value.
        {
            float old_energy = m_Energy;
            m_Energy = new_energy;
            if ( old_energy - GetEnergyUsage() <= 0 || (old_energy != new_energy && Math.Min(old_energy,new_energy) <= 0) )
            {
                UpdateCanWork();
            }
        }
    }
References GetEnergyUsage(), GetGame(), m_Energy, Math::Min(), and UpdateCanWork().
Referenced by AddEnergy(), SetEnergy0To1(), and TransferItemVariables().
SetEnergy0To1()
void ComponentEnergyManager::SetEnergy0To1 (float energy01) inline private
Energy manager: Sets stored energy for this device between 0 and MAX based on relative input value between 0 and 1.
Definition at line 538 of file componentenergymanager.c.
    {
        if (GetGame().IsServer() || !GetGame().IsMultiplayer()) // Client can't change energy value.
        {
            SetEnergy( Math.Lerp(0, GetEnergyMax(),energy01));
        }
    }
References GetEnergyMax(), GetGame(), Math::Lerp(), and SetEnergy().
SetEnergyMaxPristine()
void ComponentEnergyManager::SetEnergyMaxPristine (float new_limit) inline private
Energy manager: Changes the maximum amount of energy this device can store (when pristine).
Definition at line 636 of file componentenergymanager.c.
    {
        m_EnergyStorageMax = new_limit;
    }
References m_EnergyStorageMax.
SetEnergySource()
protected void ComponentEnergyManager::SetEnergySource (EntityAI source) inline private
Definition at line 1578 of file componentenergymanager.c.
    {
        m_EnergySource = source;
        if (source)
        {
            m_IsPlugged = true;
            StartUpdates();
        }
        else
        {
            m_IsPlugged = false;
            m_EnergySourceNetworkIDLow = -1;
            m_EnergySourceNetworkIDHigh = -1;
        }
        if (m_EnergySource)
        {
            m_EnergySource.GetNetworkID( m_EnergySourceNetworkIDLow, m_EnergySourceNetworkIDHigh );
            //Print(m_EnergySource);
            //Print(m_EnergySourceNetworkIDLow);
            //Print(m_EnergySourceNetworkIDHigh);
        }
        Synch();
    }
References m_EnergySource, m_EnergySourceNetworkIDHigh, m_EnergySourceNetworkIDLow, m_IsPlugged, StartUpdates(), and Synch().
Referenced by SetEnergySourceClient().
SetEnergySourceClient()
void ComponentEnergyManager::SetEnergySourceClient (EntityAI source) inline private
Definition at line 679 of file componentenergymanager.c.
    {
        SetEnergySource(source);
    }
References SetEnergySource().
SetEnergyUsage()
void ComponentEnergyManager::SetEnergyUsage (float new_usage) inline private
Energy manager: Changes the energy usage per second.
Definition at line 660 of file componentenergymanager.c.
    {
        m_EnergyUsage = new_usage;
    }
References m_EnergyUsage.
SetMySocketID()
protected void ComponentEnergyManager::SetMySocketID (int slot_ID) inline private
Definition at line 1707 of file componentenergymanager.c.
    {
        m_MySocketID = slot_ID;
    }
References m_MySocketID.
SetPassiveState()
void ComponentEnergyManager::SetPassiveState (bool state = true) inline private
Energy manager: Changes the status of this device. When it's passive (true), the main timer and OnWork events are not used.
Definition at line 439 of file componentenergymanager.c.
    {
        m_IsPassiveDevice = state;
        if ( !m_IsPassiveDevice )
        {
            DeviceUpdate();
        }
    }
References DeviceUpdate(), and m_IsPassiveDevice.
SetPlugOwner()
protected void ComponentEnergyManager::SetPlugOwner (string selection_name, EntityAI device) inline private
Definition at line 1636 of file componentenergymanager.c.
    {
        if ( m_DeviceByPlugSelection.Contains(selection_name) )
        {
            m_DeviceByPlugSelection.Set(selection_name, device);
        }
    }
References m_DeviceByPlugSelection.
Referenced by UnplugCordFromSocket(), and UpdateSocketSelections().
SetPlugType()
void ComponentEnergyManager::SetPlugType (int new_type) inline private
Definition at line 648 of file componentenergymanager.c.
    {
        m_PlugType = new_type;
    }
References m_PlugType.
SetPowered()
protected void ComponentEnergyManager::SetPowered (bool state) inline private
Definition at line 1664 of file componentenergymanager.c.
    {
        m_IsWorking = state;
    }
References m_IsWorking.
Referenced by DeviceUpdate(), and OnDeviceDestroyed().
SetUpdateInterval()
void ComponentEnergyManager::SetUpdateInterval (float value) inline private
Energy manager: Sets the interval of the OnWork(...) calls. Changing this value does not change the rate of energy consumption.
Definition at line 729 of file componentenergymanager.c.
    {
        m_UpdateInterval = value;
    }
References m_UpdateInterval.
Referenced by Event_OnAwake().
StartUpdates()
void ComponentEnergyManager::StartUpdates () inline private
Definition at line 1461 of file componentenergymanager.c.
    {
        if ( !m_IsPassiveDevice )
        {
            if (!m_UpdateTimer)
                m_UpdateTimer = new Timer( CALL_CATEGORY_SYSTEM );
            if ( !m_UpdateTimer.IsRunning() ) // Makes sure the timer is NOT running already
            {
                m_UpdateTimer.Run( GetUpdateInterval() , this, "DeviceUpdate", NULL, true);
            }
        }
    }
References CALL_CATEGORY_SYSTEM, GetUpdateInterval(), m_IsPassiveDevice, and m_UpdateTimer.
Referenced by AddEnergy(), SetEnergySource(), and SwitchOn().
StopUpdates()
protected void ComponentEnergyManager::StopUpdates () inline private
Definition at line 1499 of file componentenergymanager.c.
    {
        if (m_UpdateTimer)
        {
            m_UpdateTimer.Stop();
            m_UpdateTimer = NULL; // Delete timer from memory
        }
    }
References m_UpdateTimer.
Referenced by DeviceUpdate(), and SwitchOff().
StoreEnergySourceIDs()
void ComponentEnergyManager::StoreEnergySourceIDs (int b1, int b2, int b3, int b4) inline private
Definition at line 627 of file componentenergymanager.c.
    {
        m_EnergySourceStorageIDb1 = b1;
        m_EnergySourceStorageIDb2 = b2;
        m_EnergySourceStorageIDb3 = b3;
        m_EnergySourceStorageIDb4 = b4;
    }
References m_EnergySourceStorageIDb1, m_EnergySourceStorageIDb2, m_EnergySourceStorageIDb3, and m_EnergySourceStorageIDb4.
SwitchOff()
void ComponentEnergyManager::SwitchOff () inline private
Energy manager: Switches OFF the device.
Definition at line 404 of file componentenergymanager.c.
    {
        m_IsSwichedOnPreviousState = m_IsSwichedOn;
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if ( CanSwitchOff() )
            {
                m_IsSwichedOn = false;
                Synch();
                if ( IsWorking() )
                {
                    StopUpdates();
                    DeviceUpdate();
                }
                // 'Wakes up' all connected devices
                WakeUpWholeBranch( m_ThisEntityAI );
                UpdateCanWork();
                // Call event
                GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOff", NULL, 0);
            }
        }
        if ( !GetGame().IsServer()  &&  GetGame().IsMultiplayer() )
        {
            m_IsSwichedOn = false;
            GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOff", NULL, 0);
        }
    }
References ScriptModule::CallFunction(), CanSwitchOff(), DeviceUpdate(), CGame::GameScript, GetGame(), IsWorking(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StopUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by DeviceUpdate(), HandleMoveInsideCargo(), and OnDeviceDestroyed().
SwitchOn()
void ComponentEnergyManager::SwitchOn () inline private
Energy manager: Switches ON the device so it starts doing its work if it has enough energy.
Definition at line 373 of file componentenergymanager.c.
    {
        m_IsSwichedOnPreviousState = m_IsSwichedOn;
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            if ( CanSwitchOn() )
            {
                m_IsSwichedOn = true;
                Synch();
                DeviceUpdate(); // 'Wake up' this device now
                StartUpdates();
                // 'Wakes up' all connected devices
                WakeUpWholeBranch( m_ThisEntityAI );
                UpdateCanWork();
                // Call event
                GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOn", NULL, 0);
            }
        }
        if ( !GetGame().IsServer()  &&  GetGame().IsMultiplayer()/*  &&  CanSwitchOn() */) // I want the CanSwitchOn() check, but when it's here, the OnSwitchOn() event is never called on client-side due to engine's synchronization system changing the m_IsSwichedOn to true without any specific event beign called. (Yes there is OnVariablesSynchronized() but that is called also when m_CanWork is synchronized, so I need to write a method of knowing when was this specific value changed.)
        {
            GetGame().GameScript.CallFunction(m_ThisEntityAI, "OnSwitchOn", NULL, 0);
        }
    }
References ScriptModule::CallFunction(), CanSwitchOn(), DeviceUpdate(), CGame::GameScript, GetGame(), m_IsSwichedOn, m_IsSwichedOnPreviousState, Component::m_ThisEntityAI, StartUpdates(), Synch(), UpdateCanWork(), and WakeUpWholeBranch().
Referenced by Event_OnAwake(), and TransferItemVariables().
Synch()
void ComponentEnergyManager::Synch () inline private
Definition at line 1712 of file componentenergymanager.c.
    {
        m_ThisEntityAI.SetSynchDirty();
    }
References Component::m_ThisEntityAI.
Referenced by SetEnergySource(), SwitchOff(), SwitchOn(), and UpdateCanWork().
UnplugAllDevices()
void ComponentEnergyManager::UnplugAllDevices () inline private
Energy manager: Unplugs everything directly connected to this device.
Definition at line 504 of file componentenergymanager.c.
    {
        if ( GetPluggedDevices() ) // This check is necesarry in case this function is called before initialization
        {
            int index_start = GetPluggedDevicesCount() - 1;
            for ( int i = index_start; i >= 0; --i )
            {
                UnplugDevice( GetPluggedDevices().Get(i) );
            }
        }
    }
References Get(), GetPluggedDevices(), GetPluggedDevicesCount(), and UnplugDevice().
Referenced by OnDeviceDestroyed().
UnplugCordFromSocket()
protected void ComponentEnergyManager::UnplugCordFromSocket (int socket_to_unplug_ID) inline private
Definition at line 1646 of file componentenergymanager.c.
    {
        EntityAI plug_owner = GetDeviceBySocketID(socket_to_unplug_ID);
        if ( plug_owner )
        {
            SetDeviceBySocketID(socket_to_unplug_ID, NULL);
            string unplugged_selection = SOCKET_ + (socket_to_unplug_ID+1).ToString() + _AVAILABLE;
            m_ThisEntityAI.ShowSelection ( unplugged_selection );
            string plugged_selection = SOCKET_ + (socket_to_unplug_ID+1).ToString() + _PLUGGED;
            m_ThisEntityAI.HideSelection ( plugged_selection );
            SetPlugOwner( plugged_selection, NULL );
            plug_owner.GetCompEM().SetMySocketID(-1);
        }
    }
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by UnplugDevice().
UnplugDevice()
void ComponentEnergyManager::UnplugDevice (EntityAI device_to_unplug) inline private
Energy manager: Unplugs the given device from this one.
Definition at line 449 of file componentenergymanager.c.
    {
        if ( GetGame() )
        {
            int index_start = GetPluggedDevicesCount() - 1;
            bool device_found = false;
            for ( int i = index_start; i >= 0; --i )
            {
                EntityAI plugged_device = GetPluggedDevices().Get(i);
                if (plugged_device == device_to_unplug)
                {
                    GetPluggedDevices().Remove(i);
                    device_found = true;
                    break;
                }
            }
            if (device_found)
            {
                int socket_ID = device_to_unplug.GetCompEM().GetMySocketID();
                UnplugCordFromSocket( socket_ID );
                device_to_unplug.GetCompEM().SetEnergySource(NULL);
                device_to_unplug.GetCompEM().DeviceUpdate();
                device_to_unplug.GetCompEM().StartUpdates();
                device_to_unplug.GetCompEM().WakeUpWholeBranch( m_ThisEntityAI );
                if (m_DebugPlugs  &&  m_DebugPlugArrow)
                {
                    m_DebugPlugArrow.Destroy();
                    m_DebugPlugArrow = NULL;
                }
                OnOwnSocketReleased(device_to_unplug);
                device_to_unplug.GetCompEM().OnIsUnplugged( m_ThisEntityAI );
                device_to_unplug.ShowSelection ( SEL_CORD_FOLDED );
                device_to_unplug.HideSelection ( SEL_CORD_PLUGGED );
            }
        }
    }
References GetGame(), GetPluggedDevices(), GetPluggedDevicesCount(), m_DebugPlugArrow, m_DebugPlugs, Component::m_ThisEntityAI, OnOwnSocketReleased(), SEL_CORD_FOLDED, SEL_CORD_PLUGGED, and UnplugCordFromSocket().
Referenced by UnplugAllDevices().
UnplugThis()
void ComponentEnergyManager::UnplugThis () inline private
Energy manager: Unplugs this device from its power source.
Definition at line 492 of file componentenergymanager.c.
    {
        if ( GetGame() )
        {
            if ( GetEnergySource() )
            {
                GetEnergySource().GetCompEM().UnplugDevice(m_ThisEntityAI);
            }
        }
    }
References GetEnergySource(), GetGame(), and Component::m_ThisEntityAI.
Referenced by OnAttachmentRemoved(), OnDeviceDestroyed(), and UpdatePlugState().
UpdateCanWork()
void ComponentEnergyManager::UpdateCanWork () inline private
Definition at line 698 of file componentenergymanager.c.
    {
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            bool current_state = CanWork();
            if (current_state != m_CanWork)
            {
                m_CanWork = current_state;
                Synch();
                if ( m_ThisEntityAI && m_ThisEntityAI.GetHierarchyParent() && m_ThisEntityAI.GetHierarchyParent().GetCompEM() )
                {
                    m_ThisEntityAI.GetHierarchyParent().GetCompEM().UpdateCanWork();
                }
            }
        }
    }
References CanWork(), GetGame(), m_CanWork, Component::m_ThisEntityAI, and Synch().
Referenced by DeviceUpdate(), OnIsPlugged(), OnIsUnplugged(), SetEnergy(), SwitchOff(), and SwitchOn().
UpdatePlugState()
void ComponentEnergyManager::UpdatePlugState () inline private
Energy manager: Unplugs this device when it's necesarry.
Definition at line 587 of file componentenergymanager.c.
    {
        // Check if the item is held in hands during advanced placement
        if ( m_ThisEntityAI.GetHierarchyRootPlayer()  &&  m_ThisEntityAI.GetHierarchyRootPlayer().IsKindOf("SurvivorBase") )
        {
            // Yes it is in player's hands
            EntityAI player = m_ThisEntityAI.GetHierarchyRootPlayer();
            // Measure distance from the player
            vector pos_player = player.GetPosition();
            if ( ! IsEnergySourceAtReach( pos_player , 5 )  )
            {
                UnplugThis();
            }
        }
        else
        {
            // No it is not in player's hands.
            // Measure distance from the device
            vector pos_item = m_ThisEntityAI.GetPosition();
            if ( m_ThisEntityAI.GetHierarchyParent() )
            {
                pos_item = m_ThisEntityAI.GetHierarchyParent().GetPosition();
            }
            if ( ! IsEnergySourceAtReach( pos_item )  )
            {
                UnplugThis();
            }
        }
    }
References IsEnergySourceAtReach(), Component::m_ThisEntityAI, and UnplugThis().
UpdateSelections()
void ComponentEnergyManager::UpdateSelections () inline private
Energy manager: Shows/Hides all selections this system works with. Call this if something is wrong with selections (like during Init and Restore event in config)
Definition at line 547 of file componentenergymanager.c.
    {
        // Lets update sockets, if there are any
        int slots_c = GetSocketsCount();
        for ( int i = 0; i < slots_c; ++i )
        {
            EntityAI plug_owner = GetDeviceBySocketID(i);
            if ( plug_owner )
            {
                string plugged_selection = SOCKET_ + (i+1).ToString() + _PLUGGED;
                string available_selection = SOCKET_ + (i+1).ToString() + _AVAILABLE;
                m_ThisEntityAI.ShowSelection ( plugged_selection );
                m_ThisEntityAI.HideSelection ( available_selection );
                string texture_path = plug_owner.GetCompEM().GetCordTextureFile();
                int selection_index = m_ThisEntityAI.GetHiddenSelectionIndex( plugged_selection );
                m_ThisEntityAI.SetObjectTexture(selection_index, texture_path );
            }
            else
            {
                m_ThisEntityAI.ShowSelection ( SOCKET_ + (i+1).ToString() + _AVAILABLE );
                m_ThisEntityAI.HideSelection ( SOCKET_ + (i+1).ToString() + _PLUGGED );
            }
        }
        // Now lets update the cord/plug state
        if ( GetEnergySource() )
        {
            m_ThisEntityAI.ShowSelection ( SEL_CORD_PLUGGED );
            m_ThisEntityAI.HideSelection ( SEL_CORD_FOLDED );
        }
        else
        {
            m_ThisEntityAI.ShowSelection ( SEL_CORD_FOLDED );
            m_ThisEntityAI.HideSelection ( SEL_CORD_PLUGGED );
        }
    }
References _AVAILABLE, _PLUGGED, GetDeviceBySocketID(), GetEnergySource(), GetSocketsCount(), Component::m_ThisEntityAI, SEL_CORD_FOLDED, SEL_CORD_PLUGGED, SOCKET_, ToString(), and string::ToString().
UpdateSocketSelections()
protected void ComponentEnergyManager::UpdateSocketSelections (int socket_id, EntityAI device_to_plug) inline private
Definition at line 1560 of file componentenergymanager.c.
    {
        SetDeviceBySocketID(socket_id, device_to_plug);
        string plugged_selection = SOCKET_ + (socket_id+1).ToString() + _PLUGGED;
        SetPlugOwner( plugged_selection, device_to_plug );
        m_ThisEntityAI.ShowSelection ( plugged_selection );
        string unplugged_selection = SOCKET_ + (socket_id+1).ToString() + _AVAILABLE;
        m_ThisEntityAI.HideSelection ( unplugged_selection );
        string texture_path = device_to_plug.GetCompEM().GetCordTextureFile();
        int selection_index = m_ThisEntityAI.GetHiddenSelectionIndex( plugged_selection );
        m_ThisEntityAI.SetObjectTexture( selection_index, texture_path );
        device_to_plug.GetCompEM().SetMySocketID(socket_id);
    }
References _AVAILABLE, _PLUGGED, Component::m_ThisEntityAI, SetDeviceBySocketID(), SetPlugOwner(), SOCKET_, and ToString().
Referenced by PlugCordIntoSocket().
WakeUpWholeBranch()
protected void ComponentEnergyManager::WakeUpWholeBranch (EntityAI original_caller) inline private
Definition at line 1509 of file componentenergymanager.c.
    {
        if ( GetSocketsCount() > 0 )
        {
            array<EntityAI> plugged_devices = GetPluggedDevices();
            int plugged_devices_c = plugged_devices.Count();
            for ( int i = 0; i < plugged_devices_c; ++i )
            {
                EntityAI device = plugged_devices.Get(i);
                if ( device != original_caller ) // original_caller check here prevents infinite loops
                {
                    device.GetCompEM().UpdateCanWork();
                    device.GetCompEM().DeviceUpdate();
                    device.GetCompEM().StartUpdates();
                    device.GetCompEM().WakeUpWholeBranch( original_caller );
                }
            }
        }
    }
References GetPluggedDevices(), and GetSocketsCount().
Referenced by DeviceUpdate(), PlugInDevice(), SwitchOff(), and SwitchOn().
Member Data Documentation
_AVAILABLE
protected const string ComponentEnergyManager::_AVAILABLE = "_available" static private
Definition at line 63 of file componentenergymanager.c.
Referenced by UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
_PLUGGED
protected const string ComponentEnergyManager::_PLUGGED = "_plugged" static private
Definition at line 62 of file componentenergymanager.c.
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().
DEFAULT_UPDATE_INTERVAL
protected const float ComponentEnergyManager::DEFAULT_UPDATE_INTERVAL = 15 private
Definition at line 20 of file componentenergymanager.c.
Referenced by Event_OnAwake().
m_AttachmentActionType
protected int ComponentEnergyManager::m_AttachmentActionType private
Definition at line 44 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetAttachmentAction(), and SetAttachmentAction().
m_AutoSwitchOff
protected bool ComponentEnergyManager::m_AutoSwitchOff private
Definition at line 31 of file componentenergymanager.c.
Referenced by DeviceUpdate(), and Event_OnAwake().
m_AutoSwitchOffWhenInCargo
protected bool ComponentEnergyManager::m_AutoSwitchOffWhenInCargo private
Definition at line 34 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and HandleMoveInsideCargo().
m_CanStopWork
protected bool ComponentEnergyManager::m_CanStopWork private
Definition at line 29 of file componentenergymanager.c.
Referenced by DeviceUpdate().
m_CanWork
protected bool ComponentEnergyManager::m_CanWork private
Definition at line 28 of file componentenergymanager.c.
Referenced by CanWork(), DeviceUpdate(), Event_OnAwake(), and UpdateCanWork().
m_CompatiblePlugTypes
protected ref TIntArray ComponentEnergyManager::m_CompatiblePlugTypes private
Definition at line 67 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetCompatiblePlugTypes(), and IsPlugCompatible().
m_ConvertEnergyToQuantity
protected bool ComponentEnergyManager::m_ConvertEnergyToQuantity private
Definition at line 36 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and HasConversionOfEnergyToQuantity().
m_CordLength
protected float ComponentEnergyManager::m_CordLength private
Definition at line 53 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetCordLength(), and SetCordLength().
m_CordTextureFile
protected string ComponentEnergyManager::m_CordTextureFile private
Definition at line 58 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetCordTextureFile(), and SetCordTextureFile().
m_DebugPlugArrow
protected Shape ComponentEnergyManager::m_DebugPlugArrow private
Definition at line 22 of file componentenergymanager.c.
Referenced by DebugUpdate(), RefreshDebug(), UnplugDevice(), and ~ComponentEnergyManager().
m_DebugPlugs
protected bool ComponentEnergyManager::m_DebugPlugs = false static private
Definition at line 21 of file componentenergymanager.c.
Referenced by ComponentEnergyManager(), GetDebugPlugs(), OnIsPlugged(), RefreshDebug(), SetDebugPlugs(), and UnplugDevice().
m_DebugUpdate
ref Timer ComponentEnergyManager::m_DebugUpdate private
Definition at line 74 of file componentenergymanager.c.
Referenced by DebugUpdate(), OnIsPlugged(), and RefreshDebug().
m_DeviceByPlugSelection
ref map<string,EntityAI> ComponentEnergyManager::m_DeviceByPlugSelection private
Definition at line 70 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetPlugOwner(), and SetPlugOwner().
m_Energy
protected float ComponentEnergyManager::m_Energy private
Definition at line 49 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetEnergy(), GetEnergy0To1(), GetEnergy0To100(), and SetEnergy().
m_EnergySource
EntityAI ComponentEnergyManager::m_EnergySource private
Definition at line 68 of file componentenergymanager.c.
Referenced by GetEnergySource(), and SetEnergySource().
m_EnergySourceNetworkIDHigh
protected int ComponentEnergyManager::m_EnergySourceNetworkIDHigh = -1 private
Definition at line 46 of file componentenergymanager.c.
Referenced by GetEnergySourceNetworkIDHigh(), and SetEnergySource().
m_EnergySourceNetworkIDLow
protected int ComponentEnergyManager::m_EnergySourceNetworkIDLow = -1 private
Definition at line 45 of file componentenergymanager.c.
Referenced by GetEnergySourceNetworkIDLow(), and SetEnergySource().
m_EnergySourceStorageIDb1
protected int ComponentEnergyManager::m_EnergySourceStorageIDb1 private
Definition at line 40 of file componentenergymanager.c.
Referenced by GetEnergySourceStorageIDb1(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb2
protected int ComponentEnergyManager::m_EnergySourceStorageIDb2 private
Definition at line 41 of file componentenergymanager.c.
Referenced by GetEnergySourceStorageIDb2(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb3
protected int ComponentEnergyManager::m_EnergySourceStorageIDb3 private
Definition at line 42 of file componentenergymanager.c.
Referenced by GetEnergySourceStorageIDb3(), and StoreEnergySourceIDs().
m_EnergySourceStorageIDb4
protected int ComponentEnergyManager::m_EnergySourceStorageIDb4 private
Definition at line 43 of file componentenergymanager.c.
Referenced by GetEnergySourceStorageIDb4(), and StoreEnergySourceIDs().
m_EnergyStorageMax
protected float ComponentEnergyManager::m_EnergyStorageMax private
Definition at line 50 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetEnergy0To1(), GetEnergy0To100(), GetEnergyMaxPristine(), and SetEnergyMaxPristine().
m_EnergyUsage
protected float ComponentEnergyManager::m_EnergyUsage private
Definition at line 48 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetEnergyUsage(), ResetEnergyUsage(), and SetEnergyUsage().
m_HasElectricityIcon
protected bool ComponentEnergyManager::m_HasElectricityIcon private
Definition at line 33 of file componentenergymanager.c.
Referenced by Event_OnAwake(), HasElectricityIcon(), and SetElectricityIconVisibility().
m_IsPassiveDevice
protected bool ComponentEnergyManager::m_IsPassiveDevice private
Definition at line 26 of file componentenergymanager.c.
Referenced by DeviceUpdate(), Event_OnAwake(), IsPassive(), SetPassiveState(), and StartUpdates().
m_IsPlugged
protected bool ComponentEnergyManager::m_IsPlugged private
Definition at line 35 of file componentenergymanager.c.
Referenced by IsPlugged(), and SetEnergySource().
m_IsSwichedOn
protected bool ComponentEnergyManager::m_IsSwichedOn private
Definition at line 24 of file componentenergymanager.c.
Referenced by IsSwitchedOn(), SwitchOff(), and SwitchOn().
m_IsSwichedOnPreviousState
protected bool ComponentEnergyManager::m_IsSwichedOnPreviousState private
Definition at line 25 of file componentenergymanager.c.
Referenced by GetPreviousSwitchState(), SwitchOff(), and SwitchOn().
m_IsWorking
protected bool ComponentEnergyManager::m_IsWorking private
Definition at line 27 of file componentenergymanager.c.
Referenced by IsWorking(), and SetPowered().
m_LastUpdateTime
protected float ComponentEnergyManager::m_LastUpdateTime private
Definition at line 54 of file componentenergymanager.c.
Referenced by ClearLastUpdateTime(), DeviceUpdate(), and RememberLastUpdateTime().
m_MySocketID
protected int ComponentEnergyManager::m_MySocketID = -1 private
Definition at line 38 of file componentenergymanager.c.
Referenced by GetMySocketID(), and SetMySocketID().
m_PluggedDevices
ref array<EntityAI> ComponentEnergyManager::m_PluggedDevices private
Definition at line 69 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and GetPluggedDevices().
m_PlugType
protected int ComponentEnergyManager::m_PlugType private
Definition at line 39 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetPlugType(), and SetPlugType().
m_ReduceMaxEnergyByDamageCoef
protected float ComponentEnergyManager::m_ReduceMaxEnergyByDamageCoef private
Definition at line 51 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and GetEnergyMax().
m_RestorePlugState
protected bool ComponentEnergyManager::m_RestorePlugState private
Definition at line 30 of file componentenergymanager.c.
Referenced by GetRestorePlugState(), and RestorePlugState().
m_ShowSocketsInInventory
protected bool ComponentEnergyManager::m_ShowSocketsInInventory private
Definition at line 32 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and HasVisibleSocketsInInventory().
m_Sockets
EntityAI ComponentEnergyManager::m_Sockets[MAX_SOCKETS_COUNT] private
Definition at line 77 of file componentenergymanager.c.
Referenced by Event_OnAwake(), GetDeviceBySocketID(), and SetDeviceBySocketID().
m_SocketsCount
protected float ComponentEnergyManager::m_SocketsCount private
Definition at line 52 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and GetSocketsCount().
m_UpdateInterval
protected float ComponentEnergyManager::m_UpdateInterval private
Definition at line 56 of file componentenergymanager.c.
Referenced by GetUpdateInterval(), and SetUpdateInterval().
m_UpdateQuantityTimer
ref Timer ComponentEnergyManager::m_UpdateQuantityTimer private
Definition at line 73 of file componentenergymanager.c.
Referenced by Event_OnAwake(), and OnEnergyAdded().
m_UpdateTimer
ref Timer ComponentEnergyManager::m_UpdateTimer private
Definition at line 72 of file componentenergymanager.c.
Referenced by StartUpdates(), and StopUpdates().
m_WetnessExposure
protected float ComponentEnergyManager::m_WetnessExposure private
Definition at line 55 of file componentenergymanager.c.
Referenced by CheckWetness(), Event_OnAwake(), and GetWetnessExposure().
MAX_SOCKETS_COUNT
const int ComponentEnergyManager::MAX_SOCKETS_COUNT = 4 private
Definition at line 76 of file componentenergymanager.c.
Referenced by Event_OnAwake().
SEL_CORD_FOLDED
const string ComponentEnergyManager::SEL_CORD_FOLDED = "cord_folded" static private
Definition at line 65 of file componentenergymanager.c.
Referenced by PlugInDevice(), UnplugDevice(), and UpdateSelections().
SEL_CORD_PLUGGED
const string ComponentEnergyManager::SEL_CORD_PLUGGED = "cord_plugged" static private
Definition at line 64 of file componentenergymanager.c.
Referenced by ActionUnplugThisByCord::ActionCondition(), Event_OnAwake(), PlugInDevice(), UnplugDevice(), and UpdateSelections().
SOCKET_
protected const string ComponentEnergyManager::SOCKET_ = "socket_" static private
Definition at line 61 of file componentenergymanager.c.
Referenced by Event_OnAwake(), IsSelectionAPlug(), UnplugCordFromSocket(), UpdateSelections(), and UpdateSocketSelections().