DayzKode: UIScriptedWindow Class Reference
UIScriptedWindow Class Reference
Private Member Functions
void CloseWindow ()
private TStringArray GetMissionList ()
Widget GetWidgetRoot ()
void HideWindow ()
Widget Init ()
override Widget Init ()
void MissionLoader (int id)
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
override bool OnClick (Widget w, int x, int y, int button)
bool OnController (Widget w, int control, int value)
bool OnDoubleClick (Widget w, int x, int y, int button)
bool OnDrag (Widget w, int x, int y)
bool OnDragging (Widget w, int x, int y, Widget reciever)
bool OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool OnDrop (Widget w, int x, int y, Widget reciever)
bool OnDropReceived (Widget w, int x, int y, Widget reciever)
bool OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
bool OnFocus (Widget w, int x, int y)
bool OnFocusLost (Widget w, int x, int y)
bool OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool OnKeyDown (Widget w, int x, int y, int key)
bool OnKeyPress (Widget w, int x, int y, int key)
bool OnKeyUp (Widget w, int x, int y, int key)
bool OnModalResult (Widget w, int x, int y, int code, int result)
bool OnMouseButtonDown (Widget w, int x, int y, int button)
bool OnMouseButtonUp (Widget w, int x, int y, int button)
bool OnMouseEnter (Widget w, int x, int y)
bool OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool OnMouseWheel (Widget w, int x, int y, int wheel)
bool OnSelect (Widget w, int x, int y)
void ShowWindow ()
void UIScriptedWindow (int id)
void ~UIScriptedWindow ()
Static Private Member Functions
static void AddToActiveWindows (int id, UIScriptedWindow window)
static map< int, UIScriptedWindow > GetActiveWindows ()
static UIScriptedWindow GetWindow (int id)
static void RemoveFromActiveWindows (int id)
Private Attributes
int m_Id
ref TStringArray m_ListMissionsNames
string m_PathToMissions
ButtonWidget m_WgtBtnMsnClose
ButtonWidget m_WgtBtnMsnPlay
TextListboxWidget m_WgtLstMsnList
Widget m_WgtRoot
Static Private Attributes
static ref map< int, UIScriptedWindow > m_ActiveWindows
Detailed Description
Definition at line 1 of file uiscriptedwindow.c.
Constructor & Destructor Documentation
UIScriptedWindow()
void UIScriptedWindow::UIScriptedWindow (int id) inline private
Definition at line 44 of file uiscriptedwindow.c.
    {
        m_Id = id;
    }
References m_Id.
~UIScriptedWindow()
void UIScriptedWindow::~UIScriptedWindow () inline private
Definition at line 49 of file uiscriptedwindow.c.
    {
        GetWidgetRoot().Show(false);
        delete GetWidgetRoot();
    }
References GetWidgetRoot().
Member Function Documentation
AddToActiveWindows()
static void UIScriptedWindow::AddToActiveWindows (int id, UIScriptedWindow window) inline static private
Definition at line 9 of file uiscriptedwindow.c.
    {
        if ( m_ActiveWindows == NULL )
        {
            m_ActiveWindows = new map<int, UIScriptedWindow>;
        }
        m_ActiveWindows.Insert( id, window );
    }
References m_ActiveWindows.
Referenced by UIManager::OpenWindow().
CloseWindow()
void UIScriptedWindow::CloseWindow () inline private
Definition at line 74 of file uiscriptedwindow.c.
    {
        GetGame().GetUIManager().CloseWindow( m_Id );
    }
References UIManager::CloseWindow(), GetGame(), CGame::GetUIManager(), and m_Id.
Referenced by OnClick().
GetActiveWindows()
static map< int, UIScriptedWindow > UIScriptedWindow::GetActiveWindows () inline static private
Definition at line 37 of file uiscriptedwindow.c.
    {
        return m_ActiveWindows;
    }
References m_ActiveWindows.
Referenced by UIMenuPanel::OnChange(), UIMenuPanel::OnClick(), UIMenuPanel::OnController(), UIMenuPanel::OnDoubleClick(), UIMenuPanel::OnDrag(), UIMenuPanel::OnDragging(), UIMenuPanel::OnDraggingOver(), UIMenuPanel::OnDrop(), UIMenuPanel::OnDropReceived(), UIMenuPanel::OnEvent(), UIMenuPanel::OnFocus(), UIMenuPanel::OnFocusLost(), UIMenuPanel::OnItemSelected(), UIMenuPanel::OnKeyDown(), UIMenuPanel::OnKeyPress(), UIMenuPanel::OnKeyUp(), UIMenuPanel::OnModalResult(), UIMenuPanel::OnMouseButtonDown(), UIMenuPanel::OnMouseButtonUp(), UIMenuPanel::OnMouseEnter(), UIMenuPanel::OnMouseLeave(), UIMenuPanel::OnMouseWheel(), and UIMenuPanel::OnSelect().
GetMissionList()
private TStringArray UIScriptedWindow::GetMissionList () inline private
Definition at line 34 of file missionloader.c.
    {
        string  file_name;
        int     file_attr;
        int     flags;
        TStringArray list = new TStringArray;
        m_PathToMissions = "$saves:\\missions";
        string path_find_pattern = m_PathToMissions+"\\*"; //*/
        FindFileHandle file_handler = FindFile(path_find_pattern, file_name, file_attr, flags);
        bool found = true;
        while ( found )
        {
            if ( file_attr & FileAttr.DIRECTORY )
            {
                list.Insert(file_name);
            }
            found = FindNextFile(file_handler, file_name, file_attr);;
        }
        return list;
    }
References FindFile(), and FindNextFile().
Referenced by Init().
GetWidgetRoot()
Widget UIScriptedWindow::GetWidgetRoot () inline private
Definition at line 55 of file uiscriptedwindow.c.
    {
        return m_WgtRoot;
    }
References m_WgtRoot.
Referenced by HideWindow(), ShowWindow(), and ~UIScriptedWindow().
GetWindow()
static UIScriptedWindow UIScriptedWindow::GetWindow (int id) inline static private
Definition at line 27 of file uiscriptedwindow.c.
    {
        if ( m_ActiveWindows )
        {
            return m_ActiveWindows.Get( id );
        }
        return NULL;
    }
References m_ActiveWindows.
Referenced by UIManager::CloseWindow(), UIManager::IsWindowOpened(), and UIManager::OpenWindow().
HideWindow()
void UIScriptedWindow::HideWindow () inline private
Definition at line 69 of file uiscriptedwindow.c.
    {
        GetWidgetRoot().Show( false );
    }
References GetWidgetRoot().
Referenced by UIManager::CloseWindow().
Init() [1/2]
Widget UIScriptedWindow::Init () inline private
Definition at line 60 of file uiscriptedwindow.c.
    {
    }
Referenced by UIManager::OpenWindow().
Init() [2/2]
override Widget UIScriptedWindow::Init () inline private
Definition at line 15 of file missionloader.c.
    {
        m_ListMissionsNames = GetMissionList();
        m_WgtRoot           = GetGame().GetWorkspace().CreateWidgets("gui/layouts/day_z_mission_loader.layout", GetGame().GetUIManager().GetMenu().GetLayoutRoot() );
        m_WgtLstMsnList = TextListboxWidget.Cast( m_WgtRoot.FindAnyWidget("wgt_lst_missions") );
        m_WgtBtnMsnPlay = ButtonWidget.Cast( m_WgtRoot.FindAnyWidget("wgt_btn_mission_play") );
        m_WgtBtnMsnClose = ButtonWidget.Cast( m_WgtRoot.FindAnyWidget("wgt_btn_mission_close") );
        for ( int i = 0; i < m_ListMissionsNames.Count(); ++i )
        {
            string mission_name = m_ListMissionsNames.Get(i);
            m_WgtLstMsnList.AddItem(mission_name, NULL, 0);
        }
        return m_WgtRoot;
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), GetMissionList(), CGame::GetWorkspace(), m_WgtRoot, and m_WgtRoot.
MissionLoader()
void UIScriptedWindow::MissionLoader (int id) inline private
Definition at line 10 of file missionloader.c.
    {
        m_Id = id;
    }
References m_Id.
OnChange()
bool UIScriptedWindow::OnChange (Widget w, int x, int y, bool finished) inline private
Definition at line 160 of file uiscriptedwindow.c.
    {
        return false;
    }
OnClick() [1/2]
bool UIScriptedWindow::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 80 of file uiscriptedwindow.c.
    {
        return false;
    }
OnClick() [2/2]
override bool UIScriptedWindow::OnClick (Widget w, int x, int y, int button) inline private
Definition at line 60 of file missionloader.c.
    {
        if ( w == m_WgtBtnMsnPlay )
        {
            int row_index = m_WgtLstMsnList.GetSelectedRow();
            string mission_name = m_ListMissionsNames.Get(row_index);
            string mission_path = m_PathToMissions+"\\"+mission_name;
            Log(mission_path);
            GetGame().PlayMission(mission_path);
            return true;
        }
        if ( w == m_WgtBtnMsnClose )
        {
            CloseWindow();
            return true;
        }
        return false;
    }
References CloseWindow(), GetGame(), Log(), and CGame::PlayMission().
OnController()
bool UIScriptedWindow::OnController (Widget w, int control, int value) inline private
Definition at line 140 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDoubleClick()
bool UIScriptedWindow::OnDoubleClick (Widget w, int x, int y, int button) inline private
Definition at line 90 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDrag()
bool UIScriptedWindow::OnDrag (Widget w, int x, int y) inline private
Definition at line 165 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDragging()
bool UIScriptedWindow::OnDragging (Widget w, int x, int y, Widget reciever) inline private
Definition at line 170 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDraggingOver()
bool UIScriptedWindow::OnDraggingOver (Widget w, int x, int y, Widget reciever) inline private
Definition at line 175 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDrop()
bool UIScriptedWindow::OnDrop (Widget w, int x, int y, Widget reciever) inline private
Definition at line 180 of file uiscriptedwindow.c.
    {
        return false;
    }
OnDropReceived()
bool UIScriptedWindow::OnDropReceived (Widget w, int x, int y, Widget reciever) inline private
Definition at line 185 of file uiscriptedwindow.c.
    {
        return false;
    }
OnEvent()
bool UIScriptedWindow::OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) inline private
Definition at line 190 of file uiscriptedwindow.c.
    {
        return false;
    }
OnFocus()
bool UIScriptedWindow::OnFocus (Widget w, int x, int y) inline private
Definition at line 105 of file uiscriptedwindow.c.
    {
        return false;
    }
OnFocusLost()
bool UIScriptedWindow::OnFocusLost (Widget w, int x, int y) inline private
Definition at line 110 of file uiscriptedwindow.c.
    {
        return false;
    }
OnItemSelected()
bool UIScriptedWindow::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) inline private
Definition at line 100 of file uiscriptedwindow.c.
    {
        return false;
    }
OnKeyDown()
bool UIScriptedWindow::OnKeyDown (Widget w, int x, int y, int key) inline private
Definition at line 145 of file uiscriptedwindow.c.
    {
        return false;
    }
OnKeyPress()
bool UIScriptedWindow::OnKeyPress (Widget w, int x, int y, int key) inline private
Definition at line 155 of file uiscriptedwindow.c.
    {
        return false;
    }
OnKeyUp()
bool UIScriptedWindow::OnKeyUp (Widget w, int x, int y, int key) inline private
Definition at line 150 of file uiscriptedwindow.c.
    {
        return false;
    }
OnModalResult()
bool UIScriptedWindow::OnModalResult (Widget w, int x, int y, int code, int result) inline private
Definition at line 85 of file uiscriptedwindow.c.
    {
        return false;
    }
OnMouseButtonDown()
bool UIScriptedWindow::OnMouseButtonDown (Widget w, int x, int y, int button) inline private
Definition at line 125 of file uiscriptedwindow.c.
    {
        return false;
    }
OnMouseButtonUp()
bool UIScriptedWindow::OnMouseButtonUp (Widget w, int x, int y, int button) inline private
Definition at line 130 of file uiscriptedwindow.c.
    {
        return false;
    }
OnMouseEnter()
bool UIScriptedWindow::OnMouseEnter (Widget w, int x, int y) inline private
Definition at line 115 of file uiscriptedwindow.c.
    {
        return false;
    }
OnMouseLeave()
bool UIScriptedWindow::OnMouseLeave (Widget w, Widget enterW, int x, int y) inline private
Definition at line 120 of file uiscriptedwindow.c.
    {
        return false;
    }
OnMouseWheel()
bool UIScriptedWindow::OnMouseWheel (Widget w, int x, int y, int wheel) inline private
Definition at line 135 of file uiscriptedwindow.c.
    {
        return false;
    }
OnSelect()
bool UIScriptedWindow::OnSelect (Widget w, int x, int y) inline private
Definition at line 95 of file uiscriptedwindow.c.
    {
        return false;
    }
RemoveFromActiveWindows()
static void UIScriptedWindow::RemoveFromActiveWindows (int id) inline static private
Definition at line 19 of file uiscriptedwindow.c.
    {
        if ( m_ActiveWindows )
        {
            m_ActiveWindows.Remove( id );
        }
    }
References m_ActiveWindows.
Referenced by UIManager::CloseWindow().
ShowWindow()
void UIScriptedWindow::ShowWindow () inline private
Definition at line 64 of file uiscriptedwindow.c.
    {
        GetWidgetRoot().Show( true );
    }
References GetWidgetRoot().
Member Data Documentation
m_ActiveWindows
ref map<int, UIScriptedWindow> UIScriptedWindow::m_ActiveWindows static private
Definition at line 7 of file uiscriptedwindow.c.
Referenced by AddToActiveWindows(), GetActiveWindows(), GetWindow(), and RemoveFromActiveWindows().
m_Id
int UIScriptedWindow::m_Id private
Definition at line 4 of file uiscriptedwindow.c.
Referenced by CloseWindow(), and UIScriptedWindow().
m_ListMissionsNames
ref TStringArray UIScriptedWindow::m_ListMissionsNames private
Definition at line 8 of file missionloader.c.
m_PathToMissions
string UIScriptedWindow::m_PathToMissions private
Definition at line 3 of file missionloader.c.
m_WgtBtnMsnClose
ButtonWidget UIScriptedWindow::m_WgtBtnMsnClose private
Definition at line 6 of file missionloader.c.
m_WgtBtnMsnPlay
ButtonWidget UIScriptedWindow::m_WgtBtnMsnPlay private
Definition at line 5 of file missionloader.c.
m_WgtLstMsnList
TextListboxWidget UIScriptedWindow::m_WgtLstMsnList private
Definition at line 4 of file missionloader.c.
m_WgtRoot
Widget UIScriptedWindow::m_WgtRoot private
Definition at line 3 of file uiscriptedwindow.c.
Referenced by GetWidgetRoot(), and Init().