DayzKode: ActionFoldEntityToSlot Class Reference
ActionFoldEntityToSlot Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override void CreateConditionComponents ()
override bool HasTarget ()
override void OnExecuteClient (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Private Attributes
int m_SlotID = InventorySlots.INVALID
Detailed Description
Definition at line 1 of file actionfoldentitytoslot.c.
Member Function Documentation
ActionCondition()
override bool ActionFoldEntityToSlot::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 13 of file actionfoldentitytoslot.c.
    {
        EntityAI att = player.GetInventory().FindAttachment(m_SlotID);
        if ( item && att == null )
            return true;
        return false;
    }
References m_SlotID.
ActionConditionContinue()
override bool ActionFoldEntityToSlot::ActionConditionContinue (ActionData action_data) inline private
Definition at line 21 of file actionfoldentitytoslot.c.
{ return true; }
CreateConditionComponents()
override void ActionFoldEntityToSlot::CreateConditionComponents () inline private
Definition at line 5 of file actionfoldentitytoslot.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionFoldEntityToSlot::HasTarget () inline private
Definition at line 11 of file actionfoldentitytoslot.c.
{ return false; }
OnExecuteClient()
override void ActionFoldEntityToSlot::OnExecuteClient (ActionData action_data) inline private
Definition at line 23 of file actionfoldentitytoslot.c.
    {
        ClearInventoryReservationEx(action_data);
    }
References ClearInventoryReservationEx().
OnExecuteServer()
override void ActionFoldEntityToSlot::OnExecuteServer (ActionData action_data) inline private
Definition at line 28 of file actionfoldentitytoslot.c.
    {
        if ( !GetGame().IsMultiplayer() )
            ClearInventoryReservationEx(action_data);
        ItemBase old_item = action_data.m_MainItem;
        if (old_item.ConfigIsExisting("ChangeIntoOnAttach"))
        {
            string slot_name = InventorySlots.GetSlotName(m_SlotID);
            string str = old_item.ChangeIntoOnAttach(slot_name);
            if (str != "")
            {
                FoldBandanaToSlotLambda lambda = new FoldBandanaToSlotLambda(action_data.m_MainItem, str, action_data.m_Player, m_SlotID);
                action_data.m_Player.ServerReplaceItemInHandsWithNewElsewhere(lambda);
            }
        }
    }
References ClearInventoryReservationEx(), GetGame(), InventorySlots::GetSlotName(), ActionData::m_MainItem, ActionData::m_Player, and m_SlotID.
Member Data Documentation
m_SlotID
int ActionFoldEntityToSlot::m_SlotID = InventorySlots.INVALID private
Definition at line 3 of file actionfoldentitytoslot.c.
Referenced by ActionCondition(), ActionFoldBandanaToHead::ActionFoldBandanaToHead(), ActionFoldBandanaToMask::ActionFoldBandanaToMask(), and OnExecuteServer().