DayzKode: ActionStartEngine Class Reference
ActionStartEngine Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionStartEngine ()
DEPRECATED.
override bool CanBeUsedInVehicle ()
override void CreateConditionComponents ()
override void OnFinishProgressServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
bool m_BatteryCon = false
DEPRECATED.
bool m_BeltCon = false
DEPRECATED.
bool m_FuelCon = false
DEPRECATED.
bool m_SparkCon = false
DEPRECATED.
private const float ROUGH_SPECIALTY_WEIGHT = 0.5
Static Private Attributes
static const float MINIMUM_BATTERY_ENERGY = 5.0
Detailed Description
Definition at line 9 of file actionstartengine.c.
Constructor & Destructor Documentation
ActionStartEngine()
void ActionStartEngine::ActionStartEngine () inline private
DEPRECATED.
Definition at line 19 of file actionstartengine.c.
    {
        m_CallbackClass     = ActionStartCarCB;
        m_CommandUID        = DayZPlayerConstants.CMD_ACTIONMOD_STARTENGINE;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_ALL;
        m_SpecialtyWeight   = ROUGH_SPECIALTY_WEIGHT;
        m_LockTargetOnUse   = false;
        m_Text = "#start_the_car";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and ROUGH_SPECIALTY_WEIGHT.
Member Function Documentation
ActionCondition()
override bool ActionStartEngine::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 35 of file actionstartengine.c.
    {
        HumanCommandVehicle vehCommand = player.GetCommand_Vehicle();
        if (vehCommand)
        {
            Transport trans = vehCommand.GetTransport();
            if (trans)
            {
                Car car;
                if (Class.CastTo(car, trans) && !car.EngineIsOn())
                {
                    if (car.GetHealthLevel("Engine") >= GameConstants.STATE_RUINED)
                    {
                        return false;
                    }
                    if (car.CrewMemberIndex(player) == DayZPlayerConstants.VEHICLESEAT_DRIVER)
                    {
                        return true;
                    }
                }
            }
        }
        return false;
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and GameConstants::STATE_RUINED.
CanBeUsedInVehicle()
override bool ActionStartEngine::CanBeUsedInVehicle () inline private
Definition at line 96 of file actionstartengine.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionStartEngine::CreateConditionComponents () inline private
Definition at line 29 of file actionstartengine.c.
    {
        m_ConditionTarget   = new CCTNone;
        m_ConditionItem     = new CCINone;
    }
References m_ConditionItem, and m_ConditionTarget.
OnFinishProgressServer()
override void ActionStartEngine::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 62 of file actionstartengine.c.
    {
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if (vehCommand)
        {
            Transport trans = vehCommand.GetTransport();
            if (trans)
            {
                CarScript car;
                if (Class.CastTo(car, trans))
                {
                    car.EngineStart();
                }
            }
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.
OnStartServer()
override void ActionStartEngine::OnStartServer (ActionData action_data) inline private
Definition at line 79 of file actionstartengine.c.
    {
        HumanCommandVehicle vehCommand = action_data.m_Player.GetCommand_Vehicle();
        if (vehCommand)
        {
            Transport trans = vehCommand.GetTransport();
            if (trans)
            {
                CarScript car;
                if (Class.CastTo(car, trans))
                {
                    car.OnBeforeEngineStart();
                }
            }
        }
    }
References Class::CastTo(), HumanCommandVehicle::GetTransport(), and ActionData::m_Player.
Member Data Documentation
m_BatteryCon
bool ActionStartEngine::m_BatteryCon = false private
DEPRECATED.
Definition at line 14 of file actionstartengine.c.
m_BeltCon
bool ActionStartEngine::m_BeltCon = false private
DEPRECATED.
Definition at line 16 of file actionstartengine.c.
m_FuelCon
bool ActionStartEngine::m_FuelCon = false private
DEPRECATED.
Definition at line 17 of file actionstartengine.c.
m_SparkCon
bool ActionStartEngine::m_SparkCon = false private
DEPRECATED.
Definition at line 15 of file actionstartengine.c.
MINIMUM_BATTERY_ENERGY
const float ActionStartEngine::MINIMUM_BATTERY_ENERGY = 5.0 static private
Definition at line 12 of file actionstartengine.c.
ROUGH_SPECIALTY_WEIGHT
private const float ActionStartEngine::ROUGH_SPECIALTY_WEIGHT = 0.5 private
Definition at line 11 of file actionstartengine.c.
Referenced by ActionStartEngine().