DayzKode: UniversalTemperatureSource Class Reference
UniversalTemperatureSource Class Reference
original Timer deletes m_params which is unwanted
Private Member Functions
override void OnTimer ()
void SetParams (Param params)
override void Stop ()
Detailed Description
original Timer deletes m_params which is unwanted
Definition at line 27 of file universaltemperaturesource.c.
Member Function Documentation
OnTimer()
override void UniversalTemperatureSource::OnTimer () inline private
Definition at line 29 of file universaltemperaturesource.c.
    {
        if (m_params)
        {
            GetGame().GameScript.CallFunctionParams(m_target, m_function, null, m_params);
        }
        else
        {
            GetGame().GameScript.CallFunction(m_target, m_function, null, 0);
        }
    }
References ScriptModule::CallFunction(), ScriptModule::CallFunctionParams(), CGame::GameScript, and GetGame().
SetParams()
void UniversalTemperatureSource::SetParams (Param params) inline private
Definition at line 47 of file universaltemperaturesource.c.
    {
        m_params = params;
    }
Stop()
override void UniversalTemperatureSource::Stop () inline private
Definition at line 41 of file universaltemperaturesource.c.
    {
        SetRunning(false);
        m_time = 0;
    }
References m_time, and SetRunning().