DayzKode: ActionUngagSelf Class Reference
ActionUngagSelf Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionUngagSelf ()
override void CreateConditionComponents ()
override bool HasTarget ()
bool IsWearingGag (PlayerBase player)
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 1 of file actionungagself.c.
Constructor & Destructor Documentation
ActionUngagSelf()
void ActionUngagSelf::ActionUngagSelf () inline private
Definition at line 3 of file actionungagself.c.
    {
        m_CallbackClass = ActionUncoverHeadSelfCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_COVERHEAD_SELF;
        //m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT | DayZPlayerConstants.STANCEMASK_CROUCH;
        m_Text = "#ungag";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionUngagSelf::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 23 of file actionungagself.c.
    {
        if ( IsWearingGag(player) && null == player.GetHumanInventory().GetEntityInHands())
            return true;
        return false;
    }
References IsWearingGag().
CreateConditionComponents()
override void ActionUngagSelf::CreateConditionComponents () inline private
Definition at line 12 of file actionungagself.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasTarget()
override bool ActionUngagSelf::HasTarget () inline private
Definition at line 18 of file actionungagself.c.
    {
        return false;
    }
IsWearingGag()
bool ActionUngagSelf::IsWearingGag (PlayerBase player) inline private
Definition at line 44 of file actionungagself.c.
    {
        EntityAI attachment;
        Class.CastTo(attachment, player.GetInventory().FindAttachment(InventorySlots.MASK));
        if ( attachment && attachment.GetType() == "MouthRag" )
        {
            return true;
        }
        return false;
    }
References Class::CastTo().
Referenced by ActionCondition().
OnFinishProgressServer()
override void ActionUngagSelf::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 31 of file actionungagself.c.
    {
        EntityAI attachment;
        Class.CastTo(attachment, action_data.m_Player.GetInventory().FindAttachment(InventorySlots.MASK));
        if ( attachment && attachment.GetType() == "MouthRag" )
        {
            UngagSelfLambda lamb = new UngagSelfLambda(attachment, "Rag", action_data.m_Player);
            lamb.SetTransferParams(true, true, true, false, 1);
            action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lamb);
        }
        //action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References Class::CastTo(), and ActionData::m_Player.