DayzKode: Roadflare Class Reference
Roadflare Class Reference
Private Member Functions
override bool CanIgniteItem (EntityAI ignite_target=NULL)
override bool CanPutInCargo (EntityAI parent)
void DestroyAllParticles ()
void DestroyParticle (Particle p)
void DestroyParticleEx (out Particle p)
override void EEDelete (EntityAI parent)
override void OnActivatedByItem (notnull ItemBase item)
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
void Roadflare ()
override void SetActions ()
void SetBurningState (int state_number)
void SetBurningStateSynchronized (int state_number)
void SetModelState (int enum_state)
void StopSmoking ()
void UpdateActiveParticles ()
void UpdateModelSelections ()
Private Attributes
protected EffectSound m_BurningSound
private int m_BurningState = RoadflareBurningState.NOT_BURNING
ref Timer m_FinalSmokeTimer
protected EffectSound m_IgniteSound
RoadflareLight m_Light
private int m_ModelState = RoadflareModelStates.DEFAULT
ref NoiseParams m_NoisePar
private float m_NoiseTimer
protected Particle m_ParFinalFire
protected Particle m_ParInitialFire
protected Particle m_ParJustSmoke
protected Particle m_ParMainFire
Static Private Attributes
static const string BURNING_MATERIAL = "dz\\gear\\consumables\\data\\road_flare_on.rvmat"
static protected const int BURNING_NOISE_RANGE = 30
static protected const string BURNING_SOUND = "roadflareLoop_SoundSet"
static const string BURNING_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_e_co.paa"
static const string DEFAULT_MATERIAL = "dz\\gear\\consumables\\data\\road_flare.rvmat"
static const string DEFAULT_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_co.paa"
static const string EXTINGUISHED_TIP = "Burned_out"
static protected const int FINAL_BURNING_STATE_TIME = 60
static const string FLARE_CAP = "Flare_cap"
static protected const string IGNITE_SOUND = "roadflareTurnOn_SoundSet"
static const string IGNITED_TIP = "Burning"
static protected const int INITIAL_BURNING_STATE_TIME = 5
static protected vector m_FlameLocalPos = "0 0.285 0"
static protected int PARTICLE_FINAL_FIRE = ParticleList.ROADFLARE_BURNING_ENDING
static protected int PARTICLE_FINAL_SMOKE = ParticleList.ROADFLARE_BURNING_SMOKE
static protected int PARTICLE_INIT_FIRE = ParticleList.ROADFLARE_BURNING_INIT
static protected int PARTICLE_MAIN_FIRE = ParticleList.ROADFLARE_BURNING_MAIN
static const int SELECTION_All = 3
static const int SELECTION_Burned_out = 1
static const int SELECTION_Burning = 0
static const int SELECTION_Pristine = 2
static const string STANDS_FOLDED = "Sticks_Flare_Folded"
static const string STANDS_UNFOLDED = "Sticks_Flare_Unfolded"
static const string UNIGNITED_TIP = "Pristine"
Detailed Description
Definition at line 24 of file roadflare.c.
Constructor & Destructor Documentation
Roadflare()
void Roadflare::Roadflare () inline private
Definition at line 82 of file roadflare.c.
    {
        RegisterNetSyncVariableInt("m_BurningState");
    }
Member Function Documentation
CanIgniteItem()
override bool Roadflare::CanIgniteItem (EntityAI ignite_target = NULL) inline private
Definition at line 464 of file roadflare.c.
    {
        return GetCompEM().IsWorking();
    }
CanPutInCargo()
override bool Roadflare::CanPutInCargo (EntityAI parent) inline private
Definition at line 434 of file roadflare.c.
    {
        if ( !super.CanPutInCargo(parent) )
            return false;
        if ( parent && parent.IsInherited( FireplaceBase ) )
            return true;
        if ( m_BurningState != RoadflareBurningState.NOT_BURNING )
            return false;
        return true;
    }
References m_BurningState.
DestroyAllParticles()
void Roadflare::DestroyAllParticles () inline private
Definition at line 400 of file roadflare.c.
    {
        DestroyParticleEx(m_ParInitialFire);
        DestroyParticleEx(m_ParMainFire);
        DestroyParticleEx(m_ParFinalFire);
        DestroyParticleEx(m_ParJustSmoke);
    }
References DestroyParticleEx(), m_ParFinalFire, m_ParInitialFire, m_ParJustSmoke, and m_ParMainFire.
Referenced by EEDelete(), and UpdateActiveParticles().
DestroyParticle()
void Roadflare::DestroyParticle (Particle p) inline private
Definition at line 384 of file roadflare.c.
    {
        if (p)
        {
            p.SetWiggle(0,0);
            p.Stop();
        }
    }
References Particle::SetWiggle(), and Particle::Stop().
Referenced by DestroyParticleEx().
DestroyParticleEx()
void Roadflare::DestroyParticleEx (out Particle p) inline private
Definition at line 393 of file roadflare.c.
    {
        DestroyParticle(p);
        p = null;
    }
References DestroyParticle().
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
EEDelete()
override void Roadflare::EEDelete (EntityAI parent) inline private
Definition at line 94 of file roadflare.c.
    {
        super.EEDelete(parent);
        if ( GetGame() )
        {
            SEffectManager.DestroyEffect( m_BurningSound );
            SEffectManager.DestroyEffect( m_IgniteSound );
            delete m_FinalSmokeTimer;
        }
        DestroyAllParticles();
        if (m_Light)
            m_Light.FadeOut(0);
    }
References DestroyAllParticles(), SEffectManager::DestroyEffect(), GetGame(), m_BurningSound, m_FinalSmokeTimer, m_IgniteSound, and m_Light.
OnActivatedByItem()
override void Roadflare::OnActivatedByItem (notnull ItemBase item) inline private
Definition at line 456 of file roadflare.c.
    {
        if (item.IsInherited(TripwireTrap))
        {
            GetCompEM().SwitchOn();
        }
    }
References TripwireTrap().
OnInventoryEnter()
override void Roadflare::OnInventoryEnter (Man player) inline private
Definition at line 448 of file roadflare.c.
    {
        super.OnInventoryEnter(player);
        HideSelection(STANDS_UNFOLDED);
        ShowSelection(STANDS_FOLDED);
    }
References STANDS_FOLDED, and STANDS_UNFOLDED.
OnInventoryExit()
override void Roadflare::OnInventoryExit (Man player) inline private
Definition at line 416 of file roadflare.c.
    {
        super.OnInventoryExit(player);
        if (m_BurningState != RoadflareBurningState.NOT_BURNING)
        {
            HideSelection(STANDS_FOLDED);
            ShowSelection(STANDS_UNFOLDED);
            if (player)
            {
                vector ori_rotate = player.GetOrientation();
                ori_rotate = ori_rotate + Vector(180, 32, 0);
                SetOrientation(ori_rotate);
            }
        }
    }
References m_BurningState, SetOrientation(), STANDS_FOLDED, STANDS_UNFOLDED, and Vector().
OnStoreLoad()
override bool Roadflare::OnStoreLoad (ParamsReadContext ctx, int version) inline private
Definition at line 118 of file roadflare.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        int state;
        if ( !ctx.Read(state) )
            state = RoadflareModelStates.DEFAULT;
        SetModelState(state);
        return true;
    }
References Serializer::Read(), and SetModelState().
OnStoreSave()
override void Roadflare::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 111 of file roadflare.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write( m_ModelState );
    }
References m_ModelState, and Serializer::Write().
OnVariablesSynchronized()
override void Roadflare::OnVariablesSynchronized () inline private
Definition at line 469 of file roadflare.c.
    {
        super.OnVariablesSynchronized();
        UpdateActiveParticles();
    }
References UpdateActiveParticles().
OnWork()
override void Roadflare::OnWork (float consumed_energy) inline private
Definition at line 236 of file roadflare.c.
    {
        if ( GetGame().IsServer() )
        {
            float burning_time = GetCompEM().GetEnergyMax() - GetCompEM().GetEnergy();
            // Update burning states
            if (m_BurningState == RoadflareBurningState.INITIAL_BURN)
            {
                if (burning_time >= INITIAL_BURNING_STATE_TIME)
                {
                    SetBurningStateSynchronized(RoadflareBurningState.MAIN_BURN);
                }
            }
            else if ( m_BurningState == RoadflareBurningState.MAIN_BURN )
            {
                /*if ( GetGame().GetWorld().IsNight() )
                {
                    NoiseSystem noise = GetGame().GetNoiseSystem();
                    if ( noise )
                    {
                        noise.AddNoisePos( this, GetPosition(), m_NoisePar);
                    }
                }*/
                if ( burning_time >= GetCompEM().GetEnergyMax() - FINAL_BURNING_STATE_TIME )
                {
                    SetBurningStateSynchronized(RoadflareBurningState.FINAL_BURN);
                }
            }
            // Burn containers of this roadflare. This might be removed if lit roadflare can't be put into inventory.
            /*EntityAI container_EAI = GetHierarchyParent();
            if ( container_EAI  &&  container_EAI.IsInherited(ItemBase)  &&  !container_EAI.IsInherited(TripwireTrap) )
            {
                ItemBase container_IB = ItemBase.Cast( container_EAI );
                int c_size = container_IB.GetItemSize();
                if (c_size == 0)
                    c_size = 1;
                container_IB.AddHealth("","",-10/c_size);
            }*/
        }
        UpdateActiveParticles();
    }
References FINAL_BURNING_STATE_TIME, GetGame(), INITIAL_BURNING_STATE_TIME, m_BurningState, SetBurningStateSynchronized(), and UpdateActiveParticles().
OnWorkStart()
override void Roadflare::OnWorkStart () inline private
Definition at line 190 of file roadflare.c.
    {
        if ( !GetGame().IsServer()  ||  !GetGame().IsMultiplayer() )
        {
            PlaySoundSetLoop( m_BurningSound, BURNING_SOUND, 0.5, 0 );
            PlaySoundSet( m_IgniteSound, IGNITE_SOUND, 0, 0 );
            m_Light = RoadflareLight.Cast(  ScriptedLightBase.CreateLight( RoadflareLight, Vector(0,0,0) )  );
            m_Light.AttachOnMemoryPoint( this, m_Light.m_MemoryPoint );
        }
        if ( GetGame().IsServer() )
        {
            /*m_NoisePar = new NoiseParams();
            m_NoisePar.LoadFromPath("cfgVehicles Roadflare NoiseRoadFlare");
            if ( GetGame().GetWorld().IsNight() )
            {
                NoiseSystem noise = GetGame().GetNoiseSystem();
                if ( noise )
                {
                    noise.AddNoisePos( this, GetPosition(), m_NoisePar );
                }
            }*/
        }
        SetBurningState(RoadflareBurningState.INITIAL_BURN);
        SetModelState( RoadflareModelStates.UNCAPPED_IGNITED );
    }
References BURNING_SOUND, GetGame(), IGNITE_SOUND, m_BurningSound, m_IgniteSound, m_Light, PlaySoundSet(), PlaySoundSetLoop(), SetBurningState(), SetModelState(), and Vector().
OnWorkStop()
override void Roadflare::OnWorkStop () inline private
Definition at line 286 of file roadflare.c.
    {
        if ( GetGame().IsMissionMainMenu() ) // This is singleplayer main menu so no synchronization here!
        {
            SetBurningState(RoadflareBurningState.NOT_BURNING);
            UpdateActiveParticles();
        }
        else
        {
            if ( GetGame().IsServer() )
            {
                //Safeguard if item is turned off by another event than running out of energy
                if (GetCompEM().GetEnergy() > 0)
                {
                    if (m_Light)
                    {
                        m_Light.FadeOut();
                    }
                    SetBurningState(RoadflareBurningState.NOT_BURNING);
                    return;
                }
                SetBurningStateSynchronized(RoadflareBurningState.SMOKE_ONLY);
                SetHealth("","",0);
            }
            UpdateActiveParticles();
            m_FinalSmokeTimer = new Timer( CALL_CATEGORY_SYSTEM );
            m_FinalSmokeTimer.Run(60, this, "StopSmoking", NULL, false);
        }
        if ( m_BurningSound )
            StopSoundSet( m_BurningSound );
        if (m_Light)
            m_Light.FadeOut();
        SetModelState( RoadflareModelStates.UNCAPPED_BURNED_OUT );
    }
References CALL_CATEGORY_SYSTEM, GetEnergy(), GetGame(), m_BurningSound, m_FinalSmokeTimer, m_Light, SetBurningState(), SetBurningStateSynchronized(), SetHealth(), SetModelState(), StopSoundSet(), and UpdateActiveParticles().
SetActions()
override void Roadflare::SetActions () inline private
Definition at line 476 of file roadflare.c.
    {
        super.SetActions();
        AddAction(ActionAttach);
        AddAction(ActionDetach);
        AddAction(ActionLightItemOnFire);
        AddAction(ActionTurnOnWhileInHands);
    }
References ActionAttach(), ActionDetach(), ActionLightItemOnFire(), and AddAction().
SetBurningState()
void Roadflare::SetBurningState (int state_number) inline private
Definition at line 220 of file roadflare.c.
    {
        m_BurningState = state_number;
    }
References m_BurningState.
Referenced by OnWorkStart(), and OnWorkStop().
SetBurningStateSynchronized()
void Roadflare::SetBurningStateSynchronized (int state_number) inline private
Definition at line 226 of file roadflare.c.
    {
        if ( GetGame().IsServer() )
        {
            m_BurningState = state_number;
            SetSynchDirty();
        }
    }
References GetGame(), and m_BurningState.
Referenced by OnWork(), OnWorkStop(), and StopSmoking().
SetModelState()
void Roadflare::SetModelState (int enum_state) inline private
Definition at line 88 of file roadflare.c.
    {
        m_ModelState = enum_state;
        UpdateModelSelections();
    }
References m_ModelState, and UpdateModelSelections().
Referenced by ActionTurnOnWhileInHands::OnStartClient(), ActionTurnOnWhileInHands::OnStartServer(), OnStoreLoad(), OnWorkStart(), and OnWorkStop().
StopSmoking()
void Roadflare::StopSmoking () inline private
Definition at line 409 of file roadflare.c.
    {
        SetBurningStateSynchronized(RoadflareBurningState.NOT_BURNING);
        UpdateActiveParticles();
    }
References SetBurningStateSynchronized(), and UpdateActiveParticles().
UpdateActiveParticles()
void Roadflare::UpdateActiveParticles () inline private
Definition at line 327 of file roadflare.c.
    {
        if ( GetGame().IsDedicatedServer() )
            return;
        switch (m_BurningState)
        {
            case RoadflareBurningState.NOT_BURNING:
                DestroyAllParticles();
                break;
            case RoadflareBurningState.INITIAL_BURN:
                if (!m_ParInitialFire)
                {
                    DestroyAllParticles();
                    m_ParInitialFire = ParticleManager.GetInstance().PlayOnObject( PARTICLE_INIT_FIRE, this, m_FlameLocalPos);
                    m_ParInitialFire.SetWiggle( 10, 0.3 );
                }
                break;
            case RoadflareBurningState.MAIN_BURN:
                if (!m_ParMainFire)
                {
                    m_ParMainFire = ParticleManager.GetInstance().PlayOnObject( PARTICLE_MAIN_FIRE, this, m_FlameLocalPos);
                    m_ParMainFire.SetWiggle( 7, 0.3 );
                }
                DestroyParticleEx(m_ParInitialFire);
                break;
            case RoadflareBurningState.FINAL_BURN:
                if (!m_ParFinalFire)
                {
                    DestroyAllParticles();
                    m_ParFinalFire = ParticleManager.GetInstance().PlayOnObject( PARTICLE_FINAL_FIRE, this, m_FlameLocalPos);
                    m_ParFinalFire.SetWiggle( 4, 0.3 );
                }
                break;
            case RoadflareBurningState.SMOKE_ONLY:
                if (!m_ParJustSmoke)
                {
                    DestroyAllParticles();
                    m_ParJustSmoke = ParticleManager.GetInstance().PlayOnObject( PARTICLE_FINAL_SMOKE, this, m_FlameLocalPos);
                    m_ParJustSmoke.SetWiggle( 2, 0.3 );
                }
                break;
        }
    }
References DestroyAllParticles(), DestroyParticleEx(), GetGame(), m_BurningState, m_FlameLocalPos, m_ParFinalFire, m_ParInitialFire, m_ParJustSmoke, m_ParMainFire, PARTICLE_FINAL_FIRE, PARTICLE_FINAL_SMOKE, PARTICLE_INIT_FIRE, PARTICLE_MAIN_FIRE, ParticleManager(), and Particle::SetWiggle().
Referenced by OnVariablesSynchronized(), OnWork(), OnWorkStop(), and StopSmoking().
UpdateModelSelections()
void Roadflare::UpdateModelSelections () inline private
Definition at line 132 of file roadflare.c.
    {
        switch (m_ModelState)
        {
            case RoadflareModelStates.DEFAULT:
                ShowSelection(FLARE_CAP);
                ShowSelection(UNIGNITED_TIP);
                HideSelection(IGNITED_TIP);
                HideSelection(EXTINGUISHED_TIP);
                SetObjectTexture(SELECTION_Pristine, DEFAULT_TEXTURE);
                SetObjectMaterial(SELECTION_Pristine, DEFAULT_MATERIAL);
                break;
            case RoadflareModelStates.UNCAPPED_UNIGNITED:
                ShowSelection(UNIGNITED_TIP);
                HideSelection(FLARE_CAP);
                HideSelection(IGNITED_TIP);
                HideSelection(EXTINGUISHED_TIP);
                SetObjectTexture(SELECTION_Pristine, DEFAULT_TEXTURE);
                SetObjectMaterial(SELECTION_Pristine, DEFAULT_MATERIAL);
                break;
            case RoadflareModelStates.UNCAPPED_IGNITED:
                ShowSelection(IGNITED_TIP);
                HideSelection(UNIGNITED_TIP);
                HideSelection(FLARE_CAP);
                HideSelection(EXTINGUISHED_TIP);
                // No texture/material change here because the model already contains them
                break;
            case RoadflareModelStates.UNCAPPED_BURNED_OUT:
                ShowSelection(EXTINGUISHED_TIP);
                HideSelection(UNIGNITED_TIP);
                HideSelection(FLARE_CAP);
                HideSelection(IGNITED_TIP);
                SetObjectTexture(SELECTION_Burned_out, DEFAULT_TEXTURE);
                SetObjectMaterial(SELECTION_Burned_out, DEFAULT_MATERIAL);
                break;
        }
    }
References DEFAULT_MATERIAL, DEFAULT_TEXTURE, EXTINGUISHED_TIP, FLARE_CAP, IGNITED_TIP, m_ModelState, SELECTION_Burned_out, SELECTION_Pristine, and UNIGNITED_TIP.
Referenced by SetModelState().
Member Data Documentation
BURNING_MATERIAL
const string Roadflare::BURNING_MATERIAL = "dz\\gear\\consumables\\data\\road_flare_on.rvmat" static private
Definition at line 76 of file roadflare.c.
BURNING_NOISE_RANGE
protected const int Roadflare::BURNING_NOISE_RANGE = 30 static private
Definition at line 51 of file roadflare.c.
BURNING_SOUND
protected const string Roadflare::BURNING_SOUND = "roadflareLoop_SoundSet" static private
Definition at line 49 of file roadflare.c.
Referenced by OnWorkStart().
BURNING_TEXTURE
const string Roadflare::BURNING_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_e_co.paa" static private
Definition at line 73 of file roadflare.c.
DEFAULT_MATERIAL
const string Roadflare::DEFAULT_MATERIAL = "dz\\gear\\consumables\\data\\road_flare.rvmat" static private
Definition at line 75 of file roadflare.c.
Referenced by UpdateModelSelections().
DEFAULT_TEXTURE
const string Roadflare::DEFAULT_TEXTURE = "dz\\gear\\consumables\\data\\road_flare_co.paa" static private
Definition at line 72 of file roadflare.c.
Referenced by UpdateModelSelections().
EXTINGUISHED_TIP
const string Roadflare::EXTINGUISHED_TIP = "Burned_out" static private
Definition at line 65 of file roadflare.c.
Referenced by UpdateModelSelections().
FINAL_BURNING_STATE_TIME
protected const int Roadflare::FINAL_BURNING_STATE_TIME = 60 static private
Definition at line 28 of file roadflare.c.
Referenced by OnWork().
FLARE_CAP
const string Roadflare::FLARE_CAP = "Flare_cap" static private
Definition at line 62 of file roadflare.c.
Referenced by UpdateModelSelections().
IGNITE_SOUND
protected const string Roadflare::IGNITE_SOUND = "roadflareTurnOn_SoundSet" static private
Definition at line 50 of file roadflare.c.
Referenced by OnWorkStart().
IGNITED_TIP
const string Roadflare::IGNITED_TIP = "Burning" static private
Definition at line 64 of file roadflare.c.
Referenced by UpdateModelSelections().
INITIAL_BURNING_STATE_TIME
protected const int Roadflare::INITIAL_BURNING_STATE_TIME = 5 static private
Definition at line 27 of file roadflare.c.
Referenced by OnWork().
m_BurningSound
protected EffectSound Roadflare::m_BurningSound private
Definition at line 47 of file roadflare.c.
Referenced by EEDelete(), OnWorkStart(), and OnWorkStop().
m_BurningState
private int Roadflare::m_BurningState = RoadflareBurningState.NOT_BURNING private
Definition at line 30 of file roadflare.c.
Referenced by CanPutInCargo(), OnInventoryExit(), OnWork(), SetBurningState(), SetBurningStateSynchronized(), and UpdateActiveParticles().
m_FinalSmokeTimer
ref Timer Roadflare::m_FinalSmokeTimer private
Definition at line 54 of file roadflare.c.
Referenced by EEDelete(), and OnWorkStop().
m_FlameLocalPos
protected vector Roadflare::m_FlameLocalPos = "0 0.285 0" static private
Definition at line 29 of file roadflare.c.
Referenced by UpdateActiveParticles().
m_IgniteSound
protected EffectSound Roadflare::m_IgniteSound private
Definition at line 48 of file roadflare.c.
Referenced by EEDelete(), and OnWorkStart().
m_Light
RoadflareLight Roadflare::m_Light private
Definition at line 33 of file roadflare.c.
Referenced by EEDelete(), OnWorkStart(), and OnWorkStop().
m_ModelState
private int Roadflare::m_ModelState = RoadflareModelStates.DEFAULT private
Definition at line 57 of file roadflare.c.
Referenced by OnStoreSave(), SetModelState(), and UpdateModelSelections().
m_NoisePar
ref NoiseParams Roadflare::m_NoisePar private
Definition at line 79 of file roadflare.c.
m_NoiseTimer
private float Roadflare::m_NoiseTimer private
Definition at line 80 of file roadflare.c.
m_ParFinalFire
protected Particle Roadflare::m_ParFinalFire private
Definition at line 38 of file roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParInitialFire
protected Particle Roadflare::m_ParInitialFire private
Definition at line 36 of file roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParJustSmoke
protected Particle Roadflare::m_ParJustSmoke private
Definition at line 39 of file roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
m_ParMainFire
protected Particle Roadflare::m_ParMainFire private
Definition at line 37 of file roadflare.c.
Referenced by DestroyAllParticles(), and UpdateActiveParticles().
PARTICLE_FINAL_FIRE
protected int Roadflare::PARTICLE_FINAL_FIRE = ParticleList.ROADFLARE_BURNING_ENDING static private
Definition at line 43 of file roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_FINAL_SMOKE
protected int Roadflare::PARTICLE_FINAL_SMOKE = ParticleList.ROADFLARE_BURNING_SMOKE static private
Definition at line 44 of file roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_INIT_FIRE
protected int Roadflare::PARTICLE_INIT_FIRE = ParticleList.ROADFLARE_BURNING_INIT static private
Definition at line 41 of file roadflare.c.
Referenced by UpdateActiveParticles().
PARTICLE_MAIN_FIRE
protected int Roadflare::PARTICLE_MAIN_FIRE = ParticleList.ROADFLARE_BURNING_MAIN static private
Definition at line 42 of file roadflare.c.
Referenced by UpdateActiveParticles().
SELECTION_All
const int Roadflare::SELECTION_All = 3 static private
Definition at line 70 of file roadflare.c.
SELECTION_Burned_out
const int Roadflare::SELECTION_Burned_out = 1 static private
Definition at line 68 of file roadflare.c.
Referenced by UpdateModelSelections().
SELECTION_Burning
const int Roadflare::SELECTION_Burning = 0 static private
Definition at line 67 of file roadflare.c.
SELECTION_Pristine
const int Roadflare::SELECTION_Pristine = 2 static private
Definition at line 69 of file roadflare.c.
Referenced by UpdateModelSelections().
STANDS_FOLDED
const string Roadflare::STANDS_FOLDED = "Sticks_Flare_Folded" static private
Definition at line 60 of file roadflare.c.
Referenced by OnInventoryEnter(), and OnInventoryExit().
STANDS_UNFOLDED
const string Roadflare::STANDS_UNFOLDED = "Sticks_Flare_Unfolded" static private
Definition at line 61 of file roadflare.c.
Referenced by OnInventoryEnter(), and OnInventoryExit().
UNIGNITED_TIP
const string Roadflare::UNIGNITED_TIP = "Pristine" static private
Definition at line 63 of file roadflare.c.
Referenced by UpdateModelSelections().