DayzKode: ActionDropItemSimple Class Reference
ActionDropItemSimple Class Reference
Private Member Functions
void ActionDropItemSimple ()
override bool CanBeUsedOnBack ()
override bool IsInstant ()
override bool MainItemAlwaysInHands ()
override void PhysicalDropItem (ActionData action_data)
override void Start (ActionData action_data)
Detailed Description
Definition at line 1 of file actiondropitemsimple.c.
Constructor & Destructor Documentation
ActionDropItemSimple()
void ActionDropItemSimple::ActionDropItemSimple () inline private
Definition at line 5 of file actiondropitemsimple.c.
    {
    }
Member Function Documentation
CanBeUsedOnBack()
override bool ActionDropItemSimple::CanBeUsedOnBack () inline private
Definition at line 19 of file actiondropitemsimple.c.
    {
        return true;
    }
IsInstant()
override bool ActionDropItemSimple::IsInstant () inline private
Definition at line 9 of file actiondropitemsimple.c.
    {
        return true;
    }
MainItemAlwaysInHands()
override bool ActionDropItemSimple::MainItemAlwaysInHands () inline private
Definition at line 14 of file actiondropitemsimple.c.
    {
        return false;
    }
PhysicalDropItem()
override void ActionDropItemSimple::PhysicalDropItem (ActionData action_data) inline private
Definition at line 34 of file actiondropitemsimple.c.
    {
        action_data.m_Player.PredictiveDropEntity(action_data.m_MainItem);
    }
References ActionData::m_MainItem, and ActionData::m_Player.
Referenced by Start().
Start()
override void ActionDropItemSimple::Start (ActionData action_data) inline private
Definition at line 24 of file actiondropitemsimple.c.
    {
        action_data.m_MainItem.m_ThrowItemOnDrop = action_data.m_MainItem.ConfigGetString("physLayer") == "item_large"; //hack, should be redundant anyway
        if ( !GetGame().IsDedicatedServer() )
        {
            ClearInventoryReservationEx(action_data);
            PhysicalDropItem(action_data);
        }
    }
References ClearInventoryReservationEx(), GetGame(), ActionData::m_MainItem, and PhysicalDropItem().