DayzKode: Hive Class Reference
Hive Class Reference
Private Member Functions
proto native void CallUpdater (string content)
proto native void CharacterExit (Man player)
proto native void CharacterKill (Man player)
proto native void CharacterSave (Man player)
private void Hive ()
proto native void InitOffline ()
proto native void InitOnline (string ceSetup, string host="")
proto native void InitSandbox ()
proto native bool IsIdleMode ()
proto native void SetEnviroment (string env)
proto native void SetShardID (string shard)
private void ~Hive ()
Detailed Description
Definition at line 5 of file hive.c.
Constructor & Destructor Documentation
Hive()
private void Hive::Hive () inline private
Definition at line 7 of file hive.c.
{}
~Hive()
private void Hive::~Hive () inline private
Definition at line 8 of file hive.c.
{}
Member Function Documentation
CallUpdater()
proto native void Hive::CallUpdater (string content) private
CharacterExit()
proto native void Hive::CharacterExit (Man player) private
Referenced by MissionBase::PlayerDisconnected().
CharacterKill()
proto native void Hive::CharacterKill (Man player) private
Referenced by ManBase::EEKilled().
CharacterSave()
proto native void Hive::CharacterSave (Man player) private
Referenced by ManBase::Save().
InitOffline()
proto native void Hive::InitOffline () private
InitOnline()
proto native void Hive::InitOnline (string ceSetup, string host = "") private
InitSandbox()
proto native void Hive::InitSandbox () private
IsIdleMode()
proto native bool Hive::IsIdleMode () private
SetEnviroment()
proto native void Hive::SetEnviroment (string env) private
SetShardID()
proto native void Hive::SetShardID (string shard) private