DayzKode: ActionUnpackBox Class Reference
ActionUnpackBox Class Reference
Private Member Functions
void ActionUnpackBox ()
override void CreateConditionComponents ()
override bool HasProneException ()
override bool HasTarget ()
override void OnFinishProgressServer (ActionData action_data)
Detailed Description
Definition at line 9 of file actionunpackbox.c.
Constructor & Destructor Documentation
ActionUnpackBox()
void ActionUnpackBox::ActionUnpackBox () inline private
Definition at line 11 of file actionunpackbox.c.
    {
        m_CallbackClass = ActionUnpackBoxCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENITEM;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_OPENITEM;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_Text = "#unbox";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, m_SpecialtyWeight, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
CreateConditionComponents()
override void ActionUnpackBox::CreateConditionComponents () inline private
Definition at line 20 of file actionunpackbox.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasProneException()
override bool ActionUnpackBox::HasProneException () inline private
Definition at line 26 of file actionunpackbox.c.
    {
        return true;
    }
HasTarget()
override bool ActionUnpackBox::HasTarget () inline private
Definition at line 31 of file actionunpackbox.c.
    {
        return false;
    }
OnFinishProgressServer()
override void ActionUnpackBox::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 36 of file actionunpackbox.c.
    {
        if ( action_data.m_MainItem && action_data.m_MainItem.GetHierarchyRootPlayer() == action_data.m_Player )
        {
            string path = "CfgVehicles " + action_data.m_MainItem.GetType();
            string child_name = "";
            int count;
            array<string> resources = new array<string>;
            if( GetGame().ConfigIsExisting( path ) && GetGame().ConfigIsExisting( path + " Resources") )
            {
                path = path + " Resources";
                count = GetGame().ConfigGetChildrenCount ( path );
                for (int i = 0; i < count; i++)
                {
                    GetGame().ConfigGetChildName ( path, i, child_name );
                    if ( GetGame().ConfigGetInt( path + " " + child_name + " value" ) )
                    {
                        resources.Insert( child_name );
                    }
                }
                //TODO modify to allow for multiple ammo types spawning (if needed??)
                string itemType = resources.Get(0);
                int itemCount = GetGame().ConfigGetInt( path + " " + itemType + " value" );
                UnboxLambda lambda = new UnboxLambda(action_data.m_MainItem, itemType, action_data.m_Player, itemCount);
                action_data.m_Player.ServerReplaceItemInHandsWithNew(lambda);
                //spawns wrapping Paper
                ItemBase paper = ItemBase.Cast( GetGame().CreateObjectEx("Paper", action_data.m_Player.GetPosition(), ECE_PLACE_ON_SURFACE) );
                action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), ConfigGetInt(), CGame::ConfigGetInt(), ConfigIsExisting(), ECE_PLACE_ON_SURFACE, GetGame(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and path.