DayzKode: ActionCarDoors Class Reference
ActionCarDoors Class Reference
Private Member Functions
void ActionCarDoors ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool CanBeUsedInVehicle ()
override void CreateConditionComponents ()
protected void FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3)
protected void FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1)
override void OnEnd (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
Private Attributes
string m_AnimSource = ""
CarScript m_Car = null
protected int m_CommandUIDPerCrewIdx [4]
protected bool m_IsOpening = true
Detailed Description
Definition at line 1 of file actioncardoors.c.
Constructor & Destructor Documentation
ActionCarDoors()
void ActionCarDoors::ActionCarDoors () inline private
Definition at line 10 of file actioncardoors.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ALL;
    }
References AnimatedActionBase::m_CommandUID, and m_StanceMask.
Member Function Documentation
ActionCondition()
override bool ActionCarDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
player inside vehicle
crewIdx sanity checks and see if there is a door
see if door is in reach
Definition at line 22 of file actioncardoors.c.
    {
        CarScript car       = null;
        string animSource   = "";
        if (player && player.GetCommand_Vehicle())
        {
            if (Class.CastTo(car, player.GetCommand_Vehicle().GetTransport()))
            {
                int crewIdx = car.CrewMemberIndex(player);
                if (crewIdx < 0 || crewIdx > 3 || car.GetCarDoorsState(car.GetDoorInvSlotNameFromSeatPos(crewIdx)) == CarDoorState.DOORS_MISSING)
                {
                    return false;
                }
                animSource = car.GetAnimSourceFromSelection(car.GetDoorSelectionNameFromSeatPos(crewIdx));
                if (!car.CanReachDoorsFromSeat(animSource, crewIdx) || !car.IsAreaAtDoorFree(crewIdx))
                {
                    return false;
                }
                m_CommandUID = m_CommandUIDPerCrewIdx[crewIdx];
                float animationPhaseInside = car.GetAnimationPhase(animSource);
                return (m_IsOpening && animationPhaseInside <= 0.5) || (!m_IsOpening && animationPhaseInside > 0.5);
            }
        }
        return false;
    }
References CarScript::CanReachDoorsFromSeat(), Class::CastTo(), CarScript::GetAnimSourceFromSelection(), CarScript::GetCarDoorsState(), CarScript::GetDoorInvSlotNameFromSeatPos(), CarScript::GetDoorSelectionNameFromSeatPos(), AnimatedActionBase::m_CommandUID, m_CommandUIDPerCrewIdx, and m_IsOpening.
CanBeUsedInVehicle()
override bool ActionCarDoors::CanBeUsedInVehicle () inline private
Definition at line 115 of file actioncardoors.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionCarDoors::CreateConditionComponents () inline private
Definition at line 16 of file actioncardoors.c.
    {
        m_ConditionItem     = new CCINone;
        m_ConditionTarget   = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
FillCommandUIDPerCrewIdx() [1/2]
protected void ActionCarDoors::FillCommandUIDPerCrewIdx (int crewIdx0, int crewIdx1, int crewIdx2, int crewIdx3) inline private
Definition at line 120 of file actioncardoors.c.
    {
        m_CommandUIDPerCrewIdx[0] = crewIdx0;
        m_CommandUIDPerCrewIdx[1] = crewIdx1;
        m_CommandUIDPerCrewIdx[2] = crewIdx2;
        m_CommandUIDPerCrewIdx[3] = crewIdx3;
    }
References m_CommandUIDPerCrewIdx.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionOpenCarDoors::ActionOpenCarDoors(), and FillCommandUIDPerCrewIdx().
FillCommandUIDPerCrewIdx() [2/2]
protected void ActionCarDoors::FillCommandUIDPerCrewIdx (int evenCrewIdx0, int unevenCrewIdx1) inline private
Definition at line 128 of file actioncardoors.c.
    {
        FillCommandUIDPerCrewIdx(evenCrewIdx0, unevenCrewIdx1, evenCrewIdx0, unevenCrewIdx1);
    }
References FillCommandUIDPerCrewIdx().
OnEnd()
override void ActionCarDoors::OnEnd (ActionData action_data) inline private
Definition at line 107 of file actioncardoors.c.
    {
        if (m_Car || m_AnimSource.Length() > 0)
        {
            Error("[WARNING] m_Car and m_AnimSource are left for backwards compatibility to not crash mods that are using it, but should no longer be used.");
        }
    }
References Error(), string::Length(), m_AnimSource, and m_Car.
OnEndServer()
override void ActionCarDoors::OnEndServer (ActionData action_data) inline private
Definition at line 92 of file actioncardoors.c.
    {
        CarScript car;
        PlayerBase player = action_data.m_Player;
        if (player && player.GetCommand_Vehicle())
        {
            car = CarScript.Cast(player.GetCommand_Vehicle().GetTransport());
        }
        if (car)
        {
            car.ForceUpdateLightsEnd();
        }
    }
References ActionData::m_Player.
OnStartServer()
override void ActionCarDoors::OnStartServer (ActionData action_data) inline private
Definition at line 58 of file actioncardoors.c.
    {
        PlayerBase player = action_data.m_Player;
        float phase;
        if (m_IsOpening)
        {
            phase = 1.0;
        }
        else
        {
            phase = 0.0;
        }
        string animSource = "";
        CarScript car;
        if (player && player.GetCommand_Vehicle())
        {
            car = CarScript.Cast(player.GetCommand_Vehicle().GetTransport());
            if (car)
            {
                int crewIdx = car.CrewMemberIndex(player);
                animSource = car.GetAnimSourceFromSelection(car.GetDoorSelectionNameFromSeatPos(crewIdx));
            }
        }
        if (car)
        {
            car.ForceUpdateLightsStart();
            car.SetAnimationPhase(animSource, phase);
        }
    }
References CarScript::GetAnimSourceFromSelection(), CarScript::GetDoorSelectionNameFromSeatPos(), m_IsOpening, and ActionData::m_Player.
Member Data Documentation
m_AnimSource
string ActionCarDoors::m_AnimSource = "" private
Definition at line 7 of file actioncardoors.c.
Referenced by OnEnd().
m_Car
CarScript ActionCarDoors::m_Car = null private
Definition at line 6 of file actioncardoors.c.
Referenced by OnEnd().
m_CommandUIDPerCrewIdx
protected int ActionCarDoors::m_CommandUIDPerCrewIdx[4] private
Definition at line 3 of file actioncardoors.c.
Referenced by ActionCondition(), and FillCommandUIDPerCrewIdx().
m_IsOpening
protected bool ActionCarDoors::m_IsOpening = true private
Definition at line 4 of file actioncardoors.c.
Referenced by ActionCloseCarDoors::ActionCloseCarDoors(), ActionCondition(), ActionOpenCarDoors::ActionOpenCarDoors(), and OnStartServer().