DayzKode: ActionCookOnStick Class Reference
ActionCookOnStick Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionCookOnStick ()
override void CreateConditionComponents ()
override void OnEndServer (ActionData action_data)
Detailed Description
Definition at line 11 of file actioncookonstick.c.
Constructor & Destructor Documentation
ActionCookOnStick()
void ActionCookOnStick::ActionCookOnStick () inline private
Definition at line 13 of file actioncookonstick.c.
    {
        m_CallbackClass     = ActionCookOnStickCB;
        m_CommandUID        = DayZPlayerConstants.CMD_GESTUREFB_CAMPFIRE;
        m_FullBody          = true;
        m_StanceMask        = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight   = UASoftSkillsWeight.ROUGH_LOW;
        m_LockTargetOnUse   = false;
        m_Text              = "#cook_on_stick";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_LockTargetOnUse, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionCookOnStick::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actioncookonstick.c.
    {
        FireplaceBase fireplace_target = FireplaceBase.Cast(target.GetObject());
        Object targetObject = target.GetObject();
        Edible_Base item_on_stick = Edible_Base.Cast(item.GetAttachmentByType(Edible_Base));
        if (fireplace_target && item_on_stick && item_on_stick.CanBeCookedOnStick())
        {
            //fireplace
            if (fireplace_target.IsBaseFireplace())
            {
                Fireplace fireplace = Fireplace.Cast(fireplace_target);
                if (!fireplace.IsOven() && fireplace_target.CanCookOnStick())
                {
                    return true;
                }
            }
            //fireplace indoor
            if (fireplace_target.IsFireplaceIndoor())
            {
                if (fireplace_target.CanCookOnStick())
                {
                    return true;
                }
            }
        }
        return false;
    }
References Edible_Base::CanBeCookedOnStick(), FireplaceBase::IsBaseFireplace(), and FireplaceBase::IsFireplaceIndoor().
CreateConditionComponents()
override void ActionCookOnStick::CreateConditionComponents () inline private
Definition at line 25 of file actioncookonstick.c.
    {
        m_ConditionTarget   = new CCTNonRuined(UAMaxDistances.DEFAULT);
        m_ConditionItem     = new CCINonRuined;
    }
References UAMaxDistances::DEFAULT, m_ConditionItem, and m_ConditionTarget.
OnEndServer()
override void ActionCookOnStick::OnEndServer (ActionData action_data) inline private
Definition at line 61 of file actioncookonstick.c.
    {
        super.OnEndServer(action_data);
        ItemBase stick = action_data.m_MainItem;
        Edible_Base item_on_stick = Edible_Base.Cast(stick.GetAttachmentByType(Edible_Base));
        if (item_on_stick)
        {
            item_on_stick.MakeSoundsOnClient(false);
        }
    }
References ActionData::m_MainItem.