DayzKode: CreditsElement Class Reference
CreditsElement Class Reference
Private Member Functions
void CreditsDepartmentElement (int index, Widget parent, JsonDataCreditsDepartment department_data)
void CreditsGraphicalElement (int index, Widget parent)
void LoadDataAsync (array< ref JsonDataCreditsSection > department_data)
Private Attributes
protected ref array< ref CreditsDepartmentSection > m_DepartmentSectionEntries = new array<ref CreditsDepartmentSection>
protected GridSpacerWidget m_DepartmentSections
protected TextWidget m_DepartmentTitle
Detailed Description
Definition at line 1 of file creditsdepartmentelement.c.
Member Function Documentation
CreditsDepartmentElement()
void CreditsElement::CreditsDepartmentElement (int index, Widget parent, JsonDataCreditsDepartment department_data) inline private
Definition at line 7 of file creditsdepartmentelement.c.
    {
        m_Root                  = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/credits/department_element/department_element.layout", parent );
        m_DepartmentTitle       = TextWidget.Cast( m_Root.FindAnyWidget( "department_title" ) );
        m_DepartmentSections    = GridSpacerWidget.Cast( m_Root.FindAnyWidget( "department_sections" ) );
        if( department_data.DepartmentName != "" )
        {
            m_DepartmentTitle.SetText( department_data.DepartmentName );
        }
        else
        {
            m_DepartmentTitle.Show( false );
            m_Root.FindAnyWidget( "SeparatorPanel" ).Show( false );
        }
        m_Root.SetSort( index );
        LoadDataAsync( department_data.Sections );
    }
References WorkspaceWidget::CreateWidgets(), JsonDataCreditsDepartment::DepartmentName, GetGame(), CGame::GetWorkspace(), LoadDataAsync(), m_Root, and JsonDataCreditsDepartment::Sections.
CreditsGraphicalElement()
void CreditsElement::CreditsGraphicalElement (int index, Widget parent) inline private
Definition at line 3 of file creditsgraphicalelement.c.
    {
    }
LoadDataAsync()
void CreditsElement::LoadDataAsync (array< ref JsonDataCreditsSection > department_data) inline private
Definition at line 27 of file creditsdepartmentelement.c.
    {
        for( int i = 1; i <= department_data.Count(); i++ )
        {
            ref CreditsDepartmentSection e = new CreditsDepartmentSection( i, m_DepartmentSections, department_data.Get( i - 1 ) );
            m_DepartmentSectionEntries.Insert( e );
        }
        m_DepartmentSections.Update();
    }
References CreditsDepartmentSection().
Referenced by CreditsDepartmentElement(), and CreditsDepartmentSection().
Member Data Documentation
m_DepartmentSectionEntries
protected ref array<ref CreditsDepartmentSection> CreditsElement::m_DepartmentSectionEntries = new array<ref CreditsDepartmentSection> private
Definition at line 5 of file creditsdepartmentelement.c.
m_DepartmentSections
protected GridSpacerWidget CreditsElement::m_DepartmentSections private
Definition at line 4 of file creditsdepartmentelement.c.
m_DepartmentTitle
protected TextWidget CreditsElement::m_DepartmentTitle private
Definition at line 3 of file creditsdepartmentelement.c.