DayzKode: ActionBuildPart Class Reference
ActionBuildPart Class Reference
Private Member Functions
void ActionBuildPart ()
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
override bool CanBeUsedLeaning ()
override ActionData CreateActionData ()
override void CreateConditionComponents ()
override string GetAdminLogMessage (ActionData action_data)
override void HandleReciveData (ActionReciveData action_recive_data, ActionData action_data)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
override bool ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data)
protected void SetBuildingAnimation (ItemBase item)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
override void WriteToContext (ParamsWriteContext ctx, ActionData action_data)
Detailed Description
Definition at line 34 of file actionbuildpart.c.
Constructor & Destructor Documentation
ActionBuildPart()
void ActionBuildPart::ActionBuildPart () inline private
Definition at line 36 of file actionbuildpart.c.
    {
        m_CallbackClass = ActionBuildPartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#build";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionBuildPart::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 69 of file actionbuildpart.c.
    {
        if ( player.IsPlacingLocal() || player.IsPlacingServer() )
            return false;
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        //hack - gate
        //WTF
        if (target.GetObject() && (!target.GetObject().CanUseConstructionBuild() || target.GetObject().CanUseHandConstruction()))
            return false;
        if ( (!GetGame().IsDedicatedServer()) )
        {
            if ( MiscGameplayFunctions.ComplexBuildCollideCheckClient(player, target, item, m_VariantID ) )
            {
                return true;
            }
            return false;
        }
        return true;
    }
References GetGame(), and m_VariantID.
ActionConditionContinue()
override bool ActionBuildPart::ActionConditionContinue (ActionData action_data) inline private
Definition at line 94 of file actionbuildpart.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        string part_name = BuildPartActionData.Cast(action_data).m_PartType;
        CollisionCheckData check_data = new CollisionCheckData;
        check_data.m_PartName = part_name;
        check_data.m_AdditionalExcludes.Insert(action_data.m_Player);
        return !construction.IsCollidingEx( check_data ) && construction.CanBuildPart( part_name, action_data.m_MainItem, true );
    }
References CollisionCheckData(), Construction(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool ActionBuildPart::CanBeUsedLeaning () inline private
Definition at line 64 of file actionbuildpart.c.
    {
        return false;
    }
CreateActionData()
override ActionData ActionBuildPart::CreateActionData () inline private
Definition at line 128 of file actionbuildpart.c.
    {
        BuildPartActionData action_data = new BuildPartActionData;
        return action_data;
    }
CreateConditionComponents()
override void ActionBuildPart::CreateConditionComponents () inline private
Definition at line 47 of file actionbuildpart.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
GetAdminLogMessage()
override string ActionBuildPart::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 205 of file actionbuildpart.c.
    {
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        string partName = BuildPartActionData.Cast(action_data).m_PartType;
        string message = string.Format("Built %1 on %2 with %3", partName, action_data.m_Target.GetObject().GetDisplayName(), action_data.m_MainItem.GetDisplayName() );
        return message;
    }
References ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
HandleReciveData()
override void ActionBuildPart::HandleReciveData (ActionReciveData action_recive_data, ActionData action_data) inline private
Definition at line 198 of file actionbuildpart.c.
    {
        super.HandleReciveData(action_recive_data, action_data);
        BuildPartActionData.Cast(action_data).m_PartType = BuildPartActionReciveData.Cast( action_recive_data ).m_PartType;
    }
References BuildPartActionReciveData::m_PartType.
OnActionInfoUpdate()
override void ActionBuildPart::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 53 of file actionbuildpart.c.
    {
        ConstructionActionData construction_action_data = player.GetConstructionActionData();
        ConstructionPart constrution_part = construction_action_data.GetBuildPartAtIndex(m_VariantID);
        if ( constrution_part )
        {
            m_Text = "#build " + constrution_part.GetName();
        }
    }
References ConstructionActionData::GetBuildPartAtIndex(), ConstructionPart::GetName(), m_Text, and m_VariantID.
OnFinishProgressServer()
override void ActionBuildPart::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 107 of file actionbuildpart.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        string part_name = BuildPartActionData.Cast(action_data).m_PartType;
        CollisionCheckData check_data = new CollisionCheckData;
        check_data.m_PartName = part_name;
        check_data.m_AdditionalExcludes.Insert(action_data.m_Player);
        if ( !construction.IsCollidingEx( check_data ) && construction.CanBuildPart( part_name, action_data.m_MainItem, true ) ) //redundant at this point?
        {
            //build
            construction.BuildPartServer( action_data.m_Player, part_name, AT_BUILD_PART );
            //add damage to tool
            action_data.m_MainItem.DecreaseHealth( UADamageApplied.BUILD, false );
            action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        }
    }
References AT_BUILD_PART, UADamageApplied::BUILD, CollisionCheckData(), Construction(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
ReadFromContext()
override bool ActionBuildPart::ReadFromContext (ParamsReadContext ctx, out ActionReciveData action_recive_data) inline private
Definition at line 181 of file actionbuildpart.c.
    {
        action_recive_data = new BuildPartActionReciveData;
        super.ReadFromContext(ctx, action_recive_data);
        string part_type;
        if ( ctx.Read(part_type) )
        {
            BuildPartActionReciveData.Cast( action_recive_data ).m_PartType = part_type;
            return true;
        }
        else
        {
            return false;
        }
    }
References BuildPartActionReciveData::m_PartType, and Serializer::Read().
SetBuildingAnimation()
protected void ActionBuildPart::SetBuildingAnimation (ItemBase item) inline private
Definition at line 152 of file actionbuildpart.c.
    {
        switch ( item.Type() )
        {
            case Pickaxe:
            case Shovel:
            case FarmingHoe:
            case FieldShovel:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIG;
                break;
            case Pliers:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_INTERACT;
                break;
            case SledgeHammer:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_MINEROCK;
                break;
            default:
                m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_ASSEMBLE;
                break;
        }
    }
References AnimatedActionBase::m_CommandUID.
Referenced by SetupAction().
SetupAction()
override bool ActionBuildPart::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 135 of file actionbuildpart.c.
    {
        if ( super.SetupAction( player, target, item, action_data, extra_data ) )
        {
            SetBuildingAnimation( item );
            if ( !GetGame().IsDedicatedServer() )
            {
                ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
                BuildPartActionData.Cast(action_data).m_PartType = construction_action_data.GetBuildPartAtIndex(m_VariantID).GetPartName();
            }
            return true;
        }
        return false;
    }
References ConstructionActionData::GetBuildPartAtIndex(), GetGame(), ConstructionPart::GetPartName(), m_VariantID, and SetBuildingAnimation().
WriteToContext()
override void ActionBuildPart::WriteToContext (ParamsWriteContext ctx, ActionData action_data) inline private
Definition at line 174 of file actionbuildpart.c.
    {
        super.WriteToContext(ctx, action_data);
        ctx.Write(BuildPartActionData.Cast(action_data).m_PartType);
    }
References Serializer::Write().