DayzKode: ActionEnterLadder Class Reference
ActionEnterLadder Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionEnterLadder ()
override bool CanBeUsedSwimming ()
override void CreateConditionComponents ()
override bool IsInstant ()
override void Start (ActionData action_data)
override bool UseAcknowledgment ()
Private Attributes
private const string GEOM_LOD_NAME = LOD.NAME_GEOMETRY
private const string MEM_LOD_NAME = LOD.NAME_MEMORY
Detailed Description
Definition at line 2 of file actionenterladder.c.
Constructor & Destructor Documentation
ActionEnterLadder()
void ActionEnterLadder::ActionEnterLadder () inline private
Definition at line 7 of file actionenterladder.c.
    {
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#enter_ladder";
    }
References m_StanceMask, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionEnterLadder::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
is action_data.m_Target ? not on ladder and not falling ?
Definition at line 19 of file actionenterladder.c.
    {
        if (!target || !target.GetObject() || player.GetCommand_Ladder() || player.GetCommand_Fall() )
            return false;
        Building building;
        if (!Class.CastTo(building, target.GetObject()))
            return false;
        // TODO: direction tests
        // Get memory LOD from p3d and save all its selections
        LOD lod = building.GetLODByName(MEM_LOD_NAME);
        if(lod == NULL)
            return false;
        ref array<Selection> memSelection   = new array<Selection>();
        if(!lod.GetSelections(memSelection))
            return false;
        string compName = building.GetActionComponentName( target.GetComponentIndex() );
        if( compName.Length() < 6 || compName.Substring(0,6) != "ladder" )
        {
            return false;
        }
        // ze stringu compName dostat posledni cislo a to je index zebriku
        //building.GetActionComponentNameList( action_data.m_Target.GetComponentIndex(), components );
        string condCompName = string.Format("%1_con", compName);
        vector pos = player.GetPosition();
        //Print(w);
        bool found = false;
        vector ladderEnterPointGlobal;
        vector ladderDirPointGlobal;
        float minDistanceSq = 100.0;
        string dirCompName = string.Format("%1_con_dir", compName);
        for ( int i = 0; i < memSelection.Count(); i++ )
        {
            if ( memSelection[i].GetName() == condCompName )
            {
                for( int j = 0; j < memSelection[i].GetVertexCount(); j++ )
                {
                    ladderEnterPointGlobal = building.ModelToWorld( memSelection[i].GetVertexPosition(lod, j) );
                    if( vector.DistanceSq(ladderEnterPointGlobal,pos) < UAMaxDistances.LADDERS * UAMaxDistances.LADDERS)
                    {
                        HumanCommandLadder.DebugDrawLadder(building, HumanCommandLadder.DebugGetLadderIndex(compName));
                        found = true;
                        break;
                    }
                }
            }
        }
        if (found)
        {
            for (int k = 0; k < memSelection.Count(); k++)
            {
                if( memSelection[k].GetName() == dirCompName )
                {
                    for( int l = 0; l < memSelection[k].GetVertexCount(); l++ )
                    {
                        vector dirPoint = building.ModelToWorld( memSelection[k].GetVertexPosition(lod, l) );
                        float dst = vector.DistanceSq(ladderEnterPointGlobal,dirPoint);
                        if(  dst < minDistanceSq)
{
                            minDistanceSq = dst;
                            ladderDirPointGlobal = dirPoint;
                        //HumanCommandLadder.DebugDrawLadder(building, HumanCommandLadder.DebugGetLadderIndex(compName));
                        //found = true;
                        }
                    }
                }
            }
            pos = pos - ladderEnterPointGlobal;
            ladderDirPointGlobal = ladderDirPointGlobal - ladderEnterPointGlobal;
            float angle = Math.AbsFloat(pos.VectorToAngles()[0] - ladderDirPointGlobal.VectorToAngles()[0]);
            if ( angle < 90 || angle > 270)
            {
                return true;
            }
        }
        return false;
    }
References Math::AbsFloat(), Class::CastTo(), HumanCommandLadder::DebugDrawLadder(), HumanCommandLadder::DebugGetLadderIndex(), vector::DistanceSq(), GetName(), LOD::GetSelections(), UAMaxDistances::LADDERS, string::Length(), MEM_LOD_NAME, string::Substring(), and vector::VectorToAngles().
CanBeUsedSwimming()
override bool ActionEnterLadder::CanBeUsedSwimming () inline private
Definition at line 209 of file actionenterladder.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionEnterLadder::CreateConditionComponents () inline private
Definition at line 13 of file actionenterladder.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
IsInstant()
override bool ActionEnterLadder::IsInstant () inline private
Definition at line 199 of file actionenterladder.c.
    {
        return true;
    }
Start()
override void ActionEnterLadder::Start (ActionData action_data) inline private
Definition at line 113 of file actionenterladder.c.
    {
        super.Start( action_data );
        Building    b;
        Class.CastTo(b, action_data.m_Target.GetObject());
        if (b)
        {
            string compName     = b.GetActionComponentName( action_data.m_Target.GetComponentIndex() );
            int     ladderIndex = HumanCommandLadder.DebugGetLadderIndex(compName);
            LOD geomLod = action_data.m_Target.GetObject().GetLODByName(GEOM_LOD_NAME);
            string ladderType = "metal";
            for (int i = 0; i < geomLod.GetPropertyCount(); ++i)
            {
                if (geomLod.GetPropertyName(i) == "laddertype")
                {
                    ladderType = geomLod.GetPropertyValue(i);
                    break;
                }
            }
            action_data.m_Player.SetClimbingLadderType(ladderType);
            action_data.m_Player.StartCommand_Ladder(b, ladderIndex );
        }
        /* if( GetGame().IsServer() )
        {
            OnStartServer(action_data);
        }
        else
        {
            OnStartClient(action_data);
        }*/
    }
References Class::CastTo(), HumanCommandLadder::DebugGetLadderIndex(), GEOM_LOD_NAME, LOD::GetPropertyCount(), LOD::GetPropertyName(), LOD::GetPropertyValue(), ActionData::m_Player, and ActionData::m_Target.
UseAcknowledgment()
override bool ActionEnterLadder::UseAcknowledgment () inline private
Definition at line 204 of file actionenterladder.c.
    {
        return false;
    }
Member Data Documentation
GEOM_LOD_NAME
private const string ActionEnterLadder::GEOM_LOD_NAME = LOD.NAME_GEOMETRY private
Definition at line 4 of file actionenterladder.c.
Referenced by Start().
MEM_LOD_NAME
private const string ActionEnterLadder::MEM_LOD_NAME = LOD.NAME_MEMORY private
Definition at line 5 of file actionenterladder.c.
Referenced by ActionCondition().