DayzKode: BotWaitForChangeInHands Class Reference
BotWaitForChangeInHands Class Reference
Private Member Functions
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
Private Attributes
EntityAI m_Entity
Detailed Description
Definition at line 158 of file bot_testspawnandopencan.c.
Member Function Documentation
OnAbort() [1/3]
override void BotWaitForChangeInHands::OnAbort (BotEventBase e) inline private
Definition at line 177 of file bot_testspawnandopencan.c.
{ super.OnAbort(e); }
OnAbort() [2/3]
override void BotWaitForChangeInHands::OnAbort (BotEventBase e) inline private
Definition at line 210 of file bot_testspawnandopencan.c.
{ super.OnAbort(e); }
OnAbort() [3/3]
override void BotWaitForChangeInHands::OnAbort (BotEventBase e) inline private
Definition at line 234 of file bot_testspawnandopencan.c.
{ super.OnAbort(e); }
OnEntry() [1/3]
override void BotWaitForChangeInHands::OnEntry (BotEventBase e) inline private
Definition at line 162 of file bot_testspawnandopencan.c.
    {
        super.OnEntry(e);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        if (inHands)
        {
            botDebugPrint("[bot] + " + m_Owner + " dropping item=" + inHands + " bot=" + m_Owner);
            if (m_Owner.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
                m_Owner.PredictiveDropEntity(inHands);
            //m_Owner.LocalDropEntity(inHands);
        }
    }
References botDebugPrint(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnEntry() [2/3]
override void BotWaitForChangeInHands::OnEntry (BotEventBase e) inline private
Definition at line 186 of file bot_testspawnandopencan.c.
    {
        super.OnEntry(e);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        if (inHands)
        {
            botDebugPrint("[bot] + " + m_Owner + " eating item=" + inHands + " bot=" + m_Owner);
            if (m_Owner.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
            {
#ifdef BOT
                ActionManagerBase mgr = m_Owner.GetActionManager();
                ActionManagerClient cli_mgr = ActionManagerClient.Cast(mgr);
                if (cli_mgr)
                {
                    ActionTarget target;
                    target = new ActionTarget(inHands, null, -1, vector.Zero, -1);
                    cli_mgr.PerformAction(AT_EAT, target, inHands);
                }
#endif
            }
        }
    }
References ActionTarget, botDebugPrint(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), and vector::Zero.
OnEntry() [3/3]
override void BotWaitForChangeInHands::OnEntry (BotEventBase e) inline private
Definition at line 221 of file bot_testspawnandopencan.c.
    {
        super.OnEntry(e);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        if (inHands)
        {
            botDebugPrint("[bot] + " + m_Owner + " deleting item=" + inHands + " bot=" + m_Owner);
            if (m_Owner.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                inHands.Delete();
        }
    }
References botDebugPrint(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnExit() [1/3]
override void BotWaitForChangeInHands::OnExit (BotEventBase e) inline private
Definition at line 178 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnExit() [2/3]
override void BotWaitForChangeInHands::OnExit (BotEventBase e) inline private
Definition at line 211 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnExit() [3/3]
override void BotWaitForChangeInHands::OnExit (BotEventBase e) inline private
Definition at line 235 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnUpdate() [1/3]
override void BotWaitForChangeInHands::OnUpdate (float dt) inline private
Definition at line 179 of file bot_testspawnandopencan.c.
{ super.OnUpdate(dt); }
OnUpdate() [2/3]
override void BotWaitForChangeInHands::OnUpdate (float dt) inline private
Definition at line 212 of file bot_testspawnandopencan.c.
{ super.OnUpdate(dt); }
OnUpdate() [3/3]
override void BotWaitForChangeInHands::OnUpdate (float dt) inline private
Definition at line 236 of file bot_testspawnandopencan.c.
{ super.OnUpdate(dt); }
Member Data Documentation
m_Entity
EntityAI BotWaitForChangeInHands::m_Entity private
Definition at line 160 of file bot_testspawnandopencan.c.