DayzKode: VicinityItemManager Class Reference
VicinityItemManager Class Reference
Private Member Functions
void AddVicinityCargos (CargoBase object)
void AddVicinityItems (Object object)
bool CanIgnoreDistanceCheck (EntityAI entity_ai)
private void CleanupDebugShapes (array< Shape > shapesArr)
private void DebugActorsSphereDraw (float radius)
private void DebugConeDraw (vector start, float cone_angle)
private void DebugObjectsSphereDraw (float radius)
private void DebugRaycastDraw (vector start, vector end)
bool ExcludeFromContainer_Phase1 (Object actor_in_radius)
bool ExcludeFromContainer_Phase2 (Object object_in_radius)
bool ExcludeFromContainer_Phase3 (Object object_in_cone)
array< CargoBase > GetVicinityCargos ()
array< EntityAI > GetVicinityItems ()
void Init ()
bool IsObstructed (Object filtered_object)
void RefreshVicinityItems ()
void ResetRefreshCounter ()
void Update (float delta_time)
Static Private Member Functions
static VicinityItemManager GetInstance ()
Private Attributes
private const string CE_CENTER = "ce_center"
private const float CONE_HEIGHT_MAX = 3.0
private const float CONE_HEIGHT_MIN = -0.5
private const float HEIGHT_OFFSET = 0.2
private float m_RefreshCounter
private ref array< CargoBase > m_VicinityCargos = new array<CargoBase>
private ref array< EntityAI > m_VicinityItems = new array<EntityAI>
private const int OBJECT_OBSTRUCTION_WEIGHT = 10000
ref array< Shape > rayShapes = new array<Shape>()
private const float UPDATE_FREQUENCY = 0.25
private const float VICINITY_ACTOR_DISTANCE = 2.0
private const float VICINITY_CONE_ANGLE = 30
private const float VICINITY_CONE_DISTANCE = 2.0
private const float VICINITY_CONE_RADIANS = 0.5
private const float VICINITY_CONE_REACH_DISTANCE = 2.0
private const float VICINITY_DISTANCE = 0.5
private const float VICINITY_LARGE_ACTOR_DISTANCE = 3.0
Static Private Attributes
static private ref VicinityItemManager s_Instance
Detailed Description
Definition at line 1 of file vicinityitemmanager.c.
Member Function Documentation
AddVicinityCargos()
void VicinityItemManager::AddVicinityCargos (CargoBase object) inline private
Definition at line 56 of file vicinityitemmanager.c.
    {
        if ( m_VicinityCargos.Find( object ) == INDEX_NOT_FOUND /*&& GameInventory.CheckManipulatedObjectsDistances( inventory_item, GetGame().GetPlayer(), VICINITY_CONE_REACH_DISTANCE ) */ )
        {
            m_VicinityCargos.Insert( object );
        }
    }
References INDEX_NOT_FOUND, and m_VicinityCargos.
Referenced by RefreshVicinityItems().
AddVicinityItems()
void VicinityItemManager::AddVicinityItems (Object object) inline private
Definition at line 38 of file vicinityitemmanager.c.
    {
        EntityAI inventory_item = EntityAI.Cast( object );
        if ( inventory_item )
        {
            if ( m_VicinityItems.Find( inventory_item ) == INDEX_NOT_FOUND && GameInventory.CheckManipulatedObjectsDistances( inventory_item, GetGame().GetPlayer(), VICINITY_CONE_REACH_DISTANCE + 1.0 ) )
            {
                m_VicinityItems.Insert( inventory_item );
            }
        }
    }
References GetGame(), GetPlayer(), INDEX_NOT_FOUND, m_VicinityItems, and VICINITY_CONE_REACH_DISTANCE.
Referenced by RefreshVicinityItems().
CanIgnoreDistanceCheck()
bool VicinityItemManager::CanIgnoreDistanceCheck (EntityAI entity_ai) inline private
Definition at line 196 of file vicinityitemmanager.c.
    {
        return MiscGameplayFunctions.CanIgnoreDistanceCheck(entity_ai);
    }
Referenced by RefreshVicinityItems().
CleanupDebugShapes()
private void VicinityItemManager::CleanupDebugShapes (array< Shape > shapesArr) inline private
Definition at line 468 of file vicinityitemmanager.c.
    {
        for ( int it = 0; it < shapesArr.Count(); ++it )
        {
            Debug.RemoveShape( shapesArr[it] );
        }
        shapesArr.Clear();
    }
References Debug::RemoveShape().
Referenced by DebugActorsSphereDraw().
DebugActorsSphereDraw()
private void VicinityItemManager::DebugActorsSphereDraw (float radius) inline private
Definition at line 427 of file vicinityitemmanager.c.
    {
        CleanupDebugShapes(rayShapes);
        rayShapes.Insert( Debug.DrawSphere( GetGame().GetPlayer().GetPosition(), radius, COLOR_GREEN, ShapeFlags.TRANSP|ShapeFlags.WIREFRAME ) );
    }
References CleanupDebugShapes(), COLOR_GREEN, Debug::DrawSphere(), GetGame(), GetPlayer(), GetPosition, and rayShapes.
DebugConeDraw()
private void VicinityItemManager::DebugConeDraw (vector start, float cone_angle) inline private
Definition at line 444 of file vicinityitemmanager.c.
    {
        vector endL, endR;
        float playerAngle;
        float xL,xR,zL,zR;
        playerAngle = MiscGameplayFunctions.GetHeadingAngle( PlayerBase.Cast( GetGame().GetPlayer() ) );
        endL = start;
        endR = start;
        xL = VICINITY_CONE_REACH_DISTANCE * Math.Cos( playerAngle + Math.PI_HALF + cone_angle * Math.DEG2RAD ); // x
        zL = VICINITY_CONE_REACH_DISTANCE * Math.Sin( playerAngle + Math.PI_HALF + cone_angle * Math.DEG2RAD ); // z
        xR = VICINITY_CONE_REACH_DISTANCE * Math.Cos( playerAngle + Math.PI_HALF - cone_angle * Math.DEG2RAD ); // x
        zR = VICINITY_CONE_REACH_DISTANCE * Math.Sin( playerAngle + Math.PI_HALF - cone_angle * Math.DEG2RAD ); // z
        endL[0] = endL[0] + xL;
        endL[2] = endL[2] + zL;
        endR[0] = endR[0] + xR;
        endR[2] = endR[2] + zR;
        rayShapes.Insert( Debug.DrawLine( start, endL, COLOR_GREEN ) );
        rayShapes.Insert( Debug.DrawLine( start, endR, COLOR_GREEN ) ) ;
        rayShapes.Insert( Debug.DrawLine( endL, endR, COLOR_GREEN ) );
    }
References COLOR_GREEN, Math::Cos(), Math::DEG2RAD, Debug::DrawLine(), GetGame(), GetPlayer(), Math::PI_HALF, rayShapes, Math::Sin(), and VICINITY_CONE_REACH_DISTANCE.
DebugObjectsSphereDraw()
private void VicinityItemManager::DebugObjectsSphereDraw (float radius) inline private
Definition at line 434 of file vicinityitemmanager.c.
    {
        rayShapes.Insert( Debug.DrawSphere( GetGame().GetPlayer().GetPosition(), radius, COLOR_GREEN, ShapeFlags.TRANSP|ShapeFlags.WIREFRAME ) );
    }
References COLOR_GREEN, Debug::DrawSphere(), GetGame(), GetPlayer(), GetPosition, and rayShapes.
DebugRaycastDraw()
private void VicinityItemManager::DebugRaycastDraw (vector start, vector end) inline private
Definition at line 439 of file vicinityitemmanager.c.
    {
        rayShapes.Insert( Debug.DrawArrow( start, end, 0.5, COLOR_YELLOW ) );
    }
References COLOR_YELLOW, Debug::DrawArrow(), and rayShapes.
ExcludeFromContainer_Phase1()
bool VicinityItemManager::ExcludeFromContainer_Phase1 (Object actor_in_radius) inline private
Definition at line 83 of file vicinityitemmanager.c.
    {
        EntityAI entity_ai;
        if ( !Class.CastTo( entity_ai, actor_in_radius) )
            return true;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        if ( entity_ai == player )
            return true;
        if ( entity_ai.IsParticle() )
            return true;
        if ( entity_ai.IsScriptedLight() )
            return true;
        if ( entity_ai.IsBeingPlaced() )
            return true;
        if ( entity_ai.IsHologram() )
            return true;
        if ( entity_ai.IsMan() || entity_ai.IsZombie() || entity_ai.IsZombieMilitary() )
        {
            //visibility cone check
            vector object_center_pos = entity_ai.GetPosition();
            if ( entity_ai && entity_ai.IsMan() )
            {
                PlayerBase vicinity_player = PlayerBase.Cast( entity_ai );
                if ( vicinity_player )
                {
                    int bone_index_player = vicinity_player.GetBoneIndexByName( "spine3" );
                    object_center_pos = vicinity_player.GetBonePositionWS( bone_index_player );
                }
            }
            else if ( entity_ai && (entity_ai.IsZombie() || entity_ai.IsZombieMilitary()) )
            {
                ZombieBase vicinity_zombie = ZombieBase.Cast( entity_ai );
                if ( vicinity_zombie )
                {
                    int bone_index_zombie = vicinity_zombie.GetBoneIndexByName( "spine3" );
                    object_center_pos = vicinity_zombie.GetBonePositionWS( bone_index_zombie );
                }
            }
            vector entity_direction = player.GetPosition() - object_center_pos;
            entity_direction.Normalize();
            entity_direction[1] = 0; //ignore height
            vector player_direction =  MiscGameplayFunctions.GetHeadingVector( player );
            player_direction.Normalize();
            player_direction[1] = 0; //ignore height
            float dot_rad = vector.Dot( player_direction, entity_direction );
            if ( dot_rad > -0.5 )
            {
                //Print("~~~actor_in_radius out of VICINITY_CONE_RADIANS~~~");
                //Print("~~~dot_rad: ~~~: " + dot_rad);
                return true;
            }
        }
        return false;
    }
References Class::CastTo(), vector::Dot(), GetGame(), GetPlayer(), EntityAI::IsMan(), and vector::Normalize().
Referenced by RefreshVicinityItems().
ExcludeFromContainer_Phase2()
bool VicinityItemManager::ExcludeFromContainer_Phase2 (Object object_in_radius) inline private
Definition at line 144 of file vicinityitemmanager.c.
    {
        EntityAI entity_ai;
        ItemBase item;
        if ( !Class.CastTo( entity_ai, object_in_radius) )
            return true;
        if ( entity_ai == PlayerBase.Cast(GetGame().GetPlayer()) )
            return true;
        if ( entity_ai.IsParticle() )
            return true;
        if ( entity_ai.IsScriptedLight() )
            return true;
        if ( entity_ai.IsBeingPlaced() )
            return true;
        if ( entity_ai.IsHologram() )
            return true;
        if ( !Class.CastTo( item, object_in_radius) )
            return true;
        if ( !item.IsTakeable() )
            return true;
        return false;
    }
References Class::CastTo(), GetGame(), GetPlayer(), and ItemBase::IsTakeable().
Referenced by RefreshVicinityItems().
ExcludeFromContainer_Phase3()
bool VicinityItemManager::ExcludeFromContainer_Phase3 (Object object_in_cone) inline private
Definition at line 169 of file vicinityitemmanager.c.
    {
        EntityAI entity_ai;
        ItemBase item;
        PlayerBase player = PlayerBase.Cast(GetGame().GetPlayer());
        //Print("---object in cone: " + object_in_cone);
        if ( !Class.CastTo( entity_ai, object_in_cone) )
            return true;
        if ( entity_ai == player )
            return true;
        if ( entity_ai.IsParticle() )
            return true;
        if ( entity_ai.IsScriptedLight() )
            return true;
        if ( entity_ai.IsBeingPlaced() )
            return true;
        if ( entity_ai.IsHologram() )
            return true;
        if ( !Class.CastTo( item, object_in_cone) && !object_in_cone.IsTransport() && !PASBroadcaster.Cast( object_in_cone ) )
            return true;
        if ( item && !item.IsTakeable() )
            return true;
        return false;
    }
References Class::CastTo(), GetGame(), GetPlayer(), and ItemBase::IsTakeable().
Referenced by RefreshVicinityItems().
GetInstance()
static VicinityItemManager VicinityItemManager::GetInstance () inline static private
Definition at line 22 of file vicinityitemmanager.c.
    {
        if (!s_Instance)
            s_Instance = new VicinityItemManager;
        return s_Instance;
    }
References s_Instance.
Referenced by MissionBase::HideInventory(), OnShow(), and VicinityContainer::UpdateInterval().
GetVicinityCargos()
array< CargoBase > VicinityItemManager::GetVicinityCargos () inline private
Definition at line 51 of file vicinityitemmanager.c.
    {
        return m_VicinityCargos;
    }
References m_VicinityCargos.
Referenced by VicinityContainer::UpdateInterval().
GetVicinityItems()
array< EntityAI > VicinityItemManager::GetVicinityItems () inline private
Definition at line 33 of file vicinityitemmanager.c.
    {
        return m_VicinityItems;
    }
References m_VicinityItems.
Referenced by VicinityContainer::UpdateInterval().
Init()
void VicinityItemManager::Init () inline private
Definition at line 29 of file vicinityitemmanager.c.
    {
    }
IsObstructed()
bool VicinityItemManager::IsObstructed (Object filtered_object) inline private
Definition at line 418 of file vicinityitemmanager.c.
    {
        return MiscGameplayFunctions.IsObjectObstructed(filtered_object);
    }
Referenced by RefreshVicinityItems().
RefreshVicinityItems()
void VicinityItemManager::RefreshVicinityItems () inline private
Definition at line 202 of file vicinityitemmanager.c.
    {
        array<Object> objects_in_vicinity = new array<Object>;
        array<CargoBase> proxyCargos = new array<CargoBase>;
        array<Object> filtered_objects = new array<Object>;
        array<Object> allFoundObjects = new array<Object>;
        EntityAI entity_ai;
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        vector playerPosition = player.GetPosition();
        vector playerHeadPos;
        MiscGameplayFunctions.GetHeadBonePos(player,playerHeadPos);
        vector headingDirection = MiscGameplayFunctions.GetHeadingVector( player );
        if ( m_VicinityItems )
        {
            m_VicinityItems.Clear();
        }
        if (m_VicinityCargos)
            m_VicinityCargos.Clear();
        //1. GetAll actors in VICINITY_ACTOR_DISTANCE
//      DebugActorsSphereDraw(VICINITY_ACTOR_DISTANCE);
        GetGame().GetObjectsAtPosition3D( playerPosition, VICINITY_ACTOR_DISTANCE, objects_in_vicinity, proxyCargos );
        // no filtering for cargo (initial implementation)
        for ( int ic = 0; ic < proxyCargos.Count(); ic++ )
            AddVicinityCargos( proxyCargos[ic] );
        //filter unnecessary and duplicate objects beforehand
        for ( int i = 0; i < objects_in_vicinity.Count(); i++ )
        {
            Object actor_in_radius = objects_in_vicinity.Get(i);
            if ( allFoundObjects.Find( actor_in_radius ) == INDEX_NOT_FOUND )
            {
                allFoundObjects.Insert(actor_in_radius);
            }
            if (ExcludeFromContainer_Phase1(actor_in_radius))
                continue;
            if ( filtered_objects.Find( actor_in_radius ) == INDEX_NOT_FOUND )
            {
                filtered_objects.Insert( actor_in_radius );
            }
        }
        if ( objects_in_vicinity )
        {
            //allFoundObjects.InsertAll(objects_in_vicinity);
            objects_in_vicinity.Clear();
        }
        //2. GetAll Objects in VICINITY_DISTANCE
        GetGame().GetObjectsAtPosition3D( playerPosition, VICINITY_DISTANCE, objects_in_vicinity, proxyCargos );
//      DebugObjectsSphereDraw(VICINITY_DISTANCE);
        //filter unnecessary and duplicate objects beforehand
        for ( int j = 0; j < objects_in_vicinity.Count(); j++ )
        {
            Object object_in_radius = objects_in_vicinity.Get(j);
            if ( allFoundObjects.Find( object_in_radius ) == INDEX_NOT_FOUND )
            {
                allFoundObjects.Insert(object_in_radius);
            }
            if (ExcludeFromContainer_Phase2(object_in_radius))
                continue;
            if ( filtered_objects.Find( object_in_radius ) == INDEX_NOT_FOUND )
            {
                filtered_objects.Insert( object_in_radius );
            }
        }
        if ( objects_in_vicinity )
        {
            //allFoundObjects.InsertAll(objects_in_vicinity);
            objects_in_vicinity.Clear();
        }
        //3. Add objects from GetEntitiesInCone
        DayZPlayerUtils.GetEntitiesInCone( playerPosition, headingDirection, VICINITY_CONE_ANGLE, VICINITY_CONE_REACH_DISTANCE, CONE_HEIGHT_MIN, CONE_HEIGHT_MAX, objects_in_vicinity);
//      DebugConeDraw(playerPosition, VICINITY_CONE_ANGLE);
        RaycastRVParams rayInput;
        array<ref RaycastRVResult> raycastResults = new array<ref RaycastRVResult>;
        //filter unnecessary and duplicate objects beforehand
        for ( int k = 0; k < objects_in_vicinity.Count(); k++ )
        {
            Object object_in_cone = objects_in_vicinity.Get(k);
            if ( allFoundObjects.Find( object_in_cone ) == INDEX_NOT_FOUND )
            {
                allFoundObjects.Insert(object_in_cone);
            }
            if (ExcludeFromContainer_Phase3(object_in_cone))
                continue;
            if ( filtered_objects.Find( object_in_cone ) == INDEX_NOT_FOUND )
            {
                //Test distance to closest component first
                rayInput = new RaycastRVParams(playerHeadPos, object_in_cone.GetPosition(), player, 0.1);
                //rayInput.flags = CollisionFlags.ALLOBJECTS;
                DayZPhysics.RaycastRVProxy(rayInput,raycastResults);
                int count = raycastResults.Count();
                for (int d = 0; d < count; d++)
                {
                    if (vector.Distance(raycastResults[d].pos,playerHeadPos) > VICINITY_CONE_REACH_DISTANCE)
                    {
                        continue;
                    }
                    if (raycastResults[d].hierLevel > 0 && raycastResults[d].parent == object_in_cone)
                    {
                        filtered_objects.Insert( object_in_cone );
                    }
                    else if (raycastResults[d].hierLevel == 0 && raycastResults[d].obj == object_in_cone)
                    {
                        filtered_objects.Insert( object_in_cone );
                    }
                }
            }
        }
        //allFoundObjects.InsertAll(objects_in_vicinity);
        //4. Add large objects - particularly buildings and BaseBuildingBase
        BoxCollidingParams params = new BoxCollidingParams();
        vector box = {VICINITY_LARGE_ACTOR_DISTANCE,VICINITY_LARGE_ACTOR_DISTANCE,VICINITY_LARGE_ACTOR_DISTANCE};
        params.SetParams(playerPosition, headingDirection.VectorToAngles(), box * 2, ObjIntersect.View, ObjIntersect.Fire, true);
        array<ref BoxCollidingResult> results = new array<ref BoxCollidingResult>;
        if ( GetGame().IsBoxCollidingGeometryProxy(params, {player}, results) )
        {
            Object obstruction;
            foreach (BoxCollidingResult bResult : results)
            {
                obstruction = null;
                if ( bResult.obj && (bResult.obj.CanObstruct() || bResult.obj.CanProxyObstruct()) )
                {
                    obstruction = bResult.obj;
                    if ( allFoundObjects.Find( obstruction ) == INDEX_NOT_FOUND )
                    {
                        allFoundObjects.Insert(obstruction);
                    }
                }
                if ( bResult.parent && (bResult.parent.CanObstruct() || bResult.parent.CanProxyObstruct()) )
                {
                    obstruction = bResult.parent;
                    if ( allFoundObjects.Find( obstruction ) == INDEX_NOT_FOUND )
                    {
                        allFoundObjects.Insert(obstruction);
                    }
                }
            }
        }
        //5. Filter filtered objects with RayCast from the player ( head bone )
        array<Object> obstructingObjects = new array<Object>;
        MiscGameplayFunctions.FilterObstructingObjects(allFoundObjects, obstructingObjects);
        if ( obstructingObjects.Count() > 0 )
        {
            if ( filtered_objects.Count() > 10 )
            {
                vector rayStart;
                MiscGameplayFunctions.GetHeadBonePos( PlayerBase.Cast( GetGame().GetPlayer() ), rayStart);
                array<Object> filteredObjects = new array<Object>;
                MiscGameplayFunctions.FilterObstructedObjectsByGrouping( rayStart, VICINITY_CONE_DISTANCE, 0.3, filtered_objects, obstructingObjects, filteredObjects, true, true, VICINITY_CONE_REACH_DISTANCE);
                for ( int n = 0; n < filteredObjects.Count(); ++n )
                    AddVicinityItems( filteredObjects[n] );
            }
            else
            {
                for ( int l = 0; l < filtered_objects.Count(); l++ )
                {
                    Object filtered_object = filtered_objects.Get(l);
                    bool is_obstructed = false;
                    Class.CastTo( entity_ai, filtered_object );
                    //distance check
                    if ( vector.DistanceSq( playerPosition, entity_ai.GetPosition() ) > VICINITY_CONE_REACH_DISTANCE * VICINITY_CONE_REACH_DISTANCE )
                    {
                        if ( !CanIgnoreDistanceCheck( entity_ai ) )
{
                            continue;
                        }
                    }
                    is_obstructed = IsObstructed(filtered_object);
                    if ( !is_obstructed )
                    {
                        AddVicinityItems( filtered_object );
                    }
                }
            }
        }
        else
        {
            for ( int m = 0; m < filtered_objects.Count(); m++ )
            {
                AddVicinityItems( filtered_objects[m] );
            }
        }
    }
References AddVicinityCargos(), AddVicinityItems(), CanIgnoreDistanceCheck(), Class::CastTo(), CONE_HEIGHT_MAX, CONE_HEIGHT_MIN, vector::Distance(), vector::DistanceSq(), ExcludeFromContainer_Phase1(), ExcludeFromContainer_Phase2(), ExcludeFromContainer_Phase3(), DayZPlayerUtils::GetEntitiesInCone(), GetGame(), CGame::GetObjectsAtPosition3D(), GetPlayer(), INDEX_NOT_FOUND, IsObstructed(), m_VicinityCargos, m_VicinityItems, DayZPhysics::RaycastRVProxy(), BoxCollidingParams::SetParams(), vector::VectorToAngles(), VICINITY_ACTOR_DISTANCE, VICINITY_CONE_ANGLE, VICINITY_CONE_DISTANCE, VICINITY_CONE_REACH_DISTANCE, VICINITY_DISTANCE, and VICINITY_LARGE_ACTOR_DISTANCE.
Referenced by OnShow(), and Update().
ResetRefreshCounter()
void VicinityItemManager::ResetRefreshCounter () inline private
Definition at line 64 of file vicinityitemmanager.c.
    {
        m_RefreshCounter = 0;
    }
References m_RefreshCounter.
Referenced by MissionBase::HideInventory().
Update()
void VicinityItemManager::Update (float delta_time) inline private
Definition at line 70 of file vicinityitemmanager.c.
    {
        m_RefreshCounter += delta_time;
        //Call RefreshVicinityItems() every UPDATE_FREQUENCY seconds
        if ( m_RefreshCounter >= UPDATE_FREQUENCY )
        {
            RefreshVicinityItems();
            //Print("*---------------------*Refreshing vicinity*---------------------*");
            m_RefreshCounter = 0;
        }
    }
References m_RefreshCounter, RefreshVicinityItems(), and UPDATE_FREQUENCY.
Referenced by VicinityContainer::UpdateInterval().
Member Data Documentation
CE_CENTER
private const string VicinityItemManager::CE_CENTER = "ce_center" private
Definition at line 11 of file vicinityitemmanager.c.
CONE_HEIGHT_MAX
private const float VicinityItemManager::CONE_HEIGHT_MAX = 3.0 private
Definition at line 15 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
CONE_HEIGHT_MIN
private const float VicinityItemManager::CONE_HEIGHT_MIN = -0.5 private
Definition at line 14 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
HEIGHT_OFFSET
private const float VicinityItemManager::HEIGHT_OFFSET = 0.2 private
Definition at line 12 of file vicinityitemmanager.c.
m_RefreshCounter
private float VicinityItemManager::m_RefreshCounter private
Definition at line 19 of file vicinityitemmanager.c.
Referenced by ResetRefreshCounter(), and Update().
m_VicinityCargos
private ref array<CargoBase> VicinityItemManager::m_VicinityCargos = new array<CargoBase> private
Definition at line 18 of file vicinityitemmanager.c.
Referenced by AddVicinityCargos(), GetVicinityCargos(), and RefreshVicinityItems().
m_VicinityItems
private ref array<EntityAI> VicinityItemManager::m_VicinityItems = new array<EntityAI> private
Definition at line 17 of file vicinityitemmanager.c.
Referenced by AddVicinityItems(), GetVicinityItems(), and RefreshVicinityItems().
OBJECT_OBSTRUCTION_WEIGHT
private const int VicinityItemManager::OBJECT_OBSTRUCTION_WEIGHT = 10000 private
Definition at line 13 of file vicinityitemmanager.c.
rayShapes
ref array<Shape> VicinityItemManager::rayShapes = new array<Shape>() private
Definition at line 425 of file vicinityitemmanager.c.
Referenced by DebugActorsSphereDraw(), DebugConeDraw(), DebugObjectsSphereDraw(), and DebugRaycastDraw().
s_Instance
private ref VicinityItemManager VicinityItemManager::s_Instance static private
Definition at line 20 of file vicinityitemmanager.c.
Referenced by GetInstance().
UPDATE_FREQUENCY
private const float VicinityItemManager::UPDATE_FREQUENCY = 0.25 private
Definition at line 3 of file vicinityitemmanager.c.
Referenced by Update().
VICINITY_ACTOR_DISTANCE
private const float VicinityItemManager::VICINITY_ACTOR_DISTANCE = 2.0 private
Definition at line 5 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_ANGLE
private const float VicinityItemManager::VICINITY_CONE_ANGLE = 30 private
Definition at line 9 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_DISTANCE
private const float VicinityItemManager::VICINITY_CONE_DISTANCE = 2.0 private
Definition at line 7 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
VICINITY_CONE_RADIANS
private const float VicinityItemManager::VICINITY_CONE_RADIANS = 0.5 private
Definition at line 10 of file vicinityitemmanager.c.
VICINITY_CONE_REACH_DISTANCE
private const float VicinityItemManager::VICINITY_CONE_REACH_DISTANCE = 2.0 private
Definition at line 8 of file vicinityitemmanager.c.
Referenced by AddVicinityItems(), DebugConeDraw(), and RefreshVicinityItems().
VICINITY_DISTANCE
private const float VicinityItemManager::VICINITY_DISTANCE = 0.5 private
Definition at line 4 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().
VICINITY_LARGE_ACTOR_DISTANCE
private const float VicinityItemManager::VICINITY_LARGE_ACTOR_DISTANCE = 3.0 private
Definition at line 6 of file vicinityitemmanager.c.
Referenced by RefreshVicinityItems().