DayzKode: LoadingScreen Class Reference
LoadingScreen Class Reference
Private Member Functions
void Dec ()
void EndLoading ()
void Hide (bool force)
void Inc ()
bool IsLoading ()
void LoadingScreen (DayZGame game)
void OnTimer ()
void OnUpdate (float timeslice)
void SetProgress (float val)
void SetStatus (string status)
void SetTitle (string title)
void Show ()
Private Attributes
int m_Counter
DayZGame m_DayZGame
ImageWidget m_ImageBackground
ImageWidget m_ImageLoadingIcon
float m_ImageLoadingIconRotation
ImageWidget m_ImageLogoCorner
ImageWidget m_ImageLogoMid
ImageWidget m_ImageWidgetBackground
float m_LastProgressUpdate
TextWidget m_ModdedWarning
ProgressBarWidget m_ProgressLoading
TextWidget m_ProgressText
TextWidget m_TextWidgetStatus
TextWidget m_TextWidgetTitle
ref Timer m_Timer
ref Widget m_WidgetRoot
Detailed Description
Definition at line 266 of file dayzgame.c.
Constructor & Destructor Documentation
LoadingScreen()
void LoadingScreen::LoadingScreen (DayZGame game) inline private
Definition at line 294 of file dayzgame.c.
    {
        m_DayZGame = game;
        m_WidgetRoot = game.GetLoadingWorkspace().CreateWidgets("gui/layouts/loading.layout");
        //m_FrameWidgetSmall = m_WidgetRoot.FindAnyWidget("ProgressBarFrameSmall");
        //m_FrameWidgetLarge = m_WidgetRoot.FindAnyWidget("ProgressBarFrameLarge");
        //Class.CastTo(m_ProgressBarSmall, m_WidgetRoot.FindAnyWidget("ProgressBarWidgetSmall"));
        //Class.CastTo(m_ProgressBarLarge, m_WidgetRoot.FindAnyWidget("ProgressBarWidgetLarge"));
        Class.CastTo(m_ImageLogoMid, m_WidgetRoot.FindAnyWidget("ImageLogoMid"));
        Class.CastTo(m_ImageLogoCorner, m_WidgetRoot.FindAnyWidget("ImageLogoCorner"));
        Class.CastTo(m_TextWidgetTitle, m_WidgetRoot.FindAnyWidget("TextWidget"));
        Class.CastTo(m_TextWidgetStatus, m_WidgetRoot.FindAnyWidget("StatusText"));
        Class.CastTo(m_ImageWidgetBackground, m_WidgetRoot.FindAnyWidget("ImageBackground"));
        Class.CastTo(m_ImageLoadingIcon, m_WidgetRoot.FindAnyWidget("ImageLoadingIcon"));
        Class.CastTo(m_ModdedWarning, m_WidgetRoot.FindAnyWidget("ModdedWarning"));
        m_ImageBackground = ImageWidget.Cast( m_WidgetRoot.FindAnyWidget("ImageBackground") );
        m_ProgressLoading = ProgressBarWidget.Cast( m_WidgetRoot.FindAnyWidget("LoadingBar") );
        string tmp;
        m_ProgressText = TextWidget.Cast(m_WidgetRoot.FindAnyWidget("ProgressText"));
        if (GetGame())
        {
            m_ProgressText.Show( GetGame().CommandlineGetParam("loadingTest", tmp) );
        }
        m_WidgetRoot.FindAnyWidget("notification_root").Show(false);
        #ifdef PLATFORM_CONSOLE
        #ifdef PLATFORM_XBOX
        #ifdef BUILD_EXPERIMENTAL
            Widget exp_notifiaction = m_WidgetRoot.FindAnyWidget("notification_root");
            if (exp_notifiaction)
            {
                exp_notifiaction.Show(true);
            }
        #endif
        #endif
        #endif
        m_ModdedWarning.Show( g_Game.ReportModded() );
        m_ImageLogoMid.Show(true);
        m_ImageLogoCorner.Show(false);
        //m_ImageLoadingIcon.Show(true);
        //m_ProgressText.Show(true);
        //m_ProgressBar = m_ProgressBarLarge;
        //m_ProgressBar.SetCurrent(0);
        //m_FrameWidgetSmall.Show( false );
        //m_ImageWidgetBackground.LoadImageFile( 0, GetRandomLoadingBackground() );
        m_ImageWidgetBackground.Show( true );
        m_Counter = 0;
        // lighten up your desktop
        game.GetBacklit().LoadingAnim();
        ProgressAsync.SetProgressData(m_ProgressLoading);
        ProgressAsync.SetUserData(m_ImageBackground);
    }
References Class::CastTo(), g_Game, GetGame(), m_Counter, m_DayZGame, m_ImageBackground, m_ImageLoadingIcon, m_ImageLogoCorner, m_ImageLogoMid, m_ImageWidgetBackground, m_ModdedWarning, m_ProgressLoading, m_ProgressText, m_TextWidgetStatus, m_TextWidgetTitle, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Member Function Documentation
Dec()
void LoadingScreen::Dec () inline private
Definition at line 381 of file dayzgame.c.
    {
        m_Counter = m_Counter - 1;
        if ( m_Counter <= 0 )
        {
            m_Counter = 0;
            if ( m_Timer )
            {
                delete m_Timer;
            }
            /*
            m_Timer = new Timer();
            m_Timer.Run(2, this,"EndLoading", NULL, false);
            */
            EndLoading();
        }
    }
References EndLoading(), m_Counter, and m_Timer.
Referenced by Hide(), and LoadProgressUpdate().
EndLoading()
void LoadingScreen::EndLoading () inline private
Definition at line 402 of file dayzgame.c.
    {
        ProgressAsync.SetProgressData(null);
        ProgressAsync.SetUserData(null);
        m_WidgetRoot.Show( false );
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call( g_Game.CheckDialogs );
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, g_Game, CGame::GetCallQueue(), GetGame(), m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by Dec().
Hide()
void LoadingScreen::Hide (bool force) inline private
Definition at line 516 of file dayzgame.c.
    {
        if (force)
        {
            while (m_Counter > 0)
            {
                Dec();
            }
        }
        if ( m_Counter <= 0 /*&& m_WidgetRoot.IsVisible()*/ )
        {
            m_WidgetRoot.Show( false );
            //Print("***** m_WidgetRoot.Show false");
            ProgressAsync.SetUserData(null);
            ProgressAsync.SetProgressData(null);
        }
    }
References Dec(), m_Counter, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by LoadingHide().
Inc()
void LoadingScreen::Inc () inline private
Definition at line 369 of file dayzgame.c.
    {
        m_LastProgressUpdate = m_DayZGame.GetTickTime();
        m_Counter++;
        //Print("Loading Inc: "+ m_Counter);
        if ( m_Counter == 1 )
        {
            Show();
        }
    }
References m_Counter, m_DayZGame, m_LastProgressUpdate, and Show().
Referenced by LoadProgressUpdate().
IsLoading()
bool LoadingScreen::IsLoading () inline private
Definition at line 410 of file dayzgame.c.
    {
        if ( m_WidgetRoot.IsVisible() )
        {
            return true;
        }
        return false;
    }
References m_WidgetRoot.
Referenced by CheckDialogs(), IsLoading(), and OnUpdate().
OnTimer()
void LoadingScreen::OnTimer () inline private
Definition at line 357 of file dayzgame.c.
    {
        if ( GetGame() )
        {
            Print("Loading Update: "+ GetGame().GetTickTime());
        }
        else
        {
            Print("Loading Update...");
        }
    }
References GetGame(), and Print().
OnUpdate()
void LoadingScreen::OnUpdate (float timeslice) inline private
Definition at line 463 of file dayzgame.c.
    {
    }
Referenced by OnUpdate().
SetProgress()
void LoadingScreen::SetProgress (float val) inline private
Definition at line 441 of file dayzgame.c.
    {
        //m_ProgressText.SetText(val.ToString() + " %");
        float time_delta = m_DayZGame.GetTickTime() - m_LastProgressUpdate;
        //m_ProgressLoading.SetCurrent( val * 100 );
        //m_ImageBackground.SetMaskProgress( val );
//Print("SetProgress delta: "+ time_delta);
        if ( m_Counter > 0 )
        {
            //m_ImageLoadingIconRotation += 15;
            //m_ImageLoadingIcon.SetRotation(0, 0, m_ImageLoadingIconRotation);
            //m_ProgressBar.SetCurrent( val * 100 );
        }
        m_LastProgressUpdate = m_DayZGame.GetTickTime();
    }
References m_Counter, m_DayZGame, and m_LastProgressUpdate.
Referenced by LoadProgressUpdate().
SetStatus()
void LoadingScreen::SetStatus (string status) inline private
Definition at line 436 of file dayzgame.c.
    {
        m_TextWidgetStatus.SetText( status );
    }
References m_TextWidgetStatus.
Referenced by OnEvent().
SetTitle()
void LoadingScreen::SetTitle (string title) inline private
Definition at line 420 of file dayzgame.c.
    {
        m_TextWidgetTitle.SetText( title );
    }
References m_TextWidgetTitle.
Referenced by LoadProgressUpdate().
Show()
void LoadingScreen::Show () inline private
Definition at line 468 of file dayzgame.c.
    {
        Widget lIcon = m_ImageBackground;
        Widget pText = m_ProgressLoading;
        m_ProgressText.SetText("");
        m_ProgressLoading.SetCurrent( 0.0 );
        m_ImageBackground.SetMaskProgress( 0.0 );
        if ( !m_WidgetRoot.IsVisible() )
        {
            if ( m_DayZGame.GetUIManager().IsDialogVisible() )
            {
                m_DayZGame.GetUIManager().HideDialog();
            }
            if ( m_DayZGame.GetMissionState() == DayZGame.MISSION_STATE_MAINMENU )
            {
                //m_ProgressBar = m_ProgressBarSmall;
                m_ImageLogoMid.Show(false);
                m_ImageLogoCorner.Show(false);
                //m_FrameWidgetSmall.Show( true );
                //m_FrameWidgetLarge.Show( false );
                m_ImageWidgetBackground.Show( true );
                m_TextWidgetStatus.Show(true);
                //lIcon = null;
                //pText = null;
            }
            else
            {
                //m_ProgressBar = m_ProgressBarLarge;
                m_ImageLogoMid.Show(true);
                m_ImageLogoCorner.Show(false);
                //m_FrameWidgetSmall.Show( false );
                //m_FrameWidgetLarge.Show( true );
                m_ImageWidgetBackground.Show( true );
                m_TextWidgetStatus.Show(false);
            }
            m_WidgetRoot.Show( true );
            //m_ProgressBar.SetCurrent( 0 );
            m_TextWidgetTitle.SetText( "" );
            m_TextWidgetStatus.SetText( "" );
        }
        ProgressAsync.SetProgressData(pText);
        ProgressAsync.SetUserData(lIcon);
    }
References DayZGame(), m_DayZGame, m_ImageBackground, m_ImageLogoCorner, m_ImageLogoMid, m_ImageWidgetBackground, m_ProgressLoading, m_ProgressText, m_TextWidgetStatus, m_TextWidgetTitle, m_WidgetRoot, ProgressAsync::SetProgressData(), and ProgressAsync::SetUserData().
Referenced by DayZGame(), Inc(), and LoadingShow().
Member Data Documentation
m_Counter
int LoadingScreen::m_Counter private
Definition at line 291 of file dayzgame.c.
Referenced by Dec(), Hide(), Inc(), LoadingScreen(), and SetProgress().
m_DayZGame
DayZGame LoadingScreen::m_DayZGame private
Definition at line 278 of file dayzgame.c.
Referenced by Inc(), LoadingScreen(), SetProgress(), and Show().
m_ImageBackground
ImageWidget LoadingScreen::m_ImageBackground private
Definition at line 284 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_ImageLoadingIcon
ImageWidget LoadingScreen::m_ImageLoadingIcon private
Definition at line 283 of file dayzgame.c.
Referenced by LoadingScreen().
m_ImageLoadingIconRotation
float LoadingScreen::m_ImageLoadingIconRotation private
Definition at line 286 of file dayzgame.c.
m_ImageLogoCorner
ImageWidget LoadingScreen::m_ImageLogoCorner private
Definition at line 282 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_ImageLogoMid
ImageWidget LoadingScreen::m_ImageLogoMid private
Definition at line 281 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_ImageWidgetBackground
ImageWidget LoadingScreen::m_ImageWidgetBackground private
Definition at line 277 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_LastProgressUpdate
float LoadingScreen::m_LastProgressUpdate private
Definition at line 279 of file dayzgame.c.
Referenced by Inc(), and SetProgress().
m_ModdedWarning
TextWidget LoadingScreen::m_ModdedWarning private
Definition at line 276 of file dayzgame.c.
Referenced by LoadingScreen().
m_ProgressLoading
ProgressBarWidget LoadingScreen::m_ProgressLoading private
Definition at line 285 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_ProgressText
TextWidget LoadingScreen::m_ProgressText private
Definition at line 287 of file dayzgame.c.
Referenced by LoadingScreen(), and Show().
m_TextWidgetStatus
TextWidget LoadingScreen::m_TextWidgetStatus private
Definition at line 275 of file dayzgame.c.
Referenced by LoadingScreen(), SetStatus(), and Show().
m_TextWidgetTitle
TextWidget LoadingScreen::m_TextWidgetTitle private
Definition at line 274 of file dayzgame.c.
Referenced by LoadingScreen(), SetTitle(), and Show().
m_Timer
ref Timer LoadingScreen::m_Timer private
Definition at line 292 of file dayzgame.c.
Referenced by Dec().
m_WidgetRoot
ref Widget LoadingScreen::m_WidgetRoot private
Definition at line 268 of file dayzgame.c.
Referenced by EndLoading(), Hide(), IsLoading(), LoadingScreen(), and Show().