DayzKode: OptionSelector Class Reference
OptionSelector Class Reference
Private Member Functions
bool CanSwitch ()
int GetValue ()
void LoadNewValues (notnull array< string > options, int current_index)
void OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options)
void PerformSetOption (int index)
void SetCanSwitch (bool value)
override void SetNextOption ()
override void SetPrevOption ()
void SetRandomValue ()
override void SetStringOption (string option, bool fire_event=true)
void SetValue (int value, bool fire_event=true)
void SetValue (string value, bool fire_event=true)
Private Attributes
protected bool m_CanSwitch
Detailed Description
Definition at line 1 of file optionselectormultistate.c.
Member Function Documentation
CanSwitch()
bool OptionSelector::CanSwitch () inline private
Definition at line 93 of file optionselectormultistate.c.
    {
        return m_CanSwitch;
    }
References m_CanSwitch.
GetValue()
int OptionSelector::GetValue () inline private
Definition at line 128 of file optionselectormultistate.c.
    {
        return m_SelectedOptionIndex;
    }
LoadNewValues()
void OptionSelector::LoadNewValues (notnull array< string > options, int current_index) inline private
Definition at line 40 of file optionselectormultistate.c.
    {
        m_Options = options;
        SetValue( current_index );
    }
References SetValue().
OptionSelectorMultistate()
void OptionSelector::OptionSelectorMultistate (Widget parent, int current_index, ScriptedWidgetEventHandler parent_c, bool disabled, notnull array< string > options) inline private
Definition at line 5 of file optionselectormultistate.c.
    {
        m_CanSwitch = true;
        m_SelectorType              = 2;
        m_Options                   = options;
        if( options.Count() == 0 )
        {
            Error( "Invalid OptionSelectorMultistate options" );
        }
        if( current_index < 0 || current_index >= m_Options.Count() )
        {
            m_SelectedOptionIndex = 0;
        }
        else
        {
            m_SelectedOptionIndex = current_index;
        }
        /*
        //handled in the 'OptionSelector'
        m_Enabled = !disabled;
        if( m_Enabled )
        {
            Enable();
        }
        else
        {
            Disable();
        }*/
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
    }
References Error().
PerformSetOption()
void OptionSelector::PerformSetOption (int index) inline private
Definition at line 81 of file optionselectormultistate.c.
    {
        m_SelectedOptionIndex = index;
        m_SelectedOption.SetText( m_Options.Get( index ) );
        m_OptionChanged.Invoke( index );
    }
Referenced by SetNextOption(), and SetPrevOption().
SetCanSwitch()
void OptionSelector::SetCanSwitch (bool value) inline private
Definition at line 88 of file optionselectormultistate.c.
    {
        m_CanSwitch = value;
    }
SetNextOption()
override void OptionSelector::SetNextOption () inline private
Definition at line 46 of file optionselectormultistate.c.
    {
        int idx = m_SelectedOptionIndex;
        idx++;
        if( idx >= m_Options.Count() )
        {
            idx = 0;
        }
        m_AttemptOptionChange.Invoke(idx);
        if (m_CanSwitch)
        {
            //m_SelectedOptionIndex = idx;
            PerformSetOption(idx);
        }
    }
References PerformSetOption().
Referenced by OptionSelectorBase::OnClick(), and OptionSelectorBase::OnMouseButtonUp().
SetPrevOption()
override void OptionSelector::SetPrevOption () inline private
Definition at line 63 of file optionselectormultistate.c.
    {
        int idx = m_SelectedOptionIndex;
        idx--;
        if( idx < 0 )
        {
            idx = m_Options.Count() - 1;
        }
        m_AttemptOptionChange.Invoke(idx);
        if (m_CanSwitch)
        {
            //m_SelectedOptionIndex = idx;
            PerformSetOption(idx);
        }
    }
References PerformSetOption().
Referenced by OptionSelectorBase::OnMouseButtonUp().
SetRandomValue()
void OptionSelector::SetRandomValue () inline private
Definition at line 121 of file optionselectormultistate.c.
    {
        m_SelectedOptionIndex = Math.RandomInt( 0, m_Options.Count() );
        m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
        m_OptionChanged.Invoke( m_SelectedOptionIndex );
    }
References Math::RandomInt().
SetStringOption()
override void OptionSelector::SetStringOption (string option, bool fire_event = true) inline private
Definition at line 133 of file optionselectormultistate.c.
    {
        int index = m_Options.Find( option );
        if( index > -1 )
        {
            m_SelectedOptionIndex = index;
            m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
            if( fire_event )
                m_OptionChanged.Invoke( m_SelectedOptionIndex );
        }
    }
SetValue() [1/2]
void OptionSelector::SetValue (int value, bool fire_event = true) inline private
Definition at line 98 of file optionselectormultistate.c.
    {
        if( value < m_Options.Count() && value >= 0 )
        {
            m_SelectedOptionIndex = value;
            m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
            if( fire_event )
                m_OptionChanged.Invoke( m_SelectedOptionIndex );
        }
    }
Referenced by LoadNewValues().
SetValue() [2/2]
void OptionSelector::SetValue (string value, bool fire_event = true) inline private
Definition at line 109 of file optionselectormultistate.c.
    {
        int index = m_Options.Find( value );
        if( index >= 0 )
        {
            m_SelectedOptionIndex = index;
            m_SelectedOption.SetText( m_Options.Get( m_SelectedOptionIndex ) );
            if( fire_event )
                m_OptionChanged.Invoke( m_SelectedOptionIndex );
        }
    }
Member Data Documentation
m_CanSwitch
protected bool OptionSelector::m_CanSwitch private
Definition at line 3 of file optionselectormultistate.c.
Referenced by CanSwitch().