DayzKode: VicinityObjects Class Reference
VicinityObjects Class Reference
objects in vicinity - extended with secondary object which is parent of that Object
Private Member Functions
void ClearVicinityObjects ()
int Count ()
Object GetObject (int i)
returns VicinityObjects Key
Object GetParent (int i)
returns VicinityObjects Element
array< Object > GetRawVicinityObjects ()
return simple array of Objects in Vicinity
array< Object > GetVicinityObjects ()
return simple array of Objects in Vicinity
void Remove (array< Object > objects)
void Remove (Object object)
void StoreVicinityObject (Object object, Object parent=null)
stores VicinityObject to Hashmap - for storing of parent/child relationship
void TransformToVicinityObjects (array< Object > objects)
transform simple array of Objects to VicinityObjects hashmap
void VicinityObjects ()
Private Attributes
private ref map< Object, Object > m_VicinityObjects
Detailed Description
objects in vicinity - extended with secondary object which is parent of that Object
Definition at line 2 of file actiontargets.c.
Constructor & Destructor Documentation
VicinityObjects()
void VicinityObjects::VicinityObjects () inline private
Definition at line 6 of file actiontargets.c.
    {
        m_VicinityObjects = new map<Object, Object>;
    }
References m_VicinityObjects.
Member Function Documentation
ClearVicinityObjects()
void VicinityObjects::ClearVicinityObjects () inline private
Definition at line 46 of file actiontargets.c.
    {
        m_VicinityObjects.Clear();
    }
References m_VicinityObjects.
Count()
int VicinityObjects::Count () inline private
Definition at line 92 of file actiontargets.c.
    {
        return m_VicinityObjects.Count();
    }
References m_VicinityObjects.
GetObject()
Object VicinityObjects::GetObject (int i) inline private
returns VicinityObjects Key
Definition at line 81 of file actiontargets.c.
    {
        return m_VicinityObjects.GetKey(i);
    }
References m_VicinityObjects.
GetParent()
Object VicinityObjects::GetParent (int i) inline private
returns VicinityObjects Element
Definition at line 87 of file actiontargets.c.
    {
        return m_VicinityObjects.GetElement(i);
    }
References m_VicinityObjects.
GetRawVicinityObjects()
array< Object > VicinityObjects::GetRawVicinityObjects () inline private
return simple array of Objects in Vicinity
Definition at line 69 of file actiontargets.c.
    {
        ref array<Object> vicinityObjects = new array<Object>;
        for (int i = 0; i < m_VicinityObjects.Count(); i++)
        {
            vicinityObjects.Insert(GetObject(i));
        }
        return vicinityObjects;
    }
References GetObject(), and m_VicinityObjects.
GetVicinityObjects()
array< Object > VicinityObjects::GetVicinityObjects () inline private
return simple array of Objects in Vicinity
filters out non-takeable items (won't be shown in vicinity)
Definition at line 52 of file actiontargets.c.
    {
        ref array<Object> vicinityObjects = new array<Object>;
        for (int i = 0; i < m_VicinityObjects.Count(); i++)
        {
            ItemBase ib = ItemBase.Cast(GetObject(i));
            if (ib && !ib.IsTakeable())
                continue;
            vicinityObjects.Insert(GetObject(i));
        }
        return vicinityObjects;
    }
References GetObject(), ItemBase::IsTakeable(), and m_VicinityObjects.
Remove() [1/2]
void VicinityObjects::Remove (array< Object > objects) inline private
Definition at line 102 of file actiontargets.c.
    {
        for (int i = 0; i < objects.Count(); i++)
        {
            m_VicinityObjects.Remove(objects[i]);
        }
    }
References m_VicinityObjects.
Remove() [2/2]
void VicinityObjects::Remove (Object object) inline private
Definition at line 97 of file actiontargets.c.
    {
        m_VicinityObjects.Remove(object);
    }
References m_VicinityObjects.
StoreVicinityObject()
void VicinityObjects::StoreVicinityObject (Object object, Object parent = null) inline private
stores VicinityObject to Hashmap - for storing of parent/child relationship
completely remove items that are being placed or are holograms
ignores plain objects
init of VicinityObjects - object, parent(if exists)
Definition at line 12 of file actiontargets.c.
    {
        ItemBase ib = ItemBase.Cast(object);
        if (ib && (ib.IsBeingPlaced() || ib.IsHologram()))
            return;
        /*if(object && object.IsPlainObject())
        {
            Print("ERROR: VicinityObjects | StoreVicinityObject | IsPlainObject check fail");
            return;
        }*/
        if ( !m_VicinityObjects.Contains(object) )
        {
            m_VicinityObjects.Set(object, parent);
        }
    }
References m_VicinityObjects.
Referenced by TransformToVicinityObjects().
TransformToVicinityObjects()
void VicinityObjects::TransformToVicinityObjects (array< Object > objects) inline private
transform simple array of Objects to VicinityObjects hashmap
Definition at line 34 of file actiontargets.c.
    {
        for (int i = 0; i < objects.Count(); i++)
        {
            if (objects[i].GetType() != "")
            {
                StoreVicinityObject(objects[i]);
                //Print("storing, 2nd pass: " + objects[i]);
            }
        }
    }
References GetType(), and StoreVicinityObject().
Member Data Documentation
m_VicinityObjects
private ref map<Object, Object> VicinityObjects::m_VicinityObjects private
Definition at line 4 of file actiontargets.c.
Referenced by ClearVicinityObjects(), Count(), GetObject(), GetParent(), GetRawVicinityObjects(), GetVicinityObjects(), Remove(), StoreVicinityObject(), and VicinityObjects().