DayzKode: BotStateBase Class Reference
BotStateBase Class Reference
represent weapon state base
Private Member Functions
void AddTransition (FSMTransition< BotStateBase, BotEventBase, BotActionBase, BotGuardBase > t)
adds transition into m_FSM transition table
void Bot_TestSpawnOpen (Bot bot=NULL, BotStateBase parent=NULL, string new_type="")
void BotHunt (Bot bot=NULL, BotStateBase parent=NULL)
void BotSpawnEntityInHands (Bot bot=NULL, BotStateBase parent=NULL, string new_type="")
void BotStateBase (Bot bot=NULL, BotStateBase parent=NULL)
nested state machine (or null)
void BotTestAttachAndDropCycle (Bot bot=NULL, BotStateBase parent=NULL)
void BotTestItemMoveBackAndForth (Bot bot=NULL, BotStateBase parent=NULL)
void BotTimedWait (Bot bot=NULL, BotStateBase parent=NULL, float timeout=3.0)
BotFSM GetFSM ()
int GetNextSlot (int curr)
BotStateBase GetParentState ()
PlayerBase GetPlayerOwner ()
bool HasFSM ()
bool IsIdle ()
idle state does not expect any animation events
bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
override void OnAbort (BotEventBase e)
void OnAbort (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
override void OnEntry (BotEventBase e)
void OnEntry (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
override void OnExit (BotEventBase e)
void OnExit (BotEventBase e)
void OnStateChanged (BotStateBase src, BotStateBase dst)
called on current state when state machine has changed its state
void OnSubMachineChanged (BotStateBase src, BotStateBase dst)
called when sub-machine has changed its state
void OnTimeout ()
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
override void OnUpdate (float dt)
void OnUpdate (float dt)
bool ProcessEvent (BotEventBase e)
void SelectTarget ()
void SetParentState (BotStateBase parent)
allows construction of hierarchical state machine
Private Attributes
ref BotTestAttachAndDropCycle_Attaching m_Attaching
Bot m_Bot
man that this state belongs to
ref BotTestAttachAndDropCycle_Detaching m_Detaching
float m_dtAccumulator = 0.0
protected float m_dtAccumulator = 0.0
EntityAI m_Entity
ref BotFSM m_FSM
hierarchical parent state of this state (or null)
int m_hgSlot = InventorySlots.GetSlotIdFromString("Headgear")
ref BotHunt_Hunting m_Hunting
ref BotTestItemMoveBackAndForth_MoveFromSlotToSlot m_Move
int m_mskSlot = InventorySlots.GetSlotIdFromString("Mask")
ref BotOpenEntityInHands m_Opening
PlayerBase m_Owner
BotStateBase m_ParentState
bot that this state belongs to
protected bool m_Periodic = true
ref BotSpawnEntityInHands m_Spawning
Man m_Target
EntityAI m_Target
bool m_TargetInSight = false
bool m_TargetLost = false
protected float m_Timeout = 3.0
ref BotHunt_Tracking m_Tracking
bool m_Tracking = true
string m_Type
int m_WaitingForSlot = InventorySlots.INVALID
Detailed Description
represent weapon state base
Class comes with entry/update/exit hooks that can be overriden in custom states
Class is ready for hierarchic composition, i.e. this state having a sub-machine running under hood. If no m_FSM member is configured, class acts as ordinary plain finite machine state.
Definition at line 15 of file bot_hunt.c.
Constructor & Destructor Documentation
BotStateBase()
void BotStateBase::BotStateBase (Bot bot = NULL, BotStateBase parent = NULL) inline private
nested state machine (or null)
Definition at line 17 of file botstates.c.
{ m_Bot = bot; m_Owner = bot.m_Owner; m_ParentState = parent; }
References m_Bot, m_Owner, and m_ParentState.
Member Function Documentation
AddTransition()
BotStateBase::AddTransition (FSMTransition< BotStateBase, BotEventBase, BotActionBase, BotGuardBase > t) inline private
adds transition into m_FSM transition table
Definition at line 43 of file botstates.c.
    {
        if (HasFSM())
            m_FSM.AddTransition(t);
        else
            Error("[botfsm] adding transition to state without FSM. Configure FSM first.");
    }
References Error(), HasFSM(), and m_FSM.
Bot_TestSpawnOpen()
void BotStateBase::Bot_TestSpawnOpen (Bot bot = NULL, BotStateBase parent = NULL, string new_type = "") inline private
Definition at line 99 of file bot_testspawnandopencan.c.
    {
        m_Type = new_type;
        // setup nested state machine
        m_FSM = new BotFSM(this); // @NOTE: set owner of the submachine fsm
        m_Spawning = new BotSpawnEntityInHands(m_Bot, this);
        m_Opening = new BotOpenEntityInHands(m_Bot, this);
        // events
        BotEventBase __EntInH__ = new BotEventEntityInHands;
        // transitions
        m_FSM.AddTransition(new BotTransition(   m_Spawning,  __EntInH__, m_Opening));
        //m_FSM.AddTransition(new BotTransition(   m_Opening,   __EntAtt__, m_Eating));
        //m_FSM.AddTransition(new BotTransition(   m_Eating,   __EntAtt__, m_Eating));
        m_FSM.SetInitialState(m_Spawning);
    }
References m_Type.
BotHunt()
void BotStateBase::BotHunt (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 23 of file bot_hunt.c.
    {
        // setup nested state machine
        m_FSM = new BotFSM(this); // @NOTE: set owner of the submachine fsm
        m_Tracking = new BotHunt_Tracking(m_Bot, this);
        m_Hunting = new BotHunt_Hunting(m_Bot, this);
        // events
        BotEventBase __InSight__ = new BotEventHuntedTargetInSight;
        BotEventBase __Lost__ = new BotEventHuntedTargetLost;
        // transitions
        m_FSM.AddTransition(new BotTransition(   m_Tracking, __InSight__, m_Hunting));
        m_FSM.AddTransition(new BotTransition(   m_Hunting,  __Lost__   , m_Tracking));
        m_FSM.SetInitialState(m_Tracking);
    }
BotSpawnEntityInHands()
void BotStateBase::BotSpawnEntityInHands (Bot bot = NULL, BotStateBase parent = NULL, string new_type = "") inline private
Definition at line 7 of file bot_testspawnandopencan.c.
    {
        if (new_type == string.Empty)
            m_Type = "TunaCan";
        else
            m_Type = new_type;
    }
References Empty, and m_Type.
BotTestAttachAndDropCycle()
void BotStateBase::BotTestAttachAndDropCycle (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 11 of file bot_testattachanddropcycle.c.
    {
        // setup nested state machine
        m_FSM = new BotFSM(this); // @NOTE: set owner of the submachine fsm
        m_Detaching = new BotTestAttachAndDropCycle_Detaching(m_Bot, this);
        m_Attaching = new BotTestAttachAndDropCycle_Attaching(m_Bot, this);
        // events
        BotEventBase __EntAtt__ = new BotEventEntityAttached;
        BotEventBase __EntDet__ = new BotEventEntityDetached;
        // transitions
        m_FSM.AddTransition(new BotTransition(   m_Detaching, __EntDet__, m_Attaching));
        m_FSM.AddTransition(new BotTransition(   m_Attaching, __EntAtt__, m_Detaching));
        m_FSM.SetInitialState(m_Detaching);
    }
BotTestItemMoveBackAndForth()
void BotStateBase::BotTestItemMoveBackAndForth (Bot bot = NULL, BotStateBase parent = NULL) inline private
Definition at line 6 of file bot_testitemmovebackandforth.c.
    {
        // setup nested state machine
        m_FSM = new BotFSM(this); // @NOTE: set owner of the submachine fsm
        m_Move = new BotTestItemMoveBackAndForth_MoveFromSlotToSlot(m_Bot, this);
        // events
        BotEventBase __EntAtt__ = new BotEventEntityAttached;
        // transitions
        m_FSM.AddTransition(new BotTransition(   m_Move, __EntAtt__, m_Move));
        m_FSM.SetInitialState(m_Move);
    }
BotTimedWait()
void BotStateBase::BotTimedWait (Bot bot = NULL, BotStateBase parent = NULL, float timeout = 3.0) inline private
Definition at line 10 of file bot_timedwait.c.
    {
        m_Timeout = timeout;
    }
GetFSM()
BotFSM BotStateBase::GetFSM () inline private
Definition at line 31 of file botstates.c.
{ return m_FSM; }
References m_FSM.
GetNextSlot()
int BotStateBase::GetNextSlot (int curr) inline private
Definition at line 79 of file bot_testitemmovebackandforth.c.
    {
        if (curr == m_hgSlot)
            return m_mskSlot;
        if (curr == m_mskSlot)
            return m_hgSlot;
        Error("EE2");
        return InventorySlots.INVALID;
    }
References Error(), m_hgSlot, and m_mskSlot.
Referenced by OnUpdate().
GetParentState()
BotStateBase::GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
Definition at line 28 of file botstates.c.
{ return m_ParentState; }
References m_ParentState.
GetPlayerOwner()
PlayerBase BotStateBase::GetPlayerOwner () inline private
Definition at line 19 of file botstates.c.
{ return m_Owner; }
References m_Owner.
Referenced by OnUpdate(), and SelectTarget().
HasFSM()
bool BotStateBase::HasFSM () inline private
Definition at line 30 of file botstates.c.
{ return m_FSM != NULL; }
References m_FSM.
Referenced by AddTransition(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
IsIdle()
BotStateBase::IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Definition at line 112 of file botstates.c.
{ return false; }
IsWaitingForActionFinish()
BotStateBase::IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state or active substate is waiting for finish signal
Definition at line 106 of file botstates.c.
{ return HasFSM() && m_FSM.IsRunning() && m_FSM.GetCurrentState().IsWaitingForActionFinish(); }
References HasFSM(), and m_FSM.
OnAbort() [1/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 105 of file bot_hunt.c.
    {
        m_TargetLost = false;
        m_TargetInSight = false;
        m_Tracking = false;
        super.OnAbort(e);
    }
OnAbort() [2/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 183 of file bot_hunt.c.
{ super.OnAbort(e); }
OnAbort() [3/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 61 of file bot_testattachanddropcycle.c.
{ super.OnAbort(e); }
OnAbort() [4/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 97 of file bot_testattachanddropcycle.c.
{ super.OnAbort(e); }
OnAbort() [5/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 72 of file bot_testitemmovebackandforth.c.
{ super.OnAbort(e); }
OnAbort() [6/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 66 of file bot_testspawnandopencan.c.
{ super.OnAbort(e); }
OnAbort() [7/8]
override void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 131 of file bot_testspawnandopencan.c.
{ super.OnAbort(e); }
OnAbort() [8/8]
void BotStateBase::OnAbort (BotEventBase e) inline private
Definition at line 83 of file botstates.c.
    {
        if (HasFSM() && m_FSM.IsRunning())
        {
            botDebugPrint("[botfsm] OnAbort " + this.Type().ToString() + "  Has Sub-FSM! Aborting submachine...");
            m_FSM.Abort(e);
        }
        botDebugPrint("[botfsm] } ABORTED " + this.Type().ToString());
    }
References botDebugPrint(), HasFSM(), m_FSM, ToString(), and Type.
OnEntry() [1/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 50 of file bot_hunt.c.
    {
        m_dtAccumulator = 0.0;
        SelectTarget();
        super.OnEntry(e);
    }
References m_dtAccumulator, and SelectTarget().
OnEntry() [2/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 96 of file bot_hunt.c.
    {
        super.OnEntry(e);
        m_TargetLost = false;
        m_TargetInSight = false;
        m_Tracking = false;
    }
OnEntry() [3/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 178 of file bot_hunt.c.
    {
        super.OnEntry(e);
    }
OnEntry() [4/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 30 of file bot_testattachanddropcycle.c.
    {
        m_Entity = m_Owner.GetInventory().CreateAttachment("TaloonBag_Orange");
        m_Detaching.m_Entity = m_Entity;
        m_Attaching.m_Entity = m_Entity;
        super.OnEntry(e);
    }
References m_Entity, and m_Entity.
OnEntry() [5/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 56 of file bot_testattachanddropcycle.c.
    {
        super.OnEntry(e);
    }
OnEntry() [6/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 92 of file bot_testattachanddropcycle.c.
    {
        super.OnEntry(e);
    }
OnEntry() [7/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 22 of file bot_testitemmovebackandforth.c.
    {
        //m_Entity = m_Owner.GetInventory().CreateAttachment("TaloonBag_Orange");
        //m_Entity = m_Owner.GetInventory().FindAttachment();
        EntityAI hgear = m_Owner.GetInventory().FindAttachment( InventorySlots.GetSlotIdFromString("Headgear") );
        EntityAI mask = m_Owner.GetInventory().FindAttachment( InventorySlots.GetSlotIdFromString("Mask") );
        if (hgear)
            m_Entity = hgear;
        if (mask)
            m_Entity = mask;
        InventoryLocation loc = new InventoryLocation;
        if (m_Entity.GetInventory().GetCurrentInventoryLocation(loc))
        {
            m_Move.m_WaitingForSlot = loc.GetSlot();
        }
        else
            Error("EE");
        m_Move.m_Entity = m_Entity;
        super.OnEntry(e);
    }
References Error(), InventoryLocation::GetSlot(), InventorySlots::GetSlotIdFromString(), m_Entity, and m_Entity.
OnEntry() [8/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 67 of file bot_testitemmovebackandforth.c.
    {
        super.OnEntry(e);
    }
OnEntry() [9/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 15 of file bot_testspawnandopencan.c.
    {
        super.OnEntry(e);
        if (m_Owner.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            m_Owner.GetHumanInventory().CreateInHands(m_Type);
        }
    }
References m_Type.
OnEntry() [10/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 46 of file bot_testspawnandopencan.c.
    {
        super.OnEntry(e);
        if (m_Owner.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            BotEventEntityInHands ev_ih = BotEventEntityInHands.Cast(e);
            if (ev_ih)
            {
                m_Entity = ev_ih.m_Entity;
                Edible_Base b = Edible_Base.Cast(m_Entity);
                if (b)
                {
                    botDebugPrint("[bot] + " + m_Owner + " will open edible item=" + b + " bot=" + m_Owner);
                    b.Open();
                }
            }
        }
    }
References botDebugPrint(), m_Entity, and BotEventBase::m_Entity.
OnEntry() [11/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 120 of file bot_testspawnandopencan.c.
{ super.OnEntry(e); }
OnEntry() [12/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 130 of file bot_testspawnandopencan.c.
{ super.OnEntry(e); }
OnEntry() [13/14]
override void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 15 of file bot_timedwait.c.
    {
        m_dtAccumulator = 0.0;
        super.OnEntry(e);
    }
References m_dtAccumulator, and WeaponFire::OnEntry().
OnEntry() [14/14]
void BotStateBase::OnEntry (BotEventBase e) inline private
Definition at line 57 of file botstates.c.
    {
        if (HasFSM() && !m_FSM.IsRunning())
        {
            botDebugPrint("[botfsm] { " + this.Type().ToString() + "  Has Sub-FSM! Starting submachine...");
            m_FSM.Start(e);
        }
        else
            botDebugPrint("[botfsm] { " + this.Type().ToString());
    }
References botDebugPrint(), HasFSM(), m_FSM, ToString(), and Type.
OnExit() [1/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 58 of file bot_hunt.c.
    {
        m_dtAccumulator = 0.0;
        m_Target = null;
        super.OnExit(e);
    }
References m_dtAccumulator, and m_Target.
OnExit() [2/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 114 of file bot_hunt.c.
    {
        m_TargetLost = false;
        m_TargetInSight = false;
        m_Tracking = false;
        super.OnExit(e);
    }
OnExit() [3/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 185 of file bot_hunt.c.
    {
        super.OnExit(e);
    }
OnExit() [4/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 39 of file bot_testattachanddropcycle.c.
    {
        m_Entity = null;
        super.OnExit(e);
    }
References m_Entity.
OnExit() [5/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 63 of file bot_testattachanddropcycle.c.
    {
        super.OnExit(e);
    }
OnExit() [6/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 99 of file bot_testattachanddropcycle.c.
    {
        super.OnExit(e);
    }
OnExit() [7/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 47 of file bot_testitemmovebackandforth.c.
    {
        m_Entity = null;
        super.OnExit(e);
    }
References m_Entity.
OnExit() [8/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 74 of file bot_testitemmovebackandforth.c.
    {
        super.OnExit(e);
    }
OnExit() [9/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 25 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnExit() [10/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 68 of file bot_testspawnandopencan.c.
    {
        super.OnExit(e);
    }
OnExit() [11/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 121 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnExit() [12/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 132 of file bot_testspawnandopencan.c.
{ super.OnExit(e); }
OnExit() [13/14]
override void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 22 of file bot_timedwait.c.
    {
        m_dtAccumulator = 0.0;
        super.OnExit(e);
    }
References m_dtAccumulator.
OnExit() [14/14]
void BotStateBase::OnExit (BotEventBase e) inline private
Definition at line 97 of file botstates.c.
    {
        botDebugPrint("[botfsm] } " + this.Type().ToString());
    }
References botDebugPrint(), ToString(), and Type.
OnStateChanged()
BotStateBase::OnStateChanged (BotStateBase src, BotStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 126 of file botstates.c.
{ }
OnSubMachineChanged()
BotStateBase::OnSubMachineChanged (BotStateBase src, BotStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 119 of file botstates.c.
{ }
OnTimeout()
void BotStateBase::OnTimeout () inline private
Definition at line 47 of file bot_timedwait.c.
    {
        botDebugSpam("[bot] + " + m_Owner + " BotTimedWait::OnTimeout");
        m_Bot.ProcessEvent(new BotEventWaitTimeout(m_Owner));
    }
References botDebugSpam().
Referenced by OnUpdate().
OnUpdate() [1/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 66 of file bot_hunt.c.
    {
        super.OnUpdate(dt);
        m_dtAccumulator += dt;
        /*float rescanTime = 3.0;
        if (m_dtAccumulator >= rescanTime)
            if (m_weapon.CanProcessWeaponEvents())
                m_Bot.ProcessEvent(new WeaponEventReloadTimeout(p));*/
        if (m_Target == null)
        {
            int acc = m_dtAccumulator;
            if (acc % 5 == 0)
            {
                Print("Searching...");
                SelectTarget();
            }
        }
    }
References m_dtAccumulator, m_dtAccumulator, m_Target, Print(), and SelectTarget().
OnUpdate() [2/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 123 of file bot_hunt.c.
    {
        if (m_Target)
        {
            m_Tracking = true;
            vector targetPos = m_Target.GetPosition();
            botDebugPrint("[bot] + " + m_Owner + " hunt Tracking target=" + m_Target + " pos=" + targetPos);
            // tmp dist check
            float d = vector.Distance(m_Target.GetPosition(), GetPlayerOwner().GetPosition());
            if (d < 2.0)
            {
                m_TargetInSight = true;
            }
            else
            {
                m_TargetInSight = false;
            }
            if (!m_TargetInSight)
            {
                GetPlayerOwner().GetInputController().OverrideMovementSpeed(true, 1);
                GetPlayerOwner().GetInputController().OverrideMovementAngle(true, 1);
            }
            else
            {
                GetPlayerOwner().GetInputController().OverrideMovementSpeed(false, 0);
                GetPlayerOwner().GetInputController().OverrideMovementAngle(false, 0);
            }
            /*if ((.GetInputController().LimitsIsSprintDisabled()))
                .GetInputController().OverrideMovementSpeed( true, 2 );
            else
                .GetInputController().OverrideMovementSpeed( true, 3 );*/
        }
        else
        {
            if (m_Tracking)
            {
                m_TargetLost = true;
                m_TargetInSight = false;
                m_Tracking = false;
                GetPlayerOwner().GetInputController().OverrideMovementSpeed(false, 0);
                GetPlayerOwner().GetInputController().OverrideMovementAngle(false, 0);
            }
        }
    }
References botDebugPrint(), vector::Distance(), GetPlayerOwner(), GetPosition, and m_Target.
OnUpdate() [3/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 190 of file bot_hunt.c.
    {
    }
OnUpdate() [4/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 46 of file bot_testattachanddropcycle.c.
    {
        super.OnUpdate(dt);
    }
OnUpdate() [5/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 68 of file bot_testattachanddropcycle.c.
    {
        if (m_Entity)
        {
            botDebugPrint("[bot] + " + m_Owner + " drop item=" + m_Entity + " bot=" + m_Owner);
            m_Owner.PredictiveDropEntity(m_Entity);
            InventoryLocation loc = new InventoryLocation;
            if (m_Entity.GetInventory().GetCurrentInventoryLocation(loc))
            {
                if (loc.GetType() == InventoryLocationType.GROUND)
                {
                    m_Bot.ProcessEvent(new BotEventEntityDetached(m_Owner, m_Entity));
                }
            }
        }
    }
References botDebugPrint(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [6/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 104 of file bot_testattachanddropcycle.c.
    {
        if (m_Entity)
        {
            botDebugPrint("[bot] + " + m_Owner + " att item=" + m_Entity + " bot=" + m_Owner);
            if (m_Owner.GetInventory().CanAddAttachment(m_Entity))
            {
                m_Owner.PredictiveTakeEntityAsAttachment(m_Entity);
                InventoryLocation loc = new InventoryLocation;
                if (m_Entity.GetInventory().GetCurrentInventoryLocation(loc))
                {
                    if (loc.GetType() == InventoryLocationType.ATTACHMENT)
                    {
                        m_Bot.ProcessEvent(new BotEventEntityAttached(m_Owner, m_Entity));
                    }
                }
            }
        }
    }
References botDebugPrint(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [7/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 54 of file bot_testitemmovebackandforth.c.
    {
        super.OnUpdate(dt);
    }
OnUpdate() [8/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 89 of file bot_testitemmovebackandforth.c.
    {
        if (m_Entity)
        {
            botDebugPrint("[bot] + " + m_Owner + " move item=" + m_Entity);
            InventoryLocation loc = new InventoryLocation;
            if (m_Entity.GetInventory().GetCurrentInventoryLocation(loc))
            {
                if (loc.GetType() == InventoryLocationType.ATTACHMENT)
                {
                    if (loc.GetSlot() == m_WaitingForSlot)
                    {
                        int nextSlot = GetNextSlot(m_WaitingForSlot);
                        botDebugPrint("[bot] + " + m_Owner + " will switch slot=" + nextSlot + " for item=" + m_Entity);
                        m_WaitingForSlot = nextSlot;
                        m_Owner.PredictiveTakeEntityAsAttachmentEx(m_Entity, nextSlot);
                        //m_Bot.ProcessEvent(new BotEventEntityDet(m_Owner, m_Entity));
                    }
                }
            }
        }
    }
References botDebugPrint(), GetNextSlot(), InventoryLocation::GetSlot(), InventoryLocation::GetType(), and m_Entity.
OnUpdate() [9/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 27 of file bot_testspawnandopencan.c.
    {
        super.OnUpdate(dt);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        if (inHands)
        {
            botDebugPrint("[bot] + " + m_Owner + " hand item=" + inHands + " bot=" + m_Owner);
            m_Bot.ProcessEvent(new BotEventEntityInHands(m_Owner, inHands));
        }
    }
References botDebugPrint(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnUpdate() [10/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 73 of file bot_testspawnandopencan.c.
    {
        super.OnUpdate(dt);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        botDebugSpam("[bot] + " + m_Owner + " wait for opened item inHands=" + inHands + " bot=" + m_Owner);
        if (inHands)
        {
            string t_str = inHands.GetType();
            //string t_str = t.ToString();
            if (t_str.IndexOf("_Opened") != -1)
            {
                botDebugPrint("[bot] + " + m_Owner + " opened item=" + inHands + " bot=" + m_Owner);
                m_Bot.ProcessEvent(new BotEventEntityInHandsOpened(m_Owner, inHands));
            }
        }
    }
References botDebugPrint(), botDebugSpam(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), and string::IndexOf().
OnUpdate() [11/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 122 of file bot_testspawnandopencan.c.
{ super.OnUpdate(dt); }
OnUpdate() [12/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 134 of file bot_testspawnandopencan.c.
    {
        super.OnUpdate(dt);
        EntityAI inHands = m_Owner.GetHumanInventory().GetEntityInHands();
        botDebugSpam("[bot] + " + m_Owner + " waiting for empty hands, inHands=" + inHands + " bot=" + m_Owner);
        if (!inHands)
        {
            botDebugPrint("[bot] + " + m_Owner + " hand slot empty. bot=" + m_Owner);
            m_Bot.ProcessEvent(new BotEventHandsEmpty(m_Owner, inHands));
        }
    }
References botDebugPrint(), botDebugSpam(), HumanInventory::GetEntityInHands(), and EntityAI::GetHumanInventory().
OnUpdate() [13/14]
override void BotStateBase::OnUpdate (float dt) inline private
Definition at line 29 of file bot_timedwait.c.
    {
        super.OnUpdate(dt);
        m_dtAccumulator += dt;
        float rescanTime = m_Timeout;
        if (m_dtAccumulator >= rescanTime)
        {
            OnTimeout();
            if (m_Periodic)
                m_dtAccumulator = 0.0;
            else
                m_dtAccumulator = -1.0;
        }
    }
References m_dtAccumulator, m_Timeout, and OnTimeout().
OnUpdate() [14/14]
void BotStateBase::OnUpdate (float dt) inline private
Definition at line 73 of file botstates.c.
    {
        if (HasFSM() && m_FSM.IsRunning())
            m_FSM.GetCurrentState().OnUpdate(dt);
    }
References HasFSM(), and m_FSM.
ProcessEvent()
bool BotStateBase::ProcessEvent (BotEventBase e) inline private
Definition at line 33 of file botstates.c.
    {
        if (HasFSM())
            return m_FSM.ProcessEvent(e);
        return false;
    }
References HasFSM(), and m_FSM.
SelectTarget()
void BotStateBase::SelectTarget () inline private
Definition at line 42 of file bot_hunt.c.
    {
        m_Target = BotSelectNearestTarget(GetPlayerOwner());
        m_Tracking.m_Target = m_Target;
        m_Hunting.m_Target = m_Target;
        botDebugPrint("[bot] + " + m_Owner + " hunt SelectTarget target=" + m_Target);
    }
References botDebugPrint(), BotSelectNearestTarget(), GetPlayerOwner(), m_Target, and m_Target.
Referenced by OnEntry(), and OnUpdate().
SetParentState()
BotStateBase::SetParentState (BotStateBase parent) inline private
allows construction of hierarchical state machine
Definition at line 24 of file botstates.c.
{ m_ParentState = parent; }
References m_ParentState.
Member Data Documentation
m_Attaching
ref BotTestAttachAndDropCycle_Attaching BotStateBase::m_Attaching private
Definition at line 9 of file bot_testattachanddropcycle.c.
m_Bot
Bot BotStateBase::m_Bot private
man that this state belongs to
Definition at line 13 of file botstates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), and BotTestSpamUserActions::BotTestSpamUserActions().
m_Detaching
ref BotTestAttachAndDropCycle_Detaching BotStateBase::m_Detaching private
Definition at line 8 of file bot_testattachanddropcycle.c.
m_dtAccumulator [1/2]
float BotStateBase::m_dtAccumulator = 0.0 private
Definition at line 18 of file bot_hunt.c.
Referenced by OnUpdate().
m_dtAccumulator [2/2]
protected float BotStateBase::m_dtAccumulator = 0.0 private
Definition at line 6 of file bot_timedwait.c.
m_Entity
EntityAI BotStateBase::m_Entity private
Definition at line 7 of file bot_testattachanddropcycle.c.
Referenced by OnEntry().
m_FSM
ref BotFSM BotStateBase::m_FSM private
hierarchical parent state of this state (or null)
Definition at line 15 of file botstates.c.
Referenced by AddTransition(), BotTestSpamUserActions::BotTestSpamUserActions(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
m_hgSlot
int BotStateBase::m_hgSlot = InventorySlots.GetSlotIdFromString("Headgear") private
Definition at line 64 of file bot_testitemmovebackandforth.c.
Referenced by GetNextSlot().
m_Hunting
ref BotHunt_Hunting BotStateBase::m_Hunting private
Definition at line 21 of file bot_hunt.c.
m_Move
ref BotTestItemMoveBackAndForth_MoveFromSlotToSlot BotStateBase::m_Move private
Definition at line 4 of file bot_testitemmovebackandforth.c.
m_mskSlot
int BotStateBase::m_mskSlot = InventorySlots.GetSlotIdFromString("Mask") private
Definition at line 65 of file bot_testitemmovebackandforth.c.
Referenced by GetNextSlot().
m_Opening
ref BotOpenEntityInHands BotStateBase::m_Opening private
Definition at line 97 of file bot_testspawnandopencan.c.
m_Owner
PlayerBase BotStateBase::m_Owner private
Definition at line 12 of file botstates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), GetPlayerOwner(), BotTestSwapInternal::OnEntry(), BotTestSwapInternalC2H::OnEntry(), BotTestSwapG2H::OnEntry(), BotTestSpamUserActions::OnEntry(), BotTestSwapInternal::OnUpdate(), and BotTestSwapInternalC2H::OnUpdate().
m_ParentState
BotStateBase BotStateBase::m_ParentState private
bot that this state belongs to
Definition at line 14 of file botstates.c.
Referenced by BotStateBase(), BotStateIdle::BotStateIdle(), GetParentState(), and SetParentState().
m_Periodic
protected bool BotStateBase::m_Periodic = true private
Definition at line 8 of file bot_timedwait.c.
m_Spawning
ref BotSpawnEntityInHands BotStateBase::m_Spawning private
Definition at line 96 of file bot_testspawnandopencan.c.
m_Target [1/2]
EntityAI BotStateBase::m_Target private
Definition at line 17 of file bot_hunt.c.
Referenced by SelectTarget().
m_Target [2/2]
EntityAI BotStateBase::m_Target private
Definition at line 91 of file bot_hunt.c.
m_TargetInSight
bool BotStateBase::m_TargetInSight = false private
Definition at line 92 of file bot_hunt.c.
m_TargetLost
bool BotStateBase::m_TargetLost = false private
Definition at line 93 of file bot_hunt.c.
m_Timeout
protected float BotStateBase::m_Timeout = 3.0 private
Definition at line 7 of file bot_timedwait.c.
Referenced by OnUpdate().
m_Tracking [1/2]
ref BotHunt_Tracking BotStateBase::m_Tracking private
Definition at line 20 of file bot_hunt.c.
m_Tracking [2/2]
bool BotStateBase::m_Tracking = true private
Definition at line 94 of file bot_hunt.c.
m_Type
string BotStateBase::m_Type private
Definition at line 5 of file bot_testspawnandopencan.c.
m_WaitingForSlot
int BotStateBase::m_WaitingForSlot = InventorySlots.INVALID private
Definition at line 63 of file bot_testitemmovebackandforth.c.