DayzKode: ActionLockedDoors Class Reference
ActionLockedDoors Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionLockedDoors ()
override void CreateConditionComponents ()
override void OnExecute (ActionData action_data)
Detailed Description
Definition at line 1 of file actionlockeddoors.c.
Constructor & Destructor Documentation
ActionLockedDoors()
void ActionLockedDoors::ActionLockedDoors () inline private
Definition at line 3 of file actionlockeddoors.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_OPENDOORFW;
        //m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#open";
    }
References AnimatedActionBase::m_CommandUID, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionLockedDoors::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 16 of file actionlockeddoors.c.
    {
        if( !target ) return false;
        //if( IsDamageDestroyed(action_data.m_Target) ) return false;
        if( !IsBuilding(target) ) return false;
        if( !IsInReach(player, target, UAMaxDistances.DEFAULT) ) return false;
        Building building;
        if( Class.CastTo(building, target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(target.GetComponentIndex());
            if ( doorIndex != -1 )
            {
                return building.IsDoorLocked(doorIndex);
            }
        }
        return false;
    }
References Class::CastTo(), UAMaxDistances::DEFAULT, IsBuilding(), and IsInReach().
CreateConditionComponents()
override void ActionLockedDoors::CreateConditionComponents () inline private
Definition at line 10 of file actionlockeddoors.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTCursor;
    }
References m_ConditionItem, and m_ConditionTarget.
OnExecute()
override void ActionLockedDoors::OnExecute (ActionData action_data) inline private
Definition at line 35 of file actionlockeddoors.c.
    {
        Building building;
        if ( Class.CastTo(building, action_data.m_Target.GetObject()) )
        {
            int doorIndex = building.GetDoorIndex(action_data.m_Target.GetComponentIndex());
            if ( doorIndex != -1 )
            {
                building.OpenDoor(doorIndex);
            }
        }
    }
References Class::CastTo(), and ActionData::m_Target.