DayzKode: ActionRepackTent Class Reference
ActionRepackTent Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionRepackTent ()
override void CreateConditionComponents ()
override bool HasAlternativeInterrupt ()
override bool HasProgress ()
override bool HasTarget ()
override void OnEndAnimationLoop (ActionData action_data)
override void OnEndServer (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void OnStartAnimationLoopClient (ActionData action_data)
override void OnStartAnimationLoopServer (ActionData action_data)
override void OnStartServer (ActionData action_data)
override bool SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data=NULL)
void SetupAnimation (ItemBase item)
Private Attributes
bool m_IsFinished
EntityAI m_RepackedEntity
Detailed Description
Definition at line 42 of file actionrepacktent.c.
Constructor & Destructor Documentation
ActionRepackTent()
void ActionRepackTent::ActionRepackTent () inline private
Definition at line 47 of file actionrepacktent.c.
    {
        m_CallbackClass = ActionRepackTentCB;
        m_SpecialtyWeight = UASoftSkillsWeight.PRECISE_LOW;
        m_CommandUID = 0;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEMASK_ERECT;
        m_Text = "#repack_tent";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::PRECISE_LOW.
Member Function Documentation
ActionCondition()
override bool ActionRepackTent::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 83 of file actionrepacktent.c.
    {
        if ( !player.IsPlacingLocal() )
        {
            return true;
        }
        return false;
    }
ActionConditionContinue()
override bool ActionRepackTent::ActionConditionContinue (ActionData action_data) inline private
Definition at line 73 of file actionrepacktent.c.
    {
        return true;
    }
CreateConditionComponents()
override void ActionRepackTent::CreateConditionComponents () inline private
Definition at line 57 of file actionrepacktent.c.
    {
        m_ConditionItem = new CCINone;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
HasAlternativeInterrupt()
override bool ActionRepackTent::HasAlternativeInterrupt () inline private
Definition at line 78 of file actionrepacktent.c.
    {
        return true;
    }
HasProgress()
override bool ActionRepackTent::HasProgress () inline private
Definition at line 68 of file actionrepacktent.c.
    {
        return true;
    }
HasTarget()
override bool ActionRepackTent::HasTarget () inline private
Definition at line 63 of file actionrepacktent.c.
    {
        return false;
    }
OnEndAnimationLoop()
override void ActionRepackTent::OnEndAnimationLoop (ActionData action_data) inline private
Definition at line 194 of file actionrepacktent.c.
    {
        if ( !GetGame().IsMultiplayer() || GetGame().IsServer() )
        {
            Param1<bool> play = new Param1<bool>( false );
            GetGame().RPCSingleParam( action_data.m_MainItem, SoundTypeTent.REPACK, play, true );
        }
    }
References GetGame(), ActionData::m_MainItem, and CGame::RPCSingleParam().
OnEndServer()
override void ActionRepackTent::OnEndServer (ActionData action_data) inline private
Definition at line 117 of file actionrepacktent.c.
    {
        if ( m_IsFinished )
        {
            if ( action_data.m_MainItem.IsInherited( TentBase ) )
            {
                RepackLambda lambda_back_pack = new RepackLambda(action_data.m_MainItem, "LargeTentBackPack", action_data.m_Player);
                action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lambda_back_pack);
            }
            if (  action_data.m_MainItem.IsInherited( Clothing ) )
            {
                RepackLambda lambda_tent = new RepackLambda(action_data.m_MainItem, "LargeTent", action_data.m_Player);
                action_data.m_Player.ServerReplaceItemElsewhereWithNewInHands(lambda_tent);
            }
        }
        else
        {
            if ( GetGame().IsMultiplayer() )
            {
                if ( action_data.m_MainItem )
                {
                    action_data.m_Player.ServerTakeEntityToHands( action_data.m_MainItem );
                }
            }
            else
            {
                if ( action_data.m_MainItem )
                {
                    action_data.m_Player.LocalTakeEntityToHands( action_data.m_MainItem );
                }
            }
        }
    }
References GetGame(), m_IsFinished, ActionData::m_MainItem, and ActionData::m_Player.
OnFinishProgressServer()
override void ActionRepackTent::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 109 of file actionrepacktent.c.
    {
        Param1<bool> play = new Param1<bool>( false );
        GetGame().RPCSingleParam( action_data.m_MainItem, SoundTypeTent.REPACK, play, true );
        m_IsFinished = true;
    }
References GetGame(), m_IsFinished, ActionData::m_MainItem, and CGame::RPCSingleParam().
OnStartAnimationLoopClient()
override void ActionRepackTent::OnStartAnimationLoopClient (ActionData action_data) inline private
Definition at line 172 of file actionrepacktent.c.
    {
        if ( action_data.m_Player.GetItemInHands() )
            ActionRepackTentCB.Cast(action_data.m_Callback).DropDuringRepacking();
    }
References ActionRepackTentCB::DropDuringRepacking(), ActionData::m_Callback, and ActionData::m_Player.
OnStartAnimationLoopServer()
override void ActionRepackTent::OnStartAnimationLoopServer (ActionData action_data) inline private
Definition at line 178 of file actionrepacktent.c.
    {
        Param1<bool> play = new Param1<bool>( false );
        if ( !GetGame().IsMultiplayer() )
        {
            if ( action_data.m_Player.GetItemInHands() )
                ActionRepackTentCB.Cast(action_data.m_Callback).DropDuringRepacking();
        }
        if ( action_data.m_Player.GetItemInHands() )
        {
            play = new Param1<bool>( true );
            GetGame().RPCSingleParam( action_data.m_MainItem, SoundTypeTent.REPACK, play, true );
        }
    }
References ActionRepackTentCB::DropDuringRepacking(), GetGame(), ActionData::m_Callback, ActionData::m_MainItem, ActionData::m_Player, and CGame::RPCSingleParam().
OnStartServer()
override void ActionRepackTent::OnStartServer (ActionData action_data) inline private
Definition at line 103 of file actionrepacktent.c.
    {
        m_RepackedEntity = null;
        m_IsFinished = false;
    }
References m_IsFinished, and m_RepackedEntity.
SetupAction()
override bool ActionRepackTent::SetupAction (PlayerBase player, ActionTarget target, ItemBase item, out ActionData action_data, Param extra_data = NULL) inline private
Definition at line 92 of file actionrepacktent.c.
    {
        SetupAnimation( item );
        if ( super.SetupAction(player, target, item, action_data, extra_data ))
        {
            return true;
        }
        return false;
    }
References SetupAnimation().
SetupAnimation()
void ActionRepackTent::SetupAnimation (ItemBase item) inline private
Definition at line 152 of file actionrepacktent.c.
    {
        if ( item.IsHeavyBehaviour() )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_HEAVY;
        }
        else if ( item.IsOneHandedBehaviour() )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_1HD;
        }
        else if ( item.IsTwoHandedBehaviour() )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DEPLOY_2HD;
        }
        else
        {
            Print("Error: check " + item + " behaviour");
        }
    }
References AnimatedActionBase::m_CommandUID, and Print().
Referenced by SetupAction().
Member Data Documentation
m_IsFinished
bool ActionRepackTent::m_IsFinished private
Definition at line 45 of file actionrepacktent.c.
Referenced by OnEndServer(), OnFinishProgressServer(), and OnStartServer().
m_RepackedEntity
EntityAI ActionRepackTent::m_RepackedEntity private
Definition at line 44 of file actionrepacktent.c.
Referenced by OnStartServer().