DayzKode: HandStateBase Class Reference
HandStateBase Class Reference
represent hand state base
Private Member Functions
void AddTransition (HandTransition t)
adds transition into m_FSM transition table
int GetCurrentStateID ()
HandFSM GetFSM ()
HandStateBase GetParentState ()
void HandAnimatedForceSwapping (Man player=NULL, HandStateBase parent=NULL)
void HandAnimatedForceSwapping_Inst (Man player=NULL, HandStateBase parent=NULL)
void HandAnimatedMovingToAtt (Man player=NULL, HandStateBase parent=NULL)
void HandAnimatedSwapping (Man player=NULL, HandStateBase parent=NULL)
void HandAnimatedTakingFromAtt (Man player=NULL, HandStateBase parent=NULL)
void HandReplacingItemElsewhereWithNewInHands (Man player=NULL, HandStateBase parent=NULL)
void HandReplacingItemInHands (Man player=NULL, HandStateBase parent=NULL)
void HandStableState (Man player=NULL, HandStateBase parent=NULL, int anim_state=-1)
void HandStartAction (Man player=NULL, HandStateBase parent=NULL, WeaponActions action=WeaponActions.NONE, int actionType=-1)
specific action sub-type
void HandStartReplacingItemElsewhereWithNewInHands (Man player=NULL, HandStateBase parent=NULL)
void HandStartReplacingItemInHands (Man player=NULL, HandStateBase parent=NULL)
void HandStateBase (Man player=NULL, HandStateBase parent=NULL)
nested state machine (or null)
bool HasEntityInHands ()
query for entity in hands
bool HasFSM ()
override bool IsIdle ()
idle state does not expect any animation events
override bool IsIdle ()
bool IsIdle ()
override bool IsWaitingForActionFinish ()
waiting for active animation action/actionType finish
override bool IsWaitingForActionFinish ()
override bool IsWaitingForActionFinish ()
bool IsWaitingForActionFinish ()
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
override void OnAbort (HandEventBase e)
void OnAbort (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
override void OnEntry (HandEventBase e)
void OnEntry (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
override void OnExit (HandEventBase e)
void OnExit (HandEventBase e)
void OnStateChanged (HandStateBase src, HandStateBase dst)
called on current state when state machine has changed its state
void OnSubMachineChanged (HandStateBase src, HandStateBase dst)
called when sub-machine has changed its state
override void OnUpdate (float dt)
void OnUpdate (float dt)
bool ProcessEvent (HandEventBase e)
void SetParentState (HandStateBase parent)
allows construction of hierarchical state machine
void SyncAnimState ()
Private Attributes
WeaponActions m_Action
int m_ActionType
action to be played
int m_AnimState
ref InventoryLocation m_Dst
ref InventoryLocation m_Dst1 = null
ref InventoryLocation m_Dst2 = null
EntityAI m_Entity
ref HandFSM m_FSM
hierarchical parent state of this state (or null)
ref HandAnimatedMoveToDst_W4T_Basic m_Hide
ref HandStartHidingAnimated m_Hide
weapon to be taken
ref HandTakingAnimated_Hide m_Hide
ref InventoryLocation m_ilEntity
HandStateBase m_parentState
entity that this state relates to
Man m_Player
ref HandStartReplacingItemElsewhereWithNewInHands m_Replacing
ref HandStartReplacingItemInHands m_Replacing
ref HandAnimatedMoveToDst_W4T m_Show
ref HandSwappingAnimated_Show m_Show
ref HandTakingAnimated_Show m_Show
ref InventoryLocation m_Src1 = null
ref InventoryLocation m_Src2 = null
ref HandStartHidingAnimated m_Start
ref HandForceSwappingAnimated_Show m_Swap
Detailed Description
represent hand state base
Class comes with entry/update/exit hooks that can be overriden in custom states
Definition at line 1 of file handanimatedforceswapping.c.
Constructor & Destructor Documentation
HandStateBase()
void HandStateBase::HandStateBase (Man player = NULL, HandStateBase parent = NULL) inline private
nested state machine (or null)
Definition at line 11 of file handstatebase.c.
{ m_Player = player; m_parentState = parent; }
References m_parentState, and m_Player.
Member Function Documentation
AddTransition()
HandStateBase::AddTransition (HandTransition t) inline private
adds transition into m_FSM transition table
Definition at line 35 of file handstatebase.c.
    {
        if (HasFSM())
            m_FSM.AddTransition(t);
        else
            Error("[hndfsm] adding transition to state without FSM. Configure FSM first.");
    }
References Error(), HasFSM(), and m_FSM.
GetCurrentStateID()
int HandStateBase::GetCurrentStateID () inline private
Definition at line 36 of file handstablestate.c.
{ return 0; }
GetFSM()
HandFSM HandStateBase::GetFSM () inline private
Definition at line 23 of file handstatebase.c.
{ return m_FSM; }
References m_FSM.
GetParentState()
HandStateBase::GetParentState () inline private
Returns
state that owns this sub-state (or null if plain state)
Definition at line 20 of file handstatebase.c.
{ return m_parentState; }
References m_parentState.
HandAnimatedForceSwapping()
void HandStateBase::HandAnimatedForceSwapping (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 98 of file handanimatedforceswapping.c.
    {
        // setup nested state machine
        m_Start = new HandStartHidingAnimated(player, this, WeaponActions.HIDE, -1);
        m_Show = new HandAnimatedMoveToDst_W4T(player, this, WeaponActions.SHOW, -1);
        m_Hide = new HandAnimatedMoveToDst_W4T_Basic(player, this);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _AEh_ = new HandAnimEventChanged;
        HandEventBase __Xd_ = new HandEventDestroyed;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Start,      _AEh_,  m_Hide ));
        m_FSM.AddTransition(new HandTransition(   m_Hide,       _AEh_,  m_Show )); // no animation in Hide step
        m_FSM.AddTransition(new HandTransition(   m_Show,       _fin_,  NULL ));
        m_FSM.AddTransition(new HandTransition(   m_Hide,       _fin_,  NULL ));
        m_FSM.AddTransition(new HandTransition(   m_Show,       __Xd_,  null ));
        m_FSM.AddTransition(new HandTransition(   m_Hide,       __Xd_,  null ));
        m_FSM.SetInitialState(m_Start);
    }
HandAnimatedForceSwapping_Inst()
void HandStateBase::HandAnimatedForceSwapping_Inst (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 216 of file handanimatedforceswapping.c.
    {
        // setup nested state machine
        m_Start = new HandStartHidingAnimated(player, this, WeaponActions.HIDE, -1);
        m_Swap = new HandForceSwappingAnimated_Show(player, this, WeaponActions.SHOW, -1);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _AEh_ = new HandAnimEventChanged;
        HandEventBase __Xd_ = new HandEventDestroyed;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Start,  _AEh_,  m_Swap ));
        m_FSM.AddTransition(new HandTransition(   m_Swap,   _fin_,  null ));
        m_FSM.AddTransition(new HandTransition(   m_Swap,   __Xd_,  null ));
        m_FSM.SetInitialState(m_Start);
    }
HandAnimatedMovingToAtt()
void HandStateBase::HandAnimatedMovingToAtt (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 75 of file handanimatedmovingtoatt.c.
    {
        // setup nested state machine
        m_Hide = new HandStartHidingAnimated(player, this, WeaponActions.HIDE, -1);
        m_Show = new HandAnimatedMoveToDst_W4T(player, this, WeaponActions.SHOW, -1);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _AEh_ = new HandAnimEventChanged;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Hide, _AEh_,   m_Show ));
        m_FSM.AddTransition(new HandTransition(   m_Show, _fin_,     NULL ));
        m_FSM.SetInitialState(m_Hide);
    }
HandAnimatedSwapping()
void HandStateBase::HandAnimatedSwapping (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 16 of file handanimatedswapping.c.
    {
        // setup nested state machine
        m_Hide = new HandStartHidingAnimated(player, this, WeaponActions.HIDE, -1);
        m_Show = new HandSwappingAnimated_Show(player, this, WeaponActions.SHOW, -1);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _AEh_ = new HandAnimEventChanged;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Hide, _AEh_,   m_Show ));
        m_FSM.AddTransition(new HandTransition(   m_Show, _fin_,     NULL ));
        m_FSM.SetInitialState(m_Hide);
    }
HandAnimatedTakingFromAtt()
void HandStateBase::HandAnimatedTakingFromAtt (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 67 of file handanimatedtakingfromatt.c.
    {
        // setup nested state machine
        m_Hide = new HandTakingAnimated_Hide(player, this, WeaponActions.HIDE, -1);
        m_Show = new HandTakingAnimated_Show(player, this, WeaponActions.SHOW, -1);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _AEh_ = new HandAnimEventChanged;
        HandEventBase __Xd_ = new HandEventDestroyed;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Hide, _AEh_,   m_Show ));
        m_FSM.AddTransition(new HandTransition(   m_Hide, __Xd_,     NULL ));
        m_FSM.AddTransition(new HandTransition(   m_Show, _fin_,     NULL ));
        m_FSM.AddTransition(new HandTransition(   m_Show, __Xd_,     NULL ));
        m_FSM.SetInitialState(m_Hide);
    }
HandReplacingItemElsewhereWithNewInHands()
void HandStateBase::HandReplacingItemElsewhereWithNewInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 42 of file handreplacingitemelsewherewithnewinhands.c.
    {
        // setup nested state machine
        m_Replacing = new HandStartReplacingItemElsewhereWithNewInHands(player, this);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Replacing, _fin_,     NULL ));
        m_FSM.SetInitialState(m_Replacing);
    }
References HandStartReplacingItemElsewhereWithNewInHands().
HandReplacingItemInHands()
void HandStateBase::HandReplacingItemInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 51 of file handreplacingiteminhands.c.
    {
        // setup nested state machine
        m_Replacing = new HandStartReplacingItemInHands(player, this);
        // events:
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        m_FSM = new HandFSM(this); // @NOTE: set owner of the submachine fsm
        m_FSM.AddTransition(new HandTransition(   m_Replacing, _fin_,     NULL ));
        m_FSM.SetInitialState(m_Replacing);
    }
References HandStartReplacingItemInHands().
HandStableState()
void HandStateBase::HandStableState (Man player = NULL, HandStateBase parent = NULL, int anim_state = -1) inline private
Definition at line 8 of file handstablestate.c.
{ m_AnimState = anim_state; }
HandStartAction()
void HandStateBase::HandStartAction (Man player = NULL, HandStateBase parent = NULL, WeaponActions action = WeaponActions.NONE, int actionType = -1) inline private
specific action sub-type
Definition at line 9 of file handstartaction.c.
    {
        m_Action = action;
        m_ActionType = actionType;
    }
References m_Action.
HandStartReplacingItemElsewhereWithNewInHands()
void HandStateBase::HandStartReplacingItemElsewhereWithNewInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 3 of file handreplacingitemelsewherewithnewinhands.c.
    { }
Referenced by HandReplacingItemElsewhereWithNewInHands().
HandStartReplacingItemInHands()
void HandStateBase::HandStartReplacingItemInHands (Man player = NULL, HandStateBase parent = NULL) inline private
Definition at line 3 of file handreplacingiteminhands.c.
    { }
Referenced by HandReplacingItemInHands().
HasEntityInHands()
bool HandStateBase::HasEntityInHands () inline private
query for entity in hands
Definition at line 39 of file handstablestate.c.
{ return false; }
HasFSM()
bool HandStateBase::HasFSM () inline private
Definition at line 22 of file handstatebase.c.
{ return m_FSM != NULL; }
References m_FSM.
Referenced by AddTransition(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
IsIdle() [1/3]
HandStateBase::IsIdle () inline private
idle state does not expect any animation events
Returns
true if this state is idle
Definition at line 34 of file handstablestate.c.
{ return true; }
Referenced by OnHandsStateChanged().
IsIdle() [2/3]
override bool HandStateBase::IsIdle () inline private
Definition at line 53 of file handstartaction.c.
{ return false; }
IsIdle() [3/3]
bool HandStateBase::IsIdle () inline private
Definition at line 113 of file handstatebase.c.
{ return false; }
IsWaitingForActionFinish() [1/4]
HandStateBase::IsWaitingForActionFinish () inline private
waiting for active animation action/actionType finish
Returns
true if this state is waiting for finish signal
Definition at line 40 of file handanimatedforceswapping.c.
{ return true; }
IsWaitingForActionFinish() [2/4]
override bool HandStateBase::IsWaitingForActionFinish () inline private
Definition at line 34 of file handreplacingitemelsewherewithnewinhands.c.
{ return true; }
IsWaitingForActionFinish() [3/4]
override bool HandStateBase::IsWaitingForActionFinish () inline private
Definition at line 43 of file handreplacingiteminhands.c.
{ return true; }
IsWaitingForActionFinish() [4/4]
bool HandStateBase::IsWaitingForActionFinish () inline private
Definition at line 107 of file handstatebase.c.
{ return HasFSM() && m_FSM.IsRunning() && m_FSM.GetCurrentState().IsWaitingForActionFinish(); }
References HasFSM(), and m_FSM.
OnAbort() [1/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 28 of file handanimatedforceswapping.c.
    {
        m_Dst = NULL;
        super.OnAbort(e);
    }
OnAbort() [2/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 163 of file handanimatedforceswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Dst1.GetItem());
            GetGame().ClearJuncture(e.m_Player, m_Dst2.GetItem());
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnAbort(e);
    }
References CGame::ClearJuncture(), and GetGame().
OnAbort() [3/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 279 of file handanimatedforceswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Dst1.GetItem());
            GetGame().ClearJuncture(e.m_Player, m_Dst2.GetItem());
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnAbort(e);
    }
References CGame::ClearJuncture(), and GetGame().
OnAbort() [4/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 109 of file handanimatedmovingtoatt.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Entity, m_ilEntity);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Entity);
        }
        m_Entity = null;
        m_ilEntity = null;
        super.OnAbort(e);
    }
References CGame::ClearJuncture(), GetGame(), and m_Entity.
OnAbort() [5/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 62 of file handanimatedswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Dst2.GetItem());
            GetGame().ClearJuncture(e.m_Player, m_Dst1.GetItem());
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnAbort(e);
    }
References CGame::ClearJuncture(), and GetGame().
OnAbort() [6/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 102 of file handanimatedtakingfromatt.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryHFSMLogEnable() )
        {
            Debug.InventoryHFSMLog("Action - STS = " + e.m_Player.GetSimulationTimeStamp(), e.ToString() , "n/a", "OnAbort", e.m_Player.ToString() );
        }
        #endif
        e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst.GetItem(), m_Dst);
        if ( GetGame().IsServer() )
            GetGame().ClearJuncture(e.m_Player, m_Dst.GetItem());
        m_Dst = null;
        super.OnAbort(e);
    }
References CGame::ClearJuncture(), GetGame(), Debug::InventoryHFSMLog(), and LogManager::IsInventoryHFSMLogEnable().
OnAbort() [7/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 24 of file handreplacingitemelsewherewithnewinhands.c.
    {
        super.OnAbort(e);
    }
OnAbort() [8/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 33 of file handreplacingiteminhands.c.
    {
        super.OnAbort(e);
    }
OnAbort() [9/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 71 of file handreplacingiteminhands.c.
    {
        super.OnAbort(e);
    }
OnAbort() [10/11]
override void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 24 of file handstablestate.c.
    {
        super.OnAbort(e);
    }
OnAbort() [11/11]
void HandStateBase::OnAbort (HandEventBase e) inline private
Definition at line 83 of file handstatebase.c.
    {
        if (HasFSM() && m_FSM.IsRunning())
        {
            hndDebugPrint("[hndfsm] OnAbort " + this.Type().ToString() + "  Has Sub-FSM! Aborting submachine...");
            m_FSM.Abort(e);
        }
        //Debug.InventoryHFSMLog("ABORTED " + e.m_Player.GetSimulationTimeStamp(), ""/*typename.EnumToString(HandEventID, GetEventID()) */, "n/a", "OnAbort", m_Player.ToString() );
        hndDebugPrint("[hndfsm] } " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " ABORTED " + this.Type().ToString());
    }
References HasFSM(), hndDebugPrint(), m_FSM, ToString(), and Type.
OnEntry() [1/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 5 of file handanimatedforceswapping.c.
    {
        Man player = e.m_Player;
        if (m_Dst && m_Dst.IsValid())
        {
            EntityAI item = m_Dst.GetItem();
            InventoryLocation src = new InventoryLocation;
            if (item.GetInventory().GetCurrentInventoryLocation(src))
            {
                GameInventory.LocationSyncMoveEntity(src, m_Dst);
                player.OnItemInHandsChanged();
            }
            else
                Error("[hndfsm] " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " HandAnimatedMoveToDst_W4T_Basic - item " + item + " has no Inventory or Location, inv=" + item.GetInventory());
        }
        else
            Error("[hndfsm] HandAnimatedMoveToDst_W4T_Basic - event has no valid m_Dst");
        super.OnEntry(e);
    }
References Error().
OnEntry() [2/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 122 of file handanimatedforceswapping.c.
    {
        HandEventForceSwap efs = HandEventForceSwap.Cast(e);
        if (efs)
        {
            if ( efs.GetSrc().GetType() == InventoryLocationType.HANDS )
            {
                m_Start.m_ActionType = efs.m_AnimationID;
                m_Src1 = efs.GetSrc();
                m_Src2 = efs.m_Src2;
                m_Dst1 = efs.GetDst();
                m_Dst2 = efs.m_Dst2;
                m_Show.m_ActionType = efs.m_Animation2ID;
            }
            else
            {
                m_Start.m_ActionType = efs.m_Animation2ID;
                m_Src1 = efs.m_Src2;
                m_Src2 = efs.GetSrc();
                m_Dst1 = efs.m_Dst2;
                m_Dst2 = efs.GetDst();
                m_Show.m_ActionType = efs.m_AnimationID;
            }
            m_Hide.m_Dst = m_Dst1;
            m_Show.m_Dst = m_Dst2;
            if (!GetGame().IsDedicatedServer())
            {
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst1.GetItem(), m_Dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst2.GetItem(), m_Dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
            }
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References GetGame(), m_Dst1, and m_Dst2.
OnEntry() [3/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 236 of file handanimatedforceswapping.c.
    {
        HandEventForceSwap efs = HandEventForceSwap.Cast(e);
        if (efs)
        {
            if ( efs.GetSrc().GetType() == InventoryLocationType.HANDS )
            {
                m_Start.m_ActionType = efs.m_AnimationID;
                m_Src1 = efs.GetSrc();
                m_Src2 = efs.m_Src2;
                m_Dst1 = efs.GetDst();
                m_Dst2 = efs.m_Dst2;
                m_Swap.m_ActionType = efs.m_Animation2ID;
            }
            else
            {
                m_Start.m_ActionType = efs.m_Animation2ID;
                m_Src1 = efs.m_Src2;
                m_Src2 = efs.GetSrc();
                m_Dst1 = efs.m_Dst2;
                m_Dst2 = efs.GetDst();
                m_Swap.m_ActionType = efs.m_AnimationID;
            }
            m_Swap.m_Src1 = m_Src1;
            m_Swap.m_Dst1 = m_Dst1;
            m_Swap.m_Src2 = m_Src2;
            m_Swap.m_Dst2 = m_Dst2;
            if (!GetGame().IsDedicatedServer())
            {
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst1.GetItem(), m_Dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst2.GetItem(), m_Dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
            }
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References GetGame(), m_Dst1, m_Dst2, m_Src1, and m_Src2.
OnEntry() [4/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 93 of file handanimatedmovingtoatt.c.
    {
        m_Entity = e.GetSrcEntity();
        HandEventMoveTo ev_move = HandEventMoveTo.Cast(e);
        if (ev_move)
        {
            m_Show.m_Dst = ev_move.GetDst();
            m_Hide.m_ActionType = ev_move.GetAnimationID();
            m_Show.m_ActionType = ev_move.GetAnimationID();
            m_ilEntity = m_Show.m_Dst;
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References HandEventBase::m_Dst, and m_Entity.
OnEntry() [5/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 34 of file handanimatedswapping.c.
    {
        HandEventSwap es = HandEventSwap.Cast(e);
        if (es)
        {
            m_Src1 = es.GetSrc();
            m_Src2 = es.m_Src2;
            m_Dst1 = es.GetDst();
            m_Dst2 = es.m_Dst2;
            m_Show.m_Src1 = m_Src1;
            m_Show.m_Src2 = m_Src2;
            m_Show.m_Dst1 = m_Dst1;
            m_Show.m_Dst2 = m_Dst2;
            m_Hide.m_ActionType = es.m_AnimationID;
            m_Show.m_ActionType = es.m_Animation2ID;
            if (!GetGame().IsDedicatedServer())
            {
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst2.GetItem(), m_Dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
                e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst1.GetItem(), m_Dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
            }
        }
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References GetGame(), m_Dst1, m_Dst2, m_Src1, and m_Src2.
OnEntry() [6/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 88 of file handanimatedtakingfromatt.c.
    {
        m_Dst = e.GetDst();
        m_Show.m_Src = e.GetSrc();
        m_Show.m_Dst = e.GetDst();
        m_Hide.m_ActionType = e.GetAnimationID();
        m_Show.m_ActionType = e.GetAnimationID();
        e.m_Player.GetHumanInventory().AddInventoryReservationEx(m_Dst.GetItem(), m_Dst, GameInventory.c_InventoryReservationTimeoutShortMS);
        super.OnEntry(e); // @NOTE: super at the end (prevent override from submachine start)
    }
References HandEventBase::GetDst(), and HandEventBase::m_Dst.
OnEntry() [7/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 6 of file handreplacingitemelsewherewithnewinhands.c.
    {
        super.OnEntry(e);
        Man player = e.m_Player;
        HandEventReplaceWithNewBase edr = HandEventReplaceWithNewBase.Cast(e);
        if (edr)
        {
            hndDebugPrint("[hndfsm] HandStartReplacingItemElsewhereWithNewInHands about to execute lambda");
            HumanInventoryWithFSM inv = HumanInventoryWithFSM.Cast(player.GetInventory());
            edr.m_Lambda.Execute(inv);
            return;
        }
        else
            Error("[hndfsm] HandStartReplacingItemElsewhereWithNewInHands - not a HandEvenReplaceWithNewBase event");
    }
References Error(), and hndDebugPrint().
OnEntry() [8/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 6 of file handreplacingiteminhands.c.
    {
        super.OnEntry(e);
        Man player = e.m_Player;
        EntityAI itemInHands = player.GetHumanInventory().GetEntityInHands();
        InventoryLocation src = new InventoryLocation;
        if (itemInHands.GetInventory().GetCurrentInventoryLocation(src))
        {
            HandEventDestroyAndReplaceWithNew edr = HandEventDestroyAndReplaceWithNew.Cast(e);
            if (edr)
            {
                hndDebugPrint("[hndfsm] HandStartReplacingItemInHands about to execute lambda");
                HumanInventoryWithFSM inv = HumanInventoryWithFSM.Cast(player.GetInventory());
                edr.m_Lambda.Execute(inv);
                //player.GetItemAccessor().OnItemInHandsChanged();
                return;
            }
            else
                Error("[hndfsm] HandStartReplacingItemInHands - not a HandEventDestroyAndReplaceWithNew event");
        }
        else
            Error("[hndfsm] HandStartReplacingItemInHands - itemInHands has no InventoryLocation");
    }
References Error(), HumanInventory::GetEntityInHands(), EntityAI::GetHumanInventory(), and hndDebugPrint().
OnEntry() [9/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 66 of file handreplacingiteminhands.c.
    {
        super.OnEntry(e);
    }
OnEntry() [10/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 12 of file handstablestate.c.
    {
        super.OnEntry(e);
        SyncAnimState();
        //m_weapon.OnStableStateEntry();
    }
References SyncAnimState().
OnEntry() [11/12]
override void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 15 of file handstartaction.c.
    {
        super.OnEntry(e);
        if (e.m_Player)
        {
            Human hmn = Human.Cast(e.m_Player);
            HumanCommandWeapons hcw = hmn.GetCommandModifier_Weapons();
            if (hcw)
            {
                if (m_ActionType == -1)
                {
                    hcw.StartAction(-1, -1);
                    hndDebugPrint("HCW: " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " playing A=-1 AT=-1 fini=" + hcw.IsActionFinished());
                }
                else
                {
                    hcw.StartAction(m_Action, m_ActionType);
                    if (hcw.GetRunningAction() == m_Action && hcw.GetRunningActionType() == m_ActionType)
                        hndDebugPrint("HCW: " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " playing A=" + typename.EnumToString(WeaponActions, m_Action) + " AT=" + WeaponActionTypeToString(m_Action, m_ActionType) + " fini=" + hcw.IsActionFinished());
                    else
                        Error("HCW: NOT playing A=" + typename.EnumToString(WeaponActions, m_Action) + " AT=" + WeaponActionTypeToString(m_Action, m_ActionType) + " fini=" + hcw.IsActionFinished());
                }
            }
            else
                hndDebugPrint("---: remote playing A=" + typename.EnumToString(WeaponActions, m_Action) + " AT=" + WeaponActionTypeToString(m_Action, m_ActionType));
        }
        else
        {
            hndDebugPrint("---: warning, no player wants to play A=" + typename.EnumToString(WeaponActions, m_Action) + " AT=" + WeaponActionTypeToString(m_Action, m_ActionType));
        }
    }
References Error(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), hndDebugPrint(), HumanCommandWeapons::IsActionFinished(), m_Action, HumanCommandWeapons::StartAction(), and WeaponActionTypeToString().
OnEntry() [12/12]
void HandStateBase::OnEntry (HandEventBase e) inline private
Definition at line 49 of file handstatebase.c.
    {
        if (HasFSM() && !m_FSM.IsRunning())
        {
            if (e)
                hndDebugPrint("[hndfsm] { " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " " + this.Type().ToString() + "  Has Sub-FSM! Starting submachine...");
            else
            hndDebugPrint("[hndfsm] { " + this.Type().ToString() + "  Has Sub-FSM! Starting submachine...");
            m_FSM.Start(e);
        }
        else
        {
            if (e)
                hndDebugPrint("[hndfsm] { " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " " + this.Type().ToString());
        else
            hndDebugPrint("[hndfsm] { " + this.Type().ToString());
    }
    }
References HasFSM(), hndDebugPrint(), m_FSM, ToString(), and Type.
OnExit() [1/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 34 of file handanimatedforceswapping.c.
    {
        m_Dst = NULL;
        super.OnExit(e);
    }
OnExit() [2/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 184 of file handanimatedforceswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Dst1.GetItem());
            GetGame().ClearJuncture(e.m_Player, m_Dst2.GetItem());
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnExit(e);
    }
References CGame::ClearJuncture(), and GetGame().
OnExit() [3/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 300 of file handanimatedforceswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
        }
        else
        {
            GetGame().ClearJuncture(e.m_Player, m_Dst1.GetItem());
            GetGame().ClearJuncture(e.m_Player, m_Dst2.GetItem());
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnExit(e);
    }
References CGame::ClearJuncture(), and GetGame().
OnExit() [4/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 126 of file handanimatedmovingtoatt.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Entity, m_ilEntity);
        }
        m_Entity = null;
        m_ilEntity = null;
        super.OnExit(e);
    }
References GetGame(), and m_Entity.
OnExit() [5/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 83 of file handanimatedswapping.c.
    {
        if( !GetGame().IsDedicatedServer())
        {
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst2.GetItem(), m_Dst2);
            e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst1.GetItem(), m_Dst1);
        }
        m_Src1 = null;
        m_Src2 = null;
        m_Dst1 = null;
        m_Dst2 = null;
        super.OnExit(e);
    }
References GetGame().
OnExit() [6/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 118 of file handanimatedtakingfromatt.c.
    {
        e.m_Player.GetHumanInventory().ClearInventoryReservationEx(m_Dst.GetItem(), m_Dst);
        m_Dst = null;
        super.OnExit(e);
    }
OnExit() [7/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 29 of file handreplacingitemelsewherewithnewinhands.c.
    {
        super.OnExit(e);
    }
OnExit() [8/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 38 of file handreplacingiteminhands.c.
    {
        super.OnExit(e);
    }
OnExit() [9/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 76 of file handreplacingiteminhands.c.
    {
        super.OnExit(e);
    }
OnExit() [10/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 28 of file handstablestate.c.
    {
        //m_weapon.ResetWeaponAnimState();
        super.OnExit(e);
    }
OnExit() [11/12]
override void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 48 of file handstartaction.c.
    {
        super.OnExit(e);
    }
OnExit() [12/12]
void HandStateBase::OnExit (HandEventBase e) inline private
Definition at line 98 of file handstatebase.c.
    {
        hndDebugPrint("[hndfsm] } " + Object.GetDebugName(e.m_Player) + " STS = " + e.m_Player.GetSimulationTimeStamp() + " " + this.Type().ToString());
    }
References hndDebugPrint().
OnStateChanged()
HandStateBase::OnStateChanged (HandStateBase src, HandStateBase dst) inline private
called on current state when state machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 127 of file handstatebase.c.
    {
        m_Player.GetHumanInventory().OnHandsStateChanged(src, dst);
    }
References m_Player.
OnSubMachineChanged()
HandStateBase::OnSubMachineChanged (HandStateBase src, HandStateBase dst) inline private
called when sub-machine has changed its state
Parameters
[in] src from state (previous)
[in] dst to state (current)
Definition at line 120 of file handstatebase.c.
{ }
OnUpdate() [1/2]
override void HandStateBase::OnUpdate (float dt) inline private
Definition at line 19 of file handstablestate.c.
    {
        super.OnUpdate(dt);
        SyncAnimState();
    }
References SyncAnimState().
OnUpdate() [2/2]
void HandStateBase::OnUpdate (float dt) inline private
Definition at line 73 of file handstatebase.c.
    {
        if (HasFSM() && m_FSM.IsRunning())
            m_FSM.GetCurrentState().OnUpdate(dt);
    }
References HasFSM(), and m_FSM.
ProcessEvent()
bool HandStateBase::ProcessEvent (HandEventBase e) inline private
Definition at line 25 of file handstatebase.c.
    {
        if (HasFSM())
            return m_FSM.ProcessEvent(e);
        return false;
    }
References HasFSM(), and m_FSM.
SetParentState()
HandStateBase::SetParentState (HandStateBase parent) inline private
allows construction of hierarchical state machine
Definition at line 16 of file handstatebase.c.
{ m_parentState = parent; }
References m_parentState.
SyncAnimState()
void HandStateBase::SyncAnimState () inline private
Definition at line 10 of file handstablestate.c.
{ }
Member Data Documentation
m_Action
WeaponActions HandStateBase::m_Action private
Definition at line 6 of file handstartaction.c.
m_ActionType
int HandStateBase::m_ActionType private
action to be played
Definition at line 7 of file handstartaction.c.
m_AnimState
int HandStateBase::m_AnimState private
Definition at line 6 of file handstablestate.c.
m_Dst
ref InventoryLocation HandStateBase::m_Dst private
Definition at line 3 of file handanimatedforceswapping.c.
m_Dst1
ref InventoryLocation HandStateBase::m_Dst1 = null private
Definition at line 91 of file handanimatedforceswapping.c.
Referenced by OnEntry().
m_Dst2
ref InventoryLocation HandStateBase::m_Dst2 = null private
Definition at line 92 of file handanimatedforceswapping.c.
Referenced by OnEntry().
m_Entity
EntityAI HandStateBase::m_Entity private
Definition at line 68 of file handanimatedmovingtoatt.c.
m_FSM
ref HandFSM HandStateBase::m_FSM private
hierarchical parent state of this state (or null)
Definition at line 10 of file handstatebase.c.
Referenced by AddTransition(), GetFSM(), HasFSM(), IsWaitingForActionFinish(), OnAbort(), OnEntry(), OnUpdate(), and ProcessEvent().
m_Hide [1/3]
ref HandStartHidingAnimated HandStateBase::m_Hide private
Definition at line 96 of file handanimatedforceswapping.c.
m_Hide [2/3]
ref HandStartHidingAnimated HandStateBase::m_Hide private
weapon to be taken
Definition at line 70 of file handanimatedmovingtoatt.c.
m_Hide [3/3]
ref HandTakingAnimated_Hide HandStateBase::m_Hide private
Definition at line 62 of file handanimatedtakingfromatt.c.
m_ilEntity
ref InventoryLocation HandStateBase::m_ilEntity private
Definition at line 73 of file handanimatedmovingtoatt.c.
m_parentState
HandStateBase HandStateBase::m_parentState private
entity that this state relates to
Definition at line 9 of file handstatebase.c.
Referenced by GetParentState(), HandStateBase(), and SetParentState().
m_Player
Man HandStateBase::m_Player private
Definition at line 8 of file handstatebase.c.
Referenced by HandStateBase(), and OnStateChanged().
m_Replacing [1/2]
ref HandStartReplacingItemElsewhereWithNewInHands HandStateBase::m_Replacing private
Definition at line 40 of file handreplacingitemelsewherewithnewinhands.c.
m_Replacing [2/2]
ref HandStartReplacingItemInHands HandStateBase::m_Replacing private
Definition at line 49 of file handreplacingiteminhands.c.
m_Show [1/3]
ref HandAnimatedMoveToDst_W4T HandStateBase::m_Show private
Definition at line 95 of file handanimatedforceswapping.c.
m_Show [2/3]
ref HandSwappingAnimated_Show HandStateBase::m_Show private
Definition at line 14 of file handanimatedswapping.c.
m_Show [3/3]
ref HandTakingAnimated_Show HandStateBase::m_Show private
Definition at line 63 of file handanimatedtakingfromatt.c.
m_Src1
ref InventoryLocation HandStateBase::m_Src1 = null private
Definition at line 89 of file handanimatedforceswapping.c.
Referenced by OnEntry().
m_Src2
ref InventoryLocation HandStateBase::m_Src2 = null private
Definition at line 90 of file handanimatedforceswapping.c.
Referenced by OnEntry().
m_Start
ref HandStartHidingAnimated HandStateBase::m_Start private
Definition at line 94 of file handanimatedforceswapping.c.
m_Swap
ref HandForceSwappingAnimated_Show HandStateBase::m_Swap private
Definition at line 214 of file handanimatedforceswapping.c.