DayzKode: CAContinuousTransferQuantity Class Reference
CAContinuousTransferQuantity Class Reference
Private Member Functions
void CAContinuousTransferQuantity (float quantity_filled_per_second)
void CalcAndSetQuantity (ActionData action_data)
override override int Cancel (ActionData action_data)
override int Execute (ActionData action_data)
override float GetProgress ()
override void Setup (ActionData action_data)
Private Attributes
protected float m_ItemQuantity
protected float m_QuantityFilledPerSecond
protected float m_SourceQuantity
protected float m_SpentQuantity
protected ref Param1< float > m_SpentUnits
protected float m_TargetUnits
protected float m_TimeToComplete
Detailed Description
Definition at line 1 of file cacontinuoustransferquantity.c.
Constructor & Destructor Documentation
CAContinuousTransferQuantity()
void CAContinuousTransferQuantity::CAContinuousTransferQuantity (float quantity_filled_per_second) inline private
Definition at line 11 of file cacontinuoustransferquantity.c.
    {
        m_QuantityFilledPerSecond = quantity_filled_per_second;
    }
References m_QuantityFilledPerSecond.
Member Function Documentation
CalcAndSetQuantity()
void CAContinuousTransferQuantity::CalcAndSetQuantity (ActionData action_data) inline private
Definition at line 85 of file cacontinuoustransferquantity.c.
    {
        if ( GetGame().IsServer() )
        {
            if ( m_SpentUnits )
            {
                m_SpentUnits.param1 = m_SpentQuantity;
                SetACData(m_SpentUnits);
            }
            action_data.m_MainItem.AddQuantity(m_SpentQuantity);
            ItemBase trg;
            if ( Class.CastTo(trg, action_data.m_Target.GetObject()) )
            {
                trg.AddQuantity(-m_SpentQuantity,false,false);
            }
        }
    }
References Class::CastTo(), GetGame(), ActionData::m_MainItem, m_SpentQuantity, m_SpentUnits, ActionData::m_Target, and CABase::SetACData().
Cancel()
override override int CAContinuousTransferQuantity::Cancel (ActionData action_data) inline private
Definition at line 67 of file cacontinuoustransferquantity.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        CalcAndSetQuantity( action_data );
        return UA_CANCEL;
    }
References CalcAndSetQuantity(), ActionData::m_Player, UA_CANCEL, and UA_ERROR.
Execute()
override int CAContinuousTransferQuantity::Execute (ActionData action_data) inline private
Definition at line 37 of file cacontinuoustransferquantity.c.
    {
        if ( !action_data.m_Player )
        {
            return UA_ERROR;
        }
        ItemBase trg;
        Class.CastTo(trg, action_data.m_Target.GetObject());
        if ( action_data.m_MainItem.GetQuantity() >= action_data.m_MainItem.GetQuantityMax() || trg.GetQuantity() == 0 )
        {
            return UA_FINISHED;
        }
        else
        {
        if ( m_SpentQuantity < m_TargetUnits && m_SpentQuantity < m_SourceQuantity )
        {
            m_SpentQuantity += m_QuantityFilledPerSecond * action_data.m_Player.GetDeltaT();
            float val = m_ItemQuantity-m_SpentQuantity;
            if ( m_Action ) m_Action.SendMessageToClient(action_data.m_Player, val.ToString());
            return UA_PROCESSING;
        }
        else
        {
            CalcAndSetQuantity( action_data );
            OnCompletePogress(action_data);
            return UA_FINISHED;
        }
    }
    }
References CalcAndSetQuantity(), Class::CastTo(), CABase::m_Action, m_ItemQuantity, ActionData::m_MainItem, ActionData::m_Player, m_QuantityFilledPerSecond, m_SourceQuantity, m_SpentQuantity, ActionData::m_Target, m_TargetUnits, CAContinuousBase::OnCompletePogress(), float::ToString(), UA_ERROR, UA_FINISHED, and UA_PROCESSING.
GetProgress()
override float CAContinuousTransferQuantity::GetProgress () inline private
Definition at line 78 of file cacontinuoustransferquantity.c.
    {
        float progress = (m_SpentQuantity*m_QuantityFilledPerSecond)/m_TimeToComplete;
        return (m_SpentQuantity*m_QuantityFilledPerSecond)/m_TimeToComplete;
    }
References m_QuantityFilledPerSecond, m_SpentQuantity, and m_TimeToComplete.
Setup()
override void CAContinuousTransferQuantity::Setup (ActionData action_data) inline private
Definition at line 16 of file cacontinuoustransferquantity.c.
    {
        m_SpentQuantity = 0;
        if ( !m_SpentUnits )
        {
            m_SpentUnits = new Param1<float>(0);
        }
        else
        {
            m_SpentUnits.param1 = 0;
        }
        m_ItemQuantity = action_data.m_MainItem.GetQuantity();
        ItemBase trg;
        if ( Class.CastTo(trg, action_data.m_Target.GetObject()) )
        {
            m_SourceQuantity = trg.GetQuantity();
        }
        m_TargetUnits = action_data.m_MainItem.GetQuantityMax();
        m_TimeToComplete= (Math.Min((m_TargetUnits-m_ItemQuantity),m_SourceQuantity))/m_QuantityFilledPerSecond;
    }
References Class::CastTo(), m_ItemQuantity, ActionData::m_MainItem, m_QuantityFilledPerSecond, m_SourceQuantity, m_SpentQuantity, m_SpentUnits, ActionData::m_Target, m_TargetUnits, m_TimeToComplete, and Math::Min().
Member Data Documentation
m_ItemQuantity
protected float CAContinuousTransferQuantity::m_ItemQuantity private
Definition at line 5 of file cacontinuoustransferquantity.c.
Referenced by Execute(), and Setup().
m_QuantityFilledPerSecond
protected float CAContinuousTransferQuantity::m_QuantityFilledPerSecond private
Definition at line 7 of file cacontinuoustransferquantity.c.
Referenced by CAContinuousTransferQuantity(), Execute(), GetProgress(), and Setup().
m_SourceQuantity
protected float CAContinuousTransferQuantity::m_SourceQuantity private
Definition at line 6 of file cacontinuoustransferquantity.c.
Referenced by Execute(), and Setup().
m_SpentQuantity
protected float CAContinuousTransferQuantity::m_SpentQuantity private
Definition at line 4 of file cacontinuoustransferquantity.c.
Referenced by CalcAndSetQuantity(), Execute(), GetProgress(), and Setup().
m_SpentUnits
protected ref Param1<float> CAContinuousTransferQuantity::m_SpentUnits private
Definition at line 9 of file cacontinuoustransferquantity.c.
Referenced by CalcAndSetQuantity(), and Setup().
m_TargetUnits
protected float CAContinuousTransferQuantity::m_TargetUnits private
Definition at line 3 of file cacontinuoustransferquantity.c.
Referenced by Execute(), and Setup().
m_TimeToComplete
protected float CAContinuousTransferQuantity::m_TimeToComplete private
Definition at line 8 of file cacontinuoustransferquantity.c.
Referenced by GetProgress(), and Setup().