DayzKode: ActionConsumeSingle Class Reference
ActionConsumeSingle Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionConsumeSingle ()
override void CreateConditionComponents ()
int GetConsumedQuantity ()
override bool HasProneException ()
override bool HasTarget ()
override void OnEndServer (ActionData action_data)
override void OnExecuteServer (ActionData action_data)
Private Attributes
const int DEFAULT_CONSUMED_QUANTITY = 1
Detailed Description
Definition at line 9 of file actionconsumesingle.c.
Constructor & Destructor Documentation
ActionConsumeSingle()
void ActionConsumeSingle::ActionConsumeSingle () inline private
Definition at line 13 of file actionconsumesingle.c.
    {
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONMOD_LICKBATTERY;
        m_CommandUIDProne = DayZPlayerConstants.CMD_ACTIONFB_LICKBATTERY;
        m_Text = "#eat";
    }
References AnimatedActionBase::m_CommandUID, AnimatedActionBase::m_CommandUIDProne, and m_Text.
Member Function Documentation
ActionCondition()
override bool ActionConsumeSingle::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 31 of file actionconsumesingle.c.
    {
        return super.ActionCondition(player, target, item) && player.CanEatAndDrink();
    }
CreateConditionComponents()
override void ActionConsumeSingle::CreateConditionComponents () inline private
Definition at line 25 of file actionconsumesingle.c.
    {
        m_ConditionItem = new CCINotRuinedAndEmpty;
        m_ConditionTarget = new CCTSelf;
    }
References m_ConditionItem, and m_ConditionTarget.
GetConsumedQuantity()
int ActionConsumeSingle::GetConsumedQuantity () inline private
Definition at line 20 of file actionconsumesingle.c.
    {
        return DEFAULT_CONSUMED_QUANTITY;
    }
References DEFAULT_CONSUMED_QUANTITY.
Referenced by OnExecuteServer().
HasProneException()
override bool ActionConsumeSingle::HasProneException () inline private
Definition at line 36 of file actionconsumesingle.c.
    {
        return true;
    }
HasTarget()
override bool ActionConsumeSingle::HasTarget () inline private
Definition at line 41 of file actionconsumesingle.c.
    {
        return false;
    }
OnEndServer()
override void ActionConsumeSingle::OnEndServer (ActionData action_data) inline private
Definition at line 56 of file actionconsumesingle.c.
    {
        if ( action_data.m_MainItem && ( action_data.m_MainItem.GetQuantity() <= 0 ) )
        {
            action_data.m_MainItem.SetQuantity( 0 );
        }
        if ( action_data.m_Player.HasBloodyHandsEx() == eBloodyHandsTypes.SALMONELA && !action_data.m_Player.GetInventory().FindAttachment( InventorySlots.GLOVES ) && GetProgress(action_data) > 0 )
        {
            action_data.m_Player.SetBloodyHandsPenalty();
        }
    }
References AnimatedActionBase::GetProgress(), ActionData::m_MainItem, and ActionData::m_Player.
OnExecuteServer()
override void ActionConsumeSingle::OnExecuteServer (ActionData action_data) inline private
Definition at line 46 of file actionconsumesingle.c.
    {
        PlayerBase player = action_data.m_Player;
        if ( player && action_data.m_MainItem )
        {
            player.Consume(action_data.m_MainItem, GetConsumedQuantity(), EConsumeType.ITEM_SINGLE_TIME);
        }
    }
References GetConsumedQuantity(), ActionData::m_MainItem, and ActionData::m_Player.
Member Data Documentation
DEFAULT_CONSUMED_QUANTITY
const int ActionConsumeSingle::DEFAULT_CONSUMED_QUANTITY = 1 private
Definition at line 11 of file actionconsumesingle.c.
Referenced by GetConsumedQuantity().