DayzKode: ServerBrowserTabPc Class Reference
ServerBrowserTabPc Class Reference
Private Member Functions
protected override void Construct (Widget parent, ServerBrowserMenuNew menu, TabType type)
private string GetConnEndPoint (CachedServerInfo cachedInfo)
private string GetQueryEndPoint (CachedServerInfo cachedInfo)
protected override void LoadExtraEntries (int index)
override void RefreshList ()
Private Attributes
private ref array< ref CachedServerInfo > m_CachedFavoriteServerInfo
Detailed Description
Definition at line 1 of file serverbrowserfavoritestabpc.c.
Member Function Documentation
Construct()
protected override void ServerBrowserTabPc::Construct (Widget parent, ServerBrowserMenuNew menu, TabType type) inline private
Definition at line 6 of file serverbrowserfavoritestabpc.c.
    {
        m_CachedFavoriteServerInfo = new array<ref CachedServerInfo>();
        super.Construct(parent, menu, type);
        DisableFilters();
    }
GetConnEndPoint()
private string ServerBrowserTabPc::GetConnEndPoint (CachedServerInfo cachedInfo) inline private
Definition at line 88 of file serverbrowserfavoritestabpc.c.
    {
        string ip = cachedInfo.param1;
        int connPort = cachedInfo.param3;
        return ip + ":" + connPort;
    }
Referenced by LoadExtraEntries().
GetQueryEndPoint()
private string ServerBrowserTabPc::GetQueryEndPoint (CachedServerInfo cachedInfo) inline private
Definition at line 95 of file serverbrowserfavoritestabpc.c.
    {
        string ip = cachedInfo.param1;
        int queryPort = cachedInfo.param4;
        return ip + ":" + queryPort;
    }
LoadExtraEntries()
protected override void ServerBrowserTabPc::LoadExtraEntries (int index) inline private
Definition at line 14 of file serverbrowserfavoritestabpc.c.
    {
        array<ref Param2<string, CachedServerInfo>> relevantCachedInfo = new array<ref Param2<string, CachedServerInfo>>();
        foreach (CachedServerInfo cachedInfo : m_CachedFavoriteServerInfo)
        {
            string serverId = GetConnEndPoint(cachedInfo);
            // ensure the cached server is still favorited
            if (!m_Menu.IsFavorited(GetQueryEndPoint(cachedInfo)))
            {
                continue;
            }
            if (m_OnlineFavServers.Find(serverId) > -1)
            {
                continue;
            }
            relevantCachedInfo.Insert(new Param2<string, CachedServerInfo>(serverId, cachedInfo));
        }
        // adding FAVORITED, OFFLINE servers to favorites tab
        int totalServersAlreadyShown = m_PageIndex * SERVERS_VISIBLE_COUNT + index;
        int startingIndex = totalServersAlreadyShown - m_TotalLoadedServers;
        m_TotalLoadedServers += relevantCachedInfo.Count();
        for (int i = startingIndex; i < relevantCachedInfo.Count(); ++i)
        {
            if (index >= SERVERS_VISIBLE_COUNT)
            {
                break;
            }
            Param2<string, CachedServerInfo> relevantEntry = relevantCachedInfo[i];
            cachedInfo = relevantEntry.param2;
            string ip = cachedInfo.param1;
            string cachedName = cachedInfo.param2;
            int connPort = cachedInfo.param3;
            int queryPort = cachedInfo.param4;
            // do NOT insert offlineRow into m_EntriesSorted[m_SortType]!!
            // we assume that rows already in m_EntriesSorted[m_SortType] are ONLINE,
            // if we add offline info to m_EntriesSorted[m_SortType] then we cannot differente
            // between online and offline servers
            GetServersResultRow offlineRow = new GetServersResultRow();
            offlineRow.m_Id = relevantEntry.param1;
            offlineRow.m_Name = cachedName;
            offlineRow.m_HostIp = ip;
            offlineRow.m_SteamQueryPort = queryPort;
            offlineRow.m_HostPort = connPort;
            offlineRow.m_Favorite = true;
            ServerBrowserEntry entry = GetServerEntryByIndex(index, offlineRow.m_Id);
            entry.Show(true);
            entry.FillInfo(offlineRow);
            entry.SetIsOnline(false);
            entry.UpdateEntry();
            index++;
        }
    }
References GetConnEndPoint(), m_Menu, m_OnlineFavServers, and m_TotalLoadedServers.
Referenced by ServerBrowserTab::UpdateServerList().
RefreshList()
override void ServerBrowserTabPc::RefreshList () inline private
Definition at line 76 of file serverbrowserfavoritestabpc.c.
    {
        OnlineServices.GetCachedFavServerInfo(m_CachedFavoriteServerInfo);
        m_OnlineFavServers.Clear();
        super.RefreshList();
        m_CurrentFilterInput.SetFavorited( true );
        AddFavoritesToFilter(m_CurrentFilterInput);
        OnlineServices.LoadServers(m_CurrentFilterInput);
    }
References AddFavoritesToFilter(), OnlineServices::GetCachedFavServerInfo(), OnlineServices::LoadServers(), m_CurrentFilterInput, m_OnlineFavServers, and GetServersInput::SetFavorited().
Referenced by ServerBrowserTab::ApplyFilters(), and ServerBrowserTab::OnClick().
Member Data Documentation
m_CachedFavoriteServerInfo
private ref array<ref CachedServerInfo> ServerBrowserTabPc::m_CachedFavoriteServerInfo private
Definition at line 4 of file serverbrowserfavoritestabpc.c.