DayzKode: HumanCommandVehicle Class Reference
HumanCommandVehicle Class Reference
Private Member Functions
proto native void GetOutVehicle ()
proto native Transport GetTransport ()
proto native int GetVehicleClass ()
proto native int GetVehicleSeat ()
proto native int GetVehicleType ()
private void HumanCommandVehicle ()
proto native bool IsGettingIn ()
proto native bool IsGettingOut ()
proto native bool IsSwitchSeat ()
proto native void JumpOutVehicle ()
proto native void KeepInVehicleSpaceAfterLeave (bool pState)
proto native void KnockedOutVehicle ()
proto native void SetClutchState (bool pState)
proto native void SetVehicleType (int pVehicleType)
proto native bool ShouldBeKnockedOut ()
proto native void SwitchSeat (int pTransportPositionIndex, int pVehicleSeat)
proto native bool WasGearChange ()
private void ~HumanCommandVehicle ()
Detailed Description
Definition at line 665 of file human.c.
Constructor & Destructor Documentation
HumanCommandVehicle()
private void HumanCommandVehicle::HumanCommandVehicle () inline private
Definition at line 667 of file human.c.
{}
~HumanCommandVehicle()
private void HumanCommandVehicle::~HumanCommandVehicle () inline private
Definition at line 668 of file human.c.
{}
Member Function Documentation
GetOutVehicle()
proto native void HumanCommandVehicle::GetOutVehicle () private
Referenced by Start().
GetTransport()
proto native Transport HumanCommandVehicle::GetTransport () private
Referenced by ActionCarHornBase::ActionCondition(), ActionStartEngine::ActionCondition(), ActionCondition(), ActionSwitchLights::ActionCondition(), ActionStopEngine::ActionCondition(), CameraHandler(), ManBase::CommandHandler(), DayZPlayerCamera3rdPersonVehicle(), CAContinuousRepeatStartEngine::Execute(), HandleDeath(), ActionSwitchLights::OnExecuteServer(), ActionStopEngine::OnExecuteServer(), ActionStartEngine::OnFinishProgressServer(), ActionStartEngine::OnStartServer(), OnStartServer(), DeveloperTeleport::SetPlayerDirection(), DeveloperTeleport::SetPlayerPosition(), Hud::ShowVehicleInfo(), Start(), CarHornShortActionInput::UpdatePossibleActions(), and ToggleLightsActionInput::UpdatePossibleActions().
GetVehicleClass()
proto native int HumanCommandVehicle::GetVehicleClass () private
GetVehicleSeat()
proto native int HumanCommandVehicle::GetVehicleSeat () private
Referenced by ActionStopEngine::ActionCondition(), and ManBase::OnCommandVehicleStart().
GetVehicleType()
proto native int HumanCommandVehicle::GetVehicleType () private
IsGettingIn()
proto native bool HumanCommandVehicle::IsGettingIn () private
Referenced by HandleDamageHit(), and HandleDeath().
IsGettingOut()
proto native bool HumanCommandVehicle::IsGettingOut () private
Referenced by HandleDamageHit(), and HandleDeath().
IsSwitchSeat()
proto native bool HumanCommandVehicle::IsSwitchSeat () private
JumpOutVehicle()
proto native void HumanCommandVehicle::JumpOutVehicle () private
Referenced by Start().
KeepInVehicleSpaceAfterLeave()
proto native void HumanCommandVehicle::KeepInVehicleSpaceAfterLeave (bool pState) private
KnockedOutVehicle()
proto native void HumanCommandVehicle::KnockedOutVehicle () private
Referenced by ManBase::CommandHandler().
SetClutchState()
proto native void HumanCommandVehicle::SetClutchState (bool pState) private
Referenced by GearChangeActionCallback::OnFinish(), and GearChangeActionCallback::SetVehicleCommand().
SetVehicleType()
proto native void HumanCommandVehicle::SetVehicleType (int pVehicleType) private
Referenced by ActionGetInTransport::Start().
ShouldBeKnockedOut()
proto native bool HumanCommandVehicle::ShouldBeKnockedOut () private
Referenced by ManBase::CommandHandler().
SwitchSeat()
proto native void HumanCommandVehicle::SwitchSeat (int pTransportPositionIndex, int pVehicleSeat) private
Referenced by ActionSwitchSeats::Start().
WasGearChange()
proto native bool HumanCommandVehicle::WasGearChange () private
Referenced by CommandHandler().