DayzKode: LeftArea Class Reference
LeftArea Class Reference
Private Member Functions
override void DraggingOverHeader (Widget w, int x, int y, Widget receiver)
override void ExpandCollapseContainer ()
float GetCurrentContainerBottomY ()
float GetCurrentContainerTopY ()
override EntityAI GetFocusedItem ()
override ScrollWidget GetScrollWidget ()
VicinityContainer GetVicinityContainer ()
override bool IsActive ()
void LeftArea (LayoutHolder parent)
override bool OnChildAdd (Widget w, Widget child)
override bool OnChildRemove (Widget w, Widget child)
void OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver)
override void OnShow ()
override void Refresh ()
override void SetActive (bool active)
override void SetLayoutName ()
override void SetParentWidget ()
override void UnfocusGrid ()
override void UpdateInterval ()
override void UpdateSelectionIcons ()
Private Attributes
protected Widget m_ContentParent
protected ref SizeToChild m_ContentResize
protected Widget m_DownIcon
protected bool m_IsProcessing = false
protected ScrollWidget m_ScrollWidget
protected bool m_ShouldChangeSize = true
protected Widget m_UpIcon
protected ref VicinityContainer m_VicinityContainer
Detailed Description
Definition at line 1 of file leftarea.c.
Constructor & Destructor Documentation
LeftArea()
void LeftArea::LeftArea (LayoutHolder parent) inline private
Definition at line 12 of file leftarea.c.
    {
        m_MainWidget.Show(true, false);
        m_ContentParent = m_MainWidget.FindAnyWidget("ContentParent");
        m_ContentParent.GetScript(m_ContentResize);
        m_ScrollWidget  = ScrollWidget.Cast(m_MainWidget.FindAnyWidget("Scroller"));
        m_MainWidget    = m_MainWidget.FindAnyWidget("Content");
        m_UpIcon        = m_RootWidget.FindAnyWidget("Up");
        m_DownIcon      = m_RootWidget.FindAnyWidget("Down");
        m_VicinityContainer = new VicinityContainer(this, false);
        m_Body.Insert(m_VicinityContainer);
        m_ActiveIndex = 0;
        WidgetEventHandler.GetInstance().RegisterOnChildAdd(m_MainWidget, this, "OnChildAdd");
        WidgetEventHandler.GetInstance().RegisterOnChildRemove(m_MainWidget, this, "OnChildRemove");
        RecomputeOpenedContainers();
    }
References WidgetEventHandler::GetInstance(), m_ContentParent, m_ContentResize, m_DownIcon, m_RootWidget, m_ScrollWidget, m_UpIcon, m_VicinityContainer, WidgetEventHandler::RegisterOnChildAdd(), and WidgetEventHandler::RegisterOnChildRemove().
Member Function Documentation
DraggingOverHeader()
override void LeftArea::DraggingOverHeader (Widget w, int x, int y, Widget receiver) inline private
Definition at line 137 of file leftarea.c.
    {
        m_VicinityContainer.DraggingOverHeader( w, x, y, receiver );
    }
References VicinityContainer::DraggingOverHeader(), m_VicinityContainer, x, and y.
ExpandCollapseContainer()
override void LeftArea::ExpandCollapseContainer () inline private
Definition at line 121 of file leftarea.c.
    {
        Container c = GetFocusedContainer();
        if (c)
        {
            c.ExpandCollapseContainer();
        }
        Refresh();
    }
References Refresh().
GetCurrentContainerBottomY()
float LeftArea::GetCurrentContainerBottomY () inline private
Definition at line 107 of file leftarea.c.
    {
        float x, y, cont_screen_pos, cont_screen_height;
        m_MainWidget.GetScreenPos( x, y );
        if ( m_OpenedContainers.IsValidIndex( m_ActiveIndex ) )
        {
            cont_screen_pos = Container.Cast( m_OpenedContainers.Get( m_ActiveIndex ) ).GetFocusedContainerYScreenPos();
            cont_screen_height = Container.Cast( m_OpenedContainers.Get( m_ActiveIndex ) ).GetFocusedContainerHeight();
        }
        return cont_screen_pos - y + cont_screen_height;
    }
References Container::GetFocusedContainerHeight(), Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by UpdateSelectionIcons().
GetCurrentContainerTopY()
float LeftArea::GetCurrentContainerTopY () inline private
Definition at line 97 of file leftarea.c.
    {
        float x, y, cont_screen_pos;
        m_MainWidget.GetScreenPos( x, y );
        if ( m_OpenedContainers.IsValidIndex( m_ActiveIndex ) )
            cont_screen_pos = Container.Cast( m_OpenedContainers.Get( m_ActiveIndex ) ).GetFocusedContainerYScreenPos();
        return cont_screen_pos - y;
    }
References Container::GetFocusedContainerYScreenPos(), x, and y.
Referenced by UpdateSelectionIcons().
GetFocusedItem()
override EntityAI LeftArea::GetFocusedItem () inline private
Definition at line 169 of file leftarea.c.
    {
        EntityAI item = GetFocusedContainer().GetFocusedItem();
        return item;
    }
GetScrollWidget()
override ScrollWidget LeftArea::GetScrollWidget () inline private
Definition at line 61 of file leftarea.c.
    {
        return m_ScrollWidget;
    }
References m_ScrollWidget.
GetVicinityContainer()
VicinityContainer LeftArea::GetVicinityContainer () inline private
Definition at line 175 of file leftarea.c.
    {
        return m_VicinityContainer;
    }
References m_VicinityContainer.
IsActive()
override bool LeftArea::IsActive () inline private
Definition at line 44 of file leftarea.c.
    {
        if( m_OpenedContainers.Count() <= m_ActiveIndex )
        {
            m_ActiveIndex = 0;
        }
        Container active_container = Container.Cast( m_OpenedContainers.Get( m_ActiveIndex ) );
        return active_container.IsActive( );
    }
OnChildAdd()
override bool LeftArea::OnChildAdd (Widget w, Widget child) inline private
Definition at line 235 of file leftarea.c.
    {
        if (!m_IsProcessing)
            Refresh();
        return true;
    }
References m_IsProcessing, and Refresh().
OnChildRemove()
override bool LeftArea::OnChildRemove (Widget w, Widget child) inline private
Definition at line 228 of file leftarea.c.
    {
        if (!m_IsProcessing)
            Refresh();
        return true;
    }
References m_IsProcessing, and Refresh().
OnLeftPanelDropReceived()
void LeftArea::OnLeftPanelDropReceived (Widget w, int x, int y, Widget receiver) inline private
Definition at line 132 of file leftarea.c.
    {
        m_VicinityContainer.OnLeftPanelDropReceived( w, x, y, receiver );
    }
References m_VicinityContainer, VicinityContainer::OnLeftPanelDropReceived(), x, and y.
OnShow()
override void LeftArea::OnShow () inline private
Definition at line 185 of file leftarea.c.
    {
        super.OnShow();
        Refresh();
    }
References Refresh().
Refresh()
override void LeftArea::Refresh () inline private
Definition at line 191 of file leftarea.c.
    {
        super.Refresh();
        m_MainWidget.Update();
        m_RootWidget.Update();
        m_ScrollWidget.Update();
        UpdateSelectionIcons();
        m_ShouldChangeSize = true;
    }
References m_RootWidget, m_ScrollWidget, m_ShouldChangeSize, and UpdateSelectionIcons().
Referenced by ExpandCollapseContainer(), OnChildAdd(), OnChildRemove(), and OnShow().
SetActive()
override void LeftArea::SetActive (bool active) inline private
Definition at line 54 of file leftarea.c.
    {
        super.SetActive( active );
        UpdateSelectionIcons();
    }
References UpdateSelectionIcons().
SetLayoutName()
override void LeftArea::SetLayoutName () inline private
Definition at line 142 of file leftarea.c.
    {
        #ifdef PLATFORM_CONSOLE
            m_LayoutName = WidgetLayoutName.LeftAreaXbox;
        #else
            switch ( InventoryMenu.GetWidthType() )
            {
                case ScreenWidthType.NARROW:
                {
                    m_LayoutName = WidgetLayoutName.LeftAreaNarrow;
                    break;
                }
                case ScreenWidthType.MEDIUM:
                {
                    m_LayoutName = WidgetLayoutName.LeftAreaMedium;
                    break;
                }
                case ScreenWidthType.WIDE:
                {
                    m_LayoutName = WidgetLayoutName.LeftAreaWide;
                    break;
                }
            }
        #endif
    }
References InventoryMenu(), WidgetLayoutName::LeftAreaMedium, WidgetLayoutName::LeftAreaNarrow, WidgetLayoutName::LeftAreaWide, and WidgetLayoutName::LeftAreaXbox.
SetParentWidget()
override void LeftArea::SetParentWidget () inline private
Definition at line 180 of file leftarea.c.
    {
        m_ParentWidget = m_Parent.GetMainWidget().FindAnyWidget( "LeftPanel" );
    }
References m_Parent.
UnfocusGrid()
override void LeftArea::UnfocusGrid () inline private
Definition at line 34 of file leftarea.c.
    {
        Container active_container;
        for ( int i = 0; i < m_OpenedContainers.Count(); i++ )
        {
            active_container = Container.Cast( m_OpenedContainers.Get( i ) );
            active_container.UnfocusGrid();
        }
    }
UpdateInterval()
override void LeftArea::UpdateInterval () inline private
Definition at line 203 of file leftarea.c.
    {
        m_IsProcessing = true;
        super.UpdateInterval();
        m_IsProcessing = false;
        float x, y;
        float x2, y2;
        m_ContentParent.GetScreenSize( x, y );
        m_MainWidget.GetScreenSize( x2, y2 );
        if ( y2 != y )
            m_ShouldChangeSize = true;
        bool changed_size;
        //if ( m_ShouldChangeSize )
            m_ContentResize.ResizeParentToChild( changed_size );
        if ( changed_size || m_ShouldChangeSize )
        {
            m_MainWidget.Update();
            m_RootWidget.Update();
            m_ScrollWidget.Update();
            m_ShouldChangeSize = false;
        }
        CheckScrollbarVisibility();
    }
References m_ContentParent, m_ContentResize, m_IsProcessing, m_RootWidget, m_ScrollWidget, m_ShouldChangeSize, x, and y.
UpdateSelectionIcons()
override void LeftArea::UpdateSelectionIcons () inline private
Definition at line 66 of file leftarea.c.
    {
        #ifdef PLATFORM_CONSOLE
            ScrollToActiveContainer();
        #endif
        m_UpIcon.Show( m_IsActive );
        m_DownIcon.Show( m_IsActive );
        if( m_IsActive )
        {
            float x, y;
            m_UpIcon.GetScreenSize( x, y );
            float top_y     = GetCurrentContainerTopY();
            m_UpIcon.SetPos( 0, Math.Clamp( top_y, 0, 99999 ) );
            #ifndef PLATFORM_CONSOLE
            float x2, y2;
            m_DownIcon.GetScreenSize( x2, y2 );
            float bottom_y  = GetCurrentContainerBottomY() - y2;
            float diff      = bottom_y - ( top_y + y );
            if( diff < 0 )
            {
                top_y += diff / 2;
                bottom_y -= diff / 2;
            }
            m_DownIcon.SetPos( 0, bottom_y );
            #endif
        }
    }
References Math::Clamp(), GetCurrentContainerBottomY(), GetCurrentContainerTopY(), m_DownIcon, m_IsActive, m_UpIcon, x, and y.
Referenced by Refresh(), and SetActive().
Member Data Documentation
m_ContentParent
protected Widget LeftArea::m_ContentParent private
Definition at line 5 of file leftarea.c.
Referenced by LeftArea(), and UpdateInterval().
m_ContentResize
protected ref SizeToChild LeftArea::m_ContentResize private
Definition at line 8 of file leftarea.c.
Referenced by LeftArea(), and UpdateInterval().
m_DownIcon
protected Widget LeftArea::m_DownIcon private
Definition at line 4 of file leftarea.c.
Referenced by LeftArea(), and UpdateSelectionIcons().
m_IsProcessing
protected bool LeftArea::m_IsProcessing = false private
Definition at line 10 of file leftarea.c.
Referenced by OnChildAdd(), OnChildRemove(), and UpdateInterval().
m_ScrollWidget
protected ScrollWidget LeftArea::m_ScrollWidget private
Definition at line 7 of file leftarea.c.
Referenced by GetScrollWidget(), LeftArea(), Refresh(), and UpdateInterval().
m_ShouldChangeSize
protected bool LeftArea::m_ShouldChangeSize = true private
Definition at line 9 of file leftarea.c.
Referenced by Refresh(), and UpdateInterval().
m_UpIcon
protected Widget LeftArea::m_UpIcon private
Definition at line 3 of file leftarea.c.
Referenced by LeftArea(), and UpdateSelectionIcons().
m_VicinityContainer
protected ref VicinityContainer LeftArea::m_VicinityContainer private
Definition at line 6 of file leftarea.c.
Referenced by DraggingOverHeader(), GetVicinityContainer(), LeftArea(), and OnLeftPanelDropReceived().