DayzKode: OpenItem Class Reference
OpenItem Class Reference
Static Private Member Functions
static void OpenAndSwitch (ItemBase item_tool, ItemBase item_target, PlayerBase player, float specialty_weight=0)
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
static void SwitchItems (EntityAI old_item, PlayerBase player, float spill_modificator, float specialty_weight)
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Detailed Description
Definition at line 1 of file openitem.c.
Member Function Documentation
OpenAndSwitch()
static void OpenItem::OpenAndSwitch (ItemBase item_tool, ItemBase item_target, PlayerBase player, float specialty_weight = 0) inline static private
WIll open the 'item_target' by spawning a new entity and transferring item variables to the new one.
Definition at line 4 of file openitem.c.
    {
        array<int> spill_range = new array<int>;
        if( item_tool.ConfigIsExisting("OpenItemSpillRange") )
        {
            item_tool.ConfigGetIntArray("OpenItemSpillRange", spill_range );
        }
        else
        {
            Debug.LogError("OpenItemSpillRange config parameter missing, default values used ! ");
            Error("OpenItemSpillRange config parameter missing, default values used !");
            spill_range.Insert(0);
            spill_range.Insert(100);
        }
        float spill_modificator = Math.RandomIntInclusive( spill_range.Get(0),spill_range.Get(1) ) / 100;
        OpenItem.SwitchItems(item_target, player, spill_modificator, specialty_weight);
    }
References Error(), Debug::LogError(), Math::RandomIntInclusive(), and SwitchItems().
Referenced by RecipeBase::Do().
SwitchItems()
static void OpenItem::SwitchItems (EntityAI old_item, PlayerBase player, float spill_modificator, float specialty_weight) inline static private
Will switch the 'item' for a new game entity, the new entity's classname will be formed by adding the 'suffix' to the classname of the old 'item'.
Definition at line 25 of file openitem.c.
    {
        string old_name = old_item.GetType();
        string new_name = old_name + "_Opened";
        OpenAndSwitchLambda l = new OpenAndSwitchLambda(old_item, new_name, player, spill_modificator, specialty_weight);
        l.SetTransferParams(true, true, true, true);
        MiscGameplayFunctions.TurnItemIntoItemEx(player, l);
    }
Referenced by OpenAndSwitch().