DayzKode: PMTPlayback Class Reference
PMTPlayback Class Reference
Private Member Functions
TFResult CheckOnePlaying ()
TFResult CheckOnePlayingSA ()
TFResult CheckOnePlayingSAAD ()
TFResult CheckStop (float dt)
void OnePlayingSAADEnded (ParticleSource p)
void OnePlayingSAEnded (ParticleSource p)
void PassOnePlaying (ParticleSource p)
void PMTPlayback ()
void StopEnded (ParticleSource p)
TFResult TestOnePlaying ()
TFResult TestOnePlayingStandAlone ()
TFResult TestOnePlayingStandAloneAutoDestroy ()
TFResult TestStopping ()
TFResult TestWiggleStress ()
Private Attributes
bool m_bOnePlayingSAADEnded = false
bool m_bOnePlayingSAEnded = false
bool m_bOnePlayingTestSuccess = false
bool m_bStopEnded = false
bool m_bStopWasResumed = false
bool m_bStopWasStopped = false
int m_OnePlayingManagerID
int m_OnePlayingSAADPSID
int m_OnePlayingSAPSID
ref array< ParticleSource > m_ParticleSources = new array<ParticleSource>()
float m_StopAccumulatedTime
int m_StopPSID
Static Private Attributes
static const float STOP_ACCUMULATED_TIME_PLAY_CUTOFF = 3
static const float STOP_ACCUMULATED_TIME_STOP_CUTOFF = 2
Detailed Description
Definition at line 1 of file pmtplayback.c.
Constructor & Destructor Documentation
PMTPlayback()
void PMTPlayback::PMTPlayback () inline private
Definition at line 29 of file pmtplayback.c.
    {
        //AddInitTest("TestOnePlaying");
        //AddInitTest("TestOnePlayingStandAloneAutoDestroy");
        //AddInitTest("TestOnePlayingStandAlone");
        //AddInitTest("TestWiggleStress");
        AddInitTest("TestStopping");
    }
References AddInitTest().
Member Function Documentation
CheckOnePlaying()
TFResult PMTPlayback::CheckOnePlaying () inline private
Definition at line 123 of file pmtplayback.c.
    {
        ParticleManager pm;
        if (GetManager(m_OnePlayingManagerID, pm))
        {
            if (pm)
            {
                ParticleSource p = pm.GetParticle(0);
                if (p.IsParticlePlaying())
                {
                    return NTFR(TFR.PENDING);
                }
                else
                {
                    return BTFR(m_bOnePlayingTestSuccess);
                }
            }
            else
            {
                return BTFR(Assert(false));
            }
        }
        else
        {
            return BTFR(Assert(false));
        }
    }
References Assert(), BTFR(), PMTF::GetManager(), ParticleSource::GetParticle(), ParticleSource::IsParticlePlaying(), m_bOnePlayingTestSuccess, m_OnePlayingManagerID, NTFR(), and ParticleManager().
CheckOnePlayingSA()
TFResult PMTPlayback::CheckOnePlayingSA () inline private
Definition at line 190 of file pmtplayback.c.
    {
        if (m_ParticleSources.IsValidIndex(m_OnePlayingSAPSID))
        {
            ParticleSource p = m_ParticleSources[m_OnePlayingSAPSID];
            if (p)
            {
                if (p.IsParticlePlaying())
                {
                    return NTFR(TFR.PENDING);
                }
                else
                {
                    // Clean up the Particle, no leaking from tests!
                    GetGame().ObjectDelete(p);
                    // Make sure the particle ended, if it did, then success!
                    return BTFR(m_bOnePlayingSAEnded);
                }
            }
            else
            {
                // It should not be gone, no autodestroy
                return BTFR(Assert(false));
            }
        }
        else
        {
            return BTFR(Assert(false));
        }
    }
References Assert(), BTFR(), GetGame(), ParticleSource::IsParticlePlaying(), m_bOnePlayingSAEnded, m_OnePlayingSAPSID, m_ParticleSources, NTFR(), and CGame::ObjectDelete().
CheckOnePlayingSAAD()
TFResult PMTPlayback::CheckOnePlayingSAAD () inline private
Definition at line 152 of file pmtplayback.c.
    {
        if (m_ParticleSources.IsValidIndex(m_OnePlayingSAADPSID))
        {
            ParticleSource p = m_ParticleSources[m_OnePlayingSAADPSID];
            if (p)
            {
                if (p.IsParticlePlaying())
                {
                    return NTFR(TFR.PENDING);
                }
                else
                {
                    if (m_bOnePlayingSAADEnded)
                    {
                        // There might be one frame where it is still alive before getting cleaned up
                        return NTFR(TFR.PENDING);
                    }
                    else
                    {
                        // Should be gone when no longer playing
                        return BTFR(Assert(false));
                    }
                }
            }
            else
            {
                // Make sure the particle ended, if it did, then success!
                return BTFR(m_bOnePlayingSAADEnded);
            }
        }
        else
        {
            return BTFR(Assert(false));
        }
    }
References Assert(), BTFR(), ParticleSource::IsParticlePlaying(), m_bOnePlayingSAADEnded, m_OnePlayingSAADPSID, m_ParticleSources, and NTFR().
CheckStop()
TFResult PMTPlayback::CheckStop (float dt) inline private
Definition at line 222 of file pmtplayback.c.
    {
        m_StopAccumulatedTime += dt;
        if (m_ParticleSources.IsValidIndex(m_StopPSID))
        {
            ParticleSource p = m_ParticleSources[m_StopPSID];
            if (p)
            {
                if (p.IsParticlePlaying())
                {
                    if (!m_bStopWasStopped && m_StopAccumulatedTime > STOP_ACCUMULATED_TIME_STOP_CUTOFF)
                    {
                        p.StopParticle();
                        m_StopAccumulatedTime = 0;
                        m_bStopWasStopped = true;
                    }
                    return NTFR(TFR.PENDING);
                }
                else
                {
                    // Means it was stopped before it was supposed to
                    // Possibly because particle length is shorter than STOP_ACCUMULATED_TIME_CUTOFF
                    if (!Assert(m_bStopWasStopped))
                    {
                        return BTFR(false);
                    }
                    else if (!m_bStopWasResumed && m_StopAccumulatedTime > STOP_ACCUMULATED_TIME_PLAY_CUTOFF)
                    {
                        p.PlayParticle();
                        m_bStopWasResumed = true;
                    }
                    else if (m_bStopEnded)
                    {
                        // Clean up the Particle, no leaking from tests!
                        GetGame().ObjectDelete(p);
                        return BTFR(true);
                    }
                    return NTFR(TFR.PENDING);
                }
            }
            else
            {
                // It should not be gone, no autodestroy
                return BTFR(Assert(false));
            }
        }
        else
        {
            return BTFR(Assert(false));
        }
    }
References Assert(), BTFR(), GetGame(), ParticleSource::IsParticlePlaying(), m_bStopEnded, m_bStopWasResumed, m_bStopWasStopped, m_ParticleSources, m_StopAccumulatedTime, m_StopPSID, NTFR(), CGame::ObjectDelete(), Particle::PlayParticle(), STOP_ACCUMULATED_TIME_PLAY_CUTOFF, STOP_ACCUMULATED_TIME_STOP_CUTOFF, and ParticleSource::StopParticle().
OnePlayingSAADEnded()
void PMTPlayback::OnePlayingSAADEnded (ParticleSource p) inline private
Definition at line 288 of file pmtplayback.c.
    {
        m_bOnePlayingSAADEnded = true;
    }
References m_bOnePlayingSAADEnded.
Referenced by TestOnePlayingStandAloneAutoDestroy().
OnePlayingSAEnded()
void PMTPlayback::OnePlayingSAEnded (ParticleSource p) inline private
Definition at line 294 of file pmtplayback.c.
    {
        m_bOnePlayingSAEnded = true;
    }
References m_bOnePlayingSAEnded.
Referenced by TestOnePlayingStandAlone().
PassOnePlaying()
void PMTPlayback::PassOnePlaying (ParticleSource p) inline private
Definition at line 280 of file pmtplayback.c.
    {
        m_bOnePlayingTestSuccess = true;
    }
References m_bOnePlayingTestSuccess.
Referenced by TestOnePlaying().
StopEnded()
void PMTPlayback::StopEnded (ParticleSource p) inline private
Definition at line 300 of file pmtplayback.c.
    {
        m_bStopEnded = true;
    }
References m_bStopEnded.
Referenced by TestStopping().
TestOnePlaying()
TFResult PMTPlayback::TestOnePlaying () inline private
Definition at line 42 of file pmtplayback.c.
    {
        ParticleManager pm = CreatePMFixedBlocking(1);
        m_OnePlayingManagerID = InsertManager(pm);
        DayZPlayer player = GetGame().GetPlayer();
        ParticleSource p = pm.CreateParticleById(ParticleList.EXPLOSION_LANDMINE, new ParticleProperties(player.GetPosition() + player.GetDirection() * 3, true));
        p.GetEvents().Event_OnParticleEnd.Insert(PassOnePlaying);
        AddFrameTest("CheckOnePlaying");
        return BTFR(p.IsParticlePlaying());
    }
References AddFrameTest(), BTFR(), PMTF::CreatePMFixedBlocking(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), PMTF::InsertManager(), ParticleSource::IsParticlePlaying(), m_OnePlayingManagerID, ParticleManager(), and PassOnePlaying().
TestOnePlayingStandAlone()
TFResult PMTPlayback::TestOnePlayingStandAlone () inline private
Definition at line 75 of file pmtplayback.c.
    {
        DayZPlayer player = GetGame().GetPlayer();
        ParticleSource p = ParticleSource.CreateParticle(ParticleList.EXPLOSION_LANDMINE, player.GetPosition() + player.GetDirection() * 3 - player.GetDirectionAside() * 3, true);
        p.GetEvents().Event_OnParticleEnd.Insert(OnePlayingSAEnded);
        p.DisableAutoDestroy();
        m_OnePlayingSAPSID = m_ParticleSources.Insert(p);
        AddFrameTest("CheckOnePlayingSA");
        return BTFR(p.IsParticlePlaying());
    }
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleSource::DisableAutoDestroy(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_OnePlayingSAPSID, m_ParticleSources, and OnePlayingSAEnded().
TestOnePlayingStandAloneAutoDestroy()
TFResult PMTPlayback::TestOnePlayingStandAloneAutoDestroy () inline private
Definition at line 59 of file pmtplayback.c.
    {
        DayZPlayer player = GetGame().GetPlayer();
        ParticleSource p = ParticleSource.CreateParticle(ParticleList.EXPLOSION_LANDMINE, player.GetPosition() + player.GetDirection() * 3 + player.GetDirectionAside() * 3, true);
        p.GetEvents().Event_OnParticleEnd.Insert(OnePlayingSAADEnded);
        m_OnePlayingSAADPSID = m_ParticleSources.Insert(p);
        AddFrameTest("CheckOnePlayingSAAD");
        return BTFR(p.IsParticlePlaying());
    }
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_OnePlayingSAADPSID, m_ParticleSources, and OnePlayingSAADEnded().
TestStopping()
TFResult PMTPlayback::TestStopping () inline private
Definition at line 104 of file pmtplayback.c.
    {
        DayZPlayer player = GetGame().GetPlayer();
        //ParticleSource p = ParticleSource.CreateParticle(ParticleList.EXPLOSION_LANDMINE, player.GetPosition() + player.GetDirection() * 4, true);
        ParticleSource p = ParticleSource.CreateParticle(ParticleList.EXPLOSION_LANDMINE, vector.Zero, true, player);
        p.GetEvents().Event_OnParticleEnd.Insert(StopEnded);
        p.DisableAutoDestroy();
        m_StopPSID = m_ParticleSources.Insert(p);
        AddFrameTest("CheckStop");
        return BTFR(p.IsParticlePlaying());
    }
References AddFrameTest(), BTFR(), ParticleSource::CreateParticle(), ParticleSource::DisableAutoDestroy(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), m_ParticleSources, m_StopPSID, StopEnded(), and vector::Zero.
TestWiggleStress()
TFResult PMTPlayback::TestWiggleStress () inline private
Definition at line 92 of file pmtplayback.c.
    {
        DayZPlayer player = GetGame().GetPlayer();
        ParticleSource p = ParticleSource.CreateParticle(ParticleList.ROADFLARE_BURNING_MAIN, player.GetPosition() + player.GetDirection() * 4, true);
        p.SetWiggle(90, 0.1);
        return BTFR(p.IsParticlePlaying());
    }
References BTFR(), ParticleSource::CreateParticle(), GetGame(), CGame::GetPlayer(), ParticleSource::IsParticlePlaying(), ParticleList::ROADFLARE_BURNING_MAIN, and ParticleSource::SetWiggle().
Member Data Documentation
m_bOnePlayingSAADEnded
bool PMTPlayback::m_bOnePlayingSAADEnded = false private
Definition at line 11 of file pmtplayback.c.
Referenced by CheckOnePlayingSAAD(), and OnePlayingSAADEnded().
m_bOnePlayingSAEnded
bool PMTPlayback::m_bOnePlayingSAEnded = false private
Definition at line 15 of file pmtplayback.c.
Referenced by CheckOnePlayingSA(), and OnePlayingSAEnded().
m_bOnePlayingTestSuccess
bool PMTPlayback::m_bOnePlayingTestSuccess = false private
Definition at line 7 of file pmtplayback.c.
Referenced by CheckOnePlaying(), and PassOnePlaying().
m_bStopEnded
bool PMTPlayback::m_bStopEnded = false private
Definition at line 24 of file pmtplayback.c.
Referenced by CheckStop(), and StopEnded().
m_bStopWasResumed
bool PMTPlayback::m_bStopWasResumed = false private
Definition at line 23 of file pmtplayback.c.
Referenced by CheckStop().
m_bStopWasStopped
bool PMTPlayback::m_bStopWasStopped = false private
Definition at line 22 of file pmtplayback.c.
Referenced by CheckStop().
m_OnePlayingManagerID
int PMTPlayback::m_OnePlayingManagerID private
Definition at line 6 of file pmtplayback.c.
Referenced by CheckOnePlaying(), and TestOnePlaying().
m_OnePlayingSAADPSID
int PMTPlayback::m_OnePlayingSAADPSID private
Definition at line 10 of file pmtplayback.c.
Referenced by CheckOnePlayingSAAD(), and TestOnePlayingStandAloneAutoDestroy().
m_OnePlayingSAPSID
int PMTPlayback::m_OnePlayingSAPSID private
Definition at line 14 of file pmtplayback.c.
Referenced by CheckOnePlayingSA(), and TestOnePlayingStandAlone().
m_ParticleSources
ref array<ParticleSource> PMTPlayback::m_ParticleSources = new array<ParticleSource>() private
Definition at line 3 of file pmtplayback.c.
Referenced by CheckOnePlayingSA(), CheckOnePlayingSAAD(), CheckStop(), TestOnePlayingStandAlone(), TestOnePlayingStandAloneAutoDestroy(), and TestStopping().
m_StopAccumulatedTime
float PMTPlayback::m_StopAccumulatedTime private
Definition at line 19 of file pmtplayback.c.
Referenced by CheckStop().
m_StopPSID
int PMTPlayback::m_StopPSID private
Definition at line 18 of file pmtplayback.c.
Referenced by CheckStop(), and TestStopping().
STOP_ACCUMULATED_TIME_PLAY_CUTOFF
const float PMTPlayback::STOP_ACCUMULATED_TIME_PLAY_CUTOFF = 3 static private
Definition at line 21 of file pmtplayback.c.
Referenced by CheckStop().
STOP_ACCUMULATED_TIME_STOP_CUTOFF
const float PMTPlayback::STOP_ACCUMULATED_TIME_STOP_CUTOFF = 2 static private
Definition at line 20 of file pmtplayback.c.
Referenced by CheckStop().