DayzKode: ClothingBase Class Reference
ClothingBase Class Reference
Private Member Functions
override bool CanDetachAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutAsAttachment (EntityAI parent)
override bool CanPutInCargo (EntityAI parent)
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override array< int > GetEffectWidgetTypes ()
override array< int > GetEffectWidgetTypes ()
override int GetGlassesEffectID ()
override int GetVoiceEffect ()
override bool IsObstructingVoice ()
void OnRemovedFromHead (PlayerBase player)
override void OnWasAttached (EntityAI parent, int slot_id)
override void OnWasDetached (EntityAI parent, int slot_id)
void ~BurlapSackCover ()
Private Attributes
PlayerBase m_Player
Detailed Description
Definition at line 1 of file burlapsackcover.c.
Constructor & Destructor Documentation
~BurlapSackCover()
void ClothingBase::~BurlapSackCover () inline private
Definition at line 5 of file burlapsackcover.c.
    {
        if( m_Player )
        {
            OnRemovedFromHead(m_Player);
        }
    }
References m_Player, and OnRemovedFromHead().
Member Function Documentation
CanDetachAttachment()
override bool ClothingBase::CanDetachAttachment (EntityAI parent) inline private
Definition at line 70 of file burlapsackcover.c.
    {
        PlayerBase player;
        Class.CastTo(player, GetHierarchyRootPlayer());
        return false; // (player && !player.IsAlive());
    }
References Class::CastTo().
CanPutAsAttachment() [1/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file dallasmask.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        bool headgear_present = false;
        if ( parent.FindAttachmentBySlotName( "Headgear" ) )
        {
            headgear_present = parent.FindAttachmentBySlotName( "Headgear" ).ConfigGetBool( "noMask" );
        }
        if ( ( GetNumberOfItems() == 0 || !parent || parent.IsMan() ) && !headgear_present )
        {
            return true;
        }
        return false;
    }
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [2/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file greathelm.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        Clothing eyewear = Clothing.Cast(parent.FindAttachmentBySlotName("Eyewear"));
        if ( eyewear && eyewear.ConfigGetBool("isStrap") )
        {
            return false;
        }
        Clothing mask = Clothing.Cast(parent.FindAttachmentBySlotName("Mask"));
        if ( mask && mask.ConfigGetBool("noHelmet") ) //TODO
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [3/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file guyfawkesmask.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        bool headgear_present = false;
        if ( parent.FindAttachmentBySlotName( "Headgear" ) )
        {
            headgear_present = parent.FindAttachmentBySlotName( "Headgear" ).ConfigGetBool( "noMask" );
        }
        if ( ( GetNumberOfItems() == 0 || !parent || parent.IsMan() ) && !headgear_present )
        {
            return true;
        }
        return false;
    }
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [4/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file hoxtonmask.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        bool headgear_present = false;
        if ( parent.FindAttachmentBySlotName( "Headgear" ) )
        {
            headgear_present = parent.FindAttachmentBySlotName( "Headgear" ).ConfigGetBool( "noMask" );
        }
        if ( ( GetNumberOfItems() == 0 || !parent || parent.IsMan() ) && !headgear_present )
        {
            return true;
        }
        return false;
    }
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutAsAttachment() [5/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file militaryboots_colorbase.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        if ( parent != this )
        {
            return true;
        }
        return false;
    }
CanPutAsAttachment() [6/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 8 of file weldingmask.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        Clothing eyewear = Clothing.Cast(parent.FindAttachmentBySlotName("Eyewear"));
        if ( eyewear && eyewear.ConfigGetBool("isStrap") )
        {
            return false;
        }
        Clothing mask = Clothing.Cast(parent.FindAttachmentBySlotName("Mask"));
        if ( mask && mask.ConfigGetBool("noHelmet") && !SantasBeard.Cast(mask) )
        {
            return false;
        }
        return true;
    }
CanPutAsAttachment() [7/7]
override bool ClothingBase::CanPutAsAttachment (EntityAI parent) inline private
Definition at line 3 of file wolfmask.c.
    {
        if(!super.CanPutAsAttachment(parent)) {return false;}
        bool headgear_present = false;
        if ( parent.FindAttachmentBySlotName( "Headgear" ) )
        {
            headgear_present = parent.FindAttachmentBySlotName( "Headgear" ).ConfigGetBool( "noMask" );
        }
        if ( ( GetNumberOfItems() == 0 || !parent || parent.IsMan() ) && !headgear_present )
        {
            return true;
        }
        return false;
    }
References GetNumberOfItems(), and EntityAI::IsMan().
CanPutInCargo()
override bool ClothingBase::CanPutInCargo (EntityAI parent) inline private
Definition at line 60 of file burlapsackcover.c.
    {
        if( !super.CanPutInCargo(parent) ) {return false;}
        if ( parent != this )
        {
            return true;
        }
        return false;
    }
EEItemLocationChanged()
override void ClothingBase::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc) inline private
Definition at line 13 of file burlapsackcover.c.
    {
        super.EEItemLocationChanged(oldLoc,newLoc);
        if (GetGame().IsDedicatedServer() && newLoc.GetType() == InventoryLocationType.GROUND)
        {
            if (m_Player)
            {
                MiscGameplayFunctions.TurnItemIntoItem(this, "BurlapSack", m_Player);
            }
        }
    }
References GetGame(), and m_Player.
GetEffectWidgetTypes() [1/2]
override array< int > ClothingBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file greathelm.c.
    {
        return {EffectWidgetsTypes.HELMET_OCCLUDER/*,EffectWidgetsTypes.HELMET_BREATH*/};
    }
GetEffectWidgetTypes() [2/2]
override array< int > ClothingBase::GetEffectWidgetTypes () inline private
Definition at line 3 of file weldingmask.c.
    {
        return {EffectWidgetsTypes.HELMET_OCCLUDER/*,EffectWidgetsTypes.HELMET_BREATH*/};
    }
GetGlassesEffectID()
override int ClothingBase::GetGlassesEffectID () inline private
Definition at line 27 of file weldingmask.c.
    {
        return PPERequesterBank.REQ_GLASSESWELDING;
    }
GetVoiceEffect()
override int ClothingBase::GetVoiceEffect () inline private
Definition at line 32 of file greathelm.c.
    {
        return VoiceEffectObstruction;
    }
IsObstructingVoice()
override bool ClothingBase::IsObstructingVoice () inline private
Definition at line 27 of file greathelm.c.
    {
        return true;
    }
OnRemovedFromHead()
void ClothingBase::OnRemovedFromHead (PlayerBase player) inline private
Definition at line 77 of file burlapsackcover.c.
    {
        if ( player.IsControlledPlayer() )
        {
            PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Stop();
            player.SetInventorySoftLock(false);
            player.SetMasterAttenuation("");
        }
        SetInvisibleRecursive(false,player,{InventorySlots.MASK,InventorySlots.EYEWEAR});
    }
Referenced by ~BurlapSackCover().
OnWasAttached()
override void ClothingBase::OnWasAttached (EntityAI parent, int slot_id) inline private
Definition at line 26 of file burlapsackcover.c.
    {
        super.OnWasAttached(parent, slot_id);
        Class.CastTo(m_Player, parent.GetHierarchyRootPlayer());
        //bool selected = player.IsPlayerSelected();//this is 0 upon player's connection to server
        if ( (!GetGame().IsDedicatedServer()) && m_Player && m_Player.IsControlledPlayer() && slot_id == InventorySlots.HEADGEAR )
        {
            //GetGame().GetWorld().SetAperture(100000);
            PPERequesterBank.GetRequester(PPERequester_BurlapSackEffects).Start();
            m_Player.SetInventorySoftLock(true);
            m_Player.SetMasterAttenuation("BurlapSackAttenuation");
            if ( GetGame().GetUIManager().IsMenuOpen(MENU_INVENTORY) )
            {
                GetGame().GetMission().HideInventory();
            }
        }
        SetInvisibleRecursive(true,m_Player,{InventorySlots.MASK,InventorySlots.EYEWEAR});
    }
References Class::CastTo(), GetGame(), CGame::GetMission(), Mission::HideInventory(), m_Player, and MENU_INVENTORY.
OnWasDetached()
override void ClothingBase::OnWasDetached (EntityAI parent, int slot_id) inline private
Definition at line 48 of file burlapsackcover.c.
    {
        super.OnWasDetached(parent, slot_id);
        if ( GetGame().IsServer() )
        {
            PlayerBase player;
            Class.CastTo(player, parent.GetHierarchyRootPlayer());
            //MiscGameplayFunctions.TurnItemIntoItem(this, "BurlapSack", player);
        }
    }
References Class::CastTo(), and GetGame().
Member Data Documentation
m_Player
PlayerBase ClothingBase::m_Player private
Definition at line 3 of file burlapsackcover.c.