DayzKode: GPSReceiver Class Reference
GPSReceiver Class Reference
Private Member Functions
protected int GetHiddenSelection (string selection)
void GPSReceiver ()
override bool IsTurnedOn ()
override void OnDebugSpawn ()
override void OnMovedInsideCargo (EntityAI container)
need to be overriden, otherwise the item will be turned off when moved to cargo
override void OnWork (float consumed_energy)
override void OnWorkStart ()
override void OnWorkStop ()
protected void PositionalUpdate ()
override void SetActions ()
protected void UpdateDisplayElevation ()
protected void UpdateDisplayPosition ()
protected void UpdateDisplayState (bool pIsTurnedOn)
Private Attributes
const string ANIM_PHASE_DISPLAY_HIDE = "DisplayState"
const string DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa"
protected ref array< int > m_AltitudeNumbersLast
protected ref set< string > m_DisplayAltSelections
protected ref set< string > m_DisplayGridSelections
protected ref map< int, string > m_DisplayNumericSignTextureMap
protected ref array< int > m_OrderedPositionNumbersLast
cache
Detailed Description
Definition at line 1 of file gpsreceiver.c.
Constructor & Destructor Documentation
GPSReceiver()
void GPSReceiver::GPSReceiver () inline private
translate numerical -1 to - texture
Definition at line 15 of file gpsreceiver.c.
    {
        m_OrderedPositionNumbersLast    = new array<int>;
        m_AltitudeNumbersLast           = new array<int>;
        int i;
        for (i = 0; i < MapNavigationBehaviour.DISPLAY_GRID_POS_MAX_CHARS_COUNT * 2; ++i)
        {
            m_OrderedPositionNumbersLast.Insert(0);
        }
        for (i = 0; i < MapNavigationBehaviour.DISPLAY_ALT_MAX_CHARS_COUNT; ++i)
        {
            m_AltitudeNumbersLast.Insert(0);
        }
        m_DisplayGridSelections = new set<string>();
        m_DisplayGridSelections.Insert("grid_1_0");
        m_DisplayGridSelections.Insert("grid_1_1");
        m_DisplayGridSelections.Insert("grid_1_2");
        m_DisplayGridSelections.Insert("grid_2_0");
        m_DisplayGridSelections.Insert("grid_2_1");
        m_DisplayGridSelections.Insert("grid_2_2");
        m_DisplayAltSelections = new set<string>();
        m_DisplayAltSelections.Insert("alt_0");
        m_DisplayAltSelections.Insert("alt_1");
        m_DisplayAltSelections.Insert("alt_2");
        m_DisplayAltSelections.Insert("alt_3");
        m_DisplayNumericSignTextureMap = new map<int, string>();
        for (i = -1; i < 11; i++)
        {
            string texturePath = string.Format(DISPLAY_TEXTURE_PATH_FORMAT, i);
            if (i == -1)
            {
                texturePath = string.Format(DISPLAY_TEXTURE_PATH_FORMAT, "dash");
            }
            m_DisplayNumericSignTextureMap.Insert(i, texturePath);
        }
    }
References DISPLAY_TEXTURE_PATH_FORMAT, string::Format(), m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Member Function Documentation
GetHiddenSelection()
protected int GPSReceiver::GetHiddenSelection (string selection) inline private
Definition at line 161 of file gpsreceiver.c.
    {
        int idx = GetHiddenSelectionIndex(selection);
        if (idx != INDEX_NOT_FOUND)
        {
            return idx;
        }
        else
        {
            return 0;
        }
    }
References INDEX_NOT_FOUND.
Referenced by UpdateDisplayElevation(), and UpdateDisplayPosition().
IsTurnedOn()
override bool GPSReceiver::IsTurnedOn () inline private
Definition at line 78 of file gpsreceiver.c.
    {
        return GetCompEM() && GetCompEM().IsWorking();
    }
OnDebugSpawn()
override void GPSReceiver::OnDebugSpawn () inline private
Definition at line 179 of file gpsreceiver.c.
    {
        Battery9V.Cast(GetInventory().CreateInInventory("Battery9V"));
    }
References CreateInInventory().
OnMovedInsideCargo()
override void GPSReceiver::OnMovedInsideCargo (EntityAI container) private
need to be overriden, otherwise the item will be turned off when moved to cargo
OnWork()
override void GPSReceiver::OnWork (float consumed_energy) inline private
Definition at line 112 of file gpsreceiver.c.
    {
        PositionalUpdate();
    }
References PositionalUpdate().
OnWorkStart()
override void GPSReceiver::OnWorkStart () inline private
Definition at line 84 of file gpsreceiver.c.
    {
        UpdateDisplayState(true);
        if (GetHierarchyRoot())
        {
            PlayerBase pb = PlayerBase.Cast(GetHierarchyRoot());
            if (pb)
            {
                pb.MapNavigationItemInPossession(this);
            }
        }
    }
References UpdateDisplayState().
OnWorkStop()
override void GPSReceiver::OnWorkStop () inline private
Definition at line 98 of file gpsreceiver.c.
    {
        UpdateDisplayState(false);
        if (GetHierarchyRoot())
        {
            PlayerBase pb = PlayerBase.Cast(GetHierarchyRoot());
            if (pb)
            {
                pb.MapNavigationItemNotInPossession(this);
            }
        }
    }
References UpdateDisplayState().
PositionalUpdate()
protected void GPSReceiver::PositionalUpdate () inline private
Definition at line 61 of file gpsreceiver.c.
    {
        UpdateDisplayPosition();
        UpdateDisplayElevation();
    }
References UpdateDisplayElevation(), and UpdateDisplayPosition().
Referenced by OnWork().
SetActions()
override void GPSReceiver::SetActions () inline private
Definition at line 70 of file gpsreceiver.c.
    {
        super.SetActions();
        AddAction(ActionTurnOnWhileInHands);
        AddAction(ActionTurnOffWhileInHands);
    }
References AddAction().
UpdateDisplayElevation()
protected void GPSReceiver::UpdateDisplayElevation () inline private
Definition at line 142 of file gpsreceiver.c.
    {
        int selectionIndex;
        string selectionName;
        array<int> altitudeNumbers = MapNavigationBehaviour.OrderedAltitudeNumbersPosition(this);
        if (altitudeNumbers.DifferentAtPosition(m_AltitudeNumbersLast) != INDEX_NOT_FOUND)
        {
            for (int i = 0; i < m_DisplayAltSelections.Count(); ++i)
            {
                selectionName   = m_DisplayAltSelections.Get(i);
                selectionIndex  = GetHiddenSelection(selectionName);
                SetObjectTexture(selectionIndex, m_DisplayNumericSignTextureMap.Get(altitudeNumbers.Get(i)));
            }
            m_AltitudeNumbersLast = altitudeNumbers;
        }
    }
References GetHiddenSelection(), INDEX_NOT_FOUND, m_AltitudeNumbersLast, m_DisplayAltSelections, m_DisplayNumericSignTextureMap, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayPosition()
protected void GPSReceiver::UpdateDisplayPosition () inline private
Definition at line 123 of file gpsreceiver.c.
    {
        int selectionIndex;
        string selectionName;
        array<int> orderedPositionNumbers = MapNavigationBehaviour.OrderedPositionNumbersFromGridCoords(this);
        if (orderedPositionNumbers.DifferentAtPosition(m_OrderedPositionNumbersLast) != INDEX_NOT_FOUND)
        {
            for (int i = 0; i < m_DisplayGridSelections.Count(); ++i)
            {
                selectionName   = m_DisplayGridSelections.Get(i);
                selectionIndex  = GetHiddenSelection(selectionName);
                SetObjectTexture(selectionIndex, m_DisplayNumericSignTextureMap.Get(orderedPositionNumbers.Get(i)));
            }
            m_OrderedPositionNumbersLast = orderedPositionNumbers;
        }
    }
References GetHiddenSelection(), INDEX_NOT_FOUND, m_DisplayGridSelections, m_DisplayNumericSignTextureMap, m_OrderedPositionNumbersLast, and MapNavigationBehaviour().
Referenced by PositionalUpdate().
UpdateDisplayState()
protected void GPSReceiver::UpdateDisplayState (bool pIsTurnedOn) inline private
Definition at line 118 of file gpsreceiver.c.
    {
        SetAnimationPhaseNow(ANIM_PHASE_DISPLAY_HIDE, !pIsTurnedOn);
    }
References ANIM_PHASE_DISPLAY_HIDE.
Referenced by OnWorkStart(), and OnWorkStop().
Member Data Documentation
ANIM_PHASE_DISPLAY_HIDE
const string GPSReceiver::ANIM_PHASE_DISPLAY_HIDE = "DisplayState" private
Definition at line 5 of file gpsreceiver.c.
Referenced by UpdateDisplayState().
DISPLAY_TEXTURE_PATH_FORMAT
const string GPSReceiver::DISPLAY_TEXTURE_PATH_FORMAT = "dz\\gear\\navigation\\data\\GPS_%1_ca.paa" private
Definition at line 4 of file gpsreceiver.c.
Referenced by GPSReceiver().
m_AltitudeNumbersLast
protected ref array<int> GPSReceiver::m_AltitudeNumbersLast private
Definition at line 13 of file gpsreceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayAltSelections
protected ref set<string> GPSReceiver::m_DisplayAltSelections private
Definition at line 8 of file gpsreceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayElevation().
m_DisplayGridSelections
protected ref set<string> GPSReceiver::m_DisplayGridSelections private
Definition at line 7 of file gpsreceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().
m_DisplayNumericSignTextureMap
protected ref map<int, string> GPSReceiver::m_DisplayNumericSignTextureMap private
Definition at line 9 of file gpsreceiver.c.
Referenced by GPSReceiver(), UpdateDisplayElevation(), and UpdateDisplayPosition().
m_OrderedPositionNumbersLast
protected ref array<int> GPSReceiver::m_OrderedPositionNumbersLast private
cache
Definition at line 12 of file gpsreceiver.c.
Referenced by GPSReceiver(), and UpdateDisplayPosition().