DayzKode: ErrorModuleHandler Class Reference
ErrorModuleHandler Class Reference
The error handler itself, for managing and distributing errors to modules Manages the ErrorHandlerModule instances inserted in Init. API comes with several functions to Create, Throw and extract data from error codes. The format used is an int which is made up of two shorts, one that holds the category and one that holds the code. Therefore when looking at an error code, it is much easier to identify when looking at the hex value.
Private Member Functions
private void Init ()
Gets called shortly after creation of ErrorModuleHandler.
void OnEvent (EventType eventTypeId, Param params)
is called by DayZGame to pass Events.
void SafeAddModule (notnull ErrorHandlerModule errorModule)
Wrapper for AddModule to give feedback whether it succeeded or not.
void SafeRemoveModule (ErrorCategory category)
Wrapper for RemoveModule to give feedback whether it succeeded or not.
void SafeRemoveModule (notnull ErrorHandlerModule errorModule)
Wrapper for RemoveModule to give feedback whether it succeeded or not.
Static Private Member Functions
static proto bool AddModule (ErrorCategory category, notnull ErrorHandlerModule errorModule)
Adds a module handler to the ErrorModuleHandler.
static proto int CreateError (ErrorCategory category, int code)
Creates full error code.
static proto ErrorCategory GetCategoryFromError (int errorCode)
Returns the category the error was thrown from.
static proto string GetClientMessage (ErrorCategory category, int code, string additionalInfo="")
Gets the Client Message for specified error.
static proto string GetClientMessageByCode (int errorCode, string additionalInfo="")
Gets the Client Message for specified error.
static proto int GetCodeFromError (int errorCode)
Returns the code of the error.
static proto owned string GetErrorHex (int errorCode)
Returns a formatted string of the error code.
static proto void GetErrorModules (notnull out array< ErrorHandlerModule > errorModules)
static proto native ErrorModuleHandler GetInstance ()
Gets the EMH Instance.
static proto string GetLastClientMessage (ErrorCategory category, int code)
Gets the Client Message for specified error, while attempting to restore information on the most recent error.
static proto string GetLastClientMessageByCode (int errorCode)
Gets the Client Message for specified error, while attempting to restore information on the most recent error.
static proto string GetLastServerMessage (ErrorCategory category, int code)
Gets the Server Message for specified error, while attempting to restore information on the most recent error.
static proto string GetLastServerMessageByCode (int errorCode)
Gets the Server Message for specified error, while attempting to restore information on the most recent error.
static proto string GetServerMessage (ErrorCategory category, int code, string additionalInfo="")
Gets the Server Message for specified error.
static proto string GetServerMessageByCode (int errorCode, string additionalInfo="")
Gets the Server Message for specified error.
static proto bool RemoveModule (ErrorCategory category)
Removes a module handler from the ErrorModuleHandler.
static proto int ThrowError (ErrorCategory category, int code, string additionalInfo="")
Creates and throws the error code, sending it to the handler of the category.
static proto int ThrowErrorCode (int errorCode, string additionalInfo="")
Throws the error code and sends it to the handler of the category.
Detailed Description
The error handler itself, for managing and distributing errors to modules Manages the ErrorHandlerModule instances inserted in Init. API comes with several functions to Create, Throw and extract data from error codes. The format used is an int which is made up of two shorts, one that holds the category and one that holds the code. Therefore when looking at an error code, it is much easier to identify when looking at the hex value.
Definition at line 28 of file errormodulehandler.c.
Member Function Documentation
AddModule()
static proto bool ErrorModuleHandler::AddModule (ErrorCategory category, notnull ErrorHandlerModule errorModule) static private
Adds a module handler to the ErrorModuleHandler.
Parameters
category ErrorCategory Category the module is for
errorModule ErrorHandlerModule The class containing the information and codes for the category.
Returns
bool Whether the adding of the module was successful or not
Referenced by SafeAddModule().
CreateError()
static proto int ErrorModuleHandler::CreateError (ErrorCategory category, int code) static private
Creates full error code.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
Returns
int The full error code
int errorCode = ErrorModuleHandler.CreateError(ErrorCategory.ConnectErrorClient, -1);
Print(errorCode);
>> errorCode = 196607
GetCategoryFromError()
static proto ErrorCategory ErrorModuleHandler::GetCategoryFromError (int errorCode) static private
Returns the category the error was thrown from.
Parameters
errorCode int The full error code
Returns
ErrorCategory The ErrorCategory the error was thrown from
ErrorCategory category = ErrorModuleHandler.GetCategoryFromError(0x0002FFFF);
Print(category);
>> category = 2
GetClientMessage()
static proto string ErrorModuleHandler::GetClientMessage (ErrorCategory category, int code, string additionalInfo = "") static private
Gets the Client Message for specified error.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
additionalInfo string Any additional info regarding the error, usually data
Returns
string The message which would appear on Client
Referenced by OnlineServices::ErrorCaught(), and ServerBrowserTab::OnLoadServersAsyncConsole().
GetClientMessageByCode()
static proto string ErrorModuleHandler::GetClientMessageByCode (int errorCode, string additionalInfo = "") static private
Gets the Client Message for specified error.
Parameters
errorCode int The full error code
additionalInfo string Any additional info regarding the error, usually data
Returns
string The message which would appear on Client
GetCodeFromError()
static proto int ErrorModuleHandler::GetCodeFromError (int errorCode) static private
Returns the code of the error.
Parameters
errorCode int The full error code
Returns
int The code of the error
int code = ErrorModuleHandler.GetCodeFromError(0x0002FFFF);
Print(code);
>> code = -1
Referenced by GetProperties(), and ConnectErrorScriptModuleUI::OnModalResult().
GetErrorHex()
static proto owned string ErrorModuleHandler::GetErrorHex (int errorCode) static private
Returns a formatted string of the error code.
Parameters
errorCode int The full error code
Returns
string A formatted string of the error code
string formattedCode = ErrorModuleHandler.GetErrorHex(196607);
Print(formattedCode);
>> formattedCode = '0x0002FFFF'
Referenced by GetLastClientMessage(), GetLastServerMessage(), GetProperties(), ErrorHandlerModule::GetSimpleMessage(), HandleError(), ErrorHandlerModule::OnErrorThrown(), and OnErrorThrown().
GetErrorModules()
static proto void ErrorModuleHandler::GetErrorModules (notnull out array< ErrorHandlerModule > errorModules) static private
Referenced by OnEvent().
GetInstance()
static proto native ErrorModuleHandler ErrorModuleHandler::GetInstance () static private
Gets the EMH Instance.
Returns
ErrorModuleHandler The ErrorModuleHandler Instance
Referenced by OnEvent(), and EnProfilerTests::TestFuncCountData().
GetLastClientMessage()
static proto string ErrorModuleHandler::GetLastClientMessage (ErrorCategory category, int code) static private
Gets the Client Message for specified error, while attempting to restore information on the most recent error.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
Returns
string The message which would appear on Client
GetLastClientMessageByCode()
static proto string ErrorModuleHandler::GetLastClientMessageByCode (int errorCode) static private
Gets the Client Message for specified error, while attempting to restore information on the most recent error.
Parameters
errorCode int The full error code
Returns
string The message which would appear on Client
GetLastServerMessage()
static proto string ErrorModuleHandler::GetLastServerMessage (ErrorCategory category, int code) static private
Gets the Server Message for specified error, while attempting to restore information on the most recent error.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
Returns
string The message which would appear on Server
GetLastServerMessageByCode()
static proto string ErrorModuleHandler::GetLastServerMessageByCode (int errorCode) static private
Gets the Server Message for specified error, while attempting to restore information on the most recent error.
Parameters
errorCode int The full error code
Returns
string The message which would appear on Server
GetServerMessage()
static proto string ErrorModuleHandler::GetServerMessage (ErrorCategory category, int code, string additionalInfo = "") static private
Gets the Server Message for specified error.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
additionalInfo string Any additional info regarding the error, usually data
Returns
string The message which would appear on Server
GetServerMessageByCode()
static proto string ErrorModuleHandler::GetServerMessageByCode (int errorCode, string additionalInfo = "") static private
Gets the Server Message for specified error.
Parameters
errorCode int The full error code
additionalInfo string Any additional info regarding the error, usually data
Returns
string The message which would appear on Server
Init()
private void ErrorModuleHandler::Init () inline private
Gets called shortly after creation of ErrorModuleHandler.
Definition at line 240 of file errormodulehandler.c.
    {
        if (!g_Game.IsDedicatedServer())
        {
            SafeAddModule(new ConnectErrorClientModule);
            SafeAddModule(new ConnectErrorServerModule);
            SafeAddModule(new ConnectErrorScriptModule);
        }
        SafeAddModule(new ClientKickedModule);
        SafeAddModule(new BIOSErrorModule);
    }
References ConnectErrorScriptModule(), g_Game, and SafeAddModule().
OnEvent()
void ErrorModuleHandler::OnEvent (EventType eventTypeId, Param params) inline private
is called by DayZGame to pass Events.
Definition at line 255 of file errormodulehandler.c.
    {
        array<ErrorHandlerModule> errorModules = new array<ErrorHandlerModule>;
        GetErrorModules(errorModules);
        foreach (ErrorHandlerModule module : errorModules)
        {
            module.OnEvent(eventTypeId, params);
        }
    }
References GetErrorModules().
Referenced by OnEvent().
RemoveModule()
static proto bool ErrorModuleHandler::RemoveModule (ErrorCategory category) static private
Removes a module handler from the ErrorModuleHandler.
Parameters
category ErrorCategory Category the module is for
Returns
bool Whether the removing of the module was successful or not
Referenced by SafeRemoveModule().
SafeAddModule()
void ErrorModuleHandler::SafeAddModule (notnull ErrorHandlerModule errorModule) inline private
Wrapper for AddModule to give feedback whether it succeeded or not.
Parameters
errorModule ErrorHandlerModule The ErrorHandlerModule to add
Definition at line 211 of file errormodulehandler.c.
    {
        if ( !AddModule(errorModule.GetCategory(), errorModule) )
            Error(string.Format("[EMH] Adding %1 failed. (Category: %2)", errorModule, errorModule.GetCategory()));
    }
References AddModule(), and Error().
Referenced by Init().
SafeRemoveModule() [1/2]
void ErrorModuleHandler::SafeRemoveModule (ErrorCategory category) inline private
Wrapper for RemoveModule to give feedback whether it succeeded or not.
Parameters
category ErrorCategory Category to remove
Definition at line 231 of file errormodulehandler.c.
    {
        if ( !RemoveModule(category) )
            Error(string.Format("[EMH] Removing %1 failed.", category));
    }
References Error(), and RemoveModule().
SafeRemoveModule() [2/2]
void ErrorModuleHandler::SafeRemoveModule (notnull ErrorHandlerModule errorModule) inline private
Wrapper for RemoveModule to give feedback whether it succeeded or not.
Parameters
errorModule ErrorHandlerModule The ErrorHandlerModule to add
Definition at line 221 of file errormodulehandler.c.
    {
        if ( !RemoveModule(errorModule.GetCategory()) )
            Error(string.Format("[EMH] Removing %1 failed. (Category: %2)", errorModule, errorModule.GetCategory()));
    }
References Error(), and RemoveModule().
ThrowError()
static proto int ErrorModuleHandler::ThrowError (ErrorCategory category, int code, string additionalInfo = "") static private
Creates and throws the error code, sending it to the handler of the category.
Parameters
category ErrorCategory Category the error is thrown from
code int The code that the error belongs to inside the category between [-32768, 32767]
additionalInfo string Any additional info regarding the error, usually data
Returns
int The full error code
int errorCode = ErrorModuleHandler.ThrowError(ErrorCategory.ConnectErrorClient, -1);
Print(errorCode);
>> errorCode = 196607
Referenced by TryConnect().
ThrowErrorCode()
static proto int ErrorModuleHandler::ThrowErrorCode (int errorCode, string additionalInfo = "") static private
Throws the error code and sends it to the handler of the category.
Parameters
errorCode int The full error code
additionalInfo string Any additional info regarding the error, usually data
Returns
int The full error code
int errorCode = ErrorModuleHandler.ThrowErrorCode(0x0002FFFF);
Print(errorCode);
>> errorCode = 196607