DayzKode: ActionDigGardenPlot Class Reference
ActionDigGardenPlot Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
void ActionDigGardenPlot ()
void CheckSurfaceBelowGardenPlot (PlayerBase player, GardenPlot item_GP, Hologram hologram)
override void OnFinishProgressClient (ActionData action_data)
override void OnFinishProgressServer (ActionData action_data)
override void SetupAnimation (ItemBase item)
Private Attributes
GardenPlot m_GardenPlot
Detailed Description
Definition at line 17 of file actiondiggardenplot.c.
Constructor & Destructor Documentation
ActionDigGardenPlot()
void ActionDigGardenPlot::ActionDigGardenPlot () inline private
Definition at line 21 of file actiondiggardenplot.c.
    {
        m_CallbackClass = ActionDigGardenPlotCB;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_LOW;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIGMANIPULATE;
        m_Text = "#make_garden_plot";
    }
References m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_LOW.
Member Function Documentation
ActionCondition()
override bool ActionDigGardenPlot::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 32 of file actiondiggardenplot.c.
    {
        //Client
        if ( !GetGame().IsDedicatedServer() )
        {
            //Action not allowed if player has broken legs
            if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
                return false;
            if ( player.IsPlacingLocal() )
            {
                Hologram hologram = player.GetHologramLocal();
                GardenPlot item_GP;
                Class.CastTo(item_GP,  hologram.GetProjectionEntity() );
                CheckSurfaceBelowGardenPlot(player, item_GP, hologram);
                if ( !hologram.IsColliding() )
                {
                    return true;
                }
            }
            return false;
        }
        //Server
        return true;
    }
References Class::CastTo(), CheckSurfaceBelowGardenPlot(), GetGame(), Hologram::GetProjectionEntity(), and Hologram::IsColliding().
CheckSurfaceBelowGardenPlot()
void ActionDigGardenPlot::CheckSurfaceBelowGardenPlot (PlayerBase player, GardenPlot item_GP, Hologram hologram) inline private
Definition at line 67 of file actiondiggardenplot.c.
    {
        vector min_max[2];
        item_GP.GetCollisionBox(min_max);
        float offset = min_max[1][1] - min_max[0][1];
        //Print(offset);
        vector pos_adjusted = item_GP.GetPosition();
        pos_adjusted[1] = pos_adjusted[1] + offset;
        if ( item_GP.CanBePlaced(player, /*item_GP.GetPosition()*/pos_adjusted )  )
        {
            if ( item_GP.CanBePlaced(NULL, item_GP.CoordToParent(hologram.GetLeftCloseProjectionVector())) )
            {
                if ( item_GP.CanBePlaced(NULL, item_GP.CoordToParent(hologram.GetRightCloseProjectionVector())) )
                {
                    if ( item_GP.CanBePlaced(NULL, item_GP.CoordToParent(hologram.GetLeftFarProjectionVector())) )
                    {
                        if ( item_GP.CanBePlaced(NULL, item_GP.CoordToParent(hologram.GetRightFarProjectionVector())) )
{
                            hologram.SetIsCollidingGPlot( false );
                            return;
                        }
                    }
                }
            }
        }
        hologram.SetIsCollidingGPlot( true );
    }
References Hologram::GetLeftCloseProjectionVector(), Hologram::GetLeftFarProjectionVector(), Hologram::GetRightCloseProjectionVector(), Hologram::GetRightFarProjectionVector(), and Hologram::SetIsCollidingGPlot().
Referenced by ActionCondition().
OnFinishProgressClient()
override void ActionDigGardenPlot::OnFinishProgressClient (ActionData action_data) inline private
Definition at line 98 of file actiondiggardenplot.c.
    {
    }
OnFinishProgressServer()
override void ActionDigGardenPlot::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 103 of file actiondiggardenplot.c.
    {
        PlaceObjectActionData poActionData;
        poActionData = PlaceObjectActionData.Cast(action_data);
        EntityAI entity_for_placing = action_data.m_MainItem;
        vector position = action_data.m_Player.GetLocalProjectionPosition();
        vector orientation = action_data.m_Player.GetLocalProjectionOrientation();
        if ( GetGame().IsMultiplayer() )
        {
            m_GardenPlot = GardenPlot.Cast( action_data.m_Player.GetHologramServer().PlaceEntity( entity_for_placing ));
            m_GardenPlot.SetOrientation( orientation );
            action_data.m_Player.GetHologramServer().CheckPowerSource();
            action_data.m_Player.PlacingCompleteServer();
            m_GardenPlot.OnPlacementComplete( action_data.m_Player );
        }
        //local singleplayer
        if ( !GetGame().IsMultiplayer())
        {
            m_GardenPlot = GardenPlot.Cast( action_data.m_Player.GetHologramLocal().PlaceEntity( entity_for_placing ));
            m_GardenPlot.SetOrientation( orientation );
            action_data.m_Player.PlacingCompleteLocal();
            m_GardenPlot.OnPlacementComplete( action_data.m_Player );
        }
        GetGame().ClearJuncture( action_data.m_Player, entity_for_placing );
        action_data.m_MainItem.SetIsBeingPlaced( false );
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
        poActionData.m_AlreadyPlaced = true;
        action_data.m_MainItem.SoundSynchRemoteReset();
        MiscGameplayFunctions.DealAbsoluteDmg(action_data.m_MainItem, 10);
    }
References CGame::ClearJuncture(), GetGame(), PlaceObjectActionData::m_AlreadyPlaced, m_GardenPlot, ActionData::m_MainItem, ActionData::m_Player, and m_SpecialtyWeight.
SetupAnimation()
override void ActionDigGardenPlot::SetupAnimation (ItemBase item) inline private
Definition at line 59 of file actiondiggardenplot.c.
    {
        if ( item )
        {
            m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DIG;
        }
    }
Member Data Documentation
m_GardenPlot
GardenPlot ActionDigGardenPlot::m_GardenPlot private
Definition at line 19 of file actiondiggardenplot.c.
Referenced by OnFinishProgressServer().