DayzKode: Serializer Class Reference
Serializer Class Reference
Serialization general interface. Serializer API works with:
Private Member Functions
proto bool Read (void value_in)
protected void Serializer ()
proto bool Write (void value_out)
protected void ~Serializer ()
Detailed Description
Serialization general interface. Serializer API works with:
primitive types: int, float, string, bool, vector
dynamic containers: array, set, map
static arrays
complex types: classes
Note
Serializer provides deep serialization (it serialize class memebers and their members etc). To avoid serialization of certain class variable, use NonSerialized attribute.
usage:
class MyData
{
 int m_id;
 autoptr map<string, float> m_values;
 [NonSerialized()]
 string m_dbg; // I don't want to serialize this variable
}
void Serialize(Serializer s)
{
 int statArray[4] = {6,9,2,3};
 array<int> dynArray = {8,5,6,4};
 autoptr MyData data = new MyData();
 data.m_id = 965;
 data.m_values = map<string, float>;
 data.m_values.Insert("value1", 5.98);
 data.m_values.Insert("value2", 4.36);
 s.Write(10);
 s.Write("Hello");
 s.Write(statArray);
 s.Write(dynArray);
 s.Write(data);
}
void Deserialize(Serializer s)
{
 int statArray[4];
 array<int> dynArray;
 MyData data;
 int someInt;
 string someString;
 s.Read(someInt);
 s.Read(someString);
 s.Read(statArray);
 s.Read(dynArray);
 s.Read(data);
}
Definition at line 55 of file serializer.c.
Constructor & Destructor Documentation
Serializer()
protected void Serializer::Serializer () inline private
Definition at line 60 of file serializer.c.
{}
~Serializer()
protected void Serializer::~Serializer () inline private
Definition at line 61 of file serializer.c.
{}
Member Function Documentation
Read()
proto bool Serializer::Read (void value_in) private
Referenced by CreateHandEventFromContext(), CreateWeaponEventFromContext(), MenuDefaultCharacterData::DeserializeCharacterData(), Param::Deserializer(), Param7< Class T1, Class T2, Class T3, Class T4, Class T5, Class T6, Class T7 >::Deserializer(), Param8< Class T1, Class T2, Class T3, Class T4, Class T5, Class T6, Class T7, Class T8 >::Deserializer(), SyncEvents::Event_OnRPC(), FillAgentArray(), FillServerFinalVars(), PluginBase::GetRPCModifierID(), PluginBase::GetRPCModifierLock(), PluginBase::GetRPCUpdateState(), HandleInputData(), PluginBase::HandlePresetSpawn(), ManBase::HandleRemoteItemManipulation(), PluginBase::HandleSetTime(), InventoryItem::LoadAgents(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::LoadAndSetCurrentFSMState(), WeaponStateBase::LoadCurrentFSMState(), LoadCurrentFSMState(), InventoryItem::LoadVariables(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputForRemote(), OnInputFromServer(), OnInputUserDataProcess(), ActionManagerServer::OnInputUserDataProcess(), WeaponManager::OnInputUserDataProcess(), ManBase::OnInputUserDataProcess(), OnInputUserDataReceived(), OnInventoryJunctureFromServer(), SymptomManager::OnRPC(), CfgGameplayHandler::OnRPC(), UndergroundAreaLoader::OnRPC(), Managed::OnRPC(), PluginBase::OnRPC(), WrittenNoteData::OnRPC(), InventoryItemSuper::OnRPC(), InventoryItem::OnRPC(), Clothing::OnRPC(), ManBase::OnRPC(), Trigger::OnRPC(), OnRPC(), PluginBase::OnRPCAgents(), SymptomManager::OnRPCDebug(), UIScriptedMenu::OnRPCEx(), DebugMonitorValues::OnRPCFloat(), PluginBase::OnRPCLevels(), PluginBase::OnRPCMods(), PluginBase::OnRPCModsDetailed(), PluginBase::OnRPCServerLogRecieved(), DeveloperTeleport::OnRPCSetPlayerDirection(), DeveloperTeleport::OnRPCSetPlayerPosition(), PluginBase::OnRPCSpawnEntity(), PluginBase::OnRPCSpawnEntityOnCursorDir(), PluginBase::OnRPCSpawnEntityOnGround(), PluginBase::OnRPCSpawnEntityOnGroundPatternGrid(), PluginBase::OnRPCStats(), PluginBase::OnRPCStatSet(), PluginBase::OnRPCStomach(), DebugMonitorValues::OnRPCString(), PluginBase::OnRPCSyncSceneObject(), PluginBase::OnRPCTemp(), OnServerInventoryCommandStatic(), OnSetEntityRequest(), OnSetEntityRPC(), PlayerStatBase::OnStoreLoad(), BleedingSourcesManagerBase::OnStoreLoad(), OnStoreLoad(), SymptomManager::OnStoreLoad(), PlayerAgentPool::OnStoreLoad(), StaticTransmitter::OnStoreLoad(), InventoryItemSuper::OnStoreLoad(), Weapon::OnStoreLoad(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreLoad(), ItemBase::OnStoreLoad(), InventoryItem::OnStoreLoad(), Barrel_ColorBase::OnStoreLoad(), BaseBuildingBase::OnStoreLoad(), FireplaceBase::OnStoreLoad(), AlarmClock_ColorBase::OnStoreLoad(), FireworksLauncher::OnStoreLoad(), KitchenTimer::OnStoreLoad(), Grenade_Base::OnStoreLoad(), Inventory_Base::OnStoreLoad(), Roadflare::OnStoreLoad(), FlammableBase::OnStoreLoad(), ItemTransmitter::OnStoreLoad(), ManBase::OnStoreLoad(), ItemBase::OnStoreLoadCustom(), ManBase::OnStoreLoadLifespan(), OnSyncJuncture(), ActionManagerBase::OnSyncJuncture(), WeaponManager::OnSyncJuncture(), InventoryItem::OnSyncVariables(), HumanInventory::ProccessInputData(), ProccessInputData(), ReadAdditionalStaminaInfo(), DayZPlayerSyncJunctures::ReadBrokenLegsParams(), DayZPlayerSyncJunctures::ReadBrokenLegsParamsEx(), DayZPlayerSyncJunctures::ReadDamageHitParams(), DayZPlayerSyncJunctures::ReadDamageHitParamsEx(), DayZPlayerSyncJunctures::ReadDeathParams(), HandEventDrop::ReadFromContext(), HandEventBase::ReadFromContext(), InventoryLocation::ReadFromContext(), ReadFromContext(), ActionBuildPart::ReadFromContext(), ActionDrinkPondContinuous::ReadFromContext(), ActionFillBottleBase::ReadFromContext(), ActionFishingNew::ReadFromContext(), ActionRepairCarChassis::ReadFromContext(), ActionRepairCarEngine::ReadFromContext(), ActionRepairCarPart::ReadFromContext(), ActionRepairPart::ReadFromContext(), ActionRepairTent::ReadFromContext(), ActionRepairTentPart::ReadFromContext(), ActionTransferLiquid::ReadFromContext(), ActionWorldCraft::ReadFromContext(), ActionCarHornLong::ReadFromContext(), ActionDebug::ReadFromContext(), ActionBuildShelter::ReadFromContext(), DayZPlayerSyncJunctures::ReadInjuryParams(), DayZPlayerSyncJunctures::ReadKuruRequest(), ManBase::ReadLiftWeaponRequest(), DayZPlayerSyncJunctures::ReadPlayerFBModifier(), DayZPlayerSyncJunctures::ReadPlayerSymptomADDParams(), DayZPlayerSyncJunctures::ReadPlayerSymptomFBParams(), DayZPlayerSyncJunctures::ReadPlayerUnconsciousnessParams(), DayZPlayerSyncJunctures::ReadShockParams(), InventoryItem::ReadVarsFromCTX(), PlayerAgentPool::RemoteGrowRequestDebug(), SymptomManager::SetAnimation(), ManBase::SetLiftWeapon(), ManBase::SetToDelete(), SyncReceiveActivateCommand(), SyncReceiveInitDebugObject(), SyncReceiveMessage(), SyncReceiveValueBool(), SyncReceiveValueFloat(), and SyncReceiveValueInt().
Write()
proto bool Serializer::Write (void value_out) private
Referenced by ActionManagerClient::ActionStart(), InventoryItem::CombineItemsClient(), ActionMeasureTemperatureSelf::OnFinishProgressServer(), ActionMeasureTemperatureTarget::OnFinishProgressServer(), OnInputUserDataProcess(), InventoryItem::OnRightClick(), BleedingSourcesManagerBase::OnStoreSave(), OnStoreSave(), PlayerStatBase::OnStoreSave(), SymptomManager::OnStoreSave(), PlayerAgentPool::OnStoreSave(), StaticTransmitter::OnStoreSave(), InventoryItemSuper::OnStoreSave(), Weapon::OnStoreSave(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::OnStoreSave(), ItemBase::OnStoreSave(), InventoryItem::OnStoreSave(), Barrel_ColorBase::OnStoreSave(), BaseBuildingBase::OnStoreSave(), FireplaceBase::OnStoreSave(), AlarmClock_ColorBase::OnStoreSave(), FireworksLauncher::OnStoreSave(), KitchenTimer::OnStoreSave(), Grenade_Base::OnStoreSave(), Inventory_Base::OnStoreSave(), Roadflare::OnStoreSave(), FlammableBase::OnStoreSave(), ItemTransmitter::OnStoreSave(), ManBase::OnStoreSave(), ItemBase::OnStoreSaveCustom(), ManBase::OnStoreSaveLifespan(), ManBase::ReadLiftWeaponRequest(), ActionManagerClient::RequestInterruptAction(), RequestPlayerInfo(), ManBase::RequestResetADSSync(), PluginBase::RequestUniversalTemperatureSources(), InventoryItem::SaveAgents(), ManBase::SaveAreaPersistenceFlag(), WeaponStateBase::SaveCurrentFSMState(), SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentFSMState(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::SaveCurrentUnstableFSMState(), InventoryItem::SaveVariables(), DayZPlayerSyncJunctures::SendActionAcknowledgment(), DayZPlayerSyncJunctures::SendBrokenLegs(), DayZPlayerSyncJunctures::SendBrokenLegsEx(), DayZPlayerSyncJunctures::SendDamageHit(), DayZPlayerSyncJunctures::SendDamageHitEx(), DayZPlayerSyncJunctures::SendDeath(), PluginBase::SendDebug(), DayZPlayerSyncJunctures::SendDeleteItem(), SendEmoteRequestSync(), DayZPlayerSyncJunctures::SendInjury(), DayZPlayerSyncJunctures::SendKuruRequest(), ManBase::SendLiftWeaponSync(), MissionBase::SendMuteListToServer(), NotificationSystem::SendNotificationToPlayerIdentity(), NotificationSystem::SendNotificationToPlayerIdentityExtended(), DayZPlayerSyncJunctures::SendPlayerFBModifier(), DayZPlayerSyncJunctures::SendPlayerSymptomADD(), DayZPlayerSyncJunctures::SendPlayerSymptomFB(), DayZPlayerSyncJunctures::SendPlayerUnconsciousness(), DayZPlayerSyncJunctures::SendQuickbarSetShortcut(), SendRPC(), DayZPlayerSyncJunctures::SendShock(), DayZPlayerSyncJunctures::SendWeaponActionAcknowledgment(), DayZPlayerSyncJunctures::SendWeaponJamChance(), Param::Serialize(), Param7< Class T1, Class T2, Class T3, Class T4, Class T5, Class T6, Class T7 >::Serialize(), Param8< Class T1, Class T2, Class T3, Class T4, Class T5, Class T6, Class T7, Class T8 >::Serialize(), MenuDefaultCharacterData::SerializeCharacterData(), InventoryInputUserData::SerializeDestroy(), InventoryInputUserData::SerializeHandEvent(), InventoryInputUserData::SerializeMove(), InventoryInputUserData::SerializeSwap(), ServerRequestEmoteCancel(), SetEntityShortcut(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), SyncAdditionalStaminaInfo(), Weapon::SyncEventToRemote(), SyncHandEventToRemote(), WeaponManager::Synchronize(), MissionBase::SyncRespawnModeInfo(), SyncStamina(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), VicinityContainer::TraverseShowedItems(), HumanInventory::Update(), ActionManagerClient::Update(), Update(), WriteToContext(), HandEventDrop::WriteToContext(), HandEventBase::WriteToContext(), InventoryLocation::WriteToContext(), WeaponEventBase::WriteToContext(), ActionBuildPart::WriteToContext(), ActionDrinkPondContinuous::WriteToContext(), ActionFillBottleBase::WriteToContext(), ActionFishingNew::WriteToContext(), ActionRepairCarChassis::WriteToContext(), ActionRepairCarEngine::WriteToContext(), ActionRepairCarPart::WriteToContext(), ActionRepairPart::WriteToContext(), ActionRepairTent::WriteToContext(), ActionRepairTentPart::WriteToContext(), ActionTransferLiquid::WriteToContext(), ActionWorldCraft::WriteToContext(), ActionCarHornLong::WriteToContext(), ActionDebug::WriteToContext(), ActionBuildShelter::WriteToContext(), and InventoryItem::WriteVarsToCTX().