DayzKode: RockBase Class Reference
RockBase Class Reference
Private Member Functions
int GetAmountOfDrops (ItemBase item)
float GetDamageToMiningItemEachDrop (ItemBase item)
void GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map)
override bool IsRock ()
Detailed Description
Definition at line 1 of file rockbase.c.
Member Function Documentation
GetAmountOfDrops()
int RockBase::GetAmountOfDrops (ItemBase item) inline private
Definition at line 8 of file rockbase.c.
    {
        if (item)
        {
            switch (item.GetType())
            {
            case "Pickaxe":
                return 4;
            case "SledgeHammer":
                return 8;
            }
        }
        return 1;
    }
Referenced by CAContinuousMineRock::GetMiningData().
GetDamageToMiningItemEachDrop()
float RockBase::GetDamageToMiningItemEachDrop (ItemBase item) inline private
Definition at line 50 of file rockbase.c.
    {
        if (item)
        {
            switch (item.GetType())
            {
            case "SledgeHammer":
            case "Pickaxe":
                return 20;
            case "Wrench":
            case "Screwdriver":
            case "MeatTenderizer":
                return 25;
            case "PipeWrench":
            case "Crowbar":
                return 50;
            case "Hammer":
                return 40;
            }
        }
        return 25;
    }
Referenced by CAContinuousMineRock::GetMiningData().
GetMaterialAndQuantityMap()
void RockBase::GetMaterialAndQuantityMap (ItemBase item, out map< string, int > output_map) inline private
Definition at line 25 of file rockbase.c.
    {
        if (item == null)
        {
            return;
        }
        switch (item.GetType())
        {
        case "Pickaxe":
        case "SledgeHammer":
        case "Hammer":
            output_map.Insert("Stone",1);
            break;
        case "PipeWrench":
        case "Wrench":
        case "Screwdriver":
        case "Crowbar":
        case "MeatTenderizer":
            output_map.Insert("SmallStone",1);
            break;
        }
    }
Referenced by CAContinuousMineRock::GetMiningData(), and ActionMineBase::GetYieldName().
IsRock()
override bool RockBase::IsRock () inline private
Definition at line 3 of file rockbase.c.
    {
        return true;
    }