DayzKode: ActionDestroyPart Class Reference
ActionDestroyPart Class Reference
Private Member Functions
override bool ActionCondition (PlayerBase player, ActionTarget target, ItemBase item)
override bool ActionConditionContinue (ActionData action_data)
void ActionDestroyPart ()
override bool CanBeUsedLeaning ()
override void CreateConditionComponents ()
protected bool DestroyCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
override string GetAdminLogMessage (ActionData action_data)
override void OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item)
override void OnFinishProgressServer (ActionData action_data)
Static Private Attributes
static int CYCLES = 4
Detailed Description
Definition at line 9 of file actiondestroypart.c.
Constructor & Destructor Documentation
ActionDestroyPart()
void ActionDestroyPart::ActionDestroyPart () inline private
Definition at line 13 of file actiondestroypart.c.
    {
        m_CallbackClass = ActionDestroyPartCB;
        m_CommandUID = DayZPlayerConstants.CMD_ACTIONFB_DISASSEMBLE;
        m_FullBody = true;
        m_StanceMask = DayZPlayerConstants.STANCEMASK_ERECT;
        m_SpecialtyWeight = UASoftSkillsWeight.ROUGH_HIGH;
        m_Text = "#destroy";
    }
References AnimatedActionBase::m_CallbackClass, AnimatedActionBase::m_CommandUID, m_FullBody, m_SpecialtyWeight, m_StanceMask, m_Text, and UASoftSkillsWeight::ROUGH_HIGH.
Member Function Documentation
ActionCondition()
override bool ActionDestroyPart::ActionCondition (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 41 of file actiondestroypart.c.
    {
        //Action not allowed if player has broken legs
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            return false;
        return DestroyCondition( player, target, item, true );
    }
References DestroyCondition().
ActionConditionContinue()
override bool ActionDestroyPart::ActionConditionContinue (ActionData action_data) inline private
Definition at line 50 of file actiondestroypart.c.
    {
        return DestroyCondition( action_data.m_Player, action_data.m_Target, action_data.m_MainItem , false );
    }
References DestroyCondition(), ActionData::m_MainItem, ActionData::m_Player, and ActionData::m_Target.
CanBeUsedLeaning()
override bool ActionDestroyPart::CanBeUsedLeaning () inline private
Definition at line 36 of file actiondestroypart.c.
    {
        return false;
    }
CreateConditionComponents()
override void ActionDestroyPart::CreateConditionComponents () inline private
Definition at line 24 of file actiondestroypart.c.
    {
        m_ConditionItem = new CCINonRuined;
        m_ConditionTarget = new CCTNone;
    }
References m_ConditionItem, and m_ConditionTarget.
DestroyCondition()
protected bool ActionDestroyPart::DestroyCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) inline private
Definition at line 87 of file actiondestroypart.c.
    {
        Object target_object = target.GetObject();
        if ( target_object && target_object.CanUseConstruction() )
        {
            string part_name = target_object.GetActionComponentName( target.GetComponentIndex() );
            BaseBuildingBase base_building = BaseBuildingBase.Cast( target_object );
            Construction construction = base_building.GetConstruction();
            ConstructionPart construction_part = construction.GetConstructionPartToDestroy( part_name );
            if ( construction_part )
            {
                //camera and position checks
                if ( !player.GetInputController().CameraIsFreeLook() && IsInReach(player, target, UAMaxDistances.DEFAULT) && !player.GetInputController().CameraIsFreeLook() )
                {
                    //Camera check (client-only)
                    if ( camera_check )
                    {
                        if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
{
                            if ( !base_building.IsFacingCamera( part_name ) )
{
                                return false;
                            }
                        }
                    }
                    ConstructionActionData construction_action_data = player.GetConstructionActionData();
                    construction_action_data.SetTargetPart( construction_part );
                    return true;
                }
            }
        }
        return false;
    }
References Construction(), UAMaxDistances::DEFAULT, GetGame(), BaseBuildingBase::IsFacingCamera(), IsInReach(), and ConstructionActionData::SetTargetPart().
Referenced by ActionCondition(), and ActionConditionContinue().
GetAdminLogMessage()
override string ActionDestroyPart::GetAdminLogMessage (ActionData action_data) inline private
Definition at line 126 of file actiondestroypart.c.
    {
        return " destroyed " + action_data.m_Target.GetObject().GetDisplayName() + " with " + action_data.m_MainItem.GetDisplayName();
    }
References ActionData::m_MainItem, and ActionData::m_Target.
OnActionInfoUpdate()
override void ActionDestroyPart::OnActionInfoUpdate (PlayerBase player, ActionTarget target, ItemBase item) inline private
Definition at line 30 of file actiondestroypart.c.
    {
        ConstructionActionData construction_action_data = player.GetConstructionActionData();
        m_Text = "#destroy " + construction_action_data.GetTargetPart();
    }
References ConstructionActionData::GetTargetPart(), and m_Text.
OnFinishProgressServer()
override void ActionDestroyPart::OnFinishProgressServer (ActionData action_data) inline private
Definition at line 55 of file actiondestroypart.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( action_data.m_Target.GetObject() );
        Construction construction = base_building.GetConstruction();
        ConstructionActionData construction_action_data = action_data.m_Player.GetConstructionActionData();
        ConstructionPart construction_part = construction_action_data.GetTargetPart();
        if ( construction.CanDestroyPart( construction_part.GetPartName() ) )
        {
            //build
            string part_name = construction_part.GetPartName();
            string zone_name;
            DamageSystem.GetDamageZoneFromComponentName(base_building,part_name,zone_name);
            if (zone_name != "")
            {
                base_building.AddHealth(zone_name,"Health",-(base_building.GetMaxHealth(zone_name,"")/CYCLES));
                if ( base_building.GetHealth(zone_name,"Health") < 1 )
                    construction.DestroyPartServer( action_data.m_Player, construction_part.GetPartName(), AT_DESTROY_PART );
            }
            else
            {
                construction.DestroyPartServer( action_data.m_Player, construction_part.GetPartName(), AT_DESTROY_PART );
            }
            //add damage to tool
            action_data.m_MainItem.DecreaseHealth( UADamageApplied.DESTROY, false );
        }
        action_data.m_Player.GetSoftSkillsManager().AddSpecialty( m_SpecialtyWeight );
    }
References AT_DESTROY_PART, Construction(), CYCLES, UADamageApplied::DESTROY, ConstructionPart::GetPartName(), ConstructionActionData::GetTargetPart(), ActionData::m_MainItem, ActionData::m_Player, m_SpecialtyWeight, and ActionData::m_Target.
Member Data Documentation
CYCLES
int ActionDestroyPart::CYCLES = 4 static private
Definition at line 11 of file actiondestroypart.c.
Referenced by ActionDestroyPartCB::CreateActionComponent(), and OnFinishProgressServer().