DayzKode: MushroomBase Class Reference
MushroomBase Class Reference
Private Member Functions
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
override bool CanDecay ()
override void EEOnCECreate ()
override bool IsMushroom ()
override void SetActions ()
Detailed Description
Definition at line 1 of file mushroombase.c.
Member Function Documentation
CanBeCooked()
override bool MushroomBase::CanBeCooked () inline private
Definition at line 8 of file mushroombase.c.
    {
        return true;
    }
CanBeCookedOnStick()
override bool MushroomBase::CanBeCookedOnStick () inline private
Definition at line 3 of file mushroombase.c.
    {
        return true;
    }
CanDecay()
override bool MushroomBase::CanDecay () inline private
Definition at line 18 of file mushroombase.c.
    {
        return true;
    }
EEOnCECreate()
override void MushroomBase::EEOnCECreate () inline private
Definition at line 31 of file mushroombase.c.
    {
        int rand = Math.RandomInt(0,10);
        if ( rand > 6 )
        {
            ChangeFoodStage( FoodStageType.ROTTEN );
            SetHealth( "", "", GetMaxHealth()*0.1 );
        }
        else if ( rand > 2 )
        {
            ChangeFoodStage( FoodStageType.DRIED );
            SetHealth( "", "", GetMaxHealth()*0.4 );
        }
    }
References ChangeFoodStage(), GetMaxHealth(), Math::RandomInt(), and SetHealth().
IsMushroom()
override bool MushroomBase::IsMushroom () inline private
Definition at line 13 of file mushroombase.c.
    {
        return true;
    }
SetActions()
override void MushroomBase::SetActions () inline private
Definition at line 23 of file mushroombase.c.
    {
        super.SetActions();
        AddAction(ActionForceFeed);
        AddAction(ActionEat);
    }
References AddAction().