DayzKode: UniversalTemperatureSourceLambdaFireplace Class Reference
UniversalTemperatureSourceLambdaFireplace Class Reference
Private Member Functions
override void Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues)
void SetCurrentTemperature (float temperature)
void SetFuelCount (int value)
void SetNormalFireplaceTemperatureMax (int value)
void SetSmallFireplaceTemperatureMax (int value)
void UniversalTemperatureSourceLambdaFireplace ()
Private Attributes
int m_FuelCount
int m_NormalFireplaceTemperatureMax
int m_SmallFireplaceTemperatureMax
float m_Temperature
Detailed Description
Definition at line 1 of file universaltemperaturesourcelambdafireplace.c.
Constructor & Destructor Documentation
UniversalTemperatureSourceLambdaFireplace()
void UniversalTemperatureSourceLambdaFireplace::UniversalTemperatureSourceLambdaFireplace () inline private
Definition at line 8 of file universaltemperaturesourcelambdafireplace.c.
    {
        m_FuelCount                         = 0;
        m_SmallFireplaceTemperatureMax      = 0;
        m_NormalFireplaceTemperatureMax     = 0;
        m_Temperature                       = 0;
    }
References m_FuelCount, m_NormalFireplaceTemperatureMax, m_SmallFireplaceTemperatureMax, and m_Temperature.
Member Function Documentation
Execute()
override void UniversalTemperatureSourceLambdaFireplace::Execute (UniversalTemperatureSourceSettings pSettings, UniversalTemperatureSourceResult resultValues) inline private
set temperature to the item stat
Definition at line 46 of file universaltemperaturesourcelambdafireplace.c.
    {
        resultValues.m_Temperature = m_Temperature;
        //Debug.Log(string.Format("Execute: temperature: %1", resultValues.m_Temperature), "UTS Fireplace");
        if (pSettings.m_AffectStat)
        {
            pSettings.m_Parent.SetTemperature(m_Temperature);
        }
        DryItemsInVicinity(pSettings);
    }
References UniversalTemperatureSourceLambdaBase::DryItemsInVicinity(), UniversalTemperatureSourceSettings::m_AffectStat, UniversalTemperatureSourceSettings::m_Parent, and m_Temperature.
SetCurrentTemperature()
void UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature (float temperature) inline private
Definition at line 31 of file universaltemperaturesourcelambdafireplace.c.
    {
        //no fuel present, temperature should be low but there can be high temperature from previous fuel burning
        if (m_FuelCount == 0 || temperature <= m_SmallFireplaceTemperatureMax)
        {
            temperature = Math.Clamp(temperature, 0, m_SmallFireplaceTemperatureMax); //small fire
        }
        else
        {
            temperature = Math.Clamp(temperature, 0, m_NormalFireplaceTemperatureMax); //normal fire
        }
        m_Temperature = temperature;
    }
References Math::Clamp(), m_FuelCount, m_NormalFireplaceTemperatureMax, m_SmallFireplaceTemperatureMax, and m_Temperature.
Referenced by AddWetnessToFireplace(), Cooling(), and Heating().
SetFuelCount()
void UniversalTemperatureSourceLambdaFireplace::SetFuelCount (int value) inline private
Definition at line 26 of file universaltemperaturesourcelambdafireplace.c.
    {
        m_FuelCount = value;
    }
References m_FuelCount.
Referenced by AddWetnessToFireplace(), Cooling(), and Heating().
SetNormalFireplaceTemperatureMax()
void UniversalTemperatureSourceLambdaFireplace::SetNormalFireplaceTemperatureMax (int value) inline private
Definition at line 21 of file universaltemperaturesourcelambdafireplace.c.
    {
        m_NormalFireplaceTemperatureMax = value;
    }
References m_NormalFireplaceTemperatureMax.
Referenced by EEInit().
SetSmallFireplaceTemperatureMax()
void UniversalTemperatureSourceLambdaFireplace::SetSmallFireplaceTemperatureMax (int value) inline private
Definition at line 16 of file universaltemperaturesourcelambdafireplace.c.
    {
        m_SmallFireplaceTemperatureMax = value;
    }
References m_SmallFireplaceTemperatureMax.
Referenced by EEInit().
Member Data Documentation
m_FuelCount
int UniversalTemperatureSourceLambdaFireplace::m_FuelCount private
Definition at line 3 of file universaltemperaturesourcelambdafireplace.c.
Referenced by SetCurrentTemperature(), SetFuelCount(), and UniversalTemperatureSourceLambdaFireplace().
m_NormalFireplaceTemperatureMax
int UniversalTemperatureSourceLambdaFireplace::m_NormalFireplaceTemperatureMax private
Definition at line 5 of file universaltemperaturesourcelambdafireplace.c.
Referenced by SetCurrentTemperature(), SetNormalFireplaceTemperatureMax(), and UniversalTemperatureSourceLambdaFireplace().
m_SmallFireplaceTemperatureMax
int UniversalTemperatureSourceLambdaFireplace::m_SmallFireplaceTemperatureMax private
Definition at line 4 of file universaltemperaturesourcelambdafireplace.c.
Referenced by SetCurrentTemperature(), SetSmallFireplaceTemperatureMax(), and UniversalTemperatureSourceLambdaFireplace().
m_Temperature
float UniversalTemperatureSourceLambdaFireplace::m_Temperature private
Definition at line 6 of file universaltemperaturesourcelambdafireplace.c.
Referenced by Execute(), SetCurrentTemperature(), and UniversalTemperatureSourceLambdaFireplace().