DayzKode: PlayerStatBase Class Reference
PlayerStatBase Class Reference
Private Member Functions
void Add (T value, string system="")
void CreateRecord (float value, string system)
float Get ()
override float Get ()
string GetLabel ()
override string GetLabel ()
PlayerStats GetManager ()
float GetMax ()
override float GetMax ()
float GetMin ()
override float GetMin ()
float GetNormalized ()
override float GetNormalized ()
array< PlayerStatRecord > GetRecords ()
override array< PlayerStatRecord > GetRecords ()
int GetType ()
void Init (int id)
override void Init (int id)
bool IsSynced ()
void OnRPC (ParamsReadContext ctx)
bool OnStoreLoad (ParamsReadContext ctx)
override bool OnStoreLoad (ParamsReadContext ctx)
void OnStoreSave (ParamsWriteContext ctx)
override void OnStoreSave (ParamsWriteContext ctx)
void PlayerStat (T min, T max, T init, string label, int flags)
void SerializeValue (array< ref StatDebugObject > objects, int flags)
override void SerializeValue (array< ref StatDebugObject > objects, int flags)
void Set (T value, string system="")
void SetByFloat (float value)
void SetByFloat (float value, string system="")
void SetByFloatEx (float value, string system="")
override void SetByFloatEx (float value, string system="")
Private Attributes
protected int m_Flags
PlayerStats m_Manager
protected T m_MaxValue
protected T m_MinValue
ref array< PlayerStatRecord > m_Records
int m_Type
protected T m_Value
protected string m_ValueLabel
Detailed Description
Definition at line 1 of file playerstatbase.c.
Member Function Documentation
Add()
void PlayerStatBase::Add (T value, string system = "") inline private
Definition at line 106 of file playerstatbase.c.
    {
        Set(m_Value+value, system);
    }
References m_Value, and Set().
CreateRecord()
void PlayerStatBase::CreateRecord (float value, string system) inline private
Definition at line 141 of file playerstatbase.c.
    {
        m_Records.Insert( new PlayerStatRecord(value, GetGame().GetTime(), system ) );
    }
References GetGame(), and GetTime().
Get() [1/2]
float PlayerStatBase::Get () private
Referenced by GetNormalized(), and SerializeValue().
Get() [2/2]
override float PlayerStatBase::Get () inline private
Definition at line 111 of file playerstatbase.c.
    {
        return m_Value;
    }
References m_Value.
GetLabel() [1/2]
string PlayerStatBase::GetLabel () private
Referenced by SerializeValue().
GetLabel() [2/2]
override string PlayerStatBase::GetLabel () inline private
Definition at line 116 of file playerstatbase.c.
    {
        return m_ValueLabel;
    }
References m_ValueLabel.
GetManager()
PlayerStats PlayerStatBase::GetManager () inline private
Definition at line 58 of file playerstatbase.c.
    {
        return m_Manager;
    }
References m_Manager.
GetMax() [1/2]
float PlayerStatBase::GetMax () private
Referenced by GetNormalized().
GetMax() [2/2]
override float PlayerStatBase::GetMax () inline private
Definition at line 121 of file playerstatbase.c.
    {
        return m_MaxValue;
    }
References m_MaxValue.
GetMin() [1/2]
float PlayerStatBase::GetMin () private
Referenced by GetNormalized().
GetMin() [2/2]
override float PlayerStatBase::GetMin () inline private
Definition at line 126 of file playerstatbase.c.
    {
        return m_MinValue;
    }
References m_MinValue.
GetNormalized() [1/2]
float PlayerStatBase::GetNormalized () private
GetNormalized() [2/2]
override float PlayerStatBase::GetNormalized () inline private
Definition at line 131 of file playerstatbase.c.
    {
        return Math.InverseLerp(GetMin(), GetMax(), Get());
    }
References Get(), GetMax(), GetMin(), and Math::InverseLerp().
GetRecords() [1/2]
array< PlayerStatRecord > PlayerStatBase::GetRecords () private
GetRecords() [2/2]
override array< PlayerStatRecord > PlayerStatBase::GetRecords () inline private
Definition at line 136 of file playerstatbase.c.
    {
        return m_Records;
    }
References m_Records.
GetType()
int PlayerStatBase::GetType () inline private
Definition at line 18 of file playerstatbase.c.
    {
        return m_Type;
    }
References m_Type.
Init() [1/2]
void PlayerStatBase::Init (int id) private
Referenced by RegisterStat().
Init() [2/2]
override void PlayerStatBase::Init (int id) inline private
Definition at line 47 of file playerstatbase.c.
    {
        m_Type = id;
        //m_Manager = manager;
    }
References m_Type.
IsSynced()
bool PlayerStatBase::IsSynced () private
OnRPC()
void PlayerStatBase::OnRPC (ParamsReadContext ctx) private
OnStoreLoad() [1/2]
bool PlayerStatBase::OnStoreLoad (ParamsReadContext ctx) private
OnStoreLoad() [2/2]
override bool PlayerStatBase::OnStoreLoad (ParamsReadContext ctx) inline private
Definition at line 153 of file playerstatbase.c.
    {
        //string name;
        //ctx.Read(name);
        T value;
        if(ctx.Read(value))
        {
            m_Value = value;
        }
        else
        {
            return false;
        }
        //PrintString("loading " + GetLabel()+" value:" +m_Value);
        return true;
    }
References m_Value, and Serializer::Read().
OnStoreSave() [1/2]
void PlayerStatBase::OnStoreSave (ParamsWriteContext ctx) private
OnStoreSave() [2/2]
override void PlayerStatBase::OnStoreSave (ParamsWriteContext ctx) inline private
Definition at line 146 of file playerstatbase.c.
    {
        //ctx.Write(m_ValueLabel);
        //PrintString("saving " + GetLabel()+" value:" +m_Value);
        ctx.Write(m_Value);
    }
References m_Value, and Serializer::Write().
PlayerStat()
void PlayerStatBase::PlayerStat (T min, T max, T init, string label, int flags) inline private
Definition at line 36 of file playerstatbase.c.
    {
        m_MinValue      = min;
        m_MaxValue      = max;
        m_Value         = init;
        m_ValueLabel    = label;
        m_Flags         = flags;
        m_Records = new array<PlayerStatRecord>;
    }
References init, m_MaxValue, m_MinValue, and m_Value.
SerializeValue() [1/2]
void PlayerStatBase::SerializeValue (array< ref StatDebugObject > objects, int flags) private
SerializeValue() [2/2]
override void PlayerStatBase::SerializeValue (array< ref StatDebugObject > objects, int flags) inline private
Definition at line 53 of file playerstatbase.c.
    {
        objects.Insert( new StatDebugObject(GetLabel(), Get(), eRemoteStatType.PLAYER_STATS) );
    }
References Get(), and GetLabel().
Set()
void PlayerStatBase::Set (T value, string system = "") inline private
Definition at line 63 of file playerstatbase.c.
    {
        /*
        Print("setting stat: " + this.GetLabel() + "| value:" +value.ToString());
        if( this.GetLabel() == "Toxicity" )
        {
            DebugPrint.LogAndTrace("stack");
        }
        */
        if ( value > m_MaxValue )
        {
            m_Value = m_MaxValue;
        }
        else if (value < m_MinValue)
        {
            m_Value = m_MinValue;
        }
        else
        {
            m_Value = value;
        }
        //if( GetManager().GetAllowLogs() ) CreateRecord(value, system);
    }
References m_MaxValue, m_MaxValue, m_MinValue, m_MinValue, and m_Value.
Referenced by Add(), and SetByFloat().
SetByFloat() [1/2]
void PlayerStatBase::SetByFloat (float value) private
Referenced by SetByFloatEx().
SetByFloat() [2/2]
void PlayerStatBase::SetByFloat (float value, string system = "") inline private
Definition at line 88 of file playerstatbase.c.
    {
        T f = value;
        Set(f,system);
    }
References Set().
SetByFloatEx() [1/2]
void PlayerStatBase::SetByFloatEx (float value, string system = "") private
SetByFloatEx() [2/2]
override void PlayerStatBase::SetByFloatEx (float value, string system = "") inline private
Definition at line 94 of file playerstatbase.c.
    {
        SetByFloat(value, system);
    }
References SetByFloat().
Member Data Documentation
m_Flags
protected int PlayerStatBase::m_Flags private
Definition at line 30 of file playerstatbase.c.
m_Manager
PlayerStats PlayerStatBase::m_Manager private
Definition at line 33 of file playerstatbase.c.
Referenced by GetManager().
m_MaxValue
protected T PlayerStatBase::m_MaxValue private
Definition at line 27 of file playerstatbase.c.
Referenced by GetMax(), and Set().
m_MinValue
protected T PlayerStatBase::m_MinValue private
Definition at line 26 of file playerstatbase.c.
Referenced by GetMin(), and Set().
m_Records
ref array<PlayerStatRecord> PlayerStatBase::m_Records private
Definition at line 32 of file playerstatbase.c.
Referenced by GetRecords().
m_Type
int PlayerStatBase::m_Type private
Definition at line 3 of file playerstatbase.c.
Referenced by GetType().
m_Value
protected T PlayerStatBase::m_Value private
Definition at line 28 of file playerstatbase.c.
Referenced by Get().
m_ValueLabel
protected string PlayerStatBase::m_ValueLabel private
Definition at line 29 of file playerstatbase.c.
Referenced by GetLabel().