DayzKode: P:/scripts/4_world/DayZ/entities/itembase/clockbase.c File Reference
clockbase.c File Reference
Enumerations
enum EAlarmClockState { UNSET , SET , RINGING , COUNT }
Functions
protected void ActivateParent ()
protected void Arm ()
void ClockBase ()
static int ConvertAlarmHand01ToMins (float time01, int mins_max)
static int ConvertAlarmHand01ToMins12h (float time01)
static float ConvertMins12hToAlarmHand01 (int mins)
static int ConvertTimeToMins12h (int hour, int minute)
protected void Disarm ()
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override void EEKilled (Object killer)
protected int GetAlarmInMin ()
string GetDestroyedSound ()
string GetHitSound ()
float GetRingingDurationMax ()
string GetRingingSound ()
static int GetTimeDiffInMins12h (int from_mins, int to_mins)
string GetToggleSound ()
string GetWorkingSound ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
bool IsAlarmOn ()
bool IsRinging ()
protected void MakeRingingStart ()
protected void MakeRingingStop ()
override void OnDamageDestroyed (int oldLevel)
protected void OnRingingStartClient ()
protected void OnRingingStartServer ()
protected void OnRingingStopClient ()
protected void OnRingingStopServer ()
override void OnVariablesSynchronized ()
override void SetActions ()
void SetAlarmInXMins (int in_mins)
void SetAlarmTimeServer (float time01)
protected void SetState (EAlarmClockState state)
protected void SetupTimerServer ()
void TurnOff ()
void TurnOffClient ()
void TurnOn ()
void TurnOnClient ()
void ~ClockBase ()
Variables
enum EAlarmClockState m_AlarmTime01
EffectSound m_DestoryedSound
EffectSound m_HitSound
float m_RingingDuration
EffectSound m_RingingSoundLoop
int m_State = EAlarmClockState.UNSET
int m_StatePrev = -1
ref Timer m_TimerUpdate
EffectSound m_TurnOnSound
EffectSound m_WorkingSound
const float RINGING_DURATION_MAX = 60
static const float UPDATE_TICK_RATE = 1
Enumeration Type Documentation
EAlarmClockState
enum EAlarmClockState
Enumerator
UNSET
SET
RINGING
COUNT
Definition at line 1 of file clockbase.c.
{
    UNSET,
    SET,
    RINGING,
    //-----------
    COUNT
}
Function Documentation
ActivateParent()
protected void ActivateParent ()
Definition at line 210 of file clockbase.c.
    {
        if (GetHierarchyParent())
        {
            ItemBase parent = ItemBase.Cast(GetHierarchyParent());
            if (parent)
            {
                parent.OnActivatedByItem(this);
            }
        }
    }
Referenced by OnRingingStartServer().
Arm()
protected void Arm ()
Definition at line 203 of file clockbase.c.
    {
        SetupTimerServer();
        SetState(EAlarmClockState.SET);
        m_RingingDuration = 0;
    }
References m_RingingDuration, Inventory_Base::SetState(), and SetupTimerServer().
ClockBase()
void ClockBase ()
Definition at line 27 of file clockbase.c.
    {
        Init();
    }
References Init().
Referenced by ActionCondition(), Plastic_Explosive::CanReceiveAttachment(), ImprovisedExplosive::OnActivatedByItem(), ImprovisedExplosive::OnDisarmed(), OnExecuteServer(), and ImprovisedExplosive::OnTriggerAttached().
ConvertAlarmHand01ToMins()
static int ConvertAlarmHand01ToMins (float time01, int mins_max) static
Definition at line 70 of file clockbase.c.
    {
        return Math.Lerp(0,mins_max,time01);
    }
References Math::Lerp().
ConvertAlarmHand01ToMins12h()
static int ConvertAlarmHand01ToMins12h (float time01) static
Definition at line 65 of file clockbase.c.
    {
        return Math.Lerp(0,12*60,time01);
    }
References Math::Lerp().
Referenced by GetAlarmInMin(), and AlarmClock_ColorBase::OnUpdate().
ConvertMins12hToAlarmHand01()
static float ConvertMins12hToAlarmHand01 (int mins) static
Definition at line 75 of file clockbase.c.
    {
        return Math.InverseLerp(0,12*60,mins);
    }
References Math::InverseLerp().
Referenced by SetAlarmInXMins().
ConvertTimeToMins12h()
static int ConvertTimeToMins12h (int hour, int minute) static
Definition at line 81 of file clockbase.c.
    {
        if (hour >= 12)
            hour -= 12;
        return hour * 60 + minute;
    }
Referenced by GetAlarmInMin(), AlarmClock_ColorBase::OnUpdate(), and SetAlarmInXMins().
Disarm()
protected void Disarm ()
Definition at line 198 of file clockbase.c.
    {
        SetState(EAlarmClockState.UNSET);
    }
References Inventory_Base::SetState().
Referenced by TurnOff().
EEHitByRemote()
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
Definition at line 128 of file clockbase.c.
    {
        super.EEHitByRemote(damageType, source, component, dmgZone, ammo, modelPos);
        PlaySoundSet( m_HitSound, GetHitSound(), 0, 0 );
    }
References component, GetHitSound(), m_HitSound, and PlaySoundSet().
EEKilled()
override void EEKilled (Object killer)
Definition at line 122 of file clockbase.c.
    {
        super.EEKilled(killer);
        TurnOff();
    }
References TurnOff().
GetAlarmInMin()
protected int GetAlarmInMin ()
Definition at line 53 of file clockbase.c.
    {
        int alarm_hand_in_mins = ConvertAlarmHand01ToMins12h(m_AlarmTime01);
        int pass, hour, minute;
        GetGame().GetWorld().GetDate(pass, pass, pass, hour, minute);
        int curr_time_in_minutes = ConvertTimeToMins12h(hour, minute);
        int ring_in_mins = GetTimeDiffInMins12h(curr_time_in_minutes, alarm_hand_in_mins);
        return ring_in_mins;
    }
References ConvertAlarmHand01ToMins12h(), ConvertTimeToMins12h(), World::GetDate(), GetGame(), GetTimeDiffInMins12h(), CGame::GetWorld(), and m_AlarmTime01.
Referenced by AlarmClock_ColorBase::GetDebugText().
GetDestroyedSound()
string GetDestroyedSound ()
Definition at line 113 of file clockbase.c.
    {
        return "";
    }
Referenced by OnDamageDestroyed().
GetHitSound()
string GetHitSound ()
Definition at line 109 of file clockbase.c.
    {
        return "";
    }
Referenced by EEHitByRemote().
GetRingingDurationMax()
float GetRingingDurationMax ()
Definition at line 180 of file clockbase.c.
    {
        return RINGING_DURATION_MAX;
    }
References RINGING_DURATION_MAX.
Referenced by AlarmClock_ColorBase::GetDebugText(), and AlarmClock_ColorBase::OnUpdate().
GetRingingSound()
string GetRingingSound ()
Definition at line 105 of file clockbase.c.
    {
        return "";
    }
Referenced by OnRingingStartClient().
GetTimeDiffInMins12h()
static int GetTimeDiffInMins12h (int from_mins, int to_mins) static
Definition at line 88 of file clockbase.c.
    {
        if (to_mins > from_mins)
        {
            return to_mins - from_mins;
        }
        else if (to_mins < from_mins)
        {
            return ((12 * 60) - from_mins) + to_mins;
        }
        else return 0;
    }
Referenced by GetAlarmInMin().
GetToggleSound()
string GetToggleSound ()
Definition at line 101 of file clockbase.c.
    {
        return "";
    }
Referenced by OnVariablesSynchronized().
GetWorkingSound()
string GetWorkingSound ()
Definition at line 117 of file clockbase.c.
    {
        return "";
    }
Referenced by OnVariablesSynchronized().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 41 of file clockbase.c.
    {
        RegisterNetSyncVariableInt("m_State",0, EAlarmClockState.COUNT - 1);
    }
IsAlarmOn()
bool IsAlarmOn ()
Definition at line 295 of file clockbase.c.
    {
        return (m_State == EAlarmClockState.SET);
    }
References m_State.
Referenced by AlarmClock_ColorBase::OnUpdate().
IsRinging()
bool IsRinging ()
Definition at line 290 of file clockbase.c.
    {
        return (m_State == EAlarmClockState.RINGING);
    }
References m_State.
Referenced by AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), and TurnOff().
MakeRingingStart()
protected void MakeRingingStart ()
Definition at line 222 of file clockbase.c.
    {
        if (!m_TimerUpdate)
            SetupTimerServer();
        SetState(EAlarmClockState.RINGING);
        OnRingingStartServer();
    }
References m_TimerUpdate, OnRingingStartServer(), Inventory_Base::SetState(), and SetupTimerServer().
Referenced by AlarmClock_ColorBase::OnDebugSpawn(), AlarmClock_ColorBase::OnStoreLoad(), KitchenTimer::OnStoreLoad(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().
MakeRingingStop()
protected void MakeRingingStop ()
Definition at line 231 of file clockbase.c.
    {
        SetState(EAlarmClockState.UNSET);
        OnRingingStopServer();
    }
References OnRingingStopServer(), and Inventory_Base::SetState().
Referenced by KitchenTimer::OnUpdate(), and TurnOff().
OnDamageDestroyed()
override void OnDamageDestroyed (int oldLevel)
Definition at line 134 of file clockbase.c.
    {
        super.OnDamageDestroyed(oldLevel);
        if (GetGame().IsClient())
        {
            OnRingingStopClient();
            if (oldLevel != -1)
            {
                PlaySoundSet(m_DestoryedSound, GetDestroyedSound(), 0, 0);
            }
        }
    }
References GetDestroyedSound(), GetGame(), m_DestoryedSound, OnRingingStopClient(), and PlaySoundSet().
OnRingingStartClient()
protected void OnRingingStartClient ()
Definition at line 154 of file clockbase.c.
    {
        PlaySoundSetLoop( m_RingingSoundLoop, GetRingingSound(), 0, 0 );
        if (m_WorkingSound)
        {
            SEffectManager.DestroyEffect(m_WorkingSound);
        }
    }
References SEffectManager::DestroyEffect(), GetRingingSound(), m_RingingSoundLoop, m_WorkingSound, and PlaySoundSetLoop().
Referenced by OnVariablesSynchronized().
OnRingingStartServer()
protected void OnRingingStartServer ()
Definition at line 149 of file clockbase.c.
    {
        ActivateParent();
    }
References ActivateParent().
Referenced by MakeRingingStart().
OnRingingStopClient()
protected void OnRingingStopClient ()
Definition at line 165 of file clockbase.c.
    {
        SEffectManager.DestroyEffect(m_RingingSoundLoop);
    }
References SEffectManager::DestroyEffect(), and m_RingingSoundLoop.
Referenced by OnDamageDestroyed(), OnVariablesSynchronized(), and AlarmClock_ColorBase::~AlarmClock_ColorBase().
OnRingingStopServer()
protected void OnRingingStopServer ()
Referenced by MakeRingingStop().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 242 of file clockbase.c.
    {
        super.OnVariablesSynchronized();
        if (m_State != m_StatePrev)//state changed
        {
            if (m_StatePrev == EAlarmClockState.RINGING)
            {
                OnRingingStopClient();
            }
            else if (m_State == EAlarmClockState.RINGING)
            {
                OnRingingStartClient();
            }
            if (m_State == EAlarmClockState.SET)
            {
                if (m_StatePrev != -1 || IsInitialized())
                {
                    PlaySoundSet( m_TurnOnSound, GetToggleSound(), 0, 0 );
                }
                if (GetWorkingSound())
                {
                    PlaySoundSet( m_WorkingSound, GetWorkingSound(), 0, 0, true );
                }
            }
            else if (m_State == EAlarmClockState.UNSET)
            {
                if (m_StatePrev == EAlarmClockState.SET)
                {
                    if (m_WorkingSound)
                    {
                        SEffectManager.DestroyEffect(m_WorkingSound);
                    }
                    if (m_StatePrev != -1 || IsInitialized())
                    {
                        PlaySoundSet( m_TurnOnSound, GetToggleSound(), 0, 0 );
                    }
                }
            }
            m_StatePrev = m_State;
        }
    }
References SEffectManager::DestroyEffect(), GetToggleSound(), GetWorkingSound(), IsInitialized(), m_State, Inventory_Base::m_State, m_StatePrev, m_TurnOnSound, m_WorkingSound, OnRingingStartClient(), OnRingingStopClient(), and PlaySoundSet().
SetActions()
override void SetActions ()
Definition at line 46 of file clockbase.c.
    {
        super.SetActions();
        AddAction(ActionAttachExplosivesTrigger);
    }
References ActionAttachExplosivesTrigger(), and AddAction().
SetAlarmInXMins()
void SetAlarmInXMins (int in_mins)
Definition at line 170 of file clockbase.c.
    {
        int pass, hour, minute;
        GetGame().GetWorld().GetDate(pass, pass, pass, hour, minute);
        int mins12h = ConvertTimeToMins12h(hour, minute) + in_mins;
        float time01 = ConvertMins12hToAlarmHand01(mins12h);
        SetAlarmTimeServer(time01);
        Arm();
    }
References Arm(), ConvertMins12hToAlarmHand01(), ConvertTimeToMins12h(), World::GetDate(), GetGame(), CGame::GetWorld(), and SetAlarmTimeServer().
Referenced by AlarmClock_ColorBase::OnDebugButtonPressServer().
SetAlarmTimeServer()
void SetAlarmTimeServer (float time01)
Definition at line 319 of file clockbase.c.
    {
        SetAnimationPhaseNow("ClockAlarm", time01);
        m_AlarmTime01 = time01;
    }
References m_AlarmTime01.
Referenced by AlarmClock_ColorBase::OnStoreLoad(), and SetAlarmInXMins().
SetState()
protected void SetState (EAlarmClockState state)
Definition at line 192 of file clockbase.c.
    {
        m_State = state;
        SetSynchDirty();
    }
References m_State.
SetupTimerServer()
protected void SetupTimerServer ()
Definition at line 186 of file clockbase.c.
    {
        m_TimerUpdate = new Timer;
        m_TimerUpdate.Run(UPDATE_TICK_RATE , this, "OnUpdate", null, true);
    }
References m_TimerUpdate, and UPDATE_TICK_RATE.
Referenced by Arm(), and MakeRingingStart().
TurnOff()
void TurnOff ()
Definition at line 305 of file clockbase.c.
    {
        if ( IsRinging() )
        {
            MakeRingingStop();
        }
        else
        {
            Disarm();
        }
        m_TimerUpdate = null;
    }
References Disarm(), IsRinging(), m_TimerUpdate, and MakeRingingStop().
Referenced by EEKilled(), and AlarmClock_ColorBase::OnUpdate().
TurnOffClient()
void TurnOffClient ()
TurnOn()
void TurnOn ()
Definition at line 300 of file clockbase.c.
    {
        Arm();
    }
References Arm().
Referenced by AlarmClock_ColorBase::OnDebugSpawn(), AlarmClock_ColorBase::OnStoreLoad(), and KitchenTimer::SetAlarmTimeServer().
TurnOnClient()
void TurnOnClient ()
~ClockBase()
void ~ClockBase ()
Definition at line 32 of file clockbase.c.
    {
        SEffectManager.DestroyEffect(m_WorkingSound);
        SEffectManager.DestroyEffect(m_HitSound);
        SEffectManager.DestroyEffect(m_DestoryedSound);
        SEffectManager.DestroyEffect(m_TurnOnSound);
        SEffectManager.DestroyEffect(m_RingingSoundLoop);
    }
References SEffectManager::DestroyEffect(), m_DestoryedSound, m_HitSound, m_RingingSoundLoop, m_TurnOnSound, and m_WorkingSound.
Variable Documentation
m_AlarmTime01
enum EAlarmClockState m_AlarmTime01
Referenced by GetAlarmInMin(), AlarmClock_ColorBase::OnStoreSave(), AlarmClock_ColorBase::OnUpdate(), and SetAlarmTimeServer().
m_DestoryedSound
EffectSound m_DestoryedSound
Definition at line 21 of file clockbase.c.
Referenced by OnDamageDestroyed(), and ~ClockBase().
m_HitSound
EffectSound m_HitSound
Definition at line 22 of file clockbase.c.
Referenced by EEHitByRemote(), and ~ClockBase().
m_RingingDuration
float m_RingingDuration
Definition at line 16 of file clockbase.c.
Referenced by Arm(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), AlarmClock_ColorBase::OnUpdate(), and KitchenTimer::OnUpdate().
m_RingingSoundLoop
EffectSound m_RingingSoundLoop
Definition at line 19 of file clockbase.c.
Referenced by OnRingingStartClient(), OnRingingStopClient(), KitchenTimer::OnRingingStopClient(), and ~ClockBase().
m_State
int m_State = EAlarmClockState.UNSET
Definition at line 13 of file clockbase.c.
m_StatePrev
int m_StatePrev = -1
Definition at line 17 of file clockbase.c.
Referenced by OnVariablesSynchronized(), and SetState().
m_TimerUpdate
ref Timer m_TimerUpdate
Definition at line 15 of file clockbase.c.
Referenced by Init(), MakeRingingStart(), SetupTimerServer(), TurnOff(), and ~HudDebug().
m_TurnOnSound
EffectSound m_TurnOnSound
Definition at line 20 of file clockbase.c.
Referenced by OnVariablesSynchronized(), and ~ClockBase().
m_WorkingSound
EffectSound m_WorkingSound
Definition at line 23 of file clockbase.c.
Referenced by OnRingingStartClient(), OnVariablesSynchronized(), KitchenTimer::TurnOff(), and ~ClockBase().
RINGING_DURATION_MAX
const float RINGING_DURATION_MAX = 60
Definition at line 25 of file clockbase.c.
Referenced by GetRingingDurationMax().
UPDATE_TICK_RATE
const float UPDATE_TICK_RATE = 1 static
Definition at line 14 of file clockbase.c.
Referenced by AlarmClock_ColorBase::OnUpdate(), KitchenTimer::OnUpdate(), and SetupTimerServer().