DayzKode: P:/scripts/4_world/DayZ/entities/itembase/combinationlock.c File Reference
combinationlock.c File Reference
Enumerations
enum LockAction {
NONE , DIAL_NUMBER_CHANED , DIAL_INDEX_CHANGED , LOCKED ,
UNLOCKED , COUNT
}
Functions
override void AfterStoreLoad ()
void CheckLockedStateServer ()
void CombinationLock ()
void DestroyLock ()
void DialNextNumber ()
override void EEInit ()
int GetCombination ()
int GetDialIndex ()
int GetLockDigits ()
protected void HideAttached ()
protected void HideItem ()
override bool IsInitialized ()
bool IsLockAttached ()
bool IsLocked ()
bool IsLockedOnGate ()
void LockServer (EntityAI parent, bool ignore_combination=false)
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
void ResetActionVar ()
override void SetActions ()
protected void SetBaseLockValues ()
void SetCombination (int combination)
void SetCombinationLocked (int combination)
void SetInitialized ()
void SetNextDial ()
protected void ShowAttached ()
protected void ShowItem ()
void ShuffleLock ()
void SoundLockChangeDial ()
void SoundLockChangeNumber ()
protected void SoundLockClose ()
protected void SoundLockOpen ()
void Synchronize ()
void UnlockServer (EntityAI player, EntityAI parent)
void UpdateSound ()
void UpdateVisuals ()
Variables
int m_Combination
int m_CombinationLocked
int m_DialIndex
protected bool m_IsInitialized
protected bool m_IsLocked
protected LockAction m_LockActionPerformed = LockAction.NONE
enum LockAction m_LockDigits
protected EffectSound m_Sound
const string SOUND_LOCK_CHANGE_DIAL = "combinationlock_changedial_SoundSet"
const string SOUND_LOCK_CHANGE_NUMBER = "combinationlock_changenumber_SoundSet"
const string SOUND_LOCK_CLOSE = "combinationlock_close_SoundSet"
const string SOUND_LOCK_OPEN = "combinationlock_open_SoundSet"
Enumeration Type Documentation
LockAction
enum LockAction
Enumerator
NONE
DIAL_NUMBER_CHANED
DIAL_INDEX_CHANGED
LOCKED
UNLOCKED
COUNT
Definition at line 1 of file combinationlock.c.
{
    NONE,
    DIAL_NUMBER_CHANED,
    DIAL_INDEX_CHANGED,
    LOCKED,
    UNLOCKED,
    COUNT
}
Function Documentation
AfterStoreLoad()
override void AfterStoreLoad ()
Definition at line 132 of file combinationlock.c.
    {
        super.AfterStoreLoad();
        //Check combination lock
        if ( GetGame().IsServer() )
        {
            EntityAI parent = GetHierarchyParent();
            if ( parent && parent.IsInherited( BaseBuildingBase ) )
            {
                LockServer( parent, true );
            }
        }
        //synchronize
        Synchronize();
    }
References GetGame(), LockServer(), and Synchronize().
CheckLockedStateServer()
void CheckLockedStateServer ()
Definition at line 359 of file combinationlock.c.
    {
        m_IsLocked = m_Combination != m_CombinationLocked;
    }
References m_Combination, m_CombinationLocked, and m_IsLocked.
Referenced by DialNextNumber(), LockServer(), and UnlockServer().
CombinationLock()
void CombinationLock ()
Definition at line 33 of file combinationlock.c.
    {
        SetBaseLockValues();
        //synchronized variables
        int combination_length = Math.Pow( 10, m_LockDigits );
        RegisterNetSyncVariableBool( "m_IsLocked" );
        RegisterNetSyncVariableInt( "m_Combination", 0, combination_length - 1 );
        RegisterNetSyncVariableInt( "m_DialIndex", 0, m_LockDigits - 1 );
        RegisterNetSyncVariableInt( "m_LockActionPerformed", 0, LockAction.COUNT );
    }
References m_LockDigits, Math::Pow(), and CombinationLock::SetBaseLockValues().
DestroyLock()
void DestroyLock ()
Definition at line 390 of file combinationlock.c.
    {
        GetGame().ObjectDelete( this );
    }
References GetGame(), and CGame::ObjectDelete().
DialNextNumber()
void DialNextNumber ()
Definition at line 202 of file combinationlock.c.
    {
        string combination_text = m_Combination.ToString();
        string dialed_text;
        //insert zeros to dials with 0 value
        int length_diff = m_LockDigits - combination_text.Length();
        for ( int i = 0; i < length_diff; ++i )
        {
            combination_text = "0" + combination_text;
        }
        //assemble the whole combination with increased part
        for ( int j = 0; j < combination_text.Length(); ++j )
        {
            if ( j == m_DialIndex )
            {
                int next_dialed_number = combination_text.Get( j ).ToInt() + 1;
                if ( next_dialed_number > 9 )
                {
                    next_dialed_number = 0;
                }
                dialed_text += next_dialed_number.ToString();
            }
            else
            {
                dialed_text += combination_text.Get( j );
            }
        }
        //set new number
        SetCombination( dialed_text.ToInt() );
        m_LockActionPerformed = LockAction.DIAL_INDEX_CHANGED;
        CheckLockedStateServer();
        //synchronize
        Synchronize();
    }
References CheckLockedStateServer(), string::Get(), string::Length(), m_Combination, m_DialIndex, m_LockActionPerformed, m_LockDigits, SetCombination(), Synchronize(), string::ToInt(), and string::ToString().
EEInit()
override void EEInit ()
Definition at line 54 of file combinationlock.c.
    {
        super.EEInit();
        GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( SetInitialized, 1000, false );
        //SetInitialized();
        //set visual on init
        UpdateVisuals();
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), SetInitialized(), and UpdateVisuals().
GetCombination()
int GetCombination ()
Definition at line 191 of file combinationlock.c.
    {
        return m_Combination;
    }
References m_Combination.
GetDialIndex()
int GetDialIndex ()
Definition at line 242 of file combinationlock.c.
    {
        return m_DialIndex;
    }
References m_DialIndex.
GetLockDigits()
int GetLockDigits ()
Definition at line 196 of file combinationlock.c.
    {
        return m_LockDigits;
    }
References m_LockDigits.
HideAttached()
protected void HideAttached ()
Definition at line 460 of file combinationlock.c.
    {
        SetAnimationPhase( "Combination_Lock_Attached", 1 );
        SetAnimationPhase( "Lock_Attached_1",           1 );
        SetAnimationPhase( "Lock_Attached_2",           1 );
    }
Referenced by UpdateVisuals().
HideItem()
protected void HideItem ()
Definition at line 446 of file combinationlock.c.
    {
        SetAnimationPhase( "Combination_Lock_Item", 1 );
        SetAnimationPhase( "Lock_Item_1",           1 );
        SetAnimationPhase( "Lock_Item_2",           1 );
    }
Referenced by UpdateVisuals().
IsInitialized()
override bool IsInitialized ()
Definition at line 70 of file combinationlock.c.
    {
        return m_IsInitialized;
    }
References m_IsInitialized.
Referenced by ItemBase::EEItemAttached(), OnItemLocationChanged(), OnVariablesSynchronized(), and ItemBase::OnWorkStart().
IsLockAttached()
bool IsLockAttached ()
Definition at line 378 of file combinationlock.c.
    {
        Fence fence = Fence.Cast( GetHierarchyParent() );
        if ( fence )
        {
            return true;
        }
        return false;
    }
Referenced by LockServer(), and UnlockServer().
IsLocked()
bool IsLocked ()
Definition at line 354 of file combinationlock.c.
    {
        return m_IsLocked;
    }
References m_IsLocked.
IsLockedOnGate()
bool IsLockedOnGate ()
Definition at line 364 of file combinationlock.c.
    {
        Fence fence = Fence.Cast( GetHierarchyParent() );
        if ( fence )
        {
            if ( IsLocked() )
            {
                return true;
            }
        }
        return false;
    }
References IsLocked().
Referenced by UpdateVisuals().
LockServer()
void LockServer (EntityAI parent, bool ignore_combination = false)
Definition at line 272 of file combinationlock.c.
    {
        bsbDebugPrint("[bsb] CombinationLock.LockServer " + " m_Combination=" + m_Combination + " m_CombinationLocked=" + m_CombinationLocked);
        if ( IsLockAttached() )
        {
            if ( !ignore_combination )
            {
                SetCombinationLocked( m_Combination );
                //set slot lock
                InventoryLocation inventory_location = new InventoryLocation;
                GetInventory().GetCurrentInventoryLocation( inventory_location );
                parent.GetInventory().SetSlotLock( inventory_location.GetSlot(), true );
                m_LockActionPerformed = LockAction.LOCKED;
            }
            ShuffleLock();
            SetTakeable(false);
            CheckLockedStateServer();
            //synchronize
            Synchronize();
        }
        //reset performed action
        //m_LockActionPerformed = LockAction.NONE;
    }
References bsbDebugPrint(), CheckLockedStateServer(), InventoryLocation::GetSlot(), IsLockAttached(), m_Combination, m_CombinationLocked, m_LockActionPerformed, SetCombinationLocked(), SetTakeable(), ShuffleLock(), and Synchronize().
Referenced by AfterStoreLoad(), and OnItemLocationChanged().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 75 of file combinationlock.c.
    {
        super.OnItemLocationChanged( old_owner, new_owner );
        //Check combination lock
        if ( GetGame().IsServer() )
        {
            if ( IsInitialized() && new_owner && new_owner.IsInherited( BaseBuildingBase ) )
            {
                LockServer( new_owner );
            }
        }
    }
References GetGame(), IsInitialized(), and LockServer().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 99 of file combinationlock.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        //--- Combination Lock data ---
        //combination
        if ( !ctx.Read( m_Combination ) )
        {
            m_Combination = 0;
            return false;
        }
        //combination locked
        if ( !ctx.Read( m_CombinationLocked ) )
        {
            m_CombinationLocked = 0;
            return false;
        }
        //is lock attached
        if ( version < 105 )                    //removed in 105
        {
            bool is_lock_attached;
            if ( !ctx.Read( is_lock_attached ) )
            {
                return false;
            }
        }
        return true;
    }
References m_Combination, m_CombinationLocked, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 90 of file combinationlock.c.
    {
        super.OnStoreSave( ctx );
        //write data
        ctx.Write( m_Combination );
        ctx.Write( m_CombinationLocked );
    }
References m_Combination, m_CombinationLocked, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 168 of file combinationlock.c.
    {
        super.OnVariablesSynchronized();
        //update visuals (client)
        UpdateVisuals();
        //update sound (client)
        if(m_LockActionPerformed)
            UpdateSound();
        bsbDebugPrint("[bsb] CombinationLock.OnVariablesSynchronized " + " m_Combination=" + m_Combination + " m_CombinationLocked=" + m_CombinationLocked);
    }
References bsbDebugPrint(), m_Combination, m_CombinationLocked, m_LockActionPerformed, UpdateSound(), and UpdateVisuals().
ResetActionVar()
void ResetActionVar ()
Definition at line 163 of file combinationlock.c.
    {
        m_LockActionPerformed = LockAction.NONE;
    }
References m_LockActionPerformed.
Referenced by Synchronize().
SetActions()
override void SetActions ()
Definition at line 491 of file combinationlock.c.
    {
        super.SetActions();
        AddAction(ActionAttachToConstruction);
        AddAction(ActionNextCombinationLockDial);
        AddAction(ActionDialCombinationLock);
        AddAction(ActionNextCombinationLockDialOnTarget);
        AddAction(ActionDialCombinationLockOnTarget);
    }
References ActionDialCombinationLock(), ActionDialCombinationLockOnTarget(), and AddAction().
SetBaseLockValues()
protected void SetBaseLockValues ()
Definition at line 45 of file combinationlock.c.
    {
        //set lock init values
        m_LockDigits            = 3;
        m_Combination           = 111;
        m_CombinationLocked     = 999;
        m_IsLocked              = false;
    }
References m_Combination, m_CombinationLocked, m_IsLocked, and m_LockDigits.
SetCombination()
void SetCombination (int combination)
Definition at line 181 of file combinationlock.c.
    {
        m_Combination = combination;
    }
References m_Combination.
Referenced by DialNextNumber(), and ShuffleLock().
SetCombinationLocked()
void SetCombinationLocked (int combination)
Definition at line 186 of file combinationlock.c.
    {
        m_CombinationLocked = combination;
    }
References m_CombinationLocked.
Referenced by LockServer().
SetInitialized()
void SetInitialized ()
Definition at line 65 of file combinationlock.c.
    {
        m_IsInitialized = true;
    }
References m_IsInitialized.
Referenced by EEInit().
SetNextDial()
void SetNextDial ()
Definition at line 247 of file combinationlock.c.
    {
        if ( m_LockDigits > 1 )
        {
            if ( m_DialIndex <= m_LockDigits - 2 )
            {
                m_DialIndex++;
            }
            else if ( m_DialIndex >= m_LockDigits >  - 1 )
            {
                m_DialIndex = 0;
            }
        }
        else
        {
            m_DialIndex = 0;
        }
        //performed action
        m_LockActionPerformed = LockAction.DIAL_NUMBER_CHANED;
        //synchronize
        Synchronize();
    }
References m_DialIndex, m_LockActionPerformed, m_LockDigits, and Synchronize().
ShowAttached()
protected void ShowAttached ()
Definition at line 453 of file combinationlock.c.
    {
        SetAnimationPhase( "Combination_Lock_Attached", 0 );
        SetAnimationPhase( "Lock_Attached_1",           0 );
        SetAnimationPhase( "Lock_Attached_2",           0 );
    }
Referenced by UpdateVisuals().
ShowItem()
protected void ShowItem ()
Definition at line 439 of file combinationlock.c.
    {
        SetAnimationPhase( "Combination_Lock_Item", 0 );
        SetAnimationPhase( "Lock_Item_1",           0 );
        SetAnimationPhase( "Lock_Item_2",           0 );
    }
Referenced by UpdateVisuals().
ShuffleLock()
void ShuffleLock ()
Definition at line 331 of file combinationlock.c.
    {
        string combination_text = m_Combination.ToString();
        string shuffled_text;
        //insert zeros to dials with 0 value
        int length_diff = m_LockDigits - combination_text.Length();
        for ( int i = 0; i < length_diff; ++i )
        {
            combination_text = "0" + combination_text;
        }
        //assemble the whole combination with increased part
        for ( int j = 0; j < combination_text.Length(); ++j )
        {
            int dial_number = combination_text.Get( j ).ToInt();
            dial_number = ( dial_number + Math.RandomInt( 1, 9 ) ) % 10;
            shuffled_text = shuffled_text + dial_number.ToString();
        }
        SetCombination( shuffled_text.ToInt() );
    }
References string::Get(), string::Length(), m_Combination, m_LockDigits, Math::RandomInt(), SetCombination(), string::ToInt(), and string::ToString().
Referenced by LockServer().
SoundLockChangeDial()
void SoundLockChangeDial ()
Definition at line 486 of file combinationlock.c.
    {
        PlaySoundSet( m_Sound, SOUND_LOCK_CHANGE_DIAL, 0, 0 );
    }
References m_Sound, PlaySoundSet(), and SOUND_LOCK_CHANGE_DIAL.
Referenced by UpdateSound().
SoundLockChangeNumber()
void SoundLockChangeNumber ()
Definition at line 481 of file combinationlock.c.
    {
        PlaySoundSet( m_Sound, SOUND_LOCK_CHANGE_NUMBER, 0, 0 );
    }
References m_Sound, PlaySoundSet(), and SOUND_LOCK_CHANGE_NUMBER.
Referenced by UpdateSound().
SoundLockClose()
protected void SoundLockClose ()
Definition at line 476 of file combinationlock.c.
    {
        PlaySoundSet( m_Sound, SOUND_LOCK_CLOSE, 0, 0 );
    }
References m_Sound, PlaySoundSet(), and SOUND_LOCK_CLOSE.
Referenced by UpdateSound().
SoundLockOpen()
protected void SoundLockOpen ()
Definition at line 471 of file combinationlock.c.
    {
        PlaySoundSet( m_Sound, SOUND_LOCK_OPEN, 0, 0 );
    }
References m_Sound, PlaySoundSet(), and SOUND_LOCK_OPEN.
Referenced by UpdateSound().
Synchronize()
void Synchronize ()
Definition at line 151 of file combinationlock.c.
    {
        bsbDebugPrint("[bsb] CombinationLock.Synchronize " + " m_Combination=" + m_Combination + " m_CombinationLocked=" + m_CombinationLocked);
        if ( GetGame().IsServer() )
        {
            SetSynchDirty();
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( ResetActionVar, 1000);//synced var used to trigger client sound needs to be reset after triggering the sound
            UpdateVisuals();
        }
    }
References bsbDebugPrint(), CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_Combination, m_CombinationLocked, ResetActionVar(), and UpdateVisuals().
Referenced by AfterStoreLoad(), ItemBase::AfterStoreLoad(), CheckValue(), DialNextNumber(), EEItemAttached(), EEItemDetached(), Weapon::FillChamber(), Heating(), LockServer(), ItemBase::MakeSoundsOnClient(), RefreshAudioVisualsOnClient(), RemoveAudioVisualsOnClient(), ItemBase::SetCookingTime(), SetFireState(), SetNextDial(), SetOvenState(), SetStoneCircleState(), Weapon::SpawnAttachedMagazine(), StartFire(), StopFire(), and UnlockServer().
UnlockServer()
void UnlockServer (EntityAI player, EntityAI parent)
Definition at line 299 of file combinationlock.c.
    {
        bsbDebugPrint("[bsb] CombinationLock.UnlockServer " + " m_Combination=" + m_Combination + " m_CombinationLocked=" + m_CombinationLocked);
        if ( IsLockAttached() )
        {
            Fence fence = Fence.Cast( parent );
            //set slot unlock
            InventoryLocation inventory_location = new InventoryLocation;
            GetInventory().GetCurrentInventoryLocation( inventory_location );
            fence.GetInventory().SetSlotLock( inventory_location.GetSlot(), false );
            //drop entity from attachment slot
            if (player)
                player.ServerDropEntity( this );
            else
                parent.GetInventory().DropEntity(InventoryMode.SERVER, parent, this);
            SetPosition( fence.GetKitSpawnPosition() );
            PlaceOnSurface();
            m_LockActionPerformed = LockAction.UNLOCKED;
            SetTakeable(true);
            CheckLockedStateServer();
            //synchronize
            Synchronize();
        }
        //reset performed action
        //m_LockActionPerformed = LockAction.NONE;
    }
References bsbDebugPrint(), CheckLockedStateServer(), InventoryLocation::GetSlot(), IsLockAttached(), m_Combination, m_CombinationLocked, m_LockActionPerformed, PlaceOnSurface(), EntityAI::ServerDropEntity(), SetPosition(), SetTakeable(), and Synchronize().
UpdateSound()
void UpdateSound ()
Definition at line 411 of file combinationlock.c.
    {
        //was locked
        if ( m_LockActionPerformed == LockAction.LOCKED )
        {
            SoundLockClose();
        }
        //was unlocked
        if ( m_LockActionPerformed == LockAction.UNLOCKED )
        {
            SoundLockOpen();
        }
        //next dial index
        if ( m_LockActionPerformed == LockAction.DIAL_INDEX_CHANGED )
        {
            SoundLockChangeDial();
        }
        //dialed new number
        if ( m_LockActionPerformed == LockAction.DIAL_NUMBER_CHANED )
        {
            SoundLockChangeNumber();
        }
    }
References m_LockActionPerformed, SoundLockChangeDial(), SoundLockChangeNumber(), SoundLockClose(), and SoundLockOpen().
Referenced by OnVariablesSynchronized().
UpdateVisuals()
void UpdateVisuals ()
Definition at line 396 of file combinationlock.c.
    {
        //Client/Server
        if ( IsLockedOnGate() )
        {
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( HideItem,       0, false );
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( ShowAttached,   0, false );
        }
        else
        {
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( ShowItem,       0, false );
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( HideAttached,   0, false );
        }
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), HideAttached(), HideItem(), IsLockedOnGate(), ShowAttached(), and ShowItem().
Variable Documentation
m_Combination
int m_Combination
Definition at line 15 of file combinationlock.c.
Referenced by CheckLockedStateServer(), DialNextNumber(), GetCombination(), LockServer(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), SetBaseLockValues(), CombinationLock::SetBaseLockValues(), SetCombination(), ShuffleLock(), Synchronize(), and UnlockServer().
m_CombinationLocked
int m_CombinationLocked
Definition at line 16 of file combinationlock.c.
Referenced by CheckLockedStateServer(), LockServer(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), SetBaseLockValues(), CombinationLock::SetBaseLockValues(), SetCombinationLocked(), Synchronize(), and UnlockServer().
m_DialIndex
int m_DialIndex
Definition at line 17 of file combinationlock.c.
Referenced by DialNextNumber(), GetDialIndex(), and SetNextDial().
m_IsInitialized
protected bool m_IsInitialized
Definition at line 22 of file combinationlock.c.
Referenced by IsInitialized(), and SetInitialized().
m_IsLocked
protected bool m_IsLocked
Definition at line 18 of file combinationlock.c.
m_LockActionPerformed
protected LockAction m_LockActionPerformed = LockAction.NONE
Definition at line 20 of file combinationlock.c.
Referenced by DialNextNumber(), LockServer(), OnVariablesSynchronized(), ResetActionVar(), SetNextDial(), UnlockServer(), and UpdateSound().
m_LockDigits
enum LockAction m_LockDigits
Referenced by CombinationLock(), DialNextNumber(), GetLockDigits(), SetBaseLockValues(), CombinationLock::SetBaseLockValues(), SetNextDial(), and ShuffleLock().
m_Sound
protected EffectSound m_Sound
Definition at line 31 of file combinationlock.c.
SOUND_LOCK_CHANGE_DIAL
const string SOUND_LOCK_CHANGE_DIAL = "combinationlock_changedial_SoundSet"
Definition at line 29 of file combinationlock.c.
Referenced by SoundLockChangeDial().
SOUND_LOCK_CHANGE_NUMBER
const string SOUND_LOCK_CHANGE_NUMBER = "combinationlock_changenumber_SoundSet"
Definition at line 28 of file combinationlock.c.
Referenced by SoundLockChangeNumber().
SOUND_LOCK_CLOSE
const string SOUND_LOCK_CLOSE = "combinationlock_close_SoundSet"
Definition at line 27 of file combinationlock.c.
Referenced by SoundLockClose().
SOUND_LOCK_OPEN
const string SOUND_LOCK_OPEN = "combinationlock_open_SoundSet"
Definition at line 26 of file combinationlock.c.
Referenced by SoundLockOpen().