DayzKode: P:/scripts/4_world/DayZ/classes/basebuilding/construction.c File Reference
construction.c File Reference
Classes
class ConstructionBoxTrigger
class StaticConstructionMethods
Enumerations
enum ConstructionMaterialType {
MATERIAL_NONE = 0 , MATERIAL_LOG = 1 , MATERIAL_WOOD = 2 , MATERIAL_STAIRS = 3 ,
MATERIAL_METAL = 4 , MATERIAL_WIRE = 5
}
Functions
void AddToConstructedParts (string part_name)
void BuildPartServer (notnull Man player, string part_name, int action_id)
bool CanBuildPart (string part_name, ItemBase tool, bool use_tool)
bool CanDestroyPart (string part_name)
bool CanDismantlePart (string part_name, ItemBase tool)
bool CanUseToolToBuildPart (string part_name, ItemBase tool)
bool CanUseToolToDismantlePart (string part_name, ItemBase tool)
void CollisionCheckData ()
void Construction (BaseBuildingBase parent)
void CreateCollisionTrigger (string part_name, vector min_max[2], vector center)
void DestroyCollisionTrigger ()
void DestroyConnectedParts (string part_name)
protected void DestroyDebugCollisionBox ()
protected void DestroyMaterialsServer (Man player, string part_name)
void DestroyPartServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part=false)
void DismantlePartServer (notnull Man player, string part_name, int action_id)
protected void DrawDebugCollisionBox (vector min_max[2], int color)
void DropNonUsableMaterialsServer (Man player, string part_name)
bool ExceptionCheck (string part_name)
Exceptions from 'dependent parts' hierarchy are handled here.
ConstructionPart GetBaseConstructionPart ()
vector GetBoxCenter (vector min_max[2])
protected void GetCollisionBoxData (string part_name, out vector min_max[2])
vector GetCollisionBoxSize (vector min_max[2])
ConstructionPart GetConstructionPart (string part_name)
map< string, ref ConstructionPart > GetConstructionParts ()
void GetConstructionPartsToBuild (string main_part_name, out array< ConstructionPart > construction_parts, ItemBase tool, out string real_constructionTarget, bool use_tool)
ConstructionPart GetConstructionPartToDestroy (string part_name)
ConstructionPart GetConstructionPartToDismantle (string part_name, ItemBase tool)
ConstructionPart GetGateConstructionPart ()
ConstructionMaterialType GetMaterialType (string part_name)
protected BaseBuildingBase GetParent ()
Get parent of the Effect.
array< string > GetRequiredParts (string part_name, string main_part_name)
void GetTriggerExtents (vector min_max[2], out vector extents[2])
protected array< string > GetValidDepenentPartsArray (string part_name, array< string > recurs=null)
protected bool HasConflictPart (string part_name)
bool HasDependentPart (string part_name)
bool HasMaterials (string part_name, bool repairing=false)
protected bool HasMaterialWithQuantityAttached (string slot_name, float quantity)
protected bool HasRequiredPart (string part_name)
protected void HideConstructionPart (string part_name)
void HideConstructionPartPhysics (string part_name)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void InitBaseState ()
void InitVisuals ()
bool IsColliding (string part_name)
bool IsCollidingEx (CollisionCheckData check_data)
Collision check for building part.
bool IsPartConstructed (string part_name)
bool IsTriggerColliding ()
bool MaterialIsRuined (string part_name)
protected void ReceiveMaterialsServer (notnull Man player, string part_name, string damagezone_name)
void RemoveFromConstructedParts (string part_name)
void SetLockOnAttachedMaterials (string part_name, bool lock_slot)
protected void SetParent (BaseBuildingBase parent)
protected void ShowConstructionPart (string part_name)
void ShowConstructionPartPhysics (string part_name)
void TakeMaterialsServer (string part_name, bool repairing=false)
protected void UpdateConstructionParts ()
void UpdatePhysics ()
void UpdateVisuals ()
Variables
static const float DECONSTURCT_MATERIAL_LOSS = 0.2
class StaticConstructionMethods m_AdditionalExcludes
Data structure for passing parameters (extendable, modable)
protected Shape m_CollisionBox
protected ConstructionBoxTrigger m_ConstructionBoxTrigger
protected ref map< string, ref ConstructionPart > m_ConstructionParts
protected BaseBuildingBase m_Parent
string m_PartName
int m_PrimaryGeometry
int m_SecondaryGeometry
enum ConstructionMaterialType REPAIR_MATERIAL_PERCENTAGE = 0.15
Enumeration Type Documentation
ConstructionMaterialType
enum ConstructionMaterialType
Enumerator
MATERIAL_NONE
MATERIAL_LOG
MATERIAL_WOOD
MATERIAL_STAIRS
MATERIAL_METAL
MATERIAL_WIRE
Definition at line 1 of file construction.c.
{
    MATERIAL_NONE   = 0,
    MATERIAL_LOG    = 1,
    MATERIAL_WOOD   = 2,
    MATERIAL_STAIRS = 3,
    MATERIAL_METAL  = 4,
    MATERIAL_WIRE   = 5
}
Function Documentation
AddToConstructedParts()
void AddToConstructedParts (string part_name)
Definition at line 52 of file construction.c.
    {
        ConstructionPart constrution_part = GetConstructionPart( part_name );
        if ( constrution_part )
        {
            bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " AddToConstructedParts part=" + constrution_part.GetPartName());
            constrution_part.SetBuiltState( true );
        }
    }
References bsbDebugPrint(), GetConstructionPart(), ConstructionPart::GetPartName(), m_Parent, and ConstructionPart::SetBuiltState().
BuildPartServer()
void BuildPartServer (notnull Man player, string part_name, int action_id)
Definition at line 75 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction BuildPartServer | " + part_name);
        //reset DamageZone health
        string damage_zone;
        if (DamageSystem.GetDamageZoneFromComponentName(GetParent(),part_name,damage_zone))
        {
            GetParent().SetAllowDamage(true);
            GetParent().SetHealthMax(damage_zone);
            GetParent().ProcessInvulnerabilityCheck(GetParent().GetInvulnerabilityTypeString());
        }
        //on action
        TakeMaterialsServer( part_name );
        //destroy build collision check trigger
        DestroyCollisionTrigger();
        //call event
        GetParent().OnPartBuiltServer( player, part_name, action_id );
    }
References bsbDebugPrint(), DestroyCollisionTrigger(), GetInvulnerabilityTypeString(), GetParent(), and TakeMaterialsServer().
CanBuildPart()
bool CanBuildPart (string part_name, ItemBase tool, bool use_tool)
Definition at line 294 of file construction.c.
    {
        if ( !IsPartConstructed( part_name ) && HasRequiredPart( part_name ) && !HasConflictPart( part_name ) && HasMaterials( part_name ) && (!use_tool || CanUseToolToBuildPart( part_name, tool )) && !MaterialIsRuined(part_name) )
        {
            return true;
        }
        return false;
    }
References CanUseToolToBuildPart(), HasConflictPart(), HasMaterials(), HasRequiredPart(), IsPartConstructed(), and MaterialIsRuined().
Referenced by GetConstructionPartsToBuild().
CanDestroyPart()
bool CanDestroyPart (string part_name)
Definition at line 565 of file construction.c.
    {
        if ( IsPartConstructed( part_name ) && !HasDependentPart( part_name ) )
        {
            return true;
        }
        return false;
    }
References HasDependentPart(), and IsPartConstructed().
Referenced by GetConstructionPartToDestroy().
CanDismantlePart()
bool CanDismantlePart (string part_name, ItemBase tool)
Definition at line 466 of file construction.c.
    {
        if ( IsPartConstructed( part_name ) && !HasDependentPart( part_name ) && CanUseToolToDismantlePart( part_name, tool ) )
        {
            return true;
        }
        return false;
    }
References CanUseToolToDismantlePart(), HasDependentPart(), and IsPartConstructed().
Referenced by GetConstructionPartToDismantle().
CanUseToolToBuildPart()
bool CanUseToolToBuildPart (string part_name, ItemBase tool)
Definition at line 949 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        string part_cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + construction_part.GetMainPartName() + " " + construction_part.GetPartName() + " " + "build_action_type";
        if ( GetGame().ConfigIsExisting( part_cfg_path ) )
        {
            int part_build_action_type = GetGame().ConfigGetInt( part_cfg_path );
            string tool_cfg_path = "cfgVehicles" + " " + tool.GetType() + " " + "build_action_type";
            if ( GetGame().ConfigIsExisting( tool_cfg_path ) )
            {
                int tool_build_action_type = GetGame().ConfigGetInt( tool_cfg_path );
                if ( ( part_build_action_type & tool_build_action_type ) > 0 )
                {
                    return true;
                }
            }
        }
        return false;
    }
References CGame::ConfigGetInt(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and ConstructionPart::GetPartName().
Referenced by CanBuildPart().
CanUseToolToDismantlePart()
bool CanUseToolToDismantlePart (string part_name, ItemBase tool)
Definition at line 972 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        string part_cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + construction_part.GetMainPartName() + " " + construction_part.GetPartName() + " " + "dismantle_action_type";
        if ( GetGame().ConfigIsExisting( part_cfg_path ) )
        {
            int part_dismantle_action_type = GetGame().ConfigGetInt( part_cfg_path );
            string tool_cfg_path = "cfgVehicles" + " " + tool.GetType() + " " + "dismantle_action_type";
            if ( GetGame().ConfigIsExisting( tool_cfg_path ) )
            {
                int tool_dismantle_action_type = GetGame().ConfigGetInt( tool_cfg_path );
                if ( ( part_dismantle_action_type & tool_dismantle_action_type ) > 0 )
                {
                    return true;
                }
            }
        }
        return false;
    }
References CGame::ConfigGetInt(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and ConstructionPart::GetPartName().
Referenced by CanDismantlePart().
CollisionCheckData()
void CollisionCheckData ()
Definition at line 1310 of file construction.c.
    {
        m_AdditionalExcludes = new array<Object>;
        m_PartName = "";
        m_PrimaryGeometry = ObjIntersectGeom;
        m_SecondaryGeometry = ObjIntersectView;
    }
References m_AdditionalExcludes, m_PartName, m_PrimaryGeometry, and m_SecondaryGeometry.
Referenced by ActionBuildPart::ActionConditionContinue(), ActionBuildShelter::ActionConditionContinue(), and ActionBuildPart::OnFinishProgressServer().
Construction()
void Construction (BaseBuildingBase parent)
Definition at line 26 of file construction.c.
    {
        m_ConstructionParts = new ref map<string, ref ConstructionPart>;
        //set parent object
        SetParent( parent );
    }
References m_ConstructionParts, and SetParent().
Referenced by ActionBuildPart::ActionConditionContinue(), ActionBuildShelter::ActionConditionContinue(), ComplexBuildCollideCheckClient(), ItemBase::ConstructionInit(), ActionDestroyPart::DestroyCondition(), ActionDismantlePart::DismantleCondition(), ItemBase::EEHealthLevelChanged(), ItemBase::GetConstructionPartById(), ActionBuildPart::OnFinishProgressServer(), ActionDestroyPart::OnFinishProgressServer(), ActionDismantlePart::OnFinishProgressServer(), ActionRepairPart::OnFinishProgressServer(), ActionBuildShelter::OnFinishProgressServer(), ActionRepairPart::RepairCondition(), ItemBase::SetPartsFromSyncData(), and StaticConstructionMethods::SpawnConstructionMaterialPiles().
CreateCollisionTrigger()
void CreateCollisionTrigger (string part_name, vector min_max[2], vector center)
Definition at line 1180 of file construction.c.
    {
        if ( m_ConstructionBoxTrigger )
        {
            if ( m_ConstructionBoxTrigger.GetPartName() == part_name )      //already created
            {
                return;
            }
            else
            {
                DestroyCollisionTrigger();
            }
        }
        //get proper trigger extents (min<max)
        vector extents[2];
        GetTriggerExtents( min_max, extents );
        //create trigger
        m_ConstructionBoxTrigger = ConstructionBoxTrigger.Cast( GetGame().CreateObject( "ConstructionBoxTrigger", center, false, false, false ) );
        m_ConstructionBoxTrigger.SetPosition( center );
        m_ConstructionBoxTrigger.SetOrientation( GetParent().GetOrientation() );
        m_ConstructionBoxTrigger.SetExtents( extents[0], extents[1] );
        m_ConstructionBoxTrigger.SetPartName( part_name );
    }
References DestroyCollisionTrigger(), GetGame(), GetOrientation(), GetParent(), ConstructionBoxTrigger::GetPartName(), GetTriggerExtents(), m_ConstructionBoxTrigger, Trigger::SetExtents(), and ConstructionBoxTrigger::SetPartName().
DestroyCollisionTrigger()
void DestroyCollisionTrigger ()
Definition at line 1208 of file construction.c.
    {
        GetGame().ObjectDelete( m_ConstructionBoxTrigger );
        m_ConstructionBoxTrigger = NULL;
    }
References GetGame(), m_ConstructionBoxTrigger, and CGame::ObjectDelete().
Referenced by BuildPartServer(), and CreateCollisionTrigger().
DestroyConnectedParts()
void DestroyConnectedParts (string part_name)
Definition at line 141 of file construction.c.
    {
        array<string> parts;// = new array<string>;
        parts = GetValidDepenentPartsArray(part_name);
        if (parts)
        {
            for (int i = 0; i < parts.Count(); i++)
            {
                bsbDebugPrint("[bsb] Construction DestroyConnectedParts | " + parts.Get(i));
                if (!ExceptionCheck(parts.Get(i)))
                    DestroyPartServer(null,parts.Get(i),AT_DESTROY_PART,true);
            }
        }
    }
References AT_DESTROY_PART, bsbDebugPrint(), DestroyPartServer(), ExceptionCheck(), and GetValidDepenentPartsArray().
DestroyDebugCollisionBox()
protected void DestroyDebugCollisionBox ()
Definition at line 1171 of file construction.c.
    {
        if ( m_CollisionBox )
        {
            m_CollisionBox.Destroy();
            m_CollisionBox = NULL;
        }
    }
References m_CollisionBox.
Referenced by DrawDebugCollisionBox(), Hologram::UpdateHologram(), and Hologram::~Hologram().
DestroyMaterialsServer()
protected void DestroyMaterialsServer (Man player, string part_name)
Definition at line 739 of file construction.c.
    {
        ConstructionPart cPart = GetConstructionPart( part_name );
        string main_part_name = cPart.GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                //get type, quantity from material
                string config_path;
                string type;
                string slot_name;
                config_path = cfg_path + " " + child_name + " " + "type";
                GetGame().ConfigGetText( config_path, type );
                config_path = cfg_path + " " + child_name + " " + "slot_name";
                GetGame().ConfigGetText( config_path, slot_name );
                config_path = cfg_path + " " + child_name + " " + "quantity";
                float quantity = GetGame().ConfigGetFloat( config_path );
                config_path = cfg_path + " " + child_name + " " + "lockable";
                bool lockable = GetGame().ConfigGetInt( config_path );
                //get material
                ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( slot_name ) );
                //material still attached
                if ( lockable )         //if lockable
                {
                    if ( attachment )
                    {
                        InventoryLocation inventory_location = new InventoryLocation;
                        attachment.GetInventory().GetCurrentInventoryLocation( inventory_location );
                        bsbDebugPrint("[bsb] " + Object.GetDebugName(GetParent()) + " DestroyMaterialsServer unlock slot=" + inventory_location.GetSlot());
                        GetParent().GetInventory().SetSlotLock( inventory_location.GetSlot() , false );
                        GetGame().ObjectDelete( attachment );       //delete object
                    }
                }
            }
        }
    }
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), InventoryLocation::GetSlot(), and CGame::ObjectDelete().
Referenced by DestroyPartServer().
DestroyPartServer()
void DestroyPartServer (Man player, string part_name, int action_id, bool destroyed_by_connected_part = false)
Definition at line 121 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction DestroyPartServer | " + part_name);
        //destroy attached materials (if locked)
        DestroyMaterialsServer( player, part_name );
        //drop non-usable materials
        DropNonUsableMaterialsServer( player, part_name );
        //call event
        GetParent().OnPartDestroyedServer( player, part_name, action_id, destroyed_by_connected_part );
        //set DamageZone health to zero (redundant?)
        string damage_zone;
        if ( DamageSystem.GetDamageZoneFromComponentName(GetParent(),part_name,damage_zone) && GetParent().GetHealth(damage_zone,"Health") > 0 )
        {
            GetParent().SetHealth(damage_zone,"Health",0);
        }
    }
References bsbDebugPrint(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), GetHealth(), and GetParent().
Referenced by DestroyConnectedParts().
DismantlePartServer()
void DismantlePartServer (notnull Man player, string part_name, int action_id)
Definition at line 98 of file construction.c.
    {
        string damage_zone;
        DamageSystem.GetDamageZoneFromComponentName( GetParent(),part_name,damage_zone );
        bsbDebugPrint("[bsb] Construction DismantlePartServer | " + part_name);
        //receive materials
        ReceiveMaterialsServer( player, part_name, damage_zone );
        //drop non-usable materials
        DropNonUsableMaterialsServer( player, part_name );
        //call event
        GetParent().OnPartDismantledServer( player, part_name, action_id );
        //set DamageZone health to zero (redundant?)
        /*if ( GetParent().GetHealth(damage_zone,"Health") > 0 )
        {
            GetParent().SetHealth(damage_zone,"Health",0);
        }*/
    }
References bsbDebugPrint(), DropNonUsableMaterialsServer(), GetParent(), and ReceiveMaterialsServer().
DrawDebugCollisionBox()
protected void DrawDebugCollisionBox (vector min_max[2], int color)
Definition at line 1160 of file construction.c.
    {
        DestroyDebugCollisionBox();
        vector mat[4];
        GetParent().GetTransform( mat );
        m_CollisionBox = Debug.DrawBox( min_max[0], min_max[1], color );
        m_CollisionBox.SetMatrix( mat );
    }
References DestroyDebugCollisionBox(), Debug::DrawBox(), GetParent(), and m_CollisionBox.
Referenced by Hologram::IsCollidingBBox().
DropNonUsableMaterialsServer()
void DropNonUsableMaterialsServer (Man player, string part_name)
Definition at line 787 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " " + "Construction" + " " + construction_part.GetMainPartName() + " " + construction_part.GetPartName() + " " + "platform_support";
        string platform_support;
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            GetGame().ConfigGetText( cfg_path, platform_support );
        }
        if ( platform_support.Length() > 0 || construction_part.IsBase() )
        {
            string at_cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "GUIInventoryAttachmentsProps";
            if ( GetGame().ConfigIsExisting( at_cfg_path ) )
            {
                int child_count = GetGame().ConfigGetChildrenCount( at_cfg_path );
                for ( int i = 0; i < child_count; i++ )
                {
                    string child_name;
                    GetGame().ConfigGetChildName( at_cfg_path, i, child_name );
                    child_name.ToLower();
                    if ( child_name.Contains( platform_support ) )
                    {
                        ref array<string> attachment_slots = new array<string>;
                        GetGame().ConfigGetTextArray( at_cfg_path + " " + child_name + " " + "attachmentSlots", attachment_slots );
                        for ( int j = 0; j < attachment_slots.Count(); ++j )
{
                            //get material
                            ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( attachment_slots.Get( j ) ) );
                            //material still attached
                            if ( attachment )
{
                                InventoryLocation inventory_location = new InventoryLocation;
                                attachment.GetInventory().GetCurrentInventoryLocation( inventory_location );
                                bsbDebugPrint("[bsb] " + Object.GetDebugName(GetParent()) + " DropNonUsableMaterials UNlocking slot=" + inventory_location.GetSlot());
                                //unlock slot
                                GetParent().GetInventory().SetSlotLock( inventory_location.GetSlot() , false );
                                EntityAI parent = GetParent();
                                if (!parent)
                                    parent = player;
                                int quantity_max = attachment.GetTargetQuantityMax(-1);
                                InventoryLocation dst = new InventoryLocation;
                                vector mat[4];
                                attachment.GetTransform(mat);
                                if ( parent.MemoryPointExists("" + part_name + "_materials") )
{
                                    vector destination = parent.GetMemoryPointPos("" + part_name + "_materials");
                                    destination = GetGame().ObjectModelToWorld(parent,destination);
                                    float health = attachment.GetHealth("","Health");
                                    float quantity = attachment.GetQuantity() - 1;
                                    if (quantity < 1.0)
                                        quantity = 1.0;
                                    float dir[4];
                                    inventory_location.GetDir(dir);
                                    dst.SetGroundEx(attachment,destination,dir);
                                    //Print(dst.DumpToString());
                                    MiscGameplayFunctions.CreateItemBasePiles(attachment.GetType(),destination,quantity,health,true);
                                    attachment.AddQuantity( -quantity );
                                }
                                else
{
                                    dst.SetGround(attachment,mat);
                                    for ( int k = attachment.GetQuantity(); k > quantity_max;  )
{
                                        Object o = parent.GetInventory().LocationCreateEntity( dst, attachment.GetType(), ECE_PLACE_ON_SURFACE, RF_DEFAULT );
                                        ItemBase new_item = ItemBase.Cast( o );
                                        if( new_item )
{
                                            MiscGameplayFunctions.TransferItemProperties( attachment, new_item );
                                            attachment.AddQuantity( -quantity_max );
                                            new_item.SetQuantity( quantity_max );
                                        }
                                        k -= quantity_max;
                                    }
                                }
                                //drop
                                if (attachment.GetQuantity() > 0)
{
                                    if ( GetGame().IsMultiplayer() )
{
                                        parent.ServerTakeToDst( inventory_location, dst );
                                    }
                                    else
{
                                        parent.LocalTakeToDst( inventory_location, dst );
                                    }
                                }
                                else
{
                                    attachment.Delete();
                                }
                            }
                        }
                    }
                }
            }
        }
    }
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), ConfigIsExisting(), string::Contains(), ECE_PLACE_ON_SURFACE, GetConstructionPart(), InventoryLocation::GetDir(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), ConstructionPart::GetPartName(), InventoryLocation::GetSlot(), ConstructionPart::IsBase(), string::Length(), EntityAI::LocalTakeToDst(), CGame::ObjectModelToWorld(), RF_DEFAULT, EntityAI::ServerTakeToDst(), InventoryLocation::SetGround(), InventoryLocation::SetGroundEx(), and string::ToLower().
Referenced by DestroyPartServer(), and DismantlePartServer().
ExceptionCheck()
bool ExceptionCheck (string part_name)
Exceptions from 'dependent parts' hierarchy are handled here.
Definition at line 157 of file construction.c.
    {
        //gate hack
        ConstructionPart part = GetConstructionPart(part_name);
        if( /*Fence.Cast(m_Parent) && */part.IsGate() )
        {
            if( GetConstructionPart("wall_base_down").IsBuilt() || GetConstructionPart("wall_base_up").IsBuilt() )
                return true;
        }
        return false;
    }
References GetConstructionPart(), and ConstructionPart::IsGate().
Referenced by DestroyConnectedParts().
GetBaseConstructionPart()
ConstructionPart GetBaseConstructionPart ()
Definition at line 376 of file construction.c.
    {
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart value = m_ConstructionParts.Get( key );
            if ( value.IsBase() )
            {
                return value;
            }
        }
        return NULL;
    }
References ConstructionPart::IsBase(), and m_ConstructionParts.
GetBoxCenter()
vector GetBoxCenter (vector min_max[2])
Definition at line 1136 of file construction.c.
    {
        vector center;
        center[0] = ( min_max[1][0] - min_max[0][0] ) / 2;
        center[1] = ( min_max[1][1] - min_max[0][1] ) / 2;
        center[2] = ( min_max[1][2] - min_max[0][2] ) / 2;
        center = Vector( min_max[1][0] - center[0], min_max[1][1] - center[1], min_max[1][2] - center[2] ); //offset to box center
        return center;
    }
References Vector().
Referenced by IsColliding(), and IsCollidingEx().
GetCollisionBoxData()
protected void GetCollisionBoxData (string part_name, out vector min_max[2])
Definition at line 1115 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "collision_data";
        ref array<string> collision_data = new array<string>;
        GetGame().ConfigGetTextArray( cfg_path, collision_data );
        if ( collision_data.Count() > 0 )
        {
            if ( GetParent().MemoryPointExists( collision_data[0] ) )
            {
                min_max[0] = GetParent().GetMemoryPointPos( collision_data[0] );
            }
            if ( GetParent().MemoryPointExists( collision_data[1] ) )
            {
                min_max[1] = GetParent().GetMemoryPointPos( collision_data[1] );
            }
        }
    }
References CGame::ConfigGetTextArray(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and MemoryPointExists().
Referenced by IsColliding(), and IsCollidingEx().
GetCollisionBoxSize()
vector GetCollisionBoxSize (vector min_max[2])
Definition at line 1103 of file construction.c.
    {
        vector box_size = Vector( 0, 0, 0 );
        box_size[0] = Math.AbsFloat( min_max[1][0] - min_max[0][0] );
        box_size[1] = Math.AbsFloat( min_max[1][1] - min_max[0][1] );
        box_size[2] = Math.AbsFloat( min_max[1][2] - min_max[0][2] );
        return box_size;
    }
References Math::AbsFloat(), and Vector().
Referenced by GetTriggerExtents(), IsColliding(), and IsCollidingEx().
GetConstructionPart()
ConstructionPart GetConstructionPart (string part_name)
Definition at line 278 of file construction.c.
    {
        return m_ConstructionParts.Get( part_name );
    }
References m_ConstructionParts.
Referenced by AddToConstructedParts(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), ExceptionCheck(), GetCollisionBoxData(), GetConstructionPartToDestroy(), GetConstructionPartToDismantle(), GetMaterialType(), HasConflictPart(), HasMaterials(), HasRequiredPart(), IsColliding(), IsCollidingEx(), IsPartConstructed(), MaterialIsRuined(), ReceiveMaterialsServer(), RemoveFromConstructedParts(), SetLockOnAttachedMaterials(), and TakeMaterialsServer().
GetConstructionParts()
map< string, ref ConstructionPart > GetConstructionParts ()
Definition at line 273 of file construction.c.
    {
        return m_ConstructionParts;
    }
References m_ConstructionParts.
GetConstructionPartsToBuild()
void GetConstructionPartsToBuild (string main_part_name, out array< ConstructionPart > construction_parts, ItemBase tool, out string real_constructionTarget, bool use_tool)
Definition at line 337 of file construction.c.
    {
        construction_parts.Clear();
        string part_name;
        ConstructionPart value;
        string key;
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            key = m_ConstructionParts.GetKey( i );
            value = m_ConstructionParts.Get( key );
            if ( main_part_name == value.GetMainPartName() && CanBuildPart( value.GetPartName(), tool, use_tool ) )
            {
                construction_parts.Insert( value );
            }
            if ( main_part_name == value.GetPartName() )
            {
                part_name = value.GetMainPartName();
            }
        }
        if( construction_parts.Count() == 0 && part_name )
        {
            for ( i = 0; i < m_ConstructionParts.Count(); ++i )
            {
                key = m_ConstructionParts.GetKey( i );
                value = m_ConstructionParts.Get( key );
                if ( part_name == value.GetMainPartName() && CanBuildPart( value.GetPartName(), tool, use_tool ) )
                {
                    construction_parts.Insert( value );
                }
            }
        }
    }
References CanBuildPart(), ConstructionPart::GetMainPartName(), ConstructionPart::GetPartName(), and m_ConstructionParts.
GetConstructionPartToDestroy()
ConstructionPart GetConstructionPartToDestroy (string part_name)
Definition at line 555 of file construction.c.
    {
        if ( CanDestroyPart( part_name ) )
        {
            return GetConstructionPart( part_name );
        }
        return NULL;
    }
References CanDestroyPart(), and GetConstructionPart().
GetConstructionPartToDismantle()
ConstructionPart GetConstructionPartToDismantle (string part_name, ItemBase tool)
Definition at line 456 of file construction.c.
    {
        if ( CanDismantlePart( part_name, tool ) )
        {
            return GetConstructionPart( part_name );
        }
        return NULL;
    }
References CanDismantlePart(), and GetConstructionPart().
GetGateConstructionPart()
ConstructionPart GetGateConstructionPart ()
Definition at line 393 of file construction.c.
    {
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart value = m_ConstructionParts.Get( key );
            if ( value.IsGate() )
            {
                return value;
            }
        }
        return NULL;
    }
References ConstructionPart::IsGate(), and m_ConstructionParts.
GetMaterialType()
ConstructionMaterialType GetMaterialType (string part_name)
Definition at line 995 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        string part_cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + construction_part.GetMainPartName() + " " + construction_part.GetPartName() + " " + "material_type";
        if ( GetGame().ConfigIsExisting( part_cfg_path ) )
        {
            return GetGame().ConfigGetInt( part_cfg_path );
        }
        return ConstructionMaterialType.MATERIAL_NONE;
    }
References CGame::ConfigGetInt(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and ConstructionPart::GetPartName().
GetRequiredParts()
array< string > GetRequiredParts (string part_name, string main_part_name)
Definition at line 545 of file construction.c.
    {
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " " + "Construction" + " " + main_part_name + " " + part_name + " " + "required_parts";
        ref array<string> required_parts = new array<string>;
        GetGame().ConfigGetTextArray( cfg_path, required_parts );
        return required_parts;
    }
References CGame::ConfigGetTextArray(), GetGame(), and GetParent().
Referenced by UpdateConstructionParts().
GetTriggerExtents()
void GetTriggerExtents (vector min_max[2], out vector extents[2])
Definition at line 1148 of file construction.c.
    {
        vector egde_length = GetCollisionBoxSize( min_max );
        extents[0][0] = -egde_length[0] / 2;        //min
        extents[0][1] = -egde_length[1] / 2;
        extents[0][2] = -egde_length[2] / 2;
        extents[1][0] = egde_length[0] / 2;         //max
        extents[1][1] = egde_length[1] / 2;
        extents[1][2] = egde_length[2] / 2;
    }
References GetCollisionBoxSize().
Referenced by CreateCollisionTrigger().
GetValidDepenentPartsArray()
protected array< string > GetValidDepenentPartsArray (string part_name, array< string > recurs = null)
Definition at line 498 of file construction.c.
    {
        string name;
        string cfg_path;
        ref array<string> dependent_parts;
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            name = m_ConstructionParts.GetKey( i );
            ConstructionPart construction_part = m_ConstructionParts.Get( name );
            if ( construction_part.IsBuilt() && construction_part.GetRequiredParts() && construction_part.GetRequiredParts().Find( part_name ) > -1 ) //does the construction part need 'part_name' to exist?
            {
                if ( !dependent_parts )
                {
                    dependent_parts = new array<string>;
                }
                if ( !recurs || (recurs.Find(name) == -1 ) )
                {
                    dependent_parts.Insert(name);
                }
//              Print("part #" + i + ": " + name);
            }
        }
        //fully recursive search, disconnected (unnescessary)
        /*if (dependent_parts)
        {
            if ( dependent_parts.Count() > 0 )
            {
                ref array<string> temp = new array<string>;
                for ( i = 0; i < dependent_parts.Count(); i++ )
                {
                    temp = GetValidDepenentPartsArray(dependent_parts.Get(i),dependent_parts);
                    if (temp.Count() > 0)
                    {
                        dependent_parts.InsertAll(temp);
                    }
                }
            }
            Print("dependent_parts.Count(): " + dependent_parts.Count());
        }*/
        return dependent_parts;
    }
References ConstructionPart::GetRequiredParts(), ConstructionPart::IsBuilt(), m_ConstructionParts, and name.
Referenced by DestroyConnectedParts().
HasConflictPart()
protected bool HasConflictPart (string part_name)
Definition at line 436 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "conflicted_parts";
        ref array<string> conflict_parts = new array<string>;
        GetGame().ConfigGetTextArray( cfg_path, conflict_parts );
        //check if parts are already built
        for ( int i = 0; i < conflict_parts.Count(); i++ )
        {
            if ( IsPartConstructed( conflict_parts.Get( i ) ) )
            {
                return true;
            }
        }
        return false;
    }
References CGame::ConfigGetTextArray(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and IsPartConstructed().
Referenced by CanBuildPart().
HasDependentPart()
bool HasDependentPart (string part_name)
Definition at line 478 of file construction.c.
    {
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart construction_part = m_ConstructionParts.Get( key );
            if ( construction_part.IsBuilt() )
            {
                if ( construction_part.GetRequiredParts().Find( part_name ) > -1 )
                {
                    return true;
                }
            }
        }
        return false;
    }
References ConstructionPart::GetRequiredParts(), ConstructionPart::IsBuilt(), and m_ConstructionParts.
Referenced by CanDestroyPart(), and CanDismantlePart().
HasMaterials()
bool HasMaterials (string part_name, bool repairing = false)
Definition at line 616 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                //get type, quantity from material
                string material_path;
                string slot_name;
                float quantity;
                material_path = cfg_path + " " + child_name + " " + "slot_name";
                GetGame().ConfigGetText( material_path, slot_name );
                material_path = cfg_path + " " + child_name + " " + "quantity";
                quantity = GetGame().ConfigGetFloat( material_path );
                if (repairing)
                {
                    quantity *= REPAIR_MATERIAL_PERCENTAGE;
                    quantity = Math.Max(Math.Floor(quantity),1);
                }
                //if the selected material (or its quantity) is not available
                if ( !HasMaterialWithQuantityAttached( slot_name, quantity ) )
                {
                    return false;
                }
            }
        }
        return true;    //return true even if no material required
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetText(), ConfigIsExisting(), Math::Floor(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), HasMaterialWithQuantityAttached(), Math::Max(), and REPAIR_MATERIAL_PERCENTAGE.
Referenced by CanBuildPart().
HasMaterialWithQuantityAttached()
protected bool HasMaterialWithQuantityAttached (string slot_name, float quantity)
Definition at line 657 of file construction.c.
    {
        ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( slot_name ) );
        if ( attachment && attachment.GetQuantity() >= quantity )
        {
            return true;
        }
        return false;
    }
References GetParent().
Referenced by HasMaterials().
HasRequiredPart()
protected bool HasRequiredPart (string part_name)
Definition at line 410 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "required_parts";
        ref array<string> required_parts = new array<string>;
        GetGame().ConfigGetTextArray( cfg_path, required_parts );
        //check if parts are already built
        for ( int i = 0; i < required_parts.Count(); ++i )
        {
            if ( !IsPartConstructed( required_parts.Get( i ) ) )
            {
                return false;
            }
            //hack - gate
            /*else if (part_name == "wall_gate" && (IsPartConstructed("wall_base_down") || IsPartConstructed("wall_base_up")))
            {
                return true;
            }*/
        }
        return true;
    }
References CGame::ConfigGetTextArray(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and IsPartConstructed().
Referenced by CanBuildPart().
HideConstructionPart()
protected void HideConstructionPart (string part_name)
Definition at line 583 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction HideConstructionPart - " + part_name);
        GetParent().SetAnimationPhase( part_name, 1 );
    }
References bsbDebugPrint(), and GetParent().
Referenced by UpdateVisuals().
HideConstructionPartPhysics()
void HideConstructionPartPhysics (string part_name)
Definition at line 595 of file construction.c.
    {
        GetParent().RemoveProxyPhysics( part_name );
    }
References GetParent().
Referenced by UpdatePhysics().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 34 of file construction.c.
    {
        UpdateConstructionParts();
    }
References UpdateConstructionParts().
InitBaseState()
void InitBaseState ()
Definition at line 228 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " InitBaseState");
        InitVisuals();
    }
References bsbDebugPrint(), InitVisuals(), and m_Parent.
Referenced by ItemBase::EEInit().
InitVisuals()
void InitVisuals ()
Definition at line 173 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " InitVisuals");
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart value = m_ConstructionParts.Get( key );
            if ( value.IsBuilt() )
            {
                ShowConstructionPart( value.GetPartName() );
            }
        }
    }
References bsbDebugPrint(), ConstructionPart::GetPartName(), ConstructionPart::IsBuilt(), m_ConstructionParts, m_Parent, and ShowConstructionPart().
Referenced by InitBaseState(), and ItemBase::InitBaseState().
IsColliding()
bool IsColliding (string part_name)
Definition at line 1011 of file construction.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingCheck())
            return false;
        ConstructionPart construction_part = GetConstructionPart( part_name );
        if ( construction_part )
        {
            vector center;
            float absolute_ofset = 0.05;    //we need to lift BBox even more, because it colliddes with house floors due to various reasons (probably geometry or float imperfections)
            vector edge_length;
            vector min_max[2];              //data used for creating trigger
            ref array<Object> excluded_objects = new array<Object>;
            ref array<Object> collided_objects = new array<Object>;
            excluded_objects.Insert( GetParent() );
            //get min_max and center from config and memory points
            GetCollisionBoxData( part_name, min_max );
            center = GetBoxCenter( min_max );
            center = GetParent().ModelToWorld( center );        //convert to world coordinates
            edge_length = GetCollisionBoxSize( min_max );
            //Create trigger
            //CreateCollisionTrigger( part_name, min_max, center );
            //check collision on box trigger and collision box
            //IsTrigger colliding was turned off (for now) for easier way to build something with other players around
            if ( /* IsTriggerColliding() || */ GetGame().IsBoxCollidingGeometry( Vector( center[0], center[1] + absolute_ofset, center[2] ), GetParent().GetOrientation(), edge_length, ObjIntersectView, ObjIntersectGeom, excluded_objects, collided_objects ) )
            {
                //Debug
//              DrawDebugCollisionBox(min_max, ARGB(150, 255, 0, 0));
                //
                for (int i = 0; i < collided_objects.Count(); i++)
                {
                    //Print(collided_objects.Get(i).GetType());
                    EntityAI entity = EntityAI.Cast(collided_objects.Get(i));
                    if ( entity && !entity.IsIgnoredByConstruction() )
                        return true;
                }
            }
            //Debug
//          DrawDebugCollisionBox(min_max, ARGB(150, 255, 255, 255));
        }
        return false;
    }
References GetBoxCenter(), GetCollisionBoxData(), GetCollisionBoxSize(), GetConstructionPart(), CfgGameplayHandler::GetDisableIsCollidingCheck(), GetGame(), GetOrientation(), GetParent(), EntityAI::IsIgnoredByConstruction(), and Vector().
IsCollidingEx()
bool IsCollidingEx (CollisionCheckData check_data)
Collision check for building part.
Definition at line 1060 of file construction.c.
    {
        if (CfgGameplayHandler.GetDisableIsCollidingCheck())
            return false;
        ConstructionPart construction_part = GetConstructionPart( check_data.m_PartName );
        if ( construction_part )
        {
            vector center;
            float absolute_ofset = 0.05;    //we need to lift BBox even more, because it colliddes with house floors due to various reasons (probably geometry or float imperfections)
            vector edge_length;
            vector min_max[2];              //data used for creating trigger
            ref array<Object> excluded_objects = new array<Object>;
            ref array<Object> collided_objects = new array<Object>;
            excluded_objects.Insert( GetParent() );
            if (check_data.m_AdditionalExcludes.Count() > 0)
            {
                excluded_objects.InsertAll(check_data.m_AdditionalExcludes);
            }
            GetCollisionBoxData( check_data.m_PartName, min_max );
            center = GetBoxCenter( min_max );
            center = GetParent().ModelToWorld( center );        //convert to world coordinates
            edge_length = GetCollisionBoxSize( min_max );
            if ( GetGame().IsBoxCollidingGeometry( Vector( center[0], center[1] + absolute_ofset, center[2] ), GetParent().GetOrientation(), edge_length, check_data.m_PrimaryGeometry, check_data.m_SecondaryGeometry, excluded_objects, collided_objects ) )
            {
                //Debug
                //DrawDebugCollisionBox( min_max, ARGB( 150, 255, 0, 0 ) );
                for (int i = 0; i < collided_objects.Count(); i++)
                {
                    EntityAI entity = EntityAI.Cast(collided_objects.Get(i));
                    if ( entity && !entity.IsIgnoredByConstruction() )
                        return true;
                }
            }
            //Debug
            //DrawDebugCollisionBox( min_max, ARGB( 150, 255, 255, 255 ) );
        }
        return false;
    }
References GetBoxCenter(), GetCollisionBoxData(), GetCollisionBoxSize(), GetConstructionPart(), CfgGameplayHandler::GetDisableIsCollidingCheck(), GetGame(), GetOrientation(), GetParent(), EntityAI::IsIgnoredByConstruction(), and Vector().
IsPartConstructed()
bool IsPartConstructed (string part_name)
Definition at line 601 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        if ( construction_part && construction_part.IsBuilt() )
        {
            return true;
        }
        return false;
    }
References GetConstructionPart(), and ConstructionPart::IsBuilt().
Referenced by CanBuildPart(), CanDestroyPart(), CanDismantlePart(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanReceiveAttachment(), HasConflictPart(), and HasRequiredPart().
IsTriggerColliding()
bool IsTriggerColliding ()
Definition at line 1214 of file construction.c.
    {
        return m_ConstructionBoxTrigger.IsColliding();
    }
References ConstructionBoxTrigger::IsColliding(), and m_ConstructionBoxTrigger.
MaterialIsRuined()
bool MaterialIsRuined (string part_name)
Definition at line 304 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                //get type, quantity from material
                string config_path;
                string slot_name;
                config_path = cfg_path + " " + child_name + " " + "slot_name";
                GetGame().ConfigGetText( config_path, slot_name );
                config_path = cfg_path + " " + child_name + " " + "quantity";
                float quantity = GetGame().ConfigGetFloat( config_path );
                config_path = cfg_path + " " + child_name + " " + "lockable";
                bool lockable = GetGame().ConfigGetInt( config_path );
                ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( slot_name ) );
                if (attachment.IsRuined())
                    return true;
            }
        }
        return false;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), and GetParent().
Referenced by CanBuildPart().
ReceiveMaterialsServer()
protected void ReceiveMaterialsServer (notnull Man player, string part_name, string damagezone_name)
Definition at line 725 of file construction.c.
    {
        ConstructionPart construction_part = GetConstructionPart( part_name );
        bool is_base = construction_part.IsBase();
        string main_part_name = construction_part.GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            StaticConstructionMethods.SpawnConstructionMaterialPiles(GetParent(),player,cfg_path,part_name,damagezone_name,is_base);
        }
    }
References ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), ConstructionPart::IsBase(), and StaticConstructionMethods::SpawnConstructionMaterialPiles().
Referenced by DismantlePartServer().
RemoveFromConstructedParts()
void RemoveFromConstructedParts (string part_name)
Definition at line 63 of file construction.c.
    {
        ConstructionPart constrution_part = GetConstructionPart( part_name );
        if ( constrution_part )
        {
            bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " RemoveFromConstructedParts part=" + constrution_part.GetPartName());
            constrution_part.SetBuiltState( false );
        }
    }
References bsbDebugPrint(), GetConstructionPart(), ConstructionPart::GetPartName(), m_Parent, and ConstructionPart::SetBuiltState().
SetLockOnAttachedMaterials()
void SetLockOnAttachedMaterials (string part_name, bool lock_slot)
Definition at line 901 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                //get type, quantity from material
                string config_path;
                string type;
                string slot_name;
                config_path = cfg_path + " " + child_name + " " + "type";
                GetGame().ConfigGetText( config_path, type );
                config_path = cfg_path + " " + child_name + " " + "slot_name";
                GetGame().ConfigGetText( config_path, slot_name );
                config_path = cfg_path + " " + child_name + " " + "quantity";
                float quantity = GetGame().ConfigGetFloat( config_path );
                config_path = cfg_path + " " + child_name + " " + "lockable";
                bool lockable = GetGame().ConfigGetInt( config_path );
                //get material
                ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( slot_name ) );
                //material still attached
                if ( lockable )         //if lockable
                {
                    if ( attachment )
                    {
                        InventoryLocation inventory_location = new InventoryLocation;
                        attachment.GetInventory().GetCurrentInventoryLocation( inventory_location );
                        bsbDebugPrint("[bsb] " + Object.GetDebugName(GetParent()) + " SetLockOnAttachedMaterials lock=" + lock_slot +" slot=" + inventory_location.GetSlot());
                        GetParent().GetInventory().SetSlotLock( inventory_location.GetSlot(), lock_slot );
                    }
                }
            }
        }
    }
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), ConfigIsExisting(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), and InventoryLocation::GetSlot().
SetParent()
protected void SetParent (BaseBuildingBase parent)
Definition at line 44 of file construction.c.
    {
        m_Parent = parent;
    }
References m_Parent.
ShowConstructionPart()
protected void ShowConstructionPart (string part_name)
Definition at line 577 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction ShowConstructionPart - " + part_name);
        GetParent().SetAnimationPhase( part_name, 0 );
    }
References bsbDebugPrint(), and GetParent().
Referenced by InitVisuals(), and UpdateVisuals().
ShowConstructionPartPhysics()
void ShowConstructionPartPhysics (string part_name)
Definition at line 590 of file construction.c.
    {
        GetParent().AddProxyPhysics( part_name );
    }
References GetParent().
Referenced by UpdatePhysics().
TakeMaterialsServer()
void TakeMaterialsServer (string part_name, bool repairing = false)
Definition at line 670 of file construction.c.
    {
        string main_part_name = GetConstructionPart( part_name ).GetMainPartName();
        string cfg_path = "cfgVehicles" + " " + GetParent().GetType() + " "+ "Construction" + " " + main_part_name + " " + part_name + " " + "Materials";
        if ( GetGame().ConfigIsExisting( cfg_path ) )
        {
            int child_count = GetGame().ConfigGetChildrenCount( cfg_path );
            for ( int i = 0; i < child_count; i++ )
            {
                string child_name;
                GetGame().ConfigGetChildName( cfg_path, i, child_name );
                //get type, quantity from material
                string config_path;
                string slot_name;
                config_path = cfg_path + " " + child_name + " " + "slot_name";
                GetGame().ConfigGetText( config_path, slot_name );
                config_path = cfg_path + " " + child_name + " " + "quantity";
                float quantity = GetGame().ConfigGetFloat( config_path );
                config_path = cfg_path + " " + child_name + " " + "lockable";
                bool lockable = GetGame().ConfigGetInt( config_path );
                ItemBase attachment = ItemBase.Cast( GetParent().FindAttachmentBySlotName( slot_name ) );
                if ( lockable )
                {
                    //lock attachment
                    InventoryLocation inventory_location = new InventoryLocation;
                    attachment.GetInventory().GetCurrentInventoryLocation( inventory_location );
                    GetParent().GetInventory().SetSlotLock( inventory_location.GetSlot(), true );
                }
                else
                {
                    if ( quantity > -1 )                        //0 - ignores quantity
                    {
                        if (repairing)
{
                            quantity *= REPAIR_MATERIAL_PERCENTAGE;
                            quantity = Math.Max(Math.Floor(quantity),1);
                        }
                        //subtract quantity
                        attachment.AddQuantity( -quantity );
                    }
                    else                                        //-1 - deletes the object
                    {
                        GetGame().ObjectDelete( attachment );
                    }
                }
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetFloat(), CGame::ConfigGetInt(), CGame::ConfigGetText(), ConfigIsExisting(), Math::Floor(), GetConstructionPart(), GetGame(), ConstructionPart::GetMainPartName(), GetParent(), InventoryLocation::GetSlot(), Math::Max(), CGame::ObjectDelete(), and REPAIR_MATERIAL_PERCENTAGE.
Referenced by BuildPartServer().
UpdateConstructionParts()
protected void UpdateConstructionParts ()
Definition at line 235 of file construction.c.
    {
        string construction_path = "cfgVehicles" + " " + GetParent().GetType() + " " + "Construction";
        if ( GetGame().ConfigIsExisting( construction_path ) )
        {
            //main parts
            for ( int i = 0; i < GetGame().ConfigGetChildrenCount( construction_path ); ++i )
            {
                string main_part_name;
                GetGame().ConfigGetChildName( construction_path, i, main_part_name );
                string part_path = construction_path + " " + main_part_name;
                //parts
                for ( int j = 0; j < GetGame().ConfigGetChildrenCount( part_path ); ++j )
                {
                    string part_name;
                    GetGame().ConfigGetChildName( part_path, j, part_name );
                    string name;
                    GetGame().ConfigGetTextRaw( part_path + " " + part_name + " " + "name", name );                         //name
                    GetGame().FormatRawConfigStringKeys(name);
                    bool show_on_init = GetGame().ConfigGetInt( part_path + " " + part_name + " " + "show_on_init" );       //show on init
                    int id = GetGame().ConfigGetInt( part_path + " " + part_name + " " + "id" );                            //part id
                    bool is_base = GetGame().ConfigGetInt( part_path + " " + part_name + " " + "is_base" );                 //is base (part)
                    bool is_gate = GetGame().ConfigGetInt( part_path + " " + part_name + " " + "is_gate" );                 //is gate (part)
                    m_ConstructionParts.Insert( part_name, new ConstructionPart( name, part_name, main_part_name, id, show_on_init, is_base, is_gate, GetRequiredParts(part_name,main_part_name) ) );
                    bsbDebugPrint("[bsb] Construction name=" + name + " part_name=" + part_name + " show=" + show_on_init + " base=" + is_base + " gate=" + is_gate);
                }
            }
        }
    }
References bsbDebugPrint(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetTextRaw(), ConfigIsExisting(), CGame::FormatRawConfigStringKeys(), GetGame(), GetParent(), GetRequiredParts(), m_ConstructionParts, and name.
Referenced by Init().
UpdatePhysics()
void UpdatePhysics ()
Definition at line 207 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " UpdatePhysics m_ConstructionParts=" + m_ConstructionParts.Count());
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart value = m_ConstructionParts.Get( key );
            if ( value.IsBuilt() )
            {
                bsbDebugPrint("[bsb] GetType=" + m_Parent.GetType() + " i=" + i + " ADD");
                ShowConstructionPartPhysics( value.GetPartName() );
            }
            else
            {
                bsbDebugPrint("[bsb] GetType=" + m_Parent.GetType() + " i=" + i + " RM");
                HideConstructionPartPhysics( value.GetPartName() );
            }
        }
    }
References bsbDebugPrint(), ConstructionPart::GetPartName(), HideConstructionPartPhysics(), ConstructionPart::IsBuilt(), m_ConstructionParts, m_Parent, and ShowConstructionPartPhysics().
Referenced by ItemBase::EEInit(), ItemBase::OnItemLocationChanged(), ItemBase::Refresh(), and ItemBase::RefreshPhysics().
UpdateVisuals()
void UpdateVisuals ()
Definition at line 188 of file construction.c.
    {
        bsbDebugPrint("[bsb] Construction " + Object.GetDebugName(m_Parent) + " UpdateVisuals");
        for ( int i = 0; i < m_ConstructionParts.Count(); ++i )
        {
            string key = m_ConstructionParts.GetKey( i );
            ConstructionPart value = m_ConstructionParts.Get( key );
            if ( value.IsBuilt() )
            {
                ShowConstructionPart( value.GetPartName() );
            }
            else
            {
                HideConstructionPart( value.GetPartName() );
            }
        }
    }
References bsbDebugPrint(), ConstructionPart::GetPartName(), HideConstructionPart(), ConstructionPart::IsBuilt(), m_ConstructionParts, m_Parent, and ShowConstructionPart().
Referenced by EEInit(), ItemBase::EEInit(), Plastic_Explosive::OnDisarmed(), ImprovisedExplosive::OnTriggerAttached(), Plastic_Explosive::OnTriggerAttached(), ImprovisedExplosive::OnTriggerDetached(), Plastic_Explosive::OnTriggerDetached(), ImprovisedExplosive::OnVariablesSynchronized(), Plastic_Explosive::OnVariablesSynchronized(), OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), ItemBase::Refresh(), Synchronize(), and ItemBase::Synchronize().
Variable Documentation
DECONSTURCT_MATERIAL_LOSS
const float DECONSTURCT_MATERIAL_LOSS = 0.2 static
Definition at line 14 of file construction.c.
m_AdditionalExcludes
class StaticConstructionMethods m_AdditionalExcludes
Data structure for passing parameters (extendable, modable)
Referenced by CollisionCheckData().
m_CollisionBox
protected Shape m_CollisionBox
Definition at line 19 of file construction.c.
Referenced by DestroyDebugCollisionBox(), and DrawDebugCollisionBox().
m_ConstructionBoxTrigger
protected ConstructionBoxTrigger m_ConstructionBoxTrigger
Definition at line 21 of file construction.c.
Referenced by CreateCollisionTrigger(), DestroyCollisionTrigger(), and IsTriggerColliding().
m_ConstructionParts
protected ref map<string, ref ConstructionPart> m_ConstructionParts
Definition at line 15 of file construction.c.
Referenced by Construction(), GetBaseConstructionPart(), GetConstructionPart(), GetConstructionParts(), GetConstructionPartsToBuild(), GetGateConstructionPart(), GetValidDepenentPartsArray(), HasDependentPart(), InitVisuals(), UpdateConstructionParts(), UpdatePhysics(), and UpdateVisuals().
m_Parent
protected BaseBuildingBase m_Parent
Definition at line 16 of file construction.c.
m_PartName
string m_PartName
Definition at line 1306 of file construction.c.
Referenced by CollisionCheckData().
m_PrimaryGeometry
int m_PrimaryGeometry
Definition at line 1307 of file construction.c.
Referenced by CollisionCheckData().
m_SecondaryGeometry
int m_SecondaryGeometry
Definition at line 1308 of file construction.c.
Referenced by CollisionCheckData().
REPAIR_MATERIAL_PERCENTAGE
enum ConstructionMaterialType REPAIR_MATERIAL_PERCENTAGE = 0.15
Referenced by HasMaterials(), and TakeMaterialsServer().