DayzKode: P:/scripts/4_world/DayZ/entities/scriptedentities/triggers/contaminatedtrigger.c File Reference
contaminatedtrigger.c File Reference
Classes
class EffectTrigger
Functions
void ContaminatedTrigger_Dynamic ()
override void OnEnterClientEvent (TriggerInsider insider)
override void OnVariablesSynchronized ()
void SetAreaState (int state)
Variables
class ContaminatedTrigger extends EffectTrigger m_AreaState
Function Documentation
ContaminatedTrigger_Dynamic()
void ContaminatedTrigger_Dynamic ()
Definition at line 108 of file contaminatedtrigger.c.
    {
        RegisterNetSyncVariableInt("m_AreaState");
        // Register in the trigger effect manager
        m_Manager = TriggerEffectManager.GetInstance();
        m_Manager.RegisterTriggerType( this );
    }
References TriggerEffectManager::GetInstance(), and m_Manager.
Referenced by ContaminatedArea_Dynamic::CreateTrigger(), and ContaminatedArea_Dynamic::SetDecayState().
OnEnterClientEvent()
override void OnEnterClientEvent (TriggerInsider insider)
Definition at line 123 of file contaminatedtrigger.c.
    {
        if ( insider.GetObject().IsInherited( PlayerBase ) )
        {
            PlayerBase playerInsider = PlayerBase.Cast( insider.GetObject() );
            // We will only handle the controlled player, as effects are only relevant to this player instance
            if ( playerInsider.IsControlledPlayer() )
            {
                // If it is first entrance, we fire the following
                if ( !m_Manager.IsPlayerInTriggerType( playerInsider, this ) )
                {
                    // We check if we are not in the standard LIVE state
                    bool nonDefaultState = m_AreaState > eAreaDecayStage.LIVE;
                    if ( nonDefaultState )
                    {
                        // if not we check the specific state and update local effect values
                        int localPartBirthRate;
                        if ( m_AreaState == eAreaDecayStage.DECAY_START )
                            localPartBirthRate = 20;
                        else
                            localPartBirthRate = 10;
                        playerInsider.SetContaminatedEffectEx( true, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName(), nonDefaultState, localPartBirthRate );
                    }
                    else
                        playerInsider.SetContaminatedEffectEx( true, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName() );
                }
                // We then handle the update of player trigger state in manager
                m_Manager.OnPlayerEnter( playerInsider, this );
            }
        }
    }
References TriggerInsider::GetObject(), m_AreaState, m_Manager, and m_PPERequester.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 158 of file contaminatedtrigger.c.
    {
        super.OnVariablesSynchronized();
        // Is the controlled player inside when trigger is synchronized
        for ( int i = 0; i < GetInsiders().Count(); i++ )
        {
            PlayerBase playerInsider = PlayerBase.Cast( m_insiders.Get( i ).GetObject() );
            if ( playerInsider )
            {
                if ( playerInsider.IsControlledPlayer() )
                {
                    // Update Local particle effects
                    bool nonDefaultState = m_AreaState > eAreaDecayStage.LIVE;
                    if ( nonDefaultState )
                    {
                        int localPartBirthRate;
                        if ( m_AreaState == eAreaDecayStage.DECAY_START )
                            localPartBirthRate = 20;
                        else
                            localPartBirthRate = 10;
                        // Update the local effects
                        playerInsider.SetContaminatedEffectEx( true, m_PPERequester, m_AroundPartId, m_TinyPartId, GetAmbientSoundsetName(), nonDefaultState, localPartBirthRate );
                    }
                }
            }
        }
    }
References m_AreaState, and m_PPERequester.
SetAreaState()
void SetAreaState (int state)
Definition at line 117 of file contaminatedtrigger.c.
    {
        m_AreaState = state;
        SetSynchDirty();
    }
References m_AreaState.
Variable Documentation
m_AreaState
class ContaminatedTrigger extends EffectTrigger m_AreaState
Referenced by OnEnterClientEvent(), OnVariablesSynchronized(), and SetAreaState().