DayzKode: P:/scripts/5_mission/DayZ/gui/newui/credits/elements/creditsdepartmentelement.c File Reference
creditsdepartmentelement.c File Reference
Classes
class CreditsElement
Functions
void CreditsDepartmentSection (int index, Widget parent, JsonDataCreditsSection section_data)
void LoadDataAsync (array< string > section_data)
Variables
protected ref array< Widget > m_SectionEntries = new array<Widget>
protected WrapSpacerWidget m_SectionSections
class CreditsDepartmentElement extends CreditsElement m_SectionTitle
Function Documentation
CreditsDepartmentSection()
void CreditsDepartmentSection (int index, Widget parent, JsonDataCreditsSection section_data)
Definition at line 45 of file creditsdepartmentelement.c.
    {
        m_Root              = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/credits/department_element/department_section.layout", parent );
        m_SectionTitle      = TextWidget.Cast( m_Root.FindAnyWidget( "section_title" ) );
        m_SectionSections   = WrapSpacerWidget.Cast( m_Root.FindAnyWidget( "section_elements" ) );
        if( section_data.SectionName != "" )
        {
            m_SectionTitle.SetText( section_data.SectionName );
        }
        else
        {
            m_SectionTitle.Show( false );
            m_Root.FindAnyWidget( "SeparatorPanel" ).Show( false );
        }
        LoadDataAsync( section_data.SectionLines );
        m_Root.SetSort( index );
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), CreditsElement::LoadDataAsync(), m_Root, m_SectionSections, m_SectionTitle, JsonDataCreditsSection::SectionLines, and JsonDataCreditsSection::SectionName.
Referenced by CreditsElement::LoadDataAsync().
LoadDataAsync()
void LoadDataAsync (array< string > section_data)
Definition at line 65 of file creditsdepartmentelement.c.
    {
        for( int i = 1; i <= section_data.Count(); i++ )
        {
            TextWidget w = TextWidget.Cast( GetGame().GetWorkspace().CreateWidgets( "gui/layouts/new_ui/credits/department_element/department_section_element.layout", m_SectionSections ) );
            w.SetText( section_data.Get( i - 1 ) + " \n" );
            w.Update();
            m_Root.SetSort( i );
            m_SectionEntries.Insert( w );
        }
        m_SectionSections.Update();
    }
References GetGame(), m_Root, m_SectionEntries, and m_SectionSections.
Variable Documentation
m_SectionEntries
protected ref array<Widget> m_SectionEntries = new array<Widget>
Definition at line 43 of file creditsdepartmentelement.c.
Referenced by LoadDataAsync().
m_SectionSections
protected WrapSpacerWidget m_SectionSections
Definition at line 42 of file creditsdepartmentelement.c.
Referenced by CreditsDepartmentSection(), and LoadDataAsync().
m_SectionTitle
class CreditsDepartmentElement extends CreditsElement m_SectionTitle
Referenced by CreditsDepartmentSection().