DayzKode: P:/scripts/5_mission/DayZ/gui/crosshairselector.c File Reference
crosshairselector.c File Reference
Classes
class CrossHair
Functions
void CrossHairSelector ()
protected void GetActionManager ()
protected CrossHair GetCrossHairByName (string widgetName)
protected CrossHair GetCurrentCrossHair ()
protected void GetPlayer ()
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
protected void OnWidgetScriptInit (Widget w)
protected void SelectCrossHair ()
protected void ShowCrossHair (CrossHair crossHair)
protected void Update ()
void ~CrossHairSelector ()
Variables
protected ActionManagerBase m_AM
protected ref set< ref CrossHair > m_CrossHairs
class CrossHair m_Player
protected Widget m_Root
Function Documentation
CrossHairSelector()
void CrossHairSelector ()
Definition at line 58 of file crosshairselector.c.
    {
        m_Player        = null;
        m_AM            = null;
        m_CrossHairs    = new set<ref CrossHair>;
        GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(Update);
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Insert(), m_AM, m_CrossHairs, m_Player, and Update().
GetActionManager()
protected void GetActionManager ()
Definition at line 123 of file crosshairselector.c.
    {
        if( m_Player && m_Player.IsPlayerSelected() )
        {
            Class.CastTo(m_AM, m_Player.GetActionManager());
        }
        else
            m_AM = null;
    }
References Class::CastTo(), m_AM, and m_Player.
Referenced by ManBase::AddAction(), ManBase::CanBeRestrained(), Container::CanCombineAmmo(), ManBase::CanDeleteItems(), ManBase::CloseMapEx(), ManBase::CommandHandler(), ManBase::HeadingModel(), ManBase::OnQuickBarContinuousUseEnd(), ManBase::OnQuickBarContinuousUseStart(), ManBase::OnQuickBarSingleUse(), ManBase::ReloadWeapon(), and ManBase::RemoveAction().
GetCrossHairByName()
protected CrossHair GetCrossHairByName (string widgetName)
Definition at line 133 of file crosshairselector.c.
    {
        for(int i = 0; i < m_CrossHairs.Count(); i++)
        {
            if(m_CrossHairs.Get(i).GetName() == widgetName)
                return m_CrossHairs.Get(i);
        }
        return null;
    }
References m_CrossHairs.
Referenced by SelectCrossHair().
GetCurrentCrossHair()
protected CrossHair GetCurrentCrossHair ()
Definition at line 144 of file crosshairselector.c.
    {
        for(int i = 0; i < m_CrossHairs.Count(); i++)
        {
            if(m_CrossHairs.Get(i).IsCurrent())
                return m_CrossHairs.Get(i);
        }
        return null;
    }
References m_CrossHairs.
Referenced by ShowCrossHair(), and Update().
GetPlayer()
protected void GetPlayer ()
Definition at line 118 of file crosshairselector.c.
    {
        Class.CastTo(m_Player, GetGame().GetPlayer());
    }
References Class::CastTo(), GetGame(), ScriptedWidgetEventHandler::GetPlayer(), and m_Player.
Init()
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 72 of file crosshairselector.c.
    {
        m_CrossHairs.Clear();
        Widget child = m_Root.GetChildren();
        while(child)
        {
            m_CrossHairs.Insert(CrossHair(child));
            child = child.GetSibling();
        }
    }
References m_CrossHairs, and m_Root.
OnWidgetScriptInit()
protected void OnWidgetScriptInit (Widget w)
Definition at line 84 of file crosshairselector.c.
    {
        m_Root = w;
        m_Root.SetHandler(this);
        Init();
        m_Root.Update();
    }
References ScriptedWidgetEventHandler::Init(), and m_Root.
SelectCrossHair()
protected void SelectCrossHair ()
firearms
On Continuous Actions
raised hands(bare + non-firearm) + melee cmd
handle unconscious state
default
Definition at line 155 of file crosshairselector.c.
    {
        if(!m_AM) return;
        HumanInputController hic = m_Player.GetInputController();
        ActionBase action = m_AM.GetRunningAction();
        bool firearmInHands = m_Player.GetItemInHands() && m_Player.GetItemInHands().IsWeapon();
        if ( firearmInHands && m_Player.IsRaised() && !m_Player.IsInIronsights() && !m_Player.IsInOptics() && !hic.CameraIsFreeLook() && !m_Player.GetCommand_Melee2() )
        {
            ShowCrossHair(GetCrossHairByName("crossT_128x128"));
        }
        else if (action && action.GetActionCategory() == AC_CONTINUOUS)
        {
            int actionState = m_AM.GetActionState(action);
            if ( actionState != UA_NONE )
                ShowCrossHair(null);
        }
        else if ( m_Player.IsRaised() || m_Player.GetCommand_Melee2() || GetGame().GetUIManager().GetMenu() != null )
        {
            ShowCrossHair(null);
        }
        else if ( m_Player.GetCommand_Unconscious() )
        {
            ShowCrossHair(null);
        }
        else
        {
            ShowCrossHair(GetCrossHairByName("dot"));
        }
    }
References AC_CONTINUOUS, ActionBase(), HumanInputController::CameraIsFreeLook(), ActionManagerBase::GetActionState(), GetCrossHairByName(), GetGame(), ActionManagerBase::GetRunningAction(), m_AM, m_Player, ShowCrossHair(), and UA_NONE.
Referenced by Update().
ShowCrossHair()
protected void ShowCrossHair (CrossHair crossHair)
no crosshair + clean + hide the previous
hide prev crosshair
show the new one
Definition at line 194 of file crosshairselector.c.
    {
        if(!crossHair)
        {
            if(GetCurrentCrossHair())
                GetCurrentCrossHair().Hide();
            return;
        }
        else
        {
            if(GetCurrentCrossHair() && GetCurrentCrossHair() != crossHair)
                GetCurrentCrossHair().Hide();
        }
        if(!crossHair.IsCurrent() && crossHair.IsShown())
            crossHair.Show();
    }
References GetCurrentCrossHair(), CrossHair::Hide(), CrossHair::IsCurrent(), CrossHair::IsShown(), and CrossHair::Show().
Referenced by SelectCrossHair(), and Update().
~CrossHairSelector()
void ~CrossHairSelector ()
Definition at line 67 of file crosshairselector.c.
    {
        GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Remove(Update);
    }
References CALL_CATEGORY_GUI, GetGame(), CGame::GetUpdateQueue(), ScriptInvoker::Remove(), and Update().
Variable Documentation
m_AM
protected ActionManagerBase m_AM
Definition at line 52 of file crosshairselector.c.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), ScriptedWidgetEventHandler::ContinuousActionProgress(), CrossHairSelector(), ScriptedWidgetEventHandler::GetActionManager(), GetActionManager(), ScriptedWidgetEventHandler::GetActions(), ScriptedWidgetEventHandler::GetTarget(), ScriptedWidgetEventHandler::ItemActionsWidget(), SelectCrossHair(), ScriptedWidgetEventHandler::SetActionWidget(), ScriptedWidgetEventHandler::Update(), and Update().
m_CrossHairs
protected ref set<ref CrossHair> m_CrossHairs
Definition at line 56 of file crosshairselector.c.
Referenced by CrossHairSelector(), GetCrossHairByName(), GetCurrentCrossHair(), and Init().
m_Player
class CrossHair m_Player
m_Root
protected Widget m_Root
Definition at line 54 of file crosshairselector.c.