DayzKode: P:/scripts/3_game/DayZ/dayzplayer.c File Reference
dayzplayer.c File Reference
Classes
class DayZPlayerCameraResult
class DayZPlayerTypeAttachmentSoundLookupTable
class DayZPlayerTypeStepSoundLookupTable
class SDayZPlayerAimingModel
class VegetationSound
Enumerations
enum DayZPlayerConstants {
DEBUG_MENU , DEBUG_TURNSLIDE , DEBUG_SHOWDEBUGPLUGIN , DEBUG_SHOWINJURY ,
DEBUG_SHOWEXHAUSTION , DEBUG_ENABLEJUMP , DEBUG_ENABLETALKING , STANCEIDX_ERECT ,
STANCEIDX_CROUCH , STANCEIDX_PRONE , STANCEIDX_RAISEDERECT , STANCEIDX_RAISEDCROUCH ,
STANCEIDX_RAISEDPRONE , STANCEMASK_ERECT , STANCEMASK_CROUCH , STANCEMASK_PRONE ,
STANCEMASK_RAISEDERECT , STANCEMASK_RAISEDCROUCH , STANCEMASK_RAISEDPRONE , STANCEMASK_ALL ,
STANCEMASK_NOTRAISED = STANCEMASK_ERECT | STANCEMASK_CROUCH | STANCEMASK_PRONE , STANCEMASK_RAISED = STANCEMASK_RAISEDERECT | STANCEMASK_RAISEDCROUCH | STANCEMASK_RAISEDPRONE , MOVEMENT_IDLE , MOVEMENT_WALK ,
MOVEMENT_RUN , MOVEMENT_SPRINT , ROTATION_DISABLE , ROTATION_ENABLE ,
MOVEMENTIDX_SLIDE = -2 , MOVEMENTIDX_IDLE = 0 , MOVEMENTIDX_WALK = 1 , MOVEMENTIDX_RUN = 2 ,
MOVEMENTIDX_SPRINT = 3 , MOVEMENTIDX_CROUCH_RUN = 4 , MELEE_LIGHT = 0 , MELEE_HEAVY = 1 ,
VEHICLECLASS_CAR , VEHICLECLASS_HELI , VEHICLESEAT_DRIVER , VEHICLESEAT_CODRIVER ,
VEHICLESEAT_PASSENGER_L , VEHICLESEAT_PASSENGER_R , COMMANDID_NONE , COMMANDID_MOVE ,
COMMANDID_ACTION , COMMANDID_MELEE , COMMANDID_MELEE2 , COMMANDID_FALL ,
COMMANDID_DEATH , COMMANDID_DAMAGE , COMMANDID_LADDER , COMMANDID_UNCONSCIOUS ,
COMMANDID_SWIM , COMMANDID_VEHICLE , COMMANDID_CLIMB , COMMANDID_SCRIPT ,
COMMANDID_MOD_LOOKAT , COMMANDID_MOD_WEAPONS , COMMANDID_MOD_ACTION , COMMANDID_MOD_DAMAGE ,
CMD_ACTIONINT_INTERRUPT = -2 , CMD_ACTIONINT_FINISH = -1 , CMD_ACTIONINT_END = 0 , CMD_ACTIONINT_ACTION = 1 ,
CMD_ACTIONINT_ACTIONLOOP = 2 , CMD_ACTIONMOD_DRINK = 0 , CMD_ACTIONMOD_EAT = 1 , CMD_ACTIONMOD_EMPTY_VESSEL = 2 ,
CMD_ACTIONMOD_CATCHRAIN = 3 , CMD_ACTIONMOD_VIEWCOMPASS = 7 , CMD_ACTIONMOD_ITEM_TUNE = 9 , CMD_ACTIONMOD_GIVEL = 10 ,
CMD_ACTIONMOD_GIVER = 11 , CMD_ACTIONMOD_SHAVE = 12 , CMD_ACTIONMOD_FILLMAG = 13 , CMD_ACTIONMOD_EMPTYMAG = 14 ,
CMD_ACTIONMOD_OPENITEM = 15 , CMD_ACTIONMOD_TAKETEMPSELF = 18 , CMD_ACTIONMOD_VIEWMAP = 19 , CMD_ACTIONMOD_RAISEITEM = 20 ,
CMD_ACTIONMOD_SEARCHINVENTORY = 21 , CMD_ACTIONMOD_CRAFTING = 22 , CMD_ACTIONMOD_RESTRAINEDSTRUGGLE = 23 , CMD_ACTIONMOD_COVERHEAD_SELF = 24 ,
CMD_ACTIONMOD_COVERHEAD_TARGET = 25 , CMD_ACTIONMOD_SET_ALARM = 250 , CMD_ACTIONMOD_SET_KITCHENTIMER = 252 , CMD_ACTIONMOD_RESET_KITCHENTIMER = 253 ,
CMD_ACTIONMOD_PICKUP_HANDS = 500 , CMD_ACTIONMOD_PICKUP_INVENTORY = 501 , CMD_ACTIONMOD_LICKBATTERY = 502 , CMD_ACTIONMOD_LIGHTFLARE = 503 ,
CMD_ACTIONMOD_LITCHEMLIGHT = 504 , CMD_ACTIONMOD_UNPINGRENAGE = 505 , CMD_ACTIONMOD_OPENDOORFW = 506 , CMD_ACTIONMOD_OPENLID = 507 ,
CMD_ACTIONMOD_CLOSELID = 508 , CMD_ACTIONMOD_ITEM_ON = 509 , CMD_ACTIONMOD_ITEM_OFF = 510 , CMD_ACTIONMOD_BATONEXTEND = 511 ,
CMD_ACTIONMOD_BATONRETRACT = 512 , CMD_ACTIONMOD_UNLOCKHANDCUFFTARGET = 513 , CMD_ACTIONMOD_FISHINGRODEXTEND = 514 , CMD_ACTIONMOD_FISHINGRODRETRACT = 515 ,
CMD_ACTIONMOD_CLEANHANDSBOTTLE = 516 , CMD_ACTIONMOD_OPENITEM_ONCE = 517 , CMD_ACTIONMOD_ATTACHSCOPE = 518 , CMD_ACTIONMOD_ATTACHBARREL = 519 ,
CMD_ACTIONMOD_EMPTYSEEDSPACK = 520 , CMD_ACTIONMOD_INTERACTONCE = 521 , CMD_ACTIONMOD_ATTACHITEM = 522 , CMD_ACTIONMOD_CLOSEITEM_ONCE = 523 ,
CMD_ACTIONMOD_FOLDITEM_ONCE = 524 , CMD_ACTIONMOD_UNFOLDITEM_ONCE = 525 , CMD_ACTIONMOD_PRESS_TRIGGER = 526 , CMD_ACTIONMOD_STOP_ALARM = 251 ,
CMD_ACTIONMOD_DROPITEM_HANDS = 900 , CMD_ACTIONMOD_DROPITEM_INVENTORY = 901 , CMD_ACTIONFB_DRINK = 0 , CMD_ACTIONFB_EAT = 1 ,
CMD_ACTIONFB_CATCHRAIN = 3 , CMD_ACTIONFB_ITEM_TUNE = 9 , CMD_ACTIONFB_GIVEL = 10 , CMD_ACTIONFB_GIVER = 11 ,
CMD_ACTIONFB_FILLMAG = 13 , CMD_ACTIONFB_EMPTYMAG = 14 , CMD_ACTIONFB_DRINKPOND = 50 , CMD_ACTIONFB_DRINKWELL = 51 ,
CMD_ACTIONFB_FILLBOTTLEWELL = 52 , CMD_ACTIONFB_FIREESTINGUISHER = 53 , CMD_ACTIONFB_WRING = 54 , CMD_ACTIONFB_FISHING = 56 ,
CMD_ACTIONFB_CPR = 57 , CMD_ACTIONFB_BANDAGE = 58 , CMD_ACTIONFB_CRAFTING = 59 , CMD_ACTIONFB_INTERACT = 60 ,
CMD_ACTIONFB_FORCEFEED = 62 , CMD_ACTIONFB_BANDAGETARGET = 63 , CMD_ACTIONFB_SPRAYPLANT = 64 , CMD_ACTIONFB_STARTFIRE = 65 ,
CMD_ACTIONFB_ANIMALSKINNING = 66 , CMD_ACTIONFB_WASHHANDSWELL = 67 , CMD_ACTIONFB_WASHHANDSPOND = 68 , CMD_ACTIONFB_SALINEBLOODBAGTARGET = 69 ,
CMD_ACTIONFB_SALINEBLOODBAG = 70 , CMD_ACTIONFB_STITCHUPSELF = 71 , CMD_ACTIONFB_VOMIT = 72 , CMD_ACTIONFB_UNRESTRAINTARGET = 73 ,
CMD_ACTIONFB_RESTRAINTARGET = 74 , CMD_ACTIONFB_CHECKPULSE = 76 , CMD_ACTIONFB_CLEANWOUNDSTARGET = 78 , CMD_ACTIONFB_COLLECTBLOODSELF = 81 ,
CMD_ACTIONFB_EMPTY_VESSEL = 82 , CMD_ACTIONFB_OPENITEM = 83 , CMD_ACTIONFB_HACKBUSH = 85 , CMD_ACTIONFB_HACKTREE = 86 ,
CMD_ACTIONFB_TAKETEMPSELF = 87 , CMD_ACTIONFB_DIG = 88 , CMD_ACTIONFB_DIGUPCACHE = 89 , CMD_ACTIONFB_DIGMANIPULATE = 90 ,
CMD_ACTIONFB_DEPLOY_HEAVY = 95 , CMD_ACTIONFB_DEPLOY_2HD = 96 , CMD_ACTIONFB_DEPLOY_1HD = 97 , CMD_ACTIONFB_BLOWFIREPLACE = 98 ,
CMD_ACTIONFB_VIEWMAP = 99 , CMD_ACTIONFB_VIEWCOMPASS = 100 , CMD_ACTIONFB_FILLBOTTLEPOND = 101 , CMD_ACTIONFB_PLACING_HEAVY = 102 ,
CMD_ACTIONFB_PLACING_2HD = 103 , CMD_ACTIONFB_PLACING_1HD = 104 , CMD_ACTIONFB_CUTBARK = 105 , CMD_ACTIONFB_VIEWNOTE = 106 ,
CMD_ACTIONFB_SEARCHINVENTORY = 107 , CMD_GESTUREFB_LOOKOPTICS = 108 , CMD_ACTIONFB_MINEROCK = 109 , CMD_ACTIONFB_RAISEITEM = 110 ,
CMD_ACTIONFB_RESTRAINEDSTRUGGLE = 111 , CMD_ACTIONFB_RESTRAINSELF = 112 , CMD_ACTIONFB_ASSEMBLE = 113 , CMD_ACTIONFB_DISASSEMBLE = 114 ,
CMD_ACTIONFB_FLAME_REPAIR = 115 , CMD_ACTIONFB_TURN_VALVE = 116 , CMD_ACTIONFB_SET_ALARM = 250 , CMD_ACTIONFB_PICKUP_HANDS = 500 ,
CMD_ACTIONFB_PICKUP_INVENTORY = 501 , CMD_ACTIONFB_LICKBATTERY = 502 , CMD_ACTIONFB_LIGHTFLARE = 503 , CMD_ACTIONFB_LITCHEMLIGHT = 504 ,
CMD_ACTIONFB_UNPINGRENAGE = 505 , CMD_ACTIONFB_ITEM_ON = 506 , CMD_ACTIONFB_ITEM_OFF = 507 , CMD_ACTIONFB_HANDCUFFTARGET = 508 ,
CMD_ACTIONFB_MORPHINE = 509 , CMD_ACTIONFB_INJECTION = 510 , CMD_ACTIONFB_INJECTIONTARGET = 511 , CMD_ACTIONFB_DRINKSIP = 512 ,
CMD_ACTIONFB_CLEANHANDSBOTTLE = 513 , CMD_ACTIONFB_OPENITEM_ONCE = 514 , CMD_ACTIONFB_POKE = 515 , CMD_ACTIONFB_ATTACHSCOPE = 516 ,
CMD_ACTIONFB_ATTACHBARREL = 517 , CMD_ACTIONFB_RESTRAIN = 518 , CMD_ACTIONFB_PICKUP_HEAVY = 519 , CMD_ACTIONFB_PRESS_TRIGGER = 526 ,
CMD_ACTIONFB_RAISE_FLAG = 600 , CMD_ACTIONFB_LOWER_FLAG = 601 , CMD_ACTIONFB_STOP_ALARM = 251 , CMD_ACTIONFB_DROPITEM_HANDS = 900 ,
CMD_ACTIONMOD_STARTENGINE = 300 , CMD_ACTIONMOD_TOOTHORN = 301 , CMD_ACTIONMOD_DRIVER_DOOR_OPEN = 400 , CMD_ACTIONMOD_DRIVER_DOOR_CLOSE = 401 ,
CMD_ACTIONMOD_CODRIVER_DOOROPEN = 402 , CMD_ACTIONMOD_CODRIVER_DOORCLOSE = 403 , CMD_ACTIONMOD_STOPENGINE = 404 , CMD_ACTIONMOD_SHIFTGEAR = 405 ,
CMD_ACTIONMOD_HEADLIGHT = 406 , CMD_GESTUREMOD_GREETING = 1000 , CMD_GESTUREMOD_POINT = 1001 , CMD_GESTUREMOD_THUMB = 1002 ,
CMD_GESTUREMOD_THUMBDOWN = 1003 , CMD_GESTUREMOD_SILENCE = 1004 , CMD_GESTUREMOD_TAUNT = 1005 , CMD_GESTUREMOD_TIMEOUT = 1006 ,
CMD_GESTUREMOD_HEART = 1007 , CMD_GESTUREMOD_FACEPALM = 1008 , CMD_GESTUREMOD_WATCHING = 1009 , CMD_GESTUREMOD_HOLD = 1010 ,
CMD_GESTUREMOD_LISTENING = 1011 , CMD_GESTUREMOD_POINTSELF = 1012 , CMD_GESTUREMOD_LOOKATME = 1013 , CMD_GESTUREMOD_OKAY = 1014 ,
CMD_GESTUREMOD_RPS = 10000 , CMD_ACTIONINT_RPS_ROCK = 10 , CMD_ACTIONINT_RPS_PAPER = 11 , CMD_ACTIONINT_RPS_SCISSORS = 12 ,
CMD_GESTUREMOD_THROAT = 1100 , CMD_GESTUREMOD_CLAP = 1101 , CMD_GESTUREMOD_DABBING = 1102 , CMD_GESTUREMOD_MOVE = 1103 ,
CMD_GESTUREMOD_DOWN = 1104 , CMD_GESTUREMOD_COME = 1105 , CMD_GESTUREMOD_TAUNTKISS = 1106 , CMD_GESTUREMOD_TAUNTELBOW = 1107 ,
CMD_GESTUREMOD_TAUNTTHINK = 1108 , CMD_GESTUREMOD_NODHEAD = 1109 , CMD_GESTUREMOD_SHAKEHEAD = 1110 , CMD_GESTUREMOD_SHRUG = 1111 ,
CMD_GESTUREMOD_SURRENDER = 1112 , CMD_GESTUREMOD_SURRENDERIN = 1112 , CMD_GESTUREMOD_SURRENDEROUT = 1113 , CMD_GESTUREFB_GREETING = 1000 ,
CMD_GESTUREFB_POINT = 1001 , CMD_GESTUREFB_THUMB = 1002 , CMD_GESTUREFB_THUMBDOWN = 1003 , CMD_GESTUREFB_SILENCE = 1004 ,
CMD_GESTUREFB_TAUNT = 1005 , CMD_GESTUREFB_TIMEOUT = 1006 , CMD_GESTUREFB_HEART = 1007 , CMD_GESTUREFB_WATCHING = 1009 ,
CMD_GESTUREFB_HOLD = 1010 , CMD_GESTUREFB_LISTENING = 1011 , CMD_GESTUREFB_POINTSELF = 1012 , CMD_GESTUREFB_LOOKATME = 1013 ,
CMD_GESTUREFB_OKAY = 1014 , CMD_GESTUREFB_SALUTE = 1050 , CMD_GESTUREFB_CAMPFIRE = 1051 , CMD_GESTUREFB_LYINGDOWN = 1052 ,
CMD_GESTUREFB_SOS = 1053 , CMD_GESTUREFB_SITA = 1054 , CMD_GESTUREFB_SITB = 1055 , CMD_GESTUREFB_DABBING = 1056 ,
CMD_GESTUREFB_KNEEL = 1057 , CMD_GESTUREFB_THROAT = 1100 , CMD_GESTUREFB_MOVE = 1103 , CMD_GESTUREFB_DOWN = 1104 ,
CMD_GESTUREFB_COME = 1105 , CMD_GESTUREFB_TAUNTKISS = 1106 , CMD_GESTUREFB_TAUNTTHINK = 1108 , CMD_GESTUREFB_DANCE = 1109 ,
CMD_GESTUREFB_NODHEAD = 1110 , CMD_GESTUREFB_SHAKEHEAD = 1111 , CMD_GESTUREFB_SHRUG = 1112 , CMD_GESTUREFB_SURRENDER = 1113 ,
CMD_GESTUREFB_SURRENDERIN = 1113 , CMD_GESTUREFB_SURRENDEROUT = 1114 , CMD_TRAILER_WAKE_UP = 3000 , CMD_TRAILER_DEAD_BODY = 3001 ,
CMD_TRAILER_WALKIE_TALKIE = 3002 , CMD_TRAILER_WOUNDED = 3003 , CMD_TRAILER_WALK_AWAY = 3004 , CMD_TRAILER_DEAD = 3005 ,
CMD_SUICIDEFB_1HD = 2000 , CMD_SUICIDEFB_FIREAXE = 2001 , CMD_SUICIDEFB_PITCHFORK = 2002 , CMD_SUICIDEFB_PISTOL = 2003 ,
CMD_SUICIDEFB_RIFLE = 2004 , CMD_SUICIDEFB_SWORD = 2005 , CMD_SUICIDEFB_UNARMED = 2006 , CMD_SUICIDEFB_WOODAXE = 2007 ,
CMD_SUICIDEFB_SPEAR = 2008 , CMD_SUICIDEFB_SICKLE = 2009 , CMD_SUICIDEFB_HOE = 2010
}
defined in C++
enum DayZPlayerInstanceType {
INSTANCETYPE_SERVER , INSTANCETYPE_CLIENT , INSTANCETYPE_REMOTE , INSTANCETYPE_AI_SERVER ,
INSTANCETYPE_AI_REMOTE , INSTANCETYPE_AI_SINGLEPLAYER
}
defined in C++
Functions
proto native int AddItemBoneRemap (string pItemClass, array< string > pBoneRemap)
proto native int AddItemInHandsProfile (string pItemClass, string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg)
VKOSTIK: DO NOT FORGET !!! HumanItemBehaviorCfg.m_iPerItemCameraUD - per item camera user data - enables you setup different cameras for different items in hands.
proto native int AddItemInHandsProfileIK (string pItemClass, string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg, string pIkPoseAnim, string pWeaponStates="")
bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
-------------— aiming model ----------------------—
proto native void AnimCallCommand (int pCommand, int pParamInt, float pParamFloat)
-------------— animation graph functions ----------------------—
proto native void AnimSetBool (int pVar, bool pBool)
proto native void AnimSetFloat (int pVar, float pFlt)
proto native void AnimSetInt (int pVar, int pInt)
int CameraHandler (int pCameraMode)
-------------— camera handling ----------------------—
bool CanFreeLook ()
this overrides freelok for cameras
proto native SHumanCommandClimbSettings CommandClimbSettingsW ()
void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
-------------— command handling ----------------------—
proto native SHumanCommandMoveSettings CommandMoveSettingsW ()
proto native SHumanCommandSwimSettings CommandSwimSettingsW ()
class DayZPlayerCameraResult DayZPlayerCamera (DayZPlayer pPlayer, HumanInputController pInput)
private void DayZPlayerCameraResult ()
cannot be instanced from script (always created from C++)
private void DayZPlayerType ()
proto native void DebugPreloadAnimationInstances ()
debug / hack - loads all animation instances
proto native bool DebugSyncShadowSetup (DayZPlayer pPlayer)
-------------— sync shadow ----------------------—
void ForceStandUpForHeavyItems (notnull EntityAI item)
-------------— Forces player to stand up when swapping to heavy item ----------------------—
void ForceStandUpForHeavyItemsSwap (notnull EntityAI item1, notnull EntityAI item2)
TIntArray GetAnimEventIds ()
DayZPlayerTypeAttachmentSoundLookupTable GetAttachmentSoundLookupTable ()
vector GetBaseAngles ()
string GetCameraName ()
proto native DayZPlayerCamera GetCurrentCamera ()
-------------— camera additional functions ----------------------—
proto native void GetCurrentCameraTransform (out vector position, out vector direction, out vector rotation)
gets transform of current player camera
proto native int GetCurrentPerItemCameraUD ()
gets current camera
float GetCurrentPitch ()
proto native DayZPlayerType GetDayZPlayerType ()
returns appropriate DayZPlayerType
string GetDefaultHitComponent ()
string GetDefaultHitPositionComponent ()
proto native SHumanGlobalSettings GetGlobalSettingsW ()
returns Human global settings for DayZPlayer
proto native int GetHeadBoneIdx ()
string GetHitComponentForAI ()
proto native DayZPlayerInstanceType GetInstanceType ()
proto native MeleeCombatData GetMeleeCombatData ()
processes melee hit
NoiseParams GetNoiseParams (int eventId)
NoiseParams GetNoiseParamsCrouch ()
NoiseParams GetNoiseParamsLandHeavy ()
NoiseParams GetNoiseParamsLandLight ()
NoiseParams GetNoiseParamsProne ()
NoiseParams GetNoiseParamsShout ()
NoiseParams GetNoiseParamsStand ()
NoiseParams GetNoiseParamsTalk ()
NoiseParams GetNoiseParamsWhisper ()
class DayZPlayerTypeStepSoundLookupTable GetSoundBuilder (int eventId, int parameterHash)
SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
SoundObjectBuilder GetSoundBuilder (int eventId, string slotName, int attachmentHash)
class DayZPlayerTypeAttachmentSoundLookupTable GetSoundEvent (int event_id)
SoundObjectBuilder GetSoundObjectBuilder ()
DayZPlayerTypeAnimTable GetSoundTable ()
AnimSoundEvent GetSoundWeaponEvent (int event_id)
DayZPlayerTypeStepSoundLookupTable GetStepSoundLookupTable ()
array< string > GetSuitableFinisherHitComponents ()
array< ref VegetationSound > GetVegetationSounds ()
DayZPlayerTypeVoiceSoundLookupTable GetVoiceSoundLookupTable ()
bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
bool IsCamera3rdRaised ()
proto native bool IsCameraBlending ()
bool IsEyeZoom ()
returns true if player is using EyeZoom, otherwise false
bool IsHoldingBreath ()
return true if player is trying to hold breah, otherwise false
bool IsInThirdPerson ()
return true if player is currently in 3pp, otherwise false
bool IsPerformingFBGesture ()
return true if player is currently performing FB gesture, otherwise false
bool IsPlayerInStance (int pStanceMask)
-------------— camera additiona functions ----------------------—
proto native float IsPlayerSpeaking ()
-------------— speaking anim ----------------------—
bool IsShootingFromCamera ()
return true if shots are fired from camere, otherwise false
void LoadSoundWeaponEvent ()
void LoadVegetationSounds ()
void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
virtual callback - called when camera is created
void OnInputForRemote (ParamsReadContext ctx)
void OnInputFromServer (ParamsReadContext ctx)
void OnThrowingModeChange (bool change_to_enabled)
void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
virtual callback - called each frame
proto native void ProcessMeleeHit (InventoryItem pMeleeWeapon, int pMeleeModeIndex, Object pTarget, int pComponentIndex, vector pHitWorldPos)
processes melee hit (uses component index)
proto native void ProcessMeleeHitName (InventoryItem pMeleeWeapon, int pMeleeModeIndex, Object pTarget, string pComponentName, vector pHitWorldPos)
processes melee hit (uses component name)
proto native int Random ()
-------------— deterministic random numbers ---------------------—
proto native float Random01 ()
Random number in range of <0,1> - !!! use this only during deterministic simulation (CommandHandler)
proto native float RandomRange (int pRange)
Random number in range of <0,pRange-1> - !!! use this only during deterministic simulation (CommandHandler)
void RegisterAttachmentSoundLookupTable (DayZPlayerTypeAttachmentSoundLookupTable pASLUT)
proto native void RegisterCameraCreator (int pCameraID, typename pCameraType)
registers camera creator - camera type => camera type (must be descendant of DayZPlayerCamera)
proto native void RegisterCameraOnChangeFn (Class pInstance, string pFnName)
registers camera on change function -
proto native void RegisterCameraOnChangeFnStatic (typename pClass, string pFnName)
registers camera on change function - static function
void RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
proto native void RegisterParticleEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnParticleEvent();
proto native void RegisterSoundEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnSoundEvent();
void RegisterSoundTable (DayZPlayerTypeAnimTable pST)
proto native void RegisterStepEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnStepEvent();
void RegisterStepSoundLookupTable (DayZPlayerTypeStepSoundLookupTable pSSLUT)
void RegisterVoiceSoundLookupTable (DayZPlayerTypeVoiceSoundLookupTable pASLUT)
proto native void ReleaseNetworkControls ()
-------------— release controls ----------------------—
proto native void ResetCameraCreators ()
resets camera creators
proto native void ResetItemInHandsProfiles ()
reset profiles
private void SDayZPlayerHeadingModel ()
cannot be created from script
void SendRecoilOffsetZ (float offset)
m_fCamPosOffsetZ info, used to adjust near plane in DayZPlayerCameraIronsights now
proto native void SendSyncJuncture (int pJunctureID, ParamsWriteContext ctx)
-------------— sync stuff ----------------------—
proto native void SetAimLimits (float pDown, float pUp, float pLeft, float pRight)
sets aim limits for a player
proto native void SetCameraShootParams (float pRayDistance, float pRayRadius, float pMaxAngleCos)
sets aim limits for a player
class VegetationSound SetDefaultItemInHandsProfile (string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg)
proto native void SetLookLimits (float pDown, float pUp, float pLeft, float pRight)
sets look limits for a player
proto native void SetVerticalMinimumAimLimit (float value)
sets vertical minimum aim limit for a player
void SpawnCameraShake (float strength=1, float radius=2, float smoothness=5, float radius_decay_speed=6)
void SpawnCameraShakeProper (float strength, float radius, float smoothness, float radius_decay_speed)
proto native void StoreInputForRemotes (ParamsWriteContext ctx)
void UpdateDummyPlayerProxyVisibility (EntityAI shoulder, EntityAI melee)
void VegetationSound (SoundObjectBuilder soundObjectBuilder, TIntArray animEventIds)
private void ~DayZPlayerCameraResult ()
cannot be instanced from script (always created from C++)
private void ~DayZPlayerType ()
private void ~SDayZPlayerHeadingModel ()
Variables
private ref TIntArray m_AnimEventIds
ref array< ref AnimSoundEvent > m_animSoundEventsAttack
bool m_bUpdateWhenBlendOut
true - camera is updated when blending to new camera (Ironsights == false)
vector m_CameraTM [4]
transformation matrix - pos + orient of the camera
IEntity m_CollisionIgnoreEntity
ignore entity in 3rd person camera collision solver
protected string m_DefaultHitComponent
protected string m_DefaultHitPositionComponent
float m_fDistance
camera distance (external cameras only)
float m_fFovAbsolute
fov absolute value override - -1.0 default, if set - overrides absolute fov setting
float m_fFovMultiplier
fov multiplier - 1.0 default - used for modifying fov -
float m_fHeadingAngle
float m_fIgnoreParentPitch
1 - resets base transforms pitch
float m_fIgnoreParentRoll
1 - resets base transforms roll
float m_fIgnoreParentYaw
1 - resets base transforms yaw
float m_fInsideCamera
0 not used, 1 - pos, 2 - rot, 3 - pos+rot applied as a parent to m_CameraTM, 4 as 3 but cam aligned with Y
float m_fNearPlane
nearplane distance
float m_fOrientationAngle
float m_fPositionModelSpace
0.0 position is in heading space, 1.0 position is in model space
float m_fShootFromCamera
1(default) - uses shoot from camera (+aiming sway), 0 pure weapon shoot (ironsights == 0)
float m_fUseHeading
0..1 (0 uses direct dir returned, 1 uses heading from player)
protected ref array< ref DayZAIHitComponent > m_HitComponentsForAI
Melee hit components (AI targeting)
enum DayZPlayerInstanceType m_iCamMode
int m_iCurrentCommandID
int m_iDirectBone
-1 no bone, >= 0 - bone index camera is bound to, m_CameraTM is offset to the bone
int m_iDirectBoneMode
ref DayZPlayerTypeAttachmentSoundLookupTable m_pAttachmentSoundLookupTable
protected HumanInputController m_pInput
human input
ref NoiseParams m_pNoiseLandHeavy
ref NoiseParams m_pNoiseLandLight
ref NoiseParams m_pNoiseShout
ref NoiseParams m_pNoiseStepCrouch
ref NoiseParams m_pNoiseStepProne
ref NoiseParams m_pNoiseStepStand
ref NoiseParams m_pNoiseTalk
ref NoiseParams m_pNoiseWhisper
protected DayZPlayer m_pPlayer
data
ref DayZPlayerTypeAnimTable m_pSoundTable
ref DayZPlayerTypeStepSoundLookupTable m_pStepSoundLookupTable
ref array< ref VegetationSound > m_pVegetationSounds
ref DayZPlayerTypeVoiceSoundLookupTable m_pVoiceSoundLookupTable
private ref SoundObjectBuilder m_SoundObjectBuilder
protected ref array< string > m_SuitableFinisherHitComponents
enum DayZPlayerConstants SetDefaultItemInHandsProfile
const int SIMPLE_SELECTION_MELEE_MELEE = 1
class SDayZPlayerAimingModel SIMPLE_SELECTION_MELEE_RIFLE = 0
const int SIMPLE_SELECTION_SHOULDER_MELEE = 3
const int SIMPLE_SELECTION_SHOULDER_RIFLE = 2
Detailed Description
this file is interface DayZPlayer classes
Definition in file dayzplayer.c.
Enumeration Type Documentation
DayZPlayerConstants
enum DayZPlayerConstants
defined in C++
Enumerator
DEBUG_MENU
dayz player debug menu in enfusion
------------------- movement stances --------------
DEBUG_TURNSLIDE
over turn slides / clamps
DEBUG_SHOWDEBUGPLUGIN
menu for showing debug plugin
DEBUG_SHOWINJURY
menu for showing injuries
DEBUG_SHOWEXHAUSTION
menu for showing exhaustion
DEBUG_ENABLEJUMP
menu for showing exhaustion
DEBUG_ENABLETALKING
option for showing talk command
STANCEIDX_ERECT
------------------- movement stances --------------
STANCEIDX_CROUCH
STANCEIDX_PRONE
STANCEIDX_RAISEDERECT
STANCEIDX_RAISEDCROUCH
STANCEIDX_RAISEDPRONE
STANCEMASK_ERECT
stance masks
STANCEMASK_CROUCH
STANCEMASK_PRONE
STANCEMASK_RAISEDERECT
STANCEMASK_RAISEDCROUCH
STANCEMASK_RAISEDPRONE
STANCEMASK_ALL
STANCEMASK_NOTRAISED
STANCEMASK_RAISED
MOVEMENT_IDLE
movements - masks
MOVEMENT_WALK
0x1
MOVEMENT_RUN
0x2
MOVEMENT_SPRINT
0x4
ROTATION_DISABLE
0x8
rotation modes
ROTATION_ENABLE
MOVEMENTIDX_SLIDE
movement idx
MOVEMENTIDX_IDLE
MOVEMENTIDX_WALK
MOVEMENTIDX_RUN
MOVEMENTIDX_SPRINT
MOVEMENTIDX_CROUCH_RUN
MELEE_LIGHT
melee hit type
MELEE_HEAVY
VEHICLECLASS_CAR
vehicle classes
VEHICLECLASS_HELI
VEHICLESEAT_DRIVER
vehicle seats
VEHICLESEAT_CODRIVER
VEHICLESEAT_PASSENGER_L
VEHICLESEAT_PASSENGER_R
COMMANDID_NONE
command ids - main movement commands
------------------- COMMAND IDs -------------------
COMMANDID_MOVE
COMMANDID_ACTION
COMMANDID_MELEE
COMMANDID_MELEE2
COMMANDID_FALL
COMMANDID_DEATH
COMMANDID_DAMAGE
COMMANDID_LADDER
COMMANDID_UNCONSCIOUS
COMMANDID_SWIM
COMMANDID_VEHICLE
COMMANDID_CLIMB
COMMANDID_SCRIPT
COMMANDID_MOD_LOOKAT
modifier commands - additive behaviour
COMMANDID_MOD_WEAPONS
COMMANDID_MOD_ACTION
COMMANDID_MOD_DAMAGE
CMD_ACTIONINT_INTERRUPT
internal action commands used in HumanCommandActionCallback.InternalCommand()
------------------- ACTIONS -----------------------
totally interrupt action (no animation, just blend)
CMD_ACTIONINT_FINISH
secondary ending (finishing action, eg running out of water while drinking, not all actions have this)
CMD_ACTIONINT_END
end action (stopping action, without finish, all actions have this)
CMD_ACTIONINT_ACTION
one time secondary action within an action
CMD_ACTIONINT_ACTIONLOOP
loop secondary action within an action
CMD_ACTIONMOD_DRINK
animations constants
note: (erc - standing, cro - crouching, pne - prone) anim pose it can start from note: (end, end2, action, loop2) internal command which can be send in loop state
looping
modifier (differential animation)
CMD_ACTIONMOD_EAT
CMD_ACTIONMOD_EMPTY_VESSEL
CMD_ACTIONMOD_CATCHRAIN
CMD_ACTIONMOD_VIEWCOMPASS
CMD_ACTIONMOD_ITEM_TUNE
CMD_ACTIONMOD_GIVEL
CMD_ACTIONMOD_GIVER
CMD_ACTIONMOD_SHAVE
CMD_ACTIONMOD_FILLMAG
CMD_ACTIONMOD_EMPTYMAG
CMD_ACTIONMOD_OPENITEM
CMD_ACTIONMOD_TAKETEMPSELF
CMD_ACTIONMOD_VIEWMAP
CMD_ACTIONMOD_RAISEITEM
CMD_ACTIONMOD_SEARCHINVENTORY
CMD_ACTIONMOD_CRAFTING
CMD_ACTIONMOD_RESTRAINEDSTRUGGLE
CMD_ACTIONMOD_COVERHEAD_SELF
CMD_ACTIONMOD_COVERHEAD_TARGET
CMD_ACTIONMOD_SET_ALARM
CMD_ACTIONMOD_SET_KITCHENTIMER
CMD_ACTIONMOD_RESET_KITCHENTIMER
CMD_ACTIONMOD_PICKUP_HANDS
CMD_ACTIONMOD_PICKUP_INVENTORY
CMD_ACTIONMOD_LICKBATTERY
CMD_ACTIONMOD_LIGHTFLARE
CMD_ACTIONMOD_LITCHEMLIGHT
CMD_ACTIONMOD_UNPINGRENAGE
CMD_ACTIONMOD_OPENDOORFW
CMD_ACTIONMOD_OPENLID
CMD_ACTIONMOD_CLOSELID
CMD_ACTIONMOD_ITEM_ON
CMD_ACTIONMOD_ITEM_OFF
CMD_ACTIONMOD_BATONEXTEND
CMD_ACTIONMOD_BATONRETRACT
CMD_ACTIONMOD_UNLOCKHANDCUFFTARGET
CMD_ACTIONMOD_FISHINGRODEXTEND
CMD_ACTIONMOD_FISHINGRODRETRACT
CMD_ACTIONMOD_CLEANHANDSBOTTLE
CMD_ACTIONMOD_OPENITEM_ONCE
CMD_ACTIONMOD_ATTACHSCOPE
CMD_ACTIONMOD_ATTACHBARREL
CMD_ACTIONMOD_EMPTYSEEDSPACK
CMD_ACTIONMOD_INTERACTONCE
CMD_ACTIONMOD_ATTACHITEM
CMD_ACTIONMOD_CLOSEITEM_ONCE
CMD_ACTIONMOD_FOLDITEM_ONCE
CMD_ACTIONMOD_UNFOLDITEM_ONCE
CMD_ACTIONMOD_PRESS_TRIGGER
CMD_ACTIONMOD_STOP_ALARM
CMD_ACTIONMOD_DROPITEM_HANDS
CMD_ACTIONMOD_DROPITEM_INVENTORY
CMD_ACTIONFB_DRINK
fb (full body)
CMD_ACTIONFB_EAT
CMD_ACTIONFB_CATCHRAIN
CMD_ACTIONFB_ITEM_TUNE
CMD_ACTIONFB_GIVEL
CMD_ACTIONFB_GIVER
CMD_ACTIONFB_FILLMAG
CMD_ACTIONFB_EMPTYMAG
CMD_ACTIONFB_DRINKPOND
CMD_ACTIONFB_DRINKWELL
CMD_ACTIONFB_FILLBOTTLEWELL
CMD_ACTIONFB_FIREESTINGUISHER
CMD_ACTIONFB_WRING
CMD_ACTIONFB_FISHING
CMD_ACTIONFB_CPR
CMD_ACTIONFB_BANDAGE
CMD_ACTIONFB_CRAFTING
CMD_ACTIONFB_INTERACT
CMD_ACTIONFB_FORCEFEED
CMD_ACTIONFB_BANDAGETARGET
CMD_ACTIONFB_SPRAYPLANT
CMD_ACTIONFB_STARTFIRE
CMD_ACTIONFB_ANIMALSKINNING
CMD_ACTIONFB_WASHHANDSWELL
CMD_ACTIONFB_WASHHANDSPOND
CMD_ACTIONFB_SALINEBLOODBAGTARGET
CMD_ACTIONFB_SALINEBLOODBAG
CMD_ACTIONFB_STITCHUPSELF
CMD_ACTIONFB_VOMIT
CMD_ACTIONFB_UNRESTRAINTARGET
CMD_ACTIONFB_RESTRAINTARGET
CMD_ACTIONFB_CHECKPULSE
CMD_ACTIONFB_CLEANWOUNDSTARGET
CMD_ACTIONFB_COLLECTBLOODSELF
CMD_ACTIONFB_EMPTY_VESSEL
CMD_ACTIONFB_OPENITEM
CMD_ACTIONFB_HACKBUSH
CMD_ACTIONFB_HACKTREE
CMD_ACTIONFB_TAKETEMPSELF
CMD_ACTIONFB_DIG
CMD_ACTIONFB_DIGUPCACHE
CMD_ACTIONFB_DIGMANIPULATE
CMD_ACTIONFB_DEPLOY_HEAVY
CMD_ACTIONFB_DEPLOY_2HD
CMD_ACTIONFB_DEPLOY_1HD
CMD_ACTIONFB_BLOWFIREPLACE
CMD_ACTIONFB_VIEWMAP
CMD_ACTIONFB_VIEWCOMPASS
CMD_ACTIONFB_FILLBOTTLEPOND
CMD_ACTIONFB_PLACING_HEAVY
CMD_ACTIONFB_PLACING_2HD
CMD_ACTIONFB_PLACING_1HD
CMD_ACTIONFB_CUTBARK
CMD_ACTIONFB_VIEWNOTE
CMD_ACTIONFB_SEARCHINVENTORY
CMD_GESTUREFB_LOOKOPTICS
CMD_ACTIONFB_MINEROCK
CMD_ACTIONFB_RAISEITEM
CMD_ACTIONFB_RESTRAINEDSTRUGGLE
CMD_ACTIONFB_RESTRAINSELF
CMD_ACTIONFB_ASSEMBLE
CMD_ACTIONFB_DISASSEMBLE
CMD_ACTIONFB_FLAME_REPAIR
CMD_ACTIONFB_TURN_VALVE
CMD_ACTIONFB_SET_ALARM
CMD_ACTIONFB_PICKUP_HANDS
CMD_ACTIONFB_PICKUP_INVENTORY
CMD_ACTIONFB_LICKBATTERY
CMD_ACTIONFB_LIGHTFLARE
CMD_ACTIONFB_LITCHEMLIGHT
CMD_ACTIONFB_UNPINGRENAGE
CMD_ACTIONFB_ITEM_ON
CMD_ACTIONFB_ITEM_OFF
CMD_ACTIONFB_HANDCUFFTARGET
CMD_ACTIONFB_MORPHINE
CMD_ACTIONFB_INJECTION
CMD_ACTIONFB_INJECTIONTARGET
CMD_ACTIONFB_DRINKSIP
CMD_ACTIONFB_CLEANHANDSBOTTLE
CMD_ACTIONFB_OPENITEM_ONCE
CMD_ACTIONFB_POKE
CMD_ACTIONFB_ATTACHSCOPE
CMD_ACTIONFB_ATTACHBARREL
CMD_ACTIONFB_RESTRAIN
CMD_ACTIONFB_PICKUP_HEAVY
CMD_ACTIONFB_PRESS_TRIGGER
CMD_ACTIONFB_RAISE_FLAG
CMD_ACTIONFB_LOWER_FLAG
CMD_ACTIONFB_STOP_ALARM
CMD_ACTIONFB_DROPITEM_HANDS
CMD_ACTIONMOD_STARTENGINE
------------------- VEHICLES ----------------------
CMD_ACTIONMOD_TOOTHORN
CMD_ACTIONMOD_DRIVER_DOOR_OPEN
CMD_ACTIONMOD_DRIVER_DOOR_CLOSE
CMD_ACTIONMOD_CODRIVER_DOOROPEN
CMD_ACTIONMOD_CODRIVER_DOORCLOSE
CMD_ACTIONMOD_STOPENGINE
CMD_ACTIONMOD_SHIFTGEAR
CMD_ACTIONMOD_HEADLIGHT
CMD_GESTUREMOD_GREETING
------------------- GESTURES ----------------------
modifier (differential animation)
CMD_GESTUREMOD_POINT
CMD_GESTUREMOD_THUMB
CMD_GESTUREMOD_THUMBDOWN
CMD_GESTUREMOD_SILENCE
CMD_GESTUREMOD_TAUNT
CMD_GESTUREMOD_TIMEOUT
CMD_GESTUREMOD_HEART
CMD_GESTUREMOD_FACEPALM
CMD_GESTUREMOD_WATCHING
CMD_GESTUREMOD_HOLD
CMD_GESTUREMOD_LISTENING
CMD_GESTUREMOD_POINTSELF
CMD_GESTUREMOD_LOOKATME
CMD_GESTUREMOD_OKAY
CMD_GESTUREMOD_RPS
CMD_ACTIONINT_RPS_ROCK
CMD_ACTIONINT_RPS_PAPER
CMD_ACTIONINT_RPS_SCISSORS
CMD_GESTUREMOD_THROAT
CMD_GESTUREMOD_CLAP
CMD_GESTUREMOD_DABBING
CMD_GESTUREMOD_MOVE
CMD_GESTUREMOD_DOWN
CMD_GESTUREMOD_COME
CMD_GESTUREMOD_TAUNTKISS
CMD_GESTUREMOD_TAUNTELBOW
CMD_GESTUREMOD_TAUNTTHINK
CMD_GESTUREMOD_NODHEAD
CMD_GESTUREMOD_SHAKEHEAD
CMD_GESTUREMOD_SHRUG
CMD_GESTUREMOD_SURRENDER
CMD_GESTUREMOD_SURRENDERIN
CMD_GESTUREMOD_SURRENDEROUT
CMD_GESTUREFB_GREETING
fb (full body)
CMD_GESTUREFB_POINT
CMD_GESTUREFB_THUMB
CMD_GESTUREFB_THUMBDOWN
CMD_GESTUREFB_SILENCE
CMD_GESTUREFB_TAUNT
CMD_GESTUREFB_TIMEOUT
CMD_GESTUREFB_HEART
CMD_GESTUREFB_WATCHING
CMD_GESTUREFB_HOLD
CMD_GESTUREFB_LISTENING
CMD_GESTUREFB_POINTSELF
CMD_GESTUREFB_LOOKATME
CMD_GESTUREFB_OKAY
CMD_GESTUREFB_SALUTE
CMD_GESTUREFB_CAMPFIRE
CMD_GESTUREFB_LYINGDOWN
CMD_GESTUREFB_SOS
CMD_GESTUREFB_SITA
CMD_GESTUREFB_SITB
CMD_GESTUREFB_DABBING
CMD_GESTUREFB_KNEEL
CMD_GESTUREFB_THROAT
CMD_GESTUREFB_MOVE
CMD_GESTUREFB_DOWN
CMD_GESTUREFB_COME
CMD_GESTUREFB_TAUNTKISS
CMD_GESTUREFB_TAUNTTHINK
CMD_GESTUREFB_DANCE
CMD_GESTUREFB_NODHEAD
CMD_GESTUREFB_SHAKEHEAD
CMD_GESTUREFB_SHRUG
CMD_GESTUREFB_SURRENDER
CMD_GESTUREFB_SURRENDERIN
CMD_GESTUREFB_SURRENDEROUT
CMD_TRAILER_WAKE_UP
------------------- TRAILER -----------------------
CMD_TRAILER_DEAD_BODY
CMD_TRAILER_WALKIE_TALKIE
CMD_TRAILER_WOUNDED
CMD_TRAILER_WALK_AWAY
CMD_TRAILER_DEAD
CMD_SUICIDEFB_1HD
------------------- SUICIDE -----------------------
fb (full body)
CMD_SUICIDEFB_FIREAXE
CMD_SUICIDEFB_PITCHFORK
CMD_SUICIDEFB_PISTOL
CMD_SUICIDEFB_RIFLE
CMD_SUICIDEFB_SWORD
CMD_SUICIDEFB_UNARMED
CMD_SUICIDEFB_WOODAXE
CMD_SUICIDEFB_SPEAR
CMD_SUICIDEFB_SICKLE
CMD_SUICIDEFB_HOE
Definition at line 573 of file dayzplayer.c.
{
    DEBUG_MENU,
    DEBUG_TURNSLIDE,
    DEBUG_SHOWDEBUGPLUGIN,
    DEBUG_SHOWINJURY,
    DEBUG_SHOWEXHAUSTION,
    DEBUG_ENABLEJUMP,
    DEBUG_ENABLETALKING,
    STANCEIDX_ERECT,
    STANCEIDX_CROUCH,
    STANCEIDX_PRONE,
    STANCEIDX_RAISEDERECT,
    STANCEIDX_RAISEDCROUCH,
    STANCEIDX_RAISEDPRONE,
    STANCEMASK_ERECT,
    STANCEMASK_CROUCH,
    STANCEMASK_PRONE,
    STANCEMASK_RAISEDERECT,
    STANCEMASK_RAISEDCROUCH,
    STANCEMASK_RAISEDPRONE,
    STANCEMASK_ALL,     // STANCEMASK_ERECT | STANCEMASK_CROUCH | STANCEMASK_PRONE | STANCEMASK_RAISEDERECT | STANCEMASK_RAISEDCROUCH | STANCEMASK_RAISEDPRONE
    STANCEMASK_NOTRAISED    = STANCEMASK_ERECT | STANCEMASK_CROUCH | STANCEMASK_PRONE,
    STANCEMASK_RAISED       = STANCEMASK_RAISEDERECT | STANCEMASK_RAISEDCROUCH | STANCEMASK_RAISEDPRONE,
    MOVEMENT_IDLE,
    MOVEMENT_WALK,
    MOVEMENT_RUN,
    MOVEMENT_SPRINT,
    ROTATION_DISABLE,
    ROTATION_ENABLE,
    MOVEMENTIDX_SLIDE   = -2,
    MOVEMENTIDX_IDLE    = 0,
    MOVEMENTIDX_WALK    = 1,
    MOVEMENTIDX_RUN     = 2,
    MOVEMENTIDX_SPRINT  = 3,
    MOVEMENTIDX_CROUCH_RUN = 4,
    MELEE_LIGHT = 0,
    MELEE_HEAVY = 1,
    VEHICLECLASS_CAR,
    VEHICLECLASS_HELI,
    VEHICLESEAT_DRIVER,
    VEHICLESEAT_CODRIVER,
    VEHICLESEAT_PASSENGER_L,
    VEHICLESEAT_PASSENGER_R,
    COMMANDID_NONE,         // type is int - no command - invalid state
    COMMANDID_MOVE,         // type is int (overridden from C++) - normal movement (idle, walk, run, sprint, ... )
    COMMANDID_ACTION,       // type is int (overridden from C++) - full body action
    COMMANDID_MELEE,        // type is int (overridden from C++) - melee attacks
    COMMANDID_MELEE2,       // type is int (overridden from C++) - melee attacks
    COMMANDID_FALL,         // type is int (overridden from C++) - falling
    COMMANDID_DEATH,        // type is int (overridden from C++) - dead
    COMMANDID_DAMAGE,       // type is int (overridden from C++) - fullbody damage
    COMMANDID_LADDER,       // type is int (overridden from C++) - ladder
    COMMANDID_UNCONSCIOUS,  // type is int (overridden from C++) - unconscious
    COMMANDID_SWIM,         // type is int (overridden from C++) - swimming
    COMMANDID_VEHICLE,      // type is int (overridden from C++) - vehicle
    COMMANDID_CLIMB,        // type is int (overridden from C++) - climb
    COMMANDID_SCRIPT,       // type is int (overridden from C++) - all scripted commands
    COMMANDID_MOD_LOOKAT,       // look at - always on
    COMMANDID_MOD_WEAPONS,      // weapons - always on
    COMMANDID_MOD_ACTION,       // action - additive action
    COMMANDID_MOD_DAMAGE,       // damage - additive damage
    CMD_ACTIONINT_INTERRUPT             = -2,
    CMD_ACTIONINT_FINISH                = -1,
    CMD_ACTIONINT_END                   = 0,
    CMD_ACTIONINT_ACTION                = 1,
    CMD_ACTIONINT_ACTIONLOOP            = 2,
    CMD_ACTIONMOD_DRINK                 = 0,        // erc,cro          [end, end2]
    CMD_ACTIONMOD_EAT                   = 1,        // erc,cro          [end, end2]
    CMD_ACTIONMOD_EMPTY_VESSEL          = 2,        // erc,cro          [end]
    CMD_ACTIONMOD_CATCHRAIN             = 3,        // erc,cro          [end]
    CMD_ACTIONMOD_VIEWCOMPASS           = 7,        // erc,cro          [end]
    CMD_ACTIONMOD_ITEM_TUNE             = 9,        // erc,cro          [end]
    CMD_ACTIONMOD_GIVEL                 = 10,       // erc,cro          [end]
    CMD_ACTIONMOD_GIVER                 = 11,       // erc,cro          [end]
    CMD_ACTIONMOD_SHAVE                 = 12,       // erc,cro          [end]
    CMD_ACTIONMOD_FILLMAG               = 13,       // erc,cro          [end]
    CMD_ACTIONMOD_EMPTYMAG              = 14,       // erc,cro          [end]
    CMD_ACTIONMOD_OPENITEM              = 15,       // erc,cro          [end]
    CMD_ACTIONMOD_TAKETEMPSELF          = 18,       // erc,cro          [end]
    CMD_ACTIONMOD_VIEWMAP               = 19,       // erc,cro          [end]
    CMD_ACTIONMOD_RAISEITEM             = 20,       // erc,cro          [end]
    CMD_ACTIONMOD_SEARCHINVENTORY       = 21,       // erc,cro          [end]
    CMD_ACTIONMOD_CRAFTING              = 22,       // erc,cro          [end]
    CMD_ACTIONMOD_RESTRAINEDSTRUGGLE    = 23,       // erc,cro          [end, end2]
    CMD_ACTIONMOD_COVERHEAD_SELF        = 24,       // erc,cro          [end, end2]
    CMD_ACTIONMOD_COVERHEAD_TARGET      = 25,       // erc,cro          [end, end2]
    CMD_ACTIONMOD_SET_ALARM             = 250,
    CMD_ACTIONMOD_SET_KITCHENTIMER      = 252,
    CMD_ACTIONMOD_RESET_KITCHENTIMER    = 253,
    // onetime
    CMD_ACTIONMOD_PICKUP_HANDS          = 500,      // erc,cro
    CMD_ACTIONMOD_PICKUP_INVENTORY      = 501,      // erc,cro
    CMD_ACTIONMOD_LICKBATTERY           = 502,      // erc,cro
    CMD_ACTIONMOD_LIGHTFLARE            = 503,      // erc,cro
    CMD_ACTIONMOD_LITCHEMLIGHT          = 504,      // erc,cro
    CMD_ACTIONMOD_UNPINGRENAGE          = 505,      // erc,cro
    CMD_ACTIONMOD_OPENDOORFW            = 506,      // erc,cro
    CMD_ACTIONMOD_OPENLID               = 507,      // erc,cro
    CMD_ACTIONMOD_CLOSELID              = 508,      // erc,cro
    CMD_ACTIONMOD_ITEM_ON               = 509,      // erc,cro
    CMD_ACTIONMOD_ITEM_OFF              = 510,      // erc,cro
    CMD_ACTIONMOD_BATONEXTEND           = 511,      // erc,cro
    CMD_ACTIONMOD_BATONRETRACT          = 512,      // erc,cro
    CMD_ACTIONMOD_UNLOCKHANDCUFFTARGET  = 513,      // erc,cro
    CMD_ACTIONMOD_FISHINGRODEXTEND      = 514,      // erc,cro
    CMD_ACTIONMOD_FISHINGRODRETRACT     = 515,      // erc,cro
    CMD_ACTIONMOD_CLEANHANDSBOTTLE      = 516,      // erc,cro
    CMD_ACTIONMOD_OPENITEM_ONCE         = 517,      // erc,cro
    CMD_ACTIONMOD_ATTACHSCOPE           = 518,      // erc,cro
    CMD_ACTIONMOD_ATTACHBARREL          = 519,      // erc,cro
    CMD_ACTIONMOD_EMPTYSEEDSPACK        = 520,      // erc,cro
    CMD_ACTIONMOD_INTERACTONCE          = 521,      // erc,cro
    CMD_ACTIONMOD_ATTACHITEM            = 522,      // erc,cro
    CMD_ACTIONMOD_CLOSEITEM_ONCE        = 523,      // erc,cro,pne
    CMD_ACTIONMOD_FOLDITEM_ONCE         = 524,      // erc,cro
    CMD_ACTIONMOD_UNFOLDITEM_ONCE       = 525,      // erc,cro
    CMD_ACTIONMOD_PRESS_TRIGGER         = 526,      // erc,cro
    CMD_ACTIONMOD_STOP_ALARM            = 251,
    CMD_ACTIONMOD_DROPITEM_HANDS        = 900,      // erc, cro
    CMD_ACTIONMOD_DROPITEM_INVENTORY    = 901,      // erc, cro
    CMD_ACTIONFB_DRINK                  = 0,        // pne              [end, end2]
    CMD_ACTIONFB_EAT                    = 1,        // pne              [end, end2]
    CMD_ACTIONFB_CATCHRAIN              = 3,        // pne              [end]
    CMD_ACTIONFB_ITEM_TUNE              = 9,        // pne              [end]
    CMD_ACTIONFB_GIVEL                  = 10,       // pne              [end]
    CMD_ACTIONFB_GIVER                  = 11,       // pne              [end]
    CMD_ACTIONFB_FILLMAG                = 13,       // pne              [end]
    CMD_ACTIONFB_EMPTYMAG               = 14,       // pne              [end]
    CMD_ACTIONFB_DRINKPOND              = 50,       // cro              [end]
    CMD_ACTIONFB_DRINKWELL              = 51,       // cro              [end]
    CMD_ACTIONFB_FILLBOTTLEWELL         = 52,       // cro              [end]
    CMD_ACTIONFB_FIREESTINGUISHER       = 53,       // erc              [end]
    CMD_ACTIONFB_WRING                  = 54,       // cro              [end]
    CMD_ACTIONFB_FISHING                = 56,       // cro              [action (check fish), end(catch fish), end2(not catching anything ]
    CMD_ACTIONFB_CPR                    = 57,       // cro              [end]
    CMD_ACTIONFB_BANDAGE                = 58,       // cro              [end]
    CMD_ACTIONFB_CRAFTING               = 59,       // cro              [end]
    CMD_ACTIONFB_INTERACT               = 60,       // erc,cro          [end]
    CMD_ACTIONFB_FORCEFEED              = 62,       // erc,cro          [end]
    CMD_ACTIONFB_BANDAGETARGET          = 63,       // erc,cro          [end]
    CMD_ACTIONFB_SPRAYPLANT             = 64,       // cro              [end]
    CMD_ACTIONFB_STARTFIRE              = 65,       // cro              [end]
    CMD_ACTIONFB_ANIMALSKINNING         = 66,       // cro              [end]
    CMD_ACTIONFB_WASHHANDSWELL          = 67,       // cro              [end]
    CMD_ACTIONFB_WASHHANDSPOND          = 68,       // cro              [end]
    CMD_ACTIONFB_SALINEBLOODBAGTARGET   = 69,       // erc,cro          [end]
    CMD_ACTIONFB_SALINEBLOODBAG         = 70,       // erc,cro          [end]
    CMD_ACTIONFB_STITCHUPSELF           = 71,       // erc,cro          [end]
    CMD_ACTIONFB_VOMIT                  = 72,       // cro              [end]
    CMD_ACTIONFB_UNRESTRAINTARGET       = 73,       // erc,cro          [end (finish cutting), end2 (cancel cutting)]
    CMD_ACTIONFB_RESTRAINTARGET         = 74,       // erc,cro          [end (finish tying up), end2 (cancel tying up)]
    CMD_ACTIONFB_CHECKPULSE             = 76,       // cro              [end]
    CMD_ACTIONFB_CLEANWOUNDSTARGET      = 78,       // erc, cro         [end]
    CMD_ACTIONFB_COLLECTBLOODSELF       = 81,       // erc, cro         [end]
    CMD_ACTIONFB_EMPTY_VESSEL           = 82,       // erc, cro         [end]
    CMD_ACTIONFB_OPENITEM               = 83,       // pne              [end]
    CMD_ACTIONFB_HACKBUSH               = 85,       // erc              [end, end2]
    CMD_ACTIONFB_HACKTREE               = 86,       // erc              [end, end2]
    CMD_ACTIONFB_TAKETEMPSELF           = 87,       // pne              [end]
    CMD_ACTIONFB_DIG                    = 88,       // erc              [end, end2]
    CMD_ACTIONFB_DIGUPCACHE             = 89,       // erc              [end, end2]
    CMD_ACTIONFB_DIGMANIPULATE          = 90,       // erc              [end, end2]
    CMD_ACTIONFB_DEPLOY_HEAVY           = 95,       // erc              [end, end2]
    CMD_ACTIONFB_DEPLOY_2HD             = 96,       // cro              [end, end2]
    CMD_ACTIONFB_DEPLOY_1HD             = 97,       // cro              [end, end2]
    CMD_ACTIONFB_BLOWFIREPLACE          = 98,       // cro              [end]
    CMD_ACTIONFB_VIEWMAP                = 99,       // pne              [end]
    CMD_ACTIONFB_VIEWCOMPASS            = 100,      // pne              [end]
    CMD_ACTIONFB_FILLBOTTLEPOND         = 101,      // erc, cro         [end]
    CMD_ACTIONFB_PLACING_HEAVY          = 102,      // erc              [end, end2]
    CMD_ACTIONFB_PLACING_2HD            = 103,      // cro              [end, end2]
    CMD_ACTIONFB_PLACING_1HD            = 104,      // cro              [end, end2]
    CMD_ACTIONFB_CUTBARK                = 105,      // erc,cro          [end, end2]
    CMD_ACTIONFB_VIEWNOTE               = 106,      // erc,cro,pne      [end]
    CMD_ACTIONFB_SEARCHINVENTORY        = 107,      // pne              [end]
    CMD_GESTUREFB_LOOKOPTICS            = 108,      // erc,cro,pne      [end]
    CMD_ACTIONFB_MINEROCK               = 109,      // erc              [end, end2]
    CMD_ACTIONFB_RAISEITEM              = 110,      // pne              [end]
    CMD_ACTIONFB_RESTRAINEDSTRUGGLE     = 111,      // ,pne             [end, end2]
    CMD_ACTIONFB_RESTRAINSELF           = 112,      // erc,cro          [end]
    CMD_ACTIONFB_ASSEMBLE               = 113,      // erc,cro          [end, end2]
    CMD_ACTIONFB_DISASSEMBLE            = 114,      // erc,cro          [end, end2]
    CMD_ACTIONFB_FLAME_REPAIR           = 115,      // erc, cro
    CMD_ACTIONFB_TURN_VALVE             = 116,      // erc
    CMD_ACTIONFB_SET_ALARM              = 250,      // erc,cro          ??not sure
    // onetime
    CMD_ACTIONFB_PICKUP_HANDS           = 500,      // pne
    CMD_ACTIONFB_PICKUP_INVENTORY       = 501,      // pne
    CMD_ACTIONFB_LICKBATTERY            = 502,      // pne
    CMD_ACTIONFB_LIGHTFLARE             = 503,      // pne
    CMD_ACTIONFB_LITCHEMLIGHT           = 504,      // pne
    CMD_ACTIONFB_UNPINGRENAGE           = 505,      // pne
    CMD_ACTIONFB_ITEM_ON                = 506,      // pne
    CMD_ACTIONFB_ITEM_OFF               = 507,      // pne
    CMD_ACTIONFB_HANDCUFFTARGET         = 508,      // erc,cro
    CMD_ACTIONFB_MORPHINE               = 509,      // cro
    CMD_ACTIONFB_INJECTION              = 510,      // cro
    CMD_ACTIONFB_INJECTIONTARGET        = 511,      // erc,cro
    CMD_ACTIONFB_DRINKSIP               = 512,      // cro
    CMD_ACTIONFB_CLEANHANDSBOTTLE       = 513,      // pne
    CMD_ACTIONFB_OPENITEM_ONCE          = 514,      // pne
    CMD_ACTIONFB_POKE                   = 515,      // cro
    CMD_ACTIONFB_ATTACHSCOPE            = 516,      // pne
    CMD_ACTIONFB_ATTACHBARREL           = 517,      // pne
    CMD_ACTIONFB_RESTRAIN               = 518,      // erc,cro,pne
    CMD_ACTIONFB_PICKUP_HEAVY           = 519,      // erc
    CMD_ACTIONFB_PRESS_TRIGGER          = 526,      // pne
    CMD_ACTIONFB_RAISE_FLAG             = 600,      // erc?
    CMD_ACTIONFB_LOWER_FLAG             = 601,      // erc?
    CMD_ACTIONFB_STOP_ALARM             = 251,
    CMD_ACTIONFB_DROPITEM_HANDS     = 900,          // pne, pne back
    // looping actions
    CMD_ACTIONMOD_STARTENGINE           = 300,          // [end]
    CMD_ACTIONMOD_TOOTHORN              = 301,          // [end]
    // onetime actions
    CMD_ACTIONMOD_DRIVER_DOOR_OPEN      = 400,
    CMD_ACTIONMOD_DRIVER_DOOR_CLOSE     = 401,
    CMD_ACTIONMOD_CODRIVER_DOOROPEN     = 402,
    CMD_ACTIONMOD_CODRIVER_DOORCLOSE    = 403,
    CMD_ACTIONMOD_STOPENGINE            = 404,
    CMD_ACTIONMOD_SHIFTGEAR             = 405,
    CMD_ACTIONMOD_HEADLIGHT             = 406,
    CMD_GESTUREMOD_GREETING             = 1000,         // erc,cro          [end]
    CMD_GESTUREMOD_POINT                = 1001,         // erc,cro          [end]
    CMD_GESTUREMOD_THUMB                = 1002,         // erc,cro          [end, CMD_ACTIONINT_ACTION to switch to THUMB DOWN]
    CMD_GESTUREMOD_THUMBDOWN            = 1003,         // erc,cro          [end, CMD_ACTIONINT_ACTION to switch to THUMB UP]
    CMD_GESTUREMOD_SILENCE              = 1004,         // erc,cro          [end]
    CMD_GESTUREMOD_TAUNT                = 1005,         // erc,cro          [end]
    CMD_GESTUREMOD_TIMEOUT              = 1006,         // erc,cro          [end]
    CMD_GESTUREMOD_HEART                = 1007,         // erc,cro          [end]
    CMD_GESTUREMOD_FACEPALM             = 1008,         // erc,cro          [end]
    CMD_GESTUREMOD_WATCHING             = 1009,         // erc,cro          [end]
    CMD_GESTUREMOD_HOLD                 = 1010,         // erc,cro          [end]
    CMD_GESTUREMOD_LISTENING            = 1011,         // erc,cro          [end]
    CMD_GESTUREMOD_POINTSELF            = 1012,         // erc,cro          [end]
    CMD_GESTUREMOD_LOOKATME             = 1013,         // erc,cro          [end]
    CMD_GESTUREMOD_OKAY                 = 1014,         // erc,cro          [end]
    CMD_GESTUREMOD_RPS                  = 10000,        // erc              [SPECIAL, SEE BELOW]
    CMD_ACTIONINT_RPS_ROCK              = 10,           // RPS Internal Gesture
    CMD_ACTIONINT_RPS_PAPER             = 11,           // RPS Internal Gesture
    CMD_ACTIONINT_RPS_SCISSORS          = 12,           // RPS Internal Gesture
    // onetime
    CMD_GESTUREMOD_THROAT               = 1100,         // erc,cro
    CMD_GESTUREMOD_CLAP                 = 1101,         // erc,cro
    CMD_GESTUREMOD_DABBING              = 1102,         // erc,cro
    CMD_GESTUREMOD_MOVE                 = 1103,         // erc,cro
    CMD_GESTUREMOD_DOWN                 = 1104,         // erc,cro
    CMD_GESTUREMOD_COME                 = 1105,         // erc,cro
    CMD_GESTUREMOD_TAUNTKISS            = 1106,         // erc,cro
    CMD_GESTUREMOD_TAUNTELBOW           = 1107,         // erc,cro
    CMD_GESTUREMOD_TAUNTTHINK           = 1108,         // erc,cro
    CMD_GESTUREMOD_NODHEAD              = 1109,         // erc,cro
    CMD_GESTUREMOD_SHAKEHEAD            = 1110,         // erc,cro
    CMD_GESTUREMOD_SHRUG                = 1111,         // erc,cro
    CMD_GESTUREMOD_SURRENDER            = 1112,         // erc
    CMD_GESTUREMOD_SURRENDERIN          = 1112,         // erc
    CMD_GESTUREMOD_SURRENDEROUT         = 1113,         // erc
    CMD_GESTUREFB_GREETING              = 1000,         // pne      [end]
    CMD_GESTUREFB_POINT                 = 1001,         // pne      [end]
    CMD_GESTUREFB_THUMB                 = 1002,         // pne      [end, CMD_ACTIONINT_ACTION to switch to THUMB DOWN]
    CMD_GESTUREFB_THUMBDOWN             = 1003,         // pne      [end, CMD_ACTIONINT_ACTION to switch to THUMB UP]
    CMD_GESTUREFB_SILENCE               = 1004,         // pne      [end]
    CMD_GESTUREFB_TAUNT                 = 1005,         // pne      [end]
    CMD_GESTUREFB_TIMEOUT               = 1006,         // pne      [end]
    CMD_GESTUREFB_HEART                 = 1007,         // pne      [end]
    CMD_GESTUREFB_WATCHING              = 1009,         // pne      [end]
    CMD_GESTUREFB_HOLD                  = 1010,         // pne      [end]
    CMD_GESTUREFB_LISTENING             = 1011,         // pne      [end]
    CMD_GESTUREFB_POINTSELF             = 1012,         // pne      [end]
    CMD_GESTUREFB_LOOKATME              = 1013,         // pne      [end]
    CMD_GESTUREFB_OKAY                  = 1014,         // pne      [end]
    CMD_GESTUREFB_SALUTE                = 1050,         // erc              [end]
    CMD_GESTUREFB_CAMPFIRE              = 1051,         // cro              [end]
    CMD_GESTUREFB_LYINGDOWN             = 1052,         // cro              [end]
    CMD_GESTUREFB_SOS                   = 1053,         // erc              [end]
    CMD_GESTUREFB_SITA                  = 1054,         // cro              [end]
    CMD_GESTUREFB_SITB                  = 1055,         // cro              [end]
    CMD_GESTUREFB_DABBING               = 1056,         // erc, cro         [end]
    CMD_GESTUREFB_KNEEL                 = 1057,         // cro              [end]
    // onetime
    CMD_GESTUREFB_THROAT                = 1100,         // pne
    CMD_GESTUREFB_MOVE                  = 1103,         // pne
    CMD_GESTUREFB_DOWN                  = 1104,         // pne
    CMD_GESTUREFB_COME                  = 1105,         // pne
    CMD_GESTUREFB_TAUNTKISS             = 1106,         // pne
    CMD_GESTUREFB_TAUNTTHINK            = 1108,         // pne
    CMD_GESTUREFB_DANCE                 = 1109,         // erc
    CMD_GESTUREFB_NODHEAD               = 1110,         // pne
    CMD_GESTUREFB_SHAKEHEAD             = 1111,         // pne
    CMD_GESTUREFB_SHRUG                 = 1112,         // pne
    CMD_GESTUREFB_SURRENDER             = 1113,         // cro,pne
    CMD_GESTUREFB_SURRENDERIN           = 1113,         // cro,pne
    CMD_GESTUREFB_SURRENDEROUT          = 1114,         // cro,pne
    CMD_TRAILER_WAKE_UP                 = 3000,
    CMD_TRAILER_DEAD_BODY               = 3001,
    CMD_TRAILER_WALKIE_TALKIE           = 3002,
    CMD_TRAILER_WOUNDED                 = 3003,
    CMD_TRAILER_WALK_AWAY               = 3004,
    CMD_TRAILER_DEAD                    = 3005,
    CMD_SUICIDEFB_1HD                   = 2000,         // cro              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_FIREAXE               = 2001,         // erc              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_PITCHFORK             = 2002,         // erc              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_PISTOL                = 2003,         // cro              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_RIFLE                 = 2004,         // cro              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_SWORD                 = 2005,         // erc              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_UNARMED               = 2006,         // cro              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_WOODAXE               = 2007,         // erc              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_SPEAR                 = 2008,         // erc              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_SICKLE                = 2009,         // cro              [end (cancel), end2 (commit)]
    CMD_SUICIDEFB_HOE                   = 2010,         // erc              [end (cancel), end2 (commit)]
    // 32767 is totaly MAXIMAL index !!!!!
};
DayZPlayerInstanceType
enum DayZPlayerInstanceType
defined in C++
Enumerator
INSTANCETYPE_SERVER
INSTANCETYPE_CLIENT
server instance
INSTANCETYPE_REMOTE
client instance && controlled
INSTANCETYPE_AI_SERVER
client instance && other player
INSTANCETYPE_AI_REMOTE
temporary!
INSTANCETYPE_AI_SINGLEPLAYER
temporary!
Definition at line 990 of file dayzplayer.c.
{
    INSTANCETYPE_SERVER,
    INSTANCETYPE_CLIENT,
    INSTANCETYPE_REMOTE,
    INSTANCETYPE_AI_SERVER,
    INSTANCETYPE_AI_REMOTE,
    INSTANCETYPE_AI_SINGLEPLAYER,
}
Function Documentation
AddItemBoneRemap()
proto native int AddItemBoneRemap (string pItemClass, array< string > pBoneRemap)
add bone remap for item class pBoneRemap has always 2x N members bone in item's P3D first, bone in Character skeleton second array<string> remap = { "bolt", "Weapon_Bolt", "magazine", "Weapon_Magazine", "trigger", "Weapon_Trigger" }; AddItemBoneRemap("class", remap);
AddItemInHandsProfile()
proto native int AddItemInHandsProfile (string pItemClass, string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg)
VKOSTIK: DO NOT FORGET !!! HumanItemBehaviorCfg.m_iPerItemCameraUD - per item camera user data - enables you setup different cameras for different items in hands.
adds setup profile for items of class pItemClass when item is in hands - pAnimInstanceName is used for animation sourcing pCanRaise is whether weapon / item can be raised pRHandIK == false -> rhand ik is always turned off pLHandIK == false -> lhand ik is always turned off
AddItemInHandsProfileIK()
proto native int AddItemInHandsProfileIK (string pItemClass, string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg, string pIkPoseAnim, string pWeaponStates = "")
AimingModel()
bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
-------------— aiming model ----------------------—
updated each tick - this takes care about aiming
This Aiming Model
Definition at line 1301 of file dayzplayerimplement.c.
    {
        GetMovementState(m_MovementState);
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2 )
        {
            HumanCommandMelee2 hcm = GetCommand_Melee2();
            if( hcm.IsFinisher() )
            {
                if( !m_AimingFinisherStarted )
                {
                    m_AimingModel.OnFinisherBegin(pModel.m_fCurrentAimY);
                    m_AimingFinisherStarted = true;
                }
                m_AimingModel.ProcessStealthFilters(pDt, pModel);
            }
            return true;
        }
        if ( IsFireWeaponRaised() )
        {
            if ( !m_RaiseStarted )
            {
                m_AimingModel.OnRaiseBegin(this);
                m_RaiseStarted = true;
            }
            m_AimingModel.ProcessAimFilters( pDt, pModel, m_MovementState.m_iStanceIdx );
            return true;
        }
        m_RaiseStarted = false;
        m_AimingFinisherStarted = false;
        return true;
    }
References GetCommand_Melee2(), GetMovementState(), HumanCommandMelee2::IsFinisher(), IsFireWeaponRaised(), m_AimingFinisherStarted, m_AimingModel, SDayZPlayerAimingModel::m_fCurrentAimY, m_MovementState, m_RaiseStarted, DayZPlayerImplementAiming::OnFinisherBegin(), DayZPlayerImplementAiming::OnRaiseBegin(), DayZPlayerImplementAiming::ProcessAimFilters(), and DayZPlayerImplementAiming::ProcessStealthFilters().
AnimCallCommand()
proto native void AnimCallCommand (int pCommand, int pParamInt, float pParamFloat)
-------------— animation graph functions ----------------------—
functions usable only from CommandHandler
AnimSetBool()
proto native void AnimSetBool (int pVar, bool pBool)
AnimSetFloat()
proto native void AnimSetFloat (int pVar, float pFlt)
AnimSetInt()
proto native void AnimSetInt (int pVar, int pInt)
CameraHandler()
int CameraHandler (int pCameraMode)
-------------— camera handling ----------------------—
virtual returns registered camera type pCameraMode - DayZPlayerConstants.CAMERAMODE_ ...
This is main camera selection logic
ironsights
get movement state
VKOSTIK: v ostatnich commandech mimo COMMANDID_MOVE je m_MovementState.m_iStanceIdx - DayZPlayerConstants.STANCEIDX_ERECT m_MovementState.m_iMovement = 0 (idle)
COMMANDID_ACTION returns stance right - ERECT/CROUCH
melee camera - not melee - stays in stance camera
Definition at line 2354 of file dayzplayerimplement.c.
    {
        // Print("DayZPlayerCfgBase: Camera Handler called");
        /* {
            int perItemCamUD = GetCurrentPerItemCameraUD();
            string      a   = "Per Item Camera User Data: " + ToString(perItemCamUD);
            Print(a);
        } */
        if (!m_LiftWeapon_player)
        {
            if (m_CameraIronsight)
            {
                if (m_CameraOptics)
                    return DayZPlayerCameras.DAYZCAMERA_OPTICS;
                else
                    return DayZPlayerCameras.DAYZCAMERA_IRONSIGHTS;
            }
            else if (m_CameraOptics)
                return DayZPlayerCameras.DAYZCAMERA_OPTICS;
        }
        //uncon
        if ( m_IsUnconscious )
        {
            return DayZPlayerCameras.DAYZCAMERA_1ST_UNCONSCIOUS;
        }
        HumanCommandVehicle vehicleCommand = GetCommand_Vehicle();
        if (!m_Camera3rdPerson)
        {
            if ( vehicleCommand )
            {
                return DayZPlayerCameras.DAYZCAMERA_1ST_VEHICLE;
            }
            return DayZPlayerCameras.DAYZCAMERA_1ST;
        }
        else
        {
            if ( vehicleCommand )
            {
                Transport transport = vehicleCommand.GetTransport();
                if (transport && GetParent())
                {
                    return transport.Get3rdPersonCameraType();
                }
            }
            GetMovementState(m_MovementState);
            if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CLIMB;
            }
            if ( m_JumpClimb.m_bIsJumpInProgress )
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_JUMP;
            }
            //
            // normal movement cameras
            if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CRO;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CRO_RAISED;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_PRO;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_PRO_RAISED;
            }
            if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
            {
                EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
                bool isWeapon       = entityInHands && entityInHands.IsInherited(Weapon);
                if (isWeapon)
                {
                    return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED;
                }
                else
                {
                    return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED_MELEE;
                }
            }
            else if (m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_SPR;
            }
            // DayZPlayerConstants.STANCEIDX_ERECT
            return DayZPlayerCameras.DAYZCAMERA_3RD_ERC;
        }
        return DayZPlayerCameras.DAYZCAMERA_1ST;
    }
References DayZPlayerCameras::DAYZCAMERA_1ST, DayZPlayerCameras::DAYZCAMERA_1ST_UNCONSCIOUS, DayZPlayerCameras::DAYZCAMERA_1ST_VEHICLE, DayZPlayerCameras::DAYZCAMERA_3RD_CLIMB, DayZPlayerCameras::DAYZCAMERA_3RD_CRO, DayZPlayerCameras::DAYZCAMERA_3RD_CRO_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED_MELEE, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_SPR, DayZPlayerCameras::DAYZCAMERA_3RD_JUMP, DayZPlayerCameras::DAYZCAMERA_3RD_PRO, DayZPlayerCameras::DAYZCAMERA_3RD_PRO_RAISED, DayZPlayerCameras::DAYZCAMERA_IRONSIGHTS, DayZPlayerCameras::DAYZCAMERA_OPTICS, GetCommand_Vehicle(), GetMovementState(), GetParent(), HumanCommandVehicle::GetTransport(), DayZPlayerImplementJumpClimb::m_bIsJumpInProgress, m_Camera3rdPerson, m_CameraIronsight, m_CameraOptics, m_IsUnconscious, m_JumpClimb, m_LiftWeapon_player, and m_MovementState.
CanFreeLook()
bool CanFreeLook ()
this overrides freelok for cameras
Definition at line 57 of file dayzplayer.c.
    {
        return true;
    }
CommandClimbSettingsW()
proto native SHumanCommandClimbSettings CommandClimbSettingsW ()
this is used for getting appropriate sound effect to play step event on various surfaces && boots it's downcasted to StepSoundLookupTable
CommandHandler()
void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
-------------— command handling ----------------------—
updated each tick handles: starting new commands, canceling, interruption pDt - delta time pCurrentCommandID - actually running command's ID pCurrentCommandFinished - is current command finished
This is main command logic
handle weapon mode switch
handle all Camera changes, switch + zoom
handle death with high priority
handle finished commands
default behaviou after finish is to start move
debug test script command !PSOVIS
Sprint attack limiting - player has to be in full sprint for at least 0.5s
throwing handling
melee
Definition at line 1817 of file dayzplayerimplement.c.
    {
        if (ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
        HumanInputController hic = GetInputController();
        EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
        bool isWeapon       = entityInHands && entityInHands.IsInherited(Weapon);
        GetMovementState(m_MovementState);
        bool isRaisedNow = m_MovementState.IsRaised();
        if( isRaisedNow != m_IsRaised )
        {
            if( isRaisedNow && isWeapon )
                GetUApi().ActivateModificator("aiming");
            else
                GetUApi().DeactivateModificator("aiming");
            m_IsRaised = m_MovementState.IsRaised();
        }
        HandleADS();
        // handle weapons
        if (hic)
        {
            ItemOptics opticInHands = ItemOptics.Cast(entityInHands);
            if (isWeapon && (!m_ProcessFirearmMeleeHit || !m_ContinueFirearmMelee))
            {
                m_ProcessFirearmMeleeHit = false;
                bool exitIronSights = false;
                HandleWeapons(pDt, entityInHands, hic, exitIronSights);
            }
            else if (m_HandheldOpticsInUse && m_CameraOptics && opticInHands)
            {
                bool exitOptic = false;
                HandleOptic(opticInHands, true, hic, exitOptic);
            }
        }
        HandleView();
        GetMovementState(m_MovementState);
        if ( m_MovementState.m_iMovement != m_MovementState.m_LocalMovement )
        {
            OnMovementChanged();
            m_MovementState.m_LocalMovement = m_MovementState.m_iMovement;
        }
        if (HandleDeath(pCurrentCommandID))
        {
            return;
        }
        if (pCurrentCommandFinished)
        {
            if ( pCurrentCommandID == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
            {
                if ( (m_LastCommandBeforeUnconscious == DayZPlayerConstants.COMMANDID_VEHICLE) && (m_TransportCache != null))
                {
                    int crew_index = m_TransportCache.CrewMemberIndex(this);
                    int seat = m_TransportCache.GetSeatAnimationType(crew_index);
                    StartCommand_Vehicle(m_TransportCache, crew_index, seat, true);
                    m_TransportCache = null;
                    return;
                }
            }
            // start moving
            // start falling ? (could happen after climbing)
            if (PhysicsIsFalling(true))
            {
                StartCommand_Fall(0);
                m_FallYDiff = GetPosition()[1];
                return;
            }
            if ( m_Swimming.m_bWasSwimming )
            {
                StartCommand_Swim();
                return;
            }
            StartCommand_Move();
            if ( GetHumanInventory().GetEntityInHands() )
                ForceStandUpForHeavyItems( GetHumanInventory().GetEntityInHands() );
            return;
        }
        //--------------------------------------------
        if (ModCommandHandlerInside(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
        //--------------------------------------------
        // vehicle handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_VEHICLE)
        {
            HumanCommandVehicle hcv = GetCommand_Vehicle();
            if ( hcv.WasGearChange() )
            {
                GearChangeActionCallback cb = GearChangeActionCallback.Cast(AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_SHIFTGEAR, GearChangeActionCallback));
                cb.SetVehicleCommand(hcv);
            }
            return;
        }
        //--------------------------------------------
        HumanCommandMove hcm = GetCommand_Move();
        if (hcm && hcm.GetCurrentMovementSpeed() > 2.99 && m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
        {
            m_SprintedTime += pDt;
            if ( m_SprintedTime > 0.5)
                m_SprintFull = true;
            else
                m_SprintFull = false;
        }
        else
        {
            m_SprintedTime = 0.0;
            m_SprintFull = false;
        }
        //--------------------------------------------
        // swimming handling
        if (m_Swimming.HandleSwimming(pCurrentCommandID, hcm, m_MovementState))
        {
            m_JumpClimb.CheckAndFinishJump();
            return;
        }
        //--------------------------------------------
        // ladder handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_LADDER)
        {
            OnLadder(pDt, m_MovementState);
            return;
        }
        //--------------------------------------------
        // climb handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_CLIMB)
        {
            return;
        }
        //--------------------------------------------
        // fall handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL)
        {
            // vector   vel;
            // PhysicsGetVelocity(vel);
            // Print(vel);
            int landType = 0;
            HumanCommandFall fall = GetCommand_Fall();
            if (fall.PhysicsLanded())
            {
                DayZPlayerType type = GetDayZPlayerType();
                NoiseParams npar;
                // land
                m_FallYDiff = m_FallYDiff - GetPosition()[1];
                if (m_FallYDiff < 0.5)
                {
                    landType = HumanCommandFall.LANDTYPE_NONE;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandLight();
                    AddNoise(npar);
                }
                else if (m_FallYDiff < 1.0)
                {
                    if (m_MovementState.IsInProne() || m_MovementState.IsInRaisedProne())
                        landType = HumanCommandFall.LANDTYPE_NONE;
                    else
                        landType = HumanCommandFall.LANDTYPE_LIGHT;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandLight();
                    AddNoise(npar);
                }
                else if (m_FallYDiff < 2.0)
                {
                    landType = HumanCommandFall.LANDTYPE_MEDIUM;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandHeavy();
                    AddNoise(npar);
                }
                else
                {
                    landType = HumanCommandFall.LANDTYPE_HEAVY;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandHeavy();
                    AddNoise(npar);
                }
                if ( m_FallYDiff >= DayZPlayerImplementFallDamage.FD_DMG_FROM_HEIGHT && GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
                {
                    OnPlayerRecievedHit();
                }
                m_FallDamage.HandleFallDamage(m_FallYDiff);
                m_JumpClimb.CheckAndFinishJump(landType);
            }
            return;
        }
        // start falling ?
        if (PhysicsIsFalling(false))
        {
            StartCommand_Fall(0);
            m_FallYDiff = GetPosition()[1];
            return;
        }
        //--------------------------------------------
        // damage hits -> move to player base
        //if (HandleDamageHit(pCurrentCommandID))
        //{
        //  return;
        //}
        //--------------------------------------------
        // handle jumping
#ifndef NO_GUI
#ifdef DEVELOPER
        if (DiagMenu.GetValue(DayZPlayerConstants.DEBUG_ENABLEJUMP))
        {
            SHumanCommandClimbSettings hcls = GetDayZPlayerType().CommandClimbSettingsW();
            if ( m_MovementState.m_iMovement != DayZPlayerConstants.MOVEMENTIDX_IDLE )
                hcls.m_fFwMaxDistance = 3;
            else
                hcls.m_fFwMaxDistance = 1.2;
            SHumanCommandClimbResult    ret;
            HumanCommandClimb.DoClimbTest(this, ret, 0x3);
        }
#endif
#endif
        // start jump
        if (hic.IsJumpClimb())
        {
            m_JumpClimb.JumpOrClimb();
            return;
        }
        HumanCommandAdditives ad = GetCommandModifier_Additives();
        bool force = false;
#ifndef NO_GUI
#ifdef DEVELOPER
        force = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_ENABLETALKING);
#endif
#endif
        float amplitude = IsPlayerSpeaking();
        if ( amplitude > 0.1 || force )
        {
            if ( ad )
                ad.SetTalking(true);
            // add noises on server
            if ( GetGame().IsServer() )
            {
                int now = GetGame().GetTime();
                if ( now >= m_NextVoNNoiseTime )
                {
                    m_NextVoNNoiseTime = now + 1000;
                    int voiceLevel = GetGame().GetVoiceLevel(this);
                    DayZPlayerType pt = GetDayZPlayerType();
                    // add noise every second while talking
                    NoiseParams vonpar;
                    switch ( voiceLevel )
                    {
                        case VoiceLevelWhisper:
                            vonpar = pt.GetNoiseParamsWhisper();
                        break;
                        case VoiceLevelTalk:
                            vonpar = pt.GetNoiseParamsTalk();
                        break;
                        case VoiceLevelShout:
                            vonpar = pt.GetNoiseParamsShout();
                        break;
                    }
                    AddNoise(vonpar);
                }
            }
        }
        else
        {
            if ( ad )
                ad.SetTalking(false);
        }
        //--------------------------------------------
        // anything whats handled by InputController
        if (hic)
        {
            HumanCommandWeapons hcw = GetCommandModifier_Weapons();
            m_Throwing.HandleThrowing(hic, hcw, entityInHands, pDt);
            if (m_MeleeFightLogic.HandleFightLogic(pCurrentCommandID, hic, entityInHands, m_MovementState, m_ContinueFirearmMelee))
            {
                m_ProcessFirearmMeleeHit = isWeapon && (hic.IsMeleeWeaponAttack() || m_ProcessFirearmMeleeHit) || m_ContinueFirearmMelee;
                return;
            }
        }
        if (ModCommandHandlerAfter(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
    }
References UAInputAPI::ActivateModificator(), AddCommandModifier_Action(), AddNoise(), DayZPlayerImplementJumpClimb::CheckAndFinishJump(), DayZPlayerType(), UAInputAPI::DeactivateModificator(), HumanCommandClimb::DoClimbTest(), DayZPlayerImplementFallDamage::FD_DMG_FROM_HEIGHT, ForceStandUpForHeavyItems(), GetCommand_Fall(), GetCommand_Move(), GetCommand_Vehicle(), GetCommandModifier_Additives(), GetCommandModifier_Weapons(), HumanCommandMove::GetCurrentMovementSpeed(), GetDayZPlayerType(), GetGame(), GetInputController(), GetInstanceType(), GetMovementState(), GetPosition, CGame::GetTime(), GetUApi(), DiagMenu::GetValue(), CGame::GetVoiceLevel(), HandleADS(), HandleDeath(), DayZPlayerImplementFallDamage::HandleFallDamage(), HandleOptic(), DayZPlayerImplementSwimming::HandleSwimming(), DayZPlayerImplementThrowing::HandleThrowing(), HandleView(), HandleWeapons(), HumanCommandAdditives(), HumanCommandFall(), HumanInputController::IsJumpClimb(), HumanInputController::IsMeleeWeaponAttack(), IsPlayerSpeaking(), DayZPlayerImplementJumpClimb::JumpOrClimb(), DayZPlayerImplementSwimming::m_bWasSwimming, m_CameraOptics, m_ContinueFirearmMelee, m_FallDamage, m_FallYDiff, m_HandheldOpticsInUse, m_IsRaised, m_JumpClimb, m_LastCommandBeforeUnconscious, m_MeleeFightLogic, m_MovementState, m_NextVoNNoiseTime, m_ProcessFirearmMeleeHit, m_SprintedTime, m_SprintFull, m_Swimming, m_Throwing, m_TransportCache, ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), NoiseParams(), OnLadder(), OnMovementChanged(), OnPlayerRecievedHit(), PhysicsIsFalling(), GearChangeActionCallback::SetVehicleCommand(), SHumanCommandClimbSettings(), StartCommand_Fall(), StartCommand_Move(), StartCommand_Swim(), StartCommand_Vehicle(), and HumanCommandVehicle::WasGearChange().
CommandMoveSettingsW()
proto native SHumanCommandMoveSettings CommandMoveSettingsW ()
CommandSwimSettingsW()
proto native SHumanCommandSwimSettings CommandSwimSettingsW ()
DayZPlayerCamera()
class DayZPlayerCameraResult DayZPlayerCamera (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 1 of file dayzplayer.c.
    {
        m_pPlayer       = pPlayer;
        m_pInput        = pInput;
    }
Referenced by OnActivate(), and OnRPC().
DayZPlayerCameraResult()
private void DayZPlayerCamera::DayZPlayerCameraResult ()
cannot be instanced from script (always created from C++)
Definition at line 71 of file dayzplayer.c.
    {
DayZPlayerType()
private void DayZPlayerType ()
Definition at line 484 of file dayzplayer.c.
    {
        string cfgPath = "CfgVehicles SurvivorBase ";
        m_pNoiseStepStand = new NoiseParams();
        m_pNoiseStepStand.LoadFromPath(cfgPath + "NoiseStepStand");
        m_pNoiseStepCrouch = new NoiseParams();
        m_pNoiseStepCrouch.LoadFromPath(cfgPath + "NoiseStepCrouch");
        m_pNoiseStepProne = new NoiseParams();
        m_pNoiseStepProne.LoadFromPath(cfgPath + "NoiseStepProne");
        m_pNoiseLandLight = new NoiseParams();
        m_pNoiseLandLight.LoadFromPath(cfgPath + "NoiseLandLight");
        m_pNoiseLandHeavy = new NoiseParams();
        m_pNoiseLandHeavy.LoadFromPath(cfgPath + "NoiseLandHeavy");
        m_pNoiseWhisper = new NoiseParams();
        m_pNoiseWhisper.LoadFromPath(cfgPath + "NoiseWhisper");
        m_pNoiseTalk = new NoiseParams();
        m_pNoiseTalk.LoadFromPath(cfgPath + "NoiseTalk");
        m_pNoiseShout = new NoiseParams();
        m_pNoiseShout.LoadFromPath(cfgPath + "NoiseShout");
        LoadSoundWeaponEvent();
        LoadVegetationSounds();
    }
References LoadSoundWeaponEvent(), LoadVegetationSounds(), m_pNoiseLandHeavy, m_pNoiseLandLight, m_pNoiseShout, m_pNoiseStepCrouch, m_pNoiseStepProne, m_pNoiseStepStand, m_pNoiseTalk, m_pNoiseWhisper, and NoiseParams().
Referenced by CommandHandler(), OnStepEvent(), ProcessAttachmentEvent(), ProcessSoundEvent(), ProcessVoiceEvent(), and ProcessWeaponEvent().
DebugPreloadAnimationInstances()
proto native void DebugPreloadAnimationInstances ()
debug / hack - loads all animation instances
DebugSyncShadowSetup()
proto native bool DebugSyncShadowSetup (DayZPlayer pPlayer)
-------------— sync shadow ----------------------—
test if entity is DayZPlayer
ForceStandUpForHeavyItems()
void ForceStandUpForHeavyItems (notnull EntityAI item)
-------------— Forces player to stand up when swapping to heavy item ----------------------—
Definition at line 1220 of file dayzplayer.c.
    {
        InventoryLocation il = new InventoryLocation;
        if ( item.IsHeavyBehaviour() && IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_CROUCH))
        {
            HumanCommandMove cm = GetCommand_Move();
            if (cm)
            {
                cm.ForceStance(DayZPlayerConstants.STANCEIDX_ERECT);
            }
        }
    }
References HumanCommandMove::ForceStance(), GetCommand_Move(), and IsPlayerInStance().
Referenced by CommandHandler(), and ForceStandUpForHeavyItemsSwap().
ForceStandUpForHeavyItemsSwap()
void ForceStandUpForHeavyItemsSwap (notnull EntityAI item1, notnull EntityAI item2)
Definition at line 1233 of file dayzplayer.c.
    {
        ForceStandUpForHeavyItems(item1);
        ForceStandUpForHeavyItems(item2);
    }
References ForceStandUpForHeavyItems().
Referenced by ManBase::PredictiveForceSwapEntities(), and ManBase::PredictiveSwapEntities().
GetAnimEventIds()
TIntArray SetDefaultItemInHandsProfile::GetAnimEventIds ()
Definition at line 14 of file dayzplayer.c.
    {
GetAttachmentSoundLookupTable()
DayZPlayerTypeAttachmentSoundLookupTable GetAttachmentSoundLookupTable ()
Definition at line 293 of file dayzplayer.c.
    {
        return m_pAttachmentSoundLookupTable;
    }
References m_pAttachmentSoundLookupTable.
GetBaseAngles()
vector GetBaseAngles ()
helper to blend between cameras ret[0] - up down angle ret[1] - left right angle ret[2] - roll
Definition at line 76 of file dayzplayer.c.
    {
        return  "0 0 0";
    }
GetCameraName()
string GetCameraName ()
Definition at line 81 of file dayzplayer.c.
    {
        return "DayZPlayerCamera";
    }
GetCurrentCamera()
proto native DayZPlayerCamera GetCurrentCamera ()
-------------— camera additional functions ----------------------—
gets current camera
GetCurrentCameraTransform()
proto native void GetCurrentCameraTransform (out vector position, out vector direction, out vector rotation)
gets transform of current player camera
GetCurrentPerItemCameraUD()
proto native int GetCurrentPerItemCameraUD ()
gets current camera
GetCurrentPitch()
float GetCurrentPitch ()
Definition at line 86 of file dayzplayer.c.
    {
        return -1;
    }
GetDayZPlayerType()
proto native DayZPlayerType GetDayZPlayerType ()
returns appropriate DayZPlayerType
Referenced by CommandHandler(), ManBase::GetDefaultHitComponent(), ManBase::GetHitComponentForAI(), GetSlidePoseAngle(), ManBase::GetSuitableFinisherHitComponents(), HandleView(), ManBase::Init(), OnStepEvent(), OverrideSlidePoseAngle(), ProcessAttachmentEvent(), ProcessSoundEvent(), ProcessVoiceEvent(), and ProcessWeaponEvent().
GetDefaultHitComponent()
string GetDefaultHitComponent ()
Definition at line 469 of file dayzplayer.c.
    {
        return m_DefaultHitComponent;
    }
References m_DefaultHitComponent.
Referenced by GetHitComponentForAI(), and DayZCreatureAI::GetHitComponentForAI().
GetDefaultHitPositionComponent()
string GetDefaultHitPositionComponent ()
Definition at line 474 of file dayzplayer.c.
    {
        return m_DefaultHitPositionComponent;
    }
References m_DefaultHitPositionComponent.
Referenced by DayZCreatureAI::DayZAnimal(), DayZInfected::Init(), and ManBase::Init().
GetGlobalSettingsW()
proto native SHumanGlobalSettings GetGlobalSettingsW ()
returns Human global settings for DayZPlayer
GetHeadBoneIdx()
proto native int GetHeadBoneIdx ()
GetHitComponentForAI()
string GetHitComponentForAI ()
Definition at line 457 of file dayzplayer.c.
    {
        string hitComp;
        if (DayZAIHitComponentHelpers.SelectMostProbableHitComponent(m_HitComponentsForAI, hitComp))
        {
            return hitComp;
        }
        return GetDefaultHitComponent();
    }
References GetDefaultHitComponent(), m_HitComponentsForAI, and DayZAIHitComponentHelpers::SelectMostProbableHitComponent().
GetInstanceType()
proto native DayZPlayerInstanceType GetInstanceType ()
Referenced by ManBase::CheckForBurlap(), ManBase::CheckLiftWeapon(), ManBase::ClearInventory(), CommandHandler(), ManBase::CommandHandler(), ManBase::EOnFrame(), ManBase::EOnPostFrame(), ManBase::GetCraftingRecipeID(), HandleWeapons(), ManBase::HideClothing(), ManBase::Message(), ManBase::NeedInventoryJunctureFromServer(), ManBase::OnCommandHandlerTick(), ManBase::OnQuickBarContinuousUseEnd(), ManBase::OnQuickBarContinuousUseStart(), ManBase::OnQuickBarSingleUse(), ManBase::OnRPC(), ManBase::OnSelectPlayer(), OnSoundEvent(), ManBase::OnSpawnedFromConsole(), OnSprintEnd(), OnSprintStart(), ManBase::OnUnconsciousStart(), ManBase::OnUnconsciousStop(), ProccessInputData(), ManBase::ProcessHandDamage(), ManBase::ReloadWeapon(), ManBase::RequestResetADSSync(), ManBase::RequestSoundEventEx(), ManBase::SetCraftingRecipeID(), ManBase::SetHairLevelToHide(), ManBase::SpawnEntityOnGroundPos(), StoreInputForRemotes(), and ManBase::TogglePlacingLocal().
GetMeleeCombatData()
proto native MeleeCombatData GetMeleeCombatData ()
processes melee hit
GetNoiseParams()
NoiseParams GetNoiseParams (int eventId)
Definition at line 298 of file dayzplayercfgsounds.c.
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if(soundEvent.IsValid())
GetNoiseParamsCrouch()
NoiseParams GetNoiseParamsCrouch ()
Definition at line 340 of file dayzplayer.c.
    {
        return m_pNoiseStepCrouch;
    }
References m_pNoiseStepCrouch.
GetNoiseParamsLandHeavy()
NoiseParams GetNoiseParamsLandHeavy ()
Definition at line 355 of file dayzplayer.c.
    {
        return m_pNoiseLandHeavy;
    }
References m_pNoiseLandHeavy.
GetNoiseParamsLandLight()
NoiseParams GetNoiseParamsLandLight ()
Definition at line 350 of file dayzplayer.c.
    {
        return m_pNoiseLandLight;
    }
References m_pNoiseLandLight.
GetNoiseParamsProne()
NoiseParams GetNoiseParamsProne ()
Definition at line 345 of file dayzplayer.c.
    {
        return m_pNoiseStepProne;
    }
References m_pNoiseStepProne.
GetNoiseParamsShout()
NoiseParams GetNoiseParamsShout ()
Definition at line 370 of file dayzplayer.c.
    {
        return m_pNoiseShout;
    }
References m_pNoiseShout.
GetNoiseParamsStand()
NoiseParams GetNoiseParamsStand ()
Definition at line 335 of file dayzplayer.c.
    {
        return m_pNoiseStepStand;
    }
References m_pNoiseStepStand.
GetNoiseParamsTalk()
NoiseParams GetNoiseParamsTalk ()
Definition at line 365 of file dayzplayer.c.
    {
        return m_pNoiseTalk;
    }
References m_pNoiseTalk.
GetNoiseParamsWhisper()
NoiseParams GetNoiseParamsWhisper ()
Definition at line 360 of file dayzplayer.c.
    {
        return m_pNoiseWhisper;
    }
References m_pNoiseWhisper.
GetSoundBuilder() [1/3]
class DayZPlayerTypeStepSoundLookupTable GetSoundBuilder (int eventId, int parameterHash)
Definition at line 108 of file dayzplayer.c.
    {
        return null;
    }
GetSoundBuilder() [2/3]
SoundObjectBuilder GetSoundBuilder::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
Definition at line 129 of file dayzplayer.c.
    {
        return null;
    }
GetSoundBuilder() [3/3]
SoundObjectBuilder GetSoundEvent::GetSoundBuilder (int eventId, string slotName, int attachmentHash)
Definition at line 150 of file dayzplayer.c.
    {
        return null;
    }
}
GetSoundEvent()
class DayZPlayerTypeAttachmentSoundLookupTable GetSoundEvent (int event_id)
Definition at line 133 of file dayzplayer.c.
    {
        return null;
    }
GetSoundObjectBuilder()
SoundObjectBuilder SetDefaultItemInHandsProfile::GetSoundObjectBuilder ()
Definition at line 9 of file dayzplayer.c.
{
GetSoundTable()
DayZPlayerTypeAnimTable GetSoundTable ()
Definition at line 313 of file dayzplayer.c.
    {
        return m_pSoundTable;
    }
References m_pSoundTable.
GetSoundWeaponEvent()
AnimSoundEvent GetSoundWeaponEvent (int event_id)
Definition at line 420 of file dayzplayer.c.
    {
        for(int i = 0; i < m_animSoundEventsAttack.Count(); i++)
        {
            AnimSoundEvent soundEvent = m_animSoundEventsAttack.Get(i);
            if(soundEvent.m_iID == event_id)
            {
                return soundEvent;
            }
        }
        return NULL;
    }
References m_animSoundEventsAttack.
GetStepSoundLookupTable()
DayZPlayerTypeStepSoundLookupTable GetStepSoundLookupTable ()
Definition at line 283 of file dayzplayer.c.
    {
        return m_pStepSoundLookupTable;
    }
References m_pStepSoundLookupTable.
GetSuitableFinisherHitComponents()
array< string > GetSuitableFinisherHitComponents ()
Definition at line 479 of file dayzplayer.c.
    {
        return m_SuitableFinisherHitComponents;
    }
References m_SuitableFinisherHitComponents.
GetVegetationSounds()
array< ref VegetationSound > GetVegetationSounds ()
Definition at line 330 of file dayzplayer.c.
    {
        return m_pVegetationSounds;
    }
References m_pVegetationSounds.
GetVoiceSoundLookupTable()
DayZPlayerTypeVoiceSoundLookupTable GetVoiceSoundLookupTable ()
Definition at line 303 of file dayzplayer.c.
    {
        return m_pVoiceSoundLookupTable;
    }
References m_pVoiceSoundLookupTable.
HeadingModel()
bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
-------------— heading model ----------------------— updated each tick this can limit / extend player's heading (orientation) behaviour in game
on ladder - do nothing
if it's standing from prone on back
Definition at line 1228 of file dayzplayerimplement.c.
    {
        GetMovementState(m_MovementState);
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_VEHICLE )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_UNCONSCIOUS )
        {
            m_fLastHeadingDiff = 0;
            //pModel.m_iCamMode = DayZPlayerConstants.CAMERAMODE_HEAD;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
#ifdef DEVELOPER
        int actMenuValue = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_TURNSLIDE);
        if (actMenuValue != 0)
        {
            return DayZPlayerImplementHeading.ClampHeading(pDt, pModel, m_fLastHeadingDiff);
        }
#endif
        if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MOVE)
        {
            HumanCommandMove hcm = GetCommand_Move();
            if (hcm.IsStandingFromBack())
            {
                m_fLastHeadingDiff = 0;
                return false;
            }
        }
        HumanItemAccessor hia = GetItemAccessor();
        HumanItemBehaviorCfg hibcfg = hia.GetItemInHandsBehaviourCfg();
        if (hibcfg && hibcfg.m_StanceRotation[m_MovementState.m_iStanceIdx] == DayZPlayerConstants.ROTATION_DISABLE)
        {
            return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
        }
        if ( IsUnconscious() || (GetCommand_Move() && GetCommand_Move().IsLeavingUncon()) )
        {
            return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
        }
        return DayZPlayerImplementHeading.RotateOrient(pDt, pModel, m_fLastHeadingDiff);
    }
References DayZPlayerImplementHeading::ClampHeading(), GetCommand_Move(), GetItemAccessor(), GetMovementState(), DiagMenu::GetValue(), HumanItemAccessor(), IsLeavingUncon(), HumanCommandMove::IsStandingFromBack(), m_fLastHeadingDiff, m_MovementState, HumanItemBehaviorCfg::m_StanceRotation, DayZPlayerImplementHeading::NoHeading(), and DayZPlayerImplementHeading::RotateOrient().
IsCamera3rdRaised()
override bool IsCamera3rdRaised ()
Definition at line 91 of file dayzplayer.c.
    {
        return false;
    }
IsCameraBlending()
proto native bool IsCameraBlending ()
IsEyeZoom()
bool IsEyeZoom ()
returns true if player is using EyeZoom, otherwise false
Definition at line 180 of file dayzplayerimplement.c.
    {
        return m_CameraEyeZoom;
    }
References m_CameraEyeZoom.
IsHoldingBreath()
bool IsHoldingBreath ()
return true if player is trying to hold breah, otherwise false
IsInThirdPerson()
bool IsInThirdPerson ()
return true if player is currently in 3pp, otherwise false
Definition at line 205 of file dayzplayerimplement.c.
    {
        return m_Camera3rdPerson;
    }
References m_Camera3rdPerson.
IsPerformingFBGesture()
bool IsPerformingFBGesture ()
return true if player is currently performing FB gesture, otherwise false
IsPlayerInStance()
bool IsPlayerInStance (int pStanceMask)
-------------— camera additiona functions ----------------------—
returns true if player is currently in one of the stances specified by stance mask IsPlayerInStance(STANCEMASK_ERECT | STANCEMASK_CROUCH) returns true if player is standing or crouching and not raised (aimed) IsPlayerInStance(STANCEMASK_PRONE | STANCEIDX_RAISEDPRONE) returns true if player is in or in prone (both raised or nonraised) IsPlayerInStance(STANCEMASK_ALL) returns true always IsPlayerInStance(STANCEMASK_RAISEDERECT | STANCEMASK_RAISEDCROUCH | STANCEMASK_RAISEDPRONE) returns true if player has raised hands
Definition at line 1182 of file dayzplayer.c.
    {
        HumanMovementState      state = new HumanMovementState;
        GetMovementState(state);
        bool ret = ((1 << state.m_iStanceIdx) & pStanceMask) != 0;
        return ret;
    }
References GetMovementState(), and HumanMovementState::m_iStanceIdx.
Referenced by ManBase::CanRoll(), ForceStandUpForHeavyItems(), HandleView(), and ManBase::OnCommandMoveStart().
IsPlayerSpeaking()
proto native float IsPlayerSpeaking ()
-------------— speaking anim ----------------------—
Check if player is using VoN to speak and return max amplitude from current samples
Referenced by CommandHandler().
IsShootingFromCamera()
bool IsShootingFromCamera ()
return true if shots are fired from camere, otherwise false
Definition at line 185 of file dayzplayerimplement.c.
    {
        return m_IsShootingFromCamera;
    }
References m_IsShootingFromCamera.
LoadSoundWeaponEvent()
void LoadSoundWeaponEvent ()
Definition at line 375 of file dayzplayer.c.
    {
        string cfgPath = "CfgVehicles SurvivorBase AnimEvents SoundWeapon ";
        m_animSoundEventsAttack = new array<ref AnimSoundEvent>;
        int soundCount = GetGame().ConfigGetChildrenCount(cfgPath);
        for(int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(cfgPath, i, soundName);
            string soundPath = cfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if(soundEvent.IsValid())
                m_animSoundEventsAttack.Insert(soundEvent);
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and m_animSoundEventsAttack.
Referenced by DayZPlayerType().
LoadVegetationSounds()
void LoadVegetationSounds ()
Definition at line 393 of file dayzplayer.c.
    {
        m_pVegetationSounds = new array<ref VegetationSound>;
        string vegSoundsCfgPath = "CfgVehicles SurvivorBase VegetationSounds ";
        int vegSoundsCount = GetGame().ConfigGetChildrenCount(vegSoundsCfgPath);
        for (int v = 0; v < vegSoundsCount; ++v)
        {
            string vegSoundParamName;
            GetGame().ConfigGetChildName(vegSoundsCfgPath, v, vegSoundParamName);
            string soundSet = "";
            GetGame().ConfigGetText(vegSoundsCfgPath + vegSoundParamName + " soundSet", soundSet);
            TIntArray animEventIds = new TIntArray;
            GetGame().ConfigGetIntArray(vegSoundsCfgPath + vegSoundParamName + " animEventIds", animEventIds);
            SoundParams soundParams = new SoundParams(soundSet);
            if (soundParams.IsValid() && animEventIds.Count() > 0)
            {
                m_pVegetationSounds.Insert(new VegetationSound(new SoundObjectBuilder(soundParams), animEventIds));
            }
        }
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetIntArray(), CGame::ConfigGetText(), GetGame(), SoundParams::IsValid(), and m_pVegetationSounds.
Referenced by DayZPlayerType().
OnActivate()
void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
virtual callback - called when camera is created
Definition at line 63 of file dayzplayer.c.
    {
    }
OnInputForRemote()
void OnInputForRemote (ParamsReadContext ctx)
Definition at line 1191 of file dayzplayer.c.
{ }
OnInputFromServer()
void OnInputFromServer (ParamsReadContext ctx)
Definition at line 1192 of file dayzplayer.c.
{ }
OnThrowingModeChange()
void OnThrowingModeChange (bool change_to_enabled)
Definition at line 1239 of file dayzplayer.c.
{}
OnUpdate()
override void OnUpdate (float pDt, out DayZPlayerCameraResult pOutResult)
virtual callback - called each frame
basically -> transform up vector (0,1,0) and read x coord -> and set is as roll
prev update
Definition at line 68 of file dayzplayer.c.
    {
    }
ProcessMeleeHit()
proto native void ProcessMeleeHit (InventoryItem pMeleeWeapon, int pMeleeModeIndex, Object pTarget, int pComponentIndex, vector pHitWorldPos)
processes melee hit (uses component index)
ProcessMeleeHitName()
proto native void ProcessMeleeHitName (InventoryItem pMeleeWeapon, int pMeleeModeIndex, Object pTarget, string pComponentName, vector pHitWorldPos)
processes melee hit (uses component name)
Random()
proto native int Random ()
-------------— deterministic random numbers ---------------------—
Random number in range of <0,0xffffffff> - !!! use this only during deterministic simulation (CommandHandler)
Returns
int value in range of <0,0xffffffff>
Random01()
proto native float Random01 ()
Random number in range of <0,1> - !!! use this only during deterministic simulation (CommandHandler)
Returns
float value in range of <0,1>
RandomRange()
proto native float RandomRange (int pRange)
Random number in range of <0,pRange-1> - !!! use this only during deterministic simulation (CommandHandler)
Parameters
pRange upper bounds of random number
Returns
int value in range of <0,pRange-1>
RegisterAttachmentSoundLookupTable()
void RegisterAttachmentSoundLookupTable (DayZPlayerTypeAttachmentSoundLookupTable pASLUT)
Definition at line 288 of file dayzplayer.c.
    {
        m_pAttachmentSoundLookupTable = pASLUT;
    }
References m_pAttachmentSoundLookupTable.
RegisterCameraCreator()
proto native void RegisterCameraCreator (int pCameraID, typename pCameraType)
registers camera creator - camera type => camera type (must be descendant of DayZPlayerCamera)
RegisterCameraOnChangeFn()
proto native void RegisterCameraOnChangeFn (Class pInstance, string pFnName)
registers camera on change function -
RegisterCameraOnChangeFnStatic()
proto native void RegisterCameraOnChangeFnStatic (typename pClass , string pFnName)
registers camera on change function - static function
RegisterHitComponentsForAI()
override void RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
registers default hit compoent for entity
registers default hit position for entity
list of components suitable for melee finisher attacks (used in fight logic)
register hit components that are selected by probability
Definition at line 435 of file dayzplayer.c.
    {
        m_HitComponentsForAI = new array<ref DayZAIHitComponent>;
        m_DefaultHitComponent = "dmgZone_torso";
        m_DefaultHitPositionComponent = "Pelvis";
        m_SuitableFinisherHitComponents = new array<string>;
        m_SuitableFinisherHitComponents.Insert("Head");
        //DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_head", 5); // TMP comment out
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_leftArm", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_torso", 65);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_rightArm", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_leftLeg", 40);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "dmgZone_rightLeg", 40);
    }
References m_DefaultHitComponent, m_DefaultHitPositionComponent, m_HitComponentsForAI, m_SuitableFinisherHitComponents, and DayZAIHitComponentHelpers::RegisterHitComponent().
RegisterParticleEvent()
proto native void RegisterParticleEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnParticleEvent();
RegisterSoundEvent()
proto native void RegisterSoundEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnSoundEvent();
RegisterSoundTable()
void RegisterSoundTable (DayZPlayerTypeAnimTable pST)
Definition at line 308 of file dayzplayer.c.
    {
        m_pSoundTable = pST;
    }
References m_pSoundTable.
RegisterStepEvent()
proto native void RegisterStepEvent (string pEventType, float pFilterTimeout)
calls DayZPlayer.OnStepEvent();
RegisterStepSoundLookupTable()
void RegisterStepSoundLookupTable (DayZPlayerTypeStepSoundLookupTable pSSLUT)
Definition at line 278 of file dayzplayer.c.
    {
        m_pStepSoundLookupTable = pSSLUT;
    }
References m_pStepSoundLookupTable.
RegisterVoiceSoundLookupTable()
void RegisterVoiceSoundLookupTable (DayZPlayerTypeVoiceSoundLookupTable pASLUT)
Definition at line 298 of file dayzplayer.c.
    {
        m_pVoiceSoundLookupTable = pASLUT;
    }
References m_pVoiceSoundLookupTable.
ReleaseNetworkControls()
proto native void ReleaseNetworkControls ()
-------------— release controls ----------------------—
ResetCameraCreators()
proto native void ResetCameraCreators ()
resets camera creators
ResetItemInHandsProfiles()
proto native void ResetItemInHandsProfiles ()
reset profiles
SDayZPlayerHeadingModel()
private void SDayZPlayerHeadingModel ()
cannot be created from script
Definition at line 1012 of file dayzplayer.c.
{}
SendRecoilOffsetZ()
void SendRecoilOffsetZ (float offset)
m_fCamPosOffsetZ info, used to adjust near plane in DayZPlayerCameraIronsights now
Definition at line 108 of file dayzplayer.c.
{};
SendSyncJuncture()
proto native void SendSyncJuncture (int pJunctureID, ParamsWriteContext ctx)
-------------— sync stuff ----------------------—
Referenced by ManBase::ReadLiftWeaponRequest(), ManBase::ResetADSPlayerSync(), and SendCompleteWeaponRaiseJuncture().
SetAimLimits()
proto native void SetAimLimits (float pDown, float pUp, float pLeft, float pRight)
sets aim limits for a player
SetCameraShootParams()
proto native void SetCameraShootParams (float pRayDistance, float pRayRadius, float pMaxAngleCos)
sets aim limits for a player
SetDefaultItemInHandsProfile()
class VegetationSound SetDefaultItemInHandsProfile (string pAnimInstanceName, HumanItemBehaviorCfg pBehaviorCfg)
class that configures static data for DayZPlayer on each mission start DayZPlayerTypeCreate(DayZPlayerType pType) is called - can call methods
SetLookLimits()
proto native void SetLookLimits (float pDown, float pUp, float pLeft, float pRight)
sets look limits for a player
SetVerticalMinimumAimLimit()
proto native void SetVerticalMinimumAimLimit (float value)
sets vertical minimum aim limit for a player
SpawnCameraShake()
void SpawnCameraShake (float strength = 1, float radius = 2, float smoothness = 5, float radius_decay_speed = 6)
Definition at line 96 of file dayzplayer.c.
    {
        SpawnCameraShakeProper(strength, radius, smoothness, radius_decay_speed);//done this way in order to avoid duplicating default params which could cause issues under certain circumstances
    }
References SpawnCameraShakeProper().
SpawnCameraShakeProper()
void SpawnCameraShakeProper (float strength, float radius, float smoothness, float radius_decay_speed)
Definition at line 238 of file dayzplayercamera_base.c.
    {
        m_CameraShake = new CameraShake(strength, radius, smoothness, radius_decay_speed);
    }
References m_CameraShake.
Referenced by SpawnCameraShake().
StoreInputForRemotes()
proto native void StoreInputForRemotes (ParamsWriteContext ctx)
Referenced by ProccessInputData().
UpdateDummyPlayerProxyVisibility()
void UpdateDummyPlayerProxyVisibility (EntityAI shoulder, EntityAI melee)
Definition at line 1199 of file dayzplayer.c.
    {
        /*EntityAI shoulder_item = FindAttachmentBySlotName("Shoulder");
        EntityAI melee_item = FindAttachmentBySlotName("Melee");*/
        bool boo;
        if ( melee )
        {
            boo = melee.IsWeapon();
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_MELEE_RIFLE,boo);
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_MELEE_MELEE,!boo);
        }
        if ( shoulder )
        {
            boo = shoulder.IsWeapon();
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_SHOULDER_RIFLE,boo);
            SetSimpleHiddenSelectionState(SIMPLE_SELECTION_SHOULDER_MELEE,!boo);
        }
    }
References SIMPLE_SELECTION_MELEE_MELEE, SIMPLE_SELECTION_MELEE_RIFLE, SIMPLE_SELECTION_SHOULDER_MELEE, and SIMPLE_SELECTION_SHOULDER_RIFLE.
VegetationSound()
void SetDefaultItemInHandsProfile::VegetationSound (SoundObjectBuilder soundObjectBuilder, TIntArray animEventIds)
Definition at line 3 of file dayzplayer.c.
{
~DayZPlayerCameraResult()
private void DayZPlayerCamera::~DayZPlayerCameraResult ()
cannot be instanced from script (always created from C++)
Definition at line 76 of file dayzplayer.c.
    {
        return  "0 0 0";
~DayZPlayerType()
private void ~DayZPlayerType ()
~SDayZPlayerHeadingModel()
private void ~SDayZPlayerHeadingModel ()
Definition at line 1013 of file dayzplayer.c.
{}
Variable Documentation
m_AnimEventIds
private ref TIntArray m_AnimEventIds
Definition at line 1 of file dayzplayer.c.
m_animSoundEventsAttack
ref array<ref AnimSoundEvent> m_animSoundEventsAttack
Definition at line 565 of file dayzplayer.c.
Referenced by GetSoundWeaponEvent(), and LoadSoundWeaponEvent().
m_bUpdateWhenBlendOut
bool m_bUpdateWhenBlendOut
true - camera is updated when blending to new camera (Ironsights == false)
Definition at line 63 of file dayzplayer.c.
m_CameraTM
vector m_CameraTM[4]
transformation matrix - pos + orient of the camera
Definition at line 52 of file dayzplayer.c.
m_CollisionIgnoreEntity
IEntity m_CollisionIgnoreEntity
ignore entity in 3rd person camera collision solver
Definition at line 68 of file dayzplayer.c.
m_DefaultHitComponent
protected string m_DefaultHitComponent
Definition at line 560 of file dayzplayer.c.
Referenced by GetDefaultHitComponent(), DayZCreatureAI::GetDefaultHitComponent(), IsRefresherSignalingViable(), RegisterHitComponentsForAI(), DayZCreatureAI::RegisterHitComponentsForAI(), and AnimalBase::RegisterHitComponentsForAI().
m_DefaultHitPositionComponent
protected string m_DefaultHitPositionComponent
Definition at line 561 of file dayzplayer.c.
Referenced by GetDefaultHitPositionComponent(), DayZCreatureAI::GetDefaultHitPositionComponent(), IsRefresherSignalingViable(), RegisterHitComponentsForAI(), DayZCreatureAI::RegisterHitComponentsForAI(), and AnimalBase::RegisterHitComponentsForAI().
m_fDistance
float m_fDistance
camera distance (external cameras only)
Definition at line 57 of file dayzplayer.c.
Referenced by DayZPlayerCamera3rdPersonCrouch::DayZPlayerCamera3rdPersonCrouchRaised(), DayZPlayerCamera3rdPersonErc::DayZPlayerCamera3rdPersonErcSpr(), DayZPlayerCamera3rdPersonJump(), DayZPlayerCamera3rdPersonProneBase::DayZPlayerCamera3rdPersonProne(), DayZPlayerCamera3rdPersonProne(), and DayZPlayerCamera3rdPersonVehicle().
m_fFovAbsolute
float m_fFovAbsolute
fov absolute value override - -1.0 default, if set - overrides absolute fov setting
Definition at line 54 of file dayzplayer.c.
Referenced by DayZPlayerCameraBase(), DayZPlayerCameraBase::HoldBreathFOVEffect(), HoldBreathFOVEffect(), and StdFovUpdate().
m_fFovMultiplier
float m_fFovMultiplier
fov multiplier - 1.0 default - used for modifying fov -
Definition at line 53 of file dayzplayer.c.
m_fHeadingAngle
float m_fHeadingAngle
Definition at line 1009 of file dayzplayer.c.
m_fIgnoreParentPitch
float m_fIgnoreParentPitch
1 - resets base transforms pitch
Definition at line 66 of file dayzplayer.c.
m_fIgnoreParentRoll
float m_fIgnoreParentRoll
1 - resets base transforms roll
Definition at line 65 of file dayzplayer.c.
m_fIgnoreParentYaw
float m_fIgnoreParentYaw
1 - resets base transforms yaw
Definition at line 67 of file dayzplayer.c.
m_fInsideCamera
float m_fInsideCamera
0 not used, 1 - pos, 2 - rot, 3 - pos+rot applied as a parent to m_CameraTM, 4 as 3 but cam aligned with Y
0..1 (0 normal lod, 1 inside lod), >0.7 -> inside
Definition at line 62 of file dayzplayer.c.
m_fNearPlane
float m_fNearPlane
nearplane distance
Definition at line 55 of file dayzplayer.c.
m_fOrientationAngle
float m_fOrientationAngle
Definition at line 1008 of file dayzplayer.c.
m_fPositionModelSpace
float m_fPositionModelSpace
0.0 position is in heading space, 1.0 position is in model space
Definition at line 56 of file dayzplayer.c.
m_fShootFromCamera
float m_fShootFromCamera
1(default) - uses shoot from camera (+aiming sway), 0 pure weapon shoot (ironsights == 0)
Definition at line 64 of file dayzplayer.c.
Referenced by AdjustCameraParameters(), and DayZPlayerCameraOptics().
m_fUseHeading
float m_fUseHeading
0..1 (0 uses direct dir returned, 1 uses heading from player)
Definition at line 58 of file dayzplayer.c.
m_HitComponentsForAI
protected ref array<ref DayZAIHitComponent> m_HitComponentsForAI
Melee hit components (AI targeting)
Definition at line 559 of file dayzplayer.c.
Referenced by DayZCreatureAI::DayZAnimal(), GetHitComponentForAI(), DayZCreatureAI::GetHitComponentForAI(), IsRefresherSignalingViable(), RegisterHitComponentsForAI(), DayZCreatureAI::RegisterHitComponentsForAI(), and AnimalBase::RegisterHitComponentsForAI().
m_iCamMode
enum DayZPlayerInstanceType m_iCamMode
m_iCurrentCommandID
int m_iCurrentCommandID
Definition at line 1007 of file dayzplayer.c.
m_iDirectBone
int m_iDirectBone
-1 no bone, >= 0 - bone index camera is bound to, m_CameraTM is offset to the bone
Definition at line 60 of file dayzplayer.c.
m_iDirectBoneMode
int m_iDirectBoneMode
Definition at line 61 of file dayzplayer.c.
m_pAttachmentSoundLookupTable
ref DayZPlayerTypeAttachmentSoundLookupTable m_pAttachmentSoundLookupTable
Definition at line 541 of file dayzplayer.c.
Referenced by GetAttachmentSoundLookupTable(), and RegisterAttachmentSoundLookupTable().
m_pInput
protected HumanInputController m_pInput
human input
Definition at line 105 of file dayzplayer.c.
Referenced by DayZPlayerCameraBase::OnUpdate(), UpdateLRAngle(), UpdateLRAngleLookAt(), UpdateUDAngle(), and DayZPlayerCamera3rdPersonErcRaised::~DayZPlayerCamera3rdPersonErcRaisedMelee().
m_pNoiseLandHeavy
ref NoiseParams m_pNoiseLandHeavy
Definition at line 549 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsLandHeavy().
m_pNoiseLandLight
ref NoiseParams m_pNoiseLandLight
Definition at line 548 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsLandLight().
m_pNoiseShout
ref NoiseParams m_pNoiseShout
Definition at line 554 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsShout().
m_pNoiseStepCrouch
ref NoiseParams m_pNoiseStepCrouch
Definition at line 546 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsCrouch().
m_pNoiseStepProne
ref NoiseParams m_pNoiseStepProne
Definition at line 547 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsProne().
m_pNoiseStepStand
ref NoiseParams m_pNoiseStepStand
Definition at line 545 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsStand().
m_pNoiseTalk
ref NoiseParams m_pNoiseTalk
Definition at line 553 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsTalk().
m_pNoiseWhisper
ref NoiseParams m_pNoiseWhisper
Definition at line 552 of file dayzplayer.c.
Referenced by DayZPlayerType(), and GetNoiseParamsWhisper().
m_pPlayer
protected DayZPlayer m_pPlayer
data
player camera is attached to
Definition at line 104 of file dayzplayer.c.
Referenced by DayZPlayerCameraBase(), GetMovementSpeedVisualCoef(), GetMovementStanceVisualCoef(), DayZPlayerCameraBase::HoldBreathFOVEffect(), HoldBreathFOVEffect(), Init(), InitCameraOnPlayer(), OnActivate(), DayZPlayerCameraBase::OnUpdate(), DayZPlayerCamera3rdPersonErc::OnUpdate(), OnUpdate(), ProcessNoiseComponents(), ProcessVisualComponents(), SetCameraPP(), DayZPlayerCameraBase::SetCameraPP(), SetNVPostprocess(), DayZPlayerCameraBase::SetupSightEntities(), ShowCoefsDbg(), and StdFovUpdate().
m_pSoundTable
ref DayZPlayerTypeAnimTable m_pSoundTable
Definition at line 543 of file dayzplayer.c.
Referenced by GetSoundTable(), and RegisterSoundTable().
m_pStepSoundLookupTable
ref DayZPlayerTypeStepSoundLookupTable m_pStepSoundLookupTable
Definition at line 540 of file dayzplayer.c.
Referenced by GetStepSoundLookupTable(), and RegisterStepSoundLookupTable().
m_pVegetationSounds
ref array<ref VegetationSound> m_pVegetationSounds
Definition at line 556 of file dayzplayer.c.
Referenced by GetVegetationSounds(), and LoadVegetationSounds().
m_pVoiceSoundLookupTable
ref DayZPlayerTypeVoiceSoundLookupTable m_pVoiceSoundLookupTable
Definition at line 542 of file dayzplayer.c.
Referenced by GetVoiceSoundLookupTable(), and RegisterVoiceSoundLookupTable().
m_SoundObjectBuilder
private ref SoundObjectBuilder m_SoundObjectBuilder
Definition at line 0 of file dayzplayer.c.
m_SuitableFinisherHitComponents
protected ref array<string> m_SuitableFinisherHitComponents
Definition at line 563 of file dayzplayer.c.
Referenced by GetSuitableFinisherHitComponents(), and RegisterHitComponentsForAI().
SetDefaultItemInHandsProfile
enum DayZPlayerConstants SetDefaultItemInHandsProfile
SIMPLE_SELECTION_MELEE_MELEE
const int SIMPLE_SELECTION_MELEE_MELEE = 1
Definition at line 1049 of file dayzplayer.c.
Referenced by UpdateDummyPlayerProxyVisibility(), and ManBase::UpdateShoulderProxyVisibility().
SIMPLE_SELECTION_MELEE_RIFLE
class SDayZPlayerAimingModel SIMPLE_SELECTION_MELEE_RIFLE = 0
Referenced by UpdateDummyPlayerProxyVisibility(), and ManBase::UpdateShoulderProxyVisibility().
SIMPLE_SELECTION_SHOULDER_MELEE
const int SIMPLE_SELECTION_SHOULDER_MELEE = 3
Definition at line 1051 of file dayzplayer.c.
Referenced by UpdateDummyPlayerProxyVisibility(), and ManBase::UpdateShoulderProxyVisibility().
SIMPLE_SELECTION_SHOULDER_RIFLE
const int SIMPLE_SELECTION_SHOULDER_RIFLE = 2
Definition at line 1050 of file dayzplayer.c.
Referenced by UpdateDummyPlayerProxyVisibility(), and ManBase::UpdateShoulderProxyVisibility().