DayzKode: P:/scripts/3_game/DayZ/dayzgame.c File Reference
dayzgame.c File Reference
Classes
class ConnectionLost
class CrashSoundSets
class DayZProfilesOptions
class LoadingScreen
class LoginQueueBase
LoginQueue position when using -connect since mission is not created yet.
class LoginTimeBase
LoginTime when using -connect since mission is not created yet.
class UIScriptedMenu
Typedefs
typedef Param3< string, bool, bool > DayZProfilesOption
Functions
void AddVisitedServer (string ip, int port)
void AddVoiceNotification (VONStopSpeakingEventParams vonStartParams)
void CancelLoginQueue ()
void CancelLoginTimeCountdown ()
static bool CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo)
void CheckDialogs ()
void CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType)
void Connect ()
void ConnectFromCLI ()
void ConnectFromJoin (string ip, int port)
void ConnectFromServerBrowser (string ip, int port, string password="")
void ConnectLaunch ()
override string CreateDefaultPlayer ()
void CreateGamepadDisconnectMenu ()
override string CreateRandomPlayer ()
override UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
void CreateTitleScreen ()
void DayZGame ()
void DeferredInit ()
void DelayedMidAirDetonation (float x, float y, float z)
void DeleteGamepadDisconnectMenu ()
void DeleteTitleScreen ()
void DisconnectSessionScript (bool displayJoinError=false)
void EarlyAccessDialog (UIScriptedMenu parent)
void EnterLoginQueue (UIMenuPanel parent)
void EnterLoginTime (UIMenuPanel parent)
void ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo)
void FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType)
void GamepadCheck ()
Backlit GetBacklit ()
override ScriptCallQueue GetCallQueue (int call_category)
int GetCurrentDisplayLanguageIdx ()
float GetCurrentEVValue ()
string GetDatabaseID ()
DayZGame GetDayZGame ()
override DragQueue GetDragQueue ()
float GetFoodDecayModifier ()
DayZGameState GetGameState ()
bool GetLastVisitedServer (out string ip, out int port)
DayZLoadState GetLoadState ()
string GetMissionFolderPath ()
string GetMissionPath ()
int GetMissionState ()
string GetPlayerGameName ()
float GetPreviousEVValue ()
int GetPreviousGamepad ()
bool GetProfileOption (EDayZProfilesOptions option)
bool GetProfileOptionDefault (EDayZProfilesOptions option)
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap ()
override TimerQueue GetTimerQueue (int call_category)
override ScriptInvoker GetUpdateQueue (int call_category)
float GetUserFOV ()
static float GetUserFOVFromConfig ()
void GlobalsInit ()
void InitCharacterMenuDataInfo (int menudata_count)
void InitNotifications ()
bool IsAimLogEnabled ()
bool IsConnecting ()
bool IsFoodDecayEnabled ()
override bool IsInventoryOpen ()
bool IsLeftCtrlDown ()
bool IsLoading ()
bool IsNewCharacter ()
bool IsStressTest ()
bool IsVisited (string ip, int port)
bool IsWorldWetTempUpdateEnabled ()
void JoinLaunch ()
override TStringArray ListAvailableCharacters ()
void LoadingHide (bool force=false)
void LoadingShow ()
void LoadProgressUpdate (int progressState, float progress, string title)
void LoginTimeCountdown ()
void MainMenuLaunch ()
void MissionLaunch ()
override void OnActivateMessage ()
override void OnAfterCreate ()
override void OnDeactivateMessage ()
override void OnDeviceReset ()
override void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
void OnGameplayDataHandlerLoad ()
override bool OnInitialize ()
override void OnKeyPress (int key)
override void OnKeyRelease (int key)
void OnLoginTimeEvent (int loginTime)
override void OnMouseButtonPress (int button)
override void OnMouseButtonRelease (int button)
void OnMPConnectionLostEvent (int duration)
override void OnPostUpdate (bool doSim, float timeslice)
void OnPreloadEvent (vector pos)
void OnRespawnEvent (int time)
override void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
override void OnUpdate (bool doSim, float timeslice)
void PartyLaunch ()
void RefreshCurrentServerInfo ()
void RegisterProfilesOptions ()
void ReloadMission ()
void RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams)
static bool ReportModded ()
void ResetProfileOptions ()
void SelectGamepad ()
void SelectUser (int gamepad=-1)
void SetConnecting (bool value)
Returns true when connecting to server.
void SetDatabaseID (string id)
void SetEVValue (float value)
void SetGameState (DayZGameState state)
void SetKeyboardHandle (UIScriptedMenu handler)
void SetLoadState (DayZLoadState state)
void SetMissionPath (string path)
Called from C++.
void SetMissionState (int state)
void SetNewCharacter (bool state)
void SetPlayerGameName (string name)
void SetPreviousGamepad (int gamepad)
void SetProfileOption (EDayZProfilesOptions option, bool value)
void SetUserFOV (float pFov)
bool ShouldShowControllerDisconnect ()
void StoreLoginDataPrepare ()
void TryConnect ()
void UpdateLoginQueue (float timeslice)
void UpdateVoiceLevel (int level)
private void ~DayZGame ()
Variables
class DayZProfilesOptions CONNECT
class DayZProfilesOptions CONNECT_CONTROLLER_SELECT
class DayZProfilesOptions CONNECT_START
class DayZProfilesOptions CONNECT_USER_SELECT
class DayZProfilesOptions CONNECTING
static ref ScriptInvoker Event_OnRPC = new ScriptInvoker()
DayZGame g_Game
class DayZProfilesOptions JOIN
class DayZProfilesOptions JOIN_CONTROLLER_SELECT
class DayZProfilesOptions JOIN_START
class DayZProfilesOptions JOIN_USER_SELECT
private bool m_AimLoggingEnabled
static ref AmmoCamParams m_AmmoShakeParams = new AmmoCamParams()
private ref EffectSound m_ArtySound
private ref Backlit m_Backlit
private ref ScriptCallQueue m_callQueue [CALL_CATEGORY_COUNT]
private ref array< string > m_CharClassNames = new array<string>()
protected string m_ConnectAddress
private bool m_ConnectFromJoin
private ref ConnectionLost m_connectionLost
protected string m_ConnectPassword
protected int m_ConnectPort
private ref EffectSound m_CrashSound
protected string m_DatabaseID
private ref DayZProfilesOptions m_DayZProfileOptions
private ref DragQueue m_dragQueue
private bool m_early_access_dialog_accepted
float m_EVValue = 0
protected bool m_FirstConnect = true
private float m_FoodDecayModifier
protected ref Widget m_GamepadDisconnectMenu
protected DayZGameState m_GameState
protected ref Widget m_IntroMenu
private bool m_IsConnecting
private bool m_IsCtrlHolding
private bool m_IsFoodDecayEnabled = true
private bool m_IsLeftAltHolding
private bool m_IsNewCharacter
private bool m_IsRightAltHolding
private bool m_IsStressTest
private bool m_IsWinHolding
private bool m_IsWorldWetTempUpdateEnabled = true
private UIScriptedMenu m_keyboard_handler
ref LoadingScreen m_loading
protected DayZLoadState m_LoadState
private ref LoginQueueBase m_LoginQueue
private int m_LoginTime
private ref LoginTimeBase m_LoginTimeScreen
private ScriptModule m_mission_module
private string m_MissionFolderPath
private string m_MissionPath
private int m_MissionState
static ref NoiseParams m_NoiseParams = new NoiseParams()
protected ref NotificationUI m_Notifications
int m_OriginalCharactersCount
private string m_PlayerName
protected int m_PrevBlur
float m_PreviousEVValue
private int m_PreviousGamepad
static bool m_ReportModded
private bool m_ShouldShowControllerDisconnect
private ref TimerQueue m_timerQueue [CALL_CATEGORY_COUNT]
private ref ScriptInvoker m_updateQueue [CALL_CATEGORY_COUNT]
private float m_UserFOV
protected ref TStringArray m_Visited
float m_volume_music
float m_volume_radio
float m_volume_sound
float m_volume_speechEX
float m_volume_VOIP
class DayZProfilesOptions MAIN_MENU
class DayZProfilesOptions MAIN_MENU_CONTROLLER_SELECT
class DayZProfilesOptions MAIN_MENU_START
class DayZProfilesOptions MAIN_MENU_USER_SELECT
protected const int MAX_VISITED = 50
private const int MIN_ARTY_SOUND_RANGE = 300
class DayZProfilesOptions MISSION_START
const int MISSION_STATE_FINNISH = 2
const int MISSION_STATE_GAME = 1
class DayZProfilesOptions MISSION_STATE_MAINMENU = 0
class DayZProfilesOptions MISSION_USER_SELECT
class DayZProfilesOptions PARTY
class DayZProfilesOptions PARTY_CONTROLLER_SELECT
class DayZProfilesOptions PARTY_START
class DayZProfilesOptions PARTY_USER_SELECT
class DayZProfilesOptions UNDEFINED
Typedef Documentation
DayZProfilesOption
typedef Param3<string, bool, bool> DayZProfilesOption
Definition at line 591 of file dayzgame.c.
Function Documentation
AddVisitedServer()
void AddVisitedServer (string ip, int port)
Definition at line 2240 of file dayzgame.c.
    {
        string uid = ip + ":" + port;
        if( m_Visited )
        {
            int pos = m_Visited.Find( uid );
            if( pos < 0 )
            {
                if( m_Visited.Count() == MAX_VISITED )
                    m_Visited.Remove( 0 );
                m_Visited.Insert( uid );
            }
            else
            {
                // if item is not saved as last server, move it
                if( pos != ( m_Visited.Count() - 1 ))
                {
                    m_Visited.Remove( pos );
                    m_Visited.Insert( uid );
                }
            }
            SetProfileStringList( "SB_Visited", m_Visited );
            SaveProfile();
        }
    }
References m_Visited, MAX_VISITED, CGame::SaveProfile(), and CGame::SetProfileStringList().
Referenced by OnEvent().
AddVoiceNotification()
void AddVoiceNotification (VONStopSpeakingEventParams vonStartParams)
Definition at line 1410 of file dayzgame.c.
    {
        m_Notifications.AddVoiceNotification(vonStartParams.param2, vonStartParams.param1);
    }
References NotificationUI::AddVoiceNotification(), and m_Notifications.
CancelLoginQueue()
void CancelLoginQueue ()
Definition at line 1117 of file dayzgame.c.
    {
        if (m_LoginQueue)
        {
            if (m_LoginQueue.IsStatic())
            {
                m_LoginQueue.Hide();
                delete m_LoginQueue;
            }
            else
            {
                m_LoginQueue.Close();
            }
        }
    }
References m_LoginQueue.
Referenced by OnLoginTimeEvent().
CancelLoginTimeCountdown()
void CancelLoginTimeCountdown ()
Definition at line 1133 of file dayzgame.c.
    {
        GetCallQueue(CALL_CATEGORY_SYSTEM).Remove(this.LoginTimeCountdown);
        if (m_LoginTimeScreen)
        {
            if (m_LoginTimeScreen.IsStatic())
            {
                m_LoginTimeScreen.Hide();
                delete m_LoginTimeScreen;
            }
            else
            {
                m_LoginTimeScreen.Close();
            }
        }
    }
References CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), LoginTimeCountdown(), m_LoginTimeScreen, and ScriptCallQueue::Remove().
Referenced by LoginTimeCountdown(), OnEvent(), and OnPreloadEvent().
CheckAmmoCompability()
static bool CheckAmmoCompability (EntityAI weaponInHand, EntityAI ammo) static
Definition at line 3077 of file dayzgame.c.
    {
        TStringArray ammo_names = new TStringArray;                                     // Array of ammo types (their name) that can be used with weapon in hand
        string cfg_path = "CfgWeapons " + weaponInHand.GetType() + " chamberableFrom";  // Create config path
        GetGame().ConfigGetTextArray(cfg_path, ammo_names);                             // Get ammo types
        foreach (string ammo_name : ammo_names)             // for every ammo in ammo string compare passed ammo
        {
            if(ammo.GetType() == ammo_name)
            {
                 return true;
            }
        }
        // if no ammo from the array matches with ammo passed, return false
        return false;
    }
References CGame::ConfigGetTextArray(), and GetGame().
CheckDialogs()
void CheckDialogs ()
Definition at line 2786 of file dayzgame.c.
    {
        #ifndef NO_GUI
        Mission mission = GetMission();
        if (mission && !m_loading.IsLoading() && GetUIManager().IsDialogQueued())
        {
            mission.Pause();
            GetUIManager().ShowQueuedDialog();
        }
        #endif
    }
References CGame::GetMission(), CGame::GetUIManager(), LoadingScreen::IsLoading(), m_loading, mission, Mission::Pause(), and UIManager::ShowQueuedDialog().
CloseCombatEffects()
void CloseCombatEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, bool isWater, string ammoType)
Definition at line 2997 of file dayzgame.c.
    {
        #ifndef SERVER
        // if local player was hit
        Object player = GetPlayer();
        if (directHit && player && directHit == player)
        {
            player.OnPlayerRecievedHit();
        }
        ImpactMaterials.EvaluateImpactEffect(directHit, componentIndex, surface, pos, ImpactTypes.MELEE, Vector(Math.RandomFloat(-1,1), Math.RandomFloat(-1,1), Math.RandomFloat(-1,1)), "0 0 0", "0 0 0", "0 0 0", false, ammoType, isWater);
        #endif
        // add hit noise
        if ( IsServer() )
        {
            //NoiseParams npar = new NoiseParams();
            m_NoiseParams.LoadFromPath("cfgAmmo " + ammoType + " NoiseHit");
            float surfaceCoef = SurfaceGetNoiseMultiplier(directHit, pos, componentIndex);
            GetNoiseSystem().AddNoisePos(EntityAI.Cast(source), pos, m_NoiseParams, surfaceCoef);
        }
    }
References NoiseSystem::AddNoisePos(), CGame::GetNoiseSystem(), CGame::GetPlayer(), CGame::IsServer(), m_NoiseParams, Math::RandomFloat(), CGame::SurfaceGetNoiseMultiplier(), and Vector().
Connect()
void Connect ()
Definition at line 2286 of file dayzgame.c.
    {
        SetConnecting(true);
        DeleteTitleScreen();
        string addr;
        int port;
        if ( GetHostAddress( addr, port ) )
        {
            if ( m_ConnectAddress == addr && m_ConnectPort == port )
                return;
        }
        if ( Connect( GetUIManager().GetMenu(), m_ConnectAddress, m_ConnectPort, m_ConnectPassword ) != 0 )
            DisconnectSessionScript(true);
    }
References Connect(), DeleteTitleScreen(), DisconnectSessionScript(), CGame::GetHostAddress(), CGame::GetUIManager(), m_ConnectAddress, m_ConnectPassword, m_ConnectPort, and SetConnecting().
Referenced by Connect(), ConnectFromCLI(), ConnectFromJoin(), and TryConnect().
ConnectFromCLI()
void ConnectFromCLI ()
Definition at line 2351 of file dayzgame.c.
    {
        string port;
        if ( GetCLIParam("connect", m_ConnectAddress) )
        {
            GetCLIParam("port", port);
            m_ConnectPort = port.ToInt();
            GetCLIParam("password", m_ConnectPassword);
            m_ConnectFromJoin = false;
            Connect();
        }
    }
References Connect(), GetCLIParam(), m_ConnectAddress, m_ConnectFromJoin, m_ConnectPassword, m_ConnectPort, and string::ToInt().
Referenced by ConnectLaunch(), and TryConnect().
ConnectFromJoin()
void ConnectFromJoin (string ip, int port)
Definition at line 2343 of file dayzgame.c.
    {
        m_ConnectAddress    = ip;
        m_ConnectPort       = port;
        m_ConnectFromJoin   = true;
        Connect();
    }
References Connect(), m_ConnectAddress, m_ConnectFromJoin, and m_ConnectPort.
ConnectFromServerBrowser()
void ConnectFromServerBrowser (string ip, int port, string password = "")
Definition at line 2334 of file dayzgame.c.
    {
        m_ConnectAddress    = ip;
        m_ConnectPort       = port;
        m_ConnectPassword   = password;
        m_ConnectFromJoin   = false;
        OnlineServices.LoadMPPrivilege();
    }
References OnlineServices::LoadMPPrivilege(), m_ConnectAddress, m_ConnectFromJoin, m_ConnectPassword, and m_ConnectPort.
ConnectLaunch()
void ConnectLaunch ()
Definition at line 1866 of file dayzgame.c.
    {
        BiosUserManager user_manager = GetUserManager();
        if ( user_manager.GetTitleInitiator() )
        {
            user_manager.SelectUserEx( user_manager.GetTitleInitiator() );
        }
        SetGameState( DayZGameState.CONNECT );
        SetLoadState( DayZLoadState.CONNECT_START );
        #ifndef PLATFORM_WINDOWS
            #ifdef PLATFORM_CONSOLE
                CreateTitleScreen();
                GamepadCheck();
            #endif
        #else
            ConnectFromCLI();
        #endif
    }
References ConnectFromCLI(), CreateTitleScreen(), GamepadCheck(), BiosUserManager::GetTitleInitiator(), CGame::GetUserManager(), BiosUserManager::SelectUserEx(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
CreateDefaultPlayer()
override string CreateDefaultPlayer ()
Definition at line 2861 of file dayzgame.c.
    {
        if ( m_CharClassNames.Count() > 0 )
            return m_CharClassNames[0];
        else
            return "";
    }
References m_CharClassNames.
CreateGamepadDisconnectMenu()
void CreateGamepadDisconnectMenu ()
Definition at line 1794 of file dayzgame.c.
    {
        if (m_GamepadDisconnectMenu)
        {
            return;
        }
        bool canBeCreated = m_GameState != DayZGameState.IN_GAME && !GetInput().IsEnabledMouseAndKeyboard();
        canBeCreated = canBeCreated || (m_GameState == DayZGameState.IN_GAME && (!GetWorld().IsMouseAndKeyboardEnabledOnServer() || (GetWorld().IsMouseAndKeyboardEnabledOnServer() && !GetInput().IsEnabledMouseAndKeyboard())));
        if (canBeCreated)
        {
            PPERequesterBank.GetRequester(PPERequester_ControllerDisconnectBlur).Start();
            m_GamepadDisconnectMenu = GetWorkspace().CreateWidgets("gui/layouts/xbox/day_z_gamepad_connect.layout");
            RichTextWidget text_widget = RichTextWidget.Cast( m_GamepadDisconnectMenu.FindAnyWidget("Text") );
            TextWidget caption_widget = TextWidget.Cast( m_GamepadDisconnectMenu.FindAnyWidget("Caption") );
            if (text_widget)
            {
                string text = Widget.TranslateString( "#console_reconect" );
                #ifdef PLATFORM_XBOX
                    text_widget.SetText( string.Format( text, "<image set=\"xbox_buttons\" name=\"A\" />" ) );
                    caption_widget.SetText("#STR_TitleScreenLayout_Caption0");
                #endif
                #ifdef PLATFORM_PS4
                    string confirm = "cross";
                    if( GetInput().GetEnterButton() == GamepadButton.A )
                    {
                        confirm = "cross";
                    }
                    else
                    {
                        confirm = "circle";
                    }
                    text_widget.SetText( string.Format( text, "<image set=\"playstation_buttons\" name=\"" + confirm + "\" />" ) );
                    caption_widget.SetText("#ps4_STR_TitleScreenLayout_Caption0");
                #endif
            }
            #ifdef PLATFORM_XBOX
                GetInput().IdentifyGamepad(GetInput().GetEnterButton());
            #endif
            GetMission().AddActiveInputExcludes({"gamepaddisconnect"});
        }
        m_ShouldShowControllerDisconnect = true;
    }
References Mission::AddActiveInputExcludes(), WorkspaceWidget::CreateWidgets(), CGame::GetInput(), CGame::GetMission(), CGame::GetWorkspace(), CGame::GetWorld(), Input::IdentifyGamepad(), Input::IsEnabledMouseAndKeyboard(), World::IsMouseAndKeyboardEnabledOnServer(), m_GamepadDisconnectMenu, m_GameState, and m_ShouldShowControllerDisconnect.
Referenced by LoadingHide(), and OnEvent().
CreateRandomPlayer()
override string CreateRandomPlayer ()
Definition at line 2870 of file dayzgame.c.
    {
        return m_CharClassNames.GetRandomElement();
    }
References m_CharClassNames.
CreateScriptedMenu()
override UIScriptedMenu CreateScriptedMenu (int id)
create custom main menu part (submenu)
Definition at line 1095 of file dayzgame.c.
    {
    #ifndef NO_GUI
        Mission mission = GetMission();
        if (mission)
        {
            return mission.CreateScriptedMenu(id);
        }
    #endif
        return NULL;
    }
References Mission::CreateScriptedMenu(), CGame::GetMission(), and mission.
Referenced by MissionBase::InitInventory().
CreateTitleScreen()
void CreateTitleScreen ()
Definition at line 1741 of file dayzgame.c.
    {
        DeleteTitleScreen();
        m_IntroMenu = GetWorkspace().CreateWidgets("gui/layouts/xbox/day_z_title_screen.layout");
        RichTextWidget text_widget = RichTextWidget.Cast( m_IntroMenu.FindAnyWidget("InputPromptText") );
        m_IntroMenu.FindAnyWidget("notification_root").Show(false);
        if (text_widget)
        {
            string text = Widget.TranslateString( "#console_start_game" );
            #ifdef PLATFORM_XBOX
                BiosUserManager user_manager = GetGame().GetUserManager();
                if( user_manager && user_manager.GetSelectedUser() )
                    text_widget.SetText( string.Format( text, "<image set=\"xbox_buttons\" name=\"A\" />" ) );
                else
                    text_widget.SetText( string.Format( text, "<image set=\"xbox_buttons\" name=\"A\" />" ) );
            #endif
            #ifdef PLATFORM_PS4
                string confirm = "cross";
                if( GetGame().GetInput().GetEnterButton() == GamepadButton.A )
                {
                    confirm = "cross";
                }
                else
                {
                    confirm = "circle";
                }
                text_widget.SetText( string.Format( text, "<image set=\"playstation_buttons\" name=\"" + confirm + "\" />" ) );
            #endif
        }
        #ifdef PLATFORM_CONSOLE
        #ifdef PLATFORM_XBOX
        #ifdef BUILD_EXPERIMENTAL
            m_IntroMenu.FindAnyWidget("notification_root").Show(true);
        #endif
        #endif
        #endif
    }
References WorkspaceWidget::CreateWidgets(), DeleteTitleScreen(), GetGame(), CGame::GetInput(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), CGame::GetWorkspace(), and m_IntroMenu.
Referenced by ConnectLaunch(), GamepadCheck(), MissionLaunch(), and OnInitialize().
DayZGame()
void DayZGame ()
Definition at line 791 of file dayzgame.c.
    {
        PPEManagerStatic.CreateManagerStatic();
#ifdef PLATFORM_CONSOLE
        SetMainMenuWorld("MainMenuSceneXbox");
#endif
        m_MissionState = MISSION_STATE_GAME;
        m_keyboard_handler = null;
        #ifdef DEVELOPER
        m_early_access_dialog_accepted = true;
        #endif
        for (int i = 0; i < CALL_CATEGORY_COUNT; i++)
        {
            m_callQueue[i] = new ScriptCallQueue;
            m_updateQueue[i] = new ScriptInvoker;
            m_timerQueue[i] = new TimerQueue;
        }
        m_dragQueue = new DragQueue;
        m_LoginTime          = 0;
        string tmp;
        if ( CommandlineGetParam("stresstest", tmp) )
        {
            m_IsStressTest = true;
        }
        if ( CommandlineGetParam("doAimLogs", tmp) )
        {
            m_AimLoggingEnabled = true;
        }
        /*m_ParamNewMenu= false;
        if ( CommandlineGetParam("enNewMenu", tmp) )
        {
            m_ParamNewMenu = true;
        }*/
        // initialize backlit effects
        m_Backlit = new Backlit();
        m_Backlit.OnInit(this);
        m_ReportModded = GetModToBeReported();
    #ifndef NO_GUI
        if (m_loading == null)
        {
            m_loading = new LoadingScreen(this);
        }
        m_loading.Show();
    #endif
        Debug.Init();
        Component.Init();
        LogTemplates.Init();
        CachedObjectsParams.Init();
        CachedObjectsArrays.Init();
        m_DayZProfileOptions = new DayZProfilesOptions;
        GetCallQueue(CALL_CATEGORY_GUI).Call(DeferredInit);
        GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(GlobalsInit);
        //m_isTileSet = true;
        string path = "cfgVehicles";
        string child_name = "";
        int count = ConfigGetChildrenCount( path );
        for (int p = 0; p < count; ++p)
        {
            ConfigGetChildName( path, p, child_name );
            if (ConfigGetInt(path + " " + child_name + " scope") == 2 && IsKindOf(child_name, "SurvivorBase"))
                m_CharClassNames.Insert(child_name);
        }
        m_IsConnecting = false;
        m_ConnectFromJoin = false;
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_COUNT, CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CGame::CommandlineGetParam(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), PPEManagerStatic::CreateManagerStatic(), DeferredInit(), CGame::GetCallQueue(), CGame::GetModToBeReported(), GlobalsInit(), Component::Init(), Debug::Init(), LogTemplates::Init(), CachedObjectsParams::Init(), CachedObjectsArrays::Init(), CGame::IsKindOf(), m_AimLoggingEnabled, m_Backlit, m_callQueue, m_CharClassNames, m_ConnectFromJoin, m_DayZProfileOptions, m_dragQueue, m_early_access_dialog_accepted, m_IsConnecting, m_IsStressTest, m_keyboard_handler, m_loading, m_LoginTime, m_MissionState, m_ReportModded, m_timerQueue, m_updateQueue, MISSION_STATE_GAME, Backlit::OnInit(), path, CGame::SetMainMenuWorld(), and LoadingScreen::Show().
Referenced by CreateGame(), CGame::IsMissionMainMenu(), CfgGameplayHandler::OnLoaded(), MissionBase::OnMissionFinish(), MissionBase::OnMissionStart(), ItemBase::ProcessDecay(), SyncEvents::RegisterEvents(), UIScriptedMenu::SetPreviewObject(), LoadingScreen::Show(), SimulateDeath(), and ValidateMuzzleArray().
DeferredInit()
void DeferredInit ()
Definition at line 886 of file dayzgame.c.
    {
        GameOptions opt = new GameOptions;
        opt.Initialize();
        RegisterProfilesOptions();
        m_UserFOV = GetUserFOVFromConfig();
        m_volume_sound = GetSoundScene().GetSoundVolume();
        m_volume_speechEX = GetSoundScene().GetSpeechExVolume();
        m_volume_music = GetSoundScene().GetMusicVolume();
        m_volume_VOIP = GetSoundScene().GetVOIPVolume();
        m_volume_radio = GetSoundScene().GetRadioVolume();
        //m_CharacterData = new MenuDefaultCharacterData;
        PPEManagerStatic.GetPPEManager().Init();
        GetMenuDefaultCharacterData();
    }
References CGame::GetMenuDefaultCharacterData(), PPEManagerStatic::GetPPEManager(), CGame::GetSoundScene(), GetUserFOVFromConfig(), GameOptions::Initialize(), m_UserFOV, m_volume_music, m_volume_radio, m_volume_sound, m_volume_speechEX, m_volume_VOIP, and RegisterProfilesOptions().
Referenced by DayZGame().
DelayedMidAirDetonation()
void DelayedMidAirDetonation (float x, float y, float z)
Definition at line 2779 of file dayzgame.c.
    {
        EffectSound artilleryFallSound = SEffectManager.PlaySound( "Artillery_Fall_SoundSet", Vector( x, y, z ) );
        artilleryFallSound.SetAutodestroy( true );
    }
References SEffectManager::PlaySound(), EffectSound::SetAutodestroy(), Vector(), x, and y.
Referenced by OnRPC().
DeleteGamepadDisconnectMenu()
void DeleteGamepadDisconnectMenu ()
Definition at line 1840 of file dayzgame.c.
    {
        PPERequesterBank.GetRequester(PPERequester_ControllerDisconnectBlur).Stop();
        if( m_GamepadDisconnectMenu )
            delete m_GamepadDisconnectMenu;
        if( GetUIManager().IsDialogVisible() )
            GetUIManager().CloseDialog();
        m_ShouldShowControllerDisconnect = false;
        GetMission().RemoveActiveInputExcludes({"gamepaddisconnect"},true);
    }
References UIManager::CloseDialog(), CGame::GetMission(), CGame::GetUIManager(), m_GamepadDisconnectMenu, m_ShouldShowControllerDisconnect, and Mission::RemoveActiveInputExcludes().
DeleteTitleScreen()
void DeleteTitleScreen ()
Definition at line 1781 of file dayzgame.c.
    {
        if( m_IntroMenu )
        {
            delete m_IntroMenu;
        }
    }
References m_IntroMenu.
Referenced by Connect(), CreateTitleScreen(), GamepadCheck(), MainMenuLaunch(), and SelectGamepad().
DisconnectSessionScript()
void DisconnectSessionScript (bool displayJoinError = false)
Definition at line 2303 of file dayzgame.c.
    {
        if ( OnlineServices.GetBiosUser() )
            GetGame().GetUserManager().SelectUserEx( OnlineServices.GetBiosUser() );
        if ( g_Game.GetGameState() != DayZGameState.IN_GAME )
        {
            if ( GetGame().GetMission() )
            {
                if ( g_Game.GetGameState() != DayZGameState.MAIN_MENU )
                {
                //  GetGame().GetUIManager().CloseAllSubmenus();
                    GetGame().GetMission().AbortMission();
                    if ( displayJoinError && g_Game.GetGameState() == DayZGameState.JOIN )
                        NotificationSystem.AddNotification( NotificationType.JOIN_FAIL_GET_SESSION, 6 );
                    g_Game.SetGameState( DayZGameState.MAIN_MENU );
                    g_Game.SetLoadState( DayZLoadState.MAIN_MENU_CONTROLLER_SELECT );
                    g_Game.GamepadCheck();
                    return;
                }
            }
            else
            {
                g_Game.MainMenuLaunch();
            }
        }
    }
References Mission::AbortMission(), NotificationSystem::AddNotification(), g_Game, OnlineServices::GetBiosUser(), GetGame(), CGame::GetMission(), CGame::GetUserManager(), and BiosUserManager::SelectUserEx().
Referenced by Connect(), and TryConnect().
EarlyAccessDialog()
void EarlyAccessDialog (UIScriptedMenu parent)
Definition at line 1084 of file dayzgame.c.
    {
        if (!m_early_access_dialog_accepted)
        {
            g_Game.GetUIManager().EnterScriptedMenu(MENU_EARLYACCESS, parent);
            m_early_access_dialog_accepted = true;
        }
    }
References g_Game, m_early_access_dialog_accepted, and MENU_EARLYACCESS.
EnterLoginQueue()
void EnterLoginQueue (UIMenuPanel parent)
Definition at line 1561 of file dayzgame.c.
    {
        m_LoginQueue = LoginQueueBase.Cast( GetUIManager().EnterScriptedMenu(MENU_LOGIN_QUEUE, parent) );
    }
References CGame::GetUIManager(), m_LoginQueue, and MENU_LOGIN_QUEUE.
Referenced by UpdateLoginQueue().
EnterLoginTime()
void EnterLoginTime (UIMenuPanel parent)
Definition at line 1567 of file dayzgame.c.
    {
        m_LoginTimeScreen = LoginTimeBase.Cast( GetUIManager().EnterScriptedMenu(MENU_LOGIN_TIME, parent) );
    }
References CGame::GetUIManager(), m_LoginTimeScreen, and MENU_LOGIN_TIME.
Referenced by OnLoginTimeEvent(), and OnRespawnEvent().
ExplosionEffects()
void ExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
Definition at line 2901 of file dayzgame.c.
    {
        #ifndef SERVER
        if ( source )
        {
            source.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
            if (source && source.ShootsExplosiveAmmo() && ammoType == "Explosion_40mm_Ammo")
            {
                ParticleManager.GetInstance().PlayInWorld(ParticleList.EXPLOSION_LANDMINE, pos);
            }
            float distance_to_player = vector.Distance(pos, GetGame().GetPlayer().GetPosition());
            m_AmmoShakeParams.Load(ammoType);
            if (distance_to_player < m_AmmoShakeParams.m_Radius)
            {
                float dist01 = Math.InverseLerp(0, m_AmmoShakeParams.m_Radius, distance_to_player);
                float modifier = Math.Lerp(m_AmmoShakeParams.m_ModifierClose, m_AmmoShakeParams.m_ModifierFar,dist01);
                /*
                Print(">>>>>>>>>>>>>>>>>>><<<<<<<<<<<<<<<<<<");
                Print(modifier);
                Print(ammoType);
                */
                GetGame().GetPlayer().GetCurrentCamera().SpawnCameraShake(modifier * m_AmmoShakeParams.m_Strength);
            }
        }
        #endif
        /*
        Print("ExplosionEffects");
        Print("##################################");
        Print(directHit);
        Print(componentIndex);
        Print(surface);
        Print(pos);
        Print(surfNormal);
        Print(energyFactor);
        Print(explosionFactor);
        Print(isWater);
        Print(ammoType);
        */
    }
References vector::Distance(), ParticleList::EXPLOSION_LANDMINE, GetGame(), CGame::GetPlayer(), GetPosition, Math::InverseLerp(), Math::Lerp(), AmmoCamParams::Load(), m_AmmoShakeParams, AmmoCamParams::m_ModifierClose, AmmoCamParams::m_ModifierFar, AmmoCamParams::m_Radius, AmmoCamParams::m_Strength, and ParticleManager().
Referenced by ExplosionEffectsEx().
ExplosionEffectsEx()
void ExplosionEffectsEx (Object source, Object directHit, int componentIndex, float energyFactor, float explosionFactor, HitInfo hitInfo)
Definition at line 2882 of file dayzgame.c.
    {
        vector pos = hitInfo.GetPosition();
        string ammoType = hitInfo.GetAmmoType();
        // Call legacy method
        ExplosionEffects(source, directHit, componentIndex, hitInfo.GetSurface(), pos, hitInfo.GetSurfaceNormal(), energyFactor, explosionFactor, hitInfo.IsWater(), ammoType);
        // add explosion noise
        if ( IsServer() )
        {
            //NoiseParams npar = new NoiseParams();
            m_NoiseParams.LoadFromPath(string.Format("cfgAmmo %1 NoiseExplosion", ammoType));
            GetNoiseSystem().AddNoiseTarget(pos, 21, m_NoiseParams, hitInfo.GetSurfaceNoiseMultiplier());
        }
    }
References NoiseSystem::AddNoiseTarget(), ExplosionEffects(), HitInfo::GetAmmoType(), CGame::GetNoiseSystem(), HitInfo::GetPosition(), HitInfo::GetSurface(), HitInfo::GetSurfaceNoiseMultiplier(), HitInfo::GetSurfaceNormal(), CGame::IsServer(), HitInfo::IsWater(), and m_NoiseParams.
FirearmEffects()
void FirearmEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool isWater, bool deflected, string ammoType)
Definition at line 2949 of file dayzgame.c.
    {
        #ifndef SERVER
        // if local player was hit
        Object player = GetPlayer();
        if (directHit && player && directHit == player)
        {
            player.OnPlayerRecievedHit();
            float shake_strength = Math.InverseLerp(0, 500, inSpeed.Length());
            //Print(shake_strenght);
            //GetGame().GetPlayer().GetCurrentCamera().SpawnCameraShake(shake_strength,3,5,30);
            GetGame().GetPlayer().GetCurrentCamera().SpawnCameraShake(shake_strength);
        }
        //Print("Distance: " + vector.Distance(source.GetPosition(),pos));
        ImpactMaterials.EvaluateImpactEffect(directHit, componentIndex, surface, pos, ImpactTypes.UNKNOWN, surfNormal, exitPos, inSpeed, outSpeed, deflected, ammoType, isWater);
        #endif
        if ( IsServer() )
        {
            if (source && source.ShootsExplosiveAmmo() && !deflected && outSpeed == vector.Zero)
            {
                if (ammoType == "Bullet_40mm_ChemGas")
                {
                    GetGame().CreateObject("ContaminatedArea_Local", pos);
                }
                else if (ammoType == "Bullet_40mm_Explosive")
                {
                    DamageSystem.ExplosionDamage(EntityAI.Cast(source), null, "Explosion_40mm_Ammo", pos, DamageType.EXPLOSION);
                }
            }
            // add hit noise
            //NoiseParams npar = new NoiseParams();
            m_NoiseParams.LoadFromPath("cfgAmmo " + ammoType + " NoiseHit");
            float surfaceCoef = SurfaceGetNoiseMultiplier(directHit, pos, componentIndex);
            float coefAdjusted = surfaceCoef * inSpeed.Length() / ConfigGetFloat("cfgAmmo " + ammoType + " initSpeed");
            GetNoiseSystem().AddNoiseTarget(pos, 10, m_NoiseParams, coefAdjusted); // Leave a ping for 5 seconds
            //float noiseCfg = ConfigGetFloat("cfgAmmo " + ammoType + " NoiseHit strength");
            //Print("noiseCfg: " + noiseCfg + "| surface: " + surface + "| surfaceCoef: " + surfaceCoef + "| coefAdjusted: " + coefAdjusted + "| total noise generated: " + (coefAdjusted * noiseCfg * 1.7) );
        }
    }
References NoiseSystem::AddNoiseTarget(), CGame::ConfigGetFloat(), CGame::CreateObject(), GetGame(), CGame::GetNoiseSystem(), CGame::GetPlayer(), Math::InverseLerp(), CGame::IsServer(), vector::Length(), m_NoiseParams, CGame::SurfaceGetNoiseMultiplier(), and vector::Zero.
GamepadCheck()
void GamepadCheck ()
Definition at line 2064 of file dayzgame.c.
    {
#ifndef AUTOTEST
        if ( GetInput().IsActiveGamepadSelected() )
        {
#endif
            DeleteTitleScreen();
            SelectUser();
#ifndef AUTOTEST
        }
        else
        {
    #ifdef PLATFORM_CONSOLE
        #ifndef PLATFORM_WINDOWS
            #ifdef PLATFORM_PS4
            if ( GetUserManager().GetSelectedUser() )
            {
                int gamepad = GetInput().GetUserGamepad( GetUserManager().GetSelectedUser() );
                if (gamepad > -1)
                {
                    SelectUser(gamepad);
                }
                else
                {
                    if (!m_IntroMenu && !(GetGame().GetUIManager().GetMenu() && GetGame().GetUIManager().GetMenu().GetID() == MENU_TITLE_SCREEN))
                        CreateTitleScreen();
                    GetGame().GetInput().IdentifyGamepad(GetGame().GetInput().GetEnterButton());
                }
            }
            else
            #endif
            {
                if ( !m_IntroMenu && !( GetUIManager().GetMenu() && GetUIManager().GetMenu().GetID() == MENU_TITLE_SCREEN ) )
                    CreateTitleScreen();
                GetInput().IdentifyGamepad( GetInput().GetEnterButton() );
            }
        #endif
    #endif
        }
#endif
    }
References CreateTitleScreen(), DeleteTitleScreen(), GetGame(), GetID(), CGame::GetInput(), CGame::GetUIManager(), Input::GetUserGamepad(), CGame::GetUserManager(), Input::IdentifyGamepad(), m_IntroMenu, MENU_TITLE_SCREEN, and SelectUser().
Referenced by ConnectLaunch(), MissionLaunch(), and SelectUser().
GetBacklit()
Backlit GetBacklit ()
Definition at line 1066 of file dayzgame.c.
    {
        return m_Backlit;
    }
References m_Backlit.
GetCallQueue()
override ScriptCallQueue GetCallQueue (int call_category)
Definition at line 971 of file dayzgame.c.
    {
        return m_callQueue[call_category];
    }
References m_callQueue.
GetCurrentDisplayLanguageIdx()
int GetCurrentDisplayLanguageIdx ()
Definition at line 3113 of file dayzgame.c.
    {
        ListOptionsAccess   language_option;
        GameOptions options = new GameOptions();
        language_option = ListOptionsAccess.Cast( options.GetOptionByType( OptionAccessType.AT_OPTIONS_LANGUAGE ) );
        int idx = -1;
        if (language_option)
        {
            idx = language_option.GetIndex();
        }
        return idx;
    }
References GameOptions::GetOptionByType().
GetCurrentEVValue()
float GetCurrentEVValue ()
Definition at line 3103 of file dayzgame.c.
    {
        return m_EVValue;
    }
References m_EVValue.
GetDatabaseID()
string GetDatabaseID ()
Definition at line 1727 of file dayzgame.c.
    {
        return m_DatabaseID;
    }
References m_DatabaseID.
GetDayZGame()
DayZGame GetDayZGame ()
Definition at line 3146 of file dayzgame.c.
{
    return g_Game;
}
References g_Game.
Referenced by PluginBase::ActivateModifier(), ApplyEyeAcco(), DayZPlayerImplementAiming::DbgPrintAimingImplement(), PluginBase::DeactivateModifier(), EffBulletImpactBase::Event_OnStarted(), ManBase::Init(), UIScriptedMenu::Init(), PluginBase::IsModifierLocked(), PluginBase::LockModifier(), MissionBaseWorld::MissionBase(), VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), ManBase::OnCommandSwimFinish(), ManBase::OnCommandSwimStart(), Hit_MeatBones::OnEnterCalculations(), OnEvent(), UIScriptedMenu::OnHide(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), AttachmentCategoriesRow::OnMouseButtonDown(), InventoryItem::OnRightClick(), OnRPC(), ManBase::OnSelectPlayer(), UIScriptedMenu::OnShow(), ManBase::OnStoreLoad(), ManBase::OnStoreSave(), RecoilBase::RecoilBase(), Hud::RefreshVehicleHud(), DayZIntroSceneXbox::SaveCharName(), BetaSound::SaySound(), PluginBase::SendRPCAgents(), PluginBase::SendRPCLevels(), PluginBase::SendRPCMods(), PluginBase::SendRPCModsDetail(), PluginBase::SendRPCStats(), PluginBase::SendRPCStomach(), PluginBase::SendRPCTemp(), ScriptedWidgetEventHandler::SetInteractActionIcon(), Hud::SetStamina(), ActionGetInTransport::Start(), Start(), EnProfilerTests::TestFuncCountData(), PluginBase::Update(), ScriptedWidgetEventHandler::Update(), array::Update(), UIScriptedMenu::Update(), PluginBase::UpdateStatsLocal(), and MissionBaseWorld::~MissionBase().
GetDragQueue()
override DragQueue GetDragQueue ()
Definition at line 986 of file dayzgame.c.
    {
        return m_dragQueue;
    }
References m_dragQueue.
GetFoodDecayModifier()
float GetFoodDecayModifier ()
Definition at line 3137 of file dayzgame.c.
    {
        return m_FoodDecayModifier;
    }
References m_FoodDecayModifier.
Referenced by IsFoodDecayEnabled().
GetGameState()
DayZGameState GetGameState ()
Definition at line 1046 of file dayzgame.c.
    {
        return m_GameState;
    }
References m_GameState.
Referenced by OnEvent(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), and TryConnect().
GetLastVisitedServer()
bool GetLastVisitedServer (out string ip, out int port)
Definition at line 2223 of file dayzgame.c.
    {
        if( m_Visited )
        {
            if( m_Visited.Count() > 0 )
            {
                string uid = m_Visited.Get( m_Visited.Count() - 1 );
                TStringArray output = new TStringArray;
                uid.Split( ":", output );
                ip = output[0];
                port = output[1].ToInt();
                return true;
            }
        }
        return false;
    }
References m_Visited, and string::Split().
GetLoadState()
DayZLoadState GetLoadState ()
Definition at line 1056 of file dayzgame.c.
    {
        return m_LoadState;
    }
References m_LoadState.
Referenced by OnInitialize(), SelectGamepad(), SelectUser(), and TryConnect().
GetMissionFolderPath()
string GetMissionFolderPath ()
Definition at line 966 of file dayzgame.c.
    {
        return m_MissionFolderPath;
    }
References m_MissionFolderPath.
GetMissionPath()
string GetMissionPath ()
Definition at line 961 of file dayzgame.c.
    {
        return m_MissionPath;
    }
References m_MissionPath.
GetMissionState()
int GetMissionState ()
Definition at line 999 of file dayzgame.c.
    {
        return m_MissionState;
    }
References m_MissionState.
GetPlayerGameName()
string GetPlayerGameName ()
Definition at line 3037 of file dayzgame.c.
    {
        return m_PlayerName;
    }
References m_PlayerName.
GetPreviousEVValue()
float GetPreviousEVValue ()
Definition at line 3108 of file dayzgame.c.
    {
        return m_PreviousEVValue;
    }
References m_PreviousEVValue.
GetPreviousGamepad()
int GetPreviousGamepad ()
Definition at line 2059 of file dayzgame.c.
    {
        return m_PreviousGamepad;
    }
References m_PreviousGamepad.
GetProfileOption()
bool GetProfileOption (EDayZProfilesOptions option)
Definition at line 1011 of file dayzgame.c.
    {
        return m_DayZProfileOptions.GetProfileOption(option);
    }
References DayZProfilesOptions::GetProfileOption(), and m_DayZProfileOptions.
GetProfileOptionDefault()
bool GetProfileOptionDefault (EDayZProfilesOptions option)
Definition at line 1016 of file dayzgame.c.
    {
        return m_DayZProfileOptions.GetProfileOptionDefault(option);
    }
References DayZProfilesOptions::GetProfileOptionDefault(), and m_DayZProfileOptions.
GetProfileOptionMap()
map< EDayZProfilesOptions, ref DayZProfilesOption > GetProfileOptionMap ()
Definition at line 1026 of file dayzgame.c.
    {
        return m_DayZProfileOptions.GetProfileOptionMap();
    }
References DayZProfilesOptions::GetProfileOptionMap(), and m_DayZProfileOptions.
GetTimerQueue()
override TimerQueue GetTimerQueue (int call_category)
Definition at line 981 of file dayzgame.c.
    {
        return m_timerQueue[call_category];
    }
References m_timerQueue.
GetUpdateQueue()
override ScriptInvoker GetUpdateQueue (int call_category)
Definition at line 976 of file dayzgame.c.
    {
        return m_updateQueue[call_category];
    }
References m_updateQueue.
Referenced by MainMenuButtonEffect::~MainMenuButtonEffect().
GetUserFOV()
float GetUserFOV ()
Definition at line 3060 of file dayzgame.c.
    {
        return m_UserFOV;
    }
References m_UserFOV.
GetUserFOVFromConfig()
static float GetUserFOVFromConfig () static
Definition at line 3065 of file dayzgame.c.
    {
        GameOptions gameOptions = new GameOptions;
        NumericOptionsAccess noa;
        if ( gameOptions && Class.CastTo(noa,gameOptions.GetOptionByType( OptionAccessType.AT_OPTIONS_FIELD_OF_VIEW )) )
        {
            return noa.ReadValue();
        }
        return 1.0;
    }
References Class::CastTo(), and GameOptions::GetOptionByType().
Referenced by DeferredInit(), and SelectGamepad().
GlobalsInit()
void GlobalsInit ()
Definition at line 905 of file dayzgame.c.
    {
        if ( GetCEApi() )
        {
            m_IsWorldWetTempUpdateEnabled = ( GetCEApi().GetCEGlobalInt( "WorldWetTempUpdate" ) == 1 );
            m_FoodDecayModifier = GetCEApi().GetCEGlobalFloat( "FoodDecay" );
            if ( m_FoodDecayModifier == float.MIN)//check for legacy INT format, if value == float.MIN when read as FLOAT, it is of type INT, so we read it as such bellow
            {
                m_FoodDecayModifier = GetCEApi().GetCEGlobalInt( "FoodDecay" );
            }
            //Print("IsFoodDecayEnabled():" + IsFoodDecayEnabled());
            //Print("m_FoodDecayModifier:" + m_FoodDecayModifier);
        }
    }
References GetCEApi(), m_FoodDecayModifier, m_IsWorldWetTempUpdateEnabled, and MIN.
Referenced by DayZGame().
InitCharacterMenuDataInfo()
void InitCharacterMenuDataInfo (int menudata_count)
Definition at line 3027 of file dayzgame.c.
    {
        m_OriginalCharactersCount = menudata_count;
    }
References m_OriginalCharactersCount.
InitNotifications()
void InitNotifications ()
Definition at line 1708 of file dayzgame.c.
    {
        new NotificationSystem;
        m_Notifications = new NotificationUI;
    }
References m_Notifications.
Referenced by OnInitialize().
IsAimLogEnabled()
bool IsAimLogEnabled ()
Definition at line 1036 of file dayzgame.c.
    {
        return m_AimLoggingEnabled;
    }
References m_AimLoggingEnabled.
Referenced by DayZPlayerImplementAiming::DbgPrintAimingImplement().
IsConnecting()
bool IsConnecting ()
Definition at line 2804 of file dayzgame.c.
    {
        return m_IsConnecting;
    }
References m_IsConnecting.
Referenced by UIScriptedMenu::Update().
IsFoodDecayEnabled()
bool IsFoodDecayEnabled ()
Definition at line 3132 of file dayzgame.c.
    {
        return (GetFoodDecayModifier() != 0);
    }
References GetFoodDecayModifier().
IsInventoryOpen()
override bool IsInventoryOpen ()
Definition at line 1072 of file dayzgame.c.
    {
#ifndef NO_GUI
        if (GetUIManager().FindMenu(MENU_INVENTORY) != NULL)
        {
            return true;
        }
#endif
        return false;
    }
References CGame::GetUIManager(), and MENU_INVENTORY.
Referenced by ActionWorldLiquidActionSwitch::ActionCondition(), ActionManagerClient::FindContextualUserActions(), OnRPC(), InventoryActionHandler::OnUpdate(), MissionBase::OnUpdate(), and ScriptedWidgetEventHandler::Update().
IsLeftCtrlDown()
bool IsLeftCtrlDown ()
Definition at line 2366 of file dayzgame.c.
    {
        return m_IsCtrlHolding;
    }
References m_IsCtrlHolding.
Referenced by VicinitySlotsContainer::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), AttachmentCategoriesRow::OnMouseButtonDown(), and InventoryItem::OnRightClick().
IsLoading()
bool IsLoading ()
Definition at line 2810 of file dayzgame.c.
    {
        if (m_loading && m_loading.IsLoading())
        {
            return true;
        }
        return false;
    }
References LoadingScreen::IsLoading(), and m_loading.
Referenced by LoadingHide().
IsNewCharacter()
bool IsNewCharacter ()
Definition at line 3047 of file dayzgame.c.
    {
        return m_IsNewCharacter;
    }
References m_IsNewCharacter.
IsStressTest()
bool IsStressTest ()
Definition at line 1031 of file dayzgame.c.
    {
        return m_IsStressTest;
    }
References m_IsStressTest.
IsVisited()
bool IsVisited (string ip, int port)
Definition at line 2267 of file dayzgame.c.
    {
        string uid = ip + ":" + port;
        int index = m_Visited.Find( uid );
        return ( index >= 0 );
    }
References m_Visited.
IsWorldWetTempUpdateEnabled()
bool IsWorldWetTempUpdateEnabled ()
Definition at line 3127 of file dayzgame.c.
    {
        return m_IsWorldWetTempUpdateEnabled;
    }
References m_IsWorldWetTempUpdateEnabled.
JoinLaunch()
void JoinLaunch ()
Definition at line 1851 of file dayzgame.c.
    {
        SetGameState( DayZGameState.JOIN );
        SetLoadState( DayZLoadState.JOIN_START );
        #ifdef PLATFORM_CONSOLE
            string join_param;
            if( GetCLIParam("join", join_param) )
            {
                BiosUserManager user_manager = GetUserManager();
                user_manager.ParseJoinAsync( join_param );
            }
        #endif
    }
References GetCLIParam(), CGame::GetUserManager(), BiosUserManager::ParseJoinAsync(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
ListAvailableCharacters()
override TStringArray ListAvailableCharacters ()
Definition at line 2876 of file dayzgame.c.
    {
        return m_CharClassNames;
    }
References m_CharClassNames.
Referenced by MissionBase::OnClientNewEvent().
LoadingHide()
void LoadingHide (bool force = false)
Definition at line 2835 of file dayzgame.c.
    {
        #ifndef NO_GUI
            m_loading.Hide(force);
            // turn the lights back on
            SetEVValue(0);
            #ifdef PLATFORM_CONSOLE
            if( !GetInput().IsActiveGamepadSelected() )
            {
                if( !IsLoading() )
                {
                    if( m_LoadState != DayZLoadState.MAIN_MENU_START && m_LoadState != DayZLoadState.MAIN_MENU_USER_SELECT )
                    {
                        CreateGamepadDisconnectMenu();
                    }
                    #ifdef PLATFORM_XBOX
                    GetInput().IdentifyGamepad( GetInput().GetEnterButton() );
                    #endif
                }
            }
            #endif
        #endif
    }
References CreateGamepadDisconnectMenu(), CGame::GetInput(), LoadingScreen::Hide(), Input::IdentifyGamepad(), IsLoading(), m_loading, m_LoadState, and SetEVValue().
Referenced by OnEvent().
LoadingShow()
void LoadingShow ()
Definition at line 2827 of file dayzgame.c.
    {
        #ifndef NO_GUI
            m_loading.Show();
        #endif
    }
References m_loading, and LoadingScreen::Show().
Referenced by OnEvent().
LoadProgressUpdate()
void LoadProgressUpdate (int progressState, float progress, string title)
Definition at line 1612 of file dayzgame.c.
    {
    #ifndef NO_GUI
        switch(progressState)
        {
        case PROGRESS_START:
            {
            #ifndef NO_GUI
                // get out of the black screen immediately
                GetUIManager().ScreenFadeOut(0);
            #endif
                m_loading.Inc();
                m_loading.SetTitle(title);
            }
            break;
        case PROGRESS_FINISH:
            {
                m_loading.Dec();
            }
            break;
        case PROGRESS_PROGRESS:
            {
                m_loading.SetProgress(progress);
            }
            break;
        case PROGRESS_UPDATE:
            {
                m_loading.SetProgress(0);
            }
            break;
        }
    #endif
    }
References LoadingScreen::Dec(), CGame::GetUIManager(), LoadingScreen::Inc(), m_loading, PROGRESS_FINISH, PROGRESS_PROGRESS, PROGRESS_START, PROGRESS_UPDATE, UIManager::ScreenFadeOut(), LoadingScreen::SetProgress(), and LoadingScreen::SetTitle().
Referenced by OnEvent().
LoginTimeCountdown()
void LoginTimeCountdown ()
Definition at line 1493 of file dayzgame.c.
    {
        // countdown on the login screen
        if (m_LoginTimeScreen)
        {
            if (m_LoginTime > 0)
            {
                m_LoginTimeScreen.SetTime(m_LoginTime);
                m_LoginTime--;
            }
            else
            {
                // stop the call loop
                CancelLoginTimeCountdown();
            }
        }
    }
References CancelLoginTimeCountdown(), m_LoginTime, and m_LoginTimeScreen.
Referenced by CancelLoginTimeCountdown(), OnLoginTimeEvent(), and OnRespawnEvent().
MainMenuLaunch()
void MainMenuLaunch ()
Definition at line 1901 of file dayzgame.c.
    {
        SetGameState( DayZGameState.MAIN_MENU );
        SetLoadState( DayZLoadState.MAIN_MENU_START );
        //#ifdef PLATFORM_CONSOLE
            //StartRandomCutscene("Staroye");
        //#else
            StartRandomCutscene(GetMainMenuWorld());
        //#endif
        DeleteTitleScreen();
    }
References DeleteTitleScreen(), CGame::GetMainMenuWorld(), SetGameState(), SetLoadState(), and CGame::StartRandomCutscene().
Referenced by OnInitialize().
MissionLaunch()
void MissionLaunch ()
Definition at line 1915 of file dayzgame.c.
    {
        BiosUserManager user_manager = GetUserManager();
        if ( user_manager )
        {
            if ( user_manager.GetTitleInitiator() )
            {
                user_manager.SelectUserEx( user_manager.GetTitleInitiator() );
            }
        }
        SetGameState( DayZGameState.IN_GAME );
        SetLoadState( DayZLoadState.MISSION_START );
        #ifndef PLATFORM_WINDOWS
            #ifdef PLATFORM_CONSOLE
                #ifndef DEVELOPER
                    CreateTitleScreen();
                    GamepadCheck();
                    return;
                #endif
            #endif
        #endif
        string mission;
        GetCLIParam("mission", mission);
        PlayMission(mission);
    }
References CreateTitleScreen(), GamepadCheck(), GetCLIParam(), BiosUserManager::GetTitleInitiator(), CGame::GetUserManager(), mission, CGame::PlayMission(), BiosUserManager::SelectUserEx(), SetGameState(), and SetLoadState().
Referenced by OnInitialize().
OnActivateMessage()
override void OnActivateMessage ()
Definition at line 1656 of file dayzgame.c.
    {
    }
OnAfterCreate()
override void OnAfterCreate ()
Definition at line 1650 of file dayzgame.c.
    {
        Math.Randomize( -1 );
    }
References Math::Randomize().
OnDeactivateMessage()
override void OnDeactivateMessage ()
Definition at line 1661 of file dayzgame.c.
    {
    }
OnDeviceReset()
override void OnDeviceReset ()
Definition at line 2466 of file dayzgame.c.
    {
        m_IsCtrlHolding = false;
        m_IsWinHolding = false;
        m_IsLeftAltHolding = false;
        m_IsRightAltHolding  = false;
    }
References m_IsCtrlHolding, m_IsLeftAltHolding, m_IsRightAltHolding, and m_IsWinHolding.
OnEvent()
override void OnEvent (EventType eventTypeId, Param params)
Handles VON-related events.
Parameters
eventTypeId event that fired
params event-specific parameters
Definition at line 1152 of file dayzgame.c.
    {
        string address;
        int port;
        int high, low;
        switch (eventTypeId)
        {
            case StartupEventTypeID:
            {
                #ifndef SERVER
                // Just call it, to create the global instance if it doesn't exist yet
                ParticleManager.GetInstance();
                #endif
                break;
            }
            case MPSessionStartEventTypeID:
            {
                m_FirstConnect = true;
                ClientData.ResetClientData();
                break;
            }
            case MPSessionEndEventTypeID:
            {
                LoadingHide();
                CancelLoginTimeCountdown();
                SetConnecting( false );
                m_FirstConnect = true;
                #ifdef PLATFORM_CONSOLE
                    if ( GetUserManager().GetSelectedUser() )
                    {
                        OnlineServices.LeaveGameplaySession();
                        OnlineServices.ClearCurrentServerInfo();
                        if ( GetGameState() == DayZGameState.IN_GAME )
{
                            SetGameState( DayZGameState.MAIN_MENU );
                            SetLoadState( DayZLoadState.MAIN_MENU_START );
                        }
                    }
                    m_Notifications.ClearVoiceNotifications();
                #endif
                // analytics - disconnected player
                StatsEventDisconnectedData discData = new StatsEventDisconnectedData();
                discData.m_CharacterId = g_Game.GetDatabaseID();
                discData.m_Reason = "quit";
                Analytics.PlayerDisconnected(discData);
                break;
            }
            case MPSessionFailEventTypeID:
            {
                LoadingHide(true);
                SetConnecting( false );
                ProgressAsync.DestroyAllPendingProgresses();
                if ( GetGameState() == DayZGameState.CONNECTING )
                {
                    SetGameState( DayZGameState.MAIN_MENU );
                }
                break;
            }
            case MPSessionPlayerReadyEventTypeID:
            {
                LoadingHide(true);
                ProgressAsync.DestroyAllPendingProgresses();
                SetGameState(DayZGameState.IN_GAME);
                // analytics - spawned
                StatsEventSpawnedData spawnData = new StatsEventSpawnedData();
                spawnData.m_CharacterId = g_Game.GetDatabaseID();
                spawnData.m_Lifetime = 0;
                spawnData.m_Position = vector.Zero;
                if (GetPlayer())
                {
                    spawnData.m_Position = GetPlayer().GetPosition();
                }
                spawnData.m_DaytimeHour = 0;
                spawnData.m_Population = 0;
                Analytics.PlayerSpawned(spawnData);
                #ifdef PLATFORM_CONSOLE
                m_Notifications.ClearVoiceNotifications();
                OnlineServices.SetMultiplayState(true);
                #endif
                if (m_FirstConnect)
                {
                    m_FirstConnect = false;
                    if (GetHostAddress(address, port))
                    {
                        AddVisitedServer(address, port);
                    }
                    #ifdef PLATFORM_CONSOLE
                        #ifndef PLATFORM_WINDOWS // if app is not on Windows with -XBOX parameter
                            if (null != GetUserManager().GetSelectedUser())
{
                                OnlineServices.EnterGameplaySession();
                                OnlineServices.LoadVoicePrivilege();
                            }
                        #endif
                    #endif
                }
                if (m_ShouldShowControllerDisconnect)
                    CreateGamepadDisconnectMenu();
                break;
            }
            case MPConnectionLostEventTypeID:
            {
                MPConnectionLostEventParams conLost_params;
                if (Class.CastTo(conLost_params, params))
                {
                    int duration = conLost_params.param1;
                    OnMPConnectionLostEvent(duration);
                    #ifdef PLATFORM_PS4
                    //PSN Set multiplay state
                    if ( duration < 0 && GetGameState() == DayZGameState.IN_GAME )
                    {
                        OnlineServices.SetMultiplayState( true );
                        //Print("=== PLATFORM_PS4 - SetMultiplayState ACTIVE [MPConnectionLostEventTypeID]");
                    }
                    else
                    {
                        OnlineServices.SetMultiplayState( false );
                        //Print("=== PLATFORM_PS4 - SetMultiplayState NOT ACTIVE [MPConnectionLostEventTypeID]");
                    }
                    #endif
                }
                break;
            }
            case WorldCleaupEventTypeID:
            {
                LoadingShow();
                break;
            }
            case DialogQueuedEventTypeID:
            {
                GetCallQueue(CALL_CATEGORY_SYSTEM).Call(g_Game.CheckDialogs);
                break;
            }
            case ChatMessageEventTypeID:
            {
                ChatMessageEventParams chat_params;
                if (Class.CastTo(chat_params, params))
                {
                }
                break;
            }
            case ProgressEventTypeID:
            {
                ProgressEventParams prog_params;
                if (Class.CastTo(prog_params, params))
                    LoadProgressUpdate(prog_params.param1, prog_params.param2, prog_params.param3);
                break;
            }
            case LoginTimeEventTypeID:
            {
                LoginTimeEventParams loginTimeParams;
                if (Class.CastTo(loginTimeParams, params))
                {
                    OnLoginTimeEvent(loginTimeParams.param1);
                }
                break;
            }
            case RespawnEventTypeID:
            {
                RespawnEventParams respawnParams;
                if (Class.CastTo(respawnParams, params))
                {
                    OnRespawnEvent(respawnParams.param1);
                }
                break;
            }
            case PreloadEventTypeID:
            {
                PreloadEventParams preloadParams;
                if (Class.CastTo(preloadParams, params))
                {
                    OnPreloadEvent(preloadParams.param1);
                }
                break;
            }
            case LogoutEventTypeID:
            {
                LogoutEventParams logoutParams;
                if (Class.CastTo(logoutParams, params))
                {
                    GetCallQueue(CALL_CATEGORY_GUI).Call( GetMission().StartLogoutMenu, logoutParams.param1 );
                }
                break;
            }
            case LoginStatusEventTypeID:
            {
                LoginStatusEventParams loginStatusParams;
                Class.CastTo(loginStatusParams, params);
                string msg1 = loginStatusParams.param1;
                string msg2 = loginStatusParams.param2;
                string finalMsg;
                // write either to login time screen or loading screen
                if (m_LoginTimeScreen)
                {
                    finalMsg = msg1;
                    // login time screen supports two lines
                    if (msg2.Length() > 0)
                        finalMsg += "\n" + msg2;
                    m_LoginTimeScreen.SetStatus(finalMsg);
                }
                else if (m_loading)
                {
                    // loading only one line, but it's a long one
                    finalMsg = msg1 + " " + msg2;
                    m_loading.SetStatus(finalMsg);
                }
                break;
            }
            case ConnectingAbortEventTypeID:
            {
                g_Game.SetGameState(DayZGameState.MAIN_MENU);
                SetConnecting(false);
                if (m_ConnectFromJoin)
                {
                    m_ConnectFromJoin = false;
                    AbortMission();
                }
                break;
            }
            case DLCOwnerShipFailedEventTypeID:
            {
                DLCOwnerShipFailedParams dlcParams;
                if (Class.CastTo(dlcParams, params))
                {
                    Print( "### DLC Ownership failed !!! Map: " + dlcParams.param1 );
                }
                break;
            }
        }
        VONManager.GetInstance().OnEvent(eventTypeId, params);
        Mission mission = GetMission();
        if (mission)
        {
            mission.OnEvent(eventTypeId, params);
        }
        ErrorModuleHandler emh = ErrorModuleHandler.GetInstance();
        if (emh)
            emh.OnEvent(eventTypeId, params);
    }
References CGame::AbortMission(), AddVisitedServer(), ScriptCallQueue::Call(), CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, CancelLoginTimeCountdown(), Class::CastTo(), OnlineServices::ClearCurrentServerInfo(), NotificationUI::ClearVoiceNotifications(), CreateGamepadDisconnectMenu(), ProgressAsync::DestroyAllPendingProgresses(), OnlineServices::EnterGameplaySession(), g_Game, CGame::GetCallQueue(), GetGameState(), CGame::GetHostAddress(), ErrorModuleHandler::GetInstance(), VONManager::GetInstance(), CGame::GetMission(), CGame::GetPlayer(), CGame::GetUserManager(), OnlineServices::LeaveGameplaySession(), string::Length(), LoadingHide(), LoadingShow(), LoadProgressUpdate(), OnlineServices::LoadVoicePrivilege(), StatsEventDisconnectedData::m_CharacterId, StatsEventSpawnedData::m_CharacterId, m_ConnectFromJoin, StatsEventSpawnedData::m_DaytimeHour, m_FirstConnect, StatsEventSpawnedData::m_Lifetime, m_loading, m_LoginTimeScreen, m_Notifications, StatsEventSpawnedData::m_Population, StatsEventSpawnedData::m_Position, StatsEventDisconnectedData::m_Reason, m_ShouldShowControllerDisconnect, mission, Mission::OnEvent(), ErrorModuleHandler::OnEvent(), VONManagerBase::OnEvent(), OnLoginTimeEvent(), OnMPConnectionLostEvent(), OnPreloadEvent(), OnRespawnEvent(), ParticleManager(), Analytics::PlayerDisconnected(), Analytics::PlayerSpawned(), Print(), ClientData::ResetClientData(), SetConnecting(), SetGameState(), SetLoadState(), OnlineServices::SetMultiplayState(), LoadingScreen::SetStatus(), and vector::Zero.
OnGameplayDataHandlerLoad()
void OnGameplayDataHandlerLoad ()
Definition at line 992 of file dayzgame.c.
    {
    }
OnInitialize()
override bool OnInitialize ()
Definition at line 1666 of file dayzgame.c.
    {
        ParticleList.PreloadParticles();
        InitNotifications();
        m_Visited = new TStringArray;
        GetProfileStringList( "SB_Visited", m_Visited );
        if ( GetLoadState() == DayZLoadState.UNDEFINED )
        {
            string param;
            if ( GetCLIParam("join", param) )
            {
                JoinLaunch();
                #ifndef PLATFORM_PS4
                CreateTitleScreen();
                #endif
            }
            else if ( GetCLIParam("connect", param) )
            {
                ConnectLaunch();
            }
            else if ( GetCLIParam("mission", param) )
            {
                MissionLaunch();
            }
            else if ( GetCLIParam("party", param) )
            {
                PartyLaunch();
            }
            else
            {
                MainMenuLaunch();
            }
            return true;
        }
        return false;
    }
References ConnectLaunch(), CreateTitleScreen(), GetCLIParam(), GetLoadState(), CGame::GetProfileStringList(), InitNotifications(), JoinLaunch(), m_Visited, MainMenuLaunch(), MissionLaunch(), PartyLaunch(), and ParticleList::PreloadParticles().
OnKeyPress()
override void OnKeyPress (int key)
Definition at line 2372 of file dayzgame.c.
    {
        if ( key == KeyCode.KC_LCONTROL )
        {
            m_IsCtrlHolding = true;
        }
        if (key == KeyCode.KC_LMENU)
        {
            m_IsLeftAltHolding = true;
        }
        if (key == KeyCode.KC_RMENU)
        {
            m_IsRightAltHolding = true;
        }
        if (m_keyboard_handler)
        {
            m_keyboard_handler.OnKeyDown(NULL, 0, 0, key);
        }
        Mission mission = GetMission();
        if (mission)
        {
            mission.OnKeyPress(key);
        }
#ifdef DEVELOPER
        if ((m_IsLeftAltHolding || m_IsLeftAltHolding) && key == KeyCode.KC_F4)
        {
            RequestExit(0);
        }
#endif
    }
References CGame::GetMission(), m_IsCtrlHolding, m_IsLeftAltHolding, m_IsRightAltHolding, m_keyboard_handler, mission, UIScriptedMenu::OnKeyDown(), Mission::OnKeyPress(), and CGame::RequestExit().
OnKeyRelease()
override void OnKeyRelease (int key)
Definition at line 2411 of file dayzgame.c.
    {
        if ( key == KeyCode.KC_LCONTROL )
        {
            m_IsCtrlHolding = false;
        }
        if ( key == KeyCode.KC_LWIN )
        {
            m_IsWinHolding = false;
        }
        if (key == KeyCode.KC_LMENU || key == KeyCode.KC_RMENU)
        {
            m_IsLeftAltHolding = false;
        }
        if (key == KeyCode.KC_RMENU)
        {
            m_IsRightAltHolding  = false;
        }
        if (m_keyboard_handler)
        {
            m_keyboard_handler.OnKeyUp(NULL, 0, 0, key);
        }
        Mission mission = GetMission();
        if (mission)
        {
            mission.OnKeyRelease(key);
        }
    }
References CGame::GetMission(), m_IsCtrlHolding, m_IsLeftAltHolding, m_IsRightAltHolding, m_IsWinHolding, m_keyboard_handler, mission, and Mission::OnKeyRelease().
OnLoginTimeEvent()
void OnLoginTimeEvent (int loginTime)
Definition at line 1455 of file dayzgame.c.
    {
#ifndef NO_GUI
        // remove login queue if exits
        CancelLoginQueue();
        GetUserManager().GetUserDatabaseIdAsync();
        m_LoginTime = loginTime;
        // timer for login
        if (m_LoginTime > 0)
        {
            if (!m_LoginTimeScreen)
            {
                GetUIManager().CloseAll();
                if (GetMission())
                {
                    UIScriptedMenu parent = GetUIManager().GetMenu();
                    EnterLoginTime(parent);
                }
                else
                {
                    m_LoginTimeScreen = new LoginTimeStatic();
                    GetUIManager().ShowScriptedMenu(m_LoginTimeScreen, null);
                }
            }
            m_LoginTimeScreen.SetTime(m_LoginTime);
            m_LoginTimeScreen.Show();
            GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(this.LoginTimeCountdown, 1000, true);
        }
#endif
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CancelLoginQueue(), UIManager::CloseAll(), EnterLoginTime(), CGame::GetCallQueue(), UIManager::GetMenu(), CGame::GetMission(), CGame::GetUIManager(), BiosUserManager::GetUserDatabaseIdAsync(), CGame::GetUserManager(), LoginTimeCountdown(), m_LoginTime, m_LoginTimeScreen, and UIManager::ShowScriptedMenu().
Referenced by OnEvent().
OnMouseButtonPress()
override void OnMouseButtonPress (int button)
Definition at line 2446 of file dayzgame.c.
    {
        Mission mission = GetMission();
        if (mission)
        {
            mission.OnMouseButtonPress(button);
        }
    }
References CGame::GetMission(), mission, and Mission::OnMouseButtonPress().
OnMouseButtonRelease()
override void OnMouseButtonRelease (int button)
Definition at line 2456 of file dayzgame.c.
    {
        Mission mission = GetMission();
        if (mission)
        {
            mission.OnMouseButtonRelease(button);
        }
    }
References CGame::GetMission(), mission, and Mission::OnMouseButtonRelease().
OnMPConnectionLostEvent()
void OnMPConnectionLostEvent (int duration)
Definition at line 1573 of file dayzgame.c.
    {
#ifndef NO_GUI
        if( duration < 0 )
        {
            if( m_connectionLost )
                m_connectionLost.Hide();
            return;
        }
        // initialize new message
        if (!m_connectionLost )
        {
            m_connectionLost = new ConnectionLost(this);
        }
        if (duration >= 5)
        {
            // show message
            m_connectionLost.Show();
            // update message
            if (m_connectionLost.GetDuration() != duration)
            {
                // use STR_MP_NO_MESSAGE
                m_connectionLost.SetText("#dayz_game_no_message" + " %1 " + duration.ToString() + " " + "#dayz_game_seconds");
                m_connectionLost.SetDuration(duration);
            }
        }
        else
        {
            // hide unnecessary message
            m_connectionLost.Hide();
        }
#endif
    }
References ConnectionLost::GetDuration(), ConnectionLost::Hide(), m_connectionLost, ConnectionLost::SetDuration(), ConnectionLost::SetText(), and ConnectionLost::Show().
Referenced by OnEvent().
OnPostUpdate()
override void OnPostUpdate (bool doSim, float timeslice)
Definition at line 2531 of file dayzgame.c.
    {
    }
OnPreloadEvent()
void OnPreloadEvent (vector pos)
Definition at line 1538 of file dayzgame.c.
    {
        // cancel only login time (respawn time is parallel with preload, but login time is not)
        if (m_LoginTimeScreen && !m_LoginTimeScreen.IsRespawn())
            CancelLoginTimeCountdown();
        // tell game to continue
        StoreLoginDataPrepare();
    }
References CancelLoginTimeCountdown(), m_LoginTimeScreen, and StoreLoginDataPrepare().
Referenced by OnEvent().
OnRespawnEvent()
void OnRespawnEvent (int time)
Definition at line 1512 of file dayzgame.c.
    {
        // use login time screen for respawn timer
        if (time > 0)
        {
            m_LoginTime = time;
            if (!m_LoginTimeScreen)
            {
                GetUIManager().CloseAll();
                UIScriptedMenu parent = GetUIManager().GetMenu();
                EnterLoginTime(parent);
            }
            m_LoginTimeScreen.SetRespawn(true);
            m_LoginTimeScreen.SetTime(m_LoginTime);
            m_LoginTimeScreen.Show();
            GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(this.LoginTimeCountdown, 1000, true);
        }
        if (GetPlayer())
            GetPlayer().StopDeathDarkeningEffect();
        PPERequesterBank.GetRequester(PPERequester_DeathDarkening).Start(new Param1<float>(1.0));
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), UIManager::CloseAll(), EnterLoginTime(), CGame::GetCallQueue(), UIManager::GetMenu(), CGame::GetPlayer(), CGame::GetUIManager(), LoginTimeCountdown(), m_LoginTime, and m_LoginTimeScreen.
Referenced by OnEvent().
OnRPC()
override void OnRPC (PlayerIdentity sender, Object target, int rpc_type, ParamsReadContext ctx)
Definition at line 2537 of file dayzgame.c.
    {
        super.OnRPC(sender, target, rpc_type, ctx);
        Event_OnRPC.Invoke( sender, target, rpc_type, ctx );
        //Print("["+ GetGame().GetTime().ToString() +"] => DayZGame::OnRPC = "+ EnumTools.EnumToString(ERPCs,rpc_type) );
        if (target)
        {
            // call rpc on target
            target.OnRPC(sender, rpc_type, ctx);
        }
        else
        {
            switch ( rpc_type )
            {
                #ifndef SERVER
                #ifndef NO_GUI
                case ERPCs.RPC_CFG_GAMEPLAY_SYNC:
                {
                    CfgGameplayHandler.OnRPC(null, ctx);
                    break;
                }
                case ERPCs.RPC_UNDERGROUND_SYNC:
                {
                    UndergroundAreaLoader.OnRPC(ctx);
                    break;
                }
                case ERPCs.RPC_SEND_NOTIFICATION:
                {
                    NotificationType type;
                    float show_time;
                    string detail_text;
                    ctx.Read(type);
                    ctx.Read(show_time);
                    ctx.Read(detail_text);
                    NotificationSystem.AddNotification( type, show_time, detail_text );
                    break;
                }
                case ERPCs.RPC_SEND_NOTIFICATION_EXTENDED:
                {
                    float show_time_ext;
                    string title_text_ext;
                    string detail_text_ext;
                    string icon_ext;
                    ctx.Read(show_time_ext);
                    ctx.Read(title_text_ext);
                    ctx.Read(detail_text_ext);
                    ctx.Read(icon_ext);
                    NotificationSystem.AddNotificationExtended( show_time_ext, title_text_ext, detail_text_ext, icon_ext );
                    break;
                }
                case ERPCs.RPC_SOUND_HELICRASH:
                {
                    bool playSound;
                    vector pos;
                    string sound_set;
                    //Helicrash is a world event, we want anyone to be able to hear it
                    Param3<bool, vector, int> playCrashSound = new Param3<bool, vector, int>( false, "0 0 0",0 );
                    if ( ctx.Read( playCrashSound ) )
                    {
                        playSound = playCrashSound.param1;
                        pos = playCrashSound.param2;
                        sound_set = CrashSoundSets.GetSoundSetByHash(playCrashSound.param3);
                    }
                    if ( playSound )
                    {
                        m_CrashSound = SEffectManager.PlaySound( sound_set, pos, 0.1, 0.1 );
                        m_CrashSound.SetAutodestroy( true );
                    }
                break;
                }
                //Random off map artillery barrage
                case ERPCs.RPC_SOUND_ARTILLERY:
                {
                    vector position;
                    Param1<vector> playArtySound = new Param1<vector>( vector.Zero );
                    if ( ctx.Read( playArtySound ) )
                    {
                        position = playArtySound.param1;
                        if ( position == vector.Zero )
                            break;
                    }
                    else
                        break;
                    if ( !GetGame().GetPlayer() )
                        break;
                    if ( vector.DistanceSq( GetGame().GetPlayer().GetPosition(), position ) <= ( MIN_ARTY_SOUND_RANGE * MIN_ARTY_SOUND_RANGE ) )
                        break;
                    m_ArtySound = SEffectManager.PlaySound( "Artillery_Distant_Barrage_SoundSet", position, 0.1, 0.1 );
                    m_ArtySound.SetAutodestroy( true );
                break;
                }
                case ERPCs.RPC_SOUND_CONTAMINATION:
                {
                    vector soundPos;
                    Param1<vector> playContaminatedSound = new Param1<vector>( vector.Zero );
                    if ( ctx.Read( playContaminatedSound ) )
                    {
                        soundPos = playContaminatedSound.param1;
                        if ( soundPos == vector.Zero )
                            break;
                    }
                    else
                        break;
                    if ( !GetGame().GetPlayer() )
                        break;
                    EffectSound closeArtySound = SEffectManager.PlaySound( "Artillery_Close_SoundSet", soundPos );
                    closeArtySound.SetAutodestroy( true );
                    // We add camera shake upon shell detonation
                    float distance_to_player = vector.DistanceSq( soundPos, GetGame().GetPlayer().GetPosition() );
                    if ( distance_to_player <= GameConstants.CAMERA_SHAKE_ARTILLERY_DISTANCE2 )
                    {
                        float strength_factor = Math.InverseLerp( GameConstants.CAMERA_SHAKE_ARTILLERY_DISTANCE, 0, Math.Sqrt( distance_to_player ) );
                        DayZPlayerCamera camera = GetGame().GetPlayer().GetCurrentCamera();
                        if ( camera )
                            camera.SpawnCameraShake( strength_factor * 4 );
                    }
                    ParticleManager.GetInstance().PlayInWorld( ParticleList.CONTAMINATED_AREA_GAS_SHELL, soundPos );
                    break;
                }
                // Single artillery shot to announce dynamic contaminated area
                case ERPCs.RPC_SOUND_ARTILLERY_SINGLE:
                {
                    vector soundPosition;
                    vector delayedSoundPos;
                    float soundDelay;
                    Param3<vector, vector, float> playArtyShotSound = new Param3<vector, vector, float>( vector.Zero, vector.Zero, 0 );
                    if ( ctx.Read( playArtyShotSound ) )
                    {
                        soundPosition = playArtyShotSound.param1;
                        delayedSoundPos = playArtyShotSound.param2;
                        soundDelay = playArtyShotSound.param3;
                        if ( soundPosition == vector.Zero )
                            break;
                    }
                    else
                        break;
                    if ( !GetGame().GetPlayer() )
                        break;
                    m_ArtySound = SEffectManager.PlaySound( "Artillery_Distant_SoundSet", soundPosition, 0.1, 0.1 );
                    m_ArtySound.SetAutodestroy( true );
                    // We remove the amount of time the incoming sound lasts
                    soundDelay -= 5;
                    // We convert to milliseconds
                    soundDelay *= 1000;
                    GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( DelayedMidAirDetonation, soundDelay, false, delayedSoundPos[0], delayedSoundPos[1], delayedSoundPos[2] );
                    break;
                }
                #endif
                #endif
                case ERPCs.RPC_USER_SYNC_PERMISSIONS:
                {
                    map<string, bool> mute_list;
                    if ( ctx.Read( mute_list ) )
                    {
                        for ( int i = 0; i < mute_list.Count(); i++ )
{
                            string uid = mute_list.GetKey( i );
                            bool mute = mute_list.GetElement( i );
                            MutePlayer( uid, sender.GetPlainId(), mute );
                        }
                    }
                    break;
                }
                /*
                case ERPCs.RPC_SERVER_RESPAWN_MODE:
                {
                    int mode;
                    if ( ctx.Read(mode) && !IsServer() )
                    {
                        GetMission().SetRespawnModeClient(mode);
                    }
                }
                */
                #ifdef DEVELOPER
                case ERPCs.DEV_RPC_ITEM_DIAG_BUTTON:
                {
                    if (ctx.Read(CachedObjectsParams.PARAM1_INT))
                    {
                        EntityAI entity = EntityAI.Cast(_item);
                        if (entity)
{
                            entity.OnDebugButtonPressServer(CachedObjectsParams.PARAM1_INT.param1);
                        }
                    }
                    break;
                }
                #ifdef SERVER
                case ERPCs.DEV_CAMERA_TOOLS_CAM_DATA:
                {
                    if (!m_CameraToolsMenuServer)
                    {
                        m_CameraToolsMenuServer = new CameraToolsMenuServer;
                    }
                    m_CameraToolsMenuServer.OnRPC(rpc_type, ctx);
                    break;
                }
                case ERPCs.DEV_CAMERA_TOOLS_CAM_SUBSCRIBE:
                {
                    if (!m_CameraToolsMenuServer)
                    {
                        m_CameraToolsMenuServer = new CameraToolsMenuServer;
                    }
                    m_CameraToolsMenuServer.OnRPC(rpc_type, ctx);
                    break;
                }
                #endif
                #endif
            }
            // global rpc's handling
        }
    }
References NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE, GameConstants::CAMERA_SHAKE_ARTILLERY_DISTANCE2, ParticleList::CONTAMINATED_AREA_GAS_SHELL, DayZPlayerCamera(), DelayedMidAirDetonation(), vector::DistanceSq(), Event_OnRPC, CGame::GetCallQueue(), GetGame(), PlayerIdentityBase::GetPlainId(), CGame::GetPlayer(), GetPosition, CrashSoundSets::GetSoundSetByHash(), Math::InverseLerp(), ScriptInvoker::Invoke(), m_ArtySound, m_CrashSound, MIN_ARTY_SOUND_RANGE, CGame::MutePlayer(), CfgGameplayHandler::OnRPC(), UndergroundAreaLoader::OnRPC(), CachedObjectsParams::PARAM1_INT, ParticleManager(), SEffectManager::PlaySound(), Serializer::Read(), EffectSound::SetAutodestroy(), Math::Sqrt(), and vector::Zero.
OnUpdate()
override void OnUpdate (bool doSim, float timeslice)
Definition at line 2475 of file dayzgame.c.
    {
        Mission mission = GetMission();
        bool gameIsRunning = false;
        if (doSim && mission && !mission.IsPaused())
        {
            gameIsRunning = true;
        }
        if (doSim && mission)
        {
            mission.OnUpdate(timeslice);
        }
        // queues and timers update
        GetCallQueue(CALL_CATEGORY_SYSTEM).Tick(timeslice);
        GetUpdateQueue(CALL_CATEGORY_SYSTEM).Invoke(timeslice);
        GetTimerQueue(CALL_CATEGORY_SYSTEM).Tick(timeslice);
    #ifndef NO_GUI
        if (m_IsConnecting)
            UpdateLoginQueue(timeslice);
        if (m_loading && m_loading.IsLoading())
        {
            m_loading.OnUpdate(timeslice);
        }
        else if (m_LoginTimeScreen && m_LoginTimeScreen.IsStatic())
        {
            m_LoginTimeScreen.Update(timeslice);
        }
        else
        {
            GetCallQueue(CALL_CATEGORY_GUI).Tick(timeslice);
            GetUpdateQueue(CALL_CATEGORY_GUI).Invoke(timeslice);
            GetTimerQueue(CALL_CATEGORY_GUI).Tick(timeslice);
            GetDragQueue().Tick();
        }
        NotificationSystem.Update( timeslice );
        if( m_Notifications )
        {
            m_Notifications.Update( timeslice );
        }
    #endif
        if (gameIsRunning)
        {
            GetCallQueue(CALL_CATEGORY_GAMEPLAY).Tick(timeslice);
            GetUpdateQueue(CALL_CATEGORY_GAMEPLAY).Invoke(timeslice);
            GetTimerQueue(CALL_CATEGORY_GAMEPLAY).Tick(timeslice);
        }
    }
References CALL_CATEGORY_GAMEPLAY, CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), CGame::GetDragQueue(), CGame::GetMission(), CGame::GetTimerQueue(), CGame::GetUpdateQueue(), ScriptInvoker::Invoke(), LoadingScreen::IsLoading(), Mission::IsPaused(), m_IsConnecting, m_loading, m_LoginTimeScreen, m_Notifications, mission, LoadingScreen::OnUpdate(), Mission::OnUpdate(), ScriptCallQueue::Tick(), NotificationSystem::Update(), NotificationUI::Update(), and UpdateLoginQueue().
PartyLaunch()
void PartyLaunch ()
Definition at line 1887 of file dayzgame.c.
    {
        SetGameState( DayZGameState.PARTY );
        SetLoadState( DayZLoadState.PARTY_START );
        BiosUserManager user_manager = GetGame().GetUserManager();
        string param;
        if ( GetCLIParam("party", param) )
        {
            user_manager.ParsePartyAsync( param );
            StartRandomCutscene(GetMainMenuWorld());
        }
    }
References GetCLIParam(), GetGame(), CGame::GetMainMenuWorld(), CGame::GetUserManager(), BiosUserManager::ParsePartyAsync(), SetGameState(), SetLoadState(), and CGame::StartRandomCutscene().
Referenced by OnInitialize().
RefreshCurrentServerInfo()
void RefreshCurrentServerInfo ()
Definition at line 2274 of file dayzgame.c.
    {
        string addr;
        int port;
        if ( GetHostAddress( addr, port ) )
        {
            m_ConnectAddress = addr;
            m_ConnectPort = port;
        }
        OnlineServices.GetCurrentServerInfo( m_ConnectAddress, m_ConnectPort );
    }
References OnlineServices::GetCurrentServerInfo(), CGame::GetHostAddress(), m_ConnectAddress, and m_ConnectPort.
RegisterProfilesOptions()
void RegisterProfilesOptions ()
Definition at line 924 of file dayzgame.c.
    {
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.CROSSHAIR, SHOW_CROSSHAIR);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.HUD , SHOW_HUD);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.QUICKBAR, SHOW_QUICKBAR);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.SERVER_MESSAGES, SYSTEM_CHAT_MSG);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.USERS_CHAT, DIRECT_CHAT_MSG);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.RADIO_CHAT, RADIO_CHAT_MSG);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.GAME_MESSAGES, GAME_CHAT_MSG, false);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.ADMIN_MESSAGES, ADMIN_CHAT_MSG, false);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.PLAYER_MESSAGES, PLAYER_CHAT_MSG, false);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.SERVERINFO_DISPLAY, SHOW_SERVERINFO, true);
        m_DayZProfileOptions.RegisterProfileOption(EDayZProfilesOptions.BLEEDINGINDICATION, ENABLE_BLEEDINGINDICATION, true);
    }
References ADMIN_CHAT_MSG, DIRECT_CHAT_MSG, ENABLE_BLEEDINGINDICATION, GAME_CHAT_MSG, m_DayZProfileOptions, PLAYER_CHAT_MSG, RADIO_CHAT_MSG, DayZProfilesOptions::RegisterProfileOption(), SHOW_CROSSHAIR, SHOW_HUD, SHOW_QUICKBAR, SHOW_SERVERINFO, and SYSTEM_CHAT_MSG.
Referenced by DeferredInit().
ReloadMission()
void ReloadMission ()
Definition at line 1108 of file dayzgame.c.
    {
    #ifdef DEVELOPER
        Print("Reloading mission module!");
        CreateMission(m_MissionPath);
    #endif
    }
References CGame::CreateMission(), m_MissionPath, and Print().
RemoveVoiceNotification()
void RemoveVoiceNotification (VONStopSpeakingEventParams vonStopParams)
Definition at line 1415 of file dayzgame.c.
    {
        m_Notifications.RemoveVoiceNotification(vonStopParams.param2);
    }
References m_Notifications, and NotificationUI::RemoveVoiceNotification().
ReportModded()
static bool ReportModded () static
Definition at line 1061 of file dayzgame.c.
    {
        return m_ReportModded;
    }
References m_ReportModded.
ResetProfileOptions()
void ResetProfileOptions ()
Definition at line 939 of file dayzgame.c.
    {
        m_DayZProfileOptions.ResetOptions();
    }
References m_DayZProfileOptions, and DayZProfilesOptions::ResetOptions().
Referenced by SelectGamepad().
SelectGamepad()
void SelectGamepad ()
Definition at line 2106 of file dayzgame.c.
    {
        ResetProfileOptions();
        BiosUserManager user_manager = GetUserManager();
        if ( user_manager )
        {
            BiosUser selected_user = user_manager.GetSelectedUser();
            if ( selected_user )
            {
                OnlineServices.SetBiosUser(selected_user);
                SetPlayerName( selected_user.GetName() );
                SetUserFOV(GetUserFOVFromConfig());
                #ifdef PLATFORM_CONSOLE
                SetPlayerGameName( selected_user.GetName() );
                user_manager.GetUserDatabaseIdAsync();
                #endif
            }
            if ( GetUIManager().GetMenu() )
            {
                GetUIManager().GetMenu().Refresh();
            }
        }
        switch ( GetLoadState() )
        {
            case DayZLoadState.JOIN_USER_SELECT:
            {
                SetLoadState(DayZLoadState.JOIN_CONTROLLER_SELECT );
                OnlineServices.LoadMPPrivilege();
                break;
            }
            case DayZLoadState.PARTY_USER_SELECT:
            {
                SetLoadState(DayZLoadState.PARTY_CONTROLLER_SELECT);
                DeleteTitleScreen();
                GetUIManager().EnterScriptedMenu(MENU_SERVER_BROWSER, GetUIManager().GetMenu());
                break;
            }
            case DayZLoadState.CONNECT_USER_SELECT:
            {
                SetLoadState(DayZLoadState.CONNECT_CONTROLLER_SELECT );
                OnlineServices.LoadMPPrivilege();
                break;
            }
            case DayZLoadState.MAIN_MENU_USER_SELECT:
            {
                SetLoadState( DayZLoadState.MAIN_MENU_CONTROLLER_SELECT );
                DeleteTitleScreen();
                GetUIManager().EnterScriptedMenu( MENU_MAIN, GetUIManager().GetMenu() );
                break;
            }
            case DayZLoadState.MISSION_USER_SELECT:
            {
                SetLoadState( DayZLoadState.MISSION_CONTROLLER_SELECT );
                DeleteTitleScreen();
                string mission;
                GetCLIParam("mission", mission);
                PlayMission(mission);
                break;
            }
        }
    }
References DeleteTitleScreen(), UIManager::EnterScriptedMenu(), GetCLIParam(), GetLoadState(), UIManager::GetMenu(), BiosUser::GetName(), BiosUserManager::GetSelectedUser(), CGame::GetUIManager(), BiosUserManager::GetUserDatabaseIdAsync(), GetUserFOVFromConfig(), CGame::GetUserManager(), OnlineServices::LoadMPPrivilege(), MENU_MAIN, MENU_SERVER_BROWSER, mission, CGame::PlayMission(), UIScriptedMenu::Refresh(), ResetProfileOptions(), OnlineServices::SetBiosUser(), SetLoadState(), SetPlayerGameName(), CGame::SetPlayerName(), and SetUserFOV().
Referenced by SelectUser().
SelectUser()
void SelectUser (int gamepad = -1)
Definition at line 1945 of file dayzgame.c.
    {
        BiosUserManager user_manager = GetUserManager();
        if ( user_manager )
        {
            BiosUser selected_user;
            if ( gamepad > -1 )
            {
                GetInput().GetGamepadUser( gamepad, selected_user );
                #ifdef PLATFORM_PS4
                if ( selected_user && selected_user.IsOnline() )
                #endif
                {
                    GetGame().GetInput().IdentifyGamepad(GamepadButton.BUTTON_NONE);
                    GetInput().SelectActiveGamepad( gamepad );
                    user_manager.SelectUserEx( selected_user );
                }
                #ifdef PLATFORM_PS4
                else if ( selected_user )
                {
                    user_manager.SelectUserEx( selected_user );
                    user_manager.LogOnUserAsync( selected_user );
                    return;
                }
                else
                {
                    GetInput().ResetActiveGamepad();
                    GamepadCheck();
                }
                #endif
            }
            if ( !selected_user )
                selected_user = user_manager.GetSelectedUser();
            switch ( GetLoadState() )
            {
                case DayZLoadState.JOIN_START:
                {
                    SetLoadState( DayZLoadState.JOIN_USER_SELECT );
                    OnlineServices.Init();
                    SelectGamepad();
                    return;
                }
                case DayZLoadState.PARTY_START:
                {
                    SetLoadState( DayZLoadState.PARTY_USER_SELECT );
                    OnlineServices.Init();
                    SelectGamepad();
                    return;
                }
                case DayZLoadState.MAIN_MENU_START:
                {
                    if ( !selected_user )
                    {
                        user_manager.PickUserAsync();
                        return;
                    }
                    user_manager.SelectUserEx( selected_user );
                    SetLoadState( DayZLoadState.MAIN_MENU_USER_SELECT );
                    OnlineServices.Init();
                    SelectGamepad();
                    return;
                }
                case DayZLoadState.CONNECT_START:
                {
                    if ( !selected_user )
                    {
                        user_manager.PickUserAsync();
                        return;
                    }
                    user_manager.SelectUserEx( selected_user );
                    SetLoadState( DayZLoadState.CONNECT_USER_SELECT );
                    OnlineServices.Init();
                    SelectGamepad();
                    return;
                }
                case DayZLoadState.MISSION_START:
                {
                    if ( !selected_user )
                    {
                        user_manager.PickUserAsync();
                        return;
                    }
                    user_manager.SelectUserEx( selected_user );
                    SetLoadState( DayZLoadState.MISSION_USER_SELECT );
                    OnlineServices.Init();
                    SelectGamepad();
                    return;
                }
                default:
                {
                    /*
                    if( !selected_user )
                    {
                        SetLoadState( DayZLoadState.MAIN_MENU_START );
                        user_manager.PickUserAsync();
                        return;
                    }*/
                }
            }
        }
    }
References GamepadCheck(), GetGame(), Input::GetGamepadUser(), CGame::GetInput(), GetLoadState(), BiosUserManager::GetSelectedUser(), CGame::GetUserManager(), Input::IdentifyGamepad(), OnlineServices::Init(), BiosUser::IsOnline(), BiosUserManager::LogOnUserAsync(), BiosUserManager::PickUserAsync(), Input::ResetActiveGamepad(), Input::SelectActiveGamepad(), SelectGamepad(), BiosUserManager::SelectUserEx(), and SetLoadState().
Referenced by GamepadCheck().
SetConnecting()
void SetConnecting (bool value)
Returns true when connecting to server.
Definition at line 2799 of file dayzgame.c.
    {
        m_IsConnecting = value;
    }
References m_IsConnecting.
Referenced by Connect(), and OnEvent().
SetDatabaseID()
void SetDatabaseID (string id)
Definition at line 1732 of file dayzgame.c.
    {
        m_DatabaseID = id;
        if( GetUIManager().GetMenu() )
        {
            GetUIManager().GetMenu().Refresh();
        }
    }
References UIManager::GetMenu(), CGame::GetUIManager(), m_DatabaseID, and UIScriptedMenu::Refresh().
SetEVValue()
void SetEVValue (float value)
Definition at line 3096 of file dayzgame.c.
    {
        m_PreviousEVValue = m_EVValue;
        SetEVUser(value);
        m_EVValue = value;
    }
References m_EVValue, m_PreviousEVValue, and CGame::SetEVUser().
Referenced by LoadingHide().
SetGameState()
void SetGameState (DayZGameState state)
Definition at line 1041 of file dayzgame.c.
    {
        m_GameState = state;
    }
References m_GameState.
Referenced by ConnectLaunch(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), and TryConnect().
SetKeyboardHandle()
void SetKeyboardHandle (UIScriptedMenu handler)
Definition at line 2821 of file dayzgame.c.
    {
        m_keyboard_handler = handler;
    }
References m_keyboard_handler.
SetLoadState()
void SetLoadState (DayZLoadState state)
Definition at line 1051 of file dayzgame.c.
    {
        m_LoadState = state;
    }
References m_LoadState.
Referenced by ConnectLaunch(), JoinLaunch(), MainMenuLaunch(), MissionLaunch(), OnEvent(), PartyLaunch(), SelectGamepad(), and SelectUser().
SetMissionPath()
void SetMissionPath (string path)
Called from C++.
Definition at line 945 of file dayzgame.c.
    {
        m_MissionPath = path;
        int pos_end = 0;
        int pos_cur = 0;
        while ( pos_cur != -1 )
        {
            pos_end = pos_cur;
            pos_cur = path.IndexOfFrom(pos_cur + 1 , "\\");
        }
        m_MissionFolderPath = path.Substring(0, pos_end);
    }
References string::IndexOfFrom(), m_MissionFolderPath, m_MissionPath, path, and string::Substring().
SetMissionState()
void SetMissionState (int state)
Definition at line 1005 of file dayzgame.c.
    {
        m_MissionState = state;
    }
References m_MissionState.
SetNewCharacter()
void SetNewCharacter (bool state)
Definition at line 3042 of file dayzgame.c.
    {
        m_IsNewCharacter = state;
    }
References m_IsNewCharacter.
SetPlayerGameName()
void SetPlayerGameName (string name)
Definition at line 3032 of file dayzgame.c.
    {
        m_PlayerName = name;
    }
References m_PlayerName, and name.
Referenced by SelectGamepad().
SetPreviousGamepad()
void SetPreviousGamepad (int gamepad)
Definition at line 2054 of file dayzgame.c.
    {
        m_PreviousGamepad = gamepad;
    }
References m_PreviousGamepad.
SetProfileOption()
void SetProfileOption (EDayZProfilesOptions option, bool value)
Definition at line 1021 of file dayzgame.c.
    {
        m_DayZProfileOptions.SetProfileOption(option, value);
    }
References m_DayZProfileOptions, and DayZProfilesOptions::SetProfileOption().
SetUserFOV()
void SetUserFOV (float pFov)
Definition at line 3052 of file dayzgame.c.
    {
        if ( pFov < OPTIONS_FIELD_OF_VIEW_MIN ) pFov = OPTIONS_FIELD_OF_VIEW_MIN;
        if ( pFov > OPTIONS_FIELD_OF_VIEW_MAX ) pFov = OPTIONS_FIELD_OF_VIEW_MAX;
        m_UserFOV = pFov;
    }
References m_UserFOV.
Referenced by SelectGamepad().
ShouldShowControllerDisconnect()
bool ShouldShowControllerDisconnect ()
Definition at line 1789 of file dayzgame.c.
    {
        return m_ShouldShowControllerDisconnect;
    }
References m_ShouldShowControllerDisconnect.
StoreLoginDataPrepare()
void StoreLoginDataPrepare ()
Definition at line 1550 of file dayzgame.c.
    {
        ScriptReadWriteContext ctx = new ScriptReadWriteContext;
        //Print("StoreLoginDataPrepare");
        //GetMenuData().RequestGetDefaultCharacterData();
        GetMenuDefaultCharacterData().SerializeCharacterData(ctx.GetWriteContext());
        StoreLoginData(ctx.GetWriteContext());
    }
References CGame::GetMenuDefaultCharacterData(), ScriptReadWriteContext::GetWriteContext(), MenuDefaultCharacterData::SerializeCharacterData(), and CGame::StoreLoginData().
Referenced by OnPreloadEvent().
TryConnect()
void TryConnect ()
Definition at line 2171 of file dayzgame.c.
    {
        if ( GetGameState() != DayZGameState.CONNECTING )
        {
            switch ( GetLoadState() )
            {
                case DayZLoadState.JOIN_CONTROLLER_SELECT:
                {
                    SetGameState( DayZGameState.CONNECTING );
                    OnlineServices.GetSession();
                    break;
                }
                case DayZLoadState.CONNECT_CONTROLLER_SELECT:
                {
                    SetGameState( DayZGameState.CONNECTING );
                    ConnectFromCLI();
                    break;
                }
                case DayZLoadState.PARTY_CONTROLLER_SELECT:
                {
                    SetGameState( DayZGameState.CONNECTING );
                    Connect();
                    break;
                }
                case DayZLoadState.MAIN_MENU_CONTROLLER_SELECT:
                {
                    SetGameState( DayZGameState.CONNECTING );
                    Connect();
                    break;
                }
            }
        }
        else
        {
            string address;
            int port;
            if (GetHostAddress(address, port))
            {
                if (m_ConnectAddress == address && m_ConnectPort == port)
                    ErrorModuleHandler.ThrowError(ErrorCategory.ConnectErrorScript, EConnectErrorScript.ALREADY_CONNECTING_THIS);
                else
                    ErrorModuleHandler.ThrowError(ErrorCategory.ConnectErrorScript, EConnectErrorScript.ALREADY_CONNECTING, string.Format("%1:%2", address, port));
            }
            else
            {
                DisconnectSessionForce();
                DisconnectSessionScript();
                TryConnect();
            }
        }
    }
References Connect(), ConnectFromCLI(), CGame::DisconnectSessionForce(), DisconnectSessionScript(), GetGameState(), CGame::GetHostAddress(), GetLoadState(), OnlineServices::GetSession(), m_ConnectAddress, m_ConnectPort, SetGameState(), ErrorModuleHandler::ThrowError(), and TryConnect().
Referenced by TryConnect().
UpdateLoginQueue()
void UpdateLoginQueue (float timeslice)
Display login queue position dialog
manually update static login queue dialog
Definition at line 1421 of file dayzgame.c.
    {
        int pos = GetUIManager().GetLoginQueuePosition();
        if (!m_LoginQueue && pos > 0)
        {
            GetUIManager().CloseAll();
            if (GetMission())
            {
                UIScriptedMenu parent = GetUIManager().GetMenu();
                EnterLoginQueue(parent);
            }
            else
            {
                m_LoginQueue = new LoginQueueStatic();
                GetUIManager().ShowScriptedMenu(m_LoginQueue, null);
            }
        }
        if (m_LoginQueue)
        {
            m_LoginQueue.SetPosition(pos);
            LoginQueueStatic loginQueue;
            if (LoginQueueBase.CastTo(loginQueue, m_LoginQueue))
            {
                loginQueue.Update(timeslice);
            }
        }
    }
References UIManager::CloseAll(), EnterLoginQueue(), UIManager::GetLoginQueuePosition(), UIManager::GetMenu(), CGame::GetMission(), CGame::GetUIManager(), m_LoginQueue, and UIManager::ShowScriptedMenu().
Referenced by OnUpdate().
UpdateVoiceLevel()
void UpdateVoiceLevel (int level)
Definition at line 3022 of file dayzgame.c.
    {
        GetMission().UpdateVoiceLevelWidgets(level);
    }
References CGame::GetMission(), and Mission::UpdateVoiceLevelWidgets().
~DayZGame()
private void ~DayZGame ()
Definition at line 876 of file dayzgame.c.
    {
        PPEManagerStatic.DestroyManagerStatic();
        g_Game = null;
        SetDispatcher(null);
        Print("~DayZGame()");
    }
References PPEManagerStatic::DestroyManagerStatic(), g_Game, Print(), and SetDispatcher().
Variable Documentation
CONNECT
class DayZProfilesOptions CONNECT
CONNECT_CONTROLLER_SELECT
class DayZProfilesOptions CONNECT_CONTROLLER_SELECT
CONNECT_START
class DayZProfilesOptions CONNECT_START
CONNECT_USER_SELECT
class DayZProfilesOptions CONNECT_USER_SELECT
CONNECTING
class DayZProfilesOptions CONNECTING
Event_OnRPC
ref ScriptInvoker Event_OnRPC = new ScriptInvoker() static
Definition at line 772 of file dayzgame.c.
Referenced by OnRPC(), and SyncEvents::RegisterEvents().
g_Game
DayZGame g_Game
Definition at line 3144 of file dayzgame.c.
Referenced by MissionBase::AbortMission(), Chat::Add(), Trigger::AddInsider(), UIScriptedMenu::Apply(), ScriptedWidgetEventHandler::Apply(), UIScriptedMenu::Back(), EntityAI::Building(), DayZIntroSceneXbox::CameraCreate(), CCTWaterSurface::Can(), TrapSpawnBase::CanBePlaced(), UIScriptedMenu::Cancel(), InventoryItem::CanObstruct(), UIScriptedMenu::ChangeAccount(), DayZIntroScenePC::CharacterRotate(), DayZIntroScenePC::CharacterRotationStart(), Managed::CharacterUnload(), DrowningMdfr::CheckIsDrowning(), Environment::CheckWaterContact(), UIScriptedMenu::CloseMapMenu(), Environment::CollectAndSetEnvironmentData(), UIScriptedMenu::ConnectLastSession(), CreateGame(), CreateItemBasePiles(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), CreateMission(), Managed::CreateNewCharacter(), ActionSkinning::CreateOrgan(), ItemBase::CreatePlant(), Hologram::CreateTrigger(), DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), DayZPlayerCameraBase(), PPEffects::DisableBurlapSackBlindness(), DisconnectSessionScript(), EarlyAccessDialog(), ItemBase::EEItemAttached(), PPEffects::EnableBurlapSackBlindness(), LoadingScreen::EndLoading(), MenuDefaultCharacterData::EquipDefaultCharacter(), EvaluateDamageInternal(), ActionTargets::FilterObstructedObjectsEx(), FlashbangEffect::FlashbangEffect(), PluginConfigDebugProfile::GetAllPositionsNames(), OnlineServices::GetCurrentServerInfo(), GetDayZGame(), Environment::GetDebugMessage(), Environment::GetEnvironmentTemperature(), PluginConfigHandler::GetFileName(), UIScriptedMenu::GetFiltredConfigClasses(), UIScriptedMenu::GetItemNamesForSlots(), Liquid::GetLiquidConfigProperty(), PluginConfigDebugProfile::GetPositionByName(), DayZIntroScene::GetSelectedUserName(), Environment::GetWindModifierPerSurface(), CGame::GetWorldName(), HandleDeath(), HudDebugWinBase::HudDebugWinVersion(), UIScriptedMenu::HudShow(), ErrorModuleHandler::Init(), WorldData::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Init(), GameplayEffectsData::Init(), Hud::Init(), Liquid::InitAllLiquids(), SelectionTranslation::InitTranslatedSelections(), InventoryMenu(), ScriptedWidgetEventHandler::IsChanged(), CGame::IsMissionMainMenu(), IsObjectObstructedEx(), InventoryItem::IsServerCheck(), Hologram::IsUnderwater(), LanguageChanged(), UIScriptedMenu::Leave(), Managed::LoadCharacterData(), UIScriptedMenu::LoadData(), LoadingScreen::LoadingScreen(), UIScriptedMenu::LoginQueueBase(), UIScriptedMenu::LoginTimeBase(), UIScriptedMenu::LogoutMenu(), PlayerPreview::MouseButtonDown(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), UIScriptedMenu::OnAttemptSelectPreset(), UIScriptedMenu::OnAttemptTabSwitch(), OnlineServices::OnAutoConnectToEmptyServer(), WeatherPhenomenon::OnBeforeChange(), InventoryItem::OnCEUpdate(), UIScriptedMenu::OnClick(), BlindedMdfr::OnDeactivate(), PluginBase::OnDestroy(), ManBase::OnDisconnect(), MapHandler::OnDoubleClick(), BarbedWireTrigger::OnEnter(), OnEvent(), ConnectErrorClientModule::OnEvent(), ConnectErrorServerModule::OnEvent(), ActionBuryBody::OnFinishProgressServer(), OnFinishProgressServer(), ActionSkinning::OnFinishProgressServer(), BiosUserManager::OnGameNameChanged(), Input::OnGamepadConnected(), Input::OnGamepadDisconnected(), Input::OnGamepadIdentification(), BiosSessionService::OnGetGameplaySession(), BiosSessionService::OnGetSessionError(), PluginConfigHandler::OnInit(), MissionBase::OnInit(), BiosUserManager::OnJoin(), UIScriptedMenu::OnKeyPress(), OnlineServices::OnLoadMPPrivilege(), OnlineServices::OnLoadVoicePrivilege(), BiosUserManager::OnLoggedOn(), MissionBase::OnMissionFinish(), MissionBase::OnMissionStart(), ConnectErrorScriptModuleUI::OnModalResult(), UIScriptedMenu::OnModalResult(), UIScriptedMenu::OnMouseButtonDown(), BiosUserManager::OnPartyHost(), ManBase::OnPlayerLoaded(), MissionBase::OnPlayerRespawned(), WrittenNoteData::OnRPC(), UIScriptedMenu::OnShow(), BiosUserManager::OnSignedOut(), AreaDamageLooped::OnStayStartServerEvent(), BlindedMdfr::OnTick(), AreaDamageLooped::OnTriggerCreated(), ManBase::OnUnconsciousStop(), MissionBase::OnUpdate(), BiosUserManager::OnUserDatabaseId(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), PassFilter(), MissionBase::Pause(), UIScriptedMenu::Play(), PluginBase::PrintLogClient(), UIScriptedMenu::Refresh(), ScriptedWidgetEventHandler::Revert(), UIScriptedMenu::SaveData(), PluginBase::ScriptHistoryBack(), PluginBase::ScriptHistoryNext(), SelectionTranslation::SearchAndTranslate(), BiosUserManager::SelectUserEx(), Managed::SetAttachment(), PPEffects::SetEVValuePP(), UIScriptedMenu::SetFavoriteConsoles(), PPEDOF::SetFinalParameterValue(), PPEExposureNative::SetFinalParameterValue(), PPEEyeAccomodationNative::SetFinalParameterValue(), PPELightIntensityParamsNative::SetFinalParameterValue(), ManBase::SetNewCharName(), PPEffects::SetNVParams(), BarbedWireTrigger::SetParentObject(), UIScriptedMenu::SetServerInfo(), UIScriptedMenu::SetToDefaults(), ScriptedWidgetEventHandler::SetToDefaults(), Managed::SetupPlayerName(), ConnectionLost::Show(), SimulateDeath(), StdFovUpdate(), ClientData::SyncEvent_OnRecievedPlayerList(), Barrel_ColorBase::TanPelts(), UIScriptedMenu::TitleScreenMenu(), PluginBase::ToggleHelpScreen(), PluginBase::ToggleMissionLoader(), PluginBase::ToggleScriptConsole(), UIScriptedMenu::TryConnectLastSession(), BiosSessionService::TryGetSession(), ScriptedWidgetEventHandler::Update(), Update(), UIScriptedMenu::Update(), ScriptedWidgetEventHandler::UpdateFOVOption(), AreaDamageTriggerBase::UpdateInsiders(), Trigger::UpdateInsiders(), ManBase::UpdatePlayerMeasures(), DayZIntroSceneXbox::UpdateSelectedUserName(), Hologram::UpdateSelections(), GameplayEffectsData::UpdateVisibility(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::ValidateAndRepairHelper(), WorldData::WeatherOnBeforeChange(), ~DayZGame(), UIScriptedMenu::~LoginQueueBase(), UIScriptedMenu::~LoginTimeBase(), UIScriptedMenu::~LogoutMenu(), MissionBase::~MissionGameplay(), and ScriptedWidgetEventHandler::~OptionsMenuGame().
JOIN
class DayZProfilesOptions JOIN
JOIN_CONTROLLER_SELECT
class DayZProfilesOptions JOIN_CONTROLLER_SELECT
JOIN_START
class DayZProfilesOptions JOIN_START
JOIN_USER_SELECT
class DayZProfilesOptions JOIN_USER_SELECT
m_AimLoggingEnabled
private bool m_AimLoggingEnabled
Definition at line 752 of file dayzgame.c.
Referenced by DayZGame(), and IsAimLogEnabled().
m_AmmoShakeParams
ref AmmoCamParams m_AmmoShakeParams = new AmmoCamParams() static
Definition at line 770 of file dayzgame.c.
Referenced by ExplosionEffects().
m_ArtySound
private ref EffectSound m_ArtySound
Definition at line 782 of file dayzgame.c.
Referenced by OnRPC().
m_Backlit
private ref Backlit m_Backlit
Definition at line 774 of file dayzgame.c.
Referenced by DayZGame(), and GetBacklit().
m_callQueue
private ref ScriptCallQueue m_callQueue[CALL_CATEGORY_COUNT]
Definition at line 732 of file dayzgame.c.
Referenced by DayZGame(), and GetCallQueue().
m_CharClassNames
private ref array<string> m_CharClassNames = new array<string>()
Definition at line 776 of file dayzgame.c.
Referenced by CreateDefaultPlayer(), CreateRandomPlayer(), DayZGame(), and ListAvailableCharacters().
m_ConnectAddress
protected string m_ConnectAddress
Definition at line 1720 of file dayzgame.c.
Referenced by Connect(), ConnectFromCLI(), ConnectFromJoin(), ConnectFromServerBrowser(), RefreshCurrentServerInfo(), and TryConnect().
m_ConnectFromJoin
private bool m_ConnectFromJoin
Definition at line 757 of file dayzgame.c.
Referenced by ConnectFromCLI(), ConnectFromJoin(), ConnectFromServerBrowser(), DayZGame(), and OnEvent().
m_connectionLost
private ref ConnectionLost m_connectionLost
Definition at line 730 of file dayzgame.c.
Referenced by OnMPConnectionLostEvent().
m_ConnectPassword
protected string m_ConnectPassword
Definition at line 1722 of file dayzgame.c.
Referenced by Connect(), ConnectFromCLI(), and ConnectFromServerBrowser().
m_ConnectPort
protected int m_ConnectPort
Definition at line 1721 of file dayzgame.c.
Referenced by Connect(), ConnectFromCLI(), ConnectFromJoin(), ConnectFromServerBrowser(), RefreshCurrentServerInfo(), and TryConnect().
m_CrashSound
private ref EffectSound m_CrashSound
Definition at line 779 of file dayzgame.c.
Referenced by OnRPC().
m_DatabaseID
protected string m_DatabaseID
Definition at line 1718 of file dayzgame.c.
Referenced by GetDatabaseID(), and SetDatabaseID().
m_DayZProfileOptions
private ref DayZProfilesOptions m_DayZProfileOptions
Definition at line 735 of file dayzgame.c.
Referenced by DayZGame(), GetProfileOption(), GetProfileOptionDefault(), GetProfileOptionMap(), RegisterProfilesOptions(), ResetProfileOptions(), and SetProfileOption().
m_dragQueue
private ref DragQueue m_dragQueue
Definition at line 734 of file dayzgame.c.
Referenced by DayZGame(), and GetDragQueue().
m_early_access_dialog_accepted
private bool m_early_access_dialog_accepted
Definition at line 736 of file dayzgame.c.
Referenced by DayZGame(), and EarlyAccessDialog().
m_EVValue
float m_EVValue = 0
Definition at line 768 of file dayzgame.c.
Referenced by GetCurrentEVValue(), and SetEVValue().
m_FirstConnect
protected bool m_FirstConnect = true
Definition at line 722 of file dayzgame.c.
Referenced by OnEvent().
m_FoodDecayModifier
private float m_FoodDecayModifier
Definition at line 748 of file dayzgame.c.
Referenced by GetFoodDecayModifier(), and GlobalsInit().
m_GamepadDisconnectMenu
protected ref Widget m_GamepadDisconnectMenu
Definition at line 1715 of file dayzgame.c.
Referenced by CreateGamepadDisconnectMenu(), and DeleteGamepadDisconnectMenu().
m_GameState
protected DayZGameState m_GameState
Definition at line 719 of file dayzgame.c.
Referenced by CreateGamepadDisconnectMenu(), GetGameState(), and SetGameState().
m_IntroMenu
protected ref Widget m_IntroMenu
Definition at line 1714 of file dayzgame.c.
Referenced by CreateTitleScreen(), DeleteTitleScreen(), and GamepadCheck().
m_IsConnecting
private bool m_IsConnecting
Definition at line 756 of file dayzgame.c.
Referenced by DayZGame(), IsConnecting(), OnUpdate(), and SetConnecting().
m_IsCtrlHolding
private bool m_IsCtrlHolding
Definition at line 741 of file dayzgame.c.
Referenced by IsLeftCtrlDown(), OnDeviceReset(), OnKeyPress(), and OnKeyRelease().
m_IsFoodDecayEnabled
private bool m_IsFoodDecayEnabled = true
Definition at line 747 of file dayzgame.c.
m_IsLeftAltHolding
private bool m_IsLeftAltHolding
Definition at line 743 of file dayzgame.c.
Referenced by OnDeviceReset(), OnKeyPress(), and OnKeyRelease().
m_IsNewCharacter
private bool m_IsNewCharacter
Definition at line 755 of file dayzgame.c.
Referenced by IsNewCharacter(), and SetNewCharacter().
m_IsRightAltHolding
private bool m_IsRightAltHolding
Definition at line 744 of file dayzgame.c.
Referenced by OnDeviceReset(), OnKeyPress(), and OnKeyRelease().
m_IsStressTest
private bool m_IsStressTest
Definition at line 751 of file dayzgame.c.
Referenced by DayZGame(), and IsStressTest().
m_IsWinHolding
private bool m_IsWinHolding
Definition at line 742 of file dayzgame.c.
Referenced by OnDeviceReset(), and OnKeyRelease().
m_IsWorldWetTempUpdateEnabled
private bool m_IsWorldWetTempUpdateEnabled = true
Definition at line 746 of file dayzgame.c.
Referenced by GlobalsInit(), and IsWorldWetTempUpdateEnabled().
m_keyboard_handler
private UIScriptedMenu m_keyboard_handler
Definition at line 737 of file dayzgame.c.
Referenced by DayZGame(), OnKeyPress(), OnKeyRelease(), and SetKeyboardHandle().
m_loading
ref LoadingScreen m_loading
Definition at line 725 of file dayzgame.c.
Referenced by CheckDialogs(), DayZGame(), IsLoading(), LoadingHide(), LoadingShow(), LoadProgressUpdate(), OnEvent(), and OnUpdate().
m_LoadState
protected DayZLoadState m_LoadState
Definition at line 720 of file dayzgame.c.
Referenced by GetLoadState(), LoadingHide(), and SetLoadState().
m_LoginQueue
private ref LoginQueueBase m_LoginQueue
Definition at line 727 of file dayzgame.c.
Referenced by CancelLoginQueue(), EnterLoginQueue(), and UpdateLoginQueue().
m_LoginTime
private int m_LoginTime
Definition at line 728 of file dayzgame.c.
Referenced by DayZGame(), LoginTimeCountdown(), OnLoginTimeEvent(), and OnRespawnEvent().
m_LoginTimeScreen
private ref LoginTimeBase m_LoginTimeScreen
Definition at line 726 of file dayzgame.c.
Referenced by CancelLoginTimeCountdown(), EnterLoginTime(), LoginTimeCountdown(), OnEvent(), OnLoginTimeEvent(), OnPreloadEvent(), OnRespawnEvent(), and OnUpdate().
m_mission_module
private ScriptModule m_mission_module
Definition at line 738 of file dayzgame.c.
m_MissionFolderPath
private string m_MissionFolderPath
Definition at line 740 of file dayzgame.c.
Referenced by GetMissionFolderPath(), and SetMissionPath().
m_MissionPath
private string m_MissionPath
Definition at line 739 of file dayzgame.c.
Referenced by GetMissionPath(), ReloadMission(), and SetMissionPath().
m_MissionState
private int m_MissionState
Definition at line 716 of file dayzgame.c.
Referenced by DayZGame(), GetMissionState(), and SetMissionState().
m_NoiseParams
ref NoiseParams m_NoiseParams = new NoiseParams() static
Definition at line 785 of file dayzgame.c.
m_Notifications
protected ref NotificationUI m_Notifications
Definition at line 721 of file dayzgame.c.
Referenced by AddVoiceNotification(), InitNotifications(), OnEvent(), OnUpdate(), and RemoveVoiceNotification().
m_OriginalCharactersCount
int m_OriginalCharactersCount
Definition at line 753 of file dayzgame.c.
Referenced by InitCharacterMenuDataInfo().
m_PlayerName
private string m_PlayerName
Definition at line 754 of file dayzgame.c.
Referenced by GetPlayerGameName(), PluginBase::GetPlayerPrefix(), UIScriptedMenu::Init(), UIScriptedMenu::OnChangeCharacter(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), UIScriptedMenu::Refresh(), and SetPlayerGameName().
m_PrevBlur
protected int m_PrevBlur
Definition at line 1716 of file dayzgame.c.
m_PreviousEVValue
float m_PreviousEVValue
Definition at line 767 of file dayzgame.c.
Referenced by GetPreviousEVValue(), and SetEVValue().
m_PreviousGamepad
private int m_PreviousGamepad
Definition at line 759 of file dayzgame.c.
Referenced by GetPreviousGamepad(), and SetPreviousGamepad().
m_ReportModded
bool m_ReportModded static
Definition at line 750 of file dayzgame.c.
Referenced by DayZGame(), and ReportModded().
m_ShouldShowControllerDisconnect
private bool m_ShouldShowControllerDisconnect
Definition at line 758 of file dayzgame.c.
Referenced by CreateGamepadDisconnectMenu(), DeleteGamepadDisconnectMenu(), OnEvent(), and ShouldShowControllerDisconnect().
m_timerQueue
private ref TimerQueue m_timerQueue[CALL_CATEGORY_COUNT]
Definition at line 731 of file dayzgame.c.
Referenced by DayZGame(), and GetTimerQueue().
m_updateQueue
private ref ScriptInvoker m_updateQueue[CALL_CATEGORY_COUNT]
Definition at line 733 of file dayzgame.c.
Referenced by DayZGame(), and GetUpdateQueue().
m_UserFOV
private float m_UserFOV
Definition at line 760 of file dayzgame.c.
Referenced by DeferredInit(), GetUserFOV(), and SetUserFOV().
m_Visited
protected ref TStringArray m_Visited
Definition at line 1725 of file dayzgame.c.
Referenced by AddVisitedServer(), GetLastVisitedServer(), IsVisited(), and OnInitialize().
m_volume_music
float m_volume_music
Definition at line 763 of file dayzgame.c.
Referenced by DeferredInit().
m_volume_radio
float m_volume_radio
Definition at line 765 of file dayzgame.c.
Referenced by DeferredInit().
m_volume_sound
float m_volume_sound
Definition at line 761 of file dayzgame.c.
Referenced by DeferredInit().
m_volume_speechEX
float m_volume_speechEX
Definition at line 762 of file dayzgame.c.
Referenced by DeferredInit().
m_volume_VOIP
float m_volume_VOIP
Definition at line 764 of file dayzgame.c.
Referenced by DeferredInit().
MAIN_MENU
class DayZProfilesOptions MAIN_MENU
MAIN_MENU_CONTROLLER_SELECT
class DayZProfilesOptions MAIN_MENU_CONTROLLER_SELECT
MAIN_MENU_START
class DayZProfilesOptions MAIN_MENU_START
MAIN_MENU_USER_SELECT
class DayZProfilesOptions MAIN_MENU_USER_SELECT
MAX_VISITED
protected const int MAX_VISITED = 50
Definition at line 1724 of file dayzgame.c.
Referenced by AddVisitedServer().
MIN_ARTY_SOUND_RANGE
private const int MIN_ARTY_SOUND_RANGE = 300
Definition at line 783 of file dayzgame.c.
Referenced by OnRPC().
MISSION_START
class DayZProfilesOptions MISSION_START
MISSION_STATE_FINNISH
const int MISSION_STATE_FINNISH = 2
Definition at line 714 of file dayzgame.c.
MISSION_STATE_GAME
const int MISSION_STATE_GAME = 1
Definition at line 713 of file dayzgame.c.
Referenced by DayZGame().
MISSION_STATE_MAINMENU
class DayZProfilesOptions MISSION_STATE_MAINMENU = 0
MISSION_USER_SELECT
class DayZProfilesOptions MISSION_USER_SELECT
PARTY
class DayZProfilesOptions PARTY
PARTY_CONTROLLER_SELECT
class DayZProfilesOptions PARTY_CONTROLLER_SELECT
PARTY_START
class DayZProfilesOptions PARTY_START
PARTY_USER_SELECT
class DayZProfilesOptions PARTY_USER_SELECT
UNDEFINED
class DayZProfilesOptions UNDEFINED