DayzKode: P:/scripts/4_world/DayZ/entities/dayzplayerimplementmeleecombat.c File Reference
dayzplayerimplementmeleecombat.c File Reference
Enumerations
enum EMeleeHitType {
NONE = -1 , LIGHT , HEAVY , SPRINT ,
KICK , FINISHER_LIVERSTAB , FINISHER_NECKSTAB , FINISHER_GENERIC ,
WPN_HIT , WPN_HIT_BUTTSTOCK , WPN_STAB , WPN_STAB_FINISHER
}
Functions
protected bool CanObjectBeTargeted (Object obj, bool checkNonAligneAble=false)
void CheckMeleeItem ()
void DayZPlayerImplementMeleeCombat (DayZPlayerImplement player)
protected int DetermineSpecificFinisherType (ItemBase weapon)
protected float GetAngle ()
int GetFinisherType ()
vector GetHitPos ()
EMeleeHitType GetHitType ()
int GetHitZoneIdx ()
component idx
protected float GetRange ()
EntityAI GetTargetEntity ()
int GetWeaponMode ()
protected float GetWeaponRange (InventoryItem weapon, int weaponMode)
protected void HitZoneSelection ()
DEPRECATED.
protected bool HitZoneSelectionRaycast (out vector hitPos, out int hitZone, out Object target, bool useCamera)
protected bool HitZoneSelectionRaycastHelper (out vector hitPos, out int hitZone, out Object target)
void Init (DayZPlayerImplement player)
protected void InternalResetTarget ()
private bool IsEntityBehindEntityInAngle (EntityAI source, EntityAI target, float angle)
protected bool IsObstructed (Object object)
DEPRECATED - New function in MeleeTargeting.
void Reset (InventoryItem weapon, EMeleeHitType hitMask, bool wasHitEvent=false)
void ResetTarget ()
protected int SelectWeaponMode (InventoryItem weapon)
void SetFinisherType (int pFinisherType)
void SetHitPos (vector pHitPos)
void SetHitZoneIdx (int pHitZone)
protected void SetTarget (Object obj, vector hitPos, int hitZone)
void SetTargetObject (Object pTarget)
protected void TargetSelection ()
protected int TrySelectFinisherType (InventoryItem weapon, EntityAI target)
General condition for finisher attacks.
void Update (InventoryItem weapon, EMeleeHitType hitMask, bool wasHitEvent=false)
void ~DayZPlayerImplementMeleeCombat ()
Variables
protected const string DEFAULT_HIT_ZONE = "Torso"
DEPRECATED: "HitZoneSelection".
protected ref array< Object > m_AllTargetObjects
All potential targets found during most recent TargetSelection.
protected ref array< string > m_BlacklistedDamageZones
List of blacklisted damage zone names (cannot use indices due to the possible changes when p3d components are recalculated)
private int m_DebugForcedFinisherType
protected DayZPlayerImplement m_DZPlayer
Parent.
protected int m_FinisherType
protected bool m_ForceUntargetable
Misc - cache.
protected vector m_HitPositionWS
Most recent target position.
protected EMeleeHitType m_HitType
Hit type of the most recent attack.
protected int m_HitZoneIdx
Hit result - cache.
protected string m_HitZoneName
Most recent target HitZone name.
protected ref MeleeTargeting m_MeleeTargeting
Target selecting "component".
protected ref array< typename > m_NonAlignableObjects
Typenames of objects that can be targeted, but are not a priority (3rd Pass)
protected vector m_RayEnd
End position of most recent HitZoneSelectionRaycast.
protected vector m_RayEndShort
DEPRECATED: "HitZoneSelection".
protected vector m_RayStart
Start position of most recent HitZoneSelectionRaycast.
protected bool m_SprintAttack
If most recent attack was a sprint attack.
protected ref array< typename > m_TargetableObjects
Typenames of all directly/preferred targetable objects (1st Pass + 2nd Pass)
protected Object m_TargetObject
Targets - types.
protected EMeleeTargetType m_TargetType
DEPRECATED: Was added but never used..?
protected bool m_WasHit
If most recent attack was.
protected InventoryItem m_Weapon
Weapons - cache.
protected int m_WeaponMode
WeaponMode used during most recent Update.
protected float m_WeaponRange
WeaponRange used during most recent Update.
protected const float RANGE_EXTENDER_NORMAL = 0.65
General range extension.
protected const float RANGE_EXTENDER_SPRINT = 1.35
General range extension while in sprint.
enum EMeleeHitType TARGETING_ANGLE_NORMAL = 30.0
Target selection settings.
protected const float TARGETING_ANGLE_SPRINT = 15.0
Second Pass: Half angle of cone during sprint.
protected const float TARGETING_MAX_HEIGHT = 2.0
Second Pass: How high the cone goes in meters from player position.
protected const float TARGETING_MIN_HEIGHT = -2.0
Second Pass: How deep the cone goes in meters from player position.
protected const float TARGETING_RAY_DIST = 5.0
DEPRECATED: "HitZoneSelection".
protected const float TARGETING_RAY_DIST_SHORT = 2.0
DEPRECATED: "HitZoneSelection".
protected const float TARGETING_RAY_RADIUS = 0.25
DEPRECATED: "HitZoneSelection".
protected const float TARGETING_RAY_RADIUS_EX = 0.5
Second Pass: Max distance from ray projected from player looking direction.
Enumeration Type Documentation
EMeleeHitType
enum EMeleeHitType
Enumerator
NONE
LIGHT
HEAVY
SPRINT
KICK
FINISHER_LIVERSTAB
FINISHER_NECKSTAB
FINISHER_GENERIC
WPN_HIT
WPN_HIT_BUTTSTOCK
WPN_STAB
WPN_STAB_FINISHER
Definition at line 1 of file dayzplayerimplementmeleecombat.c.
{
    NONE = -1,
    LIGHT,
    HEAVY,
    SPRINT,
    KICK,
    FINISHER_LIVERSTAB,
    FINISHER_NECKSTAB,
    FINISHER_GENERIC,
    WPN_HIT,
    WPN_HIT_BUTTSTOCK,
    WPN_STAB,
    WPN_STAB_FINISHER,
}
Function Documentation
CanObjectBeTargeted()
protected bool CanObjectBeTargeted (Object obj, bool checkNonAligneAble = false)
Definition at line 516 of file dayzplayerimplementmeleecombat.c.
    {
        return obj && obj.IsAlive() && ( obj.IsAnyInherited(m_TargetableObjects) || (checkNonAligneAble && obj.IsAnyInherited(m_NonAlignableObjects)) );
    }
References m_NonAlignableObjects, and m_TargetableObjects.
Referenced by TargetSelection().
CheckMeleeItem()
void CheckMeleeItem ()
Definition at line 248 of file dayzplayerimplementmeleecombat.c.
    {
        if (m_Weapon)
        {
            ItemBase item = ItemBase.Cast(m_Weapon.ProcessMeleeItemDamage(GetWeaponMode()));
            if (item && item.GetHierarchyRootPlayer())
            {
                PlayerBase.Cast(item.GetHierarchyRootPlayer()).SetCheckMeleeItem(item);
            }
            else if (m_Weapon && m_Weapon.GetHierarchyRootPlayer())
            {
                PlayerBase.Cast(m_Weapon.GetHierarchyRootPlayer()).SetCheckMeleeItem(ItemBase.Cast(m_Weapon));
            }
        }
    }
References GetWeaponMode(), and m_Weapon.
DayZPlayerImplementMeleeCombat()
void DayZPlayerImplementMeleeCombat (DayZPlayerImplement player)
Definition at line 90 of file dayzplayerimplementmeleecombat.c.
    {
        Init(player);
    }
References Init().
Referenced by DayZPlayerImplement().
DetermineSpecificFinisherType()
protected int DetermineSpecificFinisherType (ItemBase weapon)
Definition at line 475 of file dayzplayerimplementmeleecombat.c.
    {
        if (m_DebugForcedFinisherType > -1)
        {
            array<int> finishers = {
                EMeleeHitType.FINISHER_LIVERSTAB,
                EMeleeHitType.FINISHER_NECKSTAB
            };
            return finishers[m_DebugForcedFinisherType];
        }
        if (!weapon || !weapon.GetValidFinishers() || weapon.GetValidFinishers().Count() == 0)
        {
            return EMeleeHitType.FINISHER_LIVERSTAB;
        }
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        int idx = Math.Round(Math.Lerp(0, weapon.GetValidFinishers().Count() - 1, player.GetRandomGeneratorSyncManager().GetRandom01(RandomGeneratorSyncUsage.RGSGeneric)));
        return weapon.GetValidFinishers()[idx];
    }
References Math::Lerp(), m_DebugForcedFinisherType, m_DZPlayer, and Math::Round().
Referenced by TrySelectFinisherType().
GetAngle()
protected float GetAngle ()
Definition at line 326 of file dayzplayerimplementmeleecombat.c.
    {
        if (m_SprintAttack)
            return TARGETING_ANGLE_SPRINT;
        else
            return TARGETING_ANGLE_NORMAL;
    }
References m_SprintAttack, TARGETING_ANGLE_NORMAL, and TARGETING_ANGLE_SPRINT.
Referenced by TargetSelection().
GetFinisherType()
int GetFinisherType ()
Definition at line 177 of file dayzplayerimplementmeleecombat.c.
    {
        return m_FinisherType;
    }
References m_FinisherType.
GetHitPos()
vector GetHitPos ()
Definition at line 167 of file dayzplayerimplementmeleecombat.c.
    {
        return m_HitPositionWS;
    }
References m_HitPositionWS.
GetHitType()
EMeleeHitType GetHitType ()
Definition at line 141 of file dayzplayerimplementmeleecombat.c.
    {
        return m_HitType;
    }
References m_HitType.
GetHitZoneIdx()
int GetHitZoneIdx ()
component idx
Definition at line 162 of file dayzplayerimplementmeleecombat.c.
    {
        return m_HitZoneIdx;
    }
References m_HitZoneIdx.
GetRange()
protected float GetRange ()
Definition at line 321 of file dayzplayerimplementmeleecombat.c.
    {
        return m_WeaponRange + RANGE_EXTENDER_NORMAL;
    }
References m_WeaponRange, and RANGE_EXTENDER_NORMAL.
Referenced by HitZoneSelectionRaycast(), and TargetSelection().
GetTargetEntity()
EntityAI GetTargetEntity ()
Definition at line 151 of file dayzplayerimplementmeleecombat.c.
    {
        return EntityAI.Cast(m_TargetObject);
    }
References m_TargetObject.
Referenced by Update().
GetWeaponMode()
int GetWeaponMode ()
Definition at line 187 of file dayzplayerimplementmeleecombat.c.
    {
        return m_WeaponMode;
    }
References m_WeaponMode.
Referenced by CheckMeleeItem(), and HitZoneSelection().
GetWeaponRange()
protected float GetWeaponRange (InventoryItem weapon, int weaponMode)
Definition at line 313 of file dayzplayerimplementmeleecombat.c.
    {
        if ( weapon )
            return weapon.GetMeleeCombatData().GetModeRange(weaponMode);
        else
            return m_DZPlayer.GetMeleeCombatData().GetModeRange(weaponMode);
    }
References m_DZPlayer.
Referenced by HitZoneSelection(), and Reset().
HitZoneSelection()
protected void HitZoneSelection ()
DEPRECATED.
make sure we are in range of the current weapon;
2d only
just for building and transports (big objects)
if no object in cone, set this object from raycast for these special cases
Definition at line 588 of file dayzplayerimplementmeleecombat.c.
    {
        Object cursorTarget = null;
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        // ray properties
        vector pos;
        vector cameraDirection = GetGame().GetCurrentCameraDirection();
        MiscGameplayFunctions.GetHeadBonePos(player, pos);
        m_RayStart = pos;
        m_RayEnd = pos + cameraDirection * TARGETING_RAY_DIST;
        m_RayEndShort = pos + cameraDirection * TARGETING_RAY_DIST_SHORT;
        // raycast
        set<Object> hitObjects = new set<Object>;
        int hitComponentIndex;
        float hitFraction;
        vector start, end, hitNormal, hitPosObstructed;
        PhxInteractionLayers collisionLayerMask = PhxInteractionLayers.DEFAULT;
        if ( !DayZPhysics.RaycastRV(m_RayStart, m_RayEndShort, m_HitPositionWS, hitNormal, m_HitZoneIdx, hitObjects, null, player, false, false, ObjIntersectIFire) && !DayZPhysics.RaycastRV(m_RayStart, m_RayEnd, m_HitPositionWS, hitNormal, m_HitZoneIdx, hitObjects, null, player, false, false, ObjIntersectIFire, TARGETING_RAY_RADIUS) )
        {
            m_HitZoneIdx = -1;
            //Print("HitZoneSelection failed");
        }
        else if ( hitObjects.Count() > 0 )
        {
            cursorTarget = hitObjects.Get(0);
            vector playerPos = m_DZPlayer.GetPosition();
            vector hitPos = m_HitPositionWS;
            playerPos[1] = 0;
            hitPos[1] = 0;
            if ( cursorTarget.IsAnyInherited(m_NonAlignableObjects) && vector.Distance(playerPos, hitPos) <= GetWeaponRange(m_Weapon, GetWeaponMode()))
            {
                if (m_TargetObject == null)
                {
                    m_TargetObject = cursorTarget;
                }
            }
            if (cursorTarget == m_TargetObject)
            {
                m_HitZoneName = cursorTarget.GetDamageZoneNameByComponentIndex(m_HitZoneIdx);
                //Print("hit object: " + m_TargetObject + " | component idx: " + m_HitZoneIdx + " | hitzone name: " + m_HitZoneName);
            }
            else
            {
                if (m_TargetObject == DayZInfected.Cast(m_TargetObject) || m_TargetObject == PlayerBase.Cast(m_TargetObject))
                m_HitZoneName = DEFAULT_HIT_ZONE; //Default to torso if no zone is targeted
            }
        }
        else
        {
            m_HitZoneIdx = -1;
            //Print("HitZoneSelection failed");
        }
    }
References DEFAULT_HIT_ZONE, vector::Distance(), CGame::GetCurrentCameraDirection(), GetGame(), GetWeaponMode(), GetWeaponRange(), m_DZPlayer, m_HitPositionWS, m_HitZoneIdx, m_HitZoneName, m_NonAlignableObjects, m_RayEnd, m_RayEndShort, m_RayStart, m_TargetObject, m_Weapon, DayZPhysics::RaycastRV(), TARGETING_RAY_DIST, TARGETING_RAY_DIST_SHORT, and TARGETING_RAY_RADIUS.
HitZoneSelectionRaycast()
protected bool HitZoneSelectionRaycast (out vector hitPos, out int hitZone, out Object target, bool useCamera)
Prevents targeting of objects behind player
Opponent is inside car - targeting range is shorter in that case
Definition at line 530 of file dayzplayerimplementmeleecombat.c.
    {
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        vector pos;
        vector dir;
        vector playerDir;
        if (useCamera)
        { // What the player camera is looking at (crosshair)
            vector cameraRotation;
            player.GetCurrentCameraTransform(pos, dir, cameraRotation);
            playerDir = dir;
        }
        else
        { // What the player himself is looking at
            playerDir = MiscGameplayFunctions.GetHeadingVector(player);
            dir = GetGame().GetCurrentCameraDirection();
            MiscGameplayFunctions.GetHeadBonePos(player, pos);
        }
        if (vector.Dot(dir, playerDir) < 0.5)
        {
            return false;
        }
        m_RayStart = pos;
        m_RayEnd = m_RayStart + GetRange() * dir;
        // raycast
        set<Object> hitObjects = new set<Object>;
        vector hitNormal;
        if ( DayZPhysics.RaycastRV(m_RayStart, m_RayEnd, hitPos, hitNormal, hitZone, hitObjects, null, player, false, false, ObjIntersectIFire) && hitObjects.Count() > 0 )
        {
            target = hitObjects[0];
            m_ForceUntargetable = false;
            PlayerBase playerTarget = PlayerBase.Cast(target);
            if (playerTarget && playerTarget.IsInVehicle())
            {
                if (vector.DistanceSq(pos, hitPos) > Math.SqrFloat(GetRange() * 0.5))
                {
                    m_ForceUntargetable = true;
                    target = null;
                    hitPos = vector.Zero;
                    hitZone = -1;
                }
            }
            return true;
        }
        return false;
    }
References vector::DistanceSq(), vector::Dot(), CGame::GetCurrentCameraDirection(), GetGame(), GetRange(), m_DZPlayer, m_ForceUntargetable, m_RayEnd, m_RayStart, DayZPhysics::RaycastRV(), Math::SqrFloat(), and vector::Zero.
Referenced by HitZoneSelectionRaycastHelper().
HitZoneSelectionRaycastHelper()
protected bool HitZoneSelectionRaycastHelper (out vector hitPos, out int hitZone, out Object target)
Definition at line 521 of file dayzplayerimplementmeleecombat.c.
    {
        return HitZoneSelectionRaycast(hitPos, hitZone, target, false);
        // Not sure if desired, as it can give some results that feel a little odd
        // But it will depend entirely on the player and situation..
        // I guess the crosshair is hidden while melee anyways though
        // || ( m_DZPlayer.IsInThirdPerson() && HitZoneSelectionRaycast(hitPos, hitZone, target, true);
    }
References HitZoneSelectionRaycast().
Referenced by TargetSelection().
Init()
void Init (DayZPlayerImplement player)
Definition at line 95 of file dayzplayerimplementmeleecombat.c.
    {
        m_DZPlayer      = player;
        m_MeleeTargeting = new MeleeTargeting;
        m_HitZoneName   = "";
        m_HitZoneIdx    = -1;
        m_FinisherType  = -1;
        m_HitPositionWS = vector.Zero;
        m_SprintAttack  = false;
        m_WasHit        = false;
        m_TargetObject      = null;
        m_TargetType        = EMeleeTargetType.ALIGNABLE;
        m_AllTargetObjects  = new array<Object>;
        #ifdef DEVELOPER
        m_AllPreviousTargetObjects = new array<Object>;
        #endif
        m_DebugForcedFinisherType =  -1;
        m_TargetableObjects = new array<typename>; //checks against CONFIG hierarchy
        m_TargetableObjects.Insert(DayZPlayer);
        m_TargetableObjects.Insert(DayZInfected);
        m_TargetableObjects.Insert(DayZAnimal);
        m_NonAlignableObjects = new array<typename>;
        m_NonAlignableObjects.Insert(Building);
        m_NonAlignableObjects.Insert(Car);
        m_NonAlignableObjects.Insert(CarWheel);
        m_NonAlignableObjects.Insert(CarDoor);
        m_NonAlignableObjects.Insert(TentBase);
        m_NonAlignableObjects.Insert(BaseBuildingBase);
        m_BlacklistedDamageZones = new array<string>;
        m_BlacklistedDamageZones.Insert("Brain");
    }
References m_AllTargetObjects, m_BlacklistedDamageZones, m_DebugForcedFinisherType, m_DZPlayer, m_FinisherType, m_HitPositionWS, m_HitZoneIdx, m_HitZoneName, m_MeleeTargeting, m_NonAlignableObjects, m_SprintAttack, m_TargetableObjects, m_TargetObject, m_TargetType, m_WasHit, and vector::Zero.
InternalResetTarget()
protected void InternalResetTarget ()
Definition at line 497 of file dayzplayerimplementmeleecombat.c.
    {
        m_TargetObject  = null;
        m_HitPositionWS = vector.Zero;
        m_HitZoneIdx    = -1;
        m_HitZoneName   = "";
    }
References m_HitPositionWS, m_HitZoneIdx, m_HitZoneName, m_TargetObject, and vector::Zero.
Referenced by ResetTarget(), and TargetSelection().
IsEntityBehindEntityInAngle()
private bool IsEntityBehindEntityInAngle (EntityAI source, EntityAI target, float angle)
Definition at line 678 of file dayzplayerimplementmeleecombat.c.
    {
        vector targetDirection = target.GetDirection();
        ZombieBase targetZombie;
        if (Class.CastTo(targetZombie, target))
        {
            targetDirection = Vector(targetZombie.GetOrientationSynced(),0,0);
            targetDirection = targetDirection.AnglesToVector();
        }
        vector toSourceDirection = (source.GetPosition() - target.GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        int hitDir = Math.Acos(cosFi) * Math.RAD2DEG;
        if (cross[1] < 0)
            hitDir = -hitDir;
        return hitDir <= (-180 + angle) || hitDir >= (180 - angle);
    }
References Math::Acos(), vector::AnglesToVector(), Class::CastTo(), vector::Dot(), vector::Normalize(), Math::RAD2DEG, and Vector().
Referenced by TrySelectFinisherType().
IsObstructed()
protected bool IsObstructed (Object object)
DEPRECATED - New function in MeleeTargeting.
not possible to trace when this happens (zero length raycast)
Definition at line 654 of file dayzplayerimplementmeleecombat.c.
    {
        // check direct visibility of object (obstruction check)
        PhxInteractionLayers collisionLayerMask = PhxInteractionLayers.BUILDING|PhxInteractionLayers.DOOR|PhxInteractionLayers.VEHICLE|PhxInteractionLayers.ROADWAY|PhxInteractionLayers.TERRAIN|PhxInteractionLayers.ITEM_SMALL|PhxInteractionLayers.ITEM_LARGE|PhxInteractionLayers.FENCE;
        int hitComponentIndex;
        float hitFraction;
        vector start, end, hitNormal, hitPosObstructed;
        Object hitObject = null;
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        if (object)
        {
            MiscGameplayFunctions.GetHeadBonePos(player, start);
            end = start + MiscGameplayFunctions.GetHeadingVector(player) * vector.Distance(player.GetPosition(), object.GetPosition());
            if ( end == start )
                return true;
            return DayZPhysics.RayCastBullet( start, end, collisionLayerMask, null, hitObject, hitPosObstructed, hitNormal, hitFraction);
        }
        return false;
    }
References vector::Distance(), m_DZPlayer, and DayZPhysics::RayCastBullet().
Reset()
void Reset (InventoryItem weapon, EMeleeHitType hitMask, bool wasHitEvent = false)
Definition at line 192 of file dayzplayerimplementmeleecombat.c.
    {
        m_Weapon                    = weapon;
        m_HitType                   = hitMask;
        m_TargetType                = EMeleeTargetType.ALIGNABLE;
        m_SprintAttack              = hitMask == EMeleeHitType.SPRINT;
        m_WeaponMode                = SelectWeaponMode(weapon);
        m_WeaponRange               = GetWeaponRange(weapon, m_WeaponMode);
        m_WasHit                    = wasHitEvent;
        #ifdef DEVELOPER
        m_AllPreviousTargetObjects  = m_AllTargetObjects;
        #endif
        m_AllTargetObjects.Clear();
    }
References GetWeaponRange(), m_AllTargetObjects, m_HitType, m_SprintAttack, m_TargetType, m_WasHit, m_Weapon, m_WeaponMode, m_WeaponRange, and SelectWeaponMode().
ResetTarget()
void ResetTarget ()
Definition at line 208 of file dayzplayerimplementmeleecombat.c.
    {
        #ifdef DEVELOPER
        m_PreviousTargetObject  = m_TargetObject;
        m_PreviousHitPositionWS = m_HitPositionWS;
        m_PreviousHitZoneIdx    = m_HitZoneIdx;
        m_PreviousHitZoneName   = m_HitZoneName;
        #endif
        InternalResetTarget();
    }
References InternalResetTarget(), m_HitPositionWS, m_HitZoneIdx, m_HitZoneName, and m_TargetObject.
SelectWeaponMode()
protected int SelectWeaponMode (InventoryItem weapon)
melee with firearm
melee weapon attacks - gets mode from the item
bare hand melee mode selection
default bare-hand light attack
Definition at line 269 of file dayzplayerimplementmeleecombat.c.
    {
        if (weapon)
        {
            if (weapon.IsInherited(Weapon))
            {
                switch (m_HitType)
                {
                    case EMeleeHitType.WPN_HIT:
                        return 0;
                    case EMeleeHitType.WPN_HIT_BUTTSTOCK:
                        return 1;
                    case EMeleeHitType.WPN_STAB:
                        return 2;
                }
            }
            else
            {
                switch (m_HitType)
                {
                    case EMeleeHitType.LIGHT:
                        return weapon.GetMeleeMode();
                    case EMeleeHitType.HEAVY:
                        return weapon.GetMeleeHeavyMode();
                    case EMeleeHitType.SPRINT:
                        return weapon.GetMeleeSprintMode();
                }
            }
        }
        switch (m_HitType)
        {
            case EMeleeHitType.HEAVY:
                return 1;
            case EMeleeHitType.SPRINT:
                return 2;
        }
        return 0;
    }
References m_HitType.
Referenced by Reset().
SetFinisherType()
void SetFinisherType (int pFinisherType)
Definition at line 182 of file dayzplayerimplementmeleecombat.c.
    {
        m_FinisherType = pFinisherType;
    }
References m_FinisherType.
Referenced by Update().
SetHitPos()
void SetHitPos (vector pHitPos)
Definition at line 172 of file dayzplayerimplementmeleecombat.c.
    {
        m_HitPositionWS = pHitPos;
    }
References m_HitPositionWS.
SetHitZoneIdx()
void SetHitZoneIdx (int pHitZone)
Definition at line 146 of file dayzplayerimplementmeleecombat.c.
    {
        m_HitZoneIdx = pHitZone;
    }
References m_HitZoneIdx.
SetTarget()
protected void SetTarget (Object obj, vector hitPos, int hitZone)
Definition at line 505 of file dayzplayerimplementmeleecombat.c.
    {
        if (obj)
        {
            m_TargetObject  = obj;
            m_HitPositionWS = hitPos;
            m_HitZoneIdx    = hitZone;
            m_HitZoneName   = m_TargetObject.GetDamageZoneNameByComponentIndex(m_HitZoneIdx);
        }
    }
References m_HitPositionWS, m_HitZoneIdx, m_HitZoneName, and m_TargetObject.
Referenced by TargetSelection().
SetTargetObject()
void SetTargetObject (Object pTarget)
Definition at line 156 of file dayzplayerimplementmeleecombat.c.
    {
        m_TargetObject = pTarget;
    }
References m_TargetObject.
TargetSelection()
protected void TargetSelection ()
Definition at line 334 of file dayzplayerimplementmeleecombat.c.
    {
        // Prepare common variables
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        vector pos = m_DZPlayer.GetPosition();
        vector rayStart = m_DZPlayer.GetBonePositionWS(m_DZPlayer.GetBoneIndexByName("Head"));
        vector cameraPos, cameraRot, cameraDir;
        m_DZPlayer.GetCurrentCameraTransform(cameraPos, cameraDir, cameraRot);
        vector dir = MiscGameplayFunctions.GetHeadingVector(player);
        dir[1] = cameraDir[1];
        // Calculate max distances
        float dist = GetRange();
        float angle = GetAngle();
        float dist2 = Math.SqrFloat(dist);
        // There's generally 2 TargetSelection calls per animation
        // First to obtain target to move towards during animation
        // Second one is to see if that target is still in range before applying damage to it
        // m_WasHit means the hit event occured, so this is the second call
        if ( m_WasHit )
        {
            // See if the component is still in range
            if (CanObjectBeTargeted(m_TargetObject) && ( vector.DistanceSq(rayStart, m_TargetObject.GetDamageZonePos(m_HitZoneName)) <= dist2 ))
            {
                m_AllTargetObjects.Insert(m_TargetObject);
                // This result should still be cached, so no need to fill it in again
                return;
            }
        }
        // Find a new target
        InternalResetTarget();
        Object target;
        vector hitPos;
        int hitZone;
        // First pass - Prefer what the player is looking at (only aligneable ones, we will try for nonaligneable later)
        if (HitZoneSelectionRaycastHelper(hitPos, hitZone, target))
        {
            if (m_ForceUntargetable)
            {
                SetTarget(target, hitPos, hitZone);
                return;
            }
            if (CanObjectBeTargeted(target) && vector.DistanceSq(rayStart, hitPos) <= dist2)
            {
                m_AllTargetObjects.Insert(target);
                SetTarget(target, hitPos, hitZone);
                return;
            }
        }
        // Second pass - Try to obtain something aligneable closeby the player watching direction
        MeleeTargetData targetData = m_MeleeTargeting.GetMeleeTargetEx(new MeleeTargetSettings(pos, dist*0.75, angle, TARGETING_MIN_HEIGHT, TARGETING_MAX_HEIGHT, rayStart, dir, TARGETING_RAY_RADIUS_EX, m_DZPlayer, m_TargetableObjects), m_AllTargetObjects, m_BlacklistedDamageZones);
        if (targetData)
        {
            SetTarget(targetData.Obj, targetData.HitPos, targetData.HitComponent);
            return;
        }
        // Third pass - We found no aligneable target, check if the target that we are directly looking at is nonalignable (big)
        if (CanObjectBeTargeted(target, true) && vector.DistanceSq(rayStart, hitPos) <= dist2)
        {
            m_AllTargetObjects.Insert(target);
            SetTarget(target, hitPos, hitZone);
            return;
        }
    }
References CanObjectBeTargeted(), vector::DistanceSq(), GetAngle(), GetRange(), MeleeTargetData::HitComponent, MeleeTargetData::HitPos, HitZoneSelectionRaycastHelper(), InternalResetTarget(), m_AllTargetObjects, m_BlacklistedDamageZones, m_DZPlayer, m_ForceUntargetable, m_HitZoneName, m_MeleeTargeting, m_TargetableObjects, m_TargetObject, m_WasHit, MeleeTargetSettings(), MeleeTargetData::Obj, SetTarget(), Math::SqrFloat(), TARGETING_MAX_HEIGHT, TARGETING_MIN_HEIGHT, and TARGETING_RAY_RADIUS_EX.
Referenced by Update().
TrySelectFinisherType()
protected int TrySelectFinisherType (InventoryItem weapon, EntityAI target)
General condition for finisher attacks.
Parameters
weapon Weapon used in the attack
target Target entity
Returns
int - type of finisher (-1 == no finisher)
perform only for finisher suitable weapons
check if attacker is in right pos and angle against victim
Check if the infected is aware of the player
prone checks
firearm
Definition at line 416 of file dayzplayerimplementmeleecombat.c.
    {
        if (m_WasHit)
            return -1;
        if (target && target.CanBeBackstabbed() && weapon && (weapon.IsMeleeFinisher() || m_HitType == EMeleeHitType.WPN_STAB) && !weapon.IsRuined() )
        {
            bool playGenericFinisherAnimation = false;
            ZombieBase targetZombie = ZombieBase.Cast(target);
            if (targetZombie && m_DebugForcedFinisherType == -1)
            {
                if (!IsEntityBehindEntityInAngle(m_DZPlayer, target, 60))
                {
                    return -1;
                }
                int mindState = targetZombie.GetMindStateSynced();
                if (mindState >= DayZInfectedConstants.MINDSTATE_DISTURBED)
                {
                    return -1;
                }
            }
            PlayerBase targetPlayer = PlayerBase.Cast(target);
            if (targetZombie)
            {
                playGenericFinisherAnimation = targetZombie.IsCrawling();
            }
            else if (targetPlayer)
            {
                playGenericFinisherAnimation = targetPlayer.IsInProne();
            }
            else
            {
                playGenericFinisherAnimation = true;
            }
            if (weapon.IsWeapon())
            {
                return EMeleeHitType.WPN_STAB_FINISHER;
            }
            else if (playGenericFinisherAnimation)
            {
                return EMeleeHitType.FINISHER_GENERIC;
            }
            else //specific hit depending on the component hit (gotten from the target)
            {
                return DetermineSpecificFinisherType(ItemBase.Cast(weapon));
            }
        }
        return -1;
    }
References DetermineSpecificFinisherType(), IsEntityBehindEntityInAngle(), m_DebugForcedFinisherType, m_DZPlayer, m_HitType, and m_WasHit.
Referenced by Update().
Update()
void Update (InventoryItem weapon, EMeleeHitType hitMask, bool wasHitEvent = false)
Store target into input packet
Definition at line 220 of file dayzplayerimplementmeleecombat.c.
    {
        Reset(weapon, hitMask, wasHitEvent);
        #ifndef SERVER
        if (!ScriptInputUserData.CanStoreInputUserData())
        {
            //Error("DayZPlayerImplementMeleeCombat - ScriptInputUserData already posted");
            return;
        }
        TargetSelection();
        SetFinisherType(TrySelectFinisherType(weapon, GetTargetEntity()));
        if (GetGame().IsMultiplayer())
        {
            ScriptInputUserData ctx = new ScriptInputUserData();
            ctx.Write(INPUT_UDT_MELEE_TARGET);
            ctx.Write(m_TargetObject);
            ctx.Write(m_HitPositionWS);
            ctx.Write(m_HitZoneIdx);
            ctx.Write(m_FinisherType);
            ctx.Send();
        }
        #endif
    }
References ScriptInputUserData::CanStoreInputUserData(), GetGame(), GetTargetEntity(), INPUT_UDT_MELEE_TARGET, m_FinisherType, m_HitPositionWS, m_HitZoneIdx, m_TargetObject, Reset(), ScriptInputUserData::Send(), SetFinisherType(), TargetSelection(), TrySelectFinisherType(), and Serializer::Write().
~DayZPlayerImplementMeleeCombat()
void ~DayZPlayerImplementMeleeCombat ()
Definition at line 135 of file dayzplayerimplementmeleecombat.c.
{}
Variable Documentation
DEFAULT_HIT_ZONE
protected const string DEFAULT_HIT_ZONE = "Torso"
DEPRECATED: "HitZoneSelection".
Definition at line 34 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection().
m_AllTargetObjects
protected ref array<Object> m_AllTargetObjects
All potential targets found during most recent TargetSelection.
Definition at line 42 of file dayzplayerimplementmeleecombat.c.
Referenced by DayZInfected::ChaseAttackLogic(), DayZInfected::FightAttackLogic(), DayZInfected::Init(), Init(), Reset(), and TargetSelection().
m_BlacklistedDamageZones
protected ref array<string> m_BlacklistedDamageZones
List of blacklisted damage zone names (cannot use indices due to the possible changes when p3d components are recalculated)
Definition at line 51 of file dayzplayerimplementmeleecombat.c.
Referenced by Init(), and TargetSelection().
m_DebugForcedFinisherType
private int m_DebugForcedFinisherType
Definition at line 84 of file dayzplayerimplementmeleecombat.c.
Referenced by DetermineSpecificFinisherType(), Init(), and TrySelectFinisherType().
m_DZPlayer
protected DayZPlayerImplement m_DZPlayer
Parent.
Player executing the melee
Definition at line 54 of file dayzplayerimplementmeleecombat.c.
Referenced by DetermineSpecificFinisherType(), EvaluateHit_Common(), EvaluateHit_NonAlignableObjects(), EvaluateHit_Player(), GetAttackTypeByWeaponAttachments(), GetAttackTypeFromInputs(), GetWeaponRange(), HandleComboHit(), HandleFightLogic(), HandleHitEvent(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), HandleSprintAttack(), HitZoneSelection(), HitZoneSelectionRaycast(), Init(), IsObstructed(), IsShortDistance(), TargetSelection(), and TrySelectFinisherType().
m_FinisherType
protected int m_FinisherType
Definition at line 74 of file dayzplayerimplementmeleecombat.c.
Referenced by GetFinisherType(), Init(), SetFinisherType(), and Update().
m_ForceUntargetable
protected bool m_ForceUntargetable
Misc - cache.
Forcing current target as untargetable
Definition at line 62 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelectionRaycast(), and TargetSelection().
m_HitPositionWS
protected vector m_HitPositionWS
Most recent target position.
Definition at line 76 of file dayzplayerimplementmeleecombat.c.
Referenced by GetHitPos(), HitZoneSelection(), Init(), InternalResetTarget(), ResetTarget(), SetHitPos(), SetTarget(), and Update().
m_HitType
protected EMeleeHitType m_HitType
Hit type of the most recent attack.
Definition at line 70 of file dayzplayerimplementmeleecombat.c.
Referenced by DamageHands(), EvaluateHit_Common(), GetCurrentHitType(), GetHitType(), HandleComboHit(), HandleHitEvent(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), HandleSprintAttack(), Init(), Reset(), SelectWeaponMode(), and TrySelectFinisherType().
m_HitZoneIdx
protected int m_HitZoneIdx
Hit result - cache.
Most recent target HitZone index
Definition at line 73 of file dayzplayerimplementmeleecombat.c.
Referenced by GetHitZoneIdx(), HitZoneSelection(), Init(), InternalResetTarget(), ResetTarget(), SetHitZoneIdx(), SetTarget(), and Update().
m_HitZoneName
protected string m_HitZoneName
Most recent target HitZone name.
Definition at line 75 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection(), Init(), InternalResetTarget(), ResetTarget(), SetTarget(), and TargetSelection().
m_MeleeTargeting
protected ref MeleeTargeting m_MeleeTargeting
Target selecting "component".
Contains logic for Second Pass
Definition at line 37 of file dayzplayerimplementmeleecombat.c.
Referenced by Init(), and TargetSelection().
m_NonAlignableObjects
protected ref array<typename> m_NonAlignableObjects
Typenames of objects that can be targeted, but are not a priority (3rd Pass)
Definition at line 50 of file dayzplayerimplementmeleecombat.c.
Referenced by CanObjectBeTargeted(), HitZoneSelection(), and Init().
m_RayEnd
protected vector m_RayEnd
End position of most recent HitZoneSelectionRaycast.
Definition at line 67 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection(), and HitZoneSelectionRaycast().
m_RayEndShort
protected vector m_RayEndShort
DEPRECATED: "HitZoneSelection".
Definition at line 68 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection().
m_RayStart
protected vector m_RayStart
Start position of most recent HitZoneSelectionRaycast.
Definition at line 66 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection(), and HitZoneSelectionRaycast().
m_SprintAttack
protected bool m_SprintAttack
If most recent attack was a sprint attack.
Definition at line 63 of file dayzplayerimplementmeleecombat.c.
Referenced by GetAngle(), Init(), and Reset().
m_TargetableObjects
protected ref array<typename> m_TargetableObjects
Typenames of all directly/preferred targetable objects (1st Pass + 2nd Pass)
Definition at line 49 of file dayzplayerimplementmeleecombat.c.
Referenced by CanObjectBeTargeted(), DayZInfected::ChaseAttackLogic(), DayZInfected::FightAttackLogic(), DayZInfected::Init(), Init(), and TargetSelection().
m_TargetObject
protected Object m_TargetObject
Targets - types.
Main target found during most recent TargetSelection
Definition at line 40 of file dayzplayerimplementmeleecombat.c.
Referenced by ScriptedWidgetEventHandler::GetOnScreenPosition(), GetTargetEntity(), HitZoneSelection(), Init(), InternalResetTarget(), ResetTarget(), ScriptedWidgetEventHandler::SetTarget(), SetTarget(), SetTargetObject(), TargetSelection(), ScriptedWidgetEventHandler::Update(), and Update().
m_TargetType
protected EMeleeTargetType m_TargetType
DEPRECATED: Was added but never used..?
Definition at line 41 of file dayzplayerimplementmeleecombat.c.
Referenced by Init(), and Reset().
m_WasHit
protected bool m_WasHit
If most recent attack was.
Definition at line 64 of file dayzplayerimplementmeleecombat.c.
Referenced by Init(), Reset(), TargetSelection(), and TrySelectFinisherType().
m_Weapon
protected InventoryItem m_Weapon
Weapons - cache.
Weapon used during most recent Update
Definition at line 57 of file dayzplayerimplementmeleecombat.c.
Referenced by CheckMeleeItem(), ScriptedWidgetEventHandler::GetCrosshairPosition(), HitZoneSelection(), ScriptedWidgetEventHandler::ProjectedCrosshair(), and Reset().
m_WeaponMode
protected int m_WeaponMode
WeaponMode used during most recent Update.
Definition at line 58 of file dayzplayerimplementmeleecombat.c.
Referenced by GetWeaponMode(), and Reset().
m_WeaponRange
protected float m_WeaponRange
WeaponRange used during most recent Update.
Definition at line 59 of file dayzplayerimplementmeleecombat.c.
Referenced by GetRange(), and Reset().
RANGE_EXTENDER_NORMAL
protected const float RANGE_EXTENDER_NORMAL = 0.65
General range extension.
Definition at line 31 of file dayzplayerimplementmeleecombat.c.
Referenced by GetRange().
RANGE_EXTENDER_SPRINT
protected const float RANGE_EXTENDER_SPRINT = 1.35
General range extension while in sprint.
Definition at line 32 of file dayzplayerimplementmeleecombat.c.
TARGETING_ANGLE_NORMAL
enum EMeleeHitType TARGETING_ANGLE_NORMAL = 30.0
Target selection settings.
Second Pass: Half angle of cone
Referenced by GetAngle().
TARGETING_ANGLE_SPRINT
protected const float TARGETING_ANGLE_SPRINT = 15.0
Second Pass: Half angle of cone during sprint.
Definition at line 23 of file dayzplayerimplementmeleecombat.c.
Referenced by GetAngle().
TARGETING_MAX_HEIGHT
protected const float TARGETING_MAX_HEIGHT = 2.0
Second Pass: How high the cone goes in meters from player position.
Definition at line 25 of file dayzplayerimplementmeleecombat.c.
Referenced by TargetSelection().
TARGETING_MIN_HEIGHT
protected const float TARGETING_MIN_HEIGHT = -2.0
Second Pass: How deep the cone goes in meters from player position.
Definition at line 24 of file dayzplayerimplementmeleecombat.c.
Referenced by TargetSelection().
TARGETING_RAY_DIST
protected const float TARGETING_RAY_DIST = 5.0
DEPRECATED: "HitZoneSelection".
Definition at line 28 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection().
TARGETING_RAY_DIST_SHORT
protected const float TARGETING_RAY_DIST_SHORT = 2.0
DEPRECATED: "HitZoneSelection".
Definition at line 29 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection().
TARGETING_RAY_RADIUS
protected const float TARGETING_RAY_RADIUS = 0.25
DEPRECATED: "HitZoneSelection".
Definition at line 27 of file dayzplayerimplementmeleecombat.c.
Referenced by HitZoneSelection().
TARGETING_RAY_RADIUS_EX
protected const float TARGETING_RAY_RADIUS_EX = 0.5
Second Pass: Max distance from ray projected from player looking direction.
Definition at line 26 of file dayzplayerimplementmeleecombat.c.
Referenced by TargetSelection().