DayzKode: P:/scripts/4_world/DayZ/entities/manbase/dayzplayer/dayzplayermeleefightlogic_lightheavy.c File Reference
dayzplayermeleefightlogic_lightheavy.c File Reference
Enumerations
enum EFightLogicCooldownCategory { EVADE = 0 }
Light / Heavy punches.
Functions
protected void DamageHands (DayZPlayer DZPlayer, ClothingBase gloves, InventoryItem itemInHands)
void DayZPlayerMeleeFightLogic_LightHeavy (DayZPlayerImplement player)
string DetermineFinisherAmmo (int finisher_type)
Picks a specific finisher ammo fot the hit type. This gets synchronized and guides further behaviour of the target.
int DetermineFinisherAnimation (int finisher_type)
Picks a specific finisher animation. Not used for mounted bayonet stabs.
int DetermineSpecificFinisherType (ItemBase weapon, int component)
DEPRECATED.
protected void DisableControls ()
protected bool DummyHitSelector (EMeleeHitType hitType, out string ammoType)
evaluation of hit player vs. player
protected void EnableControls ()
protected bool EvaluateFinisherAttack (InventoryItem weapon, Object target)
Check and evaluate stealth kill, if applicable.
protected void EvaluateHit (InventoryItem weapon)
protected void EvaluateHit_Common (InventoryItem weapon, Object target, bool forcedDummy=false)
protected void EvaluateHit_Infected (InventoryItem weapon, Object target)
protected void EvaluateHit_NonAlignableObjects (InventoryItem weapon, Object target)
protected void EvaluateHit_Player (InventoryItem weapon, Object target)
protected float GetAttackTypeByDistanceToTarget (EntityAI pTarget, EMeleeTargetType pTargetType=EMeleeTargetType.ALIGNABLE)
protected EMeleeHitType GetAttackTypeByWeaponAttachments (EntityAI pEntity)
protected EMeleeHitType GetAttackTypeFromInputs (HumanInputController pInputs)
bool GetCurrentHitType ()
int GetFinisherType (InventoryItem weapon, EntityAI target)
DEPRECATED.
protected void GetTargetData (out EntityAI target, out EMeleeTargetType targetType)
protected bool HandleComboHit (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
combo hits - when we are already in Melee command and clicking UseButton
bool HandleFightLogic (int pCurrentCommandID, HumanInputController pInputs, EntityAI pEntityInHands, HumanMovementState pMovementState, out bool pContinueAttack)
protected bool HandleHitEvent (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
Handle the event that our melee hit something.
protected bool HandleInitialFirearmMelee (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
NOTE: Only singular (or first) hits, combo attacks are handled in combo.
protected bool HandleInitialMeleeErc (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
First attack in raised erc (light or heavy if modifier is used). Also added support for finishers.
protected bool HandleProneKick (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
kick from raised pne
protected bool HandleSprintAttack (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
sprint attack in erc stance
void Init (DayZPlayerImplement player)
protected bool IsBehindEntity (int angle, DayZPlayer source, Object target)
DEPRECATED - moved into DayZPlayerImplementMeleeCombat.
bool IsEvading ()
bool IsHitTypeFinisher (int type)
DEPRECATED.
bool IsInBlock ()
protected bool IsShortDistance (EntityAI pTarget, float pDistanceSq)
protected void RegisterCooldowns ()
protected void ResetCooldown (EFightLogicCooldownCategory cooldownCategory)
void SetBlock (bool block)
protected void SetCooldown (float time, EFightLogicCooldownCategory cooldownCategory)
bool WeaponDestroyedCheck (InventoryItem weapon, out string ammo)
void ~DayZPlayerMeleeFightLogic_LightHeavy ()
Variables
const float CLOSE_TARGET_DISTANCE = 1.5
const string DUMMY_HEAVY_AMMO = "Dummy_Heavy"
const string DUMMY_LIGHT_AMMO = "Dummy_Light"
dummy ammo types
enum EFightLogicCooldownCategory EVADE_COOLDOWN = 0.5
cooldown timers settings
protected ref map< int, ref Timer > m_CooldownTimers
protected DayZPlayerImplement m_DZPlayer
protected EMeleeHitType m_HitType
protected bool m_IsEvading
protected bool m_IsFinisher
protected bool m_IsInBlock
protected bool m_IsInComboRange
DEPRECATED.
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat
protected Mission m_Mission
protected bool m_WasPreviousHitProcessed
Enumeration Type Documentation
EFightLogicCooldownCategory
enum EFightLogicCooldownCategory
Light / Heavy punches.
Enumerator
EVADE
Definition at line 2 of file dayzplayermeleefightlogic_lightheavy.c.
{
    EVADE = 0
}
Function Documentation
DamageHands()
protected void DamageHands (DayZPlayer DZPlayer, ClothingBase gloves, InventoryItem itemInHands)
Definition at line 807 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        EntityAI target = m_MeleeCombat.GetTargetEntity();
        //We did not hit anything
        if ( itemInHands || !target || !DZPlayer )
            return;
        //Check if server side
        if ( GetGame().IsServer() )
        {
            int randNum;
            //If gloves, damage gloves
            if ( gloves && gloves.GetHealthLevel() < GameConstants.STATE_RUINED )
            {
                gloves.DecreaseHealth("", "", 1);
            }
            else
            {
                //Do not add bleeding if hitting player, zombie or animal
                if ( PlayerBase.Cast(target) || DayZCreatureAI.Cast( target ) )
                    return;
                PlayerBase player;
                BleedingSourcesManagerServer bleedingManager;
                //We don't inflict bleeding to hands when kicking
                if ( m_HitType != EMeleeHitType.KICK )
                {
                    //If no gloves, inflict hand damage and bleeding
                    //DZPlayer.DecreaseHealth("hands", "", 10); IN CASE WE WANT TO DO STUFF WITH HAND HEALTH
                    //Random bleeding source
                    randNum = Math.RandomIntInclusive(1, 15);
                    switch ( randNum )
                    {
                        case 1:
                            player = PlayerBase.Cast( DZPlayer );
                            if ( player )
{
                                bleedingManager = player.GetBleedingManagerServer();
                                if ( bleedingManager )
{
                                    bleedingManager.AttemptAddBleedingSourceBySelection("RightForeArmRoll");
                                }
                            }
                        break;
                        case 2:
                            player = PlayerBase.Cast( DZPlayer );
                            if ( player )
{
                                bleedingManager = player.GetBleedingManagerServer();
                                if ( bleedingManager )
{
                                    bleedingManager.AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
                                }
                            }
                        break;
                        default:
                            //Do nothing here
                        break;
                    }
                }
                else
                {
                    //Random bleeding source
                    randNum = Math.RandomIntInclusive(1, 15);
                    //We only add bleeding to left foot as character kicks with left foot
                    switch ( randNum )
                    {
                        case 1:
                            player = PlayerBase.Cast( DZPlayer );
                            if ( player )
{
                                bleedingManager = player.GetBleedingManagerServer();
                                if ( bleedingManager )
{
                                    bleedingManager.AttemptAddBleedingSourceBySelection("LeftToeBase");
                                }
                            }
                        break;
                        case 2:
                            player = PlayerBase.Cast( DZPlayer );
                            if ( player )
{
                                bleedingManager = player.GetBleedingManagerServer();
                                if ( bleedingManager )
{
                                    bleedingManager.AttemptAddBleedingSourceBySelection("LeftFoot");
                                }
                            }
                        break;
                        default:
                            //Do nothing here
                        break;
                    }
                }
            }
        }
    }
References GetGame(), m_HitType, m_MeleeCombat, Math::RandomIntInclusive(), and GameConstants::STATE_RUINED.
Referenced by HandleHitEvent().
DayZPlayerMeleeFightLogic_LightHeavy()
void DayZPlayerMeleeFightLogic_LightHeavy (DayZPlayerImplement player)
Definition at line 32 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        Init(player);
    }
References Init().
Referenced by DayZPlayerImplement().
DetermineFinisherAmmo()
string DetermineFinisherAmmo (int finisher_type)
Picks a specific finisher ammo fot the hit type. This gets synchronized and guides further behaviour of the target.
Definition at line 945 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        string ret = "";
        switch (finisher_type)
        {
            case EMeleeHitType.FINISHER_NECKSTAB:
                ret = "FinisherHitNeck";
            break;
            default:
                ret = "FinisherHit";
            break;
        }
        return ret;
    }
Referenced by EvaluateFinisherAttack().
DetermineFinisherAnimation()
int DetermineFinisherAnimation (int finisher_type)
Picks a specific finisher animation. Not used for mounted bayonet stabs.
Definition at line 926 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        int animation = -1;
        switch (finisher_type)
        {
            case EMeleeHitType.FINISHER_LIVERSTAB:
                animation = HumanCommandMelee2.HIT_TYPE_FINISHER;
            break;
            case EMeleeHitType.FINISHER_NECKSTAB:
                animation = HumanCommandMelee2.HIT_TYPE_FINISHER_NECK;
            break;
        }
        return animation;
    }
References HumanCommandMelee2::HIT_TYPE_FINISHER, and HumanCommandMelee2::HIT_TYPE_FINISHER_NECK.
Referenced by HandleInitialMeleeErc().
DetermineSpecificFinisherType()
int DetermineSpecificFinisherType (ItemBase weapon, int component)
DEPRECATED.
Definition at line 963 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return -1;
    }
DisableControls()
protected void DisableControls ()
Referenced by HandleComboHit(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), and HandleSprintAttack().
DummyHitSelector()
protected bool DummyHitSelector (EMeleeHitType hitType, out string ammoType)
evaluation of hit player vs. player
in case of kick (on back or push from erc) change the ammo type to dummy
Definition at line 759 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        switch (hitType)
        {
        case EMeleeHitType.KICK:
            ammoType = DUMMY_HEAVY_AMMO;
            return true;
        break;
        }
        ammoType = DUMMY_LIGHT_AMMO;
        return false;
    }
References DUMMY_HEAVY_AMMO, and DUMMY_LIGHT_AMMO.
Referenced by EvaluateHit_Common().
EnableControls()
protected void EnableControls ()
Referenced by HandleHitEvent().
EvaluateFinisherAttack()
protected bool EvaluateFinisherAttack (InventoryItem weapon, Object target)
Check and evaluate stealth kill, if applicable.
Definition at line 634 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (GetGame().IsServer())
        {
            if (m_MeleeCombat.GetFinisherType() > -1)
            {
                target.ProcessDirectDamage(DT_CLOSE_COMBAT, weapon, "", DetermineFinisherAmmo(m_MeleeCombat.GetFinisherType()), "0 0 0", 1.0);
                //Component can't be easily used, since the function uses DAMAGE ZONE. Investigating later.
                /*string name = target.GetActionComponentName(m_MeleeCombat.GetHitZoneIdx(),"fire");
                target.ProcessDirectDamage(DT_CLOSE_COMBAT, weapon, name, "FinisherHit", "0 0 0", 1.0);*/
                return true;
            }
        }
        //Finisher attack not performed
        return false;
    }
References DetermineFinisherAmmo(), GetGame(), and m_MeleeCombat.
Referenced by EvaluateHit_Infected().
EvaluateHit()
protected void EvaluateHit (InventoryItem weapon)
Definition at line 564 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        EntityAI target = m_MeleeCombat.GetTargetEntity();
        if (target)
        {
            if (target.IsInherited(DayZPlayer))
            {
                EvaluateHit_Player(weapon, target);
            }
            else if (target.IsInherited(DayZInfected))
            {
                EvaluateHit_Infected(weapon, target);
            }
            else if (target.GetMeleeTargetType() == EMeleeTargetType.NONALIGNABLE)
            {
                EvaluateHit_NonAlignableObjects(weapon, target);
            }
            else
            {
                EvaluateHit_Common(weapon, target);
            }
            m_MeleeCombat.CheckMeleeItem();
        }
    }
References EvaluateHit_Common(), EvaluateHit_Infected(), EvaluateHit_NonAlignableObjects(), EvaluateHit_Player(), EntityAI::GetMeleeTargetType(), and m_MeleeCombat.
Referenced by HandleHitEvent().
EvaluateHit_Common()
protected void EvaluateHit_Common (InventoryItem weapon, Object target, bool forcedDummy = false)
check if we need to use dummy hit
normal hit with applied damage to targeted component
play hit animation for dummy hits
override hit pos by pos defined in type
Definition at line 653 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        int hitZoneIdx = m_MeleeCombat.GetHitZoneIdx();
        int weaponMode = m_MeleeCombat.GetWeaponMode();
        vector hitPosWS;
        string ammo;
        EntityAI targetEntity = EntityAI.Cast(target);
        if (!DummyHitSelector(m_HitType, ammo) && !forcedDummy)
        {
            if (hitZoneIdx >= 0)
            {
                hitPosWS = targetEntity.ModelToWorld(targetEntity.GetDefaultHitPosition());
                if (WeaponDestroyedCheck(weapon,ammo))
                {
                    DamageSystem.CloseCombatDamage(m_DZPlayer, target, hitZoneIdx, ammo, hitPosWS);
                    //Debug.MeleeLog(m_DZPlayer, string.Format("EvaluateHit_Common::CloseCombatDamage:: target: %1, hitzone: %2, ammo: %3", target, hitZoneIdx, ammo));
                }
                else
                {
                    m_DZPlayer.ProcessMeleeHit(weapon, weaponMode, target, hitZoneIdx, hitPosWS);
                    //Debug.MeleeLog(m_DZPlayer, string.Format("EvaluateHit_Common::ProcessMeleeHit:: target: %1, hitzone: %2, meleeMode: %3", target, hitZoneIdx, weaponMode));
                }
            }
        }
        else
        {
            if (GetGame().IsServer() && targetEntity)
            {
                hitPosWS = targetEntity.ModelToWorld(targetEntity.GetDefaultHitPosition());
                targetEntity.EEHitBy(null, 0, m_DZPlayer, hitZoneIdx, "", ammo, hitPosWS, 1.0);
                //Debug.MeleeLog(m_DZPlayer, string.Format("EvaluateHit_Common::EEHitBy:: target: %1, hitzone: %2, meleeMode: %3", target, hitZoneIdx, weaponMode));
            }
        }
    }
References DummyHitSelector(), GetGame(), m_DZPlayer, m_HitType, m_MeleeCombat, and WeaponDestroyedCheck().
Referenced by EvaluateHit(), EvaluateHit_Infected(), and EvaluateHit_Player().
EvaluateHit_Infected()
protected void EvaluateHit_Infected (InventoryItem weapon, Object target)
Definition at line 626 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        //If the finisher attack haven't been performed, then use normal hit
        if (!EvaluateFinisherAttack(weapon, target))
            EvaluateHit_Common(weapon, target);
    }
References EvaluateFinisherAttack(), and EvaluateHit_Common().
Referenced by EvaluateHit().
EvaluateHit_NonAlignableObjects()
protected void EvaluateHit_NonAlignableObjects (InventoryItem weapon, Object target)
Definition at line 694 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        int hitZoneIdx = m_MeleeCombat.GetHitZoneIdx();
        vector hitPosWS;
        string ammo;
        if (hitZoneIdx >= 0)
        {
            if (WeaponDestroyedCheck(weapon,ammo))
                DamageSystem.CloseCombatDamage(m_DZPlayer, target, hitZoneIdx, ammo, m_MeleeCombat.GetHitPos());
            else
                m_DZPlayer.ProcessMeleeHit(weapon, m_MeleeCombat.GetWeaponMode(), target, hitZoneIdx, m_MeleeCombat.GetHitPos());
        }
        return;
    }
References m_DZPlayer, m_MeleeCombat, and WeaponDestroyedCheck().
Referenced by EvaluateHit().
EvaluateHit_Player()
protected void EvaluateHit_Player (InventoryItem weapon, Object target)
Melee Hit/Impact modifiers
if the oponnent is in Melee Block shift the damage down
Definition at line 591 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        int hitZoneIdx = m_MeleeCombat.GetHitZoneIdx();
        int weaponMode = m_MeleeCombat.GetWeaponMode();
        vector hitPosWS;
        bool forcedDummy = false;
        PlayerBase targetPlayer = PlayerBase.Cast(target);
        if ( targetPlayer )
        {
            vector targetPos = targetPlayer.GetPosition();
            vector agressorPos = m_DZPlayer.GetPosition();
            // We get the angle from which an infected hit the blocking player
            float hitAngle = Math.RAD2DEG * Math.AbsFloat(Math3D.AngleFromPosition(targetPos, MiscGameplayFunctions.GetHeadingVector(targetPlayer), agressorPos));
            if (targetPlayer.GetMeleeFightLogic() && targetPlayer.GetMeleeFightLogic().IsInBlock() && hitAngle <= GameConstants.PVP_MAX_BLOCKABLE_ANGLE)
            {
                if ( weaponMode > 0 )
                {
                    weaponMode--; // Heavy -> Light shift
                }
                else
                {
                    forcedDummy = true; // dummy hits, cannot shift lower than 0
                }
            }
        }
        EvaluateHit_Common(weapon, target, forcedDummy);
    }
References Math::AbsFloat(), Math3D::AngleFromPosition(), EvaluateHit_Common(), m_DZPlayer, m_MeleeCombat, GameConstants::PVP_MAX_BLOCKABLE_ANGLE, and Math::RAD2DEG.
Referenced by EvaluateHit().
GetAttackTypeByDistanceToTarget()
protected float GetAttackTypeByDistanceToTarget (EntityAI pTarget, EMeleeTargetType pTargetType = EMeleeTargetType.ALIGNABLE)
target in short distance - in place attack
target is far from the player - forward movement attack
Definition at line 109 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (pTargetType == EMeleeTargetType.NONALIGNABLE)
        {
            return 1.0;
        }
        if (IsShortDistance(pTarget, Math.SqrFloat(CLOSE_TARGET_DISTANCE)))
        {
            return 1.0;
        }
        return 0.0;
    }
References CLOSE_TARGET_DISTANCE, IsShortDistance(), and Math::SqrFloat().
Referenced by HandleComboHit(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), and HandleSprintAttack().
GetAttackTypeByWeaponAttachments()
protected EMeleeHitType GetAttackTypeByWeaponAttachments (EntityAI pEntity)
use stabbing if the bayonet/knife is attached to firearm
Definition at line 89 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (!m_DZPlayer.CanConsumeStamina(EStaminaConsumers.MELEE_HEAVY))
        {
            return EMeleeHitType.NONE;
        }
        if (pEntity.HasBayonetAttached())
        {
            return EMeleeHitType.WPN_STAB;
        }
        else if (pEntity.HasButtstockAttached())
        {
            return EMeleeHitType.WPN_HIT_BUTTSTOCK;
        }
        return EMeleeHitType.WPN_HIT;
    }
References m_DZPlayer.
Referenced by HandleComboHit(), and HandleInitialFirearmMelee().
GetAttackTypeFromInputs()
protected EMeleeHitType GetAttackTypeFromInputs (HumanInputController pInputs)
Definition at line 79 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (pInputs.IsMeleeFastAttackModifier() && m_DZPlayer.CanConsumeStamina(EStaminaConsumers.MELEE_HEAVY))
        {
            return EMeleeHitType.HEAVY;
        }
        return EMeleeHitType.LIGHT;
    }
References HumanInputController::IsMeleeFastAttackModifier(), and m_DZPlayer.
Referenced by HandleComboHit(), and HandleInitialMeleeErc().
GetCurrentHitType()
bool GetCurrentHitType ()
Definition at line 68 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return m_HitType;
    }
References m_HitType.
GetFinisherType()
int GetFinisherType (InventoryItem weapon, EntityAI target)
DEPRECATED.
Definition at line 914 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return -1;
    }
GetTargetData()
protected void GetTargetData (out EntityAI target, out EMeleeTargetType targetType)
default
nullify target for nonalignable objects (big objects)
Definition at line 735 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        target = m_MeleeCombat.GetTargetEntity();
        targetType = EMeleeTargetType.ALIGNABLE;
        // If there is no hitzone defined, then we won't be able to hit the target anyways..
        if (m_MeleeCombat.GetHitZoneIdx() < 0)
        {
            target = null;
        }
        if ( target )
        {
            targetType = target.GetMeleeTargetType();
        }
        if ( targetType == EMeleeTargetType.NONALIGNABLE )
        {
            target = null;
        }
    }
References m_MeleeCombat.
Referenced by HandleComboHit(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), and HandleSprintAttack().
HandleComboHit()
protected bool HandleComboHit (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
combo hits - when we are already in Melee command and clicking UseButton
no suitable attack - skip that
No combos for the finisher command
select if the next attack will light or heavy (based on input/attachment modifier)
targetting
wait for the previous hit commit before hitting again
continue 'combo' - left hand attacks
broken legs shock
stamina depletion per attack
Definition at line 490 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        //Debug.MeleeLog(m_DZPlayer, "HandleComboHit::");
        if (m_HitType == EMeleeHitType.NONE)
            return false;
        if (m_MeleeCombat.GetFinisherType() > -1)
            return false;
        EntityAI target;
        EMeleeTargetType targetType;
        GetTargetData(target, targetType);
        float attackByDistance = GetAttackTypeByDistanceToTarget(target, targetType);
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        if (itemInHands && itemInHands.IsWeapon())
        {
            m_HitType = GetAttackTypeByWeaponAttachments(itemInHands);
        }
        else
        {
            m_HitType = GetAttackTypeFromInputs(pInputs);
        }
        //Debug.MeleeLog(m_DZPlayer, string.Format("HandleComboHit:: %1", EnumTools.EnumToString(EMeleeHitType, m_HitType)));
        if (m_WasPreviousHitProcessed)
        {
          m_MeleeCombat.Update(itemInHands, m_HitType);
        }
        bool isHeavy = (m_HitType == EMeleeHitType.HEAVY || m_HitType == EMeleeHitType.WPN_STAB);
        m_DZPlayer.GetCommand_Melee2().ContinueCombo(isHeavy, attackByDistance, target, m_MeleeCombat.GetHitPos());
        DisableControls();
        if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
        {
            float shock = PlayerConstants.BROKEN_LEGS_HEAVY_MELEE_SHOCK;
            if (!isHeavy)
                shock = PlayerConstants.BROKEN_LEGS_LIGHT_MELEE_SHOCK;
            player.m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_HEAVY_MELEE_SHOCK);
            player.m_ShockHandler.CheckValue(true);
        }
        switch (m_HitType)
        {
            case EMeleeHitType.HEAVY:
            case EMeleeHitType.SPRINT:
            case EMeleeHitType.WPN_STAB:
            case EMeleeHitType.WPN_HIT_BUTTSTOCK:
            case EMeleeHitType.WPN_HIT:
                m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_HEAVY);
                break;
            default:
                m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_LIGHT);
                break;
        }
        m_IsInComboRange = false;
        return true;
    }
References PlayerConstants::BROKEN_LEGS_HEAVY_MELEE_SHOCK, PlayerConstants::BROKEN_LEGS_LIGHT_MELEE_SHOCK, DisableControls(), GetAttackTypeByDistanceToTarget(), GetAttackTypeByWeaponAttachments(), GetAttackTypeFromInputs(), GetTargetData(), m_DZPlayer, m_HitType, m_IsInComboRange, m_MeleeCombat, and m_WasPreviousHitProcessed.
Referenced by HandleFightLogic().
HandleFightLogic()
bool HandleFightLogic (int pCurrentCommandID, HumanInputController pInputs, EntityAI pEntityInHands, HumanMovementState pMovementState, out bool pContinueAttack)
Check if we need to damage
Actually pressing a button to start a melee attack
do not perform attacks when blocking
if the item in hands cannot be used as melee weapon
Currently not performing any attacks, so here we start the initial
melee with firearm
first attack in raised erc (light or heavy if modifier is used). Also added support for finishers
kick from raised pne
sprint attack in erc stance
combo hits - when we are already in Melee command and clicking UseButton
evade and blocking logic
evades in raised erc stance while moving
not enough stamina to do evades
stand up when crouching and raised pressed
blocks in raised erc/pro stance (bare hand or with melee weapon only)
Definition at line 126 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        HumanCommandMove hcm        = m_DZPlayer.GetCommand_Move();
        InventoryItem itemInHands   = InventoryItem.Cast(pEntityInHands);
        PlayerBase player           = PlayerBase.Cast(m_DZPlayer);
        bool isFireWeapon           = itemInHands && itemInHands.IsWeapon();
        if (HandleHitEvent(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack))
        {
            return false;
        }
        if ((pInputs.IsAttackButtonDown() && !isFireWeapon) || (pInputs.IsMeleeWeaponAttack() && isFireWeapon) || (pContinueAttack && isFireWeapon))
        {
            //Debug.MeleeLog(m_DZPlayer, "HandleFightLogic:: Button clicked");
            if (m_IsInBlock || m_IsEvading)
            {
                return false;
            }
            if (itemInHands && !itemInHands.IsMeleeWeapon() && !isFireWeapon)
            {
                return false;
            }
            if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_MOVE)
            {
                if (isFireWeapon)
                {
                    return HandleInitialFirearmMelee(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack);
                }
                else
                {
                    if (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
                    {
                        return HandleInitialMeleeErc(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack);
                    }
                    else if (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
                    {
                        return HandleProneKick(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack);
                    }
                    else if (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT && m_DZPlayer.IsSprintFull())
                    {
                        return HandleSprintAttack(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack);
                    }
                }
            }
            else if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_MELEE2)
            {
                m_IsInComboRange = m_DZPlayer.GetCommand_Melee2().IsInComboRange();
                if (m_IsInComboRange)
                {
                    return HandleComboHit(pCurrentCommandID, pInputs, itemInHands, pMovementState, pContinueAttack);
                }
            }
        }
        else if (!isFireWeapon && pCurrentCommandID == DayZPlayerConstants.COMMANDID_MOVE)
        {
            if (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
            {
                int roll = pInputs.IsMeleeLREvade();
                if (roll != 0)
                {
                    if (!m_DZPlayer.CanConsumeStamina(EStaminaConsumers.MELEE_EVADE))
                    {
                        return false;
                    }
                    float angle;
                    if (roll == 1)
                    {
                        angle = -90;    // left
                    }
                    else
                    {
                        angle = 90;     // right
                    }
                    // start melee evade
                    m_IsEvading = true;
                    SetCooldown(EVADE_COOLDOWN, EFightLogicCooldownCategory.EVADE);
                    hcm.StartMeleeEvadeA(angle);
                    m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_EVADE);
                    //Inflict shock when sidestepping with broken legs
                    if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
                    {
                        player.m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_LIGHT_MELEE_SHOCK);
                        player.m_ShockHandler.CheckValue(true);
                    }
                }
            }
            if (pInputs.IsWeaponRaised() && pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH)
            {
                if ( DayZPlayerUtils.PlayerCanChangeStance(player, DayZPlayerConstants.STANCEIDX_ERECT) )
                    hcm.ForceStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT);
            }
            if (!isFireWeapon && (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT || pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE))
            {
                float angle2;
                if (hcm.GetCurrentInputAngle(angle2) && (angle2 < -130.0 || angle2 > 130))
                {
                    hcm.SetMeleeBlock(true);
                    SetBlock(true);
                }
                else
                {
                    hcm.SetMeleeBlock(false);
                    SetBlock(false);
                }
            }
            else
            {
                hcm.SetMeleeBlock(false);
                SetBlock(false);
            }
        }
        return false;
    }
References PlayerConstants::BROKEN_LEGS_LIGHT_MELEE_SHOCK, EVADE_COOLDOWN, HumanCommandMove::ForceStance(), HumanCommandMove::GetCurrentInputAngle(), HandleComboHit(), HandleHitEvent(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), HandleSprintAttack(), HumanInputController::IsAttackButtonDown(), HumanInputController::IsMeleeLREvade(), HumanInputController::IsMeleeWeaponAttack(), HumanInputController::IsWeaponRaised(), m_DZPlayer, m_IsEvading, m_IsInBlock, m_IsInComboRange, HumanMovementState::m_iStanceIdx, DayZPlayerUtils::PlayerCanChangeStance(), SetBlock(), SetCooldown(), HumanCommandMove::SetMeleeBlock(), and HumanCommandMove::StartMeleeEvadeA().
HandleHitEvent()
protected bool HandleHitEvent (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
Handle the event that our melee hit something.
Check if we need to damage
on anim event Hit received
re-target (enemy can have moved out of range or disappeared)
evaluate hit - selection of cfg 'ammo' type
Definition at line 268 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_MELEE2)
        {
            HumanCommandMelee2 hmc2a = m_DZPlayer.GetCommand_Melee2();
            if (hmc2a)
            {
                if (hmc2a.WasHit())
                {
                    //Debug.MeleeLog(m_DZPlayer, "HandleHitEvent::START");
                    if (m_MeleeCombat.GetFinisherType() == -1)
                        m_MeleeCombat.Update(itemInHands, m_HitType, true);
                    //Debug.MeleeLog(m_DZPlayer, string.Format("HandleHitEvent:: %1", EnumTools.EnumToString(EMeleeHitType, m_HitType)));
                    EvaluateHit(itemInHands);
                    PlayerBase player = PlayerBase.Cast(m_DZPlayer);
                    //Get gloves
                    ClothingBase gloves;
                    if (m_HitType == EMeleeHitType.KICK)
                    {
                        //We kick so "gloves" will be the shoes
                        gloves = ClothingBase.Cast(player.GetItemOnSlot("FEET"));
                    }
                    else
                    {
                        gloves = ClothingBase.Cast(player.GetItemOnSlot("GLOVES"));
                    }
                    //If we hit something, inflict damage
                    DamageHands(m_DZPlayer, gloves, itemInHands);
                    EnableControls();
                    m_WasPreviousHitProcessed = true;
                    //Debug.MeleeLog(m_DZPlayer, "HandleHitEvent::END");
                    return true;
                }
            }
        }
        return false;
    }
References DamageHands(), EnableControls(), EvaluateHit(), m_DZPlayer, m_HitType, m_MeleeCombat, m_WasPreviousHitProcessed, and HumanCommandMelee2::WasHit().
Referenced by HandleFightLogic().
HandleInitialFirearmMelee()
protected bool HandleInitialFirearmMelee (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
NOTE: Only singular (or first) hits, combo attacks are handled in combo.
don't allow bash to interfere with actions like chambering or ejecting bullets
perform firearm melee from raised erect or continue with attack after character stand up from crouch
exit if there is no suitable attack
char stand up when performing firearm melee from crouch
Definition at line 319 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        Weapon_Base weapon = Weapon_Base.Cast(itemInHands);
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        if (weapon.IsWaitingForActionFinish() || player.GetActionManager().GetRunningAction())
            return false;
        HumanCommandMove hcm = m_DZPlayer.GetCommand_Move();
        if (hcm.GetCurrentMovementSpeed() <= 2.05 && (pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT || pContinueAttack) && !m_DZPlayer.IsFighting())
        {
            m_HitType = GetAttackTypeByWeaponAttachments(itemInHands);
            if ( m_HitType == EMeleeHitType.NONE )
                return false;
            m_MeleeCombat.Update(itemInHands, m_HitType);
            EntityAI target;
            EMeleeTargetType targetType;
            GetTargetData(target, targetType);
            float attackByDistance = GetAttackTypeByDistanceToTarget(target, targetType);
            m_DZPlayer.StartCommand_Melee2(target, m_HitType == EMeleeHitType.WPN_STAB, attackByDistance, m_MeleeCombat.GetHitPos());
            // finisher attack hittype override
            int finisherType = m_MeleeCombat.GetFinisherType();
            if (finisherType != -1)
            {
                m_HitType = finisherType;
                target.SetBeingBackstabbed(finisherType);
            }
            m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_HEAVY);
            DisableControls();
            pContinueAttack = false; // reset continueAttack flag
            return true;
        }
        else if ( pMovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH )
        {
            if (hcm)
            {
                hcm.ForceStance(DayZPlayerConstants.STANCEIDX_RAISEDERECT);
                pContinueAttack = true;
                return false;
            }
        }
        return false;
    }
References DisableControls(), HumanCommandMove::ForceStance(), GetAttackTypeByDistanceToTarget(), GetAttackTypeByWeaponAttachments(), HumanCommandMove::GetCurrentMovementSpeed(), GetTargetData(), m_DZPlayer, m_HitType, HumanMovementState::m_iStanceIdx, and m_MeleeCombat.
Referenced by HandleFightLogic().
HandleInitialMeleeErc()
protected bool HandleInitialMeleeErc (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
First attack in raised erc (light or heavy if modifier is used). Also added support for finishers.
Definition at line 374 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        //Debug.MeleeLog(m_DZPlayer, "HandleInitialMeleeErc::");
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        m_HitType = GetAttackTypeFromInputs(pInputs);
        m_MeleeCombat.Update(itemInHands, m_HitType);
        //Debug.MeleeLog(m_DZPlayer, string.Format("HandleInitialMeleeErc:: %1", EnumTools.EnumToString(EMeleeHitType, m_HitType)));
        EntityAI target;
        EMeleeTargetType targetType;
        GetTargetData(target, targetType);
        float attackByDistance = GetAttackTypeByDistanceToTarget(target, targetType);
        // finisher attack hittype override
        int finisherType = m_MeleeCombat.GetFinisherType();
        if (finisherType != -1)
        {
            int animationType = DetermineFinisherAnimation(finisherType);
            if (animationType > -1)
            {
                m_DZPlayer.StartCommand_Melee2(target, animationType, attackByDistance, m_MeleeCombat.GetHitPos());
            }
            else
            {
                m_DZPlayer.StartCommand_Melee2(target, m_HitType == EMeleeHitType.HEAVY, attackByDistance, m_MeleeCombat.GetHitPos());
            }
            m_HitType = finisherType;
            target.SetBeingBackstabbed(finisherType);
        }
        else
        {
            m_DZPlayer.StartCommand_Melee2(target, m_HitType == EMeleeHitType.HEAVY, attackByDistance, m_MeleeCombat.GetHitPos());
        }
        if (m_HitType == EMeleeHitType.HEAVY)
        {
            m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_HEAVY);
            if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            {
                player.m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_HEAVY_MELEE_SHOCK);
                player.m_ShockHandler.CheckValue(true);
            }
        }
        else
        {
            m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_LIGHT);
            if (player.GetBrokenLegs() == eBrokenLegs.BROKEN_LEGS)
            {
                player.m_ShockHandler.SetShock(PlayerConstants.BROKEN_LEGS_LIGHT_MELEE_SHOCK);
                player.m_ShockHandler.CheckValue(true);
            }
        }
        m_WasPreviousHitProcessed = false;
        DisableControls();
        return true;
    }
References PlayerConstants::BROKEN_LEGS_HEAVY_MELEE_SHOCK, PlayerConstants::BROKEN_LEGS_LIGHT_MELEE_SHOCK, DetermineFinisherAnimation(), DisableControls(), GetAttackTypeByDistanceToTarget(), GetAttackTypeFromInputs(), GetTargetData(), m_DZPlayer, m_HitType, m_MeleeCombat, and m_WasPreviousHitProcessed.
Referenced by HandleFightLogic().
HandleProneKick()
protected bool HandleProneKick (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
kick from raised pne
check if player is on back (situation where the player is raised in prone and on back is not in anim graph)
Definition at line 438 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        HumanCommandWeapons hcw = m_DZPlayer.GetCommandModifier_Weapons();
        PlayerBase player = PlayerBase.Cast(m_DZPlayer);
        float hcw_angle = hcw.GetBaseAimingAngleLR();
        if ( ( hcw_angle < -90 || hcw_angle > 90 ) && player.GetBrokenLegs() != eBrokenLegs.BROKEN_LEGS )
        {
            // targetting
            m_HitType = EMeleeHitType.KICK;
            m_MeleeCombat.Update(itemInHands, m_HitType);
            EntityAI target;
            EMeleeTargetType targetType;
            GetTargetData(target, targetType);
            float attackByDistance = GetAttackTypeByDistanceToTarget(target, targetType);
            // command
            m_DZPlayer.StartCommand_Melee2(target, false, attackByDistance, m_MeleeCombat.GetHitPos());
            m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_HEAVY);
            DisableControls();
            return true;
        }
        return false;
    }
References DisableControls(), GetAttackTypeByDistanceToTarget(), HumanCommandWeapons::GetBaseAimingAngleLR(), GetTargetData(), m_DZPlayer, m_HitType, and m_MeleeCombat.
Referenced by HandleFightLogic().
HandleSprintAttack()
protected bool HandleSprintAttack (int pCurrentCommandID, HumanInputController pInputs, InventoryItem itemInHands, HumanMovementState pMovementState, out bool pContinueAttack)
sprint attack in erc stance
targetting
command
Definition at line 470 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        m_HitType = EMeleeHitType.SPRINT;
        m_MeleeCombat.Update(itemInHands, m_HitType);
        EntityAI target;
        EMeleeTargetType targetType;
        GetTargetData(target, targetType);
        float attackByDistance = GetAttackTypeByDistanceToTarget(target, targetType);
        m_DZPlayer.StartCommand_Melee2(target, false, attackByDistance, m_MeleeCombat.GetHitPos());
        m_DZPlayer.DepleteStamina(EStaminaModifiers.MELEE_HEAVY);
        DisableControls();
        return true;
    }
References DisableControls(), GetAttackTypeByDistanceToTarget(), GetTargetData(), m_DZPlayer, m_HitType, and m_MeleeCombat.
Referenced by HandleFightLogic().
Init()
void Init (DayZPlayerImplement player)
Definition at line 37 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        m_DZPlayer                  = player;
        m_MeleeCombat               = m_DZPlayer.GetMeleeCombat();
        m_Mission                   = GetGame().GetMission();
        m_IsInBlock                 = false;
        m_IsEvading                 = false;
        m_WasPreviousHitProcessed   = false;
        m_HitType                   = EMeleeHitType.NONE;
        RegisterCooldowns();
    }
References GetGame(), CGame::GetMission(), m_DZPlayer, m_HitType, m_IsEvading, m_IsInBlock, m_MeleeCombat, m_Mission, m_WasPreviousHitProcessed, and RegisterCooldowns().
IsBehindEntity()
protected bool IsBehindEntity (int angle, DayZPlayer source, Object target)
DEPRECATED - moved into DayZPlayerImplementMeleeCombat.
Definition at line 776 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return false;
    }
IsEvading()
bool IsEvading ()
Definition at line 63 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return m_IsEvading;
    }
References m_IsEvading.
IsHitTypeFinisher()
bool IsHitTypeFinisher (int type)
DEPRECATED.
Definition at line 920 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return false;
    }
IsInBlock()
bool IsInBlock ()
Definition at line 53 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return m_IsInBlock;
    }
References m_IsInBlock.
IsShortDistance()
protected bool IsShortDistance (EntityAI pTarget, float pDistanceSq)
Definition at line 968 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return pTarget && vector.DistanceSq(m_DZPlayer.GetPosition(), m_MeleeCombat.GetHitPos()) <= pDistanceSq || vector.DistanceSq(m_DZPlayer.GetBonePositionWS(m_DZPlayer.GetBoneIndexByName("Head")), m_MeleeCombat.GetHitPos()) <= pDistanceSq)
    }
References vector::DistanceSq(), m_DZPlayer, and m_MeleeCombat.
Referenced by GetAttackTypeByDistanceToTarget().
RegisterCooldowns()
protected void RegisterCooldowns ()
Definition at line 73 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        m_CooldownTimers = new map<int, ref Timer>;
        m_CooldownTimers.Insert(EFightLogicCooldownCategory.EVADE, new Timer(CALL_CATEGORY_SYSTEM)); // evades
    }
References CALL_CATEGORY_SYSTEM, and m_CooldownTimers.
Referenced by Init().
ResetCooldown()
protected void ResetCooldown (EFightLogicCooldownCategory cooldownCategory)
Definition at line 794 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        switch (cooldownCategory)
        {
        case EFightLogicCooldownCategory.EVADE:
            m_IsEvading = false;
        break;
        }
    }
References m_IsEvading.
SetBlock()
void SetBlock (bool block)
Definition at line 58 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        m_IsInBlock = block;
    }
References m_IsInBlock.
Referenced by HandleFightLogic().
SetCooldown()
protected void SetCooldown (float time, EFightLogicCooldownCategory cooldownCategory)
stops currently running cooldown timer (for specific category)
param for ResetCooldown
Definition at line 781 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if ( m_CooldownTimers.Get(cooldownCategory).IsRunning() )
        {
            m_CooldownTimers.Get(cooldownCategory).Stop();
        }
        Param1<int> param = new Param1<int>(cooldownCategory);
        m_CooldownTimers.Get(cooldownCategory).Run(time, this, "ResetCooldown", param);
    }
References m_CooldownTimers.
WeaponDestroyedCheck()
bool WeaponDestroyedCheck (InventoryItem weapon, out string ammo)
Definition at line 711 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        if (!weapon)
            return false;
        Weapon_Base firearm = Weapon_Base.Cast(weapon);
        ItemBase bayonet = ItemBase.Cast(weapon.GetInventory().FindAttachment(weapon.GetBayonetAttachmentIdx()));
        if ( firearm && bayonet && bayonet.IsRuined() )
        {
            ammo = bayonet.GetRuinedMeleeAmmoType();
            return true;
        }
        else if (weapon.IsRuined())
        {
            ammo = weapon.GetRuinedMeleeAmmoType();
            return true;
        }
        else
        {
            return false;
        }
    }
Referenced by EvaluateHit_Common(), and EvaluateHit_NonAlignableObjects().
~DayZPlayerMeleeFightLogic_LightHeavy()
void ~DayZPlayerMeleeFightLogic_LightHeavy ()
Definition at line 51 of file dayzplayermeleefightlogic_lightheavy.c.
{}
Variable Documentation
CLOSE_TARGET_DISTANCE
const float CLOSE_TARGET_DISTANCE = 1.5
Definition at line 13 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by GetAttackTypeByDistanceToTarget().
DUMMY_HEAVY_AMMO
const string DUMMY_HEAVY_AMMO = "Dummy_Heavy"
Definition at line 17 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by DummyHitSelector().
DUMMY_LIGHT_AMMO
const string DUMMY_LIGHT_AMMO = "Dummy_Light"
dummy ammo types
Definition at line 16 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by DummyHitSelector().
EVADE_COOLDOWN
enum EFightLogicCooldownCategory EVADE_COOLDOWN = 0.5
cooldown timers settings
Referenced by HandleFightLogic().
m_CooldownTimers
protected ref map<int, ref Timer> m_CooldownTimers
Definition at line 22 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by RegisterCooldowns(), and SetCooldown().
m_DZPlayer
protected DayZPlayerImplement m_DZPlayer
Definition at line 19 of file dayzplayermeleefightlogic_lightheavy.c.
m_HitType
protected EMeleeHitType m_HitType
Definition at line 21 of file dayzplayermeleefightlogic_lightheavy.c.
m_IsEvading
protected bool m_IsEvading
Definition at line 26 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by HandleFightLogic(), Init(), IsEvading(), and ResetCooldown().
m_IsFinisher
protected bool m_IsFinisher
Definition at line 27 of file dayzplayermeleefightlogic_lightheavy.c.
m_IsInBlock
protected bool m_IsInBlock
Definition at line 25 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by HandleFightLogic(), Init(), IsInBlock(), and SetBlock().
m_IsInComboRange
protected bool m_IsInComboRange
DEPRECATED.
Definition at line 29 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by HandleComboHit(), and HandleFightLogic().
m_MeleeCombat
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat
Definition at line 20 of file dayzplayermeleefightlogic_lightheavy.c.
m_Mission
protected Mission m_Mission
Definition at line 23 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by UIScriptedMenu::Init(), Init(), UIScriptedMenu::OnClick(), UIScriptedMenu::OpenCredits(), and UIScriptedMenu::Refresh().
m_WasPreviousHitProcessed
protected bool m_WasPreviousHitProcessed
Definition at line 30 of file dayzplayermeleefightlogic_lightheavy.c.
Referenced by HandleComboHit(), HandleHitEvent(), HandleInitialMeleeErc(), and Init().