DayzKode: P:/scripts/4_world/DayZ/entities/manbase/dayzplayer/dayzplayercameraironsights.c File Reference
dayzplayercameraironsights.c File Reference
Classes
class DayZPlayerCameraBase
this is main camera class
Functions
override void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult)
void DayZPlayerCameraOptics (DayZPlayer pPlayer, HumanInputController pInput)
override string GetCameraName ()
override EntityAI GetCurrentSightEntity ()
override bool GetCurrentSightInfo (out vector camPos, out vector camDir)
override float HoldBreathFOVEffect (float pDt)
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
override void SendRecoilOffsetZ (float offset)
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
Variables
class DayZPlayerCameraIronsights extends DayZPlayerCameraBase CONST_NEARPLANE_OPTICS = 0.06
protected float m_RecoilOffsetZ = 0.0
Function Documentation
AdjustCameraParameters()
override void AdjustCameraParameters (float pDt, inout DayZPlayerCameraResult pOutResult)
Definition at line 387 of file dayzplayercameraironsights.c.
    {
        pOutResult.m_iDirectBone            = m_iBoneIndex;
        pOutResult.m_iDirectBoneMode        = 4;
        pOutResult.m_fFovAbsolute = HoldBreathFOVEffect(pDt);
        pOutResult.m_bUpdateWhenBlendOut    = false;
        pOutResult.m_fDistance              = 0;
        pOutResult.m_fUseHeading            = 0;
        pOutResult.m_fInsideCamera          = 1.0;
        pOutResult.m_fShootFromCamera       = m_fShootFromCamera;
        //pOutResult.m_fNearPlane = CONST_NEARPLANE_OPTICS; //0.07 global default
        pOutResult.m_fNearPlane = Math.Clamp(m_opticsUsed.GetNearPlaneValue() - m_RecoilOffsetZ, CONST_NEARPLANE_OPTICS, 10.0); //some sufficiently nonsensical max
    }
References Math::Clamp(), CONST_NEARPLANE_OPTICS, HoldBreathFOVEffect(), m_fShootFromCamera, m_iBoneIndex, m_opticsUsed, and m_RecoilOffsetZ.
DayZPlayerCameraOptics()
void DayZPlayerCameraOptics (DayZPlayer pPlayer, HumanInputController pInput)
Definition at line 341 of file dayzplayercameraironsights.c.
    {
        if (!temp_array)
            temp_array = new array<float>;
        m_fShootFromCamera = 0;
    }
References m_fShootFromCamera.
Referenced by ManBase::HideClothing(), InventoryItemSuper::InitCameraOverrideProperties(), OnActivate(), and DayZPlayerCameras::RegisterCameras().
GetCameraName()
override string GetCameraName ()
Definition at line 550 of file dayzplayercameraironsights.c.
    {
        return "DayZPlayerCameraOptics";
    }
GetCurrentSightEntity()
override EntityAI GetCurrentSightEntity ()
Definition at line 360 of file dayzplayercameraironsights.c.
    {
        return m_opticsUsed;
    }
References m_opticsUsed.
Referenced by HoldBreathFOVEffect().
GetCurrentSightInfo()
override bool GetCurrentSightInfo (out vector camPos, out vector camDir)
Definition at line 365 of file dayzplayercameraironsights.c.
    {
        if (m_opticsUsed)
        {
            m_opticsUsed.UseWeaponIronsightsOverride(false);
            m_opticsUsed.GetCameraPoint(camPos, camDir);
            return true;
        }
        return false;
    }
References m_opticsUsed.
HoldBreathFOVEffect()
override float HoldBreathFOVEffect (float pDt)
Definition at line 404 of file dayzplayercameraironsights.c.
    {
        //hotfix; two cameras exist and update simultaneously during transition, even if optics/weapons is no longer present!
        /*PlayerBase player = PlayerBase.Cast(m_pPlayer);
        if (player && player.GetCurrentCamera() != this)
            return 0.6;*/
        ItemOptics optics = ItemOptics.Cast( GetCurrentSightEntity() );
        if (optics)
        {
            if (optics.GetCurrentStepFOV() >= GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM && (m_pPlayer.IsHoldingBreath() || m_pPlayer.IsEyeZoom()))
            {
                m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, GameConstants.DZPLAYER_CAMERA_FOV_EYEZOOM, m_fFovAbsVel, 0.1, 1000, pDt);
            }
            else if (m_isEntering) //sets FOV immediatelly to avoid "floating camera" effect
            {
                m_fFovAbsolute = optics.GetCurrentStepFOV();
                m_isEntering = false;
            }
            else
            {
                m_fFovAbsolute = Math.SmoothCD(m_fFovAbsolute, optics.GetCurrentStepFOV(), m_fFovAbsVel, 0.1, 1000, pDt);
                //m_fFovAbsolute = optics.GetCurrentStepFOV();
            }
            return m_fFovAbsolute;
        }
        else
        {
            //Error("optic camera, but there is no optic item or optic on weapon"); //camera update ticks on transitions as well, caused problems
            return 0.6;  //TODO figure some other way to get original FOV here!
        }
    }
References GameConstants::DZPLAYER_CAMERA_FOV_EYEZOOM, GetCurrentSightEntity(), m_fFovAbsolute, m_fFovAbsVel, m_pPlayer, and Math::SmoothCD().
Referenced by AdjustCameraParameters().
Init()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 348 of file dayzplayercameraironsights.c.
    {
        if (m_opticsUsed && m_opticsUsed.IsNVOptic() && m_opticsUsed.IsWorking())
        {
            SetCameraNV(true);
        }
        else
        {
            SetCameraNV(false);
        }
    }
References m_opticsUsed, and SetCameraNV().
Referenced by DayZPlayerCameraBase(), and DayZPlayerCameraBase::DayZPlayerCameraIronsights().
OnActivate()
override void OnActivate (DayZPlayerCamera pPrevCamera, DayZPlayerCameraResult pPrevCameraResult)
Definition at line 376 of file dayzplayercameraironsights.c.
    {
        super.OnActivate(pPrevCamera,pPrevCameraResult);
        PlayerBase player = PlayerBase.Cast(m_pPlayer);
        if (player)
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(player.HideClothing,m_CameraPPDelay*1000,false,m_opticsUsed,true);
        }
    }
References CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), m_CameraPPDelay, m_opticsUsed, and m_pPlayer.
SendRecoilOffsetZ()
override void SendRecoilOffsetZ (float offset)
Definition at line 575 of file dayzplayercameraironsights.c.
    {
        m_RecoilOffsetZ = offset;
    }
References m_RecoilOffsetZ.
SetCameraPP()
override void SetCameraPP (bool state, DayZPlayerCamera launchedFrom)
Definition at line 437 of file dayzplayercameraironsights.c.
    {
        //Print("SetCameraPP - optics");
        if (PlayerBase.Cast(m_pPlayer) && launchedFrom.Type() != PlayerBase.Cast(m_pPlayer).GetCurrentPlayerCamera().Type())
        {
            //Print("DayZPlayerCameraOptics | SetCameraPP | skipping, wrong camera type active!");
            return;
        }
        if (!state || !m_opticsUsed)
        {
            m_RequesterADS.Stop();
            if (IsCameraNV())
            {
                SetNVPostprocess(GetCameraNVType());
            }
            else
            {
                SetNVPostprocess(NVTypes.NONE);
            }
            if (m_weaponUsed)
            {
                m_weaponUsed.HideWeaponBarrel(false);
            }
        }
        else
        {
            array<float> lens_values = new array<float>;
            array<float> mask_values = new array<float>;
            float gauss = 0.0;
            temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
            // 1x scopes only
            if (m_opticsUsed.AllowsDOF() && !NVGoggles.Cast(m_opticsUsed))
            {
                if (m_weaponUsed)
                {
                    if (m_opticsUsed.GetOpticsDOF().Count() == 6)
                    {
                        temp_array = m_opticsUsed.GetOpticsDOF();
                    }
                    else
                    {
                        temp_array = m_weaponUsed.GetWeaponDOF(); //TODO should some optics have own DOF settings (different eye point)?
                    }
                    if (temp_array.Count() != 6)
                        temp_array = {false, 0.0, 0.0, 0.0, 0.0, 1.0};
                }
                m_RequesterADS.SetValuesIronsights(temp_array); //DOF only
                // optics NV mode
                if (m_opticsUsed.IsNVOptic())
                {
                    SetCameraNV(true);
                    SetNVPostprocess(m_opticsUsed.GetCurrentNVType());
                }
                else
                {
                    if (IsCameraNV())
                    {
                        SetNVPostprocess(GetCameraNVType());
                    }
                    else
                    {
                        SetNVPostprocess(NVTypes.NONE);
                    }
                }
            }
            else //magnifying scopes
            {
                // optics mask
                if (m_opticsUsed.GetOpticsPPMask() && m_opticsUsed.GetOpticsPPMask().Count() == 4)
                {
                    mask_values = m_opticsUsed.GetOpticsPPMask();
                }
                //optics lens
                if (m_opticsUsed.GetOpticsPPLens() && m_opticsUsed.GetOpticsPPLens().Count() == 4)
                {
                    lens_values = m_opticsUsed.GetOpticsPPLens();
                }
                //optics blur
                if (m_opticsUsed.GetOpticsPPBlur() != 0)
                {
                    gauss = m_opticsUsed.GetOpticsPPBlur();
                }
                m_RequesterADS.SetValuesOptics(mask_values,lens_values,gauss);
                // optics NV mode
                if (m_opticsUsed.IsNVOptic())
                {
                    SetCameraNV(true);
                    SetNVPostprocess(m_opticsUsed.GetCurrentNVType());
                }
                else
                {
                    SetNVPostprocess(NVTypes.NONE); //magnifying optics do not combine with other NV sources (would render NV optics obsolete)
                }
            }
            if (m_weaponUsed)
            {
                m_weaponUsed.HideWeaponBarrel(true);
            }
        }
    }
References GetCameraNVType(), IsCameraNV(), m_opticsUsed, m_pPlayer, m_weaponUsed, SetCameraNV(), and SetNVPostprocess().
SetCameraPPDelay()
override void SetCameraPPDelay (DayZPlayerCamera pPrevCamera)
Definition at line 555 of file dayzplayercameraironsights.c.
    {
        if (pPrevCamera.GetCameraName() == "DayZPlayerCameraIronsights")
        {
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_02 - 0.05;
        }
        else if (pPrevCamera.GetCameraName() == "DayZPlayerCamera1stPerson")
        {
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_02 - 0.05; //changed to accomodate handheld optics, had to be changed here also
        }
        else if (!pPrevCamera.IsCamera3rdRaised())
        {
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_03 - 0.05;
        }
        else
        {
            m_CameraPPDelay = DayZPlayerCameras.TIME_CAMERACHANGE_02 - 0.05;
        }
    }
References m_CameraPPDelay, DayZPlayerCameras::TIME_CAMERACHANGE_02, and DayZPlayerCameras::TIME_CAMERACHANGE_03.
Variable Documentation
CONST_NEARPLANE_OPTICS
class DayZPlayerCameraIronsights extends DayZPlayerCameraBase CONST_NEARPLANE_OPTICS = 0.06
Referenced by AdjustCameraParameters().
m_RecoilOffsetZ
protected float m_RecoilOffsetZ = 0.0
Definition at line 339 of file dayzplayercameraironsights.c.
Referenced by AdjustCameraParameters(), and SendRecoilOffsetZ().