DayzKode: P:/scripts/3_game/DayZ/entities/dayzinfectedtype.c File Reference
dayzinfectedtype.c File Reference
Classes
class DayZInfectedAttackType
Enumerations
enum DayZInfectedAttackGroupType
Functions
DayZInfectedAttackType ChooseAttack (DayZInfectedAttackGroupType pAttackGroupType, float pDistance, int pPitch)
protected float ComputeAttackUtility (DayZInfectedAttackType pAttackType, float pTargetDistance, int pPitch, float pProbability)
protected array< ref DayZInfectedAttackType > GetAttackGroup (DayZInfectedAttackGroupType pType)
string GetDefaultHitComponent ()
string GetDefaultHitPositionComponent ()
string GetHitComponentForAI ()
array< string > GetSuitableFinisherHitComponents ()
protected void RegisterAttack (DayZInfectedAttackGroupType pAttackGroupType, float pDistance, int pPitch, int pType, float pSubtype, string pAmmoType, int pIsHeavy, float pCooldown, float pProbability)
void RegisterAttacks ()
enum DayZInfectedAttackGroupType RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
Variables
CHASE
FIGHT
private ref array< ref DayZInfectedAttackType > m_ChaseAttacksGroup
selected & sorted targets by utility function
protected string m_DefaultHitComponent
protected string m_DefaultHitPositionComponent
private ref array< ref DayZInfectedAttackType > m_FightAttacksGroup
protected ref array< ref DayZAIHitComponent > m_HitComponentsForAI
Melee hit components (AI targeting)
protected ref array< string > m_SuitableFinisherHitComponents
Enumeration Type Documentation
DayZInfectedAttackGroupType
enum DayZInfectedAttackGroupType
Definition at line 13 of file dayzinfectedtype.c.
{
    CHASE,
    FIGHT
}
Function Documentation
ChooseAttack()
DayZInfectedAttackType ChooseAttack (DayZInfectedAttackGroupType pAttackGroupType, float pDistance, int pPitch)
Definition at line 96 of file dayzinfectedtype.c.
    {
        array<ref DayZInfectedAttackType> attackGroup = GetAttackGroup(pAttackGroupType);
        float rnd;
        float highestUtility = -1;
        DayZInfectedAttackType mostSuitableAttack = NULL;
        for ( int i = 0; i < attackGroup.Count(); ++i )
        {
            rnd = Math.RandomFloat01();
            DayZInfectedAttackType attackType = attackGroup.Get(i);
            float utility = ComputeAttackUtility(attackType, pDistance, pPitch, rnd);
            if ( utility <= 0 )
                continue;
            if ( utility > highestUtility )
            {
                mostSuitableAttack = attackType;
                highestUtility = utility;
            }
        }
        //Print("Most sutable attack selected: " + mostSuitableAttack);
        return mostSuitableAttack;
    }
References ComputeAttackUtility(), GetAttackGroup(), and Math::RandomFloat01().
ComputeAttackUtility()
protected float ComputeAttackUtility (DayZInfectedAttackType pAttackType, float pTargetDistance, int pPitch, float pProbability)
Definition at line 169 of file dayzinfectedtype.c.
    {
        // pitch
        if ( pAttackType.m_Pitch != pPitch )
            return 0;
        // distance
        float distDiff = ( pAttackType.m_Distance ) - pTargetDistance;
        if ( distDiff < 0 )
            return 0;
        float distDiffFrac = distDiff / 10;
        float utilityDistance = (1 - distDiffFrac) * 100; // distance is most important
        // probability
        float probDiff = pAttackType.m_Probability - pProbability;
        if ( probDiff < 0 )
            return 0;
        float utilityProbability = (1 - probDiff) * 10; // distance is most important
        // total
        float util = utilityDistance + utilityProbability;
        //Print("Attack Utility " + util);
        return util;
    }
References DayZInfectedAttackType::m_Distance, DayZInfectedAttackType::m_Pitch, and DayZInfectedAttackType::m_Probability.
Referenced by ChooseAttack().
GetAttackGroup()
protected array< ref DayZInfectedAttackType > GetAttackGroup (DayZInfectedAttackGroupType pType)
Definition at line 195 of file dayzinfectedtype.c.
    {
        switch ( pType )
        {
        case DayZInfectedAttackGroupType.CHASE:
            return m_ChaseAttacksGroup;
        case DayZInfectedAttackGroupType.FIGHT:
            return m_FightAttacksGroup;
        }
        return NULL;
    }
References m_ChaseAttacksGroup, and m_FightAttacksGroup.
Referenced by ChooseAttack(), and RegisterAttack().
GetDefaultHitComponent()
string GetDefaultHitComponent ()
Definition at line 134 of file dayzinfectedtype.c.
    {
        return m_DefaultHitComponent;
    }
References m_DefaultHitComponent.
GetDefaultHitPositionComponent()
string GetDefaultHitPositionComponent ()
Definition at line 139 of file dayzinfectedtype.c.
    {
        return m_DefaultHitPositionComponent;
    }
References m_DefaultHitPositionComponent.
GetHitComponentForAI()
string GetHitComponentForAI ()
Definition at line 122 of file dayzinfectedtype.c.
    {
        string hitComp;
        if (DayZAIHitComponentHelpers.SelectMostProbableHitComponent(m_HitComponentsForAI, hitComp))
        {
            return hitComp;
        }
        return GetDefaultHitComponent();
    }
References GetDefaultHitComponent(), m_HitComponentsForAI, and DayZAIHitComponentHelpers::SelectMostProbableHitComponent().
GetSuitableFinisherHitComponents()
array< string > GetSuitableFinisherHitComponents ()
Definition at line 144 of file dayzinfectedtype.c.
    {
        return m_SuitableFinisherHitComponents;
    }
References m_SuitableFinisherHitComponents.
RegisterAttack()
protected void RegisterAttack (DayZInfectedAttackGroupType pAttackGroupType, float pDistance, int pPitch, int pType, float pSubtype, string pAmmoType, int pIsHeavy, float pCooldown, float pProbability)
Definition at line 153 of file dayzinfectedtype.c.
    {
        DayZInfectedAttackType newType = new DayZInfectedAttackType();
        newType.m_Distance = pDistance;
        newType.m_Pitch = pPitch;
        newType.m_Type = pType; //If attack is left or right
        newType.m_Subtype = pSubtype; //If attack is center, down, up or run
        newType.m_AmmoType = pAmmoType;
        newType.m_IsHeavy = pIsHeavy;
        newType.m_Cooldown = pCooldown;
        newType.m_Probability = pProbability;
        GetAttackGroup(pAttackGroupType).Insert(newType);
    }
References GetAttackGroup(), DayZInfectedAttackType::m_AmmoType, DayZInfectedAttackType::m_Cooldown, DayZInfectedAttackType::m_Distance, DayZInfectedAttackType::m_IsHeavy, DayZInfectedAttackType::m_Pitch, DayZInfectedAttackType::m_Probability, DayZInfectedAttackType::m_Subtype, and DayZInfectedAttackType::m_Type.
Referenced by RegisterAttacks().
RegisterAttacks()
void RegisterAttacks ()
RegisterAttack(Group Type, Distance, Pitch, Type, Subtype, AmmoType, heavyFlag, Cooldown, Probability);
chase group
center attack
fight group
up attack
center attack
down attack
Definition at line 49 of file dayzinfectedtype.c.
    {
        string lightAttPath = string.Format("cfgVehicles %1 AttackActions AttackShort ammoType", GetName());
        string heavyAttPath = string.Format("cfgVehicles %1 AttackActions AttackLong ammoType", GetName());
        string chaseAttPath = string.Format("cfgVehicles %1 AttackActions AttackRun ammoType", GetName());
        string lightAttAmmo;
        GetGame().ConfigGetText(lightAttPath, lightAttAmmo);
        string heavyAttAmmo;
        GetGame().ConfigGetText(heavyAttPath, heavyAttAmmo);
        string chaseAttAmmo;
        GetGame().ConfigGetText(chaseAttPath, chaseAttAmmo);
        m_ChaseAttacksGroup = new array<ref DayZInfectedAttackType>;
        RegisterAttack(DayZInfectedAttackGroupType.CHASE, /*3.0*/2.4,  -1, 0, 1, chaseAttAmmo, 0, 0.3, 1.0); // center left & light
        RegisterAttack(DayZInfectedAttackGroupType.CHASE, /*3.0*/2.4,  -1, 1, 1, chaseAttAmmo, 0, 0.4, 1.0); // center right & light
        m_FightAttacksGroup = new array<ref DayZInfectedAttackType>;
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  1, 0, 0, lightAttAmmo, 0, 0.3, 0.7); // up left & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  1, 1, 0, lightAttAmmo, 0, 0.4, 0.7); // up right & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  0, 0, 1, lightAttAmmo, 0, 0.1, 0.9); // center left & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  0, 1, 1, lightAttAmmo, 0, 0.2, 0.9); // center right & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.5*/1.4,  0, 2, 1, heavyAttAmmo, 0/*1*/, 0.3, 0.6); // center left & heavy
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.5*/1.4,  0, 3, 1, heavyAttAmmo, 0/*1*/, 0.4, 0.6); // center right & heavy
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  -1, 0, 2, lightAttAmmo, 0, 0.2, 0.5); // down left & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.0*/1.7,  -1, 1, 2, lightAttAmmo, 0, 0.3, 0.4); // down right & light
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.5*/1.4,  -1, 2, 2, heavyAttAmmo, 0/*1*/, 0.5, 0.8); // down left & heavy
        RegisterAttack(DayZInfectedAttackGroupType.FIGHT, /*2.5*/1.4,  -1, 3, 2, heavyAttAmmo, 0/*1*/, 0.6, 0.8); // down right & heavy
    }
References CGame::ConfigGetText(), GetGame(), DayZCreatureAIType::GetName(), m_ChaseAttacksGroup, m_FightAttacksGroup, and RegisterAttack().
RegisterHitComponentsForAI()
enum DayZInfectedAttackGroupType RegisterHitComponentsForAI ()
register hit components for AI melee (used by attacking AI)
registers default hit compoent for the entity
registers default hit position component for entity
list of components suitable for melee finisher attacks (used in fight logic)
register hit components that are selected by probability
Definition at line 1 of file dayzinfectedtype.c.
    {
        m_HitComponentsForAI = new array<ref DayZAIHitComponent>;
        m_DefaultHitComponent = "Torso";
        m_DefaultHitPositionComponent = "Pelvis";
        m_SuitableFinisherHitComponents = new array<string>;
        m_SuitableFinisherHitComponents.Insert("Head");
        m_SuitableFinisherHitComponents.Insert("Neck");
        m_SuitableFinisherHitComponents.Insert("Torso");
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Head", 2);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "LeftArm", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "Torso", 65);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "RightArm", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "LeftLeg", 50);
        DayZAIHitComponentHelpers.RegisterHitComponent(m_HitComponentsForAI, "RightLeg", 50);
    }
Variable Documentation
CHASE
CHASE
Definition at line 26 of file dayzinfectedtype.c.
FIGHT
FIGHT
Definition at line 27 of file dayzinfectedtype.c.
m_ChaseAttacksGroup
private ref array<ref DayZInfectedAttackType> m_ChaseAttacksGroup
selected & sorted targets by utility function
Definition at line 214 of file dayzinfectedtype.c.
Referenced by GetAttackGroup(), and RegisterAttacks().
m_DefaultHitComponent
protected string m_DefaultHitComponent
Definition at line 219 of file dayzinfectedtype.c.
m_DefaultHitPositionComponent
protected string m_DefaultHitPositionComponent
Definition at line 220 of file dayzinfectedtype.c.
m_FightAttacksGroup
private ref array<ref DayZInfectedAttackType> m_FightAttacksGroup
Definition at line 215 of file dayzinfectedtype.c.
Referenced by GetAttackGroup(), and RegisterAttacks().
m_HitComponentsForAI
protected ref array<ref DayZAIHitComponent> m_HitComponentsForAI
Melee hit components (AI targeting)
Definition at line 218 of file dayzinfectedtype.c.
m_SuitableFinisherHitComponents
protected ref array<string> m_SuitableFinisherHitComponents
Definition at line 221 of file dayzinfectedtype.c.