DayzKode: P:/scripts/4_world/DayZ/entities/manbase/dayzplayer/dayzplayercfgsounds.c File Reference
dayzplayercfgsounds.c File Reference
Classes
class DayZPlayerTypeStepSoundLookupTable
class DayZPlayerTypeVoiceSoundLookupTable
Functions
class DayZPlayerTypeStepSoundLookupTableImpl extends DayZPlayerTypeStepSoundLookupTable DayZPlayerTypeAttachmentSoundLookupTableImpl ()
void DayZPlayerTypeRegisterSounds (DayZPlayerType pType)
class DayZPlayerTypeVoiceSoundLookupTableImpl extends DayZPlayerTypeVoiceSoundLookupTable DayZPlayerTypeSoundTableImpl ()
void DayZPlayerTypeStepSoundLookupTableImpl ()
void DayZPlayerTypeVoiceSoundLookupTableImpl ()
static DayZPlayerTypeStepSoundLookupTableImpl GetInstance ()
override NoiseParams GetNoiseParams (int eventId)
override SoundObjectBuilder GetSoundBuilder (int eventId, int parameterHash)
override SoundObjectBuilder GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
override SoundObjectBuilder GetSoundBuilder (int eventId, string slotName, int attachmentHash)
override AnimSoundEvent GetSoundEvent (int event_id)
Variables
private ref array< ref AnimSoundEvent > m_animSoundEvents
static private ref DayZPlayerTypeStepSoundLookupTableImpl m_instance
private autoptr map< int, ref StepSoundLookupTable > m_pSoundTableInstances
private autoptr map< int, StepSoundLookupTable > m_pSoundTables
Function Documentation
DayZPlayerTypeAttachmentSoundLookupTableImpl()
class DayZPlayerTypeStepSoundLookupTableImpl extends DayZPlayerTypeStepSoundLookupTable DayZPlayerTypeAttachmentSoundLookupTableImpl ()
Definition at line 1 of file dayzplayercfgsounds.c.
    {
        m_pSoundTableInstances = new map<int, ref AttachmentSoundLookupTable>;
        m_pSoundTables = new map<int, AttachmentSoundLookupTable>();
        string attachCfgPath = "CfgVehicles SurvivorBase AnimEvents Attachments ";
        int attachCount = GetGame().ConfigGetChildrenCount(attachCfgPath);
        for(int i = 0; i < attachCount; i++)
        {
            string defName;
            GetGame().ConfigGetChildName(attachCfgPath, i, defName);
            string defPath = attachCfgPath + defName + " ";
            string slotName;
            GetGame().ConfigGetText(defPath + "slot", slotName);
            int id = GetGame().ConfigGetInt(defPath + "id");
            string tableName;
            GetGame().ConfigGetText(defPath + "soundLookupTable", tableName);
            AttachmentSoundLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
            if(table == NULL)
            {
                table = new AttachmentSoundLookupTable();
                table.LoadTable(tableName);
                m_pSoundTableInstances.Insert(tableName.Hash(), table);
            }
            m_pSoundTables.Insert((slotName + id).Hash(), table);
        }
    }
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeRegisterSounds()
void DayZPlayerTypeRegisterSounds (DayZPlayerType pType)
register events
load and register step sound lookup table
Definition at line 320 of file dayzplayercfgsounds.c.
{
    GetGame().ProfilerStart("DayZPlayerTypeRegisterSounds");
    pType.RegisterStepEvent("Step", 0.2);
    pType.RegisterSoundEvent("Sound", -1);
    pType.RegisterSoundEvent("SoundWeapon", 0.2);
    pType.RegisterSoundEvent("SoundVoice", -1);
    if(!GetGame().IsDedicatedServer())//attachments don't generate noise, so we can ignore them on server
        pType.RegisterSoundEvent("SoundAttachment", 0.2);
    DayZPlayerTypeVoiceSoundLookupTableImpl voiceTable2 = DayZPlayerTypeVoiceSoundLookupTableImpl.GetInstance();
    pType.RegisterVoiceSoundLookupTable(voiceTable2);
    if(!GetGame().IsDedicatedServer())//sounds are unnecessary on server
    {
        pType.RegisterParticleEvent("Particle", -1);
        DayZPlayerTypeStepSoundLookupTableImpl stepTable = DayZPlayerTypeStepSoundLookupTableImpl.GetInstance();
        pType.RegisterStepSoundLookupTable(stepTable);
        DayZPlayerTypeAttachmentSoundLookupTableImpl attachTable = DayZPlayerTypeAttachmentSoundLookupTableImpl.GetInstance();
        pType.RegisterAttachmentSoundLookupTable(attachTable);
        DayZPlayerTypeSoundTableImpl soundTable = DayZPlayerTypeSoundTableImpl.GetInstance();
        pType.RegisterSoundTable(soundTable);
        //DayZPlayerTypeSoundVoiceTableImpl voiceTable = new DayZPlayerTypeSoundVoiceTableImpl();
        //pType.RegisterSoundVoiceTable(voiceTable);
    }
    GetGame().ProfilerStop("DayZPlayerTypeRegisterSounds");
}
References DayZPlayerTypeAttachmentSoundLookupTableImpl(), DayZPlayerTypeSoundTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), GetGame(), DayZPlayerTypeStepSoundLookupTable::GetInstance(), DayZPlayerTypeVoiceSoundLookupTable::GetInstance(), CGame::ProfilerStart(), and CGame::ProfilerStop().
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeCreate().
DayZPlayerTypeSoundTableImpl()
class DayZPlayerTypeVoiceSoundLookupTableImpl extends DayZPlayerTypeVoiceSoundLookupTable DayZPlayerTypeSoundTableImpl ()
Definition at line 165 of file dayzplayercfgsounds.c.
    {
        m_animSoundEvents = new array<ref AnimSoundEvent>;
        string soundsCfgPath = "CfgVehicles SurvivorBase AnimEvents Sounds ";
        int soundCount = GetGame().ConfigGetChildrenCount(soundsCfgPath);
        for(int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if(soundEvent.IsValid())
                m_animSoundEvents.Insert(soundEvent);
        }
    }
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeStepSoundLookupTableImpl()
void DayZPlayerTypeAttachmentSoundLookupTableImpl::DayZPlayerTypeStepSoundLookupTableImpl ()
Definition at line 106 of file dayzplayercfgsounds.c.
    {
        m_pSoundTableInstances = new map<int, ref AttachmentSoundLookupTable>;
        m_pSoundTables = new map<int, AttachmentSoundLookupTable>();
        string attachCfgPath = "CfgVehicles SurvivorBase AnimEvents Attachments ";
        int attachCount = GetGame().ConfigGetChildrenCount(attachCfgPath);
        for(int i = 0; i < attachCount; i++)
        {
            string defName;
            GetGame().ConfigGetChildName(attachCfgPath, i, defName);
            string defPath = attachCfgPath + defName + " ";
            string slotName;
            GetGame().ConfigGetText(defPath + "slot", slotName);
            int id = GetGame().ConfigGetInt(defPath + "id");
            string tableName;
            GetGame().ConfigGetText(defPath + "soundLookupTable", tableName);
            AttachmentSoundLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
            if(table == NULL)
            {
                table = new AttachmentSoundLookupTable();
                table.LoadTable(tableName);
                m_pSoundTableInstances.Insert(tableName.Hash(), table);
            }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigGetText(), GetGame(), string::Hash(), m_pSoundTableInstances, and m_pSoundTables.
Referenced by DayZPlayerTypeRegisterSounds().
DayZPlayerTypeVoiceSoundLookupTableImpl()
void DayZPlayerTypeSoundTableImpl::DayZPlayerTypeVoiceSoundLookupTableImpl ()
Definition at line 246 of file dayzplayercfgsounds.c.
    {
        m_animSoundEvents = new array<ref AnimSoundEvent>;
        string soundsCfgPath = "CfgVehicles SurvivorBase AnimEvents Sounds ";
        int soundCount = GetGame().ConfigGetChildrenCount(soundsCfgPath);
        for(int i = 0; i < soundCount; i++)
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if(soundEvent.IsValid())
                m_animSoundEvents.Insert(soundEvent);
        }
    }
    override AnimSoundEvent GetSoundEvent(int event_id)
    {
        for(int i = 0; i < m_animSoundEvents.Count(); i++)
        {
            AnimSoundEvent soundEvent = m_animSoundEvents.Get(i);
            if(soundEvent.m_iID == event_id)
            {
                return soundEvent;
            }
        }
        return NULL;
    }
    static DayZPlayerTypeSoundTableImpl GetInstance()
    {
        if(m_instance == NULL)
            m_instance = new DayZPlayerTypeSoundTableImpl();
        return m_instance;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), GetGame(), and m_animSoundEvents.
Referenced by DayZPlayerTypeRegisterSounds().
GetInstance()
static DayZPlayerTypeSoundTableImpl GetInstance () static
Definition at line 192 of file dayzplayercfgsounds.c.
                {
                    NoiseParams np = new NoiseParams;
                    np.Load(noiseName);
                    table.SetNoiseParam(np);
References NoiseParams().
GetNoiseParams()
override NoiseParams DayZPlayerTypeSoundTableImpl::GetNoiseParams (int eventId)
Definition at line 298 of file dayzplayercfgsounds.c.
        {
            string soundName;
            GetGame().ConfigGetChildName(soundsCfgPath, i, soundName);
            string soundPath = soundsCfgPath + soundName + " ";
            AnimSoundEvent soundEvent = new AnimSoundEvent(soundPath);
            if(soundEvent.IsValid())
GetSoundBuilder() [1/3]
override SoundObjectBuilder DayZPlayerTypeSoundTableImpl::GetSoundBuilder (int eventId, int parameterHash)
Definition at line 285 of file dayzplayercfgsounds.c.
{
GetSoundBuilder() [2/3]
override SoundObjectBuilder DayZPlayerTypeAttachmentSoundLookupTableImpl::GetSoundBuilder (int eventId, int pMovement, int pSurfaceHash, AnimBootsType pBoots)
Definition at line 135 of file dayzplayercfgsounds.c.
    {
        SoundLookupTable table = m_pSoundTables.Get((slotName + eventId).Hash());
        if(table == NULL)
            return NULL;
        SoundObjectBuilder soundBuilder = table.GetSoundBuilder(attachmentHash);
        if(soundBuilder == NULL)
            return NULL;
        return soundBuilder;
    }
    static DayZPlayerTypeAttachmentSoundLookupTableImpl GetInstance()
    {
        if(m_instance == NULL)
            m_instance = new DayZPlayerTypeAttachmentSoundLookupTableImpl();
        return m_instance;
    }
    private static ref DayZPlayerTypeAttachmentSoundLookupTableImpl m_instance;
    private autoptr map<int, ref AttachmentSoundLookupTable> m_pSoundTableInstances;
    private autoptr map<int, AttachmentSoundLookupTable> m_pSoundTables;
}
class DayZPlayerTypeVoiceSoundLookupTableImpl extends DayZPlayerTypeVoiceSoundLookupTable
{
    void DayZPlayerTypeVoiceSoundLookupTableImpl()
    {
        m_pSoundTableInstances = new map<int, ref PlayerVoiceLookupTable>;
        m_pSoundTables = new map<int, PlayerVoiceLookupTable>();
        string cfgPath = "CfgVehicles SurvivorBase AnimEvents SoundVoice ";
        int childCount = GetGame().ConfigGetChildrenCount(cfgPath);
        //Print("childCount:" + childCount);
        for(int i = 0; i < childCount; i++)
        {
            string defName;
            GetGame().ConfigGetChildName(cfgPath, i, defName);
            string defPath = cfgPath + defName + " ";
            int id = GetGame().ConfigGetInt(defPath + "id");
            string tableName;
            GetGame().ConfigGetText(defPath + "soundLookupTable", tableName);
            PlayerVoiceLookupTable table = m_pSoundTableInstances.Get(tableName.Hash());
            if(table == NULL)
            {
                table = new PlayerVoiceLookupTable();
                table.LoadTable(tableName);
GetSoundBuilder() [3/3]
override SoundObjectBuilder GetSoundBuilder (int eventId, string slotName, int attachmentHash)
Definition at line 138 of file dayzplayercfgsounds.c.
    {
        SoundLookupTable table = m_pSoundTables.Get((slotName + eventId).Hash());
        if(table == NULL)
            return NULL;
        SoundObjectBuilder soundBuilder = table.GetSoundBuilder(attachmentHash);
        if(soundBuilder == NULL)
            return NULL;
        return soundBuilder;
    }
References SoundLookupTable::GetSoundBuilder(), and m_pSoundTables.
GetSoundEvent()
override AnimSoundEvent GetSoundEvent (int event_id)
Definition at line 263 of file dayzplayercfgsounds.c.
    {
        for(int i = 0; i < m_animSoundEvents.Count(); i++)
        {
            AnimSoundEvent soundEvent = m_animSoundEvents.Get(i);
            if(soundEvent.m_iID == event_id)
            {
                return soundEvent;
            }
        }
        return NULL;
    }
References m_animSoundEvents.
Variable Documentation
m_animSoundEvents
private ref array<ref AnimSoundEvent> m_animSoundEvents
Definition at line 286 of file dayzplayercfgsounds.c.
Referenced by DayZPlayerTypeVoiceSoundLookupTableImpl(), and GetSoundEvent().
m_instance
static private ref DayZPlayerTypeSoundTableImpl m_instance static
Definition at line 200 of file dayzplayercfgsounds.c.
m_pSoundTableInstances
private autoptr map< int, ref PlayerVoiceLookupTable > m_pSoundTableInstances
Definition at line 201 of file dayzplayercfgsounds.c.
Referenced by DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), and DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl().
m_pSoundTables
private autoptr map< int, PlayerVoiceLookupTable > m_pSoundTables
Definition at line 202 of file dayzplayercfgsounds.c.
Referenced by DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::GetNoiseParams(), DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder(), DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), and GetSoundBuilder().