DayzKode: P:/scripts/4_world/DayZ/systems/inventory/dayzplayerinventory.c File Reference
dayzplayerinventory.c File Reference
Classes
class DeferredEvent
class DeferredHandEvent
class DeferredSwapEntities
Functions
void AbortWeaponEvent ()
void CancelHandEvent ()
cancels any handevents that will be executed this frame @NOTE: this is used in situations where the player performs an action that renders the event invalid exactly on the frame it will be executed
void CancelWeaponEvent ()
void CheckForRope (InventoryLocation src, InventoryLocation dst)
override void ClearInventoryReservation (HumanInventory inventory)
void DayZPlayerInventory ()
void DeferredForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
void DeferredHandEvent (InventoryMode mode, HandEventBase e)
void DeferredTakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
void DeferredWeaponFailed ()
void EnableMovableOverride (EntityAI item)
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
DayZPlayer GetDayZPlayerOwner ()
override bool HandEvent (InventoryMode mode, HandEventBase e)
void HandleForceSwapEntities (DeferredEvent deferred_event)
void HandleHandEvent (DeferredEvent deferred_event)
bool HandleInputData (bool handling_juncture, bool remote, ParamsReadContext ctx)
void HandleInventory (float dt)
override void HandleInventoryManipulation ()
void HandleSwapEntities (DeferredEvent deferred_event)
void HandleTakeToDst (DeferredEvent deferred_event)
void HandleWeaponEvents (float dt, out bool exitIronSights)
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
bool IsProcessing ()
bool IsServerOrLocalPlayer ()
override void NetSyncCurrentStateID (int id)
override void OnAfterStoreLoad ()
bool OnEventForRemoteWeapon (ParamsReadContext ctx)
bool OnHandEventForRemote (ParamsReadContext ctx)
override void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst)
override void OnHandsExitedStableState (HandStateBase src, HandStateBase dst)
override void OnHandsStateChanged (HandStateBase src, HandStateBase dst)
bool OnInputUserDataForRemote (ParamsReadContext ctx)
override void OnServerInventoryCommand (ParamsReadContext ctx)
bool PlayerCheckDropRequest (notnull InventoryLocation src, float radius)
bool PlayerCheckRequestDst (notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
bool PlayerCheckRequestSrc (notnull InventoryLocation src, float radius)
bool PlayerCheckSwapItemsRequest (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
void PostWeaponEvent (WeaponEventBase e)
override bool ProccessInputData (int type, bool handling_juncture, bool remote, ParamsReadContext ctx)
void RemoveMovableOverride (EntityAI item)
override bool ReserveInventory (HumanInventory inventory)
static void SendServerHandEventViaJuncture (notnull DayZPlayer player, HandEventBase e)
bool StoreInputForRemotes (bool handling_juncture, bool remote, ParamsReadContext ctx)
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
void SyncHandEventToRemote (HandEventBase e)
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
protected void OnHandleStoredJunctureData (ParamsReadContext ctx)
override bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
override bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
proto native void StoreJunctureData (ParamsReadContext ctx)
protected void OnHandleStoredInputUserData (ParamsReadContext ctx)
override bool OnInputUserDataProcess (ParamsReadContext ctx)
proto native void StoreInputUserData (ParamsReadContext ctx)
Variables
m_DeferredEvent = NULL
protected ref HandEventBase m_DeferredPostedHandEvent = NULL
ref WeaponEventBase m_DeferredWeaponEvent = NULL
deferred hand event
ref Timer m_DeferredWeaponTimer = new Timer
ref InventoryLocation m_dst
ref InventoryLocation m_dst1
ref InventoryLocation m_dst2
ref HandEventBase m_event
protected ref HandAnimatedForceSwapping m_FSwapping
protected ref HandAnimatedForceSwapping_Inst m_FSwappingInst
DeferredSwapEntities m_item1
EntityAI m_item2
protected ref HandAnimatedMovingToAtt m_MovingTo
class DeferredEvent m_src
protected ref HandAnimatedSwapping m_Swapping
protected ref HandAnimatedTakingFromAtt m_Taking
deferred weapon event
Function Documentation
AbortWeaponEvent()
void AbortWeaponEvent ()
Definition at line 233 of file dayzplayerinventory.c.
    {
        HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
        Weapon_Base weapon;
        Class.CastTo(weapon, GetEntityInHands());
        if (hcw && weapon && weapon.CanProcessWeaponEvents() && !weapon.IsIdle())
        {
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: ABORT! notifying running state=" + weapon.GetCurrentState()); }
            weapon.ProcessWeaponAbortEvent(new WeaponEventHumanCommandActionAborted(GetDayZPlayerOwner()));
        }
    }
References Class::CastTo(), GetDayZPlayerOwner(), LogManager::IsWeaponLogEnable(), and wpnDebugPrint().
CancelHandEvent()
CancelHandEvent ()
cancels any handevents that will be executed this frame @NOTE: this is used in situations where the player performs an action that renders the event invalid exactly on the frame it will be executed
Definition at line 221 of file dayzplayerinventory.c.
    {
        m_DeferredPostedHandEvent = null;
        //m_postedHandEvent = null;
    }
References m_DeferredPostedHandEvent.
CancelWeaponEvent()
void CancelWeaponEvent ()
Definition at line 227 of file dayzplayerinventory.c.
    {
        m_DeferredWeaponEvent = null;
        m_DeferredWeaponTimer.Stop();
    }
References m_DeferredWeaponEvent, and m_DeferredWeaponTimer.
Referenced by DeferredWeaponFailed().
CheckForRope()
void CheckForRope (InventoryLocation src, InventoryLocation dst)
Definition at line 1156 of file dayzplayerinventory.c.
    {
        Rope rope = Rope.Cast(src.GetItem());
        if (rope)
            rope.SetTargetLocation(dst);
    }
References InventoryLocation::GetItem().
Referenced by ProccessInputData().
ClearInventoryReservation()
override void ClearInventoryReservation (HumanInventory inventory)
Definition at line 31 of file dayzplayerinventory.c.
    {
        inventory.ClearInventoryReservationEx(m_dst.GetItem(), m_dst);
    }
References InventoryLocation::GetItem(), and m_dst.
DayZPlayerInventory()
void DayZPlayerInventory ()
Definition at line 151 of file dayzplayerinventory.c.
    {
    }
DeferredForceSwapEntities()
void DeferredForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation dst1, notnull InventoryLocation dst2)
Definition at line 81 of file dayzplayerinventory.c.
    {
        m_mode = mode;
        m_item1 = item1;
        m_item2 = item2;
        m_dst1 = dst1;
        m_dst2 = dst2;
    }
References m_dst1, m_dst2, m_item1, and m_item2.
Referenced by ForceSwapEntities(), and HandleForceSwapEntities().
DeferredHandEvent()
void DayZPlayerInventory::DeferredHandEvent (InventoryMode mode, HandEventBase e)
Definition at line 114 of file dayzplayerinventory.c.
    {
        m_mode = mode;
        m_event = e;
    }
DeferredTakeToDst()
void DeferredTakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
Definition at line 15 of file dayzplayerinventory.c.
    {
        m_mode = mode;
        m_src = src;
        m_dst = dst;
    }
References m_dst, and m_src.
Referenced by HandleTakeToDst(), and TakeToDst().
DeferredWeaponFailed()
void DeferredWeaponFailed ()
Definition at line 262 of file dayzplayerinventory.c.
    {
        Weapon_Base weapon;
        Class.CastTo(weapon, GetEntityInHands());
        string secondPart = " - ENTITY IN HANDS IS NOT A WEAPON: " + Object.GetDebugName(GetEntityInHands());
        string firstPart = "[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " failed to perform weaponevent " + m_DeferredWeaponEvent.DumpToString();
        if (weapon)
        {
            secondPart = " on " + Object.GetDebugName(GetEntityInHands()) + " which is in state " + weapon.GetCurrentState();
            secondPart += " with physical state: J: " + weapon.IsJammed() + " | ";
            for (int i = 0; i < weapon.GetMuzzleCount(); ++i)
            {
                secondPart += "Chamber_" + i + ": B(" + weapon.IsChamberFull(i) + ") F(" + weapon.IsChamberFiredOut(i) + ") E(" + weapon.IsChamberEmpty(i) + ") | ";
                secondPart += "Magazine_" + i + ": " + weapon.GetMagazine(i);
                if (i < weapon.GetMuzzleCount() - 1)
                    secondPart += " | ";
            }
        }
        Error(firstPart + secondPart);
        CancelWeaponEvent();
    }
References CancelWeaponEvent(), Class::CastTo(), WeaponEventBase::DumpToString(), Error(), GetInventoryOwner(), and m_DeferredWeaponEvent.
EnableMovableOverride()
void EnableMovableOverride (EntityAI item)
Definition at line 1148 of file dayzplayerinventory.c.
    {
        ItemBase itemIB = ItemBase.Cast(item);
        if (itemIB)
            itemIB.SetCanBeMovedOverride(true);
    }
Referenced by HandleHandEvent(), HandleSwapEntities(), HandleTakeToDst(), and ProccessInputData().
ForceSwapEntities()
override bool ForceSwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2, notnull InventoryLocation item2_dst)
Definition at line 1456 of file dayzplayerinventory.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryMoveLogEnable() )
        {
            Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + item1 + " item2 = " + item2 + " dst=" + InventoryLocation.DumpToStringNullSafe(item2_dst), "n/a" , "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString() );
        }
        #endif
        if( mode == InventoryMode.LOCAL )
        {
            InventoryLocation src1, src2, dst1;
            if (GameInventory.MakeSrcAndDstForForceSwap(item1, item2, src1, src2, dst1, item2_dst))
            {
                LocationSwap(src1, src2, dst1, item2_dst);
                return true;
            }
        }
        if(!super.ForceSwapEntities(mode,item1,item2,item2_dst))
        {
            if(!m_DeferredEvent)
            {
                if (GameInventory.MakeSrcAndDstForForceSwap(item1, item2, src1, src2, dst1, item2_dst))
                {
                    m_DeferredEvent = new DeferredForceSwapEntities(mode,item1,item2, dst1, item2_dst);
                    if( m_DeferredEvent.ReserveInventory(this))
                        return true;
                }
            }
            m_DeferredEvent = null;
            return false;
        }
        return true;
    }
References DeferredForceSwapEntities(), InventoryLocation::DumpToStringNullSafe(), GetDayZPlayerOwner(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LocationSwap(), m_DeferredEvent, and ToString().
GetDayZPlayerOwner()
DayZPlayer GetDayZPlayerOwner ()
Definition at line 155 of file dayzplayerinventory.c.
{ return DayZPlayer.Cast(GetInventoryOwner()); }
References GetInventoryOwner().
Referenced by AbortWeaponEvent(), ForceSwapEntities(), HandleForceSwapEntities(), HandleHandEvent(), HandleInputData(), HandleInventory(), HandleSwapEntities(), HandleTakeToDst(), HandleWeaponEvents(), IsServerOrLocalPlayer(), NetSyncCurrentStateID(), OnAfterStoreLoad(), OnEventForRemoteWeapon(), OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnHandsStateChanged(), OnInputUserDataForRemote(), OnInputUserDataProcess(), OnInventoryJunctureFromServer(), OnServerInventoryCommand(), PlayerCheckDropRequest(), PlayerCheckRequestDst(), PlayerCheckRequestSrc(), PlayerCheckSwapItemsRequest(), ProccessInputData(), StoreInputForRemotes(), SwapEntities(), SyncHandEventToRemote(), and TakeToDst().
HandEvent()
override bool HandEvent (InventoryMode mode, HandEventBase e)
Definition at line 1731 of file dayzplayerinventory.c.
    {
        if (!m_DeferredEvent)
        {
            EntityAI itemInHands = GetEntityInHands();
            InventoryLocation handInventoryLocation = new InventoryLocation;
            handInventoryLocation.SetHands(GetInventoryOwner(), itemInHands);
            bool hadHandReservation = false;
            if (e.CanPerformEvent())
            {
                m_DeferredEvent = new DeferredHandEvent(mode,e);
                if(m_DeferredEvent.ReserveInventory(this))
                    return true;
            }
            m_DeferredEvent = null;
        }
        return false;
    }
References HandEventBase::CanPerformEvent(), GetInventoryOwner(), m_DeferredEvent, and InventoryLocation::SetHands().
HandleForceSwapEntities()
void HandleForceSwapEntities (DeferredEvent deferred_event)
Definition at line 1496 of file dayzplayerinventory.c.
    {
        DeferredForceSwapEntities deferred_force_swap_entities = DeferredForceSwapEntities.Cast(deferred_event);
        if( deferred_force_swap_entities )
        {
            deferred_force_swap_entities.ClearInventoryReservation(this);
            InventoryLocation src1 = new InventoryLocation;
            InventoryLocation src2 = new InventoryLocation;
            deferred_force_swap_entities.m_item1.GetInventory().GetCurrentInventoryLocation(src1);
            deferred_force_swap_entities.m_item2.GetInventory().GetCurrentInventoryLocation(src2);
            DayZPlayer player = GetGame().GetPlayer();
            inventoryDebugPrint("[inv] I::FSwap(" + typename.EnumToString(InventoryMode, deferred_force_swap_entities.m_mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2));
            switch (deferred_force_swap_entities.m_mode)
            {
                case InventoryMode.PREDICTIVE:
                    if (CanForceSwapEntitiesEx(deferred_force_swap_entities.m_dst1.GetItem(),deferred_force_swap_entities.m_dst1,deferred_force_swap_entities.m_dst2.GetItem(), deferred_force_swap_entities.m_dst2))
                    {
                        InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
                        LocationSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Can not force swap (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_force_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_force_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2), "n/a" , "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                    }
                    break;
                case InventoryMode.JUNCTURE:
                    if (CanForceSwapEntitiesEx(deferred_force_swap_entities.m_dst1.GetItem(),deferred_force_swap_entities.m_dst1,deferred_force_swap_entities.m_dst2.GetItem(), deferred_force_swap_entities.m_dst2))
                    {
                        player.GetHumanInventory().AddInventoryReservationEx(deferred_force_swap_entities.m_item1, deferred_force_swap_entities.m_dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
                        player.GetHumanInventory().AddInventoryReservationEx(deferred_force_swap_entities.m_item2, deferred_force_swap_entities.m_dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
                        InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_force_swap_entities.m_dst1, deferred_force_swap_entities.m_dst2);
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Can not force swap (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_force_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_force_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_force_swap_entities.m_dst2), "n/a" , "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                    }
                    break;
                case InventoryMode.LOCAL:
                    break;
                default:
                    Error("ForceSwapEntities - HandEvent - Invalid mode");
            }
        }
    }
References CanForceSwapEntitiesEx(), DeferredForceSwapEntities(), InventoryLocation::DumpToStringNullSafe(), Error(), GetDayZPlayerOwner(), GetGame(), CGame::GetPlayer(), inventoryDebugPrint(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LocationSwap(), InventoryInputUserData::SendInputUserDataSwap(), and ToString().
Referenced by HandleInventoryManipulation().
HandleHandEvent()
void HandleHandEvent (DeferredEvent deferred_event)
Definition at line 1755 of file dayzplayerinventory.c.
    {
        DeferredHandEvent deferred_hand_event = DeferredHandEvent.Cast(deferred_event);
        if(deferred_hand_event)
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a" , "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString() );
            }
            #endif
            hndDebugPrint("[inv] HumanInventory::HandEvent(" + typename.EnumToString(InventoryMode, deferred_hand_event.m_mode) + ") ev=" + deferred_hand_event.m_event.DumpToString());
            switch (deferred_hand_event.m_mode)
            {
                case InventoryMode.PREDICTIVE:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("PREDICTIVE", "n/a" , "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    deferred_hand_event.ClearInventoryReservation(this);
                    if ( deferred_hand_event.m_event.CanPerformEvent() )
                    {
                        InventoryInputUserData.SendInputUserDataHandEvent(deferred_hand_event.m_event);
                        ProcessHandEvent(deferred_hand_event.m_event);
                    }
                    break;
                case InventoryMode.JUNCTURE:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("JUNCTURE", "n/a" , "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    deferred_hand_event.ClearInventoryReservation(this);
                    if ( deferred_hand_event.m_event.CanPerformEvent() )
                    {
                        deferred_hand_event.ReserveInventory(this);
                        InventoryInputUserData.SendInputUserDataHandEvent(deferred_hand_event.m_event);
                        //Functionality to prevent desync when two players perform interfering action at the same time
                        EntityAI itemSrc = deferred_hand_event.m_event.GetSrcEntity();
                        EntityAI itemDst = null;
                        if (deferred_hand_event.m_event.GetDst())
                            itemDst = deferred_hand_event.m_event.GetDst().GetItem();
                        if (itemSrc)
                            EnableMovableOverride(itemSrc);
                        if (itemDst)
                            EnableMovableOverride(itemDst);
                    }
                    break;
                case InventoryMode.LOCAL:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("LOCAL", "n/a" , "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    deferred_hand_event.ClearInventoryReservation(this);
                    ProcessHandEvent(deferred_hand_event.m_event);
                    //PostHandEvent(deferred_hand_event.m_event);
                    break;
                case InventoryMode.SERVER:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("SERVER", "n/a" , "n/a", "HandleHandEvent", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    hndDebugPrint("[inv] DZPI::HandEvent(" + typename.EnumToString(InventoryMode, deferred_hand_event.m_mode) + ")");
                    if (!deferred_hand_event.m_event.IsServerSideOnly())
                    {
                        if (GetDayZPlayerOwner().IsAlive())
{
                            SendServerHandEventViaJuncture(GetDayZPlayerOwner(), deferred_hand_event.m_event);
                        }
                        else
{
                            InventoryInputUserData.SendServerHandEventViaInventoryCommand(GetDayZPlayerOwner(), deferred_hand_event.m_event);
                        }
                    }
                    else
                    {
                        ProcessHandEvent(deferred_hand_event.m_event);
                    }
                 break;
                default:
                    Error("HumanInventory::HandEvent - Invalid mode");
            }
        }
    }
References HandEventBase::CanPerformEvent(), DeferredHandEvent::ClearInventoryReservation(), HandEventBase::DumpToString(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), HandEventBase::GetDst(), InventoryLocation::GetItem(), hndDebugPrint(), Debug::InventoryHFSMLog(), IsAlive(), LogManager::IsInventoryHFSMLogEnable(), HandEventBase::IsServerSideOnly(), DeferredHandEvent::m_event, DeferredEvent::m_mode, DeferredHandEvent::ReserveInventory(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), and ToString().
Referenced by HandleInventoryManipulation().
HandleInputData()
bool HandleInputData (bool handling_juncture, bool remote, ParamsReadContext ctx)
Definition at line 1126 of file dayzplayerinventory.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryMoveLogEnable() )
        {
            Debug.InventoryMoveLog(" STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " t=" + GetGame().GetTime() + " pos=" + GetDayZPlayerOwner().GetPosition() + "rmt=" + remote, "n/a" , "n/a", "HandleInputData", GetDayZPlayerOwner().ToString() );
        }
        #endif
        int type = -1;
        if (!ctx.Read(type))
            return false;
        return ProccessInputData(type,handling_juncture, remote, ctx);
    }
References GetDayZPlayerOwner(), GetGame(), GetPosition, GetTime(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), ProccessInputData(), Serializer::Read(), and ToString().
Referenced by OnHandleStoredInputUserData(), OnHandleStoredJunctureData(), OnInputUserDataForRemote(), and OnServerInventoryCommand().
HandleInventory()
void HandleInventory (float dt)
Definition at line 356 of file dayzplayerinventory.c.
    {
        HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
        EntityAI ih = GetEntityInHands();
        Weapon_Base weapon;
        Class.CastTo(weapon, ih);
        if (hcw)
        {
            m_FSM.GetCurrentState().OnUpdate(dt);
            #ifdef DEVELOPER
            hndDebugSpamALot("[hndfsm] HCW: playing A=" + typename.EnumToString(WeaponActions, hcw.GetRunningAction()) + " AT=" + WeaponActionTypeToString(hcw.GetRunningAction(), hcw.GetRunningActionType()) + " fini=" + hcw.IsActionFinished());
            #endif
            if ( !m_FSM.GetCurrentState().IsIdle() || !m_FSM.IsRunning() )
            {
                while (true)
                {
                    int weaponEventId = hcw.IsEvent();
                    if (weaponEventId == -1)
                    {
                        break;
                    }
                    HandEventBase anim_event = HandAnimEventFactory(weaponEventId, GetManOwner(), NULL);
                    #ifdef DEVELOPER
                    hndDebugPrint("[hndfsm] HandleInventory: event arrived " + typename.EnumToString(WeaponEvents, weaponEventId) + "(" + weaponEventId + ")  fsm_ev=" + anim_event.ToString());
                    #endif
                    if (anim_event != NULL)
                    {
                        SyncHandEventToRemote(anim_event);
                        ProcessHandEvent(anim_event);
                    }
                }
                if (hcw.IsActionFinished())
                {
                    if (m_FSM.GetCurrentState().IsWaitingForActionFinish())
                    {
                        #ifdef DEVELOPER
                        hndDebugPrint("[hndfsm] Hand-Weapon event: finished! notifying waiting state=" + m_FSM.GetCurrentState());
                        #endif
                        HandEventBase fin_event = new HandEventHumanCommandActionFinished(GetManOwner());
                        SyncHandEventToRemote(fin_event);
                        ProcessHandEvent(fin_event);
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        hndDebugPrint("[hndfsm] Hand-Weapon event: ABORT! notifying running state=" + m_FSM.GetCurrentState());
                        #endif
                        HandEventBase abt_event = new HandEventHumanCommandActionAborted(GetManOwner());
                        SyncHandEventToRemote(abt_event);
                        ProcessHandAbortEvent(abt_event);
                        //m_FSM.ProcessHandAbortEvent(new WeaponEventHumanCommandActionAborted(GetManOwner()));
                    }
                }
            }
        }
    }
References Class::CastTo(), GetDayZPlayerOwner(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), HandAnimEventFactory(), hndDebugPrint(), hndDebugSpamALot(), HumanCommandWeapons::IsActionFinished(), HumanCommandWeapons::IsEvent(), SyncHandEventToRemote(), and WeaponActionTypeToString().
HandleInventoryManipulation()
override void HandleInventoryManipulation ()
Definition at line 1855 of file dayzplayerinventory.c.
    {
        super.HandleInventoryManipulation();
        if(m_DeferredEvent && ScriptInputUserData.CanStoreInputUserData() )
        {
            HandleHandEvent(m_DeferredEvent);
            HandleTakeToDst(m_DeferredEvent);
            HandleSwapEntities(m_DeferredEvent);
            HandleForceSwapEntities(m_DeferredEvent);
            m_DeferredEvent = null;
        }
    }
References ScriptInputUserData::CanStoreInputUserData(), HandleForceSwapEntities(), HandleHandEvent(), HandleSwapEntities(), HandleTakeToDst(), and m_DeferredEvent.
HandleSwapEntities()
void HandleSwapEntities (DeferredEvent deferred_event)
Definition at line 1393 of file dayzplayerinventory.c.
    {
        DeferredSwapEntities deferred_swap_entities = DeferredSwapEntities.Cast(deferred_event);
        if( deferred_swap_entities )
        {
            deferred_swap_entities.ClearInventoryReservation(this);
            InventoryLocation src1, src2, dst1, dst2;
            if (GameInventory.MakeSrcAndDstForSwap(deferred_swap_entities.m_item1, deferred_swap_entities.m_item2, src1, src2, dst1, dst2))
            {
                inventoryDebugPrint("[inv] I::Swap(" + typename.EnumToString(InventoryMode, deferred_swap_entities.m_mode) + ") src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2));
                switch (deferred_swap_entities.m_mode)
                {
                    case InventoryMode.PREDICTIVE:
                        if (CanSwapEntitiesEx(deferred_swap_entities.m_dst1.GetItem(),deferred_swap_entities.m_dst2.GetItem()) )
{
                            InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
                            LocationSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
                        }
                        else
{
                            #ifdef DEVELOPER
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Can not swap (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2), "n/a" , "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                        }
                        break;
                    case InventoryMode.JUNCTURE:
                        if (CanSwapEntitiesEx(deferred_swap_entities.m_dst1.GetItem(),deferred_swap_entities.m_dst2.GetItem()) )
{
                            DayZPlayer player = GetGame().GetPlayer();
                            player.GetHumanInventory().AddInventoryReservationEx(deferred_swap_entities.m_dst1.GetItem(), deferred_swap_entities.m_dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
                            player.GetHumanInventory().AddInventoryReservationEx(deferred_swap_entities.m_dst2.GetItem(), deferred_swap_entities.m_dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
                            EnableMovableOverride(deferred_swap_entities.m_dst1.GetItem());
                            EnableMovableOverride(deferred_swap_entities.m_dst2.GetItem());
                            InventoryInputUserData.SendInputUserDataSwap(src1, src2, deferred_swap_entities.m_dst1, deferred_swap_entities.m_dst2);
                        }
                        else
{
                            #ifdef DEVELOPER
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Can not swap (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + deferred_swap_entities.m_dst1.GetItem() + " item2 = " + deferred_swap_entities.m_dst2.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_swap_entities.m_dst2), "n/a" , "n/a", "ForceSwapEntities", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                        }
                        break;
                    case InventoryMode.LOCAL:
                        break;
                    default:
                        Error("SwapEntities - HandEvent - Invalid mode");
                }
            }
            else
                Error("SwapEntities - MakeSrcAndDstForSwap - no inv loc");
        }
    }
References CanSwapEntitiesEx(), DeferredSwapEntities::ClearInventoryReservation(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetGame(), InventoryLocation::GetItem(), CGame::GetPlayer(), inventoryDebugPrint(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LocationSwap(), DeferredSwapEntities::m_dst1, DeferredSwapEntities::m_dst2, DeferredSwapEntities::m_item1, DeferredSwapEntities::m_item2, DeferredEvent::m_mode, InventoryInputUserData::SendInputUserDataSwap(), and ToString().
Referenced by HandleInventoryManipulation().
HandleTakeToDst()
void HandleTakeToDst (DeferredEvent deferred_event)
Definition at line 1267 of file dayzplayerinventory.c.
    {
        DeferredTakeToDst deferred_take_to_dst = DeferredTakeToDst.Cast(deferred_event);
        if( deferred_take_to_dst )
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryHFSMLogEnable() )
            {
                Debug.InventoryHFSMLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
            }
            #endif
            deferred_take_to_dst.ClearInventoryReservation(this);
            inventoryDebugPrint("[inv] I::Take2Dst(" + typename.EnumToString(InventoryMode, deferred_take_to_dst.m_mode) + ") src=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_src) + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst));
            switch (deferred_take_to_dst.m_mode)
            {
                case InventoryMode.PREDICTIVE:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("PREDICTIVE ", "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    if (LocationCanMoveEntity(deferred_take_to_dst.m_src,deferred_take_to_dst.m_dst))
                    {
                        InventoryInputUserData.SendInputUserDataMove(InventoryCommandType.SYNC_MOVE, deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
                        LocationSyncMoveEntity(deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Can not move entity (PREDICTIVE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item = " + deferred_take_to_dst.m_dst.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst), "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                    }
                    break;
                case InventoryMode.JUNCTURE:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("JUNCTURE ", "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    if (LocationCanMoveEntity(deferred_take_to_dst.m_src,deferred_take_to_dst.m_dst))
                    {
                        DayZPlayer player = GetGame().GetPlayer();
                        player.GetHumanInventory().AddInventoryReservationEx(deferred_take_to_dst.m_dst.GetItem(), deferred_take_to_dst.m_dst, GameInventory.c_InventoryReservationTimeoutShortMS);
                        EnableMovableOverride(deferred_take_to_dst.m_dst.GetItem());
                        InventoryInputUserData.SendInputUserDataMove(InventoryCommandType.SYNC_MOVE, deferred_take_to_dst.m_src, deferred_take_to_dst.m_dst);
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Can not move entity (JUNCTURE) STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item = " + deferred_take_to_dst.m_dst.GetItem() + " dst=" + InventoryLocation.DumpToStringNullSafe(deferred_take_to_dst.m_dst), "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                    }
                    break;
                case InventoryMode.LOCAL:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("LOCAL ", "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    break;
                case InventoryMode.SERVER:
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryHFSMLogEnable() )
                    {
                        Debug.InventoryHFSMLog("SERVER ", "n/a" , "n/a", "HandleTakeToDst", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    break;
                    break;
                default:
                    Error("HandEvent - Invalid mode");
            }
        }
    }
References DeferredTakeToDst(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), GetGame(), CGame::GetPlayer(), inventoryDebugPrint(), Debug::InventoryHFSMLog(), Debug::InventoryMoveLog(), LogManager::IsInventoryHFSMLogEnable(), LogManager::IsInventoryMoveLogEnable(), LocationCanMoveEntity(), LocationSyncMoveEntity(), InventoryInputUserData::SendInputUserDataMove(), and ToString().
Referenced by HandleInventoryManipulation().
HandleWeaponEvents()
void HandleWeaponEvents (float dt, out bool exitIronSights)
Definition at line 287 of file dayzplayerinventory.c.
    {
        HumanCommandWeapons hcw = GetDayZPlayerOwner().GetCommandModifier_Weapons();
        Weapon_Base weapon;
        Class.CastTo(weapon, GetEntityInHands());
        if (hcw && weapon && weapon.CanProcessWeaponEvents())
        {
            weapon.GetCurrentState().OnUpdate(dt);
            if (LogManager.IsWeaponLogEnable()) { wpnDebugSpamALot("[wpnfsm] " + Object.GetDebugName(weapon) + " HCW: playing A=" + typename.EnumToString(WeaponActions, hcw.GetRunningAction()) + " AT=" + WeaponActionTypeToString(hcw.GetRunningAction(), hcw.GetRunningActionType()) + " fini=" + hcw.IsActionFinished()); }
            if (!weapon.IsIdle())
            {
                while (true)
                {
                    int weaponEventId = hcw.IsEvent();
                    if (weaponEventId == -1)
                    {
                        break;
                    }
                    if (weaponEventId == WeaponEvents.CHANGE_HIDE)
                    {
                        break;
                    }
                    WeaponEventBase anim_event = WeaponAnimEventFactory(weaponEventId, GetDayZPlayerOwner(), NULL);
                    if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " HandleWeapons: event arrived " + typename.EnumToString(WeaponEvents, weaponEventId) + "(" + weaponEventId + ")  fsm_ev=" + anim_event.ToString()); }
                    if (anim_event != NULL)
                    {
                        weapon.ProcessWeaponEvent(anim_event);
                    }
                }
                if (hcw.IsActionFinished())
                {
                    if (weapon.IsWaitingForActionFinish())
                    {
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: finished! notifying waiting state=" + weapon.GetCurrentState()); }
                        weapon.ProcessWeaponEvent(new WeaponEventHumanCommandActionFinished(GetDayZPlayerOwner()));
                    }
                    else
                    {
                        if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: ABORT! notifying running state=" + weapon.GetCurrentState()); }
                        weapon.ProcessWeaponAbortEvent(new WeaponEventHumanCommandActionAborted(GetDayZPlayerOwner()));
                    }
                }
            }
            if (m_DeferredWeaponEvent)
            {
                if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: deferred " + m_DeferredWeaponEvent.DumpToString()); }
                if (weapon.ProcessWeaponEvent(m_DeferredWeaponEvent))
                {
                    exitIronSights = true;
                    fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(weapon) + " Weapon event: resetting deferred event" + m_DeferredWeaponEvent.DumpToString());
                    m_DeferredWeaponEvent = NULL;
                    m_DeferredWeaponTimer.Stop();
                }
                else if (!m_DeferredWeaponTimer.IsRunning())
                {
                    m_DeferredWeaponTimer.Run(3, this, "DeferredWeaponFailed");
                }
            }
        }
    }
References Class::CastTo(), WeaponEventBase::DumpToString(), fsmDebugSpam(), GetDayZPlayerOwner(), HumanCommandWeapons::GetRunningAction(), HumanCommandWeapons::GetRunningActionType(), HumanCommandWeapons::IsActionFinished(), HumanCommandWeapons::IsEvent(), LogManager::IsWeaponLogEnable(), m_DeferredWeaponEvent, m_DeferredWeaponTimer, WeaponActionTypeToString(), WeaponAnimEventFactory(), wpnDebugPrint(), and wpnDebugSpamALot().
Init()
override void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 157 of file dayzplayerinventory.c.
    {
        hndDebugPrint("[hndfsm] Creating DayZPlayer Inventory FSM");
        CreateStableStates(); // stable states needs to be created first
        m_Taking = new HandAnimatedTakingFromAtt(GetManOwner(), null);
        m_MovingTo = new HandAnimatedMovingToAtt(GetManOwner(), null);
        m_Swapping = new HandAnimatedSwapping(GetManOwner(), null);
        m_FSwapping = new HandAnimatedForceSwapping(GetManOwner(), null);
        m_FSwappingInst = new HandAnimatedForceSwapping_Inst(GetManOwner(), null);
        // events
        HandEventBase _fin_ = new HandEventHumanCommandActionFinished;
        HandEventBase _abt_ = new HandEventHumanCommandActionAborted;
        HandEventBase __T__ = new HandEventTake;
        HandEventBase __M__ = new HandEventMoveTo;
        HandEventBase __W__ = new HandEventSwap;
        //HandEventBase __D__ = new HandEventDropping;
        HandEventBase __Xd_ = new HandEventDestroyed;
        HandEventBase __F__ = new HandEventForceSwap;
        // setup transitions
        m_FSM.AddTransition(new HandTransition( m_Empty   , __T__,  m_Taking, NULL, new HandSelectAnimationOfTakeToHandsEvent(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_Taking  , _fin_,  m_Empty, null, new HandGuardNot(new HandGuardHasItemInHands(GetManOwner()))));
        m_FSM.AddTransition(new HandTransition( m_Taking  , _fin_,  m_Equipped, null, null));
        m_FSM.AddTransition(new HandTransition( m_Taking  , __Xd_,  m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
            m_Taking.AddTransition(new HandTransition(  m_Taking.m_Hide, _abt_,   m_Empty));
            m_Taking.AddTransition(new HandTransition(  m_Taking.m_Show, _abt_,   m_Equipped));
        m_FSM.AddTransition(new HandTransition( m_Equipped, __M__,  m_MovingTo, NULL, new HandSelectAnimationOfMoveFromHandsEvent(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_MovingTo, __Xd_,  m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_MovingTo, _fin_,  m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_MovingTo, _fin_,  m_Empty   , null, null));
            m_MovingTo.AddTransition(new HandTransition(  m_MovingTo.m_Hide, _abt_,   m_Equipped));
            m_MovingTo.AddTransition(new HandTransition(  m_MovingTo.m_Show, _abt_,   m_Empty));
        m_FSM.AddTransition(new HandTransition( m_Equipped, __W__,  m_Swapping, NULL, new HandSelectAnimationOfSwapInHandsEvent(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_Swapping, __Xd_,  m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_Swapping, _fin_,  m_Empty, null, new HandGuardNot(new HandGuardHasItemInHands(GetManOwner()))));
        m_FSM.AddTransition(new HandTransition( m_Swapping, _fin_,  m_Equipped, null, null));
        m_FSM.AddTransition(new HandTransition( m_Swapping, _abt_,  m_Equipped, null, null));
        m_FSM.AddTransition(new HandTransition( m_Equipped, __F__, m_FSwappingInst, NULL, new HandGuardAnd( new HandSelectAnimationOfForceSwapInHandsEvent(GetManOwner()), new HandGuardInstantForceSwap(GetManOwner()) ) ));
        m_FSM.AddTransition(new HandTransition(m_FSwappingInst, _fin_,  m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition(m_FSwappingInst, _fin_,  m_Empty, null, null));
        m_FSM.AddTransition(new HandTransition(m_FSwappingInst, __Xd_,  m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition( m_FSwappingInst, _abt_,  m_Equipped, null, null));
        m_FSM.AddTransition(new HandTransition( m_Equipped, __F__, m_FSwapping, NULL, new HandSelectAnimationOfForceSwapInHandsEvent(GetManOwner())));
        m_FSM.AddTransition(new HandTransition(m_FSwapping, _fin_,  m_Equipped, null, new HandGuardHasItemInHands(GetManOwner())));
        m_FSM.AddTransition(new HandTransition(m_FSwapping, _fin_,  m_Empty, null, null));
        m_FSM.AddTransition(new HandTransition(m_FSwapping, __Xd_,  m_Empty, new HandActionDestroyed, new HandGuardHasDestroyedItemInHands(GetManOwner())));
            m_FSwapping.AddTransition(new HandTransition(  m_FSwapping.m_Start, _abt_,   m_Equipped));
            m_FSwapping.AddTransition(new HandTransition(  m_FSwapping.m_Hide, _abt_,   m_Empty));
            m_FSwapping.AddTransition(new HandTransition(  m_FSwapping.m_Show, _abt_,   m_Equipped));
        super.Init(); // initialize ordinary human fsm (no anims)
    }
References hndDebugPrint(), m_FSwapping, m_FSwappingInst, m_MovingTo, m_Swapping, and m_Taking.
IsProcessing()
bool IsProcessing ()
Definition at line 1871 of file dayzplayerinventory.c.
    {
        return !m_FSM.GetCurrentState().IsIdle() || m_DeferredEvent || m_DeferredPostedHandEvent;
    }
References m_DeferredEvent, and m_DeferredPostedHandEvent.
Referenced by HandleADS(), and ManBase::OnQuickBarSingleUse().
IsServerOrLocalPlayer()
bool IsServerOrLocalPlayer ()
Definition at line 1163 of file dayzplayerinventory.c.
    {
        return GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || GetDayZPlayerOwner() == GetGame().GetPlayer());
    }
References GetDayZPlayerOwner(), GetGame(), and CGame::GetPlayer().
Referenced by ProccessInputData().
NetSyncCurrentStateID()
override void NetSyncCurrentStateID (int id)
Definition at line 1600 of file dayzplayerinventory.c.
    {
        super.NetSyncCurrentStateID(id);
        GetDayZPlayerOwner().GetItemAccessor().OnItemInHandsChanged();
    }
References GetDayZPlayerOwner().
OnAfterStoreLoad()
override void OnAfterStoreLoad ()
Definition at line 1613 of file dayzplayerinventory.c.
    {
        GetDayZPlayerOwner().GetItemAccessor().OnItemInHandsChanged(true);
    }
References GetDayZPlayerOwner().
OnEventForRemoteWeapon()
bool OnEventForRemoteWeapon (ParamsReadContext ctx)
Definition at line 1621 of file dayzplayerinventory.c.
    {
        if (GetEntityInHands())
        {
            Weapon_Base wpn = Weapon_Base.Cast(GetEntityInHands());
            if (wpn)
            {
                PlayerBase pb = PlayerBase.Cast(GetDayZPlayerOwner());
                WeaponEventBase e = CreateWeaponEventFromContext(ctx);
                if (pb && e)
                {
                    pb.GetWeaponManager().SetRunning(true);
                    fsmDebugSpam("[wpnfsm] " + Object.GetDebugName(wpn) + " recv event from remote: created event=" + e);
                    if (e.GetEventID() == WeaponEventID.HUMANCOMMAND_ACTION_ABORTED)
                    {
                        wpn.ProcessWeaponAbortEvent(e);
                    }
                    else
                    {
                        wpn.ProcessWeaponEvent(e);
                    }
                    pb.GetWeaponManager().SetRunning(false);
                }
            }
            else
                Error("OnEventForRemoteWeapon - entity in hands, but not weapon. item=" + GetEntityInHands());
        }
        else
            Error("OnEventForRemoteWeapon - no entity in hands");
        return true;
    }
References CreateWeaponEventFromContext(), Error(), fsmDebugSpam(), GetDayZPlayerOwner(), and WeaponEventBase::GetEventID().
OnHandEventForRemote()
bool OnHandEventForRemote (ParamsReadContext ctx)
Definition at line 1659 of file dayzplayerinventory.c.
    {
        HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
        if (e)
        {
            hndDebugSpam("[hndfsm] recv event from remote: created event=" + e);
            //m_FSM.ProcessEvent(e);
            if (e.GetEventID() == HandEventID.HUMANCOMMAND_ACTION_ABORTED)
            {
                ProcessEventResult aa;
                m_FSM.ProcessAbortEvent(e, aa);
            }
            else
            {
                m_FSM.ProcessEvent(e);
            }
            return true;
        }
        return false;
    }
References hndDebugSpam().
OnHandleStoredInputUserData()
protected void OnHandleStoredInputUserData (ParamsReadContext ctx)
Definition at line 499 of file dayzplayerinventory.c.
    {
        int tmp = -1;
        ctx.Read(tmp);
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " handle InputUserData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
        HandleInputData(false, false, ctx);
    }
References GetDayZPlayerOwner(), HandleInputData(), Serializer::Read(), and syncDebugPrint().
OnHandleStoredJunctureData()
protected void OnHandleStoredJunctureData (ParamsReadContext ctx)
Definition at line 465 of file dayzplayerinventory.c.
    {
        int tmp = -1;
        ctx.Read(tmp);
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " handle JunctureData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
        HandleInputData(true, false, ctx);
    }
References GetDayZPlayerOwner(), HandleInputData(), Serializer::Read(), and syncDebugPrint().
OnHandsEnteredStableState()
override void OnHandsEnteredStableState (HandStateBase src, HandStateBase dst)
Definition at line 1703 of file dayzplayerinventory.c.
    {
        super.OnHandsEnteredStableState(src, dst);
        hndDebugPrint("[hndfsm] hand fsm entered stable dst=" + dst.Type().ToString());
    }
References hndDebugPrint().
Referenced by OnHandsStateChanged().
OnHandsExitedStableState()
override void OnHandsExitedStableState (HandStateBase src, HandStateBase dst)
Definition at line 1696 of file dayzplayerinventory.c.
    {
        super.OnHandsExitedStableState(src, dst);
        hndDebugPrint("[hndfsm] hand fsm exit stable src=" + src.Type().ToString());
    }
References hndDebugPrint().
Referenced by OnHandsStateChanged().
OnHandsStateChanged()
override void OnHandsStateChanged (HandStateBase src, HandStateBase dst)
Definition at line 1710 of file dayzplayerinventory.c.
    {
        super.OnHandsStateChanged(src, dst);
        hndDebugPrint("[hndfsm] hand fsm changed state src=" + src.Type().ToString() + " ---> dst=" + dst.Type().ToString());
        if (src.IsIdle())
            OnHandsExitedStableState(src, dst);
        if (dst.IsIdle())
            OnHandsEnteredStableState(src, dst);
#ifdef BOT
        PlayerBase p = PlayerBase.Cast(GetDayZPlayerOwner());
        if (p && p.m_Bot)
        {
            p.m_Bot.ProcessEvent(new BotEventOnItemInHandsChanged(p));
        }
#endif
    }
References GetDayZPlayerOwner(), hndDebugPrint(), HandStateBase::IsIdle(), OnHandsEnteredStableState(), and OnHandsExitedStableState().
OnInputUserDataForRemote()
bool OnInputUserDataForRemote (ParamsReadContext ctx)
Definition at line 513 of file dayzplayerinventory.c.
    {
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " remote handling InputUserData packet from server");
        return HandleInputData(false, true, ctx);
    }
References GetDayZPlayerOwner(), HandleInputData(), and syncDebugPrint().
OnInputUserDataProcess()
override bool OnInputUserDataProcess (ParamsReadContext ctx)
Definition at line 488 of file dayzplayerinventory.c.
    {
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " store InputUserData packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
            StoreInputUserData(ctx);
        return true;
    }
References GetDayZPlayerOwner(), StoreInputUserData(), and syncDebugPrint().
OnInventoryJunctureFromServer()
override bool OnInventoryJunctureFromServer (ParamsReadContext ctx)
Definition at line 427 of file dayzplayerinventory.c.
    {
        int tmp = -1;
        ctx.Read(tmp);
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " store Juncture packet STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp());
            StoreJunctureData(ctx);
        return true;
    }
References GetDayZPlayerOwner(), Serializer::Read(), StoreJunctureData(), and syncDebugPrint().
OnInventoryJunctureRepairFromServer()
override bool OnInventoryJunctureRepairFromServer (ParamsReadContext ctx)
Definition at line 443 of file dayzplayerinventory.c.
    {
/*      InventoryLocation il = new InventoryLocation;
        if (!il.ReadFromContext(ctx) )
            return false;
        InventoryLocation il_current = new InventoryLocation;
        EntityAI item = il.GetItem();
        item.GetInventory().GetCurrentInventoryLocation(il_current);
        if( !il_current.CompareLocationOnly(il))
        {
            LocationMoveEntity(il_current,il);
        }*/
        return true;
    }
OnServerInventoryCommand()
override void OnServerInventoryCommand (ParamsReadContext ctx)
Definition at line 519 of file dayzplayerinventory.c.
    {
        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " DZPInventory command from server");
        HandleInputData(true, true, ctx);
    }
References GetDayZPlayerOwner(), HandleInputData(), and syncDebugPrint().
PlayerCheckDropRequest()
bool PlayerCheckDropRequest (notnull InventoryLocation src, float radius)
Definition at line 1991 of file dayzplayerinventory.c.
    {
        bool result = true;
        EntityAI ent = src.GetParent();
        if ( ent )
        {
            PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
            if (player)
            {
                if ( GetDayZPlayerOwner() != player )
                {
                    if (player.IsAlive())
                    {
                        if (!player.IsRestrained() && !player.IsUnconscious())
{
                            return false;
                        }
                    }
                }
            }
        }
        if ( result )
        {
            result = CheckDropRequest( GetManOwner(), src, radius);
        }
        return result;
    }
References CheckDropRequest(), and GetDayZPlayerOwner().
Referenced by ProccessInputData().
PlayerCheckRequestDst()
bool PlayerCheckRequestDst (notnull InventoryLocation src, notnull InventoryLocation dst, float radius)
Definition at line 1907 of file dayzplayerinventory.c.
    {
        bool result = true;
        EntityAI ent = dst.GetParent();
        if ( ent )
        {
            PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
            if (player)
            {
                if ( GetDayZPlayerOwner() != player )
                {
                    if (player.IsAlive())
                    {
                        if (!player.IsRestrained() && !player.IsUnconscious())
{
                            return false;
                        }
                    }
                }
            }
        }
        if ( result )
        {
            result = CheckMoveToDstRequest( GetManOwner(), src, dst, radius);
        }
        return result;
    }
References CheckMoveToDstRequest(), and GetDayZPlayerOwner().
Referenced by ProccessInputData().
PlayerCheckRequestSrc()
bool PlayerCheckRequestSrc (notnull InventoryLocation src, float radius)
Definition at line 1876 of file dayzplayerinventory.c.
    {
        bool result = true;
        EntityAI ent = src.GetParent();
        if ( ent )
        {
            PlayerBase player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
            if (player)
            {
                if ( GetDayZPlayerOwner() != player )
                {
                    if (player.IsAlive())
                    {
                        if (!player.IsRestrained() && !player.IsUnconscious())
{
                            return false;
                        }
                    }
                }
            }
        }
        if ( result )
        {
            result = CheckRequestSrc( GetManOwner(), src, radius);
        }
        return result;
    }
References CheckRequestSrc(), and GetDayZPlayerOwner().
Referenced by ProccessInputData().
PlayerCheckSwapItemsRequest()
bool PlayerCheckSwapItemsRequest (notnull InventoryLocation src1, notnull InventoryLocation src2, notnull InventoryLocation dst1, notnull InventoryLocation dst2, float radius)
Definition at line 1938 of file dayzplayerinventory.c.
    {
        bool result = true;
        EntityAI ent = dst1.GetParent();
        PlayerBase player;
        if ( ent )
        {
            player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
            if (player)
            {
                if ( GetDayZPlayerOwner() != player )
                {
                    if (player.IsAlive())
                    {
                        if (!player.IsRestrained() && !player.IsUnconscious())
{
                            return false;
                        }
                    }
                }
            }
        }
        ent = dst2.GetParent();
        if ( ent )
        {
            player = PlayerBase.Cast(ent.GetHierarchyRootPlayer());
            if (player)
            {
                if ( GetDayZPlayerOwner() != player )
                {
                    if (player.IsAlive())
                    {
                        if (!player.IsRestrained() && !player.IsUnconscious())
{
                            return false;
                        }
                    }
                }
            }
        }
        if ( result )
        {
            result = CheckSwapItemsRequest( GetManOwner(), src1, src2, dst1, dst2, GameInventory.c_MaxItemDistanceRadius);
        }
        return result;
    }
References CheckSwapItemsRequest(), and GetDayZPlayerOwner().
Referenced by ProccessInputData().
PostWeaponEvent()
void PostWeaponEvent (WeaponEventBase e)
Definition at line 251 of file dayzplayerinventory.c.
    {
        if (m_DeferredWeaponEvent == NULL)
        {
            m_DeferredWeaponEvent = e;
            if (LogManager.IsWeaponLogEnable()) { wpnDebugPrint("[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " Posted event m_DeferredWeaponEvent=" + m_DeferredWeaponEvent.DumpToString()); }
        }
        else
            Error("[wpnfsm] " + Object.GetDebugName(GetInventoryOwner()) + " warning - pending event already posted, curr_event=" + m_DeferredWeaponEvent.DumpToString() + " new_event=" + e.DumpToString());
    }
References WeaponEventBase::DumpToString(), Error(), GetInventoryOwner(), LogManager::IsWeaponLogEnable(), m_DeferredWeaponEvent, and wpnDebugPrint().
ProccessInputData()
override bool ProccessInputData (int type, bool handling_juncture, bool remote, ParamsReadContext ctx)
Definition at line 525 of file dayzplayerinventory.c.
    {
        if(super.ProccessInputData(type, handling_juncture, remote, ctx))
            return true;
        InventoryLocation correct_il;
        ScriptJunctureData ctx_repair;
        ScriptInputUserData n_ctx = new ScriptInputUserData;
        switch (type)
        {
            case InventoryCommandType.SYNC_MOVE:
            {
                InventoryLocation src = new InventoryLocation;
                InventoryLocation dst = new InventoryLocation;
                src.ReadFromContext(ctx);
                dst.ReadFromContext(ctx);
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + "src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                }
                #endif
                if (remote && (!src.GetItem() || !dst.GetItem()))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - item not in bubble", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[syncinv] HandleInputData remote input (cmd=SYNC_MOVE) dropped, item not in bubble! src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                    break; // not in bubble
                }
                EnableMovableOverride(src.GetItem());
                if (!PlayerCheckRequestSrc(src, GameInventory.c_MaxItemDistanceRadius))
                {
                    if( GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER )
                    {
                        correct_il = new InventoryLocation;
                        src.GetItem().GetInventory().GetCurrentInventoryLocation(correct_il);
                        if( !correct_il.CompareLocationOnly(src) )
{
                            ctx_repair = new ScriptJunctureData;
                            correct_il.WriteToContext(ctx_repair);
                            GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY_REPAIR, ctx_repair);
                        }
                    }
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src));
                    RemoveMovableOverride(src.GetItem());
                    return false; // stale packet
                }
                //Players should not try to determine whether some other player is cheater or not, this is up to that player and the server
                if ( IsServerOrLocalPlayer() && !PlayerCheckRequestDst(src, dst, GameInventory.c_MaxItemDistanceRadius) )
                {
                    /*if( GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER )
                    {
                        correct_il = new InventoryLocation;
                        src.GetItem().GetInventory().GetCurrentInventoryLocation(correct_il);
                        if( !correct_il.CompareLocationOnly(src) )
{
                            ctx_repair = new ScriptJunctureData;
                            correct_il.WriteToContext(ctx_repair);
                            //GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY_REPAIR, ctx_repair);
                        }
                    }*/
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckMoveToDstRequest", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                    RemoveMovableOverride(src.GetItem());
                    return false; // cheater
                }
                RemoveMovableOverride(src.GetItem());
                syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " HandleInputData t=" + GetGame().GetTime() + "ms received cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                if (!handling_juncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                {
                    JunctureRequestResult result_mv = TryAcquireInventoryJunctureFromServer(GetDayZPlayerOwner(), src, dst);
                    if (result_mv == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture not required", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        // ok, perform sync move
                    }
                    else if (result_mv == JunctureRequestResult.JUNCTURE_ACQUIRED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture sended", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        if (!GameInventory.LocationCanMoveEntity(src, dst))
{
                            #ifdef DEVELOPER
                            DumpInventoryDebug();
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Failed - LocationCanMoveEntity - Juncture denied", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                            return true;
                        }
                        GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx); // ok, send juncture
                        EnableMovableOverride(src.GetItem());
                        break; // and do NOT perform sync move
                    }
                    else if (result_mv == JunctureRequestResult.JUNCTURE_DENIED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture denied", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        return true; // abort, do not send anything to remotes
                    }
                    else
                    {
                        Error("[syncinv] HandleInputData: unexpected return code from AcquireInventoryJunctureFromServer"); return true;
                        return true; // abort, do not send anything to remotes
                    }
                }
                if( GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
                {
                    ClearInventoryReservationEx(dst.GetItem(),dst);
                }
                if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                    CheckForRope(src, dst);
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("Success - LocationSyncMoveEntity", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                }
                #endif
                if (!GameInventory.LocationCanMoveEntitySyncCheck(src, dst))
                {
                    #ifdef DEVELOPER
                    DumpInventoryDebug();
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - LocationCanMoveEntity", "SYNC_MOVE" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    Error("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT move cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                    return false;
                }
                LocationSyncMoveEntity(src, dst);
                break;
            }
            case InventoryCommandType.HAND_EVENT:
            {
                HandEventBase e = HandEventBase.CreateHandEventFromContext(ctx);
                e.ClearInventoryReservation();
                EntityAI itemSrc = e.GetSrcEntity();
                EntityAI itemDst = e.GetSecondSrcEntity();
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("STS = " + e.m_Player.GetSimulationTimeStamp() + "event= " + e.ToString(), "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                }
                #endif
                if (remote && !e.GetSrcEntity())
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                    }
                    #endif
                    Error("[syncinv] HandleInputData remote input (cmd=HAND_EVENT) dropped, item not in bubble");
                    break; // not in bubble
                }
                if (itemSrc)
                    RemoveMovableOverride(itemSrc);
                if (itemDst)
                    RemoveMovableOverride(itemDst);
                if (!e.CheckRequestSrc())
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequestSrc", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                    }
                    #endif
                    if( GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER && itemSrc )
                    {
                        correct_il = new InventoryLocation;
                        itemSrc.GetInventory().GetCurrentInventoryLocation(correct_il);
                        if( !correct_il.CompareLocationOnly(e.GetSrc()) )
{
                            ctx_repair = new ScriptJunctureData;
                            correct_il.WriteToContext(ctx_repair);
                            GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY_REPAIR, ctx_repair);
                        }
                    }
                    if (itemSrc)
                        RemoveMovableOverride(itemSrc);
                    if (itemDst)
                        RemoveMovableOverride(itemDst);
                    return false; // stale packet
                }
                //Players should not try to determine whether some other player is cheater or not, this is up to that player and the server
                if ( IsServerOrLocalPlayer() && !e.CheckRequest() )
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequest", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " event=" + e.DumpToString());
                    if (itemSrc)
                        RemoveMovableOverride(itemSrc);
                    if (itemDst)
                        RemoveMovableOverride(itemDst);
                    return false; // cheater
                }
                if (!e.CanPerformEvent())
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CanPerformEvent", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                    }
                    #endif
                    syncDebugPrint("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT do cmd=HAND_EVENT e=" + e.DumpToString());
                    if (itemSrc)
                        RemoveMovableOverride(itemSrc);
                    if (itemDst)
                        RemoveMovableOverride(itemDst);
                    return false;
                }
                if (itemSrc)
                    RemoveMovableOverride(itemSrc);
                if (itemDst)
                    RemoveMovableOverride(itemDst);
                if (!handling_juncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                {
                    JunctureRequestResult result_ev = e.AcquireInventoryJunctureFromServer(GetDayZPlayerOwner());
                    if (result_ev == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture not required", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                        }
                        #endif
                        // ok, post event
                    }
                    else if (result_ev == JunctureRequestResult.JUNCTURE_ACQUIRED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture sended", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                        }
                        #endif
                        GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx); // ok, send juncture
                        if (itemSrc)
                            EnableMovableOverride(itemSrc);
                        if (itemDst)
                            EnableMovableOverride(itemDst);
                        break; // and do NOT perform post event
                    }
                    else if (result_ev == JunctureRequestResult.JUNCTURE_DENIED)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture denied", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                        }
                        #endif
                        return true; // abort, do not send anything to remotes
                    }
                    else
                    {
                        Error("[syncinv] HandleInputData: unexpected return code from AcquireInventoryJunctureFromServer"); return true;
                        return true; // abort, do not send anything to remotes
                    }
                }
                if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                    CheckForRope(e.GetSrc(), e.GetDst());
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("Success - ProcessHandEvent", "HAND_EVENT" , "n/a", "ProccessInputData", e.m_Player.ToString() );
                }
                #endif
                e.m_Player.GetHumanInventory().ProcessHandEvent(e);
                break;
            }
            case InventoryCommandType.SWAP:
            {
                InventoryLocation src1 = new InventoryLocation;
                InventoryLocation src2 = new InventoryLocation;
                InventoryLocation dst1 = new InventoryLocation;
                InventoryLocation dst2 = new InventoryLocation;
                bool skippedSwap = false;
                src1.ReadFromContext(ctx);
                src2.ReadFromContext(ctx);
                dst1.ReadFromContext(ctx);
                dst2.ReadFromContext(ctx);
                ctx.Read(skippedSwap);
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + "src1=" + InventoryLocation.DumpToStringNullSafe(src) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + "src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2), "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                }
                #endif
                if (remote && (!src1.GetItem() || !src2.GetItem()))
                {
                    if (skippedSwap)
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Remote - skipped", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        //syncDebugPrint("[syncinv] HandleInputData remote input (cmd=SWAP) dropped, swap is skipped");
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Failed - item1 or item2 not exist", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        Error("[syncinv] HandleInputData remote input (cmd=SWAP) dropped, item not in bubble");
                    }
                    break; // not in bubble
                }
                EnableMovableOverride(src1.GetItem());
                EnableMovableOverride(src2.GetItem());
                if (false == PlayerCheckRequestSrc(src1, GameInventory.c_MaxItemDistanceRadius))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequestSrc1", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src1 check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1));
                    RemoveMovableOverride(src1.GetItem());
                    RemoveMovableOverride(src2.GetItem());
                    return false; // stale packet
                }
                if (false == PlayerCheckRequestSrc(src2, GameInventory.c_MaxItemDistanceRadius))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckRequestSrc2", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src2 check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2));
                    RemoveMovableOverride(src1.GetItem());
                    RemoveMovableOverride(src2.GetItem());
                    return false; // stale packet
                }
                //Players should not try to determine whether some other player is cheater or not, this is up to that player and the server
                if ( IsServerOrLocalPlayer() && !PlayerCheckSwapItemsRequest(src1, src2, dst1, dst2, GameInventory.c_MaxItemDistanceRadius))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CheckSwapItemsRequest", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
                    RemoveMovableOverride(src1.GetItem());
                    RemoveMovableOverride(src2.GetItem());
                    return false; // cheater
                }
                RemoveMovableOverride(src1.GetItem());
                RemoveMovableOverride(src2.GetItem());
                if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
                {
                    ClearInventoryReservationEx(dst1.GetItem(), dst1);
                    ClearInventoryReservationEx(dst2.GetItem(), dst2);
                }
                if (false == GameInventory.CanForceSwapEntitiesEx(src1.GetItem(), dst1, src2.GetItem(), dst2))
                {
                    #ifdef DEVELOPER
                        DumpInventoryDebug();
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - CanForceSwapEntitiesEx", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    Error("[desync] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " CANNOT swap cmd=" + typename.EnumToString(InventoryCommandType, type) + " src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) +" | src2=" + InventoryLocation.DumpToStringNullSafe(src2) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
                    return false;
                }
                if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT)
                {
                    AddInventoryReservationEx(dst1.GetItem(), dst1, GameInventory.c_InventoryReservationTimeoutShortMS);
                    AddInventoryReservationEx(dst2.GetItem(), dst2, GameInventory.c_InventoryReservationTimeoutShortMS);
                }
                if (src1.IsValid() && src2.IsValid() && dst1.IsValid() && dst2.IsValid())
                {
                    if (!handling_juncture && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
                    {
                        JunctureRequestResult result_sw = TryAcquireTwoInventoryJuncturesFromServer(GetDayZPlayerOwner(), src1, src2, dst1, dst2);
                        if (result_sw == JunctureRequestResult.JUNCTURE_NOT_REQUIRED)
{
                            #ifdef DEVELOPER
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Juncture not required", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                            // ok, perform swap
                        }
                        else if (result_sw == JunctureRequestResult.JUNCTURE_ACQUIRED)
{
                            #ifdef DEVELOPER
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Juncture sended", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                            GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx); // ok, send juncture
                            EnableMovableOverride(src1.GetItem());
                            EnableMovableOverride(src2.GetItem());
                            break; // and do NOT perform swap
                        }
                        else if (result_sw == JunctureRequestResult.JUNCTURE_DENIED)
{
                            #ifdef DEVELOPER
                            if ( LogManager.IsInventoryMoveLogEnable() )
{
                                Debug.InventoryMoveLog("Juncture denied", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                            }
                            #endif
                            return true; // abort, do not send anything to remotes
                        }
                        else
{
                            Error("[syncinv] HandleInputData: unexpected return code from TryAcquireTwoInventoryJuncturesFromServer"); return true;
                            return true; // abort, do not send anything to remotes
                        }
                    }
                    if (GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
                    {
                        ClearInventoryReservationEx(dst1.GetItem(),dst1);
                        ClearInventoryReservationEx(dst2.GetItem(),dst2);
                    }
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Success - item swap", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    bool isNotSkipped = LocationSwap(src1, src2, dst1, dst2);
                    InventoryInputUserData.SerializeSwap(n_ctx, src1, src2, dst1, dst2, !isNotSkipped);
                    ctx = n_ctx;
                }
                else
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed - invalid input invetory locations", "SWAP" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    Error("HandleInputData: cmd=" + typename.EnumToString(InventoryCommandType, type) + " invalid input(s): src1=" + InventoryLocation.DumpToStringNullSafe(src1) + " src2=" + InventoryLocation.DumpToStringNullSafe(src2) +  " dst1=" + InventoryLocation.DumpToStringNullSafe(dst1) + " dst2=" + InventoryLocation.DumpToStringNullSafe(dst2));
                    return true; // abort, do not send anything to remotes
                }
                break;
            }
            case InventoryCommandType.FORCESWAP:
            {
                Error("[syncinv] DZPI.ForceSwap TODO");
                break;
            }
            case InventoryCommandType.DESTROY:
            {
                src.ReadFromContext(ctx);
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + "src=" + InventoryLocation.DumpToStringNullSafe(src), "DESTROY" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                }
                #endif
                if (remote && !src.GetItem())
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed item not exist", "DESTROY" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    Error("[syncinv] HandleInputData remote input (cmd=DESTROY) dropped, item not in bubble");
                    break; // not in bubble
                }
                if (!PlayerCheckRequestSrc(src, GameInventory.c_MaxItemDistanceRadius))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed CheckRequestSrc", "DESTROY" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " failed src check with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src));
                    return false; // stale packet
                }
                //Players should not try to determine whether some other player is cheater or not, this is up to that player and the server
                if ( IsServerOrLocalPlayer() && !PlayerCheckDropRequest(src, GameInventory.c_MaxItemDistanceRadius))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("Failed CheckDropRequest", "DESTROY" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    syncDebugPrint("[cheat] HandleInputData man=" + Object.GetDebugName(GetManOwner()) + " is cheating with cmd=" + typename.EnumToString(InventoryCommandType, type) + " src=" + InventoryLocation.DumpToStringNullSafe(src));
                    return false; // cheater
                }
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("Success ObjectDelete", "DESTROY" , "n/a", "ProccessInputData", GetDayZPlayerOwner().ToString() );
                }
                #endif
                GetGame().ObjectDelete(src.GetItem());
                break;
            }
        }
        StoreInputForRemotes(handling_juncture, remote, ctx);
        return true;
    }
References HandEventBase::AcquireInventoryJunctureFromServer(), AddInventoryReservationEx(), HandEventBase::CanPerformEvent(), CheckForRope(), HandEventBase::CheckRequest(), HandEventBase::CheckRequestSrc(), HandEventBase::ClearInventoryReservation(), ClearInventoryReservationEx(), InventoryLocation::CompareLocationOnly(), HandEventBase::DumpToString(), InventoryLocation::DumpToStringNullSafe(), EnableMovableOverride(), Error(), GetDayZPlayerOwner(), HandEventBase::GetDst(), GetGame(), GetInstanceType(), InventoryLocation::GetItem(), HandEventBase::GetSecondSrcEntity(), GetTime(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), IsServerOrLocalPlayer(), InventoryLocation::IsValid(), LocationSwap(), LocationSyncMoveEntity(), CGame::ObjectDelete(), PlayerCheckDropRequest(), PlayerCheckRequestDst(), PlayerCheckRequestSrc(), PlayerCheckSwapItemsRequest(), Serializer::Read(), InventoryLocation::ReadFromContext(), RemoveMovableOverride(), InventoryInputUserData::SerializeSwap(), DayZPlayerSyncJunctures::SJ_INVENTORY, DayZPlayerSyncJunctures::SJ_INVENTORY_REPAIR, StoreInputForRemotes(), syncDebugPrint(), ToString(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), and InventoryLocation::WriteToContext().
Referenced by HandleInputData().
RemoveMovableOverride()
void RemoveMovableOverride (EntityAI item)
Definition at line 1141 of file dayzplayerinventory.c.
    {
        ItemBase itemIB = ItemBase.Cast(item);
        if (itemIB)
            itemIB.SetCanBeMovedOverride(false);
    }
Referenced by ProccessInputData().
ReserveInventory()
override bool ReserveInventory (HumanInventory inventory)
Definition at line 22 of file dayzplayerinventory.c.
    {
        if( !inventory.AddInventoryReservationEx(m_dst.GetItem(), m_dst, GameInventory.c_InventoryReservationTimeoutShortMS) )
        {
            return false;
        }
        return true;
    }
References InventoryLocation::GetItem(), and m_dst.
SendServerHandEventViaJuncture()
static void SendServerHandEventViaJuncture (notnull DayZPlayer player, HandEventBase e) static
Definition at line 1558 of file dayzplayerinventory.c.
    {
        if (GetGame().IsServer())
        {
            if (e.IsServerSideOnly())
                Error("[syncinv] " + Object.GetDebugName(player) + " SendServerHandEventViaJuncture - called on server side event only, e=" + e.DumpToString());
            if (player.IsAlive())
            {
                InventoryLocation dst = e.GetDst();
                InventoryLocation src = e.GetSrc();
                if (src.IsValid() && dst.IsValid())
                {
                    if (player.NeedInventoryJunctureFromServer(src.GetItem(), src.GetParent(), dst.GetParent()))
                    {
                        syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") need juncture src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                        if (GetGame().AddInventoryJunctureEx(player, src.GetItem(), dst, true, GameInventory.c_InventoryReservationTimeoutMS))
                            syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") got juncture");
                        else
                            syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + ") !got juncture");
                    }
                    syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + " server hand event src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                    ScriptInputUserData ctx = new ScriptInputUserData;
                    InventoryInputUserData.SerializeHandEvent(ctx, e);
                    player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx);
                    syncDebugPrint("[syncinv] " + Object.GetDebugName(player) + " STS = " + player.GetSimulationTimeStamp() + " store input for remote - SendServerHandEventViaJuncture(" + typename.EnumToString(InventoryMode, InventoryMode.SERVER) + " server hand event src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                    player.StoreInputForRemotes(ctx); // @TODO: is this right place? maybe in HandleInputData(server=true, ...)
                }
            }
            else
            {
                Error("[syncinv] SendServerHandEventViaJuncture - called on dead player, juncture is for living only");
            }
        }
    }
References HandEventBase::DumpToString(), InventoryLocation::DumpToStringNullSafe(), Error(), HandEventBase::GetDst(), GetGame(), InventoryLocation::GetItem(), InventoryLocation::GetParent(), HandEventBase::IsServerSideOnly(), InventoryLocation::IsValid(), InventoryInputUserData::SerializeHandEvent(), DayZPlayerSyncJunctures::SJ_INVENTORY, and syncDebugPrint().
Referenced by HandleHandEvent().
StoreInputForRemotes()
bool StoreInputForRemotes (bool handling_juncture, bool remote, ParamsReadContext ctx)
Definition at line 1168 of file dayzplayerinventory.c.
    {
        if (!handling_juncture && !remote && GetDayZPlayerOwner().GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            #ifdef DEVELOPER
            if ( LogManager.IsInventoryMoveLogEnable() )
            {
                Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp(), "n/a" , "n/a", "StoreInputForRemotes", GetDayZPlayerOwner().ToString() );
            }
            #endif
            GetDayZPlayerOwner().StoreInputForRemotes(ctx); // @NOTE: needs to be called _after_ the operation
            return true;
        }
        return false;
    }
References GetDayZPlayerOwner(), GetInstanceType(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), and ToString().
StoreInputUserData()
proto native void StoreInputUserData (ParamsReadContext ctx)
Referenced by OnInputUserDataProcess().
StoreJunctureData()
proto native void StoreJunctureData (ParamsReadContext ctx)
Referenced by OnInventoryJunctureFromServer().
SwapEntities()
override bool SwapEntities (InventoryMode mode, notnull EntityAI item1, notnull EntityAI item2)
Definition at line 1357 of file dayzplayerinventory.c.
    {
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryMoveLogEnable() )
        {
            Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " item1 = " + item1 + " item2 = " + item2, "n/a" , "n/a", "SwapEntities", GetDayZPlayerOwner().ToString() );
        }
        #endif
        InventoryLocation src1, src2, dst1, dst2;
        if( mode == InventoryMode.LOCAL )
        {
            if (GameInventory.MakeSrcAndDstForSwap(item1, item2, src1, src2, dst1, dst2))
            {
                LocationSwap(src1, src2, dst1, dst2);
                return true;
            }
        }
        if(!super.SwapEntities(mode,item1,item2))
        {
            if(!m_DeferredEvent)
            {
                if( GameInventory.MakeSrcAndDstForSwap(item1, item2, src1, src2, dst1, dst2) );
                {
                    m_DeferredEvent = new DeferredSwapEntities(mode, item1, item2, dst1, dst2);
                    if( m_DeferredEvent.ReserveInventory(this) )
                        return true;
                }
            }
            m_DeferredEvent = null;
            return false;
        }
        return true;
    }
References GetDayZPlayerOwner(), Debug::InventoryMoveLog(), LogManager::IsInventoryMoveLogEnable(), LocationSwap(), m_DeferredEvent, and ToString().
SyncHandEventToRemote()
void SyncHandEventToRemote (HandEventBase e)
Definition at line 1681 of file dayzplayerinventory.c.
    {
        DayZPlayer p = GetDayZPlayerOwner();
        if (p && p.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER)
        {
            ScriptRemoteInputUserData ctx = new ScriptRemoteInputUserData;
            ctx.Write(INPUT_UDT_HAND_REMOTE_EVENT);
            e.WriteToContext(ctx);
            hndDebugPrint("[hndfsm] send 2 remote: sending e=" + e + " id=" + e.GetEventID() + " p=" + p + "  e=" + e.DumpToString());
            p.StoreInputForRemotes(ctx);
        }
    }
References HandEventBase::DumpToString(), GetDayZPlayerOwner(), hndDebugPrint(), INPUT_UDT_HAND_REMOTE_EVENT, Serializer::Write(), and HandEventBase::WriteToContext().
Referenced by HandleInventory().
TakeToDst()
override bool TakeToDst (InventoryMode mode, notnull InventoryLocation src, notnull InventoryLocation dst)
Definition at line 1184 of file dayzplayerinventory.c.
    {
        if (!GetManOwner().IsAlive())
            return super.TakeToDst(mode,src,dst);
        #ifdef DEVELOPER
        if ( LogManager.IsInventoryMoveLogEnable() )
        {
            Debug.InventoryMoveLog("STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + "src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "TakeToDst", GetDayZPlayerOwner().ToString() );
        }
        #endif
        switch ( mode )
        {
            case InventoryMode.SERVER:
                if (RedirectToHandEvent(mode, src, dst))
                {
                    #ifdef DEVELOPER
                    if ( LogManager.IsInventoryMoveLogEnable() )
                    {
                        Debug.InventoryMoveLog("RedirectToHandEvent", "n/a" , "n/a", "TakeToDst", GetDayZPlayerOwner().ToString() );
                    }
                    #endif
                    return true;
                }
                if (GetDayZPlayerOwner().NeedInventoryJunctureFromServer(src.GetItem(), src.GetParent(), dst.GetParent()))
                {
                    if (GetGame().AddInventoryJunctureEx(GetDayZPlayerOwner(), src.GetItem(), dst, true, GameInventory.c_InventoryReservationTimeoutMS))
                    {
                        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") got juncture");
                    }
                    else
                    {
                        #ifdef DEVELOPER
                        if ( LogManager.IsInventoryMoveLogEnable() )
{
                            Debug.InventoryMoveLog("Juncture failed", "n/a" , "n/a", "TakeToDst", GetDayZPlayerOwner().ToString() );
                        }
                        #endif
                        syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + ") got juncture");
                        return false;
                    }
                }
                ScriptInputUserData ctx = new ScriptInputUserData;
                InventoryInputUserData.SerializeMove(ctx, InventoryCommandType.SYNC_MOVE, src, dst);
                GetDayZPlayerOwner().SendSyncJuncture(DayZPlayerSyncJunctures.SJ_INVENTORY, ctx);
                syncDebugPrint("[syncinv] " + Object.GetDebugName(GetDayZPlayerOwner()) + " STS = " + GetDayZPlayerOwner().GetSimulationTimeStamp() + " store input for remote - DZPI::Take2Dst(" + typename.EnumToString(InventoryMode, mode) + " server sync move src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst));
                GetDayZPlayerOwner().StoreInputForRemotes(ctx); // @TODO: is this right place? maybe in HandleInputData(server=true, ...)
                #ifdef DEVELOPER
                if ( LogManager.IsInventoryMoveLogEnable() )
                {
                    Debug.InventoryMoveLog("Success - store input for remote mode - " + typename.EnumToString(InventoryMode, mode) + " src=" + InventoryLocation.DumpToStringNullSafe(src) + " dst=" + InventoryLocation.DumpToStringNullSafe(dst), "n/a" , "n/a", "TakeToDst", GetDayZPlayerOwner().ToString() );
                }
                #endif
                return true;
            case InventoryMode.LOCAL:
                LocationSyncMoveEntity(src, dst);
                return true;
        }
        if(!super.TakeToDst(mode,src,dst))
        {
            if (!m_DeferredEvent)
            {
                m_DeferredEvent = new DeferredTakeToDst(mode,src,dst);
                if( m_DeferredEvent.ReserveInventory(this) )
                    return true;
            }
            m_DeferredEvent = null;
            return false;
        }
        return true;
    }
References DeferredTakeToDst(), InventoryLocation::DumpToStringNullSafe(), GetDayZPlayerOwner(), GetGame(), Debug::InventoryMoveLog(), IsAlive(), LogManager::IsInventoryMoveLogEnable(), LocationSyncMoveEntity(), m_DeferredEvent, InventoryInputUserData::SerializeMove(), DayZPlayerSyncJunctures::SJ_INVENTORY, syncDebugPrint(), and ToString().
Variable Documentation
m_DeferredEvent
m_DeferredEvent = NULL
Referenced by ForceSwapEntities(), HandEvent(), HandleInventoryManipulation(), IsProcessing(), SwapEntities(), and TakeToDst().
m_DeferredPostedHandEvent
protected ref HandEventBase m_DeferredPostedHandEvent = NULL
Definition at line 142 of file dayzplayerinventory.c.
Referenced by CancelHandEvent(), and IsProcessing().
m_DeferredWeaponEvent
ref WeaponEventBase m_DeferredWeaponEvent = NULL
deferred hand event
Definition at line 143 of file dayzplayerinventory.c.
Referenced by CancelWeaponEvent(), DeferredWeaponFailed(), HandleWeaponEvents(), and PostWeaponEvent().
m_DeferredWeaponTimer
ref Timer m_DeferredWeaponTimer = new Timer
Definition at line 138 of file dayzplayerinventory.c.
Referenced by CancelWeaponEvent(), and HandleWeaponEvents().
m_dst
ref InventoryLocation m_dst
Definition at line 13 of file dayzplayerinventory.c.
Referenced by ClearInventoryReservation(), DeferredTakeToDst(), WeaponStateBase::LoadCurrentFSMState(), WeaponStateBase::OnAbort(), WeaponStateBase::OnEntry(), WeaponStateBase::OnExit(), WeaponEventBase::ReadFromContext(), ReserveInventory(), WeaponStateBase::SaveCurrentFSMState(), WeaponEventBase::WeaponEventDetachMagazine(), WeaponEventBase::WeaponEventSwapMagazine(), and WeaponEventBase::WriteToContext().
m_dst1
ref InventoryLocation m_dst1
Definition at line 78 of file dayzplayerinventory.c.
Referenced by DeferredForceSwapEntities().
m_dst2
ref InventoryLocation m_dst2
Definition at line 79 of file dayzplayerinventory.c.
Referenced by DeferredForceSwapEntities().
m_event
ref HandEventBase m_event
Definition at line 113 of file dayzplayerinventory.c.
Referenced by FSMTransition< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FSMTransition().
m_FSwapping
protected ref HandAnimatedForceSwapping m_FSwapping
Definition at line 148 of file dayzplayerinventory.c.
Referenced by Init().
m_FSwappingInst
protected ref HandAnimatedForceSwapping_Inst m_FSwappingInst
Definition at line 149 of file dayzplayerinventory.c.
Referenced by Init().
m_item1
DeferredSwapEntities m_item1
Referenced by DeferredForceSwapEntities().
m_item2
EntityAI m_item2
Definition at line 77 of file dayzplayerinventory.c.
Referenced by DeferredForceSwapEntities().
m_MovingTo
protected ref HandAnimatedMovingToAtt m_MovingTo
Definition at line 146 of file dayzplayerinventory.c.
Referenced by Init().
m_src
class DeferredEvent m_src
Referenced by DeferredTakeToDst().
m_Swapping
protected ref HandAnimatedSwapping m_Swapping
Definition at line 147 of file dayzplayerinventory.c.
Referenced by Init().
m_Taking
protected ref HandAnimatedTakingFromAtt m_Taking
deferred weapon event
Definition at line 145 of file dayzplayerinventory.c.
Referenced by Init().