DayzKode: P:/scripts/4_world/DayZ/entities/dayzplayerimplement.c File Reference
dayzplayerimplement.c File Reference
Classes
class DayZPlayerCommandDeathCallback
Functions
void AbortWeaponEvent ()
void AddNoise (NoiseParams noisePar, float noiseMultiplier=1.0)
override bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
-------------— aiming model ----------------------—
protected void AttenuateSoundIfNecessary (SoundObject soundObject)
override int CameraHandler (int pCameraMode)
-------------— camera handling ----------------------—
bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
bool CanConsumeStamina (EStaminaConsumers consumer)
Implementations only! - used on PlayerBase.
bool CanJump ()
bool CanPickupHeavyItem (notnull EntityAI item)
-------------— Checks if player can pick up heavy item ----------------------—
bool CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2)
bool CanStartConsumingStamina (EStaminaConsumers consumer)
void CheckAnimationOverrides ()
bool CheckForDropItem (EntityAI item)
bool CheckForRespawn (EntityAI item)
bool CheckForTakeItem (EntityAI item)
void CheckLiftWeapon ()
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
-------------— command handling ----------------------—
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool CommitedSuicide ()
void CompleteWeaponRaise ()
void DayZPlayerImplement ()
constructor
void DepleteStamina (EStaminaModifiers modifier, float dT=-1)
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
event from damage system
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
override void EEKilled (Object killer)
override protected void EOnContact (IEntity other, Contact extra)
bool EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody)
selects animation type and direction based on damage system data
bool EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir)
selects animation type and direction based on damage system data
void ExitSights ()
DayZPlayerImplementAiming GetAimingModel ()
AnimBackType GetBackAttachmentType ()
AnimUpperBodyType GetBodyAttachmentType ()
AnimBootsType GetBootsType ()
DayZPlayerInventory GetDayZPlayerInventory ()
DayZPlayerImplementMeleeCombat GetMeleeCombat ()
DayZPlayerMeleeFightLogic_LightHeavy GetMeleeFightLogic ()
AnimRangedWeaponType GetShoulderAttachmentType ()
float GetSlidePoseAngle ()
string GetSurfaceType (SurfaceAnimationBone limbType)
DayZPlayerImplementThrowing GetThrowing ()
int GetTypeOfDeath (int pCurrentCommandID)
WeaponManager GetWeaponManager ()
void HandleADS ()
bool HandleDamageHit (int pCurrentCommandID)
bool HandleDeath (int pCurrentCommandID)
void HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics)
void HandleView ()
void HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights)
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
void HideClothing (ItemOptics optic, bool state)
override bool IsEyeZoom ()
returns true if player is using EyeZoom, otherwise false
bool IsFBSymptomPlaying ()
bool IsFighting ()
bool IsFireWeaponRaised ()
bool IsHandheldOpticsInUse ()
bool IsInFBEmoteState ()
Checks if fullbody animation or specific locked state is active in emote manager.
bool IsInIronsights ()
bool IsInOptics ()
override bool IsInThirdPerson ()
return true if player is currently in 3pp, otherwise false
bool IsLiftWeapon ()
bool IsPlayerSelected ()
bool IsRaised ()
bool IsRestrained ()
override bool IsShootingFromCamera ()
return true if shots are fired from camere, otherwise false
bool IsSprintFull ()
bool IsTryingHoldBreath ()
bool IsWeaponRaiseCompleted ()
void LockControls (bool state)
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
override void OnInputForRemote (ParamsReadContext ctx)
override void OnInputFromServer (ParamsReadContext ctx)
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnInputUserDataReceived (ParamsReadContext ctx)
override void OnItemInHandsChanged ()
void OnJumpEnd (int pLandType=0)
void OnJumpStart ()
void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
void OnMovementChanged ()
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
void OnSoundEvent (string pEventType, string pUserString, int pUserInt)
void OnSprintEnd ()
void OnSprintStart ()
void OnStepEvent (string pEventType, string pUserString, int pUserInt)
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
void OverrideShootFromCamera (bool pState)
void OverrideSlidePoseAngle (float value)
movement sliding override, originally for FB gestures
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false)
bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system=false, bool is_from_server=false, int param=0)
void ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt)
void ProcessFeetDamageServer (int pUserInt)
void ProcessLiftWeapon ()
void ProcessSoundEvent (string pEventType, string pUserString, int pUserInt)
AbstractWave ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt)
void ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt)
void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client=false)
void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client=false, int param=0)
void ResetDeathStartTime ()
void RunADSTimer ()
void SendCompleteWeaponRaiseJuncture ()
void SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath)
protected void SendSoundEvent (EPlayerSoundEventID id)
protected void SendSoundEventEx (EPlayerSoundEventID id, int param=0)
void SetClimbingLadderType (string value)
void SetDeathDarknessLevel (float duration, float tick_time)
void SetFallYDiff (float value)
void SetHandheldOpticsInUse (bool state)
void SetIronsights (bool value)
void SetIsInThirdPerson (bool state)
void SetOptics (bool value)
void SetReturnToOptics (bool state)
DEPRECATED.
void SetSuicide (bool state)
void SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder)
void ShowDeadScreen (bool show, float duration)
void ShowWeaponDebug (bool show)
void SimulateDeath (bool state)
void StopADSTimer ()
override void StopDeathDarkeningEffect ()
void StopHandEvent ()
void StopWeaponEvent ()
void SwitchOptics (ItemOptics optic, bool state)
void ~DayZPlayerImplement ()
Variables
static const int DEAD_SCREEN_DELAY = 1000
static const float DEFAULT_DYING_TIME = 2.5
static const float DYING_PROGRESSION_TIME = 0.05
ref Timer m_ADSAutomationTimer
protected bool m_ADSTimerLaunched
protected bool m_AimingFinisherStarted = false
protected ref DayZPlayerImplementAiming m_AimingModel
protected bool m_bADS
protected bool m_Camera3rdPerson
protected bool m_CameraEyeZoom
protected bool m_CameraIronsight
protected bool m_CameraOptics
protected bool m_CameraZoomToggle
protected string m_ClimbingLadderType
protected bool m_ContinueFirearmMelee
float m_DamageHealth = 0.0
int m_DamageHitAnimType = -1.0
float m_DamageHitDir = 0.0
bool m_DamageHitFullbody = false
int m_DeathAnimType = -2
protected float m_DeathDarkeningCurrentTime
ref Timer m_DeathEffectTimer
float m_DeathHitDir = 0
bool m_DeathJuctureSent = false
static const float m_DeathSimulationTimeout = 10.0
float m_DeathStartTime = 0.0
float m_DebugDirectionVal = -180
VKOSTIK - tady dat 0 misto -1.
bool m_DebugTypeVal = false
string m_DebugWeaponChangeItem
int m_DebugWeaponChangeShowSlot
int m_DebugWeaponChangeStage = 0
protected ref DayZPlayerImplementFallDamage m_FallDamage
protected float m_FallYDiff
ref Timer m_FightEndBlendTimer
float m_fLastHeadingDiff = 0
protected bool m_HandheldOpticsInUse
bool m_isFBsymptomPlaying
protected bool m_IsFireWeaponRaised
protected bool m_IsRaised
protected bool m_IsShootingFromCamera
protected bool m_IsTryingHoldBreath
protected bool m_IsUnconscious
protected ref DayZPlayerImplementJumpClimb m_JumpClimb
int m_LastBackSoundTime
int m_LastBackSoundTime2
protected int m_LastCommandBeforeUnconscious
float m_LastHeadingAngle
float m_LastHeadingAngleBlock
float m_LastHeadingAngleBlock2
protected int m_LastSurfaceUnderHash
protected bool m_LiftWeapon_player
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat
protected ref DayZPlayerMeleeFightLogic_LightHeavy m_MeleeFightLogic
DayZPlayerCommandDeathCallback m_MovementState = new HumanMovementState()
cached ptr for movement state
protected SHumanCommandMoveSettings m_MoveSettings
protected int m_NextVoNNoiseTime
protected bool m_PlayerSelected
protected ref PlayerSoundEventHandler m_PlayerSoundEventHandler
protected bool m_ProcessFirearmMeleeHit
protected bool m_ProcessLiftWeapon
protected bool m_ProcessLiftWeaponState
protected bool m_ProcessWeaponRaiseCompleted
protected bool m_RaiseStarted = false
protected bool m_ResetADS
protected bool m_ShouldBeUnconscious
protected bool m_ShouldReload
float m_SoundOffset
protected float m_SprintedTime
protected bool m_SprintFull
protected int m_StepCounter
protected bool m_Suicide
protected ref DayZPlayerImplementSwimming m_Swimming
protected ref array< ref SyncHitInfo > m_SyncedHitDataArray
float m_TestDamageCounter = -1
protected ref DayZPlayerImplementThrowing m_Throwing
protected Transport m_TransportCache
bool m_UnconsciousDebug
protected bool m_WasIronsight
ref WeaponDebug m_WeaponDebug
protected bool m_WeaponRaiseCompleted
Function Documentation
AbortWeaponEvent()
void AbortWeaponEvent ()
Definition at line 1418 of file dayzplayerimplement.c.
    {
        GetDayZPlayerInventory().AbortWeaponEvent();
    }
References GetDayZPlayerInventory().
Referenced by ManBase::OnCommandClimbStart(), ManBase::OnCommandDeathStart(), ManBase::OnCommandFallStart(), ManBase::OnCommandMelee2Start(), ManBase::OnCommandSwimStart(), ManBase::OnJumpStart(), and ManBase::OnStanceChange().
AddNoise()
void AddNoise (NoiseParams noisePar, float noiseMultiplier = 1.0)
Definition at line 2785 of file dayzplayerimplement.c.
    {
            if(noisePar != NULL)
            GetGame().GetNoiseSystem().AddNoise(this, noisePar, noiseMultiplier);
    }
References NoiseSystem::AddNoise(), GetGame(), and CGame::GetNoiseSystem().
AimingModel()
override bool AimingModel (float pDt, SDayZPlayerAimingModel pModel)
-------------— aiming model ----------------------—
This Aiming Model
Definition at line 1301 of file dayzplayerimplement.c.
    {
        GetMovementState(m_MovementState);
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MELEE2 )
        {
            HumanCommandMelee2 hcm = GetCommand_Melee2();
            if( hcm.IsFinisher() )
            {
                if( !m_AimingFinisherStarted )
                {
                    m_AimingModel.OnFinisherBegin(pModel.m_fCurrentAimY);
                    m_AimingFinisherStarted = true;
                }
                m_AimingModel.ProcessStealthFilters(pDt, pModel);
            }
            return true;
        }
        if ( IsFireWeaponRaised() )
        {
            if ( !m_RaiseStarted )
            {
                m_AimingModel.OnRaiseBegin(this);
                m_RaiseStarted = true;
            }
            m_AimingModel.ProcessAimFilters( pDt, pModel, m_MovementState.m_iStanceIdx );
            return true;
        }
        m_RaiseStarted = false;
        m_AimingFinisherStarted = false;
        return true;
    }
References GetCommand_Melee2(), GetMovementState(), HumanCommandMelee2::IsFinisher(), IsFireWeaponRaised(), m_AimingFinisherStarted, m_AimingModel, SDayZPlayerAimingModel::m_fCurrentAimY, m_MovementState, m_RaiseStarted, DayZPlayerImplementAiming::OnFinisherBegin(), DayZPlayerImplementAiming::OnRaiseBegin(), DayZPlayerImplementAiming::ProcessAimFilters(), and DayZPlayerImplementAiming::ProcessStealthFilters().
AttenuateSoundIfNecessary()
protected void AttenuateSoundIfNecessary (SoundObject soundObject)
Definition at line 3347 of file dayzplayerimplement.c.
    {
        if (GetGame().GetPlayer() != NULL && (IsSoundInsideBuilding() != GetGame().GetPlayer().IsSoundInsideBuilding() || IsCameraInsideVehicle() != GetGame().GetPlayer().IsCameraInsideVehicle()))
        {
            soundObject.SetKind(WaveKind.WAVEATTALWAYS);
        }
        else
        {
            soundObject.SetKind(WaveKind.WAVEEFFECTEX);
        }
    }
References GetGame(), and GetPlayer().
Referenced by OnStepEvent(), ProcessAttachmentEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), and ProcessWeaponEvent().
CameraHandler()
override int CameraHandler (int pCameraMode)
-------------— camera handling ----------------------—
This is main camera selection logic
ironsights
get movement state
VKOSTIK: v ostatnich commandech mimo COMMANDID_MOVE je m_MovementState.m_iStanceIdx - DayZPlayerConstants.STANCEIDX_ERECT m_MovementState.m_iMovement = 0 (idle)
COMMANDID_ACTION returns stance right - ERECT/CROUCH
melee camera - not melee - stays in stance camera
Definition at line 2354 of file dayzplayerimplement.c.
    {
        // Print("DayZPlayerCfgBase: Camera Handler called");
        /* {
            int perItemCamUD = GetCurrentPerItemCameraUD();
            string      a   = "Per Item Camera User Data: " + ToString(perItemCamUD);
            Print(a);
        } */
        if (!m_LiftWeapon_player)
        {
            if (m_CameraIronsight)
            {
                if (m_CameraOptics)
                    return DayZPlayerCameras.DAYZCAMERA_OPTICS;
                else
                    return DayZPlayerCameras.DAYZCAMERA_IRONSIGHTS;
            }
            else if (m_CameraOptics)
                return DayZPlayerCameras.DAYZCAMERA_OPTICS;
        }
        //uncon
        if ( m_IsUnconscious )
        {
            return DayZPlayerCameras.DAYZCAMERA_1ST_UNCONSCIOUS;
        }
        HumanCommandVehicle vehicleCommand = GetCommand_Vehicle();
        if (!m_Camera3rdPerson)
        {
            if ( vehicleCommand )
            {
                return DayZPlayerCameras.DAYZCAMERA_1ST_VEHICLE;
            }
            return DayZPlayerCameras.DAYZCAMERA_1ST;
        }
        else
        {
            if ( vehicleCommand )
            {
                Transport transport = vehicleCommand.GetTransport();
                if (transport && GetParent())
                {
                    return transport.Get3rdPersonCameraType();
                }
            }
            GetMovementState(m_MovementState);
            if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CLIMB;
            }
            if ( m_JumpClimb.m_bIsJumpInProgress )
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_JUMP;
            }
            //
            // normal movement cameras
            if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CRO;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_CRO_RAISED;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_PRO;
            }
            else if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_PRO_RAISED;
            }
            if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
            {
                EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
                bool isWeapon       = entityInHands && entityInHands.IsInherited(Weapon);
                if (isWeapon)
                {
                    return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED;
                }
                else
                {
                    return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_RAISED_MELEE;
                }
            }
            else if (m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
            {
                return DayZPlayerCameras.DAYZCAMERA_3RD_ERC_SPR;
            }
            // DayZPlayerConstants.STANCEIDX_ERECT
            return DayZPlayerCameras.DAYZCAMERA_3RD_ERC;
        }
        return DayZPlayerCameras.DAYZCAMERA_1ST;
    }
References DayZPlayerCameras::DAYZCAMERA_1ST, DayZPlayerCameras::DAYZCAMERA_1ST_UNCONSCIOUS, DayZPlayerCameras::DAYZCAMERA_1ST_VEHICLE, DayZPlayerCameras::DAYZCAMERA_3RD_CLIMB, DayZPlayerCameras::DAYZCAMERA_3RD_CRO, DayZPlayerCameras::DAYZCAMERA_3RD_CRO_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_RAISED_MELEE, DayZPlayerCameras::DAYZCAMERA_3RD_ERC_SPR, DayZPlayerCameras::DAYZCAMERA_3RD_JUMP, DayZPlayerCameras::DAYZCAMERA_3RD_PRO, DayZPlayerCameras::DAYZCAMERA_3RD_PRO_RAISED, DayZPlayerCameras::DAYZCAMERA_IRONSIGHTS, DayZPlayerCameras::DAYZCAMERA_OPTICS, GetCommand_Vehicle(), GetMovementState(), GetParent(), HumanCommandVehicle::GetTransport(), DayZPlayerImplementJumpClimb::m_bIsJumpInProgress, m_Camera3rdPerson, m_CameraIronsight, m_CameraOptics, m_IsUnconscious, m_JumpClimb, m_LiftWeapon_player, and m_MovementState.
CanClimb()
bool CanClimb (int climbType, SHumanCommandClimbResult climbRes)
Definition at line 1368 of file dayzplayerimplement.c.
    {
        if ( IsFBSymptomPlaying() || IsRestrained() || IsUnconscious() || IsInFBEmoteState() )
            return false;
        if ( m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            return false;
        if (IsRaised() && GetInputInterface().SyncedPress("UAGetOverControllerHelper")) //no raised climb on cotroller
        {
            return false;
        }
        HumanItemBehaviorCfg hibcfg = GetItemAccessor().GetItemInHandsBehaviourCfg();
        if ( !hibcfg.m_bJumpAllowed )
            return false;
        if (climbRes)
        {
            EntityAI entity;
            if (Class.CastTo(entity,climbRes.m_GrabPointParent) && entity.IsHologram())
                return false;
            if (Class.CastTo(entity,climbRes.m_ClimbStandPointParent) && entity.IsHologram())
                return false;
            if (Class.CastTo(entity,climbRes.m_ClimbOverStandPointParent) && entity.IsHologram())
                return false;
        }
        return true;
    }
References Class::CastTo(), GetItemAccessor(), IsFBSymptomPlaying(), IsInFBEmoteState(), IsRaised(), IsRestrained(), HumanItemBehaviorCfg::m_bJumpAllowed, and m_MovementState.
CanConsumeStamina()
bool CanConsumeStamina (EStaminaConsumers consumer)
Implementations only! - used on PlayerBase.
Definition at line 341 of file dayzplayerimplement.c.
{};
Referenced by ManBase::CanClimb(), ManBase::CanJump(), ManBase::CanRoll(), ManBase::CommandHandler(), and ManBase::ProcessHoldBreath().
CanJump()
bool CanJump ()
Jump
Definition at line 1345 of file dayzplayerimplement.c.
    {
        if ( IsFBSymptomPlaying() || IsRestrained() || IsUnconscious() || IsInFBEmoteState() )
            return false;
        if ( m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            return false;
        if (IsRaised() && GetInputInterface().SyncedPress("UAGetOverControllerHelper")) //no raised jump on cotroller
        {
            return false;
        }
        HumanItemBehaviorCfg hibcfg = GetItemAccessor().GetItemInHandsBehaviourCfg();
        if ( !hibcfg.m_bJumpAllowed )
            return false;
        if ( !DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_ERECT) || !DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_RAISEDERECT) )
            return false;
        return true;
    }
References GetItemAccessor(), IsFBSymptomPlaying(), IsInFBEmoteState(), IsRaised(), IsRestrained(), HumanItemBehaviorCfg::m_bJumpAllowed, m_MovementState, and DayZPlayerUtils::PlayerCanChangeStance().
CanPickupHeavyItem()
bool CanPickupHeavyItem (notnull EntityAI item)
-------------— Checks if player can pick up heavy item ----------------------—
Definition at line 3382 of file dayzplayerimplement.c.
    {
        return !item.IsHeavyBehaviour() || (item.IsHeavyBehaviour() && DayZPlayerUtils.PlayerCanChangeStance(this, DayZPlayerConstants.STANCEIDX_ERECT));
    }
References DayZPlayerUtils::PlayerCanChangeStance().
Referenced by CanPickupHeavyItemSwap(), and ManBase::CanReceiveItemIntoHands().
CanPickupHeavyItemSwap()
bool CanPickupHeavyItemSwap (notnull EntityAI item1, notnull EntityAI item2)
Definition at line 3387 of file dayzplayerimplement.c.
    {
        return CanPickupHeavyItem(item1) && CanPickupHeavyItem(item2);
    }
References CanPickupHeavyItem().
CanStartConsumingStamina()
bool CanStartConsumingStamina (EStaminaConsumers consumer)
Definition at line 342 of file dayzplayerimplement.c.
{};
Referenced by ManBase::ProcessHoldBreath().
CheckAnimationOverrides()
void CheckAnimationOverrides ()
Definition at line 3297 of file dayzplayerimplement.c.
    {
    }
CheckForDropItem()
bool CheckForDropItem (EntityAI item)
Definition at line 3226 of file dayzplayerimplement.c.
    {
        /*
        bool restrained = IsRestrained(); // IsRestrained()
        bool unconscious = IsUnconscious(); // IsRestrained()
        ItemBase ib = ItemBase.Cast(item);
        if (!IsAlive() || restrained || unconscious || ib.CanBeMovedOverride())
            return true;
        return false;
        */
        return CheckForTakeItem(item); //the two functions are currently identical
    }
References CheckForTakeItem().
CheckForRespawn()
bool CheckForRespawn (EntityAI item)
Player respawn
Definition at line 3244 of file dayzplayerimplement.c.
    {
        PlayerBase player = PlayerBase.Cast(this);
        if (!player)
            return true;
        if (!IsAlive() || player.IsUnconscious())
            return true;
        return false;
    }
References IsAlive().
CheckForTakeItem()
bool CheckForTakeItem (EntityAI item)
anti-cheat condition
Definition at line 3215 of file dayzplayerimplement.c.
    {
        bool restrained = IsRestrained(); // IsRestrained()
        bool unconscious = IsUnconscious(); // IsRestrained()
        ItemBase ib = ItemBase.Cast(item);
        if (ib && (PlayerBase.DEBUG_INVENTORY_ACCESS || !IsAlive() || restrained || unconscious || ib.CanBeMovedOverride()))
            return true;
        return false;
    }
References IsAlive(), and IsRestrained().
Referenced by CheckForDropItem().
CheckLiftWeapon()
void CheckLiftWeapon ()
Definition at line 3359 of file dayzplayerimplement.c.
{};
Referenced by HandleWeapons().
CommandHandler()
override void CommandHandler (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
-------------— command handling ----------------------—
This is main command logic
handle weapon mode switch
handle all Camera changes, switch + zoom
handle death with high priority
handle finished commands
default behaviou after finish is to start move
debug test script command !PSOVIS
Sprint attack limiting - player has to be in full sprint for at least 0.5s
throwing handling
melee
Definition at line 1817 of file dayzplayerimplement.c.
    {
        if (ModCommandHandlerBefore(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
        HumanInputController hic = GetInputController();
        EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
        bool isWeapon       = entityInHands && entityInHands.IsInherited(Weapon);
        GetMovementState(m_MovementState);
        bool isRaisedNow = m_MovementState.IsRaised();
        if( isRaisedNow != m_IsRaised )
        {
            if( isRaisedNow && isWeapon )
                GetUApi().ActivateModificator("aiming");
            else
                GetUApi().DeactivateModificator("aiming");
            m_IsRaised = m_MovementState.IsRaised();
        }
        HandleADS();
        // handle weapons
        if (hic)
        {
            ItemOptics opticInHands = ItemOptics.Cast(entityInHands);
            if (isWeapon && (!m_ProcessFirearmMeleeHit || !m_ContinueFirearmMelee))
            {
                m_ProcessFirearmMeleeHit = false;
                bool exitIronSights = false;
                HandleWeapons(pDt, entityInHands, hic, exitIronSights);
            }
            else if (m_HandheldOpticsInUse && m_CameraOptics && opticInHands)
            {
                bool exitOptic = false;
                HandleOptic(opticInHands, true, hic, exitOptic);
            }
        }
        HandleView();
        GetMovementState(m_MovementState);
        if ( m_MovementState.m_iMovement != m_MovementState.m_LocalMovement )
        {
            OnMovementChanged();
            m_MovementState.m_LocalMovement = m_MovementState.m_iMovement;
        }
        if (HandleDeath(pCurrentCommandID))
        {
            return;
        }
        if (pCurrentCommandFinished)
        {
            if ( pCurrentCommandID == DayZPlayerConstants.COMMANDID_UNCONSCIOUS)
            {
                if ( (m_LastCommandBeforeUnconscious == DayZPlayerConstants.COMMANDID_VEHICLE) && (m_TransportCache != null))
                {
                    int crew_index = m_TransportCache.CrewMemberIndex(this);
                    int seat = m_TransportCache.GetSeatAnimationType(crew_index);
                    StartCommand_Vehicle(m_TransportCache, crew_index, seat, true);
                    m_TransportCache = null;
                    return;
                }
            }
            // start moving
            // start falling ? (could happen after climbing)
            if (PhysicsIsFalling(true))
            {
                StartCommand_Fall(0);
                m_FallYDiff = GetPosition()[1];
                return;
            }
            if ( m_Swimming.m_bWasSwimming )
            {
                StartCommand_Swim();
                return;
            }
            StartCommand_Move();
            if ( GetHumanInventory().GetEntityInHands() )
                ForceStandUpForHeavyItems( GetHumanInventory().GetEntityInHands() );
            return;
        }
        //--------------------------------------------
        if (ModCommandHandlerInside(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
        //--------------------------------------------
        // vehicle handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_VEHICLE)
        {
            HumanCommandVehicle hcv = GetCommand_Vehicle();
            if ( hcv.WasGearChange() )
            {
                GearChangeActionCallback cb = GearChangeActionCallback.Cast(AddCommandModifier_Action(DayZPlayerConstants.CMD_ACTIONMOD_SHIFTGEAR, GearChangeActionCallback));
                cb.SetVehicleCommand(hcv);
            }
            return;
        }
        //--------------------------------------------
        HumanCommandMove hcm = GetCommand_Move();
        if (hcm && hcm.GetCurrentMovementSpeed() > 2.99 && m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
        {
            m_SprintedTime += pDt;
            if ( m_SprintedTime > 0.5)
                m_SprintFull = true;
            else
                m_SprintFull = false;
        }
        else
        {
            m_SprintedTime = 0.0;
            m_SprintFull = false;
        }
        //--------------------------------------------
        // swimming handling
        if (m_Swimming.HandleSwimming(pCurrentCommandID, hcm, m_MovementState))
        {
            m_JumpClimb.CheckAndFinishJump();
            return;
        }
        //--------------------------------------------
        // ladder handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_LADDER)
        {
            OnLadder(pDt, m_MovementState);
            return;
        }
        //--------------------------------------------
        // climb handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_CLIMB)
        {
            return;
        }
        //--------------------------------------------
        // fall handling
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_FALL)
        {
            // vector   vel;
            // PhysicsGetVelocity(vel);
            // Print(vel);
            int landType = 0;
            HumanCommandFall fall = GetCommand_Fall();
            if (fall.PhysicsLanded())
            {
                DayZPlayerType type = GetDayZPlayerType();
                NoiseParams npar;
                // land
                m_FallYDiff = m_FallYDiff - GetPosition()[1];
                if (m_FallYDiff < 0.5)
                {
                    landType = HumanCommandFall.LANDTYPE_NONE;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandLight();
                    AddNoise(npar);
                }
                else if (m_FallYDiff < 1.0)
                {
                    if (m_MovementState.IsInProne() || m_MovementState.IsInRaisedProne())
                        landType = HumanCommandFall.LANDTYPE_NONE;
                    else
                        landType = HumanCommandFall.LANDTYPE_LIGHT;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandLight();
                    AddNoise(npar);
                }
                else if (m_FallYDiff < 2.0)
                {
                    landType = HumanCommandFall.LANDTYPE_MEDIUM;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandHeavy();
                    AddNoise(npar);
                }
                else
                {
                    landType = HumanCommandFall.LANDTYPE_HEAVY;
                    fall.Land(landType);
                    npar = type.GetNoiseParamsLandHeavy();
                    AddNoise(npar);
                }
                if ( m_FallYDiff >= DayZPlayerImplementFallDamage.FD_DMG_FROM_HEIGHT && GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
                {
                    OnPlayerRecievedHit();
                }
                m_FallDamage.HandleFallDamage(m_FallYDiff);
                m_JumpClimb.CheckAndFinishJump(landType);
            }
            return;
        }
        // start falling ?
        if (PhysicsIsFalling(false))
        {
            StartCommand_Fall(0);
            m_FallYDiff = GetPosition()[1];
            return;
        }
        //--------------------------------------------
        // damage hits -> move to player base
        //if (HandleDamageHit(pCurrentCommandID))
        //{
        //  return;
        //}
        //--------------------------------------------
        // handle jumping
#ifndef NO_GUI
#ifdef DEVELOPER
        if (DiagMenu.GetValue(DayZPlayerConstants.DEBUG_ENABLEJUMP))
        {
            SHumanCommandClimbSettings hcls = GetDayZPlayerType().CommandClimbSettingsW();
            if ( m_MovementState.m_iMovement != DayZPlayerConstants.MOVEMENTIDX_IDLE )
                hcls.m_fFwMaxDistance = 3;
            else
                hcls.m_fFwMaxDistance = 1.2;
            SHumanCommandClimbResult    ret;
            HumanCommandClimb.DoClimbTest(this, ret, 0x3);
        }
#endif
#endif
        // start jump
        if (hic.IsJumpClimb())
        {
            m_JumpClimb.JumpOrClimb();
            return;
        }
        HumanCommandAdditives ad = GetCommandModifier_Additives();
        bool force = false;
#ifndef NO_GUI
#ifdef DEVELOPER
        force = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_ENABLETALKING);
#endif
#endif
        float amplitude = IsPlayerSpeaking();
        if ( amplitude > 0.1 || force )
        {
            if ( ad )
                ad.SetTalking(true);
            // add noises on server
            if ( GetGame().IsServer() )
            {
                int now = GetGame().GetTime();
                if ( now >= m_NextVoNNoiseTime )
                {
                    m_NextVoNNoiseTime = now + 1000;
                    int voiceLevel = GetGame().GetVoiceLevel(this);
                    DayZPlayerType pt = GetDayZPlayerType();
                    // add noise every second while talking
                    NoiseParams vonpar;
                    switch ( voiceLevel )
                    {
                        case VoiceLevelWhisper:
                            vonpar = pt.GetNoiseParamsWhisper();
                        break;
                        case VoiceLevelTalk:
                            vonpar = pt.GetNoiseParamsTalk();
                        break;
                        case VoiceLevelShout:
                            vonpar = pt.GetNoiseParamsShout();
                        break;
                    }
                    AddNoise(vonpar);
                }
            }
        }
        else
        {
            if ( ad )
                ad.SetTalking(false);
        }
        //--------------------------------------------
        // anything whats handled by InputController
        if (hic)
        {
            HumanCommandWeapons hcw = GetCommandModifier_Weapons();
            m_Throwing.HandleThrowing(hic, hcw, entityInHands, pDt);
            if (m_MeleeFightLogic.HandleFightLogic(pCurrentCommandID, hic, entityInHands, m_MovementState, m_ContinueFirearmMelee))
            {
                m_ProcessFirearmMeleeHit = isWeapon && (hic.IsMeleeWeaponAttack() || m_ProcessFirearmMeleeHit) || m_ContinueFirearmMelee;
                return;
            }
        }
        if (ModCommandHandlerAfter(pDt, pCurrentCommandID, pCurrentCommandFinished))
        {
            return;
        }
    }
References UAInputAPI::ActivateModificator(), AddCommandModifier_Action(), AddNoise(), DayZPlayerImplementJumpClimb::CheckAndFinishJump(), DayZPlayerType(), UAInputAPI::DeactivateModificator(), HumanCommandClimb::DoClimbTest(), DayZPlayerImplementFallDamage::FD_DMG_FROM_HEIGHT, ForceStandUpForHeavyItems(), GetCommand_Fall(), GetCommand_Move(), GetCommand_Vehicle(), GetCommandModifier_Additives(), GetCommandModifier_Weapons(), HumanCommandMove::GetCurrentMovementSpeed(), GetDayZPlayerType(), GetGame(), GetInputController(), GetInstanceType(), GetMovementState(), GetPosition, CGame::GetTime(), GetUApi(), DiagMenu::GetValue(), CGame::GetVoiceLevel(), HandleADS(), HandleDeath(), DayZPlayerImplementFallDamage::HandleFallDamage(), HandleOptic(), DayZPlayerImplementSwimming::HandleSwimming(), DayZPlayerImplementThrowing::HandleThrowing(), HandleView(), HandleWeapons(), HumanCommandAdditives(), HumanCommandFall(), HumanInputController::IsJumpClimb(), HumanInputController::IsMeleeWeaponAttack(), IsPlayerSpeaking(), DayZPlayerImplementJumpClimb::JumpOrClimb(), DayZPlayerImplementSwimming::m_bWasSwimming, m_CameraOptics, m_ContinueFirearmMelee, m_FallDamage, m_FallYDiff, m_HandheldOpticsInUse, m_IsRaised, m_JumpClimb, m_LastCommandBeforeUnconscious, m_MeleeFightLogic, m_MovementState, m_NextVoNNoiseTime, m_ProcessFirearmMeleeHit, m_SprintedTime, m_SprintFull, m_Swimming, m_Throwing, m_TransportCache, ModCommandHandlerAfter(), ModCommandHandlerBefore(), ModCommandHandlerInside(), NoiseParams(), OnLadder(), OnMovementChanged(), OnPlayerRecievedHit(), PhysicsIsFalling(), GearChangeActionCallback::SetVehicleCommand(), SHumanCommandClimbSettings(), StartCommand_Fall(), StartCommand_Move(), StartCommand_Swim(), StartCommand_Vehicle(), and HumanCommandVehicle::WasGearChange().
CommandHandlerDebug()
void CommandHandlerDebug (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
debug handling of adding commands
set item in hands
fuj
start show
damage test
Definition at line 2184 of file dayzplayerimplement.c.
    {
        /*
        // debug - print ironsights pos / dir
        HumanItemAccessor hia = GetItemAccessor();
        vector pos, dir;
        if (hia.WeaponGetCameraPoint(pos, dir))
        {
            string  a = "ITACC: ";
            a += pos.ToString();
            a += " ";
            a += dir.ToString();
        //Print("DayZPlayerImplement: Init");
            Print(a);
        }
        */
        /* {
            HumanCommandMove mc = GetCommand_Move();
            if (mc)
            {
                float gcms = mc.GetCurrentMovementSpeed();
                Print(gcms);
            }
        } */
        if (GetPluginManager())
        {
            PluginDayzPlayerDebug playerDebug = PluginDayzPlayerDebug.Cast(GetPluginManager().GetPluginByType(PluginDayzPlayerDebug));
            if (playerDebug)
            {
                playerDebug.CommandHandler();
                if (m_DebugWeaponChangeStage == 0)
                {
                    // debug weapon change
                    int         hideSlot;
                    if (playerDebug.IsWeaponChange(m_DebugWeaponChangeItem, hideSlot, m_DebugWeaponChangeShowSlot))
                    {
                        Print("Change Weapon started: " + m_DebugWeaponChangeItem + "," + hideSlot.ToString() + "," + m_DebugWeaponChangeShowSlot.ToString());
                        HumanCommandWeapons w = GetCommandModifier_Weapons();
                        w.StartAction(WeaponActions.HIDE, hideSlot);
                        m_DebugWeaponChangeStage = 1;
                    }
                }
                else if (m_DebugWeaponChangeStage == 1)
                {
                    // wait for weapon hide to meet event
                    HumanCommandWeapons w2 = GetCommandModifier_Weapons();
                    if (w2 && w2.GetRunningAction() == WeaponActions.HIDE)
                    {
                        if (w2.IsEvent() == WeaponEvents.CHANGE_HIDE)
{
                            Print("Change Weapon - hidden: ");
                            PlayerBase player = PlayerBase.Cast(this);
                            EntityAI item_in_hands = player.GetHumanInventory().GetEntityInHands();
                            if (item_in_hands != NULL && player.CanDropEntity(item_in_hands) && GetGame().GetPlayer().GetHumanInventory().CanRemoveEntityInHands())
{
                                player.PredictiveDropEntity(item_in_hands);
                            }
                            if (m_DebugWeaponChangeItem != "")
{
                                InventoryLocation dst = new InventoryLocation;
                                dst.SetHands(this, NULL);
                                EntityAI item = GetGame().SpawnEntity(m_DebugWeaponChangeItem, dst,ECE_IN_INVENTORY,RF_DEFAULT);
                            }
                            w2.StartAction(WeaponActions.SHOW, 3);
                            m_DebugWeaponChangeStage = 2;
                        }
                    }
                }
                else if (m_DebugWeaponChangeStage == 2)
                {
                    HumanCommandWeapons w3 = GetCommandModifier_Weapons();
                    if (w3 && w3.IsActionFinished())
                    {
                        m_DebugWeaponChangeStage = 0;
                    }
                }
            }
        }
        if (m_TestDamageCounter >= 0)
        {
            if (m_TestDamageCounter > 3)
            {
                m_DebugDirectionVal = m_DebugDirectionVal + 90;
                m_TestDamageCounter = 0;
                if (m_DebugDirectionVal > 90)
                {
                    m_DebugDirectionVal = -180;
                    m_DebugTypeVal      = !m_DebugTypeVal;
                }
                if (m_DebugTypeVal)
                {
                    AddCommandModifier_Damage(0, m_DebugDirectionVal); // starts light
                }
                else
                {
                    StartCommand_Damage(0, m_DebugDirectionVal); // starts heavy (full body)
                }
                // 0.. types
                // from: -180 back, -90 left, 0 front, 90 right, 180 back
                //AddCommandModifier_Damage(0, directionVal); // starts light
                //StartCommand_Damage(0, 0); // starts heavy (full body)
            }
            m_TestDamageCounter += pDt;
        }
#ifndef NO_GUI
#ifdef DEVELOPER
        // injury / exhaustion
        {
            HumanCommandAdditives ad = GetCommandModifier_Additives();
            float v = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_SHOWINJURY);
            if (v > 0)
            {
                v = (v - 1.0) * 0.1;
                ad.SetInjured(v, true);
            }
            v = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_SHOWEXHAUSTION);
            if (v > 0)
            {
                v = (v - 1) * 0.1;
                ad.SetExhaustion(v, true);
            }
        }
#endif
#endif
    }
References AddCommandModifier_Damage(), ECE_IN_INVENTORY, GetCommandModifier_Additives(), GetCommandModifier_Weapons(), GetGame(), GetPlayer(), GetPluginManager(), HumanCommandWeapons::GetRunningAction(), DiagMenu::GetValue(), HumanCommandAdditives(), HumanCommandWeapons::IsActionFinished(), HumanCommandWeapons::IsEvent(), m_DebugDirectionVal, m_DebugTypeVal, m_DebugWeaponChangeItem, m_DebugWeaponChangeShowSlot, m_DebugWeaponChangeStage, m_TestDamageCounter, PluginDayzPlayerDebug(), Print(), RF_DEFAULT, InventoryLocation::SetHands(), HumanCommandWeapons::StartAction(), StartCommand_Damage(), and string::ToString().
CommitedSuicide()
bool CommitedSuicide ()
Definition at line 3316 of file dayzplayerimplement.c.
    {
        return m_Suicide;
    }
References m_Suicide.
CompleteWeaponRaise()
void CompleteWeaponRaise ()
Definition at line 617 of file dayzplayerimplement.c.
    {
        m_WeaponRaiseCompleted = true;
        StopADSTimer();
    }
References m_WeaponRaiseCompleted, and StopADSTimer().
Referenced by HandleWeapons().
DayZPlayerImplement()
void DayZPlayerImplement ()
constructor
Definition at line 126 of file dayzplayerimplement.c.
    {
        //Print("DayZPlayerImplement: Init");
        m_IsFireWeaponRaised = false;
        m_SprintFull = false;
        m_SprintedTime = 0;
        m_AimingModel = new DayZPlayerImplementAiming(this);
        m_MeleeCombat = new DayZPlayerImplementMeleeCombat(this);
        m_MeleeFightLogic = new DayZPlayerMeleeFightLogic_LightHeavy(this);
        m_Swimming = new DayZPlayerImplementSwimming(this);
        m_Throwing = new DayZPlayerImplementThrowing(this);
        m_JumpClimb = new DayZPlayerImplementJumpClimb(this);
        m_FallDamage = new DayZPlayerImplementFallDamage(this);
        m_ADSAutomationTimer = new Timer();
        m_bADS = false;
        m_WeaponRaiseCompleted = false;
        m_CameraEyeZoom = false;
        SetOptics(false);
        m_IsShootingFromCamera = true;
        m_ProcessFirearmMeleeHit = false;
        m_ContinueFirearmMelee = false;
        m_WasIronsight = true; //initially uses ironsights by default
        #ifdef PLATFORM_CONSOLE
        m_Camera3rdPerson = !GetGame().GetWorld().Is3rdPersonDisabled();
        #endif
        m_LastSurfaceUnderHash = ("cp_gravel").Hash();
        m_NextVoNNoiseTime = 0;
        m_SyncedHitDataArray = new array<ref SyncHitInfo>;
    }
References DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), GetGame(), CGame::GetWorld(), World::Is3rdPersonDisabled(), m_ADSAutomationTimer, m_AimingModel, m_bADS, m_Camera3rdPerson, m_CameraEyeZoom, m_ContinueFirearmMelee, m_FallDamage, m_IsFireWeaponRaised, m_IsShootingFromCamera, m_JumpClimb, m_LastSurfaceUnderHash, m_MeleeCombat, m_MeleeFightLogic, m_NextVoNNoiseTime, m_ProcessFirearmMeleeHit, m_SprintedTime, m_SprintFull, m_Swimming, m_SyncedHitDataArray, m_Throwing, m_WasIronsight, m_WeaponRaiseCompleted, and SetOptics().
DepleteStamina()
void DepleteStamina (EStaminaModifiers modifier, float dT = -1)
Definition at line 343 of file dayzplayerimplement.c.
{};
EEHitBy()
override void EEHitBy (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
event from damage system
Definition at line 1150 of file dayzplayerimplement.c.
    {
        super.EEHitBy(damageResult, damageType, source, component, dmgZone, ammo, modelPos, speedCoef);
        m_TransportHitRegistered = false;
        if ( !IsAlive() )
        {
            int animTypeDeath;
            float animHitDirDeath;
            if (EvaluateDeathAnimation(damageType, source, ammo, animTypeDeath, animHitDirDeath))
            {
                SendDeathJuncture(animTypeDeath, animHitDirDeath);
            }
            dBodySetInteractionLayer(this, PhxInteractionLayers.RAGDOLL);
            if ( !m_DeathSyncSent ) //checked until the death is evaluated by 'OnCommandHandlerTick' higher up the road
            {
                Man killer = source.GetHierarchyRootPlayer();
                if ( !m_KillerData ) //only one player is considered killer in the event of crossfire
                {
                    m_KillerData = new KillerData;
                    m_KillerData.m_Killer = killer;
                    m_KillerData.m_MurderWeapon = source;
                }
                if ( killer && killer.IsPlayer() )
                {
                    // was player killed by headshot?
                    if ( dmgZone == "Brain" )
                    {
                        m_KilledByHeadshot = true;
                        if (m_KillerData.m_Killer == killer)
                            m_KillerData.m_KillerHiTheBrain = true;
                    }
                }
            }
        }
        else
        {
            int animType;
            float animHitDir;
            bool animHitFullbody;
            if (EvaluateDamageHitAnimation(damageResult, damageType, source, dmgZone, ammo, modelPos, animType, animHitDir, animHitFullbody))
            {
                DayZPlayerSyncJunctures.SendDamageHitEx(this, animType, animHitDir, animHitFullbody, damageResult, damageType, source, dmgZone, ammo, modelPos);
            }
            else
            {
                RequestSoundEvent(EPlayerSoundEventID.TAKING_DMG_LIGHT);
                //add code here
            }
        }
        // interupt melee for non-blocked hit or heavy hit
        if (animHitFullbody)
        {
            HumanCommandMelee2 hcm = GetCommand_Melee2();
            if(hcm) hcm.Cancel();
        }
    }
References HumanCommandMelee2::Cancel(), component, dBodySetInteractionLayer(), EvaluateDamageHitAnimation(), EvaluateDeathAnimation(), GetCommand_Melee2(), IsAlive(), KillerData::m_Killer, RequestSoundEvent(), DayZPlayerSyncJunctures::SendDamageHitEx(), and SendDeathJuncture().
EEHitByRemote()
override void EEHitByRemote (int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos)
Definition at line 1213 of file dayzplayerimplement.c.
    {
        super.EEHitByRemote(damageType, source, component, dmgZone, ammo, modelPos);
        //Print("DayZPlayerImplement : EEHitByRemote");
    }
References component.
EEKilled()
override void EEKilled (Object killer)
Definition at line 454 of file dayzplayerimplement.c.
    {
        SendDeathJuncture(-1, 0);
        super.EEKilled(killer);
    }
References SendDeathJuncture().
EOnContact()
override protected void EOnContact (IEntity other, Contact extra)
Phx contact event
Definition at line 3329 of file dayzplayerimplement.c.
    {
        if( !IsAlive() )
            return;
        if( GetParent() == other )
            return;
        Transport transport = Transport.Cast(other);
        if( transport )
        {
            if ( GetGame().IsServer() )
            {
                RegisterTransportHit(transport);
            }
        }
    }
References GetGame(), GetParent(), and IsAlive().
EvaluateDamageHitAnimation()
bool EvaluateDamageHitAnimation (TotalDamageResult pDamageResult, int pDamageType, EntityAI pSource, string pComponent, string pAmmoType, vector pModelPos, out int pAnimType, out float pAnimHitDir, out bool pAnimHitFullbody)
selects animation type and direction based on damage system data
ignore hit impacts in prone (for now)
impact from infected attack will be light only
play full body when these coponents were hit
skip evaluation of dmg hit animation
direction
Definition at line 1068 of file dayzplayerimplement.c.
    {
        int invertHitDir = 0; //Used to flip the heavy hit animation direction
        pAnimType = 0;
        pAnimHitFullbody = false; // additive anm
        GetMovementState(m_MovementState);
        switch ( pDamageType )
        {
            case DT_CLOSE_COMBAT:
                /*if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
                    return false;*/
                if ( pSource.IsInherited(DayZInfected) )
                    break;
                pAnimType = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " hitAnimation");
                invertHitDir = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " invertHitDir");
                if ( !IsUnconscious() && pAnimType == 1 && !m_MeleeFightLogic.IsInBlock() )
                    pAnimHitFullbody = true;
            break;
            case DT_FIRE_ARM:
                int impactBehaviour = 0;
                if ( !IsUnconscious() && GetHealth("", "Shock") > 25 )
                {
                    if ( pComponent == "Torso" || pComponent == "Head")
                    {
                        impactBehaviour = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " impactBehaviour");
                        float fireDamage = pDamageResult.GetHighestDamage("Health");
                        float shockDamage = pDamageResult.GetHighestDamage("Shock");
                        if ( ( fireDamage > 80.0 || shockDamage > 40.0 ) && impactBehaviour == 1 )
{
                            pAnimHitFullbody = true;
                        }
                    }
                }
            break;
            case DT_EXPLOSION:
            break;
            case DT_CUSTOM:
                pAnimType = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " hitAnimation");
                if ( pAnimType == 1 )
                    pAnimHitFullbody = true;
                else
                    return false;
            break;
        }
        vector targetDirection = GetDirection();
        vector toSourceDirection = (pSource.GetPosition() - GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        pAnimHitDir = Math.Acos(cosFi) * Math.RAD2DEG;
        // We will invert direction of the hit
        if ( invertHitDir > 0 )
            pAnimHitDir -= 180;
        if (cross[1] < 0)
            pAnimHitDir = -pAnimHitDir;
        //Print("hitdir: " + pAnimHitDir.ToString());
        return true;
    }
References Math::Acos(), CGame::ConfigGetInt(), vector::Dot(), GetDirection(), GetGame(), GetHealth(), TotalDamageResult::GetHighestDamage(), GetMovementState(), GetPosition, m_MeleeFightLogic, m_MovementState, vector::Normalize(), and Math::RAD2DEG.
Referenced by DayZInfected::EEHitBy(), and EEHitBy().
EvaluateDeathAnimation()
bool EvaluateDeathAnimation (int pDamageType, EntityAI pSource, string pAmmoType, out int pAnimType, out float pAnimHitDir)
selects animation type and direction based on damage system data
anim type (-1 = default)
direction
Definition at line 1035 of file dayzplayerimplement.c.
    {
        bool doPhxImpulse = GetGame().ConfigGetInt("cfgAmmo " + pAmmoType + " doPhxImpulse") > 0;
        pAnimType = -1;
        if ( doPhxImpulse )
            pAnimType = 10;
        vector targetDirection = GetDirection();
        vector toSourceDirection = (pSource.GetPosition() - GetPosition());
        targetDirection[1] = 0;
        toSourceDirection[1] = 0;
        targetDirection.Normalize();
        toSourceDirection.Normalize();
        float cosFi = vector.Dot(targetDirection, toSourceDirection);
        vector cross = targetDirection * toSourceDirection;
        pAnimHitDir = Math.Acos(cosFi) * Math.RAD2DEG;
        if (cross[1] < 0)
            pAnimHitDir = -pAnimHitDir;
        //Print("hitdir: " + pAnimHitDir.ToString());
        return true;
    }
References Math::Acos(), CGame::ConfigGetInt(), vector::Dot(), GetDirection(), GetGame(), GetPosition, vector::Normalize(), and Math::RAD2DEG.
Referenced by EEHitBy(), and DayZInfected::EvaluateDeathAnimationEx().
ExitSights()
void ExitSights ()
Definition at line 281 of file dayzplayerimplement.c.
    {
        ItemOptics optics = null;
        EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
        Weapon weapon = Weapon.Cast(entityInHands);
        if (weapon)
        {
            optics = weapon.GetAttachedOptics();
        }
        else
        {
            optics = ItemOptics.Cast(entityInHands);
        }
        SetIronsights(false);
        SetOptics(false);
        if (optics)
        {
            SwitchOptics(optics,false);
        }
        HumanCommandWeapons hcw = GetCommandModifier_Weapons();
        if (hcw)
        {
            hcw.SetADS(false);
        }
    }
References GetCommandModifier_Weapons(), HumanCommandWeapons::SetADS(), SetIronsights(), SetOptics(), and SwitchOptics().
Referenced by HandleADS(), and HandleView().
GetAimingModel()
DayZPlayerImplementAiming GetAimingModel ()
Definition at line 156 of file dayzplayerimplement.c.
    {
        return m_AimingModel;
    }
References m_AimingModel.
Referenced by ManBase::OnSyncJuncture().
GetBackAttachmentType()
AnimBackType GetBackAttachmentType ()
Definition at line 2685 of file dayzplayerimplement.c.
    {
        EntityAI back = GetInventory().FindAttachment(InventorySlots.BACK);
        if(back)
        {
            switch( back.GetAttachmentSoundType() )
            {
                case "Small":
                    return AnimBackType.Small;
                case "Military":
                    return AnimBackType.Military;
                case "Outdoor":
                    return AnimBackType.Outdoor;
                case "Ghillie":
                    return AnimBackType.Ghillie;
            }
        }
        return AnimBackType.None;
    }
Referenced by ProcessAttachmentEvent().
GetBodyAttachmentType()
AnimUpperBodyType GetBodyAttachmentType ()
Definition at line 2656 of file dayzplayerimplement.c.
    {
        EntityAI attachment = GetInventory().FindAttachment(InventorySlots.BODY);
        if(attachment)
        {
            switch( attachment.GetAttachmentSoundType() )
            {
                case "NylonJacket":
                    return AnimUpperBodyType.NylonJacket;
                case "TShirt":
                    return AnimUpperBodyType.TShirt;
                case "WoolShirt":
                    return AnimUpperBodyType.WoolShirt;
                case "HeavyJacket":
                    return AnimUpperBodyType.HeavyJacket;
                case "LeatherJacket":
                    return AnimUpperBodyType.LeatherJacket;
                case "Coat":
                    return AnimUpperBodyType.Coat;
                case "ChemlonDress":
                    return AnimUpperBodyType.ChemlonDress;
                case "Ghillie":
                    return AnimUpperBodyType.Ghillie;
            }
        }
        return AnimUpperBodyType.None;
    }
Referenced by ProcessAttachmentEvent().
GetBootsType()
AnimBootsType GetBootsType ()
Definition at line 2638 of file dayzplayerimplement.c.
    {
        EntityAI boots = GetInventory().FindAttachment(InventorySlots.FEET);
        if(boots)
        {
            switch( boots.GetAttachmentSoundType() )
            {
                case "Sneakers":
                    return AnimBootsType.Sneakers;
                case "Boots":
                    return AnimBootsType.Boots;
            }
        }
        return AnimBootsType.None;
    }
Referenced by OnStepEvent(), and SetVariablesLadderSoundObjectBuilder().
GetDayZPlayerInventory()
DayZPlayerInventory GetDayZPlayerInventory ()
Definition at line 628 of file dayzplayerimplement.c.
    {
        DayZPlayerInventory inv = DayZPlayerInventory.Cast(GetInventory());
        return inv;
    }
Referenced by AbortWeaponEvent(), ManBase::CanDeleteItems(), ManBase::CommandHandler(), HandleADS(), HandleWeapons(), OnInputForRemote(), OnInputFromServer(), ManBase::OnQuickBarSingleUse(), StopHandEvent(), and StopWeaponEvent().
GetMeleeCombat()
DayZPlayerImplementMeleeCombat GetMeleeCombat ()
Definition at line 161 of file dayzplayerimplement.c.
    {
        return m_MeleeCombat;
    }
References m_MeleeCombat.
GetMeleeFightLogic()
DayZPlayerMeleeFightLogic_LightHeavy GetMeleeFightLogic ()
Definition at line 166 of file dayzplayerimplement.c.
    {
        return m_MeleeFightLogic;
    }
References m_MeleeFightLogic.
Referenced by ManBase::EEItemIntoHands(), and ManBase::OnUnconsciousStart().
GetShoulderAttachmentType()
AnimRangedWeaponType GetShoulderAttachmentType ()
Definition at line 2707 of file dayzplayerimplement.c.
    {
        EntityAI shoulderAttachment = GetInventory().FindAttachment(InventorySlots.SHOULDER);
        EntityAI meleeAttachment = GetInventory().FindAttachment(InventorySlots.MELEE);
        AnimRangedWeaponType shoulderAttType = AnimRangedWeaponType.None;
        AnimRangedWeaponType meleeAttType = AnimRangedWeaponType.None;
        if(shoulderAttachment)
        {
            switch( shoulderAttachment.GetAttachmentSoundType())
            {
                case "Shotgun":
                {
                    shoulderAttType = AnimRangedWeaponType.Shotgun;
                    break;
                }
                case "Rifle":
                {
                    shoulderAttType = AnimRangedWeaponType.Rifle;
                    break;
                }
            }
        }
        if(meleeAttachment)
        {
            switch( meleeAttachment.GetAttachmentSoundType())
            {
                case "Shotgun":
                {
                    meleeAttType = AnimRangedWeaponType.Shotgun;
                    break;
                }
                case "Rifle":
                {
                    meleeAttType = AnimRangedWeaponType.Rifle;
                    break;
                }
            }
        }
        if(shoulderAttType == AnimRangedWeaponType.Shotgun || meleeAttType == AnimRangedWeaponType.Shotgun)
            return AnimRangedWeaponType.Shotgun;
        if(shoulderAttType == AnimRangedWeaponType.Rifle || meleeAttType == AnimRangedWeaponType.Rifle)
            return AnimRangedWeaponType.Rifle;
        return AnimRangedWeaponType.None;
    }
Referenced by ProcessAttachmentEvent().
GetSlidePoseAngle()
float GetSlidePoseAngle ()
Definition at line 3292 of file dayzplayerimplement.c.
    {
        return GetDayZPlayerType().CommandMoveSettingsW().m_fSlidingPoseAngle;
    }
References GetDayZPlayerType().
Referenced by ManBase::Init().
GetSurfaceType()
string GetSurfaceType (SurfaceAnimationBone limbType)
Definition at line 2757 of file dayzplayerimplement.c.
    {
        string surfaceType;
        int liquidType;
        GetGame().SurfaceUnderObjectByBone(this, limbType, surfaceType, liquidType);
        return surfaceType;
    }
References GetGame(), and CGame::SurfaceUnderObjectByBone().
GetThrowing()
DayZPlayerImplementThrowing GetThrowing ()
Definition at line 171 of file dayzplayerimplement.c.
    {
        return m_Throwing;
    }
References m_Throwing.
Referenced by ManBase::CanBeRestrained(), ManBase::CanChangeStance(), ManBase::CanDeleteItems(), and ManBase::OnQuickBarSingleUse().
GetTypeOfDeath()
int GetTypeOfDeath (int pCurrentCommandID)
Definition at line 419 of file dayzplayerimplement.c.
    {
        switch ( pCurrentCommandID )
        {
        case DayZPlayerConstants.COMMANDID_SWIM:
            return 11;
        case DayZPlayerConstants.COMMANDID_FALL:
            return 12;
        case DayZPlayerConstants.COMMANDID_UNCONSCIOUS:
            {
                HumanCommandUnconscious hcu = GetCommand_Unconscious();
                if ( hcu )
                {
                    if ( hcu.IsOnLand() )
                        return 13;
                    if ( hcu.IsInWater() )
                        return 14;
                }
            }
            break;
        }
        return 0;
    }
References GetCommand_Unconscious(), HumanCommandUnconscious::IsInWater(), and HumanCommandUnconscious::IsOnLand().
Referenced by HandleDeath().
GetWeaponManager()
WeaponManager GetWeaponManager ()
Definition at line 698 of file dayzplayerimplement.c.
{ return null; }
Referenced by ManBase::CanBeRestrained(), ManBase::CanRedirectToWeaponManager(), ManBase::GetMagazineToReload(), HandleWeapons(), ManBase::OnCommandClimbFinish(), ManBase::OnCommandClimbStart(), ManBase::OnCommandDeathStart(), ManBase::OnCommandFallFinish(), ManBase::OnCommandFallStart(), ManBase::OnCommandMelee2Finish(), ManBase::OnCommandMelee2Start(), ManBase::OnCommandSwimFinish(), ManBase::OnCommandSwimStart(), ManBase::OnJumpEnd(), ManBase::OnJumpStart(), ManBase::OnQuickBarSingleUse(), ManBase::OnStanceChange(), ManBase::PredictiveDropEntity(), ManBase::PredictiveSwapEntities(), ManBase::PredictiveTakeEntityToInventory(), ManBase::PredictiveTakeEntityToTargetAttachment(), ManBase::PredictiveTakeEntityToTargetAttachmentEx(), ManBase::PredictiveTakeEntityToTargetCargo(), ManBase::PredictiveTakeEntityToTargetCargoEx(), ManBase::PredictiveTakeEntityToTargetInventory(), ManBase::PredictiveTakeToDst(), ManBase::ProcessLiftWeapon(), ManBase::ReloadWeapon(), and ManBase::SendLiftWeaponSync().
HandleADS()
void HandleADS ()
This is main command logic
artificial Auto-ADS delay
if !raised if sprinting
Definition at line 1428 of file dayzplayerimplement.c.
    {
        if (!IsAlive())
        {
            if (m_CameraIronsight || m_CameraOptics)
            {
                ExitSights();
            }
            return;
        }
        bool bADSToggle = false;
        bool exitSights = false;
        HumanInputController hic = GetInputController();
        HumanItemAccessor   hia = GetItemAccessor();
        HumanCommandWeapons hcw = GetCommandModifier_Weapons();
        PlayerBase playerPB = PlayerBase.Cast(this);
        if (playerPB.IsRolling())
        {
            exitSights = true;
        }
        if (m_ResetADS || !hia.IsItemInHandsWeapon())
        {
            hic.ResetADS();
            m_ResetADS = false;
        }
        if ( !m_IsFireWeaponRaised || m_LiftWeapon_player)
        {
            StopADSTimer();
            exitSights = true;
        }
        else
        {
            if ( m_bADS != hic.WeaponADS() )
            {
                m_bADS = hic.WeaponADS();
                bADSToggle = true;
            }
            if ( m_bADS && !m_CameraIronsight && !m_CameraOptics )
            {
                if ( !m_WeaponRaiseCompleted )
                {
                    bADSToggle = false;
                    exitSights = true;
                }
                else
                {
                    bADSToggle = true;
                }
            }
        }
        if (bADSToggle && !GetCommand_Melee2())
        {
            if (hia.IsItemInHandsWeapon() && playerPB.GetItemInHands() && playerPB.GetItemInHands().IsWeapon() && playerPB.GetWeaponManager() && !playerPB.GetWeaponManager().IsRunning() )
            {
                Weapon_Base weapon = Weapon_Base.Cast(GetHumanInventory().GetEntityInHands());
                ItemOptics optic = weapon.GetAttachedOptics();
                bool switchToADS = false;
                bool canUseIronsights = weapon.CanEnterIronsights();
                bool canUseOptics = optic != NULL;
                if (canUseIronsights || canUseOptics)
                    switchToADS = m_bADS;
                // go to ironsights - disable ironsights when
                GetMovementState(m_MovementState);
                if (!hic.IsWeaponRaised() || m_MovementState.m_iMovement == DayZPlayerConstants.MOVEMENTIDX_SPRINT)
                {
                    switchToADS = false;
                }
                // fixes camera switching during item transitions
                if ( IsLiftWeapon() || !IsRaised() || GetDayZPlayerInventory().IsProcessing() || !IsWeaponRaiseCompleted() || IsFighting() )
                {
                    exitSights = true;
                }
                else if (switchToADS) // enter ironsights or optics
                {
                    // filter by usability
                    if (m_WasIronsight && !canUseIronsights)
                    {
                        m_WasIronsight = false;
                    }
                    else if (!m_WasIronsight && !canUseOptics)
                    {
                        m_WasIronsight = true;
                    }
                    if (m_WasIronsight)
                    {
//                      Print("GO: IRONSIGHT");
                        hic.ResetFreeLookToggle();
                        SwitchOptics(optic,false);
                        SetIronsights(true);
                    }
                    else if (!m_WasIronsight || (!canUseIronsights && canUseOptics))
                    {
//                      Print("GO: OPTICS");
                        SetIronsights(false);
                        SwitchOptics(optic,true);
                    }
                    else
                    {
                        exitSights = true;
                    }
                    if (hcw && (m_CameraOptics || m_CameraIronsight))
                    {
                        hcw.SetADS(true);
                    }
                }
                else
                {
                    exitSights = true;
                }
            }
        }
        // leave ironsight and/ or optics
        if ( exitSights && !m_HandheldOpticsInUse && (m_CameraIronsight || m_CameraOptics) || GetCommand_Melee2() )
        {
            ExitSights();
        }
    }
References ExitSights(), GetCommand_Melee2(), GetCommandModifier_Weapons(), GetDayZPlayerInventory(), GetInputController(), GetItemAccessor(), GetMovementState(), HumanItemAccessor(), IsAlive(), IsFighting(), IsLiftWeapon(), IsProcessing(), IsRaised(), IsWeaponRaiseCompleted(), HumanInputController::IsWeaponRaised(), m_bADS, m_CameraIronsight, m_CameraOptics, m_HandheldOpticsInUse, m_IsFireWeaponRaised, m_LiftWeapon_player, m_MovementState, m_ResetADS, m_WasIronsight, m_WeaponRaiseCompleted, HumanInputController::ResetADS(), HumanInputController::ResetFreeLookToggle(), HumanCommandWeapons::SetADS(), SetIronsights(), StopADSTimer(), SwitchOptics(), and HumanInputController::WeaponADS().
Referenced by CommandHandler().
HandleDamageHit()
bool HandleDamageHit (int pCurrentCommandID)
ignore hit impacts in prone (for now)
Definition at line 964 of file dayzplayerimplement.c.
    {
        if ( !m_SyncedHitDataArray || m_SyncedHitDataArray.Count() == 0 )
        {
            return false;
        }
        //evaluate all hit data
        SyncHitInfo data;
        SyncHitInfo greatest_hit;
        for (int i = 0; i < m_SyncedHitDataArray.Count(); i++)
        {
            data = m_SyncedHitDataArray[i];
            m_DamageHitDir = data.m_HitDir;
            //client-side effects
            if ( !GetGame().IsDedicatedServer() && IsAlive() && !IsUnconscious() && data.m_HasSource && GetGame().GetMission().GetHud() && GetGame().GetPlayer() == this ) //only for controlled players
            {
                m_DamageHealth = data.m_HealthDamage;
                if (m_DamageHealth > 0.0)
                {
                    float rel = m_DamageHealth / (GetMaxHealth("","Health") * PlayerConstants.HEAVY_HIT_THRESHOLD);
                    GetGame().GetMission().GetHud().SpawnHitDirEffect(this,m_DamageHitDir,rel);
                }
            }
            if ( !greatest_hit )
            {
                greatest_hit = data;
            }
            //else if ( data.m_HealthDamage > greatest_hit.m_HealthDamage || (data.m_Fullbody && !greatest_hit.m_Fullbody) ) //TODO - revisit cumulative calculation for animation evaluation purposes (stagger on shotgun to the chest)
            else if ( data.m_Fullbody ) //temporary solution; last fullbody hit is used for animation purposes, some light hit otherwise
            {
                greatest_hit = data;
            }
        }
        //general effects
        m_DamageHitFullbody = greatest_hit.m_Fullbody;
        m_DamageHitAnimType = greatest_hit.m_AnimType;
        m_DamageHitDir = greatest_hit.m_HitDir;
        m_SyncedHitDataArray.Clear();
        m_DamageHealth = 0.0;
        if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
            return false;
        // If transportcache is not null, player is unconscious inside of a car and should not head into a damage command
        if (m_DamageHitAnimType != -1 && m_TransportCache == null)
        {
            HumanCommandVehicle vehCommand = GetCommand_Vehicle();
            if (m_DamageHitFullbody && (!vehCommand || vehCommand.IsGettingIn() || vehCommand.IsGettingOut()))
            {
                StartCommand_Damage(m_DamageHitAnimType, m_DamageHitDir);
                m_DamageHitAnimType = -1;
                return true;
            }
            else
            {
                AddCommandModifier_Damage(m_DamageHitAnimType, m_DamageHitDir);
                m_DamageHitAnimType = -1;
                return false;
            }
        }
        return pCurrentCommandID == DayZPlayerConstants.COMMANDID_DAMAGE;
    }
References AddCommandModifier_Damage(), GetCommand_Vehicle(), GetGame(), Mission::GetHud(), GetMaxHealth(), CGame::GetMission(), GetPlayer(), PlayerConstants::HEAVY_HIT_THRESHOLD, IsAlive(), HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), m_DamageHealth, m_DamageHitAnimType, m_DamageHitDir, m_DamageHitFullbody, m_MovementState, m_SyncedHitDataArray, m_TransportCache, Hud::SpawnHitDirEffect(), and StartCommand_Damage().
Referenced by DayZCreatureAI::CommandHandler(), DayZInfected::CommandHandler(), and ManBase::CommandHandler().
HandleDeath()
bool HandleDeath (int pCurrentCommandID)
Definition at line 364 of file dayzplayerimplement.c.
    {
        if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_DEATH)
        {
            if ((GetGame().GetTickTime() - m_DeathStartTime) > m_DeathSimulationTimeout)
                DisableSimulation(true);
            return true;
        }
        if (m_DeathAnimType != -2 && g_Game.GetMissionState() == g_Game.MISSION_STATE_GAME)
        {
            if (!m_Suicide)
            {
                int type = m_DeathAnimType;
                if( type == -1 )
                    type = GetTypeOfDeath(pCurrentCommandID);
                // Maybe move elsewhere? Couldn't find a more fitting place to do this but I'm sure there is one
                // If player dies in driver seat, car shouldn't be simulated by the dead player anymore
                if (pCurrentCommandID == DayZPlayerConstants.COMMANDID_VEHICLE)
                {
                    HumanCommandVehicle hcv = GetCommand_Vehicle();
                    Transport transport = hcv.GetTransport();
                    int crewPos = transport.CrewMemberIndex( this );
                    transport.CrewDeath( crewPos );
                    if (hcv.IsGettingIn() || hcv.IsGettingOut())
                    {
                        transport.CrewGetOut(crewPos);
                        UnlinkFromLocalSpace();
                        DisableSimulation(false);
                        GetItemAccessor().HideItemInHands(false);
                        m_TransportCache = null;
                    }
                }
                DayZPlayerCommandDeathCallback callback = DayZPlayerCommandDeathCallback.Cast(StartCommand_Death(type, m_DeathHitDir, DayZPlayerCommandDeathCallback));
                callback.m_pPlayer = PlayerBase.Cast(this);
            }
            ResetDeathStartTime();
            // disable voice communication
            GetGame().GetWorld().SetVoiceOn(false, false);
            return true;
        }
        return false;
    }
References g_Game, GetCommand_Vehicle(), GetGame(), GetItemAccessor(), HumanCommandVehicle::GetTransport(), GetTypeOfDeath(), CGame::GetWorld(), HumanCommandVehicle::IsGettingIn(), HumanCommandVehicle::IsGettingOut(), m_DeathAnimType, m_DeathHitDir, m_DeathSimulationTimeout, m_DeathStartTime, DayZPlayerCommandDeathCallback::m_pPlayer, m_Suicide, m_TransportCache, ResetDeathStartTime(), World::SetVoiceOn(), StartCommand_Death(), and UnlinkFromLocalSpace().
Referenced by DayZCreatureAI::CommandHandler(), CommandHandler(), and DayZInfected::CommandHandler().
HandleOptic()
void HandleOptic (notnull ItemOptics optic, bool inHands, HumanInputController pInputs, out bool pExitOptics)
Definition at line 872 of file dayzplayerimplement.c.
    {
        Input input = GetGame().GetInput();
        Weapon_Base weapon;
        int FOVcount;
        bool controllerPressIn;
        bool controllerPressOut;
        if (input.LocalPress("UAZoomInOptics"))
        {
            weapon = Weapon_Base.Cast(optic.GetHierarchyParent());
            FOVcount = optic.GetStepFOVCount();
            controllerPressIn = GetUApi().GetInputByName("UAZoomInOpticsControllerHelper").LocalPress();
            if (weapon && m_CameraIronsight && !m_CameraOptics)
            {
                SetIronsights(false);
                SwitchOptics(optic,true);
                optic.SetStepFOVIndex(0);
            }
            else if (m_CameraOptics)
            {
                if (controllerPressIn) //controller
                {
                    if (!optic.StepFOVUp())
                    {
                        if (FOVcount > 0)
{
                            optic.SetStepFOVIndex(0); //loop to minimum magnification
                        }
                        if (weapon && weapon.CanEnterIronsights()) //loop into ironsights
{
                            SwitchOptics(optic,false);
                            pInputs.ResetFreeLookToggle();
                            SetIronsights(true);
                        }
                    }
                }
                else //m&k
                {
                    optic.StepFOVUp();
                }
            }
        }
        if (input.LocalPress("UAZoomOutOptics"))
        {
            weapon = Weapon_Base.Cast(optic.GetHierarchyParent());
            FOVcount = optic.GetStepFOVCount();
            controllerPressOut = GetUApi().GetInputByName("UAZoomOutOpticsControllerHelper").LocalPress();
            if (m_CameraOptics)
            {
                if (!optic.StepFOVDown())
                {
                    if (controllerPressOut)
                    {
                        if (FOVcount > 0 && (!weapon || !weapon.CanEnterIronsights()))
{
                            optic.SetStepFOVIndex(FOVcount - 1); //loop to maximum magnification
                        }
                    }
                    if (weapon && weapon.CanEnterIronsights())
                    {
                        SwitchOptics(optic,false);
                        pInputs.ResetFreeLookToggle();
                        SetIronsights(true);
                    }
                }
            }
            else if (controllerPressOut && weapon && m_CameraIronsight)
            {
                SwitchOptics(optic,true);
                if (FOVcount > 0)
                {
                    optic.SetStepFOVIndex(FOVcount - 1); //loop to maximum magnification
                }
            }
        }
    }
References GetGame(), CGame::GetInput(), UAInputAPI::GetInputByName(), GetUApi(), UAInput::LocalPress(), Input::LocalPress(), m_CameraIronsight, m_CameraOptics, HumanInputController::ResetFreeLookToggle(), SetIronsights(), and SwitchOptics().
Referenced by CommandHandler(), and HandleWeapons().
HandleView()
void HandleView ()
3rd person camera
Definition at line 1563 of file dayzplayerimplement.c.
    {
        if (!IsAlive())
        {
            if (m_CameraIronsight || m_CameraOptics)
            {
                ExitSights();
            }
            return;
        }
        Input input = GetGame().GetInput();
        HumanInputController hic = GetInputController();
        bool camChange = hic.CameraViewChanged();
        if (IsRaised())
        {
            EntityAI ent = GetHumanInventory().GetEntityInHands();
            bool isWeapon = ent && ent.IsInherited(Weapon);
            if (isWeapon)
            {
                camChange = false;
            }
        }
        if (GetGame().GetWorld().Is3rdPersonDisabled())
        {
            m_Camera3rdPerson = false;
        }
        else if (camChange)
        {
            m_Camera3rdPerson = !m_Camera3rdPerson;
        }
        // exits optics completely, comment to return to ADS
        if ( m_LiftWeapon_player && (m_CameraOptics|| m_CameraIronsight) )
            ExitSights();
        if (IsPlayerInStance(DayZPlayerConstants.STANCEMASK_RAISEDPRONE) && (m_CameraOptics || m_CameraIronsight))
            GetDayZPlayerType().SetVerticalMinimumAimLimit(DayZPlayerCameraIronsights.CONST_UD_MIN_BACK);
        else
            GetDayZPlayerType().SetVerticalMinimumAimLimit(DayZPlayerCameraIronsights.CONST_UD_MIN);
        if ( !m_MovementState.IsRaised() && hic.IsZoomToggle() )
        {
            m_CameraZoomToggle = true;
            m_CameraEyeZoom = true;
        }
        else
        {
            m_CameraZoomToggle = false;
            m_CameraEyeZoom = false;
        }
        if (m_MovementState.IsRaisedInProne())
        {
            float headingAngle = MiscGameplayFunctions.GetHeadingAngle(this);
            float headingAngleDiffBlock = Math.AbsFloat(m_LastHeadingAngleBlock - headingAngle);
            float headingAngleDiffBlock2 = Math.AbsFloat(m_LastHeadingAngleBlock2 - headingAngle);
            float headingAngleDiff = 0.0;
            if (m_LastHeadingAngle * headingAngle < 0.0)
            {
                headingAngleDiff = Math.AbsFloat(m_LastHeadingAngle + headingAngle);
            }
            else
            {
                headingAngleDiff = Math.AbsFloat(m_LastHeadingAngle - headingAngle);
            }
            if (headingAngleDiff > 0.2)
            {
                int time = GetGame().GetTime();
                float timefilterconstant = 400 - (headingAngleDiff * 100);
                if (headingAngleDiffBlock > 0.8 && time - m_LastBackSoundTime > timefilterconstant)
                {
                    float volume = headingAngleDiff / 0.5;
                    if (volume > 1)
                    {
                        volume = 1;
                    }
                    if (volume < 0.25)
                    {
                        volume = 0.25;
                    }
                    m_SoundOffset = headingAngleDiff / 2;
                    if (m_SoundOffset > 0.25)
                    {
                        m_SoundOffset = 0.25;
                    }
                    string soundSetName = "Cloth_Body_longmove_TShirt_Soundset";
                    string bodyClothName = "";
                    EntityAI attachment = GetInventory().FindAttachment(InventorySlots.BODY);
                    if (attachment)
                    {
                        bodyClothName = attachment.GetAttachmentSoundType();
                    }
                    if (bodyClothName != "")
                    {
                        string path = "CfgSoundTables CfgAttachmentSoundTables Cloth_Body_Longmove_LookupTable";
                        int soundCount = GetGame().ConfigGetChildrenCount(path);
                        for (int i = 0; i < soundCount; i++)
{
                            string name = "";
                            GetGame().ConfigGetChildName(path, i, name);
                            if (name == bodyClothName)
{
                                TStringArray stringArray = new TStringArray();
                                GetGame().ConfigGetTextArray(path + " " + name + " soundSets", stringArray);
                                soundSetName = stringArray.Get(0);
                                delete stringArray;
                            }
                        }
                    }
                    SoundParams soundParams = new SoundParams(soundSetName);
                    SoundObjectBuilder soundObjectBuilder = new SoundObjectBuilder(soundParams);
                    if (soundObjectBuilder != NULL)
                    {
                        SoundObject soundObject = soundObjectBuilder.BuildSoundObject();
                        if (soundObject != NULL)
{
                            soundObject.SetPosition(GetPosition());
                            AbstractWave wave = GetGame().GetSoundScene().Play3D(soundObject, soundObjectBuilder);
                            wave.SetStartOffset(m_SoundOffset);
                            wave.SetVolumeRelative(volume);
                            m_LastBackSoundTime = GetGame().GetTime();
                            m_LastHeadingAngleBlock = headingAngle;
                        }
                    }
                }
                if (headingAngleDiffBlock2 > 1.5 && time - m_LastBackSoundTime2 > (timefilterconstant * 2))
                {
                    float volume2 = headingAngleDiff * 2;
                    if (volume2 > 1)
                    {
                        volume2 = 1;
                    }
                    m_SoundOffset = headingAngleDiff / 1.8;
                    if (m_SoundOffset < 0.1)
                    {
                        m_SoundOffset = 0.1;
                    }
                    if (m_SoundOffset > 0.3)
                    {
                        m_SoundOffset = 0.3;
                    }
                    string soundSetName2 = "walkProne_noHS_asphalt_ext_Char_SoundSet";
                    string surfaceType = GetSurfaceType();
                    if (surfaceType != "")
                    {
                        string movementSurfaceType = "walkProne_" + surfaceType;
                        string path2 = "CfgSoundTables CfgStepSoundTables walkProne_noHS_Char_LookupTable";
                        int soundCount2 = GetGame().ConfigGetChildrenCount(path2);
                        for (int i2 = 0; i2 < soundCount2; i2++)
{
                            string name2 = "";
                            GetGame().ConfigGetChildName(path2, i2, name2);
                            if (name2 == movementSurfaceType)
{
                                TStringArray stringArray2 = new TStringArray();
                                GetGame().ConfigGetTextArray(path2 + " " + name2 + " soundSets", stringArray2);
                                soundSetName2 = stringArray2.Get(0);
                                delete stringArray2;
                            }
                        }
                    }
                    SoundParams soundParams2 = new SoundParams(soundSetName2);
                    SoundObjectBuilder soundObjectBuilder2 = new SoundObjectBuilder(soundParams2);
                    if (soundObjectBuilder2 != NULL)
                    {
                        SoundObject soundObject2 = soundObjectBuilder2.BuildSoundObject();
                        if (soundObject2 != NULL)
{
                            soundObject2.SetPosition(GetPosition());
                            AbstractWave wave2 = GetGame().GetSoundScene().Play3D(soundObject2, soundObjectBuilder2);
                            wave2.SetStartOffset(m_SoundOffset);
                            wave2.SetVolumeRelative(volume2);
                            m_LastBackSoundTime2 = GetGame().GetTime();
                            m_LastHeadingAngleBlock2 = headingAngle;
                        }
                    }
                }
                m_LastHeadingAngle = headingAngle;
            }
        }
    }
References Math::AbsFloat(), SoundObjectBuilder::BuildSoundObject(), HumanInputController::CameraViewChanged(), CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetTextArray(), ExitSights(), GetDayZPlayerType(), GetGame(), CGame::GetInput(), GetInputController(), GetPosition, CGame::GetSoundScene(), GetSurfaceType(), CGame::GetTime(), IsAlive(), IsPlayerInStance(), IsRaised(), HumanInputController::IsZoomToggle(), m_Camera3rdPerson, m_CameraEyeZoom, m_CameraIronsight, m_CameraOptics, m_CameraZoomToggle, m_LastBackSoundTime, m_LastBackSoundTime2, m_LastHeadingAngle, m_LastHeadingAngleBlock, m_LastHeadingAngleBlock2, m_LiftWeapon_player, m_MovementState, m_SoundOffset, name, path, AbstractWave::SetStartOffset(), AbstractWave::SetVolumeRelative(), and SoundObject().
Referenced by CommandHandler().
HandleWeapons()
void HandleWeapons (float pDt, Entity pInHands, HumanInputController pInputs, out bool pExitIronSights)
HandleWeapons
fire
Definition at line 704 of file dayzplayerimplement.c.
    {
        HumanCommandWeapons     hcw = GetCommandModifier_Weapons();
        GetDayZPlayerInventory().HandleWeaponEvents(pDt, pExitIronSights);
        Weapon_Base weapon;
        Class.CastTo(weapon, pInHands);
        CheckLiftWeapon();
        ProcessLiftWeapon();
        GetMovementState(m_MovementState);
        // hold breath
        if (pInputs.IsHoldBreath() && m_MovementState.IsRaised() && (IsInIronsights() || IsInOptics()))
        {
            m_IsTryingHoldBreath = true;
        }
        else
        {
            m_IsTryingHoldBreath = false;
        }
        ItemOptics optic = weapon.GetAttachedOptics();
        if (pInputs.IsFireModeChange())
        {
            GetWeaponManager().SetNextMuzzleMode();
        }
        if (pInputs.IsZeroingUp())
        {
            if (optic && (optic.IsInOptics() || optic.IsUsingWeaponIronsightsOverride()) )
            {
                optic.StepZeroingUp();
            }
            else
            {
                weapon.StepZeroingUpAllMuzzles();
            }
        }
        if (pInputs.IsZeroingDown())
        {
            if (optic && (optic.IsInOptics() || optic.IsUsingWeaponIronsightsOverride()) )
            {
                optic.StepZeroingDown();
            }
            else
            {
                weapon.StepZeroingDownAllMuzzles();
            }
        }
        if (!m_LiftWeapon_player && (m_CameraIronsight || !weapon.CanEnterIronsights() || m_CameraOptics/*m_ForceHandleOptics*/))   // HACK straight to optics, if ironsights not allowed
        {
            if (optic)
                HandleOptic(optic, false, pInputs, pExitIronSights);
        }
        if (!m_MovementState.IsRaised())
        {
            m_IsFireWeaponRaised = false;
            if (weapon && weapon.IsInOptics())
                weapon.ExitOptics();
            StopADSTimer();
            m_WeaponRaiseCompleted = false;
            return; // if not raised => return
        }
        else
        {
            m_IsFireWeaponRaised = true;
            if ( !m_WeaponRaiseCompleted && (!m_ADSAutomationTimer || (m_ADSAutomationTimer && !m_ADSAutomationTimer.IsRunning())) )
            {
                if (GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_SERVER || !GetGame().IsMultiplayer())
                    RunADSTimer();
            }
            if (m_ProcessWeaponRaiseCompleted)
            {
                CompleteWeaponRaise();
                m_ProcessWeaponRaiseCompleted = false;
            }
        }
        if ( GetWeaponManager().CanFire(weapon) )
        {
            bool autofire = weapon.GetCurrentModeAutoFire(weapon.GetCurrentMuzzle()) && weapon.IsChamberEjectable(weapon.GetCurrentMuzzle());
            int burst = weapon.GetCurrentModeBurstSize(weapon.GetCurrentMuzzle());
            int burst_count = weapon.GetBurstCount();
            if ( !autofire && (burst < 2 || burst_count < 1) )
            {
                if ( pInputs.IsAttackButtonDown() && GetInputInterface().SyncedValue("UAWeaponMeleeAttack") == 0 && GetInputInterface().SyncedValue("UAHeavyMeleeAttack") == 0 )
                {
                    GetWeaponManager().Fire(weapon);
                }
            }
            else if (autofire || burst > 1)
            {
#ifdef DEVELOPER
                int burst_option = GetWeaponManager().GetBurstOption();
                if ( burst_option == 0)
                {
#endif
                    if ( pInputs.IsAttackButton() && GetInputInterface().SyncedValue("UAWeaponMeleeAttack") == 0 && GetInputInterface().SyncedValue("UAHeavyMeleeAttack") == 0 )
                    {
                        if ( autofire || burst_count < burst )
{
                            GetWeaponManager().Fire(weapon);
                        }
                    }
                    else
                    {
                        weapon.ResetBurstCount();
                    }
#ifdef DEVELOPER
                }
                else if (burst_option == 1)
                {
                    if ( burst > 1 && burst_count == burst )
                    {
                        weapon.ResetBurstCount();
                    }
                    else if (burst > 1 && burst_count < burst)
                    {
                        GetWeaponManager().Fire(weapon);
                    }
                    else
                    {
                        //Autofire
                        if (pInputs.IsAttackButton())
{
                            GetWeaponManager().Fire(weapon);
                        }
                    }
                }
#endif
            }
        }
        #ifdef PLATFORM_CONSOLE
        if ( GetGame().GetInput().LocalRelease( "UAFire", false ) || m_ShouldReload )
        {
            if ( !weapon.IsWaitingForActionFinish() && !IsFighting() )
            {
                int muzzle_index = weapon.GetCurrentMuzzle();
                if ( weapon.IsChamberFiredOut( muzzle_index ) )
                {
                    if ( weapon.CanProcessWeaponEvents() )
                    {
                        if ( GetWeaponManager().CanEjectBullet(weapon) )
{
                            GetWeaponManager().EjectBullet();
                            pExitIronSights = true;
                            m_ShouldReload = false;
                        }
                    }
                }
            }
            else
            {
                m_ShouldReload = true;
            }
        }
        #endif
    }
References Class::CastTo(), CheckLiftWeapon(), CompleteWeaponRaise(), WeaponManager::EjectBullet(), WeaponManager::Fire(), GetCommandModifier_Weapons(), GetDayZPlayerInventory(), GetGame(), GetInput(), GetInstanceType(), GetMovementState(), GetWeaponManager(), HandleOptic(), HumanInputController::IsAttackButton(), HumanInputController::IsAttackButtonDown(), IsFighting(), HumanInputController::IsFireModeChange(), HumanInputController::IsHoldBreath(), IsInIronsights(), IsInOptics(), HumanInputController::IsZeroingDown(), HumanInputController::IsZeroingUp(), m_ADSAutomationTimer, m_CameraIronsight, m_CameraOptics, m_IsFireWeaponRaised, m_IsTryingHoldBreath, m_LiftWeapon_player, m_MovementState, m_ProcessWeaponRaiseCompleted, m_ShouldReload, m_WeaponRaiseCompleted, ProcessLiftWeapon(), RunADSTimer(), WeaponManager::SetNextMuzzleMode(), and StopADSTimer().
Referenced by CommandHandler().
HeadingModel()
override bool HeadingModel (float pDt, SDayZPlayerHeadingModel pModel)
-------------— heading model ----------------------— updated each tick this can limit / extend player's heading (orientation) behaviour in game
on ladder - do nothing
if it's standing from prone on back
Definition at line 1228 of file dayzplayerimplement.c.
    {
        GetMovementState(m_MovementState);
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_LADDER )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_VEHICLE )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_UNCONSCIOUS )
        {
            m_fLastHeadingDiff = 0;
            //pModel.m_iCamMode = DayZPlayerConstants.CAMERAMODE_HEAD;
            return false;
        }
        if( m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_CLIMB )
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
#ifdef DEVELOPER
        int actMenuValue = DiagMenu.GetValue(DayZPlayerConstants.DEBUG_TURNSLIDE);
        if (actMenuValue != 0)
        {
            return DayZPlayerImplementHeading.ClampHeading(pDt, pModel, m_fLastHeadingDiff);
        }
#endif
        if (m_MovementState.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
        {
            m_fLastHeadingDiff = 0;
            return false;
        }
        if (m_MovementState.m_CommandTypeId == DayZPlayerConstants.COMMANDID_MOVE)
        {
            HumanCommandMove hcm = GetCommand_Move();
            if (hcm.IsStandingFromBack())
            {
                m_fLastHeadingDiff = 0;
                return false;
            }
        }
        HumanItemAccessor hia = GetItemAccessor();
        HumanItemBehaviorCfg hibcfg = hia.GetItemInHandsBehaviourCfg();
        if (hibcfg && hibcfg.m_StanceRotation[m_MovementState.m_iStanceIdx] == DayZPlayerConstants.ROTATION_DISABLE)
        {
            return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
        }
        if ( IsUnconscious() || (GetCommand_Move() && GetCommand_Move().IsLeavingUncon()) )
        {
            return DayZPlayerImplementHeading.NoHeading(pDt, pModel, m_fLastHeadingDiff);
        }
        return DayZPlayerImplementHeading.RotateOrient(pDt, pModel, m_fLastHeadingDiff);
    }
References DayZPlayerImplementHeading::ClampHeading(), GetCommand_Move(), GetItemAccessor(), GetMovementState(), DiagMenu::GetValue(), HumanItemAccessor(), IsLeavingUncon(), HumanCommandMove::IsStandingFromBack(), m_fLastHeadingDiff, m_MovementState, HumanItemBehaviorCfg::m_StanceRotation, DayZPlayerImplementHeading::NoHeading(), and DayZPlayerImplementHeading::RotateOrient().
HideClothing()
void HideClothing (ItemOptics optic, bool state)
Definition at line 2168 of file dayzplayerimplement.c.
{}
IsEyeZoom()
override bool IsEyeZoom ()
returns true if player is using EyeZoom, otherwise false
Definition at line 180 of file dayzplayerimplement.c.
    {
        return m_CameraEyeZoom;
    }
References m_CameraEyeZoom.
IsFBSymptomPlaying()
bool IsFBSymptomPlaying ()
Definition at line 348 of file dayzplayerimplement.c.
    {
        return m_isFBsymptomPlaying;
    }
References m_isFBsymptomPlaying.
Referenced by CanClimb(), and CanJump().
IsFighting()
bool IsFighting ()
Referenced by HandleADS(), and HandleWeapons().
IsFireWeaponRaised()
bool IsFireWeaponRaised ()
Definition at line 215 of file dayzplayerimplement.c.
    {
        return m_IsFireWeaponRaised;
    }
References m_IsFireWeaponRaised.
Referenced by AimingModel(), and ManBase::OnSyncJuncture().
IsHandheldOpticsInUse()
bool IsHandheldOpticsInUse ()
Definition at line 3367 of file dayzplayerimplement.c.
    {
        return m_HandheldOpticsInUse;
    }
References m_HandheldOpticsInUse.
IsInFBEmoteState()
bool IsInFBEmoteState ()
Checks if fullbody animation or specific locked state is active in emote manager.
Referenced by CanClimb(), ManBase::CanConsumeStamina(), CanJump(), ManBase::CanJump(), ManBase::CanRoll(), ManBase::CanStartConsumingStamina(), and ManBase::CheckAnimationOverrides().
IsInIronsights()
bool IsInIronsights ()
Definition at line 195 of file dayzplayerimplement.c.
    {
        return m_CameraIronsight;
    }
References m_CameraIronsight.
Referenced by HandleWeapons().
IsInOptics()
bool IsInOptics ()
Definition at line 200 of file dayzplayerimplement.c.
    {
        return m_CameraOptics;
    }
References m_CameraOptics.
Referenced by HandleWeapons(), KazuarOptic::UpdateSelectionVisibility(), and StarlightOptic::UpdateSelectionVisibility().
IsInThirdPerson()
override bool IsInThirdPerson ()
return true if player is currently in 3pp, otherwise false
Definition at line 205 of file dayzplayerimplement.c.
    {
        return m_Camera3rdPerson;
    }
References m_Camera3rdPerson.
IsLiftWeapon()
bool IsLiftWeapon ()
Referenced by HandleADS().
IsPlayerSelected()
bool IsPlayerSelected ()
Definition at line 3301 of file dayzplayerimplement.c.
    {
        return m_PlayerSelected;
    }
References m_PlayerSelected.
Referenced by ManBase::CheckAnimationOverrides(), ManBase::CheckDeath(), ManBase::CommandHandler(), OnScheduledTick(), ManBase::OnScheduledTick(), SymptomManager::SendServerDebugToClient(), and ShowDeadScreen().
IsRaised()
bool IsRaised ()
Definition at line 3373 of file dayzplayerimplement.c.
    {
        return m_IsRaised;
    }
References m_IsRaised.
IsRestrained()
bool IsRestrained ()
Referenced by ManBase::CanBeRestrained(), CanClimb(), ManBase::CanConsumeStamina(), ManBase::CanDropEntity(), CanJump(), ManBase::CanManipulateInventory(), ManBase::CanStartConsumingStamina(), CheckForTakeItem(), ManBase::OnQuickBarContinuousUseStart(), ManBase::OnQuickBarSingleUse(), ManBase::OnUnconsciousStart(), and ManBase::Save().
IsShootingFromCamera()
override bool IsShootingFromCamera ()
return true if shots are fired from camere, otherwise false
Definition at line 185 of file dayzplayerimplement.c.
    {
        return m_IsShootingFromCamera;
    }
References m_IsShootingFromCamera.
IsSprintFull()
bool IsSprintFull ()
Definition at line 225 of file dayzplayerimplement.c.
    {
        return m_SprintFull;
    }
References m_SprintFull.
IsTryingHoldBreath()
bool IsTryingHoldBreath ()
Definition at line 220 of file dayzplayerimplement.c.
    {
        return m_IsTryingHoldBreath;
    }
References m_IsTryingHoldBreath.
Referenced by ManBase::ProcessHoldBreath().
IsWeaponRaiseCompleted()
bool IsWeaponRaiseCompleted ()
Definition at line 623 of file dayzplayerimplement.c.
    {
        return m_WeaponRaiseCompleted;
    }
References m_WeaponRaiseCompleted.
Referenced by HandleADS().
LockControls()
void LockControls (bool state)
Definition at line 552 of file dayzplayerimplement.c.
    {
        if (state == true)
        {
            GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_MOUSE);
            GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_KEYBOARD);
            GetGame().GetInput().ChangeGameFocus(1, INPUT_DEVICE_GAMEPAD);
            if (GetGame().GetUIManager())
            {
                GetGame().GetUIManager().ShowUICursor(true);
                if (GetGame().GetUIManager().IsDialogVisible())
                    GetGame().GetUIManager().CloseDialog();
            }
        }
        else
        {
            GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_MOUSE);
            GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_KEYBOARD);
            GetGame().GetInput().ChangeGameFocus(-1, INPUT_DEVICE_GAMEPAD);
            if (GetGame().GetUIManager())
            {
                if (GetGame().GetUIManager().GetMenu())
                {
                    GetGame().GetUIManager().ShowUICursor(true);
                }
                else
                {
                    GetGame().GetUIManager().ShowUICursor(false);
                }
            }
        }
    }
References Input::ChangeGameFocus(), UIManager::CloseDialog(), GetGame(), CGame::GetInput(), CGame::GetUIManager(), INPUT_DEVICE_GAMEPAD, INPUT_DEVICE_KEYBOARD, INPUT_DEVICE_MOUSE, and UIManager::ShowUICursor().
Referenced by UIMenuPanel::OnShow(), and SimulateDeath().
ModCommandHandlerAfter()
bool ModCommandHandlerAfter (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
Definition at line 1805 of file dayzplayerimplement.c.
    {
        return false;
    }
Referenced by DayZCreatureAI::CommandHandler(), CommandHandler(), and DayZInfected::CommandHandler().
ModCommandHandlerBefore()
bool ModCommandHandlerBefore (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
ModOverrides
Definition at line 1795 of file dayzplayerimplement.c.
    {
        return false;
    }
Referenced by DayZCreatureAI::CommandHandler(), CommandHandler(), and DayZInfected::CommandHandler().
ModCommandHandlerInside()
bool ModCommandHandlerInside (float pDt, int pCurrentCommandID, bool pCurrentCommandFinished)
Definition at line 1800 of file dayzplayerimplement.c.
    {
        return false;
    }
Referenced by DayZCreatureAI::CommandHandler(), CommandHandler(), and DayZInfected::CommandHandler().
OnInputForRemote()
override void OnInputForRemote (ParamsReadContext ctx)
Definition at line 634 of file dayzplayerimplement.c.
    {
        int userDataType = 0;
        if (!ctx.Read(userDataType))
        {
            Error("DayZPlayer: OnInputForRemote - cannot read input type");
            return;
        }
        //Print("[inv] Input For Remote! type=" + userDataType);
        switch (userDataType)
        {
            case INPUT_UDT_WEAPON_REMOTE_EVENT:
                GetDayZPlayerInventory().OnEventForRemoteWeapon(ctx);
                break;
            case INPUT_UDT_HAND_REMOTE_EVENT:
                GetDayZPlayerInventory().OnHandEventForRemote(ctx);
                break;
            case INPUT_UDT_INVENTORY:
                GetDayZPlayerInventory().OnInputUserDataForRemote(ctx);
                break;
            default:
                Error("OnInputForRemote - unknown userDataType=" + userDataType);
                break;
        }
    }
References Error(), GetDayZPlayerInventory(), INPUT_UDT_HAND_REMOTE_EVENT, INPUT_UDT_INVENTORY, INPUT_UDT_WEAPON_REMOTE_EVENT, and Serializer::Read().
OnInputFromServer()
override void OnInputFromServer (ParamsReadContext ctx)
Definition at line 661 of file dayzplayerimplement.c.
    {
        int userDataType = 0;
        if (!ctx.Read(userDataType))
        {
            Error("DayZPlayer: OnInputFromServer - cannot read input type");
            return;
        }
        switch (userDataType)
        {
            case INPUT_UDT_INVENTORY:
                GetDayZPlayerInventory().OnServerInventoryCommand(ctx);
                break;
            default:
                Error("OnInputFromServer - unknown userDataType=" + userDataType);
                break;
        }
    }
References Error(), GetDayZPlayerInventory(), INPUT_UDT_INVENTORY, and Serializer::Read().
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
Definition at line 2577 of file dayzplayerimplement.c.
    {
        if (userDataType == INPUT_UDT_MELEE_TARGET)
        {
            EntityAI target = null;
            if (ctx.Read(target))
            {
                m_MeleeCombat.SetTargetObject(target);
            }
            vector hitPos = vector.Zero;
            if (ctx.Read(hitPos))
            {
                m_MeleeCombat.SetHitPos(hitPos);
            }
            int hitZoneIdx = -1;
            if (ctx.Read(hitZoneIdx))
            {
                m_MeleeCombat.SetHitZoneIdx(hitZoneIdx);
            }
            int finisherType = -1;
            if (ctx.Read(finisherType))
            {
                m_MeleeCombat.SetFinisherType(finisherType);
            }
            return true;
        }
        return false;
    }
References INPUT_UDT_MELEE_TARGET, m_MeleeCombat, Serializer::Read(), and vector::Zero.
OnInputUserDataReceived()
void OnInputUserDataReceived (ParamsReadContext ctx)
Input userdata
Definition at line 2565 of file dayzplayerimplement.c.
    {
        int userDataTypeParam = 0;
        if (!ctx.Read(userDataTypeParam))
        {
            Error("DayZPlayerImplement: cannot read input type");
            return;
        }
        OnInputUserDataProcess(userDataTypeParam, ctx);
    }
References Error(), OnInputUserDataProcess(), and Serializer::Read().
OnItemInHandsChanged()
override void OnItemInHandsChanged ()
Definition at line 685 of file dayzplayerimplement.c.
    {
        //Print("inv: DayZPlayerImplement::OnItemInHandsChanged: "/* + GetHumanInventory().GetEntityInHands()*/);
        StopWeaponEvent();
        GetItemAccessor().OnItemInHandsChanged();
        if (!IsAlive())
        {
            //Print("inv: DayZPlayerImplement::OnItemInHandsChanged - human not alive! calling ResetWeaponInHands");
            GetItemAccessor().ResetWeaponInHands();
        }
    }
References GetItemAccessor(), IsAlive(), and StopWeaponEvent().
Referenced by ManBase::EEItemOutOfHands().
OnJumpEnd()
void OnJumpEnd (int pLandType = 0)
Definition at line 1404 of file dayzplayerimplement.c.
    {
    }
OnJumpStart()
void OnJumpStart ()
Definition at line 1400 of file dayzplayerimplement.c.
    {
    }
OnLadder()
void OnLadder (float delta_time, HumanMovementState pState)
called every command handler tick when player is on ladder
Referenced by CommandHandler().
OnMovementChanged()
void OnMovementChanged ()
Event, called when HumanMovementState.m_iMovement changes...walk, run, sprint, etc..
Definition at line 2472 of file dayzplayerimplement.c.
    {
        switch (m_MovementState.m_LocalMovement)
        {
            case DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN:
            {
                //OnCrouchRunEnd();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
            {
                OnSprintEnd();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
            {
                //OnRunEnd();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
            {
                //OnWalkEnd();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
            {
                //OnIdleEnd();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_SLIDE:
            {
                //OnSlideEnd();
                break;
            }
        }
        switch (m_MovementState.m_iMovement)
        {
            case DayZPlayerConstants.MOVEMENTIDX_CROUCH_RUN:
            {
                //OnCrouchRunStart();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
            {
                OnSprintStart();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_RUN:
            {
                //OnRunStart();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_WALK:
            {
                //OnWalkStart();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_IDLE:
            {
                //OnIdleStart();
                break;
            }
            case DayZPlayerConstants.MOVEMENTIDX_SLIDE:
            {
                //OnSlideStart();
                break;
            }
        }
    }
References m_MovementState, OnSprintEnd(), and OnSprintStart().
Referenced by CommandHandler().
OnParticleEvent()
void OnParticleEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 2953 of file dayzplayerimplement.c.
    {
    }
OnSoundEvent()
void OnSoundEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 2920 of file dayzplayerimplement.c.
    {
        if (pEventType == "Sound")
        {
            ProcessSoundEvent(pEventType, pUserString, pUserInt);
        }
        else if (pEventType == "SoundWeapon")
        {
            ProcessWeaponEvent(pEventType, pUserString, pUserInt);
        }
        else if (pEventType == "SoundAttachment")
        {
            ProcessAttachmentEvent(pEventType, pUserString, pUserInt);
        }
        else if (pEventType == "SoundVoice")
        {
            if( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT || GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_REMOTE )
            {
                int event_id = m_PlayerSoundEventHandler.ConvertAnimIDtoEventID(pUserInt);
                if( event_id > 0 )
                {
                    PlaySoundEvent(event_id);
                    return;
                }
            }
            ProcessVoiceEvent(pEventType, pUserString, pUserInt);
        }
        else
        {
            Debug.Log("OnSoundEvent: Unknown sound event \"" + pEventType + "\"");
        }
    }
References GetInstanceType(), Debug::Log(), m_PlayerSoundEventHandler, PlaySoundEvent(), ProcessAttachmentEvent(), ProcessSoundEvent(), ProcessVoiceEvent(), and ProcessWeaponEvent().
OnSprintEnd()
void OnSprintEnd ()
Definition at line 2552 of file dayzplayerimplement.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            GetUApi().GetInputByName( "UALeanLeft"  ).Unlock();
            GetUApi().GetInputByName( "UALeanRight" ).Unlock();
        }
    }
References UAInputAPI::GetInputByName(), GetInstanceType(), GetUApi(), and UAInput::Unlock().
Referenced by OnMovementChanged().
OnSprintStart()
void OnSprintStart ()
Definition at line 2543 of file dayzplayerimplement.c.
    {
        if ( GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            GetUApi().GetInputByName( "UALeanLeft"  ).Lock();
            GetUApi().GetInputByName( "UALeanRight" ).Lock();
        }
    }
References UAInputAPI::GetInputByName(), GetInstanceType(), GetUApi(), and UAInput::Lock().
Referenced by OnMovementChanged().
OnStepEvent()
void OnStepEvent (string pEventType, string pUserString, int pUserInt)
Event Processing
Definition at line 2796 of file dayzplayerimplement.c.
    {
        /*
        Print(pEventType);
        Print(pUserString);
        Print(pUserInt);
        Print("-----------------------------");
        */
        DayZPlayerType type = GetDayZPlayerType();
        ref HumanMovementState  state = new HumanMovementState();
        GetMovementState(state);
        if(!GetGame().IsDedicatedServer())
        {
            DayZPlayerTypeStepSoundLookupTable table = type.GetStepSoundLookupTable();
            SoundObjectBuilder soundBuilder = NULL;
            if(pUserInt < 100)
            {
                string surface;
                if(pUserInt % 2 == 1)
                {
                    surface = GetSurfaceType(SurfaceAnimationBone.LeftBackLimb);
                    if (surface.Length() == 0)//if no surface found, try other leg
                        surface = GetSurfaceType(SurfaceAnimationBone.RightBackLimb);
                }
                else
                {
                    surface = GetSurfaceType(SurfaceAnimationBone.RightBackLimb);
                    if (surface.Length() == 0)//if no surface found, try other leg
                        surface = GetSurfaceType(SurfaceAnimationBone.LeftBackLimb);
                }
                if (surface.Length() != 0)
                    m_LastSurfaceUnderHash = surface.Hash();
                soundBuilder = table.GetSoundBuilder(pUserInt, state.m_iMovement, m_LastSurfaceUnderHash, GetBootsType());
            }
            else
            {
                string surface2 = GetSurfaceType();
                if (surface2.Length() != 0)
                    m_LastSurfaceUnderHash = surface2.Hash();
                soundBuilder = table.GetSoundBuilder(pUserInt, state.m_iMovement, m_LastSurfaceUnderHash, GetBootsType());
            }
            if (soundBuilder != NULL && GetGame().GetPlayer())
            {
                vector orientation = Vector(0, 0, 0);
                vector edgeLength = Vector(1.5, 3.0, 1.5);
                array<Object> excludedObjects = new array<Object>;
                array<Object> collidedObjects = new array<Object>;
                if (GetGame().IsBoxColliding(GetPosition(), orientation, edgeLength, excludedObjects, collidedObjects))
                {
                    for (int i = 0; i < collidedObjects.Count(); ++i)
                    {
                        string objectClass = collidedObjects.Get(i).GetType();
                        if (objectClass.Contains("BushSoft") || objectClass.Contains("BushHard"))
{
                            for (int j = 0; j < type.GetVegetationSounds().Count(); ++j)
{
                                VegetationSound vegetationSound = type.GetVegetationSounds().Get(j);
                                if (vegetationSound.GetAnimEventIds().Find(pUserInt) >= 0)
{
                                    SoundObjectBuilder vegSoundObjectBuilder = vegetationSound.GetSoundObjectBuilder();
                                    SoundObject vegSoundObject = vegetationSound.GetSoundObjectBuilder().BuildSoundObject();
                                    if (vegSoundObject != NULL)
{
                                        AttenuateSoundIfNecessary(vegSoundObject);
                                        PlaySound(vegSoundObject, vegSoundObjectBuilder);
                                    }
                                    break;
                                }
                            }
                            break;
                        }
                    }
                }
                SoundObject soundObject = soundBuilder.BuildSoundObject();
                if (soundObject != NULL)
                {
                    AttenuateSoundIfNecessary(soundObject);
                    PlaySound(soundObject, soundBuilder);
                }
            }
        }
        if (GetGame().IsServer())
        {
            m_StepCounter++;//move outside of server condition if needed on client as well
            float noiseMultiplier = 0;
            NoiseParams noiseParams;
            if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_ERECT || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDERECT)
                noiseParams = type.GetNoiseParamsStand();
            else if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_CROUCH || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDCROUCH)
                noiseParams = type.GetNoiseParamsCrouch();
            else if (state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE || state.m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE)
                noiseParams = type.GetNoiseParamsProne();
            else
            {
                Debug.Log(string.Format("Wrong stance, id: %1 using backup with stand stance (id: 0)", state.m_iStanceIdx));
                noiseParams = type.GetNoiseParamsStand();
            }
            noiseMultiplier =  NoiseAIEvaluate.GetNoiseMultiplier(this);
            AddNoise(noiseParams, noiseMultiplier);
            if ((m_StepCounter % PlayerConstants.CHECK_EVERY_N_STEP) == 0)
            {
                ProcessFeetDamageServer(pUserInt);
            }
        }
    }
References AddNoise(), AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), PlayerConstants::CHECK_EVERY_N_STEP, string::Contains(), Count, DayZPlayerType(), VegetationSound::GetAnimEventIds(), GetBootsType(), GetDayZPlayerType(), GetGame(), GetMovementState(), NoiseAIEvaluate::GetNoiseMultiplier(), GetPlayer(), GetPosition, DayZPlayerTypeStepSoundLookupTable::GetSoundBuilder(), VegetationSound::GetSoundObjectBuilder(), GetSurfaceType(), string::Hash(), string::Length(), Debug::Log(), m_LastSurfaceUnderHash, m_StepCounter, NoiseParams(), PlaySound(), ProcessFeetDamageServer(), SoundObject(), and Vector().
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
SyncJunctures
Definition at line 2616 of file dayzplayerimplement.c.
    {
        switch (pJunctureID)
        {
        case DayZPlayerSyncJunctures.SJ_DEATH:
            if( m_DeathAnimType == -2 )
                DayZPlayerSyncJunctures.ReadDeathParams(pCtx, m_DeathAnimType, m_DeathHitDir);
            break;
        case DayZPlayerSyncJunctures.SJ_DAMAGE_HIT:
            SyncHitInfo data = new SyncHitInfo;
            if ( DayZPlayerSyncJunctures.ReadDamageHitParamsEx(pCtx, data) && data != null)
            {
                m_SyncedHitDataArray.Insert(data);
            }
            break;
        case DayZPlayerSyncJunctures.SJ_WEAPON_RAISE_COMPLETED:
            m_ProcessWeaponRaiseCompleted = true;
            break;
        }
    }
References m_DeathAnimType, m_DeathHitDir, m_ProcessWeaponRaiseCompleted, m_SyncedHitDataArray, DayZPlayerSyncJunctures::ReadDamageHitParamsEx(), DayZPlayerSyncJunctures::ReadDeathParams(), DayZPlayerSyncJunctures::SJ_DAMAGE_HIT, DayZPlayerSyncJunctures::SJ_DEATH, and DayZPlayerSyncJunctures::SJ_WEAPON_RAISE_COMPLETED.
OverrideShootFromCamera()
void OverrideShootFromCamera (bool pState)
Definition at line 190 of file dayzplayerimplement.c.
    {
        m_IsShootingFromCamera = pState;
    }
References m_IsShootingFromCamera.
OverrideSlidePoseAngle()
void OverrideSlidePoseAngle (float value)
movement sliding override, originally for FB gestures
Definition at line 3279 of file dayzplayerimplement.c.
    {
        if (!m_MoveSettings)
            m_MoveSettings = GetDayZPlayerType().CommandMoveSettingsW();
        if (m_MoveSettings.m_fSlidingPoseAngle != value)
        {
            //Print("Change from: " + m_MoveSettings.m_fSlidingPoseAngle);
            //Print("Change to: " + value);
            m_MoveSettings.m_fSlidingPoseAngle = value;
            StartCommand_Move(); //nescessary, re-initializes with adjusted values
        }
    }
References GetDayZPlayerType(), m_MoveSettings, and StartCommand_Move().
Referenced by ManBase::CheckAnimationOverrides().
PlaySound()
AbstractWave PlaySound (SoundObject so, SoundObjectBuilder sob)
Sounds
Definition at line 2772 of file dayzplayerimplement.c.
    {
        if (so == NULL)
        {
            //Print("PlaySound: NULL argument");
            return NULL;
        }
        so.SetPosition(GetPosition());
        AbstractWave wave = GetGame().GetSoundScene().Play3D(so, sob);
        return wave;
    }
References GetGame(), GetPosition, and CGame::GetSoundScene().
PlaySoundEvent()
bool PlaySoundEvent (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false)
Definition at line 345 of file dayzplayerimplement.c.
{};
Referenced by OnSoundEvent().
PlaySoundEventEx()
bool PlaySoundEventEx (EPlayerSoundEventID id, bool from_anim_system = false, bool is_from_server = false, int param = 0)
Definition at line 346 of file dayzplayerimplement.c.
{};
Referenced by ManBase::CheckSoundEvent(), ManBase::PlaySoundEvent(), and ManBase::RequestSoundEventEx().
ProcessAttachmentEvent()
void ProcessAttachmentEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 3016 of file dayzplayerimplement.c.
    {
        DayZPlayerType type = GetDayZPlayerType();
        DayZPlayerTypeAttachmentSoundLookupTable table = type.GetAttachmentSoundLookupTable();
        array<string> attachments = new array<string>();
        pUserString.Split(",", attachments);
        for(int i = 0; i < attachments.Count(); i++)
        {
            int attachmentHash = -1;
            if( attachments[i] == "shoulder" )
                attachmentHash = GetShoulderAttachmentType();
            else if( attachments[i] == "body" )
                attachmentHash = GetBodyAttachmentType();
            else if( attachments[i] == "back" )
                attachmentHash = GetBackAttachmentType();
            SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pUserInt, attachments[i], attachmentHash);
            if (soundBuilder != NULL)
            {
                SoundObject soundObject = soundBuilder.BuildSoundObject();
                if (soundObject != NULL)
                {
                    AttenuateSoundIfNecessary(soundObject);
                    PlaySound(soundObject, soundBuilder);
                }
            }
        }
    }
References AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetBackAttachmentType(), GetBodyAttachmentType(), GetDayZPlayerType(), GetShoulderAttachmentType(), DayZPlayerTypeAttachmentSoundLookupTable::GetSoundBuilder(), PlaySound(), SoundObject(), and string::Split().
Referenced by OnSoundEvent().
ProcessFeetDamageServer()
void ProcessFeetDamageServer (int pUserInt)
Referenced by OnStepEvent().
ProcessLiftWeapon()
void ProcessLiftWeapon ()
Definition at line 3360 of file dayzplayerimplement.c.
{};
Referenced by HandleWeapons().
ProcessSoundEvent()
void ProcessSoundEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 3080 of file dayzplayerimplement.c.
    {
        DayZPlayerType type = GetDayZPlayerType();
        DayZPlayerTypeAnimTable table = type.GetSoundTable();
        AnimSoundEvent soundEvent;
        if( table )
        {
            soundEvent = table.GetSoundEvent(pUserInt);
        }
        if(soundEvent != NULL)
        {
            if(!GetGame().IsDedicatedServer())
            {
                SoundObjectBuilder objectBuilder = soundEvent.GetSoundBuilder();
                if (GetCommand_Ladder())
                {
                    SetVariablesLadderSoundObjectBuilder(objectBuilder);
                }
                objectBuilder.UpdateEnvSoundControllers(GetPosition());
                SoundObject soundObject = objectBuilder.BuildSoundObject();
                if (soundObject != NULL)
                {
                    AttenuateSoundIfNecessary(soundObject);
                    PlaySound(soundObject, objectBuilder);
                }
            }
            if(GetGame().IsServer())
            {
                if(soundEvent.m_NoiseParams != NULL)
                    GetGame().GetNoiseSystem().AddNoise(this, soundEvent.m_NoiseParams);
            }
        }
    }
References NoiseSystem::AddNoise(), AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetCommand_Ladder(), GetDayZPlayerType(), GetGame(), CGame::GetNoiseSystem(), GetPosition, PlaySound(), SetVariablesLadderSoundObjectBuilder(), SoundObject(), and SoundObjectBuilder::UpdateEnvSoundControllers().
Referenced by DayZCreature::OnSoundEvent(), and OnSoundEvent().
ProcessVoiceEvent()
AbstractWave ProcessVoiceEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 3119 of file dayzplayerimplement.c.
    {
        DayZPlayerType type = GetDayZPlayerType();
        DayZPlayerTypeVoiceSoundLookupTable table = type.GetVoiceSoundLookupTable();
        if(!table)
            return null;
        AbstractWave wave;
        EntityAI mask = GetInventory().FindAttachment(InventorySlots.MASK);
        EntityAI head_gear = GetInventory().FindAttachment(InventorySlots.HEADGEAR);
        string category;
        if( mask || head_gear )
        {
            string category_mask;
            string category_headgear;
            int priority_mask;
            int priority_headgear;
            if(mask)
            {
                category_mask = mask.ConfigGetString("soundVoiceType");
                priority_mask = mask.ConfigGetInt("soundVoicePriority");
            }
            if(head_gear)
            {
                category_headgear = head_gear.ConfigGetString("soundVoiceType");
                priority_headgear = head_gear.ConfigGetInt("soundVoicePriority");
            }
            if(priority_headgear >= priority_mask && category_headgear != "")
            {
                category = category_headgear;
            }
            else
            {
                category = category_mask;
            }
        }
        if(category == "")
        {
            category = "none";
        }
        if(!GetGame().IsDedicatedServer())
        {
            SoundObjectBuilder soundBuilder = table.GetSoundBuilder(pUserInt, category.Hash());
            if (soundBuilder)
            {
                PlayerBase player = PlayerBase.Cast(this);
                //this code block looks super shady, but it's the only way the sounds play correctly, god knows what's going on on c++ side
                int maleVoiceType = 0;
                int femaleVoiceType = 0;
                if(player.IsMale())
                {
                    maleVoiceType = player.GetVoiceType();
                }
                else
                {
                    femaleVoiceType = player.GetVoiceType();
                }
                soundBuilder.SetVariable("male", maleVoiceType);
                soundBuilder.SetVariable("female", femaleVoiceType);
                // end of weirdness
                SoundObject soundObject = soundBuilder.BuildSoundObject();
                if (soundObject != NULL)
                {
                    AttenuateSoundIfNecessary(soundObject);
                    wave = PlaySound(soundObject, soundBuilder);
                }
            }
        }
        /*
        if(GetGame().IsServer())
        {
            NoiseParams noise_params = table.GetNoiseParams(pUserInt);
            if(noise_params != NULL)
                    GetGame().GetNoiseSystem().AddNoise(this, noise_params);
        }
        */
        return wave;
    }
References AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), DayZPlayerType(), GetDayZPlayerType(), GetGame(), DayZPlayerTypeVoiceSoundLookupTable::GetSoundBuilder(), string::Hash(), PlaySound(), SoundObjectBuilder::SetVariable(), and SoundObject().
Referenced by OnSoundEvent().
ProcessWeaponEvent()
void ProcessWeaponEvent (string pEventType, string pUserString, int pUserInt)
Definition at line 2959 of file dayzplayerimplement.c.
    {
        DayZPlayerType type = GetDayZPlayerType();
        AnimSoundEvent soundEvent = NULL;
        float quantity = 0;
        EntityAI entityInHands = GetHumanInventory().GetEntityInHands();
        if (entityInHands != NULL && entityInHands.IsInherited(ItemBase))
        {
            ItemBase item;
            Class.CastTo(item, entityInHands);
            if(item.HasQuantity())
                quantity = (float)item.GetQuantity() / (item.GetQuantityMax() - item.GetQuantityMin());
            InventoryItemType invItemType = item.GetInventoryItemType();
            soundEvent = invItemType.GetSoundEvent(pUserInt);
        }
        if (soundEvent == NULL)
        {
            quantity = 0;
            soundEvent = type.GetSoundWeaponEvent(pUserInt);
        }
        if (soundEvent != NULL)
        {
            if(!GetGame().IsDedicatedServer())
            {
                SoundObjectBuilder builder = soundEvent.GetSoundBuilder();
                builder.SetVariable("quantity", quantity);
                builder.SetVariable("interior", IsSoundInsideBuilding());
                SoundObject soundObject = builder.BuildSoundObject();
                if (soundObject != NULL)
                {
                    AttenuateSoundIfNecessary(soundObject);
                    PlaySound(soundObject, builder);
                }
            }
            if(GetGame().IsServer())
            {
                AddNoise(soundEvent.m_NoiseParams);
            }
        }
        else
        {
            //commented out, some events in animation should be processed only when some items are in hand
            //string className;
            //if (entityInHands != NULL)
            //  className = entityInHands.GetType();
            //else
            //  className = "SurvivorBase";
            //Print("OnSoundEvent: eventType: \"SoundWeapon\", Not defined event id: " + pUserInt + ", in class \"" + className + "\"");
        }
    }
References AddNoise(), AttenuateSoundIfNecessary(), SoundObjectBuilder::BuildSoundObject(), Class::CastTo(), DayZPlayerType(), GetDayZPlayerType(), GetGame(), InventoryItemType::GetSoundEvent(), CGame::IsDedicatedServer(), PlaySound(), SoundObjectBuilder::SetVariable(), and SoundObject().
Referenced by OnSoundEvent().
RequestSoundEvent()
void RequestSoundEvent (EPlayerSoundEventID id, bool from_server_and_client = false)
Referenced by EEHitBy(), House::EEOnCECreate(), and ManBase::TestSend().
RequestSoundEventEx()
void RequestSoundEventEx (EPlayerSoundEventID id, bool from_server_and_client = false, int param = 0)
Referenced by ManBase::OnHoldBreathEnd(), ManBase::OnHoldBreathExhausted(), ManBase::OnHoldBreathStart(), and ManBase::RequestSoundEvent().
ResetDeathStartTime()
void ResetDeathStartTime ()
Definition at line 414 of file dayzplayerimplement.c.
    {
        m_DeathStartTime = GetGame().GetTickTime();
    }
References GetGame(), CGame::GetTickTime(), and m_DeathStartTime.
Referenced by HandleDeath().
RunADSTimer()
void RunADSTimer ()
Definition at line 591 of file dayzplayerimplement.c.
    {
        if (!m_ADSAutomationTimer.IsRunning() && !m_ADSTimerLaunched)
        {
            m_ADSAutomationTimer.Run(PlayerConstants.WEAPON_RAISE_BLEND_DELAY,this,"SendCompleteWeaponRaiseJuncture");
            m_ADSTimerLaunched = true;
        }
    }
References m_ADSAutomationTimer, m_ADSTimerLaunched, and PlayerConstants::WEAPON_RAISE_BLEND_DELAY.
Referenced by HandleWeapons().
SendCompleteWeaponRaiseJuncture()
void SendCompleteWeaponRaiseJuncture ()
Definition at line 610 of file dayzplayerimplement.c.
    {
        ScriptJunctureData pCtx = new ScriptJunctureData;
        SendSyncJuncture(DayZPlayerSyncJunctures.SJ_WEAPON_RAISE_COMPLETED, pCtx);
    }
References SendSyncJuncture(), and DayZPlayerSyncJunctures::SJ_WEAPON_RAISE_COMPLETED.
SendDeathJuncture()
void SendDeathJuncture (int pAnimTypeDeath, float pAnimHitDirDeath)
Definition at line 445 of file dayzplayerimplement.c.
    {
        if ( m_DeathJuctureSent )
            return;
        DayZPlayerSyncJunctures.SendDeath(this, pAnimTypeDeath, pAnimHitDirDeath);
        m_DeathJuctureSent = true;
    }
References m_DeathJuctureSent, and DayZPlayerSyncJunctures::SendDeath().
Referenced by EEHitBy(), and EEKilled().
SendSoundEvent()
protected void SendSoundEvent (EPlayerSoundEventID id)
Referenced by ManBase::ProcessFeetDamageServer(), and ManBase::ProcessHandDamage().
SendSoundEventEx()
protected void SendSoundEventEx (EPlayerSoundEventID id, int param = 0)
Referenced by ManBase::RequestSoundEventEx(), and ManBase::SendSoundEvent().
SetClimbingLadderType()
void SetClimbingLadderType (string value)
Definition at line 335 of file dayzplayerimplement.c.
    {
        m_ClimbingLadderType = value;
    }
References m_ClimbingLadderType.
SetDeathDarknessLevel()
void SetDeathDarknessLevel (float duration, float tick_time)
Definition at line 587 of file dayzplayerimplement.c.
    {
    }
SetFallYDiff()
void SetFallYDiff (float value)
Definition at line 242 of file dayzplayerimplement.c.
    {
        m_FallYDiff = value;
    }
References m_FallYDiff.
SetHandheldOpticsInUse()
void SetHandheldOpticsInUse (bool state)
Definition at line 3362 of file dayzplayerimplement.c.
    {
        m_HandheldOpticsInUse = state;
    }
References m_HandheldOpticsInUse.
SetIronsights()
void SetIronsights (bool value)
Definition at line 247 of file dayzplayerimplement.c.
    {
        Weapon_Base weapon = Weapon_Base.Cast(GetHumanInventory().GetEntityInHands());
        if (weapon)
        {
            m_WasIronsight = m_CameraIronsight;
        }
        m_CameraIronsight = value;
        if (value)
        {
            HumanCommandWeapons hcw = GetCommandModifier_Weapons();
            if (hcw)
            {
                hcw.SetADS(true);
            }
        }
    }
References GetCommandModifier_Weapons(), m_CameraIronsight, m_WasIronsight, and HumanCommandWeapons::SetADS().
Referenced by ExitSights(), HandleADS(), and HandleOptic().
SetIsInThirdPerson()
void SetIsInThirdPerson (bool state)
Definition at line 210 of file dayzplayerimplement.c.
    {
        m_Camera3rdPerson = state;
    }
References m_Camera3rdPerson.
SetOptics()
void SetOptics (bool value)
Definition at line 267 of file dayzplayerimplement.c.
    {
        m_CameraOptics = value;
        if (value)
        {
            HumanCommandWeapons hcw = GetCommandModifier_Weapons();
            if (hcw)
            {
                hcw.SetADS(!m_HandheldOpticsInUse);
            }
        }
    }
References GetCommandModifier_Weapons(), m_CameraOptics, m_HandheldOpticsInUse, and HumanCommandWeapons::SetADS().
Referenced by DayZPlayerImplement(), ExitSights(), and SwitchOptics().
SetReturnToOptics()
void SetReturnToOptics (bool state)
DEPRECATED.
Definition at line 3397 of file dayzplayerimplement.c.
    {
    }
SetSuicide()
void SetSuicide (bool state)
Definition at line 3311 of file dayzplayerimplement.c.
    {
        m_Suicide = state;
    }
References m_Suicide.
SetVariablesLadderSoundObjectBuilder()
void SetVariablesLadderSoundObjectBuilder (SoundObjectBuilder soundObjectBuilder)
Definition at line 3047 of file dayzplayerimplement.c.
    {
        if (m_ClimbingLadderType == "wood")
        {
            soundObjectBuilder.SetVariable("laddertype", 1);
        }
        else
        {
            soundObjectBuilder.SetVariable("laddertype", 0);
        }
        AnimBootsType pBoots = GetBootsType();
        if (pBoots == AnimBootsType.None)
        {
            soundObjectBuilder.SetVariable("bare", 1);
            soundObjectBuilder.SetVariable("sneakers", 0);
            soundObjectBuilder.SetVariable("boots", 0);
        }
        else if (pBoots == AnimBootsType.Sneakers)
        {
            soundObjectBuilder.SetVariable("bare", 0);
            soundObjectBuilder.SetVariable("sneakers", 1);
            soundObjectBuilder.SetVariable("boots", 0);
        }
        else if (pBoots == AnimBootsType.Boots)
        {
            soundObjectBuilder.SetVariable("bare", 0);
            soundObjectBuilder.SetVariable("sneakers", 0);
            soundObjectBuilder.SetVariable("boots", 1);
        }
    }
References GetBootsType(), m_ClimbingLadderType, and SoundObjectBuilder::SetVariable().
Referenced by ProcessSoundEvent().
ShowDeadScreen()
void ShowDeadScreen (bool show, float duration)
Definition at line 465 of file dayzplayerimplement.c.
    {
        #ifdef PLATFORM_PS4
        //PSN Set multiplay state - NOT ACTIVE
        OnlineServices.SetMultiplayState(false);
        //Print("=== PLATFORM_PS4 - SetMultiplayState NOT ACTIVE [ShowDeadScreen]");
        #endif
        #ifndef NO_GUI
        if (show && IsPlayerSelected())
        {
            string message = "";
            if (!GetGame().GetMission().IsPlayerRespawning())
            {
                message = "#dayz_implement_dead";
            }
            #ifdef PLATFORM_CONSOLE
            GetGame().GetUIManager().ScreenFadeIn(duration, message, FadeColors.DARK_RED, FadeColors.WHITE);
            #else
            GetGame().GetUIManager().ScreenFadeIn(duration, message, FadeColors.BLACK, FadeColors.WHITE);
            #endif
        }
        else
        {
            GetGame().GetUIManager().ScreenFadeOut(duration);
            if (duration > 0)
                GetGame().GetCallQueue(CALL_CATEGORY_GUI).CallLater(StopDeathDarkeningEffect, duration*1000, false);
            else
                GetGame().GetCallQueue(CALL_CATEGORY_GUI).Call(StopDeathDarkeningEffect);
        }
        #endif
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GUI, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), CGame::GetUIManager(), IsPlayerSelected(), UIManager::ScreenFadeIn(), UIManager::ScreenFadeOut(), OnlineServices::SetMultiplayState(), and StopDeathDarkeningEffect().
Referenced by SimulateDeath().
ShowWeaponDebug()
void ShowWeaponDebug (bool show)
Definition at line 230 of file dayzplayerimplement.c.
    {
        if (show)
        {
            m_WeaponDebug = new WeaponDebug;
        }
        else
        {
            m_WeaponDebug = null;
        }
    }
References m_WeaponDebug.
SimulateDeath()
void SimulateDeath (bool state)
Definition at line 509 of file dayzplayerimplement.c.
    {
        float duration = DEFAULT_DYING_TIME;
        if (g_Game.GetMissionState() != DayZGame.MISSION_STATE_GAME)
            return;
        //Print("Calling simulate death in state: " + state)
        //controlls
        LockControls(state);
        //video
        if (m_KilledByHeadshot)
        {
            duration = 0;
        }
        if (state && duration > DYING_PROGRESSION_TIME && !m_IsUnconscious)
        {
            //Print("--SimulateDeath--");
            if (!m_DeathEffectTimer)
                m_DeathEffectTimer = new Timer();
            Param2<float,float> par = new Param2<float,float>(duration, DYING_PROGRESSION_TIME);
            m_DeathEffectTimer.Run(DYING_PROGRESSION_TIME, this, "SetDeathDarknessLevel", par, true);
        }
        if (state)
            ShowDeadScreen(state, duration);
        else
            ShowDeadScreen(state, 0);
        //audio
        if (state)
        {
            GetGame().GetSoundScene().SetSoundVolume(0,0);
            GetGame().GetSoundScene().SetSpeechExVolume(0,0);
            GetGame().GetSoundScene().SetMusicVolume(0,0);
            GetGame().GetSoundScene().SetVOIPVolume(0,0);
            GetGame().GetSoundScene().SetRadioVolume(0,0);
        }
    }
References DayZGame(), DEFAULT_DYING_TIME, DYING_PROGRESSION_TIME, g_Game, GetGame(), CGame::GetSoundScene(), LockControls(), m_DeathEffectTimer, m_IsUnconscious, and ShowDeadScreen().
Referenced by ManBase::CheckDeath().
StopADSTimer()
void StopADSTimer ()
Definition at line 600 of file dayzplayerimplement.c.
    {
        if (m_ADSAutomationTimer && m_ADSAutomationTimer.IsRunning())
        {
            m_ADSAutomationTimer.Stop();
        }
        m_ADSTimerLaunched = false;
        //m_WeaponRaiseCompleted = false;
    }
References m_ADSAutomationTimer, and m_ADSTimerLaunched.
Referenced by CompleteWeaponRaise(), HandleADS(), and HandleWeapons().
StopDeathDarkeningEffect()
override void StopDeathDarkeningEffect ()
Definition at line 500 of file dayzplayerimplement.c.
    {
        if (m_DeathEffectTimer && m_DeathEffectTimer.IsRunning())
        {
            m_DeathEffectTimer.Stop();
            m_DeathEffectTimer = null;
        }
    }
References m_DeathEffectTimer.
Referenced by ShowDeadScreen().
StopHandEvent()
void StopHandEvent ()
Definition at line 1408 of file dayzplayerimplement.c.
    {
        GetDayZPlayerInventory().CancelHandEvent();
    }
References GetDayZPlayerInventory().
Referenced by ManBase::BrokenLegForceProne().
StopWeaponEvent()
void StopWeaponEvent ()
Definition at line 1413 of file dayzplayerimplement.c.
    {
        GetDayZPlayerInventory().CancelWeaponEvent();
    }
References GetDayZPlayerInventory().
Referenced by OnItemInHandsChanged().
SwitchOptics()
void SwitchOptics (ItemOptics optic, bool state)
Definition at line 310 of file dayzplayerimplement.c.
    {
        if (optic)
        {
            if (state)
            {
                if (optic.HasEnergyManager())
                    optic.GetCompEM().SwitchOn();
                optic.EnterOptics();
                optic.OnOpticEnter();
            }
            else
            {
                optic.ExitOptics();
                optic.OnOpticExit();
                if (optic.HasEnergyManager())
                    optic.GetCompEM().SwitchOff();
            }
        }
        if (m_CameraOptics != state)
        {
            SetOptics(state);
        }
    }
References m_CameraOptics, and SetOptics().
Referenced by ExitSights(), HandleADS(), and HandleOptic().
~DayZPlayerImplement()
void ~DayZPlayerImplement ()
Definition at line 176 of file dayzplayerimplement.c.
    {
    }
Variable Documentation
DEAD_SCREEN_DELAY
const int DEAD_SCREEN_DELAY = 1000 static
Definition at line 461 of file dayzplayerimplement.c.
DEFAULT_DYING_TIME
const float DEFAULT_DYING_TIME = 2.5 static
Definition at line 462 of file dayzplayerimplement.c.
Referenced by SimulateDeath().
DYING_PROGRESSION_TIME
const float DYING_PROGRESSION_TIME = 0.05 static
Definition at line 463 of file dayzplayerimplement.c.
Referenced by SimulateDeath().
m_ADSAutomationTimer
ref Timer m_ADSAutomationTimer
Definition at line 99 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), HandleWeapons(), RunADSTimer(), and StopADSTimer().
m_ADSTimerLaunched
protected bool m_ADSTimerLaunched
Definition at line 100 of file dayzplayerimplement.c.
Referenced by RunADSTimer(), and StopADSTimer().
m_AimingFinisherStarted
protected bool m_AimingFinisherStarted = false
Definition at line 123 of file dayzplayerimplement.c.
Referenced by AimingModel().
m_AimingModel
protected ref DayZPlayerImplementAiming m_AimingModel
Definition at line 63 of file dayzplayerimplement.c.
Referenced by AimingModel(), DayZPlayerImplement(), and GetAimingModel().
m_bADS
protected bool m_bADS
Definition at line 80 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), and HandleADS().
m_Camera3rdPerson
protected bool m_Camera3rdPerson
Definition at line 78 of file dayzplayerimplement.c.
Referenced by CameraHandler(), DayZPlayerImplement(), HandleView(), IsInThirdPerson(), and SetIsInThirdPerson().
m_CameraEyeZoom
protected bool m_CameraEyeZoom
Definition at line 83 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), HandleView(), and IsEyeZoom().
m_CameraIronsight
protected bool m_CameraIronsight
Definition at line 85 of file dayzplayerimplement.c.
Referenced by CameraHandler(), HandleADS(), HandleOptic(), HandleView(), HandleWeapons(), IsInIronsights(), and SetIronsights().
m_CameraOptics
protected bool m_CameraOptics
Definition at line 86 of file dayzplayerimplement.c.
Referenced by CameraHandler(), CommandHandler(), HandleADS(), HandleOptic(), HandleView(), HandleWeapons(), IsInOptics(), SetOptics(), and SwitchOptics().
m_CameraZoomToggle
protected bool m_CameraZoomToggle
Definition at line 79 of file dayzplayerimplement.c.
Referenced by HandleView().
m_ClimbingLadderType
protected string m_ClimbingLadderType
Definition at line 113 of file dayzplayerimplement.c.
Referenced by SetClimbingLadderType(), and SetVariablesLadderSoundObjectBuilder().
m_ContinueFirearmMelee
protected bool m_ContinueFirearmMelee
Definition at line 107 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_DamageHealth
float m_DamageHealth = 0.0
Definition at line 962 of file dayzplayerimplement.c.
Referenced by HandleDamageHit().
m_DamageHitAnimType
int m_DamageHitAnimType = -1.0
Definition at line 960 of file dayzplayerimplement.c.
Referenced by HandleDamageHit().
m_DamageHitDir
float m_DamageHitDir = 0.0
Definition at line 961 of file dayzplayerimplement.c.
Referenced by ManBase::CommandHandler(), and HandleDamageHit().
m_DamageHitFullbody
bool m_DamageHitFullbody = false
HandleDamageHit
Definition at line 959 of file dayzplayerimplement.c.
Referenced by HandleDamageHit().
m_DeathAnimType
int m_DeathAnimType = -2
HandleDeath
Definition at line 358 of file dayzplayerimplement.c.
Referenced by HandleDeath(), and OnSyncJuncture().
m_DeathDarkeningCurrentTime
protected float m_DeathDarkeningCurrentTime
Definition at line 88 of file dayzplayerimplement.c.
Referenced by ManBase::SetDeathDarknessLevel().
m_DeathEffectTimer
ref Timer m_DeathEffectTimer
Definition at line 98 of file dayzplayerimplement.c.
Referenced by ManBase::SetDeathDarknessLevel(), SimulateDeath(), and StopDeathDarkeningEffect().
m_DeathHitDir
float m_DeathHitDir = 0
Definition at line 359 of file dayzplayerimplement.c.
Referenced by HandleDeath(), and OnSyncJuncture().
m_DeathJuctureSent
bool m_DeathJuctureSent = false
Definition at line 362 of file dayzplayerimplement.c.
Referenced by SendDeathJuncture().
m_DeathSimulationTimeout
const float m_DeathSimulationTimeout = 10.0 static
Definition at line 360 of file dayzplayerimplement.c.
Referenced by HandleDeath().
m_DeathStartTime
float m_DeathStartTime = 0.0
Definition at line 361 of file dayzplayerimplement.c.
Referenced by HandleDeath(), and ResetDeathStartTime().
m_DebugDirectionVal
float m_DebugDirectionVal = -180
VKOSTIK - tady dat 0 misto -1.
Definition at line 2176 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_DebugTypeVal
bool m_DebugTypeVal = false
Definition at line 2177 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_DebugWeaponChangeItem
string m_DebugWeaponChangeItem
Definition at line 2180 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_DebugWeaponChangeShowSlot
int m_DebugWeaponChangeShowSlot
Definition at line 2181 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_DebugWeaponChangeStage
int m_DebugWeaponChangeStage = 0
Definition at line 2179 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_FallDamage
protected ref DayZPlayerImplementFallDamage m_FallDamage
Definition at line 69 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_FallYDiff
protected float m_FallYDiff
Definition at line 72 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and SetFallYDiff().
m_FightEndBlendTimer
ref Timer m_FightEndBlendTimer
Definition at line 101 of file dayzplayerimplement.c.
Referenced by ManBase::RunFightBlendTimer().
m_fLastHeadingDiff
float m_fLastHeadingDiff = 0
This HeadingModel
Definition at line 1225 of file dayzplayerimplement.c.
Referenced by HeadingModel(), and ManBase::HeadingModel().
m_HandheldOpticsInUse
protected bool m_HandheldOpticsInUse
Definition at line 115 of file dayzplayerimplement.c.
Referenced by CommandHandler(), HandleADS(), IsHandheldOpticsInUse(), SetHandheldOpticsInUse(), and SetOptics().
m_isFBsymptomPlaying
bool m_isFBsymptomPlaying
Definition at line 114 of file dayzplayerimplement.c.
Referenced by IsFBSymptomPlaying().
m_IsFireWeaponRaised
protected bool m_IsFireWeaponRaised
Definition at line 76 of file dayzplayerimplement.c.
Referenced by ManBase::CommandHandler(), DayZPlayerImplement(), HandleADS(), HandleWeapons(), and IsFireWeaponRaised().
m_IsRaised
protected bool m_IsRaised
Definition at line 75 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and IsRaised().
m_IsShootingFromCamera
protected bool m_IsShootingFromCamera
Definition at line 90 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), IsShootingFromCamera(), and OverrideShootFromCamera().
m_IsTryingHoldBreath
protected bool m_IsTryingHoldBreath
Definition at line 89 of file dayzplayerimplement.c.
Referenced by HandleWeapons(), and IsTryingHoldBreath().
m_IsUnconscious
protected bool m_IsUnconscious
Definition at line 93 of file dayzplayerimplement.c.
Referenced by CameraHandler(), ManBase::CommandHandler(), ManBase::IsUnconscious(), and SimulateDeath().
m_JumpClimb
protected ref DayZPlayerImplementJumpClimb m_JumpClimb
Definition at line 68 of file dayzplayerimplement.c.
Referenced by CameraHandler(), CommandHandler(), DayZPlayerImplement(), and ManBase::IsJumpInProgress().
m_LastBackSoundTime
int m_LastBackSoundTime
Definition at line 1784 of file dayzplayerimplement.c.
Referenced by HandleView().
m_LastBackSoundTime2
int m_LastBackSoundTime2
Definition at line 1785 of file dayzplayerimplement.c.
Referenced by HandleView().
m_LastCommandBeforeUnconscious
protected int m_LastCommandBeforeUnconscious
Definition at line 96 of file dayzplayerimplement.c.
Referenced by CommandHandler(), ManBase::CommandHandler(), and ManBase::OnUnconsciousStart().
m_LastHeadingAngle
float m_LastHeadingAngle
Definition at line 1783 of file dayzplayerimplement.c.
Referenced by HandleView().
m_LastHeadingAngleBlock
float m_LastHeadingAngleBlock
Definition at line 1781 of file dayzplayerimplement.c.
Referenced by HandleView().
m_LastHeadingAngleBlock2
float m_LastHeadingAngleBlock2
Definition at line 1782 of file dayzplayerimplement.c.
Referenced by HandleView().
m_LastSurfaceUnderHash
protected int m_LastSurfaceUnderHash
Definition at line 111 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), and OnStepEvent().
m_LiftWeapon_player
protected bool m_LiftWeapon_player
Definition at line 108 of file dayzplayerimplement.c.
Referenced by CameraHandler(), ManBase::CheckLiftWeapon(), HandleADS(), HandleView(), HandleWeapons(), ManBase::IsLiftWeapon(), ManBase::ProcessLiftWeapon(), and ManBase::SendLiftWeaponSync().
m_MeleeCombat
protected ref DayZPlayerImplementMeleeCombat m_MeleeCombat
Definition at line 64 of file dayzplayerimplement.c.
Referenced by DamageHands(), DayZPlayerImplement(), ManBase::EOnPostFrame(), EvaluateFinisherAttack(), EvaluateHit(), EvaluateHit_Common(), EvaluateHit_NonAlignableObjects(), EvaluateHit_Player(), GetMeleeCombat(), GetTargetData(), HandleComboHit(), HandleHitEvent(), HandleInitialFirearmMelee(), HandleInitialMeleeErc(), HandleProneKick(), HandleSprintAttack(), Init(), IsShortDistance(), and OnInputUserDataProcess().
m_MeleeFightLogic
protected ref DayZPlayerMeleeFightLogic_LightHeavy m_MeleeFightLogic
Definition at line 65 of file dayzplayerimplement.c.
Referenced by CommandHandler(), DayZPlayerImplement(), EvaluateDamageHitAnimation(), and GetMeleeFightLogic().
m_MovementState
DayZPlayerCommandDeathCallback m_MovementState = new HumanMovementState()
cached ptr for movement state
Referenced by AimingModel(), ManBase::BrokenLegForceProne(), ManBase::BrokenLegWalkShock(), CameraHandler(), CanClimb(), CanJump(), CommandHandler(), ManBase::CommandHandler(), InjurySoundHandlerBase::DetermineInjuryZone(), EvaluateDamageHitAnimation(), ManBase::GetFeetDamageMoveModifier(), HandleADS(), HandleDamageHit(), HandleView(), HandleWeapons(), HeadingModel(), ManBase::IsClimbing(), ManBase::IsClimbingLadder(), ManBase::IsFalling(), ManBase::IsInProne(), ManBase::IsInRasedProne(), ManBase::IsInVehicle(), ManBase::IsLeaning(), ManBase::IsSprinting(), ManBase::IsSwimming(), ManBase::OnCommandHandlerTick(), OnMovementChanged(), DayZPlayerCameraBase::OnUpdate(), and ManBase::UpdateBrokenLegs().
m_MoveSettings
protected SHumanCommandMoveSettings m_MoveSettings
Definition at line 71 of file dayzplayerimplement.c.
Referenced by OverrideSlidePoseAngle().
m_NextVoNNoiseTime
protected int m_NextVoNNoiseTime
Definition at line 118 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_PlayerSelected
protected bool m_PlayerSelected
Definition at line 91 of file dayzplayerimplement.c.
Referenced by ManBase::Init(), IsPlayerSelected(), and ManBase::OnSelectPlayer().
m_PlayerSoundEventHandler
protected ref PlayerSoundEventHandler m_PlayerSoundEventHandler
Definition at line 70 of file dayzplayerimplement.c.
Referenced by ManBase::GetPlayerSoundEventHandler(), ManBase::OnCommandHandlerTick(), ManBase::OnPlayerLoaded(), OnSoundEvent(), and ManBase::PlaySoundEventEx().
m_ProcessFirearmMeleeHit
protected bool m_ProcessFirearmMeleeHit
Definition at line 106 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_ProcessLiftWeapon
protected bool m_ProcessLiftWeapon
Definition at line 109 of file dayzplayerimplement.c.
Referenced by ManBase::ProcessLiftWeapon(), and ManBase::SetLiftWeapon().
m_ProcessLiftWeaponState
protected bool m_ProcessLiftWeaponState
Definition at line 110 of file dayzplayerimplement.c.
Referenced by ManBase::ProcessLiftWeapon(), and ManBase::SetLiftWeapon().
m_ProcessWeaponRaiseCompleted
protected bool m_ProcessWeaponRaiseCompleted
Definition at line 81 of file dayzplayerimplement.c.
Referenced by HandleWeapons(), and OnSyncJuncture().
m_RaiseStarted
protected bool m_RaiseStarted = false
Definition at line 122 of file dayzplayerimplement.c.
Referenced by AimingModel().
m_ResetADS
protected bool m_ResetADS
Definition at line 116 of file dayzplayerimplement.c.
Referenced by HandleADS(), ManBase::OnSyncJuncture(), and ManBase::RequestResetADSSync().
m_ShouldBeUnconscious
protected bool m_ShouldBeUnconscious
Definition at line 94 of file dayzplayerimplement.c.
Referenced by ManBase::CommandHandler(), and ManBase::OnSyncJuncture().
m_ShouldReload
protected bool m_ShouldReload
Definition at line 77 of file dayzplayerimplement.c.
Referenced by HandleWeapons().
m_SoundOffset
float m_SoundOffset
Definition at line 1786 of file dayzplayerimplement.c.
Referenced by HandleView().
m_SprintedTime
protected float m_SprintedTime
Definition at line 73 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_SprintFull
protected bool m_SprintFull
Definition at line 74 of file dayzplayerimplement.c.
Referenced by CommandHandler(), DayZPlayerImplement(), and IsSprintFull().
m_StepCounter
protected int m_StepCounter
Definition at line 117 of file dayzplayerimplement.c.
Referenced by OnStepEvent().
m_Suicide
protected bool m_Suicide
Definition at line 92 of file dayzplayerimplement.c.
Referenced by CommitedSuicide(), HandleDeath(), and SetSuicide().
m_Swimming
protected ref DayZPlayerImplementSwimming m_Swimming
Definition at line 66 of file dayzplayerimplement.c.
Referenced by CommandHandler(), and DayZPlayerImplement().
m_SyncedHitDataArray
protected ref array<ref SyncHitInfo> m_SyncedHitDataArray
Definition at line 119 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), HandleDamageHit(), and OnSyncJuncture().
m_TestDamageCounter
float m_TestDamageCounter = -1
This is Debug functionality
Definition at line 2175 of file dayzplayerimplement.c.
Referenced by CommandHandlerDebug().
m_Throwing
protected ref DayZPlayerImplementThrowing m_Throwing
Definition at line 67 of file dayzplayerimplement.c.
Referenced by CommandHandler(), DayZPlayerImplement(), and GetThrowing().
m_TransportCache
protected Transport m_TransportCache
Definition at line 112 of file dayzplayerimplement.c.
Referenced by CommandHandler(), ManBase::CommandHandler(), HandleDamageHit(), and HandleDeath().
m_UnconsciousDebug
bool m_UnconsciousDebug
Definition at line 95 of file dayzplayerimplement.c.
Referenced by ManBase::CommandHandler().
m_WasIronsight
protected bool m_WasIronsight
Definition at line 84 of file dayzplayerimplement.c.
Referenced by DayZPlayerImplement(), HandleADS(), and SetIronsights().
m_WeaponDebug
ref WeaponDebug m_WeaponDebug
Definition at line 97 of file dayzplayerimplement.c.
Referenced by ManBase::EOnPostFrame(), ManBase::OnCommandHandlerTick(), and ShowWeaponDebug().
m_WeaponRaiseCompleted
protected bool m_WeaponRaiseCompleted
Definition at line 82 of file dayzplayerimplement.c.
Referenced by CompleteWeaponRaise(), DayZPlayerImplement(), HandleADS(), HandleWeapons(), and IsWeaponRaiseCompleted().