DayzKode: P:/scripts/3_game/DayZ/entities/dayzanimal.c File Reference
dayzanimal.c File Reference
Classes
class AnimCommandBase
base class of all commands exposed to script to provide common functionality over animations
class DayZAnimalInputController
class DayZCreature
class DayZCreatureAI
do not process rotations !
class DayZCreatureAnimInterface
Functions
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
proto native TAnimGraphEvent BindEvent (string pEventName)
proto native TAnimGraphTag BindTag (string pTagName)
proto native TAnimGraphVariable BindVariableBool (string pVariable)
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
proto native TAnimGraphVariable BindVariableInt (string pVariable)
override bool CanBeSkinned ()
private void DayZCreatureAnimInterface ()
proto native DayZCreatureAnimInterface GetAnimInterface ()
proto native int GetCurrentAnimationInstanceUUID ()
override bool IsDayZCreature ()
override bool IsIgnoredByConstruction ()
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
proto native void PostPhys_LockRotation ()
quaternion in world space
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
bool PostPhysUpdate (float pDt)
proto native bool PrePhys_GetRotation (out float pOutRot[4])
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
script function usable in PrePhysUpdate
proto native void PrePhys_SetRotation (float pInRot[4])
proto native void PrePhys_SetTranslation (vector pInTransl)
class DayZCreatureAnimInterface RegisterAnimationEvent (string event_name, string function_name)
proto native void SetAnimationInstanceByName (string animation_instance_name, int instance_uuid, float duration)
class DayZAnimalCommandMove extends AnimCommandBase SetFlagFinished (bool pFinished)
DayZAnimalCommandScript fully scriptable command.
proto native void UpdateSimulationPrecision (int simLOD)
private void ~DayZCreatureAnimInterface ()
Variables
class DayZCreatureAI extends DayZCreature COMMANDID_ATTACK
class DayZCreatureAI extends DayZCreature COMMANDID_DEATH
class DayZCreatureAI extends DayZCreature COMMANDID_HIT
class DayZCreatureAI extends DayZCreature COMMANDID_JUMP
class DayZCreatureAI extends DayZCreature COMMANDID_MOVE
class DayZCreatureAI extends DayZCreature COMMANDID_SCRIPT
Function Documentation
BindCommand()
proto native TAnimGraphCommand RegisterAnimationEvent::BindCommand (string pCommandName)
returns command index -
BindEvent()
proto native TAnimGraphEvent RegisterAnimationEvent::BindEvent (string pEventName)
BindTag()
proto native TAnimGraphTag RegisterAnimationEvent::BindTag (string pTagName)
BindVariableBool()
proto native TAnimGraphVariable RegisterAnimationEvent::BindVariableBool (string pVariable)
BindVariableFloat()
proto native TAnimGraphVariable RegisterAnimationEvent::BindVariableFloat (string pVariable)
BindVariableInt()
proto native TAnimGraphVariable RegisterAnimationEvent::BindVariableInt (string pVariable)
CanBeSkinned()
override bool CanBeSkinned ()
Definition at line 45 of file dayzanimal.c.
    {
        return true;
    }
DayZCreatureAnimInterface()
private void RegisterAnimationEvent::DayZCreatureAnimInterface ()
Definition at line 0 of file dayzanimal.c.
GetAnimInterface()
proto native DayZCreatureAnimInterface GetAnimInterface ()
GetCurrentAnimationInstanceUUID()
proto native int GetCurrentAnimationInstanceUUID ()
IsDayZCreature()
override bool IsDayZCreature ()
Definition at line 40 of file dayzanimal.c.
    {
        return true;
    }
IsIgnoredByConstruction()
override bool IsIgnoredByConstruction ()
Definition at line 50 of file dayzanimal.c.
    {
        return IsRuined();
    }
References IsRuined().
PostPhys_GetPosition()
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
PostPhys_GetRotation()
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
PostPhys_LockRotation()
proto native void PostPhys_LockRotation ()
quaternion in world space
PostPhys_SetPosition()
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
PostPhys_SetRotation()
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
PostPhysUpdate()
bool PostPhysUpdate (float pDt)
override this ! final adjustment of physics state (after physics was applied) returns true if command continues running / false if command should end (or you can use SetFlagFinished(true))
PrePhys_GetRotation()
proto native bool PrePhys_GetRotation (out float pOutRot[4])
PrePhys_GetTranslation()
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
script function usable in PrePhysUpdate
PrePhys_SetRotation()
proto native void PrePhys_SetRotation (float pInRot[4])
PrePhys_SetTranslation()
proto native void PrePhys_SetTranslation (vector pInTransl)
RegisterAnimationEvent()
class DayZCreatureAnimInterface RegisterAnimationEvent (string event_name, string function_name)
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), ActionContinuousBaseCB::InitActionComponent(), ActionInteractBaseCB::InitActionComponent(), ActionSingleUseBaseCB::InitActionComponent(), ActionActivateTrapCB::InitActionComponent(), ActionArmExplosiveCB::InitActionComponent(), and DayZCreature::RegisterAnimEvents().
SetAnimationInstanceByName()
proto native void SetAnimationInstanceByName (string animation_instance_name, int instance_uuid, float duration)
SetFlagFinished()
class DayZAnimalCommandMove extends AnimCommandBase SetFlagFinished (bool pFinished)
DayZAnimalCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through DayZAnimal.StartCommand_Script
Note
So ideally, it is best to set up the DayZAnimalCommandScript, not create any instances and start it through DayZAnimal.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be DayZAnimal this terminates command script and shows CommandHandler(... pCurrentCommandFinished == true);
UpdateSimulationPrecision()
proto native void UpdateSimulationPrecision (int simLOD)
~DayZCreatureAnimInterface()
private void RegisterAnimationEvent::~DayZCreatureAnimInterface ()
Definition at line 1 of file dayzanimal.c.
{
Variable Documentation
COMMANDID_ATTACK
class DayZCreatureAI extends DayZCreature COMMANDID_ATTACK
COMMANDID_DEATH
class DayZCreatureAI extends DayZCreature COMMANDID_DEATH
COMMANDID_HIT
class DayZCreatureAI extends DayZCreature COMMANDID_HIT
COMMANDID_JUMP
class DayZCreatureAI extends DayZCreature COMMANDID_JUMP
COMMANDID_MOVE
class DayZCreatureAI extends DayZCreature COMMANDID_MOVE
COMMANDID_SCRIPT
class DayZCreatureAI extends DayZCreature COMMANDID_SCRIPT