var dir_4add69fd3450b22a5b2c4f280c71be3b =
[
    [ "conditions", "dir_84709d26b1e0bf5f231e1b795634383e.html", "dir_84709d26b1e0bf5f231e1b795634383e" ],
    [ "diseases", "dir_ee9ba3fc7d07a60c59a8295e63df580d.html", "dir_ee9ba3fc7d07a60c59a8295e63df580d" ],
    [ "antibiotics.c", "antibiotics_8c.html", "antibiotics_8c" ],
    [ "bloodregen.c", "bloodregen_8c.html", "bloodregen_8c" ],
    [ "boneregen.c", "boneregen_8c.html", "boneregen_8c" ],
    [ "breathvapourmdfr.c", "breathvapourmdfr_8c.html", "breathvapourmdfr_8c" ],
    [ "charcoalmdfr.c", "charcoalmdfr_8c.html", "charcoalmdfr_8c" ],
    [ "disinfectmdfr.c", "disinfectmdfr_8c.html", "disinfectmdfr_8c" ],
    [ "drowning.c", "drowning_8c.html", "drowning_8c" ],
    [ "epinephrinemdfr.c", "epinephrinemdfr_8c.html", "epinephrinemdfr_8c" ],
    [ "flies.c", "flies_8c.html", "flies_8c" ],
    [ "health.c", "health_8c.html", "health_8c" ],
    [ "healthregen.c", "healthregen_8c.html", "healthregen_8c" ],
    [ "heatcomfortmdfr.c", "heatcomfortmdfr_8c.html", "heatcomfortmdfr_8c" ],
    [ "hunger.c", "hunger_8c.html", "hunger_8c" ],
    [ "immunesystem.c", "immunesystem_8c.html", "immunesystem_8c" ],
    [ "immunityboost.c", "immunityboost_8c.html", "immunityboost_8c" ],
    [ "mask.c", "mask_8c.html", "mask_8c" ],
    [ "morphinemdfr.c", "morphinemdfr_8c.html", "morphinemdfr_8c" ],
    [ "painkillersmdfr.c", "painkillersmdfr_8c.html", "painkillersmdfr_8c" ],
    [ "saline.c", "saline_8c.html", "saline_8c" ],
    [ "shock.c", "shock_8c.html", "shock_8c" ],
    [ "shockdamage.c", "shockdamage_8c.html", "shockdamage_8c" ],
    [ "stomach.c", "stomach_8c.html", "stomach_8c" ],
    [ "testing.c", "testing_8c.html", "testing_8c" ],
    [ "thirst.c", "thirst_8c.html", "thirst_8c" ],
    [ "toxicity.c", "toxicity_8c.html", "toxicity_8c" ],
    [ "unconsciousness.c", "unconsciousness_8c.html", "unconsciousness_8c" ]
];