DayzKode: P:/scripts/4_world/DayZ/classes/virtualhud/displaystatus.c File Reference
displaystatus.c File Reference
Enumerations
enum DSLevels { WARNING = 1 , CRITICAL = 2 , BLINKING = 3 , EXTRA = 4 }
Functions
bool AreArraysSame (notnull array< int > array_a, notnull array< int > array_b)
int BitToDec (int mask, int index, int compareMask)
void Debug ()
void DeserializeElements (ref array< int > mask_array)
DisplayElementBase GetElement (eDisplayElements element_id)
void ImmediateUpdate ()
void OnRPC (ParamsReadContext ctx)
void OnScheduledTick ()
void PrintElements ()
void RegisterElement (DisplayElementBase element)
void SendRPC ()
void SerializeElements (ref array< int > mask_array)
void UpdateStatus ()
void VirtualHud (PlayerBase player)
Variables
enum DSLevels BLINKING_MINUS = 3
enum DSLevels BLINKING_PLUS = 6
enum DSLevels CRITICAL_MINUS = 2
enum DSLevels CRITICAL_PLUS = 5
ref DisplayElementBase m_Elements [NUMBER_OF_ELEMENTS]
Hud m_Hud
ref array< int > m_LastSentArray
int m_LastTick
PlayerBase m_Player
string m_System = "VirtualHud"
Mission mission
enum DSLevels NORMAL = 0
const int NUMBER_OF_ELEMENTS = eDisplayElements.COUNT
enum DSLevels NUMBER_OF_MASKS = 2
ref array< ref Param > rpcParams
enum DSLevels WARNING_MINUS = 1
enum DSLevels WARNING_PLUS = 4
Enumeration Type Documentation
DSLevels
enum DSLevels
Enumerator
WARNING
CRITICAL
BLINKING
EXTRA
Definition at line 1 of file displaystatus.c.
{
    NORMAL = 0,//no bit, default
    WARNING = 1,//first bit
    CRITICAL = 2,//second bit
    BLINKING = 3,//first + second bit
    EXTRA = 4,//third bit
}
Function Documentation
AreArraysSame()
bool AreArraysSame (notnull array< int > array_a, notnull array< int > array_b)
Definition at line 180 of file displaystatus.c.
    {
        if( array_a.Count() != array_b.Count() ) return false;
        for(int i = 0; i  <array_a.Count(); i++)
        {
            if( array_a.Get(i) != array_b.Get(i) )
            {
                return false;
            }
        }
        return true;
    }
Referenced by SendRPC().
BitToDec()
int BitToDec (int mask, int index, int compareMask)
Definition at line 151 of file displaystatus.c.
    {
        int value = mask & (compareMask << index);
        value = value >> index;
        return value;
    }
Referenced by DeserializeElements().
Debug()
void Debug ()
Definition at line 232 of file displaystatus.c.
    {
        Log("debug");
        PluginPlayerStatus  m_ModulePlayerStatus = PluginPlayerStatus.Cast(GetPlugin(PluginPlayerStatus));
        m_ModulePlayerStatus.DisplayTendency(NTFKEY_HUNGRY, 2);
    }
References GetPlugin(), Log(), m_ModulePlayerStatus, and NTFKEY_HUNGRY.
DeserializeElements()
void DeserializeElements (ref array< int > mask_array)
Definition at line 127 of file displaystatus.c.
    {
        int maskArrayIndex = 0;
        int offset = 0;
        int mask = 0;
        for(int i = 0; i < NUMBER_OF_ELEMENTS;i++)
        {
            if( GetElement(i) && !GetElement(i).IsClientOnly() )
            {
                //Log("entity> " + ToString(GetElement(i)) );
                if(offset + GetElement(i).GetNumberOfBits() > BIT_INT_SIZE)
                {
                    maskArrayIndex++;
                    offset = 0;
                }
                mask = mask_array.Get(maskArrayIndex);
                int value = BitToDec( mask, offset, GetElement(i).GetCompareMask() );
                offset = offset + GetElement(i).GetNumberOfBits();
                GetElement(i).SetValue( value );
            }
        }
    }
References BIT_INT_SIZE, BitToDec(), GetElement(), and NUMBER_OF_ELEMENTS.
Referenced by OnRPC().
GetElement()
DisplayElementBase GetElement (eDisplayElements element_id)
Definition at line 95 of file displaystatus.c.
    {
        if( element_id < 0 || element_id >= NUMBER_OF_ELEMENTS )
        {
            return null;
        }
        return m_Elements[element_id];
    }
References m_Elements, and NUMBER_OF_ELEMENTS.
Referenced by DeserializeElements(), BleedingNotfr::DisplayBadge(), FracturedLegNotfr::DisplayBadge(), HeartbeatNotfr::DisplayBadge(), PillsNotfr::DisplayBadge(), SickNotfr::DisplayBadge(), StuffedNotfr::DisplayBadge(), WetnessNotfr::DisplayBadge(), BloodNotfr::DisplayTendency(), HealthNotfr::DisplayTendency(), HungerNotfr::DisplayTendency(), ThirstNotfr::DisplayTendency(), WarmthNotfr::DisplayTendency(), map< Class TKey, Class TValue >::GetKeyByValue(), map< Class TKey, Class TValue >::GetKeyByValueChecked(), map< Class TKey, Class TValue >::GetValueArray(), BleedingNotfr::HideBadge(), FracturedLegNotfr::HideBadge(), HeartbeatNotfr::HideBadge(), PillsNotfr::HideBadge(), SickNotfr::HideBadge(), StuffedNotfr::HideBadge(), WetnessNotfr::HideBadge(), ImmediateUpdate(), ManBase::OnBleedingSourceAdded(), ManBase::OnBleedingSourceRemoved(), PrintElements(), SerializeElements(), and UpdateStatus().
ImmediateUpdate()
void ImmediateUpdate ()
Definition at line 193 of file displaystatus.c.
    {
        for(int i = 0; i < NUMBER_OF_ELEMENTS;i++)
        {
            DisplayElementBase element = GetElement(i);
            if( element && element.IsClientOnly() && element.IsValueChanged() ) element.UpdateHUD();
        }
    }
References GetElement(), NUMBER_OF_ELEMENTS, and DisplayElementBase::UpdateHUD().
Referenced by OnScheduledTick().
OnRPC()
void OnRPC (ParamsReadContext ctx)
Definition at line 223 of file displaystatus.c.
    {
        //Log("OnRPC called");
        array<int> mask_array = new array<int>;
        ctx.Read(mask_array);
        DeserializeElements(mask_array);
        UpdateStatus();
    }
References DeserializeElements(), Serializer::Read(), and UpdateStatus().
OnScheduledTick()
void OnScheduledTick ()
Definition at line 71 of file displaystatus.c.
    {
        if( GetGame().IsServer() )
        {
            if(GetGame().GetTime() > (m_LastTick + VIRTUAL_HUD_UPDATE_INTERVAL))
            {
                SendRPC();
                m_LastTick = GetGame().GetTime();
            }
        }
        if( !GetGame().IsDedicatedServer() )
        {
            ImmediateUpdate();
            //DisplayPresence();
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), ImmediateUpdate(), m_LastTick, SendRPC(), and VIRTUAL_HUD_UPDATE_INTERVAL.
PrintElements()
void PrintElements ()
Definition at line 159 of file displaystatus.c.
    {
        for(int i = 0; i < NUMBER_OF_ELEMENTS; i++)
        {
            PrintString(i.ToString() +": "+ GetElement(i).m_Value.ToString() );
        }
    }
References GetElement(), m_Value, NUMBER_OF_ELEMENTS, PrintString(), and string::ToString().
RegisterElement()
void RegisterElement (DisplayElementBase element)
Definition at line 88 of file displaystatus.c.
    {
        int id = element.GetType();
        m_Elements[id] = element;
        //Log("adding element:"+id.ToString());
    }
References m_Elements.
Referenced by VirtualHud().
SendRPC()
void SendRPC ()
Definition at line 167 of file displaystatus.c.
    {
        array<int> mask_array = new array<int>;
        SerializeElements(mask_array);
        if( !m_LastSentArray || !AreArraysSame(m_LastSentArray, mask_array)  )
        {
            ScriptRPC rpc = new ScriptRPC();
            rpc.Write(mask_array);
            rpc.Send(m_Player, ERPCs.RPC_SYNC_DISPLAY_STATUS, false, m_Player.GetIdentity());
            m_LastSentArray = mask_array;
        }
    }
References AreArraysSame(), m_LastSentArray, m_Player, ScriptRPC::Send(), SerializeElements(), and Serializer::Write().
Referenced by OnScheduledTick(), and Tick().
SerializeElements()
void SerializeElements (ref array< int > mask_array)
Definition at line 104 of file displaystatus.c.
    {
        int offset = 0;
        int mask = 0;
        for(int i = 0; i < NUMBER_OF_ELEMENTS; i++)
        {
            if(  GetElement(i) && !GetElement(i).IsClientOnly() )
            {
                if( (GetElement(i).GetNumberOfBits() + offset) > BIT_INT_SIZE )
                {
                    mask_array.Insert(mask);
                    offset = 0;
                    mask = 0;
                }
                mask = mask | (GetElement(i).GetValue() << offset);
                offset = offset + GetElement(i).GetNumberOfBits();
            }
        }
        mask_array.Insert(mask);
    }
References BIT_INT_SIZE, GetElement(), and NUMBER_OF_ELEMENTS.
Referenced by SendRPC().
UpdateStatus()
void UpdateStatus ()
Definition at line 210 of file displaystatus.c.
    {
        //Log("UpdateStatus called for entity: "+ToString(m_Player));
        for(int i = 0; i < NUMBER_OF_ELEMENTS; i++)
        {
            DisplayElementBase element = GetElement(i);
            if(  element && !element.IsClientOnly() && element.IsValueChanged() )
            {
                element.UpdateHUD();
            }
        }
    }
References GetElement(), NUMBER_OF_ELEMENTS, and DisplayElementBase::UpdateHUD().
Referenced by OnRPC().
VirtualHud()
void VirtualHud (PlayerBase player)
Definition at line 36 of file displaystatus.c.
    {
        m_Player        = player;
        m_LastTick      = 0;
        // !!!!!! don't add new stuff unless you really really REALLY know what you're doing !!!!!!
        RegisterElement(new BadgeStuffed(m_Player));// size 2
        RegisterElement(new BadgeWet(m_Player));// size 1
        RegisterElement(new BadgeSick(m_Player));// size 1
        RegisterElement(new BadgePills(m_Player));// size 1
        RegisterElement(new BadgePoisoned(m_Player));// size 1
        RegisterElement(new BadgeFracture(m_Player));// size 1
        RegisterElement(new TendencyHealth(m_Player));// size 6
        RegisterElement(new TendencyBlood(m_Player));// size 6
        RegisterElement(new TendencyTemperature(m_Player));// size 6
        // sum 25/32
        RegisterElement(new TendencyHunger(m_Player));// size 6
        RegisterElement(new TendencyThirst(m_Player));// size 6
        RegisterElement(new TendencyBacteria(m_Player));// size 6
        RegisterElement(new BadgeHeartbeat(m_Player));// size 2(client only)
        // sum 20/32
        RegisterElement(new ElementStance(m_Player));// size 0(client only)
        RegisterElement(new BadgeBleeding(m_Player));// size 0(client only)
        mission = GetGame().GetMission();
        if ( mission )
        {
            m_Hud = mission.GetHud();
        }
        //UpdateStatus();
    }
References GetGame(), Mission::GetHud(), CGame::GetMission(), m_Hud, m_LastTick, m_Player, mission, and RegisterElement().
Referenced by ManBase::GetVirtualHud(), ManBase::Init(), and ManBase::OnPlayerLoaded().
Variable Documentation
BLINKING_MINUS
enum DSLevels BLINKING_MINUS = 3
BLINKING_PLUS
enum DSLevels BLINKING_PLUS = 6
CRITICAL_MINUS
enum DSLevels CRITICAL_MINUS = 2
CRITICAL_PLUS
enum DSLevels CRITICAL_PLUS = 5
m_Elements
ref DisplayElementBase m_Elements[NUMBER_OF_ELEMENTS]
Definition at line 27 of file displaystatus.c.
Referenced by GetElement(), and RegisterElement().
m_Hud
Hud m_Hud
Definition at line 29 of file displaystatus.c.
Referenced by ScriptedWidgetEventHandler::ActionTargetsCursor(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), ManBase::EOnFrame(), ManBase::Init(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::ItemActionsWidget(), MissionBase::MissionGameplay(), MissionBase::OnEvent(), MissionBase::OnInit(), MissionBase::OnKeyPress(), ManBase::OnPlayerLoaded(), ManBase::OnRPC(), MissionBase::OnUpdate(), ManBase::OnVehicleSeatDriverEnter(), ManBase::OnVehicleSeatDriverLeft(), ManBase::StaminaHUDNotifier(), PluginBase::SwitchPermanentCrossHair(), ScriptedWidgetEventHandler::Update(), and VirtualHud().
m_LastSentArray
ref array<int> m_LastSentArray
Definition at line 24 of file displaystatus.c.
Referenced by SendRPC().
m_LastTick
int m_LastTick
Definition at line 30 of file displaystatus.c.
Referenced by OnScheduledTick(), ManBase::OnTick(), and VirtualHud().
m_Player
PlayerBase m_Player
Definition at line 31 of file displaystatus.c.
m_System
string m_System = "VirtualHud"
Definition at line 32 of file displaystatus.c.
mission
Mission mission
Definition at line 28 of file displaystatus.c.
Referenced by ScriptedWidgetEventHandler::Apply(), UIScriptedMenu::CharacterCreationMenu(), CheckDialogs(), CreateScriptedMenu(), PluginBase::DisplayTendency(), Icon::FlagAction(), ScriptedWidgetEventHandler::GetHud(), BaseBuildingBase::HandleRefreshers(), UIScriptedMenu::HudShow(), UIScriptedMenu::Init(), BaseBuildingBase::InsertRefresherPosition(), IsVonToggled(), Dispatcher::MissionGameplayHideInventory(), MissionLaunch(), UIScriptedMenu::NoteMenu(), OnEvent(), OnHide(), OnKeyPress(), OnKeyRelease(), OnMouseButtonPress(), OnMouseButtonRelease(), OnShow(), OnUpdate(), OnVOIPThresholdChanged(), Hud::RefreshQuickbar(), BaseBuildingBase::RemoveRefresherPosition(), SelectGamepad(), PluginBase::SetBadge(), PluginBase::SetStamina(), PluginBase::SetStance(), ShowVoiceNotification(), ScriptedWidgetEventHandler::Update(), UpdateInterval(), ManBase::UpdateLighting(), UpdateSpecialtyMeter(), VirtualHud(), UIScriptedMenu::~InGameMenuXbox(), and UIScriptedMenu::~NoteMenu().
NORMAL
@ NORMAL = 0
Definition at line 3 of file displaystatus.c.
NUMBER_OF_ELEMENTS
const int NUMBER_OF_ELEMENTS = eDisplayElements.COUNT
Definition at line 26 of file displaystatus.c.
Referenced by DeserializeElements(), GetElement(), ImmediateUpdate(), PrintElements(), SerializeElements(), and UpdateStatus().
NUMBER_OF_MASKS
enum DSLevels NUMBER_OF_MASKS = 2
rpcParams
ref array<ref Param> rpcParams
Definition at line 34 of file displaystatus.c.
WARNING_MINUS
enum DSLevels WARNING_MINUS = 1
WARNING_PLUS
enum DSLevels WARNING_PLUS = 4