DayzKode: P:/scripts/3_game/DayZ/tools/dispatcher.c File Reference
dispatcher.c File Reference
Classes
class Dispatcher
Typedefs
typedef int CallID
Functions
Param CallMethod (CallID call_id, Param params)
Dispatcher GetDispatcher ()
void SetDispatcher (Dispatcher dispatcher)
Variables
const CallID CALL_ID_HIDE_INVENTORY = 7
const CallID CALL_ID_SCENE_EDITOR_COMMAND = 6
const CallID CALL_ID_SCR_CNSL_ADD_PRINT = 3
const CallID CALL_ID_SCR_CNSL_GET_SQF_WATCHER = 4
const CallID CALL_ID_SCR_CNSL_GETSELECTEDITEM = 8
const CallID CALL_ID_SCR_CNSL_HISTORY_BACK = 1
const CallID CALL_ID_SCR_CNSL_HISTORY_NEXT = 2
const CallID CALL_ID_SCR_CNSL_SET_SQF_WATCHER_RESULT = 5
const CallID CALL_ID_SEND_LOG = 0
class Dispatcher g_Dispatcher
Typedef Documentation
CallID
typedef int CallID
Definition at line 1 of file dispatcher.c.
Function Documentation
CallMethod()
Param CallMethod (CallID call_id, Param params)
Definition at line 36 of file dispatcher.c.
{
    Dispatcher dis = GetDispatcher();
    if ( dis )
    {
        return dis.CallMethod(call_id, params);
    }
    return NULL;
}
References Dispatcher::CallMethod(), and GetDispatcher().
Referenced by Debug::LogMessage(), PluginBase::PrintLogClient(), PluginBase::SceneEditorMenuCmdPopup(), PluginBase::SceneEditorMenuCmdRefresh(), PluginBase::SceneEditorMenuCmdSave(), PluginBase::ScriptHistoryBack(), and PluginBase::ScriptHistoryNext().
GetDispatcher()
Dispatcher GetDispatcher ()
Definition at line 20 of file dispatcher.c.
{
    if ( g_Dispatcher == NULL )
    {
        //Print("[Dispatcher.h]=>GetDispatcher(): g_Dispatcher is NULL!!");
        return NULL;
    }
    return g_Dispatcher;
}
References g_Dispatcher.
Referenced by CallMethod(), and PluginDayzPlayerDebug_Weapons::OnClick().
SetDispatcher()
void SetDispatcher (Dispatcher dispatcher)
Definition at line 31 of file dispatcher.c.
{
    g_Dispatcher = dispatcher;
}
References g_Dispatcher.
Referenced by MissionBaseWorld::MissionBase(), and ~DayZGame().
Variable Documentation
CALL_ID_HIDE_INVENTORY
const CallID CALL_ID_HIDE_INVENTORY = 7
Definition at line 10 of file dispatcher.c.
Referenced by Dispatcher::CallMethod().
CALL_ID_SCENE_EDITOR_COMMAND
const CallID CALL_ID_SCENE_EDITOR_COMMAND = 6
Definition at line 9 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), PluginBase::SceneEditorMenuCmdPopup(), PluginBase::SceneEditorMenuCmdRefresh(), and PluginBase::SceneEditorMenuCmdSave().
CALL_ID_SCR_CNSL_ADD_PRINT
const CallID CALL_ID_SCR_CNSL_ADD_PRINT = 3
Definition at line 6 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), and PluginBase::PrintLogClient().
CALL_ID_SCR_CNSL_GET_SQF_WATCHER
const CallID CALL_ID_SCR_CNSL_GET_SQF_WATCHER = 4
Definition at line 7 of file dispatcher.c.
CALL_ID_SCR_CNSL_GETSELECTEDITEM
const CallID CALL_ID_SCR_CNSL_GETSELECTEDITEM = 8
Definition at line 11 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), and PluginDayzPlayerDebug_Weapons::OnClick().
CALL_ID_SCR_CNSL_HISTORY_BACK
const CallID CALL_ID_SCR_CNSL_HISTORY_BACK = 1
Definition at line 4 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), and PluginBase::ScriptHistoryBack().
CALL_ID_SCR_CNSL_HISTORY_NEXT
const CallID CALL_ID_SCR_CNSL_HISTORY_NEXT = 2
Definition at line 5 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), and PluginBase::ScriptHistoryNext().
CALL_ID_SCR_CNSL_SET_SQF_WATCHER_RESULT
const CallID CALL_ID_SCR_CNSL_SET_SQF_WATCHER_RESULT = 5
Definition at line 8 of file dispatcher.c.
CALL_ID_SEND_LOG
const CallID CALL_ID_SEND_LOG = 0
Definition at line 3 of file dispatcher.c.
Referenced by Dispatcher::CallMethod(), and Debug::LogMessage().
g_Dispatcher
class Dispatcher g_Dispatcher
Referenced by GetDispatcher(), and SetDispatcher().