DayzKode: P:/scripts/4_world/DayZ/entities/itembase/gear/consumables/easteregg.c File Reference
easteregg.c File Reference
Enumerations
enum eCaptureState {
CAPTURE = 0 , RELEASE = 1 , STASIS = 2 , CAPTUREFX = 3 ,
RELEASEFX = 4 , END
}
Functions
private void Capture (DayZCreatureAI capAnimal)
void ContactEvent (IEntity other, vector pos)
private void DestroyEg ()
void EasterEgg ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
override void EOnContact (IEntity other, Contact extra)
override void EOnTouch (IEntity other, int extra)
override void OnInventoryEnter (Man player)
override void OnInventoryExit (Man player)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
private void PlaySFX (int releaseCase=eCaptureState.CAPTURE)
private void PlayVFX ()
void RegisterSoundSetMap ()
private void Release (vector pos)
private void ResizeParticle (DayZCreatureAI capAnimal)
void ~EasterEgg ()
Variables
private const vector CAPTURE_VELOCITY = { 0, 0, 0 }
protected EffectSound m_CaptureSound
protected int m_CaptureSoundHash
private int m_CaptureState = eCaptureState.STASIS
private int m_CreatureHash = 0
protected EffectSound m_CreatureSound
protected ref map< int, string > m_CreatureSoundMap
private string m_CreatureType
protected bool m_DangerSound = false
protected Particle m_ParCapture
private float m_ParScale = 1
protected int m_ReleaseSoundHash
enum eCaptureState m_StoredCreature = null
private const float PARTICLE_SCALE_MULT = 0.1
Enumeration Type Documentation
eCaptureState
enum eCaptureState
Enumerator
CAPTURE
RELEASE
STASIS
CAPTUREFX
RELEASEFX
END
Definition at line 1 of file easteregg.c.
{
    CAPTURE = 0,
    RELEASE = 1,
    STASIS = 2,
    CAPTUREFX = 3,
    RELEASEFX = 4,
    //Keep this last value at the end, add any new states before
    END
}
Function Documentation
Capture()
private void Capture (DayZCreatureAI capAnimal)
Definition at line 157 of file easteregg.c.
    {
        if ( !IsAlive() )
        {
            if ( m_ParCapture )
                m_ParCapture.Delete();
            Delete();
            return;
        }
        m_StoredCreature = capAnimal;
        m_CreatureType = m_StoredCreature.GetType();
        m_CreatureHash = m_CreatureType.Hash();
        m_CaptureState = eCaptureState.CAPTUREFX;
        m_DangerSound = m_StoredCreature.IsDanger();
        m_CaptureSoundHash = m_StoredCreature.CaptureSound().Hash();
        m_ReleaseSoundHash = m_StoredCreature.ReleaseSound().Hash();
        //Resize particle upon capture as there is enough delay to be sure value is synced
        ResizeParticle( capAnimal );
        SetSynchDirty();
        capAnimal.Delete();
        SetQuantity( GetQuantityMax() );
        SetVelocity( this, CAPTURE_VELOCITY );
    }
References CAPTURE_VELOCITY, Delete(), GetQuantityMax(), string::Hash(), IsAlive(), m_CaptureSoundHash, m_CaptureState, m_CreatureHash, m_CreatureType, m_DangerSound, m_ParCapture, m_ReleaseSoundHash, m_StoredCreature, ResizeParticle(), SetQuantity(), and SetVelocity().
Referenced by ContactEvent().
ContactEvent()
void ContactEvent (IEntity other, vector pos)
Definition at line 61 of file easteregg.c.
    {
        switch ( m_CaptureState )
        {
            case eCaptureState.CAPTURE:
            DayZCreatureAI capAnimal = DayZCreatureAI.Cast( other );
            if ( capAnimal && capAnimal.IsAlive() )
            {
                if ( GetGame().IsServer() )
                    Capture( capAnimal );
            }
            else
                m_CaptureState = eCaptureState.STASIS; //We did not capture anything, go back to stasis
        break;
            case eCaptureState.RELEASE:
            Release( pos );
            PlayVFX();
            PlaySFX( eCaptureState.RELEASE );
        break;
            case eCaptureState.CAPTUREFX:
            case eCaptureState.RELEASEFX:
            //Intermediate state to play FX on next client side contact event
            //Creates slight delay but saves network traffic
            if ( m_CreatureHash != 0 )
            {
                //Make sure to go back in stasis
                m_CaptureState = eCaptureState.STASIS;
                SetSynchDirty();
            }
        break;
            case eCaptureState.STASIS:
            //Do nothing here, feel free to add logic for fun fumble effects when nothing happens :)
        break;
            default: //default in case state is somehow not initialized
        break;
        }
    }
References Capture(), GetGame(), m_CaptureState, m_CreatureHash, PlaySFX(), PlayVFX(), and Release().
Referenced by EOnContact(), and EOnTouch().
DestroyEg()
private void DestroyEg ()
Definition at line 405 of file easteregg.c.
    {
        Delete();
    }
References Delete().
EasterEgg()
void EasterEgg ()
Definition at line 37 of file easteregg.c.
    {
        m_CreatureType = "";
        SetEventMask( EntityEvent.CONTACT | EntityEvent.TOUCH );
        SetFlags( EntityFlags.TRIGGER, false );
        RegisterNetSyncVariableInt( "m_CaptureState", 0, eCaptureState.END );
        RegisterNetSyncVariableInt( "m_CreatureHash", 0, 0 );
        RegisterNetSyncVariableFloat( "m_ParScale", 0, 0, 0.1 );
        RegisterNetSyncVariableBool( "m_DangerSound" );
        RegisterNetSyncVariableInt( "m_CaptureSoundHash", 0, 0 );
        RegisterNetSyncVariableInt( "m_ReleaseSoundHash", 0, 0 );
        RegisterSoundSetMap();
    }
References m_CreatureType, RegisterSoundSetMap(), and SetFlags().
EEItemLocationChanged()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
Definition at line 147 of file easteregg.c.
    {
        super.EEItemLocationChanged(oldLoc, newLoc);
        //DestroyEg();
    }
EOnContact()
override void EOnContact (IEntity other, Contact extra)
Definition at line 112 of file easteregg.c.
    {
        ContactEvent( other, extra.Position );
    }
References ContactEvent(), and Contact::Position.
EOnTouch()
override void EOnTouch (IEntity other, int extra)
Definition at line 106 of file easteregg.c.
    {
        ContactEvent( other, GetPosition() );
    }
References ContactEvent(), and GetPosition.
OnInventoryEnter()
override void OnInventoryEnter (Man player)
Definition at line 137 of file easteregg.c.
    {
        //Make sure to stop particles once in inventory
        if ( GetGame().IsClient() && m_ParCapture )
        {
            m_ParCapture.Stop();
            m_ParCapture.Delete();
        }
    }
References GetGame(), m_ParCapture, and Particle::Stop().
OnInventoryExit()
override void OnInventoryExit (Man player)
Definition at line 117 of file easteregg.c.
    {
        //Do not execute on simple drop as it may cause issues
        PlayerBase player_PB = PlayerBase.Cast( player );
        if ( player_PB && player_PB.GetThrowing().IsThrowingAnimationPlaying() )
        {
            if ( m_CreatureType != "" )
                m_CaptureState = eCaptureState.RELEASE;
            else
                m_CaptureState = eCaptureState.CAPTURE;
        }
        else
        {
            m_CaptureState = eCaptureState.STASIS;
        }
        //Make sure state is properly synchronized or VFX might bug out
        SetSynchDirty();
    }
References m_CaptureState, and m_CreatureType.
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 378 of file easteregg.c.
    {
        if ( !super.OnStoreLoad( ctx, version ) )
            return false;
        if ( !ctx.Read( m_CaptureState ) )
            return false;
        if ( !ctx.Read( m_CreatureType ) )
            return false;
        if ( !ctx.Read( m_ParScale ) )
            return false;
        if ( !ctx.Read( m_DangerSound ) )
            return false;
        if ( !ctx.Read( m_CaptureSoundHash ) )
            return false;
        if ( !ctx.Read( m_ReleaseSoundHash ) )
            return false;
        return true;
    }
References m_CaptureSoundHash, m_CaptureState, m_CreatureType, m_DangerSound, m_ParScale, m_ReleaseSoundHash, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 366 of file easteregg.c.
    {
        super.OnStoreSave( ctx );
        ctx.Write( m_CaptureState );
        ctx.Write( m_CreatureType );
        ctx.Write( m_ParScale );
        ctx.Write( m_DangerSound );
        ctx.Write( m_CaptureSoundHash );
        ctx.Write( m_ReleaseSoundHash );
    }
References m_CaptureSoundHash, m_CaptureState, m_CreatureType, m_DangerSound, m_ParScale, m_ReleaseSoundHash, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 272 of file easteregg.c.
    {
        if ( m_CaptureState == eCaptureState.CAPTUREFX )
        {
            PlayVFX();
            PlaySFX();
        }
        else if ( m_CaptureState == eCaptureState.RELEASEFX )
        {
            PlayVFX();
            PlaySFX( eCaptureState.RELEASE );
        }
    }
References m_CaptureState, PlaySFX(), and PlayVFX().
PlaySFX()
private void PlaySFX (int releaseCase = eCaptureState.CAPTURE)
Definition at line 239 of file easteregg.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            string soundSet = "";
            if ( releaseCase == eCaptureState.CAPTURE )
            {
                PlaySoundSet( m_CaptureSound, "EasterEgg_Catch_SoundSet", 0, 0 );
                m_CreatureSoundMap.Find( m_CaptureSoundHash, soundSet );
                PlaySoundSet( m_CreatureSound, soundSet, 0, 0 );
            }
            else
            {
                if ( !m_DangerSound )
                {
                    PlaySoundSet( m_CaptureSound, "EasterEgg_Spawn_SoundSet", 0, 0 );
                    m_CreatureSoundMap.Find( m_ReleaseSoundHash, soundSet );
                    PlaySoundSet( m_CreatureSound, soundSet, 0, 0 );
                }
                else
                {
                    PlaySoundSet( m_CaptureSound, "EasterEgg_Spawn_Danger_SoundSet", 0, 0 );
                    m_CreatureSoundMap.Find( m_ReleaseSoundHash, soundSet );
                    PlaySoundSet( m_CreatureSound, soundSet, 0, 0 );
                }
            }
        }
    }
References GetGame(), m_CaptureSound, m_CaptureSoundHash, m_CreatureSound, m_CreatureSoundMap, m_DangerSound, m_ReleaseSoundHash, and PlaySoundSet().
Referenced by ContactEvent(), and OnVariablesSynchronized().
PlayVFX()
private void PlayVFX ()
Definition at line 212 of file easteregg.c.
    {
        if ( !GetGame().IsDedicatedServer() )
        {
            if ( !m_ParCapture && m_CaptureState != eCaptureState.STASIS )
            {
                //Ideally play a one time effect such as an explosion
                m_ParCapture = ParticleManager.GetInstance().PlayInWorld( ParticleList.EASTER_EGG_ACTIVATE, GetPosition() );
                //Resize, -1 signifies ALL emitors
                m_ParCapture.SetParameter( -1, EmitorParam.SIZE, m_ParScale );
                m_ParCapture.SetWiggle( 7, 0.3 );
            }
        }
    }
References ParticleList::EASTER_EGG_ACTIVATE, GetGame(), GetPosition, m_CaptureState, m_ParCapture, m_ParScale, ParticleManager(), Particle::SetParameter(), and Particle::SetWiggle().
Referenced by ContactEvent(), and OnVariablesSynchronized().
RegisterSoundSetMap()
void RegisterSoundSetMap ()
Definition at line 289 of file easteregg.c.
    {
        //Register all possible creature sounds in map with their respective hash
        string soundSet;
        m_CreatureSoundMap = new map<int, string>;
        //Cow sounds
        soundSet = "CattleMooA_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "CattleBellow_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Deer sounds
        soundSet = "DeerRoar_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "DeerBleat_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Goat sounds
        soundSet = "GoatBleat_A_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "GoatBleat_B_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Hare sounds
        soundSet = "HareChirp_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "HareSquawk_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Hen sounds
        soundSet = "HenCluck_X_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "HenScream_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Hog sounds
        soundSet = "HogGrunt_G_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "HogSqueal_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Sheep sounds
        soundSet = "SheepBleat_G_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "SheepBleat_E_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Wolf sounds
        soundSet = "WolfBark_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "WolfWhimper_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Zmb F sounds
        soundSet = "ZmbF_Normal_CallToArmsShort_Soundset";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "ZmbF_Normal_HeavyHit_Soundset";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Zmb M sounds
        soundSet = "ZmbM_Normal_CallToArmsShort_Soundset";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "ZmbM_Normal_HeavyHit_Soundset";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        //Bear sounds
        soundSet = "BearRoarShort_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
        soundSet = "BearSnarl_SoundSet";
        m_CreatureSoundMap.Insert( soundSet.Hash(), soundSet );
    }
References string::Hash(), and m_CreatureSoundMap.
Referenced by EasterEgg().
Release()
private void Release (vector pos)
Definition at line 185 of file easteregg.c.
    {
        if ( GetGame().IsServer() )
        {
            m_CaptureState = eCaptureState.RELEASEFX;
            m_CreatureHash = 0;
            SetSynchDirty();
            GetGame().CreateObject( m_CreatureType, pos, false, true );
            m_CreatureType = "";
            DecreaseHealth( "", "", GetMaxHealth() * 0.4 );
            SetQuantity( GetQuantityMin(), false );
            SetVelocity( this, CAPTURE_VELOCITY );
            if ( !IsAlive() )
            {
                if ( m_ParCapture )
                    m_ParCapture.Delete();
                Delete();
            }
        }
    }
References CAPTURE_VELOCITY, CGame::CreateObject(), DecreaseHealth(), Delete(), GetGame(), GetMaxHealth(), GetQuantityMin(), IsAlive(), m_CaptureState, m_CreatureHash, m_CreatureType, m_ParCapture, SetQuantity(), and SetVelocity().
ResizeParticle()
private void ResizeParticle (DayZCreatureAI capAnimal)
Definition at line 228 of file easteregg.c.
    {
        //Determine particle scale depending on captured animal scale
        vector mins, maxs;
        capAnimal.GetWorldBounds( mins, maxs );
        m_ParScale = vector.DistanceSq( mins, maxs );
        //Multiply to rescale down as fed values can be really large
        m_ParScale *= PARTICLE_SCALE_MULT;
    }
References vector::DistanceSq(), m_ParScale, and PARTICLE_SCALE_MULT.
Referenced by Capture().
~EasterEgg()
void ~EasterEgg ()
Definition at line 52 of file easteregg.c.
    {
        if ( m_ParCapture )
            m_ParCapture.Stop();
    }
References m_ParCapture, and Particle::Stop().
Variable Documentation
CAPTURE_VELOCITY
private const vector CAPTURE_VELOCITY = { 0, 0, 0 }
Definition at line 20 of file easteregg.c.
Referenced by Capture(), and Release().
m_CaptureSound
protected EffectSound m_CaptureSound
Definition at line 28 of file easteregg.c.
Referenced by PlaySFX().
m_CaptureSoundHash
protected int m_CaptureSoundHash
Definition at line 33 of file easteregg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_CaptureState
private int m_CaptureState = eCaptureState.STASIS
Definition at line 19 of file easteregg.c.
Referenced by Capture(), ContactEvent(), OnInventoryExit(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), PlayVFX(), and Release().
m_CreatureHash
private int m_CreatureHash = 0
Definition at line 18 of file easteregg.c.
Referenced by Capture(), ContactEvent(), and Release().
m_CreatureSound
protected EffectSound m_CreatureSound
Definition at line 29 of file easteregg.c.
Referenced by PlaySFX().
m_CreatureSoundMap
protected ref map<int, string> m_CreatureSoundMap
Definition at line 32 of file easteregg.c.
Referenced by PlaySFX(), and RegisterSoundSetMap().
m_CreatureType
private string m_CreatureType
Definition at line 17 of file easteregg.c.
Referenced by Capture(), EasterEgg(), OnInventoryExit(), OnStoreLoad(), OnStoreSave(), and Release().
m_DangerSound
protected bool m_DangerSound = false
Definition at line 30 of file easteregg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_ParCapture
protected Particle m_ParCapture
Definition at line 23 of file easteregg.c.
Referenced by Capture(), OnInventoryEnter(), PlayVFX(), Release(), and ~EasterEgg().
m_ParScale
private float m_ParScale = 1
Definition at line 24 of file easteregg.c.
Referenced by OnStoreLoad(), OnStoreSave(), PlayVFX(), and ResizeParticle().
m_ReleaseSoundHash
protected int m_ReleaseSoundHash
Definition at line 34 of file easteregg.c.
Referenced by Capture(), OnStoreLoad(), OnStoreSave(), and PlaySFX().
m_StoredCreature
enum eCaptureState m_StoredCreature = null
Referenced by Capture().
PARTICLE_SCALE_MULT
private const float PARTICLE_SCALE_MULT = 0.1
Definition at line 25 of file easteregg.c.
Referenced by ResizeParticle().