DayzKode: P:/scripts/4_world/DayZ/entities/itembase/edible_base.c File Reference
edible_base.c File Reference
Classes
class ItemBase
Functions
override void AfterStoreLoad ()
override bool CanBeCooked ()
override bool CanBeCookedOnStick ()
bool CanChangeToNewStage (CookingMethodType cooking_method)
override bool CanDecay ()
override bool CanHaveTemperature ()
override bool CanProcessDecay ()
void ChangeFoodStage (FoodStageType new_food_stage_type)
bool Consume (float amount, PlayerBase consumer)
void Edible_Base ()
override void EEDelete (EntityAI parent)
override void EEInit ()
override void EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
float GetCookingTime ()
override void GetDebugActions (out TSelectableActionInfoArray outputList)
float GetDecayDelta ()
float GetDecayTimer ()
static int GetFoodAgents (ItemBase item, string classname="", int food_stage=0)
static float GetFoodDigestibility (ItemBase item, string classname="", int food_stage=0)
static float GetFoodEnergy (ItemBase item, string classname="", int food_stage=0)
static float GetFoodNutritionalIndex (ItemBase item, string classname="", int food_stage=0)
FoodStage GetFoodStage ()
string GetFoodStageName (FoodStageType food_stage_type)
FoodStageType GetFoodStageType ()
static float GetFoodTotalVolume (ItemBase item, string classname="", int food_stage=0)
static float GetFoodToxicity (ItemBase item, string classname="", int food_stage=0)
static float GetFoodWater (ItemBase item, string classname="", int food_stage=0)
FoodStageType GetLastDecayStage ()
FoodStageType GetNextFoodStageType (CookingMethodType cooking_method)
static NutritionalProfile GetNutritionalProfile (ItemBase item, string classname="", int food_stage=0)
override bool IsCorpse ()
bool IsFoodBaked ()
bool IsFoodBoiled ()
bool IsFoodBurned ()
bool IsFoodDried ()
bool IsFoodRaw ()
bool IsFoodRotten ()
override bool IsFruit ()
override bool IsMeat ()
override bool IsMushroom ()
void MakeSoundsOnClient (bool soundstate)
override bool OnAction (int action_id, Man player, ParamsReadContext ctx)
void OnConsume (float amount, PlayerBase consumer)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
override void ProcessDecay (float delta, bool hasRootAsPlayer)
protected void RefreshAudio ()
protected void RemoveAudio ()
void ReplaceEdibleWithNew (string typeName)
class Edible_Base extends ItemBase ReplaceEdibleWithNewLambda (EntityAI old_item, string new_item_type, PlayerBase player)
override void SetActions ()
void SetCookingTime (float time)
protected void SoundCookingStart (string sound_name)
protected void SoundCookingStop ()
void Synchronize ()
void TransferFoodStage (notnull Edible_Base source)
void UpdateVisuals ()
Variables
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
protected float m_DecayDelta = 0.0
protected float m_DecayTimer
ref FoodStage m_FoodStage
protected FoodStageType m_LastDecayStage = FoodStageType.NONE
protected bool m_MakeCookingSounds
protected SoundOnVehicle m_SoundCooking
protected string m_SoundPlaying
const string SOUND_BAKING_DONE = "bakeDone"
const string SOUND_BAKING_START = "bake"
const string SOUND_BURNING_DONE = "burned"
Function Documentation
AfterStoreLoad()
override void ReplaceEdibleWithNewLambda::AfterStoreLoad ()
Definition at line 1020 of file edible_base.c.
CanBeCooked()
override bool ReplaceEdibleWithNewLambda::CanBeCooked ()
Definition at line 895 of file edible_base.c.
CanBeCookedOnStick()
override bool ReplaceEdibleWithNewLambda::CanBeCookedOnStick ()
Definition at line 900 of file edible_base.c.
CanChangeToNewStage()
bool ReplaceEdibleWithNewLambda::CanChangeToNewStage (CookingMethodType cooking_method)
Definition at line 1256 of file edible_base.c.
Referenced by ItemBase::ProcessDecay().
CanDecay()
override bool ReplaceEdibleWithNewLambda::CanDecay ()
Definition at line 1340 of file edible_base.c.
CanHaveTemperature()
override bool ReplaceEdibleWithNewLambda::CanHaveTemperature ()
Definition at line 1335 of file edible_base.c.
CanProcessDecay()
override bool ReplaceEdibleWithNewLambda::CanProcessDecay ()
Definition at line 1345 of file edible_base.c.
ChangeFoodStage()
void ReplaceEdibleWithNewLambda::ChangeFoodStage (FoodStageType new_food_stage_type)
Definition at line 1241 of file edible_base.c.
Referenced by Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), ItemBase::OnAction(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
Consume()
bool ReplaceEdibleWithNewLambda::Consume (float amount, PlayerBase consumer)
Definition at line 885 of file edible_base.c.
Edible_Base()
void ReplaceEdibleWithNewLambda::Edible_Base ()
Definition at line 818 of file edible_base.c.
EEDelete()
override void ReplaceEdibleWithNewLambda::EEDelete (EntityAI parent)
Definition at line 844 of file edible_base.c.
EEInit()
override void ReplaceEdibleWithNewLambda::EEInit ()
Definition at line 836 of file edible_base.c.
EEItemLocationChanged()
override void ReplaceEdibleWithNewLambda::EEItemLocationChanged (notnull InventoryLocation oldLoc, notnull InventoryLocation newLoc)
disable sounds (from cooking)
check for DirectCooking slot name
Definition at line 852 of file edible_base.c.
GetCookingTime()
float ReplaceEdibleWithNewLambda::GetCookingTime ()
Definition at line 1276 of file edible_base.c.
GetDebugActions()
override void ReplaceEdibleWithNewLambda::GetDebugActions (out TSelectableActionInfoArray outputList)
Definition at line 1540 of file edible_base.c.
GetDecayDelta()
float ReplaceEdibleWithNewLambda::GetDecayDelta ()
Definition at line 1589 of file edible_base.c.
GetDecayTimer()
float ReplaceEdibleWithNewLambda::GetDecayTimer ()
Definition at line 1584 of file edible_base.c.
GetFoodAgents()
static int ReplaceEdibleWithNewLambda::GetFoodAgents (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1136 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodDigestibility()
static float ReplaceEdibleWithNewLambda::GetFoodDigestibility (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1151 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodEnergy()
static float ReplaceEdibleWithNewLambda::GetFoodEnergy (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1075 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodNutritionalIndex()
static float ReplaceEdibleWithNewLambda::GetFoodNutritionalIndex (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1105 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodStage()
FoodStage ReplaceEdibleWithNewLambda::GetFoodStage ()
Definition at line 1029 of file edible_base.c.
Referenced by ItemBase::CanChangeToNewStage(), ItemBase::ChangeFoodStage(), ItemBase::GetCookingTime(), ItemBase::GetFoodStageName(), ItemBase::GetFoodStageType(), ItemBase::GetNextFoodStageType(), ItemBase::IsFoodBaked(), ItemBase::IsFoodBoiled(), ItemBase::IsFoodBurned(), ItemBase::IsFoodDried(), ItemBase::IsFoodRaw(), ItemBase::IsFoodRotten(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::SetCookingTime(), and ItemBase::UpdateVisuals().
GetFoodStageName()
string ReplaceEdibleWithNewLambda::GetFoodStageName (FoodStageType food_stage_type)
Definition at line 1251 of file edible_base.c.
GetFoodStageType()
FoodStageType ReplaceEdibleWithNewLambda::GetFoodStageType ()
Definition at line 1174 of file edible_base.c.
Referenced by ItemBase::CanProcessDecay(), ItemBase::OnAction(), ItemBase::ProcessDecay(), and ItemBase::RefreshAudio().
GetFoodTotalVolume()
static float ReplaceEdibleWithNewLambda::GetFoodTotalVolume (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1059 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodToxicity()
static float ReplaceEdibleWithNewLambda::GetFoodToxicity (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1121 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetFoodWater()
static float ReplaceEdibleWithNewLambda::GetFoodWater (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1090 of file edible_base.c.
Referenced by ItemBase::GetNutritionalProfile().
GetLastDecayStage()
FoodStageType ReplaceEdibleWithNewLambda::GetLastDecayStage ()
Definition at line 1594 of file edible_base.c.
GetNextFoodStageType()
FoodStageType ReplaceEdibleWithNewLambda::GetNextFoodStageType (CookingMethodType cooking_method)
Definition at line 1246 of file edible_base.c.
GetNutritionalProfile()
static NutritionalProfile ReplaceEdibleWithNewLambda::GetNutritionalProfile (ItemBase item, string classname = "", int food_stage = 0) static
Definition at line 1166 of file edible_base.c.
IsCorpse()
override bool ReplaceEdibleWithNewLambda::IsCorpse ()
Definition at line 1040 of file edible_base.c.
IsFoodBaked()
bool ReplaceEdibleWithNewLambda::IsFoodBaked ()
Definition at line 1190 of file edible_base.c.
IsFoodBoiled()
bool ReplaceEdibleWithNewLambda::IsFoodBoiled ()
Definition at line 1200 of file edible_base.c.
IsFoodBurned()
bool ReplaceEdibleWithNewLambda::IsFoodBurned ()
Definition at line 1220 of file edible_base.c.
IsFoodDried()
bool ReplaceEdibleWithNewLambda::IsFoodDried ()
Definition at line 1210 of file edible_base.c.
IsFoodRaw()
bool ReplaceEdibleWithNewLambda::IsFoodRaw ()
Definition at line 1180 of file edible_base.c.
IsFoodRotten()
bool ReplaceEdibleWithNewLambda::IsFoodRotten ()
Definition at line 1230 of file edible_base.c.
IsFruit()
override bool ReplaceEdibleWithNewLambda::IsFruit ()
Definition at line 1045 of file edible_base.c.
IsMeat()
override bool ReplaceEdibleWithNewLambda::IsMeat ()
Definition at line 1035 of file edible_base.c.
IsMushroom()
override bool ReplaceEdibleWithNewLambda::IsMushroom ()
Definition at line 1050 of file edible_base.c.
MakeSoundsOnClient()
void ReplaceEdibleWithNewLambda::MakeSoundsOnClient (bool soundstate)
Definition at line 939 of file edible_base.c.
Referenced by ItemBase::EEItemLocationChanged().
OnAction()
override bool ReplaceEdibleWithNewLambda::OnAction (int action_id, Man player, ParamsReadContext ctx)
Definition at line 1551 of file edible_base.c.
OnConsume()
void ReplaceEdibleWithNewLambda::OnConsume (float amount, PlayerBase consumer)
OnStoreLoad()
override bool ReplaceEdibleWithNewLambda::OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 992 of file edible_base.c.
OnStoreSave()
override void ReplaceEdibleWithNewLambda::OnStoreSave (ParamsWriteContext ctx)
Definition at line 978 of file edible_base.c.
OnVariablesSynchronized()
override void ReplaceEdibleWithNewLambda::OnVariablesSynchronized ()
Definition at line 918 of file edible_base.c.
ProcessDecay()
override void ReplaceEdibleWithNewLambda::ProcessDecay (float delta, bool hasRootAsPlayer)
Definition at line 1350 of file edible_base.c.
RefreshAudio()
protected void ReplaceEdibleWithNewLambda::RefreshAudio ()
Definition at line 946 of file edible_base.c.
Referenced by ItemBase::OnVariablesSynchronized().
RemoveAudio()
protected void ReplaceEdibleWithNewLambda::RemoveAudio ()
Definition at line 969 of file edible_base.c.
Referenced by ItemBase::EEDelete(), and ItemBase::OnVariablesSynchronized().
ReplaceEdibleWithNew()
void ReplaceEdibleWithNewLambda::ReplaceEdibleWithNew (string typeName)
Definition at line 1290 of file edible_base.c.
Referenced by BakedBeansCan::Open(), PeachesCan::Open(), SardinesCan::Open(), SpaghettiCan::Open(), TacticalBaconCan::Open(), TunaCan::Open(), DogFoodCan::Open(), CatFoodCan::Open(), PorkCan::Open(), Lunchmeat::Open(), UnknownFoodCan::Open(), Pajka::Open(), Pate::Open(), and BrisketSpread::Open().
ReplaceEdibleWithNewLambda()
class Edible_Base extends ItemBase ReplaceEdibleWithNewLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 1 of file edible_base.c.
{ }
Referenced by ItemBase::ReplaceEdibleWithNew().
SetActions()
override void ReplaceEdibleWithNewLambda::SetActions ()
Definition at line 1302 of file edible_base.c.
SetCookingTime()
void ReplaceEdibleWithNewLambda::SetCookingTime (float time)
Definition at line 1281 of file edible_base.c.
SoundCookingStart()
protected void ReplaceEdibleWithNewLambda::SoundCookingStart (string sound_name)
Definition at line 1310 of file edible_base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SoundCookingStop()
protected void ReplaceEdibleWithNewLambda::SoundCookingStop ()
Definition at line 1325 of file edible_base.c.
Referenced by ItemBase::RemoveAudio(), RemoveAudioVisuals(), and ItemBase::SoundCookingStart().
Synchronize()
void ReplaceEdibleWithNewLambda::Synchronize ()
Definition at line 908 of file edible_base.c.
TransferFoodStage()
void ReplaceEdibleWithNewLambda::TransferFoodStage (notnull Edible_Base source)
Definition at line 1262 of file edible_base.c.
UpdateVisuals()
void ReplaceEdibleWithNewLambda::UpdateVisuals ()
Definition at line 877 of file edible_base.c.
Variable Documentation
DIRECT_COOKING_SLOT_NAME
const string DIRECT_COOKING_SLOT_NAME = "DirectCooking"
Definition at line 803 of file edible_base.c.
Referenced by ItemBase::EEItemLocationChanged().
m_DecayDelta
protected float m_DecayDelta = 0.0
Definition at line 815 of file edible_base.c.
Referenced by ItemBase::GetDecayDelta(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_DecayTimer
protected float m_DecayTimer
Definition at line 814 of file edible_base.c.
Referenced by ItemBase::GetDecayTimer(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), PluginBase::PluginObjectsInteractionManager(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_FoodStage
ref FoodStage m_FoodStage
Definition at line 813 of file edible_base.c.
Referenced by ItemBase::Edible_Base(), and ItemBase::GetFoodStage().
m_LastDecayStage
protected FoodStageType m_LastDecayStage = FoodStageType.NONE
Definition at line 816 of file edible_base.c.
Referenced by ItemBase::GetLastDecayStage(), ItemBase::OnStoreLoad(), ItemBase::OnStoreSave(), ItemBase::ProcessDecay(), and ItemBase::TransferFoodStage().
m_MakeCookingSounds
protected bool m_MakeCookingSounds
Definition at line 810 of file edible_base.c.
Referenced by ItemBase::MakeSoundsOnClient(), ItemBase::OnVariablesSynchronized(), and ItemBase::RemoveAudio().
m_SoundCooking
protected SoundOnVehicle m_SoundCooking
Definition at line 811 of file edible_base.c.
Referenced by ItemBase::SoundCookingStart(), Inventory_Base::SoundCookingStart(), ItemBase::SoundCookingStop(), and Inventory_Base::SoundCookingStop().
m_SoundPlaying
protected string m_SoundPlaying
Definition at line 812 of file edible_base.c.
Referenced by ItemBase::Edible_Base(), ItemBase::SoundCookingStart(), Inventory_Base::SoundCookingStart(), ItemBase::SoundCookingStop(), and Inventory_Base::SoundCookingStop().
SOUND_BAKING_DONE
const string SOUND_BAKING_DONE = "bakeDone"
Definition at line 806 of file edible_base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SOUND_BAKING_START
const string SOUND_BAKING_START = "bake"
Definition at line 805 of file edible_base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().
SOUND_BURNING_DONE
const string SOUND_BURNING_DONE = "burned"
Definition at line 808 of file edible_base.c.
Referenced by ItemBase::RefreshAudio(), and RefreshAudioVisuals().