DayzKode: P:/scripts/4_world/DayZ/classes/emotemanager.c File Reference
emotemanager.c File Reference
Classes
class EmoteCB
class EmoteLauncher
class SurrenderData
Deprecated.
Functions
void AfterStoreLoad ()
bool CanPlayEmote (int id)
void ChainedDropAndKillPlayerLambda (EntityAI old_item, string new_item_type, PlayerBase player)
void CheckEmoteLockedState ()
protected void CommitSuicide ()
void ConstructData ()
void CreateBleedingEffect (int Callback_ID)
protected void CreateEmoteCallback (typename callbacktype, int id, int mask, bool fullbody)
void CreateEmoteCBFromMenu (int id, bool interrupts_same=false)
bool DetermineEmoteData (EmoteBase emote, out int callback_ID, out int stancemask, out bool is_fullbody)
Also includes a stance check for FB callbacks.
int DetermineGestureIndex ()
void EmoteManager (PlayerBase player)
void End ()
called on surrender end request end
void EndCallbackCommand ()
void EndSurrenderRequest (SurrenderData data=null)
force-ends surrender state from outside of normal flow
override void Execute (HumanInventoryWithFSM fsm_to_notify=null)
EmoteLauncher GetEmoteLauncher ()
int GetGesture ()
map< int, ref EmoteBase > GetNameEmoteMap ()
protected void HideItemInHands ()
void InterruptCallbackCommand ()
bool InterruptGestureCheck ()
bool InterruptWaterCheck ()
bool IsControllsLocked ()
bool IsEmotePlaying ()
void KillPlayer ()
void LogSuicide ()
void OnEmoteEnd ()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
protected void PickEmote (int gestureslot)
Obsolete.
bool PlayEmote (int id)
void PlaySurrenderInOut (bool state)
void SendEmoteRequestSync (int id)
void ServerRequestEmoteCancel ()
void SetEmoteLockState (bool state)
void SetGesture (int id)
protected void ShowItemInHands ()
void Update (float deltaT)
void ~EmoteManager ()
Variables
protected const int CALLBACK_CMD_END = -2
protected const int CALLBACK_CMD_GESTURE_INTERRUPT = -3
protected const int CALLBACK_CMD_INSTACANCEL = -4
protected const int CALLBACK_CMD_INVALID = -1
PluginAdminLog m_AdminLog
bool m_bEmoteIsPlaying
EmoteCB m_Callback
bool m_CancelEmote
protected bool m_controllsLocked
protected int m_CurrentGestureID
protected int m_DeferredEmoteExecution
protected ref array< ref EmoteBase > m_EmoteClassArray
protected ref array< int > m_EmoteIDs
protected ref array< int > m_EmoteInputIDs
protected bool m_EmoteLockState
protected int m_GestureID
bool m_GestureInterruptInput
ref InventoryLocation m_HandInventoryLocation
HumanInputController m_HIC
bool m_InstantCancelEmote
ref array< string > m_InterruptInputs
bool m_IsSurrendered
ItemBase m_item
protected bool m_ItemIsOn
bool m_ItemToBeCreated
protected bool m_ItemToHands
protected int m_LastMask
ref EmoteLauncher m_MenuEmote
protected bool m_MouseButtonPressed
protected ref map< int, ref EmoteBase > m_NameEmoteMap
class EmoteLauncher m_Player
protected bool m_PlayerDies
protected int m_PreviousGestureID
protected ref Timer m_ReservationTimer
protected int m_RPSOutcome
Function Documentation
AfterStoreLoad()
void AfterStoreLoad ()
Definition at line 530 of file emotemanager.c.
    {
        //failsafe, deletes helper item after fully loading character
        if ( m_Player.GetItemInHands() && SurrenderDummyItem.Cast(m_Player.GetItemInHands()) )
            m_Player.GetItemInHands().Delete();
    }
References m_Player.
CanPlayEmote()
bool CanPlayEmote (int id)
Definition at line 842 of file emotemanager.c.
    {
        //special cases
        if ( id == CALLBACK_CMD_END || id == CALLBACK_CMD_GESTURE_INTERRUPT || id == CALLBACK_CMD_INSTACANCEL )
        {
            return true;
        }
        if ( !m_Player || (!IsEmotePlaying() && m_Player.GetCommand_Action() || m_Player.GetCommandModifier_Action()) || m_Player.GetThrowing().IsThrowingModeEnabled() || m_Player.IsItemsToDelete())
        {
            return false;
        }
        ItemBase item = m_Player.GetItemInHands();
        if ( item && item.IsHeavyBehaviour() && (id != EmoteConstants.ID_EMOTE_SURRENDER) )
        {
            return false;
        }
        if ( (m_Player.GetWeaponManager() && m_Player.GetWeaponManager().IsRunning()) || (m_Player.GetActionManager() && m_Player.GetActionManager().GetRunningAction()) )
        {
            return false;
        }
        if ( m_HIC.IsWeaponRaised() || m_Player.IsRolling() || m_Player.IsClimbing() || m_Player.IsRestrainStarted() || m_Player.IsFighting() || m_Player.IsSwimming() || m_Player.IsClimbingLadder() || m_Player.IsFalling() || m_Player.IsUnconscious() || m_Player.IsJumpInProgress() )  // rework conditions into something better?
        {
            return false;
        }
        if ( m_Player.GetCommand_Vehicle() )
        {
            if ( m_Player.GetCommand_Vehicle().GetTransport() )
            {
                return false;
            }
        }
        if ( m_Player.GetCommand_Move() && m_Player.GetCommand_Move().IsOnBack() && id != EmoteConstants.ID_EMOTE_SURRENDER)
        {
            return false;
        }
        //"locks" player in surrender state
        if ( m_IsSurrendered && (id != EmoteConstants.ID_EMOTE_SURRENDER) )
        {
            return false;
        }
        if ( m_Player.GetDayZPlayerInventory().IsProcessing() )
        {
            return false;
        }
        EmoteBase emote;
        if (m_NameEmoteMap.Find(id,emote))
        {
            int callback_ID;
            int stancemask;
            bool is_fullbody;
            if ( DetermineEmoteData(emote,callback_ID,stancemask,is_fullbody) && emote.EmoteCondition(stancemask) )
            {
                return true;
            }
        }
        return false;
    }
References CALLBACK_CMD_END, CALLBACK_CMD_GESTURE_INTERRUPT, CALLBACK_CMD_INSTACANCEL, DetermineEmoteData(), EmoteBase::EmoteCondition(), EmoteConstants::ID_EMOTE_SURRENDER, IsEmotePlaying(), HumanInputController::IsWeaponRaised(), m_HIC, m_IsSurrendered, m_NameEmoteMap, and m_Player.
Referenced by OnInputUserDataProcess(), PlayEmote(), and SendEmoteRequestSync().
ChainedDropAndKillPlayerLambda()
void ChainedDropAndKillPlayerLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 1131 of file emotemanager.c.
    {
        m_Player = player;
        InventoryLocation gnd = new InventoryLocation;
        vector mtx[4];
        old_item.GetTransform(mtx);
        gnd.SetGround( old_item, mtx );
        OverrideNewLocation( gnd );
    }
References m_Player, and InventoryLocation::SetGround().
CheckEmoteLockedState()
void CheckEmoteLockedState ()
Definition at line 993 of file emotemanager.c.
    {
        if ( !m_Player.GetItemInHands() || (m_Player.GetItemInHands() && !SurrenderDummyItem.Cast(m_Player.GetItemInHands())) )
            return;
        //refreshes reservation in case of unwanted timeout
        if ( m_EmoteLockState && m_HandInventoryLocation )
        {
            m_Player.GetInventory().ExtendInventoryReservationEx( null, m_HandInventoryLocation, 10000);
        }
    }
References m_EmoteLockState, m_HandInventoryLocation, and m_Player.
CommitSuicide()
protected void CommitSuicide ()
Definition at line 659 of file emotemanager.c.
    {
        Weapon_Base weapon;
        WeaponEventBase weapon_event = new WeaponEventTrigger;
        if ( Weapon_Base.CastTo(weapon,m_Player.GetItemInHands()) )
        {
            //TODO : check multiple muzzles for shotguns, eventually
            if (weapon.CanFire())
            {
                m_Callback.RegisterAnimationEvent("Simulation_End",EmoteConstants.EMOTE_SUICIDE_SIMULATION_END);
                m_Player.SetSuicide(true);
                weapon.ProcessWeaponEvent(weapon_event);
                m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
                if (m_Player.IsAlive())
                {
                    EntityAI helm = m_Player.FindAttachmentBySlotName("Headgear");
                    if (helm && GetGame().IsServer())
                    {
                        float damage = helm.GetMaxHealth("","");
                        helm.AddHealth( "","", -damage/2);
                    }
                    GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(this.KillPlayer);
                    //LogSuicide();     // older logging
                    if ( m_AdminLog )
                    {
                        m_AdminLog.Suicide( m_Player );
                    }
                }
            }
            else
            {
                weapon.ProcessWeaponEvent(weapon_event);
                m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
            }
        }
        else if ( m_Player.GetItemInHands() && m_Player.GetItemInHands().ConfigIsExisting("suicideAnim") )
        {
            m_Callback.RegisterAnimationEvent("Death",EmoteConstants.EMOTE_SUICIDE_DEATH);
            m_Callback.RegisterAnimationEvent("Bleed",EmoteConstants.EMOTE_SUICIDE_BLEED);
            m_Callback.RegisterAnimationEvent("Simulation_End",EmoteConstants.EMOTE_SUICIDE_SIMULATION_END);
            m_Player.SetSuicide(true);
            m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
            LogSuicide();
        }
        else
        {
            m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_FINISH);
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, EmoteConstants::EMOTE_SUICIDE_BLEED, EmoteConstants::EMOTE_SUICIDE_DEATH, EmoteConstants::EMOTE_SUICIDE_SIMULATION_END, CGame::GetCallQueue(), GetGame(), KillPlayer(), LogSuicide(), m_AdminLog, m_Callback, and m_Player.
Referenced by Update().
ConstructData()
void ConstructData ()
Definition at line 187 of file emotemanager.c.
    {
        EmoteConstructor ec = new EmoteConstructor;
        if (!m_NameEmoteMap)
        {
            ec.ConstructEmotes(m_Player,m_NameEmoteMap);
            m_EmoteClassArray = new array<ref EmoteBase>;
            m_EmoteIDs = new array<int>;
            m_EmoteInputIDs = new array<int>;
            int inputID;
            int count = m_NameEmoteMap.Count();
            UAInput inp;
            for (int i = 0; i < count; i++)
            {
                m_EmoteClassArray.Insert(m_NameEmoteMap.GetElement(i));
                m_EmoteIDs.Insert(m_NameEmoteMap.GetElement(i).GetID());
                inp = GetUApi().GetInputByName(m_NameEmoteMap.GetElement(i).GetInputActionName());
                inputID = inp.ID();
                m_EmoteInputIDs.Insert(inputID);
            }
            if (m_EmoteInputIDs.Count() != m_EmoteClassArray.Count())
            {
                ErrorEx("Faulty emote data detected in 'ConstructData' method!",ErrorExSeverity.WARNING);
            }
        }
    }
References EmoteConstructor::ConstructEmotes(), ErrorEx, UAInputAPI::GetInputByName(), GetUApi(), UAInput::ID(), m_EmoteClassArray, m_EmoteIDs, m_EmoteInputIDs, m_NameEmoteMap, and m_Player.
Referenced by EmoteManager().
CreateBleedingEffect()
void CreateBleedingEffect (int Callback_ID)
Definition at line 1076 of file emotemanager.c.
    {
        if (GetGame().IsServer() && m_Player.IsAlive())
        {
            switch (Callback_ID)
            {
                case DayZPlayerConstants.CMD_SUICIDEFB_1HD :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("Neck");
                break;
                case DayZPlayerConstants.CMD_SUICIDEFB_FIREAXE :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
                break;
                case DayZPlayerConstants.CMD_SUICIDEFB_PITCHFORK :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("Spine2");
                break;
                case DayZPlayerConstants.CMD_SUICIDEFB_SWORD :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("Spine2");
                break;
                case DayZPlayerConstants.CMD_SUICIDEFB_SPEAR :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("Head");
                break;
                case DayZPlayerConstants.CMD_SUICIDEFB_WOODAXE :
                    m_Player.GetBleedingManagerServer().AttemptAddBleedingSourceBySelection("LeftForeArmRoll");
                break;
                default :
                    ErrorEx("EmoteManager.c | CreateBleedingEffect | WRONG ID",ErrorExSeverity.INFO);
                break;
            }
        }
    }
References ErrorEx, GetGame(), and m_Player.
CreateEmoteCallback()
protected void CreateEmoteCallback (typename callbacktype , int id, int mask, bool fullbody)
Definition at line 612 of file emotemanager.c.
    {
        if ( m_Player )
        {
            m_LastMask = -1;
            if (fullbody)
            {
                Class.CastTo(m_Callback, m_Player.StartCommand_Action(id,callbacktype,mask));
                m_Callback.m_IsFullbody = true;
                m_Callback.EnableCancelCondition(true);
            }
            else if (m_Player.IsPlayerInStance(mask))
            {
                m_LastMask = mask;  //character is probably not prone now
                Class.CastTo(m_Callback, m_Player.AddCommandModifier_Action(id,callbacktype));
            }
            if (m_Callback)
            {
                m_bEmoteIsPlaying = true;
                m_Callback.m_callbackID = id;
                m_Callback.m_player = m_Player;
                m_Callback.m_Manager = this;
            }
        }
    }
References Class::CastTo(), m_bEmoteIsPlaying, m_Callback, EmoteCB::m_callbackID, EmoteCB::m_IsFullbody, m_LastMask, EmoteCB::m_Manager, m_Player, and EmoteCB::m_player.
Referenced by PlayEmote(), and PlaySurrenderInOut().
CreateEmoteCBFromMenu()
void CreateEmoteCBFromMenu (int id, bool interrupts_same = false)
Definition at line 731 of file emotemanager.c.
    {
        m_MenuEmote = new EmoteLauncher(id,interrupts_same);
    }
References m_MenuEmote.
Referenced by Update().
DetermineEmoteData()
bool DetermineEmoteData (EmoteBase emote, out int callback_ID, out int stancemask, out bool is_fullbody)
Also includes a stance check for FB callbacks.
Definition at line 241 of file emotemanager.c.
    {
        if (emote.DetermineOverride(callback_ID, stancemask, is_fullbody))
        {
            return emote.EmoteFBStanceCheck(stancemask);
        }
        else if (emote.GetAdditiveCallbackUID() != 0 && m_Player.IsPlayerInStance(emote.GetStanceMaskAdditive()))
        {
            callback_ID = emote.GetAdditiveCallbackUID();
            stancemask = emote.GetStanceMaskAdditive();
            is_fullbody = false;
            return true;
        }
        else if (emote.GetFullbodyCallbackUID() != 0 && emote.EmoteFBStanceCheck(emote.GetStanceMaskFullbody()))
        {
            callback_ID = emote.GetFullbodyCallbackUID();
            stancemask = emote.GetStanceMaskFullbody();
            is_fullbody = true;
            return true;
        }
        return false;
    }
References EmoteBase::DetermineOverride(), EmoteBase::EmoteFBStanceCheck(), EmoteBase::GetAdditiveCallbackUID(), EmoteBase::GetFullbodyCallbackUID(), EmoteBase::GetStanceMaskAdditive(), EmoteBase::GetStanceMaskFullbody(), and m_Player.
Referenced by CanPlayEmote(), and PlayEmote().
DetermineGestureIndex()
int DetermineGestureIndex ()
Definition at line 226 of file emotemanager.c.
    {
        int count = m_EmoteInputIDs.Count();
        for (int i = 0; i < count; ++i)
        {
            if (GetUApi().GetInputByID(m_EmoteInputIDs[i]).LocalPress())
            {
                return m_EmoteIDs[i];
            }
        }
        return 0;
    }
References GetUApi(), m_EmoteIDs, and m_EmoteInputIDs.
Referenced by Update().
EmoteManager()
void EmoteManager (PlayerBase player)
Definition at line 145 of file emotemanager.c.
    {
        m_Player = player;
        m_HIC = m_Player.GetInputController();
        m_ItemIsOn = false;
        m_RPSOutcome = -1;
        m_DeferredEmoteExecution = CALLBACK_CMD_INVALID;
        // new input-based interrupt actions
        m_InterruptInputs = new array<string>;
        m_InterruptInputs.Insert("UAMoveForward");
        m_InterruptInputs.Insert("UAMoveBack");
        m_InterruptInputs.Insert("UATurnLeft");
        m_InterruptInputs.Insert("UATurnRight");
        m_InterruptInputs.Insert("UAMoveLeft");
        m_InterruptInputs.Insert("UAMoveRight");
        m_InterruptInputs.Insert("UAStand");
        m_InterruptInputs.Insert("UACrouch");
        m_InterruptInputs.Insert("UAProne");
        m_InterruptInputs.Insert("UAGetOver");
        // end of new input-based interrupt actions
        m_HandInventoryLocation = new InventoryLocation;
        m_HandInventoryLocation.SetHands(m_Player,null);
        if (GetGame().IsServer())
        {
            m_AdminLog = PluginAdminLog.Cast( GetPlugin(PluginAdminLog) );
        }
        m_ReservationTimer = new Timer();
        m_ReservationTimer.Run(8,this,"CheckEmoteLockedState",NULL,true);
        ConstructData();
    }
References CALLBACK_CMD_INVALID, ConstructData(), GetGame(), GetPlugin(), m_AdminLog, m_DeferredEmoteExecution, m_HandInventoryLocation, m_HIC, m_InterruptInputs, m_ItemIsOn, m_Player, m_ReservationTimer, m_RPSOutcome, and InventoryLocation::SetHands().
Referenced by ManBase::Init().
End()
void ChainedDropAndKillPlayerLambda::End ()
called on surrender end request end
Referenced by DeactivateFishing(), AnimatedActionBase::Interrupt(), FirearmActionDetachMagazine::OnStageStart(), ActionGetInTransport::OnUpdate(), OnUpdate(), ActionSwitchSeats::OnUpdate(), FirearmActionBase::OnUpdate(), and Pulling().
EndCallbackCommand()
void EndCallbackCommand ()
Definition at line 751 of file emotemanager.c.
    {
        if (m_CurrentGestureID == EmoteConstants.ID_EMOTE_DANCE)
        {
            m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
        }
        else
        {
            m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
        }
        if (m_MenuEmote)
            m_MenuEmote = null;
        m_DeferredEmoteExecution = CALLBACK_CMD_INVALID;
    }
References CALLBACK_CMD_INVALID, EmoteConstants::ID_EMOTE_DANCE, m_Callback, m_CurrentGestureID, m_DeferredEmoteExecution, and m_MenuEmote.
Referenced by SendEmoteRequestSync(), and Update().
EndSurrenderRequest()
void EndSurrenderRequest (SurrenderData data = null)
force-ends surrender state from outside of normal flow
Definition at line 1006 of file emotemanager.c.
    {
        if (m_IsSurrendered && data)
        {
            SetEmoteLockState(false);
            if (m_Player.GetItemInHands())
                m_Player.GetItemInHands().Delete();
            m_IsSurrendered = false;
            data.End();
        }
    }
References m_IsSurrendered, m_Player, and SetEmoteLockState().
Referenced by Update().
Execute()
override void Execute (HumanInventoryWithFSM fsm_to_notify = null)
Definition at line 1142 of file emotemanager.c.
    {
        if (PrepareLocations())
        {
            vector transform[4];
            m_Player.GetInventory().TakeToDst(InventoryMode.SERVER, m_OldLocation, m_NewLocation);
            m_Player.OnItemInHandsChanged();
        }
        m_Player.SetHealth(0);
        hndDebugPrint("[syncinv] player=" + Object.GetDebugName(m_Player) + " STS = " + m_Player.GetSimulationTimeStamp() + " ChainedDropAndKillPlayerLambda");
    }
References hndDebugPrint(), and m_Player.
GetEmoteLauncher()
EmoteLauncher GetEmoteLauncher ()
Definition at line 736 of file emotemanager.c.
    {
        return m_MenuEmote;
    }
References m_MenuEmote.
GetGesture()
int GetGesture ()
Definition at line 221 of file emotemanager.c.
    {
        return m_GestureID;
    }
References m_GestureID.
GetNameEmoteMap()
map< int, ref EmoteBase > GetNameEmoteMap ()
Definition at line 1071 of file emotemanager.c.
    {
        return m_NameEmoteMap;
    }
References m_NameEmoteMap.
HideItemInHands()
protected void HideItemInHands ()
Definition at line 640 of file emotemanager.c.
    {
        m_item = m_Player.GetItemInHands();
        if(m_Callback && m_item)
        {
            m_Player.TryHideItemInHands(true);
            //m_ItemToHands = true;
        }
    }
References m_Callback, m_item, and m_Player.
Referenced by PlayEmote().
InterruptCallbackCommand()
void InterruptCallbackCommand ()
Definition at line 741 of file emotemanager.c.
    {
        m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
        if (m_MenuEmote)
            m_MenuEmote = null;
        //if (!m_CancelEmote)
            m_DeferredEmoteExecution = CALLBACK_CMD_INVALID;
    }
References CALLBACK_CMD_INVALID, m_Callback, m_DeferredEmoteExecution, and m_MenuEmote.
Referenced by Update().
InterruptGestureCheck()
bool InterruptGestureCheck ()
Definition at line 1030 of file emotemanager.c.
    {
        //interrupts any callback if restrain action is in progress, takes priority
        if (!m_Callback.m_IsFullbody)
            return false;
        UAInput inp;
        for (int idx = 0; idx < m_InterruptInputs.Count(); idx++)
        {
            inp = GetUApi().GetInputByName(m_InterruptInputs[idx]);
            if (inp && inp.LocalPress())
            {
                return true;
            }
        }
        return false;
    }
References UAInputAPI::GetInputByName(), GetUApi(), UAInput::LocalPress(), m_Callback, m_InterruptInputs, and EmoteCB::m_IsFullbody.
Referenced by Update().
InterruptWaterCheck()
bool InterruptWaterCheck ()
Definition at line 1049 of file emotemanager.c.
    {
        vector wl;
        int level = DayZPlayerUtils.CheckWaterLevel(m_Player,wl);
        if (m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE | DayZPlayerConstants.STANCEMASK_PRONE) && level > EWaterLevels.LEVEL_LOW)
        {
            return true;
        }
        else if (m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_CROUCH | DayZPlayerConstants.STANCEIDX_RAISEDCROUCH) && level > EWaterLevels.LEVEL_CROUCH)
        {
            return true;
        }
        return m_Player.GetModifiersManager() && m_Player.GetModifiersManager().IsModifierActive(eModifiers.MDF_DROWNING);
    }
References DayZPlayerUtils::CheckWaterLevel(), and m_Player.
Referenced by Update().
IsControllsLocked()
bool IsControllsLocked ()
Definition at line 837 of file emotemanager.c.
    {
        return m_controllsLocked;
    }
References m_controllsLocked.
Referenced by ManBase::HeadingModel().
IsEmotePlaying()
bool IsEmotePlaying ()
Definition at line 1066 of file emotemanager.c.
    {
        return m_bEmoteIsPlaying || m_IsSurrendered;
    }
References m_bEmoteIsPlaying, and m_IsSurrendered.
Referenced by ManBase::CanDeleteItems(), CanPlayEmote(), ManBase::IsInFBEmoteState(), and ManBase::OnQuickBarSingleUse().
KillPlayer()
void KillPlayer ()
Definition at line 711 of file emotemanager.c.
    {
        if (GetGame().IsServer())
        {
            m_Player.SetHealth(0);
        }
    }
References GetGame(), and m_Player.
Referenced by CommitSuicide().
LogSuicide()
void LogSuicide ()
Definition at line 719 of file emotemanager.c.
    {
        if (GetGame().IsServer())
        {
            PlayerIdentity identity = m_Player.GetIdentity();
            if (identity)
            {
                GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(GetGame().AdminLog, "Player '" + identity.GetName() + "' (id=" + identity.GetId() + ") committed suicide.");
            }
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), PlayerIdentityBase::GetId(), PlayerIdentityBase::GetName(), and m_Player.
Referenced by CommitSuicide().
OnEmoteEnd()
void OnEmoteEnd ()
back to the default - shoot from camera - if not set already
Definition at line 442 of file emotemanager.c.
    {
        ShowItemInHands();
        if ( m_PlayerDies )
        {
            m_Player.SetHealth(0.0);
            return;
        }
        //surrender "state" switch
        if ( m_CurrentGestureID == EmoteConstants.ID_EMOTE_SURRENDER )
        {
            m_IsSurrendered = !m_IsSurrendered;
            SetEmoteLockState(m_IsSurrendered);
        }
        m_CurrentGestureID = 0;
        if ( m_IsSurrendered )
        {
            return;
        }
        m_GestureInterruptInput = false;
        SetEmoteLockState(false);
        if (!m_Player.IsShootingFromCamera()) m_Player.OverrideShootFromCamera(true);
    }
References EmoteConstants::ID_EMOTE_SURRENDER, m_CurrentGestureID, m_GestureInterruptInput, m_IsSurrendered, m_Player, m_PlayerDies, SetEmoteLockState(), and ShowItemInHands().
Referenced by PlaySurrenderInOut(), and Update().
OnInputUserDataProcess()
bool OnInputUserDataProcess (int userDataType, ParamsReadContext ctx)
Definition at line 473 of file emotemanager.c.
    {
        if ( userDataType == INPUT_UDT_GESTURE)
        {
            int forced = EmoteLauncher.FORCE_NONE;
            int gestureID = -1;
            int random = -1;
            if (ctx.Read(gestureID))
            {
                ctx.Read(forced);
                if (ctx.Read(random))
                {
                    m_RPSOutcome = random;
                }
                //server-side check
                if (forced > EmoteLauncher.FORCE_NONE || CanPlayEmote(gestureID))
                {
                    ScriptJunctureData pCtx = new ScriptJunctureData;
                    pCtx.Write(gestureID);
                    pCtx.Write(forced);
                    m_Player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_GESTURE_REQUEST, pCtx);
                }
            }
            return true;
        }
        return false;
    }
References CanPlayEmote(), EmoteLauncher::FORCE_NONE, INPUT_UDT_GESTURE, m_Player, m_RPSOutcome, Serializer::Read(), DayZPlayerSyncJunctures::SJ_GESTURE_REQUEST, and Serializer::Write().
OnSyncJuncture()
void OnSyncJuncture (int pJunctureID, ParamsReadContext pCtx)
Definition at line 505 of file emotemanager.c.
    {
        int forced;
        int gesture_id;
        if (!m_CancelEmote)
        {
            pCtx.Read(gesture_id);
            pCtx.Read(forced);
            if ( (m_Callback || m_IsSurrendered) && (forced == EmoteLauncher.FORCE_ALL || (forced == EmoteLauncher.FORCE_DIFFERENT && m_CurrentGestureID != gesture_id)) )
            {
                m_CancelEmote = true;
            }
            if (gesture_id == CALLBACK_CMD_INSTACANCEL)
            {
                m_InstantCancelEmote = true;
            }
            m_DeferredEmoteExecution = gesture_id;
        }
        else
            m_CancelEmote = false;
    }
References CALLBACK_CMD_INSTACANCEL, EmoteLauncher::FORCE_ALL, EmoteLauncher::FORCE_DIFFERENT, m_Callback, m_CancelEmote, m_CurrentGestureID, m_DeferredEmoteExecution, m_InstantCancelEmote, m_IsSurrendered, and Serializer::Read().
PickEmote()
protected void PickEmote (int gestureslot)
Obsolete.
Definition at line 596 of file emotemanager.c.
    {
        /*if ( m_Player && (!GetGame().IsDedicatedServer()))
        {
            m_PreviousGestureID = gestureslot;
            if ( gestureslot == 12)
            {
                return;
            }
            int emote_id_from_slot = m_Player.m_ConfigEmotesProfile.GetEmoteFromSlot(gestureslot.ToString());
            CreateEmoteCBFromMenu(gestureslot,true);
        }*/
    }
PlayEmote()
bool PlayEmote (int id)
Definition at line 538 of file emotemanager.c.
    {
        m_DeferredEmoteExecution = CALLBACK_CMD_INVALID;
        if (!CanPlayEmote(id))
        {
            m_Player.SetInventorySoftLock(false);
            return false;
        }
        actionDebugPrint("[emote] " + Object.GetDebugName(m_Player) + " play emote id=" + id + " IH=" + Object.GetDebugName(m_Player.GetItemInHands()));
        m_PreviousGestureID = m_CurrentGestureID;
        m_CurrentGestureID = id;
        if (id > 0)
        {
            //-----------------------------------------------
            EmoteBase emote;
            if (m_NameEmoteMap.Find(id,emote))
            {
                int callback_ID;
                int stancemask;
                bool is_fullbody;
                if (DetermineEmoteData(emote,callback_ID,stancemask,is_fullbody))
                {
                    if (!emote.EmoteStartOverride(EmoteCB,callback_ID,stancemask,is_fullbody))
                    {
                        emote.OnBeforeStandardCallbackCreated(callback_ID,stancemask,is_fullbody);
                        CreateEmoteCallback(EmoteCB,callback_ID,stancemask,is_fullbody);
                    }
                    if (emote.GetHideItemInHands())
                    {
                        HideItemInHands();
                    }
                }
                else
                {
                    Error("EmoteManager | DetermineEmoteData failed!");
                }
            }
        }
        if (m_bEmoteIsPlaying)
        {
            m_Player.SetInventorySoftLock(true);
            if (m_Callback.m_IsFullbody)
            {
                SetEmoteLockState(true);
            }
            return true;
        }
        return false;
    }
References actionDebugPrint(), CALLBACK_CMD_INVALID, CanPlayEmote(), CreateEmoteCallback(), DetermineEmoteData(), EmoteBase::EmoteStartOverride(), Error(), EmoteBase::GetHideItemInHands(), HideItemInHands(), m_bEmoteIsPlaying, m_Callback, m_CurrentGestureID, m_DeferredEmoteExecution, EmoteCB::m_IsFullbody, m_NameEmoteMap, m_Player, m_PreviousGestureID, EmoteBase::OnBeforeStandardCallbackCreated(), and SetEmoteLockState().
Referenced by SendEmoteRequestSync(), and Update().
PlaySurrenderInOut()
void PlaySurrenderInOut (bool state)
Definition at line 909 of file emotemanager.c.
    {
        m_PreviousGestureID = m_CurrentGestureID;
        m_CurrentGestureID = EmoteConstants.ID_EMOTE_SURRENDER;
        if (state)
        {
            if (m_Player.GetItemInHands() && !m_Player.CanDropEntity(m_Player.GetItemInHands()))
                return;
            if (m_Player.GetItemInHands() && GetGame().IsClient())
            {
                m_Player.PhysicalPredictiveDropItem(m_Player.GetItemInHands());
            }
            CreateEmoteCallback(EmoteCB,DayZPlayerConstants.CMD_GESTUREFB_SURRENDERIN,DayZPlayerConstants.STANCEMASK_ALL,true);
            if (m_Callback)
                m_Callback.RegisterAnimationEvent("ActionExec", UA_ANIM_EVENT);
        }
        else
        {
            if ( m_Player.IsAlive() && !m_Player.IsUnconscious() )
            {
                CreateEmoteCallback(EmoteCB,DayZPlayerConstants.CMD_GESTUREFB_SURRENDEROUT,DayZPlayerConstants.STANCEMASK_ALL,true);
            }
            else
            {
                m_bEmoteIsPlaying = false;
                OnEmoteEnd();
            }
        }
    }
References CreateEmoteCallback(), GetGame(), EmoteConstants::ID_EMOTE_SURRENDER, m_bEmoteIsPlaying, m_Callback, m_CurrentGestureID, m_Player, m_PreviousGestureID, OnEmoteEnd(), and UA_ANIM_EVENT.
Referenced by Update().
SendEmoteRequestSync()
void SendEmoteRequestSync (int id)
Definition at line 768 of file emotemanager.c.
    {
        int forced = EmoteLauncher.FORCE_NONE;
        if (m_MenuEmote)
        {
            forced = m_MenuEmote.GetForced();
        }
        //RPS handling. TODO: move
        m_RPSOutcome = -1;
        switch (id)
        {
            case EmoteConstants.ID_EMOTE_RPS :
                m_RPSOutcome = Math.RandomInt(0,3);
            break;
            case EmoteConstants.ID_EMOTE_RPS_R :
                m_RPSOutcome = 0;
            break;
            case EmoteConstants.ID_EMOTE_RPS_P :
                m_RPSOutcome = 1;
            break;
            case EmoteConstants.ID_EMOTE_RPS_S :
                m_RPSOutcome = 2;
            break;
        }
        ScriptInputUserData ctx = new ScriptInputUserData;
        if ( GetGame().IsMultiplayer() && GetGame().IsClient() )
        {
            if ( ctx.CanStoreInputUserData() && (CanPlayEmote(id) || forced) )
            {
                ctx.Write(INPUT_UDT_GESTURE);
                ctx.Write(id);
                ctx.Write(forced);
                if (m_RPSOutcome != -1)
                {
                    ctx.Write(m_RPSOutcome);
                }
                ctx.Send();
                //TODO: investigate callstack to prevent multiple locking attempts (wasteful)
                if (id > 0)
                {
                    m_Player.SetInventorySoftLock(true);
                }
            }
            m_MenuEmote = NULL;
        }
        else if (!GetGame().IsMultiplayer())
        {
            if (id == CALLBACK_CMD_END )
            {
                EndCallbackCommand();
            }
            else if (id == CALLBACK_CMD_GESTURE_INTERRUPT)
            {
                m_DeferredEmoteExecution = CALLBACK_CMD_GESTURE_INTERRUPT;
            }
            else
            {
                PlayEmote(id);
            }
            m_MenuEmote = NULL;
        }
    }
References CALLBACK_CMD_END, CALLBACK_CMD_GESTURE_INTERRUPT, CanPlayEmote(), ScriptInputUserData::CanStoreInputUserData(), EndCallbackCommand(), EmoteLauncher::FORCE_NONE, EmoteLauncher::GetForced(), GetGame(), EmoteConstants::ID_EMOTE_RPS, EmoteConstants::ID_EMOTE_RPS_P, EmoteConstants::ID_EMOTE_RPS_R, EmoteConstants::ID_EMOTE_RPS_S, INPUT_UDT_GESTURE, m_DeferredEmoteExecution, m_MenuEmote, m_Player, m_RPSOutcome, PlayEmote(), Math::RandomInt(), ScriptInputUserData::Send(), and Serializer::Write().
Referenced by Update().
ServerRequestEmoteCancel()
void ServerRequestEmoteCancel ()
Definition at line 1021 of file emotemanager.c.
    {
        ScriptJunctureData pCtx = new ScriptJunctureData;
        pCtx.Write(CALLBACK_CMD_GESTURE_INTERRUPT);
        //pCtx.Write(CALLBACK_CMD_SERVER);
        m_Player.SendSyncJuncture(DayZPlayerSyncJunctures.SJ_GESTURE_REQUEST, pCtx);
    }
References CALLBACK_CMD_GESTURE_INTERRUPT, m_Player, DayZPlayerSyncJunctures::SJ_GESTURE_REQUEST, and Serializer::Write().
SetEmoteLockState()
void SetEmoteLockState (bool state)
Definition at line 940 of file emotemanager.c.
    {
        DayZPlayerCameraBase camera = DayZPlayerCameraBase.Cast(m_Player.GetCurrentCamera());
        if (!m_HandInventoryLocation)
        {
            m_HandInventoryLocation = new InventoryLocation;
            m_HandInventoryLocation.SetHands(m_Player,null);
        }
        if (!state)
        {
            if (m_Player.GetInventory().HasInventoryReservation(null, m_HandInventoryLocation))
            {
                m_Player.GetInventory().ClearInventoryReservationEx( null, m_HandInventoryLocation);
            }
            if ( m_Player.GetActionManager() )
                m_Player.GetActionManager().EnableActions(true);
            m_Player.SetInventorySoftLock(false);
            if ( m_controllsLocked )
            {
                m_controllsLocked = false;
                //camera.ForceFreelook(false);
                //m_Player.GetInputController().OverrideAimChangeX(false,0);
                //m_Player.GetInputController().OverrideMovementSpeed(false,0);
            }
        }
        else
        {
            //m_HandInventoryLocation.SetHands(m_Player,m_Player.GetItemInHands());
            if (!m_Player.GetInventory().HasInventoryReservation(null, m_HandInventoryLocation))
            {
                m_Player.GetInventory().AddInventoryReservationEx( null, m_HandInventoryLocation, GameInventory.c_InventoryReservationTimeoutMS);
            }
            if ( m_Player.GetActionManager() )
                m_Player.GetActionManager().EnableActions(false);
            //Movement lock in fullbody anims
            if (m_Callback && m_Callback.m_IsFullbody && !m_controllsLocked )
            {
                m_controllsLocked = true;
                //m_Player.GetInputController().OverrideAimChangeX(true,0);
                //m_Player.GetInputController().OverrideMovementSpeed(true,0);
                //camera.ForceFreelook(true);
            }
        }
        m_EmoteLockState = state;
    }
References m_Callback, m_controllsLocked, m_EmoteLockState, m_HandInventoryLocation, EmoteCB::m_IsFullbody, m_Player, and InventoryLocation::SetHands().
Referenced by EndSurrenderRequest(), OnEmoteEnd(), PlayEmote(), and Update().
SetGesture()
void SetGesture (int id)
Definition at line 216 of file emotemanager.c.
    {
        m_GestureID = id;
    }
References m_GestureID.
ShowItemInHands()
protected void ShowItemInHands ()
Definition at line 650 of file emotemanager.c.
    {
        if (m_item)
        {
            m_Player.TryHideItemInHands(false);
        }
        //m_ItemToHands = false;
    }
References m_item, and m_Player.
Referenced by OnEmoteEnd().
Update()
void Update (float deltaT)
Definition at line 266 of file emotemanager.c.
    {
        // no updates on restrained characters
        if (m_Player.IsRestrained())
            return;
        if (m_ItemToBeCreated)
        {
            if ( !m_Player.GetItemInHands() && GetGame().IsServer() )
            {
                m_Player.GetHumanInventory().CreateInHands("SurrenderDummyItem");
            }
            m_ItemToBeCreated = false;
        }
        int gestureSlot = DetermineGestureIndex();
        //deferred emote cancel
        if (m_InstantCancelEmote) //'hard' cancel
        {
            if (m_Callback)
            {
                m_Callback.Cancel();
            }
            if (m_MenuEmote)
            {
                m_MenuEmote = null;
            }
            m_DeferredEmoteExecution = CALLBACK_CMD_INVALID;
            m_InstantCancelEmote = false;
        }
        else if (m_CancelEmote) //'soft' cancel
        {
            if (m_IsSurrendered)
            {
                EndSurrenderRequest(new SurrenderData);
            }
            else if (m_Callback)
            {
                m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_INTERRUPT);
            }
            m_CancelEmote = false;
        }
        if (m_MenuEmote && m_MenuEmote.GetForced() > EmoteLauncher.FORCE_NONE && (!GetGame().IsDedicatedServer())) //forced emote playing
        {
            SendEmoteRequestSync(m_MenuEmote.GetID());
        }
        else if (m_Callback)
        {
            bool uiGesture = false;
            if (!GetGame().IsDedicatedServer())
            {
                uiGesture = GetGame().GetUIManager().IsMenuOpen(MENU_GESTURES);
                if (InterruptGestureCheck())
                {
                    SendEmoteRequestSync(CALLBACK_CMD_END);
                }
                if (InterruptWaterCheck())
                {
                    SendEmoteRequestSync(CALLBACK_CMD_INSTACANCEL);
                }
            }
            if (gestureSlot > 0 || m_GestureInterruptInput || (m_HIC.IsSingleUse() && !uiGesture) || (m_HIC.IsContinuousUseStart() && !uiGesture) || (m_Callback.m_IsFullbody && !uiGesture && m_HIC.IsWeaponRaised()))
            {
                if (m_CurrentGestureID == EmoteConstants.ID_EMOTE_SUICIDE  && m_HIC.IsSingleUse())
                {
                    if (m_Callback.GetState() == m_Callback.STATE_LOOP_LOOP)
                    {
                        CommitSuicide();
                    }
                    else
                    {
                        return;
                    }
                }
                else if ( (m_CurrentGestureID == EmoteConstants.ID_EMOTE_THUMB || m_CurrentGestureID == EmoteConstants.ID_EMOTE_THUMBDOWN) && m_HIC.IsSingleUse() )
                {
                    m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_ACTION);
                }
                else if ( m_HIC.IsSingleUse() && (m_CurrentGestureID == EmoteConstants.ID_EMOTE_RPS || m_CurrentGestureID == EmoteConstants.ID_EMOTE_RPS_R || m_CurrentGestureID == EmoteConstants.ID_EMOTE_RPS_P || m_CurrentGestureID == EmoteConstants.ID_EMOTE_RPS_S) )
                {
                    if ( m_RPSOutcome != -1 )
                    {
                        if (m_RPSOutcome == 0)          m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_RPS_ROCK);
                        else if (m_RPSOutcome == 1)     m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_RPS_PAPER);
                        else if (m_RPSOutcome == 2)     m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_RPS_SCISSORS);
                        m_RPSOutcome = -1;
                    }
                    else
                    {
                        m_Callback.InternalCommand(DayZPlayerConstants.CMD_ACTIONINT_END);
                    }
                }
                else if (m_CurrentGestureID != EmoteConstants.ID_EMOTE_SUICIDE || (m_CurrentGestureID == EmoteConstants.ID_EMOTE_SUICIDE && m_Callback.GetState() < 3))
                {
                    SendEmoteRequestSync(CALLBACK_CMD_END);
                }
                else if (m_CurrentGestureID == EmoteConstants.ID_EMOTE_SUICIDE)
                {
                    SendEmoteRequestSync(CALLBACK_CMD_END);
                }
            }
            //HOTFIX for stance changing in additive emotes
            if (m_LastMask != -1 && m_Player.IsPlayerInStance(DayZPlayerConstants.STANCEMASK_PRONE))
            {
                m_Callback.Cancel();
            }
            if (m_MenuEmote && m_bEmoteIsPlaying)
            {
                SendEmoteRequestSync(CALLBACK_CMD_END);
            }
            if (m_DeferredEmoteExecution == CALLBACK_CMD_END)
            {
                EndCallbackCommand();
            }
            if ( m_DeferredEmoteExecution == CALLBACK_CMD_GESTURE_INTERRUPT )
            {
                InterruptCallbackCommand();
            }
        }
        //no m_Callback exists //TODO please future me, refactor into some sort of switch
        else
        {
            if (m_bEmoteIsPlaying)
            {
                m_bEmoteIsPlaying = false;
                OnEmoteEnd();
            }
            else if (!m_Player.GetItemInHands() && m_IsSurrendered && !m_ItemToBeCreated)
            {
                PlaySurrenderInOut(false);
                return;
            }
            // getting out of surrender state - hard cancel
            else if (m_IsSurrendered && (m_HIC.IsSingleUse() || m_HIC.IsContinuousUseStart() || m_HIC.IsWeaponRaised()))
            {
                if ( m_Player.GetItemInHands() )
                    m_Player.GetItemInHands().Delete();
                return;
            }
            // fallback in case lock does not end properly
            else if (m_IsSurrendered && !m_Player.GetItemInHands() || (m_Player.GetItemInHands() && m_Player.GetItemInHands().GetType() != "SurrenderDummyItem" && m_EmoteLockState))
            {
                m_IsSurrendered = false;
                SetEmoteLockState(false);
                return;
            }
            //actual emote launch
            else if (m_DeferredEmoteExecution > CALLBACK_CMD_INVALID)
            {
                PlayEmote(m_DeferredEmoteExecution);
            }
            //client-side emote launcher
            else if (!m_bEmoteIsPlaying && m_MenuEmote && (!GetGame().IsDedicatedServer()))
            {
                SendEmoteRequestSync(m_MenuEmote.GetID());
            }
            else if (!m_MenuEmote && gestureSlot > 0)
            {
                CreateEmoteCBFromMenu(gestureSlot,true); //translation no longer needed
                //PickEmote(gestureSlot);
            }
        }
    }
References CALLBACK_CMD_END, CALLBACK_CMD_GESTURE_INTERRUPT, CALLBACK_CMD_INSTACANCEL, CALLBACK_CMD_INVALID, CommitSuicide(), CreateEmoteCBFromMenu(), DetermineGestureIndex(), EndCallbackCommand(), EndSurrenderRequest(), EmoteLauncher::FORCE_NONE, EmoteLauncher::GetForced(), GetGame(), EmoteLauncher::GetID(), CGame::GetUIManager(), EmoteConstants::ID_EMOTE_RPS, EmoteConstants::ID_EMOTE_RPS_P, EmoteConstants::ID_EMOTE_RPS_R, EmoteConstants::ID_EMOTE_RPS_S, EmoteConstants::ID_EMOTE_SUICIDE, EmoteConstants::ID_EMOTE_THUMB, EmoteConstants::ID_EMOTE_THUMBDOWN, InterruptCallbackCommand(), InterruptGestureCheck(), InterruptWaterCheck(), HumanInputController::IsContinuousUseStart(), UIManager::IsMenuOpen(), HumanInputController::IsSingleUse(), HumanInputController::IsWeaponRaised(), m_bEmoteIsPlaying, m_Callback, m_CancelEmote, m_CurrentGestureID, m_DeferredEmoteExecution, m_EmoteLockState, m_GestureInterruptInput, m_HIC, m_InstantCancelEmote, EmoteCB::m_IsFullbody, m_IsSurrendered, m_ItemToBeCreated, m_LastMask, m_MenuEmote, m_Player, m_RPSOutcome, MENU_GESTURES, OnEmoteEnd(), PlayEmote(), PlaySurrenderInOut(), SendEmoteRequestSync(), and SetEmoteLockState().
~EmoteManager()
void ~EmoteManager ()
Definition at line 181 of file emotemanager.c.
    {
        if (m_ReservationTimer && m_ReservationTimer.IsRunning())
            m_ReservationTimer.Stop();
    }
References m_ReservationTimer.
Variable Documentation
CALLBACK_CMD_END
protected const int CALLBACK_CMD_END = -2
Definition at line 135 of file emotemanager.c.
Referenced by CanPlayEmote(), SendEmoteRequestSync(), and Update().
CALLBACK_CMD_GESTURE_INTERRUPT
protected const int CALLBACK_CMD_GESTURE_INTERRUPT = -3
Definition at line 136 of file emotemanager.c.
Referenced by CanPlayEmote(), SendEmoteRequestSync(), ServerRequestEmoteCancel(), and Update().
CALLBACK_CMD_INSTACANCEL
protected const int CALLBACK_CMD_INSTACANCEL = -4
Definition at line 137 of file emotemanager.c.
Referenced by CanPlayEmote(), OnSyncJuncture(), and Update().
CALLBACK_CMD_INVALID
protected const int CALLBACK_CMD_INVALID = -1
Definition at line 134 of file emotemanager.c.
Referenced by EmoteManager(), EndCallbackCommand(), InterruptCallbackCommand(), PlayEmote(), and Update().
m_AdminLog
PluginAdminLog m_AdminLog
Definition at line 138 of file emotemanager.c.
Referenced by CommitSuicide(), ManBase::EEHitBy(), ManBase::EEKilled(), EmoteManager(), ManBase::Init(), InventoryItem::ItemBase(), InventoryItem::OnPlacementComplete(), ManBase::OnUnconsciousStart(), and ManBase::OnUnconsciousStop().
m_bEmoteIsPlaying
bool m_bEmoteIsPlaying
Definition at line 116 of file emotemanager.c.
Referenced by CreateEmoteCallback(), IsEmotePlaying(), PlayEmote(), PlaySurrenderInOut(), and Update().
m_Callback
EmoteCB m_Callback
Definition at line 111 of file emotemanager.c.
Referenced by CommitSuicide(), CreateEmoteCallback(), EndCallbackCommand(), HideItemInHands(), InterruptCallbackCommand(), InterruptGestureCheck(), OnSyncJuncture(), ScriptedWidgetEventHandler::Play(), PlayEmote(), PlaySurrenderInOut(), SetEmoteLockState(), ScriptedWidgetEventHandler::Stop(), and Update().
m_CancelEmote
bool m_CancelEmote
Definition at line 119 of file emotemanager.c.
Referenced by OnSyncJuncture(), and Update().
m_controllsLocked
protected bool m_controllsLocked
Definition at line 126 of file emotemanager.c.
Referenced by IsControllsLocked(), and SetEmoteLockState().
m_CurrentGestureID
protected int m_CurrentGestureID
Definition at line 131 of file emotemanager.c.
Referenced by EndCallbackCommand(), OnEmoteEnd(), OnSyncJuncture(), PlayEmote(), PlaySurrenderInOut(), and Update().
m_DeferredEmoteExecution
protected int m_DeferredEmoteExecution
Definition at line 128 of file emotemanager.c.
Referenced by EmoteManager(), EndCallbackCommand(), InterruptCallbackCommand(), OnSyncJuncture(), PlayEmote(), SendEmoteRequestSync(), and Update().
m_EmoteClassArray
protected ref array<ref EmoteBase> m_EmoteClassArray
Definition at line 141 of file emotemanager.c.
Referenced by ConstructData().
m_EmoteIDs
protected ref array<int> m_EmoteIDs
Definition at line 142 of file emotemanager.c.
Referenced by ConstructData(), and DetermineGestureIndex().
m_EmoteInputIDs
protected ref array<int> m_EmoteInputIDs
Definition at line 143 of file emotemanager.c.
Referenced by ConstructData(), and DetermineGestureIndex().
m_EmoteLockState
protected bool m_EmoteLockState
Definition at line 127 of file emotemanager.c.
Referenced by CheckEmoteLockedState(), SetEmoteLockState(), and Update().
m_GestureID
protected int m_GestureID
Definition at line 129 of file emotemanager.c.
Referenced by GetGesture(), and SetGesture().
m_GestureInterruptInput
bool m_GestureInterruptInput
Definition at line 121 of file emotemanager.c.
Referenced by OnEmoteEnd(), and Update().
m_HandInventoryLocation
ref InventoryLocation m_HandInventoryLocation
Definition at line 114 of file emotemanager.c.
Referenced by CheckEmoteLockedState(), EmoteManager(), and SetEmoteLockState().
m_HIC
HumanInputController m_HIC
Definition at line 112 of file emotemanager.c.
Referenced by CanPlayEmote(), EmoteManager(), and Update().
m_InstantCancelEmote
bool m_InstantCancelEmote
Definition at line 120 of file emotemanager.c.
Referenced by OnSyncJuncture(), and Update().
m_InterruptInputs
ref array<string> m_InterruptInputs
Definition at line 113 of file emotemanager.c.
Referenced by EmoteManager(), and InterruptGestureCheck().
m_IsSurrendered
bool m_IsSurrendered
Definition at line 117 of file emotemanager.c.
Referenced by CanPlayEmote(), EndSurrenderRequest(), IsEmotePlaying(), OnEmoteEnd(), OnSyncJuncture(), and Update().
m_item
ItemBase m_item
Definition at line 110 of file emotemanager.c.
Referenced by HideItemInHands(), and ShowItemInHands().
m_ItemIsOn
protected bool m_ItemIsOn
Definition at line 123 of file emotemanager.c.
Referenced by EmoteManager().
m_ItemToBeCreated
bool m_ItemToBeCreated
Definition at line 118 of file emotemanager.c.
Referenced by Update().
m_ItemToHands
protected bool m_ItemToHands
Definition at line 122 of file emotemanager.c.
m_LastMask
protected int m_LastMask
Definition at line 132 of file emotemanager.c.
Referenced by CreateEmoteCallback(), and Update().
m_MenuEmote
ref EmoteLauncher m_MenuEmote
Definition at line 115 of file emotemanager.c.
Referenced by CreateEmoteCBFromMenu(), EndCallbackCommand(), GetEmoteLauncher(), InterruptCallbackCommand(), SendEmoteRequestSync(), and Update().
m_MouseButtonPressed
protected bool m_MouseButtonPressed
Definition at line 124 of file emotemanager.c.
m_NameEmoteMap
protected ref map<int, ref EmoteBase> m_NameEmoteMap
Definition at line 140 of file emotemanager.c.
Referenced by CanPlayEmote(), ConstructData(), GetNameEmoteMap(), and PlayEmote().
m_Player
m_Player
m_PlayerDies
protected bool m_PlayerDies
Definition at line 125 of file emotemanager.c.
Referenced by OnEmoteEnd().
m_PreviousGestureID
protected int m_PreviousGestureID
Definition at line 130 of file emotemanager.c.
Referenced by PlayEmote(), and PlaySurrenderInOut().
m_ReservationTimer
protected ref Timer m_ReservationTimer
Definition at line 139 of file emotemanager.c.
Referenced by EmoteManager(), and ~EmoteManager().
m_RPSOutcome
protected int m_RPSOutcome
Definition at line 133 of file emotemanager.c.
Referenced by EmoteManager(), OnInputUserDataProcess(), SendEmoteRequestSync(), and Update().