DayzKode: P:/scripts/3_game/DayZ/systems/tftests/enprofilertests.c File Reference
enprofilertests.c File Reference
Classes
class EnProfilerTests
Functions
float DoEverything ()
void EnProfilerTests ()
float Sleep (float timeS)
EnProfilerTests TestFramework Sleep2 (float timeS)
float SleepAgain (float timeS)
float StringConcat ()
float StringFormat ()
TFResult TestAddFlags ()
TFResult TestClassCountData ()
TFResult TestClassTimeData ()
TFResult TestClearFlags ()
TFResult TestFuncCountData ()
void TestFuncCountDataHelper ()
static void TestFuncCountDataHelperStatic ()
TFResult TestFuncTimeData ()
TFResult TestModule ()
TFResult TestSetFlags ()
TFResult TestToggling ()
TFResult TestTogglingImmediate ()
void ~EnProfilerTests ()
Variables
bool m_bWasProfilerEnabled
Remember this, so we can restore the previous state before the test!
Function Documentation
DoEverything()
float DoEverything ()
Definition at line 784 of file enprofilertests.c.
    {
        float startTime = GetGame().GetTickTime();
        Sleep2(3);
        SleepAgain(3);
        return GetGame().GetTickTime() - startTime;
    }
References GetGame(), CGame::GetTickTime(), and Sleep2().
EnProfilerTests()
void Sleep2::EnProfilerTests ()
Definition at line 770 of file enprofilertests.c.
    {
        float startTime = GetGame().GetTickTime();
        while (GetGame().GetTickTime() - startTime < timeS)
        {
            // Zzz
        }
        return GetGame().GetTickTime() - startTime;
    }
    float DoEverything()
Sleep()
float Sleep2::Sleep (float timeS)
Definition at line 1468 of file enprofilertests.c.
Sleep2()
EnProfilerTests TestFramework Sleep2 (float timeS)
Definition at line 1 of file enprofilertests.c.
    {
        float startTime = GetGame().GetTickTime();
        while (GetGame().GetTickTime() - startTime < timeS)
        {
            // Zzz
        }
        return GetGame().GetTickTime() - startTime;
    }
Referenced by DoEverything().
SleepAgain()
float SleepAgain (float timeS)
Definition at line 773 of file enprofilertests.c.
    {
        float startTime = GetGame().GetTickTime();
        while (GetGame().GetTickTime() - startTime < timeS)
        {
            // Zzz
        }
        return GetGame().GetTickTime() - startTime;
    }
References GetGame(), and CGame::GetTickTime().
StringConcat()
float Sleep2::StringConcat ()
Definition at line 1495 of file enprofilertests.c.
StringFormat()
float Sleep2::StringFormat ()
Definition at line 1481 of file enprofilertests.c.
TestAddFlags()
TFResult Sleep2::TestAddFlags ()
Definition at line 918 of file enprofilertests.c.
TestClassCountData()
TFResult Sleep2::TestClassCountData ()
Definition at line 1190 of file enprofilertests.c.
TestClassTimeData()
TFResult Sleep2::TestClassTimeData ()
Definition at line 1142 of file enprofilertests.c.
TestClearFlags()
TFResult Sleep2::TestClearFlags ()
Definition at line 881 of file enprofilertests.c.
TestFuncCountData()
TFResult Sleep2::TestFuncCountData ()
Definition at line 1305 of file enprofilertests.c.
TestFuncCountDataHelper()
void Sleep2::TestFuncCountDataHelper ()
Definition at line 1509 of file enprofilertests.c.
TestFuncCountDataHelperStatic()
static void Sleep2::TestFuncCountDataHelperStatic () static
Definition at line 1516 of file enprofilertests.c.
TestFuncTimeData()
TFResult Sleep2::TestFuncTimeData ()
Definition at line 1242 of file enprofilertests.c.
TestModule()
TFResult Sleep2::TestModule ()
Definition at line 950 of file enprofilertests.c.
TestSetFlags()
TFResult Sleep2::TestSetFlags ()
Definition at line 828 of file enprofilertests.c.
TestToggling()
TFResult Sleep2::TestToggling ()
Definition at line 798 of file enprofilertests.c.
TestTogglingImmediate()
TFResult Sleep2::TestTogglingImmediate ()
Definition at line 813 of file enprofilertests.c.
~EnProfilerTests()
void Sleep2::~EnProfilerTests ()
Definition at line 789 of file enprofilertests.c.
Variable Documentation
m_bWasProfilerEnabled
bool m_bWasProfilerEnabled
Remember this, so we can restore the previous state before the test!
Definition at line 765 of file enprofilertests.c.