DayzKode: P:/scripts/4_world/DayZ/entities/scriptedlightbase/pointlightbase/entrancelight.c File Reference
entrancelight.c File Reference
Classes
class EntranceLightStairs2
class PointLightBase
Functions
void EntranceLight ()
class EntranceLight extends PointLightBase EntranceLightStairs1 ()
Variables
protected float m_DefaultBrightness = 0.5
protected float m_DefaultRadius = 5.5
Function Documentation
EntranceLight()
void EntranceLightStairs1::EntranceLight ()
Definition at line 26 of file entrancelight.c.
                           : EntranceLight { }
class EntranceLightMain1 : EntranceLight { }
class EntranceLightMain2 : EntranceLight { }
Referenced by CreateLights(), and Land_Underground_Stairs_Exit::CreateLights().
EntranceLightStairs1()
class EntranceLight extends PointLightBase EntranceLightStairs1 ()
Definition at line 1 of file entrancelight.c.
    {
        SetRadiusTo(10);
        SetBrightnessTo(0.5);
        SetCastShadow(true);
        SetAmbientColor(1.0, 0.4, 0.4);
        SetDiffuseColor(1.0, 0.4, 0.4);
    }
Referenced by Land_Underground_Stairs_Exit::CreateLights().
Variable Documentation
m_DefaultBrightness
protected float m_DefaultBrightness = 0.5
Definition at line 23 of file entrancelight.c.
m_DefaultRadius
protected float m_DefaultRadius = 5.5
Definition at line 24 of file entrancelight.c.