DayzKode: P:/scripts/3_game/DayZ/global/errormodulehandler/errorhandlermodule.c File Reference
errorhandlermodule.c File Reference
Classes
class ErrorHandlerModule
Definition and API of an ErrorHandlerModule - Do not insert any logic here! (as this class is not moddable)
Functions
void ErrorHandlerModuleScript ()
Constructor, by default calls the function that will fill the ErrorDataMap.
void FillErrorDataMap ()
Function to fill up m_ErrorDataMap, gets called in the Constructor.
override string GetClientMessage (int errorCode, string additionalInfo="")
Fetches the Client message for the error code.
override string GetLastClientMessage (int errorCode)
Fetches the Client message for the error code, attempting to retrieve the data from the latest.
override string GetLastServerMessage (int errorCode)
Fetches the Server message for the error code, attempting to retrieve the data from the latest.
ErrorProperties GetProperties (int errorCode)
Fetches the ErrorProperties for the error code.
override string GetServerMessage (int errorCode, string additionalInfo="")
Fetches the Server message for the error code.
void InitOptionalVariables ()
Function which gets called before FillErrorDataMap, designed to set Optional Variales before ErrorProperties are created.
void InsertDialogueErrorProperties (int code, string message, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling, using the Optional Variables.
void InsertErrorProperties (int code, string message="")
Insert an error with no handling.
void InsertExtendedPrefixDialogueErrorProperties (int code, string message, string prefix, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling with extended prefix.
void InsertExtendedPrefixSplitDialogueErrorProperties (int code, string message, string prefix, string serverMessage, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling with extended prefix and separate server message.
void InsertHeaderDialogueErrorProperties (int code, string message, string header, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling with custom header.
void InsertPrefixDialogueErrorProperties (int code, string message, string prefix, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling with custom prefix.
void InsertSplitDialogueErrorProperties (int code, string message, string serverMessage, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
Insert an error with Dialogue as handling with separate server message.
protected override void OnErrorThrown (int errorCode, owned string additionalInfo="")
Event that gets triggered when an error of the owned category is thrown. Do not call directly! Call ErrorModuleHandler.ThrowError instead.
void ~ErrorHandlerModuleScript ()
Variables
protected ref map< int, ref ErrorProperties > m_ErrorDataMap = new map<int, ref ErrorProperties>()
Map containing the codes that exist for the ErrorHandlerModule The code links to ErrorProperties This contains at the very least the Message for the error Additionally, it can contain the way to handle the error (e.g. Throw a Dialogue with the message)
class ErrorHandlerModule m_Header = ""
This is where to input logic and extend functionality of ErrorHandlerModule.
protected string m_LastAdditionalInfo = ""
Holds the last additional info passed in.
protected int m_LastErrorThrown = 0
Holds the last thrown error in this module, defaults to 0.
protected string m_Prefix = ""
Optional: Prefix (e.g. Fixed text at the start of the messages in the module)
protected ref UIScriptedMenu m_UIHandler = null
Optional: The UI the handler might generally use
Function Documentation
ErrorHandlerModuleScript()
void ErrorHandlerModuleScript ()
Constructor, by default calls the function that will fill the ErrorDataMap.
Definition at line 81 of file errorhandlermodule.c.
    {
        InitOptionalVariables();
        FillErrorDataMap();
    }
References FillErrorDataMap(), and InitOptionalVariables().
FillErrorDataMap()
void FillErrorDataMap ()
Function to fill up m_ErrorDataMap, gets called in the Constructor.
Already insert the default "UNKNOWN ERROR" message for code "-1"
Definition at line 101 of file errorhandlermodule.c.
    {
        InsertDialogueErrorProperties(-1, "#server_browser_error_unknown");
    }
References InsertDialogueErrorProperties().
Referenced by ErrorHandlerModuleScript().
GetClientMessage()
override string GetClientMessage (int errorCode, string additionalInfo = "")
Fetches the Client message for the error code.
Parameters
errorCode int The full error code
Returns
string The Client message for the error
Definition at line 130 of file errorhandlermodule.c.
    {
        ErrorProperties properties = GetProperties(errorCode);
        if ( properties )
        {
            return properties.GetClientMessage(additionalInfo);
        }
        else
        {
            return additionalInfo;
        }
    }
References ErrorProperties::GetClientMessage(), and GetProperties().
GetLastClientMessage()
override string GetLastClientMessage (int errorCode)
Fetches the Client message for the error code, attempting to retrieve the data from the latest.
Parameters
errorCode int The full error code to check against
Returns
string The Client message for the error
Definition at line 149 of file errorhandlermodule.c.
    {
        if (errorCode == m_LastErrorThrown)
        {
            return GetClientMessage(errorCode, m_LastAdditionalInfo);
        }
        else
        {
            ErrorEx(string.Format("Was unable to get the information on the last error as another has already occurred. (%1 != %2)", ErrorModuleHandler.GetErrorHex(errorCode), ErrorModuleHandler.GetErrorHex(m_LastErrorThrown)));
            return GetClientMessage(errorCode);
        }
    }
References ErrorEx, ErrorHandlerModule::GetClientMessage(), ErrorModuleHandler::GetErrorHex(), m_LastAdditionalInfo, and m_LastErrorThrown.
GetLastServerMessage()
override string GetLastServerMessage (int errorCode)
Fetches the Server message for the error code, attempting to retrieve the data from the latest.
Parameters
errorCode int The full error code to check against
Returns
string The Server message for the error
Definition at line 186 of file errorhandlermodule.c.
    {
        if (errorCode == m_LastErrorThrown)
        {
            return GetServerMessage(errorCode, m_LastAdditionalInfo);
        }
        else
        {
            ErrorEx(string.Format("Was unable to get the information on the last error as another has already occurred. (%1 != %2)", ErrorModuleHandler.GetErrorHex(errorCode), ErrorModuleHandler.GetErrorHex(m_LastErrorThrown)), ErrorExSeverity.WARNING);
            return GetServerMessage(errorCode);
        }
    }
References ErrorEx, ErrorModuleHandler::GetErrorHex(), ErrorHandlerModule::GetServerMessage(), m_LastAdditionalInfo, and m_LastErrorThrown.
GetProperties()
ErrorProperties GetProperties (int errorCode)
Fetches the ErrorProperties for the error code.
Parameters
errorCode int The full error code
Returns
ErrorProperties The data and handling for the error
Definition at line 112 of file errorhandlermodule.c.
    {
        int error = ErrorModuleHandler.GetCodeFromError(errorCode);
        ErrorProperties properties = null;
        if (!m_ErrorDataMap.Find(error, properties))
        {
            Error(string.Format("[EHM] Could not find any properties for error %1(%2) in %3", errorCode, ErrorModuleHandler.GetErrorHex(errorCode), this));
        }
        return properties;
    }
References Error(), ErrorModuleHandler::GetCodeFromError(), ErrorModuleHandler::GetErrorHex(), and m_ErrorDataMap.
Referenced by GetClientMessage(), GetServerMessage(), and OnErrorThrown().
GetServerMessage()
override string GetServerMessage (int errorCode, string additionalInfo = "")
Fetches the Server message for the error code.
Parameters
errorCode int The full error code
Returns
string The Server message for the error
Definition at line 167 of file errorhandlermodule.c.
    {
        ErrorProperties properties = GetProperties(errorCode);
        if ( properties )
        {
            return properties.GetServerMessage(additionalInfo);
        }
        else
        {
            return additionalInfo;
        }
    }
References GetProperties(), and ErrorProperties::GetServerMessage().
InitOptionalVariables()
void InitOptionalVariables ()
Function which gets called before FillErrorDataMap, designed to set Optional Variales before ErrorProperties are created.
Definition at line 96 of file errorhandlermodule.c.
    {
    }
Referenced by ErrorHandlerModuleScript().
InsertDialogueErrorProperties()
void InsertDialogueErrorProperties (int code, string message, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling, using the Optional Variables.
Definition at line 233 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2", m_Prefix, message), message, m_Header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Header, m_Prefix, and m_UIHandler.
Referenced by ClientKickedModule::FillErrorDataMap(), ConnectErrorClientModule::FillErrorDataMap(), FillErrorDataMap(), ConnectErrorServerModule::FillErrorDataMap(), and BIOSErrorModule::InsertBIOSError().
InsertErrorProperties()
void InsertErrorProperties (int code, string message = "")
Insert an error with no handling.
Definition at line 269 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, ErrorProperties(message, message));
    }
References m_ErrorDataMap.
Referenced by BIOSErrorModule::FillErrorDataMap(), ClientKickedModule::FillErrorDataMap(), ConnectErrorClientModule::FillErrorDataMap(), and BIOSErrorModule::InsertBIOSError().
InsertExtendedPrefixDialogueErrorProperties()
void InsertExtendedPrefixDialogueErrorProperties (int code, string message, string prefix, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling with extended prefix.
Definition at line 251 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2%3", m_Prefix, prefix, message), message, m_Header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Header, m_Prefix, and m_UIHandler.
Referenced by ClientKickedModule::FillErrorDataMap().
InsertExtendedPrefixSplitDialogueErrorProperties()
void InsertExtendedPrefixSplitDialogueErrorProperties (int code, string message, string prefix, string serverMessage, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling with extended prefix and separate server message.
Definition at line 257 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2%3", m_Prefix, prefix, message), serverMessage, m_Header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Header, m_Prefix, and m_UIHandler.
Referenced by ClientKickedModule::FillErrorDataMap().
InsertHeaderDialogueErrorProperties()
void InsertHeaderDialogueErrorProperties (int code, string message, string header, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling with custom header.
Definition at line 239 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2", m_Prefix, message), message, header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Prefix, and m_UIHandler.
InsertPrefixDialogueErrorProperties()
void InsertPrefixDialogueErrorProperties (int code, string message, string prefix, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling with custom prefix.
Definition at line 245 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2", prefix, message), message, m_Header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Header, and m_UIHandler.
Referenced by ClientKickedModule::FillErrorDataMap().
InsertSplitDialogueErrorProperties()
void InsertSplitDialogueErrorProperties (int code, string message, string serverMessage, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Insert an error with Dialogue as handling with separate server message.
Definition at line 263 of file errorhandlermodule.c.
    {
        m_ErrorDataMap.Insert(code, DialogueErrorProperties(string.Format("%1%2", m_Prefix, message), serverMessage, m_Header, m_UIHandler, dialogButtonType, defaultButton, dialogMeaningType, displayAdditionalInfo));
    }
References DialogueErrorProperties(), m_ErrorDataMap, m_Header, m_Prefix, and m_UIHandler.
Referenced by ClientKickedModule::FillErrorDataMap().
OnErrorThrown()
protected override void OnErrorThrown (int errorCode, owned string additionalInfo = "")
Event that gets triggered when an error of the owned category is thrown. Do not call directly! Call ErrorModuleHandler.ThrowError instead.
Parameters
errorCode int The full error code
additionalInfo string Any additional info regarding the error, usually data
Definition at line 206 of file errorhandlermodule.c.
    {
        super.OnErrorThrown(errorCode, additionalInfo);
        m_LastErrorThrown = errorCode;
        m_LastAdditionalInfo = additionalInfo;
        ErrorProperties properties = GetProperties(errorCode);
        if ( properties )
        {
            properties.HandleError(errorCode, additionalInfo);
        }
        else
        {
            ErrorEx(string.Format("Error code %1(%2) was thrown but no ErrorProperties was found for it in category %3.", errorCode, ErrorModuleHandler.GetErrorHex(errorCode), GetCategory().ToString()));
            if (m_ErrorDataMap.Find(-1, properties))
            {
                properties.HandleError(errorCode, additionalInfo);
            }
        }
    }
References ErrorEx, GetCategory(), ErrorModuleHandler::GetErrorHex(), GetProperties(), ErrorProperties::HandleError(), m_ErrorDataMap, m_LastAdditionalInfo, m_LastErrorThrown, and ToString().
~ErrorHandlerModuleScript()
void ~ErrorHandlerModuleScript ()
Definition at line 87 of file errorhandlermodule.c.
    {
        if (m_UIHandler)
        {
            delete m_UIHandler;
        }
    }
References m_UIHandler.
Variable Documentation
m_ErrorDataMap
protected ref map<int, ref ErrorProperties> m_ErrorDataMap = new map<int, ref ErrorProperties>()
Map containing the codes that exist for the ErrorHandlerModule The code links to ErrorProperties This contains at the very least the Message for the error Additionally, it can contain the way to handle the error (e.g. Throw a Dialogue with the message)
Definition at line 78 of file errorhandlermodule.c.
Referenced by GetProperties(), InsertDialogueErrorProperties(), InsertErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertHeaderDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), InsertSplitDialogueErrorProperties(), and OnErrorThrown().
m_Header
class ErrorHandlerModule m_Header = ""
This is where to input logic and extend functionality of ErrorHandlerModule.
Optional: Header (e.g. The header of a Dialogue box)
Referenced by DialogueErrorProperties(), HandleError(), BIOSErrorModule::InitOptionalVariables(), ClientKickedModule::InitOptionalVariables(), ConnectErrorClientModule::InitOptionalVariables(), ConnectErrorServerModule::InitOptionalVariables(), InsertDialogueErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), and InsertSplitDialogueErrorProperties().
m_LastAdditionalInfo
protected string m_LastAdditionalInfo = ""
Holds the last additional info passed in.
Definition at line 70 of file errorhandlermodule.c.
Referenced by GetLastClientMessage(), GetLastServerMessage(), and OnErrorThrown().
m_LastErrorThrown
protected int m_LastErrorThrown = 0
Holds the last thrown error in this module, defaults to 0.
Definition at line 69 of file errorhandlermodule.c.
Referenced by GetLastClientMessage(), GetLastServerMessage(), OnErrorThrown(), ConnectErrorClientModule::OnEvent(), OnEvent(), and ConnectErrorServerModule::OnEvent().
m_Prefix
protected string m_Prefix = ""
Optional: Prefix (e.g. Fixed text at the start of the messages in the module)
Definition at line 66 of file errorhandlermodule.c.
Referenced by ClientKickedModule::InitOptionalVariables(), InsertDialogueErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertHeaderDialogueErrorProperties(), and InsertSplitDialogueErrorProperties().
m_UIHandler
protected ref UIScriptedMenu m_UIHandler = null
Optional: The UI the handler might generally use
Definition at line 67 of file errorhandlermodule.c.
Referenced by InsertDialogueErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertHeaderDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), InsertSplitDialogueErrorProperties(), and ~ErrorHandlerModuleScript().