DayzKode: P:/scripts/3_game/DayZ/global/errormodulehandler/errorproperties.c File Reference
errorproperties.c File Reference
Classes
class ErrorProperties
Class which holds the properties and handling of an error.
Functions
void DialogueErrorProperties (string message, string serverMessage, string header, UIScriptedMenu handler=null, int dialogButtonType=DBT_OK, int defaultButton=DBB_OK, int dialogMeaningType=DMT_EXCLAMATION, bool displayAdditionalInfo=true)
int GetDefaultButton ()
int GetDialogButtonType ()
int GetDialogMeaningType ()
UIScriptedMenu GetHandler ()
string GetHeader ()
override void HandleError (int errorCode, string additionalInfo="")
Variables
protected int m_DefaultButton
protected int m_DialogButtonType
protected int m_DialogMeaningType
protected bool m_DisplayAdditionalInfo
protected UIScriptedMenu m_Handler
class ErrorProperties m_Header
Error which shows a generic Dialogue UI.
Function Documentation
DialogueErrorProperties()
void DialogueErrorProperties (string message, string serverMessage, string header, UIScriptedMenu handler = null, int dialogButtonType = DBT_OK, int defaultButton = DBB_OK, int dialogMeaningType = DMT_EXCLAMATION, bool displayAdditionalInfo = true)
Definition at line 45 of file errorproperties.c.
    {
        m_Header = header;
        m_DialogButtonType = dialogButtonType;
        m_DefaultButton = defaultButton;
        m_DialogMeaningType = dialogMeaningType;
        m_Handler = handler;
        m_DisplayAdditionalInfo = displayAdditionalInfo;
    }
References m_DefaultButton, m_DialogButtonType, m_DialogMeaningType, m_DisplayAdditionalInfo, m_Handler, and m_Header.
Referenced by InsertDialogueErrorProperties(), InsertExtendedPrefixDialogueErrorProperties(), InsertExtendedPrefixSplitDialogueErrorProperties(), InsertHeaderDialogueErrorProperties(), InsertPrefixDialogueErrorProperties(), and InsertSplitDialogueErrorProperties().
GetDefaultButton()
int GetDefaultButton ()
Definition at line 78 of file errorproperties.c.
{ return m_DefaultButton; }
References m_DefaultButton.
GetDialogButtonType()
int GetDialogButtonType ()
Definition at line 77 of file errorproperties.c.
{ return m_DialogButtonType; }
References m_DialogButtonType.
GetDialogMeaningType()
int GetDialogMeaningType ()
Definition at line 79 of file errorproperties.c.
{ return m_DialogMeaningType; }
References m_DialogMeaningType.
GetHandler()
UIScriptedMenu GetHandler ()
Definition at line 80 of file errorproperties.c.
{ return m_Handler; }
References m_Handler.
GetHeader()
string GetHeader ()
Definition at line 76 of file errorproperties.c.
{ return m_Message; }
References ErrorProperties::m_Message.
Referenced by AttachmentCategoriesRow::Init().
HandleError()
override void HandleError (int errorCode, string additionalInfo = "")
Definition at line 55 of file errorproperties.c.
    {
#ifdef NO_GUI
        return; //do not display error if GUI is disabled
#endif
#ifdef SERVER
        return;
#else
        string message;
        if (m_DisplayAdditionalInfo && additionalInfo != "")
            message = string.Format(EP_MESSAGE_FORMAT_STRING, m_Message, additionalInfo);
        else
            message = m_Message;
        GetGame().GetUIManager().ShowDialog(
            string.Format(EP_HEADER_FORMAT_STRING, m_Header, ErrorModuleHandler.GetErrorHex(errorCode)),
            message, errorCode, m_DialogButtonType, m_DefaultButton, m_DialogMeaningType, m_Handler);
#endif
    }
References string::Format(), ErrorModuleHandler::GetErrorHex(), GetGame(), CGame::GetUIManager(), m_DefaultButton, m_DialogButtonType, m_DialogMeaningType, m_DisplayAdditionalInfo, m_Handler, m_Header, ErrorProperties::m_Message, and UIManager::ShowDialog().
Variable Documentation
m_DefaultButton
protected int m_DefaultButton
Definition at line 40 of file errorproperties.c.
Referenced by DialogueErrorProperties(), GetDefaultButton(), and HandleError().
m_DialogButtonType
protected int m_DialogButtonType
Definition at line 39 of file errorproperties.c.
Referenced by DialogueErrorProperties(), GetDialogButtonType(), and HandleError().
m_DialogMeaningType
protected int m_DialogMeaningType
Definition at line 41 of file errorproperties.c.
Referenced by DialogueErrorProperties(), GetDialogMeaningType(), and HandleError().
m_DisplayAdditionalInfo
protected bool m_DisplayAdditionalInfo
Definition at line 43 of file errorproperties.c.
Referenced by DialogueErrorProperties(), and HandleError().
m_Handler
protected UIScriptedMenu m_Handler
Definition at line 42 of file errorproperties.c.
Referenced by DialogueErrorProperties(), GetHandler(), and HandleError().
m_Header
class ErrorProperties m_Header
Error which shows a generic Dialogue UI.