DayzKode: P:/scripts/4_world/DayZ/entities/firearms/fsm/events.c File Reference
events.c File Reference
Classes
class WeaponEventAnimation
class WeaponEventBase
signalize mechanism manipulation
Enumerations
enum WeaponEventID {
UNKNOWN , MECHANISM , TRIGGER , TRIGGER_JAM ,
TRIGGER_AUTO_START , TRIGGER_AUTO_END , LOAD1_BULLET , CONTINUOUS_LOADBULLET_START ,
CONTINUOUS_LOADBULLET_END , UNJAM , ATTACH_MAGAZINE , UNJAMMING_FAILED_TIMEOUT ,
UNJAMMING_TIMEOUT , DETACH_MAGAZINE , SWAP_MAGAZINE , HUMANCOMMAND_ACTION_FINISHED ,
HUMANCOMMAND_ACTION_ABORTED , RELOAD_TIMEOUT , DRY_FIRE_TIMEOUT , SET_NEXT_MUZZLE_MODE ,
ANIMATION_EVENT
}
identifier for events. mainly for rpc purposes
Functions
WeaponEventBase CreateWeaponEventFromContext (ParamsReadContext ctx)
WeaponEventBase WeaponAnimEventFactory (WeaponEvents type, DayZPlayer p=NULL, Magazine m=NULL)
creates animation system events
WeaponEventBase WeaponEventFactory (WeaponEventID id, int aetype, DayZPlayer p=NULL, Magazine m=NULL)
creates weapon fsm events
Enumeration Type Documentation
WeaponEventID
enum WeaponEventID
identifier for events. mainly for rpc purposes
Enumerator
UNKNOWN
MECHANISM
TRIGGER
TRIGGER_JAM
TRIGGER_AUTO_START
TRIGGER_AUTO_END
LOAD1_BULLET
CONTINUOUS_LOADBULLET_START
CONTINUOUS_LOADBULLET_END
UNJAM
ATTACH_MAGAZINE
UNJAMMING_FAILED_TIMEOUT
UNJAMMING_TIMEOUT
DETACH_MAGAZINE
SWAP_MAGAZINE
HUMANCOMMAND_ACTION_FINISHED
HUMANCOMMAND_ACTION_ABORTED
RELOAD_TIMEOUT
DRY_FIRE_TIMEOUT
SET_NEXT_MUZZLE_MODE
ANIMATION_EVENT
Definition at line 5 of file events.c.
{
    UNKNOWN,
    MECHANISM,
    TRIGGER,
    TRIGGER_JAM,
    TRIGGER_AUTO_START,
    TRIGGER_AUTO_END,
    LOAD1_BULLET,
    CONTINUOUS_LOADBULLET_START,
    CONTINUOUS_LOADBULLET_END,
    UNJAM,
    ATTACH_MAGAZINE,
    UNJAMMING_FAILED_TIMEOUT,
    UNJAMMING_TIMEOUT,
    DETACH_MAGAZINE,
    SWAP_MAGAZINE,
    HUMANCOMMAND_ACTION_FINISHED,
    HUMANCOMMAND_ACTION_ABORTED,
    RELOAD_TIMEOUT,
    DRY_FIRE_TIMEOUT,
    SET_NEXT_MUZZLE_MODE,
    ANIMATION_EVENT,
};
Function Documentation
CreateWeaponEventFromContext()
WeaponEventBase CreateWeaponEventFromContext (ParamsReadContext ctx)
Definition at line 281 of file events.c.
{
    int packedType;
    ctx.Read(packedType);
    DayZPlayer player;
    ctx.Read(player);
    Magazine magazine;
    ctx.Read(magazine);
    WeaponEventID eventID = packedType >> 16;
    WeaponEvents animEvent = packedType & 0x0000ffff;
    WeaponEventBase b = WeaponEventFactory(eventID, animEvent, player, magazine);
    b.ReadFromContext(ctx);
    return b;
}
References Serializer::Read(), WeaponEventBase::ReadFromContext(), and WeaponEventFactory().
Referenced by OnEventForRemoteWeapon().
WeaponAnimEventFactory()
WeaponEventBase WeaponAnimEventFactory (WeaponEvents type, DayZPlayer p = NULL, Magazine m = NULL)
creates animation system events
Definition at line 251 of file events.c.
{
    switch (type)
    {
        case WeaponEvents.ATTACHMENT_HIDE: return new WeaponEventAnimAttachmentHide(p, m);
        case WeaponEvents.ATTACHMENT_SHOW: return new WeaponEventAnimAttachmentShow(p, m);
        case WeaponEvents.BULLET_EJECT: return new WeaponEventAnimBulletEject(p, m);
        case WeaponEvents.BULLET_HIDE: return new WeaponEventAnimBulletHide(p, m);
        case WeaponEvents.BULLET_HIDE2: return new WeaponEventAnimBulletHide2(p, m);
        case WeaponEvents.BULLET_IN_CHAMBER: return new WeaponEventAnimBulletInChamber(p, m);
        case WeaponEvents.BULLET_IN_MAGAZINE: return new WeaponEventAnimBulletInMagazine(p, m);
        case WeaponEvents.BULLET_SHOW: return new WeaponEventAnimBulletShow(p, m);
        case WeaponEvents.BULLET_SHOW2: return new WeaponEventAnimBulletShow2(p, m);
        case WeaponEvents.CANUNJAM_END: return new WeaponEventAnimCanUnjamEnd(p, m);
        case WeaponEvents.CANUNJAM_START: return new WeaponEventAnimCanUnjamStart(p, m);
        case WeaponEvents.COCKED: return new WeaponEventAnimCocked(p, m);
        case WeaponEvents.MAGAZINE_ATTACHED: return new WeaponEventAnimMagazineAttached(p, m);
        case WeaponEvents.MAGAZINE_DETACHED: return new WeaponEventAnimMagazineDetached(p, m);
        case WeaponEvents.MAGAZINE_HIDE: return new WeaponEventAnimMagazineHide(p, m);
        case WeaponEvents.MAGAZINE_SHOW: return new WeaponEventAnimMagazineShow(p, m);
        case WeaponEvents.SLIDER_OPEN: return new WeaponEventAnimSliderOpen(p, m);
        case WeaponEvents.UNJAMMED: return new WeaponEventAnimUnjammed(p, m);
        case WeaponEvents.HAMMER_UNCOCKED: return new WeaponEventAnimHammerUncocked(p, m);
        case WeaponEvents.HAMMER_COCKED: return new WeaponEventAnimHammerCocked(p, m);
        case WeaponEvents.CYLINDER_ROTATE: return new WeaponEventCylinderRotate(p, m);
        //case WeaponEvents.: return new WeaponEventAnim(p, m);
    }
    return NULL;
}
Referenced by HandleWeaponEvents(), and WeaponEventFactory().
WeaponEventFactory()
WeaponEventBase WeaponEventFactory (WeaponEventID id, int aetype, DayZPlayer p = NULL, Magazine m = NULL)
creates weapon fsm events
Definition at line 223 of file events.c.
{
    switch (id)
    {
        case WeaponEventID.UNKNOWN: return null;
        case WeaponEventID.MECHANISM: return new WeaponEventMechanism(p, m);
        case WeaponEventID.TRIGGER: return new WeaponEventTrigger(p, m);
        case WeaponEventID.TRIGGER_JAM: return new WeaponEventTriggerToJam(p, m);
        case WeaponEventID.LOAD1_BULLET: return new WeaponEventLoad1Bullet(p, m);
        case WeaponEventID.CONTINUOUS_LOADBULLET_START: return new WeaponEventContinuousLoadBulletStart(p, m);
        case WeaponEventID.CONTINUOUS_LOADBULLET_END: return new WeaponEventContinuousLoadBulletEnd(p, m);
        case WeaponEventID.UNJAM: return new WeaponEventUnjam(p, m);
        case WeaponEventID.ATTACH_MAGAZINE: return new WeaponEventAttachMagazine(p, m);
        case WeaponEventID.UNJAMMING_FAILED_TIMEOUT: return new WeaponEventUnjammingFailedTimeout(p, m);
        case WeaponEventID.UNJAMMING_TIMEOUT: return new WeaponEventUnjammingTimeout(p, m);
        case WeaponEventID.DETACH_MAGAZINE: return new WeaponEventDetachMagazine(p, m);
        case WeaponEventID.SWAP_MAGAZINE: return new WeaponEventSwapMagazine(p, m);
        case WeaponEventID.HUMANCOMMAND_ACTION_FINISHED: return new WeaponEventHumanCommandActionFinished(p, m);
        case WeaponEventID.HUMANCOMMAND_ACTION_ABORTED: return new WeaponEventHumanCommandActionAborted(p, m);
        case WeaponEventID.RELOAD_TIMEOUT: return new WeaponEventReloadTimeout(p, m);
        case WeaponEventID.DRY_FIRE_TIMEOUT: return new WeaponEventDryFireTimeout(p, m);
        case WeaponEventID.SET_NEXT_MUZZLE_MODE: return new WeaponEventSetNextMuzzleMode(p, m);
        case WeaponEventID.ANIMATION_EVENT: return WeaponAnimEventFactory(aetype, p, m);
    }
    return NULL;
}
References WeaponAnimEventFactory().
Referenced by CreateWeaponEventFromContext().