DayzKode: P:/scripts/4_world/DayZ/entities/explosivesbase.c File Reference
explosivesbase.c File Reference
Classes
class ExplosiveLight
Functions
void Arm ()
bool CanBeArmed ()
bool CanBeDisarmed ()
protected void CreateLight ()
protected void DestroyParticle (Particle p)
void Disarm (bool pWithTool=false)
override void EEDelete (EntityAI parent)
override void EEKilled (Object killer)
void ExplosivesBase ()
bool GetArmed ()
bool GetDefused ()
bool HasLockedTriggerSlots ()
protected void InitiateExplosion ()
override bool IsExplosive ()
override bool IsInventoryVisible ()
override bool IsTakeable ()
bool IsTimerDetonable ()
void LockTriggerSlots ()
void OnArmed ()
override void OnCEUpdate ()
void OnDisarmed (bool pWithTool)
protected void OnExplode ()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void SetActions ()
void SetAmmoType (string pAmmoType)
void SetAmmoTypes (array< string > pAmmoTypes)
protected void SetArmed (bool state)
protected void SetDefused (bool state)
void SetParticleExplosion (int particle)
void SetParticleOrientation (vector local_ori)
void SetParticlePosition (vector local_pos)
set position for smoke particle - needs to be in Local Space
void UnlockTriggerSlots ()
void UpdateLED (int pState)
HELPERS.
Variables
protected const string ANIM_PHASE_VISIBILITY = "Visibility"
ExplosiveLight DEFAULT_AMMO_TYPE = "Explosion_NonLethal"
protected ref array< string > m_AmmoTypes
protected bool m_Armed
protected bool m_Defused
protected ref Timer m_DeleteTimer
protected ExplosiveLight m_Light
light
protected Particle m_ParticleExplosion
particle
protected ref array< ParticleSource > m_ParticleExplosionArr = {}
protected int m_ParticleExplosionId
protected vector m_ParticleOrientation
protected vector m_ParticlePosition
Function Documentation
Arm()
void Arm ()
Definition at line 165 of file explosivesbase.c.
    {
        SetArmed(true);
        OnArmed();
    }
References OnArmed(), and SetArmed().
Referenced by Grenade_ChemGas::Grenade_ChemGas(), ClaymoreMine::OnPlacementComplete(), ImprovisedExplosive::OnTriggerAttached(), Plastic_Explosive::OnTriggerAttached(), SetAlarmInXMins(), and TurnOn().
CanBeArmed()
bool CanBeArmed ()
Definition at line 174 of file explosivesbase.c.
    {
        return true;
    }
CanBeDisarmed()
bool CanBeDisarmed ()
Definition at line 188 of file explosivesbase.c.
    {
        return false;
    }
CreateLight()
protected void CreateLight ()
Definition at line 103 of file explosivesbase.c.
    {
        m_Light = ExplosiveLight.Cast(ScriptedLightBase.CreateLight(ExplosiveLight, GetPosition()));
    }
References GetPosition, and m_Light.
Referenced by EntityLightSource::CreateLightAtObjMemoryPoint(), and OnExplosionEffects().
DestroyParticle()
protected void DestroyParticle (Particle p)
Definition at line 108 of file explosivesbase.c.
    {
        #ifndef SERVER
        if (p != null)
        {
            p.Stop();
        }
        #endif
    }
References Particle::Stop().
Referenced by EEDelete(), and RefreshParticlesAndSounds().
Disarm()
void Disarm (bool pWithTool = false)
Definition at line 179 of file explosivesbase.c.
    {
        SetArmed(false);
        OnDisarmed(pWithTool);
    }
References OnDisarmed(), and SetArmed().
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 65 of file explosivesbase.c.
    {
        super.EEDelete(parent);
        if (m_ParticleExplosion)
        {
            foreach (ParticleSource p : m_ParticleExplosionArr)
            {
                DestroyParticle(p);
            }
        }
    }
References DestroyParticle(), m_ParticleExplosion, and m_ParticleExplosionArr.
EEKilled()
override void EEKilled (Object killer)
should be called only here to avoid multiple explosion calculations, call SetHealth("","",0.0) instead
Definition at line 78 of file explosivesbase.c.
    {
        super.EEKilled(killer);
        InitiateExplosion();
    }
References InitiateExplosion().
ExplosivesBase()
void ExplosivesBase ()
no effect
Definition at line 288 of file explosivesbase.c.
    {
        m_DeleteTimer   = new Timer();
        m_AmmoTypes     = new array<string>();
        SetAmmoType(DEFAULT_AMMO_TYPE);
        SetParticleExplosion(ParticleList.INVALID);
        SetParticlePosition(WorldToModel(GetPosition()));
        SetParticleOrientation(vector.Zero);
        RegisterNetSyncVariableBool("m_Armed");
        RegisterNetSyncVariableBool("m_Defused");
    }
References DEFAULT_AMMO_TYPE, GetPosition, ParticleList::INVALID, m_AmmoTypes, m_DeleteTimer, SetAmmoType(), SetParticleExplosion(), SetParticleOrientation(), SetParticlePosition(), WorldToModel(), and vector::Zero.
Referenced by ActionArmExplosive::ActionCondition(), ActionCondition(), ActionTriggerRemotely::ActionCondition(), CreateRemoteDetonatorReceiverAsAttachment(), OnEndServer(), OnFinishProgressClient(), ActionArmExplosive::OnFinishProgressServer(), OnFinishProgressServer(), Plastic_Explosive::OnWasAttached(), and Plastic_Explosive::OnWasDetached().
GetArmed()
bool GetArmed ()
Definition at line 193 of file explosivesbase.c.
    {
        return m_Armed;
    }
References m_Armed.
Referenced by ClaymoreMine::AfterStoreLoad(), ImprovisedExplosive::CanBeArmed(), Plastic_Explosive::CanBeArmed(), ClaymoreMine::CanBeDisarmed(), Plastic_Explosive::CanBeDisarmed(), ImprovisedExplosive::CanReceiveAttachment(), Plastic_Explosive::CanReceiveAttachment(), ClaymoreMine::GetViewIndex(), ImprovisedExplosive::IsDeployable(), Plastic_Explosive::IsDeployable(), ClaymoreMine::IsTakeable(), ImprovisedExplosive::IsTakeable(), Plastic_Explosive::IsTakeable(), ClaymoreMine::OnActivatedByItem(), ImprovisedExplosive::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), OnCEUpdate(), and ClaymoreMine::UpdateVisuals().
GetDefused()
bool GetDefused ()
Definition at line 204 of file explosivesbase.c.
    {
        return m_Defused;
    }
References m_Defused.
Referenced by ClaymoreMine::InitiateExplosion(), and ClaymoreMine::UpdateVisuals().
HasLockedTriggerSlots()
bool HasLockedTriggerSlots ()
Definition at line 280 of file explosivesbase.c.
    {
        return false;
    }
InitiateExplosion()
protected void InitiateExplosion ()
Definition at line 118 of file explosivesbase.c.
    {
        int count = m_AmmoTypes.Count();
        for (int i = 0; i < count; i++)
        {
            Explode(DamageType.EXPLOSION, m_AmmoTypes[i]);
        }
        OnExplode();
    }
References Explode(), m_AmmoTypes, and OnExplode().
Referenced by EEKilled(), and Plastic_Explosive::OnActivatedByItem().
IsExplosive()
override bool IsExplosive ()
Definition at line 40 of file explosivesbase.c.
    {
        return true;
    }
IsInventoryVisible()
override bool IsInventoryVisible ()
Definition at line 145 of file explosivesbase.c.
    {
        if (!super.IsInventoryVisible())
        {
            return false;
        }
        return GetAnimationPhase("Visibility") == 0;
    }
IsTakeable()
override bool IsTakeable ()
Definition at line 155 of file explosivesbase.c.
    {
        return super.IsTakeable() && GetAnimationPhase("Visibility") == 0;
    }
Referenced by CanPutInCargo(), CanPutIntoHands(), and CanRemoveFromHands().
IsTimerDetonable()
bool IsTimerDetonable ()
Definition at line 160 of file explosivesbase.c.
    {
        return false;
    }
LockTriggerSlots()
void LockTriggerSlots ()
OnArmed()
void OnArmed ()
Referenced by Arm().
OnCEUpdate()
override void OnCEUpdate ()
Definition at line 86 of file explosivesbase.c.
    {
        super.OnCEUpdate();
        if (!IsRuined() && GetArmed() && GetPairDevice())
        {
            if (vector.DistanceSq(GetPosition(), GetPairDevice().GetPosition()) <= Math.SqrFloat(UAMaxDistances.EXPLOSIVE_REMOTE_ACTIVATION))
            {
                UpdateLED(ERemoteDetonatorLEDState.LIT);
                return;
            }
        }
        UpdateLED(ERemoteDetonatorLEDState.OFF);
    }
References vector::DistanceSq(), UAMaxDistances::EXPLOSIVE_REMOTE_ACTIVATION, GetArmed(), GetPosition, IsRuined(), Math::SqrFloat(), and UpdateLED().
OnDisarmed()
void OnDisarmed (bool pWithTool)
Referenced by Disarm().
OnExplode()
protected void OnExplode ()
Definition at line 129 of file explosivesbase.c.
    {
        if (GetGame().IsServer())
        {
            m_DeleteTimer.Run(0.25, this, "DeleteSafe");
        }
    }
References GetGame(), and m_DeleteTimer.
Referenced by InitiateExplosion(), and Grenade_Base::InitiateExplosion().
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
Definition at line 45 of file explosivesbase.c.
    {
        super.OnExplosionEffects(source, directHit, componentIndex, surface, pos, surfNormal, energyFactor, explosionFactor, isWater, ammoType);
        if (m_ParticleExplosionId > ParticleList.INVALID)
        {
            EntityAI parent = this;
            if (GetHierarchyParent())
            {
                parent = GetHierarchyParent();
            }
            ParticleSource p = ParticleManager.GetInstance().PlayOnObject(m_ParticleExplosionId, parent, m_ParticlePosition, m_ParticleOrientation);
            m_ParticleExplosionArr.Insert(p);
            m_ParticleExplosion = p;
        }
        CreateLight();
    }
References CreateLight(), ParticleList::INVALID, m_ParticleExplosion, m_ParticleExplosionArr, m_ParticleExplosionId, m_ParticleOrientation, m_ParticlePosition, and ParticleManager().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 259 of file explosivesbase.c.
    {
        if (!super.OnStoreLoad(ctx, version))
            return false;
        if (version > 129)
        {
            bool armed = false;
            if (!ctx.Read(armed))
            {
                return false;
            }
            SetArmed(armed);
        }
        return true;
    }
References Serializer::Read(), and SetArmed().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 252 of file explosivesbase.c.
    {
        super.OnStoreSave(ctx);
        ctx.Write(m_Armed);
    }
References m_Armed, and Serializer::Write().
SetActions()
override void SetActions ()
Definition at line 137 of file explosivesbase.c.
    {
        super.SetActions();
        AddAction(ActionAttach);
        AddAction(ActionDetach);
    }
References ActionAttach(), ActionDetach(), and AddAction().
SetAmmoType()
void SetAmmoType (string pAmmoType)
Definition at line 215 of file explosivesbase.c.
    {
        SetAmmoTypes({pAmmoType});
    }
References SetAmmoTypes().
Referenced by ExplosivesBase(), Grenade_Base::FlashGrenade(), SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), Grenade_Base::M67Grenade(), Plastic_Explosive::Plastic_Explosive(), SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase(), Grenade_Base::RGD5Grenade(), and SmokeGrenadeBase().
SetAmmoTypes()
void SetAmmoTypes (array< string > pAmmoTypes)
Definition at line 220 of file explosivesbase.c.
    {
        m_AmmoTypes.Clear();
        m_AmmoTypes = pAmmoTypes;
    }
References m_AmmoTypes.
Referenced by ClaymoreMine::ClaymoreMine(), and SetAmmoType().
SetArmed()
protected void SetArmed (bool state)
Definition at line 198 of file explosivesbase.c.
    {
        m_Armed = state;
        SetSynchDirty();
    }
References m_Armed.
Referenced by Arm(), Disarm(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), and OnStoreLoad().
SetDefused()
protected void SetDefused (bool state)
Definition at line 209 of file explosivesbase.c.
    {
        m_Defused = state;
        SetSynchDirty();
    }
References m_Defused.
Referenced by ClaymoreMine::OnDisarmed().
SetParticleExplosion()
void SetParticleExplosion (int particle)
Definition at line 226 of file explosivesbase.c.
    {
        m_ParticleExplosionId = particle;
    }
References m_ParticleExplosionId.
Referenced by ClaymoreMine::ClaymoreMine(), ExplosivesBase(), Grenade_Base::FlashGrenade(), Grenade_ChemGas::Grenade_ChemGas(), Grenade_Base::M67Grenade(), Plastic_Explosive::Plastic_Explosive(), and Grenade_Base::RGD5Grenade().
SetParticleOrientation()
void SetParticleOrientation (vector local_ori)
Definition at line 242 of file explosivesbase.c.
    {
        m_ParticleOrientation = local_ori;
        if (GetHierarchyParent())
        {
            m_ParticleOrientation = GetHierarchyParent().WorldToModel(GetOrientation());
        }
    }
References GetOrientation(), and m_ParticleOrientation.
Referenced by ClaymoreMine::ClaymoreMine(), and ExplosivesBase().
SetParticlePosition()
void SetParticlePosition (vector local_pos)
set position for smoke particle - needs to be in Local Space
Definition at line 232 of file explosivesbase.c.
    {
        m_ParticlePosition = local_pos;
        if (GetHierarchyParent())
        {
            m_ParticlePosition = GetHierarchyParent().WorldToModel(GetPosition());
        }
    }
References GetPosition, and m_ParticlePosition.
Referenced by ExplosivesBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
UnlockTriggerSlots()
void UnlockTriggerSlots ()
UpdateLED()
void UpdateLED (int pState)
HELPERS.
Variable Documentation
ANIM_PHASE_VISIBILITY
protected const string ANIM_PHASE_VISIBILITY = "Visibility"
Definition at line 22 of file explosivesbase.c.
Referenced by ImprovisedExplosive::OnActivatedByItem().
DEFAULT_AMMO_TYPE
ExplosiveLight DEFAULT_AMMO_TYPE = "Explosion_NonLethal"
Referenced by ExplosivesBase().
m_AmmoTypes
protected ref array<string> m_AmmoTypes
Definition at line 26 of file explosivesbase.c.
Referenced by ExplosivesBase(), InitiateExplosion(), Grenade_Base::InitiateExplosion(), and SetAmmoTypes().
m_Armed
protected bool m_Armed
Definition at line 24 of file explosivesbase.c.
Referenced by GetArmed(), OnStoreSave(), and SetArmed().
m_Defused
protected bool m_Defused
Definition at line 25 of file explosivesbase.c.
Referenced by GetDefused(), and SetDefused().
m_DeleteTimer
protected ref Timer m_DeleteTimer
Definition at line 28 of file explosivesbase.c.
Referenced by EntityLightSource::DeleteLightWithDelay(), DeleteThis(), ExplosivesBase(), and OnExplode().
m_Light
protected ExplosiveLight m_Light
light
Definition at line 31 of file explosivesbase.c.
Referenced by Clothing::AttachLightOnHead(), Clothing::CreateHeadtorchLight(), CreateLight(), Grenade_Base::CreateLight(), BuildingSuper::EEDelete(), BuildingSuper::EEInit(), GetLightEntity(), ItemBase::OnItemLocationChanged(), Headtorch_Black::OnLightCreated(), Clothing::OnLightCreated(), ItemBase::OnSwitchOff(), Clothing::OnWasAttached(), Clothing::OnWasDetached(), Clothing::OnWork(), ItemBase::OnWork(), Switchable_Base::OnWork(), ItemBase::OnWorkStart(), Switchable_Base::OnWorkStart(), ItemBase::OnWorkStop(), Clothing::OnWorkStop(), Switchable_Base::OnWorkStop(), and SetLightEntity().
m_ParticleExplosion
protected Particle m_ParticleExplosion
particle
Definition at line 34 of file explosivesbase.c.
Referenced by EEDelete(), OnExplode(), and OnExplosionEffects().
m_ParticleExplosionArr
protected ref array<ParticleSource> m_ParticleExplosionArr = {}
Definition at line 35 of file explosivesbase.c.
Referenced by EEDelete(), and OnExplosionEffects().
m_ParticleExplosionId
protected int m_ParticleExplosionId
Definition at line 36 of file explosivesbase.c.
Referenced by OnExplosionEffects(), and SetParticleExplosion().
m_ParticleOrientation
protected vector m_ParticleOrientation
Definition at line 38 of file explosivesbase.c.
Referenced by OnExplosionEffects(), and SetParticleOrientation().
m_ParticlePosition
protected vector m_ParticlePosition
Definition at line 37 of file explosivesbase.c.
Referenced by OnExplosionEffects(), PlaySmokeParticle(), and SetParticlePosition().