DayzKode: P:/scripts/4_world/DayZ/entities/itembase/gear/tools/fireworkslauncher.c File Reference
fireworkslauncher.c File Reference
Classes
class ExplosionLight
class FireworksLauncher
class FireworksLauncherClientEvent
Functions
void ExplosionLight ()
override protected float GetExplosionDistance ()
override protected vector GetExplosionPosition ()
override protected vector GetShotPos ()
void Init (vector pos)
override void OnExplode ()
ExplosionLight PointLightBase OnFired ()
Variables
FireworksLauncherClientEvent m_ShotPos
Function Documentation
ExplosionLight()
void OnFired::ExplosionLight ()
Definition at line 0 of file fireworkslauncher.c.
                     : PointLightBase
{
    void ExplosionLight()
    {
        SetVisibleDuringDaylight(true);
        SetRadiusTo(80);
        SetBrightnessTo(0.05);
        SetFlareVisible(false);
        SetAmbientColor(1.0, 1.0, 1.0);
        SetDiffuseColor(1.0, 1.0, 1.0);
        SetLifetime(2.1);
        SetDisableShadowsWithinRadius(-1);
        SetFadeOutTime(1);
        m_FadeInTime = 0.25;
        SetFlickerSpeed(7);
        //SetFlickerAmplitude(0.5);
GetExplosionDistance()
override protected float GetExplosionDistance ()
Definition at line 304 of file fireworkslauncher.c.
    {
        return Math.RandomFloatInclusive(10,15);
    }
References Math::RandomFloatInclusive().
GetExplosionPosition()
override protected vector GetExplosionPosition ()
Definition at line 286 of file fireworkslauncher.c.
    {
        return GetShotPos() + m_ShotDir * GetExplosionDistance();
    }
References FireworksLauncherClientEvent::GetExplosionDistance(), and FireworksLauncherClientEvent::GetShotPos().
GetShotPos()
override protected vector GetShotPos ()
Definition at line 299 of file fireworkslauncher.c.
    {
        return m_ShotPos;
    }
References m_ShotPos.
Init()
void Init (vector pos)
Definition at line 291 of file fireworkslauncher.c.
    {
        m_ShotPos = pos;
        m_ShotDir[0] = Math.RandomFloatInclusive(-1,1);
        m_ShotDir[1] = Math.RandomFloatInclusive(-1,1);
        m_ShotDir[2] = Math.RandomFloatInclusive(-1,1);
        m_ShotDir.Normalize();
    }
References m_ShotPos, and Math::RandomFloatInclusive().
OnExplode()
override void OnExplode ()
Definition at line 309 of file fireworkslauncher.c.
    {
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( PlayExplosionSound, GetSoundDelay(), false);
        GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( SpawnLight, GetLightDelay(), false);
        m_ParticleExplosion = ParticleManager.GetInstance().PlayInWorld(GetExplParticleFromSequence(), GetExplosionPosition());
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), FireworksLauncherClientEvent::GetExplosionPosition(), FireworksLauncherClientEvent::GetExplParticleFromSequence(), GetGame(), FireworksLauncherClientEvent::GetLightDelay(), FireworksLauncherClientEvent::GetSoundDelay(), m_ParticleExplosion, and ParticleManager().
OnFired()
ExplosionLight PointLightBase OnFired ()
Variable Documentation
m_ShotPos
FireworksLauncherClientEvent m_ShotPos
Referenced by GetShotPos(), and Init().