DayzKode: P:/scripts/4_world/DayZ/entities/itembase/fireworksbase.c File Reference
fireworksbase.c File Reference
Enumerations
enum EFireworksState {
DEFAULT , PLACED , IGNITED , FIRING ,
FINISHED
}
Functions
override protected bool CanBeIgnitedBy (EntityAI igniter=NULL)
override void EEOnCECreate ()
void FireworksBase ()
protected float GetEventDelay ()
protected float GetMaxAllowedWetness ()
protected EFireworksState GetState ()
returns one of STATE_...
override bool HasFlammableMaterial ()
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
protected void OnEventServer (int type)
Called periodically after the entity gets ignited.
override protected void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
override protected void OnInventoryEnter (Man player)
override protected void OnInventoryExit (Man player)
protected void OnStateChangedClient (EFireworksState currentState)
protected void OnStateChangedServer (EFireworksState currentState)
override protected void OnVariablesSynchronized ()
override protected void SetActions ()
protected void SetState (EFireworksState state)
protected void StandUp ()
Variables
protected int m_RandomSeed
enum EFireworksState m_State
protected EFireworksState m_StatePrev
protected ref Timer m_TimerEvent
Enumeration Type Documentation
EFireworksState
enum EFireworksState
Enumerator
DEFAULT
PLACED
IGNITED
FIRING
FINISHED
Definition at line 2 of file fireworksbase.c.
{
    DEFAULT,
    PLACED,
    IGNITED,
    FIRING,
    FINISHED
}
Function Documentation
CanBeIgnitedBy()
override protected bool CanBeIgnitedBy (EntityAI igniter = NULL)
Definition at line 102 of file fireworksbase.c.
    {
        if (GetWet() >= GetMaxAllowedWetness())
        {
            return false;
        }
        if (MiscGameplayFunctions.IsUnderRoofEx(this, 60))
        {
            return false;
        }
        if ((GetState() <= EFireworksState.PLACED) && vector.Dot(vector.Up,GetDirectionUp()) > 0.95)
        {
            return true;
        }
        return false;
    }
References vector::Dot(), GetDirectionUp(), GetMaxAllowedWetness(), Inventory_Base::GetState(), GetWet(), and vector::Up.
EEOnCECreate()
override void EEOnCECreate ()
Definition at line 23 of file fireworksbase.c.
    {
        StandUp();
    }
References StandUp().
FireworksBase()
void FireworksBase ()
Definition at line 18 of file fireworksbase.c.
    {
        Init();
    }
References Init().
Referenced by ActionConditionContinue().
GetEventDelay()
protected float GetEventDelay ()
Definition at line 124 of file fireworksbase.c.
    {
        return 0;
    }
GetMaxAllowedWetness()
protected float GetMaxAllowedWetness ()
Definition at line 46 of file fireworksbase.c.
    {
        return 0.1;
    }
Referenced by CanBeIgnitedBy().
GetState()
protected EFireworksState GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 51 of file fireworksbase.c.
    {
        return m_State;
    }
References Inventory_Base::m_State.
HasFlammableMaterial()
override bool HasFlammableMaterial ()
Definition at line 41 of file fireworksbase.c.
    {
        return true;
    }
Init()
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
pre-init arrays
Definition at line 84 of file ppemanager.c.
    {
        //DbgPrnt("PPEDebug | PPEManager | m_ManagerInitialized: " + m_ManagerInitialized);
        if (!m_ManagerInitialized)
        {
            m_PPEMaterialUpdateQueueMap = new map<int, ref array<int>>;
            m_UpdatedMaterials = new array<int>;
            m_ExistingPostprocessRequests = new array<ref PPERequesterBase>;
            m_UpdatingRequests = new array<ref PPERequesterBase>;
            InitPPEManagerClassMap();
            GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(this.Update); //can be safely and easily 'disabled' here
            m_ManagerInitialized = true;
        }
    }
References AddModifier(), CALL_CATEGORY_GUI, CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), Class::CastTo(), WorkspaceWidget::CreateWidgets(), DrawConnectingLines(), UIScriptedMenu::DrawConnectingLines(), FISH_AGILITY, CGame::GetCallQueue(), GetGame(), GetPlayer(), InputUtils::GetRichtextButtonIconFromInputAction(), CGame::GetUpdateQueue(), CGame::GetWorkspace(), hndDebugPrint(), InputUtils::ICON_SCALE_TOOLBAR, INDEX_NOT_FOUND, INIT_LINE_STRETCH, InitPPEManagerClassMap(), InjectDamageSystemValues(), ScriptInvoker::Insert(), IsCameraNV(), LateInit(), m_Back, m_BurnTimePerFullFuelDose, FlammableBase::m_BurnTimePerFullFuelDoseEx, m_BurnTimePerFullLard, FlammableBase::m_BurnTimePerFullLardEx, m_BurnTimePerRag, FlammableBase::m_BurnTimePerRagEx, m_ChanceRange, m_context_menu, m_CrossHairs, m_Cycler, m_CyclerCatching, m_DrainValvePressureDeanimationSettings, m_DrainValvePressureStageSettings, m_DrainValveWaterStageSettings, m_ExistingPostprocessRequests, m_FillValvePressureDeanimationSettings, m_FillValvePressureStageSettings, m_FillValveWaterStageSettings, m_FishingTime, m_FishProximity, m_FSwapping, m_FSwappingInst, m_Inventory, m_IsFishPulling, m_LastActiveValve, m_ManagerInitialized, m_MaxConsumableFuelQuantity, FlammableBase::m_MaxConsumableFuelQuantityEx, m_MaxConsumableLardQuantity, FlammableBase::m_MaxConsumableLardQuantityEx, m_MovingTo, m_Name, m_Notifiers, m_opticsUsed, m_PipeBrokenParticles, m_PipeSounds, m_Player, m_Pos, m_PPEMaterialUpdateQueueMap, m_pPlayer, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_Pull, m_RegisteredDepletionModifiers, m_RegisteredRecoveryModifiers, m_Root, m_Swapping, m_tab_images, m_TabScript, m_Taking, m_UpdatedMaterials, m_UpdatingRequests, m_ValveManipulatedIndex, m_ValveManipulatedIndexPrev, m_ValveNames, m_ValveParticles, m_ValveStates, m_WaterLevelActual, m_WaterLevelPrev, m_WaterLevelsAvailable, m_WaterLevelSnapshot, m_WaterLevelTimesAccumulated, MAX_FISHING_TIME, MIN_FISHING_TIME, PIPES_BROKEN_COUNT, Math::RandomInt(), SetCameraNV(), SetCameraNVType(), MaskMdfr::STAMINA_DEPLETION_MODIFIER, FatigueMdfr::STAMINA_DEPLETION_MULTIPLIER, EpinephrineMdfr::STAMINA_DEPLETION_MULTIPLIER, MaskMdfr::STAMINA_RECOVERY_MODIFIER, FatigueMdfr::STAMINA_RECOVERY_MULTIPLIER, DrowningMdfr::STAMINA_RECOVERY_MULTIPLIER, Update(), UpdateConstructionParts(), UpdatePlayerStatsValues(), VALVES_COUNT, WL_AVERAGE, WL_MAX, and WL_MIN.
Referenced by ClockBase(), DayZPlayerCameraBase(), DayZPlayerCameraBase::DayZPlayerCameraIronsights(), DayZPlayerImplementMeleeCombat(), DayZPlayerMeleeFightLogic_LightHeavy(), Environment::Environment(), FireworksBase(), Land_Underground_WaterReservoir(), Link< Class T >::Link(), LoginQueueBase::LoginQueueStatic(), LoginTimeBase::LoginTimeStatic(), ModifiersManager(), NotifiersManager(), ManBase::PlayerBase(), PlayerStats::PlayerStats(), PPEClassBase::PPEClassBase(), RemotePlayerStatDebug(), StaminaHandler(), UniversalTemperatureSourceDebug::UniversalTemperatureSource(), and DayZInfected::ZombieBase().
OnEventServer()
protected void OnEventServer (int type)
Called periodically after the entity gets ignited.
OnIgnitedThis()
override protected void OnIgnitedThis (EntityAI fire_source)
Executed on Server when some item ignited this one.
Definition at line 96 of file fireworksbase.c.
    {
        SetState(EFireworksState.IGNITED);
    }
References Inventory_Base::SetState().
OnInventoryEnter()
override protected void OnInventoryEnter (Man player)
Definition at line 71 of file fireworksbase.c.
    {
        if (GetState() == EFireworksState.PLACED)
        {
            SetState(EFireworksState.DEFAULT);
        }
    }
References Inventory_Base::GetState(), and Inventory_Base::SetState().
OnInventoryExit()
override protected void OnInventoryExit (Man player)
Definition at line 79 of file fireworksbase.c.
    {
        super.OnInventoryExit(player);
        if (!IsBeingPlaced())
            StandUp();
    }
References IsBeingPlaced(), and StandUp().
OnStateChangedClient()
protected void OnStateChangedClient (EFireworksState currentState)
Referenced by OnVariablesSynchronized().
OnStateChangedServer()
protected void OnStateChangedServer (EFireworksState currentState)
Referenced by SetState().
OnVariablesSynchronized()
override protected void OnVariablesSynchronized ()
Definition at line 129 of file fireworksbase.c.
    {
        //Print("new state client: " + m_State);
        super.OnVariablesSynchronized();
        if (m_State != m_StatePrev)
        {
            OnStateChangedClient(m_State);
            m_StatePrev = m_State;
        }
    }
References m_State, Inventory_Base::m_State, m_StatePrev, and OnStateChangedClient().
SetActions()
override protected void SetActions ()
Definition at line 32 of file fireworksbase.c.
    {
        super.SetActions();
        AddAction(ActionTogglePlaceObject);
        AddAction(ActionDeployObject);
        AddAction(ActionLightItemOnFire);
    }
References ActionDeployObject(), ActionLightItemOnFire(), and AddAction().
SetState()
protected void SetState (EFireworksState state)
Definition at line 56 of file fireworksbase.c.
    {
        if (state != m_StatePrev && GetGame().IsServer())
        {
            m_State = state;
            SetSynchDirty();
            OnStateChangedServer(state);
            m_StatePrev = state;
        }
    }
References GetGame(), m_State, m_StatePrev, and OnStateChangedServer().
StandUp()
protected void StandUp ()
Definition at line 87 of file fireworksbase.c.
    {
        if (!IsRuined())
        {
            SetOrientation(vector.Zero);
        }
    }
References IsRuined(), SetOrientation(), and vector::Zero.
Referenced by EEOnCECreate(), and OnInventoryExit().
Variable Documentation
m_RandomSeed
protected int m_RandomSeed
Definition at line 16 of file fireworksbase.c.
Referenced by FireworksLauncher::FireworksLauncher(), and FireworksLauncher::OnVariablesSynchronized().
m_State
enum EFireworksState m_State
m_StatePrev
protected EFireworksState m_StatePrev
Definition at line 14 of file fireworksbase.c.
m_TimerEvent
protected ref Timer m_TimerEvent
Definition at line 15 of file fireworksbase.c.
Referenced by FireworksLauncher::OnEventServer(), FireworksLauncher::OnIgnitedThis(), and FireworksLauncher::RestartEventTimer().