DayzKode: P:/scripts/4_world/DayZ/entities/itembase/fireplacebase.c File Reference
fireplacebase.c File Reference
Enumerations
enum FireplaceFireState {
NO_FIRE = 1 , START_FIRE = 2 , SMALL_FIRE = 3 , NORMAL_FIRE = 4 ,
END_FIRE = 5 , EXTINGUISHING_FIRE = 6 , EXTINGUISHED_FIRE = 7 , REIGNITED_FIRE = 8 ,
COUNT = 9
}
Functions
protected void AddDamageToItemByFire (ItemBase item, bool can_be_ruined)
protected void AddDamageToItemByFireEx (ItemBase item, bool can_be_ruined, bool pAttachment)
protected void AddTemperatureToFireplace (float amount)
DEPRECATED.
protected void AddTemperatureToItemByFire (ItemBase item)
protected void AddToFireConsumables (ItemBase item)
void AddWetnessToFireplace (float amount)
protected void AddWetnessToItem (ItemBase item, float amount)
override void AfterStoreLoad ()
protected void BurnItemsInFireplace ()
protected void CalcAndSetQuantity ()
protected void CalcAndSetTotalEnergy ()
bool CanBuildOven ()
bool CanBuildStoneCircle ()
bool CanCookOnStick ()
bool CanDismantleOven ()
bool CanDismantleStoneCircle ()
bool CanExtinguishFire ()
override bool CanHaveTemperature ()
override bool CanHaveWetness ()
override bool CanReleaseAttachment (EntityAI attachment)
bool CanShowSmoke ()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
void ClearCookingEquipment ()
DEPRECATED.
void ClearCookingEquipment (ItemBase pItem)
protected void CookOnDirectSlot (ItemBase slot_item, float temp_equip, float temp_ext)
protected void CookWithEquipment ()
protected void Cooling ()
void CreateAreaDamage ()
void DestroyAreaDamage ()
void DestroyFireplace ()
bool DirectCookingSlotsInUse ()
override bool DisassembleOnLastDetach ()
override void EECargoOut (EntityAI item)
override void EEDelete (EntityAI parent)
override void EEInit ()
override void EEItemAttached (EntityAI item, string slot_name)
protected void FireplaceBase ()
float GetAirResistanceForSmokeParticles (float actual_height)
int GetAttachedStonesCount ()
bool GetCeilingHeight (out float actual_height)
ItemBase GetCookingEquipment ()
Cooking GetCookingProcess ()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
protected FireConsumable GetFireConsumableByItem (ItemBase item)
protected float GetFireConsumableTypeEnergy (ItemBase item)
protected vector GetFireEffectPosition ()
protected int GetFireState ()
protected float GetFuelBurnRateMP ()
protected int GetFuelCount ()
bool GetIgniteFailure ()
protected FireConsumable GetItemToConsume ()
protected int GetKindlingCount ()
FireplaceLight GetLightEntity ()
override string GetPlaceSoundset ()
protected vector GetSmokeEffectPosition ()
protected float GetTemperatureLossMP ()
bool HasAnyKindling ()
bool HasAshes ()
bool HasCookingStand ()
bool HasLastAttachment ()
bool HasLastFuelKindlingAttached ()
bool HasStoneCircle ()
bool HasStones ()
protected void Heating ()
bool IsBarrelWithHoles ()
bool IsBaseFireplace ()
bool IsBurning ()
bool IsCargoEmpty ()
bool IsCeilingHighEnoughForSmoke ()
override bool IsEmpty ()
static bool IsEntityOnInteriorSurface (notnull EntityAI entity_ai)
static bool IsEntityOnWaterSurface (notnull EntityAI entity_ai)
static bool IsEntityWet (notnull EntityAI entity_ai)
bool IsFacingFireplace (PlayerBase player)
DEPRECATED.
override bool IsFireplace ()
bool IsFireplaceIndoor ()
protected bool IsFuel (ItemBase item)
bool IsInAnimPhase (string anim_phase)
bool IsIndoorOven ()
bool IsItemAttachedQuantity (typename item_type, float quantity)
bool IsItemTypeAttached (typename item_type)
protected bool IsKindling (ItemBase item)
bool IsOnInteriorSurface ()
bool IsOnWaterSurface ()
override bool IsOpen ()
bool IsOven ()
override bool IsPrepareToDelete ()
bool IsRainingAbove ()
static bool IsRainingAboveEntity (notnull EntityAI entity_ai)
bool IsRoofAbove ()
bool IsSpaceFor (vector size)
bool IsSpaceForCircle ()
bool IsSpaceForOven ()
bool IsWet ()
static bool IsWindy ()
void LockOvenAttachments (bool lock)
override void OnAttachmentQuantityChanged (ItemBase item)
override void OnAttachmentRuined (EntityAI attachment)
override void OnDebugButtonPressServer (int button_index)
override void OnDebugSpawn ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
override bool OnStoreLoad (ParamsReadContext ctx, int version)
override void OnStoreSave (ParamsWriteContext ctx)
override void OnVariablesSynchronized ()
protected void ParticleFireEndStart ()
protected void ParticleFireEndStop ()
protected void ParticleFireStartStart ()
protected void ParticleFireStartStop ()
protected void ParticleFireWindyNoIgniteStart ()
protected void ParticleNormalFireStart ()
protected void ParticleNormalFireStop ()
protected void ParticleNormalSmokeStart ()
protected void ParticleNormalSmokeStop ()
protected void ParticleSmallFireStart ()
protected void ParticleSmallFireStop ()
protected void ParticleSmallSmokeStart ()
protected void ParticleSmallSmokeStop ()
protected void ParticleSteamEndStart ()
protected void ParticleSteamEndStop ()
protected void ParticleSteamExtinguishingStart ()
protected void ParticleSteamExtinguishingStop ()
protected void ParticleWetNoIgniteStart ()
protected void ParticleWetNoIgniteStop ()
protected bool PlayParticle (out Particle particle, int particle_type, vector pos, bool worldpos=false)
protected void RefreshFireParticlesAndSounds (bool force_refresh)
void RefreshFireplacePhysics ()
void RefreshFireplaceVisuals ()
void RefreshFireState ()
protected void RemoveFromFireConsumables (FireConsumable fire_consumable)
protected void SetAshesState (bool has_ashes)
protected void SetBurningState (bool is_burning)
protected void SetBurntFirewood ()
void SetCookingEquipment (ItemBase equipment)
void SetExtinguishingState ()
protected void SetFireState (FireplaceFireState state)
protected void SetFuelBurnRateMP (float value)
void SetIgniteFailure (bool failure)
protected FireConsumable SetItemToConsume ()
void SetLightEntity (FireplaceLight light)
void SetOvenState (bool is_oven)
void SetStoneCircleState (bool has_stonecircle)
protected void SetTemperatureLossMP (float value)
protected void SmokeOnSmokingSlot (ItemBase slot_item, float temp_equip, float temp_ext)
bool SmokingSlotsInUse ()
protected void SoundFireExtinguishedStart ()
protected void SoundFireExtinguishingStart ()
protected void SoundFireHeavyStart ()
protected void SoundFireLightStart ()
protected void SoundFireNoFireStart ()
protected void SoundFireStop ()
protected void SoundFireWetNoIgniteStart ()
protected void SoundFireWindyNoIgniteStart ()
protected void SpendFireConsumable (float amount)
protected void StartCooling ()
void StartFire (bool force_start=false)
protected void StartHeating ()
protected void StopAllParticlesAndSounds ()
protected void StopCooling ()
void StopFire (FireplaceFireState fire_state=FireplaceFireState.END_FIRE)
protected void StopHeating ()
protected bool StopParticle (out Particle particle)
void Synchronize ()
protected void TransferHeatToNearPlayers ()
DEPRECATED.
protected void ~FireplaceBase ()
Variables
const string ANIMATION_ASHES = "Ashes"
const string ANIMATION_BURNT_WOOD = "BurntWood"
const string ANIMATION_CAULDRON_HANDLE = "handle1Rotate"
const string ANIMATION_COOKWARE_HANDLE = "handleRotate"
const string ANIMATION_INVENTORY = "Inventory"
const string ANIMATION_KINDLING = "Kindling"
const string ANIMATION_OVEN = "Oven"
const string ANIMATION_STICKS = "Sticks"
const string ANIMATION_STONE = "Stone"
const string ANIMATION_STONES = "StonesCircle"
const string ANIMATION_TRIPOD = "Tripod"
const string ANIMATION_WOOD = "Wood"
ATTACHMENT_BANDAGE = BandageDressing
ATTACHMENT_BARK_BIRCH = Bark_Birch
ATTACHMENT_BARK_OAK = Bark_Oak
ATTACHMENT_BOOK = ItemBook
ATTACHMENT_CAULDRON = Cauldron
ATTACHMENT_COOKING_POT = Pot
ATTACHMENT_COOKINGSTAND = CookingStand
ATTACHMENT_FIREWOOD = Firewood
ATTACHMENT_FRYING_PAN = FryingPan
ATTACHMENT_GIFTWRAP = GiftWrapPaper
ATTACHMENT_PAPER = Paper
ATTACHMENT_PUNCHEDCARD = PunchedCard
ATTACHMENT_RAGS = Rag
ATTACHMENT_STICKS = WoodenStick
ATTACHMENT_STONES = Stone
ATTACHMENT_TRIPOD = Tripod
const int DIRECT_COOKING_SLOT_COUNT = 3
direct cooking slots
const float DIRECT_COOKING_SPEED = 1.5
const float FUEL_BURN_RATE_DEFAULT = 1.0
const float FUEL_BURN_RATE_OVEN = 0.85
const float FUEL_BURN_RATE_STONES = 0.92
const float IGNITE_WIND_THRESHOLD = 0.8
const int LIFETIME_FIREPLACE_STONE_CIRCLE = 172800
const int LIFETIME_FIREPLACE_STONE_OVEN = 604800
protected ref AreaDamageManager m_AreaDamage
private bool m_CanNoise = true
protected Object m_ClutterCutter
protected ItemBase m_CookingEquipment
protected ref Cooking m_CookingProcess
determines how fast will the fuel item burn before spending (lower is better)
protected ref Timer m_CoolingTimer
protected ItemBase m_DirectCookingSlots [DIRECT_COOKING_SLOT_COUNT]
protected ref map< ItemBase, ref FireConsumable > m_FireConsumables
static protected ref map< typename, ref FireConsumableType > m_FireConsumableTypes
protected FireplaceFireState m_FireState = FireplaceFireState.NO_FIRE
protected float m_FuelBurnRateMP = 1.0
determines how fast will the fireplace loose its temperature when cooling (lower is better)
protected vector m_HalfExtents
protected bool m_HasAshes = false
protected bool m_HasStoneCircle = false
protected ref Timer m_HeatingTimer
enum FireplaceFireState m_IsBurning = false
protected bool m_IsOven = false
protected ref FireConsumable m_ItemToConsume
protected FireplaceFireState m_LastFireState = FireplaceFireState.NO_FIRE
protected FireplaceLight m_Light
protected float m_LightDistance = 2000
protected bool m_NoIgnite = false
ref NoiseParams m_NoisePar
protected int m_OvenAttachmentsLockState = -1
protected Particle m_ParticleFireEnd
protected Particle m_ParticleFireStart
protected Particle m_ParticleNormalFire
protected Particle m_ParticleNormalSmoke
protected Particle m_ParticleSmallFire
protected Particle m_ParticleSmallSmoke
protected Particle m_ParticleSteamEnd
protected Particle m_ParticleSteamExtinguishing
protected bool m_RoofAbove = false
protected ItemBase m_SmokingSlots [SMOKING_SLOT_COUNT]
protected EffectSound m_SoundFire
protected EffectSound m_SoundFireLoop
protected float m_TemperatureLossMP = 1.0
protected float m_TotalEnergy
protected ref UniversalTemperatureSourceLambdaFireplace m_UTSLFireplace
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
const string MATERIAL_FIREPLACE_GLOW = "dz\\gear\\cooking\\data\\stoneground.rvmat"
const string MATERIAL_FIREPLACE_NOGLOW = "dz\\gear\\cooking\\data\\stonegroundnoemit.rvmat"
const int MAX_TEMPERATURE_TO_DISMANTLE_OVEN = 40
minimum amount of stones for oven
const string MESSAGE_BURY_ASHES_FAILED_BURNING = "Cannot bury ashes, the fireplace is still burning."
const string MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY = "Cannot bury ashes. There are sill items in it."
const string MESSAGE_BURY_ASHES_FAILED_SURFACE = "Cannot bury ashes on hard surface."
const string MESSAGE_BURY_ASHES_FAILED_TOO_HOT = "Cannot bury ashes, the fireplace is too hot."
const string MESSAGE_CANNOT_BUILD_OVEN = "Cannot build oven."
const string MESSAGE_CANNOT_DISMANTLE_OVEN = "Cannot dismantle oven."
const string MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED = "You cannot start fire. Fireplace is ruined."
const string MESSAGE_IGNITE_IN_WATER = "I cannot ignite the fireplace in the water."
const string MESSAGE_IGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
const string MESSAGE_IGNITE_RAIN = "The fire went out because of the rain."
const string MESSAGE_IGNITE_TOO_WET = "The fireplace is too wet to be ignited."
const string MESSAGE_IGNITE_UNDER_LOW_ROOF = "I cannot ignite the fireplace here, the is not enough room."
const string MESSAGE_IGNITE_WIND = "The fire went out because of the wind."
const string MESSAGE_REIGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
const string MESSAGE_REIGNITE_RAIN = "Cannot reignite fireplace in rain."
const string MESSAGE_REIGNITE_TOO_WET = "The fireplace is too wet to be reignited."
const float MIN_CEILING_HEIGHT = 5
maximum temperature for dismantling oven
const int MIN_STONES_TO_BUILD_CIRCLE = 8
const int MIN_STONES_TO_BUILD_OVEN = 16
minimum amount of stones for circle
const string OBJECT_CLUTTER_CUTTER = "ClutterCutterFireplace"
const float PARAM_BURN_DAMAGE_COEF = 5.0
base value of fire consumption rate (how many base energy will be spent on each update)
const float PARAM_BURN_WET_THRESHOLD = 0.40
maximum rain value when the fireplace can be ignited
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
temperature threshold for starting coooking process (degree Celsius)
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
maximum temperature of attached cooking equipment (degree Celsius)
const float PARAM_COOKING_TEMP_THRESHOLD = 100
cooking
const float PARAM_FIRE_CONSUM_RATE_AMOUNT = 0.5
value for calculating wetness loss during cooling process
const float PARAM_FULL_HEAT_RADIUS = 2.0
maximum value of temperature of items in fireplace when heating (degree Celsius)
const float PARAM_HEAT_RADIUS = 4.0
radius in which objects are fully heated by fire
const float PARAM_HEAT_THROUGH_AIR_COEF = 0.1
radius in which objects are heated by fire
const float PARAM_IGNITE_RAIN_THRESHOLD = 0.1
minimum fireplace temperature under which the fireplace can be reignited using air only (degree Celsius)
const float PARAM_ITEM_HEAT_MIN_TEMP = 40
value for calculating temperature increase on each heat update interval (degree Celsius)
const float PARAM_ITEM_HEAT_TEMP_INCREASE_COEF = 10
value for calculating damage on items located in fireplace cargo
const float PARAM_MAX_ITEM_HEAT_TEMP_INCREASE = 200
minimum temperature for items that can be heated in fireplace cargo or as attachments (degree Celsius)
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
DEPRECATED value for calculation of heat transfered from fireplace through air to player (environment)
const float PARAM_MAX_WET_TO_IGNITE = 0.2
how much will temperature decrease when fireplace is cooling (degree Celsius)
const float PARAM_MIN_FIRE_TEMPERATURE = 30
maximum fireplace temperature of a normal fire (degree Celsius)
const float PARAM_MIN_TEMP_TO_REIGNITE = 30
maximum wetness value when the fireplace can be ignited
const float PARAM_NORMAL_FIRE_TEMPERATURE = 1000
maximum fireplace temperature of a small fire (degree Celsius)
const float PARAM_SMALL_FIRE_TEMPERATURE = 150
const float PARAM_TEMPERATURE_DECREASE = 20
how much will temperature increase when fireplace is burning (degree Celsius)
const float PARAM_TEMPERATURE_INCREASE = 9
minimum fireplace temperature under which the fireplace is inactive (degree Celsius)
const float PARAM_WET_COOLING_DECREASE_COEF = 0.002
value for calculating wetness loss during heating process
const float PARAM_WET_HEATING_DECREASE_COEF = 0.01
value for calculating of wetness that fireplace gain when raining
const float PARAM_WET_INCREASE_COEF = 0.02
maximum wetness value when the fireplace is able to burn
protected int PARTICLE_FIRE_END = ParticleList.CAMP_FIRE_END
protected int PARTICLE_FIRE_START = ParticleList.CAMP_FIRE_START
protected int PARTICLE_NO_IGNITE_WIND = ParticleList.CAMP_NO_IGNITE_WIND
protected int PARTICLE_NORMAL_FIRE = ParticleList.CAMP_NORMAL_FIRE
protected int PARTICLE_NORMAL_SMOKE = ParticleList.CAMP_NORMAL_SMOKE
protected int PARTICLE_OVEN_FIRE = ParticleList.CAMP_STOVE_FIRE
protected int PARTICLE_OVEN_FIRE_END = ParticleList.CAMP_STOVE_FIRE_END
protected int PARTICLE_OVEN_FIRE_START = ParticleList.CAMP_STOVE_FIRE_START
protected int PARTICLE_SMALL_FIRE = ParticleList.CAMP_SMALL_FIRE
protected int PARTICLE_SMALL_SMOKE = ParticleList.CAMP_SMALL_SMOKE
protected int PARTICLE_STEAM_END = ParticleList.CAMP_STEAM_2END
protected int PARTICLE_STEAM_EXTINGUISHING = ParticleList.CAMP_STEAM_EXTINGUISH_START
const int SMOKING_SLOT_COUNT = 4
const float SMOKING_SPEED = 1
const string SOUND_FIRE_EXTINGUISHED = "ExtinguishByWaterEnd_SoundSet"
const string SOUND_FIRE_EXTINGUISHING = "ExtinguishByWater_SoundSet"
const string SOUND_FIRE_HEAVY = "HeavyFire_SoundSet"
const string SOUND_FIRE_LIGHT = "LightFire_SoundSet"
const string SOUND_FIRE_NO_FIRE = "NoFuelFire_SoundSet"
const float TEMPERATURE_LOSS_MP_DEFAULT = 1.0
min height of ceiling for fire to be ignited
const float TEMPERATURE_LOSS_MP_OVEN = 0.75
const float TEMPERATURE_LOSS_MP_STONES = 0.90
const int TIMER_COOLING_UPDATE_INTERVAL = 2
update interval duration of heating process (seconds)
const int TIMER_HEATING_UPDATE_INTERVAL = 3
enum FireplaceFireState WET = 1
enum FireplaceFireState WIND = 0
Enumeration Type Documentation
FireplaceFireState
enum FireplaceFireState
Enumerator
NO_FIRE
START_FIRE
SMALL_FIRE
NORMAL_FIRE
END_FIRE
EXTINGUISHING_FIRE
EXTINGUISHED_FIRE
REIGNITED_FIRE
COUNT
Definition at line 1 of file fireplacebase.c.
{
    NO_FIRE             = 1,
    START_FIRE          = 2,
    SMALL_FIRE          = 3,
    NORMAL_FIRE         = 4,
    END_FIRE            = 5,
    EXTINGUISHING_FIRE  = 6,
    EXTINGUISHED_FIRE   = 7,
    REIGNITED_FIRE      = 8,
    COUNT               = 9         //for net sync purposes
}
Function Documentation
AddDamageToItemByFire()
protected void AddDamageToItemByFire (ItemBase item, bool can_be_ruined)
Definition at line 2357 of file fireplacebase.c.
    {
        item.DecreaseHealth( PARAM_BURN_DAMAGE_COEF, false );
        if ( item.CanBeCooked() & item.GetHealthLevel() >= GameConstants.STATE_BADLY_DAMAGED )
        {
            Edible_Base edible_item = Edible_Base.Cast( item );
            edible_item.ChangeFoodStage( FoodStageType.BURNED );
        }
    }
References ItemBase::CanBeCooked(), PARAM_BURN_DAMAGE_COEF, and GameConstants::STATE_BADLY_DAMAGED.
AddDamageToItemByFireEx()
protected void AddDamageToItemByFireEx (ItemBase item, bool can_be_ruined, bool pAttachment)
fireplace cargo only
cargo item attachments
fuel & kindling
cookable
Definition at line 2288 of file fireplacebase.c.
    {
        if (!item)
        {
            return;
        }
        if (GetTemperature() <= PARAM_ITEM_HEAT_MIN_TEMP)
        {
            return;
        }
        if (!pAttachment)
        {
            GameInventory itemInventory = item.GetInventory();
            if (itemInventory)
            {
                for (int i = 0; i < itemInventory.AttachmentCount(); ++i)
                {
                    itemInventory.GetAttachmentFromIndex(i).AddHealth("", "", -PARAM_BURN_DAMAGE_COEF);
                }
            }
            item.AddHealth("", "", -PARAM_BURN_DAMAGE_COEF);
        }
        else
        {
            float timerCoef = 1.0;
            if (m_HeatingTimer && m_HeatingTimer.IsRunning())
            {
                timerCoef = TIMER_HEATING_UPDATE_INTERVAL;
            }
            else if (m_CoolingTimer && m_CoolingTimer.IsRunning())
            {
                timerCoef = TIMER_COOLING_UPDATE_INTERVAL;
            }
            switch (item.Type())
            {
            case ATTACHMENT_TRIPOD:
            case ATTACHMENT_COOKINGSTAND:
            case ATTACHMENT_COOKING_POT:
            case ATTACHMENT_CAULDRON:
            case ATTACHMENT_FRYING_PAN:
                item.DecreaseHealth(GameConstants.FIRE_ATTACHMENT_DAMAGE_PER_SECOND * timerCoef, false);
            break;
            }
            if (IsFuel(item) || IsKindling(item))
            {
                if (item.GetHealthLevel() < GameConstants.STATE_BADLY_DAMAGED)
                {
                    item.DecreaseHealth(PARAM_BURN_DAMAGE_COEF, false);
                }
            }
            if (item.CanBeCooked() && item.GetHealthLevel() >= GameConstants.STATE_BADLY_DAMAGED)
            {
                Edible_Base edible_item = Edible_Base.Cast( item );
                edible_item.ChangeFoodStage(FoodStageType.BURNED);
            }
        }
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_COOKINGSTAND, ATTACHMENT_FRYING_PAN, ATTACHMENT_TRIPOD, ItemBase::CanBeCooked(), GameConstants::FIRE_ATTACHMENT_DAMAGE_PER_SECOND, GetTemperature(), IsFuel(), IsKindling(), m_CoolingTimer, m_HeatingTimer, PARAM_BURN_DAMAGE_COEF, PARAM_ITEM_HEAT_MIN_TEMP, GameConstants::STATE_BADLY_DAMAGED, TIMER_COOLING_UPDATE_INTERVAL, and TIMER_HEATING_UPDATE_INTERVAL.
Referenced by BurnItemsInFireplace().
AddTemperatureToFireplace()
protected void AddTemperatureToFireplace (float amount)
DEPRECATED.
Definition at line 2285 of file fireplacebase.c.
{};
AddTemperatureToItemByFire()
protected void AddTemperatureToItemByFire (ItemBase item)
Definition at line 2274 of file fireplacebase.c.
    {
        if (item.GetTemperatureMax() >= PARAM_ITEM_HEAT_MIN_TEMP)
        {
            float temperature = item.GetTemperature() + PARAM_ITEM_HEAT_TEMP_INCREASE_COEF;
            temperature = Math.Clamp(temperature, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_MAX_ITEM_HEAT_TEMP_INCREASE);
            item.SetTemperature(temperature);
        }
    }
References Math::Clamp(), PARAM_ITEM_HEAT_MIN_TEMP, PARAM_ITEM_HEAT_TEMP_INCREASE_COEF, and PARAM_MAX_ITEM_HEAT_TEMP_INCREASE.
Referenced by BurnItemsInFireplace().
AddToFireConsumables()
protected void AddToFireConsumables (ItemBase item)
Definition at line 1324 of file fireplacebase.c.
    {
        float energy = GetFireConsumableTypeEnergy ( item );
        m_FireConsumables.Insert( item, new FireConsumable ( item, energy ) );
        CalcAndSetQuantity();
    }
References CalcAndSetQuantity(), GetFireConsumableTypeEnergy(), and m_FireConsumables.
Referenced by FireplaceBase::EEItemAttached().
AddWetnessToFireplace()
void AddWetnessToFireplace (float amount)
Definition at line 2378 of file fireplacebase.c.
    {
        //add wetness
        float wetness = GetWet();
        wetness = wetness + amount;
        wetness = Math.Clamp(wetness, 0, 1); //wetness <0-1>
        SetWet(wetness);
        //decrease temperature
        if ( amount > 0 )
        {
            float temperature = GetTemperature();
            temperature = temperature * ( 1 - ( wetness * 0.5 ) );
            temperature = Math.Clamp( temperature, PARAM_MIN_FIRE_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE );
            // temperature via UniversalTemperatureSource
            m_UTSLFireplace.SetFuelCount(GetFuelCount());
            m_UTSLFireplace.SetCurrentTemperature(temperature);
        }
    }
References Math::Clamp(), GetFuelCount(), GetTemperature(), GetWet(), m_UTSLFireplace, PARAM_MIN_FIRE_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE, UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature(), UniversalTemperatureSourceLambdaFireplace::SetFuelCount(), and SetWet().
Referenced by Cooling(), and Heating().
AddWetnessToItem()
protected void AddWetnessToItem (ItemBase item, float amount)
Definition at line 2369 of file fireplacebase.c.
    {
        float wetness = item.GetWet();
        wetness = wetness + amount;
        wetness = Math.Clamp(wetness, 0, 1); //wetness <0-1>
        item.SetWet(wetness);
    }
References Math::Clamp().
Referenced by BurnItemsInFireplace().
AfterStoreLoad()
override void AfterStoreLoad ()
Definition at line 437 of file fireplacebase.c.
    {
        super.AfterStoreLoad();
        Synchronize();
        //start fire
        if (IsBurning() )
        {
            if (GetGame() && GetGame().IsServer())
            {
                StartFire(true);            //will be auto-synchronized when starting fire
            }
        }
    }
References GetGame(), IsBurning(), StartFire(), and Synchronize().
BurnItemsInFireplace()
protected void BurnItemsInFireplace ()
cargo
attachments
Definition at line 2234 of file fireplacebase.c.
    {
        CargoBase cargo = GetInventory().GetCargo();
        for (int i = 0; i < cargo.GetItemCount(); i++)
        {
            ItemBase item = ItemBase.Cast(cargo.GetItem(i));
            //set damage
            AddDamageToItemByFireEx(item, false, false);
            if (item.GetHealth("", "Health") <= 0 && !item.IsKindOf("Grenade_Base"))
            {
                item.Delete();
            }
            //add temperature
            AddTemperatureToItemByFire(item);
            //remove wetness
            AddWetnessToItem(item, -PARAM_WET_HEATING_DECREASE_COEF);
        }
        for (int j = 0; j < GetInventory().AttachmentCount(); ++j)
        {
            ItemBase attachment = ItemBase.Cast(GetInventory().GetAttachmentFromIndex(j));
            //set damage
            AddDamageToItemByFireEx(attachment, false, true);
            //add temperature
            AddTemperatureToItemByFire(attachment);
            //remove wetness
            AddWetnessToItem(attachment, -PARAM_WET_HEATING_DECREASE_COEF);
        }
    }
References AddDamageToItemByFireEx(), AddTemperatureToItemByFire(), AddWetnessToItem(), CargoBase::GetItem(), CargoBase::GetItemCount(), and PARAM_WET_HEATING_DECREASE_COEF.
Referenced by Cooling(), and Heating().
CalcAndSetQuantity()
protected void CalcAndSetQuantity ()
Definition at line 2725 of file fireplacebase.c.
    {
        if ( GetGame() && GetGame().IsServer() )
        {
            float remaining_energy;
            for ( int i = 0; i < m_FireConsumables.Count(); ++i )
            {
                ItemBase key = m_FireConsumables.GetKey( i );
                FireConsumable fire_consumable = m_FireConsumables.Get( key );
                float quantity = fire_consumable.GetItem().GetQuantity();
                if ( quantity > 0 )
                {
                    remaining_energy += ( ( quantity - 1 ) * fire_consumable.GetEnergy() ) + fire_consumable.GetRemainingEnergy();
                    //Print( fire_consumable.GetItem().GetType() + " remaining energy = " + ( ( ( quantity - 1 ) * fire_consumable.GetEnergy() ) + fire_consumable.GetRemainingEnergy() ).ToString() );
                }
                else
                {
                    remaining_energy += fire_consumable.GetRemainingEnergy();
                    //Print( fire_consumable.GetItem().GetType() + " remaining energy = " + ( fire_consumable.GetRemainingEnergy().ToString() ) );
                }
            }
            SetQuantity( remaining_energy / m_TotalEnergy * GetQuantityMax() );
        }
    }
References FireConsumable::GetEnergy(), GetGame(), FireConsumable::GetItem(), GetQuantityMax(), FireConsumable::GetRemainingEnergy(), m_FireConsumables, m_TotalEnergy, and SetQuantity().
Referenced by AddToFireConsumables(), CAContinuousEmpty::Cancel(), CAContinuousEmptyMagazine::Cancel(), CAContinuousFill::Cancel(), CAContinuousFillBrakes::Cancel(), CAContinuousFillCoolant::Cancel(), CAContinuousFillFuel::Cancel(), CAContinuousFillOil::Cancel(), CAContinuousQuantity::Cancel(), CAContinuousQuantityLiquidTransfer::Cancel(), CAContinuousQuantityRepeat::Cancel(), CAContinuousTransferQuantity::Cancel(), CAContinuousDisinfectPlant::Execute(), CAContinuousEmpty::Execute(), CAContinuousEmptyMagazine::Execute(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFill::Execute(), CAContinuousFillBrakes::Execute(), CAContinuousFillCoolant::Execute(), CAContinuousFillFuel::Execute(), CAContinuousFillOil::Execute(), CAContinuousFillPowerGenerator::Execute(), CAContinuousQuantity::Execute(), CAContinuousQuantityLiquidTransfer::Execute(), CAContinuousQuantityRepeat::Execute(), CAContinuousTransferQuantity::Execute(), CAContinuousWaterPlant::Execute(), CAContinuousWaterSlot::Execute(), CASingleUseQuantity::Execute(), OnAttachmentQuantityChanged(), RemoveFromFireConsumables(), and SpendFireConsumable().
CalcAndSetTotalEnergy()
protected void CalcAndSetTotalEnergy ()
Definition at line 2682 of file fireplacebase.c.
    {
        if ( GetGame() && GetGame().IsServer() )
        {
            m_TotalEnergy = 0;
            for ( int i = 0; i < m_FireConsumableTypes.Count(); ++i )
            {
                typename key = m_FireConsumableTypes.GetKey( i );
                FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( key );
                //string qt_config_path = "CfgVehicles" + " " + fire_consumable_type.GetItemType().ToString() + " " + "varQuantityMax";
                string qt_config_path = string.Format("CfgVehicles %1 varQuantityMax", fire_consumable_type.GetItemType().ToString());
                //string sm_config_path = "CfgSlots" + " " + "Slot_" + fire_consumable_type.GetAttSlot() + " " + "stackMax";
                string sm_config_path = string.Format("CfgSlots Slot_%1 stackMax", fire_consumable_type.GetAttSlot());
                if ( GetGame().ConfigIsExisting( qt_config_path ) )
                {
                    float quantity_max = GetGame().ConfigGetFloat( qt_config_path );
                }
                if ( GetGame().ConfigIsExisting( sm_config_path ) )
                {
                    float stack_max = GetGame().ConfigGetFloat( sm_config_path );
                }
                //debug
                //Print( fire_consumable_type.GetItemType().ToString() + " quantity_max = " + quantity_max.ToString() + " [" + (quantity_max*fire_consumable_type.GetEnergy()).ToString()  + "] | stack_max = " + stack_max.ToString() + " [" + (stack_max*fire_consumable_type.GetEnergy()).ToString() + "]" );
                if ( stack_max > 0 )
                {
                    m_TotalEnergy += stack_max * fire_consumable_type.GetEnergy();
                }
                else
                {
                    m_TotalEnergy += quantity_max * fire_consumable_type.GetEnergy();
                }
            }
            //debug
            //Print( "Total energy = " + m_TotalEnergy.ToString() );
        }
    }
References CGame::ConfigGetFloat(), ConfigIsExisting(), FireConsumableType::GetAttSlot(), FireConsumableType::GetEnergy(), GetGame(), FireConsumableType::GetItemType(), m_FireConsumableTypes, and m_TotalEnergy.
Referenced by FireplaceBase().
CanBuildOven()
bool CanBuildOven ()
Definition at line 2600 of file fireplacebase.c.
    {
        return !IsOven() && !IsBurning() && (GetAttachedStonesCount() >= MIN_STONES_TO_BUILD_OVEN) && !FindAttachmentBySlotName("CookingTripod") && !HasStoneCircle() && IsSpaceForOven();
    }
References GetAttachedStonesCount(), HasStoneCircle(), IsBurning(), IsOven(), IsSpaceForOven(), and MIN_STONES_TO_BUILD_OVEN.
CanBuildStoneCircle()
bool CanBuildStoneCircle ()
Definition at line 2612 of file fireplacebase.c.
    {
        return !HasStoneCircle() && !IsOven() && !IsBurning() && (GetAttachedStonesCount() >= MIN_STONES_TO_BUILD_CIRCLE) && IsSpaceForCircle();
    }
References GetAttachedStonesCount(), HasStoneCircle(), IsBurning(), IsOven(), IsSpaceForCircle(), and MIN_STONES_TO_BUILD_CIRCLE.
CanCookOnStick()
bool CanCookOnStick ()
Definition at line 2633 of file fireplacebase.c.
    {
        return ( GetTemperature() >= PARAM_COOKING_TEMP_THRESHOLD );
    }
References GetTemperature(), and PARAM_COOKING_TEMP_THRESHOLD.
CanDismantleOven()
bool CanDismantleOven ()
Definition at line 2623 of file fireplacebase.c.
    {
        return ( IsOven() && !IsBurning() && !DirectCookingSlotsInUse() && !SmokingSlotsInUse() && GetTemperature() <= MAX_TEMPERATURE_TO_DISMANTLE_OVEN );
    }
References DirectCookingSlotsInUse(), GetTemperature(), IsBurning(), IsOven(), MAX_TEMPERATURE_TO_DISMANTLE_OVEN, and SmokingSlotsInUse().
CanDismantleStoneCircle()
bool CanDismantleStoneCircle ()
Definition at line 2628 of file fireplacebase.c.
    {
        return ( HasStoneCircle() && !IsOven() && !IsBurning() );
    }
References HasStoneCircle(), IsBurning(), and IsOven().
CanExtinguishFire()
bool CanExtinguishFire ()
Definition at line 2639 of file fireplacebase.c.
    {
        return IsBurning();
    }
References IsBurning().
CanHaveTemperature()
override bool CanHaveTemperature ()
Definition at line 531 of file fireplacebase.c.
    {
        return true;
    }
CanHaveWetness()
override bool CanHaveWetness ()
Definition at line 526 of file fireplacebase.c.
    {
        return true;
    }
CanReleaseAttachment()
override bool CanReleaseAttachment (EntityAI attachment)
Definition at line 2761 of file fireplacebase.c.
    {
        if ( !super.CanReleaseAttachment( attachment ) )
            return false;
        ItemBase item = ItemBase.Cast( attachment );
        //kindling items
        if ( IsKindling ( item ) || IsFuel( item ) )
        {
            return !IsBurning();
        }
        return true;
    }
References IsBurning(), IsFuel(), and IsKindling().
CanShowSmoke()
bool CanShowSmoke ()
Definition at line 990 of file fireplacebase.c.
    {
        return true;
    }
CanSwapEntities()
override bool CanSwapEntities (EntityAI otherItem, InventoryLocation otherDestination, InventoryLocation destination)
Definition at line 2588 of file fireplacebase.c.
    {
        if (!otherDestination || otherDestination.GetParent() == this)
        {
            return false;
        }
        return true;
    }
References InventoryLocation::GetParent().
ClearCookingEquipment() [1/2]
void ClearCookingEquipment ()
DEPRECATED.
Definition at line 558 of file fireplacebase.c.
    {
        SetCookingEquipment(null);
    }
References FireplaceBase::SetCookingEquipment().
Referenced by FireplaceBase::EEItemDetached(), and ItemBase::EEItemDetached().
ClearCookingEquipment() [2/2]
void ClearCookingEquipment (ItemBase pItem)
Definition at line 547 of file fireplacebase.c.
    {
        if (m_CookingProcess)
        {
            m_CookingProcess.TerminateCookingSounds(pItem);
        }
        SetCookingEquipment(null);
    }
References m_CookingProcess, and FireplaceBase::SetCookingEquipment().
CookOnDirectSlot()
protected void CookOnDirectSlot (ItemBase slot_item, float temp_equip, float temp_ext)
Definition at line 2187 of file fireplacebase.c.
    {
        if (m_CookingProcess == null)
        {
            m_CookingProcess = new Cooking();
        }
        m_CookingProcess.CookWithEquipment(slot_item);
        switch (slot_item.Type())
        {
        case ATTACHMENT_CAULDRON:
        case ATTACHMENT_COOKING_POT:
        case ATTACHMENT_FRYING_PAN:
            float cookEquipTemp = temp_equip + PARAM_COOKING_EQUIP_TEMP_INCREASE;
            if ( temp_ext <= PARAM_SMALL_FIRE_TEMPERATURE )
            {
                cookEquipTemp = Math.Clamp(cookEquipTemp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE);
            }
            else
            {
                cookEquipTemp = Math.Clamp(cookEquipTemp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_COOKING_EQUIP_MAX_TEMP);
            }
            slot_item.SetTemperature(cookEquipTemp);
        break;
        }
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, Math::Clamp(), m_CookingProcess, PARAM_COOKING_EQUIP_MAX_TEMP, PARAM_COOKING_EQUIP_TEMP_INCREASE, PARAM_ITEM_HEAT_MIN_TEMP, and PARAM_SMALL_FIRE_TEMPERATURE.
Referenced by Cooling(), and Heating().
CookWithEquipment()
protected void CookWithEquipment ()
Definition at line 2167 of file fireplacebase.c.
    {
        if (m_CookingProcess == null)
        {
            m_CookingProcess = new Cooking();
        }
        m_CookingProcess.CookWithEquipment(m_CookingEquipment);
    }
References m_CookingEquipment, and m_CookingProcess.
Referenced by Cooling(), and Heating().
Cooling()
protected void Cooling ()
Definition at line 2018 of file fireplacebase.c.
    {
        //Debug
        /*
        PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        player.MessageAction ( "Cooling..." );
        Print("Cooling...");
        */
        float wetness = GetWet();
        float temperature = GetTemperature();
        float temperature_modifier = 0;
        if ( this && !IsBurning() && temperature >= 10 )
        {
            //check wetness
            //set wetness if raining and alter temperature modifier (which will lower temperature increase because of rain)
            float rain = GetGame().GetWeather().GetRain().GetActual();
            if ( IsRainingAbove() && !IsRoofAbove() )
            {
                //set wet to fireplace
                AddWetnessToFireplace(PARAM_WET_INCREASE_COEF * rain);
                //set temperature modifier
                temperature_modifier = temperature_modifier + ( PARAM_TEMPERATURE_DECREASE * rain );
            }
            else        //subtrackt wetness
            {
                AddWetnessToFireplace(-PARAM_WET_COOLING_DECREASE_COEF);
            }
            //calculate already obtained wetness (e.g. extinguished by water)
            temperature_modifier = temperature_modifier + ( PARAM_TEMPERATURE_DECREASE * wetness );
            // temperature via UniversalTemperatureSource
            m_UTSLFireplace.SetFuelCount(GetFuelCount());
            m_UTSLFireplace.SetCurrentTemperature(GetTemperature() - PARAM_TEMPERATURE_DECREASE - temperature_modifier );
            //damage cargo items
            BurnItemsInFireplace();
            //cook with equipment if temperature of equipment is still high
            if ( m_CookingEquipment )
            {
                float cook_equip_temp = m_CookingEquipment.GetTemperature();
                if ( cook_equip_temp >= PARAM_COOKING_TEMP_THRESHOLD )
                {
                    //cook
                    CookWithEquipment();
                }
            }
            float cook_item_temp;
            int i;
            // manage cooking on direct cooking slots
            if ( DirectCookingSlotsInUse() )
            {
                for ( i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++ )
                {
                    if ( m_DirectCookingSlots[i] )
                    {
                        cook_item_temp = m_DirectCookingSlots[i].GetTemperature();
                        if ( cook_item_temp >= PARAM_COOKING_TEMP_THRESHOLD )
{
                            CookOnDirectSlot( m_DirectCookingSlots[i], cook_item_temp, temperature );
                        }
                    }
                }
            }
            // manage smoking slots
            if ( SmokingSlotsInUse() )
            {
                for ( i = 0; i < SMOKING_SLOT_COUNT; i++ )
                {
                    if ( m_SmokingSlots[i] )
                    {
                        SmokeOnSmokingSlot( m_SmokingSlots[i], cook_item_temp, temperature );
                    }
                }
            }
            //Debug
            //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
            //if (player != NULL) {player.MessageAction ( temperature.ToString() );}
        }
        else
        {
            //stop cooling
            if (Math.AbsFloat(temperature) < 10)
            {
                StopCooling();
                m_UTSource.SetActive(false);
            }
        }
    }
References Math::AbsFloat(), AddWetnessToFireplace(), BurnItemsInFireplace(), CookOnDirectSlot(), CookWithEquipment(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), WeatherPhenomenon::GetActual(), GetFuelCount(), GetGame(), Weather::GetRain(), GetTemperature(), CGame::GetWeather(), GetWet(), IsBurning(), IsRainingAbove(), IsRoofAbove(), m_CookingEquipment, m_DirectCookingSlots, m_SmokingSlots, m_UTSLFireplace, m_UTSource, PARAM_COOKING_TEMP_THRESHOLD, PARAM_TEMPERATURE_DECREASE, PARAM_WET_COOLING_DECREASE_COEF, PARAM_WET_INCREASE_COEF, UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature(), UniversalTemperatureSourceLambdaFireplace::SetFuelCount(), SmokeOnSmokingSlot(), SMOKING_SLOT_COUNT, SmokingSlotsInUse(), and StopCooling().
CreateAreaDamage()
void CreateAreaDamage ()
Definition at line 2402 of file fireplacebase.c.
    {
        //destroy area damage if some already exists
        DestroyAreaDamage();
        //create new area damage
        m_AreaDamage = new AreaDamageLoopedDeferred( this );
        m_AreaDamage.SetDamageComponentType(AreaDamageComponentTypes.HITZONE);
        m_AreaDamage.SetExtents("-0.30 0 -0.30", "0.30 0.75 0.30");
        m_AreaDamage.SetLoopInterval( 0.5 );
        m_AreaDamage.SetDeferDuration( 0.5 );
        m_AreaDamage.SetHitZones( { "Head","Torso","LeftHand","LeftLeg","LeftFoot","RightHand","RightLeg","RightFoot" } );
        m_AreaDamage.SetAmmoName( "FireDamage" );
        m_AreaDamage.Spawn();
    }
References DestroyAreaDamage(), AreaDamageComponentTypes::HITZONE, and m_AreaDamage.
Referenced by OnVariablesSynchronized(), StartHeating(), and ItemBase::UpdateAttachmentVisuals().
DestroyAreaDamage()
void DestroyAreaDamage ()
Definition at line 2418 of file fireplacebase.c.
    {
        if ( m_AreaDamage )
        {
            m_AreaDamage.Destroy();
        }
    }
References m_AreaDamage.
Referenced by CreateAreaDamage(), ItemBase::CreateAreaDamage(), OnVariablesSynchronized(), StopCooling(), ItemBase::UpdateAttachmentVisuals(), and BaseBuildingBase::UpdateBarbedWireAreaDamagePos().
DestroyFireplace()
void DestroyFireplace ()
Definition at line 588 of file fireplacebase.c.
    {
        //delete object
        DeleteSafe();
    }
DirectCookingSlotsInUse()
bool DirectCookingSlotsInUse ()
Definition at line 563 of file fireplacebase.c.
    {
        for (int i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++)
        {
            if ( m_DirectCookingSlots[i] )
            {
                return true;
            }
        }
        return false;
    }
References DIRECT_COOKING_SLOT_COUNT, and m_DirectCookingSlots.
Referenced by CanDismantleOven(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), Cooling(), Heating(), and StopCooling().
DisassembleOnLastDetach()
override bool DisassembleOnLastDetach ()
Definition at line 2810 of file fireplacebase.c.
    {
        return true;
    }
EECargoOut()
override void EECargoOut (EntityAI item)
Definition at line 599 of file fireplacebase.c.
    {
        super.EECargoOut(item);
        CheckForDestroy();
    }
EEDelete()
override void EEDelete (EntityAI parent)
Definition at line 369 of file fireplacebase.c.
    {
        super.EEDelete(parent);
        SetFireState(FireplaceFireState.NO_FIRE);
        // cleanup particles (for cases of leaving burning fplace and going back outside of network bubble)
        #ifndef SERVER
        StopAllParticlesAndSounds();
        #endif
    }
References SetFireState(), and StopAllParticlesAndSounds().
EEInit()
override void EEInit ()
Definition at line 283 of file fireplacebase.c.
    {
        super.EEInit();
        //refresh visual on init
        RefreshFireplaceVisuals();
        if (GetGame().IsServer() || !GetGame().IsMultiplayer())
        {
            m_UTSSettings                   = new UniversalTemperatureSourceSettings();
            m_UTSSettings.m_UpdateInterval  = 3;
            m_UTSSettings.m_Updateable      = true;
            m_UTSSettings.m_AffectStat      = true;
            m_UTSSettings.m_TemperatureMin  = 0;
            m_UTSSettings.m_TemperatureMax  = PARAM_NORMAL_FIRE_TEMPERATURE;
            m_UTSSettings.m_TemperatureCap  = PARAM_MAX_TRANSFERED_TEMPERATURE;
            m_UTSSettings.m_RangeFull       = PARAM_FULL_HEAT_RADIUS;
            m_UTSSettings.m_RangeMax        = PARAM_HEAT_RADIUS;
            m_UTSLFireplace= new UniversalTemperatureSourceLambdaFireplace();
            m_UTSLFireplace.SetSmallFireplaceTemperatureMax(PARAM_SMALL_FIRE_TEMPERATURE);
            m_UTSLFireplace.SetNormalFireplaceTemperatureMax(PARAM_NORMAL_FIRE_TEMPERATURE);
            m_UTSource = new UniversalTemperatureSource(this, m_UTSSettings, m_UTSLFireplace);
        }
    }
References GetGame(), UniversalTemperatureSourceSettings::m_AffectStat, UniversalTemperatureSourceSettings::m_RangeFull, UniversalTemperatureSourceSettings::m_RangeMax, UniversalTemperatureSourceSettings::m_TemperatureCap, UniversalTemperatureSourceSettings::m_TemperatureMax, UniversalTemperatureSourceSettings::m_TemperatureMin, UniversalTemperatureSourceSettings::m_Updateable, UniversalTemperatureSourceSettings::m_UpdateInterval, m_UTSLFireplace, m_UTSource, m_UTSSettings, PARAM_FULL_HEAT_RADIUS, PARAM_HEAT_RADIUS, PARAM_MAX_TRANSFERED_TEMPERATURE, PARAM_NORMAL_FIRE_TEMPERATURE, PARAM_SMALL_FIRE_TEMPERATURE, RefreshFireplaceVisuals(), UniversalTemperatureSourceLambdaFireplace::SetNormalFireplaceTemperatureMax(), and UniversalTemperatureSourceLambdaFireplace::SetSmallFireplaceTemperatureMax().
EEItemAttached()
override void EEItemAttached (EntityAI item, string slot_name)
Definition at line 310 of file fireplacebase.c.
    {
        super.EEItemAttached(item, slot_name);
        //cookware
        switch (item.Type())
        {
        case ATTACHMENT_CAULDRON:
        case ATTACHMENT_COOKING_POT:
        case ATTACHMENT_FRYING_PAN:
            SetCookingEquipment(ItemBase.Cast(item));
        break;
        }
    }
References ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_FRYING_PAN, and FireplaceBase::SetCookingEquipment().
FireplaceBase()
protected void FireplaceBase ()
Definition at line 231 of file fireplacebase.c.
    {
        //STATIC: define kindling types
        if (!m_FireConsumableTypes)
        {
            m_FireConsumableTypes = new ref map<typename, ref FireConsumableType>();
            m_FireConsumableTypes.Insert(ATTACHMENT_RAGS,           new FireConsumableType(ATTACHMENT_RAGS,         14,     true,   "Rags"));
            m_FireConsumableTypes.Insert(ATTACHMENT_BANDAGE,        new FireConsumableType(ATTACHMENT_BANDAGE,      14,     true,   "MedicalBandage"));
            m_FireConsumableTypes.Insert(ATTACHMENT_BOOK,           new FireConsumableType(ATTACHMENT_BOOK,         36,     true,   "Book"));
            m_FireConsumableTypes.Insert(ATTACHMENT_BARK_OAK,       new FireConsumableType(ATTACHMENT_BARK_OAK,     20,     true,   "OakBark"));
            m_FireConsumableTypes.Insert(ATTACHMENT_BARK_BIRCH,     new FireConsumableType(ATTACHMENT_BARK_BIRCH,   14,     true,   "BirchBark"));
            m_FireConsumableTypes.Insert(ATTACHMENT_PAPER,          new FireConsumableType(ATTACHMENT_PAPER,        10,     true,   "Paper"));
            m_FireConsumableTypes.Insert(ATTACHMENT_GIFTWRAP,       new FireConsumableType(ATTACHMENT_GIFTWRAP,     10,     true,   "GiftWrapPaper"));
            m_FireConsumableTypes.Insert(ATTACHMENT_PUNCHEDCARD,    new FireConsumableType(ATTACHMENT_PUNCHEDCARD,  10,     true,   "PunchedCard"));
            //define fuel types
            m_FireConsumableTypes.Insert( ATTACHMENT_STICKS,        new FireConsumableType( ATTACHMENT_STICKS,      40,     false,  "WoodenStick"));
            m_FireConsumableTypes.Insert( ATTACHMENT_FIREWOOD,      new FireConsumableType( ATTACHMENT_FIREWOOD,    100,    false,  "Firewood"));
        }
        //calculate total energy
        CalcAndSetTotalEnergy();
        //define fuel / kindling items (fire consumables)
        m_FireConsumables = new ref map<ItemBase, ref FireConsumable>;
        //default burning parameters
        SetTemperatureLossMP( TEMPERATURE_LOSS_MP_DEFAULT );
        SetFuelBurnRateMP( FUEL_BURN_RATE_DEFAULT );
        //synchronized variables
        RegisterNetSyncVariableBool( "m_IsBurning" );
        RegisterNetSyncVariableBool( "m_HasAshes" );
        RegisterNetSyncVariableBool( "m_IsOven" );
        RegisterNetSyncVariableBool( "m_HasStoneCircle" );
        RegisterNetSyncVariableBool( "m_RoofAbove" );
        RegisterNetSyncVariableInt( "m_FireState", FireplaceFireState.NO_FIRE, FireplaceFireState.COUNT );
        RegisterNetSyncVariableBool( "m_IsSoundSynchRemote" );
        RegisterNetSyncVariableBool( "m_IsPlaceSound" );
        RegisterNetSyncVariableBool( "m_NoIgnite" );
        m_HalfExtents = vector.Zero;
    }
References ATTACHMENT_BANDAGE, ATTACHMENT_BARK_BIRCH, ATTACHMENT_BARK_OAK, ATTACHMENT_BOOK, ATTACHMENT_FIREWOOD, ATTACHMENT_GIFTWRAP, ATTACHMENT_PAPER, ATTACHMENT_PUNCHEDCARD, ATTACHMENT_RAGS, ATTACHMENT_STICKS, CalcAndSetTotalEnergy(), FUEL_BURN_RATE_DEFAULT, m_FireConsumables, m_FireConsumableTypes, m_HalfExtents, SetFuelBurnRateMP(), SetTemperatureLossMP(), TEMPERATURE_LOSS_MP_DEFAULT, and vector::Zero.
GetAirResistanceForSmokeParticles()
float GetAirResistanceForSmokeParticles (float actual_height)
Definition at line 1251 of file fireplacebase.c.
    {
        float air_res;
        actual_height = Math.Clamp( actual_height, 0, 36 );
        air_res = ( 6 - actual_height ) * 0.33;
        air_res = Math.Clamp( air_res, 0, 2 );
        return air_res;
    }
References Math::Clamp().
Referenced by ParticleNormalSmokeStart(), and ParticleSmallSmokeStart().
GetAttachedStonesCount()
int GetAttachedStonesCount ()
Definition at line 1639 of file fireplacebase.c.
    {
        if (HasStones())
        {
            return GetAttachmentByType(ATTACHMENT_STONES).GetQuantity();
        }
        return 0;
    }
References ATTACHMENT_STONES, and HasStones().
Referenced by CanBuildOven(), and CanBuildStoneCircle().
GetCeilingHeight()
bool GetCeilingHeight (out float actual_height)
Definition at line 1235 of file fireplacebase.c.
    {
        vector from = this.GetPosition();
        vector to = this.GetPosition();
        from[1] = from[1] + 1.0;
        to[1] = to[1] + MIN_CEILING_HEIGHT;
        vector contactPos;
        vector contactDir;
        int contactComponent;
        bool hit = DayZPhysics.RaycastRV( from, to, contactPos, contactDir, contactComponent, NULL, NULL, this );
        actual_height = vector.Distance( from, contactPos ) + 1.0;
        return hit;
    }
References vector::Distance(), GetPosition, MIN_CEILING_HEIGHT, and DayZPhysics::RaycastRV().
Referenced by ParticleNormalSmokeStart(), and ParticleSmallSmokeStart().
GetCookingEquipment()
ItemBase GetCookingEquipment ()
Definition at line 537 of file fireplacebase.c.
    {
        return m_CookingEquipment;
    }
References m_CookingEquipment.
Referenced by StopCooling().
GetCookingProcess()
Cooking GetCookingProcess ()
Definition at line 2177 of file fireplacebase.c.
    {
        if (m_CookingProcess == null)
        {
            m_CookingProcess = new Cooking();
        }
        return m_CookingProcess;
    }
References m_CookingProcess.
GetDebugButtonNames()
override void GetDebugButtonNames (out string button1, out string button2, out string button3, out string button4)
Definition at line 2874 of file fireplacebase.c.
    {
        button1 = "Ignite";
        button2 = "Extinguish";
    }
Referenced by InventoryItem::GetDebugActions().
GetFireConsumableByItem()
protected FireConsumable GetFireConsumableByItem (ItemBase item)
Definition at line 1356 of file fireplacebase.c.
    {
        return m_FireConsumables.Get( item );
    }
References m_FireConsumables.
Referenced by FireplaceBase::EEItemDetached().
GetFireConsumableTypeEnergy()
protected float GetFireConsumableTypeEnergy (ItemBase item)
Definition at line 1332 of file fireplacebase.c.
    {
        //Kindling
        ref FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( item.Type() );
        if ( fire_consumable_type )
        {
            return fire_consumable_type.GetEnergy();
        }
        return 0;
    }
References m_FireConsumableTypes.
Referenced by AddToFireConsumables().
GetFireEffectPosition()
protected vector GetFireEffectPosition ()
Definition at line 1264 of file fireplacebase.c.
    {
        return Vector( 0, 0.05, 0 );
    }
References Vector().
Referenced by ParticleFireEndStart(), ParticleFireStartStart(), ParticleFireWindyNoIgniteStart(), ParticleNormalFireStart(), ParticleSmallFireStart(), ParticleSteamEndStart(), ParticleSteamExtinguishingStart(), and ParticleWetNoIgniteStart().
GetFireState()
protected int GetFireState ()
Definition at line 1696 of file fireplacebase.c.
    {
        return m_FireState;
    }
References m_FireState.
Referenced by Heating(), RefreshFireParticlesAndSounds(), and RefreshFireState().
GetFuelBurnRateMP()
protected float GetFuelBurnRateMP ()
Definition at line 1685 of file fireplacebase.c.
    {
        return m_FuelBurnRateMP;
    }
References m_FuelBurnRateMP.
Referenced by Heating().
GetFuelCount()
protected int GetFuelCount ()
Definition at line 1512 of file fireplacebase.c.
    {
        int attachments_count = GetInventory().AttachmentCount();
        int fire_consumables_count = m_FireConsumables.Count();
        int fuel_count = 0;
        for ( int i = 0; i < attachments_count; i++ )
        {
            ItemBase item = ItemBase.Cast( GetInventory().GetAttachmentFromIndex( i ) );
            for ( int j = 0; j < fire_consumables_count; j++ )
            {
                ref FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( item.Type() );
                if ( fire_consumable_type && !fire_consumable_type.IsKindling() )
                {
                    fuel_count++;
                    break;
                }
            }
        }
        return fuel_count;
    }
References GetAttachmentFromIndex(), m_FireConsumables, and m_FireConsumableTypes.
Referenced by AddWetnessToFireplace(), Cooling(), HasLastFuelKindlingAttached(), and Heating().
GetIgniteFailure()
bool GetIgniteFailure ()
Definition at line 2454 of file fireplacebase.c.
    {
        return m_NoIgnite;
    }
References m_NoIgnite.
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
GetItemToConsume()
protected FireConsumable GetItemToConsume ()
Definition at line 1400 of file fireplacebase.c.
    {
        return m_ItemToConsume;
    }
References m_ItemToConsume.
Referenced by SpendFireConsumable().
GetKindlingCount()
protected int GetKindlingCount ()
Definition at line 1485 of file fireplacebase.c.
    {
        int attachments_count = GetInventory().AttachmentCount();
        int fire_consumables_count = m_FireConsumables.Count();
        int kindling_count = 0;
        for ( int i = 0; i < attachments_count; i++ )
        {
            ItemBase item = ItemBase.Cast( GetInventory().GetAttachmentFromIndex( i ) );
            for ( int j = 0; j < fire_consumables_count; j++ )
            {
                ref FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( item.Type() );
                if ( fire_consumable_type && fire_consumable_type.IsKindling() )
                {
                    kindling_count++;
                    break;
                }
            }
        }
        return kindling_count;
    }
References GetAttachmentFromIndex(), m_FireConsumables, and m_FireConsumableTypes.
Referenced by HasAnyKindling(), HasLastFuelKindlingAttached(), and RefreshFireplaceVisuals().
GetLightEntity()
FireplaceLight GetLightEntity ()
Definition at line 2644 of file fireplacebase.c.
    {
        return m_Light;
    }
References m_Light.
Referenced by RefreshFireplaceVisuals(), and ~FireplaceBase().
GetPlaceSoundset()
override string GetPlaceSoundset ()
Definition at line 2673 of file fireplacebase.c.
    {
        return "placeFireplace_SoundSet";
    }
GetSmokeEffectPosition()
protected vector GetSmokeEffectPosition ()
Definition at line 1269 of file fireplacebase.c.
    {
        return Vector( 0, 0.05, 0 );
    }
References Vector().
GetTemperatureLossMP()
protected float GetTemperatureLossMP ()
Definition at line 1674 of file fireplacebase.c.
    {
        return m_TemperatureLossMP;
    }
References m_TemperatureLossMP.
HasAnyKindling()
bool HasAnyKindling ()
Definition at line 2439 of file fireplacebase.c.
    {
        return GetKindlingCount() > 0;
    }
References GetKindlingCount().
Referenced by FireplaceBase::CanBeIgnitedBy(), and FireplaceBase::IsThisIgnitionSuccessful().
HasAshes()
bool HasAshes ()
Definition at line 1606 of file fireplacebase.c.
    {
        return m_HasAshes;
    }
References m_HasAshes.
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), IsPrepareToDelete(), FireplaceBase::IsPrepareToDelete(), RefreshFireplaceVisuals(), and SpendFireConsumable().
HasCookingStand()
bool HasCookingStand ()
Definition at line 2562 of file fireplacebase.c.
    {
        return GetInventory().FindAttachment(InventorySlots.GetSlotIdFromString("CookingTripod")) != null;
    }
References InventorySlots::GetSlotIdFromString().
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), and Heating().
HasLastAttachment()
bool HasLastAttachment ()
Definition at line 1576 of file fireplacebase.c.
    {
        return ( GetInventory().AttachmentCount() == 1 );
    }
References AttachmentCount().
HasLastFuelKindlingAttached()
bool HasLastFuelKindlingAttached ()
Definition at line 1582 of file fireplacebase.c.
    {
        int fuel_kindling_count = GetFuelCount() + GetKindlingCount();
        return ( fuel_kindling_count == 1 );
    }
References GetFuelCount(), and GetKindlingCount().
HasStoneCircle()
bool HasStoneCircle ()
Definition at line 1627 of file fireplacebase.c.
    {
        return m_HasStoneCircle;
    }
References m_HasStoneCircle.
Referenced by CanBuildOven(), CanBuildStoneCircle(), CanDismantleStoneCircle(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReleaseAttachment(), and RefreshFireplaceVisuals().
HasStones()
bool HasStones ()
Definition at line 1632 of file fireplacebase.c.
    {
        EntityAI attached_item = GetAttachmentByType(ATTACHMENT_STONES);
        return attached_item && attached_item.GetQuantity() > 0;
    }
References ATTACHMENT_STONES.
Referenced by FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), GetAttachedStonesCount(), and RefreshFireplaceVisuals().
Heating()
protected void Heating ()
DEBUG
Definition at line 1800 of file fireplacebase.c.
    {
        /*
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.MessageAction ( "Heating..." );
        */
        float temperature = GetTemperature();
        float temperature_modifier = 0;
        //check burning conditions
        if ( GetWet() > PARAM_BURN_WET_THRESHOLD )      //wetness condition
        {
            StopFire( FireplaceFireState.EXTINGUISHED_FIRE );
            return;
        }
        else
        {
            if ( m_FireConsumables.Count() == 0 )       //fire consumable condition
            {
                StopFire();
                return;
            }
        }
        //DEBUG
        /*
        string s_message = "-> fire amount = " + PARAM_FIRE_CONSUM_RATE_AMOUNT.ToString() + " burn rate = " + GetFuelBurnRateMP().ToString() + " temp loss = " + GetTemperatureLossMP().ToString();
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        player.MessageAction (s_message);
        Print ( s_message );
        */
        //spend actual fire consumable
        float amount = ( PARAM_FIRE_CONSUM_RATE_AMOUNT * GetFuelBurnRateMP() ) * TIMER_HEATING_UPDATE_INTERVAL;
        SpendFireConsumable( amount );
        //set wetness if raining and alter temperature modifier (which will lower temperature increase because of rain)
        float rain = GetGame().GetWeather().GetRain().GetActual();
        if ( rain >= PARAM_BURN_WET_THRESHOLD && ( IsRainingAbove() && !MiscGameplayFunctions.IsUnderRoof( this ) ) )
        {
            //set wet to fireplace
            AddWetnessToFireplace(PARAM_WET_INCREASE_COEF * rain);
            //set temperature modifier
            temperature_modifier = PARAM_TEMPERATURE_INCREASE * rain;
        }
        //subtract wetness when heating and not raining above
        else
        {
            AddWetnessToFireplace(-PARAM_WET_HEATING_DECREASE_COEF);
        }
        // temperature via UniversalTemperatureSource
        m_UTSLFireplace.SetFuelCount(GetFuelCount());
        m_UTSLFireplace.SetCurrentTemperature(GetTemperature() + PARAM_TEMPERATURE_INCREASE - temperature_modifier);
        //check fire state
        if ( GetFireState() != FireplaceFireState.EXTINGUISHING_FIRE )
        {
            RefreshFireState();
        }
        //damage cargo items
        BurnItemsInFireplace();
        //manage cooking equipment (this applies only for case of cooking pot on a tripod)
        if (HasCookingStand() && m_CookingEquipment)
        {
            float cook_equip_temp = m_CookingEquipment.GetTemperature();
            if ( cook_equip_temp >= PARAM_COOKING_TEMP_THRESHOLD )
            {
                //start cooking
                CookWithEquipment();
            }
            //DEBUG
            /*
            PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
            string s_message = "cooking equipment temp = " + ftoa(cook_equip_temp) + " | PARAM_COOKING_TEMP_THRESHOLD = " + ftoa(PARAM_COOKING_TEMP_THRESHOLD);
            if (player != NULL) {player.MessageAction (s_message);}
            Print ( s_message );
            */
            //set temperature to cooking equipment
            cook_equip_temp = cook_equip_temp + PARAM_COOKING_EQUIP_TEMP_INCREASE;
            if ( temperature <= PARAM_SMALL_FIRE_TEMPERATURE )
            {
                cook_equip_temp = Math.Clamp ( cook_equip_temp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE );
            }
            else
            {
                cook_equip_temp = Math.Clamp ( cook_equip_temp, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_COOKING_EQUIP_MAX_TEMP );
            }
            m_CookingEquipment.SetTemperature( cook_equip_temp );
        }
        float cook_item_temp;
        int i;
        // manage cooking on direct cooking slots
        if ( DirectCookingSlotsInUse() )
        {
            for ( i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++ )
            {
                if ( m_DirectCookingSlots[i] )
                {
                    cook_item_temp = m_DirectCookingSlots[i].GetTemperature();
                    if ( cook_item_temp >= PARAM_COOKING_TEMP_THRESHOLD )
                    {
                        CookOnDirectSlot( m_DirectCookingSlots[i], cook_item_temp, temperature );
                    }
                }
            }
        }
        // manage smoking slots
        if ( SmokingSlotsInUse() )
        {
            for ( i = 0; i < SMOKING_SLOT_COUNT; i++ )
            {
                if ( m_SmokingSlots[i] )
                {
                    SmokeOnSmokingSlot( m_SmokingSlots[i], cook_item_temp, temperature );
                }
            }
        }
        //Make noise for AI, only at night
        if ( GetGame().GetWorld().IsNight() && m_CanNoise )
        {
            NoiseSystem noise = GetGame().GetNoiseSystem();
            if ( noise && m_NoisePar )
            {
                noise.AddNoisePos( this, GetPosition(), m_NoisePar);
            }
            m_CanNoise = false;
        }
        else
            m_CanNoise = true;
        Synchronize();
    }
References NoiseSystem::AddNoisePos(), AddWetnessToFireplace(), BurnItemsInFireplace(), Math::Clamp(), CookOnDirectSlot(), CookWithEquipment(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), WeatherPhenomenon::GetActual(), GetFireState(), GetFuelBurnRateMP(), GetFuelCount(), GetGame(), CGame::GetNoiseSystem(), GetPosition, Weather::GetRain(), GetTemperature(), CGame::GetWeather(), GetWet(), HasCookingStand(), IsRainingAbove(), m_CanNoise, m_CookingEquipment, m_DirectCookingSlots, m_FireConsumables, m_NoisePar, m_SmokingSlots, m_UTSLFireplace, PARAM_BURN_WET_THRESHOLD, PARAM_COOKING_EQUIP_MAX_TEMP, PARAM_COOKING_EQUIP_TEMP_INCREASE, PARAM_COOKING_TEMP_THRESHOLD, PARAM_FIRE_CONSUM_RATE_AMOUNT, PARAM_ITEM_HEAT_MIN_TEMP, PARAM_SMALL_FIRE_TEMPERATURE, PARAM_TEMPERATURE_INCREASE, PARAM_WET_HEATING_DECREASE_COEF, PARAM_WET_INCREASE_COEF, RefreshFireState(), UniversalTemperatureSourceLambdaFireplace::SetCurrentTemperature(), UniversalTemperatureSourceLambdaFireplace::SetFuelCount(), SmokeOnSmokingSlot(), SMOKING_SLOT_COUNT, SmokingSlotsInUse(), SpendFireConsumable(), StopFire(), Synchronize(), and TIMER_HEATING_UPDATE_INTERVAL.
IsBarrelWithHoles()
bool IsBarrelWithHoles ()
Definition at line 511 of file fireplacebase.c.
    {
        return false;
    }
IsBaseFireplace()
bool IsBaseFireplace ()
Definition at line 506 of file fireplacebase.c.
    {
        return false;
    }
IsBurning()
bool IsBurning ()
Definition at line 1594 of file fireplacebase.c.
    {
        return m_IsBurning;
    }
References m_IsBurning.
Referenced by AfterStoreLoad(), FireplaceBase::AfterStoreLoad(), FireplaceBase::CanBeIgnitedBy(), CanBuildOven(), CanBuildStoneCircle(), CanDismantleOven(), CanDismantleStoneCircle(), CanExtinguishFire(), FireplaceBase::CanExtinguishFire(), FireplaceBase::CanIgniteItem(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), Cooling(), FireplaceBase::IsIgnited(), IsPrepareToDelete(), FireplaceBase::IsPrepareToDelete(), RefreshFireplaceVisuals(), RefreshFireState(), and StartFire().
IsCargoEmpty()
bool IsCargoEmpty ()
Definition at line 2550 of file fireplacebase.c.
    {
        return ( GetInventory().GetCargo().GetItemCount() == 0 );
    }
References GetCargo().
Referenced by FireplaceBase::CanPutInCargo(), and FireplaceBase::CanPutIntoHands().
IsCeilingHighEnoughForSmoke()
bool IsCeilingHighEnoughForSmoke ()
Definition at line 2488 of file fireplacebase.c.
    {
        return !MiscGameplayFunctions.IsUnderRoof( this, FireplaceBase.MIN_CEILING_HEIGHT );
    }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsEmpty()
override bool IsEmpty ()
Definition at line 2544 of file fireplacebase.c.
    {
        return ( GetInventory().GetCargo().GetItemCount() == 0 && GetInventory().AttachmentCount() == 0 );
    }
References AttachmentCount(), and GetCargo().
Referenced by RecipeBase::CanDo(), CivilianBelt::CanPutInCargo(), Clothing::CanPutInCargo(), MilitaryBelt::CanPutInCargo(), RopeBelt::CanPutInCargo(), and IsPrepareToDelete().
IsEntityOnInteriorSurface()
static bool IsEntityOnInteriorSurface (notnull EntityAI entity_ai) static
Definition at line 2531 of file fireplacebase.c.
    {
        string surface_type;
        vector fireplace_pos = entity_ai.GetPosition();
        GetGame().SurfaceGetType3D( fireplace_pos[0], fireplace_pos[1] + 1.0, fireplace_pos[2], surface_type );
        return ( ( GetGame().ConfigGetInt( "CfgSurfaces " + surface_type + " interior" ) ) == 1 );
    }
References ConfigGetInt(), GetGame(), and CGame::SurfaceGetType3D().
Referenced by FireplaceBase::CanIgniteEntityAsFireplace().
IsEntityOnWaterSurface()
static bool IsEntityOnWaterSurface (notnull EntityAI entity_ai) static
Definition at line 2505 of file fireplacebase.c.
    {
        vector fireplace_pos = entity_ai.GetPosition();
        if ( GetGame().SurfaceIsSea( fireplace_pos[0], fireplace_pos[2] ) )
        {
            return true;
        }
        else if ( GetGame().SurfaceIsPond( fireplace_pos[0], fireplace_pos[2] ) )
        {
            return true;
        }
        else
        {
            string surface_type;
            GetGame().SurfaceGetType3D( fireplace_pos[0], fireplace_pos[1] + 1.0, fireplace_pos[2], surface_type );
            return surface_type.Contains("water");
        }
        return false;
    }
References string::Contains(), GetGame(), and CGame::SurfaceGetType3D().
IsEntityWet()
static bool IsEntityWet (notnull EntityAI entity_ai) static
Definition at line 2465 of file fireplacebase.c.
    {
        return ( entity_ai.GetWet() >= FireplaceBase.PARAM_MAX_WET_TO_IGNITE );
    }
IsFacingFireplace()
bool IsFacingFireplace (PlayerBase player)
DEPRECATED.
Definition at line 2427 of file fireplacebase.c.
    {
        ErrorEx("Deprecated method", ErrorExSeverity.INFO);
        return false;
    }
References ErrorEx.
IsFireplace()
override bool IsFireplace ()
Definition at line 501 of file fireplacebase.c.
    {
        return true;
    }
IsFireplaceIndoor()
bool IsFireplaceIndoor ()
Definition at line 516 of file fireplacebase.c.
    {
        return false;
    }
IsFuel()
protected bool IsFuel (ItemBase item)
Definition at line 1550 of file fireplacebase.c.
    {
        ref FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( item.Type() );
        if ( fire_consumable_type )
        {
            return !fire_consumable_type.IsKindling();
        }
        return false;
    }
References m_FireConsumableTypes.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
IsInAnimPhase()
bool IsInAnimPhase (string anim_phase)
Definition at line 2568 of file fireplacebase.c.
    {
        return GetAnimationPhase(anim_phase) == 0;
    }
Referenced by SetBurntFirewood().
IsIndoorOven()
bool IsIndoorOven ()
Definition at line 521 of file fireplacebase.c.
    {
        return false;
    }
IsItemAttachedQuantity()
bool IsItemAttachedQuantity (typename item_type , float quantity)
Definition at line 1568 of file fireplacebase.c.
    {
        ItemBase item = ItemBase.Cast( GetAttachmentByType( item_type ) );
        return ( item.GetQuantity() >= quantity );
    }
IsItemTypeAttached()
bool IsItemTypeAttached (typename item_type)
Definition at line 1562 of file fireplacebase.c.
    {
        return GetAttachmentByType( item_type ) != null;
    }
Referenced by RefreshFireplaceVisuals(), and FireplaceBase::RefreshPhysics().
IsKindling()
protected bool IsKindling (ItemBase item)
Definition at line 1538 of file fireplacebase.c.
    {
        ref FireConsumableType fire_consumable_type = m_FireConsumableTypes.Get( item.Type() );
        if ( fire_consumable_type )
        {
            return fire_consumable_type.IsKindling();
        }
        return false;
    }
References m_FireConsumableTypes.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanReceiveAttachment(), CanReleaseAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
IsOnInteriorSurface()
bool IsOnInteriorSurface ()
Definition at line 2538 of file fireplacebase.c.
    {
        return FireplaceBase.IsEntityOnInteriorSurface( this );
    }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsOnWaterSurface()
bool IsOnWaterSurface ()
Definition at line 2525 of file fireplacebase.c.
    {
        return FireplaceBase.IsEntityOnWaterSurface( this );
    }
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
IsOpen()
override bool IsOpen ()
Definition at line 2482 of file fireplacebase.c.
    {
        return true;
    }
IsOven()
bool IsOven ()
Definition at line 1623 of file fireplacebase.c.
    {
        return m_IsOven;
    }
References m_IsOven.
Referenced by CanBuildOven(), CanBuildStoneCircle(), CanDismantleOven(), CanDismantleStoneCircle(), FireplaceBase::CanDisplayAttachmentCategory(), FireplaceBase::CanPutInCargo(), FireplaceBase::CanPutIntoHands(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReleaseAttachment(), FireplaceBase::CanShowSmoke(), FireplaceBase::EEItemAttached(), FireplaceBase::IsThisIgnitionSuccessful(), OnVariablesSynchronized(), ParticleFireEndStart(), ParticleFireStartStart(), ParticleFireWindyNoIgniteStart(), ParticleNormalFireStart(), ParticleSmallFireStart(), RefreshFireplaceVisuals(), FireplaceBase::RefreshPhysics(), and StartHeating().
IsPrepareToDelete()
override bool IsPrepareToDelete ()
Definition at line 594 of file fireplacebase.c.
    {
        return IsEmpty() && !IsBurning() && !HasAshes();
    }
References HasAshes(), IsBurning(), and IsEmpty().
IsRainingAbove()
bool IsRainingAbove ()
Definition at line 2499 of file fireplacebase.c.
    {
        return FireplaceBase.IsRainingAboveEntity( this );
    }
Referenced by Cooling(), Heating(), and FireplaceBase::IsThisIgnitionSuccessful().
IsRainingAboveEntity()
static bool IsRainingAboveEntity (notnull EntityAI entity_ai) static
Definition at line 2494 of file fireplacebase.c.
    {
        return ( GetGame() && ( GetGame().GetWeather().GetRain().GetActual() >= FireplaceBase.PARAM_IGNITE_RAIN_THRESHOLD ) );
    }
References GetGame().
IsRoofAbove()
bool IsRoofAbove ()
Definition at line 2476 of file fireplacebase.c.
    {
        return m_RoofAbove;
    }
References m_RoofAbove.
Referenced by Cooling(), ParticleNormalSmokeStart(), ParticleSmallSmokeStart(), and StartHeating().
IsSpaceFor()
bool IsSpaceFor (vector size)
Definition at line 2573 of file fireplacebase.c.
    {
        array<Object> objs = {};
        if (GetGame().IsBoxCollidingGeometry(GetWorldPosition() + Vector(0, size[1] * 0.5 + 0.1, 0), GetDirection().VectorToAngles(), size, ObjIntersect.View, ObjIntersect.Geom, {this}, objs))
        {
            foreach (Object obj : objs)
            {
                if (dBodyGetInteractionLayer(obj) == PhxInteractionLayers.ITEM_LARGE)
                    return false;
            }
        }
        return true;
    }
References dBodyGetInteractionLayer(), GetDirection(), GetGame(), GetWorldPosition(), and Vector().
Referenced by IsSpaceForCircle(), and IsSpaceForOven().
IsSpaceForCircle()
bool IsSpaceForCircle ()
Definition at line 2617 of file fireplacebase.c.
    {
        return IsSpaceFor(Vector(0.9, 0.1, 0.9));
    }
References IsSpaceFor(), and Vector().
Referenced by CanBuildStoneCircle().
IsSpaceForOven()
bool IsSpaceForOven ()
Definition at line 2605 of file fireplacebase.c.
    {
        const float size = 0.6;
        return IsSpaceFor(Vector(size, size, size));
    }
References IsSpaceFor(), and Vector().
Referenced by CanBuildOven().
IsWet()
bool IsWet ()
Definition at line 2470 of file fireplacebase.c.
    {
        return FireplaceBase.IsEntityWet( this );
    }
Referenced by FireplaceBase::IsThisIgnitionSuccessful(), and RefreshFireplaceVisuals().
IsWindy()
static bool IsWindy () static
Definition at line 2445 of file fireplacebase.c.
    {
        //check wind
        float wind_speed = GetGame().GetWeather().GetWindSpeed();
        float wind_speed_threshold = GetGame().GetWeather().GetWindMaximumSpeed() * FireplaceBase.IGNITE_WIND_THRESHOLD;
        return ( wind_speed >= wind_speed_threshold );
    }
References GetGame(), CGame::GetWeather(), Weather::GetWindMaximumSpeed(), and Weather::GetWindSpeed().
Referenced by FireplaceBase::IsThisIgnitionSuccessful(), and StartHeating().
LockOvenAttachments()
void LockOvenAttachments (bool lock)
Definition at line 2777 of file fireplacebase.c.
    {
        //Print("LockOvenAttachments");
        //string path_cooking_equipment = "" + CFG_VEHICLESPATH + " " + GetType() + " GUIInventoryAttachmentsProps CookingEquipment attachmentSlots";
        string path_cooking_equipment = string.Format("%1 %2 GUIInventoryAttachmentsProps CookingEquipment attachmentSlots", CFG_VEHICLESPATH, GetType());
        //string path_direct_cooking = "" + CFG_VEHICLESPATH + " " + GetType() + " GUIInventoryAttachmentsProps DirectCooking attachmentSlots";
        string path_direct_cooking = string.Format("%1 %2 GUIInventoryAttachmentsProps DirectCooking attachmentSlots", CFG_VEHICLESPATH, GetType());
        if ( GetGame().ConfigIsExisting(path_cooking_equipment) && GetGame().ConfigIsExisting(path_direct_cooking) )
        {
            array<string> arr_cooking_equipment = new array<string>;
            array<string> arr_direct_cooking = new array<string>;
            GetGame().ConfigGetTextArray(path_cooking_equipment,arr_cooking_equipment);
            GetGame().ConfigGetTextArray(path_direct_cooking,arr_direct_cooking);
            for ( int i = 0; i < arr_cooking_equipment.Count(); i++ )
            {
                if ( lock != GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(arr_cooking_equipment[i])) )
                {
                    GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(arr_cooking_equipment[i]),lock);
                    //Print("attachment lock: " + arr_cooking_equipment[i] + " " + lock);
                }
            }
            for ( i = 0; i < arr_direct_cooking.Count(); i++ )
            {
                if ( lock == GetInventory().GetSlotLock(InventorySlots.GetSlotIdFromString(arr_direct_cooking[i])) )
                {
                    GetInventory().SetSlotLock(InventorySlots.GetSlotIdFromString(arr_direct_cooking[i]),!lock);
                    //Print("attachment lock: " + arr_direct_cooking[i] + " " + !lock);
                }
            }
        }
        m_OvenAttachmentsLockState = lock;
    }
References CFG_VEHICLESPATH, CGame::ConfigGetTextArray(), ConfigIsExisting(), GetGame(), InventorySlots::GetSlotIdFromString(), GetSlotLock(), GetType(), and m_OvenAttachmentsLockState.
Referenced by RefreshFireplaceVisuals().
OnAttachmentQuantityChanged()
override void OnAttachmentQuantityChanged (ItemBase item)
Definition at line 2754 of file fireplacebase.c.
    {
        super.OnAttachmentQuantityChanged( item );
        CalcAndSetQuantity();
    }
References CalcAndSetQuantity().
OnAttachmentRuined()
override void OnAttachmentRuined (EntityAI attachment)
Definition at line 333 of file fireplacebase.c.
    {
        switch (attachment.Type())
        {
        case ATTACHMENT_TRIPOD:
        case ATTACHMENT_COOKINGSTAND:
            int slot = InventorySlots.GetSlotIdFromString("CookingEquipment");
            EntityAI ent = GetInventory().FindAttachment(slot);
            if (ent)
            {
                switch (ent.Type())
                {
                case ATTACHMENT_COOKING_POT:
                case ATTACHMENT_CAULDRON:
                case ATTACHMENT_FRYING_PAN:
                    vector direction = ent.GetDirection();
                    float dot = vector.Dot(direction, vector.Forward);
                    float angle = Math.Acos(dot);
                    if (direction[0] < 0)
                    {
                        angle = -angle;
                    }
                    float cos = Math.Cos(angle);
                    float sin = Math.Sin(angle);
                    GetInventory().DropEntityInBounds(InventoryMode.SERVER, this, ent, "2 0 2", angle, cos, sin);
                break;
                }
            }
            attachment.Delete();
        break;
        }
    }
References Math::Acos(), ATTACHMENT_CAULDRON, ATTACHMENT_COOKING_POT, ATTACHMENT_COOKINGSTAND, ATTACHMENT_FRYING_PAN, ATTACHMENT_TRIPOD, Math::Cos(), vector::Dot(), vector::Forward, InventorySlots::GetSlotIdFromString(), and Math::Sin().
OnDebugButtonPressServer()
override void OnDebugButtonPressServer (int button_index)
Definition at line 2880 of file fireplacebase.c.
    {
        switch (button_index)
        {
            case 1:
                OnIgnitedThis(null);
                break;
            case 2:
                StopFire();
                break;
        }
    }
References FireplaceBase::OnIgnitedThis(), and StopFire().
Referenced by InventoryItem::OnAction().
OnDebugSpawn()
override void OnDebugSpawn ()
Definition at line 2858 of file fireplacebase.c.
    {
            ItemBase firewood = ItemBase.Cast(GetInventory().CreateInInventory("Firewood"));
            firewood.SetQuantity(firewood.GetQuantityMax());
            ItemBase sticks = ItemBase.Cast(GetInventory().CreateInInventory("WoodenStick"));
            sticks.SetQuantity(sticks.GetQuantityMax());
            ItemBase stone = ItemBase.Cast(GetInventory().CreateInInventory("Stone"));
            stone.SetQuantity(stone.GetQuantityMax());
            GetInventory().CreateInInventory("Rag");
            SpawnEntityOnGroundPos("PetrolLighter", GetPosition());
    }
References CreateInInventory(), and GetPosition.
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 325 of file fireplacebase.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
        //refresh physics after location change (with delay)
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(RefreshFireplacePhysics);
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), and FireplaceBase::RefreshFireplacePhysics().
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0")
Definition at line 2658 of file fireplacebase.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        if ( GetGame().IsServer() )
        {
            //remove grass
            Object cc_object = GetGame().CreateObjectEx( OBJECT_CLUTTER_CUTTER , position, ECE_PLACE_ON_SURFACE );
            cc_object.SetOrientation( orientation );
            GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).CallLater( GetGame().ObjectDelete, 1000, false, cc_object );
            SetIsPlaceSound( true );
        }
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLater(), CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, CGame::GetCallQueue(), GetGame(), OBJECT_CLUTTER_CUTTER, and SetIsPlaceSound().
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 2815 of file fireplacebase.c.
    {
        super.OnRPC( sender, rpc_type, ctx );
        ref Param1<bool> p = new Param1<bool>(false);
        if (ctx.Read(p))
        {
            bool failure = p.param1;
        }
        switch ( rpc_type )
        {
            case FirePlaceFailure.WIND:
                if ( failure )
                {
                    ParticleFireWindyNoIgniteStart();
                    SoundFireStop();
                    SoundFireWindyNoIgniteStart();
                }
            break;
            case FirePlaceFailure.WET:
                if ( failure )
                {
                    ParticleWetNoIgniteStart();
                    SoundFireStop();
                    SoundFireWetNoIgniteStart();
                }
            break;
        }
    }
References ParticleFireWindyNoIgniteStart(), ParticleWetNoIgniteStart(), Serializer::Read(), SoundFireStop(), SoundFireWetNoIgniteStart(), and SoundFireWindyNoIgniteStart().
OnStoreLoad()
override bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 399 of file fireplacebase.c.
    {
        if ( !super.OnStoreLoad(ctx, version) )
            return false;
        //--- Fireplace data ---
        //Load ashes state
        if ( !ctx.Read( m_HasAshes ) )
        {
            m_HasAshes = false;         //set default
            return false;
        }
        //Load temperature loss MP
        if ( !ctx.Read( m_TemperatureLossMP ) )
        {
            m_TemperatureLossMP = 1.0;  //set default
            return false;
        }
        //Load fuel burn rate MP
        if ( !ctx.Read( m_FuelBurnRateMP ) )
        {
            m_FuelBurnRateMP = 1.0;     //set default
            return false;
        }
        //Load burning state, if true start fire
        if ( !ctx.Read( m_IsBurning ) )
        {
            m_IsBurning = false;        //set default
            return false;
        }
        //---
        return true;
    }
References m_FuelBurnRateMP, m_HasAshes, m_IsBurning, m_TemperatureLossMP, and Serializer::Read().
OnStoreSave()
override void OnStoreSave (ParamsWriteContext ctx)
Definition at line 382 of file fireplacebase.c.
    {
        super.OnStoreSave(ctx);
        //Save ashes state
        ctx.Write( m_HasAshes );
        //Save temperature loss MP
        ctx.Write( m_TemperatureLossMP );
        //Save fuel burn rate MP
        ctx.Write( m_FuelBurnRateMP );
        //Save burning state
        ctx.Write( m_IsBurning );
    }
References m_FuelBurnRateMP, m_HasAshes, m_IsBurning, m_TemperatureLossMP, and Serializer::Write().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 470 of file fireplacebase.c.
    {
        super.OnVariablesSynchronized();
        RefreshFireplaceVisuals();
        RefreshFireParticlesAndSounds(false);
        if (IsPlaceSound())
        {
            PlayPlaceSound();
        }
        if (IsBaseFireplace() && !IsOven())
        {
            if (m_IsBurning && !m_AreaDamage)
            {
                CreateAreaDamage();
            }
            else if (!m_IsBurning && m_AreaDamage)
            {
                DestroyAreaDamage();
            }
        }
    }
References CreateAreaDamage(), DestroyAreaDamage(), FireplaceBase::IsBaseFireplace(), IsOven(), IsPlaceSound(), m_AreaDamage, m_IsBurning, PlayPlaceSound(), RefreshFireParticlesAndSounds(), and RefreshFireplaceVisuals().
ParticleFireEndStart()
protected void ParticleFireEndStart ()
Definition at line 1174 of file fireplacebase.c.
    {
        if ( IsOven() )
        {
            PlayParticle( m_ParticleFireEnd, PARTICLE_OVEN_FIRE_END, GetFireEffectPosition() );
        }
        else
        {
            PlayParticle( m_ParticleFireEnd, PARTICLE_FIRE_END, GetFireEffectPosition() );
        }
    }
References GetFireEffectPosition(), IsOven(), m_ParticleFireEnd, PARTICLE_FIRE_END, PARTICLE_OVEN_FIRE_END, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireEndStop()
protected void ParticleFireEndStop ()
Definition at line 1186 of file fireplacebase.c.
    {
        StopParticle( m_ParticleFireEnd );
    }
References m_ParticleFireEnd, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireStartStart()
protected void ParticleFireStartStart ()
Definition at line 1068 of file fireplacebase.c.
    {
        if ( IsOven() )
        {
            PlayParticle( m_ParticleFireStart, PARTICLE_OVEN_FIRE_START, GetFireEffectPosition() );
        }
        else
        {
            PlayParticle( m_ParticleFireStart, PARTICLE_FIRE_START, GetFireEffectPosition() );
        }
    }
References GetFireEffectPosition(), IsOven(), m_ParticleFireStart, PARTICLE_FIRE_START, PARTICLE_OVEN_FIRE_START, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireStartStop()
protected void ParticleFireStartStop ()
Definition at line 1080 of file fireplacebase.c.
    {
        StopParticle( m_ParticleFireStart );
    }
References m_ParticleFireStart, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleFireWindyNoIgniteStart()
protected void ParticleFireWindyNoIgniteStart ()
Definition at line 1191 of file fireplacebase.c.
    {
        if ( IsOven() )
        {
            PlayParticle( m_ParticleFireEnd, PARTICLE_OVEN_FIRE_END, GetFireEffectPosition() );
        }
        else
        {
            PlayParticle( m_ParticleFireEnd, PARTICLE_NO_IGNITE_WIND, GetFireEffectPosition() );
        }
    }
References GetFireEffectPosition(), IsOven(), m_ParticleFireEnd, PARTICLE_NO_IGNITE_WIND, PARTICLE_OVEN_FIRE_END, and PlayParticle().
Referenced by OnRPC().
ParticleNormalFireStart()
protected void ParticleNormalFireStart ()
Definition at line 1104 of file fireplacebase.c.
    {
        if ( IsOven() )
        {
            PlayParticle( m_ParticleNormalFire, PARTICLE_OVEN_FIRE, GetFireEffectPosition() );
        }
        else
        {
            PlayParticle( m_ParticleNormalFire, PARTICLE_NORMAL_FIRE, GetFireEffectPosition() );
        }
    }
References GetFireEffectPosition(), IsOven(), m_ParticleNormalFire, PARTICLE_NORMAL_FIRE, PARTICLE_OVEN_FIRE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalFireStop()
protected void ParticleNormalFireStop ()
Definition at line 1116 of file fireplacebase.c.
    {
        StopParticle( m_ParticleNormalFire );
    }
References m_ParticleNormalFire, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleNormalSmokeStart()
protected void ParticleNormalSmokeStart ()
Definition at line 1148 of file fireplacebase.c.
    {
        PlayParticle( m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, GetSmokeEffectPosition() );
        //calculate air resistance
        float actual_height;
        if ( GetCeilingHeight( actual_height ) )
        {
            float air_resistance = GetAirResistanceForSmokeParticles( actual_height );
            //alter smoke height
            m_ParticleNormalSmoke.SetParameter( -1, EmitorParam.AIR_RESISTANCE, air_resistance );
        }
        if ( IsRoofAbove() )
        {
            m_ParticleNormalSmoke.SetParameter( -1, EmitorParam.WIND, false );
        }
    }
References GetAirResistanceForSmokeParticles(), GetCeilingHeight(), FireplaceBase::GetSmokeEffectPosition(), IsRoofAbove(), m_ParticleNormalSmoke, PARTICLE_NORMAL_SMOKE, PlayParticle(), and Particle::SetParameter().
ParticleNormalSmokeStop()
protected void ParticleNormalSmokeStop ()
Definition at line 1168 of file fireplacebase.c.
    {
        StopParticle( m_ParticleNormalSmoke );
    }
References m_ParticleNormalSmoke, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallFireStart()
protected void ParticleSmallFireStart ()
Definition at line 1086 of file fireplacebase.c.
    {
        if ( IsOven() )
        {
            PlayParticle( m_ParticleSmallFire, PARTICLE_OVEN_FIRE, GetFireEffectPosition() );
        }
        else
        {
            PlayParticle( m_ParticleSmallFire, PARTICLE_SMALL_FIRE, GetFireEffectPosition() );
        }
    }
References GetFireEffectPosition(), IsOven(), m_ParticleSmallFire, PARTICLE_OVEN_FIRE, PARTICLE_SMALL_FIRE, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallFireStop()
protected void ParticleSmallFireStop ()
Definition at line 1098 of file fireplacebase.c.
    {
        StopParticle( m_ParticleSmallFire );
    }
References m_ParticleSmallFire, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSmallSmokeStart()
protected void ParticleSmallSmokeStart ()
Definition at line 1122 of file fireplacebase.c.
    {
        PlayParticle( m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, GetSmokeEffectPosition() );
        //calculate air resistance
        float actual_height;
        if ( GetCeilingHeight( actual_height ) )
        {
            float air_resistance = GetAirResistanceForSmokeParticles( actual_height );
            //alter smoke height
            m_ParticleSmallSmoke.SetParameter( -1, EmitorParam.AIR_RESISTANCE, air_resistance );
        }
        if ( IsRoofAbove() )
        {
            m_ParticleSmallSmoke.SetParameter( -1, EmitorParam.WIND, false );
        }
    }
References GetAirResistanceForSmokeParticles(), GetCeilingHeight(), FireplaceBase::GetSmokeEffectPosition(), IsRoofAbove(), m_ParticleSmallSmoke, PARTICLE_SMALL_SMOKE, PlayParticle(), and Particle::SetParameter().
ParticleSmallSmokeStop()
protected void ParticleSmallSmokeStop ()
Definition at line 1142 of file fireplacebase.c.
    {
        StopParticle( m_ParticleSmallSmoke );
    }
References m_ParticleSmallSmoke, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamEndStart()
protected void ParticleSteamEndStart ()
Definition at line 1215 of file fireplacebase.c.
    {
        PlayParticle( m_ParticleSteamEnd, PARTICLE_STEAM_END, GetFireEffectPosition() );
    }
References GetFireEffectPosition(), m_ParticleSteamEnd, PARTICLE_STEAM_END, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamEndStop()
protected void ParticleSteamEndStop ()
Definition at line 1220 of file fireplacebase.c.
    {
        StopParticle( m_ParticleSteamEnd );
    }
References m_ParticleSteamEnd, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamExtinguishingStart()
protected void ParticleSteamExtinguishingStart ()
Definition at line 1204 of file fireplacebase.c.
    {
        PlayParticle( m_ParticleSteamExtinguishing, PARTICLE_STEAM_EXTINGUISHING, GetFireEffectPosition() );
    }
References GetFireEffectPosition(), m_ParticleSteamExtinguishing, PARTICLE_STEAM_EXTINGUISHING, and PlayParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleSteamExtinguishingStop()
protected void ParticleSteamExtinguishingStop ()
Definition at line 1209 of file fireplacebase.c.
    {
        StopParticle(m_ParticleSteamExtinguishing);
    }
References m_ParticleSteamExtinguishing, and StopParticle().
Referenced by RefreshFireParticlesAndSounds().
ParticleWetNoIgniteStart()
protected void ParticleWetNoIgniteStart ()
Definition at line 1225 of file fireplacebase.c.
    {
        PlayParticle( m_ParticleSteamEnd, PARTICLE_STEAM_END, GetFireEffectPosition() );
    }
References GetFireEffectPosition(), m_ParticleSteamEnd, PARTICLE_STEAM_END, and PlayParticle().
Referenced by OnRPC().
ParticleWetNoIgniteStop()
protected void ParticleWetNoIgniteStop ()
Definition at line 1230 of file fireplacebase.c.
    {
        StopParticle( m_ParticleSteamEnd );
    }
References m_ParticleSteamEnd, and StopParticle().
PlayParticle()
protected bool PlayParticle (out Particle particle, int particle_type, vector pos, bool worldpos = false)
Definition at line 1034 of file fireplacebase.c.
    {
        if ( !particle && GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            if ( !worldpos )
            {
                particle = ParticleManager.GetInstance().PlayOnObject( particle_type, this, pos );
            }
            else
            {
                particle = ParticleManager.GetInstance().PlayInWorld( particle_type, pos );
            }
            return true;
        }
        return false;
    }
References GetGame(), and ParticleManager().
RefreshFireParticlesAndSounds()
protected void RefreshFireParticlesAndSounds (bool force_refresh)
Definition at line 792 of file fireplacebase.c.
    {
        FireplaceFireState fire_state = GetFireState();
        if ( m_LastFireState != fire_state || force_refresh )
        {
            switch ( fire_state )
            {
                case FireplaceFireState.START_FIRE:
                {
                    //particles
                    ParticleFireStartStart();
                    //sounds
                    SoundFireStop();
                    SoundFireLightStart();
                    break;
                }
                case FireplaceFireState.SMALL_FIRE:
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStart();
                    if ( CanShowSmoke() )
                        ParticleSmallSmokeStart();
                    else
                        ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleSteamExtinguishingStop();
                    //sounds
                    SoundFireStop();
                    SoundFireLightStart();
                    break;
                }
                case FireplaceFireState.NORMAL_FIRE:
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStart();
                    if ( CanShowSmoke() )
                        ParticleNormalSmokeStart();
                    else
                        ParticleNormalSmokeStop();
                    ParticleSteamExtinguishingStop();
                    //sounds
                    SoundFireStop();
                    SoundFireHeavyStart();
                    break;
                }
                case FireplaceFireState.END_FIRE:
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleFireEndStart();
                    //sounds
                    SoundFireStop();
                    SoundFireNoFireStart();
                    break;
                }
                case FireplaceFireState.EXTINGUISHING_FIRE:     //TODO add steam particles when extinguishing
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleFireEndStop();
                    ParticleSteamExtinguishingStart();
                    //sounds
                    SoundFireStop();
                    SoundFireExtinguishingStart();
                    break;
                }
                case FireplaceFireState.EXTINGUISHED_FIRE:      //TODO add steam particles when fireplace is extinguished
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleFireEndStop();
                    ParticleSteamExtinguishingStop();
                    if ( CanShowSmoke() )
                        ParticleSteamEndStart();
                    else
                        ParticleSteamEndStop();
                    //sounds
                    SoundFireStop();
                    SoundFireExtinguishedStart();
                    SoundFireNoFireStart();
                    break;
                }
                case FireplaceFireState.REIGNITED_FIRE:
                {
                    //particles
                    ParticleFireStartStart();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleFireEndStop();
                    ParticleSteamEndStop();
                    //sounds
                    SoundFireStop();
                    break;
                }
                case FireplaceFireState.NO_FIRE:
                {
                    //particles
                    ParticleFireStartStop();
                    ParticleSmallFireStop();
                    ParticleSmallSmokeStop();
                    ParticleNormalFireStop();
                    ParticleNormalSmokeStop();
                    ParticleFireEndStop();
                    ParticleSteamEndStop();
                    ParticleSteamExtinguishingStop();
                    //sounds
                    SoundFireStop();
                    break;
                }
            }
            m_LastFireState = fire_state;
        }
    }
References FireplaceBase::CanShowSmoke(), GetFireState(), m_LastFireState, ParticleFireEndStart(), ParticleFireEndStop(), ParticleFireStartStart(), ParticleFireStartStop(), ParticleNormalFireStart(), ParticleNormalFireStop(), FireplaceBase::ParticleNormalSmokeStart(), ParticleNormalSmokeStop(), ParticleSmallFireStart(), ParticleSmallFireStop(), FireplaceBase::ParticleSmallSmokeStart(), ParticleSmallSmokeStop(), ParticleSteamEndStart(), ParticleSteamEndStop(), ParticleSteamExtinguishingStart(), ParticleSteamExtinguishingStop(), SoundFireExtinguishedStart(), SoundFireExtinguishingStart(), SoundFireHeavyStart(), SoundFireLightStart(), SoundFireNoFireStart(), and SoundFireStop().
Referenced by OnVariablesSynchronized(), and FireplaceBase::OnVariablesSynchronized().
RefreshFireplacePhysics()
void RefreshFireplacePhysics ()
RefreshFireplaceVisuals()
void RefreshFireplaceVisuals ()
single stone; everything else hidden
hide stones stack completely
Definition at line 609 of file fireplacebase.c.
    {
        if (IsHologram())
        {
            return;
        }
        // Light
        #ifndef SERVER
        if (IsBurning() )
        {
            //turn light on
            if (!GetLightEntity())
            {
                SetLightEntity(FireplaceLight.Cast(ScriptedLightBase.CreateLight(FireplaceLight, GetPosition(), 20)));
                GetLightEntity().AttachOnMemoryPoint(this, "light");
            }
            if (GetLightEntity() && GetLightEntity().GetBrightness() > 0)
            {
                // change brightness based on the distance of player to the fireplace
                Object player   = GetGame().GetPlayer();
                float lightDist = m_LightDistance;
                if (IsOven())
                {
                    lightDist = 50;
                }
                if (player)
                {
                    if (vector.DistanceSq(player.GetPosition(), this.GetPosition()) > lightDist * lightDist)
                    {
                        GetLightEntity().FadeBrightnessTo(0, 5);
                    }
                    else
                    {
                        GetLightEntity().FadeBrightnessTo(FireplaceLight.m_FireplaceBrightness, 5);
                    }
                }
                // The following solves an issue with the light point clipping through narrow geometry
                if (IsItemTypeAttached(ATTACHMENT_STONES) || IsBarrelWithHoles() || IsFireplaceIndoor())
                {
                    GetLightEntity().SetInteriorMode();
                }
                else
                {
                    GetLightEntity().SetExteriorMode();
                }
            }
        }
        else
        {
            //turn light off
            if (GetLightEntity())
            {
                GetLightEntity().FadeOut();
            }
        }
        #endif
        //set default burn parameters based on fireplace type
        if (IsBarrelWithHoles() || IsFireplaceIndoor() || IsIndoorOven() || IsOven())
        {
            SetFuelBurnRateMP(FUEL_BURN_RATE_OVEN);
            SetTemperatureLossMP(TEMPERATURE_LOSS_MP_OVEN);
        }
        else if (HasStoneCircle())
        {
            SetFuelBurnRateMP(FUEL_BURN_RATE_STONES);
            SetTemperatureLossMP(TEMPERATURE_LOSS_MP_STONES);
        }
        else
        {
            SetFuelBurnRateMP(FUEL_BURN_RATE_DEFAULT);
            SetTemperatureLossMP(TEMPERATURE_LOSS_MP_DEFAULT);
        }
        // Oven attachments
        if (IsOven())
        {
            //lock attachment slots
            if (!m_OvenAttachmentsLockState)
            {
                LockOvenAttachments(true);
            }
        }
        else
        {
            //unlock attachment slots
            if (m_OvenAttachmentsLockState)
            {
                LockOvenAttachments(false);
            }
        }
        //VISUAL STATES
        //Fuel state
        if ( GetGame().IsServer() ) // SetAnimationPhase should ideally be called on server only..
        {
            // Sticks state
            if ( IsItemTypeAttached( ATTACHMENT_STICKS ) )
                SetAnimationPhase( ANIMATION_STICKS, 0 );
            else
                SetAnimationPhase( ANIMATION_STICKS, 1 );
            // Firewood state
            if ( IsItemTypeAttached( ATTACHMENT_FIREWOOD ) )
            {
                if ( IsBurning() && HasAshes() )
                {
                    SetAnimationPhase( ANIMATION_BURNT_WOOD, 0 ); // Because this might not be set under certain circumstances
                    SetAnimationPhase( ANIMATION_WOOD, 1 );
                }
                if ( IsWet() || !IsBurning() )
                {
                    SetAnimationPhase( ANIMATION_BURNT_WOOD, 1 );
                    SetAnimationPhase( ANIMATION_WOOD, 0 );
                }
            }
            else
            {
                SetAnimationPhase( ANIMATION_WOOD, 1 );
                SetAnimationPhase( ANIMATION_BURNT_WOOD, 1 );
            }
            // Kindling state
            if ( GetKindlingCount() != 0 )
                SetAnimationPhase( ANIMATION_KINDLING, 0 );
            else
                SetAnimationPhase( ANIMATION_KINDLING, 1 );
            // Ashes state
            if ( HasAshes() )
                SetAnimationPhase( ANIMATION_ASHES, 0 );
            else
                SetAnimationPhase( ANIMATION_ASHES, 1 );
            // Stone variations
            if (HasStones())
            {
                if (HasStoneCircle())
                {
                    SetAnimationPhase(ANIMATION_STONES, 0);
                    SetAnimationPhase(ANIMATION_STONE, 1);
                }
                else if (IsOven())
                {
                    SetAnimationPhase(ANIMATION_OVEN, 0);
                    SetAnimationPhase(ANIMATION_STONE, 1);
                }
                else
                {
                    SetAnimationPhase(ANIMATION_STONES, 1);
                    SetAnimationPhase(ANIMATION_OVEN, 1);
                    SetAnimationPhase(ANIMATION_STONE, 0);
                }
            }
            else
            {
                SetAnimationPhase(ANIMATION_STONE, 1);
            }
        }
        //refresh physics (with delay)
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(RefreshFireplacePhysics);
    }
References ANIMATION_ASHES, ANIMATION_BURNT_WOOD, ANIMATION_KINDLING, ANIMATION_OVEN, ANIMATION_STICKS, ANIMATION_STONE, ANIMATION_STONES, ANIMATION_WOOD, ATTACHMENT_FIREWOOD, ATTACHMENT_STICKS, ATTACHMENT_STONES, ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, vector::DistanceSq(), FUEL_BURN_RATE_DEFAULT, FUEL_BURN_RATE_OVEN, FUEL_BURN_RATE_STONES, CGame::GetCallQueue(), GetGame(), GetKindlingCount(), GetLightEntity(), CGame::GetPlayer(), GetPosition, HasAshes(), HasStoneCircle(), HasStones(), FireplaceBase::IsBarrelWithHoles(), IsBurning(), FireplaceBase::IsFireplaceIndoor(), IsHologram(), FireplaceBase::IsIndoorOven(), IsItemTypeAttached(), IsOven(), IsWet(), LockOvenAttachments(), m_LightDistance, m_OvenAttachmentsLockState, FireplaceBase::RefreshFireplacePhysics(), SetFuelBurnRateMP(), SetLightEntity(), SetTemperatureLossMP(), TEMPERATURE_LOSS_MP_DEFAULT, TEMPERATURE_LOSS_MP_OVEN, and TEMPERATURE_LOSS_MP_STONES.
Referenced by EEInit(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), OnVariablesSynchronized(), SetItemToConsume(), and Synchronize().
RefreshFireState()
void RefreshFireState ()
Definition at line 996 of file fireplacebase.c.
    {
        float temperature = GetTemperature();
        //if it's burning
        if (IsBurning())
        {
            //Start fire
            if (temperature <= PARAM_MIN_FIRE_TEMPERATURE)
            {
                if ( GetFireState() != FireplaceFireState.START_FIRE )
                {
                    SetFireState( FireplaceFireState.START_FIRE );
                }
            }
            //Small fire
            else if (temperature <= PARAM_SMALL_FIRE_TEMPERATURE)
            {
                if ( GetFireState() != FireplaceFireState.SMALL_FIRE )
                {
                    SetFireState( FireplaceFireState.SMALL_FIRE );
                }
            }
            //Normal fire
            else if (temperature > PARAM_SMALL_FIRE_TEMPERATURE)
            {
                if ( GetFireState() != FireplaceFireState.NORMAL_FIRE )
                {
                    SetFireState( FireplaceFireState.NORMAL_FIRE );
                }
            }
        }
    }
References GetFireState(), GetTemperature(), IsBurning(), PARAM_MIN_FIRE_TEMPERATURE, PARAM_SMALL_FIRE_TEMPERATURE, and SetFireState().
Referenced by Heating().
RemoveFromFireConsumables()
protected void RemoveFromFireConsumables (FireConsumable fire_consumable)
Definition at line 1345 of file fireplacebase.c.
    {
        if ( fire_consumable )
        {
            m_FireConsumables.Remove( fire_consumable.GetItem() );
            delete fire_consumable;
        }
        CalcAndSetQuantity();
    }
References CalcAndSetQuantity(), FireConsumable::GetItem(), and m_FireConsumables.
Referenced by FireplaceBase::EEItemDetached(), and SpendFireConsumable().
SetAshesState()
protected void SetAshesState (bool has_ashes)
Definition at line 1612 of file fireplacebase.c.
    {
        m_HasAshes = has_ashes;
        if (m_HasAshes)
        {
            SetBurntFirewood();     //set burnt wood visual
        }
    }
References m_HasAshes, and SetBurntFirewood().
Referenced by SpendFireConsumable().
SetBurningState()
protected void SetBurningState (bool is_burning)
Definition at line 1600 of file fireplacebase.c.
    {
        m_IsBurning = is_burning;
    }
References m_IsBurning.
Referenced by StartFire(), and StopFire().
SetBurntFirewood()
protected void SetBurntFirewood ()
Definition at line 780 of file fireplacebase.c.
    {
        if ( GetGame().IsServer() && IsInAnimPhase( ANIMATION_WOOD ) )
        {
            SetAnimationPhase( ANIMATION_WOOD, 1 );
            SetAnimationPhase( ANIMATION_BURNT_WOOD, 0 );
        }
    }
References ANIMATION_BURNT_WOOD, ANIMATION_WOOD, GetGame(), and IsInAnimPhase().
Referenced by SetAshesState().
SetCookingEquipment()
void SetCookingEquipment (ItemBase equipment)
Definition at line 542 of file fireplacebase.c.
    {
        m_CookingEquipment = equipment;
    }
References m_CookingEquipment.
SetExtinguishingState()
void SetExtinguishingState ()
Definition at line 1712 of file fireplacebase.c.
    {
        SetFireState( FireplaceFireState.EXTINGUISHING_FIRE );
    }
References SetFireState().
SetFireState()
protected void SetFireState (FireplaceFireState state)
Definition at line 1702 of file fireplacebase.c.
    {
        if ( m_FireState != state )
        {
            m_FireState = state;
            Synchronize();
        }
    }
References m_FireState, and Synchronize().
Referenced by EEDelete(), RefreshFireState(), SetExtinguishingState(), StopCooling(), and StopFire().
SetFuelBurnRateMP()
protected void SetFuelBurnRateMP (float value)
Definition at line 1690 of file fireplacebase.c.
    {
        m_FuelBurnRateMP = value;
    }
References m_FuelBurnRateMP.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
SetIgniteFailure()
void SetIgniteFailure (bool failure)
Definition at line 2459 of file fireplacebase.c.
    {
        m_NoIgnite = failure;
    }
References m_NoIgnite.
Referenced by FireplaceBase::IsThisIgnitionSuccessful().
SetItemToConsume()
protected FireConsumable SetItemToConsume ()
Definition at line 1364 of file fireplacebase.c.
    {
        if ( m_FireConsumables.Count() == 0 )
        {
            m_ItemToConsume = NULL;
        }
        else
        {
            float energy = 0;
            for ( int i = 0; i < m_FireConsumables.Count(); ++i )
            {
                ItemBase key = m_FireConsumables.GetKey( i );
                ref FireConsumable fire_consumable = m_FireConsumables.Get( key );
                energy = fire_consumable.GetEnergy();
                if ( i == 0 )
                {
                    m_ItemToConsume = fire_consumable;
                }
                else
                {
                    if ( fire_consumable.GetEnergy() < m_ItemToConsume.GetEnergy() )
                    {
                        m_ItemToConsume = fire_consumable;
                    }
                }
            }
        }
        //refresh visual
        RefreshFireplaceVisuals();
        return m_ItemToConsume;
    }
References FireConsumable::GetEnergy(), m_FireConsumables, m_ItemToConsume, and RefreshFireplaceVisuals().
Referenced by SpendFireConsumable(), and StartFire().
SetLightEntity()
void SetLightEntity (FireplaceLight light)
Definition at line 2649 of file fireplacebase.c.
    {
        m_Light = light;
    }
References m_Light.
Referenced by RefreshFireplaceVisuals().
SetOvenState()
void SetOvenState (bool is_oven)
Definition at line 1649 of file fireplacebase.c.
    {
        if ( m_IsOven != is_oven )
        {
            m_IsOven = is_oven;
            m_RoofAbove = is_oven;
            GetInventory().SetSlotLock( InventorySlots.GetSlotIdFromString("Stones") , is_oven);
            Synchronize();
        }
    }
References InventorySlots::GetSlotIdFromString(), m_IsOven, m_RoofAbove, and Synchronize().
SetStoneCircleState()
void SetStoneCircleState (bool has_stonecircle)
Definition at line 1661 of file fireplacebase.c.
    {
        if ( m_HasStoneCircle != has_stonecircle )
        {
            m_HasStoneCircle = has_stonecircle;
            GetInventory().SetSlotLock( InventorySlots.GetSlotIdFromString("Stones") , has_stonecircle);
            Synchronize();
        }
    }
References InventorySlots::GetSlotIdFromString(), m_HasStoneCircle, and Synchronize().
SetTemperatureLossMP()
protected void SetTemperatureLossMP (float value)
Definition at line 1679 of file fireplacebase.c.
    {
        m_TemperatureLossMP = value;
    }
References m_TemperatureLossMP.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
SmokeOnSmokingSlot()
protected void SmokeOnSmokingSlot (ItemBase slot_item, float temp_equip, float temp_ext)
Definition at line 2215 of file fireplacebase.c.
    {
        if ( m_CookingProcess == NULL )
        {
            m_CookingProcess = new Cooking();
        }
        // smoking slots accept only individual meat/fruit/veg items
        Edible_Base ingr = Edible_Base.Cast( slot_item );
        if ( ingr )
        {
            m_CookingProcess.SmokeItem( ingr, FireplaceBase.TIMER_HEATING_UPDATE_INTERVAL * FireplaceBase.SMOKING_SPEED );
        }
    }
References m_CookingProcess.
Referenced by Cooling(), and Heating().
SmokingSlotsInUse()
bool SmokingSlotsInUse ()
Definition at line 575 of file fireplacebase.c.
    {
        for (int i = 0; i < SMOKING_SLOT_COUNT; i++)
        {
            if ( m_SmokingSlots[i] )
            {
                return true;
            }
        }
        return false;
    }
References m_SmokingSlots, and SMOKING_SLOT_COUNT.
Referenced by CanDismantleOven(), FireplaceBase::CanPutIntoHands(), Cooling(), and Heating().
SoundFireExtinguishedStart()
protected void SoundFireExtinguishedStart ()
Definition at line 1294 of file fireplacebase.c.
    {
        PlaySoundSet( m_SoundFire, SOUND_FIRE_EXTINGUISHED, 0.1, 0.1 );
    }
References m_SoundFire, PlaySoundSet(), and SOUND_FIRE_EXTINGUISHED.
Referenced by RefreshFireParticlesAndSounds().
SoundFireExtinguishingStart()
protected void SoundFireExtinguishingStart ()
Definition at line 1304 of file fireplacebase.c.
    {
        PlaySoundSetLoop( m_SoundFireLoop, SOUND_FIRE_EXTINGUISHING, 1.0, 0.5 );
    }
References m_SoundFireLoop, PlaySoundSetLoop(), and SOUND_FIRE_EXTINGUISHING.
Referenced by RefreshFireParticlesAndSounds().
SoundFireHeavyStart()
protected void SoundFireHeavyStart ()
Definition at line 1284 of file fireplacebase.c.
    {
        PlaySoundSetLoop( m_SoundFireLoop, SOUND_FIRE_HEAVY, 1.0, 2.0 );
    }
References m_SoundFireLoop, PlaySoundSetLoop(), and SOUND_FIRE_HEAVY.
Referenced by RefreshFireParticlesAndSounds().
SoundFireLightStart()
protected void SoundFireLightStart ()
Definition at line 1279 of file fireplacebase.c.
    {
        PlaySoundSetLoop( m_SoundFireLoop, SOUND_FIRE_LIGHT, 1.0, 1.0 );
    }
References m_SoundFireLoop, PlaySoundSetLoop(), and SOUND_FIRE_LIGHT.
Referenced by RefreshFireParticlesAndSounds().
SoundFireNoFireStart()
protected void SoundFireNoFireStart ()
Definition at line 1289 of file fireplacebase.c.
    {
        PlaySoundSetLoop( m_SoundFireLoop, SOUND_FIRE_NO_FIRE, 2.0, 2.0 );
    }
References m_SoundFireLoop, PlaySoundSetLoop(), and SOUND_FIRE_NO_FIRE.
Referenced by RefreshFireParticlesAndSounds().
SoundFireStop()
protected void SoundFireStop ()
Definition at line 1315 of file fireplacebase.c.
    {
        StopSoundSet( m_SoundFireLoop );
    }
References m_SoundFireLoop, and StopSoundSet().
Referenced by OnRPC(), and RefreshFireParticlesAndSounds().
SoundFireWetNoIgniteStart()
protected void SoundFireWetNoIgniteStart ()
Definition at line 1299 of file fireplacebase.c.
    {
        PlaySoundSet( m_SoundFire, SOUND_FIRE_EXTINGUISHED, 0.1, 0.1 );
    }
References m_SoundFire, PlaySoundSet(), and SOUND_FIRE_EXTINGUISHED.
Referenced by OnRPC().
SoundFireWindyNoIgniteStart()
protected void SoundFireWindyNoIgniteStart ()
Definition at line 1309 of file fireplacebase.c.
    {
        PlaySoundSet( m_SoundFire, "ExtinguishByWind_SoundSet", 0, 0 );
    }
References m_SoundFire, and PlaySoundSet().
Referenced by OnRPC().
SpendFireConsumable()
protected void SpendFireConsumable (float amount)
Definition at line 1409 of file fireplacebase.c.
    {
        //spend item
        ref FireConsumable fire_consumable = GetItemToConsume();
        if ( !fire_consumable )
        {
            //Set new item to consume
            fire_consumable = SetItemToConsume();
        }
        if ( fire_consumable )
        {
            ItemBase item = fire_consumable.GetItem();
            //set remaining energy
            fire_consumable.SetRemainingEnergy( fire_consumable.GetRemainingEnergy() - amount );
            //Debug
            /*
            PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
            string message = "item type = " + item.GetType() + " m_RemainingEnergy = " + fire_consumable.GetRemainingEnergy().ToString() + " quantity = " + item.GetQuantity().ToString() + " amount = " + amount.ToString();
            player.MessageAction ( message );
            */
            if ( fire_consumable.GetRemainingEnergy() <= 0 || amount == 0 )
            {
                //set ashes
                if ( !HasAshes() )
                {
                    SetAshesState( true );
                }
                if ( item.IsInherited( ItemBook ) || item.IsInherited( Paper )|| item.IsInherited( GiftWrapPaper ) )
                {
                    //Debug
                    //Print( "Item consumed = " + item.GetType() + " time = " + m_debug_fire_consume_time.ToString() );
                    //m_debug_fire_consume_time = 0;
                    //
                    RemoveFromFireConsumables( fire_consumable );
                    item.Delete();
                }
                else
                {
                    //if there is nothing left, delete and remove old consumable, set new fire consumable
                    if ( item.GetQuantity() <= 1 )
                    {
                        //remove item from fuel items
                        RemoveFromFireConsumables( fire_consumable );
                    }
                    else
                    {
                        fire_consumable.SetRemainingEnergy( fire_consumable.GetEnergy() );
                    }
                    //Debug
                    //Print( "Item consumed = " + item.GetType() + " time = " + m_debug_fire_consume_time.ToString() );
                    //m_debug_fire_consume_time = 0;
                    //
                    item.AddQuantity( -1 );
                    SetItemToConsume();         //set item after each quantity decrease
                }
            }
        }
        //debug
        //m_debug_fire_consume_time += TIMER_HEATING_UPDATE_INTERVAL;
        //
        CalcAndSetQuantity();
    }
References CalcAndSetQuantity(), GetItemToConsume(), HasAshes(), RemoveFromFireConsumables(), SetAshesState(), and SetItemToConsume().
Referenced by Heating(), and StopFire().
StartCooling()
protected void StartCooling ()
Definition at line 1998 of file fireplacebase.c.
    {
        //Debug
        //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        //if (player != NULL) {player.MessageAction ( "Start cooling..." );}
        //Print("Start cooling...");
        //stop heating timer if active
        if ( m_HeatingTimer )
        {
            m_HeatingTimer.Stop();
            m_HeatingTimer = NULL;
        }
        //Start cooling
        m_CoolingTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
        m_CoolingTimer.Run( TIMER_COOLING_UPDATE_INTERVAL, this, "Cooling", NULL, true );
    }
References CALL_CATEGORY_GAMEPLAY, m_CoolingTimer, m_HeatingTimer, and TIMER_COOLING_UPDATE_INTERVAL.
Referenced by StopFire().
StartFire()
void StartFire (bool force_start = false)
Definition at line 1725 of file fireplacebase.c.
    {
        //stop cooling process if active
        if ( m_CoolingTimer )
        {
            m_CoolingTimer.Stop();
            m_CoolingTimer = NULL;
        }
        //set under roof flag (was fire ignited under roof?)
        if (MiscGameplayFunctions.IsUnderRoof(this))
        {
            m_RoofAbove = true;
        }
        //start fire
        if ( !IsBurning() || force_start )
        {
            //set fuel to consume
            SetItemToConsume();
            //set fire state
            SetBurningState( true );
            m_UTSource.SetActive(true);
            //start heating
            StartHeating();
            //Update navmesh
            if ( !IsFireplaceIndoor() )
            {
                SetAffectPathgraph( false, true );
                GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( GetGame().UpdatePathgraphRegionByObject, 100, false, this );
            }
        }
        Synchronize();
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), IsBurning(), FireplaceBase::IsFireplaceIndoor(), m_CoolingTimer, m_RoofAbove, m_UTSource, SetAffectPathgraph(), SetBurningState(), SetItemToConsume(), StartHeating(), and Synchronize().
Referenced by AfterStoreLoad(), and FireplaceBase::OnIgnitedThis().
StartHeating()
protected void StartHeating ()
Definition at line 1765 of file fireplacebase.c.
    {
        //visual
        SetObjectMaterial( 0, MATERIAL_FIREPLACE_GLOW );
        if ( IsWindy() && !IsRoofAbove() && !IsOven() && !IsBarrelWithHoles() )
        {
            StopFire();
            return;
        }
        if ( GetWet() > PARAM_BURN_WET_THRESHOLD )
        {
            StopFire( FireplaceFireState.EXTINGUISHED_FIRE );
            return;
        }
        //create area damage
        if ( IsBaseFireplace() && !IsOven() )
        {
            CreateAreaDamage();
        }
        m_HeatingTimer = new Timer( CALL_CATEGORY_GAMEPLAY );
        m_HeatingTimer.Run( TIMER_HEATING_UPDATE_INTERVAL, this, "Heating", NULL, true );
        //Setup the noise parameters on fire start
        m_NoisePar = new NoiseParams();
        if ( IsRoofAbove() || IsOven() || IsFireplaceIndoor() ) //If we have a roof, we are probably inside
            m_NoisePar.LoadFromPath("CfgVehicles FireplaceBase NoiseFireplaceSpecial");
        else
            m_NoisePar.LoadFromPath("CfgVehicles FireplaceBase NoiseFireplaceBase");
    }
References CALL_CATEGORY_GAMEPLAY, CreateAreaDamage(), GetWet(), FireplaceBase::IsBarrelWithHoles(), FireplaceBase::IsBaseFireplace(), FireplaceBase::IsFireplaceIndoor(), IsOven(), IsRoofAbove(), IsWindy(), m_HeatingTimer, m_NoisePar, MATERIAL_FIREPLACE_GLOW, NoiseParams(), PARAM_BURN_WET_THRESHOLD, StopFire(), and TIMER_HEATING_UPDATE_INTERVAL.
Referenced by StartFire().
StopAllParticlesAndSounds()
protected void StopAllParticlesAndSounds ()
Definition at line 963 of file fireplacebase.c.
    {
        // go through all fireplace particles
        if ( m_ParticleFireStart )
            StopParticle( m_ParticleFireStart );
        if ( m_ParticleSmallFire )
            StopParticle( m_ParticleSmallFire );
        if ( m_ParticleNormalFire )
            StopParticle( m_ParticleNormalFire );
        if ( m_ParticleSmallSmoke )
            StopParticle( m_ParticleSmallSmoke );
        if ( m_ParticleNormalSmoke )
            StopParticle( m_ParticleNormalSmoke );
        if ( m_ParticleFireEnd )
            StopParticle( m_ParticleFireEnd );
        if ( m_ParticleSteamEnd )
            StopParticle( m_ParticleSteamEnd );
        if ( m_ParticleSteamExtinguishing )
            StopParticle( m_ParticleSteamExtinguishing );
        // go through all fireplace sounds
        if ( m_SoundFireLoop )
            StopSoundSet( m_SoundFireLoop );
        if ( m_SoundFire )
            StopSoundSet( m_SoundFire );
    }
References m_ParticleFireEnd, m_ParticleFireStart, m_ParticleNormalFire, m_ParticleNormalSmoke, m_ParticleSmallFire, m_ParticleSmallSmoke, m_ParticleSteamEnd, m_ParticleSteamExtinguishing, m_SoundFire, m_SoundFireLoop, StopParticle(), and StopSoundSet().
Referenced by EEDelete().
StopCooling()
protected void StopCooling ()
Definition at line 2117 of file fireplacebase.c.
    {
        //Debug
        //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        //if (player != NULL) {player.MessageAction ( "Stop cooling..." );}
        //Print("Stop cooling...");
        //stop all fire visuals
        SetFireState( FireplaceFireState.NO_FIRE );
        SetObjectMaterial( 0, MATERIAL_FIREPLACE_NOGLOW );
        //Stop cooling
        m_CoolingTimer.Stop();
        m_CoolingTimer = NULL;
        //destroy area damage
        DestroyAreaDamage();
        //remove cookware audio visuals
        if ( GetCookingEquipment() )
        {
            Bottle_Base cooking_pot = Bottle_Base.Cast( GetCookingEquipment() );
            if ( cooking_pot )
                cooking_pot.RemoveAudioVisualsOnClient();
        }
        if ( DirectCookingSlotsInUse() )
        {
            for ( int i = 0; i < DIRECT_COOKING_SLOT_COUNT; i++ )
            {
                if ( m_DirectCookingSlots[i] )
                {
                    Bottle_Base cookingpot = Bottle_Base.Cast( m_DirectCookingSlots[i] );
                    if ( cookingpot )
                        cookingpot.RemoveAudioVisualsOnClient();
                    FryingPan fryingpan = FryingPan.Cast( m_DirectCookingSlots[i] );
                    if ( fryingpan )
                        fryingpan.RemoveAudioVisualsOnClient();
                    Edible_Base itsfood = Edible_Base.Cast( m_DirectCookingSlots[i] );
                    if ( itsfood )
                        itsfood.MakeSoundsOnClient( false );
                }
            }
        }
    }
References DestroyAreaDamage(), DIRECT_COOKING_SLOT_COUNT, DirectCookingSlotsInUse(), GetCookingEquipment(), m_CoolingTimer, m_DirectCookingSlots, MATERIAL_FIREPLACE_NOGLOW, and SetFireState().
Referenced by Cooling().
StopFire()
void StopFire (FireplaceFireState fire_state = FireplaceFireState.END_FIRE)
Definition at line 1949 of file fireplacebase.c.
    {
        //Debug
        //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        //if (player != NULL) {player.MessageAction ( "Stop fire..." );}
        //Print("Stop fire...");
        //Stop heating
        StopHeating();
        //spend item
        SpendFireConsumable( 0 );
        //turn fire off
        SetBurningState( false );
        //start cooling
        StartCooling();
        //Refresh fire visual
        SetFireState( fire_state );
        //Update navmesh
        if ( !IsFireplaceIndoor() )
        {
            SetAffectPathgraph( false, false );
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( GetGame().UpdatePathgraphRegionByObject, 100, false, this );
        }
        Synchronize();
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), FireplaceBase::IsFireplaceIndoor(), SetAffectPathgraph(), SetBurningState(), SetFireState(), SpendFireConsumable(), StartCooling(), StopHeating(), and Synchronize().
Referenced by Heating(), OnDebugButtonPressServer(), and StartHeating().
StopHeating()
protected void StopHeating ()
Definition at line 1982 of file fireplacebase.c.
    {
        //Debug
        //PlayerBase player = ( PlayerBase ) GetGame().GetPlayer();
        //if (player != NULL) {player.MessageAction ( "Stop heating..." );}
        //Print("Stop heating...");
        //Stop heating
        if ( !m_HeatingTimer ) //Check in case we stop fire as it starts for feedback
            return;
        m_HeatingTimer.Stop();
        m_HeatingTimer = NULL;
    }
References m_HeatingTimer.
Referenced by StopFire().
StopParticle()
protected bool StopParticle (out Particle particle)
Definition at line 1054 of file fireplacebase.c.
    {
        if ( particle && GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            particle.Stop();
            particle = NULL;
            return true;
        }
        return false;
    }
References GetGame().
Synchronize()
void Synchronize ()
Definition at line 456 of file fireplacebase.c.
    {
        if ( GetGame() && GetGame().IsServer() )
        {
            SetSynchDirty();
            if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
            {
                //Refresh visuals (on server)
                GetGame().GetCallQueue( CALL_CATEGORY_GAMEPLAY ).Call( RefreshFireplaceVisuals );
            }
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), and RefreshFireplaceVisuals().
TransferHeatToNearPlayers()
protected void TransferHeatToNearPlayers ()
DEPRECATED.
Definition at line 2399 of file fireplacebase.c.
{}
~FireplaceBase()
protected void ~FireplaceBase ()
Definition at line 275 of file fireplacebase.c.
    {
        if (GetLightEntity())
        {
            GetLightEntity().FadeOut();
        }
    }
References GetLightEntity().
Variable Documentation
ANIMATION_ASHES
const string ANIMATION_ASHES = "Ashes"
Definition at line 170 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_BURNT_WOOD
const string ANIMATION_BURNT_WOOD = "BurntWood"
Definition at line 174 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals(), and SetBurntFirewood().
ANIMATION_CAULDRON_HANDLE
const string ANIMATION_CAULDRON_HANDLE = "handle1Rotate"
Definition at line 181 of file fireplacebase.c.
Referenced by FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
ANIMATION_COOKWARE_HANDLE
const string ANIMATION_COOKWARE_HANDLE = "handleRotate"
Definition at line 180 of file fireplacebase.c.
Referenced by FireplaceBase::EEItemAttached(), and FireplaceBase::EEItemDetached().
ANIMATION_INVENTORY
const string ANIMATION_INVENTORY = "Inventory"
Definition at line 179 of file fireplacebase.c.
ANIMATION_KINDLING
const string ANIMATION_KINDLING = "Kindling"
Definition at line 171 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_OVEN
const string ANIMATION_OVEN = "Oven"
Definition at line 178 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals(), and FireplaceBase::RefreshPhysics().
ANIMATION_STICKS
const string ANIMATION_STICKS = "Sticks"
Definition at line 172 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_STONE
const string ANIMATION_STONE = "Stone"
Definition at line 175 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_STONES
const string ANIMATION_STONES = "StonesCircle"
Definition at line 176 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
ANIMATION_TRIPOD
const string ANIMATION_TRIPOD = "Tripod"
Definition at line 177 of file fireplacebase.c.
Referenced by FireplaceBase::RefreshPhysics().
ANIMATION_WOOD
const string ANIMATION_WOOD = "Wood"
Definition at line 173 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals(), and SetBurntFirewood().
ATTACHMENT_BANDAGE
ATTACHMENT_BANDAGE = BandageDressing
Definition at line 194 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_BARK_BIRCH
ATTACHMENT_BARK_BIRCH = Bark_Birch
Definition at line 197 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_BARK_OAK
ATTACHMENT_BARK_OAK = Bark_Oak
Definition at line 196 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_BOOK
ATTACHMENT_BOOK = ItemBook
Definition at line 195 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_CAULDRON
ATTACHMENT_CAULDRON = Cauldron
Definition at line 207 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), and OnAttachmentRuined().
ATTACHMENT_COOKING_POT
ATTACHMENT_COOKING_POT = Pot
Definition at line 205 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), and OnAttachmentRuined().
ATTACHMENT_COOKINGSTAND
ATTACHMENT_COOKINGSTAND = CookingStand
Definition at line 203 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), and OnAttachmentRuined().
ATTACHMENT_FIREWOOD
ATTACHMENT_FIREWOOD = Firewood
Definition at line 191 of file fireplacebase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
ATTACHMENT_FRYING_PAN
ATTACHMENT_FRYING_PAN = FryingPan
Definition at line 206 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), CookOnDirectSlot(), EEItemAttached(), FireplaceBase::EEItemDetached(), and OnAttachmentRuined().
ATTACHMENT_GIFTWRAP
ATTACHMENT_GIFTWRAP = GiftWrapPaper
Definition at line 199 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_PAPER
ATTACHMENT_PAPER = Paper
Definition at line 198 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_PUNCHEDCARD
ATTACHMENT_PUNCHEDCARD = PunchedCard
Definition at line 200 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_RAGS
ATTACHMENT_RAGS = Rag
Definition at line 193 of file fireplacebase.c.
Referenced by FireplaceBase().
ATTACHMENT_STICKS
ATTACHMENT_STICKS = WoodenStick
Definition at line 190 of file fireplacebase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
ATTACHMENT_STONES
ATTACHMENT_STONES = Stone
Definition at line 204 of file fireplacebase.c.
Referenced by FireplaceBase::CanLoadAttachment(), FireplaceBase::CanReceiveAttachment(), FireplaceBase::CanReleaseAttachment(), GetAttachedStonesCount(), HasStones(), and RefreshFireplaceVisuals().
ATTACHMENT_TRIPOD
ATTACHMENT_TRIPOD = Tripod
Definition at line 202 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), FireplaceBase::CanLoadAttachment(), OnAttachmentRuined(), and FireplaceBase::RefreshPhysics().
DIRECT_COOKING_SLOT_COUNT
const int DIRECT_COOKING_SLOT_COUNT = 3
direct cooking slots
update interval duration of cooling process (seconds)
Definition at line 86 of file fireplacebase.c.
Referenced by Cooling(), DirectCookingSlotsInUse(), Heating(), and StopCooling().
DIRECT_COOKING_SPEED
const float DIRECT_COOKING_SPEED = 1.5
Definition at line 87 of file fireplacebase.c.
FUEL_BURN_RATE_DEFAULT
const float FUEL_BURN_RATE_DEFAULT = 1.0
Definition at line 74 of file fireplacebase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
FUEL_BURN_RATE_OVEN
const float FUEL_BURN_RATE_OVEN = 0.85
Definition at line 76 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
FUEL_BURN_RATE_STONES
const float FUEL_BURN_RATE_STONES = 0.92
Definition at line 75 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
IGNITE_WIND_THRESHOLD
const float IGNITE_WIND_THRESHOLD = 0.8
Definition at line 95 of file fireplacebase.c.
LIFETIME_FIREPLACE_STONE_CIRCLE
const int LIFETIME_FIREPLACE_STONE_CIRCLE = 172800
Definition at line 92 of file fireplacebase.c.
LIFETIME_FIREPLACE_STONE_OVEN
const int LIFETIME_FIREPLACE_STONE_OVEN = 604800
Definition at line 93 of file fireplacebase.c.
m_AreaDamage
protected ref AreaDamageManager m_AreaDamage
Definition at line 213 of file fireplacebase.c.
Referenced by CreateAreaDamage(), ItemBase::CreateDamageTrigger(), ItemBase::CreateElectrifiedDamageTrigger(), DestroyAreaDamage(), ItemBase::DestroyDamageTrigger(), and OnVariablesSynchronized().
m_CanNoise
private bool m_CanNoise = true
Definition at line 220 of file fireplacebase.c.
Referenced by Heating().
m_ClutterCutter
protected Object m_ClutterCutter
Definition at line 210 of file fireplacebase.c.
Referenced by FireplaceBase::AfterStoreLoad(), ItemBase::DestroyClutterCutter(), GardenBase::EEDelete(), GardenBase::OnPlacementComplete(), OnPlacementComplete(), TentBase::OnPlacementComplete(), GardenBase::OnStoreLoad(), and ItemBase::OnStoreLoad().
m_CookingEquipment
protected ItemBase m_CookingEquipment
Definition at line 106 of file fireplacebase.c.
Referenced by CookWithEquipment(), Cooling(), GetCookingEquipment(), Heating(), SetCookingEquipment(), and ItemBase::SetCookingEquipment().
m_CookingProcess
protected ref Cooking m_CookingProcess
determines how fast will the fuel item burn before spending (lower is better)
Definition at line 40 of file fireplacebase.c.
Referenced by ClearCookingEquipment(), ItemBase::ClearCookingEquipment(), CookOnDirectSlot(), CookWithEquipment(), ItemBase::CookWithEquipment(), GetCookingProcess(), ItemBase::OnSwitchOff(), and SmokeOnSmokingSlot().
m_CoolingTimer
protected ref Timer m_CoolingTimer
Definition at line 99 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), StartCooling(), StartFire(), and StopCooling().
m_DirectCookingSlots
protected ItemBase m_DirectCookingSlots[DIRECT_COOKING_SLOT_COUNT]
Definition at line 107 of file fireplacebase.c.
Referenced by Cooling(), DirectCookingSlotsInUse(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), Heating(), and StopCooling().
m_FireConsumables
protected ref map<ItemBase, ref FireConsumable> m_FireConsumables
Definition at line 149 of file fireplacebase.c.
Referenced by AddToFireConsumables(), CalcAndSetQuantity(), FireplaceBase(), GetFireConsumableByItem(), GetFuelCount(), GetKindlingCount(), Heating(), RemoveFromFireConsumables(), and SetItemToConsume().
m_FireConsumableTypes
protected ref map<typename, ref FireConsumableType> m_FireConsumableTypes static
Definition at line 148 of file fireplacebase.c.
Referenced by CalcAndSetTotalEnergy(), FireplaceBase(), GetFireConsumableTypeEnergy(), GetFuelCount(), GetKindlingCount(), IsFuel(), and IsKindling().
m_FireState
protected FireplaceFireState m_FireState = FireplaceFireState.NO_FIRE
Definition at line 31 of file fireplacebase.c.
Referenced by GetFireState(), and SetFireState().
m_FuelBurnRateMP
protected float m_FuelBurnRateMP = 1.0
determines how fast will the fireplace loose its temperature when cooling (lower is better)
Definition at line 37 of file fireplacebase.c.
Referenced by GetFuelBurnRateMP(), OnStoreLoad(), OnStoreSave(), and SetFuelBurnRateMP().
m_HalfExtents
protected vector m_HalfExtents
Definition at line 33 of file fireplacebase.c.
m_HasAshes
protected bool m_HasAshes = false
Definition at line 25 of file fireplacebase.c.
Referenced by HasAshes(), OnStoreLoad(), OnStoreSave(), and SetAshesState().
m_HasStoneCircle
protected bool m_HasStoneCircle = false
Definition at line 27 of file fireplacebase.c.
Referenced by HasStoneCircle(), FireplaceBase::OnStoreLoad(), FireplaceBase::OnStoreSave(), and SetStoneCircleState().
m_HeatingTimer
protected ref Timer m_HeatingTimer
Definition at line 98 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), StartCooling(), StartHeating(), and StopHeating().
m_IsBurning
enum FireplaceFireState m_IsBurning = false
Referenced by IsBurning(), OnStoreLoad(), OnStoreSave(), OnVariablesSynchronized(), and SetBurningState().
m_IsOven
protected bool m_IsOven = false
Definition at line 26 of file fireplacebase.c.
Referenced by IsOven(), FireplaceBase::OnStoreLoad(), FireplaceBase::OnStoreSave(), and SetOvenState().
m_ItemToConsume
protected ref FireConsumable m_ItemToConsume
Definition at line 109 of file fireplacebase.c.
Referenced by GetItemToConsume(), and SetItemToConsume().
m_LastFireState
protected FireplaceFireState m_LastFireState = FireplaceFireState.NO_FIRE
Definition at line 32 of file fireplacebase.c.
Referenced by RefreshFireParticlesAndSounds().
m_Light
protected FireplaceLight m_Light
Definition at line 102 of file fireplacebase.c.
m_LightDistance
protected float m_LightDistance = 2000
Definition at line 103 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and RefreshFireplaceVisuals().
m_NoIgnite
protected bool m_NoIgnite = false
Definition at line 29 of file fireplacebase.c.
Referenced by GetIgniteFailure(), and SetIgniteFailure().
m_NoisePar
ref NoiseParams m_NoisePar
Definition at line 219 of file fireplacebase.c.
m_OvenAttachmentsLockState
protected int m_OvenAttachmentsLockState = -1
Definition at line 30 of file fireplacebase.c.
Referenced by LockOvenAttachments(), and RefreshFireplaceVisuals().
m_ParticleFireEnd
protected Particle m_ParticleFireEnd
Definition at line 130 of file fireplacebase.c.
Referenced by ParticleFireEndStart(), ParticleFireEndStop(), ParticleFireWindyNoIgniteStart(), and StopAllParticlesAndSounds().
m_ParticleFireStart
protected Particle m_ParticleFireStart
Definition at line 125 of file fireplacebase.c.
Referenced by ParticleFireStartStart(), ParticleFireStartStop(), and StopAllParticlesAndSounds().
m_ParticleNormalFire
protected Particle m_ParticleNormalFire
Definition at line 127 of file fireplacebase.c.
Referenced by ParticleNormalFireStart(), ParticleNormalFireStop(), and StopAllParticlesAndSounds().
m_ParticleNormalSmoke
protected Particle m_ParticleNormalSmoke
Definition at line 129 of file fireplacebase.c.
Referenced by ParticleNormalSmokeStart(), FireplaceBase::ParticleNormalSmokeStart(), ParticleNormalSmokeStop(), and StopAllParticlesAndSounds().
m_ParticleSmallFire
protected Particle m_ParticleSmallFire
Definition at line 126 of file fireplacebase.c.
Referenced by ParticleSmallFireStart(), ParticleSmallFireStop(), and StopAllParticlesAndSounds().
m_ParticleSmallSmoke
protected Particle m_ParticleSmallSmoke
Definition at line 128 of file fireplacebase.c.
Referenced by ParticleSmallSmokeStart(), FireplaceBase::ParticleSmallSmokeStart(), ParticleSmallSmokeStop(), and StopAllParticlesAndSounds().
m_ParticleSteamEnd
protected Particle m_ParticleSteamEnd
Definition at line 131 of file fireplacebase.c.
Referenced by ParticleSteamEndStart(), ParticleSteamEndStop(), ParticleWetNoIgniteStart(), ParticleWetNoIgniteStop(), and StopAllParticlesAndSounds().
m_ParticleSteamExtinguishing
protected Particle m_ParticleSteamExtinguishing
Definition at line 132 of file fireplacebase.c.
Referenced by ParticleSteamExtinguishingStart(), ParticleSteamExtinguishingStop(), and StopAllParticlesAndSounds().
m_RoofAbove
protected bool m_RoofAbove = false
Definition at line 28 of file fireplacebase.c.
Referenced by FireplaceBase::Close(), FireplaceBase::CloseLoad(), FireplaceBase::FireplaceIndoor(), IsRoofAbove(), FireplaceBase::Open(), FireplaceBase::OpenLoad(), FireplaceBase::OvenIndoor(), SetOvenState(), and StartFire().
m_SmokingSlots
protected ItemBase m_SmokingSlots[SMOKING_SLOT_COUNT]
Definition at line 108 of file fireplacebase.c.
Referenced by Cooling(), FireplaceBase::EEItemAttached(), FireplaceBase::EEItemDetached(), Heating(), and SmokingSlotsInUse().
m_SoundFire
protected EffectSound m_SoundFire
Definition at line 143 of file fireplacebase.c.
Referenced by SoundFireExtinguishedStart(), SoundFireWetNoIgniteStart(), SoundFireWindyNoIgniteStart(), and StopAllParticlesAndSounds().
m_SoundFireLoop
protected EffectSound m_SoundFireLoop
Definition at line 142 of file fireplacebase.c.
Referenced by BuildingSuper::EEDelete(), BuildingSuper::EEInit(), SoundFireExtinguishingStart(), SoundFireHeavyStart(), SoundFireLightStart(), SoundFireNoFireStart(), SoundFireStop(), and StopAllParticlesAndSounds().
m_TemperatureLossMP
protected float m_TemperatureLossMP = 1.0
Definition at line 36 of file fireplacebase.c.
Referenced by GetTemperatureLossMP(), OnStoreLoad(), OnStoreSave(), and SetTemperatureLossMP().
m_TotalEnergy
protected float m_TotalEnergy
Definition at line 216 of file fireplacebase.c.
Referenced by CalcAndSetQuantity(), and CalcAndSetTotalEnergy().
m_UTSLFireplace
protected ref UniversalTemperatureSourceLambdaFireplace m_UTSLFireplace
Definition at line 225 of file fireplacebase.c.
Referenced by AddWetnessToFireplace(), Cooling(), EEInit(), and Heating().
m_UTSource
protected ref UniversalTemperatureSource m_UTSource
Definition at line 223 of file fireplacebase.c.
Referenced by Cooling(), BuildingSuper::EEDelete(), BuildingSuper::EEInit(), EEInit(), ItemBase::EEInit(), CarScript::EEInit(), CarScript::EOnPostSimulate(), CarScript::OnEngineStart(), CarScript::OnEngineStop(), ItemBase::OnSwitchOff(), ItemBase::OnSwitchOn(), ItemBase::OnWork(), ItemBase::OnWorkStart(), ItemBase::OnWorkStop(), and StartFire().
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings
Definition at line 224 of file fireplacebase.c.
Referenced by BuildingSuper::EEInit(), EEInit(), ItemBase::EEInit(), CarScript::EEInit(), CarScript::EOnPostSimulate(), and ItemBase::OnWork().
MATERIAL_FIREPLACE_GLOW
const string MATERIAL_FIREPLACE_GLOW = "dz\\gear\\cooking\\data\\stoneground.rvmat"
Definition at line 185 of file fireplacebase.c.
Referenced by StartHeating().
MATERIAL_FIREPLACE_NOGLOW
const string MATERIAL_FIREPLACE_NOGLOW = "dz\\gear\\cooking\\data\\stonegroundnoemit.rvmat"
Definition at line 186 of file fireplacebase.c.
Referenced by StopCooling().
MAX_TEMPERATURE_TO_DISMANTLE_OVEN
const int MAX_TEMPERATURE_TO_DISMANTLE_OVEN = 40
minimum amount of stones for oven
Definition at line 67 of file fireplacebase.c.
Referenced by CanDismantleOven().
MESSAGE_BURY_ASHES_FAILED_BURNING
const string MESSAGE_BURY_ASHES_FAILED_BURNING = "Cannot bury ashes, the fireplace is still burning."
Definition at line 164 of file fireplacebase.c.
MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY
const string MESSAGE_BURY_ASHES_FAILED_NOT_EMPTY = "Cannot bury ashes. There are sill items in it."
Definition at line 162 of file fireplacebase.c.
MESSAGE_BURY_ASHES_FAILED_SURFACE
const string MESSAGE_BURY_ASHES_FAILED_SURFACE = "Cannot bury ashes on hard surface."
Definition at line 163 of file fireplacebase.c.
MESSAGE_BURY_ASHES_FAILED_TOO_HOT
const string MESSAGE_BURY_ASHES_FAILED_TOO_HOT = "Cannot bury ashes, the fireplace is too hot."
Definition at line 165 of file fireplacebase.c.
MESSAGE_CANNOT_BUILD_OVEN
const string MESSAGE_CANNOT_BUILD_OVEN = "Cannot build oven."
Definition at line 166 of file fireplacebase.c.
MESSAGE_CANNOT_DISMANTLE_OVEN
const string MESSAGE_CANNOT_DISMANTLE_OVEN = "Cannot dismantle oven."
Definition at line 167 of file fireplacebase.c.
MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED
const string MESSAGE_IGNITE_IGNIT_ITEM_DAMAGED = "You cannot start fire. Fireplace is ruined."
Definition at line 152 of file fireplacebase.c.
MESSAGE_IGNITE_IN_WATER
const string MESSAGE_IGNITE_IN_WATER = "I cannot ignite the fireplace in the water."
Definition at line 157 of file fireplacebase.c.
MESSAGE_IGNITE_NO_KINDLING
const string MESSAGE_IGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
Definition at line 153 of file fireplacebase.c.
MESSAGE_IGNITE_RAIN
const string MESSAGE_IGNITE_RAIN = "The fire went out because of the rain."
Definition at line 155 of file fireplacebase.c.
MESSAGE_IGNITE_TOO_WET
const string MESSAGE_IGNITE_TOO_WET = "The fireplace is too wet to be ignited."
Definition at line 154 of file fireplacebase.c.
MESSAGE_IGNITE_UNDER_LOW_ROOF
const string MESSAGE_IGNITE_UNDER_LOW_ROOF = "I cannot ignite the fireplace here, the is not enough room."
Definition at line 158 of file fireplacebase.c.
MESSAGE_IGNITE_WIND
const string MESSAGE_IGNITE_WIND = "The fire went out because of the wind."
Definition at line 156 of file fireplacebase.c.
MESSAGE_REIGNITE_NO_KINDLING
const string MESSAGE_REIGNITE_NO_KINDLING = "There needs to be some kindling to start a fire."
Definition at line 159 of file fireplacebase.c.
MESSAGE_REIGNITE_RAIN
const string MESSAGE_REIGNITE_RAIN = "Cannot reignite fireplace in rain."
Definition at line 160 of file fireplacebase.c.
MESSAGE_REIGNITE_TOO_WET
const string MESSAGE_REIGNITE_TOO_WET = "The fireplace is too wet to be reignited."
Definition at line 161 of file fireplacebase.c.
MIN_CEILING_HEIGHT
const float MIN_CEILING_HEIGHT = 5
maximum temperature for dismantling oven
Definition at line 68 of file fireplacebase.c.
Referenced by GetCeilingHeight().
MIN_STONES_TO_BUILD_CIRCLE
const int MIN_STONES_TO_BUILD_CIRCLE = 8
maximum value for temperature that will be transfered to player (environment)
Definition at line 65 of file fireplacebase.c.
Referenced by CanBuildStoneCircle().
MIN_STONES_TO_BUILD_OVEN
const int MIN_STONES_TO_BUILD_OVEN = 16
minimum amount of stones for circle
Definition at line 66 of file fireplacebase.c.
Referenced by CanBuildOven().
OBJECT_CLUTTER_CUTTER
const string OBJECT_CLUTTER_CUTTER = "ClutterCutterFireplace"
Definition at line 209 of file fireplacebase.c.
Referenced by FireplaceBase::AfterStoreLoad(), FireplaceBase::OnIgnitedThis(), and OnPlacementComplete().
PARAM_BURN_DAMAGE_COEF
const float PARAM_BURN_DAMAGE_COEF = 5.0
base value of fire consumption rate (how many base energy will be spent on each update)
Definition at line 56 of file fireplacebase.c.
PARAM_BURN_WET_THRESHOLD
const float PARAM_BURN_WET_THRESHOLD = 0.40
maximum rain value when the fireplace can be ignited
Definition at line 51 of file fireplacebase.c.
Referenced by Heating(), and StartHeating().
PARAM_COOKING_EQUIP_MAX_TEMP
const float PARAM_COOKING_EQUIP_MAX_TEMP = 250
temperature threshold for starting coooking process (degree Celsius)
Definition at line 80 of file fireplacebase.c.
Referenced by CookOnDirectSlot(), Heating(), and ItemBase::OnWork().
PARAM_COOKING_EQUIP_TEMP_INCREASE
const float PARAM_COOKING_EQUIP_TEMP_INCREASE = 10
maximum temperature of attached cooking equipment (degree Celsius)
Definition at line 81 of file fireplacebase.c.
Referenced by CookOnDirectSlot(), Heating(), and ItemBase::OnWork().
PARAM_COOKING_TEMP_THRESHOLD
const float PARAM_COOKING_TEMP_THRESHOLD = 100
cooking
Definition at line 79 of file fireplacebase.c.
Referenced by CanCookOnStick(), Cooling(), Heating(), and ItemBase::OnWork().
PARAM_FIRE_CONSUM_RATE_AMOUNT
const float PARAM_FIRE_CONSUM_RATE_AMOUNT = 0.5
value for calculating wetness loss during cooling process
Definition at line 55 of file fireplacebase.c.
Referenced by Heating().
PARAM_FULL_HEAT_RADIUS
const float PARAM_FULL_HEAT_RADIUS = 2.0
maximum value of temperature of items in fireplace when heating (degree Celsius)
Definition at line 60 of file fireplacebase.c.
Referenced by EEInit().
PARAM_HEAT_RADIUS
const float PARAM_HEAT_RADIUS = 4.0
radius in which objects are fully heated by fire
Definition at line 61 of file fireplacebase.c.
Referenced by EEInit().
PARAM_HEAT_THROUGH_AIR_COEF
const float PARAM_HEAT_THROUGH_AIR_COEF = 0.1
radius in which objects are heated by fire
Definition at line 62 of file fireplacebase.c.
PARAM_IGNITE_RAIN_THRESHOLD
const float PARAM_IGNITE_RAIN_THRESHOLD = 0.1
minimum fireplace temperature under which the fireplace can be reignited using air only (degree Celsius)
Definition at line 50 of file fireplacebase.c.
PARAM_ITEM_HEAT_MIN_TEMP
const float PARAM_ITEM_HEAT_MIN_TEMP = 40
value for calculating temperature increase on each heat update interval (degree Celsius)
Definition at line 58 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), AddTemperatureToItemByFire(), CookOnDirectSlot(), and Heating().
PARAM_ITEM_HEAT_TEMP_INCREASE_COEF
const float PARAM_ITEM_HEAT_TEMP_INCREASE_COEF = 10
value for calculating damage on items located in fireplace cargo
Definition at line 57 of file fireplacebase.c.
Referenced by AddTemperatureToItemByFire().
PARAM_MAX_ITEM_HEAT_TEMP_INCREASE
const float PARAM_MAX_ITEM_HEAT_TEMP_INCREASE = 200
minimum temperature for items that can be heated in fireplace cargo or as attachments (degree Celsius)
Definition at line 59 of file fireplacebase.c.
Referenced by AddTemperatureToItemByFire().
PARAM_MAX_TRANSFERED_TEMPERATURE
const float PARAM_MAX_TRANSFERED_TEMPERATURE = 25
DEPRECATED value for calculation of heat transfered from fireplace through air to player (environment)
Definition at line 63 of file fireplacebase.c.
Referenced by EEInit().
PARAM_MAX_WET_TO_IGNITE
const float PARAM_MAX_WET_TO_IGNITE = 0.2
how much will temperature decrease when fireplace is cooling (degree Celsius)
Definition at line 48 of file fireplacebase.c.
PARAM_MIN_FIRE_TEMPERATURE
const float PARAM_MIN_FIRE_TEMPERATURE = 30
maximum fireplace temperature of a normal fire (degree Celsius)
Definition at line 45 of file fireplacebase.c.
Referenced by AddWetnessToFireplace(), and RefreshFireState().
PARAM_MIN_TEMP_TO_REIGNITE
const float PARAM_MIN_TEMP_TO_REIGNITE = 30
maximum wetness value when the fireplace can be ignited
Definition at line 49 of file fireplacebase.c.
PARAM_NORMAL_FIRE_TEMPERATURE
const float PARAM_NORMAL_FIRE_TEMPERATURE = 1000
maximum fireplace temperature of a small fire (degree Celsius)
Definition at line 44 of file fireplacebase.c.
Referenced by AddWetnessToFireplace(), and EEInit().
PARAM_SMALL_FIRE_TEMPERATURE
const float PARAM_SMALL_FIRE_TEMPERATURE = 150
Definition at line 43 of file fireplacebase.c.
Referenced by CookOnDirectSlot(), EEInit(), Heating(), and RefreshFireState().
PARAM_TEMPERATURE_DECREASE
const float PARAM_TEMPERATURE_DECREASE = 20
how much will temperature increase when fireplace is burning (degree Celsius)
Definition at line 47 of file fireplacebase.c.
Referenced by Cooling().
PARAM_TEMPERATURE_INCREASE
const float PARAM_TEMPERATURE_INCREASE = 9
minimum fireplace temperature under which the fireplace is inactive (degree Celsius)
Definition at line 46 of file fireplacebase.c.
Referenced by Heating().
PARAM_WET_COOLING_DECREASE_COEF
const float PARAM_WET_COOLING_DECREASE_COEF = 0.002
value for calculating wetness loss during heating process
Definition at line 54 of file fireplacebase.c.
Referenced by Cooling().
PARAM_WET_HEATING_DECREASE_COEF
const float PARAM_WET_HEATING_DECREASE_COEF = 0.01
value for calculating of wetness that fireplace gain when raining
Definition at line 53 of file fireplacebase.c.
Referenced by BurnItemsInFireplace(), and Heating().
PARAM_WET_INCREASE_COEF
const float PARAM_WET_INCREASE_COEF = 0.02
maximum wetness value when the fireplace is able to burn
Definition at line 52 of file fireplacebase.c.
Referenced by Cooling(), and Heating().
PARTICLE_FIRE_END
protected int PARTICLE_FIRE_END = ParticleList.CAMP_FIRE_END
Definition at line 119 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleFireEndStart().
PARTICLE_FIRE_START
protected int PARTICLE_FIRE_START = ParticleList.CAMP_FIRE_START
Definition at line 112 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleFireStartStart().
PARTICLE_NO_IGNITE_WIND
protected int PARTICLE_NO_IGNITE_WIND = ParticleList.CAMP_NO_IGNITE_WIND
Definition at line 123 of file fireplacebase.c.
Referenced by ParticleFireWindyNoIgniteStart().
PARTICLE_NORMAL_FIRE
protected int PARTICLE_NORMAL_FIRE = ParticleList.CAMP_NORMAL_FIRE
Definition at line 115 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleNormalFireStart().
PARTICLE_NORMAL_SMOKE
protected int PARTICLE_NORMAL_SMOKE = ParticleList.CAMP_NORMAL_SMOKE
Definition at line 118 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleNormalSmokeStart(), and FireplaceBase::ParticleNormalSmokeStart().
PARTICLE_OVEN_FIRE
protected int PARTICLE_OVEN_FIRE = ParticleList.CAMP_STOVE_FIRE
Definition at line 116 of file fireplacebase.c.
Referenced by ParticleNormalFireStart(), and ParticleSmallFireStart().
PARTICLE_OVEN_FIRE_END
protected int PARTICLE_OVEN_FIRE_END = ParticleList.CAMP_STOVE_FIRE_END
Definition at line 120 of file fireplacebase.c.
Referenced by ParticleFireEndStart(), and ParticleFireWindyNoIgniteStart().
PARTICLE_OVEN_FIRE_START
protected int PARTICLE_OVEN_FIRE_START = ParticleList.CAMP_STOVE_FIRE_START
Definition at line 113 of file fireplacebase.c.
Referenced by ParticleFireStartStart().
PARTICLE_SMALL_FIRE
protected int PARTICLE_SMALL_FIRE = ParticleList.CAMP_SMALL_FIRE
Definition at line 114 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), and ParticleSmallFireStart().
PARTICLE_SMALL_SMOKE
protected int PARTICLE_SMALL_SMOKE = ParticleList.CAMP_SMALL_SMOKE
Definition at line 117 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleSmallSmokeStart(), and FireplaceBase::ParticleSmallSmokeStart().
PARTICLE_STEAM_END
protected int PARTICLE_STEAM_END = ParticleList.CAMP_STEAM_2END
Definition at line 121 of file fireplacebase.c.
Referenced by FireplaceBase::BarrelHoles_ColorBase(), FireplaceBase::Fireplace(), FireplaceBase::FireplaceIndoor(), FireplaceBase::OvenIndoor(), ParticleSteamEndStart(), and ParticleWetNoIgniteStart().
PARTICLE_STEAM_EXTINGUISHING
protected int PARTICLE_STEAM_EXTINGUISHING = ParticleList.CAMP_STEAM_EXTINGUISH_START
Definition at line 122 of file fireplacebase.c.
Referenced by ParticleSteamExtinguishingStart().
SMOKING_SLOT_COUNT
const int SMOKING_SLOT_COUNT = 4
Definition at line 88 of file fireplacebase.c.
Referenced by Cooling(), Heating(), and SmokingSlotsInUse().
SMOKING_SPEED
const float SMOKING_SPEED = 1
Definition at line 89 of file fireplacebase.c.
SOUND_FIRE_EXTINGUISHED
const string SOUND_FIRE_EXTINGUISHED = "ExtinguishByWaterEnd_SoundSet"
Definition at line 139 of file fireplacebase.c.
Referenced by SoundFireExtinguishedStart(), and SoundFireWetNoIgniteStart().
SOUND_FIRE_EXTINGUISHING
const string SOUND_FIRE_EXTINGUISHING = "ExtinguishByWater_SoundSet"
Definition at line 138 of file fireplacebase.c.
Referenced by SoundFireExtinguishingStart().
SOUND_FIRE_HEAVY
const string SOUND_FIRE_HEAVY = "HeavyFire_SoundSet"
Definition at line 135 of file fireplacebase.c.
Referenced by SoundFireHeavyStart().
SOUND_FIRE_LIGHT
const string SOUND_FIRE_LIGHT = "LightFire_SoundSet"
Definition at line 136 of file fireplacebase.c.
Referenced by SoundFireLightStart().
SOUND_FIRE_NO_FIRE
const string SOUND_FIRE_NO_FIRE = "NoFuelFire_SoundSet"
Definition at line 137 of file fireplacebase.c.
Referenced by SoundFireNoFireStart().
TEMPERATURE_LOSS_MP_DEFAULT
const float TEMPERATURE_LOSS_MP_DEFAULT = 1.0
min height of ceiling for fire to be ignited
Definition at line 70 of file fireplacebase.c.
Referenced by FireplaceBase(), and RefreshFireplaceVisuals().
TEMPERATURE_LOSS_MP_OVEN
const float TEMPERATURE_LOSS_MP_OVEN = 0.75
Definition at line 72 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
TEMPERATURE_LOSS_MP_STONES
const float TEMPERATURE_LOSS_MP_STONES = 0.90
Definition at line 71 of file fireplacebase.c.
Referenced by RefreshFireplaceVisuals().
TIMER_COOLING_UPDATE_INTERVAL
const int TIMER_COOLING_UPDATE_INTERVAL = 2
update interval duration of heating process (seconds)
Definition at line 84 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), and StartCooling().
TIMER_HEATING_UPDATE_INTERVAL
const int TIMER_HEATING_UPDATE_INTERVAL = 3
how much will temperature increase when attached on burning fireplace (degree Celsius)
Definition at line 83 of file fireplacebase.c.
Referenced by AddDamageToItemByFireEx(), Heating(), and StartHeating().
WET
enum FireplaceFireState WET = 1
WIND
enum FireplaceFireState WIND = 0