DayzKode: P:/scripts/3_game/DayZ/gameplay.c File Reference
gameplay.c File Reference
Classes
class CursorIcons
class Entity
class GameOptions
class Hud
class ItemPreviewWidget
class JsonSerializer
Class for sending RPC over network.
class LOD
LOD class.
class MapWidget
class MeleeCombatData
class MenuData
class MenuDefaultCharacterData
class Mission
Mission class.
class ObjectTyped
class OptionsAccess
class OptionsAccessEvents
Invokers for ParticleManager events.
class PlayerIdentity
The class that will be instanced (moddable)
class PlayerIdentityBase
Player description (base engine class)
class PlayerPreviewWidget
class PrtTest
class RichTextWidget
class ScriptInputUserData
class ScriptJunctureData
class ScriptReadWriteContext
class ScriptRemoteInputUserData
class ScriptRPC
class Selection
Selection class.
class Static
Typedefs
typedef int ChatChannel
typedef Param1< int > ChatChannelEventParams
typedef Param4< int, string, string, string > ChatMessageEventParams
channel, from, text, color config class
typedef Param2< string, string > ClientConnectedEventParams
Name, uid.
typedef Param4< PlayerIdentity, Man, int, bool > ClientDisconnectedEventParams
PlayerIdentity, Man, LogoutTime, AuthFailed.
typedef Param3< PlayerIdentity, vector, Serializer > ClientNewEventParams
PlayerIdentity, PlayerPos, Top, Bottom, Shoe, Skin.
typedef Param2< PlayerIdentity, Man > ClientNewReadyEventParams
PlayerIdentity, Man.
typedef Param5< PlayerIdentity, bool, vector, float, int > ClientPrepareEventParams
PlayerIdentity, useDB, pos, yaw, preloadTimeout (= additional time in seconds to how long server waits for loginData)
typedef Param2< PlayerIdentity, Man > ClientReadyEventParams
PlayerIdentity, Man.
typedef Param2< PlayerIdentity, Man > ClientReconnectEventParams
PlayerIdentity, Man.
typedef Param2< PlayerIdentity, Man > ClientRespawnEventParams
PlayerIdentity, Man.
typedef Param1< string > DLCOwnerShipFailedParams
world name
typedef Param2< string, string > LoginStatusEventParams
text message for line 1, text message for line 2
typedef Param1< int > LoginTimeEventParams
LoginTime.
typedef Param1< Man > LogoutCancelEventParams
Player.
typedef Param1< int > LogoutEventParams
logoutTime
typedef Param2< int, string > MPConnectionCloseEventParams
EClientKicked, AdditionalInfo.
typedef Param1< int > MPConnectionLostEventParams
Duration.
typedef Link< Object > OLinkT
typedef Serializer ParamsReadContext
typedef Serializer ParamsWriteContext
typedef Param2< DayZPlayer, Object > PlayerDeathEventParams
Player, "Killer" (Beware: Not necessarily actually the killer, Client doesn't have this info)
typedef Param1< vector > PreloadEventParams
Position.
typedef Param3< int, float, string > ProgressEventParams
state, progress, title
typedef Param1< int > RespawnEventParams
RespawnTime.
typedef Param1< string > ScriptLogEventParams
typedef Param1< FreeDebugCamera > SetFreeCameraEventParams
Camera.
typedef Param1< int > SQFConsoleEventParams
typedef Param2< string, string > VONStartSpeakingEventParams
player name, player id
typedef Param2< bool, bool > VONStateEventParams
listening, toggled
typedef Param2< string, string > VONStopSpeakingEventParams
player name, player id
typedef Param3< int, int, bool > WindowsResizeEventParams
Width, Height, Windowed.
Enumerations
enum InventoryTraversalType { PREORDER , INORDER , POSTORDER , LEVELORDER }
tree traversal type, for more see http://en.wikipedia.org/wiki/Tree_traversal
enum OptionAccessType {
AT_UNKNOWN , AT_OBJECTS_DETAIL , AT_TEXTURE_DETAIL , AT_HDR_DETAIL ,
AT_FSAA_DETAIL , AT_VSYNC_VALUE , AT_ANISO_DETAIL , AT_OPTIONS_FXAA_VALUE ,
AT_OPTIONS_SW_VALUE , AT_POSTPROCESS_EFFECTS , AT_QUALITY_PREFERENCE , AT_ATOC_DETAIL ,
AT_AMBIENT_OCCLUSION , AT_BLOOM , AT_ROTATION_BLUR , AT_SHADOW_DETAIL ,
AT_OPTIONS_TERRAIN , AT_OPTIONS_RESOLUTION , AT_OPTIONS_GAMMA_SLIDER , AT_OPTIONS_BRIGHT_SLIDER ,
AT_OPTIONS_VISIBILITY_SLIDER , AT_OPTIONS_OBJECT_VISIBILITY_SLIDER , AT_OPTIONS_SHADOW_VISIBILITY_SLIDER , AT_OPTIONS_DRAWDISTANCE_SLIDER ,
AT_ASPECT_RATIO , AT_OPTIONS_FIELD_OF_VIEW , AT_OPTIONS_MUSIC_SLIDER , AT_OPTIONS_EFFECTS_SLIDER ,
AT_OPTIONS_VON_SLIDER , AT_OPTIONS_MASTER_VOLUME , AT_OPTIONS_HWACC , AT_OPTIONS_EAX ,
AT_OPTIONS_LANGUAGE , AT_OPTIONS_RADIO , AT_CONFIG_MOUSE_FILTERING , AT_CONFIG_HEAD_BOB ,
AT_OPTIONS_DISPLAY_MODE , AT_OPTIONS_TERRAIN_SHADER , AT_OPTIONS_AIM_HELPER , AT_OPTIONS_MOUSE_AND_KEYBOARD ,
AT_OPTIONS_PAUSE , AT_OPTIONS_FLIPMODE , AT_OPTIONS_VON_THRESHOLD_SLIDER , AT_OPTIONS_MOUSE_YAXIS_INVERTED ,
AT_OPTIONS_MOUSE_XAXIS , AT_OPTIONS_MOUSE_YAXIS , AT_OPTIONS_MOUSE_XAXIS_AIM_MOD , AT_OPTIONS_MOUSE_YAXIS_AIM_MOD ,
AT_OPTIONS_CONTROLLER_LS_XAXIS , AT_OPTIONS_CONTROLLER_LS_YAXIS , AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD , AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED ,
AT_OPTIONS_CONTROLLER_RS_XAXIS , AT_OPTIONS_CONTROLLER_RS_YAXIS , AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD , AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD ,
AT_OPTIONS_VON_INPUT_MODE
}
C++ OptionAccessType.
enum OptionIDsScript {
OPTION_HUD = 100 , OPTION_CROSSHAIR , OPTION_GAME_MESSAGES , OPTION_ADMIN_MESSAGES ,
OPTION_PLAYER_MESSAGES , OPTION_QUICKBAR , OPTION_SERVER_INFO , OPTION_BLEEDINGINDICATION
}
Used for script-based game options. For anything C++ based, you would most likely use "Option Access Type" below.
Functions
static array< int > GetAttachmentSlotsArray ()
Lists all customizable InventorySlots.
static int GetConfigArrayCountFromSlotID (int slot_ID)
How many 'default equip' types are listed in the corresponding array.
static array< string > GetConfigArrayNames ()
for conversion of slot ID to config array's string
static array< string > GetConfigAttachmentTypes (int slot_ID)
Lists all configured types (if any) for the appropriate attachment.
proto native float GetDefault ()
proto native CGame GetGame ()
proto native float GetMax ()
proto native float GetMin ()
static string GetPathFromSlotID (int slot_ID)
Returns config path of att. slot category, empty if undefined.
EntityAI SpawnEntity (string object_name, notnull InventoryLocation inv_loc, int iSetupFlags, int iRotation)
proto native void WriteValue (float value)
Variables
ref ScriptInvoker Event_OnRevert = new ScriptInvoker()
const int INDEX_NOT_FOUND = -1
class MenuDefaultCharacterData m_AttachmentSlots
static ref array< string > m_ConfigArrayNames
static const string m_Path = "cfgCharacterCreation"
class MeleeCombatData NullStringArray [1] = { "" }
class LOD Object
const int PROGRESS_FINISH = 1
const int PROGRESS_PROGRESS = 2
PlayerIdentity PROGRESS_START = 0
const int PROGRESS_UPDATE = 3
class ListOptionsAccess extends OptionsAccess ReadValue
Typedef Documentation
ChatChannel
typedef int ChatChannel
Definition at line 382 of file gameplay.c.
ChatChannelEventParams
typedef Param1<int> ChatChannelEventParams
Definition at line 390 of file gameplay.c.
ChatMessageEventParams
typedef Param4<int, string, string, string> ChatMessageEventParams
channel, from, text, color config class
Definition at line 389 of file gameplay.c.
ClientConnectedEventParams
typedef Param2<string, string> ClientConnectedEventParams
Name, uid.
Definition at line 394 of file gameplay.c.
ClientDisconnectedEventParams
typedef Param4<PlayerIdentity, Man, int, bool> ClientDisconnectedEventParams
PlayerIdentity, Man, LogoutTime, AuthFailed.
Definition at line 408 of file gameplay.c.
ClientNewEventParams
typedef Param3<PlayerIdentity, vector, Serializer> ClientNewEventParams
PlayerIdentity, PlayerPos, Top, Bottom, Shoe, Skin.
Definition at line 398 of file gameplay.c.
ClientNewReadyEventParams
typedef Param2<PlayerIdentity, Man> ClientNewReadyEventParams
PlayerIdentity, Man.
Definition at line 400 of file gameplay.c.
ClientPrepareEventParams
typedef Param5<PlayerIdentity, bool, vector, float, int> ClientPrepareEventParams
PlayerIdentity, useDB, pos, yaw, preloadTimeout (= additional time in seconds to how long server waits for loginData)
Definition at line 396 of file gameplay.c.
ClientReadyEventParams
typedef Param2<PlayerIdentity, Man> ClientReadyEventParams
PlayerIdentity, Man.
Definition at line 404 of file gameplay.c.
ClientReconnectEventParams
typedef Param2<PlayerIdentity, Man> ClientReconnectEventParams
PlayerIdentity, Man.
Definition at line 406 of file gameplay.c.
ClientRespawnEventParams
typedef Param2<PlayerIdentity, Man> ClientRespawnEventParams
PlayerIdentity, Man.
Definition at line 402 of file gameplay.c.
DLCOwnerShipFailedParams
typedef Param1<string> DLCOwnerShipFailedParams
world name
Definition at line 431 of file gameplay.c.
LoginStatusEventParams
typedef Param2<string, string> LoginStatusEventParams
text message for line 1, text message for line 2
Definition at line 419 of file gameplay.c.
LoginTimeEventParams
typedef Param1<int> LoginTimeEventParams
LoginTime.
Definition at line 411 of file gameplay.c.
LogoutCancelEventParams
typedef Param1<Man> LogoutCancelEventParams
Player.
Definition at line 417 of file gameplay.c.
LogoutEventParams
typedef Param1<int> LogoutEventParams
logoutTime
Definition at line 421 of file gameplay.c.
MPConnectionCloseEventParams
typedef Param2<int, string> MPConnectionCloseEventParams
EClientKicked, AdditionalInfo.
Definition at line 437 of file gameplay.c.
MPConnectionLostEventParams
typedef Param1<int> MPConnectionLostEventParams
Duration.
Definition at line 435 of file gameplay.c.
OLinkT
typedef Link<Object> OLinkT
Definition at line 1415 of file gameplay.c.
ParamsReadContext
typedef Serializer ParamsReadContext
Definition at line 15 of file gameplay.c.
ParamsWriteContext
typedef Serializer ParamsWriteContext
Definition at line 16 of file gameplay.c.
PlayerDeathEventParams
typedef Param2<DayZPlayer, Object> PlayerDeathEventParams
Player, "Killer" (Beware: Not necessarily actually the killer, Client doesn't have this info)
Definition at line 439 of file gameplay.c.
PreloadEventParams
typedef Param1<vector> PreloadEventParams
Position.
Definition at line 415 of file gameplay.c.
ProgressEventParams
typedef Param3<int, float, string> ProgressEventParams
state, progress, title
Definition at line 386 of file gameplay.c.
RespawnEventParams
typedef Param1<int> RespawnEventParams
RespawnTime.
Definition at line 413 of file gameplay.c.
ScriptLogEventParams
typedef Param1<string> ScriptLogEventParams
Definition at line 387 of file gameplay.c.
SetFreeCameraEventParams
typedef Param1<FreeDebugCamera> SetFreeCameraEventParams
Camera.
Definition at line 433 of file gameplay.c.
SQFConsoleEventParams
typedef Param1<int> SQFConsoleEventParams
Definition at line 391 of file gameplay.c.
VONStartSpeakingEventParams
typedef Param2<string, string> VONStartSpeakingEventParams
player name, player id
Definition at line 427 of file gameplay.c.
VONStateEventParams
typedef Param2<bool, bool> VONStateEventParams
listening, toggled
Definition at line 425 of file gameplay.c.
VONStopSpeakingEventParams
typedef Param2<string, string> VONStopSpeakingEventParams
player name, player id
Definition at line 429 of file gameplay.c.
WindowsResizeEventParams
typedef Param3<int, int, bool> WindowsResizeEventParams
Width, Height, Windowed.
Definition at line 423 of file gameplay.c.
Enumeration Type Documentation
InventoryTraversalType
enum InventoryTraversalType
tree traversal type, for more see http://en.wikipedia.org/wiki/Tree_traversal
Enumerator
PREORDER
INORDER
POSTORDER
LEVELORDER
Definition at line 5 of file gameplay.c.
{
    PREORDER,
    INORDER,
    POSTORDER,
    LEVELORDER
};
OptionAccessType
enum OptionAccessType
C++ OptionAccessType.
Enumerator
AT_UNKNOWN
AT_OBJECTS_DETAIL
AT_TEXTURE_DETAIL
AT_HDR_DETAIL
AT_FSAA_DETAIL
AT_VSYNC_VALUE
AT_ANISO_DETAIL
AT_OPTIONS_FXAA_VALUE
AT_OPTIONS_SW_VALUE
AT_POSTPROCESS_EFFECTS
AT_QUALITY_PREFERENCE
AT_ATOC_DETAIL
AT_AMBIENT_OCCLUSION
AT_BLOOM
AT_ROTATION_BLUR
AT_SHADOW_DETAIL
AT_OPTIONS_TERRAIN
AT_OPTIONS_RESOLUTION
AT_OPTIONS_GAMMA_SLIDER
AT_OPTIONS_BRIGHT_SLIDER
AT_OPTIONS_VISIBILITY_SLIDER
AT_OPTIONS_OBJECT_VISIBILITY_SLIDER
AT_OPTIONS_SHADOW_VISIBILITY_SLIDER
AT_OPTIONS_DRAWDISTANCE_SLIDER
AT_ASPECT_RATIO
AT_OPTIONS_FIELD_OF_VIEW
AT_OPTIONS_MUSIC_SLIDER
AT_OPTIONS_EFFECTS_SLIDER
AT_OPTIONS_VON_SLIDER
AT_OPTIONS_MASTER_VOLUME
AT_OPTIONS_HWACC
AT_OPTIONS_EAX
AT_OPTIONS_LANGUAGE
AT_OPTIONS_RADIO
AT_CONFIG_MOUSE_FILTERING
AT_CONFIG_HEAD_BOB
AT_OPTIONS_DISPLAY_MODE
AT_OPTIONS_TERRAIN_SHADER
AT_OPTIONS_AIM_HELPER
AT_OPTIONS_MOUSE_AND_KEYBOARD
AT_OPTIONS_PAUSE
AT_OPTIONS_FLIPMODE
AT_OPTIONS_VON_THRESHOLD_SLIDER
AT_OPTIONS_MOUSE_YAXIS_INVERTED
AT_OPTIONS_MOUSE_XAXIS
AT_OPTIONS_MOUSE_YAXIS
AT_OPTIONS_MOUSE_XAXIS_AIM_MOD
AT_OPTIONS_MOUSE_YAXIS_AIM_MOD
AT_OPTIONS_CONTROLLER_LS_XAXIS
AT_OPTIONS_CONTROLLER_LS_YAXIS
AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD
AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED
AT_OPTIONS_CONTROLLER_RS_XAXIS
AT_OPTIONS_CONTROLLER_RS_YAXIS
AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD
AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD
AT_OPTIONS_VON_INPUT_MODE
Definition at line 1141 of file gameplay.c.
{
    AT_UNKNOWN,
    AT_OBJECTS_DETAIL,
    AT_TEXTURE_DETAIL,
    AT_HDR_DETAIL,
    AT_FSAA_DETAIL,
    AT_VSYNC_VALUE,
    AT_ANISO_DETAIL,
    AT_OPTIONS_FXAA_VALUE,
    AT_OPTIONS_SW_VALUE,
    AT_POSTPROCESS_EFFECTS,
    AT_QUALITY_PREFERENCE,
    AT_ATOC_DETAIL,
    AT_AMBIENT_OCCLUSION,
    AT_BLOOM,
    AT_ROTATION_BLUR,
    AT_SHADOW_DETAIL,
    AT_OPTIONS_TERRAIN,
    AT_OPTIONS_RESOLUTION,
    AT_OPTIONS_GAMMA_SLIDER,
    AT_OPTIONS_BRIGHT_SLIDER,
    AT_OPTIONS_VISIBILITY_SLIDER,
    AT_OPTIONS_OBJECT_VISIBILITY_SLIDER,
    AT_OPTIONS_SHADOW_VISIBILITY_SLIDER,
    AT_OPTIONS_DRAWDISTANCE_SLIDER,
    AT_ASPECT_RATIO,
    AT_OPTIONS_FIELD_OF_VIEW,
    AT_OPTIONS_MUSIC_SLIDER,
    AT_OPTIONS_EFFECTS_SLIDER,
    AT_OPTIONS_VON_SLIDER,
    AT_OPTIONS_MASTER_VOLUME,
    AT_OPTIONS_HWACC,
    AT_OPTIONS_EAX,
    AT_OPTIONS_LANGUAGE,
    AT_OPTIONS_RADIO,
    AT_CONFIG_MOUSE_FILTERING,
    AT_CONFIG_HEAD_BOB,
    AT_OPTIONS_DISPLAY_MODE,
    AT_OPTIONS_TERRAIN_SHADER,
    AT_OPTIONS_AIM_HELPER,
    AT_OPTIONS_MOUSE_AND_KEYBOARD,
    AT_OPTIONS_PAUSE,
    AT_OPTIONS_FLIPMODE,
    AT_OPTIONS_VON_THRESHOLD_SLIDER,
    AT_OPTIONS_MOUSE_YAXIS_INVERTED,
    AT_OPTIONS_MOUSE_XAXIS,
    AT_OPTIONS_MOUSE_YAXIS,
    AT_OPTIONS_MOUSE_XAXIS_AIM_MOD,
    AT_OPTIONS_MOUSE_YAXIS_AIM_MOD,
    AT_OPTIONS_CONTROLLER_LS_XAXIS,
    AT_OPTIONS_CONTROLLER_LS_YAXIS,
    AT_OPTIONS_CONTROLLER_LS_XAXIS_VEHICLE_MOD,
    AT_OPTIONS_CONTROLLER_RS_YAXIS_INVERTED,
    AT_OPTIONS_CONTROLLER_RS_XAXIS,
    AT_OPTIONS_CONTROLLER_RS_YAXIS,
    AT_OPTIONS_CONTROLLER_RS_XAXIS_AIM_MOD,
    AT_OPTIONS_CONTROLLER_RS_YAXIS_AIM_MOD,
    AT_OPTIONS_VON_INPUT_MODE
};
OptionIDsScript
enum OptionIDsScript
Used for script-based game options. For anything C++ based, you would most likely use "Option Access Type" below.
Enumerator
OPTION_HUD
OPTION_CROSSHAIR
OPTION_GAME_MESSAGES
OPTION_ADMIN_MESSAGES
OPTION_PLAYER_MESSAGES
OPTION_QUICKBAR
OPTION_SERVER_INFO
OPTION_BLEEDINGINDICATION
Definition at line 1205 of file gameplay.c.
{
    OPTION_HUD = 100, //starts at 100 to avoid ID conflict with AT_
    OPTION_CROSSHAIR,
    OPTION_GAME_MESSAGES,
    OPTION_ADMIN_MESSAGES,
    OPTION_PLAYER_MESSAGES,
    OPTION_QUICKBAR,
    OPTION_SERVER_INFO,
    OPTION_BLEEDINGINDICATION
};
Function Documentation
GetAttachmentSlotsArray()
static array< int > GetAttachmentSlotsArray () static
Lists all customizable InventorySlots.
Definition at line 1128 of file gameplay.c.
    {
        return m_AttachmentSlots;
    }
References m_AttachmentSlots.
GetConfigArrayCountFromSlotID()
static int GetConfigArrayCountFromSlotID (int slot_ID) static
How many 'default equip' types are listed in the corresponding array.
Definition at line 1112 of file gameplay.c.
    {
        TStringArray types = new TStringArray;
        GetGame().ConfigGetTextArray(GetPathFromSlotID(slot_ID),types);
        return types.Count();
    }
References CGame::ConfigGetTextArray(), GetGame(), and GetPathFromSlotID().
GetConfigArrayNames()
static array< string > GetConfigArrayNames () static
for conversion of slot ID to config array's string
Definition at line 1134 of file gameplay.c.
    {
        return m_ConfigArrayNames;
    }
References m_ConfigArrayNames.
GetConfigAttachmentTypes()
static array< string > GetConfigAttachmentTypes (int slot_ID) static
Lists all configured types (if any) for the appropriate attachment.
Definition at line 1120 of file gameplay.c.
    {
        TStringArray types = new TStringArray;
        GetGame().ConfigGetTextArray(GetPathFromSlotID(slot_ID),types);
        return types;
    }
References CGame::ConfigGetTextArray(), GetGame(), and GetPathFromSlotID().
GetDefault()
proto native float GetDefault ()
GetGame()
proto native CGame GetGame ()
Referenced by MissionBase::AbortMission(), HandActionBase::Action(), ActionBuildPart::ActionCondition(), ActionCondition(), ActionBuryBody::ActionCondition(), ActionCreateGreenhouseGardenPlot::ActionCondition(), ActionDigGardenPlot::ActionCondition(), ActionDigInStash::ActionCondition(), ActionDigWorms::ActionCondition(), ActionEmptyBottleBase::ActionCondition(), ActionFillBottleBase::ActionCondition(), ActionMineBush::ActionCondition(), ActionMineBushByHand::ActionCondition(), ActionPackGift::ActionCondition(), ActionRepairCarChassis::ActionCondition(), ActionRepairCarEngine::ActionCondition(), ActionRepairCarPart::ActionCondition(), ActionSkinning::ActionCondition(), ActionTransferLiquid::ActionCondition(), ActionUnrestrainTarget::ActionCondition(), ActionWashHandsWater::ActionCondition(), ActionWorldCraft::ActionCondition(), ActionDeployHuntingTrap::ActionCondition(), ActionBuildShelter::ActionCondition(), ActionDetachFromTarget::ActionCondition(), ActionPullOutPlug::ActionCondition(), ActionTakeMaterialToHands::ActionCondition(), ActionInteractLoopBase::ActionCondition(), ActionAttachOnSelection::ActionCondition(), ActionWorldLiquidActionSwitch::ActionCondition(), FirearmActionMechanicManipulate::ActionCondition(), ActionRestrainTarget::ActionConditionContinue(), ActionDeployHuntingTrap::ActionConditionContinue(), ActionConditionContinue(), ActionContinuousBase::ActionContinuousBase(), Actions_DoCancel(), Actions_DoInternalCommand(), Actions_Start(), ActionManagerClient::ActionStart(), ScriptedWidgetEventHandler::ActionTargetsCursor(), SymptomBase::Activate(), Ammo_40mm_Smoke_ColorBase::Activate(), ShockDamageMdfr::ActivateCondition(), ActivateModifier(), Grenade_Base::ActivateRandomTime(), MissionBase::AddActiveInputRestriction(), ManBase::AddActiveNV(), AddAgent(), AddDefect(), ItemBase::AddDefect(), ScriptedWidgetEventHandler::AddElement(), AddInsider(), AddInventoryReservationEx(), ScriptedWidgetEventHandler::AddItem(), UIPopupScript::AddItemToClipboard(), UIScriptedMenu::AddItemToClipboard(), PluginBase::AddKeyframe(), AddModifier(), AddNoise(), NotificationUI::AddNotification(), NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), ClientData::AddPlayerBase(), PPEffects::AddPPMask(), AddQuickbarItem(), SceneObject::AddRotation(), array::AddSubgroup(), ScriptedWidgetEventHandler::AddSubgroup(), ScriptedWidgetEventHandler::AddTab(), AddTemperatureToItem(), HudDebugWinBase::AddValue(), VicinityItemManager::AddVicinityItems(), NotificationUI::AddVoiceNotification(), EntityAI::AdvancedCommunication(), AfterStoreLoad(), FireplaceBase::AfterStoreLoad(), Hologram::AlignProjectionOnTerrain(), AnimFinished(), UIScriptedMenu::Apply(), ScriptedWidgetEventHandler::Apply(), DayZCreature::AttenuateSoundIfNecessary(), AttenuateSoundIfNecessary(), SymptomManager::AutoactivateSymptoms(), Back(), UIScriptedMenu::Back(), ItemBase::BatteryCharger(), Barrel_ColorBase::BleachClothes(), BleedingSource(), Hit_MeatBones::BloodSplatGround(), BotSelectNearestTarget(), UIScriptedMenu::BottomChanged(), BuildCondition(), ScriptedWidgetEventHandler::BuildLayout(), SoundObjectBuilder::BuildSoundObject(), CalcAndSetQuantity(), CAContinuousEmpty::CalcAndSetQuantity(), CAContinuousEmptyMagazine::CalcAndSetQuantity(), CAContinuousFill::CalcAndSetQuantity(), CAContinuousFillBrakes::CalcAndSetQuantity(), CAContinuousFillCoolant::CalcAndSetQuantity(), CAContinuousFillFuel::CalcAndSetQuantity(), CAContinuousFillOil::CalcAndSetQuantity(), CAContinuousFillPowerGenerator::CalcAndSetQuantity(), CAContinuousQuantity::CalcAndSetQuantity(), CAContinuousQuantityBloodTransfer::CalcAndSetQuantity(), CAContinuousQuantityEdible::CalcAndSetQuantity(), CAContinuousQuantityExtinguish::CalcAndSetQuantity(), CAContinuousQuantityLiquidTransfer::CalcAndSetQuantity(), CAContinuousQuantityRepeat::CalcAndSetQuantity(), CAContinuousTransferQuantity::CalcAndSetQuantity(), CASingleUseQuantity::CalcAndSetQuantity(), CASingleUseQuantityEdible::CalcAndSetQuantity(), CalcAndSetTotalEnergy(), HitDirectionEffectBase::CalculateArrowPosition(), CalculateEyeAccoTarget(), PluginBase::CalculatePos(), BroomBase::CalculateQuantity(), FlammableBase::CalculateQuantity(), ActionTargets::CalculateRayStart(), CallQueueContext::CallParams(), CameraShake::CameraShake(), UIScriptedMenu::CameraToolsMenu(), CCTCursorNoObject::Can(), CCTSurface::Can(), CCTTree::Can(), InventoryGridController::CanAddItemInHandToInventory(), Inventory_Base::CanBeFilledAtPosition(), GardenBase::CanBePlaced(), UIScriptedMenu::Cancel(), HumanCommandActionCallback::CancelCondition(), Attachments::CanCombine(), Container::CanCombine(), AttachmentCategoriesRow::CanCombine(), PlayerContainer::CanCombine(), VicinitySlotsContainer::CanCombine(), Attachments::CanCombineAmmo(), Container::CanCombineAmmo(), VicinitySlotsContainer::CanCombineAmmo(), BaseBuildingBase::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), WeaponManager::CanEjectBulletVerified(), Attachments::CanEquip(), Container::CanEquip(), HandsContainer::CanEquip(), VicinitySlotsContainer::CanEquip(), FireplaceBase::CanPlaceFireplaceInSelectedSpot(), BaseBuildingBase::CanReceiveAttachment(), Container_Base::CanReceiveItemIntoCargo(), UIScriptedMenu::CanStoreBeOpened(), BroomBase::CanTransformIntoStick(), FlammableBase::CanTransformIntoStick(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ComponentEnergyManager::CanWork(), PluginBase::CaptureFocus(), CaptureFocus(), CarPartsHealthCheck(), FlareSimulation::CastFlareAINoise(), UIScriptedMenu::ChangeAccount(), ChangeFakePlaytime(), UIScriptedMenu::ChangeFilter(), UIScriptedMenu::CharacterCreationMenu(), ChatLine::ChatLine(), CheckAllowUpdate(), CheckAmmoCompability(), BaseBuildingBase::CheckFenceClosed(), BaseBuildingBase::CheckFenceOpened(), ManBase::CheckForGag(), ItemBase::CheckForHybridAttachments(), UIScriptedMenu::CheckForLightsAndNVG(), SlotsIcon::CheckHasItemSize(), RecipeBase::CheckIngredientMatch(), Icon::CheckIsWeapon(), PMTPlayback::CheckOnePlayingSA(), WeaponParticlesBase::CheckParticleOverride(), Hologram::CheckPowerSource(), ItemBase::CheckRainTick(), SymptomBase::CheckSoundFinished(), PMTPlayback::CheckStop(), ShockHandler::CheckValue(), ItemBase::CheckWater(), House::ChristmasTree(), SEffectManager::Cleanup(), CleanUpOnClosedClient(), ManBase::ClearInventory(), PluginBase::ClearInventory(), ClearInventoryReservationEx(), HumanInventory::ClearUserReservedLocationAtIndexSynced(), HumanInventory::ClearUserReservedLocationSynced(), BaseBuildingBase::CloseFence(), ManBase::CloseInventoryMenu(), ManBase::CloseMapEx(), UIScriptedMenu::CloseMapMenu(), UIScriptedMenu::CloseMenu(), UIScriptedWindow::CloseWindow(), UIManager::CloseWindow(), UIScriptedMenu::ColorRunButton(), Barrel_ColorBase::ColourClothes(), Barrel_ColorBase::ColourLeatherClothes(), Attachments::Combine(), Container::Combine(), AttachmentCategoriesRow::Combine(), PlayerContainer::Combine(), VicinitySlotsContainer::Combine(), Icon::Combine(), InventoryItem::CombineItemsClient(), PluginDayzPlayerDebug_Ctrl::CommandHandler(), PluginDayzPlayerDebug_Weapons::CommandHandler(), CommandHandler(), ManBase::CommandHandler(), CommandHandlerDebug(), CommitSuicide(), ServerBrowserTab::Construct(), ConstructionActionData::ConstructionActionData(), ContactEvent(), FireplaceBase::ContactEvent(), PluginBase::ContainsFirstClass(), MissionBase::Continue(), ScriptedWidgetEventHandler::ContinuousActionProgress(), MissionBase::ControlPersonalLight(), InventoryItem::ConvertEnergyToQuantity(), Cooling(), UnboxLambda::CopyOldPropertiesToNew(), DropEquipAndDestroyRootLambda::CopyOldPropertiesToNew(), ItemBase::CreateAreaDamage(), AttachmentsOutOfReach::CreateAttachmentPosition(), CreateBleedingEffect(), CreateCarDestroyedEffect(), MissionBase::CreateCharacter(), CreateCollisionTrigger(), ItemBase::CreateConstructionKit(), UIScriptedMenu::CreateContent(), ManBase::CreateCopyOfItemInInventory(), CreateDamageTriggerEx(), Managed::CreateDefaultCharacter(), ScriptedWidgetEventHandler::CreateFollowedObject(), UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::CreateGroupContainer(), Particle::CreateInWorld(), CreateItemBasePiles(), Chemlight_ColorBase::CreateLight(), EntityLightSource::CreateLight(), MissionBase::CreateLogoutMenu(), CreateMagazinePiles(), CreateMagazinePilesFromBullet(), PPEClassBase::CreateMaterial(), PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), CreateNetworkObjectInfo(), Managed::CreateNewCharacter(), Managed::CreateNewCharacterByName(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ReplaceAndDestroyLambdaEx::CreateNewEntity(), ActionSkinning::CreateOrgan(), Particle::CreateParticleEffect(), ParticleSource::CreateParticleEx(), PlayerBase::CreatePersonalLight(), ItemBase::CreatePlant(), SyncPlayerList::CreatePlayerList(), CAContinuousMineWood::CreatePrimaryItems(), DayZIntroSceneXbox::CreateRandomCharacter(), PlayerStatBase::CreateRecord(), ItemBase::CreateRope(), CAContinuousMineWood::CreateSecondaryItems(), CreateTitleScreen(), CreateTrigger(), EffectArea::CreateTrigger(), Weapon::CreateWeaponWithAmmo(), Icon::CreateWhiteBackground(), PluginBase::CreateWidgetOverlay(), EffectAreaLoader::CreateZones(), CreditsElement::CreditsDepartmentElement(), CreditsDepartmentSection(), CrossHairSelector(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTEvent(), ScriptedWidgetEventHandler::CTKeyframe(), PluginBase::CursorHide(), PluginBase::CursorShow(), DamageHands(), DayZIntroScene::DayZIntroScene(), DayZIntroSceneXbox::DayZIntroSceneXbox(), DayZPlayerImplement(), DayZPlayerTypeRegisterItems(), DayZPlayerTypeRegisterSounds(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTableImpl(), SymptomBase::Deactivate(), DeactivateModifier(), ShockHandler::DealShock(), ManBase::DealShock(), PluginDayzPlayerDebug_OtherCmds::Death_Start(), VicinityItemManager::DebugActorsSphereDraw(), Component::DebugBBoxDelete(), Component::DebugBBoxDraw(), VicinityItemManager::DebugConeDraw(), Component::DebugDirectionDelete(), Component::DebugDirectionDraw(), Transport::DebugFreeAreaAtDoor(), EntityAI::DebugFreeAreaAtDoor(), DebugGrowAgentsRequest(), DebugMonitor::DebugMonitor(), VicinityItemManager::DebugObjectsSphereDraw(), DebugRemoveAgentsRequest(), SymptomManager::DebugRequestActivateSymptom(), SymptomManager::DebugRequestExitSymptom(), ComponentEnergyManager::DebugUpdate(), DecreaseCookedItemQuantity(), DecreaseHealth(), Delete(), PluginBase::DeleteKeyframe(), EntityLightSource::DeleteLightNow(), EntityLightSource::DeleteLightWithDelay(), ReplaceItemWithNewLambdaBase::DeleteOldEntity(), PluginBase::DeleteSceneObject(), DeleteTrigger(), ItemManager::DeserializeDefaultHeaderOpenStates(), ItemManager::DeserializeDefaultOpenStates(), Destroy(), ItemBase::DestroyAreaDamage(), ItemBase::DestroyClutterCutter(), FireplaceBase::DestroyClutterCutter(), DestroyCollisionTrigger(), ActionDestroyPart::DestroyCondition(), ItemBase::DestroyConstruction(), ItemBase::DestroyConstructionKit(), DestroyDamageTriggerEx(), ItemBase::DestroyFireplace(), ScriptedWidgetEventHandler::DestroyFollowedObject(), DestroyLock(), DestroyMaterialsServer(), Particle::DestroyParticleEffect(), ItemBase::DestroyPlant(), DestroySmokeGrenade(), Icon::DestroyWhiteBackground(), ComponentEnergyManager::DeviceUpdate(), DeveloperFreeCamera::DisableFreeCamera(), Disarm(), KitBase::DisassembleKit(), DisconnectSessionScript(), ActionDismantlePart::DismantleCondition(), WeaponDebug::DisplayGeneralInfo(), MissionBase::DisplayHairDebug(), Hud::DisplayPresence(), Hud::DisplayStance(), PluginBase::DisplayTendency(), RecipeBase::Do(), InventoryItem::DoAmmoExplosion(), DoEverything(), PoweredOptic_Base::DoMeasurement(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), ClosableContainer::DraggingOver(), DraggingOverCenterPanel(), Icon::DraggingOverCombine(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), ClosableContainer::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), Icon::DraggingOverSwap(), UIScriptedMenu::DrawItems(), WeaponDebug::DrawLineOfFireCameraHybrid(), WeaponDebug::DrawLineOfFireMuzzleToHit(), ScriptedWidgetEventHandler::DropdownPrefab(), ActionRepackTentCB::DropDuringRepacking(), DropNonUsableMaterialsServer(), ClosableContainer::DropReceived(), HandsContainer::DropReceived(), AttachmentCategoriesRow::DropReceived(), Icon::DropReceivedFromMain(), UniversalTemperatureSourceLambdaBase::DryItemsInVicinity(), MissionBaseWorld::DumpCurrentUILayout(), DynamicArea_Flare::DynamicArea_Flare(), PluginBase::EditorToggle(), PluginBase::EditorUpdate(), EffectArea::EEDelete(), House::EEDelete(), BuildingSuper::EEDelete(), CrashBase::EEDelete(), GardenBase::EEDelete(), ItemBase::EEDelete(), Roadflare::EEDelete(), FlammableBase::EEDelete(), EEDelete(), Weapon::EEFired(), ImprovisedExplosive::EEHealthLevelChanged(), Plastic_Explosive::EEHealthLevelChanged(), Weapon_Base::EEHealthLevelChanged(), InventoryItem::EEHealthLevelChanged(), ItemBase::EEHealthLevelChanged(), MaskBase::EEHealthLevelChanged(), GasMask_Filter::EEHealthLevelChanged(), Clothing_Base::EEHealthLevelChanged(), Container_Base::EEHealthLevelChanged(), TrapBase::EEHealthLevelChanged(), ManBase::EEHealthLevelChanged(), ManBase::EEHitBy(), EEHitBy(), ContaminatedArea_Static::EEInit(), ContaminatedArea_Dynamic::EEInit(), ContaminatedArea_Local::EEInit(), SpookyArea::EEInit(), House::EEInit(), BuildingSuper::EEInit(), Weapon::EEInit(), ItemBase::EEInit(), EEInit(), FlammableBase::EEInit(), CarScript::EEInit(), ItemBase::EEItemAttached(), FireplaceBase::EEItemAttached(), EEItemAttached(), ManBase::EEItemAttached(), ItemBase::EEItemDetached(), FireplaceBase::EEItemDetached(), FlammableBase::EEItemDetached(), EEItemDetached(), ManBase::EEItemDetached(), InventoryItem::EEItemLocationChanged(), ClothingBase::EEItemLocationChanged(), ItemBase::EEItemLocationChanged(), ManBase::EEItemOutOfHands(), InventoryItemSuper::EEKilled(), Plastic_Explosive::EEKilled(), Ammo_40mm_Explosive::EEKilled(), Ammo_40mm_Smoke_ColorBase::EEKilled(), ManBase::EEKilled(), ItemBase::EEOnAfterLoad(), ContaminatedArea_Dynamic::EEOnCECreate(), Effect(), ejectBulletAndStoreInMagazine(), WeaponManager::EjectBulletVerified(), HandsContainer::ElectricityIcon(), EmoteManager(), Inventory_Base::EmptySeedPack(), DeveloperFreeCamera::EnableFreeCamera(), End(), AnimatedActionBase::End(), LoadingScreen::EndLoading(), TriggerEvents::Enter(), OnlineServices::EnterGameplaySession(), ActionViewBinoculars::EnterOptics(), DayZCreatureAI::EOnContact(), DayZInfected::EOnContact(), EOnContact(), Grenade_ChemGas::EOnContact(), InventoryItem::EOnContact(), EOnFrame(), DayZSpectator::EOnFrame(), EntityLightSource::EOnFrame(), DayZInfected::EOnInit(), ItemBase::EOnInit(), EntityLightSource::EOnInit(), ManBase::EOnPostFrame(), EOnPostSimulate(), CarScript::EOnPostSimulate(), Attachments::EquipItem(), Container::EquipItem(), HandsContainer::EquipItem(), PlayerContainer::EquipItem(), VicinitySlotsContainer::EquipItem(), ZombieContainer::EquipItem(), ItemManager::EvaluateContainerDragabilityDefault(), DayZInfected::EvaluateDamageHitAnimation(), EvaluateDamageHitAnimation(), DayZInfected::EvaluateDeathAnimation(), EvaluateDeathAnimation(), EffBulletImpactBase::EvaluateEffect(), EvaluateFinisherAttack(), ActionFishingNew::EvaluateFishingResult(), EvaluateHit_Common(), ComponentEnergyManager::Event_OnAwake(), Event_OnClick(), PluginBase::Event_OnClick(), PluginBase::Event_OnClickMiddle(), PluginBase::Event_OnDoubleClick(), PluginBase::Event_OnDrag(), AnalyticsManagerClient::Event_OnEntityKilled(), ComponentEnergyManager::Event_OnInit(), SyncEvents::Event_OnRPC(), EffBulletImpactBase::Event_OnStarted(), VicinityItemManager::ExcludeFromContainer_Phase1(), VicinityItemManager::ExcludeFromContainer_Phase2(), VicinityItemManager::ExcludeFromContainer_Phase3(), CAContinuousFertilizeGardenSlot::Execute(), CAContinuousFish::Execute(), CAContinuousMineWood::Execute(), CAContinuousTimeCooking::Execute(), CAContinuousWringClothes::Execute(), ReplaceItemWithNewLambdaBase::Execute(), PluginBase::ExecuteEnforceScript(), UIScriptedMenu::ExecuteSelectedItem(), UIScriptedMenu::Exit(), ActionViewBinoculars::ExitOptics(), Explode(), ExplosionEffects(), ExtendInventoryReservationEx(), ItemBase::Fertilize(), DayZInfected::FightLogic(), Inventory_Base::Fill(), ManBase::FindCargoByBaseType(), ActionManagerClient::FindContextualUserActions(), FirearmEffects(), Icon::FlagAction(), Inventory_Base::Fold(), ItemBase::Fold(), PluginBase::FreeCameraControlDisable(), PluginBase::FreeCameraControlEnable(), ItemBase::FullyBuild(), GamepadCheck(), GameplayEffectWidgets_base::GameplayEffectWidgets(), UIScriptedMenu::GameRespawn(), UIScriptedMenu::GameRetry(), ItemBase::GardenBase(), PluginBase::GatherPlayerInfo(), Environment::GatherTemperatureSources(), PluginBase::GatherTemperatureSources(), GenerateAINoiseAtPosition(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), PluginRecipesManagerBase::GenerateRecipeCache(), GestureMenuItem(), UIScriptedMenu::GesturesMenu(), ManBase::GetAimPosition(), GetAlarmInMin(), AmmoEffects::GetAmmoEffectTypename(), AmmoEffects::GetAmmoParticleID(), AttachmentCategoriesContainer::GetAttachmentCategoriesCount(), AttachmentCategoriesContainer::GetAttachmentCategory(), AttachmentCategoriesSlotsContainer::GetAttachmentCategory(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), ItemBase::GetAttachmentSlots(), PluginBase::GetBaseClassPath(), PluginBase::GetBaseClassPathRecursive(), ManBase::GetBleedingSourceCount(), GetBoundButtonText(), Managed::GetCharacterName(), Managed::GetCharacterNameById(), OnlineServices::GetClientServices(), GetCollisionBoxData(), HandsContainer::GetCombinationFlags(), ItemManager::GetCombinationFlags(), GetComponentNamesFromDamageZone(), PluginBase::GetConfig(), GetConfigArrayCountFromSlotID(), SceneObject::GetConfigAttachments(), GetConfigAttachmentTypes(), PluginBase::GetConfigRecursive(), UIScriptedMenu::GetControlMappingInfo(), HitDirectionImagesBase::GetCurrentImageData(), SymptomManager::GetCurrentPrimaryActiveSymptom(), ComponentEnergyManager::GetCurrentUpdateTime(), GetDamageZoneMap(), UndergroundAreaLoader::GetData(), AlarmClock_ColorBase::GetDebugText(), KitchenTimer::GetDebugText(), ItemManager::GetDefaultOpenStateHands(), Hologram::GetDefaultOrientation(), GetDisplayName(), GetEmptyingEndSoundset(), GetEmptyingLoopSoundset(), ComponentEnergyManager::GetEnergyMax(), ItemBase::GetEnergyNeededToCharge(), Debug::GetFiltredConfigClasses(), ItemBase::GetFoodAgents(), ItemBase::GetFoodDigestibility(), ItemBase::GetFoodEnergy(), ItemBase::GetFoodNutritionalIndex(), ItemBase::GetFoodTotalVolume(), ItemBase::GetFoodToxicity(), ItemBase::GetFoodWater(), GetHealthLevelForAmmo(), HiddenSelectionsData::GetHiddenSelectionsConfig(), HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig(), HiddenSelectionsData::GetHiddenSelectionsTexturesConfig(), ScriptedWidgetEventHandler::GetHud(), AttachmentCategoriesContainer::GetIconName(), AttachmentCategoriesSlotsContainer::GetIconName(), InputUtils::GetImagesetAndIconFromInputAction(), EntityAI::GetImpactSurfaceType(), GetInstance(), ColorManager::GetItemColor(), GetItemDisplayName(), UIScriptedMenu::GetItems(), Attachments::GetItemSlots(), Liquid::GetLiquidConfigProperty(), GetMaterialType(), GetMeleeTargetEx(), CGame::GetMenuDefaultCharacterData(), MenuData::GetMenuDefaultCharacterDataInstance(), GetModelName(), CGame::GetModelName(), GetMouseDistance(), UIScriptedMenu::GetMouseLookDir(), GetMousePointerAngle(), PluginBase::GetMousePositionInScene(), ScriptedWidgetEventHandler::GetOnScreenPosition(), Surface::GetParamFloat(), GetParent(), PluginBase::GetPlantType(), ScriptedWidgetEventHandler::GetPlayer(), GetPlayer(), ManBase::GetPlayerClass(), GetPlugin(), GetProfileValueBool(), Hologram::GetProjectionEntityPosition(), InventoryItem::GetProtectionLevel(), InventoryGridController::GetQuickbarItemColor(), Attachments::GetRecipeCount(), HandsContainer::GetRecipeCount(), PlayerContainer::GetRecipeCount(), ItemManager::GetRecipeCount(), GetRequiredParts(), DayZIntroScene::GetSelectedUserName(), GetSelectionPositionLS(), GetSelectionPositionMS(), GetSelectionPositionOld(), GetSelectionPositionWS(), GetSurfaceNoise(), CGame::GetSurfaceOrientation(), GetSurfaceType(), ActionDismantlePart::GetText(), ActionRepairPart::GetText(), ActionTransferLiquid::GetText(), ActionWorldCraft::GetText(), ActionBuildShelter::GetText(), ItemBase::GetTimeNeededToCharge(), GetType(), GetTypeMaxGlobalHealth(), AttachmentCategoriesContainer::GetViewIndex(), WeaponDebug::GetWeaponInHands(), ItemBase::GrowthTimerTick(), HandGuardBase::GuardCondition(), GUIAction_ActivateCommand(), GUIAction_EnableAI(), GUIAction_InitDebugObject(), GUIAction_ReleaseDebugObject(), GUIAction_SetValue(), HandleDamageHit(), HandleDeath(), HandleEngineSound(), HandleError(), DayZPlayerImplementFallDamage::HandleFallDamage(), HandleFishingResultFailure(), HandleFishingResultSuccess(), HandleForceSwapEntities(), HandleInput(), HandleInputData(), UIScriptedMenu::HandleLights(), MissionBase::HandleMapToggleByKeyboardShortcut(), UIScriptedMenu::HandleNVG(), HandleOptic(), BaseBuildingBase::HandleRefreshers(), PluginBase::HandleSetTime(), HandleSoundEffectsPipeCreaking(), DayZPlayerUtils::HandleStoreCartridge(), HandleSwapEntities(), HandleTakeToDst(), HandleView(), HandleWeapons(), HandsContainer::HandsContainer(), HandsPreview::HandsPreview(), ItemBase::Harvest(), HasAnimation(), HasConflictPart(), InventoryItem::HasFoodStage(), HasMaterials(), HasRequiredPart(), Heating(), HiddenSelectionsData::HiddenSelectionsData(), ItemBase::HideAllAnimationsAndProxyPhysics(), MissionBase::HideInventory(), Weapon::HideWeaponBarrel(), Hologram::HideWhenClose(), PluginDayzPlayerDebug_OtherCmds::Hit_Start(), HitZoneSelection(), HitZoneSelectionRaycast(), Hologram::Hologram(), UIScriptedMenu::HudShow(), FireplaceBase::IgniteEntityAsFireplace(), UIScriptedMenu::InGameMenuXbox(), InheritsFrom(), UIScriptedMenu::Init(), MenuDefaultCharacterData::Init(), PPEffects::Init(), Init(), BleedingSourcesManagerBase::Init(), BleedingCheckMdfr::Init(), DayZInfected::Init(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), FlammableBase::Init(), ManBase::Init(), PluginBase::Init(), PluginManager::Init(), SoundSetMap::Init(), UIScriptedWindow::Init(), CABase::Init(), HumanCommandActionCallback::Init(), ItemBase::Init(), AttachmentCategoriesRow::Init(), SceneObject::Init(), ScriptedWidgetEventHandler::Init(), InventoryItemSuper::Init2DPreloadType(), Liquid::InitAllLiquids(), Attachments::InitAttachmentGrid(), InventoryItemSuper::InitCameraOverrideProperties(), Debug::InitCanvas(), InitData(), InventoryItemSuper::InitDOFAvailability(), Weapon::InitDOFProperties(), ManBase::InitEditor(), AttachmentCategoriesContainer::InitGhostSlots(), ZombieContainer::InitGhostSlots(), MissionBaseWorld::InitialiseWorldData(), InitializeWidgets(), Container::InitIconEx(), EntityAI::InitImpactSoundData(), PluginBase::InitLoad(), InventoryItemSuper::InitMapState(), InventoryItemSuper::InitOpticsDOFProperties(), InventoryItemSuper::InitOpticsPP(), InventoryItemSuper::InitReddotData(), Weapon::InitReliability(), ITEM_GeneralData::InitServer(), ITEM_PlayerData::InitServer(), InitWidgets(), PluginBase::InitWidgets(), EffectArea::InitZone(), MissionBase::InsertCorpse(), BaseBuildingBase::InsertRefresherPosition(), HandsContainer::InspectItem(), PlayerContainer::InspectItem(), ScriptedWidgetEventHandler::InspectItem(), Interact(), Land_Underground_Panel_Lever::Interact(), ActionBaseCB::Interrupt(), CAContinuousFill::Interrupt(), CAContinuousQuantityExtinguish::Interrupt(), Inventory(), Transport::IsAreaAtDoorFree(), EntityAI::IsAreaAtDoorFree(), AttachmentsOutOfReach::IsAttachmentReachable(), Hologram::IsBaseViable(), Hologram::IsClippingRoof(), IsColliding(), Hologram::IsCollidingBBox(), IsCollidingEx(), DayZPlayerImplement::IsControlledPlayer(), PluginBase::IsCurrentUIPageValid(), IsDummyFinished(), HandsContainer::IsEmpty(), IsEntityOnInteriorSurface(), IsEntityOnWaterSurface(), BaseBuildingBase::IsFacingCamera(), Input::IsInactiveGamepadOrUserSelected(), PluginBase::IsInConsole(), PluginBase::IsIngame(), IsInventoryVisible(), HandsContainer::IsItemActive(), HandsContainer::IsItemWithQuantityActive(), IsKindOf(), ScriptedWidgetEventHandler::IsLocalPlayer(), UIScriptedMenu::IsLocalPlayer(), ManBase::IsMapCallbackCancelInput(), ManBase::IsMapCallbackEndInput(), IsObjectObstructed(), IsObjectObstructedEx(), IsOutOfMap(), MissionBase::IsPaused(), ItemBase::IsPlaceable(), IsPlaceableAtPosition(), ItemBase::IsPlaceableAtPosition(), IsRainingAboveEntity(), InventoryItem::IsServerCheck(), IsServerOrLocalPlayer(), IsSpaceFor(), Hologram::IsSurfaceSea(), Hologram::IsSurfaceWater(), ItemBase::IsSurfaceWater(), ManBase::IsTargetInActiveRefresherRange(), FireplaceBase::IsThisIgnitionSuccessful(), VONManager::IsVoiceThresholdMinimum(), IsVonToggled(), IsWindy(), ScriptedWidgetEventHandler::ItemActionsWidget(), PlayerContainer::ItemAttached(), ZombieContainer::ItemAttached(), InventoryItem::ItemBase(), ItemManager::ItemManager(), ScriptedWidgetEventHandler::KeybindingElement(), ScriptedWidgetEventHandler::KeybindingElementNew(), array::KeybindingsContainer(), ScriptedWidgetEventHandler::KeybindingsGroup(), KillPlayer(), InventoryItem::KindOf(), Land_Underground_EntranceBase::Land_Underground_EntranceBase(), LateInit(), UIScriptedMenu::LateInit(), ScriptedWidgetEventHandler::LayoutHolder(), UIScriptedMenu::Leave(), TriggerEvents::Leave(), ServerBrowserTab::LeftHold(), Weapon::LiftWeaponCheck(), AmmoCamParams::Load(), DayZCreatureAIType::LoadAnimDamageEvents(), DayZCreatureAIType::LoadAnimSoundEvents(), DayZCreatureAIType::LoadAnimSoundVoiceEvents(), DayZCreatureAIType::LoadAnimStepEvents(), Managed::LoadCharacterData(), CfgGameplayHandler::LoadData(), ModStructure::LoadData(), LoadDataAsync(), UIScriptedMenu::LoadFavoriteServers(), ScriptedWidgetEventHandler::LoadFilters(), PluginBase::LoadFromCfg(), LoadFromCfg(), LoadingScreen::LoadingScreen(), ModLoader::LoadMods(), UIScriptedMenu::LoadMods(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), LoadPlayerAttachmentIndexes(), PluginConfigHandler::LoadScenePlayer(), PluginConfigHandler::LoadSceneSettings(), InventoryItemType::LoadSoundEvents(), LoadSoundWeaponEvent(), SoundLookupTable::LoadTable(), LoadVegetationSounds(), LocalDestroyEntity(), UIMenuPanel::LockControls(), LockControls(), LockModifier(), LockOvenAttachments(), Debug::LogMessage(), PluginBase::LogPrint(), LogSuicide(), magazinesHaveEqualSizes(), MainMenuButtonEffect::MainMenuButtonEffect(), SymptomBase::MakeParamObjectPersistent(), MaterialIsRuined(), ManBase::Message(), MissionBaseWorld::MissionBase(), Dispatcher::MissionGameplayHideInventory(), MissionBase::MissionServer(), ModelToWorld(), ScriptedWidgetEventHandler::ModsMenuDetailed(), ScriptedWidgetEventHandler::ModsMenuDetailedEntry(), ScriptedWidgetEventHandler::ModsMenuSimple(), ScriptedWidgetEventHandler::ModsMenuSimpleEntry(), ScriptedWidgetEventHandler::ModsMenuTooltip(), Icon::MouseClick(), PlayerContainer::MouseClick(), ClosableContainer::MouseClick2(), ClosableHeader::MouseEnter(), MoveAttachmentDown(), MoveAttachmentUp(), ActionDeployBase::MoveEntityToFinalPosition(), MoveFocusByArea(), ItemBase::MutePlayer(), Land_Underground_EntranceBase::NavmeshUpdate(), ManBase::NeedInventoryJunctureFromServer(), ActionMenu::NextAction(), ActionMenu::NextActionCategory(), UIScriptedMenu::NoteMenu(), NotificationUI::NotificationUI(), ActionUnrestrainTargetCB::ObtainUnrestrainTime(), HandStateBase::OnAbort(), WeaponChambering_Base::OnAbort(), InventoryItem::OnAction(), ItemBase::OnAction(), ActionManagerServer::OnActionEnd(), OnActivate(), WeaponParticlesBase::OnActivate(), DrowningMdfr::OnActivate(), ClaymoreMine::OnActivatedByItem(), ImprovisedExplosive::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), RemoteDetonatorTrigger::OnActivatedByItem(), Ammo_40mm_Explosive::OnActivatedByItem(), Grenade_Base::OnActivateFinished(), Grenade_Base::OnActivateImmediate(), FlareSimulation::OnActivation(), OnAnimationEvent(), AnimatedActionBase::OnAnimationEvent(), EmoteCB::OnAnimationEvent(), ClaymoreMine::OnArmed(), OnlineServices::OnAutoConnectToEmptyServer(), ManBase::OnBleedingSourceAdded(), ManBase::OnBleedingSourceRemoved(), OnCenterPanelDropReceived(), UIScriptedMenu::OnChange(), UIPopupScript::OnChange(), HudDebugWinBase::OnChange(), UIScriptedMenu::OnChanged(), WidgetEventHandler::OnChildAdd(), WidgetEventHandler::OnChildRemove(), PluginDayzPlayerDebug_Weapons::OnClick(), OnClick(), UIScriptedMenu::OnClick(), ScriptedWidgetEventHandler::OnClick(), UIPopupScript::OnClick(), UIPropertyAttachment::OnClick(), UIScriptedWindow::OnClick(), WidgetEventHandler::OnClick(), UIScriptedMenu::OnClick_Continue(), UIScriptedMenu::OnClick_Exit(), UIScriptedMenu::OnClick_Respawn(), UIScriptedMenu::OnClick_Restart(), MissionBase::OnClientDisconnectedEvent(), MissionBase::OnClientNewEvent(), MissionBase::OnClientReadyEvent(), UIPopupScript::OnClose(), ManBase::OnCommandMoveStart(), ManBase::OnConnect(), OnContact(), Grenade_ChemGas::OnDamageDestroyed(), OnDamageDestroyed(), UnconsciousnessMdfr::OnDeactivate(), PluginBase::OnDestroy(), ManBase::OnDisconnect(), Land_Underground_Stairs_Exit::OnDoorStateChangedServer(), ScriptedWidgetEventHandler::OnDoubleClick(), UIScriptedMenu::OnDoubleClick(), WidgetEventHandler::OnDoubleClick(), WidgetEventHandler::OnDrag(), WidgetEventHandler::OnDraggingOver(), Icon::OnDraggingOverBackground(), ClosableHeader::OnDragHeader(), WidgetEventHandler::OnDrop(), WidgetEventHandler::OnDropReceived(), PlayerContainer::OnDropReceivedFromGhostArea(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), AttachmentCategoriesRow::OnDropReceivedFromHeader(), ClosableContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), ActionActivateTrap::OnEnd(), ActionLockAttachment::OnEnd(), ActionContinuousBase::OnEndAnimationLoop(), ActionActivateTrap::OnEndAnimationLoop(), OnEndAnimationLoop(), ActionDrainLiquid::OnEndAnimationLoop(), ActionLockAttachment::OnEndAnimationLoop(), ActionPourLiquid::OnEndAnimationLoop(), ActionTransferLiquid::OnEndAnimationLoop(), ActionRepackTent::OnEndAnimationLoop(), ActionEmptyBottleBase::OnEndServer(), OnEndServer(), ActionCloseDoors::OnEndServer(), ActionCloseFence::OnEndServer(), ActionOpenDoors::OnEndServer(), ActionOpenFence::OnEndServer(), ActionRepackTent::OnEndServer(), ActionSwapItemToHands::OnEndServer(), ActionEmptySeedsPack::OnEndServer(), FirearmActionDetachMagazine::OnEndServer(), ItemBase::OnEnergyAdded(), VehicleBattery::OnEnergyAdded(), ItemBase::OnEnergyConsumed(), Chemlight_ColorBase::OnEnergyConsumed(), VehicleBattery::OnEnergyConsumed(), OnEngineStart(), CarScript::OnEngineStart(), CarScript::OnEngineStop(), AreaDamageTriggerBase::OnEnter(), BarbedWireTrigger::OnEnter(), AreaDamageBase::OnEnter(), Hit_MeatBones::OnEnterCalculations(), OnEntry(), BotTestSpamUserActions::OnEntry(), HandStateBase::OnEntry(), WeaponStateBase::OnEntry(), OnEvent(), MissionBase::OnEvent(), ActionRemoveSeed::OnExecute(), ActionTakeItemToHands::OnExecute(), ActionHandcuffTarget::OnExecuteClient(), ActionDigInStash::OnExecuteServer(), OnExecuteServer(), ActionEmptyMagazine::OnExecuteServer(), ActionCheckPulse::OnExecuteServer(), ActionDetachFromTarget::OnExecuteServer(), ActionPickupChicken::OnExecuteServer(), ActionRepositionPluggedItem::OnExecuteServer(), ActionTakeHybridAttachment::OnExecuteServer(), ActionTakeHybridAttachmentToHands::OnExecuteServer(), ActionTakeItem::OnExecuteServer(), ActionSwapItemToHands::OnExecuteServer(), ActionTakeMaterialToHands::OnExecuteServer(), ActionAttachOnSelection::OnExecuteServer(), ActionAttachPowerSourceToPanel::OnExecuteServer(), ActionAttachToConstruction::OnExecuteServer(), ActionAttachWithSwitch::OnExecuteServer(), ActionCreateIndoorFireplace::OnExecuteServer(), ActionCreateIndoorOven::OnExecuteServer(), ActionDropItem::OnExecuteServer(), ActionFoldEntityToSlot::OnExecuteServer(), ActionOpen::OnExecuteServer(), ActionUnfoldEntity::OnExecuteServer(), HandStateBase::OnExit(), OnExplode(), Grenade_ChemGas::OnExplode(), FireworksLauncherClientEvent::OnExplode(), FuelStation::OnExplosionEffects(), Grenade_Base::OnExplosionEffects(), ActionUnfoldMapCB::OnFinish(), ActionBaseCB::OnFinish(), ActionContinuousBase::OnFinishProgress(), ActionRestrainTarget::OnFinishProgressClient(), ActionShave::OnFinishProgressClient(), ActionSkinning::OnFinishProgressClient(), ActionBandageTarget::OnFinishProgressClient(), ActionActivateTrap::OnFinishProgressServer(), OnFinishProgressServer(), ActionCreateGreenhouseGardenPlot::OnFinishProgressServer(), ActionDestroyCombinationLock::OnFinishProgressServer(), ActionDigGardenPlot::OnFinishProgressServer(), ActionDigInStash::OnFinishProgressServer(), ActionDigWorms::OnFinishProgressServer(), ActionDismantleGardenPlot::OnFinishProgressServer(), ActionPackGift::OnFinishProgressServer(), ActionRepairCarChassis::OnFinishProgressServer(), ActionRepairCarEngine::OnFinishProgressServer(), ActionRepairCarPart::OnFinishProgressServer(), ActionRepairTent::OnFinishProgressServer(), ActionRepairTentPart::OnFinishProgressServer(), ActionSawPlanks::OnFinishProgressServer(), ActionSkinning::OnFinishProgressServer(), ActionStripCarrierVest::OnFinishProgressServer(), ActionUnpackBox::OnFinishProgressServer(), ActionUnpackGift::OnFinishProgressServer(), ActionUnrestrainTarget::OnFinishProgressServer(), ActionDeployBase::OnFinishProgressServer(), ActionMeasureTemperatureTarget::OnFinishProgressServer(), ActionRepackTent::OnFinishProgressServer(), Weapon::OnFireModeChange(), ScriptedWidgetEventHandler::OnFocus(), WidgetEventHandler::OnFocus(), WidgetEventHandler::OnFocusLost(), PluginBase::OnFrame(), PointLightBase::OnFrameLightSource(), FireworksLauncher::OnFuseIgnitedServer(), BiosUserManager::OnGameNameChanged(), Input::OnGamepadConnected(), Input::OnGamepadIdentification(), MissionBase::OnGameplayDataHandlerLoad(), ManBase::OnGameplayDataHandlerSync(), BiosSessionService::OnGetGameplaySession(), BiosSessionService::OnGetSessionError(), OnGUI(), OnGUITimer(), PluginBase::OnGUITimer(), HandsArea::OnHandsPanelDropReceived(), DestructionEffectBase::OnHealthLevelChanged(), UIScriptedMenu::OnHide(), OnHide(), SlotsIcon::OnIconDrag(), ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), FireplaceBase::OnIgnitedThis(), SymptomBase::OnInit(), PluginBase::OnInit(), MissionBase::OnInit(), OnInit(), ItemBase::OnInitEnergy(), ScriptedWidgetEventHandler::OnInputDeviceChanged(), UIScriptedMenu::OnInputDeviceChanged(), OnInputDeviceChanged(), ServerBrowserTab::OnInputDeviceChanged(), WeaponManager::OnInputUserDataProcess(), ManBase::OnInputUserDataProcess(), OnInventoryEnter(), ItemBase::OnIsCharged(), AnalyticsManagerClient::OnItemAttachedAtPlayer(), InventoryGridController::OnItemDrag(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), OnItemLocationChanged(), ItemBase::OnItemLocationChanged(), BiosUserManager::OnJoin(), ManBase::OnJumpOutVehicleFinish(), PluginBase::OnKeyPress(), MissionBaseWorld::OnKeyRelease(), Input::OnLastInputDeviceChanged(), AreaDamageTriggerBase::OnLeave(), AreaDamageBase::OnLeave(), Backlit::OnLeaveCar(), CfgGameplayHandler::OnLoaded(), OnlineServices::OnLoadVoicePrivilege(), MissionBaseWorld::OnLog(), BiosUserManager::OnLoggedOn(), MissionBase::OnMenuEnter(), MissionBase::OnMissionFinish(), UIScriptedMenu::OnModalResult(), PluginBase::OnMouse(), ScrollBarContainer::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseButtonDown(), UIScriptedMenu::OnMouseButtonDown(), WidgetEventHandler::OnMouseButtonDown(), MissionBaseWorld::OnMouseButtonPress(), PluginBase::OnMouseButtonRelease(), MissionBaseWorld::OnMouseButtonRelease(), OnMouseButtonUp(), ScriptedWidgetEventHandler::OnMouseButtonUp(), WidgetEventHandler::OnMouseButtonUp(), ScriptedWidgetEventHandler::OnMouseEnter(), OptionSelectorBase::OnMouseEnter(), WidgetEventHandler::OnMouseEnter(), ScriptedWidgetEventHandler::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), WidgetEventHandler::OnMouseLeave(), WidgetEventHandler::OnMouseWheel(), UIPopupScript::OnOpen(), InventoryItemSuper::OnOpticEnter(), InventoryItemSuper::OnOpticExit(), Land_Underground_Panel_Lever::OnPanelUsedSynchronized(), ItemBase::OnPartBuiltServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ManBase::OnParticleEvent(), ScriptedWidgetEventHandler::OnPartyChatChangedEvent(), BiosUserManager::OnPartyHost(), Icon::OnPerformCombination(), HandsContainer::OnPerformCombination(), Icon::OnPerformRecipe(), Grenade_Base::OnPin(), ClaymoreMine::OnPlacementComplete(), GardenBase::OnPlacementComplete(), ItemBase::OnPlacementComplete(), KitBase::OnPlacementComplete(), OnPlacementComplete(), FireworksLauncher::OnPlacementComplete(), Inventory_Base::OnPlacementComplete(), TentBase::OnPlacementComplete(), TrapBase::OnPlacementComplete(), ItemBase::OnPlacementStarted(), ManBase::OnPlayerLoaded(), MissionBase::OnPlayerRespawned(), WeaponDebug::OnPostFrameUpdate(), ManBase::OnRestrainStart(), InventoryItem::OnRightClick(), OnRightPanelDropReceived(), PluginBase::OnRPC(), WrittenNoteData::OnRPC(), ManBase::OnRPC(), OnRPC(), PluginBase::OnRPCSyncSceneObject(), PluginBase::OnRPCTemp(), OnScheduledTick(), DebugMonitorValues::OnScheduledTick(), Managed::OnScheduledTick(), ScriptedWidgetEventHandler::OnSelectAction(), ScriptedWidgetEventHandler::OnSelectConsolePreset(), ScriptedWidgetEventHandler::OnSelectKBPreset(), UIScriptedMenu::OnSelectKBPreset(), ManBase::OnSelectPlayer(), OnServerInventoryCommandStatic(), DeveloperFreeCamera::OnSetFreeCameraEvent(), UIScriptedMenu::OnShow(), OnShow(), BiosUserManager::OnSignedOut(), DayZPlayerCommandDeathCallback::OnSimulationEnd(), ManBase::OnSpawnedFromConsole(), FirearmActionDetachMagazine::OnStageStart(), ManBase::OnStanceChange(), PPERequester_GameplayBase::OnStart(), ActionContinuousBase::OnStartAnimationLoop(), ActionActivateTrap::OnStartAnimationLoop(), OnStartAnimationLoop(), ActionDrainLiquid::OnStartAnimationLoop(), ActionEmptyBottleBase::OnStartAnimationLoop(), ActionLockAttachment::OnStartAnimationLoop(), ActionPourLiquid::OnStartAnimationLoop(), ActionTransferLiquid::OnStartAnimationLoop(), ActionRepackTent::OnStartAnimationLoopServer(), OnStartClient(), ActionTransferLiquid::OnStartServer(), OnStartServer(), ActionHandsPartSwitch::OnStartServer(), ActionBuildPartSwitch::OnStartServer(), FirearmActionDetachMagazine::OnStartServer(), ActionReadPaperCB::OnStateChange(), ActionWritePaperCB::OnStateChange(), OnStepEvent(), TrapBase::OnSteppedOn(), OnSteppedOn(), PPERequester_GameplayBase::OnStop(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), ItemBase::OnStoreLoadCustom(), ItemBase::OnStoreSave(), FireplaceBase::OnStoreSave(), Grenade_Base::OnStoreSave(), ManBase::OnStoreSave(), ReplaceWithNewReciveCargoLambda::OnSuccess(), Backlit::OnSwimmingStop(), ItemBase::OnSwitchOff(), FlammableBase::OnSwitchOff(), ItemBase::OnSwitchOn(), FlammableBase::OnSwitchOn(), SymptomManager::OnSymptomExit(), WeaponManager::OnSyncJuncture(), UIScriptedMenu::OnTabSeleted(), ManBase::OnTick(), SymptomManager::OnTick(), ShockMdfr::OnTick(), LoadingScreen::OnTimer(), UniversalTemperatureSource::OnTimer(), TimerBase::OnTimer(), PlantSuper::OnTreeCutDown(), PluginBase::OnUIEditorOpened(), ManBase::OnUnconsciousStart(), ManBase::OnUnconsciousStop(), ManBase::OnUnconsciousUpdate(), OnUndergroundPresenceUpdate(), Grenade_Base::OnUnpin(), InventoryActionHandler::OnUpdate(), AlarmClock_ColorBase::OnUpdate(), UIPopupScript::OnUpdate(), ActionReadPaper::OnUpdate(), ActionWritePaper::OnUpdate(), PPERequester_GameplayBase::OnUpdate(), OnUpdate(), DayZPlayerCameraBase::OnUpdate(), MissionBase::OnUpdate(), OnUpdateClient(), BiosUserManager::OnUserLoggedOn(), BiosUserManager::OnUserPicked(), OnValveManipulationCanceled(), OnValveManipulationEnd(), OnValveManipulationStart(), InventoryItem::OnVariablesSynchronized(), ItemBase::OnVariablesSynchronized(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), OnVariablesSynchronized(), OnVOIPThresholdChanged(), ScriptedWidgetEventHandler::OnVonStateEvent(), ClothingBase::OnWasAttached(), PlateCarrierVest::OnWasAttached(), OnWasAttached(), InventoryItem::OnWasDetached(), ClothingBase::OnWasDetached(), OnWasDetached(), WeaponManager::OnWeaponActionEnd(), ScriptedWidgetEventHandler::OnWidgetScriptInit(), OnWork(), ItemBase::OnWork(), Clothing::OnWork(), Heatpack::OnWork(), PoweredOptic_Base::OnWork(), Roadflare::OnWork(), Switchable_Base::OnWork(), FlammableBase::OnWork(), InventoryItemSuper::OnWorkStart(), OnWorkStart(), ItemBase::OnWorkStart(), Clothing::OnWorkStart(), Heatpack::OnWorkStart(), PoweredOptic_Base::OnWorkStart(), Roadflare::OnWorkStart(), Switchable_Base::OnWorkStart(), InventoryItemSuper::OnWorkStop(), ItemBase::OnWorkStop(), Chemlight_ColorBase::OnWorkStop(), Clothing::OnWorkStop(), Heatpack::OnWorkStop(), PoweredOptic_Base::OnWorkStop(), Roadflare::OnWorkStop(), Switchable_Base::OnWorkStop(), FlammableBase::OnWorkStop(), ScriptedWidgetEventHandler::OpenDiscord(), ScriptedWidgetEventHandler::OpenDLC(), ScriptedWidgetEventHandler::OpenFeedback(), BaseBuildingBase::OpenFence(), ScriptedWidgetEventHandler::OpenForums(), UIScriptedMenu::OpenMenu(), Land_Underground_EntranceBase::OpenServer(), ScriptedWidgetEventHandler::OpenTwitter(), UIManager::OpenWindow(), ScriptedWidgetEventHandler::OpenYoutube(), OptionSelectorBase::OptionSelector(), OptionSelectorBase::OptionSelectorEditbox(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::OptionsMenuVideo(), OrderedPositionNumbersFromGridCoords(), PPEffects::OverrideDOF(), ItemBase::Pack(), RemotelyActivatedItemBehaviour::Pair(), ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ParticleCookingStop(), Inventory_Base::ParticleCookingStop(), ItemBase::ParticleTest(), PartyLaunch(), MissionBase::Pause(), ActionManagerClient::PerformActionStart(), ActionUnfoldMapCB::PerformMapChange(), BaseBuildingBase::PerformRoofCheckForBase(), UIScriptedMenu::PerformSetToDefaults(), UIScriptedMenu::PerformSwitchPreset(), ItemBase::PileOfWoodenPlanks(), ItemBase::Pitch(), Hologram::PlaceEntity(), ItemBase::PlaceOnGround(), SceneObject::PlaceOnSurface(), EffectArea::PlaceParticles(), ManBase::PlacingStartLocal(), ItemBase::PlantBase(), Play(), UIScriptedMenu::Play(), PlayActionSound(), InventoryItem::PlayAttachSound(), InventoryItem::PlayDeployFinishSound(), ItemBase::PlayDeployLoopSound(), Inventory_Base::PlayDeployLoopSound(), InventoryItem::PlayDeploySound(), PlayerContainer::PlayerContainer(), MissionBase::PlayerControlDisable(), MissionBase::PlayerControlEnable(), MissionBase::PlayerDisconnected(), PluginBase::PlayerList(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), PlayerPreview::PlayerPreview(), PlayerSoundManagerClient(), PlayerSyncCreate(), PlayerSyncDelete(), ContaminatedArea_Dynamic::PlayFlareVFX(), ContaminatedArea_Dynamic::PlayFX(), MissionBase::PlayMusic(), PlayParticle(), PluginBase::PlayPause(), InventoryItem::PlayPlaceSound(), PlaySFX(), DayZCreature::PlaySound(), EntityAI::PlaySound(), PlaySound(), PlaySoundActivate(), PlaySoundLoop(), PlaySoundSet(), PlaySurrenderInOut(), PlayVFX(), PluginBase::PluginAdminLog(), PluginDayzPlayerDebug_Weapons::PluginDayzPlayerDebug_Weapons(), ComponentEnergyManager::PlugInDevice(), UIPopupScript::PopupBack(), UIPopupScript::PopupOpen(), FirearmActionAttachMagazine::Post_SetupAction(), FirearmActionAttachMagazineQuick::Post_SetupAction(), RecoilBase::PostInit(), StaminaSoundHandlerBase::PostponeStamina(), ParticleList::PreloadParticles(), ReplaceItemWithNewLambdaBase::PrepareLocations(), ItemManager::PrepareTooltip(), MouseButtonInfo::Press(), ServerBrowserTabConsolePages::PressX(), ServerBrowserTab::PressX(), ActionMenu::PrevAction(), ActionMenu::PrevActionCategory(), UIScriptedMenu::PrimaryAction(), ProccessInputData(), HeatComfortAnimHandler::Process(), ItemBase::ProcessDecay(), UIScriptedMenu::ProcessEmoteConditionRequest(), ManBase::ProcessFeetDamageServer(), ManBase::ProcessHandDamage(), BleedingSourcesManagerBase::ProcessHit(), EntityAI::ProcessImpactSound(), ProcessLighting(), MissionBase::ProcessLoginData(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), ProcessWeaponEvent(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialMenu(), RadialProgressBar::RadialProgressBar(), UIScriptedMenu::RadialQuickbarMenu(), RainProcurementManager::RainProcurementCheck(), MissionBase::RandomArtillery(), UIScriptedMenu::RandomizeCharacter(), ReceiveMaterialsServer(), DebugMonitorValues::ReceiveValue(), ItemBase::Refresh(), ActionMenu::Refresh(), UIScriptedMenu::Refresh(), Refresh(), RefreshFireplaceVisuals(), ManBase::RefreshHandAnimationState(), UIScriptedMenu::RefreshPlayerPosEditBoxes(), Hud::RefreshPlayerTags(), Icon::RefreshQuickbar(), RefreshQuickbar(), Hud::RefreshQuickbar(), AttachmentCategoriesRow::RefreshSlot(), RefreshState(), Hud::RefreshVehicleHud(), VicinityItemManager::RefreshVicinityItems(), Hologram::RefreshVisual(), ItemBase::RegenerateNavmesh(), DayZCreature::RegisterAnimEvents(), RegisterAttacks(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), SyncEvents::RegisterEvents(), GameplayEffectWidgets_base::RegisterLayouts(), PluginManager::RegisterPlugin(), DayZProfilesOptions::RegisterProfileOption(), Release(), MouseButtonInfo::Release(), PluginBase::ReleaseFocus(), ReleaseFocus(), ScriptedWidgetEventHandler::Reload(), InventoryGridController::Remove(), EntityAI::RemoveAction(), RemoveAction(), InventoryItem::RemoveAction(), ManBase::RemoveActiveNV(), SceneObject::RemoveAttachment(), RemoveInsider(), ReplaceItemWithNewLambdaBase::RemoveNetworkObjectInfo(), RemoveNetworkObjectInfo(), ItemBase::RemovePlant(), ItemBase::RemovePlantEx(), BaseBuildingBase::RemoveRefresherPosition(), ItemBase::RemoveSlot(), RemoveSplint(), ActionRepairPart::RepairCondition(), ActionRepairTent::RepairDamageTransfer(), DestructionEffectBase::ReplaceEntityServer(), UndergroundTriggerCarrierBase::RequestDelayedTriggerSpawn(), RequestDetailedInfo(), ManBase::RequestHandAnimationStateRefresh(), Land_Underground_EntranceBase::RequestLatentTransition(), ManBase::RequestResetADSSync(), UIScriptedMenu::RequestRespawn(), FireworksLauncherClientEvent::RequestSecondaryExplosion(), House::RequestSoundEvent(), UIScriptedMenu::Reset(), UIScriptedMenu::ResetCurrentTab(), ResetDeathStartTime(), ComponentEnergyManager::ResetEnergyUsage(), PluginBase::ResetGUI(), ResetModifiers(), DayZProfilesOptions::ResetOptions(), PPEffects::ResetPPMask(), UIPopupScript::ResetSliders(), HudDebugWinBase::ResetStats(), Icon::RevertToOriginalFlip(), RightArea::RightArea(), ServerBrowserTab::RightHold(), RPC(), HudDebugWinBase::RPCChangeStat(), RPCSingleParam(), array::Run(), UIScriptedMenu::RunEnscript(), UIScriptedMenu::RunEnscriptServer(), PluginBase::Save(), Managed::SaveCharName(), DayZIntroSceneXbox::SaveCharName(), UIScriptedMenu::SaveFavoriteServersConsoles(), ScriptedWidgetEventHandler::SaveFilters(), PlayerStats::SaveStats(), BetaSound::SaySound(), ManBase::SaySoundSet(), Dispatcher::SceneEditorCommand(), PluginBase::SceneLoad(), SceneObject::SceneObjectSynch(), UIScriptedMenu::ScriptConsole(), Dispatcher::ScriptConsoleAddPrint(), Dispatcher::ScriptConsoleGetSelectedItem(), Dispatcher::ScriptConsoleHistoryBack(), Dispatcher::ScriptConsoleHistoryForward(), EntityLightSource::ScriptedLightBase(), UIScriptedMenu::SecondaryAction(), Attachments::Select(), Container::Select(), HandsPreview::Select(), AttachmentCategoriesRow::Select(), PlayerContainer::Select(), VicinitySlotsContainer::Select(), ZombieContainer::Select(), PluginBase::SelectAndFocusPlayerObject(), SelectCrossHair(), ScriptedWidgetEventHandler::SelectPlayer(), DayZPlayerUtils::SelectStoreCartridge(), SelectUser(), BiosUserManager::SelectUserEx(), SendEmoteRequestSync(), InventoryInputUserData::SendInputUserDataDestroy(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), ManBase::SendLiftWeaponSync(), SendMessageToClient(), SendRPC(), PluginBase::SendRPCAgents(), SymptomManager::SendServerDebugToClient(), InventoryInputUserData::SendServerHandEventViaInventoryCommand(), SendServerHandEventViaJuncture(), PluginBase::SendServerLogToClient(), InventoryInputUserData::SendServerMove(), InventoryInputUserData::SendServerSwap(), ManBase::SendSoundEventEx(), SyncEvents::SendSyncEvent(), SendSyncMessages(), Managed::SendValue(), DebugMonitorValues::SendValue(), ItemManager::SerializeDefaultHeaderOpenStates(), ItemManager::SerializeDefaultOpenStates(), ScriptedWidgetEventHandler::ServerBrowserEntry(), ScriptedWidgetEventHandler::ServerBrowserFilterContainer(), InventoryActionHandler::SetAction(), SetActive(), ItemBase::SetActive(), HandsContainer::SetActive(), SetAlarmInXMins(), PluginBase::SetBadge(), PPEffects::SetBlur(), Roadflare::SetBurningStateSynchronized(), SetBurntFirewood(), SetCarHornState(), UIScriptedMenu::SetCharacter(), PPEffects::SetChromAbb(), SetControlType(), ItemManager::SetDefaultOpenStateHands(), UniversalTemperatureSourceDebug::SetDefferedActive(), PluginBase::SetDeveloperItemClient(), PluginBase::SetDeveloperItemClientEx(), BleedingSourcesManagerBase::SetDiag(), SetDisplayNameText(), WeaponManager::SetEjectBulletTryTimestamp(), ComponentEnergyManager::SetEnergy(), ComponentEnergyManager::SetEnergy0To1(), SetEntityShortcut(), OnlineServices::SetGameplayActivity(), UIScriptedMenu::SetGameVersion(), WorldLighting::SetGlobalLighting(), ManBase::SetHairLevelToHide(), CTObjectFollower::SetHandsItem(), SceneObject::SetHealth(), ItemBase::SetInactive(), SceneData::SetInitDay(), SceneData::SetInitFog(), SceneData::SetInitHour(), SceneData::SetInitMinute(), SceneData::SetInitMonth(), SceneData::SetInitOvercast(), SceneData::SetInitRain(), SceneData::SetInitWindForce(), SceneData::SetInitYear(), SlotsIcon::SetItemSize(), Icon::SetItemSizeEx(), HandsContainer::SetLastActive(), EntityLightSource::SetLifetime(), Container::SetLock(), SetLockOnAttachedMaterials(), ScriptedWidgetEventHandler::SetMapName(), PPEffects::SetNVParams(), SetNVPostprocess(), TrapTrigger::SetParentObject(), OnlineServices::SetPendingInviteList(), PlayerContainer::SetPlayer(), DeveloperTeleport::SetPlayerDirection(), DeveloperTeleport::SetPlayerPosition(), SceneObject::SetPosition(), UIScriptedMenu::SetPreset(), UIScriptedMenu::SetPreviewObject(), DayZProfilesOptions::SetProfileOption(), SetProfileValueBool(), PPEffects::SetRadialBlur(), ConstructionPart::SetRequestBuiltState(), UIScriptedMenu::SetServerInfo(), ItemBase::SetSlotTextureFertilized(), SetSmokeGrenadeState(), ItemBase::SetSpoiled(), PluginBase::SetStamina(), Hud::SetStamina(), PluginBase::SetStance(), SetState(), CAContinuousFertilizeGardenSlot::Setup(), SetupAction(), ActionBuildPart::SetupAction(), ActionFishingNew::SetupAction(), ActionWorldCraft::SetupAction(), ActionDebug::SetupAction(), ActionBuildShelter::SetupAction(), ActionDetachFromTarget::SetupAction(), ActionAttachOnSelection::SetupAction(), ActionAttachWithSwitch::SetupAction(), FirearmActionLoadBulletQuick::SetupAction(), SetUpdate(), HudDebugWinBase::SetUpdate(), Managed::SetupPlayerName(), SetupTrap(), ItemBase::SetupTrap(), TrapSpawnBase::SetupTrap(), SetupTrapPlayer(), ItemBase::SetupTrapPlayer(), ItemBase::SetUsed(), PPERequester_GameplayBase::SetValuesIronsights(), PPERequester_GameplayBase::SetValuesOptics(), InventoryItem::SetVariableMask(), SetWaterLevelHeight(), UIScriptedMenu::ShoesChanged(), ShootsExplosiveAmmo(), ScriptedWidgetEventHandler::ShowActionMenu(), HandsContainer::ShowActionMenuCombine(), Icon::ShowActionMenuCombine(), MissionBase::ShowChat(), ShowDeadScreen(), ServerBrowserTab::ShowHideConsoleWidgets(), MissionBase::ShowInventory(), OnlineServices::ShowInviteScreen(), Hud::ShowPlayerTag(), InventoryItemSuper::ShowReddot(), ItemManager::ShowSourceDropzone(), ManBase::ShowUnconsciousScreen(), Hud::ShowVehicleInfo(), ShowVoiceNotification(), FlareSimulation::Simulate(), SimulateDeath(), EnProfilerTests::Sleep(), SleepAgain(), SlotsIcon::SlotsIcon(), SnapOnObject(), DayZIntroScene::SnapToGround(), DayZIntroSceneXbox::SnapToGround(), SoftSkillManagerDebug(), ActionSortAmmoPile::SortAmmo(), ItemBase::SoundBuzzLoopStart(), ItemBase::SoundBuzzLoopStop(), ItemBase::SoundCollision(), ItemBase::SoundCookingStart(), Inventory_Base::SoundCookingStart(), ItemBase::SoundCookingStop(), Inventory_Base::SoundCookingStop(), ItemBase::SoundCut(), ItemBase::SoundElectricShock(), BaseBuildingBase::SoundGateCloseEnd(), BaseBuildingBase::SoundGateCloseStart(), BaseBuildingBase::SoundGateOpenStart(), EffectSound::SoundPlayEx(), ItemBase::SoundSpark(), ManBase::SpawnAI(), ItemBase::SpawnCatch(), TrapSpawnBase::SpawnCatch(), StaticConstructionMethods::SpawnConstructionMaterialPiles(), PluginBase::SpawnEntityAsAttachment(), PluginBase::SpawnEntityInInventory(), PluginBase::SpawnEntityOnCursorDir(), PluginBase::SpawnEntityOnGroundPatternGrid(), PluginBase::SpawnEntityOnGroundPos(), ManBase::SpawnEntityOnGroundPos(), PluginBase::SpawnFromClipboard(), ContaminatedArea_Dynamic::SpawnItems(), TentBase::SpawnKit(), PluginBase::SpawnNewInfectedEntity(), ObjectSpawnerHandler::SpawnObject(), CrashBase::SpawnRandomDeerLater(), CrashBase::SpawnRandomDeers(), UndergroundTriggerCarrierBase::SpawnTrigger(), UndergroundAreaLoader::SpawnTriggerCarrier(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxCargoClient(), InventoryItem::SplitIntoStackMaxClient(), InventoryItem::SplitIntoStackMaxHandsClient(), InventoryItem::SplitIntoStackMaxToInventoryLocationClient(), HandsContainer::SplitItem(), ManBase::SpreadAgentsEx(), StaminaHandler(), Chemlight_ColorBase::StandUp(), FlammableBase::StandUp(), Start(), ActionDropItemSimple::Start(), ActionSwitchSeats::Start(), WeaponManager::StartAction(), StartActivate(), ActionManagerServer::StartDeliveredAction(), StartFire(), MissionBase::StartLogoutMenu(), ItemBase::StartLoopSound(), PoweredOptic_Base::StartPeriodicMeasurement(), ScriptedWidgetEventHandler::StartSlideshow(), StartSourceBleedingIndication(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), Stop(), UIScriptedMenu::Stop(), ItemBase::StopDeployLoopSound(), Inventory_Base::StopDeployLoopSound(), StopFire(), StopParticle(), ScrollBarContainer::StopScrolling(), ScriptedWidgetEventHandler::StopSlideShow(), StopSoundSet(), StopSourceBleedingIndication(), UIScriptedMenu::StopVideo(), EnProfilerTests::StringConcat(), EnProfilerTests::StringFormat(), Icon::Swap(), ManBase::SwitchItemTypeAttach(), ComponentEnergyManager::SwitchOff(), ComponentEnergyManager::SwitchOn(), PluginBase::SwitchPermanentCrossHair(), PlayerBase::SwitchPersonalLight(), SwitchPreset(), CfgGameplayHandler::SyncDataSend(), UndergroundAreaLoader::SyncDataSend(), CfgGameplayHandler::SyncDataSendEx(), MissionBase::SyncGlobalLighting(), Synch(), SoftSkillsManager::SynchDebugStats(), SynchExplosion(), WeaponManager::Synchronize(), ItemBase::Synchronize(), Synchronize(), Inventory_Base::Synchronize(), ItemBase::SynchronizeBaseState(), ComponentBodyStaging::SynchSkinnedState(), SoftSkillsManager::SynchSpecialtyLevel(), InventoryItemSuper::SyncMapMarkers(), ItemBase::SyncSlots(), SymptomBase::SyncToClientActivated(), SymptomBase::SyncToClientDeactivated(), SyncValveVariables(), HandsContainer::TakeAsAttachment(), ClosableContainer::TakeAsAttachment(), EntityAI::TakeEntityToHandsImpl(), TakeMaterialsServer(), TakeToDst(), DeveloperTeleport::TeleportAtCursor(), DeveloperTeleport::TeleportAtCursorEx(), TeleportCheck(), TestCleanup(), EnProfilerTests::TestFuncCountData(), PMTPlayback::TestOnePlaying(), PMTPlayback::TestOnePlayingStandAlone(), PMTPlayback::TestOnePlayingStandAloneAutoDestroy(), TestOwnership(), ManBase::TestSend(), PMTPlayback::TestStopping(), PMTPlayback::TestWiggleStress(), HumanInventory::ThrowEntity(), ThrowEntityFromInventory(), PluginDayzPlayerDebug_Weapons::Tick(), AnimationTimer::Tick(), Tick(), TickNotifiers(), MissionBase::TickScheduler(), PluginBase::ToggleCameraTools(), ToggleDebugWindowEvent(), PluginBase::ToggleFocus(), PluginBase::ToggleFreeCamera(), PluginBase::ToggleFreeCameraBackPos(), ScriptedWidgetEventHandler::ToggleMute(), ManBase::TogglePlacingLocal(), PluginBase::ToggleScriptConsole(), UIScriptedMenu::TopChanged(), TransferInventory(), Attachments::TransferItem(), Container::TransferItem(), HandsContainer::TransferItem(), AttachmentCategoriesRow::TransferItem(), PlayerContainer::TransferItem(), VicinitySlotsContainer::TransferItem(), ZombieContainer::TransferItem(), TransferItemProperties(), Attachments::TransferItemToVicinity(), Container::TransferItemToVicinity(), HandsContainer::TransferItemToVicinity(), AttachmentCategoriesRow::TransferItemToVicinity(), PlayerContainer::TransferItemToVicinity(), ZombieContainer::TransferItemToVicinity(), ScriptedWidgetEventHandler::TransformToScreenPos(), TryAcquireInventoryJunctureFromServer(), TryAcquireTwoInventoryJuncturesFromServer(), BiosSessionService::TryGetSession(), EntityLightSource::TryShadowOptimization(), FlammableBase::TryTransformIntoStick(), ScriptedWidgetEventHandler::TutorialKeybinds(), UIPropertyAttachment::UIPropertyAttachment(), PluginDayzPlayerDebug_OtherCmds::Uncon_End(), PluginDayzPlayerDebug_OtherCmds::Uncon_Start(), UndergroundHandlerClient(), ReplaceItemWithNewLambdaBase::UndoRemoveNetworkObjectInfo(), UndoRemoveNetworkObjectInfo(), Inventory_Base::Unfold(), UnlimitedAmmoDebugCheck(), UIMenuPanel::UnlockControls(), ComponentEnergyManager::UnplugDevice(), ComponentEnergyManager::UnplugThis(), UpdataControllerInput(), Update(), StaminaSoundHandlerBase::Update(), ScriptedWidgetEventHandler::Update(), HudDebugWinBase::Update(), ShockHandler::Update(), WeaponManager::Update(), SymptomBase::Update(), NotificationSystem::Update(), UIScriptedMenu::Update(), GameplayEffectsData::Update(), ActionManagerClient::Update(), ActionManagerServer::Update(), Roadflare::UpdateActiveParticles(), ScriptedWidgetEventHandler::UpdateAudioLevel(), WorldData::UpdateBaseEnvTemperature(), Hud::UpdateBloodName(), ComponentEnergyManager::UpdateCanWork(), FlammableBase::UpdateCheckForReceivingUpgrade(), PPEffects::UpdateColor(), InputUtils::UpdateConsolePresetID(), UpdateConstructionParts(), UIScriptedMenu::UpdateControlsElements(), MissionBase::UpdateCorpseStatesServer(), MissionBase::UpdateDebugMonitor(), ManBase::UpdateDelete(), UpdateDistanceWidget(), ClosableHeader::UpdateFlip(), Icon::UpdateFlip(), ItemBase::UpdateFuelMeter(), UIScriptedMenu::UpdateGUI(), UIScriptedMenu::UpdateInfo(), UIScriptedMenu::UpdateInfoPanelText(), UpdateInsiders(), AreaDamageTriggerBase::UpdateInsiders(), Attachments::UpdateInterval(), HandsPreview::UpdateInterval(), HandsHeader::UpdateInterval(), VicinityContainer::UpdateInterval(), UpdateInterval(), PlayerPreview::UpdateInterval(), EntityAI::UpdateInventoryMenu(), InventoryGridController::UpdateItems(), UpdateLifespan(), ManBase::UpdateLighting(), MissionBase::UpdateLogoutPlayers(), FlammableBase::UpdateMaterial(), UIScriptedMenu::UpdateMenuFocus(), UIScriptedMenu::UpdateMousePos(), ItemBase::UpdateNavmesh(), PumpkinHelmet::UpdateNVGStatus(), ItemBase::UpdatePhysics(), MissionBase::UpdatePlayersStats(), ScriptedWidgetEventHandler::UpdatePos(), DayZIntroSceneXbox::UpdateSelectedUserName(), Hologram::UpdateSelections(), KazuarOptic::UpdateSelectionVisibility(), StarlightOptic::UpdateSelectionVisibility(), UpdateSpecialtyMeter(), ScriptedWidgetEventHandler::UpdateStats(), ItemBase::UpdateStatusLights(), PluginBase::UpdateStatWidgets(), UIScriptedMenu::UpdateTime(), UpdateVisuals(), ScriptedWidgetEventHandler::UpdateWasMicCapturing(), ActionMenu::UpdateWidgets(), UpdateWidgetsStats(), UIMenuPanel::UseKeyboard(), UIMenuPanel::UseMouse(), VirtualHud(), UIScriptedMenu::WarningMenuBase(), Weapon::Weapon_Base(), WeaponParticlesBase::WeaponParticlesBase(), WorldData::WeatherOnBeforeChange(), WorldToModel(), CrashBase::Wreck_Mi8_Crashed(), CrashBase::Wreck_SantasSleigh(), CrashBase::Wreck_UH1Y(), ActionUnfoldMapCB::~ActionUnfoldMapCB(), UIScriptedMenu::~CameraToolsMenu(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ~CrossHairSelector(), DayZIntroSceneXbox::~DayZIntroSceneXbox(), EmoteCB::~EmoteCB(), UIScriptedMenu::~GesturesMenu(), HandsPreview::~HandsPreview(), Hologram::~Hologram(), UIScriptedMenu::~InGameMenuXbox(), UIScriptedMenu::~InspectMenuNew(), ScriptedWidgetEventHandler::~ItemActionsWidget(), InventoryItem::~ItemBase(), MainMenuButtonEffect::~MainMenuButtonEffect(), MissionBaseWorld::~MissionBase(), MissionBase::~MissionServer(), UIScriptedMenu::~NoteMenu(), ScriptedWidgetEventHandler::~OptionsMenuSounds(), ScriptedWidgetEventHandler::~OptionsMenuVideo(), ManBase::~PlayerBase(), PluginManager::~PluginManager(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), RadialProgressBar::~RadialProgressBar(), UIScriptedMenu::~RadialQuickbarMenu(), SceneObject::~SceneObject(), UIScriptedMenu::~ScriptConsole(), ShockDealtEffect::~ShockDealtEffect(), ~SoftSkillManagerDebug(), ItemBase::~TentBase(), UIPopupScript::~UIPopupScriptSceneManager(), UIPopupScript::~UIPopupScriptSceneSettings(), ~UndergroundHandlerClient(), UndergroundTriggerCarrierBase::~UndergroundTriggerCarrier(), and UIScriptedMenu::~WarningMenuBase().
GetMax()
proto native float GetMax ()
Referenced by ManBase::ResetPlayer().
GetMin()
proto native float GetMin ()
GetPathFromSlotID()
static string GetPathFromSlotID (int slot_ID) static
Returns config path of att. slot category, empty if undefined.
Definition at line 1104 of file gameplay.c.
    {
        int idx = m_AttachmentSlots.Find(slot_ID);
        string path = "" + m_Path + " " + m_ConfigArrayNames.Get(idx);
        return path;
    }
References m_AttachmentSlots, m_ConfigArrayNames, m_Path, and path.
Referenced by GetConfigArrayCountFromSlotID(), and GetConfigAttachmentTypes().
SpawnEntity()
EntityAI SpawnEntity (string object_name, notnull InventoryLocation inv_loc, int iSetupFlags, int iRotation)
Definition at line 1425 of file gameplay.c.
{
    return GameInventory.LocationCreateEntity(inv_loc, object_name,iSetupFlags,iRotation);
}
WriteValue()
proto native void WriteValue (float value)
Variable Documentation
Event_OnRevert
ref ScriptInvoker Event_OnRevert = new ScriptInvoker()
Definition at line 0 of file gameplay.c.
INDEX_NOT_FOUND
const int INDEX_NOT_FOUND = -1
Definition at line 13 of file gameplay.c.
Referenced by VicinityItemManager::AddVicinityCargos(), VicinityItemManager::AddVicinityItems(), EOnPostSimulate(), SpacerBase::GetChildIndex(), GetComponentIndex(), GPSReceiver::GetHiddenSelection(), GetTurnableValveIndex(), Init(), InventoryGridController::InventoryQuickbar(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), OnItemInPlayerPossession(), VicinityItemManager::RefreshVicinityItems(), GPSReceiver::UpdateDisplayElevation(), and GPSReceiver::UpdateDisplayPosition().
m_AttachmentSlots
class MenuDefaultCharacterData m_AttachmentSlots
Initial value:
= {
        InventorySlots.SHOULDER,
        InventorySlots.MELEE,
        InventorySlots.HEADGEAR,
        InventorySlots.MASK,
        InventorySlots.EYEWEAR,
        InventorySlots.GLOVES,
        InventorySlots.ARMBAND,
        InventorySlots.BODY,
        InventorySlots.VEST,
        InventorySlots.BACK,
        InventorySlots.HIPS,
        InventorySlots.LEGS,
        InventorySlots.FEET
    }
Referenced by GetAttachmentSlotsArray(), and GetPathFromSlotID().
m_ConfigArrayNames
ref array<string> m_ConfigArrayNames static
Initial value:
= {
        "shoulder",
        "melee",
        "headgear",
        "mask",
        "eyewear",
        "gloves",
        "armband",
        "top",
        "vests",
        "backpacks",
        "hips",
        "bottom",
        "shoe"
    }
Definition at line 1085 of file gameplay.c.
Referenced by GetConfigArrayNames(), and GetPathFromSlotID().
m_Path
const string m_Path = "cfgCharacterCreation" static
Definition at line 1101 of file gameplay.c.
Referenced by GetPathFromSlotID().
NullStringArray
class MeleeCombatData NullStringArray[1] = { "" }
Object
private void Object
PROGRESS_FINISH
const int PROGRESS_FINISH = 1
Definition at line 377 of file gameplay.c.
Referenced by LoadProgressUpdate().
PROGRESS_PROGRESS
const int PROGRESS_PROGRESS = 2
Definition at line 378 of file gameplay.c.
Referenced by LoadProgressUpdate().
PROGRESS_START
PlayerIdentity PROGRESS_START = 0
Referenced by LoadProgressUpdate().
PROGRESS_UPDATE
const int PROGRESS_UPDATE = 3
Definition at line 379 of file gameplay.c.
Referenced by LoadProgressUpdate().
ReadValue
class OptionsAccessEvents ReadValue