DayzKode: P:/scripts/5_mission/DayZ/gui/gesturesmenu.c File Reference
gesturesmenu.c File Reference
Classes
class UIScriptedMenu
Enumerations
enum GestureCategories {
CATEGORIES , CATEGORY_1 , CATEGORY_2 , CATEGORY_3 ,
CATEGORY_4 , CATEGORY_5 , CONSOLE_GESTURES
}
Functions
void GestureMenuItem (int id, string name, GestureCategories category)
string GetBoundButtonText ()
bool GetCanPerformEmote ()
GestureCategories GetCategory ()
int GetID ()
string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
Widget GetRadialItemCard ()
void SetCanPerformEmote (bool state)
void SetRadialItemCard (Widget widget)
Variables
protected bool m_CanPerformEmote
protected GestureCategories m_Category
protected EmoteBase m_EmoteClass
enum GestureCategories m_ID
protected string m_Name
protected Widget m_RadialMenuItemCard
protected Widget m_RadialMenuSelector
Enumeration Type Documentation
GestureCategories
enum GestureCategories
Enumerator
CATEGORIES
CATEGORY_1
CATEGORY_2
CATEGORY_3
CATEGORY_4
CATEGORY_5
CONSOLE_GESTURES
Definition at line 1 of file gesturesmenu.c.
{
    CATEGORIES,             //special category selection
    CATEGORY_1,
    CATEGORY_2,
    CATEGORY_3,
    CATEGORY_4,
    CATEGORY_5,
    CONSOLE_GESTURES
}
Function Documentation
GestureMenuItem()
void GestureMenuItem (int id, string name, GestureCategories category)
Definition at line 23 of file gesturesmenu.c.
    {
        m_ID                = id;
        m_Name              = name;
        m_Category          = category;
        m_CanPerformEmote   = true;
        PlayerBase player;
        if (Class.CastTo(player,GetGame().GetPlayer()) && category != GestureCategories.CATEGORIES)
        {
            m_EmoteClass = player.GetEmoteManager().GetNameEmoteMap().Get(id);
        }
    }
References Class::CastTo(), GetGame(), GetPlayer(), m_CanPerformEmote, m_Category, m_EmoteClass, m_ID, m_Name, and name.
Referenced by UIScriptedMenu::CreateGestureContent(), UIScriptedMenu::ExecuteSelectedCategory(), UIScriptedMenu::ExecuteSelectedItem(), UIScriptedMenu::GetGestureItems(), UIScriptedMenu::MarkSelected(), and UIScriptedMenu::UnmarkSelected().
GetBoundButtonText()
string GetBoundButtonText ()
Definition at line 42 of file gesturesmenu.c.
    {
        string ret = "";
        if (GetGame().GetInput().IsEnabledMouseAndKeyboardEvenOnServer() && m_EmoteClass && m_EmoteClass.GetInputActionName() != "")
        {
            map<int,ref TStringArray> button_map = InputUtils.GetComboButtonNamesFromInput(m_EmoteClass.GetInputActionName(), EInputDeviceType.MOUSE_AND_KEYBOARD);
            if (button_map && button_map.Count() > 0)
            {
                TStringArray buttons;
                for (int j = 0; j < button_map.Count(); j++)
                {
                    if (j > 0)
                    {
                        ret += "; ";
                    }
                    buttons = button_map.GetElement(j);
                    for (int i = 0; i < buttons.Count(); i++)
                    {
                        if (i > 0)
{
                            ret += " + ";
                        }
                        ret += buttons[i];
                    }
                }
            }
        }
        return ret;
    }
References InputUtils::GetComboButtonNamesFromInput(), GetGame(), GetInput(), EmoteBase::GetInputActionName(), and m_EmoteClass.
GetCanPerformEmote()
bool GetCanPerformEmote ()
Definition at line 100 of file gesturesmenu.c.
    {
        return m_CanPerformEmote;
    }
References m_CanPerformEmote.
GetCategory()
GestureCategories GetCategory ()
Definition at line 80 of file gesturesmenu.c.
    {
        return m_Category;
    }
References m_Category.
Referenced by OnErrorThrown().
GetID()
int GetID ()
Definition at line 75 of file gesturesmenu.c.
    {
        return m_ID;
    }
References m_ID.
GetRadialItemCard()
Widget GetRadialItemCard ()
Definition at line 85 of file gesturesmenu.c.
    {
        return m_RadialMenuItemCard;
    }
References m_RadialMenuItemCard.
SetCanPerformEmote()
void SetCanPerformEmote (bool state)
Definition at line 95 of file gesturesmenu.c.
    {
        m_CanPerformEmote = state;
    }
References m_CanPerformEmote.
SetRadialItemCard()
void SetRadialItemCard (Widget widget)
Definition at line 90 of file gesturesmenu.c.
    {
        m_RadialMenuItemCard = widget;
    }
References m_RadialMenuItemCard.
Variable Documentation
m_CanPerformEmote
protected bool m_CanPerformEmote
Definition at line 18 of file gesturesmenu.c.
Referenced by GestureMenuItem(), GetCanPerformEmote(), and SetCanPerformEmote().
m_Category
protected GestureCategories m_Category
Definition at line 16 of file gesturesmenu.c.
m_EmoteClass
protected EmoteBase m_EmoteClass
Definition at line 17 of file gesturesmenu.c.
Referenced by GestureMenuItem(), and GetBoundButtonText().
m_ID
enum GestureCategories m_ID
m_Name
protected string m_Name
Definition at line 15 of file gesturesmenu.c.
m_RadialMenuItemCard
protected Widget m_RadialMenuItemCard
Definition at line 21 of file gesturesmenu.c.
Referenced by GetRadialItemCard(), and SetRadialItemCard().
m_RadialMenuSelector
protected Widget m_RadialMenuSelector
Definition at line 20 of file gesturesmenu.c.