DayzKode: Enforce Script profiling API
Enforce Script profiling API
Classes
class EnProfiler
Set of methods for accessing script profiling data.
Typedefs
typedef Param2< int, typename > EnProfilerCountClassPair
typedef Param2< int, string > EnProfilerCountFuncPair
typedef Param2< float, typename > EnProfilerTimeClassPair
typedef Param2< float, string > EnProfilerTimeFuncPair
Enumerations
enum EnProfilerEnabledFlags { NONE = 0 , DIAG , SCRP , SCRC }
There are 3 states which can be toggled that governs whether script profiling is enabled or not.
enum EnProfilerFlags { NONE = 0 , RESET , RECURSIVE , ALL }
Flags that influences the behaviour of the EnProfiler API, applied through ...Flags functions.
enum EnProfilerModule {
CORE , GAMELIB , GAME , WORLD ,
MISSION , MISSION_CUSTOM , ERROR
}
Current base scripted modules.
Functions
static proto void EnProfiler::Enable (bool enable, bool immediate=false, bool sessionReset=true)
Enable the gathering of script profiling data.
static proto int EnProfiler::IsEnabled ()
Return if script profiling is enabled.
static bool EnProfiler::IsEnabledC ()
Return if script profiling is actually turned on inside of the script context.
static bool EnProfiler::IsEnabledD ()
Return if script profiling is enabled through [DM].
static bool EnProfiler::IsEnabledP ()
Return if script profiling is enabled through EnProfiler.
static proto void EnProfiler::ResetSession (bool fullReset=false)
Perform [SR], clearing SessionFrame, ProfiledSessionFrames, [SD] and [PD] (except for [CI])
static proto void EnProfiler::SortData ()
The internal sorting that happens at the end of the frame (so it is NOT necessary to call this manually) to supply Get...Per... functions.
EnProfilerFlags
Set of functions to configure the currently active EnProfilerFlags
static proto int EnProfiler::SetFlags (int flags, bool sessionReset=true)
Override the currently used set of EnProfilerFlags across the API.
static proto int EnProfiler::GetFlags ()
Get the currently used flags across the API.
static proto bool EnProfiler::IsFlagsSet (int flags)
Check if the flags are set.
static proto int EnProfiler::AddFlags (int flags, bool sessionReset=true)
Add flags to the currently used set of EnProfilerFlags across the API.
static proto int EnProfiler::RemoveFlags (int flags, bool sessionReset=true)
Remove flags from the currently used set of EnProfilerFlags across the API.
static proto int EnProfiler::ClearFlags (bool sessionReset=true)
Remove all flags from the currently used set of EnProfilerFlags across the API.
EnProfilerModule
Set of functions to configure the currently profiled EnProfilerModule
static proto void EnProfiler::SetModule (EnProfilerModule module, bool sessionReset=true)
Set the module to be profiled.
static proto EnProfilerModule EnProfiler::GetModule ()
Get the currently profiled module.
static proto owned string EnProfiler::ModuleToName (EnProfilerModule module)
Helper to convert EnProfilerModule to string.
static proto bool EnProfiler::NameToModule (string moduleName, out EnProfilerModule module)
Convert string to EnProfilerModule.
static proto void EnProfiler::SetInterval (int interval, bool sessionReset=true)
Set the interval for the [SD] to update.
static proto int EnProfiler::GetInterval ()
Get the currently set interval.
static proto void EnProfiler::SetTimeResolution (int resolution)
Set the resolution of the fetched Time data.
static proto int EnProfiler::GetTimeResolution ()
Get the currently set time resolution.
static proto void EnProfiler::EnableAverage (bool enable)
Enable/disable returning calculated averages.
static proto bool EnProfiler::IsAverage ()
Check if returning of average data is enabled.
static proto void EnProfiler::Dump ()
Print out [SD] to script log.
Frame data
Set of functions to obtain information about frame counts
static proto int EnProfiler::GetGameFrame ()
Get the total amount of frames passed.
static proto int EnProfiler::GetSessionFrame ()
Get the total amount of frames in this profiling session.
static proto int EnProfiler::GetTotalFrames ()
Get the total amount of frames across all profiling session.
static proto int EnProfiler::GetProfiledSessionFrames ()
Get the total amount of frames profiled in this profiling session.
static proto int EnProfiler::GetProfiledFrames ()
Get the total amount of frames profiled across all profiling session.
Sorted data
Set of functions to obtain [SD]
Warning
Data is appended to the array, it will not clear any previous data already existing in the array
Note
Read SortData as well for more information regarding [SD]
static proto void EnProfiler::GetTimePerClass (notnull out array< ref EnProfilerTimeClassPair > outArr, int count=int.MAX)
Obtain [SD] for Time Per Class.
static proto void EnProfiler::GetAllocationsPerClass (notnull out array< ref EnProfilerCountClassPair > outArr, int count=int.MAX)
Obtain [SD] for Allocations Per Class.
static proto void EnProfiler::GetInstancesPerClass (notnull out array< ref EnProfilerCountClassPair > outArr, int count=int.MAX)
Obtain [SD] for Instances Per Class.
static proto void EnProfiler::GetTimePerFunc (notnull out array< ref EnProfilerTimeFuncPair > outArr, int count=int.MAX)
Obtain [SD] for Time Per Function.
static proto void EnProfiler::GetCountPerFunc (notnull out array< ref EnProfilerCountFuncPair > outArr, int count=int.MAX)
Obtain [SD] for Count Per Function.
Specific data
Set of functions to obtain specific data
static proto float EnProfiler::GetTimeOfClass (typename clss, bool immediate=false)
Obtain [SD] or [PD] regarding the time a specific class consumed.
static proto int EnProfiler::GetAllocationsOfClass (typename clss, bool immediate=false)
Obtain [SD] or [PD] regarding the allocations of a specific class.
static proto int EnProfiler::GetInstancesOfClass (typename clss, bool immediate=false)
Obtain [SD] or [PD] regarding the [CI] of a specific class.
static proto float EnProfiler::GetTimeOfFunc (string funct, typename clss, bool immediate=false)
Obtain [SD] or [PD] regarding the time consumed by a specific function.
static proto float EnProfiler::GetTimeOfFuncG (string funct, bool immediate, bool immediate=false)
Obtain [SD] or [PD] regarding the time consumed by a specific global function.
static proto int EnProfiler::GetCountOfFunc (string funct, typename clss, bool immediate=false)
Obtain [SD] or [PD] regarding the amount of times a specific function was called.
static proto int EnProfiler::GetCountOfFuncG (string funct, bool immediate=false)
Obtain [SD] or [PD] regarding the amount of times a specific function was called.
Misc
Set of helper functions
static bool EnProfiler::RequestImmediateData ()
Helper method to ascertain the profiler will record [PD] right after this call.
Detailed Description
Warning
Only available on developer and diag builds
Typedef Documentation
EnProfilerCountClassPair
typedef Param2<int, typename> EnProfilerCountClassPair
Definition at line 56 of file enprofiler.c.
EnProfilerCountFuncPair
typedef Param2<int, string> EnProfilerCountFuncPair
Definition at line 59 of file enprofiler.c.
EnProfilerTimeClassPair
typedef Param2<float, typename> EnProfilerTimeClassPair
Definition at line 55 of file enprofiler.c.
EnProfilerTimeFuncPair
typedef Param2<float, string> EnProfilerTimeFuncPair
Definition at line 58 of file enprofiler.c.
Enumeration Type Documentation
EnProfilerEnabledFlags
enum EnProfilerEnabledFlags
There are 3 states which can be toggled that governs whether script profiling is enabled or not.
Note
The reason for this is because when it is enabled in debug menu, or through this API without 'immediate', it will only be enabled the next frame
Enumerator
NONE
No flags.
No automatic destroying.
Flags to pass to ParticleSource.StopParticle.
Plain Effect base.
No flags, has value 0, so will count as false in conditions.
No flags
DIAG
Script profiling UI is enabled in WIN+ALT debug menu, when this is true, it will override SCRP.
SCRP
It has been set to being always enabled through EnProfiler (SCRipt Profiler)
SCRC
Whether profiling is currently truly happening (SCRipt Context)
Definition at line 43 of file enprofiler.c.
{
    NONE,
    DIAG,
    SCRP,
    SCRC,
};
EnProfilerFlags
enum EnProfilerFlags
Flags that influences the behaviour of the EnProfiler API, applied through ...Flags functions.
Enumerator
NONE
No flags.
No automatic destroying.
Flags to pass to ParticleSource.StopParticle.
Plain Effect base.
No flags, has value 0, so will count as false in conditions.
No flags
RESET
When present, will reset [PD] on sorting, otherwise will accumulate on top of it.
RECURSIVE
Whether to profile child modules.
ALL
All flags enabled.
Definition at line 8 of file enprofiler.c.
{
    NONE,
    RESET,
    RECURSIVE,
    ALL
};
EnProfilerModule
enum EnProfilerModule
Current base scripted modules.
Enumerator
CORE
1_Core
GAMELIB
2_GameLib
GAME
3_Game
WORLD
4_World
MISSION
5_Mission
MISSION_CUSTOM
init.c
ERROR
Can be returned from some methods.
Definition at line 21 of file enprofiler.c.
{
    CORE,
    GAMELIB,
    GAME,
    WORLD,
    MISSION,
    MISSION_CUSTOM,
    ERROR,
};
Function Documentation
AddFlags()
static proto int EnProfiler::AddFlags (int flags, bool sessionReset = true) static private
Add flags to the currently used set of EnProfilerFlags across the API.
Note
Simply a helper method to quickly add EnProfilerFlags
Parameters
flags int The combination of desired EnProfilerFlags to be added to the currently used set
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
Returns
int The currently used set of EnProfilerFlags after the function call
// In the case where the current set of EnProfilerFlags is EnProfilerFlags.RESET
EnProfiler.AddFlags(EnProfilerFlags.RECURSIVE);
// The resulting set of flags now will be EnProfilerFlags.RESET | EnProfilerFlags.RECURSIVE
// As the above is pretty much the same as the following
// EnProfiler.SetFlags(EnProfiler.GetFlags() | EnProfilerFlags.RECURSIVE);
// But a much cleaner and faster alternative (bitwise operations in script is ~10x slower than C++)
Referenced by EnProfilerTests::TestAddFlags().
ClearFlags()
static proto int EnProfiler::ClearFlags (bool sessionReset = true) static private
Remove all flags from the currently used set of EnProfilerFlags across the API.
Note
Simply a helper method to quickly remove all EnProfilerFlags
Parameters
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
Returns
int The currently used set of EnProfilerFlags after the function call
// In the case where the current set of EnProfilerFlags is EnProfilerFlags.RESET
EnProfiler.ClearFlags();
// The resulting set of flags now will be EnProfilerFlags.NONE
// As the above is pretty much the same as the following
// EnProfiler.SetFlags(EnProfilerFlags.NONE);
// But a much cleaner and implicit alternative
Referenced by EnProfilerTests::TestAddFlags(), and EnProfilerTests::TestClearFlags().
Dump()
static proto void EnProfiler::Dump () static private
Print out [SD] to script log.
EnProfiler.Dump();
Enable()
static proto void EnProfiler::Enable (bool enable, bool immediate = false, bool sessionReset = true) static private
Enable the gathering of script profiling data.
Note
DEFAULT: disabled (unless launched with "-profile", then it is default enabled)
This is separate from the one in [DM], so toggling it in [DM] will not affect this, and toggling it here will not affect [DM]
It will ignore the call if trying to set the current state, except when "immediate" is used
Parameters
enable bool Whether to enable or disable, if it was previously not enabled, it will cause [SR]
Note
Disabling does not cause [SR], so all data will stay intact
Parameters
immediate bool When true will instantly start/stop profiling, otherwise it will apply it at the end of the frame (to have one stable point in time)
Warning
Keep in mind that when using immediate, it will not be the data of the entire frame, which can skew data if not kept in mind
Parameters
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
// Simple enable, will start profiling the next frame
// Will cause [SR] if !IsEnabledP() before this call
EnProfiler.Enable(true);
// Immediate enable, will start profiling immediately
// Will cause [SR] if !IsEnabledP() before this call
EnProfiler.Enable(true, true);
// Immediate disable, will stop profiling immediately
// Disabling will never cause [SR], preserving data
EnProfiler.Enable(false, true);
// Simple disable, will not profile the next frame (but still finish profiling the current one)
// Disabling will never cause [SR], preserving data
EnProfiler.Enable(false);
Referenced by EnProfiler::RequestImmediateData(), EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncCountData(), EnProfilerTests::TestFuncTimeData(), EnProfilerTests::TestModule(), EnProfilerTests::TestToggling(), EnProfilerTests::TestTogglingImmediate(), and EnProfilerTests::~EnProfilerTests().
EnableAverage()
static proto void EnProfiler::EnableAverage (bool enable) static private
Enable/disable returning calculated averages.
Note
DEFAULT: false
When EnProfilerFlags.RESET flag is not present, it will divide by the session frame
When an interval is set, it will divide by the interval
Does not affect any data itself, only the fetching and displaying of it (therefore, no [SR] is ever triggered by this method)
[CI] will never be an average, it will always be the current count of the instance (allocations will be the value of how many times an instance is created)
Parameters
enable bool Whether to enable or disable
// For example, take the situation where we only reset every 60 frames
EnProfiler.AddFlags(EnProfilerFlags.RESET);
EnProfiler.SetInterval(60);
EnProfiler.EnableAverage(true);
// And a method is called once per frame, gathering the count of that function will be 1
// Or if a method is called twice per frame, gathering the count of that function will be 2
// Or if a method is 3 times every 3 frames, gathering the count of that function will be 1
// ...
// So you get the average amount of times the method is called per frame, out of the sample of 60 frames
GetAllocationsOfClass()
static proto int EnProfiler::GetAllocationsOfClass (typename clss , bool immediate = false) static private
Obtain [SD] or [PD] regarding the allocations of a specific class.
Parameters
clss typename Typename of desired class
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
int Allocations of the specified class
int allocationsOfClass = EnProfiler.GetAllocationsOfClass(StaticGetType(EPTHelperClass), true);
Referenced by EnProfilerTests::TestClassCountData().
GetAllocationsPerClass()
static proto void EnProfiler::GetAllocationsPerClass (notnull out array< ref EnProfilerCountClassPair > outArr, int count = int.MAX) static private
Obtain [SD] for Allocations Per Class.
Parameters
outArr array<ref EnProfilerCountClassPair> Array sorted by number of allocations of a class
count int The maximum amount of entries wanted
array<ref EnProfilerCountClassPair> allocPerClass = {};
EnProfiler.GetAllocationsPerClass(allocPerClass, 20);
GetCountOfFunc()
static proto int EnProfiler::GetCountOfFunc (string funct, typename clss , bool immediate = false) static private
Obtain [SD] or [PD] regarding the amount of times a specific function was called.
Parameters
funct string Function name
clss typename Typename of class the function belongs to
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
int Amount of calls to the specified function or -1 when function was not found
int callCountOfFunc = EnProfiler.GetCountOfFunc("StringFormat", StaticGetType(EnProfilerTests), true);
Referenced by EnProfilerTests::TestFuncCountData().
GetCountOfFuncG()
static proto int EnProfiler::GetCountOfFuncG (string funct, bool immediate = false) static private
Obtain [SD] or [PD] regarding the amount of times a specific function was called.
Parameters
funct string Function name
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
int Amount of calls to the specified function or -1 when function was not found
int callCountOfFunc = EnProfiler.GetCountOfFuncG("ErrorEx", true);
Referenced by EnProfilerTests::TestFuncCountData().
GetCountPerFunc()
static proto void EnProfiler::GetCountPerFunc (notnull out array< ref EnProfilerCountFuncPair > outArr, int count = int.MAX) static private
Obtain [SD] for Count Per Function.
Parameters
outArr array<ref EnProfilerCountFuncPair> Array sorted by amount of times a function was called
count int The maximum amount of entries wanted
array<ref EnProfilerCountFuncPair> countPerFunc = {};
EnProfiler.GetCountPerFunc(countPerFunc, 20);
GetFlags()
static proto int EnProfiler::GetFlags () static private
Get the currently used flags across the API.
Returns
int The currently used set of EnProfilerFlags
int flags = EnProfiler.GetFlags();
if (flags & EnProfilerFlags.RECURSIVE)
{
    Print("Currently profiling all modules.");
}
Referenced by EnProfilerTests::TestAddFlags(), EnProfilerTests::TestClearFlags(), EnProfilerTests::TestModule(), and EnProfilerTests::TestSetFlags().
GetGameFrame()
static proto int EnProfiler::GetGameFrame () static private
Get the total amount of frames passed.
Returns
int The total amount of frames passed
int gameFrame = EnProfiler.GetGameFrame();
GetInstancesOfClass()
static proto int EnProfiler::GetInstancesOfClass (typename clss , bool immediate = false) static private
Obtain [SD] or [PD] regarding the [CI] of a specific class.
Parameters
clss typename Typename of desired class
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
int [CI] of the specified class
int instancesOfClass = EnProfiler.GetInstancesOfClass(StaticGetType(EPTHelperClass), true);
Referenced by EnProfilerTests::TestClassCountData().
GetInstancesPerClass()
static proto void EnProfiler::GetInstancesPerClass (notnull out array< ref EnProfilerCountClassPair > outArr, int count = int.MAX) static private
Obtain [SD] for Instances Per Class.
Parameters
outArr array<ref EnProfilerCountClassPair> Array sorted by number of instances of a class
count int The maximum amount of entries wanted
array<ref EnProfilerCountClassPair> instancesPerClass = {};
EnProfiler.GetInstancesPerClass(instancesPerClass, 20);
GetInterval()
static proto int EnProfiler::GetInterval () static private
Get the currently set interval.
Returns
int The currently set interval
int currentInterval = EnProfiler.GetInterval();
GetModule()
static proto EnProfilerModule EnProfiler::GetModule () static private
Get the currently profiled module.
Returns
EnProfilerModule The currently profiled module
EnProfilerModule module = EnProfiler.GetModule();
Referenced by EnProfilerTests::TestModule().
GetProfiledFrames()
static proto int EnProfiler::GetProfiledFrames () static private
Get the total amount of frames profiled across all profiling session.
Note
This will only differ from GetTotalFrames when there was an Interval set at some point
Returns
int The total amount of frames profiled across all profiling session
int totalProfiledFrames = EnProfiler.GetProfiledFrames();
GetProfiledSessionFrames()
static proto int EnProfiler::GetProfiledSessionFrames () static private
Get the total amount of frames profiled in this profiling session.
Note
This will only differ from GetSessionFrame when there is an Interval set
Returns
int The total amount of frames profiled in this profiling session
int profiledSessionFrames = EnProfiler.GetProfiledSessionFrames();
GetSessionFrame()
static proto int EnProfiler::GetSessionFrame () static private
Get the total amount of frames in this profiling session.
Note
This will only differ from GetProfiledSessionFrames when there is an Interval set
Returns
int The total amount of frames in this profiling session
int sessionFrame = EnProfiler.GetSessionFrame();
GetTimeOfClass()
static proto float EnProfiler::GetTimeOfClass (typename clss , bool immediate = false) static private
Obtain [SD] or [PD] regarding the time a specific class consumed.
Parameters
clss typename Typename of desired class
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
float Time consumed by the specified class
// Consider the class
EPTHelperClass clss = new EPTHelperClass();
// Some functions being called here...
// Gathering of data can be done through
float timeOfClass = EnProfiler.GetTimeOfClass(clss.Type(), true);
// Or when you have no variable/reference
float timeOfClass2 = EnProfiler.GetTimeOfClass(StaticGetType(EPTHelperClass), true);
Referenced by EnProfilerTests::TestClassTimeData().
GetTimeOfFunc()
static proto float EnProfiler::GetTimeOfFunc (string funct, typename clss , bool immediate = false) static private
Obtain [SD] or [PD] regarding the time consumed by a specific function.
Parameters
funct string Function name
clss typename Typename of class the function belongs to
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
float Time consumed by the specified function or -1 when function was not found
float timeOfFunc = EnProfiler.GetTimeOfFunc("StringFormat", StaticGetType(EnProfilerTests), true);
Referenced by EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
GetTimeOfFuncG()
static proto float EnProfiler::GetTimeOfFuncG (string funct, bool immediate, bool immediate = false) static private
Obtain [SD] or [PD] regarding the time consumed by a specific global function.
Parameters
funct string Function name
immediate bool When true, it will pull from [SD], when false it will pull from [PD]
Returns
float Time consumed by the specified function or -1 when function was not found
float timeOfFunc = EnProfiler.GetTimeOfFuncG("ErrorEx", true);
GetTimePerClass()
static proto void EnProfiler::GetTimePerClass (notnull out array< ref EnProfilerTimeClassPair > outArr, int count = int.MAX) static private
Obtain [SD] for Time Per Class.
Parameters
outArr array<ref EnProfilerTimeClassPair> Array sorted by time consumed by a class
count int The maximum amount of entries wanted
// In this example the array will be filled with the 20 most time intensive classes
// If there are less than 20 classes which consumed time, it will output that number of classes instead
array<ref EnProfilerTimeClassPair> timePerClass = {};
EnProfiler.GetTimePerClass(timePerClass, 20);
// In this example the array will be filled with all classes sorted by time
array<ref EnProfilerTimeClassPair> timePerClass2 = {};
EnProfiler.GetTimePerClass(timePerClass2);
Referenced by EnProfilerTests::TestModule().
GetTimePerFunc()
static proto void EnProfiler::GetTimePerFunc (notnull out array< ref EnProfilerTimeFuncPair > outArr, int count = int.MAX) static private
Obtain [SD] for Time Per Function.
Parameters
outArr array<ref EnProfilerTimeFuncPair> Array sorted by time consumed by a function
count int The maximum amount of entries wanted
array<ref EnProfilerTimeFuncPair> timePerFunc = {};
EnProfiler.GetTimePerFunc(timePerFunc, 20);
Referenced by EnProfilerTests::TestModule().
GetTimeResolution()
static proto int EnProfiler::GetTimeResolution () static private
Get the currently set time resolution.
Returns
int The currently set resolution
int currentTimeResolution = EnProfiler.GetTimeResolution();
Referenced by EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
GetTotalFrames()
static proto int EnProfiler::GetTotalFrames () static private
Get the total amount of frames across all profiling session.
Note
This will only differ from GetProfiledFrames when there was an Interval set at some point
Returns
int The total amount of frames across all profiling session
int totalFrames = EnProfiler.GetTotalFrames();
IsAverage()
static proto bool EnProfiler::IsAverage () static private
Check if returning of average data is enabled.
Returns
bool Whether returning of average data is enabled
bool isDataAverage = EnProfiler.IsAverage();
IsEnabled()
static proto int EnProfiler::IsEnabled () static private
Return if script profiling is enabled.
Note
Helper methods below
Returns
int Flags regarding the current state
int isScriptProfilingEnabled = EnProfiler.IsEnabled();
Referenced by EnProfiler::IsEnabledC(), EnProfiler::IsEnabledD(), and EnProfiler::IsEnabledP().
IsEnabledC()
static bool EnProfiler::IsEnabledC () inline static private
Return if script profiling is actually turned on inside of the script context.
Note
When using "-profile" launch parameter, it will enable it through EnProfiler, so this will return true
Returns
bool Whether script is being profiled as of this moment
bool isScriptProfilingEnabled = EnProfiler.IsEnabledC();
Definition at line 152 of file enprofiler.c.
    {
        return (IsEnabled() & EnProfilerEnabledFlags.SCRC);
    }
References EnProfiler::IsEnabled().
Referenced by EnProfilerTests::EnProfilerTests(), EnProfiler::RequestImmediateData(), and EnProfilerTests::TestTogglingImmediate().
IsEnabledD()
static bool EnProfiler::IsEnabledD () inline static private
Return if script profiling is enabled through [DM].
Returns
bool Whether script profiling is enabled through [DM]
bool isScriptProfilingDiagEnabled = EnProfiler.IsEnabledD();
Definition at line 124 of file enprofiler.c.
    {
        return (IsEnabled() & EnProfilerEnabledFlags.DIAG);
    }
References EnProfiler::IsEnabled().
IsEnabledP()
static bool EnProfiler::IsEnabledP () inline static private
Return if script profiling is enabled through EnProfiler.
Note
When using "-profile" launch parameter, it will enable it through EnProfiler, so this will return true
Returns
bool Whether script profiling is enabled through script profiler
bool isScriptProfilingToggleEnabled = EnProfiler.IsEnabledP();
Definition at line 138 of file enprofiler.c.
    {
        return (IsEnabled() & EnProfilerEnabledFlags.SCRP);
    }
References EnProfiler::IsEnabled().
Referenced by EnProfilerTests::TestToggling().
IsFlagsSet()
static proto bool EnProfiler::IsFlagsSet (int flags) static private
Check if the flags are set.
Note
Is effectively the same as the code displayed in GetFlags example, but without the bitwise operation
Parameters
flags int The combination of EnProfilerFlags to check if present
Returns
bool If the flags are set
if (EnProfiler.IsFlagsSet(EnProfilerFlags.ALL))
{
    Print("Currently all flags are enabled.");
}
if (EnProfiler.IsFlagsSet(EnProfilerFlags.RECURSIVE))
{
    Print("Currently profiling all modules.");
}
ModuleToName()
static proto owned string EnProfiler::ModuleToName (EnProfilerModule module) static private
Helper to convert EnProfilerModule to string.
Parameters
module EnProfilerModule The module to get the name of
Returns
string The name of the module
string moduleName = EnProfiler.ModuleToName(EnProfilerModule.GAME);
NameToModule()
static proto bool EnProfiler::NameToModule (string moduleName, out EnProfilerModule module) static private
Convert string to EnProfilerModule.
Parameters
moduleName string The name of the module
module EnProfilerModule The enum value of the module or EnProfilerModule.ERROR if not found
Returns
bool Whether the module was found
// Get the name of the module of the current class
string nameOfCurrentModule = Type().GetModule();
EnProfilerModule module;
// Convert it to the enum value
if (EnProfiler.NameToModule(nameOfCurrentModule, module))
{
    EnProfiler.SetModule(module);
}
else
{
    ErrorEx(string.Format("Could not find EnProfilerModule: %1", nameOfCurrentModule));
}
Referenced by EnProfilerTests::TestModule().
RemoveFlags()
static proto int EnProfiler::RemoveFlags (int flags, bool sessionReset = true) static private
Remove flags from the currently used set of EnProfilerFlags across the API.
Note
Simply a helper method to quickly remove EnProfilerFlags
Parameters
flags int The combination of desired EnProfilerFlags to be added to the currently used set
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
Returns
int The currently used set of EnProfilerFlags after the function call
// In the case where the current set of EnProfilerFlags is EnProfilerFlags.RESET
EnProfiler.RemoveFlags(EnProfilerFlags.RESET);
// The resulting set of flags now will be EnProfilerFlags.NONE
// As the above is pretty much the same as the following
// EnProfiler.SetFlags(EnProfiler.GetFlags() & ~EnProfilerFlags.RECURSIVE);
// But a much cleaner and faster alternative (bitwise operations in script is ~10x slower than C++)
Referenced by EnProfilerTests::TestClearFlags(), and EnProfilerTests::TestModule().
RequestImmediateData()
static bool EnProfiler::RequestImmediateData () inline static private
Helper method to ascertain the profiler will record [PD] right after this call.
Returns
bool Whether it was enabled before or not
bool wasEnabled = EnProfiler.RequestImmediateData();
Definition at line 745 of file enprofiler.c.
    {
        // I only care if it is actually profiling right now, so C
        bool wasEnabled = IsEnabledC();
        if (!wasEnabled)
        {
            // I want the data, and I want it now, so immediate
            Enable(true, true);
        }
        return wasEnabled;
    }
References EnProfiler::Enable(), and EnProfiler::IsEnabledC().
Referenced by EnProfilerTests::TestClassCountData(), EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncCountData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
ResetSession()
static proto void EnProfiler::ResetSession (bool fullReset = false) static private
Perform [SR], clearing SessionFrame, ProfiledSessionFrames, [SD] and [PD] (except for [CI])
Note
Can also be triggered by a variety of other functions in this API
When triggered by the other functions, it will call with fullReset = false
Parameters
fullReset bool Whether to clear [PD] of all modules, when false it will only clear the [PD] according to current settings
// Considering the settings: SetFlags(EnProfilerFlags.NONE) and SetModule(EnProfilerModule.GAME)
// The following call will only clear [PD] of 3_Game
EnProfiler.ResetSession();
// Considering the settings: SetFlags(EnProfilerFlags.RECURSIVE) and SetModule(EnProfilerModule.WORLD)
// The following call will clear [PD] of 3_Game, 4_World, 5_Mission and their children
EnProfiler.ResetSession();
// The following call resets [PD] across all modules
EnProfiler.ResetSession(true);
Referenced by EnProfilerTests::TestModule().
SetFlags()
static proto int EnProfiler::SetFlags (int flags, bool sessionReset = true) static private
Override the currently used set of EnProfilerFlags across the API.
Note
DEFAULT: EnProfilerFlags.ALL
Parameters
flags int The combination of desired EnProfilerFlags to override the currently used set
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
Returns
int The currently used set of EnProfilerFlags after the function call
// No RESET flag, [PD] will be accumulated across frames
// No RECURSIVE flag, only the curently profiled module will be sorted
EnProfiler.SetFlags(EnProfilerFlags.NONE);
// RESET flag, [PD] will be reset after sorting
// No RECURSIVE flag, only the curently profiled module will be sorted
EnProfiler.SetFlags(EnProfilerFlags.RESET);
// RESET flag, [PD] will be reset after sorting
// RECURSIVE flag, all modules will be sorted
EnProfiler.SetFlags(EnProfilerFlags.ALL);
Referenced by EnProfilerTests::TestAddFlags(), EnProfilerTests::TestClearFlags(), EnProfilerTests::TestModule(), and EnProfilerTests::TestSetFlags().
SetInterval()
static proto void EnProfiler::SetInterval (int interval, bool sessionReset = true) static private
Set the interval for the [SD] to update.
Note
DEFAULT: 0
[DM] has the following values: {0, 5, 10, 20, 30, 50, 60, 120, 144}; When an interval not part of this list is set, [DM] will be set to "CUSTOM_INTERVAL"
Does not affect the gathering of [PD], this will happen continuously as the profiling is enabled
This also delays the [SR] caused by EnProfilerFlags.RESET
Parameters
interval int Amount of frames to wait before [SD] is updated
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
// This will make it so that [SD] is updated every 60 frames
EnProfiler.SetInterval(60);
SetModule()
static proto void EnProfiler::SetModule (EnProfilerModule module, bool sessionReset = true) static private
Set the module to be profiled.
Note
DEFAULT: EnProfilerModule.CORE
When session reset is enabled, it will only reset the module which it is currently being set to, previous module data will be untouched
Parameters
module EnProfilerModule The module to profile
sessionReset bool When set to false, no [SR] will trigger, regardless of situation
EnProfiler.SetModule(EnProfilerModule.WORLD);
Referenced by EnProfilerTests::TestModule().
SetTimeResolution()
static proto void EnProfiler::SetTimeResolution (int resolution) static private
Set the resolution of the fetched Time data.
Note
DEFAULT: 100000
[DM] has the following values: {100000, 1000000, 1, 10, 100, 1000, 10000}; These are the only values available, otherwise it will round up to one in the list
Does not affect any data itself, only the fetching and displaying of it (therefore, no [SR] is ever triggered by this method)
Parameters
resolution int The nth resolution of a second
// Have all time being reported in 1 second
EnProfiler.SetTimeResolution(1);
// Have all time being reported in 1000th of a second (ms)
EnProfiler.SetTimeResolution(1000);
Referenced by EnProfilerTests::TestClassTimeData(), EnProfilerTests::TestFuncTimeData(), and EnProfilerTests::TestModule().
SortData()
static proto void EnProfiler::SortData () static private
The internal sorting that happens at the end of the frame (so it is NOT necessary to call this manually) to supply Get...Per... functions.
Note
This will clear the previous [SD] and sort the [PD] currently available at this moment
Flags apply to this
Warning
Keep in mind that EnProfilerFlags.RESET will clear all [PD] after this is called
// Sorting all the currently available [PD], populating [SD]
EnProfiler.SortData();
// If flag EnProfilerFlags.RESET is enabled, then this will return 0 now even if it has been called, as [PD] has been cleared
// This goes for any Get...Of... function (Except for [CI], the counter persists)
EnProfiler.GetTimeOfFunc("Sleep", EnProfilerTests, true);
Referenced by EnProfilerTests::TestModule().