DayzKode: Diag menu API definition
Diag menu API definition
Debug utilities » Debug Shape API definition
Classes
class DiagMenu
Functions
static proto native bool DiagMenu::GetBool (int id, bool reverse=false)
static proto native float DiagMenu::GetRangeValue (int id)
static proto native int DiagMenu::GetValue (int id)
static proto native void DiagMenu::RegisterBool (int id, string shortcut, string name, string parent, bool reverse=false)
static proto native void DiagMenu::RegisterItem (int id, string shortcut, string name, string parent, string values)
static proto native void DiagMenu::RegisterMenu (int id, string name, string parent)
static proto native void DiagMenu::RegisterRange (int id, string shortcut, string name, string parent, string valuenames)
static proto native void DiagMenu::SetRangeValue (int id, float value)
static proto native void DiagMenu::SetValue (int id, int value)
static proto native void DiagMenu::Unregister (int id)
Variables
NEARESTCONTACT ONLYSTATIC ONLYDYNAMIC ONLYWATER ALLOBJECTS
ERROR
FIRSTCONTACT
INFO
WARNING
Detailed Description
Function Documentation
GetBool()
static proto native bool DiagMenu::GetBool (int id, bool reverse = false) static private
Referenced by ApplyEyeAcco(), CalculateEyeAccoTarget(), DepleteStamina(), MissionBase::DisplayHairDebug(), ManBase::EEHitBy(), ManBase::EOnPostFrame(), GetMeleeTargetEx(), Hologram::GetProjectionEntityPosition(), Hologram::IsCollidingBBox(), BaseBuildingBase::OnDebugSpawnBuildExcludes(), Managed::OnScheduledTick(), SymptomManager::OnTick(), MissionBase::OnUpdate(), ProcessLighting(), Tick(), ScriptedWidgetEventHandler::Update(), Update(), UIScriptedMenu::Update(), and ActionMenu::UpdateWidgets().
GetRangeValue()
static proto native float DiagMenu::GetRangeValue (int id) static private
GetValue()
static proto native int DiagMenu::GetValue (int id) static private
Referenced by CheckShowMode(), CommandHandler(), CommandHandlerDebug(), HeadingModel(), and MissionBase::ShowHairDebugValues().
RegisterBool()
static proto native void DiagMenu::RegisterBool (int id, string shortcut, string name, string parent, bool reverse = false) static private
RegisterItem()
static proto native void DiagMenu::RegisterItem (int id, string shortcut, string name, string parent, string values) static private
RegisterMenu()
static proto native void DiagMenu::RegisterMenu (int id, string name, string parent) static private
RegisterRange()
static proto native void DiagMenu::RegisterRange (int id, string shortcut, string name, string parent, string valuenames) static private
range value, are defined in format "min,max,startValue,step" -> e.g. "-2, 2, 0, 0.1"
SetRangeValue()
static proto native void DiagMenu::SetRangeValue (int id, float value) static private
SetValue()
static proto native void DiagMenu::SetValue (int id, int value) static private
Referenced by SetModifiers().
Unregister()
static proto native void DiagMenu::Unregister (int id) static private
Variable Documentation
ALLOBJECTS
ALLOBJECTS
Definition at line 5 of file endebug.c.
ERROR
ERROR
Definition at line 2 of file endebug.c.
FIRSTCONTACT
FIRSTCONTACT
Definition at line 0 of file endebug.c.
INFO
INFO
Definition at line 0 of file endebug.c.
WARNING
WARNING
Definition at line 1 of file endebug.c.