DayzKode: World
World
World
Modules
Camera
Typedefs
typedef int[] WorldHandle
Functions
proto native IEntity FindEntityByID (IEntity worldEnt, int ID)
proto native IEntity FindEntityByName (IEntity worldEnt, string name)
proto native IEntity GetActiveEntity (IEntity worldEntity, int index)
returns active entity
proto native int GetNumActiveEntities (IEntity worldEntity)
returns number of active (simulated) Entities in the world
proto native float GetWorldTime ()
proto native WorldHandle SetCurrentWorld (WorldHandle world)
Detailed Description
Typedef Documentation
WorldHandle
typedef int [] WorldHandle
Definition at line 12 of file enworld.c.
Function Documentation
FindEntityByID()
proto native IEntity FindEntityByID (IEntity worldEnt, int ID)
FindEntityByName()
proto native IEntity FindEntityByName (IEntity worldEnt, string name)
GetActiveEntity()
proto native IEntity GetActiveEntity (IEntity worldEntity, int index)
returns active entity
GetNumActiveEntities()
proto native int GetNumActiveEntities (IEntity worldEntity)
returns number of active (simulated) Entities in the world
GetWorldTime()
proto native float GetWorldTime ()
Referenced by HumanCommandActionCallback::OnAnimationEvent(), DayZCreatureAnimScriptDebug::OnAnimationEvent(), and RandomizedDeviation().
SetCurrentWorld()
proto native WorldHandle SetCurrentWorld (WorldHandle world)
Sets current world. It allows to work with entities outside world processing return previous world