DayzKode: Particle effect API
Particle effect API
Visual objects » Mesh object (XOB)
Enumerations
enum EmitorParam {
CONEANGLE , EMITOFFSET , VELOCITY , VELOCITY_RND ,
AVELOCITY , SIZE , STRETCH , RANDOM_ANGLE ,
RANDOM_ROT , AIR_RESISTANCE , AIR_RESISTANCE_RND , GRAVITY_SCALE ,
GRAVITY_SCALE_RND , BIRTH_RATE , BIRTH_RATE_RND , LIFETIME ,
LIFETIME_RND , LIFETIME_BY_ANIM , ANIM_ONCE , RAND_FRAME ,
EFFECT_TIME , REPEAT , CURRENT_TIME , ACTIVE_PARTICLES ,
SORT , WIND , SPRING
}
Functions
proto native int GetParticleCount (notnull IEntity ent)
proto int GetParticleEmitorCount (notnull IEntity ent)
proto int GetParticleEmitors (notnull IEntity ent, out string emitors[], int max)
proto void GetParticleParm (notnull IEntity ent, int emitor, EmitorParam parameter, out void value)
proto void GetParticleParmOriginal (notnull IEntity ent, int emitor, EmitorParam parameter, out void value)
proto bool HasActiveParticle (notnull IEntity ent)
proto native void ResetParticlePosition (notnull IEntity ent)
proto native void RestartParticle (notnull IEntity ent)
proto void SetParticleParm (notnull IEntity ent, int emitor, EmitorParam parameter, void value)
Detailed Description
Enumeration Type Documentation
EmitorParam
enum EmitorParam
Enumerator
CONEANGLE
Vector3 R/W.
EMITOFFSET
Vector3 R/W.
VELOCITY
Float R/W.
VELOCITY_RND
Float R/W.
AVELOCITY
Float R/W.
SIZE
Float R/W.
STRETCH
Float R/W.
RANDOM_ANGLE
begin with random rotation. Bool R/W
RANDOM_ROT
rotate in random direction. Bool R/W
AIR_RESISTANCE
Float R/W.
AIR_RESISTANCE_RND
Float R/W.
GRAVITY_SCALE
Float R/W.
GRAVITY_SCALE_RND
Float R/W.
BIRTH_RATE
Float R/W.
BIRTH_RATE_RND
Float R/W.
LIFETIME
Float R/W.
LIFETIME_RND
Float R/W.
LIFETIME_BY_ANIM
Bool R/W.
ANIM_ONCE
Bool R/W.
RAND_FRAME
Bool R/W.
EFFECT_TIME
efector's total time. Float R/W
REPEAT
should efector repeate after time up? Bool R/W
CURRENT_TIME
current efector's time. Float R/W
ACTIVE_PARTICLES
number of active particles. Int R
SORT
Bool R/W.
WIND
Bool R/W.
SPRING
Float R/W.
Definition at line 113 of file envisual.c.
{
    CONEANGLE,
    EMITOFFSET,
    VELOCITY,
    VELOCITY_RND,
    AVELOCITY,
    SIZE,
    STRETCH,
    RANDOM_ANGLE,
    RANDOM_ROT,
    AIR_RESISTANCE,
    AIR_RESISTANCE_RND,
    GRAVITY_SCALE,
    GRAVITY_SCALE_RND,
    BIRTH_RATE,
    BIRTH_RATE_RND,
    LIFETIME,
    LIFETIME_RND,
    LIFETIME_BY_ANIM,
    ANIM_ONCE,
    RAND_FRAME,
    EFFECT_TIME,
    REPEAT,
    CURRENT_TIME,
    ACTIVE_PARTICLES,
    SORT,
    WIND,
    SPRING
};
Function Documentation
GetParticleCount()
proto native int GetParticleCount (notnull IEntity ent)
GetParticleEmitorCount()
proto int GetParticleEmitorCount (notnull IEntity ent)
Referenced by Particle::GetMaxLifetime(), Particle::IncrementParticleParam(), ParticleSource::IncrementParticleParam(), Particle::IncrementParticleParamFromOriginal(), ParticleSource::IncrementParticleParamFromOriginal(), Particle::IsRepeat(), Particle::ScaleParticleParam(), ParticleSource::ScaleParticleParam(), Particle::ScaleParticleParamFromOriginal(), and ParticleSource::ScaleParticleParamFromOriginal().
GetParticleEmitors()
proto int GetParticleEmitors (notnull IEntity ent, out string emitors[], int max)
GetParticleParm()
proto void GetParticleParm (notnull IEntity ent, int emitor, EmitorParam parameter, out void value)
Referenced by Particle::GetMaxLifetime(), Particle::GetParameter(), ParticleSource::GetParameter(), Particle::GetParameterEx(), ParticleSource::GetParameterEx(), Particle::IncrementParticleParam(), ParticleSource::IncrementParticleParam(), Particle::IsRepeat(), Particle::ScaleParticleParam(), and ParticleSource::ScaleParticleParam().
GetParticleParmOriginal()
proto void GetParticleParmOriginal (notnull IEntity ent, int emitor, EmitorParam parameter, out void value)
Referenced by Particle::IncrementParticleParamFromOriginal(), ParticleSource::IncrementParticleParamFromOriginal(), Particle::ScaleParticleParamFromOriginal(), and ParticleSource::ScaleParticleParamFromOriginal().
HasActiveParticle()
proto bool HasActiveParticle (notnull IEntity ent)
ResetParticlePosition()
proto native void ResetParticlePosition (notnull IEntity ent)
RestartParticle()
proto native void RestartParticle (notnull IEntity ent)
SetParticleParm()
proto void SetParticleParm (notnull IEntity ent, int emitor, EmitorParam parameter, void value)
Referenced by Particle::IncrementParticleParam(), ParticleSource::IncrementParticleParam(), Particle::IncrementParticleParamFromOriginal(), ParticleSource::IncrementParticleParamFromOriginal(), Particle::ScaleParticleParam(), ParticleSource::ScaleParticleParam(), Particle::ScaleParticleParamFromOriginal(), ParticleSource::ScaleParticleParamFromOriginal(), Particle::SetParameter(), ParticleSource::SetParameter(), Particle::SetParticleParam(), and ParticleSource::SetParticleParam().