DayzKode: Strings
Strings
Classes
class string
Functions
bool string::Contains (string sample)
Retunrs true if sample is substring of string.
static proto string string::Format (string fmt, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
Gets n-th character from string.
string string::Get (int index)
Gets n-th character from string.
proto native int string::Hash ()
Returns hash of string.
proto native int string::HexToInt ()
Converts string to integer.
proto native int string::IndexOf (string sample)
Finds 'sample' in 'str'. Returns -1 when not found.
proto native int string::IndexOfFrom (int start, string sample)
Finds 'sample' in 'str' from 'start' position. Returns -1 when not found.
proto native int string::LastIndexOf (string sample)
Finds last 'sample' in 'str'. Returns -1 when not found.
proto native int string::Length ()
Returns length of string.
proto native int string::LengthUtf8 ()
Returns number of characters in UTF8 string.
proto int string::ParseString (out string tokens[])
Parses string into array of tokens returns number of tokens.
proto int string::ParseStringEx (out string token)
Parses one token from input string. Result is put into token string, and type of token is returned. Input string is left-truncated by the resulting token length.
proto int string::Replace (string sample, string replace)
Replace all occurrances of 'sample' in 'str' by 'replace'.
void string::Set (int n, string _value)
Sets n-th character in string.
void string::Split (string sample, out array< string > output)
Splits string into array of strings separated by 'sample'.
proto string string::Substring (int start, int len)
Substring of 'str' from 'start' position 'len' number of characters.
string string::SubstringInverted (string string_to_split, int position_start, int position_end)
Inverted SubString. This deletes everything in between position_start and position_end.
proto string string::SubstringUtf8 (int startChar, int len)
Substring of 'str' from 'startChar' position 'len' number of characters for UTF8 strings with multibyte chars.
proto int string::ToAscii (string str)
Converts string's first character to ASCII code.
proto native float string::ToFloat ()
Converts string to float.
proto native int string::ToInt ()
Converts string to integer.
proto int string::ToLower ()
Changes string to lowercase. Returns length.
static proto string string::ToString (void var, bool type=false, bool name=false, bool quotes=true)
Return string representation of variable.
proto native string::ToType ()
Returns internal type representation. Can be used in runtime, or cached in variables and used for faster inheritance checking.
proto int string::ToUpper ()
Changes string to uppercase. Returns length.
proto vector string::ToVector ()
Returns a vector from a string.
proto string string::Trim ()
Returns trimmed string with removed leading and trailing whitespaces.
proto int string::TrimInPlace ()
Removes leading and trailing whitespaces in string. Returns length.
Variables
static const string string::Empty
Detailed Description
Function Documentation
Contains()
bool string::Contains (string sample) inline private
Retunrs true if sample is substring of string.
Parameters
sample string Finding string expression
Returns
bool true if sample is substring of string
string str = "Hello World";
Print(str.IndexOfFrom(3, "Hello"));
Print(str.IndexOfFrom(3, "Mexico"));
>> true
>> false
Definition at line 272 of file enstring.c.
    {
        return value.IndexOf(sample) != -1;
    }
Referenced by ActionCreateIndoorFireplace::ActionCondition(), ActionCreateIndoorOven::ActionCondition(), ActionPlaceFireplaceIndoor::ActionCondition(), ActionPlaceOvenIndoor::ActionCondition(), CCTWaterSurface::Can(), BaseBuildingBase::CanDisplayAttachmentCategory(), CarScript::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), UIScriptedMenu::ChangeFilter(), BaseBuildingBase::CheckLevelVerticalDistance(), BaseBuildingBase::CheckSlotVerticalDistance(), AttachmentsOutOfReach::CreateAttachmentPosition(), CreateMission(), DropNonUsableMaterialsServer(), ItemBase::EEHealthLevelChanged(), ItemBase::EEItemLocationChanged(), UIPopupScript::FindInHierarchy(), UIScriptedMenu::FindInHierarchy(), CheckLocalisationPlugin::FindTexts(), ItemBase::FullyBuild(), GetClosestCarWheel(), Debug::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredSceneObjects(), ScriptedWidgetEventHandler::GetOnScreenPosition(), GUIAction_SetValue(), IsEntityOnWaterSurface(), ItemBase::IsSurfaceWater(), OnStepEvent(), PluginFileHandler::ParseToValueBool(), PluginBase::SpawnFromClipboard(), and ItemBase::ToggleAnimation().
Format()
static proto string string::Format (string fmt, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) static private
Gets n-th character from string.
Parameters
index character index
Returns
string character on index-th position in string
int a = 5;
float b = 5.99;
string c = "beta";
string  test = string.Format("Ahoj %1 = %3 , %2", a, b, c);
Print(test);
>> 'Ahoj 5 = 'beta' , 5.99'
Referenced by Add(), Category(), CheckContactCache(), ConsoleToolbarTypeToString(), EffectAreaLoader::CreateZones(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ActionDigInStash::GetAdminLogMessage(), GetAdminLogMessage(), ActionMountBarbedWire::GetAdminLogMessage(), ActionUnmountBarbedWire::GetAdminLogMessage(), ErrorProperties::GetClientMessage(), GetColorString(), GetComponentNamesFromDamageZone(), GetDamageZoneMap(), UndergroundAreaLoader::GetData(), EffectParticle::GetDebugName(), EffectSound::GetDebugName(), ConstructionActionData::GetDialNumberText(), QuantityConversions::GetItemQuantityText(), ParticleList::GetParticleFullPath(), InputUtils::GetRichtextButtonIconFromInputAction(), ErrorProperties::GetServerMessage(), ErrorHandlerModule::GetSimpleMessage(), array::GetTestEx(), GPSReceiver::GPSReceiver(), HandleError(), Weapon_Base::HideBullet(), LandMineTrap(), CfgGameplayHandler::LoadData(), Debug::LogMessage(), Weapon_Base::OnFire(), Play(), Hologram::RefreshVisual(), ParticleList::RegisterParticle(), TFModule::Result(), ScriptedWidgetEventHandler::SetItemDesc(), ScriptedWidgetEventHandler::SetWeaponModeAndZeroing(), ScriptedWidgetEventHandler::SetWeaponQuantity(), Weapon_Base::ShowBullet(), Tag(), TripwireTrap(), and UIScriptedMenu::UpdateControlsElements().
Get()
string string::Get (int index) inline private
Gets n-th character from string.
Parameters
index character index
Returns
string character on index-th position in string
string str = "Hello World";
Print(str[4]); // Print(str.Get(4));
>> 'o'
Definition at line 419 of file enstring.c.
    {
        return value.Substring(index, 1);
    }
References string::Substring().
Referenced by UIPopupScript::ClearHierarchy(), UIScriptedMenu::ClearHierarchy(), ItemBase::ConvertAttSlotToPlantSlot(), DialNextNumber(), UIPopupScript::ExpandHierarchy(), UIPopupScript::FindInHierarchy(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), PluginFileHandler::GetAllSubParametersInArrayString(), PluginBase::GetBaseClassPath(), PluginBase::GetBaseClassPathRecursive(), PluginBase::GetConfig(), ConstructionActionData::GetDialNumberText(), PluginFileHandler::GetLastLine(), CGame::GetModelName(), PluginBase::GetName(), PluginBase::GetNameByID(), OptionSelectorBase::GetStringValue(), ScriptedWidgetEventHandler::GetValueString(), ScriptedWidgetEventHandler::Highlight(), PluginFileHandler::LoadParameter(), LoadPlayerAttachmentIndexes(), PluginFileHandler::LoadSubParameter(), Debug::LogArrayInt(), Debug::LogArrayString(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginBase::PlayerKilled(), ScriptedWidgetEventHandler::Select(), UIScriptedMenu::SelectTab(), MissionBase::ShowHairDebugValues(), ShuffleLock(), ItemBase::UpdatePhysics(), HudDebugWinBase::UpdateValues(), and ItemBase::UpdateVisuals().
Hash()
proto native int string::Hash () private
Returns hash of string.
Returns
int - Hash of string
string str = "Hello World";
int hash = str.Hash();
Print(hash);
Referenced by Capture(), DayZPlayerTypeStepSoundLookupTable::DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeStepSoundLookupTableImpl(), DayZPlayerTypeVoiceSoundLookupTable::DayZPlayerTypeVoiceSoundLookupTableImpl(), GetBuilder(), GetDamageDisplayName(), AnimSoundLookupTableBank::GetImpactTable(), AnimSoundLookupTableBank::GetStepTable(), SoundLookupTable::LoadTable(), OnStepEvent(), EntityAI::ProcessImpactSound(), ProcessVoiceEvent(), RegisterItem(), CrashSoundSets::RegisterSoundSet(), and RegisterSoundSetMap().
HexToInt()
proto native int string::HexToInt () private
Converts string to integer.
Returns
int - Converted string.
string str = "0xFF";
int i = str.HexToInt();
Print(i);
>> i = 255
Referenced by CfgGameplayHandler::GetHitIndicationIndicatorColor().
IndexOf()
proto native int string::IndexOf (string sample) private
Finds 'sample' in 'str'. Returns -1 when not found.
Parameters
sample string Finding string
Returns
int - Returns position where sample starts, or -1 when sample not found
string str = "Hello World";
Print(str.IndexOf("H"));
Print(str.IndexOf("W"));
Print(str.IndexOf("Q"));
>> 0
>> 6
>> -1
Referenced by PluginBase::ContainsFirstClass(), PluginBase::GetConfig(), Chemlight_ColorBase::GetMaterialForDamageState(), PluginBase::GetPlayerPrefix(), PluginConfigHandler::GetSceneList(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), DebugPrint::IsDebugLog(), DebugPrint::IsStackTrace(), UIScriptedMenu::OnClick(), BotStateBase::OnUpdate(), PluginFileHandler::ParseParam(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), DebugPrint::TrimDebugLog(), and DebugPrint::TrimStackTrace().
IndexOfFrom()
proto native int string::IndexOfFrom (int start, string sample) private
Finds 'sample' in 'str' from 'start' position. Returns -1 when not found.
Parameters
start int Start from position
sample string Finding string expression
Returns
int - Length of string s
string str = "Hello World";
Print(str.IndexOfFrom(3, "H"));
Print(str.IndexOfFrom(3, "W"));
Print(str.IndexOfFrom(3, "Q"));
>> -1
>> 6
>> -1
Referenced by ActionUnmountBarbedWire::ActionCondition(), PluginBase::GetBaseClassPathCombined(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseToValueArray(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), and SetMissionPath().
LastIndexOf()
proto native int string::LastIndexOf (string sample) private
Finds last 'sample' in 'str'. Returns -1 when not found.
Parameters
sample string Finding string
Returns
int - Returns position where sample starts, or -1 when sample not found
string str = "Hello World";
Print(str.IndexOf("l"));
>> 9
Length()
proto native int string::Length () private
Returns length of string.
Returns
int - Length of string
string str = "Hello World";
int i = str.Length();
Print(i);
>> i = 11
Referenced by ActionMountBarbedWire::ActionCondition(), ActionUnmountBarbedWire::ActionCondition(), ActionEnterLadder::ActionCondition(), ScriptedWidgetEventHandler::Add(), JsonObject::AddString(), CanReachSeatFromDoors(), UIScriptedMenu::ConnectLastSession(), ManBase::Consume(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), WrittenNoteData::DepleteWritingImplement(), DialNextNumber(), DropNonUsableMaterialsServer(), FireworksLauncherClientEvent::FireworksLauncherClientEvent(), PluginBase::GetBaseClassPath(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), ConstructionActionData::GetDialNumberText(), ScriptedWidgetEventHandler::GetFilterOptionsConsoles(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), JsonObject::GetJson(), CGame::GetModelName(), GetName(), PluginBase::GetOnlyChildPath(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), InsertAtPos(), IsComponentInSelection(), IsPingInRange(), PluginFileHandler::IsTextArray(), UIScriptedMenu::OnClick(), ActionCarDoors::OnEnd(), OnEvent(), OnStepEvent(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), PluginFileHandler::ParseToValueArray(), PluginFileHandler::ParseToValueString(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), SanitizeString(), Hud::SetCursorIcon(), ScriptedWidgetEventHandler::SetItemDesc(), ShuffleLock(), string::SubstringInverted(), ToStringLen(), DebugPrint::TrimDebugLog(), HudDebugWinBase::Update(), and ValueToBar().
LengthUtf8()
proto native int string::LengthUtf8 () private
Returns number of characters in UTF8 string.
Returns
int - Number of characters in UTF8 string
string str = "";
int i = str.LengthUtf8();
Print(i);
>> i = 7
Referenced by UIScriptedMenu::Refresh().
ParseString()
proto int string::ParseString (out string tokens[]) private
Parses string into array of tokens returns number of tokens.
Parameters
[out] tokens array[] Parsed string in array
Returns
int Number of tokens
string token[2];
string str = "Hello World";
int result = str.ParseString(token);
for(int i = 0; i < 2; i++)
{
    Print(token[i]);
}
>> 'Hello'
>> 'World'
ParseStringEx()
proto int string::ParseStringEx (out string token) private
Parses one token from input string. Result is put into token string, and type of token is returned. Input string is left-truncated by the resulting token length.
Parameters
[out] token string Founded string token
Returns
int Type of token
Token types:
 0 - error, no token
 1 - defined token (special characters etc. . / * )
 2 - quoted string. Quotes are removed -> TODO
 3 - alphabetic string
 4 - number
 5 - end of line -> TODO
string input = "Hello*World";
string token1;
string token2;
int result1 = input.ParseStringEx(token1);
int result2 = input.ParseStringEx(token2);
Print("Token1 = '" + token1 + "' Type = " + result1.ToString()));
Print("Token2 = '" + token2 + "' Type = " + result2.ToString()));
>> 'Toke1 = 'Hello' Type = 3'
>> 'Toke1 = '*' Type = 1'
Replace()
proto int string::Replace (string sample, string replace) private
Replace all occurrances of 'sample' in 'str' by 'replace'.
Parameters
sample string to search in str
replace string which replace sample in str
Returns
int - number of occurrances of 'sample' in 'str'
string test = "If the length of the C string in source is less than num, only the content up to the terminating null-character is copied.";
Print(test);
int count = test.Replace("the", "*");
Print(count);
Print(test);
>> string test = 'If the length of the C string in source is less than num, only the content up to the terminating null-character is copied.';
>> int count =   4
>> string test = 'If * length of * C string in source is less than num, only * content up to * terminating null-character is copied.'
Referenced by PluginFileHandler::AddNewLine(), Icon::Combine(), PluginConfigHandler::DecodeInitScript(), Icon::DoubleClick(), HandsContainer::DoubleClick(), AttachmentCategoriesRow::DoubleClick(), ClosableContainer::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), Icon::DraggingOver(), DraggingOverCenterPanel(), Icon::DraggingOverCombine(), ClosableContainer::DraggingOverGrid(), HandsContainer::DraggingOverGrid(), AttachmentCategoriesRow::DraggingOverGrid(), HandsArea::DraggingOverHandsPanel(), HandsContainer::DraggingOverHeader(), AttachmentCategoriesContainer::DraggingOverHeader(), AttachmentCategoriesRow::DraggingOverHeader(), VicinityContainer::DraggingOverHeader(), ZombieContainer::DraggingOverHeader(), VicinityContainer::DraggingOverIcon(), Icon::DraggingOverSwap(), Icon::DropReceivedFromMain(), PluginConfigHandler::EncodeInitScript(), PluginFileHandler::GetAllLines(), HandsContainer::GetItemPreviewItem(), AttachmentCategoriesRow::GetItemPreviewItem(), ClosableContainer::GetItemPreviewItem(), ClosableContainer::GetItemPreviewWidget(), PlayerContainer::GetItemPreviewWidget(), ClosableContainer::GetItemPreviewWidgetDragOrDrop(), LoadPlayerAttachmentIndexes(), VicinitySlotsContainer::MouseButtonDown(), VicinitySlotsContainer::MouseClick(), HandsContainer::MouseClick2(), OnCenterPanelDropReceived(), UIScriptedMenu::OnClick(), ZombieContainer::OnDropReceivedFromGhostArea(), AttachmentCategoriesContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromHeader(), VicinitySlotsContainer::OnDropReceivedFromHeader(), ZombieContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), HandsArea::OnHandsPanelDropReceived(), InventoryGridController::OnItemDraggingOver(), InventoryGridController::OnItemDropReceived(), OnRightPanelDropReceived(), SVNBlamePlugin::Run(), SVNDiffPlugin::Run(), OpenDirPlugin::Run(), SVNShowLogPlugin::Run(), ResavePlugin::RunCommandline(), DayZTool::RunDayZBat(), ColorManager::SetColor(), ItemManager::SetTemperature(), Icon::Swap(), and PlayerContainer::ToggleWidget().
Set()
void string::Set (int n, string _value) inline private
Sets n-th character in string.
string str = "Hello World";
str[4] = "O";
Print(str);
>> 'HellO World'
Definition at line 434 of file enstring.c.
    {
        string pre = value.Substring(0, n);
        n += 1;
        int length = value.Length() - n;
        string post = value.Substring(n, length);
        value = pre + _value + post;
    }
Referenced by ItemBase::GardenBase().
Split()
void string::Split (string sample, out array< string > output) inline private
Splits string into array of strings separated by 'sample'.
Parameters
sample string Strings separator
Returns
TStringArray Array with strings
TStringArray strs = new TStringArray;
EnString.Split("The quick brown fox jumps over the lazy dog", " ", strs);
for (int i = 0; i < strs.Count(); i++)
{
    Print( strs.Get(i) );
}
>> 'The'
>> 'quick'
>> 'brown'
>> 'fox'
>> 'jumps'
>> 'over'
>> 'the'
>> 'lazy'
>> 'dog'
Definition at line 381 of file enstring.c.
    {
        int txt_len = 0;
        int sep_pos = -1;
        int nxt_sep_pos = 0;
        string text = "";
        bool line_end = false;
        while (line_end == false)
        {
            sep_pos = sep_pos + txt_len + 1;
            nxt_sep_pos = value.IndexOfFrom(sep_pos, sample);
            if ( nxt_sep_pos == -1 )
            {
                nxt_sep_pos = value.Length();
                line_end = true;
            }
            txt_len = nxt_sep_pos - sep_pos;
            if ( txt_len > 0 )
            {
                text = value.Substring(sep_pos, txt_len);
                output.Insert(text);
            }
        }
    }
References string::Substring().
Referenced by JsonObject::AddString(), UIScriptedMenu::ChangeFilter(), UIPopupScript::FindInHierarchy(), UIScriptedMenu::FindInHierarchy(), ScriptedWidgetEventHandler::GenerateValidIP(), PluginBase::GetConfig(), ScriptedWidgetEventHandler::GetFilterOptionsConsoles(), GetLastVisitedServer(), PluginFileHandler::GetParameterString(), PluginFileHandler::GetSubParameterInArrayString(), ServerBrowserTab::GetTimeOfDayEnum(), ServerBrowserTabConsolePages::LoadExtraEntries(), OnGUI_AnimEvents(), ParseData(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseToValueArray(), ProcessAttachmentEvent(), ScriptedWidgetEventHandler::SetTime(), and PluginBase::SpawnFromClipboard().
Substring()
proto string string::Substring (int start, int len) private
Substring of 'str' from 'start' position 'len' number of characters.
Parameters
start Position in str
len Count of characters
Returns
string - Substring of str
string str = "Hello World";
string strSub = str.Substring(2, 5);
Print(strSub);
>> strSub = llo W
Referenced by ActionUnmountBarbedWire::ActionCondition(), ActionEnterLadder::ActionCondition(), TentBase::AnimateCamonetByOpeningSelection(), TentBase::AnimateCamonetToggle(), PluginBase::ContainsFirstClass(), AttachmentsOutOfReach::CreateAttachmentPosition(), string::Get(), PluginBase::GetBaseClassPathCombined(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), ScriptedWidgetEventHandler::GetFilterOptionsConsoles(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), Chemlight_ColorBase::GetMaterialForDamageState(), CGame::GetModelName(), PluginBase::GetOnlyChildPath(), PluginBase::GetPlayerPrefix(), PluginConfigHandler::GetSceneList(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), PluginFileHandler::GetTextType(), ScriptedWidgetEventHandler::GetValueString(), TentBase::HandleCamoNetAttachment(), InsertAtPos(), IsPingInRange(), PluginFileHandler::IsTextArray(), UIScriptedMenu::OnClick(), PluginFileHandler::ParseText(), PluginFileHandler::ParseTextToArray(), PluginFileHandler::ParseTextToParameter(), PluginFileHandler::ParseToValueArray(), PluginFileHandler::ParseToValueString(), OpenDirPlugin::Run(), DayZTool::RunDayZBat(), SanitizeString(), SetMissionPath(), string::Split(), string::SubstringInverted(), DebugPrint::TrimDebugLog(), and HudDebugWinBase::Update().
SubstringInverted()
string string::SubstringInverted (string string_to_split, int position_start, int position_end) inline private
Inverted SubString. This deletes everything in between position_start and position_end.
Definition at line 102 of file enstring.c.
    {
        string first_half = string_to_split.Substring(0, position_start);
        string second_half = string_to_split.Substring( position_end, string_to_split.Length() - position_end );
        string result = first_half + second_half;
        return result;
    }
References string::Length(), and string::Substring().
Referenced by GetName().
SubstringUtf8()
proto string string::SubstringUtf8 (int startChar, int len) private
Substring of 'str' from 'startChar' position 'len' number of characters for UTF8 strings with multibyte chars.
Parameters
startChar Position in str.
len Count of characters
Returns
string - Substring of str with startChar character and len characters
string str = "";
string strSub = str.SubstringUtf8(2, 4);
Print(strSub);
>> strSub =
Referenced by UIScriptedMenu::Refresh().
ToAscii()
proto int string::ToAscii (string str) private
Converts string's first character to ASCII code.
Parameters
str String for convert to ASCII code
Returns
ascii code int.
int ascii = "M".ToAcsii();
Print(ascii);
>> ascii = 77
ToFloat()
proto native float string::ToFloat () private
Converts string to float.
Returns
float - Converted string in float.
string str = "56.6";
float f = str.ToFloat();
Print(f);
>> f = 56.6
Referenced by Liquid::GetDigestibility(), Liquid::GetEnergy(), Liquid::GetFlammability(), Liquid::GetFullness(), ScriptedWidgetEventHandler::GetInterpTime(), Liquid::GetNutritionalIndex(), PluginFileHandler::GetParameterFloat(), Liquid::GetToxicity(), Liquid::GetWaterContent(), GUIAction_SetValue(), OnGUI_CommandsEdit(), and PluginFileHandler::ParseToValueFloat().
ToInt()
proto native int string::ToInt () private
Converts string to integer.
Returns
int - Converted string.
string str = "56";
int i = str.ToInt();
Print(i);
>> i = 56
Referenced by ConnectFromCLI(), DialNextNumber(), Liquid::GetAgents(), ItemManager::GetDefaultOpenStateHands(), ScriptedWidgetEventHandler::GetFilterOptionsConsoles(), ScriptedWidgetEventHandler::GetFilterOptionsPC(), FireplaceBase::GetFirePointIndex(), PluginFileHandler::GetParameterBool(), PluginFileHandler::GetParameterInt(), ItemBase::GetSlotIndexByAttachmentSlot(), ItemBase::GetSlotIndexBySelection(), GUIAction_SetValue(), IsPingInRange(), OnGUI_CommandsEdit(), OrderedAltitudeNumbersPosition(), OrderedPositionNumbersFromGridCoords(), PluginFileHandler::ParseToValueInt(), ScriptedWidgetEventHandler::ProcessIntoIPAddress(), and ShuffleLock().
ToLower()
proto int string::ToLower () private
Changes string to lowercase. Returns length.
Returns
int - Length of changed string
string str = "Hello World";
int i = str.ToLower();
Print(str);
Print(i);
>> str = hello world
>> i = 11
Referenced by BleedingSourcesManagerBase::AttemptAddBleedingSourceBySelection(), BaseBuildingBase::CanDisplayAttachmentCategory(), CarScript::CanDisplayAttachmentCategory(), BaseBuildingBase::CanDisplayAttachmentSlot(), ItemBase::CanToggleAnimations(), UIScriptedMenu::ChangeFilter(), BaseBuildingBase::CheckSlotVerticalDistance(), AttachmentsOutOfReach::CreateAttachmentPosition(), DropNonUsableMaterialsServer(), ItemBase::EEHealthLevelChanged(), ItemBase::EEItemDetached(), UIPopupScript::FindInHierarchy(), UIScriptedMenu::FindInHierarchy(), PluginConfigDebugProfile::GetAllPositionsNames(), GetClosestCarWheel(), GetComponentIndex(), PluginBase::GetConfig(), PluginBase::GetConfigRecursive(), GetDamageZoneFromComponentName(), Debug::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredConfigClasses(), UIScriptedMenu::GetFiltredSceneObjects(), GetLODByName(), ScriptedWidgetEventHandler::GetMapName(), PluginConfigDebugProfile::GetPositionByName(), LOD::GetSelectionByName(), ItemBase::GetSlotIndexBySelection(), GUIAction_SetValue(), ItemBase::HideAllAnimationsAndProxyPhysics(), MissionBaseWorld::InitialiseWorldData(), IsComponentInSelection(), CGame::IsKindOf(), CGame::ObjectIsKindOf(), ActionMountBarbedWire::OnFinishProgressServer(), BleedingSourcesManagerBase::RegisterBleedingZoneEx(), UIScriptedMenu::SelectPreset(), ItemBase::ToggleAnimation(), ItemBase::UpdateAllSelections(), and ItemBase::UpdatePhysics().
ToString()
static proto string string::ToString (void var, bool type = false, bool name = false, bool quotes = true) static private
Return string representation of variable.
Referenced by HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Abort(), CGame::AddInventoryJunctureEx(), AddInventoryReservationEx(), FireplaceBase::CanPlaceFireplaceInSelectedSpot(), ClearInventoryReservationEx(), CommandHandlerDebug(), EntityLightSource::CreateLight(), DbgShowBoneName(), DialNextNumber(), ItemBase::EEItemAttached(), ComponentEnergyManager::Event_OnAwake(), ExtendInventoryReservationEx(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::FindAbortDestinationState(), ItemBase::GardenBase(), ScriptedWidgetEventHandler::GenerateValidIP(), AntibioticsMdfr::GetDebugText(), DisinfectionMdfr::GetDebugText(), EpinephrineMdfr::GetDebugText(), ImmunityBoost::GetDebugText(), MorphineMdfr::GetDebugText(), PainKillersMdfr::GetDebugText(), AntibioticsMdfr::GetDebugTextSimple(), CharcoalMdfr::GetDebugTextSimple(), DisinfectionMdfr::GetDebugTextSimple(), VicinitySlotsContainer::GetItemQuantityText(), QuantityConversions::GetItemQuantityText(), GetStrValue(), Hologram::Hologram(), ComponentEnergyManager::IsSelectionAPlug(), PluginFileHandler::LoadConfigFile(), PluginConfigHandler::LoadSceneObjects(), Debug::LogArrayInt(), ActionManagerBase::OnActionEnd(), ActionTuneFrequencyOnGround::OnActionInfoUpdate(), MissionBase::OnClientDisconnectedEvent(), PluginFileHandler::ParseParam(), PluginBase::PlayerKilled(), PrintElements(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessAbortEvent(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::ProcessEvent(), PluginConfigHandler::SaveSceneObjects(), PluginConfigHandler::SceneDuplicate(), PluginLocalProfile::SceneSave(), ScriptedWidgetEventHandler::SetItemQuantity(), PluginFileHandler::SetParameterInt(), SetupAction(), ScriptedWidgetEventHandler::SetWeaponQuantity(), ShuffleLock(), OFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), FSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Start(), HFSMBase< Class FSMStateBase, Class FSMEventBase, Class FSMActionBase, Class FSMGuardBase >::Terminate(), PluginDayzPlayerDebug_Weapons::Tick(), ToStringLen(), ServerBrowserTab::UpdatePageButtons(), UpdatePlayerStatus(), and ComponentEnergyManager::UpdateSelections().
ToType()
proto native string::ToType () private
Returns internal type representation. Can be used in runtime, or cached in variables and used for faster inheritance checking.
Returns
typename Type of class
???
Referenced by ComponentsBank::CreateComponent(), CreateParticle(), DayZCreatureAI::EEHitBy(), ManBase::EEHitBy(), EvaluateImpactEffect(), AmmoEffects::GetAmmoEffectTypename(), PluginBase::GetModuleType(), EffectArea::GetRequesterIndex(), PluginBase::OnKeyPress(), PluginBase::OnMouse(), PluginManager::RegisterPlugin(), RegisterSurface(), and PluginManager::UnregisterPlugin().
ToUpper()
proto int string::ToUpper () private
Changes string to uppercase. Returns length.
Returns
int - Length of changed string
string str = "Hello World";
int i = str.ToUpper();
Print(str);
Print(i);
>> str = HELLO WORLD
>> i = 11
Referenced by ScriptedWidgetEventHandler::Add(), HandsPreview::CreateNewIcon(), Attachments::InitAttachmentGrid(), ClosableContainer::SetEntity(), ScriptedWidgetEventHandler::SetItemDesc(), ClosableHeader::SetName(), Header::SetName(), and Container::UpdateHeaderText().
ToVector()
proto vector string::ToVector () private
Returns a vector from a string.
Returns
vector Converted s as vector
string str = "1 0 1";
vector v = str.ToVector();
Print(v);
>> v = <1,0,1>
Referenced by UIScriptedMenu::OnClick(), and SceneObject::SetPositionAsString().
Trim()
proto string string::Trim () private
Returns trimmed string with removed leading and trailing whitespaces.
Returns
string - Trimmed string
string str = " Hello World "
Print(str);
Print(str.Trim());
>> ' Hello World '
>> 'Hello World'
Referenced by PluginBase::GetOnlyChildPath(), PluginFileHandler::ParseText(), and PluginFileHandler::ParseTextToParameter().
TrimInPlace()
proto int string::TrimInPlace () private
Removes leading and trailing whitespaces in string. Returns length.
Returns
int - Count of chars
string str = " Hello World ";
int i = str.TrimInPlace();
Print(str);
Print(i);
>> str = 'Hello World'
>> i = 11
Referenced by ScriptedWidgetEventHandler::GetValueString().
Variable Documentation
Empty
const string string::Empty static private
Definition at line 7 of file enstring.c.
Referenced by ActionTuneFrequencyOnGround::ActionTuneFrequencyOnGround(), ScriptedWidgetEventHandler::GetActionDesc(), PluginBase::GetFileName(), WeaponStateBase::OnEntry(), WeaponStateBase::OnExit(), DebugPrint::TrimStackTrace(), and ReplaceItemWithNewLambdaBase::WantCreateNewEntity().