DayzKode: Debug UI API
Debug UI API
Debug utilities
Immediate mode debug UI APIPer frame usage example:
Classes
class DbgUI
Functions
static proto native void DbgUI::Begin (string windowTitle, float x=0, float y=0)
static proto void DbgUI::BeginCleanupScope ()
static proto native bool DbgUI::Button (string txt, int minWidth=0)
static proto void DbgUI::Check (string label, out bool checked)
static proto native void DbgUI::ColoredText (int color, string label)
static proto void DbgUI::Combo (string label, out int selection, TStringArray elems)
private void DbgUI::DbgUI ()
static proto native void DbgUI::DoUnitTest ()
Creates all possible DbgUI widgets. Just for the testing purposes.
static proto native void DbgUI::End ()
static proto native void DbgUI::EndCleanupScope ()
static proto void DbgUI::InputFloat (string txt, out float value, int pxWidth=150)
static proto void DbgUI::InputInt (string txt, out int value, int pxWidth=150)
static proto void DbgUI::InputText (string txt, out string value, int pxWidth=150)
static proto void DbgUI::List (string label, out int selection, TStringArray elems)
static proto native void DbgUI::Panel (string label, int width, int height, int color=0xaa555555)
static proto native void DbgUI::PlotLive (string label, int sizeX, int sizeY, float val, int timeStep=100, int historySize=30, int color=0xFFFFFFFF)
static proto native void DbgUI::PopID ()
static proto native void DbgUI::PushID_Int (int int_id)
static proto native void DbgUI::PushID_Str (string str_id)
static proto native void DbgUI::SameLine ()
static proto native void DbgUI::SameSpot ()
static proto void DbgUI::SliderFloat (string label, out float value, float min, float max, int pxWidth=150)
static proto native void DbgUI::Spacer (int height)
static proto native void DbgUI::Text (string label)
private void DbgUI::~DbgUI ()
Detailed Description
Immediate mode debug UI API
Per frame usage example:
bool m_ShowDbgUI = false;
int m_DbgListSelection = 0;
float m_DbgSliderValue = 0.0;
autoptr array<string> m_DbgOptions = {"jedna", "dva", "tri"};
void OnUpdate(float timeslice)
{
   DbgUI.Begin("Test");
   DbgUI.Check("Show DbgUI", m_ShowDbgUI);
   if (m_ShowDbgUI)
   {
       DbgUI.Text("DbgUI Test");
       string name = "";
       DbgUI.InputText("name", name);
       if (DbgUI.Button("Print name"))
       {
           Print(name);
       }
       DbgUI.List("test list", m_DbgListSelection, m_DbgOptions);
       DbgUI.Text("Choice = " + m_DbgListSelection.ToString());
       DbgUI.Spacer(10);
       DbgUI.SliderFloat("slider", m_DbgSliderValue, 0, 100);
       DbgUI.Text("Slider value = " + ftoa(m_DbgSliderValue));
   }
   DbgUI.End();
}
For non-per frame usage example:
int m_DbgEventCount = 0;
void OnEvent(EventType eventTypeId, Param params)
{
   m_DbgEventCount++;
   DbgUI.BeginCleanupScope();
   DbgUI.Begin("events", 300, 0);
   DbgUI.Text("Events count = " + m_DbgEventCount.ToString());
   DbgUI.End();
   DbgUI.EndCleanupScope();
}
Function Documentation
Begin()
static proto native void DbgUI::Begin (string windowTitle, float x = 0, float y = 0) static private
Referenced by SymptomManager::CleanAvailableSymptoms(), BleedingSourcesManagerBase::CleanDebug(), SymptomManager::CleanDebug1(), SymptomManager::CleanDebug2(), BleedingSourcesManagerBase::DisplayDebug(), SymptomManager::DisplayDebug1(), SymptomManager::DisplayDebug2(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), OnGUI(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), SymptomManager::ShowAvailableSymptoms(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
BeginCleanupScope()
static proto void DbgUI::BeginCleanupScope () static private
Referenced by SymptomManager::CleanAvailableSymptoms(), BleedingSourcesManagerBase::CleanDebug(), SymptomManager::CleanDebug1(), SymptomManager::CleanDebug2(), BleedingSourcesManagerBase::DisplayDebug(), SymptomManager::DisplayDebug1(), SymptomManager::DisplayDebug2(), OnGUI(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), SymptomManager::ShowAvailableSymptoms(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
Button()
static proto native bool DbgUI::Button (string txt, int minWidth = 0) static private
Referenced by SymptomManager::DisplayDebug2(), OnGUI(), OnGUI_AIControlEdit(), OnGUI_AnimEvents(), OnGUI_BulkSet(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), and SymptomManager::ShowAvailableSymptoms().
Check()
static proto void DbgUI::Check (string label, out bool checked) static private
Referenced by OnGUI(), OnGUI_CommandsEdit(), and OnGUI_VariablesEdit().
ColoredText()
static proto native void DbgUI::ColoredText (int color, string label) static private
Combo()
static proto void DbgUI::Combo (string label, out int selection, TStringArray elems) static private
DbgUI()
private void DbgUI::DbgUI () inline private
Definition at line 61 of file dbgui.c.
{}
DoUnitTest()
static proto native void DbgUI::DoUnitTest () static private
Creates all possible DbgUI widgets. Just for the testing purposes.
End()
static proto native void DbgUI::End () static private
Referenced by SymptomManager::CleanAvailableSymptoms(), BleedingSourcesManagerBase::CleanDebug(), SymptomManager::CleanDebug1(), SymptomManager::CleanDebug2(), BleedingSourcesManagerBase::DisplayDebug(), SymptomManager::DisplayDebug1(), SymptomManager::DisplayDebug2(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), OnGUI(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), SymptomManager::ShowAvailableSymptoms(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
EndCleanupScope()
static proto native void DbgUI::EndCleanupScope () static private
Referenced by SymptomManager::CleanAvailableSymptoms(), BleedingSourcesManagerBase::CleanDebug(), SymptomManager::CleanDebug1(), SymptomManager::CleanDebug2(), BleedingSourcesManagerBase::DisplayDebug(), SymptomManager::DisplayDebug1(), SymptomManager::DisplayDebug2(), OnGUI(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), SymptomManager::ShowAvailableSymptoms(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
InputFloat()
static proto void DbgUI::InputFloat (string txt, out float value, int pxWidth = 150) static private
Referenced by PluginBase::OnGUITimer().
InputInt()
static proto void DbgUI::InputInt (string txt, out int value, int pxWidth = 150) static private
Referenced by OnGUI().
InputText()
static proto void DbgUI::InputText (string txt, out string value, int pxWidth = 150) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
List()
static proto void DbgUI::List (string label, out int selection, TStringArray elems) static private
Panel()
static proto native void DbgUI::Panel (string label, int width, int height, int color = 0xaa555555) static private
Referenced by OnGUI(), OnGUI_AnimEvents(), and ShowCoefsDbg().
PlotLive()
static proto native void DbgUI::PlotLive (string label, int sizeX, int sizeY, float val, int timeStep = 100, int historySize = 30, int color = 0xFFFFFFFF) static private
PopID()
static proto native void DbgUI::PopID () static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
PushID_Int()
static proto native void DbgUI::PushID_Int (int int_id) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
PushID_Str()
static proto native void DbgUI::PushID_Str (string str_id) static private
Referenced by OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
SameLine()
static proto native void DbgUI::SameLine () static private
Referenced by OnGUI(), OnGUI_CommandsEdit(), OnGUI_VariablesEdit(), and PluginBase::OnGUITimer().
SameSpot()
static proto native void DbgUI::SameSpot () static private
SliderFloat()
static proto void DbgUI::SliderFloat (string label, out float value, float min, float max, int pxWidth = 150) static private
Spacer()
static proto native void DbgUI::Spacer (int height) static private
Referenced by OnGUI(), and ShowCoefsDbg().
Text()
static proto native void DbgUI::Text (string label) static private
Referenced by BleedingSourcesManagerBase::DisplayDebug(), SymptomManager::DisplayDebug1(), SymptomManager::DisplayDebug2(), WeaponDebug::DisplayGeneralInfo(), WeaponDebug::DisplayTargetInfo(), PluginBase::DrawDebugs(), OnGUI(), OnGUI_AnimEvents(), OnGUI_CommandsEdit(), OnGUI_Variables(), OnGUI_VariablesEdit(), PluginBase::OnGUITimer(), MissionBase::OnUpdate(), UIScriptedMenu::SetCameraData(), ShowCoefsDbg(), Managed::ShowDebugValues(), and MissionBase::ShowHairDebugValues().
~DbgUI()
private void DbgUI::~DbgUI () inline private
Definition at line 62 of file dbgui.c.
{}