DayzKode: Keyboard input API
Keyboard input API
System
Enumerations
enum KeyCode {
KC_ESCAPE , KC_1 , KC_2 , KC_3 ,
KC_4 , KC_5 , KC_6 , KC_7 ,
KC_8 , KC_9 , KC_0 , KC_MINUS ,
KC_EQUALS , KC_BACK , KC_TAB , KC_Q ,
KC_W , KC_E , KC_R , KC_T ,
KC_Y , KC_U , KC_I , KC_O ,
KC_P , KC_LBRACKET , KC_RBRACKET , KC_RETURN ,
KC_LCONTROL , KC_A , KC_S , KC_D ,
KC_F , KC_G , KC_H , KC_J ,
KC_K , KC_L , KC_SEMICOLON , KC_APOSTROPHE ,
KC_GRAVE , KC_LSHIFT , KC_BACKSLASH , KC_Z ,
KC_X , KC_C , KC_V , KC_B ,
KC_N , KC_M , KC_COMMA , KC_PERIOD ,
KC_SLASH , KC_RSHIFT , KC_MULTIPLY , KC_LMENU ,
KC_SPACE , KC_CAPITAL , KC_F1 , KC_F2 ,
KC_F3 , KC_F4 , KC_F5 , KC_F6 ,
KC_F7 , KC_F8 , KC_F9 , KC_F10 ,
KC_NUMLOCK , KC_SCROLL , KC_NUMPAD7 , KC_NUMPAD8 ,
KC_NUMPAD9 , KC_SUBTRACT , KC_NUMPAD4 , KC_NUMPAD5 ,
KC_NUMPAD6 , KC_ADD , KC_NUMPAD1 , KC_NUMPAD2 ,
KC_NUMPAD3 , KC_NUMPAD0 , KC_DECIMAL , KC_OEM_102 ,
KC_F11 , KC_F12 , KC_NUMPADEQUALS , KC_PREVTRACK ,
KC_AT , KC_COLON , KC_UNDERLINE , KC_STOP ,
KC_AX , KC_UNLABELED , KC_NEXTTRACK , KC_NUMPADENTER ,
KC_RCONTROL , KC_MUTE , KC_CALCULATOR , KC_PLAYPAUSE ,
KC_MEDIASTOP , KC_VOLUMEDOWN , KC_VOLUMEUP , KC_WEBHOME ,
KC_NUMPADCOMMA , KC_DIVIDE , KC_SYSRQ , KC_RMENU ,
KC_PAUSE , KC_HOME , KC_UP , KC_PRIOR ,
KC_LEFT , KC_RIGHT , KC_END , KC_DOWN ,
KC_NEXT , KC_INSERT , KC_DELETE , KC_LWIN ,
KC_RWIN , KC_APPS , KC_POWER , KC_SLEEP ,
KC_WAKE , KC_MEDIASELECT
}
Functions
proto native void ClearKey (KeyCode key)
proto native int KeyState (KeyCode key)
Detailed Description
Enumeration Type Documentation
KeyCode
enum KeyCode
Enumerator
KC_ESCAPE
KC_1
KC_2
KC_3
KC_4
KC_5
KC_6
KC_7
KC_8
KC_9
KC_0
KC_MINUS
on main keyboard
KC_EQUALS
KC_BACK
backspace
KC_TAB
KC_Q
KC_W
KC_E
KC_R
KC_T
KC_Y
KC_U
KC_I
KC_O
KC_P
KC_LBRACKET
KC_RBRACKET
KC_RETURN
Enter on main keyboard.
KC_LCONTROL
KC_A
KC_S
KC_D
KC_F
KC_G
KC_H
KC_J
KC_K
KC_L
KC_SEMICOLON
KC_APOSTROPHE
KC_GRAVE
accent grave
KC_LSHIFT
KC_BACKSLASH
KC_Z
KC_X
KC_C
KC_V
KC_B
KC_N
KC_M
KC_COMMA
KC_PERIOD
. on main keyboard
KC_SLASH
/ on main keyboard
KC_RSHIFT
KC_MULTIPLY
on numeric keypad
KC_LMENU
left Alt
KC_SPACE
KC_CAPITAL
KC_F1
KC_F2
KC_F3
KC_F4
KC_F5
KC_F6
KC_F7
KC_F8
KC_F9
KC_F10
KC_NUMLOCK
KC_SCROLL
Scroll Lock.
KC_NUMPAD7
KC_NUMPAD8
KC_NUMPAD9
KC_SUBTRACT
on numeric keypad
KC_NUMPAD4
KC_NUMPAD5
KC_NUMPAD6
KC_ADD
on numeric keypad
KC_NUMPAD1
KC_NUMPAD2
KC_NUMPAD3
KC_NUMPAD0
KC_DECIMAL
. on numeric keypad
KC_OEM_102
< > | on UK/Germany keyboards
KC_F11
KC_F12
KC_NUMPADEQUALS
= on numeric keypad (NEC PC98)
KC_PREVTRACK
Previous Track (DIKC_CIRCUMFLEX on Japanese keyboard)
KC_AT
(NEC PC98)
KC_COLON
(NEC PC98)
KC_UNDERLINE
(NEC PC98)
KC_STOP
(NEC PC98)
KC_AX
(Japan AX)
KC_UNLABELED
(J3100)
KC_NEXTTRACK
Next Track.
KC_NUMPADENTER
Enter on numeric keypad.
KC_RCONTROL
KC_MUTE
Mute.
KC_CALCULATOR
Calculator.
KC_PLAYPAUSE
Play / Pause.
KC_MEDIASTOP
Media Stop.
KC_VOLUMEDOWN
Volume -.
KC_VOLUMEUP
Volume +.
KC_WEBHOME
Web home.
KC_NUMPADCOMMA
, on numeric keypad (NEC PC98)
KC_DIVIDE
/ on numeric keypad
KC_SYSRQ
KC_RMENU
right Alt
KC_PAUSE
Pause.
KC_HOME
Home on arrow keypad.
KC_UP
UpArrow on arrow keypad.
KC_PRIOR
PgUp on arrow keypad.
KC_LEFT
LeftArrow on arrow keypad.
KC_RIGHT
RightArrow on arrow keypad.
KC_END
End on arrow keypad.
KC_DOWN
DownArrow on arrow keypad.
KC_NEXT
PgDn on arrow keypad.
KC_INSERT
Insert on arrow keypad.
KC_DELETE
Delete on arrow keypad.
KC_LWIN
Left Windows key.
KC_RWIN
Right Windows key.
KC_APPS
AppMenu key.
KC_POWER
System Power.
KC_SLEEP
System Sleep.
KC_WAKE
System Wake.
KC_MEDIASELECT
Media Select.
Definition at line 156 of file ensystem.c.
{
    KC_ESCAPE,
    KC_1,
    KC_2,
    KC_3,
    KC_4,
    KC_5,
    KC_6,
    KC_7,
    KC_8,
    KC_9,
    KC_0,
    KC_MINUS,
    KC_EQUALS,
    KC_BACK,
    KC_TAB,
    KC_Q,
    KC_W,
    KC_E,
    KC_R,
    KC_T,
    KC_Y,
    KC_U,
    KC_I,
    KC_O,
    KC_P,
    KC_LBRACKET,
    KC_RBRACKET,
    KC_RETURN,
    KC_LCONTROL,
    KC_A,
    KC_S,
    KC_D,
    KC_F,
    KC_G,
    KC_H,
    KC_J,
    KC_K,
    KC_L,
    KC_SEMICOLON,
    KC_APOSTROPHE,
    KC_GRAVE,
    KC_LSHIFT,
    KC_BACKSLASH,
    KC_Z,
    KC_X,
    KC_C,
    KC_V,
    KC_B,
    KC_N,
    KC_M,
    KC_COMMA,
    KC_PERIOD,
    KC_SLASH,
    KC_RSHIFT,
    KC_MULTIPLY,
    KC_LMENU,
    KC_SPACE,
    KC_CAPITAL,
    KC_F1,
    KC_F2,
    KC_F3,
    KC_F4,
    KC_F5,
    KC_F6,
    KC_F7,
    KC_F8,
    KC_F9,
    KC_F10,
    KC_NUMLOCK,
    KC_SCROLL,
    KC_NUMPAD7,
    KC_NUMPAD8,
    KC_NUMPAD9,
    KC_SUBTRACT,
    KC_NUMPAD4,
    KC_NUMPAD5,
    KC_NUMPAD6,
    KC_ADD,
    KC_NUMPAD1,
    KC_NUMPAD2,
    KC_NUMPAD3,
    KC_NUMPAD0,
    KC_DECIMAL,
    KC_OEM_102,
    KC_F11,
    KC_F12,
    KC_NUMPADEQUALS,
    KC_PREVTRACK,
    KC_AT,
    KC_COLON,
    KC_UNDERLINE,
    KC_STOP,
    KC_AX,
    KC_UNLABELED,
    KC_NEXTTRACK,
    KC_NUMPADENTER,
    KC_RCONTROL,
    KC_MUTE,
    KC_CALCULATOR,
    KC_PLAYPAUSE,
    KC_MEDIASTOP,
    KC_VOLUMEDOWN,
    KC_VOLUMEUP,
    KC_WEBHOME,
    KC_NUMPADCOMMA,
    KC_DIVIDE,
    KC_SYSRQ,
    KC_RMENU,
    KC_PAUSE,
    KC_HOME,
    KC_UP,
    KC_PRIOR,
    KC_LEFT,
    KC_RIGHT,
    KC_END,
    KC_DOWN,
    KC_NEXT,
    KC_INSERT,
    KC_DELETE,
    KC_LWIN,
    KC_RWIN,
    KC_APPS,
    KC_POWER,
    KC_SLEEP,
    KC_WAKE,
    KC_MEDIASELECT
};
Function Documentation
ClearKey()
proto native void ClearKey (KeyCode key)
Clears the key state. Call this function if you want to overcome autorepeating in reporting key state. If called, the KeyState returns pressed only after the key is released and pressed again.
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), and WeaponDebug::OnCommandHandlerUpdate().
KeyState()
proto native int KeyState (KeyCode key)
Gets key state
Parameters
key Key code
Returns
0 when not pressed, 15. bit set when pressed, 0.-14. bit pressed count
Referenced by PluginDayzPlayerDebug_Weapons::CommandHandler(), PluginBase::IsKeyPressed(), and WeaponDebug::OnCommandHandlerUpdate().