DayzKode: Debug Shape API definition
Debug Shape API definition
Debug utilities
Modules
Diag menu API definition
Enumerations
enum CollisionFlags
enum ShapeFlags {
NOZBUFFER , NOZWRITE , WIREFRAME , TRANSP ,
DOUBLESIDE , ONCE , NOOUTLINE , BACKFACE ,
NOCULL , VISIBLE , ADDITIVE
}
enum ShapeType {
BBOX , LINE , SPHERE , CYLINDER ,
DIAMOND , PYRAMID
}
Functions
static proto native Shape Create (ShapeType type, int color, ShapeFlags flags, vector p1, vector p2)
static Shape CreateArrow (vector from, vector to, float size, int color, ShapeFlags flags)
static Shape CreateBridgeArrow (vector from, vector to, float size, int color, ShapeFlags flags)
static proto native Shape CreateCylinder (int color, ShapeFlags flags, vector origin, float radius, float length)
static proto native Shape CreateFrustum (float horizontalAngle, float verticalAngle, float length, int color, ShapeFlags flags)
static proto native Shape CreateLines (int color, ShapeFlags flags, vector p[], int num)
static void CreateMatrix (vector mat[4])
static proto native Shape CreateSphere (int color, ShapeFlags flags, vector origin, float radius)
static proto native Shape CreateTris (int color, ShapeFlags flags, vector p[], int num)
proto native void Destroy ()
Cleans up the Effect, including unregistering if needed.
proto native void GetMatrix (out vector mat[4])
proto native void SetColor (int color)
proto native void SetDirection (vector direction)
proto native void SetFlags (ShapeFlags flags)
proto native void SetMatrix (vector mat[4])
proto native void SetPosition (vector position)
Set the world position of the Effect.
Variables
enum ShapeType ErrorEx
class DiagMenu Shape ()
don't call destructor directly. Use Destroy() instead
Destroy
Methods regarding automatic cleanup
void SetAutodestroy (bool auto_destroy)
Sets whether Effect automatically cleans up when it stops.
bool IsAutodestroy ()
Get whether Effect automatically cleans up when it stops.
bool IsPendingDeletion ()
Get whether the Effect is queued up for being cleaned up.
void SetEnableEventFrame (bool enable)
Enable Event_OnFrameUpdate for the effect.
Detailed Description
Enumeration Type Documentation
CollisionFlags
enum CollisionFlags
Definition at line 140 of file endebug.c.
{
    FIRSTCONTACT,   //<In many cases only collided=true/false is enough
    NEARESTCONTACT  //<We want only one, the nearest contact
    ONLYSTATIC      //<Only static objects
    ONLYDYNAMIC     //<Only dynamic objects
    ONLYWATER       //<Only water components (legacy support for "walk on geometry")
    ALLOBJECTS      //<Valid when CF_FIRST_CONTACT, we get first contact for each object
}
ShapeFlags
enum ShapeFlags
Enumerator
NOZBUFFER
NOZWRITE
WIREFRAME
TRANSP
DOUBLESIDE
ONCE
NOOUTLINE
BACKFACE
NOCULL
VISIBLE
Entity is visible. Is rendered if there is some attached object and event EntityEvent.VISIBLE is invoked, when event mask is set.
ADDITIVE
Definition at line 125 of file endebug.c.
{
    NOZBUFFER,  //< Do not compare z-buffer when render
    NOZWRITE,       //< Do not update z-buffer when render
    WIREFRAME,  //< Render just wire-frame outline. No solid faces
    TRANSP,         //< Is translucent
    DOUBLESIDE, //< Double-sided (do not cull back-faces)
    ONCE,               //< Rendered just once and then it's automatically destroyed. Do not keep pointer to these!!
    NOOUTLINE,  //< Render just solid faces. No wire-frame outline.
    BACKFACE,       //< Render just back faces
    NOCULL,         //< Do not cull shapes by view frustum
    VISIBLE,        //< Make it visible. Set by default
    ADDITIVE        //< Additive blending (works with ShapeFlags.TRANSP)
};
ShapeType
enum ShapeType
Enumerator
BBOX
LINE
SPHERE
CYLINDER
DIAMOND
PYRAMID
Definition at line 115 of file endebug.c.
{
    BBOX,           //< Just box
    LINE,           //< One or more lines
    SPHERE,     //< Sphere represented by triangle mesh
    CYLINDER,   //< Cylinder represented by triangle mesh
    DIAMOND,    //< Eight faced pyramid. Defined by bound-box, where middle part is  equal to horizontal extents of box and top/bottom apogees lies on top/bottom side of box.
    PYRAMID //< Four sided pyramid. Defined by bound-box, where base is equal to bottom side of box.
};
Function Documentation
Create()
static proto native Shape Create (ShapeType type, int color, ShapeFlags flags, vector p1, vector p2) static
Referenced by CreateMatrix().
CreateArrow()
static Shape CreateArrow (vector from, vector to, float size, int color, ShapeFlags flags) static
Definition at line 173 of file endebug.c.
    {
        vector dir = to - from;
        dir.Normalize();
        vector dir1 = dir * size;
        size = size * 0.5;
        vector dir2 = dir.Perpend() * size;
        vector pts[5];
        pts[0] = from;
        pts[1] = to;
        pts[2] = to - dir1 - dir2;
        pts[3] = to - dir1 + dir2;
        pts[4] = to;
        return CreateLines(color, flags, pts, 5);
    }
References CreateLines(), vector::Normalize(), and vector::Perpend().
CreateBridgeArrow()
static Shape CreateBridgeArrow (vector from, vector to, float size, int color, ShapeFlags flags) static
Definition at line 192 of file endebug.c.
    {
        vector dir = to - from;
        dir.Normalize();
        vector dir1 = Vector(0, 0, -size);
        size = size * 0.5;
        vector dir2 = dir.Perpend() * size;
        vector pts[7];
        pts[0] = from;
        pts[1] = from + "0 0 1";
        pts[2] = to + "0 0 1";
        pts[3] = to;
        pts[4] = to - dir1 - dir2;
        pts[5] = to - dir1 + dir2;
        pts[6] = to;
        return CreateLines(color, flags, pts, 7);
    }
References CreateLines(), vector::Normalize(), vector::Perpend(), and Vector().
CreateCylinder()
static proto native Shape CreateCylinder (int color, ShapeFlags flags, vector origin, float radius, float length) static
CreateFrustum()
static proto native Shape CreateFrustum (float horizontalAngle, float verticalAngle, float length, int color, ShapeFlags flags) static
CreateLines()
static proto native Shape CreateLines (int color, ShapeFlags flags, vector p[], int num) static
Referenced by CreateArrow(), and CreateBridgeArrow().
CreateMatrix()
static void CreateMatrix (vector mat[4]) static
Definition at line 214 of file endebug.c.
    {
        vector org = mat[3];
        int flags = ShapeFlags.NOZWRITE|ShapeFlags.DOUBLESIDE|ShapeFlags.TRANSP|ShapeFlags.ONCE;
        Create(ShapeType.LINE, 0xffff0000, flags, org, mat[0] * 0.5 + org);
        Create(ShapeType.LINE, 0xff00ff00, flags, org, mat[1] * 0.5 + org);
        Create(ShapeType.LINE, 0xff0000ff, flags, org, mat[2] * 0.5 + org);
    }
References Create().
CreateSphere()
static proto native Shape CreateSphere (int color, ShapeFlags flags, vector origin, float radius) static
CreateTris()
static proto native Shape CreateTris (int color, ShapeFlags flags, vector p[], int num) static
Destroy()
proto native void Destroy ()
Cleans up the Effect, including unregistering if needed.
Note
Will stop the Effect and queue up the deletion in the callqueue
Is intended for usage from within the Effect itself, use SEffectManager.DestroyEffect when working from a pointer
Cleans up the Effect, including unregistering if needed.
Definition at line 212 of file effect.c.
    {
        // Already queued
        if (IsPendingDeletion())
            return;
        // Mark it to prevent queuing it up multiple times or get stuck in a call loop
        m_IsPendingDeletion = true;
        // Stop it, so that the effects can clean up themselves
        // Since if for example this is EffectParticle and the particle is looping
        // It NEEDS to be stopped to clean up the Particle
        Stop();
        // Queue up the destroying, as we should not do it while we are accessing it here
        if (GetGame())
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).Call(SEffectManager.DestroyEffect, this);
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_GAMEPLAY, DestroyDamageTriggerEx(), SEffectManager::DestroyEffect(), CGame::GetCallQueue(), GetGame(), IsPendingDeletion(), m_IsPendingDeletion, AreaDamageEvents::OnTriggerDestroyed(), and Stop().
Referenced by EntityLightSource::CheckLifetime(), EntityLightSource::HandleBrightnessFadeing(), EntityLightSource::HandleRadiusFadeing(), and ~AreaDamageManager().
GetMatrix()
proto native void GetMatrix (out vector mat[4])
IsAutodestroy()
bool IsAutodestroy ()
Get whether Effect automatically cleans up when it stops.
Returns
bool Whether Effect automatically cleans up when it stops
Definition at line 247 of file effect.c.
    {
        return m_IsAutodestroy;
    }
References m_IsAutodestroy.
IsPendingDeletion()
bool IsPendingDeletion ()
Get whether the Effect is queued up for being cleaned up.
Returns
bool Whether the Effect is queued up for being cleaned up
Definition at line 256 of file effect.c.
    {
        return m_IsPendingDeletion;
    }
References m_IsPendingDeletion.
Referenced by Destroy().
SetAutodestroy()
void SetAutodestroy (bool auto_destroy)
Sets whether Effect automatically cleans up when it stops.
Note
This means that it will be unregistered from SEffectManager as well
Parameters
auto_destroy bool Whether Effect automatically cleans up when it stops
Definition at line 238 of file effect.c.
    {
        m_IsAutodestroy = auto_destroy;
    }
References m_IsAutodestroy.
SetColor()
proto native void SetColor (int color)
SetDirection()
proto native void SetDirection (vector direction)
SetEnableEventFrame()
void SetEnableEventFrame (bool enable)
Enable Event_OnFrameUpdate for the effect.
Note
Read SEffectManager.Event_OnFrameUpdate for more info
Definition at line 269 of file effect.c.
    {
        if ( enable )
        {
            SEffectManager.Event_OnFrameUpdate.Insert(Event_OnFrameUpdate);
        }
        else
        {
            SEffectManager.Event_OnFrameUpdate.Remove(Event_OnFrameUpdate);
        }
    }
References Event_OnFrameUpdate(), SEffectManager::Event_OnFrameUpdate, ScriptInvoker::Insert(), and ScriptInvoker::Remove().
Referenced by EffEngineSmoke::EffEngineSmoke(), EffectSound::UpdateEvents(), and ~Effect().
SetFlags()
proto native void SetFlags (ShapeFlags flags)
Referenced by DayZCreature::DayZCreatureAI(), DynamicArea_Flare::DynamicArea_Flare(), EasterEgg(), EntityAI::Man(), Particle::ParticleInit(), and Trigger::Trigger().
SetMatrix()
proto native void SetMatrix (vector mat[4])
SetPosition()
proto native void SetPosition (vector pos)
Set the world position of the Effect.
Warning
Only sets the cached variable, for immediate effect use SetCurrent variant
Parameters
pos vector The world position for the Effect
Definition at line 427 of file effect.c.
    {
        m_Position = pos;
    }
References m_Position.
Referenced by Particle::AddAsChild(), EntityLightSource::AttachOnObject(), ScriptedWidgetEventHandler::CreateFollowedObject(), DynamicArea_Flare::EOnFrame(), DayZSpectator::EOnFrame(), ScriptedWidgetEventHandler::GetPosition(), EntityLightSource::HandleDancingShadows(), PointLightBase::OnFrameLightSource(), ItemBase::PlaceOnGround(), SetCurrentPosition(), TrapSpawnBase::SetupTrap(), SetupTrapPlayer(), ItemBase::SetupTrapPlayer(), Particle::StopParticle(), and UnlockServer().
Variable Documentation
ErrorEx
enum ShapeType ErrorEx
Referenced by And(), ScriptedWidgetEventHandler::Apply(), Assert(), EntityLightSource::AttachOnMemoryPoint(), WeaponParticlesBase::CheckParticleOverride(), SEffectManager::Cleanup(), ConstructData(), EmoteConstructor::ConstructEmotes(), CreateBleedingEffect(), Particle::CreateParticleEffect(), ParticleSource::CreateParticleEffect(), CreateParticleEx(), ParticleSource::CreateParticleEx(), Weapon::CreateWeaponWithAmmo(), ParticleSource::DestroyParticleEffect(), array< Class T >::DifferentAtPosition(), Effect(), SEffectManager::EffectRegister(), EmoteBase::EmoteFBStanceCheck(), ParticleSource::EOnFrame(), MenuDefaultCharacterData::EquipDefaultCharacter(), EvaluateImpactEffect(), Math::Factorial(), FireworksLauncher::GetColorSequence(), GetControlMappingInfo(), UIScriptedMenu::GetControlMappingInfo(), HitDirectionEffectBase::GetCurrentType(), Weapon_Base::GetCylinderRotation(), FireworksLauncherClientEvent::GetExplParticleFromSequence(), GetLastClientMessage(), GetLastServerMessage(), GetLightPosition(), GetMemoryPointPosition(), Weapon::GetMuzzleStates(), ParticleList::GetParticleID(), ParticleList::GetParticleIDByName(), ParticleList::GetParticlePath(), GameplayEffectsData::GetProbabilities(), DayZProfilesOptions::GetProfileOptionDefault(), GetStringVariant(), Hologram::Hologram(), Init(), Interact(), InventoryMovementButtonTickHandler(), Hologram::IsBehindObstacle(), IsFacingFireplace(), IsParticlePlaying(), AmmoTypesAPI::MagazineTypeToAmmoType(), WeaponParticlesBase::OnActivate(), ParticleSource::OnCheckAutoDelete(), OnErrorThrown(), ActionDigInStash::OnFinishProgressServer(), OnFinishProgressServer(), ActionUnrestrainTargetHands::OnFinishProgressServer(), OnInit(), CfgGameplayHandler::OnRPC(), UndergroundAreaLoader::OnRPC(), ParticleSource::OnToDelete(), Or(), EffectArea::PlaceParticles(), SEffectManager::PlayOnObject(), PlayParticle(), DestructionEffectBase::PlayParticle(), PlayParticleEx(), PlaySoundSetAtMemoryPoint(), HFSMBase< WeaponStateBase, WeaponEventBase, WeaponActionBase, WeaponGuardBase >::RandomizeFSMStateEx(), GameplayEffectsData::RegisterData(), ParticleList::RegisterParticle(), ResetParticle(), RestartParticle(), TFModule::Run(), array::Run(), ManBase::SetHairLevelToHide(), FireworksLauncherClientEvent::SetupLight(), InventoryItemSuper::ShowReddot(), EffectSound::SoundError(), Weapon::SpawnAttachedMagazine(), SEffectManager::Stop(), StopParticle(), EnProfilerTests::TestFuncCountData(), UnregisterEntrance(), UnregisterPanel(), ParticleSource::UpdateState(), ValidateMuzzleArray(), EffectParticle::ValidateStart(), and WeaponParticlesBase::WeaponParticlesBase().
Shape
enum CollisionFlags Shape ()
don't call destructor directly. Use Destroy() instead
Instance of created debug visualizer
Referenced by ComponentEnergyManager::DrawArrow(), Debug::DrawArrow(), Debug::DrawBoxEx(), Debug::DrawCube(), Debug::DrawCylinder(), Debug::DrawFrustum(), UIScriptedMenu::DrawItems(), UIScriptedMenu::DrawItemsClear(), Debug::DrawLine(), Debug::DrawLines(), Debug::DrawSphere(), ManBase::EOnPostFrame(), OnUpdate(), and Debug::RemoveShape().