DayzKode: System
System
Modules
Keyboard input API
Mouse API
returns index of defined key in InputDevice by its name
API
FileIO API
Functions
proto int GetAddons (string addonNames[])
returns all addons
proto bool GetCLIParam (string param, out string val)
Returns command line argument.
proto void GetHourMinuteSecond (out int hour, out int minute, out int second)
Returns world time.
proto void GetHourMinuteSecondUTC (out int hour, out int minute, out int second)
Returns UTC world time.
proto string GetMachineName ()
proto int GetPlugins (string pluginNames[])
returns all plugins (addons and mods)
proto string GetProfileName ()
proto void GetYearMonthDay (out int year, out int month, out int day)
Returns world date.
proto void GetYearMonthDayUTC (out int year, out int month, out int day)
Returns UTC world date.
proto native bool IsCLIParam (string param)
Returns if command line argument is present.
proto native void MemoryValidation (bool enable)
Switches memory validation (huge slowdown! Use with care only for certain section of code!)
proto native int TickCount (int prev)
performance counter. Returns number of CPU ticks between 'prev' and 'now'
Variables
ALL
<Looks in archives and fs directories.
ARCHIVES
Looks for files in archive only. (.pak)
DIRECTORIES
Looks for files in fs directories only.
Detailed Description
Function Documentation
GetAddons()
proto int GetAddons (string addonNames[])
returns all addons
GetCLIParam()
proto bool GetCLIParam (string param, out string val)
Returns command line argument.
Parameters
name of a command line argument
val string value of the param or empty string if the param hasn't been found
Returns
True if param is present, False if hasn't been found
string param;
GetCLIParam("world", param); // return a value when program executed with param -world something
Referenced by ConnectFromCLI(), JoinLaunch(), MissionLaunch(), OnInitialize(), PartyLaunch(), SelectGamepad(), and PlayerBase::UpdatePersonalLight().
GetHourMinuteSecond()
proto void GetHourMinuteSecond (out int hour, out int minute, out int second)
Returns world time.
Parameters
[out] hour int Hour
[out] minute int Minute
[out] second int Second
Returns
void
int hour = 0;
int minute = 0;
int second = 0;
GetHourMinuteSecondUTC(hour, minute, second);
Print(hour);
Print(minute);
Print(second);
>> hour = 16
>> minute = 38
>> second = 7
Referenced by Debug::GetDate(), and ManBase::UpdatePlayerMeasures().
GetHourMinuteSecondUTC()
proto void GetHourMinuteSecondUTC (out int hour, out int minute, out int second)
Returns UTC world time.
Parameters
[out] hour int Hour
[out] minute int Minute
[out] second int Second
Returns
void
int hour = 0;
int minute = 0;
int second = 0;
GetHourMinuteSecondUTC(hour, minute, second);
Print(hour);
Print(minute);
Print(second);
>> hour = 15
>> minute = 38
>> second = 7
GetMachineName()
proto string GetMachineName ()
GetPlugins()
proto int GetPlugins (string pluginNames[])
returns all plugins (addons and mods)
GetProfileName()
proto string GetProfileName ()
GetYearMonthDay()
proto void GetYearMonthDay (out int year, out int month, out int day)
Returns world date.
Parameters
[out] year int Year
[out] month int Month
[out] day int Day
Returns
void
int year = 0;
int month = 0;
int day = 0;
GetYearMonthDay(year, month, day);
Print(year);
Print(month);
Print(day);
>> year = 2015
>> month = 3
>> day = 24
Referenced by Debug::GetDate().
GetYearMonthDayUTC()
proto void GetYearMonthDayUTC (out int year, out int month, out int day)
Returns UTC world date.
Parameters
[out] year int Year
[out] month int Month
[out] day int Day
Returns
void
int year = 0;
int month = 0;
int day = 0;
GetYearMonthDayUTC(year, month, day);
Print(year);
Print(month);
Print(day);
>> year = 2015
>> month = 3
>> day = 24
IsCLIParam()
proto native bool IsCLIParam (string param)
Returns if command line argument is present.
Parameters
name of a command line argument
Returns
True if param is present, False if hasn't been found
if (IsCLIParam("verbose")) // Prints "something" when program executed with param -verbose
{
    Print("something");
}
Referenced by LogManager::Init().
MemoryValidation()
proto native void MemoryValidation (bool enable)
Switches memory validation (huge slowdown! Use with care only for certain section of code!)
Parameters
enable bool Enable
Returns
void
???
TickCount()
proto native int TickCount (int prev)
performance counter. Returns number of CPU ticks between 'prev' and 'now'
Variable Documentation
ALL
@ ALL
<Looks in archives and fs directories.
Looks in archives and fs directories.
Definition at line 2 of file ensystem.c.
ARCHIVES
ARCHIVES
Looks for files in archive only. (.pak)
Definition at line 1 of file ensystem.c.
DIRECTORIES
DIRECTORIES
Looks for files in fs directories only.
Definition at line 0 of file ensystem.c.