DayzKode: Widget UI system
Widget UI system
Classes
class BaseListboxWidget
class ScriptedWidgetEventHandler
map: item x vector(index, width, height)
class SimpleListboxWidget
class SimpleProgressBarWidget
class SpacerWidget
class TextWidget
class UIWidget
class Widget
class WorkspaceWidget
Typedefs
typedef TypeID EventType
typedef TypeID WidgetType
Enumerations
enum ControlID {
CID_NONE = 0 , CID_SELECT = 1 , CID_BACK , CID_LEFT ,
CID_RIGHT , CID_UP , CID_DOWN , CID_MENU ,
CID_DRAG , CID_TABLEFT , CID_TABRIGHT , CID_RADIALMENU ,
CID_COUNT
}
enum VideoCommand {
PLAY , STOP , REWIND , POSITION ,
REPEAT , ISPLAYING , KILL
}
enum WidgetAlignment
enum WidgetFlags {
SOURCEALPHA , BLEND , ADDITIVE , VISIBLE ,
NOWRAP , CENTER , VCENTER , HEXACTPOS ,
VEXACTPOS , EXACTPOS , HEXACTSIZE , VEXACTSIZE ,
EXACTSIZE , NOFILTER , RALIGN , STRETCH ,
FLIPU , FLIPV , CUSTOMUV , IGNOREPOINTER ,
DISABLED , NOFOCUS , CLIPCHILDREN , RENDER_ALWAYS ,
NOCLEAR , DRAGGABLE
}
Functions
proto native void AddChild (Widget child, bool immedUpdate=true)
proto native void AddChildAfter (Widget child, Widget after, bool immedUpdate=true)
proto native void UIWidget::AddChildAfter (Widget child, Widget after, bool immedUpdate=true)
proto native int UIWidget::AddItem (string item)
proto native int SimpleListboxWidget::AddItem (string text, Class userData, int column, int row=-1)
Insert new Row, if row = -1, new Row is inserted at the end otherwise at row index.
proto native Widget CancelWidgetDragging ()
proto native void Widget::Clear ()
proto native void UIWidget::ClearAll ()
proto native int ClearFlags (int flags, bool immedUpdate=true)
proto native void UIWidget::ClearItems ()
proto native external Widget WorkspaceWidget::CreateWidget (WidgetType type, int left, int top, int width, int height, WidgetFlags flags, int color, int sort, Widget parentWidget=NULL)
Create widgets by WidgetType.
proto native external Widget WorkspaceWidget::CreateWidgets (string layout, Widget parentWidget=NULL, bool immedUpdate=true)
Create widgets from *.layout file.
proto native void Widget::DisableSubtitles (bool disable)
proto native void Widget::DrawLine (float x1, float y1, float x2, float y2, float width, int color)
proto native void TextWidget::ElideText (int line, float maxWidth, string str)
proto native void Enable (bool enable)
proto native void UIWidget::EnsureVisible (int row)
proto native Widget FindAnyWidget (string pathname)
proto native Widget FindAnyWidgetById (int user_id)
proto native Widget FindWidget (string pathname)
proto native float GetAlpha ()
proto native bool Widget::GetBold ()
proto native int TextWidget::GetCarriageLine ()
proto native int TextWidget::GetCarriagePos ()
proto native Widget GetChildren ()
proto native int GetColor ()
class SpacerBaseWidget extends UIWidget GetContentAlignmentH ()
proto native WidgetAlignment GetContentAlignmentV ()
proto native float TextWidget::GetContentHeight ()
proto native float GetContentHeight ()
proto native float TextWidget::GetContentOffset ()
proto native float GetContentWidth ()
proto native float UIWidget::GetCurrent ()
proto native int UIWidget::GetCurrentItem ()
proto native Widget GetDragWidget ()
proto native int GetFlags ()
proto native Widget GetFocus ()
proto native float GetHScrollPos ()
proto native float GetHScrollPos01 ()
proto native int Widget::GetImage ()
Returns active image.
proto void Widget::GetImageSize (int image, out int sx, out int sy)
returns size of image
proto native bool Widget::GetItalic ()
proto void SimpleListboxWidget::GetItemData (int row, int column, out Class data)
proto bool SimpleListboxWidget::GetItemText (int row, int column, out string text)
Get item.
proto void TextWidget::GetLine (int line, out string text)
proto native int TextWidget::GetLinesCount ()
proto native float TextWidget::GetLineWidth (int line)
proto native float Widget::GetMaskProgress ()
proto native float Widget::GetMaskTransitionWidth ()
proto native float UIWidget::GetMax ()
proto native float UIWidget::GetMin ()
proto native owned string GetName ()
proto native int UIWidget::GetNumItems ()
proto native int TextWidget::GetNumLines ()
proto native int Widget::GetOutlineColor ()
proto native int Widget::GetOutlineSize ()
proto native Widget GetParent ()
Get parent of the Effect.
proto void GetPos (out float x, out float y)
proto void GetScreenPos (out float x, out float y)
proto void GetScreenSize (out float width, out float height)
proto void GetScript (out Class data)
proto native int UIWidget::GetSelectedRow ()
proto native int Widget::GetShadowColor ()
proto void Widget::GetShadowOffset (out float sx, out float sy)
proto native float Widget::GetShadowOpacity ()
proto native int Widget::GetShadowSize ()
proto native Widget GetSibling ()
proto void GetSize (out float width, out float height)
proto native int GetSort ()
proto native bool UIWidget::GetState ()
proto native float UIWidget::GetStep ()
proto native owned string GetStyleName ()
proto string UIWidget::GetText ()
proto void TextWidget::GetText (out string text)
proto native bool Widget::GetTextBold ()
proto native bool Widget::GetTextItalic ()
proto native int Widget::GetTextOutlineColor ()
proto native int Widget::GetTextOutlineSize ()
proto native float Widget::GetTextProportion ()
Get text proportion - ratio between button height and button text height in interval <0,1>
proto native float UIWidget::GetTextProportion ()
Get text proportion - ratio between button height and button text height in interval <0,1>
proto native int Widget::GetTextShadowColor ()
proto native float Widget::GetTextShadowOffsetX ()
proto native float Widget::GetTextShadowOffsetY ()
proto native float Widget::GetTextShadowOpacity ()
proto native int Widget::GetTextShadowSize ()
proto void Widget::GetTextSize (out int sx, out int sy)
Returns text size in pixels.
proto native WidgetType GetTypeID ()
proto native owned string GetTypeName ()
proto void GetUserData (out Class data)
proto native int GetUserID ()
proto native float GetVScrollPos ()
proto native float GetVScrollPos01 ()
proto native Widget GetWidgetUnderCursor ()
proto native bool HScrollStep (int steps)
proto native void HScrollToPos (float pos)
proto native void HScrollToPos01 (float pos01)
proto native void HScrollToWidget (Widget child)
proto native bool UIWidget::IsChecked ()
proto native bool IsControlClass ()
proto native bool IsScrollbarVisible ()
proto native bool IsVisible ()
proto native bool IsVisibleHierarchy ()
proto native bool Widget::LoadImageFile (int num, string name, bool noCache=false)
proto native bool Widget::LoadMaskTexture (string resource)
proto native bool Widget::LoadVideo (string name, int soundScene)
proto native bool LoadWidgetImageSet (string filename)
proto native void LoadWidgetStyles (string filename)
bool ScriptedWidgetEventHandler::OnChange (Widget w, int x, int y, bool finished)
bool ScriptedWidgetEventHandler::OnChildAdd (Widget w, Widget child)
bool ScriptedWidgetEventHandler::OnChildRemove (Widget w, Widget child)
bool ScriptedWidgetEventHandler::OnClick (Widget w, int x, int y, int button)
bool ScriptedWidgetEventHandler::OnController (Widget w, int control, int value)
control is one of ControlID
bool ScriptedWidgetEventHandler::OnDoubleClick (Widget w, int x, int y, int button)
bool ScriptedWidgetEventHandler::OnDrag (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnDragging (Widget w, int x, int y, Widget reciever)
bool ScriptedWidgetEventHandler::OnDraggingOver (Widget w, int x, int y, Widget reciever)
bool ScriptedWidgetEventHandler::OnDrop (Widget w, int x, int y, Widget reciever)
bool ScriptedWidgetEventHandler::OnDropReceived (Widget w, int x, int y, Widget reciever)
bool ScriptedWidgetEventHandler::OnEvent (EventType eventType, Widget target, int parameter0, int parameter1)
bool ScriptedWidgetEventHandler::OnFocus (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnFocusLost (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn)
bool ScriptedWidgetEventHandler::OnKeyDown (Widget w, int x, int y, int key)
bool ScriptedWidgetEventHandler::OnKeyPress (Widget w, int x, int y, int key)
bool ScriptedWidgetEventHandler::OnKeyUp (Widget w, int x, int y, int key)
bool ScriptedWidgetEventHandler::OnModalResult (Widget w, int x, int y, int code, int result)
bool ScriptedWidgetEventHandler::OnMouseButtonDown (Widget w, int x, int y, int button)
bool ScriptedWidgetEventHandler::OnMouseButtonUp (Widget w, int x, int y, int button)
bool ScriptedWidgetEventHandler::OnMouseEnter (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnMouseLeave (Widget w, Widget enterW, int x, int y)
bool ScriptedWidgetEventHandler::OnMouseWheel (Widget w, int x, int y, int wheel)
bool ScriptedWidgetEventHandler::OnResize (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnSelect (Widget w, int x, int y)
bool ScriptedWidgetEventHandler::OnUpdate (Widget w)
proto native int Widget::Play (VideoCommand cmd)
proto native bool ReloadTexture (string path)
proto native void RemoveChild (Widget child)
proto native void UIWidget::RemoveItem (int item)
proto native void UIWidget::RemoveRow (int row)
proto native void ReportMouse (int mousex, int mousey, Widget rootWidget)
proto native void UIWidget::SelectRow (int row)
proto native bool SetActiveWindow (Widget w, bool resetFocus)
proto native void SetAlpha (float alpha)
proto native void Widget::SetBold (bool bold)
proto native void UIWidget::SetChecked (bool checked)
proto native void SetColor (int color)
proto native void SetContentAlignmentH (WidgetAlignment alignment)
proto native void SetContentAlignmentV (WidgetAlignment alignment)
proto native void TextWidget::SetContentOffset (float offset, bool snapToLine=false)
proto native void UIWidget::SetCurrent (float curr)
proto native int UIWidget::SetCurrentItem (int n)
proto native void SetCursorWidget (Widget cursor)
proto native int SetFlags (int flags, bool immedUpdate=true)
proto native void SetFocus (Widget w)
proto native void SetGUIWidget (IEntity ent, int index, RTTextureWidget w)
proto native void SetHandler (ScriptedWidgetEventHandler eventHandler)
proto native bool Widget::SetImage (int num)
proto native void Widget::SetImageTexture (int image, RTTextureWidget texture)
proto native void Widget::SetItalic (bool italic)
proto native void UIWidget::SetItem (int item, string value)
proto native void SimpleListboxWidget::SetItem (int position, string text, Class userData, int column)
proto native void SimpleListboxWidget::SetItemColor (int row, int column, int color)
proto native void TextWidget::SetLine (int line, string text)
proto native float TextWidget::SetLineBreakingOverride (int mode)
proto native void TextWidget::SetLinesVisibility (int lineFrom, int lineTo, bool visible)
proto native void Widget::SetMaskProgress (float value)
proto native void Widget::SetMaskTransitionWidth (float value)
proto native void UIWidget::SetMinMax (float minimum, float maximum)
proto native void SetModal (Widget w)
proto native void SetName (string name)
proto native void Widget::SetOutline (int outlineSize, int argb=0xFF000000)
proto native void SetPos (float x, float y, bool immedUpdate=true)
proto native void Widget::SetRefresh (int period, int offset)
when period > 1 then every n-th frame will be rendered. Offset is initial counter.
proto native void Widget::SetResolutionScale (float xscale, float ycale)
proto native void SetRotation (float roll, float pitch, float yaw, bool immedUpdate=true)
proto native void Widget::SetShadow (int shadowSize, int shadowARGB=0xFF000000, float shadowOpacity=1, float shadowOffsetX=0, float shadowOffsetY=0)
proto native void SetSize (float x, float y, bool immedUpdate=true)
proto native void SetSort (int sort, bool immedUpdate=true)
proto native bool UIWidget::SetState (bool state)
proto native void UIWidget::SetStep (float step)
proto native void UIWidget::SetText (string str)
proto native void Widget::SetText (string text, bool immedUpdate=true)
proto native void Widget::SetTextBold (bool bold)
proto native void Widget::SetTextColor (int color)
proto native void Widget::SetTextExactSize (int size)
set text exact size. Exact Text flag must be enabled. 0 equals original size.
proto void Widget::SetTextFormat (string text, void param1=NULL, void param2=NULL, void param3=NULL, void param4=NULL, void param5=NULL, void param6=NULL, void param7=NULL, void param8=NULL, void param9=NULL)
proto native void UIWidget::SetTextHorizontalAlignment (int align)
proto native void Widget::SetTextItalic (bool italic)
proto native void UIWidget::SetTextOffset (float xoffset, float yoffset)
proto native void Widget::SetTextOffset (int left, int top)
proto native void Widget::SetTextOutline (int outlineSize, int argb=0xFF000000)
proto native void Widget::SetTextProportion (float val)
Set text proportion - ratio between button height and button text height in interval <0,1>
proto native void UIWidget::SetTextProportion (float val)
Set text proportion - ratio between button height and button text height in interval <0,1>
proto native void Widget::SetTextShadow (int shadowSize, int shadowARGB=0xFF000000, float shadowOpacity=1.0, float shadowOffsetX=0.0, float shadowOffsetY=0.0)
proto native void Widget::SetTextSpacing (int horiz, int vert)
proto native void UIWidget::SetTextVerticalAlignment (int align)
proto native void SetTransform (vector mat[4], bool immedUpdate=true)
proto native void SetUserData (Class data)
proto native void SetUserID (int id)
proto native void Widget::SetUV (float uv[4][2])
proto native void SetWidgetWorld (RenderTargetWidget w, IEntity wrldEntity, int camera)
proto native void Show (bool show, bool immedUpdate=true)
proto native void ShowCursorWidget (bool show)
static proto string TranslateString (string stringId)
proto native void Unlink ()
proto native volatile void Update ()
proto native bool VScrollStep (int steps)
proto native void VScrollToPos (float pos)
proto native void VScrollToPos01 (float pos01)
proto native void VScrollToWidget (Widget child)
Variables
enum VideoCommand GetScrollbarWidth
WA_BOTTOM = 1
WA_CENTER = 2
WA_LEFT = 0
WA_RIGHT = 1
WA_TOP = 0
WorkspaceWidget Widget ()
Defined in code.
Detailed Description
Typedef Documentation
EventType
typedef TypeID EventType
Definition at line 54 of file enwidgets.c.
WidgetType
typedef TypeID WidgetType
Definition at line 51 of file enwidgets.c.
Enumeration Type Documentation
ControlID
enum ControlID
Enumerator
CID_NONE
CID_SELECT
CID_BACK
CID_LEFT
CID_RIGHT
CID_UP
CID_DOWN
CID_MENU
CID_DRAG
CID_TABLEFT
CID_TABRIGHT
CID_RADIALMENU
CID_COUNT
Definition at line 507 of file enwidgets.c.
{
    CID_NONE = 0,
    CID_SELECT = 1,//select/use focused
    CID_BACK,
    CID_LEFT, //navigation
    CID_RIGHT,
    CID_UP,
    CID_DOWN,
    CID_MENU, //get to main menu
    CID_DRAG, //probably needed only for consoles
    CID_TABLEFT,
    CID_TABRIGHT,
    CID_RADIALMENU,
    CID_COUNT
};
VideoCommand
enum VideoCommand
Enumerator
PLAY
STOP
REWIND
POSITION
REPEAT
ISPLAYING
KILL
Definition at line 484 of file enwidgets.c.
{
    PLAY,
    STOP,
    REWIND,
    POSITION,
    REPEAT,
    ISPLAYING,
    KILL
};
WidgetAlignment
enum WidgetAlignment
Definition at line 87 of file enwidgets.c.
{
    WA_LEFT         = 0,
    WA_RIGHT        = 1,
    WA_CENTER       = 2,
    WA_TOP          = 0,
    WA_BOTTOM       = 1,
}
WidgetFlags
enum WidgetFlags
Enumerator
SOURCEALPHA
BLEND
ADDITIVE
VISIBLE
NOWRAP
CENTER
VCENTER
HEXACTPOS
VEXACTPOS
EXACTPOS
HEXACTSIZE
VEXACTSIZE
EXACTSIZE
NOFILTER
RALIGN
STRETCH
FLIPU
FLIPV
CUSTOMUV
IGNOREPOINTER
DISABLED
NOFOCUS
CLIPCHILDREN
RENDER_ALWAYS
NOCLEAR
DRAGGABLE
Definition at line 56 of file enwidgets.c.
{
    SOURCEALPHA, //< takes alpha from texture * alpha from color. If not set, considers texture as non-transparent and transparency is set only by color
    BLEND,  //< texture is blended with a surface base on alpha
    ADDITIVE,   //< texture is added to a surface based on alpha
    VISIBLE,    //<Widget is visible - ShowWidget(w, true)
    NOWRAP, //< Do not do texture wrapping
    CENTER, //< Centers TextWidgetTypeID
    VCENTER,    //< Centers TextWidgetTypeID verticaly
    HEXACTPOS,
    VEXACTPOS,
    EXACTPOS,   //< Uses physical resolution (g_iWidth, h_iHeight)
    HEXACTSIZE, //< Uses physical resolution (g_iWidth)
    VEXACTSIZE, //< Uses physical resolution (h_iHeight)
    EXACTSIZE,  //< Uses physical resolution
    NOFILTER,   //< no texture filtering (no blur)
    RALIGN, //< Right alignment TextWidgetTypeID
    STRETCH,    //< Stretch texture to a full size
    FLIPU,  //< Flips texture in U axis
    FLIPV,  //< Flips texture in V axis
    CUSTOMUV,   //< ignores STRETCH/FLIPU/FLIPV and take custom UV set by SetWidgetUV()
    IGNOREPOINTER,
    DISABLED,
    NOFOCUS,
    CLIPCHILDREN,
    RENDER_ALWAYS,
    NOCLEAR,
    DRAGGABLE
};
Function Documentation
AddChild()
proto native void AddChild (Widget child, bool immedUpdate = true)
Referenced by Particle::AddAsChild(), Particle::CreateParticleEffect(), ManBase::SetDecayEffects(), ManBase::SpawnBreathVaporEffect(), and UndergroundTriggerCarrierBase::SpawnTrigger().
AddChildAfter() [1/2]
proto native void GetContentAlignmentH::AddChildAfter (Widget child, Widget after, bool immedUpdate = true)
AddChildAfter() [2/2]
proto native void UIWidget::AddChildAfter (Widget child, Widget after, bool immedUpdate = true) private
AddItem() [1/2]
proto native int UIWidget::AddItem (string item) private
AddItem() [2/2]
proto native int SimpleListboxWidget::AddItem (string text, Class userData, int column, int row = -1) private
Insert new Row, if row = -1, new Row is inserted at the end otherwise at row index.
CancelWidgetDragging()
proto native Widget CancelWidgetDragging ()
Referenced by Container::CheckHeaderDragability(), SlotsIcon::Clear(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
Clear()
proto native void Widget::Clear () private
Referenced by GameplayEffectWidgets_base::StopAllEffects(), InventoryGridController::UpdateItems(), and GameplayEffectWidgets_base::UpdateVisibility().
ClearAll()
proto native void UIWidget::ClearAll () private
ClearFlags()
proto native int ClearFlags (int flags, bool immedUpdate = true)
Referenced by EEKilled(), Grenade_ChemGas::OnDamageDestroyed(), and Ammo_40mm_Explosive::OnDamageDestroyed().
ClearItems()
proto native void UIWidget::ClearItems () private
CreateWidget()
proto native external Widget WorkspaceWidget::CreateWidget (WidgetType type, int left, int top, int width, int height, WidgetFlags flags, int color, int sort, Widget parentWidget = NULL) private
Create widgets by WidgetType.
Referenced by GameplayEffectWidgets_base::GameplayEffectWidgets().
CreateWidgets()
proto native external Widget WorkspaceWidget::CreateWidgets (string layout, Widget parentWidget = NULL, bool immedUpdate = true) private
Create widgets from *.layout file.
Referenced by AddAgent(), ScriptedWidgetEventHandler::AddItem(), AddModifier(), NotificationUI::AddNotification(), array::AddSubgroup(), ScriptedWidgetEventHandler::AddSubgroup(), ScriptedWidgetEventHandler::AddTab(), HudDebugWinBase::AddValue(), NotificationUI::AddVoiceNotification(), ScriptedWidgetEventHandler::BuildLayout(), ChatLine::ChatLine(), ServerBrowserTab::Construct(), CreateGamepadDisconnectMenu(), PluginBase::CreateModuleWidgets(), CreateModuleWidgets(), CreateTitleScreen(), PluginBase::CreateWidgetOverlay(), CreditsElement::CreditsDepartmentElement(), CreditsDepartmentSection(), CTObjectFollower::CTActor(), ScriptedWidgetEventHandler::CTEvent(), ScriptedWidgetEventHandler::CTKeyframe(), DebugMonitor::DebugMonitor(), ScriptedWidgetEventHandler::DropdownPrefab(), ScriptedWidgetEventHandler::GenerateQuickBarBackgroundTiles(), HitDirectionImagesBase::GetCurrentImageData(), UIScriptedMenu::Init(), Init(), UIScriptedWindow::Init(), ScriptedWidgetEventHandler::Init(), Debug::InitCanvas(), InitializeWidgets(), InitWidgets(), PluginBase::InitWidgets(), ItemManager::ItemManager(), ScriptedWidgetEventHandler::KeybindingElement(), ScriptedWidgetEventHandler::KeybindingElementNew(), array::KeybindingsContainer(), ScriptedWidgetEventHandler::KeybindingsGroup(), UIScriptedMenu::LateInit(), ScriptedWidgetEventHandler::LayoutHolder(), ScriptedWidgetEventHandler::ModsMenuDetailed(), ScriptedWidgetEventHandler::ModsMenuDetailedEntry(), ScriptedWidgetEventHandler::ModsMenuSimple(), ScriptedWidgetEventHandler::ModsMenuTooltip(), NotificationUI::NotificationUI(), OnClick(), MissionBase::OnInit(), OptionSelectorBase::OptionSelector(), OptionSelectorBase::OptionSelectorEditbox(), OptionSelectorSliderSetup::OptionSelectorLevelMarker(), OptionSelectorSliderSetup::OptionSelectorSlider(), ScriptedWidgetEventHandler::OptionsMenuControls(), ScriptedWidgetEventHandler::OptionsMenuGame(), ScriptedWidgetEventHandler::OptionsMenuSounds(), ScriptedWidgetEventHandler::OptionsMenuVideo(), ScriptedWidgetEventHandler::PlayerListEntryScriptedWidget(), ScriptedWidgetEventHandler::PlayerListScriptedWidget(), Refresh(), GameplayEffectWidgets_base::RegisterLayouts(), ScriptedWidgetEventHandler::ServerBrowserEntry(), Hud::ShowPlayerTag(), SoftSkillManagerDebug(), ScriptedWidgetEventHandler::TutorialKeybinds(), and UIPropertyAttachment::UIPropertyAttachment().
DisableSubtitles()
proto native void Widget::DisableSubtitles (bool disable) private
DrawLine()
proto native void Widget::DrawLine (float x1, float y1, float x2, float y2, float width, int color) private
Referenced by DrawConnectingLines(), and UIScriptedMenu::DrawConnectingLines().
ElideText()
proto native void TextWidget::ElideText (int line, float maxWidth, string str) private
Enable()
proto native void Enable (bool enable)
Referenced by OptionSelectorBase::OptionSelector().
EnsureVisible()
proto native void UIWidget::EnsureVisible (int row) private
FindAnyWidget()
proto native Widget FindAnyWidget (string pathname)
Referenced by CargoContainerRow::CargoContainerRow(), ClosableHeader::ClosableHeader(), ClosableContainer::DropReceived(), HandsContainer::ElectricityIcon(), ContainerWithElectricManager::ElectricityIcon(), Header::Header(), Icon::Icon(), Icon::InitEx(), InitWidgets(), PluginBase::InitWidgets(), Inventory(), Header::SetItemPreview(), and SlotsContainer::SlotsContainer().
FindAnyWidgetById()
proto native Widget FindAnyWidgetById (int user_id)
FindWidget()
proto native Widget FindWidget (string pathname)
GetAlpha()
proto native float GetAlpha ()
GetBold()
proto native bool Widget::GetBold () private
GetCarriageLine()
proto native int TextWidget::GetCarriageLine () private
GetCarriagePos()
proto native int TextWidget::GetCarriagePos () private
GetChildren()
proto native Widget GetChildren ()
GetColor()
proto native int GetColor ()
Referenced by InventoryItem::GetColorString().
GetContentAlignmentH()
class SpacerBaseWidget extends UIWidget GetContentAlignmentH ()
GetContentAlignmentV()
proto native WidgetAlignment GetContentAlignmentV ()
GetContentHeight() [1/2]
proto native float TextWidget::GetContentHeight () private
GetContentHeight() [2/2]
proto native float GetContentHeight ()
GetContentOffset()
proto native float TextWidget::GetContentOffset () private
GetContentWidth()
proto native float GetContentWidth ()
GetCurrent()
proto native float UIWidget::GetCurrent () private
GetCurrentItem()
proto native int UIWidget::GetCurrentItem () private
GetDragWidget()
proto native Widget GetDragWidget ()
Referenced by Container::CheckHeaderDragability(), ClosableHeader::MouseEnter(), SlotsIcon::MouseEnter(), SlotsIcon::MouseEnterGhostSlot(), SlotsIcon::MouseLeave(), SlotsIcon::MouseLeaveGhostSlot(), VicinitySlotsContainer::ShowItemsInContainers(), and VicinityContainer::UpdateHeader().
GetFlags()
proto native int GetFlags ()
GetFocus()
proto native Widget GetFocus ()
Referenced by GetNextEntry(), GetPrevEntry(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::Lighten(), OptionSelectorBase::OnFocus(), and UIScriptedMenu::OnModalResult().
GetHScrollPos()
proto native float GetHScrollPos ()
GetHScrollPos01()
proto native float GetHScrollPos01 ()
GetImage()
proto native int Widget::GetImage () private
Returns active image.
GetImageSize()
proto void Widget::GetImageSize (int image, out int sx, out int sy) private
returns size of image
GetItalic()
proto native bool Widget::GetItalic () private
GetItemData()
proto void SimpleListboxWidget::GetItemData (int row, int column, out Class data) private
GetItemText()
proto bool SimpleListboxWidget::GetItemText (int row, int column, out string text) private
Get item.
Parameters
row int Index of row
column int Index of column
Returns
string Value in widget on row and column
string value;
textListboxWidg.GetItemText(2, 0, value);
GetLine()
proto void TextWidget::GetLine (int line, out string text) private
GetLinesCount()
proto native int TextWidget::GetLinesCount () private
GetLineWidth()
proto native float TextWidget::GetLineWidth (int line) private
GetMaskProgress()
proto native float Widget::GetMaskProgress () private
Progress determines which alpha values are opaque using the mask. For progress x, pixels with alpha in mask < x will be opaque and alpha in mask > x will be transparent. For smooth transition see GetMaskTransitionWidth.
Returns
Progress from 0 to 1 representing alpha range which is visible in the mask
GetMaskTransitionWidth()
proto native float Widget::GetMaskTransitionWidth () private
Transition width 0.1 and progress 0.2 mean that values in mask lower than progress will be opaque. Values higher than (progress + width) will be transparent and values between progress and (progress + width) will be smoothly transitioned.
Returns
Width of the alpha mask transition representing softness of the transition.
GetMax()
proto native float UIWidget::GetMax () private
GetMin()
proto native float UIWidget::GetMin () private
GetName()
string GetName ()
Definition at line 117 of file syncedvalue.c.
    {
        return m_Name;
    }
References m_Name.
Referenced by ActionEnterLadder::ActionCondition(), GetComponentIndex(), ScriptedWidgetEventHandler::GetOnScreenPosition(), IsComponentInSelection(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), and HumanInventory::ReplaceItemInHandsWithNewImpl().
GetNumItems()
proto native int UIWidget::GetNumItems () private
GetNumLines()
proto native int TextWidget::GetNumLines () private
GetOutlineColor()
proto native int Widget::GetOutlineColor () private
GetOutlineSize()
proto native int Widget::GetOutlineSize () private
GetParent()
proto native Widget GetParent ()
Get parent of the Effect.
Note
Same as GetAttachmentParent, but more generic name
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
Object The parent of the Effect
Definition at line 396 of file effect.c.
    {
        return m_ParentObject;
    }
References m_Parent, and m_ParentObject.
Referenced by BuildPartServer(), CameraHandler(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), ClosableHeader::ClosableHeader(), CreateCollisionTrigger(), DestroyMaterialsServer(), DestroyPartServer(), EntityLightSource::DetachFromParent(), DismantlePartServer(), DrawDebugCollisionBox(), DropNonUsableMaterialsServer(), EOnContact(), GetAttachmentParent(), GetCollisionBoxData(), EffectParticle::GetCurrentLocalPosition(), GetMaterialType(), ParticleSource::GetParticleParent(), GetRequiredParts(), HasConflictPart(), HasMaterials(), HasMaterialWithQuantityAttached(), HasRequiredPart(), HideConstructionPart(), HideConstructionPartPhysics(), IsColliding(), IsCollidingEx(), EntityAI::IsInTransport(), ManBase::IsInVehicle(), MaterialIsRuined(), EffectParticle::ReAttach(), ReceiveMaterialsServer(), EffectParticle::SetCurrentLocalPosition(), SetLockOnAttachedMaterials(), AttachmentsGroupContainer::SetNextActive(), LayoutHolder::SetNextActive(), AttachmentsGroupContainer::SetPreviousActive(), LayoutHolder::SetPreviousActive(), ShowConstructionPart(), ShowConstructionPartPhysics(), EffectParticle::Start(), Particle::StopParticle(), TakeMaterialsServer(), PlayerContainer::TransferItem(), ZombieContainer::TransferItem(), UpdateConstructionParts(), Container::UpdateHeaderText(), and VicinityContainer::UpdateInterval().
GetPos()
proto void GetPos (out float x, out float y)
GetScreenPos()
proto void GetScreenPos (out float x, out float y)
GetScreenSize()
proto void GetScreenSize (out float width, out float height)
GetScript()
proto void GetScript (out Class data)
GetSelectedRow()
proto native int UIWidget::GetSelectedRow () private
GetShadowColor()
proto native int Widget::GetShadowColor () private
GetShadowOffset()
proto void Widget::GetShadowOffset (out float sx, out float sy) private
GetShadowOpacity()
proto native float Widget::GetShadowOpacity () private
GetShadowSize()
proto native int Widget::GetShadowSize () private
GetSibling()
proto native Widget GetSibling ()
GetSize()
proto void GetSize (out float width, out float height)
GetSort()
proto native int GetSort ()
GetState()
proto native bool UIWidget::GetState () private
GetStep()
proto native float UIWidget::GetStep () private
GetStyleName()
proto native owned string GetStyleName ()
GetText() [1/2]
proto string UIWidget::GetText () private
GetText() [2/2]
proto void TextWidget::GetText (out string text) private
GetTextBold()
proto native bool Widget::GetTextBold () private
GetTextItalic()
proto native bool Widget::GetTextItalic () private
GetTextOutlineColor()
proto native int Widget::GetTextOutlineColor () private
GetTextOutlineSize()
proto native int Widget::GetTextOutlineSize () private
GetTextProportion() [1/2]
proto native float Widget::GetTextProportion () private
Get text proportion - ratio between button height and button text height in interval <0,1>
GetTextProportion() [2/2]
proto native float UIWidget::GetTextProportion () private
Get text proportion - ratio between button height and button text height in interval <0,1>
GetTextShadowColor()
proto native int Widget::GetTextShadowColor () private
GetTextShadowOffsetX()
proto native float Widget::GetTextShadowOffsetX () private
GetTextShadowOffsetY()
proto native float Widget::GetTextShadowOffsetY () private
GetTextShadowOpacity()
proto native float Widget::GetTextShadowOpacity () private
GetTextShadowSize()
proto native int Widget::GetTextShadowSize () private
GetTextSize()
proto void Widget::GetTextSize (out int sx, out int sy) private
Returns text size in pixels.
GetTypeID()
proto native WidgetType GetTypeID ()
GetTypeName()
proto native owned string GetTypeName ()
GetUserData()
proto void GetUserData (out Class data)
GetUserID()
proto native int GetUserID ()
GetVScrollPos()
proto native float GetVScrollPos ()
GetVScrollPos01()
proto native float GetVScrollPos01 ()
GetWidgetUnderCursor()
proto native Widget GetWidgetUnderCursor ()
Referenced by PluginBase::IsMouseInScene().
HScrollStep()
proto native bool HScrollStep (int steps)
HScrollToPos()
proto native void HScrollToPos (float pos)
HScrollToPos01()
proto native void HScrollToPos01 (float pos01)
HScrollToWidget()
proto native void HScrollToWidget (Widget child)
IsChecked()
proto native bool UIWidget::IsChecked () private
IsControlClass()
proto native bool IsControlClass ()
IsScrollbarVisible()
proto native bool IsScrollbarVisible ()
IsVisible()
proto native bool IsVisible ()
Referenced by UIScriptedMenu::FilterByVisible(), SlotsContainer::IsDisplayable(), UpdateConsoleToolbar(), UpdateInterval(), and SlotsContainer::VerifySlotsIconVisibility().
IsVisibleHierarchy()
proto native bool IsVisibleHierarchy ()
LoadImageFile()
proto native bool Widget::LoadImageFile (int num, string name, bool noCache = false) private
Loads image. When image of this 'num' is already loaded, then is replaced by new one.
Parameters
num Number of image (0...7)
name Name of image file
noCache Do not cache the texture
Returns
True when image is loaded, false otherwise
Referenced by Icon::CheckIsWeapon(), and ScriptedWidgetEventHandler::ModsMenuDetailedEntry().
LoadMaskTexture()
proto native bool Widget::LoadMaskTexture (string resource) private
Loads texture as mask used for alpha masking.
Parameters
resource Resource name of the texture to load
Returns
True if texture was successfully loaded, false otherwise
LoadVideo()
proto native bool Widget::LoadVideo (string name, int soundScene) private
LoadWidgetImageSet()
proto native bool LoadWidgetImageSet (string filename)
LoadWidgetStyles()
proto native void LoadWidgetStyles (string filename)
OnChange()
bool ScriptedWidgetEventHandler::OnChange (Widget w, int x, int y, bool finished) private
OnChildAdd()
bool ScriptedWidgetEventHandler::OnChildAdd (Widget w, Widget child) private
OnChildRemove()
bool ScriptedWidgetEventHandler::OnChildRemove (Widget w, Widget child) private
OnClick()
bool ScriptedWidgetEventHandler::OnClick (Widget w, int x, int y, int button) private
OnController()
bool ScriptedWidgetEventHandler::OnController (Widget w, int control, int value) private
control is one of ControlID
OnDoubleClick()
bool ScriptedWidgetEventHandler::OnDoubleClick (Widget w, int x, int y, int button) private
OnDrag()
bool ScriptedWidgetEventHandler::OnDrag (Widget w, int x, int y) private
OnDragging()
bool ScriptedWidgetEventHandler::OnDragging (Widget w, int x, int y, Widget reciever) private
OnDraggingOver()
bool ScriptedWidgetEventHandler::OnDraggingOver (Widget w, int x, int y, Widget reciever) private
OnDrop()
bool ScriptedWidgetEventHandler::OnDrop (Widget w, int x, int y, Widget reciever) private
OnDropReceived()
bool ScriptedWidgetEventHandler::OnDropReceived (Widget w, int x, int y, Widget reciever) private
OnEvent()
bool ScriptedWidgetEventHandler::OnEvent (EventType eventType, Widget target, int parameter0, int parameter1) private
OnFocus()
bool ScriptedWidgetEventHandler::OnFocus (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::Focus(), ScriptedWidgetEventHandler::OnFocus(), ScriptedWidgetEventHandler::OnMouseEnter(), and ScriptedWidgetEventHandler::OnMouseLeave().
OnFocusLost()
bool ScriptedWidgetEventHandler::OnFocusLost (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnFocusLost(), and ScriptedWidgetEventHandler::OnMouseLeave().
OnItemSelected()
bool ScriptedWidgetEventHandler::OnItemSelected (Widget w, int x, int y, int row, int column, int oldRow, int oldColumn) private
OnKeyDown()
bool ScriptedWidgetEventHandler::OnKeyDown (Widget w, int x, int y, int key) private
OnKeyPress()
bool ScriptedWidgetEventHandler::OnKeyPress (Widget w, int x, int y, int key) private
OnKeyUp()
bool ScriptedWidgetEventHandler::OnKeyUp (Widget w, int x, int y, int key) private
OnModalResult()
bool ScriptedWidgetEventHandler::OnModalResult (Widget w, int x, int y, int code, int result) private
OnMouseButtonDown()
bool ScriptedWidgetEventHandler::OnMouseButtonDown (Widget w, int x, int y, int button) private
OnMouseButtonUp()
bool ScriptedWidgetEventHandler::OnMouseButtonUp (Widget w, int x, int y, int button) private
OnMouseEnter()
bool ScriptedWidgetEventHandler::OnMouseEnter (Widget w, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnMouseEnter().
OnMouseLeave()
bool ScriptedWidgetEventHandler::OnMouseLeave (Widget w, Widget enterW, int x, int y) private
Referenced by ScriptedWidgetEventHandler::OnMouseLeave().
OnMouseWheel()
bool ScriptedWidgetEventHandler::OnMouseWheel (Widget w, int x, int y, int wheel) private
OnResize()
bool ScriptedWidgetEventHandler::OnResize (Widget w, int x, int y) private
OnSelect()
bool ScriptedWidgetEventHandler::OnSelect (Widget w, int x, int y) private
OnUpdate()
bool ScriptedWidgetEventHandler::OnUpdate (Widget w) private
Play()
proto native int Widget::Play (VideoCommand cmd) private
ReloadTexture()
proto native bool ReloadTexture (string path)
RemoveChild()
proto native void RemoveChild (Widget child)
RemoveItem()
proto native void UIWidget::RemoveItem (int item) private
RemoveRow()
proto native void UIWidget::RemoveRow (int row) private
ReportMouse()
proto native void ReportMouse (int mousex, int mousey, Widget rootWidget)
SelectRow()
proto native void UIWidget::SelectRow (int row) private
SetActiveWindow()
proto native bool SetActiveWindow (Widget w, bool resetFocus)
SetAlpha()
proto native void SetAlpha (float alpha)
SetBold()
proto native void Widget::SetBold (bool bold) private
SetChecked()
proto native void UIWidget::SetChecked (bool checked) private
SetColor()
proto native void SetColor (int color)
SetContentAlignmentH()
proto native void SetContentAlignmentH (WidgetAlignment alignment)
SetContentAlignmentV()
proto native void SetContentAlignmentV (WidgetAlignment alignment)
SetContentOffset()
proto native void TextWidget::SetContentOffset (float offset, bool snapToLine = false) private
SetCurrent()
proto native void UIWidget::SetCurrent (float curr) private
SetCurrentItem()
proto native int UIWidget::SetCurrentItem (int n) private
SetCursorWidget()
proto native void SetCursorWidget (Widget cursor)
SetFlags()
proto native int SetFlags (int flags, bool immedUpdate = true)
SetFocus()
proto native void SetFocus (Widget w)
Referenced by UIScriptedMenu::BackButtonFocus(), UIScriptedMenu::CheckNewOptions(), UIScriptedMenu::CloseOnline(), UIScriptedMenu::ColorDisable(), ColorDisable(), ServerBrowserTab::ColorDisable(), UIScriptedMenu::ColorDisabled(), OptionSelectorBase::ColorHighlight(), UIScriptedMenu::ColorRed(), ScriptedWidgetEventHandler::ColorRed(), UIScriptedMenu::ColorWhite(), ScriptedWidgetEventHandler::Focus(), ScriptedWidgetEventHandler::FocusFirst(), GetNextEntry(), GetPrevEntry(), UIScriptedMenu::Init(), ScriptedWidgetEventHandler::OnChange(), OptionSelectorBase::OnFocus(), UIScriptedMenu::OnMouseButtonDown(), ScriptedWidgetEventHandler::OnMouseButtonUp(), ScriptedWidgetEventHandler::OnMouseEnter(), OnMouseEnter(), ServerBrowserTab::OnMouseEnter(), UIScriptedMenu::OnMouseLeave(), OptionSelectorBase::OnMouseLeave(), ServerBrowserTab::OnMouseLeave(), UIScriptedMenu::OnShow(), OnShow(), ServerBrowserTab::SetEnableFilters(), ServerBrowserTab::SetFocusServers(), ScriptedWidgetEventHandler::UpdateEntry(), and UIScriptedMenu::UpdateMenuFocus().
SetGUIWidget()
proto native void SetGUIWidget (IEntity ent, int index, RTTextureWidget w)
sets Widget typu RTTextureWidgetTypeID, to which it is possible to reference in shader as $rendertarget it is posible to use only after object selection. When selecting another object, it is necessary to set GUI widget again
SetHandler()
proto native void SetHandler (ScriptedWidgetEventHandler eventHandler)
SetImage()
proto native bool Widget::SetImage (int num) private
Switches to another image, if it's loaded
Parameters
num Number of image.
Returns
True when there is such image, false otherwise.
Referenced by ScriptedWidgetEventHandler::Deselect(), and ScriptedWidgetEventHandler::Select().
SetImageTexture()
proto native void Widget::SetImageTexture (int image, RTTextureWidget texture) private
SetItalic()
proto native void Widget::SetItalic (bool italic) private
SetItem() [1/2]
proto native void UIWidget::SetItem (int item, string value) private
SetItem() [2/2]
proto native void SimpleListboxWidget::SetItem (int position, string text, Class userData, int column) private
SetItemColor()
proto native void SimpleListboxWidget::SetItemColor (int row, int column, int color) private
SetLine()
proto native void TextWidget::SetLine (int line, string text) private
SetLineBreakingOverride()
proto native float TextWidget::SetLineBreakingOverride (int mode) private
Referenced by ScriptedWidgetEventHandler::ModsMenuDetailedEntry().
SetLinesVisibility()
proto native void TextWidget::SetLinesVisibility (int lineFrom, int lineTo, bool visible) private
SetMaskProgress()
proto native void Widget::SetMaskProgress (float value) private
See GetMaskProgress for explanation.
Parameters
value Expected in range [0; 1]
SetMaskTransitionWidth()
proto native void Widget::SetMaskTransitionWidth (float value) private
See GetMaskTransitionWidth for transition width explanation.
Parameters
value Expected in range [0; 1]
SetMinMax()
proto native void UIWidget::SetMinMax (float minimum, float maximum) private
SetModal()
proto native void SetModal (Widget w)
SetName()
proto native void SetName (string name)
SetOutline()
proto native void Widget::SetOutline (int outlineSize, int argb = 0xFF000000) private
SetPos()
proto native void SetPos (float x, float y, bool immedUpdate = true)
SetRefresh()
proto native void Widget::SetRefresh (int period, int offset) private
when period > 1 then every n-th frame will be rendered. Offset is initial counter.
SetResolutionScale()
proto native void Widget::SetResolutionScale (float xscale, float ycale) private
SetRotation()
proto native void SetRotation (float roll, float pitch, float yaw, bool immedUpdate = true)
Referenced by ScriptedWidgetEventHandler::CreateFollowedObject().
SetShadow()
proto native void Widget::SetShadow (int shadowSize, int shadowARGB = 0xFF000000, float shadowOpacity = 1, float shadowOffsetX = 0, float shadowOffsetY = 0) private
SetSize()
proto native void SetSize (float x, float y, bool immedUpdate = true)
Referenced by updateSlotsCount().
SetSort()
proto native void SetSort (int sort, bool immedUpdate = true)
Referenced by ServerBrowserTab::Construct(), and ServerBrowserTab::ToggleSort().
SetState()
proto native bool UIWidget::SetState (bool state) private
SetStep()
proto native void UIWidget::SetStep (float step) private
SetText() [1/2]
proto native void UIWidget::SetText (string str) private
SetText() [2/2]
proto native void Widget::SetText (string text, bool immedUpdate = true) private
Referenced by UIScriptedMenu::LateInit(), and ScriptedWidgetEventHandler::LoadData().
SetTextBold()
proto native void Widget::SetTextBold (bool bold) private
SetTextColor()
proto native void Widget::SetTextColor (int color) private
SetTextExactSize()
proto native void Widget::SetTextExactSize (int size) private
set text exact size. Exact Text flag must be enabled. 0 equals original size.
SetTextFormat()
proto void Widget::SetTextFormat (string text, void param1 = NULL, void param2 = NULL, void param3 = NULL, void param4 = NULL, void param5 = NULL, void param6 = NULL, void param7 = NULL, void param8 = NULL, void param9 = NULL) private
SetTextHorizontalAlignment()
proto native void UIWidget::SetTextHorizontalAlignment (int align) private
Parameters
align ALIGN_CENTER, ALIGN_LEFT, ALIGN_RIGHT
SetTextItalic()
proto native void Widget::SetTextItalic (bool italic) private
SetTextOffset() [1/2]
proto native void UIWidget::SetTextOffset (float xoffset, float yoffset) private
SetTextOffset() [2/2]
proto native void Widget::SetTextOffset (int left, int top) private
SetTextOutline()
proto native void Widget::SetTextOutline (int outlineSize, int argb = 0xFF000000) private
SetTextProportion() [1/2]
proto native void Widget::SetTextProportion (float val) private
Set text proportion - ratio between button height and button text height in interval <0,1>
SetTextProportion() [2/2]
proto native void UIWidget::SetTextProportion (float val) private
Set text proportion - ratio between button height and button text height in interval <0,1>
SetTextShadow()
proto native void Widget::SetTextShadow (int shadowSize, int shadowARGB = 0xFF000000, float shadowOpacity = 1.0, float shadowOffsetX = 0.0, float shadowOffsetY = 0.0) private
SetTextSpacing()
proto native void Widget::SetTextSpacing (int horiz, int vert) private
SetTextVerticalAlignment()
proto native void UIWidget::SetTextVerticalAlignment (int align) private
Parameters
align ALIGN_CENTER, ALIGN_TOP, ALIGN_BOTTOM
SetTransform()
proto native void SetTransform (vector mat[4], bool immedUpdate = true)
SetUserData()
proto native void SetUserData (Class data)
SetUserID()
proto native void SetUserID (int id)
SetUV()
proto native void Widget::SetUV (float uv[4][2]) private
When WF_CUSTOMUV is set, we can supply our own UV coords instead of computed ones.
Parameters
uv Pointer to array of at least 8 floats (4 corners * 2 floats for u/v)
SetWidgetWorld()
proto native void SetWidgetWorld (RenderTargetWidget w, IEntity wrldEntity, int camera)
Show()
proto native void Show (bool show, bool immedUpdate = true)
ShowCursorWidget()
proto native void ShowCursorWidget (bool show)
TranslateString()
static proto string TranslateString (string stringId) static
Unlink()
proto native void Unlink ()
Update()
override void Update ()
don't show crosshair if it's disabled in profile or from server
Definition at line 122 of file playersoundmanager.c.
    {
        if( !m_Player.IsAlive() )
        {
            SetAllowUpdate(false);
            return;
        }
#ifndef NO_GUI
        for(int i = 0; i < MAX_HANDLERS_COUNT; i++)
        {
            m_Handlers[i].Update();
        }
#endif
    }
References ScriptModule::CallFunction(), CONTROLLER_DESELECT_TIMEOUT, CONTROLLER_TILT_TRESHOLD_SELECT, g_Game, CGame::GameScript, ScriptedWidgetEventHandler::GetActionManager(), GetAngleInDegrees(), GetCurrentCrossHair(), GetGame(), CGame::GetInput(), GetMouseDistance(), GetMousePointerAngle(), GetObjectByDegAngle(), ScriptedWidgetEventHandler::GetPlayer(), CGame::GetTime(), GetZone(), HideRadialSelector(), IsUsingController(), IsUsingMouse(), last_time, m_AM, m_ControllerAngle, m_ControllerTilt, m_ControllerTimout, m_Handlers, m_IsControllerTimoutEnabled, m_Player, m_player, m_RegisteredClass, m_SelectedObject, m_Stamina, m_StaminaLastValue, m_StaminaZoneOffset, m_UpdateTimer, m_WidgetInitialized, MAX_HANDLERS_COUNT, MOUSE_SAFE_ZONE_RADIUS, ProcessSound(), randomValuesArray, Refresh(), SelectCrossHair(), SetAgents(), SetAllowUpdate(), ShowCrossHair(), ShowRadialSelector(), UpdataControllerInput(), and USAGE_COUNT.
Referenced by ScriptedWidgetEventHandler::ContinuousActionProgress(), CrossHairSelector(), Init(), ScriptedWidgetEventHandler::ItemActionsWidget(), ScriptedWidgetEventHandler::ProjectedCrosshair(), RadialProgressBar::RadialProgressBar(), ParticleSource::SetWiggle(), ScriptedWidgetEventHandler::~ContinuousActionProgress(), ~CrossHairSelector(), ScriptedWidgetEventHandler::~ItemActionsWidget(), ScriptedWidgetEventHandler::~ProjectedCrosshair(), and RadialProgressBar::~RadialProgressBar().
VScrollStep()
proto native bool VScrollStep (int steps)
VScrollToPos()
proto native void VScrollToPos (float pos)
VScrollToPos01()
proto native void VScrollToPos01 (float pos01)
VScrollToWidget()
proto native void VScrollToWidget (Widget child)
Variable Documentation
GetScrollbarWidth
class GridSpacerWidget extends SpacerWidget GetScrollbarWidth
WA_BOTTOM
WA_BOTTOM = 1
Definition at line 4 of file enwidgets.c.
WA_CENTER
WA_CENTER = 2
Definition at line 2 of file enwidgets.c.
WA_LEFT
WA_LEFT = 0
Definition at line 0 of file enwidgets.c.
WA_RIGHT
WA_RIGHT = 1
Definition at line 1 of file enwidgets.c.
WA_TOP
WA_TOP = 0
Definition at line 3 of file enwidgets.c.
Widget
proto private void Widget
Defined in code.