DayzKode: P:/scripts/3_game/DayZ/systems/inventory/handanimated_guards.c File Reference
handanimated_guards.c File Reference
Classes
class HandGuardBase
guards
class HandSelectAnimationOfForceSwapInHandsEvent
Functions
bool SelectAnimationOfForceSwapInHands (notnull Man player, notnull InventoryLocation old_src, notnull InventoryLocation new_src, notnull InventoryLocation old_dst, notnull InventoryLocation new_dst, out int animType1, out int animType2)
bool SelectAnimationOfMoveFromHands (notnull Man player, notnull InventoryLocation src, notnull InventoryLocation dst, out int animType)
bool SelectAnimationOfTakeToHands (notnull Man player, notnull InventoryLocation src, notnull InventoryLocation dst, out int animType)
int SlotToAnimType (notnull Man player, notnull InventoryLocation src, InventoryLocation dst=null)
Function Documentation
SelectAnimationOfForceSwapInHands()
bool SelectAnimationOfForceSwapInHands (notnull Man player, notnull InventoryLocation old_src, notnull InventoryLocation new_src, notnull InventoryLocation old_dst, notnull InventoryLocation new_dst, out int animType1, out int animType2)
Definition at line 155 of file handanimated_guards.c.
{
    if (player.IsInTransport())
        return false;
    hndDebugPrint("[hndfsm] SlotToAnimType - old_src=" + InventoryLocation.DumpToStringNullSafe(old_src) + " new_src=" + InventoryLocation.DumpToStringNullSafe(new_src) + " old_dst=" + InventoryLocation.DumpToStringNullSafe(old_dst) + " new_dst=" + InventoryLocation.DumpToStringNullSafe(new_dst));
    if (old_src.GetItem().GetHierarchyRootPlayer() == player || new_src.GetItem().GetHierarchyRootPlayer() == player)
    {
        animType1 = SlotToAnimType(player, old_src, old_dst);
        animType2 = SlotToAnimType(player, new_src, new_dst);
        //Print("animType1 = " + animType1);
        //Print("animType2 = " + animType2);
        if (animType1 != -1 && animType2 != -1)
        {
            hndDebugPrint("[hndfsm] SelectAnimationOfForceSwapInHands guard - selected animType1=" + animType1 + " animType2=" + animType2 + " for old_item=" + old_src.GetItem() + " for new_item=" + new_src.GetItem());
            return true;
        }
        /*else if (animType1 != -1 || animType2 != -1) //HACK
        {
            animType1 = -1;
            animType2 = -1;
            return false;
        }*/
    }
    hndDebugPrint("[hndfsm] SelectAnimationOfForceSwapInHands - no animation");
    return false;
}
References InventoryLocation::DumpToStringNullSafe(), hndDebugPrint(), and SlotToAnimType().
Referenced by HandGuardBase::ProcessSwapEvent().
SelectAnimationOfMoveFromHands()
bool SelectAnimationOfMoveFromHands (notnull Man player, notnull InventoryLocation src, notnull InventoryLocation dst, out int animType)
Definition at line 137 of file handanimated_guards.c.
{
    if (player.IsInTransport())
        return false;
    if (src.GetItem().GetHierarchyRootPlayer() == player)
    {
        animType = SlotToAnimType(player, dst);
        if (animType != -1)
        {
            hndDebugPrint("[hndfsm] SelectAnimationOfMoveFromHands guard - selected animType=" + animType + " for item=" + src.GetItem());
            return true;
        }
    }
    hndDebugPrint("[hndfsm] SelectAnimationOfMoveFromHands - no animation");
    return false;
}
References hndDebugPrint(), and SlotToAnimType().
Referenced by HandGuardBase::GuardCondition().
SelectAnimationOfTakeToHands()
bool SelectAnimationOfTakeToHands (notnull Man player, notnull InventoryLocation src, notnull InventoryLocation dst, out int animType)
Definition at line 117 of file handanimated_guards.c.
{
    if (player.IsInTransport())
        return false;
    if (src.GetType() == InventoryLocationType.GROUND)
        return false;
    if (src.GetItem().GetHierarchyRootPlayer() == player)
    {
        animType = SlotToAnimType(player, src);
        if (animType != -1)
        {
            hndDebugPrint("[hndfsm] SelectAnimationOfTakeToHands - selected animType=" + animType + " for item=" + src.GetItem());
            return true;
        }
    }
    hndDebugPrint("[hndfsm] SelectAnimationOfTakeToHands - no animation");
    return false;
}
References hndDebugPrint(), and SlotToAnimType().
Referenced by HandGuardBase::GuardCondition().
SlotToAnimType()
int SlotToAnimType (notnull Man player, notnull InventoryLocation src, InventoryLocation dst = null)
Definition at line 1 of file handanimated_guards.c.
{
    //Print("src.GetType() " + src.GetType());
    InventoryLocation invloc1 = new InventoryLocation;
    //InventoryLocation invloc2 = new InventoryLocation;
    if ( (dst && dst.GetParent() && !dst.GetParent().GetHierarchyRootPlayer()) || (src && src.GetParent() && !src.GetParent().GetHierarchyRootPlayer()) )
        return -1;
    if (dst && (dst.GetType() == InventoryLocationType.ATTACHMENT || dst.GetType() == InventoryLocationType.CARGO))
    {
        invloc1.Copy(dst);
        //invloc2.Copy(src);
    }
    else if (src.GetType() == InventoryLocationType.ATTACHMENT || src.GetType() == InventoryLocationType.CARGO)
    {
        invloc1.Copy(src);
        //invloc2.Copy(dst);
    }
    else
    {
        return -1;
    }
    int val = -1;
    if ( invloc1.GetItem() && invloc1.GetItem().GetInventoryHandAnimation(invloc1,val) )
    {
        return val;
    }
    if (invloc1.GetType() == InventoryLocationType.ATTACHMENT /*|| src.GetType() == InventoryLocationType.HANDS*/)
    {
        //return WeaponHideShowTypes.HIDESHOW_SLOT_KNIFEBACK;
        switch (invloc1.GetSlot())
        {
            case InventorySlots.SHOULDER:
            {
                if (invloc1.GetItem() && invloc1.GetItem().IsWeapon())
                {
                    return WeaponHideShowTypes.HIDESHOW_SLOT_RFLLEFTBACK;
                }
                else if (invloc1.GetItem() && invloc1.GetItem().IsOneHandedBehaviour())
                {
                    return WeaponHideShowTypes.HIDESHOW_SLOT_1HDLEFTBACK;
                }
                return WeaponHideShowTypes.HIDESHOW_SLOT_2HDLEFTBACK;
            }
            case InventorySlots.MELEE:
            {
                if (invloc1.GetItem() && invloc1.GetItem().IsWeapon())
                {
                    return WeaponHideShowTypes.HIDESHOW_SLOT_RFLRIGHTBACK;
                }
                else if (invloc1.GetItem() && invloc1.GetItem().IsOneHandedBehaviour())
                {
                    return WeaponHideShowTypes.HIDESHOW_SLOT_1HDRIGHTBACK;
                }
                return WeaponHideShowTypes.HIDESHOW_SLOT_2HDRIGHTBACK;
            }
            case InventorySlots.PISTOL:
            {
                EntityAI parent_item = invloc1.GetParent();         // belt
                Man owner;
                if (parent_item)
                    owner = parent_item.GetHierarchyRootPlayer();       // player
                if (!owner)
                    return -1;
                EntityAI item1 = owner.GetInventory().FindAttachment(InventorySlots.HIPS);
                EntityAI item2 = parent_item.GetHierarchyParent();
                if (owner && item1 == item2) // is the pistol in a belt holster?
                {
                    return WeaponHideShowTypes.HIDESHOW_SLOT_PISTOLBELT;
                }
                return WeaponHideShowTypes.HIDESHOW_SLOT_PISTOLCHEST;
            }
            case InventorySlots.KNIFE:
                return WeaponHideShowTypes.HIDESHOW_SLOT_KNIFEBACK;
            /*case InventorySlots.VEST:
            case InventorySlots.FEET:
            case InventorySlots.BODY:
            case InventorySlots.LEGS:
            case InventorySlots.BACK:
            case InventorySlots.HIPS:
            case InventorySlots.HEADGEAR:
                return WeaponHideShowTypes.HIDESHOW_SLOT_INVENTORY;*/
            default:
                return WeaponHideShowTypes.HIDESHOW_SLOT_INVENTORY;
                //Print("[hndfsm] SlotToAnimType -  not animated slot in src_loc=" + InventoryLocation.DumpToStringNullSafe(invloc1));
        };
        //
        //if (InventorySlots.GetSlotIdFromString("Pistol"))
    }
    else if (invloc1.GetType() == InventoryLocationType.CARGO)
    {
        if ( invloc1.GetItem() && (invloc1.GetItem().GetInventory().HasInventorySlot(InventorySlots.SHOULDER) || invloc1.GetItem().GetInventory().HasInventorySlot(InventorySlots.MELEE)) )
        {
            //Print("Special inventory anim");
            if (invloc1.GetItem() && invloc1.GetItem().IsWeapon())
            {
                return WeaponHideShowTypes.HIDESHOW_SLOT_RFLRIGHTBACK;
            }
            else if (invloc1.GetItem() && invloc1.GetItem().IsOneHandedBehaviour())
            {
                return WeaponHideShowTypes.HIDESHOW_SLOT_1HDRIGHTBACK;
            }
            return WeaponHideShowTypes.HIDESHOW_SLOT_2HDRIGHTBACK;
        }
        //Print("Default inventory anim");
        return WeaponHideShowTypes.HIDESHOW_SLOT_INVENTORY; //default item animation
    }
    return -1;
}
References InventoryLocation::Copy(), InventoryLocation::GetItem(), InventoryLocation::GetParent(), InventoryLocation::GetSlot(), and InventoryLocation::GetType().
Referenced by SelectAnimationOfForceSwapInHands(), SelectAnimationOfMoveFromHands(), and SelectAnimationOfTakeToHands().