DayzKode: P:/scripts/3_game/DayZ/systems/inventory/handfsm.c File Reference
handfsm.c File Reference
Classes
class HFSMBase< HandStateBase, HandEventBase, HandActionBase, HandGuardBase >
Typedefs
typedef FSMTransition< HandStateBase, HandEventBase, HandActionBase, HandGuardBase > HandTransition
Functions
void hndDebugPrint (string s)
void hndDebugSpam (string s)
void hndDebugSpamALot (string s)
Typedef Documentation
HandTransition
typedef FSMTransition<HandStateBase, HandEventBase, HandActionBase, HandGuardBase> HandTransition
Definition at line 20 of file handfsm.c.
Function Documentation
hndDebugPrint()
void hndDebugPrint (string s)
Definition at line 1 of file handfsm.c.
{
#ifdef INV_DEBUG
    PrintToRPT("" + s); // comment/uncomment to hide/see debug logs
#else
    //Print("" + s); // comment/uncomment to hide/see debug logs
#endif
}
References PrintToRPT().
Referenced by ReplaceItemWithNewLambdaBase::CopyOldPropertiesToNew(), ReplaceItemWithNewLambdaBase::CreateNetworkObjectInfo(), ReplaceItemWithNewLambdaBase::CreateNewEntity(), ReplaceItemWithNewLambdaBase::DeleteOldEntity(), HumanInventory::DropEntity(), ReplaceItemWithNewLambdaBase::Execute(), Execute(), HumanInventory::ForceSwapEntities(), HandGuardBase::GuardCondition(), HandleHandEvent(), HandleInventory(), HumanInventoryWithFSM::Init(), Init(), HumanInventory::LocalDestroyEntity(), HandStateBase::OnAbort(), HumanInventory::OnEntityInHandsCreated(), HumanInventory::OnEntityInHandsDestroyed(), HandStateBase::OnEntry(), HandStateBase::OnExit(), OnHandsEnteredStableState(), OnHandsExitedStableState(), OnHandsStateChanged(), ReplaceItemWithNewLambdaBase::OnSuccess(), ReplaceItemWithNewLambdaBase::PrepareLocations(), HumanInventory::RedirectToHandEvent(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), SelectAnimationOfForceSwapInHands(), SelectAnimationOfMoveFromHands(), SelectAnimationOfTakeToHands(), HumanInventory::SwapEntities(), SyncHandEventToRemote(), HumanInventory::TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), HumanInventory::TakeEntityToInventory(), HumanInventory::TakeToDst(), and HumanInventory::ThrowEntity().
hndDebugSpam()
void hndDebugSpam (string s)
Definition at line 9 of file handfsm.c.
{
    //Print("" + s); // comment/uncomment to hide/see debug spam
}
Referenced by OnHandEventForRemote(), and HumanInventoryWithFSM::ProcessHandAbortEvent().
hndDebugSpamALot()
void hndDebugSpamALot (string s)
Definition at line 13 of file handfsm.c.
{
    //Print("" + s); // comment/uncomment to hide/see debug spam
}
Referenced by HandleInventory().