DayzKode: P:/scripts/4_world/DayZ/entities/vehicles/inheritedcars/hatchback_02.c File Reference
hatchback_02.c File Reference
Classes
class CarScript
class Hatchback_02
Functions
override bool CanDisplayAttachmentCategory (string category_name)
override bool CanDisplayCargo ()
override protected bool CanManipulateSpareWheel (string slotSelectionName)
override bool CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
override bool CanReachSeatFromSeat (int currentSeat, int nextSeat)
override bool CanReleaseAttachment (EntityAI attachment)
override CarLightBase CreateFrontLight ()
override CarRearLightBase CreateRearLight ()
override bool CrewCanGetThrough (int posIdx)
override void EEInit ()
override void EOnPostSimulate (IEntity other, float timeSlice)
override int GetAnimInstance ()
override string GetAnimSourceFromSelection (string selection)
override int GetCarDoorsState (string slotType)
override string GetDoorInvSlotNameFromSeatPos (int posIdx)
override string GetDoorSelectionNameFromSeatPos (int posIdx)
override int GetSeatAnimationType (int posIdx)
void Hatchback_02 ()
override bool IsVitalGlowPlug ()
override bool IsVitalTruckBattery ()
override void OnEngineStart ()
override void OnEngineStop ()
override float OnSound (CarSoundCtrl ctrl, float oldValue)
Variables
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
protected ref UniversalTemperatureSource m_UTSource
protected ref UniversalTemperatureSourceSettings m_UTSSettings
class Hatchback_02_Blue extends Hatchback_02 OnDebugSpawn
Function Documentation
CanDisplayAttachmentCategory()
override bool OnDebugSpawn::CanDisplayAttachmentCategory (string category_name)
Definition at line 596 of file hatchback_02.c.
CanDisplayCargo()
override bool OnDebugSpawn::CanDisplayCargo ()
Definition at line 613 of file hatchback_02.c.
CanManipulateSpareWheel()
override protected bool OnDebugSpawn::CanManipulateSpareWheel (string slotSelectionName)
Definition at line 591 of file hatchback_02.c.
CanReachDoorsFromSeat()
override bool OnDebugSpawn::CanReachDoorsFromSeat (string pDoorsSelection, int pCurrentSeat)
Definition at line 831 of file hatchback_02.c.
CanReachSeatFromSeat()
override bool OnDebugSpawn::CanReachSeatFromSeat (int currentSeat, int nextSeat)
Definition at line 806 of file hatchback_02.c.
CanReleaseAttachment()
override bool OnDebugSpawn::CanReleaseAttachment (EntityAI attachment)
Definition at line 572 of file hatchback_02.c.
CreateFrontLight()
override CarLightBase OnDebugSpawn::CreateFrontLight ()
Definition at line 567 of file hatchback_02.c.
CreateRearLight()
override CarRearLightBase OnDebugSpawn::CreateRearLight ()
Definition at line 561 of file hatchback_02.c.
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
References LIQUID_WATER.
CrewCanGetThrough()
override bool OnDebugSpawn::CrewCanGetThrough (int posIdx)
Definition at line 659 of file hatchback_02.c.
EEInit()
override void OnDebugSpawn::EEInit ()
Definition at line 486 of file hatchback_02.c.
            {
                container.SetLiquidType(LIQUID_WATER, true);
References LIQUID_WATER.
EOnPostSimulate()
override void OnDebugSpawn::EOnPostSimulate (IEntity other, float timeSlice)
Definition at line 525 of file hatchback_02.c.
        {
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
GetAnimInstance()
override int OnDebugSpawn::GetAnimInstance ()
Definition at line 538 of file hatchback_02.c.
            {
GetAnimSourceFromSelection()
override string OnDebugSpawn::GetAnimSourceFromSelection (string selection)
Definition at line 774 of file hatchback_02.c.
GetCarDoorsState()
override int OnDebugSpawn::GetCarDoorsState (string slotType)
Definition at line 624 of file hatchback_02.c.
Referenced by CarScript::CanDisplayAttachmentCategory(), CarScript::CanDisplayCargo(), CarScript::CanManipulateSpareWheel(), CarScript::CanReleaseAttachment(), CarScript::CrewCanGetThrough(), and CarScript::OnSound().
GetDoorInvSlotNameFromSeatPos()
override string OnDebugSpawn::GetDoorInvSlotNameFromSeatPos (int posIdx)
Definition at line 720 of file hatchback_02.c.
GetDoorSelectionNameFromSeatPos()
override string OnDebugSpawn::GetDoorSelectionNameFromSeatPos (int posIdx)
Definition at line 699 of file hatchback_02.c.
GetSeatAnimationType()
override int OnDebugSpawn::GetSeatAnimationType (int posIdx)
Definition at line 543 of file hatchback_02.c.
            {
Hatchback_02()
void OnDebugSpawn::Hatchback_02 ()
Definition at line 467 of file hatchback_02.c.
        {
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_1_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_2_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_1_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_2_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Hood_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Trunk_Black" );
IsVitalGlowPlug()
override bool OnDebugSpawn::IsVitalGlowPlug ()
Definition at line 801 of file hatchback_02.c.
IsVitalTruckBattery()
override bool OnDebugSpawn::IsVitalTruckBattery ()
Definition at line 796 of file hatchback_02.c.
OnEngineStart()
override void OnDebugSpawn::OnEngineStart ()
Definition at line 505 of file hatchback_02.c.
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
OnEngineStop()
override void OnDebugSpawn::OnEngineStop ()
Definition at line 515 of file hatchback_02.c.
{
    override void OnDebugSpawn()
    {
        EntityAI entity;
        EntityAI ent;
OnSound()
override float OnDebugSpawn::OnSound (CarSoundCtrl ctrl, float oldValue)
Definition at line 741 of file hatchback_02.c.
Variable Documentation
m_UTSLEngine
protected ref UniversalTemperatureSourceLambdaEngine m_UTSLEngine
Definition at line 465 of file hatchback_02.c.
Referenced by ItemBase::EEInit(), CarScript::EEInit(), CarScript::EOnPostSimulate(), and ItemBase::OnWork().
m_UTSource
protected ref UniversalTemperatureSource m_UTSource
Definition at line 463 of file hatchback_02.c.
Referenced by CarScript::EEInit(), CarScript::EOnPostSimulate(), CarScript::OnEngineStart(), and CarScript::OnEngineStop().
m_UTSSettings
protected ref UniversalTemperatureSourceSettings m_UTSSettings
Definition at line 464 of file hatchback_02.c.
Referenced by CarScript::EEInit(), and CarScript::EOnPostSimulate().
OnDebugSpawn
override void OnDebugSpawn
Definition at line 1 of file hatchback_02.c.
    {
        EntityAI entity;
        EntityAI ent;
        ItemBase container;
        if ( Class.CastTo(entity, this) )
        {
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_1_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_1_2_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_1_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Door_2_2_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Hood_Black" );
            entity.GetInventory().CreateInInventory( "Hatchback_02_Trunk_Black" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            //-----IN CAR CARGO
            entity.GetInventory().CreateInInventory( "Hatchback_02_Wheel" );
            entity.GetInventory().CreateInInventory( "CarBattery" );
            entity.GetInventory().CreateInInventory( "SparkPlug" );
            entity.GetInventory().CreateInInventory( "HeadlightH7" );
            entity.GetInventory().CreateInInventory( "CarRadiator" );
            //--
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            //--
            entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            ent = entity.GetInventory().CreateInInventory( "CanisterGasoline" );
            if ( Class.CastTo(container, ent) )
            {
                container.SetLiquidType(LIQUID_WATER, true);
            }
            ent = entity.GetInventory().CreateInInventory( "Blowtorch" );
            if ( ent )
            {
                entity = ent.GetInventory().CreateInInventory( "LargeGasCanister" );
            }
        }
        Fill( CarFluid.FUEL, 50 );
        Fill( CarFluid.COOLANT, 6.0 );
        Fill( CarFluid.OIL, 4.0 );
    }