DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/playersoundevents/events/holdbreathevents.c File Reference
holdbreathevents.c File Reference
Classes
class HoldBreathSoundEventBase
class PlayerSoundEventBase
Functions
void ExhaustedBreathSoundEvent ()
override bool HasHoldBreathException ()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
class HoldBreathSoundEventBase extends PlayerSoundEventBase HoldBreathSoundEvent ()
void HoldBreathSoundEventBase ()
class ExhaustedBreathSoundEvent extends HoldBreathSoundEventBase ReleaseBreathSoundEvent ()
Function Documentation
ExhaustedBreathSoundEvent()
void ReleaseBreathSoundEvent::ExhaustedBreathSoundEvent ()
Definition at line 53 of file holdbreathevents.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
        m_ID = EPlayerSoundEventID.RELEASE_BREATH;
        m_SoundVoiceAnimEventClassID = 21;
    }
References m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
Referenced by PlayerSoundEventHandler().
HasHoldBreathException()
override bool HoldBreathSoundEvent::HasHoldBreathException ()
Definition at line 24 of file holdbreathevents.c.
    {
        if (other_state_id == EPlayerSoundEventID.RELEASE_BREATH)
HasPriorityOverCurrent()
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 25 of file holdbreathevents.c.
    {
        if (other_state_id == EPlayerSoundEventID.RELEASE_BREATH)
        {
            return false;
        }
        return true;
    }
HoldBreathSoundEvent()
class HoldBreathSoundEventBase extends PlayerSoundEventBase HoldBreathSoundEvent ()
Definition at line 1 of file holdbreathevents.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
        m_ID = EPlayerSoundEventID.HOLD_BREATH;
        m_SoundVoiceAnimEventClassID = 20;
    }
Referenced by PlayerSoundEventHandler().
HoldBreathSoundEventBase()
void HoldBreathSoundEvent::HoldBreathSoundEventBase ()
Definition at line 19 of file holdbreathevents.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
        m_ID = EPlayerSoundEventID.HOLD_BREATH;
        m_SoundVoiceAnimEventClassID = 20;
References m_ID, m_SoundVoiceAnimEventClassID, and m_Type.
ReleaseBreathSoundEvent()
class ExhaustedBreathSoundEvent extends HoldBreathSoundEventBase ReleaseBreathSoundEvent ()
Definition at line 35 of file holdbreathevents.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
        m_ID = EPlayerSoundEventID.RELEASE_BREATH;
        m_SoundVoiceAnimEventClassID = 21;
    }
Referenced by PlayerSoundEventHandler().