DayzKode: P:/scripts/5_mission/DayZ/gui/scriptshuddebug/huddebugwincharagents.c File Reference
huddebugwincharagents.c File Reference
Classes
class DebugAgentData
Functions
void AddAgent (string title, string value, int id)
void ClearAgents ()
void DebugGrowAgentsRequest (int agent_id, bool should_grow)
void DebugRemoveAgentsRequest ()
void FitWindow ()
override int GetType ()
override void Hide ()
void HudDebugWinCharAgents (Widget widget_root)
bool OnClick (Widget w, int x, int y, int button)
void SetAgents ()
override void SetUpdate (bool state)
override void Show ()
override void Update ()
void ~HudDebugWinCharAgents ()
Variables
protected ref map< Widget, ref DebugAgentData > m_AgentWidgetData = new map<Widget, ref DebugAgentData>
protected ref array< ref Widget > m_AgentWidgets = new array<ref Widget>
class DebugAgentData m_WgtAgents
Function Documentation
AddAgent()
void AddAgent (string title, string value, int id)
Definition at line 189 of file huddebugwincharagents.c.
    {
        Widget widget = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/debug/day_z_hud_debug_agent.layout", m_WgtAgents );
        ButtonWidget btn = ButtonWidget.Cast( widget.FindAnyWidget( "TextAgentName" ) );
        DebugAgentData data = new DebugAgentData( "", id );
        m_AgentWidgetData.Insert(btn, data);
        Widget activate_button = widget.FindAnyWidget( "ButtonAgentActivate" );
        m_AgentWidgetData.Insert( activate_button, data );
        TextWidget count_widget = TextWidget.Cast(widget.FindAnyWidget( "TextWidgetAgentCount" ));
        m_AgentWidgetData.Insert( count_widget, data );
        count_widget.SetText(value);
        //Deactivate button
        Widget deactivate_button = widget.FindAnyWidget( "ButtonAgentDeactivate" );
        m_AgentWidgetData.Insert( deactivate_button, data );
        btn.SetText(title);
        m_AgentWidgets.Insert(widget);
        AutoHeightSpacer WgtModifiersContent_panel_script;
        m_WgtAgents.GetScript( WgtModifiersContent_panel_script );
        WgtModifiersContent_panel_script.Update();
    }
References WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_AgentWidgetData, m_AgentWidgets, m_WgtAgents, and AutoHeightSpacer::Update().
Referenced by SetAgents().
ClearAgents()
void ClearAgents ()
Definition at line 217 of file huddebugwincharagents.c.
    {
        m_AgentWidgetData.Clear();
        for ( int i = 0; i < m_AgentWidgets.Count(); i++ )
        {
            delete m_AgentWidgets.Get( i );
        }
        m_AgentWidgets.Clear();
    }
References m_AgentWidgetData, and m_AgentWidgets.
Referenced by SetAgents().
DebugGrowAgentsRequest()
void DebugGrowAgentsRequest (int agent_id, bool should_grow)
Definition at line 170 of file huddebugwincharagents.c.
    {
        if(!should_grow)//id is minus value to mark killing instead of growing
        {
            agent_id *= -1;
        }
        ref Param1<int> p1 = new Param1<int>( agent_id );
        Man man = GetGame().GetPlayer();
        man.RPCSingleParam(ERPCs.DEV_AGENT_GROW, p1, true, man.GetIdentity());
    }
References GetGame(), and CGame::GetPlayer().
Referenced by OnClick().
DebugRemoveAgentsRequest()
void DebugRemoveAgentsRequest ()
Definition at line 182 of file huddebugwincharagents.c.
    {
        ref Param1<bool> p1 = new Param1<bool>( false );
        Man man = GetGame().GetPlayer();
        man.RPCSingleParam(ERPCs.DEV_RPC_AGENT_RESET, p1, true, man.GetIdentity());
    }
References GetGame(), and CGame::GetPlayer().
Referenced by OnClick().
FitWindow()
void FitWindow ()
Definition at line 228 of file huddebugwincharagents.c.
    {
        FitWindowByContent( TextListboxWidget.Cast(m_WgtAgents) );
    }
References HudDebugWinBase::FitWindowByContent(), and m_WgtAgents.
GetType()
override int GetType ()
Definition at line 49 of file huddebugwincharagents.c.
    {
        return HudDebug.HUD_WIN_CHAR_AGENTS;
    }
References HudDebug().
Hide()
override void Hide ()
Definition at line 105 of file huddebugwincharagents.c.
    {
        super.Hide();
        //Print("Hide()");
        SetUpdate( false );
    }
References HudDebugWinBase::SetUpdate().
HudDebugWinCharAgents()
void HudDebugWinCharAgents (Widget widget_root)
Definition at line 32 of file huddebugwincharagents.c.
    {
        m_WgtRoot = widget_root;
        //m_WgtAgents = TextListboxWidget.Cast( m_WgtRoot.FindAnyWidget( "txl_CharAgents_Values" ) );
        m_WgtAgents = m_WgtRoot.FindAnyWidget( "AgentList" );
        //FitWindowByContent( m_WgtAgents );
    }
References m_WgtAgents, and m_WgtRoot.
Referenced by Init().
OnClick()
bool OnClick (Widget w, int x, int y, int button)
Definition at line 141 of file huddebugwincharagents.c.
    {
        //Button activate
        DebugAgentData data;
        if ( w.GetName() == "ButtonAgentActivate" )
        {
            data = m_AgentWidgetData.Get( w );
            DebugGrowAgentsRequest(data.GetID(), true);
            //Print("activate" + data.GetID().ToString());
            return true;
        }
        //Button deactivate
        else if ( w.GetName() == "ButtonAgentDeactivate" )
        {
            data = m_AgentWidgetData.Get( w );
            DebugGrowAgentsRequest(data.GetID(), false);
            //Print("deactivate" + data.GetID().ToString());
            return true;
        }
        else if ( w.GetName() == "ResetAgents" )
        {
            DebugRemoveAgentsRequest();
            return true;
        }
        return false;
    }
References DebugGrowAgentsRequest(), DebugRemoveAgentsRequest(), DebugAgentData::GetID(), and m_AgentWidgetData.
SetAgents()
void SetAgents ()
Definition at line 114 of file huddebugwincharagents.c.
    {
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //clear window
        ClearAgents();
        //set agents
        if ( developer_sync.m_PlayerAgentsSynced.Count() > 0 )
        {
            for ( int i = 0; i < developer_sync.m_PlayerAgentsSynced.Count(); i++ )
            {
                AddAgent( developer_sync.m_PlayerAgentsSynced.Get( i ).GetName(), developer_sync.m_PlayerAgentsSynced.Get( i ).GetValue(), developer_sync.m_PlayerAgentsSynced.Get( i ).GetID() );
            }
        }
        //fit to screen
        //FitWindow();
    }
References AddAgent(), ClearAgents(), and GetPlugin().
Referenced by Update().
SetUpdate()
override void SetUpdate (bool state)
Definition at line 57 of file huddebugwincharagents.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        PluginDeveloperSync developer_sync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<bool> params = new Param1<bool>( state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_AGENTS_UPDATE, params, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( developer_sync )
            {
                developer_sync.EnableUpdate( state, ERPCs.DEV_AGENTS_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), GetPlugin(), and HudDebugWinBase::SetRPCSent().
Show()
override void Show ()
Definition at line 96 of file huddebugwincharagents.c.
    {
        super.Show();
        //Print("Show()");
        SetUpdate( true );
    }
References HudDebugWinBase::SetUpdate().
~HudDebugWinCharAgents()
void ~HudDebugWinCharAgents ()
Definition at line 41 of file huddebugwincharagents.c.
    {
        SetUpdate( false );
    }
References HudDebugWinBase::SetUpdate().
Variable Documentation
m_AgentWidgetData
protected ref map<Widget, ref DebugAgentData> m_AgentWidgetData = new map<Widget, ref DebugAgentData>
Definition at line 28 of file huddebugwincharagents.c.
Referenced by AddAgent(), ClearAgents(), and OnClick().
m_AgentWidgets
protected ref array<ref Widget> m_AgentWidgets = new array<ref Widget>
Definition at line 27 of file huddebugwincharagents.c.
Referenced by AddAgent(), and ClearAgents().
m_WgtAgents
class DebugAgentData m_WgtAgents
Referenced by AddAgent(), FitWindow(), and HudDebugWinCharAgents().