DayzKode: P:/scripts/5_mission/DayZ/gui/huddebug.c File Reference
huddebug.c File Reference
Classes
class ScriptedWidgetEventHandler
map: item x vector(index, width, height)
Functions
void HideCrosshairVisibility ()
void HudDebug ()
override void Init (Widget hud_panel_widget)
bool IsInitialized ()
bool OnChange (Widget w, int x, int y, bool finished)
bool OnClick (Widget w, int x, int y, int button)
void PanelHide (int panel_type)
void PanelShow (int panel_type)
void RefreshByLocalProfile ()
void RefreshCrosshairVisibility ()
void SetPanelVisible (int panel_type, bool visible)
override void Update (float timeslice)
void ~HudDebug ()
Variables
static const int HUD_WIN_CHAR_AGENTS = 3
static const int HUD_WIN_CHAR_DEBUG = 4
static const int HUD_WIN_CHAR_LEVELS = 5
static const int HUD_WIN_CHAR_MODIFIERS = 2
static const int HUD_WIN_CHAR_STATS = 1
static const int HUD_WIN_CHAR_STOMACH = 6
static const int HUD_WIN_TEMPERATURE = 8
class HudDebugEventHandler extends ScriptedWidgetEventHandler HUD_WIN_UNDEFINED = 0
static const int HUD_WIN_VERSION = 7
Widget m_Crosshair
ref HudDebugEventHandler m_HudDebugHandler
ref array< ref HudDebugWinBase > m_Panels
ref Timer m_TimerUpdate
Widget m_WgtRoot
ref HudDebugWinCharAgents m_WinCharAgents
ref HudDebugWinCharModifiers m_WinCharModifiers
ref HudDebugWinCharStats m_WinCharStats
Function Documentation
HideCrosshairVisibility()
void HideCrosshairVisibility ()
Definition at line 261 of file huddebug.c.
    {
        PluginConfigDebugProfile module_cfg_profile = PluginConfigDebugProfile.Cast( GetPlugin( PluginConfigDebugProfile ) );
        if ( module_cfg_profile )
        {
            PluginDeveloper modul_dev = PluginDeveloper.Cast( GetPlugin( PluginDeveloper ) );
            if ( modul_dev.IsEnabledFreeCamera() )
            {
                m_Crosshair.Show( false );
            }
        }
    }
References GetPlugin(), and m_Crosshair.
HudDebug()
void HudDebug ()
Definition at line 104 of file huddebug.c.
    {
    }
Referenced by HudDebugWinBase::GetType(), GetType(), MissionBase::OnInit(), and RefreshByLocalProfile().
Init()
override void Init (Widget hud_panel_widget)
Definition at line 120 of file huddebug.c.
    {
        m_WgtRoot = hud_panel_widget;
        m_WgtRoot.Show( true );
        // Crosshair widget root
        m_Crosshair = m_WgtRoot.FindAnyWidget( "wdw_Crosshair" );
        m_Panels = new array<ref HudDebugWinBase>;
        // Register Window Character Stats
        m_WinCharStats = new HudDebugWinCharStats( m_WgtRoot.FindAnyWidget( "wdw_CharacterStats" ) );
        m_Panels.Insert( m_WinCharStats );
        // Register Window Character Stats
        HudDebugWinCharLevels win_char_levels = new HudDebugWinCharLevels( m_WgtRoot.FindAnyWidget( "wdw_CharacterLevels" ) );
        m_Panels.Insert( win_char_levels );
        // Register Window Chracter Modifiers
        m_WinCharModifiers = new HudDebugWinCharModifiers( m_WgtRoot.FindAnyWidget( "wdw_CharacterModifiers" ) );
        m_Panels.Insert( m_WinCharModifiers );
        // Register Window Chracter Agents
        m_WinCharAgents = new HudDebugWinCharAgents( m_WgtRoot.FindAnyWidget( "wdw_CharacterAgents" ) );
        m_Panels.Insert( m_WinCharAgents );
        // Register Window Chracter Debug
        HudDebugWinCharDebug win_char_debug = new HudDebugWinCharDebug( m_WgtRoot.FindAnyWidget( "wdw_CharacterDebug" ) );
        m_Panels.Insert( win_char_debug );
        // Register Window Chracter Debug
        HudDebugWinCharStomach win_char_stomach = new HudDebugWinCharStomach( m_WgtRoot.FindAnyWidget( "wdw_CharacterStomach" ) );
        m_Panels.Insert( win_char_stomach );
        // Register Window Version
        HudDebugWinVersion win_version = new HudDebugWinVersion( m_WgtRoot.FindAnyWidget( "wdw_Version" ) );
        m_Panels.Insert( win_version );
        // Register Window Temperature
        HudDebugWinTemperature win_temp = new HudDebugWinTemperature( m_WgtRoot.FindAnyWidget( "wdw_Temp" ) );
        m_Panels.Insert( win_temp );
        RefreshByLocalProfile();
        RefreshCrosshairVisibility();
        m_TimerUpdate = new Timer();
        m_TimerUpdate.Run( 1.0, this, "Update", NULL, true );
        //set ui event handler
        m_HudDebugHandler = new HudDebugEventHandler( this );
        m_WgtRoot.SetHandler( m_HudDebugHandler );
    }
References HudDebugWinCharAgents(), HudDebugWinCharModifiers(), m_Crosshair, m_HudDebugHandler, m_Panels, m_TimerUpdate, m_WgtRoot, m_WinCharAgents, m_WinCharModifiers, m_WinCharStats, RefreshByLocalProfile(), and RefreshCrosshairVisibility().
IsInitialized()
bool IsInitialized ()
Definition at line 299 of file huddebug.c.
    {
        if ( m_WgtRoot == NULL )
        {
            return false;
        }
        return false;
    }
References m_WgtRoot.
OnChange()
bool OnChange (Widget w, int x, int y, bool finished)
Definition at line 336 of file huddebug.c.
    {
        if ( m_WinCharStats )
        {
            if (m_WinCharStats.OnChange( w, x, y, finished ))
                return true;
        }
        return false;
    }
References m_WinCharStats, x, and y.
OnClick()
bool OnClick (Widget w, int x, int y, int button)
Definition at line 312 of file huddebug.c.
    {
        //send OnClick to HudDebugWinCharModifiers
        if ( m_WinCharModifiers )
        {
            if (m_WinCharModifiers.OnClick( w, x, y, button ))
                return true;
        }
        if ( m_WinCharAgents )
        {
            if (m_WinCharAgents.OnClick( w, x, y, button ))
                return true;
        }
        if ( m_WinCharStats )
        {
            if (m_WinCharStats.OnClick( w, x, y, button ))
                return true;
        }
        return false;
    }
References m_WinCharAgents, m_WinCharModifiers, m_WinCharStats, x, and y.
PanelHide()
void PanelHide (int panel_type)
Definition at line 222 of file huddebug.c.
    {
        for ( int i = 0; i < m_Panels.Count(); ++i )
        {
            HudDebugWinBase panel = m_Panels.Get( i );
            if ( panel.GetType() == panel_type )
            {
                panel.Hide();
            }
        }
    }
References HudDebugWinBase::GetType(), HudDebugWinBase::Hide(), and m_Panels.
Referenced by SetPanelVisible().
PanelShow()
void PanelShow (int panel_type)
Definition at line 206 of file huddebug.c.
    {
        for ( int i = 0; i < m_Panels.Count(); ++i )
        {
            HudDebugWinBase panel = m_Panels.Get( i );
            if ( panel.GetType() == panel_type )
            {
                panel.Show();
            }
        }
    }
References HudDebugWinBase::GetType(), m_Panels, and HudDebugWinBase::Show().
Referenced by SetPanelVisible().
RefreshByLocalProfile()
void RefreshByLocalProfile ()
Definition at line 279 of file huddebug.c.
    {
        PluginConfigDebugProfile module_cfg_profile = PluginConfigDebugProfile.Cast( GetPlugin( PluginConfigDebugProfile ) );
        if ( module_cfg_profile )
        {
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_STATS,       module_cfg_profile.GetCharacterStatsVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_LEVELS,      module_cfg_profile.GetCharacterLevelsVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_MODIFIERS,   module_cfg_profile.GetCharacterModifiersVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_AGENTS,      module_cfg_profile.GetCharacterAgentsVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_DEBUG,       module_cfg_profile.GetCharacterDebugVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_CHAR_STOMACH,     module_cfg_profile.GetCharacterStomachVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_VERSION,          module_cfg_profile.GetVersionVisible() );
            SetPanelVisible( HudDebug.HUD_WIN_TEMPERATURE,      module_cfg_profile.GetTempVisible() );
        }
    }
References GetPlugin(), HudDebug(), and SetPanelVisible().
Referenced by Init().
RefreshCrosshairVisibility()
void RefreshCrosshairVisibility ()
Definition at line 238 of file huddebug.c.
    {
        PluginConfigDebugProfile module_cfg_profile = PluginConfigDebugProfile.Cast( GetPlugin( PluginConfigDebugProfile ) );
        if ( module_cfg_profile )
        {
            PluginDeveloper modul_dev = PluginDeveloper.Cast( GetPlugin( PluginDeveloper ) );
            if ( modul_dev.IsEnabledFreeCamera() )
            {
                m_Crosshair.Show( module_cfg_profile.GetFreeCameraCrosshairVisible() );
            }
            else
            {
                m_Crosshair.Show( false );
            }
        }
    }
References GetPlugin(), and m_Crosshair.
Referenced by Init(), and UIScriptedMenu::OnClick().
SetPanelVisible()
void SetPanelVisible (int panel_type, bool visible)
Definition at line 191 of file huddebug.c.
    {
        if ( visible )
        {
            PanelShow( panel_type );
        }
        else
        {
            PanelHide( panel_type );
        }
    }
References PanelHide(), and PanelShow().
Referenced by RefreshByLocalProfile().
Update()
override void Update (float timeslice)
Definition at line 177 of file huddebug.c.
    {
        for ( int i = 0; i < m_Panels.Count(); ++i )
        {
            if ( m_Panels.Get( i ).IsVisible() )
            {
                m_Panels.Get( i ).Update();
            }
        }
    }
References m_Panels.
~HudDebug()
void ~HudDebug ()
Definition at line 111 of file huddebug.c.
    {
        delete m_WgtRoot;
        m_TimerUpdate.Stop();
    }
References m_TimerUpdate, and m_WgtRoot.
Variable Documentation
HUD_WIN_CHAR_AGENTS
const int HUD_WIN_CHAR_AGENTS = 3 static
Definition at line 85 of file huddebug.c.
HUD_WIN_CHAR_DEBUG
const int HUD_WIN_CHAR_DEBUG = 4 static
Definition at line 86 of file huddebug.c.
HUD_WIN_CHAR_LEVELS
const int HUD_WIN_CHAR_LEVELS = 5 static
Definition at line 87 of file huddebug.c.
HUD_WIN_CHAR_MODIFIERS
const int HUD_WIN_CHAR_MODIFIERS = 2 static
Definition at line 84 of file huddebug.c.
HUD_WIN_CHAR_STATS
const int HUD_WIN_CHAR_STATS = 1 static
Definition at line 83 of file huddebug.c.
HUD_WIN_CHAR_STOMACH
const int HUD_WIN_CHAR_STOMACH = 6 static
Definition at line 88 of file huddebug.c.
HUD_WIN_TEMPERATURE
const int HUD_WIN_TEMPERATURE = 8 static
Definition at line 90 of file huddebug.c.
HUD_WIN_UNDEFINED
class HudDebugEventHandler extends ScriptedWidgetEventHandler HUD_WIN_UNDEFINED = 0
HUD_WIN_VERSION
const int HUD_WIN_VERSION = 7 static
Definition at line 89 of file huddebug.c.
m_Crosshair
Widget m_Crosshair
Definition at line 93 of file huddebug.c.
Referenced by HideCrosshairVisibility(), Init(), and RefreshCrosshairVisibility().
m_HudDebugHandler
ref HudDebugEventHandler m_HudDebugHandler
Definition at line 96 of file huddebug.c.
Referenced by Init().
m_Panels
ref array<ref HudDebugWinBase> m_Panels
Definition at line 94 of file huddebug.c.
m_TimerUpdate
ref Timer m_TimerUpdate
Definition at line 95 of file huddebug.c.
m_WgtRoot
Widget m_WgtRoot
Definition at line 92 of file huddebug.c.
Referenced by FitWindow(), HudDebugWinCharAgents(), HudDebugWinCharModifiers(), HudDebugWinBase::HudDebugWinCharStats(), UIScriptedWindow::Init(), Init(), IsInitialized(), UIPopupScript::OnClick(), UIScriptedMenu::ToggleVisibility(), HudDebugWinBase::Update(), and ~HudDebug().
m_WinCharAgents
ref HudDebugWinCharAgents m_WinCharAgents
Definition at line 99 of file huddebug.c.
Referenced by Init(), and OnClick().
m_WinCharModifiers
ref HudDebugWinCharModifiers m_WinCharModifiers
Definition at line 97 of file huddebug.c.
Referenced by Init(), and OnClick().
m_WinCharStats
ref HudDebugWinCharStats m_WinCharStats
Definition at line 98 of file huddebug.c.
Referenced by Init(), OnChange(), and OnClick().