DayzKode: P:/scripts/5_mission/DayZ/gui/scriptshuddebug/huddebugwincharmodifiers.c File Reference
huddebugwincharmodifiers.c File Reference
Classes
class DebugModifierData
Functions
void ActivateModifier (int id)
void AddModifier (string name, int id, bool active, bool locked)
void ClearModifiers ()
void DeactivateModifier (int id)
void FitWindow ()
override int GetType ()
override void Hide ()
void HudDebugWinCharModifiers (Widget widget_root)
void LockModifier (int id, bool state)
bool OnClick (Widget w, int x, int y, int button)
void Refresh ()
void RequestDetailedInfo (int id)
void ResetModifiers ()
void SetModifiers ()
override void SetUpdate (bool state)
override void Show ()
override void Update ()
void ~HudDebugWinCharModifiers ()
Variables
protected int m_DetailedInfoIndex
protected ref map< Widget, ref DebugModifierData > m_ModifierWidgetData
protected ref array< ref Widget > m_ModifierWidgets
protected PluginDeveloperSync m_PluginDeveloperSync
protected Widget m_WgtDetailedInfo
protected TextWidget m_WgtDetailedInfoText
class DebugModifierData m_WgtModifiersContent
Function Documentation
ActivateModifier()
void ActivateModifier (int id)
Definition at line 361 of file huddebugwincharmodifiers.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<int> params = new Param1<int>( id );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_RPC_MODS_ACTIVATE, params, true );
            }
        }
        //else set directly
        else
        {
            m_PluginDeveloperSync.ActivateModifier( id );
        }
    }
References GetGame(), GetPlayer(), and m_PluginDeveloperSync.
AddModifier()
void AddModifier (string name, int id, bool active, bool locked)
Definition at line 173 of file huddebugwincharmodifiers.c.
    {
        //create widget
        Widget widget = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/debug/day_z_hud_debug_modifier.layout", m_WgtModifiersContent );
        //add to widget array (for clearing purposes)
        m_ModifierWidgets.Insert( widget );
        //set widget name
        ButtonWidget mod_name_text = ButtonWidget.Cast( widget.FindAnyWidget( "TextModifierName" ) );
        mod_name_text.SetText( name );
        if ( active )
        {
            mod_name_text.SetTextColor( ARGB( 255, 0, 255, 0 ) );
        }
        else
        {
            mod_name_text.SetTextColor( ARGB( 255, 255, 0, 0 ) );
        }
        //set set data for interactive parts (modifier ID should be enough)
        DebugModifierData data = new DebugModifierData( name, id );
        Widget modifier_button = widget.FindAnyWidget( "TextModifierName" );
        m_ModifierWidgetData.Insert( modifier_button, data );
        //Activate button
        Widget activate_button = widget.FindAnyWidget( "ButtonModifierActivate" );
        m_ModifierWidgetData.Insert( activate_button, data );
        //Deactivate button
        Widget deactivate_button = widget.FindAnyWidget( "ButtonModifierDeactivate" );
        m_ModifierWidgetData.Insert( deactivate_button, data );
        //Lock checkbox
        Widget checkbox_widget = widget.FindAnyWidget( "CheckBoxLock" );
        m_ModifierWidgetData.Insert( checkbox_widget, data );
        //set lock based on checkbox value
        CheckBoxWidget checkbox = CheckBoxWidget.Cast( checkbox_widget );
        checkbox.SetChecked( locked );
        AutoHeightSpacer WgtModifiersContent_panel_script;
        m_WgtModifiersContent.GetScript( WgtModifiersContent_panel_script );
        WgtModifiersContent_panel_script.Update();
    }
References ARGB(), WorkspaceWidget::CreateWidgets(), GetGame(), CGame::GetWorkspace(), m_ModifierWidgetData, m_ModifierWidgets, m_WgtModifiersContent, name, and AutoHeightSpacer::Update().
ClearModifiers()
void ClearModifiers ()
Definition at line 218 of file huddebugwincharmodifiers.c.
    {
        //clear widget data
        m_ModifierWidgetData.Clear();
        //destroy all modifier widgets
        for ( int i = 0; i < m_ModifierWidgets.Count(); ++i )
        {
            delete m_ModifierWidgets.Get( i );
        }
        m_ModifierWidgets.Clear();
    }
References m_ModifierWidgetData, and m_ModifierWidgets.
Referenced by SetModifiers().
DeactivateModifier()
void DeactivateModifier (int id)
Definition at line 382 of file huddebugwincharmodifiers.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<int> params = new Param1<int>( id );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_RPC_MODS_DEACTIVATE, params, true );
            }
        }
        //else set directly
        else
        {
            m_PluginDeveloperSync.DeactivateModifier( id );
        }
    }
References GetGame(), GetPlayer(), and m_PluginDeveloperSync.
FitWindow()
void FitWindow ()
Definition at line 130 of file huddebugwincharmodifiers.c.
    {
        float title_size = 20;
        float spacing = 20;
        //get wgt content size values
        float wgt_content_size_x;
        float wgt_content_size_y;
        m_WgtModifiersContent.GetSize( wgt_content_size_x, wgt_content_size_y );
        //get wgt root size values
        float wgt_root_size_x;
        float wgt_root_size_y;
        m_WgtRoot.GetSize( wgt_root_size_x, wgt_root_size_y );
        //calculate new Y size
        float new_size_y = title_size + wgt_content_size_y + spacing;
        //set size
        m_WgtRoot.SetSize( wgt_root_size_x, new_size_y );
    }
References m_WgtModifiersContent, and m_WgtRoot.
GetType()
override int GetType ()
Definition at line 55 of file huddebugwincharmodifiers.c.
    {
        return HudDebug.HUD_WIN_CHAR_MODIFIERS;
    }
References HudDebug().
Hide()
override void Hide ()
Definition at line 107 of file huddebugwincharmodifiers.c.
    {
        super.Hide();
        //Print("Hide()");
        SetUpdate( false );
    }
References HudDebugWinBase::SetUpdate().
HudDebugWinCharModifiers()
void HudDebugWinCharModifiers (Widget widget_root)
Definition at line 38 of file huddebugwincharmodifiers.c.
    {
        m_WgtRoot = widget_root;
        m_WgtModifiersContent = Widget.Cast( m_WgtRoot.FindAnyWidget( "pnl_CharModifiers_Values" ) );
        m_ModifierWidgets = new array<ref Widget>;
        m_ModifierWidgetData = new map<Widget, ref DebugModifierData>;
        m_PluginDeveloperSync = PluginDeveloperSync.Cast( GetPlugin( PluginDeveloperSync ) );
    }
References GetPlugin(), m_ModifierWidgetData, m_ModifierWidgets, m_PluginDeveloperSync, m_WgtModifiersContent, and m_WgtRoot.
Referenced by Init().
LockModifier()
void LockModifier (int id, bool state)
Definition at line 403 of file huddebugwincharmodifiers.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param2<int, bool> params = new Param2<int, bool>( id, state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_RPC_MODS_LOCK, params, true );
            }
        }
        //else set directly
        else
        {
            m_PluginDeveloperSync.LockModifier( id, state );
        }
    }
References GetGame(), GetPlayer(), and m_PluginDeveloperSync.
Referenced by OnClick().
OnClick()
bool OnClick (Widget w, int x, int y, int button)
Definition at line 234 of file huddebugwincharmodifiers.c.
    {
        if ( w )
        {
            if ( w.GetName() == "TextModifierName" )
            {
                //Print("clicked");
                DebugModifierData bc_data = m_ModifierWidgetData.Get( w );
                //Print( bc_data.GetID() );
                if(bc_data.GetID() == m_DetailedInfoIndex)//repeated request --> hide
                {
                    if(m_WgtDetailedInfo && m_WgtDetailedInfo.IsVisible())
                    {
                        m_WgtDetailedInfo.Show(false);
                    }
                    m_DetailedInfoIndex = 0;
                }
                else
                {
                    if(!m_WgtDetailedInfo)
                        m_WgtDetailedInfo = GetGame().GetWorkspace().CreateWidgets( "gui/layouts/debug/day_z_hud_debug_modifier_detailed.layout");
                    if(!m_WgtDetailedInfo.IsVisible())
                    {
                        m_WgtDetailedInfo.Show(true);
                    }
                    m_DetailedInfoIndex = bc_data.GetID();
                }
                if( m_WgtDetailedInfoText )
                    m_WgtDetailedInfoText.SetText("");
                m_PluginDeveloperSync.m_PlayerModsDetailedSynced = "";
                RequestDetailedInfo( bc_data.GetID());
                return true;
            }
            //Button activate
            if ( w.GetName() == "ButtonModifierActivate" )
            {
                DebugModifierData ba_data = m_ModifierWidgetData.Get( w );
                //activate
                ActivateModifier( ba_data.GetID() );
                //force update
                m_PluginDeveloperSync.Update();
                return true;
            }
            //Button deactivate
            else if ( w.GetName() == "ButtonModifierDeactivate" )
            {
                DebugModifierData bd_data = m_ModifierWidgetData.Get( w );
                //deactivate
                DeactivateModifier( bd_data.GetID() );
                //force update
                m_PluginDeveloperSync.Update();
                return true;
            }
            //Lock checkbox
            else if ( w.GetName() == "CheckBoxLock" )
            {
                DebugModifierData lcb_data = m_ModifierWidgetData.Get( w );
                CheckBoxWidget checkbox = CheckBoxWidget.Cast( w );
                //set lock
                LockModifier( lcb_data.GetID(), checkbox.IsChecked() );
                //force update
                m_PluginDeveloperSync.Update();
                return true;
            }
            else if ( w.GetName() == "ResetModifiers" )
            {
                ResetModifiers();
                return true;
            }
        }
        return false;
    }
References ActivateModifier(), WorkspaceWidget::CreateWidgets(), DeactivateModifier(), GetGame(), DebugModifierData::GetID(), CGame::GetWorkspace(), LockModifier(), m_DetailedInfoIndex, m_ModifierWidgetData, m_PluginDeveloperSync, m_WgtDetailedInfo, m_WgtDetailedInfoText, RequestDetailedInfo(), and ResetModifiers().
Refresh()
void Refresh ()
Definition at line 116 of file huddebugwincharmodifiers.c.
    {
        SetModifiers();
        if(m_WgtDetailedInfo && m_WgtDetailedInfo.IsVisible())
        {
            if(!m_WgtDetailedInfoText)
                m_WgtDetailedInfoText = TextWidget.Cast(m_WgtDetailedInfo.FindAnyWidget( "TextWidget" ));
            m_WgtDetailedInfoText.SetText(m_PluginDeveloperSync.m_PlayerModsDetailedSynced);
        }
    }
References m_PluginDeveloperSync, m_WgtDetailedInfo, m_WgtDetailedInfoText, and SetModifiers().
RequestDetailedInfo()
void RequestDetailedInfo (int id)
Definition at line 340 of file huddebugwincharmodifiers.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<int> params = new Param1<int>( id );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_RPC_MODS_DETAILED, params, true );
            }
        }
        //else set directly
        else
        {
            m_PluginDeveloperSync.RequestDetailedInfo( id , player);
        }
    }
References GetGame(), GetPlayer(), and m_PluginDeveloperSync.
Referenced by OnClick().
ResetModifiers()
void ResetModifiers ()
Definition at line 324 of file huddebugwincharmodifiers.c.
    {
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        ref Param1<bool> params = new Param1<bool>( false );
        if ( player )
        {
            player.RPCSingleParam( ERPCs.DEV_RPC_MODS_RESET, params, true );
        }
    }
References GetGame(), and GetPlayer().
Referenced by OnClick().
SetModifiers()
void SetModifiers ()
Definition at line 155 of file huddebugwincharmodifiers.c.
    {
        //clear window
        ClearModifiers();
        if ( m_PluginDeveloperSync.m_PlayerModsSynced.Count() > 0 )
        {
            //set active mods
            for ( int i = 0; i < m_PluginDeveloperSync.m_PlayerModsSynced.Count(); ++i )
            {
                SyncedValueModifier synced_value = m_PluginDeveloperSync.m_PlayerModsSynced.Get( i );
                AddModifier( synced_value.GetName(), synced_value.GetID(), synced_value.GetActive(),synced_value.GetLocked() );
            }
        }
        FitWindow();
    }
References AddModifier(), ClearModifiers(), HudDebugWinBase::FitWindow(), SyncedValueModifier::GetActive(), SyncedValueModifier::GetID(), SyncedValueModifier::GetLocked(), SyncedValueModifier::GetName(), and m_PluginDeveloperSync.
Referenced by Refresh().
SetUpdate()
override void SetUpdate (bool state)
Definition at line 63 of file huddebugwincharmodifiers.c.
    {
        //Disable update on server (PluginDeveloperSync)
        PlayerBase player = PlayerBase.Cast( GetGame().GetPlayer() );
        //if client, send RPC
        if ( GetGame().IsClient() )
        {
            ref Param1<bool> params = new Param1<bool>( state );
            if ( player )
            {
                player.RPCSingleParam( ERPCs.DEV_MODS_UPDATE, params, true );
                SetRPCSent();
            }
        }
        //else set directly
        else
        {
            if ( m_PluginDeveloperSync )
            {
                m_PluginDeveloperSync.EnableUpdate( state, ERPCs.DEV_MODS_UPDATE, player );
            }
        }
    }
References GetGame(), GetPlayer(), m_PluginDeveloperSync, and HudDebugWinBase::SetRPCSent().
Show()
override void Show ()
Definition at line 98 of file huddebugwincharmodifiers.c.
    {
        super.Show();
        //Print("Show()");
        SetUpdate( true );
    }
References HudDebugWinBase::SetUpdate().
~HudDebugWinCharModifiers()
void ~HudDebugWinCharModifiers ()
Definition at line 47 of file huddebugwincharmodifiers.c.
    {
        SetUpdate( false );
    }
References HudDebugWinBase::SetUpdate().
Variable Documentation
m_DetailedInfoIndex
protected int m_DetailedInfoIndex
Definition at line 31 of file huddebugwincharmodifiers.c.
Referenced by OnClick().
m_ModifierWidgetData
protected ref map<Widget, ref DebugModifierData> m_ModifierWidgetData
Definition at line 27 of file huddebugwincharmodifiers.c.
Referenced by AddModifier(), ClearModifiers(), HudDebugWinCharModifiers(), and OnClick().
m_ModifierWidgets
protected ref array<ref Widget> m_ModifierWidgets
Definition at line 26 of file huddebugwincharmodifiers.c.
Referenced by AddModifier(), ClearModifiers(), and HudDebugWinCharModifiers().
m_PluginDeveloperSync
protected PluginDeveloperSync m_PluginDeveloperSync
Definition at line 28 of file huddebugwincharmodifiers.c.
Referenced by ActivateModifier(), DeactivateModifier(), HudDebugWinCharModifiers(), HudDebugWinBase::HudDebugWinTemperature(), LockModifier(), OnClick(), Refresh(), RequestDetailedInfo(), SetModifiers(), SetUpdate(), and HudDebugWinBase::SetUpdate().
m_WgtDetailedInfo
protected Widget m_WgtDetailedInfo
Definition at line 29 of file huddebugwincharmodifiers.c.
Referenced by OnClick(), and Refresh().
m_WgtDetailedInfoText
protected TextWidget m_WgtDetailedInfoText
Definition at line 30 of file huddebugwincharmodifiers.c.
Referenced by OnClick(), and Refresh().
m_WgtModifiersContent
class DebugModifierData m_WgtModifiersContent
Referenced by AddModifier(), FitWindow(), and HudDebugWinCharModifiers().