DayzKode: P:/scripts/3_game/DayZ/human.c File Reference
human.c File Reference
Classes
class HumanAnimInterface
class HumanCommandClimb
command itself
class HumanCommandDeathCallback
class HumanCommandLadder
class HumanCommandMelee2
class HumanCommandMove
class HumanCommandUnconscious
class HumanCommandVehicle
class HumanCommandWeapons
class HumanInputController
class HumanMovementState
Typedefs
typedef int TAnimGraphEvent
typedef int TAnimGraphTag
typedef int TAnimGraphVariable
Enumerations
enum ClimbStates {
STATE_MOVE , STATE_TAKEOFF , STATE_ONTOP , STATE_FALLING ,
STATE_FINISH
}
state of climb command
enum HumanMoveCommandID
do not process rotations !
enum WeaponActionChamberingLoaderTypes { CHAMBERINGLOADER_OPENED = 0 , CHAMBERINGLOADER_CLOSED = 1 }
enum WeaponActionChamberingTypes {
CHAMBERING_END = -1 , CHAMBERING_ONEBULLET_OPENED = 0 , CHAMBERING_ONEBULLET_CLOSED = 1 , CHAMBERING_ONEBULLET_CLOSED_UNCOCKED = 2 ,
CHAMBERING_ONEBULLET_UNIQUE_OPENED = 3 , CHAMBERING_ONEBULLET_UNIQUE_CLOSED = 4 , CHAMBERING_TWOBULLETS_START = 6 , CHAMBERING_TWOBULLETS_END = 7 ,
CHAMBERING_STARTLOOPABLE_CLOSED = 10 , CHAMBERING_ENDLOOPABLE = 11 , CHAMBERING_STARTLOOPABLE_CLOSED_KEEP = 12 , CHAMBERING_STARTLOOPABLE_OPENED = 13 ,
CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED = 15 , CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED = 16 , CHAMBERING_DOUBLE_1 = 17 , CHAMBERING_DOUBLE_2 = 18 ,
CHAMBERING_DOUBLE_3 = 19 , CHAMBERING_DOUBLE_4 = 20 , CHAMBERING_CROSSBOW_OPENED = 21 , CHAMBERING_CROSSBOW_CLOSED = 22 ,
CHAMBERING_CROSSBOW_FULL = 23
}
enum WeaponActionFireTypes {
FIRE_NORMAL = 0 , FIRE_LAST = 1 , FIRE_COCKED = 2 , FIRE_UNCOCKED = 3 ,
FIRE_DRY = 4 , FIRE_JAM = 5
}
enum WeaponActionReloadClipTypes { RELOADRIFLE_CLIP_NOBULLET = 0 , RELOADRIFLE_CLIP_BULLET = 1 }
enum WeaponActionReloadTypes {
RELOADRIFLE_MAGAZINE_BULLET = 0 , RELOADRIFLE_NOMAGAZINE_BULLET = 1 , RELOADRIFLE_MAGAZINE_NOBULLET = 2 , RELOADRIFLE_NOMAGAZINE_NOBULLET = 3 ,
RELOADRIFLE_MAGAZINE_NOBULLET_OPEN = 4 , RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN = 5 , RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED = 8 , RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED = 9 ,
RELOADPISTOL_MAGAZINE_BULLET_CLOSED = 10 , RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED = 11 , RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED = 12 , RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED = 13 ,
RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED = 14 , RELOADPISTOL_MAGAZINE_NOBULLET_OPENED = 15 , RELOAD_MAGAZINE_DETACH = 16 , RELOADRIFLE_MAGAZINE_DETACH = 17 ,
RELOADSRIFLE_MAGAZINE_BULLET = 20 , RELOADSRIFLE_NOMAGAZINE_BULLET = 21 , RELOADSRIFLE_MAGAZINE_NOBULLET = 22 , RELOADSRIFLE_NOMAGAZINE_NOBULLET = 23
}
enum WeaponActions {
INTERRUPT = 15 , NONE = -1 , RELOAD = 0 , MECHANISM = 1 ,
CHAMBERING = 2 , CHAMBERING_LOADER = 3 , UNJAMMING = 4 , FIRE = 5 ,
HIDE = 6 , SHOW = 7 , RELOAD_CLIP = 8
}
actions
enum WeaponActionUnjammingTypes { UNJAMMING_START = 1 , UNJAMMING_END = 0 , UNJAMMING_INTERRUPT = -1 }
enum WeaponEvents {
ATTACHMENT_HIDE , ATTACHMENT_SHOW , BULLET_EJECT , BULLET_HIDE ,
BULLET_HIDE2 , BULLET_IN_CHAMBER , BULLET_IN_MAGAZINE , BULLET_SHOW ,
BULLET_SHOW2 , CANUNJAM_END , CANUNJAM_START , COCKED ,
MAGAZINE_ATTACHED , MAGAZINE_DETACHED , MAGAZINE_HIDE , MAGAZINE_SHOW ,
SLIDER_OPEN , UNJAMMED , HAMMER_UNCOCKED , CHANGE_HIDE ,
CHANGE_SHOW , CYLINDER_ROTATE
}
events
enum WeaponHideShowTypes {
HIDESHOW_SLOT_2HDLEFTBACK = 0 , HIDESHOW_SLOT_RFLLEFTBACK = 1 , HIDESHOW_SLOT_1HDLEFTBACK = 2 , HIDESHOW_SLOT_2HDRIGHTBACK = 3 ,
HIDESHOW_SLOT_RFLRIGHTBACK = 4 , HIDESHOW_SLOT_1HDRIGHTBACK = 5 , HIDESHOW_SLOT_PISTOLBELT = 6 , HIDESHOW_SLOT_PISTOLCHEST = 7 ,
HIDESHOW_SLOT_KNIFEBACK = 8 , HIDESHOW_SLOT_INVENTORY = 9
}
Functions
proto native HumanCommandActionCallback AddCommandModifier_Action (int pActionID, typename pCallbackClass)
adds action command modifier, creates callback instance for you
proto native HumanCommandDamage AddCommandModifier_Damage (int pType, float pDirection)
— modifier for light Damages
proto native TAnimGraphCommand BindCommand (string pCommandName)
returns command index -
proto native TAnimGraphEvent BindEvent (string pEventName)
proto native TAnimGraphTag BindTag (string pTagName)
proto native TAnimGraphVariable BindVariableBool (string pVariable)
proto native TAnimGraphVariable BindVariableFloat (string pVariable)
proto native TAnimGraphVariable BindVariableInt (string pVariable)
proto native void Cancel ()
cancels action
proto native void CancelModifier ()
cancels modifier
bool CanChangeStance (int previousStance, int newStance)
Called by code to see if it can.
proto native bool CanExit ()
returns true if on exiting point
bool CanRoll ()
proto native void ContinueCombo ()
marks command to continue to combo
proto native void ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target=null, vector hitPos=vector.Zero)
marks command to continue to combo
proto static native bool DebugDrawClimb (Human pHuman, int pLevel)
proto static native bool DebugDrawLadder (Building pBuilding, int pLadderIndex)
debug draws any ladder
proto native owned string DebugGetItemAnimInstance ()
returns current item's animation instance
proto native owned string DebugGetItemClass ()
returns current item's class name
proto native owned string DebugGetItemSuperClass ()
returns current item's class that is found in config
proto static native int DebugGetLadderIndex (string pComponentName)
proto native int DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native void DebugResetEvents ()
proto native bool DefaultCancelCondition ()
system implemented cancel condition (now raise or sprint cancels action)
proto native void DeleteCommandModifier_Action (HumanCommandActionCallback pCallback)
force remove - normally if action is ended or interrupted - this is not needed to call
proto native void DeleteCommandModifier_Damage (HumanCommandDamage pDamage)
proto static native bool DoClimbTest (Human pHuman, SHumanCommandClimbResult pResult, int pDebugDrawLevel)
proto native void EnableCancelCondition (bool pEnable)
proto native void EnableStateChangeCallback ()
enables state change callback OnStateChange
proto native void Exit ()
proto native void ForceStance (int pStanceIdx)
proto native void ForceStanceUp (int pStanceIdx)
proto native HumanAnimInterface GetAnimInterface ()
returns animation interface - usable in HumanCommandScript implementations
proto native float GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
proto native float GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
proto native vector GetBonePositionLS (int pBoneIndex)
returns local space, model space, world space position of the bone
proto native vector GetBonePositionMS (int pBoneIndex)
proto native vector GetBonePositionWS (int pBoneIndex)
proto native void GetBoneRotationLS (int pBoneIndex, out float pQuat[4])
returns local space, model space, world space orientation (quaternion) of a bone
proto native void GetBoneRotationMS (int pBoneIndex, out float pQuat[4])
proto native void GetBoneRotationWS (int pBoneIndex, out float pQuat[4])
proto native void GetBoneTransformLS (int pBoneIndex, out vector pTm[4])
returns local space, model space, world space orientation (quaternion) of a bone
proto native void GetBoneTransformMS (int pBoneIndex, out vector pTm[4])
proto native void GetBoneTransformWS (int pBoneIndex, out vector pTm[4])
proto native vector GetClimbOverStandPointWS ()
returns world space position of landspot after climbing over
proto native int GetComboCount ()
proto native HumanCommandActionCallback GetCommand_Action ()
is human is in command action - returns its callback, if current command is action
proto native HumanCommandClimb GetCommand_Climb ()
proto native HumanCommandFullBodyDamage GetCommand_Damage ()
proto native HumanCommandDeathCallback GetCommand_Death ()
proto native HumanCommandFall GetCommand_Fall ()
proto native HumanCommandLadder GetCommand_Ladder ()
proto native HumanCommandMelee GetCommand_Melee ()
proto native HumanCommandMelee2 GetCommand_Melee2 ()
proto native HumanCommandMove GetCommand_Move ()
proto native HumanCommandScript GetCommand_Script ()
is human is in command action - returns its callback, if current command is action
proto native HumanCommandSwim GetCommand_Swim ()
proto native HumanCommandUnconscious GetCommand_Unconscious ()
proto native HumanCommandVehicle GetCommand_Vehicle ()
proto native HumanCommandActionCallback GetCommandModifier_Action ()
returns callback for action if any is active, null if nothing runs
proto native HumanCommandAdditives GetCommandModifier_Additives ()
default (always-on modifiers)
proto native HumanCommandDamage GetCommandModifier_Damage ()
proto native HumanCommandWeapons GetCommandModifier_Weapons ()
returns interface for handling weapons
proto native int GetCommandModifierCount ()
proto native int GetCommandModifierID (int pIndex)
returns COMMANDID_ .. type id of command modifier on index pIndex
proto native int GetCurrentHitType ()
proto bool GetCurrentInputAngle (out float pAngle)
proto native float GetCurrentMovementAngle ()
proto native float GetCurrentMovementSpeed ()
0,1,2..3 idle, walk, run, sprint
proto native vector GetGrabPointWS ()
returns world space position of climbing grab point
proto native Human GetHuman ()
get the human this cb belongs to
proto native HumanInputController GetInputController ()
returns human input controller
proto native HumanItemAccessor GetItemAccessor ()
proto native void GetMovementState (HumanMovementState pState)
returns movement state (current command id,)
proto native int GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
proto native int GetRunningActionType ()
returns -1 when no action is running or appropriate action type
proto native int GetState ()
returns one of STATE_...
string GetStateString ()
returns debug string of current state
static string GetStateString (int pState)
returns debug string of current state
enum HumanMoveCommandID GetTransformWS (out vector pTm[4])
gets human transform in World Space
private void HumanAnimInterface ()
class HumanAnimInterface HumanCommandActionCallback ()
class HumanCommandWeapons HumanCommandAdditives ()
private void HumanCommandClimb ()
class HumanCommandUnconscious HumanCommandDamage ()
class HumanCommandDeathCallback HumanCommandDeath ()
class HumanCommandMelee2 HumanCommandFall ()
private void HumanCommandLadder ()
class HumanCommandMove HumanCommandMelee ()
private void HumanCommandMelee2 ()
private void HumanCommandMove ()
class HumanCommandLadder HumanCommandSwim ()
private void HumanCommandUnconscious ()
private void HumanCommandWeapons ()
proto native void InternalCommand (int pInternalCommandId)
proto native bool IsActionFinished ()
proto native int IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
proto native bool IsFinisher ()
bool IsGestureCallback ()
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
bool IsInProne ()
bool IsInRaisedProne ()
proto native bool IsInRoll ()
return true if character barrel rolling
proto native bool IsInWater ()
proto native bool IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
proto native bool IsLanding ()
returns true if fall is in landing state
bool IsLeaning ()
proto native bool IsLeavingUncon ()
return true if character transitions out of uncon
proto native bool IsMeleeEvade ()
this is true when in melee evade
proto native bool IsModifierActive ()
is modifier active
proto native bool IsOnBack ()
return true if prone is on back
proto native bool IsOnLand ()
bool IsRaised ()
bool IsRaisedInProne ()
proto native bool IsStandingFromBack ()
return true if prone on back is chaning to crounch/stand
bool IsSymptomCallback ()
proto native bool IsThrowingMode ()
bool IsUserActionCallback ()
proto native void Land (int pLandType)
end fall with land
proto native void LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
proto native void LinkToLocalSpaceOf (notnull IEntity child, vector pLocalSpaceMatrix[4])
class HumanMovementState OnActivate ()
HumanCommandScript fully scriptable command.
void OnAnimationEvent (int pEventID)
calls animation event -> must be registered with RegisterAnimationEvent
void OnCommandActionAdditiveFinish ()
void OnCommandActionAdditiveStart ()
void OnCommandActionFullbodyFinish ()
void OnCommandActionFullbodyStart ()
void OnCommandClimbFinish ()
void OnCommandClimbStart ()
void OnCommandDamageAdditiveFinish ()
void OnCommandDamageAdditiveStart ()
void OnCommandDamageFullbodyFinish ()
void OnCommandDamageFullbodyStart ()
void OnCommandDeathFinish ()
void OnCommandDeathStart ()
void OnCommandFallFinish ()
void OnCommandFallStart ()
void OnCommandLadderFinish ()
void OnCommandLadderStart ()
void OnCommandMelee2Finish ()
void OnCommandMelee2Start ()
void OnCommandMeleeFinish ()
void OnCommandMeleeStart ()
void OnCommandMoveFinish ()
void OnCommandMoveStart ()
void OnCommandSwimFinish ()
void OnCommandSwimStart ()
void OnCommandUnconsciousFinish ()
void OnCommandUnconsciousStart ()
void OnCommandVehicleFinish ()
void OnCommandVehicleStart ()
void OnDeactivate ()
called when command ends
void OnFinish (bool pCanceled)
called ALWAYS! when action is finished (normal finish or cancel -> pCanceled)
void OnRollFinish ()
void OnRollStart (bool isToTheRight)
void OnSimulationEnd ()
void OnStanceChange (int previousStance, int newStance)
gets called on stance change
void OnStateChange (int pOldState, int pCurrentState)
called when enabled by EnableStateChangeCallback and state changes, call GetState() to get actual state
proto native void PhysicsGetVelocity (out vector pVelocity)
outs pVelocity - linear velocity of PHYSICS CONTROLLER
proto native bool PhysicsIsFalling (bool pValidate)
returns true if physics controller is falling
proto native bool PhysicsLanded ()
this is true when fall has physically landed - need to call Land after this is true
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
proto native void PostPhys_LockRotation ()
quaternion in world space
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
bool PostPhysUpdate (float pDt)
proto native void PreAnim_CallCommand (int pCommand, int pParamInt, float pParamFloat)
function usable in PreAnimUpdate or in !!! OnActivate !!!
proto native void PreAnim_SetBool (int pVar, bool pBool)
proto native void PreAnim_SetFilteredHeading (float pYawAngle, float pFilterDt, float pMaxYawSpeed)
sets character rotation (heading)
proto native void PreAnim_SetFloat (int pVar, float pFlt)
proto native void PreAnim_SetInt (int pVar, int pInt)
void PreAnimUpdate (float pDt)
proto native bool PrePhys_GetRotation (out float pOutRot[4])
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
proto native bool PrePhys_IsEvent (int pEvent)
script function usable in PrePhysUpdate
proto native bool PrePhys_IsTag (int pTag)
proto native void PrePhys_SetRotation (float pInRot[4])
proto native void PrePhys_SetTranslation (vector pInTransl)
void PrePhysUpdate (float pDt)
proto native void RegisterAnimationEvent (string pAnimationEventStr, int pId)
registers animation event, when event registered and received - it sends OnAnimationEvent with registered id
void RegisterDefaultEvents ()
proto native void RegisterEvent (string pName, int pId)
register events
proto native void ResetAligning ()
disables character aligning
proto native void SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
proto native void SetADS (bool pState)
sets head tilt to optics
proto native void SetAligning (vector pPositionWS, vector pDirectionWS)
enables character aligning to desired position and direction in world space
proto native void SetCurrentWaterLevel (float value)
sets water level (depth)
proto native void SetDirectionFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
proto native void SetDirectionSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
proto native void SetExhaustion (float pValue, bool pInterpolate)
sets exhaustion level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
proto native void SetFlagFinished (bool pFinished)
this terminates human command script and shows CommandHandler(... pCurrentCommandFinished == true);
proto native void SetInitState (int pFrameIndex)
proto native void SetInjured (float pValue, bool pInterpolate)
sets injury level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
proto native void SetMeleeBlock (bool pBlock)
this enables/disables block
proto native void SetRunSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
proto native void SetTalking (bool pValue)
sets talking
proto native void SetThrowingMode (bool pState)
proto native void SetTurnSpanModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
proto native void SetTurnSpanSprintModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
proto native bool StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
proto native HumanCommandActionCallback StartCommand_Action (int pActionID, typename pCallbackClass, int pStanceMask)
--— ACTIONS --—
proto native HumanCommandClimb StartCommand_Climb (SHumanCommandClimbResult pClimbResult, int pType)
--— CLIMB --—
proto native HumanCommandFullBodyDamage StartCommand_Damage (int pType, float pDirection)
--— FullBody Damages --—
proto native HumanCommandDeathCallback StartCommand_Death (int pType, float pDirection, typename pCallbackClass)
--— Death --—
proto native HumanCommandFall StartCommand_Fall (float pYVelocity)
--— FALL --—
proto native HumanCommandLadder StartCommand_Ladder (Building pBuilding, int pLadderIndex)
--— LADDER --—
proto native HumanCommandMelee StartCommand_Melee (EntityAI pTarget)
--— MELEE --—
proto native HumanCommandMelee2 StartCommand_Melee2 (EntityAI pTarget, int pHitType, float pComboValue, vector hitPos=vector.Zero)
starts command - melee2
proto native HumanCommandMove StartCommand_Move ()
returns current command ID
proto native HumanCommandScript StartCommand_Script (HumanCommandScript pHumanCommand)
— SCRIPTED COMMANDS
proto native HumanCommandScript StartCommand_ScriptInst (typename pCallbackClass)
proto native HumanCommandSwim StartCommand_Swim ()
--— LADDER --—
proto native HumanCommandUnconscious StartCommand_Unconscious (float pType)
starts command - unconscious
proto native HumanCommandVehicle StartCommand_Vehicle (Transport pTransport, int pTransportPositionIndex, int pVehicleSeat, bool fromUnconscious=false)
--— VEHICLE --—
proto native void StartMeleeEvade ()
marks command to continue to combo
proto native void StartMeleeEvadeA (float pDirAngle)
marks command to continue to combo, pDirAngle specifies angle
proto native void StartModifier (int pType)
starts modifier
proto static native void StaticSetInitState (Human pHuman, int pFrameIdx)
just static version of SetInitState
proto native void StopSwimming ()
proto native void ThrowItem (int throwType)
proto native void UnlinkFromLocalSpace ()
proto native void WakeUp (int targetStance=-1)
proto native bool WasHit ()
is true only once after hit event
proto native bool WasItemLeaveHandsEvent ()
proto static native vector WaterLevelCheck (Human pHuman, vector pPosition)
string WeaponActionTypeToString (int A, int AT)
private void ~HumanAnimInterface ()
private void ~HumanCommandActionCallback ()
private void ~HumanCommandAdditives ()
private void ~HumanCommandClimb ()
private void ~HumanCommandDamage ()
private void ~HumanCommandDeath ()
private void ~HumanCommandFall ()
private void ~HumanCommandFullBodyDamage ()
private void ~HumanCommandLadder ()
private void ~HumanCommandMelee ()
private void ~HumanCommandMelee2 ()
private void ~HumanCommandMove ()
private void ~HumanCommandSwim ()
private void ~HumanCommandUnconscious ()
private void ~HumanCommandWeapons ()
Variables
CommandActionAdditive = 8192
CommandActionFullbody = 4096
CommandClimb = 16
CommandDamageAdditive = 256
CommandDamageFullbody = 128
CommandDeath = 32
CommandFall = 8
CommandLadder = 512
CommandMelee = 2
CommandMelee2 = 4
CommandMove = 1
CommandSwim = 1024
CommandUnconscious = 64
CommandVehicle = 2048
static const int HIT_TYPE_FINISHER = 2
static const int HIT_TYPE_FINISHER_NECK = 3
static const int HIT_TYPE_HEAVY = 1
static const int HIT_TYPE_LIGHT = 0
enum WeaponActions HumanCommandFullBodyDamage
static const int LANDTYPE_HEAVY = 3
static const int LANDTYPE_LIGHT = 1
static const int LANDTYPE_MEDIUM = 2
static const int LANDTYPE_NONE = 0
bool m_bFinishWithFall
bool m_bHasParent
class HumanCommandVehicle m_bIsClimb
result from static test
bool m_bIsClimbOver
vector m_ClimbGrabPoint
vector m_ClimbGrabPointNormal
grab point for climb && climb over (in local space of it's parent)
vector m_ClimbOverStandPoint
where climb ends (in local space of it's parent)
IEntity m_ClimbOverStandPointParent
vector m_ClimbStandPoint
normal to grabpoint position (used for character orientation)
IEntity m_ClimbStandPointParent
parent of grabpoint
int m_CommandTypeId
float m_fClimbHeight
float m_fLeaning
current movement (0 idle, 1 walk, 2-run, 3-sprint), only if the command has a movement
IEntity m_GrabPointParent
where climb over ends (in local space of it's parent)
int m_iMovement
current stance (DayZPlayer.STANCEIDX_ERECT, ...), only if the command has a stance
int m_iStanceIdx
current command's id
int m_LocalMovement = -1
leaning state (not all commands need to have all movements)
enum WeaponActionReloadClipTypes MECHANISM_CLOSED = 1
enum WeaponActionReloadClipTypes MECHANISM_CLOSED_UNCOCKED = 3
enum WeaponActionReloadClipTypes MECHANISM_OPENED = 0
mechanism action types
enum WeaponActionReloadClipTypes MECHANISM_SPECIAL = 2
None = 0
static const int STATE_LOOP_ACTION = 6
static const int STATE_LOOP_END = 3
static const int STATE_LOOP_END2 = 4
static const int STATE_LOOP_IN = 1
looped state
static const int STATE_LOOP_LOOP = 2
static const int STATE_LOOP_LOOP2 = 5
static const int STATE_NONE = 0
undef state - not running anymore
static const int STATE_NORMAL = 7
one time state
class HumanInputController TAnimGraphCommand
Detailed Description
this file is interface to Human
Definition in file human.c.
Typedef Documentation
TAnimGraphEvent
typedef int TAnimGraphEvent
Definition at line 267 of file human.c.
TAnimGraphTag
typedef int TAnimGraphTag
Definition at line 266 of file human.c.
TAnimGraphVariable
typedef int TAnimGraphVariable
Definition at line 265 of file human.c.
Enumeration Type Documentation
ClimbStates
enum ClimbStates
state of climb command
Enumerator
STATE_MOVE
STATE_TAKEOFF
STATE_ONTOP
STATE_FALLING
STATE_FINISH
Definition at line 715 of file human.c.
{
    STATE_MOVE,
    STATE_TAKEOFF,
    STATE_ONTOP,
    STATE_FALLING,
    STATE_FINISH
};
HumanMoveCommandID
enum HumanMoveCommandID
do not process rotations !
used in script-side identification of animation commands on human (swim, fall, move...)
Definition at line 1196 of file human.c.
{
    None = 0,
    CommandMove = 1,
    CommandMelee = 2,
    CommandMelee2 = 4,
    CommandFall = 8,
    CommandClimb = 16,
    CommandDeath = 32,
    CommandUnconscious = 64,
    CommandDamageFullbody = 128,
    CommandDamageAdditive = 256,
    CommandLadder = 512,
    CommandSwim = 1024,
    CommandVehicle = 2048,
    CommandActionFullbody = 4096,
    CommandActionAdditive = 8192
}
WeaponActionChamberingLoaderTypes
enum WeaponActionChamberingLoaderTypes
Enumerator
CHAMBERINGLOADER_OPENED
CHAMBERINGLOADER_CLOSED
Definition at line 852 of file human.c.
{
    CHAMBERINGLOADER_OPENED     = 0,        // CMD_Reload_ChamberingFast - one bullet reload with open mechanism
    CHAMBERINGLOADER_CLOSED     = 1,        //  - one bullet reload with closed mechanism
};
WeaponActionChamberingTypes
enum WeaponActionChamberingTypes
Enumerator
CHAMBERING_END
CHAMBERING_ONEBULLET_OPENED
chambering action types
CHAMBERING_ONEBULLET_CLOSED
CHAMBERING_ONEBULLET_CLOSED_UNCOCKED
CHAMBERING_ONEBULLET_UNIQUE_OPENED
CHAMBERING_ONEBULLET_UNIQUE_CLOSED
CHAMBERING_TWOBULLETS_START
CHAMBERING_TWOBULLETS_END
CHAMBERING_STARTLOOPABLE_CLOSED
CHAMBERING_ENDLOOPABLE
CHAMBERING_STARTLOOPABLE_CLOSED_KEEP
CHAMBERING_STARTLOOPABLE_OPENED
CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED
CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED
CHAMBERING_DOUBLE_1
CHAMBERING_DOUBLE_2
CHAMBERING_DOUBLE_3
CHAMBERING_DOUBLE_4
CHAMBERING_CROSSBOW_OPENED
CHAMBERING_CROSSBOW_CLOSED
CHAMBERING_CROSSBOW_FULL
Definition at line 822 of file human.c.
{
    CHAMBERING_END = -1,
    CHAMBERING_ONEBULLET_OPENED                 = 0,        // CMD_Reload_Chambering
    CHAMBERING_ONEBULLET_CLOSED                 = 1,        //
    CHAMBERING_ONEBULLET_CLOSED_UNCOCKED        = 2,
    CHAMBERING_ONEBULLET_UNIQUE_OPENED          = 3,        //
    CHAMBERING_ONEBULLET_UNIQUE_CLOSED          = 4,        //
    CHAMBERING_TWOBULLETS_START                 = 6,        //  plays one bullet, then second, then ends, when CHAMBERING_TWOBULLETS_END arise, it's canceled
    CHAMBERING_TWOBULLETS_END                   = 7,        //  - one bullet reload with closed mechanism
    CHAMBERING_STARTLOOPABLE_CLOSED             = 10,       // start loop chambering
    CHAMBERING_ENDLOOPABLE                      = 11,       // end loop chambering
    CHAMBERING_STARTLOOPABLE_CLOSED_KEEP        = 12,       // start loop chambering and keep last bullet
    CHAMBERING_STARTLOOPABLE_OPENED             = 13,       //
    CHAMBERING_STARTLOOPABLE_SHOTGUN_UNCOCKED   = 15,
    CHAMBERING_STARTLOOPABLE_SHOTGUN_COCKED     = 16,
    CHAMBERING_DOUBLE_1             = 17,
    CHAMBERING_DOUBLE_2             = 18,
    CHAMBERING_DOUBLE_3             = 19,
    CHAMBERING_DOUBLE_4             = 20,
    CHAMBERING_CROSSBOW_OPENED          = 21,       // chambering crossbow
    CHAMBERING_CROSSBOW_CLOSED          = 22,       // chambering crossbow
    CHAMBERING_CROSSBOW_FULL            = 23,       // chambering crossbow
};
WeaponActionFireTypes
enum WeaponActionFireTypes
Enumerator
FIRE_NORMAL
FIRE_LAST
FIRE_COCKED
FIRE_UNCOCKED
FIRE_DRY
FIRE_JAM
Definition at line 866 of file human.c.
{
    FIRE_NORMAL                         = 0,
    FIRE_LAST                           = 1,
    FIRE_COCKED                         = 2,
    FIRE_UNCOCKED                       = 3,
    FIRE_DRY                            = 4,
    FIRE_JAM                            = 5
};
WeaponActionReloadClipTypes
enum WeaponActionReloadClipTypes
Enumerator
RELOADRIFLE_CLIP_NOBULLET
RELOADRIFLE_CLIP_BULLET
Definition at line 807 of file human.c.
{
    RELOADRIFLE_CLIP_NOBULLET           = 0,
    RELOADRIFLE_CLIP_BULLET             = 1,
}
WeaponActionReloadTypes
enum WeaponActionReloadTypes
action types reload action types
Enumerator
RELOADRIFLE_MAGAZINE_BULLET
reload action types - rifles
RELOADRIFLE_NOMAGAZINE_BULLET
RELOADRIFLE_MAGAZINE_NOBULLET
RELOADRIFLE_NOMAGAZINE_NOBULLET
RELOADRIFLE_MAGAZINE_NOBULLET_OPEN
RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN
RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED
RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED
RELOADPISTOL_MAGAZINE_BULLET_CLOSED
RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED
RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED
RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED
RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED
RELOADPISTOL_MAGAZINE_NOBULLET_OPENED
RELOAD_MAGAZINE_DETACH
RELOADRIFLE_MAGAZINE_DETACH
RELOADSRIFLE_MAGAZINE_BULLET
RELOADSRIFLE_NOMAGAZINE_BULLET
RELOADSRIFLE_MAGAZINE_NOBULLET
RELOADSRIFLE_NOMAGAZINE_NOBULLET
Definition at line 778 of file human.c.
{
    RELOADRIFLE_MAGAZINE_BULLET             = 0,        // CMD_Reload_Magazine
    RELOADRIFLE_NOMAGAZINE_BULLET           = 1,
    RELOADRIFLE_MAGAZINE_NOBULLET           = 2,
    RELOADRIFLE_NOMAGAZINE_NOBULLET         = 3,
    RELOADRIFLE_MAGAZINE_NOBULLET_OPEN      = 4,
    RELOADRIFLE_NOMAGAZINE_NOBULLET_OPEN    = 5,
    // reload action types - pistols
    RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_UNCOCKED    = 8, // CMD_Reload_Magazine
    RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_UNCOCKED      = 9,
    RELOADPISTOL_MAGAZINE_BULLET_CLOSED                 = 10,
    RELOADPISTOL_NOMAGAZINE_BULLET_CLOSED               = 11,
    RELOADPISTOL_MAGAZINE_NOBULLET_CLOSED_COCKED        = 12,
    RELOADPISTOL_NOMAGAZINE_NOBULLET_CLOSED_COCKED      = 13,
    RELOADPISTOL_NOMAGAZINE_NOBULLET_OPENED             = 14,
    RELOADPISTOL_MAGAZINE_NOBULLET_OPENED               = 15,
    RELOAD_MAGAZINE_DETACH  = 16,
    RELOADRIFLE_MAGAZINE_DETACH = 17,                    // CMD_Reload_Magazine
    RELOADSRIFLE_MAGAZINE_BULLET        = 20,           // CMD_Reload_Magazine
    RELOADSRIFLE_NOMAGAZINE_BULLET      = 21,
    RELOADSRIFLE_MAGAZINE_NOBULLET      = 22,
    RELOADSRIFLE_NOMAGAZINE_NOBULLET    = 23,
};
WeaponActions
enum WeaponActions
actions
Enumerator
INTERRUPT
NONE
RELOAD
MECHANISM
CHAMBERING
CHAMBERING_LOADER
UNJAMMING
FIRE
HIDE
SHOW
RELOAD_CLIP
Definition at line 762 of file human.c.
{
    INTERRUPT           = 15,
    NONE                = -1,
    RELOAD              = 0,
    MECHANISM           = 1,
    CHAMBERING          = 2,
    CHAMBERING_LOADER   = 3,
    UNJAMMING           = 4,
    FIRE                = 5,
    HIDE                = 6,
    SHOW                = 7,
    RELOAD_CLIP         = 8,
};
WeaponActionUnjammingTypes
enum WeaponActionUnjammingTypes
Enumerator
UNJAMMING_START
unjam action types
UNJAMMING_END
UNJAMMING_INTERRUPT
Definition at line 858 of file human.c.
{
    UNJAMMING_START                     = 1,        // CMD_Weapon_Jam - 0
    UNJAMMING_END                       = 0,        // 1
    UNJAMMING_INTERRUPT                 = -1,
};
WeaponEvents
enum WeaponEvents
events
Enumerator
ATTACHMENT_HIDE
ATTACHMENT_SHOW
BULLET_EJECT
BULLET_HIDE
BULLET_HIDE2
BULLET_IN_CHAMBER
BULLET_IN_MAGAZINE
BULLET_SHOW
BULLET_SHOW2
CANUNJAM_END
CANUNJAM_START
COCKED
MAGAZINE_ATTACHED
MAGAZINE_DETACHED
MAGAZINE_HIDE
MAGAZINE_SHOW
SLIDER_OPEN
UNJAMMED
HAMMER_UNCOCKED
CHANGE_HIDE
CHANGE_SHOW
CYLINDER_ROTATE
Definition at line 909 of file human.c.
{
    ATTACHMENT_HIDE,
    ATTACHMENT_SHOW,
    BULLET_EJECT,
    BULLET_HIDE,
    BULLET_HIDE2,
    BULLET_IN_CHAMBER,
    BULLET_IN_MAGAZINE,
    BULLET_SHOW,
    BULLET_SHOW2,
    CANUNJAM_END,
    CANUNJAM_START,
    COCKED,
    MAGAZINE_ATTACHED,
    MAGAZINE_DETACHED,
    MAGAZINE_HIDE,
    MAGAZINE_SHOW,
    SLIDER_OPEN,
    UNJAMMED,
    HAMMER_UNCOCKED,
    HAMMER_COCKED
    CHANGE_HIDE,
    CHANGE_SHOW,
    CYLINDER_ROTATE,
};
WeaponHideShowTypes
enum WeaponHideShowTypes
Enumerator
HIDESHOW_SLOT_2HDLEFTBACK
HIDESHOW_SLOT_RFLLEFTBACK
HIDESHOW_SLOT_1HDLEFTBACK
HIDESHOW_SLOT_2HDRIGHTBACK
HIDESHOW_SLOT_RFLRIGHTBACK
HIDESHOW_SLOT_1HDRIGHTBACK
HIDESHOW_SLOT_PISTOLBELT
HIDESHOW_SLOT_PISTOLCHEST
HIDESHOW_SLOT_KNIFEBACK
HIDESHOW_SLOT_INVENTORY
Definition at line 876 of file human.c.
{
    HIDESHOW_SLOT_2HDLEFTBACK = 0,
    HIDESHOW_SLOT_RFLLEFTBACK = 1,
    HIDESHOW_SLOT_1HDLEFTBACK = 2,
    HIDESHOW_SLOT_2HDRIGHTBACK = 3,
    HIDESHOW_SLOT_RFLRIGHTBACK = 4,
    HIDESHOW_SLOT_1HDRIGHTBACK = 5,
    HIDESHOW_SLOT_PISTOLBELT = 6,
    HIDESHOW_SLOT_PISTOLCHEST = 7,
    HIDESHOW_SLOT_KNIFEBACK = 8,
    HIDESHOW_SLOT_INVENTORY = 9,
};
Function Documentation
AddCommandModifier_Action()
proto native HumanCommandActionCallback AddCommandModifier_Action (int pActionID, typename pCallbackClass)
adds action command modifier, creates callback instance for you
Referenced by CommandHandler().
AddCommandModifier_Damage()
proto native HumanCommandDamage AddCommandModifier_Damage (int pType, float pDirection)
— modifier for light Damages
starts additive damage
Referenced by CommandHandlerDebug(), and HandleDamageHit().
BindCommand()
proto native TAnimGraphCommand HumanCommandActionCallback::BindCommand (string pCommandName)
returns command index -
BindEvent()
proto native TAnimGraphEvent HumanCommandActionCallback::BindEvent (string pEventName)
BindTag()
proto native TAnimGraphTag HumanCommandActionCallback::BindTag (string pTagName)
BindVariableBool()
proto native TAnimGraphVariable HumanCommandActionCallback::BindVariableBool (string pVariable)
BindVariableFloat()
proto native TAnimGraphVariable HumanCommandActionCallback::BindVariableFloat (string pVariable)
BindVariableInt()
proto native TAnimGraphVariable HumanCommandActionCallback::BindVariableInt (string pVariable)
Cancel()
proto native void Cancel ()
cancels action
cancels command melee and goes to HumanCommandMove
Referenced by CABase::Interrupt().
CancelModifier()
proto native void CancelModifier ()
cancels modifier
CanChangeStance()
bool CanChangeStance (int previousStance, int newStance)
Called by code to see if it can.
CanExit()
proto native bool HumanCommandSwim::CanExit ()
returns true if on exiting point
CanRoll()
bool CanRoll ()
ContinueCombo() [1/2]
proto native void ContinueCombo ()
marks command to continue to combo
ContinueCombo() [2/2]
proto native void HumanCommandFall::ContinueCombo (bool pHeavyHit, float pComboValue, EntityAI target = null, vector hitPos = vector.Zero)
marks command to continue to combo
DebugDrawClimb()
proto static native bool HumanCommandFullBodyDamage::DebugDrawClimb (Human pHuman, int pLevel) static
debug draws climb heauristics int pLevel = 1 result, 2 - capsules (3 - all)
DebugDrawLadder()
proto static native bool HumanCommandSwim::DebugDrawLadder (Building pBuilding, int pLadderIndex) static
debug draws any ladder
DebugGetItemAnimInstance()
proto native owned string DebugGetItemAnimInstance ()
returns current item's animation instance
DebugGetItemClass()
proto native owned string DebugGetItemClass ()
returns current item's class name
DebugGetItemSuperClass()
proto native owned string DebugGetItemSuperClass ()
returns current item's class that is found in config
DebugGetLadderIndex()
proto static native int HumanCommandSwim::DebugGetLadderIndex (string pComponentName) static
DebugIsEvent()
proto native int HumanCommandAdditives::DebugIsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
DebugResetEvents()
proto native void HumanCommandAdditives::DebugResetEvents ()
DefaultCancelCondition()
proto native bool DefaultCancelCondition ()
system implemented cancel condition (now raise or sprint cancels action)
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), and HumanCommandActionCallback::CancelCondition().
DeleteCommandModifier_Action()
proto native void DeleteCommandModifier_Action (HumanCommandActionCallback pCallback)
force remove - normally if action is ended or interrupted - this is not needed to call
DeleteCommandModifier_Damage()
proto native void DeleteCommandModifier_Damage (HumanCommandDamage pDamage)
DoClimbTest()
proto static native bool HumanCommandFullBodyDamage::DoClimbTest (Human pHuman, SHumanCommandClimbResult pResult, int pDebugDrawLevel) static
debug draws climb heauristics pDebugDrawLevel viz DebugDrawClimb
EnableCancelCondition()
proto native void EnableCancelCondition (bool pEnable)
enables calling cancel condition default is disabled when enabled - there must be a function "bool CancelCondition()" implemented
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), HumanCommandActionCallback::Init(), ActionContinuousBaseCB::InitActionComponent(), and ActionInteractLoopBaseCB::InitActionComponent().
EnableStateChangeCallback()
proto native void EnableStateChangeCallback ()
enables state change callback OnStateChange
Referenced by ActionUnfoldMapCB::ActionUnfoldMapCB(), CreateActionComponent(), ActionReadPaperCB::CreateActionComponent(), and ActionWritePaperCB::CreateActionComponent().
Exit()
proto native void HumanCommandSwim::Exit ()
ForceStance()
proto native void HumanCommandMelee::ForceStance (int pStanceIdx)
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH,STANCEIDX_PRONE,STANCEIDX_RAISEDERECT,STANCEIDX_RAISEDCROUCH,STANCEIDX_RAISEDPRONE, or -1 when release the stance lock
ForceStanceUp()
proto native void HumanCommandMelee::ForceStanceUp (int pStanceIdx)
pStanceIds is one of STANCEIDX_ERECT,STANCEIDX_CROUCH this forces to stand up to required stance
GetAnimInterface()
proto native HumanAnimInterface GetAnimInterface ()
returns animation interface - usable in HumanCommandScript implementations
GetBaseAimingAngleLR()
proto native float HumanCommandAdditives::GetBaseAimingAngleLR ()
returns base aiming angle LR - without sway/offsets/...
GetBaseAimingAngleUD()
proto native float HumanCommandAdditives::GetBaseAimingAngleUD ()
returns base aiming angle UD - without sway/offsets/...
GetBoneIndexByName()
proto native int GetBoneIndexByName (string pBoneName)
returns bone index for a name (-1 if pBoneName doesn't exist)
Referenced by DayZInfected::GetCenter(), ManBase::GetCenter(), ManBase::SetDecayEffects(), and ManBase::SpawnBreathVaporEffect().
GetBonePositionLS()
proto native vector GetBonePositionLS (int pBoneIndex)
returns local space, model space, world space position of the bone
GetBonePositionMS()
proto native vector GetBonePositionMS (int pBoneIndex)
GetBonePositionWS()
proto native vector GetBonePositionWS (int pBoneIndex)
Referenced by DayZInfected::GetCenter(), and ManBase::GetCenter().
GetBoneRotationLS()
proto native void GetBoneRotationLS (int pBoneIndex, out float pQuat[4])
returns local space, model space, world space orientation (quaternion) of a bone
GetBoneRotationMS()
proto native void GetBoneRotationMS (int pBoneIndex, out float pQuat[4])
GetBoneRotationWS()
proto native void GetBoneRotationWS (int pBoneIndex, out float pQuat[4])
GetBoneTransformLS()
proto native void GetBoneTransformLS (int pBoneIndex, out vector pTm[4])
returns local space, model space, world space orientation (quaternion) of a bone
GetBoneTransformMS()
proto native void GetBoneTransformMS (int pBoneIndex, out vector pTm[4])
GetBoneTransformWS()
proto native void GetBoneTransformWS (int pBoneIndex, out vector pTm[4])
GetClimbOverStandPointWS()
proto native vector HumanCommandFullBodyDamage::GetClimbOverStandPointWS ()
returns world space position of landspot after climbing over
GetComboCount()
proto native int HumanCommandFall::GetComboCount ()
GetCommand_Action()
proto native HumanCommandActionCallback GetCommand_Action ()
is human is in command action - returns its callback, if current command is action
Referenced by ManBase::BrokenLegForceProne().
GetCommand_Climb()
proto native HumanCommandClimb GetCommand_Climb ()
GetCommand_Damage()
proto native HumanCommandFullBodyDamage GetCommand_Damage ()
GetCommand_Death()
proto native HumanCommandDeathCallback GetCommand_Death ()
GetCommand_Fall()
proto native HumanCommandFall GetCommand_Fall ()
Referenced by CommandHandler().
GetCommand_Ladder()
proto native HumanCommandLadder GetCommand_Ladder ()
Referenced by ProcessSoundEvent().
GetCommand_Melee()
proto native HumanCommandMelee GetCommand_Melee ()
Referenced by ManBase::OnQuickBarContinuousUseStart(), and ManBase::OnQuickBarSingleUse().
GetCommand_Melee2()
proto native HumanCommandMelee2 GetCommand_Melee2 ()
Referenced by AimingModel(), EEHitBy(), and HandleADS().
GetCommand_Move()
proto native HumanCommandMove GetCommand_Move ()
Referenced by ManBase::BrokenLegForceProne(), ManBase::CanRoll(), CommandHandler(), ManBase::ContaminatedParticleAdjustment(), ManBase::EEItemIntoHands(), DayZInfected::EOnInit(), ForceStandUpForHeavyItems(), DayZInfected::HandleMindStateChange(), HeadingModel(), and ManBase::IsRolling().
GetCommand_Script()
proto native HumanCommandScript GetCommand_Script ()
is human is in command action - returns its callback, if current command is action
GetCommand_Swim()
proto native HumanCommandSwim GetCommand_Swim ()
GetCommand_Unconscious()
proto native HumanCommandUnconscious GetCommand_Unconscious ()
Referenced by ManBase::CommandHandler(), and GetTypeOfDeath().
GetCommand_Vehicle()
proto native HumanCommandVehicle GetCommand_Vehicle ()
Referenced by CameraHandler(), CommandHandler(), ManBase::CommandHandler(), HandleDamageHit(), HandleDeath(), IsInventoryVisible(), and ManBase::OnCommandVehicleStart().
GetCommandModifier_Action()
proto native HumanCommandActionCallback GetCommandModifier_Action ()
returns callback for action if any is active, null if nothing runs
GetCommandModifier_Additives()
proto native HumanCommandAdditives GetCommandModifier_Additives ()
default (always-on modifiers)
returns modifier for additives / small behaviours on human
Referenced by CommandHandler(), CommandHandlerDebug(), and ManBase::ProcessADDModifier().
GetCommandModifier_Damage()
proto native HumanCommandDamage GetCommandModifier_Damage ()
GetCommandModifier_Weapons()
proto native HumanCommandWeapons GetCommandModifier_Weapons ()
returns interface for handling weapons
Referenced by CommandHandler(), CommandHandlerDebug(), ExitSights(), HandleADS(), HandleWeapons(), ManBase::ProcessLiftWeapon(), ManBase::SendLiftWeaponSync(), SetIronsights(), and SetOptics().
GetCommandModifierCount()
proto native int GetCommandModifierCount ()
GetCommandModifierID()
proto native int GetCommandModifierID (int pIndex)
returns COMMANDID_ .. type id of command modifier on index pIndex
GetCurrentHitType()
proto native int HumanCommandFall::GetCurrentHitType ()
Definition at line 68 of file dayzplayermeleefightlogic_lightheavy.c.
    {
        return m_HitType;
    }
References m_HitType.
GetCurrentInputAngle()
proto bool HumanCommandMelee::GetCurrentInputAngle (out float pAngle)
direction held on keyboard/controller -180 -90 0 90 180 angles of input movement (no filtering, no postprocesses) return false in idle states
GetCurrentMovementAngle()
proto native float HumanCommandMelee::GetCurrentMovementAngle ()
marks command to continue to combo -180 -90 0 90 180 angles of current movement
GetCurrentMovementSpeed()
proto native float HumanCommandMelee::GetCurrentMovementSpeed ()
0,1,2..3 idle, walk, run, sprint
GetGrabPointWS()
proto native vector HumanCommandFullBodyDamage::GetGrabPointWS ()
returns world space position of climbing grab point
GetHuman()
proto native Human GetHuman ()
get the human this cb belongs to
Referenced by GearChangeActionCallback::OnFinish().
GetInputController()
proto native HumanInputController GetInputController ()
returns human input controller
Referenced by DayZCreatureAI::CommandHandler(), CommandHandler(), DayZInfected::CommandHandler(), ManBase::CommandHandler(), HandleADS(), DayZInfected::HandleMove(), and HandleView().
GetItemAccessor()
proto native HumanItemAccessor GetItemAccessor ()
Referenced by CanClimb(), CanJump(), HandleADS(), HandleDeath(), HeadingModel(), OnItemInHandsChanged(), ManBase::RefreshHandAnimationState(), and ManBase::TryHideItemInHands().
GetMovementState()
proto native void GetMovementState (HumanMovementState pState)
returns movement state (current command id,)
Referenced by AimingModel(), CameraHandler(), CommandHandler(), EvaluateDamageHitAnimation(), HandleADS(), HandleWeapons(), HeadingModel(), IsPlayerInStance(), and OnStepEvent().
GetRunningAction()
proto native int HumanCommandAdditives::GetRunningAction ()
returns -1 when no action is running or RELOAD,MECHANISM, ....
Referenced by ManBase::CanBeRestrained(), ManBase::HeadingModel(), and ManBase::OnQuickBarSingleUse().
GetRunningActionType()
proto native int HumanCommandAdditives::GetRunningActionType ()
returns -1 when no action is running or appropriate action type
GetState()
proto native int GetState ()
returns one of STATE_...
returns the state of climb (enum value of ClimbStates);
Definition at line 29 of file staminahandler.c.
{ return m_State; }
References m_State, and Inventory_Base::m_State.
Referenced by ItemBase::CanAttach(), ItemBase::CanBeManipulated(), ItemBase::CanBePacked(), ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), CanDisplayAttachmentSlot(), FireworksLauncher::CanPutInCargo(), FireworksLauncher::CanPutIntoHands(), CanReceiveAttachment(), ItemBase::EEHealthLevelChanged(), GetStateString(), ItemBase::GetViewIndex(), ItemBase::HandleOpeningsPhysics(), FireworksLauncher::IsIgnited(), IsTakeable(), FireworksLauncher::OnPlacementComplete(), RefreshState(), ItemBase::UpdatePhysics(), UpdateProxySelections(), and ItemBase::UpdateVisuals().
GetStateString() [1/2]
string GetStateString ()
returns debug string of current state
Definition at line 380 of file human.c.
    {
        return GetStateString(GetState());
    }
References GetState(), and GetStateString().
Referenced by GetStateString(), and HumanCommandActionCallback::OnStateChange().
GetStateString() [2/2]
static string GetStateString (int pState) static
returns debug string of current state
one time state
Definition at line 358 of file human.c.
    {
        switch (pState)
        {
        case STATE_NONE:            return "NONE";
        case STATE_LOOP_IN:         return "LOOP_IN";
        case STATE_LOOP_LOOP:       return "LOOP_LOOP";
        case STATE_LOOP_END:        return "LOOP_END";
        case STATE_LOOP_END2:       return "LOOP_END2";
        case STATE_LOOP_LOOP2:      return "LOOP_LOOP2";
        case STATE_LOOP_ACTION:     return "LOOP_ACTION";
        case STATE_NORMAL:          return "ONE TIME";
        }
        return "Undef";
    }
References STATE_LOOP_ACTION, STATE_LOOP_END, STATE_LOOP_END2, STATE_LOOP_IN, STATE_LOOP_LOOP, STATE_LOOP_LOOP2, STATE_NONE, and STATE_NORMAL.
GetTransformWS()
enum HumanMoveCommandID GetTransformWS (out vector pTm[4])
gets human transform in World Space
HumanAnimInterface()
private void HumanCommandActionCallback::HumanAnimInterface ()
HumanCommandActionCallback()
class HumanAnimInterface HumanCommandActionCallback ()
HumanCommandAdditives()
class HumanCommandWeapons HumanCommandAdditives ()
Definition at line 890 of file human.c.
{}
References A.
Referenced by ApplyExhaustion(), CommandHandler(), CommandHandlerDebug(), WeaponStateBase::OnEntry(), Play(), ManBase::ProcessADDModifier(), Update(), SmptAnimMetaADD::Update(), and PlayerPreview::UpdateInterval().
HumanCommandClimb()
private void HumanCommandFullBodyDamage::HumanCommandClimb ()
Definition at line 757 of file human.c.
{}
HumanCommandDamage()
class HumanCommandUnconscious HumanCommandDamage ()
Definition at line 594 of file human.c.
{}
HumanCommandDeath()
class HumanCommandDeathCallback HumanCommandDeath ()
Definition at line 574 of file human.c.
{}
Referenced by IsFinisher().
HumanCommandFall()
class HumanCommandMelee2 HumanCommandFall ()
Definition at line 514 of file human.c.
{}
Referenced by CommandHandler(), ManBase::OnJumpEnd(), and SetTurnSpanModifier().
HumanCommandLadder()
private void HumanCommandSwim::HumanCommandLadder ()
Definition at line 650 of file human.c.
{}
HumanCommandMelee()
class HumanCommandMove HumanCommandMelee ()
Definition at line 411 of file human.c.
{}
HumanCommandMelee2()
private void HumanCommandFall::HumanCommandMelee2 ()
Definition at line 560 of file human.c.
{}
HumanCommandMove()
private void HumanCommandMelee::HumanCommandMove ()
Definition at line 499 of file human.c.
{}
HumanCommandSwim()
class HumanCommandLadder HumanCommandSwim ()
Definition at line 618 of file human.c.
{}
Referenced by Environment::CheckWaterContact(), DayZPlayerUtils::CheckWaterLevel(), EmoteBase::EmoteCondition(), DayZPlayerImplementSwimming::GetCharacterDepth(), DayZPlayerImplementSwimming::GetWaterDepth(), DayZPlayerImplementSwimming::HandleSwimming(), and ActionFillBottleBase::SetupStance().
HumanCommandUnconscious()
private void HumanCommandDamage::HumanCommandUnconscious ()
Definition at line 618 of file human.c.
{}
HumanCommandWeapons()
private void HumanCommandAdditives::HumanCommandWeapons ()
Definition at line 1054 of file human.c.
{}
InternalCommand()
proto native void InternalCommand (int pInternalCommandId)
calls internal command pInternalCommandId is one of CMD_ACTIONINT_ ...
Referenced by ActionBaseCB::SetCommand().
IsActionFinished()
proto native bool HumanCommandAdditives::IsActionFinished ()
IsEvent()
proto native int HumanCommandAdditives::IsEvent ()
return -1 when there is no event, otherwise it returns pId of event from animation
IsFinisher()
proto native bool HumanCommandFall::IsFinisher ()
References HumanCommandDeath().
IsGestureCallback()
bool IsGestureCallback ()
Definition at line 406 of file human.c.
    {
        return false;
    }
IsInComboRange()
proto native bool IsInComboRange ()
returns true if hit is in range, where person can continue to combo
IsInProne()
bool OnActivate::IsInProne ()
Definition at line 1155 of file human.c.
{
IsInRaisedProne()
bool OnActivate::IsInRaisedProne ()
Definition at line 1161 of file human.c.
{
IsInRoll()
proto native bool HumanCommandMelee::IsInRoll ()
return true if character barrel rolling
IsInWater()
proto native bool HumanCommandDamage::IsInWater ()
Referenced by ManBase::BrokenLegForceProne().
IsInWeaponReloadBulletSwitchState()
proto native bool HumanCommandAdditives::IsInWeaponReloadBulletSwitchState ()
returns true when clip visual change is needed for reload clip action
IsLanding()
proto native bool IsLanding ()
returns true if fall is in landing state
IsLeaning()
bool OnActivate::IsLeaning ()
Definition at line 1167 of file human.c.
{
IsLeavingUncon()
proto native bool HumanCommandMelee::IsLeavingUncon ()
return true if character transitions out of uncon
Referenced by HeadingModel().
IsMeleeEvade()
proto native bool HumanCommandMelee::IsMeleeEvade ()
this is true when in melee evade
IsModifierActive()
proto native bool IsModifierActive ()
is modifier active
Referenced by ManBase::EEHitBy(), and ManBase::SaveAreaPersistenceFlag().
IsOnBack()
proto native bool IsOnBack ()
return true if prone is on back
is on back in prone stance?
IsOnLand()
proto native bool HumanCommandDamage::IsOnLand ()
IsRaised()
bool OnActivate::IsRaised ()
Definition at line 1143 of file human.c.
{
Referenced by ManBase::CanBeRestrained(), CanClimb(), CanJump(), ManBase::CanSprint(), ManBase::EEItemIntoHands(), HandleADS(), HandleView(), ManBase::IsMapCallbackCancelInput(), ManBase::OnQuickBarContinuousUseStart(), and ManBase::OnQuickBarSingleUse().
IsRaisedInProne()
bool OnActivate::IsRaisedInProne ()
Definition at line 1149 of file human.c.
{
IsStandingFromBack()
proto native bool HumanCommandMelee::IsStandingFromBack ()
return true if prone on back is chaning to crounch/stand
IsSymptomCallback()
bool IsSymptomCallback ()
Definition at line 411 of file human.c.
    {
        return false;
    }
IsThrowingMode()
proto native bool HumanCommandAdditives::IsThrowingMode ()
IsUserActionCallback()
bool IsUserActionCallback ()
Definition at line 401 of file human.c.
    {
        return false;
    }
Land()
proto native void Land (int pLandType)
end fall with land
LiftWeapon()
proto native void HumanCommandAdditives::LiftWeapon (bool pState)
command for lifting weapon near obstacled (works only when weapon is raised)
LinkToLocalSpaceOf()
proto native void LinkToLocalSpaceOf (notnull IEntity child, vector pLocalSpaceMatrix[4])
OnActivate()
class HumanMovementState OnActivate ()
HumanCommandScript fully scriptable command.
Warning
NON-MANAGED, will be managed by C++ once it is sent to the CommandHandler through Human.StartCommand_Script
Note
So ideally, it is best to set up the HumanCommandScript, not create any instances and start it through Human.StartCommand_ScriptInst In case an instance needs to be created, it needs manual deletion if not sent to the CommandHandler But deleting it while it is in the CommandHandler will cause crashes constructor must have 1st parameter to be Human virtual to be overridden called when command starts
Definition at line 1072 of file human.c.
{ };
Referenced by Activate(), AntibioticsMdfr::OnReconnect(), CharcoalMdfr::OnReconnect(), FatigueMdfr::OnReconnect(), FeverMdfr::OnReconnect(), HemolyticReactionMdfr::OnReconnect(), PoisoningMdfr::OnReconnect(), WetMdfr::OnReconnect(), DisinfectionMdfr::OnReconnect(), DrowningMdfr::OnReconnect(), EpinephrineMdfr::OnReconnect(), FliesMdfr::OnReconnect(), ImmunityBoost::OnReconnect(), MaskMdfr::OnReconnect(), MorphineMdfr::OnReconnect(), PainKillersMdfr::OnReconnect(), and SalineMdfr::OnReconnect().
OnAnimationEvent()
void OnAnimationEvent (int pEventID)
calls animation event -> must be registered with RegisterAnimationEvent
Definition at line 391 of file human.c.
{};
OnCommandActionAdditiveFinish()
void OnCommandActionAdditiveFinish ()
OnCommandActionAdditiveStart()
void OnCommandActionAdditiveStart ()
OnCommandActionFullbodyFinish()
void OnCommandActionFullbodyFinish ()
OnCommandActionFullbodyStart()
void OnCommandActionFullbodyStart ()
OnCommandClimbFinish()
void OnCommandClimbFinish ()
OnCommandClimbStart()
void OnCommandClimbStart ()
OnCommandDamageAdditiveFinish()
void OnCommandDamageAdditiveFinish ()
OnCommandDamageAdditiveStart()
void OnCommandDamageAdditiveStart ()
OnCommandDamageFullbodyFinish()
void OnCommandDamageFullbodyFinish ()
OnCommandDamageFullbodyStart()
void OnCommandDamageFullbodyStart ()
OnCommandDeathFinish()
void OnCommandDeathFinish ()
OnCommandDeathStart()
void OnCommandDeathStart ()
OnCommandFallFinish()
void OnCommandFallFinish ()
OnCommandFallStart()
void OnCommandFallStart ()
OnCommandLadderFinish()
void OnCommandLadderFinish ()
OnCommandLadderStart()
void OnCommandLadderStart ()
OnCommandMelee2Finish()
void OnCommandMelee2Finish ()
OnCommandMelee2Start()
void OnCommandMelee2Start ()
OnCommandMeleeFinish()
void OnCommandMeleeFinish ()
OnCommandMeleeStart()
void OnCommandMeleeStart ()
OnCommandMoveFinish()
void OnCommandMoveFinish ()
OnCommandMoveStart()
void OnCommandMoveStart ()
OnCommandSwimFinish()
void OnCommandSwimFinish ()
OnCommandSwimStart()
void OnCommandSwimStart ()
OnCommandUnconsciousFinish()
void OnCommandUnconsciousFinish ()
OnCommandUnconsciousStart()
void OnCommandUnconsciousStart ()
OnCommandVehicleFinish()
void OnCommandVehicleFinish ()
OnCommandVehicleStart()
void OnCommandVehicleStart ()
OnDeactivate()
void OnDeactivate ()
called when command ends
Definition at line 1137 of file human.c.
{ };
Referenced by Deactivate().
OnFinish()
void OnFinish (bool pCanceled)
called ALWAYS! when action is finished (normal finish or cancel -> pCanceled)
Definition at line 394 of file human.c.
{};
OnRollFinish()
void OnRollFinish ()
OnRollStart()
void OnRollStart (bool isToTheRight)
OnSimulationEnd()
void HumanCommandDeath::OnSimulationEnd ()
Definition at line 597 of file human.c.
{
OnStanceChange()
void OnStanceChange (int previousStance, int newStance)
gets called on stance change
OnStateChange()
void OnStateChange (int pOldState, int pCurrentState)
called when enabled by EnableStateChangeCallback and state changes, call GetState() to get actual state
Definition at line 397 of file human.c.
{};
PhysicsGetVelocity()
proto native void PhysicsGetVelocity (out vector pVelocity)
outs pVelocity - linear velocity of PHYSICS CONTROLLER
Referenced by ManBase::BrokenLegWalkShock().
PhysicsIsFalling()
proto native bool PhysicsIsFalling (bool pValidate)
returns true if physics controller is falling
Referenced by CommandHandler().
PhysicsLanded()
proto native bool PhysicsLanded ()
this is true when fall has physically landed - need to call Land after this is true
PostPhys_GetPosition()
proto native void PostPhys_GetPosition (out vector pOutTransl)
script function usable in PostPhysUpdate
PostPhys_GetRotation()
proto native void PostPhys_GetRotation (out float pOutRot[4])
vec3 in world space
PostPhys_LockRotation()
proto native void PostPhys_LockRotation ()
quaternion in world space
PostPhys_SetPosition()
proto native void PostPhys_SetPosition (vector pInTransl)
quaternion in world space
PostPhys_SetRotation()
proto native void PostPhys_SetRotation (float pInRot[4])
vec3 in world space
PostPhysUpdate()
bool PostPhysUpdate (float pDt)
override this ! final adjustment of physics state (after physics was applied) returns true if command continues running / false if command should end (or you can use SetFlagFinished(true))
PreAnim_CallCommand()
proto native void PreAnim_CallCommand (int pCommand, int pParamInt, float pParamFloat)
function usable in PreAnimUpdate or in !!! OnActivate !!!
PreAnim_SetBool()
proto native void PreAnim_SetBool (int pVar, bool pBool)
PreAnim_SetFilteredHeading()
proto native void PreAnim_SetFilteredHeading (float pYawAngle, float pFilterDt, float pMaxYawSpeed)
sets character rotation (heading)
PreAnim_SetFloat()
proto native void PreAnim_SetFloat (int pVar, float pFlt)
PreAnim_SetInt()
proto native void PreAnim_SetInt (int pVar, int pInt)
PreAnimUpdate()
void PreAnimUpdate (float pDt)
override this ! called before any animation is processed here change animation values, add animation commands
PrePhys_GetRotation()
proto native bool PrePhys_GetRotation (out float pOutRot[4])
PrePhys_GetTranslation()
proto native bool PrePhys_GetTranslation (out vector pOutTransl)
PrePhys_IsEvent()
proto native bool PrePhys_IsEvent (int pEvent)
script function usable in PrePhysUpdate
PrePhys_IsTag()
proto native bool PrePhys_IsTag (int pTag)
PrePhys_SetRotation()
proto native void PrePhys_SetRotation (float pInRot[4])
PrePhys_SetTranslation()
proto native void PrePhys_SetTranslation (vector pInTransl)
PrePhysUpdate()
void PrePhysUpdate (float pDt)
override this ! after animation is processed, before physics is processed
RegisterAnimationEvent()
proto native void RegisterAnimationEvent (string pAnimationEventStr, int pId)
registers animation event, when event registered and received - it sends OnAnimationEvent with registered id
RegisterDefaultEvents()
void HumanCommandAdditives::RegisterDefaultEvents ()
Definition at line 1088 of file human.c.
    {
        return m_iStanceIdx >= DayZPlayerConstants.STANCEIDX_RAISEDERECT;
    }
    bool        IsRaisedInProne()
    {
        return m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE;
    }
    bool        IsInProne()
    {
        return m_iStanceIdx == DayZPlayerConstants.STANCEIDX_PRONE;
    }
    bool        IsInRaisedProne()
    {
        return m_iStanceIdx == DayZPlayerConstants.STANCEIDX_RAISEDPRONE;
    }
    bool        IsLeaning()
RegisterEvent()
proto native void HumanCommandAdditives::RegisterEvent (string pName, int pId)
register events
ResetAligning()
proto native void ResetAligning ()
disables character aligning
SetActionProgressParams()
proto native void HumanCommandAdditives::SetActionProgressParams (float pStart, float pEnd)
sets start and end animation position - f.e. for reload clip action
SetADS()
proto native void HumanCommandAdditives::SetADS (bool pState)
sets head tilt to optics
SetAligning()
proto native void SetAligning (vector pPositionWS, vector pDirectionWS)
enables character aligning to desired position and direction in world space
SetCurrentWaterLevel()
proto native void HumanCommandMelee::SetCurrentWaterLevel (float value)
sets water level (depth)
SetDirectionFilterModifier()
proto native void HumanCommandMelee::SetDirectionFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterTimeout
SetDirectionSprintFilterModifier()
proto native void HumanCommandMelee::SetDirectionSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fDirFilterSprintTimeout
SetExhaustion()
proto native void SetExhaustion (float pValue, bool pInterpolate)
sets exhaustion level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
SetFlagFinished()
proto native void SetFlagFinished (bool pFinished)
this terminates human command script and shows CommandHandler(... pCurrentCommandFinished == true);
SetInitState()
proto native void HumanCommandAdditives::SetInitState (int pFrameIndex)
this sets to a weapon init state each weapon has a different weapon state those states are defined by animation set by AddItemInHandsProfileIK - in DayZPlayerCfgBase.c each frame of animation is one init state
SetInjured()
proto native void SetInjured (float pValue, bool pInterpolate)
sets injury level 0..1, interpolate == false -> resets the value, otherwise it's interpolating towards the new value
SetMeleeBlock()
proto native void HumanCommandMelee::SetMeleeBlock (bool pBlock)
this enables/disables block
SetRunSprintFilterModifier()
proto native void HumanCommandMelee::SetRunSprintFilterModifier (float value)
sets the multiplier for SHumanCommandMoveSettings::m_fRunSpringTimeout
SetTalking()
proto native void SetTalking (bool pValue)
sets talking
SetThrowingMode()
proto native void HumanCommandAdditives::SetThrowingMode (bool pState)
SetTurnSpanModifier()
proto native void HumanCommandMelee::SetTurnSpanModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingFilterSpan
References HumanCommandFall().
SetTurnSpanSprintModifier()
proto native void HumanCommandMelee::SetTurnSpanSprintModifier (float value)
sets the multiplier for HumanItemBehaviorCfg::m_fMoveHeadingSprintFilterSpan
StartAction()
proto native bool HumanCommandAdditives::StartAction (WeaponActions pAction, int pActionType)
start reload,mechanism,chambering,unjam ...
StartCommand_Action()
proto native HumanCommandActionCallback StartCommand_Action (int pActionID, typename pCallbackClass , int pStanceMask)
--— ACTIONS --—
starts command - Action pStanceMask is mix of flags STANCEMASK_ERECT, ...
StartCommand_Climb()
proto native HumanCommandClimb StartCommand_Climb (SHumanCommandClimbResult pClimbResult, int pType)
--— CLIMB --—
starts command - climb
StartCommand_Damage()
proto native HumanCommandFullBodyDamage StartCommand_Damage (int pType, float pDirection)
--— FullBody Damages --—
starts fullbody damage
Referenced by ManBase::CommandHandler(), CommandHandlerDebug(), and HandleDamageHit().
StartCommand_Death()
proto native HumanCommandDeathCallback StartCommand_Death (int pType, float pDirection, typename pCallbackClass)
--— Death --—
starts command - death
Referenced by DayZCreatureAI::HandleDeath(), DayZInfected::HandleDeath(), and HandleDeath().
StartCommand_Fall()
proto native HumanCommandFall StartCommand_Fall (float pYVelocity)
--— FALL --—
starts command - fall pYVelocity <= 0 -> fall pYVelocity > 0 -> jump
Referenced by CommandHandler().
StartCommand_Ladder()
proto native HumanCommandLadder StartCommand_Ladder (Building pBuilding, int pLadderIndex)
--— LADDER --—
starts command - fall
StartCommand_Melee()
proto native HumanCommandMelee StartCommand_Melee (EntityAI pTarget)
--— MELEE --—
starts command - melee
StartCommand_Melee2()
proto native HumanCommandMelee2 StartCommand_Melee2 (EntityAI pTarget, int pHitType, float pComboValue, vector hitPos = vector.Zero)
starts command - melee2
StartCommand_Move()
proto native HumanCommandMove StartCommand_Move ()
returns current command ID
--— MOVE --— starts command - Move
Referenced by ManBase::BrokenLegForceProne(), DayZCreatureAI::CommandHandler(), CommandHandler(), DayZInfected::CommandHandler(), and OverrideSlidePoseAngle().
StartCommand_Script()
proto native HumanCommandScript StartCommand_Script (HumanCommandScript pHumanCommand)
— SCRIPTED COMMANDS
starts command - Action pStanceMask is mix of flags STANCEMASK_ERECT, ...
StartCommand_ScriptInst()
proto native HumanCommandScript StartCommand_ScriptInst (typename pCallbackClass)
StartCommand_Swim()
proto native HumanCommandSwim StartCommand_Swim ()
--— LADDER --—
starts command - Swim
Referenced by CommandHandler().
StartCommand_Unconscious()
proto native HumanCommandUnconscious StartCommand_Unconscious (float pType)
starts command - unconscious
Referenced by ManBase::CommandHandler().
StartCommand_Vehicle()
proto native HumanCommandVehicle StartCommand_Vehicle (Transport pTransport, int pTransportPositionIndex, int pVehicleSeat, bool fromUnconscious = false)
--— VEHICLE --—
starts command - vehicle
Referenced by CommandHandler().
StartMeleeEvade()
proto native void HumanCommandMelee::StartMeleeEvade ()
marks command to continue to combo
StartMeleeEvadeA()
proto native void HumanCommandMelee::StartMeleeEvadeA (float pDirAngle)
marks command to continue to combo, pDirAngle specifies angle
StartModifier()
proto native void StartModifier (int pType)
starts modifier
StaticSetInitState()
proto static native void HumanCommandAdditives::StaticSetInitState (Human pHuman, int pFrameIdx) static
just static version of SetInitState
StopSwimming()
proto native void StopSwimming ()
ThrowItem()
proto native void HumanCommandAdditives::ThrowItem (int throwType)
UnlinkFromLocalSpace()
proto native void UnlinkFromLocalSpace ()
Referenced by HandleDeath().
WakeUp()
proto native void HumanCommandDamage::WakeUp (int targetStance = -1)
WasHit()
proto native bool WasHit ()
is true only once after hit event
WasItemLeaveHandsEvent()
proto native bool HumanCommandAdditives::WasItemLeaveHandsEvent ()
WaterLevelCheck()
proto static native vector WaterLevelCheck (Human pHuman, vector pPosition) static
returns water level from entity position returns in format (totalWaterDepth, characterDepht, 0)
WeaponActionTypeToString()
string WeaponActionTypeToString (int A, int AT)
Definition at line 890 of file human.c.
{
    switch (A)
    {
        case WeaponActions.INTERRUPT: return "Weapon interrupt";
        case WeaponActions.NONE: return "---";
        case WeaponActions.RELOAD: return typename.EnumToString(WeaponActionReloadTypes, AT);
        case WeaponActions.MECHANISM: return typename.EnumToString(WeaponActionMechanismTypes, AT);
        case WeaponActions.CHAMBERING: return typename.EnumToString(WeaponActionChamberingTypes, AT);
        case WeaponActions.CHAMBERING_LOADER: return typename.EnumToString(WeaponActionChamberingLoaderTypes, AT);
        case WeaponActions.UNJAMMING: return typename.EnumToString(WeaponActionUnjammingTypes, AT);
        case WeaponActions.FIRE: return typename.EnumToString(WeaponActionFireTypes, AT);
        case WeaponActions.HIDE: return typename.EnumToString(WeaponHideShowTypes, AT);
        case WeaponActions.SHOW: return typename.EnumToString(WeaponHideShowTypes, AT);
    }
    return "---";
}
Referenced by HandleInventory(), HandleWeaponEvents(), HandStateBase::OnEntry(), and WeaponStateBase::OnEntry().
~HumanAnimInterface()
private void HumanCommandActionCallback::~HumanAnimInterface ()
~HumanCommandActionCallback()
private void ~HumanCommandActionCallback ()
~HumanCommandAdditives()
private void ~HumanCommandAdditives ()
Definition at line 1054 of file human.c.
{}
~HumanCommandClimb()
private void HumanCommandFullBodyDamage::~HumanCommandClimb ()
Definition at line 758 of file human.c.
{
~HumanCommandDamage()
private void ~HumanCommandDamage ()
Definition at line 618 of file human.c.
{}
~HumanCommandDeath()
private void ~HumanCommandDeath ()
Definition at line 594 of file human.c.
{}
~HumanCommandFall()
private void ~HumanCommandFall ()
Definition at line 560 of file human.c.
{}
~HumanCommandFullBodyDamage()
private void ~HumanCommandFullBodyDamage ()
Definition at line 757 of file human.c.
{}
~HumanCommandLadder()
private void HumanCommandSwim::~HumanCommandLadder ()
Definition at line 651 of file human.c.
{
~HumanCommandMelee()
private void ~HumanCommandMelee ()
Definition at line 499 of file human.c.
{}
~HumanCommandMelee2()
private void HumanCommandFall::~HumanCommandMelee2 ()
Definition at line 561 of file human.c.
{
~HumanCommandMove()
private void HumanCommandMelee::~HumanCommandMove ()
Definition at line 500 of file human.c.
{
~HumanCommandSwim()
private void ~HumanCommandSwim ()
Definition at line 650 of file human.c.
{}
~HumanCommandUnconscious()
private void HumanCommandDamage::~HumanCommandUnconscious ()
Definition at line 619 of file human.c.
{
~HumanCommandWeapons()
private void HumanCommandAdditives::~HumanCommandWeapons ()
Definition at line 1055 of file human.c.
{
Variable Documentation
CommandActionAdditive
CommandActionAdditive = 8192
Definition at line 14 of file human.c.
CommandActionFullbody
CommandActionFullbody = 4096
Definition at line 13 of file human.c.
CommandClimb
CommandClimb = 16
Definition at line 5 of file human.c.
CommandDamageAdditive
CommandDamageAdditive = 256
Definition at line 9 of file human.c.
CommandDamageFullbody
CommandDamageFullbody = 128
Definition at line 8 of file human.c.
CommandDeath
CommandDeath = 32
Definition at line 6 of file human.c.
CommandFall
CommandFall = 8
Definition at line 4 of file human.c.
CommandLadder
CommandLadder = 512
Definition at line 10 of file human.c.
CommandMelee
CommandMelee = 2
Definition at line 2 of file human.c.
CommandMelee2
CommandMelee2 = 4
Definition at line 3 of file human.c.
CommandMove
CommandMove = 1
Definition at line 1 of file human.c.
CommandSwim
CommandSwim = 1024
Definition at line 11 of file human.c.
CommandUnconscious
CommandUnconscious = 64
Definition at line 7 of file human.c.
CommandVehicle
CommandVehicle = 2048
Definition at line 12 of file human.c.
HIT_TYPE_FINISHER
const int HIT_TYPE_FINISHER = 2 static
Definition at line 565 of file human.c.
HIT_TYPE_FINISHER_NECK
const int HIT_TYPE_FINISHER_NECK = 3 static
Definition at line 566 of file human.c.
HIT_TYPE_HEAVY
const int HIT_TYPE_HEAVY = 1 static
Definition at line 564 of file human.c.
HIT_TYPE_LIGHT
const int HIT_TYPE_LIGHT = 0 static
Definition at line 563 of file human.c.
HumanCommandFullBodyDamage
class HumanCommandClimb HumanCommandFullBodyDamage
Definition at line 710 of file human.c.
{}
LANDTYPE_HEAVY
const int LANDTYPE_HEAVY = 3 static
Definition at line 565 of file human.c.
LANDTYPE_LIGHT
const int LANDTYPE_LIGHT = 1 static
Definition at line 563 of file human.c.
LANDTYPE_MEDIUM
const int LANDTYPE_MEDIUM = 2 static
Definition at line 564 of file human.c.
LANDTYPE_NONE
const int LANDTYPE_NONE = 0 static
Definition at line 562 of file human.c.
m_bFinishWithFall
bool m_bFinishWithFall
Definition at line 698 of file human.c.
m_bHasParent
bool m_bHasParent
Definition at line 699 of file human.c.
m_bIsClimb
class HumanCommandVehicle m_bIsClimb
result from static test
m_bIsClimbOver
bool m_bIsClimbOver
Definition at line 697 of file human.c.
m_ClimbGrabPoint
vector m_ClimbGrabPoint
Definition at line 703 of file human.c.
m_ClimbGrabPointNormal
vector m_ClimbGrabPointNormal
grab point for climb && climb over (in local space of it's parent)
Definition at line 704 of file human.c.
m_ClimbOverStandPoint
vector m_ClimbOverStandPoint
where climb ends (in local space of it's parent)
Definition at line 706 of file human.c.
m_ClimbOverStandPointParent
IEntity m_ClimbOverStandPointParent
Definition at line 710 of file human.c.
m_ClimbStandPoint
vector m_ClimbStandPoint
normal to grabpoint position (used for character orientation)
Definition at line 705 of file human.c.
m_ClimbStandPointParent
IEntity m_ClimbStandPointParent
parent of grabpoint
Definition at line 709 of file human.c.
m_CommandTypeId
int m_CommandTypeId
Definition at line 1135 of file human.c.
m_fClimbHeight
float m_fClimbHeight
Definition at line 701 of file human.c.
m_fLeaning
float m_fLeaning
current movement (0 idle, 1 walk, 2-run, 3-sprint), only if the command has a movement
Definition at line 1138 of file human.c.
m_GrabPointParent
IEntity m_GrabPointParent
where climb over ends (in local space of it's parent)
Definition at line 708 of file human.c.
m_iMovement
int m_iMovement
current stance (DayZPlayer.STANCEIDX_ERECT, ...), only if the command has a stance
Definition at line 1137 of file human.c.
m_iStanceIdx
int m_iStanceIdx
current command's id
Definition at line 1136 of file human.c.
m_LocalMovement
int m_LocalMovement = -1
leaning state (not all commands need to have all movements)
Definition at line 1140 of file human.c.
MECHANISM_CLOSED
enum WeaponActionReloadClipTypes MECHANISM_CLOSED = 1
MECHANISM_CLOSED_UNCOCKED
enum WeaponActionReloadClipTypes MECHANISM_CLOSED_UNCOCKED = 3
MECHANISM_OPENED
enum WeaponActionReloadClipTypes MECHANISM_OPENED = 0
mechanism action types
MECHANISM_SPECIAL
enum WeaponActionReloadClipTypes MECHANISM_SPECIAL = 2
None
@ None = 0
Definition at line 0 of file human.c.
STATE_LOOP_ACTION
const int STATE_LOOP_ACTION = 6 static
Definition at line 345 of file human.c.
Referenced by GetStateString().
STATE_LOOP_END
const int STATE_LOOP_END = 3 static
Definition at line 342 of file human.c.
Referenced by GetStateString(), and OnStateChange().
STATE_LOOP_END2
const int STATE_LOOP_END2 = 4 static
Definition at line 343 of file human.c.
Referenced by GetStateString(), and OnStateChange().
STATE_LOOP_IN
const int STATE_LOOP_IN = 1 static
looped state
Definition at line 340 of file human.c.
Referenced by GetStateString(), and ActionUnfoldMapCB::OnStateChange().
STATE_LOOP_LOOP
const int STATE_LOOP_LOOP = 2 static
Definition at line 341 of file human.c.
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), GetStateString(), ActionRaiseAndViewCB::OnStateChange(), ActionReadPaperCB::OnStateChange(), ActionUnfoldMapCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
STATE_LOOP_LOOP2
const int STATE_LOOP_LOOP2 = 5 static
Definition at line 344 of file human.c.
Referenced by ActionContinuousBaseCB::CancelCondition(), ActionInteractLoopBaseCB::CancelCondition(), and GetStateString().
STATE_NONE
const int STATE_NONE = 0 static
undef state - not running anymore
example of implement of CancelCondition returns true it it should CANCEL the action
Definition at line 337 of file human.c.
Referenced by GetStateString(), OnStateChange(), ActionReadPaperCB::OnStateChange(), and ActionWritePaperCB::OnStateChange().
STATE_NORMAL
const int STATE_NORMAL = 7 static
one time state
Definition at line 348 of file human.c.
Referenced by GetStateString().
TAnimGraphCommand
class HumanInputController TAnimGraphCommand