DayzKode: P:/scripts/3_game/DayZ/humansettings.c File Reference
humansettings.c File Reference
Classes
class SHumanCommandSwimSettings
class SHumanGlobalSettings
Functions
class SHumanCommandSwimSettings SHumanCommandClimbSettings ()
class SHumanGlobalSettings SHumanCommandMoveSettings ()
private void SHumanCommandSwimSettings ()
private void SHumanGlobalSettings ()
private void ~SHumanCommandClimbSettings ()
private void ~SHumanCommandMoveSettings ()
private void ~SHumanCommandSwimSettings ()
private void ~SHumanGlobalSettings ()
Variables
float m_fAlignFastMaxChanged
float m_fAlignFastTimeout
float m_fAlignIdleMaxChanged
align filters in idle, slow, fast
float m_fAlignIdleTimeout
float m_fAlignSlowMaxChanged
float m_fAlignSlowTimeout
float m_fCharHeight
generic settings
float m_fCharWidth
forward pass
float m_fClimbOverMaxWidth
float m_fClimbOverMinHeight
float m_fDirFilterSpeed
direction filter max rot speed [rad/s]
float m_fDirFilterSprintTimeout
sprint direction filter timeout [s]
float m_fDirFilterTimeout
direction filter timeout [s]
float m_fFwMaxDistance
float m_fFwMaxHeight
float m_fFwMinHeight
float m_fHeadingChangeLimiterIdle
float m_fHeadingChangeLimiterRun
float m_fHeadingChangeLimiterWalk
float m_fLeaningSpeed
float m_fMaxSprintAngle
max sprint angle [rad]
float m_fMovementSpeed
float m_fMovementSpeedFltMaxChange
float m_fMovementSpeedFltTime
float m_fPhysMoveMaxTracedDistance
when actual phys step is lower than this -> distance is traced, otherwise it's just set
float m_fRunSpringMaxChange
filter speed value [val/s]
float m_fRunSpringTimeout
filter span value [s]
float m_fSlidingPoseAngle
angle (0.707 * PI) - when angle is bigger - sliding pose is done (rad)
float m_fSlidingPoseRepTime
not to do sliding pose after another sliding pose (sec)
float m_fSlidingPoseTrackTime
time change of angle is tracked in the past (sec)
float m_fStepDownRadius
float m_fStepFreeSpace
forward step
float m_fStepMinNormal
float m_fStepMinWidth
float m_fStepPositionAfterEdge
must be a space to step there
float m_fStepVariation
float m_fToCrouchLevel
when to crouch
float m_fToErectLevel
when to stand
float m_fTurnAngle
when character starts to turn (45 deg default)
float m_fTurnEndUpdateNTime
when turn values are not updated anymore (normalized time)
float m_fTurnNextNTime
when next turn is started from previous turn
float m_fWaterLevelIn
when entering water - what level cases swimming (1.5m)
float m_fWaterLevelOut
what water level causes to stop swimming (1.2m)
float m_fWaterLevelSpeedRectrictionHigh
Water level (in meters) - m_iMaxSpeedNormal_WaterLevelHigh and m_iMaxSpeedFast_WaterLevelHigh are applied when character is deeper.
float m_fWaterLevelSpeedRectrictionLow
Water level (in meters) - m_iMaxSpeedNormal_WaterLevelLow and m_iMaxSpeedFast_WaterLevelLow are applied when character is deeper.
float m_fWaterLevelSwim
when swimming - entity position depth (1.4 m)
int m_iMaxSpeedFast_WaterLevelHigh
Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
int m_iMaxSpeedFast_WaterLevelLow
Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
int m_iMaxSpeedNormal_WaterLevelHigh
Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
int m_iMaxSpeedNormal_WaterLevelLow
Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
Function Documentation
SHumanCommandClimbSettings()
class SHumanCommandSwimSettings SHumanCommandClimbSettings ()
Definition at line 42 of file humansettings.c.
{}
Referenced by CommandHandler(), and DayZPlayerImplementJumpClimb::JumpOrClimb().
SHumanCommandMoveSettings()
class SHumanGlobalSettings SHumanCommandMoveSettings ()
Definition at line 1 of file humansettings.c.
{}
Referenced by DayZPlayerTypeUtils::DayZPlayerTypeInitMovement().
SHumanCommandSwimSettings()
private void SHumanCommandClimbSettings::SHumanCommandSwimSettings ()
Definition at line 75 of file humansettings.c.
{}
SHumanGlobalSettings()
private void SHumanCommandMoveSettings::SHumanGlobalSettings ()
Definition at line 13 of file humansettings.c.
{}
~SHumanCommandClimbSettings()
private void ~SHumanCommandClimbSettings ()
Definition at line 75 of file humansettings.c.
{}
~SHumanCommandMoveSettings()
private void ~SHumanCommandMoveSettings ()
Definition at line 13 of file humansettings.c.
{}
~SHumanCommandSwimSettings()
private void SHumanCommandClimbSettings::~SHumanCommandSwimSettings ()
Definition at line 76 of file humansettings.c.
~SHumanGlobalSettings()
private void SHumanCommandMoveSettings::~SHumanGlobalSettings ()
Definition at line 14 of file humansettings.c.
{
Variable Documentation
m_fAlignFastMaxChanged
float m_fAlignFastMaxChanged
Definition at line 83 of file humansettings.c.
m_fAlignFastTimeout
float m_fAlignFastTimeout
Definition at line 82 of file humansettings.c.
m_fAlignIdleMaxChanged
float m_fAlignIdleMaxChanged
align filters in idle, slow, fast
Definition at line 79 of file humansettings.c.
m_fAlignIdleTimeout
float m_fAlignIdleTimeout
Definition at line 78 of file humansettings.c.
m_fAlignSlowMaxChanged
float m_fAlignSlowMaxChanged
Definition at line 81 of file humansettings.c.
m_fAlignSlowTimeout
float m_fAlignSlowTimeout
Definition at line 80 of file humansettings.c.
m_fCharHeight
float m_fCharHeight
generic settings
Definition at line 78 of file humansettings.c.
m_fCharWidth
float m_fCharWidth
forward pass
Definition at line 81 of file humansettings.c.
m_fClimbOverMaxWidth
float m_fClimbOverMaxWidth
Definition at line 95 of file humansettings.c.
m_fClimbOverMinHeight
float m_fClimbOverMinHeight
Definition at line 96 of file humansettings.c.
m_fDirFilterSpeed
float m_fDirFilterSpeed
direction filter max rot speed [rad/s]
Definition at line 19 of file humansettings.c.
m_fDirFilterSprintTimeout
float m_fDirFilterSprintTimeout
sprint direction filter timeout [s]
Definition at line 18 of file humansettings.c.
m_fDirFilterTimeout
float m_fDirFilterTimeout
direction filter timeout [s]
Definition at line 17 of file humansettings.c.
m_fFwMaxDistance
float m_fFwMaxDistance
Definition at line 85 of file humansettings.c.
m_fFwMaxHeight
float m_fFwMaxHeight
Definition at line 84 of file humansettings.c.
m_fFwMinHeight
float m_fFwMinHeight
Definition at line 83 of file humansettings.c.
m_fHeadingChangeLimiterIdle
float m_fHeadingChangeLimiterIdle
Definition at line 30 of file humansettings.c.
m_fHeadingChangeLimiterRun
float m_fHeadingChangeLimiterRun
Definition at line 32 of file humansettings.c.
m_fHeadingChangeLimiterWalk
float m_fHeadingChangeLimiterWalk
Definition at line 31 of file humansettings.c.
m_fLeaningSpeed
float m_fLeaningSpeed
Definition at line 34 of file humansettings.c.
m_fMaxSprintAngle
float m_fMaxSprintAngle
max sprint angle [rad]
Definition at line 20 of file humansettings.c.
m_fMovementSpeed
float m_fMovementSpeed
Definition at line 85 of file humansettings.c.
m_fMovementSpeedFltMaxChange
float m_fMovementSpeedFltMaxChange
Definition at line 87 of file humansettings.c.
m_fMovementSpeedFltTime
float m_fMovementSpeedFltTime
Definition at line 86 of file humansettings.c.
m_fPhysMoveMaxTracedDistance
float m_fPhysMoveMaxTracedDistance
when actual phys step is lower than this -> distance is traced, otherwise it's just set
Definition at line 16 of file humansettings.c.
m_fRunSpringMaxChange
float m_fRunSpringMaxChange
filter speed value [val/s]
Definition at line 16 of file humansettings.c.
m_fRunSpringTimeout
float m_fRunSpringTimeout
filter span value [s]
Definition at line 15 of file humansettings.c.
m_fSlidingPoseAngle
float m_fSlidingPoseAngle
angle (0.707 * PI) - when angle is bigger - sliding pose is done (rad)
Definition at line 26 of file humansettings.c.
m_fSlidingPoseRepTime
float m_fSlidingPoseRepTime
not to do sliding pose after another sliding pose (sec)
Definition at line 28 of file humansettings.c.
m_fSlidingPoseTrackTime
float m_fSlidingPoseTrackTime
time change of angle is tracked in the past (sec)
Definition at line 27 of file humansettings.c.
m_fStepDownRadius
float m_fStepDownRadius
Definition at line 90 of file humansettings.c.
m_fStepFreeSpace
float m_fStepFreeSpace
forward step
Definition at line 88 of file humansettings.c.
m_fStepMinNormal
float m_fStepMinNormal
Definition at line 91 of file humansettings.c.
m_fStepMinWidth
float m_fStepMinWidth
Definition at line 93 of file humansettings.c.
m_fStepPositionAfterEdge
float m_fStepPositionAfterEdge
must be a space to step there
Definition at line 89 of file humansettings.c.
m_fStepVariation
float m_fStepVariation
Definition at line 92 of file humansettings.c.
m_fToCrouchLevel
float m_fToCrouchLevel
when to crouch
Definition at line 94 of file humansettings.c.
m_fToErectLevel
float m_fToErectLevel
when to stand
Definition at line 95 of file humansettings.c.
m_fTurnAngle
float m_fTurnAngle
when character starts to turn (45 deg default)
Definition at line 22 of file humansettings.c.
m_fTurnEndUpdateNTime
float m_fTurnEndUpdateNTime
when turn values are not updated anymore (normalized time)
Definition at line 23 of file humansettings.c.
m_fTurnNextNTime
float m_fTurnNextNTime
when next turn is started from previous turn
Definition at line 24 of file humansettings.c.
m_fWaterLevelIn
float m_fWaterLevelIn
when entering water - what level cases swimming (1.5m)
Definition at line 90 of file humansettings.c.
m_fWaterLevelOut
float m_fWaterLevelOut
what water level causes to stop swimming (1.2m)
Definition at line 91 of file humansettings.c.
m_fWaterLevelSpeedRectrictionHigh
float m_fWaterLevelSpeedRectrictionHigh
Water level (in meters) - m_iMaxSpeedNormal_WaterLevelHigh and m_iMaxSpeedFast_WaterLevelHigh are applied when character is deeper.
Definition at line 37 of file humansettings.c.
m_fWaterLevelSpeedRectrictionLow
float m_fWaterLevelSpeedRectrictionLow
Water level (in meters) - m_iMaxSpeedNormal_WaterLevelLow and m_iMaxSpeedFast_WaterLevelLow are applied when character is deeper.
Definition at line 36 of file humansettings.c.
m_fWaterLevelSwim
float m_fWaterLevelSwim
when swimming - entity position depth (1.4 m)
Definition at line 89 of file humansettings.c.
m_iMaxSpeedFast_WaterLevelHigh
int m_iMaxSpeedFast_WaterLevelHigh
Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character wants to sprint (-1 means no change)
Definition at line 42 of file humansettings.c.
m_iMaxSpeedFast_WaterLevelLow
int m_iMaxSpeedFast_WaterLevelLow
Max movement speed for m_fWaterLevelSpeedRectrictionLow when character wants to sprint (-1 means no change)
Definition at line 40 of file humansettings.c.
m_iMaxSpeedNormal_WaterLevelHigh
int m_iMaxSpeedNormal_WaterLevelHigh
Max movement speed for m_fWaterLevelSpeedRectrictionHigh when character doesn't want to sprint (-1 means no change)
Definition at line 41 of file humansettings.c.
m_iMaxSpeedNormal_WaterLevelLow
int m_iMaxSpeedNormal_WaterLevelLow
Max movement speed for m_fWaterLevelSpeedRectrictionLow when character doesn't want to sprint (-1 means no change)
Definition at line 39 of file humansettings.c.