DayzKode: P:/scripts/4_world/DayZ/classes/soundhandlers/hungersoundhandler.c File Reference
hungersoundhandler.c File Reference
Classes
class HungerSoundHandlerBase
class SoundHandlerBase
Functions
void PlaySound ()
void ProcessSound ()
override void Update ()
Variables
EffectSound m_Sound
float m_SoundTime
const float SOUND_INTERVALS_LIGHT_MAX = 30
class HungerSoundHandlerBase extends SoundHandlerBase SOUND_INTERVALS_LIGHT_MIN = 10
Function Documentation
PlaySound()
void PlaySound ()
Definition at line 38 of file hungersoundhandler.c.
    {
        m_Sound = SEffectManager.PlaySoundOnObject("hungry_uni_Voice_Char_SoundSet", m_Player);
        if( m_Sound )
        {
            m_Sound.SetAutodestroy(true);
        }
        else
        {
            Debug.LogError("Missing sounset");
        }
    }
References Debug::LogError(), m_Player, m_Sound, SEffectManager::PlaySoundOnObject(), and EffectSound::SetAutodestroy().
Referenced by SymptomBase::OnGetActivatedServer(), OnStepEvent(), EntityAI::PlayImpactSound(), ProcessAttachmentEvent(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), DayZCreature::ProcessSoundEvent(), ProcessSoundEvent(), DayZCreature::ProcessSoundVoiceEvent(), DayZInfected::ProcessSoundVoiceEvent(), DayZCreature::ProcessStepEvent(), ProcessVoiceEvent(), DayZInfected::ProcessVoiceFX(), ProcessWeaponEvent(), ItemBase::SoundCollision(), BarbedWireTrigger::SoundCollision(), ItemBase::SoundCut(), ItemBase::SoundElectricShock(), BarbedWireTrigger::SoundElectricShock(), and ItemBase::SoundSpark().
ProcessSound()
void ProcessSound ()
Definition at line 28 of file hungersoundhandler.c.
    {
        if ( GetGame().GetTime() > m_SoundTime)
        {
            float offset_time = Math.RandomFloatInclusive(SOUND_INTERVALS_LIGHT_MIN, SOUND_INTERVALS_LIGHT_MAX) * 1000;
            m_SoundTime = GetGame().GetTime() + offset_time;
            PlaySound();
        }
    }
References GetGame(), GetTime(), CGame::GetTime(), m_SoundTime, PlaySound(), Math::RandomFloatInclusive(), SOUND_INTERVALS_LIGHT_MAX, and SOUND_INTERVALS_LIGHT_MIN.
Referenced by Tick(), Update(), and InjurySoundHandlerBase::Update().
Variable Documentation
m_Sound
EffectSound m_Sound
Definition at line 18 of file hungersoundhandler.c.
Referenced by ActionActivateTrap::ActionActivateTrap(), ActionArmExplosive::ActionArmExplosive(), ActionBase(), ActionCraft::ActionCraft(), ActionDeployHuntingTrap::ActionDeployHuntingTrap(), ActionTakeABite::ActionTakeABite(), PlayActionSound(), PlaySound(), ItemBase::SoundBuildStart(), ItemBase::SoundDestroyStart(), ItemBase::SoundDismantleStart(), SoundLockChangeDial(), SoundLockChangeNumber(), SoundLockClose(), SoundLockOpen(), PASBroadcaster::SoundTurnOff(), and PASBroadcaster::SoundTurnOn().
m_SoundTime
float m_SoundTime
Definition at line 17 of file hungersoundhandler.c.
Referenced by ProcessSound(), and InjurySoundHandlerBase::ProcessSound().
SOUND_INTERVALS_LIGHT_MAX
const float SOUND_INTERVALS_LIGHT_MAX = 30
Definition at line 16 of file hungersoundhandler.c.
Referenced by ProcessSound(), and InjurySoundHandlerBase::ProcessSound().
SOUND_INTERVALS_LIGHT_MIN
class HungerSoundHandlerBase extends SoundHandlerBase SOUND_INTERVALS_LIGHT_MIN = 10
Referenced by ProcessSound(), and InjurySoundHandlerBase::ProcessSound().