DayzKode: P:/scripts/3_game/DayZ/impacteffects.c File Reference
impacteffects.c File Reference
Enumerations
enum ImpactTypes { MELEE }
Variables
static ref map< string, int > m_IgnoredAmmo
Map of ammo which will not spawn any impact effect.
enum ImpactTypes m_ImpactEffect
static int m_LastRegisteredIgnoredAmmo = 0
static int m_LastRegisteredMaterial = 0
enum ImpactTypes string
Surface effects
Register all hit materials here! When modding, these can be unregistered with 'UnregisterSurface' if so desired
static int CONCRETE = RegisterSurface("Hit_Concrete")
static int DIRT = RegisterSurface("Hit_Dirt")
static int ERROR_NO_MATERIAL = RegisterSurface("Hit_ErrorNoMaterial")
static int FOLIAGE = RegisterSurface("Hit_Foliage")
static int GLASS = RegisterSurface("Hit_Glass")
static int GLASS_THIN = RegisterSurface("Hit_Glass_Thin")
static int GRASS = RegisterSurface("Hit_Grass")
static int GRAVEL = RegisterSurface("Hit_Gravel")
static int MEATBONES = RegisterSurface("Hit_MeatBones")
static int MEATBONES_FIST = RegisterSurface("Hit_MeatBones_MeleeFist")
static int MEATBONES_PIPEWRENCH = RegisterSurface("Hit_MeatBones_MeleePipeWrench")
static int MEATBONES_SHOVEL = RegisterSurface("Hit_MeatBones_MeleeShovel")
static int MEATBONES_WRENCH = RegisterSurface("Hit_MeatBones_MeleeWrench")
static int METAL = RegisterSurface("Hit_Metal")
static int PLASTER = RegisterSurface("Hit_Plaster")
static int PLASTIC = RegisterSurface("Hit_Plastic")
static int RUBBER = RegisterSurface("Hit_Rubber")
static int SAND = RegisterSurface("Hit_Sand")
static int TEXTILE = RegisterSurface("Hit_Textile")
static int UNDEFINED = RegisterSurface("Hit_Undefined")
static int WATER = RegisterSurface("Hit_Water")
static int WOOD = RegisterSurface("Hit_Wood")
Ignored ammo
Register ammo which will not spawn impact effects here When modding, these can be unregistered with 'UnregisterIgnoredAmmo' if so desired
static void EvaluateImpactEffect (Object directHit, int componentIndex, string surface, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool deflected, string ammoType, bool isWater)
static int FIST = RegisterIgnoredAmmo("MeleeFist")
static int FIST_HEAVY = RegisterIgnoredAmmo("MeleeFist_Heavy")
static GetImpactEffect (string surface, string ammoType)
static int RegisterIgnoredAmmo (string ammo)
static int RegisterSurface (string surface)
static int SOFT = RegisterIgnoredAmmo("MeleeSoft")
static int SOFT_HEAVY = RegisterIgnoredAmmo("MeleeSoft_Heavy")
static bool UnregisterIgnoredAmmo (string ammo)
static bool UnregisterSurface (string surface)
Enumeration Type Documentation
ImpactTypes
enum ImpactTypes
Enumerator
MELEE
Definition at line 1 of file impacteffects.c.
{
    UNKNOWN;
    STOP;
    PENETRATE;
    RICOCHET;
    MELEE;
}
Function Documentation
EvaluateImpactEffect()
static void EvaluateImpactEffect (Object directHit, int componentIndex, string surface, vector pos, int impact_type, vector surfNormal, vector exitPos, vector inSpeed, vector outSpeed, bool deflected, string ammoType, bool isWater) static
Definition at line 115 of file impacteffects.c.
    {
        // No impact effects wanted for this ammo
        if (m_IgnoredAmmo.Contains(ammoType))
            return;
        if (impact_type == ImpactTypes.UNKNOWN)
            impact_type = ImpactTypes.STOP;
        if (deflected)
            impact_type = ImpactTypes.RICOCHET;
        else if (outSpeed)
            impact_type = ImpactTypes.PENETRATE;
        if (isWater)
            surface = "Hit_Water";
        EffBulletImpactBase eff = EffBulletImpactBase.Cast(GetImpactEffect(surface, ammoType).Spawn());
        if ( !eff && surface == "" ) // handle undefined surface
        {
            eff = EffBulletImpactBase.Cast( surface.ToType().Spawn() );
            if (eff)
            {
                RegisterSurface(surface);
                ErrorEx(string.Format("Unregistered surface for bullet impact effect (%1). Register this surface in ImpactMaterials (Script) for better performance.", surface), ErrorExSeverity.WARNING);
            }
            else
            {
                if (directHit)
                {
                    string object_type = directHit.GetType();
                    if ( object_type == "" )
                        object_type = "OBJECT_WITHOUT_CONFIG_CLASS";
                    ErrorEx(string.Format("Object '%1' with model file: %2.p3d has undefined 'Hit_...' material! Cannot play impact effect.", object_type, directHit.GetModelName()));
                    eff = EffBulletImpactBase.Cast(GetImpactEffect("Hit_ErrorNoMaterial", ammoType).Spawn());
                }
            }
        }
        if ( !eff && surface != "" )
        {
            ErrorEx(string.Format("Unregistered surface impact material <%1>! Register this surface in ImpactMaterials (Script).", surface));
            eff = EffBulletImpactBase.Cast(GetImpactEffect("Hit_Undefined", ammoType).Spawn());
        }
        if (eff)
        {
            eff.EvaluateEffect(directHit, componentIndex, pos, impact_type, surfNormal, exitPos, inSpeed, outSpeed, ammoType);
            eff.SetAutodestroy(true);
            SEffectManager.PlayInWorld( eff, pos );
        }
    }
References ErrorEx, EffBulletImpactBase::EvaluateEffect(), GetImpactEffect(), m_IgnoredAmmo, SEffectManager::PlayInWorld(), RegisterSurface(), Spawn(), and string::ToType().
GetImpactEffect()
static GetImpactEffect (string surface, string ammoType) static
Definition at line 103 of file impacteffects.c.
    {
        string key = string.Format("%1_%2", surface, ammoType);
        typename eff_type = m_ImpactEffect[key];
        if (eff_type)
            return eff_type;
        else
            return m_ImpactEffect[surface];
    }
References m_ImpactEffect.
Referenced by EvaluateImpactEffect().
RegisterIgnoredAmmo()
static int RegisterIgnoredAmmo (string ammo) static
Definition at line 80 of file impacteffects.c.
    {
        if (!m_IgnoredAmmo)
            m_IgnoredAmmo = new map<string, int>;
        ++m_LastRegisteredIgnoredAmmo;
        m_IgnoredAmmo.Insert(ammo, m_LastRegisteredIgnoredAmmo);
        return m_LastRegisteredIgnoredAmmo;
    }
References m_IgnoredAmmo, and m_LastRegisteredIgnoredAmmo.
RegisterSurface()
static int RegisterSurface (string surface) static
Definition at line 59 of file impacteffects.c.
    {
        if (!m_ImpactEffect)
            m_ImpactEffect = new map<string, typename>;
        m_ImpactEffect.Insert(surface, surface.ToType());
        return ++m_LastRegisteredMaterial;
    }
References m_ImpactEffect, m_LastRegisteredMaterial, and string::ToType().
Referenced by EvaluateImpactEffect().
UnregisterIgnoredAmmo()
static bool UnregisterIgnoredAmmo (string ammo) static
Definition at line 92 of file impacteffects.c.
    {
        if (m_IgnoredAmmo)
        {
            m_IgnoredAmmo.Remove(ammo);
            return !m_IgnoredAmmo.Contains(ammo);
        }
        return false;
    }
References m_IgnoredAmmo.
UnregisterSurface()
static bool UnregisterSurface (string surface) static
Definition at line 69 of file impacteffects.c.
    {
        if (m_ImpactEffect)
        {
            m_ImpactEffect.Remove(surface);
            return !m_ImpactEffect.Contains(surface);
        }
        return false;
    }
References m_ImpactEffect.
Variable Documentation
CONCRETE
int CONCRETE = RegisterSurface("Hit_Concrete") static
Definition at line 27 of file impacteffects.c.
DIRT
int DIRT = RegisterSurface("Hit_Dirt") static
Definition at line 29 of file impacteffects.c.
ERROR_NO_MATERIAL
int ERROR_NO_MATERIAL = RegisterSurface("Hit_ErrorNoMaterial") static
Definition at line 45 of file impacteffects.c.
FIST
int FIST = RegisterIgnoredAmmo("MeleeFist") static
Definition at line 53 of file impacteffects.c.
FIST_HEAVY
int FIST_HEAVY = RegisterIgnoredAmmo("MeleeFist_Heavy") static
Definition at line 54 of file impacteffects.c.
FOLIAGE
int FOLIAGE = RegisterSurface("Hit_Foliage") static
Definition at line 30 of file impacteffects.c.
GLASS
int GLASS = RegisterSurface("Hit_Glass") static
Definition at line 34 of file impacteffects.c.
GLASS_THIN
int GLASS_THIN = RegisterSurface("Hit_Glass_Thin") static
Definition at line 35 of file impacteffects.c.
GRASS
int GRASS = RegisterSurface("Hit_Grass") static
Definition at line 31 of file impacteffects.c.
GRAVEL
int GRAVEL = RegisterSurface("Hit_Gravel") static
Definition at line 28 of file impacteffects.c.
m_IgnoredAmmo
ref map<string, int> m_IgnoredAmmo static
Map of ammo which will not spawn any impact effect.
Definition at line 16 of file impacteffects.c.
Referenced by EvaluateImpactEffect(), RegisterIgnoredAmmo(), and UnregisterIgnoredAmmo().
m_ImpactEffect
enum ImpactTypes m_ImpactEffect
Referenced by GetImpactEffect(), RegisterSurface(), and UnregisterSurface().
m_LastRegisteredIgnoredAmmo
int m_LastRegisteredIgnoredAmmo = 0 static
Definition at line 17 of file impacteffects.c.
Referenced by RegisterIgnoredAmmo().
m_LastRegisteredMaterial
int m_LastRegisteredMaterial = 0 static
Definition at line 13 of file impacteffects.c.
Referenced by RegisterSurface().
MEATBONES
int MEATBONES = RegisterSurface("Hit_MeatBones") static
Definition at line 39 of file impacteffects.c.
MEATBONES_FIST
int MEATBONES_FIST = RegisterSurface("Hit_MeatBones_MeleeFist") static
Definition at line 43 of file impacteffects.c.
MEATBONES_PIPEWRENCH
int MEATBONES_PIPEWRENCH = RegisterSurface("Hit_MeatBones_MeleePipeWrench") static
Definition at line 41 of file impacteffects.c.
MEATBONES_SHOVEL
int MEATBONES_SHOVEL = RegisterSurface("Hit_MeatBones_MeleeShovel") static
Definition at line 40 of file impacteffects.c.
MEATBONES_WRENCH
int MEATBONES_WRENCH = RegisterSurface("Hit_MeatBones_MeleeWrench") static
Definition at line 42 of file impacteffects.c.
METAL
int METAL = RegisterSurface("Hit_Metal") static
Definition at line 33 of file impacteffects.c.
PLASTER
int PLASTER = RegisterSurface("Hit_Plaster") static
Definition at line 38 of file impacteffects.c.
PLASTIC
int PLASTIC = RegisterSurface("Hit_Plastic") static
Definition at line 24 of file impacteffects.c.
RUBBER
int RUBBER = RegisterSurface("Hit_Rubber") static
Definition at line 37 of file impacteffects.c.
SAND
int SAND = RegisterSurface("Hit_Sand") static
Definition at line 25 of file impacteffects.c.
SOFT
int SOFT = RegisterIgnoredAmmo("MeleeSoft") static
Definition at line 55 of file impacteffects.c.
SOFT_HEAVY
int SOFT_HEAVY = RegisterIgnoredAmmo("MeleeSoft_Heavy") static
Definition at line 56 of file impacteffects.c.
string
enum ImpactTypes string
TEXTILE
int TEXTILE = RegisterSurface("Hit_Textile") static
Definition at line 26 of file impacteffects.c.
UNDEFINED
int UNDEFINED = RegisterSurface("Hit_Undefined") static
Definition at line 44 of file impacteffects.c.
WATER
int WATER = RegisterSurface("Hit_Water") static
Definition at line 36 of file impacteffects.c.
WOOD
int WOOD = RegisterSurface("Hit_Wood") static
Definition at line 32 of file impacteffects.c.