DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/infectedsoundevents/infectedsoundeventbase.c File Reference
infectedsoundeventbase.c File Reference
Enumerations
enum EInfectedSoundEventType { GENERAL }
Functions
void InfectedSoundEventBase ()
void Init (ZombieBase pInfected)
override bool Play ()
void PosUpdate ()
void SoftStop ()
override void Stop ()
void ~InfectedSoundEventBase ()
Variables
enum EInfectedSoundEventType m_Infected
Enumeration Type Documentation
EInfectedSoundEventType
enum EInfectedSoundEventType
Enumerator
GENERAL
Definition at line 1 of file infectedsoundeventbase.c.
{
    GENERAL,
}
Function Documentation
InfectedSoundEventBase()
void InfectedSoundEventBase ()
Definition at line 10 of file infectedsoundeventbase.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
    }
References m_Type.
Init()
void Init (ZombieBase pInfected)
Definition at line 20 of file infectedsoundeventbase.c.
    {
        m_Infected = pInfected;
    }
References m_Infected.
Play()
override bool Play ()
Definition at line 53 of file infectedsoundeventbase.c.
    {
        string soundset_name;
        soundset_name = string.Format("%1_%2_SoundSet", m_Infected.ClassName(), m_SoundSetNameRoot);
        m_SoundSetCallback = m_Infected.ProcessVoiceFX(soundset_name);
        if ( m_SoundSetCallback )
        {
            GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).CallLaterByName(this, "PosUpdate", 0, true);
            return true;
        }
        #ifdef DEVELOPER
        Error("[ERROR] No sound callback for : " + m_Infected.ClassName() + " Please define relevant SoundSet in Zombie_SoundSets.hpp");
        #endif
        PrintToRPT("[WARNING] No sound callback for : " + m_Infected.ClassName() + " Please define relevant SoundSet in sounds/hpp/config.cpp");
        return false;
    }
References CALL_CATEGORY_GAMEPLAY, ScriptCallQueue::CallLaterByName(), Error(), string::Format(), CGame::GetCallQueue(), GetGame(), m_Infected, m_SoundSetCallback, m_SoundSetNameRoot, and PrintToRPT().
PosUpdate()
void PosUpdate ()
Definition at line 45 of file infectedsoundeventbase.c.
    {
        if (m_SoundSetCallback)
        {
            m_SoundSetCallback.SetPosition(m_Infected.GetPosition());
        }
    }
References m_Infected, m_SoundSetCallback, and AbstractWave::SetPosition().
SoftStop()
void SoftStop ()
Definition at line 25 of file infectedsoundeventbase.c.
    {
        if (m_SoundSetCallback)
        {
            m_SoundSetCallback.Loop(false);
            m_SoundSetCallback = null;
        }
    }
References AbstractWave::Loop(), and m_SoundSetCallback.
Stop()
override void Stop ()
Definition at line 34 of file infectedsoundeventbase.c.
    {
        if (m_SoundSetCallback)
        {
            m_SoundSetCallback.Stop();
            m_SoundSetCallback = null;
        }
        GetGame().GetCallQueue(CALL_CATEGORY_GAMEPLAY).RemoveByName(this, "PosUpdate");
    }
References CALL_CATEGORY_GAMEPLAY, CGame::GetCallQueue(), GetGame(), m_SoundSetCallback, ScriptCallQueue::RemoveByName(), and AbstractWave::Stop().
~InfectedSoundEventBase()
void ~InfectedSoundEventBase ()
Definition at line 15 of file infectedsoundeventbase.c.
    {
        if(m_SoundSetCallback) m_SoundSetCallback.Stop();
    }
References m_SoundSetCallback, and AbstractWave::Stop().
Variable Documentation
m_Infected
enum EInfectedSoundEventType m_Infected
Referenced by InfectedSoundEventHandler(), Init(), Play(), PlayRequest(), and PosUpdate().