DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/infectedsoundevents/infectedsoundeventhandler.c File Reference
infectedsoundeventhandler.c File Reference
Enumerations
enum EInfectedSoundEventID {
MINDSTATE_CALM_IDLE = 1 , MINDSTATE_CALM_MOVE , MINDSTATE_DISTURBED_IDLE , MINDSTATE_CHASE_MOVE ,
MINDSTATE_ALERTED_IDLE , MINDSTATE_ALERTED_MOVE , ENUM_COUNT
}
Functions
override int GetCurrentStateEventID ()
override int GetCurrentStateEventType ()
static override int GetSoundEventType (int id)
void InfectedSoundEventHandler (ZombieBase pInfected)
bool IsPlaying ()
override bool PlayRequest (int id, bool sent_from_server=false)
void SoftStop ()
void Stop ()
Variables
static ref InfectedSoundEventBase m_AvailableStates [SOUND_EVENTS_MAX]
ref InfectedSoundEventBase m_CurrentState
ZombieBase m_Infected
enum EInfectedSoundEventID SOUND_EVENTS_MAX = EInfectedSoundEventID.ENUM_COUNT
Enumeration Type Documentation
EInfectedSoundEventID
enum EInfectedSoundEventID
Enumerator
MINDSTATE_CALM_IDLE
MINDSTATE_CALM_MOVE
MINDSTATE_DISTURBED_IDLE
MINDSTATE_CHASE_MOVE
MINDSTATE_ALERTED_IDLE
MINDSTATE_ALERTED_MOVE
ENUM_COUNT
Definition at line 1 of file infectedsoundeventhandler.c.
{
    MINDSTATE_CALM_IDLE = 1,
    MINDSTATE_CALM_MOVE,
    MINDSTATE_DISTURBED_IDLE,
    //MINDSTATE_CHASE_IDLE,
    MINDSTATE_CHASE_MOVE,
    MINDSTATE_ALERTED_IDLE,
    MINDSTATE_ALERTED_MOVE,
    //--------------
    ENUM_COUNT,
}
Function Documentation
GetCurrentStateEventID()
override int GetCurrentStateEventID ()
Definition at line 38 of file infectedsoundeventhandler.c.
    {
        if (m_CurrentState)
        {
            return m_CurrentState.GetSoundEventID();
        }
        return -1;
    }
References m_CurrentState.
Referenced by PlayRequest().
GetCurrentStateEventType()
override int GetCurrentStateEventType ()
Definition at line 47 of file infectedsoundeventhandler.c.
    {
        if (m_CurrentState)
        {
            return m_CurrentState.GetSoundEventType();
        }
        return -1;
    }
References m_CurrentState.
GetSoundEventType()
static override int GetSoundEventType (int id) static
Definition at line 33 of file infectedsoundeventhandler.c.
    {
        return m_AvailableStates[id].GetSoundEventType();
    }
References m_AvailableStates.
InfectedSoundEventHandler()
void InfectedSoundEventHandler (ZombieBase pInfected)
Definition at line 21 of file infectedsoundeventhandler.c.
    {
        m_Infected = pInfected;
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_CALM_IDLE] = new CalmIdleSoundEvent();
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_CALM_MOVE] = new CalmMoveSoundEvent();
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_DISTURBED_IDLE] = new DisturbedIdleSoundEvent();
        //m_AvailableStates[EInfectedSoundEventID.MINDSTATE_CHASE_IDLE] = new ChaseIdleSoundEvent();
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_CHASE_MOVE] = new ChaseMoveSoundEvent();
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_ALERTED_IDLE] = new AlertedIdleSoundEvent();
        m_AvailableStates[EInfectedSoundEventID.MINDSTATE_ALERTED_MOVE] = new AlertedMoveSoundEvent();
    }
References AlertedIdleSoundEvent(), CalmIdleSoundEvent(), CalmMoveSoundEvent(), ChaseMoveSoundEvent(), DisturbedIdleSoundEvent(), m_AvailableStates, and m_Infected.
Referenced by DayZInfected::Init().
IsPlaying()
bool IsPlaying ()
Definition at line 72 of file infectedsoundeventhandler.c.
    {
        if ( m_CurrentState && m_CurrentState.IsSoundCallbackExist() )
        {
            return true;
        }
        return false;
    }
References m_CurrentState.
PlayRequest()
override bool PlayRequest (int id, bool sent_from_server = false)
same sound event - skip
Definition at line 82 of file infectedsoundeventhandler.c.
    {
        InfectedSoundEventBase requested_state = m_AvailableStates[id];
        if ( !requested_state.CanPlay() )
        {
            return false;
        }
        if (m_CurrentState)
        {
            if (!m_CurrentState.IsSoundCallbackExist())
            {
                //Print("Missing callback - cleanup and continue");
                delete m_CurrentState;
            }
            if (GetCurrentStateEventID() == id)
            {
                //Print("Same ID - skipping");
                return false;
            }
        }
        if (m_CurrentState)
        {
            m_CurrentState.SoftStop();
            m_CurrentState = InfectedSoundEventBase.Cast(requested_state.ClassName().ToType().Spawn());
            m_CurrentState.Init(m_Infected);
            m_CurrentState.Play();
            return true;
        }
        else
        {
            m_CurrentState = InfectedSoundEventBase.Cast(requested_state.ClassName().ToType().Spawn());
            m_CurrentState.Init(m_Infected);
            m_CurrentState.Play();
            return true;
        }
        return false;//should never get here
    }
References InfectedSoundEventBase::CanPlay(), GetCurrentStateEventID(), m_AvailableStates, m_CurrentState, and m_Infected.
SoftStop()
void SoftStop ()
Definition at line 64 of file infectedsoundeventhandler.c.
    {
        if ( m_CurrentState )
        {
            m_CurrentState.SoftStop();
        }
    }
References m_CurrentState.
Stop()
void Stop ()
Definition at line 56 of file infectedsoundeventhandler.c.
    {
        if ( m_CurrentState )
        {
            m_CurrentState.Stop();
        }
    }
References m_CurrentState.
Variable Documentation
m_AvailableStates
ref InfectedSoundEventBase m_AvailableStates[SOUND_EVENTS_MAX] static
Definition at line 17 of file infectedsoundeventhandler.c.
Referenced by GetSoundEventType(), InfectedSoundEventHandler(), PlayRequest(), PlayRequestEx(), and RegisterState().
m_CurrentState
ref InfectedSoundEventBase m_CurrentState
Definition at line 18 of file infectedsoundeventhandler.c.
Referenced by GetCurrentStateEventID(), GetCurrentStateEventType(), IsPlaying(), OnTick(), PlayRequest(), PlayRequestEx(), SoftStop(), and Stop().
m_Infected
ZombieBase m_Infected
Definition at line 19 of file infectedsoundeventhandler.c.
SOUND_EVENTS_MAX
enum EInfectedSoundEventID SOUND_EVENTS_MAX = EInfectedSoundEventID.ENUM_COUNT
Referenced by PlayRequestEx().