DayzKode: P:/scripts/4_world/DayZ/classes/injuryhandler.c File Reference
injuryhandler.c File Reference
Classes
class InjuryAnimValues
class InjuryHandlerThresholds
Enumerations
enum eInjuryHandlerLevels {
PRISTINE , WORN , DAMAGED , BADLY_DAMAGED ,
RUINED
}
Functions
void CheckValue (bool forceUpdate=false)
float GetInjuryAnimValue ()
eInjuryHandlerLevels GetInjuryLevel (float health)
float GetInjuryValue (eInjuryHandlerLevels level)
ScriptInvoker GetInvoker ()
eInjuryHandlerLevels GetOverrideLevel (eInjuryHandlerLevels unchanged_level)
void InjuryAnimationHandler (PlayerBase player)
bool IsInjuryAnimEnabled ()
void SendValue (eInjuryHandlerLevels level)
void SetInjuryCommandParams (bool enable, eInjuryHandlerLevels level)
void Synchronize (eInjuryHandlerLevels level)
void Update (float deltaT)
Variables
enum eInjuryHandlerLevels BROKEN_LEGS = 8
enum eInjuryHandlerLevels BROKEN_LEGS_SPLINT = 16
private bool m_AnimationChange = false
owner
ref ScriptInvoker m_ChangedStateInvoker = new ScriptInvoker()
int m_ForceInjuryAnimMask
float m_HealthMaxValue
private float m_InjuryAnimDamageValue = 0
private bool m_InjuryAnimEnabled = false
eInjuryHandlerLevels m_LastHealthUpdate
float m_LastUpdate
private PlayerBase m_Player
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
enum eInjuryHandlerLevels MORPHINE = 1
enum eInjuryHandlerLevels NONE = 0
MUST BE POW2.
enum eInjuryHandlerLevels PAIN_KILLERS_LVL0 = 2
enum eInjuryHandlerLevels PAIN_KILLERS_LVL1 = 4
enum eInjuryHandlerLevels PRONE_ANIM_OVERRIDE = 32
const float SENSITIVTY_PERCENTAGE = 1
enum eInjuryHandlerLevels VALUE_CHECK_INTERVAL = 5
Enumeration Type Documentation
eInjuryHandlerLevels
enum eInjuryHandlerLevels
Enumerator
PRISTINE
WORN
DAMAGED
BADLY_DAMAGED
RUINED
Definition at line 18 of file injuryhandler.c.
{
    PRISTINE,
    WORN,
    DAMAGED,
    BADLY_DAMAGED,
    RUINED,
}
Function Documentation
CheckValue()
void CheckValue (bool forceUpdate = false)
Definition at line 154 of file injuryhandler.c.
    {
        float health_current_normalized = m_Player.GetHealth("","Health") / m_HealthMaxValue;
        eInjuryHandlerLevels injury_level = GetInjuryLevel(health_current_normalized);
        if ( m_ForceInjuryAnimMask )
        {
            injury_level = GetOverrideLevel(injury_level);
        }
        if ( m_LastHealthUpdate != injury_level || forceUpdate )
        {
            SendValue(injury_level);
            m_ChangedStateInvoker.Invoke(injury_level);
            m_LastHealthUpdate = injury_level;
            Synchronize(injury_level);
        }
    }
References GetInjuryLevel(), GetOverrideLevel(), ScriptInvoker::Invoke(), m_ChangedStateInvoker, m_ForceInjuryAnimMask, m_HealthMaxValue, m_LastHealthUpdate, m_Player, SendValue(), and Synchronize().
Referenced by Update().
GetInjuryAnimValue()
float GetInjuryAnimValue ()
Definition at line 70 of file injuryhandler.c.
    {
        return m_InjuryAnimDamageValue;
    }
References m_InjuryAnimDamageValue.
GetInjuryLevel()
eInjuryHandlerLevels GetInjuryLevel (float health)
Definition at line 192 of file injuryhandler.c.
    {
        if ( health  < InjuryHandlerThresholds.RUINED )
        {
            return eInjuryHandlerLevels.RUINED;
        }
        if ( health  < InjuryHandlerThresholds.BADLY_DAMAGED )
        {
            return eInjuryHandlerLevels.BADLY_DAMAGED;
        }
        if ( health  < InjuryHandlerThresholds.DAMAGED )
        {
            return eInjuryHandlerLevels.DAMAGED;
        }
        if ( health  < InjuryHandlerThresholds.WORN )
        {
            return eInjuryHandlerLevels.WORN;
        }
        return eInjuryHandlerLevels.PRISTINE;
    }
References InjuryHandlerThresholds::BADLY_DAMAGED, InjuryHandlerThresholds::DAMAGED, InjuryHandlerThresholds::RUINED, and InjuryHandlerThresholds::WORN.
Referenced by CheckValue().
GetInjuryValue()
float GetInjuryValue (eInjuryHandlerLevels level)
Definition at line 218 of file injuryhandler.c.
    {
        switch ( level )
        {
            case eInjuryHandlerLevels.RUINED:
            {
                return InjuryAnimValues.LVL4;
            }
            case eInjuryHandlerLevels.BADLY_DAMAGED:
            {
                return InjuryAnimValues.LVL3;
            }
            case eInjuryHandlerLevels.DAMAGED:
            {
                return InjuryAnimValues.LVL2;
            }
            case eInjuryHandlerLevels.WORN:
            {
                return InjuryAnimValues.LVL1;
            }
            case eInjuryHandlerLevels.PRISTINE:
            {
                return InjuryAnimValues.LVL0;
            }
            default:
                Error("Undefined Injury level");
        }
        return 0;
    }
References Error(), InjuryAnimValues::LVL0, InjuryAnimValues::LVL1, InjuryAnimValues::LVL2, InjuryAnimValues::LVL3, and InjuryAnimValues::LVL4.
Referenced by SetInjuryCommandParams().
GetInvoker()
ScriptInvoker GetInvoker ()
Definition at line 75 of file injuryhandler.c.
    {
        return m_ChangedStateInvoker;
    }
References m_ChangedStateInvoker.
GetOverrideLevel()
eInjuryHandlerLevels GetOverrideLevel (eInjuryHandlerLevels unchanged_level)
Definition at line 100 of file injuryhandler.c.
    {
        eInjuryHandlerLevels override_level = unchanged_level;
        //Whatever the case, prone will always use PRISTINE anim level as alternative anim level(s) are not interesting gameplaywise
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.PRONE_ANIM_OVERRIDE && override_level > eInjuryHandlerLevels.PRISTINE )
        {
            override_level = eInjuryHandlerLevels.PRISTINE;
            return override_level;
        }
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.MORPHINE && override_level > eInjuryHandlerLevels.PRISTINE )
        {
            override_level = eInjuryHandlerLevels.PRISTINE;
        }
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.PAIN_KILLERS_LVL1 && override_level > eInjuryHandlerLevels.WORN )
        {
            override_level = eInjuryHandlerLevels.WORN;
        }
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.PAIN_KILLERS_LVL0 && override_level > eInjuryHandlerLevels.DAMAGED )
        {
            override_level = eInjuryHandlerLevels.DAMAGED;
        }
        if ( m_ForceInjuryAnimMask && override_level > eInjuryHandlerLevels.DAMAGED )
        {
            override_level = eInjuryHandlerLevels.RUINED;
        }
        //Broken leg overrides
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.BROKEN_LEGS_SPLINT && override_level < eInjuryHandlerLevels.DAMAGED )
        {
            override_level = eInjuryHandlerLevels.DAMAGED;
        }
        if ( m_ForceInjuryAnimMask & eInjuryOverrides.BROKEN_LEGS && override_level < eInjuryHandlerLevels.RUINED )
        {
            //Average leg health used to determine which animation to use
            float avgLegHealth = m_Player.GetHealth("RightLeg","") + m_Player.GetHealth("LeftLeg","") + m_Player.GetHealth("RightFoot","") + m_Player.GetHealth("LeftFoot","");
            avgLegHealth *= 0.25; //divide by 4 to make the average leg health;
            if (avgLegHealth <= PlayerConstants.BROKEN_LEGS_LOW_HEALTH_THRESHOLD)
                override_level = eInjuryHandlerLevels.RUINED;
            else if (avgLegHealth >= PlayerConstants.BROKEN_LEGS_HIGH_HEALTH_THRESHOLD)
                override_level = eInjuryHandlerLevels.WORN;
            else
                override_level = eInjuryHandlerLevels.DAMAGED;
        }
        return override_level;
    }
References PlayerConstants::BROKEN_LEGS_HIGH_HEALTH_THRESHOLD, PlayerConstants::BROKEN_LEGS_LOW_HEALTH_THRESHOLD, m_ForceInjuryAnimMask, and m_Player.
Referenced by CheckValue().
InjuryAnimationHandler()
void InjuryAnimationHandler (PlayerBase player)
Definition at line 59 of file injuryhandler.c.
    {
        m_Player = player;
        m_HealthMaxValue = m_Player.GetMaxHealth("", "Health");
    }
References m_HealthMaxValue, and m_Player.
Referenced by ManBase::Init().
IsInjuryAnimEnabled()
bool IsInjuryAnimEnabled ()
Definition at line 65 of file injuryhandler.c.
    {
        return m_InjuryAnimEnabled;
    }
References m_InjuryAnimEnabled.
SendValue()
void SendValue (eInjuryHandlerLevels level)
Definition at line 180 of file injuryhandler.c.
    {
        DayZPlayerSyncJunctures.SendInjury(m_Player, true, level);
    }
References m_Player, and DayZPlayerSyncJunctures::SendInjury().
Referenced by CheckValue().
SetInjuryCommandParams()
void SetInjuryCommandParams (bool enable, eInjuryHandlerLevels level)
Definition at line 185 of file injuryhandler.c.
    {
        m_AnimationChange = true;
        m_InjuryAnimEnabled = enable;
        m_InjuryAnimDamageValue = GetInjuryValue(level);
    }
References GetInjuryValue(), m_AnimationChange, m_InjuryAnimDamageValue, and m_InjuryAnimEnabled.
Synchronize()
void Synchronize (eInjuryHandlerLevels level)
Definition at line 173 of file injuryhandler.c.
    {
        m_Player.m_HealthLevel = level;
        //Print("m_Player.m_HealthLevel:" + m_Player.m_HealthLevel);
        m_Player.SetSynchDirty();
    }
References m_Player.
Update()
void Update (float deltaT)
Definition at line 80 of file injuryhandler.c.
    {
        if ( m_AnimationChange )
        {
            m_Player.GetCommandModifier_Additives().SetInjured(m_InjuryAnimDamageValue, m_InjuryAnimEnabled);
            m_AnimationChange = false;
        }
        if ( GetGame().IsClient() )
            return;
        m_TimeSinceLastTick += deltaT;
        if ( m_TimeSinceLastTick > VALUE_CHECK_INTERVAL )
        {
            CheckValue();
            m_TimeSinceLastTick = 0;
        }
    }
References CheckValue(), GetGame(), m_AnimationChange, m_InjuryAnimDamageValue, m_InjuryAnimEnabled, m_Player, m_TimeSinceLastTick, and VALUE_CHECK_INTERVAL.
Variable Documentation
BROKEN_LEGS
enum eInjuryHandlerLevels BROKEN_LEGS = 8
BROKEN_LEGS_SPLINT
enum eInjuryHandlerLevels BROKEN_LEGS_SPLINT = 16
m_AnimationChange
private bool m_AnimationChange = false
owner
Definition at line 54 of file injuryhandler.c.
Referenced by SetInjuryCommandParams(), and Update().
m_ChangedStateInvoker
ref ScriptInvoker m_ChangedStateInvoker = new ScriptInvoker()
Definition at line 45 of file injuryhandler.c.
Referenced by CheckValue(), and GetInvoker().
m_ForceInjuryAnimMask
int m_ForceInjuryAnimMask
Definition at line 57 of file injuryhandler.c.
Referenced by CheckValue(), and GetOverrideLevel().
m_HealthMaxValue
float m_HealthMaxValue
Definition at line 50 of file injuryhandler.c.
Referenced by CheckValue(), Managed::Init(), and InjuryAnimationHandler().
m_InjuryAnimDamageValue
private float m_InjuryAnimDamageValue = 0
Definition at line 56 of file injuryhandler.c.
Referenced by GetInjuryAnimValue(), SetInjuryCommandParams(), and Update().
m_InjuryAnimEnabled
private bool m_InjuryAnimEnabled = false
Definition at line 55 of file injuryhandler.c.
Referenced by IsInjuryAnimEnabled(), SetInjuryCommandParams(), and Update().
m_LastHealthUpdate
eInjuryHandlerLevels m_LastHealthUpdate
Definition at line 49 of file injuryhandler.c.
Referenced by Managed::CheckHealth(), CheckValue(), Managed::Init(), and Managed::SendInitValues().
m_LastUpdate
float m_LastUpdate
Definition at line 48 of file injuryhandler.c.
m_Player
private PlayerBase m_Player
Definition at line 53 of file injuryhandler.c.
m_TimeSinceLastTick
float m_TimeSinceLastTick = VALUE_CHECK_INTERVAL + 1
Definition at line 47 of file injuryhandler.c.
Referenced by Managed::OnScheduledTick(), and Update().
MORPHINE
enum eInjuryHandlerLevels MORPHINE = 1
NONE
enum eInjuryHandlerLevels NONE = 0
MUST BE POW2.
PAIN_KILLERS_LVL0
enum eInjuryHandlerLevels PAIN_KILLERS_LVL0 = 2
PAIN_KILLERS_LVL1
enum eInjuryHandlerLevels PAIN_KILLERS_LVL1 = 4
PRONE_ANIM_OVERRIDE
enum eInjuryHandlerLevels PRONE_ANIM_OVERRIDE = 32
SENSITIVTY_PERCENTAGE
const float SENSITIVTY_PERCENTAGE = 1
Definition at line 43 of file injuryhandler.c.
Referenced by Managed::CheckBlood(), and Managed::CheckHealth().
VALUE_CHECK_INTERVAL
enum eInjuryHandlerLevels VALUE_CHECK_INTERVAL = 5
Referenced by Managed::OnScheduledTick(), and Update().