DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/playersoundevents/events/injuryevents.c File Reference
injuryevents.c File Reference
Classes
class InjurySoundEvents
class PlayerSoundEventBase
Functions
override bool CanPlay (PlayerBase player)
override bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
class InjuryMediumSoundEvent extends InjurySoundEvents InjuryHeavySoundEvent ()
class InjurySoundEvents extends PlayerSoundEventBase InjuryLightSoundEvent ()
void InjuryMediumSoundEvent ()
void InjurySoundEvents ()
Function Documentation
CanPlay()
override bool InjuryLightSoundEvent::CanPlay (PlayerBase player)
Definition at line 31 of file injuryevents.c.
{
    void InjuryMediumSoundEvent()
    {
HasPriorityOverCurrent()
override bool InjuryLightSoundEvent::HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 36 of file injuryevents.c.
{
InjuryHeavySoundEvent()
class InjuryMediumSoundEvent extends InjurySoundEvents InjuryHeavySoundEvent ()
Definition at line 31 of file injuryevents.c.
    {
        m_ID = EPlayerSoundEventID.INJURED_HIGH;
        m_SoundVoiceAnimEventClassID = 28;
    }
Referenced by PlayerSoundEventHandler().
InjuryLightSoundEvent()
class InjurySoundEvents extends PlayerSoundEventBase InjuryLightSoundEvent ()
Definition at line 1 of file injuryevents.c.
    {
        m_ID = EPlayerSoundEventID.INJURED_LIGHT;
        m_SoundVoiceAnimEventClassID = 28;
    }
Referenced by PlayerSoundEventHandler().
InjuryMediumSoundEvent()
void InjuryHeavySoundEvent::InjuryMediumSoundEvent ()
Definition at line 44 of file injuryevents.c.
    {
        m_ID = EPlayerSoundEventID.INJURED_HIGH;
        m_SoundVoiceAnimEventClassID = 28;
    }
}
References m_ID, and m_SoundVoiceAnimEventClassID.
Referenced by PlayerSoundEventHandler().
InjurySoundEvents()
void InjuryLightSoundEvent::InjurySoundEvents ()
Definition at line 25 of file injuryevents.c.
{