DayzKode: P:/scripts/5_mission/DayZ/gui/inventorymenu.c File Reference
inventorymenu.c File Reference
Enumerations
enum ScreenWidthType { NARROW , MEDIUM , WIDE }
Functions
void CheckWidth ()
override ContextMenu GetContextMenu ()
static int GetHeight ()
static float GetHeightMultiplied (float value)
int GetLastDisplayLanguage ()
static int GetWidth ()
static ScreenWidthType GetWidthType ()
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void InitContainers (EntityAI target)
void InventoryMenu ()
bool IsOpened ()
bool LanguageChanged ()
override bool OnController (Widget w, int control, int value)
override void OnHide ()
override void OnShow ()
override void Refresh ()
void RefreshQuickbar ()
override void Update (float timeslice)
Variables
private ref ContextMenu m_context_menu
static protected int m_Height
enum ScreenWidthType m_Inventory
protected bool m_IsOpened
protected int m_LastDisplayLanguage
protected bool m_OnlyFirstTime
static protected int m_Width
static protected ScreenWidthType m_WidthType
Enumeration Type Documentation
ScreenWidthType
enum ScreenWidthType
Enumerator
NARROW
MEDIUM
WIDE
Definition at line 1 of file inventorymenu.c.
{
    NARROW,
    MEDIUM,
    WIDE
}
Function Documentation
CheckWidth()
void CheckWidth ()
Definition at line 38 of file inventorymenu.c.
    {
        GetScreenSize( m_Width, m_Height );
        if( m_Height > 0 )
        {
            float ratio = m_Width / m_Height;
            if( ratio > 1.75 )
                m_WidthType = ScreenWidthType.WIDE;
            else if( ratio > 1.5 )
                m_WidthType = ScreenWidthType.MEDIUM;
            else
                m_WidthType = ScreenWidthType.NARROW;
        }
    }
References GetScreenSize(), m_Height, m_Width, and m_WidthType.
Referenced by InventoryMenu().
GetContextMenu()
override ContextMenu GetContextMenu ()
Definition at line 80 of file inventorymenu.c.
    {
        return m_context_menu;
    }
References m_context_menu.
GetHeight()
static int GetHeight () static
Definition at line 64 of file inventorymenu.c.
    {
        return m_Height;
    }
References m_Height.
GetHeightMultiplied()
static float GetHeightMultiplied (float value) static
Definition at line 69 of file inventorymenu.c.
    {
        float height = m_Height;
        return height / 1080 * value;
    }
References m_Height.
GetLastDisplayLanguage()
int GetLastDisplayLanguage ()
Definition at line 160 of file inventorymenu.c.
    {
        return m_LastDisplayLanguage;
    }
References m_LastDisplayLanguage.
GetWidth()
static int GetWidth () static
Definition at line 59 of file inventorymenu.c.
    {
        return m_Width;
    }
References m_Width.
GetWidthType()
static ScreenWidthType GetWidthType () static
Definition at line 54 of file inventorymenu.c.
    {
        return m_WidthType;
    }
References m_WidthType.
Init()
override Widget Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 30 of file inventorymenu.c.
    {
        m_Inventory.Init();
        m_context_menu.Init(layoutRoot);
        layoutRoot = m_Inventory.GetMainWidget();
        return layoutRoot;
    }
References m_context_menu, and m_Inventory.
InitContainers()
void InitContainers (EntityAI target)
Definition at line 85 of file inventorymenu.c.
    {
    }
InventoryMenu()
void InventoryMenu ()
Definition at line 20 of file inventorymenu.c.
    {
        CheckWidth();
        m_Inventory = new Inventory(null);
        m_Inventory.Reset();
        m_Inventory.UpdateInterval();
        m_context_menu = new ContextMenu;
        m_LastDisplayLanguage = g_Game.GetCurrentDisplayLanguageIdx();
    }
References CheckWidth(), g_Game, Inventory(), m_context_menu, m_Inventory, and m_LastDisplayLanguage.
Referenced by AddQuickbarItem(), MissionBaseWorld::CreateScriptedMenu(), Icon::DestroyWhiteBackground(), Icon::DoubleClick(), PlayerContainer::DoubleClick(), VicinitySlotsContainer::DoubleClick(), ZombieContainer::DoubleClick(), MissionBase::InitInventory(), ScriptedWidgetEventHandler::InspectItem(), PlayerContainer::OnDropReceivedFromGhostArea(), VicinityContainer::OnDropReceivedFromHeader(), VicinityContainer::OnDropReceivedFromIcon(), MissionBase::OnEvent(), InventoryGridController::OnItemDrop(), InventoryGridController::OnItemDropReceived(), MissionBase::OnUpdate(), Icon::RefreshQuickbar(), Hud::RefreshQuickbar(), LeftArea::SetLayoutName(), RightArea::SetLayoutName(), Container::SetLayoutName(), CargoContainerRow::SetLayoutName(), Icon::SetLayoutName(), SlotsContainer::SetLayoutName(), SetLayoutName(), ClosableHeader::SetName(), Container::UpdateHeaderText(), and HandsArea::UpdateInterval().
IsOpened()
bool IsOpened ()
Definition at line 136 of file inventorymenu.c.
    {
        return m_IsOpened;
    }
References m_IsOpened.
LanguageChanged()
bool LanguageChanged ()
Definition at line 165 of file inventorymenu.c.
    {
        return g_Game.GetCurrentDisplayLanguageIdx() != m_LastDisplayLanguage;
    }
References g_Game, and m_LastDisplayLanguage.
OnController()
override bool OnController (Widget w, int control, int value)
Definition at line 129 of file inventorymenu.c.
    {
        if( m_IsOpened )
            return m_Inventory.Controller( w, control, value );
        return false;
    }
References m_Inventory, and m_IsOpened.
OnHide()
override void OnHide ()
Definition at line 141 of file inventorymenu.c.
    {
        super.OnHide();
        m_context_menu.Hide();
        m_IsOpened = false;
        PPERequesterBank.GetRequester(PPERequesterBank.REQ_INVENTORYBLUR).Stop();
        if(m_Inventory)
            m_Inventory.OnHide();
        MissionGameplay mission = MissionGameplay.Cast( GetGame().GetMission() );
        if( mission )
        {
            mission.MoveHudForInventory( false );
        }
        ItemManager.GetInstance().SetItemMicromanagmentMode( false );
        ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
        ItemManager.GetInstance().HideTooltip();
    }
References GetGame(), ItemManager::GetInstance(), ItemManager::HideTooltip(), m_context_menu, m_Inventory, m_IsOpened, mission, ItemManager::SetItemMicromanagmentMode(), and ItemManager::SetSelectedItem().
Referenced by Container::Close(), ClosableContainer::Close(), ClosableContainer::LockCargo(), and Container::SetOpenState().
OnShow()
override void OnShow ()
Definition at line 105 of file inventorymenu.c.
    {
        super.OnShow();
        m_IsOpened = true;
        PPERequesterBank.GetRequester(PPERequesterBank.REQ_INVENTORYBLUR).Start();
        VicinityItemManager.GetInstance().RefreshVicinityItems();
        if(m_Inventory)
            m_Inventory.OnShow();
        SetFocus( layoutRoot );
        MissionGameplay mission = MissionGameplay.Cast( GetGame().GetMission() );
        if( mission )
        {
            mission.MoveHudForInventory( true );
        }
        ItemManager.GetInstance().SetItemMicromanagmentMode( false );
        ItemManager.GetInstance().SetSelectedItem( null, null, null, null );
        m_Inventory.Refresh();
    }
References GetGame(), ItemManager::GetInstance(), VicinityItemManager::GetInstance(), m_Inventory, m_IsOpened, mission, VicinityItemManager::RefreshVicinityItems(), SetFocus(), ItemManager::SetItemMicromanagmentMode(), and ItemManager::SetSelectedItem().
Refresh()
override void Refresh ()
Definition at line 98 of file inventorymenu.c.
    {
        super.Refresh();
        m_Inventory.UpdateConsoleToolbar();
    }
References m_Inventory.
RefreshQuickbar()
void RefreshQuickbar ()
Definition at line 75 of file inventorymenu.c.
    {
        m_Inventory.RefreshQuickbar();
    }
References m_Inventory.
Referenced by UIScriptedMenu::ChangeCurrentCategory(), UIScriptedMenu::Init(), OnShow(), UIScriptedMenu::PrimaryAction(), Refresh(), and UIScriptedMenu::SecondaryAction().
Update()
override void Update (float timeslice)
Definition at line 90 of file inventorymenu.c.
    {
        if( m_Inventory )
        {
            m_Inventory.Update(timeslice);
        }
    }
References m_Inventory.
Variable Documentation
m_context_menu
private ref ContextMenu m_context_menu
Definition at line 11 of file inventorymenu.c.
Referenced by GetContextMenu(), Init(), InventoryMenu(), and OnHide().
m_Height
protected int m_Height static
Definition at line 18 of file inventorymenu.c.
Referenced by CheckWidth(), GetHeight(), and GetHeightMultiplied().
m_Inventory
enum ScreenWidthType m_Inventory
Referenced by Init(), InventoryMenu(), OnController(), OnHide(), OnShow(), Refresh(), RefreshQuickbar(), and Update().
m_IsOpened
protected bool m_IsOpened
Definition at line 12 of file inventorymenu.c.
Referenced by IsOpened(), OnController(), OnHide(), OnShow(), BaseBuildingBase::OnStoreLoad(), BaseBuildingBase::OnStoreSave(), BaseBuildingBase::OnVariablesSynchronized(), and BaseBuildingBase::SetOpenedState().
m_LastDisplayLanguage
protected int m_LastDisplayLanguage
Definition at line 14 of file inventorymenu.c.
Referenced by GetLastDisplayLanguage(), InventoryMenu(), and LanguageChanged().
m_OnlyFirstTime
protected bool m_OnlyFirstTime
Definition at line 13 of file inventorymenu.c.
m_Width
protected int m_Width static
Definition at line 17 of file inventorymenu.c.
Referenced by CheckWidth(), and GetWidth().
m_WidthType
protected ScreenWidthType m_WidthType static
Definition at line 16 of file inventorymenu.c.
Referenced by CheckWidth(), and GetWidthType().