DayzKode: P:/scripts/3_game/DayZ/systems/inventory/inventorylocation.c File Reference
inventorylocation.c File Reference
Classes
class InventoryLocation
InventoryLocation.
Enumerations
enum FindInventoryLocationType {
ATTACHMENT , CARGO , HANDS , PROXYCARGO ,
ANY_CARGO , ANY , NO_SLOT_AUTO_ASSIGN
}
flags for searching locations in inventory
enum InventoryLocationType {
UNKNOWN , GROUND , ATTACHMENT , CARGO ,
HANDS , PROXYCARGO
}
types of Inventory Location
Functions
bool OptionalLocationReadFromContext (out InventoryLocation loc, notnull ParamsReadContext ctx)
bool OptionalLocationWriteToContext (InventoryLocation loc, notnull ParamsWriteContext ctx)
Enumeration Type Documentation
FindInventoryLocationType
enum FindInventoryLocationType
flags for searching locations in inventory
Enumerator
ATTACHMENT
< ground
ATT.
attachment of another entity
CARGO
cargo of another entity
CGO.
HANDS
hands of another entity
HND.
PROXYCARGO
cargo of a large object (building,...)
PXY.
ANY_CARGO
CGO | PXY.
ANY
ATT | CGO | PXY | HND.
NO_SLOT_AUTO_ASSIGN
skips auto-assign test
Definition at line 15 of file inventorylocation.c.
{
    ATTACHMENT,
    CARGO,
    HANDS,
    PROXYCARGO,
    ANY_CARGO,
    ANY,
    NO_SLOT_AUTO_ASSIGN
};
InventoryLocationType
enum InventoryLocationType
types of Inventory Location
Enumerator
UNKNOWN
unknown, usually freshly created object
GROUND
ATTACHMENT
< ground
ATT.
attachment of another entity
CARGO
cargo of another entity
CGO.
HANDS
hands of another entity
HND.
PROXYCARGO
cargo of a large object (building,...)
PXY.
Definition at line 3 of file inventorylocation.c.
{
    UNKNOWN,
    GROUND,
    ATTACHMENT,
    CARGO,
    HANDS,
    PROXYCARGO,
};
Function Documentation
OptionalLocationReadFromContext()
bool OptionalLocationReadFromContext (out InventoryLocation loc, notnull ParamsReadContext ctx)
Definition at line 570 of file inventorylocation.c.
{
    bool present = false;
    if (!ctx.Read(present))
    {
        Error("OptionalLocationReadFromContext - cannot read bool from context!");
        return false;
    }
    if (!present)
        return true;
    loc = new InventoryLocation;
    if (!loc.ReadFromContext(ctx))
    {
        Error("OptionalLocationReadFromContext - cannot read (present) inventorylocation from context!");
        return false;
    }
    return true;
}
References Error().
Referenced by CreateHandEventFromContext(), WeaponStateBase::LoadCurrentFSMState(), and LoadCurrentFSMState().
OptionalLocationWriteToContext()
bool OptionalLocationWriteToContext (InventoryLocation loc, notnull ParamsWriteContext ctx)
Definition at line 548 of file inventorylocation.c.
{
    if (loc)
    {
        if (!ctx.Write(true))
        {
            Error("OptionalLocationWriteToContext - cannot write 1 to context!");
            return false;
        }
        return loc.WriteToContext(ctx);
    }
    else
    {
        if (!ctx.Write(false))
        {
            Error("OptionalLocationWriteToContext - cannot write 0 to context!");
            return false;
        }
    }
    return true;
}
References Error(), and InventoryLocation::WriteToContext().
Referenced by WeaponStateBase::SaveCurrentFSMState(), SaveCurrentFSMState(), and WriteToContext().