DayzKode: P:/scripts/4_world/DayZ/entities/building/underground/water/land_underground_waterreservoir.c File Reference
land_underground_waterreservoir.c File Reference
Classes
class Land_Underground_WaterReservoir_Water
class WaterLevelSettings
class WaterLevelSnapshot
Functions
protected PressureLevelSettings ActualPressureLevelStageSettings (int pValveIndex, bool pDeanimationRequest=false)
protected WaterLevelSettings ActualWaterLevelStageSettings (int pValveIndex)
protected float AdjustTime (float originalTime)
protected void AdvanceToNextPressureLevelStageSettings (int pValveIndex)
protected void AdvanceToNextWaterLevelStageSettings (int pValveIndex)
protected void AnimateValve (int pValveIndex, float pPhase)
protected void CleanSoundEffects ()
protected void CleanVisualEffects ()
protected void ConfigureValvesAndGaugesCourse ()
override void EOnPostSimulate (IEntity other, float timeSlice)
protected vector GetMemoryPointPosition (string pMemoryPoint)
override int GetTurnableValveIndex (int pComponentIndex)
array< vector > GetValveAligningPointsWS (int pValveIndex)
protected float GetValvePressureLevelGauge (int pValveIndex)
protected void HandleSoundEffects ()
protected void HandleSoundEffectsPipeCreaking ()
protected void HandleSoundEffectsPipeSprinkling ()
protected void HandleSoundEffectsUnderwaterPipeSounds ()
protected void HandleSoundEffectsWaterLevelMovementSounds ()
protected void HandleVisualEffects ()
override bool HasTurnableValveBehavior ()
protected int HeightToWaterLevel (float pHeight)
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
protected bool IsAnyValveActive ()
protected bool IsValveActive (int pValveIndex)
protected bool IsValvePressureLevelGaugeAtBase (int pValveIndex)
override bool IsValveTurnable (int pValveIndex)
void Land_Underground_WaterReservoir ()
protected void LateInit ()
void OnValveManipulationCanceled (int pValveIndex)
void OnValveManipulationEnd (int pValveIndex)
void OnValveManipulationStart (int pValveIndex)
override void OnVariablesSynchronized ()
protected int PackArrayOfBoolStatesIntoBits (array< bool > pStates)
protected void PlayPipeCreakingSoundOnLocation ()
protected void PlayValveManipulationSound ()
void PressureLevelSettings (int pPressureLevel, float pDuration)
protected float PressureLevelToValue (int pPressureLevel)
protected PressureLevelSettings PreviousPressureLevelStageSettings (int pValveIndex, bool pDeanimationRequest=false)
protected WaterLevelSettings PreviousWaterLevelStageSettings (int pValveIndex)
protected void RegisterValve (string pCompName, int pIndex)
protected void ResetState ()
override void SetActions ()
protected void SetDefaultPressureLevelStageSettings (int pValveIndex)
protected void SetLastActiveValve (int pValveIndex)
protected void SetValvePressureLevelGauge (int pValveIndex, float pValue)
protected void SetWaterLevelHeight (float pHeight)
protected void SyncValveVariables ()
protected void TranslateMemoryPointsToWaterLevels ()
protected array< bool > UnpackBitsToArrayOfBoolStates (int pPackedBits, int pArrayLength)
protected float WaterLevelToHeight (int pWaterLevel)
void ~Land_Underground_WaterReservoir ()
Variables
protected const string ANIM_PHASE_VALVE_DRAIN = "Valve1"
protected const string ANIM_PHASE_VALVE_FILL = "Valve2"
protected const string ANIM_PHASE_VALVE_GAUGE_DRAIN = "ValveGauge1"
tighter broken pipe
protected const string ANIM_PHASE_VALVE_GAUGE_FILL = "ValveGauge2"
float Duration
protected ref array< ref PressureLevelSettings > m_DrainValvePressureDeanimationSettings
protected int m_DrainValvePressureLevelStageIndex
protected ref array< ref PressureLevelSettings > m_DrainValvePressureStageSettings
protected int m_DrainValveWaterLevelStageIndex
pointing to specific stage for each valve/pipe
protected ref array< ref WaterLevelSettings > m_DrainValveWaterStageSettings
valve/pipe stages for water and pressure levels
protected ref array< ref PressureLevelSettings > m_FillValvePressureDeanimationSettings
protected int m_FillValvePressureLevelStageIndex
protected ref array< ref PressureLevelSettings > m_FillValvePressureStageSettings
protected int m_FillValveWaterLevelStageIndex
protected ref array< ref WaterLevelSettings > m_FillValveWaterStageSettings
for deanimation purposes
protected int m_LastActiveValve
protected ref ParticleSourceArray m_PipeBrokenParticles
protected bool m_PipeCreakingSoundRequested
protected ref EffectSound m_PipeCreakingSounds
protected ref array< EffectSound > m_PipeSounds
protected bool m_PipeUnderwaterSoundRunning protected ref EffectSound m_PipeUnderwaterSound
protected ref array< bool > m_PressureAnimationRequests
protected ref array< bool > m_PressureDeanimationRequests
protected ref array< float > m_PressureTimesAccumulated
protected Object m_SpawnedWaterObject
protected int m_ValveManipulatedIndex
protected int m_ValveManipulatedIndexPrev
protected ref EffectSound m_ValveManipulationSound
protected bool m_ValveManipulationSoundRequested
VFX/SFX.
protected ref array< string > m_ValveNames
protected ref ParticleSourceArray m_ValveParticles
protected ref array< bool > m_ValveStates
protected int m_ValveStatesPacked
protected int m_ValveStatesPackedPrev
protected int m_WaterLevelActual
protected vector m_WaterLevelDefault
protected float m_WaterLevelHeightActual
protected ref EffectSound m_WaterLevelMovementSound
protected int m_WaterLevelPrev
protected ref map< string, vector > m_WaterLevelsAvailable
protected ref WaterLevelSnapshot m_WaterLevelSnapshot
for deanimation purposes
protected ref array< float > m_WaterLevelTimesAccumulated
class WaterLevelSnapshot OBJECT_NAME_WATER_PLANE = "Land_Underground_WaterReservoir_Water"
protected const int PARTICLE_DRAIN_PIPE_MAX_PRESSURE = ParticleList.WATER_SPILLING
protected const int PARTICLE_FILL_PIPE_JET = ParticleList.WATER_JET
protected const int PARTICLE_FILL_PIPE_JET_WEAK = ParticleList.WATER_JET_WEAK
protected const int PARTICLE_FILL_PIPE_MAX_PRESSURE = ParticleList.WATER_SPILLING
protected const int PIPE_CREAKING_MAX_TIME_DELAY_MS = 15000
protected const int PIPE_CREAKING_MIN_TIME_DELAY_MS = 10000
protected const string PIPE_CREAKING_SOUND_LOCATIONS [PIPE_CREAKING_SOUND_LOCATIONS_COUNT]
protected const int PIPE_CREAKING_SOUND_LOCATIONS_COUNT = 4
protected const int PIPE_INDEX_BROKEN1 = 0
protected const int PIPE_INDEX_BROKEN2 = 1
main broken pipe
protected const string PIPE_NAME_BROKEN1 = "pipe_broken_1"
protected const string PIPE_NAME_BROKEN2 = "pipe_broken_2"
protected const string PIPE_NAME_LEAKING_DRAIN = "pipe_leaking_1"
protected const string PIPE_NAME_LEAKING_FILL = "pipe_leaking_2"
protected const int PIPES_BROKEN_COUNT = 2
protected const int PL_AVERAGE = 1
protected const int PL_MAX = 2
protected const int PL_MIN = 0
class WaterLevelSettings PressureLevel
protected const string SOUND_NAME_PIPE_CREAKING = "WaterObjectUndergroundPipeCreaking_SoundSet"
protected const string SOUND_NAME_PIPE_SPRINKLING_END = "WaterObjectUndergroundPipeSprinkling_End_SoundSet"
protected const string SOUND_NAME_PIPE_SPRINKLING_LOOP1 = "WaterObjectUndergroundPipeSprinkling_Loop1_SoundSet"
protected const string SOUND_NAME_PIPE_SPRINKLING_LOOP2 = "WaterObjectUndergroundPipeSprinkling_Loop2_SoundSet"
protected const string SOUND_NAME_PIPE_SPRINKLING_START = "WaterObjectUndergroundPipeSprinkling_Start_SoundSet"
protected const string SOUND_NAME_UPIPE_SPRINKLING_END = "WaterObjectUndergroundUnderwaterPipe_End_SoundSet"
protected const string SOUND_NAME_UPIPE_SPRINKLING_LOOP = "WaterObjectUndergroundUnderwaterPipe_Loop_SoundSet"
protected const string SOUND_NAME_UPIPE_SPRINKLING_START = "WaterObjectUndergroundUnderwaterPipe_Start_SoundSet"
protected const string SOUND_NAME_VALVE_MANIPULATION = "WaterObjectUndergroundValve_SoundSet"
protected const string SOUND_NAME_WATER_DRAIN_LOOP = "WaterObjectUndergroundUnderwaterEmpty_Loop_SoundSet"
protected const string SOUND_NAME_WATER_FILL_LOOP = "WaterObjectUndergroundUnderwaterFill_Loop_SoundSet"
protected const int VALVE_INDEX_DRAIN = 0
protected const int VALVE_INDEX_FILL = 1
protected const string VALVE_NAME_DRAIN = "valve1"
protected const string VALVE_NAME_FILL = "valve2"
protected const int VALVES_COUNT = 2
static protected const string WATER_LEVEL_ABOVE_PIPES = "water_level_above_pipes"
static protected const string WATER_LEVEL_AVERAGE = "water_level_average"
static protected const string WATER_LEVEL_MAX = "water_level_max"
static protected const string WATER_LEVEL_MIN = "water_level_min"
protected const string WATER_LEVELS [WATER_LEVELS_COUNT]
protected const int WATER_LEVELS_COUNT = 4
protected const int WL_ABOVE_PIPES = 1
protected const int WL_AVERAGE = 2
protected const int WL_MAX = 3
protected const int WL_MIN = 0
Function Documentation
ActualPressureLevelStageSettings()
protected PressureLevelSettings ActualPressureLevelStageSettings (int pValveIndex, bool pDeanimationRequest = false)
Definition at line 776 of file land_underground_waterreservoir.c.
    {
        PressureLevelSettings plStageSettings;
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            if (pDeanimationRequest)
            {
                plStageSettings = m_DrainValvePressureDeanimationSettings[1];
                return plStageSettings;
            }
            plStageSettings = m_DrainValvePressureStageSettings.Get(m_DrainValvePressureLevelStageIndex);
        break;
        case VALVE_INDEX_FILL:
            if (pDeanimationRequest)
            {
                plStageSettings = m_FillValvePressureDeanimationSettings[1];
                return plStageSettings;
            }
            plStageSettings = m_FillValvePressureStageSettings.Get(m_FillValvePressureLevelStageIndex);
        break;
        }
        return plStageSettings;
    }
References m_DrainValvePressureDeanimationSettings, m_DrainValvePressureLevelStageIndex, m_DrainValvePressureStageSettings, m_FillValvePressureDeanimationSettings, m_FillValvePressureLevelStageIndex, m_FillValvePressureStageSettings, PressureLevelSettings(), VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
ActualWaterLevelStageSettings()
protected WaterLevelSettings ActualWaterLevelStageSettings (int pValveIndex)
Definition at line 689 of file land_underground_waterreservoir.c.
    {
        WaterLevelSettings wlStageSettings;
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            wlStageSettings = m_DrainValveWaterStageSettings.Get(m_DrainValveWaterLevelStageIndex);
        break;
        case VALVE_INDEX_FILL:
            wlStageSettings = m_FillValveWaterStageSettings.Get(m_FillValveWaterLevelStageIndex);
        break;
        }
        return wlStageSettings;
    }
References m_DrainValveWaterLevelStageIndex, m_DrainValveWaterStageSettings, m_FillValveWaterLevelStageIndex, m_FillValveWaterStageSettings, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
AdjustTime()
protected float AdjustTime (float originalTime)
Definition at line 901 of file land_underground_waterreservoir.c.
    {
        #ifdef DEVELOPER
        float timeAccel = 1;
        if (FeatureTimeAccel.GetFeatureTimeAccelEnabled(ETimeAccelCategories.UNDERGROUND_RESERVOIR))
        {
            timeAccel = FeatureTimeAccel.GetFeatureTimeAccelValue();
            return originalTime * timeAccel;
        }
        #endif
        return originalTime;
    }
Referenced by EOnPostSimulate().
AdvanceToNextPressureLevelStageSettings()
protected void AdvanceToNextPressureLevelStageSettings (int pValveIndex)
Definition at line 805 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            if (m_DrainValvePressureLevelStageIndex < m_DrainValvePressureStageSettings.Count() - 1)
            {
                m_DrainValvePressureLevelStageIndex++;
            }
            else
            {
                m_DrainValvePressureLevelStageIndex = 0;
            }
        break;
        case VALVE_INDEX_FILL:
            if (m_FillValvePressureLevelStageIndex < m_FillValvePressureStageSettings.Count() - 1)
            {
                m_FillValvePressureLevelStageIndex++;
            }
            else
            {
                m_FillValvePressureLevelStageIndex = 0;
            }
        break;
        }
    }
References m_DrainValvePressureLevelStageIndex, m_DrainValvePressureStageSettings, m_FillValvePressureLevelStageIndex, m_FillValvePressureStageSettings, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
AdvanceToNextWaterLevelStageSettings()
protected void AdvanceToNextWaterLevelStageSettings (int pValveIndex)
Definition at line 706 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            if (m_DrainValveWaterLevelStageIndex < m_DrainValveWaterStageSettings.Count() - 1)
            {
                m_DrainValveWaterLevelStageIndex++;
            }
            else
            {
                m_DrainValveWaterLevelStageIndex = 0;
            }
        break;
        case VALVE_INDEX_FILL:
            if (m_FillValveWaterLevelStageIndex < m_FillValveWaterStageSettings.Count() - 1)
            {
                m_FillValveWaterLevelStageIndex++;
            }
            else
            {
                m_FillValveWaterLevelStageIndex = 0;
            }
        break;
        }
    }
References m_DrainValveWaterLevelStageIndex, m_DrainValveWaterStageSettings, m_FillValveWaterLevelStageIndex, m_FillValveWaterStageSettings, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
AnimateValve()
protected void AnimateValve (int pValveIndex, float pPhase)
Definition at line 845 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            SetAnimationPhase(ANIM_PHASE_VALVE_DRAIN, pPhase);
        break;
        case VALVE_INDEX_FILL:
            SetAnimationPhase(ANIM_PHASE_VALVE_FILL, pPhase);
        break;
        }
    }
References ANIM_PHASE_VALVE_DRAIN, ANIM_PHASE_VALVE_FILL, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by OnValveManipulationCanceled(), OnValveManipulationEnd(), and OnValveManipulationStart().
CleanSoundEffects()
protected void CleanSoundEffects ()
Definition at line 1084 of file land_underground_waterreservoir.c.
    {
        SEffectManager.DestroySound(m_PipeSounds[VALVE_INDEX_DRAIN]);
        SEffectManager.DestroySound(m_PipeSounds[VALVE_INDEX_FILL]);
    }
References SEffectManager::DestroySound(), m_PipeSounds, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by ResetState(), and ~Land_Underground_WaterReservoir().
CleanVisualEffects()
protected void CleanVisualEffects ()
Definition at line 1175 of file land_underground_waterreservoir.c.
    {
        for (int valve = 0; valve < VALVES_COUNT; ++valve)
        {
            if (m_ValveParticles[valve])
            {
                m_ValveParticles[valve].StopParticle();
                m_ValveParticles[valve] = null;
            }
        }
        for (int pipe = 0; pipe < m_PipeBrokenParticles.Count(); ++pipe)
        {
            if (m_PipeBrokenParticles[pipe])
            {
                m_PipeBrokenParticles[pipe].StopParticle();
                m_PipeBrokenParticles[pipe] = null;
            }
        }
    }
References m_PipeBrokenParticles, m_ValveParticles, and VALVES_COUNT.
Referenced by ~Land_Underground_WaterReservoir().
ConfigureValvesAndGaugesCourse()
protected void ConfigureValvesAndGaugesCourse ()
drain - water level
drain - pressure
for deanimation purposes only while valves activation overllaps
fill - water level
fill - pressure
for deanimation purposes only while valves activation overllaps
Definition at line 410 of file land_underground_waterreservoir.c.
    {
        m_DrainValveWaterStageSettings.Insert(new WaterLevelSettings(WL_AVERAGE, -1.0));
        m_DrainValveWaterStageSettings.Insert(new WaterLevelSettings(WL_MIN, 40.0));
        m_DrainValveWaterStageSettings.Insert(new WaterLevelSettings(WL_MIN, 200.0));
        m_DrainValveWaterStageSettings.Insert(new WaterLevelSettings(WL_AVERAGE, 360.0));
        m_DrainValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MIN, -1.0));
        m_DrainValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MAX, 40.0));
        m_DrainValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MAX, 200.0));
        m_DrainValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MIN, 360.0));
        m_DrainValvePressureDeanimationSettings.Insert(new PressureLevelSettings(PL_AVERAGE, -1));
        m_DrainValvePressureDeanimationSettings.Insert(new PressureLevelSettings(PL_MIN, 5.0));
        m_FillValveWaterStageSettings.Insert(new WaterLevelSettings(WL_AVERAGE, -1.0));
        m_FillValveWaterStageSettings.Insert(new WaterLevelSettings(WL_MAX, 40.0));
        m_FillValveWaterStageSettings.Insert(new WaterLevelSettings(WL_MAX, 100.0));
        m_FillValveWaterStageSettings.Insert(new WaterLevelSettings(WL_AVERAGE, 40.0));
        m_FillValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MAX, -1.0));
        m_FillValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MIN, 40.0));
        m_FillValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MIN, 100.0));
        m_FillValvePressureStageSettings.Insert(new PressureLevelSettings(PL_MAX, 40.0));
        m_FillValvePressureDeanimationSettings.Insert(new PressureLevelSettings(PL_AVERAGE, -1.0));
        m_FillValvePressureDeanimationSettings.Insert(new PressureLevelSettings(PL_MAX, 5.0));
    }
References m_DrainValvePressureDeanimationSettings, m_DrainValvePressureStageSettings, m_DrainValveWaterStageSettings, m_FillValvePressureDeanimationSettings, m_FillValvePressureStageSettings, m_FillValveWaterStageSettings, PL_AVERAGE, PL_MAX, PL_MIN, PressureLevelSettings(), WL_AVERAGE, WL_MAX, and WL_MIN.
Referenced by LateInit().
EOnPostSimulate()
override void EOnPostSimulate (IEntity other, float timeSlice)
In case where one of the valves is already running
snapshot values; stop animation of that valve and continue with newly requested
will force that valve to start deanimation of gauge
water level course and animation
stay on the same level
pressure course and animation
stay on the same level
end of deanimation - overlapped activation of valves
Definition at line 166 of file land_underground_waterreservoir.c.
    {
        #ifndef SERVER
        HandleSoundEffects();
        HandleVisualEffects();
        #endif
        if (!GetGame().IsServer())
        {
            return;
        }
        int valve;
        float waterHeight, pressureLevel;
        WaterLevelSettings wlStageSettings, wlStageSettingsPrev;
        PressureLevelSettings plStageSettings, plStageSettingsPrev;
        for (valve = 0; valve < VALVES_COUNT; ++valve)
        {
            if (m_LastActiveValve != INDEX_NOT_FOUND && m_LastActiveValve != valve && m_ValveStates[valve] == true)
            {
                wlStageSettings                         = ActualWaterLevelStageSettings(valve);
                m_WaterLevelSnapshot                    = new WaterLevelSnapshot();
                m_WaterLevelSnapshot.WaterHeight        = m_WaterLevelHeightActual;
                m_WaterLevelSnapshot.RemainingDuration  = Math.Clamp(wlStageSettings.Duration - m_WaterLevelTimesAccumulated[valve], 0, wlStageSettings.Duration);
                m_ValveStates[valve]                    = false;
                m_PressureDeanimationRequests[valve]    = true;
                break;
            }
        }
        for (valve = 0; valve < VALVES_COUNT; ++valve)
        {
            if (m_ValveStates[valve] == true)
            {
                wlStageSettingsPrev = PreviousWaterLevelStageSettings(valve);
                wlStageSettings     = ActualWaterLevelStageSettings(valve);
                if (wlStageSettings.Duration == -1.0)
                {
                    m_ValveStates[valve]                = false;
                    m_WaterLevelTimesAccumulated[valve] = 0;
                    m_WaterLevelSnapshot                = null;
                    SyncValveVariables();
                    return;
                }
                float adjustedWaterHeight   = WaterLevelToHeight(wlStageSettingsPrev.WaterLevel);
                float adjustedDuration      = wlStageSettings.Duration;
                if (m_WaterLevelSnapshot)
                {
                    adjustedWaterHeight = m_WaterLevelSnapshot.WaterHeight;
                    adjustedDuration    = wlStageSettings.Duration + m_WaterLevelSnapshot.RemainingDuration;
                }
                if (m_WaterLevelTimesAccumulated[valve] <= adjustedDuration)
                {
                    float start     = adjustedWaterHeight;
                    float target    = WaterLevelToHeight(wlStageSettings.WaterLevel);
                    waterHeight     = Math.Lerp(start, target, Easing.EaseInOutSine(m_WaterLevelTimesAccumulated[valve] / adjustedDuration));
                    SetWaterLevelHeight(waterHeight);
                }
                else
                {
                    m_WaterLevelTimesAccumulated[valve] = 0;
                    m_WaterLevelSnapshot                = null;
                    AdvanceToNextWaterLevelStageSettings(valve);
                    SetSynchDirty();
                }
                m_WaterLevelTimesAccumulated[valve] = m_WaterLevelTimesAccumulated[valve] + AdjustTime(timeSlice);
            }
            else
            {
                m_WaterLevelTimesAccumulated[valve] = 0;
                SyncValveVariables();
            }
        }
        int allValvesStates = 0;
        for (valve = 0; valve < VALVES_COUNT; ++valve)
        {
            if (m_PressureAnimationRequests[valve] == true)
            {
                bool hasToBeDeanimated  = m_PressureAnimationRequests[valve] == m_PressureDeanimationRequests[valve];
                plStageSettingsPrev     = PreviousPressureLevelStageSettings(valve, hasToBeDeanimated);
                plStageSettings         = ActualPressureLevelStageSettings(valve, hasToBeDeanimated);
                if (plStageSettings.Duration == -1.0)
                {
                    m_PressureTimesAccumulated[valve]   = 0;
                    m_PressureAnimationRequests[valve]  = false;
                    SyncValveVariables();
                    return;
                }
                if (m_PressureTimesAccumulated[valve] <= plStageSettings.Duration)
                {
                    float plStart   = PressureLevelToValue(plStageSettingsPrev.PressureLevel);
                    float plTarget  = PressureLevelToValue(plStageSettings.PressureLevel);
                    pressureLevel   = Math.Lerp(plStart, plTarget, m_PressureTimesAccumulated[valve] / plStageSettings.Duration);
                    SetValvePressureLevelGauge(valve, pressureLevel);
                }
                else
                {
                    m_PressureTimesAccumulated[valve] = 0;
                    if (hasToBeDeanimated && IsValvePressureLevelGaugeAtBase(valve))
                    {
                        m_PressureDeanimationRequests[valve] = false;
                        SetDefaultPressureLevelStageSettings(valve);
                    }
                    else
                    {
                        AdvanceToNextPressureLevelStageSettings(valve);
                        SetSynchDirty();
                    }
                }
                m_PressureTimesAccumulated[valve] = m_PressureTimesAccumulated[valve] + AdjustTime(timeSlice);
            }
            else
            {
                m_PressureTimesAccumulated[valve] = 0;
            }
            allValvesStates += m_PressureAnimationRequests[valve];
            if (allValvesStates == false)
            {
                SyncValveVariables();
            }
        }
    }
References ActualPressureLevelStageSettings(), ActualWaterLevelStageSettings(), AdjustTime(), AdvanceToNextPressureLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), Math::Clamp(), WaterLevelSettings::Duration, Easing::EaseInOutSine(), GetGame(), HandleSoundEffects(), HandleVisualEffects(), INDEX_NOT_FOUND, IsValvePressureLevelGaugeAtBase(), Math::Lerp(), m_LastActiveValve, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_ValveStates, m_WaterLevelHeightActual, m_WaterLevelSnapshot, m_WaterLevelTimesAccumulated, PressureLevelSettings(), PressureLevelToValue(), PreviousPressureLevelStageSettings(), PreviousWaterLevelStageSettings(), WaterLevelSnapshot::RemainingDuration, SetDefaultPressureLevelStageSettings(), SetValvePressureLevelGauge(), SetWaterLevelHeight(), SyncValveVariables(), VALVES_COUNT, WaterLevelSnapshot::WaterHeight, WaterLevelSettings::WaterLevel, and WaterLevelToHeight().
GetMemoryPointPosition()
protected vector GetMemoryPointPosition (string pMemoryPoint)
Definition at line 914 of file land_underground_waterreservoir.c.
    {
        vector pos = vector.Zero;
        if (MemoryPointExists(pMemoryPoint))
        {
            pos = GetMemoryPointPos(pMemoryPoint);
            pos = ModelToWorld(pos);
        }
        else
        {
            ErrorEx(string.Format("Memory point %1 not found, falling back to vector.Zero", pMemoryPoint));
        }
        return pos;
    }
References ErrorEx, GetMemoryPointPos(), MemoryPointExists(), ModelToWorld(), and vector::Zero.
Referenced by GetValveAligningPointsWS(), and HandleVisualEffects().
GetTurnableValveIndex()
override int GetTurnableValveIndex (int pComponentIndex)
Definition at line 468 of file land_underground_waterreservoir.c.
    {
        string targetedValveName = GetActionComponentName(pComponentIndex);
        for (int i = 0; i < m_ValveNames.Count(); ++i)
        {
            if (m_ValveNames[i] == targetedValveName)
            {
                return i;
            }
        }
        return INDEX_NOT_FOUND;
    }
References GetActionComponentName(), INDEX_NOT_FOUND, and m_ValveNames.
GetValveAligningPointsWS()
array< vector > GetValveAligningPointsWS (int pValveIndex)
for the animation aligning returns data in order: start point; direction point
Definition at line 532 of file land_underground_waterreservoir.c.
    {
        vector posPoint, dirPoint = vector.Zero;
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            posPoint = GetMemoryPointPosition(string.Format("%1_align_pos", VALVE_NAME_DRAIN));
            dirPoint = GetMemoryPointPosition(string.Format("%1_align_dir", VALVE_NAME_DRAIN));
        break;
        case VALVE_INDEX_FILL:
            posPoint = GetMemoryPointPosition(string.Format("%1_align_pos", VALVE_NAME_FILL));
            dirPoint = GetMemoryPointPosition(string.Format("%1_align_dir", VALVE_NAME_FILL));
        break;
        }
        array<vector> valvePositions = new array<vector>();
        valvePositions.Insert(posPoint);
        valvePositions.Insert(dirPoint);
        return valvePositions;
    }
References GetMemoryPointPosition(), VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, VALVE_NAME_DRAIN, VALVE_NAME_FILL, and vector::Zero.
GetValvePressureLevelGauge()
protected float GetValvePressureLevelGauge (int pValveIndex)
Definition at line 871 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            return GetAnimationPhase(ANIM_PHASE_VALVE_GAUGE_DRAIN);
        break;
        case VALVE_INDEX_FILL:
            return GetAnimationPhase(ANIM_PHASE_VALVE_GAUGE_FILL);
        break;
        }
        return 0;
    }
References ANIM_PHASE_VALVE_GAUGE_DRAIN, ANIM_PHASE_VALVE_GAUGE_FILL, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by HandleSoundEffectsPipeSprinkling(), HandleVisualEffects(), and IsValvePressureLevelGaugeAtBase().
HandleSoundEffects()
protected void HandleSoundEffects ()
Definition at line 931 of file land_underground_waterreservoir.c.
    {
        HandleSoundEffectsPipeCreaking();
        HandleSoundEffectsPipeSprinkling();
        HandleSoundEffectsUnderwaterPipeSounds();
        HandleSoundEffectsWaterLevelMovementSounds();
    }
References HandleSoundEffectsPipeCreaking(), HandleSoundEffectsPipeSprinkling(), HandleSoundEffectsUnderwaterPipeSounds(), and HandleSoundEffectsWaterLevelMovementSounds().
Referenced by EOnPostSimulate().
HandleSoundEffectsPipeCreaking()
protected void HandleSoundEffectsPipeCreaking ()
Definition at line 952 of file land_underground_waterreservoir.c.
    {
        if (IsAnyValveActive())
        {
            if ((m_PipeCreakingSounds == null && !m_PipeCreakingSoundRequested) || !m_PipeCreakingSoundRequested)
            {
                m_PipeCreakingSoundRequested = true;
                int randomDelay = Math.RandomInt(PIPE_CREAKING_MIN_TIME_DELAY_MS, PIPE_CREAKING_MAX_TIME_DELAY_MS);
                GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(PlayPipeCreakingSoundOnLocation, randomDelay, false);
            }
        }
        else
        {
            if (m_PipeCreakingSounds)
            {
                StopSoundSet(m_PipeCreakingSounds);
                m_PipeCreakingSounds = null;
            }
        }
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), IsAnyValveActive(), m_PipeCreakingSoundRequested, m_PipeCreakingSounds, PIPE_CREAKING_MAX_TIME_DELAY_MS, PIPE_CREAKING_MIN_TIME_DELAY_MS, PlayPipeCreakingSoundOnLocation(), Math::RandomInt(), and StopSoundSet().
Referenced by HandleSoundEffects().
HandleSoundEffectsPipeSprinkling()
protected void HandleSoundEffectsPipeSprinkling ()
Definition at line 973 of file land_underground_waterreservoir.c.
    {
        if (!m_PipeSounds || m_PipeSounds.Count() == 0)
        {
            return;
        }
        EffectSound sndDrain, sndFill;
        float drainPressureLevel = GetValvePressureLevelGauge(VALVE_INDEX_DRAIN);
        if (drainPressureLevel >= 0.4 && drainPressureLevel < 0.8)
        {
            if (m_PipeSounds[VALVE_INDEX_DRAIN] == null)
            {
                PlaySoundSetAtMemoryPoint(sndDrain, SOUND_NAME_PIPE_SPRINKLING_START, VALVE_NAME_DRAIN, false, 0.0, 0.5);
                m_PipeSounds[VALVE_INDEX_DRAIN] = sndDrain;
                StopSoundSet(m_PipeSounds[VALVE_INDEX_DRAIN]);
                m_PipeSounds[VALVE_INDEX_DRAIN] = null;
                PlaySoundSetAtMemoryPointLooped(sndDrain, SOUND_NAME_PIPE_SPRINKLING_LOOP1, VALVE_NAME_DRAIN, 0.5, 0.5);
                m_PipeSounds[VALVE_INDEX_DRAIN] = sndDrain;
            }
        }
        if (drainPressureLevel < 0.4)
        {
            if (m_PipeSounds[VALVE_INDEX_DRAIN] != null)
            {
                StopSoundSet(m_PipeSounds[VALVE_INDEX_DRAIN]);
                m_PipeSounds[VALVE_INDEX_DRAIN] = null;
            }
        }
        float fillPressureLevel = GetValvePressureLevelGauge(VALVE_INDEX_FILL);
        if (fillPressureLevel >= 0.4)
        {
            if (m_PipeSounds[VALVE_INDEX_FILL] == null)
            {
                PlaySoundSetAtMemoryPoint(sndFill, SOUND_NAME_PIPE_SPRINKLING_START, VALVE_NAME_FILL, false, 0.0, 0.5);
                StopSoundSet(m_PipeSounds[VALVE_INDEX_FILL]);
                m_PipeSounds[VALVE_INDEX_FILL] = null;
                PlaySoundSetAtMemoryPointLooped(sndFill, SOUND_NAME_PIPE_SPRINKLING_LOOP2, VALVE_NAME_FILL, 0.5, 0.5);
                m_PipeSounds[VALVE_INDEX_FILL] = sndFill;
            }
        }
        if (fillPressureLevel < 0.4)
        {
            if (m_PipeSounds[VALVE_INDEX_FILL] != null)
            {
                StopSoundSet(m_PipeSounds[VALVE_INDEX_FILL]);
                m_PipeSounds[VALVE_INDEX_FILL] = null;
            }
        }
    }
References GetValvePressureLevelGauge(), m_PipeSounds, PlaySoundSetAtMemoryPoint(), PlaySoundSetAtMemoryPointLooped(), SOUND_NAME_PIPE_SPRINKLING_LOOP1, SOUND_NAME_PIPE_SPRINKLING_LOOP2, SOUND_NAME_PIPE_SPRINKLING_START, StopSoundSet(), VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, VALVE_NAME_DRAIN, and VALVE_NAME_FILL.
Referenced by HandleSoundEffects().
HandleSoundEffectsUnderwaterPipeSounds()
protected void HandleSoundEffectsUnderwaterPipeSounds ()
strong water jet sound only when fill valve activated
Definition at line 1029 of file land_underground_waterreservoir.c.
    {
        if (IsValveActive(VALVE_INDEX_FILL))
        {
            if ((m_WaterLevelActual == WL_ABOVE_PIPES) || (m_WaterLevelActual == WL_MAX && m_WaterLevelPrev == WL_AVERAGE))
            {
                if (m_PipeUnderwaterSound == null)
                {
                    PlaySoundSetAtMemoryPoint(m_PipeUnderwaterSound, SOUND_NAME_UPIPE_SPRINKLING_START, PIPE_NAME_BROKEN1, false, 0.0, 0.5);
                    StopSoundSet(m_PipeUnderwaterSound);
                    m_PipeUnderwaterSound = null;
                    m_PipeUnderwaterSoundRunning = PlaySoundSetAtMemoryPointLooped(m_PipeUnderwaterSound, SOUND_NAME_UPIPE_SPRINKLING_LOOP, PIPE_NAME_BROKEN1, 0.0, 0.5);
                }
            }
            else if (m_WaterLevelActual == m_WaterLevelPrev)
            {
                if (m_PipeUnderwaterSound)
                {
                    StopSoundSet(m_PipeUnderwaterSound);
                    if (m_PipeUnderwaterSoundRunning)
                    {
                        PlaySoundSetAtMemoryPoint(m_PipeUnderwaterSound, SOUND_NAME_UPIPE_SPRINKLING_END, PIPE_NAME_BROKEN1, false, 0.0, 0.5);
                        m_PipeUnderwaterSoundRunning = false;
                    }
                }
            }
        }
    }
References IsValveActive(), m_PipeUnderwaterSound, m_WaterLevelActual, m_WaterLevelPrev, PIPE_NAME_BROKEN1, PlaySoundSetAtMemoryPoint(), PlaySoundSetAtMemoryPointLooped(), SOUND_NAME_UPIPE_SPRINKLING_END, SOUND_NAME_UPIPE_SPRINKLING_LOOP, SOUND_NAME_UPIPE_SPRINKLING_START, StopSoundSet(), VALVE_INDEX_FILL, WL_ABOVE_PIPES, WL_AVERAGE, and WL_MAX.
Referenced by HandleSoundEffects().
HandleSoundEffectsWaterLevelMovementSounds()
protected void HandleSoundEffectsWaterLevelMovementSounds ()
Definition at line 1059 of file land_underground_waterreservoir.c.
    {
        if (m_WaterLevelActual < m_WaterLevelPrev)
        {
            if (m_WaterLevelMovementSound == null)
            {
                PlaySoundSetAtMemoryPointLooped(m_WaterLevelMovementSound, SOUND_NAME_WATER_DRAIN_LOOP, PIPE_NAME_BROKEN1, 0.0, 0.5);
            }
        }
        else if (m_WaterLevelActual > m_WaterLevelPrev)
        {
            if (m_WaterLevelMovementSound == null)
            {
                PlaySoundSetAtMemoryPointLooped(m_WaterLevelMovementSound, SOUND_NAME_WATER_FILL_LOOP, PIPE_NAME_BROKEN1, 0.0, 0.5);
            }
        }
        else if (m_WaterLevelActual == m_WaterLevelPrev)
        {
            if (m_WaterLevelMovementSound)
            {
                StopSoundSet(m_WaterLevelMovementSound);
            }
        }
    }
References m_WaterLevelActual, m_WaterLevelMovementSound, m_WaterLevelPrev, PIPE_NAME_BROKEN1, PlaySoundSetAtMemoryPointLooped(), SOUND_NAME_WATER_DRAIN_LOOP, SOUND_NAME_WATER_FILL_LOOP, and StopSoundSet().
Referenced by HandleSoundEffects().
HandleVisualEffects()
protected void HandleVisualEffects ()
strong jet stream particle only when fill valve activated
we don't need the weak jet stream
weak jet stream
Definition at line 1097 of file land_underground_waterreservoir.c.
    {
        if (GetValvePressureLevelGauge(VALVE_INDEX_DRAIN) >= 0.4)
        {
            if (m_ValveParticles[VALVE_INDEX_DRAIN] == null)
            {
                m_ValveParticles[VALVE_INDEX_DRAIN] = ParticleManager.GetInstance().PlayInWorldEx(PARTICLE_DRAIN_PIPE_MAX_PRESSURE, null, GetMemoryPointPosition(PIPE_NAME_LEAKING_DRAIN), GetOrientation() + "0 -90 165", true);
            }
        }
        if (GetValvePressureLevelGauge(VALVE_INDEX_DRAIN) <= 0.4)
        {
            if (m_ValveParticles[VALVE_INDEX_DRAIN] != null)
            {
                m_ValveParticles[VALVE_INDEX_DRAIN].StopParticle();
                m_ValveParticles[VALVE_INDEX_DRAIN] = null;
            }
        }
        if (GetValvePressureLevelGauge(VALVE_INDEX_FILL) >= 0.4)
        {
            if (m_ValveParticles[VALVE_INDEX_FILL] == null)
            {
                m_ValveParticles[VALVE_INDEX_FILL] = ParticleManager.GetInstance().PlayInWorldEx(PARTICLE_FILL_PIPE_MAX_PRESSURE, null, GetMemoryPointPosition(PIPE_NAME_LEAKING_FILL), GetOrientation() + "0 90 -90", true);
            }
        }
        if (GetValvePressureLevelGauge(VALVE_INDEX_FILL) <= 0.4)
        {
            if (m_ValveParticles[VALVE_INDEX_FILL] != null)
            {
                m_ValveParticles[VALVE_INDEX_FILL].StopParticle();
                m_ValveParticles[VALVE_INDEX_FILL] = null;
            }
        }
        if (IsValveActive(VALVE_INDEX_FILL))
        {
            if ((m_WaterLevelActual == WL_ABOVE_PIPES) || (m_WaterLevelActual == WL_MAX && m_WaterLevelPrev == WL_AVERAGE))
            {
                if (m_PipeBrokenParticles[PIPE_INDEX_BROKEN1] == null)
                {
                    m_PipeBrokenParticles[PIPE_INDEX_BROKEN1] = ParticleManager.GetInstance().PlayInWorldEx(PARTICLE_FILL_PIPE_JET, null, GetMemoryPointPosition(PIPE_NAME_BROKEN1), GetOrientation() + "0 0 0", true);
                }
                if (m_PipeBrokenParticles[PIPE_INDEX_BROKEN2])
                {
                    m_PipeBrokenParticles[PIPE_INDEX_BROKEN2].StopParticle();
                    m_PipeBrokenParticles[PIPE_INDEX_BROKEN2] = null;
                }
            }
        }
        if ((m_WaterLevelActual == WL_ABOVE_PIPES && m_WaterLevelPrev == WL_AVERAGE))
        {
            if (m_PipeBrokenParticles[PIPE_INDEX_BROKEN2] == null)
            {
                m_PipeBrokenParticles[PIPE_INDEX_BROKEN2] = ParticleManager.GetInstance().PlayInWorldEx(PARTICLE_FILL_PIPE_JET_WEAK, null, GetMemoryPointPosition(PIPE_NAME_BROKEN2), GetOrientation() + "0 0 0", true);
            }
        }
        if (m_WaterLevelActual >= WL_AVERAGE)
        {
            for (int pipe = 0; pipe < m_PipeBrokenParticles.Count(); ++pipe)
            {
                if (m_PipeBrokenParticles[pipe])
                {
                    m_PipeBrokenParticles[pipe].StopParticle();
                    m_PipeBrokenParticles[pipe] = null;
                }
            }
        }
    }
References GetMemoryPointPosition(), GetOrientation(), GetValvePressureLevelGauge(), IsValveActive(), m_PipeBrokenParticles, m_ValveParticles, m_WaterLevelActual, m_WaterLevelPrev, PARTICLE_DRAIN_PIPE_MAX_PRESSURE, PARTICLE_FILL_PIPE_JET, PARTICLE_FILL_PIPE_JET_WEAK, PARTICLE_FILL_PIPE_MAX_PRESSURE, ParticleManager(), PIPE_INDEX_BROKEN1, PIPE_INDEX_BROKEN2, PIPE_NAME_BROKEN1, PIPE_NAME_BROKEN2, PIPE_NAME_LEAKING_DRAIN, PIPE_NAME_LEAKING_FILL, VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, WL_ABOVE_PIPES, WL_AVERAGE, and WL_MAX.
Referenced by EOnPostSimulate().
HasTurnableValveBehavior()
override bool HasTurnableValveBehavior ()
Definition at line 328 of file land_underground_waterreservoir.c.
    {
        return true;
    }
HeightToWaterLevel()
protected int HeightToWaterLevel (float pHeight)
Definition at line 618 of file land_underground_waterreservoir.c.
    {
        if (pHeight <= m_WaterLevelsAvailable[WATER_LEVEL_MIN][1])
        {
            return WL_MIN;
        }
        else if (pHeight > m_WaterLevelsAvailable[WATER_LEVEL_MIN][1] && pHeight <= m_WaterLevelsAvailable[WATER_LEVEL_ABOVE_PIPES][1])
        {
            return WL_ABOVE_PIPES;
        }
        else if (pHeight > m_WaterLevelsAvailable[WATER_LEVEL_ABOVE_PIPES][1] && pHeight <= m_WaterLevelsAvailable[WATER_LEVEL_AVERAGE][1])
        {
            return WL_AVERAGE;
        }
        else if (pHeight < m_WaterLevelsAvailable[WATER_LEVEL_MAX][1] && pHeight >= m_WaterLevelsAvailable[WATER_LEVEL_AVERAGE][1])
        {
            return WL_AVERAGE;
        }
        return WL_MAX;
    }
References m_WaterLevelsAvailable, WATER_LEVEL_ABOVE_PIPES, WATER_LEVEL_AVERAGE, WATER_LEVEL_MAX, WATER_LEVEL_MIN, WL_ABOVE_PIPES, WL_AVERAGE, WL_MAX, and WL_MIN.
Referenced by SetWaterLevelHeight().
Init()
protected void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 333 of file land_underground_waterreservoir.c.
    {
        m_ValveNames                            = new array<string>();
        m_ValveStates                           = new array<bool>();
        m_PressureAnimationRequests             = new array<bool>();
        m_PressureDeanimationRequests           = new array<bool>();
        m_WaterLevelTimesAccumulated            = new array<float>();
        m_PressureTimesAccumulated              = new array<float>();
        m_WaterLevelsAvailable                  = new map<string, vector>();
        m_DrainValveWaterStageSettings          = new array<ref WaterLevelSettings>();
        m_DrainValvePressureStageSettings       = new array<ref PressureLevelSettings>();
        m_DrainValvePressureDeanimationSettings = new array<ref PressureLevelSettings>();
        m_FillValveWaterStageSettings           = new array<ref WaterLevelSettings>();
        m_FillValvePressureStageSettings        = new array<ref PressureLevelSettings>();
        m_FillValvePressureDeanimationSettings  = new array<ref PressureLevelSettings>();
        m_WaterLevelSnapshot                    = null;
        m_WaterLevelActual                      = WL_AVERAGE;
        m_WaterLevelPrev                        = WL_AVERAGE;
        m_LastActiveValve                       = INDEX_NOT_FOUND;
        m_ValveManipulatedIndex                 = -1;
        m_ValveManipulatedIndexPrev             = -1;
        m_PipeSounds                            = new array<EffectSound>();
        m_ValveParticles                        = new ParticleSourceArray();
        m_PipeBrokenParticles                   = new ParticleSourceArray();
        int i = 0;
        for (i = 0; i < VALVES_COUNT; ++i)
        {
            m_ValveNames.Insert("none");
            m_ValveStates.Insert(false);
            m_PressureAnimationRequests.Insert(false);
            m_PressureDeanimationRequests.Insert(false);
            m_WaterLevelTimesAccumulated.Insert(-1);
            m_PressureTimesAccumulated.Insert(-1);
            m_PipeSounds.Insert(null);
            m_ValveParticles.Insert(null);
        }
        for (i = 0; i < PIPES_BROKEN_COUNT; ++i)
        {
            m_PipeBrokenParticles.Insert(null);
        }
        RegisterNetSyncVariableInt("m_ValveStatesPacked", 0);
        RegisterNetSyncVariableInt("m_ValveManipulatedIndex", -1, VALVES_COUNT - 1);
        RegisterNetSyncVariableInt("m_WaterLevelActual", WL_MIN, WL_MAX);
        RegisterNetSyncVariableInt("m_WaterLevelPrev", WL_MIN, WL_MAX);
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).CallLater(LateInit, 250);
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), CGame::GetCallQueue(), GetGame(), INDEX_NOT_FOUND, LateInit(), m_DrainValvePressureDeanimationSettings, m_DrainValvePressureStageSettings, m_DrainValveWaterStageSettings, m_FillValvePressureDeanimationSettings, m_FillValvePressureStageSettings, m_FillValveWaterStageSettings, m_LastActiveValve, m_PipeBrokenParticles, m_PipeSounds, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_ValveManipulatedIndex, m_ValveManipulatedIndexPrev, m_ValveNames, m_ValveParticles, m_ValveStates, m_WaterLevelActual, m_WaterLevelPrev, m_WaterLevelsAvailable, m_WaterLevelSnapshot, m_WaterLevelTimesAccumulated, PIPES_BROKEN_COUNT, VALVES_COUNT, WL_AVERAGE, WL_MAX, and WL_MIN.
IsAnyValveActive()
protected bool IsAnyValveActive ()
Definition at line 450 of file land_underground_waterreservoir.c.
    {
        for (int i = 0; i < m_ValveStates.Count(); ++i)
        {
            if (m_ValveStates[i])
            {
                return true;
            }
        }
        return false;
    }
References m_ValveStates.
Referenced by HandleSoundEffectsPipeCreaking().
IsValveActive()
protected bool IsValveActive (int pValveIndex)
Definition at line 463 of file land_underground_waterreservoir.c.
    {
        return pValveIndex >= 0 && pValveIndex <= VALVES_COUNT && m_ValveStates[pValveIndex];
    }
References m_ValveStates, and VALVES_COUNT.
Referenced by HandleSoundEffectsUnderwaterPipeSounds(), HandleVisualEffects(), and IsValveTurnable().
IsValvePressureLevelGaugeAtBase()
protected bool IsValvePressureLevelGaugeAtBase (int pValveIndex)
Definition at line 886 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            return GetValvePressureLevelGauge(pValveIndex) <= 0.01;
        break;
        case VALVE_INDEX_FILL:
            return GetValvePressureLevelGauge(pValveIndex) >= 0.99;
        break;
        }
        return 0.0;
    }
References GetValvePressureLevelGauge(), VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate(), and IsValveTurnable().
IsValveTurnable()
override bool IsValveTurnable (int pValveIndex)
Definition at line 445 of file land_underground_waterreservoir.c.
    {
        return !IsValveActive(pValveIndex) && IsValvePressureLevelGaugeAtBase(pValveIndex);
    }
References IsValveActive(), and IsValvePressureLevelGaugeAtBase().
Land_Underground_WaterReservoir()
void Land_Underground_WaterReservoir ()
Definition at line 153 of file land_underground_waterreservoir.c.
    {
        SetEventMask(EntityEvent.POSTSIMULATE);
        Init();
    }
References Init().
Referenced by CreateAndSetupActionCallback(), OnEndAnimationLoop(), OnFinishProgressServer(), and OnStartAnimationLoopServer().
LateInit()
protected void LateInit ()
Definition at line 388 of file land_underground_waterreservoir.c.
    {
        RegisterValve(VALVE_NAME_DRAIN, VALVE_INDEX_DRAIN);
        RegisterValve(VALVE_NAME_FILL, VALVE_INDEX_FILL);
        TranslateMemoryPointsToWaterLevels();
        ConfigureValvesAndGaugesCourse();
        m_WaterLevelDefault = m_WaterLevelsAvailable[WATER_LEVEL_AVERAGE];
        if (GetGame().IsServer())
        {
            m_SpawnedWaterObject = GetGame().CreateObjectEx(OBJECT_NAME_WATER_PLANE, m_WaterLevelDefault, ECE_CREATEPHYSICS);
            m_SpawnedWaterObject.SetOrientation(GetOrientation());
            SetWaterLevelHeight(m_WaterLevelDefault[1]);
        }
        GetGame().RegisterNetworkStaticObject(this);
        SetSynchDirty();
    }
References ConfigureValvesAndGaugesCourse(), CGame::CreateObjectEx(), ECE_CREATEPHYSICS, GetGame(), GetOrientation(), m_SpawnedWaterObject, m_WaterLevelDefault, m_WaterLevelsAvailable, OBJECT_NAME_WATER_PLANE, CGame::RegisterNetworkStaticObject(), RegisterValve(), SetWaterLevelHeight(), TranslateMemoryPointsToWaterLevels(), VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, VALVE_NAME_DRAIN, VALVE_NAME_FILL, and WATER_LEVEL_AVERAGE.
Referenced by Init().
OnValveManipulationCanceled()
void OnValveManipulationCanceled (int pValveIndex)
Definition at line 520 of file land_underground_waterreservoir.c.
    {
        if (GetGame().IsServer())
        {
            AnimateValve(pValveIndex, 0);
            m_ValveManipulatedIndex = -1;
            SetSynchDirty();
        }
    }
References AnimateValve(), GetGame(), and m_ValveManipulatedIndex.
OnValveManipulationEnd()
void OnValveManipulationEnd (int pValveIndex)
Definition at line 492 of file land_underground_waterreservoir.c.
    {
        if (GetGame().IsServer())
        {
            switch (pValveIndex)
            {
            case VALVE_INDEX_DRAIN:
                m_ValveStates[pValveIndex]                  = true;
                m_PressureAnimationRequests[pValveIndex]    = true;
                m_DrainValveWaterLevelStageIndex            = 1;
                m_DrainValvePressureLevelStageIndex         = 1;
                SetLastActiveValve(pValveIndex);
                AnimateValve(pValveIndex, 0);
            break;
            case VALVE_INDEX_FILL:
                m_ValveStates[pValveIndex]                  = true;
                m_PressureAnimationRequests[pValveIndex]    = true;
                m_FillValveWaterLevelStageIndex             = 1;
                m_FillValvePressureLevelStageIndex          = 1;
                AnimateValve(pValveIndex, 0);
                SetLastActiveValve(pValveIndex);
            break;
            }
            SyncValveVariables();
        }
    }
References AnimateValve(), GetGame(), m_DrainValvePressureLevelStageIndex, m_DrainValveWaterLevelStageIndex, m_FillValvePressureLevelStageIndex, m_FillValveWaterLevelStageIndex, m_PressureAnimationRequests, m_ValveStates, SetLastActiveValve(), SyncValveVariables(), VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
OnValveManipulationStart()
void OnValveManipulationStart (int pValveIndex)
Definition at line 482 of file land_underground_waterreservoir.c.
    {
        if (GetGame().IsServer())
        {
            AnimateValve(pValveIndex, 1);
            m_ValveManipulatedIndex = pValveIndex;
            SetSynchDirty();
        }
    }
References AnimateValve(), GetGame(), and m_ValveManipulatedIndex.
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 308 of file land_underground_waterreservoir.c.
    {
        super.OnVariablesSynchronized();
        m_ValveStates = UnpackBitsToArrayOfBoolStates(m_ValveStatesPacked, VALVES_COUNT);
        if (!m_ValveManipulationSoundRequested)
            PlayValveManipulationSound();
        if (m_ValveManipulatedIndex == -1)
            m_ValveManipulationSoundRequested = false;
    }
References m_ValveManipulatedIndex, m_ValveManipulationSoundRequested, m_ValveStates, m_ValveStatesPacked, PlayValveManipulationSound(), UnpackBitsToArrayOfBoolStates(), and VALVES_COUNT.
PackArrayOfBoolStatesIntoBits()
protected int PackArrayOfBoolStatesIntoBits (array< bool > pStates)
Definition at line 1234 of file land_underground_waterreservoir.c.
    {
        int packedBits = 0;
        for (int i = 0; i < pStates.Count(); ++i)
        {
            if (pStates[i] == true)
            {
                packedBits |= 1 << i;
            }
        }
        return packedBits;
    }
Referenced by SyncValveVariables().
PlayPipeCreakingSoundOnLocation()
protected void PlayPipeCreakingSoundOnLocation ()
Definition at line 1090 of file land_underground_waterreservoir.c.
    {
        m_PipeCreakingSoundRequested = false;
        int index = Math.RandomInt(0, PIPE_CREAKING_SOUND_LOCATIONS_COUNT);
        PlaySoundSetAtMemoryPoint(m_PipeCreakingSounds, SOUND_NAME_PIPE_CREAKING, PIPE_CREAKING_SOUND_LOCATIONS[index]);
    }
References m_PipeCreakingSoundRequested, m_PipeCreakingSounds, PIPE_CREAKING_SOUND_LOCATIONS, PIPE_CREAKING_SOUND_LOCATIONS_COUNT, PlaySoundSetAtMemoryPoint(), Math::RandomInt(), and SOUND_NAME_PIPE_CREAKING.
Referenced by HandleSoundEffectsPipeCreaking().
PlayValveManipulationSound()
protected void PlayValveManipulationSound ()
Definition at line 939 of file land_underground_waterreservoir.c.
    {
        switch (m_ValveManipulatedIndex)
        {
            case VALVE_INDEX_DRAIN:
                m_ValveManipulationSoundRequested = PlaySoundSetAtMemoryPoint(m_ValveManipulationSound, SOUND_NAME_VALVE_MANIPULATION, VALVE_NAME_DRAIN);
                break;
            case VALVE_INDEX_FILL:
                m_ValveManipulationSoundRequested = PlaySoundSetAtMemoryPoint(m_ValveManipulationSound, SOUND_NAME_VALVE_MANIPULATION, VALVE_NAME_FILL);
                break;
        }
    }
References m_ValveManipulatedIndex, m_ValveManipulationSound, m_ValveManipulationSoundRequested, PlaySoundSetAtMemoryPoint(), SOUND_NAME_VALVE_MANIPULATION, VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, VALVE_NAME_DRAIN, and VALVE_NAME_FILL.
Referenced by OnVariablesSynchronized().
PressureLevelSettings()
void PressureLevelSettings (int pPressureLevel, float pDuration)
Definition at line 18 of file land_underground_waterreservoir.c.
    {
        PressureLevel   = pPressureLevel;
        Duration        = pDuration;
    }
References Duration, and PressureLevel.
Referenced by ActualPressureLevelStageSettings(), ConfigureValvesAndGaugesCourse(), EOnPostSimulate(), and PreviousPressureLevelStageSettings().
PressureLevelToValue()
protected float PressureLevelToValue (int pPressureLevel)
Definition at line 640 of file land_underground_waterreservoir.c.
    {
        switch (pPressureLevel)
        {
        case PL_MIN:
            return 0.0;
        case PL_AVERAGE:
            return 0.5;
        case PL_MAX:
            return 1.0;
        }
        return 0.0;
    }
References PL_AVERAGE, PL_MAX, and PL_MIN.
Referenced by EOnPostSimulate().
PreviousPressureLevelStageSettings()
protected PressureLevelSettings PreviousPressureLevelStageSettings (int pValveIndex, bool pDeanimationRequest = false)
Definition at line 733 of file land_underground_waterreservoir.c.
    {
        PressureLevelSettings plStageSettings;
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            if (pDeanimationRequest)
            {
                plStageSettings = m_FillValvePressureDeanimationSettings[0];
                return plStageSettings;
            }
            if (m_DrainValvePressureLevelStageIndex > 0)
            {
                plStageSettings = m_DrainValvePressureStageSettings.Get(m_DrainValvePressureLevelStageIndex - 1);
            }
            else
            {
                plStageSettings = m_DrainValvePressureStageSettings.Get(m_DrainValvePressureLevelStageIndex);
            }
        break;
        case VALVE_INDEX_FILL:
            if (pDeanimationRequest)
            {
                plStageSettings = m_FillValvePressureDeanimationSettings[0];
                return plStageSettings;
            }
            if (m_FillValvePressureLevelStageIndex > 0)
            {
                plStageSettings = m_FillValvePressureStageSettings.Get(m_FillValvePressureLevelStageIndex - 1);
            }
            else
            {
                plStageSettings = m_FillValvePressureStageSettings.Get(m_FillValvePressureLevelStageIndex);
            }
        break;
        }
        return plStageSettings;
    }
References m_DrainValvePressureLevelStageIndex, m_DrainValvePressureStageSettings, m_FillValvePressureDeanimationSettings, m_FillValvePressureLevelStageIndex, m_FillValvePressureStageSettings, PressureLevelSettings(), VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
PreviousWaterLevelStageSettings()
protected WaterLevelSettings PreviousWaterLevelStageSettings (int pValveIndex)
Definition at line 655 of file land_underground_waterreservoir.c.
    {
        WaterLevelSettings wlStageSettings;
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            if (m_DrainValveWaterLevelStageIndex > 0)
            {
                wlStageSettings = m_DrainValveWaterStageSettings.Get(m_DrainValveWaterLevelStageIndex - 1);
            }
            else
            {
                wlStageSettings = m_DrainValveWaterStageSettings.Get(m_DrainValveWaterLevelStageIndex);
            }
        break;
        case VALVE_INDEX_FILL:
            if (m_FillValveWaterLevelStageIndex > 0)
            {
                wlStageSettings = m_FillValveWaterStageSettings.Get(m_FillValveWaterLevelStageIndex - 1);
            }
            else
            {
                wlStageSettings = m_FillValveWaterStageSettings.Get(m_FillValveWaterLevelStageIndex);
            }
        break;
        }
        m_WaterLevelPrev = wlStageSettings.WaterLevel;
        SetSynchDirty();
        return wlStageSettings;
    }
References m_DrainValveWaterLevelStageIndex, m_DrainValveWaterStageSettings, m_FillValveWaterLevelStageIndex, m_FillValveWaterStageSettings, m_WaterLevelPrev, VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, and WaterLevelSettings::WaterLevel.
Referenced by EOnPostSimulate().
RegisterValve()
protected void RegisterValve (string pCompName, int pIndex)
Definition at line 575 of file land_underground_waterreservoir.c.
    {
        m_ValveNames.Set(pIndex, pCompName);
        m_ValveStates.Set(pIndex, false);
        m_PressureAnimationRequests.Set(pIndex, 0);
        m_PressureDeanimationRequests.Set(pIndex, 0);
        m_WaterLevelTimesAccumulated.Set(pIndex, 0);
        m_PressureTimesAccumulated.Set(pIndex, false);
        m_PipeSounds.Set(pIndex, null);
    }
References m_PipeSounds, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_ValveNames, m_ValveStates, and m_WaterLevelTimesAccumulated.
Referenced by LateInit().
ResetState()
protected void ResetState ()
Definition at line 1198 of file land_underground_waterreservoir.c.
    {
        SetWaterLevelHeight(m_WaterLevelsAvailable[WATER_LEVEL_AVERAGE][1]);
        SetValvePressureLevelGauge(VALVE_INDEX_DRAIN, 0.0);
        SetValvePressureLevelGauge(VALVE_INDEX_FILL, 1.0);
        m_DrainValveWaterLevelStageIndex            = 0;
        m_DrainValvePressureLevelStageIndex         = 0;
        m_FillValveWaterLevelStageIndex             = 0;
        m_FillValvePressureLevelStageIndex          = 0;
        m_ValveStates                               = {0, 0};
        m_PressureAnimationRequests                 = {0, 0};
        m_PressureDeanimationRequests               = {0, 0};
        m_WaterLevelTimesAccumulated                = {0, 0};
        m_PressureTimesAccumulated                  = {0, 0};
        m_LastActiveValve                           = -1;
        m_WaterLevelHeightActual                    = WaterLevelToHeight(WL_AVERAGE);
        m_PipeCreakingSoundRequested                = false;
        m_ValveManipulatedIndex                     = -1;
        m_ValveManipulatedIndexPrev                 = -1;
        SetSynchDirty();
        CleanSoundEffects();
    }
References CleanSoundEffects(), m_DrainValvePressureLevelStageIndex, m_DrainValveWaterLevelStageIndex, m_FillValvePressureLevelStageIndex, m_FillValveWaterLevelStageIndex, m_LastActiveValve, m_PipeCreakingSoundRequested, m_PressureAnimationRequests, m_PressureDeanimationRequests, m_PressureTimesAccumulated, m_ValveManipulatedIndex, m_ValveManipulatedIndexPrev, m_ValveStates, m_WaterLevelHeightActual, m_WaterLevelsAvailable, m_WaterLevelTimesAccumulated, SetValvePressureLevelGauge(), SetWaterLevelHeight(), VALVE_INDEX_DRAIN, VALVE_INDEX_FILL, WATER_LEVEL_AVERAGE, WaterLevelToHeight(), and WL_AVERAGE.
SetActions()
override void SetActions ()
Definition at line 321 of file land_underground_waterreservoir.c.
    {
        super.SetActions();
        AddAction(ActionTurnValveUndergroundReservoir);
    }
References ActionTurnValveUndergroundReservoir(), and AddAction().
SetDefaultPressureLevelStageSettings()
protected void SetDefaultPressureLevelStageSettings (int pValveIndex)
Definition at line 832 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            m_DrainValvePressureLevelStageIndex = 0;
        break;
        case VALVE_INDEX_FILL:
            m_FillValvePressureLevelStageIndex = 0;
        break;
        }
    }
References m_DrainValvePressureLevelStageIndex, m_FillValvePressureLevelStageIndex, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate().
SetLastActiveValve()
protected void SetLastActiveValve (int pValveIndex)
Definition at line 555 of file land_underground_waterreservoir.c.
    {
        m_LastActiveValve = pValveIndex;
    }
References m_LastActiveValve.
Referenced by OnValveManipulationEnd().
SetValvePressureLevelGauge()
protected void SetValvePressureLevelGauge (int pValveIndex, float pValue)
Definition at line 858 of file land_underground_waterreservoir.c.
    {
        switch (pValveIndex)
        {
        case VALVE_INDEX_DRAIN:
            SetAnimationPhase(ANIM_PHASE_VALVE_GAUGE_DRAIN, pValue);
        break;
        case VALVE_INDEX_FILL:
            SetAnimationPhase(ANIM_PHASE_VALVE_GAUGE_FILL, pValue);
        break;
        }
    }
References ANIM_PHASE_VALVE_GAUGE_DRAIN, ANIM_PHASE_VALVE_GAUGE_FILL, VALVE_INDEX_DRAIN, and VALVE_INDEX_FILL.
Referenced by EOnPostSimulate(), and ResetState().
SetWaterLevelHeight()
protected void SetWaterLevelHeight (float pHeight)
Definition at line 560 of file land_underground_waterreservoir.c.
    {
        if (GetGame() && GetGame().IsServer())
        {
            vector pos                  = Vector(m_WaterLevelDefault[0], pHeight, m_WaterLevelDefault[2]);
            m_WaterLevelHeightActual    = pHeight;
            m_WaterLevelActual          = HeightToWaterLevel(pHeight);
            if (m_SpawnedWaterObject)
            {
                m_SpawnedWaterObject.SetPosition(pos);
            }
        }
    }
References GetGame(), HeightToWaterLevel(), m_SpawnedWaterObject, m_WaterLevelActual, m_WaterLevelDefault, m_WaterLevelHeightActual, and Vector().
Referenced by EOnPostSimulate(), LateInit(), and ResetState().
SyncValveVariables()
protected void SyncValveVariables ()
Definition at line 1221 of file land_underground_waterreservoir.c.
    {
        if (GetGame())
        {
            m_ValveStatesPacked = PackArrayOfBoolStatesIntoBits(m_ValveStates);
            if (m_ValveStatesPacked != m_ValveStatesPackedPrev)
            {
                m_ValveStatesPackedPrev = m_ValveStatesPacked;
                SetSynchDirty();
            }
        }
    }
References GetGame(), m_ValveStates, m_ValveStatesPacked, m_ValveStatesPackedPrev, and PackArrayOfBoolStatesIntoBits().
Referenced by EOnPostSimulate(), and OnValveManipulationEnd().
TranslateMemoryPointsToWaterLevels()
protected void TranslateMemoryPointsToWaterLevels ()
Definition at line 586 of file land_underground_waterreservoir.c.
    {
        m_WaterLevelsAvailable.Clear();
        for (int i = 0; i < WATER_LEVELS_COUNT; ++i)
        {
            if (MemoryPointExists(WATER_LEVELS[i]))
            {
                if (!m_WaterLevelsAvailable.Contains(WATER_LEVELS[i]))
                {
                    m_WaterLevelsAvailable.Insert(WATER_LEVELS[i], ModelToWorld(GetMemoryPointPos(WATER_LEVELS[i])));
                }
            }
        }
    }
References GetMemoryPointPos(), m_WaterLevelsAvailable, MemoryPointExists(), ModelToWorld(), WATER_LEVELS, and WATER_LEVELS_COUNT.
Referenced by LateInit().
UnpackBitsToArrayOfBoolStates()
protected array< bool > UnpackBitsToArrayOfBoolStates (int pPackedBits, int pArrayLength)
Definition at line 1249 of file land_underground_waterreservoir.c.
    {
        array<bool> unpackedBools = new array<bool>();
        for (int i = 0; i < pArrayLength; ++i)
        {
            if ((pPackedBits & 1 << i) != 0)
            {
                unpackedBools.Insert(true);
            }
            else
            {
                unpackedBools.Insert(false);
            }
        }
        return unpackedBools;
    }
Referenced by OnVariablesSynchronized().
WaterLevelToHeight()
protected float WaterLevelToHeight (int pWaterLevel)
Definition at line 601 of file land_underground_waterreservoir.c.
    {
        switch (pWaterLevel)
        {
        case WL_MIN:
            return m_WaterLevelsAvailable[WATER_LEVEL_MIN][1];
        case WL_ABOVE_PIPES:
            return m_WaterLevelsAvailable[WATER_LEVEL_ABOVE_PIPES][1];
        case WL_AVERAGE:
            return m_WaterLevelsAvailable[WATER_LEVEL_AVERAGE][1];
        case WL_MAX:
            return m_WaterLevelsAvailable[WATER_LEVEL_MAX][1];
        }
        return 0;
    }
References m_WaterLevelsAvailable, WATER_LEVEL_ABOVE_PIPES, WATER_LEVEL_AVERAGE, WATER_LEVEL_MAX, WATER_LEVEL_MIN, WL_ABOVE_PIPES, WL_AVERAGE, WL_MAX, and WL_MIN.
Referenced by EOnPostSimulate(), and ResetState().
~Land_Underground_WaterReservoir()
void ~Land_Underground_WaterReservoir ()
Definition at line 160 of file land_underground_waterreservoir.c.
    {
        CleanSoundEffects();
        CleanVisualEffects();
    }
References CleanSoundEffects(), and CleanVisualEffects().
Variable Documentation
ANIM_PHASE_VALVE_DRAIN
protected const string ANIM_PHASE_VALVE_DRAIN = "Valve1"
Definition at line 54 of file land_underground_waterreservoir.c.
Referenced by AnimateValve().
ANIM_PHASE_VALVE_FILL
protected const string ANIM_PHASE_VALVE_FILL = "Valve2"
Definition at line 55 of file land_underground_waterreservoir.c.
Referenced by AnimateValve().
ANIM_PHASE_VALVE_GAUGE_DRAIN
protected const string ANIM_PHASE_VALVE_GAUGE_DRAIN = "ValveGauge1"
tighter broken pipe
Definition at line 52 of file land_underground_waterreservoir.c.
Referenced by GetValvePressureLevelGauge(), and SetValvePressureLevelGauge().
ANIM_PHASE_VALVE_GAUGE_FILL
protected const string ANIM_PHASE_VALVE_GAUGE_FILL = "ValveGauge2"
Definition at line 53 of file land_underground_waterreservoir.c.
Referenced by GetValvePressureLevelGauge(), and SetValvePressureLevelGauge().
Duration
float Duration
Definition at line 16 of file land_underground_waterreservoir.c.
Referenced by PressureLevelSettings().
m_DrainValvePressureDeanimationSettings
protected ref array<ref PressureLevelSettings> m_DrainValvePressureDeanimationSettings
Definition at line 83 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), ConfigureValvesAndGaugesCourse(), and Init().
m_DrainValvePressureLevelStageIndex
protected int m_DrainValvePressureLevelStageIndex
Definition at line 91 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), OnValveManipulationEnd(), PreviousPressureLevelStageSettings(), ResetState(), and SetDefaultPressureLevelStageSettings().
m_DrainValvePressureStageSettings
protected ref array<ref PressureLevelSettings> m_DrainValvePressureStageSettings
Definition at line 82 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), ConfigureValvesAndGaugesCourse(), Init(), and PreviousPressureLevelStageSettings().
m_DrainValveWaterLevelStageIndex
protected int m_DrainValveWaterLevelStageIndex
pointing to specific stage for each valve/pipe
Definition at line 90 of file land_underground_waterreservoir.c.
Referenced by ActualWaterLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), OnValveManipulationEnd(), PreviousWaterLevelStageSettings(), and ResetState().
m_DrainValveWaterStageSettings
protected ref array<ref WaterLevelSettings> m_DrainValveWaterStageSettings
valve/pipe stages for water and pressure levels
Definition at line 81 of file land_underground_waterreservoir.c.
Referenced by ActualWaterLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), ConfigureValvesAndGaugesCourse(), Init(), and PreviousWaterLevelStageSettings().
m_FillValvePressureDeanimationSettings
protected ref array<ref PressureLevelSettings> m_FillValvePressureDeanimationSettings
Definition at line 86 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), ConfigureValvesAndGaugesCourse(), Init(), and PreviousPressureLevelStageSettings().
m_FillValvePressureLevelStageIndex
protected int m_FillValvePressureLevelStageIndex
Definition at line 93 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), OnValveManipulationEnd(), PreviousPressureLevelStageSettings(), ResetState(), and SetDefaultPressureLevelStageSettings().
m_FillValvePressureStageSettings
protected ref array<ref PressureLevelSettings> m_FillValvePressureStageSettings
Definition at line 85 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), ConfigureValvesAndGaugesCourse(), Init(), and PreviousPressureLevelStageSettings().
m_FillValveWaterLevelStageIndex
protected int m_FillValveWaterLevelStageIndex
Definition at line 92 of file land_underground_waterreservoir.c.
Referenced by ActualWaterLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), OnValveManipulationEnd(), PreviousWaterLevelStageSettings(), and ResetState().
m_FillValveWaterStageSettings
protected ref array<ref WaterLevelSettings> m_FillValveWaterStageSettings
for deanimation purposes
Definition at line 84 of file land_underground_waterreservoir.c.
Referenced by ActualWaterLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), ConfigureValvesAndGaugesCourse(), Init(), and PreviousWaterLevelStageSettings().
m_LastActiveValve
protected int m_LastActiveValve
Definition at line 121 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), ResetState(), and SetLastActiveValve().
m_PipeBrokenParticles
protected ref ParticleSourceArray m_PipeBrokenParticles
Definition at line 151 of file land_underground_waterreservoir.c.
Referenced by CleanVisualEffects(), HandleVisualEffects(), and Init().
m_PipeCreakingSoundRequested
protected bool m_PipeCreakingSoundRequested
Definition at line 132 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeCreaking(), PlayPipeCreakingSoundOnLocation(), and ResetState().
m_PipeCreakingSounds
protected ref EffectSound m_PipeCreakingSounds
Definition at line 133 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeCreaking(), and PlayPipeCreakingSoundOnLocation().
m_PipeSounds
protected ref array<EffectSound> m_PipeSounds
Definition at line 130 of file land_underground_waterreservoir.c.
Referenced by CleanSoundEffects(), HandleSoundEffectsPipeSprinkling(), Init(), and RegisterValve().
m_PipeUnderwaterSound
protected bool m_PipeUnderwaterSoundRunning protected ref EffectSound m_PipeUnderwaterSound
Definition at line 136 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds().
m_PressureAnimationRequests
protected ref array<bool> m_PressureAnimationRequests
Definition at line 117 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), OnValveManipulationEnd(), RegisterValve(), and ResetState().
m_PressureDeanimationRequests
protected ref array<bool> m_PressureDeanimationRequests
Definition at line 118 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), RegisterValve(), and ResetState().
m_PressureTimesAccumulated
protected ref array<float> m_PressureTimesAccumulated
Definition at line 120 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), RegisterValve(), and ResetState().
m_SpawnedWaterObject
protected Object m_SpawnedWaterObject
Definition at line 123 of file land_underground_waterreservoir.c.
Referenced by LateInit(), and SetWaterLevelHeight().
m_ValveManipulatedIndex
protected int m_ValveManipulatedIndex
Definition at line 110 of file land_underground_waterreservoir.c.
Referenced by Init(), OnValveManipulationCanceled(), OnValveManipulationStart(), OnVariablesSynchronized(), PlayValveManipulationSound(), and ResetState().
m_ValveManipulatedIndexPrev
protected int m_ValveManipulatedIndexPrev
Definition at line 111 of file land_underground_waterreservoir.c.
Referenced by Init(), and ResetState().
m_ValveManipulationSound
protected ref EffectSound m_ValveManipulationSound
Definition at line 129 of file land_underground_waterreservoir.c.
Referenced by PlayValveManipulationSound().
m_ValveManipulationSoundRequested
protected bool m_ValveManipulationSoundRequested
VFX/SFX.
Definition at line 128 of file land_underground_waterreservoir.c.
Referenced by OnVariablesSynchronized(), and PlayValveManipulationSound().
m_ValveNames
protected ref array<string> m_ValveNames
Definition at line 112 of file land_underground_waterreservoir.c.
Referenced by GetTurnableValveIndex(), Init(), and RegisterValve().
m_ValveParticles
protected ref ParticleSourceArray m_ValveParticles
Definition at line 150 of file land_underground_waterreservoir.c.
Referenced by CleanVisualEffects(), HandleVisualEffects(), and Init().
m_ValveStates
protected ref array<bool> m_ValveStates
Definition at line 113 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), IsAnyValveActive(), IsValveActive(), OnValveManipulationEnd(), OnVariablesSynchronized(), RegisterValve(), ResetState(), and SyncValveVariables().
m_ValveStatesPacked
protected int m_ValveStatesPacked
Definition at line 108 of file land_underground_waterreservoir.c.
Referenced by OnVariablesSynchronized(), and SyncValveVariables().
m_ValveStatesPackedPrev
protected int m_ValveStatesPackedPrev
Definition at line 109 of file land_underground_waterreservoir.c.
Referenced by SyncValveVariables().
m_WaterLevelActual
protected int m_WaterLevelActual
Definition at line 115 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds(), HandleSoundEffectsWaterLevelMovementSounds(), HandleVisualEffects(), Init(), and SetWaterLevelHeight().
m_WaterLevelDefault
protected vector m_WaterLevelDefault
Definition at line 124 of file land_underground_waterreservoir.c.
Referenced by LateInit(), and SetWaterLevelHeight().
m_WaterLevelHeightActual
protected float m_WaterLevelHeightActual
Definition at line 125 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), ResetState(), and SetWaterLevelHeight().
m_WaterLevelMovementSound
protected ref EffectSound m_WaterLevelMovementSound
Definition at line 138 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsWaterLevelMovementSounds().
m_WaterLevelPrev
protected int m_WaterLevelPrev
Definition at line 116 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds(), HandleSoundEffectsWaterLevelMovementSounds(), HandleVisualEffects(), Init(), and PreviousWaterLevelStageSettings().
m_WaterLevelsAvailable
protected ref map<string, vector> m_WaterLevelsAvailable
Definition at line 114 of file land_underground_waterreservoir.c.
Referenced by HeightToWaterLevel(), Init(), LateInit(), ResetState(), TranslateMemoryPointsToWaterLevels(), and WaterLevelToHeight().
m_WaterLevelSnapshot
protected ref WaterLevelSnapshot m_WaterLevelSnapshot
for deanimation purposes
Definition at line 87 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), and Init().
m_WaterLevelTimesAccumulated
protected ref array<float> m_WaterLevelTimesAccumulated
Definition at line 119 of file land_underground_waterreservoir.c.
Referenced by EOnPostSimulate(), Init(), RegisterValve(), and ResetState().
OBJECT_NAME_WATER_PLANE
class WaterLevelSnapshot OBJECT_NAME_WATER_PLANE = "Land_Underground_WaterReservoir_Water"
Referenced by LateInit().
PARTICLE_DRAIN_PIPE_MAX_PRESSURE
protected const int PARTICLE_DRAIN_PIPE_MAX_PRESSURE = ParticleList.WATER_SPILLING
Definition at line 75 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PARTICLE_FILL_PIPE_JET
protected const int PARTICLE_FILL_PIPE_JET = ParticleList.WATER_JET
Definition at line 77 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PARTICLE_FILL_PIPE_JET_WEAK
protected const int PARTICLE_FILL_PIPE_JET_WEAK = ParticleList.WATER_JET_WEAK
Definition at line 78 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PARTICLE_FILL_PIPE_MAX_PRESSURE
protected const int PARTICLE_FILL_PIPE_MAX_PRESSURE = ParticleList.WATER_SPILLING
Definition at line 76 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPE_CREAKING_MAX_TIME_DELAY_MS
protected const int PIPE_CREAKING_MAX_TIME_DELAY_MS = 15000
Definition at line 141 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeCreaking().
PIPE_CREAKING_MIN_TIME_DELAY_MS
protected const int PIPE_CREAKING_MIN_TIME_DELAY_MS = 10000
Definition at line 140 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeCreaking().
PIPE_CREAKING_SOUND_LOCATIONS
protected const string PIPE_CREAKING_SOUND_LOCATIONS[PIPE_CREAKING_SOUND_LOCATIONS_COUNT]
Initial value:
= {
        "pipe_creaking_sound_pos_1",
        "pipe_creaking_sound_pos_2",
        "pipe_creaking_sound_pos_3",
        "pipe_creaking_sound_pos_4"
    }
Definition at line 143 of file land_underground_waterreservoir.c.
Referenced by PlayPipeCreakingSoundOnLocation().
PIPE_CREAKING_SOUND_LOCATIONS_COUNT
protected const int PIPE_CREAKING_SOUND_LOCATIONS_COUNT = 4
Definition at line 142 of file land_underground_waterreservoir.c.
Referenced by PlayPipeCreakingSoundOnLocation().
PIPE_INDEX_BROKEN1
protected const int PIPE_INDEX_BROKEN1 = 0
Definition at line 49 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPE_INDEX_BROKEN2
protected const int PIPE_INDEX_BROKEN2 = 1
main broken pipe
Definition at line 50 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPE_NAME_BROKEN1
protected const string PIPE_NAME_BROKEN1 = "pipe_broken_1"
Definition at line 58 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds(), HandleSoundEffectsWaterLevelMovementSounds(), and HandleVisualEffects().
PIPE_NAME_BROKEN2
protected const string PIPE_NAME_BROKEN2 = "pipe_broken_2"
Definition at line 59 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPE_NAME_LEAKING_DRAIN
protected const string PIPE_NAME_LEAKING_DRAIN = "pipe_leaking_1"
Definition at line 60 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPE_NAME_LEAKING_FILL
protected const string PIPE_NAME_LEAKING_FILL = "pipe_leaking_2"
Definition at line 61 of file land_underground_waterreservoir.c.
Referenced by HandleVisualEffects().
PIPES_BROKEN_COUNT
protected const int PIPES_BROKEN_COUNT = 2
Definition at line 48 of file land_underground_waterreservoir.c.
Referenced by Init().
PL_AVERAGE
protected const int PL_AVERAGE = 1
Definition at line 41 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), and PressureLevelToValue().
PL_MAX
protected const int PL_MAX = 2
Definition at line 42 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), and PressureLevelToValue().
PL_MIN
protected const int PL_MIN = 0
Definition at line 40 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), and PressureLevelToValue().
PressureLevel
class WaterLevelSettings PressureLevel
Referenced by PressureLevelSettings().
SOUND_NAME_PIPE_CREAKING
protected const string SOUND_NAME_PIPE_CREAKING = "WaterObjectUndergroundPipeCreaking_SoundSet"
Definition at line 63 of file land_underground_waterreservoir.c.
Referenced by PlayPipeCreakingSoundOnLocation().
SOUND_NAME_PIPE_SPRINKLING_END
protected const string SOUND_NAME_PIPE_SPRINKLING_END = "WaterObjectUndergroundPipeSprinkling_End_SoundSet"
Definition at line 66 of file land_underground_waterreservoir.c.
SOUND_NAME_PIPE_SPRINKLING_LOOP1
protected const string SOUND_NAME_PIPE_SPRINKLING_LOOP1 = "WaterObjectUndergroundPipeSprinkling_Loop1_SoundSet"
Definition at line 67 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeSprinkling().
SOUND_NAME_PIPE_SPRINKLING_LOOP2
protected const string SOUND_NAME_PIPE_SPRINKLING_LOOP2 = "WaterObjectUndergroundPipeSprinkling_Loop2_SoundSet"
Definition at line 68 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeSprinkling().
SOUND_NAME_PIPE_SPRINKLING_START
protected const string SOUND_NAME_PIPE_SPRINKLING_START = "WaterObjectUndergroundPipeSprinkling_Start_SoundSet"
Definition at line 65 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsPipeSprinkling().
SOUND_NAME_UPIPE_SPRINKLING_END
protected const string SOUND_NAME_UPIPE_SPRINKLING_END = "WaterObjectUndergroundUnderwaterPipe_End_SoundSet"
Definition at line 70 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds().
SOUND_NAME_UPIPE_SPRINKLING_LOOP
protected const string SOUND_NAME_UPIPE_SPRINKLING_LOOP = "WaterObjectUndergroundUnderwaterPipe_Loop_SoundSet"
Definition at line 71 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds().
SOUND_NAME_UPIPE_SPRINKLING_START
protected const string SOUND_NAME_UPIPE_SPRINKLING_START = "WaterObjectUndergroundUnderwaterPipe_Start_SoundSet"
Definition at line 69 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds().
SOUND_NAME_VALVE_MANIPULATION
protected const string SOUND_NAME_VALVE_MANIPULATION = "WaterObjectUndergroundValve_SoundSet"
Definition at line 64 of file land_underground_waterreservoir.c.
Referenced by PlayValveManipulationSound().
SOUND_NAME_WATER_DRAIN_LOOP
protected const string SOUND_NAME_WATER_DRAIN_LOOP = "WaterObjectUndergroundUnderwaterEmpty_Loop_SoundSet"
Definition at line 73 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsWaterLevelMovementSounds().
SOUND_NAME_WATER_FILL_LOOP
protected const string SOUND_NAME_WATER_FILL_LOOP = "WaterObjectUndergroundUnderwaterFill_Loop_SoundSet"
Definition at line 72 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsWaterLevelMovementSounds().
VALVE_INDEX_DRAIN
protected const int VALVE_INDEX_DRAIN = 0
Definition at line 45 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), ActualWaterLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), AnimateValve(), CleanSoundEffects(), GetValveAligningPointsWS(), GetValvePressureLevelGauge(), HandleSoundEffectsPipeSprinkling(), HandleVisualEffects(), IsValvePressureLevelGaugeAtBase(), LateInit(), OnValveManipulationEnd(), PlayValveManipulationSound(), PreviousPressureLevelStageSettings(), PreviousWaterLevelStageSettings(), ResetState(), SetDefaultPressureLevelStageSettings(), and SetValvePressureLevelGauge().
VALVE_INDEX_FILL
protected const int VALVE_INDEX_FILL = 1
Definition at line 46 of file land_underground_waterreservoir.c.
Referenced by ActualPressureLevelStageSettings(), ActualWaterLevelStageSettings(), AdvanceToNextPressureLevelStageSettings(), AdvanceToNextWaterLevelStageSettings(), AnimateValve(), CleanSoundEffects(), GetValveAligningPointsWS(), GetValvePressureLevelGauge(), HandleSoundEffectsPipeSprinkling(), HandleSoundEffectsUnderwaterPipeSounds(), HandleVisualEffects(), IsValvePressureLevelGaugeAtBase(), LateInit(), OnValveManipulationEnd(), PlayValveManipulationSound(), PreviousPressureLevelStageSettings(), PreviousWaterLevelStageSettings(), ResetState(), SetDefaultPressureLevelStageSettings(), and SetValvePressureLevelGauge().
VALVE_NAME_DRAIN
protected const string VALVE_NAME_DRAIN = "valve1"
Definition at line 56 of file land_underground_waterreservoir.c.
Referenced by GetValveAligningPointsWS(), HandleSoundEffectsPipeSprinkling(), LateInit(), and PlayValveManipulationSound().
VALVE_NAME_FILL
protected const string VALVE_NAME_FILL = "valve2"
Definition at line 57 of file land_underground_waterreservoir.c.
Referenced by GetValveAligningPointsWS(), HandleSoundEffectsPipeSprinkling(), LateInit(), and PlayValveManipulationSound().
VALVES_COUNT
protected const int VALVES_COUNT = 2
Definition at line 44 of file land_underground_waterreservoir.c.
Referenced by CleanVisualEffects(), EOnPostSimulate(), Init(), IsValveActive(), and OnVariablesSynchronized().
WATER_LEVEL_ABOVE_PIPES
protected const string WATER_LEVEL_ABOVE_PIPES = "water_level_above_pipes" static
Definition at line 97 of file land_underground_waterreservoir.c.
Referenced by HeightToWaterLevel(), and WaterLevelToHeight().
WATER_LEVEL_AVERAGE
protected const string WATER_LEVEL_AVERAGE = "water_level_average" static
Definition at line 96 of file land_underground_waterreservoir.c.
Referenced by HeightToWaterLevel(), LateInit(), ResetState(), and WaterLevelToHeight().
WATER_LEVEL_MAX
protected const string WATER_LEVEL_MAX = "water_level_max" static
Definition at line 95 of file land_underground_waterreservoir.c.
Referenced by HeightToWaterLevel(), and WaterLevelToHeight().
WATER_LEVEL_MIN
protected const string WATER_LEVEL_MIN = "water_level_min" static
Definition at line 98 of file land_underground_waterreservoir.c.
Referenced by HeightToWaterLevel(), and WaterLevelToHeight().
WATER_LEVELS
protected const string WATER_LEVELS[WATER_LEVELS_COUNT]
Initial value:
= {
        WATER_LEVEL_MAX,
        WATER_LEVEL_AVERAGE,
        WATER_LEVEL_ABOVE_PIPES,
        WATER_LEVEL_MIN
    }
Definition at line 101 of file land_underground_waterreservoir.c.
Referenced by TranslateMemoryPointsToWaterLevels().
WATER_LEVELS_COUNT
protected const int WATER_LEVELS_COUNT = 4
Definition at line 100 of file land_underground_waterreservoir.c.
Referenced by TranslateMemoryPointsToWaterLevels().
WL_ABOVE_PIPES
protected const int WL_ABOVE_PIPES = 1
Definition at line 36 of file land_underground_waterreservoir.c.
Referenced by HandleSoundEffectsUnderwaterPipeSounds(), HandleVisualEffects(), HeightToWaterLevel(), and WaterLevelToHeight().
WL_AVERAGE
protected const int WL_AVERAGE = 2
Definition at line 37 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), HandleSoundEffectsUnderwaterPipeSounds(), HandleVisualEffects(), HeightToWaterLevel(), Init(), ResetState(), and WaterLevelToHeight().
WL_MAX
protected const int WL_MAX = 3
Definition at line 38 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), HandleSoundEffectsUnderwaterPipeSounds(), HandleVisualEffects(), HeightToWaterLevel(), Init(), and WaterLevelToHeight().
WL_MIN
protected const int WL_MIN = 0
Definition at line 35 of file land_underground_waterreservoir.c.
Referenced by ConfigureValvesAndGaugesCourse(), HeightToWaterLevel(), Init(), and WaterLevelToHeight().