DayzKode: P:/scripts/4_world/DayZ/entities/building/underground/entrance/land_underground_panel.c File Reference
land_underground_panel.c File Reference
Enumerations
enum ELEDState { OFF , BLINKING , ON }
Functions
bool CanInteract ()
Land_Underground_EntranceBase GetClosestDoor ()
Land_Underground_EntranceBase GetLinkedDoor ()
EUndegroundDoorType GetLinkedDoorType ()
void Interact ()
void Land_Underground_Panel ()
void OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
void OnLEDStateChanged ()
void OnPanelUsedSynchronized ()
override void OnVariablesSynchronized ()
static void RegisterEntrance (Land_Underground_EntranceBase entrance)
static void RegisterPanel (Land_Underground_Panel panel)
void ResetPanelUsed ()
void SetBlinkingTimer (bool enable)
void SetLEDState (ELEDColors color, ELEDState state)
void ToggleFlipFlop ()
static void UnregisterEntrance (Land_Underground_EntranceBase entrance)
static void UnregisterPanel (Land_Underground_Panel panel)
protected void UpdateLED (string selection, string color)
void ~Land_Underground_Panel ()
Variables
const string COLOR_LED_GREEN = "#(argb,8,8,3)color(0,1,0,1.0,co)"
const string COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
const string COLOR_LED_RED = "#(argb,8,8,3)color(1,0,0,1.0,co)"
enum ELEDState GREEN
EffectSound m_ActivationSound
bool m_BlinkingFlipFlop
enum ELEDState m_Entrances
ref Timer m_FlipFlopTimer
ELEDState m_LedStateGreen
ELEDState m_LedStateRed
Land_Underground_EntranceBase m_LinkedDoor
static ref set< Land_Underground_Panel > m_Panels
bool m_PanelWasUsed bool m_PanelWasUsedPrev
enum ELEDState RED
const string SELECTION_NAME_LED_GREEN = "LED_Green"
const string SELECTION_NAME_LED_RED = "LED_Red"
Enumeration Type Documentation
ELEDState
enum ELEDState
Enumerator
OFF
BLINKING
ON
Definition at line 1 of file land_underground_panel.c.
{
    OFF,
    BLINKING,
    ON,
}
Function Documentation
CanInteract()
bool CanInteract ()
Definition at line 51 of file land_underground_panel.c.
    {
        Land_Underground_EntranceBase door = GetLinkedDoor();
        if (door)
        {
            return Land_Underground_EntranceBase.Cast(door).CanManipulate();
        }
        return false;
    }
References Land_Underground_EntranceBase::CanManipulate(), and GetLinkedDoor().
GetClosestDoor()
Land_Underground_EntranceBase GetClosestDoor ()
Definition at line 140 of file land_underground_panel.c.
    {
        if (!m_Entrances)
        {
            return null;
        }
        float closestDst = float.MAX;
        Land_Underground_EntranceBase closestObj;
        vector thisPos = GetPosition();
        foreach (Land_Underground_EntranceBase obj: m_Entrances)
        {
            float dist = vector.DistanceSq(thisPos, obj.GetPosition());
            if (dist < closestDst)
            {
                closestDst = dist;
                closestObj = obj;
            }
        }
        return closestObj;
    }
References vector::DistanceSq(), GetPosition, and m_Entrances.
Referenced by GetLinkedDoor().
GetLinkedDoor()
Land_Underground_EntranceBase GetLinkedDoor ()
Definition at line 133 of file land_underground_panel.c.
    {
        if (!m_LinkedDoor)
            m_LinkedDoor = GetClosestDoor();
        return m_LinkedDoor;
    }
References GetClosestDoor(), and m_LinkedDoor.
Referenced by CanInteract(), GetLinkedDoorType(), Interact(), and Land_Underground_Panel_Lever::Interact().
GetLinkedDoorType()
EUndegroundDoorType GetLinkedDoorType ()
Definition at line 128 of file land_underground_panel.c.
    {
        return GetLinkedDoor().m_DoorType;
    }
References GetLinkedDoor(), and Land_Underground_EntranceBase::m_DoorType.
Referenced by OnDoorStateChangedClient().
Interact()
void Interact ()
Definition at line 61 of file land_underground_panel.c.
    {
        Land_Underground_EntranceBase door = GetLinkedDoor();
        if (door)
        {
            GetGame().RegisterNetworkStaticObject(this);
            Land_Underground_EntranceBase.Cast(door).Manipulate();
            GetGame().GetCallQueue( CALL_CATEGORY_SYSTEM ).CallLater( ResetPanelUsed, 500);
            m_PanelWasUsed = true;
            SetSynchDirty();
        }
        else
        {
            ErrorEx("Can't find the instance of entrance the panel is linkined to");
        }
    }
References CALL_CATEGORY_SYSTEM, ScriptCallQueue::CallLater(), ErrorEx, CGame::GetCallQueue(), GetGame(), GetLinkedDoor(), Land_Underground_EntranceBase::Manipulate(), CGame::RegisterNetworkStaticObject(), and ResetPanelUsed().
Land_Underground_Panel()
void Land_Underground_Panel ()
Definition at line 38 of file land_underground_panel.c.
    {
        RegisterNetSyncVariableBool("m_PanelWasUsed");
        RegisterPanel(this);
        SetLEDState(ELEDColors.RED, ELEDState.ON);
        SetLEDState(ELEDColors.GREEN, ELEDState.OFF);
    }
References RegisterPanel(), and SetLEDState().
Referenced by ActionUseUndergroundLever::ActionCondition(), ActionUseUndergroundPanel::ActionCondition(), Land_Underground_EntranceBase::GetConnectedPanels(), Land_Underground_EntranceBase::Land_Underground_EntranceBase(), Land_Underground_EntranceBase::OnDoorStateChangedClient(), ActionUseUndergroundLever::OnStartServer(), ActionUseUndergroundPanel::OnStartServer(), and Land_Underground_EntranceBase::~Land_Underground_EntranceBase().
OnDoorStateChangedClient()
void OnDoorStateChangedClient (EUndegroundEntranceState newState, EUndegroundEntranceState prevState)
Definition at line 270 of file land_underground_panel.c.
    {
        switch (GetLinkedDoorType())
        {
            case EUndegroundDoorType.MAIN:
            {
                if (newState >= EUndegroundEntranceState.CLOSED && newState < EUndegroundEntranceState.OPENING_G)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.ON);
                }
                else if (newState == EUndegroundEntranceState.OPENING_G)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.OFF);
                }
                else if (newState >= EUndegroundEntranceState.CLOSING_A)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.BLINKING);
                }
                if (newState == EUndegroundEntranceState.CLOSED)
                {
                    SetLEDState(ELEDColors.GREEN, ELEDState.OFF);
                }
                else if (newState >= EUndegroundEntranceState.OPENING_A && newState < EUndegroundEntranceState.OPENING_G)
                {
                    SetLEDState(ELEDColors.GREEN, ELEDState.BLINKING);
                }
                else if (newState >= EUndegroundEntranceState.OPENING_G)
                {
                    SetLEDState(ELEDColors.GREEN, ELEDState.ON);
                }
            }
            break;
            case EUndegroundDoorType.SMALL:
            {
                if (newState == EUndegroundEntranceState.OPENING_A)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.ON);
                    SetLEDState(ELEDColors.GREEN, ELEDState.BLINKING);
                }
                else if (newState == EUndegroundEntranceState.OPENING_B)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.OFF);
                    SetLEDState(ELEDColors.GREEN, ELEDState.ON);
                }
                else if (newState == EUndegroundEntranceState.CLOSING_A)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.BLINKING);
                    SetLEDState(ELEDColors.GREEN, ELEDState.ON);
                }
                if (newState == EUndegroundEntranceState.CLOSING_B || newState == EUndegroundEntranceState.CLOSED)
                {
                    SetLEDState(ELEDColors.RED, ELEDState.ON);
                    SetLEDState(ELEDColors.GREEN, ELEDState.OFF);
                }
            }
            break;
        }
    }
References GetLinkedDoorType(), and SetLEDState().
OnLEDStateChanged()
void OnLEDStateChanged ()
Definition at line 205 of file land_underground_panel.c.
    {
        /*
        Print("OnLEDStateChanged()");
        Print("m_LedStateRed: " + m_LedStateRed);
        Print("m_LedStateGreen: " + m_LedStateGreen);
        */
        if (m_LedStateRed == ELEDState.BLINKING || m_LedStateGreen == ELEDState.BLINKING)
        {
            SetBlinkingTimer(true);
        }
        else
        {
            SetBlinkingTimer(false);
        }
        //red
        if (m_LedStateRed == ELEDState.ON)
        {
            UpdateLED(SELECTION_NAME_LED_RED, COLOR_LED_RED);
        }
        else if (m_LedStateRed == ELEDState.OFF)
        {
            UpdateLED(SELECTION_NAME_LED_RED, COLOR_LED_OFF);
        }
        else if (m_LedStateRed == ELEDState.BLINKING)
        {
            if (m_BlinkingFlipFlop)
            {
                UpdateLED(SELECTION_NAME_LED_RED, COLOR_LED_RED);
            }
            else
            {
                UpdateLED(SELECTION_NAME_LED_RED, COLOR_LED_OFF);
            }
        //green
        }
        if (m_LedStateGreen == ELEDState.ON)
        {
            UpdateLED(SELECTION_NAME_LED_GREEN, COLOR_LED_GREEN);
        }
        else if (m_LedStateGreen == ELEDState.OFF)
        {
            UpdateLED(SELECTION_NAME_LED_GREEN, COLOR_LED_OFF);
        }
        else if (m_LedStateGreen == ELEDState.BLINKING)
        {
            if(m_BlinkingFlipFlop)
            {
                UpdateLED(SELECTION_NAME_LED_GREEN, COLOR_LED_GREEN);
            }
            else
            {
                UpdateLED(SELECTION_NAME_LED_GREEN, COLOR_LED_OFF);
            }
        }
    }
References COLOR_LED_GREEN, COLOR_LED_OFF, COLOR_LED_RED, m_BlinkingFlipFlop, m_LedStateGreen, m_LedStateRed, SELECTION_NAME_LED_GREEN, SELECTION_NAME_LED_RED, SetBlinkingTimer(), and UpdateLED().
Referenced by Land_Underground_Panel_Lever::OnPanelUsedSynchronized(), SetLEDState(), and ToggleFlipFlop().
OnPanelUsedSynchronized()
void OnPanelUsedSynchronized ()
Definition at line 344 of file land_underground_panel.c.
    {
        PlaySoundSet( m_ActivationSound, "UndergroundDoor_PanelActivation_SoundSet", 0, 0 );
    }
References m_ActivationSound, and PlaySoundSet().
Referenced by OnVariablesSynchronized().
OnVariablesSynchronized()
override void OnVariablesSynchronized ()
Definition at line 349 of file land_underground_panel.c.
    {
        if (m_PanelWasUsed != m_PanelWasUsedPrev)
        {
            if (m_PanelWasUsed)
            {
                OnPanelUsedSynchronized();
            }
            m_PanelWasUsedPrev = m_PanelWasUsed;
        }
    }
References m_PanelWasUsedPrev, and OnPanelUsedSynchronized().
RegisterEntrance()
static void RegisterEntrance (Land_Underground_EntranceBase entrance) static
Definition at line 78 of file land_underground_panel.c.
    {
        if (!m_Entrances)
        {
            m_Entrances = new set<Land_Underground_EntranceBase>();
        }
        m_Entrances.Insert(entrance);
    }
References m_Entrances.
RegisterPanel()
static void RegisterPanel (Land_Underground_Panel panel) static
Definition at line 103 of file land_underground_panel.c.
    {
        if (!m_Panels)
        {
            m_Panels = new set<Land_Underground_Panel>;
        }
        m_Panels.Insert(panel);
    }
References m_Panels.
Referenced by Land_Underground_Panel().
ResetPanelUsed()
void ResetPanelUsed ()
Definition at line 264 of file land_underground_panel.c.
    {
        m_PanelWasUsed = false;
        SetSynchDirty();
    }
Referenced by Interact().
SetBlinkingTimer()
void SetBlinkingTimer (bool enable)
Definition at line 186 of file land_underground_panel.c.
    {
        if (enable)
        {
            if (!m_FlipFlopTimer)
            {
                m_FlipFlopTimer = new Timer();
                m_FlipFlopTimer.Run(0.1, this, "ToggleFlipFlop", NULL, true);
            }
        }
        else
        {
            if (m_FlipFlopTimer)
            {
                m_FlipFlopTimer = null;
            }
        }
    }
References m_FlipFlopTimer.
Referenced by OnLEDStateChanged().
SetLEDState()
void SetLEDState (ELEDColors color, ELEDState state)
Definition at line 164 of file land_underground_panel.c.
    {
        #ifndef SERVER
        if (color == ELEDColors.RED)
        {
            if (m_LedStateRed != state)
            {
                m_LedStateRed = state;
                OnLEDStateChanged();
            }
        }
        else
        {
            if (m_LedStateGreen != state)
            {
                m_LedStateGreen = state;
                OnLEDStateChanged();
            }
        }
        #endif
    }
References m_LedStateGreen, m_LedStateRed, and OnLEDStateChanged().
Referenced by Land_Underground_Panel(), and OnDoorStateChangedClient().
ToggleFlipFlop()
void ToggleFlipFlop ()
Definition at line 338 of file land_underground_panel.c.
    {
        m_BlinkingFlipFlop = !m_BlinkingFlipFlop;
        OnLEDStateChanged();
    }
References m_BlinkingFlipFlop, and OnLEDStateChanged().
UnregisterEntrance()
static void UnregisterEntrance (Land_Underground_EntranceBase entrance) static
Definition at line 87 of file land_underground_panel.c.
    {
        if (m_Entrances)
        {
            int index = m_Entrances.Find(entrance);
            if (index != -1)
            {
                m_Entrances.Remove(index);
            }
            else
            {
                ErrorEx("Attempted to unregistered non-registered entrance");
            }
        }
    }
References ErrorEx, and m_Entrances.
UnregisterPanel()
static void UnregisterPanel (Land_Underground_Panel panel) static
Definition at line 112 of file land_underground_panel.c.
    {
        if (m_Panels)
        {
            int index = m_Panels.Find(panel);
            if (index != -1)
            {
                m_Panels.Remove(index);
            }
            else
            {
                ErrorEx("Attempted to unregistered non-registered panel");
            }
        }
    }
References ErrorEx, and m_Panels.
Referenced by ~Land_Underground_Panel().
UpdateLED()
protected void UpdateLED (string selection, string color)
Definition at line 331 of file land_underground_panel.c.
    {
        int selectionIdx = GetHiddenSelectionIndex(selection);
        SetObjectTexture(selectionIdx, color);
        //Print("selection: " +selection + ", color: " + color +", selectionIdx: "+ selectionIdx);
    }
Referenced by EEKilled(), OnCEUpdate(), OnLEDStateChanged(), and OnWasDetached().
~Land_Underground_Panel()
void ~Land_Underground_Panel ()
Definition at line 46 of file land_underground_panel.c.
    {
        UnregisterPanel(this);
    }
References UnregisterPanel().
Variable Documentation
COLOR_LED_GREEN
const string COLOR_LED_GREEN = "#(argb,8,8,3)color(0,1,0,1.0,co)"
Definition at line 22 of file land_underground_panel.c.
Referenced by OnLEDStateChanged().
COLOR_LED_OFF
const string COLOR_LED_OFF = "#(argb,8,8,3)color(0,0,0,1.0,co)"
Definition at line 21 of file land_underground_panel.c.
Referenced by OnLEDStateChanged(), and UpdateLED().
COLOR_LED_RED
const string COLOR_LED_RED = "#(argb,8,8,3)color(1,0,0,1.0,co)"
Definition at line 23 of file land_underground_panel.c.
Referenced by OnLEDStateChanged().
GREEN
enum ELEDState GREEN
m_ActivationSound
EffectSound m_ActivationSound
Definition at line 33 of file land_underground_panel.c.
Referenced by OnPanelUsedSynchronized().
m_BlinkingFlipFlop
bool m_BlinkingFlipFlop
Definition at line 30 of file land_underground_panel.c.
Referenced by OnLEDStateChanged(), and ToggleFlipFlop().
m_Entrances
enum ELEDState m_Entrances
Referenced by GetClosestDoor(), RegisterEntrance(), and UnregisterEntrance().
m_FlipFlopTimer
ref Timer m_FlipFlopTimer
Definition at line 31 of file land_underground_panel.c.
Referenced by SetBlinkingTimer().
m_LedStateGreen
ELEDState m_LedStateGreen
Definition at line 36 of file land_underground_panel.c.
Referenced by OnLEDStateChanged(), and SetLEDState().
m_LedStateRed
ELEDState m_LedStateRed
Definition at line 35 of file land_underground_panel.c.
Referenced by OnLEDStateChanged(), and SetLEDState().
m_LinkedDoor
Land_Underground_EntranceBase m_LinkedDoor
Definition at line 19 of file land_underground_panel.c.
Referenced by GetLinkedDoor().
m_Panels
ref set<Land_Underground_Panel> m_Panels static
Definition at line 17 of file land_underground_panel.c.
Referenced by Init(), PanelHide(), PanelShow(), RegisterPanel(), UnregisterPanel(), and Update().
m_PanelWasUsedPrev
bool m_PanelWasUsed bool m_PanelWasUsedPrev
Definition at line 29 of file land_underground_panel.c.
Referenced by OnVariablesSynchronized().
RED
enum ELEDState RED
SELECTION_NAME_LED_GREEN
const string SELECTION_NAME_LED_GREEN = "LED_Green"
Definition at line 26 of file land_underground_panel.c.
Referenced by OnLEDStateChanged().
SELECTION_NAME_LED_RED
const string SELECTION_NAME_LED_RED = "LED_Red"
Definition at line 25 of file land_underground_panel.c.
Referenced by OnLEDStateChanged().