DayzKode: P:/scripts/4_world/DayZ/entities/itembase/tentbase/largetent.c File Reference
largetent.c File Reference
Enumerations
enum SoundTypeTent { REPACK = 1 , NONE = 0 }
Functions
override void EEInit ()
override string GetClutterCutter ()
override string GetDeploySoundset ()
override string GetLoopDeploySoundset ()
override string GetSoundClose ()
override string GetSoundCloseWindow ()
override string GetSoundOpen ()
override string GetSoundOpenWindow ()
override bool HasClutterCutter ()
void LargeTent ()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
override void OnPlacementComplete (Man player, vector position="0 0 0", vector orientation="0 0 0")
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
void PlayRepackingLoopSound ()
override void SetActions ()
void StopRepackingLoopSound ()
void ~LargeTent ()
Variables
enum SoundTypeTent m_RepackingLoopSound
Enumeration Type Documentation
SoundTypeTent
enum SoundTypeTent
Enumerator
REPACK
NONE
Definition at line 1 of file largetent.c.
{
    REPACK      = 1,
    NONE        = 0,
}
Function Documentation
EEInit()
override void EEInit ()
Definition at line 86 of file largetent.c.
    {
        super.EEInit();
    }
GetClutterCutter()
override string GetClutterCutter ()
Definition at line 121 of file largetent.c.
    {
        return "LargeTentClutterCutter";
    }
GetDeploySoundset()
override string GetDeploySoundset ()
Definition at line 146 of file largetent.c.
    {
        return "placeLargeTent_SoundSet";
    }
GetLoopDeploySoundset()
override string GetLoopDeploySoundset ()
Definition at line 151 of file largetent.c.
    {
        return "largetent_deploy_SoundSet";
    }
GetSoundClose()
override string GetSoundClose ()
Definition at line 101 of file largetent.c.
    {
        return "LargeTent_Door_Close_SoundSet";
    }
GetSoundCloseWindow()
override string GetSoundCloseWindow ()
Definition at line 111 of file largetent.c.
    {
        return "LargeTent_Window_Close_SoundSet";
    }
GetSoundOpen()
override string GetSoundOpen ()
Definition at line 96 of file largetent.c.
    {
        return "LargeTent_Door_Open_SoundSet";
    }
GetSoundOpenWindow()
override string GetSoundOpenWindow ()
Definition at line 106 of file largetent.c.
    {
        return "LargeTent_Window_Open_SoundSet";
    }
HasClutterCutter()
override bool HasClutterCutter ()
Definition at line 116 of file largetent.c.
    {
        return true;
    }
LargeTent()
void LargeTent ()
Definition at line 11 of file largetent.c.
    {
        m_ToggleAnimations.Insert( new ToggleAnimations("EntranceO", "EntranceC", OPENING_0), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window1O", "Window1C", OPENING_1), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window2O", "Window2C", OPENING_2), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window3O", "Window3C", OPENING_3), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window4O", "Window4C", OPENING_4), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window5O", "Window5C", OPENING_5), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window6O", "Window6C", OPENING_6), 0 );
        m_ToggleAnimations.Insert( new ToggleAnimations("Window7O", "Window7C", OPENING_7), 0 );
        m_ShowAnimationsWhenPitched.Insert( "Body" );
        /*m_ShowAnimationsWhenPitched.Insert( "EntranceO" );
        m_ShowAnimationsWhenPitched.Insert( "Window1O" );
        m_ShowAnimationsWhenPitched.Insert( "Window2O" );
        m_ShowAnimationsWhenPitched.Insert( "Window3O" );
        m_ShowAnimationsWhenPitched.Insert( "Window4O" );
        m_ShowAnimationsWhenPitched.Insert( "Window5O" );
        m_ShowAnimationsWhenPitched.Insert( "Window6O" );
        m_ShowAnimationsWhenPitched.Insert( "Window7O" );*/
        m_ShowAnimationsWhenPitched.Insert( "Pack" );
        m_ShowAnimationsWhenPacked.Insert( "Inventory" );
        m_HalfExtents = Vector(2.2, 0.3, 1.9);
    }
References m_HalfExtents, and Vector().
OnItemLocationChanged()
override void OnItemLocationChanged (EntityAI old_owner, EntityAI new_owner)
Definition at line 91 of file largetent.c.
    {
        super.OnItemLocationChanged(old_owner, new_owner);
    }
OnPlacementComplete()
override void OnPlacementComplete (Man player, vector position = "0 0 0", vector orientation = "0 0 0")
Definition at line 130 of file largetent.c.
    {
        super.OnPlacementComplete( player, position, orientation );
        PlayerBase pb = PlayerBase.Cast( player );
        if ( GetGame().IsServer() )
        {
            if ( !m_ClutterCutter )
            {
                m_ClutterCutter = GetGame().CreateObjectEx( "LargeTentClutterCutter", pb.GetLocalProjectionPosition(), ECE_PLACE_ON_SURFACE );
                m_ClutterCutter.SetOrientation( pb.GetLocalProjectionOrientation() );
            }
        }
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, GetGame(), and m_ClutterCutter.
OnRPC()
override void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 43 of file largetent.c.
    {
        super.OnRPC(sender, rpc_type, ctx);
        Param1<bool> p = new Param1<bool>(false);
        if (ctx.Read(p))
        {
            bool play = p.param1;
        }
        switch (rpc_type)
        {
            case SoundTypeTent.REPACK:
                if ( play )
                {
                    PlayRepackingLoopSound();
                }
                if ( !play )
                {
                    StopRepackingLoopSound();
                }
            break;
        }
    }
References PlayRepackingLoopSound(), Serializer::Read(), and StopRepackingLoopSound().
PlayRepackingLoopSound()
void PlayRepackingLoopSound ()
Definition at line 72 of file largetent.c.
    {
        if ( !m_RepackingLoopSound || !m_RepackingLoopSound.IsSoundPlaying() )
        {
            m_RepackingLoopSound = SEffectManager.PlaySound( "largetent_deploy_SoundSet", GetPosition(), 0.5, 0.5 );
        }
    }
References GetPosition, m_RepackingLoopSound, and SEffectManager::PlaySound().
Referenced by OnRPC().
SetActions()
override void SetActions ()
Definition at line 156 of file largetent.c.
    {
        super.SetActions();
        //AddAction(ActionRepackTent);
    }
StopRepackingLoopSound()
void StopRepackingLoopSound ()
Definition at line 80 of file largetent.c.
    {
        m_RepackingLoopSound.SetSoundFadeOut(0.5);
        m_RepackingLoopSound.SoundStop();
    }
References m_RepackingLoopSound.
Referenced by OnRPC().
~LargeTent()
void ~LargeTent ()
Definition at line 38 of file largetent.c.
    {
        SEffectManager.DestroyEffect( m_RepackingLoopSound );
    }
References SEffectManager::DestroyEffect(), and m_RepackingLoopSound.
Variable Documentation
m_RepackingLoopSound
enum SoundTypeTent m_RepackingLoopSound
Referenced by Clothing::LargeTentBackPack(), PlayRepackingLoopSound(), Clothing::PlayRepackingLoopSound(), StopRepackingLoopSound(), Clothing::StopRepackingLoopSound(), ~LargeTent(), and Clothing::~LargeTentBackPack().