DayzKode: P:/scripts/4_world/DayZ/entities/grenade_base/m18smokegrenade_colorbase.c File Reference
m18smokegrenade_colorbase.c File Reference
Classes
class M18SmokeGrenade_ColorBase
class M18SmokeGrenade_Red
class SmokeGrenadeBase
Functions
void M18SmokeGrenade_ColorBase ()
class M18SmokeGrenade_Red_Contaminated extends M18SmokeGrenade_Red M18SmokeGrenade_Green ()
class M18SmokeGrenade_Yellow extends M18SmokeGrenade_ColorBase M18SmokeGrenade_Purple ()
class M18SmokeGrenade_ColorBase extends SmokeGrenadeBase M18SmokeGrenade_Red ()
void M18SmokeGrenade_Yellow ()
override void OnWorkStop ()
void ~M18SmokeGrenade_ColorBase ()
Variables
const string SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet"
const string SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet"
const string SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet"
Function Documentation
M18SmokeGrenade_ColorBase()
void M18SmokeGrenade_Red::M18SmokeGrenade_ColorBase ()
Definition at line 26 of file m18smokegrenade_colorbase.c.
{
    override void OnWorkStop()
    {
M18SmokeGrenade_Green()
class M18SmokeGrenade_Red_Contaminated extends M18SmokeGrenade_Red M18SmokeGrenade_Green ()
Definition at line 30 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_GREEN_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_GREEN_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_GREEN_END);
    }
M18SmokeGrenade_Purple()
class M18SmokeGrenade_Yellow extends M18SmokeGrenade_ColorBase M18SmokeGrenade_Purple ()
Definition at line 51 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_PURPLE_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_PURPLE_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_PURPLE_END);
    }
M18SmokeGrenade_Red()
class M18SmokeGrenade_ColorBase extends SmokeGrenadeBase M18SmokeGrenade_Red ()
Definition at line 1 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_RED_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_RED_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_RED_END);
    }
M18SmokeGrenade_Yellow()
void M18SmokeGrenade_Purple::M18SmokeGrenade_Yellow ()
Definition at line 64 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_PURPLE_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_PURPLE_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_PURPLE_END);
    }
}
References ParticleList::GRENADE_M18_PURPLE_END, ParticleList::GRENADE_M18_PURPLE_LOOP, ParticleList::GRENADE_M18_PURPLE_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
OnWorkStop()
override void M18SmokeGrenade_Green::OnWorkStop ()
Definition at line 44 of file m18smokegrenade_colorbase.c.
    {
        SetParticleSmokeStart(ParticleList.GRENADE_M18_GREEN_START);
        SetParticleSmokeLoop(ParticleList.GRENADE_M18_GREEN_LOOP);
        SetParticleSmokeEnd(ParticleList.GRENADE_M18_GREEN_END);
    }
}
References ParticleList::GRENADE_M18_GREEN_END, ParticleList::GRENADE_M18_GREEN_LOOP, ParticleList::GRENADE_M18_GREEN_START, SetParticleSmokeEnd(), SetParticleSmokeLoop(), and SetParticleSmokeStart().
~M18SmokeGrenade_ColorBase()
void M18SmokeGrenade_Red::~M18SmokeGrenade_ColorBase ()
Definition at line 35 of file m18smokegrenade_colorbase.c.
{
Variable Documentation
SOUND_SMOKE_END
const string SOUND_SMOKE_END = "SmokegGrenades_M18_end_loop_SoundSet"
Definition at line 24 of file m18smokegrenade_colorbase.c.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SOUND_SMOKE_LOOP
const string SOUND_SMOKE_LOOP = "SmokegGrenades_M18_active_loop_SoundSet"
Definition at line 23 of file m18smokegrenade_colorbase.c.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().
SOUND_SMOKE_START
const string SOUND_SMOKE_START = "SmokegGrenades_M18_start_loop_SoundSet"
Definition at line 22 of file m18smokegrenade_colorbase.c.
Referenced by SmokeGrenadeBase::M18SmokeGrenade_ColorBase(), and SmokeGrenadeBase::RDG2SmokeGrenade_ColorBase().