DayzKode: P:/scripts/4_world/DayZ/entities/itembase/mapnavigationbehaviour.c File Reference
mapnavigationbehaviour.c File Reference
Enumerations
enum EMapNavigationType { BASIC = 0 , COMPASS = 1 , GPS = 2 , ALL = 4 }
Functions
EMapNavigationType GetNavigationType ()
vector GetPositionRandomized ()
vector GetPositionReal ()
static bool IsOutOfMap (EntityAI pEntity)
void MapNavigationBehaviour (PlayerBase pPlayer, EMapNavigationType pNavigationType=EMapNavigationType.BASIC)
void OnItemInPlayerPossession (EntityAI item)
void OnItemNotInPlayerPossession (EntityAI item)
static array< int > OrderedAltitudeNumbersPosition (EntityAI pEntity)
static array< int > OrderedPositionNumbersFromGridCoords (EntityAI pEntity)
protected float RandomizedDeviation ()
void RandomizePosition ()
protected void SetNavigationType (EMapNavigationType pType)
protected void UnsetNavigationType (EMapNavigationType pType)
Variables
static const int DISPLAY_ALT_MAX_CHARS_COUNT = 4
static const int DISPLAY_GRID_POS_MAX_CHARS_COUNT = 3
static protected const string GRID_SIZE_CFG_PATH = "CfgWorlds %1 Grid Zoom1 stepX"
protected ref array< EntityAI > m_CompassInPossessionArr
protected ref array< EntityAI > m_GPSInPossessionArr
protected EMapNavigationType m_NavigationType
protected PlayerBase m_Player
protected int m_RandomPositionDeviationX
protected int m_RandomPositionDeviationZ
const int RANDOM_DEVIATION_MAX = 15
enum EMapNavigationType RANDOM_DEVIATION_MIN = 4
Enumeration Type Documentation
EMapNavigationType
enum EMapNavigationType
Enumerator
BASIC
COMPASS
GPS
ALL
Definition at line 1 of file mapnavigationbehaviour.c.
{
    BASIC   = 0,
    COMPASS = 1,
    GPS     = 2,
    ALL     = 4
}
Function Documentation
GetNavigationType()
EMapNavigationType GetNavigationType ()
Definition at line 46 of file mapnavigationbehaviour.c.
    {
        return m_NavigationType;
    }
References m_NavigationType.
GetPositionRandomized()
vector GetPositionRandomized ()
Definition at line 112 of file mapnavigationbehaviour.c.
    {
        vector realPosition = m_Player.GetPosition();
        vector randomizedPosition = Vector(realPosition[0] + m_RandomPositionDeviationX, realPosition[1], realPosition[2] + m_RandomPositionDeviationZ);
        return randomizedPosition;
    }
References m_Player, m_RandomPositionDeviationX, m_RandomPositionDeviationZ, and Vector().
GetPositionReal()
vector GetPositionReal ()
Definition at line 120 of file mapnavigationbehaviour.c.
    {
        return m_Player.GetPosition();
    }
References m_Player.
IsOutOfMap()
static bool IsOutOfMap (EntityAI pEntity) static
Definition at line 180 of file mapnavigationbehaviour.c.
    {
        vector worldPos = pEntity.GetPosition();
        if (worldPos[0] < 0 || worldPos[0] > GetGame().GetWorld().GetWorldSize() || worldPos[2] < 0 || worldPos[2] > GetGame().GetWorld().GetWorldSize())
        {
            return true;
        }
        return false;
    }
References GetGame().
Referenced by OrderedPositionNumbersFromGridCoords().
MapNavigationBehaviour()
void MapNavigationBehaviour (PlayerBase pPlayer, EMapNavigationType pNavigationType = EMapNavigationType.BASIC)
Definition at line 27 of file mapnavigationbehaviour.c.
    {
        m_Player                    = pPlayer;
        m_NavigationType            = pNavigationType;
        m_GPSInPossessionArr        = new array<EntityAI>();
        m_CompassInPossessionArr    = new array<EntityAI>();
    }
References m_CompassInPossessionArr, m_GPSInPossessionArr, m_NavigationType, and m_Player.
Referenced by GPSReceiver::GPSReceiver(), ManBase::Init(), UIScriptedMenu::Update(), GPSReceiver::UpdateDisplayElevation(), and GPSReceiver::UpdateDisplayPosition().
OnItemInPlayerPossession()
void OnItemInPlayerPossession (EntityAI item)
Definition at line 51 of file mapnavigationbehaviour.c.
    {
        if (item.IsInherited(ItemGPS))
        {
            if (m_GPSInPossessionArr.Find(item) == INDEX_NOT_FOUND)
            {
                m_GPSInPossessionArr.Insert(item);
                SetNavigationType(EMapNavigationType.GPS);
            }
        }
        if (item.IsInherited(ItemCompass))
        {
            if (m_CompassInPossessionArr.Find(item) == INDEX_NOT_FOUND)
            {
                m_CompassInPossessionArr.Insert(item);
                SetNavigationType(EMapNavigationType.COMPASS);
            }
        }
    }
References INDEX_NOT_FOUND, m_CompassInPossessionArr, m_GPSInPossessionArr, and SetNavigationType().
OnItemNotInPlayerPossession()
void OnItemNotInPlayerPossession (EntityAI item)
Definition at line 72 of file mapnavigationbehaviour.c.
    {
        if (item.IsInherited(ItemGPS))
        {
            m_GPSInPossessionArr.RemoveItem(item);
            if (m_GPSInPossessionArr.Count() == 0)
            {
                UnsetNavigationType(EMapNavigationType.GPS);
            }
        }
        if (item.IsInherited(ItemCompass))
        {
            m_CompassInPossessionArr.RemoveItem(item);
            if (m_CompassInPossessionArr.Count() == 0)
            {
                UnsetNavigationType(EMapNavigationType.COMPASS);
            }
        }
    }
References m_CompassInPossessionArr, m_GPSInPossessionArr, and UnsetNavigationType().
OrderedAltitudeNumbersPosition()
static array< int > OrderedAltitudeNumbersPosition (EntityAI pEntity) static
Definition at line 165 of file mapnavigationbehaviour.c.
    {
        array<int> altArray = new array<int>();
        float altF          = pEntity.GetPosition()[1];
        int altI            = Math.Round(altF);
        string altString    = altI.ToStringLen(DISPLAY_ALT_MAX_CHARS_COUNT);
        for (int i = 0; i < altString.Length(); ++i)
        {
            altArray.Insert(altString.Get(i).ToInt());
        }
        return altArray;
    }
References DISPLAY_ALT_MAX_CHARS_COUNT, string::Get(), string::Length(), Math::Round(), and string::ToInt().
OrderedPositionNumbersFromGridCoords()
static array< int > OrderedPositionNumbersFromGridCoords (EntityAI pEntity) static
Definition at line 125 of file mapnavigationbehaviour.c.
    {
        float gridSize = GetGame().ConfigGetFloat(string.Format(GRID_SIZE_CFG_PATH, GetGame().GetWorldName()));
        int gridX, gridZ;
        GetGame().GetWorld().GetGridCoords(pEntity.GetPosition(), gridSize, gridX, gridZ);
        gridX = Math.AbsInt(gridX);
        gridZ = Math.AbsInt(gridZ);
        array<int> positions    = new array<int>();
        string gridXStr         = gridX.ToStringLen(DISPLAY_GRID_POS_MAX_CHARS_COUNT);
        string gridZStr         = gridZ.ToStringLen(DISPLAY_GRID_POS_MAX_CHARS_COUNT);
        int i = 0;
        int gridCoordNumber;
        for (i = 0; i < gridXStr.Length(); ++i)
        {
            gridCoordNumber = gridXStr.Get(i).ToInt();
            if (IsOutOfMap(pEntity))
            {
                gridCoordNumber = -1;
            }
            positions.Insert(gridCoordNumber);
        }
        for (i = 0; i < gridZStr.Length(); ++i)
        {
            gridCoordNumber = gridZStr.Get(i).ToInt();
            if (IsOutOfMap(pEntity))
            {
                gridCoordNumber = -1;
            }
            positions.Insert(gridCoordNumber);
        }
        return positions;
    }
References Math::AbsInt(), CGame::ConfigGetFloat(), DISPLAY_GRID_POS_MAX_CHARS_COUNT, string::Get(), GetGame(), World::GetGridCoords(), CGame::GetWorld(), GRID_SIZE_CFG_PATH, IsOutOfMap(), string::Length(), and string::ToInt().
RandomizedDeviation()
protected float RandomizedDeviation ()
Definition at line 99 of file mapnavigationbehaviour.c.
    {
        Math.Randomize(GetWorldTime() + Math.RandomIntInclusive(2, 4096));
        if ((Math.RandomIntInclusive(0, 10) % 2) == 0)
        {
            return Math.RandomIntInclusive(-RANDOM_DEVIATION_MAX, -RANDOM_DEVIATION_MIN);
        }
        else
        {
            return Math.RandomIntInclusive(RANDOM_DEVIATION_MIN, RANDOM_DEVIATION_MAX);
        }
    }
References GetWorldTime(), RANDOM_DEVIATION_MAX, RANDOM_DEVIATION_MIN, Math::RandomIntInclusive(), and Math::Randomize().
Referenced by RandomizePosition().
RandomizePosition()
void RandomizePosition ()
Definition at line 93 of file mapnavigationbehaviour.c.
    {
        m_RandomPositionDeviationX  = RandomizedDeviation();
        m_RandomPositionDeviationZ  = RandomizedDeviation();
    }
References m_RandomPositionDeviationX, m_RandomPositionDeviationZ, and RandomizedDeviation().
Referenced by CrashBase::SpawnRandomDeers().
SetNavigationType()
protected void SetNavigationType (EMapNavigationType pType)
Definition at line 36 of file mapnavigationbehaviour.c.
    {
        m_NavigationType = m_NavigationType | pType;
    }
References m_NavigationType.
Referenced by OnItemInPlayerPossession().
UnsetNavigationType()
protected void UnsetNavigationType (EMapNavigationType pType)
Definition at line 41 of file mapnavigationbehaviour.c.
    {
        m_NavigationType = m_NavigationType & ~pType;
    }
References m_NavigationType.
Referenced by OnItemNotInPlayerPossession().
Variable Documentation
DISPLAY_ALT_MAX_CHARS_COUNT
const int DISPLAY_ALT_MAX_CHARS_COUNT = 4 static
Definition at line 15 of file mapnavigationbehaviour.c.
Referenced by OrderedAltitudeNumbersPosition().
DISPLAY_GRID_POS_MAX_CHARS_COUNT
const int DISPLAY_GRID_POS_MAX_CHARS_COUNT = 3 static
Definition at line 14 of file mapnavigationbehaviour.c.
Referenced by OrderedPositionNumbersFromGridCoords().
GRID_SIZE_CFG_PATH
protected const string GRID_SIZE_CFG_PATH = "CfgWorlds %1 Grid Zoom1 stepX" static
Definition at line 17 of file mapnavigationbehaviour.c.
Referenced by OrderedPositionNumbersFromGridCoords().
m_CompassInPossessionArr
protected ref array<EntityAI> m_CompassInPossessionArr
Definition at line 25 of file mapnavigationbehaviour.c.
Referenced by MapNavigationBehaviour(), OnItemInPlayerPossession(), and OnItemNotInPlayerPossession().
m_GPSInPossessionArr
protected ref array<EntityAI> m_GPSInPossessionArr
Definition at line 24 of file mapnavigationbehaviour.c.
Referenced by MapNavigationBehaviour(), OnItemInPlayerPossession(), and OnItemNotInPlayerPossession().
m_NavigationType
protected EMapNavigationType m_NavigationType
Definition at line 21 of file mapnavigationbehaviour.c.
Referenced by GetNavigationType(), MapNavigationBehaviour(), SetNavigationType(), and UnsetNavigationType().
m_Player
protected PlayerBase m_Player
Definition at line 22 of file mapnavigationbehaviour.c.
m_RandomPositionDeviationX
protected int m_RandomPositionDeviationX
Definition at line 19 of file mapnavigationbehaviour.c.
Referenced by GetPositionRandomized(), and RandomizePosition().
m_RandomPositionDeviationZ
protected int m_RandomPositionDeviationZ
Definition at line 20 of file mapnavigationbehaviour.c.
Referenced by GetPositionRandomized(), and RandomizePosition().
RANDOM_DEVIATION_MAX
const int RANDOM_DEVIATION_MAX = 15
Definition at line 12 of file mapnavigationbehaviour.c.
Referenced by RandomizedDeviation().
RANDOM_DEVIATION_MIN
enum EMapNavigationType RANDOM_DEVIATION_MIN = 4
Referenced by RandomizedDeviation().