DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/infectedsoundevents/events/mindstates.c File Reference
mindstates.c File Reference
Classes
class InfectedSoundEventBase
class MindStateSoundEventBase
Functions
class ChaseMoveSoundEvent extends MindStateSoundEventBase AlertedIdleSoundEvent ()
class MindStateSoundEventBase extends InfectedSoundEventBase CalmIdleSoundEvent ()
void CalmMoveSoundEvent ()
override bool CanPlay ()
void ChaseMoveSoundEvent ()
class CalmMoveSoundEvent extends MindStateSoundEventBase DisturbedIdleSoundEvent ()
Function Documentation
AlertedIdleSoundEvent()
class ChaseMoveSoundEvent extends MindStateSoundEventBase AlertedIdleSoundEvent ()
Definition at line 43 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_ALERTED_IDLE;
        m_SoundSetNameRoot = "AlertedIdle";
    }
Referenced by InfectedSoundEventHandler().
CalmIdleSoundEvent()
class MindStateSoundEventBase extends InfectedSoundEventBase CalmIdleSoundEvent ()
Definition at line 1 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_CALM_IDLE;
        m_SoundSetNameRoot = "CalmIdle";
    }
Referenced by InfectedSoundEventHandler().
CalmMoveSoundEvent()
void DisturbedIdleSoundEvent::CalmMoveSoundEvent ()
Definition at line 36 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_DISTURBED_IDLE;
        m_SoundSetNameRoot = "DisturbedIdle";
    }
}
References m_ID, m_SoundSetNameRoot, and m_Type.
Referenced by InfectedSoundEventHandler().
CanPlay()
override bool CalmIdleSoundEvent::CanPlay ()
Definition at line 16 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_CALM_IDLE;
        m_SoundSetNameRoot = "CalmIdle";
    }
}
class CalmMoveSoundEvent extends MindStateSoundEventBase
References m_ID, m_SoundSetNameRoot, and m_Type.
ChaseMoveSoundEvent()
void AlertedIdleSoundEvent::ChaseMoveSoundEvent ()
Definition at line 56 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_ALERTED_IDLE;
        m_SoundSetNameRoot = "AlertedIdle";
    }
}
References m_ID, m_SoundSetNameRoot, and m_Type.
Referenced by InfectedSoundEventHandler().
DisturbedIdleSoundEvent()
class CalmMoveSoundEvent extends MindStateSoundEventBase DisturbedIdleSoundEvent ()
Definition at line 23 of file mindstates.c.
    {
        m_Type = EInfectedSoundEventType.GENERAL;
        m_ID = EInfectedSoundEventID.MINDSTATE_DISTURBED_IDLE;
        m_SoundSetNameRoot = "DisturbedIdle";
    }
Referenced by InfectedSoundEventHandler().