DayzKode: P:/scripts/4_world/DayZ/static/miscgameplayfunctions.c File Reference
miscgameplayfunctions.c File Reference
Classes
class DestroyItemInCorpsesHandsAndCreateNewOnGndLambda
class DropEquipAndDestroyRootLambda
this one is a bit special: it drops all items and destroys the ex-root of the hierarchy
class ReplaceItemWithNewLambda
adds automatic QuickBar handling
class TurnItemIntoItemLambda
Enumerations
enum ThrowEntityFlags
enum TransferInventoryResult { Ok , DroppedSome }
Functions
static float Bobbing (float period, float amplitude, float elapsedTime)
static bool BuildCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check)
static bool BuildCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check, int constraction_index)
static bool CanIgnoreDistanceCheck (Object obj)
void ClearCache ()
static bool ComplexBuildCollideCheckClient (PlayerBase player, ActionTarget target, ItemBase item, int constraction_index)
static bool ComplexBuildCollideCheckClient (PlayerBase player, ActionTarget target, ItemBase item, string partName="")
override void CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
static array< ItemBase > CreateItemBasePiles (string item_name, vector ground_position, float quantity, float health, bool floaty_spawn=false)
Spawns multiple piles of stackable ItemBase objects on ground (intended for generic use)
static array< Magazine > CreateMagazinePiles (string item_name, vector ground_position, float quantity, float health)
static array< Magazine > CreateMagazinePilesFromBullet (string bullet_type, vector ground_position, float quantity, float health)
override protected void CreateNetworkObjectInfo (EntityAI new_item)
static void DealAbsoluteDmg (ItemBase item, float dmg)
static void DropAllItemsInInventoryInBounds (ItemBase ib, vector halfExtents)
void DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player)
static void FilterObstructedObjectsByGrouping (vector origin, float range, float distanceDelta, array< Object > objects, array< Object > obstructingObjects, out array< Object > filteredObjects, bool doDistanceCheck=false, bool checkIfDistanceCanBeIgnored=false, float maxDist=0)
group objects that are close to each other together
static void FilterObstructingObjects (array< Object > potentiallyObstructingObjects, out array< Object > obstructingObjects)
static float FModulus (float x, float y)
static void GenerateAINoiseAtPosition (vector position, float lifeTime, NoiseParams noiseParams)
static vector GetClosestSafePos (vector to_pos, notnull array< ref array< float > > positions)
static string GetColorString (float r, float g, float b, float a)
static int GetComponentIndex (array< Selection > pSelection, string pCompName)
static float GetCurrentItemHeatIsolation (ItemBase pItem)
static float GetEnergyMetabolicSpeed (int movement_speed)
static void GetHeadBonePos (notnull PlayerBase player, out vector pos)
static float GetHeadingAngle (notnull DayZPlayerImplement player)
static vector GetHeadingVector (notnull PlayerBase player)
static int GetHealthLevelForAmmo (string class_name, float health)
static string GetItemDisplayName (string type)
static float GetMaxValue (array< float > pArray)
static float GetMinValue (array< float > pArray)
static bool GetProjectedCursorPos3d (out vector position, Weapon_Base weapon)
static vector GetSteamPosition (EntityAI parent)
static float GetTypeMaxGlobalHealth (string class_name, string health_type="Health")
static float GetWaterMetabolicSpeed (int movement_speed)
static string InsertAtPos (string base, string insert, int pos)
Insert 'insert' behind index 'pos' of the 'base' string.
static bool IsComponentInSelection (array< Selection > pSelection, string pCompName)
static bool IsObjectObstructed (Object object, bool doDistanceCheck=false, vector distanceCheckPos="0 0 0", float maxDist=0)
void IsObjectObstructedCache (vector rayCastStart, int totalObjects)
static bool IsObjectObstructedEx (Object object, IsObjectObstructedCache cache, bool doDistanceCheck=false, vector distanceCheckPos="0 0 0", float maxDist=0)
static bool IsObjectObstructedFilter (Object object, IsObjectObstructedCache cache, PlayerBase player)
static bool IsObjectObstructedProxy (Object object, IsObjectObstructedCache cache, PlayerBase player)
static bool IsPlayerOrientedTowardPos (notnull DayZPlayerImplement player, vector target_pos, float cone_angle)
Check if player direction(based on cone of defined angle) is oriented to target position.
static bool IsUnderRoof (EntityAI entity, float height=GameConstants.ROOF_CHECK_RAYCAST_DIST)
static bool IsUnderRoofEx (EntityAI entity, float height=GameConstants.ROOF_CHECK_RAYCAST_DIST, int geometry=ObjIntersectView)
static void IsUnderRoofFromToCalculation (EntityAI entity, out vector from, out vector to, float height=GameConstants.ROOF_CHECK_RAYCAST_DIST)
static bool IsValueInRange (float value, float from, float to)
void MoveEquipToExistingItemAndDestroyOldRootLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI new_item)
static float Normalize (int val, int maxVal)
static string ObtainRestrainItemTargetClassname (notnull EntityAI entity)
class TurnItemIntoItemLambdaAnimSysNotifyLambda extends TurnItemIntoItemLambda OnSuccess (EntityAI new_item)
override protected void RemoveNetworkObjectInfo ()
static void RemoveSplint (PlayerBase player)
static string SanitizeString (string input)
static void SplitArrayIntoGroupsByDistance (array< Object > objects, array< ref array< Object > > objectGroups, float squaredDistanceDelta)
static void TeleportCheck (notnull PlayerBase player, notnull array< ref array< float > > safe_positions)
checks if we should teleport the player to a safe location and if so, performs the teleportation
static void ThrowAllItemsInInventory (notnull EntityAI parent, int flags)
static void ThrowEntityFromInventory (notnull EntityAI entity, vector position, float direction[4], vector force, int flags)
static TransferInventoryResult TransferInventory (EntityAI sourceItem, EntityAI targetItem, PlayerBase player)
static void TransferItemProperties (EntityAI source, notnull EntityAI target, bool transfer_agents=true, bool transfer_variables=true, bool transfer_health=true, bool exclude_quantity=false)
will transform item' variables, agents and other local scripted properties as well as any relevant non-scripted properties like health
static void TransferItemVariables (ItemBase source, ItemBase target, bool exclude_quantity=false)
static void TransformRestrainItem (EntityAI current_item, EntityAI tool, PlayerBase player_source, PlayerBase player_target, bool destroy=false)
enum ThrowEntityFlags Truncate (float value, int decimals=2)
truncate float to specified precision
static string TruncateToS (float value, int decimals=2)
truncate float to specified precision, output as string
static vector TruncateVec (vector value, int decimals=2)
truncate float to specified precision
static string TruncateVecToS (vector value, int decimals=2, string delimiter=" ")
static void TurnItemInHandsIntoItem (notnull ItemBase old_item, string new_item_type, notnull PlayerBase player)
static void TurnItemInHandsIntoItemEx (notnull PlayerBase player, ReplaceItemWithNewLambdaBase lambda)
static void TurnItemIntoItem (notnull ItemBase old_item, string new_item_type, notnull PlayerBase player)
static void TurnItemIntoItemEx (notnull PlayerBase player, ReplaceItemWithNewLambdaBase lambda)
override protected void UndoRemoveNetworkObjectInfo ()
static void UnlimitedAmmoDebugCheck (Weapon_Base weapon)
static string ValueToBar (float value, string bar="[----------]", string mark="x")
Produces ACII "progress bar" based on an 0..1 'value' input.
Variables
int ContactComponent = -1
ref set< Object > HitObjects = new set<Object>
ref array< ref RaycastRVResult > HitProxyObjects = new array<ref RaycastRVResult>
EntityAI m_NewItem
PlayerBase m_Player
NONE = 0
vector ObjectCenterPos = "0 0 0"
vector ObjectContactDir = "0 0 0"
vector ObjectContactPos = "0 0 0"
DestroyItemInCorpsesHandsAndCreateNewOnGndLambda RaycastStart = "0 0 0"
SPLIT = 1
int TotalObjects = 0
Enumeration Type Documentation
ThrowEntityFlags
enum ThrowEntityFlags
Definition at line 206 of file miscgameplayfunctions.c.
{
    NONE = 0,
    SPLIT = 1, //< Splits the item when it has quantity, recommended to use when called on an attachment
}
TransferInventoryResult
enum TransferInventoryResult
Enumerator
Ok
DroppedSome
Definition at line 201 of file miscgameplayfunctions.c.
{
    Ok, DroppedSome
};
Function Documentation
Bobbing()
static float Bobbing (float period, float amplitude, float elapsedTime) static
Definition at line 1399 of file miscgameplayfunctions.c.
    {
        //Prevent division by 0
        if ( period == 0 )
            period = 1;
        elapsedTime /= period;
        float cycle;
        cycle += elapsedTime;
        cycle = FModulus(cycle, 360);
        cycle = Math.Sin(cycle) * amplitude;
        return cycle;
    }
References FModulus(), and Math::Sin().
BuildCondition() [1/2]
static bool BuildCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check) static
Definition at line 783 of file miscgameplayfunctions.c.
    {
        return true;
    }
Referenced by ComplexBuildCollideCheckClient().
BuildCondition() [2/2]
static bool BuildCondition (PlayerBase player, ActionTarget target, ItemBase item, bool camera_check, int constraction_index) static
Definition at line 788 of file miscgameplayfunctions.c.
    {
        Object targetObject = target.GetObject();
        if ( targetObject && targetObject.CanUseConstruction() )
        {
            BaseBuildingBase base_building = BaseBuildingBase.Cast( targetObject );
            ConstructionActionData construction_action_data = player.GetConstructionActionData();
            construction_action_data.SetTarget( targetObject );
            ConstructionPart constrution_part;
            if ( item )
            {
                constrution_part = construction_action_data.GetBuildPartAtIndex(constraction_index);
            }
            else
            {
                constrution_part = construction_action_data.GetBuildPartNoToolAtIndex(constraction_index);
            }
            //Debug
            /*
            if ( constrution_part )
            {
                Construction construction = base_building.GetConstruction();
                construction.IsColliding( constrution_part.GetPartName() );
            }
            */
            if ( constrution_part )
            {
                //camera and position checks
                bool position_check = ( base_building.MustBeBuiltFromOutside() && !base_building.IsPlayerInside(player, constrution_part.GetMainPartName()) ) || ( !base_building.MustBeBuiltFromOutside() && base_building.IsPlayerInside(player, constrution_part.GetMainPartName()) );
                if ( position_check && !player.GetInputController().CameraIsFreeLook() )
                {
                    //Camera check (client-only)
                    if ( camera_check )
                    {
                        if ( GetGame() && ( !GetGame().IsDedicatedServer() ) )
{
                            return !base_building.IsFacingCamera( constrution_part.GetMainPartName() );
                        }
                    }
                    return true;
                }
            }
        }
        return false;
    }
References ConstructionActionData::GetBuildPartAtIndex(), ConstructionActionData::GetBuildPartNoToolAtIndex(), GetGame(), ConstructionPart::GetMainPartName(), CGame::IsDedicatedServer(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsPlayerInside(), BaseBuildingBase::MustBeBuiltFromOutside(), and ConstructionActionData::SetTarget().
CanIgnoreDistanceCheck()
static bool CanIgnoreDistanceCheck (Object obj) static
Definition at line 1134 of file miscgameplayfunctions.c.
    {
        return obj.IsTransport() || obj.CanUseConstruction();
    }
Referenced by FilterObstructedObjectsByGrouping().
ClearCache()
void ClearCache ()
Definition at line 1658 of file miscgameplayfunctions.c.
    {
        // TODO: What is fastest to assign to vector, "0 0 0" or Vector(0, 0, 0) ?
        ObjectCenterPos = "0 0 0";
        ObjectContactPos = "0 0 0";
        ObjectContactDir = "0 0 0";
        ContactComponent = -1;
        HitProxyObjects.Clear();
        HitObjects.Clear();
    }
References ContactComponent, HitObjects, HitProxyObjects, ObjectCenterPos, ObjectContactDir, and ObjectContactPos.
ComplexBuildCollideCheckClient() [1/2]
static bool ComplexBuildCollideCheckClient (PlayerBase player, ActionTarget target, ItemBase item, int constraction_index) static
Definition at line 746 of file miscgameplayfunctions.c.
    {
        BaseBuildingBase base_building = BaseBuildingBase.Cast( target.GetObject() );
        if (base_building)
        {
            Construction construction = base_building.GetConstruction();
            if (construction && BuildCondition( player, target, item, false, constraction_index ))
            {
                ConstructionActionData construction_action_data = player.GetConstructionActionData();
                string partName;
                if ( item )
                {
                    partName = construction_action_data.GetBuildPartAtIndex(constraction_index).GetPartName();
                }
                else
                {
                    partName = construction_action_data.GetBuildPartNoToolAtIndex(constraction_index).GetPartName();
                }
                bool boo;
                if (base_building.PerformRoofCheckForBase(partName,player,boo) && boo)
                    return false;
                if ( player.IsPlacingLocal() || player.IsPlacingServer() )
                    return false;
                /*float distance_root = vector.DistanceSq(target.GetCursorHitPos(), player.GetPosition());
                if (!CfgGameplayHandler.GetDisableDistanceCheck() && distance_root < UAMaxDistances.BASEBUILDING_SHORT)
                {
                    return false;
                } */
                return !construction.IsColliding( partName );
            }
        }
        return false;
    }
References BuildCondition(), Construction(), ConstructionActionData::GetBuildPartAtIndex(), ConstructionActionData::GetBuildPartNoToolAtIndex(), ConstructionPart::GetPartName(), and BaseBuildingBase::PerformRoofCheckForBase().
ComplexBuildCollideCheckClient() [2/2]
static bool ComplexBuildCollideCheckClient (PlayerBase player, ActionTarget target, ItemBase item, string partName = "") static
Definition at line 741 of file miscgameplayfunctions.c.
    {
        return true;
    }
CopyOldPropertiesToNew()
override void MoveEquipToExistingItemAndDestroyOldRootLambda::CopyOldPropertiesToNew (notnull EntityAI old_item, EntityAI new_item)
Definition at line 124 of file miscgameplayfunctions.c.
    {
        super.CopyOldPropertiesToNew(old_item, new_item);
        InventoryLocation understash_src = m_NewLocation; // m_NewLocation is a backup of original old_item's src before the operation started
        array<EntityAI> children = new array<EntityAI>;
        old_item.GetInventory().EnumerateInventory(InventoryTraversalType.LEVELORDER, children);
        int count = children.Count();
        for (int i = 0; i < count; i++)
        {
            EntityAI child = children.Get(i);
            if (child)
            {
                InventoryLocation child_src = new InventoryLocation;
                child.GetInventory().GetCurrentInventoryLocation(child_src);
                InventoryLocation child_dst = new InventoryLocation;
                //@TODO: modify _dst with place on gnd?
                vector m4[4];
                Math3D.MatrixIdentity4(m4);
                GameInventory.PrepareDropEntityPos(old_item, child, m4, false);
                child_dst.SetGround(child,m4);
                m_Player.LocalTakeToDst(child_src, child_dst);
                GetGame().RemoteObjectTreeCreate(child); // this forces server to send CreateVehicle Message to client. This is needed for preserving the appearance of network operations on client (so that DeleteObject(old) arrives before CreateVehicle(new)). @NOTE: this does not delete the object on server, only it's network representation.
            }
        }
    }
CreateItemBasePiles()
static array< ItemBase > CreateItemBasePiles (string item_name, vector ground_position, float quantity, float health, bool floaty_spawn = false) static
Spawns multiple piles of stackable ItemBase objects on ground (intended for generic use)
Definition at line 427 of file miscgameplayfunctions.c.
    {
        array<ItemBase> item_piles;
        float max_stack_size;
        ItemBase pile;
        item_piles = new array<ItemBase>;
        max_stack_size = g_Game.ConfigGetInt("cfgVehicles " + item_name + " varStackMax");
        if( max_stack_size < 1)
            max_stack_size = g_Game.ConfigGetInt("cfgVehicles " + item_name + " varQuantityMax");
        if( max_stack_size < 1)
            max_stack_size = 1;
        int full_piles_count = Math.Floor(quantity/max_stack_size);
        int rest = quantity - (full_piles_count*max_stack_size);
        for ( int i = 0; i < full_piles_count; i++ )
        {
            if (floaty_spawn)
                pile = ItemBase.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_CREATEPHYSICS|ECE_UPDATEPATHGRAPH));
            else
                pile = ItemBase.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
            pile.SetQuantity(max_stack_size);
            pile.SetHealth(health);
            item_piles.Insert(pile);
        }
        if ( rest > 0 )
        {
            if (floaty_spawn)
                pile = ItemBase.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_CREATEPHYSICS|ECE_UPDATEPATHGRAPH));
            else
                pile = ItemBase.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
            pile.SetQuantity(rest);
            pile.SetHealth(health);
            item_piles.Insert(pile);
        }
        return item_piles;
    }
References CGame::CreateObjectEx(), ECE_CREATEPHYSICS, ECE_PLACE_ON_SURFACE, ECE_UPDATEPATHGRAPH, Math::Floor(), g_Game, and GetGame().
CreateMagazinePiles()
static array< Magazine > CreateMagazinePiles (string item_name, vector ground_position, float quantity, float health) static
Definition at line 466 of file miscgameplayfunctions.c.
    {
        array<Magazine> items;
        float stack_size;
        Magazine pile;
        items = new array<Magazine>;
        stack_size = g_Game.ConfigGetInt("cfgMagazines " + item_name + " count");
        int piles_count = Math.Floor(quantity/stack_size);
        int rest = quantity - (piles_count*stack_size);
        for ( int i = 0; i < piles_count; i++ )
        {
            pile = Magazine.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
            pile.ServerSetAmmoCount(stack_size);
            items.Insert(pile);
        }
        if ( rest > 0)
        {
            pile = Magazine.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
            pile.ServerSetAmmoCount(rest);
            items.Insert(pile);
        }
        return items;
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, Math::Floor(), g_Game, and GetGame().
CreateMagazinePilesFromBullet()
static array< Magazine > CreateMagazinePilesFromBullet (string bullet_type, vector ground_position, float quantity, float health) static
Definition at line 493 of file miscgameplayfunctions.c.
    {
        array<Magazine> items;
        items = new array<Magazine>;
        float stack_size;
        Magazine pile;
        string item_name;
        if( !g_Game.ConfigGetText("cfgAmmo " + bullet_type + " spawnPileType", item_name) )
            return items;
        stack_size = g_Game.ConfigGetInt("cfgMagazines " + item_name + " count");
        if(stack_size > 0)
        {
            int piles_count = Math.Floor(quantity/stack_size);
            int rest = quantity - (piles_count*stack_size);
            for ( int i = 0; i < piles_count; i++ )
            {
                pile = Magazine.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
                pile.ServerSetAmmoCount(stack_size);
                items.Insert(pile);
            }
            if ( rest > 0)
            {
                pile = Magazine.Cast(GetGame().CreateObjectEx(item_name, ground_position, ECE_PLACE_ON_SURFACE));
                pile.ServerSetAmmoCount(rest);
                items.Insert(pile);
            }
        }
        return items;
    }
References CGame::CreateObjectEx(), ECE_PLACE_ON_SURFACE, Math::Floor(), g_Game, and GetGame().
CreateNetworkObjectInfo()
override protected void CreateNetworkObjectInfo (EntityAI new_item)
Definition at line 194 of file miscgameplayfunctions.c.
    {
        super.CreateNetworkObjectInfo(new_item);
        GetGame().RemoteObjectTreeCreate(m_NewItem);
    }
References GetGame(), m_NewItem, and CGame::RemoteObjectTreeCreate().
DealAbsoluteDmg()
static void DealAbsoluteDmg (ItemBase item, float dmg) static
Definition at line 1377 of file miscgameplayfunctions.c.
    {
        float totalDmg = dmg;
        //Print("The damage dealt is : " + totalDmg);
        item.DecreaseHealth(totalDmg, false);
        //Print("Current health of item is : " + item.GetHealth());
    }
DropAllItemsInInventoryInBounds()
static void DropAllItemsInInventoryInBounds (ItemBase ib, vector halfExtents) static
Definition at line 944 of file miscgameplayfunctions.c.
    {
        array<EntityAI> items = new array<EntityAI>;
        ib.GetInventory().EnumerateInventory(InventoryTraversalType.LEVELORDER, items);
        vector direction = ib.GetDirection();
        float dot = vector.Dot(direction, vector.Forward);
        float angle = Math.Acos(dot);
        if (direction[0] < 0)
            angle = -angle;
        float cos = Math.Cos(angle);
        float sin = Math.Sin(angle);
        EntityAI item;
        int count = items.Count();
        for ( int i = 0; i < count; ++i )
        {
            item = items.Get(i);
            if ( item )
                ib.GetInventory().DropEntityInBounds(InventoryMode.SERVER, ib, item, halfExtents, angle, cos, sin);
        }
    }
References Math::Acos(), Math::Cos(), vector::Dot(), vector::Forward, and Math::Sin().
DropEquipAndDestroyRootLambda()
void MoveEquipToExistingItemAndDestroyOldRootLambda::DropEquipAndDestroyRootLambda (EntityAI old_item, string new_item_type, PlayerBase player)
Definition at line 119 of file miscgameplayfunctions.c.
    {
        m_Player = player;
    }
FilterObstructedObjectsByGrouping()
static void FilterObstructedObjectsByGrouping (vector origin, float range, float distanceDelta, array< Object > objects, array< Object > obstructingObjects, out array< Object > filteredObjects, bool doDistanceCheck = false, bool checkIfDistanceCanBeIgnored = false, float maxDist = 0) static
group objects that are close to each other together
Definition at line 1140 of file miscgameplayfunctions.c.
    {
        array<Object> vicinityObjects= new array<Object>;
        vicinityObjects.Copy(objects);
        int i = 0;
        int j = 0;
        int k = 0;
        int mCount = vicinityObjects.Count();
        if (!filteredObjects)
            filteredObjects = new array<Object>;
        // Remove objects that are too far from the player anyways
        if ( doDistanceCheck )
        {
            for ( i = vicinityObjects.Count() - 1; i >= 0; --i )
            {
                Object obj = vicinityObjects[i];
                if ( obj && !CanIgnoreDistanceCheck( obj ) && vector.DistanceSq(origin, obj.GetPosition()) > maxDist * maxDist )
                    vicinityObjects.Remove(i);
            }
        }
        // Sort obstructingObjects to have the furthest one first
        array<Object> sortedObstructingObjects = new array<Object>;
        array<float> distanceHelper = new array<float>;
        array<float> distanceHelperUnsorted = new array<float>;
        float distance, dist1, dist2;
        for ( i = 0; i < obstructingObjects.Count(); ++i )
        {
            distance = vector.DistanceSq(obstructingObjects[i].GetWorldPosition(), origin);
            distanceHelper.Insert(distance);
        }
        distanceHelperUnsorted.Copy(distanceHelper);
        distanceHelper.Sort();
        for ( i = distanceHelper.Count() - 1; i >= 0; --i )
            sortedObstructingObjects.Insert(obstructingObjects[distanceHelperUnsorted.Find(distanceHelper[i])]);
        array<ref array<Object>> tempGroups = new array<ref array<Object>>;
        array<ref array<Object>> objectGroups = new array<ref array<Object>>;
        array<Object> group;
        float cos = Math.Cos(90);
        float sin = Math.Sin(90);
        // Iterate through sorted obstructingObjects
        for ( i = 0; i < sortedObstructingObjects.Count(); ++i )
        {
            Object obstrObj = sortedObstructingObjects[i];
            vector worldPos = obstrObj.GetWorldPosition();
            vector min, max;
            vector minMax[2];
            if ( obstrObj.GetCollisionBox(minMax) )
            {
                min = minMax[0];
                max = minMax[1];
                max = max * (obstrObj.GetOrientation() * range);
                vector center, dx, dy, dz, half;
                center = (min + max) * 0.5;
                dz = obstrObj.GetOrientation();
                dx = vector.RotateAroundZero(dz, vector.Up, cos, sin);
                dy = vector.RotateAroundZero(dz, vector.Aside, cos, sin);
                half = (max - min) * 0.5;
                half = Vector(Math.AbsFloat(half[0]), Math.AbsFloat(half[1]), Math.AbsFloat(half[2]));
                group = new array<Object>;
                // Group objects within the above box
                for ( j = vicinityObjects.Count() - 1; j >= 0; --j )
                {
                    Object vicObj = vicinityObjects[j];
                    if ( vicObj )
                    {
                        vector d = vicObj.GetWorldPosition() - worldPos + center;
                        if ( Math.AbsFloat(vector.Dot(d, dx)) <= half[0] && Math.AbsFloat(vector.Dot(d, dy)) <= half[1] && Math.AbsFloat(vector.Dot(d, dz)) <= half[2] )
{
                            group.Insert(vicObj);
                            vicinityObjects.Remove(j);
                        }
                    }
                }
                if ( group.Count() > 0 )
                    tempGroups.Insert(group);
            }
        }
        // Go through the objects grouped by obstruction to split them by distance too
        for ( i = 0; i < tempGroups.Count(); ++i )
            SplitArrayIntoGroupsByDistance(tempGroups[i], objectGroups, distanceDelta);
        // Split initial groups by distance
        SplitArrayIntoGroupsByDistance(vicinityObjects, objectGroups, distanceDelta);
        // Raycast accordingly to groups
        IsObjectObstructedCache cache = new IsObjectObstructedCache(origin, mCount);
        for ( i = 0; i < objectGroups.Count(); ++i )
        {
            array<Object> objectGroup = objectGroups[i];
            Object sampleObject = objectGroup[0];
            if ( !IsObjectObstructedEx(sampleObject, cache) )
                filteredObjects.InsertAll(objectGroup);
            cache.ClearCache();
        }
    }
References Math::AbsFloat(), vector::Aside, CanIgnoreDistanceCheck(), Math::Cos(), vector::DistanceSq(), vector::Dot(), GetWorldPosition(), IsObjectObstructedCache(), IsObjectObstructedEx(), vector::RotateAroundZero(), Math::Sin(), SplitArrayIntoGroupsByDistance(), vector::Up, and Vector().
FilterObstructingObjects()
static void FilterObstructingObjects (array< Object > potentiallyObstructingObjects, out array< Object > obstructingObjects) static
Definition at line 1121 of file miscgameplayfunctions.c.
    {
        if (!obstructingObjects)
            obstructingObjects = new array<Object>;
        for ( int i = 0; i < potentiallyObstructingObjects.Count(); ++i )
        {
            Object obj = potentiallyObstructingObjects[i];
            if ( obj && ( obj.CanObstruct() || obj.CanProxyObstruct() ) )
                obstructingObjects.Insert(obj);
        }
    }
FModulus()
static float FModulus (float x, float y) static
Definition at line 1416 of file miscgameplayfunctions.c.
    {
        // Keeping this for reference in case someone wants it later
        /*float res;
        //Prevent division by 0
        if (y == 0)
            y = 1;
        int n = Math.Floor(x/y);
        res = x - n * y;
        return res;*/
        return Math.ModFloat( x, y );
    }
References Math::ModFloat(), x, and y.
Referenced by Bobbing().
GenerateAINoiseAtPosition()
static void GenerateAINoiseAtPosition (vector position, float lifeTime, NoiseParams noiseParams) static
Definition at line 1529 of file miscgameplayfunctions.c.
    {
        if (GetGame().IsServer())
        {
            NoiseSystem noise = GetGame().GetNoiseSystem();
            if (noise)
            {
                noise.AddNoiseTarget(position, lifeTime, noiseParams);
            }
        }
    }
References NoiseSystem::AddNoiseTarget(), GetGame(), and CGame::GetNoiseSystem().
GetClosestSafePos()
static vector GetClosestSafePos (vector to_pos, notnull array< ref array< float > > positions) static
Definition at line 1508 of file miscgameplayfunctions.c.
    {
        vector closest_pos = to_pos;
        float smallest_dist = float.MAX;
        foreach( array<float> pos:positions)
        {
            vector vpos = "0 0 0";
            vpos[0] = pos[0];
            vpos[2] = pos[1];
            to_pos[1] = 0;
            float dist = vector.DistanceSq(to_pos, vpos);//2d dist sq
            if ( dist < smallest_dist)
            {
                smallest_dist = dist;
                closest_pos = vpos;
            }
        }
        return closest_pos;
    }
References vector::DistanceSq().
GetColorString()
static string GetColorString (float r, float g, float b, float a) static
Definition at line 240 of file miscgameplayfunctions.c.
    {
        return string.Format("#(argb,8,8,3)color(%1,CO)", string.Format("%1,%2,%3,%4", r, g, b, a));
    }
References string::Format().
GetComponentIndex()
static int GetComponentIndex (array< Selection > pSelection, string pCompName) static
Definition at line 1593 of file miscgameplayfunctions.c.
    {
        if (!MiscGameplayFunctions.IsComponentInSelection(pSelection, pCompName))
        {
            return INDEX_NOT_FOUND;
        }
        for (int i = 0; i < pSelection.Count(); ++i)
        {
            pCompName.ToLower();
            if (pSelection[i] && pSelection[i].GetName() == pCompName)
            {
                return i;
            }
        }
        return INDEX_NOT_FOUND;
    }
References GetName(), INDEX_NOT_FOUND, and string::ToLower().
GetCurrentItemHeatIsolation()
static float GetCurrentItemHeatIsolation (ItemBase pItem) static
item heat isolation (from cfg)
item health (state)
item wetness
wet factor selection
health factor selection
apply factors
Definition at line 1059 of file miscgameplayfunctions.c.
    {
        float wetFactor;
        float healthFactor;
        float heatIsolation = pItem.GetHeatIsolation();
        float itemHealthLabel = pItem.GetHealthLevel();
        float itemWetness = pItem.GetWet();
        if ( itemWetness >= GameConstants.STATE_DRY && itemWetness < GameConstants.STATE_DAMP )
        {
            wetFactor = GameConstants.ENVIRO_ISOLATION_WETFACTOR_DRY;
        }
        else if ( itemWetness >= GameConstants.STATE_DAMP && itemWetness < GameConstants.STATE_WET )
        {
            wetFactor = GameConstants.ENVIRO_ISOLATION_WETFACTOR_DAMP;
        }
        else if ( itemWetness >= GameConstants.STATE_WET && itemWetness < GameConstants.STATE_SOAKING_WET )
        {
            wetFactor = GameConstants.ENVIRO_ISOLATION_WETFACTOR_WET;
        }
        else if ( itemWetness >= GameConstants.STATE_SOAKING_WET && itemWetness < GameConstants.STATE_DRENCHED )
        {
            wetFactor = GameConstants.ENVIRO_ISOLATION_WETFACTOR_SOAKED;
        }
        else if ( itemWetness >= GameConstants.STATE_DRENCHED )
        {
            wetFactor = GameConstants.ENVIRO_ISOLATION_WETFACTOR_DRENCHED;
        }
        switch (itemHealthLabel)
        {
            case GameConstants.STATE_PRISTINE:
                healthFactor = GameConstants.ENVIRO_ISOLATION_HEALTHFACTOR_PRISTINE;
            break;
            case GameConstants.STATE_WORN:
                healthFactor = GameConstants.ENVIRO_ISOLATION_HEALTHFACTOR_WORN;
            break;
            case GameConstants.STATE_DAMAGED:
                healthFactor = GameConstants.ENVIRO_ISOLATION_HEALTHFACTOR_DAMAGED;
            break;
            case GameConstants.STATE_BADLY_DAMAGED:
                healthFactor = GameConstants.ENVIRO_ISOLATION_HEALTHFACTOR_B_DAMAGED;
            break;
            case GameConstants.STATE_RUINED:
                healthFactor = GameConstants.ENVIRO_ISOLATION_HEALTHFACTOR_RUINED;
            break;
        }
        heatIsolation *= healthFactor;
        heatIsolation *= wetFactor;
        return heatIsolation;
    }
References GameConstants::ENVIRO_ISOLATION_HEALTHFACTOR_B_DAMAGED, GameConstants::ENVIRO_ISOLATION_HEALTHFACTOR_DAMAGED, GameConstants::ENVIRO_ISOLATION_HEALTHFACTOR_PRISTINE, GameConstants::ENVIRO_ISOLATION_HEALTHFACTOR_RUINED, GameConstants::ENVIRO_ISOLATION_HEALTHFACTOR_WORN, GameConstants::ENVIRO_ISOLATION_WETFACTOR_DAMP, GameConstants::ENVIRO_ISOLATION_WETFACTOR_DRENCHED, GameConstants::ENVIRO_ISOLATION_WETFACTOR_DRY, GameConstants::ENVIRO_ISOLATION_WETFACTOR_SOAKED, GameConstants::ENVIRO_ISOLATION_WETFACTOR_WET, GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_DAMP, GameConstants::STATE_DRENCHED, GameConstants::STATE_DRY, GameConstants::STATE_PRISTINE, GameConstants::STATE_RUINED, GameConstants::STATE_SOAKING_WET, GameConstants::STATE_WET, and GameConstants::STATE_WORN.
GetEnergyMetabolicSpeed()
static float GetEnergyMetabolicSpeed (int movement_speed) static
Definition at line 611 of file miscgameplayfunctions.c.
    {
        float speed;
        switch (movement_speed)
        {
        case DayZPlayerConstants.MOVEMENTIDX_WALK:
            speed = PlayerConstants.METABOLIC_SPEED_ENERGY_WALK;
        break;
        case DayZPlayerConstants.MOVEMENTIDX_RUN:
            speed = PlayerConstants.METABOLIC_SPEED_ENERGY_JOG;
        break;
        case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
            speed = PlayerConstants.METABOLIC_SPEED_ENERGY_SPRINT;
        break;
        default:
            speed = 0;
        break;
        }
        speed += PlayerConstants.METABOLIC_SPEED_ENERGY_BASAL;
        return speed;
    }
References PlayerConstants::METABOLIC_SPEED_ENERGY_BASAL, PlayerConstants::METABOLIC_SPEED_ENERGY_JOG, PlayerConstants::METABOLIC_SPEED_ENERGY_SPRINT, and PlayerConstants::METABOLIC_SPEED_ENERGY_WALK.
GetHeadBonePos()
static void GetHeadBonePos (notnull PlayerBase player, out vector pos) static
Definition at line 583 of file miscgameplayfunctions.c.
    {
        // Get position of head for starting trace pos, otherwise use sane default
        int headBoneIdx = player.GetBoneIndexByName("Head");
        if ( headBoneIdx == -1 )
            { pos = player.GetPosition()[1] + 1.6; }
        else
            { pos = player.GetBonePositionWS(headBoneIdx); }
    }
GetHeadingAngle()
static float GetHeadingAngle (notnull DayZPlayerImplement player) static
Definition at line 603 of file miscgameplayfunctions.c.
    {
        HumanInputController hic = player.GetInputController();
        float headingAngle = hic.GetHeadingAngle();
        return headingAngle;
    }
References HumanInputController::GetHeadingAngle().
Referenced by GetHeadingVector().
GetHeadingVector()
static vector GetHeadingVector (notnull PlayerBase player) static
Definition at line 593 of file miscgameplayfunctions.c.
    {
        vector dir = vector.Zero;
        float headingAngle = GetHeadingAngle(player);
        dir[0] = Math.Cos(headingAngle + Math.PI_HALF);
        dir[2] = Math.Sin(headingAngle + Math.PI_HALF);
        return dir.Normalized();
    }
References Math::Cos(), GetHeadingAngle(), vector::Normalized(), Math::PI_HALF, Math::Sin(), and vector::Zero.
GetHealthLevelForAmmo()
static int GetHealthLevelForAmmo (string class_name, float health) static
Definition at line 526 of file miscgameplayfunctions.c.
    {
        float health_normalized = health / 100;
        string config_path = CFG_WEAPONSPATH + " " + class_name + " DamageSystem" + " GlobalHealth" + " healthLabels";
        CachedObjectsArrays.ARRAY_FLOAT.Clear();
        GetGame().ConfigGetFloatArray(config_path, CachedObjectsArrays.ARRAY_FLOAT);
        for(int i = 0; i < CachedObjectsArrays.ARRAY_FLOAT.Count(); i++)
        {
            if( health_normalized >= CachedObjectsArrays.ARRAY_FLOAT.Get(i) )
            {
                return i;
            }
        }
        return -1;
    }
References CachedObjectsArrays::ARRAY_FLOAT, CFG_WEAPONSPATH, class_name, CGame::ConfigGetFloatArray(), and GetGame().
GetItemDisplayName()
static string GetItemDisplayName (string type) static
Definition at line 1569 of file miscgameplayfunctions.c.
    {
        return GetGame().ConfigGetTextOut("CfgVehicles " + type + " displayName");
    }
References CGame::ConfigGetTextOut(), and GetGame().
GetMaxValue()
static float GetMaxValue (array< float > pArray) static
Definition at line 1555 of file miscgameplayfunctions.c.
    {
        float maxValue = 0.0;
        for (int i = 0; i < pArray.Count(); i++)
        {
            if (maxValue == 0 || pArray.Get(i) > maxValue)
            {
                maxValue = pArray.Get(i);
            }
        }
        return maxValue;
    }
GetMinValue()
static float GetMinValue (array< float > pArray) static
Definition at line 1541 of file miscgameplayfunctions.c.
    {
        float minValue = 0.0;
        for (int i = 0; i < pArray.Count(); i++)
        {
            if (minValue == 0 || pArray.Get(i) < minValue)
            {
                minValue = pArray.Get(i);
            }
        }
        return minValue;
    }
GetProjectedCursorPos3d()
static bool GetProjectedCursorPos3d (out vector position, Weapon_Base weapon) static
Definition at line 565 of file miscgameplayfunctions.c.
    {
        vector usti_hlavne_position = weapon.GetSelectionPositionMS( "usti hlavne" );
        vector konec_hlavne_position = weapon.GetSelectionPositionMS( "konec hlavne" );
        vector end_point = weapon.ModelToWorld(usti_hlavne_position);
        vector begin_point = weapon.ModelToWorld(konec_hlavne_position);
        vector contact_dir;
        int contact_component;
        vector aim_point = end_point - begin_point;
        aim_point = aim_point.Normalized() * PROJECTED_CURSOR_DISTANCE;
        aim_point = aim_point + end_point;
        if (DayZPhysics.RaycastRV(begin_point, aim_point, position, contact_dir, contact_component, null, null, null, false, false, ObjIntersectFire))
            return true;
        return false;
    }
References vector::Normalized(), PROJECTED_CURSOR_DISTANCE, and DayZPhysics::RaycastRV().
GetSteamPosition()
static vector GetSteamPosition (EntityAI parent) static
Definition at line 903 of file miscgameplayfunctions.c.
    {
        vector particle_pos;
        float steam_offset = 0;
        if ( parent )
        {
            particle_pos = parent.GetPosition();
            if ( parent.IsInherited( PortableGasStove ) )
            {
                steam_offset = 0.2;
            }
            else if ( parent.IsInherited( FireplaceBase ) )
            {
                FireplaceBase fireplace = FireplaceBase.Cast( parent );
                if ( fireplace.IsBaseFireplace() )
                {
                    steam_offset = 0.8;
                }
                else if ( fireplace.IsBarrelWithHoles() )
                {
                    steam_offset = 1.1;
                }
                else if ( fireplace.IsFireplaceIndoor() )
                {
                    steam_offset = 0.45;
                }
                else if ( fireplace.IsIndoorOven() )
                {
                    steam_offset = 0.9;
                }
            }
        }
        particle_pos[1] = particle_pos[1] + steam_offset;
        return particle_pos;
    }
References FireplaceBase::IsBarrelWithHoles(), FireplaceBase::IsBaseFireplace(), FireplaceBase::IsFireplaceIndoor(), and FireplaceBase::IsIndoorOven().
GetTypeMaxGlobalHealth()
static float GetTypeMaxGlobalHealth (string class_name, string health_type = "Health") static
Definition at line 542 of file miscgameplayfunctions.c.
    {
        float max_health;
        string cfg_path;
        if ( GetGame().ConfigIsExisting(CFG_VEHICLESPATH+" "+class_name) )
        {
            cfg_path = CFG_VEHICLESPATH;
        }
        else if ( GetGame().ConfigIsExisting(CFG_WEAPONSPATH+" "+class_name) )
        {
            cfg_path = CFG_WEAPONSPATH;
        }
        else if ( GetGame().ConfigIsExisting(CFG_MAGAZINESPATH+" "+class_name) )
        {
            cfg_path = CFG_MAGAZINESPATH;
        }
        cfg_path = cfg_path + " "+class_name+" DamageSystem GlobalHealth " + health_type + " hitpoints";
        max_health = GetGame().ConfigGetFloat(cfg_path);
        return max_health;
    }
References CFG_MAGAZINESPATH, CFG_VEHICLESPATH, CFG_WEAPONSPATH, class_name, CGame::ConfigGetFloat(), ConfigIsExisting(), and GetGame().
GetWaterMetabolicSpeed()
static float GetWaterMetabolicSpeed (int movement_speed) static
Definition at line 634 of file miscgameplayfunctions.c.
    {
        float speed;
        switch (movement_speed)
        {
        case DayZPlayerConstants.MOVEMENTIDX_WALK:
            speed = PlayerConstants.METABOLIC_SPEED_WATER_WALK;
        break;
        case DayZPlayerConstants.MOVEMENTIDX_RUN:
            speed = PlayerConstants.METABOLIC_SPEED_WATER_JOG;
        break;
        case DayZPlayerConstants.MOVEMENTIDX_SPRINT:
            speed = PlayerConstants.METABOLIC_SPEED_WATER_SPRINT;
        break;
        default:
            speed = 0;
        break;
        }
        speed += PlayerConstants.METABOLIC_SPEED_WATER_BASAL;
        return speed;
    }
References PlayerConstants::METABOLIC_SPEED_WATER_BASAL, PlayerConstants::METABOLIC_SPEED_WATER_JOG, PlayerConstants::METABOLIC_SPEED_WATER_SPRINT, and PlayerConstants::METABOLIC_SPEED_WATER_WALK.
InsertAtPos()
static string InsertAtPos (string base, string insert, int pos) static
Insert 'insert' behind index 'pos' of the 'base' string.
Definition at line 257 of file miscgameplayfunctions.c.
    {
        int length_first = pos+1;
        int length_base = base.Length();
        int length_second = length_base - length_first;
        string first = base.Substring(0,length_first);
        string second = base.Substring(pos+1,length_second);
        return first + insert + second;
    }
References string::Length(), and string::Substring().
Referenced by ValueToBar().
IsComponentInSelection()
static bool IsComponentInSelection (array< Selection > pSelection, string pCompName) static
Definition at line 1574 of file miscgameplayfunctions.c.
    {
        if (pSelection.Count() == 0 || pCompName.Length() == 0)
        {
            return false;
        }
        for (int i = 0; i < pSelection.Count(); ++i)
        {
            pCompName.ToLower();
            if (pSelection[i] && pSelection[i].GetName() == pCompName)
            {
                return true;
            }
        }
        return false;
    }
References GetName(), string::Length(), and string::ToLower().
Referenced by ScriptedWidgetEventHandler::GetOnScreenPosition().
IsObjectObstructed()
static bool IsObjectObstructed (Object object, bool doDistanceCheck = false, vector distanceCheckPos = "0 0 0", float maxDist = 0) static
Definition at line 1287 of file miscgameplayfunctions.c.
    {
        vector rayStart;
        MiscGameplayFunctions.GetHeadBonePos( PlayerBase.Cast( GetGame().GetPlayer() ), rayStart);
        IsObjectObstructedCache cache = new IsObjectObstructedCache(rayStart, 1);
        return IsObjectObstructedEx(object, cache, doDistanceCheck, distanceCheckPos, maxDist);
    }
References GetGame(), GetPlayer(), IsObjectObstructedCache(), and IsObjectObstructedEx().
IsObjectObstructedCache()
void IsObjectObstructedCache (vector rayCastStart, int totalObjects)
Definition at line 1651 of file miscgameplayfunctions.c.
    {
        RaycastStart = rayCastStart;
        TotalObjects = totalObjects;
    }
References RaycastStart, and TotalObjects.
Referenced by ActionTargets::FilterObstructedObjects(), FilterObstructedObjectsByGrouping(), IsObjectObstructed(), and ActionTargets::IsObstructed().
IsObjectObstructedEx()
static bool IsObjectObstructedEx (Object object, IsObjectObstructedCache cache, bool doDistanceCheck = false, vector distanceCheckPos = "0 0 0", float maxDist = 0) static
Definition at line 1295 of file miscgameplayfunctions.c.
    {
        if (!object)
            return true;
        PlayerBase player = PlayerBase.Cast(g_Game.GetPlayer());
        if (doDistanceCheck && vector.DistanceSq(player.GetPosition(), distanceCheckPos) > maxDist * maxDist)
            return true;
        cache.ObjectCenterPos = object.GetCenter();
        if (IsObjectObstructedProxy(object, cache, player))
            return true;
        //Print(" ===>>> pouzij standardny raycast s fire geometriou koli domom a basebuildingu <<<=== ");
        DayZPhysics.RaycastRV( cache.RaycastStart, cache.ObjectCenterPos, cache.ObjectContactPos, cache.ObjectContactDir, cache.ContactComponent, cache.HitObjects, object, GetGame().GetPlayer(), false, false, ObjIntersectFire, 0.0, CollisionFlags.ALLOBJECTS );
        return IsObjectObstructedFilter(object, cache, player);
    }
References vector::DistanceSq(), g_Game, GetGame(), GetPlayer(), IsObjectObstructedFilter(), IsObjectObstructedProxy(), and DayZPhysics::RaycastRV().
Referenced by FilterObstructedObjectsByGrouping(), and IsObjectObstructed().
IsObjectObstructedFilter()
static bool IsObjectObstructedFilter (Object object, IsObjectObstructedCache cache, PlayerBase player) static
Definition at line 1349 of file miscgameplayfunctions.c.
    {
        for ( int m = 0; m < cache.HitObjects.Count(); m++ )
        {
            Object hit_object = cache.HitObjects.Get(m);
            if ( hit_object.CanObstruct() )
                return true;
            //4.3. ignore item if items are big and heavy >= OBJECT_OBSTRUCTION_WEIGHT
            //EntityAI eai;
            //if ( Class.CastTo( eai, hit_object ) )
            //{
            //  if ( eai.GetWeight() >= OBJECT_OBSTRUCTION_WEIGHT )
            //  {
            //      if ( eai != filtered_object && eai.GetHierarchyRoot() != filtered_object )
            //      {
            //          //Print("!!!!!obstacle vaha: " + hit_object);
            //          is_obstructed = true;
            //      }
            //  }
            //}
        }
        return false;
    }
Referenced by IsObjectObstructedEx().
IsObjectObstructedProxy()
static bool IsObjectObstructedProxy (Object object, IsObjectObstructedCache cache, PlayerBase player) static
Definition at line 1315 of file miscgameplayfunctions.c.
    {
        if ( object.CanProxyObstruct() )
        {
            //Print(" :) (: pouzij proxy raycast koli proxy itemom :) (: ");
            RaycastRVParams ray_input = new RaycastRVParams( cache.RaycastStart, cache.ObjectCenterPos, player );
            DayZPhysics.RaycastRVProxy( ray_input, cache.HitProxyObjects );
            if ( cache.HitProxyObjects )
            {
                //Print(" - cache.HitProxyObjects - ");
                if ( cache.HitProxyObjects.Count() > 0 )
                {
                    if ( cache.HitProxyObjects[0].hierLevel > 0 )
                    {
                        // ignores attachments on player
                        if ( !cache.HitProxyObjects[0].parent.IsMan() )
{
                            //Print( "cache.HitProxyObjects[0].obj " + cache.HitProxyObjects[0].obj );
                            //Print( "cache.HitProxyObjects[0].parent" + cache.HitProxyObjects[0].parent );
                            if ( cache.HitProxyObjects[0].parent )
{
                                EntityAI proxy_parent = EntityAI.Cast( cache.HitProxyObjects[0].parent );
                                if ( proxy_parent.GetInventory() && proxy_parent.GetInventory().GetCargo() )
                                    return true;
                            }
                        }
                    }
                }
            }
        }
        return false;
    }
References CanProxyObstruct(), and DayZPhysics::RaycastRVProxy().
Referenced by IsObjectObstructedEx().
IsPlayerOrientedTowardPos()
static bool IsPlayerOrientedTowardPos (notnull DayZPlayerImplement player, vector target_pos, float cone_angle) static
Check if player direction(based on cone of defined angle) is oriented to target position.
dir in cone or in a tip of cone
Definition at line 699 of file miscgameplayfunctions.c.
    {
        if (player)
        {
            vector player_dir = player.GetDirection();
            vector to_target_dir = target_pos - player.GetPosition();
            player_dir[1] = 0;
            to_target_dir[1] = 0;
            player_dir.Normalize();
            to_target_dir.Normalize();
            float cos_fi = vector.Dot(player_dir, to_target_dir);
            vector cross = player_dir * to_target_dir;
            int dir = Math.Acos(cos_fi) * Math.RAD2DEG;
            if( cross[1] < 0 )
                dir = -dir;
            if( (dir <= cone_angle && dir >= -cone_angle) || Math.AbsFloat(dir) == 90 )
            {
                return true;
            }
        }
        return false;
    }
References Math::AbsFloat(), Math::Acos(), vector::Dot(), vector::Normalize(), and Math::RAD2DEG.
IsUnderRoof()
static bool IsUnderRoof (EntityAI entity, float height = GameConstants.ROOF_CHECK_RAYCAST_DIST) static
Definition at line 869 of file miscgameplayfunctions.c.
    {
        return IsUnderRoofEx(entity, height, ObjIntersectView);
    }
References IsUnderRoofEx().
IsUnderRoofEx()
static bool IsUnderRoofEx (EntityAI entity, float height = GameConstants.ROOF_CHECK_RAYCAST_DIST, int geometry = ObjIntersectView) static
Definition at line 874 of file miscgameplayfunctions.c.
    {
        vector from;
        vector to;
        IsUnderRoofFromToCalculation(entity, from, to, height);
        vector contact_pos;
        vector contact_dir;
        int contact_component;
        //set<Object> hit_object = new set<Object>;
        bool boo = DayZPhysics.RaycastRV( from, to, contact_pos, contact_dir, contact_component, /*hit_object*/NULL, NULL, entity, false, false, geometry,0.25 );
        /*if (boo)
        {
            Debug.DrawSphere(from , 0.8,Colors.YELLOW, ShapeFlags.ONCE);
            Debug.DrawSphere(to , 0.8,Colors.RED, ShapeFlags.ONCE);
        }
        else
        {
            Debug.DrawSphere(from , 0.8,Colors.GREEN, ShapeFlags.ONCE);
            Debug.DrawSphere(to , 0.8,Colors.RED, ShapeFlags.ONCE);
        }*/
        return boo;
    }
References IsUnderRoofFromToCalculation(), and DayZPhysics::RaycastRV().
Referenced by IsUnderRoof().
IsUnderRoofFromToCalculation()
static void IsUnderRoofFromToCalculation (EntityAI entity, out vector from, out vector to, float height = GameConstants.ROOF_CHECK_RAYCAST_DIST) static
Definition at line 839 of file miscgameplayfunctions.c.
    {
        vector minMax[2];
        entity.GetCollisionBox(minMax);
        vector size = Vector(0,0,0);
        //size[1] = minMax[1][1] - minMax[0][1];
        float from_override = entity.HeightStartCheckOverride();
        if (from_override > 0.0)
        {
            size[1] = from_override;
        }
        else
        {
            size[1] = minMax[1][1] - minMax[0][1];
        }
        from = entity.GetPosition() + size;
        if ( entity.HeightCheckOverride() > 0 )
        {
            to = entity.GetPosition() + Vector(0, entity.HeightCheckOverride(), 0);
        }
        else
        {
            vector ceiling = "0 0 0";
            ceiling[1] = height;
            to = from + ceiling; //+size ??? offset to cast same distance
        }
    }
References Vector().
Referenced by IsUnderRoofEx().
IsValueInRange()
static bool IsValueInRange (float value, float from, float to) static
Definition at line 693 of file miscgameplayfunctions.c.
    {
        return (value >= from) && (value <= to);
    }
MoveEquipToExistingItemAndDestroyOldRootLambda()
void MoveEquipToExistingItemAndDestroyOldRootLambda (EntityAI old_item, string new_item_type, PlayerBase player, EntityAI new_item)
Definition at line 167 of file miscgameplayfunctions.c.
    {
        m_Player = player;
        m_NewItem = new_item;
        if (new_item_type != string.Empty)
            Error("MoveEquipAndDestroyRootLambda expects new_item_type to be empty");
    }
References Empty, Error(), m_NewItem, and m_Player.
Normalize()
static float Normalize (int val, int maxVal) static
Definition at line 1386 of file miscgameplayfunctions.c.
    {
        float normVal;
        if (maxVal == 0)
        {
            Debug.LogError("Division by 0 is not allowed");
            return 0;
        }
        normVal = val / maxVal;
        return normVal;
    }
References Debug::LogError().
ObtainRestrainItemTargetClassname()
static string ObtainRestrainItemTargetClassname (notnull EntityAI entity) static
Definition at line 657 of file miscgameplayfunctions.c.
    {
        return entity.ConfigGetString( "OnRestrainChange");
    }
OnSuccess()
class TurnItemIntoItemLambdaAnimSysNotifyLambda extends TurnItemIntoItemLambda OnSuccess (EntityAI new_item)
Definition at line 91 of file miscgameplayfunctions.c.
    {
        super.OnSuccess(new_item);
        m_Player.SetRestrained(true);
    }
RemoveNetworkObjectInfo()
override protected void RemoveNetworkObjectInfo ()
Definition at line 175 of file miscgameplayfunctions.c.
    {
        super.RemoveNetworkObjectInfo();
        GetGame().RemoteObjectTreeDelete(m_NewItem);
    }
References GetGame(), m_NewItem, and CGame::RemoteObjectTreeDelete().
RemoveSplint()
static void RemoveSplint (PlayerBase player) static
Definition at line 1430 of file miscgameplayfunctions.c.
    {
        EntityAI entity = player.GetInventory().CreateInInventory("Splint");
        if (!entity)
            entity = player.SpawnEntityOnGroundOnCursorDir("Splint", 0.5);
        EntityAI attachment;
        ItemBase new_item = ItemBase.Cast(entity);
        Class.CastTo(attachment, player.GetItemOnSlot("Splint_Right"));
        if ( attachment && attachment.GetType() == "Splint_Applied" )
        {
            if (new_item)
            {
                MiscGameplayFunctions.TransferItemProperties(attachment,new_item);
                if (GetGame().IsServer())
                {
                    //Lower health level of splint after use
                    if (new_item.GetHealthLevel() < 4)
                    {
                        int newDmgLevel = new_item.GetHealthLevel() + 1;
                        float max = new_item.GetMaxHealth("","");
                        switch ( newDmgLevel )
{
                            case GameConstants.STATE_BADLY_DAMAGED:
                                new_item.SetHealth( "", "", max * GameConstants.DAMAGE_BADLY_DAMAGED_VALUE );
                                break;
                            case GameConstants.STATE_DAMAGED:
                                new_item.SetHealth( "", "", max * GameConstants.DAMAGE_DAMAGED_VALUE );
                                break;
                            case GameConstants.STATE_WORN:
                                new_item.SetHealth( "", "", max * GameConstants.DAMAGE_WORN_VALUE );
                                break;
                            case GameConstants.STATE_RUINED:
                                new_item.SetHealth( "", "", max * GameConstants.DAMAGE_RUINED_VALUE );
                                break;
                            default:
                                break;
                        }
                    }
                }
            }
            attachment.Delete();
        }
    }
References Class::CastTo(), GameConstants::DAMAGE_BADLY_DAMAGED_VALUE, GameConstants::DAMAGE_DAMAGED_VALUE, GameConstants::DAMAGE_RUINED_VALUE, GameConstants::DAMAGE_WORN_VALUE, GetGame(), GameConstants::STATE_BADLY_DAMAGED, GameConstants::STATE_DAMAGED, GameConstants::STATE_RUINED, and GameConstants::STATE_WORN.
SanitizeString()
static string SanitizeString (string input) static
Definition at line 731 of file miscgameplayfunctions.c.
    {
        int max_length = 512;
        string output = input;
        output = output.Substring(0,Math.Clamp(max_length,0,output.Length()));
        return output;
    }
References Math::Clamp(), string::Length(), and string::Substring().
SplitArrayIntoGroupsByDistance()
static void SplitArrayIntoGroupsByDistance (array< Object > objects, array< ref array< Object > > objectGroups, float squaredDistanceDelta) static
Definition at line 1253 of file miscgameplayfunctions.c.
    {
        array<Object> group;
        for ( int i = 0; i < objects.Count(); )
        {
            Object obj1 = objects[i];
            if ( obj1 )
            {
                group = new array<Object>;
                group.Insert(obj1);
                for ( int j = objects.Count() - 1; j > i; --j )
                {
                    Object obj2 = objects[j];
                    if ( obj1 && obj2 )
                    {
                        vector start = obj1.GetWorldPosition();
                        vector end = obj2.GetWorldPosition();
                        float distance = vector.DistanceSq(start, end);
                        if ( distance < squaredDistanceDelta )
{
                            group.Insert(obj2);
                            objects.Remove(j);
                        }
                    }
                }
                objectGroups.Insert(group);
                objects.Remove(i);
                continue;
            }
            ++i;
        }
    }
References vector::DistanceSq().
Referenced by FilterObstructedObjectsByGrouping().
TeleportCheck()
static void TeleportCheck (notnull PlayerBase player, notnull array< ref array< float > > safe_positions) static
checks if we should teleport the player to a safe location and if so, performs the teleportation
Definition at line 1484 of file miscgameplayfunctions.c.
    {
        if( player.GetSimulationTimeStamp() < 20 && !player.IsPersistentFlag(PersistentFlag.AREA_PRESENCE) )
        {
            //simulation time is bellow a threshold, which means the player has recently connected,
            //the player does not have the AREA_PRESENCE flag set, which means they were not inside the area when they disconnected,
            //that means they just spawned into a contaminated area, lets move them somewhere safe
            vector player_pos = player.GetPosition();
            vector closest_safe_pos = MiscGameplayFunctions.GetClosestSafePos(player_pos, safe_positions);
            if (player_pos!=closest_safe_pos)
            {
                closest_safe_pos[1] = GetGame().SurfaceY(closest_safe_pos[0], closest_safe_pos[2]);
                player.SetPosition( closest_safe_pos );//...so lets teleport them somewhere safe
                //DeveloperTeleport.SetPlayerPosition(player, closest_safe_pos);
                GetGame().RPCSingleParam(player, ERPCs.RPC_WARNING_TELEPORT, null, true, player.GetIdentity());
            }
            player.SetPersistentFlag(PersistentFlag.AREA_PRESENCE, false);
        }
    }
References GetGame(), CGame::RPCSingleParam(), and CGame::SurfaceY().
ThrowAllItemsInInventory()
static void ThrowAllItemsInInventory (notnull EntityAI parent, int flags) static
Definition at line 969 of file miscgameplayfunctions.c.
    {
        vector position = parent.GetPosition();
        vector orientation = parent.GetOrientation();
        vector rotation_matrix[3];
        float direction[4];
        vector minmax[2];
        parent.GetCollisionBox(minmax);
        Math3D.YawPitchRollMatrix( orientation, rotation_matrix );
        Math3D.MatrixToQuat( rotation_matrix, direction );
        vector randomPos;
        for ( int i = 0; i < parent.GetInventory().AttachmentCount(); ++i )
        {
            randomPos = Vector(position[0] + Math.RandomFloat(minmax[0][0], minmax[1][0]),
                                position[1] + Math.RandomFloat(minmax[0][1], minmax[1][1]),
                                position[2] + Math.RandomFloat(minmax[0][2], minmax[1][2]));
            ThrowEntityFromInventory(parent.GetInventory().GetAttachmentFromIndex( i ), randomPos, direction, -GetVelocity(parent), ThrowEntityFlags.NONE);
        }
        for ( int j = 0; j < parent.GetInventory().GetCargo().GetItemCount(); ++j )
        {
            randomPos = Vector(position[0] + Math.RandomFloat(minmax[0][0], minmax[1][0]),
                                position[1] + Math.RandomFloat(minmax[0][1], minmax[1][1]),
                                position[2] + Math.RandomFloat(minmax[0][2], minmax[1][2]));
            ThrowEntityFromInventory(parent.GetInventory().GetCargo().GetItem( j ), randomPos, direction, -GetVelocity(parent), ThrowEntityFlags.NONE);
        }
    }
References AttachmentCount(), GetCargo(), GetVelocity(), Math3D::MatrixToQuat(), Math::RandomFloat(), ThrowEntityFromInventory(), Vector(), and Math3D::YawPitchRollMatrix().
ThrowEntityFromInventory()
static void ThrowEntityFromInventory (notnull EntityAI entity, vector position, float direction[4], vector force, int flags) static
Definition at line 1002 of file miscgameplayfunctions.c.
    {
        InventoryMode invMode = InventoryMode.SERVER;
        if ( !GetGame().IsMultiplayer() )
            invMode = InventoryMode.LOCAL;
        ItemBase entityIB;
        if (CastTo(entityIB, entity))
        {
            InventoryLocation dst = new InventoryLocation;
            dst.SetGroundEx(entity, position, direction);
            if ( (flags & ThrowEntityFlags.SPLIT) && entityIB.CanBeSplit() )
            {
                for (int l = 0; l < entityIB.GetQuantity(); ++l)
                {
                    ItemBase new_item = ItemBase.Cast( GameInventory.LocationCreateEntity( dst, entityIB.GetType(), ECE_NONE, RF_DEFAULT ) );
                    if ( new_item )
                    {
                        MiscGameplayFunctions.TransferItemProperties(entityIB, new_item);
                        entityIB.AddQuantity( -1 );
                        new_item.SetQuantity( 1 );
                        new_item.ThrowPhysically(null, force);
                    }
                }
            }
            else
            {
                float stackable = entityIB.GetTargetQuantityMax();
                if ( !(stackable == 0 || stackable >= entityIB.GetQuantity()) )
                {
                    while (entityIB.GetQuantity() > stackable)
                    {
                        InventoryLocation spltDst = new InventoryLocation;
                        position[1] = position[1] + 0.1;
                        spltDst.SetGroundEx(entity, position, direction);
                        ItemBase splitItem = entityIB.SplitIntoStackMaxToInventoryLocationEx( spltDst );
                        splitItem.ThrowPhysically(null, force);
                    }
                }
                InventoryLocation src = new InventoryLocation;
                entity.GetInventory().GetCurrentInventoryLocation(src);
                entity.GetInventory().TakeToDst(invMode, src, dst);
                entityIB.ThrowPhysically(null, force);
            }
        }
        else
        {
            entity.GetInventory().DropEntity(invMode, entity.GetHierarchyRoot(), entity);
            dBodyApplyImpulse(entity, force);
        }
    }
References dBodyApplyImpulse(), ECE_NONE, GetGame(), RF_DEFAULT, and InventoryLocation::SetGroundEx().
Referenced by ThrowAllItemsInInventory().
TransferInventory()
static TransferInventoryResult TransferInventory (EntityAI sourceItem, EntityAI targetItem, PlayerBase player) static
Definition at line 329 of file miscgameplayfunctions.c.
    {
        TransferInventoryResult result = TransferInventoryResult.Ok;
        array<EntityAI> children = new array<EntityAI>;
        sourceItem.GetInventory().EnumerateInventory(InventoryTraversalType.LEVELORDER, children);
        int count = children.Count();
        for (int i = 0; i < count; i++)
        {
            EntityAI child = children.Get(i);
            if (child)
            {
                InventoryLocation child_src = new InventoryLocation;
                child.GetInventory().GetCurrentInventoryLocation( child_src );
                InventoryLocation child_dst = new InventoryLocation;
                child_dst.Copy( child_src );
                child_dst.SetParent( targetItem );
                bool drop = false;
                if (GameInventory.LocationCanAddEntity(child_dst))
                {
                    // try to move it to the same exact place in dst
                    targetItem.GetInventory().TakeToDst(InventoryMode.LOCAL, child_src, child_dst);
                }
                else
                {
                    drop = true; // or drop otherwise
                }
                if (drop)
                {
                    player.LocalDropEntity(child);
                    GetGame().RemoteObjectTreeCreate(child);
                    result = TransferInventoryResult.DroppedSome;
                }
            }
        }
        return result;
    }
References InventoryLocation::Copy(), GetGame(), CGame::RemoteObjectTreeCreate(), and InventoryLocation::SetParent().
TransferItemProperties()
static void TransferItemProperties (EntityAI source, notnull EntityAI target, bool transfer_agents = true, bool transfer_variables = true, bool transfer_health = true, bool exclude_quantity = false) static
will transform item' variables, agents and other local scripted properties as well as any relevant non-scripted properties like health
Definition at line 268 of file miscgameplayfunctions.c.
    {
        ItemBase target_ib = ItemBase.Cast(target);
        ItemBase source_ib = ItemBase.Cast(source);
        if( transfer_agents ) target_ib.TransferAgents( source.GetAgents() );
        if( transfer_variables )
        {
            MiscGameplayFunctions.TransferItemVariables(source_ib, target_ib, exclude_quantity);
        }
        if( !GetGame().IsClient())
        {
            //if( transfer_health ) target_ib.SetHealth("", "", source.GetHealth("",""));
            target_ib.SetHealth("", "", source.GetHealth01("","") * target_ib.GetMaxHealth("",""));
        }
    }
References GetGame().
TransferItemVariables()
static void TransferItemVariables (ItemBase source, ItemBase target, bool exclude_quantity = false) static
Definition at line 287 of file miscgameplayfunctions.c.
    {
        target.TransferVariablesFloat( source.GetVariablesFloat() );
        //target.TransferVariablesString( source.GetVariablesString() );
        if ( exclude_quantity )
        {
            target.RemoveItemVariable(VARIABLE_QUANTITY);
        }
        else if ( source.IsMagazine() && target.IsMagazine() )
        {
            Magazine source_mag = Magazine.Cast(source);
            Magazine target_mag = Magazine.Cast(target);
            target_mag.ServerSetAmmoCount( source_mag.GetAmmoCount() );
        }
        if ( source.IsWeapon() && target.IsWeapon() )
        {
            Weapon_Base source_wpn = Weapon_Base.Cast(source);
            Weapon_Base target_wpn = Weapon_Base.Cast(target);
            target_wpn.CopyWeaponStateFrom(source_wpn);
        }
        else if ( source.HasEnergyManager() && target.HasEnergyManager() )
        {
            ComponentEnergyManager ems = source.GetCompEM();
            ComponentEnergyManager emt = target.GetCompEM();
            emt.SetEnergy(ems.GetEnergy());
            if (ems.IsSwitchedOn())
                emt.SwitchOn();
        }
        else if ( source.CanDecay() && target.CanDecay() )
        {
            Edible_Base source_edb = Edible_Base.Cast(source);
            Edible_Base target_edb = Edible_Base.Cast(target);
            target_edb.TransferFoodStage(source_edb);
        }
    }
References ItemBase::CanDecay(), ComponentEnergyManager::GetEnergy(), ComponentEnergyManager::IsSwitchedOn(), ComponentEnergyManager::SetEnergy(), ComponentEnergyManager::SwitchOn(), and VARIABLE_QUANTITY.
TransformRestrainItem()
static void TransformRestrainItem (EntityAI current_item, EntityAI tool, PlayerBase player_source, PlayerBase player_target, bool destroy = false) static
Definition at line 662 of file miscgameplayfunctions.c.
    {
        bool type;
        if ( tool )
        {
            //is unrestrain and not struggle
            type = tool.ConfigGetBool("RestrainUnlockType");
        }
        string new_item_name = current_item.ConfigGetString( "OnRestrainChange");
        if ( new_item_name != "" )
        {
            if ( player_target )
            {
                if (player_target.IsAlive())
                    MiscGameplayFunctions.TurnItemIntoItemEx(player_target, new ReplaceAndDestroyLambdaEx(current_item, new_item_name, player_target, type));
                else
                    MiscGameplayFunctions.TurnItemIntoItemEx(player_source, new DestroyItemInCorpsesHandsAndCreateNewOnGndLambda(current_item, new_item_name, player_target, type));
            }
            else
            {
                MiscGameplayFunctions.TurnItemIntoItemEx(player_target, new ReplaceAndDestroyLambdaEx(current_item, new_item_name, player_target, type));
            }
        }
        else
        {
            Error("current_item:" +current_item+ ", tool:" +tool +". No value for 'OnRestrainChange' config parameter");
        }
    }
References Error().
Truncate()
enum ThrowEntityFlags Truncate (float value, int decimals = 2)
truncate float to specified precision
Definition at line 194 of file miscgameplayfunctions.c.
    {
        int multiplier = Math.Pow(10,decimals);
        return Math.Clamp(Math.Floor(value * multiplier),float.LOWEST, float.MAX) / multiplier;
    }
Referenced by TruncateToS().
TruncateToS()
static string TruncateToS (float value, int decimals = 2) static
truncate float to specified precision, output as string
Definition at line 221 of file miscgameplayfunctions.c.
    {
        return Truncate(value, decimals).ToString();
    }
References Truncate().
TruncateVec()
static vector TruncateVec (vector value, int decimals = 2) static
truncate float to specified precision
Definition at line 226 of file miscgameplayfunctions.c.
    {
        int multiplier = Math.Pow(10,decimals);
        float v1 = Math.Clamp(Math.Floor(value[0] * multiplier),float.LOWEST, float.MAX) / multiplier;
        float v2 = Math.Clamp(Math.Floor(value[1] * multiplier),float.LOWEST, float.MAX) / multiplier;
        float v3 = Math.Clamp(Math.Floor(value[2] * multiplier),float.LOWEST, float.MAX) / multiplier;
        return Vector(v1,v2,v3);
    }
References Math::Clamp(), Math::Floor(), float::LOWEST, float::MAX, Math::Pow(), and Vector().
TruncateVecToS()
static string TruncateVecToS (vector value, int decimals = 2, string delimiter = " ") static
Definition at line 235 of file miscgameplayfunctions.c.
    {
        return MiscGameplayFunctions.TruncateToS(value[0],decimals) + delimiter + MiscGameplayFunctions.TruncateToS(value[1],decimals) +delimiter + MiscGameplayFunctions.TruncateToS(value[2],decimals));
    }
TurnItemInHandsIntoItem()
static void TurnItemInHandsIntoItem (notnull ItemBase old_item, string new_item_type, notnull PlayerBase player) static
Definition at line 416 of file miscgameplayfunctions.c.
    {
        TurnItemInHandsIntoItemEx(player, new TurnItemIntoItemLambda(old_item, new_item_type, player));
    }
References TurnItemInHandsIntoItemEx().
TurnItemInHandsIntoItemEx()
static void TurnItemInHandsIntoItemEx (notnull PlayerBase player, ReplaceItemWithNewLambdaBase lambda) static
Definition at line 421 of file miscgameplayfunctions.c.
    {
        player.ServerReplaceItemInHandsWithNew(lambda);
    }
Referenced by TurnItemInHandsIntoItem().
TurnItemIntoItem()
static void TurnItemIntoItem (notnull ItemBase old_item, string new_item_type, notnull PlayerBase player) static
Definition at line 406 of file miscgameplayfunctions.c.
    {
        TurnItemIntoItemEx(player, new TurnItemIntoItemLambda(old_item, new_item_type, player));
    }
References TurnItemIntoItemEx().
TurnItemIntoItemEx()
static void TurnItemIntoItemEx (notnull PlayerBase player, ReplaceItemWithNewLambdaBase lambda) static
Definition at line 411 of file miscgameplayfunctions.c.
    {
        player.ServerReplaceItemWithNew(lambda);
    }
Referenced by TurnItemIntoItem().
UndoRemoveNetworkObjectInfo()
override protected void UndoRemoveNetworkObjectInfo ()
Definition at line 180 of file miscgameplayfunctions.c.
    {
        super.UndoRemoveNetworkObjectInfo();
        GetGame().RemoteObjectTreeCreate(m_NewItem);
    }
References GetGame(), m_NewItem, and CGame::RemoteObjectTreeCreate().
UnlimitedAmmoDebugCheck()
static void UnlimitedAmmoDebugCheck (Weapon_Base weapon) static
Definition at line 371 of file miscgameplayfunctions.c.
    {
        if ( ItemBase.GetDebugActionsMask() & DebugActionType.UNLIMITED_AMMO )
        {
            Magazine magazine;
            if ( GetGame().IsServer() )
            {
                magazine = weapon.GetMagazine(weapon.GetCurrentMuzzle());
                if (magazine)
                {
                    if (magazine.GetAmmoCount() <= 5)
                    {
                        magazine.ServerSetAmmoMax();
                    }
                }
            }
            else
            {
                magazine = weapon.GetMagazine(weapon.GetCurrentMuzzle());
                if (magazine)
                {
                    if (magazine.GetAmmoCount() <= 5)
                    {
                        magazine.LocalSetAmmoMax();
                    }
                }
            }
        }
    }
References GetGame().
ValueToBar()
static string ValueToBar (float value, string bar = "[----------]", string mark = "x") static
Produces ACII "progress bar" based on an 0..1 'value' input.
Definition at line 246 of file miscgameplayfunctions.c.
    {
        int length = bar.Length() - 2;
        float index = Math.Lerp(0,length, value);
        index = Math.Round(index);
        index = Math.Clamp(index,0,length);
        return InsertAtPos(bar,mark,index);
    }
References Math::Clamp(), InsertAtPos(), string::Length(), Math::Lerp(), and Math::Round().
Variable Documentation
ContactComponent
int ContactComponent = -1
Definition at line 1647 of file miscgameplayfunctions.c.
Referenced by ClearCache().
HitObjects
ref set<Object> HitObjects = new set<Object>
Definition at line 1649 of file miscgameplayfunctions.c.
Referenced by ClearCache().
HitProxyObjects
ref array<ref RaycastRVResult> HitProxyObjects = new array<ref RaycastRVResult>
Definition at line 1648 of file miscgameplayfunctions.c.
Referenced by ClearCache().
m_NewItem
EntityAI m_NewItem
Definition at line 165 of file miscgameplayfunctions.c.
Referenced by CreateNetworkObjectInfo(), MoveEquipToExistingItemAndDestroyOldRootLambda(), RemoveNetworkObjectInfo(), and UndoRemoveNetworkObjectInfo().
m_Player
m_Player
Definition at line 117 of file miscgameplayfunctions.c.
Referenced by ReplaceItemWithNewLambda::CopyOldPropertiesToNew(), ReplaceItemWithNewLambda::OnSuccess(), and DestroyItemInCorpsesHandsAndCreateNewOnGndLambda::RemoveOldItemFromLocation().
NONE
@ NONE = 0
Definition at line 216 of file miscgameplayfunctions.c.
ObjectCenterPos
vector ObjectCenterPos = "0 0 0"
Definition at line 1644 of file miscgameplayfunctions.c.
Referenced by ClearCache().
ObjectContactDir
vector ObjectContactDir = "0 0 0"
Definition at line 1646 of file miscgameplayfunctions.c.
Referenced by ClearCache().
ObjectContactPos
vector ObjectContactPos = "0 0 0"
Definition at line 1645 of file miscgameplayfunctions.c.
Referenced by ClearCache().
RaycastStart
DestroyItemInCorpsesHandsAndCreateNewOnGndLambda RaycastStart = "0 0 0"
Referenced by IsObjectObstructedCache().
SPLIT
SPLIT = 1
Definition at line 217 of file miscgameplayfunctions.c.
TotalObjects
int TotalObjects = 0
Definition at line 1641 of file miscgameplayfunctions.c.
Referenced by IsObjectObstructedCache().