DayzKode: P:/scripts/4_world/DayZ/classes/playernotifiers/notifiersmanager.c File Reference
notifiersmanager.c File Reference
Enumerations
enum eNotifiers {
NTF_HEALTHY , NTF_BLEEDISH , NTF_HUNGRY , NTF_THIRSTY ,
NTF_STUFFED , NTF_SICK , NTF_WETNESS , NTF_WARMTH ,
NTF_FEVERISH , NTF_BLOOD , NTF_LIVES , NTF_STAMINA ,
NTF_PILLS , NTF_HEARTBEAT , NTF_FRACTURE , NTF_COUNT
}
Functions
void ActivateByType (int notifier, bool triggerEvent=true)
void DeactivateByType (int notifier, bool triggerEvent=true)
NotifierBase FindNotifier (int type)
PlayerBase GetPlayer ()
VirtualHud GetVirtualHud ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void NotifiersManager (PlayerBase player)
void OnScheduledTick ()
void RegisterItself (int notifier_id, NotifierBase modifier)
void TickNotifiers ()
Variables
int m_MinTickTime
ref array< ref NotifierBase > m_Notifiers
ref NotifierBase m_NotifiersStatic [MAX_COUNT]
PlayerBase m_Player
string m_System = "Notifiers"
ref VirtualHud m_VirtualHud
enum eNotifiers MAX_COUNT = 64
Enumeration Type Documentation
eNotifiers
enum eNotifiers
Enumerator
NTF_HEALTHY
NTF_BLEEDISH
NTF_HUNGRY
NTF_THIRSTY
NTF_STUFFED
NTF_SICK
NTF_WETNESS
NTF_WARMTH
NTF_FEVERISH
NTF_BLOOD
NTF_LIVES
NTF_STAMINA
NTF_PILLS
NTF_HEARTBEAT
NTF_FRACTURE
NTF_COUNT
Definition at line 1 of file notifiersmanager.c.
{
    NTF_HEALTHY,
    NTF_BLEEDISH,
    NTF_HUNGRY,
    NTF_THIRSTY,
    NTF_STUFFED,
    NTF_SICK,
    NTF_WETNESS,
    NTF_WARMTH,
    NTF_FEVERISH,
    NTF_BLOOD,
    NTF_LIVES,
    NTF_STAMINA,
    //NTF_AGENT_INFECTION,
    NTF_PILLS,
    NTF_HEARTBEAT,
    NTF_FRACTURE,
    //----------------------------
    NTF_COUNT,// !!! LAST ITEM !!!
}
Function Documentation
ActivateByType()
void ActivateByType (int notifier, bool triggerEvent = true)
Definition at line 85 of file notifiersmanager.c.
    {
        FindNotifier(notifier).SetActive(true);
    }
References FindNotifier(), and NotifierBase::SetActive().
DeactivateByType()
void DeactivateByType (int notifier, bool triggerEvent = true)
Definition at line 90 of file notifiersmanager.c.
    {
        FindNotifier(notifier).SetActive(false);
    }
References FindNotifier(), and NotifierBase::SetActive().
FindNotifier()
NotifierBase FindNotifier (int type)
Definition at line 80 of file notifiersmanager.c.
    {
        return m_NotifiersStatic[type];
    }
References m_NotifiersStatic.
Referenced by ActivateByType(), and DeactivateByType().
GetPlayer()
PlayerBase GetPlayer ()
Definition at line 70 of file notifiersmanager.c.
    {
        return m_Player;
    }
References m_Player.
GetVirtualHud()
VirtualHud GetVirtualHud ()
Definition at line 75 of file notifiersmanager.c.
    {
        return m_VirtualHud;
    }
References m_VirtualHud.
Referenced by ManBase::OnBleedingSourceAdded(), ManBase::OnBleedingSourceRemoved(), and ManBase::OnRPC().
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 45 of file notifiersmanager.c.
    {
        m_Notifiers.Insert(new HungerNotfr(this));
        m_Notifiers.Insert(new ThirstNotfr(this));
        m_Notifiers.Insert(new WarmthNotfr(this));
        m_Notifiers.Insert(new WetnessNotfr(this));
        m_Notifiers.Insert(new HealthNotfr(this));
        m_Notifiers.Insert(new FeverNotfr(this));
        m_Notifiers.Insert(new SickNotfr(this));
        m_Notifiers.Insert(new StuffedNotfr(this));
        m_Notifiers.Insert(new BloodNotfr(this));
        m_Notifiers.Insert(new PillsNotfr(this));
        m_Notifiers.Insert(new HeartbeatNotfr(this));
        m_Notifiers.Insert(new FracturedLegNotfr(this)); //New addition
    }
References m_Notifiers.
NotifiersManager()
void NotifiersManager (PlayerBase player)
Definition at line 35 of file notifiersmanager.c.
    {
        m_Player = player;
        m_Notifiers = new array<ref NotifierBase>;
        m_MinTickTime = MIN_TICK_NOTIFIERS;
        Init();
    }
References Init(), m_MinTickTime, m_Notifiers, m_Player, and MIN_TICK_NOTIFIERS.
Referenced by ManBase::Init().
OnScheduledTick()
void OnScheduledTick ()
Definition at line 95 of file notifiersmanager.c.
    {
        if( !GetPlayer().IsPlayerSelected() ) return;
        TickNotifiers();
    }
References GetPlayer(), IsPlayerSelected(), and TickNotifiers().
Referenced by ManBase::OnTick().
RegisterItself()
void RegisterItself (int notifier_id, NotifierBase modifier)
Definition at line 62 of file notifiersmanager.c.
    {
        if(notifier_id >= MAX_COUNT)
            Error("out of bounds for notifier id: " + notifier_id);
        else
            m_NotifiersStatic[notifier_id] = modifier;
    }
References Error(), m_NotifiersStatic, and MAX_COUNT.
TickNotifiers()
void TickNotifiers ()
Definition at line 102 of file notifiersmanager.c.
    {
        int current_time = GetGame().GetTime();
        foreach(NotifierBase notifier: m_Notifiers)
        {
            if ( notifier.IsActive() && notifier.IsTimeToTick(current_time) )
            {
                notifier.OnTick(current_time);
            }
        }
    }
References GetGame(), CGame::GetTime(), and m_Notifiers.
Referenced by OnScheduledTick().
Variable Documentation
m_MinTickTime
int m_MinTickTime
Definition at line 32 of file notifiersmanager.c.
Referenced by NotifiersManager().
m_Notifiers
ref array<ref NotifierBase> m_Notifiers
Definition at line 28 of file notifiersmanager.c.
Referenced by Hud::DisplayNotifier(), Hud::DisplayTendencyNormal(), Hud::DisplayTendencyTemp(), Hud::HideTemperature(), Init(), Hud::Init(), Hud::InitBadgesAndNotifiers(), NotifiersManager(), Hud::OnResizeScreen(), Hud::RefreshHudVisibility(), Hud::SetTemperature(), and TickNotifiers().
m_NotifiersStatic
ref NotifierBase m_NotifiersStatic[MAX_COUNT]
Definition at line 29 of file notifiersmanager.c.
Referenced by FindNotifier(), and RegisterItself().
m_Player
PlayerBase m_Player
Definition at line 30 of file notifiersmanager.c.
m_System
string m_System = "Notifiers"
Definition at line 33 of file notifiersmanager.c.
m_VirtualHud
ref VirtualHud m_VirtualHud
Definition at line 31 of file notifiersmanager.c.
Referenced by GetVirtualHud(), ManBase::GetVirtualHud(), ManBase::Init(), ManBase::OnPlayerLoaded(), and ManBase::OnScheduledTick().
MAX_COUNT
enum eNotifiers MAX_COUNT = 64
Referenced by RegisterItself().