DayzKode: P:/scripts/3_game/DayZ/client/notifications/notificationsystem.c File Reference
notificationsystem.c File Reference
Classes
class NotificationSystem
Enumerations
enum NotificationType {
FRIEND_CONNECTED , INVITE_FAIL_SAME_SERVER , JOIN_FAIL_GET_SESSION , CONNECT_FAIL_GENERIC ,
NOTIFICATIONS_END
}
Functions
string GetDetailText ()
string GetIcon ()
float GetTime ()
string GetTitleText ()
void NotificationRuntimeData (float time, NotificationData data, string detail_text)
void SetTime (float time)
Variables
string m_DetailText
float m_NotificationTime
enum NotificationType m_StaticData
static const float NOTIFICATION_FADE_TIME = 3.0
Enumeration Type Documentation
NotificationType
enum NotificationType
Enumerator
FRIEND_CONNECTED
INVITE_FAIL_SAME_SERVER
JOIN_FAIL_GET_SESSION
CONNECT_FAIL_GENERIC
NOTIFICATIONS_END
Definition at line 3 of file notificationsystem.c.
{
    FRIEND_CONNECTED,
    INVITE_FAIL_SAME_SERVER,
    JOIN_FAIL_GET_SESSION,
    CONNECT_FAIL_GENERIC,
    //Please add types before this item
    NOTIFICATIONS_END
}
Function Documentation
GetDetailText()
string GetDetailText ()
Definition at line 50 of file notificationsystem.c.
    {
        return m_DetailText;
    }
References m_DetailText.
GetIcon()
string GetIcon ()
Definition at line 40 of file notificationsystem.c.
    {
        return m_StaticData.m_Icon;
    }
References m_StaticData.
Referenced by Container::GetFocusedIcon(), Container::GetIcon(), and Container::UpdateSelection().
GetTime()
float GetTime ()
Definition at line 35 of file notificationsystem.c.
    {
        return m_NotificationTime;
    }
References m_NotificationTime.
Referenced by ShockDamageMdfr::ActivateCondition(), HumanCommandActionCallback::CancelCondition(), PlayerStatBase::CreateRecord(), HandleInputData(), MissionBase::InsertCorpse(), ServerBrowserTab::LeftHold(), MissionBase::OnClientDisconnectedEvent(), OnScheduledTick(), OnServerInventoryCommandStatic(), ShockMdfr::OnTick(), UIPopupScript::OnUpdate(), ServerBrowserTabConsolePages::PressX(), ServerBrowserTab::PressX(), ProccessInputData(), ProcessSound(), InjurySoundHandlerBase::ProcessSound(), ServerBrowserTab::RightHold(), InventoryInputUserData::SendInputUserDataHandEvent(), InventoryInputUserData::SendInputUserDataMove(), InventoryInputUserData::SendInputUserDataSwap(), StaminaSoundHandlerBase::Update(), and MissionBase::UpdateLogoutPlayers().
GetTitleText()
string GetTitleText ()
Definition at line 45 of file notificationsystem.c.
    {
        return m_StaticData.m_TitleText;
    }
References m_StaticData.
NotificationRuntimeData()
void NotificationRuntimeData (float time, NotificationData data, string detail_text)
Definition at line 20 of file notificationsystem.c.
    {
        m_NotificationTime  = time + NOTIFICATION_FADE_TIME;
        m_StaticData        = data;
        if ( detail_text != "" )
            m_DetailText    = detail_text;
        else
            m_DetailText    = m_StaticData.m_DescriptionText;
    }
References m_DetailText, m_NotificationTime, m_StaticData, and NOTIFICATION_FADE_TIME.
Referenced by NotificationSystem::AddNotification(), NotificationSystem::AddNotificationExtended(), and NotificationSystem::Update().
SetTime()
void SetTime (float time)
Definition at line 30 of file notificationsystem.c.
    {
        m_NotificationTime = time;
    }
References m_NotificationTime.
Variable Documentation
m_DetailText
string m_DetailText
Definition at line 18 of file notificationsystem.c.
Referenced by GetDetailText(), and NotificationRuntimeData().
m_NotificationTime
float m_NotificationTime
Definition at line 17 of file notificationsystem.c.
Referenced by GetTime(), NotificationRuntimeData(), and SetTime().
m_StaticData
enum NotificationType m_StaticData
Referenced by GetIcon(), GetTitleText(), and NotificationRuntimeData().
NOTIFICATION_FADE_TIME
const float NOTIFICATION_FADE_TIME = 3.0 static
Definition at line 1 of file notificationsystem.c.
Referenced by NotificationRuntimeData(), and NotificationUI::Update().