DayzKode: P:/scripts/3_game/DayZ/entities/object.c File Reference
object.c File Reference
Enumerations
enum ProcessDirectDamageFlags
Functions
void AddHealth (float add_health)
Equivalent of AddHealth("", "", float value);.
proto native void AddHealth (string zoneName, string healthType, float value)
Adds health.
void AddHealthLevel (int healthLevelDelta, string zone="")
Similar to 'SetHealthLevel', but allows to jump up/down 'healthLevelDelta' amount of health levels from the current one. Positive values cause health level increase, therefore damage the item, and vice-versa.
proto native void AddProxyPhysics (string proxySelectionName)
proto native bool CanAffectPathgraph ()
Returns true if object's geometry can affect pathgraph generation.
bool CanBeIgnoredByDroppedItem ()
bool CanBeRepairedToPristine ()
bool CanBeSkinned ()
bool CanObstruct ()
bool CanProxyObstruct ()
bool CanUseConstruction ()
Returns if this entity can be constucted,deconstructed (e.g. fence,watchtower)
bool CanUseConstructionBuild ()
Returns if this entity can be built, specifically.
bool CanUseHandConstruction ()
Returns if this entity can be constructed without tools.
proto float ClippingInfo (out vector minMax[2])
Get Clipping info.
bool ConfigGetBool (string entryName)
proto float ConfigGetFloat (string entryName)
proto native void ConfigGetFloatArray (string entryName, out TFloatArray values)
Get array of floats from config entry.
proto int ConfigGetInt (string entryName)
proto native void ConfigGetIntArray (string entryName, out TIntArray values)
Get array of integers from config entry.
proto string ConfigGetString (string entryName)
proto string ConfigGetStringRaw (string entryName)
Get a raw strings from config entry.
proto native void ConfigGetTextArray (string entryName, out TStringArray values)
Get array of strings from config entry.
proto native void ConfigGetTextArrayRaw (string entryName, out TStringArray values)
Get array of raw strings from config entry.
proto vector ConfigGetVector (string entryName)
proto native bool ConfigIsExisting (string entryName)
Checks if given entry exists.
proto native void CreateDynamicPhysics (PhxInteractionLayers layer)
void DecreaseHealth (float dec_health, bool auto_delete=true)
Equivalent of DecreaseHealth("", "", float value, bool auto_delete);.
proto native void DecreaseHealth (string zoneName, string healthType, float value)
Decreases health.
void DecreaseHealth (string zoneName, string healthType, float value, bool auto_delete)
Decreases health with the option of auto-deleting the object if its ruined.
void DecreaseHealthCoef (float dec_health_coef, bool auto_delete=true)
Decreases health by the given coeficient.
void Delete ()
Delete this object in next frame.
bool DescriptionOverride (out string output)
bool DisableVicinityIcon ()
Disables icon in the vicinity, useful for large, immovable items, that are not buildings.
bool DisplayNameRuinAttach ()
bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
Event called from C++ right before damage is applied.
proto native void EnableDynamicCCD (bool state)
void Explode (int damageType, string ammoType="")
Creates an explosion on this object by its ammoType in config.
proto native owned string GetActionComponentName (int componentIndex, string geometry="")
returns action component name by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
proto native owned int GetActionComponentNameList (int componentIndex, TStringArray nameList, string geometry="")
outputs action component name list by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode). Returns -1 (not found), 0 (found default component only), or 1 (found named component)
proto native owned vector GetActionComponentPosition (int componentIndex, string geometry="")
returns action component position by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
void GetActions (typename action_input_type, out array< ActionBase_Basic > actions)
proto native bool GetAllowDamage ()
Returns if object can receive damage.
proto native bool GetCanBeDestroyed ()
Returns if object is destroyable.
vector GetCenter ()
proto native bool GetCollisionBox (out vector minMax[2])
Gets collision bounding box.
proto native float GetCollisionRadius ()
Gets collision radius (bounding sphere)
proto native float GetDamage ()
Get total damage (clipped to range 0..1)
proto native owned string GetDamageZoneNameByComponentIndex (int componentIndex)
Obtains name of damage zone based on index of specific component.
proto native vector GetDamageZonePos (string zoneName)
Obtains middle position of damage zone based on it's name.
proto native void GetDamageZones (out TStringArray dmgZones)
Obtains a list of nammes of all object's damage zones.
static string GetDebugName (Object o)
proto string GetDebugNameNative ()
native GetDebugName which is internally overloaded where needed
proto native vector GetDirection ()
Retrieve direction vector.
proto native vector GetDirectionAside ()
Retrieve direction aside vector.
proto native vector GetDirectionUp ()
Retrieve direction up vector.
string GetDisplayName ()
Get display name of entity.
proto native vector GetGlobalPos (vector vPos)
Calculate global position to this entity from local position.
float GetHealth ()
Equivalent of GetHealth("", "");.
proto native float GetHealth (string zoneName, string healthType)
Returns current state of health.
float GetHealth01 ()
Equivalent of GetHealth01("", "");.
proto native float GetHealth01 (string zoneName, string healthType)
Returns current state of health in range <0, 1>.
proto native int GetHealthLevel (string zone="")
Returns global health level specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
proto native float GetHealthLevelValue (int healthLevel, string zone="")
Returns cutoff value for health level specified in object's config class parameter healthLevels.
TStringArray GetHiddenSelections ()
Returns the hiddenSelections array from the object's config.
TStringArray GetHiddenSelectionsMaterials ()
Returns the hiddenSelectionsMaterials array from the object's config.
TStringArray GetHiddenSelectionsTextures ()
Returns the hiddenSelectionsTextures array from the object's config.
proto native vector GetLocalPos (vector vPos)
Calculate local position of other entity to this entity.
LOD GetLODByName (string name)
Retrieve LOD by given name.
proto native owned string GetLODName (LOD lod)
Retrieve LOD name.
proto native bool GetLODS (notnull out array< LOD > lods)
Retrieve all LODS
float GetMaxHealth ()
Equivalent of GetMaxHealth("", "");.
proto native float GetMaxHealth (string zoneName, string healthType)
Returns maximum value of health.
proto native int GetMemoryPointIndex (string memoryPointName)
If Returns true if this item has EnergyManager in its config. Otherwise returns false.
proto native vector GetMemoryPointPos (string memoryPointName)
proto native vector GetMemoryPointPosByIndex (int pointIndex)
string GetModelName ()
Returns name of the model of this object without the '.p3d' suffix.
proto native vector GetModelSpeed ()
Retrieve object's speed in local space.
proto void GetNetworkID (out int lowBits, out int highBits)
string GetNetworkIDString ()
proto native int GetNumberOfHealthLevels (string zone="")
Returns global number of health levels specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
proto native vector GetOrientation ()
Retrieve orientation (yaw, pitch, roll) in degrees
proto native vector GetPosition ()
Retrieve position.
proto native void GetSelectionList (out TStringArray selectionList)
vector GetSelectionPositionLS (string name)
vector GetSelectionPositionMS (string name)
vector GetSelectionPositionOld (string name)
vector GetSelectionPositionWS (string name)
proto native vector GetSpeed ()
Retrieve object's speed in global space.
float GetSurfaceNoise ()
Returns noise multiplier of surface under object.
string GetSurfaceType ()
Returns type of surface under object.
string GetType ()
Get config class of object.
proto native vector GetWorldPosition ()
bool HasAnimation (string anim_name)
Searches object's config for the given animation name. Returns true if it was found, or false if not.
proto native bool HasDamageSystem ()
Checks if object's DamageSystem has been initialized(despite the name, does not really reliably answer the question whether the object is configured to have damage system or not)
bool HasNetworkID ()
bool HasProxyParts ()
bool HasSelection (string selection)
Returns true if the given selection was found in the p3d file. False if otherwise.
proto native bool IsActionComponentPartOfSelection (int componentIndex, string selectionName, string geometry="")
return true if selection containts action component, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
bool IsAlive ()
bool IsAmmoPile ()
Returns if this entity is Ammo Pile.
bool IsAnyInherited (array< typename > typenames)
bool IsBeingBackstabbed ()
bool IsBuilding ()
Returns if this entity is Building.
bool IsBush ()
Returns if this entity is bush.
bool IsClothing ()
Returns if this entity is Clothing.
bool IsContainer ()
bool IsCorpse ()
bool IsCuttable ()
proto native bool IsDamageDestroyed ()
Checks if object is destroyed.
bool IsElectricAppliance ()
Returns if this is an appliance, that can be plugged into electric circuit (== not energy source)
bool IsEntityAI ()
Returns if this entity is EntityAI.
bool IsFireplace ()
Returns if this entity is fireplacebase.
bool IsFood ()
Returns if this entity if a food item.
bool IsFruit ()
bool IsFuelStation ()
Returns if this entity is Fuel Station (extends Building)
bool IsHealthVisible ()
Returns if the health of this entity should be displayed (widgets, inventory)
bool IsHologram ()
bool IsInventoryItem ()
Returns if this entity is InventoryItem.
bool IsItemBase ()
Returns if this entity is ItemBase.
bool IsItemTent ()
bool IsKindOf (string type)
Check config class name of the object.
bool IsMagazine ()
Returns if this entity is Magazine.
bool IsMan ()
Returns if this entity is Man.
bool IsMeat ()
bool IsMeleeWeapon ()
returns if this entity is Melee Weapon
bool IsMushroom ()
bool IsParticle ()
bool IsPeltBase ()
Returns if this entity is Pelt_Base.
proto native bool IsPendingDeletion ()
Get whether the Effect is queued up for being cleaned up.
proto native bool IsPlainObject ()
Is this just static object without config? So we can avoid calling unnecessary methods.
bool IsRock ()
Returns if this entity is rock.
bool IsRuined ()
Returns whether the object is ruined (0 Health).
proto native bool IsScenery ()
Is this Scenery? (handy for excluding terain when it is not needed)
bool IsScriptedLight ()
bool IsStaticTransmitter ()
Returns if this entity is Static Transmitter.
bool IsTransmitter ()
Returns if this entity is a non-static Transmitter.
bool IsTransport ()
Returns if this entity is transport.
bool IsTree ()
Returns if this entity is tree.
bool IsWeapon ()
Returns if this entity is Weapon.
bool IsWell ()
Returns if this entity is Well (extends Building)
bool IsWoodBase ()
Returns whether object is PlanBase.
bool KindOf (string tag)
Compares config class name to given string.
proto native bool MemoryPointExists (string memoryPoint)
vector ModelToWorld (vector modelPos)
bool NameOverride (out string output)
enum ProcessDirectDamageFlags Object ()
void OnEnterTrigger (ScriptedEntity trigger)
Object entered trigger.
void OnExplodeClient ()
Called on clients when this object explodes.
void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
void OnLeaveTrigger (ScriptedEntity trigger)
Object left trigger.
void OnPlayerRecievedHit ()
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
void OnSimulationDisabled ()
Event called from C++ when simulation is disabled.
void OnSimulationEnabled ()
Event called from C++ when simulation is enabled.
void OnTreeCutDown (EntityAI cutting_entity)
Called when tree is chopped down. 'cutting_entity' can be tool, or player, if cutting bush with bare hands.
proto native void PlaceOnSurface ()
Place object on surface.
SoundOnVehicle PlaySound (string sound_name, float range, bool create_local=true)
Plays the given sound once on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
SoundOnVehicle PlaySoundLoop (string sound_name, float range, bool create_local=true)
Plays the given sound in loop on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
bool PlaySoundSet (out EffectSound sound, string sound_set, float fade_in, float fade_out, bool loop=false)
EffectSound - plays soundset on this object and returns state of the sound (true - played, false - not played)
bool PlaySoundSetAtMemoryPoint (out EffectSound sound, string soundSet, string memoryPoint, bool looped=false, float play_fade_in=0, float stop_fade_out=0)
bool PlaySoundSetAtMemoryPointLooped (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in=0, float stop_fade_out=0)
bool PlaySoundSetAtMemoryPointLoopedSafe (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in=0, float stop_fade_out=0)
Same as PlaySoundSetAtMemoryPointLooped, only requests stoppage of the currently playing EffectSound if it already exists and playing, before playing the new sound.
bool PlaySoundSetLoop (out EffectSound sound, string sound_set, float fade_in, float fade_out)
EffectSound - plays soundset on this object in loop and returns state of the sound (true - played, false - not played)
void PostAreaDamageActions ()
void PreAreaDamageActions ()
proto native void ProcessDirectDamage (int damageType, EntityAI source, string componentName, string ammoName, vector modelPos, float damageCoef=1.0, int flags=0)
Applies damage on object.
EntityAI ProcessMeleeItemDamage (int mode=0)
int Release ()
proto native void RemoveProxyPhysics (string proxySelectionName)
void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient=NULL)
Remote procedure call shortcut, see CGame.RPC / CGame.RPCSingleParam.
void RPCSingleParam (int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient=NULL)
Remote procedure call shortcut, see CGame.RPCSingleParam / CGame.RPC.
proto native void SetAffectPathgraph (bool fromConfig, bool affect)
Sets if object's geometry affects pathgraph generation. If first parameter is true, it ignores second parameter and sets affecting pathgraph by parameter set in object's config.
proto native void SetAllowDamage (bool val)
Enable or disable object to receive damage.
void SetBeingBackstabbed (int backstabType)
proto native void SetCanBeDestroyed (bool val)
Enable or disable destruction of object (after health is depleated)
proto native void SetDestructTime (float time)
Sets the time over which to perform DestructTent/DestructTree.
proto native void SetDirection (vector vPos)
Set direction of object.
proto native void SetDynamicPhysicsLifeTime (float lifeTime)
void SetHealth (float health)
Equivalent of SetHealth("", "", float value);.
proto native void SetHealth (string zoneName, string healthType, float value)
Sets current state of health.
void SetHealth01 (string zoneName, string healthType, float coef)
Sets health relative to its maximum.
void SetHealthLevel (int healthLevel, string zone="")
Sets specific health level. It will use the cutoff value as returned by 'GetHealthLevelValue' as the health value for the given health level, which means it will always be set to the max health as allowed by the given health level.
void SetHealthMax (string zoneName="", string healthType="")
Sets health to its maximum (zone or global)
proto native void SetOrientation (vector vOrientation)
Set orientation (yaw, pitch, roll) in degrees
proto native void SetPosition (vector vPos)
Set position.
bool ShootsExplosiveAmmo ()
Returns if this entity is a weapon which can shoot explosive ammo.
bool ShowZonesHealth ()
Returns true if the health of damage zones should be displayed (instead of global HP of the entity) (action widgets)
void SpawnDamageDealtEffect ()
bool StopSoundSet (out EffectSound sound)
EffectSound - stops soundset and returns state of the sound (true - stopped, false - not playing)
void SynchExplosion ()
proto native bool ToDelete ()
Flag to determine this object is marked to be deleted soon.
vector WorldToModel (vector worldPos)
Variables
NO_ATTACHMENT_TRANSFER
Do not transfer damage to attachments.
NO_GLOBAL_TRANSFER
Do not transfer damage to global.
NO_TRANSFER
NO_ATTACHMENT_TRANSFER | NO_GLOBAL_TRANSFER.
Enumeration Type Documentation
ProcessDirectDamageFlags
enum ProcessDirectDamageFlags
Definition at line 1 of file object.c.
{
    NO_ATTACHMENT_TRANSFER,
    NO_GLOBAL_TRANSFER,
    NO_TRANSFER,
}
Function Documentation
AddHealth() [1/2]
void AddHealth (float add_health)
Equivalent of AddHealth("", "", float value);.
Definition at line 933 of file object.c.
    {
        AddHealth("", "", add_health);
    }
References AddHealth().
AddHealth() [2/2]
proto native void AddHealth (string zoneName, string healthType, float value)
Adds health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
Referenced by AddHealth(), ManBase::ApplySplint(), DayZCreatureAI::EEHitBy(), ManBase::EEHitBy(), EOnPostSimulate(), ManBase::GiveShock(), InventoryItem::OnAction(), and OnUpdate().
AddHealthLevel()
void AddHealthLevel (int healthLevelDelta, string zone = "")
Similar to 'SetHealthLevel', but allows to jump up/down 'healthLevelDelta' amount of health levels from the current one. Positive values cause health level increase, therefore damage the item, and vice-versa.
Definition at line 915 of file object.c.
    {
        int maxHealthLevel = GetNumberOfHealthLevels(zone) - 1;
        int newHealthLevel = Math.Clamp(GetHealthLevel(zone) + healthLevelDelta,0,maxHealthLevel);
        SetHealthLevel(newHealthLevel,zone);
    }
References Math::Clamp(), GetHealthLevel(), GetNumberOfHealthLevels(), and SetHealthLevel().
Referenced by PunchedCard::OnUse().
AddProxyPhysics()
proto native void AddProxyPhysics (string proxySelectionName)
Referenced by ItemBase::EEItemAttached(), ItemBase::HandleOpeningsPhysics(), ItemBase::RefreshAttachements(), ItemBase::RefreshPhysics(), FireplaceBase::RefreshPhysics(), Inventory_Base::RefreshPhysics(), ItemBase::SetPartFromSyncData(), ItemBase::ToggleAnimation(), ItemBase::UpdateAttachmentPhysics(), ItemBase::UpdatePhysics(), and ItemBase::UpdateSelections().
CanAffectPathgraph()
proto native bool CanAffectPathgraph ()
Returns true if object's geometry can affect pathgraph generation.
CanBeIgnoredByDroppedItem()
bool CanBeIgnoredByDroppedItem ()
Definition at line 636 of file object.c.
    {
        return IsBush() || IsTree();
    }
References IsBush(), and IsTree().
CanBeRepairedToPristine()
bool CanBeRepairedToPristine ()
Definition at line 1177 of file object.c.
    {
        return false;
    }
Referenced by PluginBase::CalculateHealth(), and PluginBase::Repair().
CanBeSkinned()
bool CanBeSkinned ()
Definition at line 13 of file object.c.
    {
        return false;
    }
CanObstruct()
bool CanObstruct ()
Definition at line 626 of file object.c.
    {
        return IsPlainObject() && !IsScenery();
    }
References IsPlainObject(), and IsScenery().
CanProxyObstruct()
bool CanProxyObstruct ()
Definition at line 631 of file object.c.
    {
        return HasProxyParts() || CanUseConstruction();
    }
References CanUseConstruction(), and HasProxyParts().
Referenced by IsObjectObstructedProxy().
CanUseConstruction()
bool CanUseConstruction ()
Returns if this entity can be constucted,deconstructed (e.g. fence,watchtower)
Definition at line 539 of file object.c.
    {
        return false;
    }
Referenced by CanProxyObstruct().
CanUseConstructionBuild()
bool CanUseConstructionBuild ()
Returns if this entity can be built, specifically.
Definition at line 545 of file object.c.
    {
        return false;
    }
CanUseHandConstruction()
bool CanUseHandConstruction ()
Returns if this entity can be constructed without tools.
Definition at line 551 of file object.c.
    {
        return false;
    }
ClippingInfo()
proto float ClippingInfo (out vector minMax[2])
Get Clipping info.
Parameters
minMax array[2] of vectors, into minMax[0] is returned min, into minMax[1] is returned max
Returns
radius of bounding box
vector minMax[2];
float radius = GetGame().GetPlayer().ClippingInfo(minMax);
Print(minMax);
Print(radius);
ConfigGetBool()
bool ConfigGetBool (string entryName)
Definition at line 729 of file object.c.
    {
        return (ConfigGetInt(entryName) == 1);
    }
References ConfigGetInt().
Referenced by InventoryItem::InitItemVariables(), InventoryItemSuper::InitOpticsPPInfo(), EntityAI::InventoryItem(), IsCuttable(), ManBase::IsMale(), InventoryItem::ItemBase(), and InventoryItem::SetQuantity().
ConfigGetFloat()
proto float ConfigGetFloat (string entryName)
Referenced by ItemBase::Clothing_Base(), GetCycleTimeOverride(), InventoryItem::GetHeatIsolationInit(), InventoryItem::GetItemModelLength(), GetToolDamage(), InventoryItem::GetUnitWeight(), InventoryItemSuper::InitCameraOverrideProperties(), InventoryItem::InitItemVariables(), Weapon::InitWeaponLength(), InventoryItem::IsLiquidContainer(), UIScriptedMenu::OnClick(), and Grenade_Base::OnExplosionEffects().
ConfigGetFloatArray()
proto native void ConfigGetFloatArray (string entryName, out TFloatArray values)
Get array of floats from config entry.
Parameters
entryName
value output
ConfigGetInt()
proto int ConfigGetInt (string entryName)
Referenced by ConfigGetBool(), InventoryItem::GetLiquidTypeInit(), GetPrimaryDropsAmount(), GetSecondaryDropsAmount(), InventoryItem::GetSingleInventoryItemWeight(), ManBase::GetVoiceType(), ManBase::Init(), InventoryItem::InitItemVariables(), IsEntityOnInteriorSurface(), InventoryItem::ItemBase(), and ActionUnpackBox::OnFinishProgressServer().
ConfigGetIntArray()
proto native void ConfigGetIntArray (string entryName, out TIntArray values)
Get array of integers from config entry.
Parameters
entryName
value output
Referenced by InventoryItem::InitItemVariables().
ConfigGetString()
proto string ConfigGetString (string entryName)
Referenced by BrakeLightsShineOff(), BrakeLightsShineOn(), InventoryItem::ChangeIntoOnAttach(), InventoryItem::ChangeIntoOnDetach(), DashboardShineOff(), DashboardShineOn(), Explode(), GetBarkType(), GetPrimaryOutput(), GetSecondaryOutput(), InventoryItem::GetSingleInventoryItemWeight(), EntityAI::GetTooltip(), ManBase::Init(), EntityAI::InitImpactSoundData(), InventoryItem::InitItemVariables(), LeftFrontLightShineOff(), LeftFrontLightShineOn(), OnExplodeClient(), InventoryItem::PreLoadSoundAttachmentType(), ReverseLightsShineOff(), ReverseLightsShineOn(), RightFrontLightShineOff(), RightFrontLightShineOn(), TailLightsShineOff(), TailLightsShineOn(), and InventoryItem::UpdateWeight().
ConfigGetStringRaw()
proto string ConfigGetStringRaw (string entryName)
Get a raw strings from config entry.
Parameters
entryName
Returns
value output string
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetTextArray()
proto native void ConfigGetTextArray (string entryName, out TStringArray values)
Get array of strings from config entry.
Parameters
entryName
value output
Referenced by ItemBase::BaseBuildingBase(), InventoryItem::ChangeIntoOnAttach(), InventoryItem::ChangeIntoOnDetach(), Head::Init(), InventoryItem::ItemBase(), KindOf(), InventoryItem::PlayAttachSound(), and Weapon::Weapon_Base().
ConfigGetTextArrayRaw()
proto native void ConfigGetTextArrayRaw (string entryName, out TStringArray values)
Get array of raw strings from config entry.
Parameters
entryName
value output in raw format (localization keys '$STR_' are not translated).
Note
use 'FormatRawConfigStringKeys' method to change localization keys to script-friendly
ConfigGetVector()
proto vector ConfigGetVector (string entryName)
ConfigIsExisting()
proto native bool ConfigIsExisting (string entryName)
Checks if given entry exists.
Parameters
entryName
Referenced by ItemBase::BaseBuildingBase(), CalcAndSetTotalEnergy(), BaseBuildingBase::CanReceiveAttachment(), CanUseToolToBuildPart(), CanUseToolToDismantlePart(), UnboxLambda::CopyOldPropertiesToNew(), AttachmentsOutOfReach::CreateAttachmentPosition(), DestroyMaterialsServer(), DropNonUsableMaterialsServer(), ManBase::EEHitBy(), ComponentEnergyManager::Event_OnAwake(), ConstructionActionData::GetAttachmentsFromSelection(), ConstructionActionData::GetAttachmentSlotFromSelection(), ItemBase::GetAttachmentSlots(), GetComponentNamesFromDamageZone(), SceneObject::GetConfigAttachments(), GetDamageZoneMap(), InventoryItem::GetItemModelLength(), Attachments::GetItemSlots(), GetMaterialType(), GetTypeMaxGlobalHealth(), HasAnimation(), HasMaterials(), ItemBase::HideAllAnimationsAndProxyPhysics(), Hologram::Hologram(), Head::Init(), InventoryItemSuper::Init2DPreloadType(), InventoryItemSuper::InitCameraOverrideProperties(), Weapon::InitDOFProperties(), ZombieContainer::InitGhostSlots(), EntityAI::InitImpactSoundData(), InventoryItem::InitItemVariables(), InventoryItemSuper::InitOpticsDOFProperties(), InventoryItemSuper::InitReddotData(), Weapon::InitReliability(), Weapon::InitWeaponLength(), EntityAI::InventoryItem(), InventoryItem::ItemBase(), ModStructure::LoadData(), InventoryItem::LoadParticleConfigOnOverheating(), LockOvenAttachments(), MaterialIsRuined(), Grenade_Base::OnExplosionEffects(), ActionUnpackBox::OnFinishProgressServer(), InventoryItem::PlayAttachSound(), PlayerContainer::PlayerContainer(), InventoryItem::PreLoadSoundAttachmentType(), ReceiveMaterialsServer(), BetaSound::SaySound(), SetLockOnAttachedMaterials(), TakeMaterialsServer(), UpdateConstructionParts(), VicinityContainer::UpdateInterval(), Hologram::UpdateSelections(), Weapon::Weapon_Base(), and WeaponParticlesBase::WeaponParticlesBase().
CreateDynamicPhysics()
proto native void CreateDynamicPhysics (PhxInteractionLayers layer)
DecreaseHealth() [1/3]
void DecreaseHealth (float dec_health, bool auto_delete = true)
Equivalent of DecreaseHealth("", "", float value, bool auto_delete);.
Definition at line 938 of file object.c.
    {
        DecreaseHealth("", "", dec_health, auto_delete);
    }
References DecreaseHealth().
DecreaseHealth() [2/3]
proto native void DecreaseHealth (string zoneName, string healthType, float value)
Decreases health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
Referenced by AddDefect(), ItemBase::AddDefect(), ManBase::DamageAllLegs(), DecreaseHealth(), DecreaseHealthCoef(), Inventory_Base::Fill(), Inventory_Base::Fold(), ItemBase::OnIgnitedTarget(), ItemBase::OnIgnitedTargetFailed(), Release(), and Inventory_Base::Unfold().
DecreaseHealth() [3/3]
void DecreaseHealth (string zoneName, string healthType, float value, bool auto_delete)
Decreases health with the option of auto-deleting the object if its ruined.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
Definition at line 877 of file object.c.
    {
        DecreaseHealth( zoneName, healthType, value);
        float result_health = GetHealth(zoneName, healthType);
        if ( auto_delete  &&  result_health <= 0 )
        {
            GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().ObjectDelete, this);
        }
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, DecreaseHealth(), CGame::GetCallQueue(), GetGame(), and GetHealth().
DecreaseHealthCoef()
void DecreaseHealthCoef (float dec_health_coef, bool auto_delete = true)
Decreases health by the given coeficient.
Definition at line 943 of file object.c.
    {
        float current_health = GetHealth();
        float final_health_coef = GetHealth01() - dec_health_coef;
        float final_health = GetMaxHealth() * final_health_coef;
        DecreaseHealth("", "", current_health - final_health);
    }
References DecreaseHealth(), GetHealth(), GetHealth01(), and GetMaxHealth().
Delete()
void Delete ()
Delete this object in next frame.
Returns
void
ItemBase item = GetGame().GetPlayer().CreateInInventory("GrenadeRGD5");
item.Delete();
Definition at line 26 of file object.c.
    {
        GetGame().GetCallQueue(CALL_CATEGORY_SYSTEM).Call(GetGame().ObjectDelete, this);
    }
References ScriptCallQueue::Call(), CALL_CATEGORY_SYSTEM, CGame::GetCallQueue(), and GetGame().
Referenced by Capture(), TentBase::Deconstruct(), DestroyEg(), ItemBase::EEItemDetached(), ItemBase::EEItemLocationChanged(), EOnFrame(), InventoryItem::OnAction(), Particle::OnCheckAutoDelete(), Grenade_ChemGas::OnDamageDestroyed(), DummyItem::OnItemLocationChanged(), Release(), InventoryItem::SetQuantity(), and ContaminatedArea_Local::Tick().
DescriptionOverride()
bool DescriptionOverride (out string output)
Definition at line 1170 of file object.c.
    {
        return false;
    }
Referenced by EntityAI::GetTooltip().
DisableVicinityIcon()
bool DisableVicinityIcon ()
Disables icon in the vicinity, useful for large, immovable items, that are not buildings.
Definition at line 642 of file object.c.
    {
        return false;
    }
DisplayNameRuinAttach()
bool DisplayNameRuinAttach ()
Definition at line 360 of file object.c.
    {
        return false;
    }
EEOnDamageCalculated()
bool EEOnDamageCalculated (TotalDamageResult damageResult, int damageType, EntityAI source, int component, string dmgZone, string ammo, vector modelPos, float speedCoef)
Event called from C++ right before damage is applied.
Returns
whether to apply the damage or not
Definition at line 967 of file object.c.
    {
        return true;
    }
EnableDynamicCCD()
proto native void EnableDynamicCCD (bool state)
Explode()
void Explode (int damageType, string ammoType = "")
Creates an explosion on this object by its ammoType in config.
Definition at line 86 of file object.c.
    {
        if (ammoType == "")
            ammoType = ConfigGetString("ammoType");
        if (ammoType == "")
            ammoType = "Dummy_Heavy";
        if ( GetGame().IsServer() )
        {
            SynchExplosion();
            DamageSystem.ExplosionDamage(EntityAI.Cast(this), null, ammoType, GetPosition(), damageType);
        }
    }
References ConfigGetString(), GetGame(), GetPosition, and SynchExplosion().
Referenced by FuelStation::EEKilled(), InventoryItem::EEKilled(), EEKilled(), ExplodeNow(), InitiateExplosion(), Grenade_Base::InitiateExplosion(), OnServerSteppedOn(), and OnSteppedOn().
GetActionComponentName()
proto native owned string GetActionComponentName (int componentIndex, string geometry = "")
returns action component name by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
Referenced by GetTurnableValveIndex().
GetActionComponentNameList()
proto native owned int GetActionComponentNameList (int componentIndex, TStringArray nameList, string geometry = "")
outputs action component name list by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode). Returns -1 (not found), 0 (found default component only), or 1 (found named component)
Referenced by ScriptedWidgetEventHandler::GetOnScreenPosition().
GetActionComponentPosition()
proto native owned vector GetActionComponentPosition (int componentIndex, string geometry = "")
returns action component position by given component index, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
GetActions()
void GetActions (typename action_input_type , out array< ActionBase_Basic > actions)
Definition at line 1053 of file object.c.
    {
    }
GetAllowDamage()
proto native bool GetAllowDamage ()
Returns if object can receive damage.
GetCanBeDestroyed()
proto native bool GetCanBeDestroyed ()
Returns if object is destroyable.
GetCenter()
vector GetCenter ()
Definition at line 1182 of file object.c.
    {
        if ( MemoryPointExists("ce_center") )
        {
            //Print("CE_CENTER found");
            return ModelToWorld( GetMemoryPointPos("ce_center") );
        }
        else
        {
            //Print("CE_CENTER DOING A BAMBOOZLE => not found");
            return GetPosition() + Vector(0, 0.2, 0);
        }
    }
References GetMemoryPointPos(), GetPosition, MemoryPointExists(), ModelToWorld(), and Vector().
GetCollisionBox()
proto native bool GetCollisionBox (out vector minMax[2])
Gets collision bounding box.
Parameters
minMax array[2] of vectors, into minMax[0] is returned min, into minMax[1] is returned max
Returns
true if collision box exists, false otherwise
vector minMax[2];
if(GetGame().GetPlayer().GetCollisionBox(minMax))
    Print("has box");
Referenced by ManBase::EOnPostFrame(), BaseBuildingBase::IsPlayerInside(), and TentBase::IsPlayerInside().
GetCollisionRadius()
proto native float GetCollisionRadius ()
Gets collision radius (bounding sphere)
Returns
bounding sphere radius
Referenced by Trigger::GetRadius().
GetDamage()
proto native float GetDamage ()
Get total damage (clipped to range 0..1)
GetDamageZoneNameByComponentIndex()
proto native owned string GetDamageZoneNameByComponentIndex (int componentIndex)
Obtains name of damage zone based on index of specific component.
Parameters
index of the component
GetDamageZonePos()
proto native vector GetDamageZonePos (string zoneName)
Obtains middle position of damage zone based on it's name.
Parameters
name of the damage zone
GetDamageZones()
proto native void GetDamageZones (out TStringArray dmgZones)
Obtains a list of nammes of all object's damage zones.
Parameters
list of names
Referenced by InventoryItem::PerformDamageSystemReinit(), and InventoryItem::SetZoneDamageCEInit().
GetDebugName()
static string GetDebugName (Object o) static
Definition at line 658 of file object.c.
    {
        if (o)
            return o.GetType() + ":" + o.GetNetworkIDString();
        return "null";
    }
GetDebugNameNative()
proto string GetDebugNameNative ()
native GetDebugName which is internally overloaded where needed
Referenced by GetDebugName().
GetDirection()
proto native vector GetDirection ()
Retrieve direction vector.
Referenced by TrapSpawnBase::AlignCatch(), DayZInfected::ChaseAttackLogic(), DayZInfected::ComputeHitDirectionAngle(), DayZCreatureAI::ComputeHitDirectionAngleDeg(), DayZInfected::ComputeHitDirectionAngleEx(), Transport::DebugFreeAreaAtDoor(), ManBase::DropItem(), DayZSpectator::EOnFrame(), DayZInfected::EvaluateCrawlTransitionAnimation(), EvaluateDamageHitAnimation(), EvaluateDeathAnimation(), DayZInfected::FightAttackLogic(), Transport::IsAreaAtDoorFree(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), ManBase::IsFacingTarget(), BaseBuildingBase::IsPlayerInside(), TentBase::IsPlayerInside(), IsSpaceFor(), and ManBase::SpawnEntityOnGroundOnCursorDir().
GetDirectionAside()
proto native vector GetDirectionAside ()
Retrieve direction aside vector.
GetDirectionUp()
proto native vector GetDirectionUp ()
Retrieve direction up vector.
Referenced by CanBeIgnitedBy().
GetDisplayName()
string GetDisplayName ()
Get display name of entity.
Definition at line 343 of file object.c.
    {
        string tmp;
        if (NameOverride(tmp))
        {
            tmp = Widget.TranslateString(tmp);
            //tmp.ToUpper();
        }
        else
        {
            GetGame().ObjectGetDisplayName(this, tmp);
        }
        return tmp;
    }
References GetGame(), NameOverride(), and CGame::ObjectGetDisplayName().
Referenced by ManBase::EEHitBy().
GetGlobalPos()
proto native vector GetGlobalPos (vector vPos)
Calculate global position to this entity from local position.
GetHealth() [1/2]
float GetHealth ()
Equivalent of GetHealth("", "");.
Definition at line 890 of file object.c.
    {
        return GetHealth("", "");
    }
References GetHealth().
Referenced by ManBase::ApplySplint(), ManBase::BrokenLegWalkShock(), DecreaseHealth(), DecreaseHealthCoef(), DestroyPartServer(), ManBase::EEHitBy(), DayZInfected::EvaluateCrawlTransitionAnimation(), EvaluateDamageHitAnimation(), GetHealth(), ManBase::GetHealthRegenSpeed(), ManBase::GetImmunity(), ManBase::GetStatBordersBlood(), ManBase::GetStatBordersHealth(), ManBase::GetStatLevelBlood(), ManBase::GetStatLevelHealth(), ItemBase::OnWork(), and ManBase::SimplifyShock().
GetHealth() [2/2]
proto native float GetHealth (string zoneName, string healthType)
Returns current state of health.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetHealth01() [1/2]
float GetHealth01 ()
Equivalent of GetHealth01("", "");.
Definition at line 895 of file object.c.
    {
        return GetHealth01("", "");
    }
References GetHealth01().
Referenced by BroomBase::CalculateQuantity(), CarPartsHealthCheck(), InventoryItem::CombineItems(), DecreaseHealthCoef(), BroomBase::EEHitBy(), Inventory_Base::EmptySeedPack(), GetHealth01(), ItemBase::ProcessDecay(), Weapon_Base::SetAttachmentsHealth(), InventoryItem::SetZoneDamageCEInit(), and TentBase::SpawnKit().
GetHealth01() [2/2]
proto native float GetHealth01 (string zoneName, string healthType)
Returns current state of health in range <0, 1>.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetHealthLevel()
proto native int GetHealthLevel (string zone = "")
Returns global health level specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
Parameters
zoneName if empty string, returns state of global health level
Referenced by AddHealthLevel(), InventoryItem::CanBeCombined(), CanLoadAttachment(), FireplaceBase::CanLoadAttachment(), ItemBase::CanLoadAttachment(), CanLoadItemIntoCargo(), FireplaceBase::CanLoadItemIntoCargo(), ItemBase::CanLoadItemIntoCargo(), CanReceiveAttachment(), FireplaceBase::CanReceiveAttachment(), ItemBase::CanReceiveAttachment(), CanReceiveItemIntoCargo(), FireplaceBase::CanReceiveItemIntoCargo(), ItemBase::CanReceiveItemIntoCargo(), ItemBase::CanToggleAnimations(), Weapon::GetChanceToJam(), Chemlight_ColorBase::GetMaterialForDamageState(), TentBase::HandleCamoNetAttachment(), ItemBase::HandleOpeningsPhysics(), Plastic_Explosive::OnActivatedByItem(), and CarScript::OnSound().
GetHealthLevelValue()
proto native float GetHealthLevelValue (int healthLevel, string zone = "")
Returns cutoff value for health level specified in object's config class parameter healthLevels.
Parameters
zoneName if empty string, returns number of global health levels
healthLevel the health level to get the value from
Referenced by SetHealthLevel().
GetHiddenSelections()
TStringArray GetHiddenSelections ()
Returns the hiddenSelections array from the object's config.
Definition at line 68 of file object.c.
    {
        return HiddenSelectionsData.GetHiddenSelectionsConfig(GetType());
    }
References HiddenSelectionsData::GetHiddenSelectionsConfig(), and GetType().
GetHiddenSelectionsMaterials()
TStringArray GetHiddenSelectionsMaterials ()
Returns the hiddenSelectionsMaterials array from the object's config.
Definition at line 80 of file object.c.
    {
        return HiddenSelectionsData.GetHiddenSelectionsMaterialsConfig(GetType());
    }
References HiddenSelectionsData::GetHiddenSelectionsMaterialsConfig(), and GetType().
Referenced by Chemlight_ColorBase::Chemlight_ColorBase().
GetHiddenSelectionsTextures()
TStringArray GetHiddenSelectionsTextures ()
Returns the hiddenSelectionsTextures array from the object's config.
Definition at line 74 of file object.c.
    {
        return HiddenSelectionsData.GetHiddenSelectionsTexturesConfig(GetType());
    }
References HiddenSelectionsData::GetHiddenSelectionsTexturesConfig(), and GetType().
Referenced by ItemBase::SetSlotTextureDigged(), and ItemBase::SetSlotTextureFertilized().
GetLocalPos()
proto native vector GetLocalPos (vector vPos)
Calculate local position of other entity to this entity.
GetLODByName()
LOD GetLODByName (string name)
Retrieve LOD by given name.
Definition at line 48 of file object.c.
    {
        array<LOD> lods = new array<LOD>;
        GetLODS( lods );
        for ( int i = 0; i < lods.Count(); ++i )
        {
            string lod_name = GetLODName( lods.Get( i ) );
            lod_name.ToLower();
            name.ToLower();
            if ( lod_name == name )
            {
                return lods.Get( i );
            }
        }
        return NULL;
    }
References GetLODName(), GetLODS(), name, and string::ToLower().
GetLODName()
proto native owned string GetLODName (LOD lod)
Retrieve LOD name.
Referenced by GetLODByName().
GetLODS()
proto native bool GetLODS (notnull out array< LOD > lods)
Retrieve all LODS
Referenced by GetLODByName().
GetMaxHealth() [1/2]
float GetMaxHealth ()
Equivalent of GetMaxHealth("", "");.
Definition at line 900 of file object.c.
    {
        return GetMaxHealth("", "");
    }
References GetMaxHealth().
Referenced by ManBase::ApplySplint(), InventoryItem::CombineItems(), DecreaseHealthCoef(), RecipeBase::Do(), Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), EOnPostSimulate(), Inventory_Base::Fold(), ManBase::GetHealthRegenSpeed(), ManBase::GetImmunity(), GetMaxHealth(), ManBase::GetStatBordersBlood(), ManBase::GetStatBordersHealth(), HandleDamageHit(), InventoryItem::OnAction(), Release(), ManBase::ResetPlayer(), SetHealth01(), SetHealthMax(), ManBase::SimplifyShock(), and Inventory_Base::Unfold().
GetMaxHealth() [2/2]
proto native float GetMaxHealth (string zoneName, string healthType)
Returns maximum value of health.
Parameters
zoneName if empty string, returns state of global health
healthType if empty string, returns state of main health
GetMemoryPointIndex()
proto native int GetMemoryPointIndex (string memoryPointName)
If Returns true if this item has EnergyManager in its config. Otherwise returns false.
GetMemoryPointPos()
proto native vector GetMemoryPointPos (string memoryPointName)
Referenced by ItemBase::CalcDamageAreaRotation(), CanReachSeatFromDoors(), CarScript(), BaseBuildingBase::CheckMemoryPointVerticalDistance(), ItemBase::CreateAreaDamage(), ItemBase::DoMeasurement(), BuildingSuper::EEInit(), GetCenter(), BaseBuildingBase::GetKitSpawnPosition(), GetLightPosition(), GetMemoryPointPosition(), BaseBuildingBase::HasProperDistance(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), BaseBuildingBase::IsPlayerInside(), FireworksLauncher::OnFuseIgnitedClient(), BaseBuildingBase::PerformRoofCheckForBase(), PlaySoundSetAtMemoryPoint(), ItemBase::SpawnCatch(), TranslateMemoryPointsToWaterLevels(), and UpdateLightsClient().
GetMemoryPointPosByIndex()
proto native vector GetMemoryPointPosByIndex (int pointIndex)
GetModelName()
string GetModelName ()
Returns name of the model of this object without the '.p3d' suffix.
Definition at line 366 of file object.c.
    {
        return GetGame().GetModelName(GetType());
    }
References GetGame(), CGame::GetModelName(), and GetType().
GetModelSpeed()
proto native vector GetModelSpeed ()
Retrieve object's speed in local space.
GetNetworkID()
proto void GetNetworkID (out int lowBits, out int highBits)
Returns low and high bits of networkID. This id is shared between client and server for whole server-client session.
Referenced by GetNetworkIDString(), and HasNetworkID().
GetNetworkIDString()
string GetNetworkIDString ()
Definition at line 651 of file object.c.
    {
        int low, high;
        GetNetworkID( low, high );
        return high.ToString() + low.ToString();
    }
References GetNetworkID().
GetNumberOfHealthLevels()
proto native int GetNumberOfHealthLevels (string zone = "")
Returns global number of health levels specified in object's config class parameter healthLevels (range is usually 0..4, 0 = pristine, 1 = worn, 2 = damaged, 3 = badly damaged, 4 = ruined but can be changed).
Parameters
zoneName if empty string, returns number of global health levels
Referenced by AddHealthLevel().
GetOrientation()
proto native vector GetOrientation ()
Retrieve orientation (yaw, pitch, roll) in degrees
Returns
vector of yaw, pitch and roll angles (x = yaw, y = pitch, z = roll)
Definition at line 306 of file areadamagemanager.c.
    {
        return m_AreaOrientation;
    }
References m_AreaOrientation.
Referenced by FireplaceBase::AfterStoreLoad(), TrapSpawnBase::AlignCatch(), ItemBase::CreateAreaDamage(), CreateCollisionTrigger(), CreateTrigger(), TrapBase::CreateTrigger(), ItemBase::DoMeasurement(), DayZSpectator::EOnFrame(), DayZInfected::HandleOrientation(), HandleVisualEffects(), IsColliding(), IsCollidingEx(), LateInit(), FireplaceBase::OnIgnitedThis(), GardenBase::OnStoreLoad(), ItemBase::OnStoreLoad(), BaseBuildingBase::PerformRoofCheckForBase(), ManBase::PhysicalPredictiveDropItem(), SetParticleOrientation(), UndergroundTriggerCarrierBase::SpawnTrigger(), and FlammableBase::TryTransformIntoStick().
GetPosition()
proto native vector GetPosition ()
Retrieve position.
Retrieve position.
Warning
Only gets the cached variable, for immediate effect use GetCurrent variant
Returns
vector The world position of the Effect
Definition at line 44 of file undergroundarealoader.c.
    {
        return Vector(Position[0],Position[1],Position[2]);
    }
GetSelectionList()
proto native void GetSelectionList (out TStringArray selectionList)
Referenced by HasSelection().
GetSelectionPositionLS()
vector GetSelectionPositionLS (string name)
Definition at line 692 of file object.c.
    {
        return GetGame().ObjectGetSelectionPositionLS(this, name);
    }
References GetGame(), name, and CGame::ObjectGetSelectionPositionLS().
Referenced by Weapon::LiftWeaponCheck().
GetSelectionPositionMS()
vector GetSelectionPositionMS (string name)
Definition at line 697 of file object.c.
    {
        return GetGame().ObjectGetSelectionPositionMS(this, name);
    }
References GetGame(), name, and CGame::ObjectGetSelectionPositionMS().
Referenced by ItemBase::GetSlotPosition(), DayZCreatureAI::SetDefaultHitPosition(), DayZInfected::SetDefaultHitPosition(), and ManBase::SetDefaultHitPosition().
GetSelectionPositionOld()
vector GetSelectionPositionOld (string name)
Definition at line 687 of file object.c.
    {
        return GetGame().ObjectGetSelectionPosition(this, name);
    }
References GetGame(), name, and CGame::ObjectGetSelectionPosition().
GetSelectionPositionWS()
vector GetSelectionPositionWS (string name)
Definition at line 702 of file object.c.
    {
        return GetGame().ObjectGetSelectionPositionWS(this, name);
    }
References GetGame(), name, and CGame::ObjectGetSelectionPositionWS().
GetSpeed()
proto native vector GetSpeed ()
Retrieve object's speed in global space.
GetSurfaceNoise()
float GetSurfaceNoise ()
Returns noise multiplier of surface under object.
Definition at line 252 of file object.c.
    {
        vector position = GetPosition();
        return GetGame().SurfaceGetNoiseMultiplier(NULL, position, -1);
    }
References GetGame(), GetPosition, and CGame::SurfaceGetNoiseMultiplier().
GetSurfaceType()
string GetSurfaceType ()
Returns type of surface under object.
Definition at line 259 of file object.c.
    {
        string surface_type;
        int liquid_type;
        GetGame().SurfaceUnderObject(this, surface_type,liquid_type);
//      Print(surface_type);
//      Print(liquid_type);
        return surface_type;
    }
References GetGame(), and CGame::SurfaceUnderObject().
Referenced by HandleView(), OnStepEvent(), and DayZCreature::ProcessStepEvent().
GetType()
string GetType ()
Get config class of object.
Definition at line 334 of file object.c.
    {
        string ret;
        GetGame().ObjectGetType(this, ret);
        return ret;
    }
References GetGame(), and CGame::ObjectGetType().
Referenced by Ammo_40mm_Smoke_ColorBase::Activate(), ItemBase::BatteryCharger(), EntityAI::Building(), InventoryItem::CanBeCombined(), ItemBase::CanPutInCargo(), BaseBuildingBase::CanReceiveAttachment(), ItemBase::ChangeInfestation(), Chemlight_ColorBase::Chemlight_ColorBase(), Chemlight_ColorBase::CreateLight(), RecipeBase::Do(), InventoryItemSuper::EEHealthLevelChanged(), EEInit(), Inventory_Base::EmptySeedPack(), ItemBase::GetEnergyNeededToCharge(), GetHiddenSelections(), GetHiddenSelectionsMaterials(), GetHiddenSelectionsTextures(), ManBase::GetItemOnSlot(), GetModelName(), InventoryItem::GetMuzzleID(), ScriptedWidgetEventHandler::GetOnScreenPosition(), InventoryItem::GetProtectionLevel(), PluginRecipesManagerBase::GetRecipeIntersection(), ItemBase::GetTimeNeededToCharge(), HasAnimation(), InventoryItem::HasFoodStage(), ItemBase::HideAllAnimationsAndProxyPhysics(), Hologram::Hologram(), AlarmClock_ColorBase::Init(), KitchenTimer::Init(), FlammableBase::Init(), InventoryItemSuper::Init2DPreloadType(), InventoryItemSuper::InitCameraOverrideProperties(), InventoryItemSuper::InitDOFAvailability(), Weapon::InitDOFProperties(), InventoryItemSuper::InitOpticsDOFProperties(), InventoryItemSuper::InitOpticsPP(), InventoryItemSuper::InitReddotData(), Weapon::InitReliability(), KindOf(), InventoryItem::KindOf(), Weapon::LoadCurrentFSMState(), InventoryItem::LoadParticleConfigOnFire(), InventoryItem::LoadParticleConfigOnOverheating(), LockOvenAttachments(), ItemBase::OnInitEnergy(), InventoryItem::OnRightClick(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), OnWorkStart(), ItemBase::PlantBase(), InventoryItem::PlayAttachSound(), Weapon::SaveCurrentFSMState(), ItemBase::SetFuel(), PluginRecipesManagerBase::SortIngredientsInRecipe(), InventoryItem::SplitIntoStackMax(), InventoryItem::SplitIntoStackMaxHands(), InventoryItem::SplitItem(), InventoryItem::SplitItemToInventoryLocation(), VicinityObjects::TransformToVicinityObjects(), and FlammableBase::TryTransformIntoStick().
GetWorldPosition()
proto native vector GetWorldPosition ()
Returns world position. This function takes proxy transformation into account.
Referenced by FilterObstructedObjectsByGrouping(), UIScriptedMenu::Init(), EffectArea::InitZone(), ContaminatedArea_Static::InitZoneClient(), ContaminatedArea_Dynamic::InitZoneClient(), SpookyArea::InitZoneClient(), IsSpaceFor(), UIScriptedMenu::OnMouseButtonDown(), ParticleSource::SetWiggle(), and ManBase::SpreadAgentsEx().
HasAnimation()
bool HasAnimation (string anim_name)
Searches object's config for the given animation name. Returns true if it was found, or false if not.
Definition at line 289 of file object.c.
    {
        string cfg_path_vehicles = "CfgVehicles " + GetType() + " ";
        if ( GetGame().ConfigIsExisting (cfg_path_vehicles)  &&  GetGame().ConfigIsExisting (cfg_path_vehicles + "AnimationSources " + anim_name) )
        {
            return true;
        }
        string cfg_path_weapons = "CfgWeapons " + GetType() + " ";
        if ( GetGame().ConfigIsExisting (cfg_path_weapons)  &&  GetGame().ConfigIsExisting (cfg_path_weapons + "AnimationSources " + anim_name) )
        {
            return true;
        }
        string cfg_path_magazines = "CfgMagazines " + GetType() + " ";
        if ( GetGame().ConfigIsExisting (cfg_path_magazines)  &&  GetGame().ConfigIsExisting (cfg_path_magazines + "AnimationSources " + anim_name) )
        {
            return true;
        }
        return false;
    }
References ConfigIsExisting(), GetGame(), and GetType().
HasDamageSystem()
proto native bool HasDamageSystem ()
Checks if object's DamageSystem has been initialized(despite the name, does not really reliably answer the question whether the object is configured to have damage system or not)
HasNetworkID()
bool HasNetworkID ()
Definition at line 1157 of file object.c.
    {
        int lo = 0;
        int hi = 0;
        GetNetworkID(lo, hi);
        return lo | hi;
    }
References GetNetworkID().
HasProxyParts()
bool HasProxyParts ()
Definition at line 621 of file object.c.
    {
        return false;
    }
Referenced by CanProxyObstruct().
HasSelection()
bool HasSelection (string selection)
Returns true if the given selection was found in the p3d file. False if otherwise.
Definition at line 272 of file object.c.
    {
        TStringArray selections = new TStringArray;
        GetSelectionList( selections );
        for ( int i = 0; i < selections.Count(); ++i )
        {
            if ( selections.Get( i ) == selection )
            {
                return true;
            }
        }
        return false;
    }
References GetSelectionList().
Referenced by Weapon::LiftWeaponCheck().
IsActionComponentPartOfSelection()
proto native bool IsActionComponentPartOfSelection (int componentIndex, string selectionName, string geometry = "")
return true if selection containts action component, 'geometry' can be "fire" or "view" (default "" for mixed/legacy mode)
IsAlive()
bool IsAlive ()
Definition at line 384 of file object.c.
    {
        return !IsDamageDestroyed();
    }
References IsDamageDestroyed().
Referenced by DayZInfected::CanReceiveAttachment(), ManBase::CanSpawnBreathVaporEffect(), Capture(), ManBase::CheckDeath(), CheckForRespawn(), CheckForTakeItem(), ManBase::CommandHandler(), DayZInfected::EEHitBy(), EEHitBy(), ManBase::EEItemOutOfHands(), DayZCreatureAI::EOnContact(), DayZInfected::EOnContact(), EOnContact(), ManBase::EOnPostFrame(), AreaDamageBase::EvaluateDamage_Common(), EntityAI::GetPlayerState(), ManBase::GetUndergroundHandler(), HandleADS(), HandleDamageHit(), DayZInfected::HandleDeath(), HandleHandEvent(), DayZInfected::HandleSoundEvents(), HandleView(), HumanInventory::LocalDestroyEntity(), ManBase::OnCommandHandlerTick(), OnItemInHandsChanged(), ManBase::OnScheduledTick(), ManBase::OnUnconsciousStop(), OnUpdate(), Release(), HumanInventory::ReplaceItemInElsewhereWithNewinHandsImpl(), HumanInventory::ReplaceItemInHandsWithNewImpl(), EntityAI::ServerTakeEntityToTargetCargo(), ManBase::SetDeathDarknessLevel(), HumanInventory::TakeEntityAsAttachmentEx(), HumanInventory::TakeEntityToCargoEx(), HumanInventory::TakeToDst(), and TakeToDst().
IsAmmoPile()
bool IsAmmoPile ()
Returns if this entity is Ammo Pile.
Definition at line 433 of file object.c.
    {
        return false;
    }
IsAnyInherited()
bool IsAnyInherited (array< typename > typenames)
Definition at line 793 of file object.c.
    {
        bool ret;
        for( int i = 0; i < typenames.Count(); i++ )
        {
            ret = ret || this.IsInherited( typenames.Get(i) );
        }
        return ret;
    }
Referenced by AreaDamageBase::EvaluateDamage_Common().
IsBeingBackstabbed()
bool IsBeingBackstabbed ()
Definition at line 556 of file object.c.
    {
        return false;
    }
IsBuilding()
bool IsBuilding ()
Returns if this entity is Building.
Definition at line 504 of file object.c.
    {
        return false;
    }
Referenced by ActionLockDoors::ActionCondition(), ActionUnlockDoors::ActionCondition(), ActionCloseDoors::ActionCondition(), ActionLockedDoors::ActionCondition(), and ActionOpenDoors::ActionCondition().
IsBush()
bool IsBush ()
Returns if this entity is bush.
Definition at line 475 of file object.c.
    {
        return false;
    }
Referenced by CanBeIgnoredByDroppedItem().
IsClothing()
bool IsClothing ()
Returns if this entity is Clothing.
Definition at line 445 of file object.c.
    {
        return false;
    }
IsContainer()
bool IsContainer ()
Definition at line 421 of file object.c.
    {
        return false;
    }
IsCorpse()
bool IsCorpse ()
Definition at line 579 of file object.c.
    {
        return false;
    }
Referenced by IsFood().
IsCuttable()
bool IsCuttable ()
Definition at line 480 of file object.c.
    {
        return false;
    }
IsDamageDestroyed()
proto native bool IsDamageDestroyed ()
Checks if object is destroyed.
Referenced by InventoryItem::GetProtectionLevel(), IsAlive(), IsRuined(), PumpkinHelmet::UpdateGlowState(), and ZombieMaleBase::ZmbM_Mummy().
IsElectricAppliance()
bool IsElectricAppliance ()
Returns if this is an appliance, that can be plugged into electric circuit (== not energy source)
Definition at line 533 of file object.c.
    {
        return false;
    }
IsEntityAI()
bool IsEntityAI ()
Returns if this entity is EntityAI.
Definition at line 397 of file object.c.
    {
        return false;
    }
IsFireplace()
bool IsFireplace ()
Returns if this entity is fireplacebase.
Definition at line 451 of file object.c.
    {
        return false;
    }
Referenced by TripodBase::CanSwapEntities(), and InventoryItem::ProcessItemTemperature().
IsFood()
bool IsFood ()
Returns if this entity if a food item.
Definition at line 564 of file object.c.
    {
        return ( IsFruit() || IsMeat() || IsCorpse() || IsMushroom() );
    }
References IsCorpse(), IsFruit(), IsMeat(), and IsMushroom().
IsFruit()
bool IsFruit ()
Definition at line 569 of file object.c.
    {
        return false;
    }
Referenced by IsFood().
IsFuelStation()
bool IsFuelStation ()
Returns if this entity is Fuel Station (extends Building)
Definition at line 521 of file object.c.
    {
        return false;
    }
IsHealthVisible()
bool IsHealthVisible ()
Returns if the health of this entity should be displayed (widgets, inventory)
Definition at line 590 of file object.c.
    {
        return true;
    }
IsHologram()
bool IsHologram ()
Definition at line 616 of file object.c.
    {
        return false;
    }
Referenced by ItemBase::AssembleKit(), KitBase::DisassembleKit(), ItemBase::EOnInit(), RefreshFireplaceVisuals(), and ItemBase::UpdateAllSelections().
IsInventoryItem()
bool IsInventoryItem ()
Returns if this entity is InventoryItem.
Definition at line 439 of file object.c.
    {
        return false;
    }
Referenced by ScriptedWidgetEventHandler::GetOnScreenPosition().
IsItemBase()
bool IsItemBase ()
Returns if this entity is ItemBase.
Definition at line 415 of file object.c.
    {
        return false;
    }
IsItemTent()
bool IsItemTent ()
Definition at line 606 of file object.c.
    {
        return false;
    }
IsKindOf()
bool IsKindOf (string type)
Check config class name of the object.
Definition at line 378 of file object.c.
    {
        return GetGame().ObjectIsKindOf(this, type);
    }
References GetGame(), and CGame::ObjectIsKindOf().
Referenced by ActionUnrestrainTarget::ActionCondition(), Barrel_ColorBase::BleachClothes(), RecipeBase::CanDo(), RecipeBase::CheckIngredientMatch(), ItemBase::EEItemAttached(), ItemBase::EEItemDetached(), ManBase::FindCargoByBaseType(), Managed::LoadCharacterData(), LoadFromCfg(), ActionUnrestrainTargetCB::ObtainUnrestrainTime(), ActionUnrestrainTarget::OnFinishProgressServer(), Hologram::PlaceEntity(), ItemBase::RefreshAttachements(), and UIScriptedMenu::SetPreviewObject().
IsMagazine()
bool IsMagazine ()
Returns if this entity is Magazine.
Definition at line 427 of file object.c.
    {
        return false;
    }
Referenced by InventoryItem::CombineItems(), InventoryItem::EEKilled(), InventoryItem::EEOnCECreate(), and InventoryItem::OnAction().
IsMan()
bool IsMan ()
Returns if this entity is Man.
Definition at line 391 of file object.c.
    {
        return false;
    }
IsMeat()
bool IsMeat ()
Definition at line 574 of file object.c.
    {
        return false;
    }
Referenced by IsFood().
IsMeleeWeapon()
bool IsMeleeWeapon ()
returns if this entity is Melee Weapon
Definition at line 498 of file object.c.
    {
        return false;
    }
IsMushroom()
bool IsMushroom ()
Definition at line 584 of file object.c.
    {
        return false;
    }
Referenced by IsFood(), and ItemBase::ProcessDecay().
IsParticle()
bool IsParticle ()
Definition at line 601 of file object.c.
    {
        return false;
    }
IsPeltBase()
bool IsPeltBase ()
Returns if this entity is Pelt_Base.
Definition at line 486 of file object.c.
    {
        return false;
    }
IsPendingDeletion()
proto native bool IsPendingDeletion ()
Get whether the Effect is queued up for being cleaned up.
Determine whether this object is in the deletion ProcessDirectDamage Is useful in the case where a parent is being deleted, since the children will be deleted first So to know if something was removed or detached from it's parent, use this check to see if it is because the parent is being deleted
Returns
bool Whether the Effect is queued up for being cleaned up
Definition at line 256 of file effect.c.
    {
        return m_IsPendingDeletion;
    }
References m_IsPendingDeletion.
Referenced by Destroy().
IsPlainObject()
proto native bool IsPlainObject ()
Is this just static object without config? So we can avoid calling unnecessary methods.
Referenced by CanObstruct().
IsRock()
bool IsRock ()
Returns if this entity is rock.
Definition at line 463 of file object.c.
    {
        return false;
    }
IsRuined()
bool IsRuined ()
Returns whether the object is ruined (0 Health).
Returns
bool true = item has 0 Health or less
if (item.IsRuined())
{
    Print("Object is ruined!");
}
Definition at line 1042 of file object.c.
    {
        return IsDamageDestroyed();
    }
References IsDamageDestroyed().
Referenced by InventoryItem::CanPutAsAttachment(), FuelStation::HasFuelToGive(), Clothing::HasValidFilter(), IsActivable(), IsIgnoredByConstruction(), ManBase::IsIgnoredByConstruction(), IsTakeable(), RemoteDetonatorTrigger::OnActivatedByItem(), OnCEUpdate(), RemoteDetonatorTrigger::OnCEUpdate(), InventoryItemSuper::OnInventoryEnter(), InventoryItemSuper::OnInventoryExit(), InventoryItemSuper::OnWasAttached(), InventoryItemSuper::OnWasDetached(), TrapSpawnBase::SetupTrap(), StandUp(), and FlammableBase::StandUp().
IsScenery()
proto native bool IsScenery ()
Is this Scenery? (handy for excluding terain when it is not needed)
Referenced by CanObstruct().
IsScriptedLight()
bool IsScriptedLight ()
Definition at line 611 of file object.c.
    {
        return false;
    }
IsStaticTransmitter()
bool IsStaticTransmitter ()
Returns if this entity is Static Transmitter.
Definition at line 403 of file object.c.
    {
        return false;
    }
IsTransmitter()
bool IsTransmitter ()
Returns if this entity is a non-static Transmitter.
Definition at line 409 of file object.c.
    {
        return false;
    }
IsTransport()
bool IsTransport ()
Returns if this entity is transport.
Definition at line 527 of file object.c.
    {
        return false;
    }
Referenced by ActionFillBrakes::ActionCondition(), ActionFillFuel::ActionCondition(), and ActionFillOil::ActionCondition().
IsTree()
bool IsTree ()
Returns if this entity is tree.
Definition at line 457 of file object.c.
    {
        return false;
    }
Referenced by CanBeIgnoredByDroppedItem(), GetAmountOfDrops(), GetAmountOfDropsEx(), GetDamageToMiningItemEachDrop(), GetDamageToMiningItemEachDropEx(), GetMaterialAndQuantityMap(), and GetMaterialAndQuantityMapEx().
IsWeapon()
bool IsWeapon ()
Returns if this entity is Weapon.
Definition at line 492 of file object.c.
    {
        return false;
    }
IsWell()
bool IsWell ()
Returns if this entity is Well (extends Building)
Definition at line 510 of file object.c.
    {
        return false;
    }
IsWoodBase()
bool IsWoodBase ()
Returns whether object is PlanBase.
Definition at line 469 of file object.c.
    {
        return false;
    }
KindOf()
bool KindOf (string tag)
Compares config class name to given string.
Definition at line 774 of file object.c.
    {
        bool found = false;
        string item_name = this.GetType();
        TStringArray item_tag_array = new TStringArray;
        ConfigGetTextArray("cfgVehicles " + item_name + " itemInfo", item_tag_array);
        int array_size = item_tag_array.Count();
        for (int i = 0; i < array_size; i++)
        {
            if ( item_tag_array.Get(i) == tag )
            {
                found = true;
                break;
            }
        }
        return found;
    }
References ConfigGetTextArray(), and GetType().
MemoryPointExists()
proto native bool MemoryPointExists (string memoryPoint)
Referenced by ItemBase::CalcDamageAreaRotation(), CanReachSeatFromDoors(), CarScript(), BaseBuildingBase::CheckMemoryPointVerticalDistance(), ItemBase::CreateAreaDamage(), GetCenter(), GetCollisionBoxData(), BaseBuildingBase::GetKitSpawnPosition(), GetLightPosition(), GetMemoryPointPosition(), ClaymoreMine::GetViewIndex(), ItemBase::GetViewIndex(), BaseBuildingBase::HasProperDistance(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), FireworksLauncher::OnFuseIgnitedClient(), PlaySoundSetAtMemoryPoint(), ItemBase::SpawnCatch(), and TranslateMemoryPointsToWaterLevels().
ModelToWorld()
vector ModelToWorld (vector modelPos)
Definition at line 708 of file object.c.
    {
        return GetGame().ObjectModelToWorld(this, modelPos);
    }
References GetGame(), and CGame::ObjectModelToWorld().
Referenced by ItemBase::CalcDamageAreaRotation(), CanReachSeatFromDoors(), BaseBuildingBase::CheckMemoryPointVerticalDistance(), ItemBase::CreateAreaDamage(), Get_1_1PointPosWS(), Get_1_2PointPosWS(), Get_2_1PointPosWS(), Get_2_2PointPosWS(), GetBackPointPosWS(), GetCenter(), GetCoolantPtcPosWS(), GetEnginePointPosWS(), GetEnginePosWS(), GetFrontPointPosWS(), BaseBuildingBase::GetKitSpawnPosition(), GetLightPosition(), GetMemoryPointPosition(), GetRefillPointPosWS(), ItemBase::GetSlotPosition(), HandleEngineSound(), BaseBuildingBase::HasProperDistance(), BaseBuildingBase::IsFacingCamera(), BaseBuildingBase::IsFacingPlayer(), FireworksLauncher::OnFuseIgnitedClient(), TrapBase::OnSteppedOn(), PlaySoundSetAtMemoryPoint(), ItemBase::SpawnCatch(), and TranslateMemoryPointsToWaterLevels().
NameOverride()
bool NameOverride (out string output)
Definition at line 1165 of file object.c.
    {
        return false;
    }
Referenced by GetDisplayName().
Object()
enum ProcessDirectDamageFlags Object ()
OnEnterTrigger()
void OnEnterTrigger (ScriptedEntity trigger)
Object entered trigger.
Definition at line 36 of file object.c.
{}
OnExplodeClient()
void OnExplodeClient ()
Called on clients when this object explodes.
Definition at line 115 of file object.c.
    {
        string ammoType = ConfigGetString("ammoType");
        if (ammoType == "")
            ammoType = "Dummy_Heavy";
        vector pos = GetPosition();
        // Handle spawn of particle if one is configured in config
        AmmoEffects.PlayAmmoParticle(ammoType, pos);
        // Handle spawn of Effect if one is configured in config
        AmmoEffects.PlayAmmoEffect(ammoType, pos);
    }
References ConfigGetString(), GetPosition, AmmoEffects::PlayAmmoEffect(), and AmmoEffects::PlayAmmoParticle().
Referenced by SynchExplosion().
OnExplosionEffects()
override void OnExplosionEffects (Object source, Object directHit, int componentIndex, string surface, vector pos, vector surfNormal, float energyFactor, float explosionFactor, bool isWater, string ammoType)
Definition at line 131 of file object.c.
{ }
OnLeaveTrigger()
void OnLeaveTrigger (ScriptedEntity trigger)
Object left trigger.
Definition at line 39 of file object.c.
{}
OnPlayerRecievedHit()
void OnPlayerRecievedHit ()
Definition at line 1155 of file object.c.
{}
Referenced by CommandHandler().
OnRPC()
void OnRPC (PlayerIdentity sender, int rpc_type, ParamsReadContext ctx)
Called after remote procedure call is recieved for this object.
Parameters
rpc_type user defined identification of RPC
ctx read context for params
Definition at line 7359 of file itembase.c.
References GetGame(), TrapBase::OnDisarm(), ParticleFireWindyNoIgniteStart(), ParticleWetNoIgniteStart(), PlayDeployLoopSound(), PlayDisarmingLoopSound(), PlayEmptyingLoopSound(), PlayPouringLoopSound(), PlayRepackingLoopSound(), Serializer::Read(), SnapOnObject(), SoundFireStop(), SoundFireWetNoIgniteStart(), SoundFireWindyNoIgniteStart(), StopDeployLoopSound(), StopDisarmingLoopSound(), StopEmptyingLoopSound(), StopPouringLoopSound(), and StopRepackingLoopSound().
OnSimulationDisabled()
void OnSimulationDisabled ()
Event called from C++ when simulation is disabled.
Definition at line 1051 of file object.c.
{}
OnSimulationEnabled()
void OnSimulationEnabled ()
Event called from C++ when simulation is enabled.
Definition at line 1048 of file object.c.
{}
OnTreeCutDown()
void OnTreeCutDown (EntityAI cutting_entity)
Called when tree is chopped down. 'cutting_entity' can be tool, or player, if cutting bush with bare hands.
Definition at line 328 of file object.c.
    {
    }
PlaceOnSurface()
proto native void PlaceOnSurface ()
Place object on surface.
Referenced by UnlockServer().
PlaySound()
SoundOnVehicle PlaySound (string sound_name, float range, bool create_local = true)
Plays the given sound once on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
Definition at line 1058 of file object.c.
    {
        return GetGame().CreateSoundOnObject(this, sound_name, range, false, create_local);
    }
References CGame::CreateSoundOnObject(), and GetGame().
PlaySoundLoop()
SoundOnVehicle PlaySoundLoop (string sound_name, float range, bool create_local = true)
Plays the given sound in loop on this object's instance. Range is in meters. Created sound is only local, unless create_local is set to false. Returns the sound itself.
Definition at line 1064 of file object.c.
    {
        return GetGame().CreateSoundOnObject(this, sound_name, range, true, create_local);
    }
References CGame::CreateSoundOnObject(), and GetGame().
Referenced by FlammableBase::OnWork(), ItemBase::OnWorkStart(), ItemBase::SoundBuzzLoopStart(), ItemBase::SoundCookingStart(), and Inventory_Base::SoundCookingStart().
PlaySoundSet()
bool PlaySoundSet (out EffectSound sound, string sound_set, float fade_in, float fade_out, bool loop = false)
EffectSound - plays soundset on this object and returns state of the sound (true - played, false - not played)
Definition at line 1070 of file object.c.
    {
        if ( GetGame() && !GetGame().IsDedicatedServer() )
        {
            if ( sound )
            {
                if ( loop )
                {
                    return true;
                }
                else
                {
                    StopSoundSet( sound );      //auto stop for non-looped sounds
                }
            }
            sound = SEffectManager.PlaySoundOnObject( sound_set, this, fade_in, fade_out, loop );
            sound.SetAutodestroy( true );
            return true;
        }
        return false;
    }
References GetGame(), SEffectManager::PlaySoundOnObject(), EffectSound::SetAutodestroy(), and StopSoundSet().
Referenced by ManBase::BreakLegSound(), InventoryItemSuper::EEHealthLevelChanged(), EEHitByRemote(), Land_Underground_Stairs_Exit::HandleAudioPlayback(), HandleCarHornSound(), Grenade_ChemGas::OnDamageDestroyed(), OnDamageDestroyed(), FireworksLauncher::OnFuseIgnitedClient(), OnPanelUsedSynchronized(), KitchenTimer::OnRingingStopClient(), ItemBase::OnVariablesSynchronized(), OnVariablesSynchronized(), ItemBase::OnWorkStart(), Roadflare::OnWorkStart(), ItemBase::OnWorkStop(), PlaySFX(), PlaySoundSetLoop(), ItemBase::SoundBuildStart(), ItemBase::SoundDestroyStart(), ItemBase::SoundDismantleStart(), SoundFireExtinguishedStart(), SoundFireWetNoIgniteStart(), SoundFireWindyNoIgniteStart(), BaseBuildingBase::SoundGateCloseEnd(), BaseBuildingBase::SoundGateCloseStart(), BaseBuildingBase::SoundGateOpenStart(), SoundLockChangeDial(), SoundLockChangeNumber(), SoundLockClose(), SoundLockOpen(), PASBroadcaster::SoundTurnOff(), ItemBase::SoundTurnOff(), PASBroadcaster::SoundTurnOn(), and ItemBase::SoundTurnOn().
PlaySoundSetAtMemoryPoint()
bool PlaySoundSetAtMemoryPoint (out EffectSound sound, string soundSet, string memoryPoint, bool looped = false, float play_fade_in = 0, float stop_fade_out = 0)
Definition at line 1117 of file object.c.
    {
        vector pos;
        if (MemoryPointExists(memoryPoint))
        {
            pos = GetMemoryPointPos(memoryPoint);
            pos = ModelToWorld(pos);
        }
        else
        {
            ErrorEx(string.Format("Memory point %1 not found when playing soundset %2 at memory point location", memoryPoint, soundSet));
            return false;
        }
        sound = SEffectManager.PlaySoundEnviroment(soundSet, pos, play_fade_in, stop_fade_out, looped);
        return true;
    }
References ErrorEx, GetMemoryPointPos(), MemoryPointExists(), ModelToWorld(), and SEffectManager::PlaySoundEnviroment().
Referenced by HandleAudioPlayback(), HandleSoundEffectsPipeSprinkling(), HandleSoundEffectsUnderwaterPipeSounds(), PlayPipeCreakingSoundOnLocation(), PlaySoundSetAtMemoryPointLooped(), and PlayValveManipulationSound().
PlaySoundSetAtMemoryPointLooped()
bool PlaySoundSetAtMemoryPointLooped (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in = 0, float stop_fade_out = 0)
Definition at line 1111 of file object.c.
    {
        return PlaySoundSetAtMemoryPoint(sound, soundSet, memoryPoint, true, play_fade_in, stop_fade_out);
    }
References PlaySoundSetAtMemoryPoint().
Referenced by HandleAudioPlayback(), HandleSoundEffectsPipeSprinkling(), HandleSoundEffectsUnderwaterPipeSounds(), HandleSoundEffectsWaterLevelMovementSounds(), PlaySoundSetAtMemoryPointLoopedSafe(), and SoundEnded().
PlaySoundSetAtMemoryPointLoopedSafe()
bool PlaySoundSetAtMemoryPointLoopedSafe (out EffectSound sound, string soundSet, string memoryPoint, float play_fade_in = 0, float stop_fade_out = 0)
Same as PlaySoundSetAtMemoryPointLooped, only requests stoppage of the currently playing EffectSound if it already exists and playing, before playing the new sound.
Definition at line 1102 of file object.c.
    {
        if (sound && sound.IsPlaying())
        {
            sound.SoundStop();
        }
        return PlaySoundSetAtMemoryPointLooped(sound, soundSet, memoryPoint, play_fade_in, stop_fade_out);
    }
References PlaySoundSetAtMemoryPointLooped().
PlaySoundSetLoop()
bool PlaySoundSetLoop (out EffectSound sound, string sound_set, float fade_in, float fade_out)
EffectSound - plays soundset on this object in loop and returns state of the sound (true - played, false - not played)
Definition at line 1096 of file object.c.
    {
        return PlaySoundSet( sound, sound_set, fade_in, fade_out, true );
    }
References PlaySoundSet().
Referenced by BuildingSuper::EEInit(), House::EEInit(), FireworksLauncher::OnFuseIgnitedClient(), OnRingingStartClient(), Roadflare::OnWorkStart(), ManBase::SetContaminatedEffectEx(), ManBase::SetDecayEffects(), ItemBase::SoundBurningStart(), Land_Underground_Stairs_Exit::SoundEnded(), SoundFireExtinguishingStart(), SoundFireHeavyStart(), SoundFireLightStart(), SoundFireNoFireStart(), SoundSmokeEnd(), SoundSmokeLoop(), SoundSmokeStart(), PASBroadcaster::SoundTurnedOnNoiseStart(), ItemTransmitter::SoundTurnedOnNoiseStart(), and ItemBase::StartLoopSound().
PostAreaDamageActions()
void PostAreaDamageActions ()
Definition at line 1150 of file object.c.
{}
PreAreaDamageActions()
void PreAreaDamageActions ()
Definition at line 1151 of file object.c.
{}
ProcessDirectDamage()
proto native void ProcessDirectDamage (int damageType, EntityAI source, string componentName, string ammoName, vector modelPos, float damageCoef = 1.0, int flags = 0)
Applies damage on object.
Parameters
damageType DT_CLOSE_COMBAT/DT_FIRE_ARM/DT_EXPLOSION/DT_CUSTOM
source source of damage
componentName which 'DamageZone' was hit (NOT a component name, actually!)
ammoName ammoType, which defines how much damage should be applied
directHitModelPos local position of hit
damageCoef multiplier of applied damage
flags enables/disables special behaviour depending on the flags used (ProcessDirectDamageFlags type)
Referenced by CheckContactCache(), and EOnPostSimulate().
ProcessMeleeItemDamage()
EntityAI ProcessMeleeItemDamage (int mode = 0)
Definition at line 1175 of file object.c.
{}
Release()
int Release ()
Definition at line 372 of file object.c.
    {
        return GetGame().ObjectRelease(this);
    }
References GetGame(), and CGame::ObjectRelease().
Referenced by ContactEvent().
RemoveProxyPhysics()
proto native void RemoveProxyPhysics (string proxySelectionName)
Referenced by ItemBase::EEHealthLevelChanged(), ItemBase::EEItemDetached(), ItemBase::HandleOpeningsPhysics(), ItemBase::HideAllAnimationsAndProxyPhysics(), ItemBase::RefreshPhysics(), FireplaceBase::RefreshPhysics(), Inventory_Base::RefreshPhysics(), ItemBase::SetPartFromSyncData(), ItemBase::ToggleAnimation(), ItemBase::UpdateAttachmentPhysics(), ItemBase::UpdatePhysics(), and ItemBase::UpdateSelections().
RPC()
void RPC (int rpc_type, array< ref Param > params, bool guaranteed, PlayerIdentity recipient = NULL)
Remote procedure call shortcut, see CGame.RPC / CGame.RPCSingleParam.
Definition at line 669 of file object.c.
    {
        GetGame().RPC(this, rpc_type, params, guaranteed, recipient);
    }
References GetGame(), and CGame::RPC().
RPCSingleParam()
void RPCSingleParam (int rpc_type, Param param, bool guaranteed, PlayerIdentity recipient = NULL)
Remote procedure call shortcut, see CGame.RPCSingleParam / CGame.RPC.
Definition at line 675 of file object.c.
    {
        GetGame().RPCSingleParam(this, rpc_type, param, guaranteed, recipient);
    }
References GetGame(), and CGame::RPCSingleParam().
Referenced by ManBase::OnRPC(), and InventoryItemSuper::SyncMapMarkers().
SetAffectPathgraph()
proto native void SetAffectPathgraph (bool fromConfig, bool affect)
Sets if object's geometry affects pathgraph generation. If first parameter is true, it ignores second parameter and sets affecting pathgraph by parameter set in object's config.
Referenced by ItemBase::RegenerateNavmesh(), StartFire(), StopFire(), and ItemBase::UpdateNavmesh().
SetAllowDamage()
proto native void SetAllowDamage (bool val)
Enable or disable object to receive damage.
Parameters
enable or disable
Referenced by Inventory_Base::Fill(), Inventory_Base::Fold(), ItemBase::PileOfWoodenPlanks(), and Inventory_Base::Unfold().
SetBeingBackstabbed()
void SetBeingBackstabbed (int backstabType)
Definition at line 561 of file object.c.
{}
SetCanBeDestroyed()
proto native void SetCanBeDestroyed (bool val)
Enable or disable destruction of object (after health is depleated)
Parameters
enable or disable
SetDestructTime()
proto native void SetDestructTime (float time)
Sets the time over which to perform DestructTent/DestructTree.
Parameters
time time over which to perform DestructTent/DestructTree
SetDirection()
proto native void SetDirection (vector vPos)
Set direction of object.
Parameters
vDirection,direction vector
Note
object up vector is always y-axis
SetDynamicPhysicsLifeTime()
proto native void SetDynamicPhysicsLifeTime (float lifeTime)
Referenced by InventoryItem::StopItemDynamicPhysics().
SetHealth() [1/2]
void SetHealth (float health)
Equivalent of SetHealth("", "", float value);.
Definition at line 905 of file object.c.
    {
        SetHealth("", "", health);
    }
References SetHealth().
SetHealth() [2/2]
proto native void SetHealth (string zoneName, string healthType, float value)
Sets current state of health.
Parameters
zoneName if empty string, sets state of global health
healthType if empty string, sets state of main health
Referenced by ItemBase::CheckForHybridAttachments(), InventoryItem::CombineItems(), DestroySmokeGrenade(), EEItemAttached(), EEItemDetached(), Apple::EEOnCECreate(), GreenBellPepper::EEOnCECreate(), Pear::EEOnCECreate(), Plum::EEOnCECreate(), Potato::EEOnCECreate(), Tomato::EEOnCECreate(), Zucchini::EEOnCECreate(), MushroomBase::EEOnCECreate(), EOnPostSimulate(), ClaymoreMine::OnActivatedByItem(), Plastic_Explosive::OnActivatedByItem(), Ammo_40mm_Smoke_ColorBase::OnActivatedByItem(), OnActivatedByItem(), Grenade_Base::OnActivateFinished(), Grenade_Base::OnActivateImmediate(), ClaymoreMine::OnDisarmed(), ManBase::OnUnconsciousUpdate(), Chemlight_ColorBase::OnWorkStop(), Heatpack::OnWorkStop(), Roadflare::OnWorkStop(), ManBase::ResetPlayer(), SetHealth(), SetHealth01(), SetHealthMax(), and ManBase::SetLegHealth().
SetHealth01()
void SetHealth01 (string zoneName, string healthType, float coef)
Sets health relative to its maximum.
Definition at line 923 of file object.c.
    {
        SetHealth(zoneName,healthType,(GetMaxHealth(zoneName,healthType)*coef));
    }
References GetMaxHealth(), and SetHealth().
Referenced by BroomBase::CalculateQuantity(), BroomBase::DebugSetHealthAndEnergy(), InventoryItem::OnAction(), FireworksLauncher::OnFiringStop(), PlateCarrierVest::OnWasAttached(), SetHealthLevel(), and InventoryItem::SetZoneDamageCEInit().
SetHealthLevel()
void SetHealthLevel (int healthLevel, string zone = "")
Sets specific health level. It will use the cutoff value as returned by 'GetHealthLevelValue' as the health value for the given health level, which means it will always be set to the max health as allowed by the given health level.
Definition at line 910 of file object.c.
    {
        SetHealth01(zone,"", GetHealthLevelValue(healthLevel, zone));
    }
References GetHealthLevelValue(), and SetHealth01().
Referenced by AddHealthLevel().
SetHealthMax()
void SetHealthMax (string zoneName = "", string healthType = "")
Sets health to its maximum (zone or global)
Definition at line 928 of file object.c.
    {
        SetHealth(zoneName,healthType,GetMaxHealth(zoneName,healthType));
    }
References GetMaxHealth(), and SetHealth().
Referenced by InventoryItem::PerformDamageSystemReinit().
SetOrientation()
proto native void SetOrientation (vector vOrientation)
Set orientation (yaw, pitch, roll) in degrees
Parameters
vOrientation,vector of yaw, pitch and roll angles (x = yaw, y = pitch, z = roll)
Referenced by Particle::AddAsChild(), EntityLightSource::AttachOnObject(), DayZSpectator::EOnFrame(), ItemBase::OnInventoryExit(), Roadflare::OnInventoryExit(), Switchable_Base::OnInventoryExit(), TrapSpawnBase::SetupTrap(), Chemlight_ColorBase::StandUp(), StandUp(), and FlammableBase::StandUp().
ShootsExplosiveAmmo()
bool ShootsExplosiveAmmo ()
Returns if this entity is a weapon which can shoot explosive ammo.
Definition at line 515 of file object.c.
    {
        return false;
    }
ShowZonesHealth()
bool ShowZonesHealth ()
Returns true if the health of damage zones should be displayed (instead of global HP of the entity) (action widgets)
Definition at line 596 of file object.c.
    {
        return false;
    }
SpawnDamageDealtEffect()
void SpawnDamageDealtEffect ()
Definition at line 1154 of file object.c.
{ }
Referenced by ManBase::OnPlayerRecievedHit().
StopSoundSet()
bool StopSoundSet (out EffectSound sound)
EffectSound - stops soundset and returns state of the sound (true - stopped, false - not playing)
Definition at line 1137 of file object.c.
    {
        if ( sound && GetGame() && ( !GetGame().IsDedicatedServer() ) )
        {
            sound.SoundStop();
            sound = null;
            return true;
        }
        return false;
    }
References GetGame().
Referenced by ManBase::EEDelete(), HandleAudioPlayback(), HandleSoundEffectsPipeCreaking(), HandleSoundEffectsPipeSprinkling(), HandleSoundEffectsUnderwaterPipeSounds(), HandleSoundEffectsWaterLevelMovementSounds(), ItemBase::OnWorkStop(), Roadflare::OnWorkStop(), PlaySoundSet(), ManBase::SetContaminatedEffectEx(), ManBase::SetDecayEffects(), ItemBase::SoundBurningStop(), SoundFireStop(), SoundSmokeStop(), PASBroadcaster::SoundTurnedOnNoiseStop(), ItemTransmitter::SoundTurnedOnNoiseStop(), StopAllParticlesAndSounds(), and ManBase::~PlayerBase().
SynchExplosion()
void SynchExplosion ()
Definition at line 101 of file object.c.
    {
        if ( GetGame().IsDedicatedServer() ) // Multiplayer server
        {
            Param1<EntityAI> p = new Param1<EntityAI>(null);
            GetGame().RPCSingleParam( this, ERPCs.RPC_EXPLODE_EVENT, p, true);
        }
        else if ( !GetGame().IsMultiplayer() ) // Singleplayer
        {
            OnExplodeClient();
        }
    }
References GetGame(), OnExplodeClient(), and CGame::RPCSingleParam().
Referenced by Explode().
ToDelete()
proto native bool ToDelete ()
Flag to determine this object is marked to be deleted soon.
Referenced by Particle::AddAsChild(), ManBase::CanSpawnBreathVaporEffect(), EntityLightSource::DetachFromParent(), ParticleSource::RandomizeOrientation(), Inventory_Base::RefreshPhysics(), and Particle::StopParticle().
WorldToModel()
vector WorldToModel (vector worldPos)
Definition at line 713 of file object.c.
    {
        return GetGame().ObjectWorldToModel(this, worldPos);
    }
References GetGame(), and CGame::ObjectWorldToModel().
Referenced by ExplosivesBase().
Variable Documentation
NO_ATTACHMENT_TRANSFER
NO_ATTACHMENT_TRANSFER
Do not transfer damage to attachments.
Definition at line 0 of file object.c.
NO_GLOBAL_TRANSFER
NO_GLOBAL_TRANSFER
Do not transfer damage to global.
Definition at line 1 of file object.c.
NO_TRANSFER
NO_TRANSFER
NO_ATTACHMENT_TRANSFER | NO_GLOBAL_TRANSFER.
Definition at line 2 of file object.c.