DayzKode: P:/scripts/3_game/DayZ/particles/particlemanager/particlemanager.c File Reference
particlemanager.c File Reference
Classes
class ParticleManagerConstants
Class simply to have easily modded constants.
class ParticleManagerEvents
Invokers for ParticleManager events.
Enumerations
enum ParticleManagerSettingsFlags {
NONE , FIXED_INDEX , BLOCKING , DISABLE_VIRTUAL ,
REUSE_OWNED
}
Flags for ParticleManagerSettings.
Functions
static void CleanupInstance ()
To clean it up properly before game closes.
static ParticleManager GetInstance ()
Access to the static ParticleManager.
void ParticleManager (ParticleManagerSettings settings)
Constructor (ctor)
class ParticleManagerConstants ParticleManagerSettings (int poolSize, int flags=ParticleManagerSettingsFlags.NONE)
Settings given to ParticleManager on creation (in ctor)
void ~ParticleManager ()
dtor
void ~ParticleManagerSettings ()
dtor
API for compatibility with Particle/ParticleSource create/play
Mimics the static Create and Play methods from Particle/ParticleSource
ParticleSource Create (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0")
Legacy function for backwards compatibility.
ParticleSource Create (int particle_id, vector global_pos, vector global_ori="0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
ParticleSource CreateInWorld (int particle_id, vector global_pos, vector global_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter on the given position.
ParticleSource CreateOnObject (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter and attaches it on the given object.
ParticleSource CreateParticle (int id, vector pos, bool playOnCreation=false, Object parent=null, vector ori=vector.Zero, bool forceWorldRotation=false, Class owner=null)
Create function.
ParticleSource CreateParticleEx (int id, vector pos, int flags=ParticlePropertiesFlags.NONE, Object parent=null, vector ori=vector.Zero, Class owner=null)
Master create function.
Static play on creation
You can use the following Play(...) functions to create and activate a particle in 1 line of your script.
ParticleSource Play (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
ParticleSource Play (int particle_id, vector global_pos)
Legacy function for backwards compatibility with 1.01 and below.
ParticleSource PlayInWorld (int particle_id, vector global_pos)
Creates a particle emitter on the given position and activates it.
ParticleSource PlayInWorldEx (int particle_id, Object parent_obj, vector global_pos, vector global_ori="0 0 0", bool force_world_rotation=false)
ParticleSource PlayOnObject (int particle_id, Object parent_obj, vector local_pos="0 0 0", vector local_ori="0 0 0", bool force_world_rotation=false)
Creates a particle emitter, attaches it on the given object and activates it.
Get Particles
API for creating, playing or obtaining particles from the pool
ParticleSource CreateParticleById (int id, ParticleProperties properties)
QoL function for when only one particle is needed using script ParticleList, strongly recommend to read comments for CreateParticles as well.
ParticleSource CreateParticleByPath (string path, notnull ParticleProperties properties)
Create a particle.
proto native int CreateParticles (array< ParticleSource > particles, string path, notnull ParticlePropertiesArray properties, int count=1)
Creates an amount of particles with the properties given.
int CreateParticlesById (int id, notnull ParticlePropertiesArray properties, int count)
QoL function using script ParticleList, strongly recommend to read comments for CreateParticles as well.
array< ParticleSource > CreateParticlesByIdArr (int id, notnull ParticlePropertiesArray properties, int count)
QoL function using script ParticleList, strongly recommend to read comments for CreateParticles as well.
proto native ParticleSource GetParticle (int index)
Manually get the particle at index.
proto native int GetParticles (out array< ParticleSource > outArray, int startIndex, int count)
Manually get a portion of the particles in the pool.
array< ParticleSource > GetParticlesEx (int startIndex, int count)
Manually get a portion of the particles in the pool.
ParticleSource PlayParticleById (int id, array< vector > position)
QoL function for when only one particle is needed using script ParticleList, strongly recommend to read comments for PlayParticles as well.
proto native int PlayParticles (out array< ParticleSource > particles, string path, notnull array< vector > positions, int count=1)
QoL function for when wanting to play a particle at a position right away.
array< ParticleSource > PlayParticlesById (int id, array< vector > positions, int count)
QoL function using script ParticleList, strongly recommend to read comments for PlayParticles as well.
Identification
Identification functionality
proto int GetCountID ()
Gets the ID for the ParticleManager.
override string GetDebugName ()
Gets the debug name for the ParticleManager.
proto string GetDebugNameNative ()
Gets the debug name for the ParticleManager.
proto string GetName ()
Gets the name which is set for the ParticleManager, default is "ParticleSourceManager".
proto static native int GetStaticActiveCount ()
Gets the amount of ParticleManager that are currently existing.
proto static native int GetStaticCount ()
Gets the amount of ParticleManager that have been created since the start of the program.
proto native void SetName (string name)
Set a name for the ParticleManager to identify it more easily.
Properties and state
Obtain information about the state of the ParticleManager
proto native int GetAllocatedCount ()
Gets the amount of particles currently allocated.
proto native int GetPlayingCount ()
Gets the amount of playing particles.
proto native int GetPoolSize ()
Gets the fixed maximum size of the pool.
proto native int GetVirtualCount ()
Gets the amount of virtual particles.
proto native bool IsFinishedAllocating ()
Checks if the ParticleManager has allocated all slots in the pool.
Script Events API
Setting and getting of ScriptEvents
ParticleManagerEvents GetEvents ()
Get the events.
private proto Managed GetScriptEvents ()
Get the events.
private proto void SetScriptEvents (Managed events)
Set the events.
Events
Events called from C++
void OnAllocation (array< ParticleSource > allocatedParticles)
void OnAllocationEnd ()
Variables
class ParticleManagerEvents g_ParticleManager
Has a fixed pool of precreated and reserved particles.
Global ParticleManager settings
Settings applied to the global ParticleManager
static const int FLAGS = ParticleManagerSettingsFlags.NONE
static const int POOL_SIZE = 10000
Enumeration Type Documentation
ParticleManagerSettingsFlags
enum ParticleManagerSettingsFlags
Flags for ParticleManagerSettings.
Enumerator
NONE
FIXED_INDEX
Particles will be locked to the index and not reused.
BLOCKING
Allocation blocks the game until it is done.
DISABLE_VIRTUAL
Disable the creation of virtual particles when the pool is still allocating.
REUSE_OWNED
Reuse stopped particles even if they are owned by something.
Definition at line 2 of file particlemanager.c.
{
    NONE,
    FIXED_INDEX,
    BLOCKING,
    DISABLE_VIRTUAL,
    REUSE_OWNED,
};
Function Documentation
CleanupInstance()
static void CleanupInstance () static
To clean it up properly before game closes.
Definition at line 74 of file particlemanager.c.
    {
        if (g_ParticleManager)
            delete g_ParticleManager;
    }
References g_ParticleManager.
Create() [1/2]
ParticleSource Create (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0")
Legacy function for backwards compatibility.
Definition at line 174 of file particlemanager.c.
    {
        return CreateOnObject( particle_id, parent_obj, local_pos, local_ori);
    }
References CreateOnObject(), and particle_id.
Create() [2/2]
ParticleSource Create (int particle_id, vector global_pos, vector global_ori = "0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 195 of file particlemanager.c.
    {
        return CreateInWorld( particle_id, global_pos, global_ori );
    }
References CreateInWorld(), and particle_id.
CreateInWorld()
ParticleSource CreateInWorld (int particle_id, vector global_pos, vector global_ori = "0 0 0", bool force_world_rotation = false)
Creates a particle emitter on the given position.
Parameters
particle_id int Particle ID registered in ParticleList
global_pos Vector Position where the particel will be created
global_ori vector Orientation (Pitch, Yawn, Roll in degrees) (Optional)
force_world_rotation bool Has absolutely no effect here as there is no parent
Returns
ParticleSource Created particle instance
Definition at line 187 of file particlemanager.c.
    {
        return CreateParticle(particle_id, global_pos, false, null, global_ori, force_world_rotation);
    }
References CreateParticle(), and particle_id.
Referenced by Create().
CreateOnObject()
ParticleSource CreateOnObject (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_world_rotation = false)
Creates a particle emitter and attaches it on the given object.
Parameters
particle_id int Particle ID registered in ParticleList
parent_obj Object Instance on which this particle will be attached
local_pos vector Attachment position local to the parent (Optional)
local_ori vector Orientation local to the parent (Pitch, Yaw, Roll in degrees) (Optional)
force_world_rotation bool Forces particle's orientation to rotate relative to the world and not with the object (Optional)
Returns
ParticleSource Created particle instance
Definition at line 161 of file particlemanager.c.
    {
        return CreateParticle(particle_id, local_pos, false, parent_obj, local_ori, force_world_rotation);
    }
References CreateParticle(), and particle_id.
Referenced by Create().
CreateParticle()
ParticleSource CreateParticle (int id, vector pos, bool playOnCreation = false, Object parent = null, vector ori = vector.Zero, bool forceWorldRotation = false, Class owner = null)
Create function.
Parameters
id int Particle ID registered in ParticleList
pos vector Position of ParticleSource in LS (WS when no parent)
playOnCreation bool Whether to play immediately after creation (Optional)
parent Object Parent Object which will child the ParticleSource (Optional)
ori vector Orientation of ParticleSource in LS (WS when no parent) (Pitch, Yaw, Roll in degrees) (Optional)
forceWorldRotation bool Forces orientation to rotate relative to the world and not with the parent (Optional)
owner Class The owning instance for this particle (Optional)
Returns
ParticleSource Created particle instance when successful
Definition at line 111 of file particlemanager.c.
    {
        int flags = ParticlePropertiesFlags.NONE;
        if (playOnCreation)
        {
            flags = flags | ParticlePropertiesFlags.PLAY_ON_CREATION;
        }
        if (forceWorldRotation)
        {
            flags = flags | ParticlePropertiesFlags.FORCE_WORLD_ROT;
        }
        return CreateParticleEx(id, pos, flags, parent, ori, owner);
    }
References CreateParticleEx().
CreateParticleById()
ParticleSource CreateParticleById (int id, ParticleProperties properties)
QoL function for when only one particle is needed using script ParticleList, strongly recommend to read comments for CreateParticles as well.
Parameters
id int ID of particle registered in ParticleList
properties ParticleProperties Properties of the particles created
Returns
ParticleSource The resulting particle
Definition at line 324 of file particlemanager.c.
    {
        array<ParticleSource> tempArr = new array<ParticleSource>;
        CreateParticles(tempArr, ParticleList.GetParticleFullPath(id), {properties}, 1);
        if (tempArr.Count() > 0)
            return tempArr[0];
        else
            return null;
    }
References CreateParticles(), and ParticleList::GetParticleFullPath().
CreateParticleByPath()
ParticleSource CreateParticleByPath (string path, notnull ParticleProperties properties)
Create a particle.
Parameters
path string Path of particle effect
properties ParticleProperties Properties of the particles created
Returns
ParticleSource The resulting particle
Definition at line 281 of file particlemanager.c.
    {
        array<ParticleSource> tempArr = new array<ParticleSource>;
        CreateParticles(tempArr, path, {properties}, 1);
        if (tempArr.Count() > 0)
            return tempArr[0];
        else
            return null;
    }
References CreateParticles(), and path.
Referenced by CreateParticleEx().
CreateParticleEx()
ParticleSource CreateParticleEx (int id, vector pos, int flags = ParticlePropertiesFlags.NONE, Object parent = null, vector ori = vector.Zero, Class owner = null)
Master create function.
Parameters
id int Particle ID registered in ParticleList
pos vector Position of ParticleSource in LS (WS when no parent)
flags int See ParticlePropertiesFlags (Optional)
parent Object Parent Object which will child the ParticleSource (Optional)
ori vector Orientation of ParticleSource in LS (WS when no parent) (Pitch, Yaw, Roll in degrees) (Optional)
owner Class The owning instance for this particle (Optional)
Returns
ParticleSource Created particle instance when successful
Definition at line 138 of file particlemanager.c.
    {
        string particlePath = ParticleList.GetParticleFullPath(id);
        if (particlePath == "") // There is already an error inside of ParticleList signaling this
        {
            ErrorEx(string.Format("Could not create ParticleSource as particle id %1 is invalid.", id));
            return null;
        }
        ParticleProperties props = new ParticleProperties(pos, flags, parent, ori, owner);
        ParticleSource p = CreateParticleByPath(particlePath, props);
        return p;
    }
References CreateParticleByPath(), ErrorEx, and ParticleList::GetParticleFullPath().
Referenced by CreateParticle().
CreateParticles()
proto native int CreateParticles (array< ParticleSource > particles, string path, notnull ParticlePropertiesArray properties, int count = 1)
Creates an amount of particles with the properties given.
Parameters
particles array<ParticleSource> The resulting particles if an array is given
path string Path of particle effect
properties ParticleProperties Properties of the particles created
count int Amount of particles to create with these properties
Returns
int Amount of particles created in this frame, if the ParticleManager is still allocating while this is called and virtual particles are enabled, the overflow particles will be virtual instead and not given in the out array
Referenced by CreateParticleById(), CreateParticleByPath(), CreateParticlesById(), and CreateParticlesByIdArr().
CreateParticlesById()
int CreateParticlesById (int id, notnull ParticlePropertiesArray properties, int count)
QoL function using script ParticleList, strongly recommend to read comments for CreateParticles as well.
Parameters
id int ID of particle registered in ParticleList
properties ParticleProperties Properties of the particles created
count int Amount of particles to create with these properties
Returns
int Amount of particles created in this frame, if the ParticleManager is still allocating while this is called and virtual particles are enabled, the overflow particles will be virtual instead
Definition at line 299 of file particlemanager.c.
    {
        return CreateParticles(null, ParticleList.GetParticleFullPath(id), properties, count);
    }
References CreateParticles(), and ParticleList::GetParticleFullPath().
CreateParticlesByIdArr()
array< ParticleSource > CreateParticlesByIdArr (int id, notnull ParticlePropertiesArray properties, int count)
QoL function using script ParticleList, strongly recommend to read comments for CreateParticles as well.
Parameters
id int ID of particle registered in ParticleList
properties ParticleProperties Properties of the particles created
count int Amount of particles to create with these properties
Returns
array<ParticleSource> The resulting particles - Read particles param of CreateParticles
Definition at line 311 of file particlemanager.c.
    {
        array<ParticleSource> outArr = new array<ParticleSource>;
        CreateParticles(outArr, ParticleList.GetParticleFullPath(id), properties, count);
        return outArr;
    }
References CreateParticles(), and ParticleList::GetParticleFullPath().
GetAllocatedCount()
proto native int GetAllocatedCount ()
Gets the amount of particles currently allocated.
Returns
int Amount of particles currently allocated
GetCountID()
proto int GetCountID ()
Gets the ID for the ParticleManager.
Returns
int ID for the ParticleManager (different every restart, as it is the nth instance created since the start of the program)
GetDebugName()
override string GetDebugName ()
Gets the debug name for the ParticleManager.
Returns
string "name:id"
Definition at line 436 of file particlemanager.c.
    {
        return GetDebugNameNative();
    }
References GetDebugNameNative().
Referenced by Trigger::AddInsider(), ItemBase::DestroyConstruction(), EntityAI::DropEntityImpl(), TriggerEvents::Enter(), EntityAI::ForceSwapEntitiesImpl(), ItemBase::InitBaseState(), ItemBase::InitVisuals(), TriggerEvents::Leave(), EntityAI::LocalDestroyEntityInHands(), Debug::MeleeLog(), ManBase::NeedInventoryJunctureFromServer(), ItemBase::OnPartDestroyedServer(), ItemBase::OnPartDismantledServer(), ItemBase::OnSetSlotLock(), ItemBase::OnVariablesSynchronized(), Debug::ParticleLog(), EntityAI::PredictiveMoveItemFromHandsToInventory(), EntityAI::PredictiveTakeEntityToTargetAttachmentEx(), EntityAI::PredictiveTakeEntityToTargetCargo(), EntityAI::PredictiveTakeEntityToTargetCargoEx(), Trigger::RemoveInsider(), EntityAI::ReplaceItemElsewhereWithNewInHandsImpl(), EntityAI::ReplaceItemInHandsWithNewElsewhereImpl(), EntityAI::ReplaceItemInHandsWithNewImpl(), EntityAI::ReplaceItemWithNewImpl(), ItemBase::SetMountedState(), ItemBase::SetPartFromSyncData(), Weapon::SpawnAttachedMagazine(), TriggerEvents::Stay(), TriggerEvents::StayFinish(), TriggerEvents::StayStart(), EntityAI::SwapEntitiesImpl(), EntityAI::TakeEntityAsAttachmentExImpl(), EntityAI::TakeEntityAsAttachmentImpl(), ManBase::TakeEntityAsAttachmentImpl(), EntityAI::TakeEntityToCargoImpl(), ManBase::TakeEntityToCargoImpl(), EntityAI::TakeEntityToHandsImpl(), ManBase::TakeEntityToHandsImpl(), EntityAI::TakeEntityToInventoryImpl(), ManBase::TakeEntityToInventoryImpl(), EntityAI::TakeEntityToTargetAttachmentExImpl(), ManBase::TakeEntityToTargetAttachmentImpl(), EntityAI::TakeEntityToTargetCargoExImpl(), EntityAI::TakeEntityToTargetCargoImpl(), ManBase::TakeEntityToTargetCargoImpl(), EntityAI::TakeEntityToTargetInventoryImpl(), ManBase::TakeEntityToTargetInventoryImpl(), EntityAI::TakeToDstImpl(), ManBase::TakeToDstImpl(), Debug::TFLog(), ItemBase::UpdateAttachmentPhysics(), Trigger::UpdateInsiders(), and ItemBase::UpdatePhysics().
GetDebugNameNative()
proto string GetDebugNameNative ()
Gets the debug name for the ParticleManager.
Parameters
dbgName string "name:id"
GetEvents()
ParticleManagerEvents GetEvents ()
Get the events.
Returns
ParticleManagerEvents If there is any events set, this will return them so that additional functionality can be bound to them
Definition at line 523 of file particlemanager.c.
    {
        return ParticleManagerEvents.Cast(GetScriptEvents());
    }
References GetScriptEvents().
GetInstance()
static ParticleManager GetInstance () static
Access to the static ParticleManager.
Definition at line 59 of file particlemanager.c.
    {
        if (!g_ParticleManager && !GetGame().IsDedicatedServer())
        {
            g_ParticleManager = new ParticleManager(
                new ParticleManagerSettings(
                    ParticleManagerConstants.POOL_SIZE,
                    ParticleManagerConstants.FLAGS));
            g_ParticleManager.SetName("GlobalParticleManager");
        }
        return g_ParticleManager;
    }
References ParticleManagerConstants::FLAGS, g_ParticleManager, GetGame(), ParticleManager(), ParticleManagerSettings(), and ParticleManagerConstants::POOL_SIZE.
GetParticle()
proto native ParticleSource GetParticle (int index)
Manually get the particle at index.
Parameters
index int Index of particle
Returns
ParticleSource ParticleSource at given index
GetParticles()
proto native int GetParticles (out array< ParticleSource > outArray, int startIndex, int count)
Manually get a portion of the particles in the pool.
Parameters
particles array<ParticleSource> The resulting particles
startIndex int Starting index
count int Amount of particles to get
Returns
int Amount of particles in outArray
Referenced by GetParticlesEx().
GetParticlesEx()
array< ParticleSource > GetParticlesEx (int startIndex, int count)
Manually get a portion of the particles in the pool.
Parameters
startIndex int Starting index
count int Amount of particles to get
Returns
array<ParticleSource> The resulting particles
Definition at line 398 of file particlemanager.c.
    {
        array<ParticleSource> outArr = new array<ParticleSource>;
        GetParticles(outArr, startIndex, count);
        return outArr;
    }
References GetParticles().
GetPlayingCount()
proto native int GetPlayingCount ()
Gets the amount of playing particles.
Returns
int Amount of currently playing particles
GetPoolSize()
proto native int GetPoolSize ()
Gets the fixed maximum size of the pool.
Returns
int The fixed maximum size of the pool
GetScriptEvents()
private proto Managed GetScriptEvents ()
Get the events.
Returns
Managed If there is any events set, this will return them
Referenced by GetEvents().
GetStaticActiveCount()
proto static native int GetStaticActiveCount () static
Gets the amount of ParticleManager that are currently existing.
Returns
int Amount of ParticleManager that are currently existing
GetStaticCount()
proto static native int GetStaticCount () static
Gets the amount of ParticleManager that have been created since the start of the program.
Returns
int Amount of ParticleManager that have been created since the start of the program
GetVirtualCount()
proto native int GetVirtualCount ()
Gets the amount of virtual particles.
Returns
int Amount of virtual particles currently waiting to be turned into real particles
IsFinishedAllocating()
proto native bool IsFinishedAllocating ()
Checks if the ParticleManager has allocated all slots in the pool.
Returns
bool True when the number of allocated particles is the same as the pool size
OnAllocation()
void OnAllocation (array< ParticleSource > allocatedParticles)
Definition at line 537 of file particlemanager.c.
    {
        GetEvents().Event_OnAllocation.Invoke(this, allocatedParticles);
    }
References GetEvents().
OnAllocationEnd()
void OnAllocationEnd ()
Definition at line 542 of file particlemanager.c.
    {
        GetEvents().Event_OnAllocationEnd.Invoke(this);
    }
References GetEvents().
ParticleManager()
void ParticleManager (ParticleManagerSettings settings)
Constructor (ctor)
Parameters
settings ParticleManagerSettings Settings for the ParticleManager
Definition at line 84 of file particlemanager.c.
    {
    }
Referenced by Hit_MeatBones::BloodSplatGround(), PMTPlayback::CheckOnePlaying(), CheckTestEvents(), PMTF::CreatePMFixedBlocking(), ItemBase::DoMeasurement(), DynamicArea_Flare::DynamicArea_Flare(), BuildingSuper::EEInit(), EffBulletImpactBase::Event_OnStarted(), ExplosionEffects(), GetInstance(), EntityLightSource::HandleDancingShadows(), HandleVisualEffects(), WeaponParticlesBase::OnActivate(), FlareSimulation::OnActivation(), Grenade_ChemGas::OnDamageDestroyed(), OnEvent(), FireworksLauncherClientEvent::OnExplode(), OnExplode(), FuelStation::OnExplosionEffects(), OnExplosionEffects(), SmokeSimulation::OnFire(), FireworksLauncherClientEvent::OnFired(), FireworksLauncher::OnFuseIgnitedClient(), OnRPC(), Ammo_40mm_Smoke_ColorBase::OnVariablesSynchronized(), ParticleCookingStart(), Inventory_Base::ParticleCookingStart(), ItemBase::ParticleTest(), EffectArea::PlaceParticles(), AmmoEffects::PlayAmmoParticle(), DestructionEffectBase::PlayParticle(), PlayParticle(), PlaySmokeParticle(), PlayVFX(), PMTF::PrintActiveStats(), ManBase::SetContaminatedEffectEx(), ItemBase::Spark(), ManBase::SpawnBreathVaporEffect(), ActionDigInStash::SpawnParticleShovelRaise(), SpawnParticleShovelRaise(), EffectParticle::Start(), TestCleanup(), TestCreationSmallBlocking(), TestEvents(), PMTPlayback::TestOnePlaying(), TestOwnership(), Roadflare::UpdateActiveParticles(), BroomBase::UpdateParticle(), FlammableBase::UpdateParticle(), CrashBase::Wreck_Mi8_Crashed(), CrashBase::Wreck_SantasSleigh(), CrashBase::Wreck_UH1Y(), and CGame::~CGame().
ParticleManagerSettings()
class ParticleManagerConstants ParticleManagerSettings (int poolSize, int flags = ParticleManagerSettingsFlags.NONE)
Settings given to ParticleManager on creation (in ctor)
Constructor (ctor)
Parameters
poolSize int Size of pool (amount of created and reserved particles)
flags int ParticleManagerSettingsFlags
Definition at line 1 of file particlemanager.c.
    {
    }
Referenced by PMTF::CreatePMFixedBlocking(), GetInstance(), and TestEvents().
Play() [1/2]
ParticleSource Play (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0")
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 226 of file particlemanager.c.
    {
        return PlayOnObject( particle_id, parent_obj, local_pos, local_ori);
    }
References particle_id, and PlayOnObject().
Play() [2/2]
ParticleSource Play (int particle_id, vector global_pos)
Legacy function for backwards compatibility with 1.01 and below.
Definition at line 251 of file particlemanager.c.
    {
        return PlayInWorld( particle_id, global_pos);
    }
References particle_id, and PlayInWorld().
PlayInWorld()
ParticleSource PlayInWorld (int particle_id, vector global_pos)
Creates a particle emitter on the given position and activates it.
Parameters
particle_id int Particle ID registered in ParticleList
global_pos Vector Position where the particel will be created
Returns
ParticleSource Created particle instance
Definition at line 237 of file particlemanager.c.
    {
        return PlayInWorldEx(particle_id, null, global_pos);
    }
References particle_id, and PlayInWorldEx().
Referenced by Play().
PlayInWorldEx()
ParticleSource PlayInWorldEx (int particle_id, Object parent_obj, vector global_pos, vector global_ori = "0 0 0", bool force_world_rotation = false)
Definition at line 242 of file particlemanager.c.
    {
        return CreateParticle(particle_id, global_pos, true, parent_obj, global_ori, force_world_rotation);
    }
References CreateParticle(), and particle_id.
Referenced by PlayInWorld().
PlayOnObject()
ParticleSource PlayOnObject (int particle_id, Object parent_obj, vector local_pos = "0 0 0", vector local_ori = "0 0 0", bool force_world_rotation = false)
Creates a particle emitter, attaches it on the given object and activates it.
Parameters
particle_id int Particle ID registered in ParticleList
parent_obj Object Instance on which this particle will be attached
local_pos vector Attachment position local to the parent (Optional)
local_ori vector Orientation local to the parent (Pitch, Yaw, Roll in degrees) (Optional)
force_world_rotation bool Forces particle's orientation to rotate relative to the world and not with the object (Optional)
Returns
ParticleSource Created particle instance
Definition at line 218 of file particlemanager.c.
    {
        return CreateParticle(particle_id, local_pos, true, parent_obj, local_ori, force_world_rotation);
    }
References CreateParticle(), and particle_id.
Referenced by Play().
PlayParticleById()
ParticleSource PlayParticleById (int id, array< vector > position)
QoL function for when only one particle is needed using script ParticleList, strongly recommend to read comments for PlayParticles as well.
Parameters
id int ID of particle registered in ParticleList
positions array<vector> Positions of particles
Returns
ParticleSource The resulting particle
Definition at line 365 of file particlemanager.c.
    {
        array<ParticleSource> tempArr = new array<ParticleSource>;
        PlayParticles(tempArr, ParticleList.GetParticleFullPath(id), position, 1);
        if (tempArr.Count() > 0)
            return tempArr[0];
        else
            return null;
    }
References ParticleList::GetParticleFullPath(), and PlayParticles().
PlayParticles()
proto native int PlayParticles (out array< ParticleSource > particles, string path, notnull array< vector > positions, int count = 1)
QoL function for when wanting to play a particle at a position right away.
Parameters
particles array<ParticleSource> The resulting particles if an array is given
path string Path of particle effect
positions array<vector> Positions of particles
count int Amount of particles to create at this position
Returns
int Amount of particles created in this frame, if the ParticleManager is still allocating while this is called and virtual particles are enabled, the overflow particles will be virtual instead and not given in the out array
Referenced by PlayParticleById(), and PlayParticlesById().
PlayParticlesById()
array< ParticleSource > PlayParticlesById (int id, array< vector > positions, int count)
QoL function using script ParticleList, strongly recommend to read comments for PlayParticles as well.
Parameters
id int ID of particle registered in ParticleList
positions array<vector> Positions of particles
count int Amount of particles to create at this position
Returns
array<ParticleSource> The resulting particles - Read particles param of PlayParticles
Definition at line 352 of file particlemanager.c.
    {
        array<ParticleSource> outArr = new array<ParticleSource>;
        PlayParticles(outArr, ParticleList.GetParticleFullPath(id), positions, count);
        return outArr;
    }
References ParticleList::GetParticleFullPath(), and PlayParticles().
SetName()
proto native void SetName (string name)
Set a name for the ParticleManager to identify it more easily.
Parameters
name string Name for ParticleManager
SetScriptEvents()
private proto void SetScriptEvents (Managed events)
Set the events.
Parameters
events Managed The events to set
~ParticleManager()
void ~ParticleManager ()
dtor
Definition at line 89 of file particlemanager.c.
    {
    }
~ParticleManagerSettings()
void ~ParticleManagerSettings ()
dtor
Definition at line 40 of file particlemanager.c.
    {
    }
Variable Documentation
FLAGS
const int FLAGS = ParticleManagerSettingsFlags.NONE static
Definition at line 41 of file particlemanager.c.
g_ParticleManager
class ParticleManagerEvents g_ParticleManager
Has a fixed pool of precreated and reserved particles.
Static ParticleManager
Referenced by CleanupInstance(), and GetInstance().
POOL_SIZE
const int POOL_SIZE = 10000 static
Definition at line 40 of file particlemanager.c.