DayzKode: P:/scripts/3_game/DayZ/particles/particlebase.c File Reference
particlebase.c File Reference
Classes
class ParticleEvents
Invokers for ParticleBase events, called from events.
Functions
override bool IsParticle ()
Have script recognize this as a Particle without casting.
void ParticleBase ()
ctor
Playback
Methods regarding playing/stopping of particle
ParticleEvents GetEvents ()
Get the events.
bool IsParticlePlaying ()
Ask if the particle is still playing.
void PlayParticle (int particle_id=-1)
Method to tell the particle to start playing.
bool PlayParticleEx (int particle_id=-1, int flags=0)
Method to tell the particle to start playing.
bool ResetParticle ()
Method to tell the particle to reset.
bool RestartParticle ()
Method to tell the particle to restart (reset + play)
bool StopParticle (int flags=0)
Method to tell the particle to stop playing.
Events
ParticleBase events For ParticleSource, these are handed on C++ side For more information, read ParticleEvents
protected void OnParticleEnd ()
Event when the particle ends.
protected void OnParticleParented (IEntity parent)
Event when the particle receives a parent.
protected void OnParticleReset ()
Event when the particle is restarted.
protected void OnParticleStart ()
Event when the particle starts.
protected void OnParticleStop ()
Event when the particle stops.
protected void OnParticleUnParented (IEntity parent)
Event when the particle is orphaned.
Variables
protected ref ParticleEvents m_EventInvokers
Event invokers.
class ParticleEvents m_IsPlaying
Engine base class with internal functionality.
Function Documentation
GetEvents()
ParticleEvents GetEvents ()
Get the events.
Returns
ParticleEvents If there is any events set, this will return them so that additional functionality can be bound to them
Definition at line 162 of file particlebase.c.
    {
        return m_EventInvokers;
    }
References m_EventInvokers.
Referenced by OnAllocation(), OnAllocationEnd(), OnParticleEnd(), OnParticleParented(), OnParticleReset(), OnParticleStart(), OnParticleStop(), and OnParticleUnParented().
IsParticle()
override bool IsParticle ()
Have script recognize this as a Particle without casting.
Definition at line 79 of file particlebase.c.
    {
        return true;
    }
IsParticlePlaying()
bool IsParticlePlaying ()
Ask if the particle is still playing.
Returns
bool Whether the particle is playing
Definition at line 148 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
OnParticleEnd()
protected void OnParticleEnd ()
Event when the particle ends.
Note
Looping particles will never end
Definition at line 206 of file particlebase.c.
    {
        GetEvents().Event_OnParticleEnd.Invoke(this);
    }
References ParticleEvents::Event_OnParticleEnd, GetEvents(), and ScriptInvoker::Invoke().
Referenced by Particle::OnCheckAutoDelete().
OnParticleParented()
protected void OnParticleParented (IEntity parent)
Event when the particle receives a parent.
Definition at line 214 of file particlebase.c.
    {
        GetEvents().Event_OnParticleParented.Invoke(this);
    }
References ParticleEvents::Event_OnParticleParented, GetEvents(), and ScriptInvoker::Invoke().
OnParticleReset()
protected void OnParticleReset ()
Event when the particle is restarted.
Definition at line 197 of file particlebase.c.
    {
        GetEvents().Event_OnParticleReset.Invoke(this);
    }
References ParticleEvents::Event_OnParticleReset, GetEvents(), and ScriptInvoker::Invoke().
OnParticleStart()
protected void OnParticleStart ()
Event when the particle starts.
Definition at line 179 of file particlebase.c.
    {
        m_IsPlaying = true;
        GetEvents().Event_OnParticleStart.Invoke(this);
    }
References ParticleEvents::Event_OnParticleStart, GetEvents(), ScriptInvoker::Invoke(), and m_IsPlaying.
Referenced by Particle::PlayParticleEx().
OnParticleStop()
protected void OnParticleStop ()
Event when the particle stops.
Definition at line 188 of file particlebase.c.
    {
        m_IsPlaying = false;
        GetEvents().Event_OnParticleStop.Invoke(this);
    }
References ParticleEvents::Event_OnParticleStop, GetEvents(), ScriptInvoker::Invoke(), and m_IsPlaying.
Referenced by Particle::OnCheckAutoDelete(), and Particle::StopParticle().
OnParticleUnParented()
protected void OnParticleUnParented (IEntity parent)
Event when the particle is orphaned.
Definition at line 222 of file particlebase.c.
    {
        GetEvents().Event_OnParticleUnParented.Invoke(this);
    }
References ParticleEvents::Event_OnParticleUnParented, GetEvents(), and ScriptInvoker::Invoke().
ParticleBase()
void ParticleBase ()
ctor
Definition at line 71 of file particlebase.c.
    {
        m_EventInvokers = new ParticleEvents();
    }
References m_EventInvokers.
PlayParticle()
void PlayParticle (int particle_id = -1)
Method to tell the particle to start playing.
Parameters
particle_id int Particle ID registered in ParticleList to start playing
Returns
bool Whether the particle successfully started
Definition at line 96 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
    }
References ErrorEx.
Referenced by ParticleFireEndStart(), ParticleFireStartStart(), ParticleFireWindyNoIgniteStart(), ParticleNormalFireStart(), ParticleNormalSmokeStart(), FireplaceBase::ParticleNormalSmokeStart(), ParticleSmallFireStart(), ParticleSmallSmokeStart(), FireplaceBase::ParticleSmallSmokeStart(), ParticleSteamEndStart(), ParticleSteamExtinguishingStart(), and ParticleWetNoIgniteStart().
PlayParticleEx()
bool PlayParticleEx (int particle_id = -1, int flags = 0)
Method to tell the particle to start playing.
Parameters
particle_id int Particle ID registered in ParticleList to start playing
flags int Flags to pass to the playing
Returns
bool Whether the particle successfully started
Definition at line 107 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
ResetParticle()
bool ResetParticle ()
Method to tell the particle to reset.
Returns
bool Whether the particle successfully reset
Definition at line 128 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
RestartParticle()
bool RestartParticle ()
Method to tell the particle to restart (reset + play)
Returns
bool Whether the particle successfully restarted
Definition at line 138 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
StopParticle()
bool StopParticle (int flags = 0)
Method to tell the particle to stop playing.
Parameters
flags int Flags to pass to the stopping
Returns
bool Whether the particle successfully stopped
Definition at line 118 of file particlebase.c.
    {
        ErrorEx("Not implemented.", ErrorExSeverity.WARNING);
        return false;
    }
References ErrorEx.
Referenced by ParticleFireEndStop(), ParticleFireStartStop(), ParticleNormalFireStop(), ParticleNormalSmokeStop(), ParticleSmallFireStop(), ParticleSmallSmokeStop(), ParticleSteamEndStop(), ParticleSteamExtinguishingStop(), ParticleWetNoIgniteStop(), and StopAllParticlesAndSounds().
Variable Documentation
m_EventInvokers
protected ref ParticleEvents m_EventInvokers
Event invokers.
Definition at line 66 of file particlebase.c.
Referenced by GetEvents(), and ParticleBase().
m_IsPlaying
class ParticleEvents m_IsPlaying
Engine base class with internal functionality.
Note
Is NOT intended for direct creation As this does not have an actual particle Use either Particle or ParticleSource Whether the particle is currently playing