DayzKode: P:/scripts/4_world/DayZ/classes/playerlightmanager.c File Reference
playerlightmanager.c File Reference
Classes
class ActionTargetLighSource
Functions
void AddLightSource (Object object)
ref array< ref ActionTarget > GetLightSourceList ()
int GetSelectedLightSourceIdx ()
ref ActionTarget GetSelectedLightSourceTarget ()
void PlayerLightManager (PlayerBase player)
void RemoveLightSource (Object object)
void SelectLightSourceTarget (ActionTarget target)
void SetSelectedLightSourceIdx (int value)
void UpdateLightSourceList ()
Variables
ref ActionTargetLighSource m_LightItemTarget
PlayerBase m_Player
ActionTargetLighSource m_SelectedLightSource
ref array< ref ActionTarget > m_ValidLightItems
Function Documentation
AddLightSource()
void AddLightSource (Object object)
Definition at line 22 of file playerlightmanager.c.
    {
        m_LightItemTarget = new ActionTargetLighSource(object, null, -1, vector.Zero, -1);
        UpdateLightSourceList();
    }
References m_LightItemTarget, UpdateLightSourceList(), and vector::Zero.
GetLightSourceList()
ref array< ref ActionTarget > GetLightSourceList ()
Definition at line 50 of file playerlightmanager.c.
    {
        return m_ValidLightItems;
    }
References m_ValidLightItems.
GetSelectedLightSourceIdx()
int GetSelectedLightSourceIdx ()
Definition at line 60 of file playerlightmanager.c.
    {
        return m_SelectedLightSource;
    }
References m_SelectedLightSource.
GetSelectedLightSourceTarget()
ref ActionTarget GetSelectedLightSourceTarget ()
Definition at line 71 of file playerlightmanager.c.
    {
        return m_ValidLightItems.Get(m_SelectedLightSource);
    }
References m_SelectedLightSource, and m_ValidLightItems.
PlayerLightManager()
void PlayerLightManager (PlayerBase player)
Definition at line 14 of file playerlightmanager.c.
    {
        m_LightItemTarget = null;
        m_ValidLightItems = new array<ref ActionTarget>;
        m_Player = player;
    }
References m_LightItemTarget, m_Player, and m_ValidLightItems.
RemoveLightSource()
void RemoveLightSource (Object object)
Definition at line 28 of file playerlightmanager.c.
    {
        m_LightItemTarget = new ActionTargetLighSource(object, null, -1, vector.Zero, -1);
        m_LightItemTarget.m_Remove = true;
        UpdateLightSourceList();
    }
References m_LightItemTarget, ActionTargetLighSource::m_Remove, UpdateLightSourceList(), and vector::Zero.
SelectLightSourceTarget()
void SelectLightSourceTarget (ActionTarget target)
Definition at line 65 of file playerlightmanager.c.
    {
        int idx = m_ValidLightItems.Find(target);
        SetSelectedLightSourceIdx(idx);
    }
References m_ValidLightItems, and SetSelectedLightSourceIdx().
SetSelectedLightSourceIdx()
void SetSelectedLightSourceIdx (int value)
Definition at line 55 of file playerlightmanager.c.
    {
        m_SelectedLightSource = value;
    }
References m_SelectedLightSource.
Referenced by SelectLightSourceTarget().
UpdateLightSourceList()
void UpdateLightSourceList ()
Definition at line 35 of file playerlightmanager.c.
    {
        if ( m_LightItemTarget )
        {
            if ( !m_LightItemTarget.m_Remove )
            {
                m_ValidLightItems.Insert(m_LightItemTarget);
            }
            else
            {
                m_ValidLightItems.RemoveItem(m_LightItemTarget);
            }
        }
    }
References m_LightItemTarget, ActionTargetLighSource::m_Remove, and m_ValidLightItems.
Referenced by AddLightSource(), and RemoveLightSource().
Variable Documentation
m_LightItemTarget
ref ActionTargetLighSource m_LightItemTarget
Definition at line 10 of file playerlightmanager.c.
Referenced by AddLightSource(), PlayerLightManager(), RemoveLightSource(), and UpdateLightSourceList().
m_Player
PlayerBase m_Player
Definition at line 12 of file playerlightmanager.c.
m_SelectedLightSource
ActionTargetLighSource m_SelectedLightSource
Referenced by GetSelectedLightSourceIdx(), GetSelectedLightSourceTarget(), and SetSelectedLightSourceIdx().
m_ValidLightItems
ref array<ref ActionTarget> m_ValidLightItems
Definition at line 11 of file playerlightmanager.c.
Referenced by GetLightSourceList(), GetSelectedLightSourceTarget(), PlayerLightManager(), SelectLightSourceTarget(), and UpdateLightSourceList().