DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/playersoundevents/playersoundeventhandler.c File Reference
playersoundeventhandler.c File Reference
Enumerations
enum EPlayerSoundEventID {
HOLD_BREATH = 1 , EXHAUSTED_BREATH , RELEASE_BREATH , STAMINA_DOWN_LIGHT ,
STAMINA_DOWN_HEAVY , STAMINA_UP_LIGHT , STAMINA_UP_HEAVY , STAMINA_UP_END ,
STAMINA_NORMAL_DUMMY , TAKING_DMG_LIGHT , TAKING_DMG_HEAVY , SYMPTOM_COUGH ,
SYMPTOM_LAUGHTER , SYMPTOM_SNEEZE , JUMP , MELEE_ATTACK_LIGHT ,
INJURED_LIGHT , INJURED_MEDIUM , INJURED_HIGH , FREEZING ,
HOT , SYMPTOM_FATIGUE , STAMINA_LOW_FILTER_UPPER , STAMINA_LOW_FILTER_MID ,
STAMINA_LOW_FILTER_LOWER , DROWNING_BREATH , DROWNING_PAIN , ENUM_COUNT
}
Functions
int ConvertAnimIDtoEventID (int anim_id)
override int GetCurrentStateEventID ()
override int GetCurrentStateEventType ()
static override EPlayerSoundEventType GetSoundEventType (int id)
void OnTick (float delta_time)
void PlayerSoundEventHandler (PlayerBase player)
override bool PlayRequest (EPlayerSoundEventID id, bool sent_from_server=false)
override bool PlayRequestEx (EPlayerSoundEventID id, bool sent_from_server=false, int param=0)
void RegisterState (PlayerSoundEventBase state)
Variables
static ref PlayerSoundEventBase m_AvailableStates [SOUND_EVENTS_MAX]
static ref map< int, int > m_ConfigIDToScriptIDmapping = new ref map<int,int>
ref PlayerSoundEventBase m_CurrentState
enum EPlayerSoundEventID m_Player
ref Timer m_UpdateTimer
const int SOUND_EVENTS_MAX = EPlayerSoundEventID.ENUM_COUNT
Enumeration Type Documentation
EPlayerSoundEventID
enum EPlayerSoundEventID
Enumerator
HOLD_BREATH
EXHAUSTED_BREATH
RELEASE_BREATH
STAMINA_DOWN_LIGHT
STAMINA_DOWN_HEAVY
STAMINA_UP_LIGHT
STAMINA_UP_HEAVY
STAMINA_UP_END
STAMINA_NORMAL_DUMMY
TAKING_DMG_LIGHT
TAKING_DMG_HEAVY
SYMPTOM_COUGH
SYMPTOM_LAUGHTER
SYMPTOM_SNEEZE
JUMP
MELEE_ATTACK_LIGHT
INJURED_LIGHT
INJURED_MEDIUM
INJURED_HIGH
FREEZING
HOT
SYMPTOM_FATIGUE
STAMINA_LOW_FILTER_UPPER
STAMINA_LOW_FILTER_MID
STAMINA_LOW_FILTER_LOWER
DROWNING_BREATH
DROWNING_PAIN
ENUM_COUNT
Definition at line 1 of file playersoundeventhandler.c.
{
    HOLD_BREATH = 1,
    EXHAUSTED_BREATH,
    RELEASE_BREATH,
    STAMINA_DOWN_LIGHT,
    STAMINA_DOWN_HEAVY,
    STAMINA_UP_LIGHT,
    STAMINA_UP_HEAVY,
    STAMINA_UP_END,
    STAMINA_NORMAL_DUMMY,
    TAKING_DMG_LIGHT,
    TAKING_DMG_HEAVY,
    SYMPTOM_COUGH,
    SYMPTOM_LAUGHTER,
    SYMPTOM_SNEEZE,
    JUMP,
    MELEE_ATTACK_LIGHT,
    MELEE_ATTACK_HEAVY
    INJURED_LIGHT,
    INJURED_MEDIUM,
    INJURED_HIGH,
    FREEZING,
    HOT,
    SYMPTOM_FATIGUE,
    STAMINA_LOW_FILTER_UPPER,
    STAMINA_LOW_FILTER_MID,
    STAMINA_LOW_FILTER_LOWER,
    DROWNING_BREATH,
    DROWNING_PAIN,
    //--------------
    // Count bellow, put enums above
    //--------------
    ENUM_COUNT,
}
Function Documentation
ConvertAnimIDtoEventID()
int ConvertAnimIDtoEventID (int anim_id)
Definition at line 107 of file playersoundeventhandler.c.
    {
        return m_ConfigIDToScriptIDmapping.Get(anim_id);
    }
References m_ConfigIDToScriptIDmapping.
GetCurrentStateEventID()
override int GetCurrentStateEventID ()
Definition at line 117 of file playersoundeventhandler.c.
    {
        if(m_CurrentState)
        {
            return m_CurrentState.GetSoundEventID();
        }
        return -1;
    }
References m_CurrentState.
GetCurrentStateEventType()
override int GetCurrentStateEventType ()
Definition at line 126 of file playersoundeventhandler.c.
    {
        if(m_CurrentState)
        {
            return m_CurrentState.GetSoundEventType();
        }
        return -1;
    }
References m_CurrentState.
GetSoundEventType()
static override EPlayerSoundEventType GetSoundEventType (int id) static
Definition at line 112 of file playersoundeventhandler.c.
    {
        return m_AvailableStates[id].GetSoundEventType();
    }
References m_AvailableStates.
OnTick()
void OnTick (float delta_time)
Definition at line 96 of file playersoundeventhandler.c.
    {
        if (m_CurrentState)
        {
            if( m_CurrentState.IsFinished())
                m_CurrentState = null;
            else
                m_CurrentState.OnTick(delta_time);
        }
    }
References m_CurrentState.
PlayerSoundEventHandler()
void PlayerSoundEventHandler (PlayerBase player)
Definition at line 47 of file playersoundeventhandler.c.
    {
        m_Player = player;
        if(!m_UpdateTimer && !m_Player.IsControlledPlayer())
        {
            m_UpdateTimer = new Timer();
            m_UpdateTimer.Run(1, this, "OnTick", null, true);//ticking for remotes, the controlled player is ticking on command handler at higher intervals
        }
        RegisterState(new HoldBreathSoundEvent());
        RegisterState(new ExhaustedBreathSoundEvent());
        RegisterState(new FatigueSoundEvent());
        RegisterState(new ReleaseBreathSoundEvent());
        RegisterState(new StaminaDownLight());
        RegisterState(new StaminaDownHeavy());
        RegisterState(new StaminaUpLight());
        RegisterState(new StaminaUpHeavy());
        RegisterState(new StaminaUpEnd());
        RegisterState(new DamageLightSoundEvent());
        RegisterState(new DamageHeavySoundEvent());
        RegisterState(new SneezeSoundEvent());
        RegisterState(new LaugherSoundEvent());
        RegisterState(new CoughSoundEvent());
        RegisterState(new JumpSoundEvent());
        RegisterState(new MeleeAttackLightEvent());
        RegisterState(new MeleeAttackHeavyEvent());
        RegisterState(new StaminaNormalDummy());
        RegisterState(new InjuryLightSoundEvent());
        RegisterState(new InjuryMediumSoundEvent());
        RegisterState(new InjuryHeavySoundEvent());
        RegisterState(new FreezingSoundEvent());
        RegisterState(new HotSoundEvent());
        RegisterState(new StaminaLowFilterUpper());
        RegisterState(new StaminaLowFilterMid());
        RegisterState(new StaminaLowFilterLower());
        RegisterState(new DrowningEvent1());
        RegisterState(new DrowningEvent2());
    }
References CoughSoundEvent(), DamageLightSoundEvent(), DrowningEvent1(), ExhaustedBreathSoundEvent(), FreezingSoundEvent(), HoldBreathSoundEvent(), InjuryHeavySoundEvent(), InjuryLightSoundEvent(), InjuryMediumSoundEvent(), JumpSoundEvent(), LaugherSoundEvent(), m_Player, m_UpdateTimer, MeleeAttackLightEvent(), RegisterState(), ReleaseBreathSoundEvent(), SneezeSoundEvent(), StaminaDownHeavy(), StaminaDownLight(), StaminaLowFilterMid(), StaminaLowFilterUpper(), StaminaNormalDummy(), StaminaUpEnd(), StaminaUpHeavy(), and StaminaUpLight().
Referenced by ManBase::OnPlayerLoaded().
PlayRequest()
override bool PlayRequest (EPlayerSoundEventID id, bool sent_from_server = false)
Definition at line 186 of file playersoundeventhandler.c.
    {
        return PlayRequestEx(id, sent_from_server);
    }
References PlayRequestEx().
PlayRequestEx()
override bool PlayRequestEx (EPlayerSoundEventID id, bool sent_from_server = false, int param = 0)
Definition at line 135 of file playersoundeventhandler.c.
    {
        if (id < 0 || id > (SOUND_EVENTS_MAX - 1))
        {
            Error("EPlayerSoundEventID out of bounds");
        }
        PlayerSoundEventBase requested_state = m_AvailableStates[id];
        if ( sent_from_server && (param & EPlayerSoundEventParam.SKIP_CONTROLLED_PLAYER) && m_Player.GetInstanceType() == DayZPlayerInstanceType.INSTANCETYPE_CLIENT )
        {
            return false;
        }
        if ( !requested_state.CanPlay(m_Player) )
        {
            return false;
        }
        if (m_CurrentState)
        {
            if (param & EPlayerSoundEventParam.HIGHEST_PRIORITY)
            {
                m_CurrentState.Stop();
            }
            else
            {
                int current_type =  m_CurrentState.GetSoundEventType();
                //int requested_type = requested_state.GetSoundEventType();
                if ( (requested_state.GetPriorityOverTypes() & current_type) == 0 )
                {
                    return false;
                }
                if (!requested_state.HasPriorityOverCurrent(m_Player, id, current_type) )
                {
                    return false;
                }
                m_CurrentState.Stop();
            }
        }
        m_CurrentState = PlayerSoundEventBase.Cast(requested_state.ClassName().ToType().Spawn());
        m_CurrentState.InitEx(m_Player, param);
        if (m_CurrentState.Play())
        {
            m_CurrentState.OnPlay(m_Player);
        }
        return true;
    }
References PlayerSoundEventBase::CanPlay(), Error(), PlayerSoundEventBase::HasPriorityOverCurrent(), m_AvailableStates, m_CurrentState, m_Player, and SOUND_EVENTS_MAX.
Referenced by PlayRequest().
RegisterState()
void RegisterState (PlayerSoundEventBase state)
Definition at line 88 of file playersoundeventhandler.c.
    {
        int index = state.GetSoundEventID();
        m_AvailableStates[index] = state;
        m_ConfigIDToScriptIDmapping.Insert(state.GetSoundVoiceAnimEventClassID(),index);
    }
References m_AvailableStates, and m_ConfigIDToScriptIDmapping.
Referenced by PlayerSoundEventHandler().
Variable Documentation
m_AvailableStates
ref PlayerSoundEventBase m_AvailableStates[SOUND_EVENTS_MAX] static
Definition at line 41 of file playersoundeventhandler.c.
m_ConfigIDToScriptIDmapping
ref map<int,int> m_ConfigIDToScriptIDmapping = new ref map<int,int> static
Definition at line 42 of file playersoundeventhandler.c.
Referenced by ConvertAnimIDtoEventID(), and RegisterState().
m_CurrentState
ref PlayerSoundEventBase m_CurrentState
Definition at line 43 of file playersoundeventhandler.c.
m_Player
enum EPlayerSoundEventID m_Player
m_UpdateTimer
ref Timer m_UpdateTimer
Definition at line 44 of file playersoundeventhandler.c.
SOUND_EVENTS_MAX
const int SOUND_EVENTS_MAX = EPlayerSoundEventID.ENUM_COUNT
Definition at line 40 of file playersoundeventhandler.c.