DayzKode: P:/scripts/4_world/DayZ/classes/soundevents/playersoundevents/playersoundeventbase.c File Reference
playersoundeventbase.c File Reference
Enumerations
enum EPlayerSoundEventType {
GENERAL = 0x00000001 , MELEE = 0x00000002 , STAMINA = 0x00000004 , DAMAGE = 0x00000008 ,
DUMMY = 0x00000010 , INJURY = 0x00000020 , DROWNING = 0x00000040
}
Functions
bool CanPlay (PlayerBase player)
EPlayerSoundEventType GetPriorityOverTypes ()
int GetSoundVoiceAnimEventClassID ()
bool HasHoldBreathException ()
bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
void Init (PlayerBase player)
void InitEx (PlayerBase player, int param)
bool IsDummy ()
bool IsDummyFinished ()
bool IsFinished ()
void OnEnd ()
void OnInterupt ()
override void OnPlay (PlayerBase player)
void OnTick (float delta_time)
override bool Play ()
void PlayerSoundEventBase ()
void SendEvent (float time)
void ~PlayerSoundEventBase ()
Variables
enum EPlayerSoundEventType ENUM_COUNT = 0x00000002
enum EPlayerSoundEventType HIGHEST_PRIORITY = 0x00000002
float m_DummySoundLength
float m_DummyStartTime
EPlayerSoundEventType m_HasPriorityOverTypes
ref HumanMovementState m_Hms = new HumanMovementState()
bool m_IsDummyType
enum EPlayerSoundEventType m_Player = 0x00000002
float m_PlayTime
bool m_ProcessPlaybackEvent
enum EPlayerSoundEventType SKIP_CONTROLLED_PLAYER = 0x00000001
Enumeration Type Documentation
EPlayerSoundEventType
enum EPlayerSoundEventType
Enumerator
GENERAL
MELEE
STAMINA
DAMAGE
DUMMY
INJURY
DROWNING
Definition at line 1 of file playersoundeventbase.c.
{
    GENERAL     = 0x00000001,
    MELEE       = 0x00000002,
    STAMINA     = 0x00000004,
    DAMAGE      = 0x00000008,
    DUMMY       = 0x00000010,
    INJURY      = 0x00000020,
    DROWNING    = 0x00000040,
    //HEAT_COMFORT  = 0x00000080,
}
Function Documentation
CanPlay()
bool CanPlay (PlayerBase player)
Definition at line 115 of file playersoundeventbase.c.
    {
        player.GetMovementState(m_Hms);
        if (player.IsHoldingBreath() && !HasHoldBreathException())
        {
            return false;
        }
        if (player.m_IsDrowning || (player.IsSwimming() && m_Hms.m_iMovement != 0))
        {
            return false;
        }
        return true;
    }
References PlayerSoundEventBase::HasHoldBreathException(), m_Hms, and HumanMovementState::m_iMovement.
GetPriorityOverTypes()
EPlayerSoundEventType GetPriorityOverTypes ()
Definition at line 47 of file playersoundeventbase.c.
    {
        return m_HasPriorityOverTypes;
    }
References m_HasPriorityOverTypes.
GetSoundVoiceAnimEventClassID()
int GetSoundVoiceAnimEventClassID ()
Definition at line 69 of file playersoundeventbase.c.
    {
        return m_SoundVoiceAnimEventClassID;
    }
References m_SoundVoiceAnimEventClassID.
HasHoldBreathException()
bool HasHoldBreathException ()
Definition at line 53 of file playersoundeventbase.c.
    {
        return false;
    }
HasPriorityOverCurrent()
bool HasPriorityOverCurrent (PlayerBase player, EPlayerSoundEventID other_state_id, EPlayerSoundEventType type_other)
Definition at line 74 of file playersoundeventbase.c.
    {
        return true;
    }
Init()
void Init (PlayerBase player)
Definition at line 130 of file playersoundeventbase.c.
    {
        InitEx(player,0);
    }
References InitEx().
InitEx()
void InitEx (PlayerBase player, int param)
Definition at line 135 of file playersoundeventbase.c.
    {
        m_Player = player;
        m_Param = param;
        if (param & EPlayerSoundEventParam.HIGHEST_PRIORITY)
        {
            m_HasPriorityOverTypes = -1;
        }
    }
References m_HasPriorityOverTypes, m_Param, and m_Player.
Referenced by Init().
IsDummy()
bool IsDummy ()
Definition at line 42 of file playersoundeventbase.c.
    {
        return m_IsDummyType;
    }
References m_IsDummyType.
Referenced by IsFinished(), and Play().
IsDummyFinished()
bool IsDummyFinished ()
Definition at line 91 of file playersoundeventbase.c.
    {
        return GetGame().GetTime() > (m_DummyStartTime + m_DummySoundLength);
    }
References GetGame(), CGame::GetTime(), m_DummySoundLength, and m_DummyStartTime.
Referenced by IsFinished().
IsFinished()
bool IsFinished ()
Definition at line 79 of file playersoundeventbase.c.
    {
        if(IsDummy())
        {
            return IsDummyFinished();
        }
        else
        {
            return !IsSoundCallbackExist();
        }
    }
References IsDummy(), IsDummyFinished(), and IsSoundCallbackExist().
OnEnd()
void OnEnd ()
Definition at line 145 of file playersoundeventbase.c.
    {
        if(m_ProcessPlaybackEvent)
            SendEvent(1);
    }
References m_ProcessPlaybackEvent, and SendEvent().
OnInterupt()
void OnInterupt ()
Definition at line 161 of file playersoundeventbase.c.
    {
    }
Referenced by Play().
OnPlay()
override void OnPlay (PlayerBase player)
!! beware of the ifdef above , most likely you want to put your code above it, otherwise it might not get executed !!!
Definition at line 166 of file playersoundeventbase.c.
    {
        super.OnPlay(player);
        //Print("start playing -------------------->" + m_Type);
        player.OnVoiceEvent(this);
        //m_Player.OnVoiceEventDuration(m_SoundSetCallback, 0);
    }
OnTick()
void OnTick (float delta_time)
Definition at line 97 of file playersoundeventbase.c.
    {
        if ( m_SoundSetCallback )
        {
            m_SoundSetCallback.SetPosition(m_Player.GetPosition());
            //---------- Playback event -------------
            if( delta_time > 0 && m_ProcessPlaybackEvent )//delta_time 0 is for remotes
            {
                m_PlayTime += delta_time;
                //this is not 100% precise as the playback position is not obtained from the sound system
                float playback01 = Math.Clamp(m_PlayTime / m_SoundSetCallback.GetLength(),0,1);
                SendEvent(playback01);
            //---------- Playback event -------------
            }
        }
    }
References Math::Clamp(), AbstractWave::GetLength(), m_Player, m_PlayTime, m_ProcessPlaybackEvent, m_SoundSetCallback, SendEvent(), and AbstractWave::SetPosition().
Play()
override bool Play ()
Definition at line 174 of file playersoundeventbase.c.
    {
        if(!super.Play())
            return false;
        if( !IsDummy() )
        {
            m_SoundSetCallback = m_Player.ProcessVoiceEvent("","", m_SoundVoiceAnimEventClassID);
            if(m_SoundSetCallback)
            {
                AbstractWaveEvents events = AbstractWaveEvents.Cast(m_SoundSetCallback.GetUserData());
                events.Event_OnSoundWaveEnded.Insert( OnEnd );
                events.Event_OnSoundWaveStopped.Insert( OnInterupt );
                return true;
            }
            else
                return false;
        }
        else
        {
            m_DummyStartTime = GetGame().GetTime();
            return true;
        }
        return false;
    }
References GetGame(), CGame::GetTime(), AbstractWave::GetUserData(), IsDummy(), m_DummyStartTime, m_Player, m_SoundSetCallback, m_SoundVoiceAnimEventClassID, PlayerSoundEventBase::OnEnd(), and OnInterupt().
PlayerSoundEventBase()
void PlayerSoundEventBase ()
Definition at line 58 of file playersoundeventbase.c.
    {
        m_Type = EPlayerSoundEventType.GENERAL;
    }
References m_Type.
SendEvent()
void SendEvent (float time)
Definition at line 151 of file playersoundeventbase.c.
    {
        if(m_PlayTime < 0 || !m_SoundSetCallback)//negative m_PlayTime value indicates the event has already been sent for playback01 = 1
            return;
        m_Player.OnVoiceEventPlayback(this, m_SoundSetCallback, time);
        if(time >= 1)
            m_PlayTime = -float.MAX;
    }
References m_Player, m_PlayTime, m_SoundSetCallback, and float::MAX.
~PlayerSoundEventBase()
void ~PlayerSoundEventBase ()
Definition at line 63 of file playersoundeventbase.c.
    {
        if(!m_SoundSetCallback)
            OnEnd();
    }
References m_SoundSetCallback, and PlayerSoundEventBase::OnEnd().
Variable Documentation
ENUM_COUNT
enum EPlayerSoundEventType ENUM_COUNT = 0x00000002
HIGHEST_PRIORITY
enum EPlayerSoundEventType HIGHEST_PRIORITY = 0x00000002
m_DummySoundLength
float m_DummySoundLength
Definition at line 33 of file playersoundeventbase.c.
Referenced by IsDummyFinished(), and StaminaSoundEventBase::StaminaNormalDummy().
m_DummyStartTime
float m_DummyStartTime
Definition at line 34 of file playersoundeventbase.c.
Referenced by IsDummyFinished(), and Play().
m_HasPriorityOverTypes
EPlayerSoundEventType m_HasPriorityOverTypes
Definition at line 40 of file playersoundeventbase.c.
Referenced by PlayerSoundEventBase::DamageSoundEvents(), PlayerSoundEventBase::DrowningEvents(), GetPriorityOverTypes(), HasPriorityOverCurrent(), PlayerSoundEventBase::HeatComfortEventsBase(), PlayerSoundEventBase::HoldBreathSoundEventBase(), InitEx(), PlayerSoundEventBase::InjurySoundEvents(), PlayerSoundEventBase::MeleeAttackSoundEvents(), StaminaSoundEventBase::StaminaNormalDummy(), PlayerSoundEventBase::StaminaSoundEventBase(), and PlayerSoundEventBase::SymptomSoundEventBase().
m_Hms
ref HumanMovementState m_Hms = new HumanMovementState()
Definition at line 39 of file playersoundeventbase.c.
Referenced by CanPlay().
m_IsDummyType
bool m_IsDummyType
Definition at line 35 of file playersoundeventbase.c.
Referenced by IsDummy(), and StaminaSoundEventBase::StaminaNormalDummy().
m_Player
enum EPlayerSoundEventType m_Player = 0x00000002
m_PlayTime
float m_PlayTime
Definition at line 37 of file playersoundeventbase.c.
Referenced by OnTick(), and SendEvent().
m_ProcessPlaybackEvent
bool m_ProcessPlaybackEvent
Definition at line 36 of file playersoundeventbase.c.
Referenced by OnEnd(), OnTick(), and StaminaNormalDummy().
SKIP_CONTROLLED_PLAYER
enum EPlayerSoundEventType SKIP_CONTROLLED_PLAYER = 0x00000001