DayzKode: P:/scripts/4_world/DayZ/classes/playerstomach.c File Reference
playerstomach.c File Reference
Classes
class StomachItem
Functions
void AddToStomach (string class_name, float amount, int food_stage=0, int agents=0)
void ClearContents ()
void DigestAgents (int agents, float quantity)
int GetAgentTransferFilter ()
static string GetClassnameFromID (int id)
int GetDebugObject (array< ref Param > object_out)
int GetDigestingType ()
static int GetIDFromClassname (string name)
float GetStomachVolume ()
int GetStorageVersion ()
static bool InitData ()
bool IsDigesting ()
bool OnStoreLoad (ParamsReadContext ctx, int version)
void OnStoreSave (ParamsWriteContext ctx)
void PlayerStomach (PlayerBase player)
void PrintUpdate ()
void ProcessNutrients (float delta_time)
static void RegisterItem (string classname, int id)
void SetAgentTransferFilter (int filter_agents)
void Update (float delta_time)
void ~PlayerStomach ()
Variables
const int ACCEPTABLE_FOODSTAGE_MAX = FoodStageType.COUNT - 1
const int ACCEPTABLE_QUANTITY_MAX = 32768
static int CHECKSUM
const int DIGESTING_ENERGY = 2
class StomachItem DIGESTING_WATER = 1
const float DIGESTION_POINTS = PlayerConstants.DIGESTION_SPEED
const int id_bit_offset = 4
int m_AgentTransferFilter
bool m_Digesting
int m_DigestingType
static ref map< int, string > m_IDsToNames = new map<int, string>
static const bool m_InitData = PlayerStomach.InitData()
static ref map< string, int > m_NamesToIDs = new map<string, int>
PlayerBase m_Player
ref array< ref StomachItem > m_StomachContents = new array<ref StomachItem>
float m_StomachVolume
const int quantity_bit_offset = 16
const int STORAGE_VERSION = 106
Function Documentation
AddToStomach()
void AddToStomach (string class_name, float amount, int food_stage = 0, int agents = 0)
Definition at line 323 of file playerstomach.c.
    {
        if (GetIDFromClassname(class_name) == -1)
            return;
        bool is_liquid;
        NutritionalProfile profile = Liquid.GetNutritionalProfileByName(class_name);
        if(profile)
        {
            is_liquid = true;
        }
        else
        {
            profile = Edible_Base.GetNutritionalProfile(null,class_name, food_stage);
        }
        if(profile)
        {
            // sanity checks start
            if(amount > ACCEPTABLE_QUANTITY_MAX || amount < 0)
            {
                amount = 0;
            }
            if (food_stage < 0 || food_stage > ACCEPTABLE_FOODSTAGE_MAX)
            {
                food_stage = FoodStageType.RAW;
            }
            // sanity checks end
            agents = agents | profile.GetAgents();
            bool found = false;
            for(int i = 0; i < m_StomachContents.Count(); i++)
            {
                StomachItem stomach_item = m_StomachContents.Get(i);
                if(stomach_item.GetClassName() == class_name )
                {
                    if (is_liquid || stomach_item.GetFoodStage() == food_stage)
                    {
                        stomach_item.AddAmount(amount);
                        stomach_item.AddAgents(agents);
                        found = true;
                    }
                }
            }
            if(!found)
            {
                m_StomachContents.Insert(new StomachItem(class_name, amount, profile, food_stage, agents));
            }
        }
    }
References ACCEPTABLE_FOODSTAGE_MAX, ACCEPTABLE_QUANTITY_MAX, StomachItem::AddAgents(), StomachItem::AddAmount(), class_name, NutritionalProfile::GetAgents(), StomachItem::GetClassName(), StomachItem::GetFoodStage(), GetIDFromClassname(), Liquid::GetNutritionalProfileByName(), and m_StomachContents.
Referenced by OnStoreLoad().
ClearContents()
void ClearContents ()
Definition at line 143 of file playerstomach.c.
    {
        m_StomachContents.Clear();
        m_StomachVolume = 0.0;
    }
References m_StomachContents, and m_StomachVolume.
DigestAgents()
void DigestAgents (int agents, float quantity)
Definition at line 287 of file playerstomach.c.
    {
        if(!agents)
            return;
        agents = agents & (~m_AgentTransferFilter);//filter against the agent filter mask
        int highest_bit = Math.Log2(agents) + 1;
        for(int i = 0; i < highest_bit;i++)
        {
            int agent = (1 << i)& agents;
            if( agent )
            {
                m_Player.m_AgentPool.DigestAgent(agent, quantity);
            }
        }
    }
References Math::Log2(), and m_Player.
Referenced by ProcessNutrients().
GetAgentTransferFilter()
int GetAgentTransferFilter ()
Definition at line 154 of file playerstomach.c.
    {
        return m_AgentTransferFilter;
    }
References m_AgentTransferFilter.
GetClassnameFromID()
static string GetClassnameFromID (int id) static
Definition at line 169 of file playerstomach.c.
    {
        return m_IDsToNames.Get(id);
    }
References m_IDsToNames.
Referenced by OnStoreLoad().
GetDebugObject()
int GetDebugObject (array< ref Param > object_out)
Definition at line 442 of file playerstomach.c.
    {
        int count = m_StomachContents.Count();
        for(int i = 0; i < m_StomachContents.Count();i++)
        {
            int id = PlayerStomach.GetIDFromClassname(m_StomachContents.Get(i).m_ClassName);
            int food_stage = m_StomachContents.Get(i).m_FoodStage;
            int agents = m_StomachContents.Get(i).m_Agents;
            float amount = m_StomachContents.Get(i).m_Amount;
            Param4<int,int,int,float> p4 = new Param4<int,int,int,float>(id, food_stage, agents, amount);
            object_out.Insert(p4);
        }
        Param1<float> p1 = new Param1<float>(m_StomachVolume);
        object_out.Insert(p1);
        return count;
    }
References m_StomachContents, m_StomachVolume, and PlayerStomach().
GetDigestingType()
int GetDigestingType ()
Definition at line 237 of file playerstomach.c.
    {
        return m_DigestingType;
    }
References m_DigestingType.
GetIDFromClassname()
static int GetIDFromClassname (string name) static
Definition at line 174 of file playerstomach.c.
    {
        if(!m_NamesToIDs.Contains(name))
            return -1;
        return m_NamesToIDs.Get(name);
    }
References m_NamesToIDs, and name.
Referenced by AddToStomach().
GetStomachVolume()
float GetStomachVolume ()
Definition at line 138 of file playerstomach.c.
    {
        return m_StomachVolume;
    }
References m_StomachVolume.
GetStorageVersion()
int GetStorageVersion ()
Definition at line 227 of file playerstomach.c.
    {
        return STORAGE_VERSION;
    }
References STORAGE_VERSION.
InitData()
static bool InitData () static
Definition at line 181 of file playerstomach.c.
    {
        TStringArray all_paths = new TStringArray;
        all_paths.Insert("CfgVehicles");
        all_paths.Insert("cfgLiquidDefinitions");
        string config_path;
        string child_name;
        int scope;
        string path;
        int consumable_count;
        for(int i = 0; i < all_paths.Count(); i++)
        {
            config_path = all_paths.Get(i);
            int children_count = GetGame().ConfigGetChildrenCount(config_path);
            for(int x = 0; x < children_count; x++)
            {
                GetGame().ConfigGetChildName(config_path, x, child_name);
                path = config_path + " " + child_name;
                scope = GetGame().ConfigGetInt( config_path + " " + child_name + " scope" );
                bool should_check = 1;
                if( config_path == "CfgVehicles" && scope == 0)
                {
                    should_check = 0;
                }
                if ( should_check )
                {
                    bool has_nutrition = GetGame().ConfigIsExisting(path + " Nutrition");
                    bool has_stages = GetGame().ConfigIsExisting(path + " Food");
                    if(has_nutrition || has_stages)
                    {
                        //Print("child name:" + child_name);
                        RegisterItem(child_name, consumable_count);//consumable_count value serves as an unique ID for each item
                        consumable_count++;
                    }
                }
            }
        }
        //Print("consumable_count " + consumable_count);
        return true;
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetInt(), CGame::ConfigIsExisting(), GetGame(), path, RegisterItem(), and x.
IsDigesting()
bool IsDigesting ()
Definition at line 232 of file playerstomach.c.
    {
        return (m_DigestingType != 0);
    }
References m_DigestingType.
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx, int version)
Definition at line 396 of file playerstomach.c.
    {
        int checksum, count;
        if(!ctx.Read(checksum))
        {
            return false;
        }
        if(!ctx.Read(count))
        {
            return false;
        }
        for(int i = 0; i < count; i++)
        {
            int value, agents;
            if(!ctx.Read(value) )
            {
                return false;
            }
            if(!ctx.Read(agents) )
            {
                return false;
            }
            if(checksum == CHECKSUM)//if checksum matches, add to stomach, otherwise throw the data away but go through the de-serialization to keep the stream intact
            {
                int amount = value >> quantity_bit_offset;//isolate amount bits
                int id_mask = Math.Pow(2, quantity_bit_offset) - 1;
                int id = (id_mask & value) >> id_bit_offset;//isolate id bits
                int food_mask = Math.Pow(2, id_bit_offset) - 1;
                int food_stage = value & food_mask;
                //Print("LOAD value:" + value);
                //Print("LOAD id:" + id);
                //Print("LOAD id_bit_offset:" + id_bit_offset);
                //Print("LOAD food_stage:" + food_stage);
                string classname = GetClassnameFromID(id);
                AddToStomach(classname, amount, food_stage, agents);
            }
        }
        //Print("LOAD checksum:" + checksum);
        if(checksum != CHECKSUM)
        {
            Print("Stomach checksum fail");
        }
        return true;
    }
References AddToStomach(), CHECKSUM, GetClassnameFromID(), id_bit_offset, Math::Pow(), Print(), quantity_bit_offset, and Serializer::Read().
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx)
Definition at line 375 of file playerstomach.c.
    {
        ctx.Write( PlayerStomach.CHECKSUM );
        ctx.Write( m_StomachContents.Count() );
        StomachItem stomach_item;
        for(int i = 0; i < m_StomachContents.Count();i++)
        {
            stomach_item = m_StomachContents.Get(i);
            int id = PlayerStomach.GetIDFromClassname(stomach_item.m_ClassName);
            //Print("SAVE id:" + id);
            //Print("SAVE id_bit_offset:" + id_bit_offset);
            int write_result = stomach_item.m_FoodStage | ( id << id_bit_offset );
            write_result = write_result | ((int)stomach_item.m_Amount << quantity_bit_offset);
            ctx.Write( write_result );
            ctx.Write( stomach_item.m_Agents );
            //Print("SAVE write_result:" + write_result);
        }
        //Print("SAVE CHECKSUM:" + PlayerStomach.CHECKSUM);
    }
References id_bit_offset, int, StomachItem::m_Agents, StomachItem::m_Amount, StomachItem::m_ClassName, StomachItem::m_FoodStage, m_StomachContents, PlayerStomach(), quantity_bit_offset, and Serializer::Write().
PlayerStomach()
void PlayerStomach (PlayerBase player)
Definition at line 127 of file playerstomach.c.
    {
        m_Player = player;
    }
References m_Player.
Referenced by GetDebugObject(), ManBase::Init(), OnStoreSave(), HungerMdfr::OnTick(), and HudDebugWinBase::SetContentValues().
PrintUpdate()
void PrintUpdate ()
Definition at line 303 of file playerstomach.c.
    {
        Print("================================");
        for(int i = 0; i < m_StomachContents.Count(); i++)
        {
            string itemname = m_StomachContents.Get(i).m_ClassName;
            float amount = m_StomachContents.Get(i).GetAmount();
            int food_stage = m_StomachContents.Get(i).GetFoodStage();
            int agents = m_StomachContents.Get(i).m_Agents;
            Print(">");
            Print("itemname:" + itemname);
            Print("amount:" + amount);
            Print("food_stage:" + food_stage);
            Print("agents:" + agents);
            Print(">");
        }
        Print("m_StomachVolume:" + m_StomachVolume);
        Print("================================");
    }
References m_StomachContents, m_StomachVolume, and Print().
ProcessNutrients()
void ProcessNutrients (float delta_time)
Definition at line 248 of file playerstomach.c.
    {
        StomachItem item;
        int stomach_items_count = m_StomachContents.Count();
        m_DigestingType = 0;
        if(stomach_items_count == 0)
            return;
        float digestion_points_per_item = (DIGESTION_POINTS / stomach_items_count) * delta_time;
        m_StomachVolume = 0;//reset, it's accumulated with each pass
        for(int i = 0; i < m_StomachContents.Count(); i ++)
        {
            item = m_StomachContents.Get(i);
            float water, energy, toxicity, volume, consumed_amount;
            int agents;
            if(item.ProcessDigestion( digestion_points_per_item, water, energy, toxicity, volume, agents, consumed_amount ))
            {
                m_StomachContents.Remove(i);
                i--;
            }
            m_StomachVolume += volume;
            m_Player.GetStatEnergy().Add(energy);
            m_Player.GetStatWater().Add(water);
            if(energy > 0)
            {
                m_DigestingType = m_DigestingType | DIGESTING_ENERGY;
            }
            if(water > 0)
            {
                m_DigestingType = m_DigestingType | DIGESTING_WATER;
            }
            DigestAgents(agents, consumed_amount);
        }
    }
References DigestAgents(), DIGESTING_ENERGY, DIGESTING_WATER, DIGESTION_POINTS, m_DigestingType, m_Player, m_StomachContents, m_StomachVolume, and StomachItem::ProcessDigestion().
Referenced by Update().
RegisterItem()
static void RegisterItem (string classname, int id) static
Definition at line 159 of file playerstomach.c.
    {
        int hash = classname.Hash();
        CHECKSUM = CHECKSUM^hash; //xor hash vs current checksum
//      Print(classname);
//      Print(CHECKSUM);
        m_NamesToIDs.Insert(classname, id);
        m_IDsToNames.Insert(id, classname);
    }
References CHECKSUM, string::Hash(), m_IDsToNames, and m_NamesToIDs.
Referenced by InitData().
SetAgentTransferFilter()
void SetAgentTransferFilter (int filter_agents)
Definition at line 149 of file playerstomach.c.
    {
        m_AgentTransferFilter;
    }
References m_AgentTransferFilter.
Update()
void Update (float delta_time)
Definition at line 243 of file playerstomach.c.
    {
        ProcessNutrients(delta_time);
    }
References ProcessNutrients().
~PlayerStomach()
void ~PlayerStomach ()
Definition at line 132 of file playerstomach.c.
    {
    }
Variable Documentation
ACCEPTABLE_FOODSTAGE_MAX
const int ACCEPTABLE_FOODSTAGE_MAX = FoodStageType.COUNT - 1
Definition at line 114 of file playerstomach.c.
Referenced by AddToStomach().
ACCEPTABLE_QUANTITY_MAX
const int ACCEPTABLE_QUANTITY_MAX = 32768
Definition at line 113 of file playerstomach.c.
Referenced by AddToStomach().
CHECKSUM
int CHECKSUM static
Definition at line 111 of file playerstomach.c.
Referenced by OnStoreLoad(), and RegisterItem().
DIGESTING_ENERGY
const int DIGESTING_ENERGY = 2
Definition at line 107 of file playerstomach.c.
Referenced by ProcessNutrients().
DIGESTING_WATER
class StomachItem DIGESTING_WATER = 1
Referenced by ProcessNutrients().
DIGESTION_POINTS
const float DIGESTION_POINTS = PlayerConstants.DIGESTION_SPEED
Definition at line 112 of file playerstomach.c.
Referenced by ProcessNutrients().
id_bit_offset
const int id_bit_offset = 4
Definition at line 110 of file playerstomach.c.
Referenced by OnStoreLoad(), and OnStoreSave().
m_AgentTransferFilter
int m_AgentTransferFilter
Definition at line 119 of file playerstomach.c.
Referenced by GetAgentTransferFilter(), and SetAgentTransferFilter().
m_Digesting
bool m_Digesting
Definition at line 120 of file playerstomach.c.
m_DigestingType
int m_DigestingType
Definition at line 121 of file playerstomach.c.
Referenced by GetDigestingType(), IsDigesting(), and ProcessNutrients().
m_IDsToNames
ref map<int, string> m_IDsToNames = new map<int, string> static
Definition at line 116 of file playerstomach.c.
Referenced by GetClassnameFromID(), and RegisterItem().
m_InitData
const bool m_InitData = PlayerStomach.InitData() static
Definition at line 117 of file playerstomach.c.
m_NamesToIDs
ref map<string, int> m_NamesToIDs = new map<string, int> static
Definition at line 115 of file playerstomach.c.
Referenced by GetIDFromClassname(), and RegisterItem().
m_Player
PlayerBase m_Player
Definition at line 122 of file playerstomach.c.
m_StomachContents
ref array<ref StomachItem> m_StomachContents = new array<ref StomachItem>
Definition at line 118 of file playerstomach.c.
Referenced by AddToStomach(), ClearContents(), GetDebugObject(), OnStoreSave(), PrintUpdate(), and ProcessNutrients().
m_StomachVolume
float m_StomachVolume
Definition at line 123 of file playerstomach.c.
Referenced by ClearContents(), GetDebugObject(), GetStomachVolume(), PrintUpdate(), and ProcessNutrients().
quantity_bit_offset
const int quantity_bit_offset = 16
Definition at line 109 of file playerstomach.c.
Referenced by OnStoreLoad(), and OnStoreSave().
STORAGE_VERSION
const int STORAGE_VERSION = 106
Definition at line 124 of file playerstomach.c.