DayzKode: P:/scripts/4_world/DayZ/classes/soundhandlers/playersoundmanager.c File Reference
playersoundmanager.c File Reference
Classes
class PlayerSoundManagerBase
Enumerations
enum eSoundHandlers { STAMINA , HUNGER , INJURY , COUNT }
Functions
void CheckAllowUpdate ()
SoundHandlerBase GetHandler (eSoundHandlers id)
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
void PlayerSoundManagerBase (PlayerBase player)
void PlayerSoundManagerClient (PlayerBase player)
void RegisterHandler (SoundHandlerBase handler)
void SetAllowUpdate (bool enable)
void Update ()
Variables
ref Timer m_ClientCharacterDistanceCheck = new Timer
class PlayerSoundManagerServer extends PlayerSoundManagerBase m_ClientCharacterTick = new Timer
ref SoundHandlerBase m_Handlers [MAX_HANDLERS_COUNT]
enum eSoundHandlers m_Player
bool m_UpdateTimerRunning
const int MAX_HANDLERS_COUNT = eSoundHandlers.COUNT
const float SOUNDS_HEARING_DISTANCE = 50
Enumeration Type Documentation
eSoundHandlers
enum eSoundHandlers
Enumerator
STAMINA
HUNGER
INJURY
COUNT
Definition at line 4 of file playersoundmanager.c.
{
    STAMINA,
    HUNGER,
    INJURY,
    //FREEZING,
    //------
    // add stuff above !
    //------
    COUNT
}
Function Documentation
CheckAllowUpdate()
void CheckAllowUpdate ()
Definition at line 138 of file playersoundmanager.c.
    {
        if( GetGame().GetPlayer() )
        {
            bool is_at_hearing_distance = vector.Distance(GetGame().GetPlayer().GetPosition(), m_Player.GetPosition()) < SOUNDS_HEARING_DISTANCE;
            if( m_UpdateTimerRunning && !is_at_hearing_distance )
            {
                SetAllowUpdate(false);
            }
            else if( !m_UpdateTimerRunning && is_at_hearing_distance )
            {
                SetAllowUpdate(true);
            }
            //PrintString("distance:" + vector.Distance(GetGame().GetPlayer().GetPosition(), m_Player.GetPosition()).ToString());
        }
    }
References vector::Distance(), GetGame(), GetPlayer(), GetPosition, m_Player, m_UpdateTimerRunning, SetAllowUpdate(), and SOUNDS_HEARING_DISTANCE.
GetHandler()
SoundHandlerBase GetHandler (eSoundHandlers id)
Definition at line 38 of file playersoundmanager.c.
    {
        return m_Handlers[id];
    }
References m_Handlers.
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
Definition at line 43 of file playersoundmanager.c.
    {
    }
PlayerSoundManagerBase()
void PlayerSoundManagerBase (PlayerBase player)
Definition at line 26 of file playersoundmanager.c.
    {
        m_Player = player;
        Init();
    }
References PlayerSoundManagerBase::Init(), and m_Player.
PlayerSoundManagerClient()
void PlayerSoundManagerClient (PlayerBase player)
Definition at line 99 of file playersoundmanager.c.
    {
        if( !GetGame().IsDedicatedServer() )
        {
            m_ClientCharacterDistanceCheck.Run(2, this, "CheckAllowUpdate", null, true);
        }
    }
References GetGame(), and m_ClientCharacterDistanceCheck.
Referenced by ManBase::Init().
RegisterHandler()
void RegisterHandler (SoundHandlerBase handler)
Definition at line 32 of file playersoundmanager.c.
    {
        int index = handler.GetID();
        m_Handlers[index] = handler;
    }
References m_Handlers.
Referenced by PlayerSoundManagerBase::Init().
SetAllowUpdate()
void SetAllowUpdate (bool enable)
Definition at line 108 of file playersoundmanager.c.
    {
        if( enable )
        {
            m_UpdateTimerRunning = true;
            m_ClientCharacterTick.Run(0.03, this, "Update", null, true);
        }
        else
        {
            m_UpdateTimerRunning = false;
            m_ClientCharacterTick.Stop();
        }
    }
References m_ClientCharacterTick, and m_UpdateTimerRunning.
Referenced by CheckAllowUpdate(), and Update().
Variable Documentation
m_ClientCharacterDistanceCheck
ref Timer m_ClientCharacterDistanceCheck = new Timer
Definition at line 85 of file playersoundmanager.c.
Referenced by PlayerSoundManagerClient().
m_ClientCharacterTick
class PlayerSoundManagerServer extends PlayerSoundManagerBase m_ClientCharacterTick = new Timer
Referenced by SetAllowUpdate().
m_Handlers
ref SoundHandlerBase m_Handlers[MAX_HANDLERS_COUNT]
Definition at line 24 of file playersoundmanager.c.
Referenced by GetHandler(), RegisterHandler(), Update(), and PlayerSoundManagerBase::Update().
m_Player
enum eSoundHandlers m_Player
Referenced by PlayerSoundManagerBase().
m_UpdateTimerRunning
bool m_UpdateTimerRunning
Definition at line 86 of file playersoundmanager.c.
Referenced by CheckAllowUpdate(), and SetAllowUpdate().
MAX_HANDLERS_COUNT
const int MAX_HANDLERS_COUNT = eSoundHandlers.COUNT
Definition at line 23 of file playersoundmanager.c.
Referenced by Update(), and PlayerSoundManagerBase::Update().
SOUNDS_HEARING_DISTANCE
const float SOUNDS_HEARING_DISTANCE = 50
Definition at line 2 of file playersoundmanager.c.
Referenced by CheckAllowUpdate().