DayzKode: P:/scripts/4_world/DayZ/classes/playerstats/playerstatspco.c File Reference
playerstatspco.c File Reference
Classes
class PCOHandlerStats
class PlayerStatsPCO_Base
class PlayerStatsPCO_v115
Enumerations
enum EPlayerStats_current : EPlayerStats_v115
enum EPlayerStats_v100 {
HEATCOMFORT , TREMOR , WET , ENERGY ,
WATER , STOMACH_SOLID , STOMACH_ENERGY , STOMACH_WATER ,
DIET , STAMINA , SPECIALTY , BLOODTYPE
}
enum EPlayerStats_v101 {
HEATCOMFORT , TREMOR , WET , ENERGY ,
WATER , STOMACH_SOLID , STOMACH_ENERGY , STOMACH_WATER ,
DIET , STAMINA , SPECIALTY , BLOODTYPE ,
TOXICITY
}
enum EPlayerStats_v106 {
HEATCOMFORT , TREMOR , WET , ENERGY ,
WATER , DIET , STAMINA , SPECIALTY ,
BLOODTYPE , TOXICITY
}
enum EPlayerStats_v115 {
HEATCOMFORT , TREMOR , WET , ENERGY ,
WATER , DIET , STAMINA , SPECIALTY ,
BLOODTYPE , TOXICITY , HEATBUFFER
}
Functions
array< ref PlayerStatBase > Get ()
PlayerStatsPCO_Base GetPCO (int version=-1)
PlayerStatBase GetStatObject (int id)
int GetVersion ()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
bool OnStoreLoad (ParamsReadContext ctx)
void OnStoreSave (ParamsWriteContext ctx)
void PCOHandlerStats ()
void RegisterPCO (PlayerStatsPCO_Base pco)
void RegisterStat (int id, PlayerStatBase stat)
void ResetAllStats ()
Variables
int m_HighestVersion
ref map< int, ref PlayerStatsPCO_Base > m_PCOs = new map<int, ref PlayerStatsPCO_Base>
ref array< ref PlayerStatBase > m_PlayerStats = new array<ref PlayerStatBase>
enum EPlayerStats_v100 PlayerStatsPCO_Base
Enumeration Type Documentation
EPlayerStats_current
enum EPlayerStats_current : EPlayerStats_v115
Definition at line 293 of file playerstatspco.c.
{
};
EPlayerStats_v100
enum EPlayerStats_v100
Enumerator
HEATCOMFORT
TREMOR
WET
ENERGY
WATER
STOMACH_SOLID
STOMACH_ENERGY
STOMACH_WATER
DIET
STAMINA
SPECIALTY
BLOODTYPE
Definition at line 118 of file playerstatspco.c.
{
    HEATCOMFORT,
    TREMOR,
    WET,
    ENERGY,
    WATER,
    STOMACH_SOLID,
    STOMACH_ENERGY,
    STOMACH_WATER,
    DIET,
    STAMINA,
    SPECIALTY,
    BLOODTYPE,
};
EPlayerStats_v101
enum EPlayerStats_v101
Enumerator
HEATCOMFORT
TREMOR
WET
ENERGY
WATER
STOMACH_SOLID
STOMACH_ENERGY
STOMACH_WATER
DIET
STAMINA
SPECIALTY
BLOODTYPE
TOXICITY
Definition at line 169 of file playerstatspco.c.
{
    HEATCOMFORT,
    TREMOR,
    WET,
    ENERGY,
    WATER,
    STOMACH_SOLID,
    STOMACH_ENERGY,
    STOMACH_WATER,
    DIET,
    STAMINA,
    SPECIALTY,
    BLOODTYPE,
    TOXICITY,
};
EPlayerStats_v106
enum EPlayerStats_v106
Enumerator
HEATCOMFORT
TREMOR
WET
ENERGY
WATER
DIET
STAMINA
SPECIALTY
BLOODTYPE
TOXICITY
Definition at line 213 of file playerstatspco.c.
{
    HEATCOMFORT,
    TREMOR,
    WET,
    ENERGY,
    WATER,
    DIET,
    STAMINA,
    SPECIALTY,
    BLOODTYPE,
    TOXICITY,
};
EPlayerStats_v115
enum EPlayerStats_v115
Enumerator
HEATCOMFORT
TREMOR
WET
ENERGY
WATER
DIET
STAMINA
SPECIALTY
BLOODTYPE
TOXICITY
HEATBUFFER
Definition at line 250 of file playerstatspco.c.
{
    HEATCOMFORT,
    TREMOR,
    WET,
    ENERGY,
    WATER,
    DIET,
    STAMINA,
    SPECIALTY,
    BLOODTYPE,
    TOXICITY,
    HEATBUFFER,
};
Function Documentation
Get()
array< ref PlayerStatBase > Get ()
Definition at line 103 of file playerstatspco.c.
    {
        return m_PlayerStats;
    }
References m_PlayerStats.
Referenced by array< Class T >::Debug(), array< Class T >::DifferentAtPosition(), array< Class T >::GetRandomElement(), array< Class T >::Invert(), Link< Class T >::IsNull(), array< ref TSelectableActionInfo >::IsSameAs(), HudDebugWinBase::OnChange(), PluginBase::OnRPCStatSet(), ManBase::OnSelectPlayer(), Link< Class T >::Ptr(), UIScriptedMenu::RandomizeCharacter(), Link< Class T >::Release(), array< ref CallQueueContext >::RemoveCalls(), map< Class TKey, Class TValue >::ReplaceKey(), PluginBase::SendRPCStats(), array< Class T >::SwapItems(), array< ref CallQueueContext >::Tick(), CallQueue::Tick(), array< TimerBase >::Tick(), LayoutHolder::UnfocusAll(), IconsContainer::UnfocusAll(), AttachmentCategoriesRow::UnfocusAll(), ComponentEnergyManager::UnplugAllDevices(), PluginBase::UpdateStatsLocal(), and array< TimerBase >::~TimerQueue().
GetPCO()
PlayerStatsPCO_Base PlayerStatsPCO_Base::GetPCO (int version = -1)
Definition at line 81 of file playerstatspco.c.
    {
        for ( int i = 0; i < m_PlayerStats.Count(); i++ )
        {
            m_PlayerStats.Get(i).OnStoreSave(ctx);
        }
    }
    bool OnStoreLoad ( ParamsReadContext ctx )
    {
        for ( int i = 0; i < m_PlayerStats.Count(); i++ )
        {
            if(!m_PlayerStats.Get(i).OnStoreLoad(ctx))
            {
                return false;
            }
        }
        return true;
    }
    array<ref PlayerStatBase> Get()
    {
        return m_PlayerStats;
    }
GetStatObject()
PlayerStatBase GetStatObject (int id)
Definition at line 72 of file playerstatspco.c.
    {
        return m_PlayerStats.Get(id);
    }
References m_PlayerStats.
Referenced by ManBase::GetStatBloodType(), ManBase::GetStatDiet(), ManBase::GetStatEnergy(), ManBase::GetStatHeatBuffer(), ManBase::GetStatHeatComfort(), ManBase::GetStatSpecialty(), ManBase::GetStatStamina(), ManBase::GetStatToxicity(), ManBase::GetStatTremor(), ManBase::GetStatWater(), and ManBase::GetStatWet().
GetVersion()
int GetVersion ()
Definition at line 65 of file playerstatspco.c.
    {
        return -1;
    }
Init()
void Init ()
Launched from 'DayZGame.DeferredInit' to make earlier access, use, and updates impossible (downside of a non-static system)
script functions
called by engine right after creation of entity
pre-init arrays
Definition at line 84 of file ppemanager.c.
    {
        //DbgPrnt("PPEDebug | PPEManager | m_ManagerInitialized: " + m_ManagerInitialized);
        if (!m_ManagerInitialized)
        {
            m_PPEMaterialUpdateQueueMap = new map<int, ref array<int>>;
            m_UpdatedMaterials = new array<int>;
            m_ExistingPostprocessRequests = new array<ref PPERequesterBase>;
            m_UpdatingRequests = new array<ref PPERequesterBase>;
            InitPPEManagerClassMap();
            GetGame().GetUpdateQueue(CALL_CATEGORY_GUI).Insert(this.Update); //can be safely and easily 'disabled' here
            m_ManagerInitialized = true;
        }
    }
OnStoreLoad()
bool OnStoreLoad (ParamsReadContext ctx)
Definition at line 91 of file playerstatspco.c.
    {
        for ( int i = 0; i < m_PlayerStats.Count(); i++ )
        {
            if(!m_PlayerStats.Get(i).OnStoreLoad(ctx))
            {
                return false;
            }
        }
        return true;
    }
References m_PlayerStats.
OnStoreSave()
void OnStoreSave (ParamsWriteContext ctx)
Definition at line 83 of file playerstatspco.c.
    {
        for ( int i = 0; i < m_PlayerStats.Count(); i++ )
        {
            m_PlayerStats.Get(i).OnStoreSave(ctx);
        }
    }
References m_PlayerStats.
PCOHandlerStats()
void PlayerStatsPCO_Base::PCOHandlerStats ()
Definition at line 62 of file playerstatspco.c.
    {
        return -1;
RegisterPCO()
void PlayerStatsPCO_Base::RegisterPCO (PlayerStatsPCO_Base pco)
Definition at line 69 of file playerstatspco.c.
    {
        return m_PlayerStats.Get(id);
    }
    void RegisterStat(int id, PlayerStatBase stat)
    {
        m_PlayerStats.InsertAt(stat, id);
RegisterStat()
void RegisterStat (int id, PlayerStatBase stat)
Definition at line 77 of file playerstatspco.c.
    {
        m_PlayerStats.InsertAt(stat, id);
        stat.Init(id/*, this*/);
    }
References PlayerStatBase::Init(), and m_PlayerStats.
Referenced by PlayerStatsPCO_Base::Init().
ResetAllStats()
void ResetAllStats ()
Definition at line 108 of file playerstatspco.c.
    {
        m_PlayerStats.Clear();
        Init();
    }
References PlayerStatsPCO_Base::Init(), and m_PlayerStats.
Variable Documentation
m_HighestVersion
int m_HighestVersion
Definition at line 60 of file playerstatspco.c.
m_PCOs
ref map<int, ref PlayerStatsPCO_Base> m_PCOs = new map<int, ref PlayerStatsPCO_Base>
Definition at line 59 of file playerstatspco.c.
m_PlayerStats
ref array<ref PlayerStatBase> m_PlayerStats = new array<ref PlayerStatBase>
Definition at line 70 of file playerstatspco.c.
Referenced by Get(), ManBase::GetPlayerStats(), GetStatObject(), ManBase::Init(), OnStoreLoad(), OnStoreSave(), RegisterStat(), and ResetAllStats().
PlayerStatsPCO_Base
class PCOHandlerStats PlayerStatsPCO_Base
Definition at line 1 of file playerstatspco.c.
    {
        Init();
    }