DayzKode: P:/scripts/4_world/DayZ/plugins/pluginbase/pluginlifespan.c File Reference
pluginlifespan.c File Reference
Enumerations
enum eBloodyHandsTypes { CLEAN = 0 , SALMONELA , JUST_BLOOD , LAST_INDEX }
Functions
bool CanMakeHandsBloody (PlayerBase player)
void ChangeFakePlaytime (PlayerBase player, int change)
string GetCurrentHeadMaterial (PlayerBase player)
string GetCurrentHeadTexture (PlayerBase player)
static PluginLifespan GetInstance ()
protected LifespanLevel GetLifespanLevel (string player_class, float age=0)
void LoadFromCfg ()
void PluginLifespan ()
void SetBloodyHands (PlayerBase player, bool show)
void SetBloodyHandsEx (PlayerBase player, eBloodyHandsTypes type)
protected void SetHandsMaterial (PlayerBase player, int material_type)
protected void SetPlayerLifespanLevel (PlayerBase player, LifespanLevel level)
void SynchBeardVisual (PlayerBase player, int state)
void SynchBloodyHandsVisual (PlayerBase player, bool has_bloody_hands)
void SynchLifespanVisual (PlayerBase player, int beard_state_visible, bool bloody_hands_visible, bool blood_type_visible, int blood_type)
void SynchShowBloodType (PlayerBase player, int blood_type)
void SynchShowBloodTypeVisual (PlayerBase player, bool show)
void UpdateBloodType (PlayerBase player, int blood_type)
void UpdateBloodTypeVisibility (PlayerBase player, bool show)
void UpdateBloodyHandsVisibility (PlayerBase player, bool show)
void UpdateBloodyHandsVisibilityEx (PlayerBase player, eBloodyHandsTypes type)
void UpdateLifespan (PlayerBase player, bool force_update=false)
protected void UpdateLifespanLevel (PlayerBase player, float player_beard, bool force_update=false)
Variables
enum eBloodyHandsTypes BEARD_EXTRA = 3
enum eBloodyHandsTypes BEARD_LARGE = 2
enum eBloodyHandsTypes BEARD_MEDIUM = 1
enum eBloodyHandsTypes BEARD_NONE = 0
enum eBloodyHandsTypes COUNT = 4
static protected const int LIFESPAN_MAX = 240
enum eBloodyHandsTypes LIFESPAN_MIN = 0
protected ref map< PlayerBase, int > m_BloodType
protected ref map< string, ref BloodyHands > m_BloodyHands
protected int m_FakePlaytime
protected ref map< string, ref array< ref LifespanLevel > > m_LifespanLevels
protected ref map< PlayerBase, ref LifespanLevel > m_PlayerCurrentLevel
Enumeration Type Documentation
eBloodyHandsTypes
enum eBloodyHandsTypes
Enumerator
CLEAN
SALMONELA
JUST_BLOOD
LAST_INDEX
Definition at line 8 of file pluginlifespan.c.
{
    CLEAN = 0,//clean needs to be 0
    SALMONELA,
    JUST_BLOOD,
    //--- ONLY LAST_INDEX BELLOW !!!
    LAST_INDEX,
}
Function Documentation
CanMakeHandsBloody()
bool CanMakeHandsBloody (PlayerBase player)
Definition at line 490 of file pluginlifespan.c.
    {
        if ( !player.FindAttachmentBySlotName( "Gloves" ) )
        {
            return true;
        }
        else
        {
            return false;
        }
    }
Referenced by UpdateBloodyHandsVisibility(), and UpdateBloodyHandsVisibilityEx().
ChangeFakePlaytime()
void ChangeFakePlaytime (PlayerBase player, int change)
Definition at line 207 of file pluginlifespan.c.
    {
        if ( !GetGame().IsMultiplayer() )
        {
            m_FakePlaytime = change;
            UpdateLifespan( player, true );
        }
    }
References GetGame(), m_FakePlaytime, and UpdateLifespan().
GetCurrentHeadMaterial()
string GetCurrentHeadMaterial (PlayerBase player)
Definition at line 545 of file pluginlifespan.c.
    {
        if ( m_PlayerCurrentLevel.Contains(player) )
        {
            LifespanLevel current_level = m_PlayerCurrentLevel.Get( player );
            return current_level.GetMaterialName();
        }
        return "";
    }
References LifespanLevel::GetMaterialName(), and m_PlayerCurrentLevel.
GetCurrentHeadTexture()
string GetCurrentHeadTexture (PlayerBase player)
Definition at line 535 of file pluginlifespan.c.
    {
        if ( m_PlayerCurrentLevel.Contains(player) )
        {
            LifespanLevel current_level = m_PlayerCurrentLevel.Get( player );
            return current_level.GetTextureName();
        }
        return "";
    }
References LifespanLevel::GetTextureName(), and m_PlayerCurrentLevel.
GetInstance()
static PluginLifespan GetInstance () static
Definition at line 40 of file pluginlifespan.c.
    {
        return PluginLifespan.Cast( GetPlugin(PluginLifespan) );
    }
References GetPlugin(), and PluginLifespan().
GetLifespanLevel()
protected LifespanLevel GetLifespanLevel (string player_class, float age = 0)
Definition at line 276 of file pluginlifespan.c.
    {
        array< ref LifespanLevel> lifespan_levels = m_LifespanLevels.Get( player_class );
        if ( lifespan_levels != NULL )
        {
            for ( int i = lifespan_levels.Count() - 1; i >= 0; i-- )
            {
                LifespanLevel level = lifespan_levels.Get( i );
                if ( age >= level.GetThreshold() )
                {
                    return level;
                }
            }
        }
        return NULL;
    }
References LifespanLevel::GetThreshold(), and m_LifespanLevels.
Referenced by UpdateLifespanLevel().
LoadFromCfg()
void LoadFromCfg ()
Definition at line 56 of file pluginlifespan.c.
    {
        m_LifespanLevels = new map<string, ref array< ref LifespanLevel>>;
        m_BloodyHands = new map<string, ref BloodyHands>;
        const int LIFESPAN_LENGTH = LIFESPAN_MAX - LIFESPAN_MIN;
        //cfg_name = 'CfgVehicles'
        //  config_name = 'CfgVehicles'
        //cfg_class_count = 2348
        //  config_count = 2348
        //cfg_class_name = 'SurvivorMale_Base'
        //  survivor_name = 'SurvivorMale_Base'
        //cfg_class_fullname = 'CfgVehicles SurvivorMale_Base'
        //  survivor_path = 'CfgVehicles SurvivorMale_Base'
        //cfg_class_member_count = 10
        //  survivor_lifespan_count = 10
        //cfg_class_member_name = 'Lifespan'
        //  survivor_lifespan_name = 'Lifespan'
        //cfg_class_member_fullname = 'CfgVehicles SurvivorMale_Base Lifespan';
        //  survivor_lifespan_path = 'CfgVehicles SurvivorMale_Base Lifespan';
        //cfg_class_member_member_count = 1
        //  survivor_lifespan_beard_count = 1
        //cfg_class_member_member_name = 'Beard'
        //  survivor_lifespan_beard_name = 'Beard'
        //cfg_class_member_member_fullname = 'CfgVehicles SurvivorMale_Base Lifespan Beard'
        //  survivor_lifespan_beard_path = 'CfgVehicles SurvivorMale_Base Lifespan Beard'
        //cfg_class_member_member_variable_name = 'mat'
        //  survivor_lifespan_beard_material_name = 'mat'
        //cfg_class_member_member_variable_fullname = 'CfgVehicles SurvivorMale_Base Lifespan Beard mat'
        //  survivor_lifespan_beard_material_path = 'CfgVehicles SurvivorMale_Base Lifespan Beard mat'
        string config_name = "CfgVehicles";
        int config_count = GetGame().ConfigGetChildrenCount( config_name );
        int i, j, k, l, m;
        //Print( "config_count: " + config_count );
        for ( i = 0; i < config_count; i++ )
        {
            string survivor_name = "";
            GetGame().ConfigGetChildName( config_name, i, survivor_name );
            if ( survivor_name != "" && survivor_name != "access" )
            {
                if ( GetGame().IsKindOf(survivor_name, "SurvivorMale_Base")  ||  GetGame().IsKindOf(survivor_name, "SurvivorFemale_Base") )
                {
                    string survivor_path = config_name + " " + survivor_name;
                    int survivor_lifespan_count = GetGame().ConfigGetChildrenCount( survivor_path );
                    //Print( "survivor_path: " + survivor_path );
                    for ( j = 0; j < survivor_lifespan_count; j++ )
                    {
                        string survivor_lifespan_name = "";
                        GetGame().ConfigGetChildName( survivor_path, j, survivor_lifespan_name );
                        string survivor_lifespan_path = survivor_path + " " + survivor_lifespan_name;
                        if ( survivor_lifespan_name == "Lifespan" )
{
                            int survivor_lifespan_beard_count = GetGame().ConfigGetChildrenCount( survivor_lifespan_path );
                            for ( k = 0; k < survivor_lifespan_beard_count; k++ )
{
                                string survivor_lifespan_beard_name = "";
                                GetGame().ConfigGetChildName( survivor_lifespan_path, k, survivor_lifespan_beard_name );
                                string survivor_lifespan_beard_path = survivor_lifespan_path + " " + survivor_lifespan_beard_name;
                                if ( survivor_lifespan_beard_name == "Beard" )
{
                                    ref TStringArray materials = new TStringArray;
                                    int cfg_class_member_member_variable_count = GetGame().ConfigGetChildrenCount( survivor_lifespan_beard_path );
                                    for ( l = 0; l < cfg_class_member_member_variable_count; l++ )
{
                                        string survivor_lifespan_beard_material_name = "";
                                        GetGame().ConfigGetChildName( survivor_lifespan_beard_path, l, survivor_lifespan_beard_material_name );
                                        string survivor_lifespan_beard_material_path = survivor_lifespan_beard_path + " " + survivor_lifespan_beard_material_name;
                                        if ( survivor_lifespan_beard_material_name == "mat" )
{
                                            GetGame().ConfigGetTextArray( survivor_lifespan_beard_material_path, materials );
                                            ref array<ref LifespanLevel> lifespan_levels = new array< ref LifespanLevel>;
                                            int level_count = materials.Count() / 2;
                                            for ( m = 0; m < level_count; m++ )
{
                                                int tex = m*2;
                                                int mat = ((m*2)+1);
                                                if ( mat < materials.Count() )
{
                                                    float threshold = (((float)m / (float)(level_count - 1)) * (float)LIFESPAN_LENGTH) + (float)LIFESPAN_MIN;
                                                    lifespan_levels.Insert( new LifespanLevel(m, threshold, materials.Get(tex), materials.Get(mat)) );
                                                    //Print("material a textura a threshold: " + materials.Get(tex) + " " + materials.Get(mat) + " " + threshold );
                                                }
                                            }
                                            if ( lifespan_levels.Count() > 0 )
{
                                                m_LifespanLevels.Set( survivor_name, lifespan_levels );
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else if ( survivor_lifespan_name == "BloodyHands" )
{
                            string bloody_material, normal_material;
                            string path_normal = survivor_lifespan_path + " mat_normal";
                            string path_bloody = survivor_lifespan_path + " mat_blood";
                            GetGame().ConfigGetText(path_normal, normal_material);
                            GetGame().ConfigGetText(path_bloody, bloody_material);
                            m_BloodyHands.Set( survivor_name, new BloodyHands(normal_material, bloody_material) );
                        }
                    }
                }
            }
        }
        /*for ( int cl = 0; cl < m_LifespanLevels.Count(); cl++ )
        {
            string class_name = m_LifespanLevels.GetKey( cl );
            array<ref LifespanLevel> levels = m_LifespanLevels.GetElement( cl );
            Print( class_name );
            for ( int ll = 0; ll < levels.Count(); ll++)
            {
                Print( "lvl: " + levels.Get( ll ).GetLevel() );
                Print( "treshold: " + levels.Get( ll ).GetThreshold() );
                Print( "texture: " + levels.Get( ll ).GetTextureName() );
                Print( "material: " + levels.Get( ll ).GetMaterialName() );
            }
        }*/
    }
References CGame::ConfigGetChildName(), CGame::ConfigGetChildrenCount(), CGame::ConfigGetText(), CGame::ConfigGetTextArray(), GetGame(), IsKindOf(), LIFESPAN_MAX, LIFESPAN_MIN, m_BloodyHands, and m_LifespanLevels.
PluginLifespan()
void PluginLifespan ()
Definition at line 45 of file pluginlifespan.c.
    {
        LoadFromCfg();
        m_PlayerCurrentLevel = new map<PlayerBase, ref LifespanLevel>;
        m_BloodType = new map<PlayerBase, int>;
        m_FakePlaytime = 0;
    }
References PluginBase::LoadFromCfg(), m_BloodType, m_FakePlaytime, and m_PlayerCurrentLevel.
Referenced by ActionEatMeat::ApplyModifiers(), RecipeBase::Do(), GetInstance(), ManBase::Init(), SymptomBase::OnAnimationFinish(), SymptomBase::OnAnimationStart(), ActionInteractLoopBase::OnEndServer(), ActionWashHandsItem::OnEndServer(), ActionSkinning::OnFinishProgressServer(), ActionWashHandsWater::OnFinishProgressServer(), ActionWashHandsWell::OnFinishProgressServer(), ActionTestBloodSelf::OnFinishProgressServer(), ActionTestBloodTarget::OnFinishProgressServer(), ActionTestBloodTarget::OnStartServer(), ManBase::ResetPlayer(), and MissionBase::UpdatePlayersStats().
SetBloodyHands()
void SetBloodyHands (PlayerBase player, bool show)
Definition at line 454 of file pluginlifespan.c.
    {
        player.SetBloodyHands( show );
        if ( show )
        {
            SetHandsMaterial( player, BloodyHands.MATERIAL_TYPE_BLOODY );
        }
        else
        {
            SetHandsMaterial( player, BloodyHands.MATERIAL_TYPE_NORMAL );
        }
    }
References BloodyHands::MATERIAL_TYPE_BLOODY, BloodyHands::MATERIAL_TYPE_NORMAL, and SetHandsMaterial().
Referenced by UpdateBloodyHandsVisibility().
SetBloodyHandsEx()
void SetBloodyHandsEx (PlayerBase player, eBloodyHandsTypes type)
Definition at line 439 of file pluginlifespan.c.
    {
        player.SetBloodyHandsEx( type );
        if ( type )
        {
            SetHandsMaterial( player, BloodyHands.MATERIAL_TYPE_BLOODY );
        }
        else
        {
            SetHandsMaterial( player, BloodyHands.MATERIAL_TYPE_NORMAL );
        }
    }
References BloodyHands::MATERIAL_TYPE_BLOODY, BloodyHands::MATERIAL_TYPE_NORMAL, and SetHandsMaterial().
Referenced by UpdateBloodyHandsVisibilityEx().
SetHandsMaterial()
protected void SetHandsMaterial (PlayerBase player, int material_type)
Definition at line 468 of file pluginlifespan.c.
    {
        string player_class = player.GetPlayerClass();
        int slot_id;
        EntityAI eai;
        if ( m_BloodyHands.Contains(player_class))
        {
            slot_id = InventorySlots.GetSlotIdFromString("Gloves");
            eai = player.GetInventory().FindPlaceholderForSlot( slot_id );
            if (eai)
            {
                eai.SetObjectMaterial( 0, m_BloodyHands.Get(player_class).GetMaterial(material_type) );
            }
        }
        else
        {
            //Print("Error! Player class <" + player_class + "> does not contain valid configuration for bloody hands!");
        }
    }
References InventorySlots::GetSlotIdFromString(), and m_BloodyHands.
Referenced by SetBloodyHands(), and SetBloodyHandsEx().
SetPlayerLifespanLevel()
protected void SetPlayerLifespanLevel (PlayerBase player, LifespanLevel level)
Definition at line 296 of file pluginlifespan.c.
    {
        if (player.m_CorpseState != 0)
            return;
        int slot_id = InventorySlots.GetSlotIdFromString("Head");
        EntityAI players_head = player.GetInventory().FindPlaceholderForSlot( slot_id );
        if( players_head )
        {
            switch(level.GetLevel())
            {
                case LifeSpanState.BEARD_NONE:
                {
                    players_head.SetObjectTexture( 0, "");
                    players_head.SetObjectMaterial( 0, "");
                    player.SetFaceTexture( level.GetTextureName() );
                    player.SetFaceMaterial( level.GetMaterialName() );
                    player.SetLifeSpanStateVisible(LifeSpanState.BEARD_NONE);
                    //Print("LifeSpanState.BEARD_NONE");
                    break;
                }
                case LifeSpanState.BEARD_MEDIUM:
                {
                    players_head.SetObjectTexture( 0, "");
                    players_head.SetObjectMaterial( 0, "");
                    player.SetFaceTexture( level.GetTextureName() );
                    player.SetFaceMaterial( level.GetMaterialName() );
                    player.SetLifeSpanStateVisible(LifeSpanState.BEARD_MEDIUM);
                    //Print("LifeSpanState.BEARD_MEDIUM");
                    break;
                }
                case LifeSpanState.BEARD_LARGE:
                {
                    players_head.SetObjectTexture( 0, "");
                    players_head.SetObjectMaterial( 0, "");
                    player.SetFaceTexture( level.GetTextureName() );
                    player.SetFaceMaterial( level.GetMaterialName() );
                    player.SetLifeSpanStateVisible(LifeSpanState.BEARD_LARGE);
                    //Print("LifeSpanState.BEARD_LARGE");
                    break;
                }
                case LifeSpanState.BEARD_EXTRA:
                {
                    players_head.SetObjectTexture( 0, level.GetTextureName() );
                    players_head.SetObjectMaterial( 0, level.GetMaterialName() );
                    array< ref LifespanLevel> lifespan_levels = m_LifespanLevels.Get( player.GetPlayerClass() );
                    LifespanLevel prev_level = lifespan_levels.Get(LifeSpanState.BEARD_LARGE);
                    player.SetFaceTexture( prev_level.GetTextureName() );
                    player.SetFaceMaterial( prev_level.GetMaterialName() );
                    player.SetLifeSpanStateVisible(LifeSpanState.BEARD_EXTRA);
                    //Print("LifeSpanState.BEARD_EXTRA");
                    break;
                }
                default:
                {
                    Print("Lifespan state missing");
                    break;
                }
            }
        }
    }
References LifespanLevel::GetLevel(), LifespanLevel::GetMaterialName(), InventorySlots::GetSlotIdFromString(), LifespanLevel::GetTextureName(), m_LifespanLevels, and Print().
Referenced by UpdateLifespanLevel().
SynchBeardVisual()
void SynchBeardVisual (PlayerBase player, int state)
Definition at line 370 of file pluginlifespan.c.
    {
        float player_beard;
        switch(state)
        {
            case LifeSpanState.BEARD_NONE:
            {
                // first out of 4 states
                player_beard = LIFESPAN_MIN;
                break;
            }
            case LifeSpanState.BEARD_MEDIUM:
            {
                // second out of 4 states
                player_beard = LIFESPAN_MAX/3;
                break;
            }
            case LifeSpanState.BEARD_LARGE:
            {
                // third out of 4 states
                player_beard = LIFESPAN_MAX/1.5;
                break;
            }
            case LifeSpanState.BEARD_EXTRA:
            {
                // fourth out of 4 states
                player_beard = LIFESPAN_MAX;
                break;
            }
            default:
            {
                Print("Lifespan state missing");
                break;
            }
        }
        UpdateLifespanLevel( player, player_beard, true );
    }
References LIFESPAN_MAX, LIFESPAN_MIN, Print(), and UpdateLifespanLevel().
Referenced by SynchLifespanVisual().
SynchBloodyHandsVisual()
void SynchBloodyHandsVisual (PlayerBase player, bool has_bloody_hands)
Definition at line 433 of file pluginlifespan.c.
    {
        UpdateBloodyHandsVisibility( player, has_bloody_hands );
    }
References UpdateBloodyHandsVisibility().
Referenced by SynchLifespanVisual().
SynchLifespanVisual()
void SynchLifespanVisual (PlayerBase player, int beard_state_visible, bool bloody_hands_visible, bool blood_type_visible, int blood_type)
Definition at line 199 of file pluginlifespan.c.
    {
        SynchBeardVisual( player, beard_state_visible );
        SynchBloodyHandsVisual( player, bloody_hands_visible );
        SynchShowBloodTypeVisual( player, blood_type_visible );
        SynchShowBloodType( player, blood_type );
    }
References SynchBeardVisual(), SynchBloodyHandsVisual(), SynchShowBloodType(), and SynchShowBloodTypeVisual().
SynchShowBloodType()
void SynchShowBloodType (PlayerBase player, int blood_type)
Definition at line 526 of file pluginlifespan.c.
    {
        UpdateBloodType( player, blood_type );
    }
References UpdateBloodType().
Referenced by SynchLifespanVisual().
SynchShowBloodTypeVisual()
void SynchShowBloodTypeVisual (PlayerBase player, bool show)
Definition at line 521 of file pluginlifespan.c.
    {
        UpdateBloodTypeVisibility( player, show );
    }
References UpdateBloodTypeVisibility().
Referenced by SynchLifespanVisual().
UpdateBloodType()
void UpdateBloodType (PlayerBase player, int blood_type)
Definition at line 516 of file pluginlifespan.c.
    {
        player.SetBloodType( blood_type );
    }
Referenced by SynchShowBloodType().
UpdateBloodTypeVisibility()
void UpdateBloodTypeVisibility (PlayerBase player, bool show)
Definition at line 506 of file pluginlifespan.c.
    {
        player.SetBloodTypeVisible( show );
        if ( player.m_Hud )
        {
            player.m_Hud.UpdateBloodName();
        }
    }
Referenced by SynchShowBloodTypeVisual().
UpdateBloodyHandsVisibility()
void UpdateBloodyHandsVisibility (PlayerBase player, bool show)
Definition at line 425 of file pluginlifespan.c.
    {
        if ( CanMakeHandsBloody( player ) )
        {
            SetBloodyHands( player, show );
        }
    }
References CanMakeHandsBloody(), and SetBloodyHands().
Referenced by SynchBloodyHandsVisual().
UpdateBloodyHandsVisibilityEx()
void UpdateBloodyHandsVisibilityEx (PlayerBase player, eBloodyHandsTypes type)
Definition at line 417 of file pluginlifespan.c.
    {
        if ( CanMakeHandsBloody( player ) )
        {
            SetBloodyHandsEx( player, type );
        }
    }
References CanMakeHandsBloody(), and SetBloodyHandsEx().
UpdateLifespan()
void UpdateLifespan (PlayerBase player, bool force_update = false)
Definition at line 220 of file pluginlifespan.c.
    {
        if ( player != NULL )
        {
            // NEW STATS API
            if ( GetGame().IsMultiplayer() && GetGame().IsServer() )
            {
                float player_playtime = player.StatGet("playtime");
            }
            else
            {
                player_playtime = m_FakePlaytime;
            }
            float player_beard = player_playtime - player.GetLastShavedSeconds();
            player_beard = player_beard / 60.0;
            UpdateLifespanLevel( player, player_beard, force_update );
        }
    }
References GetGame(), m_FakePlaytime, and UpdateLifespanLevel().
Referenced by ChangeFakePlaytime().
UpdateLifespanLevel()
protected void UpdateLifespanLevel (PlayerBase player, float player_beard, bool force_update = false)
Definition at line 241 of file pluginlifespan.c.
    {
        if ( !player.IsAlive() )
            return;
        if ( m_PlayerCurrentLevel.Contains(player) )
        {
            LifespanLevel current_level = m_PlayerCurrentLevel.Get( player );
            if ( player_beard > current_level.GetThreshold() || force_update )
            {
                LifespanLevel next_level = GetLifespanLevel( player.GetPlayerClass(), player_beard );
                if ( next_level != NULL )
                {
                    SetPlayerLifespanLevel( player, next_level );
                    m_PlayerCurrentLevel.Set( player, next_level );
                }
            }
        }
        else
        {
            if ( m_LifespanLevels.Contains( player.GetPlayerClass() ) )
            {
                LifespanLevel level = GetLifespanLevel( player.GetPlayerClass(), player_beard );
                if ( level != NULL )
                {
                    SetPlayerLifespanLevel( player, level );
                    m_PlayerCurrentLevel.Set( player, level );
                }
            }
        }
    }
References GetLifespanLevel(), LifespanLevel::GetThreshold(), m_LifespanLevels, m_PlayerCurrentLevel, and SetPlayerLifespanLevel().
Referenced by SynchBeardVisual(), and UpdateLifespan().
Variable Documentation
BEARD_EXTRA
enum eBloodyHandsTypes BEARD_EXTRA = 3
BEARD_LARGE
enum eBloodyHandsTypes BEARD_LARGE = 2
BEARD_MEDIUM
enum eBloodyHandsTypes BEARD_MEDIUM = 1
BEARD_NONE
enum eBloodyHandsTypes BEARD_NONE = 0
COUNT
enum eBloodyHandsTypes COUNT = 4
LIFESPAN_MAX
protected const int LIFESPAN_MAX = 240 static
Definition at line 29 of file pluginlifespan.c.
Referenced by LoadFromCfg(), and SynchBeardVisual().
LIFESPAN_MIN
enum eBloodyHandsTypes LIFESPAN_MIN = 0
Referenced by LoadFromCfg(), and SynchBeardVisual().
m_BloodType
protected ref map<PlayerBase, int> m_BloodType
Definition at line 35 of file pluginlifespan.c.
Referenced by ManBase::GetBloodType(), ManBase::Init(), Hud::Init(), ManBase::OnPlayerLoaded(), ManBase::OnStoreLoadLifespan(), ManBase::OnStoreSaveLifespan(), ManBase::OnVariablesSynchronized(), PluginLifespan(), ManBase::SetBloodType(), and Hud::UpdateBloodName().
m_BloodyHands
protected ref map<string, ref BloodyHands> m_BloodyHands
Definition at line 34 of file pluginlifespan.c.
Referenced by LoadFromCfg(), and SetHandsMaterial().
m_FakePlaytime
protected int m_FakePlaytime
Definition at line 30 of file pluginlifespan.c.
Referenced by ChangeFakePlaytime(), PluginLifespan(), and UpdateLifespan().
m_LifespanLevels
protected ref map<string, ref array< ref LifespanLevel> > m_LifespanLevels
Definition at line 33 of file pluginlifespan.c.
Referenced by GetLifespanLevel(), LoadFromCfg(), SetPlayerLifespanLevel(), and UpdateLifespanLevel().
m_PlayerCurrentLevel
protected ref map<PlayerBase, ref LifespanLevel> m_PlayerCurrentLevel
Definition at line 32 of file pluginlifespan.c.
Referenced by GetCurrentHeadMaterial(), GetCurrentHeadTexture(), PluginLifespan(), and UpdateLifespanLevel().